CMaNGOS_WoTLK: AnticheatChatCommandsFunctions.h File Reference
AnticheatChatCommandsFunctions.h File Reference
Functions
bool HandleAnticheatInfoCommand (char *args)
bool HandleAnticheatEnableCommand (char *args)
bool HandleAnticheatSilenceCommand (char *args)
bool HandleAnticheatUnsilenceCommand (char *args)
bool HandleAnticheatSpaminfoCommand (char *args)
bool HandleAnticheatCheatinformCommand (char *args)
bool HandleAnticheatSpaminformCommand (char *args)
bool HandleAnticheatBlacklistCommand (char *args)
bool HandleAnticheatDebugExtrapCommand (char *args)
bool HandleAnticheatFingerprintListCommand (char *args)
bool HandleAnticheatFingerprintHistoryCommand (char *args)
bool HandleAnticheatFingerprintAHistoryCommand (char *args)
Function Documentation
HandleAnticheatBlacklistCommand()
bool ChatHandler::HandleAnticheatBlacklistCommand (char * args)
Definition at line 238 of file anticheatchatcommandsfunctions.cpp.
References sAntispamMgr, and ChatHandler::SendSysMessage().
HandleAnticheatCheatinformCommand()
bool ChatHandler::HandleAnticheatCheatinformCommand (char * args)
Definition at line 194 of file anticheatchatcommandsfunctions.cpp.
References ACCOUNT_FLAG_SHOW_ANTICHEAT, WorldSession::AddAccountFlag(), WorldSession::GetAccountId(), ChatHandler::GetSession(), WorldSession::HasAccountFlag(), LoginDatabase, Database::PExecute(), WorldSession::RemoveAccountFlag(), and ChatHandler::SendSysMessage().
HandleAnticheatDebugExtrapCommand()
bool ChatHandler::HandleAnticheatDebugExtrapCommand (char * args)
Definition at line 260 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractUInt32Base(), GetAnticheatLib(), HOUR, ChatHandler::PSendSysMessage(), and ChatHandler::SendSysMessage().
HandleAnticheatEnableCommand()
bool ChatHandler::HandleAnticheatEnableCommand (char * args)
Definition at line 31 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::PSendSysMessage().
HandleAnticheatFingerprintAHistoryCommand()
bool ChatHandler::HandleAnticheatFingerprintAHistoryCommand (char * args)
Definition at line 158 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractUInt32Base(), Field::GetCppString(), Field::GetUInt32(), LoginDatabase, Database::PQuery(), ChatHandler::PSendSysMessage(), and sAnticheatConfig.
HandleAnticheatFingerprintHistoryCommand()
bool ChatHandler::HandleAnticheatFingerprintHistoryCommand (char * args)
Definition at line 123 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractUInt32Base(), Field::GetCppString(), Field::GetUInt32(), LoginDatabase, Database::PQuery(), ChatHandler::PSendSysMessage(), and sAnticheatConfig.
HandleAnticheatFingerprintListCommand()
bool ChatHandler::HandleAnticheatFingerprintListCommand (char * args)
Definition at line 81 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ChatHandler(), World::ExecuteForAllSessions(), ChatHandler::ExtractUInt32Base(), WorldSession::GetAnticheat(), NamreebAnticheat::SessionAnticheat::GetFingerprint(), ChatHandler::GetSession(), and sWorld.
HandleAnticheatInfoCommand()
bool ChatHandler::HandleAnticheatInfoCommand (char * args)
Definition at line 10 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractPlayerTarget(), WorldSession::GetAnticheat(), Object::GetGuidStr(), Player::GetSession(), and ChatHandler::PSendSysMessage().
HandleAnticheatSilenceCommand()
bool ChatHandler::HandleAnticheatSilenceCommand (char * args)
Definition at line 37 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractUInt32Base(), ChatHandler::PSendSysMessage(), and sAntispamMgr.
HandleAnticheatSpaminfoCommand()
bool ChatHandler::HandleAnticheatSpaminfoCommand (char * args)
Definition at line 51 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractPlayerTarget(), WorldSession::GetAnticheat(), Player::GetSession(), sAntispamMgr, ChatHandler::SendSysMessage(), and sObjectMgr.
HandleAnticheatSpaminformCommand()
bool ChatHandler::HandleAnticheatSpaminformCommand (char * args)
Definition at line 216 of file anticheatchatcommandsfunctions.cpp.
References ACCOUNT_FLAG_SHOW_ANTISPAM, WorldSession::AddAccountFlag(), WorldSession::GetAccountId(), ChatHandler::GetSession(), WorldSession::HasAccountFlag(), LoginDatabase, Database::PExecute(), WorldSession::RemoveAccountFlag(), and ChatHandler::SendSysMessage().
HandleAnticheatUnsilenceCommand()
bool ChatHandler::HandleAnticheatUnsilenceCommand (char * args)
Definition at line 246 of file anticheatchatcommandsfunctions.cpp.
References ChatHandler::ExtractUInt32Base(), ChatHandler::PSendSysMessage(), and sAntispamMgr.