CMaNGOS_WoTLK: arathi_highlands.cpp File Reference
arathi_highlands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_professor_phizzlethorpeAI
struct npc_kineloryAI
Enumerations
enum {
SAY_PROGRESS_1 = -1000264 , SAY_PROGRESS_2 = -1000265 , SAY_PROGRESS_3 = -1000266 , EMOTE_PROGRESS_4 = -1000267 ,
SAY_AGGRO = -1000268 , SAY_PROGRESS_5 = -1000269 , SAY_PROGRESS_6 = -1000270 , SAY_PROGRESS_7 = -1000271 ,
EMOTE_PROGRESS_8 = -1000272 , SAY_PROGRESS_9 = -1000273 , QUEST_SUNKEN_TREASURE = 665 , ENTRY_VENGEFUL_SURGE = 2776
}
enum {
SAY_START = -1000948 , SAY_REACH_BOTTOM = -1000949 , SAY_AGGRO_KINELORY = -1000950 , SAY_AGGRO_JORELL = -1000951 ,
SAY_WATCH_BACK = -1000952 , EMOTE_BELONGINGS = -1000953 , SAY_DATA_FOUND = -1000954 , SAY_ESCAPE = -1000955 ,
SAY_FINISH = -1000956 , EMOTE_HAND_PACK = -1000957 , SPELL_REJUVENATION = 3627 , SPELL_BEAR_FORM = 4948 ,
NPC_JORELL = 2733 , NPC_QUAE = 2712 , QUEST_HINTS_NEW_PLAGUE = 660
}
Functions
bool QuestAccept_npc_professor_phizzlethorpe (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_professor_phizzlethorpe (Creature *pCreature)
UnitAI * GetAI_npc_kinelory (Creature *pCreature)
bool QuestAccept_npc_kinelory (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_arathi_highlands ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PROGRESS_1
SAY_PROGRESS_2
SAY_PROGRESS_3
EMOTE_PROGRESS_4
SAY_AGGRO
SAY_PROGRESS_5
SAY_PROGRESS_6
SAY_PROGRESS_7
EMOTE_PROGRESS_8
SAY_PROGRESS_9
QUEST_SUNKEN_TREASURE
ENTRY_VENGEFUL_SURGE
Definition at line 36 of file arathi_highlands.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_REACH_BOTTOM
SAY_AGGRO_KINELORY
SAY_AGGRO_JORELL
SAY_WATCH_BACK
EMOTE_BELONGINGS
SAY_DATA_FOUND
SAY_ESCAPE
SAY_FINISH
EMOTE_HAND_PACK
SPELL_REJUVENATION
SPELL_BEAR_FORM
NPC_JORELL
NPC_QUAE
QUEST_HINTS_NEW_PLAGUE
Definition at line 122 of file arathi_highlands.cpp.
Function Documentation
AddSC_arathi_highlands()
void AddSC_arathi_highlands ()
Definition at line 253 of file arathi_highlands.cpp.
References Script::GetAI, GetAI_npc_kinelory(), GetAI_npc_professor_phizzlethorpe(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_kinelory(), QuestAccept_npc_professor_phizzlethorpe(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_kinelory()
UnitAI* GetAI_npc_kinelory (Creature * pCreature)
Definition at line 240 of file arathi_highlands.cpp.
Referenced by AddSC_arathi_highlands().
GetAI_npc_professor_phizzlethorpe()
UnitAI* GetAI_npc_professor_phizzlethorpe (Creature * pCreature)
Definition at line 113 of file arathi_highlands.cpp.
Referenced by AddSC_arathi_highlands().
QuestAccept_npc_kinelory()
bool QuestAccept_npc_kinelory (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 245 of file arathi_highlands.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_HINTS_NEW_PLAGUE, and UnitAI::SendAIEvent().
Referenced by AddSC_arathi_highlands().
QuestAccept_npc_professor_phizzlethorpe()
bool QuestAccept_npc_professor_phizzlethorpe (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 100 of file arathi_highlands.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_SUNKEN_TREASURE, SAY_PROGRESS_1, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_arathi_highlands().