CMaNGOS_WoTLK: arcatraz.cpp File Reference
arcatraz.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "arcatraz.h"
Enumerations
enum {
SAY_SOCCOTHRATES_AGGRO = -1552039 , SAY_SOCCOTHRATES_DEATH = -1552043 , YELL_MELLICHAR_INTRO1 = -1552023 , YELL_MELLICHAR_INTRO2 = -1552024 ,
YELL_MELLICHAR_RELEASE1 = -1552025 , YELL_MELLICHAR_RELEASE2 = -1552026 , YELL_MELLICHAR_RELEASE3 = -1552027 , YELL_MELLICHAR_RELEASE4 = -1552028 ,
YELL_MELLICHAR_RELEASE5 = -1552029 , YELL_MELLICAR_WELCOME = -1552030 , SAY_SKYRISS_INTRO = -1552000 , SAY_SKYRISS_AGGRO = -1552001 ,
SAY_MILLHOUSE_COMPLETE = -1552022 , SPELL_TARGET_BETA = 36854 , SPELL_TARGET_ALPHA = 36856 , SPELL_TARGET_DELTA = 36857 ,
SPELL_TARGET_GAMMA = 36858 , SPELL_SIMPLE_TELEPORT = 12980 , SPELL_MIND_REND = 36859 , SPELL_QUIET_SUICIDE = 3617 ,
QUEST_TRIAL_OF_THE_NAARU_TENACITY = 10886
}
Functions
InstanceData * GetInstanceData_instance_arcatraz (Map *pMap)
void AddSC_instance_arcatraz ()
Variables
static const DialogueEntry aArcatrazDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SOCCOTHRATES_AGGRO
SAY_SOCCOTHRATES_DEATH
YELL_MELLICHAR_INTRO1
YELL_MELLICHAR_INTRO2
YELL_MELLICHAR_RELEASE1
YELL_MELLICHAR_RELEASE2
YELL_MELLICHAR_RELEASE3
YELL_MELLICHAR_RELEASE4
YELL_MELLICHAR_RELEASE5
YELL_MELLICAR_WELCOME
SAY_SKYRISS_INTRO
SAY_SKYRISS_AGGRO
SAY_MILLHOUSE_COMPLETE
SPELL_TARGET_BETA
SPELL_TARGET_ALPHA
SPELL_TARGET_DELTA
SPELL_TARGET_GAMMA
SPELL_SIMPLE_TELEPORT
SPELL_MIND_REND
SPELL_QUIET_SUICIDE
QUEST_TRIAL_OF_THE_NAARU_TENACITY
Definition at line 34 of file arcatraz.cpp.
Function Documentation
AddSC_instance_arcatraz()
void AddSC_instance_arcatraz ()
Definition at line 519 of file arcatraz.cpp.
References Script::GetInstanceData, GetInstanceData_instance_arcatraz(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_arcatraz()
InstanceData* GetInstanceData_instance_arcatraz (Map * pMap)
Definition at line 514 of file arcatraz.cpp.
Referenced by AddSC_instance_arcatraz().
Variable Documentation
aArcatrazDialogue
const DialogueEntry aArcatrazDialogue[] static
Initial value:
=
{
    {TYPE_DALLIAH,            0,             5000},
    {SAY_SOCCOTHRATES_AGGRO,  NPC_SOCCOTHRATES, 0},
    {TYPE_SOCCOTHRATES,       0,             5000},
    {SAY_SOCCOTHRATES_DEATH,  NPC_SOCCOTHRATES, 0},
    {YELL_MELLICHAR_INTRO1,   NPC_MELLICHAR, 22000},
    {YELL_MELLICHAR_INTRO2,   NPC_MELLICHAR, 7000},
    {SPELL_TARGET_ALPHA,      0,             7000},
    {YELL_MELLICHAR_RELEASE1, NPC_MELLICHAR, 0},
    {YELL_MELLICHAR_RELEASE2, NPC_MELLICHAR, 7000},
    {SPELL_TARGET_BETA,       0,             7000},
    {TYPE_WARDEN_2,           0,             0},
    {YELL_MELLICHAR_RELEASE3, NPC_MELLICHAR, 7000},
    {SPELL_TARGET_DELTA,      0,             7000},
    {TYPE_WARDEN_3,           0,             0},
    {YELL_MELLICHAR_RELEASE4, NPC_MELLICHAR, 7000},
    {SPELL_TARGET_GAMMA,      0,             7000},
    {TYPE_WARDEN_4,           0,             0},
    {YELL_MELLICHAR_RELEASE5, NPC_MELLICHAR, 8000},
    {TYPE_WARDEN_5,           0,             5000},
    {SAY_SKYRISS_INTRO,       NPC_SKYRISS,   25000},
    {YELL_MELLICAR_WELCOME,   NPC_MELLICHAR, 3000},
    {SAY_SKYRISS_AGGRO,       NPC_SKYRISS,   0},
    {0, 0, 0},
}
Definition at line 63 of file arcatraz.cpp.