CMaNGOS_WoTLK: arcatrazScripts.cpp File Reference
arcatrazScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "arcatraz.h"
Data Structures
struct npc_millhouse_manastormAI
struct npc_warden_mellicharAI
struct npc_arcatraz_defenderAI
Enumerations
enum {
SAY_INTRO_1 = -1552010 , SAY_INTRO_2 = -1552011 , SAY_WATER = -1552012 , SAY_BUFFS = -1552013 ,
SAY_DRINK = -1552014 , SAY_READY = -1552015 , SAY_KILL_1 = -1552016 , SAY_KILL_2 = -1552017 ,
SAY_PYRO = -1552018 , SAY_ICEBLOCK = -1552019 , SAY_LOWHP = -1552020 , SAY_DEATH = -1552021 ,
SPELL_CONJURE_WATER = 36879 , SPELL_ARCANE_INTELLECT = 36880 , SPELL_ICE_ARMOR = 36881 , SD_SPELL_DRINK = 30024 ,
SPELL_ARCANE_MISSILES = 33833 , SPELL_CONE_OF_COLD = 12611 , SPELL_FIRE_BLAST = 13341 , SPELL_FIREBALL = 14034 ,
SPELL_FROSTBOLT = 15497 , SPELL_PYROBLAST = 33975 , SPELL_ICE_BLOCK = 36911 , POINT_ID_CENTER = 1
}
enum { SPELL_BUBBLE_VISUAL = 36849 , SPELL_SIMPLE_TELEPORT = 12980 }
enum { SPELL_FLAMING_WEAPON = 36601 , SPELL_FLAMING_WEAPON_H = 38804 , SPELL_PROTEAN_SUBDUAL = 36288 , SPELL_PROTEAN_SUBDUAL_H = 40449 }
Functions
UnitAI * GetAI_npc_millhouse_manastorm (Creature *pCreature)
UnitAI * GetAI_npc_warden_mellichar (Creature *pCreature)
UnitAI * GetAI_npc_arcatraz_defender (Creature *pCreature)
void AddSC_arcatraz ()
Variables
static const DialogueEntry aIntroDialogue []
static const float fRoomCenterCoords [3] = {445.8804f, -158.7055f, 43.06898f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_1
SAY_INTRO_2
SAY_WATER
SAY_BUFFS
SAY_DRINK
SAY_READY
SAY_KILL_1
SAY_KILL_2
SAY_PYRO
SAY_ICEBLOCK
SAY_LOWHP
SAY_DEATH
SPELL_CONJURE_WATER
SPELL_ARCANE_INTELLECT
SPELL_ICE_ARMOR
SD_SPELL_DRINK
SPELL_ARCANE_MISSILES
SPELL_CONE_OF_COLD
SPELL_FIRE_BLAST
SPELL_FIREBALL
SPELL_FROSTBOLT
SPELL_PYROBLAST
SPELL_ICE_BLOCK
POINT_ID_CENTER
Definition at line 37 of file arcatrazScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BUBBLE_VISUAL
SPELL_SIMPLE_TELEPORT
Definition at line 254 of file arcatrazScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FLAMING_WEAPON
SPELL_FLAMING_WEAPON_H
SPELL_PROTEAN_SUBDUAL
SPELL_PROTEAN_SUBDUAL_H
Definition at line 348 of file arcatrazScripts.cpp.
Function Documentation
AddSC_arcatraz()
void AddSC_arcatraz ()
Definition at line 408 of file arcatrazScripts.cpp.
References Script::GetAI, GetAI_npc_arcatraz_defender(), GetAI_npc_millhouse_manastorm(), GetAI_npc_warden_mellichar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_arcatraz_defender()
UnitAI* GetAI_npc_arcatraz_defender (Creature * pCreature)
Definition at line 403 of file arcatrazScripts.cpp.
Referenced by AddSC_arcatraz().
GetAI_npc_millhouse_manastorm()
UnitAI* GetAI_npc_millhouse_manastorm (Creature * pCreature)
Definition at line 245 of file arcatrazScripts.cpp.
Referenced by AddSC_arcatraz().
GetAI_npc_warden_mellichar()
UnitAI* GetAI_npc_warden_mellichar (Creature * pCreature)
Definition at line 339 of file arcatrazScripts.cpp.
Referenced by AddSC_arcatraz().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {NPC_MILLHOUSE,   0,             2000},
    {SAY_INTRO_1,     NPC_MILLHOUSE, 10000},
    {TYPE_WARDEN_2,   0,             10000},
    {SAY_INTRO_2,     NPC_MILLHOUSE, 18000},
    {SAY_WATER,       NPC_MILLHOUSE, 7000},
    {SAY_BUFFS,       NPC_MILLHOUSE, 6000},
    {SPELL_ICE_ARMOR, 0,             1000},
    {SAY_DRINK,       NPC_MILLHOUSE, 7000},
    {SAY_READY,       NPC_MILLHOUSE, 6000},
    {POINT_ID_CENTER, 0,             0},
    {0, 0, 0},
}
Definition at line 68 of file arcatrazScripts.cpp.
fRoomCenterCoords
const float fRoomCenterCoords[3] = {445.8804f, -158.7055f, 43.06898f} static
Definition at line 83 of file arcatrazScripts.cpp.
Referenced by npc_millhouse_manastormAI::EnterEvadeMode(), and npc_millhouse_manastormAI::JustDidDialogueStep().