CMaNGOS_WoTLK: areatrigger_scripts.cpp File Reference
areatrigger_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "world_map_scripts.h"
Data Structures
struct HotOnTrailData
struct AncientSpawn
struct Location
Enumerations
enum {
TRIGGER_SOUTH = 5284 , TRIGGER_CENTRAL = 5285 , TRIGGER_NORTH = 5286 , TRIGGER_NORTHWEST = 5287 ,
NPC_SOUTH_GATE = 32195 , NPC_CENTRAL_GATE = 32196 , NPC_NORTH_GATE = 32197 , NPC_NORTHWEST_GATE = 32199
}
enum { GO_COILFANG_WATERFALL = 184212 }
enum { SPELL_TELE_A_TO = 37389 , QUEST_GAINING_ACCESS_A = 10589 , SPELL_TELE_H_TO = 37387 , QUEST_GAINING_ACCESS_H = 10604 }
enum { QUEST_MANOR_RAVENHOLDT = 6681 , NPC_RAVENHOLDT = 13936 }
enum { QUEST_MISTWHISPER_TREASURE = 12575 , NPC_TARTEK = 28105 }
enum {
QUEST_THE_WARSONG_FARMS = 11686 , NPC_CREDIT_SLAUGHTERHOUSE = 25672 , NPC_CREDIT_GRAINERY = 25669 , NPC_CREDIT_TORP_FARM = 25671 ,
AT_SLAUGHTERHOUSE = 4873 , AT_GRAINERY = 4871 , AT_TORP_FARM = 4872
}
enum {
SPELL_SHOLOZAR_TO_UNGORO_TELEPORT = 52056 , SPELL_UNGORO_TO_SHOLOZAR_TELEPORT = 52057 , AT_WAYGATE_SHOLOZAR = 5046 , AT_WAYGATE_UNGORO = 5047 ,
QUEST_THE_MARKERS_OVERLOOK = 12613 , QUEST_THE_MARKERS_PERCH = 12559
}
enum { QUEST_STRENGTH_OF_THE_TEMPEST = 12741 , SPELL_CREATE_TRUE_POWER_OF_THE_TEMPEST = 53067 }
enum { QUEST_SCENT_OF_LARKORWI = 4291 , NPC_LARKORWI_MATE = 9683 }
enum {
QUEST_ANCIENT_LEAF = 7632 , NPC_VARTRUS = 14524 , NPC_STOMA = 14525 , NPC_HASTAT = 14526 ,
MAX_ANCIENTS = 3
}
enum { QUEST_SPECIAL_DELIVERY_TO_SHATTRATH = 10280 }
enum {
QUEST_RESUPPLYING_THE_EXCAVATION = 273 , NPC_SAEAN = 1380 , NPC_MIRAN = 1379 , NPC_HULDAR = 2057 ,
NPC_DARK_IRON_AMBUSHER = 1981 , FACTION_HOSTILE = 14 , SAY_MIRAN_AMBUSH = -1010029
}
enum { SPELL_A52_NEURALYZER = 34400 }
enum { NPC_TWILIGHT_CORRUPTER = 15625 , ITEM_FRAGMENT_NIGHTMARE = 21149 , QUEST_NIGHTMARE_CORRUPTION = 8735 , SAY_TWILIGHT_CORRUPTER_SPAWN = -1000411 }
enum { QUEST_I_SENSE_A_DISTURBANCE = 12665 }
Functions
bool AreaTrigger_at_childrens_week_spot (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_aldurthar_gate (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_coilfang_waterfall (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_legion_teleporter (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_ravenholdt (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_spearborn_encampment (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_warsong_farms (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_waygate (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_stormwright_shelf (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_scent_larkorwi (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_murkdeep (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_hot_on_the_trail (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_ancient_leaf (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_haramad_teleport (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_huldar_miran (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_area_52 (Player *player, AreaTriggerEntry const *at)
bool AreaTrigger_at_twilight_grove (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_hive_tower (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_quetzlun (Player *player, AreaTriggerEntry const *)
void AddSC_areatrigger_scripts ()
Variables
static uint32 TriggerOrphanSpell [6][3]
static const HotOnTrailData aHotOnTrailValues [6]
static const AncientSpawn afSpawnLocations [MAX_ANCIENTS]
static const Location m_miranAmbushSpawns []
static const Location m_twilightCorrupterSpawn = { -10326.3f, -487.423f, 50.1127f, 5.73692f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TRIGGER_SOUTH
TRIGGER_CENTRAL
TRIGGER_NORTH
TRIGGER_NORTHWEST
NPC_SOUTH_GATE
NPC_CENTRAL_GATE
NPC_NORTH_GATE
NPC_NORTHWEST_GATE
Definition at line 77 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
GO_COILFANG_WATERFALL
Definition at line 106 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_TELE_A_TO
QUEST_GAINING_ACCESS_A
SPELL_TELE_H_TO
QUEST_GAINING_ACCESS_H
Definition at line 125 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MANOR_RAVENHOLDT
NPC_RAVENHOLDT
Definition at line 158 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MISTWHISPER_TREASURE
NPC_TARTEK
Definition at line 176 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_THE_WARSONG_FARMS
NPC_CREDIT_SLAUGHTERHOUSE
NPC_CREDIT_GRAINERY
NPC_CREDIT_TORP_FARM
AT_SLAUGHTERHOUSE
AT_GRAINERY
AT_TORP_FARM
Definition at line 202 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SHOLOZAR_TO_UNGORO_TELEPORT
SPELL_UNGORO_TO_SHOLOZAR_TELEPORT
AT_WAYGATE_SHOLOZAR
AT_WAYGATE_UNGORO
QUEST_THE_MARKERS_OVERLOOK
QUEST_THE_MARKERS_PERCH
Definition at line 232 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_STRENGTH_OF_THE_TEMPEST
SPELL_CREATE_TRUE_POWER_OF_THE_TEMPEST
Definition at line 260 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SCENT_OF_LARKORWI
NPC_LARKORWI_MATE
Definition at line 278 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ANCIENT_LEAF
NPC_VARTRUS
NPC_STOMA
NPC_HASTAT
MAX_ANCIENTS
Definition at line 379 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SPECIAL_DELIVERY_TO_SHATTRATH
Definition at line 426 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_RESUPPLYING_THE_EXCAVATION
NPC_SAEAN
NPC_MIRAN
NPC_HULDAR
NPC_DARK_IRON_AMBUSHER
FACTION_HOSTILE
SAY_MIRAN_AMBUSH
Definition at line 444 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_A52_NEURALYZER
Definition at line 524 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_TWILIGHT_CORRUPTER
ITEM_FRAGMENT_NIGHTMARE
QUEST_NIGHTMARE_CORRUPTION
SAY_TWILIGHT_CORRUPTER_SPAWN
Definition at line 547 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_I_SENSE_A_DISTURBANCE
Definition at line 613 of file areatrigger_scripts.cpp.
Function Documentation
AddSC_areatrigger_scripts()
void AddSC_areatrigger_scripts ()
Definition at line 625 of file areatrigger_scripts.cpp.
References AreaTrigger_at_aldurthar_gate(), AreaTrigger_at_ancient_leaf(), AreaTrigger_at_area_52(), AreaTrigger_at_childrens_week_spot(), AreaTrigger_at_coilfang_waterfall(), AreaTrigger_at_haramad_teleport(), AreaTrigger_at_hive_tower(), AreaTrigger_at_hot_on_the_trail(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_legion_teleporter(), AreaTrigger_at_murkdeep(), AreaTrigger_at_quetzlun(), AreaTrigger_at_ravenholdt(), AreaTrigger_at_scent_larkorwi(), AreaTrigger_at_spearborn_encampment(), AreaTrigger_at_stormwright_shelf(), AreaTrigger_at_twilight_grove(), AreaTrigger_at_warsong_farms(), AreaTrigger_at_waygate(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_aldurthar_gate()
bool AreaTrigger_at_aldurthar_gate (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 90 of file areatrigger_scripts.cpp.
References AreaTriggerEntry::id, Player::KilledMonsterCredit(), NPC_CENTRAL_GATE, NPC_NORTH_GATE, NPC_NORTHWEST_GATE, NPC_SOUTH_GATE, TRIGGER_CENTRAL, TRIGGER_NORTH, TRIGGER_NORTHWEST, and TRIGGER_SOUTH.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_ancient_leaf()
bool AreaTrigger_at_ancient_leaf (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 403 of file areatrigger_scripts.cpp.
References afSpawnLocations, GetClosestCreatureWithEntry(), Player::GetQuestStatus(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NPC_HASTAT, NPC_STOMA, NPC_VARTRUS, QUEST_ANCIENT_LEAF, QUEST_STATUS_COMPLETE, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_area_52()
bool AreaTrigger_at_area_52 (Player * player, AreaTriggerEntry const * at)
Definition at line 529 of file areatrigger_scripts.cpp.
References Unit::CastSpell(), Unit::HasAura(), SQLStorage::LookupEntry(), SpellCastTargets::setDestination(), SpellCastTargets::setUnitTarget(), SPELL_A52_NEURALYZER, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_childrens_week_spot()
bool AreaTrigger_at_childrens_week_spot (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 59 of file areatrigger_scripts.cpp.
References Unit::CastSpell(), Object::GetEntry(), Unit::GetMiniPet(), AreaTriggerEntry::id, TRIGGERED_OLD_TRIGGERED, and TriggerOrphanSpell.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_coilfang_waterfall()
bool AreaTrigger_at_coilfang_waterfall (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 111 of file areatrigger_scripts.cpp.
References GetClosestGameObjectWithEntry(), GO_COILFANG_WATERFALL, and GO_READY.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_haramad_teleport()
bool AreaTrigger_at_haramad_teleport (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 431 of file areatrigger_scripts.cpp.
References Player::IsCurrentQuest(), QUEST_SPECIAL_DELIVERY_TO_SHATTRATH, and Player::TeleportTo().
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_hive_tower()
bool AreaTrigger_at_hive_tower (Player * player, AreaTriggerEntry const *)
Definition at line 588 of file areatrigger_scripts.cpp.
References aSpawnLocations, InstanceData::GetData(), WorldObject::GetInstanceData(), IN_MILLISECONDS, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NOT_STARTED, NPC_HIVE_ASHI_DRONES, POS_IDX_HIVE_DRONES_START, POS_IDX_HIVE_DRONES_STOP, InstanceData::SetData(), WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, and TYPE_HIVE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_hot_on_the_trail()
bool AreaTrigger_at_hot_on_the_trail (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 354 of file areatrigger_scripts.cpp.
References aHotOnTrailValues, Unit::CastSpell(), Player::GetQuestStatus(), Player::GetReqKillOrCastCurrentCount(), AreaTriggerEntry::id, Unit::IsAlive(), Player::IsGameMaster(), QUEST_STATUS_INCOMPLETE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_huldar_miran()
bool AreaTrigger_at_huldar_miran (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 470 of file areatrigger_scripts.cpp.
References Player::CompleteQuest(), DoScriptText(), FACTION_HOSTILE, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), Unit::IsAlive(), Player::IsGameMaster(), Unit::IsInCombat(), m_miranAmbushSpawns, NPC_DARK_IRON_AMBUSHER, NPC_HULDAR, NPC_MIRAN, NPC_SAEAN, QUEST_RESUPPLYING_THE_EXCAVATION, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, SAY_MIRAN_AMBUSH, Player::SendQuestCompleteEvent(), Creature::SetFactionTemporary(), WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_legion_teleporter()
bool AreaTrigger_at_legion_teleporter (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 134 of file areatrigger_scripts.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetQuestRewardStatus(), Player::GetTeam(), HORDE, Unit::IsAlive(), Unit::IsInCombat(), QUEST_GAINING_ACCESS_A, QUEST_GAINING_ACCESS_H, SPELL_TELE_A_TO, SPELL_TELE_H_TO, and TRIGGERED_NONE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_murkdeep()
bool AreaTrigger_at_murkdeep (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 299 of file areatrigger_scripts.cpp.
References aSpawnLocations, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), Player::IsGameMaster(), NPC_GREYMIST_COASTRUNNNER, NPC_MURKDEEP, POS_IDX_MURKDEEP_MOVE, POS_IDX_MURKDEEP_SPAWN, QUEST_STATUS_INCOMPLETE, QUEST_WANTED_MURKDEEP, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_quetzlun()
bool AreaTrigger_at_quetzlun (Player * player, AreaTriggerEntry const *)
Definition at line 618 of file areatrigger_scripts.cpp.
References Player::GetQuestStatus(), QUEST_I_SENSE_A_DISTURBANCE, QUEST_STATUS_INCOMPLETE, and Player::RewardPlayerAndGroupAtEventExplored().
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_ravenholdt()
bool AreaTrigger_at_ravenholdt (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 164 of file areatrigger_scripts.cpp.
References Player::GetQuestStatus(), Player::KilledMonsterCredit(), NPC_RAVENHOLDT, QUEST_MANOR_RAVENHOLDT, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_scent_larkorwi()
bool AreaTrigger_at_scent_larkorwi (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 284 of file areatrigger_scripts.cpp.
References GetClosestCreatureWithEntry(), Player::GetQuestStatus(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NPC_LARKORWI_MATE, QUEST_SCENT_OF_LARKORWI, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_spearborn_encampment()
bool AreaTrigger_at_spearborn_encampment (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 183 of file areatrigger_scripts.cpp.
References GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Player::GetReqKillOrCastCurrentCount(), IN_MILLISECONDS, MINUTE, NPC_TARTEK, QUEST_MISTWHISPER_TREASURE, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_stormwright_shelf()
bool AreaTrigger_at_stormwright_shelf (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 266 of file areatrigger_scripts.cpp.
References Unit::CastSpell(), Player::GetQuestStatus(), Unit::IsDead(), QUEST_STATUS_INCOMPLETE, QUEST_STRENGTH_OF_THE_TEMPEST, SPELL_CREATE_TRUE_POWER_OF_THE_TEMPEST, and TRIGGERED_NONE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_twilight_grove()
bool AreaTrigger_at_twilight_grove (Player * player, AreaTriggerEntry const *)
Definition at line 557 of file areatrigger_scripts.cpp.
References DoScriptText(), GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), Player::HasItemCount(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), ITEM_FRAGMENT_NIGHTMARE, Location::m_fO, Location::m_fX, Location::m_fY, Location::m_fZ, m_twilightCorrupterSpawn, MINUTE, NPC_TWILIGHT_CORRUPTER, QUEST_NIGHTMARE_CORRUPTION, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, SAY_TWILIGHT_CORRUPTER_SPAWN, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_warsong_farms()
bool AreaTrigger_at_warsong_farms (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 214 of file areatrigger_scripts.cpp.
References AT_GRAINERY, AT_SLAUGHTERHOUSE, AT_TORP_FARM, Player::GetQuestStatus(), AreaTriggerEntry::id, Unit::IsDead(), Player::KilledMonsterCredit(), NPC_CREDIT_GRAINERY, NPC_CREDIT_SLAUGHTERHOUSE, NPC_CREDIT_TORP_FARM, QUEST_STATUS_INCOMPLETE, and QUEST_THE_WARSONG_FARMS.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_waygate()
bool AreaTrigger_at_waygate (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 242 of file areatrigger_scripts.cpp.
References AT_WAYGATE_SHOLOZAR, AT_WAYGATE_UNGORO, Unit::CastSpell(), Player::GetQuestStatus(), AreaTriggerEntry::id, Unit::IsDead(), QUEST_STATUS_COMPLETE, QUEST_THE_MARKERS_OVERLOOK, QUEST_THE_MARKERS_PERCH, SPELL_SHOLOZAR_TO_UNGORO_TELEPORT, SPELL_UNGORO_TO_SHOLOZAR_TELEPORT, and TRIGGERED_NONE.
Referenced by AddSC_areatrigger_scripts().
Variable Documentation
afSpawnLocations
const AncientSpawn afSpawnLocations[MAX_ANCIENTS] static
Initial value:
=
{
    { NPC_VARTRUS, 6204.051758f, -1172.575684f, 370.079224f, 0.86052f },
    { NPC_STOMA,   6246.953613f, -1155.985718f, 366.182953f, 2.90269f },
    { NPC_HASTAT,  6193.449219f, -1137.834106f, 366.260529f, 5.77332f },
}
Definition at line 396 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_ancient_leaf().
aHotOnTrailValues
const HotOnTrailData aHotOnTrailValues[6] static
Initial value:
=
{
    {5710, 24849, 38340, 71713},
    {5711, 24849, 38341, 71745},
    {5712, 24849, 38342, 71752},
    {5714, 24851, 38341, 71760},
    {5715, 24851, 38340, 71759},
    {5716, 24851, 38342, 71758},
}
Definition at line 344 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_hot_on_the_trail().
m_miranAmbushSpawns
const Location m_miranAmbushSpawns[] static
Initial value:
=
{
    { -5760.73f, -3437.71f, 305.54f, 2.41f },
    { -5759.85f, -3441.29f, 305.57f, 2.24f },
    { -5757.75f, -3437.61f, 304.32f, 2.56f },
}
Definition at line 463 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_huldar_miran().
m_twilightCorrupterSpawn
const Location m_twilightCorrupterSpawn = { -10326.3f, -487.423f, 50.1127f, 5.73692f } static
Definition at line 555 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_twilight_grove().
TriggerOrphanSpell
uint32 TriggerOrphanSpell[6][3] static
Initial value:
=
{
    {3546, 14305, 65056},
    {3547, 14444, 65059},
    {3548, 14305, 65055},
    {3549, 14444, 65058},
    {3550, 14444, 65057},
    {3552, 14305, 65054}
}
Definition at line 49 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_childrens_week_spot().