CMaNGOS_WoTLK: ashenvale.cpp File Reference
ashenvale.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_muglashAI
struct npc_ruul_snowhoofAI
struct npc_torekAI
struct npc_feero_ironhandAI
Enumerations
enum {
SAY_MUG_START1 = -1000501 , SAY_MUG_START2 = -1000502 , SAY_MUG_BRAZIER = -1000503 , SAY_MUG_BRAZIER_WAIT = -1000504 ,
SAY_MUG_ON_GUARD = -1000505 , SAY_MUG_REST = -1000506 , SAY_MUG_DONE = -1000507 , SAY_MUG_GRATITUDE = -1000508 ,
SAY_MUG_PATROL = -1000509 , SAY_MUG_RETURN = -1000510 , QUEST_VORSHA = 6641 , GO_NAGA_BRAZIER = 178247 ,
NPC_MUGLASH = 12717 , NPC_WRATH_RIDER = 3713 , NPC_WRATH_SORCERESS = 3717 , NPC_WRATH_RAZORTAIL = 3712 ,
NPC_WRATH_PRIESTESS = 3944 , NPC_WRATH_MYRMIDON = 3711 , NPC_WRATH_SEAWITCH = 3715 , NPC_VORSHA = 12940
}
enum {
QUEST_FREEDOM_TO_RUUL = 6482 , NPC_T_AVENGER = 3925 , NPC_T_SHAMAN = 3924 , NPC_T_PATHFINDER = 3926 ,
SPELL_RUUL_SHAPECHANGE = 20514 , SAY_RUUL_COMPLETE = -1010022
}
enum {
SAY_READY = -1000106 , SAY_MOVE = -1000107 , SAY_PREPARE = -1000108 , SAY_WIN = -1000109 ,
SAY_END = -1000110 , SPELL_REND = 11977 , SPELL_THUNDERCLAP = 8078 , QUEST_TOREK_ASSULT = 6544 ,
NPC_SPLINTERTREE_RAIDER = 12859 , NPC_DURIEL = 12860 , NPC_SILVERWING_SENTINEL = 12896 , NPC_SILVERWING_WARRIOR = 12897
}
enum {
SAY_QUEST_START = -1000771 , SAY_FIRST_AMBUSH_START = -1000772 , SAY_FIRST_AMBUSH_END = -1000773 , SAY_SECOND_AMBUSH_START = -1000774 ,
SAY_SCOUT_SECOND_AMBUSH = -1000775 , SAY_SECOND_AMBUSH_END = -1000776 , SAY_FINAL_AMBUSH_START = -1000777 , SAY_BALIZAR_FINAL_AMBUSH = -1000778 ,
SAY_FINAL_AMBUSH_ATTACK = -1000779 , SAY_QUEST_END = -1000780 , QUEST_SUPPLIES_TO_AUBERDINE = 976 , NPC_DARK_STRAND_ASSASSIN = 3879 ,
NPC_FORSAKEN_SCOUT = 3893 , NPC_ALIGAR_THE_TORMENTOR = 3898 , NPC_BALIZAR_THE_UMBRAGE = 3899 , NPC_CAEDAKAR_THE_VICIOUS = 3900
}
Functions
bool QuestAccept_npc_muglash (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_muglash (Creature *pCreature)
bool GOUse_go_naga_brazier (Player *, GameObject *pGo)
bool QuestAccept_npc_ruul_snowhoof (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_ruul_snowhoofAI (Creature *pCreature)
bool QuestAccept_npc_torek (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_torek (Creature *pCreature)
UnitAI * GetAI_npc_feero_ironhand (Creature *pCreature)
bool QuestAccept_npc_feero_ironhand (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_ashenvale ()
Variables
static float m_afFirstNagaCoord [3][3]
static float m_afSecondNagaCoord [3][3]
static float m_fVorshaCoord [] = {3633.056885f, 1172.924072f, -5.388f}
static uint32 m_ruulAmbushers [3] = { NPC_T_AVENGER, NPC_T_SHAMAN, NPC_T_PATHFINDER}
static float m_ruulAmbushCoords [2][3]
static const float aSummonPositions [2][2]
static const float aEliteSummonPositions [3][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_MUG_START1
SAY_MUG_START2
SAY_MUG_BRAZIER
SAY_MUG_BRAZIER_WAIT
SAY_MUG_ON_GUARD
SAY_MUG_REST
SAY_MUG_DONE
SAY_MUG_GRATITUDE
SAY_MUG_PATROL
SAY_MUG_RETURN
QUEST_VORSHA
GO_NAGA_BRAZIER
NPC_MUGLASH
NPC_WRATH_RIDER
NPC_WRATH_SORCERESS
NPC_WRATH_RAZORTAIL
NPC_WRATH_PRIESTESS
NPC_WRATH_MYRMIDON
NPC_WRATH_SEAWITCH
NPC_VORSHA
Definition at line 38 of file ashenvale.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_FREEDOM_TO_RUUL
NPC_T_AVENGER
NPC_T_SHAMAN
NPC_T_PATHFINDER
SPELL_RUUL_SHAPECHANGE
SAY_RUUL_COMPLETE
Definition at line 247 of file ashenvale.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_READY
SAY_MOVE
SAY_PREPARE
SAY_WIN
SAY_END
SPELL_REND
SPELL_THUNDERCLAP
QUEST_TOREK_ASSULT
NPC_SPLINTERTREE_RAIDER
NPC_DURIEL
NPC_SILVERWING_SENTINEL
NPC_SILVERWING_WARRIOR
Definition at line 349 of file ashenvale.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_QUEST_START
SAY_FIRST_AMBUSH_START
SAY_FIRST_AMBUSH_END
SAY_SECOND_AMBUSH_START
SAY_SCOUT_SECOND_AMBUSH
SAY_SECOND_AMBUSH_END
SAY_FINAL_AMBUSH_START
SAY_BALIZAR_FINAL_AMBUSH
SAY_FINAL_AMBUSH_ATTACK
SAY_QUEST_END
QUEST_SUPPLIES_TO_AUBERDINE
NPC_DARK_STRAND_ASSASSIN
NPC_FORSAKEN_SCOUT
NPC_ALIGAR_THE_TORMENTOR
NPC_BALIZAR_THE_UMBRAGE
NPC_CAEDAKAR_THE_VICIOUS
Definition at line 465 of file ashenvale.cpp.
Function Documentation
AddSC_ashenvale()
void AddSC_ashenvale ()
Definition at line 638 of file ashenvale.cpp.
References Script::GetAI, GetAI_npc_feero_ironhand(), GetAI_npc_muglash(), GetAI_npc_ruul_snowhoofAI(), GetAI_npc_torek(), GOUse_go_naga_brazier(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_feero_ironhand(), QuestAccept_npc_muglash(), QuestAccept_npc_ruul_snowhoof(), QuestAccept_npc_torek(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_feero_ironhand()
UnitAI* GetAI_npc_feero_ironhand (Creature * pCreature)
Definition at line 619 of file ashenvale.cpp.
Referenced by AddSC_ashenvale().
GetAI_npc_muglash()
UnitAI* GetAI_npc_muglash (Creature * pCreature)
Definition at line 222 of file ashenvale.cpp.
Referenced by AddSC_ashenvale().
GetAI_npc_ruul_snowhoofAI()
UnitAI* GetAI_npc_ruul_snowhoofAI (Creature * pCreature)
Definition at line 340 of file ashenvale.cpp.
Referenced by AddSC_ashenvale().
GetAI_npc_torek()
UnitAI* GetAI_npc_torek (Creature * pCreature)
Definition at line 456 of file ashenvale.cpp.
Referenced by AddSC_ashenvale().
GOUse_go_naga_brazier()
bool GOUse_go_naga_brazier (Player * , GameObject * pGo)
Definition at line 227 of file ashenvale.cpp.
References DoScriptText(), GetClosestCreatureWithEntry(), INTERACTION_DISTANCE, NPC_MUGLASH, and SAY_MUG_BRAZIER_WAIT.
Referenced by AddSC_ashenvale().
QuestAccept_npc_feero_ironhand()
bool QuestAccept_npc_feero_ironhand (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 624 of file ashenvale.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_A_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_SUPPLIES_TO_AUBERDINE, SAY_QUEST_START, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_ashenvale().
QuestAccept_npc_muglash()
bool QuestAccept_npc_muglash (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 206 of file ashenvale.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_PASSIVE, Quest::GetQuestId(), QUEST_VORSHA, SAY_MUG_START1, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_ashenvale().
QuestAccept_npc_ruul_snowhoof()
bool QuestAccept_npc_ruul_snowhoof (Player * player, Creature * creature, const Quest * quest)
Definition at line 327 of file ashenvale.cpp.
References Creature::AI(), FACTION_ESCORT_H_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_FREEDOM_TO_RUUL, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_ashenvale().
QuestAccept_npc_torek()
bool QuestAccept_npc_torek (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 442 of file ashenvale.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_TOREK_ASSULT, and SAY_READY.
Referenced by AddSC_ashenvale().
Variable Documentation
aEliteSummonPositions
const float aEliteSummonPositions[3][4] static
Initial value:
=
{
    {4243.12f, 108.22f, 38.12f, 3.62f},
    {4240.95f, 114.04f, 38.35f, 3.56f},
    {4235.78f, 118.09f, 38.08f, 4.12f}
}
Definition at line 501 of file ashenvale.cpp.
Referenced by npc_feero_ironhandAI::WaypointReached().
aSummonPositions
const float aSummonPositions[2][2] static
Initial value:
=
{
    {30.0f, 1.25f},
    {30.0f, 0.95f}
}
Definition at line 494 of file ashenvale.cpp.
Referenced by npc_feero_ironhandAI::WaypointReached().
m_afFirstNagaCoord
float m_afFirstNagaCoord[3][3] static
Initial value:
=
{
    {3603.504150f, 1122.631104f, 1.635f},
    {3589.293945f, 1148.664063f, 5.565f},
    {3609.925537f, 1168.759521f, -1.168f}
}
Definition at line 67 of file ashenvale.cpp.
Referenced by npc_muglashAI::DoWaveSummon().
m_afSecondNagaCoord
float m_afSecondNagaCoord[3][3] static
Initial value:
=
{
    {3609.925537f, 1168.759521f, -1.168f},
    {3645.652100f, 1139.425415f, 1.322f},
    {3583.602051f, 1128.405762f, 2.347f}
}
Definition at line 74 of file ashenvale.cpp.
Referenced by npc_muglashAI::DoWaveSummon().
m_fVorshaCoord
float m_fVorshaCoord[] = {3633.056885f, 1172.924072f, -5.388f} static
Definition at line 81 of file ashenvale.cpp.
Referenced by npc_muglashAI::DoWaveSummon().
m_ruulAmbushCoords
float m_ruulAmbushCoords[2][3] static
Initial value:
=
        {
                {3425.33f, -595.93f, 178.31f},
                {3245.34f, -506.66f, 150.05f},
        }
Definition at line 259 of file ashenvale.cpp.
Referenced by npc_ruul_snowhoofAI::DoSpawnAmbush().
m_ruulAmbushers
uint32 m_ruulAmbushers[3] = { NPC_T_AVENGER, NPC_T_SHAMAN, NPC_T_PATHFINDER} static
Definition at line 257 of file ashenvale.cpp.
Referenced by npc_ruul_snowhoofAI::DoSpawnAmbush().