CMaNGOS_WoTLK: assembly_of_iron.cpp File Reference
assembly_of_iron.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_brundirAI
struct boss_molgeimAI
struct boss_steelbreakerAI
struct LightningWhirl
struct LightningWhirlHeroic
Enumerations
enum {
SAY_BRUNDIR_AGGRO = -1603056 , SAY_BRUNDIR_WHIRL = -1603057 , SAY_BRUNDIR_DEATH_1 = -1603058 , SAY_BRUNDIR_DEATH_2 = -1603059 ,
SAY_BRUNDIR_SLAY_1 = -1603060 , SAY_BRUNDIR_SLAY_2 = -1603061 , SAY_BRUNDIR_BERSERK = -1603062 , SAY_BRUNDIR_FLY = -1603063 ,
SAY_MOLGEIM_AGGRO = -1603064 , SAY_MOLGEIM_DEATH_1 = -1603065 , SAY_MOLGEIM_DEATH_2 = -1603066 , SAY_MOLGEIM_DEATH_RUNE = -1603067 ,
SAY_MOLGEIM_SURGE = -1603068 , SAY_MOLGEIM_SLAY_1 = -1603069 , SAY_MOLGEIM_SLAY_2 = -1603070 , SAY_MOLGEIM_BERSERK = -1603071 ,
SAY_STEEL_AGGRO = -1603072 , SAY_STEEL_DEATH_1 = -1603073 , SAY_STEEL_DEATH_2 = -1603074 , SAY_STEEL_SLAY_1 = -1603075 ,
SAY_STEEL_SLAY_2 = -1603076 , SAY_STEEL_OVERWHELM = -1603077 , SAY_STEEL_BERSERK = -1603078 , SPELL_BERSERK = 62535 ,
SPELL_SUPERCHARGE = 61920 , SPELL_LIGHTNING_CHANNEL_PREFIGHT = 61942 , SPELL_RUNE_OF_POWER_PREFIGHT = 61975 , SPELL_COUNCIL_KILL_CREDIT = 65195 ,
SPELL_HIGH_VOLTAGE = 61890 , SPELL_HIGH_VOLTAGE_H = 63498 , SPELL_FUSION_PUNCH = 61903 , SPELL_FUSION_PUNCH_H = 63493 ,
SPELL_STATIC_DISRUPTION = 61911 , SPELL_STATIC_DISRUPTION_H = 63495 , SPELL_OVERWHELMING_POWER = 61888 , SPELL_OVERWHELMING_POWER_H = 64637 ,
SPELL_ELECTRICAL_CHARGE = 61900 , SPELL_SHIELD = 62274 , SPELL_SHIELD_H = 63489 , SPELL_RUNE_OF_POWER = 61973 ,
SPELL_RUNE_OF_DEATH = 62269 , SPELL_RUNE_OF_DEATH_H = 63490 , SPELL_RUNE_OF_SUMMONING = 62273 , SPELL_CHAIN_LIGHTNING = 61879 ,
SPELL_CHAIN_LIGHTNING_H = 63479 , SPELL_OVERLOAD = 61869 , SPELL_LIGHTNING_WHIRL = 61915 , SPELL_LIGHTNING_WHIRL_H = 63483 ,
SPELL_LIGHTNING_WHIRL_DAMAGE = 61916 , SPELL_LIGHTNING_WHIRL_DAMAGE_H = 63482 , SPELL_STORMSHIELD = 64187 , SPELL_LIGHTNING_TENDRILS = 61887 ,
SPELL_LIGHTNING_TENDRILS_H = 63486 , SPELL_TENDRILS_VISUAL = 61883 , SPELL_OVERLOAD_AURA = 61877 , SPELL_RUNE_OF_POWER_AURA = 61974 ,
SPELL_RUNE_OF_SUMMONING_AURA = 62019 , SPELL_LIGHTNING_ELEMENTAL_PASSIVE = 62052 , SPELL_LIGHTNING_ELEMENTAL_PASSIVE_H = 63492 , NPC_OVERLOAD_VISUAL = 32866 ,
NPC_RUNE_OF_POWER = 33705 , NPC_RUNE_OF_SUMMONING = 33051 , NPC_LIGHTNING_ELEMENTAL = 32958 , PHASE_NO_CHARGE = 0 ,
PHASE_CHARGE_ONE = 1 , PHASE_CHARGE_TWO = 2 , POINT_ID_LIFT_OFF = 1 , POINT_ID_LAND = 2
}
Functions
UnitAI * GetAI_boss_brundir (Creature *pCreature)
UnitAI * GetAI_boss_molgeim (Creature *pCreature)
UnitAI * GetAI_boss_steelbreaker (Creature *pCreature)
void AddSC_boss_assembly_of_iron ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_BRUNDIR_AGGRO
SAY_BRUNDIR_WHIRL
SAY_BRUNDIR_DEATH_1
SAY_BRUNDIR_DEATH_2
SAY_BRUNDIR_SLAY_1
SAY_BRUNDIR_SLAY_2
SAY_BRUNDIR_BERSERK
SAY_BRUNDIR_FLY
SAY_MOLGEIM_AGGRO
SAY_MOLGEIM_DEATH_1
SAY_MOLGEIM_DEATH_2
SAY_MOLGEIM_DEATH_RUNE
SAY_MOLGEIM_SURGE
SAY_MOLGEIM_SLAY_1
SAY_MOLGEIM_SLAY_2
SAY_MOLGEIM_BERSERK
SAY_STEEL_AGGRO
SAY_STEEL_DEATH_1
SAY_STEEL_DEATH_2
SAY_STEEL_SLAY_1
SAY_STEEL_SLAY_2
SAY_STEEL_OVERWHELM
SAY_STEEL_BERSERK
SPELL_BERSERK
SPELL_SUPERCHARGE
SPELL_LIGHTNING_CHANNEL_PREFIGHT
SPELL_RUNE_OF_POWER_PREFIGHT
SPELL_COUNCIL_KILL_CREDIT
SPELL_HIGH_VOLTAGE
SPELL_HIGH_VOLTAGE_H
SPELL_FUSION_PUNCH
SPELL_FUSION_PUNCH_H
SPELL_STATIC_DISRUPTION
SPELL_STATIC_DISRUPTION_H
SPELL_OVERWHELMING_POWER
SPELL_OVERWHELMING_POWER_H
SPELL_ELECTRICAL_CHARGE
SPELL_SHIELD
SPELL_SHIELD_H
SPELL_RUNE_OF_POWER
SPELL_RUNE_OF_DEATH
SPELL_RUNE_OF_DEATH_H
SPELL_RUNE_OF_SUMMONING
SPELL_CHAIN_LIGHTNING
SPELL_CHAIN_LIGHTNING_H
SPELL_OVERLOAD
SPELL_LIGHTNING_WHIRL
SPELL_LIGHTNING_WHIRL_H
SPELL_LIGHTNING_WHIRL_DAMAGE
SPELL_LIGHTNING_WHIRL_DAMAGE_H
SPELL_STORMSHIELD
SPELL_LIGHTNING_TENDRILS
SPELL_LIGHTNING_TENDRILS_H
SPELL_TENDRILS_VISUAL
SPELL_OVERLOAD_AURA
SPELL_RUNE_OF_POWER_AURA
SPELL_RUNE_OF_SUMMONING_AURA
SPELL_LIGHTNING_ELEMENTAL_PASSIVE
SPELL_LIGHTNING_ELEMENTAL_PASSIVE_H
NPC_OVERLOAD_VISUAL
NPC_RUNE_OF_POWER
NPC_RUNE_OF_SUMMONING
NPC_LIGHTNING_ELEMENTAL
PHASE_NO_CHARGE
PHASE_CHARGE_ONE
PHASE_CHARGE_TWO
POINT_ID_LIFT_OFF
POINT_ID_LAND
Definition at line 27 of file assembly_of_iron.cpp.
Function Documentation
AddSC_boss_assembly_of_iron()
void AddSC_boss_assembly_of_iron ()
Definition at line 777 of file assembly_of_iron.cpp.
References Script::GetAI, GetAI_boss_brundir(), GetAI_boss_molgeim(), GetAI_boss_steelbreaker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_brundir()
UnitAI* GetAI_boss_brundir (Creature * pCreature)
Definition at line 421 of file assembly_of_iron.cpp.
Referenced by AddSC_boss_assembly_of_iron().
GetAI_boss_molgeim()
UnitAI* GetAI_boss_molgeim (Creature * pCreature)
Definition at line 606 of file assembly_of_iron.cpp.
Referenced by AddSC_boss_assembly_of_iron().
GetAI_boss_steelbreaker()
UnitAI* GetAI_boss_steelbreaker (Creature * pCreature)
Definition at line 756 of file assembly_of_iron.cpp.
Referenced by AddSC_boss_assembly_of_iron().