CMaNGOS_WoTLK: azshara.cpp File Reference
azshara.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
Data Structures
struct npc_rizzle_sprysprocketAI
struct npc_depth_chargeAI
struct SpitelashAbilityStruct
struct mobs_spitelashesAI
struct npc_felhound_trackerAI
struct SummonLocation
struct go_ai_lightning
struct boss_mawsAI
Macros
#define GOSSIP_ITEM_MOONSTONE "Hand over the Southfury moonstone and I'll let you go."
Enumerations
enum {
SAY_START = -1000351 , EMOTE_START = -1000352 , SAY_WHISPER_CHILL = -1000353 , SAY_GRENADE_FAIL = -1000354 ,
SAY_END = -1000355 , QUEST_MOONSTONE = 10994 , NPC_RIZZLE = 23002 , NPC_DEPTH_CHARGE = 23025 ,
SPELL_SUMMON_RIZZLE = 39866 , SPELL_BLACKJACK = 39865 , SPELL_ESCAPE = 39871 , SPELL_SWIM_SPEED = 40596 ,
SPELL_FROST_TRAP = 39902 , SPELL_PERIODIC_GRENADE = 40553 , SPELL_FROST_GRENADE = 40525 , SPELL_SUMMON_DEPTH_CHARGE = 39907 ,
SPELL_TRAP = 39899 , SPELL_PERIODIC_CHECK = 39888 , SPELL_SURRENDER = 39889 , SPELL_GIVE_MOONSTONE = 39886
}
enum {
SPELL_POLYMORPH_BACKFIRE = 28406 , QUEST_FRAGMENTED_MAGIC = 9364 , SPELL_DISARM = 6713 , SPELL_SCREECH = 3589 ,
SPELL_FROST_SHOCK = 12548 , SPELL_RENEW = 11640 , SPELL_SHOOT = 6660 , SPELL_FROST_SHOT = 12551 ,
SPELL_FROST_NOVA = 11831 , SPELL_STRIKE = 11976 , NPC_SPITELASH_WARRIOR = 6190 , NPC_SPITELASH_SCREAMER = 6193 ,
NPC_SPITELASH_GUARD = 6194 , NPC_SPITELASH_SIREN = 6195 , NPC_SPITELASH_MYRMIDON = 6196 , TARGET_TYPE_RANDOM = 0 ,
TARGET_TYPE_VICTIM = 1 , TARGET_TYPE_SELF = 2 , TARGET_TYPE_FRIENDLY = 3
}
enum {
QUEST_AZSHARITE = 3602 , GO_AZSHARITE_1 = 152620 , GO_AZSHARITE_2 = 152621 , GO_AZSHARITE_3 = 152622 ,
GO_AZSHARITE_4 = 152631 , SOUND_GROWL = 1249
}
enum { EVENT_ARCANITE_BUOY = 9542 , NPC_MAWS = 15571 , GO_THEATRIC_LIGHTNING = 183356 }
enum { SPELL_FRENZY = 19812 , SPELL_DARK_WATER = 25743 , SPELL_RAMPAGE = 25744 , EMOTE_GENERIC_FRENZY_KILL = -1000001 }
Functions
UnitAI * GetAI_npc_rizzle_sprysprocket (Creature *pCreature)
bool GossipHello_npc_rizzle_sprysprocket (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_rizzle_sprysprocket (Player *pPlayer, Creature *, uint32, uint32 uiAction)
UnitAI * GetAI_npc_depth_charge (Creature *pCreature)
bool GOUse_go_southfury_moonstone (Player *pPlayer, GameObject *)
UnitAI * GetAI_mobs_spitelashes (Creature *pCreature)
bool GossipHello_npc_loramus_thalipedes (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_loramus_thalipedes (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_felhound_tracker (Creature *pCreature)
bool ProcessEventId_arcanite_buoy (uint32 uiEventId, Object *pSource, Object *, bool)
GameObjectAI * GetAI_go_lightning (GameObject *go)
UnitAI * GetAI_boss_maws (Creature *pCreature)
void AddSC_azshara ()
Variables
static SpitelashAbilityStruct m_aSpitelashAbility [8]
static const uint32 aGOList [] = {GO_AZSHARITE_1, GO_AZSHARITE_2, GO_AZSHARITE_3, GO_AZSHARITE_4}
static const SummonLocation aMawsSpawn = { 3561.73f, -6647.2f, -7.5f }
Macro Definition Documentation
GOSSIP_ITEM_MOONSTONE
#define GOSSIP_ITEM_MOONSTONE "Hand over the Southfury moonstone and I'll let you go."
Definition at line 75 of file azshara.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
EMOTE_START
SAY_WHISPER_CHILL
SAY_GRENADE_FAIL
SAY_END
QUEST_MOONSTONE
NPC_RIZZLE
NPC_DEPTH_CHARGE
SPELL_SUMMON_RIZZLE
SPELL_BLACKJACK
SPELL_ESCAPE
SPELL_SWIM_SPEED
SPELL_FROST_TRAP
SPELL_PERIODIC_GRENADE
SPELL_FROST_GRENADE
SPELL_SUMMON_DEPTH_CHARGE
SPELL_TRAP
SPELL_PERIODIC_CHECK
SPELL_SURRENDER
SPELL_GIVE_MOONSTONE
Definition at line 44 of file azshara.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_POLYMORPH_BACKFIRE
QUEST_FRAGMENTED_MAGIC
SPELL_DISARM
SPELL_SCREECH
SPELL_FROST_SHOCK
SPELL_RENEW
SPELL_SHOOT
SPELL_FROST_SHOT
SPELL_FROST_NOVA
SPELL_STRIKE
NPC_SPITELASH_WARRIOR
NPC_SPITELASH_SCREAMER
NPC_SPITELASH_GUARD
NPC_SPITELASH_SIREN
NPC_SPITELASH_MYRMIDON
TARGET_TYPE_RANDOM
TARGET_TYPE_VICTIM
TARGET_TYPE_SELF
TARGET_TYPE_FRIENDLY
Definition at line 252 of file azshara.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_AZSHARITE
GO_AZSHARITE_1
GO_AZSHARITE_2
GO_AZSHARITE_3
GO_AZSHARITE_4
SOUND_GROWL
Definition at line 468 of file azshara.cpp.
anonymous enum
anonymous enum
Enumerator
EVENT_ARCANITE_BUOY
NPC_MAWS
GO_THEATRIC_LIGHTNING
Definition at line 592 of file azshara.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FRENZY
SPELL_DARK_WATER
SPELL_RAMPAGE
EMOTE_GENERIC_FRENZY_KILL
Definition at line 673 of file azshara.cpp.
Function Documentation
AddSC_azshara()
void AddSC_azshara ()
Definition at line 766 of file azshara.cpp.
References Script::GetAI, GetAI_boss_maws(), GetAI_go_lightning(), GetAI_mobs_spitelashes(), GetAI_npc_depth_charge(), GetAI_npc_felhound_tracker(), GetAI_npc_rizzle_sprysprocket(), Script::GetGameObjectAI, GossipHello_npc_loramus_thalipedes(), GossipHello_npc_rizzle_sprysprocket(), GossipSelect_npc_loramus_thalipedes(), GossipSelect_npc_rizzle_sprysprocket(), GOUse_go_southfury_moonstone(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, ProcessEventId_arcanite_buoy(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_maws()
UnitAI* GetAI_boss_maws (Creature * pCreature)
Definition at line 761 of file azshara.cpp.
Referenced by AddSC_azshara().
GetAI_go_lightning()
GameObjectAI* GetAI_go_lightning (GameObject * go)
Definition at line 664 of file azshara.cpp.
Referenced by AddSC_azshara().
GetAI_mobs_spitelashes()
UnitAI* GetAI_mobs_spitelashes (Creature * pCreature)
Definition at line 402 of file azshara.cpp.
Referenced by AddSC_azshara().
GetAI_npc_depth_charge()
UnitAI* GetAI_npc_depth_charge (Creature * pCreature)
Definition at line 229 of file azshara.cpp.
Referenced by AddSC_azshara().
GetAI_npc_felhound_tracker()
UnitAI* GetAI_npc_felhound_tracker (Creature * pCreature)
Definition at line 583 of file azshara.cpp.
Referenced by AddSC_azshara().
GetAI_npc_rizzle_sprysprocket()
UnitAI* GetAI_npc_rizzle_sprysprocket (Creature * pCreature)
Definition at line 188 of file azshara.cpp.
Referenced by AddSC_azshara().
GossipHello_npc_loramus_thalipedes()
bool GossipHello_npc_loramus_thalipedes (Player * pPlayer, Creature * pCreature)
Definition at line 411 of file azshara.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_azshara().
GossipHello_npc_rizzle_sprysprocket()
bool GossipHello_npc_rizzle_sprysprocket (Player * pPlayer, Creature * pCreature)
Definition at line 193 of file azshara.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_MOONSTONE, GOSSIP_SENDER_MAIN, QUEST_MOONSTONE, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_azshara().
GossipSelect_npc_loramus_thalipedes()
bool GossipSelect_npc_loramus_thalipedes (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 427 of file azshara.cpp.
References Player::AreaExploredOrEventHappens(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, and GOSSIP_SENDER_MAIN.
Referenced by AddSC_azshara().
GossipSelect_npc_rizzle_sprysprocket()
bool GossipSelect_npc_rizzle_sprysprocket (Player * pPlayer, Creature * , uint32 , uint32 uiAction)
Definition at line 202 of file azshara.cpp.
References Unit::CastSpell(), GOSSIP_ACTION_INFO_DEF, SPELL_GIVE_MOONSTONE, and TRIGGERED_NONE.
Referenced by AddSC_azshara().
GOUse_go_southfury_moonstone()
bool GOUse_go_southfury_moonstone (Player * pPlayer, GameObject *)
Definition at line 238 of file azshara.cpp.
References NPC_RIZZLE, SPELL_BLACKJACK, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TRIGGERED_NONE.
Referenced by AddSC_azshara().
ProcessEventId_arcanite_buoy()
bool ProcessEventId_arcanite_buoy (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 606 of file azshara.cpp.
References aMawsSpawn, EVENT_ARCANITE_BUOY, GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), Object::GetTypeId(), GO_THEATRIC_LIGHTNING, SummonLocation::m_fX, SummonLocation::m_fY, SummonLocation::m_fZ, NPC_MAWS, TEMPSPAWN_MANUAL_DESPAWN, and TYPEID_PLAYER.
Referenced by AddSC_azshara().
Variable Documentation
aGOList
const uint32 aGOList[] = {GO_AZSHARITE_1, GO_AZSHARITE_2, GO_AZSHARITE_3, GO_AZSHARITE_4} static
Definition at line 480 of file azshara.cpp.
Referenced by npc_felhound_trackerAI::DoFindNewCrystal().
aMawsSpawn
const SummonLocation aMawsSpawn = { 3561.73f, -6647.2f, -7.5f } static
Definition at line 604 of file azshara.cpp.
Referenced by ProcessEventId_arcanite_buoy().
m_aSpitelashAbility
SpitelashAbilityStruct m_aSpitelashAbility[8] static
Initial value:
=
{
    {NPC_SPITELASH_WARRIOR,     SPELL_DISARM,       TARGET_TYPE_VICTIM,     4000,  10000},
    {NPC_SPITELASH_SCREAMER,    SPELL_SCREECH,      TARGET_TYPE_SELF,       7000,  15000},
    {NPC_SPITELASH_GUARD,       SPELL_FROST_SHOCK,  TARGET_TYPE_VICTIM,     7000,  13000},
    {NPC_SPITELASH_SIREN,       SPELL_RENEW,        TARGET_TYPE_FRIENDLY,   4000,  7000},
    {NPC_SPITELASH_SIREN,       SPELL_SHOOT,        TARGET_TYPE_RANDOM,     3000,  9000},
    {NPC_SPITELASH_SIREN,       SPELL_FROST_SHOT,   TARGET_TYPE_RANDOM,     7000,  10000},
    {NPC_SPITELASH_SIREN,       SPELL_FROST_NOVA,   TARGET_TYPE_SELF,       10000, 15000},
    {NPC_SPITELASH_MYRMIDON,    SPELL_STRIKE,       TARGET_TYPE_VICTIM,     3000,  7000}
}
Definition at line 287 of file azshara.cpp.
Referenced by mobs_spitelashesAI::CanUseSpecialAbility(), mobs_spitelashesAI::mobs_spitelashesAI(), mobs_spitelashesAI::Reset(), and mobs_spitelashesAI::UpdateAI().