CMaNGOS_WoTLK: azuremyst_isle.cpp File Reference
azuremyst_isle.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_draenei_survivorAI
struct npc_magwinAI
Enumerations
enum {
SAY_HEAL1 = -1001216 , SAY_HEAL2 = -1001217 , SAY_HEAL3 = -1001218 , SAY_HEAL4 = -1001219 ,
SAY_HEAL5 = -1001220 , SAY_HEAL6 = -1001221 , SAY_HELP1 = -1001222 , SAY_HELP2 = -1001223 ,
SAY_HELP3 = -1001224 , SAY_HELP4 = -1001225 , SPELL_IRRIDATION = 35046 , SPELL_STUNNED = 28630
}
enum {
SAY_START = -1000111 , SAY_AGGRO = -1000112 , SAY_PROGRESS = -1000113 , SAY_END1 = -1000114 ,
SAY_END2 = -1000115 , EMOTE_HUG = -1000116 , SAY_DAUGHTER = -1000184 , NPC_COWLEN = 17311 ,
QUEST_A_CRY_FOR_HELP = 9528
}
Functions
UnitAI * GetAI_npc_draenei_survivor (Creature *pCreature)
bool QuestAccept_npc_magwin (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_azuremyst_isle ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_HEAL1
SAY_HEAL2
SAY_HEAL3
SAY_HEAL4
SAY_HEAL5
SAY_HEAL6
SAY_HELP1
SAY_HELP2
SAY_HELP3
SAY_HELP4
SPELL_IRRIDATION
SPELL_STUNNED
Definition at line 36 of file azuremyst_isle.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_AGGRO
SAY_PROGRESS
SAY_END1
SAY_END2
EMOTE_HUG
SAY_DAUGHTER
NPC_COWLEN
QUEST_A_CRY_FOR_HELP
Definition at line 181 of file azuremyst_isle.cpp.
Function Documentation
AddSC_azuremyst_isle()
void AddSC_azuremyst_isle ()
Definition at line 276 of file azuremyst_isle.cpp.
References Script::GetAI, GetAI_npc_draenei_survivor(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_magwin(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_draenei_survivor()
UnitAI* GetAI_npc_draenei_survivor (Creature * pCreature)
Definition at line 172 of file azuremyst_isle.cpp.
Referenced by AddSC_azuremyst_isle().
QuestAccept_npc_magwin()
bool QuestAccept_npc_magwin (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 267 of file azuremyst_isle.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_A_CRY_FOR_HELP.
Referenced by AddSC_azuremyst_isle().