CMaNGOS_WoTLK: BattleGroundMgr.cpp File Reference
BattleGroundMgr.cpp File Reference
#include "Common.h"
#include "Globals/SharedDefines.h"
#include "Entities/Player.h"
#include "BattleGroundMgr.h"
#include "BattleGroundAV.h"
#include "BattleGroundAB.h"
#include "BattleGroundEY.h"
#include "BattleGroundWS.h"
#include "BattleGroundNA.h"
#include "BattleGroundBE.h"
#include "BattleGroundRL.h"
#include "BattleGroundSA.h"
#include "BattleGroundDS.h"
#include "BattleGroundRV.h"
#include "BattleGroundIC.h"
#include "Maps/MapManager.h"
#include "Maps/Map.h"
#include "Globals/ObjectMgr.h"
#include "Util/ProgressBar.h"
#include "Chat/Chat.h"
#include "Arena/ArenaTeam.h"
#include "World/World.h"
#include "Server/WorldPacket.h"
#include "GameEvents/GameEventMgr.h"
#include "Tools/Formulas.h"
#include "Mails/Mail.h"
#include "Loot/LootMgr.h"
#include "Policies/Singleton.h"
Functions
INSTANTIATE_SINGLETON_1 (BattleGroundMgr)
void CheckPlayersAndAddToWinners (ArenaTeam *team, std::map< ObjectGuid, uint32 > &playerRanks, uint32 rank)
Method checks players and arena winners.
void SetTitleValues (uint32 &first, uint32 &second, uint32 titleId)
Method that sets that title values.
Function Documentation
CheckPlayersAndAddToWinners()
void CheckPlayersAndAddToWinners (ArenaTeam * team, std::map< ObjectGuid, uint32 > & playerRanks, uint32 rank)
Method checks players and arena winners.
Parameters
arena team
player ranks map
rank
Definition at line 2136 of file BattleGroundMgr.cpp.
References ArenaTeamStats::games_season, ArenaTeam::GetMembers(), ArenaTeam::GetStats(), and ArenaTeamStats::rating.
Referenced by BattleGroundMgr::RewardArenaSeason().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (BattleGroundMgr)
SetTitleValues()
void SetTitleValues (uint32 & first, uint32 & second, uint32 titleId)
Method that sets that title values.
Parameters
first title
second title
title id
Definition at line 2162 of file BattleGroundMgr.cpp.
Referenced by BattleGroundMgr::RewardArenaSeason().