CMaNGOS_WoTLK: battlegrounds.cpp File Reference
battlegrounds.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "Entities/Transports.h"
Data Structures
struct npc_spirit_guideAI
struct OpeningCapping
struct FlagAuraBg
struct FlagClickBg
struct ArenaPreparation
struct InactiveBattleground
struct spell_battleground_banner_trigger
struct spell_outdoor_pvp_banner_trigger
struct OutdoorPvpNotifyAI
struct spell_split_teleport_boat
struct spell_gunship_portal_click
struct spell_repair_cannon_aura
struct spell_repair_cannon
struct spell_end_of_round
struct spell_teleport_sota
Enumerations
enum { SPELL_SPIRIT_HEAL_CHANNEL = 22011 , SPELL_SPIRIT_HEAL = 22012 , SPELL_SPIRIT_HEAL_MANA = 44535 , SPELL_WAITING_TO_RESURRECT = 2584 }
enum { SPELL_OPENING_ANIM = 24390 }
Functions
bool GossipHello_npc_spirit_guide (Player *pPlayer, Creature *)
void AddSC_battleground ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_SPIRIT_HEAL_CHANNEL
SPELL_SPIRIT_HEAL
SPELL_SPIRIT_HEAL_MANA
SPELL_WAITING_TO_RESURRECT
Definition at line 41 of file battlegrounds.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_OPENING_ANIM
Definition at line 112 of file battlegrounds.cpp.
Function Documentation
AddSC_battleground()
void AddSC_battleground ()
Definition at line 439 of file battlegrounds.cpp.
References Script::GetAI, Script::GetGameObjectAI, GossipHello_npc_spirit_guide(), Script::Name, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_spirit_guide()
bool GossipHello_npc_spirit_guide (Player * pPlayer, Creature *)
Definition at line 106 of file battlegrounds.cpp.
References Unit::CastSpell(), SPELL_WAITING_TO_RESURRECT, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_battleground().