CMaNGOS_WoTLK: BattleGround.h File Reference
BattleGround.h File Reference
#include "Common.h"
#include "Globals/SharedDefines.h"
#include "Maps/Map.h"
#include "Util/ByteBuffer.h"
#include "Entities/ObjectGuid.h"
Data Structures
struct BattleGroundEventIdx
struct BattleGroundPlayer
struct BattleGroundObjectInfo
class BattleGroundScore
class BattleGround
struct BattleGround::EventObjects
struct WorldStatePair
Macros
#define BG_EVENT_NONE 255
#define BG_EVENT_DOOR 254
#define ARENA_BUFF_EVENT 253
#define ARENA_TIMELIMIT_POINTS_LOSS -16
#define BG_STARTING_EVENT_COUNT 4
Enumerations
enum BattleGroundSounds { SOUND_HORDE_WINS = 8454 , SOUND_ALLIANCE_WINS = 8455 , SOUND_BG_START = 3439 }
enum BattleGroundQuests {
SPELL_WS_QUEST_REWARD_1 = 43483 , SPELL_WS_QUEST_REWARD_2 = 69158 , SPELL_WS_QUEST_REWARD_3 = 69496 , SPELL_WS_QUEST_REWARD_4 = 69497 ,
SPELL_WS_QUEST_REWARD_5 = 69498 , SPELL_AB_QUEST_REWARD_1 = 43484 , SPELL_AB_QUEST_REWARD_2 = 69153 , SPELL_AB_QUEST_REWARD_3 = 69499 ,
SPELL_AB_QUEST_REWARD_4 = 69500 , SPELL_AV_QUEST_REWARD_1 = 43475 , SPELL_AV_QUEST_REWARD_2 = 69160 , SPELL_AV_QUEST_REWARD_3 = 69501 ,
SPELL_EY_QUEST_REWARD_1 = 43477 , SPELL_EY_QUEST_REWARD_2 = 69156 , SPELL_SA_QUEST_REWARD = 61213 , SPELL_IC_QUEST_REWARD = 67033
}
enum BattleGroundMarks {
SPELL_WS_MARK_LOSER = 24950 , SPELL_WS_MARK_WINNER = 24951 , SPELL_AB_MARK_LOSER = 24952 , SPELL_AB_MARK_WINNER = 24953 ,
SPELL_AV_MARK_LOSER = 24954 , SPELL_AV_MARK_WINNER = 24955 , SPELL_SA_MARK_LOSER = 61159 , SPELL_SA_MARK_WINNER = 61160
}
enum BattleGroundMarksCount { ITEM_WINNER_COUNT = 3 , ITEM_LOSER_COUNT = 1 }
enum ArenaSpells : uint32 {
SPELL_LAST_MAN_STANDING = 26549 , SPELL_ARENA_PREPARATION = 32727 , SPELL_ALLIANCE_GOLD_FLAG = 32724 , SPELL_ALLIANCE_GREEN_FLAG = 32725 ,
SPELL_HORDE_GOLD_FLAG = 35774 , SPELL_HORDE_GREEN_FLAG = 35775 , SPELL_ARENA_DAMPENING = 74410
}
enum BattleGroundSpells : uint32 {
SPELL_GRAVEYARD_TELEPORT = 24237 , SPELL_PREPARATION = 44521 , SPELL_RECENTLY_DROPPED_FLAG = 42792 , SPELL_AURA_PLAYER_INACTIVE = 43681 ,
SPELL_BATTLEGROUND_DAMPENING = 74411
}
enum BattleGroundTimeIntervals {
CHECK_PLAYER_POSITION_INVERVAL = 1000 , RESURRECTION_INTERVAL = 30000 , INVITATION_REMIND_TIME = 20000 , INVITE_ACCEPT_WAIT_TIME = 60000 ,
TIME_TO_AUTOREMOVE = 120000 , MAX_OFFLINE_TIME = 300 , RESPAWN_ONE_DAY = 86400 , RESPAWN_IMMEDIATELY = 0 ,
BUFF_RESPAWN_TIME = 180 , ARENA_SPAWN_BUFF_OBJECTS = 90000 , ARENA_FORCED_DRAW = 2700000
}
enum BattleGroundStartTimeIntervals {
BG_START_DELAY_2M = 120000 , BG_START_DELAY_1M = 60000 , BG_START_DELAY_30S = 30000 , BG_START_DELAY_15S = 15000 ,
BG_START_DELAY_NONE = 0
}
enum BattleGroundBuffObjects { BG_OBJECTID_SPEEDBUFF_ENTRY = 179871 , BG_OBJECTID_REGENBUFF_ENTRY = 179904 , BG_OBJECTID_BERSERKERBUFF_ENTRY = 179905 }
enum BattlegroundSpiritHealers { BG_NPC_SPIRIT_GUIDE_ALLIANCE = 13116 , BG_NPC_SPIRIT_GUIDE_HORDE = 13117 }
enum BattlegroundHonorableDefenders { BG_NPC_HON_DEFENDER_TRIGGER_A = 35379 , BG_NPC_HON_DEFENDER_TRIGGER_H = 35380 , BG_NPC_HON_DEFENDER_TRIGGER_25_A = 36349 , BG_NPC_HON_DEFENDER_TRIGGER_25_H = 36350 }
enum BattleGroundRandomRewards {
BG_REWARD_WINNER_HONOR_FIRST = 30 , BG_REWARD_WINNER_ARENA_FIRST = 25 , BG_REWARD_WINNER_HONOR_LAST = 15 , BG_REWARD_WINNER_ARENA_LAST = 0 ,
BG_REWARD_LOOSER_HONOR_FIRST = 5 , BG_REWARD_LOOSER_HONOR_LAST = 5
}
enum BattleGroundStatus {
STATUS_NONE = 0 , STATUS_WAIT_QUEUE = 1 , STATUS_WAIT_JOIN = 2 , STATUS_IN_PROGRESS = 3 ,
STATUS_WAIT_LEAVE = 4
}
enum BattleGroundQueueTypeId {
BATTLEGROUND_QUEUE_NONE = 0 , BATTLEGROUND_QUEUE_AV = 1 , BATTLEGROUND_QUEUE_WS = 2 , BATTLEGROUND_QUEUE_AB = 3 ,
BATTLEGROUND_QUEUE_EY = 4 , BATTLEGROUND_QUEUE_SA = 5 , BATTLEGROUND_QUEUE_IC = 6 , BATTLEGROUND_QUEUE_RB = 7 ,
BATTLEGROUND_QUEUE_2v2 = 8 , BATTLEGROUND_QUEUE_3v3 = 9 , BATTLEGROUND_QUEUE_5v5 = 10 , MAX_BATTLEGROUND_QUEUE_TYPES = 11
}
enum ScoreType {
SCORE_KILLING_BLOWS = 1 , SCORE_DEATHS = 2 , SCORE_HONORABLE_KILLS = 3 , SCORE_BONUS_HONOR = 4 ,
SCORE_DAMAGE_DONE = 5 , SCORE_HEALING_DONE = 6 , SCORE_FLAG_CAPTURES = 7 , SCORE_FLAG_RETURNS = 8 ,
SCORE_BASES_ASSAULTED = 9 , SCORE_BASES_DEFENDED = 10 , SCORE_GRAVEYARDS_ASSAULTED = 11 , SCORE_GRAVEYARDS_DEFENDED = 12 ,
SCORE_TOWERS_ASSAULTED = 13 , SCORE_TOWERS_DEFENDED = 14 , SCORE_SECONDARY_OBJECTIVES = 15 , SCORE_GATES_DESTROYED = 16 ,
SCORE_DEMOLISHERS_DESTROYED = 17
}
enum BattleGroundType { TYPE_BATTLEGROUND = 3 , TYPE_ARENA = 4 }
enum BattleGroundStartingEvents {
BG_STARTING_EVENT_NONE = 0x00 , BG_STARTING_EVENT_1 = 0x01 , BG_STARTING_EVENT_2 = 0x02 , BG_STARTING_EVENT_3 = 0x04 ,
BG_STARTING_EVENT_4 = 0x08
}
enum BattleGroundStartingEventsIds { BG_STARTING_EVENT_FIRST = 0 , BG_STARTING_EVENT_SECOND = 1 , BG_STARTING_EVENT_THIRD = 2 , BG_STARTING_EVENT_FOURTH = 3 }
enum GroupJoinBattlegroundResult {
ERR_GROUP_JOIN_BATTLEGROUND_FAIL = 0 , ERR_BATTLEGROUND_NONE = -1 , ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS = -2 , ERR_ARENA_TEAM_PARTY_SIZE = -3 ,
ERR_BATTLEGROUND_TOO_MANY_QUEUES = -4 , ERR_BATTLEGROUND_CANNOT_QUEUE_FOR_RATED = -5 , ERR_BATTLEDGROUND_QUEUED_FOR_RATED = -6 , ERR_BATTLEGROUND_TEAM_LEFT_QUEUE = -7 ,
ERR_BATTLEGROUND_NOT_IN_BATTLEGROUND = -8 , ERR_BATTLEGROUND_JOIN_XP_GAIN = -9 , ERR_BATTLEGROUND_JOIN_RANGE_INDEX = -10 , ERR_BATTLEGROUND_JOIN_TIMED_OUT = -11 ,
ERR_BATTLEGROUND_JOIN_FAILED = -12 , ERR_LFG_CANT_USE_BATTLEGROUND = -13 , ERR_IN_RANDOM_BG = -14 , ERR_IN_NON_RANDOM_BG = -15
}
Functions
void FillInitialWorldState (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldState (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void FillInitialWorldState (ByteBuffer &data, uint32 &count, uint32 state, bool value)
void FillInitialWorldState (ByteBuffer &data, uint32 &count, WorldStatePair const *array)
Variables
const uint32 Buff_Entries [3] = { BG_OBJECTID_SPEEDBUFF_ENTRY, BG_OBJECTID_REGENBUFF_ENTRY, BG_OBJECTID_BERSERKERBUFF_ENTRY }
Macro Definition Documentation
ARENA_BUFF_EVENT
#define ARENA_BUFF_EVENT 253
Definition at line 34 of file BattleGround.h.
ARENA_TIMELIMIT_POINTS_LOSS
#define ARENA_TIMELIMIT_POINTS_LOSS -16
Definition at line 35 of file BattleGround.h.
BG_EVENT_DOOR
#define BG_EVENT_DOOR 254
Definition at line 31 of file BattleGround.h.
BG_EVENT_NONE
#define BG_EVENT_NONE 255
Definition at line 29 of file BattleGround.h.
BG_STARTING_EVENT_COUNT
#define BG_STARTING_EVENT_COUNT 4
Definition at line 270 of file BattleGround.h.
Enumeration Type Documentation
ArenaSpells
enum ArenaSpells : uint32
Enumerator
SPELL_LAST_MAN_STANDING
SPELL_ARENA_PREPARATION
SPELL_ALLIANCE_GOLD_FLAG
SPELL_ALLIANCE_GREEN_FLAG
SPELL_HORDE_GOLD_FLAG
SPELL_HORDE_GREEN_FLAG
SPELL_ARENA_DAMPENING
Definition at line 103 of file BattleGround.h.
BattleGroundBuffObjects
enum BattleGroundBuffObjects
Enumerator
BG_OBJECTID_SPEEDBUFF_ENTRY
BG_OBJECTID_REGENBUFF_ENTRY
BG_OBJECTID_BERSERKERBUFF_ENTRY
Definition at line 147 of file BattleGround.h.
BattlegroundHonorableDefenders
enum BattlegroundHonorableDefenders
Enumerator
BG_NPC_HON_DEFENDER_TRIGGER_A
BG_NPC_HON_DEFENDER_TRIGGER_H
BG_NPC_HON_DEFENDER_TRIGGER_25_A
BG_NPC_HON_DEFENDER_TRIGGER_25_H
Definition at line 160 of file BattleGround.h.
BattleGroundMarks
enum BattleGroundMarks
Enumerator
SPELL_WS_MARK_LOSER
SPELL_WS_MARK_WINNER
SPELL_AB_MARK_LOSER
SPELL_AB_MARK_WINNER
SPELL_AV_MARK_LOSER
SPELL_AV_MARK_WINNER
SPELL_SA_MARK_LOSER
SPELL_SA_MARK_WINNER
Definition at line 85 of file BattleGround.h.
BattleGroundMarksCount
enum BattleGroundMarksCount
Enumerator
ITEM_WINNER_COUNT
ITEM_LOSER_COUNT
Definition at line 97 of file BattleGround.h.
BattleGroundQuests
enum BattleGroundQuests
Enumerator
SPELL_WS_QUEST_REWARD_1
SPELL_WS_QUEST_REWARD_2
SPELL_WS_QUEST_REWARD_3
SPELL_WS_QUEST_REWARD_4
SPELL_WS_QUEST_REWARD_5
SPELL_AB_QUEST_REWARD_1
SPELL_AB_QUEST_REWARD_2
SPELL_AB_QUEST_REWARD_3
SPELL_AB_QUEST_REWARD_4
SPELL_AV_QUEST_REWARD_1
SPELL_AV_QUEST_REWARD_2
SPELL_AV_QUEST_REWARD_3
SPELL_EY_QUEST_REWARD_1
SPELL_EY_QUEST_REWARD_2
SPELL_SA_QUEST_REWARD
SPELL_IC_QUEST_REWARD
Definition at line 60 of file BattleGround.h.
BattleGroundQueueTypeId
enum BattleGroundQueueTypeId
Enumerator
BATTLEGROUND_QUEUE_NONE
BATTLEGROUND_QUEUE_AV
BATTLEGROUND_QUEUE_WS
BATTLEGROUND_QUEUE_AB
BATTLEGROUND_QUEUE_EY
BATTLEGROUND_QUEUE_SA
BATTLEGROUND_QUEUE_IC
BATTLEGROUND_QUEUE_RB
BATTLEGROUND_QUEUE_2v2
BATTLEGROUND_QUEUE_3v3
BATTLEGROUND_QUEUE_5v5
MAX_BATTLEGROUND_QUEUE_TYPES
Definition at line 205 of file BattleGround.h.
BattleGroundRandomRewards
enum BattleGroundRandomRewards
Enumerator
BG_REWARD_WINNER_HONOR_FIRST
BG_REWARD_WINNER_ARENA_FIRST
BG_REWARD_WINNER_HONOR_LAST
BG_REWARD_WINNER_ARENA_LAST
BG_REWARD_LOOSER_HONOR_FIRST
BG_REWARD_LOOSER_HONOR_LAST
Definition at line 168 of file BattleGround.h.
BattleGroundSounds
enum BattleGroundSounds
Enumerator
SOUND_HORDE_WINS
SOUND_ALLIANCE_WINS
SOUND_BG_START
Definition at line 53 of file BattleGround.h.
BattleGroundSpells
enum BattleGroundSpells : uint32
Enumerator
SPELL_GRAVEYARD_TELEPORT
SPELL_PREPARATION
SPELL_RECENTLY_DROPPED_FLAG
SPELL_AURA_PLAYER_INACTIVE
SPELL_BATTLEGROUND_DAMPENING
Definition at line 114 of file BattleGround.h.
BattlegroundSpiritHealers
enum BattlegroundSpiritHealers
Enumerator
BG_NPC_SPIRIT_GUIDE_ALLIANCE
BG_NPC_SPIRIT_GUIDE_HORDE
Definition at line 154 of file BattleGround.h.
BattleGroundStartingEvents
enum BattleGroundStartingEvents
Enumerator
BG_STARTING_EVENT_NONE
BG_STARTING_EVENT_1
BG_STARTING_EVENT_2
BG_STARTING_EVENT_3
BG_STARTING_EVENT_4
Definition at line 254 of file BattleGround.h.
BattleGroundStartingEventsIds
enum BattleGroundStartingEventsIds
Enumerator
BG_STARTING_EVENT_FIRST
BG_STARTING_EVENT_SECOND
BG_STARTING_EVENT_THIRD
BG_STARTING_EVENT_FOURTH
Definition at line 263 of file BattleGround.h.
BattleGroundStartTimeIntervals
enum BattleGroundStartTimeIntervals
Enumerator
BG_START_DELAY_2M
BG_START_DELAY_1M
BG_START_DELAY_30S
BG_START_DELAY_15S
BG_START_DELAY_NONE
Definition at line 138 of file BattleGround.h.
BattleGroundStatus
enum BattleGroundStatus
Enumerator
STATUS_NONE
STATUS_WAIT_QUEUE
STATUS_WAIT_JOIN
STATUS_IN_PROGRESS
STATUS_WAIT_LEAVE
Definition at line 180 of file BattleGround.h.
BattleGroundTimeIntervals
enum BattleGroundTimeIntervals
Enumerator
CHECK_PLAYER_POSITION_INVERVAL
RESURRECTION_INTERVAL
INVITATION_REMIND_TIME
INVITE_ACCEPT_WAIT_TIME
TIME_TO_AUTOREMOVE
MAX_OFFLINE_TIME
RESPAWN_ONE_DAY
RESPAWN_IMMEDIATELY
BUFF_RESPAWN_TIME
ARENA_SPAWN_BUFF_OBJECTS
ARENA_FORCED_DRAW
Definition at line 123 of file BattleGround.h.
BattleGroundType
enum BattleGroundType
Enumerator
TYPE_BATTLEGROUND
TYPE_ARENA
Definition at line 248 of file BattleGround.h.
GroupJoinBattlegroundResult
enum GroupJoinBattlegroundResult
Enumerator
ERR_GROUP_JOIN_BATTLEGROUND_FAIL
ERR_BATTLEGROUND_NONE
ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS
ERR_ARENA_TEAM_PARTY_SIZE
ERR_BATTLEGROUND_TOO_MANY_QUEUES
ERR_BATTLEGROUND_CANNOT_QUEUE_FOR_RATED
ERR_BATTLEDGROUND_QUEUED_FOR_RATED
ERR_BATTLEGROUND_TEAM_LEFT_QUEUE
ERR_BATTLEGROUND_NOT_IN_BATTLEGROUND
ERR_BATTLEGROUND_JOIN_XP_GAIN
ERR_BATTLEGROUND_JOIN_RANGE_INDEX
ERR_BATTLEGROUND_JOIN_TIMED_OUT
ERR_BATTLEGROUND_JOIN_FAILED
ERR_LFG_CANT_USE_BATTLEGROUND
ERR_IN_RANDOM_BG
ERR_IN_NON_RANDOM_BG
Definition at line 272 of file BattleGround.h.
ScoreType
enum ScoreType
Enumerator
SCORE_KILLING_BLOWS
SCORE_DEATHS
SCORE_HONORABLE_KILLS
SCORE_BONUS_HONOR
SCORE_DAMAGE_DONE
SCORE_HEALING_DONE
SCORE_FLAG_CAPTURES
SCORE_FLAG_RETURNS
SCORE_BASES_ASSAULTED
SCORE_BASES_DEFENDED
SCORE_GRAVEYARDS_ASSAULTED
SCORE_GRAVEYARDS_DEFENDED
SCORE_TOWERS_ASSAULTED
SCORE_TOWERS_DEFENDED
SCORE_SECONDARY_OBJECTIVES
SCORE_GATES_DESTROYED
SCORE_DEMOLISHERS_DESTROYED
Definition at line 222 of file BattleGround.h.
Function Documentation
FillInitialWorldState() [1/4]
void FillInitialWorldState (ByteBuffer & data, uint32 & count, uint32 state, bool value) inline
Definition at line 785 of file BattleGround.h.
FillInitialWorldState() [2/4]
void FillInitialWorldState (ByteBuffer & data, uint32 & count, uint32 state, int32 value) inline
Definition at line 778 of file BattleGround.h.
FillInitialWorldState() [3/4]
void FillInitialWorldState (ByteBuffer & data, uint32 & count, uint32 state, uint32 value) inline
Definition at line 771 of file BattleGround.h.
Referenced by Player::FillBGWeekendWorldStates(), BattlefieldWG::FillInitialWorldStates(), OutdoorPvPEP::FillInitialWorldStates(), OutdoorPvPHP::FillInitialWorldStates(), OutdoorPvPNA::FillInitialWorldStates(), OutdoorPvPSI::FillInitialWorldStates(), OutdoorPvPTF::FillInitialWorldStates(), OutdoorPvPZM::FillInitialWorldStates(), and Player::SendInitWorldStates().
FillInitialWorldState() [4/4]
void FillInitialWorldState (ByteBuffer & data, uint32 & count, WorldStatePair const * array) inline
Definition at line 798 of file BattleGround.h.
References WorldStatePair::state.
Variable Documentation
Buff_Entries
const uint32 Buff_Entries[3] = { BG_OBJECTID_SPEEDBUFF_ENTRY, BG_OBJECTID_REGENBUFF_ENTRY, BG_OBJECTID_BERSERKERBUFF_ENTRY }
Definition at line 178 of file BattleGround.h.