CMaNGOS_WoTLK: blackwing_lair.cpp File Reference
blackwing_lair.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackwing_lair.h"
Data Structures
struct go_ai_suppression
Functions
InstanceData * GetInstanceData_instance_blackwing_lair (Map *pMap)
GameObjectAI * GetAI_go_suppression (GameObject *go)
bool ProcessEventId_event_weekly_chromatic_selection (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_instance_blackwing_lair ()
Function Documentation
AddSC_instance_blackwing_lair()
void AddSC_instance_blackwing_lair ()
Definition at line 830 of file blackwing_lair.cpp.
References GetAI_go_suppression(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_blackwing_lair(), Script::Name, Script::pProcessEventId, ProcessEventId_event_weekly_chromatic_selection(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_go_suppression()
GameObjectAI* GetAI_go_suppression (GameObject * go)
Definition at line 779 of file blackwing_lair.cpp.
Referenced by AddSC_instance_blackwing_lair().
GetInstanceData_instance_blackwing_lair()
InstanceData* GetInstanceData_instance_blackwing_lair (Map * pMap)
Definition at line 724 of file blackwing_lair.cpp.
Referenced by AddSC_instance_blackwing_lair().
ProcessEventId_event_weekly_chromatic_selection()
bool ProcessEventId_event_weekly_chromatic_selection (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 788 of file blackwing_lair.cpp.
References Object::GetTypeId(), and TYPEID_UNIT.
Referenced by AddSC_instance_blackwing_lair().