CMaNGOS_WoTLK: blackrock_depths.cpp File Reference
blackrock_depths.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackrock_depths.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_grimstoneAI
struct npc_phalanxAI
struct npc_mistress_nagmaraAI
struct npc_rocknotAI
struct npc_marshal_windsorAI
struct npc_hurley_blackbreathAI
struct boss_plugger_spazzringAI
struct npc_ironhand_guardianAI
Enumerations
enum { SAY_GUARD_AGGRO = -1230043 }
enum {
SAY_START_1 = -1230004 , SAY_START_2 = -1230005 , SAY_OPEN_EAST_GATE = -1230006 , SAY_SUMMON_BOSS_1 = -1230007 ,
SAY_SUMMON_BOSS_2 = -1230008 , SAY_OPEN_NORTH_GATE = -1230009 , NPC_GRIMSTONE = 10096 , DATA_BANNER_BEFORE_EVENT = 5 ,
MAX_THELDREN_ADDS = 4 , MAX_POSSIBLE_THELDREN_ADDS = 8 , SPELL_SUMMON_THELRIN_DND = 27517 , SPELL_ASHCROMBES_TELEPORT_A = 15742 ,
SPELL_ASHCROMBES_TELEPORT_B = 6422 , SPELL_ARENA_FLASH_A = 15737 , SPELL_ARENA_FLASH_B = 15739 , SPELL_ARENA_FLASH_C = 15740 ,
SPELL_ARENA_FLASH_D = 15741 , QUEST_THE_CHALLENGE = 9015 , NPC_THELDREN_QUEST_CREDIT = 16166
}
enum SpawnPosition { POS_EAST = 0 , POS_NORTH = 1 , POS_GRIMSTONE = 2 }
enum RingOfLawPhases { PHASE_MOBS = 0 , PHASE_BOSS = 2 , PHASE_GLADIATORS = 3 }
enum { YELL_PHALANX_AGGRO = -1230040 , SPELL_THUNDERCLAP = 15588 , SPELL_MIGHTY_BLOW = 14099 , SPELL_FIREBALL_VOLLEY = 15285 }
enum {
GOSSIP_ITEM_NAGMARA = -3230003 , GOSSIP_ID_NAGMARA = 2727 , GOSSIP_ID_NAGMARA_2 = 2729 , SPELL_POTION_LOVE = 14928 ,
SPELL_NAGMARA_ROCKNOT = 15064 , SAY_NAGMARA_1 = -1230066 , SAY_NAGMARA_2 = -1230067 , TEXTEMOTE_NAGMARA = -1230068 ,
TEXTEMOTE_ROCKNOT = -1230069 , QUEST_POTION_LOVE = 4201
}
enum {
SAY_GOT_BEER = -1230000 , SAY_MORE_BEER = -1230036 , SAY_BARREL_1 = -1230044 , SAY_BARREL_2 = -1230045 ,
SAY_BARREL_3 = -1230046 , SPELL_DRUNKEN_RAGE = 14872 , QUEST_ALE = 4295
}
enum {
SAY_WINDSOR_AGGRO1 = -1230011 , SAY_WINDSOR_AGGRO2 = -1230012 , SAY_WINDSOR_AGGRO3 = -1230013 , SAY_WINDSOR_START = -1230014 ,
SAY_WINDSOR_CELL_DUGHAL_1 = -1230015 , SAY_WINDSOR_CELL_DUGHAL_3 = -1230016 , SAY_WINDSOR_EQUIPMENT_1 = -1230017 , SAY_WINDSOR_EQUIPMENT_2 = -1230018 ,
SAY_WINDSOR_EQUIPMENT_3 = -1230019 , SAY_WINDSOR_EQUIPMENT_4 = -1230020 , SAY_WINDSOR_CELL_JAZ_1 = -1230021 , SAY_WINDSOR_CELL_JAZ_2 = -1230022 ,
SAY_WINDSOR_CELL_SHILL_1 = -1230023 , SAY_WINDSOR_CELL_SHILL_2 = -1230024 , SAY_WINDSOR_CELL_SHILL_3 = -1230025 , SAY_WINDSOR_CELL_CREST_1 = -1230026 ,
SAY_WINDSOR_CELL_CREST_2 = -1230027 , SAY_WINDSOR_CELL_TOBIAS_1 = -1230028 , SAY_WINDSOR_CELL_TOBIAS_2 = -1230029 , SAY_WINDSOR_FREE_1 = -1230030 ,
SAY_WINDSOR_FREE_2 = -1230031 , SAY_DUGHAL_FREE = -1230010 , GOSSIP_ID_DUGHAL = -3230000 , GOSSIP_TEXT_ID_DUGHAL = 2846 ,
SAY_TOBIAS_FREE_1 = -1230032 , SAY_TOBIAS_FREE_2 = -1230033 , GOSSIP_ID_TOBIAS = -3230001 , GOSSIP_TEXT_ID_TOBIAS = 2847 ,
NPC_REGINALD_WINDSOR = 9682 , QUEST_JAIL_BREAK = 4322 , SPELL_WINDSORS_FRENZY = 15167
}
enum {
YELL_HURLEY_SPAWN = -1230041 , SAY_HURLEY_AGGRO = -1230042 , SPELL_FLAME_BREATH = 9573 , NPC_RIBBLY_SCREWSPIGOT = 9543 ,
NPC_RIBBLY_CRONY = 10043
}
enum { SAY_DOOMREL_START_EVENT = -1230003 , GOSSIP_ITEM_CHALLENGE = -3230002 , GOSSIP_TEXT_ID_CHALLENGE = 2601 }
enum {
SAY_OOC_1 = -1230050 , SAY_OOC_2 = -1230051 , SAY_OOC_3 = -1230052 , SAY_OOC_4 = -1230053 ,
YELL_STOLEN_1 = -1230054 , YELL_STOLEN_2 = -1230055 , YELL_STOLEN_3 = -1230056 , YELL_AGRRO_1 = -1230057 ,
YELL_AGRRO_2 = -1230058 , YELL_PICKPOCKETED = -1230059 , SPELL_BANISH = 8994 , SPELL_CURSE_OF_TONGUES = 13338 ,
SPELL_DEMON_ARMOR = 13787 , SPELL_IMMOLATE = 12742 , SPELL_SHADOW_BOLT = 12739 , SPELL_PICKPOCKET = 921
}
enum { SPELL_GOUT_OF_FLAME = 15529 , SPELL_STONED_VISUAL = 15533 }
Functions
bool GOUse_go_bar_beer_keg (Player *, GameObject *pGo)
bool GOUse_go_shadowforge_brazier (Player *, GameObject *pGo)
bool GOUse_go_relic_coffer_door (Player *, GameObject *pGo)
bool AreaTrigger_at_shadowforge_bridge (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_ring_of_law (Player *pPlayer, AreaTriggerEntry const *pAt)
UnitAI * GetAI_npc_grimstone (Creature *pCreature)
bool EffectDummyCreature_spell_banner_of_provocation (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_phalanx (Creature *pCreature)
bool GossipHello_npc_mistress_nagmara (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_mistress_nagmara (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool QuestRewarded_npc_mistress_nagmara (Player *, Creature *pCreature, Quest const *pQuest)
UnitAI * GetAI_npc_mistress_nagmara (Creature *pCreature)
UnitAI * GetAI_npc_rocknot (Creature *pCreature)
bool QuestRewarded_npc_rocknot (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
UnitAI * GetAI_npc_marshal_windsor (Creature *pCreature)
bool QuestAccept_npc_marshal_windsor (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GossipHello_npc_dughal_stormwing (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_dughal_stormwing (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipHello_npc_tobias_seecher (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_tobias_seecher (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_hurley_blackbreath (Creature *pCreature)
bool GossipHello_boss_doomrel (Player *pPlayer, Creature *pCreature)
bool GossipSelect_boss_doomrel (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_boss_plugger_spazzring (Creature *pCreature)
bool GOUse_go_bar_ale_mug (Player *pPlayer, GameObject *pGo)
UnitAI * GetAI_npc_ironhand_guardian (Creature *creature)
void AddSC_blackrock_depths ()
Variables
static const float aGuardSpawnPositions [2][4]
static const float aSpawnPositions [3][4]
static const uint32 aGladiator [MAX_POSSIBLE_THELDREN_ADDS] = {NPC_LEFTY, NPC_ROTFANG, NPC_SNOKH, NPC_MALGEN, NPC_KORV, NPC_REZZNIK, NPC_VAJASHNI, NPC_VOLIDA}
static const uint32 aRingMob [2][6]
static const uint32 aRingBoss [] = {NPC_GOROSH, NPC_GRIZZLE, NPC_EVISCERATOR, NPC_OKTHOR, NPC_ANUBSHIAH, NPC_HEDRUM}
static const float aPosNagmaraRocknot [3] = {878.1779f, -222.0662f, -49.96714f}
static const int aRandomSays [] = { SAY_OOC_1, SAY_OOC_2, SAY_OOC_3, SAY_OOC_4 }
static const int aRandomYells [] = { YELL_STOLEN_1, YELL_STOLEN_2, YELL_STOLEN_3 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GUARD_AGGRO
Definition at line 107 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START_1
SAY_START_2
SAY_OPEN_EAST_GATE
SAY_SUMMON_BOSS_1
SAY_SUMMON_BOSS_2
SAY_OPEN_NORTH_GATE
NPC_GRIMSTONE
DATA_BANNER_BEFORE_EVENT
MAX_THELDREN_ADDS
MAX_POSSIBLE_THELDREN_ADDS
SPELL_SUMMON_THELRIN_DND
SPELL_ASHCROMBES_TELEPORT_A
SPELL_ASHCROMBES_TELEPORT_B
SPELL_ARENA_FLASH_A
SPELL_ARENA_FLASH_B
SPELL_ARENA_FLASH_C
SPELL_ARENA_FLASH_D
QUEST_THE_CHALLENGE
NPC_THELDREN_QUEST_CREDIT
Definition at line 152 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
YELL_PHALANX_AGGRO
SPELL_THUNDERCLAP
SPELL_MIGHTY_BLOW
SPELL_FIREBALL_VOLLEY
Definition at line 544 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_NAGMARA
GOSSIP_ID_NAGMARA
GOSSIP_ID_NAGMARA_2
SPELL_POTION_LOVE
SPELL_NAGMARA_ROCKNOT
SAY_NAGMARA_1
SAY_NAGMARA_2
TEXTEMOTE_NAGMARA
TEXTEMOTE_ROCKNOT
QUEST_POTION_LOVE
Definition at line 687 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_GOT_BEER
SAY_MORE_BEER
SAY_BARREL_1
SAY_BARREL_2
SAY_BARREL_3
SPELL_DRUNKEN_RAGE
QUEST_ALE
Definition at line 858 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_WINDSOR_AGGRO1
SAY_WINDSOR_AGGRO2
SAY_WINDSOR_AGGRO3
SAY_WINDSOR_START
SAY_WINDSOR_CELL_DUGHAL_1
SAY_WINDSOR_CELL_DUGHAL_3
SAY_WINDSOR_EQUIPMENT_1
SAY_WINDSOR_EQUIPMENT_2
SAY_WINDSOR_EQUIPMENT_3
SAY_WINDSOR_EQUIPMENT_4
SAY_WINDSOR_CELL_JAZ_1
SAY_WINDSOR_CELL_JAZ_2
SAY_WINDSOR_CELL_SHILL_1
SAY_WINDSOR_CELL_SHILL_2
SAY_WINDSOR_CELL_SHILL_3
SAY_WINDSOR_CELL_CREST_1
SAY_WINDSOR_CELL_CREST_2
SAY_WINDSOR_CELL_TOBIAS_1
SAY_WINDSOR_CELL_TOBIAS_2
SAY_WINDSOR_FREE_1
SAY_WINDSOR_FREE_2
SAY_DUGHAL_FREE
GOSSIP_ID_DUGHAL
GOSSIP_TEXT_ID_DUGHAL
SAY_TOBIAS_FREE_1
SAY_TOBIAS_FREE_2
GOSSIP_ID_TOBIAS
GOSSIP_TEXT_ID_TOBIAS
NPC_REGINALD_WINDSOR
QUEST_JAIL_BREAK
SPELL_WINDSORS_FRENZY
Definition at line 1110 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
YELL_HURLEY_SPAWN
SAY_HURLEY_AGGRO
SPELL_FLAME_BREATH
NPC_RIBBLY_SCREWSPIGOT
NPC_RIBBLY_CRONY
Definition at line 1439 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_DOOMREL_START_EVENT
GOSSIP_ITEM_CHALLENGE
GOSSIP_TEXT_ID_CHALLENGE
Definition at line 1573 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_OOC_1
SAY_OOC_2
SAY_OOC_3
SAY_OOC_4
YELL_STOLEN_1
YELL_STOLEN_2
YELL_STOLEN_3
YELL_AGRRO_1
YELL_AGRRO_2
YELL_PICKPOCKETED
SPELL_BANISH
SPELL_CURSE_OF_TONGUES
SPELL_DEMON_ARMOR
SPELL_IMMOLATE
SPELL_SHADOW_BOLT
SPELL_PICKPOCKET
Definition at line 1612 of file blackrock_depths.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GOUT_OF_FLAME
SPELL_STONED_VISUAL
Definition at line 1836 of file blackrock_depths.cpp.
RingOfLawPhases
enum RingOfLawPhases
Enumerator
PHASE_MOBS
PHASE_BOSS
PHASE_GLADIATORS
Definition at line 202 of file blackrock_depths.cpp.
SpawnPosition
enum SpawnPosition
Enumerator
POS_EAST
POS_NORTH
POS_GRIMSTONE
Definition at line 180 of file blackrock_depths.cpp.
Function Documentation
AddSC_blackrock_depths()
void AddSC_blackrock_depths ()
Definition at line 1899 of file blackrock_depths.cpp.
References AreaTrigger_at_ring_of_law(), AreaTrigger_at_shadowforge_bridge(), EffectDummyCreature_spell_banner_of_provocation(), Script::GetAI, GetAI_boss_plugger_spazzring(), GetAI_npc_grimstone(), GetAI_npc_hurley_blackbreath(), GetAI_npc_ironhand_guardian(), GetAI_npc_marshal_windsor(), GetAI_npc_mistress_nagmara(), GetAI_npc_phalanx(), GetAI_npc_rocknot(), GossipHello_boss_doomrel(), GossipHello_npc_dughal_stormwing(), GossipHello_npc_mistress_nagmara(), GossipHello_npc_tobias_seecher(), GossipSelect_boss_doomrel(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_mistress_nagmara(), GossipSelect_npc_tobias_seecher(), GOUse_go_bar_ale_mug(), GOUse_go_bar_beer_keg(), GOUse_go_relic_coffer_door(), GOUse_go_shadowforge_brazier(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, QuestAccept_npc_marshal_windsor(), QuestRewarded_npc_mistress_nagmara(), QuestRewarded_npc_rocknot(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_ring_of_law()
bool AreaTrigger_at_ring_of_law (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 209 of file blackrock_depths.cpp.
References aSpawnPositions, DATA_BANNER_BEFORE_EVENT, DONE, WorldObject::GetInstanceData(), IN_PROGRESS, Player::IsGameMaster(), NPC_GRIMSTONE, POS_GRIMSTONE, SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_RING_OF_LAW, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_blackrock_depths().
AreaTrigger_at_shadowforge_bridge()
bool AreaTrigger_at_shadowforge_bridge (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 113 of file blackrock_depths.cpp.
References aGuardSpawnPositions, DoDisplayText(), DONE, WorldObject::GetContactPoint(), WorldObject::GetInstanceData(), Unit::IsAlive(), Player::IsGameMaster(), NPC_ANVILRAGE_GUARDMAN, NPC_LOREGRAIN, SAY_GUARD_AGGRO, Creature::SetWalk(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_BRIDGE.
Referenced by AddSC_blackrock_depths().
EffectDummyCreature_spell_banner_of_provocation()
bool EffectDummyCreature_spell_banner_of_provocation (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 527 of file blackrock_depths.cpp.
References DATA_BANNER_BEFORE_EVENT, DONE, EFFECT_INDEX_0, instance_blackrock_depths::GetData(), WorldObject::GetInstanceData(), IN_PROGRESS, instance_blackrock_depths::SetData(), SPECIAL, SPELL_SUMMON_THELRIN_DND, and TYPE_RING_OF_LAW.
Referenced by AddSC_blackrock_depths().
GetAI_boss_plugger_spazzring()
UnitAI* GetAI_boss_plugger_spazzring (Creature * pCreature)
Definition at line 1799 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_grimstone()
UnitAI* GetAI_npc_grimstone (Creature * pCreature)
Definition at line 522 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_hurley_blackbreath()
UnitAI* GetAI_npc_hurley_blackbreath (Creature * pCreature)
Definition at line 1564 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_ironhand_guardian()
UnitAI* GetAI_npc_ironhand_guardian (Creature * creature)
Definition at line 1894 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_marshal_windsor()
UnitAI* GetAI_npc_marshal_windsor (Creature * pCreature)
Definition at line 1349 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_mistress_nagmara()
UnitAI* GetAI_npc_mistress_nagmara (Creature * pCreature)
Definition at line 849 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_phalanx()
UnitAI* GetAI_npc_phalanx (Creature * pCreature)
Definition at line 678 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GetAI_npc_rocknot()
UnitAI* GetAI_npc_rocknot (Creature * pCreature)
Definition at line 1072 of file blackrock_depths.cpp.
Referenced by AddSC_blackrock_depths().
GossipHello_boss_doomrel()
bool GossipHello_boss_doomrel (Player * pPlayer, Creature * pCreature)
Definition at line 1580 of file blackrock_depths.cpp.
References FAIL, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_CHALLENGE, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_CHALLENGE, NOT_STARTED, and TYPE_TOMB_OF_SEVEN.
Referenced by AddSC_blackrock_depths().
GossipHello_npc_dughal_stormwing()
bool GossipHello_npc_dughal_stormwing (Player * pPlayer, Creature * pCreature)
Definition at line 1373 of file blackrock_depths.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ID_DUGHAL, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_DUGHAL, QUEST_JAIL_BREAK, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_blackrock_depths().
GossipHello_npc_mistress_nagmara()
bool GossipHello_npc_mistress_nagmara (Player * pPlayer, Creature * pCreature)
Definition at line 804 of file blackrock_depths.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ID_NAGMARA, GOSSIP_ID_NAGMARA_2, GOSSIP_ITEM_NAGMARA, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), QUEST_POTION_LOVE, and QUEST_STATUS_COMPLETE.
Referenced by AddSC_blackrock_depths().
GossipHello_npc_tobias_seecher()
bool GossipHello_npc_tobias_seecher (Player * pPlayer, Creature * pCreature)
Definition at line 1406 of file blackrock_depths.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ID_TOBIAS, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_TOBIAS, QUEST_JAIL_BREAK, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_blackrock_depths().
GossipSelect_boss_doomrel()
bool GossipSelect_boss_doomrel (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1592 of file blackrock_depths.cpp.
References DoScriptText(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, IN_PROGRESS, SAY_DOOMREL_START_EVENT, and TYPE_TOMB_OF_SEVEN.
Referenced by AddSC_blackrock_depths().
GossipSelect_npc_dughal_stormwing()
bool GossipSelect_npc_dughal_stormwing (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1382 of file blackrock_depths.cpp.
References DoScriptText(), WorldObject::GetInstanceData(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, MotionMaster::MoveWaypoint(), Object::RemoveFlag(), SAY_DUGHAL_FREE, Creature::SetWalk(), SPECIAL, TYPE_QUEST_JAIL_BREAK, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_blackrock_depths().
GossipSelect_npc_mistress_nagmara()
bool GossipSelect_npc_mistress_nagmara (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 820 of file blackrock_depths.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_blackrock_depths().
GossipSelect_npc_tobias_seecher()
bool GossipSelect_npc_tobias_seecher (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1415 of file blackrock_depths.cpp.
References DoScriptText(), WorldObject::GetInstanceData(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, MotionMaster::MoveWaypoint(), Object::RemoveFlag(), SAY_TOBIAS_FREE_1, SAY_TOBIAS_FREE_2, Creature::SetWalk(), SPECIAL, TYPE_QUEST_JAIL_BREAK, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and urand().
Referenced by AddSC_blackrock_depths().
GOUse_go_bar_ale_mug()
bool GOUse_go_bar_ale_mug (Player * pPlayer, GameObject * pGo)
Definition at line 1808 of file blackrock_depths.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, NPC_PLUGGER_SPAZZRING, SPECIAL, and TYPE_PLUGGER.
Referenced by AddSC_blackrock_depths().
GOUse_go_bar_beer_keg()
bool GOUse_go_bar_beer_keg (Player * , GameObject * pGo)
Definition at line 53 of file blackrock_depths.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, SPECIAL, and TYPE_HURLEY.
Referenced by AddSC_blackrock_depths().
GOUse_go_relic_coffer_door()
bool GOUse_go_relic_coffer_door (Player * , GameObject * pGo)
Definition at line 85 of file blackrock_depths.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, SPECIAL, and TYPE_VAULT.
Referenced by AddSC_blackrock_depths().
GOUse_go_shadowforge_brazier()
bool GOUse_go_shadowforge_brazier (Player * , GameObject * pGo)
Definition at line 69 of file blackrock_depths.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, and TYPE_LYCEUM.
Referenced by AddSC_blackrock_depths().
QuestAccept_npc_marshal_windsor()
bool QuestAccept_npc_marshal_windsor (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1354 of file blackrock_depths.cpp.
References Creature::AI(), FACTION_ESCORT_A_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_JAIL_BREAK, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_blackrock_depths().
QuestRewarded_npc_mistress_nagmara()
bool QuestRewarded_npc_mistress_nagmara (Player * , Creature * pCreature, Quest const * pQuest)
Definition at line 833 of file blackrock_depths.cpp.
References Creature::AI(), WorldObject::GetInstanceData(), Quest::GetQuestId(), and QUEST_POTION_LOVE.
Referenced by AddSC_blackrock_depths().
QuestRewarded_npc_rocknot()
bool QuestRewarded_npc_rocknot (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
Definition at line 1077 of file blackrock_depths.cpp.
References Creature::AI(), DONE, DoScriptText(), InstanceData::GetData(), WorldObject::GetInstanceData(), Quest::GetQuestId(), IN_PROGRESS, QUEST_ALE, SAY_GOT_BEER, InstanceData::SetData(), Unit::SetFacingToObject(), SPECIAL, and TYPE_ROCKNOT.
Referenced by AddSC_blackrock_depths().
Variable Documentation
aGladiator
const uint32 aGladiator[MAX_POSSIBLE_THELDREN_ADDS] = {NPC_LEFTY, NPC_ROTFANG, NPC_SNOKH, NPC_MALGEN, NPC_KORV, NPC_REZZNIK, NPC_VAJASHNI, NPC_VOLIDA} static
Definition at line 194 of file blackrock_depths.cpp.
Referenced by npc_grimstoneAI::npc_grimstoneAI().
aGuardSpawnPositions
const float aGuardSpawnPositions[2][4] static
Initial value:
=
{
    {642.3660f, -274.5155f, -43.10918f, 0.4712389f},
    {740.1137f, -283.3448f, -42.75082f, 2.8623400f}
}
Definition at line 101 of file blackrock_depths.cpp.
Referenced by AreaTrigger_at_shadowforge_bridge().
aPosNagmaraRocknot
const float aPosNagmaraRocknot[3] = {878.1779f, -222.0662f, -49.96714f} static
Definition at line 871 of file blackrock_depths.cpp.
Referenced by npc_rocknotAI::WaypointReached().
aRandomSays
const int aRandomSays[] = { SAY_OOC_1, SAY_OOC_2, SAY_OOC_3, SAY_OOC_4 } static
Definition at line 1635 of file blackrock_depths.cpp.
Referenced by boss_plugger_spazzringAI::UpdateAI().
aRandomYells
const int aRandomYells[] = { YELL_STOLEN_1, YELL_STOLEN_2, YELL_STOLEN_3 } static
Definition at line 1637 of file blackrock_depths.cpp.
Referenced by boss_plugger_spazzringAI::WarnThief().
aRingBoss
const uint32 aRingBoss[] = {NPC_GOROSH, NPC_GRIZZLE, NPC_EVISCERATOR, NPC_OKTHOR, NPC_ANUBSHIAH, NPC_HEDRUM} static
Definition at line 200 of file blackrock_depths.cpp.
Referenced by npc_grimstoneAI::UpdateEscortAI().
aRingMob
const uint32 aRingMob[2][6] static
Initial value:
=
{
    {NPC_WORM, NPC_STINGER, NPC_SCREECHER, NPC_THUNDERSNOUT, NPC_CREEPER, NPC_BEETLE},
    {4, 2, 5, 3, 3, 7}
}
Definition at line 195 of file blackrock_depths.cpp.
Referenced by npc_grimstoneAI::UpdateEscortAI().
aSpawnPositions
const float aSpawnPositions[3][4] static
Initial value:
=
{
    {608.960f, -235.322f, -53.907f, 1.857f},
    {644.300f, -175.989f, -53.739f, 3.418f},
    {625.559f, -205.618f, -52.735f, 2.609f}
}
Definition at line 187 of file blackrock_depths.cpp.
Referenced by AreaTrigger_at_ring_of_law(), instance_trial_of_the_crusader::DoHandleEventEpilogue(), npc_beast_combat_stalkerAI::DoSummonNextBeast(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_grimstoneAI::SummonRingMob(), npc_beast_combat_stalkerAI::UpdateAI(), and boss_icehowlAI::UpdateAI().