CMaNGOS_WoTLK: blades_edge_mountains.cpp File Reference
blades_edge_mountains.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/outland/world_outland.h"
#include "Entities/TemporarySpawn.h"
#include "Reputation/ReputationMgr.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "Spells/Spell.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct mobs_nether_drakeAI
struct npc_daranelleAI
struct npc_bloodmaul_stout_triggerAI
struct SimonGame
struct npc_simon_game_bunnyAI
struct npc_light_orb_collectorAI
struct npc_obelisk_triggerAI
struct npc_vimgol_AI
struct npc_vimgol_visual_bunnyAI
struct npc_vimgol_middle_bunnyAI
struct npc_bird_spiritAI
struct npc_bloodmaul_dire_wolfAI
struct Prophecy
struct go_aura_generator_000AI
struct npc_frequency_scanner
struct npc_fel_cannon
struct npc_warp_gate
struct npc_soulgrinderAI
struct npc_supplicantAI
struct npc_spirit_prisoner_of_bladespire
struct npc_deadsoul_orb
struct npc_evergrove_druidAI
struct npc_apexis_flayerAI
struct ExorcismFeather
struct KoiKoiDeath
struct go_nether_drake_egg_trapAI
struct Soaring
struct CoaxMarmot
Enumerations
enum {
SAY_NIHIL_1 = -1000169 , SAY_NIHIL_2 = -1000170 , SAY_NIHIL_3 = -1000171 , SAY_NIHIL_4 = -1000172 ,
SAY_NIHIL_INTERRUPT = -1000173 , MAX_ENTRIES = 4 , NPC_PROTO = 21821 , NPC_ADOLESCENT = 21817 ,
NPC_MATURE = 21820 , NPC_NIHIL = 21823 , SPELL_T_PHASE_MODULATOR = 37573 , SPELL_ARCANE_BLAST = 38881 ,
SPELL_MANA_BURN = 38884 , SPELL_INTANGIBLE_PRESENCE = 36513 , SPELL_RESISTANCES = 36630
}
enum { SAY_SPELL_INFLUENCE = -1000174 , SPELL_LASHHAN_CHANNEL = 36904 , SPELL_DISPELLING_ANALYSIS = 37028 }
enum {
SAY_BREW_1 = -1000156 , SAY_BREW_2 = -1000207 , SAY_BREW_3 = -1000208 , SPELL_INTOXICATION = 35240 ,
GO_TANKARD = 184315
}
enum {
SOUND_ID_BLUE = 11588 , SOUND_ID_GREEN = 11589 , SOUND_ID_RED = 11590 , SOUND_ID_YELLOW = 11591 ,
SOUND_ID_DISABLE_NODE = 11758 , SPELL_SIMON_GAME_START = 39993 , SPELL_PRE_EVENT_TIMER = 40041 , SPELL_PRE_GAME_BLUE_AURA = 40176 ,
SPELL_PRE_GAME_GREEN_AURA = 40177 , SPELL_PRE_GAME_RED_AURA = 40178 , SPELL_PRE_GAME_YELLOW_AURA = 40179 , SPELL_PRE_GAME_YELLOW_LARGE = 41110 ,
SPELL_PRE_GAME_RED_LARGE = 41111 , SPELL_PRE_GAME_GREEN_LARGE = 41112 , SPELL_PRE_GAME_BLUE_LARGE = 41113 , SPELL_BUTTON_PUSH_BLUE = 40244 ,
SPELL_BUTTON_PUSH_GREEN = 40245 , SPELL_BUTTON_PUSH_RED = 40246 , SPELL_BUTTON_PUSH_YELLOW = 40247 , SPELL_GAME_START_RED = 40169 ,
SPELL_GAME_START_BLUE = 40170 , SPELL_GAME_START_GREEN = 40171 , SPELL_GAME_START_YELLOW = 40172 , SPELL_GAME_END_BLUE = 40283 ,
SPELL_GAME_END_GREEN = 40284 , SPELL_GAME_END_RED = 40285 , SPELL_GAME_END_YELLOW = 40286 , SPELL_SWITCHED_ON = 40494 ,
SPELL_SWITCHED_OFF = 40495 , SPELL_VISUAL_LEVEL_START = 40436 , SPELL_VISUAL_GAME_FAILED = 40437 , SPELL_VISUAL_GAME_START = 40387 ,
SPELL_VISUAL_GAME_TICK = 40391 , SPELL_VISUAL_GAME_TICK_LARGE = 42019 , SPELL_INTROSPECTION_GREEN = 40055 , SPELL_INTROSPECTION_BLUE = 40165 ,
SPELL_INTROSPECTION_RED = 40166 , SPELL_INTROSPECTION_YELLOW = 40167 , SPELL_SIMON_BUTTON_PRESSED = 39999 , SPELL_GOOD_PRESS = 40063 ,
SPELL_BAD_PRESS = 41241 , SPELL_SIMON_GROUP_REWARD = 41952 , SPELL_APEXIS_VIBRATIONS = 40310 , SPELL_APEXIS_EMANATIONS = 40311 ,
SPELL_APEXIS_ENLIGHTENMENT = 40312 , NPC_SIMON_GAME_BUNNY = 22923 , NPC_SIMON_GAME_BUNNY_LARGE = 23378 , GO_APEXIS_RELIC = 185890 ,
GO_APEXIS_MONUMENT = 185944 , QUEST_AN_APEXIS_RELIC = 11058 , QUEST_RELICS_EMANATION = 11080 , COLOR_IDX_BLUE = 0 ,
COLOR_IDX_GREEN = 1 , COLOR_IDX_RED = 2 , COLOR_IDX_YELLOW = 3 , PHASE_INACTIVE = 0 ,
PHASE_LEVEL_PREPARE = 1 , PHASE_AI_GAME = 2 , PHASE_PLAYER_PREPARE = 3 , PHASE_PLAYER_GAME = 4 ,
PHASE_LEVEL_FINISHED = 5 , SIMON_BIG_LEVEL_SUMMON = 6 , SIMON_LEVEL_VIBRATIONS = 6 , SIMON_LEVEL_EMANATIONS = 8 ,
SIMON_LEVEL_ENLIGHTENMENT = 10 , MAX_SIMON_FAIL_TIMER = 5
}
enum { NPC_LIGHT_ORB_MINI = 20771 , NPC_KILL_CREDIT_TRIGGER = 21929 , MAX_PULL_DISTANCE = 20 }
enum { NPC_TRIGGER = 20736 , NPC_DOOMCRYER = 19963 , SPELL_GREEN_BEAM = 35846 }
enum {
NPC_VIMGOL_THE_VILE = 22911 , NPC_VIMGOL_MIDDLE_BUNNY = 23081 , SPELL_VIMGOL_POP_TEST_A = 39834 , SPELL_VIMGOL_POP_TEST_B = 39851 ,
SPELL_VIMGOL_POP_TEST_C = 39852 , SPELL_VIMGOL_POP_TEST_D = 39853 , SPELL_VIMGOL_POP_TEST_E = 39854 , SPELL_PENTAGRAM_BEAM = 39921 ,
SPELL_UNHOLY_GROWTH = 40545 , SPELL_SUMMONED_DEMON = 7741 , SPELL_INTERRUPT_UNHOLY_GROWTH = 40547 , SPELL_SUMMON_GRIMOIRE = 39862 ,
SPELL_SHADOWBOLT_VOLLEY = 40070 , SAY_VIMGOL_1 = 20773 , SAY_VIMGOL_2 = 21264
}
enum { NPC_TASKMASTER = 22160 }
enum {
SPELL_REND = 13443 , SPELL_RINAS_DIMINUTION_POWDER = 36310 , NPC_DIRE_WOLF_TRIGGER = 21176 , NPC_BLOODMAUL_DIRE_WOLF = 20058 ,
FACTION_FRIENDLY = 35
}
enum { UNDERSTAND_RAVENSPEECH_SPELL = 37466 , UNDERSTAND_RAVENSPEECH_AURA = 37642 , QUEST_WHISPERS_OF_THE_RAVEN_GOD = 10607 , NPC_VISION_RAVEN_GOD_TEMPLATE = 21861 }
enum {
SPELL_OSCILLATION_FIELD = 37408 , SPELL_OSCILLATING_FREQUENCY_SCANNER = 37407 , SPELL_SUMMON_TOP_BUNNY_CASTER = 37392 , SPELL_SUMMON_WYRM_FROM_BEYOND = 37503 ,
SPELL_SUMMON_SINGING_RIDGE_VOID_STORM = 37510 , SPELL_SUMMON_AURA_GENERATOR_000 = 37373 , SPELL_TOP_BUNNY_BEAM = 37418 , NPC_VOID_STORM = 21798 ,
NPC_TOP_BUNNY = 21759 , MODEL_WYRM_FROM_BEYOND = 20476
}
enum {
SPELL_DEATHS_DOOR_FEL_CANNON = 39219 , SPELL_ANTI_DEMON_FLAME_THROWER = 39222 , SPELL_ARTILLERY_ON_THE_WARP_GATE = 39221 , SPELL_FEL_CANNON_BLAST = 36242 ,
SPELL_UNSTABLE_FEL_IMP_TRANSFORM = 39227 , SPELL_UNSTABLE_EXPLOSION = 39266 , SPELL_VOID_HOUND_TRANSFORM = 39275 , SPELL_GO_SMALL_FIRE = 49910 ,
SPELL_GO_SMOKE = 49911 , SPELL_GO_BIG_FIRE = 49912 , SPELL_EXPLOSION = 30934 , NPC_DEATHS_DOOR_FEL_CANNON = 22443 ,
NPC_UNSTABLE_FEL_IMP = 22474 , NPC_DEATHS_DOOR_FEL_CANNON_TARGET_BUNNY = 22495 , NPC_WARP_GATE_SHIELD = 23116 , NPC_DEATHS_DOOR_EXPLOSION_BUNNY = 22502 ,
NPC_NORTH_WARP_GATE_CREDIT = 22503 , NPC_SOUTH_WARP_GATE_CREDIT = 22504 , GO_SMALL_FIRE = 185317 , GO_SMOKE = 185318 ,
GO_BIG_FIRE = 185319 , NPC_EXPLOSION_BUNNY = 22502
}
enum {
NPC_SOULGRINDER = 23019 , NPC_OGRE_SPIRIT = 22912 , NPC_SKULLOC_SOULGRINDER = 22910 , NPC_SOULGRINDER_BUNNY = 23037 ,
SPELL_SOULGRINDER_RITUAL_VISUAL_BUNNY = 39936 , SPELL_BEAM = 39920 , SPELL_SHADOWFORM_1 = 39943 , SPELL_SHADOWFORM_2 = 39944 ,
SPELL_SHADOWFORM_3 = 39946 , SPELL_SHADOWFORM_4 = 39947 , SPELL_SHADOWFORM_TEST = 39951 , SPELL_VIMGOL_CANTATION = 40328 ,
SPELL_SOULGRINDER_RITUAL_VISUAL_IN_PROGRESS = 39918 , SPELL_SCARE_SOULGRINDER_GHOST = 39914 , SPELL_SOULGRINDER_GHOST_TRANSFORM = 39916 , SPELL_SPIRIT_PARTICLES_PURPLE = 28126 ,
SPELL_SOULGRINDER_GHOST_SPAWN_IN = 17321 , SAY_SKULLOC_SOULGRINDER = -1015016 , SAY_FAIL_QUEST = -1015017
}
enum {
QUEST_INTO_THE_SOULGRINDER = 11000 , NPC_BLOODMAUL_SUPPLICANT = 23052 , NPC_BLADESPIRE_SUPPLICANT = 23053 , NPC_OGRE_DRUM_BUNNY = 23056 ,
MUG_EQUIP = 2703 , DRUMMER_EQUIP = 5301 , SAY_MOGDORG_1 = -1001181 , SAY_SUPPLICANT_LOS_1 = -1001186 ,
SAY_SUPPLICANT_LOS_2 = -1001187 , SAY_SUPPLICANT_LOS_3 = -1001188 , SAY_SUPPLICANT_LOS_4 = -1001235 , SAY_SUPPLICANT_LOS_5 = -1001236 ,
SAY_EMOTE_RESPONSE_KISS = -1001184 , SAY_EMOTE_RESPONSE_POINT = -1001185 , SAY_EMOTE_RESPONSE_ANGRY = -1001234 , SAY_EMOTE_RESPONSE_FART_1 = -1001232 ,
SAY_EMOTE_RESPONSE_FART_2 = -1001233 , SPELL_OGRE_FORCE_REACTION = 39960 , SPELL_BLOODMAUL_INTOXICATION_VISUAL = 35777 , RANDOM_SOUND_1 = 11627 ,
RANDOM_SOUND_2 = 11628 , RANDOM_SOUND_3 = 11629 , RANDOM_SOUND_4 = 11630 , CHEER_SOUND = 396 ,
ROAR_SOUND = 402 , DBSCRIPT_SPAWN_OGRES = 10104 , PHASE_KNEEL_TO_PLAYER = 1 , PHASE_UNKNEEL_TO_PLAYER = 2 ,
PHASE_TURN_TO_OGRE = 3 , PHASE_MASS_KNEEL_TO_PLAYER = 4 , PHASE_DRUMMER = 5
}
enum { POINT_PLAYER_POSITION = 1 }
enum {
WAYPOINT_TRIGGER_1 = 20851 , WAYPOINT_TRIGGER_2 = 20852 , WAYPOINT_TRIGGER_3 = 20853 , WAYPOINT_TRIGGER_4 = 20855 ,
WAYPOINT_TRIGGER_5 = 20856 , ORB_TRIGGER_01 = 20666
}
enum {
SPELL_DRUID_SIGNAL = 38782 , SPELL_EVERGROVE_DRUID_TRANSFORM_CROW = 38776 , SPELL_EVERGROVE_DRUID_TRANSFORM_DRUID = 39158 , DBSCRIPT_LANDING_SCRIPT = 10074 ,
DBSCRIPT_FLY_OFF_SCRIPT = 10075
}
enum { NPC_NETHERSTORM_TRIGGER = 19656 , FLAYER_SPELL_SPECIAL_UNARMED = 33334 , FLAYER_SPELL_REND = 13443 , FLAYER_SPELL_SHRED_ARMOR = 40770 }
enum FlayerActions { FLAYER_ACTION_REND , FLAYER_ACTION_SHRED_ARMOR , FLAYER_ACTION_MAX }
enum { NPC_LEAFBEARD = 21326 }
enum { NPC_NETHER_DRAKE_EGG_BUNNY = 21814 }
enum { SPELL_ZEPHYRIUM_CHARGED = 37108 }
Functions
UnitAI * GetAI_mobs_nether_drake (Creature *pCreature)
UnitAI * GetAI_npc_daranelle (Creature *pCreature)
UnitAI * GetAI_npc_bloodmaul_stout_trigger (Creature *pCreature)
UnitAI * GetAI_npc_simon_game_bunny (Creature *pCreature)
bool EffectDummyCreature_npc_simon_game_bunny (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectScriptEffectCreature_npc_simon_game_bunny (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid originalCasterGuid)
UnitAI * GetAI_npc_light_orb_collector (Creature *pCreature)
UnitAI * GetAI_obelisk_triggerAI (Creature *pCreature)
UnitAI * GetAI_npc_vimgol (Creature *pCreature)
UnitAI * GetAI_npc_vimgol_visual_bunny (Creature *pCreature)
UnitAI * GetAI_npc_vimgol_middle_bunny (Creature *pCreature)
UnitAI * GetAI_npc_bird_spirit (Creature *pCreature)
UnitAI * GetAI_npc_bloodmaul_dire_wolf (Creature *pCreature)
bool EffectScriptEffectCreature_spell_diminution_powder (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool AreaTrigger_at_raven_prophecy (Player *pPlayer, AreaTriggerEntry const *pAt)
UnitAI * GetAI_npc_frequency_scanner (Creature *creature)
GameObjectAI * GetGOAI_go_aura_generator_000 (GameObject *go)
UnitAI * GetAI_npc_fel_cannon (Creature *pCreature)
UnitAI * GetAI_npc_warp_gate (Creature *pCreature)
bool ProcessEventId_Soulgrinder (uint32, Object *pSource, Object *, bool)
UnitAI * GetAI_npc_soulgrinder (Creature *pCreature)
bool QuestRewarded_into_the_soulgrinder (Player *player, Creature *pCreature, Quest const *pQuest)
UnitAI * GetAI_npc_supplicant (Creature *pCreature)
UnitAI * GetAI_npc_spirit_prisoner_of_bladespire (Creature *pCreature)
UnitAI * GetAI_npc_deadsoul_orb (Creature *pCreature)
bool QuestAccept_npc_evergrove_druid (Player *player, Creature *creature, const Quest *)
UnitAI * GetAI_npc_evergrove_druidAI (Creature *creature)
UnitAI * GetAI_npc_apexis_flayerAI (Creature *creature)
void AddSC_blades_edge_mountains ()
Variables
static const uint32 aNetherDrakeEntries [MAX_ENTRIES] = {NPC_PROTO, NPC_ADOLESCENT, NPC_MATURE, NPC_NIHIL}
static const uint32 aOgreEntries [] = {19995, 19998, 20334, 20723, 20726, 20730, 20731, 20732, 21296}
static const SimonGame aApexisGameData [4]
static const uint32 aObeliskEntries [] = { 185193, 185195, 185196, 185197, 185198 }
static const std::unordered_map< uint32, Prophecy > prophecies
static float impSpawns [2][4]
static float fireSpawns [14][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_NIHIL_1
SAY_NIHIL_2
SAY_NIHIL_3
SAY_NIHIL_4
SAY_NIHIL_INTERRUPT
MAX_ENTRIES
NPC_PROTO
NPC_ADOLESCENT
NPC_MATURE
NPC_NIHIL
SPELL_T_PHASE_MODULATOR
SPELL_ARCANE_BLAST
SPELL_MANA_BURN
SPELL_INTANGIBLE_PRESENCE
SPELL_RESISTANCES
Definition at line 58 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_SPELL_INFLUENCE
SPELL_LASHHAN_CHANNEL
SPELL_DISPELLING_ANALYSIS
Definition at line 243 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_BREW_1
SAY_BREW_2
SAY_BREW_3
SPELL_INTOXICATION
GO_TANKARD
Definition at line 281 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SOUND_ID_BLUE
SOUND_ID_GREEN
SOUND_ID_RED
SOUND_ID_YELLOW
SOUND_ID_DISABLE_NODE
SPELL_SIMON_GAME_START
SPELL_PRE_EVENT_TIMER
SPELL_PRE_GAME_BLUE_AURA
SPELL_PRE_GAME_GREEN_AURA
SPELL_PRE_GAME_RED_AURA
SPELL_PRE_GAME_YELLOW_AURA
SPELL_PRE_GAME_YELLOW_LARGE
SPELL_PRE_GAME_RED_LARGE
SPELL_PRE_GAME_GREEN_LARGE
SPELL_PRE_GAME_BLUE_LARGE
SPELL_BUTTON_PUSH_BLUE
SPELL_BUTTON_PUSH_GREEN
SPELL_BUTTON_PUSH_RED
SPELL_BUTTON_PUSH_YELLOW
SPELL_GAME_START_RED
SPELL_GAME_START_BLUE
SPELL_GAME_START_GREEN
SPELL_GAME_START_YELLOW
SPELL_GAME_END_BLUE
SPELL_GAME_END_GREEN
SPELL_GAME_END_RED
SPELL_GAME_END_YELLOW
SPELL_SWITCHED_ON
SPELL_SWITCHED_OFF
SPELL_VISUAL_LEVEL_START
SPELL_VISUAL_GAME_FAILED
SPELL_VISUAL_GAME_START
SPELL_VISUAL_GAME_TICK
SPELL_VISUAL_GAME_TICK_LARGE
SPELL_INTROSPECTION_GREEN
SPELL_INTROSPECTION_BLUE
SPELL_INTROSPECTION_RED
SPELL_INTROSPECTION_YELLOW
SPELL_SIMON_BUTTON_PRESSED
SPELL_GOOD_PRESS
SPELL_BAD_PRESS
SPELL_SIMON_GROUP_REWARD
SPELL_APEXIS_VIBRATIONS
SPELL_APEXIS_EMANATIONS
SPELL_APEXIS_ENLIGHTENMENT
NPC_SIMON_GAME_BUNNY
NPC_SIMON_GAME_BUNNY_LARGE
GO_APEXIS_RELIC
GO_APEXIS_MONUMENT
QUEST_AN_APEXIS_RELIC
QUEST_RELICS_EMANATION
COLOR_IDX_BLUE
COLOR_IDX_GREEN
COLOR_IDX_RED
COLOR_IDX_YELLOW
PHASE_INACTIVE
PHASE_LEVEL_PREPARE
PHASE_AI_GAME
PHASE_PLAYER_PREPARE
PHASE_PLAYER_GAME
PHASE_LEVEL_FINISHED
SIMON_BIG_LEVEL_SUMMON
SIMON_LEVEL_VIBRATIONS
SIMON_LEVEL_EMANATIONS
SIMON_LEVEL_ENLIGHTENMENT
MAX_SIMON_FAIL_TIMER
Definition at line 405 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_LIGHT_ORB_MINI
NPC_KILL_CREDIT_TRIGGER
MAX_PULL_DISTANCE
Definition at line 861 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_TRIGGER
NPC_DOOMCRYER
SPELL_GREEN_BEAM
Definition at line 953 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_VIMGOL_THE_VILE
NPC_VIMGOL_MIDDLE_BUNNY
SPELL_VIMGOL_POP_TEST_A
SPELL_VIMGOL_POP_TEST_B
SPELL_VIMGOL_POP_TEST_C
SPELL_VIMGOL_POP_TEST_D
SPELL_VIMGOL_POP_TEST_E
SPELL_PENTAGRAM_BEAM
SPELL_UNHOLY_GROWTH
SPELL_SUMMONED_DEMON
SPELL_INTERRUPT_UNHOLY_GROWTH
SPELL_SUMMON_GRIMOIRE
SPELL_SHADOWBOLT_VOLLEY
SAY_VIMGOL_1
SAY_VIMGOL_2
Definition at line 1104 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_TASKMASTER
Definition at line 1430 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_REND
SPELL_RINAS_DIMINUTION_POWDER
NPC_DIRE_WOLF_TRIGGER
NPC_BLOODMAUL_DIRE_WOLF
FACTION_FRIENDLY
Definition at line 1518 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
UNDERSTAND_RAVENSPEECH_SPELL
UNDERSTAND_RAVENSPEECH_AURA
QUEST_WHISPERS_OF_THE_RAVEN_GOD
NPC_VISION_RAVEN_GOD_TEMPLATE
Definition at line 1625 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_OSCILLATION_FIELD
SPELL_OSCILLATING_FREQUENCY_SCANNER
SPELL_SUMMON_TOP_BUNNY_CASTER
SPELL_SUMMON_WYRM_FROM_BEYOND
SPELL_SUMMON_SINGING_RIDGE_VOID_STORM
SPELL_SUMMON_AURA_GENERATOR_000
SPELL_TOP_BUNNY_BEAM
NPC_VOID_STORM
NPC_TOP_BUNNY
MODEL_WYRM_FROM_BEYOND
Definition at line 1667 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DEATHS_DOOR_FEL_CANNON
SPELL_ANTI_DEMON_FLAME_THROWER
SPELL_ARTILLERY_ON_THE_WARP_GATE
SPELL_FEL_CANNON_BLAST
SPELL_UNSTABLE_FEL_IMP_TRANSFORM
SPELL_UNSTABLE_EXPLOSION
SPELL_VOID_HOUND_TRANSFORM
SPELL_GO_SMALL_FIRE
SPELL_GO_SMOKE
SPELL_GO_BIG_FIRE
SPELL_EXPLOSION
NPC_DEATHS_DOOR_FEL_CANNON
NPC_UNSTABLE_FEL_IMP
NPC_DEATHS_DOOR_FEL_CANNON_TARGET_BUNNY
NPC_WARP_GATE_SHIELD
NPC_DEATHS_DOOR_EXPLOSION_BUNNY
NPC_NORTH_WARP_GATE_CREDIT
NPC_SOUTH_WARP_GATE_CREDIT
GO_SMALL_FIRE
GO_SMOKE
GO_BIG_FIRE
NPC_EXPLOSION_BUNNY
Definition at line 1796 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_SOULGRINDER
NPC_OGRE_SPIRIT
NPC_SKULLOC_SOULGRINDER
NPC_SOULGRINDER_BUNNY
SPELL_SOULGRINDER_RITUAL_VISUAL_BUNNY
SPELL_BEAM
SPELL_SHADOWFORM_1
SPELL_SHADOWFORM_2
SPELL_SHADOWFORM_3
SPELL_SHADOWFORM_4
SPELL_SHADOWFORM_TEST
SPELL_VIMGOL_CANTATION
SPELL_SOULGRINDER_RITUAL_VISUAL_IN_PROGRESS
SPELL_SCARE_SOULGRINDER_GHOST
SPELL_SOULGRINDER_GHOST_TRANSFORM
SPELL_SPIRIT_PARTICLES_PURPLE
SPELL_SOULGRINDER_GHOST_SPAWN_IN
SAY_SKULLOC_SOULGRINDER
SAY_FAIL_QUEST
Definition at line 2092 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_INTO_THE_SOULGRINDER
NPC_BLOODMAUL_SUPPLICANT
NPC_BLADESPIRE_SUPPLICANT
NPC_OGRE_DRUM_BUNNY
MUG_EQUIP
DRUMMER_EQUIP
SAY_MOGDORG_1
SAY_SUPPLICANT_LOS_1
SAY_SUPPLICANT_LOS_2
SAY_SUPPLICANT_LOS_3
SAY_SUPPLICANT_LOS_4
SAY_SUPPLICANT_LOS_5
SAY_EMOTE_RESPONSE_KISS
SAY_EMOTE_RESPONSE_POINT
SAY_EMOTE_RESPONSE_ANGRY
SAY_EMOTE_RESPONSE_FART_1
SAY_EMOTE_RESPONSE_FART_2
SPELL_OGRE_FORCE_REACTION
SPELL_BLOODMAUL_INTOXICATION_VISUAL
RANDOM_SOUND_1
RANDOM_SOUND_2
RANDOM_SOUND_3
RANDOM_SOUND_4
CHEER_SOUND
ROAR_SOUND
DBSCRIPT_SPAWN_OGRES
PHASE_KNEEL_TO_PLAYER
PHASE_UNKNEEL_TO_PLAYER
PHASE_TURN_TO_OGRE
PHASE_MASS_KNEEL_TO_PLAYER
PHASE_DRUMMER
Definition at line 2393 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
POINT_PLAYER_POSITION
Definition at line 2763 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
WAYPOINT_TRIGGER_1
WAYPOINT_TRIGGER_2
WAYPOINT_TRIGGER_3
WAYPOINT_TRIGGER_4
WAYPOINT_TRIGGER_5
ORB_TRIGGER_01
Definition at line 2799 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DRUID_SIGNAL
SPELL_EVERGROVE_DRUID_TRANSFORM_CROW
SPELL_EVERGROVE_DRUID_TRANSFORM_DRUID
DBSCRIPT_LANDING_SCRIPT
DBSCRIPT_FLY_OFF_SCRIPT
Definition at line 2906 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_NETHERSTORM_TRIGGER
FLAYER_SPELL_SPECIAL_UNARMED
FLAYER_SPELL_REND
FLAYER_SPELL_SHRED_ARMOR
Definition at line 3046 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_LEAFBEARD
Definition at line 3253 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_NETHER_DRAKE_EGG_BUNNY
Definition at line 3286 of file blades_edge_mountains.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ZEPHYRIUM_CHARGED
Definition at line 3302 of file blades_edge_mountains.cpp.
FlayerActions
enum FlayerActions
Enumerator
FLAYER_ACTION_REND
FLAYER_ACTION_SHRED_ARMOR
FLAYER_ACTION_MAX
Definition at line 3055 of file blades_edge_mountains.cpp.
Function Documentation
AddSC_blades_edge_mountains()
void AddSC_blades_edge_mountains ()
Definition at line 3339 of file blades_edge_mountains.cpp.
References AreaTrigger_at_raven_prophecy(), EffectDummyCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_spell_diminution_powder(), Script::GetAI, GetAI_mobs_nether_drake(), GetAI_npc_apexis_flayerAI(), GetAI_npc_bird_spirit(), GetAI_npc_bloodmaul_dire_wolf(), GetAI_npc_bloodmaul_stout_trigger(), GetAI_npc_daranelle(), GetAI_npc_deadsoul_orb(), GetAI_npc_evergrove_druidAI(), GetAI_npc_fel_cannon(), GetAI_npc_frequency_scanner(), GetAI_npc_light_orb_collector(), GetAI_npc_simon_game_bunny(), GetAI_npc_soulgrinder(), GetAI_npc_spirit_prisoner_of_bladespire(), GetAI_npc_supplicant(), GetAI_npc_vimgol(), GetAI_npc_vimgol_middle_bunny(), GetAI_npc_vimgol_visual_bunny(), GetAI_npc_warp_gate(), GetAI_obelisk_triggerAI(), Script::GetGameObjectAI, GetGOAI_go_aura_generator_000(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, Script::pEffectScriptEffectNPC, Script::pProcessEventId, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, ProcessEventId_Soulgrinder(), QuestAccept_npc_evergrove_druid(), QuestRewarded_into_the_soulgrinder(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_raven_prophecy()
bool AreaTrigger_at_raven_prophecy (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 1634 of file blades_edge_mountains.cpp.
References Prophecy::creature, DoScriptText(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), Player::GetReqKillOrCastCurrentCount(), Unit::HasAura(), AreaTriggerEntry::id, Unit::IsAlive(), Player::KilledMonsterCredit(), NPC_VISION_RAVEN_GOD_TEMPLATE, NPC_WHISPER_RAVEN_GOD_TEMPLATE, Prophecy::o, prophecies, QUEST_STATUS_INCOMPLETE, QUEST_WHISPERS_OF_THE_RAVEN_GOD, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, Prophecy::text, UNDERSTAND_RAVENSPEECH_AURA, Prophecy::x, Prophecy::y, and Prophecy::z.
Referenced by AddSC_blades_edge_mountains().
EffectDummyCreature_npc_simon_game_bunny()
bool EffectDummyCreature_npc_simon_game_bunny (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 828 of file blades_edge_mountains.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_B, EFFECT_INDEX_0, Object::GetEntry(), NPC_SIMON_GAME_BUNNY, NPC_SIMON_GAME_BUNNY_LARGE, UnitAI::SendAIEvent(), and SPELL_PRE_EVENT_TIMER.
Referenced by AddSC_blades_edge_mountains().
EffectScriptEffectCreature_npc_simon_game_bunny()
bool EffectScriptEffectCreature_npc_simon_game_bunny (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid originalCasterGuid)
Definition at line 842 of file blades_edge_mountains.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_C, EFFECT_INDEX_1, Object::GetEntry(), Object::GetTypeId(), ObjectGuid::IsGameObject(), NPC_SIMON_GAME_BUNNY, NPC_SIMON_GAME_BUNNY_LARGE, UnitAI::SendAIEvent(), SPELL_INTROSPECTION_BLUE, SPELL_INTROSPECTION_GREEN, SPELL_INTROSPECTION_RED, SPELL_INTROSPECTION_YELLOW, and TYPEID_PLAYER.
Referenced by AddSC_blades_edge_mountains().
EffectScriptEffectCreature_spell_diminution_powder()
bool EffectScriptEffectCreature_spell_diminution_powder (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 1579 of file blades_edge_mountains.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Unit::CombatStop(), EFFECT_INDEX_1, FACTION_FRIENDLY, Object::GetEntry(), Unit::HasAura(), NPC_BLOODMAUL_DIRE_WOLF, NPC_DIRE_WOLF_TRIGGER, Unit::RemoveSpellsCausingAura(), UnitAI::SendAIEvent(), Creature::SetFactionTemporary(), SPELL_AURA_PERIODIC_DAMAGE, SPELL_RINAS_DIMINUTION_POWDER, and TEMPFACTION_RESTORE_REACH_HOME.
Referenced by AddSC_blades_edge_mountains().
GetAI_mobs_nether_drake()
UnitAI* GetAI_mobs_nether_drake (Creature * pCreature)
Definition at line 234 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_apexis_flayerAI()
UnitAI* GetAI_npc_apexis_flayerAI (Creature * creature)
Definition at line 3248 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_bird_spirit()
UnitAI* GetAI_npc_bird_spirit (Creature * pCreature)
Definition at line 1509 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_bloodmaul_dire_wolf()
UnitAI* GetAI_npc_bloodmaul_dire_wolf (Creature * pCreature)
Definition at line 1574 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_bloodmaul_stout_trigger()
UnitAI* GetAI_npc_bloodmaul_stout_trigger (Creature * pCreature)
Definition at line 396 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_daranelle()
UnitAI* GetAI_npc_daranelle (Creature * pCreature)
Definition at line 272 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_deadsoul_orb()
UnitAI* GetAI_npc_deadsoul_orb (Creature * pCreature)
Definition at line 2897 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_evergrove_druidAI()
UnitAI* GetAI_npc_evergrove_druidAI (Creature * creature)
Definition at line 3037 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_fel_cannon()
UnitAI* GetAI_npc_fel_cannon (Creature * pCreature)
Definition at line 1900 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_frequency_scanner()
UnitAI* GetAI_npc_frequency_scanner (Creature * creature)
Definition at line 1782 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_light_orb_collector()
UnitAI* GetAI_npc_light_orb_collector (Creature * pCreature)
Definition at line 944 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_simon_game_bunny()
UnitAI* GetAI_npc_simon_game_bunny (Creature * pCreature)
Definition at line 823 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_soulgrinder()
UnitAI* GetAI_npc_soulgrinder (Creature * pCreature)
Definition at line 2384 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_spirit_prisoner_of_bladespire()
UnitAI* GetAI_npc_spirit_prisoner_of_bladespire (Creature * pCreature)
Definition at line 2790 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_supplicant()
UnitAI* GetAI_npc_supplicant (Creature * pCreature)
Definition at line 2754 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_vimgol()
UnitAI* GetAI_npc_vimgol (Creature * pCreature)
Definition at line 1190 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_vimgol_middle_bunny()
UnitAI* GetAI_npc_vimgol_middle_bunny (Creature * pCreature)
Definition at line 1421 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_vimgol_visual_bunny()
UnitAI* GetAI_npc_vimgol_visual_bunny (Creature * pCreature)
Definition at line 1264 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_npc_warp_gate()
UnitAI* GetAI_npc_warp_gate (Creature * pCreature)
Definition at line 2083 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetAI_obelisk_triggerAI()
UnitAI* GetAI_obelisk_triggerAI (Creature * pCreature)
Definition at line 1095 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
GetGOAI_go_aura_generator_000()
GameObjectAI* GetGOAI_go_aura_generator_000 (GameObject * go)
Definition at line 1787 of file blades_edge_mountains.cpp.
Referenced by AddSC_blades_edge_mountains().
ProcessEventId_Soulgrinder()
bool ProcessEventId_Soulgrinder (uint32 , Object * pSource, Object * , bool)
Definition at line 2119 of file blades_edge_mountains.cpp.
References GetClosestCreatureWithEntry(), NPC_SOULGRINDER, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OR_CORPSE_DESPAWN.
Referenced by AddSC_blades_edge_mountains().
QuestAccept_npc_evergrove_druid()
bool QuestAccept_npc_evergrove_druid (Player * player, Creature * creature, const Quest *)
Definition at line 3028 of file blades_edge_mountains.cpp.
References Creature::AI().
Referenced by AddSC_blades_edge_mountains().
QuestRewarded_into_the_soulgrinder()
bool QuestRewarded_into_the_soulgrinder (Player * player, Creature * pCreature, Quest const * pQuest)
Definition at line 2436 of file blades_edge_mountains.cpp.
References Unit::CastSpell(), DBSCRIPT_SPAWN_OGRES, DoScriptText(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Quest::GetQuestId(), QUEST_INTO_THE_SOULGRINDER, SAY_MOGDORG_1, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), SPELL_OGRE_FORCE_REACTION, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_blades_edge_mountains().
Variable Documentation
aApexisGameData
const SimonGame aApexisGameData[4] static
Initial value:
=
{
    {COLOR_IDX_BLUE,    SPELL_BUTTON_PUSH_BLUE,     SPELL_INTROSPECTION_BLUE,   SOUND_ID_BLUE},
    {COLOR_IDX_GREEN,   SPELL_BUTTON_PUSH_GREEN,    SPELL_INTROSPECTION_GREEN,  SOUND_ID_GREEN},
    {COLOR_IDX_RED,     SPELL_BUTTON_PUSH_RED,      SPELL_INTROSPECTION_RED,    SOUND_ID_RED},
    {COLOR_IDX_YELLOW,  SPELL_BUTTON_PUSH_YELLOW,   SPELL_INTROSPECTION_YELLOW, SOUND_ID_YELLOW}
}
Definition at line 515 of file blades_edge_mountains.cpp.
Referenced by npc_simon_game_bunnyAI::DoSetupLevel(), and npc_simon_game_bunnyAI::ReceiveAIEvent().
aNetherDrakeEntries
const uint32 aNetherDrakeEntries[MAX_ENTRIES] = {NPC_PROTO, NPC_ADOLESCENT, NPC_MATURE, NPC_NIHIL} static
Definition at line 82 of file blades_edge_mountains.cpp.
Referenced by mobs_nether_drakeAI::SpellHit().
aObeliskEntries
const uint32 aObeliskEntries[] = { 185193, 185195, 185196, 185197, 185198 } static
Definition at line 961 of file blades_edge_mountains.cpp.
Referenced by npc_obelisk_triggerAI::Reset(), and npc_obelisk_triggerAI::UpdateAI().
aOgreEntries
const uint32 aOgreEntries[] = {19995, 19998, 20334, 20723, 20726, 20730, 20731, 20732, 21296} static
Definition at line 293 of file blades_edge_mountains.cpp.
Referenced by npc_bloodmaul_stout_triggerAI::UpdateAI().
fireSpawns
float fireSpawns[14][3] static
Initial value:
=
{
    { 2199.255f,5474.860f,153.578f},
    { 2185.102f,5470.938f,164.374f },
    { 2185.104f,5484.197f,154.817f },
    { 2188.340f, 5476.629f, 155.069f },
    { 2194.513f,5481.483f,164.991f },
    { 2178.581f,5477.184f, 157.264f},
    { 2188.340f, 5476.629f, 155.069f},
    { 1982.273f,5331.832f,153.952f },
    { 1987.307f,5307.395f,169.677f },
    { 1980.868f,8325.251f,169.290f },
    { 1981.730f, 5315.390f, 156.600f },
    { 1989.396f,5322.008f,155.384f },
    { 1973.351f,5299.629f,155.395f},
    { 1981.730f, 5315.390f, 156.600f }
}
Definition at line 1915 of file blades_edge_mountains.cpp.
Referenced by npc_warp_gate::SpellHit().
impSpawns
float impSpawns[2][4] static
Initial value:
=
{
    { 2188.340f, 5476.629f, 155.069f, 5.259f },
    { 1981.730f, 5315.390f, 156.600f, 0.262f}
}
Definition at line 1909 of file blades_edge_mountains.cpp.
Referenced by npc_warp_gate::UpdateAI().
prophecies
const std::unordered_map<uint32, Prophecy> prophecies static
Initial value:
=
{
    {4613,{ (uint32)22798, (int32)-1015012, 3779.987061f, 6729.603027f, 180.498413f, 5.71490f }},
    {4615,{ (uint32)22799, (int32)-1015013, 3629.285889f, 6542.140137f, 155.004669f, 2.56267f }},
    {4616,{ (uint32)22800, (int32)-1015014, 3736.950439f, 6640.749023f, 133.674530f, 3.33629f }},
    {4617,{ (uint32)22801, (int32)-1015015, 3572.574219f, 6669.196289f, 128.455444f, 5.62290f }}
}
Definition at line 1617 of file blades_edge_mountains.cpp.
Referenced by AreaTrigger_at_raven_prophecy().