CMaNGOS_WoTLK: blasted_lands.cpp File Reference
blasted_lands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Functions
bool TrapTargetSearchRuneOfTheDefiler (Unit *unit)
void AddSC_blasted_lands ()
Variables
std::function< bool(Unit *)> functionRuneOfTheDefiler = &TrapTargetSearchRuneOfTheDefiler
Function Documentation
AddSC_blasted_lands()
void AddSC_blasted_lands ()
Definition at line 43 of file blasted_lands.cpp.
References functionRuneOfTheDefiler, Script::Name, Script::pTrapSearching, and Script::RegisterSelf().
Referenced by AddScripts().
TrapTargetSearchRuneOfTheDefiler()
bool TrapTargetSearchRuneOfTheDefiler (Unit * unit)
Definition at line 29 of file blasted_lands.cpp.
References Object::GetTypeId(), Player::HasItemCount(), and TYPEID_PLAYER.
Variable Documentation
functionRuneOfTheDefiler
std::function<bool(Unit*)> functionRuneOfTheDefiler = &TrapTargetSearchRuneOfTheDefiler
Definition at line 41 of file blasted_lands.cpp.
Referenced by AddSC_blasted_lands().