CMaNGOS_WoTLK: bloodmyst_isle.cpp File Reference
bloodmyst_isle.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct mob_webbed_creatureAI
struct npc_demolitionist_legosoAI
Enumerations
enum { NPC_EXPEDITION_RESEARCHER = 17681 }
enum {
SAY_ESCORT_START = -1000185 , SAY_ESCORT_LEGOSO_1 = -1000186 , SAY_ESCORT_LEGOSO_2 = -1001198 , SAY_ESCORT_LEGOSO_3 = -1001199 ,
SAY_ESCORT_LEGOSO_4 = -1001200 , SAY_ESCORT_COUNT_3 = -1001201 , SAY_ESCORT_COUNT_2 = -1001202 , SAY_ESCORT_COUNT_1 = -1001203 ,
SAY_ESCORT_CONTINUE = -1001204 , SAY_ESCORT_LEGOSO_5 = -1001205 , SAY_ESCORT_LEGOSO_6 = -1001206 , SAY_ESCORT_LEGOSO_7 = -1001207 ,
SAY_ESCORT_LEGOSO_8 = -1001208 , SAY_ESCORT_LEGOSO_9 = -1001209 , SAY_ESCORT_LEGOSO_10 = -1001210 , SAY_LEGOSO_AGGRO = -1001211 ,
SAY_ESCORT_COMPLETE_1 = -1001212 , SAY_ESCORT_COMPLETE_2 = -1001213 , NPC_LEGOSO = 17982 , NPC_SIRONAS = 17678 ,
GO_EXPLOSIVES_1 = 182088 , GO_EXPLOSIVES_2 = 182091 , GO_COIL_FIRE_L = 182090 , GO_COIL_FIRE_S = 182089 ,
QUEST_ENDING_THEIR_WORLD = 9759 , POINT_ID_EXPLOSIVES_1 = 11 , POINT_ID_EXPLOSIVES_2 = 12 , POINT_ID_EXPLOSIVES_3 = 13 ,
POINT_ID_EXPLOSIVES_4 = 14 , POINT_ID_EXPLOSIVES_5 = 15 , POINT_ID_EXPLOSIVES_6 = 16 , POINT_ID_EXPLOSIVES_7 = 17 ,
POINT_ID_EXPLOSIVES_8 = 18 , POINT_ID_EXPLOSIVES_9 = 19 , POINT_ID_COUNT_START = 20 , POINT_ID_COUNT_FINISHED = 21 ,
POINT_ID_TEXT_1 = 30 , POINT_ID_TEXT_2 = 31 , POINT_ID_TEXT_3 = 32
}
Functions
UnitAI * GetAI_mob_webbed_creature (Creature *pCreature)
UnitAI * GetAI_npc_demolitionist_legoso (Creature *pCreature)
bool QuestAccept_npc_demolitionist_legoso (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_bloodmyst_isle ()
Variables
const uint32 possibleSpawns [31] = {17322, 17661, 17496, 17522, 17340, 17352, 17333, 17524, 17654, 17348, 17339, 17345, 17353, 17336, 17550, 17330, 17701, 17321, 17325, 17320, 17683, 17342, 17715, 17334, 17341, 17338, 17337, 17346, 17344, 17327}
static const DialogueEntry aLegosoDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_EXPEDITION_RESEARCHER
Definition at line 36 of file bloodmyst_isle.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_ESCORT_LEGOSO_1
SAY_ESCORT_LEGOSO_2
SAY_ESCORT_LEGOSO_3
SAY_ESCORT_LEGOSO_4
SAY_ESCORT_COUNT_3
SAY_ESCORT_COUNT_2
SAY_ESCORT_COUNT_1
SAY_ESCORT_CONTINUE
SAY_ESCORT_LEGOSO_5
SAY_ESCORT_LEGOSO_6
SAY_ESCORT_LEGOSO_7
SAY_ESCORT_LEGOSO_8
SAY_ESCORT_LEGOSO_9
SAY_ESCORT_LEGOSO_10
SAY_LEGOSO_AGGRO
SAY_ESCORT_COMPLETE_1
SAY_ESCORT_COMPLETE_2
NPC_LEGOSO
NPC_SIRONAS
GO_EXPLOSIVES_1
GO_EXPLOSIVES_2
GO_COIL_FIRE_L
GO_COIL_FIRE_S
QUEST_ENDING_THEIR_WORLD
POINT_ID_EXPLOSIVES_1
POINT_ID_EXPLOSIVES_2
POINT_ID_EXPLOSIVES_3
POINT_ID_EXPLOSIVES_4
POINT_ID_EXPLOSIVES_5
POINT_ID_EXPLOSIVES_6
POINT_ID_EXPLOSIVES_7
POINT_ID_EXPLOSIVES_8
POINT_ID_EXPLOSIVES_9
POINT_ID_COUNT_START
POINT_ID_COUNT_FINISHED
POINT_ID_TEXT_1
POINT_ID_TEXT_2
POINT_ID_TEXT_3
Definition at line 84 of file bloodmyst_isle.cpp.
Function Documentation
AddSC_bloodmyst_isle()
void AddSC_bloodmyst_isle ()
Definition at line 433 of file bloodmyst_isle.cpp.
References Script::GetAI, GetAI_mob_webbed_creature(), GetAI_npc_demolitionist_legoso(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_demolitionist_legoso(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_webbed_creature()
UnitAI* GetAI_mob_webbed_creature (Creature * pCreature)
Definition at line 75 of file bloodmyst_isle.cpp.
Referenced by AddSC_bloodmyst_isle().
GetAI_npc_demolitionist_legoso()
UnitAI* GetAI_npc_demolitionist_legoso (Creature * pCreature)
Definition at line 420 of file bloodmyst_isle.cpp.
Referenced by AddSC_bloodmyst_isle().
QuestAccept_npc_demolitionist_legoso()
bool QuestAccept_npc_demolitionist_legoso (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 425 of file bloodmyst_isle.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ENDING_THEIR_WORLD, and UnitAI::SendAIEvent().
Referenced by AddSC_bloodmyst_isle().
Variable Documentation
aLegosoDialogue
const DialogueEntry aLegosoDialogue[] static
Definition at line 133 of file bloodmyst_isle.cpp.
possibleSpawns
const uint32 possibleSpawns[31] = {17322, 17661, 17496, 17522, 17340, 17352, 17333, 17524, 17654, 17348, 17339, 17345, 17353, 17336, 17550, 17330, 17701, 17321, 17325, 17320, 17683, 17342, 17715, 17334, 17341, 17338, 17337, 17346, 17344, 17327}
Definition at line 42 of file bloodmyst_isle.cpp.
Referenced by mob_webbed_creatureAI::JustDied().