CMaNGOS_WoTLK: blood_prince_council.cpp File Reference
blood_prince_council.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
Data Structures
struct npc_queen_lanathel_introAI
struct npc_ball_of_flameAI
struct npc_kinetic_bombAI
struct npc_dark_nucleusAI
struct npc_blood_orb_controlAI
struct blood_prince_council_baseAI
struct boss_valanar_iccAI
struct boss_keleseth_iccAI
struct boss_taldaram_iccAI
Enumerations
enum {
SAY_COUNCIL_INTRO_1 = -1631101 , SAY_COUNCIL_INTRO_2 = -1631102 , SAY_KELESETH_INVOCATION = -1631103 , SAY_KELESETH_SPECIAL = -1631104 ,
SAY_KELESETH_SLAY_1 = -1631105 , SAY_KELESETH_SLAY_2 = -1631106 , SAY_KELESETH_BERSERK = -1631107 , SAY_KELESETH_DEATH = -1631108 ,
SAY_TALDARAM_INVOCATION = -1631109 , SAY_TALDARAM_SPECIAL = -1631110 , SAY_TALDARAM_SLAY_1 = -1631111 , SAY_TALDARAM_SLAY_2 = -1631112 ,
SAY_TALDARAM_BERSERK = -1631113 , SAY_TALDARAM_DEATH = -1631114 , SAY_VALANAR_INVOCATION = -1631115 , SAY_VALANAR_SPECIAL = -1631116 ,
SAY_VALANAR_SLAY_1 = -1631117 , SAY_VALANAR_SLAY_2 = -1631118 , SAY_VALANAR_BERSERK = -1631119 , SAY_VALANAR_DEATH = -1631120 ,
EMOTE_INVOCATION = -1631197 , EMOTE_SHOCK_VORTEX = -1631198 , EMOTE_FLAMES = -1631199 , SPELL_BERSERK = 26662 ,
SPELL_FEIGN_DEATH = 71598 , SPELL_INVOCATION_BLOOD = 70934 , SPELL_INVOCATION_BLOOD_2 = 71596 , SPELL_INVOCATION_V_MOVE = 71075 ,
SPELL_INVOCATION_K_MOVE = 71079 , SPELL_INVOCATION_T_MOVE = 71082 , SPELL_INVOCATION_VALANAR = 70952 , SPELL_KINETIC_BOMB_TARGET = 72053 ,
SPELL_KINETIC_BOMB = 72080 , SPELL_SHOCK_VORTEX = 72037 , SPELL_EMP_SHOCK_VORTEX = 72039 , NPC_KINETIC_BOMB = 38454 ,
NPC_KINETIC_BOMB_TARGET = 38458 , SPELL_KINETIC_BOMB_DMG = 72052 , SPELL_KINETIC_BOMB_VISUAL = 72054 , SPELL_UNSTABLE = 72059 ,
SPELL_KINETIC_KNOCKBACK = 72087 , SPELL_INVOCATION_KELESETH = 70981 , SPELL_SHADOW_LANCE = 71405 , SPELL_EMP_SHADOW_LANCE = 71815 ,
SPELL_SHADOW_RESONANCE = 71943 , SPELL_SHADOW_RESONANCE_AURA = 71911 , SPELL_SHADOW_RESONANCE_BUFF = 71822 , SPELL_SHADOW_RESONANCE_DMG = 72980 ,
SPELL_INVOCATION_TALDARAM = 70982 , SPELL_GLITTERING_SPARKS = 71806 , SPELL_CONJURE_FLAME = 71718 , SPELL_CONJURE_EMP_FLAME = 72040 ,
NPC_BALL_OF_FLAME = 38332 , NPC_BALL_OF_INFERNO_FLAME = 38451 , SPELL_BALL_FLAMES_VISUAL = 71706 , SPELL_FLAMES = 71393 ,
SPELL_BALL_FLAMES_PERIODIC = 71709 , SPELL_FLAMES_PROC = 71756 , MAX_PRINCES = 3
}
Functions
UnitAI * GetAI_npc_queen_lanathel_intro (Creature *pCreature)
UnitAI * GetAI_npc_ball_of_flame (Creature *pCreature)
UnitAI * GetAI_npc_kinetic_bomb (Creature *pCreature)
UnitAI * GetAI_npc_dark_nucleus (Creature *pCreature)
UnitAI * GetAI_npc_blood_orb_control (Creature *pCreature)
UnitAI * GetAI_boss_valanar_icc (Creature *pCreature)
UnitAI * GetAI_boss_keleseth_icc (Creature *pCreature)
UnitAI * GetAI_boss_taldaram_icc (Creature *pCreature)
void AddSC_blood_prince_council ()
Variables
static const DialogueEntry aIntroDialogue []
static const float aLanathelFlyPos [3] = {4660.49f, 2769.2f, 430.0f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_COUNCIL_INTRO_1
SAY_COUNCIL_INTRO_2
SAY_KELESETH_INVOCATION
SAY_KELESETH_SPECIAL
SAY_KELESETH_SLAY_1
SAY_KELESETH_SLAY_2
SAY_KELESETH_BERSERK
SAY_KELESETH_DEATH
SAY_TALDARAM_INVOCATION
SAY_TALDARAM_SPECIAL
SAY_TALDARAM_SLAY_1
SAY_TALDARAM_SLAY_2
SAY_TALDARAM_BERSERK
SAY_TALDARAM_DEATH
SAY_VALANAR_INVOCATION
SAY_VALANAR_SPECIAL
SAY_VALANAR_SLAY_1
SAY_VALANAR_SLAY_2
SAY_VALANAR_BERSERK
SAY_VALANAR_DEATH
EMOTE_INVOCATION
EMOTE_SHOCK_VORTEX
EMOTE_FLAMES
SPELL_BERSERK
SPELL_FEIGN_DEATH
SPELL_INVOCATION_BLOOD
SPELL_INVOCATION_BLOOD_2
SPELL_INVOCATION_V_MOVE
SPELL_INVOCATION_K_MOVE
SPELL_INVOCATION_T_MOVE
SPELL_INVOCATION_VALANAR
SPELL_KINETIC_BOMB_TARGET
SPELL_KINETIC_BOMB
SPELL_SHOCK_VORTEX
SPELL_EMP_SHOCK_VORTEX
NPC_KINETIC_BOMB
NPC_KINETIC_BOMB_TARGET
SPELL_KINETIC_BOMB_DMG
SPELL_KINETIC_BOMB_VISUAL
SPELL_UNSTABLE
SPELL_KINETIC_KNOCKBACK
SPELL_INVOCATION_KELESETH
SPELL_SHADOW_LANCE
SPELL_EMP_SHADOW_LANCE
SPELL_SHADOW_RESONANCE
SPELL_SHADOW_RESONANCE_AURA
SPELL_SHADOW_RESONANCE_BUFF
SPELL_SHADOW_RESONANCE_DMG
SPELL_INVOCATION_TALDARAM
SPELL_GLITTERING_SPARKS
SPELL_CONJURE_FLAME
SPELL_CONJURE_EMP_FLAME
NPC_BALL_OF_FLAME
NPC_BALL_OF_INFERNO_FLAME
SPELL_BALL_FLAMES_VISUAL
SPELL_FLAMES
SPELL_BALL_FLAMES_PERIODIC
SPELL_FLAMES_PROC
MAX_PRINCES
Definition at line 27 of file blood_prince_council.cpp.
Function Documentation
AddSC_blood_prince_council()
void AddSC_blood_prince_council ()
Definition at line 843 of file blood_prince_council.cpp.
References Script::GetAI, GetAI_boss_keleseth_icc(), GetAI_boss_taldaram_icc(), GetAI_boss_valanar_icc(), GetAI_npc_ball_of_flame(), GetAI_npc_blood_orb_control(), GetAI_npc_dark_nucleus(), GetAI_npc_kinetic_bomb(), GetAI_npc_queen_lanathel_intro(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_keleseth_icc()
UnitAI* GetAI_boss_keleseth_icc (Creature * pCreature)
Definition at line 751 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_boss_taldaram_icc()
UnitAI* GetAI_boss_taldaram_icc (Creature * pCreature)
Definition at line 838 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_boss_valanar_icc()
UnitAI* GetAI_boss_valanar_icc (Creature * pCreature)
Definition at line 671 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_npc_ball_of_flame()
UnitAI* GetAI_npc_ball_of_flame (Creature * pCreature)
Definition at line 275 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_npc_blood_orb_control()
UnitAI* GetAI_npc_blood_orb_control (Creature * pCreature)
Definition at line 460 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_npc_dark_nucleus()
UnitAI* GetAI_npc_dark_nucleus (Creature * pCreature)
Definition at line 368 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_npc_kinetic_bomb()
UnitAI* GetAI_npc_kinetic_bomb (Creature * pCreature)
Definition at line 316 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
GetAI_npc_queen_lanathel_intro()
UnitAI* GetAI_npc_queen_lanathel_intro (Creature * pCreature)
Definition at line 223 of file blood_prince_council.cpp.
Referenced by AddSC_blood_prince_council().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_COUNCIL_INTRO_1,   NPC_LANATHEL_INTRO, 15000},
    {SAY_COUNCIL_INTRO_2,   NPC_LANATHEL_INTRO, 10000},
    {NPC_BLOOD_ORB_CONTROL, 0,                  0},
    {0, 0, 0},
}
Definition at line 118 of file blood_prince_council.cpp.
aLanathelFlyPos
const float aLanathelFlyPos[3] = {4660.49f, 2769.2f, 430.0f} static
Definition at line 126 of file blood_prince_council.cpp.
Referenced by npc_queen_lanathel_introAI::JustDidDialogueStep().