CMaNGOS_WoTLK: borean_tundra.cpp File Reference
borean_tundra.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_nesingwary_trapperAI
struct npc_oil_stained_wolfAI
struct npc_sinkhole_kill_creditAI
struct npc_lurgglbrAI
struct npc_nexus_drake_hatchlingAI
struct npc_scourged_flamespitterAI
struct npc_bonker_togglevoltAI
struct npc_jennyAI
struct npc_seaforium_depth_chargeAI
struct npc_mootoo_the_youngerAI
struct ProudhoofSpawns
struct npc_proudhoofAI
struct npc_orphaned_mammoth_calfAI
struct MammothTrapBoreanAI
struct PlantWarsongBanner
Enumerations
enum {
NPC_NESINGWARY_TRAPPER = 25835 , GO_QUALITY_FUR = 187983 , SAY_PHRASE_1 = -1000599 , SAY_PHRASE_2 = -1000600 ,
SAY_PHRASE_3 = -1000601 , SAY_PHRASE_4 = -1000602
}
enum {
SPELL_THROW_WOLF_BAIT = 53326 , SPELL_PLACE_WOLF_BAIT = 46072 , SPELL_HAS_EATEN = 46073 , SPELL_SUMMON_DROPPINGS = 46075 ,
FACTION_MONSTER = 634 , POINT_DEST = 1
}
enum { SPELL_SUMMON_EXPLOSIVES_CART_FIRE = 46799 , SPELL_SUMMON_SCOURGE_BURROWER = 46800 , SPELL_COSMETIC_HUGE_EXPLOSION = 46225 , SPELL_CANNON_FIRE = 42445 }
enum {
QUEST_ESCAPE_FROM_WINTERFIN_CAVERNS = 11570 , GO_CAGE = 187369 , SAY_START_1 = -1000575 , SAY_START_2 = -1000576 ,
SAY_END_1 = -1000577 , SAY_END_2 = -1000578
}
enum {
SPELL_ARCANE_CHAINS = 45611 , SPELL_ARCANE_CHAINS_CHANNEL = 45630 , SPELL_SUMMON_CHAINS_CHARACTER = 45625 , NPC_BERYL_SORCERER = 25316 ,
NPC_CAPTURED_BERYL_SORCERER = 25474
}
enum {
SPELL_INTANGIBLE_PRESENCE = 36513 , SPELL_NETHERBREATH = 36631 , SPELL_DRAKE_HARPOON = 46607 , SPELL_RED_DRAGONBLOOD = 46620 ,
SPELL_CAPTURE_TRIGGER = 46673 , SPELL_SUBDUED = 46675 , SPELL_DRAKE_HATCHLING_SUBDUED = 46691 , SPELL_DRAKE_VOMIT_PERIODIC = 46678 ,
SPELL_DRAKE_TURN_IN = 46696 , SPELL_STRIP_AURAS = 46693 , SPELL_DRAKE_COMPLETION_PING = 46702 , SPELL_RAELORASZ_FIREBALL = 46704 ,
SPELL_COMPLETE_IMMOLATION = 46703 , NPC_RAELORASZ = 26117 , NPC_NEXUS_DRAKE_HATCHLING = 26127 , NPC_COLDARRA_DRAKE_HUNT_INVISMAN = 26175 ,
QUEST_DRAKE_HUNT = 11919 , QUEST_DRAKE_HUNT_DAILY = 11940 , FACTION_FRIENDLY = 35
}
enum {
SPELL_REINFORCED_NET = 46361 , SPELL_NET = 47021 , SPELL_INCINERATE_COSMETIC = 45863 , SPELL_INCINERATE = 32707 ,
NPC_FLAMESPITTER = 25582
}
enum {
SAY_BONKER_START = -1001013 , SAY_BONKER_GO = -1001014 , SAY_BONKER_AGGRO = -1001015 , SAY_BONKER_LEFT = -1001016 ,
SAY_BONKER_COMPLETE = -1001017 , QUEST_ID_GET_ME_OUTA_HERE = 11673
}
enum {
SPELL_CREATES_CARRIED = 46340 , SPELL_JENNY_CREDIT_TRIGGER = 46357 , SPELL_JENNY_CREDIT = 46358 , NPC_FEZZIX = 25849 ,
QUEST_ID_LOADER_UP = 11881
}
enum { SPELL_SEAFORIUM_DEPTH_EXPLOSION = 45502 }
enum {
SAY_MOOTOO_Y_START = -1001226 , SAY_1_MOOTOO_Y = -1001227 , SAY_2_MOOTOO_Y = -1001228 , SAY_3_MOOTOO_Y = -1001229 ,
SAY_4_MOOTOO_Y = -1001230 , SAY_5_MOOTOO_Y = -1001231 , SAY_6_MOOTOO_Y = -1001232 , SAY_7_MOOTOO_Y = -1001233 ,
SAY_8_MOOTOO_Y = -1001234 , SAY_9_MOOTOO_Y = -1001237 , SAY_CREDIT_MOOTOO_Y = -1001235 , SAY_1_ELDER_MOOTOO = -1001236 ,
SAY_2_ELDER_MOOTOO = -1001238 , NPC_ELDER_MOOTOO = 25503 , QUEST_ESCAPING_THE_MIST = 11664
}
enum { QUEST_MASTER_THE_STORM = 11895 , NPC_STORM_TEMPEST = 26045 }
enum {
SAY_QUEST_START = -1001312 , SAY_QUEST_INTRO = -1001313 , SAY_AMBUSH = -1001314 , SAY_AGGRO = -1001315 ,
SAY_AMBUSH_COMPLETE = -1001316 , SAY_FINAL_BATTLE = -1001317 , SAY_QUEST_END = -1001318 , SPELL_FORCEFUL_CLEAVE = 35473 ,
NPC_RISEN_LONGRUNNER = 25350 , NPC_GHOSTLY_SAGE = 25351 , NPC_COMMANDER_STEELJAW = 25359 , NPC_CARAVAN_GUARD = 25338 ,
QUEST_WE_STRIKE = 11592 , MAX_PROUDHOOF_SPAWNS = 6
}
enum { SPELL_MAMMOTH_CALL_CREDIT = 46231 , SOUND_ID_QUEST_COMPLETE = 9917 , NPC_KHUNOK_THE_BEHEMOTH = 25862 }
Functions
UnitAI * GetAI_npc_nesingwary_trapper (Creature *pCreature)
UnitAI * GetAI_npc_oil_stained_wolf (Creature *pCreature)
bool EffectDummyCreature_npc_oil_stained_wolf (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectAuraDummy_npc_oil_stained_wolf (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_sinkhole_kill_credit (Creature *pCreature)
bool QuestAccept_npc_lurgglbr (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_lurgglbr (Creature *pCreature)
bool EffectAuraDummy_npc_beryl_sorcerer (const Aura *pAura, bool bApply)
bool EffectAuraDummy_npc_captured_beryl_sorcerer (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_nexus_drake_hatchling (Creature *pCreature)
bool EffectAuraDummy_npc_nexus_drake_hatchling (const Aura *pAura, bool bApply)
bool EffectDummyCreature_npc_nexus_drake_hatchling (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_scourged_flamespitter (Creature *pCreature)
bool EffectAuraDummy_npc_scourged_flamespitter (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_bonker_togglevolt (Creature *pCreature)
bool QuestAccept_npc_bonker_togglevolt (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_jenny (Creature *pCreature)
bool EffectAuraDummy_spell_aura_dummy_crates_carried (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_seaforium_depth_charge (Creature *pCreature)
bool QuestAccept_npc_mootoo_the_younger (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_mootoo_the_youngerAI (Creature *pCreature)
bool NpcSpellClick_npc_storm_totem (Player *pPlayer, Creature *pClickedCreature, uint32)
UnitAI * GetAI_npc_proudhoof (Creature *pCreature)
bool QuestAccept_npc_proudhoof (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_orphaned_mammoth_calf (Creature *pCreature)
void AddSC_borean_tundra ()
Variables
static const ProudhoofSpawns aProudhoofSpawns [MAX_PROUDHOOF_SPAWNS]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_NESINGWARY_TRAPPER
GO_QUALITY_FUR
SAY_PHRASE_1
SAY_PHRASE_2
SAY_PHRASE_3
SAY_PHRASE_4
Definition at line 51 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_THROW_WOLF_BAIT
SPELL_PLACE_WOLF_BAIT
SPELL_HAS_EATEN
SPELL_SUMMON_DROPPINGS
FACTION_MONSTER
POINT_DEST
Definition at line 180 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_EXPLOSIVES_CART_FIRE
SPELL_SUMMON_SCOURGE_BURROWER
SPELL_COSMETIC_HUGE_EXPLOSION
SPELL_CANNON_FIRE
Definition at line 302 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ESCAPE_FROM_WINTERFIN_CAVERNS
GO_CAGE
SAY_START_1
SAY_START_2
SAY_END_1
SAY_END_2
Definition at line 397 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ARCANE_CHAINS
SPELL_ARCANE_CHAINS_CHANNEL
SPELL_SUMMON_CHAINS_CHARACTER
NPC_BERYL_SORCERER
NPC_CAPTURED_BERYL_SORCERER
Definition at line 538 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_INTANGIBLE_PRESENCE
SPELL_NETHERBREATH
SPELL_DRAKE_HARPOON
SPELL_RED_DRAGONBLOOD
SPELL_CAPTURE_TRIGGER
SPELL_SUBDUED
SPELL_DRAKE_HATCHLING_SUBDUED
SPELL_DRAKE_VOMIT_PERIODIC
SPELL_DRAKE_TURN_IN
SPELL_STRIP_AURAS
SPELL_DRAKE_COMPLETION_PING
SPELL_RAELORASZ_FIREBALL
SPELL_COMPLETE_IMMOLATION
NPC_RAELORASZ
NPC_NEXUS_DRAKE_HATCHLING
NPC_COLDARRA_DRAKE_HUNT_INVISMAN
QUEST_DRAKE_HUNT
QUEST_DRAKE_HUNT_DAILY
FACTION_FRIENDLY
Definition at line 604 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_REINFORCED_NET
SPELL_NET
SPELL_INCINERATE_COSMETIC
SPELL_INCINERATE
NPC_FLAMESPITTER
Definition at line 856 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_BONKER_START
SAY_BONKER_GO
SAY_BONKER_AGGRO
SAY_BONKER_LEFT
SAY_BONKER_COMPLETE
QUEST_ID_GET_ME_OUTA_HERE
Definition at line 966 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CREATES_CARRIED
SPELL_JENNY_CREDIT_TRIGGER
SPELL_JENNY_CREDIT
NPC_FEZZIX
QUEST_ID_LOADER_UP
Definition at line 1047 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SEAFORIUM_DEPTH_EXPLOSION
Definition at line 1126 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MOOTOO_Y_START
SAY_1_MOOTOO_Y
SAY_2_MOOTOO_Y
SAY_3_MOOTOO_Y
SAY_4_MOOTOO_Y
SAY_5_MOOTOO_Y
SAY_6_MOOTOO_Y
SAY_7_MOOTOO_Y
SAY_8_MOOTOO_Y
SAY_9_MOOTOO_Y
SAY_CREDIT_MOOTOO_Y
SAY_1_ELDER_MOOTOO
SAY_2_ELDER_MOOTOO
NPC_ELDER_MOOTOO
QUEST_ESCAPING_THE_MIST
Definition at line 1170 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MASTER_THE_STORM
NPC_STORM_TEMPEST
Definition at line 1293 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_QUEST_START
SAY_QUEST_INTRO
SAY_AMBUSH
SAY_AGGRO
SAY_AMBUSH_COMPLETE
SAY_FINAL_BATTLE
SAY_QUEST_END
SPELL_FORCEFUL_CLEAVE
NPC_RISEN_LONGRUNNER
NPC_GHOSTLY_SAGE
NPC_COMMANDER_STEELJAW
NPC_CARAVAN_GUARD
QUEST_WE_STRIKE
MAX_PROUDHOOF_SPAWNS
Definition at line 1311 of file borean_tundra.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_MAMMOTH_CALL_CREDIT
SOUND_ID_QUEST_COMPLETE
NPC_KHUNOK_THE_BEHEMOTH
Definition at line 1483 of file borean_tundra.cpp.
Function Documentation
AddSC_borean_tundra()
void AddSC_borean_tundra ()
Definition at line 1563 of file borean_tundra.cpp.
References EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_oil_stained_wolf(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_crates_carried(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_oil_stained_wolf(), Script::GetAI, GetAI_npc_bonker_togglevolt(), GetAI_npc_jenny(), GetAI_npc_lurgglbr(), GetAI_npc_mootoo_the_youngerAI(), GetAI_npc_nesingwary_trapper(), GetAI_npc_nexus_drake_hatchling(), GetAI_npc_oil_stained_wolf(), GetAI_npc_orphaned_mammoth_calf(), GetAI_npc_proudhoof(), GetAI_npc_scourged_flamespitter(), GetAI_npc_seaforium_depth_charge(), GetAI_npc_sinkhole_kill_credit(), Script::GetGameObjectAI, Script::Name, NpcSpellClick_npc_storm_totem(), Script::pEffectAuraDummy, Script::pEffectDummyNPC, Script::pNpcSpellClick, Script::pQuestAcceptNPC, QuestAccept_npc_bonker_togglevolt(), QuestAccept_npc_lurgglbr(), QuestAccept_npc_mootoo_the_younger(), QuestAccept_npc_proudhoof(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_npc_beryl_sorcerer()
bool EffectAuraDummy_npc_beryl_sorcerer (const Aura * pAura, bool bApply)
Definition at line 549 of file borean_tundra.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Creature::ForcedDespawn(), Aura::GetCaster(), Aura::GetEffIndex(), Object::GetEntry(), Unit::GetHealthPercent(), Aura::GetId(), Aura::GetTarget(), Object::GetTypeId(), NPC_BERYL_SORCERER, SPELL_ARCANE_CHAINS, SPELL_ARCANE_CHAINS_CHANNEL, SPELL_SUMMON_CHAINS_CHARACTER, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
Referenced by AddSC_borean_tundra().
EffectAuraDummy_npc_captured_beryl_sorcerer()
bool EffectAuraDummy_npc_captured_beryl_sorcerer (const Aura * pAura, bool bApply)
Definition at line 579 of file borean_tundra.cpp.
References EFFECT_INDEX_0, WorldObject::GetAngle(), Aura::GetCaster(), WorldObject::GetDistance(), Aura::GetEffIndex(), Object::GetEntry(), Aura::GetId(), Unit::GetMotionMaster(), Aura::GetTarget(), Object::GetTypeId(), M_PI_F, MotionMaster::MoveFollow(), NPC_CAPTURED_BERYL_SORCERER, SPELL_ARCANE_CHAINS_CHANNEL, and TYPEID_PLAYER.
Referenced by AddSC_borean_tundra().
EffectAuraDummy_npc_nexus_drake_hatchling()
bool EffectAuraDummy_npc_nexus_drake_hatchling (const Aura * pAura, bool bApply)
Definition at line 748 of file borean_tundra.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, UnitAI::AttackStart(), Unit::CastSpell(), EFFECT_INDEX_0, Aura::GetCaster(), Aura::GetEffIndex(), Object::GetEntry(), Aura::GetId(), Aura::GetTarget(), Object::GetTypeId(), Unit::HasAura(), NPC_NEXUS_DRAKE_HATCHLING, UnitAI::SendAIEvent(), SPELL_CAPTURE_TRIGGER, SPELL_DRAKE_HARPOON, SPELL_RED_DRAGONBLOOD, SPELL_SUBDUED, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
Referenced by AddSC_borean_tundra().
EffectAuraDummy_npc_oil_stained_wolf()
bool EffectAuraDummy_npc_oil_stained_wolf (const Aura * pAura, bool bApply)
Definition at line 275 of file borean_tundra.cpp.
References EFFECT_INDEX_0, EMOTE_ONESHOT_CUSTOMSPELL01, CreatureInfo::Faction, Creature::GetCreatureInfo(), Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), Unit::HandleEmote(), Unit::setFaction(), and SPELL_HAS_EATEN.
Referenced by AddSC_borean_tundra().
EffectAuraDummy_npc_scourged_flamespitter()
bool EffectAuraDummy_npc_scourged_flamespitter (const Aura * pAura, bool bApply)
Definition at line 941 of file borean_tundra.cpp.
References MotionMaster::Clear(), EFFECT_INDEX_0, Aura::GetCaster(), Aura::GetEffIndex(), Object::GetEntry(), Map::GetHeight(), Aura::GetId(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Aura::GetTarget(), Object::GetTypeId(), MotionMaster::MovePoint(), NPC_FLAMESPITTER, Creature::SetWalk(), SPELL_REINFORCED_NET, and TYPEID_PLAYER.
Referenced by AddSC_borean_tundra().
EffectAuraDummy_spell_aura_dummy_crates_carried()
bool EffectAuraDummy_spell_aura_dummy_crates_carried (const Aura * pAura, bool bApply)
Definition at line 1112 of file borean_tundra.cpp.
References AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), and SPELL_CREATES_CARRIED.
Referenced by AddSC_borean_tundra().
EffectDummyCreature_npc_nexus_drake_hatchling()
bool EffectDummyCreature_npc_nexus_drake_hatchling (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 796 of file borean_tundra.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, Unit::CastSpell(), MotionMaster::Clear(), Unit::CombatStop(), CONTACT_DISTANCE, EFFECT_INDEX_0, FACTION_FRIENDLY, Creature::ForcedDespawn(), GetClosestCreatureWithEntry(), Object::GetEntry(), Unit::GetMotionMaster(), Player::GetQuestStatus(), Object::GetTypeId(), Unit::HasAura(), MotionMaster::MovePoint(), NPC_NEXUS_DRAKE_HATCHLING, NPC_RAELORASZ, QUEST_DRAKE_HUNT, QUEST_DRAKE_HUNT_DAILY, QUEST_STATUS_INCOMPLETE, UnitAI::SendAIEvent(), Creature::SetFactionTemporary(), Unit::SetStandState(), SPELL_CAPTURE_TRIGGER, SPELL_COMPLETE_IMMOLATION, SPELL_DRAKE_COMPLETION_PING, SPELL_DRAKE_HATCHLING_SUBDUED, SPELL_DRAKE_TURN_IN, SPELL_DRAKE_VOMIT_PERIODIC, SPELL_RAELORASZ_FIREBALL, SPELL_SUBDUED, TEMPFACTION_RESTORE_REACH_HOME, TEMPFACTION_RESTORE_RESPAWN, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and UNIT_STAND_STATE_DEAD.
Referenced by AddSC_borean_tundra().
EffectDummyCreature_npc_oil_stained_wolf()
bool EffectDummyCreature_npc_oil_stained_wolf (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 254 of file borean_tundra.cpp.
References CONTACT_DISTANCE, EFFECT_INDEX_0, FACTION_MONSTER, WorldObject::GetContactPoint(), Unit::GetFaction(), Unit::GetMotionMaster(), Unit::HasAura(), MotionMaster::MoveIdle(), MotionMaster::MovePoint(), POINT_DEST, Creature::SetFactionTemporary(), Creature::SetWalk(), SPELL_HAS_EATEN, and SPELL_THROW_WOLF_BAIT.
Referenced by AddSC_borean_tundra().
GetAI_npc_bonker_togglevolt()
UnitAI* GetAI_npc_bonker_togglevolt (Creature * pCreature)
Definition at line 1027 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_jenny()
UnitAI* GetAI_npc_jenny (Creature * pCreature)
Definition at line 1107 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_lurgglbr()
UnitAI* GetAI_npc_lurgglbr (Creature * pCreature)
Definition at line 529 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_mootoo_the_youngerAI()
UnitAI* GetAI_npc_mootoo_the_youngerAI (Creature * pCreature)
Definition at line 1284 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_nesingwary_trapper()
UnitAI* GetAI_npc_nesingwary_trapper (Creature * pCreature)
Definition at line 171 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_nexus_drake_hatchling()
UnitAI* GetAI_npc_nexus_drake_hatchling (Creature * pCreature)
Definition at line 743 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_oil_stained_wolf()
UnitAI* GetAI_npc_oil_stained_wolf (Creature * pCreature)
Definition at line 249 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_orphaned_mammoth_calf()
UnitAI* GetAI_npc_orphaned_mammoth_calf (Creature * pCreature)
Definition at line 1519 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_proudhoof()
UnitAI* GetAI_npc_proudhoof (Creature * pCreature)
Definition at line 1463 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_scourged_flamespitter()
UnitAI* GetAI_npc_scourged_flamespitter (Creature * pCreature)
Definition at line 936 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_seaforium_depth_charge()
UnitAI* GetAI_npc_seaforium_depth_charge (Creature * pCreature)
Definition at line 1161 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
GetAI_npc_sinkhole_kill_credit()
UnitAI* GetAI_npc_sinkhole_kill_credit (Creature * pCreature)
Definition at line 388 of file borean_tundra.cpp.
Referenced by AddSC_borean_tundra().
NpcSpellClick_npc_storm_totem()
bool NpcSpellClick_npc_storm_totem (Player * pPlayer, Creature * pClickedCreature, uint32)
Definition at line 1299 of file borean_tundra.cpp.
References GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::IsInCombat(), NPC_STORM_TEMPEST, QUEST_MASTER_THE_STORM, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN.
Referenced by AddSC_borean_tundra().
QuestAccept_npc_bonker_togglevolt()
bool QuestAccept_npc_bonker_togglevolt (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1032 of file borean_tundra.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_GET_ME_OUTA_HERE, and UnitAI::SendAIEvent().
Referenced by AddSC_borean_tundra().
QuestAccept_npc_lurgglbr()
bool QuestAccept_npc_lurgglbr (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 516 of file borean_tundra.cpp.
References Creature::AI(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_ESCAPE_FROM_WINTERFIN_CAVERNS, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_borean_tundra().
QuestAccept_npc_mootoo_the_younger()
bool QuestAccept_npc_mootoo_the_younger (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1273 of file borean_tundra.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ESCAPING_THE_MIST, and UnitAI::SendAIEvent().
Referenced by AddSC_borean_tundra().
QuestAccept_npc_proudhoof()
bool QuestAccept_npc_proudhoof (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1468 of file borean_tundra.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_WE_STRIKE, and UnitAI::SendAIEvent().
Referenced by AddSC_borean_tundra().
Variable Documentation
aProudhoofSpawns
const ProudhoofSpawns aProudhoofSpawns[MAX_PROUDHOOF_SPAWNS] static
Initial value:
=
{
    { NPC_RISEN_LONGRUNNER,     3970.342f, 5769.431f, 72.759f, 0.549f },
    { NPC_RISEN_LONGRUNNER,     3987.955f, 5790.864f, 74.124f, 4.443f },
    { NPC_RISEN_LONGRUNNER,     3981.751f, 5767.377f, 71.785f, 1.508f },
    { NPC_GHOSTLY_SAGE,         3995.641f, 5773.730f, 71.079f, 2.772f },
    { NPC_GHOSTLY_SAGE,         3973.069f, 5783.232f, 74.131f, 5.856f },
    { NPC_COMMANDER_STEELJAW,   3880.034f, 5719.530f, 66.578f, 1.048f },
}
Definition at line 1339 of file borean_tundra.cpp.
Referenced by npc_proudhoofAI::WaypointReached().