CMaNGOS_WoTLK: boss_nadox.cpp File Reference
boss_nadox.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ahnkahet.h"
Data Structures
struct mob_ahnkahar_eggAI
struct boss_nadoxAI
Enumerations
enum {
SAY_AGGRO = -1619000 , SAY_SUMMON_EGG_1 = -1619001 , SAY_SUMMON_EGG_2 = -1619002 , SAY_SLAY_1 = -1619003 ,
SAY_SLAY_2 = -1619004 , SAY_SLAY_3 = -1619005 , SAY_DEATH = -1619006 , EMOTE_HATCH = -1619007 ,
SPELL_BROOD_PLAGUE = 56130 , SPELL_BROOD_PLAGUE_H = 59467 , SPELL_BERSERK = 26662 , SPELL_BROOD_RAGE = 59465 ,
SPELL_GUARDIAN_AURA = 56151 , SPELL_SUMMON_SWARM_GUARDIAN = 56120 , SPELL_SUMMON_SWARMERS = 56119 , NPC_AHNKAHAR_GUARDIAN = 30176 ,
NPC_AHNKAHAR_SWARMER = 30178
}
Functions
UnitAI * GetAI_mob_ahnkahar_egg (Creature *pCreature)
UnitAI * GetAI_boss_nadox (Creature *pCreature)
void AddSC_boss_nadox ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SUMMON_EGG_1
SAY_SUMMON_EGG_2
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
EMOTE_HATCH
SPELL_BROOD_PLAGUE
SPELL_BROOD_PLAGUE_H
SPELL_BERSERK
SPELL_BROOD_RAGE
SPELL_GUARDIAN_AURA
SPELL_SUMMON_SWARM_GUARDIAN
SPELL_SUMMON_SWARMERS
NPC_AHNKAHAR_GUARDIAN
NPC_AHNKAHAR_SWARMER
Definition at line 27 of file boss_nadox.cpp.
Function Documentation
AddSC_boss_nadox()
void AddSC_boss_nadox ()
Definition at line 240 of file boss_nadox.cpp.
References Script::GetAI, GetAI_boss_nadox(), GetAI_mob_ahnkahar_egg(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_nadox()
UnitAI* GetAI_boss_nadox (Creature * pCreature)
Definition at line 235 of file boss_nadox.cpp.
Referenced by AddSC_boss_nadox().
GetAI_mob_ahnkahar_egg()
UnitAI* GetAI_mob_ahnkahar_egg (Creature * pCreature)
Definition at line 99 of file boss_nadox.cpp.
Referenced by AddSC_boss_nadox().