CMaNGOS_WoTLK: boss_illidan.cpp File Reference
boss_illidan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "black_temple.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct Locations
struct boss_illidan_stormrageAI
struct npc_akama_illidanAI
struct boss_maievAI
struct npc_cage_trap_triggerAI
struct npc_flame_of_azzinothAI
struct npc_shadow_demonAI
struct npc_blade_of_azzinothAI
struct npc_parasitic_shadowfiendAI
struct ParasiticShadowfiendAura
struct ShadowPrison
Enumerations
enum {
SAY_AKAMA_COUNCIL_DEAD = -1564140 , SAY_AKAMA_BEWARE = -1564120 , SAY_AKAMA_OPEN_DOOR_1 = -1564131 , SAY_AKAMA_OPEN_DOOR_2 = -1564132 ,
SAY_UDALO_OPEN_DOOR_3 = -1564133 , SAY_OLUM_OPEN_DOOR_4 = -1564134 , SAY_AKAMA_OPEN_DOOR_5 = -1564136 , GOSSIP_ITEM_PREPARE = -3564001 ,
GOSSIP_ITEM_START_EVENT = -3564002 , TEXT_ID_AKAMA_ILLIDAN_PREPARE = 10465 , TEXT_ID_AKAMA_ILLIDAN_START = 10835 , SAY_ILLIDAN_SPEECH_1 = -1564097 ,
SAY_AKAMA_SPEECH_2 = -1564098 , SAY_ILLIDAN_SPEECH_3 = -1564099 , SAY_AKAMA_SPEECH_4 = -1564100 , SAY_ILLIDAN_SPEECH_5 = -1564101 ,
SAY_ILLIDAN_MINION = -1564121 , SAY_AKAMA_LEAVE = -1564122 , SAY_ILLIDAN_SPEECH_6 = -1564102 , SAY_MAIEV_SPEECH_7 = -1564103 ,
SAY_ILLIDAN_SPEECH_8 = -1564104 , SAY_MAIEV_SPEECH_9 = -1564105 , SAY_MAIEV_TRAP = -1564118 , SAY_MAIEV_FALL = -1564141 ,
SAY_MAIEV_EPILOGUE_1 = -1564107 , SAY_ILLIDAN_EPILOGUE_2 = -1564108 , SAY_MAIEV_EPILOGUE_3 = -1564109 , SAY_MAIEV_EPILOGUE_4 = -1564110 ,
SAY_AKAMA_EPILOGUE_5 = -1564111 , SAY_KILL1 = -1564123 , SAY_KILL2 = -1564124 , SAY_TAKEOFF = -1564125 ,
SAY_SUMMONFLAMES = -1564126 , SAY_EYE_BLAST = -1564127 , SAY_MORPH = -1564128 , SAY_FRENZY = -1564106 ,
SAY_BERSERK = -1564129 , SAY_TAUNT_1 = -1564112 , SAY_TAUNT_2 = -1564113 , SAY_TAUNT_3 = -1564114 ,
SAY_TAUNT_4 = -1564115 , SAY_MAIEV_TAUNT_1 = -1564116 , SAY_MAIEV_TAUNT_2 = -1564117 , SAY_MAIEV_TAUNT_3 = -1564119 ,
SPELL_SHEAR = 41032 , SPELL_FLAME_CRASH = 40832 , SPELL_DRAW_SOUL = 40904 , SPELL_PARASITIC_SHADOWFIEND_BOSS = 41917 ,
SPELL_SUMMON_PARASITICS = 41915 , SPELL_AGONIZING_FLAMES = 40834 , SPELL_FRENZY = 40683 , SPELL_THROW_GLAIVE = 39635 ,
SPELL_THROW_GLAIVE_VISUAL = 39849 , SPELL_GLAIVE_RETURNS = 39873 , SPELL_FIREBALL = 40598 , SPELL_DARK_BARRAGE = 40585 ,
SPELL_EYE_BLAST_DUMMY = 39908 , SPELL_DEMON_TRANSFORM_1 = 40511 , SPELL_DEMON_TRANSFORM_2 = 40398 , SPELL_DEMON_TRANSFORM_3 = 40510 ,
SPELL_DEMON_FORM = 40506 , SPELL_SHADOW_BLAST = 41078 , SPELL_FLAME_BURST = 41126 , SPELL_SUMMON_SHADOW_DEMONS = 41117 ,
SPELL_KNEEL_INTRO = 39656 , SPELL_SUMMMON_MAIEV = 40403 , SPELL_TELEPORT_MAIEV = 41221 , SPELL_SHADOW_PRISON = 40647 ,
SPELL_CAGE_TRAP = 40693 , SPELL_DEATH = 41218 , SPELL_BERSERK = 45078 , SPELL_PASSIVE_HIT = 43689 ,
SPELL_EMOTE_TALK_QUESTION = 41616 , SPELL_AKAMA_DOOR_FAIL = 41271 , SPELL_AKAMA_DOOR_CHANNEL = 41268 , SPELL_DEATHSWORN_DOOR_CHANNEL = 41269 ,
SPELL_HEALING_POTION = 40535 , SPELL_CHAIN_LIGHTNING = 40536 , SPELL_AKAMA_DESPAWN = 41242 , SPELL_ARCANE_EXPL_VISUAL = 35426 ,
SPELL_SHADOW_STRIKE = 40685 , SPELL_THROW_DAGGER = 41152 , SPELL_CAGE_TRAP_SUMMON = 40694 , SPELL_TELEPORT_VISUAL = 41236 ,
SPELL_MAIEV_DOWN = 40409 , SPELL_FLAME_CRASH_EFFECT = 40836 , SPELL_EYE_BLAST_TRIGGER = 40017 , SPELL_BLAZE_EFFECT = 40610 ,
SPELL_INSTANT_BLADE_BIRTH = 40031 , SPELL_RANGE_MARKER = 41997 , SPELL_SUMMON_TEAR_AZZINOTH = 39855 , SPELL_AZZINOTH_CHANNEL = 39857 ,
SPELL_FLAME_BLAST = 40631 , SPELL_CHARGE = 42003 , SPELL_UNCAGED_WRATH = 39869 , SPELL_BLAZE = 40637 ,
SPELL_PARASITIC_SHADOWFIEND_P = 41913 , SPELL_PARASITIC_SHADOWFIEND_ADD = 41914 , SPELL_SHADOWFORM_PARASITE = 34429 , SPELL_SHADOW_DEMON_PASSIVE = 41079 ,
SPELL_CONSUME_SOUL = 41080 , SPELL_PARALYZE = 41083 , SPELL_CAGE_TRAP_PERIODIC = 40760 , SPELL_CAGE_TRAP_DUMMY = 40761 ,
SPELL_CAGED = 40695 , SPELL_QUIET_SUICIDE = 3617 , NPC_CAGE_TRAP_TRIGGER_1 = 23292 , NPC_CAGE_TRAP_TRIGGER_2 = 23293 ,
NPC_CAGE_TRAP_TRIGGER_3 = 23294 , NPC_CAGE_TRAP_TRIGGER_4 = 23295 , NPC_CAGE_TRAP_TRIGGER_5 = 23296 , NPC_CAGE_TRAP_TRIGGER_6 = 23297 ,
NPC_CAGE_TRAP_TRIGGER_7 = 23298 , NPC_CAGE_TRAP_TRIGGER_8 = 23299 , GO_CAGE_TRAP = 185916 , EQUIP_ID_MAIN_HAND = 32837 ,
EQUIP_ID_OFF_HAND = 32838 , MAX_ILLIDARI_ELITES = 10 , MAX_CAGE_SPELLS = 8 , MAX_FLAME_AZZINOTH = 2 ,
DUMMY_EMOTE_ID_1 = 1 , DUMMY_EMOTE_ID_2 = 2 , DUMMY_EMOTE_ID_3 = 3 , DUMMY_EMOTE_ID_4 = 4 ,
DUMMY_EMOTE_ID_5 = 7 , POINT_ILLIDAN_FLIGHT = 0 , POINT_ILLIDAN_FLIGHT_RANDOM = 1 , POINT_ILLIDAN_LANDING = 2 ,
POINT_AKAMA_ILLIDAN_CLOSE = 1 , POINT_AKAMA_COUNCIL_DEAD_END = 2 , POINT_AKAMA_DOOR_STOP = 8 , POINT_AKAMA_ILLIDAN_STOP = 5 ,
POINT_AKAMA_ILLDARI = 7 , POINT_AKAMA_BACK_UP = 6 , PATH_ID_AKAMA_COUNCIL_DEAD = 1 , PATH_ID_AKAMA_COUNCIL_PRE_DOOR = 2 ,
PATH_ID_AKAMA_COUNCIL_POST_DOOR = 3 , PATH_ID_AKAMA_ILLIDAN = 4 , PATH_ID_AKAMA_FIGHT_ILLIDARI = 5 , PATH_ID_AKAMA_BACK_UP = 6 ,
SOUND_KIT_AKAMA_CHANNEL_DOOR = 11717 , SOUND_KIT_ILLIDAN_AGGRO = 11725 , SOUND_KIT_ILLIDAN_90 = 11726 , SOUND_KIT_ILLIDAN_TAKEOFF = 11727 ,
SOUND_KIT_ILLIDAN_P3 = 11728 , SOUND_KIT_ILLIDAN_P5 = 11729
}
enum IllidanPhase {
PHASE_1_AKAMA , PHASE_2_FLIGHT , PHASE_3_NORMAL , PHASE_4_DEMON ,
PHASE_5_MAIEV , PHASE_TRANSITION
}
enum PhaseTransition { PHASETRANSITION_NONE , PHASETRANSITION_LIFTOFF , PHASETRANSITION_LAND , PHASETRANSITION_MAIEV }
enum IllidanActions {
ILLIDAN_ACTION_BERSERK , ILLIDAN_ACTION_AKAMA , ILLIDAN_ACTION_PHASE_2 , ILLIDAN_ACTION_PHASE_3 ,
ILLIDAN_ACTION_PHASE_5 , ILLIDAN_ACTION_TRANSFORM , ILLIDAN_ACTION_TRAP , ILLIDAN_ACTION_ENRAGE ,
ILLIDAN_ACTION_FLAME_BURST , ILLIDAN_ACTION_SHADOW_DEMON , ILLIDAN_ACTION_SHADOW_BLAST , ILLIDAN_ACTION_AGONISING_FLAMES ,
ILLIDAN_ACTION_EYE_BLAST , ILLIDAN_ACTION_DARK_BARRAGE , ILLIDAN_ACTION_FIREBALL , ILLIDAN_ACTION_SHADOW_FIEND ,
ILLIDAN_ACTION_FLAME_CRASH , ILLIDAN_ACTION_SHEAR , ILLIDAN_ACTION_DRAW_SOUL , ILLIDAN_ACTIONS_MAX ,
ILLIDAN_ACTION_PHASE_TRANSITION
}
enum AkamaStages { AKAMA_STAGE_COUNCIL = 0 , AKAMA_STAGE_ILLIDAN = 1 }
enum AkamaActions {
AKAMA_ACTION_HEAL , AKAMA_ACTION_CHAIN_LIGHTNING , AKAMA_ACTION_MAX , AKAMA_SUMMON_ILLIDARI ,
AKAMA_OUTRO_DELAY , AKAMA_OUTRO_ACTIONS , AKAMA_ACTION_LOW_HEALTH , AKAMA_ACTION_DESTRUCTIVE_POISON ,
AKAMA_ACTION_CHAIN_LIGHTNING , AKAMA_ACTION_MAX
}
enum MaievActions {
MAIEV_ACTION_SHADOW_STRIKE , MAIEV_ACTION_THROW_DAGGER , MAIEV_ACTION_TAUNT , MAIEV_ACTION_MAX ,
MAIEV_ACTION_TRAP
}
enum FlameActions {
FLAME_ACTION_WRATH_CHECK , FLAME_ACTION_FLAME_BLAST , FLAME_ACTION_SUMMON_BLAZE , FLAME_ACTION_CHARGE ,
FLAME_ACTION_MAX , FLAME_ACTION_ATTACK
}
Functions
bool GossipHello_npc_akama_illidan (Player *player, Creature *creature)
bool GossipSelect_npc_akama_illidan (Player *player, Creature *creature, uint32, uint32 action)
bool GOUse_go_cage_trap (Player *player, GameObject *go)
void AddSC_boss_illidan ()
Variables
static const uint32 aCagedSummonSpells [MAX_CAGE_SPELLS] = { 40696, 40697, 40698, 40699, 40700, 40701, 40702, 40703 }
static const uint32 aCagedVisualSpells [MAX_CAGE_SPELLS] = { 40704, 40707, 40708, 40709, 40710, 40711, 40712, 40713 }
static const DialogueEntry aIntroDialogue []
static const DialogueEntry aEventDialogue []
static const DialogueEntry aEpilogueDialogue []
static const Locations aCenterLoc []
static const Locations aIllidariElitesPos [MAX_ILLIDARI_ELITES]
static const Locations illidanFlightPos []
static const Locations aEyeBlastPos []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AKAMA_COUNCIL_DEAD
SAY_AKAMA_BEWARE
SAY_AKAMA_OPEN_DOOR_1
SAY_AKAMA_OPEN_DOOR_2
SAY_UDALO_OPEN_DOOR_3
SAY_OLUM_OPEN_DOOR_4
SAY_AKAMA_OPEN_DOOR_5
GOSSIP_ITEM_PREPARE
GOSSIP_ITEM_START_EVENT
TEXT_ID_AKAMA_ILLIDAN_PREPARE
TEXT_ID_AKAMA_ILLIDAN_START
SAY_ILLIDAN_SPEECH_1
SAY_AKAMA_SPEECH_2
SAY_ILLIDAN_SPEECH_3
SAY_AKAMA_SPEECH_4
SAY_ILLIDAN_SPEECH_5
SAY_ILLIDAN_MINION
SAY_AKAMA_LEAVE
SAY_ILLIDAN_SPEECH_6
SAY_MAIEV_SPEECH_7
SAY_ILLIDAN_SPEECH_8
SAY_MAIEV_SPEECH_9
SAY_MAIEV_TRAP
SAY_MAIEV_FALL
SAY_MAIEV_EPILOGUE_1
SAY_ILLIDAN_EPILOGUE_2
SAY_MAIEV_EPILOGUE_3
SAY_MAIEV_EPILOGUE_4
SAY_AKAMA_EPILOGUE_5
SAY_KILL1
SAY_KILL2
SAY_TAKEOFF
SAY_SUMMONFLAMES
SAY_EYE_BLAST
SAY_MORPH
SAY_FRENZY
SAY_BERSERK
SAY_TAUNT_1
SAY_TAUNT_2
SAY_TAUNT_3
SAY_TAUNT_4
SAY_MAIEV_TAUNT_1
SAY_MAIEV_TAUNT_2
SAY_MAIEV_TAUNT_3
SPELL_SHEAR
SPELL_FLAME_CRASH
SPELL_DRAW_SOUL
SPELL_PARASITIC_SHADOWFIEND_BOSS
SPELL_SUMMON_PARASITICS
SPELL_AGONIZING_FLAMES
SPELL_FRENZY
SPELL_THROW_GLAIVE
SPELL_THROW_GLAIVE_VISUAL
SPELL_GLAIVE_RETURNS
SPELL_FIREBALL
SPELL_DARK_BARRAGE
SPELL_EYE_BLAST_DUMMY
SPELL_DEMON_TRANSFORM_1
SPELL_DEMON_TRANSFORM_2
SPELL_DEMON_TRANSFORM_3
SPELL_DEMON_FORM
SPELL_SHADOW_BLAST
SPELL_FLAME_BURST
SPELL_SUMMON_SHADOW_DEMONS
SPELL_KNEEL_INTRO
SPELL_SUMMMON_MAIEV
SPELL_TELEPORT_MAIEV
SPELL_SHADOW_PRISON
SPELL_CAGE_TRAP
SPELL_DEATH
SPELL_BERSERK
SPELL_PASSIVE_HIT
SPELL_EMOTE_TALK_QUESTION
SPELL_AKAMA_DOOR_FAIL
SPELL_AKAMA_DOOR_CHANNEL
SPELL_DEATHSWORN_DOOR_CHANNEL
SPELL_HEALING_POTION
SPELL_CHAIN_LIGHTNING
SPELL_AKAMA_DESPAWN
SPELL_ARCANE_EXPL_VISUAL
SPELL_SHADOW_STRIKE
SPELL_THROW_DAGGER
SPELL_CAGE_TRAP_SUMMON
SPELL_TELEPORT_VISUAL
SPELL_MAIEV_DOWN
SPELL_FLAME_CRASH_EFFECT
SPELL_EYE_BLAST_TRIGGER
SPELL_BLAZE_EFFECT
SPELL_INSTANT_BLADE_BIRTH
SPELL_RANGE_MARKER
SPELL_SUMMON_TEAR_AZZINOTH
SPELL_AZZINOTH_CHANNEL
SPELL_FLAME_BLAST
SPELL_CHARGE
SPELL_UNCAGED_WRATH
SPELL_BLAZE
SPELL_PARASITIC_SHADOWFIEND_P
SPELL_PARASITIC_SHADOWFIEND_ADD
SPELL_SHADOWFORM_PARASITE
SPELL_SHADOW_DEMON_PASSIVE
SPELL_CONSUME_SOUL
SPELL_PARALYZE
SPELL_CAGE_TRAP_PERIODIC
SPELL_CAGE_TRAP_DUMMY
SPELL_CAGED
SPELL_QUIET_SUICIDE
NPC_CAGE_TRAP_TRIGGER_1
NPC_CAGE_TRAP_TRIGGER_2
NPC_CAGE_TRAP_TRIGGER_3
NPC_CAGE_TRAP_TRIGGER_4
NPC_CAGE_TRAP_TRIGGER_5
NPC_CAGE_TRAP_TRIGGER_6
NPC_CAGE_TRAP_TRIGGER_7
NPC_CAGE_TRAP_TRIGGER_8
GO_CAGE_TRAP
EQUIP_ID_MAIN_HAND
EQUIP_ID_OFF_HAND
MAX_ILLIDARI_ELITES
MAX_CAGE_SPELLS
MAX_FLAME_AZZINOTH
DUMMY_EMOTE_ID_1
DUMMY_EMOTE_ID_2
DUMMY_EMOTE_ID_3
DUMMY_EMOTE_ID_4
DUMMY_EMOTE_ID_5
POINT_ILLIDAN_FLIGHT
POINT_ILLIDAN_FLIGHT_RANDOM
POINT_ILLIDAN_LANDING
POINT_AKAMA_ILLIDAN_CLOSE
POINT_AKAMA_COUNCIL_DEAD_END
POINT_AKAMA_DOOR_STOP
POINT_AKAMA_ILLIDAN_STOP
POINT_AKAMA_ILLDARI
POINT_AKAMA_BACK_UP
PATH_ID_AKAMA_COUNCIL_DEAD
PATH_ID_AKAMA_COUNCIL_PRE_DOOR
PATH_ID_AKAMA_COUNCIL_POST_DOOR
PATH_ID_AKAMA_ILLIDAN
PATH_ID_AKAMA_FIGHT_ILLIDARI
PATH_ID_AKAMA_BACK_UP
SOUND_KIT_AKAMA_CHANNEL_DOOR
SOUND_KIT_ILLIDAN_AGGRO
SOUND_KIT_ILLIDAN_90
SOUND_KIT_ILLIDAN_TAKEOFF
SOUND_KIT_ILLIDAN_P3
SOUND_KIT_ILLIDAN_P5
Definition at line 33 of file boss_illidan.cpp.
AkamaActions
enum AkamaActions
Enumerator
AKAMA_ACTION_HEAL
AKAMA_ACTION_CHAIN_LIGHTNING
AKAMA_ACTION_MAX
AKAMA_SUMMON_ILLIDARI
AKAMA_OUTRO_DELAY
AKAMA_OUTRO_ACTIONS
AKAMA_ACTION_LOW_HEALTH
AKAMA_ACTION_DESTRUCTIVE_POISON
AKAMA_ACTION_CHAIN_LIGHTNING
AKAMA_ACTION_MAX
Definition at line 1367 of file boss_illidan.cpp.
AkamaStages
enum AkamaStages
Enumerator
AKAMA_STAGE_COUNCIL
AKAMA_STAGE_ILLIDAN
Definition at line 1361 of file boss_illidan.cpp.
FlameActions
enum FlameActions
Enumerator
FLAME_ACTION_WRATH_CHECK
FLAME_ACTION_FLAME_BLAST
FLAME_ACTION_SUMMON_BLAZE
FLAME_ACTION_CHARGE
FLAME_ACTION_MAX
FLAME_ACTION_ATTACK
Definition at line 1979 of file boss_illidan.cpp.
IllidanActions
enum IllidanActions
Enumerator
ILLIDAN_ACTION_BERSERK
ILLIDAN_ACTION_AKAMA
ILLIDAN_ACTION_PHASE_2
ILLIDAN_ACTION_PHASE_3
ILLIDAN_ACTION_PHASE_5
ILLIDAN_ACTION_TRANSFORM
ILLIDAN_ACTION_TRAP
ILLIDAN_ACTION_ENRAGE
ILLIDAN_ACTION_FLAME_BURST
ILLIDAN_ACTION_SHADOW_DEMON
ILLIDAN_ACTION_SHADOW_BLAST
ILLIDAN_ACTION_AGONISING_FLAMES
ILLIDAN_ACTION_EYE_BLAST
ILLIDAN_ACTION_DARK_BARRAGE
ILLIDAN_ACTION_FIREBALL
ILLIDAN_ACTION_SHADOW_FIEND
ILLIDAN_ACTION_FLAME_CRASH
ILLIDAN_ACTION_SHEAR
ILLIDAN_ACTION_DRAW_SOUL
ILLIDAN_ACTIONS_MAX
ILLIDAN_ACTION_PHASE_TRANSITION
Definition at line 378 of file boss_illidan.cpp.
IllidanPhase
enum IllidanPhase
Enumerator
PHASE_1_AKAMA
PHASE_2_FLIGHT
PHASE_3_NORMAL
PHASE_4_DEMON
PHASE_5_MAIEV
PHASE_TRANSITION
Definition at line 319 of file boss_illidan.cpp.
MaievActions
enum MaievActions
Enumerator
MAIEV_ACTION_SHADOW_STRIKE
MAIEV_ACTION_THROW_DAGGER
MAIEV_ACTION_TAUNT
MAIEV_ACTION_MAX
MAIEV_ACTION_TRAP
Definition at line 1744 of file boss_illidan.cpp.
PhaseTransition
enum PhaseTransition
Enumerator
PHASETRANSITION_NONE
PHASETRANSITION_LIFTOFF
PHASETRANSITION_LAND
PHASETRANSITION_MAIEV
Definition at line 329 of file boss_illidan.cpp.
Function Documentation
AddSC_boss_illidan()
void AddSC_boss_illidan ()
Definition at line 2343 of file boss_illidan.cpp.
References Script::GetAI, GossipHello_npc_akama_illidan(), GossipSelect_npc_akama_illidan(), GOUse_go_cage_trap(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_akama_illidan()
bool GossipHello_npc_akama_illidan (Player * player, Creature * creature)
Definition at line 1709 of file boss_illidan.cpp.
References Object::GetObjectGuid(), WorldObject::GetPositionZ(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_PREPARE, GOSSIP_ITEM_START_EVENT, GOSSIP_SENDER_MAIN, TEXT_ID_AKAMA_ILLIDAN_PREPARE, and TEXT_ID_AKAMA_ILLIDAN_START.
Referenced by AddSC_boss_illidan().
GossipSelect_npc_akama_illidan()
bool GossipSelect_npc_akama_illidan (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1727 of file boss_illidan.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_boss_illidan().
GOUse_go_cage_trap()
bool GOUse_go_cage_trap (Player * player, GameObject * go)
Definition at line 2281 of file boss_illidan.cpp.
References Creature::AI(), Unit::CastSpell(), Creature::ForcedDespawn(), GetClosestCreatureWithEntry(), UnitAI::GetCombatScriptStatus(), boss_illidan_stormrageAI::m_phase, NPC_CAGE_TRAP_DISTURB_TRIGGER, NPC_ILLIDAN_STORMRAGE, PHASE_4_DEMON, SPELL_CAGE_TRAP_DUMMY, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_illidan().
Variable Documentation
aCagedSummonSpells
const uint32 aCagedSummonSpells[MAX_CAGE_SPELLS] = { 40696, 40697, 40698, 40699, 40700, 40701, 40702, 40703 } static
Definition at line 252 of file boss_illidan.cpp.
Referenced by boss_illidan_stormrageAI::ReceiveAIEvent().
aCagedVisualSpells
const uint32 aCagedVisualSpells[MAX_CAGE_SPELLS] = { 40704, 40707, 40708, 40709, 40710, 40711, 40712, 40713 } static
Definition at line 253 of file boss_illidan.cpp.
Referenced by boss_illidan_stormrageAI::ReceiveAIEvent().
aCenterLoc
const Locations aCenterLoc[] static
Initial value:
=
{
    {676.648f, 304.7607f, 354.1909f},
}
Definition at line 342 of file boss_illidan.cpp.
Referenced by boss_illidan_stormrageAI::HandlePhaseTransition().
aEpilogueDialogue
const DialogueEntry aEpilogueDialogue[] static
Initial value:
=
{
    {SAY_MAIEV_EPILOGUE_1,      NPC_MAIEV_SHADOWSONG,   6000},
    {SAY_ILLIDAN_EPILOGUE_2,    NPC_ILLIDAN_STORMRAGE,  18000},
    {NPC_ILLIDAN_STORMRAGE,     0,                      2000},
    {SAY_MAIEV_EPILOGUE_3,      NPC_MAIEV_SHADOWSONG,   13000},
    {SAY_MAIEV_EPILOGUE_4,      NPC_MAIEV_SHADOWSONG,   2000},
    {SPELL_TELEPORT_VISUAL,     0,                      0},
    {0, 0, 0},
}
Definition at line 307 of file boss_illidan.cpp.
aEventDialogue
const DialogueEntry aEventDialogue[] static
Definition at line 273 of file boss_illidan.cpp.
aEyeBlastPos
const Locations aEyeBlastPos[] static
Initial value:
=
{
    {642.7164f, 305.2436f, 353.5596f},
    {652.105f,  259.5127f, 353.0794f},
    {710.8815f, 306.4028f, 353.5962f},
    {708.8524f, 342.2623f, 353.0794f},
}
Definition at line 369 of file boss_illidan.cpp.
Referenced by boss_illidan_stormrageAI::DoCastEyeBlastIfCan().
aIllidariElitesPos
const Locations aIllidariElitesPos[MAX_ILLIDARI_ELITES] static
Initial value:
=
{
    {743.9686f, 289.6447f, 311.1807f},
    {753.8425f, 286.562f, 310.9353f},
    {745.2552f, 322.1574f, 310.4596f},
    {745.3237f, 283.986f, 309.2765f},
    {750.0472f, 282.3274f, 309.4353f},
    {747.0576f, 326.4268f, 309.0688f},
    {751.0878f, 327.6505f, 309.4576f},
    {748.8422f, 288.062f, 310.9782f},
    {750.0322f, 323.6064f, 310.2757f},
    {754.0332f, 325.8136f, 310.3195f},
}
Definition at line 347 of file boss_illidan.cpp.
Referenced by npc_akama_illidanAI::npc_akama_illidanAI().
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_AKAMA_COUNCIL_DEAD,    NPC_AKAMA,              0},
    {DUMMY_EMOTE_ID_1,          0,                      5000},
    {SAY_AKAMA_OPEN_DOOR_1,     NPC_AKAMA,              3500},
    {SPELL_AKAMA_DOOR_FAIL,     0,                      10000},
    {SAY_AKAMA_OPEN_DOOR_2,     NPC_AKAMA,              6000},
    {NPC_SPIRIT_OF_OLUM,        0,                      1500},
    {SAY_UDALO_OPEN_DOOR_3,     NPC_SPIRIT_OF_UDALO,    6000},
    {SAY_OLUM_OPEN_DOOR_4,      NPC_SPIRIT_OF_OLUM,     8000},
    {SPELL_AKAMA_DOOR_CHANNEL,  0,                      11000},
    {GO_ILLIDAN_GATE,           0,                      6500},
    {SAY_AKAMA_OPEN_DOOR_5,     NPC_AKAMA,              8000},
    {EMOTE_ONESHOT_SALUTE,      0,                      3000},
    {NPC_SPIRIT_OF_UDALO,       0,                      0},
    {0, 0, 0},
}
Definition at line 255 of file boss_illidan.cpp.
illidanFlightPos
const Locations illidanFlightPos[] static
Initial value:
=
{
    { 658.8175f, 266.0992f, 370.0833f},
    { 705.2382f, 273.1146f, 370.0833f},
    { 657.8459f, 343.9125f, 370.0833f},
    { 705.9218f, 336.1461f, 370.0815f},
}
Definition at line 361 of file boss_illidan.cpp.
Referenced by boss_illidan_stormrageAI::HandlePhaseTransition(), and boss_illidan_stormrageAI::ReceiveAIEvent().