CMaNGOS_WoTLK: boss_halion.cpp File Reference
boss_halion.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ruby_sanctum.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_halion_realAI
struct boss_halion_twilightAI
struct npc_halion_controllerAI
struct npc_meteor_strike_initialAI
struct npc_orb_carrierAI
struct spell_leave_twilight_realm_aura
struct spell_clear_debuffs
struct spell_fiery_combustion_aura
struct spell_soul_consumption_aura
Enumerations
enum {
SAY_AGGRO = -1724025 , SAY_SLAY_1 = -1724026 , SOUND_SLAY_2 = 17502 , SAY_DEATH = -1724027 ,
SAY_BERSERK = -1724028 , SAY_FIREBALL = -1724029 , SAY_SPHERES = -1724030 , SAY_PHASE_2 = -1724031 ,
SAY_PHASE_3 = -1724032 , EMOTE_SPHERES = -1724033 , EMOTE_OUT_OF_TWILLIGHT = -1724034 , EMOTE_OUT_OF_PHYSICAL = -1724035 ,
EMOTE_INTO_TWILLIGHT = -1724036 , EMOTE_INTO_PHYSICAL = -1724037 , EMOTE_REGENERATE = -1724038 , SPELL_TWILIGHT_PRECISION = 78243 ,
SPELL_CLEAVE = 74524 , SPELL_TAIL_LASH = 74531 , SPELL_BERSERK = 26662 , SPELL_TWILIGHT_PHASING = 74808 ,
SPELL_SUMMON_PORTAL = 74809 , SPELL_TWILIGHT_DIVISION = 75063 , SPELL_TWILIGHT_MENDING = 75509 , SPELL_TWILIGHT_REALM = 74807 ,
SPELL_LEAVE_TWILIGHT_REALM = 74812 , SPELL_FLAME_BREATH = 74525 , SPELL_METEOR_SUMMON = 74637 , SPELL_FIERY_COMBUSTION = 74562 ,
SPELL_DARK_BREATH = 74806 , SPELL_DUSK_SHROUD = 75476 , SPELL_SOUL_CONSUMPTION = 74792 , SPELL_CORPOREALITY_EVEN = 74826 ,
SPELL_CORPOREALITY_20I = 74827 , SPELL_CORPOREALITY_40I = 74828 , SPELL_CORPOREALITY_60I = 74829 , SPELL_CORPOREALITY_80I = 74830 ,
SPELL_CORPOREALITY_100I = 74831 , SPELL_CORPOREALITY_20D = 74832 , SPELL_CORPOREALITY_40D = 74833 , SPELL_CORPOREALITY_60D = 74834 ,
SPELL_CORPOREALITY_80D = 74835 , SPELL_CORPOREALITY_100D = 74836 , SPELL_METEOR_VISUAL = 74641 , SPELL_METEOR_IMPACT = 74648 ,
SPELL_METEOR_FLAME_MAIN = 74713 , SPELL_METEOR_FLAME = 74718 , SPELL_BIRTH = 40031 , SPELL_TWILIGHT_PULSE = 78861 ,
SPELL_TWILIGHT_CUTTER = 74768 , SPELL_TRACK_ROTATION = 74758 , SPELL_BLAZING_AURA = 75885 , SPELL_AWAKEN_FLAMES = 75889 ,
NPC_LIVING_INFERNO = 40681 , NPC_LIVING_EMBER = 40683 , PHASE_PHISYCAL_REALM = 1 , PHASE_TWILIGHT_REALM = 2 ,
PHASE_BOTH_REALMS = 3 , SEAT_ID_LEFT = 1 , SEAT_ID_RIGHT = 2 , SEAT_ID_BACK = 3 ,
SEAT_ID_FRONT = 4 , CORPOREALITY_NONE = 0 , CORPOREALITY_INCREASE = 1 , CORPOREALITY_DECREASE = 2 ,
MAX_ALLOWED_FLAMES = 10 , MAX_CORPOREALITY_STATES = 11
}
Functions
bool GOUse_go_twilight_portal (Player *pPlayer, GameObject *pGo)
void AddSC_boss_halion ()
Variables
static const uint32 halionCorporeality [MAX_CORPOREALITY_STATES]
static const float aRotationFocusPosition [4] = { 3184.448f, 530.314f, 73.0f, 4.586f }
static const float aOrbCarrierPosition1 [3] = { 3153.75f, 533.1875f, 72.972f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SOUND_SLAY_2
SAY_DEATH
SAY_BERSERK
SAY_FIREBALL
SAY_SPHERES
SAY_PHASE_2
SAY_PHASE_3
EMOTE_SPHERES
EMOTE_OUT_OF_TWILLIGHT
EMOTE_OUT_OF_PHYSICAL
EMOTE_INTO_TWILLIGHT
EMOTE_INTO_PHYSICAL
EMOTE_REGENERATE
SPELL_TWILIGHT_PRECISION
SPELL_CLEAVE
SPELL_TAIL_LASH
SPELL_BERSERK
SPELL_TWILIGHT_PHASING
SPELL_SUMMON_PORTAL
SPELL_TWILIGHT_DIVISION
SPELL_TWILIGHT_MENDING
SPELL_TWILIGHT_REALM
SPELL_LEAVE_TWILIGHT_REALM
SPELL_FLAME_BREATH
SPELL_METEOR_SUMMON
SPELL_FIERY_COMBUSTION
SPELL_DARK_BREATH
SPELL_DUSK_SHROUD
SPELL_SOUL_CONSUMPTION
SPELL_CORPOREALITY_EVEN
SPELL_CORPOREALITY_20I
SPELL_CORPOREALITY_40I
SPELL_CORPOREALITY_60I
SPELL_CORPOREALITY_80I
SPELL_CORPOREALITY_100I
SPELL_CORPOREALITY_20D
SPELL_CORPOREALITY_40D
SPELL_CORPOREALITY_60D
SPELL_CORPOREALITY_80D
SPELL_CORPOREALITY_100D
SPELL_METEOR_VISUAL
SPELL_METEOR_IMPACT
SPELL_METEOR_FLAME_MAIN
SPELL_METEOR_FLAME
SPELL_BIRTH
SPELL_TWILIGHT_PULSE
SPELL_TWILIGHT_CUTTER
SPELL_TRACK_ROTATION
SPELL_BLAZING_AURA
SPELL_AWAKEN_FLAMES
NPC_LIVING_INFERNO
NPC_LIVING_EMBER
PHASE_PHISYCAL_REALM
PHASE_TWILIGHT_REALM
PHASE_BOTH_REALMS
SEAT_ID_LEFT
SEAT_ID_RIGHT
SEAT_ID_BACK
SEAT_ID_FRONT
CORPOREALITY_NONE
CORPOREALITY_INCREASE
CORPOREALITY_DECREASE
MAX_ALLOWED_FLAMES
MAX_CORPOREALITY_STATES
Definition at line 29 of file boss_halion.cpp.
Function Documentation
AddSC_boss_halion()
void AddSC_boss_halion ()
Definition at line 1108 of file boss_halion.cpp.
References Script::GetAI, GOUse_go_twilight_portal(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_twilight_portal()
bool GOUse_go_twilight_portal (Player * pPlayer, GameObject * pGo)
Definition at line 989 of file boss_halion.cpp.
References Unit::CastSpell(), InstanceData::GetData(), WorldObject::GetInstanceData(), Unit::HasAura(), IN_PROGRESS, SPELL_TWILIGHT_REALM, TRIGGERED_OLD_TRIGGERED, and TYPE_HALION.
Referenced by AddSC_boss_halion().
Variable Documentation
aOrbCarrierPosition1
const float aOrbCarrierPosition1[3] = { 3153.75f, 533.1875f, 72.972f } static
Definition at line 155 of file boss_halion.cpp.
Referenced by npc_halion_controllerAI::ReceiveAIEvent().
aRotationFocusPosition
const float aRotationFocusPosition[4] = { 3184.448f, 530.314f, 73.0f, 4.586f } static
Definition at line 154 of file boss_halion.cpp.
Referenced by npc_halion_controllerAI::ReceiveAIEvent().
halionCorporeality
const uint32 halionCorporeality[MAX_CORPOREALITY_STATES] static
Initial value:
=
{
    SPELL_CORPOREALITY_100D,
    SPELL_CORPOREALITY_80D,
    SPELL_CORPOREALITY_60D,
    SPELL_CORPOREALITY_40D,
    SPELL_CORPOREALITY_20D,
    SPELL_CORPOREALITY_EVEN,
    SPELL_CORPOREALITY_20I,
    SPELL_CORPOREALITY_40I,
    SPELL_CORPOREALITY_60I,
    SPELL_CORPOREALITY_80I,
    SPELL_CORPOREALITY_100I
}
Definition at line 138 of file boss_halion.cpp.
Referenced by npc_halion_controllerAI::DoUpdateCorporeality().