CMaNGOS_WoTLK: boss_skadi.cpp File Reference
boss_skadi.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_pinnacle.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct GauntletIntroData
struct boss_skadiAI
struct npc_graufAI
struct spell_launch_harpoon
struct spell_summon_gauntlet_mobs_periodic_aura
struct spell_freezing_cloud_aura
struct spell_poisoned_spear
Enumerations
enum {
SAY_AGGRO = -1575019 , SAY_DRAKEBREATH_1 = -1575020 , SAY_DRAKEBREATH_2 = -1575021 , SAY_DRAKEBREATH_3 = -1575022 ,
SAY_DRAKE_HARPOON_1 = -1575023 , SAY_DRAKE_HARPOON_2 = -1575024 , SAY_KILL_1 = -1575025 , SAY_KILL_2 = -1575026 ,
SAY_KILL_3 = -1575027 , SAY_DEATH = -1575028 , SAY_DRAKE_DEATH = -1575029 , EMOTE_HARPOON_RANGE = -1575030 ,
EMOTE_DEEP_BREATH = -1575041 , SPELL_RIDE_VEHICLE = 61791 , SPELL_FREEZING_CLOUD_LEFT = 47590 , SPELL_FREEZING_CLOUD_RIGHT = 47592 ,
SPELL_SKADI_TELEPORT = 61790 , SPELL_SUMMON_GAUNTLET_MOBS = 48630 , SPELL_SUMMON_GAUNTLET_MOBS_H = 59275 , SPELL_LAUNCH_HARPOON = 48642 ,
SPELL_CLOUD_AURA_LEFT = 47574 , SPELL_CLOUD_AURA_RIGHT = 47594 , SPELL_CLOUD_AURA_DAMAGE = 47579 , SPELL_CRUSH = 50234 ,
SPELL_CRUSH_H = 59330 , SPELL_WHIRLWIND = 50228 , SPELL_WHIRLWIND_H = 59322 , SPELL_POISONED_SPEAR = 50255 ,
SPELL_POISONED_SPEAR_H = 59331 , MAX_INTRO_MOBS = 13 , PHASE_GAUNTLET = 1 , PHASE_NORMAL_COMBAT = 2
}
enum SkadiActions {
SKADI_ACTION_CRUSH , SKADI_ACTION_WHIRLWIND , SKADI_ACTION_POISONED_SPEAR , SKADI_ACTION_MAX ,
SKADI_ACTION_MOUNT
}
Functions
bool AreaTrigger_at_skadi (Player *pPlayer, AreaTriggerEntry const *)
void AddSC_boss_skadi ()
Variables
static const GauntletIntroData aSkadiIntroData [MAX_INTRO_MOBS]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_DRAKEBREATH_1
SAY_DRAKEBREATH_2
SAY_DRAKEBREATH_3
SAY_DRAKE_HARPOON_1
SAY_DRAKE_HARPOON_2
SAY_KILL_1
SAY_KILL_2
SAY_KILL_3
SAY_DEATH
SAY_DRAKE_DEATH
EMOTE_HARPOON_RANGE
EMOTE_DEEP_BREATH
SPELL_RIDE_VEHICLE
SPELL_FREEZING_CLOUD_LEFT
SPELL_FREEZING_CLOUD_RIGHT
SPELL_SKADI_TELEPORT
SPELL_SUMMON_GAUNTLET_MOBS
SPELL_SUMMON_GAUNTLET_MOBS_H
SPELL_LAUNCH_HARPOON
SPELL_CLOUD_AURA_LEFT
SPELL_CLOUD_AURA_RIGHT
SPELL_CLOUD_AURA_DAMAGE
SPELL_CRUSH
SPELL_CRUSH_H
SPELL_WHIRLWIND
SPELL_WHIRLWIND_H
SPELL_POISONED_SPEAR
SPELL_POISONED_SPEAR_H
MAX_INTRO_MOBS
PHASE_GAUNTLET
PHASE_NORMAL_COMBAT
Definition at line 30 of file boss_skadi.cpp.
SkadiActions
enum SkadiActions
Enumerator
SKADI_ACTION_CRUSH
SKADI_ACTION_WHIRLWIND
SKADI_ACTION_POISONED_SPEAR
SKADI_ACTION_MAX
SKADI_ACTION_MOUNT
Definition at line 96 of file boss_skadi.cpp.
Function Documentation
AddSC_boss_skadi()
void AddSC_boss_skadi ()
Definition at line 566 of file boss_skadi.cpp.
References AreaTrigger_at_skadi(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_skadi()
bool AreaTrigger_at_skadi (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 447 of file boss_skadi.cpp.
References AI_EVENT_CUSTOM_B, WorldObject::GetInstanceData(), Player::IsGameMaster(), NOT_STARTED, NPC_SKADI, SPECIAL, and TYPE_SKADI.
Referenced by AddSC_boss_skadi().
Variable Documentation
aSkadiIntroData
const GauntletIntroData aSkadiIntroData[MAX_INTRO_MOBS] static
Initial value:
=
{
    {NPC_YMIRJAR_WITCH_DOCTOR, 1},
    {NPC_YMIRJAR_HARPOONER, 1},
    {NPC_YMIRJAR_HARPOONER, 2},
    {NPC_YMIRJAR_WARRIOR, 1},
    {NPC_YMIRJAR_WARRIOR, 2},
    {NPC_YMIRJAR_WARRIOR, 3},
    {NPC_YMIRJAR_WARRIOR, 4},
    {NPC_YMIRJAR_WARRIOR, 5},
    {NPC_YMIRJAR_WARRIOR, 6},
    {NPC_YMIRJAR_WARRIOR, 7},
    {NPC_YMIRJAR_WARRIOR, 8},
    {NPC_YMIRJAR_WARRIOR, 9},
    {NPC_YMIRJAR_WARRIOR, 10},
}
Definition at line 79 of file boss_skadi.cpp.
Referenced by boss_skadiAI::DoPrepareForGauntlet().