CMaNGOS_WoTLK: boss_shade_of_akama.cpp File Reference
boss_shade_of_akama.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "black_temple.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct Location
struct npc_akamaAI
struct boss_shade_of_akamaAI
struct mob_ashtongue_channelerAI
struct mob_ashtongue_sorcererAI
struct npc_creature_generatorAI
Enumerations
enum {
SAY_DEATH = -1564013 , SAY_LOW_HEALTH = -1564014 , SAY_FREE_1 = -1564130 , SAY_FREE_2 = -1564135 ,
SAY_FREE_3 = -1564015 , SAY_BROKEN_FREE_1 = -1564016 , SAY_BROKEN_FREE_2 = -1564017 , BROKEN_FACTION_CHANGE = 1820 ,
GOSSIP_ITEM_START_ENCOUNTER = -3564000 , TEXT_ID_AKAMA = 10866 , SPELL_STEALTH = 34189 , SPELL_DESTRUCTIVE_POISON = 40874 ,
SPELL_CHAIN_LIGHTNING = 39945 , SPELL_AKAMA_SOUL_CHANNEL = 40447 , SPELL_AKAMA_SOUL_RETRIEVE = 40902 , SPELL_AKAMA_SOUL_EXPEL_CHANNEL = 40927 ,
SPELL_ASHTONGUE_WAVE_B = 42035 , SPELL_ASHTONGUE_WAVE_A = 42073 , SPELL_SUMMON_DEFENDER = 40474 , SPELL_SUMMON_SORCERER = 40476 ,
SPELL_THREAT = 41602 , SPELL_FIXATE = 40607 , SPELL_SHADE_SOUL_CHANNEL = 40401 , SPELL_SUMMON_SHADE_TRIGGER = 40955 ,
NPC_ASH_SORCERER = 23215 , NPC_ASH_DEFENDER = 23216 , NPC_ASH_ELEMENTAL = 23523 , NPC_ASH_ROGUE = 23318 ,
NPC_ASH_SPIRITBIND = 23524 , NPC_ASH_BROKEN = 23319 , POINT_DESTINATION = 1 , PHASE_CHANNEL = 1 ,
PHASE_COMBAT = 2 , PHASE_EPILOGUE = 3 , MAX_CHANNELERS = 6 , FACTION_AKAMA_FIGHT = 1868
}
enum AkamaActions {
AKAMA_ACTION_HEAL , AKAMA_ACTION_CHAIN_LIGHTNING , AKAMA_ACTION_MAX , AKAMA_SUMMON_ILLIDARI ,
AKAMA_OUTRO_DELAY , AKAMA_OUTRO_ACTIONS , AKAMA_ACTION_LOW_HEALTH , AKAMA_ACTION_DESTRUCTIVE_POISON ,
AKAMA_ACTION_CHAIN_LIGHTNING , AKAMA_ACTION_MAX
}
Functions
bool GossipHello_npc_akama (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_akama (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_boss_shade_of_akama ()
Variables
static const uint32 auiRandSpawnEntry []
static const DialogueEntry aOutroDialogue []
static const Location akamaWaypoints []
static const Location brokenSpawnLocations []
static const Location brokenDestinationLocations []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DEATH
SAY_LOW_HEALTH
SAY_FREE_1
SAY_FREE_2
SAY_FREE_3
SAY_BROKEN_FREE_1
SAY_BROKEN_FREE_2
BROKEN_FACTION_CHANGE
GOSSIP_ITEM_START_ENCOUNTER
TEXT_ID_AKAMA
SPELL_STEALTH
SPELL_DESTRUCTIVE_POISON
SPELL_CHAIN_LIGHTNING
SPELL_AKAMA_SOUL_CHANNEL
SPELL_AKAMA_SOUL_RETRIEVE
SPELL_AKAMA_SOUL_EXPEL_CHANNEL
SPELL_ASHTONGUE_WAVE_B
SPELL_ASHTONGUE_WAVE_A
SPELL_SUMMON_DEFENDER
SPELL_SUMMON_SORCERER
SPELL_THREAT
SPELL_FIXATE
SPELL_SHADE_SOUL_CHANNEL
SPELL_SUMMON_SHADE_TRIGGER
NPC_ASH_SORCERER
NPC_ASH_DEFENDER
NPC_ASH_ELEMENTAL
NPC_ASH_ROGUE
NPC_ASH_SPIRITBIND
NPC_ASH_BROKEN
POINT_DESTINATION
PHASE_CHANNEL
PHASE_COMBAT
PHASE_EPILOGUE
MAX_CHANNELERS
FACTION_AKAMA_FIGHT
Definition at line 28 of file boss_shade_of_akama.cpp.
AkamaActions
enum AkamaActions
Enumerator
AKAMA_ACTION_HEAL
AKAMA_ACTION_CHAIN_LIGHTNING
AKAMA_ACTION_MAX
AKAMA_SUMMON_ILLIDARI
AKAMA_OUTRO_DELAY
AKAMA_OUTRO_ACTIONS
AKAMA_ACTION_LOW_HEALTH
AKAMA_ACTION_DESTRUCTIVE_POISON
AKAMA_ACTION_CHAIN_LIGHTNING
AKAMA_ACTION_MAX
Definition at line 160 of file boss_shade_of_akama.cpp.
Function Documentation
AddSC_boss_shade_of_akama()
void AddSC_boss_shade_of_akama ()
Definition at line 783 of file boss_shade_of_akama.cpp.
References Script::GetAI, GossipHello_npc_akama(), GossipSelect_npc_akama(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_akama()
bool GossipHello_npc_akama (Player * pPlayer, Creature * pCreature)
Definition at line 461 of file boss_shade_of_akama.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_START_ENCOUNTER, GOSSIP_SENDER_MAIN, TEXT_ID_AKAMA, and TYPE_SHADE.
Referenced by AddSC_boss_shade_of_akama().
GossipSelect_npc_akama()
bool GossipSelect_npc_akama (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 473 of file boss_shade_of_akama.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_boss_shade_of_akama().
Variable Documentation
akamaWaypoints
const Location akamaWaypoints[] static
Initial value:
=
{
    { 517.4877f,   400.7993f,   112.7837f },
    { 512.4877f,   400.8283f,   112.7837f },
    { 469.597443f, 402.264404f, 118.537f }
}
Definition at line 116 of file boss_shade_of_akama.cpp.
Referenced by npc_akamaAI::DoStartEvent(), npc_akamaAI::ReceiveAIEvent(), and boss_shade_of_akamaAI::SpellHit().
aOutroDialogue
const DialogueEntry aOutroDialogue[] static
Initial value:
=
{
    { PHASE_CHANNEL,             0,                  3500 },
    { SPELL_AKAMA_SOUL_CHANNEL,  0,                  600000 },
    { SPELL_AKAMA_SOUL_RETRIEVE, 0,                  15500 },
    { SAY_FREE_1,                NPC_AKAMA_SHADE,    10000 },
    { SAY_FREE_2,                NPC_AKAMA_SHADE,    10000 },
    { SAY_FREE_3,                NPC_AKAMA_SHADE,    15000 },
    { SAY_BROKEN_FREE_1,         0,                  5000 },
    { SAY_BROKEN_FREE_2,         0,                  0 },
    { 0, 0, 0 },
}
Definition at line 97 of file boss_shade_of_akama.cpp.
auiRandSpawnEntry
const uint32 auiRandSpawnEntry[] static
Initial value:
=
{
    NPC_ASH_ELEMENTAL,
    NPC_ASH_ROGUE,
    NPC_ASH_SPIRITBIND
}
Definition at line 90 of file boss_shade_of_akama.cpp.
brokenDestinationLocations
const Location brokenDestinationLocations[] static
Initial value:
=
{
    {476.2499f, 369.0865f, 112.7838f},
    {473.3224f, 368.4310f, 112.7838f},
    {479.1774f, 369.7420f, 112.7838f},
    {491.9286f, 383.0433f, 112.7838f},
    {490.0695f, 380.6888f, 112.7838f},
    {493.1895f, 385.7655f, 112.7838f},
    {488.3535f, 395.3652f, 112.7838f},
    {487.5005f, 392.4891f, 112.7838f},
    {488.5529f, 398.3586f, 112.7838f},
    {491.8618f, 403.2035f, 112.7838f},
    {491.7784f, 400.2046f, 112.7838f},
    {491.9451f, 406.2023f, 112.7838f},
    {479.1884f, 434.8635f, 112.7839f},
    {478.1014f, 433.3450f, 112.7839f},
}
Definition at line 142 of file boss_shade_of_akama.cpp.
Referenced by npc_akamaAI::DoSummonBrokenAshtongue().
brokenSpawnLocations
const Location brokenSpawnLocations[] static
Initial value:
=
{
    {501.5699f, 337.8271f, 112.8673f},
    {499.0937f, 337.9894f, 112.8673f},
    {496.8722f, 338.0152f, 112.8673f},
    {532.5723f, 344.6454f, 112.8671f},
    {532.5565f, 346.8792f, 112.8671f},
    {532.5491f, 348.6840f, 112.8671f},
    {521.8465f, 393.1343f, 112.8671f},
    {521.9014f, 395.6381f, 112.8671f},
    {522.2610f, 397.7423f, 112.8671f},
    {522.2963f, 402.3578f, 112.8671f},
    {521.9184f, 404.6848f, 112.8671f},
    {522.4290f, 406.5160f, 112.8671f},
    {495.9472f, 463.3625f, 112.8673f},
    {498.3421f, 463.8384f, 112.8673f},
}
Definition at line 123 of file boss_shade_of_akama.cpp.
Referenced by npc_akamaAI::DoSummonBrokenAshtongue().