CMaNGOS_WoTLK: boss_anubarak_trial.cpp File Reference
boss_anubarak_trial.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_crusader.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_anubarak_trialAI
struct npc_anubarak_trial_spikeAI
struct npc_anubarak_trial_frostsphereAI
struct npc_nerubian_burrowerAI
struct spell_burrower_submerge
struct spell_leeching_swarm_aura
struct spell_pursuing_spikes
Enumerations
enum {
SAY_INTRO = -1649038 , SAY_AGGRO = -1649064 , SAY_SLAY_1 = -1649065 , SAY_SLAY_2 = -1649066 ,
SAY_DEATH = -1649067 , SAY_BERSERK = -1649068 , SAY_SUBMERGE = -1649069 , SAY_LEECHING_SWARM = -1649070 ,
EMOTE_BURROW = -1649071 , EMOTE_PURSUE = -1649072 , EMOTE_EMERGE = -1649073 , EMOTE_LEECHING_SWARM = -1649074 ,
SPELL_FREEZING_SLASH = 66012 , SPELL_PENETRATING_COLD = 66013 , SPELL_SUMMON_NERUBIAN_BURROWER = 66332 , SPELL_SUMMON_SCARAB = 66339 ,
SPELL_SUBMERGE = 65981 , SPELL_EMERGE = 65982 , SPELL_TELEPORT_TO_SPIKE = 66170 , SPELL_CLEAR_ALL_DEBUFFS = 34098 ,
SPELL_SUMMON_SPIKES = 66169 , SPELL_LEECHING_SWARM = 66118 , SPELL_BERSERK = 26662 , SPELL_SCARAB_ACHIEV_10 = 68186 ,
SPELL_SCARAB_ACHIEV_25 = 68515 , SPELL_PURSUING_SPIKES_FAIL = 66181 , SPELL_PURSUING_SPIKES_DUMMY = 67470 , SPELL_PURSUING_SPIKES_SPEED1 = 65920 ,
SPELL_PURSUING_SPIKES_GROUND = 65921 , SPELL_PURSUING_SPIKES_SPEED2 = 65922 , SPELL_PURSUING_SPIKES_SPEED3 = 65923 , SPELL_MARK = 67574 ,
SPELL_PERMAFROST_VISUAL = 65882 , SPELL_PERMAFROST_DUMMY = 65872 , SPELL_PERMAFROST_TRANSFORM = 66185 , SPELL_PERMAFROST_SLOW = 66193 ,
SPELL_FROSTSPHERE_VISUAL = 67539 , SPELL_SPIDER_FRENZY = 66128 , SPELL_EXPOSE_WEAKNESS = 67720 , SPELL_RECENTLY_AWAKENED = 66311 ,
SPELL_SHADOW_STRIKE = 66134 , SPELL_BURROWER_SUBMERGE = 67322 , SPELL_SUBMERGE_BURROWER_STUN = 68394 , NPC_FROSTSPHERE = 34606 ,
NPC_ANUBARAK_SPIKE = 34660 , MAX_FROSTSPHERES = 6 , MAX_BURROWS = 4
}
enum Phases {
PHASE_GROUND = 0 , PHASE_UNDERGROUND = 1 , PHASE_LEECHING_SWARM = 2 , PHASE_SUBMERGING = 3 ,
PHASE_IDLE = 0 , PHASE_SHIELDED = 1 , PHASE_WAITING = 2 , PHASE_NORMAL = 3 ,
PHASE_SKELETAL = 0 , PHASE_TAKE_FLESH = 1 , PHASE_FLESH = 2 , PHASE_RETURN_FLESH = 3 ,
PHASE_SKELETAL_END = 4 , PHASE_EMERGING = 0 , PHASE_NORMAL = 1 , PHASE_SPOUT = 2 ,
PHASE_SUBMERGED = 3 , PHASE_NORMAL = 1 , PHASE_SPLIT = 2 , PHASE_VOID = 3
}
enum PursuingSpikesPhases { PHASE_NO_MOVEMENT = 0 , PHASE_IMPALE_NORMAL = 1 , PHASE_IMPALE_MIDDLE = 2 , PHASE_IMPALE_FAST = 3 }
enum NerubianBurrowerActions { BURROWER_SUBMERGE , BURROWER_SHADOW_STRIKE , BURROWER_ACTION_MAX , BURROWER_EMERGE }
Functions
bool EffectDummyCreature_spell_dummy_permafrost (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_anubarak_trial ()
Variables
static const float aFrostSphereSpawnPositions [MAX_FROSTSPHERES][3]
static const float aBurrowSpawnPositions [MAX_BURROWS][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SAY_BERSERK
SAY_SUBMERGE
SAY_LEECHING_SWARM
EMOTE_BURROW
EMOTE_PURSUE
EMOTE_EMERGE
EMOTE_LEECHING_SWARM
SPELL_FREEZING_SLASH
SPELL_PENETRATING_COLD
SPELL_SUMMON_NERUBIAN_BURROWER
SPELL_SUMMON_SCARAB
SPELL_SUBMERGE
SPELL_EMERGE
SPELL_TELEPORT_TO_SPIKE
SPELL_CLEAR_ALL_DEBUFFS
SPELL_SUMMON_SPIKES
SPELL_LEECHING_SWARM
SPELL_BERSERK
SPELL_SCARAB_ACHIEV_10
SPELL_SCARAB_ACHIEV_25
SPELL_PURSUING_SPIKES_FAIL
SPELL_PURSUING_SPIKES_DUMMY
SPELL_PURSUING_SPIKES_SPEED1
SPELL_PURSUING_SPIKES_GROUND
SPELL_PURSUING_SPIKES_SPEED2
SPELL_PURSUING_SPIKES_SPEED3
SPELL_MARK
SPELL_PERMAFROST_VISUAL
SPELL_PERMAFROST_DUMMY
SPELL_PERMAFROST_TRANSFORM
SPELL_PERMAFROST_SLOW
SPELL_FROSTSPHERE_VISUAL
SPELL_SPIDER_FRENZY
SPELL_EXPOSE_WEAKNESS
SPELL_RECENTLY_AWAKENED
SPELL_SHADOW_STRIKE
SPELL_BURROWER_SUBMERGE
SPELL_SUBMERGE_BURROWER_STUN
NPC_FROSTSPHERE
NPC_ANUBARAK_SPIKE
MAX_FROSTSPHERES
MAX_BURROWS
Definition at line 30 of file boss_anubarak_trial.cpp.
NerubianBurrowerActions
enum NerubianBurrowerActions
Enumerator
BURROWER_SUBMERGE
BURROWER_SHADOW_STRIKE
BURROWER_ACTION_MAX
BURROWER_EMERGE
Definition at line 622 of file boss_anubarak_trial.cpp.
Phases
enum Phases
Enumerator
PHASE_GROUND
PHASE_UNDERGROUND
PHASE_LEECHING_SWARM
PHASE_SUBMERGING
PHASE_IDLE
PHASE_SHIELDED
PHASE_WAITING
PHASE_NORMAL
PHASE_SKELETAL
PHASE_TAKE_FLESH
PHASE_FLESH
PHASE_RETURN_FLESH
PHASE_SKELETAL_END
PHASE_EMERGING
PHASE_NORMAL
PHASE_SPOUT
PHASE_SUBMERGED
PHASE_NORMAL
PHASE_SPLIT
PHASE_VOID
Definition at line 94 of file boss_anubarak_trial.cpp.
PursuingSpikesPhases
enum PursuingSpikesPhases
Enumerator
PHASE_NO_MOVEMENT
PHASE_IMPALE_NORMAL
PHASE_IMPALE_MIDDLE
PHASE_IMPALE_FAST
Definition at line 102 of file boss_anubarak_trial.cpp.
Function Documentation
AddSC_boss_anubarak_trial()
void AddSC_boss_anubarak_trial ()
Definition at line 765 of file boss_anubarak_trial.cpp.
References EffectDummyCreature_spell_dummy_permafrost(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_dummy_permafrost()
bool EffectDummyCreature_spell_dummy_permafrost (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 530 of file boss_anubarak_trial.cpp.
References Creature::AI(), EFFECT_INDEX_0, and SPELL_PERMAFROST_DUMMY.
Referenced by AddSC_boss_anubarak_trial().
Variable Documentation
aBurrowSpawnPositions
const float aBurrowSpawnPositions[MAX_BURROWS][4] static
Initial value:
=
{
    { 735.4028f, 75.35764f, 142.2023f, 2.094395f  },
    { 692.9202f, 184.809f,  142.2026f, 5.358161f  },
    { 688.2066f, 102.8472f, 142.2023f, 0.6457718f },
    { 740.5452f, 189.1129f, 142.1972f, 3.752458f  }
}
Definition at line 120 of file boss_anubarak_trial.cpp.
Referenced by boss_anubarak_trialAI::Aggro().
aFrostSphereSpawnPositions
const float aFrostSphereSpawnPositions[MAX_FROSTSPHERES][3] static
Initial value:
=
{
    { 701.4270f, 126.4739f, 158.0205f },
    { 712.5711f, 160.9948f, 158.4367f },
    { 736.0243f, 113.4201f, 158.0225f },
    { 747.9201f, 155.0920f, 158.0613f },
    { 769.6285f, 121.1024f, 158.0504f },
    { 779.8038f, 150.658f,  158.1426f }
}
Definition at line 110 of file boss_anubarak_trial.cpp.
Referenced by boss_anubarak_trialAI::Aggro(), and boss_anubarak_trialAI::DoRefreshSpheres().