CMaNGOS_WoTLK: boss_hummel.cpp File Reference
boss_hummel.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "shadowfang_keep.h"
Data Structures
struct boss_apothecary_hummelAI
struct npc_valentine_boss_managerAI
struct spell_lingering_fumes_targetting
struct spell_valentine_boss_validate_area
struct spell_valentine_trigger_vial_a
struct spell_valentine_trigger_vial_b
struct spell_alluring_perfume_spill_aura
struct spell_irresistible_cologne_spill_aura
Enumerations
enum {
SAY_INTRO_1 = -1033020 , SAY_INTRO_2 = -1033021 , SAY_INTRO_3 = -1033022 , SAY_CALL_BAXTER = -1033023 ,
SAY_CALL_FRYE = -1033024 , SAY_HUMMEL_DEATH = -1033025 , SPELL_ALLURING_PERFUME = 68589 , SPELL_ALLURING_PERFUME_SPRAY = 68607 ,
SPELL_CHAIN_REACTION = 68821 , SPELL_SUMMON_TABLE = 69218 , SPELL_PERMANENT_FEIGN_DEATH = 29266 , SPELL_SUMMON_VALENTINE_ADD = 68610 ,
QUEST_BEEN_SERVED = 14488 , FACTION_HOSTILE = 14
}
enum HummelActions { HUMMEL_ACTION_PERFUME_SPRAY , HUMMEL_ACTION_CHAIN_REACTION , HUMMEL_ACTION_SUMMON_ADD , HUMMEL_ACTION_MAX }
Functions
bool QuestRewarded_boss_apothecary_hummel (Player *player, Creature *creature, Quest const *quest)
void AddSC_boss_hummel ()
Variables
static const DialogueEntry aIntroDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_CALL_BAXTER
SAY_CALL_FRYE
SAY_HUMMEL_DEATH
SPELL_ALLURING_PERFUME
SPELL_ALLURING_PERFUME_SPRAY
SPELL_CHAIN_REACTION
SPELL_SUMMON_TABLE
SPELL_PERMANENT_FEIGN_DEATH
SPELL_SUMMON_VALENTINE_ADD
QUEST_BEEN_SERVED
FACTION_HOSTILE
Definition at line 30 of file boss_hummel.cpp.
HummelActions
enum HummelActions
Enumerator
HUMMEL_ACTION_PERFUME_SPRAY
HUMMEL_ACTION_CHAIN_REACTION
HUMMEL_ACTION_SUMMON_ADD
HUMMEL_ACTION_MAX
Definition at line 51 of file boss_hummel.cpp.
Function Documentation
AddSC_boss_hummel()
void AddSC_boss_hummel ()
Definition at line 426 of file boss_hummel.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedNPC, QuestRewarded_boss_apothecary_hummel(), and Script::RegisterSelf().
Referenced by AddScripts().
QuestRewarded_boss_apothecary_hummel()
bool QuestRewarded_boss_apothecary_hummel (Player * player, Creature * creature, Quest const * quest)
Definition at line 142 of file boss_hummel.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, WorldObject::GetInstanceData(), Quest::GetQuestId(), NPC_VALENTINE_BOSS_MGR, QUEST_BEEN_SERVED, and UnitAI::SendAIEvent().
Referenced by AddSC_boss_hummel().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {QUEST_BEEN_SERVED, 0,          1000},
    {SAY_INTRO_1,       NPC_HUMMEL, 4000},
    {SAY_INTRO_2,       NPC_HUMMEL, 4000},
    {SAY_INTRO_3,       NPC_HUMMEL, 3000},
    {NPC_HUMMEL,        0,          8000},
    {NPC_BAXTER,        0,          8000},
    {NPC_FRYE,          0,          0},
    {0, 0, 0},
}
Definition at line 152 of file boss_hummel.cpp.