CMaNGOS_WoTLK: boss_terokk.cpp File Reference
boss_terokk.cpp File Reference
#include <utility>
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/scripts/outland/world_outland.h"
Data Structures
struct boss_terokkAI
struct TerokkAncientFlames
Enumerations
enum {
SAY_SPAWN = -1001278 , SAY_CHOSEN_ONE = -1001279 , SAY_DIVINE_SHIELD = -1001280 , SAY_ENRAGE = -1001281 ,
SAY_SPAWN_ACE = -1001282 , SAY_FLAMES = -1001283 , SAY_TEROKK_DOWN = -1001284 , NPC_TEROKK = 21838 ,
NPC_ACE = 23377 , NPC_INVISIBLE_STALKER = 15214 , SPELL_RED_BEAM = 24240 , SPELL_SHADOWFORM_TEROKK = 41408 ,
SPELL_SHADOW_BOLT_VOLLEY = 40721 , SPELL_CLEAVE = 15284 , SPELL_DIVINE_SHIELD = 40733 , SPELL_ENRAGE = 28747 ,
SPELL_CHOSEN_ONE = 40726 , SPELL_WILL_OF_THE_ARAKKOA_GOD = 40722 , SPELL_SKYGUARD_FLARE = 40655 , SPELL_ANCIENT_FLAMES = 40657 ,
SPELL_SKYGUARD_FLARE_VISUAL = 40656 , PATH_ID_START = 0 , PATH_ID_CYCLE = 1 , PATH_ID_END = 2 ,
POINT_FINAL_START = 2 , POINT_FINAL_END = 4 , COUNT_ACE = 3 , MOUNT_OFFSET = 21155 ,
MOUNT_COUNT = 4
}
enum TerokkActions {
TEROKK_COMBAT_ACTION_SPAWN_ACE , TEROKK_COMBAT_ACTION_PHASE_2 , TEROKK_COMBAT_ACTION_DIVINE_SHIELD , TEROKK_COMBAT_ACTION_SHADOW_BOLT_VOLLEY ,
TEROKK_COMBAT_ACTION_CHOSEN_ONE , TEROKK_COMBAT_ACTION_CLEAVE , TEROKK_COMBAT_ACTION_MAX , TEROKK_ACTION_SPAWN = TEROKK_COMBAT_ACTION_MAX ,
TEROKK_ACTION_SAY , TEROKK_ACTION_ATTACK , TEROKK_ACTION_ACE_CAST
}
Functions
bool ProcessEventId_event_summon_terokk (uint32, Object *source, Object *, bool)
void AddSC_boss_terokk ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SPAWN
SAY_CHOSEN_ONE
SAY_DIVINE_SHIELD
SAY_ENRAGE
SAY_SPAWN_ACE
SAY_FLAMES
SAY_TEROKK_DOWN
NPC_TEROKK
NPC_ACE
NPC_INVISIBLE_STALKER
SPELL_RED_BEAM
SPELL_SHADOWFORM_TEROKK
SPELL_SHADOW_BOLT_VOLLEY
SPELL_CLEAVE
SPELL_DIVINE_SHIELD
SPELL_ENRAGE
SPELL_CHOSEN_ONE
SPELL_WILL_OF_THE_ARAKKOA_GOD
SPELL_SKYGUARD_FLARE
SPELL_ANCIENT_FLAMES
SPELL_SKYGUARD_FLARE_VISUAL
PATH_ID_START
PATH_ID_CYCLE
PATH_ID_END
POINT_FINAL_START
POINT_FINAL_END
COUNT_ACE
MOUNT_OFFSET
MOUNT_COUNT
Definition at line 29 of file boss_terokk.cpp.
TerokkActions
enum TerokkActions
Enumerator
TEROKK_COMBAT_ACTION_SPAWN_ACE
TEROKK_COMBAT_ACTION_PHASE_2
TEROKK_COMBAT_ACTION_DIVINE_SHIELD
TEROKK_COMBAT_ACTION_SHADOW_BOLT_VOLLEY
TEROKK_COMBAT_ACTION_CHOSEN_ONE
TEROKK_COMBAT_ACTION_CLEAVE
TEROKK_COMBAT_ACTION_MAX
TEROKK_ACTION_SPAWN
TEROKK_ACTION_SAY
TEROKK_ACTION_ATTACK
TEROKK_ACTION_ACE_CAST
Definition at line 75 of file boss_terokk.cpp.
Function Documentation
AddSC_boss_terokk()
void AddSC_boss_terokk ()
Definition at line 314 of file boss_terokk.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_summon_terokk(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_summon_terokk()
bool ProcessEventId_event_summon_terokk (uint32 , Object * source, Object * , bool)
Definition at line 294 of file boss_terokk.cpp.
References WorldObject::GetMap(), NPC_TEROKK, Map::SpawnedCountForEntry(), WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN.
Referenced by AddSC_boss_terokk().