CMaNGOS_WoTLK: boss_festergut.cpp File Reference
boss_festergut.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_festergutAI
struct npc_orange_gas_stalkerAI
Enumerations
enum {
SPELL_BERSERK = 47008 , SPELL_REMOVE_INOCULENT = 69298 , SPELL_GASTRIC_BLOAT = 72214 , SPELL_GAS_SPORE = 69278 ,
SPELL_VILE_GAS = 71307 , SPELL_INHALE_BLIGHT = 69165 , SPELL_INHALED_BLIGHT_10 = 69166 , SPELL_INHALED_BLIGHT_25 = 71912 ,
SPELL_PUNGENT_BLIGHT = 69195 , SPELL_GASEOUS_BLIGHT_INIT = 69125 , SPELL_GASEOUS_BLIGHT_1 = 69157 , SPELL_GASEOUS_BLIGHT_2 = 69162 ,
SPELL_GASEOUS_BLIGHT_3 = 69164 , SPELL_GASEOUS_BLIGHT_DUMMY1 = 69126 , SPELL_GASEOUS_BLIGHT_DUMMY2 = 69152 , SPELL_GASEOUS_BLIGHT_DUMMY3 = 69154 ,
SPELL_MALLEABLE_GOO_SUMMON = 72299 , SPELL_MALLEABLE_GOO = 72296 , NPC_MALLEABLE_OOZE_STALKER = 38556 , SAY_AGGRO = -1631082 ,
SAY_BLIGHT = -1631083 , SAY_BLIGHT_ROTFACE_DEAD = -1631200 , SAY_PUNGUENT_BLIGHT = -1631085 , SAY_SLAY_1 = -1631087 ,
SAY_SLAY_2 = -1631088 , SAY_BERSERK = -1631089 , SAY_DEATH = -1631090 , SAY_PUTRICIDE_AGGRO = -1631080 ,
EMOTE_SPORES = -1631201
}
Functions
UnitAI * GetAI_boss_festergut (Creature *pCreature)
bool EffectScriptEffectCreature_spell_inhale_blight (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_orange_gas_stalker (Creature *pCreature)
void AddSC_boss_festergut ()
Variables
static const float afBalconyLocation [3] = {4324.82f, 3166.03f, 389.3831f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_BERSERK
SPELL_REMOVE_INOCULENT
SPELL_GASTRIC_BLOAT
SPELL_GAS_SPORE
SPELL_VILE_GAS
SPELL_INHALE_BLIGHT
SPELL_INHALED_BLIGHT_10
SPELL_INHALED_BLIGHT_25
SPELL_PUNGENT_BLIGHT
SPELL_GASEOUS_BLIGHT_INIT
SPELL_GASEOUS_BLIGHT_1
SPELL_GASEOUS_BLIGHT_2
SPELL_GASEOUS_BLIGHT_3
SPELL_GASEOUS_BLIGHT_DUMMY1
SPELL_GASEOUS_BLIGHT_DUMMY2
SPELL_GASEOUS_BLIGHT_DUMMY3
SPELL_MALLEABLE_GOO_SUMMON
SPELL_MALLEABLE_GOO
NPC_MALLEABLE_OOZE_STALKER
SAY_AGGRO
SAY_BLIGHT
SAY_BLIGHT_ROTFACE_DEAD
SAY_PUNGUENT_BLIGHT
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
SAY_PUTRICIDE_AGGRO
EMOTE_SPORES
Definition at line 28 of file boss_festergut.cpp.
Function Documentation
AddSC_boss_festergut()
void AddSC_boss_festergut ()
Definition at line 360 of file boss_festergut.cpp.
References EffectScriptEffectCreature_spell_inhale_blight(), Script::GetAI, GetAI_boss_festergut(), GetAI_npc_orange_gas_stalker(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectScriptEffectCreature_spell_inhale_blight()
bool EffectScriptEffectCreature_spell_inhale_blight (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 309 of file boss_festergut.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::HasAura(), NPC_FESTERGUT, NPC_GAS_STALKER, Unit::RemoveAllAurasOnEvade(), SPELL_GASEOUS_BLIGHT_1, SPELL_GASEOUS_BLIGHT_2, SPELL_GASEOUS_BLIGHT_3, SPELL_INHALE_BLIGHT, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_festergut().
GetAI_boss_festergut()
UnitAI* GetAI_boss_festergut (Creature * pCreature)
Definition at line 304 of file boss_festergut.cpp.
Referenced by AddSC_boss_festergut().
GetAI_npc_orange_gas_stalker()
UnitAI* GetAI_npc_orange_gas_stalker (Creature * pCreature)
Definition at line 355 of file boss_festergut.cpp.
Referenced by AddSC_boss_festergut().
Variable Documentation
afBalconyLocation
const float afBalconyLocation[3] = {4324.82f, 3166.03f, 389.3831f} static
Definition at line 83 of file boss_festergut.cpp.
Referenced by boss_festergutAI::Aggro().