CMaNGOS_WoTLK: boss_grand_champions.cpp File Reference
boss_grand_champions.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_champion.h"
#include "Maps/TransportSystem.h"
Data Structures
struct trial_companion_commonAI
struct boss_champion_warriorAI
struct boss_champion_mageAI
struct boss_champion_shamanAI
struct boss_champion_hunterAI
struct boss_champion_rogueAI
struct npc_trial_grand_championAI
struct npc_champion_mountAI
Enumerations
enum {
SPELL_DEFEND_DUMMY = 64101 , SPELL_SHIELD_BREAKER = 68504 , SPELL_CHARGE = 68301 , SPELL_CHARGE_VEHICLE = 68307 ,
SPELL_FULL_HEAL = 43979 , SPELL_RIDE_ARGENT_VEHICLE = 69692
}
enum { SPELL_INTERCEPT = 67540 , SPELL_BLADESTORM = 67541 , SPELL_MORTAL_STRIKE = 67542 , SPELL_ROLLING_THROW = 67546 }
enum { SPELL_FIREBALL = 66042 , SPELL_POLYMORPH = 66043 , SPELL_BLAST_WAVE = 66044 , SPELL_HASTE = 66045 }
enum { SPELL_HEALING_WAVE = 67528 , SPELL_CHAIN_LIGHTNING = 67529 , SPELL_EARTH_SHIELD = 67530 , SPELL_HEX_OF_MENDING = 67534 }
enum {
SPELL_DISENGAGE = 68340 , SPELL_LIGHTNING_ARROWS = 66083 , SPELL_LIGHTNING_ARROWS_PROC = 66085 , SPELL_MULTI_SHOT = 66081 ,
SPELL_SHOOT = 65868
}
enum { SPELL_POISON_BOTTLE = 67701 , SPELL_FAN_OF_KNIVES = 67706 , SPELL_EVISCERATE = 67709 , SPELL_DEADLY_POISON = 67710 }
enum { SPELL_CHAMPION_CHARGE = 63010 , SPELL_CHAMPION_DEFEND = 64100 }
Functions
UnitAI * GetAI_boss_champion_warrior (Creature *pCreature)
UnitAI * GetAI_boss_champion_mage (Creature *pCreature)
UnitAI * GetAI_boss_champion_shaman (Creature *pCreature)
UnitAI * GetAI_boss_champion_hunter (Creature *pCreature)
UnitAI * GetAI_boss_champion_rogue (Creature *pCreature)
UnitAI * GetAI_npc_trial_grand_champion (Creature *pCreature)
UnitAI * GetAI_npc_champion_mount (Creature *pCreature)
void AddSC_boss_grand_champions ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_DEFEND_DUMMY
SPELL_SHIELD_BREAKER
SPELL_CHARGE
SPELL_CHARGE_VEHICLE
SPELL_FULL_HEAL
SPELL_RIDE_ARGENT_VEHICLE
Definition at line 28 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_INTERCEPT
SPELL_BLADESTORM
SPELL_MORTAL_STRIKE
SPELL_ROLLING_THROW
Definition at line 354 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FIREBALL
SPELL_POLYMORPH
SPELL_BLAST_WAVE
SPELL_HASTE
Definition at line 437 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_HEALING_WAVE
SPELL_CHAIN_LIGHTNING
SPELL_EARTH_SHIELD
SPELL_HEX_OF_MENDING
Definition at line 531 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DISENGAGE
SPELL_LIGHTNING_ARROWS
SPELL_LIGHTNING_ARROWS_PROC
SPELL_MULTI_SHOT
SPELL_SHOOT
Definition at line 611 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_POISON_BOTTLE
SPELL_FAN_OF_KNIVES
SPELL_EVISCERATE
SPELL_DEADLY_POISON
Definition at line 719 of file boss_grand_champions.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CHAMPION_CHARGE
SPELL_CHAMPION_DEFEND
Definition at line 798 of file boss_grand_champions.cpp.
Function Documentation
AddSC_boss_grand_champions()
void AddSC_boss_grand_champions ()
Definition at line 966 of file boss_grand_champions.cpp.
References Script::GetAI, GetAI_boss_champion_hunter(), GetAI_boss_champion_mage(), GetAI_boss_champion_rogue(), GetAI_boss_champion_shaman(), GetAI_boss_champion_warrior(), GetAI_npc_champion_mount(), GetAI_npc_trial_grand_champion(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_champion_hunter()
UnitAI* GetAI_boss_champion_hunter (Creature * pCreature)
Definition at line 714 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_boss_champion_mage()
UnitAI* GetAI_boss_champion_mage (Creature * pCreature)
Definition at line 526 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_boss_champion_rogue()
UnitAI* GetAI_boss_champion_rogue (Creature * pCreature)
Definition at line 789 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_boss_champion_shaman()
UnitAI* GetAI_boss_champion_shaman (Creature * pCreature)
Definition at line 606 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_boss_champion_warrior()
UnitAI* GetAI_boss_champion_warrior (Creature * pCreature)
Definition at line 432 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_npc_champion_mount()
UnitAI* GetAI_npc_champion_mount (Creature * pCreature)
Definition at line 961 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().
GetAI_npc_trial_grand_champion()
UnitAI* GetAI_npc_trial_grand_champion (Creature * pCreature)
Definition at line 876 of file boss_grand_champions.cpp.
Referenced by AddSC_boss_grand_champions().