CMaNGOS_WoTLK: boss_doomlord_kazzak.cpp File Reference
boss_doomlord_kazzak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_doomlordkazzakAI
Enumerations
enum {
SAY_INTRO = -1000147 , SAY_AGGRO1 = -1000148 , SAY_AGGRO2 = -1000149 , SAY_SURPREME1 = -1000150 ,
SAY_SURPREME2 = -1000151 , SAY_KILL1 = -1000152 , SAY_KILL2 = -1000153 , SAY_KILL3 = -1000154 ,
SAY_DEATH = -1000155 , EMOTE_GENERIC_FRENZY = -1000002 , SAY_RAND1 = -1000157 , SAY_RAND2 = -1000158 ,
SPELL_SHADOW_VOLLEY = 32963 , SPELL_CLEAVE = 16044 , SPELL_THUNDERCLAP = 36706 , SPELL_VOID_BOLT = 21066 ,
SPELL_MARK_OF_KAZZAK = 32960 , SPELL_FRENZY = 32964 , SPELL_CAPTURE_SOUL = 48473 , SPELL_TWISTED_REFLECTION = 21063 ,
SPELL_BERSERK = 32965
}
Functions
UnitAI * GetAI_boss_doomlordkazzak (Creature *pCreature)
void AddSC_boss_doomlordkazzak ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO1
SAY_AGGRO2
SAY_SURPREME1
SAY_SURPREME2
SAY_KILL1
SAY_KILL2
SAY_KILL3
SAY_DEATH
EMOTE_GENERIC_FRENZY
SAY_RAND1
SAY_RAND2
SPELL_SHADOW_VOLLEY
SPELL_CLEAVE
SPELL_THUNDERCLAP
SPELL_VOID_BOLT
SPELL_MARK_OF_KAZZAK
SPELL_FRENZY
SPELL_CAPTURE_SOUL
SPELL_TWISTED_REFLECTION
SPELL_BERSERK
Definition at line 26 of file boss_doomlord_kazzak.cpp.
Function Documentation
AddSC_boss_doomlordkazzak()
void AddSC_boss_doomlordkazzak ()
Definition at line 197 of file boss_doomlord_kazzak.cpp.
References Script::GetAI, GetAI_boss_doomlordkazzak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_doomlordkazzak()
UnitAI* GetAI_boss_doomlordkazzak (Creature * pCreature)
Definition at line 192 of file boss_doomlord_kazzak.cpp.
Referenced by AddSC_boss_doomlordkazzak().