CMaNGOS_WoTLK: boss_auriaya.cpp File Reference
boss_auriaya.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_auriayaAI
struct boss_feral_defenderAI
Enumerations
enum {
SAY_AGGRO = -1603079 , SAY_SLAY_1 = -1603080 , SAY_SLAY_2 = -1603081 , SAY_BERSERK = -1603082 ,
SAY_DEATH = -1603083 , EMOTE_SCREECH = -1603084 , EMOTE_DEFENDER = -1603085 , SPELL_BERSERK = 47008 ,
SPELL_GUARDIAN_SWARM = 64396 , SPELL_SENTINEL_BLAST = 64389 , SPELL_SENTINEL_BLAST_H = 64678 , SPELL_SONIC_SCREECH = 64422 ,
SPELL_SONIC_SCREECH_H = 64688 , SPELL_TERRIFYING_SCREECH = 64386 , SPELL_ACTIVATE_FERAL_DEFENDER = 64449 , SPELL_ACTIVATE_FERAL_DEFENDER_TRIGG = 64448 ,
SPELL_FERAL_ESSENCE = 64455 , SPELL_FERAL_ESSENCE_REMOVAL = 64456 , SPELL_FERAL_POUNCE = 64478 , SPELL_FERAL_POUNCE_H = 64669 ,
SPELL_FERAL_RUSH = 64489 , SPELL_FERAL_RUSH_H = 64673 , SPELL_SEEPING_FERAL_ESSENCE_SUMMON = 64457 , SPELL_FEIGN_DEATH = 64461 ,
SPELL_FULL_HEAL = 64460 , SPELL_SEEPING_FERAL_ESSENCE = 64458 , SPELL_SEEPING_FERAL_ESSENCE_H = 64676 , NPC_SEEPING_FERAL_ESSENCE = 34098 ,
NPC_FERAL_DEFENDER_STALKER = 34096
}
Functions
UnitAI * GetAI_boss_auriaya (Creature *pCreature)
UnitAI * GetAI_boss_feral_defender (Creature *pCreature)
void AddSC_boss_auriaya ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
EMOTE_SCREECH
EMOTE_DEFENDER
SPELL_BERSERK
SPELL_GUARDIAN_SWARM
SPELL_SENTINEL_BLAST
SPELL_SENTINEL_BLAST_H
SPELL_SONIC_SCREECH
SPELL_SONIC_SCREECH_H
SPELL_TERRIFYING_SCREECH
SPELL_ACTIVATE_FERAL_DEFENDER
SPELL_ACTIVATE_FERAL_DEFENDER_TRIGG
SPELL_FERAL_ESSENCE
SPELL_FERAL_ESSENCE_REMOVAL
SPELL_FERAL_POUNCE
SPELL_FERAL_POUNCE_H
SPELL_FERAL_RUSH
SPELL_FERAL_RUSH_H
SPELL_SEEPING_FERAL_ESSENCE_SUMMON
SPELL_FEIGN_DEATH
SPELL_FULL_HEAL
SPELL_SEEPING_FERAL_ESSENCE
SPELL_SEEPING_FERAL_ESSENCE_H
NPC_SEEPING_FERAL_ESSENCE
NPC_FERAL_DEFENDER_STALKER
Definition at line 27 of file boss_auriaya.cpp.
Function Documentation
AddSC_boss_auriaya()
void AddSC_boss_auriaya ()
Definition at line 380 of file boss_auriaya.cpp.
References Script::GetAI, GetAI_boss_auriaya(), GetAI_boss_feral_defender(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_auriaya()
UnitAI* GetAI_boss_auriaya (Creature * pCreature)
Definition at line 207 of file boss_auriaya.cpp.
Referenced by AddSC_boss_auriaya().
GetAI_boss_feral_defender()
UnitAI* GetAI_boss_feral_defender (Creature * pCreature)
Definition at line 375 of file boss_auriaya.cpp.
Referenced by AddSC_boss_auriaya().