CMaNGOS_WoTLK: boss_high_botanist_freywinn.cpp File Reference
boss_high_botanist_freywinn.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_high_botanist_freywinnAI
Enumerations
enum {
SAY_AGGRO = -1553000 , SAY_KILL_1 = -1553001 , SAY_KILL_2 = -1553002 , SAY_TREE_1 = -1553003 ,
SAY_TREE_2 = -1553004 , SAY_DEATH = -1553005 , SPELL_TRANQUILITY = 34550 , SPELL_TREE_FORM = 34551 ,
SPELL_SUMMON_FRAYER = 34557 , SPELL_PLANT_WHITE = 34759 , SPELL_PLANT_GREEN = 34761 , SPELL_PLANT_BLUE = 34762 ,
SPELL_PLANT_RED = 34763 , NPC_FRAYER_PROTECTOR = 19953
}
Functions
UnitAI * GetAI_boss_high_botanist_freywinn (Creature *pCreature)
void AddSC_boss_high_botanist_freywinn ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_KILL_1
SAY_KILL_2
SAY_TREE_1
SAY_TREE_2
SAY_DEATH
SPELL_TRANQUILITY
SPELL_TREE_FORM
SPELL_SUMMON_FRAYER
SPELL_PLANT_WHITE
SPELL_PLANT_GREEN
SPELL_PLANT_BLUE
SPELL_PLANT_RED
NPC_FRAYER_PROTECTOR
Definition at line 26 of file boss_high_botanist_freywinn.cpp.
Function Documentation
AddSC_boss_high_botanist_freywinn()
void AddSC_boss_high_botanist_freywinn ()
Definition at line 198 of file boss_high_botanist_freywinn.cpp.
References Script::GetAI, GetAI_boss_high_botanist_freywinn(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_high_botanist_freywinn()
UnitAI* GetAI_boss_high_botanist_freywinn (Creature * pCreature)
Definition at line 193 of file boss_high_botanist_freywinn.cpp.
Referenced by AddSC_boss_high_botanist_freywinn().