CMaNGOS_WoTLK: boss_thorim.cpp File Reference
boss_thorim.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_thorimAI
struct boss_sifAI
struct npc_runic_colossusAI
struct npc_thunder_orbAI
Enumerations
enum {
SAY_AGGRO_1 = -1603138 , SAY_AGGRO_2 = -1603139 , SAY_SPECIAL_1 = -1603140 , SAY_SPECIAL_2 = -1603141 ,
SAY_SPECIAL_3 = -1603142 , SAY_JUMP = -1603143 , SAY_SLAY_1 = -1603144 , SAY_SLAY_2 = -1603145 ,
SAY_BERSERK = -1603146 , SAY_ARENA_WIPE = -1603147 , SAY_DEFEATED = -1603148 , SAY_OUTRO_1 = -1603149 ,
SAY_OUTRO_2 = -1603150 , SAY_OUTRO_3 = -1603151 , SAY_OUTRO_HARD_1 = -1603152 , SAY_OUTRO_HARD_2 = -1603153 ,
SAY_OUTRO_HARD_3 = -1603154 , SAY_SIF_BEGIN = -1603156 , SAY_SIF_EVENT = -1603157 , SAY_SIF_DESPAWN = -1603158 ,
EMOTE_RUNIC_BARRIER = -1603247 , SPELL_SHEAT_OF_LIGHTNING = 62276 , SPELL_STORMHAMMER = 62042 , SPELL_CHARGE_ORB = 62016 ,
SPELL_TOUCH_OF_DOMINION = 62507 , SPELL_TOUCH_OF_DOMINION_AURA = 62565 , SPELL_BERSERK_1 = 62560 , SPELL_SUMMON_LIGHTNING_ORB = 62391 ,
SPELL_LIGHTNING_DESTRUCTION = 62393 , SPELL_CHAIN_LIGHTNING = 62131 , SPELL_CHAIN_LIGHTNING_H = 64390 , SPELL_LIGHTNING_CHARGE_DAMAGE = 62466 ,
SPELL_UNBALANCING_STRIKE = 62130 , SPELL_BERSERK_2 = 62555 , SPELL_THORIM_CREDIT = 64985 , SPELL_STORMHAMMER_OUTRO = 64767 ,
SPELL_LIGHTNING_PILLAR_ORB = 63238 , SPELL_LIGHTNING_ORG_CHARGED = 62186 , SPELL_LIGHTNING_ORB_TRIGGER = 62278 , SPELL_LIGHTNING_PILLAR = 62976 ,
SPELL_ACTIVATE_LIGHTNING_ORB_PERIODIC = 62184 , SPELL_LIGHTNING_FIELD = 64972 , SPELL_FROSTBOLT = 62583 , SPELL_FROSTBOLT_H = 62601 ,
SPELL_FROSTBOLT_VOLLEY = 62580 , SPELL_FROSTBOLT_VOLLEY_H = 62604 , SPELL_FROST_NOVA = 62597 , SPELL_FROST_NOVA_H = 62605 ,
SPELL_BLIZZARD = 62577 , SPELL_BLIZZARD_H = 62603 , SPELL_BLINK = 62578 , SPELL_RUNIC_SMASH_L = 62058 ,
SPELL_RUNIC_SMASH_R = 62057 , SPELL_RUNIC_SMASH = 62465 , MAX_RUNIC_SMASH = 10 , SPELL_SMASH = 62339 ,
SPELL_RUNIC_BARRIER = 62338 , SPELL_CHARGE = 62613 , SPELL_CHARGE_H = 62614 , SPELL_LEAP = 61934 ,
NPC_LIGHTNING_ORB = 33138 , NPC_DARK_RUNE_CHAMPION = 32876 , NPC_DARK_RUNE_WARBRINGER = 32877 , NPC_DARK_RUNE_EVOKER = 32878 ,
NPC_DARK_RUNE_COMMONER = 32904 , FACTION_ID_FRIENDLY = 35 , PHASE_ARENA = 1 , PHASE_SOLO = 2 ,
PHASE_TRANSITION = 3
}
Functions
UnitAI * GetAI_boss_thorim (Creature *pCreature)
UnitAI * GetAI_boss_sif (Creature *pCreature)
UnitAI * GetAI_npc_runic_colossus (Creature *pCreature)
UnitAI * GetAI_npc_thunder_orb (Creature *pCreature)
void AddSC_boss_thorim ()
Variables
static const DialogueEntry aThorimDialogue []
static const float afSifSpawnLoc [4] = {2148.301f, -297.8453f, 438.3308f, 2.68f}
static const float afArenaCenterLoc [3] = {2134.8f, -263.056f, 419.983f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO_1
SAY_AGGRO_2
SAY_SPECIAL_1
SAY_SPECIAL_2
SAY_SPECIAL_3
SAY_JUMP
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_ARENA_WIPE
SAY_DEFEATED
SAY_OUTRO_1
SAY_OUTRO_2
SAY_OUTRO_3
SAY_OUTRO_HARD_1
SAY_OUTRO_HARD_2
SAY_OUTRO_HARD_3
SAY_SIF_BEGIN
SAY_SIF_EVENT
SAY_SIF_DESPAWN
EMOTE_RUNIC_BARRIER
SPELL_SHEAT_OF_LIGHTNING
SPELL_STORMHAMMER
SPELL_CHARGE_ORB
SPELL_TOUCH_OF_DOMINION
SPELL_TOUCH_OF_DOMINION_AURA
SPELL_BERSERK_1
SPELL_SUMMON_LIGHTNING_ORB
SPELL_LIGHTNING_DESTRUCTION
SPELL_CHAIN_LIGHTNING
SPELL_CHAIN_LIGHTNING_H
SPELL_LIGHTNING_CHARGE_DAMAGE
SPELL_UNBALANCING_STRIKE
SPELL_BERSERK_2
SPELL_THORIM_CREDIT
SPELL_STORMHAMMER_OUTRO
SPELL_LIGHTNING_PILLAR_ORB
SPELL_LIGHTNING_ORG_CHARGED
SPELL_LIGHTNING_ORB_TRIGGER
SPELL_LIGHTNING_PILLAR
SPELL_ACTIVATE_LIGHTNING_ORB_PERIODIC
SPELL_LIGHTNING_FIELD
SPELL_FROSTBOLT
SPELL_FROSTBOLT_H
SPELL_FROSTBOLT_VOLLEY
SPELL_FROSTBOLT_VOLLEY_H
SPELL_FROST_NOVA
SPELL_FROST_NOVA_H
SPELL_BLIZZARD
SPELL_BLIZZARD_H
SPELL_BLINK
SPELL_RUNIC_SMASH_L
SPELL_RUNIC_SMASH_R
SPELL_RUNIC_SMASH
MAX_RUNIC_SMASH
SPELL_SMASH
SPELL_RUNIC_BARRIER
SPELL_CHARGE
SPELL_CHARGE_H
SPELL_LEAP
NPC_LIGHTNING_ORB
NPC_DARK_RUNE_CHAMPION
NPC_DARK_RUNE_WARBRINGER
NPC_DARK_RUNE_EVOKER
NPC_DARK_RUNE_COMMONER
FACTION_ID_FRIENDLY
PHASE_ARENA
PHASE_SOLO
PHASE_TRANSITION
Definition at line 27 of file boss_thorim.cpp.
Function Documentation
AddSC_boss_thorim()
void AddSC_boss_thorim ()
Definition at line 1052 of file boss_thorim.cpp.
References Script::GetAI, GetAI_boss_sif(), GetAI_boss_thorim(), GetAI_npc_runic_colossus(), GetAI_npc_thunder_orb(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_sif()
UnitAI* GetAI_boss_sif (Creature * pCreature)
Definition at line 820 of file boss_thorim.cpp.
Referenced by AddSC_boss_thorim().
GetAI_boss_thorim()
UnitAI* GetAI_boss_thorim (Creature * pCreature)
Definition at line 672 of file boss_thorim.cpp.
Referenced by AddSC_boss_thorim().
GetAI_npc_runic_colossus()
UnitAI* GetAI_npc_runic_colossus (Creature * pCreature)
Definition at line 996 of file boss_thorim.cpp.
Referenced by AddSC_boss_thorim().
GetAI_npc_thunder_orb()
UnitAI* GetAI_npc_thunder_orb (Creature * pCreature)
Definition at line 1047 of file boss_thorim.cpp.
Referenced by AddSC_boss_thorim().
Variable Documentation
afArenaCenterLoc
const float afArenaCenterLoc[3] = {2134.8f, -263.056f, 419.983f} static
Definition at line 151 of file boss_thorim.cpp.
Referenced by boss_thorimAI::JustDidDialogueStep().
afSifSpawnLoc
const float afSifSpawnLoc[4] = {2148.301f, -297.8453f, 438.3308f, 2.68f} static
Definition at line 150 of file boss_thorim.cpp.
Referenced by boss_thorimAI::JustDidDialogueStep().
aThorimDialogue
const DialogueEntry aThorimDialogue[] static
Initial value:
=
{
    {SAY_AGGRO_1,               NPC_THORIM,     9000},
    {SAY_AGGRO_2,               NPC_THORIM,     7000},
    {NPC_SIF,                   0,              5000},
    {SPELL_TOUCH_OF_DOMINION,   0,              0},
    {SAY_JUMP,                  NPC_THORIM,     10000},
    {PHASE_SOLO,                0,              0},
    {SAY_DEFEATED,              NPC_THORIM,     3000},
    {SAY_OUTRO_1,               NPC_THORIM,     10000},
    {SAY_OUTRO_2,               NPC_THORIM,     12000},
    {SAY_OUTRO_3,               NPC_THORIM,     10000},
    {SPELL_TELEPORT,            0,              0},
    {SPELL_STORMHAMMER_OUTRO,   0,              3000},
    {SAY_OUTRO_HARD_1,          NPC_THORIM,     6000},
    {SAY_OUTRO_HARD_2,          NPC_THORIM,     12000},
    {SAY_OUTRO_HARD_3,          NPC_THORIM,     10000},
    {SPELL_THORIM_CREDIT,       0,              0},
    {0, 0, 0},
}
Definition at line 129 of file boss_thorim.cpp.