CMaNGOS_WoTLK: boss_grandmaster_vorpil.cpp File Reference
boss_grandmaster_vorpil.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shadow_labyrinth.h"
Data Structures
struct SummonLocations
struct boss_grandmaster_vorpilAI
struct npc_void_travelerAI
Enumerations
enum {
SAY_INTRO = -1555028 , SAY_AGGRO_1 = -1555029 , SAY_AGGRO_2 = -1555030 , SAY_AGGRO_3 = -1555031 ,
SAY_HELP = -1555032 , SAY_SLAY_1 = -1555033 , SAY_SLAY_2 = -1555034 , SAY_DEATH = -1555035 ,
SPELL_DRAW_SHADOWS = 33563 , SPELL_VOID_PORTAL_A = 33566 , SPELL_SHADOW_BOLT_VOLLEY = 32963 , SPELL_RAIN_OF_FIRE = 33617 ,
SPELL_RAIN_OF_FIRE_H = 39363 , SPELL_BANISH_H = 38791 , SPELL_SUMMON_VOID_SUMMONER = 33927 , SPELL_SUMMON_VOIDWALKER_A = 33582 ,
SPELL_SUMMON_VOIDWALKER_B = 33583 , SPELL_SUMMON_VOIDWALKER_C = 33584 , SPELL_SUMMON_VOIDWALKER_D = 33585 , SPELL_SUMMON_VOIDWALKER_E = 33586 ,
SPELL_VOID_PORTAL_VISUAL = 33569 , SPELL_EMPOWERING_SHADOWS = 33783 , SPELL_EMPOWERING_SHADOWS_H = 39364 , SPELL_SHADOW_NOVA = 33846 ,
SPELL_INSTAKILL_SELF = 29878 , NPC_VOID_PORTAL = 19224 , NPC_VOID_TRAVELER = 19226 , MAX_PORTALS = 4
}
Functions
UnitAI * GetAI_boss_grandmaster_vorpil (Creature *pCreature)
UnitAI * GetAI_npc_void_traveler (Creature *pCreature)
void AddSC_boss_grandmaster_vorpil ()
Variables
static const SummonLocations aVorpilLocation [MAX_PORTALS]
static const float aVorpilTeleportLoc [3] = { -253.06f, -264.02f, 17.08f}
static const uint32 aTravelerSummonSpells [5] = {SPELL_SUMMON_VOIDWALKER_A, SPELL_SUMMON_VOIDWALKER_B, SPELL_SUMMON_VOIDWALKER_C, SPELL_SUMMON_VOIDWALKER_D, SPELL_SUMMON_VOIDWALKER_E}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_HELP
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SPELL_DRAW_SHADOWS
SPELL_VOID_PORTAL_A
SPELL_SHADOW_BOLT_VOLLEY
SPELL_RAIN_OF_FIRE
SPELL_RAIN_OF_FIRE_H
SPELL_BANISH_H
SPELL_SUMMON_VOID_SUMMONER
SPELL_SUMMON_VOIDWALKER_A
SPELL_SUMMON_VOIDWALKER_B
SPELL_SUMMON_VOIDWALKER_C
SPELL_SUMMON_VOIDWALKER_D
SPELL_SUMMON_VOIDWALKER_E
SPELL_VOID_PORTAL_VISUAL
SPELL_EMPOWERING_SHADOWS
SPELL_EMPOWERING_SHADOWS_H
SPELL_SHADOW_NOVA
SPELL_INSTAKILL_SELF
NPC_VOID_PORTAL
NPC_VOID_TRAVELER
MAX_PORTALS
Definition at line 27 of file boss_grandmaster_vorpil.cpp.
Function Documentation
AddSC_boss_grandmaster_vorpil()
void AddSC_boss_grandmaster_vorpil ()
Definition at line 322 of file boss_grandmaster_vorpil.cpp.
References Script::GetAI, GetAI_boss_grandmaster_vorpil(), GetAI_npc_void_traveler(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_grandmaster_vorpil()
UnitAI* GetAI_boss_grandmaster_vorpil (Creature * pCreature)
Definition at line 263 of file boss_grandmaster_vorpil.cpp.
Referenced by AddSC_boss_grandmaster_vorpil().
GetAI_npc_void_traveler()
UnitAI* GetAI_npc_void_traveler (Creature * pCreature)
Definition at line 317 of file boss_grandmaster_vorpil.cpp.
Referenced by AddSC_boss_grandmaster_vorpil().
Variable Documentation
aTravelerSummonSpells
const uint32 aTravelerSummonSpells[5] = {SPELL_SUMMON_VOIDWALKER_A, SPELL_SUMMON_VOIDWALKER_B, SPELL_SUMMON_VOIDWALKER_C, SPELL_SUMMON_VOIDWALKER_D, SPELL_SUMMON_VOIDWALKER_E} static
Definition at line 81 of file boss_grandmaster_vorpil.cpp.
Referenced by boss_grandmaster_vorpilAI::UpdateAI().
aVorpilLocation
const SummonLocations aVorpilLocation[MAX_PORTALS] static
Initial value:
=
{
    { -282.272f, -240.432f, 12.6839f, 5.58017f},
    { -261.676f, -297.69f, 17.08701f, 1.36025f},
    { -291.833f, -268.595f, 12.68254f, 0.047734f},
    { -303.966f, -255.759f, 12.6834f, 6.01283f}
}
Definition at line 71 of file boss_grandmaster_vorpil.cpp.
Referenced by boss_grandmaster_vorpilAI::Aggro().
aVorpilTeleportLoc
const float aVorpilTeleportLoc[3] = { -253.06f, -264.02f, 17.08f} static
Definition at line 79 of file boss_grandmaster_vorpil.cpp.
Referenced by boss_grandmaster_vorpilAI::DoTeleportToPlatform().