CMaNGOS_WoTLK: boss_algalon.cpp File Reference
boss_algalon.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_algalonAI
struct npc_living_constellationAI
struct npc_worm_holeAI
struct npc_black_holeAI
struct npc_collapsing_starAI
Enumerations
enum {
SAY_INTRO_1 = -1603106 , SAY_INTRO_2 = -1603107 , SAY_INTRO_3 = -1603108 , SAY_ENGAGE = -1603109 ,
SAY_AGGRO = -1603110 , SAY_SLAY_1 = -1603111 , SAY_SLAY_2 = -1603112 , SAY_SUMMON_STAR = -1603113 ,
SAY_BIG_BANG_1 = -1603114 , SAY_BIG_BANG_2 = -1603115 , SAY_PHASE_2 = -1603116 , SAY_BERSERK = -1603117 ,
SAY_DESPAWN_1 = -1603118 , SAY_DESPAWN_2 = -1603119 , SAY_DESPAWN_3 = -1603120 , SAY_OUTRO_1 = -1603121 ,
SAY_OUTRO_2 = -1603122 , SAY_OUTRO_3 = -1603123 , SAY_OUTRO_4 = -1603124 , SAY_OUTRO_5 = -1603125 ,
SAY_BRANN_OUTRO = -1603246 , SPELL_ARRIVAL = 64997 , SPELL_RIDE_LIGHTNING = 64986 , SPELL_SUMMON_AZEROTH = 64994 ,
SPELL_REORIGINATION = 64996 , SPELL_KILL_CREDIT = 65184 , SPELL_SUPERMASSIVE_FAIL = 65311 , SPELL_BERSERK = 47008 ,
SPELL_ASCEND_HEAVENS = 64487 , SPELL_QUANTUM_STRIKE = 64395 , SPELL_QUANTUM_STRIKE_H = 64592 , SPELL_PHASE_PUNCH = 64412 ,
SPELL_PHASE_PUNCH_SHIFT = 64417 , SPELL_COSMIC_SMASH_SUMMON = 62301 , SPELL_COSMIC_SMASH_SUMMON_H = 64598 , SPELL_BIG_BANG = 64443 ,
SPELL_BIG_BANG_H = 64584 , SPELL_COSMIC_SMASH_STATE = 62300 , SPELL_COLLAPSE = 62018 , SPELL_BLACK_HOLE_EXPLOSION = 64122 ,
SPELL_BLACK_HOLE_EXPLOSION_H = 65108 , SPELL_SUMMON_BLACK_HOLE = 62189 , SPELL_BLACK_HOLE_SPAWN_VISUAL = 62003 , SPELL_BLACK_HOLE_STATE = 64135 ,
SPELL_BLACK_HOLE_TRIGG = 62185 , SPELL_BLACK_HOLE_PHASE = 62168 , SPELL_BLACK_HOLE_DMG = 62169 , SPELL_BLACK_HOLE_CREDIT = 65312 ,
SPELL_BLACK_HOLE_DESPAWN = 64391 , SPELL_ARCANE_BARRAGE = 64599 , SPELL_ARCANE_BARRAGE_H = 64607 , SPELL_WORM_HOLE_TRIGGER = 65251 ,
SPELL_WORM_HOLE_PHASE = 65250 , SPELL_SUMMON_UNLEASHED_DARK_MATTER = 64450 , SPELL_SUMMON_VOID_ZONE_VISUAL = 64470 , SPELL_VOID_ZONE_VISUAL = 64469 ,
NPC_AZEROTH = 34246 , NPC_ASTEROID_STALKER_1 = 33104 , NPC_COLLAPSING_STAR = 32955 , NPC_BLACK_HOLE = 32953 ,
NPC_VOID_ZONE_VISUAL = 34100 , NPC_LIVING_CONSTELLATION = 33052 , NPC_WORM_HOLE = 34099 , NPC_UNLEASHED_DARK_MATTER = 34097 ,
FACTION_ID_FRIENDLY = 35 , MAX_CONSTELATIONS = 11 , MAX_ACTIVE_CONSTELATIONS = 3 , MAX_BLACK_HOLES = 4 ,
MAX_WORM_HOLES = 4
}
Functions
UnitAI * GetAI_boss_algalon (Creature *pCreature)
UnitAI * GetAI_npc_living_constellation (Creature *pCreature)
UnitAI * GetAI_npc_worm_hole (Creature *pCreature)
UnitAI * GetAI_npc_black_hole (Creature *pCreature)
UnitAI * GetAI_npc_collapsing_star (Creature *pCreature)
bool GOUse_go_celestial_access (Player *pPlayer, GameObject *pGo)
void AddSC_boss_algalon ()
Variables
static const DialogueEntry aAlgalonDialogue []
static const float afWormHoles [MAX_WORM_HOLES][3]
static const float afConstellations [MAX_CONSTELATIONS][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_ENGAGE
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SUMMON_STAR
SAY_BIG_BANG_1
SAY_BIG_BANG_2
SAY_PHASE_2
SAY_BERSERK
SAY_DESPAWN_1
SAY_DESPAWN_2
SAY_DESPAWN_3
SAY_OUTRO_1
SAY_OUTRO_2
SAY_OUTRO_3
SAY_OUTRO_4
SAY_OUTRO_5
SAY_BRANN_OUTRO
SPELL_ARRIVAL
SPELL_RIDE_LIGHTNING
SPELL_SUMMON_AZEROTH
SPELL_REORIGINATION
SPELL_KILL_CREDIT
SPELL_SUPERMASSIVE_FAIL
SPELL_BERSERK
SPELL_ASCEND_HEAVENS
SPELL_QUANTUM_STRIKE
SPELL_QUANTUM_STRIKE_H
SPELL_PHASE_PUNCH
SPELL_PHASE_PUNCH_SHIFT
SPELL_COSMIC_SMASH_SUMMON
SPELL_COSMIC_SMASH_SUMMON_H
SPELL_BIG_BANG
SPELL_BIG_BANG_H
SPELL_COSMIC_SMASH_STATE
SPELL_COLLAPSE
SPELL_BLACK_HOLE_EXPLOSION
SPELL_BLACK_HOLE_EXPLOSION_H
SPELL_SUMMON_BLACK_HOLE
SPELL_BLACK_HOLE_SPAWN_VISUAL
SPELL_BLACK_HOLE_STATE
SPELL_BLACK_HOLE_TRIGG
SPELL_BLACK_HOLE_PHASE
SPELL_BLACK_HOLE_DMG
SPELL_BLACK_HOLE_CREDIT
SPELL_BLACK_HOLE_DESPAWN
SPELL_ARCANE_BARRAGE
SPELL_ARCANE_BARRAGE_H
SPELL_WORM_HOLE_TRIGGER
SPELL_WORM_HOLE_PHASE
SPELL_SUMMON_UNLEASHED_DARK_MATTER
SPELL_SUMMON_VOID_ZONE_VISUAL
SPELL_VOID_ZONE_VISUAL
NPC_AZEROTH
NPC_ASTEROID_STALKER_1
NPC_COLLAPSING_STAR
NPC_BLACK_HOLE
NPC_VOID_ZONE_VISUAL
NPC_LIVING_CONSTELLATION
NPC_WORM_HOLE
NPC_UNLEASHED_DARK_MATTER
FACTION_ID_FRIENDLY
MAX_CONSTELATIONS
MAX_ACTIVE_CONSTELATIONS
MAX_BLACK_HOLES
MAX_WORM_HOLES
Definition at line 27 of file boss_algalon.cpp.
Function Documentation
AddSC_boss_algalon()
void AddSC_boss_algalon ()
Definition at line 804 of file boss_algalon.cpp.
References Script::GetAI, GetAI_boss_algalon(), GetAI_npc_black_hole(), GetAI_npc_collapsing_star(), GetAI_npc_living_constellation(), GetAI_npc_worm_hole(), GOUse_go_celestial_access(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_algalon()
UnitAI* GetAI_boss_algalon (Creature * pCreature)
Definition at line 615 of file boss_algalon.cpp.
Referenced by AddSC_boss_algalon().
GetAI_npc_black_hole()
UnitAI* GetAI_npc_black_hole (Creature * pCreature)
Definition at line 762 of file boss_algalon.cpp.
Referenced by AddSC_boss_algalon().
GetAI_npc_collapsing_star()
UnitAI* GetAI_npc_collapsing_star (Creature * pCreature)
Definition at line 781 of file boss_algalon.cpp.
Referenced by AddSC_boss_algalon().
GetAI_npc_living_constellation()
UnitAI* GetAI_npc_living_constellation (Creature * pCreature)
Definition at line 668 of file boss_algalon.cpp.
Referenced by AddSC_boss_algalon().
GetAI_npc_worm_hole()
UnitAI* GetAI_npc_worm_hole (Creature * pCreature)
Definition at line 715 of file boss_algalon.cpp.
Referenced by AddSC_boss_algalon().
GOUse_go_celestial_access()
bool GOUse_go_celestial_access (Player * pPlayer, GameObject * pGo)
Definition at line 790 of file boss_algalon.cpp.
References InstanceData::GetData(), WorldObject::GetInstanceData(), NOT_STARTED, InstanceData::SetData(), SPECIAL, and TYPE_ALGALON.
Referenced by AddSC_boss_algalon().
Variable Documentation
aAlgalonDialogue
const DialogueEntry aAlgalonDialogue[] static
Initial value:
=
{
    {SAY_INTRO_1,           NPC_ALGALON,        6000},
    {SPELL_SUMMON_AZEROTH,  0,                  5000},
    {SAY_INTRO_2,           NPC_ALGALON,        8000},
    {SAY_INTRO_3,           NPC_ALGALON,        12000},
    {SPELL_SUPERMASSIVE_FAIL, 0,                0},
    {SAY_AGGRO,             NPC_ALGALON,        14000},
    {SAY_ENGAGE,            NPC_ALGALON,        0},
    {SPELL_ASCEND_HEAVENS,  0,                  3000},
    {SPELL_BERSERK,         0,                  0},
    {SAY_DESPAWN_1,         NPC_ALGALON,        15000},
    {SAY_DESPAWN_2,         NPC_ALGALON,        8000},
    {SAY_DESPAWN_3,         NPC_ALGALON,        10000},
    {SPELL_TELEPORT,        0,                  0},
    {NPC_ALGALON,           0,                  12000},
    {SAY_OUTRO_1,           NPC_ALGALON,        39000},
    {SAY_OUTRO_2,           NPC_ALGALON,        18000},
    {SAY_OUTRO_3,           NPC_ALGALON,        12000},
    {SAY_OUTRO_4,           NPC_ALGALON,        12000},
    {SAY_BRANN_OUTRO,       NPC_BRANN_ALGALON,  11000},
    {SAY_OUTRO_5,           NPC_ALGALON,        15000},
    {SPELL_TELEPORT,        0,                  0},
    {0, 0, 0},
}
Definition at line 132 of file boss_algalon.cpp.
afConstellations
const float afConstellations[MAX_CONSTELATIONS][4] static
Initial value:
=
{
    {1678.677f, -276.328f, 427.7531f, 3.97f},
    {1685.613f, -300.1219f, 443.2366f, 3.38f},
    {1668.317f, -324.7676f, 457.9394f, 3.21f},
    {1635.821f, -363.3442f, 424.3459f, 1.46f},
    {1672.188f, -357.2484f, 436.7337f, 2.33f},
    {1593.389f, -299.4325f, 432.4636f, 6.07f},
    {1591.706f, -263.8201f, 441.4153f, 5.25f},
    {1658.279f, -262.549f, 441.9073f, 4.18f},
    {1592.242f, -325.5323f, 446.9508f, 0.22f},
    {1625.208f, -267.2771f, 446.4296f, 5.04f},
    {1615.8f, -348.0065f, 442.9586f, 1.13f},
}
Definition at line 166 of file boss_algalon.cpp.
Referenced by boss_algalonAI::DoSpawnConstellations().
afWormHoles
const float afWormHoles[MAX_WORM_HOLES][3] static
Initial value:
=
{
    {1649.364f, -328.4229f, 417.4044f},
    {1615.728f, -320.9379f, 417.4044f},
    {1618.209f, -292.0328f, 417.4044f},
    {1646.932f, -296.028f, 417.4044f},
}
Definition at line 158 of file boss_algalon.cpp.
Referenced by boss_algalonAI::UpdateAI().