CMaNGOS_WoTLK: boss_onyxia.cpp File Reference
boss_onyxia.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "onyxias_lair.h"
Data Structures
struct OnyxiaMove
struct boss_onyxiaAI
Enumerations
enum {
SAY_AGGRO = -1249000 , SAY_KILL = -1249001 , SAY_PHASE_2_TRANS = -1249002 , SAY_PHASE_3_TRANS = -1249003 ,
EMOTE_BREATH = -1249004 , SAY_KITE = -1249005 , SPELL_WINGBUFFET = 18500 , SPELL_WINGBUFFET_H = 69293 ,
SPELL_FLAMEBREATH = 18435 , SPELL_FLAMEBREATH_H = 68970 , SPELL_CLEAVE = 68868 , SPELL_TAILSWEEP = 68867 ,
SPELL_TAILSWEEP_H = 69286 , SPELL_KNOCK_AWAY = 19633 , SPELL_FIREBALL = 18392 , SPELL_FIREBALL_H = 68926 ,
SPELL_BREATH_NORTH_TO_SOUTH = 17086 , SPELL_BREATH_SOUTH_TO_NORTH = 18351 , SPELL_BREATH_EAST_TO_WEST = 18576 , SPELL_BREATH_WEST_TO_EAST = 18609 ,
SPELL_BREATH_SE_TO_NW = 18564 , SPELL_BREATH_NW_TO_SE = 18584 , SPELL_BREATH_SW_TO_NE = 18596 , SPELL_BREATH_NE_TO_SW = 18617 ,
SPELL_VISUAL_BREATH_A = 4880 , SPELL_VISUAL_BREATH_B = 4919 , SPELL_BREATH_ENTRANCE = 21131 , SPELL_BELLOWINGROAR = 18431 ,
SPELL_HEATED_GROUND = 22191 , SPELL_SUMMONWHELP = 17646 , SPELL_SUMMON_LAIR_GUARD = 68968 , MAX_WHELPS_PER_PACK = 40 ,
POINT_ID_NORTH = 0 , POINT_ID_SOUTH = 4 , NUM_MOVE_POINT = 8 , POINT_ID_LIFTOFF = 1 + NUM_MOVE_POINT ,
POINT_ID_IN_AIR = 2 + NUM_MOVE_POINT , POINT_ID_INIT_NORTH = 3 + NUM_MOVE_POINT , POINT_ID_LAND = 4 + NUM_MOVE_POINT , PHASE_START = 1 ,
PHASE_BREATH = 2 , PHASE_END = 3 , PHASE_BREATH_POST = 4 , PHASE_TO_LIFTOFF = 5 ,
PHASE_BREATH_PRE = 6
}
Functions
UnitAI * GetAI_boss_onyxia (Creature *pCreature)
void AddSC_boss_onyxia ()
Variables
static const OnyxiaMove aMoveData [NUM_MOVE_POINT]
static const float afSpawnLocations [3][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_KILL
SAY_PHASE_2_TRANS
SAY_PHASE_3_TRANS
EMOTE_BREATH
SAY_KITE
SPELL_WINGBUFFET
SPELL_WINGBUFFET_H
SPELL_FLAMEBREATH
SPELL_FLAMEBREATH_H
SPELL_CLEAVE
SPELL_TAILSWEEP
SPELL_TAILSWEEP_H
SPELL_KNOCK_AWAY
SPELL_FIREBALL
SPELL_FIREBALL_H
SPELL_BREATH_NORTH_TO_SOUTH
SPELL_BREATH_SOUTH_TO_NORTH
SPELL_BREATH_EAST_TO_WEST
SPELL_BREATH_WEST_TO_EAST
SPELL_BREATH_SE_TO_NW
SPELL_BREATH_NW_TO_SE
SPELL_BREATH_SW_TO_NE
SPELL_BREATH_NE_TO_SW
SPELL_VISUAL_BREATH_A
SPELL_VISUAL_BREATH_B
SPELL_BREATH_ENTRANCE
SPELL_BELLOWINGROAR
SPELL_HEATED_GROUND
SPELL_SUMMONWHELP
SPELL_SUMMON_LAIR_GUARD
MAX_WHELPS_PER_PACK
POINT_ID_NORTH
POINT_ID_SOUTH
NUM_MOVE_POINT
POINT_ID_LIFTOFF
POINT_ID_IN_AIR
POINT_ID_INIT_NORTH
POINT_ID_LAND
PHASE_START
PHASE_BREATH
PHASE_END
PHASE_BREATH_POST
PHASE_TO_LIFTOFF
PHASE_BREATH_PRE
Definition at line 27 of file boss_onyxia.cpp.
Function Documentation
AddSC_boss_onyxia()
void AddSC_boss_onyxia ()
Definition at line 534 of file boss_onyxia.cpp.
References Script::GetAI, GetAI_boss_onyxia(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_onyxia()
UnitAI* GetAI_boss_onyxia (Creature * pCreature)
Definition at line 529 of file boss_onyxia.cpp.
Referenced by AddSC_boss_onyxia().
Variable Documentation
afSpawnLocations
const float afSpawnLocations[3][3] static
Initial value:
=
{
    { -30.127f, -254.463f, -89.440f},
    { -30.817f, -177.106f, -89.258f},
    { -126.57f, -214.609f, -71.446f}
}
Definition at line 109 of file boss_onyxia.cpp.
Referenced by boss_onyxiaAI::DidSummonWhelps(), and boss_onyxiaAI::UpdateAI().
aMoveData
const OnyxiaMove aMoveData[NUM_MOVE_POINT] static
Initial value:
=
{
    {SPELL_BREATH_NORTH_TO_SOUTH,  24.16332f, -216.0808f, -58.98009f},
    {SPELL_BREATH_NE_TO_SW,        10.2191f,  -247.912f,  -60.896f},
    {SPELL_BREATH_EAST_TO_WEST,   -15.00505f, -244.4841f, -60.40087f},
    {SPELL_BREATH_SE_TO_NW,       -63.5156f,  -240.096f,  -60.477f},
    {SPELL_BREATH_SOUTH_TO_NORTH, -66.3589f,  -215.928f,  -64.23904f},
    {SPELL_BREATH_SW_TO_NE,       -58.2509f,  -189.020f,  -60.790f},
    {SPELL_BREATH_WEST_TO_EAST,   -16.70134f, -181.4501f, -61.98513f},
    {SPELL_BREATH_NW_TO_SE,        12.26687f, -181.1084f, -60.23914f},
}
Definition at line 97 of file boss_onyxia.cpp.
Referenced by boss_onyxiaAI::SpellHit(), and boss_onyxiaAI::UpdateAI().