CMaNGOS_WoTLK: boss_pathaleon_the_calculator.cpp File Reference
boss_pathaleon_the_calculator.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "mechanar.h"
Data Structures
struct boss_pathaleon_the_calculatorAI
struct mob_nether_wraithAI
Enumerations
enum {
SAY_AGGRO = -1554020 , SAY_DOMINATION_1 = -1554021 , SAY_DOMINATION_2 = -1554022 , SAY_SUMMON = -1554023 ,
SAY_ENRAGE = -1554024 , SAY_SLAY_1 = -1554025 , SAY_SLAY_2 = -1554026 , SAY_DEATH = -1554027 ,
SPELL_MANA_TAP = 36021 , SPELL_ARCANE_TORRENT = 36022 , SPELL_DOMINATION = 35280 , SPELL_ARCANE_EXPLOSION_H = 15453 ,
SPELL_FRENZY = 36992 , SPELL_SUICIDE = 35301 , SPELL_DISGRUNTLED_ANGER = 35289 , SPELL_SUMMON_NETHER_WRAITH_1 = 35285 ,
SPELL_SUMMON_NETHER_WRAITH_2 = 35286 , SPELL_SUMMON_NETHER_WRAITH_3 = 35287 , SPELL_SUMMON_NETHER_WRAITH_4 = 35288 , SPELL_DETONATION = 35058 ,
SPELL_ARCANE_BOLT = 20720
}
Functions
UnitAI * GetAI_boss_pathaleon_the_calculator (Creature *pCreature)
UnitAI * GetAI_mob_nether_wraith (Creature *pCreature)
void AddSC_boss_pathaleon_the_calculator ()
Variables
static const uint32 aWraithSummonSpells [4] = {SPELL_SUMMON_NETHER_WRAITH_1, SPELL_SUMMON_NETHER_WRAITH_2, SPELL_SUMMON_NETHER_WRAITH_3, SPELL_SUMMON_NETHER_WRAITH_4}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_DOMINATION_1
SAY_DOMINATION_2
SAY_SUMMON
SAY_ENRAGE
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SPELL_MANA_TAP
SPELL_ARCANE_TORRENT
SPELL_DOMINATION
SPELL_ARCANE_EXPLOSION_H
SPELL_FRENZY
SPELL_SUICIDE
SPELL_DISGRUNTLED_ANGER
SPELL_SUMMON_NETHER_WRAITH_1
SPELL_SUMMON_NETHER_WRAITH_2
SPELL_SUMMON_NETHER_WRAITH_3
SPELL_SUMMON_NETHER_WRAITH_4
SPELL_DETONATION
SPELL_ARCANE_BOLT
Definition at line 27 of file boss_pathaleon_the_calculator.cpp.
Function Documentation
AddSC_boss_pathaleon_the_calculator()
void AddSC_boss_pathaleon_the_calculator ()
Definition at line 264 of file boss_pathaleon_the_calculator.cpp.
References Script::GetAI, GetAI_boss_pathaleon_the_calculator(), GetAI_mob_nether_wraith(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_pathaleon_the_calculator()
UnitAI* GetAI_boss_pathaleon_the_calculator (Creature * pCreature)
Definition at line 254 of file boss_pathaleon_the_calculator.cpp.
Referenced by AddSC_boss_pathaleon_the_calculator().
GetAI_mob_nether_wraith()
UnitAI* GetAI_mob_nether_wraith (Creature * pCreature)
Definition at line 259 of file boss_pathaleon_the_calculator.cpp.
Referenced by AddSC_boss_pathaleon_the_calculator().
Variable Documentation
aWraithSummonSpells
const uint32 aWraithSummonSpells[4] = {SPELL_SUMMON_NETHER_WRAITH_1, SPELL_SUMMON_NETHER_WRAITH_2, SPELL_SUMMON_NETHER_WRAITH_3, SPELL_SUMMON_NETHER_WRAITH_4} static
Definition at line 57 of file boss_pathaleon_the_calculator.cpp.
Referenced by boss_pathaleon_the_calculatorAI::UpdateAI().