CMaNGOS_WoTLK: boss_laj.cpp File Reference
boss_laj.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_lajAI
Enumerations
enum {
EMOTE_SUMMON = -1553006 , SPELL_ALLERGIC_REACTION = 34697 , SPELL_TELEPORT_SELF = 34673 , SPELL_TRASH = 3391 ,
SPELL_SUMMON_LASHER_1 = 34681 , SPELL_SUMMON_FLAYER_1 = 34682 , SPELL_SUMMON_LASHER_2 = 34684 , SPELL_SUMMON_FLAYER_2 = 34685 ,
SPELL_SUMMON_LASHER_3 = 34686 , SPELL_SUMMON_FLAYER_4 = 34687 , SPELL_SUMMON_LASHER_4 = 34688 , SPELL_SUMMON_FLAYER_3 = 34690 ,
MODEL_ID_DEFAULT = 13109 , MODEL_ID_ARCANE = 14213 , MODEL_ID_FIRE = 13110 , MODEL_ID_FROST = 14112 ,
MODEL_ID_NATURE = 14214
}
Functions
UnitAI * GetAI_boss_laj (Creature *pCreature)
void AddSC_boss_laj ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_SUMMON
SPELL_ALLERGIC_REACTION
SPELL_TELEPORT_SELF
SPELL_TRASH
SPELL_SUMMON_LASHER_1
SPELL_SUMMON_FLAYER_1
SPELL_SUMMON_LASHER_2
SPELL_SUMMON_FLAYER_2
SPELL_SUMMON_LASHER_3
SPELL_SUMMON_FLAYER_4
SPELL_SUMMON_LASHER_4
SPELL_SUMMON_FLAYER_3
MODEL_ID_DEFAULT
MODEL_ID_ARCANE
MODEL_ID_FIRE
MODEL_ID_FROST
MODEL_ID_NATURE
Definition at line 26 of file boss_laj.cpp.
Function Documentation
AddSC_boss_laj()
void AddSC_boss_laj ()
Definition at line 219 of file boss_laj.cpp.
References Script::GetAI, GetAI_boss_laj(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_laj()
UnitAI* GetAI_boss_laj (Creature * pCreature)
Definition at line 214 of file boss_laj.cpp.
Referenced by AddSC_boss_laj().