CMaNGOS_WoTLK: boss_emperor_dagran_thaurissan.cpp File Reference
boss_emperor_dagran_thaurissan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackrock_depths.h"
Data Structures
struct boss_emperor_dagran_thaurissanAI
struct boss_moira_bronzebeardAI
Enumerations
enum eEmperor {
FACTION_NEUTRAL = 734 , YELL_AGGRO_1 = -1230001 , YELL_AGGRO_2 = -1230064 , YELL_AGGRO_3 = -1230065 ,
YELL_SLAY = -1230002 , SPELL_HANDOFTHAURISSAN = 17492 , SPELL_AVATAROFFLAME = 15636
}
enum ePrincess {
SPELL_HEAL = 15586 , SPELL_RENEW = 10929 , SPELL_SHIELD = 10901 , SPELL_MINDBLAST = 15587 ,
SPELL_SHADOWWORDPAIN = 15654 , SPELL_SMITE = 10934 , SPELL_SHADOW_BOLT = 15537 , SPELL_OPEN_PORTAL = 13912
}
Functions
UnitAI * GetAI_boss_emperor_dagran_thaurissan (Creature *pCreature)
UnitAI * GetAI_boss_moira_bronzebeard (Creature *pCreature)
void AddSC_boss_draganthaurissan ()
Enumeration Type Documentation
eEmperor
enum eEmperor
Enumerator
FACTION_NEUTRAL
YELL_AGGRO_1
YELL_AGGRO_2
YELL_AGGRO_3
YELL_SLAY
SPELL_HANDOFTHAURISSAN
SPELL_AVATAROFFLAME
Definition at line 27 of file boss_emperor_dagran_thaurissan.cpp.
ePrincess
enum ePrincess
Enumerator
SPELL_HEAL
SPELL_RENEW
SPELL_SHIELD
SPELL_MINDBLAST
SPELL_SHADOWWORDPAIN
SPELL_SMITE
SPELL_SHADOW_BOLT
SPELL_OPEN_PORTAL
Definition at line 131 of file boss_emperor_dagran_thaurissan.cpp.
Function Documentation
AddSC_boss_draganthaurissan()
void AddSC_boss_draganthaurissan ()
Definition at line 239 of file boss_emperor_dagran_thaurissan.cpp.
References Script::GetAI, GetAI_boss_emperor_dagran_thaurissan(), GetAI_boss_moira_bronzebeard(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_emperor_dagran_thaurissan()
UnitAI* GetAI_boss_emperor_dagran_thaurissan (Creature * pCreature)
Definition at line 122 of file boss_emperor_dagran_thaurissan.cpp.
Referenced by AddSC_boss_draganthaurissan().
GetAI_boss_moira_bronzebeard()
UnitAI* GetAI_boss_moira_bronzebeard (Creature * pCreature)
Definition at line 234 of file boss_emperor_dagran_thaurissan.cpp.
Referenced by AddSC_boss_draganthaurissan().