CMaNGOS_WoTLK: boss_cthun.cpp File Reference
boss_cthun.cpp File Reference
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "temple_of_ahnqiraj.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_eye_of_cthunAI
struct boss_cthunAI
struct npc_giant_claw_tentacleAI
struct PeriodicSummonEyeTrigger
struct SummonCThunTentacles
struct RotateTrigger
struct PeriodicRotate
struct HookTentacleTrigger
struct ExitStomach
struct CheckReset
struct CThunMouthTentacle
struct DigestiveAcidPeriodic
Enumerations
enum {
EMOTE_WEAKENED = -1531011 , SPELL_CHECK_RESET_AURA = 26255 , SPELL_RESET_ENCOUNTER = 26257 , SPELL_EYE_BEAM = 26134 ,
SPELL_EYE_BEAM_INIT = 32950 , SPELL_DARK_GLARE = 26029 , SPELL_ROTATE_TRIGGER = 26137 , SPELL_ROTATE_360_LEFT = 26009 ,
SPELL_ROTATE_360_RIGHT = 26136 , SPELL_SUMMON_HOOK_TENTACLES_1 = 26397 , SPELL_SUMMON_HOOK_TENTACLES_2 = 26398 , SPELL_SUMMON_HOOK_TENTACLE = 26140 ,
SPELL_SUMMON_EYE_TENTACLES = 26152 , SPELL_SUMMON_EYE_TENTACLE_1 = 26144 , SPELL_SUMMON_EYE_TENTACLE_2 = 26145 , SPELL_SUMMON_EYE_TENTACLE_3 = 26146 ,
SPELL_SUMMON_EYE_TENTACLE_4 = 26147 , SPELL_SUMMON_EYE_TENTACLE_5 = 26148 , SPELL_SUMMON_EYE_TENTACLE_6 = 26149 , SPELL_SUMMON_EYE_TENTACLE_7 = 26150 ,
SPELL_SUMMON_EYE_TENTACLE_8 = 26151 , SPELL_DESPAWN_TENTACLES = 26399 , SPELL_CARAPACE_CTHUN = 26156 , SPELL_TRANSFORM = 26232 ,
SPELL_CTHUN_VULNERABLE = 26235 , SPELL_SUMMON_EYE_TENTACLES_P2 = 26769 , SPELL_GIANT_EYE_TENTACLES_1 = 26766 , SPELL_GIANT_EYE_TENTACLES_2 = 26767 ,
SPELL_SUMMON_GIANT_EYE_TENTACLE = 26768 , SPELL_SUMMON_GIANT_HOOKS_1 = 26213 , SPELL_SUMMON_GIANT_HOOKS_2 = 26217 , SPELL_SUMMON_GIANT_HOOK_TENTACLE = 26216 ,
SPELL_SUMMON_MOUTH_TENTACLES_1 = 26236 , SPELL_SUMMON_MOUTH_TENTACLES_2 = 26237 , SPELL_SUMMON_MOUTH_TENTACLE = 26332 , SPELL_DIGESTIVE_ACID_TELEPORT = 26220 ,
SPELL_EXIT_STOMACH_EFFECT = 26230 , SPELL_PORT_OUT_STOMACH_EFFECT = 26648 , SPELL_DIGESTIVE_ACID = 26476 , SPELL_EXIT_STOMACH = 26221 ,
NPC_WORLD_TRIGGER = 15384 , DISPLAY_ID_CTHUN_BODY = 15786 , AREATRIGGER_STOMACH_1 = 4033 , AREATRIGGER_STOMACH_2 = 4034 ,
AREATRIGGER_STOMACH_3 = 4036 , MAX_FLESH_TENTACLES = 2
}
enum EyeCthunActions { EYECTHUN_EYEBEAM , EYECTHUN_DARKGLARE , EYECTHUN_ACTION_MAX , EYECTHUN_END_DARKGLARE }
enum CthunActions {
CTHUN_CLAWTENTACLEDELAY , CTHUN_EYETENTACLEDELAY , CTHUN_ACTION_MAX , CTHUN_EMERGE ,
CTHUN_WEAKENED_END
}
enum {
SPELL_GIANT_GROUND_RUPTURE = 26478 , SPELL_HAMSTRING = 26211 , SPELL_THRASH = 3391 , SPELL_SUBMERGE_VISUAL = 28819 ,
SPELL_TELEPORT_GIANT_HOOK = 26191 , SPELL_TELEPORT_GIANT_HOOK_TRIGGER = 26205
}
enum GiantClawActions { GIANTCLAW_TRASH , GIANTCLAW_HAMSTRING , GIANTCLAW_CHECKTARGET , GIANTCLAW_ACTION_MAX }
Functions
bool AreaTrigger_at_stomach_cthun (Player *player, AreaTriggerEntry const *at)
void AddSC_boss_cthun ()
Variables
static const float cthunLocations [4][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_WEAKENED
SPELL_CHECK_RESET_AURA
SPELL_RESET_ENCOUNTER
SPELL_EYE_BEAM
SPELL_EYE_BEAM_INIT
SPELL_DARK_GLARE
SPELL_ROTATE_TRIGGER
SPELL_ROTATE_360_LEFT
SPELL_ROTATE_360_RIGHT
SPELL_SUMMON_HOOK_TENTACLES_1
SPELL_SUMMON_HOOK_TENTACLES_2
SPELL_SUMMON_HOOK_TENTACLE
SPELL_SUMMON_EYE_TENTACLES
SPELL_SUMMON_EYE_TENTACLE_1
SPELL_SUMMON_EYE_TENTACLE_2
SPELL_SUMMON_EYE_TENTACLE_3
SPELL_SUMMON_EYE_TENTACLE_4
SPELL_SUMMON_EYE_TENTACLE_5
SPELL_SUMMON_EYE_TENTACLE_6
SPELL_SUMMON_EYE_TENTACLE_7
SPELL_SUMMON_EYE_TENTACLE_8
SPELL_DESPAWN_TENTACLES
SPELL_CARAPACE_CTHUN
SPELL_TRANSFORM
SPELL_CTHUN_VULNERABLE
SPELL_SUMMON_EYE_TENTACLES_P2
SPELL_GIANT_EYE_TENTACLES_1
SPELL_GIANT_EYE_TENTACLES_2
SPELL_SUMMON_GIANT_EYE_TENTACLE
SPELL_SUMMON_GIANT_HOOKS_1
SPELL_SUMMON_GIANT_HOOKS_2
SPELL_SUMMON_GIANT_HOOK_TENTACLE
SPELL_SUMMON_MOUTH_TENTACLES_1
SPELL_SUMMON_MOUTH_TENTACLES_2
SPELL_SUMMON_MOUTH_TENTACLE
SPELL_DIGESTIVE_ACID_TELEPORT
SPELL_EXIT_STOMACH_EFFECT
SPELL_PORT_OUT_STOMACH_EFFECT
SPELL_DIGESTIVE_ACID
SPELL_EXIT_STOMACH
NPC_WORLD_TRIGGER
DISPLAY_ID_CTHUN_BODY
AREATRIGGER_STOMACH_1
AREATRIGGER_STOMACH_2
AREATRIGGER_STOMACH_3
MAX_FLESH_TENTACLES
Definition at line 31 of file boss_cthun.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GIANT_GROUND_RUPTURE
SPELL_HAMSTRING
SPELL_THRASH
SPELL_SUBMERGE_VISUAL
SPELL_TELEPORT_GIANT_HOOK
SPELL_TELEPORT_GIANT_HOOK_TRIGGER
Definition at line 475 of file boss_cthun.cpp.
CthunActions
enum CthunActions
Enumerator
CTHUN_CLAWTENTACLEDELAY
CTHUN_EYETENTACLEDELAY
CTHUN_ACTION_MAX
CTHUN_EMERGE
CTHUN_WEAKENED_END
Definition at line 250 of file boss_cthun.cpp.
EyeCthunActions
enum EyeCthunActions
Enumerator
EYECTHUN_EYEBEAM
EYECTHUN_DARKGLARE
EYECTHUN_ACTION_MAX
EYECTHUN_END_DARKGLARE
Definition at line 105 of file boss_cthun.cpp.
GiantClawActions
enum GiantClawActions
Enumerator
GIANTCLAW_TRASH
GIANTCLAW_HAMSTRING
GIANTCLAW_CHECKTARGET
GIANTCLAW_ACTION_MAX
Definition at line 485 of file boss_cthun.cpp.
Function Documentation
AddSC_boss_cthun()
void AddSC_boss_cthun ()
Definition at line 768 of file boss_cthun.cpp.
References AreaTrigger_at_stomach_cthun(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_stomach_cthun()
bool AreaTrigger_at_stomach_cthun (Player * player, AreaTriggerEntry const * at)
Definition at line 560 of file boss_cthun.cpp.
References AREATRIGGER_STOMACH_1, AREATRIGGER_STOMACH_2, AREATRIGGER_STOMACH_3, cthunLocations, GetClosestCreatureWithEntry(), Unit::HasAura(), AreaTriggerEntry::id, Unit::IsAlive(), Player::IsGameMaster(), Unit::NearTeleportTo(), NPC_WORLD_TRIGGER, SPELL_DIGESTIVE_ACID, SPELL_EXIT_STOMACH, SPELL_EXIT_STOMACH_EFFECT, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_cthun().
Variable Documentation
cthunLocations
const float cthunLocations[4][4] static
Initial value:
=
{
    { -8571.47f, 1990.2f, -98.7779f, 1.01229f},
    { -8525.08f, 1994.71f, -98.2553f, 2.58309f},
    { -8563.56f, 2040.69f,   -97.0f,  4.9426f},
    { -8576.06f, 1985.8359f, 100.23f, 6.10865f},
}
Definition at line 93 of file boss_cthun.cpp.
Referenced by AreaTrigger_at_stomach_cthun(), and boss_cthunAI::DoSpawnTentacles().