CMaNGOS_WoTLK: boss_majordomo_executus.cpp File Reference
boss_majordomo_executus.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "molten_core.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_majordomoAI
Enumerations
enum {
SAY_AGGRO = -1409003 , SAY_SLAY_1 = 9425 , SAY_SLAY_SOUND = 8036 , SAY_LAST_ADD = -1409019 ,
SAY_DEFEAT_1 = -1409007 , SAY_DEFEAT_2 = -1409020 , SAY_DEFEAT_3 = -1409021 , SPELL_MAGIC_REFLECTION = 20619 ,
SPELL_DAMAGE_REFLECTION = 21075 , SPELL_AEGIS = 20620 , SPELL_TELEPORT_RANDOM = 20618 , SPELL_TELEPORT_TARGET = 20534 ,
SPELL_HATE_TO_ZERO = 20538 , SPELL_IMMUNE_POLY = 21087 , SPELL_SEPARATION_ANXIETY = 21094 , SPELL_ENCOURAGEMENT = 21086 ,
SPELL_CHAMPION = 21090 , GOSSIP_ITEM_SUMMON_1 = -3409000 , GOSSIP_ITEM_SUMMON_2 = -3409001 , GOSSIP_ITEM_SUMMON_3 = -3409002 ,
SAY_SUMMON_0 = -1409023 , SAY_SUMMON_1 = -1409024 , SAY_SUMMON_MAJ = -1409008 , SAY_ARRIVAL1_RAG = -1409009 ,
SAY_ARRIVAL2_MAJ = -1409010 , SAY_ARRIVAL3_RAG = -1409011 , SAY_ARRIVAL4_MAJ = -1409022 , TEXT_ID_SUMMON_1 = 4995 ,
TEXT_ID_SUMMON_2 = 5011 , TEXT_ID_SUMMON_3 = 5012 , SPELL_TELEPORT_SELF = 19484 , SPELL_SUMMON_RAGNAROS = 19774 ,
SPELL_ELEMENTAL_FIRE = 19773 , SPELL_RAGNA_EMERGE = 20568
}
enum MajordomoActions {
MAJORDOMO_REFLECTION_SHIELD , MAJORDOMO_TELEPORT_RANDOM , MAJORDOMO_TELEPORT_TARGET , MAJORDOMO_AEGIS ,
MAJORDOMO_ACTION_MAX , MAJORDOMO_OUTRO
}
Functions
UnitAI * GetAI_boss_majordomo (Creature *creature)
bool GossipHello_boss_majordomo (Player *player, Creature *creature)
bool GossipSelect_boss_majordomo (Player *player, Creature *creature, uint32, uint32 uiAction)
void AddSC_boss_majordomo ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_SOUND
SAY_LAST_ADD
SAY_DEFEAT_1
SAY_DEFEAT_2
SAY_DEFEAT_3
SPELL_MAGIC_REFLECTION
SPELL_DAMAGE_REFLECTION
SPELL_AEGIS
SPELL_TELEPORT_RANDOM
SPELL_TELEPORT_TARGET
SPELL_HATE_TO_ZERO
SPELL_IMMUNE_POLY
SPELL_SEPARATION_ANXIETY
SPELL_ENCOURAGEMENT
SPELL_CHAMPION
GOSSIP_ITEM_SUMMON_1
GOSSIP_ITEM_SUMMON_2
GOSSIP_ITEM_SUMMON_3
SAY_SUMMON_0
SAY_SUMMON_1
SAY_SUMMON_MAJ
SAY_ARRIVAL1_RAG
SAY_ARRIVAL2_MAJ
SAY_ARRIVAL3_RAG
SAY_ARRIVAL4_MAJ
TEXT_ID_SUMMON_1
TEXT_ID_SUMMON_2
TEXT_ID_SUMMON_3
SPELL_TELEPORT_SELF
SPELL_SUMMON_RAGNAROS
SPELL_ELEMENTAL_FIRE
SPELL_RAGNA_EMERGE
Definition at line 29 of file boss_majordomo_executus.cpp.
MajordomoActions
enum MajordomoActions
Enumerator
MAJORDOMO_REFLECTION_SHIELD
MAJORDOMO_TELEPORT_RANDOM
MAJORDOMO_TELEPORT_TARGET
MAJORDOMO_AEGIS
MAJORDOMO_ACTION_MAX
MAJORDOMO_OUTRO
Definition at line 74 of file boss_majordomo_executus.cpp.
Function Documentation
AddSC_boss_majordomo()
void AddSC_boss_majordomo ()
Definition at line 444 of file boss_majordomo_executus.cpp.
References Script::GetAI, GetAI_boss_majordomo(), GossipHello_boss_majordomo(), GossipSelect_boss_majordomo(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_majordomo()
UnitAI* GetAI_boss_majordomo (Creature * creature)
Definition at line 404 of file boss_majordomo_executus.cpp.
Referenced by AddSC_boss_majordomo().
GossipHello_boss_majordomo()
bool GossipHello_boss_majordomo (Player * player, Creature * creature)
Definition at line 409 of file boss_majordomo_executus.cpp.
References FAIL, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SUMMON_1, GOSSIP_SENDER_MAIN, NOT_STARTED, TEXT_ID_SUMMON_1, and TYPE_RAGNAROS.
Referenced by AddSC_boss_majordomo().
GossipSelect_boss_majordomo()
bool GossipSelect_boss_majordomo (Player * player, Creature * creature, uint32 , uint32 uiAction)
Definition at line 422 of file boss_majordomo_executus.cpp.
References Creature::AI(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SUMMON_2, GOSSIP_ITEM_SUMMON_3, GOSSIP_SENDER_MAIN, TEXT_ID_SUMMON_2, and TEXT_ID_SUMMON_3.
Referenced by AddSC_boss_majordomo().