CMaNGOS_WoTLK: boss_thorngrin_the_tender.cpp File Reference
boss_thorngrin_the_tender.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_thorngrinAI
Enumerations
enum {
SAY_DEATH = -1553013 , SAY_PLAYER_KILL = -1553014 , SAY_SACRIFICE = -1553015 , SAY_20_HP = -1553016 ,
SAY_50_HP = -1553017 , SAY_HELLFIRE_1 = -1553018 , SAY_HELLFIRE_2 = -1553019 , SAY_AGGRO = -1553020 ,
SPELL_HELLFIRE = 34659 , SPELL_HELLFIRE_H = 39131 , SPELL_SACRIFICE = 34661 , SPELL_ENRAGE = 34670
}
Functions
UnitAI * GetAI_boss_thorngrin (Creature *pCreature)
void AddSC_boss_thorngrin ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DEATH
SAY_PLAYER_KILL
SAY_SACRIFICE
SAY_20_HP
SAY_50_HP
SAY_HELLFIRE_1
SAY_HELLFIRE_2
SAY_AGGRO
SPELL_HELLFIRE
SPELL_HELLFIRE_H
SPELL_SACRIFICE
SPELL_ENRAGE
Definition at line 26 of file boss_thorngrin_the_tender.cpp.
Function Documentation
AddSC_boss_thorngrin()
void AddSC_boss_thorngrin ()
Definition at line 138 of file boss_thorngrin_the_tender.cpp.
References Script::GetAI, GetAI_boss_thorngrin(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_thorngrin()
UnitAI* GetAI_boss_thorngrin (Creature * pCreature)
Definition at line 133 of file boss_thorngrin_the_tender.cpp.
Referenced by AddSC_boss_thorngrin().