CMaNGOS_WoTLK: boss_lich_king.cpp File Reference
boss_lich_king.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_reflection.h"
Data Structures
struct boss_lich_king_horAI
struct npc_jaina_sylvanas_horAI
Enumerations
enum {
SAY_FIRST_WALL = -1668005 , SAY_SECOND_WALL = -1668006 , SAY_THIRD_WALL = -1668007 , SAY_LAST_WALL = -1668008 ,
SPELL_SOUL_REAPER = 69409 , SPELL_SOUL_REAPER_H = 73797 , SPELL_SOUL_REAPER_TRIGGER = 69410 , SPELL_FURY_FROSTMOURNE = 70063 ,
SPELL_HARVEST_SOUL = 69866 , SPELL_STUN_BREAK = 69763 , SPELL_STUN_BREAK_VISUAL_A = 69764 , SPELL_STUN_BREAK_VISUAL_H = 70200 ,
POINT_ID_EPILOGUE = 101
}
enum { SPELL_ICE_BARRIER = 69787 , SPELL_CLOAK_OF_DARNKESS = 70188 }
Functions
bool EffectScriptEffectCreature_spell_stun_break (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool AreaTrigger_at_wrath_lich_king (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_boss_lich_king ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_FIRST_WALL
SAY_SECOND_WALL
SAY_THIRD_WALL
SAY_LAST_WALL
SPELL_SOUL_REAPER
SPELL_SOUL_REAPER_H
SPELL_SOUL_REAPER_TRIGGER
SPELL_FURY_FROSTMOURNE
SPELL_HARVEST_SOUL
SPELL_STUN_BREAK
SPELL_STUN_BREAK_VISUAL_A
SPELL_STUN_BREAK_VISUAL_H
POINT_ID_EPILOGUE
Definition at line 31 of file boss_lich_king.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ICE_BARRIER
SPELL_CLOAK_OF_DARNKESS
Definition at line 271 of file boss_lich_king.cpp.
Function Documentation
AddSC_boss_lich_king()
void AddSC_boss_lich_king ()
Definition at line 354 of file boss_lich_king.cpp.
References AreaTrigger_at_wrath_lich_king(), EffectScriptEffectCreature_spell_stun_break(), Script::GetAI, Script::Name, Script::pAreaTrigger, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_wrath_lich_king()
bool AreaTrigger_at_wrath_lich_king (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 333 of file boss_lich_king.cpp.
References AREATRIGGER_LICH_KING_ROOM, DONE, instance_halls_of_reflection::GetData(), WorldObject::GetInstanceData(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), instance_halls_of_reflection::SetData(), TYPE_FROSTWORN_GENERAL, and TYPE_LICH_KING.
Referenced by AddSC_boss_lich_king().
EffectScriptEffectCreature_spell_stun_break()
bool EffectScriptEffectCreature_spell_stun_break (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 253 of file boss_lich_king.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, UnitAI::EnterEvadeMode(), UnitAI::SendAIEvent(), Unit::SetImmuneToPlayer(), and SPELL_STUN_BREAK.
Referenced by AddSC_boss_lich_king().