CMaNGOS_WoTLK: boss_gortok.cpp File Reference
boss_gortok.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_pinnacle.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct spell_awaken_subboss_aura
struct spell_awaken_gortok
Functions
bool ProcessEventId_event_spell_gortok_event (uint32, Object *pSource, Object *, bool)
void AddSC_boss_gortok ()
Function Documentation
AddSC_boss_gortok()
void AddSC_boss_gortok ()
Definition at line 103 of file boss_gortok.cpp.
References Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_gortok_event(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_spell_gortok_event()
bool ProcessEventId_event_spell_gortok_event (uint32 , Object * pSource, Object * , bool)
Definition at line 33 of file boss_gortok.cpp.
References DONE, Object::GetObjectGuid(), IN_PROGRESS, and TYPE_GORTOK.
Referenced by AddSC_boss_gortok().