CMaNGOS_WoTLK: boss_sapphiron.cpp File Reference
boss_sapphiron.cpp File Reference
#include "AI/ScriptDevAI/base/BossAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_sapphironAI
struct IceBolt
struct FrostBreath
struct PeriodicIceBolt
struct DespawnIceBlock
struct SapphironBlizzardInit
struct SapphironAchievementCheck
Enumerations
enum {
EMOTE_BREATH = 36542 , EMOTE_GENERIC_ENRAGED = 7798 , EMOTE_SAPPHIRON_FLY = 32801 , EMOTE_SAPPHIRON_LAND = 32802 ,
SPELL_FROST_AURA = 71387 , SPELL_FROST_AURA_H = 55799 , SPELL_BERSERK = 26662 , SPELL_CLEAVE = 19983 ,
SPELL_TAIL_SWEEP = 15847 , SPELL_TAIL_SWEEP_H = 55696 , SPELL_LIFE_DRAIN = 28542 , SPELL_LIFE_DRAIN_H = 55665 ,
SPELL_SUMMON_BLIZZARD_INIT = 28560 , SPELL_SUMMON_BLIZZARD = 28561 , SPELL_DRAGON_HOVER = 18430 , SPELL_ICEBOLT_INIT = 28526 ,
SPELL_ICEBOLT = 28522 , SPELL_ICEBOLT_IMMUNITY = 31800 , SPELL_ICEBLOCK_SUMMON = 28535 , SPELL_FROST_BREATH_DUMMY = 30101 ,
SPELL_FROST_BREATH = 28524 , SPELL_DESPAWN_ICEBLOCK_GO = 28523 , SPELL_SUMMON_WING_BUFFET = 29329 , SPELL_DESPAWN_WING_BUFFET = 29330 ,
SPELL_DESPAWN_BUFFET_EFFECT = 29336 , SPELL_CHILL = 28547 , SPELL_CHILL_H = 55699 , SPELL_ACHIEVEMENT_CHECK = 60539 ,
NPC_BLIZZARD = 16474 , NPC_WING_BUFFET = 17025 , SPELLSET_10N = 1598901 , SPELLSET_AIR_10N = 1598902 ,
SPELLSET_NULL_10N = 1598903 , SPELLSET_25N = 2999101 , SPELLSET_AIR_25N = 2999102 , SPELLSET_NULL_25N = 2999103
}
enum SapphironPhases { PHASE_GROUND = 1 , PHASE_LIFT_OFF = 2 }
enum SapphironActions {
SAPPHIRON_AIR_PHASE , SAPPHIRON_LANDING_PHASE , SAPPHIRON_GROUND_PHASE , SAPPHIRON_BERSERK ,
SAPPHIRON_ACTION_MAX
}
Functions
bool GOUse_go_sapphiron_birth (Player *, GameObject *go)
void AddSC_boss_sapphiron ()
Variables
static const float aLiftOffPosition [3] = {3522.386f, -5236.784f, 137.709f}
std::unordered_set< ObjectGuid > localIceBlocks
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_BREATH
EMOTE_GENERIC_ENRAGED
EMOTE_SAPPHIRON_FLY
EMOTE_SAPPHIRON_LAND
SPELL_FROST_AURA
SPELL_FROST_AURA_H
SPELL_BERSERK
SPELL_CLEAVE
SPELL_TAIL_SWEEP
SPELL_TAIL_SWEEP_H
SPELL_LIFE_DRAIN
SPELL_LIFE_DRAIN_H
SPELL_SUMMON_BLIZZARD_INIT
SPELL_SUMMON_BLIZZARD
SPELL_DRAGON_HOVER
SPELL_ICEBOLT_INIT
SPELL_ICEBOLT
SPELL_ICEBOLT_IMMUNITY
SPELL_ICEBLOCK_SUMMON
SPELL_FROST_BREATH_DUMMY
SPELL_FROST_BREATH
SPELL_DESPAWN_ICEBLOCK_GO
SPELL_SUMMON_WING_BUFFET
SPELL_DESPAWN_WING_BUFFET
SPELL_DESPAWN_BUFFET_EFFECT
SPELL_CHILL
SPELL_CHILL_H
SPELL_ACHIEVEMENT_CHECK
NPC_BLIZZARD
NPC_WING_BUFFET
SPELLSET_10N
SPELLSET_AIR_10N
SPELLSET_NULL_10N
SPELLSET_25N
SPELLSET_AIR_25N
SPELLSET_NULL_25N
Definition at line 28 of file boss_sapphiron.cpp.
SapphironActions
enum SapphironActions
Enumerator
SAPPHIRON_AIR_PHASE
SAPPHIRON_LANDING_PHASE
SAPPHIRON_GROUND_PHASE
SAPPHIRON_BERSERK
SAPPHIRON_ACTION_MAX
Definition at line 85 of file boss_sapphiron.cpp.
SapphironPhases
enum SapphironPhases
Enumerator
PHASE_GROUND
PHASE_LIFT_OFF
Definition at line 79 of file boss_sapphiron.cpp.
Function Documentation
AddSC_boss_sapphiron()
void AddSC_boss_sapphiron ()
Definition at line 369 of file boss_sapphiron.cpp.
References Script::GetAI, GOUse_go_sapphiron_birth(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_sapphiron_birth()
bool GOUse_go_sapphiron_birth (Player * , GameObject * go)
Definition at line 225 of file boss_sapphiron.cpp.
References InstanceData::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), NOT_STARTED, NPC_SAPPHIRON, InstanceData::SetData(), SPECIAL, and TYPE_SAPPHIRON.
Referenced by AddSC_boss_sapphiron().
Variable Documentation
aLiftOffPosition
const float aLiftOffPosition[3] = {3522.386f, -5236.784f, 137.709f} static
Definition at line 77 of file boss_sapphiron.cpp.
Referenced by boss_sapphironAI::ExecuteAction().
localIceBlocks
std::unordered_set<ObjectGuid> localIceBlocks
Definition at line 94 of file boss_sapphiron.cpp.