CMaNGOS_WoTLK: boss_yogg_saron.cpp File Reference
boss_yogg_saron.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Entities/TemporarySpawn.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_saraAI
struct boss_yogg_saronAI
struct npc_voice_yogg_saronAI
struct npc_brain_yogg_saronAI
struct npc_guardian_of_yoggAI
struct npc_immortal_guardianAI
struct npc_constrictor_tentacleAI
struct npc_ominous_cloudAI
struct npc_death_rayAI
struct npc_descent_madnessAI
struct npc_keeper_mimironAI
struct npc_keeper_thorimAI
struct HodirsProtectiveGaze
Enumerations
enum {
SAY_SARA_INTRO_1 = -1603197 , SAY_SARA_INTRO_2 = -1603198 , SAY_SARA_AGGRO = -1603199 , SAY_SARA_HELP_1 = -1603201 ,
SAY_SARA_HELP_2 = -1603202 , SAY_SARA_SLAY_1 = -1603203 , SAY_SARA_SLAY_2 = -1603204 , SAY_WIPE_PHASE_1 = -1603205 ,
SAY_PHASE_2_INTRO_1 = -1603206 , SAY_PHASE_2_INTRO_2 = -1603262 , SAY_PHASE_2_INTRO_3 = -1603263 , SAY_PHASE_2_INTRO_4 = -1603264 ,
SAY_PHASE_2_INTRO_5 = -1603265 , SAY_SARA_PHYCHOSIS = -1603207 , SAY_SARA_DEATH_RAY = -1603208 , SAY_MADNESS = -1603209 ,
SAY_PHASE_3 = -1603210 , SAY_SLAY = -1603212 , SAY_DEATH = -1603213 , SAY_TO_INSANE_1 = -1603214 ,
SAY_TO_INSANE_2 = -1603215 , SOUND_ID_LUNATIC_GAZE = 15757 , SAY_LICH_KING_1 = -1603216 , SAY_CHAMPION_1 = -1603217 ,
SAY_CHAMPION_2 = -1603218 , SAY_LICH_KING_2 = -1603219 , SAY_YOGG_V3_1 = -1603220 , SAY_YOGG_V3_2 = -1603221 ,
SAY_NELTHARION_1 = -1603222 , SAY_YSERA = -1603223 , SAY_NELTHARION_2 = -1603224 , SAY_MALYGOS = -1603225 ,
SAY_YOGG_V2 = -1603226 , SAY_GARONA_1 = -1603227 , SAY_GARONA_2 = -1603267 , SAY_GARONA_3 = -1603228 ,
SAY_YOGG_V1_1 = -1603229 , SAY_YOGG_V1_2 = -1603230 , SAY_KING_LLANE = -1603231 , SAY_GARONA_4 = -1603232 ,
SAY_YOGG_V1_3 = -1603233 , EMOTE_VISION_BLAST = -1603234 , EMOTE_SHATTER_BLAST = -1603235 , EMOTE_CLOUD_BOIL = -1603261 ,
EMOTE_DEAFENING_ROAR = -1603266 , EMOTE_EMPOWERING_SHADOWS = -1603211 , SPELL_EXTINGUISH_LIFE = 64166 , SPELL_SARAS_FERVOR = 63747 ,
SPELL_SARAS_BLESSING = 63745 , SPELL_SARAS_ANGER = 63744 , SPELL_BOIL_OMNIOUSLY = 63030 , SPELL_SHADOW_NOVA = 62714 ,
SPELL_SHADOW_NOVA_H = 65209 , SPELL_DARK_VOLLEY = 63038 , SPELL_DOMINATE_MIND = 63713 , SPELL_SANITY = 63786 ,
SPELL_INSANE = 63120 , SPELL_INSANE_PERIODIC = 64554 , SPELL_SUMMON_GUARDIAN_YOGG = 62978 , SPELL_SHADOWY_BARRIER_YOGG = 63894 ,
SPELL_KNOCK_AWAY = 64022 , SPELL_MATCH_HEALTH = 64066 , SPELL_BRAIN_HURT_VISUAL = 64361 , SPELL_SHADOWY_BARRIER = 64775 ,
SPELL_FULL_HEAL = 43978 , SPELL_PHASE_2_TRANSFORM = 65157 , SPELL_RIDE_VEHICLE_YOGG = 61791 , SPELL_PHYCHOSIS = 63795 ,
SPELL_PHYCHOSIS_H = 65301 , SPELL_MALADY_OF_THE_MIND = 63830 , SPELL_BRAIN_LINK = 63802 , SPELL_DEATH_RAY_SUMMON = 63891 ,
SPELL_CONSTRICTOR_TENTACLE = 64132 , SPELL_CORRUPTOR_TENTACLE = 64143 , SPELL_CRUSHER_TENTACLE = 64139 , SPELL_TENTACLE_VOID_ZONE = 64384 ,
SPELL_ERUPT = 64144 , SPELL_LUNGE = 64131 , SPELL_TENTACLE_VOID_ZONE_BIG = 64017 , SPELL_CRUSH = 64146 ,
SPELL_DIMINISH_POWER = 64148 , SPELL_FOCUSED_ANGER = 57688 , SPELL_SQUEEZE = 64125 , SPELL_SQUEEZE_H = 64126 ,
SPELL_LUNATIC_GAZE_SKULL = 64167 , SPELL_NONDESCRIPT_ARMOR = 64013 , SPELL_NONDESCRIPT_CREATURE = 64010 , SPELL_GRIM_REPRISAL = 63305 ,
SPELL_SHATTERED_ILLUSION = 64173 , SPELL_SHATTERED_ILLUSION_REMOVE = 65238 , SPELL_INDUCE_MADNESS = 64059 , SPELL_LUNATIC_GAZE_YOGG = 64163 ,
SPELL_SHADOW_BEACON = 64465 , SPELL_DEAFENING_ROAR = 64189 , SPELL_IMMORTAL_GUARDIAN = 64158 , SPELL_DEATH_RAY_TRIGG = 63883 ,
SPELL_DEATH_RAY_VISUAL_WARN = 63882 , SPELL_DEATH_RAY_VISUAL_DAMAGE = 63886 , SPELL_DEATH_RAY_VISUAL_ORIGIN = 63893 , SPELL_TELEPORT_PORTAL_VISUAL = 64416 ,
SPELL_TELEPORT_TO_STORMWIND_ILLUSION = 63989 , SPELL_TELEPORT_TO_CHAMBER_ILLUSION = 63997 , SPELL_TELEPORT_TO_ICEECROWN_ILLUSION = 63998 , SPELL_EMPOWERED = 64161 ,
SPELL_EMPOWERED_MOD = 65294 , SPELL_RECENTLY_SPAWNED = 64497 , SPELL_SIMPLE_TELEPORT = 64195 , SPELL_DRAIN_LIFE = 64159 ,
SPELL_DRAIN_LIFE_H = 64160 , SPELL_WEAKENED = 64162 , NPC_DEATH_RAY = 33881 , NPC_DEATH_ORB = 33882 ,
NPC_CONSTRICTOR_TENTACLE = 33983 , NPC_CRUSHER_TENTACLE = 33966 , NPC_CORRUPTOR_TENTACLE = 33985 , NPC_DESCEND_INTO_MADNESS = 34072 ,
NPC_IMMORTAL_GUARDIAN = 33988 , NPC_LAUGHING_SKULL = 33990 , NPC_INFLUENCE_TENTACLE = 33943 , NPC_RUBY_CONSORT = 33716 ,
NPC_AZURE_CONSORT = 33717 , NPC_EMERALD_CONSORT = 33719 , NPC_OBSIDIAN_CONSORT = 33720 , NPC_SUIT_OF_ARMOR = 33433 ,
SPELL_ASSASSINATE = 64063 , NPC_DEATHSWORM_ZEALOT = 33567 , SPELL_DEATHGRASP = 63037 , SPELL_RESILIENCE_OF_NATURE = 62670 ,
SPELL_SUMMON_SANITY_WELL = 64170 , SPELL_FORTITUDE_OF_FROST = 62650 , SPELL_HODIRS_PROTECTIVE_GAZE = 64174 , SPELL_SPEED_OF_INVENTION = 62671 ,
SPELL_DESTABILIZATION_MATRIX = 65206 , SPELL_FURY_OF_THE_STORM = 62702 , SPELL_TITANIC_STORM = 64171 , FACTION_SARA_HOSTILE = 16 ,
MAX_ILLUSIONS = 3 , PHASE_INTRO = 0 , PHASE_SARA = 1 , PHASE_VISIONS = 2 ,
PHASE_OLD_GOD = 3 , PHASE_TRANSITION = 4
}
Functions
UnitAI * GetAI_boss_sara (Creature *pCreature)
UnitAI * GetAI_boss_yogg_saron (Creature *pCreature)
UnitAI * GetAI_npc_voice_yogg_saron (Creature *pCreature)
UnitAI * GetAI_npc_brain_yogg_saron (Creature *pCreature)
UnitAI * GetAI_npc_guardian_of_yogg (Creature *pCreature)
UnitAI * GetAI_npc_immortal_guardian (Creature *pCreature)
bool EffectDummyCreature_npc_immortal_guardian (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_constrictor_tentacle (Creature *pCreature)
UnitAI * GetAI_npc_ominous_cloud (Creature *pCreature)
UnitAI * GetAI_npc_death_ray (Creature *pCreature)
UnitAI * GetAI_npc_descent_madness (Creature *pCreature)
bool NpcSpellClick_npc_descent_madness (Player *pPlayer, Creature *pClickedCreature, uint32)
UnitAI * GetAI_npc_keeper_mimiron (Creature *pCreature)
UnitAI * GetAI_npc_keeper_thorim (Creature *pCreature)
void AddSC_boss_yogg_saron ()
Variables
static const DialogueEntry aYoggSaronDialog []
static const DialogueEntry aYoggIllusionsDialog []
static const float afYoggSaronSpawn [4] = {1980.43f, -25.7708f, 324.9724f, 3.141f}
static const uint32 aMadnessTeleportSpells [MAX_ILLUSIONS] = { SPELL_TELEPORT_TO_STORMWIND_ILLUSION, SPELL_TELEPORT_TO_CHAMBER_ILLUSION, SPELL_TELEPORT_TO_ICEECROWN_ILLUSION }
static const uint32 aMadnessChamberDoors [MAX_ILLUSIONS] = { GO_BRAIN_DOOR_STORMWIND, GO_BRAIN_DOOR_CHAMBER, GO_BRAIN_DOOR_ICECROWN }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SARA_INTRO_1
SAY_SARA_INTRO_2
SAY_SARA_AGGRO
SAY_SARA_HELP_1
SAY_SARA_HELP_2
SAY_SARA_SLAY_1
SAY_SARA_SLAY_2
SAY_WIPE_PHASE_1
SAY_PHASE_2_INTRO_1
SAY_PHASE_2_INTRO_2
SAY_PHASE_2_INTRO_3
SAY_PHASE_2_INTRO_4
SAY_PHASE_2_INTRO_5
SAY_SARA_PHYCHOSIS
SAY_SARA_DEATH_RAY
SAY_MADNESS
SAY_PHASE_3
SAY_SLAY
SAY_DEATH
SAY_TO_INSANE_1
SAY_TO_INSANE_2
SOUND_ID_LUNATIC_GAZE
SAY_LICH_KING_1
SAY_CHAMPION_1
SAY_CHAMPION_2
SAY_LICH_KING_2
SAY_YOGG_V3_1
SAY_YOGG_V3_2
SAY_NELTHARION_1
SAY_YSERA
SAY_NELTHARION_2
SAY_MALYGOS
SAY_YOGG_V2
SAY_GARONA_1
SAY_GARONA_2
SAY_GARONA_3
SAY_YOGG_V1_1
SAY_YOGG_V1_2
SAY_KING_LLANE
SAY_GARONA_4
SAY_YOGG_V1_3
EMOTE_VISION_BLAST
EMOTE_SHATTER_BLAST
EMOTE_CLOUD_BOIL
EMOTE_DEAFENING_ROAR
EMOTE_EMPOWERING_SHADOWS
SPELL_EXTINGUISH_LIFE
SPELL_SARAS_FERVOR
SPELL_SARAS_BLESSING
SPELL_SARAS_ANGER
SPELL_BOIL_OMNIOUSLY
SPELL_SHADOW_NOVA
SPELL_SHADOW_NOVA_H
SPELL_DARK_VOLLEY
SPELL_DOMINATE_MIND
SPELL_SANITY
SPELL_INSANE
SPELL_INSANE_PERIODIC
SPELL_SUMMON_GUARDIAN_YOGG
SPELL_SHADOWY_BARRIER_YOGG
SPELL_KNOCK_AWAY
SPELL_MATCH_HEALTH
SPELL_BRAIN_HURT_VISUAL
SPELL_SHADOWY_BARRIER
SPELL_FULL_HEAL
SPELL_PHASE_2_TRANSFORM
SPELL_RIDE_VEHICLE_YOGG
SPELL_PHYCHOSIS
SPELL_PHYCHOSIS_H
SPELL_MALADY_OF_THE_MIND
SPELL_BRAIN_LINK
SPELL_DEATH_RAY_SUMMON
SPELL_CONSTRICTOR_TENTACLE
SPELL_CORRUPTOR_TENTACLE
SPELL_CRUSHER_TENTACLE
SPELL_TENTACLE_VOID_ZONE
SPELL_ERUPT
SPELL_LUNGE
SPELL_TENTACLE_VOID_ZONE_BIG
SPELL_CRUSH
SPELL_DIMINISH_POWER
SPELL_FOCUSED_ANGER
SPELL_SQUEEZE
SPELL_SQUEEZE_H
SPELL_LUNATIC_GAZE_SKULL
SPELL_NONDESCRIPT_ARMOR
SPELL_NONDESCRIPT_CREATURE
SPELL_GRIM_REPRISAL
SPELL_SHATTERED_ILLUSION
SPELL_SHATTERED_ILLUSION_REMOVE
SPELL_INDUCE_MADNESS
SPELL_LUNATIC_GAZE_YOGG
SPELL_SHADOW_BEACON
SPELL_DEAFENING_ROAR
SPELL_IMMORTAL_GUARDIAN
SPELL_DEATH_RAY_TRIGG
SPELL_DEATH_RAY_VISUAL_WARN
SPELL_DEATH_RAY_VISUAL_DAMAGE
SPELL_DEATH_RAY_VISUAL_ORIGIN
SPELL_TELEPORT_PORTAL_VISUAL
SPELL_TELEPORT_TO_STORMWIND_ILLUSION
SPELL_TELEPORT_TO_CHAMBER_ILLUSION
SPELL_TELEPORT_TO_ICEECROWN_ILLUSION
SPELL_EMPOWERED
SPELL_EMPOWERED_MOD
SPELL_RECENTLY_SPAWNED
SPELL_SIMPLE_TELEPORT
SPELL_DRAIN_LIFE
SPELL_DRAIN_LIFE_H
SPELL_WEAKENED
NPC_DEATH_RAY
NPC_DEATH_ORB
NPC_CONSTRICTOR_TENTACLE
NPC_CRUSHER_TENTACLE
NPC_CORRUPTOR_TENTACLE
NPC_DESCEND_INTO_MADNESS
NPC_IMMORTAL_GUARDIAN
NPC_LAUGHING_SKULL
NPC_INFLUENCE_TENTACLE
NPC_RUBY_CONSORT
NPC_AZURE_CONSORT
NPC_EMERALD_CONSORT
NPC_OBSIDIAN_CONSORT
NPC_SUIT_OF_ARMOR
SPELL_ASSASSINATE
NPC_DEATHSWORM_ZEALOT
SPELL_DEATHGRASP
SPELL_RESILIENCE_OF_NATURE
SPELL_SUMMON_SANITY_WELL
SPELL_FORTITUDE_OF_FROST
SPELL_HODIRS_PROTECTIVE_GAZE
SPELL_SPEED_OF_INVENTION
SPELL_DESTABILIZATION_MATRIX
SPELL_FURY_OF_THE_STORM
SPELL_TITANIC_STORM
FACTION_SARA_HOSTILE
MAX_ILLUSIONS
PHASE_INTRO
PHASE_SARA
PHASE_VISIONS
PHASE_OLD_GOD
PHASE_TRANSITION
Definition at line 29 of file boss_yogg_saron.cpp.
Function Documentation
AddSC_boss_yogg_saron()
void AddSC_boss_yogg_saron ()
Definition at line 1680 of file boss_yogg_saron.cpp.
References EffectDummyCreature_npc_immortal_guardian(), Script::GetAI, GetAI_boss_sara(), GetAI_boss_yogg_saron(), GetAI_npc_brain_yogg_saron(), GetAI_npc_constrictor_tentacle(), GetAI_npc_death_ray(), GetAI_npc_descent_madness(), GetAI_npc_guardian_of_yogg(), GetAI_npc_immortal_guardian(), GetAI_npc_keeper_mimiron(), GetAI_npc_keeper_thorim(), GetAI_npc_ominous_cloud(), GetAI_npc_voice_yogg_saron(), Script::Name, NpcSpellClick_npc_descent_madness(), Script::pEffectDummyNPC, Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_immortal_guardian()
bool EffectDummyCreature_npc_immortal_guardian (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 1380 of file boss_yogg_saron.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), Unit::GetHealthPercent(), Unit::GetSpellAuraHolder(), NPC_IMMORTAL_GUARDIAN, Unit::RemoveAuraHolderFromStack(), Unit::RemoveAurasDueToSpell(), SPELL_EMPOWERED, SPELL_EMPOWERED_MOD, SPELL_WEAKENED, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_yogg_saron().
GetAI_boss_sara()
UnitAI* GetAI_boss_sara (Creature * pCreature)
Definition at line 599 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_boss_yogg_saron()
UnitAI* GetAI_boss_yogg_saron (Creature * pCreature)
Definition at line 737 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_brain_yogg_saron()
UnitAI* GetAI_npc_brain_yogg_saron (Creature * pCreature)
Definition at line 1213 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_constrictor_tentacle()
UnitAI* GetAI_npc_constrictor_tentacle (Creature * pCreature)
Definition at line 1435 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_death_ray()
UnitAI* GetAI_npc_death_ray (Creature * pCreature)
Definition at line 1535 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_descent_madness()
UnitAI* GetAI_npc_descent_madness (Creature * pCreature)
Definition at line 1565 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_guardian_of_yogg()
UnitAI* GetAI_npc_guardian_of_yogg (Creature * pCreature)
Definition at line 1309 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_immortal_guardian()
UnitAI* GetAI_npc_immortal_guardian (Creature * pCreature)
Definition at line 1375 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_keeper_mimiron()
UnitAI* GetAI_npc_keeper_mimiron (Creature * pCreature)
Definition at line 1628 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_keeper_thorim()
UnitAI* GetAI_npc_keeper_thorim (Creature * pCreature)
Definition at line 1648 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_ominous_cloud()
UnitAI* GetAI_npc_ominous_cloud (Creature * pCreature)
Definition at line 1493 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
GetAI_npc_voice_yogg_saron()
UnitAI* GetAI_npc_voice_yogg_saron (Creature * pCreature)
Definition at line 976 of file boss_yogg_saron.cpp.
Referenced by AddSC_boss_yogg_saron().
NpcSpellClick_npc_descent_madness()
bool NpcSpellClick_npc_descent_madness (Player * pPlayer, Creature * pClickedCreature, uint32)
Definition at line 1570 of file boss_yogg_saron.cpp.
References Creature::AI(), Unit::CastSpell(), Creature::ForcedDespawn(), Object::GetEntry(), NPC_DESCEND_INTO_MADNESS, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_yogg_saron().
Variable Documentation
afYoggSaronSpawn
const float afYoggSaronSpawn[4] = {1980.43f, -25.7708f, 324.9724f, 3.141f} static
Definition at line 294 of file boss_yogg_saron.cpp.
Referenced by boss_saraAI::JustDidDialogueStep().
aMadnessChamberDoors
const uint32 aMadnessChamberDoors[MAX_ILLUSIONS] = { GO_BRAIN_DOOR_STORMWIND, GO_BRAIN_DOOR_CHAMBER, GO_BRAIN_DOOR_ICECROWN } static
Definition at line 296 of file boss_yogg_saron.cpp.
Referenced by npc_brain_yogg_saronAI::SummonedCreatureJustDied().
aMadnessTeleportSpells
const uint32 aMadnessTeleportSpells[MAX_ILLUSIONS] = { SPELL_TELEPORT_TO_STORMWIND_ILLUSION, SPELL_TELEPORT_TO_CHAMBER_ILLUSION, SPELL_TELEPORT_TO_ICEECROWN_ILLUSION } static
Definition at line 295 of file boss_yogg_saron.cpp.
Referenced by npc_voice_yogg_saronAI::JustSummoned().
aYoggIllusionsDialog
const DialogueEntry aYoggIllusionsDialog[] static
Initial value:
=
{
    {NPC_KING_LLANE,    0,                      10000},
    {SAY_GARONA_1,      NPC_GARONA,             2000},
    {SAY_GARONA_2,      NPC_GARONA,             8000},
    {SAY_GARONA_3,      NPC_GARONA,             12000},
    {SAY_YOGG_V1_1,     NPC_YOGGSARON_ILLUSION, 4000},
    {SAY_YOGG_V1_2,     NPC_YOGGSARON_ILLUSION, 4000},
    {SAY_KING_LLANE,    NPC_KING_LLANE,         12000},
    {SAY_GARONA_4,      NPC_GARONA,             2000},
    {SPELL_ASSASSINATE, 0,                      4000},
    {SAY_YOGG_V1_3,     NPC_YOGGSARON_ILLUSION, 0},
    {NPC_NELTHARION,    0,                      10000},
    {SAY_NELTHARION_1,  NPC_NELTHARION,         10000},
    {SAY_YSERA,         NPC_YSERA,              7000},
    {SAY_NELTHARION_2,  NPC_NELTHARION,         6000},
    {SAY_MALYGOS,       NPC_MALYGOS,            9000},
    {SAY_YOGG_V2,       NPC_YOGGSARON_ILLUSION, 0},
    {NPC_LICH_KING,     0,                      10000},
    {SAY_LICH_KING_1,   NPC_LICH_KING,          5000},
    {SAY_CHAMPION_1,    NPC_IMMOLATED_CHAMPION, 8000},
    {SAY_CHAMPION_2,    NPC_IMMOLATED_CHAMPION, 8000},
    {SAY_LICH_KING_2,   NPC_LICH_KING,          7000},
    {SAY_YOGG_V3_1,     NPC_YOGGSARON_ILLUSION, 5000},
    {SAY_YOGG_V3_2,     NPC_YOGGSARON_ILLUSION, 0},
    {0, 0, 0},
}
Definition at line 263 of file boss_yogg_saron.cpp.
aYoggSaronDialog
const DialogueEntry aYoggSaronDialog[] static
Initial value:
=
{
    {SAY_PHASE_2_INTRO_1,       NPC_SARA,       4000},
    {SAY_PHASE_2_INTRO_2,       NPC_SARA,       5000},
    {SAY_PHASE_2_INTRO_3,       NPC_SARA,       5000},
    {SAY_PHASE_2_INTRO_4,       NPC_SARA,       1000},
    {SPELL_PHASE_2_TRANSFORM,   0,              3000},
    {SAY_PHASE_2_INTRO_5,       NPC_YOGGSARON,  0},
    {0, 0, 0},
}
Definition at line 252 of file boss_yogg_saron.cpp.