CMaNGOS_WoTLK: boss_ossirian.cpp File Reference
boss_ossirian.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ruins_of_ahnqiraj.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Globals/ObjectMgr.h"
Data Structures
struct boss_ossirianAI
Enumerations
enum {
SAY_SUPREME_1 = -1509018 , SAY_SUPREME_2 = -1509019 , SAY_SUPREME_3 = -1509020 , SAY_RAND_INTRO_1 = -1509021 ,
SAY_RAND_INTRO_2 = -1509023 , SAY_RAND_INTRO_3 = -1509024 , SAY_AGGRO = -1509025 , SAY_SLAY = 11450 ,
SAY_DEATH = -1509027 , SPELL_CURSE_OF_TONGUES = 25195 , SPELL_CYCLONE = 25189 , SPELL_STOMP = 25188 ,
SPELL_SUPREME = 25176 , SPELL_SUMMON_CRYSTAL = 25192 , SPELL_SAND_STORM = 25160 , SPELL_SUMMON = 20477 ,
SPELL_DOUBLE_ATTACK = 19818 , MAX_CRYSTAL_POSITIONS = 1 , SPELL_WEAKNESS_FIRE = 25177 , SPELL_WEAKNESS_FROST = 25178 ,
SPELL_WEAKNESS_NATURE = 25180 , SPELL_WEAKNESS_ARCANE = 25181 , SPELL_WEAKNESS_SHADOW = 25183 , NPC_SAND_VORTEX = 15428 ,
ZONE_ID_RUINS_AQ = 3429
}
enum OssirianActions {
OSSIRIAN_INITIAL_SPAWN , OSSIRIAN_SUPREME , OSSIRIAN_CYCLONE , OSSIRIAN_STOMP ,
OSSIRIAN_CURSE_OF_TONGUES , OSSIRIAN_SPEEDUP , OSSIRIAN_ACTION_MAX
}
Functions
bool GOUse_go_ossirian_crystal (Player *, GameObject *go)
void AddSC_boss_ossirian ()
Variables
static const float aSandVortexSpawnPos [2][4]
static const float aCrystalSpawnPos [3] = { -9355.75f, 1905.43f, 85.55f}
static const std::vector< uint32 > aWeaknessSpell {SPELL_WEAKNESS_FIRE, SPELL_WEAKNESS_FROST, SPELL_WEAKNESS_NATURE, SPELL_WEAKNESS_ARCANE, SPELL_WEAKNESS_SHADOW}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SUPREME_1
SAY_SUPREME_2
SAY_SUPREME_3
SAY_RAND_INTRO_1
SAY_RAND_INTRO_2
SAY_RAND_INTRO_3
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SPELL_CURSE_OF_TONGUES
SPELL_CYCLONE
SPELL_STOMP
SPELL_SUPREME
SPELL_SUMMON_CRYSTAL
SPELL_SAND_STORM
SPELL_SUMMON
SPELL_DOUBLE_ATTACK
MAX_CRYSTAL_POSITIONS
SPELL_WEAKNESS_FIRE
SPELL_WEAKNESS_FROST
SPELL_WEAKNESS_NATURE
SPELL_WEAKNESS_ARCANE
SPELL_WEAKNESS_SHADOW
NPC_SAND_VORTEX
ZONE_ID_RUINS_AQ
Definition at line 29 of file boss_ossirian.cpp.
OssirianActions
enum OssirianActions
Enumerator
OSSIRIAN_INITIAL_SPAWN
OSSIRIAN_SUPREME
OSSIRIAN_CYCLONE
OSSIRIAN_STOMP
OSSIRIAN_CURSE_OF_TONGUES
OSSIRIAN_SPEEDUP
OSSIRIAN_ACTION_MAX
Definition at line 72 of file boss_ossirian.cpp.
Function Documentation
AddSC_boss_ossirian()
void AddSC_boss_ossirian ()
Definition at line 311 of file boss_ossirian.cpp.
References Script::GetAI, GOUse_go_ossirian_crystal(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_ossirian_crystal()
bool GOUse_go_ossirian_crystal (Player * , GameObject * go)
Definition at line 302 of file boss_ossirian.cpp.
References aWeaknessSpell, GetClosestCreatureWithEntry(), Object::GetObjectGuid(), NPC_OSSIRIAN_TRIGGER, WorldObject::SendGameObjectCustomAnim(), TRIGGERED_NONE, and urand().
Referenced by AddSC_boss_ossirian().
Variable Documentation
aCrystalSpawnPos
const float aCrystalSpawnPos[3] = { -9355.75f, 1905.43f, 85.55f} static
Definition at line 69 of file boss_ossirian.cpp.
Referenced by boss_ossirianAI::JustSummoned().
aSandVortexSpawnPos
const float aSandVortexSpawnPos[2][4] static
Initial value:
=
{
    { -9523.482f, 1880.435f, 85.645f, 5.08f},
    { -9321.39f,  1822.968f, 84.266f, 3.16f},
}
Definition at line 63 of file boss_ossirian.cpp.
Referenced by boss_ossirianAI::Aggro().
aWeaknessSpell
const std::vector<uint32> aWeaknessSpell {SPELL_WEAKNESS_FIRE, SPELL_WEAKNESS_FROST, SPELL_WEAKNESS_NATURE, SPELL_WEAKNESS_ARCANE, SPELL_WEAKNESS_SHADOW} static
Definition at line 70 of file boss_ossirian.cpp.
Referenced by GOUse_go_ossirian_crystal(), and boss_ossirianAI::SpellHit().