CMaNGOS_WoTLK: boss_victor_nefarius.cpp File Reference
boss_victor_nefarius.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackwing_lair.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_victor_nefariusAI
Enumerations
enum {
SAY_GAMESBEGIN_1 = -1469004 , SAY_GAMESBEGIN_2 = -1469005 , GOSSIP_ITEM_NEFARIUS_1 = -3469000 , GOSSIP_ITEM_NEFARIUS_2 = -3469001 ,
GOSSIP_ITEM_NEFARIUS_3 = -3469002 , GOSSIP_TEXT_NEFARIUS_1 = 7134 , GOSSIP_TEXT_NEFARIUS_2 = 7198 , GOSSIP_TEXT_NEFARIUS_3 = 7199 ,
SPELL_NEFARIUS_BARRIER = 22663 , SPELL_SHADOWBLINK = 22664 , SPELL_SHADOWBOLT_VOLLEY = 22665 , SPELL_SILENCE = 22666 ,
SPELL_SHADOW_COMMAND = 22667 , SPELL_SHADOWBOLT = 22677 , SPELL_FEAR = 22678 , SPELL_TUNNEL_SELECTION = 23343 ,
MAP_ID_BWL = 469 , FACTION_BLACK_DRAGON = 103
}
enum VictorNefariusActions {
NEFARIUS_SHADOW_BOLT , NEFARIUS_FEAR , NEFARIUS_SHADOWBOLT_VOLLEY , NEFARIUS_SILENCE ,
NEFARIUS_SHADOW_COMMAND , NEFARIUS_SHADOW_BLINK , NEFARIUS_ACTION_MAX
}
Functions
bool GossipHello_boss_victor_nefarius (Player *player, Creature *creature)
bool GossipSelect_boss_victor_nefarius (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_boss_victor_nefarius ()
Variables
static const DialogueEntry aIntroDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GAMESBEGIN_1
SAY_GAMESBEGIN_2
GOSSIP_ITEM_NEFARIUS_1
GOSSIP_ITEM_NEFARIUS_2
GOSSIP_ITEM_NEFARIUS_3
GOSSIP_TEXT_NEFARIUS_1
GOSSIP_TEXT_NEFARIUS_2
GOSSIP_TEXT_NEFARIUS_3
SPELL_NEFARIUS_BARRIER
SPELL_SHADOWBLINK
SPELL_SHADOWBOLT_VOLLEY
SPELL_SILENCE
SPELL_SHADOW_COMMAND
SPELL_SHADOWBOLT
SPELL_FEAR
SPELL_TUNNEL_SELECTION
MAP_ID_BWL
FACTION_BLACK_DRAGON
Definition at line 28 of file boss_victor_nefarius.cpp.
VictorNefariusActions
enum VictorNefariusActions
Enumerator
NEFARIUS_SHADOW_BOLT
NEFARIUS_FEAR
NEFARIUS_SHADOWBOLT_VOLLEY
NEFARIUS_SILENCE
NEFARIUS_SHADOW_COMMAND
NEFARIUS_SHADOW_BLINK
NEFARIUS_ACTION_MAX
Definition at line 63 of file boss_victor_nefarius.cpp.
Function Documentation
AddSC_boss_victor_nefarius()
void AddSC_boss_victor_nefarius ()
Definition at line 242 of file boss_victor_nefarius.cpp.
References Script::GetAI, GossipHello_boss_victor_nefarius(), GossipSelect_boss_victor_nefarius(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_boss_victor_nefarius()
bool GossipHello_boss_victor_nefarius (Player * player, Creature * creature)
Definition at line 204 of file boss_victor_nefarius.cpp.
References WorldObject::GetMapId(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NEFARIUS_1, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_NEFARIUS_1, and MAP_ID_BWL.
Referenced by AddSC_boss_victor_nefarius().
GossipSelect_boss_victor_nefarius()
bool GossipSelect_boss_victor_nefarius (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 214 of file boss_victor_nefarius.cpp.
References Creature::AI(), EMOTE_ONESHOT_TALK, WorldObject::GetMapId(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NEFARIUS_2, GOSSIP_ITEM_NEFARIUS_3, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_NEFARIUS_2, GOSSIP_TEXT_NEFARIUS_3, Unit::HandleEmote(), MAP_ID_BWL, Object::RemoveFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_boss_victor_nefarius().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_GAMESBEGIN_1,    NPC_LORD_VICTOR_NEFARIUS,     4000},
    {SAY_GAMESBEGIN_2,    NPC_LORD_VICTOR_NEFARIUS,     5000},
    {SPELL_SHADOWBLINK,   0,                            0},
    {0, 0, 0},
}
Definition at line 55 of file boss_victor_nefarius.cpp.