CMaNGOS_WoTLK: boss_volazj.cpp File Reference
boss_volazj.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ahnkahet.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct boss_volazjAI
Enumerations
enum {
SAY_AGGRO = -1619033 , SAY_INSANITY = -1619034 , SAY_SLAY_1 = -1619035 , SAY_SLAY_2 = -1619036 ,
SAY_SLAY_3 = -1619037 , SAY_DEATH_1 = -1619038 , SAY_DEATH_2 = -1619039 , SPELL_MIND_FLAY = 57941 ,
SPELL_MIND_FLAY_H = 59974 , SPELL_SHADOW_BOLT = 57942 , SPELL_SHADOW_BOLT_H = 59975 , SPELL_SHIVER = 57949 ,
SPELL_SHIVER_H = 59978 , SPELL_WHISPER_AGGRO = 60291 , SPELL_WHISPER_INSANITY = 60292 , SPELL_WHISPER_SLAY_1 = 60293 ,
SPELL_WHISPER_SLAY_2 = 60294 , SPELL_WHISPER_SLAY_3 = 60295 , SPELL_WHISPER_DEATH_1 = 60296 , SPELL_WHISPER_DEATH_2 = 60297 ,
SPELL_INSANITY = 57496 , SPELL_INSANITY_VISUAL = 57561 , SPELL_TWISTED_VISAGE_SPAWN = 57506 , SPELL_TWISTED_VISAGE_SPAWN_H = 59982 ,
SPELL_TWISTED_VISAGE_EFFECT = 57507 , SPELL_TWISTED_VISAGE_PASSIVE = 57551 , SPELL_SUMMON_VISAGE_1 = 57500 , SPELL_SUMMON_VISAGE_2 = 57501 ,
SPELL_SUMMON_VISAGE_3 = 57502 , SPELL_SUMMON_VISAGE_4 = 57503 , SPELL_SUMMON_VISAGE_5 = 57504 , MAX_INSANITY_SPELLS = 5
}
Functions
UnitAI * GetAI_boss_volazj (Creature *pCreature)
void AddSC_boss_volazj ()
Variables
static const uint32 aInsanityPhaseSpells [MAX_INSANITY_SPELLS] = {SPELL_INSANITY_PHASE_16, SPELL_INSANITY_PHASE_32, SPELL_INSANITY_PHASE_64, SPELL_INSANITY_PHASE_128, SPELL_INSANITY_PHASE_256}
static const uint32 aSpawnVisageSpells [MAX_INSANITY_SPELLS] = {SPELL_SUMMON_VISAGE_1, SPELL_SUMMON_VISAGE_2, SPELL_SUMMON_VISAGE_3, SPELL_SUMMON_VISAGE_4, SPELL_SUMMON_VISAGE_5}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_INSANITY
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH_1
SAY_DEATH_2
SPELL_MIND_FLAY
SPELL_MIND_FLAY_H
SPELL_SHADOW_BOLT
SPELL_SHADOW_BOLT_H
SPELL_SHIVER
SPELL_SHIVER_H
SPELL_WHISPER_AGGRO
SPELL_WHISPER_INSANITY
SPELL_WHISPER_SLAY_1
SPELL_WHISPER_SLAY_2
SPELL_WHISPER_SLAY_3
SPELL_WHISPER_DEATH_1
SPELL_WHISPER_DEATH_2
SPELL_INSANITY
SPELL_INSANITY_VISUAL
SPELL_TWISTED_VISAGE_SPAWN
SPELL_TWISTED_VISAGE_SPAWN_H
SPELL_TWISTED_VISAGE_EFFECT
SPELL_TWISTED_VISAGE_PASSIVE
SPELL_SUMMON_VISAGE_1
SPELL_SUMMON_VISAGE_2
SPELL_SUMMON_VISAGE_3
SPELL_SUMMON_VISAGE_4
SPELL_SUMMON_VISAGE_5
MAX_INSANITY_SPELLS
Definition at line 28 of file boss_volazj.cpp.
Function Documentation
AddSC_boss_volazj()
void AddSC_boss_volazj ()
Definition at line 290 of file boss_volazj.cpp.
References Script::GetAI, GetAI_boss_volazj(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_volazj()
UnitAI* GetAI_boss_volazj (Creature * pCreature)
Definition at line 285 of file boss_volazj.cpp.
Referenced by AddSC_boss_volazj().
Variable Documentation
aInsanityPhaseSpells
const uint32 aInsanityPhaseSpells[MAX_INSANITY_SPELLS] = {SPELL_INSANITY_PHASE_16, SPELL_INSANITY_PHASE_32, SPELL_INSANITY_PHASE_64, SPELL_INSANITY_PHASE_128, SPELL_INSANITY_PHASE_256} static
Definition at line 70 of file boss_volazj.cpp.
Referenced by boss_volazjAI::SpellHitTarget().
aSpawnVisageSpells
const uint32 aSpawnVisageSpells[MAX_INSANITY_SPELLS] = {SPELL_SUMMON_VISAGE_1, SPELL_SUMMON_VISAGE_2, SPELL_SUMMON_VISAGE_3, SPELL_SUMMON_VISAGE_4, SPELL_SUMMON_VISAGE_5} static
Definition at line 71 of file boss_volazj.cpp.
Referenced by boss_volazjAI::SpellHitTarget().