CMaNGOS_WoTLK: boss_dathrohan_balnazzar.cpp File Reference
boss_dathrohan_balnazzar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "stratholme.h"
Data Structures
struct boss_dathrohan_balnazzarAI
Enumerations
enum {
SAY_AGGRO = -1329016 , SAY_TRANSFORM = -1329017 , SAY_DEATH = -1329018 , SPELL_CRUSADERSHAMMER = 17286 ,
SPELL_CRUSADERSTRIKE = 17281 , SPELL_HOLYSTRIKE = 17284 , SPELL_BALNAZZARTRANSFORM = 17288 , SPELL_SHADOWSHOCK = 17399 ,
SPELL_MINDBLAST = 17287 , SPELL_PSYCHICSCREAM = 13704 , SPELL_SLEEP = 12098 , SPELL_MINDCONTROL = 15690 ,
NPC_DATHROHAN = 10812
}
Functions
UnitAI * GetAI_boss_dathrohan_balnazzar (Creature *pCreature)
void AddSC_boss_dathrohan_balnazzar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_TRANSFORM
SAY_DEATH
SPELL_CRUSADERSHAMMER
SPELL_CRUSADERSTRIKE
SPELL_HOLYSTRIKE
SPELL_BALNAZZARTRANSFORM
SPELL_SHADOWSHOCK
SPELL_MINDBLAST
SPELL_PSYCHICSCREAM
SPELL_SLEEP
SPELL_MINDCONTROL
NPC_DATHROHAN
Definition at line 27 of file boss_dathrohan_balnazzar.cpp.
Function Documentation
AddSC_boss_dathrohan_balnazzar()
void AddSC_boss_dathrohan_balnazzar ()
Definition at line 202 of file boss_dathrohan_balnazzar.cpp.
References Script::GetAI, GetAI_boss_dathrohan_balnazzar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_dathrohan_balnazzar()
UnitAI* GetAI_boss_dathrohan_balnazzar (Creature * pCreature)
Definition at line 197 of file boss_dathrohan_balnazzar.cpp.
Referenced by AddSC_boss_dathrohan_balnazzar().