CMaNGOS_WoTLK: boss_general_vezax.cpp File Reference
boss_general_vezax.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_general_vezaxAI
struct npc_saronite_vaporAI
Enumerations
enum {
SAY_AGGRO = -1603096 , SAY_SLAY_1 = -1603097 , SAY_SLAY_2 = -1603098 , SAY_SURGE = -1603099 ,
SAY_DEATH = -1603100 , SAY_ENRAGE = -1603101 , SAY_HARD_MODE = -1603102 , EMOTE_VAPOR = -1603103 ,
EMOTE_SURGE = -1603104 , EMOTE_ANIMUS = -1603105 , SPELL_AURA_OF_DESPAIR = 62692 , SPELL_SHADOW_CRASH = 62660 ,
SPELL_SHADOW_CRASH_DAMAGE = 62659 , SPELL_MARK_OF_FACELESS = 63276 , SPELL_SEARING_FLAMES = 62661 , SPELL_SURGE_OF_DARKNESS = 62662 ,
SPELL_SUMMON_VAPORS = 63081 , SPELL_BERSERK = 26662 , SPELL_SARONITE_BARRIER = 63364 , SPELL_SUMMON_ANIMUS = 63145 ,
SPELL_ANIMUS_FORMATION = 63319 , SPELL_SARONITE_VAPORS = 63323 , SPELL_CORRUPTED_RAGE = 68415 , SPELL_CORRUPTED_WISDOM = 64646 ,
MAX_HARD_MODE_VAPORS = 6 , NPC_SARONITE_VAPOR = 33488
}
Functions
UnitAI * GetAI_boss_general_vezax (Creature *pCreature)
UnitAI * GetAI_npc_saronite_vapor (Creature *pCreature)
bool ProcessEventId_event_spell_saronite_barrier (uint32, Object *pSource, Object *, bool)
void AddSC_boss_general_vezax ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SURGE
SAY_DEATH
SAY_ENRAGE
SAY_HARD_MODE
EMOTE_VAPOR
EMOTE_SURGE
EMOTE_ANIMUS
SPELL_AURA_OF_DESPAIR
SPELL_SHADOW_CRASH
SPELL_SHADOW_CRASH_DAMAGE
SPELL_MARK_OF_FACELESS
SPELL_SEARING_FLAMES
SPELL_SURGE_OF_DARKNESS
SPELL_SUMMON_VAPORS
SPELL_BERSERK
SPELL_SARONITE_BARRIER
SPELL_SUMMON_ANIMUS
SPELL_ANIMUS_FORMATION
SPELL_SARONITE_VAPORS
SPELL_CORRUPTED_RAGE
SPELL_CORRUPTED_WISDOM
MAX_HARD_MODE_VAPORS
NPC_SARONITE_VAPOR
Definition at line 27 of file boss_general_vezax.cpp.
Function Documentation
AddSC_boss_general_vezax()
void AddSC_boss_general_vezax ()
Definition at line 413 of file boss_general_vezax.cpp.
References Script::GetAI, GetAI_boss_general_vezax(), GetAI_npc_saronite_vapor(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_saronite_barrier(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_general_vezax()
UnitAI* GetAI_boss_general_vezax (Creature * pCreature)
Definition at line 347 of file boss_general_vezax.cpp.
Referenced by AddSC_boss_general_vezax().
GetAI_npc_saronite_vapor()
UnitAI* GetAI_npc_saronite_vapor (Creature * pCreature)
Definition at line 394 of file boss_general_vezax.cpp.
Referenced by AddSC_boss_general_vezax().
ProcessEventId_event_spell_saronite_barrier()
bool ProcessEventId_event_spell_saronite_barrier (uint32 , Object * pSource, Object * , bool)
Definition at line 399 of file boss_general_vezax.cpp.
References Object::GetTypeId(), IN_PROGRESS, NPC_VEZAX, TYPE_VEZAX_HARD, and TYPEID_UNIT.
Referenced by AddSC_boss_general_vezax().