CMaNGOS_WoTLK: boss_mimiron.cpp File Reference
boss_mimiron.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_mimironAI
struct boss_leviathan_mk2AI
struct boss_vx001AI
struct boss_aerial_unitAI
struct npc_proximity_mineAI
struct npc_bot_triggerAI
struct npc_mimiron_flamesAI
struct npc_frost_bombAI
struct npc_rocket_strikeAI
struct boss_leviathan_mk2_turretAI
struct npc_computerAI
Enumerations
enum {
SAY_INTRO = -1603176 , SAY_HARD_MODE = -1603177 , SAY_BERSERK = -1603178 , SAY_TANK_ACTIVE = -1603179 ,
SAY_TANK_SLAY_1 = -1603180 , SAY_TANK_SLAY_2 = -1603181 , SAY_TANK_DEATH = -1603182 , SAY_TORSO_ACTIVE = -1603183 ,
SAY_TORSO_SLAY_1 = -1603184 , SAY_TORSO_SLAY_2 = -1603185 , SAY_TORSO_DEATH = -1603186 , SAY_HEAD_ACTIVE = -1603187 ,
SAY_HEAD_SLAY_1 = -1603188 , SAY_HEAD_SLAY_2 = -1603189 , SAY_HEAD_DEATH = -1603190 , SAY_ROBOT_ACTIVE = -1603191 ,
SAY_ROBOT_SLAY_1 = -1603192 , SAY_ROBOT_SLAY_2 = -1603193 , SAY_ROBOT_DEATH = -1603194 , EMOTE_PLASMA_BLAST = -1603196 ,
SAY_SELF_DESTRUCT = -1603248 , SAY_SELF_DESTRUCT_END = -1603260 , SAY_DESTRUCT_10_MIN = -1603249 , SAY_DESTRUCT_9_MIN = -1603250 ,
SAY_DESTRUCT_8_MIN = -1603251 , SAY_DESTRUCT_7_MIN = -1603252 , SAY_DESTRUCT_6_MIN = -1603253 , SAY_DESTRUCT_5_MIN = -1603254 ,
SAY_DESTRUCT_4_MIN = -1603255 , SAY_DESTRUCT_3_MIN = -1603256 , SAY_DESTRUCT_2_MIN = -1603257 , SAY_DESTRUCT_1_MIN = -1603258 ,
SAY_DESTRUCT_0_MIN = -1603259 , SPELL_WELD = 63339 , SPELL_TELEPORT_VISUAL = 41232 , SPELL_TELEPORT_VISUAL_2 = 64446 ,
SPELL_RIDE_VEHICLE_MIMIRON_0 = 52391 , SPELL_RIDE_VEHICLE_MIMIRON_1 = 63313 , SPELL_RIDE_VEHICLE_MIMIRON_2 = 63314 , SPELL_RIDE_VEHICLE_MIMIRON_3 = 63315 ,
SPELL_RIDE_VEHICLE_MIMIRON_4 = 63316 , SPELL_RIDE_VEHICLE_MIMIRON_5 = 63344 , SPELL_RIDE_VEHICLE_MIMIRON_6 = 63345 , SPELL_JET_PACK_VISUAL = 63307 ,
SPELL_JET_PACK = 63341 , SPELL_SLEEP_VISUAL = 64393 , SPELL_SLEEP_WAKE = 64394 , SPELL_NOT_FRIENDLY_FIRE = 65040 ,
SPELL_BERSERK = 26662 , SPELL_FREEZE_ANIM = 16245 , SPELL_SELF_REPAIR = 64383 , SPELL_HALF_HEAL = 64188 ,
SPELL_CLEAR_DEBUFFS = 34098 , SPELL_RIDE_VEHICLE_ROBOT_1 = 64387 , SPELL_RIDE_VEHICLE_ROBOT_2 = 64388 , SPELL_VEHICLE_DAMAGED = 63415 ,
SPELL_DESPAWN_ASSAULT_BOTS = 64463 , SPELL_PROXIMITY_MINES = 63027 , SPELL_NAPALM_SHELL = 64539 , SPELL_PLASMA_BLAST = 62997 ,
SPELL_PLASMA_BLAST_H = 64529 , SPELL_SHOCK_BLAST = 63631 , SPELL_FREEZE_ANIM_DEFEATED = 63354 , SPELL_FLAME_SUPPRESSANT = 64570 ,
SPELL_EMERGENCY_MODE_LEVIATHAN = 65101 , SPELL_RAPID_BURST_SUMMON = 64840 , SPELL_RAPID_BURST_EFFECT = 64841 , SPELL_RAPID_BURST_AURA = 63382 ,
SPELL_SPINNING_UP = 63414 , SPELL_ROCKET_STRIKE = 64402 , SPELL_HEAT_WAVE = 63679 , SPELL_HEAT_WAVE_H = 64534 ,
SPELL_HAND_PULSE_LEFT = 64348 , SPELL_HAND_PULSE_RIGHT = 64352 , SPELL_HAND_PULSE_LEFT_H = 64536 , SPELL_HAND_PULSE_RIGHT_H = 64537 ,
SPELL_TORSO_DISABLED = 64120 , SPELL_FLAME_SUPPRESSANT_CLOSE = 65192 , SPELL_FROST_BOMB_SUMMON = 64623 , SPELL_PLASMA_BALL_FLY = 63689 ,
SPELL_PLASMA_BALL_FLY_H = 64535 , SPELL_PLASMA_BALL = 65647 , SPELL_PLASMA_BALL_H = 65648 , SPELL_SUMMON_ASSAULT_BOT_TRIGGER = 64425 ,
SPELL_SUMMON_ASSAULT_BOT_VISUAL = 64426 , SPELL_SUMMON_ASSAULT_BOT = 64427 , SPELL_SUMMON_SCRAP_BOT_TRIGGER = 63820 , SPELL_SUMMON_SCRAP_BOT_VISUAL = 64398 ,
SPELL_SUMMON_SCRAP_BOT = 63819 , SPELL_BOMB_BOT_SUMMON = 63811 , SPELL_MAGNETIC_CORE_PULL = 64436 , SPELL_MAGNETIC_CORE_VISUAL = 64438 ,
SPELL_SUMMON_FIRE_BOT_TRIGGER = 64620 , SPELL_SUMMON_FIRE_BOT_VISUAL = 64621 , SPELL_SUMMON_FIRE_BOT = 64622 , SPELL_PROXIMITY_MINE = 65345 ,
SPELL_EXPLOSION = 66351 , SPELL_EXPLOSION_H = 63009 , SPELL_ROCKET_STRIKE_DAMAGE = 64064 , SPELL_SELF_DESTRUCTION = 64613 ,
SPELL_SELF_DESTRUCTION_DAMAGE = 64610 , SPELL_EMERGENCY_MODE = 64582 , SPELL_SUMMON_FLAMES_INITIAL = 64563 , SPELL_FLAMES = 64561 ,
SPELL_SUMMON_FLAMES_SPREAD = 64562 , SPELL_EXPLOSION_FROST = 64626 , SPELL_FROST_BOMB_VISUAL = 64624 , SPELL_CLEAR_FIRES = 65354 ,
NPC_PROXIMITY_MINE = 34362 , NPC_ROCKET_VISUAL = 34050 , NPC_ROCKET_STRIKE = 34047 , NPC_BURST_TARGET = 34211 ,
NPC_ASSALT_BOT = 34057 , NPC_BOMB_BOT = 33836 , NPC_MAGNETIC_CORE = 34068 , NPC_JUNK_BOT = 33855 ,
NPC_FROST_BOMB = 34149 , POINT_ID_PARK = 1 , POINT_ID_CENTER = 2 , SEAT_ID_TURRET = 4 ,
PHASE_INTRO = 0 , PHASE_LEVIATHAN = 1 , PHASE_VX001 = 2 , PHASE_AERIAL_UNIT = 3 ,
PHASE_FULL_ROBOT = 4 , PHASE_TRANSITION = 5 , PHASE_DAMAGED = 6
}
Functions
UnitAI * GetAI_boss_mimiron (Creature *pCreature)
UnitAI * GetAI_boss_leviathan_mk2 (Creature *pCreature)
UnitAI * GetAI_boss_vx001 (Creature *pCreature)
UnitAI * GetAI_boss_aerial_unit (Creature *pCreature)
UnitAI * GetAI_npc_proximity_mine (Creature *pCreature)
UnitAI * GetAI_npc_bot_trigger (Creature *pCreature)
bool EffectDummyCreature_npc_bot_trigger (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_mimiron_flames (Creature *pCreature)
UnitAI * GetAI_npc_frost_bomb (Creature *pCreature)
UnitAI * GetAI_npc_rocket_strike (Creature *pCreature)
UnitAI * GetAI_boss_leviathan_mk2_turret (Creature *pCreature)
UnitAI * GetAI_npc_computer (Creature *pCreature)
bool GOUse_go_big_red_button (Player *pPlayer, GameObject *pGo)
void AddSC_boss_mimiron ()
Variables
static const DialogueEntry aMimironDialogue []
static const uint32 aRandomAnimationSpells [] = {SPELL_RIDE_VEHICLE_MIMIRON_0, SPELL_RIDE_VEHICLE_MIMIRON_1, SPELL_RIDE_VEHICLE_MIMIRON_2, SPELL_RIDE_VEHICLE_MIMIRON_4}
static const uint32 aMimironTeleporters [] = {GO_MIMIRON_TEL1, GO_MIMIRON_TEL2, GO_MIMIRON_TEL3, GO_MIMIRON_TEL4, GO_MIMIRON_TEL5, GO_MIMIRON_TEL6, GO_MIMIRON_TEL7, GO_MIMIRON_TEL8, GO_MIMIRON_TEL9}
static const float afTankEvadePos [4] = {2792.07f, 2596.32f, 364.3136f, 3.5f}
static const float afRobotSpawnPos [4] = {2744.431f, 2569.385f, 364.3968f, 3.141f}
static const float afRocketSpawnPos [4] = {2746.262f, 2567.085f, 369.2921f, 3.14f}
static const float afAerialSpawnPos [4] = {2744.365f, 2569.303f, 392.2355f, 3.15f}
static const float afAerialMovePos [3] = {2743.32f, 2569.285f, 378.2812f}
static const float afTankMovePos [3] = {2763.82f, 2568.87f, 364.3136f}
static const float afCenterMovePos [3] = {2744.61f, 2569.38f, 364.3136f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_HARD_MODE
SAY_BERSERK
SAY_TANK_ACTIVE
SAY_TANK_SLAY_1
SAY_TANK_SLAY_2
SAY_TANK_DEATH
SAY_TORSO_ACTIVE
SAY_TORSO_SLAY_1
SAY_TORSO_SLAY_2
SAY_TORSO_DEATH
SAY_HEAD_ACTIVE
SAY_HEAD_SLAY_1
SAY_HEAD_SLAY_2
SAY_HEAD_DEATH
SAY_ROBOT_ACTIVE
SAY_ROBOT_SLAY_1
SAY_ROBOT_SLAY_2
SAY_ROBOT_DEATH
EMOTE_PLASMA_BLAST
SAY_SELF_DESTRUCT
SAY_SELF_DESTRUCT_END
SAY_DESTRUCT_10_MIN
SAY_DESTRUCT_9_MIN
SAY_DESTRUCT_8_MIN
SAY_DESTRUCT_7_MIN
SAY_DESTRUCT_6_MIN
SAY_DESTRUCT_5_MIN
SAY_DESTRUCT_4_MIN
SAY_DESTRUCT_3_MIN
SAY_DESTRUCT_2_MIN
SAY_DESTRUCT_1_MIN
SAY_DESTRUCT_0_MIN
SPELL_WELD
SPELL_TELEPORT_VISUAL
SPELL_TELEPORT_VISUAL_2
SPELL_RIDE_VEHICLE_MIMIRON_0
SPELL_RIDE_VEHICLE_MIMIRON_1
SPELL_RIDE_VEHICLE_MIMIRON_2
SPELL_RIDE_VEHICLE_MIMIRON_3
SPELL_RIDE_VEHICLE_MIMIRON_4
SPELL_RIDE_VEHICLE_MIMIRON_5
SPELL_RIDE_VEHICLE_MIMIRON_6
SPELL_JET_PACK_VISUAL
SPELL_JET_PACK
SPELL_SLEEP_VISUAL
SPELL_SLEEP_WAKE
SPELL_NOT_FRIENDLY_FIRE
SPELL_BERSERK
SPELL_FREEZE_ANIM
SPELL_SELF_REPAIR
SPELL_HALF_HEAL
SPELL_CLEAR_DEBUFFS
SPELL_RIDE_VEHICLE_ROBOT_1
SPELL_RIDE_VEHICLE_ROBOT_2
SPELL_VEHICLE_DAMAGED
SPELL_DESPAWN_ASSAULT_BOTS
SPELL_PROXIMITY_MINES
SPELL_NAPALM_SHELL
SPELL_PLASMA_BLAST
SPELL_PLASMA_BLAST_H
SPELL_SHOCK_BLAST
SPELL_FREEZE_ANIM_DEFEATED
SPELL_FLAME_SUPPRESSANT
SPELL_EMERGENCY_MODE_LEVIATHAN
SPELL_RAPID_BURST_SUMMON
SPELL_RAPID_BURST_EFFECT
SPELL_RAPID_BURST_AURA
SPELL_SPINNING_UP
SPELL_ROCKET_STRIKE
SPELL_HEAT_WAVE
SPELL_HEAT_WAVE_H
SPELL_HAND_PULSE_LEFT
SPELL_HAND_PULSE_RIGHT
SPELL_HAND_PULSE_LEFT_H
SPELL_HAND_PULSE_RIGHT_H
SPELL_TORSO_DISABLED
SPELL_FLAME_SUPPRESSANT_CLOSE
SPELL_FROST_BOMB_SUMMON
SPELL_PLASMA_BALL_FLY
SPELL_PLASMA_BALL_FLY_H
SPELL_PLASMA_BALL
SPELL_PLASMA_BALL_H
SPELL_SUMMON_ASSAULT_BOT_TRIGGER
SPELL_SUMMON_ASSAULT_BOT_VISUAL
SPELL_SUMMON_ASSAULT_BOT
SPELL_SUMMON_SCRAP_BOT_TRIGGER
SPELL_SUMMON_SCRAP_BOT_VISUAL
SPELL_SUMMON_SCRAP_BOT
SPELL_BOMB_BOT_SUMMON
SPELL_MAGNETIC_CORE_PULL
SPELL_MAGNETIC_CORE_VISUAL
SPELL_SUMMON_FIRE_BOT_TRIGGER
SPELL_SUMMON_FIRE_BOT_VISUAL
SPELL_SUMMON_FIRE_BOT
SPELL_PROXIMITY_MINE
SPELL_EXPLOSION
SPELL_EXPLOSION_H
SPELL_ROCKET_STRIKE_DAMAGE
SPELL_SELF_DESTRUCTION
SPELL_SELF_DESTRUCTION_DAMAGE
SPELL_EMERGENCY_MODE
SPELL_SUMMON_FLAMES_INITIAL
SPELL_FLAMES
SPELL_SUMMON_FLAMES_SPREAD
SPELL_EXPLOSION_FROST
SPELL_FROST_BOMB_VISUAL
SPELL_CLEAR_FIRES
NPC_PROXIMITY_MINE
NPC_ROCKET_VISUAL
NPC_ROCKET_STRIKE
NPC_BURST_TARGET
NPC_ASSALT_BOT
NPC_BOMB_BOT
NPC_MAGNETIC_CORE
NPC_JUNK_BOT
NPC_FROST_BOMB
POINT_ID_PARK
POINT_ID_CENTER
SEAT_ID_TURRET
PHASE_INTRO
PHASE_LEVIATHAN
PHASE_VX001
PHASE_AERIAL_UNIT
PHASE_FULL_ROBOT
PHASE_TRANSITION
PHASE_DAMAGED
Definition at line 27 of file boss_mimiron.cpp.
Function Documentation
AddSC_boss_mimiron()
void AddSC_boss_mimiron ()
Definition at line 2007 of file boss_mimiron.cpp.
References EffectDummyCreature_npc_bot_trigger(), Script::GetAI, GetAI_boss_aerial_unit(), GetAI_boss_leviathan_mk2(), GetAI_boss_leviathan_mk2_turret(), GetAI_boss_mimiron(), GetAI_boss_vx001(), GetAI_npc_bot_trigger(), GetAI_npc_computer(), GetAI_npc_frost_bomb(), GetAI_npc_mimiron_flames(), GetAI_npc_proximity_mine(), GetAI_npc_rocket_strike(), GOUse_go_big_red_button(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_bot_trigger()
bool EffectDummyCreature_npc_bot_trigger (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 1737 of file boss_mimiron.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, aMimironTeleporters, Unit::CastSpell(), EFFECT_INDEX_0, GetClosestGameObjectWithEntry(), UnitAI::SendAIEvent(), SPELL_SUMMON_ASSAULT_BOT, SPELL_SUMMON_ASSAULT_BOT_TRIGGER, SPELL_SUMMON_ASSAULT_BOT_VISUAL, SPELL_SUMMON_FIRE_BOT, SPELL_SUMMON_FIRE_BOT_TRIGGER, SPELL_SUMMON_FIRE_BOT_VISUAL, SPELL_SUMMON_SCRAP_BOT, SPELL_SUMMON_SCRAP_BOT_TRIGGER, SPELL_SUMMON_SCRAP_BOT_VISUAL, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_mimiron().
GetAI_boss_aerial_unit()
UnitAI* GetAI_boss_aerial_unit (Creature * pCreature)
Definition at line 1612 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_boss_leviathan_mk2()
UnitAI* GetAI_boss_leviathan_mk2 (Creature * pCreature)
Definition at line 1059 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_boss_leviathan_mk2_turret()
UnitAI* GetAI_boss_leviathan_mk2_turret (Creature * pCreature)
Definition at line 1960 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_boss_mimiron()
UnitAI* GetAI_boss_mimiron (Creature * pCreature)
Definition at line 775 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_boss_vx001()
UnitAI* GetAI_boss_vx001 (Creature * pCreature)
Definition at line 1358 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_bot_trigger()
UnitAI* GetAI_npc_bot_trigger (Creature * pCreature)
Definition at line 1732 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_computer()
UnitAI* GetAI_npc_computer (Creature * pCreature)
Definition at line 1980 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_frost_bomb()
UnitAI* GetAI_npc_frost_bomb (Creature * pCreature)
Definition at line 1910 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_mimiron_flames()
UnitAI* GetAI_npc_mimiron_flames (Creature * pCreature)
Definition at line 1852 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_proximity_mine()
UnitAI* GetAI_npc_proximity_mine (Creature * pCreature)
Definition at line 1661 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GetAI_npc_rocket_strike()
UnitAI* GetAI_npc_rocket_strike (Creature * pCreature)
Definition at line 1940 of file boss_mimiron.cpp.
Referenced by AddSC_boss_mimiron().
GOUse_go_big_red_button()
bool GOUse_go_big_red_button (Player * pPlayer, GameObject * pGo)
Definition at line 1989 of file boss_mimiron.cpp.
References AI_EVENT_CUSTOM_A, DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, NPC_MIMIRON, InstanceData::SetData(), TYPE_MIMIRON, and TYPE_MIMIRON_HARD.
Referenced by AddSC_boss_mimiron().
Variable Documentation
afAerialMovePos
const float afAerialMovePos[3] = {2743.32f, 2569.285f, 378.2812f} static
Definition at line 260 of file boss_mimiron.cpp.
Referenced by boss_aerial_unitAI::DamageTaken(), boss_mimironAI::JustSummoned(), and boss_aerial_unitAI::UpdateAI().
afAerialSpawnPos
const float afAerialSpawnPos[4] = {2744.365f, 2569.303f, 392.2355f, 3.15f} static
Definition at line 259 of file boss_mimiron.cpp.
Referenced by boss_mimironAI::JustDidDialogueStep().
afCenterMovePos
const float afCenterMovePos[3] = {2744.61f, 2569.38f, 364.3136f} static
Definition at line 262 of file boss_mimiron.cpp.
Referenced by boss_mimironAI::JustDidDialogueStep().
afRobotSpawnPos
const float afRobotSpawnPos[4] = {2744.431f, 2569.385f, 364.3968f, 3.141f} static
Definition at line 257 of file boss_mimiron.cpp.
Referenced by boss_mimironAI::JustDidDialogueStep().
afRocketSpawnPos
const float afRocketSpawnPos[4] = {2746.262f, 2567.085f, 369.2921f, 3.14f} static
Definition at line 258 of file boss_mimiron.cpp.
afTankEvadePos
const float afTankEvadePos[4] = {2792.07f, 2596.32f, 364.3136f, 3.5f} static
Definition at line 256 of file boss_mimiron.cpp.
Referenced by boss_leviathan_mk2AI::DamageTaken(), and boss_leviathan_mk2AI::MovementInform().
afTankMovePos
const float afTankMovePos[3] = {2763.82f, 2568.87f, 364.3136f} static
Definition at line 261 of file boss_mimiron.cpp.
Referenced by boss_mimironAI::JustDidDialogueStep().
aMimironDialogue
const DialogueEntry aMimironDialogue[] static
Definition at line 201 of file boss_mimiron.cpp.
aMimironTeleporters
const uint32 aMimironTeleporters[] = {GO_MIMIRON_TEL1, GO_MIMIRON_TEL2, GO_MIMIRON_TEL3, GO_MIMIRON_TEL4, GO_MIMIRON_TEL5, GO_MIMIRON_TEL6, GO_MIMIRON_TEL7, GO_MIMIRON_TEL8, GO_MIMIRON_TEL9} static
Definition at line 253 of file boss_mimiron.cpp.
Referenced by EffectDummyCreature_npc_bot_trigger(), and npc_bot_triggerAI::UpdateAI().
aRandomAnimationSpells
const uint32 aRandomAnimationSpells[] = {SPELL_RIDE_VEHICLE_MIMIRON_0, SPELL_RIDE_VEHICLE_MIMIRON_1, SPELL_RIDE_VEHICLE_MIMIRON_2, SPELL_RIDE_VEHICLE_MIMIRON_4} static
Definition at line 250 of file boss_mimiron.cpp.
Referenced by boss_mimironAI::DoFlyToNextRandomSeat().