CMaNGOS_WoTLK: boss_svala.cpp File Reference
boss_svala.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_pinnacle.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_svalaAI
struct spell_ritual_of_the_sword
struct spell_svala_transforming
Enumerations
enum {
SAY_AGGRO = -1575005 , SAY_SLAY_1 = -1575006 , SAY_SLAY_2 = -1575007 , SAY_SLAY_3 = -1575008 ,
SAY_SACRIFICE_1 = -1575009 , SAY_SACRIFICE_2 = -1575010 , SAY_SACRIFICE_3 = -1575011 , SAY_SACRIFICE_4 = -1575012 ,
SAY_SACRIFICE_5 = -1575013 , SAY_DEATH = -1575014 , NPC_CHANNELER = 27281 , NPC_SCOURGE_HULK = 26555 ,
SPELL_RITUAL_OF_SWORD = 48276 , SPELL_RITUAL_STRIKE = 48331 , SPELL_RITUAL_DISARM = 54159 , SPELL_RITUAL_SELECTION = 54148 ,
SPELL_CALL_FLAMES = 48258 , SPELL_SINISTER_STRIKE = 15667 , SPELL_SINISTER_STRIKE_H = 59409 , SPELL_SUMMON_CHANNELER_1 = 48271 ,
SPELL_SUMMON_CHANNELER_2 = 48274 , SPELL_SUMMON_CHANNELER_3 = 48275 , SPELL_PARALIZE = 48278 , SPELL_SHADOWS_IN_THE_DARK = 59407 ,
SPELL_BALL_OF_FLAME = 48246
}
enum SvalaActions {
SVALA_ACTION_SINISTER_STRIKE , SVALA_ACTION_CALL_FLAMES , SVALA_ACTION_RITUAL_STRIKE , SVALA_ACTION_RITUAL_OF_SWORD ,
SVALA_ACTION_MAX
}
Functions
bool ProcessEventId_event_spell_call_flames (uint32, Object *pSource, Object *, bool)
void AddSC_boss_svala ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_SACRIFICE_1
SAY_SACRIFICE_2
SAY_SACRIFICE_3
SAY_SACRIFICE_4
SAY_SACRIFICE_5
SAY_DEATH
NPC_CHANNELER
NPC_SCOURGE_HULK
SPELL_RITUAL_OF_SWORD
SPELL_RITUAL_STRIKE
SPELL_RITUAL_DISARM
SPELL_RITUAL_SELECTION
SPELL_CALL_FLAMES
SPELL_SINISTER_STRIKE
SPELL_SINISTER_STRIKE_H
SPELL_SUMMON_CHANNELER_1
SPELL_SUMMON_CHANNELER_2
SPELL_SUMMON_CHANNELER_3
SPELL_PARALIZE
SPELL_SHADOWS_IN_THE_DARK
SPELL_BALL_OF_FLAME
Definition at line 30 of file boss_svala.cpp.
SvalaActions
enum SvalaActions
Enumerator
SVALA_ACTION_SINISTER_STRIKE
SVALA_ACTION_CALL_FLAMES
SVALA_ACTION_RITUAL_STRIKE
SVALA_ACTION_RITUAL_OF_SWORD
SVALA_ACTION_MAX
Definition at line 66 of file boss_svala.cpp.
Function Documentation
AddSC_boss_svala()
void AddSC_boss_svala ()
Definition at line 248 of file boss_svala.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_call_flames(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_spell_call_flames()
bool ProcessEventId_event_spell_call_flames (uint32 , Object * pSource, Object * , bool)
Definition at line 194 of file boss_svala.cpp.
References SPELL_BALL_OF_FLAME, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_svala().