CMaNGOS_WoTLK: boss_arlokk.cpp File Reference
boss_arlokk.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "zulgurub.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_arlokkAI
struct npc_zulian_prowlerAI
struct ArlokkVanish
Enumerations
enum {
SAY_AGGRO = -1309011 , SAY_FEAST_PANTHER = -1309012 , SAY_DEATH = -1309013 , SPELL_SHADOW_WORD_PAIN = 24212 ,
SPELL_GOUGE = 12540 , SPELL_MARK_ARLOKK = 24210 , SPELL_RAVAGE = 24213 , SPELL_TRASH = 3391 ,
SPELL_WHIRLWIND = 24236 , SPELL_PANTHER_TRANSFORM = 24190 , SPELL_SUMMON_ZULIAN_PROWLERS = 24247 , SPELL_HATE_TO_ZERO = 20538 ,
SPELL_VANISH_TELEPORT = 24228 , SPELL_VANISH = 24223 , SPELL_SUPER_INVIS = 24235 , SPELL_TRANSFORM_VISUAL = 24085 ,
SPELL_SNEAK = 22766 , SPELL_LIST_PHASE_1 = 1451501 , SPELL_LIST_PHASE_2 = 1451502
}
enum ArlokkActions { ARLOKK_PHASE_TRANSITION , ARLOKK_ACTION_MAX , ARLOKK_INVIS_SELECT , ARLOKK_INVIS_TIMER }
Functions
bool GOUse_go_gong_of_bethekk (Player *, GameObject *pGo)
void AddSC_boss_arlokk ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_FEAST_PANTHER
SAY_DEATH
SPELL_SHADOW_WORD_PAIN
SPELL_GOUGE
SPELL_MARK_ARLOKK
SPELL_RAVAGE
SPELL_TRASH
SPELL_WHIRLWIND
SPELL_PANTHER_TRANSFORM
SPELL_SUMMON_ZULIAN_PROWLERS
SPELL_HATE_TO_ZERO
SPELL_VANISH_TELEPORT
SPELL_VANISH
SPELL_SUPER_INVIS
SPELL_TRANSFORM_VISUAL
SPELL_SNEAK
SPELL_LIST_PHASE_1
SPELL_LIST_PHASE_2
Definition at line 34 of file boss_arlokk.cpp.
ArlokkActions
enum ArlokkActions
Enumerator
ARLOKK_PHASE_TRANSITION
ARLOKK_ACTION_MAX
ARLOKK_INVIS_SELECT
ARLOKK_INVIS_TIMER
Definition at line 62 of file boss_arlokk.cpp.
Function Documentation
AddSC_boss_arlokk()
void AddSC_boss_arlokk ()
Definition at line 287 of file boss_arlokk.cpp.
References Script::GetAI, GOUse_go_gong_of_bethekk(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_gong_of_bethekk()
bool GOUse_go_gong_of_bethekk (Player * , GameObject * pGo)
Definition at line 258 of file boss_arlokk.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, and TYPE_ARLOKK.
Referenced by AddSC_boss_arlokk().