CMaNGOS_WoTLK: boss_warbringer_omrogg.cpp File Reference
boss_warbringer_omrogg.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shattered_halls.h"
Data Structures
struct Yell
struct mob_omrogg_headsAI
struct boss_warbringer_omroggAI
Enumerations
enum {
YELL_DIE_L = -1540039 , YELL_DIE_R = -1540040 , EMOTE_ENRAGE = -1540041 , SPELL_BLAST_WAVE = 30600 ,
SPELL_FEAR = 30584 , SPELL_THUNDERCLAP = 30633 , SPELL_BURNING_MAUL = 30598 , SPELL_BURNING_MAUL_H = 36056 ,
SPELL_BEATDOWN = 30618 , NPC_LEFT_HEAD = 19523 , NPC_RIGHT_HEAD = 19524
}
Functions
UnitAI * GetAI_boss_warbringer_omrogg (Creature *pCreature)
UnitAI * GetAI_mob_omrogg_heads (Creature *pCreature)
void AddSC_boss_warbringer_omrogg ()
Variables
static Yell GoCombat []
static Yell GoCombatDelay []
static Yell Threat []
static Yell ThreatDelay1 []
static Yell ThreatDelay2 []
static Yell Killing []
static Yell KillingDelay []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
YELL_DIE_L
YELL_DIE_R
EMOTE_ENRAGE
SPELL_BLAST_WAVE
SPELL_FEAR
SPELL_THUNDERCLAP
SPELL_BURNING_MAUL
SPELL_BURNING_MAUL_H
SPELL_BEATDOWN
NPC_LEFT_HEAD
NPC_RIGHT_HEAD
Definition at line 32 of file boss_warbringer_omrogg.cpp.
Function Documentation
AddSC_boss_warbringer_omrogg()
void AddSC_boss_warbringer_omrogg ()
Definition at line 414 of file boss_warbringer_omrogg.cpp.
References Script::GetAI, GetAI_boss_warbringer_omrogg(), GetAI_mob_omrogg_heads(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_warbringer_omrogg()
UnitAI* GetAI_boss_warbringer_omrogg (Creature * pCreature)
Definition at line 404 of file boss_warbringer_omrogg.cpp.
Referenced by AddSC_boss_warbringer_omrogg().
GetAI_mob_omrogg_heads()
UnitAI* GetAI_mob_omrogg_heads (Creature * pCreature)
Definition at line 409 of file boss_warbringer_omrogg.cpp.
Referenced by AddSC_boss_warbringer_omrogg().
Variable Documentation
GoCombat
Yell GoCombat[] static
Initial value:
=
{
    { -1540018, NPC_LEFT_HEAD},
    { -1540019, NPC_LEFT_HEAD},
    { -1540020, NPC_LEFT_HEAD},
}
Definition at line 57 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::Aggro().
GoCombatDelay
Yell GoCombatDelay[] static
Initial value:
=
{
    { -1540021, NPC_RIGHT_HEAD},
    { -1540022, NPC_RIGHT_HEAD},
    { -1540023, NPC_RIGHT_HEAD},
}
Definition at line 63 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::UpdateAI().
Killing
Yell Killing[] static
Initial value:
=
{
    { -1540036, NPC_LEFT_HEAD},
    { -1540037, NPC_RIGHT_HEAD},
}
Definition at line 92 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::KilledUnit().
KillingDelay
Yell KillingDelay[] static
Initial value:
=
{
    { -1540038, NPC_RIGHT_HEAD},
    { -1000000, NPC_LEFT_HEAD},
}
Definition at line 97 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::UpdateAI().
Threat
Yell Threat[] static
Initial value:
=
{
    { -1540024, NPC_LEFT_HEAD},
    { -1540025, NPC_RIGHT_HEAD},
    { -1540026, NPC_LEFT_HEAD},
    { -1540027, NPC_LEFT_HEAD},
}
Definition at line 70 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::DoYellForThreat().
ThreatDelay1
Yell ThreatDelay1[] static
Initial value:
=
{
    { -1540028, NPC_RIGHT_HEAD},
    { -1540029, NPC_LEFT_HEAD},
    { -1540030, NPC_RIGHT_HEAD},
    { -1540031, NPC_RIGHT_HEAD},
}
Definition at line 77 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::UpdateAI().
ThreatDelay2
Yell ThreatDelay2[] static
Initial value:
=
{
    { -1540032, NPC_LEFT_HEAD},
    { -1540033, NPC_RIGHT_HEAD},
    { -1540034, NPC_LEFT_HEAD},
    { -1540035, NPC_LEFT_HEAD},
}
Definition at line 84 of file boss_warbringer_omrogg.cpp.
Referenced by boss_warbringer_omroggAI::UpdateAI().