CMaNGOS_WoTLK: boss_ionar.cpp File Reference
boss_ionar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_lightning.h"
Data Structures
struct boss_ionarAI
struct mob_spark_of_ionarAI
Enumerations
enum {
SAY_AGGRO = -1602011 , SAY_SLAY_1 = -1602012 , SAY_SLAY_2 = -1602013 , SAY_SLAY_3 = -1602014 ,
SAY_DEATH = -1602015 , SAY_SPLIT_1 = -1602016 , SAY_SPLIT_2 = -1602017 , SPELL_BALL_LIGHTNING_N = 52780 ,
SPELL_BALL_LIGHTNING_H = 59800 , SPELL_STATIC_OVERLOAD_N = 52658 , SPELL_STATIC_OVERLOAD_H = 59795 , SPELL_DISPERSE = 52770 ,
SPELL_SUMMON_SPARK = 52746 , SPELL_SPARK_DESPAWN = 52776 , SPELL_SPARK_VISUAL_TRIGGER_N = 52667 , SPELL_SPARK_VISUAL_TRIGGER_H = 59833 ,
NPC_SPARK_OF_IONAR = 28926 , MAX_SPARKS = 5 , POINT_CALLBACK = 0
}
Functions
bool EffectDummyCreature_boss_ionar (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_ionar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
SAY_SPLIT_1
SAY_SPLIT_2
SPELL_BALL_LIGHTNING_N
SPELL_BALL_LIGHTNING_H
SPELL_STATIC_OVERLOAD_N
SPELL_STATIC_OVERLOAD_H
SPELL_DISPERSE
SPELL_SUMMON_SPARK
SPELL_SPARK_DESPAWN
SPELL_SPARK_VISUAL_TRIGGER_N
SPELL_SPARK_VISUAL_TRIGGER_H
NPC_SPARK_OF_IONAR
MAX_SPARKS
POINT_CALLBACK
Definition at line 27 of file boss_ionar.cpp.
Function Documentation
AddSC_boss_ionar()
void AddSC_boss_ionar ()
Definition at line 365 of file boss_ionar.cpp.
References EffectDummyCreature_boss_ionar(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_boss_ionar()
bool EffectDummyCreature_boss_ionar (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 292 of file boss_ionar.cpp.
References Creature::AI(), Unit::AttackStop(), Unit::CastSpell(), CHASE_MOTION_TYPE, EFFECT_INDEX_0, MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Unit::GetMotionMaster(), MAX_SPARKS, MotionMaster::MovementExpired(), NPC_IONAR, Unit::SetVisibility(), SPELL_DISPERSE, SPELL_SPARK_DESPAWN, SPELL_SUMMON_SPARK, TRIGGERED_OLD_TRIGGERED, and VISIBILITY_OFF.
Referenced by AddSC_boss_ionar().