CMaNGOS_WoTLK: boss_ragnaros.cpp File Reference
boss_ragnaros.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "molten_core.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_ragnarosAI
Enumerations
enum {
SAY_ARRIVAL5_RAG = -1409012 , SAY_REINFORCEMENTS_1 = -1409013 , SAY_REINFORCEMENTS_2 = -1409014 , SAY_HAMMER = -1409015 ,
SAY_WRATH = -1409016 , SAY_KILL = 7626 , SAY_MAGMABURST = -1409018 , SPELL_WRATH_OF_RAGNAROS = 20566 ,
SPELL_ELEMENTAL_FIRE = 20563 , SPELL_MAGMA_BLAST = 20565 , SPELL_MELT_WEAPON = 21387 , SPELL_RAGNA_SUBMERGE = 21107 ,
SPELL_RAGNA_SUBMERGE_VISUAL = 20567 , SPELL_RAGNA_EMERGE = 20568 , SPELL_SUBMERGE_EFFECT = 21859 , SPELL_ELEMENTAL_FIRE_KILL = 19773 ,
SPELL_MIGHT_OF_RAGNAROS = 21154 , SPELL_INTENSE_HEAT = 21155 , SPELL_LAVA_BURST = 21908 , SPELL_SUMMON_SONS_FLAME = 21108 ,
SPELL_DOUBLE_ATTACK = 19818 , SPELL_LAVA_SHIELD = 21857 , NB_ADDS_IN_SUBMERGE = 8 , NPC_SON_OF_FLAME = 12143 ,
NPC_FLAME_OF_RAGNAROS = 13148 , PHASE_EMERGING = 0 , PHASE_EMERGED = 1 , PHASE_SUBMERGING = 2 ,
PHASE_SUBMERGED = 3
}
enum RagnarosActions {
RAGNAROS_PHASE_TRANSITION , RAGNAROS_WRATH_OF_RAGNAROS , RAGNAROS_MIGHT_OF_RAGNAROS , RAGNAROS_MAGMA_BLAST ,
RAGNAROS_LAVA_BURST , RAGNAROS_ACTION_MAX , RAGNAROS_ENTER_COMBAT
}
Functions
UnitAI * GetAI_boss_ragnaros (Creature *creature)
void AddSC_boss_ragnaros ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ARRIVAL5_RAG
SAY_REINFORCEMENTS_1
SAY_REINFORCEMENTS_2
SAY_HAMMER
SAY_WRATH
SAY_KILL
SAY_MAGMABURST
SPELL_WRATH_OF_RAGNAROS
SPELL_ELEMENTAL_FIRE
SPELL_MAGMA_BLAST
SPELL_MELT_WEAPON
SPELL_RAGNA_SUBMERGE
SPELL_RAGNA_SUBMERGE_VISUAL
SPELL_RAGNA_EMERGE
SPELL_SUBMERGE_EFFECT
SPELL_ELEMENTAL_FIRE_KILL
SPELL_MIGHT_OF_RAGNAROS
SPELL_INTENSE_HEAT
SPELL_LAVA_BURST
SPELL_SUMMON_SONS_FLAME
SPELL_DOUBLE_ATTACK
SPELL_LAVA_SHIELD
NB_ADDS_IN_SUBMERGE
NPC_SON_OF_FLAME
NPC_FLAME_OF_RAGNAROS
PHASE_EMERGING
PHASE_EMERGED
PHASE_SUBMERGING
PHASE_SUBMERGED
Definition at line 28 of file boss_ragnaros.cpp.
RagnarosActions
enum RagnarosActions
Enumerator
RAGNAROS_PHASE_TRANSITION
RAGNAROS_WRATH_OF_RAGNAROS
RAGNAROS_MIGHT_OF_RAGNAROS
RAGNAROS_MAGMA_BLAST
RAGNAROS_LAVA_BURST
RAGNAROS_ACTION_MAX
RAGNAROS_ENTER_COMBAT
Definition at line 66 of file boss_ragnaros.cpp.
Function Documentation
AddSC_boss_ragnaros()
void AddSC_boss_ragnaros ()
Definition at line 350 of file boss_ragnaros.cpp.
References Script::GetAI, GetAI_boss_ragnaros(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_ragnaros()
UnitAI* GetAI_boss_ragnaros (Creature * creature)
Definition at line 345 of file boss_ragnaros.cpp.
Referenced by AddSC_boss_ragnaros().