CMaNGOS_WoTLK: boss_lady_vashj.cpp File Reference
boss_lady_vashj.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "serpent_shrine.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_lady_vashjAI
struct mob_enchanted_elementalAI
struct VashjPersuasion
struct SporeDropEffect
Enumerations
enum {
SAY_INTRO = -1548042 , SAY_AGGRO1 = -1548043 , SAY_AGGRO2 = -1548044 , SAY_AGGRO3 = -1548045 ,
SAY_AGGRO4 = -1548046 , SAY_AGGRO5 = -1548047 , SAY_PHASE2 = -1548048 , SAY_PHASE3 = -1548049 ,
SAY_BOWSHOT1 = -1548050 , SAY_BOWSHOT2 = -1548051 , SAY_SLAY1 = -1548052 , SAY_SLAY2 = -1548053 ,
SAY_SLAY3 = -1548054 , SAY_DEATH = -1548055 , SPELL_MULTI_SHOT = 38310 , SPELL_SHOCK_BLAST = 38509 ,
SPELL_ENTANGLE = 38316 , SPELL_STATIC_CHARGE = 38280 , SPELL_FORKED_LIGHTNING = 38145 , SPELL_SHOOT = 38295 ,
SPELL_MAGIC_BARRIER = 38112 , SPELL_SURGE = 38044 , SPELL_SUMMON_TAINTED_ELEM = 38139 , SPELL_PERSUASION = 38511 ,
SPELL_PERSUASION_BONUS = 38514 , NPC_ENCHANTED_ELEMENTAL = 21958 , NPC_TAINTED_ELEMENTAL = 22009 , NPC_COILFANG_STRIDER = 22056 ,
NPC_COILFANG_ELITE = 22055 , NPC_TOXIC_SPOREBAT = 22140 , NPC_OLD_WORLD_TRIGGER = 15384 , SPELL_WAVE_A = 38019 ,
SPELL_WAVE_C = 38242 , SPELL_WAVE_D = 38244 , SPELL_WAVE_B = 38247 , SPELL_WAVE_E_1 = 38489 ,
SPELL_WAVE_E_2 = 38490 , SPELL_WAVE_E_3 = 38492 , SPELL_WAVE_E_4 = 38493 , COUNT_SPELLS = 3 ,
SPELL_PANIC_PERIODIC = 38257 , SPELL_SPORE_DROP = 38571 , SPELL_SPORE_DROP_EFFECT = 38573 , SPELL_TOXIC_SPORES_SUMMON = 38574 ,
SPELL_TOXIC_SPORES_DAMAGE = 38575 , NPC_SPORE_DROP_TRIGGER = 22207 , PATH_ID_1 = 1 , PATH_ID_2 = 2 ,
PATH_ID_3 = 3 , PATH_ID_COUNT = 3 , PATH_ID_4 = 4 , PATH_ID_5 = 5 ,
PATH_ID_6 = 6 , WAYPOINT_MOVE_FINAL_POINT_SPOREBAT = 8 , ITEM_TAINTED_CORE = 31088 , SPELL_PARALYZE = 38132 ,
SPELL_THROW_KEY = 38134 , SPELL_REMOVE_TAINTED_CORES = 39495 , SPELL_VISUAL_KIT = 6445 , POINT_MOVE_CENTER = 1 ,
PHASE_1 = 1 , PHASE_2 = 2 , PHASE_3 = 3 , MAX_SHIELD_GEN = 4
}
enum VashjActions {
VASHJ_ACTION_PHASE_2 = 0 , VASHJ_ACTION_PERSUASION , VASHJ_ACTION_SHOCK_BLAST , VASHJ_ACTION_STATIC_CHARGE ,
VASHJ_ACTION_ENTANGLE , VASHJ_ACTION_MELEE_MODE , VASHJ_ACTION_SHOOT , VASHJ_ACTION_FORKED_LIGHTNING ,
VASHJ_ACTION_MAX , VASHJ_INTRO , VASHJ_COILFANG_ELITE , VASHJ_COILFANG_STRIDER ,
VASHJ_SPOREBAT , VASHJ_ENCHANTED_ELEMENTAL , VASHJ_TAINTED_ELEMENTAL
}
Functions
bool GOUse_go_shield_generator (Player *, GameObject *pGo)
bool OnLootItemTaintedCore (Player *player, Item *, bool apply)
bool GOUse_go_vashj_bridge (Player *player, GameObject *go)
void AddSC_boss_lady_vashj ()
Variables
static const float afMiddlePos [3] = { 29.8326f, -923.274f, 42.90189f}
static const float batSpells [] = { SPELL_WAVE_E_1, SPELL_WAVE_E_3, SPELL_WAVE_E_4}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_AGGRO4
SAY_AGGRO5
SAY_PHASE2
SAY_PHASE3
SAY_BOWSHOT1
SAY_BOWSHOT2
SAY_SLAY1
SAY_SLAY2
SAY_SLAY3
SAY_DEATH
SPELL_MULTI_SHOT
SPELL_SHOCK_BLAST
SPELL_ENTANGLE
SPELL_STATIC_CHARGE
SPELL_FORKED_LIGHTNING
SPELL_SHOOT
SPELL_MAGIC_BARRIER
SPELL_SURGE
SPELL_SUMMON_TAINTED_ELEM
SPELL_PERSUASION
SPELL_PERSUASION_BONUS
NPC_ENCHANTED_ELEMENTAL
NPC_TAINTED_ELEMENTAL
NPC_COILFANG_STRIDER
NPC_COILFANG_ELITE
NPC_TOXIC_SPOREBAT
NPC_OLD_WORLD_TRIGGER
SPELL_WAVE_A
SPELL_WAVE_C
SPELL_WAVE_D
SPELL_WAVE_B
SPELL_WAVE_E_1
SPELL_WAVE_E_2
SPELL_WAVE_E_3
SPELL_WAVE_E_4
COUNT_SPELLS
SPELL_PANIC_PERIODIC
SPELL_SPORE_DROP
SPELL_SPORE_DROP_EFFECT
SPELL_TOXIC_SPORES_SUMMON
SPELL_TOXIC_SPORES_DAMAGE
NPC_SPORE_DROP_TRIGGER
PATH_ID_1
PATH_ID_2
PATH_ID_3
PATH_ID_COUNT
PATH_ID_4
PATH_ID_5
PATH_ID_6
WAYPOINT_MOVE_FINAL_POINT_SPOREBAT
ITEM_TAINTED_CORE
SPELL_PARALYZE
SPELL_THROW_KEY
SPELL_REMOVE_TAINTED_CORES
SPELL_VISUAL_KIT
POINT_MOVE_CENTER
PHASE_1
PHASE_2
PHASE_3
MAX_SHIELD_GEN
Definition at line 30 of file boss_lady_vashj.cpp.
VashjActions
enum VashjActions
Enumerator
VASHJ_ACTION_PHASE_2
VASHJ_ACTION_PERSUASION
VASHJ_ACTION_SHOCK_BLAST
VASHJ_ACTION_STATIC_CHARGE
VASHJ_ACTION_ENTANGLE
VASHJ_ACTION_MELEE_MODE
VASHJ_ACTION_SHOOT
VASHJ_ACTION_FORKED_LIGHTNING
VASHJ_ACTION_MAX
VASHJ_INTRO
VASHJ_COILFANG_ELITE
VASHJ_COILFANG_STRIDER
VASHJ_SPOREBAT
VASHJ_ENCHANTED_ELEMENTAL
VASHJ_TAINTED_ELEMENTAL
Definition at line 130 of file boss_lady_vashj.cpp.
Function Documentation
AddSC_boss_lady_vashj()
void AddSC_boss_lady_vashj ()
Definition at line 749 of file boss_lady_vashj.cpp.
References Script::GetAI, GOUse_go_shield_generator(), GOUse_go_vashj_bridge(), Script::Name, OnLootItemTaintedCore(), Script::pGOUse, Script::pItemLoot, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_shield_generator()
bool GOUse_go_shield_generator (Player * , GameObject * pGo)
Definition at line 673 of file boss_lady_vashj.cpp.
References GAMEOBJECT_FLAGS, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), GO_FLAG_NO_INTERACT, NPC_LADYVASHJ, NPC_TINY_TRIGGER, and Object::SetFlag().
Referenced by AddSC_boss_lady_vashj().
GOUse_go_vashj_bridge()
bool GOUse_go_vashj_bridge (Player * player, GameObject * go)
Definition at line 702 of file boss_lady_vashj.cpp.
References AI_EVENT_CUSTOM_A, WorldObject::GetInstanceData(), GO_BRIDGE_PART_1, GO_BRIDGE_PART_2, GO_BRIDGE_PART_3, and NPC_LADYVASHJ.
Referenced by AddSC_boss_lady_vashj().
OnLootItemTaintedCore()
bool OnLootItemTaintedCore (Player * player, Item * , bool apply)
Definition at line 693 of file boss_lady_vashj.cpp.
References ByteConverter::apply(), Unit::CastSpell(), Unit::RemoveAurasDueToSpell(), SPELL_PARALYZE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_lady_vashj().
Variable Documentation
afMiddlePos
const float afMiddlePos[3] = { 29.8326f, -923.274f, 42.90189f} static
Definition at line 126 of file boss_lady_vashj.cpp.
Referenced by boss_lady_vashjAI::ExecuteAction().
batSpells
const float batSpells[] = { SPELL_WAVE_E_1, SPELL_WAVE_E_3, SPELL_WAVE_E_4} static
Definition at line 128 of file boss_lady_vashj.cpp.
Referenced by boss_lady_vashjAI::HandleSporebat().