CMaNGOS_WoTLK: boss_blood_queen_lanathel.cpp File Reference
boss_blood_queen_lanathel.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
Data Structures
struct boss_blood_queen_lanathelAI
Enumerations
enum {
SAY_AGGRO = -1631121 , SAY_BITE_1 = -1631122 , SAY_BITE_2 = -1631123 , SAY_SHADOWS = -1631124 ,
SAY_PACT = -1631125 , SAY_MC = -1631126 , SAY_AIR_PHASE = -1631127 , SAY_BERSERK = -1631128 ,
SAY_DEATH = -1631129 , SAY_SLAY_1 = -1631195 , SAY_SLAY_2 = -1631196 , SPELL_BERSERK = 26662 ,
SPELL_SHROUD_OF_SORROW = 70986 , SPELL_BLOOD_MIRROR = 70837 , SPELL_SWARMING_SHADOWS = 71861 , SPELL_PACT_OF_THE_DARKFALLEN = 71336 ,
SPELL_VAMPIRIC_BITE = 71837 , SPELL_TWILIGHT_BLOODBOLT = 71445 , SPELL_DELIRIOUS_SLASH = 72261 , SPELL_PRESENCE_OF_DARKFALLEN = 70994 ,
SPELL_THIRST_QUENCHED = 72154 , SPELL_INCITE_TERROR = 73070 , SPELL_BLOODBOLT_WHIRL = 71772 , PHASE_GROUND = 1 ,
PHASE_RUNNING = 2 , PHASE_AIR = 3 , PHASE_FLYING = 4 , POINT_CENTER_GROUND = 1 ,
POINT_CENTER_AIR = 2
}
Functions
UnitAI * GetAI_boss_blood_queen_lanathel (Creature *pCreature)
void AddSC_boss_blood_queen_lanathel ()
Variables
static const float aQueenPosition [2][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_BITE_1
SAY_BITE_2
SAY_SHADOWS
SAY_PACT
SAY_MC
SAY_AIR_PHASE
SAY_BERSERK
SAY_DEATH
SAY_SLAY_1
SAY_SLAY_2
SPELL_BERSERK
SPELL_SHROUD_OF_SORROW
SPELL_BLOOD_MIRROR
SPELL_SWARMING_SHADOWS
SPELL_PACT_OF_THE_DARKFALLEN
SPELL_VAMPIRIC_BITE
SPELL_TWILIGHT_BLOODBOLT
SPELL_DELIRIOUS_SLASH
SPELL_PRESENCE_OF_DARKFALLEN
SPELL_THIRST_QUENCHED
SPELL_INCITE_TERROR
SPELL_BLOODBOLT_WHIRL
PHASE_GROUND
PHASE_RUNNING
PHASE_AIR
PHASE_FLYING
POINT_CENTER_GROUND
POINT_CENTER_AIR
Definition at line 27 of file boss_blood_queen_lanathel.cpp.
Function Documentation
AddSC_boss_blood_queen_lanathel()
void AddSC_boss_blood_queen_lanathel ()
Definition at line 329 of file boss_blood_queen_lanathel.cpp.
References Script::GetAI, GetAI_boss_blood_queen_lanathel(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_blood_queen_lanathel()
UnitAI* GetAI_boss_blood_queen_lanathel (Creature * pCreature)
Definition at line 324 of file boss_blood_queen_lanathel.cpp.
Referenced by AddSC_boss_blood_queen_lanathel().
Variable Documentation
aQueenPosition
const float aQueenPosition[2][3] static
Initial value:
=
{
    {4595.64f, 2769.19f, 400.13f},
    {4595.90f, 2769.31f, 421.83f},
}
Definition at line 73 of file boss_blood_queen_lanathel.cpp.
Referenced by boss_blood_queen_lanathelAI::MovementInform(), and boss_blood_queen_lanathelAI::UpdateAI().