CMaNGOS_WoTLK: boss_teron_gorefiend.cpp File Reference
boss_teron_gorefiend.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "black_temple.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_teron_gorefiendAI
struct npc_doom_blossomAI
struct npc_shadow_constructAI
struct ShadowOfDeath
struct ShadowOfDeathRemove
struct SummonBlossomMoveTarget
Enumerations
enum {
SAY_INTRO = -1564037 , SAY_AGGRO = -1564038 , SAY_SLAY1 = 21099 , SAY_SLAY2 = 21100 ,
SAY_SPELL1 = -1564041 , SAY_SPELL2 = -1564042 , SAY_SPECIAL1 = -1564043 , SAY_SPECIAL2 = -1564044 ,
SAY_UNK = -1564045 , SAY_DEATH = -1564046 , EMOTE_BERSERK = -1000004 , SPELL_INCINERATE = 40239 ,
SPELL_CRUSHING_SHADOWS = 40243 , SPELL_SHADOW_OF_DEATH = 40251 , SPELL_BERSERK = 45078 , SPELL_SUMMON_DOOM_BLOSSOM = 40188 ,
SPELL_SUMMON_SPIRIT = 40266 , SPELL_SPIRITUAL_VENGEANCE = 40268 , SPELL_SUMMON_SKELETON_1 = 40270 , SPELL_SUMMON_SKELETON_2 = 41948 ,
SPELL_SUMMON_SKELETON_3 = 41949 , SPELL_SUMMON_SKELETON_4 = 41950 , SPELL_DESTROY_SPIRIT = 41626 , SPELL_DESTROY_ALL_SPIRITS = 44659 ,
SPELL_SHADOW_OF_DEATH_REMOVE = 41999 , SPELL_POSSESS_SPIRIT_IMMUNE = 40282 , SPELL_SHADOWY_CONSTRUCT = 40326 , SPELL_ATROPHY = 40327 ,
SPELL_SHADOW_STRIKES = 40334 , SPELL_SUMMON_BLOSSOM_MOVE_TARGET = 40186 , SPELL_SHADOW_BOLT = 40185 , NPC_DOOM_BLOSSOM = 23123
}
enum GorefiendActions {
GOREFIEND_ACTION_BERSERK , GOREFIEND_ACTION_DOOM_BLOSSOM , GOREFIEND_ACTION_INCINERATE , GOREFIEND_ACTION_SHADOW_OF_DEATH ,
GOREFIEND_ACTION_CRUSHING_SHADOWS , GOREFIEND_ACTION_MAX
}
Functions
bool AreaTrigger_at_teron_gorefiend (Player *player, AreaTriggerEntry const *)
void AddSC_boss_teron_gorefiend ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO
SAY_SLAY1
SAY_SLAY2
SAY_SPELL1
SAY_SPELL2
SAY_SPECIAL1
SAY_SPECIAL2
SAY_UNK
SAY_DEATH
EMOTE_BERSERK
SPELL_INCINERATE
SPELL_CRUSHING_SHADOWS
SPELL_SHADOW_OF_DEATH
SPELL_BERSERK
SPELL_SUMMON_DOOM_BLOSSOM
SPELL_SUMMON_SPIRIT
SPELL_SPIRITUAL_VENGEANCE
SPELL_SUMMON_SKELETON_1
SPELL_SUMMON_SKELETON_2
SPELL_SUMMON_SKELETON_3
SPELL_SUMMON_SKELETON_4
SPELL_DESTROY_SPIRIT
SPELL_DESTROY_ALL_SPIRITS
SPELL_SHADOW_OF_DEATH_REMOVE
SPELL_POSSESS_SPIRIT_IMMUNE
SPELL_SHADOWY_CONSTRUCT
SPELL_ATROPHY
SPELL_SHADOW_STRIKES
SPELL_SUMMON_BLOSSOM_MOVE_TARGET
SPELL_SHADOW_BOLT
NPC_DOOM_BLOSSOM
Definition at line 30 of file boss_teron_gorefiend.cpp.
GorefiendActions
enum GorefiendActions
Enumerator
GOREFIEND_ACTION_BERSERK
GOREFIEND_ACTION_DOOM_BLOSSOM
GOREFIEND_ACTION_INCINERATE
GOREFIEND_ACTION_SHADOW_OF_DEATH
GOREFIEND_ACTION_CRUSHING_SHADOWS
GOREFIEND_ACTION_MAX
Definition at line 78 of file boss_teron_gorefiend.cpp.
Function Documentation
AddSC_boss_teron_gorefiend()
void AddSC_boss_teron_gorefiend ()
Definition at line 429 of file boss_teron_gorefiend.cpp.
References AreaTrigger_at_teron_gorefiend(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_teron_gorefiend()
bool AreaTrigger_at_teron_gorefiend (Player * player, AreaTriggerEntry const *)
Definition at line 363 of file boss_teron_gorefiend.cpp.
References AI_EVENT_CUSTOM_A, Map::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), Player::IsGameMaster(), and NPC_TERON_GOREFIEND.
Referenced by AddSC_boss_teron_gorefiend().