CMaNGOS_WoTLK: boss_taldaram.cpp File Reference
boss_taldaram.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "ahnkahet.h"
Data Structures
struct boss_taldaramAI
struct spell_conjure_flame_sphere
Enumerations
enum {
SAY_AGGRO = -1619008 , SAY_VANISH_1 = -1619009 , SAY_VANISH_2 = -1619010 , SAY_FEED_1 = -1619011 ,
SAY_FEED_2 = -1619012 , SAY_SLAY_1 = -1619013 , SAY_SLAY_2 = -1619014 , SAY_SLAY_3 = -1619015 ,
SAY_DEATH = -1619016 , SPELL_BEAM_VISUAL = 60342 , SPELL_CONJURE_FLAME_SPHERE = 55931 , SPELL_FLAME_SPHERE_SUMMON_1 = 55895 ,
SPELL_FLAME_SPHERE_SUMMON_2 = 59511 , SPELL_FLAME_SPHERE_SUMMON_3 = 59512 , SPELL_BLOODTHIRST = 55968 , SPELL_VANISH = 55964 ,
SPELL_EMBRACE_OF_THE_VAMPYR = 55959 , SPELL_EMBRACE_OF_THE_VAMPYR_H = 59513 , SPELL_FLAME_SPHERE_PERIODIC = 55926 , SPELL_FLAME_SPHERE_PERIODIC_H = 59508 ,
SPELL_FLAME_SPHERE_SPAWN_EFFECT = 55891 , SPELL_FLAME_SPHERE_VISUAL = 55928 , SPELL_FLAME_SPHERE_DEATH_EFFECT = 55947
}
Functions
UnitAI * GetAI_boss_taldaram (Creature *pCreature)
bool GOUse_go_nerubian_device (Player *, GameObject *pGo)
void AddSC_boss_taldaram ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_VANISH_1
SAY_VANISH_2
SAY_FEED_1
SAY_FEED_2
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
SPELL_BEAM_VISUAL
SPELL_CONJURE_FLAME_SPHERE
SPELL_FLAME_SPHERE_SUMMON_1
SPELL_FLAME_SPHERE_SUMMON_2
SPELL_FLAME_SPHERE_SUMMON_3
SPELL_BLOODTHIRST
SPELL_VANISH
SPELL_EMBRACE_OF_THE_VAMPYR
SPELL_EMBRACE_OF_THE_VAMPYR_H
SPELL_FLAME_SPHERE_PERIODIC
SPELL_FLAME_SPHERE_PERIODIC_H
SPELL_FLAME_SPHERE_SPAWN_EFFECT
SPELL_FLAME_SPHERE_VISUAL
SPELL_FLAME_SPHERE_DEATH_EFFECT
Definition at line 28 of file boss_taldaram.cpp.
Function Documentation
AddSC_boss_taldaram()
void AddSC_boss_taldaram ()
Definition at line 334 of file boss_taldaram.cpp.
References Script::GetAI, GetAI_boss_taldaram(), GOUse_go_nerubian_device(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_taldaram()
UnitAI* GetAI_boss_taldaram (Creature * pCreature)
Definition at line 293 of file boss_taldaram.cpp.
Referenced by AddSC_boss_taldaram().
GOUse_go_nerubian_device()
bool GOUse_go_nerubian_device (Player * , GameObject * pGo)
Definition at line 319 of file boss_taldaram.cpp.
References DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), InstanceData::SetData(), SPECIAL, and TYPE_TALDARAM.
Referenced by AddSC_boss_taldaram().