CMaNGOS_WoTLK: boss_mother_shahraz.cpp File Reference
boss_mother_shahraz.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "black_temple.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_shahrazAI
Enumerations
enum {
SAY_ATTRACTION_1 = -1564018 , SAY_ATTRACTION_2 = -1564019 , SAY_ATTRACTION_3 = -1564020 , SAY_AGGRO = -1564021 ,
SAY_BEAM_1 = -1564022 , SAY_BEAM_2 = -1564023 , SAY_BEAM_3 = -1564024 , SAY_SLAY_1 = 21774 ,
SAY_SLAY_2 = 21775 , SAY_ENRAGE = -1564027 , SAY_DEATH = -1564028 , SPELL_SINFUL_PERIODIC = 40862 ,
SPELL_SINISTER_PERIODIC = 40863 , SPELL_VILE_PERIODIC = 40865 , SPELL_WICKED_PERIODIC = 40866 , SPELL_RANDOM_PERIODIC = 40867 ,
SPELL_FATAL_ATTRACTION = 40869 , SPELL_SILENCING_SHRIEK = 40823 , SPELL_SABER_LASH_PROC = 40816 , SPELL_FRENZY = 23537 ,
SPELL_BERSERK = 45078
}
enum ShahrazActions {
SHAHRAZ_ACTION_BERSERK , SHAHRAZ_ACTION_FRENZY , SHAHRAZ_ACTION_FATAL_ATTRACTION , SHAHRAZ_ACTION_BEAM ,
SHAHRAZ_ACTION_SHRIEK , SHAHRAZ_ACTION_PRISMATIC_SHIELD , SHAHRAZ_ACTION_MAX
}
Functions
UnitAI * GetAI_boss_shahraz (Creature *creature)
void AddSC_boss_mother_shahraz ()
Variables
static const uint32 aPrismaticAuras []
static const uint32 aPeriodicBeams [] = {SPELL_SINFUL_PERIODIC, SPELL_SINISTER_PERIODIC, SPELL_VILE_PERIODIC, SPELL_WICKED_PERIODIC}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ATTRACTION_1
SAY_ATTRACTION_2
SAY_ATTRACTION_3
SAY_AGGRO
SAY_BEAM_1
SAY_BEAM_2
SAY_BEAM_3
SAY_SLAY_1
SAY_SLAY_2
SAY_ENRAGE
SAY_DEATH
SPELL_SINFUL_PERIODIC
SPELL_SINISTER_PERIODIC
SPELL_VILE_PERIODIC
SPELL_WICKED_PERIODIC
SPELL_RANDOM_PERIODIC
SPELL_FATAL_ATTRACTION
SPELL_SILENCING_SHRIEK
SPELL_SABER_LASH_PROC
SPELL_FRENZY
SPELL_BERSERK
Definition at line 28 of file boss_mother_shahraz.cpp.
ShahrazActions
enum ShahrazActions
Enumerator
SHAHRAZ_ACTION_BERSERK
SHAHRAZ_ACTION_FRENZY
SHAHRAZ_ACTION_FATAL_ATTRACTION
SHAHRAZ_ACTION_BEAM
SHAHRAZ_ACTION_SHRIEK
SHAHRAZ_ACTION_PRISMATIC_SHIELD
SHAHRAZ_ACTION_MAX
Definition at line 68 of file boss_mother_shahraz.cpp.
Function Documentation
AddSC_boss_mother_shahraz()
void AddSC_boss_mother_shahraz ()
Definition at line 231 of file boss_mother_shahraz.cpp.
References Script::GetAI, GetAI_boss_shahraz(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_shahraz()
UnitAI* GetAI_boss_shahraz (Creature * creature)
Definition at line 226 of file boss_mother_shahraz.cpp.
Referenced by AddSC_boss_mother_shahraz().
Variable Documentation
aPeriodicBeams
const uint32 aPeriodicBeams[] = {SPELL_SINFUL_PERIODIC, SPELL_SINISTER_PERIODIC, SPELL_VILE_PERIODIC, SPELL_WICKED_PERIODIC} static
Definition at line 66 of file boss_mother_shahraz.cpp.
Referenced by boss_shahrazAI::ExecuteAction().
aPrismaticAuras
const uint32 aPrismaticAuras[] static
Initial value:
=
{
    40880,
    40882,
    40883,
    40891,
    40896,
    40897,
}
Definition at line 56 of file boss_mother_shahraz.cpp.
Referenced by boss_shahrazAI::ExecuteAction().