var boss__faction__champions_8cpp =
[
    [ "CrusaderAbilityStruct", "structCrusaderAbilityStruct.html", "structCrusaderAbilityStruct" ],
    [ "trial_crusader_commonAI", "structtrial__crusader__commonAI.html", "structtrial__crusader__commonAI" ],
    [ "boss_crusader_druid_restoAI", "structboss__crusader__druid__restoAI.html", "structboss__crusader__druid__restoAI" ],
    [ "boss_crusader_paladin_holyAI", "structboss__crusader__paladin__holyAI.html", "structboss__crusader__paladin__holyAI" ],
    [ "boss_crusader_priest_discAI", "structboss__crusader__priest__discAI.html", "structboss__crusader__priest__discAI" ],
    [ "boss_crusader_shaman_restoAI", "structboss__crusader__shaman__restoAI.html", "structboss__crusader__shaman__restoAI" ],
    [ "boss_crusader_druid_balanceAI", "structboss__crusader__druid__balanceAI.html", "structboss__crusader__druid__balanceAI" ],
    [ "boss_crusader_hunterAI", "structboss__crusader__hunterAI.html", "structboss__crusader__hunterAI" ],
    [ "boss_crusader_mageAI", "structboss__crusader__mageAI.html", "structboss__crusader__mageAI" ],
    [ "boss_crusader_priest_shadowAI", "structboss__crusader__priest__shadowAI.html", "structboss__crusader__priest__shadowAI" ],
    [ "boss_crusader_warlockAI", "structboss__crusader__warlockAI.html", "structboss__crusader__warlockAI" ],
    [ "boss_crusader_death_knightAI", "structboss__crusader__death__knightAI.html", "structboss__crusader__death__knightAI" ],
    [ "boss_crusader_warriorAI", "structboss__crusader__warriorAI.html", "structboss__crusader__warriorAI" ],
    [ "boss_crusader_paladin_retriAI", "structboss__crusader__paladin__retriAI.html", "structboss__crusader__paladin__retriAI" ],
    [ "boss_crusader_shaman_enhaAI", "structboss__crusader__shaman__enhaAI.html", "structboss__crusader__shaman__enhaAI" ],
    [ "boss_crusader_rogueAI", "structboss__crusader__rogueAI.html", "structboss__crusader__rogueAI" ],
    [ "spell_disengage", "structspell__disengage.html", "structspell__disengage" ],
    [ "AddSC_boss_faction_champions", "boss__faction__champions_8cpp.html#a2c605e9c8b27e970c308e89491e4b541", null ],
    [ "m_aDeathKnightAbilities", "boss__faction__champions_8cpp.html#a795d19bcf2ea85c97f43b0acf75899f4", null ],
    [ "m_aDruidDamageAbilities", "boss__faction__champions_8cpp.html#aba330fb8525f142a9d99e69ab6e5e36f", null ],
    [ "m_aDruidHealerAbilities", "boss__faction__champions_8cpp.html#ab18409de17840030b2b863f353e1c630", null ],
    [ "m_aHunterAbilities", "boss__faction__champions_8cpp.html#aeb23f605dd2311bd74fa3acb9c3132d9", null ],
    [ "m_aMageAbilities", "boss__faction__champions_8cpp.html#afce9ca79b48a893e4acdd163f7ef672f", null ],
    [ "m_aPaladinDamageAbilities", "boss__faction__champions_8cpp.html#a48b6fde184c5585b3777ed3b789f645c", null ],
    [ "m_aPaladinHealerAbilities", "boss__faction__champions_8cpp.html#acf8c245f8bb095cb1bd0f754c3783189", null ],
    [ "m_aPriestDamageAbilities", "boss__faction__champions_8cpp.html#aa0f413046fd53df16835ea521a4bcba8", null ],
    [ "m_aPriestHealerAbilities", "boss__faction__champions_8cpp.html#a0f6edc0c91f72e7eab2553ad86f7dd17", null ],
    [ "m_aRogueAbilities", "boss__faction__champions_8cpp.html#a76bda89fec45b57ad973811e656890a9", null ],
    [ "m_aShamanDamageAbilities", "boss__faction__champions_8cpp.html#a7988a9e74f76ed6e00f52ebb231b09b6", null ],
    [ "m_aShamanHealerAbilities", "boss__faction__champions_8cpp.html#a38e08161e20abf62dda8f2b1fa4bc232", null ],
    [ "m_aWarlockAbilities", "boss__faction__champions_8cpp.html#a5eb2d0585ac28cd691411a502d2f798b", null ],
    [ "m_aWarriorAbilities", "boss__faction__champions_8cpp.html#a15848ed2a7128160925ae8914786abdb", null ]
];