CMaNGOS_WoTLK: boss_black_knight.cpp File Reference
boss_black_knight.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_champion.h"
Data Structures
struct boss_black_knightAI
struct npc_black_knight_ghoulAI
struct npc_black_knight_gryphonAI
Enumerations
enum {
SAY_PHASE_2 = -1650066 , SAY_PHASE_3 = -1650067 , SAY_KILL_1 = -1650068 , SAY_KILL_2 = -1650069 ,
SAY_DEATH = -1650070 , SPELL_KILL_CREDIT = 68663 , SPELL_FEIGN_DEATH = 67691 , SPELL_CLEAR_ALL_DEBUFFS = 34098 ,
SPELL_FULL_HEAL = 17683 , SPELL_BLACK_KNIGHT_RES = 67693 , SPELL_RAISE_DEAD_ARELAS = 67705 , SPELL_RAISE_DEAD_JAEREN = 67715 ,
SPELL_DEATHS_RESPITE = 67745 , SPELL_ICY_TOUCH = 67718 , SPELL_OBLITERATE = 67725 , SPELL_PLAGUE_STRIKE = 67724 ,
SPELL_ARMY_OF_THE_DEAD = 67761 , SPELL_DESECRATION = 67778 , SPELL_GHOUL_EXPLODE = 67751 , SPELL_DEATHS_BITE = 67808 ,
SPELL_MARKED_FOR_DEATH = 67823 , SPELL_CLAW = 67774 , SPELL_EXPLODE = 67729 , SPELL_LEAP = 67749 ,
NPC_RISEN_JAEREN = 35545 , NPC_RISEN_ARELAS = 35564 , NPC_RISEN_CHAMPION = 35590 , MODEL_ID_SKELETON = 29846 ,
MODEL_ID_GHOST = 21300 , EQUIP_ID_SWORD = 40343 , PHASE_DEATH_KNIGHT = 1 , PHASE_SKELETON = 2 ,
PHASE_GHOST = 3 , PHASE_TRANSITION = 4
}
Functions
UnitAI * GetAI_boss_black_knight (Creature *pCreature)
bool EffectDummyCreature_black_knight_res (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_black_knight_ghoul (Creature *pCreature)
UnitAI * GetAI_npc_black_knight_gryphon (Creature *pCreature)
void AddSC_boss_black_knight ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PHASE_2
SAY_PHASE_3
SAY_KILL_1
SAY_KILL_2
SAY_DEATH
SPELL_KILL_CREDIT
SPELL_FEIGN_DEATH
SPELL_CLEAR_ALL_DEBUFFS
SPELL_FULL_HEAL
SPELL_BLACK_KNIGHT_RES
SPELL_RAISE_DEAD_ARELAS
SPELL_RAISE_DEAD_JAEREN
SPELL_DEATHS_RESPITE
SPELL_ICY_TOUCH
SPELL_OBLITERATE
SPELL_PLAGUE_STRIKE
SPELL_ARMY_OF_THE_DEAD
SPELL_DESECRATION
SPELL_GHOUL_EXPLODE
SPELL_DEATHS_BITE
SPELL_MARKED_FOR_DEATH
SPELL_CLAW
SPELL_EXPLODE
SPELL_LEAP
NPC_RISEN_JAEREN
NPC_RISEN_ARELAS
NPC_RISEN_CHAMPION
MODEL_ID_SKELETON
MODEL_ID_GHOST
EQUIP_ID_SWORD
PHASE_DEATH_KNIGHT
PHASE_SKELETON
PHASE_GHOST
PHASE_TRANSITION
Definition at line 27 of file boss_black_knight.cpp.
Function Documentation
AddSC_boss_black_knight()
void AddSC_boss_black_knight ()
Definition at line 458 of file boss_black_knight.cpp.
References EffectDummyCreature_black_knight_res(), Script::GetAI, GetAI_boss_black_knight(), GetAI_npc_black_knight_ghoul(), GetAI_npc_black_knight_gryphon(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_black_knight_res()
bool EffectDummyCreature_black_knight_res (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 356 of file boss_black_knight.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, UnitAI::SendAIEvent(), and SPELL_BLACK_KNIGHT_RES.
Referenced by AddSC_boss_black_knight().
GetAI_boss_black_knight()
UnitAI* GetAI_boss_black_knight (Creature * pCreature)
Definition at line 351 of file boss_black_knight.cpp.
Referenced by AddSC_boss_black_knight().
GetAI_npc_black_knight_ghoul()
UnitAI* GetAI_npc_black_knight_ghoul (Creature * pCreature)
Definition at line 433 of file boss_black_knight.cpp.
Referenced by AddSC_boss_black_knight().
GetAI_npc_black_knight_gryphon()
UnitAI* GetAI_npc_black_knight_gryphon (Creature * pCreature)
Definition at line 453 of file boss_black_knight.cpp.
Referenced by AddSC_boss_black_knight().