CMaNGOS_WoTLK: boss_jedoga.cpp File Reference
boss_jedoga.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ahnkahet.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_jedogaAI
struct npc_twilight_volunteerAI
Enumerations
enum {
SAY_AGGRO = -1619017 , SAY_CALL_SACRIFICE1 = -1619018 , SAY_CALL_SACRIFICE2 = -1619019 , SAY_SACRIFICE1 = -1619020 ,
SAY_SACRIFICE2 = -1619021 , SAY_SLAY_1 = -1619022 , SAY_SLAY_2 = -1619023 , SAY_SLAY_3 = -1619024 ,
SAY_DEATH = -1619025 , SAY_PREACHING1 = -1619026 , SAY_PREACHING2 = -1619027 , SAY_PREACHING3 = -1619028 ,
SAY_PREACHING4 = -1619029 , SAY_PREACHING5 = -1619030 , SAY_VOLUNTEER_CHOOSEN = -1619031 , SAY_VOLUNTEER_SACRIFICED = -1619032 ,
SPELL_BEAM_VISUAL = 56312 , SPELL_SPHERE_VISUAL = 56075 , SPELL_LIGHTNING_VISUAL = 56327 , SPELL_CYCLONE_STRIKE = 56855 ,
SPELL_CYCLONE_STRIKE_H = 60030 , SPELL_LIGHTNING_BOLT = 56891 , SPELL_LIGHTNING_BOLT_H = 60032 , SPELL_THUNDERSHOCK = 56926 ,
SPELL_THUNDERSHOCK_H = 60029 , SPELL_HOVER_FALL = 56100 , SPELL_SACRIFICE_VISUAL = 56133 , SPELL_SACRIFICE_BEAM = 56150 ,
SPELL_VOLUNTEER_SPHERE = 56102 , SPELL_PILLAR_LIGHTNING = 56868 , NPC_TWILIGHT_VOLUNTEER = 30385 , MAX_VOLUNTEERS_PER_SIDE = 13 ,
POINT_ID_PREPARE = 1 , POINT_ID_SACRIFICE = 2 , POINT_ID_LEVITATE = 3 , POINT_ID_COMBAT = 4
}
Functions
UnitAI * GetAI_boss_jedoga (Creature *pCreature)
UnitAI * GetAI_npc_twilight_volunteer (Creature *pCreature)
bool EffectAuraDummy_spell_aura_dummy_sacrifice_beam (const Aura *pAura, bool bApply)
void AddSC_boss_jedoga ()
Variables
static const float aVolunteerPosition [2][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_CALL_SACRIFICE1
SAY_CALL_SACRIFICE2
SAY_SACRIFICE1
SAY_SACRIFICE2
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
SAY_PREACHING1
SAY_PREACHING2
SAY_PREACHING3
SAY_PREACHING4
SAY_PREACHING5
SAY_VOLUNTEER_CHOOSEN
SAY_VOLUNTEER_SACRIFICED
SPELL_BEAM_VISUAL
SPELL_SPHERE_VISUAL
SPELL_LIGHTNING_VISUAL
SPELL_CYCLONE_STRIKE
SPELL_CYCLONE_STRIKE_H
SPELL_LIGHTNING_BOLT
SPELL_LIGHTNING_BOLT_H
SPELL_THUNDERSHOCK
SPELL_THUNDERSHOCK_H
SPELL_HOVER_FALL
SPELL_SACRIFICE_VISUAL
SPELL_SACRIFICE_BEAM
SPELL_VOLUNTEER_SPHERE
SPELL_PILLAR_LIGHTNING
NPC_TWILIGHT_VOLUNTEER
MAX_VOLUNTEERS_PER_SIDE
POINT_ID_PREPARE
POINT_ID_SACRIFICE
POINT_ID_LEVITATE
POINT_ID_COMBAT
Definition at line 28 of file boss_jedoga.cpp.
Function Documentation
AddSC_boss_jedoga()
void AddSC_boss_jedoga ()
Definition at line 459 of file boss_jedoga.cpp.
References EffectAuraDummy_spell_aura_dummy_sacrifice_beam(), Script::GetAI, GetAI_boss_jedoga(), GetAI_npc_twilight_volunteer(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_sacrifice_beam()
bool EffectAuraDummy_spell_aura_dummy_sacrifice_beam (const Aura * pAura, bool bApply)
Definition at line 449 of file boss_jedoga.cpp.
References EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), and SPELL_SACRIFICE_BEAM.
Referenced by AddSC_boss_jedoga().
GetAI_boss_jedoga()
UnitAI* GetAI_boss_jedoga (Creature * pCreature)
Definition at line 408 of file boss_jedoga.cpp.
Referenced by AddSC_boss_jedoga().
GetAI_npc_twilight_volunteer()
UnitAI* GetAI_npc_twilight_volunteer (Creature * pCreature)
Definition at line 444 of file boss_jedoga.cpp.
Referenced by AddSC_boss_jedoga().
Variable Documentation
aVolunteerPosition
const float aVolunteerPosition[2][3] static
Initial value:
=
{
    {456.09f, -724.34f, -31.58f},
    {410.11f, -785.46f, -31.58f},
}
Definition at line 77 of file boss_jedoga.cpp.
Referenced by boss_jedogaAI::DoCallVolunteers().