CMaNGOS_WoTLK: boss_yor.cpp File Reference
boss_yor.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct boss_yorAI
struct npc_ethereum_prisoner_dungeonAI
Enumerations
enum {
SPELL_C_C_D = 35465 , SPELL_PURPLE_BANISH_STATE = 32566 , FACTION_HOSTILE = 14 , NPC_YOR = 22930 ,
SPELL_STOMP = 36405 , SPELL_DOUBLE_BREATH = 38361 , NPC_STASIS_PRISONER_DUNGEON = 22927
}
enum YorActions { YOR_ACTION_STOMP , YOR_ACTION_DOUBLE_BREATH , YOR_COMBAT_ACTION_MAX , YOR_ATTACK }
enum PrisonerActions {
PRISONER_ATTACK , PRISONER_TALK , PRISONER_CAST , PRISONER_CREDIT ,
PRISONER_ATTACK , PRISONER_TALK , PRISONER_CAST
}
enum {
SPELL_BLUE_BANISH_STATE = 39650 , SAY_RELEASED_1 = -1557036 , SAY_RELEASED_2 = -1557037 , NPC_AMBASSADOR_PAXIVI = 22928 ,
SPELL_QID_10977 = 39660
}
Functions
bool GOUse_go_stasis_chamber_shaffar (Player *player, GameObject *go)
UnitAI * GetAInpc_ethereum_prisoner_dungeon (Creature *creature)
bool GOUse_go_stasis_chamber_mana_tombs (Player *player, GameObject *go)
void AddSC_boss_yor ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_C_C_D
SPELL_PURPLE_BANISH_STATE
FACTION_HOSTILE
NPC_YOR
SPELL_STOMP
SPELL_DOUBLE_BREATH
NPC_STASIS_PRISONER_DUNGEON
Definition at line 32 of file boss_yor.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BLUE_BANISH_STATE
SAY_RELEASED_1
SAY_RELEASED_2
NPC_AMBASSADOR_PAXIVI
SPELL_QID_10977
Definition at line 191 of file boss_yor.cpp.
PrisonerActions
enum PrisonerActions
Enumerator
PRISONER_ATTACK
PRISONER_TALK
PRISONER_CAST
PRISONER_CREDIT
PRISONER_ATTACK
PRISONER_TALK
PRISONER_CAST
Definition at line 55 of file boss_yor.cpp.
YorActions
enum YorActions
Enumerator
YOR_ACTION_STOMP
YOR_ACTION_DOUBLE_BREATH
YOR_COMBAT_ACTION_MAX
YOR_ATTACK
Definition at line 47 of file boss_yor.cpp.
Function Documentation
AddSC_boss_yor()
void AddSC_boss_yor ()
Definition at line 282 of file boss_yor.cpp.
References Script::GetAI, GetAInpc_ethereum_prisoner_dungeon(), GOUse_go_stasis_chamber_mana_tombs(), GOUse_go_stasis_chamber_shaffar(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetAInpc_ethereum_prisoner_dungeon()
UnitAI* GetAInpc_ethereum_prisoner_dungeon (Creature * creature)
Definition at line 263 of file boss_yor.cpp.
References WorldObject::GetPositionX().
Referenced by AddSC_boss_yor().
GOUse_go_stasis_chamber_mana_tombs()
bool GOUse_go_stasis_chamber_mana_tombs (Player * player, GameObject * go)
Definition at line 271 of file boss_yor.cpp.
References GetClosestCreatureWithEntry(), NPC_STASIS_PRISONER_DUNGEON, and npc_ethereum_prisoner_dungeonAI::StartEvent().
Referenced by AddSC_boss_yor().
GOUse_go_stasis_chamber_shaffar()
bool GOUse_go_stasis_chamber_shaffar (Player * player, GameObject * go)
Definition at line 180 of file boss_yor.cpp.
References GetClosestCreatureWithEntry(), NPC_STASIS_PRISONER_DUNGEON, and boss_yorAI::StartEvent().
Referenced by AddSC_boss_yor().