CMaNGOS_WoTLK: boss_general_angerforge.cpp File Reference
boss_general_angerforge.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_general_angerforgeAI
Enumerations
enum {
EMOTE_ALARM = -1230035 , SPELL_FLURRY = 15088 , SPELL_ENRAGE = 15097 , SPELL_SUNDER_ARMOR = 15572 ,
NPC_ANVILRAGE_MEDIC = 8894 , NPC_ANVILRAGE_RESERVIST = 8901 , NPC_ELITE_AMOUNT = 2 , NPC_NORMAL_AMOUNT = 8
}
Functions
UnitAI * GetAI_boss_general_angerforge (Creature *pCreature)
void AddSC_boss_general_angerforge ()
Variables
static const float aAlarmPoint [4] = {717.343f, 22.116f, -45.4321f, 3.1415f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_ALARM
SPELL_FLURRY
SPELL_ENRAGE
SPELL_SUNDER_ARMOR
NPC_ANVILRAGE_MEDIC
NPC_ANVILRAGE_RESERVIST
NPC_ELITE_AMOUNT
NPC_NORMAL_AMOUNT
Definition at line 26 of file boss_general_angerforge.cpp.
Function Documentation
AddSC_boss_general_angerforge()
void AddSC_boss_general_angerforge ()
Definition at line 117 of file boss_general_angerforge.cpp.
References Script::GetAI, GetAI_boss_general_angerforge(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_general_angerforge()
UnitAI* GetAI_boss_general_angerforge (Creature * pCreature)
Definition at line 112 of file boss_general_angerforge.cpp.
Referenced by AddSC_boss_general_angerforge().
Variable Documentation
aAlarmPoint
const float aAlarmPoint[4] = {717.343f, 22.116f, -45.4321f, 3.1415f} static
Definition at line 41 of file boss_general_angerforge.cpp.
Referenced by boss_general_angerforgeAI::SummonAdd().