CMaNGOS_WoTLK: boss_rotface.cpp File Reference
boss_rotface.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_rotfaceAI
struct mob_little_oozeAI
struct mob_big_oozeAI
Enumerations
enum {
SAY_AGGRO = -1631071 , SAY_OOZE_EXPLODE = -1631073 , SAY_SLAY_1 = -1631076 , SAY_SLAY_2 = -1631077 ,
SAY_BERSERK = -1631078 , SAY_DEATH = -1631079 , SAY_PUTRICIDE_AGGRO = -1631091 , EMOTE_SLIME_SPRAY = -1631202 ,
EMOTE_OOZE_GROW_1 = -1631203 , EMOTE_OOZE_GROW_2 = -1631204 , EMOTE_OOZE_GROW_3 = -1631205 , SPELL_MUTATED_INFECTION_1 = 70090 ,
SPELL_MUTATED_INFECTION_2 = 70003 , SPELL_MUTATED_INFECTION_3 = 70004 , SPELL_MUTATED_INFECTION_4 = 70005 , SPELL_MUTATED_INFECTION_5 = 70006 ,
SPELL_SLIME_SPRAY_SUMMON = 70882 , SPELL_FACE_SPRAY_STALKER = 70881 , SPELL_SLIME_SPRAY = 69508 , SPELL_OOZE_FLOOD_PERIODIC = 70069 ,
SPELL_OOZE_FLOOD_REMOVE = 70079 , SPELL_GREEN_ABOMINATION_HIT = 70001 , SPELL_WEAK_RADIATING_OOZE = 69750 , SPELL_LITTLE_OOZE_COMBINE = 69537 ,
SPELL_STICKY_OOZE = 69774 , SPELL_STICKY_AURA = 69776 , SPELL_UNSTABLE_OOZE = 69558 , SPELL_RADIATING_OOZE = 69760 ,
SPELL_BIG_OOZE_COMBINE = 69552 , SPELL_BIG_OOZE_BUFF_COMB = 69611 , SPELL_UNSTABLE_EXPLOSION = 69839 , SPELL_OOZE_EXPLOSION = 69832 ,
SPELL_VILE_TRIGGER = 72285 , SPELL_VILE_GAS = 72272 , NPC_LITTLE_OOZE = 36897 , NPC_STICKY_OOZE = 37006 ,
NPC_BIG_OOZE = 36899 , NPC_VILE_GAS_STALKER = 38548 , NPC_OOZE_SPRAY_STALKER = 37986 , NPC_OOZE_EXPLOSION_STALKER = 38107 ,
MAX_MUTATE_INFACTION_STEPS = 5
}
Functions
UnitAI * GetAI_boss_rotface (Creature *pCreature)
UnitAI * GetAI_mob_little_ooze (Creature *pCreature)
UnitAI * GetAI_mob_big_ooze (Creature *pCreature)
bool EffectScriptEffectCreature_spell_unstable_ooze (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_rotface ()
Variables
static const uint32 uiMutatedInfections [MAX_MUTATE_INFACTION_STEPS]
static const float afBalconyLocation [3] = {4390.371f, 3164.5f, 389.389f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_OOZE_EXPLODE
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
SAY_PUTRICIDE_AGGRO
EMOTE_SLIME_SPRAY
EMOTE_OOZE_GROW_1
EMOTE_OOZE_GROW_2
EMOTE_OOZE_GROW_3
SPELL_MUTATED_INFECTION_1
SPELL_MUTATED_INFECTION_2
SPELL_MUTATED_INFECTION_3
SPELL_MUTATED_INFECTION_4
SPELL_MUTATED_INFECTION_5
SPELL_SLIME_SPRAY_SUMMON
SPELL_FACE_SPRAY_STALKER
SPELL_SLIME_SPRAY
SPELL_OOZE_FLOOD_PERIODIC
SPELL_OOZE_FLOOD_REMOVE
SPELL_GREEN_ABOMINATION_HIT
SPELL_WEAK_RADIATING_OOZE
SPELL_LITTLE_OOZE_COMBINE
SPELL_STICKY_OOZE
SPELL_STICKY_AURA
SPELL_UNSTABLE_OOZE
SPELL_RADIATING_OOZE
SPELL_BIG_OOZE_COMBINE
SPELL_BIG_OOZE_BUFF_COMB
SPELL_UNSTABLE_EXPLOSION
SPELL_OOZE_EXPLOSION
SPELL_VILE_TRIGGER
SPELL_VILE_GAS
NPC_LITTLE_OOZE
NPC_STICKY_OOZE
NPC_BIG_OOZE
NPC_VILE_GAS_STALKER
NPC_OOZE_SPRAY_STALKER
NPC_OOZE_EXPLOSION_STALKER
MAX_MUTATE_INFACTION_STEPS
Definition at line 28 of file boss_rotface.cpp.
Function Documentation
AddSC_boss_rotface()
void AddSC_boss_rotface ()
Definition at line 452 of file boss_rotface.cpp.
References EffectScriptEffectCreature_spell_unstable_ooze(), Script::GetAI, GetAI_boss_rotface(), GetAI_mob_big_ooze(), GetAI_mob_little_ooze(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectScriptEffectCreature_spell_unstable_ooze()
bool EffectScriptEffectCreature_spell_unstable_ooze (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 420 of file boss_rotface.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, DoScriptText(), EFFECT_INDEX_2, EMOTE_OOZE_GROW_1, EMOTE_OOZE_GROW_2, EMOTE_OOZE_GROW_3, Object::GetEntry(), Unit::GetSpellAuraHolder(), SpellAuraHolder::GetStackAmount(), NPC_BIG_OOZE, UnitAI::SendAIEvent(), and SPELL_UNSTABLE_OOZE.
Referenced by AddSC_boss_rotface().
GetAI_boss_rotface()
UnitAI* GetAI_boss_rotface (Creature * pCreature)
Definition at line 262 of file boss_rotface.cpp.
Referenced by AddSC_boss_rotface().
GetAI_mob_big_ooze()
UnitAI* GetAI_mob_big_ooze (Creature * pCreature)
Definition at line 415 of file boss_rotface.cpp.
Referenced by AddSC_boss_rotface().
GetAI_mob_little_ooze()
UnitAI* GetAI_mob_little_ooze (Creature * pCreature)
Definition at line 309 of file boss_rotface.cpp.
Referenced by AddSC_boss_rotface().
Variable Documentation
afBalconyLocation
const float afBalconyLocation[3] = {4390.371f, 3164.5f, 389.389f} static
Definition at line 105 of file boss_rotface.cpp.
Referenced by boss_rotfaceAI::Aggro().
uiMutatedInfections
const uint32 uiMutatedInfections[MAX_MUTATE_INFACTION_STEPS] static
Initial value:
=
{
    SPELL_MUTATED_INFECTION_1,
    SPELL_MUTATED_INFECTION_2,
    SPELL_MUTATED_INFECTION_3,
    SPELL_MUTATED_INFECTION_4,
    SPELL_MUTATED_INFECTION_5
}
Definition at line 96 of file boss_rotface.cpp.
Referenced by boss_rotfaceAI::UpdateAI().