CMaNGOS_WoTLK: boss_professor_putricide.cpp File Reference
boss_professor_putricide.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
Data Structures
struct boss_professor_putricideAI
struct npc_volatile_ooze_iccAI
struct npc_gas_cloud_iccAI
struct npc_growing_ooze_puddleAI
struct npc_choking_gas_bombAI
struct npc_puddle_stalkerAI
Enumerations
enum {
SAY_AGGRO = -1631092 , SAY_AIRLOCK = -1631093 , SAY_PHASE_CHANGE = -1631094 , SAY_TRANSFORM_1 = -1631095 ,
SAY_TRANSFORM_2 = -1631096 , SAY_SLAY_1 = -1631097 , SAY_SLAY_2 = -1631098 , SAY_BERSERK = -1631099 ,
SAY_DEATH = -1631100 , EMOTE_EXPERIMENT = -1631206 , SAY_SLIME_FLOW_1 = -1631074 , SAY_SLIME_FLOW_2 = -1631075 ,
SPELL_BERSERK = 47008 , SPELL_ORANGE_OOZE_SUMMON = 71415 , SPELL_GREEN_OOZE_SUMMON = 71412 , SPELL_SLIME_PUDDLE_SUMMON = 70341 ,
SPELL_SLIME_PUDDLE_TRIGGER = 71424 , SPELL_UNSTABLE_EXPERIMENT = 70351 , SPELL_CREATE_CONCOCTION = 71621 , SPELL_MALLEABLE_GOO = 72295 ,
SPELL_CHOKING_GAS_BOMB = 71255 , SPELL_TEAR_GAS = 71617 , SPELL_TEAR_GAS_CANCEL = 71620 , SPELL_TEAR_GAS_PERIODIC = 73170 ,
SPELL_VOLATILE_EXPERIMENT = 72840 , SPELL_CLEANSE_MUTATION = 71693 , SPELL_GUZZLE_POTIONS = 71893 , SPELL_MUTATED_PLAGUE = 72451 ,
SPELL_UNBOUND_PLAGUE = 70911 , SPELL_OOZE_VARIABLE = 70352 , SPELL_OOZE_VARIABLE_OOZE = 74118 , SPELL_GAS_VARIABLE = 70353 ,
SPELL_GAS_VARIABLE_GAS = 74119 , SPELL_OOZE_TANK_PROTECTION = 71770 , SPELL_OOZE_FLOOD_TRIGGER = 69795 , SPELL_OOZE_FLOOD = 69782 ,
SPELL_SLIME_PUDDLE_DAMAGE = 70343 , SPELL_GROW_STACKER = 70345 , SPELL_EAT_OOZE = 70360 , SPELL_CHOKING_GAS_PERIODIC = 71259 ,
SPELL_CHOKING_GAS_EXPLOSION_PER = 71280 , SPELL_OOZE_ADHESIVE = 70447 , SPELL_OOZE_ERUPTION = 70492 , SPELL_GASEOUS_BLOAT = 70672 ,
SPELL_EXPUNGED_GAS = 70701 , SPELL_GASEOUS_BLOAT_VISUAL = 70215 , NPC_GROWING_OOZE_PUDDLE_TRIGGER = 38234 , NPC_GROWING_OOZE_PUDDLE = 37690 ,
NPC_GAS_CLOUD = 37562 , NPC_VOLATILE_OOZE = 37697 , NPC_CHOKING_GAS_BOMB = 38159
}
enum Phase {
PHASE_ONE = 1 , PHASE_RUNNING_ONE = 2 , PHASE_TRANSITION_ONE = 3 , PHASE_TWO = 4 ,
PHASE_RUNNING_TWO = 5 , PHASE_TRANSITION_TWO = 6 , PHASE_THREE = 7 , PHASE_INTRO = 0 ,
PHASE_ONE = 1 , PHASE_RUNNING_WINTER_ONE = 2 , PHASE_TRANSITION_ONE = 3 , PHASE_QUAKE_ONE = 4 ,
PHASE_TWO = 5 , PHASE_RUNNING_WINTER_TWO = 6 , PHASE_TRANSITION_TWO = 7 , PHASE_QUAKE_TWO = 8 ,
PHASE_THREE = 9 , PHASE_IN_FROSTMOURNE = 10 , PHASE_CUTSCENE = 11 , PHASE_DEATH_AWAITS = 12 ,
PHASE_INTRO , PHASE_NORMAL , PHASE_GUARDIANS
}
enum Waypoint { POINT_PUTRICIDE_SPAWN = 1 , POINT_FESTERGUT_BALCONY = 101 , POINT_ROTFACE_BALCONY = 102 }
Functions
UnitAI * GetAI_boss_professor_putricide (Creature *pCreature)
bool EffectScriptEffectCreature_npc_putricide (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectDummyCreature_npc_putricide (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_volatile_ooze_icc (Creature *pCreature)
UnitAI * GetAI_npc_gas_cloud_icc (Creature *pCreature)
UnitAI * GetAI_npc_growing_ooze_puddle (Creature *pCreature)
bool EffectScriptEffectCreature_spell_eat_ooze (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_choking_gas_bomb (Creature *pCreature)
UnitAI * GetAI_npc_puddle_stalker (Creature *pCreature)
bool EffectScriptEffectCreature_spell_ooze_flood (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_professor_putricide ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_AIRLOCK
SAY_PHASE_CHANGE
SAY_TRANSFORM_1
SAY_TRANSFORM_2
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
EMOTE_EXPERIMENT
SAY_SLIME_FLOW_1
SAY_SLIME_FLOW_2
SPELL_BERSERK
SPELL_ORANGE_OOZE_SUMMON
SPELL_GREEN_OOZE_SUMMON
SPELL_SLIME_PUDDLE_SUMMON
SPELL_SLIME_PUDDLE_TRIGGER
SPELL_UNSTABLE_EXPERIMENT
SPELL_CREATE_CONCOCTION
SPELL_MALLEABLE_GOO
SPELL_CHOKING_GAS_BOMB
SPELL_TEAR_GAS
SPELL_TEAR_GAS_CANCEL
SPELL_TEAR_GAS_PERIODIC
SPELL_VOLATILE_EXPERIMENT
SPELL_CLEANSE_MUTATION
SPELL_GUZZLE_POTIONS
SPELL_MUTATED_PLAGUE
SPELL_UNBOUND_PLAGUE
SPELL_OOZE_VARIABLE
SPELL_OOZE_VARIABLE_OOZE
SPELL_GAS_VARIABLE
SPELL_GAS_VARIABLE_GAS
SPELL_OOZE_TANK_PROTECTION
SPELL_OOZE_FLOOD_TRIGGER
SPELL_OOZE_FLOOD
SPELL_SLIME_PUDDLE_DAMAGE
SPELL_GROW_STACKER
SPELL_EAT_OOZE
SPELL_CHOKING_GAS_PERIODIC
SPELL_CHOKING_GAS_EXPLOSION_PER
SPELL_OOZE_ADHESIVE
SPELL_OOZE_ERUPTION
SPELL_GASEOUS_BLOAT
SPELL_EXPUNGED_GAS
SPELL_GASEOUS_BLOAT_VISUAL
NPC_GROWING_OOZE_PUDDLE_TRIGGER
NPC_GROWING_OOZE_PUDDLE
NPC_GAS_CLOUD
NPC_VOLATILE_OOZE
NPC_CHOKING_GAS_BOMB
Definition at line 27 of file boss_professor_putricide.cpp.
Phase
enum Phase
Enumerator
PHASE_ONE
PHASE_RUNNING_ONE
PHASE_TRANSITION_ONE
PHASE_TWO
PHASE_RUNNING_TWO
PHASE_TRANSITION_TWO
PHASE_THREE
PHASE_INTRO
PHASE_ONE
PHASE_RUNNING_WINTER_ONE
PHASE_TRANSITION_ONE
PHASE_QUAKE_ONE
PHASE_TWO
PHASE_RUNNING_WINTER_TWO
PHASE_TRANSITION_TWO
PHASE_QUAKE_TWO
PHASE_THREE
PHASE_IN_FROSTMOURNE
PHASE_CUTSCENE
PHASE_DEATH_AWAITS
PHASE_INTRO
PHASE_NORMAL
PHASE_GUARDIANS
Definition at line 121 of file boss_professor_putricide.cpp.
Waypoint
enum Waypoint
Enumerator
POINT_PUTRICIDE_SPAWN
POINT_FESTERGUT_BALCONY
POINT_ROTFACE_BALCONY
Definition at line 132 of file boss_professor_putricide.cpp.
Function Documentation
AddSC_boss_professor_putricide()
void AddSC_boss_professor_putricide ()
Definition at line 788 of file boss_professor_putricide.cpp.
References EffectDummyCreature_npc_putricide(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_spell_eat_ooze(), EffectScriptEffectCreature_spell_ooze_flood(), Script::GetAI, GetAI_boss_professor_putricide(), GetAI_npc_choking_gas_bomb(), GetAI_npc_gas_cloud_icc(), GetAI_npc_growing_ooze_puddle(), GetAI_npc_puddle_stalker(), GetAI_npc_volatile_ooze_icc(), Script::Name, Script::pEffectDummyNPC, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_putricide()
bool EffectDummyCreature_npc_putricide (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 555 of file boss_professor_putricide.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_B, EFFECT_INDEX_0, Object::GetEntry(), NPC_PROFESSOR_PUTRICIDE, UnitAI::SendAIEvent(), and SPELL_VOLATILE_EXPERIMENT.
Referenced by AddSC_boss_professor_putricide().
EffectScriptEffectCreature_npc_putricide()
bool EffectScriptEffectCreature_npc_putricide (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 485 of file boss_professor_putricide.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Unit::CastSpell(), DoScriptText(), EFFECT_INDEX_0, Map::GetCreature(), GetCreatureListWithEntryInGrid(), Object::GetEntry(), WorldObject::GetInstanceData(), WorldObject::GetMap(), instance_icecrown_citadel::GetRotfaceStalkersList(), GetSpellStore(), NPC_PROFESSOR_PUTRICIDE, NPC_PUDDLE_STALKER, SAY_SLIME_FLOW_1, SAY_SLIME_FLOW_2, script_error_log(), UnitAI::SendAIEvent(), SPELL_OOZE_FLOOD_TRIGGER, SPELL_UNSTABLE_EXPERIMENT, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by AddSC_boss_professor_putricide().
EffectScriptEffectCreature_spell_eat_ooze()
bool EffectScriptEffectCreature_spell_eat_ooze (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 705 of file boss_professor_putricide.cpp.
References EFFECT_INDEX_0, Creature::ForcedDespawn(), Object::GetEntry(), WorldObject::GetInstanceData(), GetSpellStore(), Unit::HasAura(), SQLStorage::LookupEntry(), NPC_GROWING_OOZE_PUDDLE, Unit::RemoveAllAurasOnEvade(), Unit::RemoveAuraHolderFromStack(), instance_icecrown_citadel::SetSpecialAchievementCriteria(), SPELL_EAT_OOZE, and TYPE_ACHIEV_NAUSEA.
Referenced by AddSC_boss_professor_putricide().
EffectScriptEffectCreature_spell_ooze_flood()
bool EffectScriptEffectCreature_spell_ooze_flood (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 774 of file boss_professor_putricide.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, GetClosestCreatureWithEntry(), Object::GetEntry(), GetSpellStore(), NPC_PUDDLE_STALKER, SPELL_OOZE_FLOOD, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_professor_putricide().
GetAI_boss_professor_putricide()
UnitAI* GetAI_boss_professor_putricide (Creature * pCreature)
Definition at line 480 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().
GetAI_npc_choking_gas_bomb()
UnitAI* GetAI_npc_choking_gas_bomb (Creature * pCreature)
Definition at line 749 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().
GetAI_npc_gas_cloud_icc()
UnitAI* GetAI_npc_gas_cloud_icc (Creature * pCreature)
Definition at line 680 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().
GetAI_npc_growing_ooze_puddle()
UnitAI* GetAI_npc_growing_ooze_puddle (Creature * pCreature)
Definition at line 700 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().
GetAI_npc_puddle_stalker()
UnitAI* GetAI_npc_puddle_stalker (Creature * pCreature)
Definition at line 769 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().
GetAI_npc_volatile_ooze_icc()
UnitAI* GetAI_npc_volatile_ooze_icc (Creature * pCreature)
Definition at line 622 of file boss_professor_putricide.cpp.
Referenced by AddSC_boss_professor_putricide().