CMaNGOS_WoTLK: boss_kologarn.cpp File Reference
boss_kologarn.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct boss_kologarnAI
struct npc_focused_eyebeamAI
struct npc_rubble_stalkerAI
Enumerations
enum {
SAY_AGGRO = -1603126 , SAY_SHOCKWAVE = -1603127 , SAY_GRAB = -1603128 , SAY_ARM_LOST_LEFT = -1603129 ,
SAY_ARM_LOST_RIGHT = -1603130 , SAY_SLAY_1 = -1603131 , SAY_SLAY_2 = -1603132 , SAY_BERSERK = -1603133 ,
SAY_DEATH = -1603134 , EMOTE_ARM_RIGHT = -1603135 , EMOTE_ARM_LEFT = -1603136 , EMOTE_STONE_GRIP = -1603137 ,
SPELL_INSTAKILL_KOLOGARN_ARM = 63628 , SPELL_OVERHEAD_SMASH = 63356 , SPELL_OVERHEAD_SMASH_H = 64003 , SPELL_ONE_ARMED_SMASH = 63573 ,
SPELL_ONE_ARMED_SMASH_H = 64006 , SPELL_STONE_SHOUT = 63716 , SPELL_STONE_SHOUT_H = 64005 , SPELL_PETRIFYING_BREATH = 62030 ,
SPELL_PETRIFYING_BREATH_H = 63980 , SPELL_BERSERK = 64238 , SPELL_REDUCE_PARRY_CHANCE = 64651 , SPELL_ARM_VISUAL = 64753 ,
SPELL_ARM_DEAD_DAMAGE_KOLOGARN = 63629 , SPELL_ARM_DEAD_DAMAGE_KOLOGARN_H = 63979 , SPELL_RIDE_KOLOGARN_ARMS = 65343 , SPELL_ARM_SWEEP = 63766 ,
SPELL_ARM_SWEEP_H = 63983 , SPELL_STONE_GRIP = 62166 , SPELL_STONE_GRIP_H = 63981 , SPELL_FOCUSED_EYEBEAM_SUMMON = 63342 ,
SPELL_EYEBEAM_PERIODIC = 63347 , SPELL_EYEBEAM_PERIODIC_H = 63977 , SPELL_EYEBEAM_DAMAGE = 63346 , SPELL_EYEBEAM_DAMAGE_H = 63976 ,
SPELL_EYEBEAM_VISUAL_LEFT = 63676 , SPELL_EYEBEAM_VISUAL_RIGHT = 63702 , SPELL_SUMMON_RUBBLE = 63633 , SPELL_FALLING_RUBBLE = 63821 ,
SPELL_FALLING_RUBBLE_H = 64001 , SPELL_CANCEL_STONE_GRIP = 65594 , NPC_FOCUSED_EYEBEAM_RIGHT = 33802 , NPC_FOCUSED_EYEBEAM_LEFT = 33632 ,
NPC_RUBBLE = 33768 , SEAT_ID_LEFT = 1 , SEAT_ID_RIGHT = 2 , MAX_ACHIEV_RUBBLE = 25
}
Functions
UnitAI * GetAI_boss_kologarn (Creature *pCreature)
UnitAI * GetAI_npc_focused_eyebeam (Creature *pCreature)
UnitAI * GetAI_npc_rubble_stalker (Creature *pCreature)
void AddSC_boss_kologarn ()
Variables
static const float afKoloArmsLoc [4] = {1797.15f, -24.4027f, 448.741f, 3.1939f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SHOCKWAVE
SAY_GRAB
SAY_ARM_LOST_LEFT
SAY_ARM_LOST_RIGHT
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
EMOTE_ARM_RIGHT
EMOTE_ARM_LEFT
EMOTE_STONE_GRIP
SPELL_INSTAKILL_KOLOGARN_ARM
SPELL_OVERHEAD_SMASH
SPELL_OVERHEAD_SMASH_H
SPELL_ONE_ARMED_SMASH
SPELL_ONE_ARMED_SMASH_H
SPELL_STONE_SHOUT
SPELL_STONE_SHOUT_H
SPELL_PETRIFYING_BREATH
SPELL_PETRIFYING_BREATH_H
SPELL_BERSERK
SPELL_REDUCE_PARRY_CHANCE
SPELL_ARM_VISUAL
SPELL_ARM_DEAD_DAMAGE_KOLOGARN
SPELL_ARM_DEAD_DAMAGE_KOLOGARN_H
SPELL_RIDE_KOLOGARN_ARMS
SPELL_ARM_SWEEP
SPELL_ARM_SWEEP_H
SPELL_STONE_GRIP
SPELL_STONE_GRIP_H
SPELL_FOCUSED_EYEBEAM_SUMMON
SPELL_EYEBEAM_PERIODIC
SPELL_EYEBEAM_PERIODIC_H
SPELL_EYEBEAM_DAMAGE
SPELL_EYEBEAM_DAMAGE_H
SPELL_EYEBEAM_VISUAL_LEFT
SPELL_EYEBEAM_VISUAL_RIGHT
SPELL_SUMMON_RUBBLE
SPELL_FALLING_RUBBLE
SPELL_FALLING_RUBBLE_H
SPELL_CANCEL_STONE_GRIP
NPC_FOCUSED_EYEBEAM_RIGHT
NPC_FOCUSED_EYEBEAM_LEFT
NPC_RUBBLE
SEAT_ID_LEFT
SEAT_ID_RIGHT
MAX_ACHIEV_RUBBLE
Definition at line 28 of file boss_kologarn.cpp.
Function Documentation
AddSC_boss_kologarn()
void AddSC_boss_kologarn ()
Definition at line 543 of file boss_kologarn.cpp.
References Script::GetAI, GetAI_boss_kologarn(), GetAI_npc_focused_eyebeam(), GetAI_npc_rubble_stalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_kologarn()
UnitAI* GetAI_boss_kologarn (Creature * pCreature)
Definition at line 470 of file boss_kologarn.cpp.
Referenced by AddSC_boss_kologarn().
GetAI_npc_focused_eyebeam()
UnitAI* GetAI_npc_focused_eyebeam (Creature * pCreature)
Definition at line 502 of file boss_kologarn.cpp.
Referenced by AddSC_boss_kologarn().
GetAI_npc_rubble_stalker()
UnitAI* GetAI_npc_rubble_stalker (Creature * pCreature)
Definition at line 538 of file boss_kologarn.cpp.
Referenced by AddSC_boss_kologarn().
Variable Documentation
afKoloArmsLoc
const float afKoloArmsLoc[4] = {1797.15f, -24.4027f, 448.741f, 3.1939f} static
Definition at line 97 of file boss_kologarn.cpp.
Referenced by boss_kologarnAI::UpdateAI().