CMaNGOS_WoTLK: boss_cannon_master_willey.cpp File Reference
boss_cannon_master_willey.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_cannon_master_willeyAI
Enumerations
enum { SPELL_KNOCK_AWAY = 10101 , SPELL_PUMMEL = 15615 , SPELL_SHOOT = 16496 , SPELL_SUMMON_RIFLEMAN = 17279 }
Functions
UnitAI * GetAI_boss_cannon_master_willey (Creature *pCreature)
void AddSC_boss_cannon_master_willey ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_KNOCK_AWAY
SPELL_PUMMEL
SPELL_SHOOT
SPELL_SUMMON_RIFLEMAN
Definition at line 26 of file boss_cannon_master_willey.cpp.
Function Documentation
AddSC_boss_cannon_master_willey()
void AddSC_boss_cannon_master_willey ()
Definition at line 111 of file boss_cannon_master_willey.cpp.
References Script::GetAI, GetAI_boss_cannon_master_willey(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_cannon_master_willey()
UnitAI* GetAI_boss_cannon_master_willey (Creature * pCreature)
Definition at line 106 of file boss_cannon_master_willey.cpp.
Referenced by AddSC_boss_cannon_master_willey().