CMaNGOS_WoTLK: boss_mr_smite.cpp File Reference
boss_mr_smite.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "deadmines.h"
Data Structures
struct boss_mr_smiteAI
Enumerations
enum {
SAY_PHASE_2 = -1036002 , SAY_PHASE_3 = -1036003 , EQUIP_ID_AXE = 2183 , EQUIP_ID_HAMMER = 10756 ,
SPELL_NIBLE_REFLEXES = 6433 , SPELL_SMITE_SLAM = 6435 , SPELL_SMITE_STOMP = 6432 , SPELL_SMITE_HAMMER = 6436 ,
SPELL_THRASH = 12787 , PHASE_1 = 1 , PHASE_2 = 2 , PHASE_3 = 3 ,
PHASE_EQUIP_NULL = 4 , PHASE_EQUIP_START = 5 , PHASE_EQUIP_PROCESS = 6 , PHASE_EQUIP_END = 7
}
Functions
UnitAI * GetAI_boss_mr_smite (Creature *pCreature)
void AddSC_boss_mr_smite ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PHASE_2
SAY_PHASE_3
EQUIP_ID_AXE
EQUIP_ID_HAMMER
SPELL_NIBLE_REFLEXES
SPELL_SMITE_SLAM
SPELL_SMITE_STOMP
SPELL_SMITE_HAMMER
SPELL_THRASH
PHASE_1
PHASE_2
PHASE_3
PHASE_EQUIP_NULL
PHASE_EQUIP_START
PHASE_EQUIP_PROCESS
PHASE_EQUIP_END
Definition at line 27 of file boss_mr_smite.cpp.
Function Documentation
AddSC_boss_mr_smite()
void AddSC_boss_mr_smite ()
Definition at line 260 of file boss_mr_smite.cpp.
References Script::GetAI, GetAI_boss_mr_smite(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_mr_smite()
UnitAI* GetAI_boss_mr_smite (Creature * pCreature)
Definition at line 255 of file boss_mr_smite.cpp.
Referenced by AddSC_boss_mr_smite().