CMaNGOS_WoTLK: boss_amanitar.cpp File Reference
boss_amanitar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "ahnkahet.h"
Data Structures
struct boss_amanitarAI
struct npc_amanitar_mushroomAI
struct spell_remove_mushroom_power
Enumerations
enum {
SPELL_BASH = 57094 , SPELL_VENOM_BOLT_VOLLEY = 57088 , SPELL_ENTANGLING_ROOTS = 57095 , SPELL_MINI = 57055 ,
SPELL_REMOVE_MUSHROOM_POWER = 57283 , NPC_HEALTHY_MUSHROOM = 30391 , NPC_POISONOUS_MUSHROOM = 30435 , SPELL_POISON_CLOUD = 57061 ,
SPELL_POTENT_FUNGUS = 56648 , SPELL_POISON_MUSHROOM_VISUAL = 56741 , SPELL_POWER_MUSHROOM_VISUAL = 56740 , SPELL_MUSHROOM_FORM = 31690
}
Functions
UnitAI * GetAI_boss_amanitar (Creature *pCreature)
UnitAI * GetAI_npc_amanitar_mushroom (Creature *pCreature)
void AddSC_boss_amanitar ()
Variables
static const float aMushroomPos [3] = {362.8f, -869.16f, -75.03f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_BASH
SPELL_VENOM_BOLT_VOLLEY
SPELL_ENTANGLING_ROOTS
SPELL_MINI
SPELL_REMOVE_MUSHROOM_POWER
NPC_HEALTHY_MUSHROOM
NPC_POISONOUS_MUSHROOM
SPELL_POISON_CLOUD
SPELL_POTENT_FUNGUS
SPELL_POISON_MUSHROOM_VISUAL
SPELL_POWER_MUSHROOM_VISUAL
SPELL_MUSHROOM_FORM
Definition at line 29 of file boss_amanitar.cpp.
Function Documentation
AddSC_boss_amanitar()
void AddSC_boss_amanitar ()
Definition at line 230 of file boss_amanitar.cpp.
References Script::GetAI, GetAI_boss_amanitar(), GetAI_npc_amanitar_mushroom(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_amanitar()
UnitAI* GetAI_boss_amanitar (Creature * pCreature)
Definition at line 193 of file boss_amanitar.cpp.
Referenced by AddSC_boss_amanitar().
GetAI_npc_amanitar_mushroom()
UnitAI* GetAI_npc_amanitar_mushroom (Creature * pCreature)
Definition at line 213 of file boss_amanitar.cpp.
Referenced by AddSC_boss_amanitar().
Variable Documentation
aMushroomPos
const float aMushroomPos[3] = {362.8f, -869.16f, -75.03f} static
Definition at line 49 of file boss_amanitar.cpp.
Referenced by boss_amanitarAI::DoSummonMushrooms().