CMaNGOS_WoTLK: boss_anzu.cpp File Reference
boss_anzu.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sethekk_halls.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct boss_anzuAI
struct npc_anzu_bird_spiritAI
Enumerations
enum {
SAY_ANZU_INTRO_1 = -1556016 , SAY_ANZU_INTRO_2 = -1556017 , SAY_BANISH = -1556018 , SAY_WHISPER_MAGIC_1 = -1556019 ,
SAY_WHISPER_MAGIC_2 = -1556021 , SAY_WHISPER_MAGIC_3 = -1556022 , EMOTE_BIRD_STONE = -1556020 , SPELL_SHADOWFORM = 37816 ,
SPELL_FLESH_RIP = 40199 , SPELL_SCREECH = 40184 , SPELL_SPELL_BOMB = 40303 , SPELL_CYCLONE = 40321 ,
SPELL_BANISH_SELF = 42354 , SPELL_DIVE = 40279 , SPELL_HATE_TO_ZERO = 9205 , NPC_HAWK_SPIRIT = 23134 ,
NPC_FALCON_SPIRIT = 23135 , NPC_EAGLE_SPIRIT = 23136 , SPELL_IMPROVED_DURATION = 40250 , SPELL_FREEZE_ANIM = 16245 ,
SPELL_SPIRIT_STONEFORM = 40308 , SPELL_PROTECTION_OF_THE_HAWK = 40237 , SPELL_SPITE_OF_THE_EAGLE = 40240 , SPELL_SPEED_OF_THE_FALCON = 40241 ,
MAX_BROODS = 6 , PATH_ID_1 = 1 , PATH_ID_2 = 2
}
enum AnzuActions {
ANZU_ACTION_SPAWN_BROODS , ANZU_ACTION_BANISH , ANZU_ACTION_DIVE , ANZU_ACTION_FLESH_RIP ,
ANZU_ACTION_SCREECH , ANZU_ACTION_SPELL_BOMB , ANZU_ACTION_CYCLONE , ANZU_COMBAT_ACTION_MAX ,
ANZU_INTRO_TALK , ANZU_INTRO_FLAGS , ANZU_BROOD_ATTACK
}
Functions
UnitAI * GetAI_boss_anzu (Creature *pCreature)
UnitAI * GetAI_npc_anzu_bird_spirit (Creature *pCreature)
void AddSC_boss_anzu ()
Variables
static const uint32 aSpiritsEntries [3] = {NPC_FALCON_SPIRIT, NPC_HAWK_SPIRIT, NPC_EAGLE_SPIRIT}
float spiritSpawns [][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ANZU_INTRO_1
SAY_ANZU_INTRO_2
SAY_BANISH
SAY_WHISPER_MAGIC_1
SAY_WHISPER_MAGIC_2
SAY_WHISPER_MAGIC_3
EMOTE_BIRD_STONE
SPELL_SHADOWFORM
SPELL_FLESH_RIP
SPELL_SCREECH
SPELL_SPELL_BOMB
SPELL_CYCLONE
SPELL_BANISH_SELF
SPELL_DIVE
SPELL_HATE_TO_ZERO
NPC_HAWK_SPIRIT
NPC_FALCON_SPIRIT
NPC_EAGLE_SPIRIT
SPELL_IMPROVED_DURATION
SPELL_FREEZE_ANIM
SPELL_SPIRIT_STONEFORM
SPELL_PROTECTION_OF_THE_HAWK
SPELL_SPITE_OF_THE_EAGLE
SPELL_SPEED_OF_THE_FALCON
MAX_BROODS
PATH_ID_1
PATH_ID_2
Definition at line 29 of file boss_anzu.cpp.
AnzuActions
enum AnzuActions
Enumerator
ANZU_ACTION_SPAWN_BROODS
ANZU_ACTION_BANISH
ANZU_ACTION_DIVE
ANZU_ACTION_FLESH_RIP
ANZU_ACTION_SCREECH
ANZU_ACTION_SPELL_BOMB
ANZU_ACTION_CYCLONE
ANZU_COMBAT_ACTION_MAX
ANZU_INTRO_TALK
ANZU_INTRO_FLAGS
ANZU_BROOD_ATTACK
Definition at line 87 of file boss_anzu.cpp.
Function Documentation
AddSC_boss_anzu()
void AddSC_boss_anzu ()
Definition at line 477 of file boss_anzu.cpp.
References Script::GetAI, GetAI_boss_anzu(), GetAI_npc_anzu_bird_spirit(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_anzu()
UnitAI* GetAI_boss_anzu (Creature * pCreature)
Definition at line 467 of file boss_anzu.cpp.
Referenced by AddSC_boss_anzu().
GetAI_npc_anzu_bird_spirit()
UnitAI* GetAI_npc_anzu_bird_spirit (Creature * pCreature)
Definition at line 472 of file boss_anzu.cpp.
Referenced by AddSC_boss_anzu().
Variable Documentation
aSpiritsEntries
const uint32 aSpiritsEntries[3] = {NPC_FALCON_SPIRIT, NPC_HAWK_SPIRIT, NPC_EAGLE_SPIRIT} static
Definition at line 75 of file boss_anzu.cpp.
Referenced by boss_anzuAI::DoSummonBirdHelpers().
spiritSpawns
float spiritSpawns[][4]
Initial value:
=
{
    { -118.1717f, 284.5299f, 121.2287f, 2.775074f },
    { -87.59662f, 263.5181f, 92.70478f, 1.658063f },
    { -60.94724f, 272.2065f, 111.3746f, 5.759586f },
    { -98.15528f, 293.4469f, 109.2385f, 0.1745329f },
    { -99.7016f,  270.1699f, 98.27389f, 6.178465f },
    { -69.25543f, 303.0768f, 97.84479f, 5.532694f },
}
Definition at line 77 of file boss_anzu.cpp.
Referenced by boss_anzuAI::DoSummonBroodsOfAnzu().