CMaNGOS_WoTLK: boss_kazzak.cpp File Reference
boss_kazzak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct boss_kazzakAI
Enumerations
enum {
SAY_INTRO = -1000147 , SAY_AGGRO1 = -1000148 , SAY_AGGRO2 = -1000149 , SAY_SURPREME1 = -1000150 ,
SAY_SURPREME2 = -1000151 , SAY_KILL1 = -1000152 , SAY_KILL2 = -1000153 , SAY_KILL3 = -1000154 ,
SAY_DEATH = -1000155 , EMOTE_FRENZY = -1000002 , SAY_RAND1 = -1000157 , SAY_RAND2 = -1000158 ,
SPELL_SHADOW_VOLLEY = 21341 , SPELL_BERSERK = 21340 , SPELL_CLEAVE = 20691 , SPELL_THUNDERCLAP = 26554 ,
SPELL_VOIDBOLT = 21066 , SPELL_MARK_OF_KAZZAK = 21056 , SPELL_CAPTURESOUL = 21053 , SPELL_TWISTED_REFLECTION = 21063
}
enum KazzakActions {
KAZZAK_ACTION_SUPREME , KAZZAK_ACTION_VOIDBOLT , KAZZAK_ACTION_TWISTED_REFLECTION , KAZZAK_ACTION_MARK_OF_KAZZAK ,
KAZZAK_ACTION_SHADOW_BOLT_VOLLEY , KAZZAK_ACTION_THUNDERCLAP , KAZZAK_ACTION_CLEAVE , KAZZAK_ACTION_MAX
}
Functions
UnitAI * GetAI_boss_kazzak (Creature *pCreature)
void AddSC_boss_kazzakAI ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_AGGRO1
SAY_AGGRO2
SAY_SURPREME1
SAY_SURPREME2
SAY_KILL1
SAY_KILL2
SAY_KILL3
SAY_DEATH
EMOTE_FRENZY
SAY_RAND1
SAY_RAND2
SPELL_SHADOW_VOLLEY
SPELL_BERSERK
SPELL_CLEAVE
SPELL_THUNDERCLAP
SPELL_VOIDBOLT
SPELL_MARK_OF_KAZZAK
SPELL_CAPTURESOUL
SPELL_TWISTED_REFLECTION
Definition at line 28 of file boss_kazzak.cpp.
KazzakActions
enum KazzakActions
Enumerator
KAZZAK_ACTION_SUPREME
KAZZAK_ACTION_VOIDBOLT
KAZZAK_ACTION_TWISTED_REFLECTION
KAZZAK_ACTION_MARK_OF_KAZZAK
KAZZAK_ACTION_SHADOW_BOLT_VOLLEY
KAZZAK_ACTION_THUNDERCLAP
KAZZAK_ACTION_CLEAVE
KAZZAK_ACTION_MAX
Definition at line 53 of file boss_kazzak.cpp.
Function Documentation
AddSC_boss_kazzakAI()
void AddSC_boss_kazzakAI ()
Definition at line 269 of file boss_kazzak.cpp.
References Script::GetAI, GetAI_boss_kazzak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_kazzak()
UnitAI* GetAI_boss_kazzak (Creature * pCreature)
Definition at line 264 of file boss_kazzak.cpp.
Referenced by AddSC_boss_kazzakAI().