CMaNGOS_WoTLK: boss_rajaxx.cpp File Reference
boss_rajaxx.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ruins_of_ahnqiraj.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct npc_general_andorovAI
struct npc_kaldorei_eliteAI
Enumerations
enum {
SAY_ANDOROV_INTRO_1 = -1509004 , SAY_ANDOROV_INTRO_2 = -1509031 , SAY_ANDOROV_INTRO_3 = -1509003 , SAY_ANDOROV_INTRO_4 = -1509029 ,
SAY_ANDOROV_ATTACK_START = -1509030 , SAY_ANDOROV_DESPAWN = -1509032 , SAY_KILLS_ANDOROV = -1509016 , SAY_UNK1 = -1509011 ,
SAY_UNK2 = -1509012 , SAY_UNK3 = -1509013 , SAY_UNK4 = -1509014 , GOSSIP_TEXT_ID_INTRO = 7883 ,
GOSSIP_TEXT_ID_TRADE = 8305 , GOSSIP_ITEM_START = -3509000 , GOSSIP_ITEM_TRADE = -3509001 , SPELL_AURA_OF_COMMAND = 25516 ,
SPELL_BASH = 25515 , SPELL_STRIKE = 22591 , SPELL_CLEAVE = 26350 , SPELL_MORTAL_STRIKE = 16856 ,
POINT_ID_MOVE_INTRO = 2 , POINT_ID_MOVE_ATTACK = 4
}
enum AndorovActions {
ANDOROV_COMMAND_AURA , ANDOROV_BASH , ANDOROV_STRIKE , ANDOROV_ACTION_MAX ,
ANDOROV_MOVE , ANDOROV_DESPAWN
}
enum KaldoreiEliteActions { KALDOREI_CLEAVE , KALDOREI_STRIKE , KALDOREI_ACTION_MAX }
Functions
bool GossipHello_npc_general_andorov (Player *player, Creature *creature)
bool GossipSelect_npc_general_andorov (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_boss_rajaxx ()
Variables
static const DialogueEntry aIntroDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ANDOROV_INTRO_1
SAY_ANDOROV_INTRO_2
SAY_ANDOROV_INTRO_3
SAY_ANDOROV_INTRO_4
SAY_ANDOROV_ATTACK_START
SAY_ANDOROV_DESPAWN
SAY_KILLS_ANDOROV
SAY_UNK1
SAY_UNK2
SAY_UNK3
SAY_UNK4
GOSSIP_TEXT_ID_INTRO
GOSSIP_TEXT_ID_TRADE
GOSSIP_ITEM_START
GOSSIP_ITEM_TRADE
SPELL_AURA_OF_COMMAND
SPELL_BASH
SPELL_STRIKE
SPELL_CLEAVE
SPELL_MORTAL_STRIKE
POINT_ID_MOVE_INTRO
POINT_ID_MOVE_ATTACK
Definition at line 28 of file boss_rajaxx.cpp.
AndorovActions
enum AndorovActions
Enumerator
ANDOROV_COMMAND_AURA
ANDOROV_BASH
ANDOROV_STRIKE
ANDOROV_ACTION_MAX
ANDOROV_MOVE
ANDOROV_DESPAWN
Definition at line 77 of file boss_rajaxx.cpp.
KaldoreiEliteActions
enum KaldoreiEliteActions
Enumerator
KALDOREI_CLEAVE
KALDOREI_STRIKE
KALDOREI_ACTION_MAX
Definition at line 312 of file boss_rajaxx.cpp.
Function Documentation
AddSC_boss_rajaxx()
void AddSC_boss_rajaxx ()
Definition at line 372 of file boss_rajaxx.cpp.
References Script::GetAI, GossipHello_npc_general_andorov(), GossipSelect_npc_general_andorov(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_general_andorov()
bool GossipHello_npc_general_andorov (Player * player, Creature * creature)
Definition at line 277 of file boss_rajaxx.cpp.
References FAIL, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ICON_CHAT, GOSSIP_ICON_VENDOR, GOSSIP_ITEM_START, GOSSIP_ITEM_TRADE, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_INTRO, Object::HasFlag(), IN_PROGRESS, NOT_STARTED, TYPE_RAJAXX, UNIT_NPC_FLAG_VENDOR, and UNIT_NPC_FLAGS.
Referenced by AddSC_boss_rajaxx().
GossipSelect_npc_general_andorov()
bool GossipSelect_npc_general_andorov (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 296 of file boss_rajaxx.cpp.
References Creature::AI(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, and GOSSIP_ACTION_TRADE.
Referenced by AddSC_boss_rajaxx().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_ANDOROV_INTRO_1,       NPC_GENERAL_ANDOROV,    7000},
    {SAY_ANDOROV_INTRO_2,       NPC_GENERAL_ANDOROV,    0},
    {SAY_ANDOROV_INTRO_3,       NPC_GENERAL_ANDOROV,    4000},
    {SAY_ANDOROV_INTRO_4,       NPC_GENERAL_ANDOROV,    6000},
    {SAY_ANDOROV_ATTACK_START,  NPC_GENERAL_ANDOROV,    0},
    {0, 0, 0},
}
Definition at line 67 of file boss_rajaxx.cpp.