CMaNGOS_WoTLK: boss_muru.cpp File Reference
boss_muru.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sunwell_plateau.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct boss_muruAI
struct boss_entropiusAI
struct npc_portal_targetAI
struct npc_darknessAI
struct npc_singularityAI
struct DarkFiendAI
struct DarkFiendAura
struct DarkFiendDummy
struct SummonBloodElvesScript
struct SummonBloodElvesPeriodic
struct DarknessMuru
struct EntropiusDarkEnergy
struct OpenAllPortals
struct TransformVisualPeriodic
struct OpenPortalMuru
struct SummonVoidSentinelSummoner
struct SummonVoidSentinelSummonerVisual
struct SpellShadowPulsePeriodic
struct BlackHoleEffect
Enumerations
enum {
SPELL_NEGATIVE_ENERGY = 46009 , SPELL_DARKNESS = 45996 , SPELL_OPEN_PORTAL_PERIODIC = 45994 , SPELL_OPEN_PORTAL = 45976 ,
SPELL_OPEN_PORTAL_AURA = 45977 , SPELL_SUMMON_BERSERKER_1 = 46037 , SPELL_SUMMON_BERSERKER_2 = 46040 , SPELL_SUMMON_FURY_MAGE_1 = 46038 ,
SPELL_SUMMON_FURY_MAGE_2 = 46039 , SPELL_SUMMON_DARK_FIEND_1 = 46000 , SPELL_SUMMON_DARK_FIEND_2 = 46001 , SPELL_SUMMON_DARK_FIEND_3 = 46002 ,
SPELL_SUMMON_DARK_FIEND_4 = 46003 , SPELL_SUMMON_DARK_FIEND_5 = 46004 , SPELL_SUMMON_DARK_FIEND_6 = 46005 , SPELL_SUMMON_DARK_FIEND_7 = 46006 ,
SPELL_SUMMON_DARK_FIEND_8 = 46007 , SPELL_DARK_FIEND_TRIGGER = 45936 , SPELL_OPEN_ALL_PORTALS = 46177 , SPELL_SUMMON_ENTROPIUS = 46217 ,
SPELL_ENTROPIUS_SPAWN = 46223 , SPELL_NEGATIVE_ENERGY_ENT = 46284 , SPELL_NEGATIVE_ENERGY_DAMAGE = 46285 , SPELL_SUMMON_BLACK_HOLE = 46282 ,
SPELL_SUMMON_DARKNESS = 46269 , SPELL_SUMMON_BLOOD_ELVES_SCRIPT = 46050 , SPELL_SUMMON_BLOOD_ELVES_PERIODIC = 46041 , SPELL_SENTINEL_SUMMONER_VISUAL = 45989 ,
SPELL_SUMMON_VOID_SENTINEL = 45988 , SPELL_SUMMON_SENTINEL_SUMMONER = 45978 , SPELL_TRANSFORM_VISUAL_1 = 46178 , SPELL_TRANSFORM_VISUAL_2 = 46208 ,
NPC_VOID_SENTINEL_SUMMONER = 25782 , SPELL_DARKNESS_PERIODIC = 45998 , SPELL_VOID_ZONE_VISUAL = 46265 , SPELL_VOID_ZONE_PERIODIC = 46262 ,
SPELL_SUMMON_DARK_FIEND = 46263 , SPELL_BLACK_HOLE_SUMMON_VISUAL = 46242 , SPELL_BLACK_HOLE_SUMMON_VISUAL_2 = 46247 , SPELL_BLACK_HOLE_PASSIVE = 46228 ,
SPELL_BLACK_HOLE_VISUAL_2 = 46235 , SPELL_DARK_FIEND_DUMMY = 45943 , SPELL_DARK_FIEND_EXPLO = 45944 , SPELL_DARK_FIEND_VISUAL = 45934 ,
MAX_TRANSFORM_CASTS = 10
}
enum MuruActions {
MURU_TRANSITION , MURU_DARK_FIENDS , MURU_HUMANOIDS , MURU_ACTION_MAX ,
MURU_SPAWN_ENTROPIUS , MURU_ATTACK_SPAWNS
}
enum EntropiusActions { ENTROPIUS_DARKNESS , ENTROPIUS_BLACK_HOLE , ENTROPIUS_ACTION_MAX , ENTROPIUS_ATTACK_DELAY }
enum SingularityActions { SINGULARITY_SPAWN , SINGULARITY_TARGET_CHANGE }
Functions
void SummonElves (Unit *target)
void AddSC_boss_muru ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_NEGATIVE_ENERGY
SPELL_DARKNESS
SPELL_OPEN_PORTAL_PERIODIC
SPELL_OPEN_PORTAL
SPELL_OPEN_PORTAL_AURA
SPELL_SUMMON_BERSERKER_1
SPELL_SUMMON_BERSERKER_2
SPELL_SUMMON_FURY_MAGE_1
SPELL_SUMMON_FURY_MAGE_2
SPELL_SUMMON_DARK_FIEND_1
SPELL_SUMMON_DARK_FIEND_2
SPELL_SUMMON_DARK_FIEND_3
SPELL_SUMMON_DARK_FIEND_4
SPELL_SUMMON_DARK_FIEND_5
SPELL_SUMMON_DARK_FIEND_6
SPELL_SUMMON_DARK_FIEND_7
SPELL_SUMMON_DARK_FIEND_8
SPELL_DARK_FIEND_TRIGGER
SPELL_OPEN_ALL_PORTALS
SPELL_SUMMON_ENTROPIUS
SPELL_ENTROPIUS_SPAWN
SPELL_NEGATIVE_ENERGY_ENT
SPELL_NEGATIVE_ENERGY_DAMAGE
SPELL_SUMMON_BLACK_HOLE
SPELL_SUMMON_DARKNESS
SPELL_SUMMON_BLOOD_ELVES_SCRIPT
SPELL_SUMMON_BLOOD_ELVES_PERIODIC
SPELL_SENTINEL_SUMMONER_VISUAL
SPELL_SUMMON_VOID_SENTINEL
SPELL_SUMMON_SENTINEL_SUMMONER
SPELL_TRANSFORM_VISUAL_1
SPELL_TRANSFORM_VISUAL_2
NPC_VOID_SENTINEL_SUMMONER
SPELL_DARKNESS_PERIODIC
SPELL_VOID_ZONE_VISUAL
SPELL_VOID_ZONE_PERIODIC
SPELL_SUMMON_DARK_FIEND
SPELL_BLACK_HOLE_SUMMON_VISUAL
SPELL_BLACK_HOLE_SUMMON_VISUAL_2
SPELL_BLACK_HOLE_PASSIVE
SPELL_BLACK_HOLE_VISUAL_2
SPELL_DARK_FIEND_DUMMY
SPELL_DARK_FIEND_EXPLO
SPELL_DARK_FIEND_VISUAL
MAX_TRANSFORM_CASTS
Definition at line 29 of file boss_muru.cpp.
EntropiusActions
enum EntropiusActions
Enumerator
ENTROPIUS_DARKNESS
ENTROPIUS_BLACK_HOLE
ENTROPIUS_ACTION_MAX
ENTROPIUS_ATTACK_DELAY
Definition at line 306 of file boss_muru.cpp.
MuruActions
enum MuruActions
Enumerator
MURU_TRANSITION
MURU_DARK_FIENDS
MURU_HUMANOIDS
MURU_ACTION_MAX
MURU_SPAWN_ENTROPIUS
MURU_ATTACK_SPAWNS
Definition at line 102 of file boss_muru.cpp.
SingularityActions
enum SingularityActions
Enumerator
SINGULARITY_SPAWN
SINGULARITY_TARGET_CHANGE
Definition at line 497 of file boss_muru.cpp.
Function Documentation
AddSC_boss_muru()
void AddSC_boss_muru ()
Definition at line 791 of file boss_muru.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
SummonElves()
void SummonElves (Unit * target)
Definition at line 650 of file boss_muru.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_B, Unit::CastSpell(), UnitAI::SendAIEvent(), SPELL_SUMMON_BERSERKER_1, SPELL_SUMMON_BERSERKER_2, SPELL_SUMMON_FURY_MAGE_1, SPELL_SUMMON_FURY_MAGE_2, and TRIGGERED_OLD_TRIGGERED.
Referenced by SummonBloodElvesScript::OnEffectExecute(), and SummonBloodElvesPeriodic::OnPeriodicDummy().