CMaNGOS_WoTLK: boss_malygos.cpp File Reference
boss_malygos.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "eye_of_eternity.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct HoverDiskSummonData
struct boss_malygosAI
struct npc_power_sparkAI
struct spell_ride_red_dragon_buddy
struct spell_arcane_bomb
struct spell_arcane_storm
struct spell_vortex
struct spell_vortex_aura
struct spell_align_disk_aggro
Enumerations
enum {
SAY_INTRO_1 = -1616000 , SAY_INTRO_2 = -1616001 , SAY_INTRO_3 = -1616002 , SAY_INTRO_4 = -1616003 ,
SAY_INTRO_5 = -1616004 , SAY_AGGRO = -1616005 , SAY_VORTEX = -1616006 , SAY_SPARK_BUFF = -1616007 ,
SAY_SLAY_1_A = -1616008 , SAY_SLAY_1_B = -1616009 , SAY_SLAY_1_C = -1616010 , SAY_END_PHASE_1 = -1616011 ,
SAY_START_PHASE_2 = -1616012 , SAY_DEEP_BREATH = -1616013 , SAY_SHELL = -1616014 , SAY_SLAY_2_A = -1616015 ,
SAY_SLAY_2_B = -1616016 , SAY_SLAY_2_C = -1616017 , SAY_END_PHASE_2 = -1616018 , SAY_INTRO_PHASE_3 = -1616019 ,
SAY_START_PHASE_3 = -1616020 , SAY_SLAY_3_A = -1616021 , SAY_SLAY_3_B = -1616022 , SAY_SLAY_3_C = -1616023 ,
SAY_SURGE = -1616024 , SAY_SPELL_1 = -1616025 , SAY_SPELL_2 = -1616026 , SAY_SPELL_3 = -1616027 ,
SAY_DEATH = -1616028 , SAY_EMOTE_SPARK = -1616033 , SAY_EMOTE_BREATH = -1616034 , SPELL_BERSERK = 60670 ,
SPELL_ARCANE_BREATH = 56272 , SPELL_ARCANE_BREATH_H = 60072 , SPELL_SUMMON_SPARK = 56140 , SPELL_VORTEX = 56105 ,
SPELL_VORTEX_STUN = 56237 , SPELL_ARCANE_STORM_MASTER = 57473 , SPELL_ARCANE_STORM = 61693 , SPELL_ARCANE_STORM_H = 61694 ,
SPELL_SUMMON_ARCANE_BOMB = 56429 , SPELL_SURGE_OF_POWER_PULSE = 56505 , SPELL_DESTROY_PLATFORM_PRE = 58842 , SPELL_DESTROY_PLATFORM_BOOM = 59084 ,
SPELL_DESTROY_PLATFORM_EVENT = 59099 , SPELL_SUMMON_RED_DRAGON = 58846 , SPELL_CLEAR_ALL_DEBUFFS = 34098 , SPELL_IMMUNE_CURSES = 64515 ,
SPELL_ARCANE_STORM_VEHICLE = 57459 , SPELL_STATIC_FIELD_SUMMON = 57430 , SPELL_SURGE_OF_POWER = 57407 , SPELL_SURGE_OF_POWER_H = 60936 ,
SPELL_SURGE_OF_POWER_WARNING = 60939 , SPELL_POWER_SPARK_MALYGOS = 56152 , SPELL_POWER_SPARK_PLAYERS = 55852 , SPELL_POWER_SPARK_VISUAL = 55845 ,
SPELL_VORTEX_VISUAL = 55873 , SPELL_VORTEX_CONTROL_1 = 55853 , SPELL_VORTEX_CONTROL_2 = 56263 , SPELL_VORTEX_CONTROL_3 = 56264 ,
SPELL_VORTEX_CONTROL_4 = 56265 , SPELL_VORTEX_CONTROL_5 = 56266 , SPELL_VORTEX_CONTROL_1_H = 61071 , SPELL_VORTEX_CONTROL_2_H = 61072 ,
SPELL_VORTEX_CONTROL_3_H = 61073 , SPELL_VORTEX_CONTROL_4_H = 61074 , SPELL_VORTEX_CONTROL_5_H = 61075 , SPELL_VORTEX_TELEPORT = 73040 ,
SPELL_ARCANE_BOMB = 56430 , SPELL_STATIC_FIELD = 57428 , NPC_VORTEX = 30090 , NPC_POWER_SPARK = 30084 ,
NPC_STATIC_FIELD = 30592 , PHASE_FLOOR = 1 , PHASE_TRANSITION = 2 , PHASE_DISCS = 3 ,
PHASE_DRAGONS = 4 , PHASE_VORTEX = 8 , PHASE_SURGE = 9 , POINT_ID_COMBAT = 1 ,
POINT_ID_VORTEX = 2 , POINT_ID_TRANSITION_1 = 3 , POINT_ID_FLIGHT = 4 , POINT_ID_SURGE = 5 ,
POINT_ID_TRANSITION_2 = 6 , POINT_ID_PHASE_3 = 7 , LIGHT_ID_DEFAULT = 1773 , LIGHT_ID_OBSCURE_SPACE = 1822 ,
LIGHT_ID_CHANGE_DIMENSIONS = 1823 , LIGHT_ID_ARCANE_RUNES = 1824 , LIGHT_ID_OBSCURE_ARCANE_RUNES = 1825 , AREA_ID_EYE_OF_ETERNITY = 4500
}
Functions
bool ProcessEventId_event_go_focusing_iris (uint32, Object *pSource, Object *, bool)
void AddSC_boss_malygos ()
Variables
static const DialogueEntry aIntroDialogue []
static const float aCenterMovePos [3] = {754.395f, 1301.270f, 266.253f}
static const float aVortexMovePos [3] = { 756.70105f, 1303.9907f, 286.1703f }
static const float aHoverMovePos [3] = { 828.996f, 1298.84f, 300.0f }
static const float aSurgeMovePos [3] = { 746.10187f, 1305.9847f, 316.653f }
static const float aTransitionPos [3] = { 754.544f, 1301.71f, 320.0f }
static const float aDragonsMovePos [3] = { 752.20557f, 1304.3005f, 220.06091f }
static const uint32 vortexSpellsNormal [] = { SPELL_VORTEX_CONTROL_1, SPELL_VORTEX_CONTROL_2, SPELL_VORTEX_CONTROL_3, SPELL_VORTEX_CONTROL_4, SPELL_VORTEX_CONTROL_5 }
static const uint32 vortexSpellsHeroic [] = { SPELL_VORTEX_CONTROL_1_H, SPELL_VORTEX_CONTROL_2_H, SPELL_VORTEX_CONTROL_3_H, SPELL_VORTEX_CONTROL_4_H, SPELL_VORTEX_CONTROL_5_H }
static const HoverDiskSummonData lordDiskSummonData []
static const HoverDiskSummonData scionDiskSummonData []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_INTRO_4
SAY_INTRO_5
SAY_AGGRO
SAY_VORTEX
SAY_SPARK_BUFF
SAY_SLAY_1_A
SAY_SLAY_1_B
SAY_SLAY_1_C
SAY_END_PHASE_1
SAY_START_PHASE_2
SAY_DEEP_BREATH
SAY_SHELL
SAY_SLAY_2_A
SAY_SLAY_2_B
SAY_SLAY_2_C
SAY_END_PHASE_2
SAY_INTRO_PHASE_3
SAY_START_PHASE_3
SAY_SLAY_3_A
SAY_SLAY_3_B
SAY_SLAY_3_C
SAY_SURGE
SAY_SPELL_1
SAY_SPELL_2
SAY_SPELL_3
SAY_DEATH
SAY_EMOTE_SPARK
SAY_EMOTE_BREATH
SPELL_BERSERK
SPELL_ARCANE_BREATH
SPELL_ARCANE_BREATH_H
SPELL_SUMMON_SPARK
SPELL_VORTEX
SPELL_VORTEX_STUN
SPELL_ARCANE_STORM_MASTER
SPELL_ARCANE_STORM
SPELL_ARCANE_STORM_H
SPELL_SUMMON_ARCANE_BOMB
SPELL_SURGE_OF_POWER_PULSE
SPELL_DESTROY_PLATFORM_PRE
SPELL_DESTROY_PLATFORM_BOOM
SPELL_DESTROY_PLATFORM_EVENT
SPELL_SUMMON_RED_DRAGON
SPELL_CLEAR_ALL_DEBUFFS
SPELL_IMMUNE_CURSES
SPELL_ARCANE_STORM_VEHICLE
SPELL_STATIC_FIELD_SUMMON
SPELL_SURGE_OF_POWER
SPELL_SURGE_OF_POWER_H
SPELL_SURGE_OF_POWER_WARNING
SPELL_POWER_SPARK_MALYGOS
SPELL_POWER_SPARK_PLAYERS
SPELL_POWER_SPARK_VISUAL
SPELL_VORTEX_VISUAL
SPELL_VORTEX_CONTROL_1
SPELL_VORTEX_CONTROL_2
SPELL_VORTEX_CONTROL_3
SPELL_VORTEX_CONTROL_4
SPELL_VORTEX_CONTROL_5
SPELL_VORTEX_CONTROL_1_H
SPELL_VORTEX_CONTROL_2_H
SPELL_VORTEX_CONTROL_3_H
SPELL_VORTEX_CONTROL_4_H
SPELL_VORTEX_CONTROL_5_H
SPELL_VORTEX_TELEPORT
SPELL_ARCANE_BOMB
SPELL_STATIC_FIELD
NPC_VORTEX
NPC_POWER_SPARK
NPC_STATIC_FIELD
PHASE_FLOOR
PHASE_TRANSITION
PHASE_DISCS
PHASE_DRAGONS
PHASE_VORTEX
PHASE_SURGE
POINT_ID_COMBAT
POINT_ID_VORTEX
POINT_ID_TRANSITION_1
POINT_ID_FLIGHT
POINT_ID_SURGE
POINT_ID_TRANSITION_2
POINT_ID_PHASE_3
LIGHT_ID_DEFAULT
LIGHT_ID_OBSCURE_SPACE
LIGHT_ID_CHANGE_DIMENSIONS
LIGHT_ID_ARCANE_RUNES
LIGHT_ID_OBSCURE_ARCANE_RUNES
AREA_ID_EYE_OF_ETERNITY
Definition at line 28 of file boss_malygos.cpp.
Function Documentation
AddSC_boss_malygos()
void AddSC_boss_malygos ()
Definition at line 989 of file boss_malygos.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_focusing_iris(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_go_focusing_iris()
bool ProcessEventId_event_go_focusing_iris (uint32 , Object * pSource, Object * , bool)
Definition at line 826 of file boss_malygos.cpp.
References DONE, WorldObject::GetAngle(), Unit::GetMotionMaster(), WorldObject::GetNearPoint(), Object::GetTypeId(), IN_PROGRESS, Unit::InterruptNonMeleeSpells(), MotionMaster::MovePoint(), NPC_LARGE_TRIGGER, NPC_MALYGOS, POINT_ID_COMBAT, Unit::SetImmuneToPlayer(), Creature::SetInCombatWithZone(), TYPE_MALYGOS, and TYPEID_PLAYER.
Referenced by AddSC_boss_malygos().
Variable Documentation
aCenterMovePos
const float aCenterMovePos[3] = {754.395f, 1301.270f, 266.253f} static
Definition at line 185 of file boss_malygos.cpp.
Referenced by boss_malygosAI::UpdateAI().
aDragonsMovePos
const float aDragonsMovePos[3] = { 752.20557f, 1304.3005f, 220.06091f } static
Definition at line 190 of file boss_malygos.cpp.
Referenced by boss_malygosAI::JustDidDialogueStep().
aHoverMovePos
const float aHoverMovePos[3] = { 828.996f, 1298.84f, 300.0f } static
Definition at line 187 of file boss_malygos.cpp.
Referenced by boss_malygosAI::JustDidDialogueStep().
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_END_PHASE_1,             NPC_MALYGOS,  3000},
    {LIGHT_ID_ARCANE_RUNES,       0,            22000},
    {PHASE_DISCS,                 0,            0},
    {SAY_END_PHASE_2,             NPC_MALYGOS,  1000},
    {LIGHT_ID_CHANGE_DIMENSIONS,  0,            6000},
    {LIGHT_ID_OBSCURE_SPACE,      0,            4000},
    {SPELL_DESTROY_PLATFORM_PRE,  0,            3000},
    {SPELL_DESTROY_PLATFORM_BOOM, 0,            2000},
    {SPELL_SUMMON_RED_DRAGON,     0,            5000},
    {SAY_INTRO_PHASE_3,           NPC_MALYGOS,  11000},
    {LIGHT_ID_OBSCURE_ARCANE_RUNES, 0,          0},
    {0, 0, 0},
}
Definition at line 166 of file boss_malygos.cpp.
aSurgeMovePos
const float aSurgeMovePos[3] = { 746.10187f, 1305.9847f, 316.653f } static
Definition at line 188 of file boss_malygos.cpp.
Referenced by boss_malygosAI::UpdateAI().
aTransitionPos
const float aTransitionPos[3] = { 754.544f, 1301.71f, 320.0f } static
Definition at line 189 of file boss_malygos.cpp.
Referenced by boss_malygosAI::ReceiveAIEvent().
aVortexMovePos
const float aVortexMovePos[3] = { 756.70105f, 1303.9907f, 286.1703f } static
Definition at line 186 of file boss_malygos.cpp.
Referenced by boss_malygosAI::UpdateAI().
lordDiskSummonData
const HoverDiskSummonData lordDiskSummonData[] static
Initial value:
=
{
    {753.9635f, 1319.003f, 285.052f, 0},
    {773.4768f, 1301.474f, 266.582f, 1},
    {778.6023f, 1301.635f, 285.671f, 2},
    {730.3984f, 1301.644f, 285.091f, 3}
}
Definition at line 201 of file boss_malygos.cpp.
Referenced by boss_malygosAI::DoSpawnAdds().
scionDiskSummonData
const HoverDiskSummonData scionDiskSummonData[] static
Initial value:
=
{
    {753.960f, 1272.719f, 282.3402f, 0},
    {724.828f, 1301.750f, 282.3402f, 2},
    {754.020f, 1330.910f, 282.3402f, 3},
    {784.416f, 1301.570f, 282.3402f, 4},
    {734.432f, 1280.950f, 282.3402f, 5},
    {733.814f, 1323.340f, 282.3402f, 6},
    {774.969f, 1322.170f, 282.3402f, 7},
    {773.226f, 1279.437f, 282.3402f, 8},
}
Definition at line 209 of file boss_malygos.cpp.
Referenced by boss_malygosAI::DoSpawnAdds().
vortexSpellsHeroic
const uint32 vortexSpellsHeroic[] = { SPELL_VORTEX_CONTROL_1_H, SPELL_VORTEX_CONTROL_2_H, SPELL_VORTEX_CONTROL_3_H, SPELL_VORTEX_CONTROL_4_H, SPELL_VORTEX_CONTROL_5_H } static
Definition at line 193 of file boss_malygos.cpp.
Referenced by spell_vortex::OnEffectExecute().
vortexSpellsNormal
const uint32 vortexSpellsNormal[] = { SPELL_VORTEX_CONTROL_1, SPELL_VORTEX_CONTROL_2, SPELL_VORTEX_CONTROL_3, SPELL_VORTEX_CONTROL_4, SPELL_VORTEX_CONTROL_5 } static
Definition at line 192 of file boss_malygos.cpp.
Referenced by spell_vortex::OnEffectExecute().