CMaNGOS_WoTLK: boss_maleki_the_pallid.cpp File Reference
boss_maleki_the_pallid.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_maleki_the_pallidAI
Enumerations
enum { SPELL_FROSTBOLT = 17503 , SPELL_DRAIN_LIFE = 17238 , SPELL_DRAIN_MANA = 17243 , SPELL_ICE_TOMB = 16869 }
Functions
UnitAI * GetAI_boss_maleki_the_pallid (Creature *pCreature)
void AddSC_boss_maleki_the_pallid ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_FROSTBOLT
SPELL_DRAIN_LIFE
SPELL_DRAIN_MANA
SPELL_ICE_TOMB
Definition at line 26 of file boss_maleki_the_pallid.cpp.
Function Documentation
AddSC_boss_maleki_the_pallid()
void AddSC_boss_maleki_the_pallid ()
Definition at line 113 of file boss_maleki_the_pallid.cpp.
References Script::GetAI, GetAI_boss_maleki_the_pallid(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_maleki_the_pallid()
UnitAI* GetAI_boss_maleki_the_pallid (Creature * pCreature)
Definition at line 108 of file boss_maleki_the_pallid.cpp.
Referenced by AddSC_boss_maleki_the_pallid().