CMaNGOS_WoTLK: boss_aeonus.cpp File Reference
boss_aeonus.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "dark_portal.h"
Data Structures
struct boss_aeonusAI
Enumerations
enum {
SAY_AGGRO = -1269013 , SAY_BANISH = -1269014 , SAY_SLAY1 = -1269015 , SAY_SLAY2 = -1269016 ,
SAY_DEATH = -1269017 , EMOTE_GENERIC_FRENZY = -1000002 , SPELL_THRASH = 8876 , SPELL_DOUBLE_ATTACK = 19818 ,
SPELL_CLEAVE = 40504 , SPELL_TIME_STOP = 31422 , SPELL_ENRAGE = 37605 , SPELL_SAND_BREATH = 31473 ,
SPELL_SAND_BREATH_H = 39049
}
Functions
UnitAI * GetAI_boss_aeonus (Creature *pCreature)
void AddSC_boss_aeonus ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_BANISH
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
EMOTE_GENERIC_FRENZY
SPELL_THRASH
SPELL_DOUBLE_ATTACK
SPELL_CLEAVE
SPELL_TIME_STOP
SPELL_ENRAGE
SPELL_SAND_BREATH
SPELL_SAND_BREATH_H
Definition at line 27 of file boss_aeonus.cpp.
Function Documentation
AddSC_boss_aeonus()
void AddSC_boss_aeonus ()
Definition at line 157 of file boss_aeonus.cpp.
References Script::GetAI, GetAI_boss_aeonus(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_aeonus()
UnitAI* GetAI_boss_aeonus (Creature * pCreature)
Definition at line 152 of file boss_aeonus.cpp.
Referenced by AddSC_boss_aeonus().