CMaNGOS_WoTLK: boss_nethekurse.cpp File Reference
boss_nethekurse.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shattered_halls.h"
Data Structures
struct boss_grand_warlock_nethekurseAI
struct mob_fel_orc_convertAI
Enumerations
enum {
SAY_AGGRO_1 = -1540000 , SAY_AGGRO_2 = -1540001 , SAY_AGGRO_3 = -1540002 , SAY_PEON_ATTACK_1 = -1540003 ,
SAY_PEON_ATTACK_2 = -1540004 , SAY_PEON_ATTACK_3 = -1540005 , SAY_PEON_ATTACK_4 = -1540006 , SAY_PEON_DIE_1 = -1540007 ,
SAY_PEON_DIE_2 = -1540008 , SAY_PEON_DIE_3 = -1540009 , SAY_TAUNT_1 = -1540010 , SAY_TAUNT_2 = -1540011 ,
SAY_TAUNT_3 = -1540012 , SAY_SLAY_1 = -1540013 , SAY_SLAY_2 = -1540014 , SAY_SLAY_3 = -1540015 ,
SAY_SLAY_4 = -1540016 , SAY_DIE = -1540017 , SPELL_DEATH_COIL = 30500 , SPELL_DEATH_COIL_2 = 30741 ,
SPELL_DARK_SPIN = 30502 , SPELL_TARGET_FISSURES = 30745 , SPELL_SHADOW_FISSURE = 30496 , SPELL_SHADOW_FISSURE_2 = 30744 ,
SPELL_SHADOW_CLEAVE = 30495 , SPELL_SHADOW_SLAM_H = 35953 , SPELL_SHADOW_SEAR = 30735 , SPELL_HEMORRHAGE = 30478 ,
NPC_FEL_ORC_CONVERT = 17083
}
Functions
UnitAI * GetAI_boss_grand_warlock_nethekurse (Creature *pCreature)
UnitAI * GetAI_mob_fel_orc_convert (Creature *pCreature)
void AddSC_boss_grand_warlock_nethekurse ()
Variables
static const int32 aRandomAggro [] = { -1540200, -1540201, -1540202, -1540203, -1540204, -1540205, -1540206 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_PEON_ATTACK_1
SAY_PEON_ATTACK_2
SAY_PEON_ATTACK_3
SAY_PEON_ATTACK_4
SAY_PEON_DIE_1
SAY_PEON_DIE_2
SAY_PEON_DIE_3
SAY_TAUNT_1
SAY_TAUNT_2
SAY_TAUNT_3
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_SLAY_4
SAY_DIE
SPELL_DEATH_COIL
SPELL_DEATH_COIL_2
SPELL_DARK_SPIN
SPELL_TARGET_FISSURES
SPELL_SHADOW_FISSURE
SPELL_SHADOW_FISSURE_2
SPELL_SHADOW_CLEAVE
SPELL_SHADOW_SLAM_H
SPELL_SHADOW_SEAR
SPELL_HEMORRHAGE
NPC_FEL_ORC_CONVERT
Definition at line 33 of file boss_nethekurse.cpp.
Function Documentation
AddSC_boss_grand_warlock_nethekurse()
void AddSC_boss_grand_warlock_nethekurse ()
Definition at line 411 of file boss_nethekurse.cpp.
References Script::GetAI, GetAI_boss_grand_warlock_nethekurse(), GetAI_mob_fel_orc_convert(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_grand_warlock_nethekurse()
UnitAI* GetAI_boss_grand_warlock_nethekurse (Creature * pCreature)
Definition at line 401 of file boss_nethekurse.cpp.
Referenced by AddSC_boss_grand_warlock_nethekurse().
GetAI_mob_fel_orc_convert()
UnitAI* GetAI_mob_fel_orc_convert (Creature * pCreature)
Definition at line 406 of file boss_nethekurse.cpp.
Referenced by AddSC_boss_grand_warlock_nethekurse().
Variable Documentation
aRandomAggro
const int32 aRandomAggro[] = { -1540200, -1540201, -1540202, -1540203, -1540204, -1540205, -1540206 } static
Definition at line 317 of file boss_nethekurse.cpp.
Referenced by mob_fel_orc_convertAI::Aggro().