CMaNGOS_WoTLK: boss_valithria_dreamwalker.cpp File Reference
boss_valithria_dreamwalker.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
Data Structures
struct boss_valithria_dreamwalkerAI
Enumerations
enum SvalnaTexts {
SAY_SVALNA_EVENT_1 = -1631130 , SAY_SVALNA_EVENT_2 = -1631131 , SAY_SVALNA_EVENT_3 = -1631132 , SAY_SVALNA_EVENT_4 = -1631133 ,
SAY_KILLING_CRUSADERS = -1631134 , SAY_RESSURECT = -1631135 , SAY_SVALNA_AGGRO = -1631136 , SAY_KILL_CAPTAIN = -1631137 ,
SAY_KILL_PLAYER = -1631138 , SAY_DEATH = -1631139
}
enum {
SAY_AGGRO = -1631140 , SAY_PORTAL = -1631141 , SAY_75_HEALTH = -1631142 , SAY_25_HEALTH = -1631143 ,
SAY_0_HEALTH = -1631144 , SAY_PLAYER_DIES = -1631145 , SAY_BERSERK = -1631146 , SAY_VICTORY = -1631147
}
enum {
SPELL_NIGHTMARE_PORTAL_PRE = 71977 , SPELL_NIGHTMARE_PORTAL = 71987 , SPELL_TWISTED_NIGHTMARES = 71941 , SPELL_TWISTED_NIGHTMARES_DOT = 71940 ,
SPELL_NIGHTMARE_CLOUD = 71970 , SPELL_NIGHTMARE_CLOUD_VISUAL = 71939 , SPELL_DREAM_PORTAL_PRE = 71301 , SPELL_DREAM_PORTAL = 71305 ,
SPELL_EMERALD_VIGOR = 70873 , SPELL_DREAM_CLOUD_VISUAL = 70876 , SPELL_DREAM_STATE = 70766 , SPELL_DREAMWALKER_RAGE = 71189 ,
SPELL_IMMUNITY = 72724 , SPELL_CORRUPTION = 70904 , SPELL_DREAM_SLIP = 71196 , SPELL_ICE_SPIKE = 70702 ,
SPELL_CLEAR_DREAMS_NIGHTMARES = 75863 , SPELL_SUMMON_TIMER_SUPPRESSER = 70912 , SPELL_SUMMON_TIMER_SKELETON = 70913 , SPELL_SUMMON_TIMER_ZOMBIE = 70914 ,
SPELL_SUMMON_TIMER_ABOMIN = 70915 , SPELL_SUMMON_TIMER_ARCHMAGE = 70916 , NPC_NIGHTMARE_PORTAL_PRE = 38429 , NPC_NIGHTMARE_PORTAL = 38430 ,
NPC_NIGHTMARE_CLOUD = 38421 , NPC_DREAM_PORTAL_PRE = 38186 , NPC_DREAM_PORTAL = 37945 , NPC_DREAM_CLOUD = 37985 ,
SPELL_ACHIEVEMENT_CREDIT = 72706 , SUMMON_TYPES_NUMBER = 4
}
Functions
UnitAI * GetAI_boss_valithria_dreamwalker (Creature *pCreature)
void AddSC_boss_valithria_dreamwalker ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_PORTAL
SAY_75_HEALTH
SAY_25_HEALTH
SAY_0_HEALTH
SAY_PLAYER_DIES
SAY_BERSERK
SAY_VICTORY
Definition at line 41 of file boss_valithria_dreamwalker.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_NIGHTMARE_PORTAL_PRE
SPELL_NIGHTMARE_PORTAL
SPELL_TWISTED_NIGHTMARES
SPELL_TWISTED_NIGHTMARES_DOT
SPELL_NIGHTMARE_CLOUD
SPELL_NIGHTMARE_CLOUD_VISUAL
SPELL_DREAM_PORTAL_PRE
SPELL_DREAM_PORTAL
SPELL_EMERALD_VIGOR
SPELL_DREAM_CLOUD_VISUAL
SPELL_DREAM_STATE
SPELL_DREAMWALKER_RAGE
SPELL_IMMUNITY
SPELL_CORRUPTION
SPELL_DREAM_SLIP
SPELL_ICE_SPIKE
SPELL_CLEAR_DREAMS_NIGHTMARES
SPELL_SUMMON_TIMER_SUPPRESSER
SPELL_SUMMON_TIMER_SKELETON
SPELL_SUMMON_TIMER_ZOMBIE
SPELL_SUMMON_TIMER_ABOMIN
SPELL_SUMMON_TIMER_ARCHMAGE
NPC_NIGHTMARE_PORTAL_PRE
NPC_NIGHTMARE_PORTAL
NPC_NIGHTMARE_CLOUD
NPC_DREAM_PORTAL_PRE
NPC_DREAM_PORTAL
NPC_DREAM_CLOUD
SPELL_ACHIEVEMENT_CREDIT
SUMMON_TYPES_NUMBER
Definition at line 54 of file boss_valithria_dreamwalker.cpp.
SvalnaTexts
enum SvalnaTexts
Enumerator
SAY_SVALNA_EVENT_1
SAY_SVALNA_EVENT_2
SAY_SVALNA_EVENT_3
SAY_SVALNA_EVENT_4
SAY_KILLING_CRUSADERS
SAY_RESSURECT
SAY_SVALNA_AGGRO
SAY_KILL_CAPTAIN
SAY_KILL_PLAYER
SAY_DEATH
Definition at line 27 of file boss_valithria_dreamwalker.cpp.
Function Documentation
AddSC_boss_valithria_dreamwalker()
void AddSC_boss_valithria_dreamwalker ()
Definition at line 150 of file boss_valithria_dreamwalker.cpp.
References Script::GetAI, GetAI_boss_valithria_dreamwalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_valithria_dreamwalker()
UnitAI* GetAI_boss_valithria_dreamwalker (Creature * pCreature)
Definition at line 145 of file boss_valithria_dreamwalker.cpp.
Referenced by AddSC_boss_valithria_dreamwalker().