CMaNGOS_WoTLK: boss_harbinger_skyriss.cpp File Reference
boss_harbinger_skyriss.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "arcatraz.h"
Data Structures
struct boss_harbinger_skyrissAI
Enumerations
enum {
SAY_KILL_1 = -1552002 , SAY_KILL_2 = -1552003 , SAY_MIND_1 = -1552004 , SAY_MIND_2 = -1552005 ,
SAY_FEAR_1 = -1552006 , SAY_FEAR_2 = -1552007 , SAY_IMAGE = -1552008 , SAY_DEATH = -1552009 ,
SPELL_FEAR = 39415 , SPELL_MIND_REND = 36924 , SPELL_MIND_REND_H = 39017 , SPELL_DOMINATION = 37162 ,
SPELL_DOMINATION_H = 39019 , SPELL_MANA_BURN_H = 39020 , SPELL_66_ILLUSION = 36931 , SPELL_33_ILLUSION = 36932 ,
SPELL_BIRTH = 26262 , SPELL_BLINK_VISUAL = 36937
}
Functions
UnitAI * GetAI_boss_harbinger_skyriss (Creature *pCreature)
void AddSC_boss_harbinger_skyriss ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_KILL_1
SAY_KILL_2
SAY_MIND_1
SAY_MIND_2
SAY_FEAR_1
SAY_FEAR_2
SAY_IMAGE
SAY_DEATH
SPELL_FEAR
SPELL_MIND_REND
SPELL_MIND_REND_H
SPELL_DOMINATION
SPELL_DOMINATION_H
SPELL_MANA_BURN_H
SPELL_66_ILLUSION
SPELL_33_ILLUSION
SPELL_BIRTH
SPELL_BLINK_VISUAL
Definition at line 27 of file boss_harbinger_skyriss.cpp.
Function Documentation
AddSC_boss_harbinger_skyriss()
void AddSC_boss_harbinger_skyriss ()
Definition at line 185 of file boss_harbinger_skyriss.cpp.
References Script::GetAI, GetAI_boss_harbinger_skyriss(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_harbinger_skyriss()
UnitAI* GetAI_boss_harbinger_skyriss (Creature * pCreature)
Definition at line 180 of file boss_harbinger_skyriss.cpp.
Referenced by AddSC_boss_harbinger_skyriss().