CMaNGOS_WoTLK: boss_shade_of_aran.cpp File Reference
boss_shade_of_aran.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "karazhan.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Globals/ObjectMgr.h"
Data Structures
struct boss_aranAI
struct SummonBlizzard
struct DispelBlizzard
struct MassiveMagneticPull
struct FlameWreath
Enumerations
enum {
SAY_AGGRO1 = -1532073 , SAY_AGGRO2 = -1532074 , SAY_AGGRO3 = -1532075 , SAY_FLAMEWREATH1 = -1532076 ,
SAY_FLAMEWREATH2 = -1532077 , SAY_BLIZZARD1 = -1532078 , SAY_BLIZZARD2 = -1532079 , SAY_EXPLOSION1 = -1532080 ,
SAY_EXPLOSION2 = -1532081 , SAY_DRINK = -1532082 , SAY_ELEMENTALS = -1532083 , SAY_KILL1 = -1532084 ,
SAY_KILL2 = -1532085 , SAY_TIMEOVER = -1532086 , SAY_DEATH = -1532087 , SAY_ATIESH = -1532088 ,
SAY_EXPLOSION_EMOTE = -1532139 , SPELL_FROSTBOLT = 29954 , SPELL_FIREBALL = 29953 , SPELL_ARCANE_MISSILES = 29955 ,
SPELL_DRAGONS_BREATH = 29964 , SPELL_CHAINS_OF_ICE = 29991 , SPELL_COUNTERSPELL = 29961 , SPELL_MASS_POLYMORPH = 29963 ,
SPELL_CONJURE_WATER = 29975 , SD_SPELL_DRINK = 30024 , SPELL_MANA_POTION = 32453 , SPELL_PYROBLAST = 29978 ,
SPELL_DISPEL_BLIZZARD = 29970 , SPELL_FLAME_WREATH = 30004 , SPELL_SUMMON_BLIZZARD = 29969 , SPELL_BLINK_CENTER = 29967 ,
SPELL_MASSIVE_MAGNETIC_PULL = 29979 , SPELL_MASS_SLOW = 30035 , SPELL_ARCANE_EXPLOSION = 29973 , SPELL_SUMMON_WATER_ELEM_1 = 29962 ,
SPELL_SUMMON_WATER_ELEM_2 = 37051 , SPELL_SUMMON_WATER_ELEM_3 = 37052 , SPELL_SUMMON_WATER_ELEM_4 = 37053 , NPC_WATER_ELEMENTAL = 17167 ,
NPC_SHADOW_OF_ARAN = 18254 , MAX_SHADOWS_OF_ARAN = 5 , NORMAL_SPELL_COUNT = 3 , ITEM_ATIESH_1 = 22589 ,
ITEM_ATIESH_2 = 22632 , ITEM_ATIESH_3 = 22631 , ITEM_ATIESH_4 = 22630
}
enum SuperSpells { SUPER_FLAME_WREATH = 0 , SUPER_BLIZZARD = 1 , SUPER_ARCANE_EXPL = 2 }
enum AranActions {
ARAN_ACTION_DRINK , ARAN_ACTION_POTION , ARAN_ACTION_ELEMENTALS , ARAN_ACTION_BERSERK ,
ARAN_ACTION_DRAGONS_BREATH , ARAN_ACTION_SUPERSPELL , ARAN_ACTION_SECONDARY_SPELL , ARAN_ACTION_PRIMARY_SPELL ,
ARAN_ACTION_MAX , ARAN_DRINKING_STAGES
}
Functions
void AddSC_boss_shade_of_aran ()
Variables
static std::set< uint32 > atieshStaves = { ITEM_ATIESH_1, ITEM_ATIESH_2, ITEM_ATIESH_3, ITEM_ATIESH_4 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_FLAMEWREATH1
SAY_FLAMEWREATH2
SAY_BLIZZARD1
SAY_BLIZZARD2
SAY_EXPLOSION1
SAY_EXPLOSION2
SAY_DRINK
SAY_ELEMENTALS
SAY_KILL1
SAY_KILL2
SAY_TIMEOVER
SAY_DEATH
SAY_ATIESH
SAY_EXPLOSION_EMOTE
SPELL_FROSTBOLT
SPELL_FIREBALL
SPELL_ARCANE_MISSILES
SPELL_DRAGONS_BREATH
SPELL_CHAINS_OF_ICE
SPELL_COUNTERSPELL
SPELL_MASS_POLYMORPH
SPELL_CONJURE_WATER
SD_SPELL_DRINK
SPELL_MANA_POTION
SPELL_PYROBLAST
SPELL_DISPEL_BLIZZARD
SPELL_FLAME_WREATH
SPELL_SUMMON_BLIZZARD
SPELL_BLINK_CENTER
SPELL_MASSIVE_MAGNETIC_PULL
SPELL_MASS_SLOW
SPELL_ARCANE_EXPLOSION
SPELL_SUMMON_WATER_ELEM_1
SPELL_SUMMON_WATER_ELEM_2
SPELL_SUMMON_WATER_ELEM_3
SPELL_SUMMON_WATER_ELEM_4
NPC_WATER_ELEMENTAL
NPC_SHADOW_OF_ARAN
MAX_SHADOWS_OF_ARAN
NORMAL_SPELL_COUNT
ITEM_ATIESH_1
ITEM_ATIESH_2
ITEM_ATIESH_3
ITEM_ATIESH_4
Definition at line 35 of file boss_shade_of_aran.cpp.
AranActions
enum AranActions
Enumerator
ARAN_ACTION_DRINK
ARAN_ACTION_POTION
ARAN_ACTION_ELEMENTALS
ARAN_ACTION_BERSERK
ARAN_ACTION_DRAGONS_BREATH
ARAN_ACTION_SUPERSPELL
ARAN_ACTION_SECONDARY_SPELL
ARAN_ACTION_PRIMARY_SPELL
ARAN_ACTION_MAX
ARAN_DRINKING_STAGES
Definition at line 111 of file boss_shade_of_aran.cpp.
SuperSpells
enum SuperSpells
Enumerator
SUPER_FLAME_WREATH
SUPER_BLIZZARD
SUPER_ARCANE_EXPL
Definition at line 104 of file boss_shade_of_aran.cpp.
Function Documentation
AddSC_boss_shade_of_aran()
void AddSC_boss_shade_of_aran ()
Definition at line 506 of file boss_shade_of_aran.cpp.
References Script::GetAI, boss_aranAI::GetNormalSpellCooldown(), Script::Name, NPC_SHADOW_OF_ARAN, Script::RegisterSelf(), sObjectMgr, SPELL_ARCANE_MISSILES, SPELL_FIREBALL, and SPELL_FROSTBOLT.
Referenced by AddScripts().
Variable Documentation
atieshStaves
std::set<uint32> atieshStaves = { ITEM_ATIESH_1, ITEM_ATIESH_2, ITEM_ATIESH_3, ITEM_ATIESH_4 } static
Definition at line 102 of file boss_shade_of_aran.cpp.
Referenced by boss_aranAI::MoveInLineOfSight().