CMaNGOS_WoTLK: boss_overlord_wyrmthalak.cpp File Reference
boss_overlord_wyrmthalak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_overlordwyrmthalakAI
Enumerations
enum {
SPELL_BLASTWAVE = 11130 , SPELL_SHOUT = 23511 , SPELL_CLEAVE = 20691 , SPELL_KNOCKAWAY = 20686 ,
NPC_SPIRESTONE_WARLORD = 9216 , NPC_SMOLDERTHORN_BERSERKER = 9268 , NPC_BLOODAXE_VETERAN = 9583
}
Functions
UnitAI * GetAI_boss_overlordwyrmthalak (Creature *pCreature)
void AddSC_boss_overlordwyrmthalak ()
Variables
const uint32 uSummons [3] = {NPC_BLOODAXE_VETERAN, NPC_SMOLDERTHORN_BERSERKER, NPC_SPIRESTONE_WARLORD}
const float afLocations [4][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_BLASTWAVE
SPELL_SHOUT
SPELL_CLEAVE
SPELL_KNOCKAWAY
NPC_SPIRESTONE_WARLORD
NPC_SMOLDERTHORN_BERSERKER
NPC_BLOODAXE_VETERAN
Definition at line 26 of file boss_overlord_wyrmthalak.cpp.
Function Documentation
AddSC_boss_overlordwyrmthalak()
void AddSC_boss_overlordwyrmthalak ()
Definition at line 149 of file boss_overlord_wyrmthalak.cpp.
References Script::GetAI, GetAI_boss_overlordwyrmthalak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_overlordwyrmthalak()
UnitAI* GetAI_boss_overlordwyrmthalak (Creature * pCreature)
Definition at line 144 of file boss_overlord_wyrmthalak.cpp.
Referenced by AddSC_boss_overlordwyrmthalak().
Variable Documentation
afLocations
const float afLocations[4][4]
Initial value:
=
{
    { -51.6805f, -439.831f, 78.2874f, 4.657f},
    { -54.4554f, -439.679f, 78.2884f, 4.657f},
    { -39.355381f, -513.456482f, 88.472046f, 4.679872f},
    { -49.875881f, -511.896942f, 88.195160f, 4.613114f}
}
Definition at line 40 of file boss_overlord_wyrmthalak.cpp.
Referenced by boss_overlordwyrmthalakAI::UpdateAI().
uSummons
const uint32 uSummons[3] = {NPC_BLOODAXE_VETERAN, NPC_SMOLDERTHORN_BERSERKER, NPC_SPIRESTONE_WARLORD}
Definition at line 38 of file boss_overlord_wyrmthalak.cpp.
Referenced by boss_overlordwyrmthalakAI::UpdateAI().