CMaNGOS_WoTLK: boss_highlord_kruul.cpp File Reference
boss_highlord_kruul.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "World/WorldState.h"
Data Structures
struct boss_highlord_kruulAI
struct npc_infernal_houndAI
struct go_infernaling_summoner
Enumerations
enum {
SAY_INTRO1 = -1015073 , SAY_INTRO2 = -1015074 , SAY_AGGRO1 = -1015075 , SAY_AGGRO2 = -1015076 ,
SAY_AGGRO3 = -1015077 , SAY_KILL = -1015078 , SAY_DESPAWN = -1015079 , EMOTE_FRENZY = -1000002 ,
SPELL_SHADOW_VOLLEY = 21341 , SPELL_BERSERK = 21340 , SPELL_CLEAVE = 20691 , SPELL_THUNDERCLAP = 26554 ,
SPELL_VOIDBOLT = 21066 , SPELL_MARK_OF_KAZZAK = 21056 , SPELL_CAPTURESOUL = 21053 , SPELL_TWISTED_REFLECTION = 21063 ,
SPELL_SUMMON_INFERNALING = 33533 , SPELL_CREATE_INFERNALING_SUMMONER = 33536 , SPELL_CREATE_INFERNALING_SUMMONER_C = 33541 , SPELL_INFERNALING_SPAWN_IN = 33543 ,
SPELL_INFERNALING_DURATION = 33544 , SPELL_INFERNALING_DESPAWN = 33545 , SPELL_INFERNALING_IMMOLATION = 19483 , SPELL_KAZZAKS_ASSAULT = 33512 ,
NPC_HAND_OF_THE_HIGHLORD = 19214 , NPC_HIGHLORD_KRUUL = 18338 , NPC_INFERNAL_HOUND = 19207 , MAX_INFERNAL_HOUNDS = 15
}
enum KruulActions {
KRUUL_ACTION_SUPREME , KRUUL_ACTION_VOIDBOLT , KRUUL_ACTION_TWISTED_REFLECTION , KRUUL_ACTION_MARK_OF_KAZZAK ,
KRUUL_ACTION_SHADOW_BOLT_VOLLEY , KRUUL_ACTION_THUNDERCLAP , KRUUL_ACTION_CLEAVE , KRUUL_ACTION_KAZZAKS_ASSAULT ,
KRUUL_ACTION_MAX
}
Functions
UnitAI * GetAI_boss_highlord_kruul (Creature *pCreature)
UnitAI * GetAI_npc_infernal_hound (Creature *pCreature)
GameObjectAI * GetAI_go_infernaling_summoner (GameObject *go)
void AddSC_boss_highlord_kruul ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO1
SAY_INTRO2
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_KILL
SAY_DESPAWN
EMOTE_FRENZY
SPELL_SHADOW_VOLLEY
SPELL_BERSERK
SPELL_CLEAVE
SPELL_THUNDERCLAP
SPELL_VOIDBOLT
SPELL_MARK_OF_KAZZAK
SPELL_CAPTURESOUL
SPELL_TWISTED_REFLECTION
SPELL_SUMMON_INFERNALING
SPELL_CREATE_INFERNALING_SUMMONER
SPELL_CREATE_INFERNALING_SUMMONER_C
SPELL_INFERNALING_SPAWN_IN
SPELL_INFERNALING_DURATION
SPELL_INFERNALING_DESPAWN
SPELL_INFERNALING_IMMOLATION
SPELL_KAZZAKS_ASSAULT
NPC_HAND_OF_THE_HIGHLORD
NPC_HIGHLORD_KRUUL
NPC_INFERNAL_HOUND
MAX_INFERNAL_HOUNDS
Definition at line 29 of file boss_highlord_kruul.cpp.
KruulActions
enum KruulActions
Enumerator
KRUUL_ACTION_SUPREME
KRUUL_ACTION_VOIDBOLT
KRUUL_ACTION_TWISTED_REFLECTION
KRUUL_ACTION_MARK_OF_KAZZAK
KRUUL_ACTION_SHADOW_BOLT_VOLLEY
KRUUL_ACTION_THUNDERCLAP
KRUUL_ACTION_CLEAVE
KRUUL_ACTION_KAZZAKS_ASSAULT
KRUUL_ACTION_MAX
Definition at line 65 of file boss_highlord_kruul.cpp.
Function Documentation
AddSC_boss_highlord_kruul()
void AddSC_boss_highlord_kruul ()
Definition at line 409 of file boss_highlord_kruul.cpp.
References Script::GetAI, GetAI_boss_highlord_kruul(), GetAI_npc_infernal_hound(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_highlord_kruul()
UnitAI* GetAI_boss_highlord_kruul (Creature * pCreature)
Definition at line 350 of file boss_highlord_kruul.cpp.
Referenced by AddSC_boss_highlord_kruul().
GetAI_go_infernaling_summoner()
GameObjectAI* GetAI_go_infernaling_summoner (GameObject * go)
Definition at line 404 of file boss_highlord_kruul.cpp.
GetAI_npc_infernal_hound()
UnitAI* GetAI_npc_infernal_hound (Creature * pCreature)
Definition at line 369 of file boss_highlord_kruul.cpp.
Referenced by AddSC_boss_highlord_kruul().