CMaNGOS_WoTLK: boss_sindragosa.cpp File Reference
boss_sindragosa.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
Data Structures
struct boss_sindragosaAI
struct npc_rimefang_iccAI
struct npc_spinestalker_iccAI
struct mob_frost_bombAI
Frost Bomb - npc marking the target of Frost Bomb.
Macros
#define FROST_BOMB_MIN_X 4367.0f
#define FROST_BOMB_MAX_X 4424.0f
#define FROST_BOMB_MIN_Y 2437.0f
#define FROST_BOMB_MAX_Y 2527.0f
Enumerations
enum {
SAY_AGGRO = -1631148 , SAY_UNCHAINED_MAGIC = -1631149 , SAY_BLISTERING_COLD = -1631150 , SAY_RESPIRE = -1631151 ,
SAY_TAKEOFF = -1631152 , SAY_PHASE_3 = -1631153 , SAY_SLAY_1 = -1631154 , SAY_SLAY_2 = -1631155 ,
SAY_BERSERK = -1631156 , SAY_DEATH = -1631157 , SPELL_BERSERK = 26662 , SPELL_TAIL_SMASH = 71077 ,
SPELL_CLEAVE = 19983 , SPELL_FROST_AURA = 70084 , SPELL_FROST_BREATH = 69649 , SPELL_ICY_GRIP = 70117 ,
SPELL_PERMEATING_CHILL = 70109 , SPELL_UNCHAINED_MAGIC = 69762 , SPELL_ICE_TOMB = 69712 , SPELL_ICE_TOMB_PROTECTION = 69700 ,
SPELL_FROST_BOMB = 69846 , SPELL_FROST_BOMB_DMG = 69845 , SPELL_FROST_BOMB_VISUAL = 70022 , SPELL_MYSTIC_BUFFET = 70128 ,
SPELL_ICE_TOMB_SINGLE = 69675 , SPELL_RIMEFANG_FROST_AURA = 71387 , SPELL_RIMEFANG_FROST_BREATH = 71386 , SPELL_RIMEFANG_ICY_BLAST = 71376 ,
SPELL_SPINESTALKER_BELLOWING_ROAR = 36922 , SPELL_SPINESTALKER_CLEAVE = 40505 , SPELL_SPINESTALKER_TAIL_SWEEP = 71369
}
enum SindragosaPhase {
SINDRAGOSA_PHASE_OOC = 0 , SINDRAGOSA_PHASE_AGGRO = 1 , SINDRAGOSA_PHASE_GROUND = 2 , SINDRAGOSA_PHASE_FLYING_TO_AIR = 3 ,
SINDRAGOSA_PHASE_AIR = 4 , SINDRAGOSA_PHASE_FLYING_TO_GROUND = 5 , SINDRAGOSA_PHASE_THREE = 6
}
enum SindragosaPoint {
SINDRAGOSA_POINT_GROUND_CENTER = 0 , SINDRAGOSA_POINT_AIR_CENTER = 1 , SINDRAGOSA_POINT_AIR_PHASE_2 = 2 , SINDRAGOSA_POINT_AIR_EAST = 3 ,
SINDRAGOSA_POINT_AIR_WEST = 4
}
enum RimefangPhase { RIMEFANG_PHASE_GROUND = 0 , RIMEFANG_PHASE_FLYING = 1 , RIMEFANG_PHASE_AIR = 2 }
enum RimefangPoint { RIMEFANG_POINT_GROUND = 0 , RIMEFANG_POINT_AIR = 1 , RIMEFANG_POINT_INITIAL_LAND_AIR = 2 , RIMEFANG_POINT_INITIAL_LAND = 3 }
enum SpinestalkerPoint { SPINESTALKER_POINT_INITIAL_LAND_AIR = 0 , SPINESTALKER_POINT_INITIAL_LAND = 1 }
Functions
UnitAI * GetAI_boss_sindragosa (Creature *pCreature)
UnitAI * GetAI_npc_rimefang_icc (Creature *pCreature)
UnitAI * GetAI_npc_spinestalker_icc (Creature *pCreature)
UnitAI * GetAI_mob_frost_bomb (Creature *pCreature)
void AddSC_boss_sindragosa ()
Variables
static const float SindragosaPosition [10][3]
Macro Definition Documentation
FROST_BOMB_MAX_X
#define FROST_BOMB_MAX_X 4424.0f
Definition at line 122 of file boss_sindragosa.cpp.
FROST_BOMB_MAX_Y
#define FROST_BOMB_MAX_Y 2527.0f
Definition at line 124 of file boss_sindragosa.cpp.
FROST_BOMB_MIN_X
#define FROST_BOMB_MIN_X 4367.0f
Definition at line 121 of file boss_sindragosa.cpp.
FROST_BOMB_MIN_Y
#define FROST_BOMB_MIN_Y 2437.0f
Definition at line 123 of file boss_sindragosa.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_UNCHAINED_MAGIC
SAY_BLISTERING_COLD
SAY_RESPIRE
SAY_TAKEOFF
SAY_PHASE_3
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
SPELL_BERSERK
SPELL_TAIL_SMASH
SPELL_CLEAVE
SPELL_FROST_AURA
SPELL_FROST_BREATH
SPELL_ICY_GRIP
SPELL_PERMEATING_CHILL
SPELL_UNCHAINED_MAGIC
SPELL_ICE_TOMB
SPELL_ICE_TOMB_PROTECTION
SPELL_FROST_BOMB
SPELL_FROST_BOMB_DMG
SPELL_FROST_BOMB_VISUAL
SPELL_MYSTIC_BUFFET
SPELL_ICE_TOMB_SINGLE
SPELL_RIMEFANG_FROST_AURA
SPELL_RIMEFANG_FROST_BREATH
SPELL_RIMEFANG_ICY_BLAST
SPELL_SPINESTALKER_BELLOWING_ROAR
SPELL_SPINESTALKER_CLEAVE
SPELL_SPINESTALKER_TAIL_SWEEP
Definition at line 27 of file boss_sindragosa.cpp.
RimefangPhase
enum RimefangPhase
Enumerator
RIMEFANG_PHASE_GROUND
RIMEFANG_PHASE_FLYING
RIMEFANG_PHASE_AIR
Definition at line 100 of file boss_sindragosa.cpp.
RimefangPoint
enum RimefangPoint
Enumerator
RIMEFANG_POINT_GROUND
RIMEFANG_POINT_AIR
RIMEFANG_POINT_INITIAL_LAND_AIR
RIMEFANG_POINT_INITIAL_LAND
Definition at line 107 of file boss_sindragosa.cpp.
SindragosaPhase
enum SindragosaPhase
Enumerator
SINDRAGOSA_PHASE_OOC
SINDRAGOSA_PHASE_AGGRO
SINDRAGOSA_PHASE_GROUND
SINDRAGOSA_PHASE_FLYING_TO_AIR
SINDRAGOSA_PHASE_AIR
SINDRAGOSA_PHASE_FLYING_TO_GROUND
SINDRAGOSA_PHASE_THREE
Definition at line 80 of file boss_sindragosa.cpp.
SindragosaPoint
enum SindragosaPoint
Enumerator
SINDRAGOSA_POINT_GROUND_CENTER
SINDRAGOSA_POINT_AIR_CENTER
SINDRAGOSA_POINT_AIR_PHASE_2
SINDRAGOSA_POINT_AIR_EAST
SINDRAGOSA_POINT_AIR_WEST
Definition at line 91 of file boss_sindragosa.cpp.
SpinestalkerPoint
enum SpinestalkerPoint
Enumerator
SPINESTALKER_POINT_INITIAL_LAND_AIR
SPINESTALKER_POINT_INITIAL_LAND
Definition at line 115 of file boss_sindragosa.cpp.
Function Documentation
AddSC_boss_sindragosa()
void AddSC_boss_sindragosa ()
Definition at line 849 of file boss_sindragosa.cpp.
References Script::GetAI, GetAI_boss_sindragosa(), GetAI_mob_frost_bomb(), GetAI_npc_rimefang_icc(), GetAI_npc_spinestalker_icc(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_sindragosa()
UnitAI* GetAI_boss_sindragosa (Creature * pCreature)
Definition at line 459 of file boss_sindragosa.cpp.
Referenced by AddSC_boss_sindragosa().
GetAI_mob_frost_bomb()
UnitAI* GetAI_mob_frost_bomb (Creature * pCreature)
Definition at line 844 of file boss_sindragosa.cpp.
Referenced by AddSC_boss_sindragosa().
GetAI_npc_rimefang_icc()
UnitAI* GetAI_npc_rimefang_icc (Creature * pCreature)
Definition at line 652 of file boss_sindragosa.cpp.
Referenced by AddSC_boss_sindragosa().
GetAI_npc_spinestalker_icc()
UnitAI* GetAI_npc_spinestalker_icc (Creature * pCreature)
Definition at line 790 of file boss_sindragosa.cpp.
Referenced by AddSC_boss_sindragosa().
Variable Documentation
SindragosaPosition
const float SindragosaPosition[10][3] static
Initial value:
=
{
    {4407.44f, 2484.37f, 203.37f},
    {4407.44f, 2484.37f, 235.37f},
    {4470.00f, 2484.37f, 235.37f},
    {4414.32f, 2456.94f, 203.37f},
    {4414.32f, 2456.94f, 228.37f},
    {4414.32f, 2512.73f, 203.37f},
    {4414.32f, 2512.73f, 228.37f},
    {4505.00f, 2484.37f, 235.37f},
    {4505.00f, 2444.37f, 235.37f},
    {4505.00f, 2524.37f, 235.37f},
}
Definition at line 126 of file boss_sindragosa.cpp.
Referenced by boss_sindragosaAI::AttackStart(), npc_rimefang_iccAI::AttackStart(), npc_spinestalker_iccAI::AttackStart(), boss_sindragosaAI::DoFrostBomb(), npc_rimefang_iccAI::EnterEvadeMode(), npc_spinestalker_iccAI::EnterEvadeMode(), npc_rimefang_iccAI::JustDied(), npc_spinestalker_iccAI::JustDied(), boss_sindragosaAI::JustReachedHome(), boss_sindragosaAI::MovementInform(), npc_rimefang_iccAI::MovementInform(), npc_spinestalker_iccAI::MovementInform(), and boss_sindragosaAI::UpdateAI().