CMaNGOS_WoTLK: boss_pyroguard_emberseer.cpp File Reference
boss_pyroguard_emberseer.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackrock_spire.h"
Data Structures
struct boss_pyroguard_emberseerAI
Enumerations
enum {
EMOTE_NEAR = -1229001 , EMOTE_FULL = -1229002 , SAY_FREE = -1229003 , MAX_GROWING_STACKS = 20 ,
SPELL_ENCAGE_EMBERSEER = 15281 , SPELL_FIRE_SHIELD = 13376 , SPELL_DESPAWN_EMBERSEER = 16078 , SPELL_FREEZE_ANIM = 16245 ,
SPELL_FULL_STRENGHT = 16047 , SPELL_GROWING = 16049 , SPELL_BONUS_DAMAGE = 16534 , SPELL_TRANSFORM = 16052 ,
SPELL_FIRENOVA = 23462 , SPELL_FLAMEBUFFET = 23341 , SPELL_PYROBLAST = 20228
}
Functions
UnitAI * GetAI_boss_pyroguard_emberseer (Creature *pCreature)
void AddSC_boss_pyroguard_emberseer ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_NEAR
EMOTE_FULL
SAY_FREE
MAX_GROWING_STACKS
SPELL_ENCAGE_EMBERSEER
SPELL_FIRE_SHIELD
SPELL_DESPAWN_EMBERSEER
SPELL_FREEZE_ANIM
SPELL_FULL_STRENGHT
SPELL_GROWING
SPELL_BONUS_DAMAGE
SPELL_TRANSFORM
SPELL_FIRENOVA
SPELL_FLAMEBUFFET
SPELL_PYROBLAST
Definition at line 27 of file boss_pyroguard_emberseer.cpp.
Function Documentation
AddSC_boss_pyroguard_emberseer()
void AddSC_boss_pyroguard_emberseer ()
Definition at line 200 of file boss_pyroguard_emberseer.cpp.
References Script::GetAI, GetAI_boss_pyroguard_emberseer(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_pyroguard_emberseer()
UnitAI* GetAI_boss_pyroguard_emberseer (Creature * pCreature)
Definition at line 195 of file boss_pyroguard_emberseer.cpp.
Referenced by AddSC_boss_pyroguard_emberseer().