CMaNGOS_WoTLK: boss_ignis.cpp File Reference
boss_ignis.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_ignisAI
struct npc_iron_constructAI
struct npc_scorchAI
Enumerations
enum {
SAY_AGGRO = -1603026 , SAY_SLAGPOT_1 = -1603027 , SAY_SLAGPOT_2 = -1603028 , SAY_FLAME_JETS = -1603029 ,
SAY_ADDS = -1603030 , SAY_SLAY_1 = -1603031 , SAY_SLAY_2 = -1603032 , SAY_BERSERK = -1603033 ,
SAY_DEATH = -1603034 , EMOTE_FLAME_JETS = -1603035 , EMOTE_EXTINGUISH_SCORCH = -1603238 , SPELL_FLAME_JETS = 62680 ,
SPELL_FLAME_JETS_H = 63472 , SPELL_SLAG_POT = 62717 , SPELL_GRAB = 62707 , SPELL_GRAB_POT = 62711 ,
SPELL_SCORCH = 62546 , SPELL_SCORCH_H = 63474 , SPELL_SCORCH_SUMMON = 62551 , SPELL_ACTIVATE_CONSTRUCT = 62488 ,
SPELL_KILL_ALL_CONSTRUCTS = 65109 , SPELL_BERSERK = 26662 , SPELL_CONSTRUCT_HITTING_YA = 65110 , SPELL_STONED = 62468 ,
SPELL_HEAT = 65667 , SPELL_MOLTEN = 62373 , SPELL_CHILL = 62381 , SPELL_BRITTLE = 62382 ,
SPELL_BRITTLE_H = 67114 , SPELL_SHATTER = 62383 , SPELL_STRENGTH_REMOVE = 64475 , SPELL_WATER_EFFECT = 64503 ,
SPELL_SCORCH_AURA = 62548 , SPELL_SCORCH_AURA_H = 63476 , NPC_SCORCH = 33221 , NPC_IRON_CONSTRUCT = 33121 ,
MAX_HEAT_STACKS = 10
}
Functions
UnitAI * GetAI_boss_ignis (Creature *pCreature)
UnitAI * GetAI_npc_iron_construct (Creature *pCreature)
bool EffectScriptEffectCreature_npc_iron_construct (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_scorch (Creature *pCreature)
bool EffectScriptEffectCreature_npc_scorch (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_ignis ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAGPOT_1
SAY_SLAGPOT_2
SAY_FLAME_JETS
SAY_ADDS
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_DEATH
EMOTE_FLAME_JETS
EMOTE_EXTINGUISH_SCORCH
SPELL_FLAME_JETS
SPELL_FLAME_JETS_H
SPELL_SLAG_POT
SPELL_GRAB
SPELL_GRAB_POT
SPELL_SCORCH
SPELL_SCORCH_H
SPELL_SCORCH_SUMMON
SPELL_ACTIVATE_CONSTRUCT
SPELL_KILL_ALL_CONSTRUCTS
SPELL_BERSERK
SPELL_CONSTRUCT_HITTING_YA
SPELL_STONED
SPELL_HEAT
SPELL_MOLTEN
SPELL_CHILL
SPELL_BRITTLE
SPELL_BRITTLE_H
SPELL_SHATTER
SPELL_STRENGTH_REMOVE
SPELL_WATER_EFFECT
SPELL_SCORCH_AURA
SPELL_SCORCH_AURA_H
NPC_SCORCH
NPC_IRON_CONSTRUCT
MAX_HEAT_STACKS
Definition at line 28 of file boss_ignis.cpp.
Function Documentation
AddSC_boss_ignis()
void AddSC_boss_ignis ()
Definition at line 363 of file boss_ignis.cpp.
References EffectScriptEffectCreature_npc_iron_construct(), EffectScriptEffectCreature_npc_scorch(), Script::GetAI, GetAI_boss_ignis(), GetAI_npc_iron_construct(), GetAI_npc_scorch(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectScriptEffectCreature_npc_iron_construct()
bool EffectScriptEffectCreature_npc_iron_construct (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 316 of file boss_ignis.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), Unit::HasAura(), NPC_IRON_CONSTRUCT, SPELL_CHILL, SPELL_MOLTEN, SPELL_WATER_EFFECT, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_ignis().
EffectScriptEffectCreature_npc_scorch()
bool EffectScriptEffectCreature_npc_scorch (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 350 of file boss_ignis.cpp.
References DoScriptText(), EFFECT_INDEX_0, EMOTE_EXTINGUISH_SCORCH, Creature::ForcedDespawn(), Object::GetEntry(), NPC_SCORCH, and SPELL_WATER_EFFECT.
Referenced by AddSC_boss_ignis().
GetAI_boss_ignis()
UnitAI* GetAI_boss_ignis (Creature * pCreature)
Definition at line 231 of file boss_ignis.cpp.
Referenced by AddSC_boss_ignis().
GetAI_npc_iron_construct()
UnitAI* GetAI_npc_iron_construct (Creature * pCreature)
Definition at line 311 of file boss_ignis.cpp.
Referenced by AddSC_boss_ignis().
GetAI_npc_scorch()
UnitAI* GetAI_npc_scorch (Creature * pCreature)
Definition at line 345 of file boss_ignis.cpp.
Referenced by AddSC_boss_ignis().