CMaNGOS_WoTLK: boss_nethermancer_sepethrea.cpp File Reference
boss_nethermancer_sepethrea.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "mechanar.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct boss_nethermancer_sepethreaAI
struct npc_raging_flamesAI
Enumerations
enum {
SAY_AGGRO = -1554013 , SAY_SUMMON = -1554014 , SAY_DRAGONS_BREATH_1 = -1554015 , SAY_DRAGONS_BREATH_2 = -1554016 ,
SAY_SLAY1 = -1554017 , SAY_SLAY2 = -1554018 , SAY_DEATH = -1554019 , SPELL_SUMMON_RAGING_FLAMES = 35275 ,
SPELL_SUMMON_RAGING_FLAMES_H = 39084 , SPELL_FROST_ATTACK = 45196 , SPELL_ARCANE_BLAST = 35314 , SPELL_DRAGONS_BREATH = 35250 ,
NPC_RAGING_FLAMES = 20481
}
enum { SPELL_RAGING_FLAMES = 35281 , SPELL_INFERNO = 35268 , SPELL_INFERNO_H = 39346 }
Functions
UnitAI * GetAI_boss_nethermancer_sepethrea (Creature *pCreature)
UnitAI * GetAI_npc_raging_flames (Creature *pCreature)
void AddSC_boss_nethermancer_sepethrea ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SUMMON
SAY_DRAGONS_BREATH_1
SAY_DRAGONS_BREATH_2
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SPELL_SUMMON_RAGING_FLAMES
SPELL_SUMMON_RAGING_FLAMES_H
SPELL_FROST_ATTACK
SPELL_ARCANE_BLAST
SPELL_DRAGONS_BREATH
NPC_RAGING_FLAMES
Definition at line 28 of file boss_nethermancer_sepethrea.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RAGING_FLAMES
SPELL_INFERNO
SPELL_INFERNO_H
Definition at line 143 of file boss_nethermancer_sepethrea.cpp.
Function Documentation
AddSC_boss_nethermancer_sepethrea()
void AddSC_boss_nethermancer_sepethrea ()
Definition at line 216 of file boss_nethermancer_sepethrea.cpp.
References Script::GetAI, GetAI_boss_nethermancer_sepethrea(), GetAI_npc_raging_flames(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_nethermancer_sepethrea()
UnitAI* GetAI_boss_nethermancer_sepethrea (Creature * pCreature)
Definition at line 138 of file boss_nethermancer_sepethrea.cpp.
Referenced by AddSC_boss_nethermancer_sepethrea().
GetAI_npc_raging_flames()
UnitAI* GetAI_npc_raging_flames (Creature * pCreature)
Definition at line 211 of file boss_nethermancer_sepethrea.cpp.
Referenced by AddSC_boss_nethermancer_sepethrea().