CMaNGOS_WoTLK: boss_jandice_barov.cpp File Reference
boss_jandice_barov.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_jandicebarovAI
Enumerations
enum {
SPELL_CURSE_OF_BLOOD = 16098 , SPELL_SPREAD_ILLUSIONS = 17772 , SPELL_SUMMON_ILLUSIONS = 17773 , SPELL_SPREAD_JANDICE = 17774 ,
SPELL_BANISH = 8994
}
Functions
UnitAI * GetAI_boss_jandicebarov (Creature *pCreature)
void AddSC_boss_jandicebarov ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_CURSE_OF_BLOOD
SPELL_SPREAD_ILLUSIONS
SPELL_SUMMON_ILLUSIONS
SPELL_SPREAD_JANDICE
SPELL_BANISH
Definition at line 26 of file boss_jandice_barov.cpp.
Function Documentation
AddSC_boss_jandicebarov()
void AddSC_boss_jandicebarov ()
Definition at line 104 of file boss_jandice_barov.cpp.
References Script::GetAI, GetAI_boss_jandicebarov(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_jandicebarov()
UnitAI* GetAI_boss_jandicebarov (Creature * pCreature)
Definition at line 99 of file boss_jandice_barov.cpp.
Referenced by AddSC_boss_jandicebarov().