CMaNGOS_WoTLK: boss_exarch_maladaar.cpp File Reference
boss_exarch_maladaar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct mob_stolen_soulAI
struct boss_exarch_maladaarAI
Enumerations
enum {
SPELL_STOLEN_SOUL_DISPEL = 33326 , SPELL_MOONFIRE = 37328 , SPELL_FIREBALL = 37329 , SPELL_MIND_FLAY = 37330 ,
SPELL_HEMORRHAGE = 37331 , SPELL_FROSTSHOCK = 37332 , SPELL_CURSE_OF_AGONY = 37334 , SPELL_MORTAL_STRIKE = 37335 ,
SPELL_FREEZING_TRAP = 37368 , SPELL_HAMMER_OF_JUSTICE = 37369 , SPELL_PLAGUE_STRIKE = 58339
}
enum {
SAY_INTRO = -1558000 , SAY_SUMMON = -1558001 , SAY_AGGRO_1 = -1558002 , SAY_AGGRO_2 = -1558003 ,
SAY_AGGRO_3 = -1558004 , SAY_ROAR = -1558005 , SAY_SOUL_CLEAVE = -1558006 , SAY_SLAY_1 = -1558007 ,
SAY_SLAY_2 = -1558008 , SAY_DEATH = -1558009 , SPELL_RIBBON_OF_SOULS = 32422 , SPELL_SOUL_SCREAM = 32421 ,
SPELL_STOLEN_SOUL = 32346 , SPELL_STOLEN_SOUL_VISUAL = 32395 , SPELL_SUMMON_AVATAR = 32424 , SPELL_PHASE_IN = 33422 ,
NPC_STOLEN_SOUL = 18441 , NPC_DORE = 19412 , NPC_AVATAR_MARTYRED = 18478
}
Functions
UnitAI * GetAI_mob_stolen_soul (Creature *pCreature)
UnitAI * GetAI_boss_exarch_maladaar (Creature *pCreature)
void AddSC_boss_exarch_maladaar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_STOLEN_SOUL_DISPEL
SPELL_MOONFIRE
SPELL_FIREBALL
SPELL_MIND_FLAY
SPELL_HEMORRHAGE
SPELL_FROSTSHOCK
SPELL_CURSE_OF_AGONY
SPELL_MORTAL_STRIKE
SPELL_FREEZING_TRAP
SPELL_HAMMER_OF_JUSTICE
SPELL_PLAGUE_STRIKE
Definition at line 31 of file boss_exarch_maladaar.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_SUMMON
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_ROAR
SAY_SOUL_CLEAVE
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SPELL_RIBBON_OF_SOULS
SPELL_SOUL_SCREAM
SPELL_STOLEN_SOUL
SPELL_STOLEN_SOUL_VISUAL
SPELL_SUMMON_AVATAR
SPELL_PHASE_IN
NPC_STOLEN_SOUL
NPC_DORE
NPC_AVATAR_MARTYRED
Definition at line 137 of file boss_exarch_maladaar.cpp.
Function Documentation
AddSC_boss_exarch_maladaar()
void AddSC_boss_exarch_maladaar ()
Definition at line 322 of file boss_exarch_maladaar.cpp.
References Script::GetAI, GetAI_boss_exarch_maladaar(), GetAI_mob_stolen_soul(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_exarch_maladaar()
UnitAI* GetAI_boss_exarch_maladaar (Creature * pCreature)
Definition at line 317 of file boss_exarch_maladaar.cpp.
Referenced by AddSC_boss_exarch_maladaar().
GetAI_mob_stolen_soul()
UnitAI* GetAI_mob_stolen_soul (Creature * pCreature)
Definition at line 132 of file boss_exarch_maladaar.cpp.
Referenced by AddSC_boss_exarch_maladaar().