CMaNGOS_WoTLK: boss_kelthuzad.cpp File Reference
boss_kelthuzad.cpp File Reference
#include "AI/ScriptDevAI/base/BossAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_kelthuzadAI
struct TriggerKTAdd
struct ChainsKelThuzad
struct FrostBlast
Enumerations
enum {
SAY_SUMMON_MINIONS = 12999 , EMOTE_PHASE2 = 32803 , SAY_AGGRO1 = 12995 , SAY_AGGRO2 = 12996 ,
SAY_AGGRO3 = 12997 , SAY_SLAY1 = 13021 , SAY_SLAY2 = 13022 , SAY_DEATH = 13019 ,
SAY_CHAIN1 = 13017 , SAY_CHAIN2 = 13018 , SAY_FROST_BLAST = 13020 , SAY_REQUEST_AID = 12998 ,
SAY_ANSWER_REQUEST = 12994 , SAY_SPECIAL1_MANA_DET = 13492 , EMOTE_GUARDIAN = 32804 , SPELL_FROST_BOLT = 28478 ,
SPELL_FROST_BOLT_H = 55802 , SPELL_FROST_BOLT_NOVA = 28479 , SPELL_FROST_BOLT_NOVA_H = 55807 , SPELL_CHAINS_OF_KELTHUZAD = 28408 ,
SPELL_CHAINS_OF_KELTHUZAD_SCALE = 28409 , SPELL_CHAINS_OF_KELTHUZAD_TARGET = 28410 , SPELL_MANA_DETONATION = 27819 , SPELL_SHADOW_FISSURE = 27810 ,
SPELL_FROST_BLAST = 27808 , SPELL_FROST_BLAST_DAMAGE = 29879 , SPELL_CHANNEL_VISUAL = 29423 , MAX_SOLDIER_COUNT = 71 ,
MAX_ABOMINATION_COUNT = 8 , MAX_BANSHEE_COUNT = 8 , SPELL_CHANNEL_VISUAL_EFFECT = 29422 , NPC_WORLD_TRIGGER = 15384 ,
MAX_SUMMON_TICKS = 5 * MINUTE + 10 , MAX_CHANNEL_TICKS = 5 * MINUTE + 25 , SPELL_SUMMON_PERIODIC_A_1 = 29410 , SPELL_SUMMON_PERIODIC_A_2 = 29391 ,
SPELL_SUMMON_PERIODIC_A_3 = 28425 , SPELL_SUMMON_PERIODIC_A_4 = 29392 , SPELL_SUMMON_PERIODIC_A_5 = 29409 , SPELL_SUMMON_PERIODIC_B_1 = 28426 ,
SPELL_SUMMON_PERIODIC_B_2 = 29393 , SPELL_SUMMON_PERIODIC_B_3 = 29394 , SPELL_SUMMON_PERIODIC_B_4 = 29398 , SPELL_SUMMON_PERIODIC_B_5 = 29411 ,
SPELL_SUMMON_PERIODIC_C_1 = 29399 , SPELL_SUMMON_PERIODIC_C_2 = 29400 , SPELL_SUMMON_PERIODIC_C_3 = 28427 , SPELL_SUMMON_PERIODIC_C_4 = 29401 ,
SPELL_SUMMON_PERIODIC_C_5 = 29412 , SPELL_SUMMON_TYPE_A = 28421 , SPELL_SUMMON_TYPE_B = 28422 , SPELL_SUMMON_TYPE_C = 28423 ,
SPELL_SUMMON_TYPE_D = 28454 , SPELL_SUMMON_PERIODIC_D = 28453 , SPELL_GUARDIAN_INIT = 29898 , MAX_CONTROLLED_TARGETS = 2 ,
ACHIEV_REQ_KILLED_ABOMINATIONS = 18
}
enum Phase {
PHASE_ONE = 1 , PHASE_RUNNING_ONE = 2 , PHASE_TRANSITION_ONE = 3 , PHASE_TWO = 4 ,
PHASE_RUNNING_TWO = 5 , PHASE_TRANSITION_TWO = 6 , PHASE_THREE = 7 , PHASE_INTRO = 0 ,
PHASE_ONE = 1 , PHASE_RUNNING_WINTER_ONE = 2 , PHASE_TRANSITION_ONE = 3 , PHASE_QUAKE_ONE = 4 ,
PHASE_TWO = 5 , PHASE_RUNNING_WINTER_TWO = 6 , PHASE_TRANSITION_TWO = 7 , PHASE_QUAKE_TWO = 8 ,
PHASE_THREE = 9 , PHASE_IN_FROSTMOURNE = 10 , PHASE_CUTSCENE = 11 , PHASE_DEATH_AWAITS = 12 ,
PHASE_INTRO , PHASE_NORMAL , PHASE_GUARDIANS
}
enum KelThuzadActions { KELTHUZAD_PHASE_GUARDIANS , KELTHUZAD_ACTIONS_MAX , KELTHUZAD_LICH_KING_ANSWER }
Functions
const Position centerRoomKT (3716.f, -5106.f, 141.f)
void AddSC_boss_kelthuzad ()
Variables
static const uint32 phaseOneAdds [] = {NPC_SOLDIER_FROZEN, NPC_UNSTOPPABLE_ABOM, NPC_SOUL_WEAVER}
static const std::vector< std::vector< uint32 > > soulWeaverSpellsTimers
static const std::vector< std::vector< uint32 > > unstoppableAbominationSpellsTimers
static const std::vector< std::vector< uint32 > > soldierFrozenWasteSpellsTimers
static const std::map< uint32, std::vector< uint32 > > summoningSpells
static float M_F_ANGLE = 0.2f
static float M_F_HEIGHT = 2.0f
static float M_F_RANGE = 55.0f
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SUMMON_MINIONS
EMOTE_PHASE2
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SAY_CHAIN1
SAY_CHAIN2
SAY_FROST_BLAST
SAY_REQUEST_AID
SAY_ANSWER_REQUEST
SAY_SPECIAL1_MANA_DET
EMOTE_GUARDIAN
SPELL_FROST_BOLT
SPELL_FROST_BOLT_H
SPELL_FROST_BOLT_NOVA
SPELL_FROST_BOLT_NOVA_H
SPELL_CHAINS_OF_KELTHUZAD
SPELL_CHAINS_OF_KELTHUZAD_SCALE
SPELL_CHAINS_OF_KELTHUZAD_TARGET
SPELL_MANA_DETONATION
SPELL_SHADOW_FISSURE
SPELL_FROST_BLAST
SPELL_FROST_BLAST_DAMAGE
SPELL_CHANNEL_VISUAL
MAX_SOLDIER_COUNT
MAX_ABOMINATION_COUNT
MAX_BANSHEE_COUNT
SPELL_CHANNEL_VISUAL_EFFECT
NPC_WORLD_TRIGGER
MAX_SUMMON_TICKS
MAX_CHANNEL_TICKS
SPELL_SUMMON_PERIODIC_A_1
SPELL_SUMMON_PERIODIC_A_2
SPELL_SUMMON_PERIODIC_A_3
SPELL_SUMMON_PERIODIC_A_4
SPELL_SUMMON_PERIODIC_A_5
SPELL_SUMMON_PERIODIC_B_1
SPELL_SUMMON_PERIODIC_B_2
SPELL_SUMMON_PERIODIC_B_3
SPELL_SUMMON_PERIODIC_B_4
SPELL_SUMMON_PERIODIC_B_5
SPELL_SUMMON_PERIODIC_C_1
SPELL_SUMMON_PERIODIC_C_2
SPELL_SUMMON_PERIODIC_C_3
SPELL_SUMMON_PERIODIC_C_4
SPELL_SUMMON_PERIODIC_C_5
SPELL_SUMMON_TYPE_A
SPELL_SUMMON_TYPE_B
SPELL_SUMMON_TYPE_C
SPELL_SUMMON_TYPE_D
SPELL_SUMMON_PERIODIC_D
SPELL_GUARDIAN_INIT
MAX_CONTROLLED_TARGETS
ACHIEV_REQ_KILLED_ABOMINATIONS
Definition at line 32 of file boss_kelthuzad.cpp.
KelThuzadActions
enum KelThuzadActions
Enumerator
KELTHUZAD_PHASE_GUARDIANS
KELTHUZAD_ACTIONS_MAX
KELTHUZAD_LICH_KING_ANSWER
Definition at line 168 of file boss_kelthuzad.cpp.
Phase
enum Phase
Enumerator
PHASE_ONE
PHASE_RUNNING_ONE
PHASE_TRANSITION_ONE
PHASE_TWO
PHASE_RUNNING_TWO
PHASE_TRANSITION_TWO
PHASE_THREE
PHASE_INTRO
PHASE_ONE
PHASE_RUNNING_WINTER_ONE
PHASE_TRANSITION_ONE
PHASE_QUAKE_ONE
PHASE_TWO
PHASE_RUNNING_WINTER_TWO
PHASE_TRANSITION_TWO
PHASE_QUAKE_TWO
PHASE_THREE
PHASE_IN_FROSTMOURNE
PHASE_CUTSCENE
PHASE_DEATH_AWAITS
PHASE_INTRO
PHASE_NORMAL
PHASE_GUARDIANS
Definition at line 161 of file boss_kelthuzad.cpp.
Function Documentation
AddSC_boss_kelthuzad()
void AddSC_boss_kelthuzad ()
Definition at line 617 of file boss_kelthuzad.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
centerRoomKT()
const Position centerRoomKT (3716. f, -5106. f, 141. f)
Referenced by TriggerKTAdd::OnCheckTarget(), and boss_kelthuzadAI::SpellHit().
Variable Documentation
M_F_ANGLE
float M_F_ANGLE = 0.2f static
Definition at line 157 of file boss_kelthuzad.cpp.
M_F_HEIGHT
float M_F_HEIGHT = 2.0f static
Definition at line 158 of file boss_kelthuzad.cpp.
M_F_RANGE
float M_F_RANGE = 55.0f static
Definition at line 159 of file boss_kelthuzad.cpp.
phaseOneAdds
const uint32 phaseOneAdds[] = {NPC_SOLDIER_FROZEN, NPC_UNSTOPPABLE_ABOM, NPC_SOUL_WEAVER} static
Definition at line 117 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
soldierFrozenWasteSpellsTimers
const std::vector<std::vector<uint32> > soldierFrozenWasteSpellsTimers static
Initial value:
{
        {7,   SPELL_SUMMON_PERIODIC_A_1},
        {73,  SPELL_SUMMON_PERIODIC_A_2},
        {134, SPELL_SUMMON_PERIODIC_A_3},
        {189, SPELL_SUMMON_PERIODIC_A_4},
        {244, SPELL_SUMMON_PERIODIC_A_5},
        {292, 0}
}
Definition at line 139 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
soulWeaverSpellsTimers
const std::vector<std::vector<uint32> > soulWeaverSpellsTimers static
Initial value:
{
        {1,   SPELL_SUMMON_PERIODIC_C_1},
        {42,  SPELL_SUMMON_PERIODIC_C_4},
        {63,  SPELL_SUMMON_PERIODIC_C_3},
        {154, SPELL_SUMMON_PERIODIC_C_5},
        {290, 0}
}
Definition at line 120 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
summoningSpells
const std::map<uint32, std::vector<uint32> > summoningSpells static
Initial value:
{
        {NPC_SOUL_WEAVER,      {SPELL_SUMMON_PERIODIC_C_1, SPELL_SUMMON_PERIODIC_C_2, SPELL_SUMMON_PERIODIC_C_3, SPELL_SUMMON_PERIODIC_C_4, SPELL_SUMMON_PERIODIC_C_5}},
        {NPC_UNSTOPPABLE_ABOM, {SPELL_SUMMON_PERIODIC_B_1, SPELL_SUMMON_PERIODIC_B_2, SPELL_SUMMON_PERIODIC_B_3, SPELL_SUMMON_PERIODIC_B_4, SPELL_SUMMON_PERIODIC_B_5}},
        {NPC_SOLDIER_FROZEN,   {SPELL_SUMMON_PERIODIC_A_1, SPELL_SUMMON_PERIODIC_A_2, SPELL_SUMMON_PERIODIC_A_3, SPELL_SUMMON_PERIODIC_A_4, SPELL_SUMMON_PERIODIC_A_5}}
}
Definition at line 150 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::StopAllSummoningForNPC().
unstoppableAbominationSpellsTimers
const std::vector<std::vector<uint32> > unstoppableAbominationSpellsTimers static
Initial value:
{
        {15,  SPELL_SUMMON_PERIODIC_B_1},
        {76,  SPELL_SUMMON_PERIODIC_B_2},
        {127, SPELL_SUMMON_PERIODIC_B_3},
        {228, SPELL_SUMMON_PERIODIC_B_4},
        {259, SPELL_SUMMON_PERIODIC_B_5},
        {291, 0}
}
Definition at line 129 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().