CMaNGOS_WoTLK: boss_tharonja.cpp File Reference
boss_tharonja.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Globals/ObjectMgr.h"
#include "draktharon_keep.h"
Data Structures
struct boss_tharonjaAI
Enumerations
enum {
SAY_AGGRO = -1600012 , SAY_KILL_1 = -1600013 , SAY_KILL_2 = -1600014 , SAY_FLESH_1 = -1600015 ,
SAY_FLESH_2 = -1600016 , SAY_SKELETON_1 = -1600017 , SAY_SKELETON_2 = -1600018 , SAY_DEATH = -1600019 ,
SPELL_CURSE_OF_LIFE = 49527 , SPELL_CURSE_OF_LIFE_H = 59972 , SPELL_RAIN_OF_FIRE = 49518 , SPELL_RAIN_OF_FIRE_H = 59971 ,
SPELL_SHADOW_VOLLEY = 49528 , SPELL_SHADOW_VOLLEY_H = 59973 , SPELL_LIGHTNING_BREATH = 49537 , SPELL_LIGHTNING_BREATH_H = 59963 ,
SPELL_EYE_BEAM = 49544 , SPELL_EYE_BEAM_H = 59965 , SPELL_POISON_CLOUD = 49548 , SPELL_POISON_CLOUD_H = 59969 ,
SPELL_DECAY_FLESH = 49356 , SPELL_GIFT_OF_THARONJA = 52509 , SPELL_RETURN_FLESH = 53463 , SPELL_CLEAR_GIFT_OF_THARONJA = 53242 ,
SPELL_ACHIEVEMENT_CHECK = 61863 , NPC_THARONJA_SKELETAL = 26632 , NPC_THARONJA_FLESH = 27696
}
enum Phases {
PHASE_GROUND = 0 , PHASE_UNDERGROUND = 1 , PHASE_LEECHING_SWARM = 2 , PHASE_SUBMERGING = 3 ,
PHASE_IDLE = 0 , PHASE_SHIELDED = 1 , PHASE_WAITING = 2 , PHASE_NORMAL = 3 ,
PHASE_SKELETAL = 0 , PHASE_TAKE_FLESH = 1 , PHASE_FLESH = 2 , PHASE_RETURN_FLESH = 3 ,
PHASE_SKELETAL_END = 4 , PHASE_EMERGING = 0 , PHASE_NORMAL = 1 , PHASE_SPOUT = 2 ,
PHASE_SUBMERGED = 3 , PHASE_NORMAL = 1 , PHASE_SPLIT = 2 , PHASE_VOID = 3
}
Functions
UnitAI * GetAI_boss_tharonja (Creature *pCreature)
void AddSC_boss_tharonja ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_KILL_1
SAY_KILL_2
SAY_FLESH_1
SAY_FLESH_2
SAY_SKELETON_1
SAY_SKELETON_2
SAY_DEATH
SPELL_CURSE_OF_LIFE
SPELL_CURSE_OF_LIFE_H
SPELL_RAIN_OF_FIRE
SPELL_RAIN_OF_FIRE_H
SPELL_SHADOW_VOLLEY
SPELL_SHADOW_VOLLEY_H
SPELL_LIGHTNING_BREATH
SPELL_LIGHTNING_BREATH_H
SPELL_EYE_BEAM
SPELL_EYE_BEAM_H
SPELL_POISON_CLOUD
SPELL_POISON_CLOUD_H
SPELL_DECAY_FLESH
SPELL_GIFT_OF_THARONJA
SPELL_RETURN_FLESH
SPELL_CLEAR_GIFT_OF_THARONJA
SPELL_ACHIEVEMENT_CHECK
NPC_THARONJA_SKELETAL
NPC_THARONJA_FLESH
Definition at line 28 of file boss_tharonja.cpp.
Phases
enum Phases
Enumerator
PHASE_GROUND
PHASE_UNDERGROUND
PHASE_LEECHING_SWARM
PHASE_SUBMERGING
PHASE_IDLE
PHASE_SHIELDED
PHASE_WAITING
PHASE_NORMAL
PHASE_SKELETAL
PHASE_TAKE_FLESH
PHASE_FLESH
PHASE_RETURN_FLESH
PHASE_SKELETAL_END
PHASE_EMERGING
PHASE_NORMAL
PHASE_SPOUT
PHASE_SUBMERGED
PHASE_NORMAL
PHASE_SPLIT
PHASE_VOID
Definition at line 63 of file boss_tharonja.cpp.
Function Documentation
AddSC_boss_tharonja()
void AddSC_boss_tharonja ()
Definition at line 285 of file boss_tharonja.cpp.
References Script::GetAI, GetAI_boss_tharonja(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_tharonja()
UnitAI* GetAI_boss_tharonja (Creature * pCreature)
Definition at line 280 of file boss_tharonja.cpp.
Referenced by AddSC_boss_tharonja().