CMaNGOS_WoTLK: boss_trollgore.cpp File Reference
boss_trollgore.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "draktharon_keep.h"
Data Structures
struct boss_trollgoreAI
Enumerations
enum {
SAY_AGGRO = -1600000 , SAY_CONSUME = -1600001 , SAY_DEATH = -1600002 , SAY_EXPLODE = -1600003 ,
SAY_KILL = -1600004 , SPELL_CRUSH = 49639 , SPELL_INFECTED_WOUND = 49637 , SPELL_CORPSE_EXPLODE = 49555 ,
SPELL_CORPSE_EXPLODE_H = 59807 , SPELL_CONSUME = 49380 , SPELL_CONSUME_H = 59803 , SPELL_CONSUME_BUFF = 49381 ,
SPELL_CONSUME_BUFF_H = 59805 , SPELL_SUMMON_INVADER_1 = 49456 , SPELL_SUMMON_INVADER_2 = 49457 , SPELL_INVADER_TAUNT = 49405 ,
MAX_CONSOME_STACKS = 10
}
Functions
UnitAI * GetAI_boss_trollgore (Creature *pCreature)
void AddSC_boss_trollgore ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_CONSUME
SAY_DEATH
SAY_EXPLODE
SAY_KILL
SPELL_CRUSH
SPELL_INFECTED_WOUND
SPELL_CORPSE_EXPLODE
SPELL_CORPSE_EXPLODE_H
SPELL_CONSUME
SPELL_CONSUME_H
SPELL_CONSUME_BUFF
SPELL_CONSUME_BUFF_H
SPELL_SUMMON_INVADER_1
SPELL_SUMMON_INVADER_2
SPELL_INVADER_TAUNT
MAX_CONSOME_STACKS
Definition at line 27 of file boss_trollgore.cpp.
Function Documentation
AddSC_boss_trollgore()
void AddSC_boss_trollgore ()
Definition at line 237 of file boss_trollgore.cpp.
References Script::GetAI, GetAI_boss_trollgore(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_trollgore()
UnitAI* GetAI_boss_trollgore (Creature * pCreature)
Definition at line 232 of file boss_trollgore.cpp.
Referenced by AddSC_boss_trollgore().