CMaNGOS_WoTLK: boss_noxxion.cpp File Reference
boss_noxxion.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_noxxionAI
Enumerations
enum { SPELL_TOXICVOLLEY = 21687 , SPELL_UPPERCUT = 22916 , SPELL_NOXXION_SPAWNS_AURA = 21708 , SPELL_NOXXION_SPAWNS_SUMMON = 21707 }
Functions
UnitAI * GetAI_boss_noxxion (Creature *pCreature)
bool EffectAuraDummy_spell_aura_dummy_noxxion_spawns (const Aura *pAura, bool bApply)
void AddSC_boss_noxxion ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_TOXICVOLLEY
SPELL_UPPERCUT
SPELL_NOXXION_SPAWNS_AURA
SPELL_NOXXION_SPAWNS_SUMMON
Definition at line 27 of file boss_noxxion.cpp.
Function Documentation
AddSC_boss_noxxion()
void AddSC_boss_noxxion ()
Definition at line 112 of file boss_noxxion.cpp.
References EffectAuraDummy_spell_aura_dummy_noxxion_spawns(), Script::GetAI, GetAI_boss_noxxion(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_noxxion_spawns()
bool EffectAuraDummy_spell_aura_dummy_noxxion_spawns (const Aura * pAura, bool bApply)
Definition at line 94 of file boss_noxxion.cpp.
References EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), SPELL_NOXXION_SPAWNS_AURA, SPELL_NOXXION_SPAWNS_SUMMON, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by AddSC_boss_noxxion().
GetAI_boss_noxxion()
UnitAI* GetAI_boss_noxxion (Creature * pCreature)
Definition at line 89 of file boss_noxxion.cpp.
Referenced by AddSC_boss_noxxion().