CMaNGOS_WoTLK: boss_vaelastrasz.cpp File Reference
boss_vaelastrasz.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackwing_lair.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_vaelastraszAI
Enumerations
enum {
SAY_LINE_1 = -1469026 , SAY_LINE_2 = -1469027 , SAY_LINE_3 = -1469028 , SAY_HALFLIFE = -1469029 ,
SAY_KILLTARGET = -1469030 , SAY_NEFARIUS_CORRUPT_1 = -1469006 , SAY_NEFARIUS_CORRUPT_2 = -1469032 , SAY_TECHNICIAN_RUN = -1469034 ,
NPC_BLACKWING_TECHNICIAN = 13996 , SPELL_ESSENCE_OF_THE_RED = 23513 , SPELL_FLAME_BREATH = 23461 , SPELL_FIRE_NOVA = 23462 ,
SPELL_TAIL_SWEEP = 15847 , SPELL_BURNING_ADRENALINE_TANK = 18173 , SPELL_BURNING_ADRENALINE = 23620 , SPELL_CLEAVE = 19983 ,
SPELL_NEFARIUS_CORRUPTION = 23642 , SPELL_RED_LIGHTNING = 19484 , GOSSIP_ITEM_VAEL_1 = -3469003 , GOSSIP_ITEM_VAEL_2 = -3469004 ,
GOSSIP_TEXT_VAEL_1 = 7156 , GOSSIP_TEXT_VAEL_2 = 7256 , FACTION_HOSTILE = 14 , AREATRIGGER_VAEL_INTRO = 3626 ,
QUEST_NEFARIUS_CORRUPTION = 8730
}
enum VaelaastraszActions {
VAEL_LOW_HP_YELL , VAEL_BURNING_ADRENALINE_TANK , VAEL_BURNING_ADRENALINE_TARGET , VAEL_FLAME_BREATH ,
VAEL_FIRE_NOVA , VAEL_CLEAVE , VAEL_TAIL_SWEEP , VAEL_ACTION_MAX ,
VAEL_INTRO , VAEL_SPEECH
}
Functions
bool GossipSelect_boss_vaelastrasz (Player *pPlayer, Creature *creature, uint32, uint32 uiAction)
bool GossipHello_boss_vaelastrasz (Player *pPlayer, Creature *creature)
bool QuestAccept_boss_vaelastrasz (Player *pPlayer, Creature *, const Quest *pQuest)
bool AreaTrigger_at_vaelastrasz (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_boss_vaelastrasz ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_LINE_1
SAY_LINE_2
SAY_LINE_3
SAY_HALFLIFE
SAY_KILLTARGET
SAY_NEFARIUS_CORRUPT_1
SAY_NEFARIUS_CORRUPT_2
SAY_TECHNICIAN_RUN
NPC_BLACKWING_TECHNICIAN
SPELL_ESSENCE_OF_THE_RED
SPELL_FLAME_BREATH
SPELL_FIRE_NOVA
SPELL_TAIL_SWEEP
SPELL_BURNING_ADRENALINE_TANK
SPELL_BURNING_ADRENALINE
SPELL_CLEAVE
SPELL_NEFARIUS_CORRUPTION
SPELL_RED_LIGHTNING
GOSSIP_ITEM_VAEL_1
GOSSIP_ITEM_VAEL_2
GOSSIP_TEXT_VAEL_1
GOSSIP_TEXT_VAEL_2
FACTION_HOSTILE
AREATRIGGER_VAEL_INTRO
QUEST_NEFARIUS_CORRUPTION
Definition at line 28 of file boss_vaelastrasz.cpp.
VaelaastraszActions
enum VaelaastraszActions
Enumerator
VAEL_LOW_HP_YELL
VAEL_BURNING_ADRENALINE_TANK
VAEL_BURNING_ADRENALINE_TARGET
VAEL_FLAME_BREATH
VAEL_FIRE_NOVA
VAEL_CLEAVE
VAEL_TAIL_SWEEP
VAEL_ACTION_MAX
VAEL_INTRO
VAEL_SPEECH
Definition at line 65 of file boss_vaelastrasz.cpp.
Function Documentation
AddSC_boss_vaelastrasz()
void AddSC_boss_vaelastrasz ()
Definition at line 390 of file boss_vaelastrasz.cpp.
References AreaTrigger_at_vaelastrasz(), Script::GetAI, GossipHello_boss_vaelastrasz(), GossipSelect_boss_vaelastrasz(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_boss_vaelastrasz(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_vaelastrasz()
bool AreaTrigger_at_vaelastrasz (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 368 of file boss_vaelastrasz.cpp.
References AREATRIGGER_VAEL_INTRO, WorldObject::GetInstanceData(), AreaTriggerEntry::id, Unit::IsDead(), Player::IsGameMaster(), NOT_STARTED, NPC_VAELASTRASZ, and TYPE_VAELASTRASZ.
Referenced by AddSC_boss_vaelastrasz().
GossipHello_boss_vaelastrasz()
bool GossipHello_boss_vaelastrasz (Player * pPlayer, Creature * creature)
Definition at line 346 of file boss_vaelastrasz.cpp.
References Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_VAEL_1, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_VAEL_1, Unit::isQuestGiver(), and Player::PrepareQuestMenu().
Referenced by AddSC_boss_vaelastrasz().
GossipSelect_boss_vaelastrasz()
bool GossipSelect_boss_vaelastrasz (Player * pPlayer, Creature * creature, uint32 , uint32 uiAction)
Definition at line 328 of file boss_vaelastrasz.cpp.
References Creature::AI(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_VAEL_2, GOSSIP_SENDER_MAIN, and GOSSIP_TEXT_VAEL_2.
Referenced by AddSC_boss_vaelastrasz().
QuestAccept_boss_vaelastrasz()
bool QuestAccept_boss_vaelastrasz (Player * pPlayer, Creature * , const Quest * pQuest)
Definition at line 357 of file boss_vaelastrasz.cpp.
References WorldObject::GetInstanceData(), Quest::GetQuestId(), IN_PROGRESS, QUEST_NEFARIUS_CORRUPTION, and TYPE_QUEST_SCEPTER.
Referenced by AddSC_boss_vaelastrasz().