CMaNGOS_WoTLK: boss_doomwalker.cpp File Reference
boss_doomwalker.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_doomwalkerAI
Enumerations
enum {
NPC_DREADLORD = 21166 , NPC_ILLIDARI_RAVAGER = 22857 , NPC_SHADOWHOOF_ASSASSIN = 22858 , NPC_SHADOWHOOF_SUMMONER = 22859 ,
NPC_ILLIDARI_SUCCUBUS = 22860 , SAY_AGGRO = -1000159 , SAY_EARTHQUAKE_1 = -1000160 , SAY_EARTHQUAKE_2 = -1000161 ,
SAY_OVERRUN_1 = -1000162 , SAY_OVERRUN_2 = -1000163 , SAY_SLAY_1 = -1000164 , SAY_SLAY_2 = -1000165 ,
SAY_SLAY_3 = -1000166 , SAY_DEATH = -1000167 , EMOTE_FRENZY = -1000002 , SPELL_EARTHQUAKE = 32686 ,
SPELL_CRUSH_ARMOR = 33661 , SPELL_LIGHTNING_WRATH = 33665 , SPELL_OVERRUN = 32636 , SPELL_OVERRUN_TRIGGER_SPAWN = 32632 ,
SPELL_OVERRUN_DAMAGE = 32637 , SPELL_ENRAGE = 33653 , SPELL_MARK_OF_DEATH_PLAYER = 37128 , SPELL_MARK_OF_DEATH_AURA = 37125 ,
SPELL_EARTHQUAKE_VISUAL = 41966 , COUNT_OVERRUN = 5 , POINT_OVERRUN = 1
}
Functions
UnitAI * GetAI_boss_doomwalker (Creature *pCreature)
void AddSC_boss_doomwalker ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_DREADLORD
NPC_ILLIDARI_RAVAGER
NPC_SHADOWHOOF_ASSASSIN
NPC_SHADOWHOOF_SUMMONER
NPC_ILLIDARI_SUCCUBUS
SAY_AGGRO
SAY_EARTHQUAKE_1
SAY_EARTHQUAKE_2
SAY_OVERRUN_1
SAY_OVERRUN_2
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
EMOTE_FRENZY
SPELL_EARTHQUAKE
SPELL_CRUSH_ARMOR
SPELL_LIGHTNING_WRATH
SPELL_OVERRUN
SPELL_OVERRUN_TRIGGER_SPAWN
SPELL_OVERRUN_DAMAGE
SPELL_ENRAGE
SPELL_MARK_OF_DEATH_PLAYER
SPELL_MARK_OF_DEATH_AURA
SPELL_EARTHQUAKE_VISUAL
COUNT_OVERRUN
POINT_OVERRUN
Definition at line 26 of file boss_doomwalker.cpp.
Function Documentation
AddSC_boss_doomwalker()
void AddSC_boss_doomwalker ()
Definition at line 264 of file boss_doomwalker.cpp.
References Script::GetAI, GetAI_boss_doomwalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_doomwalker()
UnitAI* GetAI_boss_doomwalker (Creature * pCreature)
Definition at line 259 of file boss_doomwalker.cpp.
Referenced by AddSC_boss_doomwalker().