CMaNGOS_WoTLK: boss_herod.cpp File Reference
boss_herod.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct boss_herodAI
struct mob_scarlet_traineeAI
Enumerations
enum {
SAY_AGGRO = -1189000 , SAY_WHIRLWIND = -1189001 , SAY_ENRAGE = -1189002 , SAY_KILL = -1189003 ,
EMOTE_GENERIC_ENRAGED = -1000003 , SAY_TRAINEE_SPAWN = -1189035 , SPELL_RUSHINGCHARGE = 8260 , SPELL_CLEAVE = 15496 ,
SPELL_WHIRLWIND = 8989 , SPELL_FRENZY = 8269 , NPC_SCARLET_TRAINEE = 6575
}
Functions
UnitAI * GetAI_boss_herod (Creature *pCreature)
UnitAI * GetAI_mob_scarlet_trainee (Creature *pCreature)
void AddSC_boss_herod ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_WHIRLWIND
SAY_ENRAGE
SAY_KILL
EMOTE_GENERIC_ENRAGED
SAY_TRAINEE_SPAWN
SPELL_RUSHINGCHARGE
SPELL_CLEAVE
SPELL_WHIRLWIND
SPELL_FRENZY
NPC_SCARLET_TRAINEE
Definition at line 27 of file boss_herod.cpp.
Function Documentation
AddSC_boss_herod()
void AddSC_boss_herod ()
Definition at line 174 of file boss_herod.cpp.
References Script::GetAI, GetAI_boss_herod(), GetAI_mob_scarlet_trainee(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_herod()
UnitAI* GetAI_boss_herod (Creature * pCreature)
Definition at line 131 of file boss_herod.cpp.
Referenced by AddSC_boss_herod().
GetAI_mob_scarlet_trainee()
UnitAI* GetAI_mob_scarlet_trainee (Creature * pCreature)
Definition at line 169 of file boss_herod.cpp.
Referenced by AddSC_boss_herod().