CMaNGOS_WoTLK: boss_nightbane.cpp File Reference
boss_nightbane.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "karazhan.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "MotionGenerators/WaypointManager.h"
#include <G3D/Vector3.h>
Data Structures
struct boss_nightbaneAI
Enumerations
enum {
EMOTE_AWAKEN = -1532125 , SAY_AGGRO = -1532126 , SAY_AIR_PHASE = -1532127 , SAY_LAND_PHASE_1 = -1532128 ,
SAY_LAND_PHASE_2 = -1532129 , EMOTE_DEEP_BREATH = -1532130 , SPELL_BELLOWING_ROAR = 36922 , SPELL_CHARRED_EARTH = 30129 ,
SPELL_CHARRED_EARTH_TARGETING = 30209 , SPELL_SMOLDERING_BREATH = 30210 , SPELL_TAIL_SWEEP = 25653 , SPELL_CLEAVE = 30131 ,
SPELL_DISTRACTING_ASH_GROUND = 30280 , SPELL_DISTRACTING_ASH = 30130 , SPELL_RAIN_OF_BONES = 37098 , SPELL_SMOKING_BLAST = 37057 ,
SPELL_FIREBALL_BARRAGE = 30282 , PHASE_GROUND = 1 , PHASE_AIR = 2 , PHASE_TRANSITION = 3 ,
POINT_ID_AIR = 1 , POINT_ID_GROUND = 2 , POINT_INTRO_END = 11 , POINT_LANDING_END = 6
}
enum NightbaneActions {
NIGHTBANE_PHASE_RESET , NIGHTBANE_PHASE_2 , NIGHTBANE_BELLOWING_ROAR , NIGHTBANE_CHARRED_EARTH ,
NIGHTBANE_SMOLDERING_BREATH , NIGHTBANE_TAIL_SWEEP , NIGHTBANE_CLEAVE , NIGHTBANE_DISTRACTING_ASH ,
NIGHTBANE_RAIN_OF_BONES , NIGHTBANE_SMOKING_BLAST , NIGHTBANE_FIREBALL_BARRAGE , NIGHTBANE_ACTION_MAX ,
NIGHTBANE_ATTACK_DELAY
}
Functions
bool ProcessEventId_event_spell_summon_nightbane (uint32, Object *source, Object *, bool bIsStart)
void AddSC_boss_nightbane ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_AWAKEN
SAY_AGGRO
SAY_AIR_PHASE
SAY_LAND_PHASE_1
SAY_LAND_PHASE_2
EMOTE_DEEP_BREATH
SPELL_BELLOWING_ROAR
SPELL_CHARRED_EARTH
SPELL_CHARRED_EARTH_TARGETING
SPELL_SMOLDERING_BREATH
SPELL_TAIL_SWEEP
SPELL_CLEAVE
SPELL_DISTRACTING_ASH_GROUND
SPELL_DISTRACTING_ASH
SPELL_RAIN_OF_BONES
SPELL_SMOKING_BLAST
SPELL_FIREBALL_BARRAGE
PHASE_GROUND
PHASE_AIR
PHASE_TRANSITION
POINT_ID_AIR
POINT_ID_GROUND
POINT_INTRO_END
POINT_LANDING_END
Definition at line 30 of file boss_nightbane.cpp.
NightbaneActions
enum NightbaneActions
Enumerator
NIGHTBANE_PHASE_RESET
NIGHTBANE_PHASE_2
NIGHTBANE_BELLOWING_ROAR
NIGHTBANE_CHARRED_EARTH
NIGHTBANE_SMOLDERING_BREATH
NIGHTBANE_TAIL_SWEEP
NIGHTBANE_CLEAVE
NIGHTBANE_DISTRACTING_ASH
NIGHTBANE_RAIN_OF_BONES
NIGHTBANE_SMOKING_BLAST
NIGHTBANE_FIREBALL_BARRAGE
NIGHTBANE_ACTION_MAX
NIGHTBANE_ATTACK_DELAY
Definition at line 66 of file boss_nightbane.cpp.
Function Documentation
AddSC_boss_nightbane()
void AddSC_boss_nightbane ()
Definition at line 470 of file boss_nightbane.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_summon_nightbane(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_spell_summon_nightbane()
bool ProcessEventId_event_spell_summon_nightbane (uint32 , Object * source, Object * , bool bIsStart)
Definition at line 436 of file boss_nightbane.cpp.
References Creature::AI(), DoScriptText(), EMOTE_AWAKEN, FAIL, InstanceData::GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), Object::GetTypeId(), IN_PROGRESS, Unit::IsAlive(), NOT_STARTED, NPC_NIGHTBANE, Object::RemoveByteFlag(), Object::RemoveFlag(), Object::SetByteValue(), InstanceData::SetData(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetStandState(), TYPE_NIGHTBANE, TYPEID_PLAYER, UNIT_BYTE1_FLAG_ALWAYS_STAND, UNIT_BYTE1_FLAG_FLY_ANIM, UNIT_BYTES_1_OFFSET_MISC_FLAGS, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_boss_nightbane().