CMaNGOS_WoTLK: boss_dalliah.cpp File Reference
boss_dalliah.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "arcatraz.h"
Data Structures
struct boss_dalliahAI
Enumerations
enum {
SAY_AGGRO = -1552031 , SAY_SOCCOTHRATES_TAUNT_1 = -1552040 , SAY_SOCCOTHRATES_TAUNT_2 = -1552041 , SAY_SOCCOTHRATES_TAUNT_3 = -1552042 ,
SAY_HEAL_1 = -1552032 , SAY_HEAL_2 = -1552033 , SAY_KILL_1 = -1552034 , SAY_KILL_2 = -1552035 ,
SAY_WHIRLWIND_1 = -1552036 , SAY_WHIRLWIND_2 = -1552037 , SAY_DEATH = -1552038 , SPELL_DOUBLE_ATTACK = 19818 ,
SPELL_GIFT_DOOMSAYER = 36173 , SPELL_GIFT_DOOMSAYER_H = 39009 , SPELL_HEAL = 36144 , SPELL_HEAL_H = 39013 ,
SPELL_WHIRLWIND = 36142 , SPELL_SHADOW_WAVE = 39016
}
Functions
UnitAI * GetAI_boss_dalliah (Creature *pCreature)
void AddSC_boss_dalliah ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SOCCOTHRATES_TAUNT_1
SAY_SOCCOTHRATES_TAUNT_2
SAY_SOCCOTHRATES_TAUNT_3
SAY_HEAL_1
SAY_HEAL_2
SAY_KILL_1
SAY_KILL_2
SAY_WHIRLWIND_1
SAY_WHIRLWIND_2
SAY_DEATH
SPELL_DOUBLE_ATTACK
SPELL_GIFT_DOOMSAYER
SPELL_GIFT_DOOMSAYER_H
SPELL_HEAL
SPELL_HEAL_H
SPELL_WHIRLWIND
SPELL_SHADOW_WAVE
Definition at line 27 of file boss_dalliah.cpp.
Function Documentation
AddSC_boss_dalliah()
void AddSC_boss_dalliah ()
Definition at line 211 of file boss_dalliah.cpp.
References Script::GetAI, GetAI_boss_dalliah(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_dalliah()
UnitAI* GetAI_boss_dalliah (Creature * pCreature)
Definition at line 206 of file boss_dalliah.cpp.
Referenced by AddSC_boss_dalliah().