CMaNGOS_WoTLK: boss_warlord_kalithresh.cpp File Reference
boss_warlord_kalithresh.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "steam_vault.h"
Data Structures
struct boss_warlord_kalithreshAI
struct mob_naga_distillerAI
Enumerations
enum {
SAY_INTRO = -1545016 , SAY_REGEN = -1545017 , SAY_AGGRO1 = -1545018 , SAY_AGGRO2 = -1545019 ,
SAY_AGGRO3 = -1545020 , SAY_SLAY1 = -1545021 , SAY_SLAY2 = -1545022 , SAY_DEATH = -1545023 ,
SPELL_SPELL_REFLECTION = 31534 , SPELL_IMPALE = 39061 , SPELL_WARLORDS_RAGE = 37081 , SPELL_WARLORDS_RAGE_NAGA = 31543 ,
SPELL_HEAD_CRACK = 16172 , POINT_MOVE_DISTILLER = 1
}
enum WarlordKalithreshActions {
WARLORD_KALITHRESH_ACTION_WARLORDS_RAGE , WARLORD_KALITHRESH_ACTION_REFLECTION , WARLORD_KALITHRESH_ACTION_IMPALE , WARLORD_KALITHRESH_ACTION_HEAD_CRACK ,
WARLORD_KALITHRESH_ACTION_MAX
}
Functions
UnitAI * GetAI_boss_warlord_kalithresh (Creature *pCreature)
UnitAI * GetAI_mob_naga_distiller (Creature *pCreature)
void AddSC_boss_warlord_kalithresh ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_REGEN
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SPELL_SPELL_REFLECTION
SPELL_IMPALE
SPELL_WARLORDS_RAGE
SPELL_WARLORDS_RAGE_NAGA
SPELL_HEAD_CRACK
POINT_MOVE_DISTILLER
Definition at line 28 of file boss_warlord_kalithresh.cpp.
WarlordKalithreshActions
enum WarlordKalithreshActions
Enumerator
WARLORD_KALITHRESH_ACTION_WARLORDS_RAGE
WARLORD_KALITHRESH_ACTION_REFLECTION
WARLORD_KALITHRESH_ACTION_IMPALE
WARLORD_KALITHRESH_ACTION_HEAD_CRACK
WARLORD_KALITHRESH_ACTION_MAX
Definition at line 48 of file boss_warlord_kalithresh.cpp.
Function Documentation
AddSC_boss_warlord_kalithresh()
void AddSC_boss_warlord_kalithresh ()
Definition at line 289 of file boss_warlord_kalithresh.cpp.
References Script::GetAI, GetAI_boss_warlord_kalithresh(), GetAI_mob_naga_distiller(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_warlord_kalithresh()
UnitAI* GetAI_boss_warlord_kalithresh (Creature * pCreature)
Definition at line 279 of file boss_warlord_kalithresh.cpp.
Referenced by AddSC_boss_warlord_kalithresh().
GetAI_mob_naga_distiller()
UnitAI* GetAI_mob_naga_distiller (Creature * pCreature)
Definition at line 284 of file boss_warlord_kalithresh.cpp.
Referenced by AddSC_boss_warlord_kalithresh().