CMaNGOS_WoTLK: boss_order_of_silver_hand.cpp File Reference
boss_order_of_silver_hand.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "stratholme.h"
Data Structures
struct SilverHandAbilityStruct
struct boss_silver_hand_bossesAI
Enumerations
enum {
SPELL_HAMMER_JUSTICE = 13005 , SPELL_HAMMER_WRATH = 32772 , SPELL_HOLY_SHOCK = 32771 , SPELL_HOLY_SHIELD = 32777 ,
SPELL_REDOUBT = 32776 , AELMAR_SPELL_JUDGEMENT = 32778 , SPELL_BLESSING_SD = 32770 , SPELL_HOLY_LIGHT = 32769 ,
TARGET_TYPE_RANDOM = 0 , TARGET_TYPE_VICTIM = 1 , TARGET_TYPE_SELF = 2 , TARGET_TYPE_FRIENDLY = 3
}
Functions
UnitAI * GetAI_boss_silver_hand_bossesAI (Creature *pCreature)
void AddSC_boss_order_of_silver_hand ()
Variables
static SilverHandAbilityStruct m_aSilverHandAbility [8]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_HAMMER_JUSTICE
SPELL_HAMMER_WRATH
SPELL_HOLY_SHOCK
SPELL_HOLY_SHIELD
SPELL_REDOUBT
AELMAR_SPELL_JUDGEMENT
SPELL_BLESSING_SD
SPELL_HOLY_LIGHT
TARGET_TYPE_RANDOM
TARGET_TYPE_VICTIM
TARGET_TYPE_SELF
TARGET_TYPE_FRIENDLY
Definition at line 34 of file boss_order_of_silver_hand.cpp.
Function Documentation
AddSC_boss_order_of_silver_hand()
void AddSC_boss_order_of_silver_hand ()
Definition at line 173 of file boss_order_of_silver_hand.cpp.
References Script::GetAI, GetAI_boss_silver_hand_bossesAI(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_silver_hand_bossesAI()
UnitAI* GetAI_boss_silver_hand_bossesAI (Creature * pCreature)
Definition at line 168 of file boss_order_of_silver_hand.cpp.
Referenced by AddSC_boss_order_of_silver_hand().
Variable Documentation
m_aSilverHandAbility
SilverHandAbilityStruct m_aSilverHandAbility[8] static
Initial value:
=
{
    {NPC_GREGOR_THE_JUSTICIAR,  SPELL_HAMMER_JUSTICE,   TARGET_TYPE_RANDOM,     2000,  15000},
    {NPC_GREGOR_THE_JUSTICIAR,  SPELL_HAMMER_WRATH,     TARGET_TYPE_RANDOM,     10000, 15000},
    {NPC_GREGOR_THE_JUSTICIAR,  SPELL_HOLY_SHOCK,       TARGET_TYPE_RANDOM,     4000,  7000},
    {NPC_CATHELA_THE_SEEKER,    SPELL_HOLY_SHIELD,      TARGET_TYPE_SELF,       1000,  60000},
    {NPC_CATHELA_THE_SEEKER,    SPELL_REDOUBT,          TARGET_TYPE_SELF,       5000,  15000},
    {NPC_AELMAR_THE_VANQUISHER, AELMAR_SPELL_JUDGEMENT, TARGET_TYPE_VICTIM,     4000,  9000},
    {NPC_VICAR_HYERONIMUS,      SPELL_BLESSING_SD,      TARGET_TYPE_FRIENDLY,   2000,  13000},
    {NPC_VICAR_HYERONIMUS,      SPELL_HOLY_LIGHT,       TARGET_TYPE_FRIENDLY,   5000,  9000},
}
Definition at line 62 of file boss_order_of_silver_hand.cpp.
Referenced by boss_silver_hand_bossesAI::boss_silver_hand_bossesAI(), boss_silver_hand_bossesAI::CanUseSpecialAbility(), boss_silver_hand_bossesAI::Reset(), and boss_silver_hand_bossesAI::UpdateAI().