CMaNGOS_WoTLK: boss_flame_leviathan.cpp File Reference
boss_flame_leviathan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_flame_leviathanAI
struct npc_hodir_fury_reticleAI
struct npc_hodir_furyAI
struct npc_freya_wardAI
struct npc_mimiron_infernoAI
Enumerations
enum {
SAY_AGGRO = -1603159 , SAY_SLAY = -1603160 , SAY_DEATH = -1603161 , SAY_CHANGE_1 = -1603162 ,
SAY_CHANGE_2 = -1603163 , SAY_CHANGE_3 = -1603164 , SAY_PLAYER_RIDE = -1603165 , SAY_OVERLOAD_1 = -1603166 ,
SAY_OVERLOAD_2 = -1603167 , SAY_OVERLOAD_3 = -1603168 , SAY_HARD_MODE = -1603169 , SAY_TOWER_FROST = -1603170 ,
SAY_TOWER_FIRE = -1603171 , SAY_TOWER_ENERGY = -1603172 , SAY_TOWER_NATURE = -1603173 , SAY_TOWER_DOWN = -1603174 ,
EMOTE_PURSUE = -1603175 , EMOTE_HODIR_FURY = -1603242 , EMOTE_FREYA_WARD = -1603243 , EMOTE_MIMIRON_INFERNO = -1603244 ,
EMOTE_THORIM_HAMMER = -1603245 , SPELL_INVISIBILITY_DETECTION = 18950 , SPELL_PURSUED = 62374 , SPELL_MISSILE_BARRAGE_TARGET = 62401 ,
SPELL_MISSILE_BARRAGE = 62400 , SPELL_FLAME_VENTS = 62396 , SPELL_BATTERING_RAM = 62376 , SPELL_GATHERING_SPEED = 62375 ,
SPELL_OVERLOAD_CIRCUIT = 62399 , SPELL_SEARING_FLAME = 62402 , SPELL_SYSTEMS_SHUTDOWN = 62475 , SPELL_TOWER_OF_FROST = 65077 ,
SPELL_TOWER_OF_LIFE = 64482 , SPELL_TOWER_OF_STORMS = 65076 , SPELL_TOWER_OF_FLAMES = 65075 , SPELL_HODIR_FURY = 62533 ,
SPELL_FREYA_WARD = 62906 , SPELL_THORIM_HAMMER = 62911 , SPELL_MIMIRON_INFERNO = 62909 , SPELL_LIGHTNING_SKYBEAM = 62897 ,
SPELL_RED_SKYBEAM = 63772 , SPELL_BLUE_SKYBEAM = 63769 , SPELL_GREEN_SKYBEAM = 62895 , NPC_HODIR_FURY = 33212 ,
NPC_THORIM_HAMMER_VEHICLE = 33364 , NPC_MIMIRON_INFERNO_VEHICLE = 33369 , NPC_HODIR_FURY_VEHICLE = 33108 , NPC_FREYA_WARD_VEHICLE = 33366 ,
NPC_WRITHING_LASHER = 33387 , NPC_WARD_OF_LIFE = 34275 , SPELL_RIDE_VEHICLE = 43671 , NPC_BRANN_FLYING_MACHINE = 34120 ,
NPC_BRANN_BRONZEBEARD_LEVIATHAN = 34119 , NPC_ARCHMANGE_RHYDIAN = 33696 , MAX_FREYA_WARD = 4 , MAX_HODIR_FURY = 2 ,
MAX_THORIM_HAMMER = 22 , TOWER_ID_HODIR = 0 , TOWER_ID_FREYA = 1 , TOWER_ID_MIMIRON = 2 ,
TOWER_ID_THORIM = 3
}
Functions
UnitAI * GetAI_boss_flame_leviathan (Creature *pCreature)
UnitAI * GetAI_npc_hodir_fury_reticle (Creature *pCreature)
UnitAI * GetAI_npc_hodir_fury (Creature *pCreature)
UnitAI * GetAI_npc_freya_ward (Creature *pCreature)
UnitAI * GetAI_npc_mimiron_inferno (Creature *pCreature)
void AddSC_boss_flame_leviathan ()
Variables
static const int32 aLeviathanTowerYell [KEEPER_ENCOUNTER] = { SAY_TOWER_FROST, SAY_TOWER_NATURE, SAY_TOWER_FIRE, SAY_TOWER_ENERGY }
static const int32 aLeviathanTowerEmote [KEEPER_ENCOUNTER] = { EMOTE_HODIR_FURY, EMOTE_FREYA_WARD, EMOTE_MIMIRON_INFERNO, EMOTE_THORIM_HAMMER }
static const float afFreyaWard [MAX_FREYA_WARD][4]
static const float afHodirFury [MAX_HODIR_FURY][3]
static const float afMimironInferno [3] = {329.1809f, 8.02577f, 409.887f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY
SAY_DEATH
SAY_CHANGE_1
SAY_CHANGE_2
SAY_CHANGE_3
SAY_PLAYER_RIDE
SAY_OVERLOAD_1
SAY_OVERLOAD_2
SAY_OVERLOAD_3
SAY_HARD_MODE
SAY_TOWER_FROST
SAY_TOWER_FIRE
SAY_TOWER_ENERGY
SAY_TOWER_NATURE
SAY_TOWER_DOWN
EMOTE_PURSUE
EMOTE_HODIR_FURY
EMOTE_FREYA_WARD
EMOTE_MIMIRON_INFERNO
EMOTE_THORIM_HAMMER
SPELL_INVISIBILITY_DETECTION
SPELL_PURSUED
SPELL_MISSILE_BARRAGE_TARGET
SPELL_MISSILE_BARRAGE
SPELL_FLAME_VENTS
SPELL_BATTERING_RAM
SPELL_GATHERING_SPEED
SPELL_OVERLOAD_CIRCUIT
SPELL_SEARING_FLAME
SPELL_SYSTEMS_SHUTDOWN
SPELL_TOWER_OF_FROST
SPELL_TOWER_OF_LIFE
SPELL_TOWER_OF_STORMS
SPELL_TOWER_OF_FLAMES
SPELL_HODIR_FURY
SPELL_FREYA_WARD
SPELL_THORIM_HAMMER
SPELL_MIMIRON_INFERNO
SPELL_LIGHTNING_SKYBEAM
SPELL_RED_SKYBEAM
SPELL_BLUE_SKYBEAM
SPELL_GREEN_SKYBEAM
NPC_HODIR_FURY
NPC_THORIM_HAMMER_VEHICLE
NPC_MIMIRON_INFERNO_VEHICLE
NPC_HODIR_FURY_VEHICLE
NPC_FREYA_WARD_VEHICLE
NPC_WRITHING_LASHER
NPC_WARD_OF_LIFE
SPELL_RIDE_VEHICLE
NPC_BRANN_FLYING_MACHINE
NPC_BRANN_BRONZEBEARD_LEVIATHAN
NPC_ARCHMANGE_RHYDIAN
MAX_FREYA_WARD
MAX_HODIR_FURY
MAX_THORIM_HAMMER
TOWER_ID_HODIR
TOWER_ID_FREYA
TOWER_ID_MIMIRON
TOWER_ID_THORIM
Definition at line 27 of file boss_flame_leviathan.cpp.
Function Documentation
AddSC_boss_flame_leviathan()
void AddSC_boss_flame_leviathan ()
Definition at line 731 of file boss_flame_leviathan.cpp.
References Script::GetAI, GetAI_boss_flame_leviathan(), GetAI_npc_freya_ward(), GetAI_npc_hodir_fury(), GetAI_npc_hodir_fury_reticle(), GetAI_npc_mimiron_inferno(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_flame_leviathan()
UnitAI* GetAI_boss_flame_leviathan (Creature * pCreature)
Definition at line 557 of file boss_flame_leviathan.cpp.
Referenced by AddSC_boss_flame_leviathan().
GetAI_npc_freya_ward()
UnitAI* GetAI_npc_freya_ward (Creature * pCreature)
Definition at line 690 of file boss_flame_leviathan.cpp.
Referenced by AddSC_boss_flame_leviathan().
GetAI_npc_hodir_fury()
UnitAI* GetAI_npc_hodir_fury (Creature * pCreature)
Definition at line 648 of file boss_flame_leviathan.cpp.
Referenced by AddSC_boss_flame_leviathan().
GetAI_npc_hodir_fury_reticle()
UnitAI* GetAI_npc_hodir_fury_reticle (Creature * pCreature)
Definition at line 628 of file boss_flame_leviathan.cpp.
Referenced by AddSC_boss_flame_leviathan().
GetAI_npc_mimiron_inferno()
UnitAI* GetAI_npc_mimiron_inferno (Creature * pCreature)
Definition at line 726 of file boss_flame_leviathan.cpp.
Referenced by AddSC_boss_flame_leviathan().
Variable Documentation
afFreyaWard
const float afFreyaWard[MAX_FREYA_WARD][4] static
Initial value:
=
{
    {156.9291f, 61.52306f, 409.887f, 5.68f},
    {376.641f, 68.61361f, 411.2287f, 3.85f},
    {383.6206f, -130.8576f, 410.7088f, 2.26f},
    {154.9095f, -137.4339f, 409.887f, 0.79f},
}
Definition at line 147 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI::DoSpawnFreyaWard().
afHodirFury
const float afHodirFury[MAX_HODIR_FURY][3] static
Initial value:
=
{
    {219.9013f, 7.913357f, 409.7861f},
    {326.0777f, -74.99034f, 409.887f},
}
Definition at line 155 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI::DoSpawnHodirFury().
afMimironInferno
const float afMimironInferno[3] = {329.1809f, 8.02577f, 409.887f} static
Definition at line 161 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI::DoSpawnMimironInferno().
aLeviathanTowerEmote
const int32 aLeviathanTowerEmote[KEEPER_ENCOUNTER] = { EMOTE_HODIR_FURY, EMOTE_FREYA_WARD, EMOTE_MIMIRON_INFERNO, EMOTE_THORIM_HAMMER } static
Definition at line 145 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI::UpdateAI().
aLeviathanTowerYell
const int32 aLeviathanTowerYell[KEEPER_ENCOUNTER] = { SAY_TOWER_FROST, SAY_TOWER_NATURE, SAY_TOWER_FIRE, SAY_TOWER_ENERGY } static
Definition at line 144 of file boss_flame_leviathan.cpp.
Referenced by boss_flame_leviathanAI::UpdateAI().