CMaNGOS_WoTLK: boss_warp_splinter.cpp File Reference
boss_warp_splinter.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_warp_splinterAI
struct npc_saplingAI
Enumerations
enum {
SAY_AGGRO = -1553007 , SAY_SLAY_1 = -1553008 , SAY_SLAY_2 = -1553009 , SAY_SUMMON_1 = -1553010 ,
SAY_SUMMON_2 = -1553011 , SAY_DEATH = -1553012 , SPELL_WAR_STOMP = 34716 , SPELL_SUMMON_SAPLINGS = 34741 ,
SPELL_ARCANE_VOLLEY = 36705 , SPELL_ARCANE_VOLLEY_H = 39133 , SPELL_ANCESTRAL_LIFE = 34742 , SPELL_MOONFIRE_VISUAL = 36704 ,
NPC_SAPLING = 19949
}
Functions
UnitAI * GetAI_boss_warp_splinter (Creature *pCreature)
UnitAI * GetAI_npc_sapling (Creature *pCreature)
void AddSC_boss_warp_splinter ()
Variables
static const uint32 saplingsSummonSpells [6] = { 34727, 34731, 34733, 34734, 34736, 34739 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SUMMON_1
SAY_SUMMON_2
SAY_DEATH
SPELL_WAR_STOMP
SPELL_SUMMON_SAPLINGS
SPELL_ARCANE_VOLLEY
SPELL_ARCANE_VOLLEY_H
SPELL_ANCESTRAL_LIFE
SPELL_MOONFIRE_VISUAL
NPC_SAPLING
Definition at line 30 of file boss_warp_splinter.cpp.
Function Documentation
AddSC_boss_warp_splinter()
void AddSC_boss_warp_splinter ()
Definition at line 199 of file boss_warp_splinter.cpp.
References Script::GetAI, GetAI_boss_warp_splinter(), GetAI_npc_sapling(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_warp_splinter()
UnitAI* GetAI_boss_warp_splinter (Creature * pCreature)
Definition at line 189 of file boss_warp_splinter.cpp.
Referenced by AddSC_boss_warp_splinter().
GetAI_npc_sapling()
UnitAI* GetAI_npc_sapling (Creature * pCreature)
Definition at line 194 of file boss_warp_splinter.cpp.
Referenced by AddSC_boss_warp_splinter().
Variable Documentation
saplingsSummonSpells
const uint32 saplingsSummonSpells[6] = { 34727, 34731, 34733, 34734, 34736, 34739 } static
Definition at line 54 of file boss_warp_splinter.cpp.
Referenced by boss_warp_splinterAI::SummonTreants().