CMaNGOS_WoTLK: boss_brutallus.cpp File Reference
boss_brutallus.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sunwell_plateau.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct boss_brutallusAI
struct SpellBurnBrutallus
struct SpellBurnDamageBrutallus
struct StompBrutallus
struct DeathCloudBrutallus
struct FreezeMadrigosa
struct spell_break_ice
Enumerations
enum {
YELL_INTRO = -1580017 , YELL_INTRO_BREAK_ICE = -1580018 , YELL_INTRO_CHARGE = -1580019 , YELL_INTRO_KILL_MADRIGOSA = -1580020 ,
YELL_INTRO_TAUNT = -1580021 , YELL_MADR_ICE_BARRIER = -1580031 , YELL_MADR_INTRO = -1580032 , YELL_MADR_ICE_BLOCK = -1580033 ,
YELL_MADR_TRAP = -1580034 , YELL_MADR_DEATH = -1580035 , YELL_AGGRO = -1580022 , YELL_KILL1 = 25629 ,
YELL_KILL2 = 25630 , YELL_KILL3 = 25631 , YELL_LOVE1 = -1580026 , YELL_LOVE2 = -1580027 ,
YELL_LOVE3 = -1580028 , YELL_BERSERK = -1580029 , YELL_DEATH = -1580030 , SPELL_METEOR_SLASH = 45150 ,
SPELL_BURN = 45141 , SPELL_BURN_DAMAGE = 46394 , SPELL_STOMP = 45185 , SPELL_BERSERK = 26662 ,
SPELL_SUMMON_DEATH_CLOUD = 45884 , SPELL_DUAL_WEILD_PASSIVE = 42459 , SPELL_TAUNT_HIT_CHANCE = 45210 , SPELL_BRUTALLUS_DEATH_CLOUD = 45212 ,
SPELL_FELBLAZE_PREVIZUAL = 44885 , SPELL_SUMMON_FELBLAZE = 45069 , NPC_BRUTALLUS_DEATH_CLOUD = 25703 , SPELL_FROST_BLAST = 45203 ,
SPELL_FREEZE = 46609 , SPELL_FREEZE_USE_GO = 46610 , SPELL_FROSTBOLT = 44843 , SPELL_FROST_BREATH = 45065 ,
SPELL_ENCAPSULATE = 44883 , SPELL_FEL_FIREBALL = 44844 , SPELL_CLEAR_DEBUFFS = 34098 , SPELL_FLAME_RING = 44874 ,
SPELL_CHARGE = 44884 , SPELL_BREAK_ICE = 46637 , SPELL_ARCANE_EXPLOSION_VISUAL = 35426 , SPELL_FULL_HEAL = 17683 ,
SPELL_PERMANENT_FEIGN_DEATH = 29266 , SPELL_SELF_STUN = 45066 , POINT_MOVE_GROUND = 1 , POINT_MOVE_ICE_BLOCK = 2 ,
POINT_MOVE_ENCAPSULATE = 3 , POINT_MOVE_FEL_FIREBALL = 4
}
enum BrutallusActions {
BRUTALLUS_BERSERK , BRUTALLUS_SLASH , BRUTALLUS_STOMP , BRUTALLUS_BURN ,
BRUTALLUS_LOVE , BRUTALLUS_ACTION_MAX , BRUTALLUS_MADRIGOSA_FROSTBOLT , BRUTALLUS_MADRIGOSA_SPAWN_MOVE
}
Functions
bool AreaTrigger_at_madrigosa (Player *player, AreaTriggerEntry const *)
void AddSC_boss_brutallus ()
Variables
static const DialogueEntry aIntroDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
YELL_INTRO
YELL_INTRO_BREAK_ICE
YELL_INTRO_CHARGE
YELL_INTRO_KILL_MADRIGOSA
YELL_INTRO_TAUNT
YELL_MADR_ICE_BARRIER
YELL_MADR_INTRO
YELL_MADR_ICE_BLOCK
YELL_MADR_TRAP
YELL_MADR_DEATH
YELL_AGGRO
YELL_KILL1
YELL_KILL2
YELL_KILL3
YELL_LOVE1
YELL_LOVE2
YELL_LOVE3
YELL_BERSERK
YELL_DEATH
SPELL_METEOR_SLASH
SPELL_BURN
SPELL_BURN_DAMAGE
SPELL_STOMP
SPELL_BERSERK
SPELL_SUMMON_DEATH_CLOUD
SPELL_DUAL_WEILD_PASSIVE
SPELL_TAUNT_HIT_CHANCE
SPELL_BRUTALLUS_DEATH_CLOUD
SPELL_FELBLAZE_PREVIZUAL
SPELL_SUMMON_FELBLAZE
NPC_BRUTALLUS_DEATH_CLOUD
SPELL_FROST_BLAST
SPELL_FREEZE
SPELL_FREEZE_USE_GO
SPELL_FROSTBOLT
SPELL_FROST_BREATH
SPELL_ENCAPSULATE
SPELL_FEL_FIREBALL
SPELL_CLEAR_DEBUFFS
SPELL_FLAME_RING
SPELL_CHARGE
SPELL_BREAK_ICE
SPELL_ARCANE_EXPLOSION_VISUAL
SPELL_FULL_HEAL
SPELL_PERMANENT_FEIGN_DEATH
SPELL_SELF_STUN
POINT_MOVE_GROUND
POINT_MOVE_ICE_BLOCK
POINT_MOVE_ENCAPSULATE
POINT_MOVE_FEL_FIREBALL
Definition at line 29 of file boss_brutallus.cpp.
BrutallusActions
enum BrutallusActions
Enumerator
BRUTALLUS_BERSERK
BRUTALLUS_SLASH
BRUTALLUS_STOMP
BRUTALLUS_BURN
BRUTALLUS_LOVE
BRUTALLUS_ACTION_MAX
BRUTALLUS_MADRIGOSA_FROSTBOLT
BRUTALLUS_MADRIGOSA_SPAWN_MOVE
Definition at line 122 of file boss_brutallus.cpp.
Function Documentation
AddSC_boss_brutallus()
void AddSC_boss_brutallus ()
Definition at line 573 of file boss_brutallus.cpp.
References AreaTrigger_at_madrigosa(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_madrigosa()
bool AreaTrigger_at_madrigosa (Player * player, AreaTriggerEntry const *)
Definition at line 482 of file boss_brutallus.cpp.
References WorldObject::GetInstanceData(), Player::IsGameMaster(), and NPC_BRUTALLUS.
Referenced by AddSC_boss_brutallus().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {NPC_MADRIGOSA,             0,              6000},
    {YELL_MADR_ICE_BARRIER,     NPC_MADRIGOSA,  7000},
    {YELL_MADR_INTRO,           NPC_MADRIGOSA,  7000},
    {YELL_INTRO,                NPC_BRUTALLUS,  6000},
    {SPELL_FROST_BREATH,        0,              6000},
    {POINT_MOVE_ICE_BLOCK,      0,              5000},
    {YELL_MADR_ICE_BLOCK,       NPC_MADRIGOSA,  5000},
    {SPELL_FLAME_RING,          0,              7000},
    {YELL_INTRO_BREAK_ICE,      NPC_BRUTALLUS,  1000},
    {SPELL_FEL_FIREBALL,        0,              4000},
    {POINT_MOVE_GROUND,         0,              5000},
    {YELL_MADR_TRAP,            NPC_MADRIGOSA,  3000},
    {POINT_MOVE_ENCAPSULATE,    0,              7000},
    {YELL_INTRO_CHARGE,         NPC_BRUTALLUS,  2000},
    {SPELL_CHARGE,              NPC_BRUTALLUS,  5000},
    {SPELL_SELF_STUN,           0,              5000},
    {YELL_INTRO_KILL_MADRIGOSA, NPC_BRUTALLUS,  8000},
    {YELL_INTRO_TAUNT,          NPC_BRUTALLUS,  0},
    {0, 0, 0},
}
Definition at line 95 of file boss_brutallus.cpp.