CMaNGOS_WoTLK: boss_the_lurker_below.cpp File Reference
boss_the_lurker_below.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "serpent_shrine.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct AddsLocations
struct boss_the_lurker_belowAI
struct Spout
struct SpoutTurning
Enumerations
enum {
EMOTE_DEEP_BREATH = -1548056 , SPELL_WHIRL = 37660 , SPELL_GEYSER = 37478 , SPELL_SPOUT = 37431 ,
SPELL_SPOUT_LEFT = 37429 , SPELL_SPOUT_RIGHT = 37430 , SPELL_SPOUT_DAMAGE = 37433 , SPELL_WATERBOLT = 37138 ,
SPELL_SUBMERGE = 28819 , SPELL_CLEAR_ALL_DEBUFFS = 34098 , NPC_COILFANG_AMBUSHER = 21865 , NPC_COILFANG_GUARDIAN = 21873 ,
MAX_SUBMERGE_ADDS = 9
}
enum Phases {
PHASE_GROUND = 0 , PHASE_UNDERGROUND = 1 , PHASE_LEECHING_SWARM = 2 , PHASE_SUBMERGING = 3 ,
PHASE_IDLE = 0 , PHASE_SHIELDED = 1 , PHASE_WAITING = 2 , PHASE_NORMAL = 3 ,
PHASE_SKELETAL = 0 , PHASE_TAKE_FLESH = 1 , PHASE_FLESH = 2 , PHASE_RETURN_FLESH = 3 ,
PHASE_SKELETAL_END = 4 , PHASE_EMERGING = 0 , PHASE_NORMAL = 1 , PHASE_SPOUT = 2 ,
PHASE_SUBMERGED = 3 , PHASE_NORMAL = 1 , PHASE_SPLIT = 2 , PHASE_VOID = 3
}
enum LurkerActions {
LURKER_SUBMERGE_PHASE , LURKER_SPOUT , LURKER_WHIRL , LURKER_GEYSER ,
LURKER_WATERBOLT , LURKER_ACTION_MAX , LURKER_INITIAL_AGGRO , LURKER_SUBMERGE_ACTIONS ,
LURKER_SPOUT_END
}
Functions
bool GOUse_go_strange_pool (Player *, GameObject *go)
void AddSC_boss_the_lurker_below ()
Variables
static const AddsLocations aLurkerLoc [MAX_SUBMERGE_ADDS]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_DEEP_BREATH
SPELL_WHIRL
SPELL_GEYSER
SPELL_SPOUT
SPELL_SPOUT_LEFT
SPELL_SPOUT_RIGHT
SPELL_SPOUT_DAMAGE
SPELL_WATERBOLT
SPELL_SUBMERGE
SPELL_CLEAR_ALL_DEBUFFS
NPC_COILFANG_AMBUSHER
NPC_COILFANG_GUARDIAN
MAX_SUBMERGE_ADDS
Definition at line 30 of file boss_the_lurker_below.cpp.
LurkerActions
enum LurkerActions
Enumerator
LURKER_SUBMERGE_PHASE
LURKER_SPOUT
LURKER_WHIRL
LURKER_GEYSER
LURKER_WATERBOLT
LURKER_ACTION_MAX
LURKER_INITIAL_AGGRO
LURKER_SUBMERGE_ACTIONS
LURKER_SPOUT_END
Definition at line 78 of file boss_the_lurker_below.cpp.
Phases
enum Phases
Enumerator
PHASE_GROUND
PHASE_UNDERGROUND
PHASE_LEECHING_SWARM
PHASE_SUBMERGING
PHASE_IDLE
PHASE_SHIELDED
PHASE_WAITING
PHASE_NORMAL
PHASE_SKELETAL
PHASE_TAKE_FLESH
PHASE_FLESH
PHASE_RETURN_FLESH
PHASE_SKELETAL_END
PHASE_EMERGING
PHASE_NORMAL
PHASE_SPOUT
PHASE_SUBMERGED
PHASE_NORMAL
PHASE_SPLIT
PHASE_VOID
Definition at line 50 of file boss_the_lurker_below.cpp.
Function Documentation
AddSC_boss_the_lurker_below()
void AddSC_boss_the_lurker_below ()
Definition at line 356 of file boss_the_lurker_below.cpp.
References Script::GetAI, GOUse_go_strange_pool(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_strange_pool()
bool GOUse_go_strange_pool (Player * , GameObject * go)
Definition at line 303 of file boss_the_lurker_below.cpp.
References DAY, FAIL, WorldObject::GetInstanceData(), IN_PROGRESS, NOT_STARTED, GameObject::SetRespawnTime(), TYPE_THELURKER_EVENT, and urand().
Referenced by AddSC_boss_the_lurker_below().
Variable Documentation
aLurkerLoc
const AddsLocations aLurkerLoc[MAX_SUBMERGE_ADDS] static
Initial value:
=
{
    {NPC_COILFANG_AMBUSHER, 99.992676f, -275.775f, -21.852718f, 0},
    {NPC_COILFANG_AMBUSHER, 158.81189f, -316.7783f, -20.568338f, 1},
    {NPC_COILFANG_AMBUSHER, 82.55382f, -550.19965f, -20.765057f, 2},
    {NPC_COILFANG_AMBUSHER, 17.01065f, -557.4272f, -21.487282f, 3},
    {NPC_COILFANG_AMBUSHER, -14.230728f, -549.0762f, -21.056725f, 4},
    {NPC_COILFANG_AMBUSHER, -1.9712651f, -540.2956f, -21.792835f, 5},
    {NPC_COILFANG_GUARDIAN, 106.962f, -468.5177f, -21.63681f, 0},
    {NPC_COILFANG_GUARDIAN, 65.17899f, -340.6617f, -21.5217f, 1,},
    {NPC_COILFANG_GUARDIAN, -49.6826f, -414.9719f, -20.54604f, 2},
}
Definition at line 65 of file boss_the_lurker_below.cpp.
Referenced by boss_the_lurker_belowAI::DoSummonCoilfangNaga().