CMaNGOS_WoTLK: boss_darkweaver_syth.cpp File Reference
boss_darkweaver_syth.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct boss_darkweaver_sythAI
Enumerations
enum {
SAY_SUMMON = -1556000 , SAY_AGGRO_1 = -1556001 , SAY_AGGRO_2 = -1556002 , SAY_AGGRO_3 = -1556003 ,
SAY_SLAY_1 = -1556004 , SAY_SLAY_2 = -1556005 , SAY_DEATH = -1556006 , SPELL_FROST_SHOCK = 12548 ,
SPELL_FROST_SHOCK_H = 21401 , SPELL_FLAME_SHOCK = 15039 , SPELL_FLAME_SHOCK_H = 15616 , SPELL_SHADOW_SHOCK = 33620 ,
SPELL_SHADOW_SHOCK_H = 38136 , SPELL_ARCANE_SHOCK = 33534 , SPELL_ARCANE_SHOCK_H = 38135 , SPELL_CHAIN_LIGHTNING = 15659 ,
SPELL_CHAIN_LIGHTNING_H = 15305 , SPELL_SUMMON_SYTH_FIRE = 33537 , SPELL_SUMMON_SYTH_ARCANE = 33538 , SPELL_SUMMON_SYTH_FROST = 33539 ,
SPELL_SUMMON_SYTH_SHADOW = 33540 , NPC_FIRE_ELEMENTAL = 19203 , NPC_FROST_ELEMENTAL = 19204 , NPC_ARCANE_ELEMENTAL = 19205 ,
NPC_SHADOW_ELEMENTAL = 19206
}
Functions
UnitAI * GetAI_boss_darkweaver_syth (Creature *pCreature)
void AddSC_boss_darkweaver_syth ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SUMMON
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_SLAY_1
SAY_SLAY_2
SAY_DEATH
SPELL_FROST_SHOCK
SPELL_FROST_SHOCK_H
SPELL_FLAME_SHOCK
SPELL_FLAME_SHOCK_H
SPELL_SHADOW_SHOCK
SPELL_SHADOW_SHOCK_H
SPELL_ARCANE_SHOCK
SPELL_ARCANE_SHOCK_H
SPELL_CHAIN_LIGHTNING
SPELL_CHAIN_LIGHTNING_H
SPELL_SUMMON_SYTH_FIRE
SPELL_SUMMON_SYTH_ARCANE
SPELL_SUMMON_SYTH_FROST
SPELL_SUMMON_SYTH_SHADOW
NPC_FIRE_ELEMENTAL
NPC_FROST_ELEMENTAL
NPC_ARCANE_ELEMENTAL
NPC_SHADOW_ELEMENTAL
Definition at line 26 of file boss_darkweaver_syth.cpp.
Function Documentation
AddSC_boss_darkweaver_syth()
void AddSC_boss_darkweaver_syth ()
Definition at line 227 of file boss_darkweaver_syth.cpp.
References Script::GetAI, GetAI_boss_darkweaver_syth(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_darkweaver_syth()
UnitAI* GetAI_boss_darkweaver_syth (Creature * pCreature)
Definition at line 222 of file boss_darkweaver_syth.cpp.
Referenced by AddSC_boss_darkweaver_syth().