CMaNGOS_WoTLK: boss_warchief_kargath_bladefist.cpp File Reference
boss_warchief_kargath_bladefist.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shattered_halls.h"
Data Structures
struct boss_warchief_kargath_bladefistAI
struct npc_blade_dance_targetAI
Enumerations
enum {
SAY_AGGRO1 = -1540042 , SAY_AGGRO2 = -1540043 , SAY_AGGRO3 = -1540044 , SAY_SLAY1 = -1540045 ,
SAY_SLAY2 = -1540046 , SAY_DEATH = -1540047 , SAY_EVADE = -1540048 , SPELL_BLADE_DANCE_CHARGE = 30751 ,
SPELL_BLADE_DANCE_TARGETING = 30738 , SPELL_BLADE_DANCE = 30739 , SPELL_CHARGE_H = 25821 , SPELL_DOUBLE_ATTACK = 19818 ,
TARGET_NUM = 8 , NPC_SHATTERED_ASSASSIN = 17695 , NPC_HEARTHEN_GUARD = 17621 , NPC_SHARPSHOOTER_GUARD = 17622 ,
NPC_REAVER_GUARD = 17623
}
Functions
UnitAI * GetAI_boss_warchief_kargath_bladefist (Creature *pCreature)
UnitAI * GetAI_npc_blade_dance_target (Creature *pCreature)
void AddSC_boss_warchief_kargath_bladefist ()
Variables
float AssassEntrance [3] = {275.136f, -84.29f, 2.3f}
float AssassExit [3] = {184.233f, -84.29f, 2.3f}
float AddsEntrance [3] = {306.036f, -84.29f, 1.93f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SAY_EVADE
SPELL_BLADE_DANCE_CHARGE
SPELL_BLADE_DANCE_TARGETING
SPELL_BLADE_DANCE
SPELL_CHARGE_H
SPELL_DOUBLE_ATTACK
TARGET_NUM
NPC_SHATTERED_ASSASSIN
NPC_HEARTHEN_GUARD
NPC_SHARPSHOOTER_GUARD
NPC_REAVER_GUARD
Definition at line 31 of file boss_warchief_kargath_bladefist.cpp.
Function Documentation
AddSC_boss_warchief_kargath_bladefist()
void AddSC_boss_warchief_kargath_bladefist ()
Definition at line 349 of file boss_warchief_kargath_bladefist.cpp.
References Script::GetAI, GetAI_boss_warchief_kargath_bladefist(), GetAI_npc_blade_dance_target(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_warchief_kargath_bladefist()
UnitAI* GetAI_boss_warchief_kargath_bladefist (Creature * pCreature)
Definition at line 329 of file boss_warchief_kargath_bladefist.cpp.
Referenced by AddSC_boss_warchief_kargath_bladefist().
GetAI_npc_blade_dance_target()
UnitAI* GetAI_npc_blade_dance_target (Creature * pCreature)
Definition at line 344 of file boss_warchief_kargath_bladefist.cpp.
Referenced by AddSC_boss_warchief_kargath_bladefist().
Variable Documentation
AddsEntrance
float AddsEntrance[3] = {306.036f, -84.29f, 1.93f}
Definition at line 57 of file boss_warchief_kargath_bladefist.cpp.
Referenced by boss_warchief_kargath_bladefistAI::UpdateAI().
AssassEntrance
float AssassEntrance[3] = {275.136f, -84.29f, 2.3f}
Definition at line 55 of file boss_warchief_kargath_bladefist.cpp.
Referenced by boss_warchief_kargath_bladefistAI::SpawnAssassin().
AssassExit
float AssassExit[3] = {184.233f, -84.29f, 2.3f}
Definition at line 56 of file boss_warchief_kargath_bladefist.cpp.
Referenced by boss_warchief_kargath_bladefistAI::SpawnAssassin().