CMaNGOS_WoTLK: bosses_opera.cpp File Reference
bosses_opera.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "karazhan.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct boss_dorotheeAI
struct boss_strawmanAI
struct boss_tinheadAI
struct boss_roarAI
struct boss_croneAI
struct npc_grandmotherAI
struct boss_bigbadwolfAI
struct boss_julianneAI
struct boss_romuloAI
Enumerations
enum {
SAY_DOROTHEE_DEATH = -1532025 , SAY_DOROTHEE_SUMMON = -1532026 , SAY_DOROTHEE_TITO_DEATH = -1532027 , SAY_DOROTHEE_AGGRO = -1532028 ,
SAY_ROAR_AGGRO = -1532029 , SAY_ROAR_DEATH = -1532030 , SAY_ROAR_SLAY = -1532031 , SAY_STRAWMAN_AGGRO = -1532032 ,
SAY_STRAWMAN_DEATH = -1532033 , SAY_STRAWMAN_SLAY = -1532034 , SAY_TINHEAD_AGGRO = -1532035 , SAY_TINHEAD_DEATH = -1532036 ,
SAY_TINHEAD_SLAY = -1532037 , EMOTE_RUST = -1532038 , SAY_CRONE_INTRO = -1532039 , SAY_CRONE_INTRO2 = -1532040 ,
SAY_CRONE_DEATH = -1532041 , SAY_CRONE_SLAY = -1532042 , SPELL_WATERBOLT = 31012 , SPELL_FRIGHTENEDSCREAM = 31013 ,
SPELL_SUMMONTITO = 31014 , SPELL_BRAIN_BASH = 31046 , SPELL_BRAIN_WIPE = 31069 , SPELL_CONFLAG_PROC = 31073 ,
SPELL_CLEAVE = 31043 , SPELL_RUST = 31086 , SPELL_MANGLE = 31041 , SPELL_SHRED = 31042 ,
SPELL_FRIGHTENED_SCREAM = 31013 , SPELL_CHAIN_LIGHTNING = 32337 , SPELL_FIERY_BROOM_PROC = 32339 , SPELL_CYCLONE = 32334 ,
SPELL_CYCLONE_VISUAL = 32332 , NPC_TITO = 17548 , NPC_CYCLONE = 18412
}
enum DorotheeActions {
DOROTHEE_ACTION_SUMMONTITO , DOROTHEE_ACTION_FRIGHTENEDSCREAM , DOROTHEE_ACTION_WATERBOLT , DOROTHEE_ACTION_MAX ,
DOROTHEE_INTRO , DOROTHEE_AGGRO
}
enum {
SAY_WOLF_AGGRO = -1532043 , SAY_WOLF_SLAY = -1532044 , SAY_WOLF_HOOD = -1532045 , SOUND_WOLF_DEATH = 9275 ,
SPELL_PICK_RED_RIDING_HOOD = 30769 , SPELL_RED_RIDING_HOOD = 30756 , SPELL_TERRIFYING_HOWL = 30752 , SPELL_WIDE_SWIPE = 30761 ,
GOSSIP_ITEM_GRANDMA_FIRST = -3532020 , GOSSIP_ITEM_GRANDMA_SECOND = -3532021 , GOSSIP_ITEM_GRANDMA_THIRD = -3532005 , TEXT_ID_GRANDMA_FIRST = 9009 ,
TEXT_ID_GRANDMA_SECOND = 9010 , TEXT_ID_GRANDMA_THIRD = 9011 , GOSSIP_MENU_ID_GRANDMA_FIRST = 7441 , GOSSIP_MENU_ID_GRANDMA_SECOND = 7442 ,
GOSSIP_MENU_ID_GRANDMA_THIRD = 7443 , TEXT_ID_GRANDMA = 8990 , NPC_BIG_BAD_WOLF = 17521
}
enum {
SAY_JULIANNE_AGGRO = -1532046 , SAY_JULIANNE_ENTER = -1532047 , SAY_JULIANNE_DEATH01 = -1532048 , SAY_JULIANNE_DEATH02 = -1532049 ,
SAY_JULIANNE_RESURRECT = -1532050 , SAY_JULIANNE_SLAY = -1532051 , SAY_ROMULO_AGGRO = -1532052 , SAY_ROMULO_DEATH = -1532053 ,
SAY_ROMULO_ENTER = -1532054 , SAY_ROMULO_RESURRECT = -1532055 , SAY_ROMULO_SLAY = -1532056 , SPELL_BLINDING_PASSION = 30890 ,
SPELL_DEVOTION = 30887 , SPELL_ETERNAL_AFFECTION = 30878 , SPELL_POWERFUL_ATTRACTION = 30889 , SPELL_DRINK_POISON = 30907 ,
SPELL_BACKWARD_LUNGE = 30815 , SPELL_DARING = 30841 , SPELL_DEADLY_SWATHE = 30817 , SPELL_POISON_THRUST = 30822 ,
SPELL_FULL_HEALTH = 43979 , SPELL_UNDYING_LOVE = 30951 , SPELL_SUICIDE_WHILE_DEAD = 30966
}
enum OperaPhase { PHASE_JULIANNE = 0 , PHASE_ROMULO = 1 , PHASE_BOTH = 2 }
Functions
bool GossipHello_npc_grandmother (Player *pPlayer, Creature *creature)
bool GossipSelect_npc_grandmother (Player *pPlayer, Creature *creature, uint32, uint32 uiAction)
bool EffectDummyCreature_spell_drink_poison (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *creatureTarget, ObjectGuid)
void AddSC_bosses_opera ()
Variables
static const float afCycloneSpawnLoc1 [4] = { -10908.86f, -1773.627f, 90.55865f, 5.833215f }
static const float afCycloneSpawnLoc2 [4] = { -10910.79f, -1771.201f, 90.56122f, 0.3642556f }
static const float afCycloneSpawnLoc3 [4] = { -10907.68f, -1778.651f, 90.56018f, 2.44127f }
static const float afRomuloSpawnLoc [4] = { -10893.62f, -1760.78f, 90.55f, 4.76f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DOROTHEE_DEATH
SAY_DOROTHEE_SUMMON
SAY_DOROTHEE_TITO_DEATH
SAY_DOROTHEE_AGGRO
SAY_ROAR_AGGRO
SAY_ROAR_DEATH
SAY_ROAR_SLAY
SAY_STRAWMAN_AGGRO
SAY_STRAWMAN_DEATH
SAY_STRAWMAN_SLAY
SAY_TINHEAD_AGGRO
SAY_TINHEAD_DEATH
SAY_TINHEAD_SLAY
EMOTE_RUST
SAY_CRONE_INTRO
SAY_CRONE_INTRO2
SAY_CRONE_DEATH
SAY_CRONE_SLAY
SPELL_WATERBOLT
SPELL_FRIGHTENEDSCREAM
SPELL_SUMMONTITO
SPELL_BRAIN_BASH
SPELL_BRAIN_WIPE
SPELL_CONFLAG_PROC
SPELL_CLEAVE
SPELL_RUST
SPELL_MANGLE
SPELL_SHRED
SPELL_FRIGHTENED_SCREAM
SPELL_CHAIN_LIGHTNING
SPELL_FIERY_BROOM_PROC
SPELL_CYCLONE
SPELL_CYCLONE_VISUAL
NPC_TITO
Creature Entries.
NPC_CYCLONE
Definition at line 33 of file bosses_opera.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_WOLF_AGGRO
SAY_WOLF_SLAY
SAY_WOLF_HOOD
SOUND_WOLF_DEATH
SPELL_PICK_RED_RIDING_HOOD
SPELL_RED_RIDING_HOOD
SPELL_TERRIFYING_HOWL
SPELL_WIDE_SWIPE
GOSSIP_ITEM_GRANDMA_FIRST
GOSSIP_ITEM_GRANDMA_SECOND
GOSSIP_ITEM_GRANDMA_THIRD
TEXT_ID_GRANDMA_FIRST
TEXT_ID_GRANDMA_SECOND
TEXT_ID_GRANDMA_THIRD
GOSSIP_MENU_ID_GRANDMA_FIRST
GOSSIP_MENU_ID_GRANDMA_SECOND
GOSSIP_MENU_ID_GRANDMA_THIRD
TEXT_ID_GRANDMA
NPC_BIG_BAD_WOLF
Definition at line 598 of file bosses_opera.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_JULIANNE_AGGRO
SAY_JULIANNE_ENTER
SAY_JULIANNE_DEATH01
SAY_JULIANNE_DEATH02
SAY_JULIANNE_RESURRECT
SAY_JULIANNE_SLAY
SAY_ROMULO_AGGRO
SAY_ROMULO_DEATH
SAY_ROMULO_ENTER
SAY_ROMULO_RESURRECT
SAY_ROMULO_SLAY
SPELL_BLINDING_PASSION
SPELL_DEVOTION
SPELL_ETERNAL_AFFECTION
SPELL_POWERFUL_ATTRACTION
SPELL_DRINK_POISON
SPELL_BACKWARD_LUNGE
SPELL_DARING
SPELL_DEADLY_SWATHE
SPELL_POISON_THRUST
SPELL_FULL_HEALTH
SPELL_UNDYING_LOVE
SPELL_SUICIDE_WHILE_DEAD
Definition at line 826 of file bosses_opera.cpp.
DorotheeActions
enum DorotheeActions
Enumerator
DOROTHEE_ACTION_SUMMONTITO
DOROTHEE_ACTION_FRIGHTENEDSCREAM
DOROTHEE_ACTION_WATERBOLT
DOROTHEE_ACTION_MAX
DOROTHEE_INTRO
DOROTHEE_AGGRO
Definition at line 91 of file bosses_opera.cpp.
OperaPhase
enum OperaPhase
Enumerator
PHASE_JULIANNE
PHASE_ROMULO
PHASE_BOTH
Definition at line 861 of file bosses_opera.cpp.
Function Documentation
AddSC_bosses_opera()
void AddSC_bosses_opera ()
Definition at line 1360 of file bosses_opera.cpp.
References EffectDummyCreature_spell_drink_poison(), Script::GetAI, GossipHello_npc_grandmother(), GossipSelect_npc_grandmother(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_drink_poison()
bool EffectDummyCreature_spell_drink_poison (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 1121 of file bosses_opera.cpp.
References Creature::AI(), DoScriptText(), EFFECT_INDEX_0, SAY_JULIANNE_DEATH01, and SPELL_DRINK_POISON.
Referenced by AddSC_bosses_opera().
GossipHello_npc_grandmother()
bool GossipHello_npc_grandmother (Player * pPlayer, Creature * creature)
Definition at line 630 of file bosses_opera.cpp.
References Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_GRANDMA_FIRST, GOSSIP_MENU_ID_GRANDMA_FIRST, GOSSIP_SENDER_MAIN, and TEXT_ID_GRANDMA_FIRST.
Referenced by AddSC_bosses_opera().
GossipSelect_npc_grandmother()
bool GossipSelect_npc_grandmother (Player * pPlayer, Creature * creature, uint32 , uint32 uiAction)
Definition at line 639 of file bosses_opera.cpp.
References AI_EVENT_CUSTOM_A, Creature::ForcedDespawn(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_GRANDMA_SECOND, GOSSIP_ITEM_GRANDMA_THIRD, GOSSIP_MENU_ID_GRANDMA_SECOND, GOSSIP_MENU_ID_GRANDMA_THIRD, GOSSIP_SENDER_MAIN, NPC_BIG_BAD_WOLF, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEXT_ID_GRANDMA_SECOND, and TEXT_ID_GRANDMA_THIRD.
Referenced by AddSC_bosses_opera().
Variable Documentation
afCycloneSpawnLoc1
const float afCycloneSpawnLoc1[4] = { -10908.86f, -1773.627f, 90.55865f, 5.833215f } static
Definition at line 487 of file bosses_opera.cpp.
Referenced by boss_croneAI::Aggro().
afCycloneSpawnLoc2
const float afCycloneSpawnLoc2[4] = { -10910.79f, -1771.201f, 90.56122f, 0.3642556f } static
Definition at line 488 of file bosses_opera.cpp.
Referenced by boss_croneAI::Aggro().
afCycloneSpawnLoc3
const float afCycloneSpawnLoc3[4] = { -10907.68f, -1778.651f, 90.56018f, 2.44127f } static
Definition at line 489 of file bosses_opera.cpp.
Referenced by boss_croneAI::Aggro().
afRomuloSpawnLoc
const float afRomuloSpawnLoc[4] = { -10893.62f, -1760.78f, 90.55f, 4.76f} static
Definition at line 868 of file bosses_opera.cpp.
Referenced by boss_julianneAI::UpdateAI().