CMaNGOS_WoTLK: boss_archaedas.cpp File Reference
boss_archaedas.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "uldaman.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_archaedasAI
Enumerations
enum {
SPELL_ARCHAEDAS_AWAKEN_VISUAL = 10347 , SPELL_GROUND_TREMOR = 6524 , SPELL_AWAKEN_EARTHEN_GUARDIAN = 10252 , SPELL_AWAKEN_VAULT_WARDER = 10258 ,
SPELL_AWAKEN_EARTHEN_DWARF = 10259 , SAY_AGGRO = -1070001 , SAY_AWAKE_GUARDIANS = -1070002 , SAY_AWAKE_WARDERS = -1070003 ,
SAY_UNIT_SLAIN = -1070004 , EMOTE_BREAKS_FREE = -1070005
}
Functions
UnitAI * GetAI_boss_archaedas (Creature *pCreature)
bool EffectDummyCreature_npc_vault_warder (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectAuraDummy_spell_aura_dummy_awaken_dwarf (const Aura *pAura, bool bApply)
void AddSC_boss_archaedas ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_ARCHAEDAS_AWAKEN_VISUAL
SPELL_GROUND_TREMOR
SPELL_AWAKEN_EARTHEN_GUARDIAN
SPELL_AWAKEN_VAULT_WARDER
SPELL_AWAKEN_EARTHEN_DWARF
SAY_AGGRO
SAY_AWAKE_GUARDIANS
SAY_AWAKE_WARDERS
SAY_UNIT_SLAIN
EMOTE_BREAKS_FREE
Definition at line 28 of file boss_archaedas.cpp.
Function Documentation
AddSC_boss_archaedas()
void AddSC_boss_archaedas ()
Definition at line 235 of file boss_archaedas.cpp.
References EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectDummyCreature_npc_vault_warder(), Script::GetAI, GetAI_boss_archaedas(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_awaken_dwarf()
bool EffectAuraDummy_spell_aura_dummy_awaken_dwarf (const Aura * pAura, bool bApply)
Definition at line 212 of file boss_archaedas.cpp.
References EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), ScriptedInstance::GetSingleCreatureFromStorage(), Aura::GetTarget(), NPC_ARCHAEDAS, SPELL_AWAKEN_EARTHEN_DWARF, SPELL_AWAKEN_EARTHEN_GUARDIAN, and SPELL_STONED.
Referenced by AddSC_boss_archaedas().
EffectDummyCreature_npc_vault_warder()
bool EffectDummyCreature_npc_vault_warder (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 189 of file boss_archaedas.cpp.
References Creature::AI(), UnitAI::AttackStart(), EFFECT_INDEX_0, Object::GetEntry(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_ARCHAEDAS, NPC_VAULT_WARDER, Unit::RemoveAurasDueToSpell(), SPELL_AWAKEN_VAULT_WARDER, and SPELL_STONED.
Referenced by AddSC_boss_archaedas().
GetAI_boss_archaedas()
UnitAI* GetAI_boss_archaedas (Creature * pCreature)
Definition at line 184 of file boss_archaedas.cpp.
Referenced by AddSC_boss_archaedas().