CMaNGOS_WoTLK: bosses_emerald_dragons.cpp File Reference
bosses_emerald_dragons.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "World/WorldState.h"
Data Structures
struct boss_emerald_dragonAI
struct boss_emerissAI
struct boss_lethonAI
struct npc_spirit_shadeAI
struct boss_taerarAI
struct boss_ysondreAI
Enumerations
enum {
SPELL_MARK_OF_NATURE_PLAYER = 25040 , SPELL_MARK_OF_NATURE_AURA = 25041 , SPELL_SEEPING_FOG_R = 24813 , SPELL_SEEPING_FOG_L = 24814 ,
SPELL_NOXIOUS_BREATH = 24818 , SPELL_TAILSWEEP = 15847 , SPELL_SUMMON_PLAYER = 24776 , NPC_YSONDRE = 14887
}
enum {
SAY_EMERISS_AGGRO = -1000401 , SAY_CAST_CORRUPTION = -1000402 , SPELL_VOLATILE_INFECTION = 24928 , SPELL_CORRUPTION_OF_EARTH = 24910 ,
SPELL_PUTRID_MUSHROOM = 24904 , SPELL_DESPAWN_MUSHROOMS = 24958
}
enum {
SAY_LETHON_AGGRO = -1000666 , SAY_DRAW_SPIRIT = -1000667 , SPELL_SHADOW_BOLT_WIRL = 24834 , SPELL_DRAW_SPIRIT = 24811 ,
NPC_LETHON = 14888 , NPC_SPIRIT_SHADE = 15261 , SPELL_DARK_OFFERING = 24804 , SPELL_SPIRIT_SHAPE_VISUAL = 24809
}
enum {
SAY_TAERAR_AGGRO = -1000399 , SAY_SUMMONSHADE = -1000400 , SPELL_ARCANE_BLAST = 24857 , SPELL_BELLOWING_ROAR = 22686 ,
SPELL_SUMMON_SHADE_1 = 24841 , SPELL_SUMMON_SHADE_2 = 24842 , SPELL_SUMMON_SHADE_3 = 24843 , SPELL_SELF_STUN = 24883 ,
SPELL_DESPAWN_SHADES = 24886 , NPC_SHADE_OF_TAERAR = 15302
}
enum { SAY_YSONDRE_AGGRO = -1000360 , SAY_SUMMON_DRUIDS = -1000361 , SPELL_LIGHTNING_WAVE = 24819 , SPELL_SUMMON_DRUIDS = 24796 }
Functions
UnitAI * GetAI_boss_emeriss (Creature *pCreature)
UnitAI * GetAI_boss_lethon (Creature *pCreature)
UnitAI * GetAI_npc_spirit_shade (Creature *pCreature)
UnitAI * GetAI_boss_taerar (Creature *pCreature)
UnitAI * GetAI_boss_ysondre (Creature *pCreature)
void AddSC_bosses_emerald_dragons ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_MARK_OF_NATURE_PLAYER
SPELL_MARK_OF_NATURE_AURA
SPELL_SEEPING_FOG_R
SPELL_SEEPING_FOG_L
SPELL_NOXIOUS_BREATH
SPELL_TAILSWEEP
SPELL_SUMMON_PLAYER
NPC_YSONDRE
Definition at line 40 of file bosses_emerald_dragons.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_EMERISS_AGGRO
SAY_CAST_CORRUPTION
SPELL_VOLATILE_INFECTION
SPELL_CORRUPTION_OF_EARTH
SPELL_PUTRID_MUSHROOM
SPELL_DESPAWN_MUSHROOMS
Definition at line 149 of file bosses_emerald_dragons.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_LETHON_AGGRO
SAY_DRAW_SPIRIT
SPELL_SHADOW_BOLT_WIRL
SPELL_DRAW_SPIRIT
NPC_LETHON
NPC_SPIRIT_SHADE
SPELL_DARK_OFFERING
SPELL_SPIRIT_SHAPE_VISUAL
Definition at line 227 of file bosses_emerald_dragons.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_TAERAR_AGGRO
SAY_SUMMONSHADE
SPELL_ARCANE_BLAST
SPELL_BELLOWING_ROAR
SPELL_SUMMON_SHADE_1
SPELL_SUMMON_SHADE_2
SPELL_SUMMON_SHADE_3
SPELL_SELF_STUN
SPELL_DESPAWN_SHADES
NPC_SHADE_OF_TAERAR
Definition at line 352 of file bosses_emerald_dragons.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_YSONDRE_AGGRO
SAY_SUMMON_DRUIDS
SPELL_LIGHTNING_WAVE
SPELL_SUMMON_DRUIDS
Definition at line 489 of file bosses_emerald_dragons.cpp.
Function Documentation
AddSC_bosses_emerald_dragons()
void AddSC_bosses_emerald_dragons ()
Definition at line 550 of file bosses_emerald_dragons.cpp.
References Script::GetAI, GetAI_boss_emeriss(), GetAI_boss_lethon(), GetAI_boss_taerar(), GetAI_boss_ysondre(), GetAI_npc_spirit_shade(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_emeriss()
UnitAI* GetAI_boss_emeriss (Creature * pCreature)
Definition at line 218 of file bosses_emerald_dragons.cpp.
Referenced by AddSC_bosses_emerald_dragons().
GetAI_boss_lethon()
UnitAI* GetAI_boss_lethon (Creature * pCreature)
Definition at line 338 of file bosses_emerald_dragons.cpp.
Referenced by AddSC_bosses_emerald_dragons().
GetAI_boss_taerar()
UnitAI* GetAI_boss_taerar (Creature * pCreature)
Definition at line 480 of file bosses_emerald_dragons.cpp.
Referenced by AddSC_bosses_emerald_dragons().
GetAI_boss_ysondre()
UnitAI* GetAI_boss_ysondre (Creature * pCreature)
Definition at line 545 of file bosses_emerald_dragons.cpp.
Referenced by AddSC_bosses_emerald_dragons().
GetAI_npc_spirit_shade()
UnitAI* GetAI_npc_spirit_shade (Creature * pCreature)
Definition at line 343 of file bosses_emerald_dragons.cpp.
Referenced by AddSC_bosses_emerald_dragons().