CMaNGOS_WoTLK: boss_ymiron.cpp File Reference
boss_ymiron.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "utgarde_pinnacle.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct BoatSpirits
struct boss_ymironAI
struct spell_create_spirit_fount_beam_aura
struct spell_avenging_spirits
Enumerations
enum {
SAY_AGGRO = -1575031 , SAY_SUMMON_BJORN = -1575032 , SAY_SUMMON_HALDOR = -1575033 , SAY_SUMMON_RANULF = -1575034 ,
SAY_SUMMON_TORGYN = -1575035 , SAY_SLAY_1 = -1575036 , SAY_SLAY_2 = -1575037 , SAY_SLAY_3 = -1575038 ,
SAY_SLAY_4 = -1575039 , SAY_DEATH = -1575040 , SPELL_BANE = 48294 , SPELL_BANE_H = 59301 ,
SPELL_DARK_SLASH = 48292 , SPELL_FETID_ROT = 48291 , SPELL_FETID_ROT_H = 59300 , SPELL_SCREAMS_OF_THE_DEAD = 51750 ,
SPELL_SPIRIT_BURST = 48529 , SPELL_SPIRIT_BURST_H = 59305 , SPELL_SPIRIT_STRIKE = 48423 , SPELL_SPIRIT_STRIKE_H = 59304 ,
SPELL_SUMMON_SPIRIT_FOUNT = 48386 , SPELL_SPIRIT_FOUNT_BEAM = 48385 , SPELL_AVENGING_SPIRITS = 48590 , SPELL_CHANNEL_YMIRON_SPIRIT = 48307 ,
SPELL_CHANNEL_SPIRIT_YMIRON = 48316 , SPELL_EMERGE_STATE = 56864 , SPELL_SPIRIT_DIES = 48596 , SPELL_BJORN_TRANSFORM = 48308 ,
SPELL_HALDOR_TRANSFORM = 48311 , SPELL_RANULF_TRANSFORM = 48312 , SPELL_TORGYN_TRANSFORM = 48313 , MAX_BOATS = 4 ,
PHASE_NO_BOAT = 0 , PHASE_BJORN = 1 , PHASE_HALDOR = 2 , PHASE_RANULF = 3 ,
PHASE_TORGYN = 4
}
Functions
bool ProcessEventId_event_achiev_kings_bane (uint32, Object *pSource, Object *, bool)
void AddSC_boss_ymiron ()
Variables
static const BoatSpirits aYmironBoatsSpirits [MAX_BOATS]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SUMMON_BJORN
SAY_SUMMON_HALDOR
SAY_SUMMON_RANULF
SAY_SUMMON_TORGYN
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_SLAY_4
SAY_DEATH
SPELL_BANE
SPELL_BANE_H
SPELL_DARK_SLASH
SPELL_FETID_ROT
SPELL_FETID_ROT_H
SPELL_SCREAMS_OF_THE_DEAD
SPELL_SPIRIT_BURST
SPELL_SPIRIT_BURST_H
SPELL_SPIRIT_STRIKE
SPELL_SPIRIT_STRIKE_H
SPELL_SUMMON_SPIRIT_FOUNT
SPELL_SPIRIT_FOUNT_BEAM
SPELL_AVENGING_SPIRITS
SPELL_CHANNEL_YMIRON_SPIRIT
SPELL_CHANNEL_SPIRIT_YMIRON
SPELL_EMERGE_STATE
SPELL_SPIRIT_DIES
SPELL_BJORN_TRANSFORM
SPELL_HALDOR_TRANSFORM
SPELL_RANULF_TRANSFORM
SPELL_TORGYN_TRANSFORM
MAX_BOATS
PHASE_NO_BOAT
PHASE_BJORN
PHASE_HALDOR
PHASE_RANULF
PHASE_TORGYN
Definition at line 29 of file boss_ymiron.cpp.
Function Documentation
AddSC_boss_ymiron()
void AddSC_boss_ymiron ()
Definition at line 463 of file boss_ymiron.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_achiev_kings_bane(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_achiev_kings_bane()
bool ProcessEventId_event_achiev_kings_bane (uint32 , Object * pSource, Object * , bool)
Definition at line 407 of file boss_ymiron.cpp.
References IN_PROGRESS, SPECIAL, and TYPE_YMIRON.
Referenced by AddSC_boss_ymiron().
Variable Documentation
aYmironBoatsSpirits
const BoatSpirits aYmironBoatsSpirits[MAX_BOATS] static
Initial value:
=
{
    {SPELL_BJORN_TRANSFORM,  NPC_BJORN,  SAY_SUMMON_BJORN,  PHASE_BJORN},
    {SPELL_HALDOR_TRANSFORM, NPC_HALDOR, SAY_SUMMON_HALDOR, PHASE_HALDOR},
    {SPELL_RANULF_TRANSFORM, NPC_RANULF, SAY_SUMMON_RANULF, PHASE_RANULF},
    {SPELL_TORGYN_TRANSFORM, NPC_TORGYN, SAY_SUMMON_TORGYN, PHASE_TORGYN}
}
Definition at line 95 of file boss_ymiron.cpp.
Referenced by boss_ymironAI::DoChannelSpiritYmiron(), boss_ymironAI::DoResetSpirits(), boss_ymironAI::MovementInform(), and boss_ymironAI::UpdateAI().