CMaNGOS_WoTLK: boss_northrend_beasts.cpp File Reference
boss_northrend_beasts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_crusader.h"
Data Structures
struct npc_beast_combat_stalkerAI
struct boss_gormokAI
struct twin_jormungars_commonAI
struct boss_acidmawAI
struct boss_dreadscaleAI
struct boss_icehowlAI
Enumerations
enum {
SAY_TIRION_BEAST_2 = -1649005 , SAY_TIRION_BEAST_3 = -1649006 , EMOTE_JORMUNGAR_ENRAGE = -1649076 , SPELL_BERSERK = 26662 ,
SPELL_JORMUNGAR_ENRAGE = 68335 , SPELL_JORMUNGAR_ACHIEV_CREDIT = 68523 , PHASE_GORMOK = 0 , PHASE_WORMS = 1 ,
PHASE_ICEHOWL = 2
}
enum {
SPELL_IMPALE = 66331 , SPELL_STOMP = 66330 , SPELL_JUMP_TO_HAND = 66342 , SPELL_RISING_ANGER = 66636 ,
SPELL_SNOBOLLED = 66406
}
enum {
SPELL_SLIME_POOL = 66883 , SPELL_SWEEP = 66794 , SPELL_SPAWN_GROUND_VISUAL = 68302 , SPELL_STATIC_WORM_SUBMERGE = 66936 ,
SPELL_MOBILE_WORM_SUBMERGE = 66948 , SPELL_MOBILE_WORM_EMERGE = 66949 , SPELL_STATIC_WORM_EMERGE = 66947 , SPELL_HATE_TO_ZERO = 63984 ,
SPELL_PARALYTIC_TOXIN = 66823 , SPELL_BURNING_BILE = 66869 , SPELL_SLIME_POOL_AURA = 66882 , NPC_SLIME_POOL = 35176 ,
PHASE_STATIONARY = 0 , PHASE_SUBMERGED = 1 , PHASE_MOBILE = 2
}
enum {
SPELL_ACID_SPEW = 66818 , SPELL_PARALYTIC_BITE = 66824 , SPELL_ACID_SPIT = 66880 , SPELL_PARALYTIC_SPRAY = 66901 ,
DISPLAY_ID_ACIDMAW_FIXED = 29815 , DISPLAY_ID_ACIDMWA_MOBILE = 29816
}
enum {
SPELL_MOLTEN_SPEW = 66821 , SPELL_BURNING_BITE = 66879 , SPELL_FIRE_SPIT = 66796 , SPELL_BURNING_SPRAY = 66902 ,
DISPLAY_ID_DREADSCALE_FIXED = 26935 , DISPLAY_ID_DREADSCALE_MOBILE = 24564
}
enum {
EMOTE_MASSIVE_CRASH = -1649039 , EMOTE_WALL_CRASH = -1649077 , SPELL_ARCTIC_BREATH = 66689 , SPELL_WHIRL = 67345 ,
SPELL_FEROCIOUS_BUTT = 66770 , SPELL_MASSIVE_CRASH = 66683 , SPELL_SURGE_OF_ADRENALINE = 68667 , SPELL_ROAR = 66736 ,
SPELL_JUMP_BACK = 66733 , SPELL_TRAMPLE = 66734 , SPELL_STAGGERED_DAZE = 66758 , SPELL_FROTHING_RAGE = 66759 ,
NPC_FURIOUS_CHARGE_STALKER = 35062 , POINT_ID_CHARGE_BEGIN = 101 , POINT_ID_CHARGE_END = 102
}
Functions
bool EffectDummyCreature_worm_emerge (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_northrend_beasts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_TIRION_BEAST_2
SAY_TIRION_BEAST_3
EMOTE_JORMUNGAR_ENRAGE
SPELL_BERSERK
SPELL_JORMUNGAR_ENRAGE
SPELL_JORMUNGAR_ACHIEV_CREDIT
PHASE_GORMOK
PHASE_WORMS
PHASE_ICEHOWL
Definition at line 31 of file boss_northrend_beasts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_IMPALE
SPELL_STOMP
SPELL_JUMP_TO_HAND
SPELL_RISING_ANGER
SPELL_SNOBOLLED
Definition at line 352 of file boss_northrend_beasts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SLIME_POOL
SPELL_SWEEP
SPELL_SPAWN_GROUND_VISUAL
SPELL_STATIC_WORM_SUBMERGE
SPELL_MOBILE_WORM_SUBMERGE
SPELL_MOBILE_WORM_EMERGE
SPELL_STATIC_WORM_EMERGE
SPELL_HATE_TO_ZERO
SPELL_PARALYTIC_TOXIN
SPELL_BURNING_BILE
SPELL_SLIME_POOL_AURA
NPC_SLIME_POOL
PHASE_STATIONARY
PHASE_SUBMERGED
PHASE_MOBILE
Definition at line 513 of file boss_northrend_beasts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ACID_SPEW
SPELL_PARALYTIC_BITE
SPELL_ACID_SPIT
SPELL_PARALYTIC_SPRAY
DISPLAY_ID_ACIDMAW_FIXED
DISPLAY_ID_ACIDMWA_MOBILE
Definition at line 736 of file boss_northrend_beasts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_MOLTEN_SPEW
SPELL_BURNING_BITE
SPELL_FIRE_SPIT
SPELL_BURNING_SPRAY
DISPLAY_ID_DREADSCALE_FIXED
DISPLAY_ID_DREADSCALE_MOBILE
Definition at line 797 of file boss_northrend_beasts.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_MASSIVE_CRASH
EMOTE_WALL_CRASH
SPELL_ARCTIC_BREATH
SPELL_WHIRL
SPELL_FEROCIOUS_BUTT
SPELL_MASSIVE_CRASH
SPELL_SURGE_OF_ADRENALINE
SPELL_ROAR
SPELL_JUMP_BACK
SPELL_TRAMPLE
SPELL_STAGGERED_DAZE
SPELL_FROTHING_RAGE
NPC_FURIOUS_CHARGE_STALKER
POINT_ID_CHARGE_BEGIN
POINT_ID_CHARGE_END
Definition at line 875 of file boss_northrend_beasts.cpp.
Function Documentation
AddSC_northrend_beasts()
void AddSC_northrend_beasts ()
Definition at line 1114 of file boss_northrend_beasts.cpp.
References EffectDummyCreature_worm_emerge(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_worm_emerge()
bool EffectDummyCreature_worm_emerge (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 859 of file boss_northrend_beasts.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_C, EFFECT_INDEX_0, UnitAI::SendAIEvent(), SPELL_MOBILE_WORM_EMERGE, and SPELL_STATIC_WORM_EMERGE.
Referenced by AddSC_northrend_beasts().