CMaNGOS_WoTLK: boss_novos.cpp File Reference
boss_novos.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "draktharon_keep.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_novosAI
struct npc_crystal_channel_targetAI
Enumerations
enum {
SAY_AGGRO = -1600005 , SAY_DEATH = -1600006 , SAY_KILL = -1600007 , SAY_ADDS = -1600008 ,
SAY_BUBBLE_1 = -1600009 , SAY_BUBBLE_2 = -1600010 , EMOTE_ASSISTANCE = -1600011 , SPELL_ARCANE_FIELD = 47346 ,
SPELL_IMMUNITY = 34098 , SPELL_SUMMON_MINIONS_H = 59910 , SPELL_FROSTBOLT = 49037 , SPELL_FROSTBOLT_H = 59855 ,
SPELL_ARCANE_BLAST = 49198 , SPELL_ARCANE_BLAST_H = 59909 , SPELL_BLIZZARD = 49034 , SPELL_BLIZZARD_H = 59854 ,
SPELL_TOUCH_OF_MISERY = 50090 , SPELL_WRATH_OF_MISERY = 50089 , SPELL_WRATH_OF_MISERY_H = 59856 , SPELL_SUMMON_FETID_TROLL_CORPSE = 49103 ,
SPELL_SUMMON_HULKING_CORPSE = 49104 , SPELL_SUMMON_RISON_SHADOWCASTER = 49105
}
enum Phases {
PHASE_GROUND = 0 , PHASE_UNDERGROUND = 1 , PHASE_LEECHING_SWARM = 2 , PHASE_SUBMERGING = 3 ,
PHASE_IDLE = 0 , PHASE_SHIELDED = 1 , PHASE_WAITING = 2 , PHASE_NORMAL = 3 ,
PHASE_SKELETAL = 0 , PHASE_TAKE_FLESH = 1 , PHASE_FLESH = 2 , PHASE_RETURN_FLESH = 3 ,
PHASE_SKELETAL_END = 4 , PHASE_EMERGING = 0 , PHASE_NORMAL = 1 , PHASE_SPOUT = 2 ,
PHASE_SUBMERGED = 3 , PHASE_NORMAL = 1 , PHASE_SPLIT = 2 , PHASE_VOID = 3
}
Functions
UnitAI * GetAI_boss_novos (Creature *pCreature)
UnitAI * GetAI_npc_crystal_channel_target (Creature *pCreature)
bool EffectAuraDummy_npc_crystal_channel_target (const Aura *pAura, bool bApply)
void AddSC_boss_novos ()
Variables
static const float aHandlerSummonPos [2][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_DEATH
SAY_KILL
SAY_ADDS
SAY_BUBBLE_1
SAY_BUBBLE_2
EMOTE_ASSISTANCE
SPELL_ARCANE_FIELD
SPELL_IMMUNITY
SPELL_SUMMON_MINIONS_H
SPELL_FROSTBOLT
SPELL_FROSTBOLT_H
SPELL_ARCANE_BLAST
SPELL_ARCANE_BLAST_H
SPELL_BLIZZARD
SPELL_BLIZZARD_H
SPELL_TOUCH_OF_MISERY
SPELL_WRATH_OF_MISERY
SPELL_WRATH_OF_MISERY_H
SPELL_SUMMON_FETID_TROLL_CORPSE
SPELL_SUMMON_HULKING_CORPSE
SPELL_SUMMON_RISON_SHADOWCASTER
Definition at line 28 of file boss_novos.cpp.
Phases
enum Phases
Enumerator
PHASE_GROUND
PHASE_UNDERGROUND
PHASE_LEECHING_SWARM
PHASE_SUBMERGING
PHASE_IDLE
PHASE_SHIELDED
PHASE_WAITING
PHASE_NORMAL
PHASE_SKELETAL
PHASE_TAKE_FLESH
PHASE_FLESH
PHASE_RETURN_FLESH
PHASE_SKELETAL_END
PHASE_EMERGING
PHASE_NORMAL
PHASE_SPOUT
PHASE_SUBMERGED
PHASE_NORMAL
PHASE_SPLIT
PHASE_VOID
Definition at line 71 of file boss_novos.cpp.
Function Documentation
AddSC_boss_novos()
void AddSC_boss_novos ()
Definition at line 409 of file boss_novos.cpp.
References EffectAuraDummy_npc_crystal_channel_target(), Script::GetAI, GetAI_boss_novos(), GetAI_npc_crystal_channel_target(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_npc_crystal_channel_target()
bool EffectAuraDummy_npc_crystal_channel_target (const Aura * pAura, bool bApply)
Definition at line 377 of file boss_novos.cpp.
References aCrystalHandlerDeathSpells, EFFECT_INDEX_0, FAIL, Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), MAX_CRYSTALS, NOT_STARTED, NPC_NOVOS, and TYPE_NOVOS.
Referenced by AddSC_boss_novos().
GetAI_boss_novos()
UnitAI* GetAI_boss_novos (Creature * pCreature)
Definition at line 319 of file boss_novos.cpp.
Referenced by AddSC_boss_novos().
GetAI_npc_crystal_channel_target()
UnitAI* GetAI_npc_crystal_channel_target (Creature * pCreature)
Definition at line 371 of file boss_novos.cpp.
Referenced by AddSC_boss_novos().
Variable Documentation
aHandlerSummonPos
const float aHandlerSummonPos[2][3] static
Initial value:
=
{
    { -342.894836f, -727.016846f, 28.581081f},
    { -410.644653f, -731.826904f, 28.580412f}
}
Definition at line 61 of file boss_novos.cpp.
Referenced by boss_novosAI::UpdateAI().