CMaNGOS_WoTLK: boss_varos.cpp File Reference
boss_varos.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "oculus.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct CaptainData
struct boss_varosAI
struct npc_arcane_beamAI
Enumerations
enum {
SAY_AGGRO = -1578020 , SAY_CALL_CAPTAIN_1 = -1578021 , SAY_CALL_CAPTAIN_2 = -1578022 , SAY_CALL_CAPTAIN_3 = -1578023 ,
SAY_KILL_1 = -1578026 , SAY_KILL_2 = -1578027 , SAY_DEATH = -1578028 , EMOTE_CAPTAIN = -1578029 ,
SPELL_CENTRIFUGE_SHIELD = 50053 , SPELL_AMPLIFY_MAGIC = 51054 , SPELL_AMPLIFY_MAGIC_H = 59371 , SPELL_ENERGIZE_CORES = 50785 ,
SPELL_ENERGIZE_CORES_H = 59372 , SPELL_CALL_CAPTAIN_1 = 51008 , SPELL_CALL_CAPTAIN_2 = 51002 , SPELL_CALL_CAPTAIN_3 = 51006 ,
SPELL_CALL_CAPTAIN_4 = 51007 , EVENT_ID_CALL_CAPTAIN_1 = 18455 , EVENT_ID_CALL_CAPTAIN_2 = 12229 , EVENT_ID_CALL_CAPTAIN_3 = 10665 ,
EVENT_ID_CALL_CAPTAIN_4 = 18454 , MAX_CAPTAIN_EVENTS = 4 , SPELL_SUMMON_ARCANE_BEAM = 51014 , SPELL_ARCANE_BEAM_PERIODIC = 51019 ,
SPELL_ARCANE_BEAM_SPAWN = 51022 , NPC_ARCANE_BEAM = 28239
}
Functions
bool ProcessEventId_event_spell_call_captain (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
void AddSC_boss_varos ()
Variables
static const CaptainData aVarosCaptainData [4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_CALL_CAPTAIN_1
SAY_CALL_CAPTAIN_2
SAY_CALL_CAPTAIN_3
SAY_KILL_1
SAY_KILL_2
SAY_DEATH
EMOTE_CAPTAIN
SPELL_CENTRIFUGE_SHIELD
SPELL_AMPLIFY_MAGIC
SPELL_AMPLIFY_MAGIC_H
SPELL_ENERGIZE_CORES
SPELL_ENERGIZE_CORES_H
SPELL_CALL_CAPTAIN_1
SPELL_CALL_CAPTAIN_2
SPELL_CALL_CAPTAIN_3
SPELL_CALL_CAPTAIN_4
EVENT_ID_CALL_CAPTAIN_1
EVENT_ID_CALL_CAPTAIN_2
EVENT_ID_CALL_CAPTAIN_3
EVENT_ID_CALL_CAPTAIN_4
MAX_CAPTAIN_EVENTS
SPELL_SUMMON_ARCANE_BEAM
SPELL_ARCANE_BEAM_PERIODIC
SPELL_ARCANE_BEAM_SPAWN
NPC_ARCANE_BEAM
Definition at line 28 of file boss_varos.cpp.
Function Documentation
AddSC_boss_varos()
void AddSC_boss_varos ()
Definition at line 311 of file boss_varos.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_call_captain(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_spell_call_captain()
bool ProcessEventId_event_spell_call_captain (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 245 of file boss_varos.cpp.
References aVarosCaptainData, FORCED_MOVEMENT_FLIGHT, Object::GetTypeId(), NPC_AZURE_RING_CAPTAIN, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPEID_UNIT.
Referenced by AddSC_boss_varos().
Variable Documentation
aVarosCaptainData
const CaptainData aVarosCaptainData[4] static
Initial value:
=
{
    {EVENT_ID_CALL_CAPTAIN_1, 1205.74f,  1060.24f,  480.083f, 1.15f, 1239.198f, 1064.537f, 455.587f},
    {EVENT_ID_CALL_CAPTAIN_2, 1273.78f,  1159.366f, 480.083f, 4.79f, 1278.488f, 1119.482f, 455.634f},
    {EVENT_ID_CALL_CAPTAIN_3, 1356.845f, 1077.118f, 480.083f, 3.28f, 1331.333f, 1076.381f, 455.69f},
    {EVENT_ID_CALL_CAPTAIN_4, 1296.89f,  1002.76f,  480.083f, 1.71f, 1291.95f,  1024.354f, 455.739f},
}
Definition at line 72 of file boss_varos.cpp.
Referenced by ProcessEventId_event_spell_call_captain().