CMaNGOS_WoTLK: boss_darkmaster_gandling.cpp File Reference
boss_darkmaster_gandling.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "scholomance.h"
Data Structures
struct boss_darkmaster_gandlingAI
Enumerations
enum { SPELL_ARCANE_MISSILES = 15790 , SPELL_SHADOW_SHIELD = 12040 , SPELL_CURSE_SD = 18702 , SPELL_SHADOW_PORTAL = 17950 }
Functions
UnitAI * GetAI_boss_darkmaster_gandling (Creature *pCreature)
void AddSC_boss_darkmaster_gandling ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_ARCANE_MISSILES
SPELL_SHADOW_SHIELD
SPELL_CURSE_SD
SPELL_SHADOW_PORTAL
Definition at line 27 of file boss_darkmaster_gandling.cpp.
Function Documentation
AddSC_boss_darkmaster_gandling()
void AddSC_boss_darkmaster_gandling ()
Definition at line 115 of file boss_darkmaster_gandling.cpp.
References Script::GetAI, GetAI_boss_darkmaster_gandling(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_darkmaster_gandling()
UnitAI* GetAI_boss_darkmaster_gandling (Creature * pCreature)
Definition at line 110 of file boss_darkmaster_gandling.cpp.
Referenced by AddSC_boss_darkmaster_gandling().