CMaNGOS_WoTLK: boss_volkhan.cpp File Reference
boss_volkhan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_lightning.h"
Data Structures
struct boss_volkhanAI
struct mob_molten_golemAI
Enumerations
enum {
SAY_AGGRO = -1602032 , SAY_SLAY_1 = -1602033 , SAY_SLAY_2 = -1602034 , SAY_SLAY_3 = -1602035 ,
SAY_DEATH = -1602036 , SAY_STOMP_1 = -1602037 , SAY_STOMP_2 = -1602038 , SAY_FORGE_1 = -1602039 ,
SAY_FORGE_2 = -1602040 , EMOTE_TO_ANVIL = -1602041 , EMOTE_SHATTER = -1602042 , SPELL_HEAT = 52387 ,
SPELL_HEAT_H = 59528 , SPELL_SHATTERING_STOMP = 52237 , SPELL_SHATTERING_STOMP_H = 59529 , SPELL_TEMPER = 52238 ,
SPELL_TEMPER_DUMMY = 52654 , SPELL_SUMMON_MOLTEN_GOLEM = 52405 , SPELL_BLAST_WAVE = 23113 , SPELL_IMMOLATION_STRIKE = 52433 ,
SPELL_IMMOLATION_STRIKE_H = 59530 , SPELL_SHATTER = 52429 , SPELL_SHATTER_H = 59527 , SPELL_COOL_DOWN = 52441 ,
NPC_MOLTEN_GOLEM = 28695 , NPC_BRITTLE_GOLEM = 28681 , MAX_GOLEM = 2 , MAX_ACHIEV_GOLEMS = 4
}
Functions
bool EffectDummyCreature_boss_volkhan (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectDummyCreature_npc_volkhan_anvil (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_boss_volkhan ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_SLAY_3
SAY_DEATH
SAY_STOMP_1
SAY_STOMP_2
SAY_FORGE_1
SAY_FORGE_2
EMOTE_TO_ANVIL
EMOTE_SHATTER
SPELL_HEAT
SPELL_HEAT_H
SPELL_SHATTERING_STOMP
SPELL_SHATTERING_STOMP_H
SPELL_TEMPER
SPELL_TEMPER_DUMMY
SPELL_SUMMON_MOLTEN_GOLEM
SPELL_BLAST_WAVE
SPELL_IMMOLATION_STRIKE
SPELL_IMMOLATION_STRIKE_H
SPELL_SHATTER
SPELL_SHATTER_H
SPELL_COOL_DOWN
NPC_MOLTEN_GOLEM
NPC_BRITTLE_GOLEM
MAX_GOLEM
MAX_ACHIEV_GOLEMS
Definition at line 27 of file boss_volkhan.cpp.
Function Documentation
AddSC_boss_volkhan()
void AddSC_boss_volkhan ()
Definition at line 408 of file boss_volkhan.cpp.
References EffectDummyCreature_boss_volkhan(), EffectDummyCreature_npc_volkhan_anvil(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_boss_volkhan()
bool EffectDummyCreature_boss_volkhan (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 272 of file boss_volkhan.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), MAX_GOLEM, NPC_VOLKHAN, NPC_VOLKHAN_ANVIL, SPELL_SUMMON_MOLTEN_GOLEM, SPELL_TEMPER_DUMMY, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_volkhan().
EffectDummyCreature_npc_volkhan_anvil()
bool EffectDummyCreature_npc_volkhan_anvil (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 294 of file boss_volkhan.cpp.
References Unit::CastSpell(), MotionMaster::Clear(), EFFECT_INDEX_0, Object::GetEntry(), Unit::GetMotionMaster(), Unit::GetVictim(), MotionMaster::MoveChase(), NPC_VOLKHAN, NPC_VOLKHAN_ANVIL, SPELL_TEMPER, SPELL_TEMPER_DUMMY, and TRIGGERED_NONE.
Referenced by AddSC_boss_volkhan().