CMaNGOS_WoTLK: boss_razorscale.cpp File Reference
boss_razorscale.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_razorscaleAI
struct npc_expedition_commanderAI
struct npc_razorscale_spawnerAI
struct npc_harpoon_fire_stateAI
Enumerations
enum {
SAY_INTRO_WELCOME = -1603036 , SAY_INTRO_1 = -1603037 , SAY_INTRO_2 = -1603038 , SAY_INTRO_3 = -1603039 ,
SAY_GROUNDED = -1603040 , SAY_EXTINGUISH_FIRE = -1603042 , EMOTE_BREATH = -1603041 , EMOTE_HARPOON_READY = -1603043 ,
EMOTE_GROUNDED = -1603044 , SPELL_BERSERK = 47008 , SPELL_DEVOURING_FLAME = 63236 , SPELL_FLAME_BREATH = 63317 ,
SPELL_FLAME_BREATH_H = 64021 , SPELL_FIREBALL = 62796 , SPELL_FIREBALL_H = 63815 , SPELL_STUN = 62794 ,
SPELL_THREAT = 65146 , SPELL_SHACKLE = 62646 , SPELL_WING_BUFFET = 62666 , SPELL_FIREBOLT = 62669 ,
SPELL_HARPOON_FIRE = 62696 , SPELL_FLAME_BUFFET = 64016 , SPELL_FLAME_BUFFET_H = 64023 , SPELL_FUSE_ARMOR = 64771 ,
SPELL_DEVOURING_FLAME_AURA = 64709 , SPELL_DEVOURING_FLAME_AURA_H = 64734 , SPELL_SUMMON_DWARF_WATCHER = 63135 , SPELL_SUMMON_DWARF_GUARDIAN = 62926 ,
SPELL_SUMMON_IRON_VRYKUL = 63798 , SPELL_SUMMON_MOLE_MACHINE = 62899 , NPC_DEVOURING_FLAME = 34188 , NPC_RAZORSCALE_SPAWNER = 33245 ,
NPC_HARPOON_FIRE_STATE = 33282 , SPEED_RATE_RAZORSCALE = 10 , SPEED_RATE_HELPERS = 8 , GOSSIP_ITEM_START_RAZORSCALE = -3603009 ,
GOSSIP_MENU_ID_WELCOME = 14317 , PHASE_AIR = 1 , PHASE_GROUNDED = 2 , PHASE_ONLY_GROUND = 3 ,
PHASE_TRANSITION = 4
}
Functions
UnitAI * GetAI_boss_razorscale (Creature *pCreature)
UnitAI * GetAI_npc_expedition_commander (Creature *pCreature)
bool GossipHello_npc_expedition_commander (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_expedition_commander (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_razorscale_spawner (Creature *pCreature)
UnitAI * GetAI_npc_harpoon_fire_state (Creature *pCreature)
bool EffectDummyCreature_npc_harpoon_fire_state (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool ProcessEventId_event_spell_harpoon_shot (uint32, Object *pSource, Object *, bool)
void AddSC_boss_razorscale ()
Variables
static const DialogueEntry aIntroDialogue []
static const float afRazorscaleGroundPos [3] = { 585.401f, -173.543f, 391.6421f }
static const float afRazorscaleSpawnersPos [3][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO_WELCOME
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_GROUNDED
SAY_EXTINGUISH_FIRE
EMOTE_BREATH
EMOTE_HARPOON_READY
EMOTE_GROUNDED
SPELL_BERSERK
SPELL_DEVOURING_FLAME
SPELL_FLAME_BREATH
SPELL_FLAME_BREATH_H
SPELL_FIREBALL
SPELL_FIREBALL_H
SPELL_STUN
SPELL_THREAT
SPELL_SHACKLE
SPELL_WING_BUFFET
SPELL_FIREBOLT
SPELL_HARPOON_FIRE
SPELL_FLAME_BUFFET
SPELL_FLAME_BUFFET_H
SPELL_FUSE_ARMOR
SPELL_DEVOURING_FLAME_AURA
SPELL_DEVOURING_FLAME_AURA_H
SPELL_SUMMON_DWARF_WATCHER
SPELL_SUMMON_DWARF_GUARDIAN
SPELL_SUMMON_IRON_VRYKUL
SPELL_SUMMON_MOLE_MACHINE
NPC_DEVOURING_FLAME
NPC_RAZORSCALE_SPAWNER
NPC_HARPOON_FIRE_STATE
SPEED_RATE_RAZORSCALE
SPEED_RATE_HELPERS
GOSSIP_ITEM_START_RAZORSCALE
GOSSIP_MENU_ID_WELCOME
PHASE_AIR
PHASE_GROUNDED
PHASE_ONLY_GROUND
PHASE_TRANSITION
Definition at line 27 of file boss_razorscale.cpp.
Function Documentation
AddSC_boss_razorscale()
void AddSC_boss_razorscale ()
Definition at line 912 of file boss_razorscale.cpp.
References EffectDummyCreature_npc_harpoon_fire_state(), Script::GetAI, GetAI_boss_razorscale(), GetAI_npc_expedition_commander(), GetAI_npc_harpoon_fire_state(), GetAI_npc_razorscale_spawner(), GossipHello_npc_expedition_commander(), GossipSelect_npc_expedition_commander(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_harpoon_shot(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_harpoon_fire_state()
bool EffectDummyCreature_npc_harpoon_fire_state (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 856 of file boss_razorscale.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), Object::GetEntry(), GO_BROKEN_HARPOON, GO_HARPOON_GUN_1, GO_HARPOON_GUN_2, GO_HARPOON_GUN_3, GO_HARPOON_GUN_4, GO_JUST_DEACTIVATED, NPC_HARPOON_FIRE_STATE, NPC_RAZORSCALE_CONTROLLER, GameObject::SetLootState(), SPELL_FIREBOLT, SPELL_HARPOON_FIRE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_razorscale().
GetAI_boss_razorscale()
UnitAI* GetAI_boss_razorscale (Creature * pCreature)
Definition at line 643 of file boss_razorscale.cpp.
Referenced by AddSC_boss_razorscale().
GetAI_npc_expedition_commander()
UnitAI* GetAI_npc_expedition_commander (Creature * pCreature)
Definition at line 744 of file boss_razorscale.cpp.
Referenced by AddSC_boss_razorscale().
GetAI_npc_harpoon_fire_state()
UnitAI* GetAI_npc_harpoon_fire_state (Creature * pCreature)
Definition at line 851 of file boss_razorscale.cpp.
Referenced by AddSC_boss_razorscale().
GetAI_npc_razorscale_spawner()
UnitAI* GetAI_npc_razorscale_spawner (Creature * pCreature)
Definition at line 831 of file boss_razorscale.cpp.
Referenced by AddSC_boss_razorscale().
GossipHello_npc_expedition_commander()
bool GossipHello_npc_expedition_commander (Player * pPlayer, Creature * pCreature)
Definition at line 749 of file boss_razorscale.cpp.
References FAIL, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_START_RAZORSCALE, GOSSIP_MENU_ID_WELCOME, GOSSIP_SENDER_MAIN, NOT_STARTED, and TYPE_RAZORSCALE.
Referenced by AddSC_boss_razorscale().
GossipSelect_npc_expedition_commander()
bool GossipSelect_npc_expedition_commander (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 763 of file boss_razorscale.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, GOSSIP_ACTION_INFO_DEF, Object::RemoveFlag(), UnitAI::SendAIEvent(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_boss_razorscale().
ProcessEventId_event_spell_harpoon_shot()
bool ProcessEventId_event_spell_harpoon_shot (uint32 , Object * pSource, Object * , bool)
Definition at line 895 of file boss_razorscale.cpp.
References AI_EVENT_CUSTOM_B, NPC_RAZORSCALE, and NPC_RAZORSCALE_CONTROLLER.
Referenced by AddSC_boss_razorscale().
Variable Documentation
afRazorscaleGroundPos
const float afRazorscaleGroundPos[3] = { 585.401f, -173.543f, 391.6421f } static
Definition at line 110 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI::ReceiveAIEvent().
afRazorscaleSpawnersPos
const float afRazorscaleSpawnersPos[3][3] static
Initial value:
=
{
    {577.103f, -231.223f, 391.180f},
    {606.138f, -231.266f, 391.517f},
    {589.451f, -209.737f, 391.517f},
}
Definition at line 112 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI::DoSpawnMoleMachines().
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {NPC_EXPEDITION_ENGINEER,   0,                          3000},
    {SAY_INTRO_2,               NPC_EXPEDITION_COMMANDER,   4000},
    {NPC_RAZORSCALE,            0,                          25000},
    {NPC_EXPEDITION_DEFENDER,   0,                          0},
    {0, 0, 0},
}
Definition at line 101 of file boss_razorscale.cpp.