CMaNGOS_WoTLK: boss_hodir.cpp File Reference
boss_hodir.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct boss_hodirAI
struct npc_flash_freezeAI
struct npc_icicle_targetAI
Enumerations
enum {
SAY_AGGRO = -1603086 , SAY_SLAY_1 = -1603087 , SAY_SLAY_2 = -1603088 , SAY_FLASH_FREEZE = -1603089 ,
SAY_FROZEN_BLOWS = -1603090 , SAY_EPILOGUE = -1603091 , SAY_BERSERK = -1603092 , EMOTE_FLASH_FREEZE = -1603094 ,
EMOTE_FROZEN_BLOWS = -1603095 , SPELL_BERSERK = 26662 , SPELL_HODIR_CREDIT = 64899 , SPELL_SHATTER_CHEST = 65272 ,
SPELL_FROZEN_BLOWS = 62478 , SPELL_FROZEN_BLOWS_H = 63512 , SPELL_FREEZE = 62469 , SPELL_BITTING_COLD = 62038 ,
SPELL_ICICLE_AURA = 62227 , SPELL_ICICLE_SNOWPACK = 62476 , SPELL_ICICLE_SNOWPACK_H = 62477 , SPELL_FLASH_FREEZE = 61968 ,
SPELL_ICICLE = 62236 , SPELL_ICICLE_DUMMY = 62453 , SPELL_SAFE_AREA = 65705 , SPELL_FLASH_FREEZE_AURA = 61969 ,
SPELL_FLASH_FREEZE_KILL = 62226 , SPELL_FLASH_FREEZE_AURA_NPC = 61990 , SPELL_FLASH_FREEZE_INITIAL = 62878 , NPC_ICICLE = 33169 ,
NPC_FLASH_FREEZE = 32926 , NPC_FLASH_FREEZE_NPC = 32938 , EVENT_ID_ATTACK_START = 21045 , EVENT_ID_SHATTER_CHEST = 20907 ,
FACTION_ID_FRIENDLY = 35
}
Functions
UnitAI * GetAI_boss_hodir (Creature *pCreature)
UnitAI * GetAI_npc_flash_freeze (Creature *pCreature)
bool ProcessEventId_event_boss_hodir (uint32 uiEventId, Object *pSource, Object *, bool)
UnitAI * GetAI_npc_icicle_target (Creature *pCreature)
void AddSC_boss_hodir ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_FLASH_FREEZE
SAY_FROZEN_BLOWS
SAY_EPILOGUE
SAY_BERSERK
EMOTE_FLASH_FREEZE
EMOTE_FROZEN_BLOWS
SPELL_BERSERK
SPELL_HODIR_CREDIT
SPELL_SHATTER_CHEST
SPELL_FROZEN_BLOWS
SPELL_FROZEN_BLOWS_H
SPELL_FREEZE
SPELL_BITTING_COLD
SPELL_ICICLE_AURA
SPELL_ICICLE_SNOWPACK
SPELL_ICICLE_SNOWPACK_H
SPELL_FLASH_FREEZE
SPELL_ICICLE
SPELL_ICICLE_DUMMY
SPELL_SAFE_AREA
SPELL_FLASH_FREEZE_AURA
SPELL_FLASH_FREEZE_KILL
SPELL_FLASH_FREEZE_AURA_NPC
SPELL_FLASH_FREEZE_INITIAL
NPC_ICICLE
NPC_FLASH_FREEZE
NPC_FLASH_FREEZE_NPC
EVENT_ID_ATTACK_START
EVENT_ID_SHATTER_CHEST
FACTION_ID_FRIENDLY
Definition at line 28 of file boss_hodir.cpp.
Function Documentation
AddSC_boss_hodir()
void AddSC_boss_hodir ()
Definition at line 451 of file boss_hodir.cpp.
References Script::GetAI, GetAI_boss_hodir(), GetAI_npc_flash_freeze(), GetAI_npc_icicle_target(), Script::Name, Script::pProcessEventId, ProcessEventId_event_boss_hodir(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_hodir()
UnitAI* GetAI_boss_hodir (Creature * pCreature)
Definition at line 302 of file boss_hodir.cpp.
Referenced by AddSC_boss_hodir().
GetAI_npc_flash_freeze()
UnitAI* GetAI_npc_flash_freeze (Creature * pCreature)
Definition at line 383 of file boss_hodir.cpp.
Referenced by AddSC_boss_hodir().
GetAI_npc_icicle_target()
UnitAI* GetAI_npc_icicle_target (Creature * pCreature)
Definition at line 446 of file boss_hodir.cpp.
Referenced by AddSC_boss_hodir().
ProcessEventId_event_boss_hodir()
bool ProcessEventId_event_boss_hodir (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 392 of file boss_hodir.cpp.
References EVENT_ID_ATTACK_START, EVENT_ID_SHATTER_CHEST, FACTION_ID_FRIENDLY, FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), Object::GetTypeId(), GO_CACHE_OF_RARE_WINTER_10, GO_CACHE_OF_RARE_WINTER_25, GO_JUST_DEACTIVATED, InstanceData::instance, Map::IsRegularDifficulty(), NPC_HODIR, instance_ulduar::SetData(), TYPE_HODIR_HARD, and TYPEID_UNIT.
Referenced by AddSC_boss_hodir().