CMaNGOS_WoTLK: boss_thaddius.cpp File Reference
boss_thaddius.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/BossAI.h"
#include "naxxramas.h"
Data Structures
struct boss_thaddiusAI
struct ShockThaddius
struct ThaddiusLightningVisual
struct npc_tesla_coilAI
struct boss_thaddiusAddsAI
struct boss_stalaggAI
struct boss_feugenAI
struct MagneticPullThaddius
struct PolarityShift
struct ThaddiusChargeDamage
struct ThaddiusCharge
struct TriggerTeslas
struct ThaddiusTeslaEffect
struct ThaddiusTeslaChain
Enumerations
enum {
SAY_STAL_AGGRO = 13083 , SAY_STAL_SLAY = 13085 , SAY_STAL_DEATH = 12195 , SAY_FEUG_AGGRO = 13023 ,
SAY_FEUG_SLAY = 13025 , SAY_FEUG_DEATH = 12195 , EMOTE_LOSING_LINK = 12156 , EMOTE_TESLA_OVERLOAD = 12178 ,
SAY_AGGRO_1 = 13086 , SAY_AGGRO_2 = 13087 , SAY_AGGRO_3 = 13088 , SAY_SLAY = 13096 ,
SAY_ELECT = 13090 , SAY_DEATH = 13089 , EMOTE_POLARITY_SHIFT = 32324 , SPELL_THADIUS_SPAWN = 28160 ,
SPELL_THADIUS_LIGHTNING_VISUAL = 28136 , SPELL_BALL_LIGHTNING = 28299 , SPELL_CHAIN_LIGHTNING = 28167 , SPELL_CHAIN_LIGHTNING_H = 54531 ,
SPELL_POLARITY_SHIFT = 28089 , SPELL_POSITIVE_CHARGE = 28059 , SPELL_NEGATIVE_CHARGE = 28084 , SPELL_POSITIVE_CHARGE_BUFF = 29659 ,
SPELL_NEGATIVE_CHARGE_BUFF = 29660 , SPELL_POSITIVE_CHARGE_DAMAGE = 28062 , SPELL_NEGATIVE_CHARGE_DAMAGE = 28085 , SPELL_BESERK = 27680 ,
SPELL_CLEAR_CHARGES = 63133 , SPELL_MAGNETIC_PULL_A = 28338 , SPELL_MAGNETIC_PULL_B = 54517 , SPELL_MAGNETIC_PULL_EFFECT = 30010 ,
SPELL_STATIC_FIELD = 28135 , SPELL_STATIC_FIELD_H = 54528 , SPELL_POWERSURGE_H = 28134 , SPELL_POWERSURGE = 54529 ,
SPELL_FEUGEN_CHAIN = 28111 , SPELL_STALAGG_CHAIN = 28096 , SPELL_FEUGEN_TESLA_PASSIVE = 28109 , SPELL_STALAGG_TESLA_PASSIVE = 28097 ,
SPELL_FEUGEN_TESLA_EFFECT = 28110 , SPELL_STALAGG_TESLA_EFFECT = 28098 , SPELL_SHOCK_OVERLOAD = 28159 , SPELL_SHOCK = 28099 ,
SPELL_TRIGGER_TESLAS = 28359
}
enum ThaddiusActions { THADDIUS_BALL_LIGHTNING , THADDIUS_ACTIONS_MAX }
enum TeslaCoilActions { TESLA_COIL_SETUP_CHAIN }
enum ThaddiusAddActions { THADDIUS_ADD_ACTIONS_MAX , THADDIUS_ADD_REVIVE , THADDIUS_ADD_SHOCK_OVERLOAD , THADDIUS_ADD_HOLD }
Functions
bool EffectDummyNPC_spell_thaddius_encounter (Unit *, uint32 spellId, SpellEffectIndex uiEffIndex, Creature *creatureTarget, ObjectGuid)
void AddSC_boss_thaddius ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_STAL_AGGRO
SAY_STAL_SLAY
SAY_STAL_DEATH
SAY_FEUG_AGGRO
SAY_FEUG_SLAY
SAY_FEUG_DEATH
EMOTE_LOSING_LINK
EMOTE_TESLA_OVERLOAD
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_SLAY
SAY_ELECT
SAY_DEATH
EMOTE_POLARITY_SHIFT
SPELL_THADIUS_SPAWN
SPELL_THADIUS_LIGHTNING_VISUAL
SPELL_BALL_LIGHTNING
SPELL_CHAIN_LIGHTNING
SPELL_CHAIN_LIGHTNING_H
SPELL_POLARITY_SHIFT
SPELL_POSITIVE_CHARGE
SPELL_NEGATIVE_CHARGE
SPELL_POSITIVE_CHARGE_BUFF
SPELL_NEGATIVE_CHARGE_BUFF
SPELL_POSITIVE_CHARGE_DAMAGE
SPELL_NEGATIVE_CHARGE_DAMAGE
SPELL_BESERK
SPELL_CLEAR_CHARGES
SPELL_MAGNETIC_PULL_A
SPELL_MAGNETIC_PULL_B
SPELL_MAGNETIC_PULL_EFFECT
SPELL_STATIC_FIELD
SPELL_STATIC_FIELD_H
SPELL_POWERSURGE_H
SPELL_POWERSURGE
SPELL_FEUGEN_CHAIN
SPELL_STALAGG_CHAIN
SPELL_FEUGEN_TESLA_PASSIVE
SPELL_STALAGG_TESLA_PASSIVE
SPELL_FEUGEN_TESLA_EFFECT
SPELL_STALAGG_TESLA_EFFECT
SPELL_SHOCK_OVERLOAD
SPELL_SHOCK
SPELL_TRIGGER_TESLAS
Definition at line 35 of file boss_thaddius.cpp.
TeslaCoilActions
enum TeslaCoilActions
Enumerator
TESLA_COIL_SETUP_CHAIN
Definition at line 268 of file boss_thaddius.cpp.
ThaddiusActions
enum ThaddiusActions
Enumerator
THADDIUS_BALL_LIGHTNING
THADDIUS_ACTIONS_MAX
Definition at line 101 of file boss_thaddius.cpp.
ThaddiusAddActions
enum ThaddiusAddActions
Enumerator
THADDIUS_ADD_ACTIONS_MAX
THADDIUS_ADD_REVIVE
THADDIUS_ADD_SHOCK_OVERLOAD
THADDIUS_ADD_HOLD
Definition at line 321 of file boss_thaddius.cpp.
Function Documentation
AddSC_boss_thaddius()
void AddSC_boss_thaddius ()
Definition at line 761 of file boss_thaddius.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyNPC_spell_thaddius_encounter()
bool EffectDummyNPC_spell_thaddius_encounter (Unit * , uint32 spellId, SpellEffectIndex uiEffIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 244 of file boss_thaddius.cpp.
References EFFECT_INDEX_0, Object::GetEntry(), NPC_THADDIUS, SPELL_SHOCK_OVERLOAD, and SPELL_THADIUS_LIGHTNING_VISUAL.