CMaNGOS_WoTLK: boss_kaelthas.cpp File Reference
boss_kaelthas.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "the_eye.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_kaelthasAI
struct advisor_base_ai
struct boss_thaladred_the_darkenerAI
struct boss_lord_sanguinarAI
struct boss_grand_astromancer_capernianAI
struct boss_master_engineer_telonicusAI
struct npc_nether_vaporAI
struct NetherVaporLightning
struct NetherVaporSummon
struct NetherVaporSummonParent
struct RemoveWeapons
struct GravityLapseKnockup
Enumerations
enum {
SAY_INTRO = -1550016 , SAY_INTRO_CAPERNIAN = -1550017 , SAY_INTRO_TELONICUS = -1550018 , SAY_INTRO_THALADRED = -1550019 ,
SAY_INTRO_SANGUINAR = -1550020 , SAY_PHASE2_WEAPON = -1550021 , SAY_PHASE3_ADVANCE = -1550022 , SAY_PHASE4_INTRO2 = -1550023 ,
SAY_PHASE5_NUTS = -1550024 , SAY_SLAY1 = -1550025 , SAY_SLAY2 = -1550026 , SAY_SLAY3 = -1550027 ,
SAY_MINDCONTROL1 = -1550028 , SAY_MINDCONTROL2 = -1550029 , SAY_GRAVITYLAPSE1 = -1550030 , SAY_GRAVITYLAPSE2 = -1550031 ,
SAY_SUMMON_PHOENIX1 = -1550032 , SAY_SUMMON_PHOENIX2 = -1550033 , SAY_DEATH = -1550034 , EMOTE_PYROBLAST = -1550044 ,
SAY_THALADRED_AGGRO = -1550035 , SAY_THALADRED_DEATH = -1550036 , EMOTE_THALADRED_GAZE = -1550037 , SAY_SANGUINAR_AGGRO = -1550038 ,
SAY_SANGUINAR_DEATH = -1550039 , SAY_CAPERNIAN_AGGRO = -1550040 , SAY_CAPERNIAN_DEATH = -1550041 , SAY_TELONICUS_AGGRO = -1550042 ,
SAY_TELONICUS_DEATH = -1550043 , SPELL_KAEL_PHASE_2 = 36709 , SPELL_SUMMON_WEAPONS = 36976 , SPELL_SUMMON_WEAPONA = 36958 ,
SPELL_SUMMON_WEAPONB = 36959 , SPELL_SUMMON_WEAPONC = 36960 , SPELL_SUMMON_WEAPOND = 36961 , SPELL_SUMMON_WEAPONE = 36962 ,
SPELL_SUMMON_WEAPONF = 36963 , SPELL_SUMMON_WEAPONG = 36964 , SPELL_RESURRECTION = 36450 , SPELL_FIREBALL = 36805 ,
SPELL_PYROBLAST = 36819 , SPELL_FLAME_STRIKE = 36735 , SPELL_FLAME_STRIKE_DUMMY = 36730 , SPELL_ARCANE_DISRUPTION = 36834 ,
SPELL_SHOCK_BARRIER = 36815 , SPELL_PHOENIX_ANIMATION = 36723 , SPELL_MIND_CONTROL = 36797 , SPELL_MIND_CONTROL2 = 36798 ,
SPELL_NETHERBEAM_EXPLODE = 36089 , SPELL_NETHERBEAM = 36090 , SPELL_KAEL_GAIN_POWER = 36091 , SPELL_EXPLODE = 36092 ,
SPELL_KAEL_STUN = 36185 , SPELL_KAEL_FULL_POWER = 36187 , SPELL_PURE_NETHER_BEAM1 = 36196 , SPELL_PURE_NETHER_BEAM2 = 36197 ,
SPELL_PURE_NETHER_BEAM3 = 36198 , SPELL_PURE_NETHER_BEAM4 = 36201 , SPELL_PURE_NETHER_BEAM5 = 36290 , SPELL_PURE_NETHER_BEAM6 = 36291 ,
SPELL_NETHERBEAM_GLOW1 = 36364 , SPELL_NETHERBEAM_GLOW2 = 36370 , SPELL_NETHERBEAM_GLOW3 = 36371 , SPELL_EXPLODE_1 = 36354 ,
SPELL_EXPLODE_2 = 36373 , SPELL_EXPLODE_3 = 36375 , SPELL_EXPLODE_4 = 36376 , SPELL_FLOATING_DROWNED = 36550 ,
SPELL_GRAVITY_LAPSE = 35941 , SPELL_GRAVITY_LAPSE_KNOCKBACK = 34480 , SPELL_GRAVITY_LAPSE_AURA = 39432 , SPELL_NETHER_BEAM = 35869 ,
SPELL_NETHER_BEAM_DAMAGE = 35873 , SPELL_NETHER_VAPOR_SUMMON = 35865 , SPELL_NETHER_VAPOR_PERIODIC_DAMAGE = 35858 , SPELL_NETHER_VAPOR_PERIODIC_SCRIPT = 35879 ,
SPELL_NETHER_VAPOR_SUMMON_1 = 35861 , SPELL_NETHER_VAPOR_SUMMON_2 = 35862 , SPELL_NETHER_VAPOR_SUMMON_3 = 35863 , SPELL_NETHER_VAPOR_SUMMON_4 = 35864 ,
SPELL_NETHER_VAPOR_LIGHTNING = 45960 , SPELL_ASTRAL_STORM = 45959 , SPELL_REMOVE_WEAPONS = 39497 , SPELL_PSYCHIC_BLOW = 36966 ,
SPELL_SILENCE = 30225 , SPELL_REND = 36965 , SPELL_THRASH = 8876 , SPELL_BELLOWING_ROAR = 44863 ,
SPELL_CAPERNIAN_FIREBALL = 36971 , SPELL_CONFLAGRATION = 37018 , SPELL_ARCANE_BURST = 36970 , SPELL_BOMB = 37036 ,
SPELL_REMOTE_TOY = 37027 , SPELL_SHOOT = 16496 , SPELL_PERMANENT_FEIGN_DEATH = 29266 , SPELL_BANISH = 40370 ,
NPC_FLAME_STRIKE_TRIGGER = 21369 , NPC_PHOENIX = 21362 , NPC_PHOENIX_EGG = 21364 , NPC_NETHER_VAPOR = 21002 ,
PHASE_0_NOT_BEGUN = 0 , PHASE_1_ADVISOR = 1 , PHASE_2_WEAPON = 2 , PHASE_3_ADVISOR_ALL = 3 ,
PHASE_4_SOLO = 4 , PHASE_5_GRAVITY = 5 , PHASE_TRANSITION = 6 , POINT_ID_CENTER = 1 ,
POINT_ID_AIR = 2 , POINT_ID_LAND = 3 , SOUND_PHASE_TRANSITION1 = 27 , SOUND_PHASE_TRANSITION2 = 1136 ,
SOUND_PHASE_TRANSITION3 = 6477 , SOUND_PHASE_TRANSITION4 = 44 , VISUAL_PHASE_TRANSITION1 = 7234 , VISUAL_PHASE_TRANSITION2 = 7235 ,
MAX_WEAPONS = 7 , MAX_MIND_CONTROL = 3
}
enum TriggerData {
TRIGGERS_FIRST_STAGE = 6 , TRIGGERS_EXPLOSION = 6 , TRIGGERS_SECOND_STAGE = 13 , TRIGGERS_TOTAL = 25 ,
TRIGGERS_GROUP_ONE = 6 , TRIGGERS_GROUP_TWO = 4 , TRIGGERS_GROUP_THREE = 3
}
enum KaelThasActions {
KAEL_ACTION_PYROBLAST_SEQUENCE , KAEL_ACTION_NETHER_VAPOR , KAEL_ACTION_NETHER_BEAM , KAEL_ACTION_PHASE_5 ,
KAEL_ACTION_PHOENIX , KAEL_ACTION_FLAMESTRIKE , KAEL_ACTION_ARCANE_DISRUPTION , KAEL_ACTION_SHOCK_BARRIER ,
KAEL_ACTION_GRAVITY_LAPSE , KAEL_ACTION_MIND_CONTROL , KAEL_ACTION_PYROBLAST_INIT , KAEL_ACTION_MELEE_MODE ,
KAEL_ACTION_FIREBALL , KAEL_ACTION_MAX
}
Functions
bool EffectDummyCreature_kael_phase_2 (Unit *caster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *creatureTarget, ObjectGuid)
void AddSC_boss_kaelthas ()
Variables
static const uint32 m_auiSpellSummonWeapon [MAX_WEAPONS]
static const uint32 m_auiSpellGravityLapseTeleport []
static const float aCenterPos [3] = { 796.641f, -0.588817f, 48.72847f}
static const float flightPos [3] = { 795.007f, -0.471827f, 75.f }
static const float landPos [3] = { 792.419f, -0.504778f, 50.0505f }
static const uint32 triggerSpellIds [13] = { 36201, 36201, 36201, 36290, 36290, 36290, 36290, 36290, 36290, 36290, 36291, 36291, 36291}
static const uint32 groupOneIndices [TRIGGERS_GROUP_ONE] = { 0, 1, 4, 7, 8, 9}
static const uint32 groupTwoIndices [TRIGGERS_GROUP_TWO] = { 2, 4, 9, 10}
static const uint32 groupThreeIndices [TRIGGERS_GROUP_THREE] = { 5, 11, 12}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_INTRO_CAPERNIAN
SAY_INTRO_TELONICUS
SAY_INTRO_THALADRED
SAY_INTRO_SANGUINAR
SAY_PHASE2_WEAPON
SAY_PHASE3_ADVANCE
SAY_PHASE4_INTRO2
SAY_PHASE5_NUTS
SAY_SLAY1
SAY_SLAY2
SAY_SLAY3
SAY_MINDCONTROL1
SAY_MINDCONTROL2
SAY_GRAVITYLAPSE1
SAY_GRAVITYLAPSE2
SAY_SUMMON_PHOENIX1
SAY_SUMMON_PHOENIX2
SAY_DEATH
EMOTE_PYROBLAST
SAY_THALADRED_AGGRO
SAY_THALADRED_DEATH
EMOTE_THALADRED_GAZE
SAY_SANGUINAR_AGGRO
SAY_SANGUINAR_DEATH
SAY_CAPERNIAN_AGGRO
SAY_CAPERNIAN_DEATH
SAY_TELONICUS_AGGRO
SAY_TELONICUS_DEATH
SPELL_KAEL_PHASE_2
SPELL_SUMMON_WEAPONS
SPELL_SUMMON_WEAPONA
SPELL_SUMMON_WEAPONB
SPELL_SUMMON_WEAPONC
SPELL_SUMMON_WEAPOND
SPELL_SUMMON_WEAPONE
SPELL_SUMMON_WEAPONF
SPELL_SUMMON_WEAPONG
SPELL_RESURRECTION
SPELL_FIREBALL
SPELL_PYROBLAST
SPELL_FLAME_STRIKE
SPELL_FLAME_STRIKE_DUMMY
SPELL_ARCANE_DISRUPTION
SPELL_SHOCK_BARRIER
SPELL_PHOENIX_ANIMATION
SPELL_MIND_CONTROL
SPELL_MIND_CONTROL2
SPELL_NETHERBEAM_EXPLODE
SPELL_NETHERBEAM
SPELL_KAEL_GAIN_POWER
SPELL_EXPLODE
SPELL_KAEL_STUN
SPELL_KAEL_FULL_POWER
SPELL_PURE_NETHER_BEAM1
SPELL_PURE_NETHER_BEAM2
SPELL_PURE_NETHER_BEAM3
SPELL_PURE_NETHER_BEAM4
SPELL_PURE_NETHER_BEAM5
SPELL_PURE_NETHER_BEAM6
SPELL_NETHERBEAM_GLOW1
SPELL_NETHERBEAM_GLOW2
SPELL_NETHERBEAM_GLOW3
SPELL_EXPLODE_1
SPELL_EXPLODE_2
SPELL_EXPLODE_3
SPELL_EXPLODE_4
SPELL_FLOATING_DROWNED
SPELL_GRAVITY_LAPSE
SPELL_GRAVITY_LAPSE_KNOCKBACK
SPELL_GRAVITY_LAPSE_AURA
SPELL_NETHER_BEAM
SPELL_NETHER_BEAM_DAMAGE
SPELL_NETHER_VAPOR_SUMMON
SPELL_NETHER_VAPOR_PERIODIC_DAMAGE
SPELL_NETHER_VAPOR_PERIODIC_SCRIPT
SPELL_NETHER_VAPOR_SUMMON_1
SPELL_NETHER_VAPOR_SUMMON_2
SPELL_NETHER_VAPOR_SUMMON_3
SPELL_NETHER_VAPOR_SUMMON_4
SPELL_NETHER_VAPOR_LIGHTNING
SPELL_ASTRAL_STORM
SPELL_REMOVE_WEAPONS
SPELL_PSYCHIC_BLOW
SPELL_SILENCE
SPELL_REND
SPELL_THRASH
SPELL_BELLOWING_ROAR
SPELL_CAPERNIAN_FIREBALL
SPELL_CONFLAGRATION
SPELL_ARCANE_BURST
SPELL_BOMB
SPELL_REMOTE_TOY
SPELL_SHOOT
SPELL_PERMANENT_FEIGN_DEATH
SPELL_BANISH
NPC_FLAME_STRIKE_TRIGGER
NPC_PHOENIX
NPC_PHOENIX_EGG
NPC_NETHER_VAPOR
PHASE_0_NOT_BEGUN
PHASE_1_ADVISOR
PHASE_2_WEAPON
PHASE_3_ADVISOR_ALL
PHASE_4_SOLO
PHASE_5_GRAVITY
PHASE_TRANSITION
POINT_ID_CENTER
POINT_ID_AIR
POINT_ID_LAND
SOUND_PHASE_TRANSITION1
SOUND_PHASE_TRANSITION2
SOUND_PHASE_TRANSITION3
SOUND_PHASE_TRANSITION4
VISUAL_PHASE_TRANSITION1
VISUAL_PHASE_TRANSITION2
MAX_WEAPONS
MAX_MIND_CONTROL
Definition at line 33 of file boss_kaelthas.cpp.
KaelThasActions
enum KaelThasActions
Enumerator
KAEL_ACTION_PYROBLAST_SEQUENCE
KAEL_ACTION_NETHER_VAPOR
KAEL_ACTION_NETHER_BEAM
KAEL_ACTION_PHASE_5
KAEL_ACTION_PHOENIX
KAEL_ACTION_FLAMESTRIKE
KAEL_ACTION_ARCANE_DISRUPTION
KAEL_ACTION_SHOCK_BARRIER
KAEL_ACTION_GRAVITY_LAPSE
KAEL_ACTION_MIND_CONTROL
KAEL_ACTION_PYROBLAST_INIT
KAEL_ACTION_MELEE_MODE
KAEL_ACTION_FIREBALL
KAEL_ACTION_MAX
Definition at line 241 of file boss_kaelthas.cpp.
TriggerData
enum TriggerData
Enumerator
TRIGGERS_FIRST_STAGE
TRIGGERS_EXPLOSION
TRIGGERS_SECOND_STAGE
TRIGGERS_TOTAL
TRIGGERS_GROUP_ONE
TRIGGERS_GROUP_TWO
TRIGGERS_GROUP_THREE
Definition at line 217 of file boss_kaelthas.cpp.
Function Documentation
AddSC_boss_kaelthas()
void AddSC_boss_kaelthas ()
Definition at line 1931 of file boss_kaelthas.cpp.
References EffectDummyCreature_kael_phase_2(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_kael_phase_2()
bool EffectDummyCreature_kael_phase_2 (Unit * caster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 1345 of file boss_kaelthas.cpp.
References Creature::AI(), EFFECT_INDEX_0, Object::GetEntry(), and SPELL_KAEL_PHASE_2.
Referenced by AddSC_boss_kaelthas().
Variable Documentation
aCenterPos
const float aCenterPos[3] = { 796.641f, -0.588817f, 48.72847f} static
Definition at line 213 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::ExecuteActions().
flightPos
const float flightPos[3] = { 795.007f, -0.471827f, 75.f } static
Definition at line 214 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().
groupOneIndices
const uint32 groupOneIndices[TRIGGERS_GROUP_ONE] = { 0, 1, 4, 7, 8, 9} static
Definition at line 233 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().
groupThreeIndices
const uint32 groupThreeIndices[TRIGGERS_GROUP_THREE] = { 5, 11, 12} static
Definition at line 235 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().
groupTwoIndices
const uint32 groupTwoIndices[TRIGGERS_GROUP_TWO] = { 2, 4, 9, 10} static
Definition at line 234 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().
landPos
const float landPos[3] = { 792.419f, -0.504778f, 50.0505f } static
Definition at line 215 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().
m_auiSpellGravityLapseTeleport
const uint32 m_auiSpellGravityLapseTeleport[] static
Initial value:
=
{
    35966, 35967, 35968, 35969, 35970, 35971, 35972, 35973, 35974, 35975, 35976, 35977, 35978, 35979, 35980,
    35981, 35982, 35983, 35984, 35985, 35986, 35987, 35988, 35989, 35990
}
Definition at line 207 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::SpellHitTarget().
m_auiSpellSummonWeapon
const uint32 m_auiSpellSummonWeapon[MAX_WEAPONS] static
Initial value:
=
{
    SPELL_SUMMON_WEAPONA, SPELL_SUMMON_WEAPONB, SPELL_SUMMON_WEAPONC, SPELL_SUMMON_WEAPOND,
    SPELL_SUMMON_WEAPONE, SPELL_SUMMON_WEAPONF, SPELL_SUMMON_WEAPONG
}
Definition at line 200 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::SpellHit().
triggerSpellIds
const uint32 triggerSpellIds[13] = { 36201, 36201, 36201, 36290, 36290, 36290, 36290, 36290, 36290, 36290, 36291, 36291, 36291} static
Definition at line 230 of file boss_kaelthas.cpp.
Referenced by boss_kaelthasAI::UpdateAI().