CMaNGOS_WoTLK: boss_xt_002.cpp File Reference
boss_xt_002.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct boss_xt_002AI
struct boss_heart_deconstructorAI
struct npc_scrapbotAI
struct npc_xt_toy_pileAI
Enumerations
enum {
SAY_AGGRO = -1603045 , SAY_SLAY_1 = -1603046 , SAY_SLAY_2 = -1603047 , SAY_BERSERK = -1603048 ,
SAY_ADDS = -1603049 , SAY_DEATH = -1603050 , SAY_HEART_OPEN = -1603051 , SAY_HEART_CLOSE = -1603052 ,
SAY_TANCTRUM = -1603053 , EMOTE_HEART = -1603054 , EMOTE_REPAIR = -1603055 , EMOTE_KILL_HEART = -1603236 ,
EMOTE_EARTH_QUAKE = -1603237 , SPELL_TYMPANIC_TANTRUM = 62776 , SPELL_SEARING_LIGHT = 63018 , SPELL_SEARING_LIGHT_H = 65121 ,
SPELL_GRAVITY_BOMB = 63024 , SPELL_GRAVITY_BOMB_H = 64234 , SPELL_BERSERK = 26662 , SPELL_HEARTBREAK = 65737 ,
SPELL_HEARTBREAK_H = 64193 , SPELL_VOIDZONE = 64203 , SPELL_VOIDZONE_H = 64235 , SPELL_LIFE_SPARK = 64210 ,
SPELL_HEART_RIDE_VEHICLE = 63852 , SPELL_FULL_HEAL = 17683 , SPELL_RIDE_VEHICLE = 63313 , SPELL_LIGHTNING_TETHER = 64799 ,
SPELL_HEART_OVERLOAD = 62789 , SPELL_EXPOSED_HEART = 63849 , SPELL_ENERGY_ORB = 62790 , SPELL_ENERGY_ORB_DUMMY = 62826 ,
SPELL_RECHARGE_ROBOT_1 = 62828 , SPELL_RECHARGE_ROBOT_2 = 62835 , SPELL_RECHARGE_ROBOT_3 = 62831 , SPELL_CONSUMPTION = 64208 ,
SPELL_ARCANE_POWER_STATE = 49411 , SPELL_STATIC_CHARGED = 64227 , SPELL_STATIC_CHARGED_H = 64236 , SPELL_SCRAP_REPAIR = 62832 ,
SPELL_RIDE_VEHICLE_SCRAPBOT = 47020 , NPC_SCRAPBOT = 33343 , NPC_BOOMBOT = 33346 , NPC_PUMMELLER = 33344 ,
NPC_VOIDZONE = 34001 , NPC_LIFE_SPARK = 34004 , PHASE_NORMAL = 1 , PHASE_TRANSITION = 2 ,
PHASE_HEART = 3 , MAX_SCRAPBOTS = 5
}
Functions
UnitAI * GetAI_boss_xt_002 (Creature *pCreature)
UnitAI * GetAI_boss_heart_deconstructor (Creature *pCreature)
UnitAI * GetAI_npc_scrapbot (Creature *pCreature)
UnitAI * GetAI_npc_xt_toy_pile (Creature *pCreature)
void AddSC_boss_xt_002 ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SLAY_1
SAY_SLAY_2
SAY_BERSERK
SAY_ADDS
SAY_DEATH
SAY_HEART_OPEN
SAY_HEART_CLOSE
SAY_TANCTRUM
EMOTE_HEART
EMOTE_REPAIR
EMOTE_KILL_HEART
EMOTE_EARTH_QUAKE
SPELL_TYMPANIC_TANTRUM
SPELL_SEARING_LIGHT
SPELL_SEARING_LIGHT_H
SPELL_GRAVITY_BOMB
SPELL_GRAVITY_BOMB_H
SPELL_BERSERK
SPELL_HEARTBREAK
SPELL_HEARTBREAK_H
SPELL_VOIDZONE
SPELL_VOIDZONE_H
SPELL_LIFE_SPARK
SPELL_HEART_RIDE_VEHICLE
SPELL_FULL_HEAL
SPELL_RIDE_VEHICLE
SPELL_LIGHTNING_TETHER
SPELL_HEART_OVERLOAD
SPELL_EXPOSED_HEART
SPELL_ENERGY_ORB
SPELL_ENERGY_ORB_DUMMY
SPELL_RECHARGE_ROBOT_1
SPELL_RECHARGE_ROBOT_2
SPELL_RECHARGE_ROBOT_3
SPELL_CONSUMPTION
SPELL_ARCANE_POWER_STATE
SPELL_STATIC_CHARGED
SPELL_STATIC_CHARGED_H
SPELL_SCRAP_REPAIR
SPELL_RIDE_VEHICLE_SCRAPBOT
NPC_SCRAPBOT
NPC_BOOMBOT
NPC_PUMMELLER
NPC_VOIDZONE
NPC_LIFE_SPARK
PHASE_NORMAL
PHASE_TRANSITION
PHASE_HEART
MAX_SCRAPBOTS
Definition at line 27 of file boss_xt_002.cpp.
Function Documentation
AddSC_boss_xt_002()
void AddSC_boss_xt_002 ()
Definition at line 535 of file boss_xt_002.cpp.
References Script::GetAI, GetAI_boss_heart_deconstructor(), GetAI_boss_xt_002(), GetAI_npc_scrapbot(), GetAI_npc_xt_toy_pile(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_heart_deconstructor()
UnitAI* GetAI_boss_heart_deconstructor (Creature * pCreature)
Definition at line 477 of file boss_xt_002.cpp.
Referenced by AddSC_boss_xt_002().
GetAI_boss_xt_002()
UnitAI* GetAI_boss_xt_002 (Creature * pCreature)
Definition at line 362 of file boss_xt_002.cpp.
Referenced by AddSC_boss_xt_002().
GetAI_npc_scrapbot()
UnitAI* GetAI_npc_scrapbot (Creature * pCreature)
Definition at line 510 of file boss_xt_002.cpp.
Referenced by AddSC_boss_xt_002().
GetAI_npc_xt_toy_pile()
UnitAI* GetAI_npc_xt_toy_pile (Creature * pCreature)
Definition at line 530 of file boss_xt_002.cpp.
Referenced by AddSC_boss_xt_002().