CMaNGOS_WoTLK: boss_thermaplugg.cpp File Reference
boss_thermaplugg.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "gnomeregan.h"
Data Structures
struct boss_thermapluggAI
Enumerations
enum {
SAY_AGGRO = -1090024 , SAY_PHASE = -1090025 , SAY_BOMB = -1090026 , SAY_SLAY = -1090027 ,
SPELL_ACTIVATE_BOMB_A = 11511 , SPELL_ACTIVATE_BOMB_B = 11795 , SPELL_KNOCK_AWAY = 10101 , SPELL_KNOCK_AWAY_AOE = 11130 ,
SPELL_WALKING_BOMB_EFFECT = 11504 , NPC_WALKING_BOMB = 7915
}
Functions
UnitAI * GetAI_boss_thermaplugg (Creature *pCreature)
bool EffectDummyCreature_spell_boss_thermaplugg (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GOUse_go_gnomeface_button (Player *pPlayer, GameObject *pGo)
void AddSC_boss_thermaplugg ()
Variables
static const float fBombSpawnZ = -316.2625f
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_PHASE
SAY_BOMB
SAY_SLAY
SPELL_ACTIVATE_BOMB_A
SPELL_ACTIVATE_BOMB_B
SPELL_KNOCK_AWAY
SPELL_KNOCK_AWAY_AOE
SPELL_WALKING_BOMB_EFFECT
NPC_WALKING_BOMB
Definition at line 27 of file boss_thermaplugg.cpp.
Function Documentation
AddSC_boss_thermaplugg()
void AddSC_boss_thermaplugg ()
Definition at line 267 of file boss_thermaplugg.cpp.
References EffectDummyCreature_spell_boss_thermaplugg(), Script::GetAI, GetAI_boss_thermaplugg(), GOUse_go_gnomeface_button(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_boss_thermaplugg()
bool EffectDummyCreature_spell_boss_thermaplugg (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 235 of file boss_thermaplugg.cpp.
References EFFECT_INDEX_0, WorldObject::GetInstanceData(), MAX_GNOME_FACES, SPELL_ACTIVATE_BOMB_A, SPELL_ACTIVATE_BOMB_B, and urand().
Referenced by AddSC_boss_thermaplugg().
GetAI_boss_thermaplugg()
UnitAI* GetAI_boss_thermaplugg (Creature * pCreature)
Definition at line 230 of file boss_thermaplugg.cpp.
Referenced by AddSC_boss_thermaplugg().
GOUse_go_gnomeface_button()
bool GOUse_go_gnomeface_button (Player * pPlayer, GameObject * pGo)
Definition at line 247 of file boss_thermaplugg.cpp.
References instance_gnomeregan::DoDeactivateBombFace(), Object::GetEntry(), WorldObject::GetInstanceData(), GO_BUTTON_1, GO_BUTTON_2, GO_BUTTON_3, GO_BUTTON_4, GO_BUTTON_5, and GO_BUTTON_6.
Referenced by AddSC_boss_thermaplugg().
Variable Documentation
fBombSpawnZ
const float fBombSpawnZ = -316.2625f static
Definition at line 43 of file boss_thermaplugg.cpp.
Referenced by boss_thermapluggAI::UpdateAI().