CMaNGOS_WoTLK: boss_chrono_lord_deja.cpp File Reference
boss_chrono_lord_deja.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "dark_portal.h"
Data Structures
struct boss_chrono_lord_dejaAI
Enumerations
enum {
SAY_AGGRO = -1269007 , SAY_BANISH = -1269008 , SAY_SLAY1 = -1269009 , SAY_SLAY2 = -1269010 ,
SAY_DEATH = -1269011 , SPELL_ARCANE_BLAST = 31457 , SPELL_ARCANE_BLAST_H = 38538 , SPELL_ARCANE_DISCHARGE = 31472 ,
SPELL_ARCANE_DISCHARGE_H = 38539 , SPELL_TIME_LAPSE = 31467 , SPELL_ATTRACTION = 38540
}
Functions
UnitAI * GetAI_boss_chrono_lord_deja (Creature *pCreature)
void AddSC_boss_chrono_lord_deja ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_BANISH
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SPELL_ARCANE_BLAST
SPELL_ARCANE_BLAST_H
SPELL_ARCANE_DISCHARGE
SPELL_ARCANE_DISCHARGE_H
SPELL_TIME_LAPSE
SPELL_ATTRACTION
Definition at line 27 of file boss_chrono_lord_deja.cpp.
Function Documentation
AddSC_boss_chrono_lord_deja()
void AddSC_boss_chrono_lord_deja ()
Definition at line 152 of file boss_chrono_lord_deja.cpp.
References Script::GetAI, GetAI_boss_chrono_lord_deja(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_chrono_lord_deja()
UnitAI* GetAI_boss_chrono_lord_deja (Creature * pCreature)
Definition at line 147 of file boss_chrono_lord_deja.cpp.
Referenced by AddSC_boss_chrono_lord_deja().