CMaNGOS_WoTLK: boss_coren_direbrew.cpp File Reference
boss_coren_direbrew.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "LFG/LFGDefines.h"
Data Structures
struct boss_coren_direbrewAI
struct RequestSecondMug
struct DirebrewDisarm
struct DirebrewDisarmPrecast
struct SummonMoleMachineTargetPicker
struct SummonDirebrewMinion
Enumerations
enum {
SAY_AGGRO = -1230034 , SPELL_DIREBREW_DISARM = 47310 , SPELL_SUMMON_DIREBREW_MINION = 47375 , SPELL_DIREBREW_CHARGE = 47718 ,
SPELL_SUMMON_MOLE_MACHINE = 47691 , SPELL_SUMMON_MOLE_MACHINE_MINION_SUMMONER = 47690 , SPELL_PORT_TO_COREN = 52850 , SPELL_SEND_SECOND_MUG = 47339 ,
SPELL_DIREBREW_MINION_KNOCKBACK = 50313 , SPELL_DIREBREWS_DISARM_PRECAST = 47407 , SPELL_DIREBREWS_DISARM_GROW = 47409 , NPC_ILSA_DIREBREW = 26764 ,
NPC_URSULA_DIREBREW = 26822 , NPC_DARK_IRON_ANTAGONIST = 23795 , FACTION_HOSTILE = 736 , QUEST_INSULT_COREN = 12062 ,
MAX_DIREBREW_MINIONS = 3
}
enum CorenActions {
COREN_SPAWN_ILSA , COREN_SPAWN_URSULA , COREN_DISARM , COREN_DIREBREW_MINION ,
COREN_ACTION_MAX , COREN_ATTACK_TIMER
}
Functions
bool QuestRewarded_npc_coren_direbrew (Player *player, Creature *creature, Quest const *quest)
void AddSC_boss_coren_direbrew ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SPELL_DIREBREW_DISARM
SPELL_SUMMON_DIREBREW_MINION
SPELL_DIREBREW_CHARGE
SPELL_SUMMON_MOLE_MACHINE
SPELL_SUMMON_MOLE_MACHINE_MINION_SUMMONER
SPELL_PORT_TO_COREN
SPELL_SEND_SECOND_MUG
SPELL_DIREBREW_MINION_KNOCKBACK
SPELL_DIREBREWS_DISARM_PRECAST
SPELL_DIREBREWS_DISARM_GROW
NPC_ILSA_DIREBREW
NPC_URSULA_DIREBREW
NPC_DARK_IRON_ANTAGONIST
FACTION_HOSTILE
QUEST_INSULT_COREN
MAX_DIREBREW_MINIONS
Definition at line 28 of file boss_coren_direbrew.cpp.
CorenActions
enum CorenActions
Enumerator
COREN_SPAWN_ILSA
COREN_SPAWN_URSULA
COREN_DISARM
COREN_DIREBREW_MINION
COREN_ACTION_MAX
COREN_ATTACK_TIMER
Definition at line 67 of file boss_coren_direbrew.cpp.
Function Documentation
AddSC_boss_coren_direbrew()
void AddSC_boss_coren_direbrew ()
Definition at line 273 of file boss_coren_direbrew.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedNPC, QuestRewarded_npc_coren_direbrew(), and Script::RegisterSelf().
Referenced by AddScripts().
QuestRewarded_npc_coren_direbrew()
bool QuestRewarded_npc_coren_direbrew (Player * player, Creature * creature, Quest const * quest)
Definition at line 214 of file boss_coren_direbrew.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_EVENTAI_A, Quest::GetQuestId(), QUEST_INSULT_COREN, and UnitAI::SendAIEvent().
Referenced by AddSC_boss_coren_direbrew().