CMaNGOS_WoTLK: boss_freya.cpp File Reference
boss_freya.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_freyaAI
struct three_nature_alliesAI
struct npc_water_spiritAI
struct npc_snaplasherAI
struct npc_storm_lasherAI
struct npc_eonars_giftAI
struct npc_nature_bombAI
struct npc_iron_rootsAI
struct npc_healthy_sporeAI
Enumerations
enum {
SAY_AGGRO = -1603000 , SAY_AGGRO_HARD = -1603001 , SAY_ADDS_CONSERVATOR = -1603002 , SAY_ADDS_TRIO = -1603003 ,
SAY_ADDS_LASHER = -1603004 , SAY_SLAY_1 = -1603005 , SAY_SLAY_2 = -1603006 , SAY_EPILOGUE = -1603007 ,
SAY_BERSERK = -1603008 , EMOTE_ALLIES_NATURE = -1603010 , EMOTE_REGEN_ALLIES = -1603011 , SAY_AGGRO_BRIGHT = -1603014 ,
SAY_SLAY_1_BRIGHT = -1603015 , SAY_SLAY_2_BRIGHT = -1603016 , SAY_DEATH_BRIGHT = -1603017 , SAY_AGGRO_IRON = -1603018 ,
SAY_SLAY_1_IRON = -1603019 , SAY_SLAY_2_IRON = -1603020 , SAY_DEATH_IRON = -1603021 , SAY_AGGRO_STONE = -1603022 ,
SAY_SLAY_1_STONE = -1603023 , SAY_SLAY_2_STONE = -1603024 , SAY_DEATH_STONE = -1603025 , SPELL_FREYA_CREDIT = 65074 ,
SPELL_DEFORESTATION_CREDIT = 65015 , SPELL_BERSERK = 47008 , SPELL_ATTUNED_TO_NATURE = 62519 , SPELL_TOUCH_OF_EONAR = 62528 ,
SPELL_TOUCH_OF_EONAR_H = 62892 , SPELL_SUNBEAM = 62623 , SPELL_SUNBEAM_H = 62872 , SPELL_SUMMON_ALLIES_OF_NATURE = 62678 ,
SPELL_SUMMON_ALLIES_OF_NATURE_H = 62873 , SPELL_SUMMON_WAVE_1 = 62685 , SPELL_SUMMON_WAVE_3 = 62686 , SPELL_SUMMON_WAVE_10 = 62688 ,
SPELL_LIFEBINDERS_GIFT_SUMMON = 62572 , SPELL_NATURE_BOMB_SUMMON = 64604 , SPELL_SUMMON_CHEST_0 = 62950 , SPELL_SUMMON_CHEST_1 = 62952 ,
SPELL_SUMMON_CHEST_2 = 62953 , SPELL_SUMMON_CHEST_3 = 62954 , SPELL_SUMMON_CHEST_0_H = 62955 , SPELL_SUMMON_CHEST_1_H = 62956 ,
SPELL_SUMMON_CHEST_2_H = 62957 , SPELL_SUMMON_CHEST_3_H = 62958 , SPELL_FULL_HEAL = 43978 , SPELL_DRAINED_OF_POWER = 62467 ,
SPELL_BRIGHTLEAF_ESSENCE_CHANNEL = 62485 , SPELL_BRIGHTLEAF_ESSENCE_CHANNEL_H = 65587 , SPELL_UNSTABLE_SUN_BEAM = 62450 , SPELL_UNSTABLE_SUN_BEAM_H = 62868 ,
SPELL_IRONBRANCH_ESSENCE_CHANNEL = 62484 , SPELL_IRONBRANCH_ESSENCE_CHANNEL_H = 65588 , SPELL_IRON_ROOTS = 62439 , SPELL_IRON_ROOTS_H = 62862 ,
SPELL_STONEBARK_ESSEMCE_CHANNEL = 62483 , SPELL_STONEBARK_ESSEMCE_CHANNEL_H = 65589 , SPELL_GROUND_TREMOR = 62437 , SPELL_GROUND_TREMOR_H = 62859 ,
SPELL_SPORE_SUMMON_PERIODIC = 62566 , SPELL_HEALTHY_SPORE_VISUAL = 62538 , SPELL_POTENT_PHEROMONES = 62541 , SPELL_STRENGTHEN_IRON_ROOTS = 62440 ,
SPELL_STRENGTHEN_IRON_ROOTS_H = 63601 , SPELL_IRON_ROOTS_REMOVE = 62282 , SPELL_IRON_ROOTS_REMOVE_H = 63598 , SPELL_NATURE_BOMB_GO = 64600 ,
SPELL_NATURE_BOMB = 64587 , SPELL_NATURE_BOMB_H = 64650 , SPELL_ATTUNED_10_STACKS = 62525 , SPELL_ATTUNED_2_STACKS = 62524 ,
SPELL_ATTUNED_25_STACKS = 62521 , SPELL_FEIGN_DEATH = 65985 , SPELL_CLEAR_DEBUFFS = 34098 , SPELL_TIDAL_WAVE = 62652 ,
SPELL_TIDAL_WAVE_VISUAL = 62655 , SPELL_HARDENED_BARK = 62664 , SPELL_HARDENED_BARK_H = 64191 , SPELL_LIGHTNING_LASH = 62648 ,
SPELL_LIGHTNING_LASH_H = 62939 , SPELL_STORMBOLT = 62649 , SPELL_STORMBOLT_H = 62938 , SPELL_LIFEBINDERS_GIFT = 62584 ,
SPELL_LIFEBINDERS_GIFT_H = 64185 , SPELL_LIFEBINDERS_GIFT_VISUAL = 62579 , SPELL_AUTO_GROW = 62559 , SPELL_PHEROMONES = 62619 ,
NPC_DETONATING_LASHER = 32918 , NPC_ANCIENT_CONSERVATOR = 33203 , NPC_WATER_SPIRIT = 33202 , NPC_STORM_LASHER = 32919 ,
NPC_SNAPLASHER = 32916 , NPC_NATURE_BOMB = 34129 , NPC_IRON_ROOTS = 33088 , NPC_STRENGHENED_IRON_ROOTS = 33168 ,
NPC_EONARS_GIFT = 33228 , MIN_ATTUNED_NATURE_STACKS = 25 , MAX_ALLIES_SPELLS = 3 , MAX_ALLIES_WAVES = 6 ,
MIN_DEFORESTATION_COUNT = 2
}
Functions
UnitAI * GetAI_boss_freya (Creature *pCreature)
bool EffectScriptEffectCreature_boss_freya (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_water_spirit (Creature *pCreature)
UnitAI * GetAI_npc_snaplasher (Creature *pCreature)
UnitAI * GetAI_npc_storm_lasher (Creature *pCreature)
UnitAI * GetAI_npc_eonars_gift (Creature *pCreature)
UnitAI * GetAI_npc_nature_bomb (Creature *pCreature)
UnitAI * GetAI_npc_iron_roots (Creature *pCreature)
UnitAI * GetAI_npc_healthy_spore (Creature *pCreature)
void AddSC_boss_freya ()
Variables
static const uint32 aAlliesSpawnSpells [MAX_ALLIES_SPELLS] = {SPELL_SUMMON_WAVE_1, SPELL_SUMMON_WAVE_3, SPELL_SUMMON_WAVE_10}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_AGGRO_HARD
SAY_ADDS_CONSERVATOR
SAY_ADDS_TRIO
SAY_ADDS_LASHER
SAY_SLAY_1
SAY_SLAY_2
SAY_EPILOGUE
SAY_BERSERK
EMOTE_ALLIES_NATURE
EMOTE_REGEN_ALLIES
SAY_AGGRO_BRIGHT
SAY_SLAY_1_BRIGHT
SAY_SLAY_2_BRIGHT
SAY_DEATH_BRIGHT
SAY_AGGRO_IRON
SAY_SLAY_1_IRON
SAY_SLAY_2_IRON
SAY_DEATH_IRON
SAY_AGGRO_STONE
SAY_SLAY_1_STONE
SAY_SLAY_2_STONE
SAY_DEATH_STONE
SPELL_FREYA_CREDIT
SPELL_DEFORESTATION_CREDIT
SPELL_BERSERK
SPELL_ATTUNED_TO_NATURE
SPELL_TOUCH_OF_EONAR
SPELL_TOUCH_OF_EONAR_H
SPELL_SUNBEAM
SPELL_SUNBEAM_H
SPELL_SUMMON_ALLIES_OF_NATURE
SPELL_SUMMON_ALLIES_OF_NATURE_H
SPELL_SUMMON_WAVE_1
SPELL_SUMMON_WAVE_3
SPELL_SUMMON_WAVE_10
SPELL_LIFEBINDERS_GIFT_SUMMON
SPELL_NATURE_BOMB_SUMMON
SPELL_SUMMON_CHEST_0
SPELL_SUMMON_CHEST_1
SPELL_SUMMON_CHEST_2
SPELL_SUMMON_CHEST_3
SPELL_SUMMON_CHEST_0_H
SPELL_SUMMON_CHEST_1_H
SPELL_SUMMON_CHEST_2_H
SPELL_SUMMON_CHEST_3_H
SPELL_FULL_HEAL
SPELL_DRAINED_OF_POWER
SPELL_BRIGHTLEAF_ESSENCE_CHANNEL
SPELL_BRIGHTLEAF_ESSENCE_CHANNEL_H
SPELL_UNSTABLE_SUN_BEAM
SPELL_UNSTABLE_SUN_BEAM_H
SPELL_IRONBRANCH_ESSENCE_CHANNEL
SPELL_IRONBRANCH_ESSENCE_CHANNEL_H
SPELL_IRON_ROOTS
SPELL_IRON_ROOTS_H
SPELL_STONEBARK_ESSEMCE_CHANNEL
SPELL_STONEBARK_ESSEMCE_CHANNEL_H
SPELL_GROUND_TREMOR
SPELL_GROUND_TREMOR_H
SPELL_SPORE_SUMMON_PERIODIC
SPELL_HEALTHY_SPORE_VISUAL
SPELL_POTENT_PHEROMONES
SPELL_STRENGTHEN_IRON_ROOTS
SPELL_STRENGTHEN_IRON_ROOTS_H
SPELL_IRON_ROOTS_REMOVE
SPELL_IRON_ROOTS_REMOVE_H
SPELL_NATURE_BOMB_GO
SPELL_NATURE_BOMB
SPELL_NATURE_BOMB_H
SPELL_ATTUNED_10_STACKS
SPELL_ATTUNED_2_STACKS
SPELL_ATTUNED_25_STACKS
SPELL_FEIGN_DEATH
SPELL_CLEAR_DEBUFFS
SPELL_TIDAL_WAVE
SPELL_TIDAL_WAVE_VISUAL
SPELL_HARDENED_BARK
SPELL_HARDENED_BARK_H
SPELL_LIGHTNING_LASH
SPELL_LIGHTNING_LASH_H
SPELL_STORMBOLT
SPELL_STORMBOLT_H
SPELL_LIFEBINDERS_GIFT
SPELL_LIFEBINDERS_GIFT_H
SPELL_LIFEBINDERS_GIFT_VISUAL
SPELL_AUTO_GROW
SPELL_PHEROMONES
NPC_DETONATING_LASHER
NPC_ANCIENT_CONSERVATOR
NPC_WATER_SPIRIT
NPC_STORM_LASHER
NPC_SNAPLASHER
NPC_NATURE_BOMB
NPC_IRON_ROOTS
NPC_STRENGHENED_IRON_ROOTS
NPC_EONARS_GIFT
MIN_ATTUNED_NATURE_STACKS
MAX_ALLIES_SPELLS
MAX_ALLIES_WAVES
MIN_DEFORESTATION_COUNT
Definition at line 28 of file boss_freya.cpp.
Function Documentation
AddSC_boss_freya()
void AddSC_boss_freya ()
Definition at line 1132 of file boss_freya.cpp.
References EffectScriptEffectCreature_boss_freya(), Script::GetAI, GetAI_boss_freya(), GetAI_npc_eonars_gift(), GetAI_npc_healthy_spore(), GetAI_npc_iron_roots(), GetAI_npc_nature_bomb(), GetAI_npc_snaplasher(), GetAI_npc_storm_lasher(), GetAI_npc_water_spirit(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectScriptEffectCreature_boss_freya()
bool EffectScriptEffectCreature_boss_freya (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 774 of file boss_freya.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, Object::GetEntry(), NPC_FREYA, UnitAI::SendAIEvent(), SPELL_SUMMON_ALLIES_OF_NATURE, and SPELL_SUMMON_ALLIES_OF_NATURE_H.
Referenced by AddSC_boss_freya().
GetAI_boss_freya()
UnitAI* GetAI_boss_freya (Creature * pCreature)
Definition at line 769 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_eonars_gift()
UnitAI* GetAI_npc_eonars_gift (Creature * pCreature)
Definition at line 1013 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_healthy_spore()
UnitAI* GetAI_npc_healthy_spore (Creature * pCreature)
Definition at line 1127 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_iron_roots()
UnitAI* GetAI_npc_iron_roots (Creature * pCreature)
Definition at line 1100 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_nature_bomb()
UnitAI* GetAI_npc_nature_bomb (Creature * pCreature)
Definition at line 1063 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_snaplasher()
UnitAI* GetAI_npc_snaplasher (Creature * pCreature)
Definition at line 919 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_storm_lasher()
UnitAI* GetAI_npc_storm_lasher (Creature * pCreature)
Definition at line 973 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
GetAI_npc_water_spirit()
UnitAI* GetAI_npc_water_spirit (Creature * pCreature)
Definition at line 895 of file boss_freya.cpp.
Referenced by AddSC_boss_freya().
Variable Documentation
aAlliesSpawnSpells
const uint32 aAlliesSpawnSpells[MAX_ALLIES_SPELLS] = {SPELL_SUMMON_WAVE_1, SPELL_SUMMON_WAVE_3, SPELL_SUMMON_WAVE_10} static
Definition at line 180 of file boss_freya.cpp.
Referenced by boss_freyaAI::boss_freyaAI().