CMaNGOS_WoTLK: boss_razuvious.cpp File Reference
boss_razuvious.cpp File Reference
#include "AI/ScriptDevAI/base/BossAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/northrend/naxxramas/naxxramas.h"
Data Structures
struct boss_razuviousAI
struct npc_obedienceCrystalAI
struct ForcedObedience
Enumerations
enum {
SAY_COMMAND1 = 13072 , SAY_COMMAND2 = 13073 , SAY_COMMAND3 = 13074 , SAY_AGGRO1 = 13075 ,
SAY_AGGRO2 = 13076 , SAY_AGGRO3 = 13077 , SAY_AGGRO4 = 13078 , SAY_DEATH = 13079 ,
SAY_SLAY1 = 13080 , SAY_SLAY2 = 13081 , EMOTE_TRIUMPH = 13082 , SPELL_UNBALANCING_STRIKE = 55470 ,
SPELL_DISRUPTING_SHOUT = 55543 , SPELL_DISRUPTING_SHOUT_H = 29107 , SPELL_JAGGED_KNIFE = 55550 , SPELL_HOPELESS = 29125 ,
SPELL_FORCED_OBEDIENCE = 55479 , SPELL_OBEDIENCE_CHAINS = 55520 , SPELL_TAUNT = 29060 , SPELLSET_10N = 1606101 ,
SPELLSET_25N = 2835701
}
Functions
bool NpcSpellClick_npc_obedienceCrystal (Player *player, Creature *clickedCreature, uint32 spellId)
void AddSC_boss_razuvious ()
Variables
static const float resetZ = 285.0f
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_COMMAND1
SAY_COMMAND2
SAY_COMMAND3
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_AGGRO4
SAY_DEATH
SAY_SLAY1
SAY_SLAY2
EMOTE_TRIUMPH
SPELL_UNBALANCING_STRIKE
SPELL_DISRUPTING_SHOUT
SPELL_DISRUPTING_SHOUT_H
SPELL_JAGGED_KNIFE
SPELL_HOPELESS
SPELL_FORCED_OBEDIENCE
SPELL_OBEDIENCE_CHAINS
SPELL_TAUNT
SPELLSET_10N
SPELLSET_25N
Definition at line 28 of file boss_razuvious.cpp.
Function Documentation
AddSC_boss_razuvious()
void AddSC_boss_razuvious ()
Definition at line 161 of file boss_razuvious.cpp.
References Script::GetAI, Script::Name, NpcSpellClick_npc_obedienceCrystal(), Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
NpcSpellClick_npc_obedienceCrystal()
bool NpcSpellClick_npc_obedienceCrystal (Player * player, Creature * clickedCreature, uint32 spellId)
Definition at line 112 of file boss_razuvious.cpp.
References Unit::CastSpell(), GetCreatureListWithEntryInGrid(), Object::GetEntry(), Object::GetObjectGuid(), Unit::IsNonMeleeSpellCasted(), NPC_DEATHKNIGHT_UNDERSTUDY, NPC_OBEDIENCE_CRYSTAL, WorldObject::RemoveAllCooldowns(), SPELL_OBEDIENCE_CHAINS, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_razuvious().
Variable Documentation
resetZ
const float resetZ = 285.0f static
Definition at line 56 of file boss_razuvious.cpp.
Referenced by boss_razuviousAI::boss_razuviousAI().