CMaNGOS_WoTLK: boss_magtheridon.cpp File Reference
boss_magtheridon.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "magtheridons_lair.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "Entities/DynamicObject.h"
Data Structures
struct boss_magtheridonAI
struct mob_hellfire_channelerAI
struct go_manticron_cubeAI
struct ShadowGraspCube
struct ShadowGraspMagth
struct QuakeMagth
struct QuakeMagthKnockback
struct DebrisMagtheridon
Enumerations
enum {
SAY_AGGRO = -1544006 , SAY_UNUSED = -1544007 , SAY_BANISH = -1544008 , SAY_CHAMBER_DESTROY = -1544009 ,
SAY_PLAYER_KILLED = -1544010 , SAY_DEATH = -1544011 , EMOTE_GENERIC_ENRAGED = -1000003 , EMOTE_BLASTNOVA = -1544013 ,
EMOTE_FREED = -1544015 , SPELL_SHADOW_CAGE_DUMMY = 30205 , SPELL_BLASTNOVA = 30616 , SPELL_CLEAVE = 30619 ,
SPELL_QUAKE = 30657 , SPELL_QUAKE_REMOVAL = 30572 , SPELL_QUAKE_KNOCKBACK = 30571 , SPELL_BLAZE = 30541 ,
SPELL_BERSERK = 27680 , SPELL_CONFLAGRATION = 30757 , SPELL_CAMERA_SHAKE = 36455 , SPELL_DEBRIS_KNOCKDOWN = 36449 ,
SPELL_DEBRIS_1 = 30629 , SPELL_DEBRIS_2 = 30630 , SPELL_DEBRIS_DAMAGE = 30631 , SPELL_DEBRIS_VISUAL = 30632 ,
SPELL_SHADOW_CAGE = 30168 , SPELL_SHADOW_GRASP_VISUAL = 30166 , SPELL_SHADOW_GRASP = 30410 , SPELL_MIND_EXHAUSTION = 44032 ,
SPELL_SHADOW_GRASP_DUMMY = 30207 , SPELL_SHADOW_BOLT_VOLLEY = 30510 , SPELL_DARK_MENDING = 30528 , SPELL_FEAR = 30530 ,
SPELL_BURNING_ABYSSAL = 30511 , SPELL_SOUL_TRANSFER = 30531 , NPC_RAID_TRIGGER = 17376 , MAX_QUAKE_COUNT = 7
}
enum MagtheridonActions {
MAGTHERIDON_PHASE_3 , MAGTHERIDON_BERSERK , MAGTHERIDON_BLAST_NOVA , MAGTHERIDON_DEBRIS ,
MAGTHERIDON_QUAKE , MAGTHERIDON_CLEAVE , MAGTHERIDON_BLAZE , MAGTHERIDON_ACTION_MAX ,
MAGTHERIDON_QUAKE_TIMER , MAGTHERIDON_TRANSITION_TIMER
}
enum ChannelerActions {
CHANNELER_MARK_OF_SHADOW , CHANNELER_SHADOW_BOLT , CHANNELER_ACTION_MAX , CHANNELER_SETUP_TIMER ,
CHANNELER_INFERNAL , CHANNELER_DARK_MENDING , CHANNELER_FEAR , CHANNELER_SHADOW_BOLT ,
CHANNELER_ACTION_MAX , CHANNELER_SHADOW_GRASP
}
Functions
bool GOUse_go_manticron_cube (Player *player, GameObject *go)
void AddSC_boss_magtheridon ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_UNUSED
SAY_BANISH
SAY_CHAMBER_DESTROY
SAY_PLAYER_KILLED
SAY_DEATH
EMOTE_GENERIC_ENRAGED
EMOTE_BLASTNOVA
EMOTE_FREED
SPELL_SHADOW_CAGE_DUMMY
SPELL_BLASTNOVA
SPELL_CLEAVE
SPELL_QUAKE
SPELL_QUAKE_REMOVAL
SPELL_QUAKE_KNOCKBACK
SPELL_BLAZE
SPELL_BERSERK
SPELL_CONFLAGRATION
SPELL_CAMERA_SHAKE
SPELL_DEBRIS_KNOCKDOWN
SPELL_DEBRIS_1
SPELL_DEBRIS_2
SPELL_DEBRIS_DAMAGE
SPELL_DEBRIS_VISUAL
SPELL_SHADOW_CAGE
SPELL_SHADOW_GRASP_VISUAL
SPELL_SHADOW_GRASP
SPELL_MIND_EXHAUSTION
SPELL_SHADOW_GRASP_DUMMY
SPELL_SHADOW_BOLT_VOLLEY
SPELL_DARK_MENDING
SPELL_FEAR
SPELL_BURNING_ABYSSAL
SPELL_SOUL_TRANSFER
NPC_RAID_TRIGGER
MAX_QUAKE_COUNT
Definition at line 31 of file boss_magtheridon.cpp.
ChannelerActions
enum ChannelerActions
Enumerator
CHANNELER_MARK_OF_SHADOW
CHANNELER_SHADOW_BOLT
CHANNELER_ACTION_MAX
CHANNELER_SETUP_TIMER
CHANNELER_INFERNAL
CHANNELER_DARK_MENDING
CHANNELER_FEAR
CHANNELER_SHADOW_BOLT
CHANNELER_ACTION_MAX
CHANNELER_SHADOW_GRASP
Definition at line 318 of file boss_magtheridon.cpp.
MagtheridonActions
enum MagtheridonActions
Enumerator
MAGTHERIDON_PHASE_3
MAGTHERIDON_BERSERK
MAGTHERIDON_BLAST_NOVA
MAGTHERIDON_DEBRIS
MAGTHERIDON_QUAKE
MAGTHERIDON_CLEAVE
MAGTHERIDON_BLAZE
MAGTHERIDON_ACTION_MAX
MAGTHERIDON_QUAKE_TIMER
MAGTHERIDON_TRANSITION_TIMER
Definition at line 91 of file boss_magtheridon.cpp.
Function Documentation
AddSC_boss_magtheridon()
void AddSC_boss_magtheridon ()
Definition at line 506 of file boss_magtheridon.cpp.
References Script::GetAI, Script::GetGameObjectAI, GOUse_go_manticron_cube(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_manticron_cube()
bool GOUse_go_manticron_cube (Player * player, GameObject * go)
Definition at line 409 of file boss_magtheridon.cpp.
References GameObject::AI(), Unit::CastSpell(), WorldObject::GetInstanceData(), go_manticron_cubeAI::GetManticronCubeLastUser(), Unit::HasAura(), IN_PROGRESS, NPC_MAGTHERIDON, SPELL_MIND_EXHAUSTION, SPELL_SHADOW_GRASP, TRIGGERED_NONE, and TYPE_MAGTHERIDON_EVENT.
Referenced by AddSC_boss_magtheridon().