CMaNGOS_WoTLK: boss_razorgore.cpp File Reference
boss_razorgore.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackwing_lair.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct boss_razorgoreAI
struct npc_blackwing_orbAI
struct DestroyEgg
struct ExplosionRazorgore
struct PossessRazorgore
struct CalmDragonkin
Enumerations
enum {
SAY_EGGS_BROKEN_1 = -1469022 , SAY_EGGS_BROKEN_2 = -1469023 , SAY_EGGS_BROKEN_3 = -1469024 , SPELL_POSSESS_VISUAL = 23014 ,
SPELL_DESTROY_EGG = 19873 , SPELL_DRAGON_ORB = 23021 , SPELL_MIND_EXHAUSTION = 23958 , SPELL_CLEAVE = 19632 ,
SPELL_WARSTOMP = 24375 , SPELL_FIREBALL_VOLLEY = 22425 , SPELL_CONFLAGRATION = 23023 , SPELL_DOUBLE_ATTACK = 18943
}
enum RazorgoreActions {
RAZORGORE_CONFLAGRATION , RAZORGORE_FIREBALL_VOLLEY , RAZORGORE_WAR_STOMP , RAZORGORE_CLEAVE ,
RAZORGORE_ACTION_MAX
}
Functions
bool ProcessEventIdRazorgorePossess (uint32 eventId, Object *source, Object *target, bool isStart)
void AddSC_boss_razorgore ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_EGGS_BROKEN_1
SAY_EGGS_BROKEN_2
SAY_EGGS_BROKEN_3
SPELL_POSSESS_VISUAL
SPELL_DESTROY_EGG
SPELL_DRAGON_ORB
SPELL_MIND_EXHAUSTION
SPELL_CLEAVE
SPELL_WARSTOMP
SPELL_FIREBALL_VOLLEY
SPELL_CONFLAGRATION
SPELL_DOUBLE_ATTACK
Definition at line 30 of file boss_razorgore.cpp.
RazorgoreActions
enum RazorgoreActions
Enumerator
RAZORGORE_CONFLAGRATION
RAZORGORE_FIREBALL_VOLLEY
RAZORGORE_WAR_STOMP
RAZORGORE_CLEAVE
RAZORGORE_ACTION_MAX
Definition at line 50 of file boss_razorgore.cpp.
Function Documentation
AddSC_boss_razorgore()
void AddSC_boss_razorgore ()
Definition at line 300 of file boss_razorgore.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventIdRazorgorePossess(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventIdRazorgorePossess()
bool ProcessEventIdRazorgorePossess (uint32 eventId, Object * source, Object * target, bool isStart)
Definition at line 216 of file boss_razorgore.cpp.
References Unit::CastSpell(), Map::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), Object::IsPlayer(), NPC_BLACKWING_ORB_TRIGGER, SPELL_POSSESS_VISUAL, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_boss_razorgore().