CMaNGOS_WoTLK: boss_argent_challenge.cpp File Reference
boss_argent_challenge.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_champion.h"
Data Structures
struct argent_champion_commonAI
struct boss_eadricAI
struct boss_paletressAI
Enumerations
enum { FACTION_CHAMPION_FRIENDLY = 35 }
enum {
SAY_EADRIC_AGGRO = -1650052 , SAY_EADRIC_HAMMER = -1650053 , SAY_EADRIC_KILL_1 = -1650054 , SAY_EADRIC_KILL_2 = -1650055 ,
SAY_EADRIC_DEFEAT = -1650056 , EMOTE_EADRIC_RADIANCE = -1650057 , EMOTE_EADRIC_HAMMER = -1650058 , SPELL_KILL_CREDIT_EADRIC = 68575 ,
SPELL_EADRIC_ACHIEVEMENT = 68197 , SPELL_HAMMER_OF_JUSTICE = 66863 , SPELL_HAMMER_OF_RIGHTEOUS = 66867 , SPELL_RADIANCE = 66935 ,
SPELL_VENGEANCE = 66865
}
enum {
SAY_PALETRESS_AGGRO = -1650059 , SAY_PALETRESS_MEMORY = -1650060 , SAY_PALETRESS_MEMORY_DIES = -1650061 , SAY_PALETRESS_KILL_1 = -1650062 ,
SAY_PALETRESS_KILL_2 = -1650063 , SAY_PALETRESS_DEFEAT = -1650064 , SPELL_KILL_CREDIT_PALETRESS = 68574 , SPELL_CONFESSOR_ACHIEVEMENT = 68206 ,
SPELL_CONFESS = 66547 , SPELL_CONFESS_AURA = 66680 , SPELL_SUMMON_MEMORY = 66545 , SPELL_REFLECTIVE_SHIELD = 66515 ,
SPELL_HOLY_FIRE = 66538 , SPELL_HOLY_NOVA = 66546 , SPELL_HOLY_SMITE = 66536 , SPELL_RENEW = 66537 ,
SPELL_MEMORY_SPAWN_EFFECT = 66675 , SPELL_SHADOWFORM = 41408
}
Functions
UnitAI * GetAI_boss_eadric (Creature *pCreature)
UnitAI * GetAI_boss_paletress (Creature *pCreature)
void AddSC_boss_argent_challenge ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FACTION_CHAMPION_FRIENDLY
Definition at line 27 of file boss_argent_challenge.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_EADRIC_AGGRO
SAY_EADRIC_HAMMER
SAY_EADRIC_KILL_1
SAY_EADRIC_KILL_2
SAY_EADRIC_DEFEAT
EMOTE_EADRIC_RADIANCE
EMOTE_EADRIC_HAMMER
SPELL_KILL_CREDIT_EADRIC
SPELL_EADRIC_ACHIEVEMENT
SPELL_HAMMER_OF_JUSTICE
SPELL_HAMMER_OF_RIGHTEOUS
SPELL_RADIANCE
SPELL_VENGEANCE
Definition at line 91 of file boss_argent_challenge.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_PALETRESS_AGGRO
SAY_PALETRESS_MEMORY
SAY_PALETRESS_MEMORY_DIES
SAY_PALETRESS_KILL_1
SAY_PALETRESS_KILL_2
SAY_PALETRESS_DEFEAT
SPELL_KILL_CREDIT_PALETRESS
SPELL_CONFESSOR_ACHIEVEMENT
SPELL_CONFESS
SPELL_CONFESS_AURA
SPELL_SUMMON_MEMORY
SPELL_REFLECTIVE_SHIELD
SPELL_HOLY_FIRE
SPELL_HOLY_NOVA
SPELL_HOLY_SMITE
SPELL_RENEW
SPELL_MEMORY_SPAWN_EFFECT
SPELL_SHADOWFORM
Definition at line 192 of file boss_argent_challenge.cpp.
Function Documentation
AddSC_boss_argent_challenge()
void AddSC_boss_argent_challenge ()
Definition at line 343 of file boss_argent_challenge.cpp.
References Script::GetAI, GetAI_boss_eadric(), GetAI_boss_paletress(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_eadric()
UnitAI* GetAI_boss_eadric (Creature * pCreature)
Definition at line 187 of file boss_argent_challenge.cpp.
Referenced by AddSC_boss_argent_challenge().
GetAI_boss_paletress()
UnitAI* GetAI_boss_paletress (Creature * pCreature)
Definition at line 338 of file boss_argent_challenge.cpp.
Referenced by AddSC_boss_argent_challenge().