CMaNGOS_WoTLK: brewfest.cpp File Reference
brewfest.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/eastern_kingdoms/world_eastern_kingdoms.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "AI/ScriptDevAI/scripts/world/brewfest.h"
Data Structures
struct BrewfestMountTransformation
struct BrewfestMountTransformationFactionSwap
struct npc_brewfest_barker
struct GiddyUp
struct RamsteinsSwiftWorkRam
struct RamNeutral
struct RamTrot
struct RamCanter
struct RamGallop
struct RamFatigue
struct AppleTrapFriendly
struct BrewfestBarkerBunny
struct FaceStringIDFacingBunny
struct FaceMe
struct BrewfestThrowKegPlayerDND
struct BrewfestRelayRacePlayerIncreaseMountDuration
struct SummonMoleMachinePovBunny
struct MoleMachinePortSchedule
struct MoleMachinePortalSchedule
struct MakeBunnySummonMoleMachine
struct SummonMoleMachine
Enumerations
enum {
AT_ITA_THUNDERBREW = 4712 , AT_MAEVE_BARLEYBREW = 4715 , AT_GORDOK_BREW_BARKER_ALLY = 4716 , AT_BELBI_QUIKSWITCH = 4718 ,
AT_GORDOK_BREW_BARKER_HORDE = 4797 , AT_DROHNS_DISTILLERY_BARKER = 4798 , AT_TCHALIS_VOODOO_BREWERY_BARKER = 4799 , AT_BLIX_FIXWIDGET = 4800 ,
AT_IPFELKOFER_IRONKEG = 4820 , AT_TAPPER_SWINDLEKEG = 4829
}
enum BrewfestRamMechanics {
SPELL_GIDDYUP = 42924 , SPELL_NEUTRAL = 43310 , SPELL_TROT = 42992 , SPELL_CANTER = 42993 ,
SPELL_GALLOP = 42994 , SPELL_RAM = 43880 , SPELL_RENTAL_RAM = 43883 , SPELL_RAM_RACING_AURA = 42146 ,
SPELL_APPLE_TRAP = 43492 , SPELL_RAM_FATIGUE = 43052 , SPELL_EXHAUSTED_RAM = 43332 , SPELL_BREWFEST_QUEST_SPEED_BUNNY_GREEN = 43345 ,
SPELL_BREWFEST_QUEST_SPEED_BUNNY_YELLOW = 43346 , SPELL_BREWFEST_QUEST_SPEED_BUNNY_RED = 43347 , QUEST_NOW_THIS_IS_RAM_RACING_ALMOST_A = 11318 , QUEST_NOW_THIS_IS_RAM_RACING_ALMOST_H = 11409
}
enum {
AT_HORDE_1 = 4801 , AT_HORDE_2 = 4802 , AT_HORDE_3 = 4803 , AT_HORDE_4 = 4804 ,
AT_ALLY_1 = 4769 , AT_ALLY_2 = 4770 , AT_ALLY_3 = 4772 , AT_ALLY_4 = 4774 ,
SPELL_BARKING_CREDIT_1 = 43259 , SPELL_BARKING_CREDIT_2 = 43260 , SPELL_BARKING_CREDIT_3 = 43261 , SPELL_BARKING_CREDIT_4 = 43262 ,
QUEST_BARK_FOR_THE_BARLEYBREWS = 11293 , QUEST_BARK_FOR_THE_THUNDERBREWS = 11294 , QUEST_BARK_FOR_DROHNS_DISTILLERY = 11407 , QUEST_BARK_FOR_TCHALIS_VOODOO_BREWERY = 11408
}
enum KegFetching {
SPELL_BREWFEST_THROW_KEG_DND = 43660 , SPELL_SEE_BASE_CAMP_MARK = 44070 , SPELL_SEE_SUPPLIER_MARK = 44069 , SPELL_RELAY_RACE_HAS_PORTABLE_KEG = 44066 ,
SPELL_BREWFEST_DAILY_RELAY_RACE_PLAYER_INCREASE_MOUNT_DURATION = 43755 , SPELL_WORKING_FOR_THE_MAN = 43534 , SPELL_HOLIDAY_BREWFEST_DAILY_RELAY_RACE_CREATE_TICKETS = 44501 , SPELL_BREWFEST_DAILY_RELAY_RACE_PLAYER_TURN_IN = 43663 ,
SPELL_BREWFEST_RELAY_RACE_INTRO_ASSIGN_KILL_CREDIT = 44601 , SPELL_BREWFEST_RELAY_RACE_INTRO_FORCE_PLAYER_TO_THROW = 43714 , SPELL_RELAY_RACE_ACCEPT_HIDDEN_DEBUFF = 44689 , NPC_BOK_DROPCERTAIN = 24527 ,
NPC_DRIZ_TUMBLEQUICK = 24510 , NPC_FLYNN_FIREBREW = 24364 , NPC_POL_AMBERSTILL = 24468 , QUEST_THERE_AND_BACK_AGAIN_A = 11122 ,
QUEST_THERE_AND_BACK_AGAIN_H = 11412
}
enum MoleMachine {
SPELL_MOLE_MACHINE_PORT_SCHEDULE = 47489 , SPELL_MOLE_MACHINE_BIND_SIGHT = 47513 , SPELL_MOVE_BIND_SIGHT = 47673 , SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER = 47523 ,
SPELL_MOLE_MACHINE_HEARTH_AURA_ALREADY_PORTING = 49476 , SPELL_MOLE_MACHINE_PLAYER_HIDE_AND_ROOT = 47521 , SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER_PORTAL = 49846 , SPELL_MAKE_BUNNY_SUMMON_MOLE_MACHINE = 49858 ,
SPELL_MOLE_MACHINE_PLAYER_LAND = 47676 , SPELL_SUMMON_MOLE_MACHINE = 47514
}
enum BrewfestTimers { BREWFEST_KEG_TAPPING_TIMER , BREWFEST_DARK_IRON_ATTACK_TIMER }
enum KegTapping { SAY_20_VOLJIN = 23882 , SAY_20_MEKKATORQUE = 23886 , SAY_10_VOLJIN = 23881 , SAY_10_MEKKATORQUE = 23887 }
enum DarkIronEvent { SPELL_PLAYERS_WON_A_SUMMON_DARK_IRON_DWARF_PLANS = 48145 , SPELL_PLAYERS_WON_H_SUMMON_DARK_IRON_DWARF_PLANS = 49318 }
Functions
bool AreaTrigger_at_brewfest_barker (Player *player, AreaTriggerEntry const *pAt)
void RamCleanup (Unit *target)
bool AreaTrigger_at_brewfest_quest_barking (Player *player, AreaTriggerEntry const *at)
bool AreaTrigger_at_brewfest_receive_keg (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_brewfest_send_keg (Player *player, AreaTriggerEntry const *)
void AddSC_brewfest ()
Variables
const std::vector< uint32 > belbiTexts = { 22170, 22171, 22172, 22173, 22174, 22175 }
const std::vector< uint32 > blixTexts = { 23497, 23498, 23499, 23500, 23501, 23502 }
const std::vector< uint32 > itaTexts = { 22135, 22136, 22137 }
const std::vector< uint32 > maeveTexts = { 22132, 22133, 22134 }
const std::vector< uint32 > gordokTexts = { 22138, 22139, 22140 }
const std::vector< uint32 > drohnTexts = { 23513, 23514, 23515, 23516 }
const std::vector< uint32 > tchaliTexts = { 23517, 23518, 23519 }
const std::vector< uint32 > ipfelkoferTexts = { 23691, 23692, 23693 }
const std::vector< uint32 > tapperTexts = { 23698, 23700, 23701 }
const uint32 auraPerStacks []
const std::vector< uint32 > drohnsTexts = { 23520, 23521, 23522, 23523 }
const std::vector< uint32 > tchalisTexts = { 23524, 23525, 23526, 23527 }
const std::vector< uint32 > barleyTexts = { 22134, 23464, 23465, 23466 }
const std::vector< uint32 > thunderTexts = { 22942, 23467, 23468, 23469 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AT_ITA_THUNDERBREW
AT_MAEVE_BARLEYBREW
AT_GORDOK_BREW_BARKER_ALLY
AT_BELBI_QUIKSWITCH
AT_GORDOK_BREW_BARKER_HORDE
AT_DROHNS_DISTILLERY_BARKER
AT_TCHALIS_VOODOO_BREWERY_BARKER
AT_BLIX_FIXWIDGET
AT_IPFELKOFER_IRONKEG
AT_TAPPER_SWINDLEKEG
Definition at line 186 of file brewfest.cpp.
anonymous enum
anonymous enum
Enumerator
AT_HORDE_1
AT_HORDE_2
AT_HORDE_3
AT_HORDE_4
AT_ALLY_1
AT_ALLY_2
AT_ALLY_3
AT_ALLY_4
SPELL_BARKING_CREDIT_1
SPELL_BARKING_CREDIT_2
SPELL_BARKING_CREDIT_3
SPELL_BARKING_CREDIT_4
QUEST_BARK_FOR_THE_BARLEYBREWS
QUEST_BARK_FOR_THE_THUNDERBREWS
QUEST_BARK_FOR_DROHNS_DISTILLERY
QUEST_BARK_FOR_TCHALIS_VOODOO_BREWERY
Definition at line 430 of file brewfest.cpp.
BrewfestRamMechanics
enum BrewfestRamMechanics
Enumerator
SPELL_GIDDYUP
SPELL_NEUTRAL
SPELL_TROT
SPELL_CANTER
SPELL_GALLOP
SPELL_RAM
SPELL_RENTAL_RAM
SPELL_RAM_RACING_AURA
SPELL_APPLE_TRAP
SPELL_RAM_FATIGUE
SPELL_EXHAUSTED_RAM
SPELL_BREWFEST_QUEST_SPEED_BUNNY_GREEN
SPELL_BREWFEST_QUEST_SPEED_BUNNY_YELLOW
SPELL_BREWFEST_QUEST_SPEED_BUNNY_RED
QUEST_NOW_THIS_IS_RAM_RACING_ALMOST_A
QUEST_NOW_THIS_IS_RAM_RACING_ALMOST_H
Definition at line 233 of file brewfest.cpp.
BrewfestTimers
enum BrewfestTimers
Enumerator
BREWFEST_KEG_TAPPING_TIMER
BREWFEST_DARK_IRON_ATTACK_TIMER
Definition at line 762 of file brewfest.cpp.
DarkIronEvent
enum DarkIronEvent
Enumerator
SPELL_PLAYERS_WON_A_SUMMON_DARK_IRON_DWARF_PLANS
SPELL_PLAYERS_WON_H_SUMMON_DARK_IRON_DWARF_PLANS
Definition at line 823 of file brewfest.cpp.
KegFetching
enum KegFetching
Enumerator
SPELL_BREWFEST_THROW_KEG_DND
SPELL_SEE_BASE_CAMP_MARK
SPELL_SEE_SUPPLIER_MARK
SPELL_RELAY_RACE_HAS_PORTABLE_KEG
SPELL_BREWFEST_DAILY_RELAY_RACE_PLAYER_INCREASE_MOUNT_DURATION
SPELL_WORKING_FOR_THE_MAN
SPELL_HOLIDAY_BREWFEST_DAILY_RELAY_RACE_CREATE_TICKETS
SPELL_BREWFEST_DAILY_RELAY_RACE_PLAYER_TURN_IN
SPELL_BREWFEST_RELAY_RACE_INTRO_ASSIGN_KILL_CREDIT
SPELL_BREWFEST_RELAY_RACE_INTRO_FORCE_PLAYER_TO_THROW
SPELL_RELAY_RACE_ACCEPT_HIDDEN_DEBUFF
NPC_BOK_DROPCERTAIN
NPC_DRIZ_TUMBLEQUICK
NPC_FLYNN_FIREBREW
NPC_POL_AMBERSTILL
QUEST_THERE_AND_BACK_AGAIN_A
QUEST_THERE_AND_BACK_AGAIN_H
Definition at line 536 of file brewfest.cpp.
KegTapping
enum KegTapping
Enumerator
SAY_20_VOLJIN
SAY_20_MEKKATORQUE
SAY_10_VOLJIN
SAY_10_MEKKATORQUE
Definition at line 768 of file brewfest.cpp.
MoleMachine
enum MoleMachine
Enumerator
SPELL_MOLE_MACHINE_PORT_SCHEDULE
SPELL_MOLE_MACHINE_BIND_SIGHT
SPELL_MOVE_BIND_SIGHT
SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER
SPELL_MOLE_MACHINE_HEARTH_AURA_ALREADY_PORTING
SPELL_MOLE_MACHINE_PLAYER_HIDE_AND_ROOT
SPELL_MOLE_MACHINE_PORT_TO_GRIM_GUZZLER_PORTAL
SPELL_MAKE_BUNNY_SUMMON_MOLE_MACHINE
SPELL_MOLE_MACHINE_PLAYER_LAND
SPELL_SUMMON_MOLE_MACHINE
Definition at line 631 of file brewfest.cpp.
Function Documentation
AddSC_brewfest()
void AddSC_brewfest ()
Definition at line 835 of file brewfest.cpp.
References AreaTrigger_at_brewfest_barker(), AreaTrigger_at_brewfest_quest_barking(), AreaTrigger_at_brewfest_receive_keg(), AreaTrigger_at_brewfest_send_keg(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_brewfest_barker()
bool AreaTrigger_at_brewfest_barker (Player * player, AreaTriggerEntry const * pAt)
Definition at line 200 of file brewfest.cpp.
References AT_BELBI_QUIKSWITCH, AT_BLIX_FIXWIDGET, AT_DROHNS_DISTILLERY_BARKER, AT_GORDOK_BREW_BARKER_ALLY, AT_GORDOK_BREW_BARKER_HORDE, AT_IPFELKOFER_IRONKEG, AT_ITA_THUNDERBREW, AT_MAEVE_BARLEYBREW, AT_TAPPER_SWINDLEKEG, AT_TCHALIS_VOODOO_BREWERY_BARKER, WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), AreaTriggerEntry::id, Unit::IsAlive(), Player::IsGameMaster(), NPC_BELBI_QUIKSWITCH, NPC_BLIX_FIXWIDGET, NPC_DROHNS_DISTILLERY_BARKER, NPC_GORDOK_BREW_BARKER, NPC_IPFELKOFER_IRONKEG, NPC_ITA_THUNDERBREW, NPC_MAEVE_BARLEYBREW, NPC_TAPPER_SWINDLEKEG, and NPC_TCHALIS_VOODOO_BREWERY_BARKER.
Referenced by AddSC_brewfest().
AreaTrigger_at_brewfest_quest_barking()
bool AreaTrigger_at_brewfest_quest_barking (Player * player, AreaTriggerEntry const * at)
Definition at line 460 of file brewfest.cpp.
References AT_ALLY_1, AT_ALLY_2, AT_ALLY_3, AT_ALLY_4, AT_HORDE_1, AT_HORDE_2, AT_HORDE_3, AT_HORDE_4, Unit::CastSpell(), Unit::HasAura(), AreaTriggerEntry::id, SPELL_BARKING_CREDIT_1, SPELL_BARKING_CREDIT_2, SPELL_BARKING_CREDIT_3, SPELL_BARKING_CREDIT_4, SPELL_RENTAL_RAM, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_brewfest().
AreaTrigger_at_brewfest_receive_keg()
bool AreaTrigger_at_brewfest_receive_keg (Player * player, AreaTriggerEntry const *)
Definition at line 561 of file brewfest.cpp.
References Unit::CastSpell(), GetClosestCreatureWithEntry(), Player::GetTeam(), Unit::HasAura(), HORDE, NPC_BOK_DROPCERTAIN, NPC_FLYNN_FIREBREW, Unit::RemoveAurasDueToSpell(), SPELL_BREWFEST_THROW_KEG_DND, SPELL_RAM, SPELL_RELAY_RACE_HAS_PORTABLE_KEG, SPELL_SEE_BASE_CAMP_MARK, SPELL_SEE_SUPPLIER_MARK, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_brewfest().
AreaTrigger_at_brewfest_send_keg()
bool AreaTrigger_at_brewfest_send_keg (Player * player, AreaTriggerEntry const *)
Definition at line 579 of file brewfest.cpp.
References Unit::CastSpell(), GetClosestCreatureWithEntry(), Player::GetTeam(), Unit::HasAura(), HORDE, Player::IsCurrentQuest(), NPC_DRIZ_TUMBLEQUICK, NPC_POL_AMBERSTILL, QUEST_THERE_AND_BACK_AGAIN_A, QUEST_THERE_AND_BACK_AGAIN_H, Unit::RemoveAurasDueToSpell(), SPELL_BREWFEST_DAILY_RELAY_RACE_PLAYER_TURN_IN, SPELL_BREWFEST_RELAY_RACE_INTRO_FORCE_PLAYER_TO_THROW, SPELL_RAM, SPELL_RELAY_RACE_HAS_PORTABLE_KEG, SPELL_SEE_BASE_CAMP_MARK, SPELL_SEE_SUPPLIER_MARK, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_brewfest().
RamCleanup()
void RamCleanup (Unit * target)
Definition at line 263 of file brewfest.cpp.
References Unit::RemoveAurasDueToSpell(), SPELL_APPLE_TRAP, SPELL_CANTER, SPELL_GALLOP, SPELL_GIDDYUP, SPELL_NEUTRAL, SPELL_RAM, SPELL_RAM_FATIGUE, SPELL_RAM_RACING_AURA, SPELL_RENTAL_RAM, and SPELL_TROT.
Referenced by RamsteinsSwiftWorkRam::OnApply().
Variable Documentation
auraPerStacks
const uint32 auraPerStacks[]
Initial value:
=
{
    SPELL_NEUTRAL, SPELL_TROT, SPELL_TROT, SPELL_TROT, SPELL_CANTER, SPELL_CANTER, SPELL_CANTER, SPELL_CANTER, SPELL_GALLOP, SPELL_GALLOP, SPELL_GALLOP, SPELL_GALLOP, SPELL_GALLOP
}
Definition at line 258 of file brewfest.cpp.
Referenced by GiddyUp::HandleTickAndApplication().
barleyTexts
const std::vector<uint32> barleyTexts = { 22134, 23464, 23465, 23466 }
Definition at line 457 of file brewfest.cpp.
Referenced by BrewfestBarkerBunny::OnApply().
belbiTexts
const std::vector<uint32> belbiTexts = { 22170, 22171, 22172, 22173, 22174, 22175 }
Definition at line 92 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
blixTexts
const std::vector<uint32> blixTexts = { 23497, 23498, 23499, 23500, 23501, 23502 }
Definition at line 93 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
drohnsTexts
const std::vector<uint32> drohnsTexts = { 23520, 23521, 23522, 23523 }
Definition at line 455 of file brewfest.cpp.
Referenced by BrewfestBarkerBunny::OnApply().
drohnTexts
const std::vector<uint32> drohnTexts = { 23513, 23514, 23515, 23516 }
Definition at line 97 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
gordokTexts
const std::vector<uint32> gordokTexts = { 22138, 22139, 22140 }
Definition at line 96 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
ipfelkoferTexts
const std::vector<uint32> ipfelkoferTexts = { 23691, 23692, 23693 }
Definition at line 99 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
itaTexts
const std::vector<uint32> itaTexts = { 22135, 22136, 22137 }
Definition at line 94 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
maeveTexts
const std::vector<uint32> maeveTexts = { 22132, 22133, 22134 }
Definition at line 95 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
tapperTexts
const std::vector<uint32> tapperTexts = { 23698, 23700, 23701 }
Definition at line 100 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
tchalisTexts
const std::vector<uint32> tchalisTexts = { 23524, 23525, 23526, 23527 }
Definition at line 456 of file brewfest.cpp.
Referenced by BrewfestBarkerBunny::OnApply().
tchaliTexts
const std::vector<uint32> tchaliTexts = { 23517, 23518, 23519 }
Definition at line 98 of file brewfest.cpp.
Referenced by npc_brewfest_barker::StartScript().
thunderTexts
const std::vector<uint32> thunderTexts = { 22942, 23467, 23468, 23469 }
Definition at line 458 of file brewfest.cpp.
Referenced by BrewfestBarkerBunny::OnApply().