CMaNGOS_WoTLK: burning_steppes.cpp File Reference
burning_steppes.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_grark_lorkrubAI
struct npc_klinfranAI
Macros
#define GOSSIP_ITEM "Show me your real face, demon."
Enumerations
enum {
SAY_START = -1000873 , SAY_PAY = -1000874 , SAY_FIRST_AMBUSH_START = -1000875 , SAY_FIRST_AMBUSH_END = -1000876 ,
SAY_SEC_AMBUSH_START = -1000877 , SAY_SEC_AMBUSH_END = -1000878 , SAY_THIRD_AMBUSH_START = -1000879 , SAY_THIRD_AMBUSH_END = -1000880 ,
EMOTE_LAUGH = -1000881 , SAY_LAST_STAND = -1000882 , SAY_LEXLORT_1 = -1000883 , SAY_LEXLORT_2 = -1000884 ,
EMOTE_RAISE_AXE = -1000885 , EMOTE_LOWER_HAND = -1000886 , SAY_LEXLORT_3 = -1000887 , SAY_LEXLORT_4 = -1000888 ,
EMOTE_SUBMIT = -1000889 , SAY_AGGRO = -1000890 , SPELL_CAPTURE_GRARK = 14250 , NPC_BLACKROCK_AMBUSHER = 9522 ,
NPC_BLACKROCK_RAIDER = 9605 , NPC_FLAMESCALE_DRAGONSPAWN = 7042 , NPC_SEARSCALE_DRAKE = 7046 , NPC_GRARK_LORKRUB = 9520 ,
NPC_HIGH_EXECUTIONER_NUZARK = 9538 , NPC_SHADOW_OF_LEXLORT = 9539 , FACTION_FRIENDLY = 35 , QUEST_ID_PRECARIOUS_PREDICAMENT = 4121
}
enum {
SPELL_FOOLS_PLIGHT = 23504 , SPELL_DEMONIC_FRENZY = 23257 , SPELL_ENTROPIC_STING = 23260 , EMOTE_FRENZY = -1000001 ,
NPC_NELSON_THE_NICE = 14529 , NPC_KLINFRAN_THE_CRAZED = 14534 , NPC_THE_CLEANER = 14503 , QUEST_STAVE_OF_THE_ANCIENTS = 7636
}
Functions
UnitAI * GetAI_npc_grark_lorkrub (Creature *pCreature)
bool QuestAccept_npc_grark_lorkrub (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool EffectDummyCreature_spell_capture_grark (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GossipHello_npc_klinfran (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_klinfran (Player *pPlayer, Creature *pCreature, uint32, uint32)
UnitAI * GetAI_npc_klinfran (Creature *pCreature)
void AddSC_burning_steppes ()
Variables
static const DialogueEntry aOutroDialogue []
Macro Definition Documentation
GOSSIP_ITEM
#define GOSSIP_ITEM "Show me your real face, demon."
Definition at line 355 of file burning_steppes.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_PAY
SAY_FIRST_AMBUSH_START
SAY_FIRST_AMBUSH_END
SAY_SEC_AMBUSH_START
SAY_SEC_AMBUSH_END
SAY_THIRD_AMBUSH_START
SAY_THIRD_AMBUSH_END
EMOTE_LAUGH
SAY_LAST_STAND
SAY_LEXLORT_1
SAY_LEXLORT_2
EMOTE_RAISE_AXE
EMOTE_LOWER_HAND
SAY_LEXLORT_3
SAY_LEXLORT_4
EMOTE_SUBMIT
SAY_AGGRO
SPELL_CAPTURE_GRARK
NPC_BLACKROCK_AMBUSHER
NPC_BLACKROCK_RAIDER
NPC_FLAMESCALE_DRAGONSPAWN
NPC_SEARSCALE_DRAKE
NPC_GRARK_LORKRUB
NPC_HIGH_EXECUTIONER_NUZARK
NPC_SHADOW_OF_LEXLORT
FACTION_FRIENDLY
QUEST_ID_PRECARIOUS_PREDICAMENT
Definition at line 35 of file burning_steppes.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FOOLS_PLIGHT
SPELL_DEMONIC_FRENZY
SPELL_ENTROPIC_STING
EMOTE_FRENZY
NPC_NELSON_THE_NICE
NPC_KLINFRAN_THE_CRAZED
NPC_THE_CLEANER
QUEST_STAVE_OF_THE_ANCIENTS
Definition at line 339 of file burning_steppes.cpp.
Function Documentation
AddSC_burning_steppes()
void AddSC_burning_steppes ()
Definition at line 563 of file burning_steppes.cpp.
References EffectDummyCreature_spell_capture_grark(), Script::GetAI, GetAI_npc_grark_lorkrub(), GetAI_npc_klinfran(), GossipHello_npc_klinfran(), GossipSelect_npc_klinfran(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_grark_lorkrub(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_capture_grark()
bool EffectDummyCreature_spell_capture_grark (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 318 of file burning_steppes.cpp.
References Creature::AI(), DoScriptText(), EFFECT_INDEX_0, EMOTE_SUBMIT, UnitAI::EnterEvadeMode(), FACTION_FRIENDLY, Unit::GetHealthPercent(), Creature::SetFactionTemporary(), SPELL_CAPTURE_GRARK, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_burning_steppes().
GetAI_npc_grark_lorkrub()
UnitAI* GetAI_npc_grark_lorkrub (Creature * pCreature)
Definition at line 300 of file burning_steppes.cpp.
Referenced by AddSC_burning_steppes().
GetAI_npc_klinfran()
UnitAI* GetAI_npc_klinfran (Creature * pCreature)
Definition at line 558 of file burning_steppes.cpp.
Referenced by AddSC_burning_steppes().
GossipHello_npc_klinfran()
bool GossipHello_npc_klinfran (Player * pPlayer, Creature * pCreature)
Definition at line 542 of file burning_steppes.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and QUEST_STAVE_OF_THE_ANCIENTS.
Referenced by AddSC_burning_steppes().
GossipSelect_npc_klinfran()
bool GossipSelect_npc_klinfran (Player * pPlayer, Creature * pCreature, uint32 , uint32)
Definition at line 551 of file burning_steppes.cpp.
References Creature::AI(), and Object::GetObjectGuid().
Referenced by AddSC_burning_steppes().
QuestAccept_npc_grark_lorkrub()
bool QuestAccept_npc_grark_lorkrub (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 305 of file burning_steppes.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_ID_PRECARIOUS_PREDICAMENT.
Referenced by AddSC_burning_steppes().
Variable Documentation
aOutroDialogue
const DialogueEntry aOutroDialogue[] static
Initial value:
=
{
    {SAY_LAST_STAND,    NPC_GRARK_LORKRUB,              5000},
    {SAY_LEXLORT_1,     NPC_SHADOW_OF_LEXLORT,          3000},
    {SAY_LEXLORT_2,     NPC_SHADOW_OF_LEXLORT,          5000},
    {EMOTE_RAISE_AXE,   NPC_HIGH_EXECUTIONER_NUZARK,    4000},
    {EMOTE_LOWER_HAND,  NPC_SHADOW_OF_LEXLORT,          3000},
    {SAY_LEXLORT_3,     NPC_SHADOW_OF_LEXLORT,          3000},
    {NPC_GRARK_LORKRUB, 0,                              5000},
    {SAY_LEXLORT_4,     NPC_SHADOW_OF_LEXLORT,          0},
    {0, 0, 0},
}
Definition at line 73 of file burning_steppes.cpp.