CMaNGOS_WoTLK: ByteBuffer.h File Reference
ByteBuffer.h File Reference
#include "Common.h"
#include "Util/ByteConverter.h"
#include <utf8.h>
Data Structures
class ByteBufferException
struct Unused< T >
class ByteBuffer
struct ByteBuffer::Reserve
struct ByteBuffer::Resize
Functions
template<typename T >
ByteBuffer & operator<< (ByteBuffer &b, std::vector< T > const &v)
template<typename T >
ByteBuffer & operator>> (ByteBuffer &b, std::vector< T > &v)
template<typename T >
ByteBuffer & operator<< (ByteBuffer &b, std::list< T > const &v)
template<typename T >
ByteBuffer & operator>> (ByteBuffer &b, std::list< T > &v)
template<typename K , typename V >
ByteBuffer & operator<< (ByteBuffer &b, std::map< K, V > &m)
template<typename K , typename V >
ByteBuffer & operator>> (ByteBuffer &b, std::map< K, V > &m)
template<>
void ByteBuffer::read_skip< std::string > ()
Function Documentation
ByteBuffer::read_skip< std::string >()
template<> void ByteBuffer::read_skip< std::string > () inline
Definition at line 568 of file ByteBuffer.h.
operator<<() [1/3]
template<typename T > ByteBuffer& operator<< (ByteBuffer & b, std::list< T > const & v) inline
Definition at line 502 of file ByteBuffer.h.
References ByteBuffer::size().
operator<<() [2/3]
template<typename K , typename V > ByteBuffer& operator<< (ByteBuffer & b, std::map< K, V > & m) inline
Definition at line 528 of file ByteBuffer.h.
References ByteBuffer::size().
operator<<() [3/3]
template<typename T > ByteBuffer& operator<< (ByteBuffer & b, std::vector< T > const & v) inline
Definition at line 476 of file ByteBuffer.h.
References ByteBuffer::size().
operator>>() [1/3]
template<typename T > ByteBuffer& operator>> (ByteBuffer & b, std::list< T > & v) inline
Definition at line 513 of file ByteBuffer.h.
References ByteBuffer::clear().
operator>>() [2/3]
template<typename K , typename V > ByteBuffer& operator>> (ByteBuffer & b, std::map< K, V > & m) inline
Definition at line 539 of file ByteBuffer.h.
References ByteBuffer::clear().
operator>>() [3/3]
template<typename T > ByteBuffer& operator>> (ByteBuffer & b, std::vector< T > & v) inline
Definition at line 487 of file ByteBuffer.h.
References ByteBuffer::clear().