CMaNGOS_WoTLK: ChannelMgr.h File Reference
ChannelMgr.h File Reference
#include "Common.h"
#include "Chat/Channel.h"
#include <map>
Data Structures
class ChannelMgr
class AllianceChannelMgr
class HordeChannelMgr
Functions
ChannelMgr * channelMgr (Team team)
Function Documentation
channelMgr()
ChannelMgr* channelMgr (Team team)
Definition at line 26 of file ChannelMgr.cpp.
References ALLIANCE, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, HORDE, MaNGOS::Singleton< T, ThreadingModel, CreatePolicy, LifeTimePolicy >::Instance(), and sWorld.
Referenced by Player::CleanupChannels(), WorldSession::HandleChannelAnnouncementsOpcode(), WorldSession::HandleChannelBanOpcode(), WorldSession::HandleChannelDisplayListQueryOpcode(), WorldSession::HandleChannelInviteOpcode(), WorldSession::HandleChannelKickOpcode(), ChatHandler::HandleChannelListCommand(), WorldSession::HandleChannelListOpcode(), WorldSession::HandleChannelModerateOpcode(), WorldSession::HandleChannelModeratorOpcode(), WorldSession::HandleChannelMuteOpcode(), WorldSession::HandleChannelOwnerOpcode(), WorldSession::HandleChannelPasswordOpcode(), WorldSession::HandleChannelSetOwnerOpcode(), ChatHandler::HandleChannelStaticCommand(), WorldSession::HandleChannelUnbanOpcode(), WorldSession::HandleChannelUnmoderatorOpcode(), WorldSession::HandleChannelUnmuteOpcode(), WorldSession::HandleGetChannelMemberCountOpcode(), WorldSession::HandleJoinChannelOpcode(), WorldSession::HandleLeaveChannelOpcode(), WorldSession::HandleMessagechatOpcode(), and Player::UpdateLocalChannels().