CMaNGOS_WoTLK: chess_event.cpp File Reference
chess_event.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "karazhan.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_echo_of_medivhAI
struct npc_chess_piece_genericAI
struct npc_king_llaneAI
struct npc_warchief_blackhandAI
struct npc_human_conjurerAI
struct npc_orc_warlockAI
struct npc_human_footmanAI
struct npc_orc_gruntAI
struct npc_water_elementalAI
struct npc_summoned_daemonAI
struct npc_human_chargerAI
struct npc_orc_wolfAI
struct npc_human_clericAI
struct npc_orc_necrolyteAI
Enumerations
enum {
EMOTE_LIFT_CURSE = -1532131 , EMOTE_CHEAT = -1532132 , SOUND_ID_GAME_BEGIN = 10338 , SOUND_ID_LOSE_PAWN_PLAYER_1 = 10339 ,
SOUND_ID_LOSE_PAWN_PLAYER_2 = 10340 , SOUND_ID_LOSE_PAWN_PLAYER_3 = 10341 , SOUND_ID_LOSE_PAWN_MEDIVH_1 = 10342 , SOUND_ID_LOSE_PAWN_MEDIVH_2 = 10343 ,
SOUND_ID_LOSE_PAWN_MEDIVH_3 = 10344 , SOUND_ID_LOSE_ROOK_PLAYER = 10345 , SOUND_ID_LOSE_ROOK_MEDIVH = 10346 , SOUND_ID_LOSE_BISHOP_PLAYER = 10347 ,
SOUND_ID_LOSE_BISHOP_MEDIVH = 10348 , SOUND_ID_LOSE_KNIGHT_PLAYER = 10349 , SOUND_ID_LOSE_KNIGHT_MEDIVH = 10350 , SOUND_ID_LOSE_QUEEN_PLAYER = 10351 ,
SOUND_ID_LOSE_QUEEN_MEDIVH = 10352 , SOUND_ID_CHECK_PLAYER = 10353 , SOUND_ID_CHECK_MEDIVH = 10354 , SOUND_ID_WIN_PLAYER = 10355 ,
SOUND_ID_WIN_MEDIVH = 10356 , SOUND_ID_CHEAT_1 = 10357 , SOUND_ID_CHEAT_2 = 10358 , SOUND_ID_CHEAT_3 = 10359 ,
SPELL_MOVE_GENERIC = 30012 , SPELL_MOVE_1 = 32312 , SPELL_MOVE_2 = 37388 , SPELL_CHANGE_FACING = 30284 ,
SPELL_FACE_SQUARE = 30270 , SPELL_MOVE_TO_SQUARE = 30253 , SPELL_MOVE_COOLDOWN = 30543 , SPELL_MOVE_MARKER = 32261 ,
SPELL_DISABLE_SQUARE = 32745 , SPELL_IS_SQUARE_USED = 39400 , SPELL_IN_GAME = 30532 , SPELL_CONTROL_PIECE = 30019 ,
SPELL_RECENTLY_IN_GAME = 30529 , SPELL_CHESS_AI_ATTACK_TIMER = 32226 , SPELL_ACTION_MELEE = 32225 , SPELL_MELEE_DAMAGE = 32247 ,
SPELL_MELEE_FOOTMAN = 32227 , SPELL_MELEE_WATER_ELEM = 37142 , SPELL_MELEE_CHARGER = 37143 , SPELL_MELEE_CLERIC = 37147 ,
SPELL_MELEE_CONJURER = 37149 , SPELL_MELEE_KING_LLANE = 37150 , SPELL_MELEE_GRUNT = 32228 , SPELL_MELEE_DAEMON = 37220 ,
SPELL_MELEE_NECROLYTE = 37337 , SPELL_MELEE_WOLF = 37339 , SPELL_MELEE_WARLOCK = 37345 , SPELL_MELEE_WARCHIEF_BLACKHAND = 37348 ,
SPELL_HAND_OF_MEDIVH_HORDE = 39338 , SPELL_HAND_OF_MEDIVH_ALLIANCE = 39342 , SPELL_FURY_OF_MEDIVH_HORDE = 39341 , SPELL_FURY_OF_MEDIVH_ALLIANCE = 39344 ,
SPELL_FURY_OF_MEDIVH_AURA = 39383 , SPELL_HEROISM = 37471 , SPELL_SWEEP = 37474 , SPELL_BLOODLUST = 37472 ,
SPELL_CLEAVE = 37476 , SPELL_HEROIC_BLOW = 37406 , SPELL_SHIELD_BLOCK = 37414 , SPELL_VICIOUS_STRIKE = 37413 ,
SPELL_WEAPON_DEFLECTION = 37416 , SPELL_SMASH = 37453 , SPELL_STOMP = 37498 , SPELL_BITE = 37454 ,
SPELL_HOWL = 37502 , SPELL_ELEMENTAL_BLAST = 37462 , SPELL_RAIN_OF_FIRE = 37465 , SPELL_FIREBALL = 37463 ,
SPELL_POISON_CLOUD_ACTION = 37775 , SPELL_HEALING = 37455 , SPELL_HOLY_LANCE = 37459 , SPELL_SHADOW_MEND_ACTION = 37824 ,
SPELL_SHADOW_SPEAR = 37461 , SPELL_GEYSER = 37427 , SPELL_WATER_SHIELD = 37432 , SPELL_HELLFIRE_CHESS = 37428 ,
SPELL_FIRE_SHIELD = 37434 , SPELL_TRANSFORM_FOOTMAN = 39350 , SPELL_TRANSFORM_CHARGER = 39352 , SPELL_TRANSFORM_CLERIC = 39353 ,
SPELL_TRANSFORM_WATER_ELEM = 39354 , SPELL_TRANSFORM_CONJURER = 39355 , SPELL_TRANSFORM_KING_LLANE = 39356 , SPELL_TRANSFORM_GRUNT = 39357 ,
SPELL_TRANSFORM_WOLF = 39358 , SPELL_TRANSFORM_NECROLYTE = 39359 , SPELL_TRANSFORM_DAEMON = 39360 , SPELL_TRANSFORM_WARLOCK = 39361 ,
SPELL_TRANSFORM_BLACKHAND = 39362 , NPC_FURY_MEDIVH_VISUAL = 22521 , GOSSIP_ITEM_ORC_GRUNT = -3532006 , GOSSIP_ITEM_ORC_WOLF = -3532007 ,
GOSSIP_ITEM_SUMMONED_DEAMON = -3532008 , GOSSIP_ITEM_ORC_WARLOCK = -3532009 , GOSSIP_ITEM_ORC_NECROLYTE = -3532010 , GOSSIP_ITEM_WARCHIEF_BLACKHAND = -3532011 ,
GOSSIP_ITEM_HUMAN_FOOTMAN = -3532012 , GOSSIP_ITEM_HUMAN_CHARGER = -3532013 , GOSSIP_ITEM_WATER_ELEMENTAL = -3532014 , GOSSIP_ITEM_HUMAN_CONJURER = -3532015 ,
GOSSIP_ITEM_HUMAN_CLERIC = -3532016 , GOSSIP_ITEM_KING_LLANE = -3532017 , GOSSIP_ITEM_RESET_BOARD = -3532018 , GOSSIP_MENU_ID_GRUNT = 10425 ,
GOSSIP_MENU_ID_WOLF = 10439 , GOSSIP_MENU_ID_WARLOCK = 10440 , GOSSIP_MENU_ID_NECROLYTE = 10434 , GOSSIP_MENU_ID_DEAMON = 10426 ,
GOSSIP_MENU_ID_BLACKHAND = 10442 , GOSSIP_MENU_ID_FOOTMAN = 8952 , GOSSIP_MENU_ID_CHARGER = 10414 , GOSSIP_MENU_ID_CONJURER = 10417 ,
GOSSIP_MENU_ID_CLERIC = 10416 , GOSSIP_MENU_ID_ELEMENTAL = 10413 , GOSSIP_MENU_ID_LLANE = 10418 , GOSSIP_MENU_ID_MEDIVH = 10506 ,
GOSSIP_MENU_ID_MEDIVH_BEATEN = 10718 , TARGET_TYPE_RANDOM = 1 , TARGET_TYPE_FRIENDLY = 2
}
Functions
UnitAI * GetAI_npc_echo_of_medivh (Creature *pCreature)
bool GossipHello_npc_echo_of_medivh (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_echo_of_medivh (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipSelect_npc_chess_generic (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool EffectDummyCreature_npc_chess_generic (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_king_llane (Creature *pCreature)
bool GossipHello_npc_king_llane (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_warchief_blackhand (Creature *pCreature)
bool GossipHello_npc_warchief_blackhand (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_human_conjurer (Creature *pCreature)
bool GossipHello_npc_human_conjurer (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_orc_warlock (Creature *pCreature)
bool GossipHello_npc_orc_warlock (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_human_footman (Creature *pCreature)
bool GossipHello_npc_human_footman (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_orc_grunt (Creature *pCreature)
bool GossipHello_npc_orc_grunt (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_water_elemental (Creature *pCreature)
bool GossipHello_npc_water_elemental (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_summoned_daemon (Creature *pCreature)
bool GossipHello_npc_summoned_daemon (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_human_charger (Creature *pCreature)
bool GossipHello_npc_human_charger (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_orc_wolf (Creature *pCreature)
bool GossipHello_npc_orc_wolf (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_human_cleric (Creature *pCreature)
bool GossipHello_npc_human_cleric (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_orc_necrolyte (Creature *pCreature)
bool GossipHello_npc_orc_necrolyte (Player *pPlayer, Creature *pCreature)
void AddSC_chess_event ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_LIFT_CURSE
EMOTE_CHEAT
SOUND_ID_GAME_BEGIN
SOUND_ID_LOSE_PAWN_PLAYER_1
SOUND_ID_LOSE_PAWN_PLAYER_2
SOUND_ID_LOSE_PAWN_PLAYER_3
SOUND_ID_LOSE_PAWN_MEDIVH_1
SOUND_ID_LOSE_PAWN_MEDIVH_2
SOUND_ID_LOSE_PAWN_MEDIVH_3
SOUND_ID_LOSE_ROOK_PLAYER
SOUND_ID_LOSE_ROOK_MEDIVH
SOUND_ID_LOSE_BISHOP_PLAYER
SOUND_ID_LOSE_BISHOP_MEDIVH
SOUND_ID_LOSE_KNIGHT_PLAYER
SOUND_ID_LOSE_KNIGHT_MEDIVH
SOUND_ID_LOSE_QUEEN_PLAYER
SOUND_ID_LOSE_QUEEN_MEDIVH
SOUND_ID_CHECK_PLAYER
SOUND_ID_CHECK_MEDIVH
SOUND_ID_WIN_PLAYER
SOUND_ID_WIN_MEDIVH
SOUND_ID_CHEAT_1
SOUND_ID_CHEAT_2
SOUND_ID_CHEAT_3
SPELL_MOVE_GENERIC
SPELL_MOVE_1
SPELL_MOVE_2
SPELL_CHANGE_FACING
SPELL_FACE_SQUARE
SPELL_MOVE_TO_SQUARE
SPELL_MOVE_COOLDOWN
SPELL_MOVE_MARKER
SPELL_DISABLE_SQUARE
SPELL_IS_SQUARE_USED
SPELL_IN_GAME
SPELL_CONTROL_PIECE
SPELL_RECENTLY_IN_GAME
SPELL_CHESS_AI_ATTACK_TIMER
SPELL_ACTION_MELEE
SPELL_MELEE_DAMAGE
SPELL_MELEE_FOOTMAN
SPELL_MELEE_WATER_ELEM
SPELL_MELEE_CHARGER
SPELL_MELEE_CLERIC
SPELL_MELEE_CONJURER
SPELL_MELEE_KING_LLANE
SPELL_MELEE_GRUNT
SPELL_MELEE_DAEMON
SPELL_MELEE_NECROLYTE
SPELL_MELEE_WOLF
SPELL_MELEE_WARLOCK
SPELL_MELEE_WARCHIEF_BLACKHAND
SPELL_HAND_OF_MEDIVH_HORDE
SPELL_HAND_OF_MEDIVH_ALLIANCE
SPELL_FURY_OF_MEDIVH_HORDE
SPELL_FURY_OF_MEDIVH_ALLIANCE
SPELL_FURY_OF_MEDIVH_AURA
SPELL_HEROISM
SPELL_SWEEP
SPELL_BLOODLUST
SPELL_CLEAVE
SPELL_HEROIC_BLOW
SPELL_SHIELD_BLOCK
SPELL_VICIOUS_STRIKE
SPELL_WEAPON_DEFLECTION
SPELL_SMASH
SPELL_STOMP
SPELL_BITE
SPELL_HOWL
SPELL_ELEMENTAL_BLAST
SPELL_RAIN_OF_FIRE
SPELL_FIREBALL
SPELL_POISON_CLOUD_ACTION
SPELL_HEALING
SPELL_HOLY_LANCE
SPELL_SHADOW_MEND_ACTION
SPELL_SHADOW_SPEAR
SPELL_GEYSER
SPELL_WATER_SHIELD
SPELL_HELLFIRE_CHESS
SPELL_FIRE_SHIELD
SPELL_TRANSFORM_FOOTMAN
SPELL_TRANSFORM_CHARGER
SPELL_TRANSFORM_CLERIC
SPELL_TRANSFORM_WATER_ELEM
SPELL_TRANSFORM_CONJURER
SPELL_TRANSFORM_KING_LLANE
SPELL_TRANSFORM_GRUNT
SPELL_TRANSFORM_WOLF
SPELL_TRANSFORM_NECROLYTE
SPELL_TRANSFORM_DAEMON
SPELL_TRANSFORM_WARLOCK
SPELL_TRANSFORM_BLACKHAND
NPC_FURY_MEDIVH_VISUAL
GOSSIP_ITEM_ORC_GRUNT
GOSSIP_ITEM_ORC_WOLF
GOSSIP_ITEM_SUMMONED_DEAMON
GOSSIP_ITEM_ORC_WARLOCK
GOSSIP_ITEM_ORC_NECROLYTE
GOSSIP_ITEM_WARCHIEF_BLACKHAND
GOSSIP_ITEM_HUMAN_FOOTMAN
GOSSIP_ITEM_HUMAN_CHARGER
GOSSIP_ITEM_WATER_ELEMENTAL
GOSSIP_ITEM_HUMAN_CONJURER
GOSSIP_ITEM_HUMAN_CLERIC
GOSSIP_ITEM_KING_LLANE
GOSSIP_ITEM_RESET_BOARD
GOSSIP_MENU_ID_GRUNT
GOSSIP_MENU_ID_WOLF
GOSSIP_MENU_ID_WARLOCK
GOSSIP_MENU_ID_NECROLYTE
GOSSIP_MENU_ID_DEAMON
GOSSIP_MENU_ID_BLACKHAND
GOSSIP_MENU_ID_FOOTMAN
GOSSIP_MENU_ID_CHARGER
GOSSIP_MENU_ID_CONJURER
GOSSIP_MENU_ID_CLERIC
GOSSIP_MENU_ID_ELEMENTAL
GOSSIP_MENU_ID_LLANE
GOSSIP_MENU_ID_MEDIVH
GOSSIP_MENU_ID_MEDIVH_BEATEN
TARGET_TYPE_RANDOM
TARGET_TYPE_FRIENDLY
Definition at line 28 of file chess_event.cpp.
Function Documentation
AddSC_chess_event()
void AddSC_chess_event ()
Definition at line 1690 of file chess_event.cpp.
References EffectDummyCreature_npc_chess_generic(), Script::GetAI, GetAI_npc_echo_of_medivh(), GetAI_npc_human_charger(), GetAI_npc_human_cleric(), GetAI_npc_human_conjurer(), GetAI_npc_human_footman(), GetAI_npc_king_llane(), GetAI_npc_orc_grunt(), GetAI_npc_orc_necrolyte(), GetAI_npc_orc_warlock(), GetAI_npc_orc_wolf(), GetAI_npc_summoned_daemon(), GetAI_npc_warchief_blackhand(), GetAI_npc_water_elemental(), GossipHello_npc_echo_of_medivh(), GossipHello_npc_human_charger(), GossipHello_npc_human_cleric(), GossipHello_npc_human_conjurer(), GossipHello_npc_human_footman(), GossipHello_npc_king_llane(), GossipHello_npc_orc_grunt(), GossipHello_npc_orc_necrolyte(), GossipHello_npc_orc_warlock(), GossipHello_npc_orc_wolf(), GossipHello_npc_summoned_daemon(), GossipHello_npc_warchief_blackhand(), GossipHello_npc_water_elemental(), GossipSelect_npc_chess_generic(), GossipSelect_npc_echo_of_medivh(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_chess_generic()
bool EffectDummyCreature_npc_chess_generic (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 622 of file chess_event.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_C, Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), Object::GetTypeId(), NPC_CONJURED_WATER_ELEMENTAL, NPC_HUMAN_CHARGER, NPC_HUMAN_CLERIC, NPC_HUMAN_CONJURER, NPC_HUMAN_FOOTMAN, NPC_KING_LLANE, NPC_ORC_GRUNT, NPC_ORC_NECROLYTE, NPC_ORC_WARLOCK, NPC_ORC_WOLF, NPC_SUMMONED_DAEMON, NPC_WARCHIEF_BLACKHAND, UnitAI::SendAIEvent(), Unit::SetFacingToObject(), Unit::SetInFront(), SPELL_ACTION_MELEE, SPELL_DISABLE_SQUARE, SPELL_FACE_SQUARE, SPELL_IS_SQUARE_USED, SPELL_MELEE_CHARGER, SPELL_MELEE_CLERIC, SPELL_MELEE_CONJURER, SPELL_MELEE_DAEMON, SPELL_MELEE_FOOTMAN, SPELL_MELEE_GRUNT, SPELL_MELEE_KING_LLANE, SPELL_MELEE_NECROLYTE, SPELL_MELEE_WARCHIEF_BLACKHAND, SPELL_MELEE_WARLOCK, SPELL_MELEE_WATER_ELEM, SPELL_MELEE_WOLF, SPELL_MOVE_COOLDOWN, SPELL_MOVE_TO_SQUARE, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, and TYPEID_UNIT.
Referenced by AddSC_chess_event().
GetAI_npc_echo_of_medivh()
UnitAI* GetAI_npc_echo_of_medivh (Creature * pCreature)
Definition at line 258 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_human_charger()
UnitAI* GetAI_npc_human_charger (Creature * pCreature)
Definition at line 1442 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_human_cleric()
UnitAI* GetAI_npc_human_cleric (Creature * pCreature)
Definition at line 1594 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_human_conjurer()
UnitAI* GetAI_npc_human_conjurer (Creature * pCreature)
Definition at line 958 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_human_footman()
UnitAI* GetAI_npc_human_footman (Creature * pCreature)
Definition at line 1124 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_king_llane()
UnitAI* GetAI_npc_king_llane (Creature * pCreature)
Definition at line 769 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_orc_grunt()
UnitAI* GetAI_npc_orc_grunt (Creature * pCreature)
Definition at line 1214 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_orc_necrolyte()
UnitAI* GetAI_npc_orc_necrolyte (Creature * pCreature)
Definition at line 1670 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_orc_warlock()
UnitAI* GetAI_npc_orc_warlock (Creature * pCreature)
Definition at line 1034 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_orc_wolf()
UnitAI* GetAI_npc_orc_wolf (Creature * pCreature)
Definition at line 1518 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_summoned_daemon()
UnitAI* GetAI_npc_summoned_daemon (Creature * pCreature)
Definition at line 1366 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_warchief_blackhand()
UnitAI* GetAI_npc_warchief_blackhand (Creature * pCreature)
Definition at line 882 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GetAI_npc_water_elemental()
UnitAI* GetAI_npc_water_elemental (Creature * pCreature)
Definition at line 1290 of file chess_event.cpp.
Referenced by AddSC_chess_event().
GossipHello_npc_echo_of_medivh()
bool GossipHello_npc_echo_of_medivh (Player * pPlayer, Creature * pCreature)
Definition at line 263 of file chess_event.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_RESET_BOARD, GOSSIP_MENU_ID_MEDIVH, GOSSIP_MENU_ID_MEDIVH_BEATEN, GOSSIP_SENDER_MAIN, SPECIAL, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_human_charger()
bool GossipHello_npc_human_charger (Player * pPlayer, Creature * pCreature)
Definition at line 1447 of file chess_event.cpp.
References ALLIANCE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_HUMAN_CHARGER, GOSSIP_MENU_ID_CHARGER, GOSSIP_SENDER_MAIN, Unit::HasAura(), IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_human_cleric()
bool GossipHello_npc_human_cleric (Player * pPlayer, Creature * pCreature)
Definition at line 1599 of file chess_event.cpp.
References ALLIANCE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_HUMAN_CLERIC, GOSSIP_MENU_ID_CLERIC, GOSSIP_SENDER_MAIN, Unit::HasAura(), IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_human_conjurer()
bool GossipHello_npc_human_conjurer (Player * pPlayer, Creature * pCreature)
Definition at line 963 of file chess_event.cpp.
References ALLIANCE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_HUMAN_CONJURER, GOSSIP_MENU_ID_CONJURER, GOSSIP_SENDER_MAIN, Unit::HasAura(), IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_human_footman()
bool GossipHello_npc_human_footman (Player * pPlayer, Creature * pCreature)
Definition at line 1129 of file chess_event.cpp.
References ALLIANCE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_HUMAN_FOOTMAN, GOSSIP_MENU_ID_FOOTMAN, GOSSIP_SENDER_MAIN, Unit::HasAura(), IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_king_llane()
bool GossipHello_npc_king_llane (Player * pPlayer, Creature * pCreature)
Definition at line 774 of file chess_event.cpp.
References ALLIANCE, DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KING_LLANE, GOSSIP_MENU_ID_LLANE, GOSSIP_SENDER_MAIN, Unit::HasAura(), SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_orc_grunt()
bool GossipHello_npc_orc_grunt (Player * pPlayer, Creature * pCreature)
Definition at line 1219 of file chess_event.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ORC_GRUNT, GOSSIP_MENU_ID_GRUNT, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_orc_necrolyte()
bool GossipHello_npc_orc_necrolyte (Player * pPlayer, Creature * pCreature)
Definition at line 1675 of file chess_event.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ORC_NECROLYTE, GOSSIP_MENU_ID_NECROLYTE, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_orc_warlock()
bool GossipHello_npc_orc_warlock (Player * pPlayer, Creature * pCreature)
Definition at line 1039 of file chess_event.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ORC_WARLOCK, GOSSIP_MENU_ID_WARLOCK, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_orc_wolf()
bool GossipHello_npc_orc_wolf (Player * pPlayer, Creature * pCreature)
Definition at line 1523 of file chess_event.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ORC_WOLF, GOSSIP_MENU_ID_WOLF, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_summoned_daemon()
bool GossipHello_npc_summoned_daemon (Player * pPlayer, Creature * pCreature)
Definition at line 1371 of file chess_event.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SUMMONED_DEAMON, GOSSIP_MENU_ID_DEAMON, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_warchief_blackhand()
bool GossipHello_npc_warchief_blackhand (Player * pPlayer, Creature * pCreature)
Definition at line 887 of file chess_event.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_WARCHIEF_BLACKHAND, GOSSIP_MENU_ID_BLACKHAND, GOSSIP_SENDER_MAIN, Unit::HasAura(), HORDE, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipHello_npc_water_elemental()
bool GossipHello_npc_water_elemental (Player * pPlayer, Creature * pCreature)
Definition at line 1295 of file chess_event.cpp.
References ALLIANCE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetTeam(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_WATER_ELEMENTAL, GOSSIP_MENU_ID_ELEMENTAL, GOSSIP_SENDER_MAIN, Unit::HasAura(), IN_PROGRESS, SPECIAL, SPELL_CONTROL_PIECE, SPELL_RECENTLY_IN_GAME, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipSelect_npc_chess_generic()
bool GossipSelect_npc_chess_generic (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 599 of file chess_event.cpp.
References Unit::CastSpell(), DONE, WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, IN_PROGRESS, NOT_STARTED, SPECIAL, SPELL_CONTROL_PIECE, SPELL_IN_GAME, TRIGGERED_OLD_TRIGGERED, and TYPE_CHESS.
Referenced by AddSC_chess_event().
GossipSelect_npc_echo_of_medivh()
bool GossipSelect_npc_echo_of_medivh (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 283 of file chess_event.cpp.
References DONE, WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, and TYPE_CHESS.
Referenced by AddSC_chess_event().