CMaNGOS_WoTLK: OutdoorPvPTF Class Reference
OutdoorPvPTF Class Reference
#include <OutdoorPvPTF.h>
Public Member Functions
OutdoorPvPTF ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleObjectiveComplete (uint32 eventId, const PlayerList &players, Team team) override
void HandleGameObjectCreate (GameObject *go) override
void Update (uint32 diff) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleGameObjectUse (Player *, GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
void UpdateTimerWorldState ()
void CalculateTimerWorldStateValues (uint32 &firstDigit, uint32 &secondDigit, uint32 &hoursLeft)
bool ProcessCaptureEvent (GameObject *go, uint32 towerId, Team team, uint32 newWorldState)
void LockZone (GameObject *go, uint32 towerId, Team team, uint32 newWorldState)
void UnlockZone ()
void LockTowers (const WorldObject *objRef)
void ResetTowers (const WorldObject *objRef)
Private Attributes
uint32 m_towerWorldState [MAX_TF_TOWERS]
uint32 m_zoneWorldState
Team m_towerOwner [MAX_TF_TOWERS]
Team m_zoneOwner
uint32 m_zoneLockTimer
uint8 m_towersAlliance
uint8 m_towersHorde
ObjectGuid m_towerBanners [MAX_TF_TOWERS]
Friends
class OutdoorPvPMgr
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 120 of file OutdoorPvPTF.h.
Constructor & Destructor Documentation
OutdoorPvPTF()
OutdoorPvPTF::OutdoorPvPTF ()
Definition at line 28 of file OutdoorPvPTF.cpp.
References m_towerOwner, m_towerWorldState, TEAM_NONE, WORLD_STATE_TF_EAST_TOWER_NEUTRAL, WORLD_STATE_TF_NORTH_TOWER_NEUTRAL, WORLD_STATE_TF_SOUTH_EAST_TOWER_NEUTRAL, WORLD_STATE_TF_SOUTH_TOWER_NEUTRAL, and WORLD_STATE_TF_WEST_TOWER_NEUTRAL.
Member Function Documentation
CalculateTimerWorldStateValues()
void OutdoorPvPTF::CalculateTimerWorldStateValues (uint32 & firstDigit, uint32 & secondDigit, uint32 & hoursLeft) private
Definition at line 351 of file OutdoorPvPTF.cpp.
References m_zoneLockTimer.
Referenced by FillInitialWorldStates(), and UpdateTimerWorldState().
FillInitialWorldStates()
void OutdoorPvPTF::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 46 of file OutdoorPvPTF.cpp.
References CalculateTimerWorldStateValues(), FillInitialWorldState(), m_towersAlliance, m_towersHorde, m_towerWorldState, m_zoneWorldState, WORLD_STATE_ADD, WORLD_STATE_TF_TIME_HOURS, WORLD_STATE_TF_TIME_MIN_FIRST_DIGIT, WORLD_STATE_TF_TIME_MIN_SECOND_DIGIT, WORLD_STATE_TF_TOWER_COUNT_A, WORLD_STATE_TF_TOWER_COUNT_H, and WORLD_STATE_TF_TOWERS_CONTROLLED.
HandleEvent()
bool OutdoorPvPTF::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 144 of file OutdoorPvPTF.cpp.
References Object::GetEntry(), Object::IsGameObject(), m_towerOwner, MAX_TF_TOWERS, ProcessCaptureEvent(), sWorld, terokkarTowerEvents, terokkarTowers, and ZONE_ID_TEROKKAR_FOREST.
HandleGameObjectCreate()
void OutdoorPvPTF::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 95 of file OutdoorPvPTF.cpp.
References OutdoorPvP::GetBannerArtKit(), Object::GetEntry(), Object::GetObjectGuid(), GO_TOWER_BANNER_EAST, GO_TOWER_BANNER_NORTH, GO_TOWER_BANNER_SOUTH, GO_TOWER_BANNER_SOUTH_EAST, GO_TOWER_BANNER_WEST, OutdoorPvP::HandleGameObjectCreate(), m_towerBanners, m_towerOwner, and GameObject::SetGoArtKit().
HandleObjectiveComplete()
void OutdoorPvPTF::HandleObjectiveComplete (uint32 eventId, const PlayerList & players, Team team) override virtual
Reimplemented from OutdoorPvP.
Definition at line 124 of file OutdoorPvPTF.cpp.
References ALLIANCE, QUEST_SPIRITS_OF_AUCHINDOUM_ALLIANCE, QUEST_SPIRITS_OF_AUCHINDOUM_HORDE, and terokkarTowerEvents.
HandlePlayerEnterZone()
void OutdoorPvPTF::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 75 of file OutdoorPvPTF.cpp.
References Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), m_zoneOwner, Unit::RemoveAurasDueToSpell(), SPELL_AUCHINDOUN_BLESSING, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerLeaveZone()
void OutdoorPvPTF::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 87 of file OutdoorPvPTF.cpp.
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and SPELL_AUCHINDOUN_BLESSING.
LockTowers()
void OutdoorPvPTF::LockTowers (const WorldObject * objRef) private
Definition at line 361 of file OutdoorPvPTF.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, Map::GetGameObject(), WorldObject::GetMap(), GO_JUST_DEACTIVATED, m_towerBanners, m_zoneOwner, MAX_TF_TOWERS, sOutdoorPvPMgr, and terokkarTowers.
Referenced by LockZone().
LockZone()
void OutdoorPvPTF::LockZone (GameObject * go, uint32 towerId, Team team, uint32 newWorldState) private
Definition at line 246 of file OutdoorPvPTF.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), LANG_OPVP_TF_CAPTURE_ALL_TOWERS_A, LANG_OPVP_TF_CAPTURE_ALL_TOWERS_H, LockTowers(), m_towerWorldState, m_zoneLockTimer, m_zoneOwner, m_zoneWorldState, OutdoorPvP::SendUpdateWorldState(), SPELL_AUCHINDOUN_BLESSING, sWorld, TIMER_TF_LOCK_TIME, UpdateTimerWorldState(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_TF_LOCKED_ALLIANCE, WORLD_STATE_TF_LOCKED_HORDE, and ZONE_ID_TEROKKAR_FOREST.
Referenced by ProcessCaptureEvent().
ProcessCaptureEvent()
bool OutdoorPvPTF::ProcessCaptureEvent (GameObject * go, uint32 towerId, Team team, uint32 newWorldState) private
Definition at line 177 of file OutdoorPvPTF.cpp.
References ALLIANCE, CAPTURE_ANIM_ALLIANCE, CAPTURE_ANIM_HORDE, CAPTURE_ANIM_NEUTRAL, CAPTURE_ARTKIT_ALLIANCE, CAPTURE_ARTKIT_HORDE, CAPTURE_ARTKIT_NEUTRAL, HORDE, LockZone(), m_towerOwner, m_towersAlliance, m_towersHorde, m_towerWorldState, MAX_TF_TOWERS, OutdoorPvP::SendUpdateWorldState(), OutdoorPvP::SetBannerVisual(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_TF_TOWER_COUNT_A, and WORLD_STATE_TF_TOWER_COUNT_H.
Referenced by HandleEvent().
ResetTowers()
void OutdoorPvPTF::ResetTowers (const WorldObject * objRef) private
Definition at line 377 of file OutdoorPvPTF.cpp.
References CAPTURE_ANIM_NEUTRAL, CAPTURE_ARTKIT_NEUTRAL, CAPTURE_SLIDER_MIDDLE, Map::GetGameObject(), WorldObject::GetMap(), m_towerBanners, MAX_TF_TOWERS, OutdoorPvP::SetBannerVisual(), sOutdoorPvPMgr, and terokkarTowers.
Referenced by UnlockZone().
SendRemoveWorldStates()
void OutdoorPvPTF::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 67 of file OutdoorPvPTF.cpp.
References m_towerWorldState, m_zoneWorldState, Player::SendUpdateWorldState(), and WORLD_STATE_REMOVE.
UnlockZone()
void OutdoorPvPTF::UnlockZone () private
Definition at line 271 of file OutdoorPvPTF.cpp.
References OutdoorPvP::BuffTeam(), m_towersAlliance, m_towersHorde, m_towerWorldState, m_zoneOwner, OutdoorPvP::m_zonePlayers, m_zoneWorldState, ResetTowers(), OutdoorPvP::SendUpdateWorldState(), sObjectMgr, SPELL_AUCHINDOUN_BLESSING, TEAM_NONE, WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_TF_EAST_TOWER_NEUTRAL, WORLD_STATE_TF_NORTH_TOWER_NEUTRAL, WORLD_STATE_TF_SOUTH_EAST_TOWER_NEUTRAL, WORLD_STATE_TF_SOUTH_TOWER_NEUTRAL, WORLD_STATE_TF_TOWER_COUNT_A, WORLD_STATE_TF_TOWER_COUNT_H, WORLD_STATE_TF_TOWERS_CONTROLLED, and WORLD_STATE_TF_WEST_TOWER_NEUTRAL.
Referenced by Update().
Update()
void OutdoorPvPTF::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
Definition at line 312 of file OutdoorPvPTF.cpp.
References m_zoneLockTimer, UnlockZone(), and UpdateTimerWorldState().
UpdateTimerWorldState()
void OutdoorPvPTF::UpdateTimerWorldState () private
Definition at line 340 of file OutdoorPvPTF.cpp.
References CalculateTimerWorldStateValues(), OutdoorPvP::SendUpdateWorldState(), WORLD_STATE_TF_TIME_HOURS, WORLD_STATE_TF_TIME_MIN_FIRST_DIGIT, and WORLD_STATE_TF_TIME_MIN_SECOND_DIGIT.
Referenced by LockZone(), and Update().
Friends And Related Function Documentation
OutdoorPvPMgr
friend class OutdoorPvPMgr friend
Definition at line 122 of file OutdoorPvPTF.h.
Field Documentation
m_towerBanners
ObjectGuid OutdoorPvPTF::m_towerBanners[MAX_TF_TOWERS] private
Definition at line 163 of file OutdoorPvPTF.h.
Referenced by HandleGameObjectCreate(), LockTowers(), and ResetTowers().
m_towerOwner
Team OutdoorPvPTF::m_towerOwner[MAX_TF_TOWERS] private
Definition at line 154 of file OutdoorPvPTF.h.
Referenced by HandleEvent(), HandleGameObjectCreate(), OutdoorPvPTF(), and ProcessCaptureEvent().
m_towersAlliance
uint8 OutdoorPvPTF::m_towersAlliance private
Definition at line 160 of file OutdoorPvPTF.h.
Referenced by FillInitialWorldStates(), ProcessCaptureEvent(), and UnlockZone().
m_towersHorde
uint8 OutdoorPvPTF::m_towersHorde private
Definition at line 161 of file OutdoorPvPTF.h.
Referenced by FillInitialWorldStates(), ProcessCaptureEvent(), and UnlockZone().
m_towerWorldState
uint32 OutdoorPvPTF::m_towerWorldState[MAX_TF_TOWERS] private
Definition at line 151 of file OutdoorPvPTF.h.
Referenced by FillInitialWorldStates(), LockZone(), OutdoorPvPTF(), ProcessCaptureEvent(), SendRemoveWorldStates(), and UnlockZone().
m_zoneLockTimer
uint32 OutdoorPvPTF::m_zoneLockTimer private
Definition at line 157 of file OutdoorPvPTF.h.
Referenced by CalculateTimerWorldStateValues(), LockZone(), and Update().
m_zoneOwner
Team OutdoorPvPTF::m_zoneOwner private
Definition at line 155 of file OutdoorPvPTF.h.
Referenced by HandlePlayerEnterZone(), LockTowers(), LockZone(), and UnlockZone().
m_zoneWorldState
uint32 OutdoorPvPTF::m_zoneWorldState private
Definition at line 152 of file OutdoorPvPTF.h.
Referenced by FillInitialWorldStates(), LockZone(), SendRemoveWorldStates(), and UnlockZone().
The documentation for this class was generated from the following files:
OutdoorPvPTF.h
OutdoorPvPTF.cpp