CMaNGOS_WoTLK: MaNGOS::CannibalizeObjectCheck Class Reference
MaNGOS::CannibalizeObjectCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
CannibalizeObjectCheck (Unit const *fobj, float range)
WorldObject const & GetFocusObject () const
bool operator() (Player *u)
bool operator() (Corpse *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Private Attributes
Unit const * i_fobj
float i_range
Detailed Description
Definition at line 634 of file GridNotifiers.h.
Constructor & Destructor Documentation
CannibalizeObjectCheck()
MaNGOS::CannibalizeObjectCheck::CannibalizeObjectCheck (Unit const * fobj, float range) inline
Definition at line 637 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::CannibalizeObjectCheck::GetFocusObject () const inline
Definition at line 638 of file GridNotifiers.h.
References i_fobj.
operator()() [1/4]
bool CannibalizeObjectCheck::operator() (Corpse * u)
Definition at line 239 of file GridNotifiers.cpp.
References Unit::CanAssist(), CORPSE_BONES, ObjectAccessor::FindPlayer(), Corpse::GetOwnerGuid(), Corpse::GetType(), i_fobj, i_range, and WorldObject::IsWithinDistInMap().
operator()() [2/4]
bool MaNGOS::CannibalizeObjectCheck::operator() (Creature * u) inline
Definition at line 647 of file GridNotifiers.h.
References Unit::CanAssist(), CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD, Unit::GetCreatureTypeMask(), i_fobj, i_range, Unit::IsAlive(), Unit::IsTaxiFlying(), and WorldObject::IsWithinDistInMap().
operator()() [3/4]
template<class NOT_INTERESTED > bool MaNGOS::CannibalizeObjectCheck::operator() (NOT_INTERESTED *) inline
Definition at line 655 of file GridNotifiers.h.
operator()() [4/4]
bool MaNGOS::CannibalizeObjectCheck::operator() (Player * u) inline
Definition at line 639 of file GridNotifiers.h.
References Unit::CanAssist(), i_fobj, i_range, Unit::IsAlive(), Unit::IsTaxiFlying(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_fobj
Unit const* MaNGOS::CannibalizeObjectCheck::i_fobj private
Definition at line 657 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::CannibalizeObjectCheck::i_range private
Definition at line 658 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp