CMaNGOS_WoTLK: OutdoorPvPMgr Class Reference
OutdoorPvPMgr Class Reference
#include <OutdoorPvPMgr.h>
Public Member Functions
OutdoorPvPMgr ()
~OutdoorPvPMgr ()
void InitOutdoorPvP ()
Function which loads all outdoor pvp scripts.
void HandlePlayerEnterZone (Player *player, uint32 zoneId)
Function that handles the players which enters a specific zone.
void HandlePlayerLeaveZone (Player *player, uint32 zoneId)
Function that handles the player who leaves a specific zone.
void HandlePlayerEnterArea (Player *player, uint32 zoneId, uint32 areaId)
Function that handles the player who enters a specific area in a specific zone id.
void HandlePlayerLeaveArea (Player *player, uint32 zoneId, uint32 areaId)
Function that handles the player who leaves a specific area in a specific zone id.
OutdoorPvP * GetScript (uint32 zoneId)
void Update (uint32 diff)
CapturePointSliderMap const * GetCapturePointSliderMap () const
void SetCapturePointSlider (uint32 entry, CapturePointSlider value)
Battlefield * GetBattlefieldById (uint32 id)
Function that returns the battlefield script by id.
Private Member Functions
OutdoorPvP * GetScriptOfAffectedZone (uint32 zoneId)
Private Attributes
OutdoorPvP * m_scripts [MAX_OPVP_ID]
CapturePointSliderMap m_capturePointSlider
ShortIntervalTimer m_updateTimer
Detailed Description
Definition at line 104 of file OutdoorPvPMgr.h.
Constructor & Destructor Documentation
OutdoorPvPMgr()
OutdoorPvPMgr::OutdoorPvPMgr ()
Definition at line 36 of file OutdoorPvPMgr.cpp.
References m_scripts, m_updateTimer, ShortIntervalTimer::SetInterval(), and TIMER_OPVP_MGR_UPDATE.
~OutdoorPvPMgr()
OutdoorPvPMgr::~OutdoorPvPMgr ()
Definition at line 42 of file OutdoorPvPMgr.cpp.
References m_scripts.
Member Function Documentation
GetBattlefieldById()
Battlefield * OutdoorPvPMgr::GetBattlefieldById (uint32 id)
Function that returns the battlefield script by id.
Parameters
battlefield id
Definition at line 214 of file OutdoorPvPMgr.cpp.
References m_scripts.
GetCapturePointSliderMap()
CapturePointSliderMap const* OutdoorPvPMgr::GetCapturePointSliderMap () const inline
Definition at line 131 of file OutdoorPvPMgr.h.
References m_capturePointSlider.
GetScript()
OutdoorPvP * OutdoorPvPMgr::GetScript (uint32 zoneId)
Definition at line 82 of file OutdoorPvPMgr.cpp.
References m_scripts, OPVP_ID_EP, OPVP_ID_GH, OPVP_ID_HP, OPVP_ID_NA, OPVP_ID_SI, OPVP_ID_TF, OPVP_ID_WG, OPVP_ID_ZM, ZONE_ID_EASTERN_PLAGUELANDS, ZONE_ID_GRIZZLY_HILLS, ZONE_ID_HELLFIRE_PENINSULA, ZONE_ID_NAGRAND, ZONE_ID_SILITHUS, ZONE_ID_TEROKKAR_FOREST, ZONE_ID_WINTERGRASP, and ZONE_ID_ZANGARMARSH.
Referenced by HandlePlayerEnterArea(), HandlePlayerEnterZone(), HandlePlayerLeaveArea(), and HandlePlayerLeaveZone().
GetScriptOfAffectedZone()
OutdoorPvP * OutdoorPvPMgr::GetScriptOfAffectedZone (uint32 zoneId) private
Definition at line 107 of file OutdoorPvPMgr.cpp.
References m_scripts, OPVP_ID_EP, OPVP_ID_HP, OPVP_ID_SI, OPVP_ID_TF, OPVP_ID_ZM, ZONE_ID_AUCHENAI_CRYPTS, ZONE_ID_BLOOD_FURNACE, ZONE_ID_GATES_OF_AQ, ZONE_ID_HELLFIRE_CITADEL, ZONE_ID_HELLFIRE_RAMPARTS, ZONE_ID_MANA_TOMBS, ZONE_ID_RUINS_OF_AQ, ZONE_ID_SCHOLOMANCE, ZONE_ID_SETHEKK_HALLS, ZONE_ID_SHADOW_LABYRINTH, ZONE_ID_SHATTERED_HALLS, ZONE_ID_SLAVE_PENS, ZONE_ID_STEAMVAULT, ZONE_ID_STRATHOLME, ZONE_ID_TEMPLE_OF_AQ, and ZONE_ID_UNDERBOG.
Referenced by HandlePlayerEnterArea(), HandlePlayerEnterZone(), HandlePlayerLeaveArea(), and HandlePlayerLeaveZone().
HandlePlayerEnterArea()
void OutdoorPvPMgr::HandlePlayerEnterArea (Player * player, uint32 zoneId, uint32 areaId)
Function that handles the player who enters a specific area in a specific zone id.
Parameters
player to be handled in the event
zone id used for the current outdoor pvp script
area id refered by the function
Definition at line 173 of file OutdoorPvPMgr.cpp.
References GetScript(), and GetScriptOfAffectedZone().
HandlePlayerEnterZone()
void OutdoorPvPMgr::HandlePlayerEnterZone (Player * player, uint32 zoneId)
Function that handles the players which enters a specific zone.
Parameters
player to be handled in the event
zone id used for the current outdoor pvp script
Definition at line 143 of file OutdoorPvPMgr.cpp.
References GetScript(), and GetScriptOfAffectedZone().
HandlePlayerLeaveArea()
void OutdoorPvPMgr::HandlePlayerLeaveArea (Player * player, uint32 zoneId, uint32 areaId)
Function that handles the player who leaves a specific area in a specific zone id.
Parameters
player to be handled in the event
zone id used for the current outdoor pvp script
area id refered by the function
Definition at line 188 of file OutdoorPvPMgr.cpp.
References GetScript(), and GetScriptOfAffectedZone().
HandlePlayerLeaveZone()
void OutdoorPvPMgr::HandlePlayerLeaveZone (Player * player, uint32 zoneId)
Function that handles the player who leaves a specific zone.
Parameters
player to be handled in the event
zone id used for the current outdoor pvp script
Definition at line 157 of file OutdoorPvPMgr.cpp.
References GetScript(), and GetScriptOfAffectedZone().
InitOutdoorPvP()
void OutdoorPvPMgr::InitOutdoorPvP ()
Function which loads all outdoor pvp scripts.
Definition at line 65 of file OutdoorPvPMgr.cpp.
References LOAD_BATTLEFIELD, LOAD_OPVP_ZONE, and sLog.
SetCapturePointSlider()
void OutdoorPvPMgr::SetCapturePointSlider (uint32 entry, CapturePointSlider value) inline
Definition at line 132 of file OutdoorPvPMgr.h.
References m_capturePointSlider.
Update()
void OutdoorPvPMgr::Update (uint32 diff)
Definition at line 196 of file OutdoorPvPMgr.cpp.
References ShortIntervalTimer::GetCurrent(), m_scripts, m_updateTimer, ShortIntervalTimer::Passed(), ShortIntervalTimer::Reset(), and ShortIntervalTimer::Update().
Field Documentation
m_capturePointSlider
CapturePointSliderMap OutdoorPvPMgr::m_capturePointSlider private
Definition at line 144 of file OutdoorPvPMgr.h.
Referenced by GetCapturePointSliderMap(), and SetCapturePointSlider().
m_scripts
OutdoorPvP* OutdoorPvPMgr::m_scripts[MAX_OPVP_ID] private
Definition at line 142 of file OutdoorPvPMgr.h.
Referenced by GetBattlefieldById(), GetScript(), GetScriptOfAffectedZone(), OutdoorPvPMgr(), Update(), and ~OutdoorPvPMgr().
m_updateTimer
ShortIntervalTimer OutdoorPvPMgr::m_updateTimer private
Definition at line 147 of file OutdoorPvPMgr.h.
Referenced by OutdoorPvPMgr(), and Update().
The documentation for this class was generated from the following files:
OutdoorPvPMgr.h
OutdoorPvPMgr.cpp