CMaNGOS_WoTLK: PlayerbotPriestAI Class Reference
PlayerbotPriestAI Class Reference
#include <PlayerbotPriestAI.h>
Public Member Functions
PlayerbotPriestAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotPriestAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
uint32 Neutralize (uint8 creatureType) override
void DoNonCombatActions () override
bool CastHoTOnTank ()
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns CastSpell (uint32 nextAction, Unit *pTarget=nullptr)
CombatManeuverReturns HealPlayer (Player *target) override
CombatManeuverReturns ResurrectPlayer (Player *target) override
CombatManeuverReturns DispelPlayer (Player *target=nullptr)
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Static Private Member Functions
static bool BuffHelper (PlayerbotAI *ai, uint32 spellId, Unit *target)
Private Attributes
uint32 BINDING_HEAL
uint32 CIRCLE_OF_HEALING
uint32 CLEARCASTING
uint32 DESPERATE_PRAYER
uint32 FLASH_HEAL
uint32 GREATER_HEAL
uint32 HEAL
uint32 HOLY_FIRE
uint32 HOLY_NOVA
uint32 LESSER_HEAL
uint32 MANA_BURN
uint32 PRAYER_OF_HEALING
uint32 PRAYER_OF_MENDING
uint32 RENEW
uint32 RESURRECTION
uint32 SHACKLE_UNDEAD
uint32 SMITE
uint32 CURE_DISEASE
uint32 ABOLISH_DISEASE
uint32 PRIEST_DISPEL_MAGIC
uint32 SHOOT
uint32 FADE
uint32 SHADOW_WORD_PAIN
uint32 MIND_BLAST
uint32 SCREAM
uint32 MIND_FLAY
uint32 DEVOURING_PLAGUE
uint32 SHADOW_PROTECTION
uint32 VAMPIRIC_TOUCH
uint32 PRAYER_OF_SHADOW_PROTECTION
uint32 SHADOWFIEND
uint32 MIND_SEAR
uint32 SHADOWFORM
uint32 VAMPIRIC_EMBRACE
uint32 POWER_WORD_SHIELD
uint32 INNER_FIRE
uint32 POWER_WORD_FORTITUDE
uint32 PRAYER_OF_FORTITUDE
uint32 FEAR_WARD
uint32 POWER_INFUSION
uint32 MASS_DISPEL
uint32 PENANCE
uint32 DIVINE_SPIRIT
uint32 PRAYER_OF_SPIRIT
uint32 INNER_FOCUS
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 95 of file PlayerbotPriestAI.h.
Constructor & Destructor Documentation
PlayerbotPriestAI()
PlayerbotPriestAI::PlayerbotPriestAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotPriestAI.cpp.
References ABOLISH_DISEASE, ABOLISH_DISEASE_1, ARCANE_TORRENT, ARCANE_TORRENT_MANA_CLASSES, BERSERKING, BERSERKING_ALL, BINDING_HEAL, BINDING_HEAL_1, CIRCLE_OF_HEALING, CIRCLE_OF_HEALING_1, CURE_DISEASE, CURE_DISEASE_1, DESPERATE_PRAYER, DESPERATE_PRAYER_1, DEVOURING_PLAGUE, DEVOURING_PLAGUE_1, DISPEL_MAGIC_1, DIVINE_SPIRIT, DIVINE_SPIRIT_1, EVERY_MAN_FOR_HIMSELF, EVERY_MAN_FOR_HIMSELF_ALL, FADE, FADE_1, FEAR_WARD, FEAR_WARD_1, FLASH_HEAL, FLASH_HEAL_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_PRIEST, GREATER_HEAL, GREATER_HEAL_1, HEAL, HEAL_1, HOLY_FIRE, HOLY_FIRE_1, HOLY_NOVA, HOLY_NOVA_1, PlayerbotAI::initSpell(), INNER_FIRE, INNER_FIRE_1, INNER_FOCUS, INNER_FOCUS_1, LESSER_HEAL, LESSER_HEAL_1, PlayerbotClassAI::m_ai, MANA_BURN, MANA_BURN_1, MASS_DISPEL, MASS_DISPEL_1, MIND_BLAST, MIND_BLAST_1, MIND_FLAY, MIND_FLAY_1, MIND_SEAR, MIND_SEAR_1, PENANCE, PENANCE_1, POWER_INFUSION, POWER_INFUSION_1, POWER_WORD_FORTITUDE, POWER_WORD_FORTITUDE_1, POWER_WORD_SHIELD, POWER_WORD_SHIELD_1, PRAYER_OF_FORTITUDE, PRAYER_OF_FORTITUDE_1, PRAYER_OF_HEALING, PRAYER_OF_HEALING_1, PRAYER_OF_MENDING, PRAYER_OF_MENDING_1, PRAYER_OF_SHADOW_PROTECTION, PRAYER_OF_SHADOW_PROTECTION_1, PRAYER_OF_SPIRIT, PRAYER_OF_SPIRIT_1, PRIEST_DISPEL_MAGIC, PSYCHIC_SCREAM_1, PlayerbotClassAI::RECENTLY_BANDAGED, RENEW, RENEW_1, RESURRECTION, RESURRECTION_1, SCREAM, SHACKLE_UNDEAD, SHACKLE_UNDEAD_1, SHADOW_PROTECTION, SHADOW_PROTECTION_1, SHADOW_WORD_PAIN, SHADOW_WORD_PAIN_1, SHADOWFIEND, SHADOWFIEND_1, SHADOWFORM, SHADOWFORM_1, SHADOWMELD, SHADOWMELD_ALL, SHOOT, SHOOT_1, SMITE, SMITE_1, STONEFORM, STONEFORM_ALL, VAMPIRIC_EMBRACE, VAMPIRIC_EMBRACE_1, VAMPIRIC_TOUCH, VAMPIRIC_TOUCH_1, WILL_OF_THE_FORSAKEN, and WILL_OF_THE_FORSAKEN_ALL.
~PlayerbotPriestAI()
PlayerbotPriestAI::~PlayerbotPriestAI () virtual
Definition at line 91 of file PlayerbotPriestAI.cpp.
Member Function Documentation
BuffHelper()
bool PlayerbotPriestAI::BuffHelper (PlayerbotAI * ai, uint32 spellId, Unit * target) static private
Definition at line 568 of file PlayerbotPriestAI.cpp.
References PlayerbotAI::Buff(), Unit::GetPet(), Unit::HasAuraType(), SPELL_AURA_MOD_UNATTACKABLE, and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
CastHoTOnTank()
bool PlayerbotPriestAI::CastHoTOnTank ()
Definition at line 589 of file PlayerbotPriestAI.cpp.
References CastSpell(), PlayerbotAI::GetGroupTank(), PlayerbotAI::In_Reach(), PlayerbotAI::IsHealer(), PlayerbotClassAI::m_ai, RENEW, and RETURN_CONTINUE.
CastSpell()
CombatManeuverReturns PlayerbotPriestAI::CastSpell (uint32 nextAction, Unit * pTarget = nullptr) inline private
Definition at line 118 of file PlayerbotPriestAI.h.
References PlayerbotClassAI::CastSpellWand(), and SHOOT.
Referenced by CastHoTOnTank(), DispelPlayer(), DoFirstCombatManeuverPVE(), DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and HealPlayer().
DispelPlayer()
CombatManeuverReturns PlayerbotPriestAI::DispelPlayer (Player * target = nullptr) private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 471 of file PlayerbotPriestAI.cpp.
References ABOLISH_DISEASE, CastSpell(), CURE_DISEASE, DISPEL_DISEASE, DISPEL_MAGIC, PlayerbotClassAI::DispelPlayer(), PlayerbotClassAI::GetDispelTarget(), PRIEST_DISPEL_MAGIC, RETURN_CONTINUE, and RETURN_NO_ACTION_OK.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotPriestAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 93 of file PlayerbotPriestAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotClassAI::GetHealTarget(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), HealPlayer(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_HEAL, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotPriestAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 135 of file PlayerbotPriestAI.cpp.
References CastSpell(), EFFECT_INDEX_0, PlayerbotClassAI::GetHealTarget(), Unit::HasAura(), PlayerbotAI::In_Reach(), PlayerbotAI::IsHealer(), JOB_TANK, PlayerbotClassAI::m_ai, PRAYER_OF_MENDING, RETURN_CONTINUE, RETURN_FINISHED_FIRST_MOVES, and RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotPriestAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 149 of file PlayerbotPriestAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotPriestAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 154 of file PlayerbotPriestAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotPriestAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 171 of file PlayerbotPriestAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, Unit::CanReachWithMeleeAttack(), CastSpell(), PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, DESPERATE_PRAYER, DEVOURING_PLAGUE, DispelPlayer(), EFFECT_INDEX_0, FADE, FEAR_WARD, PlayerbotAI::FindAttacker(), PlayerbotClassAI::FindTargetAndHeal(), PlayerbotAI::GetCombatStyle(), PlayerbotClassAI::GetHealTarget(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetManaPercent(), Unit::GetPet(), Unit::GetVictim(), Player::GetWeaponForAttack(), Unit::HasAura(), PlayerbotAI::HasDispelOrder(), HealPlayer(), HOLY_FIRE, PlayerbotAI::In_Reach(), INNER_FOCUS, PlayerbotAI::IsElite(), PlayerbotAI::IsHealer(), PlayerbotAI::IsImmuneToSchool(), PlayerbotAI::IsMainHealer(), PlayerbotAI::IsNeutralized(), WorldObject::IsSpellReady(), JOB_MAIN_TANK, JOB_TANK, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_master, MIND_BLAST, MIND_FLAY, PENANCE, POWER_INFUSION, POWER_WORD_SHIELD, PRIEST_SPEC_DISCIPLINE, PRIEST_SPEC_HOLY, PRIEST_SPEC_SHADOW, RANGED_ATTACK, RETURN_CONTINUE, RETURN_NO_ACTION_OK, PlayerbotAI::SetCombatStyle(), PlayerbotAI::SetIgnoreUpdateTime(), SHADOW_WORD_PAIN, SHADOWFIEND, SHADOWFORM, SHOOT, SMITE, SPELL_SCHOOL_MASK_SHADOW, PlayerbotAI::TellMaster(), and VAMPIRIC_TOUCH.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotPriestAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 361 of file PlayerbotPriestAI.cpp.
References CastSpell(), DoNextCombatManeuverPVE(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetScenarioType(), GREATER_HEAL, PlayerbotAI::HasAura(), HEAL, PlayerbotAI::In_Reach(), PlayerbotClassAI::m_ai, MIND_BLAST, RENEW, RETURN_ANY_OK, RETURN_CONTINUE, PlayerbotAI::SCENARIO_PVP_DUEL, SCREAM, SHADOW_WORD_PAIN, SMITE, and PlayerbotAI::TellMaster().
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotPriestAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 499 of file PlayerbotPriestAI.cpp.
References PlayerbotClassAI::Buff(), BuffHelper(), DispelPlayer(), DIVINE_SPIRIT, PlayerbotClassAI::EatDrinkBandage(), PlayerbotAI::GetCombatOrder(), PlayerbotClassAI::GetHealTarget(), PlayerbotClassAI::GetResurrectionTarget(), PlayerbotAI::HasDispelOrder(), PlayerbotAI::HasSpellReagents(), HealPlayer(), INNER_FIRE, Unit::IsAlive(), PlayerbotAI::IsHealer(), JOB_ALL, JOB_MANAONLY, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::NeedGroupBuff(), PlayerbotAI::ORDERS_RESIST_SHADOW, POWER_WORD_FORTITUDE, PRAYER_OF_FORTITUDE, PRAYER_OF_SHADOW_PROTECTION, PRAYER_OF_SPIRIT, PRIEST_SPEC_SHADOW, ResurrectPlayer(), RETURN_CONTINUE, PlayerbotAI::SelfBuff(), SHADOW_PROTECTION, SHADOWFORM, SPELL_CAST_OK, and VAMPIRIC_EMBRACE.
HealPlayer()
CombatManeuverReturns PlayerbotPriestAI::HealPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 396 of file PlayerbotPriestAI.cpp.
References BINDING_HEAL, PlayerbotAI::CastSpell(), CastSpell(), EFFECT_INDEX_0, FLASH_HEAL, Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetManaPercent(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), PlayerbotClassAI::GetTargetJob(), GREATER_HEAL, Unit::HasAura(), HEAL, PlayerbotClassAI::HealPlayer(), PlayerbotAI::In_Reach(), INNER_FOCUS, PlayerbotAI::IsInCombat(), WorldObject::IsSpellReady(), JOB_MAIN_TANK, JOB_TANK, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), PlayerbotAI::MOVEMENT_STAY, POWER_WORD_SHIELD, PRAYER_OF_MENDING, RENEW, RETURN_CONTINUE, RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_OK, SPELL_CAST_OK, and WEAKNED_SOUL.
Referenced by DoFirstCombatManeuver(), DoNextCombatManeuverPVE(), and DoNonCombatActions().
Neutralize()
uint32 PlayerbotPriestAI::Neutralize (uint8 creatureType) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 601 of file PlayerbotPriestAI.cpp.
References CREATURE_TYPE_UNDEAD, PlayerbotClassAI::m_ai, SHACKLE_UNDEAD, and PlayerbotAI::TellMaster().
ResurrectPlayer()
CombatManeuverReturns PlayerbotPriestAI::ResurrectPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 452 of file PlayerbotPriestAI.cpp.
References PlayerbotAI::CastSpell(), WorldObject::GetName(), PlayerbotAI::In_Reach(), PlayerbotAI::IsInCombat(), LANG_UNIVERSAL, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, RESURRECTION, PlayerbotClassAI::ResurrectPlayer(), RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, Player::Say(), and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
Field Documentation
ABOLISH_DISEASE
uint32 PlayerbotPriestAI::ABOLISH_DISEASE private
Definition at line 148 of file PlayerbotPriestAI.h.
Referenced by DispelPlayer(), and PlayerbotPriestAI().
ARCANE_TORRENT
uint32 PlayerbotPriestAI::ARCANE_TORRENT private
Definition at line 182 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
BERSERKING
uint32 PlayerbotPriestAI::BERSERKING private
Definition at line 189 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
BINDING_HEAL
uint32 PlayerbotPriestAI::BINDING_HEAL private
Definition at line 130 of file PlayerbotPriestAI.h.
Referenced by HealPlayer(), and PlayerbotPriestAI().
CIRCLE_OF_HEALING
uint32 PlayerbotPriestAI::CIRCLE_OF_HEALING private
Definition at line 131 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
CLEARCASTING
uint32 PlayerbotPriestAI::CLEARCASTING private
Definition at line 132 of file PlayerbotPriestAI.h.
CURE_DISEASE
uint32 PlayerbotPriestAI::CURE_DISEASE private
Definition at line 147 of file PlayerbotPriestAI.h.
Referenced by DispelPlayer(), and PlayerbotPriestAI().
DESPERATE_PRAYER
uint32 PlayerbotPriestAI::DESPERATE_PRAYER private
Definition at line 133 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
DEVOURING_PLAGUE
uint32 PlayerbotPriestAI::DEVOURING_PLAGUE private
Definition at line 159 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
DIVINE_SPIRIT
uint32 PlayerbotPriestAI::DIVINE_SPIRIT private
Definition at line 177 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
ESCAPE_ARTIST
uint32 PlayerbotPriestAI::ESCAPE_ARTIST private
Definition at line 185 of file PlayerbotPriestAI.h.
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotPriestAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 186 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
FADE
uint32 PlayerbotPriestAI::FADE private
Definition at line 154 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
FEAR_WARD
uint32 PlayerbotPriestAI::FEAR_WARD private
Definition at line 173 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
FLASH_HEAL
uint32 PlayerbotPriestAI::FLASH_HEAL private
Definition at line 134 of file PlayerbotPriestAI.h.
Referenced by HealPlayer(), and PlayerbotPriestAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotPriestAI::GIFT_OF_THE_NAARU private
Definition at line 183 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
GREATER_HEAL
uint32 PlayerbotPriestAI::GREATER_HEAL private
Definition at line 135 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVP(), HealPlayer(), and PlayerbotPriestAI().
HEAL
uint32 PlayerbotPriestAI::HEAL private
Definition at line 136 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVP(), HealPlayer(), and PlayerbotPriestAI().
HOLY_FIRE
uint32 PlayerbotPriestAI::HOLY_FIRE private
Definition at line 137 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
HOLY_NOVA
uint32 PlayerbotPriestAI::HOLY_NOVA private
Definition at line 138 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
INNER_FIRE
uint32 PlayerbotPriestAI::INNER_FIRE private
Definition at line 170 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
INNER_FOCUS
uint32 PlayerbotPriestAI::INNER_FOCUS private
Definition at line 179 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotPriestAI().
LESSER_HEAL
uint32 PlayerbotPriestAI::LESSER_HEAL private
Definition at line 139 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
MANA_BURN
uint32 PlayerbotPriestAI::MANA_BURN private
Definition at line 140 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
MASS_DISPEL
uint32 PlayerbotPriestAI::MASS_DISPEL private
Definition at line 175 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
MIND_BLAST
uint32 PlayerbotPriestAI::MIND_BLAST private
Definition at line 156 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotPriestAI().
MIND_FLAY
uint32 PlayerbotPriestAI::MIND_FLAY private
Definition at line 158 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
MIND_SEAR
uint32 PlayerbotPriestAI::MIND_SEAR private
Definition at line 164 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
PENANCE
uint32 PlayerbotPriestAI::PENANCE private
Definition at line 176 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
POWER_INFUSION
uint32 PlayerbotPriestAI::POWER_INFUSION private
Definition at line 174 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
POWER_WORD_FORTITUDE
uint32 PlayerbotPriestAI::POWER_WORD_FORTITUDE private
Definition at line 171 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
POWER_WORD_SHIELD
uint32 PlayerbotPriestAI::POWER_WORD_SHIELD private
Definition at line 169 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotPriestAI().
PRAYER_OF_FORTITUDE
uint32 PlayerbotPriestAI::PRAYER_OF_FORTITUDE private
Definition at line 172 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
PRAYER_OF_HEALING
uint32 PlayerbotPriestAI::PRAYER_OF_HEALING private
Definition at line 141 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
PRAYER_OF_MENDING
uint32 PlayerbotPriestAI::PRAYER_OF_MENDING private
Definition at line 142 of file PlayerbotPriestAI.h.
Referenced by DoFirstCombatManeuverPVE(), HealPlayer(), and PlayerbotPriestAI().
PRAYER_OF_SHADOW_PROTECTION
uint32 PlayerbotPriestAI::PRAYER_OF_SHADOW_PROTECTION private
Definition at line 162 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
PRAYER_OF_SPIRIT
uint32 PlayerbotPriestAI::PRAYER_OF_SPIRIT private
Definition at line 178 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
PRIEST_DISPEL_MAGIC
uint32 PlayerbotPriestAI::PRIEST_DISPEL_MAGIC private
Definition at line 149 of file PlayerbotPriestAI.h.
Referenced by DispelPlayer(), and PlayerbotPriestAI().
RENEW
uint32 PlayerbotPriestAI::RENEW private
Definition at line 143 of file PlayerbotPriestAI.h.
Referenced by CastHoTOnTank(), DoNextCombatManeuverPVP(), HealPlayer(), and PlayerbotPriestAI().
RESURRECTION
uint32 PlayerbotPriestAI::RESURRECTION private
Definition at line 144 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI(), and ResurrectPlayer().
SCREAM
uint32 PlayerbotPriestAI::SCREAM private
Definition at line 157 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVP(), and PlayerbotPriestAI().
SHACKLE_UNDEAD
uint32 PlayerbotPriestAI::SHACKLE_UNDEAD private
Definition at line 145 of file PlayerbotPriestAI.h.
Referenced by Neutralize(), and PlayerbotPriestAI().
SHADOW_PROTECTION
uint32 PlayerbotPriestAI::SHADOW_PROTECTION private
Definition at line 160 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
SHADOW_WORD_PAIN
uint32 PlayerbotPriestAI::SHADOW_WORD_PAIN private
Definition at line 155 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotPriestAI().
SHADOWFIEND
uint32 PlayerbotPriestAI::SHADOWFIEND private
Definition at line 163 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
SHADOWFORM
uint32 PlayerbotPriestAI::SHADOWFORM private
Definition at line 165 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotPriestAI().
SHADOWMELD
uint32 PlayerbotPriestAI::SHADOWMELD private
Definition at line 187 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
SHOOT
uint32 PlayerbotPriestAI::SHOOT private
Definition at line 151 of file PlayerbotPriestAI.h.
Referenced by CastSpell(), DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
SMITE
uint32 PlayerbotPriestAI::SMITE private
Definition at line 146 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotPriestAI().
STONEFORM
uint32 PlayerbotPriestAI::STONEFORM private
Definition at line 184 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
VAMPIRIC_EMBRACE
uint32 PlayerbotPriestAI::VAMPIRIC_EMBRACE private
Definition at line 166 of file PlayerbotPriestAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPriestAI().
VAMPIRIC_TOUCH
uint32 PlayerbotPriestAI::VAMPIRIC_TOUCH private
Definition at line 161 of file PlayerbotPriestAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPriestAI().
WAR_STOMP
uint32 PlayerbotPriestAI::WAR_STOMP private
Definition at line 188 of file PlayerbotPriestAI.h.
WILL_OF_THE_FORSAKEN
uint32 PlayerbotPriestAI::WILL_OF_THE_FORSAKEN private
Definition at line 190 of file PlayerbotPriestAI.h.
Referenced by PlayerbotPriestAI().
The documentation for this class was generated from the following files:
PlayerbotPriestAI.h
PlayerbotPriestAI.cpp