CMaNGOS_WoTLK: Database Class Reference
Database Class Reference abstract
#include <Database.h>
Public Member Functions
virtual ~Database ()
virtual bool Initialize (const char *infoString, int nConns=1)
virtual void InitDelayThread ()
virtual void HaltDelayThread ()
QueryResult * Query (const char *sql)
Synchronous DB queries.
QueryNamedResult * QueryNamed (const char *sql)
QueryResult * PQuery (const char *format,...) ATTR_PRINTF(2
QueryResult QueryNamedResult * PQueryNamed (const char *format,...) ATTR_PRINTF(2
QueryResult QueryNamedResult bool DirectExecute (const char *sql) const
bool DirectPExecute (const char *format,...) ATTR_PRINTF(2
template<class Class >
bool bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *), const char *sql)
Async queries and query holders, implemented in DatabaseImpl.h.
template<class Class , typename ParamType1 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *sql)
template<class Class , typename ParamType1 , typename ParamType2 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *sql)
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *sql)
template<typename ParamType1 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *sql)
template<typename ParamType1 , typename ParamType2 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *sql)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *sql)
template<class Class >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *), const char *format,...) ATTR_PRINTF(4
template<class Class , typename ParamType1 >
bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...) ATTR_PRINTF(5
template<class Class , typename ParamType1 , typename ParamType2 >
bool bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...) ATTR_PRINTF(6
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool bool bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...) ATTR_PRINTF(7
template<typename ParamType1 >
bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...) ATTR_PRINTF(4
template<typename ParamType1 , typename ParamType2 >
bool bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...) ATTR_PRINTF(5
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool bool bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...) ATTR_PRINTF(6
template<class Class >
bool bool bool bool bool bool bool bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *), SqlQueryHolder *holder)
template<class Class , typename ParamType1 >
bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *, ParamType1), SqlQueryHolder *holder, ParamType1 param1)
bool Execute (const char *sql)
bool PExecute (const char *format,...) ATTR_PRINTF(2
bool bool PExecuteLog (const char *format,...) ATTR_PRINTF(2
bool bool bool BeginTransaction ()
bool CommitTransaction ()
bool RollbackTransaction ()
bool CommitTransactionDirect ()
SqlStatement CreateStatement (SqlStatementID &index, const char *fmt)
std::string GetStmtString (const int stmtId) const
operator bool () const
void escape_string (std::string &str)
virtual void ThreadStart ()
virtual void ThreadEnd ()
void ProcessResultQueue ()
bool CheckRequiredField (char const *table_name, char const *required_name)
uint32 GetPingIntervall () const
void Ping ()
void AllowAsyncTransactions ()
template<class Class >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *), const char *sql)
template<class Class , typename ParamType1 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...)
template<class Class , typename ParamType1 , typename ParamType2 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...)
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...)
template<typename ParamType1 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...)
template<typename ParamType1 , typename ParamType2 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...)
template<class Class >
bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *), SqlQueryHolder *holder)
Protected Types
typedef std::vector< SqlConnection * > SqlConnectionContainer
typedef std::mutex LOCK_TYPE
typedef std::lock_guard< LOCK_TYPE > LOCK_GUARD
typedef std::unordered_map< std::string, int > PreparedStmtRegistry
Protected Member Functions
Database ()
void StopServer ()
virtual SqlConnection * CreateConnection ()=0
virtual SqlDelayThread * CreateDelayThread ()
SqlConnection * getQueryConnection ()
SqlConnection * getAsyncConnection () const
bool ExecuteStmt (const SqlStatementID &id, SqlStmtParameters *params)
bool DirectExecuteStmt (const SqlStatementID &id, SqlStmtParameters *params)
Protected Attributes
boost::thread_specific_ptr< SqlTransaction > m_currentTransaction
DB connections.
int m_nQueryConnPoolSize
std::atomic_long m_nQueryCounter
SqlConnectionContainer m_pQueryConnections
SqlConnection * m_pAsyncConn
SqlResultQueue * m_pResultQueue
Transaction queues from diff. threads.
SqlDelayThread * m_threadBody
Pointer to delay sql executer (owned by m_delayThread)
MaNGOS::Thread * m_delayThread
Pointer to executer thread.
std::atomic< bool > m_allowAsyncTransactions
flag which specifies if async transactions are enabled
LOCK_TYPE m_stmtGuard
PreparedStmtRegistry m_stmtRegistry
int m_iStmtIndex
Private Attributes
bool m_logSQL
std::string m_logsDir
uint32 m_pingIntervallms
Friends
class SqlStatement
Detailed Description
Definition at line 102 of file Database.h.
Member Typedef Documentation
LOCK_GUARD
typedef std::lock_guard<LOCK_TYPE> Database::LOCK_GUARD protected
Definition at line 274 of file Database.h.
LOCK_TYPE
typedef std::mutex Database::LOCK_TYPE protected
Definition at line 273 of file Database.h.
PreparedStmtRegistry
typedef std::unordered_map<std::string, int> Database::PreparedStmtRegistry protected
Definition at line 278 of file Database.h.
SqlConnectionContainer
typedef std::vector< SqlConnection* > Database::SqlConnectionContainer protected
Definition at line 260 of file Database.h.
Constructor & Destructor Documentation
~Database()
Database::~Database () virtual
Definition at line 95 of file Database.cpp.
References StopServer().
Database()
Database::Database () inline protected
Definition at line 224 of file Database.h.
References m_nQueryCounter.
Member Function Documentation
AllowAsyncTransactions()
void Database::AllowAsyncTransactions () inline
Definition at line 221 of file Database.h.
References m_allowAsyncTransactions.
Referenced by main(), and Master::Run().
AsyncPQuery() [1/13]
template<class Class > bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *) method, const char * format, ...)
Definition at line 112 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
Referenced by MassMailMgr::AddMassMailTask(), NamreebAnticheat::SessionAnticheat::CleanupFingerprintHistory(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleCharEnumOpcode(), WorldSession::HandleCharRenameOpcode(), WorldSession::SendNameQueryResponseFromDB(), and World::UpdateRealmCharCount().
AsyncPQuery() [2/13]
template<class Class , typename ParamType1 > bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * format, ...)
Definition at line 120 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [3/13]
template<class Class , typename ParamType1 > bool bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * format, ...)
AsyncPQuery() [4/13]
template<class Class , typename ParamType1 , typename ParamType2 > bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * format, ...)
Definition at line 128 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [5/13]
template<class Class , typename ParamType1 , typename ParamType2 > bool bool bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * format, ...)
AsyncPQuery() [6/13]
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 > bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * format, ...)
Definition at line 136 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [7/13]
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 > bool bool bool bool Database::AsyncPQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * format, ...)
AsyncPQuery() [8/13]
template<typename ParamType1 > bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * format, ...)
Definition at line 146 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [9/13]
template<typename ParamType1 > bool bool bool bool bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * format, ...)
AsyncPQuery() [10/13]
template<typename ParamType1 , typename ParamType2 > bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * format, ...)
Definition at line 154 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [11/13]
template<typename ParamType1 , typename ParamType2 > bool bool bool bool bool bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * format, ...)
AsyncPQuery() [12/13]
template<typename ParamType1 , typename ParamType2 , typename ParamType3 > bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * format, ...)
Definition at line 162 of file DatabaseImpl.h.
References ASYNC_PQUERY_BODY, and AsyncQuery().
AsyncPQuery() [13/13]
template<typename ParamType1 , typename ParamType2 , typename ParamType3 > bool bool bool bool bool bool bool Database::AsyncPQuery (void(*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * format, ...)
AsyncQuery() [1/8]
template<class Class > bool bool Database::AsyncQuery (Class * object, void(Class::*)(QueryResult *) method, const char * sql)
Async queries and query holders, implemented in DatabaseImpl.h.
Referenced by AsyncPQuery().
AsyncQuery() [2/8]
template<class Class > bool Database::AsyncQuery (Class * object, void(Class::*)(QueryResult *) method, const char * sql)
Definition at line 52 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [3/8]
template<class Class , typename ParamType1 > bool Database::AsyncQuery (Class * object, void(Class::*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * sql)
Definition at line 60 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [4/8]
template<class Class , typename ParamType1 , typename ParamType2 > bool Database::AsyncQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * sql)
Definition at line 68 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [5/8]
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 > bool Database::AsyncQuery (Class * object, void(Class::*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * sql)
Definition at line 76 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [6/8]
template<typename ParamType1 > bool Database::AsyncQuery (void(*)(QueryResult *, ParamType1) method, ParamType1 param1, const char * sql)
Definition at line 86 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [7/8]
template<typename ParamType1 , typename ParamType2 > bool Database::AsyncQuery (void(*)(QueryResult *, ParamType1, ParamType2) method, ParamType1 param1, ParamType2 param2, const char * sql)
Definition at line 94 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
AsyncQuery() [8/8]
template<typename ParamType1 , typename ParamType2 , typename ParamType3 > bool Database::AsyncQuery (void(*)(QueryResult *, ParamType1, ParamType2, ParamType3) method, ParamType1 param1, ParamType2 param2, ParamType3 param3, const char * sql)
Definition at line 102 of file DatabaseImpl.h.
References ASYNC_QUERY_BODY, SqlDelayThread::Delay(), m_pResultQueue, and m_threadBody.
BeginTransaction()
bool Database::BeginTransaction ()
Definition at line 388 of file Database.cpp.
References m_currentTransaction, m_pAsyncConn, and MANGOS_ASSERT.
Referenced by PlayerbotAI::_HandleCommandMail(), MapPersistentStateManager::_ResetOrWarnAll(), Group::_setLeader(), World::_UpdateRealmCharCount(), AuctionHouseObject::AddAuction(), AuctionEntry::AuctionBidWinning(), Player::AutoUnequipOffhandIfNeed(), NamreebAnticheat::AntispamMgr::BlacklistAdd(), MapPersistentStateManager::CleanupInstances(), ArenaTeam::Create(), Group::Create(), Guild::Create(), Guild::CreateNewBankTab(), AccountMgr::DeleteAccount(), AchievementMgr::DeleteFromDB(), Player::DeleteFromDB(), Pet::DeleteFromDB(), Creature::DeleteFromDB(), MapPersistentStateManager::DeleteInstanceFromDB(), DungeonPersistentState::DeleteRespawnTimes(), Guild::Disband(), Group::Disband(), ArenaTeam::Disband(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleMailTakeMoney(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetRename(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleWrapItemOpcode(), PlayerDumpReader::LoadDump(), Pet::LoadPetFromDB(), Guild::LoadRanksFromDB(), main(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), NamreebAnticheat::Antispam::Notify(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), Mail::prepareTemplateItems(), Player::RemovePetitionsAndSigns(), MapPersistentState::SaveCreatureRespawnTime(), MapPersistentState::SaveGORespawnTime(), Pet::SavePetToDB(), ArenaTeam::SaveToDB(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Player::SendItemRetrievalMail(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), WorldSession::SetAccountData(), ObjectMgr::SetHighestGuids(), NamreebAnticheat::Antispam::Silence(), NamreebAnticheat::AntispamMgr::Silence(), Guild::SwapItems(), NamreebAnticheat::AntispamMgr::Unsilence(), WardenWin::Update(), and AuctionEntry::UpdateBid().
CheckRequiredField()
bool Database::CheckRequiredField (char const * table_name, char const * required_name)
Definition at line 446 of file Database.cpp.
References QueryNamedResult::GetFieldNames(), PQuery(), PQueryNamed(), and sLog.
Referenced by Master::_StartDB(), and StartDB().
CommitTransaction()
bool Database::CommitTransaction ()
Definition at line 401 of file Database.cpp.
References CommitTransactionDirect(), SqlDelayThread::Delay(), m_allowAsyncTransactions, m_currentTransaction, m_pAsyncConn, and m_threadBody.
Referenced by PlayerbotAI::_HandleCommandMail(), MapPersistentStateManager::_ResetOrWarnAll(), Group::_setLeader(), World::_UpdateRealmCharCount(), AuctionHouseObject::AddAuction(), AuctionEntry::AuctionBidWinning(), Player::AutoUnequipOffhandIfNeed(), NamreebAnticheat::AntispamMgr::BlacklistAdd(), MapPersistentStateManager::CleanupInstances(), ArenaTeam::Create(), Group::Create(), Guild::Create(), Guild::CreateNewBankTab(), AccountMgr::DeleteAccount(), AchievementMgr::DeleteFromDB(), Player::DeleteFromDB(), Pet::DeleteFromDB(), Creature::DeleteFromDB(), MapPersistentStateManager::DeleteInstanceFromDB(), DungeonPersistentState::DeleteRespawnTimes(), Guild::Disband(), Group::Disband(), ArenaTeam::Disband(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleMailTakeMoney(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetRename(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleWrapItemOpcode(), PlayerDumpReader::LoadDump(), Pet::LoadPetFromDB(), Guild::LoadRanksFromDB(), main(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), NamreebAnticheat::Antispam::Notify(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), Mail::prepareTemplateItems(), Player::RemovePetitionsAndSigns(), MapPersistentState::SaveCreatureRespawnTime(), MapPersistentState::SaveGORespawnTime(), Pet::SavePetToDB(), ArenaTeam::SaveToDB(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Player::SendItemRetrievalMail(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), WorldSession::SetAccountData(), ObjectMgr::SetHighestGuids(), NamreebAnticheat::Antispam::Silence(), NamreebAnticheat::AntispamMgr::Silence(), Guild::SwapItems(), NamreebAnticheat::AntispamMgr::Unsilence(), WardenWin::Update(), and AuctionEntry::UpdateBid().
CommitTransactionDirect()
bool Database::CommitTransactionDirect ()
Definition at line 415 of file Database.cpp.
References m_currentTransaction, and m_pAsyncConn.
Referenced by CommitTransaction().
CreateConnection()
virtual SqlConnection* Database::CreateConnection () protected pure virtual
Implemented in DatabasePostgre, and DatabaseMysql.
Referenced by Initialize().
CreateDelayThread()
SqlDelayThread * Database::CreateDelayThread () protected virtual
Definition at line 164 of file Database.cpp.
References m_pAsyncConn.
Referenced by InitDelayThread().
CreateStatement()
SqlStatement Database::CreateStatement (SqlStatementID & index, const char * fmt)
Definition at line 581 of file Database.cpp.
References SqlStatementID::init(), SqlStatementID::initialized(), m_iStmtIndex, m_stmtGuard, m_stmtRegistry, and SqlStatement.
Referenced by Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveBGData(), Player::_SaveDailyQuestStatus(), Player::_SaveEquipmentSets(), Player::_SaveGlyphs(), Player::_SaveInventory(), Player::_SaveMail(), Player::_SaveMonthlyQuestStatus(), Player::_SaveNewInstanceIdTimer(), Player::_SaveQuestStatus(), Player::_SaveSkills(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), Pet::_SaveSpells(), Player::_SaveSpells(), Player::_SaveStats(), Player::_SaveTalents(), Player::_SaveWeeklyQuestStatus(), World::AddSession_(), NamreebAnticheat::AntispamMgr::BlacklistAdd(), Item::DeleteFromDB(), Corpse::DeleteFromDB(), Pet::DeleteFromDB(), Item::DeleteFromInventoryDB(), Player::DestroyItem(), BattleGround::EndBattleGround(), WorldSocket::HandleAuthSession(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePlayerLogin(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleUnstablePet(), Item::LoadFromDB(), Pet::LoadPetFromDB(), WorldSession::LogoutPlayer(), NamreebAnticheat::Antispam::Notify(), GMTicketMgr::Save(), MapPersistentState::SaveCreatureRespawnTime(), Player::SaveGoldToDB(), MapPersistentState::SaveGORespawnTime(), Player::SaveItemToInventory(), Pet::SavePetToDB(), AchievementMgr::SaveToDB(), Item::SaveToDB(), Player::SaveToDB(), ReputationMgr::SaveToDB(), WorldSession::SaveTutorialsData(), WorldSession::SetAccountData(), AuctionHouseBot::SetItemData(), NamreebAnticheat::Antispam::Silence(), and WardenWin::Update().
DelayQueryHolder() [1/3]
template<class Class > bool bool bool bool bool bool bool bool Database::DelayQueryHolder (Class * object, void(Class::*)(QueryResult *, SqlQueryHolder *) method, SqlQueryHolder * holder)
Referenced by WorldSession::HandlePlayerLoginOpcode().
DelayQueryHolder() [2/3]
template<class Class > bool Database::DelayQueryHolder (Class * object, void(Class::*)(QueryResult *, SqlQueryHolder *) method, SqlQueryHolder * holder)
Definition at line 172 of file DatabaseImpl.h.
References ASYNC_DELAYHOLDER_BODY, SqlQueryHolder::Execute(), m_pResultQueue, and m_threadBody.
DelayQueryHolder() [3/3]
template<class Class , typename ParamType1 > bool Database::DelayQueryHolder (Class * object, void(Class::*)(QueryResult *, SqlQueryHolder *, ParamType1) method, SqlQueryHolder * holder, ParamType1 param1)
Definition at line 180 of file DatabaseImpl.h.
References ASYNC_DELAYHOLDER_BODY, SqlQueryHolder::Execute(), m_pResultQueue, and m_threadBody.
DirectExecute()
QueryResult QueryNamedResult bool Database::DirectExecute (const char * sql) const inline
Definition at line 129 of file Database.h.
References SqlConnection::Execute(), and m_pAsyncConn.
Referenced by DirectPExecute(), Execute(), CalendarMgr::LoadCalendarsFromDB(), MapPersistentStateManager::LoadCreatureRespawnTimes(), and MapPersistentStateManager::LoadGameobjectRespawnTimes().
DirectExecuteStmt()
bool Database::DirectExecuteStmt (const SqlStatementID & id, SqlStmtParameters * params) protected
Definition at line 572 of file Database.cpp.
References SqlConnection::ExecuteStmt(), getAsyncConnection(), and MANGOS_ASSERT.
Referenced by SqlStatement::DirectExecute(), and ExecuteStmt().
DirectPExecute()
bool Database::DirectPExecute (const char * format, ...)
Definition at line 368 of file Database.cpp.
References DirectExecute(), MAX_QUERY_LEN, and sLog.
Referenced by PlayerbotAI::_HandleCommandEquip(), PlayerbotAI::_HandleCommandFollow(), PlayerbotAI::_HandleCommandGM(), PlayerbotAI::_HandleCommandOrders(), CharacterDatabaseCleaner::CleanCharacterTalent(), DungeonResetScheduler::LoadResetTimes(), Master::Run(), PlayerbotAI::SetCombatOrder(), and DungeonResetScheduler::Update().
escape_string()
void Database::escape_string (std::string & str)
Definition at line 204 of file Database.cpp.
References m_pQueryConnections.
Referenced by MapPersistentStateManager::_DelHelper(), AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleReconnectChallenge(), CalendarMgr::AddEvent(), ObjectMgr::AddGameTele(), Guild::AddMember(), World::BanAccount(), AccountMgr::ChangeUsername(), ArenaTeam::Create(), Guild::Create(), CreateDumpString(), Guild::CreateRank(), SqlPlainPreparedStatement::DataToString(), AccountMgr::GetId(), ObjectMgr::GetPlayerGuidByName(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), ChatHandler::HandleAddItemCommand(), WorldSocket::HandleAuthSession(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListAccountCommand(), ChatHandler::HandleBanListCharacterCommand(), ChatHandler::HandleBanListIPCommand(), WorldSession::HandleBugOpcode(), WorldSession::HandleCalendarEventInvite(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharRenameOpcode(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleLookupAccountEmailCommand(), ChatHandler::HandleLookupAccountIpCommand(), ChatHandler::HandleLookupAccountNameCommand(), ChatHandler::HandleLookupPlayerAccountCommand(), ChatHandler::HandleLookupPlayerEmailCommand(), ChatHandler::HandleLookupPlayerIpCommand(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetRename(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), PlayerDumpReader::LoadDump(), Guild::LoadRanksFromDB(), World::RemoveBanAccount(), Master::Run(), DungeonPersistentState::SaveToDB(), InstanceData::SaveToDB(), MailDraft::SendMailTo(), PlayerSocial::SetFriendNote(), Guild::SetGINFO(), Guild::SetGuildBankTabInfo(), Guild::SetGuildBankTabText(), Guild::SetMOTD(), MemberSlot::SetOFFNOTE(), MemberSlot::SetPNOTE(), Guild::SetRankName(), and World::WarnAccount().
Execute()
bool Database::Execute (const char * sql)
Definition at line 324 of file Database.cpp.
References SqlDelayThread::Delay(), DirectExecute(), m_allowAsyncTransactions, m_currentTransaction, m_pAsyncConn, and m_threadBody.
Referenced by CharacterDatabaseCleaner::CheckUnique(), CharacterDatabaseCleaner::CleanDatabase(), MapPersistentStateManager::CleanupInstances(), Master::clearOnlineAccounts(), AccountMgr::CreateAccount(), ChatHandler::HandleBanListAccountCommand(), ChatHandler::HandleBanListCharacterCommand(), ChatHandler::HandleBanListIPCommand(), GameEventMgr::Initialize(), PlayerDumpReader::LoadDump(), main(), PExecute(), PExecuteLog(), World::ResetDailyQuests(), World::ResetMonthlyQuests(), World::ResetRandomBattleground(), Pet::resetTalentsForAllPetsOf(), World::ResetWeeklyQuests(), Player::SavePositionInDB(), Corpse::SaveToDB(), and World::SetInitialWorldSettings().
ExecuteStmt()
bool Database::ExecuteStmt (const SqlStatementID & id, SqlStmtParameters * params) protected
Definition at line 548 of file Database.cpp.
References SqlDelayThread::Delay(), DirectExecuteStmt(), m_allowAsyncTransactions, m_currentTransaction, m_pAsyncConn, and m_threadBody.
Referenced by SqlStatement::Execute().
getAsyncConnection()
SqlConnection* Database::getAsyncConnection () const inline protected
Definition at line 247 of file Database.h.
References m_pAsyncConn.
Referenced by DirectExecuteStmt().
GetPingIntervall()
uint32 Database::GetPingIntervall () const inline
Definition at line 213 of file Database.h.
References m_pingIntervallms.
Referenced by SqlDelayThread::run().
getQueryConnection()
SqlConnection * Database::getQueryConnection () protected
Definition at line 216 of file Database.cpp.
References m_nQueryConnPoolSize, m_nQueryCounter, and m_pQueryConnections.
Referenced by Query(), and QueryNamed().
GetStmtString()
std::string Database::GetStmtString (const int stmtId) const
Definition at line 609 of file Database.cpp.
References m_iStmtIndex, m_stmtGuard, and m_stmtRegistry.
Referenced by SqlStatement::DirectExecute(), SqlStatement::Execute(), and SqlConnection::GetStmt().
HaltDelayThread()
void Database::HaltDelayThread () virtual
Definition at line 179 of file Database.cpp.
References m_delayThread, m_threadBody, SqlDelayThread::Stop(), and MaNGOS::Thread::wait().
Referenced by Master::_StartDB(), main(), Master::Run(), StartDB(), and StopServer().
InitDelayThread()
void Database::InitDelayThread () virtual
Definition at line 170 of file Database.cpp.
References CreateDelayThread(), m_delayThread, and m_threadBody.
Referenced by Initialize().
Initialize()
bool Database::Initialize (const char * infoString, int nConns = 1) virtual
Definition at line 100 of file Database.cpp.
References CreateConnection(), InitDelayThread(), SqlConnection::Initialize(), m_logsDir, m_logSQL, m_nQueryConnPoolSize, m_pAsyncConn, m_pingIntervallms, m_pQueryConnections, m_pResultQueue, MAX_CONNECTION_POOL_SIZE, MIN_CONNECTION_POOL_SIZE, MINUTE, and sConfig.
Referenced by Master::_StartDB(), and StartDB().
operator bool()
Database::operator bool () const inline
Definition at line 199 of file Database.h.
References m_pAsyncConn, and m_pQueryConnections.
PExecute()
bool Database::PExecute (const char * format, ...)
Definition at line 348 of file Database.cpp.
References Execute(), MAX_QUERY_LEN, and sLog.
Referenced by Group::_addMember(), MapPersistentStateManager::_DelHelper(), PlayerbotAI::_HandleCommandMail(), AuthSocket::_HandleLogonProof(), Player::_LoadBoundInstances(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItemLoot(), Player::_LoadMailedItems(), Player::_LoadSkills(), Player::_LoadSpells(), Player::_LoadTalents(), Group::_removeMember(), MapPersistentStateManager::_ResetOrWarnAll(), Player::_SaveNewInstanceIdTimer(), Group::_setAssistantFlag(), Group::_setLeader(), Group::_setMainAssistant(), Group::_setMainTank(), Group::_setMembersGroup(), World::_UpdateRealmCharCount(), CalendarMgr::AddEvent(), Guild::AddGBankItemToDB(), CalendarMgr::AddInvite(), ArenaTeam::AddMember(), Guild::AddMember(), Pet::addSpell(), Player::addSpell(), PlayerSocial::AddToSocialList(), GameEventMgr::ApplyNewEvent(), AuctionEntry::AuctionBidWinning(), World::BanAccount(), Player::BindToInstance(), Group::BindToInstance(), AccountMgr::ChangePassword(), MemberSlot::ChangeRank(), AccountMgr::ChangeUsername(), Master::clearOnlineAccounts(), Player::ConvertInstancesToGroup(), Group::ConvertToLFG(), Group::ConvertToRaid(), ArenaTeam::Create(), Group::Create(), Guild::Create(), AccountMgr::CreateAccount(), Guild::CreateDefaultGuildRanks(), Map::CreateInstanceData(), Guild::CreateNewBankTab(), Guild::CreateRank(), Player::Customize(), AccountMgr::DeleteAccount(), AuctionEntry::DeleteFromDB(), AchievementMgr::DeleteFromDB(), Player::DeleteFromDB(), MailDraft::deleteIncludedItems(), MapPersistentStateManager::DeleteInstanceFromDB(), DungeonPersistentState::DeleteRespawnTimes(), ArenaTeam::DelMember(), Guild::DelMember(), Guild::DelRank(), Guild::Disband(), Group::Disband(), ArenaTeam::Disband(), BattleGroundMgr::DistributeArenaPoints(), World::GenerateEventGroupEvents(), Guild::GetMemberMoneyWithdrawRem(), Guild::GetMemberSlotWithdrawRem(), Player::GetZoneIdFromDB(), ChatHandler::HandleAccountLockCommand(), ChatHandler::HandleAccountSetAddonCommand(), ChatHandler::HandleAccountSetGmLevelCommand(), HandleAnticheatCheatinformCommand(), HandleAnticheatSpaminformCommand(), WorldSession::HandleBugOpcode(), WorldSession::HandleCalendarEventModeratorStatus(), WorldSession::HandleCalendarEventRsvp(), WorldSession::HandleCalendarEventStatus(), WorldSession::HandleCalendarUpdateEvent(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), ChatHandler::HandleCharacterCustomizeCommand(), ChatHandler::HandleCharacterDeletedRestoreHelper(), ChatHandler::HandleCharacterLevel(), ChatHandler::HandleCharacterRenameCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), ChatHandler::HandleLinkAddCommand(), ChatHandler::HandleLinkEditCommand(), ChatHandler::HandleLinkRemoveCommand(), ChatHandler::HandleLinkToggleCommand(), WorldSession::HandleMailReturnToSender(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleMuteCommand(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetRename(), ChatHandler::HandleResetAllCommand(), ChatHandler::HandleResetSpecsCommand(), ChatHandler::HandleResetSpellsCommand(), ChatHandler::HandleResetTaxiNodesCommand(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), WorldSession::HandleTurnInPetitionOpcode(), ChatHandler::HandleUnmuteCommand(), WorldSession::HandleWrapItemOpcode(), AchievementMgr::IncompletedAchievement(), BattleGroundMgr::InitAutomaticArenaPointDistribution(), World::InitDailyQuestResetTime(), World::InitRandomBattlegroundResetTime(), World::InitWeeklyQuestResetTime(), WaypointManager::Load(), AuctionHouseMgr::LoadAuctions(), Guild::LoadBankRightsFromDB(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), Player::LoadFromDB(), AchievementMgr::LoadFromDB(), ObjectMgr::LoadGroups(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), GuildMgr::LoadGuilds(), Item::LoadLootFromDB(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), Guild::LoadRanksFromDB(), Guild::LogBankEvent(), Guild::LogGuildEvent(), Guild::MemberItemWithdraw(), Guild::MemberMoneyWithdraw(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), Mail::prepareTemplateItems(), NamreebAnticheat::SessionAnticheat::RecordCheat(), Player::RemoveAtLoginFlag(), World::RemoveBanAccount(), CalendarMgr::RemoveEvent(), PlayerSocial::RemoveFromSocialList(), CalendarEvent::RemoveInviteByItr(), Guild::RemoveItem(), MapPersistentStateManager::RemovePersistentState(), Player::RemovePetitionsAndSigns(), World::ResetDailyQuests(), Group::ResetInstances(), World::ResetRandomBattleground(), World::ResetWeeklyQuests(), ObjectMgr::ReturnOrDeleteOldMails(), BattleGroundMgr::RewardArenaSeason(), GMTicketMgr::Save(), WorldState::Save(), WorldState::SaveHelper(), Player::SaveTitles(), ArenaTeam::SaveToDB(), DungeonPersistentState::SaveToDB(), AuctionEntry::SaveToDB(), InstanceData::SaveToDB(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionWonMail(), MailDraft::SendMailTo(), MailDraft::SendReturnToSender(), Guild::SetBankMoney(), Guild::SetBankMoneyPerDay(), Guild::SetBankRightsAndSlots(), ArenaTeam::SetCaptain(), Group::SetDungeonDifficulty(), ArenaTeam::SetEmblem(), Guild::SetEmblem(), PlayerSocial::SetFriendNote(), Guild::SetGINFO(), Guild::SetGuildBankTabInfo(), Guild::SetGuildBankTabText(), ObjectMgr::SetHighestGuids(), Player::SetHomebindToLocation(), World::SetInitialWorldSettings(), Guild::SetLeader(), World::SetMonthlyQuestResetTime(), Guild::SetMOTD(), MemberSlot::SetOFFNOTE(), World::SetPlayerLimit(), MemberSlot::SetPNOTE(), Group::SetRaidDifficulty(), Player::SetRandomBattlegroundWinner(), Guild::SetRankName(), Guild::SetRankRights(), ArenaTeam::SetStats(), NamreebAnticheat::AntispamMgr::Silence(), GameEventMgr::UnApplyEvent(), Player::UnbindInstance(), Group::UnbindInstance(), NamreebAnticheat::AntispamMgr::Unsilence(), BattleGround::Update(), World::Update(), BattleGroundMgr::Update(), AuctionEntry::UpdateBid(), DungeonPersistentState::UpdateEncounterState(), and World::WarnAccount().
PExecuteLog()
bool Database::PExecuteLog (const char * format, ...)
Definition at line 244 of file Database.cpp.
References Execute(), m_logsDir, m_logSQL, MAX_QUERY_LEN, and sLog.
Referenced by ObjectMgr::AddGameTele(), GraveyardManager::AddGraveYardLink(), WaypointManager::AddNode(), ObjectMgr::AddVendorItem(), GameObject::DeleteFromDB(), Creature::DeleteFromDB(), ObjectMgr::DeleteGameTele(), WaypointManager::DeleteNode(), WaypointManager::DeletePath(), ChatHandler::HandleNpcFactionIdCommand(), ChatHandler::HandleNpcFlagCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSpawnDistCommand(), ChatHandler::HandleNpcSpawnTimeCommand(), ObjectMgr::RemoveVendorItem(), Creature::SaveToDB(), GameObject::SaveToDB(), WaypointManager::SetNodeOrientation(), WaypointManager::SetNodePosition(), WaypointManager::SetNodeScriptId(), and WaypointManager::SetNodeWaittime().
Ping()
void Database::Ping ()
Definition at line 228 of file Database.cpp.
References m_nQueryConnPoolSize, m_pAsyncConn, m_pQueryConnections, and SqlConnection::Query().
Referenced by main(), and SqlDelayThread::run().
PQuery()
QueryResult * Database::PQuery (const char * format, ...)
Definition at line 286 of file Database.cpp.
References MAX_QUERY_LEN, Query(), and sLog.
Referenced by MapPersistentStateManager::_DelHelper(), PlayerbotAI::_HandleCommandGM(), PlayerbotAI::_HandleCommandOrders(), PlayerbotAI::_HandleCommandQuest(), PlayerbotAI::_HandleCommandSurvey(), AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), Pet::_LoadAuras(), Player::_LoadCreatedInstanceTimers(), Pet::_LoadGuardianPetNumber(), Pet::_LoadSpellCooldowns(), Pet::_LoadSpells(), ArenaTeam::AddMember(), Guild::AddMember(), World::BanAccount(), PlayerbotAI::BotDataRestore(), AccountMgr::ChangeUsername(), AccountMgr::CheckPassword(), CheckRequiredField(), CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), CharacterDatabaseCleaner::CleanDatabase(), PlayerbotAI::CombatOrderRestore(), Map::CreateInstanceData(), Player::Customize(), AccountMgr::DeleteAccount(), Player::DeleteFromDB(), Pet::DeleteFromDB(), Player::DeleteOldCharacters(), PlayerDumpWriter::DumpTableContent(), AuctionHouseBot::FillUintVectorFromQuery(), Player::GetArenaTeamIdFromDB(), AccountMgr::GetCharactersCount(), ChatHandler::GetDeletedCharacterInfoList(), AccountMgr::GetFlags(), Player::GetGuildIdFromDB(), AccountMgr::GetId(), Player::GetLevelFromDB(), AccountMgr::GetName(), ObjectMgr::GetPlayerAccountIdByGUID(), ObjectMgr::GetPlayerAccountIdByPlayerName(), ObjectMgr::GetPlayerGuidByName(), ObjectMgr::GetPlayerMapIdByGUID(), ObjectMgr::GetPlayerNameByGUID(), ObjectMgr::GetPlayerTeamByGUID(), Player::GetRankFromDB(), AccountMgr::GetSecurity(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), PlayerbotAI::GetTalentSpecsAmount(), Player::GetZoneIdFromDB(), ChatHandler::HandleAccountCharactersCommand(), ChatHandler::HandleAccountOnlineListCommand(), ChatHandler::HandleAddItemCommand(), HandleAnticheatFingerprintAHistoryCommand(), HandleAnticheatFingerprintHistoryCommand(), WorldSocket::HandleAuthSession(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListAccountCommand(), ChatHandler::HandleBanListCharacterCommand(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleBanListIPCommand(), WorldSession::HandleCalendarEventInvite(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharDeleteOpcode(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleLinkAddCommand(), ChatHandler::HandleLinkCheckCommand(), ChatHandler::HandleLinkEditCommand(), ChatHandler::HandleLinkRemoveCommand(), ChatHandler::HandleLinkToggleCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListItemCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandleLookupAccountEmailCommand(), ChatHandler::HandleLookupAccountIpCommand(), ChatHandler::HandleLookupAccountNameCommand(), ChatHandler::HandleLookupPlayerAccountCommand(), ChatHandler::HandleLookupPlayerEmailCommand(), ChatHandler::HandleLookupPlayerIpCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), ChatHandler::HandlePInfoCommand(), WorldSession::HandleSendMail(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleWhoisOpcode(), ChatHandler::HandleWpAddCommand(), AuctionHouseBot::Initialize(), CreatureLinkingMgr::IsLinkingEntryValid(), Player::LeaveAllArenaTeams(), PlayerbotAI::ListAuctions(), WaypointManager::Load(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), PlayerDumpReader::LoadDump(), ObjectMgr::LoadGameObjects(), WorldSession::LoadGlobalAccountData(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), LootStore::LoadLootTable(), ObjectMgr::LoadMangosStrings(), Pet::LoadPetFromDB(), Player::LoadPositionFromDB(), ObjectMgr::LoadQuestRelationsHelper(), AuthSocket::LoadRealmlist(), ScriptMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), ObjectMgr::LoadTrainers(), WorldSession::LoadTutorialsData(), ObjectMgr::LoadVendors(), SystemMgr::LoadVersion(), ChatHandler::LookupPlayerSearchCommand(), Player::OnGossipSelect(), PlayerbotAI::RemoveAuction(), Player::RemovePetitionsAndSigns(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), BattleGroundMgr::RewardArenaSeason(), WorldSession::SendPetitionQueryOpcode(), WorldSession::SendStablePet(), PlayerbotAI::SetQuestNeedItems(), and Pet::TryLoadFromDB().
PQueryNamed()
QueryNamedResult * Database::PQueryNamed (const char * format, ...)
Definition at line 305 of file Database.cpp.
References MAX_QUERY_LEN, QueryNamed(), and sLog.
Referenced by CheckRequiredField().
ProcessResultQueue()
void Database::ProcessResultQueue ()
Definition at line 198 of file Database.cpp.
References m_pResultQueue, and SqlResultQueue::Update().
Referenced by World::UpdateResultQueue().
Query()
QueryResult* Database::Query (const char * sql) inline
Synchronous DB queries.
Definition at line 114 of file Database.h.
References getQueryConnection(), and SqlConnection::Query().
Referenced by BattleGroundMgr::CreateInitialBattleGrounds(), BattleGround::EndBattleGround(), ChatHandler::getCommandTable(), ChatHandler::GetDeletedCharacterInfoList(), PlayerbotAI::GetTalentSpecsAmount(), ChatHandler::HandleBanListAccountCommand(), ChatHandler::HandleBanListIPCommand(), ChatHandler::HandleGMListFullCommand(), BattleGroundMgr::InitAutomaticArenaPointDistribution(), World::InitDailyQuestResetTime(), GameEventMgr::Initialize(), World::InitRandomBattlegroundResetTime(), World::InitWeeklyQuestResetTime(), CombatConditionMgr::Load(), UnitConditionMgr::Load(), WaypointManager::Load(), WorldState::Load(), WorldStateExpressionMgr::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), LootStore::LoadAndCheckReferenceNames(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastText(), ObjectMgr::LoadBroadcastTextLocales(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnDataTemplates(), ObjectMgr::LoadCreatureSpawnEntry(), ObjectMgr::LoadCreatureSpellLists(), ObjectMgr::LoadCreatureTemplateSpells(), ScriptMgr::LoadDbScriptRandomTemplates(), World::LoadDBVersion(), World::LoadEventGroupChosen(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), NamreebAnticheat::AntispamMgr::LoadFromDB(), WardenScanMgr::loadFromDB(), CreatureLinkingMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolManager::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), GMTicketMgr::LoadGMTickets(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), GuildMgr::LoadGuilds(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LFGMgr::LoadLFGDungeons(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), DungeonResetScheduler::LoadResetTimes(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), LFGMgr::LoadRewards(), ScriptDevAIMgr::LoadScriptNames(), SpellScriptMgr::LoadScripts(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), World::LoadSpamRecords(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ScriptMgr::LoadStringIds(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), MapManager::LoadTransports(), ObjectMgr::LoadVehicleSeatParameters(), WeatherMgr::LoadWeatherZoneChances(), ObjectMgr::LoadWorldStateNames(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), PQuery(), ObjectMgr::SetHighestGuids(), World::SetMonthlyQuestResetTime(), PlayerbotAI::TalentSpecDBContainsError(), and RealmList::UpdateRealms().
QueryNamed()
QueryNamedResult* Database::QueryNamed (const char * sql) inline
Definition at line 120 of file Database.h.
References getQueryConnection(), and SqlConnection::QueryNamed().
Referenced by PlayerDumpWriter::GetDump(), and PQueryNamed().
RollbackTransaction()
bool Database::RollbackTransaction ()
Definition at line 432 of file Database.cpp.
References m_currentTransaction, and m_pAsyncConn.
Referenced by WorldSession::HandleGuildBankWithdrawMoney().
StopServer()
void Database::StopServer () protected
Definition at line 148 of file Database.cpp.
References HaltDelayThread(), m_pAsyncConn, m_pQueryConnections, and m_pResultQueue.
Referenced by ~Database(), and DatabaseMysql::~DatabaseMysql().
ThreadEnd()
void Database::ThreadEnd () virtual
Reimplemented in DatabaseMysql.
Definition at line 194 of file Database.cpp.
ThreadStart()
void Database::ThreadStart () virtual
Reimplemented in DatabaseMysql.
Definition at line 190 of file Database.cpp.
Friends And Related Function Documentation
SqlStatement
friend class SqlStatement friend
Definition at line 249 of file Database.h.
Referenced by CreateStatement().
Field Documentation
m_allowAsyncTransactions
std::atomic<bool> Database::m_allowAsyncTransactions protected
flag which specifies if async transactions are enabled
Definition at line 270 of file Database.h.
Referenced by AllowAsyncTransactions(), CommitTransaction(), Execute(), and ExecuteStmt().
m_currentTransaction
boost::thread_specific_ptr<SqlTransaction> Database::m_currentTransaction protected
DB connections.
Definition at line 240 of file Database.h.
Referenced by BeginTransaction(), CommitTransaction(), CommitTransactionDirect(), Execute(), ExecuteStmt(), and RollbackTransaction().
m_delayThread
MaNGOS::Thread* Database::m_delayThread protected
Pointer to executer thread.
Definition at line 268 of file Database.h.
Referenced by HaltDelayThread(), and InitDelayThread().
m_iStmtIndex
int Database::m_iStmtIndex protected
Definition at line 281 of file Database.h.
Referenced by CreateStatement(), and GetStmtString().
m_logsDir
std::string Database::m_logsDir private
Definition at line 286 of file Database.h.
Referenced by Initialize(), and PExecuteLog().
m_logSQL
bool Database::m_logSQL private
Definition at line 285 of file Database.h.
Referenced by Initialize(), and PExecuteLog().
m_nQueryConnPoolSize
int Database::m_nQueryConnPoolSize protected
Definition at line 256 of file Database.h.
Referenced by getQueryConnection(), Initialize(), and Ping().
m_nQueryCounter
std::atomic_long Database::m_nQueryCounter protected
Definition at line 257 of file Database.h.
Referenced by Database(), and getQueryConnection().
m_pAsyncConn
SqlConnection* Database::m_pAsyncConn protected
Definition at line 264 of file Database.h.
Referenced by BeginTransaction(), CommitTransaction(), CommitTransactionDirect(), CreateDelayThread(), DirectExecute(), Execute(), ExecuteStmt(), getAsyncConnection(), Initialize(), operator bool(), Ping(), RollbackTransaction(), and StopServer().
m_pingIntervallms
uint32 Database::m_pingIntervallms private
Definition at line 287 of file Database.h.
Referenced by GetPingIntervall(), and Initialize().
m_pQueryConnections
SqlConnectionContainer Database::m_pQueryConnections protected
Definition at line 261 of file Database.h.
Referenced by escape_string(), getQueryConnection(), Initialize(), operator bool(), Ping(), and StopServer().
m_pResultQueue
SqlResultQueue* Database::m_pResultQueue protected
Transaction queues from diff. threads.
Definition at line 266 of file Database.h.
Referenced by AsyncQuery(), DelayQueryHolder(), Initialize(), ProcessResultQueue(), and StopServer().
m_stmtGuard
LOCK_TYPE Database::m_stmtGuard mutable protected
Definition at line 276 of file Database.h.
Referenced by CreateStatement(), and GetStmtString().
m_stmtRegistry
PreparedStmtRegistry Database::m_stmtRegistry protected
Definition at line 279 of file Database.h.
Referenced by CreateStatement(), and GetStmtString().
m_threadBody
SqlDelayThread* Database::m_threadBody protected
Pointer to delay sql executer (owned by m_delayThread)
Definition at line 267 of file Database.h.
Referenced by AsyncQuery(), CommitTransaction(), DelayQueryHolder(), Execute(), ExecuteStmt(), HaltDelayThread(), and InitDelayThread().
The documentation for this class was generated from the following files:
Database.h
Database.cpp
DatabaseImpl.h