CMaNGOS_WoTLK: SQLStorageBase::SQLSIterator< T > Class Template Reference
SQLStorageBase::SQLSIterator< T > Class Template Reference
#include <SQLStorage.h>
Public Member Functions
T const * getValue () const
void operator++ ()
T const * operator* () const
T const * operator-> () const
bool operator< (const SQLSIterator &r) const
void operator= (const SQLSIterator &r)
Private Member Functions
SQLSIterator (char *ptr, uint32 _recordSize)
Private Attributes
char * pointer
uint32 recordSize
Friends
class SQLStorageBase
Detailed Description
template<typename T>
class SQLStorageBase::SQLSIterator< T >
Definition at line 43 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLSIterator()
template<typename T > SQLStorageBase::SQLSIterator< T >::SQLSIterator (char * ptr, uint32 _recordSize) inline private
Definition at line 57 of file SQLStorage.h.
Member Function Documentation
getValue()
template<typename T > T const* SQLStorageBase::SQLSIterator< T >::getValue () const inline
Definition at line 48 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::pointer.
Referenced by SQLStorageBase::SQLSIterator< T >::operator*(), and SQLStorageBase::SQLSIterator< T >::operator->().
operator*()
template<typename T > T const* SQLStorageBase::SQLSIterator< T >::operator* () const inline
Definition at line 51 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::getValue().
operator++()
template<typename T > void SQLStorageBase::SQLSIterator< T >::operator++ () inline
Definition at line 50 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::pointer, and SQLStorageBase::SQLSIterator< T >::recordSize.
operator->()
template<typename T > T const* SQLStorageBase::SQLSIterator< T >::operator-> () const inline
Definition at line 52 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::getValue().
operator<()
template<typename T > bool SQLStorageBase::SQLSIterator< T >::operator< (const SQLSIterator< T > & r) const inline
Definition at line 53 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::pointer.
operator=()
template<typename T > void SQLStorageBase::SQLSIterator< T >::operator= (const SQLSIterator< T > & r) inline
Definition at line 54 of file SQLStorage.h.
References SQLStorageBase::SQLSIterator< T >::pointer, and SQLStorageBase::SQLSIterator< T >::recordSize.
Friends And Related Function Documentation
SQLStorageBase
template<typename T > friend class SQLStorageBase friend
Definition at line 45 of file SQLStorage.h.
Field Documentation
pointer
template<typename T > char* SQLStorageBase::SQLSIterator< T >::pointer private
Definition at line 58 of file SQLStorage.h.
Referenced by SQLStorageBase::SQLSIterator< T >::getValue(), SQLStorageBase::SQLSIterator< T >::operator++(), SQLStorageBase::SQLSIterator< T >::operator<(), and SQLStorageBase::SQLSIterator< T >::operator=().
recordSize
template<typename T > uint32 SQLStorageBase::SQLSIterator< T >::recordSize private
Definition at line 59 of file SQLStorage.h.
Referenced by SQLStorageBase::SQLSIterator< T >::operator++(), and SQLStorageBase::SQLSIterator< T >::operator=().
The documentation for this class was generated from the following file:
SQLStorage.h