CMaNGOS_WoTLK: GameObjectGroup Class Reference
GameObjectGroup Class Reference
#include <SpawnGroup.h>
Public Member Functions
GameObjectGroup (SpawnGroupEntry const &entry, Map &map)
void RemoveObject (WorldObject *wo) override
void Despawn (uint32 timeMSToDespawn=0, uint32 forcedDespawnTime=0) override
Public Member Functions inherited from SpawnGroup
SpawnGroup (SpawnGroupEntry const &entry, Map &map, uint32 typeId)
virtual ~SpawnGroup ()
virtual void AddObject (uint32 dbGuid, uint32 entry)
uint32 GetGuidEntry (uint32 dbGuid) const
virtual void Update ()
uint32 GetEligibleEntry (std::map< uint32, uint32 > &existingEntries, std::map< uint32, uint32 > &minEntries)
virtual void Spawn (bool force)
std::string to_string () const
uint32 GetObjectTypeId () const
void SetEnabled (bool enabled)
SpawnGroupEntry const & GetGroupEntry () const
uint32 GetGroupId () const
virtual CreatureGroup * GetCreatureGroup ()
bool IsWorldstateConditionSatisfied () const
void RespawnIfInVicinity (Position pos, float range)
Additional Inherited Members
Protected Attributes inherited from SpawnGroup
SpawnGroupEntry const & m_entry
Map & m_map
std::map< uint32, uint32 > m_objects
std::map< uint32, uint32 > m_chosenEntries
std::map< uint32, bool > m_chosenSpawns
uint32 m_objectTypeId
bool m_enabled
Detailed Description
Definition at line 108 of file SpawnGroup.h.
Constructor & Destructor Documentation
GameObjectGroup()
GameObjectGroup::GameObjectGroup (SpawnGroupEntry const & entry, Map & map)
Definition at line 573 of file SpawnGroup.cpp.
Member Function Documentation
Despawn()
void GameObjectGroup::Despawn (uint32 timeMSToDespawn = 0, uint32 forcedDespawnTime = 0) override virtual
Implements SpawnGroup.
Definition at line 584 of file SpawnGroup.cpp.
References Map::GetGameObject(), SpawnGroup::GetObjectTypeId(), Map::GetPersistentState(), SpawnGroup::m_map, SpawnGroup::m_objects, MapPersistentState::RemoveGameobjectFromGrid(), MapPersistentState::SaveObjectRespawnTime(), and sObjectMgr.
RemoveObject()
void GameObjectGroup::RemoveObject (WorldObject * wo) override virtual
Reimplemented from SpawnGroup.
Definition at line 577 of file SpawnGroup.cpp.
References Object::GetDbGuid(), Map::GetPersistentState(), SpawnGroup::m_map, MapPersistentState::RemoveGameobjectFromGrid(), SpawnGroup::RemoveObject(), and sObjectMgr.
Referenced by GameObject::ClearGameObjectGroup().
The documentation for this class was generated from the following files:
SpawnGroup.h
SpawnGroup.cpp