CMaNGOS_WoTLK: GroupReference Class Reference
GroupReference Class Reference
#include <GroupReference.h>
Public Member Functions
GroupReference ()
~GroupReference ()
GroupReference * next ()
GroupReference const * next () const
uint8 getSubGroup () const
void setSubGroup (uint8 pSubGroup)
Public Member Functions inherited from Reference< Group, Player >
Reference ()
virtual ~Reference ()
void link (Group *toObj, Player *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Group, Player > * next ()
Reference< Group, Player > const * next () const
Reference< Group, Player > * prev ()
Reference< Group, Player > const * prev () const
Reference< Group, Player > * nocheck_next ()
Reference< Group, Player > const * nocheck_next () const
Reference< Group, Player > * nocheck_prev ()
Reference< Group, Player > const * nocheck_prev () const
Group * operator-> () const
Group * getTarget () const
Player * getSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Protected Attributes
uint8 iSubGroup
Detailed Description
Definition at line 27 of file GroupReference.h.
Constructor & Destructor Documentation
GroupReference()
GroupReference::GroupReference () inline
Definition at line 35 of file GroupReference.h.
~GroupReference()
GroupReference::~GroupReference () inline
Definition at line 36 of file GroupReference.h.
References Reference< Group, Player >::unlink().
Member Function Documentation
getSubGroup()
uint8 GroupReference::getSubGroup () const inline
Definition at line 39 of file GroupReference.h.
References iSubGroup.
Referenced by Player::GetOriginalSubGroup(), and Player::GetSubGroup().
next() [1/2]
GroupReference* GroupReference::next () inline
Definition at line 37 of file GroupReference.h.
References Reference< TO, FROM >::next().
Referenced by Group::_updateMembersOnRosterChanged(), BattleGroundQueue::AddGroup(), Group::AddMember(), Group::BroadcastPacket(), Group::BroadcastPacketInMap(), Group::BroadcastPacketInRange(), Group::BroadcastReadyCheck(), npc_simon_game_bunnyAI::BuffPlayers(), Group::CanJoinBattleGroundQueue(), Player::CheckForGroup(), npc_manaforge_control_consoleAI::DoFailEvent(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), Player::FailQuestForGroup(), Spell::FillRaidOrPartyTargets(), LFGMgr::FinishDungeon(), Group::GetDataForXPAtKill(), FollowerAI::GetLeaderForFollower(), Creature::GetLootRecipient(), GameObject::GetLootRecipient(), Group::GetMaxSkillValueForGroup(), Player::GetNextRaidMemberWithLowestLifePercentage(), Unit::GetNextRandomRaidMember(), Player::GetsRecruitAFriendBonus(), GossipSelect_npc_saeed(), GOUse_go_gauntlet_gate(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleGroupgoCommand(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), OutdoorPvP::HandlePlayerKill(), WorldSession::HandlePushQuestToParty(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), ChatHandler::HandleTeleGroupCommand(), Group::InCombatToInstance(), PlayerbotAI::IsInCombat(), npc_shadowlord_deathwailAI::IsPlayerOrGroupInRangeAndActiveInEvent(), LFGMgr::JoinLfg(), FollowerAI::JustDied(), npc_cork_gizeltonAI::MakeQuestFailAndClean(), WorldObject::MonsterText(), SpellReflectionRaid::OnApply(), Aura::ReapplyAffectedPassiveAuras(), Group::RemoveMember(), Group::RewardGroupAtKill(), Player::RewardPlayerAndGroupAtCast(), Player::RewardPlayerAndGroupAtEventCredit(), Player::RewardPlayerAndGroupAtEventExplored(), Group::SetDungeonDifficulty(), Group::SetRaidDifficulty(), Spell::SetTargetMap(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), LFGMgr::TeleportPlayer(), Totem::UnSummon(), AreaAura::Update(), FollowerAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), PetAI::UpdateAllies(), PlayerbotAI::UpdateAttackerInfo(), and Group::UpdatePlayerOutOfRange().
next() [2/2]
GroupReference const* GroupReference::next () const inline
Definition at line 38 of file GroupReference.h.
References Reference< TO, FROM >::next().
setSubGroup()
void GroupReference::setSubGroup (uint8 pSubGroup) inline
Definition at line 40 of file GroupReference.h.
References iSubGroup.
Referenced by Group::ChangeMembersGroup(), Player::RemoveFromBattleGroundRaid(), Player::SetBattleRaid(), Player::SetGroup(), and Player::SetOriginalGroup().
sourceObjectDestroyLink()
void GroupReference::sourceObjectDestroyLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 34 of file GroupReference.cpp.
References Group::DelinkMember(), and Reference< Group, Player >::getTarget().
targetObjectBuildLink()
void GroupReference::targetObjectBuildLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 22 of file GroupReference.cpp.
References Reference< Group, Player >::getTarget(), and Group::LinkMember().
targetObjectDestroyLink()
void GroupReference::targetObjectDestroyLink () override protected virtual
Implements Reference< Group, Player >.
Definition at line 28 of file GroupReference.cpp.
References Group::DelinkMember(), and Reference< Group, Player >::getTarget().
Field Documentation
iSubGroup
uint8 GroupReference::iSubGroup protected
Definition at line 30 of file GroupReference.h.
Referenced by getSubGroup(), and setSubGroup().
The documentation for this class was generated from the following files:
GroupReference.h
GroupReference.cpp