CMaNGOS_WoTLK: FormationData Class Reference
FormationData Class Reference
#include <SpawnGroup.h>
Public Member Functions
FormationData (CreatureGroup *gData, FormationEntrySPtr fEntry)
FormationData ()=delete
~FormationData ()
Unit * GetMaster ()
void Add (Creature *creature)
void Add (Player *player)
void Remove (Creature *creature)
void Remove (Player *player)
void Remove (Unit *unit)
void Reset ()
void Disband ()
void OnDeath (Creature *creature)
void OnHome ()
void OnDelete (Creature *creature)
void OnWPStartNode ()
void OnWPEndNode ()
bool GetMirrorState () const
void Compact (bool set=true)
bool SwitchFormation (SpawnGroupFormationType newShape)
SpawnGroupFormationType GetCurrentShape () const
void SetSpread (float spread)
void SetOptions (uint32 options)
bool CanUseMMap () const
void Update ()
FormationSlotDataSPtr SetFormationSlot (Creature *creature, SpawnGroupFormationSlotType slotType=SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC)
std::string to_string () const
FormationEntrySPtr GetFormationEntry () const
void SetMovementInfo (MovementGeneratorType moveType, uint32 pahtId)
void ResetLastWP ()
Private Member Functions
void SetMasterMovement ()
bool TrySetNewMaster (Unit *masterCandidat=nullptr)
FormationSlotDataSPtr GetFirstEmptySlot ()
FormationSlotDataSPtr GetFirstAliveSlot ()
int32 GetDefaultSlotId (uint32 dbGuid)
FormationSlotDataSPtr GetDefaultSlot (uint32 dbGuid, SpawnGroupFormationSlotType slotType=SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC)
void FixSlotsPositions ()
void SwitchSlotOwner (FormationSlotDataSPtr slotA, FormationSlotDataSPtr slotB)
bool SetFollowersMaster ()
void ClearMoveGen ()
bool FreeSlot (FormationSlotDataSPtr slot)
bool AddInFormationSlot (Unit *newUnit, SpawnGroupFormationSlotType slotType=SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC)
void StartFollower ()
void StopFollower ()
bool HaveOption (SpawGroupFormationOptions const &option, uint32 const &options) const
bool HaveOption (SpawGroupFormationOptions const &option) const
Private Attributes
CreatureGroup * m_groupData
FormationEntrySPtr m_fEntry
SpawnGroupFormationType m_currentFormationShape
FormationSlotMap m_slotsMap
MovementGeneratorType m_masterMotionType
RespawnPosition m_spawnPos
bool m_mirrorState
bool m_followerStopped
bool m_masterDied
uint32 m_realMasterDBGuid
uint32 m_slotGuid
uint32 m_lastWP
uint32 m_wpPathId
uint32 m_currentOptions
TimePoint m_nextVariation
TimePoint m_nextVariationUpdate
TimePoint m_followerStartTime
float m_currentSpread
Detailed Description
Definition at line 186 of file SpawnGroup.h.
Constructor & Destructor Documentation
FormationData() [1/2]
FormationData::FormationData (CreatureGroup * gData, FormationEntrySPtr fEntry)
Definition at line 613 of file SpawnGroup.cpp.
References SpawnGroupEntry::DbGuids, SpawnGroup::GetGroupEntry(), m_currentFormationShape, m_currentOptions, m_currentSpread, m_fEntry, m_groupData, m_masterMotionType, m_realMasterDBGuid, m_slotGuid, and m_slotsMap.
FormationData() [2/2]
FormationData::FormationData () delete
~FormationData()
FormationData::~FormationData ()
Definition at line 636 of file SpawnGroup.cpp.
References SpawnGroup::GetGroupEntry(), SpawnGroupEntry::Id, m_groupData, and sLog.
Member Function Documentation
Add() [1/2]
void FormationData::Add (Creature * creature)
Definition at line 1088 of file SpawnGroup.cpp.
References Object::GetDbGuid(), GetDefaultSlot(), Unit::GetFormationSlot(), SpawnGroup::GetGroupId(), Object::GetGuidStr(), Unit::IsAlive(), Creature::IsTemporarySummon(), m_groupData, m_slotGuid, m_slotsMap, SetFormationSlot(), sLog, and SPAWN_GROUP_FORMATION_SLOT_TYPE_SCRIPT.
Add() [2/2]
void FormationData::Add (Player * player)
Definition at line 1123 of file SpawnGroup.cpp.
References FixSlotsPositions(), Object::GetDbGuid(), GetDefaultSlot(), Unit::GetFormationSlot(), SpawnGroup::GetGroupId(), Object::GetGuidStr(), m_groupData, m_slotGuid, m_slotsMap, SetFollowersMaster(), Unit::SetFormationSlot(), sLog, and SPAWN_GROUP_FORMATION_SLOT_TYPE_PLAYER.
AddInFormationSlot()
bool FormationData::AddInFormationSlot (Unit * newUnit, SpawnGroupFormationSlotType slotType = SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC) private
Definition at line 1032 of file SpawnGroup.cpp.
References FreeSlot(), Object::GetDbGuid(), GetDefaultSlot(), Object::GetGuidStr(), Unit::IsAlive(), Unit::SetFormationSlot(), and sLog.
Referenced by SetFormationSlot().
CanUseMMap()
bool FormationData::CanUseMMap () const inline
Definition at line 212 of file SpawnGroup.h.
References HaveOption(), and SPAWN_GROUP_FORMATION_OPTION_FOLLOWERS_WILL_NOT_PATHFIND_TO_LOCATION.
ClearMoveGen()
void FormationData::ClearMoveGen () private
Definition at line 722 of file SpawnGroup.cpp.
References MotionMaster::getLastReachedWaypoint(), Unit::GetMotionMaster(), Unit::GetOwner(), MotionMaster::GetPathId(), MotionMaster::Initialize(), Unit::IsAlive(), m_fEntry, m_lastWP, m_slotsMap, and m_wpPathId.
Referenced by Disband().
Compact()
void FormationData::Compact (bool set = true)
Definition at line 1078 of file SpawnGroup.cpp.
References FixSlotsPositions(), m_currentOptions, and SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT.
Disband()
void FormationData::Disband ()
Definition at line 706 of file SpawnGroup.cpp.
References ClearMoveGen(), Unit::GetOwner(), m_slotsMap, and Unit::SetFormationSlot().
FixSlotsPositions()
void FormationData::FixSlotsPositions () private
Definition at line 1415 of file SpawnGroup.cpp.
References GetMaster(), HaveOption(), m_currentFormationShape, m_currentSpread, M_PI_F, m_slotsMap, SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT, SPAWN_GROUP_FORMATION_TYPE_CIRCLE_THE_LEADER, SPAWN_GROUP_FORMATION_TYPE_FANNED_OUT_BEHIND, SPAWN_GROUP_FORMATION_TYPE_FANNED_OUT_IN_FRONT, SPAWN_GROUP_FORMATION_TYPE_LIKE_GEESE, SPAWN_GROUP_FORMATION_TYPE_RANDOM, SPAWN_GROUP_FORMATION_TYPE_SIDE_BY_SIDE, and SPAWN_GROUP_FORMATION_TYPE_SINGLE_FILE.
Referenced by Add(), Compact(), OnDeath(), Remove(), SetFormationSlot(), SetOptions(), SetSpread(), SwitchFormation(), and TrySetNewMaster().
FreeSlot()
bool FormationData::FreeSlot (FormationSlotDataSPtr slot) private
Definition at line 1010 of file SpawnGroup.cpp.
References GetDefaultSlot(), GetFirstEmptySlot(), SpawnGroup::GetGroupId(), m_groupData, sLog, and SwitchSlotOwner().
Referenced by AddInFormationSlot().
GetCurrentShape()
SpawnGroupFormationType FormationData::GetCurrentShape () const inline
Definition at line 209 of file SpawnGroup.h.
References m_currentFormationShape.
GetDefaultSlot()
FormationSlotDataSPtr FormationData::GetDefaultSlot (uint32 dbGuid, SpawnGroupFormationSlotType slotType = SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC) private
Definition at line 961 of file SpawnGroup.cpp.
References GetDefaultSlotId(), m_slotsMap, SPAWN_GROUP_FORMATION_SLOT_TYPE_PLAYER, SPAWN_GROUP_FORMATION_SLOT_TYPE_SCRIPT, and SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC.
Referenced by Add(), AddInFormationSlot(), and FreeSlot().
GetDefaultSlotId()
int32 FormationData::GetDefaultSlotId (uint32 dbGuid) private
Definition at line 953 of file SpawnGroup.cpp.
References SpawnGroupEntry::DbGuids, SpawnGroup::GetGroupEntry(), and m_groupData.
Referenced by GetDefaultSlot().
GetFirstAliveSlot()
FormationSlotDataSPtr FormationData::GetFirstAliveSlot () private
Definition at line 799 of file SpawnGroup.cpp.
References m_slotsMap.
Referenced by TrySetNewMaster().
GetFirstEmptySlot()
FormationSlotDataSPtr FormationData::GetFirstEmptySlot () private
Definition at line 786 of file SpawnGroup.cpp.
References m_slotsMap.
Referenced by FreeSlot().
GetFormationEntry()
FormationEntrySPtr FormationData::GetFormationEntry () const inline
Definition at line 218 of file SpawnGroup.h.
References m_fEntry.
GetMaster()
Unit * FormationData::GetMaster ()
Definition at line 747 of file SpawnGroup.cpp.
References m_slotsMap.
Referenced by FixSlotsPositions(), FormationSlotData::GetMaster(), SetFollowersMaster(), SetFormationSlot(), SetMovementInfo(), and Update().
GetMirrorState()
bool FormationData::GetMirrorState () const inline
Definition at line 206 of file SpawnGroup.h.
References m_mirrorState.
HaveOption() [1/2]
bool FormationData::HaveOption (SpawGroupFormationOptions const & option) const inline private
Definition at line 239 of file SpawnGroup.h.
References m_currentOptions.
HaveOption() [2/2]
bool FormationData::HaveOption (SpawGroupFormationOptions const & option, uint32 const & options) const inline private
Definition at line 238 of file SpawnGroup.h.
Referenced by CanUseMMap(), FixSlotsPositions(), OnDeath(), Remove(), SetOptions(), and to_string().
OnDeath()
void FormationData::OnDeath (Creature * creature)
Definition at line 908 of file SpawnGroup.cpp.
References FixSlotsPositions(), Unit::GetFormationSlot(), MotionMaster::getLastReachedWaypoint(), Unit::GetMotionMaster(), MotionMaster::GetPathId(), HaveOption(), CreatureGroup::IsOutOfCombat(), m_groupData, m_lastWP, m_masterDied, m_wpPathId, Unit::SetFormationSlot(), SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT, and TrySetNewMaster().
Referenced by OnDelete(), and Remove().
OnDelete()
void FormationData::OnDelete (Creature * creature)
Definition at line 946 of file SpawnGroup.cpp.
References OnDeath().
Referenced by Creature::CleanupsBeforeDelete().
OnHome()
void FormationData::OnHome ()
Definition at line 937 of file SpawnGroup.cpp.
References m_masterDied, and TrySetNewMaster().
OnWPEndNode()
void FormationData::OnWPEndNode () inline
Definition at line 205 of file SpawnGroup.h.
References m_mirrorState.
OnWPStartNode()
void FormationData::OnWPStartNode () inline
Definition at line 204 of file SpawnGroup.h.
References m_mirrorState.
Remove() [1/3]
void FormationData::Remove (Creature * creature)
Definition at line 1166 of file SpawnGroup.cpp.
References FixSlotsPositions(), Object::GetDbGuid(), Unit::GetFormationSlot(), Unit::GetMotionMaster(), HaveOption(), MotionMaster::Initialize(), m_slotsMap, OnDeath(), SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT, and SwitchSlotOwner().
Referenced by Creature::ClearCreatureGroup(), and Remove().
Remove() [2/3]
void FormationData::Remove (Player * player)
Definition at line 1208 of file SpawnGroup.cpp.
References FixSlotsPositions(), Object::GetDbGuid(), Unit::GetFormationSlot(), SpawnGroup::GetGroupId(), Object::GetGuidStr(), Unit::GetMotionMaster(), HaveOption(), MotionMaster::Initialize(), m_groupData, m_slotsMap, Unit::SetFormationSlot(), sLog, SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT, SPAWN_GROUP_FORMATION_SLOT_TYPE_PLAYER, and SwitchSlotOwner().
Remove() [3/3]
void FormationData::Remove (Unit * unit)
Definition at line 1156 of file SpawnGroup.cpp.
References Object::IsCreature(), Object::IsPlayer(), and Remove().
Reset()
void FormationData::Reset ()
Definition at line 853 of file SpawnGroup.cpp.
References Map::GetCreature(), CreatureGroup::GetMap(), m_fEntry, m_groupData, m_masterDied, m_mirrorState, m_slotsMap, StartFollower(), SwitchFormation(), SwitchSlotOwner(), and TrySetNewMaster().
ResetLastWP()
void FormationData::ResetLastWP () inline
Definition at line 221 of file SpawnGroup.h.
References m_lastWP.
Referenced by CreatureGroup::RemoveObject().
SetFollowersMaster()
bool FormationData::SetFollowersMaster () private
Definition at line 641 of file SpawnGroup.cpp.
References FORMATION_MOTION_TYPE, GetMaster(), and m_slotsMap.
Referenced by Add(), SetFormationSlot(), and TrySetNewMaster().
SetFormationSlot()
FormationSlotDataSPtr FormationData::SetFormationSlot (Creature * creature, SpawnGroupFormationSlotType slotType = SPAWN_GROUP_FORMATION_SLOT_TYPE_STATIC)
Definition at line 1262 of file SpawnGroup.cpp.
References AddInFormationSlot(), FixSlotsPositions(), Object::GetDbGuid(), Unit::GetFormationSlot(), SpawnGroup::GetGroupEntry(), GetMaster(), Creature::GetRespawnCoord(), Unit::IsAlive(), m_fEntry, m_groupData, m_realMasterDBGuid, m_spawnPos, RespawnPosition::radius, SetFollowersMaster(), SetMasterMovement(), SwitchFormation(), RespawnPosition::x, RespawnPosition::y, and RespawnPosition::z.
Referenced by Add(), and Creature::LoadFromDB().
SetMasterMovement()
void FormationData::SetMasterMovement () private
Definition at line 754 of file SpawnGroup.cpp.
References LINEAR_WP_MOTION_TYPE, m_fEntry, m_lastWP, m_masterMotionType, m_slotsMap, m_spawnPos, m_wpPathId, PATH_FROM_WAYPOINT_PATH, RespawnPosition::radius, RANDOM_MOTION_TYPE, WAYPOINT_MOTION_TYPE, RespawnPosition::x, RespawnPosition::y, and RespawnPosition::z.
Referenced by SetFormationSlot(), and TrySetNewMaster().
SetMovementInfo()
void FormationData::SetMovementInfo (MovementGeneratorType moveType, uint32 pahtId)
Definition at line 1349 of file SpawnGroup.cpp.
References GetMaster(), m_fEntry, m_lastWP, m_masterMotionType, m_spawnPos, RespawnPosition::radius, RespawnPosition::x, RespawnPosition::y, and RespawnPosition::z.
SetOptions()
void FormationData::SetOptions (uint32 options)
Definition at line 695 of file SpawnGroup.cpp.
References FixSlotsPositions(), HaveOption(), m_currentOptions, and SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT.
Referenced by ScriptAction::ExecuteDbscriptCommand().
SetSpread()
void FormationData::SetSpread (float spread) inline
Definition at line 210 of file SpawnGroup.h.
References FixSlotsPositions(), and m_currentSpread.
Referenced by ScriptAction::ExecuteDbscriptCommand().
StartFollower()
void FormationData::StartFollower () private
Definition at line 1063 of file SpawnGroup.cpp.
References m_followerStopped, and m_slotsMap.
Referenced by Reset(), and Update().
StopFollower()
void FormationData::StopFollower () private
Definition at line 1070 of file SpawnGroup.cpp.
References World::GetCurrentClockTime(), m_followerStartTime, m_followerStopped, and m_slotsMap.
Referenced by TrySetNewMaster().
SwitchFormation()
bool FormationData::SwitchFormation (SpawnGroupFormationType newShape)
Definition at line 684 of file SpawnGroup.cpp.
References FixSlotsPositions(), and m_currentFormationShape.
Referenced by ScriptAction::ExecuteDbscriptCommand(), Reset(), and SetFormationSlot().
SwitchSlotOwner()
void FormationData::SwitchSlotOwner (FormationSlotDataSPtr slotA, FormationSlotDataSPtr slotB) private
Definition at line 996 of file SpawnGroup.cpp.
References Unit::GetOwner(), and Unit::SetFormationSlot().
Referenced by FreeSlot(), Remove(), Reset(), and TrySetNewMaster().
to_string()
std::string FormationData::to_string () const
Definition at line 1309 of file SpawnGroup.cpp.
References HaveOption(), m_currentFormationShape, m_currentSpread, m_fEntry, m_masterMotionType, m_slotsMap, and SPAWN_GROUP_FORMATION_OPTION_KEEP_CONPACT.
TrySetNewMaster()
bool FormationData::TrySetNewMaster (Unit * masterCandidat = nullptr) private
Definition at line 812 of file SpawnGroup.cpp.
References FixSlotsPositions(), GetFirstAliveSlot(), Unit::GetFormationSlot(), SpawnGroup::GetGroupId(), Unit::IsAlive(), m_fEntry, m_groupData, m_slotsMap, SetFollowersMaster(), SetMasterMovement(), StopFollower(), and SwitchSlotOwner().
Referenced by OnDeath(), OnHome(), and Reset().
Update()
void FormationData::Update ()
Definition at line 1365 of file SpawnGroup.cpp.
References World::GetCurrentClockTime(), GetMaster(), m_currentFormationShape, m_followerStartTime, m_followerStopped, m_nextVariation, m_nextVariationUpdate, m_slotsMap, SPAWN_GROUP_FORMATION_TYPE_RANDOM, StartFollower(), and urand().
Field Documentation
m_currentFormationShape
SpawnGroupFormationType FormationData::m_currentFormationShape private
Definition at line 243 of file SpawnGroup.h.
Referenced by FixSlotsPositions(), FormationData(), GetCurrentShape(), SwitchFormation(), to_string(), and Update().
m_currentOptions
uint32 FormationData::m_currentOptions private
Definition at line 256 of file SpawnGroup.h.
Referenced by Compact(), FormationData(), HaveOption(), and SetOptions().
m_currentSpread
float FormationData::m_currentSpread private
Definition at line 261 of file SpawnGroup.h.
Referenced by FixSlotsPositions(), FormationData(), SetSpread(), and to_string().
m_fEntry
FormationEntrySPtr FormationData::m_fEntry private
Definition at line 242 of file SpawnGroup.h.
Referenced by ClearMoveGen(), FormationData(), GetFormationEntry(), Reset(), SetFormationSlot(), SetMasterMovement(), SetMovementInfo(), to_string(), and TrySetNewMaster().
m_followerStartTime
TimePoint FormationData::m_followerStartTime private
Definition at line 259 of file SpawnGroup.h.
Referenced by StopFollower(), and Update().
m_followerStopped
bool FormationData::m_followerStopped private
Definition at line 249 of file SpawnGroup.h.
Referenced by StartFollower(), StopFollower(), and Update().
m_groupData
CreatureGroup* FormationData::m_groupData private
Definition at line 241 of file SpawnGroup.h.
Referenced by Add(), FormationData(), FreeSlot(), GetDefaultSlotId(), OnDeath(), Remove(), Reset(), SetFormationSlot(), TrySetNewMaster(), and ~FormationData().
m_lastWP
uint32 FormationData::m_lastWP private
Definition at line 254 of file SpawnGroup.h.
Referenced by ClearMoveGen(), OnDeath(), ResetLastWP(), SetMasterMovement(), and SetMovementInfo().
m_masterDied
bool FormationData::m_masterDied private
Definition at line 250 of file SpawnGroup.h.
Referenced by OnDeath(), OnHome(), and Reset().
m_masterMotionType
MovementGeneratorType FormationData::m_masterMotionType private
Definition at line 245 of file SpawnGroup.h.
Referenced by FormationData(), SetMasterMovement(), SetMovementInfo(), and to_string().
m_mirrorState
bool FormationData::m_mirrorState private
Definition at line 248 of file SpawnGroup.h.
Referenced by GetMirrorState(), OnWPEndNode(), OnWPStartNode(), and Reset().
m_nextVariation
TimePoint FormationData::m_nextVariation private
Definition at line 257 of file SpawnGroup.h.
Referenced by Update().
m_nextVariationUpdate
TimePoint FormationData::m_nextVariationUpdate private
Definition at line 258 of file SpawnGroup.h.
Referenced by Update().
m_realMasterDBGuid
uint32 FormationData::m_realMasterDBGuid private
Definition at line 252 of file SpawnGroup.h.
Referenced by FormationData(), and SetFormationSlot().
m_slotGuid
uint32 FormationData::m_slotGuid private
Definition at line 253 of file SpawnGroup.h.
Referenced by Add(), and FormationData().
m_slotsMap
FormationSlotMap FormationData::m_slotsMap private
Definition at line 244 of file SpawnGroup.h.
Referenced by Add(), ClearMoveGen(), Disband(), FixSlotsPositions(), FormationData(), GetDefaultSlot(), GetFirstAliveSlot(), GetFirstEmptySlot(), GetMaster(), Remove(), Reset(), SetFollowersMaster(), SetMasterMovement(), StartFollower(), StopFollower(), to_string(), TrySetNewMaster(), and Update().
m_spawnPos
RespawnPosition FormationData::m_spawnPos private
Definition at line 246 of file SpawnGroup.h.
Referenced by SetFormationSlot(), SetMasterMovement(), and SetMovementInfo().
m_wpPathId
uint32 FormationData::m_wpPathId private
Definition at line 255 of file SpawnGroup.h.
Referenced by ClearMoveGen(), OnDeath(), and SetMasterMovement().
The documentation for this class was generated from the following files:
SpawnGroup.h
SpawnGroup.cpp