CMaNGOS_WoTLK: FixedPathMovementGenerator Class Reference
FixedPathMovementGenerator Class Reference
#include <PathMovementGenerator.h>
Public Member Functions
FixedPathMovementGenerator (const Movement::PointsArray &path, float orientation, uint32 forcedMovement, bool flying=false, float speed=0, int32 offset=0)
FixedPathMovementGenerator (const Movement::PointsArray &path, uint32 forcedMovement, bool flying=false, float speed=0, int32 offset=0)
FixedPathMovementGenerator (Unit &unit, int32 pathId, WaypointPathOrigin wpOrigin, ForcedMovement forcedMovement, bool flying=false, float speed=0, int32 offset=0, bool cyclic=false, ObjectGuid guid=ObjectGuid())
FixedPathMovementGenerator (Creature &creature)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
void Reset (Unit &unit) override
MovementGeneratorType GetMovementGeneratorType () const override
void AddToPathPauseTime (int32 waitTimeDiff, bool force)
Public Member Functions inherited from AbstractPathMovementGenerator
AbstractPathMovementGenerator (const Movement::PointsArray &path, float orientation=0, int32 offset=0)
AbstractPathMovementGenerator (const WaypointPath *path, int32 offset=0, bool cyclic=false, ObjectGuid guid=ObjectGuid())
bool Update (Unit &owner, const uint32 &) override
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual bool Move (Unit &unit) const
Protected Member Functions inherited from AbstractPathMovementGenerator
virtual void MovementInform (Unit &unit)
Protected Attributes
bool m_flying
float m_speed
uint32 m_forcedMovement
Protected Attributes inherited from AbstractPathMovementGenerator
WaypointPath m_path
int32 m_pathIndex
Movement::PointsArray m_spline
float m_orientation
ShortTimeTracker m_timer
bool m_cyclic
bool m_firstCycle
uint32 m_startPoint
ObjectGuid m_guid
Detailed Description
Definition at line 61 of file PathMovementGenerator.h.
Constructor & Destructor Documentation
FixedPathMovementGenerator() [1/4]
FixedPathMovementGenerator::FixedPathMovementGenerator (const Movement::PointsArray & path, float orientation, uint32 forcedMovement, bool flying = false, float speed = 0, int32 offset = 0) inline
Definition at line 64 of file PathMovementGenerator.h.
FixedPathMovementGenerator() [2/4]
FixedPathMovementGenerator::FixedPathMovementGenerator (const Movement::PointsArray & path, uint32 forcedMovement, bool flying = false, float speed = 0, int32 offset = 0) inline
Definition at line 66 of file PathMovementGenerator.h.
FixedPathMovementGenerator() [3/4]
FixedPathMovementGenerator::FixedPathMovementGenerator (Unit & unit, int32 pathId, WaypointPathOrigin wpOrigin, ForcedMovement forcedMovement, bool flying = false, float speed = 0, int32 offset = 0, bool cyclic = false, ObjectGuid guid = ObjectGuid())
Definition at line 228 of file PathMovementGenerator.cpp.
FixedPathMovementGenerator() [4/4]
FixedPathMovementGenerator::FixedPathMovementGenerator (Creature & creature)
Definition at line 234 of file PathMovementGenerator.cpp.
Member Function Documentation
AddToPathPauseTime()
void FixedPathMovementGenerator::AddToPathPauseTime (int32 waitTimeDiff, bool force)
Definition at line 304 of file PathMovementGenerator.cpp.
References ShortTimeTracker::GetExpiry(), AbstractPathMovementGenerator::m_spline, AbstractPathMovementGenerator::m_timer, ShortTimeTracker::Passed(), and ShortTimeTracker::Reset().
Finalize()
void FixedPathMovementGenerator::Finalize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 254 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Finalize(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
GetMovementGeneratorType()
MovementGeneratorType FixedPathMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Definition at line 76 of file PathMovementGenerator.h.
References PATH_MOTION_TYPE.
Initialize()
void FixedPathMovementGenerator::Initialize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 240 of file PathMovementGenerator.cpp.
References Unit::addUnitState(), AbstractPathMovementGenerator::Initialize(), AbstractPathMovementGenerator::m_firstCycle, AbstractPathMovementGenerator::m_pathIndex, AbstractPathMovementGenerator::m_spline, AbstractPathMovementGenerator::m_startPoint, Move(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Interrupt()
void FixedPathMovementGenerator::Interrupt (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 260 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Interrupt(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Move()
bool FixedPathMovementGenerator::Move (Unit & unit) const protected virtual
Definition at line 272 of file PathMovementGenerator.cpp.
References Movement::MoveSplineInit::CheckBounds(), ERROR_DB_FILTER_LOG, Movement::MoveSpline::Finalized(), FORCED_MOVEMENT_RUN, FORCED_MOVEMENT_WALK, Unit::GetMotionMaster(), WorldObject::GetName(), MotionMaster::GetPathId(), WorldObject::GetPosition(), WorldObject::GetTransport(), Unit::hasUnitState(), Movement::MoveSplineInit::Launch(), LOG_FILTER_AI_AND_MOVEGENSS, AbstractPathMovementGenerator::m_cyclic, m_flying, m_forcedMovement, AbstractPathMovementGenerator::m_orientation, AbstractPathMovementGenerator::m_pathIndex, m_speed, AbstractPathMovementGenerator::m_spline, Movement::MoveSplineInit::MovebyPath(), Unit::movespline, Movement::MoveSplineInit::Path(), Movement::MoveSplineInit::SetCyclic(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetFirstPointId(), Movement::MoveSplineInit::SetFly(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), UNIT_STAT_RUNNING, Unit::UpdateSplinePosition(), Position::x, Position::y, and Position::z.
Referenced by Initialize().
Reset()
void FixedPathMovementGenerator::Reset (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 266 of file PathMovementGenerator.cpp.
References Unit::addUnitState(), AbstractPathMovementGenerator::Reset(), and UNIT_STAT_ROAMING.
Field Documentation
m_flying
bool FixedPathMovementGenerator::m_flying protected
Definition at line 84 of file PathMovementGenerator.h.
Referenced by Move().
m_forcedMovement
uint32 FixedPathMovementGenerator::m_forcedMovement protected
Definition at line 86 of file PathMovementGenerator.h.
Referenced by Move().
m_speed
float FixedPathMovementGenerator::m_speed protected
Definition at line 85 of file PathMovementGenerator.h.
Referenced by Move().
The documentation for this class was generated from the following files:
PathMovementGenerator.h
PathMovementGenerator.cpp