CMaNGOS_WoTLK: GridReference< OBJECT > Class Template Reference
GridReference< OBJECT > Class Template Reference
#include <GridReference.h>
Public Member Functions
GridReference ()
~GridReference ()
GridReference * next ()
Public Member Functions inherited from Reference< GridRefManager< OBJECT >, OBJECT >
Reference ()
virtual ~Reference ()
void link (GridRefManager< OBJECT > *toObj, OBJECT *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< GridRefManager< OBJECT >, OBJECT > * next ()
Reference< GridRefManager< OBJECT >, OBJECT > const * next () const
Reference< GridRefManager< OBJECT >, OBJECT > * prev ()
Reference< GridRefManager< OBJECT >, OBJECT > const * prev () const
Reference< GridRefManager< OBJECT >, OBJECT > * nocheck_next ()
Reference< GridRefManager< OBJECT >, OBJECT > const * nocheck_next () const
Reference< GridRefManager< OBJECT >, OBJECT > * nocheck_prev ()
Reference< GridRefManager< OBJECT >, OBJECT > const * nocheck_prev () const
GridRefManager< OBJECT > * operator-> () const
GridRefManager< OBJECT > * getTarget () const
OBJECT * getSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Detailed Description
template<class OBJECT>
class GridReference< OBJECT >
Definition at line 27 of file GridReference.h.
Constructor & Destructor Documentation
GridReference()
template<class OBJECT > GridReference< OBJECT >::GridReference () inline
Definition at line 53 of file GridReference.h.
~GridReference()
template<class OBJECT > GridReference< OBJECT >::~GridReference () inline
Definition at line 58 of file GridReference.h.
References Reference< GridRefManager< OBJECT >, OBJECT >::unlink().
Member Function Documentation
next()
template<class OBJECT > GridReference* GridReference< OBJECT >::next () inline
Definition at line 63 of file GridReference.h.
sourceObjectDestroyLink()
template<class OBJECT > void GridReference< OBJECT >::sourceObjectDestroyLink () inline override protected virtual
Implements Reference< GridRefManager< OBJECT >, OBJECT >.
Definition at line 45 of file GridReference.h.
References Reference< GridRefManager< OBJECT >, OBJECT >::getTarget().
targetObjectBuildLink()
template<class OBJECT > void GridReference< OBJECT >::targetObjectBuildLink () inline override protected virtual
Implements Reference< GridRefManager< OBJECT >, OBJECT >.
Definition at line 31 of file GridReference.h.
References Reference< GridRefManager< OBJECT >, OBJECT >::getTarget().
targetObjectDestroyLink()
template<class OBJECT > void GridReference< OBJECT >::targetObjectDestroyLink () inline override protected virtual
Implements Reference< GridRefManager< OBJECT >, OBJECT >.
Definition at line 38 of file GridReference.h.
References Reference< GridRefManager< OBJECT >, OBJECT >::getTarget(), and Reference< GridRefManager< OBJECT >, OBJECT >::isValid().
The documentation for this class was generated from the following file:
GridReference.h