CMaNGOS_WoTLK: WorldSession Class Reference
WorldSession Class Reference
User to World Communication
Player session in the World.
#include <WorldSession.h>
Public Member Functions
WorldSession (uint32 id, WorldSocket *sock, AccountTypes sec, uint8 expansion, time_t mute_time, LocaleConstant locale, std::string accountName, uint32 accountFlags, uint32 recruitingFriend, bool isARecruiter)
WorldSession constructor.
~WorldSession ()
WorldSession destructor.
void SetOffline ()
void SetOnline ()
void SetInCharSelection ()
bool RequestNewSocket (WorldSocket *socket)
bool IsOffline () const
WorldSessionState GetState () const
bool PlayerLoading () const
bool PlayerLogout () const
bool PlayerLogoutWithSave () const
void SizeError (WorldPacket const &packet, uint32 size) const
void SendPacket (WorldPacket const &packet) const
Send a packet to the client.
void SendExpectedSpamRecords ()
void SendMotd ()
void SendOfflineNameQueryResponses ()
void SendNotification (const char *format,...) const ATTR_PRINTF(2
void void SendNotification (int32 string_id,...) const
void SendPetNameInvalid (uint32 error, const std::string &name, DeclinedName *declinedName) const
void SendLfgPlayerReward (LfgPlayerRewardData const &rewardData)
void SendPartyResult (PartyOperation operation, const std::string &member, PartyResult res) const
void SendGroupInvite (Player *player, bool alreadyInGroup=false) const
void SendAreaTriggerMessage (const char *Text,...) const ATTR_PRINTF(2
void void SendTransferAborted (uint32 mapid, uint8 reason, uint8 arg=0) const
void SendSetPhaseShift (uint32 PhaseShift) const
void SendQueryTimeResponse () const
void SendRedirectClient (std::string &ip, uint16 port) const
bool IsInitialZoneUpdated ()
AccountTypes GetSecurity () const
uint32 GetAccountFlags () const
bool HasAccountFlag (uint32 flags) const
void AddAccountFlag (uint32 flags)
void RemoveAccountFlag (uint32 flags)
uint32 GetAccountId () const
std::string const & GetAccountName () const
Player * GetPlayer () const
char const * GetPlayerName () const
Get the player name.
std::string GetChatType (uint32 type)
void SetSecurity (AccountTypes security)
const std::string GetRemoteAddress () const
const std::string & GetLocalAddress () const
void SetPlayer (Player *plr, uint32 playerGuid)
uint8 GetExpansion () const
void SetExpansion (uint8 expansion)
void InitializeAnticheat (const BigNumber &K)
void AssignAnticheat ()
void SetDelayedAnticheat (std::unique_ptr< SessionAnticheatInterface > &&anticheat)
SessionAnticheatInterface * GetAnticheat () const
void SetInQueue (bool state)
Session in auth.queue currently.
bool isLogingOut () const
Is the user engaged in a log out process?
void LogoutRequest (time_t requestTime, bool saveToDB=true, bool kickSession=false)
Engage the logout process for the user.
bool ShouldLogOut (time_t currTime) const
Is logout cooldown expired?
bool ShouldDisconnect (time_t currTime)
void LogoutPlayer ()
Log the player out
void KickPlayer (bool save=false, bool inPlace=false)
Kick a player out of the World.
void QueuePacket (std::unique_ptr< WorldPacket > new_packet)
Add an incoming packet to the queue.
void DeleteMovementPackets ()
bool Update (uint32 diff)
Update the WorldSession (triggered by World update)
void UpdateMap (uint32 diff)
void SendAuthWaitQue (uint32 position) const
Handle the authentication waiting queue (to be completed)
void SendNameQueryResponse (CharacterNameQueryResponse &response) const
void SendNameQueryResponseFromDB (ObjectGuid guid) const
void SendTrainerList (ObjectGuid guid) const
void SendListInventory (ObjectGuid guid) const
bool CheckBanker (ObjectGuid guid) const
void SendShowBank (ObjectGuid guid) const
bool CheckMailBox (ObjectGuid guid) const
void SendShowMailBox (ObjectGuid guid) const
void SendTabardVendorActivate (ObjectGuid guid) const
void SendSpiritResurrect () const
void SendBindPoint (Creature *npc) const
void SendGMTicketResult (uint32 opcode, uint32 result) const
void SendGMTicket (const GMTicket &ticket, time_t now=time(nullptr)) const
void SendGMTicketResponseError () const
void SendGMTicketResponseResolve (bool survey) const
void SendGMTicketResponse (GMTicket *ticket) const
void SendBattleGroundList (ObjectGuid guid, BattleGroundTypeId bgTypeId) const
Send battleground list.
void SendTradeStatus (const TradeStatusInfo &status) const
void SendUpdateTrade (bool trader_state=true) const
void SendCancelTrade ()
void SendPetitionQueryOpcode (ObjectGuid petitionguid) const
void SendPetNameQuery (ObjectGuid guid, uint32 petnumber) const
void SendStablePet (ObjectGuid guid) const
void SendStableResult (uint8 res) const
bool CheckStableMaster (ObjectGuid guid) const
AccountData * GetAccountData (AccountDataType type)
void SetAccountData (AccountDataType type, time_t time_, const std::string &data)
void SendAccountDataTimes (uint32 mask)
void LoadGlobalAccountData ()
void LoadAccountData (QueryResult *result, uint32 mask)
void LoadTutorialsData ()
void SendTutorialsData ()
void SaveTutorialsData ()
uint32 GetTutorialInt (uint32 intId)
void SetTutorialInt (uint32 intId, uint32 value)
void SendAuctionHello (Unit *unit) const
void SendAuctionCommandResult (AuctionEntry *auc, AuctionAction Action, AuctionError ErrorCode, InventoryResult invError=EQUIP_ERR_OK) const
void SendAuctionBidderNotification (AuctionEntry *auction) const
void SendAuctionOwnerNotification (AuctionEntry *auction) const
void SendAuctionRemovedNotification (AuctionEntry *auction) const
void BuildListAuctionItems (std::vector< AuctionEntry * > const &auctions, WorldPacket &data, std::wstring const &searchedname, uint32 listfrom, uint32 levelmin, uint32 levelmax, uint32 usable, uint32 inventoryType, uint32 itemClass, uint32 itemSubClass, uint32 quality, uint32 &count, uint32 &totalcount, bool isFull) const
AuctionHouseEntry const * GetCheckedAuctionHouseForAuctioneer (ObjectGuid guid) const
void SendItemEnchantTimeUpdate (ObjectGuid playerGuid, ObjectGuid itemGuid, uint32 slot, uint32 duration) const
void SendTaxiStatus (ObjectGuid guid) const
void SendTaxiMenu (Creature *unit) const
bool SendLearnNewTaxiNode (Creature *unit) const
void SendActivateTaxiReply (ActivateTaxiReply reply) const
void SendGuildCommandResult (uint32 typecmd, const std::string &str, uint32 cmdresult) const
void SendArenaTeamCommandResult (uint32 team_action, const std::string &team, const std::string &player, uint32 error_id) const
void SendNotInArenaTeamPacket (uint8 type) const
void SendPetitionShowList (ObjectGuid guid) const
void SendSaveGuildEmblem (uint32 msg) const
void SendLfgDisabled ()
void SendLfgOfferContinue (uint32 dungeonEntry)
void SendLfgTeleportError (uint8 err)
LocaleConstant GetSessionDbcLocale () const
int GetSessionDbLocaleIndex () const
const char * GetMangosString (int32 entry) const
uint32 GetLatency () const
void SetLatency (uint32 latency)
void ResetClientTimeDelay ()
uint32 getDialogStatus (const Player *pPlayer, const Object *questgiver, uint32 defstatus) const
What - if any - kind of explanation mark or question-mark should a quest-giver display for a player.
ClientOSType GetOS () const
void SetOS (ClientOSType os)
ClientPlatformType GetPlatform () const
void SetPlatform (ClientPlatformType platform)
uint32 GetGameBuild () const
void SetGameBuild (uint32 version)
uint32 GetAccountMaxLevel () const
void SetAccountMaxLevel (uint32 level)
uint32 GetOrderCounter () const
void IncrementOrderCounter ()
uint32 GetRecruitingFriendId () const
bool IsARecruiter () const
void ResetTimeSync ()
void SendTimeSync ()
uint32 GetCurrentPlayerLevel ()
void SetCurrentPlayerLevel (uint32 level)
void SendKnockBack (Unit *who, float angle, float horizontalSpeed, float verticalSpeed)
void SendPlaySpellVisual (ObjectGuid guid, uint32 spellArtKit) const
void SendAuthOk () const
void SendAuthQueued () const
void Handle_NULL (WorldPacket &recvPacket)
void Handle_EarlyProccess (WorldPacket &recvPacket)
void Handle_ServerSide (WorldPacket &recvPacket)
void Handle_Deprecated (WorldPacket &recvPacket)
void HandleCharEnumOpcode (WorldPacket &recvPacket)
void HandleCharDeleteOpcode (WorldPacket &recvPacket)
void HandleCharCreateOpcode (WorldPacket &recvPacket)
void HandlePlayerLoginOpcode (WorldPacket &recvPacket)
void HandleCharEnum (QueryResult *result)
void HandlePlayerLogin (LoginQueryHolder *holder)
void HandlePlayerReconnect ()
void HandlePlayedTime (WorldPacket &recvPacket)
void HandleMoveRootAck (WorldPacket &recvPacket)
void HandleInspectOpcode (WorldPacket &recvPacket)
void HandleInspectHonorStatsOpcode (WorldPacket &recvPacket)
void HandleMoveFlagChangeOpcode (WorldPacket &recvPacket)
void HandleMountSpecialAnimOpcode (WorldPacket &recvdata)
void HandleShowingHelmOpcode (WorldPacket &recv_data)
void HandleShowingCloakOpcode (WorldPacket &recv_data)
void HandleRepairItemOpcode (WorldPacket &recvPacket)
void HandleMoveKnockBackAck (WorldPacket &recvPacket)
void HandleMoveTeleportAckOpcode (WorldPacket &recvPacket)
void HandleForceSpeedChangeAckOpcodes (WorldPacket &recv_data)
void HandleRepopRequestOpcode (WorldPacket &recvPacket)
void HandleAutostoreLootItemOpcode (WorldPacket &recvPacket)
void HandleLootMoneyOpcode (WorldPacket &recvPacket)
void HandleLootOpcode (WorldPacket &recvPacket)
void HandleLootReleaseOpcode (WorldPacket &recvPacket)
void HandleLootMasterGiveOpcode (WorldPacket &recvPacket)
void HandleWhoOpcode (WorldPacket &recvPacket)
void HandleLogoutRequestOpcode (WorldPacket &recvPacket)
void HandlePlayerLogoutOpcode (WorldPacket &recvPacket)
void HandleLogoutCancelOpcode (WorldPacket &recvPacket)
void HandleGMTicketSystemStatusOpcode (WorldPacket &recvPacket)
void HandleGMTicketGetTicketOpcode (WorldPacket &recvPacket)
void HandleGMTicketCreateOpcode (WorldPacket &recvPacket)
void HandleGMTicketUpdateTextOpcode (WorldPacket &recvPacket)
void HandleGMTicketDeleteTicketOpcode (WorldPacket &recvPacket)
void HandleGMSurveySubmitOpcode (WorldPacket &recvPacket)
void HandleGMResponseResolveOpcode (WorldPacket &recv_data)
void HandleTogglePvP (WorldPacket &recvPacket)
void HandleZoneUpdateOpcode (WorldPacket &recvPacket)
void HandleSetTargetOpcode (WorldPacket &recvPacket)
void HandleSetSelectionOpcode (WorldPacket &recvPacket)
void HandleStandStateChangeOpcode (WorldPacket &recvPacket)
void HandleEmoteOpcode (WorldPacket &recvPacket)
void HandleContactListOpcode (WorldPacket &recvPacket)
void HandleAddFriendOpcode (WorldPacket &recvPacket)
void HandleDelFriendOpcode (WorldPacket &recvPacket)
void HandleAddIgnoreOpcode (WorldPacket &recvPacket)
void HandleDelIgnoreOpcode (WorldPacket &recvPacket)
void HandleSetContactNotesOpcode (WorldPacket &recvPacket)
void HandleBugOpcode (WorldPacket &recvPacket)
void HandleSetAmmoOpcode (WorldPacket &recvPacket)
void HandleItemNameQueryOpcode (WorldPacket &recvPacket)
void HandleAreaTriggerOpcode (WorldPacket &recvPacket)
void HandleSetFactionAtWarOpcode (WorldPacket &recv_data)
void HandleSetWatchedFactionOpcode (WorldPacket &recv_data)
void HandleSetFactionInactiveOpcode (WorldPacket &recv_data)
void HandleUpdateAccountData (WorldPacket &recvPacket)
void HandleRequestAccountData (WorldPacket &recvPacket)
void HandleSetActionButtonOpcode (WorldPacket &recvPacket)
void HandleGameObjectUseOpcode (WorldPacket &recPacket)
void HandleGameobjectReportUse (WorldPacket &recvPacket)
void HandleNameQueryOpcode (WorldPacket &recvPacket)
void HandleQueryTimeOpcode (WorldPacket &recvPacket)
void HandleCreatureQueryOpcode (WorldPacket &recvPacket)
Only static data send in this packet !!!
void HandleGameObjectQueryOpcode (WorldPacket &recvPacket)
Only static data send in this packet !!!
void HandleMoveWorldportAckOpcode (WorldPacket &recvPacket)
void HandleMoveWorldportAckOpcode ()
void HandleMovementOpcodes (WorldPacket &recvPacket)
void HandleSetActiveMoverOpcode (WorldPacket &recv_data)
void HandleMoveNotActiveMoverOpcode (WorldPacket &recv_data)
void HandleMoveTimeSkippedOpcode (WorldPacket &recv_data)
bool ProcessMovementInfo (MovementInfo &movementInfo, Unit *mover, Player *plMover, WorldPacket &recv_data)
void HandleDismissControlledVehicle (WorldPacket &recvPacket)
void HandleRequestVehicleExit (WorldPacket &recvPacket)
void HandleRequestVehicleSwitchSeat (WorldPacket &recvPacket)
void HandleRequestVehicleNextSeat (WorldPacket &recvPacket)
void HandleChangeSeatsOnControlledVehicle (WorldPacket &recvPacket)
void HandleRideVehicleInteract (WorldPacket &recvPacket)
void HandleEjectPassenger (WorldPacket &recvPacket)
void HandleRequestRaidInfoOpcode (WorldPacket &recv_data)
void HandleGroupInviteOpcode (WorldPacket &recvPacket)
void HandleGroupAcceptOpcode (WorldPacket &recvPacket)
void HandleGroupDeclineOpcode (WorldPacket &recvPacket)
void HandleGroupUninviteOpcode (WorldPacket &recvPacket)
void HandleGroupUninviteGuidOpcode (WorldPacket &recvPacket)
void HandleGroupSetLeaderOpcode (WorldPacket &recvPacket)
void HandleGroupDisbandOpcode (WorldPacket &recvPacket)
void HandleOptOutOfLootOpcode (WorldPacket &recv_data)
void HandleSetAllowLowLevelRaidOpcode (WorldPacket &recv_data)
void HandleLootMethodOpcode (WorldPacket &recvPacket)
void HandleLootRoll (WorldPacket &recv_data)
void HandleRequestPartyMemberStatsOpcode (WorldPacket &recv_data)
void HandleRaidTargetUpdateOpcode (WorldPacket &recv_data)
void HandleRaidReadyCheckOpcode (WorldPacket &recv_data)
void HandleRaidReadyCheckFinishedOpcode (WorldPacket &recv_data)
void HandleGroupRaidConvertOpcode (WorldPacket &recv_data)
void HandleGroupChangeSubGroupOpcode (WorldPacket &recv_data)
void HandleGroupSwapSubGroupOpcode (WorldPacket &recv_data)
void HandleGroupAssistantLeaderOpcode (WorldPacket &recv_data)
void HandlePartyAssignmentOpcode (WorldPacket &recv_data)
void HandlePetitionBuyOpcode (WorldPacket &recv_data)
void HandlePetitionShowSignOpcode (WorldPacket &recv_data)
void HandlePetitionQueryOpcode (WorldPacket &recv_data)
void HandlePetitionRenameOpcode (WorldPacket &recv_data)
void HandlePetitionSignOpcode (WorldPacket &recv_data)
void HandlePetitionDeclineOpcode (WorldPacket &recv_data)
void HandleOfferPetitionOpcode (WorldPacket &recv_data)
void HandleTurnInPetitionOpcode (WorldPacket &recv_data)
void HandleGuildQueryOpcode (WorldPacket &recvPacket)
void HandleGuildCreateOpcode (WorldPacket &recvPacket)
void HandleGuildInviteOpcode (WorldPacket &recvPacket)
void HandleGuildRemoveOpcode (WorldPacket &recvPacket)
void HandleGuildAcceptOpcode (WorldPacket &recvPacket)
void HandleGuildDeclineOpcode (WorldPacket &recvPacket)
void HandleGuildInfoOpcode (WorldPacket &recvPacket)
void HandleGuildEventLogQueryOpcode (WorldPacket &recvPacket)
void HandleGuildRosterOpcode (WorldPacket &recvPacket)
void HandleGuildPromoteOpcode (WorldPacket &recvPacket)
void HandleGuildDemoteOpcode (WorldPacket &recvPacket)
void HandleGuildLeaveOpcode (WorldPacket &recvPacket)
void HandleGuildDisbandOpcode (WorldPacket &recvPacket)
void HandleGuildLeaderOpcode (WorldPacket &recvPacket)
void HandleGuildMOTDOpcode (WorldPacket &recvPacket)
void HandleGuildSetPublicNoteOpcode (WorldPacket &recvPacket)
void HandleGuildSetOfficerNoteOpcode (WorldPacket &recvPacket)
void HandleGuildRankOpcode (WorldPacket &recvPacket)
void HandleGuildAddRankOpcode (WorldPacket &recvPacket)
void HandleGuildDelRankOpcode (WorldPacket &recvPacket)
void HandleGuildChangeInfoTextOpcode (WorldPacket &recvPacket)
void HandleSaveGuildEmblemOpcode (WorldPacket &recvPacket)
void HandleTaxiNodeStatusQueryOpcode (WorldPacket &recvPacket)
void HandleTaxiQueryAvailableNodes (WorldPacket &recvPacket)
void HandleActivateTaxiOpcode (WorldPacket &recvPacket)
void HandleActivateTaxiExpressOpcode (WorldPacket &recvPacket)
void HandleMoveSplineDoneOpcode (WorldPacket &recvPacket)
void HandleTabardVendorActivateOpcode (WorldPacket &recvPacket)
void HandleBankerActivateOpcode (WorldPacket &recvPacket)
void HandleBuyBankSlotOpcode (WorldPacket &recvPacket)
void HandleTrainerListOpcode (WorldPacket &recvPacket)
void HandleTrainerBuySpellOpcode (WorldPacket &recvPacket)
void HandlePetitionShowListOpcode (WorldPacket &recvPacket)
void HandleGossipHelloOpcode (WorldPacket &recvPacket)
void HandleGossipSelectOptionOpcode (WorldPacket &recvPacket)
void HandleSpiritHealerActivateOpcode (WorldPacket &recvPacket)
void HandleNpcTextQueryOpcode (WorldPacket &recvPacket)
void HandleBinderActivateOpcode (WorldPacket &recvPacket)
void HandleListStabledPetsOpcode (WorldPacket &recvPacket)
void HandleStablePet (WorldPacket &recvPacket)
void HandleUnstablePet (WorldPacket &recvPacket)
void HandleBuyStableSlot (WorldPacket &recvPacket)
void HandleStableRevivePet (WorldPacket &recvPacket)
void HandleStableSwapPet (WorldPacket &recvPacket)
void HandleDuelAcceptedOpcode (WorldPacket &recvPacket)
void HandleDuelCancelledOpcode (WorldPacket &recvPacket)
void HandleAcceptTradeOpcode (WorldPacket &recvPacket)
void HandleBeginTradeOpcode (WorldPacket &recvPacket)
void HandleBusyTradeOpcode (WorldPacket &recvPacket)
void HandleCancelTradeOpcode (WorldPacket &recvPacket)
void HandleClearTradeItemOpcode (WorldPacket &recvPacket)
void HandleIgnoreTradeOpcode (WorldPacket &recvPacket)
void HandleInitiateTradeOpcode (WorldPacket &recvPacket)
void HandleSetTradeGoldOpcode (WorldPacket &recvPacket)
void HandleSetTradeItemOpcode (WorldPacket &recvPacket)
void HandleUnacceptTradeOpcode (WorldPacket &recvPacket)
void HandleAuctionHelloOpcode (WorldPacket &recvPacket)
void HandleAuctionListItems (WorldPacket &recv_data)
void HandleAuctionListBidderItems (WorldPacket &recv_data)
void HandleAuctionSellItem (WorldPacket &recv_data)
void HandleAuctionRemoveItem (WorldPacket &recv_data)
void HandleAuctionListOwnerItems (WorldPacket &recv_data)
void HandleAuctionPlaceBid (WorldPacket &recv_data)
void HandleAuctionListPendingSales (WorldPacket &recv_data)
void HandleGetMailList (WorldPacket &recv_data)
Handles the packet sent by the client when requesting the current mail list.
void HandleSendMail (WorldPacket &recv_data)
Handles the Packet sent by the client when sending a mail.
void HandleMailTakeMoney (WorldPacket &recv_data)
Handles the packet sent by the client when taking money from the mail.
void HandleMailTakeItem (WorldPacket &recv_data)
Handles the packet sent by the client when taking an item from the mail.
void HandleMailMarkAsRead (WorldPacket &recv_data)
Handles the Packet sent by the client when reading a mail.
void HandleMailReturnToSender (WorldPacket &recv_data)
Handles the Packet sent by the client when returning a mail to sender.
void HandleMailDelete (WorldPacket &recv_data)
Handles the Packet sent by the client when deleting a mail.
void HandleItemTextQuery (WorldPacket &recv_data)
Handles the packet sent by the client when requesting information about item text.
void HandleMailCreateTextItem (WorldPacket &recv_data)
Handles the packet sent by the client when he copies the body a mail to his inventory.
void HandleQueryNextMailTime (WorldPacket &recv_data)
No idea when this is called.
void HandleCancelChanneling (WorldPacket &recv_data)
void HandleSplitItemOpcode (WorldPacket &recvPacket)
void HandleSwapInvItemOpcode (WorldPacket &recvPacket)
void HandleDestroyItemOpcode (WorldPacket &recvPacket)
void HandleAutoEquipItemOpcode (WorldPacket &recvPacket)
void HandleItemQuerySingleOpcode (WorldPacket &recvPacket)
void HandleSellItemOpcode (WorldPacket &recvPacket)
void HandleBuyItemInSlotOpcode (WorldPacket &recvPacket)
void HandleBuyItemOpcode (WorldPacket &recvPacket)
void HandleListInventoryOpcode (WorldPacket &recvPacket)
void HandleAutoStoreBagItemOpcode (WorldPacket &recvPacket)
void HandleReadItemOpcode (WorldPacket &recvPacket)
void HandleAutoEquipItemSlotOpcode (WorldPacket &recvPacket)
void HandleSwapItem (WorldPacket &recvPacket)
void HandleBuybackItem (WorldPacket &recvPacket)
void HandleAutoBankItemOpcode (WorldPacket &recvPacket)
void HandleAutoStoreBankItemOpcode (WorldPacket &recvPacket)
void HandleWrapItemOpcode (WorldPacket &recvPacket)
void HandleAttackSwingOpcode (WorldPacket &recvPacket)
void HandleAttackStopOpcode (WorldPacket &recvPacket)
void HandleSetSheathedOpcode (WorldPacket &recvPacket)
void HandleUseItemOpcode (WorldPacket &recvPacket)
void HandleOpenItemOpcode (WorldPacket &recvPacket)
void HandleCastSpellOpcode (WorldPacket &recvPacket)
void HandleCancelCastOpcode (WorldPacket &recvPacket)
void HandleCancelAuraOpcode (WorldPacket &recvPacket)
void HandleCancelGrowthAuraOpcode (WorldPacket &recvPacket)
void HandleCancelAutoRepeatSpellOpcode (WorldPacket &recvPacket)
void HandleLearnTalentOpcode (WorldPacket &recvPacket)
void HandleLearnPreviewTalents (WorldPacket &recvPacket)
void HandleTalentWipeConfirmOpcode (WorldPacket &recvPacket)
void HandleUnlearnSkillOpcode (WorldPacket &recvPacket)
void HandleQuestgiverStatusQueryOpcode (WorldPacket &recvPacket)
void HandleQuestgiverStatusMultipleQuery (WorldPacket &recvPacket)
void HandleQuestgiverHelloOpcode (WorldPacket &recvPacket)
void HandleQuestgiverAcceptQuestOpcode (WorldPacket &recvPacket)
void HandleQuestgiverQueryQuestOpcode (WorldPacket &recvPacket)
void HandleQuestgiverChooseRewardOpcode (WorldPacket &recvPacket)
void HandleQuestgiverRequestRewardOpcode (WorldPacket &recvPacket)
void HandleQuestQueryOpcode (WorldPacket &recvPacket)
void HandleQuestgiverCancel (WorldPacket &recv_data)
void HandleQuestLogSwapQuest (WorldPacket &recv_data)
void HandleQuestLogRemoveQuest (WorldPacket &recv_data)
void HandleQuestConfirmAccept (WorldPacket &recv_data)
void HandleQuestgiverCompleteQuest (WorldPacket &recv_data)
bool CanInteractWithQuestGiver (ObjectGuid guid, char const *descr) const
void HandleQuestgiverQuestAutoLaunch (WorldPacket &recvPacket)
void HandlePushQuestToParty (WorldPacket &recvPacket)
void HandleQuestPushResult (WorldPacket &recvPacket)
bool CheckChatMessage (std::string &, bool addon=false)
void SendPlayerNotFoundNotice (const std::string &name) const
void SendPlayerAmbiguousNotice (const std::string &name) const
void SendWrongFactionNotice () const
void SendChatRestrictedNotice (ChatRestrictionType restriction) const
void HandleMessagechatOpcode (WorldPacket &recvPacket)
void HandleTextEmoteOpcode (WorldPacket &recvPacket)
void HandleChatIgnoredOpcode (WorldPacket &recvPacket)
void HandleReclaimCorpseOpcode (WorldPacket &recvPacket)
void HandleCorpseQueryOpcode (WorldPacket &recvPacket)
void HandleCorpseMapPositionQueryOpcode (WorldPacket &recvPacket)
void HandleResurrectResponseOpcode (WorldPacket &recvPacket)
void HandleSummonResponseOpcode (WorldPacket &recv_data)
bool CheckChatChannelNameAndPassword (std::string &name, std::string &pass)
void HandleJoinChannelOpcode (WorldPacket &recvPacket)
void HandleLeaveChannelOpcode (WorldPacket &recvPacket)
void HandleChannelListOpcode (WorldPacket &recvPacket)
void HandleChannelPasswordOpcode (WorldPacket &recvPacket)
void HandleChannelSetOwnerOpcode (WorldPacket &recvPacket)
void HandleChannelOwnerOpcode (WorldPacket &recvPacket)
void HandleChannelModeratorOpcode (WorldPacket &recvPacket)
void HandleChannelUnmoderatorOpcode (WorldPacket &recvPacket)
void HandleChannelMuteOpcode (WorldPacket &recvPacket)
void HandleChannelUnmuteOpcode (WorldPacket &recvPacket)
void HandleChannelInviteOpcode (WorldPacket &recvPacket)
void HandleChannelKickOpcode (WorldPacket &recvPacket)
void HandleChannelBanOpcode (WorldPacket &recvPacket)
void HandleChannelUnbanOpcode (WorldPacket &recvPacket)
void HandleChannelAnnouncementsOpcode (WorldPacket &recvPacket)
void HandleChannelModerateOpcode (WorldPacket &recvPacket)
void HandleChannelDisplayListQueryOpcode (WorldPacket &recvPacket)
void HandleGetChannelMemberCountOpcode (WorldPacket &recvPacket)
void HandleSetChannelWatchOpcode (WorldPacket &recvPacket)
void HandleCompleteCinematic (WorldPacket &recvPacket)
void HandleNextCinematicCamera (WorldPacket &recvPacket)
void HandlePageQuerySkippedOpcode (WorldPacket &recvPacket)
void HandlePageTextQueryOpcode (WorldPacket &recvPacket)
void HandleTutorialFlagOpcode (WorldPacket &recv_data)
void HandleTutorialClearOpcode (WorldPacket &recv_data)
void HandleTutorialResetOpcode (WorldPacket &recv_data)
void HandlePetAction (WorldPacket &recv_data)
void HandlePetStopAttack (WorldPacket &recv_data)
void HandlePetNameQueryOpcode (WorldPacket &recv_data)
void HandlePetSetAction (WorldPacket &recv_data)
void HandlePetAbandon (WorldPacket &recv_data)
void HandlePetRename (WorldPacket &recv_data)
void HandlePetCancelAuraOpcode (WorldPacket &recvPacket)
void HandlePetUnlearnOpcode (WorldPacket &recvPacket)
void HandlePetSpellAutocastOpcode (WorldPacket &recvPacket)
void HandlePetCastSpellOpcode (WorldPacket &recvPacket)
void HandlePetLearnTalent (WorldPacket &recvPacket)
void HandleLearnPreviewTalentsPet (WorldPacket &recvPacket)
void HandleDismissCritter (WorldPacket &recvPacket)
void HandleSetActionBarTogglesOpcode (WorldPacket &recv_data)
void HandleCharRenameOpcode (WorldPacket &recv_data)
void HandleSetPlayerDeclinedNamesOpcode (WorldPacket &recv_data)
void HandleTotemDestroyed (WorldPacket &recv_data)
void HandleBattlemasterHelloOpcode (WorldPacket &recv_data)
void HandleBattlemasterJoinOpcode (WorldPacket &recv_data)
void HandleBattleGroundPlayerPositionsOpcode (WorldPacket &recv_data)
void HandlePVPLogDataOpcode (WorldPacket &recv_data)
void HandleBattlefieldStatusOpcode (WorldPacket &recv_data)
void HandleBattlefieldPortOpcode (WorldPacket &recv_data)
void HandleBattlefieldListOpcode (WorldPacket &recv_data)
void HandleLeaveBattlefieldOpcode (WorldPacket &recv_data)
void HandleBattlemasterJoinArena (WorldPacket &recv_data)
void HandleReportPvPAFK (WorldPacket &recv_data)
void HandleWorldTeleportOpcode (WorldPacket &recv_data)
void HandleMinimapPingOpcode (WorldPacket &recv_data)
void HandleRandomRollOpcode (WorldPacket &recv_data)
void HandleFarSightOpcode (WorldPacket &recv_data)
void HandleSetDungeonDifficultyOpcode (WorldPacket &recv_data)
void HandleSetRaidDifficultyOpcode (WorldPacket &recv_data)
void HandleChangePlayerDifficulty (WorldPacket &recv_data)
void HandleSetSavedInstanceExtend (WorldPacket &recv_data)
void HandleInstanceLockResponse (WorldPacket &recv_data)
void HandleSetTitleOpcode (WorldPacket &recv_data)
void HandleRealmSplitOpcode (WorldPacket &recv_data)
void HandleTimeSyncResp (WorldPacket &recv_data)
void HandleWhoisOpcode (WorldPacket &recv_data)
void HandleResetInstancesOpcode (WorldPacket &recv_data)
void HandleHearthandResurrect (WorldPacket &recv_data)
void HandleInspectArenaTeamsOpcode (WorldPacket &recv_data)
void HandleArenaTeamQueryOpcode (WorldPacket &recv_data)
void HandleArenaTeamRosterOpcode (WorldPacket &recv_data)
void HandleArenaTeamInviteOpcode (WorldPacket &recv_data)
void HandleArenaTeamAcceptOpcode (WorldPacket &recv_data)
void HandleArenaTeamDeclineOpcode (WorldPacket &recv_data)
void HandleArenaTeamLeaveOpcode (WorldPacket &recv_data)
void HandleArenaTeamRemoveOpcode (WorldPacket &recv_data)
void HandleArenaTeamDisbandOpcode (WorldPacket &recv_data)
void HandleArenaTeamLeaderOpcode (WorldPacket &recv_data)
void HandleAreaSpiritHealerQueryOpcode (WorldPacket &recv_data)
void HandleAreaSpiritHealerQueueOpcode (WorldPacket &recv_data)
void HandleCancelMountAuraOpcode (WorldPacket &recv_data)
void HandleSelfResOpcode (WorldPacket &recv_data)
void HandleComplainOpcode (WorldPacket &recv_data)
void HandleRequestPetInfoOpcode (WorldPacket &recv_data)
void HandleSocketOpcode (WorldPacket &recv_data)
void HandleCancelTempEnchantmentOpcode (WorldPacket &recv_data)
void HandleItemRefundInfoRequest (WorldPacket &recv_data)
void HandleChannelVoiceOnOpcode (WorldPacket &recv_data)
void HandleVoiceSessionEnableOpcode (WorldPacket &recv_data)
void HandleSetActiveVoiceChannel (WorldPacket &recv_data)
void HandleSetTaxiBenchmarkOpcode (WorldPacket &recv_data)
void HandleCommentatorModeOpcode (WorldPacket &recv_data)
void HandleGuildPermissions (WorldPacket &recv_data)
void HandleGuildBankMoneyWithdrawn (WorldPacket &recv_data)
void HandleGuildBankerActivate (WorldPacket &recv_data)
void HandleGuildBankQueryTab (WorldPacket &recv_data)
void HandleGuildBankLogQuery (WorldPacket &recv_data)
void HandleGuildBankDepositMoney (WorldPacket &recv_data)
void HandleGuildBankWithdrawMoney (WorldPacket &recv_data)
void HandleGuildBankSwapItems (WorldPacket &recv_data)
void HandleGuildBankUpdateTab (WorldPacket &recv_data)
void HandleGuildBankBuyTab (WorldPacket &recv_data)
void HandleQueryGuildBankTabText (WorldPacket &recv_data)
void HandleSetGuildBankTabText (WorldPacket &recv_data)
void HandleCalendarGetCalendar (WorldPacket &recv_data)
void HandleCalendarGetEvent (WorldPacket &recv_data)
void HandleCalendarGuildFilter (WorldPacket &recv_data)
void HandleCalendarEventSignup (WorldPacket &recvData)
void HandleCalendarArenaTeam (WorldPacket &recv_data)
void HandleCalendarAddEvent (WorldPacket &recv_data)
void HandleCalendarUpdateEvent (WorldPacket &recv_data)
void HandleCalendarRemoveEvent (WorldPacket &recv_data)
void HandleCalendarCopyEvent (WorldPacket &recv_data)
void HandleCalendarEventInvite (WorldPacket &recv_data)
void HandleCalendarEventRsvp (WorldPacket &recv_data)
void HandleCalendarEventRemoveInvite (WorldPacket &recv_data)
void HandleCalendarEventStatus (WorldPacket &recv_data)
void HandleCalendarEventModeratorStatus (WorldPacket &recv_data)
void HandleCalendarComplain (WorldPacket &recv_data)
void HandleCalendarGetNumPending (WorldPacket &recv_data)
void SendBattlefieldWarInvite (uint32 battlefieldId, uint32 zoneId, uint32 acceptDelay)
Invite a player to join and teleport to a battlefield.
void SendBattlefieldQueueInvite (uint32 battlefieldId)
Invite a player to queue for a battlefield (when entering zone or by battlemaster)
void SendBattlefieldQueueResponse (uint32 battlefieldId, uint32 zoneId, bool canJoin, bool queueFull)
Send response to player when he joins the battlefield queue.
void SendBattlefieldEnteredResponse (uint32 battlefieldId)
Send response when player accepts invitation to a battlefield.
void SendBattlefieldLeaveMessage (uint32 battlefieldId, BattlefieldLeaveReason reason)
Send response when player leaves a battlefield.
void HandleBattlefieldQueueResponse (WorldPacket &recv_data)
void HandleBattlefieldWarResponse (WorldPacket &recv_data)
void HandleBattlefieldExitRequest (WorldPacket &recv_data)
void HandleSpellClick (WorldPacket &recv_data)
void HandleGetMirrorimageData (WorldPacket &recv_data)
void HandleUpdateMissileTrajectory (WorldPacket &recv_data)
void HandleOnMissileTrajectoryCollision (WorldPacket &recv_data)
void HandleClientCastFlags (WorldPacket &recvPacket, uint8 castFlags, SpellCastTargets &targets)
void HandleAlterAppearanceOpcode (WorldPacket &recv_data)
void HandleRemoveGlyphOpcode (WorldPacket &recv_data)
void HandleCharCustomizeOpcode (WorldPacket &recv_data)
void HandleQueryInspectAchievementsOpcode (WorldPacket &recv_data)
void HandleEquipmentSetSaveOpcode (WorldPacket &recv_data)
void HandleEquipmentSetDeleteOpcode (WorldPacket &recv_data)
void HandleEquipmentSetUseOpcode (WorldPacket &recv_data)
void HandleUITimeRequestOpcode (WorldPacket &recv_data)
void HandleReadyForAccountDataTimesOpcode (WorldPacket &recv_data)
void HandleQueryQuestsCompletedOpcode (WorldPacket &recv_data)
void HandleQuestPOIQueryOpcode (WorldPacket &recv_data)
void HandleGrantLevel (WorldPacket &recv_data)
void HandleReferAFriend (WorldPacket &recv_data)
void HandleAcceptLevelGrant (WorldPacket &recv_data)
void HandleWardenDataOpcode (WorldPacket &recv_data)
void SynchronizeMovement (MovementInfo &movementInfo)
void HandleLfgJoinOpcode (WorldPacket &recv_data)
void HandleLfgLeaveOpcode (WorldPacket &recv_data)
void HandleLfrJoinOpcode (WorldPacket &recv_data)
void HandleLfrLeaveOpcode (WorldPacket &recv_data)
void HandleLfgSetCommentOpcode (WorldPacket &recv_data)
void HandleLfgSetBootVoteOpcode (WorldPacket &recv_data)
void HandleLfgTeleportOpcode (WorldPacket &recv_data)
void HandleLfgGetStatus (WorldPacket &recv_data)
void HandleLfgProposalResultOpcode (WorldPacket &recv_data)
void HandleLfgSetRolesOpcode (WorldPacket &recv_data)
void HandleLfgPlayerLockInfoRequestOpcode (WorldPacket &recv_data)
void HandleLfgPartyLockInfoRequestOpcode (WorldPacket &recv_data)
std::deque< uint32 > GetOutOpcodeHistory ()
std::deque< uint32 > GetIncOpcodeHistory ()
Messager< WorldSession > & GetMessager ()
void SetPacketLogging (bool state)
Static Public Member Functions
static WorldPacket BuildLfgJoinResult (LfgJoinResultData joinResult)
static WorldPacket BuildLfgUpdate (LfgUpdateData const &updateData, bool isGroup)
static WorldPacket BuildLfgRoleChosen (ObjectGuid guid, uint8 roles)
static WorldPacket BuildLfgRoleCheckUpdate (LFGQueueData const &data)
static WorldPacket BuildLfgUpdateProposal (LfgProposal const &proposal, uint32 randomDungeonId, ObjectGuid guid)
static void SendNameQueryResponseFromDBCallBack (QueryResult *result, uint32 accountId)
static void SendAuctionOutbiddedMail (AuctionEntry *auction)
static void SendAuctionCancelledToBidderMail (AuctionEntry *auction)
static void BuildPartyMemberStatsChangedPacket (Player *player, WorldPacket &data)
static void HandleAddFriendOpcodeCallBack (QueryResult *result, uint32 accountId, std::string friendNote)
static void HandleAddIgnoreOpcodeCallBack (QueryResult *result, uint32 accountId)
static void HandleChangePlayerNameOpcodeCallBack (QueryResult *result, uint32 accountId, std::string newname)
Data Fields
time_t m_muteTime
ShortTimeTracker m_ticketSquelchTimer
Private Member Functions
void HandleComplainMail (WorldPacket &recv_data)
void HandleComplainChat (WorldPacket &recv_data)
void HandlePetActionHelper (uint8 flag, uint32 spellid, Unit *petUnit, ObjectGuid targetGuid)
void moveItems (Item *myItems[], Item *hisItems[])
bool VerifyMovementInfo (MovementInfo const &movementInfo, Unit *mover, bool unroot) const
void HandleMoverRelocation (MovementInfo &movementInfo)
void ExecuteOpcode (OpcodeHandler const &opHandle, WorldPacket &packet)
void LogUnexpectedOpcode (WorldPacket const &packet, const char *reason) const
Logging helper for unexpected opcodes.
void LogUnprocessedTail (WorldPacket &packet) const
Logging helper for unexpected opcodes.
void ProcessByteBufferException (WorldPacket const &packet)
void ComputeNewClockDelta ()
Private Attributes
uint32 m_GUIDLow
Player * _player
std::shared_ptr< WorldSocket > m_Socket
std::shared_ptr< WorldSocket > m_requestSocket
std::string m_localAddress
WorldSessionState m_sessionState
AccountTypes _security
uint32 _accountId
uint8 m_expansion
std::string m_accountName
uint32 m_accountFlags
ClientOSType m_clientOS
ClientPlatformType m_clientPlatform
uint32 m_gameBuild
uint32 m_accountMaxLevel
uint32 m_orderCounter
uint32 m_lastAnticheatUpdate
std::unique_ptr< SessionAnticheatInterface > m_delayedAnticheat
std::unique_ptr< SessionAnticheatInterface > m_anticheat
time_t _logoutTime
time_t m_kickTime
bool m_playerSave
bool m_inQueue
bool m_playerLoading
bool m_kickSession
bool m_playerLogout
bool m_playerRecentlyLogout
LocaleConstant m_sessionDbcLocale
int m_sessionDbLocaleIndex
uint32 m_latency
uint32 m_clientTimeDelay
AccountData m_accountData [NUM_ACCOUNT_DATA_TYPES]
uint32 m_Tutorials [8]
TutorialDataState m_tutorialState
std::set< ObjectGuid > m_offlineNameQueries
std::deque< CharacterNameQueryResponse > m_offlineNameResponses
bool m_initialZoneUpdated = false
boost::circular_buffer< std::pair< int64, uint32 > > m_timeSyncClockDeltaQueue
int64 m_timeSyncClockDelta
std::map< uint32, uint32 > m_pendingTimeSyncRequests
uint32 m_timeSyncNextCounter
uint32 m_timeSyncTimer
uint32 m_recruitingFriendId
bool m_isRecruiter
std::mutex m_recvQueueLock
std::mutex m_recvQueueMapLock
std::deque< std::unique_ptr< WorldPacket > > m_recvQueue
std::deque< std::unique_ptr< WorldPacket > > m_recvQueueMap
Messager< WorldSession > m_messager
std::atomic< uint32 > m_currentPlayerLevel
Friends
class CharacterHandler
Detailed Description
Player session in the World.
Definition at line 243 of file WorldSession.h.
Constructor & Destructor Documentation
WorldSession()
WorldSession::WorldSession (uint32 id, WorldSocket * sock, AccountTypes sec, uint8 expansion, time_t mute_time, LocaleConstant locale, std::string accountName, uint32 accountFlags, uint32 recruitingFriend, bool isARecruiter)
WorldSession constructor.
Definition at line 97 of file WorldSession.cpp.
~WorldSession()
WorldSession::~WorldSession ()
WorldSession destructor.
unload player if not unloaded
Definition at line 107 of file WorldSession.cpp.
References _player, LogoutPlayer(), and m_Socket.
Member Function Documentation
AddAccountFlag()
void WorldSession::AddAccountFlag (uint32 flags) inline
Definition at line 293 of file WorldSession.h.
References m_accountFlags.
Referenced by HandleAnticheatCheatinformCommand(), HandleAnticheatSpaminformCommand(), and NamreebAnticheat::SessionAnticheat::RecordCheat().
AssignAnticheat()
void WorldSession::AssignAnticheat ()
Definition at line 1284 of file WorldSession.cpp.
References m_anticheat, and m_delayedAnticheat.
Referenced by WorldSocket::HandleAuthSession().
BuildLfgJoinResult()
WorldPacket WorldSession::BuildLfgJoinResult (LfgJoinResultData joinResult) static
Definition at line 322 of file LFGHandler.cpp.
References BuildPartyLockDungeonBlock(), LfgJoinResultData::lockmap, LfgJoinResultData::result, SMSG_LFG_JOIN_RESULT, and LfgJoinResultData::state.
Referenced by LFGMgr::JoinLfg(), and LFGQueueData::UpdateRoleCheck().
BuildLfgRoleCheckUpdate()
WorldPacket WorldSession::BuildLfgRoleCheckUpdate (LFGQueueData const & data) static
Definition at line 412 of file LFGHandler.cpp.
References LFG_ROLECHECK_INITIALITING, LFGQueueData::m_dungeons, LFGQueuePlayer::m_level, LFGQueueData::m_playerInfoPerGuid, LFGQueueData::m_randomDungeonId, LFGQueueData::m_roleCheckState, LFGQueuePlayer::m_roles, sLFGMgr, and SMSG_LFG_ROLE_CHECK_UPDATE.
Referenced by LFGQueueData::UpdateRoleCheck().
BuildLfgRoleChosen()
WorldPacket WorldSession::BuildLfgRoleChosen (ObjectGuid guid, uint8 roles) static
Definition at line 403 of file LFGHandler.cpp.
References SMSG_ROLE_CHOSEN.
Referenced by LFGQueueData::UpdateRoleCheck().
BuildLfgUpdate()
WorldPacket WorldSession::BuildLfgUpdate (LfgUpdateData const & updateData, bool isGroup) static
Definition at line 337 of file LFGHandler.cpp.
References LfgUpdateData::comment, LfgUpdateData::dungeons, LFG_STATE_NONE, LFG_STATE_QUEUED, LFG_STATE_RAIDBROWSER, LFG_STATE_ROLECHECK, LFG_UPDATETYPE_ADDED_TO_QUEUE, LFG_UPDATETYPE_JOIN_QUEUE, LFG_UPDATETYPE_PROPOSAL_BEGIN, LFG_UPDATETYPE_UPDATE_STATUS, LfgUpdateData::m_roles, SMSG_LFG_UPDATE_PARTY, SMSG_LFG_UPDATE_PLAYER, LfgUpdateData::state, and LfgUpdateData::updateType.
Referenced by LfgProposal::AcceptProposal(), LfgProposal::FailProposal(), LFGMgr::JoinLfg(), LFGMgr::LeaveLfg(), LFGQueue::OnPlayerLogout(), LFGQueueData::PopQueue(), and LFGQueueData::UpdateRoleCheck().
BuildLfgUpdateProposal()
WorldPacket WorldSession::BuildLfgUpdateProposal (LfgProposal const & proposal, uint32 randomDungeonId, ObjectGuid guid) static
Definition at line 446 of file LFGHandler.cpp.
References LfgProposalPlayer::answer, LfgProposal::dungeonId, LfgProposal::encounters, LfgProposalPlayer::group, LfgProposal::group, LfgProposal::id, LfgProposal::isNew, LFG_ANSWER_AGREE, LFG_ANSWER_PENDING, LfgProposal::players, LfgProposalPlayer::role, sLFGMgr, SMSG_LFG_PROPOSAL_UPDATE, and LfgProposal::state.
Referenced by LfgProposal::AcceptProposal(), LFGQueueData::PopQueue(), and LFGQueue::UpdateProposal().
BuildListAuctionItems()
void WorldSession::BuildListAuctionItems (std::vector< AuctionEntry * > const & auctions, WorldPacket & data, std::wstring const & searchedname, uint32 listfrom, uint32 levelmin, uint32 levelmax, uint32 usable, uint32 inventoryType, uint32 itemClass, uint32 itemSubClass, uint32 quality, uint32 & count, uint32 & totalcount, bool isFull) const
Definition at line 806 of file AuctionHouseMgr.cpp.
References _player, Player::CanUseItem(), ItemPrototype::Class, EFFECT_INDEX_0, EQUIP_ERR_OK, Item::GetProto(), Player::GetSession(), GetSessionDbLocaleIndex(), Player::HasSpell(), ItemPrototype::InventoryType, INVTYPE_CHEST, INVTYPE_ROBE, ITEM_CLASS_RECIPE, ItemPrototype::ItemId, SQLStorage::LookupEntry(), ItemPrototype::Name1, ItemPrototype::Quality, ItemPrototype::RequiredLevel, sAuctionMgr, sObjectMgr, _Spell::SpellId, ItemPrototype::Spells, sSpellTemplate, ItemPrototype::SubClass, and Utf8FitTo().
Referenced by HandleAuctionListItems().
BuildPartyMemberStatsChangedPacket()
void WorldSession::BuildPartyMemberStatsChangedPacket (Player * player, WorldPacket & data) static
Definition at line 665 of file GroupHandler.cpp.
References Unit::GetAuraUpdateMask(), Unit::GetCharm(), Unit::GetDisplayId(), GetGroupMemberStatus(), Player::GetGroupUpdateFlag(), Unit::GetHealth(), Unit::GetLevel(), Unit::GetMaxHealth(), Unit::GetMaxPower(), WorldObject::GetName(), Object::GetObjectGuid(), Object::GetPackGUID(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Unit::GetPower(), Unit::GetPowerType(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Unit::GetVisibleAura(), WorldObject::GetZoneId(), GROUP_UPDATE_FLAG_AURAS, GROUP_UPDATE_FLAG_CUR_HP, GROUP_UPDATE_FLAG_CUR_POWER, GROUP_UPDATE_FLAG_LEVEL, GROUP_UPDATE_FLAG_MAX_HP, GROUP_UPDATE_FLAG_MAX_POWER, GROUP_UPDATE_FLAG_PET_AURAS, GROUP_UPDATE_FLAG_PET_CUR_HP, GROUP_UPDATE_FLAG_PET_CUR_POWER, GROUP_UPDATE_FLAG_PET_GUID, GROUP_UPDATE_FLAG_PET_MAX_HP, GROUP_UPDATE_FLAG_PET_MAX_POWER, GROUP_UPDATE_FLAG_PET_MODEL_ID, GROUP_UPDATE_FLAG_PET_NAME, GROUP_UPDATE_FLAG_PET_POWER_TYPE, GROUP_UPDATE_FLAG_POSITION, GROUP_UPDATE_FLAG_POWER_TYPE, GROUP_UPDATE_FLAG_STATUS, GROUP_UPDATE_FLAG_VEHICLE_SEAT, GROUP_UPDATE_FLAG_ZONE, GROUP_UPDATE_FLAGS_COUNT, GroupUpdateLength, WorldPacket::Initialize(), MAX_AURAS, and SMSG_PARTY_MEMBER_STATS.
Referenced by Group::UpdatePlayerOutOfRange().
CanInteractWithQuestGiver()
bool WorldSession::CanInteractWithQuestGiver (ObjectGuid guid, char const * descr) const
Definition at line 781 of file QuestHandler.cpp.
References _player, DEBUG_LOG, GAMEOBJECT_TYPE_QUESTGIVER, Player::GetGameObjectIfCanInteractWith(), Object::GetGuidStr(), Player::GetNPCIfCanInteractWith(), ObjectGuid::GetString(), Unit::IsAlive(), ObjectGuid::IsCreatureOrVehicle(), ObjectGuid::IsGameObject(), and UNIT_NPC_FLAG_QUESTGIVER.
Referenced by HandleQuestgiverAcceptQuestOpcode(), HandleQuestgiverChooseRewardOpcode(), HandleQuestgiverCompleteQuest(), and HandleQuestgiverRequestRewardOpcode().
CheckBanker()
bool WorldSession::CheckBanker (ObjectGuid guid) const
Definition at line 894 of file ItemHandler.cpp.
References DEBUG_LOG, GetPlayer(), ObjectGuid::GetString(), and UNIT_NPC_FLAG_BANKER.
Referenced by HandleBankerActivateOpcode(), and HandleBuyBankSlotOpcode().
CheckChatChannelNameAndPassword()
bool WorldSession::CheckChatChannelNameAndPassword (std::string & name, std::string & pass)
Definition at line 22 of file ChannelHandler.cpp.
References CHAT_INVALID_NAME_NOTICE, CHAT_WRONG_PASSWORD_NOTICE, GetPlayer(), GetSecurity(), ChatHandler::HasEscapeSequences(), SEC_PLAYER, SendPacket(), sLog, SMSG_CHANNEL_NOTIFY, stripLineInvisibleChars(), and utf8limit().
Referenced by HandleJoinChannelOpcode().
CheckChatMessage()
bool WorldSession::CheckChatMessage (std::string & msg, bool addon = false)
Definition at line 40 of file ChatHandler.cpp.
References _player, ChatHandler::CheckEscapeSequences(), CONFIG_BOOL_CHAT_FAKE_MESSAGE_PREVENTING, CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_KICK, CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_SEVERITY, GetPlayer(), GetSecurity(), KickPlayer(), SEC_PLAYER, sLog, stripLineInvisibleChars(), sWorld, and utf8limit().
Referenced by HandleGMSurveySubmitOpcode(), HandleGMTicketCreateOpcode(), HandleGMTicketUpdateTextOpcode(), and HandleMessagechatOpcode().
CheckStableMaster()
bool WorldSession::CheckStableMaster (ObjectGuid guid) const
Definition at line 588 of file NPCHandler.cpp.
References DEBUG_LOG, GetPlayer(), ObjectGuid::GetString(), SPELL_AURA_OPEN_STABLE, and UNIT_NPC_FLAG_STABLEMASTER.
Referenced by HandleBuyStableSlot(), HandleListStabledPetsOpcode(), HandleStablePet(), HandleStableSwapPet(), and HandleUnstablePet().
ComputeNewClockDelta()
void WorldSession::ComputeNewClockDelta () private
Definition at line 856 of file MovementHandler.cpp.
References m_timeSyncClockDelta, and m_timeSyncClockDeltaQueue.
Referenced by HandleTimeSyncResp().
DeleteMovementPackets()
void WorldSession::DeleteMovementPackets ()
Definition at line 290 of file WorldSession.cpp.
References m_recvQueueMap, m_recvQueueMapLock, MSG_MOVE_HEARTBEAT, and MSG_MOVE_SET_FACING.
Referenced by Player::SetSemaphoreTeleportFar(), and Player::SetSemaphoreTeleportNear().
ExecuteOpcode()
void WorldSession::ExecuteOpcode (OpcodeHandler const & opHandle, WorldPacket & packet) private
Definition at line 1167 of file WorldSession.cpp.
References _player, OpcodeHandler::handler, Player::IsHasDelayedTeleport(), LOG_LVL_DEBUG, LogUnprocessedTail(), Player::m_teleport_dest, Player::m_teleport_options, ProcessByteBufferException(), ByteBuffer::rpos(), Player::SetCanDelayTeleport(), sLog, Player::TeleportTo(), and ByteBuffer::wpos().
Referenced by Update(), and UpdateMap().
GetAccountData()
AccountData* WorldSession::GetAccountData (AccountDataType type) inline
Definition at line 397 of file WorldSession.h.
References m_accountData.
Referenced by HandleRequestAccountData(), and SendAccountDataTimes().
GetAccountFlags()
uint32 WorldSession::GetAccountFlags () const inline
Definition at line 291 of file WorldSession.h.
References m_accountFlags.
Referenced by NamreebAnticheat::AntispamMgr::IsSilenced(), and NamreebAnticheat::SessionAnticheat::RecordCheatInternal().
GetAccountId()
uint32 WorldSession::GetAccountId () const inline
Definition at line 295 of file WorldSession.h.
References _accountId.
Referenced by PlayerbotAI::_HandleCommandMail(), Player::_LoadCreatedInstanceTimers(), Player::_SaveNewInstanceIdTimer(), Guild::AddMember(), World::AddSession_(), World::BanAccount(), PlayerbotAI::canObeyCommandFrom(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), ChatHandler::ExtractAccountId(), ChatHandler::GetAccountId(), WardenWin::GetScanFlags(), HandleAcceptLevelGrant(), HandleAcceptTradeOpcode(), ChatHandler::HandleAddCharacterNoteCommand(), HandleAddFriendOpcode(), HandleAddIgnoreOpcode(), HandleAnticheatCheatinformCommand(), HandleAnticheatSpaminformCommand(), HandleAuctionPlaceBid(), HandleAuctionSellItem(), ChatHandler::HandleBanInfoCharacterCommand(), HandleChangePlayerNameOpcodeCallBack(), ChatHandler::HandleCharacterEraseCommand(), HandleCharCreateOpcode(), HandleCharCustomizeOpcode(), HandleCharDeleteOpcode(), HandleCharEnum(), HandleCharEnumOpcode(), HandleCharRenameOpcode(), HandleForceSpeedChangeAckOpcodes(), HandleGrantLevel(), HandleGuildBankDepositMoney(), HandleMailReturnToSender(), HandleMailTakeItem(), ChatHandler::HandleMuteCommand(), Warden::HandlePacket(), HandlePetitionSignOpcode(), ChatHandler::HandlePInfoCommand(), HandlePlayerLogin(), HandlePlayerLoginOpcode(), HandlePlayerReconnect(), HandleSendMail(), ChatHandler::HandleUnmuteCommand(), ChatHandler::HandleWarnCharacterCommand(), HandleWhoisOpcode(), Item::IsBindedNotWith(), LoadGlobalAccountData(), LoadTutorialsData(), LogoutPlayer(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), moveItems(), Player::OnGossipSelect(), ProcessByteBufferException(), WorldSocket::ProcessIncomingData(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), NamreebAnticheat::SessionAnticheat::RecordCheat(), Warden::RequestChallenge(), SaveTutorialsData(), AuctionHouseMgr::SendAuctionWonMail(), Warden::SendModuleToClient(), SendNameQueryResponseFromDB(), SetAccountData(), SizeError(), Warden::Update(), WardenWin::Update(), WardenWin::ValidateEndScene(), NamreebAnticheat::SessionAnticheat::VerifyTracking(), and Warden::Warden().
GetAccountMaxLevel()
uint32 WorldSession::GetAccountMaxLevel () const inline
Definition at line 476 of file WorldSession.h.
References m_accountMaxLevel.
Referenced by WardenMac::GetScanFlags(), WardenWin::GetScanFlags(), and NamreebAnticheat::SessionAnticheat::RecordCheatInternal().
GetAccountName()
std::string const& WorldSession::GetAccountName () const inline
Definition at line 296 of file WorldSession.h.
References m_accountName.
Referenced by NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), NamreebAnticheat::SessionAnticheat::Update(), WardenMac::WardenMac(), and NamreebAnticheat::SessionAnticheat::~SessionAnticheat().
GetAnticheat()
SessionAnticheatInterface* WorldSession::GetAnticheat () const inline
Definition at line 316 of file WorldSession.h.
References m_anticheat.
Referenced by Player::CheckAreaExploreAndOutdoor(), HandleAnticheatFingerprintListCommand(), HandleAnticheatInfoCommand(), HandleAnticheatSpaminfoCommand(), WorldSocket::HandleAuthSession(), HandleGroupInviteOpcode(), ChatHandler::HandlePInfoCommand(), HandleSendMail(), Channel::Invite(), Player::RemoveFromWorld(), Player::Say(), Channel::Say(), Unit::SendMoveRoot(), Unit::SendTeleportPacket(), Unit::SetSpeedRate(), Player::TextEmote(), Player::Whisper(), and Player::Yell().
GetChatType()
std::string WorldSession::GetChatType (uint32 type)
GetCheckedAuctionHouseForAuctioneer()
AuctionHouseEntry const * WorldSession::GetCheckedAuctionHouseForAuctioneer (ObjectGuid guid) const
Definition at line 196 of file AuctionHouseHandler.cpp.
References DEBUG_LOG, AuctionHouseMgr::GetAuctionHouseEntry(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), and UNIT_NPC_FLAG_AUCTIONEER.
Referenced by HandleAuctionListBidderItems(), HandleAuctionListItems(), HandleAuctionListOwnerItems(), HandleAuctionListPendingSales(), HandleAuctionPlaceBid(), HandleAuctionRemoveItem(), and HandleAuctionSellItem().
GetCurrentPlayerLevel()
uint32 WorldSession::GetCurrentPlayerLevel () inline
Definition at line 490 of file WorldSession.h.
References m_currentPlayerLevel.
getDialogStatus()
uint32 WorldSession::getDialogStatus (const Player * pPlayer, const Object * questgiver, uint32 defstatus) const
What - if any - kind of explanation mark or question-mark should a quest-giver display for a player.
Parameters
pPlayer - for whom
questgiver - from whom
defstatus - initial set status (usually it will be called with DIALOG_STATUS_NONE) - must not be DIALOG_STATUS_UNDEFINED
Definition at line 675 of file QuestHandler.cpp.
References Player::CanSeeStartQuest(), Player::CanTakeQuest(), CONFIG_INT32_QUEST_LOW_LEVEL_HIDE_DIFF, DIALOG_STATUS_AVAILABLE, DIALOG_STATUS_AVAILABLE_REP, DIALOG_STATUS_INCOMPLETE, DIALOG_STATUS_LOW_LEVEL_AVAILABLE, DIALOG_STATUS_NONE, DIALOG_STATUS_REWARD, DIALOG_STATUS_REWARD_REP, DIALOG_STATUS_UNAVAILABLE, DIALOG_STATUS_UNDEFINED, Object::GetEntry(), Player::GetQuestLevelForPlayer(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Object::GetTypeId(), Quest::HasQuestFlag(), Quest::IsActive(), Quest::IsAutoComplete(), Quest::IsDailyOrWeekly(), Quest::IsRepeatable(), MANGOS_ASSERT, QUEST_FLAGS_DAILY, QUEST_FLAGS_WEEKLY, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_STATUS_NONE, Player::SatisfyQuestLevel(), sLog, sObjectMgr, sWorld, TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by HandleQuestgiverStatusQueryOpcode(), and Player::SendQuestGiverStatusMultiple().
GetExpansion()
uint8 WorldSession::GetExpansion () const inline
Definition at line 310 of file WorldSession.h.
References m_expansion.
Referenced by World::AddQueuedSession(), LFGMgr::GetLockedDungeons(), HandleCharCreateOpcode(), HandleLfgPlayerLockInfoRequestOpcode(), HandlePlayerLogin(), and SendAuthOk().
GetGameBuild()
uint32 WorldSession::GetGameBuild () const inline
Definition at line 474 of file WorldSession.h.
References m_gameBuild.
Referenced by WardenWin::GetScanFlags(), and NamreebAnticheat::SessionAnticheat::SendPlayerInfo().
GetIncOpcodeHistory()
std::deque< uint32 > WorldSession::GetIncOpcodeHistory ()
Definition at line 1226 of file WorldSession.cpp.
References m_Socket.
Referenced by ChatHandler::HandleDebugIncPacketHistory().
GetLatency()
uint32 WorldSession::GetLatency () const inline
Definition at line 466 of file WorldSession.h.
References m_latency.
Referenced by ChatHandler::HandlePInfoCommand(), and NamreebAnticheat::SessionAnticheat::Update().
GetLocalAddress()
const std::string& WorldSession::GetLocalAddress () const inline
Definition at line 307 of file WorldSession.h.
References m_localAddress.
Referenced by NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), and NamreebAnticheat::SessionAnticheat::SendPlayerInfo().
GetMangosString()
const char * WorldSession::GetMangosString (int32 entry) const
Definition at line 920 of file WorldSession.cpp.
References GetSessionDbLocaleIndex(), and sObjectMgr.
Referenced by Player::_LoadInventory(), Player::AutoUnequipOffhandIfNeed(), ChatHandler::GetMangosString(), HandleAddFriendOpcode(), HandleAddIgnoreOpcode(), HandleMessagechatOpcode(), HandleTextEmoteOpcode(), GMTicketMgr::PrintTicketList(), SendNotification(), BattleGround::SendRewardMarkByMail(), SendTrainerList(), and Player::Whisper().
GetMessager()
Messager<WorldSession>& WorldSession::GetMessager () inline
Definition at line 1007 of file WorldSession.h.
References m_messager.
Referenced by WorldSocket::HandleAuthSession(), HandleCastSpellOpcode(), ProcessByteBufferException(), and Update().
GetOrderCounter()
uint32 WorldSession::GetOrderCounter () const inline
Definition at line 478 of file WorldSession.h.
References m_orderCounter.
Referenced by SendKnockBack(), Unit::SendMoveRoot(), Unit::SendTeleportPacket(), and Unit::SetSpeedRate().
GetOS()
ClientOSType WorldSession::GetOS () const inline
Definition at line 470 of file WorldSession.h.
References m_clientOS.
Referenced by Warden::HandlePacket(), Warden::RequestScans(), and NamreebAnticheat::SessionAnticheat::SendPlayerInfo().
GetOutOpcodeHistory()
std::deque< uint32 > WorldSession::GetOutOpcodeHistory ()
Definition at line 1218 of file WorldSession.cpp.
References m_Socket.
Referenced by ChatHandler::HandleDebugOutPacketHistory().
GetPlatform()
ClientPlatformType WorldSession::GetPlatform () const inline
Definition at line 472 of file WorldSession.h.
References m_clientPlatform.
Referenced by Warden::Warden().
GetPlayer()
Player* WorldSession::GetPlayer () const inline
Definition at line 297 of file WorldSession.h.
References _player.
Referenced by Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), CheckBanker(), CheckChatChannelNameAndPassword(), CheckChatMessage(), CheckMailBox(), CheckStableMaster(), Guild::DisplayGuildBankContent(), Guild::DisplayGuildBankMoneyUpdate(), Guild::DisplayGuildBankTabsInfo(), instance_molten_core::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), ChatHandler::ExtractLocationFromLink(), GetCheckedAuctionHouseForAuctioneer(), ChatHandler::GetGameObjectWithGuid(), ChatHandler::GetNameLink(), GetPlayerName(), ChatHandler::getSelectedCreature(), ChatHandler::getSelectedPlayer(), ChatHandler::getSelectedUnit(), HandleActivateTaxiExpressOpcode(), HandleActivateTaxiOpcode(), HandleAddFriendOpcode(), HandleAddFriendOpcodeCallBack(), HandleAddIgnoreOpcode(), HandleAddIgnoreOpcodeCallBack(), ChatHandler::HandleAddItemCommand(), ChatHandler::HandleAddItemSetCommand(), HandleAreaSpiritHealerQueryOpcode(), HandleAreaSpiritHealerQueueOpcode(), HandleAreaTriggerOpcode(), HandleArenaTeamInviteOpcode(), HandleAttackStopOpcode(), ChatHandler::HandleAuctionAllianceCommand(), ChatHandler::HandleAuctionCommand(), ChatHandler::HandleAuctionGoblinCommand(), HandleAuctionHelloOpcode(), ChatHandler::HandleAuctionHordeCommand(), HandleAuctionListBidderItems(), HandleAuctionListItems(), HandleAuctionPlaceBid(), HandleAuctionRemoveItem(), HandleAuctionSellItem(), ChatHandler::HandleAuraCommand(), ChatHandler::HandleBagsCommand(), ChatHandler::HandleBankCommand(), HandleBattlefieldExitRequest(), HandleBattlefieldQueueResponse(), HandleBattlefieldWarResponse(), ChatHandler::HandleBattlegroundStartCommand(), ChatHandler::HandleBattlegroundStopCommand(), HandleBattlemasterHelloOpcode(), HandleBattlemasterJoinArena(), HandleBinderActivateOpcode(), HandleBuybackItem(), HandleBuyItemInSlotOpcode(), HandleBuyItemOpcode(), HandleBuyStableSlot(), HandleCancelTempEnchantmentOpcode(), ChatHandler::HandleCastBackCommand(), ChatHandler::HandleCastCommand(), ChatHandler::HandleCastDistCommand(), ChatHandler::HandleCastSelfCommand(), ChatHandler::HandleCastTargetCommand(), ChatHandler::HandleChangeWeatherCommand(), ChatHandler::HandleChannelStaticCommand(), ChatHandler::HandleCharacterLevelCommand(), ChatHandler::HandleCombatListCommand(), ChatHandler::HandleComeToMeCommand(), HandleCommentatorModeOpcode(), HandleCompleteCinematic(), ChatHandler::HandleCooldownClearCommand(), HandleCorpseQueryOpcode(), ChatHandler::HandleDamageCommand(), ChatHandler::HandleDebugAnimCommand(), ChatHandler::HandleDebugAreaTriggersCommand(), ChatHandler::HandleDebugChatFreezeCommand(), ChatHandler::HandleDebugDbscript(), ChatHandler::HandleDebugDbscriptGuided(), ChatHandler::HandleDebugDbscriptSourced(), ChatHandler::HandleDebugDbscriptTargeted(), ChatHandler::HandleDebugGetItemStateCommand(), ChatHandler::HandleDebugGetItemValueCommand(), ChatHandler::HandleDebugHaveAtClientCommand(), ChatHandler::HandleDebugIncPacketHistory(), ChatHandler::HandleDebugIsVisibleCommand(), ChatHandler::HandleDebugModItemValueCommand(), ChatHandler::HandleDebugOutPacketHistory(), ChatHandler::HandleDebugPetDismissSound(), ChatHandler::HandleDebugPlayCinematicCommand(), ChatHandler::HandleDebugPlayMovieCommand(), ChatHandler::HandleDebugPlayMusicCommand(), ChatHandler::HandleDebugPlaySoundCommand(), ChatHandler::HandleDebugRespawnDynguid(), ChatHandler::HandleDebugSendBuyErrorCommand(), ChatHandler::HandleDebugSendChatMsgCommand(), ChatHandler::HandleDebugSendEquipErrorCommand(), ChatHandler::HandleDebugSendOpcodeCommand(), ChatHandler::HandleDebugSendPoiCommand(), ChatHandler::HandleDebugSendQuestFailedMsgCommand(), ChatHandler::HandleDebugSendQuestInvalidMsgCommand(), ChatHandler::HandleDebugSendQuestPartyMsgCommand(), ChatHandler::HandleDebugSendSellErrorCommand(), ChatHandler::HandleDebugSendWorldState(), ChatHandler::HandleDebugSetItemValueCommand(), ChatHandler::HandleDebugSpawnsList(), ChatHandler::HandleDebugTaxiCommand(), ChatHandler::HandleDebugTransports(), ChatHandler::HandleDebugUpdateWorldStateCommand(), HandleDelFriendOpcode(), HandleDelIgnoreOpcode(), ChatHandler::HandleDeMorphCommand(), ChatHandler::HandleDieCommand(), ChatHandler::HandleDismountCommand(), HandleDuelAcceptedOpcode(), HandleDuelCancelledOpcode(), HandleEmoteOpcode(), ChatHandler::HandleExploreCheatCommand(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectDeleteCommand(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), HandleGameobjectReportUse(), ChatHandler::HandleGameObjectRespawnCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGetDistanceCommand(), ChatHandler::HandleGetLosCommand(), ChatHandler::HandleGMChatCommand(), ChatHandler::HandleGMCommand(), ChatHandler::HandleGMFlyCommand(), ChatHandler::HandleGMListIngameCommand(), ChatHandler::HandleGMMountUpCommand(), HandleGMResponseResolveOpcode(), HandleGMSurveySubmitOpcode(), HandleGMTicketCreateOpcode(), HandleGMTicketDeleteTicketOpcode(), HandleGMTicketGetTicketOpcode(), HandleGMTicketUpdateTextOpcode(), ChatHandler::HandleGMVisibleCommand(), ChatHandler::HandleGoCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoGraveyardCommand(), ChatHandler::HandleGoGridCommand(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleGoObjectCommand(), HandleGossipHelloOpcode(), HandleGossipSelectOptionOpcode(), ChatHandler::HandleGoTaxinodeCommand(), ChatHandler::HandleGoTriggerCommand(), ChatHandler::HandleGoWarpCommand(), ChatHandler::HandleGoXYCommand(), ChatHandler::HandleGoXYZCommand(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleGridsLoadedCount(), HandleGroupAcceptOpcode(), HandleGroupAssistantLeaderOpcode(), HandleGroupChangeSubGroupOpcode(), HandleGroupDeclineOpcode(), HandleGroupDisbandOpcode(), ChatHandler::HandleGroupgoCommand(), HandleGroupInviteOpcode(), HandleGroupRaidConvertOpcode(), HandleGroupSetLeaderOpcode(), HandleGroupSwapSubGroupOpcode(), HandleGroupUninviteGuidOpcode(), HandleGroupUninviteOpcode(), HandleGuildAcceptOpcode(), HandleGuildAddRankOpcode(), HandleGuildBankBuyTab(), HandleGuildBankDepositMoney(), HandleGuildBankerActivate(), HandleGuildBankLogQuery(), HandleGuildBankMoneyWithdrawn(), HandleGuildBankQueryTab(), HandleGuildBankSwapItems(), HandleGuildBankUpdateTab(), HandleGuildBankWithdrawMoney(), HandleGuildChangeInfoTextOpcode(), HandleGuildCreateOpcode(), HandleGuildDeclineOpcode(), HandleGuildDelRankOpcode(), HandleGuildDemoteOpcode(), HandleGuildDisbandOpcode(), HandleGuildEventLogQueryOpcode(), HandleGuildInfoOpcode(), HandleGuildInviteOpcode(), HandleGuildLeaderOpcode(), HandleGuildMOTDOpcode(), HandleGuildPermissions(), HandleGuildPromoteOpcode(), HandleGuildRankOpcode(), HandleGuildRemoveOpcode(), HandleGuildSetOfficerNoteOpcode(), HandleGuildSetPublicNoteOpcode(), ChatHandler::HandleHonorAddKillCommand(), HandleInitiateTradeOpcode(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceSaveDataCommand(), ChatHandler::HandleInstanceUnbindCommand(), ChatHandler::HandleItemMoveCommand(), ChatHandler::HandleKickPlayerCommand(), ChatHandler::HandleLearnAllCraftsCommand(), ChatHandler::HandleLearnAllGMCommand(), ChatHandler::HandleLearnAllLangCommand(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleLevelUpCommand(), HandleLfgJoinOpcode(), HandleLfgLeaveOpcode(), HandleLfgPartyLockInfoRequestOpcode(), HandleLfgPlayerLockInfoRequestOpcode(), HandleLfgProposalResultOpcode(), HandleLfgSetCommentOpcode(), HandleLfgSetRolesOpcode(), HandleLfgTeleportOpcode(), HandleLfrJoinOpcode(), HandleLfrLeaveOpcode(), ChatHandler::HandleLinkAddCommand(), ChatHandler::HandleLinkCheckCommand(), ChatHandler::HandleLinkEditCommand(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleLinkRemoveCommand(), ChatHandler::HandleLinkToggleCommand(), ChatHandler::HandleListAreaTriggerCommand(), ChatHandler::HandleListCreatureCommand(), HandleListInventoryOpcode(), ChatHandler::HandleListObjectCommand(), HandleLogoutCancelOpcode(), HandleLogoutRequestOpcode(), ChatHandler::HandleLookupItemCommand(), HandleLootMethodOpcode(), HandleLootOpcode(), HandleLootRoll(), ChatHandler::HandleMailBoxCommand(), HandleMessagechatOpcode(), HandleMinimapPingOpcode(), ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapStatsCommand(), ChatHandler::HandleMmapTestArea(), ChatHandler::HandleMmapTestHeight(), ChatHandler::HandleModifyMorphCommand(), ChatHandler::HandleModifyPhaseCommand(), ChatHandler::HandleModifyStandStateCommand(), HandleMountSpecialAnimOpcode(), HandleMoveTeleportAckOpcode(), HandleMoveWorldportAckOpcode(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), HandleNextCinematicCamera(), ChatHandler::HandleNpcAddCommand(), ChatHandler::HandleNpcAddVendorItemCommand(), ChatHandler::HandleNpcDeleteCommand(), ChatHandler::HandleNpcFollowCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSayCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcTameCommand(), ChatHandler::HandleNpcTempSpawn(), ChatHandler::HandleNpcTextEmoteCommand(), ChatHandler::HandleNpcUnFollowCommand(), ChatHandler::HandleNpcWhisperCommand(), ChatHandler::HandleNpcYellCommand(), HandleOfferPetitionOpcode(), HandleOptOutOfLootOpcode(), HandlePartyAssignmentOpcode(), HandlePetCancelAuraOpcode(), HandlePetitionBuyOpcode(), HandlePetitionSignOpcode(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), HandleQueryGuildBankTabText(), HandleQuestgiverAcceptQuestOpcode(), HandleQuestgiverHelloOpcode(), HandleQuestLogSwapQuest(), HandleRaidReadyCheckFinishedOpcode(), HandleRaidReadyCheckOpcode(), HandleRaidTargetUpdateOpcode(), HandleRandomRollOpcode(), HandleReclaimCorpseOpcode(), HandleRepairItemOpcode(), HandleRepopRequestOpcode(), ChatHandler::HandleResetSpecsCommand(), ChatHandler::HandleResetSpellsCommand(), ChatHandler::HandleResetTalentsCommand(), ChatHandler::HandleResetTaxiNodesCommand(), ChatHandler::HandleRespawnCommand(), HandleResurrectResponseOpcode(), ChatHandler::HandleSaveCommand(), HandleSaveGuildEmblemOpcode(), ChatHandler::HandleSD2HelpCommand(), ChatHandler::HandleSD2ScriptCommand(), HandleSellItemOpcode(), ChatHandler::HandleSendItemsCommand(), ChatHandler::HandleSendItemsHelper(), HandleSendMail(), ChatHandler::HandleSendMailCommand(), ChatHandler::HandleSendMassItemsCommand(), ChatHandler::HandleSendMassMailCommand(), ChatHandler::HandleSendMassMoneyCommand(), ChatHandler::HandleSendMoneyCommand(), HandleSetActionBarTogglesOpcode(), HandleSetActionButtonOpcode(), HandleSetAllowLowLevelRaidOpcode(), HandleSetAmmoOpcode(), HandleSetFactionAtWarOpcode(), HandleSetGuildBankTabText(), HandleSetSavedInstanceExtend(), HandleSetSheathedOpcode(), HandleSetTitleOpcode(), ChatHandler::HandleSetViewCommand(), HandleSetWatchedFactionOpcode(), ChatHandler::HandleShowTemporarySpawnList(), HandleSpiritHealerActivateOpcode(), ChatHandler::HandleStableCommand(), HandleStablePet(), ChatHandler::HandleStartCommand(), HandleTabardVendorActivateOpcode(), HandleTalentWipeConfirmOpcode(), ChatHandler::HandleTaxiCheatCommand(), HandleTaxiQueryAvailableNodes(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleTeleCommand(), HandleTextEmoteOpcode(), ChatHandler::HandleTicketGoCommand(), ChatHandler::HandleTicketsCommand(), HandleTogglePvP(), HandleTotemDestroyed(), HandleTrainerBuySpellOpcode(), ChatHandler::HandleTriggerActiveCommand(), ChatHandler::HandleTriggerCommand(), ChatHandler::HandleTriggerNearCommand(), HandleUnlearnSkillOpcode(), HandleUpdateMissileTrajectory(), ChatHandler::HandleVariablePrint(), ChatHandler::HandleWhisperRestrictionCommand(), ChatHandler::HandleWhispersCommand(), HandleWhoisOpcode(), HandleWhoOpcode(), HandleWorldTeleportOpcode(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), HandleZoneUpdateOpcode(), ChatHandler::LogCommand(), MapSessionFilterHelper(), ArenaTeam::MassInviteToEvent(), Guild::MassInviteToEvent(), NamreebAnticheat::SessionAnticheat::Movement(), ChatHandler::needReportToTarget(), NamreebAnticheat::SessionAnticheat::NewPlayer(), Warden::ReadScanResults(), Guild::Roster(), SendBindPoint(), ChatHandler::SendGlobalSysMessage(), SendGroupInvite(), SendKnockBack(), SendLearnNewTaxiNode(), SendLfgPlayerReward(), SendListInventory(), SendPacket(), SendPetitionShowList(), SendStablePet(), SendTaxiMenu(), SendTaxiStatus(), SendTrainerList(), GMTicket::SetAssignee(), ChatHandler::ShowAccountListHelper(), ChatHandler::ShowTriggerListHelper(), ChatHandler::ShowTriggerTargetListHelper(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), Warden::Update(), Update(), NamreebAnticheat::SessionAnticheat::VerifyTracking(), and GMTicketMgr::Whisper().
GetPlayerName()
char const * WorldSession::GetPlayerName () const
Get the player name.
Definition at line 180 of file WorldSession.cpp.
References WorldObject::GetName(), and GetPlayer().
Referenced by GMTicketMgr::CanClose(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), GMTicketMgr::Close(), GMTicketMgr::Comment(), ArenaTeam::Disband(), GMTicketMgr::Escalate(), ChatHandler::HandleAddCharacterNoteCommand(), HandleAuctionSellItem(), ChatHandler::HandleBanHelper(), ChatHandler::HandleDebugSendChatMsgCommand(), HandleMailTakeItem(), ChatHandler::HandleMuteCommand(), HandleSendMail(), ChatHandler::HandleUnBanHelper(), ChatHandler::HandleWarnCharacterCommand(), GMTicket::SetAssignee(), GMTicketMgr::Sort(), and NamreebAnticheat::SessionAnticheat::VerifyTracking().
GetRecruitingFriendId()
uint32 WorldSession::GetRecruitingFriendId () const inline
Definition at line 482 of file WorldSession.h.
References m_recruitingFriendId.
Referenced by Spell::CheckCast(), Spell::EffectSummonRafFriend(), Player::GetsRecruitAFriendBonus(), HandleAcceptLevelGrant(), and HandleGrantLevel().
GetRemoteAddress()
const std::string WorldSession::GetRemoteAddress () const inline
Definition at line 305 of file WorldSession.h.
References m_Socket.
Referenced by HandleChangePlayerNameOpcodeCallBack(), HandleCharCreateOpcode(), HandleCharCustomizeOpcode(), HandleCharDeleteOpcode(), Warden::HandlePacket(), HandlePlayerLogin(), HandlePlayerReconnect(), LogoutPlayer(), ProcessByteBufferException(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), Warden::SendModuleToClient(), NamreebAnticheat::SessionAnticheat::Update(), Warden::Update(), WardenWin::Update(), WardenWin::ValidateEndScene(), NamreebAnticheat::SessionAnticheat::VerifyTracking(), Warden::Warden(), and NamreebAnticheat::SessionAnticheat::~SessionAnticheat().
GetSecurity()
AccountTypes WorldSession::GetSecurity () const inline
Definition at line 290 of file WorldSession.h.
References _security.
Referenced by PlayerbotAI::_HandleCommandGM(), PlayerbotAI::_HandleCommandHelp(), World::AddSession_(), ScriptedInstance::BanPlayersIfNoGm(), SocialMgr::BroadcastToFriendListers(), GMTicketMgr::CanClose(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), CheckChatChannelNameAndPassword(), CheckChatMessage(), NamreebAnticheat::Movement::CheckTeleport(), GMTicketMgr::Close(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), GMTicketMgr::Escalate(), ChatHandler::GetAccessLevel(), SocialMgr::GetFriendInfo(), GMTicket::GMTicket(), HandleAcceptTradeOpcode(), HandleAddFriendOpcodeCallBack(), HandleAuctionSellItem(), HandleCharCreateOpcode(), HandleCharCustomizeOpcode(), HandleCharRenameOpcode(), PlayerbotAI::HandleCommand(), ChatHandler::HandleGMListIngameCommand(), HandleGuildBankDepositMoney(), HandleLogoutRequestOpcode(), HandleMailTakeItem(), HandleMessagechatOpcode(), WorldSocket::HandlePing(), HandleSendMail(), HandleWhoisOpcode(), HandleWhoOpcode(), HandleWorldTeleportOpcode(), ChatHandler::HasLowerSecurityAccount(), Player::InitPrimaryProfessions(), Player::isAcceptTickets(), Player::isGMChat(), Player::IsVisibleGloballyFor(), Player::IsVisibleInGridForPlayer(), Channel::Join(), Channel::KickOrBan(), Channel::Leave(), ChatHandler::ModifyMountCommandHelper(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), moveItems(), Player::OnGossipSelect(), ChatHandler::ParseCommands(), NamreebAnticheat::SessionAnticheat::RecordCheat(), GMTicket::Recycle(), Player::removeSpell(), AchievementMgr::ResetAchievementCriteria(), Channel::Say(), AuctionHouseMgr::SendAuctionWonMail(), Channel::SendChannelListResponse(), Channel::SendChannelOwnerResponse(), NamreebAnticheat::SessionAnticheat::SendPlayerInfo(), WorldState::SetExpansion(), Channel::SetModeFlags(), Channel::SetOwner(), Channel::SetPassword(), AchievementMgr::StartTimedAchievementCriteria(), Channel::ToggleAnnouncements(), Channel::ToggleModeration(), Channel::UnBan(), AchievementMgr::UpdateAchievementCriteria(), NamreebAnticheat::Movement::VerifyMovementFlags(), and GMTicketMgr::Whisper().
GetSessionDbcLocale()
LocaleConstant WorldSession::GetSessionDbcLocale () const inline
Definition at line 462 of file WorldSession.h.
References m_sessionDbcLocale.
Referenced by PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandSpells(), PlayerbotAI::getPetSpellId(), ChatHandler::GetSessionDbcLocale(), PlayerbotAI::getSpellId(), GMTicket::GMTicket(), HandleMailCreateTextItem(), HandleWhoOpcode(), PlayerbotAI::MakeSpellLink(), PlayerbotAI::MakeWeaponSkillLink(), GMTicketMgr::Print(), GMTicketMgr::PrintTicketList(), GMTicket::Recycle(), GMTicketMgr::TicketChatAlert(), and Player::UpdateLocalChannels().
GetSessionDbLocaleIndex()
int WorldSession::GetSessionDbLocaleIndex () const inline
Definition at line 463 of file WorldSession.h.
References m_sessionDbLocaleIndex.
Referenced by GossipMenu::AddMenuItem(), BuildListAuctionItems(), AuctionEntry::CompareAuctionEntry(), AchievementMgr::CompletedAchievement(), Guild::Create(), PlayerbotAI::CreatureLocalization(), PlayerbotAI::GameObjectLocalization(), GetMangosString(), ChatHandler::GetSessionDbLocaleIndex(), HandleCreatureQueryOpcode(), HandleGameObjectQueryOpcode(), HandleItemNameQueryOpcode(), HandleItemQuerySingleOpcode(), HandleNpcTextQueryOpcode(), HandlePageTextQueryOpcode(), HandleQuestQueryOpcode(), PlayerbotAI::ItemLocalization(), MaNGOS::LocalizedPacketDo< Builder >::operator()(), MaNGOS::LocalizedPacketListDo< Builder >::operator()(), Player::PrepareGossipMenu(), Loot::PrintLootList(), PlayerbotAI::QuestLocalization(), Player::QueueOrAddResurrectRequest(), PlayerMenu::SendGossipMenu(), SendPetNameQuery(), PlayerMenu::SendPointOfInterest(), Player::SendPreparedQuest(), BattlefieldWG::SendPromotionWhisper(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverQuestList(), PlayerMenu::SendQuestGiverRequestItems(), BattleGround::SendRewardMarkByMail(), SendTrainerList(), and Battlefield::SendZoneWarning().
GetState()
WorldSessionState WorldSession::GetState () const inline
Definition at line 259 of file WorldSession.h.
References m_sessionState.
Referenced by WorldSocket::HandleAuthSession().
GetTutorialInt()
uint32 WorldSession::GetTutorialInt (uint32 intId) inline
Definition at line 405 of file WorldSession.h.
References m_Tutorials.
Referenced by HandleTutorialFlagOpcode().
Handle_Deprecated()
void WorldSession::Handle_Deprecated (WorldPacket & recvPacket)
Definition at line 946 of file WorldSession.cpp.
References WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and sLog.
Handle_EarlyProccess()
void WorldSession::Handle_EarlyProccess (WorldPacket & recvPacket)
Definition at line 932 of file WorldSession.cpp.
References WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and sLog.
Handle_NULL()
void WorldSession::Handle_NULL (WorldPacket & recvPacket)
Definition at line 925 of file WorldSession.cpp.
References DEBUG_LOG, WorldPacket::GetOpcode(), and WorldPacket::GetOpcodeName().
Handle_ServerSide()
void WorldSession::Handle_ServerSide (WorldPacket & recvPacket)
Definition at line 939 of file WorldSession.cpp.
References WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and sLog.
HandleAcceptLevelGrant()
void WorldSession::HandleAcceptLevelGrant (WorldPacket & recv_data)
Definition at line 75 of file RafHandler.cpp.
References _player, DEBUG_LOG, GetAccountId(), Player::GetGrantableLevels(), Unit::GetLevel(), WorldObject::GetMap(), Map::GetPlayer(), GetRecruitingFriendId(), Player::GetSession(), Player::GiveLevel(), IsARecruiter(), ObjectGuid::ReadAsPacked(), and Player::SetGrantableLevels().
HandleAcceptTradeOpcode()
void WorldSession::HandleAcceptTradeOpcode (WorldPacket & recvPacket)
Definition at line 244 of file TradeHandler.cpp.
References _player, Database::BeginTransaction(), Player::CanStoreItems(), CharacterDatabase, Spell::CheckCast(), clearAcceptTradeMode(), Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, EQUIP_ERR_NOT_ENOUGH_MONEY, EQUIP_ERR_OK, GetAccountId(), TradeData::GetItem(), TradeData::GetMoney(), Player::GetMoney(), WorldObject::GetName(), Object::GetObjectGuid(), GetSecurity(), Player::GetSession(), TradeData::GetSpell(), TradeData::GetSpellCastItem(), Player::GetTrader(), TradeData::HasSpellCastItem(), TradeData::IsAccepted(), TradeStatusInfo::IsTargetResult, WorldObject::IsWithinDistInMap(), ITEM_FIELD_GIFTCREATOR, TradeStatusInfo::ItemLimitCategoryId, SQLStorage::LookupEntry(), Spell::m_targets, Player::m_trade, Player::ModifyMoney(), Player::MoveItemFromInventory(), moveItems(), ByteBuffer::read_skip(), TradeStatusInfo::Result, Player::SaveInventoryAndGoldToDB(), SEC_PLAYER, Spell::SendCastResult(), SendTradeStatus(), TradeData::SetAccepted(), setAcceptTradeMode(), Spell::SetCastItem(), TradeData::SetSpell(), SpellCastTargets::setTradeItemTarget(), sLog, SPELL_CAST_OK, Spell::SpellStart(), sSpellTemplate, TradeStatusInfo::Status, sWorld, TRADE_DISTANCE, TRADE_SLOT_NONTRADED, TRADE_SLOT_TRADED_COUNT, TRADE_STATUS_CLOSE_WINDOW, TRADE_STATUS_TARGET_TO_FAR, TRADE_STATUS_TRADE_ACCEPT, TRADE_STATUS_TRADE_CANCELED, TRADE_STATUS_TRADE_COMPLETE, and TRIGGERED_OLD_TRIGGERED.
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleActivateTaxiExpressOpcode()
void WorldSession::HandleActivateTaxiExpressOpcode (WorldPacket & recvPacket)
Definition at line 141 of file TaxiHandler.cpp.
References _player, Player::ActivateTaxiPathTo(), DEBUG_LOG, ERR_TAXINOTVISITED, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), Player::isTaxiCheater(), PlayerTaxi::IsTaximaskNodeKnown(), Player::m_taxi, ByteBuffer::rpos(), SendActivateTaxiReply(), UNIT_NPC_FLAG_FLIGHTMASTER, and ByteBuffer::wpos().
HandleActivateTaxiOpcode()
void WorldSession::HandleActivateTaxiOpcode (WorldPacket & recvPacket)
Definition at line 196 of file TaxiHandler.cpp.
References _player, Player::ActivateTaxiPathTo(), DEBUG_LOG, ERR_TAXINOTVISITED, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), Player::isTaxiCheater(), PlayerTaxi::IsTaximaskNodeKnown(), Player::m_taxi, SendActivateTaxiReply(), and UNIT_NPC_FLAG_FLIGHTMASTER.
HandleAddFriendOpcode()
void WorldSession::HandleAddFriendOpcode (WorldPacket & recvPacket)
Definition at line 445 of file MiscHandler.cpp.
References Database::AsyncPQuery(), CharacterDatabase, DEBUG_LOG, Database::escape_string(), GetAccountId(), GetMangosString(), GetPlayer(), HandleAddFriendOpcodeCallBack(), LANG_FRIEND_IGNORE_UNKNOWN, and normalizePlayerName().
HandleAddFriendOpcodeCallBack()
void WorldSession::HandleAddFriendOpcodeCallBack (QueryResult * result, uint32 accountId, std::string friendNote) static
Definition at line 467 of file MiscHandler.cpp.
References PlayerSocial::AddToSocialList(), CONFIG_BOOL_ALLOW_TWO_SIDE_ADD_FRIEND, DEBUG_LOG, ObjectAccessor::FindPlayer(), FRIEND_ADDED_OFFLINE, FRIEND_ADDED_ONLINE, FRIEND_ALREADY, FRIEND_ENEMY, FRIEND_LIST_FULL, FRIEND_NOT_FOUND, FRIEND_SELF, WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), GetSecurity(), Player::GetSocial(), Player::GetTeam(), PlayerSocial::HasFriend(), HIGHGUID_PLAYER, Object::IsInWorld(), Player::IsVisibleGloballyFor(), SEC_MODERATOR, PlayerSocial::SetFriendNote(), sSocialMgr, sWorld, and Player::TeamForRace().
Referenced by HandleAddFriendOpcode().
HandleAddIgnoreOpcode()
void WorldSession::HandleAddIgnoreOpcode (WorldPacket & recvPacket)
Definition at line 533 of file MiscHandler.cpp.
References Database::AsyncPQuery(), CharacterDatabase, DEBUG_LOG, Database::escape_string(), GetAccountId(), GetMangosString(), GetPlayer(), HandleAddIgnoreOpcodeCallBack(), LANG_FRIEND_IGNORE_UNKNOWN, and normalizePlayerName().
HandleAddIgnoreOpcodeCallBack()
void WorldSession::HandleAddIgnoreOpcodeCallBack (QueryResult * result, uint32 accountId) static
Definition at line 552 of file MiscHandler.cpp.
References PlayerSocial::AddToSocialList(), DEBUG_LOG, FRIEND_IGNORE_ADDED, FRIEND_IGNORE_ALREADY, FRIEND_IGNORE_FULL, FRIEND_IGNORE_NOT_FOUND, FRIEND_IGNORE_SELF, Object::GetObjectGuid(), GetPlayer(), Player::GetSocial(), PlayerSocial::HasIgnore(), HIGHGUID_PLAYER, sSocialMgr, and sWorld.
Referenced by HandleAddIgnoreOpcode().
HandleAlterAppearanceOpcode()
void WorldSession::HandleAlterAppearanceOpcode (WorldPacket & recv_data)
Definition at line 1345 of file CharacterHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER, ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP, DEBUG_LOG, BarberShopStyleEntry::gender, Player::GetAchievementMgr(), Player::GetBarberShopCost(), Unit::getGender(), Player::GetMoney(), Unit::getRace(), BarberShopStyleEntry::hair_id, Player::ModifyMoney(), PLAYER_BYTES, PLAYER_BYTES_2, BarberShopStyleEntry::race, RACE_TAUREN, sBarberShopStyleStore, SendPacket(), Object::SetByteValue(), Unit::SetStandState(), SMSG_BARBER_SHOP_RESULT, BarberShopStyleEntry::type, and AchievementMgr::UpdateAchievementCriteria().
HandleAreaSpiritHealerQueryOpcode()
void WorldSession::HandleAreaSpiritHealerQueryOpcode (WorldPacket & recv_data)
Definition at line 648 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, Player::GetBattleGround(), Map::GetCreature(), WorldObject::GetMap(), GetPlayer(), Unit::isSpiritService(), and Creature::SendAreaSpiritHealerQueryOpcode().
HandleAreaSpiritHealerQueueOpcode()
void WorldSession::HandleAreaSpiritHealerQueueOpcode (WorldPacket & recv_data)
Definition at line 670 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, Player::GetBattleGround(), Map::GetCreature(), WorldObject::GetMap(), GetPlayer(), Unit::isSpiritService(), and sScriptDevAIMgr.
HandleAreaTriggerOpcode()
void WorldSession::HandleAreaTriggerOpcode (WorldPacket & recvPacket)
Definition at line 699 of file MiscHandler.cpp.
References Player::AreaExploredOrEventHappens(), Player::CheckAndRevivePlayerOnDungeonEnter(), CONDITION_FROM_AREATRIGGER_TELEPORT, AreaTrigger::conditionId, DEBUG_LOG, Player::GetBattleGround(), Player::GetCachedZoneId(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetQuestStatus(), Player::GetRestType(), Player::GetSession(), Player::IsActiveQuest(), Unit::IsAlive(), Player::isDebuggingAreaTriggers(), MapEntry::IsDungeon(), IsPointInAreaTriggerZone(), Unit::IsTaxiFlying(), LANG_DEBUG_AREATRIGGER_REACHED, ChatHandler::PSendSysMessage(), QUEST_STATUS_INCOMPLETE, REST_TYPE_IN_CITY, REST_TYPE_IN_TAVERN, sAreaTriggerStore, Player::SetRestType(), sMapStore, sObjectMgr, sOutdoorPvPMgr, sScriptDevAIMgr, AreaTrigger::target_mapId, AreaTrigger::target_Orientation, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, TELE_TO_NOT_LEAVE_TRANSPORT, and Player::TeleportTo().
Referenced by PlayerbotMgr::HandleMasterIncomingPacket().
HandleArenaTeamAcceptOpcode()
void WorldSession::HandleArenaTeamAcceptOpcode (WorldPacket & recv_data)
Definition at line 159 of file ArenaTeamHandler.cpp.
References _player, ArenaTeam::AddMember(), ArenaTeam::BroadcastEvent(), CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, DEBUG_LOG, ERR_ALREADY_IN_ARENA_TEAM, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_INTERNAL, ERR_ARENA_TEAM_JOIN_SS, ERR_ARENA_TEAM_NOT_ALLIED, Player::GetArenaTeamId(), Player::GetArenaTeamIdInvited(), ArenaTeam::GetCaptainGuid(), ArenaTeam::GetName(), WorldObject::GetName(), Object::GetObjectGuid(), ArenaTeam::GetSlot(), Player::GetTeam(), SendArenaTeamCommandResult(), sObjectMgr, and sWorld.
HandleArenaTeamDeclineOpcode()
void WorldSession::HandleArenaTeamDeclineOpcode (WorldPacket & recv_data)
Definition at line 193 of file ArenaTeamHandler.cpp.
References _player, DEBUG_LOG, and Player::SetArenaTeamIdInvited().
HandleArenaTeamDisbandOpcode()
void WorldSession::HandleArenaTeamDisbandOpcode (WorldPacket & recv_data)
Definition at line 238 of file ArenaTeamHandler.cpp.
References _player, DEBUG_LOG, Object::GetObjectGuid(), and sObjectMgr.
HandleArenaTeamInviteOpcode()
void WorldSession::HandleArenaTeamInviteOpcode (WorldPacket & recv_data)
Definition at line 81 of file ArenaTeamHandler.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, ERR_ALREADY_IN_ARENA_TEAM_S, ERR_ALREADY_INVITED_TO_ARENA_TEAM_S, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_INVITE_SS, ERR_ARENA_TEAM_NOT_ALLIED, ERR_ARENA_TEAM_PLAYER_NOT_FOUND_S, ERR_ARENA_TEAM_PLAYER_NOT_IN_TEAM, ERR_ARENA_TEAM_TARGET_TOO_LOW_S, ERR_ARENA_TEAM_TOO_MANY_MEMBERS_S, ObjectAccessor::FindPlayerByName(), Player::GetArenaTeamId(), Player::GetArenaTeamIdInvited(), ArenaTeam::GetId(), Unit::GetLevel(), ArenaTeam::GetMaxMembersSize(), ArenaTeam::GetMembersSize(), ArenaTeam::GetName(), WorldObject::GetName(), GetPlayer(), Player::GetSession(), ArenaTeam::GetSlot(), Player::GetSocial(), Player::GetTeam(), PlayerSocial::HasIgnore(), normalizePlayerName(), SendArenaTeamCommandResult(), SendPacket(), Player::SetArenaTeamIdInvited(), SMSG_ARENA_TEAM_INVITE, sObjectMgr, and sWorld.
HandleArenaTeamLeaderOpcode()
void WorldSession::HandleArenaTeamLeaderOpcode (WorldPacket & recv_data)
Definition at line 304 of file ArenaTeamHandler.cpp.
References _player, ArenaTeam::BroadcastEvent(), DEBUG_LOG, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_LEADER_CHANGED_SSS, ERR_ARENA_TEAM_PERMISSIONS, ERR_ARENA_TEAM_PLAYER_NOT_FOUND_S, ArenaTeam::GetCaptainGuid(), ArenaTeam::GetMember(), ArenaTeam::GetName(), WorldObject::GetName(), Object::GetObjectGuid(), ArenaTeamMember::guid, normalizePlayerName(), SendArenaTeamCommandResult(), ArenaTeam::SetCaptain(), and sObjectMgr.
HandleArenaTeamLeaveOpcode()
void WorldSession::HandleArenaTeamLeaveOpcode (WorldPacket & recv_data)
Definition at line 200 of file ArenaTeamHandler.cpp.
References _player, ArenaTeam::BroadcastEvent(), DEBUG_LOG, ArenaTeam::DelMember(), ArenaTeam::Disband(), ERR_ARENA_TEAM_LEADER_LEAVE_S, ERR_ARENA_TEAM_LEAVE_SS, ERR_ARENA_TEAM_QUIT_S, ArenaTeam::GetCaptainGuid(), ArenaTeam::GetMembersSize(), ArenaTeam::GetName(), WorldObject::GetName(), Object::GetObjectGuid(), Player::InArena(), Player::InBattleGroundQueue(), SendArenaTeamCommandResult(), and sObjectMgr.
HandleArenaTeamQueryOpcode()
void WorldSession::HandleArenaTeamQueryOpcode (WorldPacket & recv_data)
Definition at line 56 of file ArenaTeamHandler.cpp.
References DEBUG_LOG, and sObjectMgr.
HandleArenaTeamRemoveOpcode()
void WorldSession::HandleArenaTeamRemoveOpcode (WorldPacket & recv_data)
Definition at line 258 of file ArenaTeamHandler.cpp.
References _player, ArenaTeam::BroadcastEvent(), DEBUG_LOG, ArenaTeam::DelMember(), ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_LEADER_LEAVE_S, ERR_ARENA_TEAM_PERMISSIONS, ERR_ARENA_TEAM_PLAYER_NOT_FOUND_S, ERR_ARENA_TEAM_QUIT_S, ERR_ARENA_TEAM_REMOVE_SSS, ObjectAccessor::FindPlayer(), ArenaTeam::GetCaptainGuid(), ArenaTeam::GetMember(), ArenaTeam::GetName(), WorldObject::GetName(), Object::GetObjectGuid(), ArenaTeamMember::guid, Player::InArena(), Player::InBattleGroundQueue(), normalizePlayerName(), SendArenaTeamCommandResult(), and sObjectMgr.
HandleArenaTeamRosterOpcode()
void WorldSession::HandleArenaTeamRosterOpcode (WorldPacket & recv_data)
Definition at line 70 of file ArenaTeamHandler.cpp.
References DEBUG_LOG, and sObjectMgr.
HandleAttackStopOpcode()
void WorldSession::HandleAttackStopOpcode (WorldPacket & recvPacket)
Definition at line 59 of file CombatHandler.cpp.
References Unit::AttackStop(), and GetPlayer().
HandleAttackSwingOpcode()
void WorldSession::HandleAttackSwingOpcode (WorldPacket & recvPacket)
Definition at line 26 of file CombatHandler.cpp.
References _player, Unit::Attack(), Unit::CanAttackNow(), DEBUG_FILTER_LOG, WorldObject::GetMap(), Player::GetMover(), ObjectGuid::GetString(), Map::GetUnit(), ObjectGuid::IsUnit(), LOG_FILTER_COMBAT, Unit::SendMeleeAttackStop(), and sLog.
HandleAuctionHelloOpcode()
void WorldSession::HandleAuctionHelloOpcode (WorldPacket & recvPacket)
Definition at line 36 of file AuctionHouseHandler.cpp.
References DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), SendAuctionHello(), and UNIT_NPC_FLAG_AUCTIONEER.
HandleAuctionListBidderItems()
void WorldSession::HandleAuctionListBidderItems (WorldPacket & recv_data)
Definition at line 518 of file AuctionHouseHandler.cpp.
References AuctionEntry::BuildAuctionInfo(), AuctionHouseObject::BuildListBidderItems(), DEBUG_LOG, AuctionHouseObject::GetAuction(), GetCheckedAuctionHouseForAuctioneer(), GetPlayer(), ByteBuffer::put(), sAuctionMgr, SendPacket(), ByteBuffer::size(), sLog, and SMSG_AUCTION_BIDDER_LIST_RESULT.
HandleAuctionListItems()
void WorldSession::HandleAuctionListItems (WorldPacket & recv_data)
Definition at line 599 of file AuctionHouseHandler.cpp.
References AUCTION_SORT_REVERSED, BuildListAuctionItems(), DEBUG_LOG, AuctionHouseObject::GetAuctions(), GetCheckedAuctionHouseForAuctioneer(), GetPlayer(), MAX_AUCTION_SORT, ByteBuffer::put(), sAuctionMgr, SendPacket(), SMSG_AUCTION_LIST_RESULT, Utf8toWStr(), and wstrToLower().
HandleAuctionListOwnerItems()
void WorldSession::HandleAuctionListOwnerItems (WorldPacket & recv_data)
Definition at line 568 of file AuctionHouseHandler.cpp.
References _player, AuctionHouseObject::BuildListOwnerItems(), DEBUG_LOG, GetCheckedAuctionHouseForAuctioneer(), ByteBuffer::put(), sAuctionMgr, SendPacket(), and SMSG_AUCTION_OWNER_LIST_RESULT.
HandleAuctionListPendingSales()
void WorldSession::HandleAuctionListPendingSales (WorldPacket & recv_data)
Definition at line 677 of file AuctionHouseHandler.cpp.
References _player, DEBUG_LOG, GetCheckedAuctionHouseForAuctioneer(), MAX_AUCTION_HOUSE_TYPE, ByteBuffer::put(), sAuctionMgr, SendPacket(), and SMSG_AUCTION_LIST_PENDING_SALES.
HandleAuctionPlaceBid()
void WorldSession::HandleAuctionPlaceBid (WorldPacket & recv_data)
Definition at line 372 of file AuctionHouseHandler.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID, AUCTION_BID_PLACED, AUCTION_ERR_BID_INCREMENT, AUCTION_ERR_BID_OWN, AUCTION_ERR_HIGHER_BID, AUCTION_OK, AuctionEntry::buyout, DEBUG_LOG, GetAccountId(), Player::GetAchievementMgr(), AuctionHouseObject::GetAuction(), AuctionEntry::GetAuctionOutBid(), GetCheckedAuctionHouseForAuctioneer(), Object::GetGUIDLow(), Player::GetMoney(), GetPlayer(), Player::GetSession(), HIGHGUID_PLAYER, AuctionEntry::owner, sAuctionMgr, SendAuctionCommandResult(), sObjectMgr, AchievementMgr::UpdateAchievementCriteria(), and AuctionEntry::UpdateBid().
HandleAuctionRemoveItem()
void WorldSession::HandleAuctionRemoveItem (WorldPacket & recv_data)
Definition at line 450 of file AuctionHouseHandler.cpp.
References MailDraft::AddItem(), AUCTION_CANCELED, AUCTION_ERR_DATABASE, AUCTION_ERR_INVENTORY, AUCTION_OK, AUCTION_REMOVED, Database::BeginTransaction(), AuctionEntry::bid, AuctionEntry::bidder, CharacterDatabase, Database::CommitTransaction(), DEBUG_LOG, AuctionEntry::DeleteFromDB(), EQUIP_ERR_ITEM_NOT_FOUND, AuctionHouseObject::GetAuction(), AuctionEntry::GetAuctionCut(), GetCheckedAuctionHouseForAuctioneer(), Object::GetGUIDLow(), Player::GetMoney(), GetPlayer(), AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemGuidLow, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, MAIL_CHECK_MASK_COPIED, Player::ModifyMoney(), AuctionEntry::owner, AuctionHouseObject::RemoveAuction(), sAuctionMgr, Player::SaveInventoryAndGoldToDB(), SendAuctionCancelledToBidderMail(), SendAuctionCommandResult(), MailDraft::SendMailTo(), and sLog.
HandleAuctionSellItem()
void WorldSession::HandleAuctionSellItem (WorldPacket & recv_data)
Definition at line 229 of file AuctionHouseHandler.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION, AuctionHouseObject::AddAuction(), AUCTION_ERR_DATABASE, AUCTION_ERR_INVENTORY, AUCTION_ERR_NOT_ENOUGH_MONEY, AUCTION_OK, AUCTION_STARTED, Item::CanBeTraded(), Item::CloneItem(), CONFIG_BOOL_GM_LOG_TRADE, DEBUG_LOG, Player::DestroyItemCount(), DETAIL_LOG, EQUIP_ERR_CANNOT_TRADE_THAT, EQUIP_ERR_ITEM_NOT_FOUND, ItemPrototype::Flags, GetAccountId(), Player::GetAchievementMgr(), AuctionHouseMgr::GetAuctionDeposit(), GetCheckedAuctionHouseForAuctioneer(), Item::GetCount(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGuidStr(), Player::GetItemByGuid(), Item::GetMaxStackCount(), Player::GetMoney(), GetPlayer(), GetPlayerName(), Item::GetProto(), GetSecurity(), ObjectGuid::GetString(), Object::GetUInt32Value(), Player::HasItemCount(), AuctionHouseEntry::houseId, ITEM_FIELD_DURATION, ITEM_FLAG_CONJURED, MAX_BAG_SIZE, MAX_MONEY_AMOUNT, MIN_AUCTION_TIME, MINUTE, Player::ModifyMoney(), ItemPrototype::Name1, ByteBuffer::rpos(), sAuctionMgr, SEC_PLAYER, SendAuctionCommandResult(), sLog, sWorld, AchievementMgr::UpdateAchievementCriteria(), and ByteBuffer::wpos().
HandleAutoBankItemOpcode()
void WorldSession::HandleAutoBankItemOpcode (WorldPacket & recvPacket)
Definition at line 965 of file ItemHandler.cpp.
References _player, Player::BankItem(), Player::CanBankItem(), DEBUG_LOG, EQUIP_ERR_NONE, EQUIP_ERR_OK, Player::GetItemByPos(), Item::GetPos(), NULL_BAG, NULL_SLOT, Player::RemoveItem(), and Player::SendEquipError().
HandleAutoEquipItemOpcode()
void WorldSession::HandleAutoEquipItemOpcode (WorldPacket & recvPacket)
Definition at line 142 of file ItemHandler.cpp.
References _player, Player::AutoUnequipOffhandIfNeed(), Player::BankItem(), Player::CanBankItem(), Player::CanEquipItem(), Player::CanStoreItem(), Player::CanUnequipItem(), EQUIP_ERR_OK, Player::EquipItem(), Item::GetBagSlot(), Player::GetItemByPos(), Item::GetPos(), Item::GetSlot(), Item::IsBag(), Player::IsBankPos(), Player::IsEquipmentPos(), Player::IsInventoryPos(), NULL_BAG, NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), and Player::StoreItem().
HandleAutoEquipItemSlotOpcode()
void WorldSession::HandleAutoEquipItemSlotOpcode (WorldPacket & recvPacket)
Definition at line 93 of file ItemHandler.cpp.
References _player, Player::GetItemByGuid(), Item::GetPos(), INVENTORY_SLOT_BAG_0, Player::IsEquipmentPos(), and Player::SwapItem().
HandleAutoStoreBagItemOpcode()
void WorldSession::HandleAutoStoreBagItemOpcode (WorldPacket & recvPacket)
Definition at line 843 of file ItemHandler.cpp.
References _player, Player::CanStoreItem(), Player::CanUnequipItem(), EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, EQUIP_ERR_NONE, EQUIP_ERR_OK, Player::GetItemByPos(), Item::GetPos(), Player::IsBagPos(), Player::IsEquipmentPos(), Player::IsValidPos(), NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), and Player::StoreItem().
HandleAutoStoreBankItemOpcode()
void WorldSession::HandleAutoStoreBankItemOpcode (WorldPacket & recvPacket)
Definition at line 997 of file ItemHandler.cpp.
References _player, Player::BankItem(), Player::CanBankItem(), Player::CanStoreItem(), DEBUG_LOG, EQUIP_ERR_OK, Player::GetItemByPos(), Player::IsBankPos(), NULL_BAG, NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), and Player::StoreItem().
HandleAutostoreLootItemOpcode()
void WorldSession::HandleAutostoreLootItemOpcode (WorldPacket & recvPacket)
Definition at line 31 of file LootHandler.cpp.
References _player, DEBUG_LOG, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, Object::GetGuidStr(), Player::GetItemByGuid(), Loot::GetLootGuid(), Loot::GetLootItemInSlot(), LootItem::GetSlotTypeForSharedLoot(), LootItem::isBlocked, ObjectGuid::IsItem(), ITEM_LOOT_CHANGED, LootItem::itemId, MAX_LOOT_SLOT_TYPE, Player::SendEquipError(), Loot::SendItem(), Loot::SendReleaseFor(), sLog, and sLootMgr.
HandleBankerActivateOpcode()
void WorldSession::HandleBankerActivateOpcode (WorldPacket & recvPacket)
Definition at line 69 of file NPCHandler.cpp.
References CheckBanker(), DEBUG_LOG, and SendShowBank().
HandleBattlefieldExitRequest()
void WorldSession::HandleBattlefieldExitRequest (WorldPacket & recv_data)
Definition at line 140 of file BattlefieldHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sOutdoorPvPMgr.
HandleBattlefieldListOpcode()
void WorldSession::HandleBattlefieldListOpcode (WorldPacket & recv_data)
Definition at line 364 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, sBattleGroundMgr, sBattlemasterListStore, SendPacket(), and sLog.
HandleBattlefieldPortOpcode()
void WorldSession::HandleBattlefieldPortOpcode (WorldPacket & recv_data)
Definition at line 390 of file BattleGroundHandler.cpp.
References _player, ARENA_TYPE_NONE, GroupQueueInfo::arenaTeamId, GroupQueueInfo::arenaTeamRating, GroupQueueInfo::arenaType, BattleGroundMgr::BgQueueTypeId(), Player::CanJoinToBattleground(), DEBUG_LOG, ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS, BattleGround::GetArenaType(), Player::GetBattleGround(), GetBattlegroundBracketByLevel(), Player::GetBattleGroundQueueIndex(), Player::GetBGTeam(), PvPDifficultyEntry::GetBracketId(), Object::GetGUIDLow(), Object::GetGuidStr(), BattleGround::GetInstanceId(), Unit::GetLevel(), BattleGround::GetMapId(), BattleGround::GetMaxLevel(), WorldObject::GetName(), Object::GetObjectGuid(), BattleGroundQueue::GetPlayerGroupInfoData(), Player::GetSession(), BattleGround::GetStartTime(), BattleGround::GetTypeId(), GroupQueueInfo::groupTeam, Player::InBattleGround(), Player::InBattleGroundQueue(), Unit::IsAlive(), IsArenaTypeValid(), Player::IsInvitedForBattleGroundQueueType(), GroupQueueInfo::isInvitedToBgInstanceGuid, GroupQueueInfo::isRated, ArenaTeam::MemberLost(), GroupQueueInfo::opponentsTeamRating, Player::RemoveBattleGroundQueueId(), BattleGroundQueue::RemovePlayer(), Player::ResurrectPlayer(), ArenaTeam::SaveToDB(), sBattleGroundMgr, sBattlemasterListStore, SendPacket(), Player::SetBattleGroundEntryPoint(), Player::SetBattleGroundId(), Player::SetBGTeam(), sLog, sObjectMgr, Player::SpawnCorpseBones(), STATUS_IN_PROGRESS, STATUS_NONE, Player::TaxiFlightInterrupt(), and TEAM_NONE.
HandleBattlefieldQueueResponse()
void WorldSession::HandleBattlefieldQueueResponse (WorldPacket & recv_data)
Definition at line 114 of file BattlefieldHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sOutdoorPvPMgr.
HandleBattlefieldStatusOpcode()
void WorldSession::HandleBattlefieldStatusOpcode (WorldPacket & recv_data)
Definition at line 578 of file BattleGroundHandler.cpp.
References _player, BATTLEGROUND_AA, BattleGroundMgr::BgArenaType(), BattleGroundMgr::BgTemplateId(), DEBUG_LOG, BattleGround::GetArenaType(), BattleGroundQueue::GetAverageQueueWaitTime(), Player::GetBattleGround(), GetBattlegroundBracketByLevel(), Player::GetBattleGroundQueueTypeId(), Player::GetBattleGroundTypeId(), Player::GetBGTeam(), PvPDifficultyEntry::GetBracketId(), BattleGround::GetEndTime(), Unit::GetLevel(), BattleGround::GetMapId(), WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), Object::GetObjectGuid(), BattleGroundQueue::GetPlayerGroupInfoData(), BattleGround::GetStartTime(), GroupQueueInfo::isInvitedToBgInstanceGuid, GroupQueueInfo::joinTime, PLAYER_MAX_BATTLEGROUND_QUEUES, GroupQueueInfo::removeInviteTime, sBattleGroundMgr, SendPacket(), STATUS_IN_PROGRESS, STATUS_WAIT_JOIN, STATUS_WAIT_QUEUE, and TEAM_NONE.
HandleBattlefieldWarResponse()
void WorldSession::HandleBattlefieldWarResponse (WorldPacket & recv_data)
Definition at line 127 of file BattlefieldHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sOutdoorPvPMgr.
HandleBattleGroundPlayerPositionsOpcode()
void WorldSession::HandleBattleGroundPlayerPositionsOpcode (WorldPacket & recv_data)
Definition at line 256 of file BattleGroundHandler.cpp.
References _player, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_WS, DEBUG_LOG, Player::GetBattleGround(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Player::GetTeam(), BattleGround::GetTypeId(), BattleGroundWS::IsFlagHeldFor45Seconds(), MSG_BATTLEGROUND_PLAYER_POSITIONS, SendPacket(), sObjectMgr, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
HandleBattlemasterHelloOpcode()
void WorldSession::HandleBattlemasterHelloOpcode (WorldPacket & recv_data)
Definition at line 38 of file BattleGroundHandler.cpp.
References _player, BATTLEGROUND_TYPE_NONE, DEBUG_LOG, Player::GetBGAccessByLevel(), Map::GetCreature(), Object::GetEntry(), Creature::GetInteractionPauseTimer(), WorldObject::GetMap(), Unit::GetMotionMaster(), GetPlayer(), ObjectGuid::GetString(), Unit::isBattleMaster(), LANG_YOUR_BG_LEVEL_REQ_ERROR, MotionMaster::PauseWaypoints(), sBattleGroundMgr, SendBattleGroundList(), and SendNotification().
HandleBattlemasterJoinArena()
void WorldSession::HandleBattlemasterJoinArena (WorldPacket & recv_data)
Definition at line 692 of file BattleGroundHandler.cpp.
References _player, Player::AddBattleGroundQueueId(), BattleGroundQueue::AddGroup(), ARENA_TYPE_2v2, ARENA_TYPE_3v3, ARENA_TYPE_5v5, BATTLEGROUND_AA, BattleGroundMgr::BgQueueTypeId(), Group::CanJoinBattleGroundQueue(), DEBUG_LOG, ERR_GROUP_JOIN_BATTLEGROUND_FAIL, Player::GetArenaTeamId(), BattleGroundQueue::GetAverageQueueWaitTime(), GetBattlegroundBracketByLevel(), Player::GetBattleGroundQueueIndex(), PvPDifficultyEntry::GetBracketId(), Map::GetCreature(), Group::GetFirstMember(), Player::GetGroup(), Object::GetGUIDLow(), Group::GetLeaderGuid(), Unit::GetLevel(), WorldObject::GetMap(), BattleGround::GetMapId(), ArenaTeam::GetMember(), Group::GetMembersCount(), Group::GetMemberSlots(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), ArenaTeam::GetRating(), Player::GetSession(), BattleGround::GetTypeId(), Player::HasFreeBattleGroundQueueId(), Player::InBattleGround(), Unit::isBattleMaster(), GroupReference::next(), ArenaTeamMember::personal_rating, PLAYER_MAX_BATTLEGROUND_QUEUES, sBattleGroundMgr, SendNotInArenaTeamPacket(), SendPacket(), BattleGround::SetRated(), sLog, sObjectMgr, STATUS_WAIT_QUEUE, and TEAM_NONE.
HandleBattlemasterJoinOpcode()
void WorldSession::HandleBattlemasterJoinOpcode (WorldPacket & recv_data)
Definition at line 86 of file BattleGroundHandler.cpp.
References _player, Player::AddBattleGroundQueueId(), BattleGroundQueue::AddGroup(), ARENA_TYPE_NONE, GroupQueueInfo::arenaType, BATTLEGROUND_RB, BattleGroundMgr::BgQueueTypeId(), Group::CanJoinBattleGroundQueue(), Player::CanJoinToBattleground(), CONFIG_UINT32_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH, DEBUG_LOG, ERR_BATTLEGROUND_TOO_MANY_QUEUES, ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS, ERR_GROUP_JOIN_BATTLEGROUND_FAIL, ERR_IN_NON_RANDOM_BG, ERR_IN_RANDOM_BG, BattleGroundQueue::GetAverageQueueWaitTime(), GetBattlegroundBracketByLevel(), Player::GetBattleGroundQueueIndex(), PvPDifficultyEntry::GetBracketId(), Group::GetFirstMember(), Player::GetGroup(), Object::GetGUIDLow(), Group::GetLeaderGuid(), Unit::GetLevel(), BattleGround::GetMapId(), BattleGround::GetMaxPlayersPerTeam(), Group::GetMembersCount(), BattleGround::GetMinPlayersPerTeam(), WorldObject::GetName(), Object::GetObjectGuid(), Player::GetSession(), ObjectGuid::GetString(), Player::HasFreeBattleGroundQueueId(), Player::InBattleGround(), Player::InBattleGroundQueue(), GroupReference::next(), PLAYER_MAX_BATTLEGROUND_QUEUES, sBattleGroundMgr, sBattlemasterListStore, SendPacket(), sLog, STATUS_WAIT_QUEUE, sWorld, and TEAM_NONE.
HandleBeginTradeOpcode()
void WorldSession::HandleBeginTradeOpcode (WorldPacket & recvPacket)
Definition at line 519 of file TradeHandler.cpp.
References _player, Player::GetSession(), TradeData::GetTrader(), Player::m_trade, SendTradeStatus(), TradeStatusInfo::Status, and TRADE_STATUS_OPEN_WINDOW.
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleBinderActivateOpcode()
void WorldSession::HandleBinderActivateOpcode (WorldPacket & recvPacket)
Definition at line 447 of file NPCHandler.cpp.
References DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), SendBindPoint(), and UNIT_NPC_FLAG_INNKEEPER.
HandleBugOpcode()
void WorldSession::HandleBugOpcode (WorldPacket & recvPacket)
Definition at line 616 of file MiscHandler.cpp.
References CharacterDatabase, DEBUG_LOG, Database::escape_string(), and Database::PExecute().
HandleBusyTradeOpcode()
void WorldSession::HandleBusyTradeOpcode (WorldPacket & recvPacket)
Definition at line 67 of file TradeHandler.cpp.
References _player, DEBUG_LOG, and Object::GetGUIDLow().
HandleBuybackItem()
void WorldSession::HandleBuybackItem (WorldPacket & recvPacket)
Definition at line 609 of file ItemHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, BUY_ERR_CANT_FIND_ITEM, BUY_ERR_NOT_ENOUGHT_MONEY, BUYBACK_SLOT_START, Player::CanStoreItem(), DEBUG_LOG, EQUIP_ERR_OK, Player::GetAchievementMgr(), Item::GetCount(), Object::GetEntry(), Player::GetItemFromBuyBackSlot(), Player::GetMoney(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), Object::GetUInt32Value(), Player::ItemAddedQuestCheck(), Player::ModifyMoney(), NULL_BAG, NULL_SLOT, PLAYER_FIELD_BUYBACK_PRICE_1, Player::RemoveItemFromBuyBackSlot(), SELL_ERR_CANT_FIND_VENDOR, Player::SendBuyError(), Player::SendEquipError(), Player::SendSellError(), Player::StoreItem(), UNIT_NPC_FLAG_VENDOR, and AchievementMgr::UpdateAchievementCriteria().
HandleBuyBankSlotOpcode()
void WorldSession::HandleBuyBankSlotOpcode (WorldPacket & recvPacket)
Definition at line 919 of file ItemHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT, CheckBanker(), DEBUG_LOG, DETAIL_LOG, ERR_BANKSLOT_FAILED_TOO_MANY, ERR_BANKSLOT_INSUFFICIENT_FUNDS, ERR_BANKSLOT_OK, Player::GetAchievementMgr(), Player::GetBankBagSlotCount(), Player::GetMoney(), Player::ModifyMoney(), BankBagSlotPricesEntry::price, sBankBagSlotPricesStore, SendPacket(), Player::SetBankBagSlotCount(), SMSG_BUY_BANK_SLOT_RESULT, and AchievementMgr::UpdateAchievementCriteria().
HandleBuyItemInSlotOpcode()
void WorldSession::HandleBuyItemInSlotOpcode (WorldPacket & recvPacket)
Definition at line 652 of file ItemHandler.cpp.
References _player, Player::BuyItemFromVendorSlot(), DEBUG_LOG, Player::GetItemByPos(), Object::GetObjectGuid(), GetPlayer(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, and NULL_BAG.
HandleBuyItemOpcode()
void WorldSession::HandleBuyItemOpcode (WorldPacket & recvPacket)
Definition at line 695 of file ItemHandler.cpp.
References Player::BuyItemFromVendorSlot(), DEBUG_LOG, GetPlayer(), NULL_BAG, and NULL_SLOT.
HandleBuyStableSlot()
void WorldSession::HandleBuyStableSlot (WorldPacket & recvPacket)
Definition at line 840 of file NPCHandler.cpp.
References _player, CheckStableMaster(), DEBUG_LOG, Player::GetMoney(), GetPlayer(), Player::m_stableSlots, MAX_PET_STABLES, Player::ModifyMoney(), StableSlotPricesEntry::Price, SendStableResult(), sStableSlotPricesStore, STABLE_ERR_MONEY, STABLE_ERR_STABLE, and STABLE_SUCCESS_BUY_SLOT.
HandleCalendarAddEvent()
void WorldSession::HandleCalendarAddEvent (WorldPacket & recv_data)
Definition at line 258 of file CalendarHandler.cpp.
References _player, CALENDAR_RANK_PLAYER, CALENDAR_SENDTYPE_ADD, CALENDAR_STATUS_NOT_SIGNED_UP, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), CalendarEvent::IsGuildAnnouncement(), ObjectGuid::ReadAsPacked(), sCalendarMgr, and timeBitFieldsToSecs().
HandleCalendarArenaTeam()
void WorldSession::HandleCalendarArenaTeam (WorldPacket & recv_data)
Definition at line 248 of file CalendarHandler.cpp.
References _player, DEBUG_LOG, Object::GetGuidStr(), and sObjectMgr.
HandleCalendarComplain()
void WorldSession::HandleCalendarComplain (WorldPacket & recv_data)
Definition at line 703 of file CalendarHandler.cpp.
References _player, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, sCalendarMgr, SendPacket(), SMSG_COMPLAIN_RESULT, and UI64FMTD.
HandleCalendarCopyEvent()
void WorldSession::HandleCalendarCopyEvent (WorldPacket & recv_data)
Definition at line 397 of file CalendarHandler.cpp.
References _player, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, sCalendarMgr, timeBitFieldsToSecs(), and UI64FMTD.
HandleCalendarEventInvite()
void WorldSession::HandleCalendarEventInvite (WorldPacket & recv_data)
Definition at line 414 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_IGNORING_YOU_S, CALENDAR_ERROR_NO_GUILD_INVITES, CALENDAR_ERROR_NOT_ALLIED, CALENDAR_ERROR_PLAYER_NOT_FOUND, CALENDAR_RANK_PLAYER, CALENDAR_STATUS_INVITED, CharacterDatabase, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CALENDAR, DEBUG_FILTER_LOG, DEBUG_LOG, Database::escape_string(), QueryResult::Fetch(), ObjectGuid::GetCounter(), Player::GetGuildId(), Player::GetGuildIdFromDB(), Object::GetObjectGuid(), ObjectGuid::GetString(), Player::GetTeam(), HIGHGUID_PLAYER, CalendarInvite::InviteeGuid, ObjectGuid::IsEmpty(), CalendarInvite::LastUpdateTime, LOG_FILTER_CALENDAR, Database::PQuery(), CalendarInvite::Rank, sCalendarMgr, CalendarInvite::SenderGuid, sObjectAccessor, SOCIAL_FLAG_IGNORED, CalendarInvite::Status, sWorld, TEAM_NONE, and Player::TeamForRace().
HandleCalendarEventModeratorStatus()
void WorldSession::HandleCalendarEventModeratorStatus (WorldPacket & recv_data)
Definition at line 649 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_NO_INVITE, CALENDAR_ERROR_NOT_INVITED, CALENDAR_ERROR_PERMISSIONS, CALENDAR_RANK_MODERATOR, CALENDAR_RANK_OWNER, CharacterDatabase, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, Database::PExecute(), CalendarInvite::Rank, ObjectGuid::ReadAsPacked(), sCalendarMgr, and UI64FMTD.
HandleCalendarEventRemoveInvite()
void WorldSession::HandleCalendarEventRemoveInvite (WorldPacket & recv_data)
Definition at line 576 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, ObjectGuid::ReadAsPacked(), sCalendarMgr, and UI64FMTD.
HandleCalendarEventRsvp()
void WorldSession::HandleCalendarEventRsvp (WorldPacket & recv_data)
Definition at line 522 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_EVENT_LOCKED, CALENDAR_ERROR_NO_INVITE, CALENDAR_ERROR_NOT_INVITED, CALENDAR_ERROR_PERMISSIONS, CALENDAR_FLAG_INVITES_LOCKED, CALENDAR_RANK_MODERATOR, CALENDAR_RANK_OWNER, CALENDAR_STATUS_REMOVED, CharacterDatabase, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, Database::PExecute(), CalendarInvite::Rank, sCalendarMgr, and UI64FMTD.
HandleCalendarEventSignup()
void WorldSession::HandleCalendarEventSignup (WorldPacket & recvData)
Definition at line 220 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_GUILD_PLAYER_NOT_IN_GUILD, CALENDAR_RANK_PLAYER, CALENDAR_STATUS_SIGNED_UP, CALENDAR_STATUS_TENTATIVE, DEBUG_FILTER_LOG, DEBUG_LOG, Player::GetGuildId(), Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, sCalendarMgr, and UI64FMTD.
HandleCalendarEventStatus()
void WorldSession::HandleCalendarEventStatus (WorldPacket & recv_data)
Definition at line 598 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_NO_INVITE, CALENDAR_ERROR_NOT_INVITED, CALENDAR_ERROR_PERMISSIONS, CALENDAR_RANK_MODERATOR, CALENDAR_RANK_OWNER, CharacterDatabase, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), ByteBuffer::hexlike(), LOG_FILTER_CALENDAR, Database::PExecute(), CalendarInvite::Rank, ObjectGuid::ReadAsPacked(), sCalendarMgr, sObjectMgr, and UI64FMTD.
HandleCalendarGetCalendar()
void WorldSession::HandleCalendarGetCalendar (WorldPacket & recv_data)
Definition at line 34 of file CalendarHandler.cpp.
References _player, ByteBuffer::append(), HolidaysEntry::CalendarFilterType, HolidaysEntry::CalendarFlags, ByteBuffer::clear(), HolidaysEntry::Date, DEBUG_FILTER_LOG, DEBUG_LOG, HolidaysEntry::Duration, Player::GetBoundInstances(), MapPersistentState::GetDifficulty(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMapId(), Object::GetObjectGuid(), DungeonPersistentState::GetResetTime(), ObjectGuid::GetString(), HolidaysEntry::Id, MapEntry::IsRaid(), LOG_FILTER_CALENDAR, HolidaysEntry::Looping, MANGOS_ASSERT, MAX_DIFFICULTY, MAX_HOLIDAY_DATES, MAX_HOLIDAY_DURATIONS, MAX_HOLIDAY_FLAGS, PAIR32_LOPART, HolidaysEntry::Priority, HolidaysEntry::Region, MapDifficultyEntry::resetTime, sCalendarMgr, secsToTimeBitFields(), SendPacket(), sHolidaysStore, sMapDifficultyMap, sMapPersistentStateMgr, sMapStore, SMSG_CALENDAR_SEND_CALENDAR, HolidaysEntry::TextureFilename, TimeToTimestampStr(), and UI64FMTD.
HandleCalendarGetEvent()
void WorldSession::HandleCalendarGetEvent (WorldPacket & recv_data)
Definition at line 190 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_SENDTYPE_GET, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), and sCalendarMgr.
HandleCalendarGetNumPending()
void WorldSession::HandleCalendarGetNumPending (WorldPacket & recv_data)
Definition at line 727 of file CalendarHandler.cpp.
References _player, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, sCalendarMgr, SendPacket(), and SMSG_CALENDAR_SEND_NUM_PENDING.
HandleCalendarGuildFilter()
void WorldSession::HandleCalendarGuildFilter (WorldPacket & recv_data)
Definition at line 204 of file CalendarHandler.cpp.
References _player, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetGuidStr(), Player::GetGuildId(), LOG_FILTER_CALENDAR, and sGuildMgr.
HandleCalendarRemoveEvent()
void WorldSession::HandleCalendarRemoveEvent (WorldPacket & recv_data)
Definition at line 382 of file CalendarHandler.cpp.
References _player, DEBUG_FILTER_LOG, DEBUG_LOG, Object::GetGuidStr(), LOG_FILTER_CALENDAR, sCalendarMgr, and UI64FMTD.
HandleCalendarUpdateEvent()
void WorldSession::HandleCalendarUpdateEvent (WorldPacket & recv_data)
Definition at line 313 of file CalendarHandler.cpp.
References _player, CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_NOT_INVITED, CALENDAR_ERROR_PERMISSIONS, CALENDAR_RANK_MODERATOR, CharacterDatabase, DEBUG_FILTER_LOG, DEBUG_LOG, Database::escape_string(), Object::GetObjectGuid(), ObjectGuid::GetString(), LOG_FILTER_CALENDAR, Database::PExecute(), CalendarInvite::Rank, sCalendarMgr, timeBitFieldsToSecs(), and UI64FMTD.
HandleCancelAuraOpcode()
void WorldSession::HandleCancelAuraOpcode (WorldPacket & recvPacket)
Definition at line 515 of file SpellHandler.cpp.
References _player, CURRENT_CHANNELED_SPELL, SpellEntry::EffectApplyAuraName, SpellAuraHolder::GetCasterGuid(), Unit::GetCurrentSpell(), Object::GetObjectGuid(), Unit::GetSpellAuraHolder(), SpellAuraHolder::GetSpellProto(), HasAreaAuraEffect(), SpellEntry::HasAttribute(), Unit::InterruptSpell(), IsChanneledSpell(), IsPassiveSpell(), SpellAuraHolder::IsPositive(), Player::IsSelfMover(), SQLStorage::LookupEntry(), Unit::RemoveAurasDueToSpellByCancel(), SPELL_ATTR_NO_AURA_CANCEL, SPELL_AURA_MOD_POSSESS, SPELL_AURA_MOD_POSSESS_PET, and sSpellTemplate.
HandleCancelAutoRepeatSpellOpcode()
void WorldSession::HandleCancelAutoRepeatSpellOpcode (WorldPacket & recvPacket)
Definition at line 620 of file SpellHandler.cpp.
References _player, CURRENT_AUTOREPEAT_SPELL, Player::GetMover(), and Unit::InterruptSpell().
HandleCancelCastOpcode()
void WorldSession::HandleCancelCastOpcode (WorldPacket & recvPacket)
Definition at line 496 of file SpellHandler.cpp.
References _player, Player::GetMover(), Object::GetTypeId(), Unit::InterruptNonMeleeSpells(), Unit::IsClientControlled(), Unit::IsNonMeleeSpellCasted(), ByteBuffer::read_skip(), and TYPEID_PLAYER.
HandleCancelChanneling()
void WorldSession::HandleCancelChanneling (WorldPacket & recv_data)
Definition at line 627 of file SpellHandler.cpp.
References _player, CURRENT_CHANNELED_SPELL, Player::GetMover(), Object::GetTypeId(), Unit::InterruptSpell(), ByteBuffer::read_skip(), and TYPEID_PLAYER.
HandleCancelGrowthAuraOpcode()
void WorldSession::HandleCancelGrowthAuraOpcode (WorldPacket & recvPacket)
Definition at line 615 of file SpellHandler.cpp.
HandleCancelMountAuraOpcode()
void WorldSession::HandleCancelMountAuraOpcode (WorldPacket & recv_data)
Definition at line 1455 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Unit::IsMounted(), Unit::IsTaxiFlying(), LANG_CHAR_NON_MOUNTED, LANG_YOU_IN_FLIGHT, Unit::RemoveSpellsCausingAura(), ChatHandler::SendSysMessage(), SPELL_AURA_MOUNTED, and Player::Unmount().
Referenced by PlayerbotMgr::HandleMasterOutgoingPacket(), and PlayerbotAI::UpdateAI().
HandleCancelTempEnchantmentOpcode()
void WorldSession::HandleCancelTempEnchantmentOpcode (WorldPacket & recv_data)
Definition at line 1424 of file ItemHandler.cpp.
References Player::ApplyEnchantment(), Item::ClearEnchantment(), DEBUG_LOG, Item::GetEnchantmentId(), Player::GetItemByPos(), GetPlayer(), INVENTORY_SLOT_BAG_0, Player::IsEquipmentPos(), and TEMP_ENCHANTMENT_SLOT.
HandleCancelTradeOpcode()
void WorldSession::HandleCancelTradeOpcode (WorldPacket & recvPacket)
Definition at line 541 of file TradeHandler.cpp.
References _player, and Player::TradeCancel().
HandleCastSpellOpcode()
void WorldSession::HandleCastSpellOpcode (WorldPacket & recvPacket)
Definition at line 378 of file SpellHandler.cpp.
References _player, Messager< T >::AddMessage(), Spell::CheckVehicle(), DEBUG_LOG, Object::GetGuidStr(), GetMessager(), Player::GetMover(), Object::GetObjectGuid(), Aura::GetSpellProto(), Unit::GetTarget(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Unit::GetTriggeredByClientAura(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), HandleClientCastFlags(), WorldObject::HasGCD(), WorldObject::HasGCDOrCooldownWithinMargin(), HasMissingTargetFromClient(), Player::HasQueuedSpell(), Player::HasSpell(), Unit::HasSpell(), IsPassiveSpell(), WorldObject::IsSpellReady(), SQLStorage::LookupEntry(), Spell::m_cast_count, Spell::m_clientCast, SpellCastTargets::ReadForCaster(), ByteBuffer::rpos(), Player::SetQueuedSpell(), SpellCastTargets::setUnitTarget(), ByteBuffer::size(), SIZEFMTD, sLog, SPELL_CAST_OK, sSpellMgr, sSpellTemplate, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and ByteBuffer::wpos().
HandleChangePlayerDifficulty()
void WorldSession::HandleChangePlayerDifficulty (WorldPacket & recv_data)
Definition at line 1359 of file MiscHandler.cpp.
References _player, AREA_LOCKSTATUS_OK, Group::BroadcastPacketInMap(), Map::ChangeMapDifficulty(), DEBUG_LOG, Player::GetAreaTriggerLockStatus(), Map::GetCurrentClockTime(), Map::GetDifficulty(), Map::GetEntry(), Group::GetFirstMember(), Player::GetGroup(), Map::GetId(), Map::GetInstanceData(), WorldObject::GetMap(), Map::GetNewDifficultyCooldown(), Object::GetObjectGuid(), Map::IsDungeon(), MapEntry::IsDynamicDifficultyMap(), InstanceData::IsEncounterInProgress(), Unit::IsInCombat(), Group::IsLeader(), GroupReference::next(), RESULT_COMPLETE, RESULT_COOLDOWN, RESULT_ENCOUNTER_IN_PROGRESS, RESULT_FAILED_CONDITION, RESULT_PLAYER_IN_COMBAT, RESULT_SET_DIFFICULTY, RESULT_START, SendPacket(), Player::SendRaidDifficulty(), Group::SetRaidDifficulty(), SMSG_CHANGE_PLAYER_DIFFICULTY_RESULT, and sObjectMgr.
HandleChangePlayerNameOpcodeCallBack()
void WorldSession::HandleChangePlayerNameOpcodeCallBack (QueryResult * result, uint32 accountId, std::string newname) static
Definition at line 1219 of file CharacterHandler.cpp.
References AT_LOGIN_RENAME, Database::BeginTransaction(), CHAR_CREATE_ERROR, CharacterDatabase, Database::CommitTransaction(), QueryResult::Fetch(), GetAccountId(), Field::GetCppString(), GetRemoteAddress(), Field::GetUInt32(), HIGHGUID_PLAYER, Database::PExecute(), RESPONSE_SUCCESS, SendPacket(), sLog, SMSG_CHAR_RENAME, and sWorld.
Referenced by HandleCharRenameOpcode().
HandleChangeSeatsOnControlledVehicle()
void WorldSession::HandleChangeSeatsOnControlledVehicle (WorldPacket & recvPacket)
Definition at line 134 of file VehicleHandler.cpp.
References _player, Unit::CastSpell(), DEBUG_LOG, Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), Map::GetUnit(), VehicleInfo::GetVehicleEntry(), Unit::GetVehicleInfo(), ByteBuffer::hexlike(), TransportInfo::IsOnVehicle(), Unit::IsVehicle(), VehicleEntry::m_flags, ObjectGuid::ReadAsPacked(), sObjectMgr, VehicleInfo::SwitchSeat(), TRIGGERED_OLD_TRIGGERED, TYPEID_UNIT, and VEHICLE_FLAG_DISABLE_SWITCH.
HandleChannelAnnouncementsOpcode()
void WorldSession::HandleChannelAnnouncementsOpcode (WorldPacket & recvPacket)
Definition at line 295 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelBanOpcode()
void WorldSession::HandleChannelBanOpcode (WorldPacket & recvPacket)
Definition at line 260 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelDisplayListQueryOpcode()
void WorldSession::HandleChannelDisplayListQueryOpcode (WorldPacket & recvPacket)
Definition at line 317 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelInviteOpcode()
void WorldSession::HandleChannelInviteOpcode (WorldPacket & recvPacket)
Definition at line 227 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelKickOpcode()
void WorldSession::HandleChannelKickOpcode (WorldPacket & recvPacket)
Definition at line 244 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelListOpcode()
void WorldSession::HandleChannelListOpcode (WorldPacket & recvPacket)
Definition at line 103 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelModerateOpcode()
void WorldSession::HandleChannelModerateOpcode (WorldPacket & recvPacket)
Definition at line 306 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelModeratorOpcode()
void WorldSession::HandleChannelModeratorOpcode (WorldPacket & recvPacket)
Definition at line 158 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelMuteOpcode()
void WorldSession::HandleChannelMuteOpcode (WorldPacket & recvPacket)
Definition at line 192 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelOwnerOpcode()
void WorldSession::HandleChannelOwnerOpcode (WorldPacket & recvPacket)
Definition at line 147 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelPasswordOpcode()
void WorldSession::HandleChannelPasswordOpcode (WorldPacket & recvPacket)
Definition at line 115 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleChannelSetOwnerOpcode()
void WorldSession::HandleChannelSetOwnerOpcode (WorldPacket & recvPacket)
Definition at line 129 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelUnbanOpcode()
void WorldSession::HandleChannelUnbanOpcode (WorldPacket & recvPacket)
Definition at line 277 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelUnmoderatorOpcode()
void WorldSession::HandleChannelUnmoderatorOpcode (WorldPacket & recvPacket)
Definition at line 175 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelUnmuteOpcode()
void WorldSession::HandleChannelUnmuteOpcode (WorldPacket & recvPacket)
Definition at line 209 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), and normalizePlayerName().
HandleChannelVoiceOnOpcode()
void WorldSession::HandleChannelVoiceOnOpcode (WorldPacket & recv_data)
Definition at line 33 of file VoiceChatHandler.cpp.
References DEBUG_LOG, and ByteBuffer::hexlike().
HandleCharCreateOpcode()
void WorldSession::HandleCharCreateOpcode (WorldPacket & recvPacket)
Definition at line 227 of file CharacterHandler.cpp.
References ALLIANCE, AT_LOGIN_FIRST, CHAR_CREATE_ACCOUNT_LIMIT, CHAR_CREATE_DISABLED, CHAR_CREATE_ERROR, CHAR_CREATE_EXPANSION, CHAR_CREATE_EXPANSION_CLASS, CHAR_CREATE_FAILED, CHAR_CREATE_LEVEL_REQUIREMENT, CHAR_CREATE_NAME_IN_USE, CHAR_CREATE_PVP_TEAMS_VIOLATION, CHAR_CREATE_SERVER_LIMIT, CHAR_CREATE_SUCCESS, CHAR_CREATE_UNIQUE_CLASS_LIMIT, CHAR_NAME_NO_NAME, CHAR_NAME_RESERVED, CHAR_NAME_SUCCESS, CharacterDatabase, ObjectMgr::CheckPlayerName(), CINEMATICS_SKIP_ALL, CINEMATICS_SKIP_SAME_RACE, CLASS_DEATH_KNIGHT, CONFIG_BOOL_ALLOW_TWO_SIDE_ACCOUNTS, CONFIG_UINT32_CHARACTERS_CREATING_DISABLED, CONFIG_UINT32_CHARACTERS_PER_ACCOUNT, CONFIG_UINT32_CHARACTERS_PER_REALM, CONFIG_UINT32_HEROIC_CHARACTERS_PER_REALM, CONFIG_UINT32_MAX_PLAYER_LEVEL, CONFIG_UINT32_MIN_LEVEL_FOR_HEROIC_CHARACTER_CREATING, CONFIG_UINT32_SKIP_CINEMATICS, Player::Create(), DETAIL_LOG, ChrClassesEntry::expansion, ChrRacesEntry::expansion, QueryResult::Fetch(), GetAccountId(), GetExpansion(), Object::GetGUIDLow(), GetRemoteAddress(), GetSecurity(), Field::GetUInt32(), Field::GetUInt8(), HORDE, LoginDatabase, QueryResult::NextRow(), normalizePlayerName(), Database::PExecute(), Database::PQuery(), realmID, Player::SaveToDB(), sChrClassesStore, sChrRacesStore, SEC_PLAYER, SendPacket(), Player::SetAtLoginFlag(), Player::setCinematic(), sLog, SMSG_CHAR_CREATE, sObjectMgr, sWorld, Player::TeamForRace(), and Player::ValidateAppearance().
HandleCharCustomizeOpcode()
void WorldSession::HandleCharCustomizeOpcode (WorldPacket & recv_data)
Definition at line 1420 of file CharacterHandler.cpp.
References AT_LOGIN_CUSTOMIZE, CHAR_CREATE_ERROR, CHAR_CREATE_NAME_IN_USE, CHAR_NAME_NO_NAME, CHAR_NAME_RESERVED, CHAR_NAME_SUCCESS, CharacterDatabase, ObjectMgr::CheckPlayerName(), Player::Customize(), Database::escape_string(), QueryResult::Fetch(), GetAccountId(), ObjectGuid::GetCounter(), GetRemoteAddress(), GetSecurity(), ObjectGuid::GetString(), Field::GetUInt32(), normalizePlayerName(), Database::PExecute(), Database::PQuery(), RESPONSE_SUCCESS, SEC_PLAYER, SendPacket(), sLog, SMSG_CHAR_CUSTOMIZE, sObjectMgr, and sWorld.
HandleCharDeleteOpcode()
void WorldSession::HandleCharDeleteOpcode (WorldPacket & recvPacket)
Definition at line 525 of file CharacterHandler.cpp.
References BASIC_LOG, CHAR_DELETE_FAILED_ARENA_CAPTAIN, CHAR_DELETE_FAILED_GUILD_LEADER, CHAR_DELETE_SUCCESS, CharacterDatabase, Player::DeleteFromDB(), QueryResult::Fetch(), GetAccountId(), ObjectGuid::GetCounter(), Field::GetCppString(), PlayerDumpWriter::GetDump(), GetRemoteAddress(), Field::GetUInt32(), Database::PQuery(), sCalendarMgr, SendPacket(), sGuildMgr, sLog, SMSG_CHAR_DELETE, and sObjectMgr.
HandleCharEnum()
void WorldSession::HandleCharEnum (QueryResult * result)
Definition at line 170 of file CharacterHandler.cpp.
References Player::BuildEnumData(), DETAIL_LOG, GetAccountId(), m_anticheat, QueryResult::NextRow(), ByteBuffer::put(), and SMSG_CHAR_ENUM.
Referenced by CharacterHandler::HandleCharEnumCallback().
HandleCharEnumOpcode()
void WorldSession::HandleCharEnumOpcode (WorldPacket & recvPacket)
get all the data necessary for loading all characters (along with their pets) on the account
Definition at line 197 of file CharacterHandler.cpp.
References Database::AsyncPQuery(), CharacterDatabase, chrHandler, CONFIG_BOOL_DECLINED_NAMES_USED, GetAccountId(), CharacterHandler::HandleCharEnumCallback(), PET_SAVE_AS_CURRENT, and sWorld.
HandleCharRenameOpcode()
void WorldSession::HandleCharRenameOpcode (WorldPacket & recv_data)
Definition at line 1172 of file CharacterHandler.cpp.
References Database::AsyncPQuery(), AT_LOGIN_RENAME, CHAR_NAME_NO_NAME, CHAR_NAME_RESERVED, CHAR_NAME_SUCCESS, CharacterDatabase, ObjectMgr::CheckPlayerName(), Database::escape_string(), GetAccountId(), ObjectGuid::GetCounter(), GetSecurity(), HandleChangePlayerNameOpcodeCallBack(), normalizePlayerName(), SEC_PLAYER, SendPacket(), SMSG_CHAR_RENAME, and sObjectMgr.
HandleChatIgnoredOpcode()
void WorldSession::HandleChatIgnoredOpcode (WorldPacket & recvPacket)
Definition at line 706 of file ChatHandler.cpp.
References _player, ChatHandler::BuildChatPacket(), CHAT_MSG_IGNORED, CHAT_TAG_NONE, WorldObject::GetName(), Object::GetObjectGuid(), Player::GetSession(), LANG_UNIVERSAL, SendPacket(), and sObjectMgr.
HandleClearTradeItemOpcode()
void WorldSession::HandleClearTradeItemOpcode (WorldPacket & recvPacket)
Definition at line 719 of file TradeHandler.cpp.
References _player, Player::m_trade, TradeData::SetItem(), and TRADE_SLOT_COUNT.
HandleClientCastFlags()
void WorldSession::HandleClientCastFlags (WorldPacket & recvPacket, uint8 castFlags, SpellCastTargets & targets)
Definition at line 879 of file SpellHandler.cpp.
References HandleMovementOpcodes(), MSG_MOVE_STOP, SpellCastTargets::setElevation(), WorldPacket::SetOpcode(), and SpellCastTargets::setSpeed().
Referenced by HandleCastSpellOpcode(), HandlePetCastSpellOpcode(), and HandleUseItemOpcode().
HandleCommentatorModeOpcode()
void WorldSession::HandleCommentatorModeOpcode (WorldPacket & recv_data)
Definition at line 1552 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Object::GetGUIDLow(), GetPlayer(), Player::IsGameMaster(), PLAYER_FLAGS, PLAYER_FLAGS_COMMENTATOR, PLAYER_FLAGS_COMMENTATOR_UBER, Object::RemoveFlag(), Object::SetFlag(), sLog, and Object::ToggleFlag().
HandleComplainChat()
void WorldSession::HandleComplainChat (WorldPacket & recv_data) private
Definition at line 1171 of file MiscHandler.cpp.
References DEBUG_LOG, and ObjectGuid::GetString().
Referenced by HandleComplainOpcode().
HandleComplainMail()
void WorldSession::HandleComplainMail (WorldPacket & recv_data) private
Definition at line 1156 of file MiscHandler.cpp.
References DEBUG_LOG, and ObjectGuid::GetString().
Referenced by HandleComplainOpcode().
HandleComplainOpcode()
void WorldSession::HandleComplainOpcode (WorldPacket & recv_data)
Definition at line 1130 of file MiscHandler.cpp.
References DEBUG_LOG, HandleComplainChat(), HandleComplainMail(), SendPacket(), and SMSG_COMPLAIN_RESULT.
HandleCompleteCinematic()
void WorldSession::HandleCompleteCinematic (WorldPacket & recvPacket)
Definition at line 931 of file MiscHandler.cpp.
References DEBUG_LOG, GetPlayer(), and Player::StopCinematic().
HandleContactListOpcode()
void WorldSession::HandleContactListOpcode (WorldPacket & recvPacket)
Definition at line 436 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetSocial(), and PlayerSocial::SendSocialList().
HandleCorpseMapPositionQueryOpcode()
void WorldSession::HandleCorpseMapPositionQueryOpcode (WorldPacket & recvPacket)
Definition at line 475 of file QueryHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_CORPSE_TRANSPORT_QUERY.
HandleCorpseQueryOpcode()
void WorldSession::HandleCorpseQueryOpcode (WorldPacket & recvPacket)
Definition at line 294 of file QueryHandler.cpp.
References _player, DETAIL_LOG, Player::GetCorpse(), WorldObject::GetMapId(), GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), MAX_HEIGHT, MSG_CORPSE_QUERY, SendPacket(), sMapStore, and sTerrainMgr.
HandleCreatureQueryOpcode()
void WorldSession::HandleCreatureQueryOpcode (WorldPacket & recvPacket)
Only static data send in this packet !!!
Definition at line 185 of file QueryHandler.cpp.
References CreatureInfo::CreatureType, CreatureInfo::CreatureTypeFlags, DEBUG_LOG, DETAIL_LOG, CreatureInfo::Family, ObjectMgr::GetCreatureTemplate(), GetSessionDbLocaleIndex(), ObjectGuid::GetString(), CreatureInfo::HealthMultiplier, CreatureInfo::IconName, CreatureInfo::KillCredit, CreatureInfo::ModelId, CreatureInfo::MovementTemplateId, CreatureInfo::Name, CreatureInfo::PowerMultiplier, CreatureInfo::QuestItems, CreatureInfo::RacialLeader, CreatureInfo::Rank, SendPacket(), SMSG_CREATURE_QUERY_RESPONSE, sObjectMgr, and CreatureInfo::SubName.
HandleDelFriendOpcode()
void WorldSession::HandleDelFriendOpcode (WorldPacket & recvPacket)
Definition at line 518 of file MiscHandler.cpp.
References _player, DEBUG_LOG, FRIEND_REMOVED, GetPlayer(), Player::GetSocial(), PlayerSocial::RemoveFromSocialList(), and sSocialMgr.
HandleDelIgnoreOpcode()
void WorldSession::HandleDelIgnoreOpcode (WorldPacket & recvPacket)
Definition at line 592 of file MiscHandler.cpp.
References _player, DEBUG_LOG, FRIEND_IGNORE_REMOVED, GetPlayer(), Player::GetSocial(), PlayerSocial::RemoveFromSocialList(), and sSocialMgr.
HandleDestroyItemOpcode()
void WorldSession::HandleDestroyItemOpcode (WorldPacket & recvPacket)
Definition at line 236 of file ItemHandler.cpp.
References _player, Player::CanUnequipItem(), Player::DestroyItem(), Player::DestroyItemCount(), EQUIP_ERR_CANT_DROP_SOULBOUND, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, ItemPrototype::Flags, Player::GetItemByPos(), Item::GetProto(), Player::IsBagPos(), Player::IsEquipmentPos(), ITEM_FLAG_NO_USER_DESTROY, and Player::SendEquipError().
HandleDismissControlledVehicle()
void WorldSession::HandleDismissControlledVehicle (WorldPacket & recvPacket)
Definition at line 28 of file VehicleHandler.cpp.
References _player, DEBUG_LOG, Object::GetObjectGuid(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), ByteBuffer::hexlike(), TransportInfo::IsOnVehicle(), ObjectGuid::ReadAsPacked(), Unit::RemoveSpellsCausingAura(), and SPELL_AURA_CONTROL_VEHICLE.
HandleDismissCritter()
void WorldSession::HandleDismissCritter (WorldPacket & recvPacket)
Definition at line 883 of file PetHandler.cpp.
References _player, Unit::GetMiniPet(), and PET_SAVE_AS_DELETED.
HandleDuelAcceptedOpcode()
void WorldSession::HandleDuelAcceptedOpcode (WorldPacket & recvPacket)
Definition at line 25 of file DuelHandler.cpp.
References DEBUG_FILTER_LOG, Player::duel, Object::GetGUIDLow(), WorldObject::GetName(), GetPlayer(), DuelInfo::initiator, LOG_FILTER_COMBAT, DuelInfo::opponent, Player::SendDuelCountdown(), DuelInfo::startTime, and DuelInfo::startTimer.
HandleDuelCancelledOpcode()
void WorldSession::HandleDuelCancelledOpcode (WorldPacket & recvPacket)
Definition at line 65 of file DuelHandler.cpp.
References Unit::CombatStopWithPets(), DEBUG_LOG, Player::duel, DUEL_INTERRUPTED, DUEL_WON, GetPlayer(), DuelInfo::opponent, and TRIGGERED_OLD_TRIGGERED.
HandleEjectPassenger()
void WorldSession::HandleEjectPassenger (WorldPacket & recvPacket)
Definition at line 199 of file VehicleHandler.cpp.
References _player, DEBUG_LOG, WorldObject::GetMap(), VehicleInfo::GetSeatEntry(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Map::GetUnit(), Unit::GetVehicleInfo(), TransportBase::HasOnBoard(), ByteBuffer::hexlike(), WorldObject::IsBoarded(), Unit::IsVehicle(), Unit::RemoveSpellsCausingAura(), SEAT_FLAG_B_EJECTABLE, and SPELL_AURA_CONTROL_VEHICLE.
HandleEmoteOpcode()
void WorldSession::HandleEmoteOpcode (WorldPacket & recvPacket)
Definition at line 604 of file ChatHandler.cpp.
References AURA_INTERRUPT_FLAG_ANIM_CANCELS, EMOTE_ONESHOT_NONE, EMOTE_ONESHOT_WAVE, GetPlayer(), Unit::HandleEmoteCommand(), Unit::InterruptSpellsAndAurasWithInterruptFlags(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PREVENT_ANIM.
HandleEquipmentSetDeleteOpcode()
void WorldSession::HandleEquipmentSetDeleteOpcode (WorldPacket & recv_data)
Definition at line 1563 of file CharacterHandler.cpp.
References _player, DEBUG_LOG, Player::DeleteEquipmentSet(), ObjectGuid::GetRawValue(), and ObjectGuid::ReadAsPacked().
HandleEquipmentSetSaveOpcode()
void WorldSession::HandleEquipmentSetSaveOpcode (WorldPacket & recv_data)
Definition at line 1511 of file CharacterHandler.cpp.
References _player, DEBUG_LOG, EQUIPMENT_SET_NEW, EQUIPMENT_SLOT_END, ObjectGuid::GetCounter(), Player::GetItemByPos(), Object::GetObjectGuid(), ObjectGuid::GetRawValue(), EquipmentSet::Guid, EquipmentSet::IconName, EquipmentSet::IgnoreMask, INVENTORY_SLOT_BAG_0, EquipmentSet::Items, MAX_EQUIPMENT_SET_INDEX, EquipmentSet::Name, ObjectGuid::ReadAsPacked(), Player::SetEquipmentSet(), and EquipmentSet::state.
HandleEquipmentSetUseOpcode()
void WorldSession::HandleEquipmentSetUseOpcode (WorldPacket & recv_data)
Definition at line 1574 of file CharacterHandler.cpp.
References _player, Player::CanStoreItem(), DEBUG_LOG, EQUIP_ERR_OK, EQUIPMENT_SLOT_END, Player::GetItemByGuid(), Player::GetItemByPos(), Item::GetPos(), ObjectGuid::GetRawValue(), ObjectGuid::GetString(), ByteBuffer::hexlike(), INVENTORY_SLOT_BAG_0, NULL_BAG, NULL_SLOT, ObjectGuid::ReadAsPacked(), Player::RemoveItem(), Player::SendEquipError(), SendPacket(), SMSG_USE_EQUIPMENT_SET_RESULT, Player::StoreItem(), and Player::SwapItem().
HandleFarSightOpcode()
void WorldSession::HandleFarSightOpcode (WorldPacket & recv_data)
Definition at line 1210 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetCamera(), Player::GetFarSightGuid(), Object::GetGuidStr(), WorldObject::GetMap(), ObjectGuid::GetString(), Map::GetWorldObject(), Camera::ResetView(), and Camera::SetView().
HandleForceSpeedChangeAckOpcodes()
void WorldSession::HandleForceSpeedChangeAckOpcodes (WorldPacket & recv_data)
Definition at line 367 of file MovementHandler.cpp.
References _player, BASIC_LOG, CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK, CMSG_FORCE_PITCH_RATE_CHANGE_ACK, CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_RUN_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_SPEED_CHANGE_ACK, CMSG_FORCE_TURN_RATE_CHANGE_ACK, CMSG_FORCE_WALK_SPEED_CHANGE_ACK, CMSG_MOVE_SET_COLLISION_HGT_ACK, DEBUG_LOG, GetAccountId(), Player::GetMover(), WorldObject::GetName(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetSession(), Unit::GetSpeed(), Unit::GetSpeedRate(), WorldObject::GetTransport(), Player::IsSelfMover(), KickPlayer(), m_anticheat, Player::m_forced_speed_changes, MAX_MOVE_TYPE, MOVE_FLIGHT, MOVE_FLIGHT_BACK, MOVE_PITCH_RATE, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_TURN_RATE, MOVE_WALK, MSG_MOVE_SET_COLLISION_HGT, ProcessMovementInfo(), ObjectGuid::ReadAsPacked(), WorldObject::SendMessageToSetExcept(), SetSpeed2Opc_table, Unit::SetSpeedRate(), sLog, and ObjectGuid::WriteAsPacked().
HandleGameObjectQueryOpcode()
void WorldSession::HandleGameObjectQueryOpcode (WorldPacket & recvPacket)
Only static data send in this packet !!!
Definition at line 240 of file QueryHandler.cpp.
References ByteBuffer::append(), GameObjectInfo::castBarCaption, GameObjectLocale::CastBarCaption, DEBUG_LOG, DETAIL_LOG, GameObjectInfo::displayId, ObjectMgr::GetGameObjectInfo(), GetSessionDbLocaleIndex(), ObjectGuid::GetString(), GameObjectInfo::IconName, GameObjectInfo::name, GameObjectLocale::Name, GameObjectInfo::questItems, GameObjectInfo::raw, SendPacket(), GameObjectInfo::size, SMSG_GAMEOBJECT_QUERY_RESPONSE, sObjectMgr, GameObjectInfo::type, and GameObjectInfo::unk1.
HandleGameobjectReportUse()
void WorldSession::HandleGameobjectReportUse (WorldPacket & recvPacket)
Definition at line 357 of file SpellHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, DEBUG_LOG, Player::GetAchievementMgr(), Object::GetEntry(), Map::GetGameObject(), WorldObject::GetMap(), GetPlayer(), ObjectGuid::GetString(), INTERACTION_DISTANCE, Player::IsSelfMover(), WorldObject::IsWithinDistInMap(), and AchievementMgr::UpdateAchievementCriteria().
HandleGameObjectUseOpcode()
void WorldSession::HandleGameObjectUseOpcode (WorldPacket & recPacket)
Definition at line 288 of file SpellHandler.cpp.
References _player, GameObjectInfo::CannotBeUsedUnderImmunity(), DEBUG_LOG, DIST_CALC_NONE, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_GENERIC, GameObject::GetClosestChairSlotPosition(), WorldObject::GetDistance(), Object::GetEntry(), Map::GetGameObject(), GameObject::GetGOInfo(), GameObject::GetGoType(), WorldObject::GetMap(), WorldObject::GetPositionZ(), ObjectGuid::GetString(), WorldObject::GetTransportInfo(), Object::GetUInt32Value(), GO_FLAG_IN_USE, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, Object::HasFlag(), GameObject::IsAtInteractDistance(), Player::IsBeingTeleported(), TransportInfo::IsOnVehicle(), Player::IsSelfMover(), GameObject::IsSpawned(), GameObjectInfo::IsUsableMounted(), sLog, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE, and GameObject::Use().
HandleGetChannelMemberCountOpcode()
void WorldSession::HandleGetChannelMemberCountOpcode (WorldPacket & recvPacket)
Definition at line 328 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Player::GetTeam(), SendPacket(), and SMSG_CHANNEL_MEMBER_COUNT.
HandleGetMirrorimageData()
void WorldSession::HandleGetMirrorimageData (WorldPacket & recv_data)
Definition at line 705 of file SpellHandler.cpp.
References _player, DEBUG_FILTER_LOG, EQUIPMENT_SLOT_BACK, EQUIPMENT_SLOT_BODY, EQUIPMENT_SLOT_CHEST, EQUIPMENT_SLOT_FEET, EQUIPMENT_SLOT_HANDS, EQUIPMENT_SLOT_HEAD, EQUIPMENT_SLOT_LEGS, EQUIPMENT_SLOT_SHOULDERS, EQUIPMENT_SLOT_TABARD, EQUIPMENT_SLOT_WAIST, EQUIPMENT_SLOT_WRISTS, Map::GetAnyTypeCreature(), Unit::GetAurasByType(), Object::GetByteValue(), Unit::getClass(), Unit::GetDisplayId(), Unit::getGender(), Player::GetGuildId(), Player::GetItemDisplayIdInSlot(), WorldObject::GetMap(), Creature::getRace(), Object::GetTypeId(), Object::HasFlag(), INVENTORY_SLOT_BAG_0, LOG_FILTER_SPELL_CAST, PLAYER_BYTES, PLAYER_BYTES_2, PLAYER_FLAGS, PLAYER_FLAGS_HIDE_CLOAK, PLAYER_FLAGS_HIDE_HELM, SendPacket(), SMSG_MIRRORIMAGE_DATA, SPELL_AURA_MIRROR_IMAGE, and TYPEID_PLAYER.
HandleGMResponseResolveOpcode()
void WorldSession::HandleGMResponseResolveOpcode (WorldPacket & recv_data)
Definition at line 316 of file GMTicketHandler.cpp.
References GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, SendGMTicketResponseError(), SendGMTicketResponseResolve(), and sTicketMgr.
HandleGMSurveySubmitOpcode()
void WorldSession::HandleGMSurveySubmitOpcode (WorldPacket & recvPacket)
Definition at line 192 of file GMTicketHandler.cpp.
References CheckChatMessage(), GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, GMTICKET_STATE_CLOSED, m_sessionDbcLocale, m_ticketSquelchTimer, MAX_GMSURVEY_QUESTIONS, ShortTimeTracker::Passed(), GMSurveyEntry::questionID, ByteBuffer::read_skip(), ShortTimeTracker::Reset(), sGMSurveyAnswersStore, sGMSurveyCurrentSurveyStore, sGMSurveySurveysStore, ByteBuffer::size(), sTicketMgr, GMSurveyCurrentSurveyEntry::surveyID, and utf8limit().
HandleGMTicketCreateOpcode()
void WorldSession::HandleGMTicketCreateOpcode (WorldPacket & recvPacket)
Definition at line 70 of file GMTicketHandler.cpp.
References CheckChatMessage(), Object::GetObjectGuid(), GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, GMTICKET_RESPONSE_ALREADY_EXIST, GMTICKET_RESPONSE_CREATE_ERROR, GMTICKET_RESPONSE_CREATE_SUCCESS, GMTICKET_STATE_ABANDONED, m_ticketSquelchTimer, ShortTimeTracker::Passed(), ByteBuffer::read_skip(), ShortTimeTracker::Reset(), ByteBuffer::rpos(), SendGMTicketResult(), ByteBuffer::size(), SMSG_GMTICKET_CREATE, and sTicketMgr.
HandleGMTicketDeleteTicketOpcode()
void WorldSession::HandleGMTicketDeleteTicketOpcode (WorldPacket & recvPacket)
Definition at line 178 of file GMTicketHandler.cpp.
References GMTicketMgr::COMMAND_RESULT_SUCCESS, GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, GMTICKET_RESPONSE_NOT_EXIST, GMTICKET_RESPONSE_TICKET_DELETED, SendGMTicketResult(), SMSG_GMTICKET_DELETETICKET, and sTicketMgr.
HandleGMTicketGetTicketOpcode()
void WorldSession::HandleGMTicketGetTicketOpcode (WorldPacket & recvPacket)
Definition at line 59 of file GMTicketHandler.cpp.
References GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, GMTICKET_STATUS_DEFAULT, SendGMTicket(), SendGMTicketResult(), SMSG_GMTICKET_GETTICKET, and sTicketMgr.
HandleGMTicketSystemStatusOpcode()
void WorldSession::HandleGMTicketSystemStatusOpcode (WorldPacket & recvPacket)
Definition at line 54 of file GMTicketHandler.cpp.
References SendGMTicketResult(), SMSG_GMTICKET_SYSTEMSTATUS, and sTicketMgr.
HandleGMTicketUpdateTextOpcode()
void WorldSession::HandleGMTicketUpdateTextOpcode (WorldPacket & recvPacket)
Definition at line 151 of file GMTicketHandler.cpp.
References CheckChatMessage(), GMTicketMgr::COMMAND_RESULT_SUCCESS, GetPlayer(), GMTICKET_QUEUE_STATUS_ENABLED, GMTICKET_RESPONSE_UPDATE_ERROR, GMTICKET_RESPONSE_UPDATE_SUCCESS, m_ticketSquelchTimer, ShortTimeTracker::Passed(), ByteBuffer::read_skip(), ShortTimeTracker::Reset(), SendGMTicketResult(), ByteBuffer::size(), SMSG_GMTICKET_CREATE, SMSG_GMTICKET_UPDATETEXT, and sTicketMgr.
HandleGossipHelloOpcode()
void WorldSession::HandleGossipHelloOpcode (WorldPacket & recvPacket)
Definition at line 316 of file NPCHandler.cpp.
References _player, DEBUG_LOG, Creature::GetDefaultGossipMenuId(), Creature::GetInteractionPauseTimer(), Unit::GetMotionMaster(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), Unit::isSpiritGuide(), MotionMaster::PauseWaypoints(), Player::PrepareGossipMenu(), Creature::SendAreaSpiritHealerQueryOpcode(), Player::SendPreparedGossip(), sScriptDevAIMgr, and UNIT_NPC_FLAG_NONE.
HandleGossipSelectOptionOpcode()
void WorldSession::HandleGossipSelectOptionOpcode (WorldPacket & recvPacket)
Definition at line 344 of file NPCHandler.cpp.
References _player, DEBUG_LOG, Player::GetGameObjectIfCanInteractWith(), Player::GetNPCIfCanInteractWith(), GetPlayer(), Player::GetPlayerMenu(), ObjectGuid::GetString(), PlayerMenu::GossipOptionAction(), PlayerMenu::GossipOptionCoded(), PlayerMenu::GossipOptionSender(), ObjectGuid::IsAnyTypeCreature(), ObjectGuid::IsGameObject(), Player::OnGossipSelect(), sScriptDevAIMgr, and UNIT_NPC_FLAG_NONE.
HandleGrantLevel()
void WorldSession::HandleGrantLevel (WorldPacket & recv_data)
Definition at line 27 of file RafHandler.cpp.
References _player, CONFIG_UINT32_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL, DEBUG_LOG, ERR_REFER_A_FRIEND_DIFFERENT_FACTION, ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I, ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS, ERR_REFER_A_FRIEND_NO_TARGET, ERR_REFER_A_FRIEND_NOT_IN_GROUP, ERR_REFER_A_FRIEND_NOT_REFERRED_BY, ERR_REFER_A_FRIEND_TARGET_TOO_HIGH, GetAccountId(), Player::GetGrantableLevels(), Player::GetGroup(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetName(), Object::GetPackGUID(), Map::GetPlayer(), GetRecruitingFriendId(), Player::GetSession(), Player::GetTeam(), IsARecruiter(), ObjectGuid::ReadAsPacked(), Player::SendDirectMessage(), SendPacket(), SMSG_PROPOSE_LEVEL_GRANT, SMSG_REFER_A_FRIEND_FAILURE, and sWorld.
HandleGroupAcceptOpcode()
void WorldSession::HandleGroupAcceptOpcode (WorldPacket & recvPacket)
error handling
Definition at line 208 of file GroupHandler.cpp.
References Group::AddMember(), Group::Create(), ERR_GROUP_FULL, Player::GetGroupInvite(), Group::GetLeaderGuid(), Group::GetLeaderName(), GetPlayer(), Group::IsCreated(), Group::IsFull(), PARTY_OP_INVITE, Group::RemoveInvite(), SendPartyResult(), sLog, and sObjectMgr.
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleGroupAssistantLeaderOpcode()
void WorldSession::HandleGroupAssistantLeaderOpcode (WorldPacket & recv_data)
error handling
Definition at line 555 of file GroupHandler.cpp.
References Player::GetGroup(), GetPlayer(), Group::IsLeader(), and Group::SetAssistant().
HandleGroupChangeSubGroupOpcode()
void WorldSession::HandleGroupChangeSubGroupOpcode (WorldPacket & recv_data)
error handling
Definition at line 520 of file GroupHandler.cpp.
References Group::ChangeMembersGroup(), Player::GetGroup(), GetPlayer(), Group::HasFreeSlotSubGroup(), Group::IsAssistant(), Group::IsLeader(), MAX_RAID_SUBGROUPS, and sObjectMgr.
HandleGroupDeclineOpcode()
void WorldSession::HandleGroupDeclineOpcode (WorldPacket & recvPacket)
Definition at line 255 of file GroupHandler.cpp.
References Player::GetGroupInvite(), Group::GetLeaderGuid(), WorldObject::GetName(), GetPlayer(), Player::GetSession(), SendPacket(), SMSG_GROUP_DECLINE, sObjectMgr, and Player::UninviteFromGroup().
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleGroupDisbandOpcode()
void WorldSession::HandleGroupDisbandOpcode (WorldPacket & recvPacket)
error handling
Definition at line 391 of file GroupHandler.cpp.
References Group::Disband(), ERR_INVITE_RESTRICTED, ERR_PARTY_RESULT_OK, Player::GetGroup(), Player::GetGroupInvite(), Group::GetLeaderGuid(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), Player::InBattleGround(), PARTY_OP_INVITE, PARTY_OP_LEAVE, Player::RemoveFromGroup(), and SendPartyResult().
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleGroupInviteOpcode()
void WorldSession::HandleGroupInviteOpcode (WorldPacket & recvPacket)
Definition at line 71 of file GroupHandler.cpp.
References Group::AddInvite(), Group::AddLeaderInvite(), CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GROUP, CONFIG_UINT32_MIN_LEVEL_FOR_RAID, ERR_ALREADY_IN_GROUP_S, ERR_BAD_PLAYER_NAME_S, ERR_GROUP_FULL, ERR_IGNORING_YOU_S, ERR_NOT_LEADER, ERR_PARTY_RESULT_OK, ERR_PLAYER_WRONG_FACTION, ERR_RAID_DISALLOWED_BY_LEVEL, ERR_TARGET_NOT_IN_INSTANCE_S, Player::GetAllowLowLevelRaid(), GetAnticheat(), Player::GetGroup(), Player::GetGroupInvite(), WorldObject::GetInstanceId(), Unit::GetLevel(), WorldObject::GetMapId(), Object::GetObjectGuid(), Player::GetOriginalGroup(), GetPlayer(), Player::GetSocial(), Player::GetTeam(), PlayerSocial::HasIgnore(), Group::IsAssistant(), Group::IsBattleGroup(), Group::IsCreated(), Group::IsFull(), Group::IsLeader(), Group::IsRaidGroup(), normalizePlayerName(), PARTY_OP_INVITE, SessionAnticheatInterface::PartyInvite(), ByteBuffer::read_skip(), Group::RemoveAllInvites(), SendGroupInvite(), SendPartyResult(), sObjectMgr, and sWorld.
HandleGroupRaidConvertOpcode()
void WorldSession::HandleGroupRaidConvertOpcode (WorldPacket & recv_data)
error handling
Definition at line 501 of file GroupHandler.cpp.
References _player, Group::ConvertToRaid(), ERR_PARTY_RESULT_OK, Player::GetGroup(), Group::GetMembersCount(), Group::GetMembersMinCount(), GetPlayer(), Player::InBattleGround(), Group::IsLeader(), PARTY_OP_INVITE, and SendPartyResult().
HandleGroupSetLeaderOpcode()
void WorldSession::HandleGroupSetLeaderOpcode (WorldPacket & recvPacket)
error handling
Definition at line 371 of file GroupHandler.cpp.
References Group::ChangeLeader(), Player::GetGroup(), GetPlayer(), Group::IsLeader(), and sObjectMgr.
Referenced by PlayerbotAI::HandleBotOutgoingPacket().
HandleGroupSwapSubGroupOpcode()
void WorldSession::HandleGroupSwapSubGroupOpcode (WorldPacket & recv_data)
Definition at line 967 of file GroupHandler.cpp.
References Group::ChangeMembersGroup(), Player::GetGroup(), Group::GetMemberSlots(), Object::GetObjectGuid(), GetPlayer(), Group::IsAssistant(), Group::IsLeader(), and Group::IsRaidGroup().
HandleGroupUninviteGuidOpcode()
void WorldSession::HandleGroupUninviteGuidOpcode (WorldPacket & recvPacket)
Definition at line 276 of file GroupHandler.cpp.
References Player::CanUninviteFromGroup(), ERR_NOT_LEADER, ERR_PARTY_RESULT_OK, ERR_TARGET_NOT_IN_GROUP_S, Player::GetGroup(), Object::GetGuidStr(), Group::GetInvited(), Object::GetObjectGuid(), GetPlayer(), Group::IsLeader(), Group::IsMember(), PARTY_OP_LEAVE, ByteBuffer::read_skip(), Player::RemoveFromGroup(), SendPartyResult(), and sLog.
HandleGroupUninviteOpcode()
void WorldSession::HandleGroupUninviteOpcode (WorldPacket & recvPacket)
Definition at line 322 of file GroupHandler.cpp.
References Player::CanUninviteFromGroup(), ERR_NOT_LEADER, ERR_PARTY_RESULT_OK, ERR_TARGET_NOT_IN_GROUP_S, Player::GetGroup(), Group::GetInvited(), Group::GetLeaderName(), Group::GetMemberGuid(), GetPlayer(), normalizePlayerName(), PARTY_OP_LEAVE, Player::RemoveFromGroup(), SendPartyResult(), and sLog.
HandleGuildAcceptOpcode()
void WorldSession::HandleGuildAcceptOpcode (WorldPacket & recvPacket)
Definition at line 194 of file GuildHandler.cpp.
References Guild::AddMember(), Guild::BroadcastEvent(), CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, DEBUG_LOG, GE_JOINED, Player::GetGuildId(), Player::GetGuildIdInvited(), Guild::GetLeaderGuid(), Guild::GetLowestRank(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), Player::GetTeam(), GUILD_EVENT_LOG_JOIN_GUILD, Guild::LogGuildEvent(), sGuildMgr, sObjectMgr, and sWorld.
HandleGuildAddRankOpcode()
void WorldSession::HandleGuildAddRankOpcode (WorldPacket & recvPacket)
Definition at line 648 of file GuildHandler.cpp.
References Guild::CreateRank(), DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, Guild::GetLeaderGuid(), GetPlayer(), Guild::GetRanksSize(), GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, GUILD_CREATE_S, GUILD_INVITE_S, GUILD_RANKS_MAX_COUNT, Guild::Query(), Guild::Roster(), SendGuildCommandResult(), and sGuildMgr.
HandleGuildBankBuyTab()
void WorldSession::HandleGuildBankBuyTab (WorldPacket & recv_data)
Definition at line 1097 of file GuildHandler.cpp.
References Guild::CreateNewBankTab(), DEBUG_LOG, Guild::DisplayGuildBankTabsInfo(), GAMEOBJECT_TYPE_GUILD_BANK, GetGuildBankTabPrice(), Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), GOLD, GUILD_BANK_RIGHT_FULL, Player::ModifyMoney(), Guild::Roster(), Guild::SetBankRightsAndSlots(), sGuildMgr, and WITHDRAW_SLOT_UNLIMITED.
HandleGuildBankDepositMoney()
void WorldSession::HandleGuildBankDepositMoney (WorldPacket & recv_data)
Definition at line 886 of file GuildHandler.cpp.
References _player, Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, DEBUG_LOG, Guild::DisplayGuildBankContent(), Guild::DisplayGuildBankMoneyUpdate(), Guild::DisplayGuildBankTabsInfo(), GAMEOBJECT_TYPE_GUILD_BANK, GetAccountId(), Guild::GetGuildBankMoney(), Player::GetGuildId(), WorldObject::GetName(), GetPlayer(), Guild::GetPurchasedTabs(), GetSecurity(), Player::GetSession(), GUILD_BANK_LOG_DEPOSIT_MONEY, Guild::LogBankEvent(), Player::ModifyMoney(), Player::SaveGoldToDB(), SEC_PLAYER, Guild::SetBankMoney(), sGuildMgr, sLog, and sWorld.
HandleGuildBankerActivate()
void WorldSession::HandleGuildBankerActivate (WorldPacket & recv_data)
Definition at line 834 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PLAYER_NOT_IN_GUILD, GAMEOBJECT_TYPE_GUILD_BANK, GetPlayer(), GUILD_UNK1, SendGuildCommandResult(), and sGuildMgr.
HandleGuildBankLogQuery()
void WorldSession::HandleGuildBankLogQuery (WorldPacket & recv_data)
Definition at line 1176 of file GuildHandler.cpp.
References DEBUG_LOG, Guild::DisplayGuildBankLogs(), Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), GUILD_BANK_MAX_TABS, and sGuildMgr.
HandleGuildBankMoneyWithdrawn()
void WorldSession::HandleGuildBankMoneyWithdrawn (WorldPacket & recv_data)
Definition at line 796 of file GuildHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sGuildMgr.
HandleGuildBankQueryTab()
void WorldSession::HandleGuildBankQueryTab (WorldPacket & recv_data)
Definition at line 858 of file GuildHandler.cpp.
References DEBUG_LOG, Guild::DisplayGuildBankContent(), GAMEOBJECT_TYPE_GUILD_BANK, Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), Guild::SendMoneyInfo(), and sGuildMgr.
HandleGuildBankSwapItems()
void WorldSession::HandleGuildBankSwapItems (WorldPacket & recv_data)
Definition at line 990 of file GuildHandler.cpp.
References _player, DEBUG_LOG, EQUIP_ERR_NONE, GAMEOBJECT_TYPE_GUILD_BANK, Player::GetGameObjectIfCanInteractWith(), Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), GUILD_BANK_MAX_SLOTS, Player::IsInventoryPos(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), NULL_BAG, NULL_SLOT, ByteBuffer::read_skip(), ByteBuffer::rpos(), Player::SendEquipError(), sGuildMgr, Guild::SwapItems(), and ByteBuffer::wpos().
HandleGuildBankUpdateTab()
void WorldSession::HandleGuildBankUpdateTab (WorldPacket & recv_data)
Definition at line 1137 of file GuildHandler.cpp.
References DEBUG_LOG, Guild::DisplayGuildBankContent(), Guild::DisplayGuildBankTabsInfo(), GAMEOBJECT_TYPE_GUILD_BANK, Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), Guild::SetGuildBankTabInfo(), and sGuildMgr.
HandleGuildBankWithdrawMoney()
void WorldSession::HandleGuildBankWithdrawMoney (WorldPacket & recv_data)
Definition at line 937 of file GuildHandler.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), DEBUG_LOG, Guild::DisplayGuildBankContent(), Guild::DisplayGuildBankMoneyUpdate(), Guild::DisplayGuildBankTabsInfo(), GAMEOBJECT_TYPE_GUILD_BANK, Guild::GetGuildBankMoney(), Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), GR_RIGHT_WITHDRAW_GOLD, GUILD_BANK_LOG_WITHDRAW_MONEY, Guild::HasRankRight(), Guild::LogBankEvent(), Guild::MemberMoneyWithdraw(), Player::ModifyMoney(), Database::RollbackTransaction(), Player::SaveGoldToDB(), Guild::SendMoneyInfo(), and sGuildMgr.
HandleGuildChangeInfoTextOpcode()
void WorldSession::HandleGuildChangeInfoTextOpcode (WorldPacket & recvPacket)
Definition at line 711 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, GetPlayer(), GR_RIGHT_MODIFY_GUILD_INFO, GUILD_CREATE_S, Guild::HasRankRight(), SendGuildCommandResult(), Guild::SetGINFO(), and sGuildMgr.
HandleGuildCreateOpcode()
void WorldSession::HandleGuildCreateOpcode (WorldPacket & recvPacket)
Definition at line 47 of file GuildHandler.cpp.
References Guild::Create(), DEBUG_LOG, GetPlayer(), and sGuildMgr.
HandleGuildDeclineOpcode()
void WorldSession::HandleGuildDeclineOpcode (WorldPacket & recvPacket)
Definition at line 216 of file GuildHandler.cpp.
References _player, DEBUG_LOG, ObjectAccessor::FindPlayer(), Player::GetGuildId(), Player::GetGuildIdInvited(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), ObjectGuid::IsEmpty(), Player::SetGuildIdInvited(), sGuildMgr, and SMSG_GUILD_DECLINE.
HandleGuildDelRankOpcode()
void WorldSession::HandleGuildDelRankOpcode (WorldPacket & recvPacket)
Definition at line 677 of file GuildHandler.cpp.
References DEBUG_LOG, Guild::DelRank(), ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, Guild::GetLeaderGuid(), GetPlayer(), GUILD_CREATE_S, GUILD_INVITE_S, Guild::Query(), Guild::Roster(), SendGuildCommandResult(), and sGuildMgr.
HandleGuildDemoteOpcode()
void WorldSession::HandleGuildDemoteOpcode (WorldPacket & recvPacket)
Definition at line 322 of file GuildHandler.cpp.
References _player, Guild::BroadcastEvent(), MemberSlot::ChangeRank(), DEBUG_LOG, ERR_GUILD_NAME_INVALID, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, ERR_GUILD_RANK_TOO_HIGH_S, ERR_GUILD_RANK_TOO_LOW_S, GE_DEMOTION, Guild::GetLowestRank(), Guild::GetMemberSlot(), WorldObject::GetName(), GetPlayer(), Guild::GetRankName(), GR_RIGHT_DEMOTE, MemberSlot::guid, GUILD_CREATE_S, GUILD_EVENT_LOG_DEMOTE_PLAYER, GUILD_INVITE_S, Guild::HasRankRight(), Guild::LogGuildEvent(), normalizePlayerName(), MemberSlot::RankId, SendGuildCommandResult(), and sGuildMgr.
HandleGuildDisbandOpcode()
void WorldSession::HandleGuildDisbandOpcode (WorldPacket & recvPacket)
Definition at line 424 of file GuildHandler.cpp.
References DEBUG_LOG, Guild::Disband(), ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, Guild::GetLeaderGuid(), GetPlayer(), GUILD_CREATE_S, GUILD_INVITE_S, SendGuildCommandResult(), and sGuildMgr.
HandleGuildEventLogQueryOpcode()
void WorldSession::HandleGuildEventLogQueryOpcode (WorldPacket & recvPacket)
Definition at line 784 of file GuildHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sGuildMgr.
HandleGuildInfoOpcode()
void WorldSession::HandleGuildInfoOpcode (WorldPacket & recvPacket)
Definition at line 242 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PLAYER_NOT_IN_GUILD, Guild::GetAccountsNumber(), Guild::GetCreatedDate(), Guild::GetMemberSize(), Guild::GetName(), GetPlayer(), GUILD_CREATE_S, secsToTimeBitFields(), SendGuildCommandResult(), SendPacket(), sGuildMgr, and SMSG_GUILD_INFO.
HandleGuildInviteOpcode()
void WorldSession::HandleGuildInviteOpcode (WorldPacket & recvPacket)
Definition at line 67 of file GuildHandler.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, DEBUG_LOG, ERR_ALREADY_IN_GUILD_S, ERR_ALREADY_INVITED_TO_GUILD_S, ERR_GUILD_NOT_ALLIED, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_FOUND_S, ERR_GUILD_PLAYER_NOT_IN_GUILD, ObjectAccessor::FindPlayerByName(), Player::GetGuildId(), Player::GetGuildIdInvited(), WorldObject::GetName(), Guild::GetName(), Object::GetObjectGuid(), GetPlayer(), Player::GetSession(), Player::GetSocial(), Player::GetTeam(), GR_RIGHT_INVITE, GUILD_CREATE_S, GUILD_EVENT_LOG_INVITE_PLAYER, GUILD_INVITE_S, PlayerSocial::HasIgnore(), Guild::HasRankRight(), Guild::LogGuildEvent(), normalizePlayerName(), SendGuildCommandResult(), SendPacket(), Player::SetGuildIdInvited(), sGuildMgr, SMSG_GUILD_INVITE, and sWorld.
HandleGuildLeaderOpcode()
void WorldSession::HandleGuildLeaderOpcode (WorldPacket & recvPacket)
Definition at line 447 of file GuildHandler.cpp.
References Guild::BroadcastEvent(), MemberSlot::ChangeRank(), DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, GE_LEADER_CHANGED, Player::GetGuildId(), Guild::GetLeaderGuid(), Guild::GetMemberSlot(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), GR_OFFICER, MemberSlot::guid, GUILD_CREATE_S, GUILD_INVITE_S, normalizePlayerName(), SendGuildCommandResult(), Guild::SetLeader(), and sGuildMgr.
HandleGuildLeaveOpcode()
void WorldSession::HandleGuildLeaveOpcode (WorldPacket & recvPacket)
Definition at line 383 of file GuildHandler.cpp.
References _player, Guild::BroadcastEvent(), DEBUG_LOG, Guild::DelMember(), Guild::Disband(), ERR_GUILD_LEADER_LEAVE, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_PLAYER_NO_MORE_IN_GUILD, GE_LEFT, Player::GetGuildId(), Guild::GetId(), Guild::GetLeaderGuid(), Guild::GetMemberSize(), WorldObject::GetName(), Guild::GetName(), Object::GetObjectGuid(), GUILD_CREATE_S, GUILD_EVENT_LOG_LEAVE_GUILD, GUILD_QUIT_S, Guild::LogGuildEvent(), sCalendarMgr, SendGuildCommandResult(), and sGuildMgr.
HandleGuildMOTDOpcode()
void WorldSession::HandleGuildMOTDOpcode (WorldPacket & recvPacket)
Definition at line 493 of file GuildHandler.cpp.
References Guild::BroadcastEvent(), ByteBuffer::clear(), DEBUG_LOG, ByteBuffer::empty(), ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, GE_MOTD, GetPlayer(), GR_RIGHT_SETMOTD, GUILD_CREATE_S, GUILD_INVITE_S, Guild::HasRankRight(), SendGuildCommandResult(), Guild::SetMOTD(), and sGuildMgr.
HandleGuildPermissions()
void WorldSession::HandleGuildPermissions (WorldPacket & recv_data)
Definition at line 805 of file GuildHandler.cpp.
References DEBUG_LOG, GetPlayer(), Player::GetRank(), GUILD_BANK_MAX_TABS, MSG_GUILD_PERMISSIONS, SendPacket(), and sGuildMgr.
HandleGuildPromoteOpcode()
void WorldSession::HandleGuildPromoteOpcode (WorldPacket & recvPacket)
Definition at line 269 of file GuildHandler.cpp.
References _player, Guild::BroadcastEvent(), MemberSlot::ChangeRank(), DEBUG_LOG, ERR_GUILD_NAME_INVALID, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, ERR_GUILD_RANK_TOO_HIGH_S, GE_PROMOTION, Guild::GetMemberSlot(), WorldObject::GetName(), GetPlayer(), Guild::GetRankName(), GR_RIGHT_PROMOTE, MemberSlot::guid, GUILD_CREATE_S, GUILD_EVENT_LOG_PROMOTE_PLAYER, GUILD_INVITE_S, Guild::HasRankRight(), Guild::LogGuildEvent(), normalizePlayerName(), MemberSlot::RankId, SendGuildCommandResult(), and sGuildMgr.
HandleGuildQueryOpcode()
void WorldSession::HandleGuildQueryOpcode (WorldPacket & recvPacket)
Definition at line 31 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PLAYER_NOT_IN_GUILD, GUILD_CREATE_S, SendGuildCommandResult(), and sGuildMgr.
HandleGuildRankOpcode()
void WorldSession::HandleGuildRankOpcode (WorldPacket & recvPacket)
Definition at line 596 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, Guild::GetLeaderGuid(), GetPlayer(), GR_GUILDMASTER, GR_RIGHT_ALL, GUILD_BANK_MAX_TABS, GUILD_CREATE_S, GUILD_INVITE_S, Guild::Query(), Guild::Roster(), ByteBuffer::rpos(), SendGuildCommandResult(), Guild::SetBankMoneyPerDay(), Guild::SetBankRightsAndSlots(), Guild::SetRankName(), Guild::SetRankRights(), sGuildMgr, and ByteBuffer::wpos().
HandleGuildRemoveOpcode()
void WorldSession::HandleGuildRemoveOpcode (WorldPacket & recvPacket)
Definition at line 137 of file GuildHandler.cpp.
References _player, Guild::BroadcastEvent(), DEBUG_LOG, Guild::DelMember(), Guild::Disband(), ERR_GUILD_LEADER_LEAVE, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, ERR_GUILD_RANK_TOO_HIGH_S, GE_REMOVED, Guild::GetMemberSlot(), WorldObject::GetName(), GetPlayer(), GR_GUILDMASTER, GR_RIGHT_REMOVE, MemberSlot::guid, GUILD_CREATE_S, GUILD_EVENT_LOG_UNINVITE_PLAYER, GUILD_INVITE_S, GUILD_QUIT_S, Guild::HasRankRight(), Guild::LogGuildEvent(), normalizePlayerName(), MemberSlot::RankId, SendGuildCommandResult(), and sGuildMgr.
HandleGuildRosterOpcode()
void WorldSession::HandleGuildRosterOpcode (WorldPacket & recvPacket)
Definition at line 261 of file GuildHandler.cpp.
References _player, DEBUG_LOG, Player::GetGuildId(), and sGuildMgr.
HandleGuildSetOfficerNoteOpcode()
void WorldSession::HandleGuildSetOfficerNoteOpcode (WorldPacket & recvPacket)
Definition at line 559 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, Guild::GetMemberSlot(), GetPlayer(), GR_RIGHT_EOFFNOTE, GUILD_CREATE_S, GUILD_INVITE_S, Guild::HasRankRight(), normalizePlayerName(), Guild::Roster(), SendGuildCommandResult(), MemberSlot::SetOFFNOTE(), and sGuildMgr.
HandleGuildSetPublicNoteOpcode()
void WorldSession::HandleGuildSetPublicNoteOpcode (WorldPacket & recvPacket)
Definition at line 521 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILD_PERMISSIONS, ERR_GUILD_PLAYER_NOT_IN_GUILD, ERR_GUILD_PLAYER_NOT_IN_GUILD_S, Guild::GetMemberSlot(), GetPlayer(), GR_RIGHT_EPNOTE, GUILD_CREATE_S, GUILD_INVITE_S, Guild::HasRankRight(), normalizePlayerName(), Guild::Roster(), SendGuildCommandResult(), MemberSlot::SetPNOTE(), and sGuildMgr.
HandleHearthandResurrect()
void WorldSession::HandleHearthandResurrect (WorldPacket & recv_data)
Definition at line 1534 of file MiscHandler.cpp.
References _player, AREA_FLAG_CAN_HEARTH_AND_RES, Player::BuildPlayerRepop(), DEBUG_LOG, AreaTableEntry::flags, WorldObject::GetAreaId(), Unit::IsTaxiFlying(), Player::ResurrectPlayer(), sAreaStore, and Player::TeleportToHomebind().
HandleIgnoreTradeOpcode()
void WorldSession::HandleIgnoreTradeOpcode (WorldPacket & recvPacket)
Definition at line 61 of file TradeHandler.cpp.
References _player, DEBUG_LOG, and Object::GetGUIDLow().
HandleInitiateTradeOpcode()
void WorldSession::HandleInitiateTradeOpcode (WorldPacket & recvPacket)
Definition at line 548 of file TradeHandler.cpp.
References _player, Unit::CanCooperate(), ObjectAccessor::FindPlayer(), Object::GetObjectGuid(), GetPlayer(), Player::GetSession(), Player::GetSocial(), Unit::HasCharmer(), PlayerSocial::HasIgnore(), Unit::IsAlive(), Player::IsInGroup(), isLogingOut(), Unit::IsStunned(), Unit::IsTaxiFlying(), WorldObject::IsWithinDistInMap(), Player::m_trade, SendTradeStatus(), TradeStatusInfo::Status, TRADE_DISTANCE, TRADE_STATUS_BEGIN_TRADE, TRADE_STATUS_BUSY, TRADE_STATUS_IGNORE_YOU, TRADE_STATUS_NO_TARGET, TRADE_STATUS_TARGET_DEAD, TRADE_STATUS_TARGET_LOGOUT, TRADE_STATUS_TARGET_STUNNED, TRADE_STATUS_TARGET_TO_FAR, TRADE_STATUS_WRONG_FACTION, TRADE_STATUS_YOU_DEAD, TRADE_STATUS_YOU_LOGOUT, TRADE_STATUS_YOU_STUNNED, and TradeStatusInfo::TraderGuid.
HandleInspectArenaTeamsOpcode()
void WorldSession::HandleInspectArenaTeamsOpcode (WorldPacket & recv_data)
Definition at line 28 of file ArenaTeamHandler.cpp.
References _player, Unit::CanAttack(), DEBUG_LOG, Player::GetArenaTeamId(), Object::GetObjectGuid(), ObjectGuid::GetString(), INSPECT_DISTANCE, WorldObject::IsWithinDistInMap(), MAX_ARENA_SLOT, and sObjectMgr.
HandleInspectHonorStatsOpcode()
void WorldSession::HandleInspectHonorStatsOpcode (WorldPacket & recvPacket)
Definition at line 1006 of file MiscHandler.cpp.
References _player, Unit::CanAttack(), Player::GetHighestPvPRankIndex(), Object::GetObjectGuid(), Object::GetUInt32Value(), INSPECT_DISTANCE, WorldObject::IsWithinDistInMap(), MSG_INSPECT_HONOR_STATS, PLAYER_FIELD_KILLS, PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, PLAYER_FIELD_TODAY_CONTRIBUTION, PLAYER_FIELD_YESTERDAY_CONTRIBUTION, SendPacket(), sLog, and sObjectMgr.
HandleInspectOpcode()
void WorldSession::HandleInspectOpcode (WorldPacket & recvPacket)
Definition at line 973 of file MiscHandler.cpp.
References _player, Player::BuildEnchantmentsInfoData(), Player::BuildPlayerTalentsInfoData(), Unit::CanAttack(), CONFIG_BOOL_TALENTS_INSPECTING, DEBUG_LOG, Object::GetPackGUID(), ObjectGuid::GetString(), INSPECT_DISTANCE, Player::IsGameMaster(), WorldObject::IsWithinDistInMap(), SendPacket(), SMSG_INSPECT_RESULTS, sObjectMgr, and sWorld.
HandleInstanceLockResponse()
void WorldSession::HandleInstanceLockResponse (WorldPacket & recv_data)
Definition at line 1619 of file MiscHandler.cpp.
References _player, Player::BindToInstance(), Object::GetGuidStr(), Player::HasPendingBind(), Player::RepopAtGraveyard(), Player::SetPendingBind(), and sLog.
HandleItemNameQueryOpcode()
void WorldSession::HandleItemNameQueryOpcode (WorldPacket & recvPacket)
Definition at line 1067 of file ItemHandler.cpp.
References DEBUG_LOG, ObjectMgr::GetItemPrototype(), GetSessionDbLocaleIndex(), ByteBuffer::read_skip(), SendPacket(), sItemStore, sLog, SMSG_ITEM_NAME_QUERY_RESPONSE, and sObjectMgr.
HandleItemQuerySingleOpcode()
void WorldSession::HandleItemQuerySingleOpcode (WorldPacket & recvPacket)
Definition at line 281 of file ItemHandler.cpp.
References ItemPrototype::AllowableClass, ItemPrototype::AllowableRace, ItemPrototype::AmmoType, ItemPrototype::ArcaneRes, ItemPrototype::Area, ItemPrototype::Armor, ItemPrototype::ArmorDamageModifier, ItemPrototype::BagFamily, ItemPrototype::Block, ItemPrototype::Bonding, ItemPrototype::BuyPrice, SpellEntry::Category, SpellEntry::CategoryRecoveryTime, ItemPrototype::Class, ItemPrototype::ContainerSlots, ItemPrototype::Damage, DEBUG_LOG, ItemPrototype::Delay, ItemPrototype::Description, DETAIL_LOG, ItemPrototype::DisplayInfoID, ItemPrototype::Duration, ItemPrototype::FireRes, ItemPrototype::Flags, ItemPrototype::Flags2, ItemPrototype::FrostRes, ItemPrototype::GemProperties, ObjectMgr::GetItemPrototype(), GetSessionDbLocaleIndex(), ItemPrototype::HolidayId, ItemPrototype::HolyRes, ItemPrototype::InventoryType, ItemPrototype::ItemId, ItemPrototype::ItemLevel, ItemPrototype::ItemLimitCategory, ItemPrototype::ItemSet, ItemPrototype::ItemStat, _ItemStat::ItemStatType, _ItemStat::ItemStatValue, ItemPrototype::LanguageID, ItemPrototype::LockID, SQLStorage::LookupEntry(), ItemPrototype::Map, ItemPrototype::Material, ItemPrototype::MaxCount, ItemPrototype::MaxDurability, ItemPrototype::Name1, ItemPrototype::NatureRes, ItemPrototype::PageMaterial, ItemPrototype::PageText, ItemPrototype::Quality, ItemPrototype::RandomProperty, ItemPrototype::RandomSuffix, ItemPrototype::RangedModRange, SpellEntry::RecoveryTime, ItemPrototype::RequiredCityRank, ItemPrototype::RequiredDisenchantSkill, ItemPrototype::RequiredHonorRank, ItemPrototype::RequiredLevel, ItemPrototype::RequiredReputationFaction, ItemPrototype::RequiredReputationRank, ItemPrototype::RequiredSkill, ItemPrototype::RequiredSkillRank, ItemPrototype::RequiredSpell, ItemPrototype::ScalingStatDistribution, ItemPrototype::ScalingStatValue, ItemPrototype::SellPrice, SendPacket(), ItemPrototype::ShadowRes, ItemPrototype::Sheath, SMSG_ITEM_QUERY_SINGLE_RESPONSE, sObjectMgr, ItemPrototype::Socket, ItemPrototype::socketBonus, ItemPrototype::Spells, sSpellTemplate, ItemPrototype::Stackable, ItemPrototype::StartQuest, ItemPrototype::StatsCount, ItemPrototype::SubClass, ItemPrototype::TotemCategory, and ItemPrototype::Unk0.
HandleItemRefundInfoRequest()
void WorldSession::HandleItemRefundInfoRequest (WorldPacket & recv_data)
Definition at line 1448 of file ItemHandler.cpp.
References _player, DEBUG_LOG, ItemPrototype::Flags, Player::GetItemByGuid(), Item::GetProto(), and ITEM_FLAG_ITEMPURCHASE_RECORD.
HandleItemTextQuery()
void WorldSession::HandleItemTextQuery (WorldPacket & recv_data)
Handles the packet sent by the client when requesting information about item text.
This function is called when player clicks on item which has some flag set
Definition at line 1476 of file ItemHandler.cpp.
References _player, DEBUG_LOG, ObjectGuid::GetCounter(), Player::GetItemByGuid(), SendPacket(), and SMSG_ITEM_TEXT_QUERY_RESPONSE.
HandleJoinChannelOpcode()
void WorldSession::HandleJoinChannelOpcode (WorldPacket & recvPacket)
Definition at line 58 of file ChannelHandler.cpp.
References _player, channelMgr(), CheckChatChannelNameAndPassword(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleLearnPreviewTalents()
void WorldSession::HandleLearnPreviewTalents (WorldPacket & recvPacket)
Definition at line 39 of file SkillHandler.cpp.
References _player, Pet::CastOwnerTalentAuras(), DEBUG_LOG, Unit::GetPet(), Player::LearnTalent(), and Player::SendTalentsInfoData().
HandleLearnPreviewTalentsPet()
void WorldSession::HandleLearnPreviewTalentsPet (WorldPacket & recvPacket)
Definition at line 861 of file PetHandler.cpp.
References _player, DEBUG_LOG, Player::LearnPetTalent(), and Player::SendTalentsInfoData().
HandleLearnTalentOpcode()
void WorldSession::HandleLearnTalentOpcode (WorldPacket & recvPacket)
Definition at line 26 of file SkillHandler.cpp.
References _player, Pet::CastOwnerTalentAuras(), Unit::GetPet(), Player::LearnTalent(), and Player::SendTalentsInfoData().
HandleLeaveBattlefieldOpcode()
void WorldSession::HandleLeaveBattlefieldOpcode (WorldPacket & recv_data)
Definition at line 556 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, Player::GetBattleGround(), Unit::IsInCombat(), Player::LeaveBattleground(), ByteBuffer::read_skip(), and STATUS_WAIT_LEAVE.
HandleLeaveChannelOpcode()
void WorldSession::HandleLeaveChannelOpcode (WorldPacket & recvPacket)
Definition at line 82 of file ChannelHandler.cpp.
References _player, channelMgr(), DEBUG_LOG, WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and Player::GetTeam().
HandleLfgGetStatus()
void WorldSession::HandleLfgGetStatus (WorldPacket & recv_data)
Definition at line 206 of file LFGHandler.cpp.
HandleLfgJoinOpcode()
void WorldSession::HandleLfgJoinOpcode (WorldPacket & recv_data)
Definition at line 48 of file LFGHandler.cpp.
References DEBUG_LOG, GetPlayer(), ByteBuffer::read(), ByteBuffer::resize(), sLFGDungeonStore, and sLFGMgr.
HandleLfgLeaveOpcode()
void WorldSession::HandleLfgLeaveOpcode (WorldPacket & recv_data)
Definition at line 87 of file LFGHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sLFGMgr.
HandleLfgPartyLockInfoRequestOpcode()
void WorldSession::HandleLfgPartyLockInfoRequestOpcode (WorldPacket & recv_data)
Definition at line 287 of file LFGHandler.cpp.
References BuildPartyLockDungeonBlock(), DEBUG_LOG, Group::GetFirstMember(), Player::GetGroup(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), GroupReference::next(), SendPacket(), sLFGMgr, and SMSG_LFG_PARTY_INFO.
HandleLfgPlayerLockInfoRequestOpcode()
void WorldSession::HandleLfgPlayerLockInfoRequestOpcode (WorldPacket & recv_data)
Definition at line 219 of file LFGHandler.cpp.
References BuildPlayerLockDungeonBlock(), Player::CanRewardQuest(), DEBUG_LOG, ItemPrototype::DisplayInfoID, LfgReward::firstQuest, GetExpansion(), Unit::GetLevel(), GetPlayer(), Quest::GetRewItemsCount(), Quest::GetRewOrReqMoney(), Quest::GetXPReward(), LfgReward::otherQuest, QUEST_REWARDS_COUNT, Quest::RewItemCount, Quest::RewItemId, SendPacket(), sLFGMgr, SMSG_LFG_PLAYER_INFO, and sObjectMgr.
HandleLfgProposalResultOpcode()
void WorldSession::HandleLfgProposalResultOpcode (WorldPacket & recv_data)
Definition at line 94 of file LFGHandler.cpp.
References GetPlayer(), sWorld, and LFGQueue::UpdateProposal().
HandleLfgSetBootVoteOpcode()
void WorldSession::HandleLfgSetBootVoteOpcode (WorldPacket & recv_data)
Definition at line 172 of file LFGHandler.cpp.
HandleLfgSetCommentOpcode()
void WorldSession::HandleLfgSetCommentOpcode (WorldPacket & recv_data)
Definition at line 136 of file LFGHandler.cpp.
References DEBUG_LOG, Player::GetGroup(), Player::GetLfgData(), Object::GetObjectGuid(), GetPlayer(), LFGData::GetState(), LFG_STATE_RAIDBROWSER, LFGData::SetComment(), and sWorld.
HandleLfgSetRolesOpcode()
void WorldSession::HandleLfgSetRolesOpcode (WorldPacket & recv_data)
Definition at line 107 of file LFGHandler.cpp.
References Player::GetGroup(), Group::GetLfgData(), Group::GetObjectGuid(), GetPlayer(), World::GetRaidBrowser(), LFGData::GetState(), LFG_STATE_RAIDBROWSER, LFGQueue::SetPlayerRoles(), and sWorld.
HandleLfgTeleportOpcode()
void WorldSession::HandleLfgTeleportOpcode (WorldPacket & recv_data)
Definition at line 210 of file LFGHandler.cpp.
References GetPlayer(), and sLFGMgr.
HandleLfrJoinOpcode()
void WorldSession::HandleLfrJoinOpcode (WorldPacket & recv_data)
Definition at line 178 of file LFGHandler.cpp.
References DEBUG_LOG, GetPlayer(), World::GetRaidBrowser(), and sWorld.
HandleLfrLeaveOpcode()
void WorldSession::HandleLfrLeaveOpcode (WorldPacket & recv_data)
Definition at line 192 of file LFGHandler.cpp.
References DEBUG_LOG, GetPlayer(), World::GetRaidBrowser(), and sWorld.
HandleListInventoryOpcode()
void WorldSession::HandleListInventoryOpcode (WorldPacket & recvPacket)
Definition at line 713 of file ItemHandler.cpp.
References DEBUG_LOG, GetPlayer(), and SendListInventory().
HandleListStabledPetsOpcode()
void WorldSession::HandleListStabledPetsOpcode (WorldPacket & recvPacket)
Definition at line 482 of file NPCHandler.cpp.
References CheckStableMaster(), DEBUG_LOG, SendStablePet(), SendStableResult(), and STABLE_ERR_STABLE.
HandleLogoutCancelOpcode()
void WorldSession::HandleLogoutCancelOpcode (WorldPacket & recvPacket)
Definition at line 319 of file MiscHandler.cpp.
References DEBUG_LOG, GetPlayer(), LogoutRequest(), SendPacket(), Unit::SetStunnedByLogout(), and SMSG_LOGOUT_CANCEL_ACK.
HandleLogoutRequestOpcode()
void WorldSession::HandleLogoutRequestOpcode (WorldPacket & recvPacket)
Definition at line 277 of file MiscHandler.cpp.
References CONFIG_UINT32_INSTANT_LOGOUT, DEBUG_LOG, GetPlayer(), GetSecurity(), Player::HasMovementFlag(), LogoutPlayer(), LogoutRequest(), MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, PLAYER_FLAGS, PLAYER_FLAGS_RESTING, SendPacket(), Unit::SetStunnedByLogout(), SMSG_LOGOUT_RESPONSE, and sWorld.
HandleLootMasterGiveOpcode()
void WorldSession::HandleLootMasterGiveOpcode (WorldPacket & recvPacket)
Definition at line 166 of file LootHandler.cpp.
References _player, DEBUG_LOG, EQUIP_ERR_CANT_CARRY_MORE_OF_THIS, EQUIP_ERR_INVENTORY_FULL, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, ObjectAccessor::FindPlayer(), Object::GetGuidStr(), Loot::GetLootItemInSlot(), Loot::GetMasterLootGuid(), Object::GetObjectGuid(), LootItem::GetSlotTypeForSharedLoot(), ObjectGuid::GetString(), LootItem::IsAllowed(), Player::IsInGroup(), WorldObject::IsInMap(), LootItem::itemId, LOOT_ERROR_DIDNT_KILL, LOOT_ERROR_MASTER_INV_FULL, LOOT_ERROR_MASTER_OTHER, LOOT_ERROR_MASTER_UNIQUE_ITEM, LOOT_ERROR_PLAYER_NOT_FOUND, MAX_LOOT_SLOT_TYPE, Player::SendEquipError(), Loot::SendItem(), Player::SendLootError(), sLog, and sLootMgr.
HandleLootMethodOpcode()
void WorldSession::HandleLootMethodOpcode (WorldPacket & recvPacket)
error handling
Definition at line 239 of file LootHandler.cpp.
References Player::GetGroup(), GetPlayer(), Group::IsLeader(), Group::SendUpdate(), Group::SetLootMethod(), Group::SetLootThreshold(), and Group::SetMasterLooterGuid().
HandleLootMoneyOpcode()
void WorldSession::HandleLootMoneyOpcode (WorldPacket & recvPacket)
Definition at line 74 of file LootHandler.cpp.
References _player, DEBUG_LOG, Object::GetGuidStr(), Loot::SendGold(), sLog, and sLootMgr.
HandleLootOpcode()
void WorldSession::HandleLootOpcode (WorldPacket & recvPacket)
Definition at line 89 of file LootHandler.cpp.
References _player, DEBUG_LOG, DIST_CALC_NONE, Player::DoLoot(), Unit::GetCombatReach(), Map::GetGameObject(), WorldObject::GetMap(), GetPlayer(), Map::GetUnit(), Unit::InterruptNonMeleeSpells(), Unit::IsAlive(), ObjectGuid::IsGameObject(), Object::IsInWorld(), ObjectGuid::IsItem(), Unit::IsStandState(), Unit::IsStunned(), ObjectGuid::IsUnit(), LOOT_ERROR_NOTSTANDING, LOOT_ERROR_STUNNED, LOOT_ERROR_TOO_FAR, Player::SendLootError(), and sLootMgr.
HandleLootReleaseOpcode()
void WorldSession::HandleLootReleaseOpcode (WorldPacket & recvPacket)
Definition at line 155 of file LootHandler.cpp.
References _player, DEBUG_LOG, and sLootMgr.
HandleLootRoll()
void WorldSession::HandleLootRoll (WorldPacket & recv_data)
Definition at line 262 of file LootHandler.cpp.
References _player, Player::GetGroup(), GetPlayer(), ObjectGuid::GetString(), ROLL_NOT_EMITED_YET, sLog, and sLootMgr.
HandleMessagechatOpcode()
void WorldSession::HandleMessagechatOpcode (WorldPacket & recvPacket)
Definition at line 77 of file ChatHandler.cpp.
References _player, Player::autoReplyMsg, Group::BroadcastPacket(), ChatHandler::BuildChatPacket(), Player::CanSpeak(), channelMgr(), CHAT_MSG_AFK, CHAT_MSG_BATTLEGROUND, CHAT_MSG_BATTLEGROUND_LEADER, CHAT_MSG_CHANNEL, CHAT_MSG_DND, CHAT_MSG_EMOTE, CHAT_MSG_GUILD, CHAT_MSG_OFFICER, CHAT_MSG_PARTY, CHAT_MSG_PARTY_LEADER, CHAT_MSG_RAID, CHAT_MSG_RAID_LEADER, CHAT_MSG_RAID_WARNING, CHAT_MSG_SAY, CHAT_MSG_WHISPER, CHAT_MSG_YELL, CheckChatMessage(), CONFIG_BOOL_ADDON_CHANNEL, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHAT, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GROUP, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, CONFIG_BOOL_CHAT_RESTRICTED_RAID_WARNINGS, DEBUG_LOG, Unit::GetAurasByType(), Player::GetChatTag(), Player::GetGroup(), GetLanguageDescByID(), GetMangosString(), Group::GetMemberGroup(), WorldObject::GetName(), Object::GetObjectGuid(), Player::GetOriginalGroup(), GetPlayer(), GetSecurity(), Player::GetSession(), Player::GetTeam(), Player::HasSkill(), Player::isAcceptWhispers(), Player::isAFK(), Player::isAllowedWhisperFrom(), Group::IsAssistant(), Group::IsBattleGroup(), Player::isDND(), Player::isEnabledWhisperRestriction(), Player::IsGameMaster(), Group::IsLeader(), Group::IsRaidGroup(), LANG_ADDON, LANG_NOT_LEARNED_LANGUAGE, LANG_PLAYER_AFK_DEFAULT, LANG_PLAYER_DND_DEFAULT, LANG_UNIVERSAL, LANG_UNKNOWN_LANGUAGE, LANG_WAIT_BEFORE_SPEAKING, m_anticheat, m_muteTime, MAX_CHAT_MSG_TYPE, normalizePlayerName(), ChatHandler::PSendSysMessage(), ByteBuffer::read(), Player::Say(), SEC_PLAYER, secsToTimeString(), SendNotification(), SendPlayerNotFoundNotice(), SendWrongFactionNotice(), sGuildMgr, LanguageDesc::skill_id, sLog, sObjectMgr, SPELL_AURA_COMPREHEND_LANGUAGE, SPELL_AURA_MOD_LANGUAGE, sTicketMgr, sWorld, Player::TextEmote(), Player::ToggleAFK(), Player::ToggleDND(), Player::UpdateSpeakTime(), Player::Whisper(), and Player::Yell().
HandleMinimapPingOpcode()
void WorldSession::HandleMinimapPingOpcode (WorldPacket & recv_data)
error handling
Definition at line 422 of file GroupHandler.cpp.
References Group::BroadcastPacket(), Player::GetGroup(), Object::GetObjectGuid(), GetPlayer(), and MSG_MINIMAP_PING.
HandleMountSpecialAnimOpcode()
void WorldSession::HandleMountSpecialAnimOpcode (WorldPacket & recvdata)
Definition at line 504 of file MovementHandler.cpp.
References Object::GetObjectGuid(), GetPlayer(), Player::SendMessageToSet(), and SMSG_MOUNTSPECIAL_ANIM.
HandleMoveFlagChangeOpcode()
void WorldSession::HandleMoveFlagChangeOpcode (WorldPacket & recvPacket)
Definition at line 572 of file MovementHandler.cpp.
References _player, CMSG_MOVE_FEATHER_FALL_ACK, CMSG_MOVE_HOVER_ACK, CMSG_MOVE_SET_CAN_FLY_ACK, CMSG_MOVE_WATER_WALK_ACK, DEBUG_LOG, Player::GetMover(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), m_anticheat, MSG_MOVE_FEATHER_FALL, MSG_MOVE_HOVER, MSG_MOVE_UPDATE_CAN_FLY, MSG_MOVE_WATER_WALK, MSG_NULL_ACTION, ProcessMovementInfo(), ObjectGuid::ReadAsPacked(), WorldObject::SendMessageToSetExcept(), and ObjectGuid::WriteAsPacked().
HandleMoveKnockBackAck()
void WorldSession::HandleMoveKnockBackAck (WorldPacket & recvPacket)
Definition at line 514 of file MovementHandler.cpp.
References _player, MovementInfo::JumpInfo::cosAngle, DEBUG_LOG, Player::GetMover(), WorldPacket::GetOpcode(), Object::GetPackGUID(), Player::IsBeingTeleported(), Player::IsFreeFlying(), Object::IsPlayer(), MovementInfo::jump, m_anticheat, MSG_MOVE_KNOCK_BACK, ProcessMovementInfo(), ObjectGuid::ReadAsPacked(), ByteBuffer::rpos(), WorldObject::SendMessageToSetExcept(), Unit::SetCanFly(), MovementInfo::JumpInfo::sinAngle, ByteBuffer::size(), ByteBuffer::wpos(), MovementInfo::JumpInfo::xyspeed, and MovementInfo::JumpInfo::zspeed.
HandleMovementOpcodes()
void WorldSession::HandleMovementOpcodes (WorldPacket & recvPacket)
Definition at line 326 of file MovementHandler.cpp.
References _player, CMSG_MOVE_CHNG_TRANSPORT, CMSG_MOVE_FALL_RESET, DEBUG_LOG, Player::GetMover(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), Object::GetPackGUID(), Object::GetTypeId(), ByteBuffer::hexlike(), LOG_FILTER_PLAYER_MOVES, LookupOpcodeName(), ProcessMovementInfo(), WorldObject::SendMessageToSetExcept(), ByteBuffer::size(), sLog, TYPEID_PLAYER, and MovementInfo::Write().
Referenced by HandleClientCastFlags(), and HandleUpdateMissileTrajectory().
HandleMoveNotActiveMoverOpcode()
void WorldSession::HandleMoveNotActiveMoverOpcode (WorldPacket & recv_data)
Definition at line 479 of file MovementHandler.cpp.
References _player, DEBUG_LOG, Object::GetGuidStr(), Player::GetMover(), Object::GetObjectGuid(), ObjectGuid::GetString(), ByteBuffer::hexlike(), Unit::IsClientControlled(), Unit::IsTaxiFlying(), WorldObject::m_movementInfo, ObjectGuid::ReadAsPacked(), ByteBuffer::rpos(), sLog, and ByteBuffer::wpos().
HandleMoveRootAck()
void WorldSession::HandleMoveRootAck (WorldPacket & recvPacket)
Definition at line 610 of file MovementHandler.cpp.
References _player, CMSG_FORCE_MOVE_UNROOT_ACK, DEBUG_LOG, Player::GetMover(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), MovementInfo::HasMovementFlag(), m_anticheat, WorldObject::m_movementInfo, MOVEFLAG_ROOT, MSG_MOVE_ROOT, MSG_MOVE_UNROOT, ProcessMovementInfo(), ObjectGuid::ReadAsPacked(), WorldObject::SendMessageToSetExcept(), and ObjectGuid::WriteAsPacked().
HandleMoverRelocation()
void WorldSession::HandleMoverRelocation (MovementInfo & movementInfo) private
Definition at line 692 of file MovementHandler.cpp.
References _player, MovementInfo::ClearTransportData(), Map::CreatureRelocation(), DAMAGE_FALL_TO_VOID, WorldObject::GetMap(), Player::GetMover(), MovementInfo::GetPos(), Map::GetTransport(), MovementInfo::GetTransportGuid(), Object::GetTypeId(), Object::IsInWorld(), WorldObject::m_movementInfo, MOVEFLAG_ONTRANSPORT, Position::o, SynchronizeMovement(), TYPEID_PLAYER, Position::x, Position::y, and Position::z.
Referenced by ProcessMovementInfo().
HandleMoveSplineDoneOpcode()
void WorldSession::HandleMoveSplineDoneOpcode (WorldPacket & recvPacket)
Definition at line 181 of file TaxiHandler.cpp.
References DEBUG_LOG, and ObjectGuid::ReadAsPacked().
HandleMoveTeleportAckOpcode()
void WorldSession::HandleMoveTeleportAckOpcode (WorldPacket & recvPacket)
Definition at line 262 of file MovementHandler.cpp.
References _player, GenericTransport::AddPassenger(), Unit::CastSpell(), WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, DEBUG_LOG, WorldObject::GetMap(), Player::GetMover(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), GetPlayer(), ObjectGuid::GetString(), Player::GetTeleportDest(), Map::GetTransport(), Object::GetTypeId(), WorldObject::GetZoneAndAreaId(), WorldObject::GetZoneId(), IN_MILLISECONDS, PvPInfo::inPvPEnforcedArea, Player::IsBeingTeleportedNear(), m_anticheat, Player::m_teleportTransport, WorldLocation::orientation, Player::ProcessDelayedOperations(), Player::pvpInfo, ObjectGuid::ReadAsPacked(), Player::ResummonPetTemporaryUnSummonedIfAny(), Player::SetDelayedZoneUpdate(), Player::SetFallInformation(), Player::SetPosition(), Player::SetSemaphoreTeleportNear(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and Player::UpdateZone().
HandleMoveTimeSkippedOpcode()
void WorldSession::HandleMoveTimeSkippedOpcode (WorldPacket & recv_data)
Definition at line 753 of file MovementHandler.cpp.
References _player, MovementInfo::ctime, DEBUG_LOG, Player::GetMover(), Object::GetObjectGuid(), Object::GetPackGUID(), m_anticheat, WorldObject::m_movementInfo, MSG_MOVE_TIME_SKIPPED, ObjectGuid::ReadAsPacked(), WorldObject::SendMessageToSetExcept(), and MovementInfo::stime.
HandleMoveWorldportAckOpcode() [1/2]
void WorldSession::HandleMoveWorldportAckOpcode ()
Definition at line 48 of file MovementHandler.cpp.
References _player, Messager< T >::AddMessage(), AREA_LOCKSTATUS_OK, AURA_INTERRUPT_FLAG_ENTER_WORLD, BATTLEGROUND_TYPE_NONE, Unit::CastSpell(), WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, DETAIL_LOG, VehicleInfo::DisableAccessoryInit(), Player::GetBattleGround(), Player::GetBattleGroundId(), Player::GetDifficulty(), Group::GetDifficulty(), Player::GetGroup(), ObjectMgr::GetInstanceTemplate(), Map::GetMessager(), GetPlayer(), WorldObject::GetPosition(), Player::GetTeleportDest(), Map::GetTransport(), Unit::GetVehicleInfo(), GROUP_UPDATE_FULL, Player::InBattleGround(), MapEntry::IsBattleGroundOrArena(), Player::IsInvitedForBattleGroundInstance(), MapEntry::IsRaid(), MapManager::IsValidMapCoord(), Unit::IsVehicle(), KickPlayer(), m_anticheat, Player::m_InstanceValid, WorldObject::m_movementInfo, Player::m_teleportTransport, WorldLocation::mapid, InstanceTemplate::mountAllowed, WorldLocation::orientation, Player::ProcessDelayedOperations(), WorldObject::Relocate(), Unit::RemoveAurasWithInterruptFlags(), Unit::RemoveSpellsCausingAura(), Player::ResetMap(), Player::ResummonPetTemporaryUnSummonedIfAny(), Player::SendInitialPacketsAfterAddToMap(), Player::SendInitialPacketsBeforeAddToMap(), Player::SetBattleGroundId(), Player::SetBGTeam(), Player::SetGroupUpdateFlag(), WorldObject::SetMap(), Player::SetSemaphoreTeleportFar(), sLog, sMapMgr, sMapStore, sObjectMgr, SPELL_AURA_MOUNTED, MovementInfo::t_pos, Player::TaxiFlightInterrupt(), Player::TaxiFlightResume(), TEAM_NONE, Player::TeleportToHomebind(), and TRIGGERED_OLD_TRIGGERED.
Referenced by HandleMoveWorldportAckOpcode(), HandlePlayerLoginOpcode(), and LogoutPlayer().
HandleMoveWorldportAckOpcode() [2/2]
void WorldSession::HandleMoveWorldportAckOpcode (WorldPacket & recvPacket)
Definition at line 42 of file MovementHandler.cpp.
References DEBUG_LOG, and HandleMoveWorldportAckOpcode().
HandleNameQueryOpcode()
void WorldSession::HandleNameQueryOpcode (WorldPacket & recvPacket)
Definition at line 136 of file QueryHandler.cpp.
References CharacterNameQueryResponse::classid, CharacterNameQueryResponse::declined, CharacterNameQueryResponse::gender, Unit::getClass(), Player::GetDeclinedNames(), Unit::getGender(), WorldObject::GetName(), Object::GetObjectGuid(), Unit::getRace(), CharacterNameQueryResponse::guid, m_offlineNameQueries, m_offlineNameResponses, m_sessionState, MAX_DECLINED_NAME_CASES, DeclinedName::name, CharacterNameQueryResponse::name, CharacterNameQueryResponse::race, CharacterNameQueryResponse::realm, SendNameQueryResponse(), SendNameQueryResponseFromDB(), sObjectMgr, and WORLD_SESSION_STATE_READY.
HandleNextCinematicCamera()
void WorldSession::HandleNextCinematicCamera (WorldPacket & recvPacket)
Definition at line 938 of file MiscHandler.cpp.
References DEBUG_LOG, GetPlayer(), and Player::StartCinematic().
HandleNpcTextQueryOpcode()
void WorldSession::HandleNpcTextQueryOpcode (WorldPacket & recvPacket)
Definition at line 345 of file QueryHandler.cpp.
References GossipTextOption::broadcastTextId, DEBUG_LOG, DETAIL_LOG, GossipTextOption::Emotes, GENDER_FEMALE, GENDER_MALE, GetSessionDbLocaleIndex(), GossipTextOption::Language, MAX_GOSSIP_TEXT_OPTIONS, GossipText::Options, GossipTextOption::Probability, SendPacket(), SMSG_NPC_TEXT_UPDATE, sObjectMgr, GossipTextOption::Text_0, and GossipTextOption::Text_1.
HandleOfferPetitionOpcode()
void WorldSession::HandleOfferPetitionOpcode (WorldPacket & recv_data)
Get petition type and check
Get petition signs count
Send response
Definition at line 606 of file PetitionsHandler.cpp.
References _player, CharacterDatabase, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, ERR_ALREADY_IN_ARENA_TEAM_S, ERR_ALREADY_IN_GUILD_S, ERR_ALREADY_INVITED_TO_ARENA_TEAM_S, ERR_ALREADY_INVITED_TO_GUILD_S, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_INVITE_SS, ERR_ARENA_TEAM_NOT_ALLIED, ERR_ARENA_TEAM_TARGET_TOO_LOW_S, ERR_GUILD_NOT_ALLIED, QueryResult::Fetch(), ObjectAccessor::FindPlayer(), Player::GetArenaTeamId(), Player::GetArenaTeamIdInvited(), ObjectGuid::GetCounter(), Player::GetGuildId(), Player::GetGuildIdInvited(), Unit::GetLevel(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), QueryResult::GetRowCount(), Player::GetSession(), ArenaTeam::GetSlotByType(), ObjectGuid::GetString(), Player::GetTeam(), Field::GetUInt32(), GUILD_CREATE_S, GUILD_INVITE_S, HIGHGUID_PLAYER, IsArenaTypeValid(), MAX_ARENA_SLOT, QueryResult::NextRow(), Database::PQuery(), SendArenaTeamCommandResult(), SendGuildCommandResult(), SendPacket(), SMSG_PETITION_SHOW_SIGNATURES, and sWorld.
HandleOnMissileTrajectoryCollision()
void WorldSession::HandleOnMissileTrajectoryCollision (WorldPacket & recv_data)
Definition at line 841 of file SpellHandler.cpp.
References _player, DEBUG_FILTER_LOG, Unit::FindCurrentSpellBySpellId(), ObjectAccessor::GetUnit(), LOG_FILTER_SPELL_CAST, SpellCastTargets::m_targetMask, Spell::m_targets, Spell::RecalculateDelayMomentForDest(), WorldObject::SendMessageToSet(), SpellCastTargets::setDestination(), SMSG_NOTIFY_MISSILE_TRAJECTORY_COLLISION, and TARGET_FLAG_DEST_LOCATION.
HandleOpenItemOpcode()
void WorldSession::HandleOpenItemOpcode (WorldPacket & recvPacket)
Definition at line 200 of file SpellHandler.cpp.
References _player, CharacterDatabase, Database::CreateStatement(), Player::DestroyItem(), DETAIL_LOG, EQUIP_ERR_ITEM_LOCKED, EQUIP_ERR_ITEM_NOT_FOUND, QueryResult::Fetch(), Item::GetBagSlot(), Object::GetGUIDLow(), Player::GetItemByPos(), Item::GetProto(), Item::GetSlot(), Field::GetUInt32(), Object::HasFlag(), Player::IsSelfMover(), ITEM_CHANGED, ITEM_DYNFLAG_UNLOCKED, ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, ItemPrototype::LockID, LOOT_PICKPOCKETING, Object::m_loot, SqlStatement::PExecute(), Database::PQuery(), Player::SendEquipError(), Object::SetEntry(), Object::SetGuidValue(), Item::SetState(), Object::SetUInt32Value(), Loot::ShowContentTo(), ByteBuffer::size(), SIZEFMTD, LockEntry::Skill, sLockStore, and sLog.
HandleOptOutOfLootOpcode()
void WorldSession::HandleOptOutOfLootOpcode (WorldPacket & recv_data)
Definition at line 938 of file GroupHandler.cpp.
References DEBUG_LOG, GetPlayer(), and sLog.
HandlePageQuerySkippedOpcode()
void WorldSession::HandlePageQuerySkippedOpcode (WorldPacket & recvPacket)
Definition at line 469 of file ItemHandler.cpp.
References DEBUG_LOG, DETAIL_LOG, and ObjectGuid::GetString().
HandlePageTextQueryOpcode()
void WorldSession::HandlePageTextQueryOpcode (WorldPacket & recvPacket)
Definition at line 428 of file QueryHandler.cpp.
References DEBUG_LOG, DETAIL_LOG, GetSessionDbLocaleIndex(), ByteBuffer::hexlike(), SQLStorage::LookupEntry(), PageText::Next_Page, ByteBuffer::read_skip(), SendPacket(), SMSG_PAGE_TEXT_QUERY_RESPONSE, sObjectMgr, sPageTextStore, PageText::Text, and PageTextLocale::Text.
HandlePartyAssignmentOpcode()
void WorldSession::HandlePartyAssignmentOpcode (WorldPacket & recv_data)
error handling
Definition at line 575 of file GroupHandler.cpp.
References ByteConverter::apply(), DEBUG_LOG, Player::GetGroup(), Group::GetMainAssistantGuid(), Group::GetMainTankGuid(), GetPlayer(), Group::IsLeader(), Group::SetMainAssistant(), and Group::SetMainTank().
HandlePetAbandon()
void WorldSession::HandlePetAbandon (WorldPacket & recv_data)
Definition at line 674 of file PetHandler.cpp.
References _player, Unit::BreakCharmOutgoing(), CORPSE, DETAIL_LOG, WorldObject::GetMap(), Object::GetObjectGuid(), ObjectGuid::GetString(), Object::GetTypeId(), Map::GetUnit(), HUNTER_PET, Object::IsInWorld(), Creature::IsPet(), PET_SAVE_AS_DELETED, TYPEID_UNIT, and Pet::Unsummon().
HandlePetAction()
void WorldSession::HandlePetAction (WorldPacket & recv_data)
Definition at line 63 of file PetHandler.cpp.
References _player, ACT_COMMAND, Unit::Attack(), Unit::BreakCharmOutgoing(), Unit::CanAttack(), COMMAND_ATTACK, COMMAND_DISMISS, COMMAND_FOLLOW, COMMAND_STAY, DETAIL_LOG, FEEDBACK_CANT_ATT_TARGET, FEEDBACK_NOTHING_TO_ATT, FEEDBACK_PET_DEAD, Unit::GetCharmInfo(), Player::GetControlled(), Object::GetGUIDLow(), Object::GetGuidStr(), WorldObject::GetMap(), Unit::GetMasterGuid(), Object::GetObjectGuid(), ObjectGuid::GetString(), Object::GetTypeId(), Map::GetUnit(), Unit::GetVictim(), HandlePetActionHelper(), Unit::HasCharmer(), Unit::hasUnitState(), Unit::IsAlive(), Object::IsCreature(), PET_MODE_DISABLE_ACTIONS, Unit::SendPetActionFeedback(), CharmInfo::SetCommandState(), sLog, UNIT_ACTION_BUTTON_ACTION, UNIT_ACTION_BUTTON_TYPE, and UNIT_STAT_POSSESSED.
HandlePetActionHelper()
void WorldSession::HandlePetActionHelper (uint8 flag, uint32 spellid, Unit * petUnit, ObjectGuid targetGuid) private
Definition at line 175 of file PetHandler.cpp.
References _player, ACT_COMMAND, ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, ACT_REACTION, Unit::AI(), Unit::Attack(), UnitAI::AttackStart(), Unit::AttackStop(), Unit::BreakCharmOutgoing(), Unit::CanAttack(), Unit::CanAttackNow(), CheckPathToTarget(), MotionMaster::Clear(), Unit::clearUnitState(), COMMAND_ATTACK, COMMAND_DISMISS, COMMAND_FOLLOW, COMMAND_STAY, SpellEntry::EffectImplicitTargetA, FEEDBACK_CANT_ATT_TARGET, FEEDBACK_NOTHING_TO_ATT, Creature::ForcedDespawn(), Pet::ForcedDespawn(), Unit::GetCharmInfo(), Unit::GetCombatManager(), Map::GetCurrentMSTime(), WorldObject::GetMap(), Unit::GetMotionMaster(), Pet::getPetType(), Object::GetTypeId(), Map::GetUnit(), Unit::GetVictim(), Unit::HasSpell(), Unit::hasUnitState(), HUNTER_PET, Object::IsCreature(), Pet::IsDismissDisabled(), CombatManager::IsEvadingHome(), Unit::isInAccessablePlaceFor(), IsPassiveSpell(), Creature::IsPet(), WorldObject::IsSpellReady(), IsSpellRequireTarget(), Creature::IsTemporarySummon(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), SQLStorage::LookupEntry(), SpellRangeEntry::maxRange, SpellRangeEntry::minRange, PET_TALK_ATTACK, PET_TALK_SPECIAL_SPELL, Pet::PlayDismissSound(), SpellEntry::rangeIndex, REACT_AGGRESSIVE, REACT_DEFENSIVE, REACT_PASSIVE, CharmInfo::ResetStayPosition(), roll_chance_i(), SendNoPathToOwner(), Unit::SendPetActionFeedback(), Unit::SendPetAIReaction(), Unit::SendPetTalk(), CharmInfo::SetCommandState(), CharmInfo::SetIsRetreating(), CharmInfo::SetPetLastAttackCommandTime(), UnitAI::SetReactState(), CharmInfo::SetSpellOpener(), SpellCastTargets::setUnitTarget(), sLog, SPELL_CAST_OK, Spell::SpellStart(), sSpellRangeStore, sSpellTemplate, SUMMON_PET, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TRIGGERED_NORMAL_COMBAT_CAST, TRIGGERED_PET_CAST, TYPEID_UNIT, UNIT_STAT_MOVING, UNIT_STAT_POSSESSED, and urand().
Referenced by HandlePetAction().
HandlePetCancelAuraOpcode()
void WorldSession::HandlePetCancelAuraOpcode (WorldPacket & recvPacket)
Definition at line 577 of file SpellHandler.cpp.
References FEEDBACK_PET_DEAD, Map::GetAnyTypeCreature(), WorldObject::GetMap(), GetPlayer(), ObjectGuid::GetString(), Unit::IsAlive(), SQLStorage::LookupEntry(), Unit::RemoveAurasDueToSpell(), Unit::SendPetActionFeedback(), sLog, and sSpellTemplate.
HandlePetCastSpellOpcode()
void WorldSession::HandlePetCastSpellOpcode (WorldPacket & recvPacket)
Definition at line 774 of file PetHandler.cpp.
References _player, DEBUG_LOG, DETAIL_LOG, Object::GetGuidStr(), WorldObject::GetMap(), Object::GetObjectGuid(), Unit::GetPetGuid(), Aura::GetSpellProto(), ObjectGuid::GetString(), Unit::GetTarget(), Unit::GetTriggeredByClientAura(), Object::GetTypeId(), Map::GetUnit(), SpellCastTargets::getUnitTarget(), HandleClientCastFlags(), Unit::HasCharm(), HasMissingTargetFromClient(), Unit::HasSpell(), IsPassiveSpell(), Creature::IsPet(), WorldObject::IsSpellReady(), SQLStorage::LookupEntry(), Spell::m_cast_count, PET_TALK_SPECIAL_SPELL, SpellCastTargets::ReadForCaster(), Unit::SendPetAIReaction(), Unit::SendPetTalk(), SpellCastTargets::setUnitTarget(), sLog, SPELL_CAST_OK, Spell::SpellStart(), sSpellTemplate, SUMMON_PET, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TRIGGERED_PET_CAST, TYPEID_UNIT, and urand().
HandlePetitionBuyOpcode()
void WorldSession::HandlePetitionBuyOpcode (WorldPacket & recv_data)
Definition at line 49 of file PetitionsHandler.cpp.
References _player, ARENA_TEAM_CHARTER_2v2, ARENA_TEAM_CHARTER_2v2_COST, ARENA_TEAM_CHARTER_3v3, ARENA_TEAM_CHARTER_3v3_COST, ARENA_TEAM_CHARTER_5v5, ARENA_TEAM_CHARTER_5v5_COST, Database::BeginTransaction(), BUY_ERR_CANT_FIND_ITEM, BUY_ERR_NOT_ENOUGHT_MONEY, ItemPrototype::BuyCount, Player::CanStoreNewItem(), CharacterDatabase, Database::CommitTransaction(), CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, EQUIP_ERR_OK, ERR_ALREADY_IN_ARENA_TEAM, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_NAME_EXISTS_S, ERR_ARENA_TEAM_NAME_INVALID, ERR_GUILD_NAME_EXISTS_S, ERR_GUILD_NAME_INVALID, Database::escape_string(), QueryResult::Fetch(), Player::GetArenaTeamId(), Object::GetGUIDLow(), Player::GetGuildId(), ObjectMgr::GetItemPrototype(), Unit::GetLevel(), Player::GetMoney(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), Field::GetUInt32(), GUILD_CHARTER, GUILD_CHARTER_COST, GUILD_CREATE_S, ByteBuffer::hexlike(), Unit::isTabardDesigner(), ObjectMgr::IsValidCharterName(), ITEM_CHANGED, ITEM_FIELD_ENCHANTMENT_1_1, LANG_ARENA_ONE_TOOLOW, Player::ModifyMoney(), QueryResult::NextRow(), NULL_BAG, NULL_SLOT, Database::PExecute(), Database::PQuery(), ByteBuffer::read_skip(), sAnticheatLib, SendArenaTeamCommandResult(), Player::SendBuyError(), Player::SendEquipError(), SendGuildCommandResult(), Player::SendNewItem(), SendNotification(), Item::SetState(), Object::SetUInt32Value(), sGuildMgr, sLog, sObjectMgr, Player::StoreNewItem(), sWorld, and UNIT_NPC_FLAG_PETITIONER.
HandlePetitionDeclineOpcode()
void WorldSession::HandlePetitionDeclineOpcode (WorldPacket & recv_data)
Definition at line 577 of file PetitionsHandler.cpp.
References _player, CharacterDatabase, DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), Object::GetGuidStr(), Object::GetObjectGuid(), Player::GetSession(), ObjectGuid::GetString(), HIGHGUID_PLAYER, MSG_PETITION_DECLINE, Database::PQuery(), SendPacket(), and sObjectMgr.
HandlePetitionQueryOpcode()
void WorldSession::HandlePetitionQueryOpcode (WorldPacket & recv_data)
Definition at line 297 of file PetitionsHandler.cpp.
References DEBUG_LOG, ObjectGuid::GetString(), and SendPetitionQueryOpcode().
HandlePetitionRenameOpcode()
void WorldSession::HandlePetitionRenameOpcode (WorldPacket & recv_data)
Definition at line 373 of file PetitionsHandler.cpp.
References _player, CharacterDatabase, DEBUG_LOG, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_NAME_EXISTS_S, ERR_ARENA_TEAM_NAME_INVALID, ERR_GUILD_NAME_EXISTS_S, ERR_GUILD_NAME_INVALID, Database::escape_string(), QueryResult::Fetch(), ObjectGuid::GetCounter(), Player::GetItemByGuid(), ObjectGuid::GetString(), Field::GetUInt32(), GUILD_CREATE_S, ObjectMgr::IsValidCharterName(), MSG_PETITION_RENAME, Database::PExecute(), Database::PQuery(), SendArenaTeamCommandResult(), SendGuildCommandResult(), SendPacket(), sGuildMgr, and sObjectMgr.
HandlePetitionShowListOpcode()
void WorldSession::HandlePetitionShowListOpcode (WorldPacket & recvPacket)
Definition at line 915 of file PetitionsHandler.cpp.
References DEBUG_LOG, and SendPetitionShowList().
HandlePetitionShowSignOpcode()
void WorldSession::HandlePetitionShowSignOpcode (WorldPacket & recv_data)
Definition at line 242 of file PetitionsHandler.cpp.
References _player, CharacterDatabase, DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), Player::GetGuildId(), Object::GetObjectGuid(), QueryResult::GetRowCount(), ObjectGuid::GetString(), Field::GetUInt32(), HIGHGUID_PLAYER, QueryResult::NextRow(), Database::PQuery(), SendPacket(), sLog, and SMSG_PETITION_SHOW_SIGNATURES.
HandlePetitionSignOpcode()
void WorldSession::HandlePetitionSignOpcode (WorldPacket & recv_data)
Definition at line 443 of file PetitionsHandler.cpp.
References _player, CharacterDatabase, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, ERR_ALREADY_IN_ARENA_TEAM_S, ERR_ALREADY_IN_GUILD_S, ERR_ALREADY_INVITED_TO_ARENA_TEAM_S, ERR_ALREADY_INVITED_TO_GUILD_S, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_INVITE_SS, ERR_ARENA_TEAM_NOT_ALLIED, ERR_ARENA_TEAM_TARGET_TOO_LOW_S, ERR_GUILD_NOT_ALLIED, QueryResult::Fetch(), GetAccountId(), Player::GetArenaTeamId(), Player::GetArenaTeamIdInvited(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), Object::GetGuidStr(), Player::GetGuildId(), Player::GetGuildIdInvited(), Unit::GetLevel(), WorldObject::GetName(), Object::GetObjectGuid(), GetPlayer(), ArenaTeam::GetSlotByType(), ObjectGuid::GetString(), Field::GetUInt32(), Field::GetUInt8(), GUILD_CREATE_S, GUILD_INVITE_S, HIGHGUID_PLAYER, IsArenaTypeValid(), MAX_ARENA_SLOT, PETITION_SIGN_ALREADY_SIGNED, PETITION_SIGN_OK, Database::PExecute(), Database::PQuery(), SendArenaTeamCommandResult(), SendGuildCommandResult(), SendPacket(), sLog, SMSG_PETITION_SIGN_RESULTS, sObjectMgr, and sWorld.
HandlePetLearnTalent()
void WorldSession::HandlePetLearnTalent (WorldPacket & recvPacket)
Definition at line 849 of file PetHandler.cpp.
References _player, DEBUG_LOG, Player::LearnPetTalent(), and Player::SendTalentsInfoData().
HandlePetNameQueryOpcode()
void WorldSession::HandlePetNameQueryOpcode (WorldPacket & recv_data)
Definition at line 430 of file PetHandler.cpp.
References DETAIL_LOG, and SendPetNameQuery().
HandlePetRename()
void WorldSession::HandlePetRename (WorldPacket & recv_data)
Definition at line 600 of file PetHandler.cpp.
References _player, Database::BeginTransaction(), CharacterDatabase, ObjectMgr::CheckDeclinedNames(), ObjectMgr::CheckPetName(), Database::CommitTransaction(), DETAIL_LOG, Database::escape_string(), Unit::GetCharmInfo(), Player::GetGroup(), Object::GetGUIDLow(), GetMainPartOfName(), WorldObject::GetMap(), Object::GetObjectGuid(), Unit::GetOwnerGuid(), Map::GetPet(), CharmInfo::GetPetNumber(), Pet::getPetType(), GROUP_UPDATE_FLAG_PET_NAME, Object::HasByteFlag(), HUNTER_PET, DeclinedName::name, PET_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME, PET_NAME_RESERVED, PET_NAME_SUCCESS, Database::PExecute(), Object::RemoveByteFlag(), SendPetNameInvalid(), Player::SetGroupUpdateFlag(), WorldObject::SetName(), Object::SetUInt32Value(), sObjectMgr, UNIT_BYTES_2_OFFSET_PET_FLAGS, UNIT_CAN_BE_RENAMED, UNIT_FIELD_BYTES_2, UNIT_FIELD_PET_NAME_TIMESTAMP, and Utf8toWStr().
HandlePetSetAction()
void WorldSession::HandlePetSetAction (WorldPacket & recv_data)
Definition at line 485 of file PetHandler.cpp.
References _player, ACT_COMMAND, ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, ACT_REACTION, DETAIL_LOG, UnitActionBarEntry::GetAction(), CharmInfo::GetActionBarEntry(), Unit::GetCharm(), Unit::GetCharmInfo(), Object::GetGuidStr(), WorldObject::GetMap(), WorldObject::GetName(), Unit::GetPet(), UnitActionBarEntry::GetType(), Object::GetTypeId(), Map::GetUnit(), Unit::HasCharmer(), Unit::HasSpell(), Creature::IsPet(), MAX_UNIT_ACTION_BAR_INDEX, PET_MODE_DISABLE_ACTIONS, CharmInfo::SetActionBar(), ByteBuffer::size(), sLog, CharmInfo::ToggleCreatureAutocast(), TYPEID_UNIT, UNIT_ACTION_BUTTON_ACTION, and UNIT_ACTION_BUTTON_TYPE.
HandlePetSpellAutocastOpcode()
void WorldSession::HandlePetSpellAutocastOpcode (WorldPacket & recvPacket)
Definition at line 735 of file PetHandler.cpp.
References _player, DETAIL_LOG, Unit::GetCharmInfo(), Object::GetGuidStr(), WorldObject::GetMap(), Unit::GetPetGuid(), ObjectGuid::GetString(), Object::GetTypeId(), Map::GetUnit(), Unit::HasCharm(), Unit::HasCharmer(), Unit::HasSpell(), IsAutocastable(), Creature::IsPet(), CharmInfo::SetSpellAutocast(), sLog, CharmInfo::ToggleCreatureAutocast(), and TYPEID_UNIT.
HandlePetStopAttack()
void WorldSession::HandlePetStopAttack (WorldPacket & recv_data)
Definition at line 404 of file PetHandler.cpp.
References _player, Unit::AttackStop(), DEBUG_LOG, Object::GetGuidStr(), WorldObject::GetMap(), Unit::GetMasterGuid(), Object::GetObjectGuid(), ObjectGuid::GetString(), Map::GetUnit(), Unit::IsAlive(), and sLog.
HandlePetUnlearnOpcode()
void WorldSession::HandlePetUnlearnOpcode (WorldPacket & recvPacket)
Definition at line 707 of file PetHandler.cpp.
References _player, DETAIL_LOG, Unit::GetCharmInfo(), Object::GetGuidStr(), Object::GetObjectGuid(), Unit::GetPet(), Pet::getPetType(), ObjectGuid::GetString(), HUNTER_PET, Pet::m_usedTalentCount, Pet::resetTalents(), Player::SendTalentsInfoData(), and sLog.
HandlePlayedTime()
void WorldSession::HandlePlayedTime (WorldPacket & recvPacket)
Definition at line 961 of file MiscHandler.cpp.
References _player, Player::GetLevelPlayedTime(), Player::GetTotalPlayedTime(), SendPacket(), and SMSG_PLAYED_TIME.
HandlePlayerLogin()
void WorldSession::HandlePlayerLogin (LoginQueryHolder * holder)
Definition at line 676 of file CharacterHandler.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, Map::Add(), ALIVE, AREA_LOCKSTATUS_INSUFFICIENT_EXPANSION, AREA_LOCKSTATUS_OK, AREA_LOCKSTATUS_UNKNOWN_ERROR, AT_LOGIN_ADD_BG_DESERTER, AT_LOGIN_FIRST, AT_LOGIN_RESET_PET_TALENTS, AT_LOGIN_RESET_SPELLS, AT_LOGIN_RESET_TALENTS, AT_LOGIN_RESET_TAXINODES, Guild::BroadcastEvent(), Unit::CastSpell(), CHAR_LOGIN_NO_CHARACTER, CharacterDatabase, CONFIG_BOOL_ALL_TAXI_PATHS, CONFIG_UINT32_GM_INVISIBLE_AURA, Database::CreateStatement(), DEBUG_LOG, Guild::DisplayGuildBankTabsInfo(), MapEntry::Expansion(), QueryResult::Fetch(), FRIEND_ONLINE, GE_MOTD, GE_SIGNED_ON, GetAccountId(), Player::GetAchievementMgr(), Player::GetAreaTriggerLockStatus(), Player::getCinematic(), Unit::getClass(), Player::GetDifficulty(), GetExpansion(), Player::GetGroup(), LoginQueryHolder::GetGuid(), Object::GetGUIDLow(), Object::GetGuidStr(), Player::GetGuildId(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetMapId(), Guild::GetMOTD(), Unit::GetMotionMaster(), WorldTimer::getMSTime(), WorldObject::GetName(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::getRace(), GetRemoteAddress(), SqlQueryHolder::GetResult(), Player::GetSession(), WorldObject::GetTransport(), MovementInfo::GetTransportPos(), Player::HasAtLoginFlag(), Object::HasFlag(), MotionMaster::Initialize(), WorldPacket::Initialize(), Player::InitTaxiNodesForLevel(), Player::IsGameMaster(), Player::isGMVisible(), Map::IsRaid(), IsSpellAppliesAura(), Unit::IsStandState(), Unit::IsStunned(), KickPlayer(), LANG_GM_ON, LANG_INVISIBLE_INVISIBLE, LANG_RESET_SPELLS, LANG_RESET_TALENTS, LoadAccountData(), Player::LoadCorpse(), Player::LoadFromDB(), Player::LoadPet(), LoginDatabase, SQLStorage::LookupEntry(), m_currentPlayerLevel, Unit::m_deathState, m_initialZoneUpdated, WorldObject::m_movementInfo, m_playerLoading, Position::o, PER_CHARACTER_CACHE_MASK, SqlStatement::PExecute(), PLAYER_FLAGS, PLAYER_FLAGS_CONTESTED_PVP, PLAYER_FLAGS_RESTING, PLAYER_LOGIN_QUERY_LOADACCOUNTDATA, PLAYER_LOGIN_QUERY_LOADGUILD, RACE_NIGHTELF, realmID, Player::RemoveAtLoginFlag(), Player::resetSpells(), Player::resetTalents(), Pet::resetTalentsForAllPetsOf(), sChrClassesStore, sChrRacesStore, SendAccountDataTimes(), Player::SendCinematicStart(), Player::SendDungeonDifficulty(), SendExpectedSpamRecords(), Player::SendInitialPacketsAfterAddToMap(), Player::SendInitialPacketsBeforeAddToMap(), SendMotd(), SendNotification(), SendOfflineNameQueryResponses(), SendPacket(), Player::SendTalentsInfoData(), Group::SendUpdateTo(), Player::setCinematic(), Player::SetInGameTime(), Player::SetInGuild(), SetOnline(), SetPlayer(), Unit::SetPvPFreeForAll(), Player::SetRank(), Unit::SetStandState(), Player::SetTaxiCheater(), Unit::SetWaterWalk(), sGuildMgr, sLog, sMapStore, SMSG_CHARACTER_LOGIN_FAILED, SMSG_FEATURE_SYSTEM_STATUS, SMSG_GUILD_EVENT, SMSG_LEARNED_DANCE_MOVES, SMSG_LOGIN_VERIFY_WORLD, sObjectAccessor, sObjectMgr, SPELL_ID_BATTLEGROUND_DESERTER, sSocialMgr, sSpellTemplate, sTicketMgr, sWorld, AreaTrigger::target_mapId, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, Player::TaxiFlightResume(), Player::TeleportTo(), Player::TeleportToHomebind(), TRIGGERED_OLD_TRIGGERED, UNIT_STAND_STATE_STAND, AchievementMgr::UpdateAchievementCriteria(), Group::UpdatePlayerOnlineStatus(), Player::UpdatePvPContested(), Position::x, Position::y, and Position::z.
HandlePlayerLoginOpcode()
void WorldSession::HandlePlayerLoginOpcode (WorldPacket & recvPacket)
Definition at line 589 of file CharacterHandler.cpp.
References _player, CHAR_LOGIN_DUPLICATE_CHARACTER, CHAR_LOGIN_FAILED, CharacterDatabase, chrHandler, DEBUG_LOG, Database::DelayQueryHolder(), ObjectAccessor::FindPlayer(), GetAccountId(), Object::GetGuidStr(), HandleMoveWorldportAckOpcode(), CharacterHandler::HandlePlayerLoginCallback(), HandlePlayerReconnect(), LoginQueryHolder::Initialize(), Player::IsBeingTeleportedFar(), Object::IsInWorld(), isLogingOut(), m_playerLoading, PlayerLoading(), SendPacket(), sLog, sLootMgr, and SMSG_CHARACTER_LOGIN_FAILED.
HandlePlayerLogoutOpcode()
void WorldSession::HandlePlayerLogoutOpcode (WorldPacket & recvPacket)
Definition at line 314 of file MiscHandler.cpp.
References DEBUG_LOG.
HandlePlayerReconnect()
void WorldSession::HandlePlayerReconnect ()
Definition at line 953 of file CharacterHandler.cpp.
References _player, Guild::BroadcastEvent(), Unit::CastSpell(), Player::CleanupChannels(), CONFIG_BOOL_ALL_TAXI_PATHS, Map::CreatePlayerOnClient(), DEBUG_LOG, FRIEND_ONLINE, GE_MOTD, GE_SIGNED_ON, GetAccountId(), Player::getCinematic(), Player::GetGroup(), Object::GetGUIDLow(), Player::GetGuildId(), WorldObject::GetMap(), WorldObject::GetMapId(), Guild::GetMOTD(), WorldObject::GetName(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetRaidDifficulty(), GetRemoteAddress(), Player::GetSocial(), Map::GetWorldObject(), WorldObject::GetZoneAndAreaId(), WorldPacket::Initialize(), Unit::IsAlive(), Unit::IsClientControlled(), Player::IsGameMaster(), Unit::IsStandState(), Unit::IsStunned(), Unit::IsTaxiFlying(), LANG_GM_ON, LogoutRequest(), m_anticheat, Player::m_clientGUIDs, m_initialZoneUpdated, m_playerLoading, PER_CHARACTER_CACHE_MASK, SendAccountDataTimes(), Player::SendCorpseReclaimDelay(), Player::SendDungeonDifficulty(), Player::SendEnchantmentDurations(), SendExpectedSpamRecords(), Player::SendInitialPacketsBeforeAddToMap(), Player::SendInitWorldStates(), Player::SendItemDurations(), Player::SendMirrorTimers(), SendMotd(), SendNotification(), SendOfflineNameQueryResponses(), SendPacket(), Player::SendPetBar(), Player::SendRaidDifficulty(), PlayerSocial::SendSocialList(), Group::SendUpdateTo(), Player::SetInGuild(), SetOnline(), Unit::SetStandState(), Unit::SetStunnedByLogout(), Player::SetTaxiCheater(), sGuildMgr, sLog, SMSG_FEATURE_SYSTEM_STATUS, SMSG_GUILD_EVENT, SMSG_LEARNED_DANCE_MOVES, SMSG_LOGIN_VERIFY_WORLD, sSocialMgr, sTicketMgr, Player::StopCinematic(), sWorld, Player::TaxiFlightResume(), TRIGGERED_OLD_TRIGGERED, UNIT_STAND_STATE_STAND, Player::UpdateClientAuras(), and Player::UpdateClientControl().
Referenced by HandlePlayerLoginOpcode().
HandlePushQuestToParty()
void WorldSession::HandlePushQuestToParty (WorldPacket & recvPacket)
Definition at line 576 of file QuestHandler.cpp.
References _player, Player::CanShareQuest(), Player::CanTakeQuest(), DEBUG_LOG, Player::GetDividerGuid(), Player::GetGroup(), Object::GetGuidStr(), Object::GetObjectGuid(), Player::GetPlayerMenu(), Player::GetQuestStatus(), Object::IsInWorld(), GroupReference::next(), QUEST_PARTY_MSG_BUSY, QUEST_PARTY_MSG_CANT_TAKE_QUEST, QUEST_PARTY_MSG_FINISH_QUEST, QUEST_PARTY_MSG_HAVE_QUEST, QUEST_PARTY_MSG_LOG_FULL, QUEST_PARTY_MSG_SHARING_QUEST, QUEST_STATUS_COMPLETE, Player::SatisfyQuestLog(), Player::SatisfyQuestStatus(), Player::SendPushToPartyResponse(), PlayerMenu::SendQuestGiverQuestDetails(), Player::SetDividerGuid(), sLog, and sObjectMgr.
HandlePVPLogDataOpcode()
void WorldSession::HandlePVPLogDataOpcode (WorldPacket & recv_data)
Definition at line 344 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, Player::GetBattleGround(), BattleGround::IsArena(), sBattleGroundMgr, and SendPacket().
HandleQueryGuildBankTabText()
void WorldSession::HandleQueryGuildBankTabText (WorldPacket & recv_data)
Definition at line 1198 of file GuildHandler.cpp.
References DEBUG_LOG, Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), Guild::SendGuildBankTabText(), and sGuildMgr.
HandleQueryInspectAchievementsOpcode()
void WorldSession::HandleQueryInspectAchievementsOpcode (WorldPacket & recv_data)
Definition at line 1497 of file MiscHandler.cpp.
References _player, Unit::CanAttack(), Player::GetAchievementMgr(), INSPECT_DISTANCE, WorldObject::IsWithinDistInMap(), ObjectGuid::ReadAsPacked(), AchievementMgr::SendRespondInspectAchievements(), and sObjectMgr.
HandleQueryQuestsCompletedOpcode()
void WorldSession::HandleQueryQuestsCompletedOpcode (WorldPacket & recv_data)
Definition at line 490 of file QueryHandler.cpp.
References _player, Player::getQuestStatusMap(), ByteBuffer::put(), SendPacket(), and SMSG_ALL_QUESTS_COMPLETED.
HandleQueryTimeOpcode()
void WorldSession::HandleQueryTimeOpcode (WorldPacket & recvPacket)
Definition at line 179 of file QueryHandler.cpp.
References SendQueryTimeResponse().
HandleQuestConfirmAccept()
void WorldSession::HandleQuestConfirmAccept (WorldPacket & recv_data)
Definition at line 505 of file QuestHandler.cpp.
References _player, Player::AddQuest(), Player::CanAddQuest(), Player::ClearDividerGuid(), DEBUG_LOG, ObjectAccessor::FindPlayer(), Player::GetDividerGuid(), Player::IsInGroup(), Unit::IsInParty(), QUEST_FLAGS_PARTY_ACCEPT, and sObjectMgr.
HandleQuestgiverAcceptQuestOpcode()
void WorldSession::HandleQuestgiverAcceptQuestOpcode (WorldPacket & recvPacket)
Definition at line 116 of file QuestHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, Player::AddQuest(), Player::CanAddQuest(), Player::CanCompleteQuest(), CanInteractWithQuestGiver(), Player::CanShareQuest(), Player::CanTakeQuest(), Unit::CastSpell(), Player::ClearDividerGuid(), PlayerMenu::CloseGossip(), Player::CompleteQuest(), DEBUG_LOG, ObjectAccessor::FindPlayer(), Player::GetAchievementMgr(), Player::GetDividerGuid(), Player::GetGroup(), Object::GetGuidStr(), Player::GetObjectByTypeMask(), Object::GetObjectGuid(), GetPlayer(), Player::GetPlayerMenu(), Quest::GetSrcSpell(), ObjectGuid::GetString(), Object::GetTypeId(), Object::HasQuest(), Quest::HasQuestFlag(), Object::IsInWorld(), GroupReference::next(), QUEST_FLAGS_PARTY_ACCEPT, QUEST_PARTY_MSG_ACCEPT_QUEST, Player::SendQuestConfirmAccept(), Player::SetDividerGuid(), sObjectMgr, AchievementMgr::StartTimedAchievementCriteria(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and TYPEMASK_CREATURE_GAMEOBJECT_PLAYER_OR_ITEM.
Referenced by PlayerbotMgr::HandleMasterIncomingPacket().
HandleQuestgiverCancel()
void WorldSession::HandleQuestgiverCancel (WorldPacket & recv_data)
Definition at line 446 of file QuestHandler.cpp.
References _player, PlayerMenu::CloseGossip(), DEBUG_LOG, and Player::GetPlayerMenu().
HandleQuestgiverChooseRewardOpcode()
void WorldSession::HandleQuestgiverChooseRewardOpcode (WorldPacket & recvPacket)
Definition at line 381 of file QuestHandler.cpp.
References _player, CanInteractWithQuestGiver(), Player::CanRewardQuest(), DEBUG_LOG, Object::GetGuidStr(), Player::GetNextQuest(), Player::GetObjectByTypeMask(), Player::GetPlayerMenu(), ObjectGuid::GetString(), Object::HasInvolvedQuest(), QUEST_REWARD_CHOICES_COUNT, Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), sLog, sObjectMgr, and TYPEMASK_CREATURE_OR_GAMEOBJECT.
HandleQuestgiverCompleteQuest()
void WorldSession::HandleQuestgiverCompleteQuest (WorldPacket & recv_data)
Definition at line 540 of file QuestHandler.cpp.
References _player, Player::CanCompleteRepeatableQuest(), CanInteractWithQuestGiver(), Player::CanRewardQuest(), DEBUG_LOG, Object::GetGuidStr(), Player::GetPlayerMenu(), Player::GetQuestStatus(), ObjectGuid::GetString(), QUEST_STATUS_COMPLETE, PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverRequestItems(), and sObjectMgr.
HandleQuestgiverHelloOpcode()
void WorldSession::HandleQuestgiverHelloOpcode (WorldPacket & recvPacket)
Definition at line 91 of file QuestHandler.cpp.
References _player, DEBUG_LOG, Creature::GetDefaultGossipMenuId(), Object::GetGuidStr(), Creature::GetInteractionPauseTimer(), Unit::GetMotionMaster(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), MotionMaster::PauseWaypoints(), Player::PrepareGossipMenu(), Player::SendPreparedGossip(), sScriptDevAIMgr, and UNIT_NPC_FLAG_NONE.
HandleQuestgiverQueryQuestOpcode()
void WorldSession::HandleQuestgiverQueryQuestOpcode (WorldPacket & recvPacket)
Definition at line 203 of file QuestHandler.cpp.
References _player, PlayerMenu::CloseGossip(), DEBUG_LOG, Object::GetGuidStr(), Player::GetObjectByTypeMask(), Object::GetObjectGuid(), Player::GetPlayerMenu(), ObjectGuid::GetString(), Object::HasInvolvedQuest(), Object::HasQuest(), PlayerMenu::SendQuestGiverQuestDetails(), sObjectMgr, and TYPEMASK_CREATURE_GAMEOBJECT_OR_ITEM.
HandleQuestgiverQuestAutoLaunch()
void WorldSession::HandleQuestgiverQuestAutoLaunch (WorldPacket & recvPacket)
Definition at line 571 of file QuestHandler.cpp.
References DEBUG_LOG.
HandleQuestgiverRequestRewardOpcode()
void WorldSession::HandleQuestgiverRequestRewardOpcode (WorldPacket & recvPacket)
Definition at line 421 of file QuestHandler.cpp.
References _player, Player::CanCompleteQuest(), CanInteractWithQuestGiver(), Player::CompleteQuest(), DEBUG_LOG, Object::GetGuidStr(), Player::GetObjectByTypeMask(), Player::GetPlayerMenu(), Player::GetQuestStatus(), ObjectGuid::GetString(), Object::HasInvolvedQuest(), QUEST_STATUS_COMPLETE, PlayerMenu::SendQuestGiverOfferReward(), sObjectMgr, and TYPEMASK_CREATURE_OR_GAMEOBJECT.
HandleQuestgiverStatusMultipleQuery()
void WorldSession::HandleQuestgiverStatusMultipleQuery (WorldPacket & recvPacket)
Definition at line 773 of file QuestHandler.cpp.
References _player, DEBUG_LOG, and Player::SendQuestGiverStatusMultiple().
HandleQuestgiverStatusQueryOpcode()
void WorldSession::HandleQuestgiverStatusQueryOpcode (WorldPacket & recvPacket)
Definition at line 38 of file QuestHandler.cpp.
References _player, Unit::CanInteract(), DEBUG_LOG, DETAIL_LOG, DIALOG_STATUS_NONE, DIALOG_STATUS_UNDEFINED, getDialogStatus(), Object::GetGuidStr(), Player::GetObjectByTypeMask(), Player::GetPlayerMenu(), ObjectGuid::GetString(), Object::GetTypeId(), PlayerMenu::SendQuestGiverStatus(), sLog, sScriptDevAIMgr, TYPEID_GAMEOBJECT, TYPEID_UNIT, and TYPEMASK_CREATURE_OR_GAMEOBJECT.
HandleQuestLogRemoveQuest()
void WorldSession::HandleQuestLogRemoveQuest (WorldPacket & recv_data)
Definition at line 466 of file QuestHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED, BIND_QUEST_ITEM, ItemPrototype::Bonding, DEBUG_LOG, Player::DestroyItemCount(), Player::GetAchievementMgr(), ObjectMgr::GetItemPrototype(), Player::GetQuestSlotQuestId(), MAX_QUEST_LOG_SIZE, QUEST_SOURCE_ITEM_IDS_COUNT, QUEST_SPECIAL_FLAG_TIMED, QUEST_STATUS_NONE, Player::RemoveTimedQuest(), Player::SetQuestSlot(), Player::SetQuestStatus(), sObjectMgr, Player::TakeQuestSourceItem(), and AchievementMgr::UpdateAchievementCriteria().
HandleQuestLogSwapQuest()
void WorldSession::HandleQuestLogSwapQuest (WorldPacket & recv_data)
Definition at line 453 of file QuestHandler.cpp.
References DEBUG_LOG, GetPlayer(), MAX_QUEST_LOG_SIZE, and Player::SwapQuestSlot().
HandleQuestPOIQueryOpcode()
void WorldSession::HandleQuestPOIQueryOpcode (WorldPacket & recv_data)
Definition at line 509 of file QueryHandler.cpp.
References _player, Player::FindQuestSlot(), Player::GetQuestSlotQuestId(), MAX_QUEST_LOG_SIZE, ByteBuffer::rpos(), SendPacket(), SMSG_QUEST_POI_QUERY_RESPONSE, sObjectMgr, and ByteBuffer::wpos().
HandleQuestPushResult()
void WorldSession::HandleQuestPushResult (WorldPacket & recvPacket)
Definition at line 651 of file QuestHandler.cpp.
References _player, Player::ClearDividerGuid(), DEBUG_LOG, ObjectAccessor::FindPlayer(), Player::GetDividerGuid(), and MSG_QUEST_PUSH_RESULT.
HandleQuestQueryOpcode()
void WorldSession::HandleQuestQueryOpcode (WorldPacket & recvPacket)
Definition at line 224 of file QuestHandler.cpp.
References DEBUG_LOG, Quest::GetBonusTalents(), Quest::GetCharTitleId(), Quest::GetCompletedText(), Quest::GetDetails(), Quest::GetEndText(), Quest::GetMinLevel(), Quest::GetNextQuestInChain(), Quest::GetObjectives(), Quest::GetPlayersSlain(), Quest::GetPointMapId(), Quest::GetPointOpt(), Quest::GetPointX(), Quest::GetPointY(), Quest::GetQuestFlags(), Quest::GetQuestId(), Quest::GetQuestLevel(), Quest::GetQuestMethod(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveValue(), Quest::GetRewHonorAddition(), Quest::GetRewHonorMultiplier(), Quest::GetRewMoneyMaxLevel(), Quest::GetRewOrReqMoney(), Quest::GetRewSpell(), Quest::GetRewSpellCast(), Quest::GetRewXPId(), GetSessionDbLocaleIndex(), Quest::GetSrcItemId(), Quest::GetSuggestedPlayers(), Quest::GetTitle(), Quest::GetType(), Quest::GetZoneOrSort(), Quest::HasQuestFlag(), Quest::ObjectiveText, QUEST_FLAGS_HIDDEN_REWARDS, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, Quest::ReqCreatureOrGOCount, Quest::ReqCreatureOrGOId, Quest::ReqItemCount, Quest::ReqItemId, Quest::ReqSourceId, Quest::RewChoiceItemCount, Quest::RewChoiceItemId, Quest::RewItemCount, Quest::RewItemId, Quest::RewRepFaction, Quest::RewRepValueId, SendPacket(), SMSG_QUEST_QUERY_RESPONSE, and sObjectMgr.
HandleRaidReadyCheckFinishedOpcode()
void WorldSession::HandleRaidReadyCheckFinishedOpcode (WorldPacket & recv_data)
Definition at line 651 of file GroupHandler.cpp.
References Group::BroadcastPacket(), Player::GetGroup(), GetPlayer(), Group::IsAssistant(), Group::IsLeader(), and MSG_RAID_READY_CHECK_FINISHED.
HandleRaidReadyCheckOpcode()
void WorldSession::HandleRaidReadyCheckOpcode (WorldPacket & recv_data)
error handling
Definition at line 613 of file GroupHandler.cpp.
References Group::BroadcastPacket(), Group::BroadcastReadyCheck(), ByteBuffer::empty(), Player::GetGroup(), Object::GetObjectGuid(), GetPlayer(), Group::IsAssistant(), Group::IsLeader(), MSG_RAID_READY_CHECK, MSG_RAID_READY_CHECK_CONFIRM, and Group::OfflineReadyCheck().
HandleRaidTargetUpdateOpcode()
void WorldSession::HandleRaidTargetUpdateOpcode (WorldPacket & recv_data)
error handling
Definition at line 471 of file GroupHandler.cpp.
References _player, Player::GetGroup(), Object::GetObjectGuid(), GetPlayer(), Group::IsAssistant(), Group::IsLeader(), Group::IsRaidGroup(), Group::SendTargetIconList(), and Group::SetTargetIcon().
HandleRandomRollOpcode()
void WorldSession::HandleRandomRollOpcode (WorldPacket & recv_data)
error handling
Definition at line 444 of file GroupHandler.cpp.
References Group::BroadcastPacket(), Player::GetGroup(), Object::GetObjectGuid(), GetPlayer(), MSG_RANDOM_ROLL, SendPacket(), and urand().
HandleReadItemOpcode()
void WorldSession::HandleReadItemOpcode (WorldPacket & recvPacket)
Definition at line 436 of file ItemHandler.cpp.
References _player, Player::CanUseItem(), DETAIL_LOG, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, Player::GetItemByPos(), Object::GetObjectGuid(), Item::GetProto(), WorldPacket::Initialize(), ItemPrototype::PageText, Player::SendEquipError(), SendPacket(), SMSG_READ_ITEM_FAILED, and SMSG_READ_ITEM_OK.
HandleReadyForAccountDataTimesOpcode()
void WorldSession::HandleReadyForAccountDataTimesOpcode (WorldPacket & recv_data)
Definition at line 1526 of file MiscHandler.cpp.
References DEBUG_LOG, GLOBAL_CACHE_MASK, and SendAccountDataTimes().
HandleRealmSplitOpcode()
void WorldSession::HandleRealmSplitOpcode (WorldPacket & recv_data)
Definition at line 1190 of file MiscHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_REALM_SPLIT.
HandleReclaimCorpseOpcode()
void WorldSession::HandleReclaimCorpseOpcode (WorldPacket & recvPacket)
Definition at line 638 of file MiscHandler.cpp.
References CORPSE_RECLAIM_RADIUS, CORPSE_RESURRECTABLE_PVP, DETAIL_LOG, Player::GetCorpse(), Corpse::GetGhostTime(), GetPlayer(), Corpse::GetType(), WorldObject::IsWithinDistInMap(), PLAYER_FLAGS, PLAYER_FLAGS_GHOST, Player::ResurrectPlayer(), and Player::SpawnCorpseBones().
HandleReferAFriend()
void WorldSession::HandleReferAFriend (WorldPacket & recv_data)
Definition at line 70 of file RafHandler.cpp.
HandleRemoveGlyphOpcode()
void WorldSession::HandleRemoveGlyphOpcode (WorldPacket & recv_data)
Definition at line 1401 of file CharacterHandler.cpp.
References _player, Player::ApplyGlyph(), DEBUG_LOG, Player::GetGlyph(), MAX_GLYPH_SLOT_INDEX, Player::SendTalentsInfoData(), and Player::SetGlyph().
HandleRepairItemOpcode()
void WorldSession::HandleRepairItemOpcode (WorldPacket & recvPacket)
Definition at line 985 of file NPCHandler.cpp.
References _player, DEBUG_LOG, Player::DurabilityRepair(), Player::DurabilityRepairAll(), Object::GetGUIDLow(), Player::GetGuildId(), Player::GetItemByGuid(), Player::GetNPCIfCanInteractWith(), GetPlayer(), Item::GetPos(), Player::GetReputationPriceDiscount(), ObjectGuid::GetString(), GUILD_BANK_LOG_REPAIR_MONEY, Guild::LogBankEvent(), Guild::SendMoneyInfo(), sGuildMgr, and UNIT_NPC_FLAG_REPAIR.
HandleRepopRequestOpcode()
void WorldSession::HandleRepopRequestOpcode (WorldPacket & recvPacket)
Definition at line 47 of file MiscHandler.cpp.
References Player::BuildPlayerRepop(), DEBUG_LOG, Unit::GetDeathState(), GetPlayer(), Unit::HasAuraType(), Object::HasFlag(), Unit::IsAlive(), JUST_DIED, Player::KillPlayer(), PET_SAVE_REAGENTS, PLAYER_FLAGS, PLAYER_FLAGS_GHOST, ByteBuffer::read_skip(), Player::RemovePet(), Player::RepopAtGraveyard(), and SPELL_AURA_PREVENT_RESURRECTION.
HandleReportPvPAFK()
void WorldSession::HandleReportPvPAFK (WorldPacket & recv_data)
Definition at line 877 of file BattleGroundHandler.cpp.
References _player, DEBUG_LOG, WorldObject::GetName(), Player::ReportedAfkBy(), and sObjectMgr.
HandleRequestAccountData()
void WorldSession::HandleRequestAccountData (WorldPacket & recvPacket)
Definition at line 852 of file MiscHandler.cpp.
References _player, ByteBuffer::append(), ByteBuffer::contents(), AccountData::Data, DEBUG_LOG, DETAIL_LOG, GetAccountData(), Object::GetObjectGuid(), NUM_ACCOUNT_DATA_TYPES, ByteBuffer::resize(), SendPacket(), SMSG_UPDATE_ACCOUNT_DATA, and AccountData::Time.
HandleRequestPartyMemberStatsOpcode()
void WorldSession::HandleRequestPartyMemberStatsOpcode (WorldPacket & recv_data)
Definition at line 815 of file GroupHandler.cpp.
References WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, DEBUG_LOG, ObjectAccessor::FindPlayer(), Unit::GetCharm(), Unit::GetDisplayId(), GetGroupMemberStatus(), Unit::GetHealth(), Unit::GetLevel(), Unit::GetMaxHealth(), Unit::GetMaxPower(), WorldObject::GetName(), Object::GetObjectGuid(), Object::GetPackGUID(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Unit::GetPower(), Unit::GetPowerType(), Player::GetTeleportDest(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Unit::GetVisibleAura(), WorldObject::GetZoneId(), GROUP_UPDATE_FLAG_STATUS, Player::IsBeingTeleported(), Object::IsInWorld(), WorldLocation::mapid, MAX_AURAS, MEMBER_STATUS_OFFLINE, ByteBuffer::put(), SendPacket(), SMSG_PARTY_MEMBER_STATS_FULL, sTerrainMgr, ByteBuffer::wpos(), and ObjectGuid::WriteAsPacked().
HandleRequestPetInfoOpcode()
void WorldSession::HandleRequestPetInfoOpcode (WorldPacket & recv_data)
Definition at line 1476 of file MiscHandler.cpp.
References _player, Player::CharmSpellInitialize(), Unit::GetCharm(), Unit::GetPet(), and Player::PetSpellInitialize().
HandleRequestRaidInfoOpcode()
void WorldSession::HandleRequestRaidInfoOpcode (WorldPacket & recv_data)
Definition at line 932 of file GroupHandler.cpp.
References _player, and Player::SendRaidInfo().
HandleRequestVehicleExit()
void WorldSession::HandleRequestVehicleExit (WorldPacket & recvPacket)
Definition at line 53 of file VehicleHandler.cpp.
References _player, DEBUG_LOG, Object::GetObjectGuid(), VehicleInfo::GetSeatEntry(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Unit::GetVehicleInfo(), ByteBuffer::hexlike(), TransportInfo::IsOnVehicle(), Unit::RemoveSpellsCausingAura(), SEAT_FLAG_CAN_EXIT, and SPELL_AURA_CONTROL_VEHICLE.
HandleRequestVehicleNextSeat()
void WorldSession::HandleRequestVehicleNextSeat (WorldPacket & recvPacket)
Definition at line 70 of file VehicleHandler.cpp.
References _player, VehicleInfo::ChangeSeat(), CMSG_REQUEST_VEHICLE_NEXT_SEAT, CMSG_REQUEST_VEHICLE_PREV_SEAT, DEBUG_LOG, WorldPacket::GetOpcode(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Unit::GetVehicleInfo(), and TransportInfo::IsOnVehicle().
HandleRequestVehicleSwitchSeat()
void WorldSession::HandleRequestVehicleSwitchSeat (WorldPacket & recvPacket)
Definition at line 97 of file VehicleHandler.cpp.
References _player, Unit::CastSpell(), DEBUG_LOG, Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), Map::GetUnit(), VehicleInfo::GetVehicleEntry(), Unit::GetVehicleInfo(), ByteBuffer::hexlike(), TransportInfo::IsOnVehicle(), Unit::IsVehicle(), VehicleEntry::m_flags, ObjectGuid::ReadAsPacked(), sObjectMgr, VehicleInfo::SwitchSeat(), TRIGGERED_OLD_TRIGGERED, TYPEID_UNIT, and VEHICLE_FLAG_DISABLE_SWITCH.
HandleResetInstancesOpcode()
void WorldSession::HandleResetInstancesOpcode (WorldPacket & recv_data)
Definition at line 1254 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetGroup(), Object::GetObjectGuid(), INSTANCE_RESET_ALL, and Player::ResetInstances().
HandleResurrectResponseOpcode()
void WorldSession::HandleResurrectResponseOpcode (WorldPacket & recvPacket)
Definition at line 675 of file MiscHandler.cpp.
References Player::ClearResurrectRequestData(), DETAIL_LOG, GetPlayer(), and Player::ResurrectUsingRequestDataInit().
HandleRideVehicleInteract()
void WorldSession::HandleRideVehicleInteract (WorldPacket & recvPacket)
Definition at line 179 of file VehicleHandler.cpp.
References _player, Unit::CastSpell(), DEBUG_LOG, WorldObject::GetMap(), Map::GetPlayer(), ByteBuffer::hexlike(), Player::IsInGroup(), Unit::IsVehicle(), SPELL_RIDE_VEHICLE_HARDCODED, and TRIGGERED_OLD_TRIGGERED.
HandleSaveGuildEmblemOpcode()
void WorldSession::HandleSaveGuildEmblemOpcode (WorldPacket & recvPacket)
Definition at line 734 of file GuildHandler.cpp.
References DEBUG_LOG, ERR_GUILDEMBLEM_INVALIDVENDOR, ERR_GUILDEMBLEM_NOGUILD, ERR_GUILDEMBLEM_NOTENOUGHMONEY, ERR_GUILDEMBLEM_NOTGUILDMASTER, ERR_GUILDEMBLEM_SUCCESS, Guild::GetLeaderGuid(), Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), GOLD, Player::ModifyMoney(), Guild::Query(), SendSaveGuildEmblem(), Guild::SetEmblem(), sGuildMgr, and UNIT_NPC_FLAG_TABARDDESIGNER.
HandleSelfResOpcode()
void WorldSession::HandleSelfResOpcode (WorldPacket & recv_data)
Definition at line 656 of file SpellHandler.cpp.
References _player, Unit::CastSpell(), DEBUG_FILTER_LOG, Object::GetUInt32Value(), Unit::HasAuraType(), LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), PLAYER_SELF_RES_SPELL, Object::SetUInt32Value(), SPELL_AURA_PREVENT_RESURRECTION, sSpellTemplate, and TRIGGERED_NONE.
HandleSellItemOpcode()
void WorldSession::HandleSellItemOpcode (WorldPacket & recvPacket)
Definition at line 481 of file ItemHandler.cpp.
References _player, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, Player::AddItemToBuyBackSlot(), Item::CloneItem(), DEBUG_LOG, Player::GetAchievementMgr(), Item::GetBagSlot(), Item::GetCount(), Object::GetEntry(), Player::GetItemByGuid(), Player::GetLootGuid(), Player::GetNPCIfCanInteractWith(), Object::GetObjectGuid(), Item::GetOwnerGuid(), GetPlayer(), Item::GetProto(), Item::GetSlot(), Item::GetSpellCharges(), ObjectGuid::GetString(), Unit::InterruptNonMeleeSpells(), Item::IsBag(), Object::IsInWorld(), ITEM_CHANGED, Player::ItemRemovedQuestCheck(), MAX_ITEM_PROTO_SPELLS, Player::ModifyMoney(), Item::RemoveFromUpdateQueueOf(), Player::RemoveItem(), SELL_ERR_CANT_FIND_ITEM, SELL_ERR_CANT_FIND_VENDOR, SELL_ERR_CANT_SELL_ITEM, ItemPrototype::SellPrice, Object::SendCreateUpdateToPlayer(), Player::SendSellError(), Item::SetCount(), Item::SetState(), sLog, _Spell::SpellCharges, ItemPrototype::Spells, UNIT_NPC_FLAG_VENDOR, and AchievementMgr::UpdateAchievementCriteria().
HandleSetActionBarTogglesOpcode()
void WorldSession::HandleSetActionBarTogglesOpcode (WorldPacket & recv_data)
Definition at line 945 of file MiscHandler.cpp.
References GetPlayer(), PLAYER_FIELD_BYTES, PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES, Object::SetByteValue(), and sLog.
HandleSetActionButtonOpcode()
void WorldSession::HandleSetActionButtonOpcode (WorldPacket & recvPacket)
Definition at line 890 of file MiscHandler.cpp.
References ACTION_BUTTON_ACTION, ACTION_BUTTON_CMACRO, ACTION_BUTTON_EQSET, ACTION_BUTTON_ITEM, ACTION_BUTTON_MACRO, ACTION_BUTTON_SPELL, ACTION_BUTTON_TYPE, Player::addActionButton(), DEBUG_LOG, DETAIL_LOG, GetPlayer(), Player::removeActionButton(), and sLog.
HandleSetActiveMoverOpcode()
void WorldSession::HandleSetActiveMoverOpcode (WorldPacket & recv_data)
Definition at line 462 of file MovementHandler.cpp.
References _player, DEBUG_LOG, Object::GetGuidStr(), Player::GetMover(), Object::GetObjectGuid(), ObjectGuid::GetString(), ByteBuffer::hexlike(), m_anticheat, WorldObject::m_movementInfo, and sLog.
HandleSetActiveVoiceChannel()
void WorldSession::HandleSetActiveVoiceChannel (WorldPacket & recv_data)
Definition at line 40 of file VoiceChatHandler.cpp.
References DEBUG_LOG, ByteBuffer::hexlike(), and ByteBuffer::read_skip().
HandleSetAllowLowLevelRaidOpcode()
void WorldSession::HandleSetAllowLowLevelRaidOpcode (WorldPacket & recv_data)
Definition at line 957 of file GroupHandler.cpp.
References DEBUG_LOG, WorldPacket::GetOpcode(), GetPlayer(), and Player::SetAllowLowLevelRaid().
HandleSetAmmoOpcode()
void WorldSession::HandleSetAmmoOpcode (WorldPacket & recvPacket)
Definition at line 1037 of file ItemHandler.cpp.
References DEBUG_LOG, EQUIP_ERR_YOU_ARE_DEAD, GetPlayer(), Player::RemoveAmmo(), Player::SendEquipError(), and Player::SetAmmo().
HandleSetChannelWatchOpcode()
void WorldSession::HandleSetChannelWatchOpcode (WorldPacket & recvPacket)
Definition at line 347 of file ChannelHandler.cpp.
References DEBUG_LOG, WorldPacket::GetOpcode(), and WorldPacket::GetOpcodeName().
HandleSetContactNotesOpcode()
void WorldSession::HandleSetContactNotesOpcode (WorldPacket & recvPacket)
Definition at line 607 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetSocial(), and PlayerSocial::SetFriendNote().
HandleSetDungeonDifficultyOpcode()
void WorldSession::HandleSetDungeonDifficultyOpcode (WorldPacket & recv_data)
Definition at line 1267 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetDungeonDifficulty(), Player::GetGroup(), Object::GetGUIDLow(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), INSTANCE_RESET_CHANGE_DIFFICULTY, Map::IsDungeon(), LEVELREQUIREMENT_HEROIC, MAX_DUNGEON_DIFFICULTY, REGULAR_DIFFICULTY, Player::ResetInstances(), Player::SetDungeonDifficulty(), and sLog.
HandleSetFactionAtWarOpcode()
void WorldSession::HandleSetFactionAtWarOpcode (WorldPacket & recv_data)
Definition at line 1097 of file CharacterHandler.cpp.
References DEBUG_LOG, GetPlayer(), Player::GetReputationMgr(), and ReputationMgr::SetAtWar().
HandleSetFactionInactiveOpcode()
void WorldSession::HandleSetFactionInactiveOpcode (WorldPacket & recv_data)
Definition at line 1150 of file CharacterHandler.cpp.
References _player, DEBUG_LOG, Player::GetReputationMgr(), and ReputationMgr::SetInactive().
HandleSetGuildBankTabText()
void WorldSession::HandleSetGuildBankTabText (WorldPacket & recv_data)
Definition at line 1219 of file GuildHandler.cpp.
References DEBUG_LOG, Player::GetGuildId(), GetPlayer(), Guild::GetPurchasedTabs(), Guild::SetGuildBankTabText(), and sGuildMgr.
HandleSetPlayerDeclinedNamesOpcode()
void WorldSession::HandleSetPlayerDeclinedNamesOpcode (WorldPacket & recv_data)
Definition at line 1258 of file CharacterHandler.cpp.
References Database::BeginTransaction(), CharacterDatabase, ObjectMgr::CheckDeclinedNames(), Database::CommitTransaction(), Database::escape_string(), ObjectGuid::GetCounter(), GetMainPartOfName(), isCyrillicCharacter(), DeclinedName::name, normalizePlayerName(), Database::PExecute(), SendPacket(), SMSG_SET_PLAYER_DECLINED_NAMES_RESULT, sObjectMgr, and Utf8toWStr().
HandleSetRaidDifficultyOpcode()
void WorldSession::HandleSetRaidDifficultyOpcode (WorldPacket & recv_data)
Definition at line 1312 of file MiscHandler.cpp.
References _player, DEBUG_LOG, Player::GetDifficulty(), Map::GetEntry(), Player::GetGroup(), Object::GetGUIDLow(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), INSTANCE_RESET_CHANGE_DIFFICULTY, Map::IsDungeon(), MapEntry::IsDynamicDifficultyMap(), LEVELREQUIREMENT_HEROIC, MAX_RAID_DIFFICULTY, REGULAR_DIFFICULTY, Player::ResetInstances(), Player::SetRaidDifficulty(), and sLog.
HandleSetSavedInstanceExtend()
void WorldSession::HandleSetSavedInstanceExtend (WorldPacket & recv_data)
Definition at line 1586 of file MiscHandler.cpp.
References DEBUG_LOG, EXTEND_STATE_EXPIRED, EXTEND_STATE_EXTENDED, EXTEND_STATE_NORMAL, InstancePlayerBind::extendState, GetPlayer(), InstancePlayerBind::perm, and InstancePlayerBind::state.
HandleSetSelectionOpcode()
void WorldSession::HandleSetSelectionOpcode (WorldPacket & recvPacket)
Definition at line 392 of file MiscHandler.cpp.
References _player, Unit::GetFaction(), Player::GetMover(), Player::GetReputationMgr(), ObjectAccessor::GetUnit(), Player::SetSelectionGuid(), ReputationMgr::SetVisible(), and sFactionTemplateStore.
HandleSetSheathedOpcode()
void WorldSession::HandleSetSheathedOpcode (WorldPacket & recvPacket)
Definition at line 64 of file CombatHandler.cpp.
References DEBUG_LOG, GetPlayer(), MAX_SHEATH_STATE, Player::SetSheath(), and sLog.
HandleSetTargetOpcode()
void WorldSession::HandleSetTargetOpcode (WorldPacket & recvPacket)
Definition at line 375 of file MiscHandler.cpp.
References _player, Unit::GetFaction(), Player::GetReputationMgr(), ObjectAccessor::GetUnit(), Unit::SetTargetGuid(), ReputationMgr::SetVisible(), and sFactionTemplateStore.
HandleSetTaxiBenchmarkOpcode()
void WorldSession::HandleSetTaxiBenchmarkOpcode (WorldPacket & recv_data)
Definition at line 1484 of file MiscHandler.cpp.
References _player, DEBUG_LOG, PLAYER_FLAGS, PLAYER_FLAGS_TAXI_BENCHMARK, Object::RemoveFlag(), and Object::SetFlag().
HandleSetTitleOpcode()
void WorldSession::HandleSetTitleOpcode (WorldPacket & recv_data)
Definition at line 1235 of file MiscHandler.cpp.
References DEBUG_LOG, GetPlayer(), MAX_TITLE_INDEX, PLAYER_CHOSEN_TITLE, and Object::SetUInt32Value().
HandleSetTradeGoldOpcode()
void WorldSession::HandleSetTradeGoldOpcode (WorldPacket & recvPacket)
Definition at line 660 of file TradeHandler.cpp.
References _player, Player::GetTradeData(), and TradeData::SetMoney().
HandleSetTradeItemOpcode()
void WorldSession::HandleSetTradeItemOpcode (WorldPacket & recvPacket)
Definition at line 674 of file TradeHandler.cpp.
References _player, Item::CanBeTraded(), Player::GetItemByPos(), Object::GetObjectGuid(), TradeData::HasItem(), Player::m_trade, SendTradeStatus(), TradeData::SetItem(), TradeStatusInfo::Status, TRADE_SLOT_COUNT, TRADE_SLOT_NONTRADED, and TRADE_STATUS_TRADE_CANCELED.
HandleSetWatchedFactionOpcode()
void WorldSession::HandleSetWatchedFactionOpcode (WorldPacket & recv_data)
Definition at line 1142 of file CharacterHandler.cpp.
References DEBUG_LOG, GetPlayer(), PLAYER_FIELD_WATCHED_FACTION_INDEX, and Object::SetInt32Value().
HandleShowingCloakOpcode()
void WorldSession::HandleShowingCloakOpcode (WorldPacket & recv_data)
Definition at line 1166 of file CharacterHandler.cpp.
References _player, DEBUG_LOG, WorldObject::GetName(), PLAYER_FLAGS, PLAYER_FLAGS_HIDE_CLOAK, and Object::ToggleFlag().
HandleShowingHelmOpcode()
void WorldSession::HandleShowingHelmOpcode (WorldPacket & recv_data)
Definition at line 1160 of file CharacterHandler.cpp.
References _player, DEBUG_LOG, WorldObject::GetName(), PLAYER_FLAGS, PLAYER_FLAGS_HIDE_HELM, and Object::ToggleFlag().
HandleSocketOpcode()
void WorldSession::HandleSocketOpcode (WorldPacket & recv_data)
Definition at line 1211 of file ItemHandler.cpp.
References _player, Player::ApplyEnchantment(), BONUS_ENCHANTMENT_SLOT, Player::CanEquipUniqueItem(), _Socket::Color, GemPropertiesEntry::color, DEBUG_LOG, Player::DestroyItem(), EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED, ItemPrototype::Flags, Item::GemsFitSockets(), Item::GetEnchantmentId(), Object::GetEntry(), Player::GetItemByGuid(), ObjectMgr::GetItemPrototype(), Object::GetObjectGuid(), Item::GetProto(), Item::GetSlot(), Item::IsEquipped(), ObjectGuid::IsItem(), ITEM_FLAG_UNIQUE_EQUIPPABLE, ItemPrototype::ItemId, ItemPrototype::ItemLimitCategory, MAX_GEM_SOCKETS, NULL_SLOT, PRISMATIC_ENCHANTMENT_SLOT, Player::SendEquipError(), Item::SendUpdateSockets(), Item::SetEnchantment(), sGemPropertiesStore, sItemLimitCategoryStore, SOCK_ENCHANTMENT_SLOT, ItemPrototype::Socket, SOCKET_COLOR_META, ItemPrototype::socketBonus, sSpellItemEnchantmentStore, and Player::ToggleMetaGemsActive().
HandleSpellClick()
void WorldSession::HandleSpellClick (WorldPacket & recv_data)
Definition at line 673 of file SpellHandler.cpp.
References _player, Unit::CastSpell(), Map::GetAnyTypeCreature(), Object::GetEntry(), WorldObject::GetMap(), Map::IsDungeon(), Unit::IsInCombat(), sLog, sObjectMgr, sScriptDevAIMgr, and TRIGGERED_OLD_TRIGGERED.
HandleSpiritHealerActivateOpcode()
void WorldSession::HandleSpiritHealerActivateOpcode (WorldPacket & recvPacket)
Definition at line 392 of file NPCHandler.cpp.
References DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), SendSpiritResurrect(), and UNIT_NPC_FLAG_SPIRITHEALER.
HandleSplitItemOpcode()
void WorldSession::HandleSplitItemOpcode (WorldPacket & recvPacket)
Definition at line 30 of file ItemHandler.cpp.
References _player, EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, EQUIP_ERR_ITEM_NOT_FOUND, Player::IsValidPos(), Player::SendEquipError(), and Player::SplitItem().
HandleStablePet()
void WorldSession::HandleStablePet (WorldPacket & recvPacket)
Definition at line 613 of file NPCHandler.cpp.
References _player, Database::BeginTransaction(), CharacterDatabase, CheckStableMaster(), Database::CommitTransaction(), Database::CreateStatement(), DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), Object::GetObjectGuid(), Unit::GetPet(), Pet::getPetType(), GetPlayer(), Player::GetTemporaryUnsummonedPetNumber(), Field::GetUInt32(), HUNTER_PET, Unit::IsAlive(), QueryResult::NextRow(), PET_SAVE_AS_CURRENT, PET_SAVE_FIRST_STABLE_SLOT, PET_SAVE_LAST_STABLE_SLOT, PET_SAVE_NOT_IN_SLOT, PETTAME_DEAD, PETTAME_INVALIDCREATURE, SqlStatement::PExecute(), Database::PQuery(), Player::SendPetTameFailure(), SendStableResult(), Player::SetTemporaryUnsummonedPetNumber(), SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_TARGETS_DEAD, STABLE_ERR_STABLE, STABLE_SUCCESS_STABLE, Pet::TryLoadFromDB(), and Pet::Unsummon().
HandleStableRevivePet()
void WorldSession::HandleStableRevivePet (WorldPacket & recvPacket)
Definition at line 869 of file NPCHandler.cpp.
References DEBUG_LOG.
HandleStableSwapPet()
void WorldSession::HandleStableSwapPet (WorldPacket & recvPacket)
Definition at line 874 of file NPCHandler.cpp.
References _player, Database::BeginTransaction(), Player::CanTameExoticPets(), CharacterDatabase, CheckStableMaster(), Database::CommitTransaction(), Database::CreateStatement(), DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), ObjectMgr::GetCreatureTemplate(), Object::GetGUIDLow(), Object::GetObjectGuid(), Unit::GetPet(), Pet::GetPetSpawnPosition(), Pet::getPetType(), Player::GetTemporaryUnsummonedPetNumber(), Field::GetUInt32(), HUNTER_PET, Unit::IsAlive(), CreatureInfo::isTameable(), Pet::LoadPetFromDB(), PET_SAVE_AS_CURRENT, PET_SAVE_NOT_IN_SLOT, PETTAME_DEAD, PETTAME_INVALIDCREATURE, SqlStatement::PExecute(), Database::PQuery(), Player::SendPetTameFailure(), SendStableResult(), SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_TARGETS_DEAD, STABLE_ERR_STABLE, STABLE_SUCCESS_UNSTABLE, Pet::TryLoadFromDB(), and Pet::Unsummon().
HandleStandStateChangeOpcode()
void WorldSession::HandleStandStateChangeOpcode (WorldPacket & recvPacket)
Definition at line 412 of file MiscHandler.cpp.
References _player, AURA_INTERRUPT_FLAG_ANIM_CANCELS, Object::HasFlag(), Unit::InterruptSpellsAndAurasWithInterruptFlags(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_ANIM, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_SIT, UNIT_STAND_STATE_SLEEP, and UNIT_STAND_STATE_STAND.
HandleSummonResponseOpcode()
void WorldSession::HandleSummonResponseOpcode (WorldPacket & recv_data)
Definition at line 648 of file MovementHandler.cpp.
References _player, Unit::IsAlive(), Unit::IsInCombat(), and Player::SummonIfPossible().
HandleSwapInvItemOpcode()
void WorldSession::HandleSwapInvItemOpcode (WorldPacket & recvPacket)
Definition at line 63 of file ItemHandler.cpp.
References _player, EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, EQUIP_ERR_ITEM_NOT_FOUND, INVENTORY_SLOT_BAG_0, Player::IsValidPos(), Player::SendEquipError(), and Player::SwapItem().
HandleSwapItem()
void WorldSession::HandleSwapItem (WorldPacket & recvPacket)
Definition at line 112 of file ItemHandler.cpp.
References _player, EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT, EQUIP_ERR_ITEM_NOT_FOUND, Player::IsValidPos(), Player::SendEquipError(), and Player::SwapItem().
HandleTabardVendorActivateOpcode()
void WorldSession::HandleTabardVendorActivateOpcode (WorldPacket & recvPacket)
Definition at line 47 of file NPCHandler.cpp.
References DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), SendTabardVendorActivate(), and UNIT_NPC_FLAG_TABARDDESIGNER.
HandleTalentWipeConfirmOpcode()
void WorldSession::HandleTalentWipeConfirmOpcode (WorldPacket & recvPacket)
Definition at line 62 of file SkillHandler.cpp.
References _player, Creature::CanTrainAndResetTalentsOf(), Pet::CastOwnerTalentAuras(), Unit::CastSpell(), DEBUG_LOG, DETAIL_LOG, Player::GetNPCIfCanInteractWith(), Unit::GetPet(), GetPlayer(), ObjectGuid::GetString(), MSG_TALENT_WIPE_CONFIRM, Player::resetTalents(), SendPacket(), Player::SendTalentsInfoData(), TRIGGERED_OLD_TRIGGERED, and UNIT_NPC_FLAG_TRAINER.
HandleTaxiNodeStatusQueryOpcode()
void WorldSession::HandleTaxiNodeStatusQueryOpcode (WorldPacket & recvPacket)
Definition at line 30 of file TaxiHandler.cpp.
References DEBUG_LOG, and SendTaxiStatus().
HandleTaxiQueryAvailableNodes()
void WorldSession::HandleTaxiQueryAvailableNodes (WorldPacket & recvPacket)
Definition at line 66 of file TaxiHandler.cpp.
References DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), SendLearnNewTaxiNode(), SendTaxiMenu(), and UNIT_NPC_FLAG_FLIGHTMASTER.
HandleTextEmoteOpcode()
void WorldSession::HandleTextEmoteOpcode (WorldPacket & recvPacket)
Definition at line 652 of file ChatHandler.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, Unit::AI(), AURA_INTERRUPT_FLAG_ANIM_CANCELS, CONFIG_FLOAT_LISTEN_RANGE_TEXTEMOTE, EMOTE_ONESHOT_NONE, EMOTE_STATE_KNEEL, EMOTE_STATE_SIT, EMOTE_STATE_SLEEP, Player::GetAchievementMgr(), GetMangosString(), WorldObject::GetMap(), GetPlayer(), Map::GetUnit(), Unit::HandleEmote(), Unit::InterruptSpellsAndAurasWithInterruptFlags(), LANG_WAIT_BEFORE_SPEAKING, m_muteTime, UnitAI::ReceiveEmote(), secsToTimeString(), sEmotesTextStore, SendNotification(), sWorld, EmotesTextEntry::textid, UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_ANIM, AchievementMgr::UpdateAchievementCriteria(), and Cell::VisitWorldObjects().
HandleTimeSyncResp()
void WorldSession::HandleTimeSyncResp (WorldPacket & recv_data)
Definition at line 822 of file MovementHandler.cpp.
References ComputeNewClockDelta(), DEBUG_LOG, WorldTimer::getMSTimeDiff(), WorldPacket::GetReceivedTime(), m_pendingTimeSyncRequests, and m_timeSyncClockDeltaQueue.
HandleTogglePvP()
void WorldSession::HandleTogglePvP (WorldPacket & recvPacket)
Definition at line 334 of file MiscHandler.cpp.
References Object::ApplyModFlag(), AREA_FLAG_SANCTUARY, GetAreaEntryByAreaID(), GetPlayer(), WorldObject::GetZoneId(), PLAYER_FLAGS, PLAYER_FLAGS_PVP_DESIRED, ByteBuffer::size(), Object::ToggleFlag(), and Player::UpdatePvP().
HandleTotemDestroyed()
void WorldSession::HandleTotemDestroyed (WorldPacket & recv_data)
Definition at line 639 of file SpellHandler.cpp.
References _player, GetPlayer(), Player::IsSelfMover(), and MAX_TOTEM_SLOT.
HandleTrainerBuySpellOpcode()
void WorldSession::HandleTrainerBuySpellOpcode (WorldPacket & recvPacket)
Definition at line 242 of file NPCHandler.cpp.
References _player, Unit::CastSpell(), DEBUG_LOG, TrainerSpellData::Find(), Player::GetMoney(), Player::GetNPCIfCanInteractWith(), Object::GetObjectGuid(), GetPlayer(), Player::GetReputationPriceDiscount(), ObjectGuid::GetString(), Creature::GetTrainerSpells(), Player::GetTrainerSpellState(), Creature::GetTrainerTemplateSpells(), WorldPacket::Initialize(), TrainerSpell::IsCastable(), TrainerSpell::isProvidedReqLevel, Player::IsSpellFitByClassAndRace(), Creature::IsTrainerOf(), TrainerSpell::learnedSpell, Player::learnSpell(), Player::ModifyMoney(), TrainerSpell::reqLevel, SendPacket(), SendPlaySpellVisual(), SMSG_PLAY_SPELL_IMPACT, SMSG_TRAINER_BUY_SUCCEEDED, TrainerSpell::spell, TrainerSpell::spellCost, TRAINER_SPELL_GREEN, TRIGGERED_OLD_TRIGGERED, and UNIT_NPC_FLAG_TRAINER.
HandleTrainerListOpcode()
void WorldSession::HandleTrainerListOpcode (WorldPacket & recvPacket)
Definition at line 97 of file NPCHandler.cpp.
References SendTrainerList().
HandleTurnInPetitionOpcode()
void WorldSession::HandleTurnInPetitionOpcode (WorldPacket & recv_data)
Collect petition info data
Definition at line 715 of file PetitionsHandler.cpp.
References _player, ArenaTeam::AddMember(), Guild::AddMember(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CONFIG_UINT32_MIN_PETITION_SIGNS, ArenaTeam::Create(), Guild::Create(), DEBUG_LOG, Player::DestroyItem(), ERR_ALREADY_IN_ARENA_TEAM, ERR_ARENA_TEAM_CREATE_S, ERR_ARENA_TEAM_NAME_EXISTS_S, ERR_GUILD_NAME_EXISTS_S, QueryResult::Fetch(), Player::GetArenaTeamId(), Item::GetBagSlot(), ObjectGuid::GetCounter(), Field::GetCppString(), Object::GetGuidStr(), Player::GetGuildId(), Player::GetItemByGuid(), Guild::GetLowestRank(), Object::GetObjectGuid(), QueryResult::GetRowCount(), Player::GetSession(), Item::GetSlot(), ArenaTeam::GetSlotByType(), ObjectGuid::GetString(), Field::GetUInt32(), GUILD_CREATE_S, GUILD_EVENT_LOG_JOIN_GUILD, GUILD_FOUNDER_S, HIGHGUID_PLAYER, IsArenaTypeValid(), Guild::LogGuildEvent(), MAX_ARENA_SLOT, QueryResult::NextRow(), PETITION_TURN_ALREADY_IN_GUILD, PETITION_TURN_NEED_MORE_SIGNATURES, PETITION_TURN_OK, Database::PExecute(), Database::PQuery(), SendArenaTeamCommandResult(), SendGuildCommandResult(), SendPacket(), ArenaTeam::SetEmblem(), sGuildMgr, sLog, SMSG_TURN_IN_PETITION_RESULTS, sObjectMgr, and sWorld.
HandleTutorialClearOpcode()
void WorldSession::HandleTutorialClearOpcode (WorldPacket & recv_data)
Definition at line 1130 of file CharacterHandler.cpp.
References SetTutorialInt().
HandleTutorialFlagOpcode()
void WorldSession::HandleTutorialFlagOpcode (WorldPacket & recv_data)
Definition at line 1110 of file CharacterHandler.cpp.
References GetTutorialInt(), and SetTutorialInt().
HandleTutorialResetOpcode()
void WorldSession::HandleTutorialResetOpcode (WorldPacket & recv_data)
Definition at line 1136 of file CharacterHandler.cpp.
References SetTutorialInt().
HandleUITimeRequestOpcode()
void WorldSession::HandleUITimeRequestOpcode (WorldPacket & recv_data)
Definition at line 1516 of file MiscHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_UI_TIME.
HandleUnacceptTradeOpcode()
void WorldSession::HandleUnacceptTradeOpcode (WorldPacket & recvPacket)
Definition at line 510 of file TradeHandler.cpp.
References _player, Player::m_trade, and TradeData::SetAccepted().
HandleUnlearnSkillOpcode()
void WorldSession::HandleUnlearnSkillOpcode (WorldPacket & recvPacket)
Definition at line 94 of file SkillHandler.cpp.
References SkillRaceClassInfoEntry::flags, GetPlayer(), Player::GetSkillInfo(), Player::SetSkillStep(), and SKILL_FLAG_CAN_UNLEARN.
HandleUnstablePet()
void WorldSession::HandleUnstablePet (WorldPacket & recvPacket)
Definition at line 716 of file NPCHandler.cpp.
References _player, Database::BeginTransaction(), Player::CanTameExoticPets(), CharacterDatabase, CheckStableMaster(), Database::CommitTransaction(), Database::CreateStatement(), DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), ObjectMgr::GetCreatureTemplate(), Object::GetGUIDLow(), Object::GetGuidStr(), Object::GetObjectGuid(), Unit::GetPet(), Pet::GetPetSpawnPosition(), Pet::getPetType(), Player::GetTemporaryUnsummonedPetNumber(), Field::GetUInt32(), HUNTER_PET, Unit::IsAlive(), CreatureInfo::isTameable(), Pet::LoadPetFromDB(), PET_SAVE_AS_CURRENT, PET_SAVE_FIRST_STABLE_SLOT, PET_SAVE_LAST_STABLE_SLOT, PET_SAVE_NOT_IN_SLOT, PETTAME_ANOTHERSUMMONACTIVE, PETTAME_DEAD, SqlStatement::PExecute(), Database::PQuery(), Player::SendPetTameFailure(), SendStableResult(), Player::SetTemporaryUnsummonedPetNumber(), sLog, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_TARGETS_DEAD, STABLE_ERR_STABLE, STABLE_SUCCESS_UNSTABLE, Pet::TryLoadFromDB(), and Pet::Unsummon().
HandleUpdateAccountData()
void WorldSession::HandleUpdateAccountData (WorldPacket & recvPacket)
Definition at line 797 of file MiscHandler.cpp.
References ByteBuffer::contents(), DEBUG_LOG, DETAIL_LOG, NUM_ACCOUNT_DATA_TYPES, ByteBuffer::resize(), ByteBuffer::rpos(), SendPacket(), SetAccountData(), ByteBuffer::size(), sLog, SMSG_UPDATE_ACCOUNT_DATA_COMPLETE, and ByteBuffer::wpos().
HandleUpdateMissileTrajectory()
void WorldSession::HandleUpdateMissileTrajectory (WorldPacket & recv_data)
Definition at line 791 of file SpellHandler.cpp.
References CURRENT_GENERIC_SPELL, DEBUG_FILTER_LOG, Unit::GetCurrentSpell(), SpellCastTargets::getElevation(), GetPlayer(), SpellCastTargets::getSpeed(), ObjectAccessor::GetUnit(), HandleMovementOpcodes(), SpellEntry::Id, LOG_FILTER_SPELL_CAST, SpellCastTargets::m_destPos, Spell::m_spellInfo, SpellCastTargets::m_srcPos, SpellCastTargets::m_targetMask, Spell::m_targets, MSG_MOVE_STOP, SpellCastTargets::setDestination(), SpellCastTargets::setElevation(), WorldPacket::SetOpcode(), SpellCastTargets::setSource(), SpellCastTargets::setSpeed(), TARGET_FLAG_DEST_LOCATION, Position::x, Position::y, and Position::z.
HandleUseItemOpcode()
void WorldSession::HandleUseItemOpcode (WorldPacket & recvPacket)
Definition at line 34 of file SpellHandler.cpp.
References _player, AURA_INTERRUPT_FLAG_ITEM_USE, BIND_QUEST_ITEM, BIND_WHEN_PICKED_UP, BIND_WHEN_USE, ItemPrototype::Bonding, Player::CanUseItem(), Player::CastItemUseSpell(), ItemPrototype::Class, DETAIL_LOG, EFFECT_INDEX_0, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_NONE, EQUIP_ERR_NOT_DURING_ARENA_MATCH, EQUIP_ERR_NOT_IN_COMBAT, EQUIP_ERR_OBJECT_IS_BUSY, EQUIP_ERR_OK, ItemPrototype::Flags, Object::GetEntry(), Player::GetItemByPos(), Player::GetLastPotionId(), Object::GetObjectGuid(), Item::GetProto(), SpellCastTargets::getUnitTarget(), HandleClientCastFlags(), Player::InArena(), ItemPrototype::InventoryType, INVTYPE_NON_EQUIP, IsAreaEffectTarget(), Item::IsEquipped(), Unit::IsInCombat(), Item::IsInTrade(), IsNonCombatSpell(), IsPointEffectTarget(), Item::IsPotion(), Player::IsSelfMover(), Item::IsSoulBound(), Item::IsTargetValidForItemUse(), ITEM_CHANGED, ITEM_CLASS_CONSUMABLE, ITEM_FLAG_IGNORE_DEFAULT_ARENA_RESTRICTIONS, SQLStorage::LookupEntry(), MAX_GLYPH_SLOT_INDEX, SpellCastTargets::ReadForCaster(), Unit::RemoveAurasWithInterruptFlags(), ByteBuffer::rpos(), Spell::SendCastResult(), Player::SendEquipError(), Item::SetBinding(), Item::SetState(), ByteBuffer::size(), SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_NO_VALID_TARGETS, ItemPrototype::Spells, sScriptDevAIMgr, sSpellTemplate, SpellCastTargets::Update(), and ByteBuffer::wpos().
HandleVoiceSessionEnableOpcode()
void WorldSession::HandleVoiceSessionEnableOpcode (WorldPacket & recv_data)
Definition at line 24 of file VoiceChatHandler.cpp.
References DEBUG_LOG, ByteBuffer::hexlike(), and ByteBuffer::read_skip().
HandleWardenDataOpcode()
void WorldSession::HandleWardenDataOpcode (WorldPacket & recv_data)
Definition at line 1303 of file WorldSession.cpp.
References m_anticheat.
HandleWhoisOpcode()
void WorldSession::HandleWhoisOpcode (WorldPacket & recv_data)
Definition at line 1073 of file MiscHandler.cpp.
References _player, DEBUG_LOG, QueryResult::Fetch(), GetAccountId(), Field::GetCppString(), GetPlayer(), GetSecurity(), Player::GetSession(), LANG_ACCOUNT_FOR_PLAYER_NOT_FOUND, LANG_NEED_CHARACTER_NAME, LANG_PLAYER_NOT_EXIST_OR_OFFLINE, LANG_YOU_NOT_HAVE_PERMISSION, LoginDatabase, normalizePlayerName(), Database::PQuery(), SEC_ADMINISTRATOR, SendNotification(), SendPacket(), SMSG_WHOIS, and sObjectMgr.
HandleWhoOpcode()
void WorldSession::HandleWhoOpcode (WorldPacket & recvPacket)
Definition at line 76 of file MiscHandler.cpp.
References _player, CONFIG_BOOL_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST, CONFIG_UINT32_MAX_WHOLIST_RETURNS, DEBUG_LOG, GetAreaEntryByAreaID(), Unit::getClass(), Unit::getGender(), Player::GetGuildId(), Unit::GetLevel(), WorldObject::GetName(), GetPlayer(), Unit::getRace(), GetSecurity(), Player::GetSession(), GetSessionDbcLocale(), Player::GetTeam(), WorldObject::GetZoneId(), Object::IsInWorld(), Player::IsVisibleGloballyFor(), MAX_LEVEL, ByteBuffer::put(), SEC_PLAYER, SendPacket(), sGuildMgr, SMSG_WHO, sObjectAccessor, sTicketMgr, STRONG_MAX_LEVEL, sWorld, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
HandleWorldTeleportOpcode()
void WorldSession::HandleWorldTeleportOpcode (WorldPacket & recv_data)
Definition at line 1035 of file MiscHandler.cpp.
References DEBUG_LOG, GetPlayer(), GetSecurity(), LANG_YOU_NOT_HAVE_PERMISSION, SEC_ADMINISTRATOR, SendNotification(), and Player::TeleportTo().
HandleWrapItemOpcode()
void WorldSession::HandleWrapItemOpcode (WorldPacket & recvPacket)
Definition at line 1097 of file ItemHandler.cpp.
References _player, Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), DEBUG_LOG, Player::DestroyItemCount(), EQUIP_ERR_BAGS_CANT_BE_WRAPPED, EQUIP_ERR_BOUND_CANT_BE_WRAPPED, EQUIP_ERR_CANT_DO_RIGHT_NOW, EQUIP_ERR_EQUIPPED_CANT_BE_WRAPPED, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_STACKABLE_CANT_BE_WRAPPED, EQUIP_ERR_UNIQUE_CANT_BE_WRAPPED, EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED, ItemPrototype::Flags, ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetGuidValue(), Player::GetItemByPos(), Item::GetMaxStackCount(), Object::GetObjectGuid(), Item::GetOwnerGuid(), Item::GetProto(), Item::GetState(), Object::GetUInt32Value(), Item::IsBag(), Item::IsEquipped(), Unit::IsNonMeleeSpellCasted(), Item::IsSoulBound(), ITEM_CHANGED, ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, ITEM_FLAG_IS_WRAPPER, ITEM_NEW, ItemPrototype::MaxCount, Database::PExecute(), Item::RemoveFromUpdateQueueOf(), Player::SaveItemToInventory(), Player::SendEquipError(), Object::SetEntry(), Object::SetGuidValue(), Item::SetState(), and Object::SetUInt32Value().
HandleZoneUpdateOpcode()
void WorldSession::HandleZoneUpdateOpcode (WorldPacket & recvPacket)
Definition at line 359 of file MiscHandler.cpp.
References _player, CONFIG_BOOL_TAXI_FLIGHT_CHAT_FIX, DETAIL_LOG, Object::ForceValuesUpdateAtIndex(), GetPlayer(), IsInitialZoneUpdated(), Unit::IsTaxiFlying(), m_initialZoneUpdated, Player::SetDelayedZoneUpdate(), sWorld, and UNIT_FIELD_FLAGS.
HasAccountFlag()
bool WorldSession::HasAccountFlag (uint32 flags) const inline
Definition at line 292 of file WorldSession.h.
References m_accountFlags.
Referenced by HandleAnticheatCheatinformCommand(), and HandleAnticheatSpaminformCommand().
IncrementOrderCounter()
void WorldSession::IncrementOrderCounter () inline
Definition at line 479 of file WorldSession.h.
References m_orderCounter.
Referenced by SendKnockBack(), Unit::SendMoveRoot(), Unit::SendTeleportPacket(), and Unit::SetSpeedRate().
InitializeAnticheat()
void WorldSession::InitializeAnticheat (const BigNumber & K)
Definition at line 1279 of file WorldSession.cpp.
References m_anticheat, and sAnticheatLib.
Referenced by WorldSocket::HandleAuthSession().
IsARecruiter()
bool WorldSession::IsARecruiter () const inline
Definition at line 483 of file WorldSession.h.
References m_isRecruiter.
Referenced by HandleAcceptLevelGrant(), and HandleGrantLevel().
IsInitialZoneUpdated()
bool WorldSession::IsInitialZoneUpdated () inline
Definition at line 288 of file WorldSession.h.
References m_initialZoneUpdated.
Referenced by HandleZoneUpdateOpcode().
isLogingOut()
bool WorldSession::isLogingOut () const inline
Is the user engaged in a log out process?
Definition at line 326 of file WorldSession.h.
References _logoutTime, and m_playerLogout.
Referenced by HandleInitiateTradeOpcode(), HandlePlayerLoginOpcode(), ChatHandler::HandleSendMessageCommand(), and Player::SaveToDB().
IsOffline()
bool WorldSession::IsOffline () const inline
Definition at line 258 of file WorldSession.h.
References m_sessionState, and WORLD_SESSION_STATE_OFFLINE.
Referenced by Update().
KickPlayer()
void WorldSession::KickPlayer (bool save = false, bool inPlace = false)
Kick a player out of the World.
Definition at line 788 of file WorldSession.cpp.
References _player, Unit::GetMaster(), Object::GetObjectGuid(), LogoutPlayer(), LogoutRequest(), m_kickSession, and m_playerSave.
Referenced by World::AddSession_(), World::BanAccount(), CheckChatMessage(), WardenWin::GetScanFlags(), Warden::HandleChallengeResponse(), ChatHandler::HandleCharacterEraseCommand(), HandleForceSpeedChangeAckOpcodes(), ChatHandler::HandleKickPlayerCommand(), HandleMoveWorldportAckOpcode(), Warden::HandlePacket(), HandlePlayerLogin(), ObjectAccessor::KickPlayer(), NullSessionAnticheat::RecordCheat(), NamreebAnticheat::SessionAnticheat::Update(), Warden::Update(), Update(), and NamreebAnticheat::SessionAnticheat::~SessionAnticheat().
LoadAccountData()
void WorldSession::LoadAccountData (QueryResult * result, uint32 mask)
Definition at line 969 of file WorldSession.cpp.
References AccountData::Data, QueryResult::Fetch(), Field::GetCppString(), Field::GetUInt32(), GLOBAL_CACHE_MASK, m_accountData, QueryResult::NextRow(), NUM_ACCOUNT_DATA_TYPES, sLog, and AccountData::Time.
Referenced by HandlePlayerLogin(), and LoadGlobalAccountData().
LoadGlobalAccountData()
void WorldSession::LoadGlobalAccountData ()
Definition at line 961 of file WorldSession.cpp.
References CharacterDatabase, GetAccountId(), GLOBAL_CACHE_MASK, LoadAccountData(), and Database::PQuery().
Referenced by WorldSocket::HandleAuthSession().
LoadTutorialsData()
void WorldSession::LoadTutorialsData ()
Definition at line 1060 of file WorldSession.cpp.
References CharacterDatabase, QueryResult::Fetch(), GetAccountId(), m_Tutorials, m_tutorialState, QueryResult::NextRow(), Database::PQuery(), TUTORIALDATA_NEW, and TUTORIALDATA_UNCHANGED.
Referenced by WorldSocket::HandleAuthSession().
LogoutPlayer()
void WorldSession::LogoutPlayer ()
Log the player out
Teleport to home if the player is in an invalid instance
Reset the online field in the account table
If the player is in a guild, update the guild roster and broadcast a logout message to other guild members
Remove pet
empty buyback items and save the player in the database
Leave all channels before player delete...
If the player is in a group (or invited), remove him. If the group if then only 1 person, disband the group.
Send update to group
Broadcast a logout message to the player's friends
Remove the player from the world
Send the 'logout complete' packet to the client
Since each account can only have one online character at any given time, ensure all characters for active account are marked as offline
Since each account can only have one online character at any given time, ensure all characters for active account are marked as offline
Definition at line 577 of file WorldSession.cpp.
References _logoutTime, _player, AURA_INTERRUPT_FLAG_LEAVE_WORLD, Player::BuildPlayerRepop(), CharacterDatabase, Player::CleanupChannels(), Player::CleanupsBeforeDelete(), Unit::CombatStopWithPets(), Database::CreateStatement(), DEBUG_LOG, Map::DeleteFromWorld(), HostileRefManager::deleteReferences(), FRIEND_OFFLINE, GE_SIGNED_OFF, GetAccountId(), Player::GetBattleGround(), Player::GetBattleGroundQueueTypeId(), Player::GetDeathTimer(), Player::GetGroup(), Object::GetGUIDLow(), Player::GetGuildId(), Unit::getHostileRefManager(), Player::GetLfgData(), WorldObject::GetMap(), WorldObject::GetName(), Object::GetObjectGuid(), Group::GetObjectGuid(), GetRemoteAddress(), Player::GetSocial(), LFGData::GetState(), HandleMoveWorldportAckOpcode(), Unit::HasAuraType(), Player::HasPendingBind(), Player::IsBeingTeleportedFar(), Player::IsGameMaster(), Unit::IsInCombat(), Object::IsInWorld(), Group::IsRaidGroup(), Player::KillPlayer(), LFG_STATE_QUEUED, LoginDatabase, Player::m_InstanceValid, m_kickSession, m_playerLogout, m_playerRecentlyLogout, m_playerSave, m_Socket, PET_SAVE_AS_CURRENT, SqlStatement::PExecute(), PLAYER_MAX_BATTLEGROUND_QUEUES, Map::Remove(), Unit::RemoveAurasWithInterruptFlags(), Player::RemoveBattleGroundQueueId(), Player::RemoveFromGroup(), Player::RemovePet(), Unit::RemoveSpellsCausingAura(), Player::RepopAtGraveyard(), Player::SaveToDB(), sBattleGroundMgr, SendPacket(), SetInCharSelection(), Player::SetPendingBind(), SetPlayer(), sGuildMgr, sLog, sLootMgr, SMSG_LOGOUT_COMPLETE, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_SPIRIT_OF_REDEMPTION, sSocialMgr, sTicketMgr, sWorld, Player::TeleportToHomebind(), and Player::UninviteFromGroup().
Referenced by HandleLogoutRequestOpcode(), KickPlayer(), PlayerbotMgr::RemoveBots(), Update(), and ~WorldSession().
LogoutRequest()
void WorldSession::LogoutRequest (time_t requestTime, bool saveToDB = true, bool kickSession = false) inline
Engage the logout process for the user.
Definition at line 329 of file WorldSession.h.
References _logoutTime, m_kickSession, and m_playerSave.
Referenced by HandleLogoutCancelOpcode(), HandleLogoutRequestOpcode(), HandlePlayerReconnect(), KickPlayer(), and SetOffline().
LogUnexpectedOpcode()
void WorldSession::LogUnexpectedOpcode (WorldPacket const & packet, const char * reason) const private
Logging helper for unexpected opcodes.
Definition at line 311 of file WorldSession.cpp.
References WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), and sLog.
Referenced by Update().
LogUnprocessedTail()
void WorldSession::LogUnprocessedTail (WorldPacket & packet) const private
Logging helper for unexpected opcodes.
Definition at line 320 of file WorldSession.cpp.
References WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), ByteBuffer::rpos(), SIZEFMTD, sLog, and ByteBuffer::wpos().
Referenced by ExecuteOpcode(), and QueuePacket().
moveItems()
void WorldSession::moveItems (Item * myItems[], Item * hisItems[]) private
Definition at line 124 of file TradeHandler.cpp.
References _player, Player::CanStoreItem(), CONFIG_BOOL_GM_LOG_TRADE, DEBUG_LOG, EQUIP_ERR_OK, GetAccountId(), Item::GetCount(), Object::GetEntry(), WorldObject::GetName(), Item::GetProto(), GetSecurity(), Player::GetSession(), Player::GetTrader(), Player::MoveItemToInventory(), ItemPrototype::Name1, NULL_BAG, NULL_SLOT, SEC_PLAYER, sLog, sWorld, and TRADE_SLOT_TRADED_COUNT.
Referenced by HandleAcceptTradeOpcode().
PlayerLoading()
bool WorldSession::PlayerLoading () const inline
Definition at line 261 of file WorldSession.h.
References m_playerLoading.
Referenced by HandlePlayerLoginOpcode(), Spell::SendCastResult(), and ReputationMgr::SendVisible().
PlayerLogout()
bool WorldSession::PlayerLogout () const inline
Definition at line 262 of file WorldSession.h.
References m_playerLogout.
Referenced by OutdoorPvP::HandlePlayerLeaveZone().
PlayerLogoutWithSave()
bool WorldSession::PlayerLogoutWithSave () const inline
Definition at line 263 of file WorldSession.h.
References m_playerLogout, and m_playerSave.
ProcessByteBufferException()
void WorldSession::ProcessByteBufferException (WorldPacket const & packet) private
Definition at line 328 of file WorldSession.cpp.
References _player, Messager< T >::AddMessage(), CHEAT_ACTION_INFO_LOG, CONFIG_BOOL_KICK_PLAYER_ON_BAD_PACKET, DEBUG_LOG, DETAIL_LOG, GetAccountId(), GetMessager(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), GetRemoteAddress(), ByteBuffer::hexlike(), ObjectAccessor::KickPlayer(), LOG_LVL_DEBUG, m_anticheat, sLog, and sWorld.
Referenced by ExecuteOpcode(), and QueuePacket().
ProcessMovementInfo()
bool WorldSession::ProcessMovementInfo (MovementInfo & movementInfo, Unit * mover, Player * plMover, WorldPacket & recv_data)
Definition at line 780 of file MovementHandler.cpp.
References CMSG_FORCE_MOVE_ROOT_ACK, CMSG_FORCE_MOVE_UNROOT_ACK, CMSG_MOVE_KNOCK_BACK_ACK, Movement::MoveSpline::Finalized(), MovementInfo::GetMovementFlags(), WorldPacket::GetOpcode(), Unit::HandleEmoteState(), Player::HandleFall(), HandleMoverRelocation(), Player::IsBeingTeleported(), Movement::MoveSpline::IsBoarding(), Player::IsLaunched(), Unit::IsStandUpOnMovementState(), Unit::IsTaxiFlying(), m_anticheat, MOVEFLAG_MASK_MOVING_OR_TURN, Unit::movespline, MSG_MOVE_FALL_LAND, MSG_MOVE_START_SWIM, Player::SetLaunched(), Unit::SetStandState(), UNIT_STAND_STATE_STAND, Player::UpdateFallInformationIfNeed(), and VerifyMovementInfo().
Referenced by HandleForceSpeedChangeAckOpcodes(), HandleMoveFlagChangeOpcode(), HandleMoveKnockBackAck(), HandleMovementOpcodes(), and HandleMoveRootAck().
QueuePacket()
void WorldSession::QueuePacket (std::unique_ptr< WorldPacket > new_packet)
Add an incoming packet to the queue.
Definition at line 258 of file WorldSession.cpp.
References OpcodeHandler::handler, LOG_LVL_DEBUG, LogUnprocessedTail(), m_recvQueue, m_recvQueueLock, m_recvQueueMap, m_recvQueueMapLock, opcodeTable, OpcodeHandler::packetProcessing, PROCESS_IMMEDIATE, PROCESS_MAP_THREAD, ProcessByteBufferException(), sLog, and sWorld.
Referenced by PlayerbotAI::_HandleCommandPet(), PlayerbotAI::AddAuction(), PlayerbotAI::CastSpell(), PlayerbotAI::DoLoot(), PlayerbotAI::HandleBotOutgoingPacket(), PlayerbotAI::InterruptCurrentCastingSpell(), PlayerbotMgr::OnBotLogin(), WorldSocket::ProcessIncomingData(), PlayerbotAI::Repair(), PlayerbotAI::SendWhisper(), PlayerbotAI::Talent(), PlayerbotAI::TradeCopper(), PlayerbotAI::TradeItem(), and PlayerbotAI::UseItem().
RemoveAccountFlag()
void WorldSession::RemoveAccountFlag (uint32 flags) inline
Definition at line 294 of file WorldSession.h.
References m_accountFlags.
Referenced by HandleAnticheatCheatinformCommand(), and HandleAnticheatSpaminformCommand().
RequestNewSocket()
bool WorldSession::RequestNewSocket (WorldSocket * socket)
Definition at line 162 of file WorldSession.cpp.
References m_recvQueueLock, m_requestSocket, m_sessionState, MaNGOS::Socket::shared(), and WORLD_SESSION_STATE_CREATED.
Referenced by WorldSocket::HandleAuthSession().
ResetClientTimeDelay()
void WorldSession::ResetClientTimeDelay () inline
Definition at line 468 of file WorldSession.h.
References m_clientTimeDelay.
Referenced by WorldSocket::HandlePing().
ResetTimeSync()
void WorldSession::ResetTimeSync ()
Definition at line 1260 of file WorldSession.cpp.
References m_pendingTimeSyncRequests, and m_timeSyncNextCounter.
Referenced by Player::SendInitialPacketsAfterAddToMap().
SaveTutorialsData()
void WorldSession::SaveTutorialsData ()
Definition at line 1095 of file WorldSession.cpp.
References SqlStatement::addUInt32(), CharacterDatabase, Database::CreateStatement(), SqlStatement::Execute(), GetAccountId(), m_Tutorials, m_tutorialState, TUTORIALDATA_CHANGED, TUTORIALDATA_NEW, and TUTORIALDATA_UNCHANGED.
Referenced by Player::SaveToDB().
SendAccountDataTimes()
void WorldSession::SendAccountDataTimes (uint32 mask)
Definition at line 1048 of file WorldSession.cpp.
References GetAccountData(), NUM_ACCOUNT_DATA_TYPES, SendPacket(), and SMSG_ACCOUNT_DATA_TIMES.
Referenced by HandlePlayerLogin(), HandlePlayerReconnect(), HandleReadyForAccountDataTimesOpcode(), and World::RemoveQueuedSession().
SendActivateTaxiReply()
void WorldSession::SendActivateTaxiReply (ActivateTaxiReply reply) const
Definition at line 132 of file TaxiHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_ACTIVATETAXIREPLY.
Referenced by Player::ActivateTaxiPathTo(), HandleActivateTaxiExpressOpcode(), and HandleActivateTaxiOpcode().
SendAreaTriggerMessage()
void WorldSession::SendAreaTriggerMessage (const char * Text, ...) const
Definition at line 861 of file WorldSession.cpp.
References SendPacket(), and SMSG_AREA_TRIGGER_MESSAGE.
Referenced by ChatHandler::HandleSendMessageCommand(), and Player::SendTransferAbortedByLockStatus().
SendArenaTeamCommandResult()
void WorldSession::SendArenaTeamCommandResult (uint32 team_action, const std::string & team, const std::string & player, uint32 error_id) const
Definition at line 343 of file ArenaTeamHandler.cpp.
References SendPacket(), and SMSG_ARENA_TEAM_COMMAND_RESULT.
Referenced by HandleArenaTeamAcceptOpcode(), HandleArenaTeamInviteOpcode(), HandleArenaTeamLeaderOpcode(), HandleArenaTeamLeaveOpcode(), HandleArenaTeamRemoveOpcode(), HandleOfferPetitionOpcode(), HandlePetitionBuyOpcode(), HandlePetitionRenameOpcode(), HandlePetitionSignOpcode(), and HandleTurnInPetitionOpcode().
SendAuctionBidderNotification()
void WorldSession::SendAuctionBidderNotification (AuctionEntry * auction) const
Definition at line 94 of file AuctionHouseHandler.cpp.
References AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::GetAuctionOutBid(), AuctionEntry::GetHouseId(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, AuctionEntry::moneyDeliveryTime, SendPacket(), and SMSG_AUCTION_BIDDER_NOTIFICATION.
Referenced by SendAuctionOutbiddedMail(), and AuctionHouseMgr::SendAuctionWonMail().
SendAuctionCancelledToBidderMail()
void WorldSession::SendAuctionCancelledToBidderMail (AuctionEntry * auction) static
Definition at line 172 of file AuctionHouseHandler.cpp.
References AUCTION_CANCELLED_TO_BIDDER, AuctionEntry::bid, AuctionEntry::bidder, Player::GetSession(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, MAIL_CHECK_MASK_COPIED, SendAuctionRemovedNotification(), MailDraft::SendMailTo(), MailDraft::SetMoney(), and sObjectMgr.
Referenced by HandleAuctionRemoveItem().
SendAuctionCommandResult()
void WorldSession::SendAuctionCommandResult (AuctionEntry * auc, AuctionAction Action, AuctionError ErrorCode, InventoryResult invError = EQUIP_ERR_OK) const
Definition at line 65 of file AuctionHouseHandler.cpp.
References AUCTION_BID_PLACED, AUCTION_ERR_HIGHER_BID, AUCTION_ERR_INVENTORY, AUCTION_OK, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::GetAuctionOutBid(), HIGHGUID_PLAYER, AuctionEntry::Id, SendPacket(), and SMSG_AUCTION_COMMAND_RESULT.
Referenced by HandleAuctionPlaceBid(), HandleAuctionRemoveItem(), HandleAuctionSellItem(), and PlayerbotAI::RemoveAuction().
SendAuctionHello()
void WorldSession::SendAuctionHello (Unit * unit) const
Definition at line 52 of file AuctionHouseHandler.cpp.
References AuctionHouseMgr::GetAuctionHouseEntry(), Object::GetObjectGuid(), AuctionHouseEntry::houseId, MSG_AUCTION_HELLO, and SendPacket().
Referenced by ChatHandler::HandleAuctionAllianceCommand(), ChatHandler::HandleAuctionCommand(), ChatHandler::HandleAuctionGoblinCommand(), HandleAuctionHelloOpcode(), ChatHandler::HandleAuctionHordeCommand(), and Player::OnGossipSelect().
SendAuctionOutbiddedMail()
void WorldSession::SendAuctionOutbiddedMail (AuctionEntry * auction) static
Definition at line 147 of file AuctionHouseHandler.cpp.
References AUCTION_OUTBIDDED, AuctionEntry::bid, AuctionEntry::bidder, Player::GetSession(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, MAIL_CHECK_MASK_COPIED, SendAuctionBidderNotification(), MailDraft::SendMailTo(), MailDraft::SetMoney(), and sObjectMgr.
Referenced by AuctionEntry::UpdateBid().
SendAuctionOwnerNotification()
void WorldSession::SendAuctionOwnerNotification (AuctionEntry * auction) const
Definition at line 111 of file AuctionHouseHandler.cpp.
References AuctionEntry::bid, AuctionEntry::bidder, DAY, AuctionEntry::GetAuctionOutBid(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, AuctionEntry::moneyDeliveryTime, SendPacket(), and SMSG_AUCTION_OWNER_NOTIFICATION.
Referenced by AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionWonMail(), and AuctionEntry::UpdateBid().
SendAuctionRemovedNotification()
void WorldSession::SendAuctionRemovedNotification (AuctionEntry * auction) const
Definition at line 136 of file AuctionHouseHandler.cpp.
References AuctionEntry::Id, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, SendPacket(), and SMSG_AUCTION_REMOVED_NOTIFICATION.
Referenced by SendAuctionCancelledToBidderMail().
SendAuthOk()
void WorldSession::SendAuthOk () const
Definition at line 1240 of file WorldSession.cpp.
References AUTH_OK, GetExpansion(), SendPacket(), and SMSG_AUTH_RESPONSE.
Referenced by WorldSocket::HandleAuthSession(), SendAuthWaitQue(), SetExpansion(), and Update().
SendAuthQueued()
void WorldSession::SendAuthQueued () const
Definition at line 1251 of file WorldSession.cpp.
References AUTH_WAIT_QUEUE, SendPacket(), SMSG_AUTH_RESPONSE, and sWorld.
Referenced by SendAuthWaitQue(), and Update().
SendAuthWaitQue()
void WorldSession::SendAuthWaitQue (uint32 position) const
Handle the authentication waiting queue (to be completed)
Definition at line 953 of file WorldSession.cpp.
References SendAuthOk(), and SendAuthQueued().
Referenced by World::RemoveQueuedSession().
SendBattlefieldEnteredResponse()
void WorldSession::SendBattlefieldEnteredResponse (uint32 battlefieldId)
Send response when player accepts invitation to a battlefield.
Parameters
battlefield id
Definition at line 85 of file BattlefieldHandler.cpp.
References _player, Player::isAFK(), SendPacket(), and SMSG_BATTLEFIELD_MANAGER_ENTERING.
Referenced by Battlefield::HandleWarInviteResponse().
SendBattlefieldLeaveMessage()
void WorldSession::SendBattlefieldLeaveMessage (uint32 battlefieldId, BattlefieldLeaveReason reason)
Send response when player leaves a battlefield.
Parameters
battlefield id
leave reason
Definition at line 102 of file BattlefieldHandler.cpp.
References SendPacket(), and SMSG_BATTLEFIELD_MANAGER_EJECTED.
Referenced by Battlefield::HandleBattlefieldGroupDisband(), Battlefield::HandleExitRequest(), Battlefield::HandlePlayerAFK(), Battlefield::HandlePlayerLeaveZone(), Battlefield::HandleWarInviteResponse(), and Battlefield::StartBattle().
SendBattlefieldQueueInvite()
void WorldSession::SendBattlefieldQueueInvite (uint32 battlefieldId)
Invite a player to queue for a battlefield (when entering zone or by battlemaster)
Parameters
battlefield id
Definition at line 50 of file BattlefieldHandler.cpp.
References SendPacket(), and SMSG_BATTLEFIELD_MANAGER_QUEUE_INVITE.
Referenced by Battlefield::InvitePlayerToQueue().
SendBattlefieldQueueResponse()
void WorldSession::SendBattlefieldQueueResponse (uint32 battlefieldId, uint32 zoneId, bool canJoin, bool queueFull)
Send response to player when he joins the battlefield queue.
Parameters
battlefield id
zone id for the battlefield
if player is able to queue
if battlefield is full
Definition at line 68 of file BattlefieldHandler.cpp.
References SendPacket(), and SMSG_BATTLEFIELD_MANAGER_QUEUE_REQUEST_RESPONSE.
Referenced by Battlefield::HandleQueueInviteResponse(), and Battlefield::InvitePlayerToQueue().
SendBattlefieldWarInvite()
void WorldSession::SendBattlefieldWarInvite (uint32 battlefieldId, uint32 zoneId, uint32 acceptDelay)
Invite a player to join and teleport to a battlefield.
Parameters
battlefield id
zone id for the battlefield
time delay to accept the invitation
Definition at line 35 of file BattlefieldHandler.cpp.
References SendPacket(), and SMSG_BATTLEFIELD_MANAGER_ENTRY_INVITE.
Referenced by Battlefield::HandlePlayerEnterZone(), Battlefield::HandleQueueInviteResponse(), and Battlefield::StartBattle().
SendBattleGroundList()
void WorldSession::SendBattleGroundList (ObjectGuid guid, BattleGroundTypeId bgTypeId) const
Send battleground list.
Parameters
guid
bgTypeId
Definition at line 78 of file BattleGroundHandler.cpp.
References _player, sBattleGroundMgr, and SendPacket().
Referenced by HandleBattlemasterHelloOpcode(), and Player::OnGossipSelect().
SendBindPoint()
void WorldSession::SendBindPoint (Creature * npc) const
Definition at line 465 of file NPCHandler.cpp.
References _player, Unit::CastSpell(), PlayerMenu::CloseGossip(), Object::GetObjectGuid(), GetPlayer(), Player::GetPlayerMenu(), SendPacket(), SMSG_TRAINER_BUY_SUCCEEDED, and TRIGGERED_OLD_TRIGGERED.
Referenced by HandleBinderActivateOpcode().
SendCancelTrade()
void WorldSession::SendCancelTrade ()
Definition at line 531 of file TradeHandler.cpp.
References m_playerRecentlyLogout, SendTradeStatus(), TradeStatusInfo::Status, and TRADE_STATUS_TRADE_CANCELED.
Referenced by Player::TradeCancel().
SendChatRestrictedNotice()
void WorldSession::SendChatRestrictedNotice (ChatRestrictionType restriction) const
Definition at line 744 of file ChatHandler.cpp.
References SendPacket(), and SMSG_CHAT_RESTRICTED.
SendExpectedSpamRecords()
void WorldSession::SendExpectedSpamRecords ()
Definition at line 816 of file WorldSession.cpp.
References SendPacket(), ByteBuffer::size(), SMSG_EXPECTED_SPAM_RECORDS, and sWorld.
Referenced by HandlePlayerLogin(), and HandlePlayerReconnect().
SendGMTicket()
void WorldSession::SendGMTicket (const GMTicket & ticket, time_t now = time(nullptr)) const
Definition at line 35 of file GMTicketHandler.cpp.
References GMTicket::GetCategory(), GMTicket::GetCreatedAt(), GMTicket::GetId(), GMTicket::GetStatus(), GMTicket::GetText(), GMTICKET_STATUS_HASTEXT, GMTicket::IsSeen(), SendPacket(), SMSG_GMTICKET_GETTICKET, and sTicketMgr.
Referenced by HandleGMTicketGetTicketOpcode().
SendGMTicketResponse()
void WorldSession::SendGMTicketResponse (GMTicket * ticket) const
Definition at line 300 of file GMTicketHandler.cpp.
References GMTicket::GetConclusion(), GMTicket::GetId(), GMTicket::GetText(), SendPacket(), SMSG_GMTICKET_GET_RESPONSE, and utf8limit().
SendGMTicketResponseError()
void WorldSession::SendGMTicketResponseError () const
Definition at line 287 of file GMTicketHandler.cpp.
References SendPacket(), and SMSG_GMTICKET_RESPONSE_ERROR.
Referenced by HandleGMResponseResolveOpcode().
SendGMTicketResponseResolve()
void WorldSession::SendGMTicketResponseResolve (bool survey) const
Definition at line 293 of file GMTicketHandler.cpp.
References SendPacket(), and SMSG_GMTICKET_RESOLVE_RESPONSE.
Referenced by HandleGMResponseResolveOpcode().
SendGMTicketResult()
void WorldSession::SendGMTicketResult (uint32 opcode, uint32 result) const
Definition at line 28 of file GMTicketHandler.cpp.
References SendPacket().
Referenced by GMTicketMgr::Close(), HandleGMTicketCreateOpcode(), HandleGMTicketDeleteTicketOpcode(), HandleGMTicketGetTicketOpcode(), HandleGMTicketSystemStatusOpcode(), HandleGMTicketUpdateTextOpcode(), and GMTicketMgr::Whisper().
SendGroupInvite()
void WorldSession::SendGroupInvite (Player * player, bool alreadyInGroup = false) const
Definition at line 57 of file GroupHandler.cpp.
References WorldObject::GetName(), GetPlayer(), Player::GetSession(), SendPacket(), and SMSG_GROUP_INVITE.
Referenced by HandleGroupInviteOpcode().
SendGuildCommandResult()
void WorldSession::SendGuildCommandResult (uint32 typecmd, const std::string & str, uint32 cmdresult) const
Definition at line 700 of file GuildHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_GUILD_COMMAND_RESULT.
Referenced by HandleGuildAddRankOpcode(), HandleGuildBankerActivate(), HandleGuildChangeInfoTextOpcode(), HandleGuildDelRankOpcode(), HandleGuildDemoteOpcode(), HandleGuildDisbandOpcode(), HandleGuildInfoOpcode(), HandleGuildInviteOpcode(), HandleGuildLeaderOpcode(), HandleGuildLeaveOpcode(), HandleGuildMOTDOpcode(), HandleGuildPromoteOpcode(), HandleGuildQueryOpcode(), HandleGuildRankOpcode(), HandleGuildRemoveOpcode(), HandleGuildSetOfficerNoteOpcode(), HandleGuildSetPublicNoteOpcode(), HandleOfferPetitionOpcode(), HandlePetitionBuyOpcode(), HandlePetitionRenameOpcode(), HandlePetitionSignOpcode(), and HandleTurnInPetitionOpcode().
SendItemEnchantTimeUpdate()
void WorldSession::SendItemEnchantTimeUpdate (ObjectGuid playerGuid, ObjectGuid itemGuid, uint32 slot, uint32 duration) const
Definition at line 1056 of file ItemHandler.cpp.
References SendPacket(), and SMSG_ITEM_ENCHANT_TIME_UPDATE.
Referenced by Player::AddEnchantmentDuration(), and Player::SendEnchantmentDurations().
SendKnockBack()
void WorldSession::SendKnockBack (Unit * who, float angle, float horizontalSpeed, float verticalSpeed)
Definition at line 553 of file MovementHandler.cpp.
References GetOrderCounter(), Object::GetPackGUID(), GetPlayer(), IncrementOrderCounter(), m_anticheat, SendPacket(), Player::SetLaunched(), and SMSG_MOVE_KNOCK_BACK.
SendLearnNewTaxiNode()
bool WorldSession::SendLearnNewTaxiNode (Creature * unit) const
Definition at line 109 of file TaxiHandler.cpp.
References WorldObject::GetMapId(), Object::GetObjectGuid(), GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SendPacket(), SMSG_NEW_TAXI_PATH, SMSG_TAXINODE_STATUS, and sObjectMgr.
Referenced by PlayerbotMgr::HandleMasterIncomingPacket(), and HandleTaxiQueryAvailableNodes().
SendLfgDisabled()
void WorldSession::SendLfgDisabled ()
Definition at line 524 of file LFGHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_LFG_DISABLED.
SendLfgOfferContinue()
void WorldSession::SendLfgOfferContinue (uint32 dungeonEntry)
Definition at line 531 of file LFGHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_LFG_OFFER_CONTINUE.
SendLfgPlayerReward()
void WorldSession::SendLfgPlayerReward (LfgPlayerRewardData const & rewardData)
Definition at line 488 of file LFGHandler.cpp.
References ItemPrototype::DisplayInfoID, LfgPlayerRewardData::done, GetPlayer(), Quest::GetRewItemsCount(), Quest::GetRewOrReqMoney(), Quest::GetXPReward(), LfgPlayerRewardData::quest, QUEST_REWARDS_COUNT, LfgPlayerRewardData::rdungeonEntry, Quest::RewItemCount, Quest::RewItemId, LfgPlayerRewardData::sdungeonEntry, SendPacket(), sLog, SMSG_LFG_PLAYER_REWARD, and sObjectMgr.
Referenced by LFGMgr::FinishDungeon().
SendLfgTeleportError()
void WorldSession::SendLfgTeleportError (uint8 err)
Definition at line 539 of file LFGHandler.cpp.
References DEBUG_LOG, SendPacket(), and SMSG_LFG_TELEPORT_DENIED.
Referenced by LFGMgr::TeleportPlayer().
SendListInventory()
void WorldSession::SendListInventory (ObjectGuid guid) const
Definition at line 727 of file ItemHandler.cpp.
References _player, ALLIANCE, ItemPrototype::AllowableClass, ItemPrototype::AllowableRace, BIND_WHEN_PICKED_UP, ItemPrototype::Bonding, ItemPrototype::BuyCount, ItemPrototype::BuyPrice, CONDITION_FROM_VENDOR, VendorItem::conditionId, DEBUG_LOG, ItemPrototype::DisplayInfoID, VendorItem::ExtendedCost, ItemPrototype::Flags, ItemPrototype::Flags2, Unit::getClassMask(), Creature::GetInteractionPauseTimer(), VendorItemData::GetItem(), VendorItemData::GetItemCount(), ObjectMgr::GetItemPrototype(), WorldObject::GetMap(), Unit::GetMotionMaster(), Player::GetNPCIfCanInteractWith(), GetPlayer(), Unit::getRaceMask(), Player::GetReputationPriceDiscount(), Player::GetReputationRank(), ObjectGuid::GetString(), Player::GetTeam(), Creature::GetVendorItemCurrentCount(), Creature::GetVendorItems(), Creature::GetVendorTemplateItems(), HORDE, Player::IsGameMaster(), VendorItem::item, ITEM_FLAG2_DONT_IGNORE_BUY_PRICE, ITEM_FLAG2_FACTION_ALLIANCE, ITEM_FLAG2_FACTION_HORDE, ITEM_FLAG_IS_BOUND_TO_ACCOUNT, ItemPrototype::ItemId, MAX_VENDOR_ITEMS, VendorItem::maxcount, ItemPrototype::MaxDurability, MotionMaster::PauseWaypoints(), ByteBuffer::put(), ItemPrototype::RequiredReputationFaction, ItemPrototype::RequiredReputationRank, SELL_ERR_CANT_FIND_VENDOR, SendPacket(), Player::SendSellError(), SMSG_LIST_INVENTORY, sObjectMgr, UNIT_NPC_FLAG_VENDOR, and ByteBuffer::wpos().
Referenced by HandleListInventoryOpcode(), and Player::OnGossipSelect().
SendMotd()
void WorldSession::SendMotd ()
Definition at line 829 of file WorldSession.cpp.
References DEBUG_LOG, SendPacket(), ByteBuffer::size(), SMSG_MOTD, and sWorld.
Referenced by HandlePlayerLogin(), and HandlePlayerReconnect().
SendNameQueryResponse()
void WorldSession::SendNameQueryResponse (CharacterNameQueryResponse & response) const
Definition at line 35 of file QueryHandler.cpp.
References CharacterNameQueryResponse::classid, CharacterNameQueryResponse::declined, CharacterNameQueryResponse::gender, CharacterNameQueryResponse::guid, DeclinedName::name, CharacterNameQueryResponse::name, CharacterNameQueryResponse::race, CharacterNameQueryResponse::realm, SendPacket(), SMSG_NAME_QUERY_RESPONSE, and ObjectGuid::WriteAsPacked().
Referenced by HandleNameQueryOpcode(), SendNameQueryResponseFromDBCallBack(), and SendOfflineNameQueryResponses().
SendNameQueryResponseFromDB()
void WorldSession::SendNameQueryResponseFromDB (ObjectGuid guid) const
Definition at line 76 of file QueryHandler.cpp.
References Database::AsyncPQuery(), CharacterDatabase, CONFIG_BOOL_DECLINED_NAMES_USED, GetAccountId(), ObjectGuid::GetCounter(), SendNameQueryResponseFromDBCallBack(), and sWorld.
Referenced by HandleNameQueryOpcode().
SendNameQueryResponseFromDBCallBack()
void WorldSession::SendNameQueryResponseFromDBCallBack (QueryResult * result, uint32 accountId) static
Definition at line 94 of file QueryHandler.cpp.
References CharacterNameQueryResponse::classid, CONFIG_BOOL_DECLINED_NAMES_USED, CharacterNameQueryResponse::declined, QueryResult::Fetch(), CharacterNameQueryResponse::gender, Field::GetCppString(), Field::GetUInt8(), CharacterNameQueryResponse::guid, HIGHGUID_PLAYER, m_offlineNameResponses, m_sessionState, MAX_DECLINED_NAME_CASES, DeclinedName::name, CharacterNameQueryResponse::name, CharacterNameQueryResponse::race, CharacterNameQueryResponse::realm, SendNameQueryResponse(), sWorld, and WORLD_SESSION_STATE_READY.
Referenced by SendNameQueryResponseFromDB().
SendNotification() [1/2]
void WorldSession::SendNotification (const char * format, ...) const
Definition at line 878 of file WorldSession.cpp.
References SendPacket(), and SMSG_NOTIFICATION.
Referenced by BattleGroundAB::HandleAreaTrigger(), BattleGroundAV::HandleAreaTrigger(), HandleBattlemasterHelloOpcode(), ChatHandler::HandleGMChatCommand(), ChatHandler::HandleGMCommand(), ChatHandler::HandleGMVisibleCommand(), HandleMessagechatOpcode(), HandlePetitionBuyOpcode(), HandlePlayerLogin(), HandlePlayerReconnect(), HandleTextEmoteOpcode(), HandleWhoisOpcode(), and HandleWorldTeleportOpcode().
SendNotification() [2/2]
void WorldSession::SendNotification (int32 string_id, ...) const
Definition at line 895 of file WorldSession.cpp.
References GetMangosString(), SendPacket(), and SMSG_NOTIFICATION.
SendNotInArenaTeamPacket()
void WorldSession::SendNotInArenaTeamPacket (uint8 type) const
Definition at line 353 of file ArenaTeamHandler.cpp.
References SendPacket(), and SMSG_ARENA_ERROR.
Referenced by HandleBattlemasterJoinArena().
SendOfflineNameQueryResponses()
void WorldSession::SendOfflineNameQueryResponses ()
Definition at line 851 of file WorldSession.cpp.
References m_offlineNameQueries, m_offlineNameResponses, and SendNameQueryResponse().
Referenced by HandlePlayerLogin(), and HandlePlayerReconnect().
SendPacket()
void WorldSession::SendPacket (WorldPacket const & packet) const
Send a packet to the client.
Definition at line 202 of file WorldSession.cpp.
References DETAIL_LOG, GetPlayer(), m_Socket, ByteBuffer::size(), UI64FMTD, and ByteBuffer::wpos().
Referenced by PlayerbotAI::_HandleCommandSkill(), Player::AddGCD(), World::AddQueuedSession(), Player::AddRunePower(), World::AddSession_(), Player::ApplyEquipCooldown(), VehicleInfo::Board(), ArenaTeam::BroadcastPacket(), Guild::BroadcastPacket(), Group::BroadcastPacket(), Group::BroadcastPacketInMap(), Group::BroadcastPacketInRange(), Guild::BroadcastPacketToRank(), Group::BroadcastReadyCheck(), SocialMgr::BroadcastToFriendListers(), Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), Player::BuildPlayerRepop(), Player::BuyItemFromVendorSlot(), instance_zulaman::ChangeWeather(), Player::CharmSpellInitialize(), Player::CheckAndRevivePlayerOnDungeonEnter(), CheckChatChannelNameAndPassword(), Player::CheckDuelDistance(), Player::ClearSelectionGuid(), PlayerMenu::CloseGossip(), Player::ConvertRune(), Object::DestroyForPlayer(), Group::Disband(), Guild::DisplayGuildBankContent(), Guild::DisplayGuildBankContentUpdate(), Guild::DisplayGuildBankLogs(), Guild::DisplayGuildBankTabsInfo(), Guild::DisplayGuildEventLog(), Player::DuelComplete(), Spell::EffectDuel(), BattleGround::EndBattleGround(), Player::EnvironmentalDamage(), BgQueueInviteEvent::Execute(), ChannelMgr::GetChannel(), Player::GiveLevel(), Loot::GroupCheck(), HandleAlterAppearanceOpcode(), HandleArenaTeamInviteOpcode(), HandleAuctionListBidderItems(), HandleAuctionListItems(), HandleAuctionListOwnerItems(), HandleAuctionListPendingSales(), Aura::HandleAuraDummy(), HandleBattlefieldListOpcode(), HandleBattlefieldPortOpcode(), HandleBattlefieldStatusOpcode(), HandleBattleGroundPlayerPositionsOpcode(), HandleBattlemasterJoinArena(), HandleBattlemasterJoinOpcode(), HandleBuyBankSlotOpcode(), HandleCalendarComplain(), HandleCalendarGetCalendar(), HandleCalendarGetNumPending(), HandleChangePlayerDifficulty(), HandleChangePlayerNameOpcodeCallBack(), HandleCharCreateOpcode(), HandleCharCustomizeOpcode(), HandleCharDeleteOpcode(), HandleCharRenameOpcode(), HandleChatIgnoredOpcode(), HandleComplainOpcode(), HandleCorpseMapPositionQueryOpcode(), HandleCorpseQueryOpcode(), HandleCreatureQueryOpcode(), ChatHandler::HandleDebugSendChannelNotifyCommand(), ChatHandler::HandleDebugSendChatMsgCommand(), ChatHandler::HandleDebugSendSpellFailCommand(), ChatHandler::HandleDebugSpellModsCommand(), HandleEquipmentSetUseOpcode(), HandleGameObjectQueryOpcode(), HandleGetChannelMemberCountOpcode(), HandleGetMailList(), HandleGetMirrorimageData(), HandleGrantLevel(), HandleGroupDeclineOpcode(), HandleGuildInfoOpcode(), HandleGuildInviteOpcode(), HandleGuildPermissions(), HandleInspectHonorStatsOpcode(), HandleInspectOpcode(), HandleItemNameQueryOpcode(), HandleItemQuerySingleOpcode(), HandleItemTextQuery(), HandleLfgPartyLockInfoRequestOpcode(), HandleLfgPlayerLockInfoRequestOpcode(), HandleLogoutCancelOpcode(), HandleLogoutRequestOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), HandleNpcTextQueryOpcode(), HandleOfferPetitionOpcode(), HandlePageTextQueryOpcode(), HandlePetitionDeclineOpcode(), HandlePetitionRenameOpcode(), HandlePetitionShowSignOpcode(), HandlePetitionSignOpcode(), HandlePlayedTime(), HandlePlayerLogin(), HandlePlayerLoginOpcode(), HandlePlayerReconnect(), HandlePVPLogDataOpcode(), HandleQueryNextMailTime(), HandleQueryQuestsCompletedOpcode(), HandleQuestPOIQueryOpcode(), HandleQuestQueryOpcode(), HandleRandomRollOpcode(), HandleReadItemOpcode(), HandleRealmSplitOpcode(), HandleRequestAccountData(), HandleRequestPartyMemberStatsOpcode(), HandleSetPlayerDeclinedNamesOpcode(), HandleTalentWipeConfirmOpcode(), HandleTrainerBuySpellOpcode(), HandleTurnInPetitionOpcode(), HandleUITimeRequestOpcode(), HandleUpdateAccountData(), HandleWhoisOpcode(), HandleWhoOpcode(), ArenaTeam::InspectStats(), PlayerbotAI::InspectUpdate(), BattleGroundQueue::InviteGroupToBg(), LFGMgr::JoinLfg(), Unit::Kill(), Player::learnSpell(), LFGMgr::LeaveLfg(), Player::LockOutSpells(), LogoutPlayer(), ArenaTeam::MassInviteToEvent(), Guild::MassInviteToEvent(), MaNGOS::VisibleNotifier::Notify(), Loot::NotifyItemChanged(), Loot::NotifyItemRemoved(), Loot::NotifyMoneyRemoved(), DungeonMap::PermBindAllPlayers(), Player::PetSpellInitialize(), BattleGround::PlayerAddedToBgCheckIfBgIsRunning(), PlayerbotAI::PlaySound(), BattleGround::PlaySoundToTeam(), Player::PossessSpellInitialize(), Guild::Query(), ArenaTeam::Query(), Player::RemovedInsignia(), Group::RemoveMember(), BattleGround::RemovePlayerAtLeave(), World::RemoveQueuedSession(), Player::RepopAtGraveyard(), Player::ResurrectPlayer(), Player::ResyncRunes(), Player::RewardHonor(), ArenaTeam::Roster(), Guild::Roster(), Player::SatisfyQuestLog(), Player::Say(), Channel::Say(), SendAccountDataTimes(), SendActivateTaxiReply(), AchievementMgr::SendAllAchievementData(), GroupLootRoll::SendAllPassed(), SendAreaTriggerMessage(), SendArenaTeamCommandResult(), Player::SendAttackSwingBadFacingAttack(), Player::SendAttackSwingCancelAttack(), Player::SendAttackSwingCantAttack(), Player::SendAttackSwingDeadTarget(), Player::SendAttackSwingNotInRange(), SendAuctionBidderNotification(), SendAuctionCommandResult(), SendAuctionHello(), SendAuctionOwnerNotification(), SendAuctionRemovedNotification(), Player::SendAurasForTarget(), SendAuthOk(), SendAuthQueued(), Player::SendAutoRepeatCancel(), SendBattlefieldEnteredResponse(), SendBattlefieldLeaveMessage(), SendBattlefieldQueueInvite(), SendBattlefieldQueueResponse(), SendBattlefieldWarInvite(), SendBattleGroundList(), SendBindPoint(), Player::SendBuyError(), Player::SendCanTakeQuestResponse(), Spell::SendCastResult(), NullSessionAnticheat::SendCharEnum(), SendChatRestrictedNotice(), Player::SendComboPoints(), Player::SendCorpseReclaimDelay(), Object::SendCreateUpdateToPlayer(), UpdateData::SendData(), Player::SendDirectMessage(), Player::SendDuelCountdown(), Player::SendDungeonDifficulty(), Player::SendEquipError(), Player::SendEquipmentSetList(), SendExpectedSpamRecords(), Player::SendExplorationExperience(), Player::SendFeignDeathResisted(), SocialMgr::SendFriendStatus(), SendGMTicket(), SendGMTicketResponse(), SendGMTicketResponseError(), SendGMTicketResponseResolve(), SendGMTicketResult(), Loot::SendGold(), PlayerMenu::SendGossipMenu(), SendGroupInvite(), Guild::SendGuildBankTabText(), SendGuildCommandResult(), Player::SendInitialActionButtons(), Player::SendInitialPacketsBeforeAddToMap(), Player::SendInitialSpells(), Map::SendInitSelf(), Map::SendInitTransports(), Player::SendInitWorldStates(), Player::SendInstanceResetWarning(), SendItemEnchantTimeUpdate(), SendKnockBack(), SendLearnNewTaxiNode(), SendLfgDisabled(), SendLfgOfferContinue(), SendLfgPlayerReward(), SendLfgTeleportError(), SendListInventory(), Player::SendLockActionButtons(), Player::SendLogXPGain(), GroupLootRoll::SendLootRollWon(), Player::SendMailResult(), Player::SendMessageToAllWhoSeeMe(), Player::SendMessageToSet(), Player::SendMessageToSetInRange(), Player::SendMirrorTimerPause(), Player::SendMirrorTimerStart(), Player::SendMirrorTimerStop(), Guild::SendMoneyInfo(), SendMotd(), Unit::SendMoveRoot(), SendNameQueryResponse(), Player::SendNewItem(), Player::SendNewMail(), SendNotification(), SendNotInArenaTeamPacket(), Player::SendOverrideLightUpdate(), Warden::SendPacket(), BattleGround::SendPacketToTeam(), SendPartyResult(), Player::SendPetGUIDs(), SendPetitionQueryOpcode(), SendPetitionShowList(), SendPetNameInvalid(), SendPetNameQuery(), Player::SendPetSkillWipeConfirm(), Player::SendPetTameFailure(), SendPlayerAmbiguousNotice(), SendPlayerNotFoundNotice(), SendPlaySpellVisual(), PlayerMenu::SendPointOfInterest(), Player::SendProficiency(), Player::SendPushToPartyResponse(), SendQueryTimeResponse(), Player::SendQuestCompleteEvent(), Player::SendQuestConfirmAccept(), Player::SendQuestFailed(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverQuestList(), PlayerMenu::SendQuestGiverRequestItems(), PlayerMenu::SendQuestGiverStatus(), Player::SendQuestGiverStatusMultiple(), Player::SendQuestReward(), Player::SendQuestTimerFailed(), Player::SendQuestUpdateAddCreatureOrGo(), Player::SendQuestUpdateAddPlayer(), Player::SendRaidDifficulty(), Player::SendRaidInfo(), SendRedirectClient(), Loot::SendReleaseFor(), Player::SendRemovedSpell(), Map::SendRemoveTransports(), Player::SendResetFailedNotify(), Player::SendResetInstanceFailed(), Player::SendResetInstanceSuccess(), AchievementMgr::SendRespondInspectAchievements(), Player::SendResurrectRequest(), GroupLootRoll::SendRoll(), Player::SendSavedInstances(), SendSaveGuildEmblem(), Player::SendSellError(), World::SendServerMessage(), SendSetPhaseShift(), SendShowBank(), SendShowMailBox(), PlayerSocial::SendSocialList(), SendStablePet(), SendStableResult(), GroupLootRoll::SendStartRoll(), Player::SendSupercededSpell(), ChatHandler::SendSysMessage(), SendTabardVendorActivate(), Player::SendTalentsInfoData(), Player::SendTalentWipeConfirm(), Group::SendTargetIconList(), SendTaxiMenu(), SendTaxiStatus(), Unit::SendTeleportPacket(), SendTimeSync(), Item::SendTimeUpdate(), SendTradeStatus(), SendTrainerList(), SendTransferAborted(), SendTutorialsData(), Group::SendUpdateTo(), SendUpdateTrade(), Player::SendUpdateWorldState(), Player::SendWeatherUpdate(), Weather::SendWeatherUpdateToPlayer(), SendWrongFactionNotice(), Map::SendZoneDynamicInfo(), Player::SetBindPoint(), WardenMac::SetCharEnumPacket(), WardenWin::SetCharEnumPacket(), Player::SetEquipmentSet(), Unit::SetSpeedRate(), Player::SetTitle(), ArenaTeam::Stats(), Player::TeleportTo(), Player::TextEmote(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), WardenMac::Update(), WardenWin::Update(), LfgRaidBrowser::Update(), Player::UpdateClientControl(), Player::UpdateForQuestWorldObjects(), Player::UpdateHomebindTime(), BattleGround::UpdateWorldStateForPlayer(), GameObject::Use(), Player::VehicleSpellInitialize(), Player::Whisper(), and Player::Yell().
SendPartyResult()
void WorldSession::SendPartyResult (PartyOperation operation, const std::string & member, PartyResult res) const
Definition at line 46 of file GroupHandler.cpp.
References SendPacket(), and SMSG_PARTY_COMMAND_RESULT.
Referenced by HandleGroupAcceptOpcode(), HandleGroupDisbandOpcode(), HandleGroupInviteOpcode(), HandleGroupRaidConvertOpcode(), HandleGroupUninviteGuidOpcode(), and HandleGroupUninviteOpcode().
SendPetitionQueryOpcode()
void WorldSession::SendPetitionQueryOpcode (ObjectGuid petitionguid) const
Definition at line 311 of file PetitionsHandler.cpp.
References CharacterDatabase, DEBUG_LOG, QueryResult::Fetch(), ObjectGuid::GetCounter(), Field::GetCppString(), Field::GetUInt32(), HIGHGUID_PLAYER, Database::PQuery(), SendPacket(), and SMSG_PETITION_QUERY_RESPONSE.
Referenced by HandlePetitionQueryOpcode(), and Player::RemovePetitionsAndSigns().
SendPetitionShowList()
void WorldSession::SendPetitionShowList (ObjectGuid guid) const
Definition at line 926 of file PetitionsHandler.cpp.
References ARENA_TEAM_CHARTER_2v2, ARENA_TEAM_CHARTER_2v2_COST, ARENA_TEAM_CHARTER_3v3, ARENA_TEAM_CHARTER_3v3_COST, ARENA_TEAM_CHARTER_5v5, ARENA_TEAM_CHARTER_5v5_COST, CHARTER_DISPLAY_ID, DEBUG_LOG, Player::GetNPCIfCanInteractWith(), GetPlayer(), ObjectGuid::GetString(), GUILD_CHARTER, GUILD_CHARTER_COST, Unit::isTabardDesigner(), SendPacket(), SMSG_PETITION_SHOWLIST, and UNIT_NPC_FLAG_PETITIONER.
Referenced by HandlePetitionShowListOpcode(), and Player::OnGossipSelect().
SendPetNameInvalid()
void WorldSession::SendPetNameInvalid (uint32 error, const std::string & name, DeclinedName * declinedName) const
Definition at line 833 of file PetHandler.cpp.
References DeclinedName::name, SendPacket(), and SMSG_PET_NAME_INVALID.
Referenced by HandlePetRename().
SendPetNameQuery()
void WorldSession::SendPetNameQuery (ObjectGuid guid, uint32 petnumber) const
Definition at line 443 of file PetHandler.cpp.
References _player, Map::GetAnyTypeCreature(), Unit::GetCharmInfo(), Object::GetEntry(), WorldObject::GetMap(), WorldObject::GetName(), Unit::GetOwnerGuid(), Player::GetSession(), GetSessionDbLocaleIndex(), Object::GetUInt32Value(), Creature::IsPet(), ObjectGuid::IsPlayer(), SendPacket(), SMSG_PET_NAME_QUERY_RESPONSE, sObjectMgr, UNIT_FIELD_PET_NAME_TIMESTAMP, and UNIT_FIELD_PETNUMBER.
Referenced by HandlePetNameQueryOpcode().
SendPlayerAmbiguousNotice()
void WorldSession::SendPlayerAmbiguousNotice (const std::string & name) const
Definition at line 731 of file ChatHandler.cpp.
References SendPacket(), and SMSG_CHAT_PLAYER_AMBIGUOUS.
SendPlayerNotFoundNotice()
void WorldSession::SendPlayerNotFoundNotice (const std::string & name) const
Definition at line 724 of file ChatHandler.cpp.
References SendPacket(), and SMSG_CHAT_PLAYER_NOT_FOUND.
Referenced by HandleMessagechatOpcode().
SendPlaySpellVisual()
void WorldSession::SendPlaySpellVisual (ObjectGuid guid, uint32 spellArtKit) const
Definition at line 1198 of file WorldSession.cpp.
References SendPacket(), and SMSG_PLAY_SPELL_VISUAL.
Referenced by HandleTrainerBuySpellOpcode().
SendQueryTimeResponse()
void WorldSession::SendQueryTimeResponse () const
Definition at line 578 of file QueryHandler.cpp.
References SendPacket(), SMSG_QUERY_TIME_RESPONSE, and sWorld.
Referenced by HandleQueryTimeOpcode().
SendRedirectClient()
void WorldSession::SendRedirectClient (std::string & ip, uint16 port) const
Definition at line 1148 of file WorldSession.cpp.
References ByteBuffer::append(), HMACSHA1::Finalize(), HMACSHA1::GetDigest(), m_Socket, SendPacket(), SMSG_CONNECT_TO, and HMACSHA1::UpdateData().
SendSaveGuildEmblem()
void WorldSession::SendSaveGuildEmblem (uint32 msg) const
Definition at line 1242 of file GuildHandler.cpp.
References MSG_SAVE_GUILD_EMBLEM, and SendPacket().
Referenced by HandleSaveGuildEmblemOpcode().
SendSetPhaseShift()
void WorldSession::SendSetPhaseShift (uint32 PhaseShift) const
Definition at line 913 of file WorldSession.cpp.
References SendPacket(), and SMSG_SET_PHASE_SHIFT.
Referenced by ChatHandler::HandleDebugSendSetPhaseShiftCommand(), and Player::SetPhaseMask().
SendShowBank()
void WorldSession::SendShowBank (ObjectGuid guid) const
Definition at line 83 of file NPCHandler.cpp.
References SendPacket(), and SMSG_SHOW_BANK.
Referenced by ChatHandler::HandleBankCommand(), HandleBankerActivateOpcode(), and Player::OnGossipSelect().
SendShowMailBox()
void WorldSession::SendShowMailBox (ObjectGuid guid) const
Definition at line 90 of file NPCHandler.cpp.
References SendPacket(), and SMSG_SHOW_MAILBOX.
Referenced by ChatHandler::HandleMailBoxCommand(), and Player::OnGossipSelect().
SendSpiritResurrect()
void WorldSession::SendSpiritResurrect () const
Definition at line 410 of file NPCHandler.cpp.
References _player, Player::DurabilityLossAll(), Player::GetCamera(), GraveyardManager::GetClosestGraveYard(), Player::GetCorpse(), Map::GetGraveyardManager(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetTeam(), WorldSafeLocsEntry::map_id, WorldSafeLocsEntry::o, Player::ResurrectPlayer(), Player::SpawnCorpseBones(), Player::TeleportTo(), WorldObject::UpdateObjectVisibility(), Camera::UpdateVisibilityForOwner(), WorldSafeLocsEntry::x, WorldSafeLocsEntry::y, and WorldSafeLocsEntry::z.
Referenced by HandleSpiritHealerActivateOpcode().
SendStablePet()
void WorldSession::SendStablePet (ObjectGuid guid) const
Definition at line 498 of file NPCHandler.cpp.
References _player, CharacterDatabase, DEBUG_LOG, QueryResult::Fetch(), Unit::GetCharmInfo(), Object::GetEntry(), Object::GetGUIDLow(), Unit::GetLevel(), WorldObject::GetName(), Unit::GetPet(), CharmInfo::GetPetNumber(), Pet::getPetType(), GetPlayer(), Field::GetString(), Player::GetTemporaryUnsummonedPetNumber(), HUNTER_PET, Unit::IsAlive(), MSG_LIST_STABLED_PETS, QueryResult::NextRow(), PET_SAVE_AS_CURRENT, PET_SAVE_FIRST_STABLE_SLOT, PET_SAVE_LAST_STABLE_SLOT, PET_SAVE_NOT_IN_SLOT, Database::PQuery(), ByteBuffer::put(), SendPacket(), and ByteBuffer::wpos().
Referenced by Aura::HandleAuraOpenStable(), HandleListStabledPetsOpcode(), ChatHandler::HandleStableCommand(), and Player::OnGossipSelect().
SendStableResult()
void WorldSession::SendStableResult (uint8 res) const
Definition at line 581 of file NPCHandler.cpp.
References SendPacket(), and SMSG_STABLE_RESULT.
Referenced by HandleBuyStableSlot(), HandleListStabledPetsOpcode(), HandleStablePet(), HandleStableSwapPet(), and HandleUnstablePet().
SendTabardVendorActivate()
void WorldSession::SendTabardVendorActivate (ObjectGuid guid) const
Definition at line 62 of file NPCHandler.cpp.
References MSG_TABARDVENDOR_ACTIVATE, and SendPacket().
Referenced by HandleTabardVendorActivateOpcode(), and Player::OnGossipSelect().
SendTaxiMenu()
void WorldSession::SendTaxiMenu (Creature * unit) const
Definition at line 89 of file TaxiHandler.cpp.
References PlayerTaxi::AppendTaximaskTo(), DEBUG_LOG, WorldObject::GetMapId(), Object::GetObjectGuid(), GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::m_taxi, SendPacket(), SMSG_SHOWTAXINODES, and sObjectMgr.
Referenced by HandleTaxiQueryAvailableNodes(), and Player::OnGossipSelect().
SendTaxiStatus()
void WorldSession::SendTaxiStatus (ObjectGuid guid) const
Definition at line 40 of file TaxiHandler.cpp.
References DEBUG_LOG, Map::GetCreature(), WorldObject::GetMap(), WorldObject::GetMapId(), GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), ObjectGuid::GetString(), SendPacket(), SMSG_TAXINODE_STATUS, and sObjectMgr.
Referenced by HandleTaxiNodeStatusQueryOpcode().
SendTimeSync()
void WorldSession::SendTimeSync ()
Definition at line 1266 of file WorldSession.cpp.
References WorldTimer::getMSTime(), m_pendingTimeSyncRequests, m_timeSyncNextCounter, m_timeSyncTimer, SendPacket(), and SMSG_TIME_SYNC_REQ.
Referenced by Player::SendInitialPacketsAfterAddToMap().
SendTradeStatus()
void WorldSession::SendTradeStatus (const TradeStatusInfo & status) const
Definition at line 32 of file TradeHandler.cpp.
References TradeStatusInfo::IsTargetResult, TradeStatusInfo::ItemLimitCategoryId, TradeStatusInfo::Result, SendPacket(), TradeStatusInfo::Slot, SMSG_TRADE_STATUS, TradeStatusInfo::Status, TRADE_STATUS_BEGIN_TRADE, TRADE_STATUS_CLOSE_WINDOW, TRADE_STATUS_NOT_ON_TAPLIST, TRADE_STATUS_OPEN_WINDOW, TRADE_STATUS_WRONG_REALM, and TradeStatusInfo::TraderGuid.
Referenced by HandleAcceptTradeOpcode(), HandleBeginTradeOpcode(), HandleInitiateTradeOpcode(), HandleSetTradeItemOpcode(), SendCancelTrade(), TradeData::SetAccepted(), and TradeData::SetMoney().
SendTrainerList()
void WorldSession::SendTrainerList (ObjectGuid guid) const
Definition at line 136 of file NPCHandler.cpp.
References _player, CONDITION_FROM_TRAINER, TrainerSpell::conditionId, DEBUG_LOG, Creature::GetCreatureInfo(), ObjectGuid::GetEntry(), Player::GetFreePrimaryProfessionPoints(), GetMangosString(), WorldObject::GetMap(), Player::GetNPCIfCanInteractWith(), GetPlayer(), Player::GetReputationPriceDiscount(), GetSessionDbLocaleIndex(), ObjectGuid::GetString(), Creature::GetTrainerSpells(), Player::GetTrainerSpellState(), Creature::GetTrainerTemplateSpells(), TrainerSpell::isProvidedReqLevel, Player::IsSpellFitByClassAndRace(), Creature::IsTrainerOf(), LANG_NPC_TAINER_HELLO, TrainerSpell::learnedSpell, ByteBuffer::put(), TrainerSpell::reqLevel, SendPacket(), SendTrainerSpellHelper(), SMSG_TRAINER_LIST, sObjectMgr, TrainerSpellData::spellList, TrainerSpellData::trainerType, UNIT_NPC_FLAG_TRAINER, and ByteBuffer::wpos().
Referenced by HandleTrainerListOpcode(), and Player::OnGossipSelect().
SendTransferAborted()
void WorldSession::SendTransferAborted (uint32 mapid, uint8 reason, uint8 arg = 0) const
Definition at line 1132 of file WorldSession.cpp.
References SendPacket(), SMSG_TRANSFER_ABORTED, TRANSFER_ABORT_DIFFICULTY, TRANSFER_ABORT_INSUF_EXPAN_LVL, and TRANSFER_ABORT_UNIQUE_MESSAGE.
Referenced by Player::SendTransferAbortedByLockStatus().
SendTutorialsData()
void WorldSession::SendTutorialsData ()
Definition at line 1087 of file WorldSession.cpp.
References m_Tutorials, SendPacket(), and SMSG_TUTORIAL_FLAGS.
Referenced by World::AddSession_(), and World::RemoveQueuedSession().
SendUpdateTrade()
void WorldSession::SendUpdateTrade (bool trader_state = true) const
Definition at line 73 of file TradeHandler.cpp.
References _player, TradeData::GetItem(), TradeData::GetMoney(), TradeData::GetSpell(), Player::GetTradeData(), TradeData::GetTraderData(), ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_CREATOR, ITEM_FIELD_DURABILITY, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, ITEM_FIELD_MAXDURABILITY, MAX_GEM_SOCKETS, PERM_ENCHANTMENT_SLOT, SendPacket(), SMSG_TRADE_STATUS_EXTENDED, SOCK_ENCHANTMENT_SLOT, and TRADE_SLOT_COUNT.
Referenced by TradeData::Update().
SendWrongFactionNotice()
void WorldSession::SendWrongFactionNotice () const
Definition at line 738 of file ChatHandler.cpp.
References SendPacket(), and SMSG_CHAT_WRONG_FACTION.
Referenced by HandleMessagechatOpcode().
SetAccountData()
void WorldSession::SetAccountData (AccountDataType type, time_t time_, const std::string & data)
Definition at line 1005 of file WorldSession.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Database::CreateStatement(), AccountData::Data, GetAccountId(), GLOBAL_CACHE_MASK, m_accountData, m_GUIDLow, SqlStatement::PExecute(), and AccountData::Time.
Referenced by HandleUpdateAccountData().
SetAccountMaxLevel()
void WorldSession::SetAccountMaxLevel (uint32 level) inline
Definition at line 477 of file WorldSession.h.
References m_accountMaxLevel.
SetCurrentPlayerLevel()
void WorldSession::SetCurrentPlayerLevel (uint32 level) inline
Definition at line 491 of file WorldSession.h.
References m_currentPlayerLevel.
Referenced by Player::GiveLevel().
SetDelayedAnticheat()
void WorldSession::SetDelayedAnticheat (std::unique_ptr< SessionAnticheatInterface > && anticheat)
Definition at line 1289 of file WorldSession.cpp.
References m_delayedAnticheat.
Referenced by WorldSocket::HandleAuthSession().
SetExpansion()
void WorldSession::SetExpansion (uint8 expansion)
Definition at line 193 of file WorldSession.cpp.
References _player, m_expansion, Player::OnExpansionChange(), and SendAuthOk().
Referenced by WorldState::SetExpansion().
SetGameBuild()
void WorldSession::SetGameBuild (uint32 version) inline
Definition at line 475 of file WorldSession.h.
References m_gameBuild.
Referenced by WorldSocket::HandleAuthSession().
SetInCharSelection()
void WorldSession::SetInCharSelection ()
Definition at line 156 of file WorldSession.cpp.
References m_kickTime, m_sessionState, and WORLD_SESSION_STATE_CHAR_SELECTION.
Referenced by LogoutPlayer(), and Update().
SetInQueue()
void WorldSession::SetInQueue (bool state) inline
Session in auth.queue currently.
Definition at line 323 of file WorldSession.h.
References m_inQueue.
Referenced by World::AddQueuedSession(), and World::RemoveQueuedSession().
SetLatency()
void WorldSession::SetLatency (uint32 latency) inline
Definition at line 467 of file WorldSession.h.
References m_latency.
Referenced by WorldSocket::HandlePing().
SetOffline()
void WorldSession::SetOffline ()
Definition at line 124 of file WorldSession.cpp.
References _player, FRIEND_OFFLINE, Object::GetObjectGuid(), LogoutRequest(), m_sessionState, m_Socket, sSocialMgr, and WORLD_SESSION_STATE_OFFLINE.
Referenced by Update().
SetOnline()
void WorldSession::SetOnline ()
Definition at line 147 of file WorldSession.cpp.
References _player, m_kickTime, m_sessionState, m_Socket, and WORLD_SESSION_STATE_READY.
Referenced by HandlePlayerLogin(), and HandlePlayerReconnect().
SetOS()
void WorldSession::SetOS (ClientOSType os) inline
Definition at line 471 of file WorldSession.h.
References m_clientOS.
Referenced by WorldSocket::HandleAuthSession().
SetPacketLogging()
void WorldSession::SetPacketLogging (bool state)
Definition at line 1234 of file WorldSession.cpp.
References m_Socket.
Referenced by ChatHandler::HandleDebugPacketLog().
SetPlatform()
void WorldSession::SetPlatform (ClientPlatformType platform) inline
Definition at line 473 of file WorldSession.h.
References m_clientPlatform.
Referenced by WorldSocket::HandleAuthSession().
SetPlayer()
void WorldSession::SetPlayer (Player * plr, uint32 playerGuid)
Definition at line 185 of file WorldSession.cpp.
References _player, m_anticheat, and m_GUIDLow.
Referenced by HandlePlayerLogin(), and LogoutPlayer().
SetSecurity()
void WorldSession::SetSecurity (AccountTypes security) inline
Definition at line 300 of file WorldSession.h.
References _security.
Referenced by ChatHandler::HandleAccountSetGmLevelCommand().
SetTutorialInt()
void WorldSession::SetTutorialInt (uint32 intId, uint32 value) inline
Definition at line 410 of file WorldSession.h.
References m_Tutorials, m_tutorialState, TUTORIALDATA_CHANGED, and TUTORIALDATA_UNCHANGED.
Referenced by HandleTutorialClearOpcode(), HandleTutorialFlagOpcode(), and HandleTutorialResetOpcode().
ShouldDisconnect()
bool WorldSession::ShouldDisconnect (time_t currTime) inline
Definition at line 342 of file WorldSession.h.
References _logoutTime.
Referenced by Update().
ShouldLogOut()
bool WorldSession::ShouldLogOut (time_t currTime) const inline
Is logout cooldown expired?
Definition at line 337 of file WorldSession.h.
References _logoutTime.
Referenced by Update().
SizeError()
void WorldSession::SizeError (WorldPacket const & packet, uint32 size) const
Definition at line 173 of file WorldSession.cpp.
References GetAccountId(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), ByteBuffer::size(), SIZEFMTD, and sLog.
SynchronizeMovement()
void WorldSession::SynchronizeMovement (MovementInfo & movementInfo)
Definition at line 1206 of file WorldSession.cpp.
References MovementInfo::ctime, DETAIL_LOG, World::GetCurrentMSTime(), m_timeSyncClockDelta, and MovementInfo::stime.
Referenced by HandleMoverRelocation().
Update()
bool WorldSession::Update (uint32 diff)
Update the WorldSession (triggered by World update)
Retrieve packets from the receive queue and call the appropriate handlers not process packets if socket already closed
Definition at line 352 of file WorldSession.cpp.
References _player, CMSG_SET_ACTIVE_VOICE_CHANNEL, CMSG_WARDEN_DATA, DEBUG_LOG, Messager< T >::Execute(), ExecuteOpcode(), GetMessager(), WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), GetPlayer(), Player::GetSession(), Object::IsInWorld(), IsOffline(), KickPlayer(), LogoutPlayer(), LogUnexpectedOpcode(), m_anticheat, m_inQueue, m_kickTime, m_lastAnticheatUpdate, m_playerLoading, m_playerRecentlyLogout, m_recvQueue, m_recvQueueLock, m_requestSocket, m_sessionState, m_Socket, opcodeTable, SendAuthOk(), SendAuthQueued(), SetInCharSelection(), SetOffline(), ShouldDisconnect(), ShouldLogOut(), sLog, OpcodeHandler::status, STATUS_AUTHED, STATUS_LOGGEDIN, STATUS_LOGGEDIN_OR_RECENTLY_LOGGEDOUT, STATUS_NEVER, STATUS_TRANSFER, STATUS_UNHANDLED, WORLD_SESSION_STATE_CHAR_SELECTION, WORLD_SESSION_STATE_CREATED, WORLD_SESSION_STATE_OFFLINE, and WORLD_SESSION_STATE_READY.
Referenced by World::UpdateSessions().
UpdateMap()
void WorldSession::UpdateMap (uint32 diff)
Definition at line 554 of file WorldSession.cpp.
References ExecuteOpcode(), m_recvQueueMap, m_recvQueueMapLock, m_Socket, opcodeTable, OpcodeHandler::status, and STATUS_LOGGEDIN.
Referenced by Map::Update().
VerifyMovementInfo()
bool WorldSession::VerifyMovementInfo (MovementInfo const & movementInfo, Unit * mover, bool unroot) const private
Definition at line 661 of file MovementHandler.cpp.
References _player, Player::GetMover(), Object::GetObjectGuid(), MovementInfo::GetPos(), MovementInfo::GetTransportPos(), MovementInfo::HasMovementFlag(), Unit::IsRooted(), MaNGOS::IsValidMapCoord(), MOVEFLAG_MASK_MOVING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_ROOT, Position::o, Position::x, Position::y, and Position::z.
Referenced by ProcessMovementInfo().
Friends And Related Function Documentation
CharacterHandler
friend class CharacterHandler friend
Definition at line 245 of file WorldSession.h.
Field Documentation
_accountId
uint32 WorldSession::_accountId private
Definition at line 1039 of file WorldSession.h.
Referenced by GetAccountId().
_logoutTime
time_t WorldSession::_logoutTime private
Definition at line 1054 of file WorldSession.h.
Referenced by isLogingOut(), LogoutPlayer(), LogoutRequest(), ShouldDisconnect(), and ShouldLogOut().
_player
Player* WorldSession::_player private
Definition at line 1032 of file WorldSession.h.
Referenced by BuildListAuctionItems(), CanInteractWithQuestGiver(), CheckChatMessage(), ExecuteOpcode(), GetPlayer(), HandleAcceptLevelGrant(), HandleAcceptTradeOpcode(), HandleActivateTaxiExpressOpcode(), HandleActivateTaxiOpcode(), HandleAlterAppearanceOpcode(), HandleAreaSpiritHealerQueryOpcode(), HandleAreaSpiritHealerQueueOpcode(), HandleArenaTeamAcceptOpcode(), HandleArenaTeamDeclineOpcode(), HandleArenaTeamDisbandOpcode(), HandleArenaTeamLeaderOpcode(), HandleArenaTeamLeaveOpcode(), HandleArenaTeamRemoveOpcode(), HandleAttackSwingOpcode(), HandleAuctionListOwnerItems(), HandleAuctionListPendingSales(), HandleAutoBankItemOpcode(), HandleAutoEquipItemOpcode(), HandleAutoEquipItemSlotOpcode(), HandleAutoStoreBagItemOpcode(), HandleAutoStoreBankItemOpcode(), HandleAutostoreLootItemOpcode(), HandleBattlefieldListOpcode(), HandleBattlefieldPortOpcode(), HandleBattlefieldStatusOpcode(), HandleBattleGroundPlayerPositionsOpcode(), HandleBattlemasterHelloOpcode(), HandleBattlemasterJoinArena(), HandleBattlemasterJoinOpcode(), HandleBeginTradeOpcode(), HandleBusyTradeOpcode(), HandleBuybackItem(), HandleBuyBankSlotOpcode(), HandleBuyItemInSlotOpcode(), HandleBuyStableSlot(), HandleCalendarAddEvent(), HandleCalendarArenaTeam(), HandleCalendarComplain(), HandleCalendarCopyEvent(), HandleCalendarEventInvite(), HandleCalendarEventModeratorStatus(), HandleCalendarEventRemoveInvite(), HandleCalendarEventRsvp(), HandleCalendarEventSignup(), HandleCalendarEventStatus(), HandleCalendarGetCalendar(), HandleCalendarGetEvent(), HandleCalendarGetNumPending(), HandleCalendarGuildFilter(), HandleCalendarRemoveEvent(), HandleCalendarUpdateEvent(), HandleCancelAuraOpcode(), HandleCancelAutoRepeatSpellOpcode(), HandleCancelCastOpcode(), HandleCancelChanneling(), HandleCancelMountAuraOpcode(), HandleCancelTradeOpcode(), HandleCastSpellOpcode(), HandleChangePlayerDifficulty(), HandleChangeSeatsOnControlledVehicle(), HandleChannelAnnouncementsOpcode(), HandleChannelBanOpcode(), HandleChannelDisplayListQueryOpcode(), HandleChannelInviteOpcode(), HandleChannelKickOpcode(), HandleChannelListOpcode(), HandleChannelModerateOpcode(), HandleChannelModeratorOpcode(), HandleChannelMuteOpcode(), HandleChannelOwnerOpcode(), HandleChannelPasswordOpcode(), HandleChannelSetOwnerOpcode(), HandleChannelUnbanOpcode(), HandleChannelUnmoderatorOpcode(), HandleChannelUnmuteOpcode(), HandleChatIgnoredOpcode(), HandleClearTradeItemOpcode(), HandleCommentatorModeOpcode(), HandleContactListOpcode(), HandleCorpseQueryOpcode(), HandleDelFriendOpcode(), HandleDelIgnoreOpcode(), HandleDestroyItemOpcode(), HandleDismissControlledVehicle(), HandleDismissCritter(), HandleEjectPassenger(), HandleEquipmentSetDeleteOpcode(), HandleEquipmentSetSaveOpcode(), HandleEquipmentSetUseOpcode(), HandleFarSightOpcode(), HandleForceSpeedChangeAckOpcodes(), HandleGameobjectReportUse(), HandleGameObjectUseOpcode(), HandleGetChannelMemberCountOpcode(), HandleGetMailList(), HandleGetMirrorimageData(), HandleGossipHelloOpcode(), HandleGossipSelectOptionOpcode(), HandleGrantLevel(), HandleGroupRaidConvertOpcode(), HandleGuildBankDepositMoney(), HandleGuildBankSwapItems(), HandleGuildDeclineOpcode(), HandleGuildDemoteOpcode(), HandleGuildLeaveOpcode(), HandleGuildPromoteOpcode(), HandleGuildRemoveOpcode(), HandleGuildRosterOpcode(), HandleHearthandResurrect(), HandleIgnoreTradeOpcode(), HandleInitiateTradeOpcode(), HandleInspectArenaTeamsOpcode(), HandleInspectHonorStatsOpcode(), HandleInspectOpcode(), HandleInstanceLockResponse(), HandleItemRefundInfoRequest(), HandleItemTextQuery(), HandleJoinChannelOpcode(), HandleLearnPreviewTalents(), HandleLearnPreviewTalentsPet(), HandleLearnTalentOpcode(), HandleLeaveBattlefieldOpcode(), HandleLeaveChannelOpcode(), HandleLootMasterGiveOpcode(), HandleLootMoneyOpcode(), HandleLootOpcode(), HandleLootReleaseOpcode(), HandleLootRoll(), HandleMailCreateTextItem(), HandleMailDelete(), HandleMailMarkAsRead(), HandleMailReturnToSender(), HandleMailTakeItem(), HandleMailTakeMoney(), HandleMessagechatOpcode(), HandleMoveFlagChangeOpcode(), HandleMoveKnockBackAck(), HandleMovementOpcodes(), HandleMoveNotActiveMoverOpcode(), HandleMoveRootAck(), HandleMoverRelocation(), HandleMoveTeleportAckOpcode(), HandleMoveTimeSkippedOpcode(), HandleMoveWorldportAckOpcode(), HandleOfferPetitionOpcode(), HandleOnMissileTrajectoryCollision(), HandleOpenItemOpcode(), HandlePetAbandon(), HandlePetAction(), HandlePetActionHelper(), HandlePetCastSpellOpcode(), HandlePetitionBuyOpcode(), HandlePetitionDeclineOpcode(), HandlePetitionRenameOpcode(), HandlePetitionShowSignOpcode(), HandlePetitionSignOpcode(), HandlePetLearnTalent(), HandlePetRename(), HandlePetSetAction(), HandlePetSpellAutocastOpcode(), HandlePetStopAttack(), HandlePetUnlearnOpcode(), HandlePlayedTime(), HandlePlayerLoginOpcode(), HandlePlayerReconnect(), HandlePushQuestToParty(), HandlePVPLogDataOpcode(), HandleQueryInspectAchievementsOpcode(), HandleQueryNextMailTime(), HandleQueryQuestsCompletedOpcode(), HandleQuestConfirmAccept(), HandleQuestgiverAcceptQuestOpcode(), HandleQuestgiverCancel(), HandleQuestgiverChooseRewardOpcode(), HandleQuestgiverCompleteQuest(), HandleQuestgiverHelloOpcode(), HandleQuestgiverQueryQuestOpcode(), HandleQuestgiverRequestRewardOpcode(), HandleQuestgiverStatusMultipleQuery(), HandleQuestgiverStatusQueryOpcode(), HandleQuestLogRemoveQuest(), HandleQuestPOIQueryOpcode(), HandleQuestPushResult(), HandleRaidTargetUpdateOpcode(), HandleReadItemOpcode(), HandleRemoveGlyphOpcode(), HandleRepairItemOpcode(), HandleReportPvPAFK(), HandleRequestAccountData(), HandleRequestPetInfoOpcode(), HandleRequestRaidInfoOpcode(), HandleRequestVehicleExit(), HandleRequestVehicleNextSeat(), HandleRequestVehicleSwitchSeat(), HandleResetInstancesOpcode(), HandleRideVehicleInteract(), HandleSelfResOpcode(), HandleSellItemOpcode(), HandleSendMail(), HandleSetActiveMoverOpcode(), HandleSetContactNotesOpcode(), HandleSetDungeonDifficultyOpcode(), HandleSetFactionInactiveOpcode(), HandleSetRaidDifficultyOpcode(), HandleSetSelectionOpcode(), HandleSetTargetOpcode(), HandleSetTaxiBenchmarkOpcode(), HandleSetTradeGoldOpcode(), HandleSetTradeItemOpcode(), HandleShowingCloakOpcode(), HandleShowingHelmOpcode(), HandleSocketOpcode(), HandleSpellClick(), HandleSplitItemOpcode(), HandleStablePet(), HandleStableSwapPet(), HandleStandStateChangeOpcode(), HandleSummonResponseOpcode(), HandleSwapInvItemOpcode(), HandleSwapItem(), HandleTalentWipeConfirmOpcode(), HandleTotemDestroyed(), HandleTrainerBuySpellOpcode(), HandleTurnInPetitionOpcode(), HandleUnacceptTradeOpcode(), HandleUnstablePet(), HandleUseItemOpcode(), HandleWhoisOpcode(), HandleWhoOpcode(), HandleWrapItemOpcode(), HandleZoneUpdateOpcode(), KickPlayer(), LogoutPlayer(), moveItems(), ProcessByteBufferException(), SendBattlefieldEnteredResponse(), SendBattleGroundList(), SendBindPoint(), SendListInventory(), SendPetNameQuery(), SendSpiritResurrect(), SendStablePet(), SendTrainerList(), SendUpdateTrade(), SetExpansion(), SetOffline(), SetOnline(), SetPlayer(), Update(), VerifyMovementInfo(), and ~WorldSession().
_security
AccountTypes WorldSession::_security private
Definition at line 1038 of file WorldSession.h.
Referenced by GetSecurity(), and SetSecurity().
m_accountData
AccountData WorldSession::m_accountData[NUM_ACCOUNT_DATA_TYPES] private
Definition at line 1068 of file WorldSession.h.
Referenced by GetAccountData(), LoadAccountData(), and SetAccountData().
m_accountFlags
uint32 WorldSession::m_accountFlags private
Definition at line 1042 of file WorldSession.h.
Referenced by AddAccountFlag(), GetAccountFlags(), HasAccountFlag(), and RemoveAccountFlag().
m_accountMaxLevel
uint32 WorldSession::m_accountMaxLevel private
Definition at line 1048 of file WorldSession.h.
Referenced by GetAccountMaxLevel(), and SetAccountMaxLevel().
m_accountName
std::string WorldSession::m_accountName private
Definition at line 1041 of file WorldSession.h.
Referenced by GetAccountName().
m_anticheat
std::unique_ptr<SessionAnticheatInterface> WorldSession::m_anticheat private
Definition at line 1052 of file WorldSession.h.
Referenced by AssignAnticheat(), GetAnticheat(), HandleCharEnum(), HandleForceSpeedChangeAckOpcodes(), HandleMessagechatOpcode(), HandleMoveFlagChangeOpcode(), HandleMoveKnockBackAck(), HandleMoveRootAck(), HandleMoveTeleportAckOpcode(), HandleMoveTimeSkippedOpcode(), HandleMoveWorldportAckOpcode(), HandlePlayerReconnect(), HandleSendMail(), HandleSetActiveMoverOpcode(), HandleWardenDataOpcode(), InitializeAnticheat(), ProcessByteBufferException(), ProcessMovementInfo(), SendKnockBack(), SetPlayer(), and Update().
m_clientOS
ClientOSType WorldSession::m_clientOS private
Definition at line 1045 of file WorldSession.h.
Referenced by GetOS(), and SetOS().
m_clientPlatform
ClientPlatformType WorldSession::m_clientPlatform private
Definition at line 1046 of file WorldSession.h.
Referenced by GetPlatform(), and SetPlatform().
m_clientTimeDelay
uint32 WorldSession::m_clientTimeDelay private
Definition at line 1067 of file WorldSession.h.
Referenced by ResetClientTimeDelay().
m_currentPlayerLevel
std::atomic<uint32> WorldSession::m_currentPlayerLevel private
Definition at line 1097 of file WorldSession.h.
Referenced by GetCurrentPlayerLevel(), HandlePlayerLogin(), and SetCurrentPlayerLevel().
m_delayedAnticheat
std::unique_ptr<SessionAnticheatInterface> WorldSession::m_delayedAnticheat private
Definition at line 1051 of file WorldSession.h.
Referenced by AssignAnticheat(), and SetDelayedAnticheat().
m_expansion
uint8 WorldSession::m_expansion private
Definition at line 1040 of file WorldSession.h.
Referenced by GetExpansion(), and SetExpansion().
m_gameBuild
uint32 WorldSession::m_gameBuild private
Definition at line 1047 of file WorldSession.h.
Referenced by GetGameBuild(), and SetGameBuild().
m_GUIDLow
uint32 WorldSession::m_GUIDLow private
Definition at line 1031 of file WorldSession.h.
Referenced by SetAccountData(), and SetPlayer().
m_initialZoneUpdated
bool WorldSession::m_initialZoneUpdated = false private
Definition at line 1075 of file WorldSession.h.
Referenced by HandlePlayerLogin(), HandlePlayerReconnect(), HandleZoneUpdateOpcode(), and IsInitialZoneUpdated().
m_inQueue
bool WorldSession::m_inQueue private
Definition at line 1057 of file WorldSession.h.
Referenced by SetInQueue(), and Update().
m_isRecruiter
bool WorldSession::m_isRecruiter private
Definition at line 1087 of file WorldSession.h.
Referenced by IsARecruiter().
m_kickSession
bool WorldSession::m_kickSession private
Definition at line 1059 of file WorldSession.h.
Referenced by KickPlayer(), LogoutPlayer(), and LogoutRequest().
m_kickTime
time_t WorldSession::m_kickTime private
Definition at line 1055 of file WorldSession.h.
Referenced by SetInCharSelection(), SetOnline(), and Update().
m_lastAnticheatUpdate
uint32 WorldSession::m_lastAnticheatUpdate private
Definition at line 1050 of file WorldSession.h.
Referenced by Update().
m_latency
uint32 WorldSession::m_latency private
Definition at line 1066 of file WorldSession.h.
Referenced by GetLatency(), and SetLatency().
m_localAddress
std::string WorldSession::m_localAddress private
Definition at line 1035 of file WorldSession.h.
Referenced by GetLocalAddress().
m_messager
Messager<WorldSession> WorldSession::m_messager private
Definition at line 1095 of file WorldSession.h.
Referenced by GetMessager().
m_muteTime
time_t WorldSession::m_muteTime
Definition at line 457 of file WorldSession.h.
Referenced by Player::CanSpeak(), HandleMessagechatOpcode(), ChatHandler::HandleMuteCommand(), HandleTextEmoteOpcode(), ChatHandler::HandleUnmuteCommand(), and Player::UpdateSpeakTime().
m_offlineNameQueries
std::set<ObjectGuid> WorldSession::m_offlineNameQueries private
Definition at line 1072 of file WorldSession.h.
Referenced by HandleNameQueryOpcode(), and SendOfflineNameQueryResponses().
m_offlineNameResponses
std::deque<CharacterNameQueryResponse> WorldSession::m_offlineNameResponses private
Definition at line 1073 of file WorldSession.h.
Referenced by HandleNameQueryOpcode(), SendNameQueryResponseFromDBCallBack(), and SendOfflineNameQueryResponses().
m_orderCounter
uint32 WorldSession::m_orderCounter private
Definition at line 1049 of file WorldSession.h.
Referenced by GetOrderCounter(), and IncrementOrderCounter().
m_pendingTimeSyncRequests
std::map<uint32, uint32> WorldSession::m_pendingTimeSyncRequests private
Definition at line 1081 of file WorldSession.h.
Referenced by HandleTimeSyncResp(), ResetTimeSync(), and SendTimeSync().
m_playerLoading
bool WorldSession::m_playerLoading private
Definition at line 1058 of file WorldSession.h.
Referenced by HandlePlayerLogin(), HandlePlayerLoginOpcode(), HandlePlayerReconnect(), PlayerLoading(), and Update().
m_playerLogout
bool WorldSession::m_playerLogout private
Definition at line 1062 of file WorldSession.h.
Referenced by isLogingOut(), LogoutPlayer(), PlayerLogout(), and PlayerLogoutWithSave().
m_playerRecentlyLogout
bool WorldSession::m_playerRecentlyLogout private
Definition at line 1063 of file WorldSession.h.
Referenced by LogoutPlayer(), SendCancelTrade(), and Update().
m_playerSave
bool WorldSession::m_playerSave private
Definition at line 1056 of file WorldSession.h.
Referenced by KickPlayer(), LogoutPlayer(), LogoutRequest(), and PlayerLogoutWithSave().
m_recruitingFriendId
uint32 WorldSession::m_recruitingFriendId private
Definition at line 1086 of file WorldSession.h.
Referenced by GetRecruitingFriendId().
m_recvQueue
std::deque<std::unique_ptr<WorldPacket> > WorldSession::m_recvQueue private
Definition at line 1092 of file WorldSession.h.
Referenced by QueuePacket(), and Update().
m_recvQueueLock
std::mutex WorldSession::m_recvQueueLock private
Definition at line 1090 of file WorldSession.h.
Referenced by QueuePacket(), RequestNewSocket(), and Update().
m_recvQueueMap
std::deque<std::unique_ptr<WorldPacket> > WorldSession::m_recvQueueMap private
Definition at line 1093 of file WorldSession.h.
Referenced by DeleteMovementPackets(), QueuePacket(), and UpdateMap().
m_recvQueueMapLock
std::mutex WorldSession::m_recvQueueMapLock private
Definition at line 1091 of file WorldSession.h.
Referenced by DeleteMovementPackets(), QueuePacket(), and UpdateMap().
m_requestSocket
std::shared_ptr<WorldSocket> WorldSession::m_requestSocket private
Definition at line 1034 of file WorldSession.h.
Referenced by RequestNewSocket(), and Update().
m_sessionDbcLocale
LocaleConstant WorldSession::m_sessionDbcLocale private
Definition at line 1064 of file WorldSession.h.
Referenced by GetSessionDbcLocale(), and HandleGMSurveySubmitOpcode().
m_sessionDbLocaleIndex
int WorldSession::m_sessionDbLocaleIndex private
Definition at line 1065 of file WorldSession.h.
Referenced by GetSessionDbLocaleIndex().
m_sessionState
WorldSessionState WorldSession::m_sessionState private
Definition at line 1036 of file WorldSession.h.
Referenced by GetState(), HandleNameQueryOpcode(), IsOffline(), RequestNewSocket(), SendNameQueryResponseFromDBCallBack(), SetInCharSelection(), SetOffline(), SetOnline(), and Update().
m_Socket
std::shared_ptr<WorldSocket> WorldSession::m_Socket private
Definition at line 1033 of file WorldSession.h.
Referenced by GetIncOpcodeHistory(), GetOutOpcodeHistory(), GetRemoteAddress(), LogoutPlayer(), SendPacket(), SendRedirectClient(), SetOffline(), SetOnline(), SetPacketLogging(), Update(), UpdateMap(), and ~WorldSession().
m_ticketSquelchTimer
ShortTimeTracker WorldSession::m_ticketSquelchTimer
Definition at line 459 of file WorldSession.h.
Referenced by HandleGMSurveySubmitOpcode(), HandleGMTicketCreateOpcode(), and HandleGMTicketUpdateTextOpcode().
m_timeSyncClockDelta
int64 WorldSession::m_timeSyncClockDelta private
Definition at line 1078 of file WorldSession.h.
Referenced by ComputeNewClockDelta(), and SynchronizeMovement().
m_timeSyncClockDeltaQueue
boost::circular_buffer<std::pair<int64, uint32> > WorldSession::m_timeSyncClockDeltaQueue private
Definition at line 1077 of file WorldSession.h.
Referenced by ComputeNewClockDelta(), and HandleTimeSyncResp().
m_timeSyncNextCounter
uint32 WorldSession::m_timeSyncNextCounter private
Definition at line 1082 of file WorldSession.h.
Referenced by ResetTimeSync(), and SendTimeSync().
m_timeSyncTimer
uint32 WorldSession::m_timeSyncTimer private
Definition at line 1083 of file WorldSession.h.
Referenced by SendTimeSync().
m_Tutorials
uint32 WorldSession::m_Tutorials[8] private
Definition at line 1069 of file WorldSession.h.
Referenced by GetTutorialInt(), LoadTutorialsData(), SaveTutorialsData(), SendTutorialsData(), and SetTutorialInt().
m_tutorialState
TutorialDataState WorldSession::m_tutorialState private
Definition at line 1070 of file WorldSession.h.
Referenced by LoadTutorialsData(), SaveTutorialsData(), and SetTutorialInt().
The documentation for this class was generated from the following files:
WorldSession.h
ArenaTeamHandler.cpp
AuctionHouseHandler.cpp
AuctionHouseMgr.cpp
BattlefieldHandler.cpp
BattleGroundHandler.cpp
CalendarHandler.cpp
ChannelHandler.cpp
ChatHandler.cpp
CombatHandler.cpp
DuelHandler.cpp
CharacterHandler.cpp
ItemHandler.cpp
MiscHandler.cpp
NPCHandler.cpp
PetHandler.cpp
PetitionsHandler.cpp
QueryHandler.cpp
RafHandler.cpp
SkillHandler.cpp
VehicleHandler.cpp
GMTicketHandler.cpp
GroupHandler.cpp
GuildHandler.cpp
LFGHandler.cpp
LootHandler.cpp
MailHandler.cpp
TaxiHandler.cpp
MovementHandler.cpp
QuestHandler.cpp
WorldSession.cpp
SpellHandler.cpp
TradeHandler.cpp
VoiceChatHandler.cpp