CMaNGOS_WoTLK: MMAP::MMapFactory Class Reference
MMAP::MMapFactory Class Reference
#include <MoveMap.h>
Static Public Member Functions
static MMapManager * createOrGetMMapManager ()
static void clear ()
static void preventPathfindingOnMaps (const char *ignoreMapIds)
static bool IsPathfindingEnabled (uint32 mapId, const Unit *unit)
static bool IsPathfindingForceEnabled (const Unit *unit)
static bool IsPathfindingForceDisabled (const Unit *unit)
Detailed Description
Definition at line 130 of file MoveMap.h.
Member Function Documentation
clear()
void MMAP::MMapFactory::clear () static
Definition at line 87 of file MoveMap.cpp.
References MMAP::g_mmapDisabledIds, and MMAP::g_MMapManager.
Referenced by World::~World().
createOrGetMMapManager()
MMapManager * MMAP::MMapFactory::createOrGetMMapManager () static
Definition at line 34 of file MoveMap.cpp.
References MMAP::g_MMapManager.
Referenced by Map::ChangeGOPathfinding(), ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapStatsCommand(), Map::Initialize(), Map::LoadMapAndVMap(), PathFinder::PathFinder(), PathFinder::SetCurrentNavMesh(), World::SetInitialWorldSettings(), Map::SetNavTile(), Map::~Map(), and TerrainInfo::~TerrainInfo().
IsPathfindingEnabled()
bool MMAP::MMapFactory::IsPathfindingEnabled (uint32 mapId, const Unit * unit = nullptr) static
Definition at line 61 of file MoveMap.cpp.
References CONFIG_BOOL_MMAP_ENABLED, MMAP::g_mmapDisabledIds, Unit::GetOwner(), Object::GetTypeId(), IsPathfindingForceDisabled(), IsPathfindingForceEnabled(), sWorld, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by MMAP::MMapManager::loadMapData(), PathFinder::PathFinder(), and PathFinder::SetCurrentNavMesh().
IsPathfindingForceDisabled()
bool MMAP::MMapFactory::IsPathfindingForceDisabled (const Unit * unit) static
Definition at line 110 of file MoveMap.cpp.
Referenced by IsPathfindingEnabled().
IsPathfindingForceEnabled()
bool MMAP::MMapFactory::IsPathfindingForceEnabled (const Unit * unit) static
Definition at line 96 of file MoveMap.cpp.
References CREATURE_EXTRA_FLAG_MMAP_FORCE_ENABLE.
Referenced by IsPathfindingEnabled().
preventPathfindingOnMaps()
void MMAP::MMapFactory::preventPathfindingOnMaps (const char * ignoreMapIds) static
Definition at line 42 of file MoveMap.cpp.
References MMAP::g_mmapDisabledIds.
Referenced by World::LoadConfigSettings().
The documentation for this class was generated from the following files:
MoveMap.h
MoveMap.cpp