CMaNGOS_WoTLK: SpellModRAII Class Reference
SpellModRAII Class Reference
#include <Spell.h>
Public Member Functions
SpellModRAII (Spell *spell, Player *modOwner, bool success=false, bool onlySave=false)
void SetSuccess ()
~SpellModRAII ()
Private Attributes
Spell * m_spell
Player * m_modOwner
bool m_success
bool m_onlySave
Detailed Description
Definition at line 334 of file Spell.h.
Constructor & Destructor Documentation
SpellModRAII()
SpellModRAII::SpellModRAII (Spell * spell, Player * modOwner, bool success = false, bool onlySave = false)
Definition at line 9929 of file Spell.cpp.
References Player::GetSpellModSpell(), m_modOwner, and Player::SetSpellModSpell().
~SpellModRAII()
SpellModRAII::~SpellModRAII ()
Definition at line 9935 of file Spell.cpp.
References Player::GetSpellModSpell(), m_modOwner, m_onlySave, m_spell, m_success, Spell::m_usedAuraCharges, Player::RemoveSpellMods(), Player::ResetSpellModsDueToCanceledSpell(), and Player::SetSpellModSpell().
Member Function Documentation
SetSuccess()
void SpellModRAII::SetSuccess () inline
Definition at line 338 of file Spell.h.
References m_success.
Referenced by Spell::cast().
Field Documentation
m_modOwner
Player* SpellModRAII::m_modOwner private
Definition at line 342 of file Spell.h.
Referenced by SpellModRAII(), and ~SpellModRAII().
m_onlySave
bool SpellModRAII::m_onlySave private
Definition at line 344 of file Spell.h.
Referenced by ~SpellModRAII().
m_spell
Spell* SpellModRAII::m_spell private
Definition at line 341 of file Spell.h.
Referenced by ~SpellModRAII().
m_success
bool SpellModRAII::m_success private
Definition at line 343 of file Spell.h.
Referenced by SetSuccess(), and ~SpellModRAII().
The documentation for this class was generated from the following files:
Spell.h
Spell.cpp