CMaNGOS_WoTLK: GroupLootRoll Class Reference
GroupLootRoll Class Reference
#include <LootMgr.h>
Public Types
typedef std::unordered_map< ObjectGuid, PlayerRollVote > RollVoteMap
Public Member Functions
GroupLootRoll ()
~GroupLootRoll ()
bool TryToStart (Loot &loot, uint32 itemSlot)
bool PlayerVote (Player *player, RollVote vote)
bool UpdateRoll ()
Private Member Functions
void SendStartRoll ()
void SendAllPassed ()
void SendRoll (ObjectGuid const &targetGuid, uint32 rollNumber, uint32 rollType)
void SendLootRollWon (ObjectGuid const &targetGuid, uint32 rollNumber, RollVote rollType)
void Finish (RollVoteMap::const_iterator &winnerItr)
bool AllPlayerVoted (RollVoteMap::const_iterator &winnerItr)
: Check if all player have voted and return true in that case.
Private Attributes
RollVoteMap m_rollVoteMap
bool m_isStarted
LootItem * m_lootItem
Loot * m_loot
uint32 m_itemSlot
RollVoteMask m_voteMask
time_t m_endTime
Detailed Description
Definition at line 134 of file LootMgr.h.
Member Typedef Documentation
RollVoteMap
typedef std::unordered_map<ObjectGuid, PlayerRollVote> GroupLootRoll::RollVoteMap
Definition at line 137 of file LootMgr.h.
Constructor & Destructor Documentation
GroupLootRoll()
GroupLootRoll::GroupLootRoll () inline
Definition at line 139 of file LootMgr.h.
~GroupLootRoll()
GroupLootRoll::~GroupLootRoll ()
Definition at line 715 of file LootMgr.cpp.
References m_isStarted, and SendAllPassed().
Member Function Documentation
AllPlayerVoted()
bool GroupLootRoll::AllPlayerVoted (RollVoteMap::const_iterator & winnerItr) private
: Check if all player have voted and return true in that case.
Also return current winner.
Parameters
RollVoteMap::const_iterator& winnerItr > will be different than m_rollCoteMap.end() if winner exist. (Someone voted greed or need)
Returns
: bool > true if all players voted
Definition at line 837 of file LootMgr.cpp.
References m_rollVoteMap, ROLL_DISENCHANT, ROLL_GREED, ROLL_NEED, ROLL_NOT_EMITED_YET, and ROLL_PASS.
Referenced by UpdateRoll().
Finish()
void GroupLootRoll::Finish (RollVoteMap::const_iterator & winnerItr) private
Definition at line 877 of file LootMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, Loot::AddItem(), LootItem::allowedGuid, Loot::AutoStore(), LootItem::count, ItemPrototype::DisenchantID, LootItem::displayID, Player::GetAchievementMgr(), Loot::GetLootItemsListFor(), Object::GetObjectGuid(), Player::GetSession(), LootItem::isBlocked, LootItem::isReleased, LootItem::itemId, LootItem::itemProto, LOOT_DISENCHANTING, LootItem::lootSlot, m_isStarted, m_itemSlot, m_loot, m_lootItem, m_rollVoteMap, Loot::NotifyItemChanged(), Loot::NotifyItemRemoved(), LootItem::randomPropertyId, LootItem::randomSuffix, ROLL_DISENCHANT, ROLL_NEED, SendAllPassed(), Loot::SendItem(), SendLootRollWon(), sObjectMgr, AchievementMgr::UpdateAchievementCriteria(), and Player::UpdateAchievementCriteria().
Referenced by UpdateRoll().
PlayerVote()
bool GroupLootRoll::PlayerVote (Player * player, RollVote vote)
Definition at line 776 of file LootMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, Player::GetAchievementMgr(), Object::GetObjectGuid(), m_rollVoteMap, ROLL_DISENCHANT, ROLL_GREED, ROLL_NEED, ROLL_NOT_VALID, ROLL_PASS, SendRoll(), AchievementMgr::UpdateAchievementCriteria(), and urand().
Referenced by LootMgr::PlayerVote().
SendAllPassed()
void GroupLootRoll::SendAllPassed () private
Definition at line 622 of file LootMgr.cpp.
References Loot::GetLootGuid(), Player::GetSession(), LootItem::itemId, m_itemSlot, m_loot, m_lootItem, m_rollVoteMap, LootItem::randomPropertyId, LootItem::randomSuffix, ROLL_NOT_VALID, WorldSession::SendPacket(), SMSG_LOOT_ALL_PASSED, and sObjectMgr.
Referenced by Finish(), and ~GroupLootRoll().
SendLootRollWon()
void GroupLootRoll::SendLootRollWon (ObjectGuid const & targetGuid, uint32 rollNumber, RollVote rollType) private
Definition at line 645 of file LootMgr.cpp.
References Loot::GetLootGuid(), Player::GetSession(), LootItem::itemId, m_itemSlot, m_loot, m_lootItem, m_rollVoteMap, LootItem::randomPropertyId, LootItem::randomSuffix, ROLL_GREED, ROLL_NEED, ROLL_NOT_EMITED_YET, ROLL_NOT_VALID, ROLL_PASS, WorldSession::SendPacket(), SendRoll(), SMSG_LOOT_ROLL_WON, and sObjectMgr.
Referenced by Finish().
SendRoll()
void GroupLootRoll::SendRoll (ObjectGuid const & targetGuid, uint32 rollNumber, uint32 rollType) private
Definition at line 689 of file LootMgr.cpp.
References Loot::GetLootGuid(), Player::GetSession(), LootItem::itemId, m_itemSlot, m_loot, m_lootItem, m_rollVoteMap, LootItem::randomPropertyId, LootItem::randomSuffix, ROLL_NOT_VALID, WorldSession::SendPacket(), SMSG_LOOT_ROLL, and sObjectMgr.
Referenced by PlayerVote(), and SendLootRollWon().
SendStartRoll()
void GroupLootRoll::SendStartRoll () private
Definition at line 587 of file LootMgr.cpp.
References Player::CanUseItem(), LootItem::count, EQUIP_ERR_OK, Loot::GetLootGuid(), Loot::GetLootTarget(), WorldObject::GetMapId(), Player::GetSession(), LootItem::itemId, LootItem::itemProto, LOOT_ROLL_TIMEOUT, m_itemSlot, m_loot, m_lootItem, Loot::m_lootMethod, m_rollVoteMap, m_voteMask, NEED_BEFORE_GREED, ByteBuffer::put(), LootItem::randomPropertyId, LootItem::randomSuffix, ROLL_NOT_VALID, ROLL_VOTE_MASK_NEED, WorldSession::SendPacket(), SMSG_LOOT_START_ROLL, sObjectMgr, and ByteBuffer::wpos().
Referenced by TryToStart().
TryToStart()
bool GroupLootRoll::TryToStart (Loot & loot, uint32 itemSlot)
Definition at line 723 of file LootMgr.cpp.
References ItemPrototype::DisenchantID, ItemPrototype::Flags2, Loot::GetLootItemInSlot(), LootItem::IsAllowed(), LootItem::isBlocked, LootItem::isUnderThreshold, ITEM_FLAG2_CAN_ONLY_ROLL_GREED, LootItem::itemProto, LOOT_ROLL_TIMEOUT, LOOTITEM_TYPE_QUEST, LootItem::lootItemType, m_endTime, m_isStarted, m_itemSlot, m_loot, m_lootItem, Loot::m_lootItems, Loot::m_maxEnchantSkill, Loot::m_ownerSet, m_rollVoteMap, m_voteMask, ItemPrototype::RequiredDisenchantSkill, ROLL_NOT_EMITED_YET, ROLL_NOT_VALID, ROLL_VOTE_MASK_ALL, ROLL_VOTE_MASK_DISENCHANT, ROLL_VOTE_MASK_NEED, SendStartRoll(), and sObjectMgr.
UpdateRoll()
bool GroupLootRoll::UpdateRoll ()
Definition at line 820 of file LootMgr.cpp.
References AllPlayerVoted(), Finish(), m_endTime, and m_rollVoteMap.
Field Documentation
m_endTime
time_t GroupLootRoll::m_endTime private
Definition at line 160 of file LootMgr.h.
Referenced by TryToStart(), and UpdateRoll().
m_isStarted
bool GroupLootRoll::m_isStarted private
Definition at line 155 of file LootMgr.h.
Referenced by Finish(), TryToStart(), and ~GroupLootRoll().
m_itemSlot
uint32 GroupLootRoll::m_itemSlot private
Definition at line 158 of file LootMgr.h.
Referenced by Finish(), SendAllPassed(), SendLootRollWon(), SendRoll(), SendStartRoll(), and TryToStart().
m_loot
Loot* GroupLootRoll::m_loot private
Definition at line 157 of file LootMgr.h.
Referenced by Finish(), SendAllPassed(), SendLootRollWon(), SendRoll(), SendStartRoll(), and TryToStart().
m_lootItem
LootItem* GroupLootRoll::m_lootItem private
Definition at line 156 of file LootMgr.h.
Referenced by Finish(), SendAllPassed(), SendLootRollWon(), SendRoll(), SendStartRoll(), and TryToStart().
m_rollVoteMap
RollVoteMap GroupLootRoll::m_rollVoteMap private
Definition at line 154 of file LootMgr.h.
Referenced by AllPlayerVoted(), Finish(), PlayerVote(), SendAllPassed(), SendLootRollWon(), SendRoll(), SendStartRoll(), TryToStart(), and UpdateRoll().
m_voteMask
RollVoteMask GroupLootRoll::m_voteMask private
Definition at line 159 of file LootMgr.h.
Referenced by SendStartRoll(), and TryToStart().
The documentation for this class was generated from the following files:
LootMgr.h
LootMgr.cpp