CMaNGOS_WoTLK: AbstractPathMovementGenerator Class Reference
AbstractPathMovementGenerator Class Reference
#include <PathMovementGenerator.h>
Public Member Functions
AbstractPathMovementGenerator (const Movement::PointsArray &path, float orientation=0, int32 offset=0)
AbstractPathMovementGenerator (const WaypointPath *path, int32 offset=0, bool cyclic=false, ObjectGuid guid=ObjectGuid())
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
void Reset (Unit &owner) override
bool Update (Unit &owner, const uint32 &) override
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual MovementGeneratorType GetMovementGeneratorType () const =0
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual void MovementInform (Unit &unit)
Protected Attributes
WaypointPath m_path
int32 m_pathIndex
Movement::PointsArray m_spline
float m_orientation
ShortTimeTracker m_timer
bool m_cyclic
bool m_firstCycle
uint32 m_startPoint
ObjectGuid m_guid
Private Attributes
bool m_speedChanged
Detailed Description
Definition at line 29 of file PathMovementGenerator.h.
Constructor & Destructor Documentation
AbstractPathMovementGenerator() [1/2]
AbstractPathMovementGenerator::AbstractPathMovementGenerator (const Movement::PointsArray & path, float orientation = 0, int32 offset = 0) explicit
Definition at line 29 of file PathMovementGenerator.cpp.
References m_path, and m_spline.
AbstractPathMovementGenerator() [2/2]
AbstractPathMovementGenerator::AbstractPathMovementGenerator (const WaypointPath * path, int32 offset = 0, bool cyclic = false, ObjectGuid guid = ObjectGuid()) explicit
Definition at line 39 of file PathMovementGenerator.cpp.
References m_cyclic, m_path, and m_spline.
Member Function Documentation
Finalize()
void AbstractPathMovementGenerator::Finalize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PathJumpGenerator, TaxiMovementGenerator, and FixedPathMovementGenerator.
Definition at line 118 of file PathMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), Unit::InterruptMoving(), Unit::IsClientControlled(), Unit::movespline, and Unit::StopMoving().
Referenced by FixedPathMovementGenerator::Finalize(), TaxiMovementGenerator::Finalize(), and PathJumpGenerator::Finalize().
Initialize()
void AbstractPathMovementGenerator::Initialize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PathJumpGenerator, TaxiMovementGenerator, and FixedPathMovementGenerator.
Definition at line 61 of file PathMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), Object::GetDbGuid(), Object::GetEntry(), WorldObject::GetName(), Unit::InterruptMoving(), Unit::IsClientControlled(), m_cyclic, m_orientation, m_path, m_pathIndex, m_speedChanged, m_spline, m_timer, Unit::movespline, ShortTimeTracker::Reset(), sLog, and Unit::StopMoving().
Referenced by FixedPathMovementGenerator::Initialize(), TaxiMovementGenerator::Initialize(), PathJumpGenerator::Initialize(), Reset(), and Update().
Interrupt()
void AbstractPathMovementGenerator::Interrupt (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PathJumpGenerator, TaxiMovementGenerator, and FixedPathMovementGenerator.
Definition at line 130 of file PathMovementGenerator.cpp.
References Unit::InterruptMoving().
Referenced by FixedPathMovementGenerator::Interrupt(), TaxiMovementGenerator::Interrupt(), and PathJumpGenerator::Interrupt().
MovementInform()
void AbstractPathMovementGenerator::MovementInform (Unit & unit) protected virtual
Definition at line 196 of file PathMovementGenerator.cpp.
References Unit::AI(), DEBUG_FILTER_LOG, Map::GetAnyTypeCreature(), Object::GetGuidStr(), WorldObject::GetMap(), MovementGenerator::GetMovementGeneratorType(), WorldObject::GetSpawnerGuid(), Object::GetTypeId(), ObjectGuid::IsCreatureOrPet(), Creature::IsTemporarySummon(), LOG_FILTER_AI_AND_MOVEGENSS, m_firstCycle, m_path, m_pathIndex, WaypointNode::script_id, SCRIPT_TYPE_CREATURE_MOVEMENT, Map::ScriptsStart(), and TYPEID_UNIT.
Referenced by Update().
Reset()
void AbstractPathMovementGenerator::Reset (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PathJumpGenerator, and FixedPathMovementGenerator.
Definition at line 135 of file PathMovementGenerator.cpp.
References Initialize().
Referenced by FixedPathMovementGenerator::Reset(), and PathJumpGenerator::Reset().
UnitSpeedChanged()
void AbstractPathMovementGenerator::UnitSpeedChanged () inline override virtual
Reimplemented from MovementGenerator.
Definition at line 41 of file PathMovementGenerator.h.
References m_speedChanged.
Update()
bool AbstractPathMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Implements MovementGenerator.
Reimplemented in TaxiMovementGenerator.
Definition at line 140 of file PathMovementGenerator.cpp.
References Movement::MoveSpline::currentPathIdx(), Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::Finalized(), Initialize(), m_cyclic, m_firstCycle, m_path, m_pathIndex, m_speedChanged, m_spline, m_startPoint, m_timer, MovementInform(), Unit::movespline, ShortTimeTracker::Passed(), and ShortTimeTracker::Update().
Referenced by TaxiMovementGenerator::Update().
Field Documentation
m_cyclic
bool AbstractPathMovementGenerator::m_cyclic protected
Definition at line 52 of file PathMovementGenerator.h.
Referenced by AbstractPathMovementGenerator(), Initialize(), FixedPathMovementGenerator::Move(), and Update().
m_firstCycle
bool AbstractPathMovementGenerator::m_firstCycle protected
Definition at line 53 of file PathMovementGenerator.h.
Referenced by FixedPathMovementGenerator::Initialize(), PathJumpGenerator::Initialize(), MovementInform(), and Update().
m_guid
ObjectGuid AbstractPathMovementGenerator::m_guid protected
Definition at line 55 of file PathMovementGenerator.h.
m_orientation
float AbstractPathMovementGenerator::m_orientation protected
Definition at line 50 of file PathMovementGenerator.h.
Referenced by Initialize(), FixedPathMovementGenerator::Move(), and PathJumpGenerator::Move().
m_path
WaypointPath AbstractPathMovementGenerator::m_path protected
Definition at line 47 of file PathMovementGenerator.h.
Referenced by AbstractPathMovementGenerator(), Initialize(), MovementInform(), TaxiMovementGenerator::Resume(), and Update().
m_pathIndex
int32 AbstractPathMovementGenerator::m_pathIndex protected
Definition at line 48 of file PathMovementGenerator.h.
Referenced by Initialize(), FixedPathMovementGenerator::Initialize(), PathJumpGenerator::Initialize(), TaxiMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), MovementInform(), TaxiMovementGenerator::Resume(), and Update().
m_speedChanged
bool AbstractPathMovementGenerator::m_speedChanged private
Definition at line 58 of file PathMovementGenerator.h.
Referenced by Initialize(), UnitSpeedChanged(), and Update().
m_spline
Movement::PointsArray AbstractPathMovementGenerator::m_spline protected
Definition at line 49 of file PathMovementGenerator.h.
Referenced by AbstractPathMovementGenerator(), FixedPathMovementGenerator::AddToPathPauseTime(), Initialize(), FixedPathMovementGenerator::Initialize(), PathJumpGenerator::Initialize(), TaxiMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), TaxiMovementGenerator::Resume(), and Update().
m_startPoint
uint32 AbstractPathMovementGenerator::m_startPoint protected
Definition at line 54 of file PathMovementGenerator.h.
Referenced by FixedPathMovementGenerator::Initialize(), PathJumpGenerator::Initialize(), and Update().
m_timer
ShortTimeTracker AbstractPathMovementGenerator::m_timer protected
Definition at line 51 of file PathMovementGenerator.h.
Referenced by FixedPathMovementGenerator::AddToPathPauseTime(), Initialize(), and Update().
The documentation for this class was generated from the following files:
PathMovementGenerator.h
PathMovementGenerator.cpp