CMaNGOS_WoTLK: InstanceData Class Reference
InstanceData Class Reference
#include <InstanceData.h>
Public Member Functions
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Initialize ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectCreate (GameObject *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Data Fields
Map * instance
Detailed Description
Definition at line 105 of file InstanceData.h.
Constructor & Destructor Documentation
InstanceData()
InstanceData::InstanceData (Map * map) inline explicit
Definition at line 109 of file InstanceData.h.
~InstanceData()
virtual InstanceData::~InstanceData () inline virtual
Definition at line 110 of file InstanceData.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool InstanceData::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * target = nullptr, uint32 miscvalue1 = 0) const virtual
Reimplemented in instance_icecrown_citadel, instance_trial_of_the_crusader, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_obsidian_sanctum, instance_nexus, instance_naxxramas, instance_pit_of_saron, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, and instance_onyxias_lair.
Definition at line 43 of file InstanceData.cpp.
References Map::GetId(), instance, and sLog.
Referenced by AchievementCriteriaRequirement::Meets().
CheckConditionCriteriaMeet()
bool InstanceData::CheckConditionCriteriaMeet (Player const * source, uint32 instance_condition_id, WorldObject const * conditionSource, uint32 conditionSourceType) const virtual
Reimplemented in instance_icecrown_citadel, instance_shattered_halls, instance_serpentshrine_cavern, instance_ulduar, instance_obsidian_sanctum, instance_dire_maul, instance_mount_hyjal, instance_dark_portal, instance_blackwing_lair, world_map_outland, world_map_kalimdor, instance_zulaman, world_map_eastern_kingdoms, and instance_stratholme.
Definition at line 50 of file InstanceData.cpp.
References Map::GetId(), instance, and sLog.
ExecuteChatCommand()
virtual void InstanceData::ExecuteChatCommand (ChatHandler * , char *) inline virtual
Reimplemented in world_map_outland, instance_mechanar, instance_blood_furnace, instance_serpentshrine_cavern, instance_violet_hold, instance_halls_of_stone, instance_icecrown_citadel, instance_halls_of_reflection, instance_trial_of_the_crusader, instance_mount_hyjal, instance_dark_portal, instance_zulaman, instance_sunwell_plateau, and instance_molten_core.
Definition at line 212 of file InstanceData.h.
FillInitialWorldStateData() [1/2]
void InstanceData::FillInitialWorldStateData (ByteBuffer & data, uint32 & count, uint32 state, int32 value) inline
Definition at line 204 of file InstanceData.h.
FillInitialWorldStateData() [2/2]
void InstanceData::FillInitialWorldStateData (ByteBuffer & data, uint32 & count, uint32 state, uint32 value) inline
Definition at line 197 of file InstanceData.h.
Referenced by world_map_outland::FillInitialWorldStates().
FillInitialWorldStates()
virtual void InstanceData::FillInitialWorldStates (ByteBuffer & , uint32 & , uint32 , uint32) inline virtual
Reimplemented in world_map_outland.
Definition at line 194 of file InstanceData.h.
GetData()
virtual uint32 InstanceData::GetData (uint32) const inline virtual
Reimplemented in instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_ramparts, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_obsidian_sanctum, instance_oculus, instance_nexus, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulaman, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_scholomance, world_map_ebon_hold, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, instance_scarlet_monastery, world_map_outland, instance_blood_furnace, instance_underbog, instance_slave_pens, instance_black_temple, world_map_kalimdor, instance_maraudon, instance_zulgurub, world_map_eastern_kingdoms, instance_stratholme, and instance_shadowfang_keep.
Definition at line 182 of file InstanceData.h.
Referenced by boss_alythessAI::Aggro(), boss_sacrolashAI::Aggro(), mob_fel_orc_convertAI::Aggro(), AreaTrigger_at_ghazan_surface(), AreaTrigger_at_hive_tower(), AreaTrigger_at_naturalist_bite(), boss_vazruden_heraldAI::AttackStart(), boss_chromaggusAI::boss_chromaggusAI(), boss_thekalAI::CanPreventAddsResurrect(), boss_vazruden_heraldAI::DoMoveToCombat(), npc_forest_frogAI::DoSpawnRandom(), boss_alythessAI::EnterEvadeMode(), boss_sacrolashAI::EnterEvadeMode(), boss_volazjAI::EnterEvadeMode(), GossipHello_npc_ashli(), GossipHello_npc_aurius(), GossipHello_npc_barrett_ramsey(), GossipHello_npc_disciple_of_naralex(), GossipHello_npc_erozion(), GossipHello_npc_harkor(), GossipHello_npc_harrison_jones_za(), GossipHello_npc_kraz(), GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), GossipHello_npc_shadowfang_prisoner(), GossipHello_npc_tanzar(), GossipSelect_npc_barrett_ramsey(), GOUse_go_big_red_button(), GOUse_go_celestial_access(), GOUse_go_defias_cannon(), GOUse_go_gauntlet_gate(), GOUse_go_main_chambers_access_panel(), GOUse_go_nerubian_device(), GOUse_go_prison_cell_lever(), GOUse_go_sapphiron_birth(), GOUse_go_service_gate(), GOUse_go_stratholme_postbox(), GOUse_go_twilight_portal(), GOUse_go_wooden_door(), boss_hakkarAI::InitiateHakkarPowerStacks(), boss_victor_nefariusAI::JustDidDialogueStep(), boss_lady_blaumeuxAI::JustDied(), boss_rivendare_naxxAI::JustDied(), boss_thane_korthazzAI::JustDied(), boss_sir_zeliekAI::JustDied(), mob_fel_orc_convertAI::JustDied(), mob_zealot_lorkhanAI::mob_zealot_lorkhanAI(), mob_zealot_zathAI::mob_zealot_zathAI(), mob_steamrigger_mechanicAI::MoveInLineOfSight(), npc_reliquary_LOS_aggro_triggerAI::MoveInLineOfSight(), npc_inner_demonAI::npc_inner_demonAI(), InsidiousWhisper::OnApply(), SummonVoidSentinelSummonerVisual::OnEffectExecute(), go_ai_suppression::OnLootStateChange(), ProcessEventId_event_spell_summon_nightbane(), QuestAccept_npc_major_mills(), QuestRewarded_npc_aurius(), QuestRewarded_npc_rocknot(), npc_deathstalker_vincentAI::Reset(), npc_orphan_matronAI::SummonShadeOfTheHorseman(), npc_ironhand_guardianAI::UpdateAI(), go_screaming_hall_door::UpdateAI(), npc_orphanAI::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), boss_grand_warlock_nethekurseAI::UpdateAI(), boss_dalliahAI::UpdateAI(), and npc_kindal_moonweaverAI::UpdateFollowerAI().
GetData64()
virtual uint64 InstanceData::GetData64 (uint32) const inline virtual
Reimplemented in instance_uldaman.
Definition at line 174 of file InstanceData.h.
Referenced by GetGuid().
GetGuid()
ObjectGuid InstanceData::GetGuid (uint32 dataIdx) const inline
Definition at line 178 of file InstanceData.h.
References GetData64().
Referenced by boss_archaedasAI::UpdateAI().
Initialize()
virtual void InstanceData::Initialize () inline virtual
Reimplemented in world_map_outland, instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_ramparts, instance_blood_furnace, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_black_temple, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_obsidian_sanctum, instance_oculus, instance_nexus, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, world_map_kalimdor, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_onyxias_lair, instance_maraudon, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulgurub, instance_zulaman, world_map_eastern_kingdoms, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_stratholme, instance_shadowfang_keep, instance_scholomance, instance_scarlet_monastery, world_map_ebon_hold, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, instance_underbog, and instance_slave_pens.
Definition at line 115 of file InstanceData.h.
Referenced by Map::CreateInstanceData().
IsEncounterInProgress()
virtual bool InstanceData::IsEncounterInProgress () const inline virtual
Reimplemented in instance_the_eye, instance_magtheridons_lair, instance_gruuls_lair, instance_serpentshrine_cavern, instance_black_temple, instance_ulduar, instance_ruby_sanctum, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_trial_of_the_crusader, instance_temple_of_ahnqiraj, instance_onyxias_lair, instance_mount_hyjal, instance_zulaman, instance_sunwell_plateau, instance_molten_core, instance_karazhan, and instance_blackwing_lair.
Definition at line 129 of file InstanceData.h.
Referenced by Spell::EffectSanctuary(), Player::GetAreaTriggerLockStatus(), WorldSession::HandleChangePlayerDifficulty(), Aura::HandleModUnattackable(), and Unit::SetFeignDeath().
Load()
virtual void InstanceData::Load (const char *) inline virtual
Reimplemented in instance_icecrown_citadel, instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_blood_furnace, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_black_temple, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_oculus, instance_nexus, instance_naxxramas, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_maraudon, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulgurub, instance_zulaman, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_stratholme, instance_shadowfang_keep, instance_scholomance, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, and instance_blackrock_depths.
Definition at line 118 of file InstanceData.h.
Referenced by Map::CreateInstanceData().
OnCreatureCreate()
virtual void InstanceData::OnCreatureCreate (Creature *) inline virtual
Reimplemented in instance_mechanar, instance_the_eye, instance_arcatraz, instance_magtheridons_lair, instance_ramparts, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_obsidian_sanctum, instance_oculus, instance_nexus, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, world_map_kalimdor, instance_wailing_caverns, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_onyxias_lair, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, world_map_eastern_kingdoms, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_scholomance, instance_scarlet_monastery, world_map_ebon_hold, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, world_map_outland, instance_shattered_halls, instance_blood_furnace, instance_underbog, instance_slave_pens, instance_black_temple, world_map_northrend, instance_temple_of_ahnqiraj, instance_zulgurub, instance_zulaman, instance_stratholme, and instance_shadowfang_keep.
Definition at line 150 of file InstanceData.h.
OnCreatureDeath()
virtual void InstanceData::OnCreatureDeath (Creature *) inline virtual
Reimplemented in instance_mechanar, instance_arcatraz, instance_steam_vault, instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_oculus, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, world_map_kalimdor, instance_ruins_of_ahnqiraj, instance_razorfen_downs, instance_onyxias_lair, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, world_map_eastern_kingdoms, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_scholomance, instance_scarlet_monastery, world_map_ebon_hold, instance_karazhan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, world_map_outland, instance_shattered_halls, instance_blood_furnace, instance_underbog, instance_black_temple, instance_temple_of_ahnqiraj, instance_maraudon, instance_zulaman, instance_stratholme, and instance_shadowfang_keep.
Definition at line 162 of file InstanceData.h.
OnCreatureDespawn()
virtual void InstanceData::OnCreatureDespawn (Creature *) inline virtual
Reimplemented in instance_halls_of_reflection, instance_trial_of_the_champion, instance_blackrock_spire, and world_map_outland.
Definition at line 165 of file InstanceData.h.
OnCreatureEnterCombat()
virtual void InstanceData::OnCreatureEnterCombat (Creature *) inline virtual
Reimplemented in instance_serpentshrine_cavern, instance_violet_hold, instance_ulduar, instance_halls_of_stone, instance_oculus, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_champion, instance_azjol_nerub, instance_zulfarrak, instance_ruins_of_ahnqiraj, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_scholomance, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, instance_shattered_halls, instance_sunwell_plateau, and instance_stratholme.
Definition at line 156 of file InstanceData.h.
OnCreatureEvade()
virtual void InstanceData::OnCreatureEvade (Creature *) inline virtual
Reimplemented in instance_violet_hold, instance_pinnacle, instance_halls_of_stone, instance_oculus, instance_halls_of_reflection, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_uldaman, instance_sunwell_plateau, instance_blackrock_spire, instance_blackrock_depths, instance_draktharon_keep, instance_zulfarrak, instance_ruins_of_ahnqiraj, instance_old_hillsbrad, instance_dark_portal, instance_sunken_temple, instance_scholomance, world_map_outland, instance_the_eye, instance_shattered_halls, instance_blood_furnace, instance_black_temple, instance_maraudon, instance_zulaman, instance_shadowfang_keep, instance_karazhan, and instance_stratholme.
Definition at line 159 of file InstanceData.h.
OnCreatureGroupDespawn()
virtual void InstanceData::OnCreatureGroupDespawn (CreatureGroup * , Creature *) inline virtual
Reimplemented in instance_uldaman.
Definition at line 168 of file InstanceData.h.
Referenced by CreatureGroup::RemoveObject().
OnCreatureRespawn()
virtual void InstanceData::OnCreatureRespawn (Creature *) inline virtual
Reimplemented in instance_violet_hold, instance_halls_of_stone, instance_ruby_sanctum, instance_oculus, instance_eye_of_eternity, instance_icecrown_citadel, instance_pit_of_saron, instance_trial_of_the_crusader, instance_azjol_nerub, world_map_ebon_hold, world_map_outland, instance_the_eye, instance_shattered_halls, instance_ramparts, instance_black_temple, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_nexus, instance_naxxramas, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_mount_hyjal, instance_zulaman, instance_sunwell_plateau, instance_stratholme, instance_shadowfang_keep, instance_scarlet_monastery, instance_karazhan, instance_blackwing_lair, and instance_blackrock_depths.
Definition at line 153 of file InstanceData.h.
OnEventHappened()
virtual void InstanceData::OnEventHappened (uint16 , bool , bool) inline virtual
Reimplemented in world_map_kalimdor, and world_map_eastern_kingdoms.
Definition at line 171 of file InstanceData.h.
Referenced by Map::OnEventHappened().
OnObjectCreate()
virtual void InstanceData::OnObjectCreate (GameObject *) inline virtual
Reimplemented in instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_ramparts, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_oculus, instance_nexus, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, world_map_kalimdor, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_onyxias_lair, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulaman, world_map_eastern_kingdoms, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_scholomance, instance_scarlet_monastery, world_map_ebon_hold, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, world_map_outland, instance_blood_furnace, instance_black_temple, instance_ruins_of_ahnqiraj, instance_maraudon, instance_zulgurub, instance_stratholme, and instance_shadowfang_keep.
Definition at line 144 of file InstanceData.h.
OnObjectSpawn()
virtual void InstanceData::OnObjectSpawn (GameObject *) inline virtual
Reimplemented in instance_icecrown_citadel, instance_ulduar, and instance_scarlet_monastery.
Definition at line 147 of file InstanceData.h.
OnPlayerDeath()
virtual void InstanceData::OnPlayerDeath (Player *) inline virtual
Reimplemented in instance_ulduar, instance_naxxramas, instance_trial_of_the_crusader, instance_mount_hyjal, instance_sunwell_plateau, and instance_gundrak.
Definition at line 135 of file InstanceData.h.
OnPlayerEnter()
virtual void InstanceData::OnPlayerEnter (Player *) inline virtual
Reimplemented in instance_mechanar, instance_arcatraz, instance_shattered_halls, instance_violet_hold, instance_pinnacle, instance_ulduar, instance_halls_of_stone, instance_ruby_sanctum, instance_oculus, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_wailing_caverns, instance_ruins_of_ahnqiraj, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_sunwell_plateau, instance_scholomance, instance_molten_core, instance_karazhan, instance_deadmines, instance_blood_furnace, instance_slave_pens, instance_black_temple, instance_zulaman, instance_stratholme, instance_shadowfang_keep, instance_scarlet_monastery, and instance_blackrock_depths.
Definition at line 132 of file InstanceData.h.
Referenced by Map::Add().
OnPlayerLeave()
virtual void InstanceData::OnPlayerLeave (Player *) inline virtual
Definition at line 141 of file InstanceData.h.
Referenced by Map::Remove().
OnPlayerResurrect()
virtual void InstanceData::OnPlayerResurrect (Player *) inline virtual
Reimplemented in instance_serpentshrine_cavern, and instance_black_temple.
Definition at line 138 of file InstanceData.h.
Save()
virtual const char* InstanceData::Save () const inline virtual
Reimplemented in instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_blood_furnace, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_black_temple, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_oculus, instance_nexus, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_maraudon, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulgurub, instance_zulaman, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_stratholme, instance_shadowfang_keep, instance_scholomance, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, and instance_blackrock_depths.
Definition at line 121 of file InstanceData.h.
Referenced by DungeonPersistentState::SaveToDB(), and SaveToDB().
SaveToDB()
void InstanceData::SaveToDB () const
Definition at line 25 of file InstanceData.cpp.
References CharacterDatabase, Database::escape_string(), Map::GetId(), Map::GetInstanceId(), instance, Map::Instanceable(), Map::IsBattleGroundOrArena(), Database::PExecute(), and Save().
Referenced by ChatHandler::HandleInstanceSaveDataCommand(), instance_shadowfang_keep::SetData(), instance_stratholme::SetData(), instance_zulgurub::SetData(), instance_maraudon::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), instance_blackrock_depths::SetData(), instance_blackrock_spire::SetData(), instance_blackwing_lair::SetData(), instance_deadmines::SetData(), instance_gnomeregan::SetData(), instance_karazhan::SetData(), instance_magisters_terrace::SetData(), instance_molten_core::SetData(), instance_scholomance::SetData(), instance_sunken_temple::SetData(), instance_sunwell_plateau::SetData(), instance_uldaman::SetData(), instance_zulaman::SetData(), instance_blackfathom_deeps::SetData(), instance_culling_of_stratholme::SetData(), instance_dark_portal::SetData(), instance_mount_hyjal::SetData(), instance_old_hillsbrad::SetData(), instance_dire_maul::SetData(), instance_razorfen_downs::SetData(), instance_razorfen_kraul::SetData(), instance_ruins_of_ahnqiraj::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_wailing_caverns::SetData(), instance_zulfarrak::SetData(), instance_ahnkahet::SetData(), instance_azjol_nerub::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_draktharon_keep::SetData(), instance_gundrak::SetData(), instance_forge_of_souls::SetData(), instance_halls_of_reflection::SetData(), instance_pit_of_saron::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_nexus::SetData(), instance_oculus::SetData(), instance_ruby_sanctum::SetData(), instance_halls_of_lightning::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_utgarde_keep::SetData(), instance_pinnacle::SetData(), instance_violet_hold::SetData(), instance_sethekk_halls::SetData(), instance_shadow_labyrinth::SetData(), instance_serpentshrine_cavern::SetData(), instance_steam_vault::SetData(), instance_gruuls_lair::SetData(), instance_shattered_halls::SetData(), instance_arcatraz::SetData(), instance_the_eye::SetData(), and instance_mechanar::SetData().
SendEncounterFrame()
void InstanceData::SendEncounterFrame (uint32 type, ObjectGuid sourceGuid = ObjectGuid(), uint8 param1 = 0, uint8 param2 = 0) const
Definition at line 57 of file InstanceData.cpp.
References ENCOUNTER_FRAME_ADD_TIMER, ENCOUNTER_FRAME_DISABLE_OBJECTIVE, ENCOUNTER_FRAME_DISENGAGE, ENCOUNTER_FRAME_ENABLE_OBJECTIVE, ENCOUNTER_FRAME_ENGAGE, ENCOUNTER_FRAME_UNK7, ENCOUNTER_FRAME_UPDATE_OBJECTIVE, ENCOUNTER_FRAME_UPDATE_PRIORITY, instance, MANGOS_ASSERT, Map::SendToPlayers(), SMSG_INSTANCE_ENCOUNTER, and ObjectGuid::WriteAsPacked().
Referenced by boss_halion_realAI::Aggro(), boss_halion_twilightAI::Aggro(), instance_icecrown_citadel::SetData(), and instance_ruby_sanctum::SetData().
SetData()
virtual void InstanceData::SetData (uint32 , uint32) inline virtual
Reimplemented in world_map_northrend, instance_mechanar, instance_the_eye, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_ramparts, instance_gruuls_lair, instance_steam_vault, instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_utgarde_keep, instance_ulduar, instance_halls_of_stone, instance_halls_of_lightning, instance_ruby_sanctum, instance_obsidian_sanctum, instance_oculus, instance_nexus, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_pit_of_saron, instance_halls_of_reflection, instance_forge_of_souls, instance_gundrak, instance_draktharon_keep, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_ahnkahet, instance_zulfarrak, instance_wailing_caverns, instance_temple_of_ahnqiraj, instance_ruins_of_ahnqiraj, instance_razorfen_kraul, instance_razorfen_downs, instance_onyxias_lair, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulaman, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_scholomance, instance_scarlet_monastery, world_map_ebon_hold, instance_molten_core, instance_magisters_terrace, instance_karazhan, instance_gnomeregan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, instance_blackrock_depths, world_map_kalimdor, world_map_outland, instance_blood_furnace, instance_underbog, instance_slave_pens, instance_black_temple, instance_maraudon, instance_zulgurub, world_map_eastern_kingdoms, instance_stratholme, and instance_shadowfang_keep.
Definition at line 183 of file InstanceData.h.
Referenced by boss_ambassador_flamelashAI::Aggro(), boss_broodlordAI::Aggro(), boss_chromaggusAI::Aggro(), boss_ebonrocAI::Aggro(), boss_firemawAI::Aggro(), boss_flamegorAI::Aggro(), boss_vaelastraszAI::Aggro(), boss_victor_nefariusAI::Aggro(), boss_curatorAI::Aggro(), boss_maiden_of_virtueAI::Aggro(), boss_moroesAI::Aggro(), boss_netherspiteAI::Aggro(), boss_malchezaarAI::Aggro(), boss_terestianAI::Aggro(), boss_felblood_kaelthasAI::Aggro(), boss_priestess_delrissaAI::Aggro(), boss_vexallusAI::Aggro(), boss_baron_geddonAI::Aggro(), boss_garrAI::Aggro(), boss_gehennasAI::Aggro(), boss_golemaggAI::Aggro(), boss_lucifronAI::Aggro(), boss_magmadarAI::Aggro(), boss_shazzrahAI::Aggro(), boss_sulfuronAI::Aggro(), boss_alythessAI::Aggro(), boss_sacrolashAI::Aggro(), boss_halazziAI::Aggro(), boss_janalaiAI::Aggro(), boss_mandokirAI::Aggro(), mob_zealot_lorkhanAI::Aggro(), mob_zealot_zathAI::Aggro(), boss_silithidRoyaltyAI::Aggro(), boss_eye_of_cthunAI::Aggro(), boss_fankrissAI::Aggro(), boss_huhuranAI::Aggro(), boss_sarturaAI::Aggro(), boss_skeramAI::Aggro(), boss_viscidusAI::Aggro(), boss_amanitarAI::Aggro(), boss_volazjAI::Aggro(), boss_tharonjaAI::Aggro(), npc_blood_orb_controlAI::Aggro(), boss_talon_king_ikissAI::Aggro(), boss_blackheart_the_inciterAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_gurtogg_bloodboilAI::Aggro(), boss_supremusAI::Aggro(), boss_illidari_councilAI::Aggro(), boss_fathomlord_karathressAI::Aggro(), boss_leotheras_the_blindAI::Aggro(), boss_morogrim_tidewalkerAI::Aggro(), boss_thespiaAI::Aggro(), boss_mekgineer_steamriggerAI::Aggro(), boss_gruulAI::Aggro(), boss_high_king_maulgarAI::Aggro(), boss_broggokAI::Aggro(), boss_the_makerAI::Aggro(), mob_hellfire_channelerAI::Aggro(), boss_warbringer_omroggAI::Aggro(), boss_warchief_kargath_bladefistAI::Aggro(), boss_dalliahAI::Aggro(), boss_soccothratesAI::Aggro(), boss_alarAI::Aggro(), boss_high_astromancer_solarianAI::Aggro(), boss_void_reaverAI::Aggro(), boss_nethermancer_sepethreaAI::Aggro(), mob_fel_orc_convertAI::Aggro(), npc_warden_mellicharAI::Aggro(), BossAI::Aggro(), AreaTrigger_at_ghazan_surface(), AreaTrigger_at_hive_tower(), AreaTrigger_at_naturalist_bite(), boss_vaelastraszAI::BeginIntro(), boss_tethyrAI::boss_tethyrAI(), boss_thekalAI::boss_thekalAI(), boss_tethyrAI::DoEncounterCleanup(), npc_forest_frogAI::DoSpawnRandom(), boss_nefarianAI::EnterEvadeMode(), boss_netherspiteAI::EnterEvadeMode(), boss_felblood_kaelthasAI::EnterEvadeMode(), boss_alythessAI::EnterEvadeMode(), boss_sacrolashAI::EnterEvadeMode(), boss_mandokirAI::EnterEvadeMode(), boss_archimondeAI::EnterEvadeMode(), boss_viscidusAI::EnterEvadeMode(), boss_dalliahAI::EnterEvadeMode(), boss_soccothratesAI::EnterEvadeMode(), boss_ouroAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), GossipSelect_npc_barrett_ramsey(), GOUse_go_big_red_button(), GOUse_go_cage_door(), GOUse_go_celestial_access(), GOUse_go_containment_sphere(), GOUse_go_defias_cannon(), GOUse_go_gauntlet_gate(), GOUse_go_gundrak_altar(), GOUse_go_main_chambers_access_panel(), GOUse_go_nerubian_device(), GOUse_go_omen_cluster(), GOUse_go_prison_cell_lever(), GOUse_go_sapphiron_birth(), GOUse_go_service_gate(), GOUse_go_ssc_boss_consoles(), GOUse_go_stratholme_postbox(), npc_doomguard_punisherAI::HandleAttackDelay(), npc_shivan_assassinAI::HandleAttackDelay(), npc_eye_of_shartuulAI::HandleAttackDelay(), npc_dreadmawAI::HandleAttackDelay(), npc_shartuulAI::HandleFightSequence(), boss_magtheridonAI::HandlePhaseTransition(), npc_shadowfang_prisonerAI::HandleSpeech(), go_large_jack_o_lanternAI::JustDespawned(), npc_millhouse_manastormAI::JustDidDialogueStep(), boss_ambassador_flamelashAI::JustDied(), boss_broodlordAI::JustDied(), boss_chromaggusAI::JustDied(), boss_ebonrocAI::JustDied(), boss_firemawAI::JustDied(), boss_flamegorAI::JustDied(), boss_nefarianAI::JustDied(), boss_vaelastraszAI::JustDied(), boss_curatorAI::JustDied(), boss_maiden_of_virtueAI::JustDied(), boss_moroesAI::JustDied(), boss_netherspiteAI::JustDied(), boss_malchezaarAI::JustDied(), boss_terestianAI::JustDied(), boss_croneAI::JustDied(), boss_bigbadwolfAI::JustDied(), boss_julianneAI::JustDied(), boss_romuloAI::JustDied(), boss_felblood_kaelthasAI::JustDied(), boss_priestess_delrissaAI::JustDied(), boss_vexallusAI::JustDied(), boss_baron_geddonAI::JustDied(), boss_garrAI::JustDied(), boss_gehennasAI::JustDied(), boss_golemaggAI::JustDied(), boss_lucifronAI::JustDied(), boss_magmadarAI::JustDied(), boss_shazzrahAI::JustDied(), boss_sulfuronAI::JustDied(), mob_arugal_voidwalkerAI::JustDied(), boss_alythessAI::JustDied(), boss_sacrolashAI::JustDied(), boss_halazziAI::JustDied(), boss_janalaiAI::JustDied(), boss_jeklikAI::JustDied(), boss_mandokirAI::JustDied(), boss_marliAI::JustDied(), boss_thekalAI::JustDied(), boss_venoxisAI::JustDied(), npc_medivh_black_morassAI::JustDied(), boss_anetheronAI::JustDied(), boss_azgalorAI::JustDied(), boss_kazrogalAI::JustDied(), boss_rage_winterchillAI::JustDied(), boss_cthunAI::JustDied(), boss_fankrissAI::JustDied(), boss_huhuranAI::JustDied(), boss_ouroAI::JustDied(), boss_sarturaAI::JustDied(), boss_skeramAI::JustDied(), boss_viscidusAI::JustDied(), boss_amanitarAI::JustDied(), boss_volazjAI::JustDied(), boss_tharonjaAI::JustDied(), npc_blood_orb_controlAI::JustDied(), boss_lady_blaumeuxAI::JustDied(), boss_rivendare_naxxAI::JustDied(), boss_thane_korthazzAI::JustDied(), boss_sir_zeliekAI::JustDied(), boss_talon_king_ikissAI::JustDied(), boss_blackheart_the_inciterAI::JustDied(), boss_grandmaster_vorpilAI::JustDied(), boss_gurtogg_bloodboilAI::JustDied(), boss_supremusAI::JustDied(), mob_illidari_councilAI::JustDied(), boss_fathomlord_karathressAI::JustDied(), boss_leotheras_the_blindAI::JustDied(), boss_morogrim_tidewalkerAI::JustDied(), boss_the_lurker_belowAI::JustDied(), boss_thespiaAI::JustDied(), boss_mekgineer_steamriggerAI::JustDied(), boss_gruulAI::JustDied(), boss_high_king_maulgarAI::JustDied(), Council_Base_AI::JustDied(), boss_broggokAI::JustDied(), boss_the_makerAI::JustDied(), boss_vazruden_heraldAI::JustDied(), boss_vazrudenAI::JustDied(), boss_magtheridonAI::JustDied(), boss_grand_warlock_nethekurseAI::JustDied(), boss_warbringer_omroggAI::JustDied(), boss_warchief_kargath_bladefistAI::JustDied(), boss_dalliahAI::JustDied(), boss_harbinger_skyrissAI::JustDied(), boss_soccothratesAI::JustDied(), boss_alarAI::JustDied(), boss_high_astromancer_solarianAI::JustDied(), boss_kaelthasAI::JustDied(), boss_void_reaverAI::JustDied(), boss_nethermancer_sepethreaAI::JustDied(), boss_pathaleon_the_calculatorAI::JustDied(), npc_shade_of_the_horsemanAI::JustDied(), boss_silithidRoyaltyAI::JustDied(), npc_twilight_volunteerAI::JustDied(), npc_eye_of_shartuulAI::JustPreventedDeath(), npc_dreadmawAI::JustPreventedDeath(), boss_silithidRoyaltyAI::JustPreventedDeath(), npc_shartuulAI::JustPreventedDeath(), boss_ambassador_flamelashAI::JustReachedHome(), boss_broodlordAI::JustReachedHome(), boss_chromaggusAI::JustReachedHome(), boss_ebonrocAI::JustReachedHome(), boss_firemawAI::JustReachedHome(), boss_flamegorAI::JustReachedHome(), boss_vaelastraszAI::JustReachedHome(), boss_victor_nefariusAI::JustReachedHome(), boss_curatorAI::JustReachedHome(), boss_maiden_of_virtueAI::JustReachedHome(), boss_moroesAI::JustReachedHome(), boss_malchezaarAI::JustReachedHome(), boss_terestianAI::JustReachedHome(), boss_dorotheeAI::JustReachedHome(), boss_strawmanAI::JustReachedHome(), boss_tinheadAI::JustReachedHome(), boss_roarAI::JustReachedHome(), boss_croneAI::JustReachedHome(), boss_bigbadwolfAI::JustReachedHome(), boss_julianneAI::JustReachedHome(), boss_romuloAI::JustReachedHome(), boss_priestess_delrissaAI::JustReachedHome(), boss_vexallusAI::JustReachedHome(), boss_baron_geddonAI::JustReachedHome(), boss_garrAI::JustReachedHome(), boss_gehennasAI::JustReachedHome(), boss_golemaggAI::JustReachedHome(), boss_lucifronAI::JustReachedHome(), boss_magmadarAI::JustReachedHome(), boss_shazzrahAI::JustReachedHome(), boss_sulfuronAI::JustReachedHome(), boss_halazziAI::JustReachedHome(), boss_janalaiAI::JustReachedHome(), boss_jeklikAI::JustReachedHome(), boss_marliAI::JustReachedHome(), boss_thekalAI::JustReachedHome(), boss_venoxisAI::JustReachedHome(), boss_silithidRoyaltyAI::JustReachedHome(), boss_eye_of_cthunAI::JustReachedHome(), boss_cthunAI::JustReachedHome(), boss_fankrissAI::JustReachedHome(), boss_huhuranAI::JustReachedHome(), boss_ouroAI::JustReachedHome(), boss_sarturaAI::JustReachedHome(), boss_skeramAI::JustReachedHome(), boss_amanitarAI::JustReachedHome(), boss_volazjAI::JustReachedHome(), boss_tharonjaAI::JustReachedHome(), npc_blood_orb_controlAI::JustReachedHome(), boss_talon_king_ikissAI::JustReachedHome(), boss_blackheart_the_inciterAI::JustReachedHome(), boss_grandmaster_vorpilAI::JustReachedHome(), boss_gurtogg_bloodboilAI::JustReachedHome(), boss_supremusAI::JustReachedHome(), boss_illidari_councilAI::JustReachedHome(), boss_fathomlord_karathressAI::JustReachedHome(), boss_leotheras_the_blindAI::JustReachedHome(), boss_morogrim_tidewalkerAI::JustReachedHome(), boss_the_lurker_belowAI::JustReachedHome(), boss_thespiaAI::JustReachedHome(), boss_mekgineer_steamriggerAI::JustReachedHome(), boss_gruulAI::JustReachedHome(), boss_high_king_maulgarAI::JustReachedHome(), boss_the_makerAI::JustReachedHome(), boss_vazruden_heraldAI::JustReachedHome(), boss_vazrudenAI::JustReachedHome(), boss_magtheridonAI::JustReachedHome(), mob_hellfire_channelerAI::JustReachedHome(), boss_grand_warlock_nethekurseAI::JustReachedHome(), boss_warbringer_omroggAI::JustReachedHome(), boss_warchief_kargath_bladefistAI::JustReachedHome(), npc_doomguard_punisherAI::JustReachedHome(), npc_shivan_assassinAI::JustReachedHome(), npc_eye_of_shartuulAI::JustReachedHome(), npc_dreadmawAI::JustReachedHome(), npc_shartuulAI::JustReachedHome(), boss_harbinger_skyrissAI::JustReachedHome(), boss_alarAI::JustReachedHome(), boss_high_astromancer_solarianAI::JustReachedHome(), boss_kaelthasAI::JustReachedHome(), advisor_base_ai::JustReachedHome(), boss_void_reaverAI::JustReachedHome(), boss_nethermancer_sepethreaAI::JustReachedHome(), boss_pathaleon_the_calculatorAI::JustReachedHome(), npc_shade_of_the_horsemanAI::JustRespawned(), boss_vazruden_heraldAI::JustSummoned(), boss_tethyrAI::KilledUnit(), boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_kaelthasAI::MoveInLineOfSight(), npc_shattered_hands_zealotAI::MovementInform(), boss_vazruden_heraldAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_Shattered_Hand_Scout::MovementInform(), InsidiousWhisper::OnApply(), PossessionTransfer::OnApply(), boss_thekalAI::OnFakeingDeath(), mob_zealot_lorkhanAI::OnFakeingDeath(), mob_zealot_zathAI::OnFakeingDeath(), go_ai_larva_spewer::OnLootStateChange(), CreatureEventAI::ProcessAction(), ProcessEventId_event_ritual_of_power(), ProcessEventId_event_spell_summon_nightbane(), QuestRewarded_npc_aurius(), QuestRewarded_npc_rocknot(), mob_zealot_lorkhanAI::Reset(), mob_zealot_zathAI::Reset(), npc_warp_gate::SpellHit(), boss_volazjAI::SpellHitTarget(), npc_fire_cycloneAI::SpellHitTarget(), mob_ahnkahar_eggAI::SummonedCreatureJustDied(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_warp_gate::UpdateAI(), npc_grandmotherAI::UpdateAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), and npc_captured_sprite_darterAI::WaypointReached().
SetData64()
virtual void InstanceData::SetData64 (uint32 , uint64) inline virtual
Reimplemented in instance_serpentshrine_cavern, instance_shadow_labyrinth, instance_oculus, instance_ahnkahet, instance_forge_of_souls, instance_uldaman, instance_karazhan, and instance_blackwing_lair.
Definition at line 175 of file InstanceData.h.
Referenced by ScriptAction::ExecuteDbscriptCommand(), CreatureEventAI::ProcessAction(), SetGuid(), and boss_volazjAI::SpellHitTarget().
SetGuid()
void InstanceData::SetGuid (uint32 dataIdx, ObjectGuid value) inline
Definition at line 179 of file InstanceData.h.
References ObjectGuid::GetRawValue(), and SetData64().
Referenced by npc_corrupted_soul_fragmentAI::JustDied(), and npc_corrupted_soul_fragmentAI::MoveInLineOfSight().
ShowChatCommands()
virtual void InstanceData::ShowChatCommands (ChatHandler *) inline virtual
Reimplemented in world_map_outland, instance_mechanar, instance_blood_furnace, instance_serpentshrine_cavern, instance_violet_hold, instance_halls_of_stone, instance_icecrown_citadel, instance_trial_of_the_crusader, instance_mount_hyjal, instance_dark_portal, instance_zulaman, instance_sunwell_plateau, and instance_molten_core.
Definition at line 211 of file InstanceData.h.
Update()
virtual void InstanceData::Update (const uint32) inline virtual
Reimplemented in instance_temple_of_ahnqiraj, instance_ulduar, instance_pit_of_saron, instance_halls_of_reflection, world_map_kalimdor, world_map_eastern_kingdoms, world_map_outland, instance_mechanar, instance_arcatraz, instance_shattered_halls, instance_magtheridons_lair, instance_blood_furnace, instance_slave_pens, instance_sethekk_halls, instance_violet_hold, instance_pinnacle, instance_halls_of_stone, instance_ruby_sanctum, instance_eye_of_eternity, instance_naxxramas, instance_icecrown_citadel, instance_gundrak, instance_trial_of_the_crusader, instance_trial_of_the_champion, instance_azjol_nerub, instance_zulfarrak, instance_ruins_of_ahnqiraj, instance_maraudon, instance_dire_maul, instance_old_hillsbrad, instance_mount_hyjal, instance_dark_portal, instance_culling_of_stratholme, instance_blackfathom_deeps, instance_zulaman, instance_uldaman, instance_sunwell_plateau, instance_sunken_temple, instance_stratholme, instance_shadowfang_keep, instance_scholomance, world_map_ebon_hold, instance_karazhan, instance_deadmines, instance_blackwing_lair, instance_blackrock_spire, and instance_blackrock_depths.
Definition at line 126 of file InstanceData.h.
Referenced by Map::Update().
Field Documentation
instance
Map* InstanceData::instance
Definition at line 112 of file InstanceData.h.
Referenced by instance_halls_of_stone::ActivateFace(), npc_amanishi_scoutAI::Aggro(), boss_ossirianAI::Aggro(), boss_skeramAI::Aggro(), boss_sjonnirAI::Aggro(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_shattered_halls(), ScriptedInstance::BanPlayersIfNoGm(), BrewfestEvent::BrewfestEvent(), instance_blackrock_depths::CanReplacePrincess(), instance_zulaman::ChangeWeather(), CheckAchievementCriteriaMeet(), CheckConditionCriteriaMeet(), instance_blackwing_lair::CleanupNefarianStage(), instance_wailing_caverns::DespawnAll(), instance_mount_hyjal::DespawnBase(), world_map_outland::DespawnBashir(), ScriptedInstance::DespawnGuids(), instance_black_temple::DespawnImpalingSpines(), boss_kelthuzadAI::DespawnIntroCreatures(), instance_mount_hyjal::DespawnOverrun(), instance_mount_hyjal::DespawnWaveSpawns(), instance_gundrak::DoAltarVisualEffect(), instance_shattered_halls::DoBeginArcherAttack(), instance_ulduar::DoCallLeviathanHelp(), instance_shattered_halls::DoCastGroupDebuff(), instance_zulaman::DoChestEvent(), instance_culling_of_stratholme::DoChromieWhisper(), instance_trial_of_the_champion::DoCleanupArenaOnWipe(), instance_trial_of_the_crusader::DoCleanupCrusaders(), instance_halls_of_reflection::DoCleanupFrostmourneEvent(), world_map_ebon_hold::DoClearBattleScene(), instance_violet_hold::DoClearBossMobs(), world_map_ebon_hold::DoDefeatUndeadArmy(), world_map_kalimdor::DoDespawnElementalRifts(), instance_sunwell_plateau::DoEjectSpectralPlayers(), instance_karazhan::DoFailChessEvent(), instance_karazhan::DoFinishChessEvent(), instance_draktharon_keep::DoHandleCrystal(), npc_thrall_old_hillsbradAI::DoHandleQuestCredit(), instance_shattered_halls::DoInitialGets(), instance_stratholme::DoMoveBackDefenders(), instance_karazhan::DoMoveChessPieceToSides(), instance_blood_furnace::DoNextBroggokEventPhase(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), instance_karazhan::DoPrepareChessEvent(), boss_skadiAI::DoPrepareForGauntlet(), instance_blackrock_spire::DoProcessEmberseerEvent(), instance_violet_hold::DoReleaseBoss(), world_map_ebon_hold::DoResetBattleScene(), instance_uldaman::DoResetKeeperEvent(), instance_scholomance::DoRespawnEntranceRoom(), ScriptedInstance::DoRespawnGameObject(), instance_trial_of_the_champion::DoSendChampionsToExit(), instance_trial_of_the_champion::DoSendNextArenaWave(), instance_ruins_of_ahnqiraj::DoSendNextArmyWave(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), instance_trial_of_the_champion::DoSetChamptionsInCombat(), instance_trial_of_the_crusader::DoSetCrusadersInCombat(), boss_kelidan_the_breakerAI::DoSetupAdds(), instance_culling_of_stratholme::DoSetupEntranceSoldiers(), instance_blood_furnace::DoSortBroggokOrcs(), instance_sunwell_plateau::DoSortFlightTriggers(), instance_draktharon_keep::DoSortNovosDummies(), instance_blackrock_spire::DoSortRoomEventMobs(), instance_stratholme::DoSortZiggurats(), instance_ulduar::DoSpawnHodirNpcs(), instance_violet_hold::DoSpawnIntroMob(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), ScriptedInstance::DoStartTimedAchievement(), instance_shattered_halls::DoSummonInitialWave(), instance_shattered_halls::DoSummonSHZealot(), ScriptedInstance::DoToggleGameObjectFlags(), instance_naxxramas::DoTriggerHeiganTraps(), world_map_ebon_hold::DoUpdateBattleWeatherData(), world_map_ebon_hold::DoUpdateBattleWorldState(), world_map_ebon_hold::DoUpdateBattleZoneLightData(), ScriptedInstance::DoUpdateWorldState(), instance_culling_of_stratholme::DoUpdateZombieResidents(), ScriptedInstance::DoUseDoorOrButton(), instance_blackrock_spire::DoUseEmberseerRunes(), instance_sunwell_plateau::DropFog(), instance_serpentshrine_cavern::EngageBossConsole(), instance_serpentshrine_cavern::EngageBridgeConsole(), boss_sjonnirAI::ExecuteAction(), instance_halls_of_reflection::ExecuteChatCommand(), instance_icecrown_citadel::ExecuteChatCommand(), instance_mount_hyjal::FailEvent(), instance_shattered_halls::FailGauntlet(), instance_sunwell_plateau::FailKiljaeden(), instance_sethekk_halls::FinishAnzuIntro(), world_map_outland::FinishPhase(), instance_uldaman::GetClosestDwarfNotInCombat(), instance_culling_of_stratholme::GetCratesBunnyOrderedList(), world_map_outland::GetCurrentPlayer(), instance_draktharon_keep::GetNextCrystalTarget(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), instance_draktharon_keep::GetSummonDummy(), world_map_kalimdor::GhostOPlasmEventStep(), instance_blackrock_depths::HandleBarPatrol(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirEnemyAttack(), instance_scholomance::HandleDawnGambitEvent(), instance_ahnkahet::HandleInsanityClear(), instance_ahnkahet::HandleInsanitySwitch(), boss_gothikAI::HandleOpenGates(), world_map_outland::HandleShartuulAddAttack(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulEventReset(), world_map_outland::HandleShartuulSpawnSequence(), boss_gothikAI::HasPlayersInLeftSide(), instance_sunwell_plateau::ImpYell(), instance_trial_of_the_champion::InformChampionReachHome(), instance_uldaman::Initialize(), instance_zulaman::Initialize(), instance_mount_hyjal::Initialize(), world_map_kalimdor::Initialize(), world_map_outland::Initialize(), instance_trial_of_the_crusader::Is25ManDifficulty(), instance_icecrown_citadel::Is25ManDifficulty(), instance_ruby_sanctum::Is25ManDifficulty(), instance_trial_of_the_champion::IsArenaChallengeComplete(), world_map_northrend::IsDalaranCooldownForPlayer(), instance_trial_of_the_crusader::IsHeroicDifficulty(), instance_icecrown_citadel::IsHeroicDifficulty(), instance_ruby_sanctum::IsHeroicDifficulty(), instance_trial_of_the_crusader::JustDidDialogueStep(), instance_icecrown_citadel::JustDidDialogueStep(), boss_sjonnirAI::JustDied(), npc_graufAI::JustDied(), boss_alarAI::JustDied(), boss_sjonnirAI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), instance_trial_of_the_champion::MoveChampionToHome(), npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), world_map_outland::OnCreatureCreate(), instance_mount_hyjal::OnCreatureCreate(), instance_underbog::OnCreatureDeath(), instance_sunwell_plateau::OnCreatureDeath(), instance_mount_hyjal::OnCreatureDeath(), world_map_kalimdor::OnCreatureDeath(), instance_ahnkahet::OnCreatureDeath(), instance_eye_of_eternity::OnCreatureDeath(), instance_gundrak::OnCreatureEnterCombat(), instance_zulaman::OnCreatureEvade(), instance_uldaman::OnCreatureGroupDespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_gundrak::OnObjectCreate(), instance_blackrock_depths::OnPlayerEnter(), instance_scarlet_monastery::OnPlayerEnter(), instance_shadowfang_keep::OnPlayerEnter(), instance_slave_pens::OnPlayerEnter(), instance_blood_furnace::OnPlayerEnter(), instance_halls_of_stone::OnPlayerEnter(), instance_ulduar::OnPlayerEnter(), instance_shattered_halls::OnPlayerEnter(), instance_dire_maul::ProcessDreadsteedRitualStart(), ProcessEventId_event_boss_hodir(), instance_forge_of_souls::ProcessEventNpcs(), instance_halls_of_stone::ProcessFaceSpell(), instance_halls_of_stone::ProcessFaceSummon(), instance_dire_maul::ProcessForceFieldOpening(), world_map_outland::ProgressShartuul(), npc_amanishi_scoutAI::ReceiveAIEvent(), instance_violet_hold::ResetEvent(), instance_halls_of_stone::ResetFace(), instance_sunwell_plateau::ResetGauntlet(), instance_violet_hold::ResetGuards(), instance_azjol_nerub::ResetHadronoxTriggers(), instance_violet_hold::ResetIntroPortals(), instance_black_temple::RespawnChannelers(), ScriptedInstance::RespawnDbGuids(), instance_mount_hyjal::RetreatBase(), SaveToDB(), world_map_outland::ScriptAction(), instance_zulgurub::SelectRandomPantherTrigger(), SendEncounterFrame(), instance_zulaman::SendNextBearWave(), world_map_northrend::SetDalaranCooldownTime(), instance_shadowfang_keep::SetData(), instance_stratholme::SetData(), instance_zulgurub::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), world_map_outland::SetData(), world_map_kalimdor::SetData(), instance_blackrock_depths::SetData(), instance_blackrock_spire::SetData(), instance_blackwing_lair::SetData(), instance_gnomeregan::SetData(), instance_karazhan::SetData(), instance_magisters_terrace::SetData(), world_map_ebon_hold::SetData(), instance_scarlet_monastery::SetData(), instance_sunken_temple::SetData(), instance_sunwell_plateau::SetData(), instance_zulaman::SetData(), instance_culling_of_stratholme::SetData(), instance_mount_hyjal::SetData(), instance_old_hillsbrad::SetData(), instance_dire_maul::SetData(), instance_onyxias_lair::SetData(), instance_ruins_of_ahnqiraj::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_ahnkahet::SetData(), instance_trial_of_the_champion::SetData(), instance_draktharon_keep::SetData(), instance_gundrak::SetData(), instance_forge_of_souls::SetData(), instance_halls_of_reflection::SetData(), instance_pit_of_saron::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_eye_of_eternity::SetData(), instance_oculus::SetData(), instance_ruby_sanctum::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_pinnacle::SetData(), instance_serpentshrine_cavern::SetData(), instance_steam_vault::SetData(), instance_ramparts::SetData(), instance_magtheridons_lair::SetData(), instance_shattered_halls::SetData(), instance_arcatraz::SetData(), instance_mechanar::SetData(), instance_blackwing_lair::SetData64(), instance_ahnkahet::SetData64(), instance_halls_of_stone::SortFaces(), instance_dire_maul::SortPylonGuards(), instance_mount_hyjal::SpawnBase(), instance_sunwell_plateau::SpawnFelmyst(), instance_deadmines::SpawnFirstDeadminesPatrol(), instance_serpentshrine_cavern::SpawnFishCorpses(), instance_sunwell_plateau::SpawnGauntlet(), instance_mount_hyjal::SpawnInfernal(), instance_sunwell_plateau::SpawnKiljaeden(), instance_zulaman::SpawnMalacrass(), instance_deadmines::SpawnSecondDeadminesPatrol(), instance_deadmines::SpawnThirdDeadminesPatrol(), instance_sunwell_plateau::SpawnTwins(), instance_mount_hyjal::SpawnWave(), instance_magisters_terrace::StartCrystalVisual(), instance_sunwell_plateau::StartImps(), world_map_outland::StartManaSlaveEvent(), instance_sunwell_plateau::StartMiniEvent(), DialogueHelper::StartNextDialogueText(), instance_dark_portal::StartPostEvent(), instance_sunwell_plateau::StopImps(), instance_stratholme::ThazudinAcolyteJustDied(), instance_blackwing_lair::Update(), instance_karazhan::Update(), world_map_ebon_hold::Update(), instance_shadowfang_keep::Update(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_sunwell_plateau::Update(), instance_uldaman::Update(), instance_dire_maul::Update(), instance_zulfarrak::Update(), instance_azjol_nerub::Update(), instance_trial_of_the_champion::Update(), instance_eye_of_eternity::Update(), instance_halls_of_stone::Update(), instance_pinnacle::Update(), instance_slave_pens::Update(), instance_blood_furnace::Update(), instance_shattered_halls::Update(), instance_mechanar::Update(), instance_halls_of_reflection::Update(), instance_pit_of_saron::Update(), instance_ulduar::Update(), npc_putricides_trapAI::UpdateAI(), instance_violet_hold::UpdateCellForBoss(), and instance_old_hillsbrad::UpdateLodgeQuestCredit().
The documentation for this class was generated from the following files:
InstanceData.h
InstanceData.cpp