CMaNGOS_WoTLK: VMAP::TileAssembler Class Reference
VMAP::TileAssembler Class Reference
#include <TileAssembler.h>
Public Member Functions
TileAssembler (const std::string &pSrcDirName, const std::string &pDestDirName)
virtual ~TileAssembler ()
bool convertWorld2 ()
bool readMapSpawns ()
bool calculateTransformedBound (ModelSpawn &spawn)
void exportGameobjectModels ()
bool convertRawFile (const std::string &pModelFilename)
Private Attributes
std::string iDestDir
std::string iSrcDir
MapData mapData
std::set< std::string > spawnedModelFiles
Detailed Description
Definition at line 91 of file TileAssembler.h.
Constructor & Destructor Documentation
TileAssembler()
VMAP::TileAssembler::TileAssembler (const std::string & pSrcDirName, const std::string & pDestDirName)
Definition at line 55 of file TileAssembler.cpp.
References iDestDir, and iSrcDir.
~TileAssembler()
VMAP::TileAssembler::~TileAssembler () virtual
Definition at line 63 of file TileAssembler.cpp.
Member Function Documentation
calculateTransformedBound()
bool VMAP::TileAssembler::calculateTransformedBound (ModelSpawn & spawn)
Definition at line 246 of file TileAssembler.cpp.
References VMAP::ModelSpawn::flags, VMAP::WorldModel_Raw::groupsArray, VMAP::ModelSpawn::iBound, VMAP::ModelPosition::iDir, VMAP::ModelPosition::init(), VMAP::ModelSpawn::iPos, VMAP::ModelSpawn::iRot, VMAP::ModelSpawn::iScale, VMAP::ModelPosition::iScale, iSrcDir, VMAP::MOD_HAS_BOUND, VMAP::ModelSpawn::name, VMAP::WorldModel_Raw::Read(), and VMAP::ModelPosition::transform().
Referenced by convertWorld2().
convertRawFile()
bool VMAP::TileAssembler::convertRawFile (const std::string & pModelFilename)
Definition at line 298 of file TileAssembler.cpp.
References VMAP::GroupModel_Raw::bounds, VMAP::WorldModel_Raw::groupsArray, VMAP::GroupModel_Raw::GroupWMOID, iDestDir, iSrcDir, VMAP::GroupModel_Raw::liquid, VMAP::GroupModel_Raw::mogpflags, VMAP::WorldModel_Raw::Read(), VMAP::WorldModel_Raw::RootWMOID, VMAP::WorldModel::setGroupModels(), VMAP::WorldModel::setRootWmoID(), VMAP::GroupModel_Raw::triangles, VMAP::GroupModel_Raw::vertexArray, and VMAP::WorldModel::writeFile().
Referenced by convertWorld2().
convertWorld2()
bool VMAP::TileAssembler::convertWorld2 ()
Definition at line 68 of file TileAssembler.cpp.
References BIH::build(), calculateTransformedBound(), convertRawFile(), exportGameobjectModels(), VMAP::ModelSpawn::flags, VMAP::ModelSpawn::ID, iDestDir, mapData, VMAP::MOD_M2, VMAP::MOD_WORLDSPAWN, VMAP::StaticMapTree::packTileID(), readMapSpawns(), spawnedModelFiles, VMAP::StaticMapTree::unpackTileID(), VMAP::VMAP_MAGIC, BIH::writeToFile(), and VMAP::ModelSpawn::writeToFile().
exportGameobjectModels()
void VMAP::TileAssembler::exportGameobjectModels ()
Definition at line 332 of file TileAssembler.cpp.
References VMAP::GAMEOBJECT_MODELS, VMAP::WorldModel_Raw::groupsArray, iDestDir, iSrcDir, VMAP::WorldModel_Raw::Read(), and spawnedModelFiles.
Referenced by convertWorld2().
readMapSpawns()
bool VMAP::TileAssembler::readMapSpawns ()
Definition at line 207 of file TileAssembler.cpp.
References VMAP::ModelSpawn::ID, iSrcDir, mapData, VMAP::StaticMapTree::packTileID(), VMAP::ModelSpawn::readFromFile(), VMAP::MapSpawns::TileEntries, and VMAP::MapSpawns::UniqueEntries.
Referenced by convertWorld2().
Field Documentation
iDestDir
std::string VMAP::TileAssembler::iDestDir private
Definition at line 94 of file TileAssembler.h.
Referenced by convertRawFile(), convertWorld2(), exportGameobjectModels(), and TileAssembler().
iSrcDir
std::string VMAP::TileAssembler::iSrcDir private
Definition at line 95 of file TileAssembler.h.
Referenced by calculateTransformedBound(), convertRawFile(), exportGameobjectModels(), readMapSpawns(), and TileAssembler().
mapData
MapData VMAP::TileAssembler::mapData private
Definition at line 96 of file TileAssembler.h.
Referenced by convertWorld2(), and readMapSpawns().
spawnedModelFiles
std::set<std::string> VMAP::TileAssembler::spawnedModelFiles private
Definition at line 97 of file TileAssembler.h.
Referenced by convertWorld2(), and exportGameobjectModels().
The documentation for this class was generated from the following files:
TileAssembler.h
TileAssembler.cpp