CMaNGOS_WoTLK: TaxiMovementGenerator Class Reference
TaxiMovementGenerator Class Reference
#include <PathMovementGenerator.h>
Public Member Functions
TaxiMovementGenerator ()
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
bool Update (Unit &unit, const uint32 &diff) override
MovementGeneratorType GetMovementGeneratorType () const override
bool Resume (Unit &unit)
Public Member Functions inherited from AbstractPathMovementGenerator
AbstractPathMovementGenerator (const Movement::PointsArray &path, float orientation=0, int32 offset=0)
AbstractPathMovementGenerator (const WaypointPath *path, int32 offset=0, bool cyclic=false, ObjectGuid guid=ObjectGuid())
void Reset (Unit &owner) override
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual bool Move (Unit &unit)
Protected Member Functions inherited from AbstractPathMovementGenerator
virtual void MovementInform (Unit &unit)
Additional Inherited Members
Protected Attributes inherited from AbstractPathMovementGenerator
WaypointPath m_path
int32 m_pathIndex
Movement::PointsArray m_spline
float m_orientation
ShortTimeTracker m_timer
bool m_cyclic
bool m_firstCycle
uint32 m_startPoint
ObjectGuid m_guid
Detailed Description
Definition at line 89 of file PathMovementGenerator.h.
Constructor & Destructor Documentation
TaxiMovementGenerator()
TaxiMovementGenerator::TaxiMovementGenerator () inline explicit
Definition at line 92 of file PathMovementGenerator.h.
Member Function Documentation
Finalize()
void TaxiMovementGenerator::Finalize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 333 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Finalize(), Unit::GetClientControlling(), Object::GetTypeId(), PLAYER_FLAGS, PLAYER_FLAGS_TAXI_BENCHMARK, Object::RemoveFlag(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_CLIENT_CONTROL_LOST, UNIT_FLAG_TAXI_FLIGHT, and UNIT_STAT_TAXI_FLIGHT.
GetMovementGeneratorType()
MovementGeneratorType TaxiMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Definition at line 100 of file PathMovementGenerator.h.
References TAXI_MOTION_TYPE.
Initialize()
void TaxiMovementGenerator::Initialize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 321 of file PathMovementGenerator.cpp.
References Unit::addUnitState(), Unit::GetClientControlling(), AbstractPathMovementGenerator::Initialize(), Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_CLIENT_CONTROL_LOST, UNIT_FLAG_TAXI_FLIGHT, and UNIT_STAT_TAXI_FLIGHT.
Interrupt()
void TaxiMovementGenerator::Interrupt (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 348 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Interrupt(), and UNIT_STAT_TAXI_FLIGHT.
Move()
bool TaxiMovementGenerator::Move (Unit & unit) protected virtual
Definition at line 376 of file PathMovementGenerator.cpp.
References Movement::MoveSplineInit::Launch(), AbstractPathMovementGenerator::m_pathIndex, AbstractPathMovementGenerator::m_spline, Movement::MoveSplineInit::Path(), Movement::MoveSplineInit::SetFirstPointId(), Movement::MoveSplineInit::SetFly(), Movement::MoveSplineInit::SetVelocity(), and TAXI_FLIGHT_SPEED.
Referenced by Resume().
Resume()
bool TaxiMovementGenerator::Resume (Unit & unit)
Definition at line 387 of file PathMovementGenerator.cpp.
References Unit::GetMountID(), Player::GetTaxiPathSpline(), Player::GetTaxiPathSplineOffset(), Object::GetTypeId(), AbstractPathMovementGenerator::m_path, AbstractPathMovementGenerator::m_pathIndex, AbstractPathMovementGenerator::m_spline, Move(), Player::OnTaxiFlightSplineEnd(), Player::OnTaxiFlightSplineUpdate(), and TYPEID_PLAYER.
Referenced by Update().
Update()
bool TaxiMovementGenerator::Update (Unit & unit, const uint32 & diff) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 354 of file PathMovementGenerator.cpp.
References Movement::MoveSpline::currentPathIdx(), Movement::MoveSpline::Finalized(), Object::GetTypeId(), Unit::movespline, Player::OnTaxiFlightEject(), Player::OnTaxiFlightUpdate(), Resume(), TYPEID_PLAYER, and AbstractPathMovementGenerator::Update().
The documentation for this class was generated from the following files:
PathMovementGenerator.h
PathMovementGenerator.cpp