CMaNGOS_WoTLK: PackedGuid Class Reference
PackedGuid Class Reference
#include <ObjectGuid.h>
Public Member Functions
PackedGuid ()
PackedGuid (uint64 const &guid)
PackedGuid (ObjectGuid const &guid)
void Set (uint64 const &guid)
void Set (ObjectGuid const &guid)
size_t size () const
Private Attributes
ByteBuffer m_packedGuid
Friends
ByteBuffer & operator<< (ByteBuffer &buf, PackedGuid const &guid)
Detailed Description
Definition at line 216 of file ObjectGuid.h.
Constructor & Destructor Documentation
PackedGuid() [1/3]
PackedGuid::PackedGuid () inline explicit
Definition at line 221 of file ObjectGuid.h.
References ByteBuffer::appendPackGUID(), and m_packedGuid.
PackedGuid() [2/3]
PackedGuid::PackedGuid (uint64 const & guid) inline explicit
Definition at line 222 of file ObjectGuid.h.
References ByteBuffer::appendPackGUID(), and m_packedGuid.
PackedGuid() [3/3]
PackedGuid::PackedGuid (ObjectGuid const & guid) inline explicit
Definition at line 223 of file ObjectGuid.h.
References ByteBuffer::appendPackGUID(), ObjectGuid::GetRawValue(), and m_packedGuid.
Member Function Documentation
Set() [1/2]
void PackedGuid::Set (ObjectGuid const & guid) inline
Definition at line 227 of file ObjectGuid.h.
References ByteBuffer::appendPackGUID(), ObjectGuid::GetRawValue(), m_packedGuid, and ByteBuffer::wpos().
Set() [2/2]
void PackedGuid::Set (uint64 const & guid) inline
Definition at line 226 of file ObjectGuid.h.
References ByteBuffer::appendPackGUID(), m_packedGuid, and ByteBuffer::wpos().
Referenced by Object::_Create().
size()
size_t PackedGuid::size () const inline
Definition at line 230 of file ObjectGuid.h.
References m_packedGuid, and ByteBuffer::size().
Referenced by Unit::AddComboPoints(), VehicleInfo::Board(), Player::SendAutoRepeatCancel(), Player::SendComboPoints(), Unit::SendMoveRoot(), and Player::UpdateClientControl().
Friends And Related Function Documentation
operator<<
ByteBuffer& operator<< (ByteBuffer & buf, PackedGuid const & guid) friend
Definition at line 89 of file ObjectGuid.cpp.
Field Documentation
m_packedGuid
ByteBuffer PackedGuid::m_packedGuid private
Definition at line 233 of file ObjectGuid.h.
Referenced by PackedGuid(), Set(), and size().
The documentation for this class was generated from the following file:
ObjectGuid.h