CMaNGOS_WoTLK: MaNGOS::NearestGameObjectEntryInObjectRangeCheck Class Reference
MaNGOS::NearestGameObjectEntryInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestGameObjectEntryInObjectRangeCheck (WorldObject const &obj, uint32 entry, float range)
WorldObject const & GetFocusObject () const
bool operator() (GameObject *go)
float GetLastRange () const
Private Member Functions
NearestGameObjectEntryInObjectRangeCheck (NearestGameObjectEntryInObjectRangeCheck const &)
Private Attributes
WorldObject const & i_obj
uint32 i_entry
float i_range
Detailed Description
Definition at line 745 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestGameObjectEntryInObjectRangeCheck() [1/2]
MaNGOS::NearestGameObjectEntryInObjectRangeCheck::NearestGameObjectEntryInObjectRangeCheck (WorldObject const & obj, uint32 entry, float range) inline
Definition at line 748 of file GridNotifiers.h.
NearestGameObjectEntryInObjectRangeCheck() [2/2]
MaNGOS::NearestGameObjectEntryInObjectRangeCheck::NearestGameObjectEntryInObjectRangeCheck (NearestGameObjectEntryInObjectRangeCheck const &) private
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::NearestGameObjectEntryInObjectRangeCheck::GetFocusObject () const inline
Definition at line 749 of file GridNotifiers.h.
References i_obj.
GetLastRange()
float MaNGOS::NearestGameObjectEntryInObjectRangeCheck::GetLastRange () const inline
Definition at line 759 of file GridNotifiers.h.
References i_range.
operator()()
bool MaNGOS::NearestGameObjectEntryInObjectRangeCheck::operator() (GameObject * go) inline
Definition at line 750 of file GridNotifiers.h.
References WorldObject::GetDistance(), Object::GetEntry(), i_entry, i_obj, i_range, and WorldObject::IsWithinDistInMap().
Field Documentation
i_entry
uint32 MaNGOS::NearestGameObjectEntryInObjectRangeCheck::i_entry private
Definition at line 762 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const& MaNGOS::NearestGameObjectEntryInObjectRangeCheck::i_obj private
Definition at line 761 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::NearestGameObjectEntryInObjectRangeCheck::i_range private
Definition at line 763 of file GridNotifiers.h.
Referenced by GetLastRange(), and operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h