CMaNGOS_WoTLK: AccountMgr Class Reference
AccountMgr Class Reference
#include <AccountMgr.h>
Public Member Functions
AccountMgr ()
~AccountMgr ()
AccountOpResult CreateAccount (std::string username, std::string password) const
AccountOpResult CreateAccount (std::string username, std::string password, uint32 expansion) const
AccountOpResult DeleteAccount (uint32 accid) const
AccountOpResult ChangeUsername (uint32 accid, std::string new_uname, std::string new_passwd) const
AccountOpResult ChangePassword (uint32 accid, std::string new_passwd) const
bool CheckPassword (uint32 accid, std::string passwd) const
uint32 GetId (std::string username) const
bool GetName (uint32 acc_id, std::string &name) const
uint32 GetCharactersCount (uint32 acc_id) const
std::string CalculateShaPassHash (std::string &name, std::string &password) const
uint32 GetFlags (uint32 acc_id) const
Static Public Member Functions
static AccountTypes GetSecurity (uint32 acc_id)
static bool normalizeString (std::string &utf8str)
Detailed Description
Definition at line 36 of file AccountMgr.h.
Constructor & Destructor Documentation
AccountMgr()
AccountMgr::AccountMgr ()
Definition at line 33 of file AccountMgr.cpp.
~AccountMgr()
AccountMgr::~AccountMgr ()
Definition at line 36 of file AccountMgr.cpp.
Member Function Documentation
CalculateShaPassHash()
std::string AccountMgr::CalculateShaPassHash (std::string & name, std::string & password) const
Definition at line 317 of file AccountMgr.cpp.
References CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength(), hexEncodeByteArray(), CryptoHash< Algorithm, DigestSize >::Initialize(), and CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by ChangePassword(), ChangeUsername(), CheckPassword(), and CreateAccount().
ChangePassword()
AccountOpResult AccountMgr::ChangePassword (uint32 accid, std::string new_passwd) const
Definition at line 188 of file AccountMgr.cpp.
References AOR_DB_INTERNAL_ERROR, AOR_NAME_NOT_EXIST, AOR_OK, AOR_PASS_TOO_LONG, BigNumber::AsHexStr(), CalculateShaPassHash(), SRP6::CalculateVerifier(), GetName(), SRP6::GetSalt(), SRP6::GetVerifier(), LoginDatabase, MAX_ACCOUNT_STR, normalizeString(), Database::PExecute(), and utf8length().
ChangeUsername()
AccountOpResult AccountMgr::ChangeUsername (uint32 accid, std::string new_uname, std::string new_passwd) const
Definition at line 149 of file AccountMgr.cpp.
References AOR_DB_INTERNAL_ERROR, AOR_NAME_NOT_EXIST, AOR_NAME_TOO_LONG, AOR_OK, AOR_PASS_TOO_LONG, BigNumber::AsHexStr(), CalculateShaPassHash(), SRP6::CalculateVerifier(), Database::escape_string(), SRP6::GetSalt(), SRP6::GetVerifier(), LoginDatabase, MAX_ACCOUNT_STR, normalizeString(), Database::PExecute(), Database::PQuery(), and utf8length().
CheckPassword()
bool AccountMgr::CheckPassword (uint32 accid, std::string passwd) const
Definition at line 273 of file AccountMgr.cpp.
References CalculateShaPassHash(), SRP6::CalculateVerifier(), QueryResult::Fetch(), Field::GetCppString(), GetName(), LoginDatabase, normalizeString(), Database::PQuery(), and SRP6::ProofVerifier().
CreateAccount() [1/2]
AccountOpResult AccountMgr::CreateAccount (std::string username, std::string password) const
Definition at line 39 of file AccountMgr.cpp.
References AOR_DB_INTERNAL_ERROR, AOR_NAME_ALREADY_EXIST, AOR_NAME_TOO_LONG, AOR_OK, BigNumber::AsHexStr(), CalculateShaPassHash(), SRP6::CalculateVerifier(), Database::Execute(), GetId(), SRP6::GetSalt(), SRP6::GetVerifier(), LoginDatabase, MAX_ACCOUNT_STR, normalizeString(), Database::PExecute(), and utf8length().
CreateAccount() [2/2]
AccountOpResult AccountMgr::CreateAccount (std::string username, std::string password, uint32 expansion) const
Definition at line 73 of file AccountMgr.cpp.
References AOR_DB_INTERNAL_ERROR, AOR_NAME_ALREADY_EXIST, AOR_NAME_TOO_LONG, AOR_OK, BigNumber::AsHexStr(), CalculateShaPassHash(), SRP6::CalculateVerifier(), Database::Execute(), GetId(), SRP6::GetSalt(), SRP6::GetVerifier(), LoginDatabase, MAX_ACCOUNT_STR, normalizeString(), Database::PExecute(), and utf8length().
DeleteAccount()
AccountOpResult AccountMgr::DeleteAccount (uint32 accid) const
Definition at line 106 of file AccountMgr.cpp.
References AOR_DB_INTERNAL_ERROR, AOR_NAME_NOT_EXIST, AOR_OK, Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Player::DeleteFromDB(), QueryResult::Fetch(), Field::GetUInt32(), HIGHGUID_PLAYER, ObjectAccessor::KickPlayer(), LoginDatabase, QueryResult::NextRow(), Database::PExecute(), and Database::PQuery().
GetCharactersCount()
uint32 AccountMgr::GetCharactersCount (uint32 acc_id) const
Definition at line 259 of file AccountMgr.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetUInt32(), and Database::PQuery().
GetFlags()
uint32 AccountMgr::GetFlags (uint32 acc_id) const
Definition at line 332 of file AccountMgr.cpp.
References LoginDatabase, and Database::PQuery().
GetId()
uint32 AccountMgr::GetId (std::string username) const
Definition at line 222 of file AccountMgr.cpp.
References Database::escape_string(), LoginDatabase, and Database::PQuery().
Referenced by CreateAccount().
GetName()
bool AccountMgr::GetName (uint32 acc_id, std::string & name) const
Definition at line 246 of file AccountMgr.cpp.
References LoginDatabase, and Database::PQuery().
Referenced by ChangePassword(), and CheckPassword().
GetSecurity()
AccountTypes AccountMgr::GetSecurity (uint32 acc_id) static
Definition at line 233 of file AccountMgr.cpp.
References LoginDatabase, Database::PQuery(), and SEC_PLAYER.
normalizeString()
bool AccountMgr::normalizeString (std::string & utf8str) static
Definition at line 303 of file AccountMgr.cpp.
References MAX_ACCOUNT_STR, Utf8toWStr(), wcharToUpperOnlyLatin(), and WStrToUtf8().
Referenced by ChangePassword(), ChangeUsername(), CheckPassword(), CreateAccount(), ChatHandler::ExtractAccountId(), ChatHandler::HandleBanHelper(), ChatHandler::HandleLookupAccountNameCommand(), ChatHandler::HandleLookupPlayerAccountCommand(), and ChatHandler::HandleUnBanHelper().
The documentation for this class was generated from the following files:
AccountMgr.h
AccountMgr.cpp