CMaNGOS_WoTLK: NamreebAnticheat::SessionAnticheat Class Reference
NamreebAnticheat::SessionAnticheat Class Reference final
#include <libanticheat.hpp>
Public Member Functions
SessionAnticheat (WorldSession *session, const BigNumber &K)
virtual void Update (uint32 diff)
virtual bool IsSilenced () const
virtual void SendCharEnum (WorldPacket &&packet)
virtual void NewPlayer ()
virtual void LeaveWorld ()
virtual void Disconnect ()
virtual bool ReadAddonInfo (WorldPacket *, WorldPacket &)
virtual void SendPlayerInfo (ChatHandler *) const
virtual void RecordCheat (uint32 actionMask, const char *detector, const char *format,...)
virtual bool Movement (MovementInfo &mi, const WorldPacket &packet)
virtual void TimeSkipped (const ObjectGuid &mover, uint32 ms)
virtual bool ExtrapolateMovement (MovementInfo const &mi, uint32 diffMs, Position &pos)
virtual bool SpeedChangeAck (MovementInfo &mi, const WorldPacket &packet, float newSpeed)
virtual bool IsInKnockBack () const
virtual void KnockBack (float speedxy, float speedz, float cos, float sin)
virtual void OnExplore (const AreaTableEntry *p)
virtual void Teleport (const Position &pos)
virtual void OrderSent (uint16 opcode, uint32 counter)
virtual void OrderAck (uint16 opcode, uint32 counter)
virtual void WardenPacket (WorldPacket &packet)
virtual void AutoReply (const std::string &msg)
virtual void Whisper (const std::string &msg, const ObjectGuid &to)
virtual void Say (const std::string &msg)
virtual void Yell (const std::string &msg)
virtual void Channel (const std::string &msg)
virtual void Mail (const std::string &subject, const std::string &body, const ObjectGuid &to)
virtual void ChannelInvite (const std::string &channelName, const ObjectGuid &to) override
virtual void PartyInvite (const ObjectGuid &to)
~SessionAnticheat ()
void SendCheatInfo (ChatHandler *handler) const
void SendSpamInfo (ChatHandler *handler) const
float GetDistanceTraveled () const
bool GetMovementSpeeds (float *speeds) const
bool VerifyTracking (uint16 unitTracking, uint16 resourceTracking) const
void VerifyMovementFlags (uint32 flags, uint32 &removeFlags, bool strict) const
void RecordCheatInternal (CheatType type, const char *format=nullptr,...)
uint32 GetFingerprint () const
bool IsKickTimerActive () const
bool IsBanTimerActive () const
void CleanupFingerprintHistory () const
size_t PendingOrderCount () const
uint32 GetWorldEnterTime () const
std::shared_ptr< Antispam > GetAntispam () const
void GetMovementDebugString (std::string &out) const
Public Member Functions inherited from SessionAnticheatInterface
virtual ~SessionAnticheatInterface ()=default
Private Member Functions
void EnterWorld ()
void BeginKickTimer ()
void BeginBanTimer (bool account, bool ip)
Private Attributes
WorldSession *const _session
std::unique_ptr< Warden > _warden
bool _inWorld
uint32 _worldEnterTime
uint32 _tickTimer
uint32 _cheatsReported
uint32 _cheatOccuranceTick [CHEATS_COUNT]
uint32 _cheatOccuranceTotal [CHEATS_COUNT]
uint32 _kickTimer
uint32 _banTimer
bool _banAccount
bool _banIP
uint32 _fingerprint
std::unique_ptr< NamreebAnticheat::Movement > _movementData
std::shared_ptr< NamreebAnticheat::Antispam > _antispam
Static Private Attributes
static constexpr uint32 AnticheatUpdateInterval = 4000
Detailed Description
Definition at line 64 of file libanticheat.hpp.
Constructor & Destructor Documentation
SessionAnticheat()
NamreebAnticheat::SessionAnticheat::SessionAnticheat (WorldSession * session, const BigNumber & K)
Definition at line 668 of file libanticheat.cpp.
References _cheatOccuranceTick, and _cheatOccuranceTotal.
~SessionAnticheat()
NamreebAnticheat::SessionAnticheat::~SessionAnticheat ()
Definition at line 677 of file libanticheat.cpp.
References _antispam, _banAccount, _banIP, _banTimer, _kickTimer, _session, BAN_ACCOUNT, BAN_IP, WorldSession::GetAccountName(), WorldSession::GetRemoteAddress(), World::IsStopped(), WorldSession::KickPlayer(), sAntispamMgr, and sWorld.
Member Function Documentation
AutoReply()
void NamreebAnticheat::SessionAnticheat::AutoReply (const std::string & msg) virtual
Implements SessionAnticheatInterface.
Definition at line 1017 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
BeginBanTimer()
void NamreebAnticheat::SessionAnticheat::BeginBanTimer (bool account, bool ip) private
Definition at line 726 of file libanticheat.cpp.
References _banAccount, _banIP, _banTimer, and sAnticheatConfig.
Referenced by RecordCheat().
BeginKickTimer()
void NamreebAnticheat::SessionAnticheat::BeginKickTimer () private
Definition at line 719 of file libanticheat.cpp.
References _banTimer, _kickTimer, and sAnticheatConfig.
Referenced by RecordCheat().
Channel()
void NamreebAnticheat::SessionAnticheat::Channel (const std::string & msg) virtual
Implements SessionAnticheatInterface.
Definition at line 1041 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
ChannelInvite()
void NamreebAnticheat::SessionAnticheat::ChannelInvite (const std::string & channelName, const ObjectGuid & to) override virtual
Implements SessionAnticheatInterface.
Definition at line 1053 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
CleanupFingerprintHistory()
void NamreebAnticheat::SessionAnticheat::CleanupFingerprintHistory () const
Definition at line 1124 of file libanticheat.cpp.
References _fingerprint, Database::AsyncPQuery(), and LoginDatabase.
Referenced by WardenWin::Update().
Disconnect()
void NamreebAnticheat::SessionAnticheat::Disconnect () virtual
Implements SessionAnticheatInterface.
Definition at line 818 of file libanticheat.cpp.
References _antispam, and sAntispamMgr.
EnterWorld()
void NamreebAnticheat::SessionAnticheat::EnterWorld () private
Definition at line 712 of file libanticheat.cpp.
References _inWorld, _movementData, _worldEnterTime, and WorldTimer::getMSTime().
Referenced by Movement().
ExtrapolateMovement()
bool NamreebAnticheat::SessionAnticheat::ExtrapolateMovement (MovementInfo const & mi, uint32 diffMs, Position & pos) virtual
Implements SessionAnticheatInterface.
Definition at line 967 of file libanticheat.cpp.
References _movementData.
GetAntispam()
std::shared_ptr<Antispam> NamreebAnticheat::SessionAnticheat::GetAntispam () const inline
Definition at line 199 of file libanticheat.hpp.
References _antispam.
GetDistanceTraveled()
float NamreebAnticheat::SessionAnticheat::GetDistanceTraveled () const
Definition at line 1135 of file libanticheat.cpp.
References _movementData.
Referenced by NamreebAnticheat::Antispam::GetDistanceTraveled().
GetFingerprint()
uint32 NamreebAnticheat::SessionAnticheat::GetFingerprint () const inline
Definition at line 188 of file libanticheat.hpp.
References _fingerprint.
Referenced by HandleAnticheatFingerprintListCommand(), and WardenWin::Update().
GetMovementDebugString()
void NamreebAnticheat::SessionAnticheat::GetMovementDebugString (std::string & out) const
Definition at line 1238 of file libanticheat.cpp.
References _movementData.
Referenced by NamreebAnticheat::Movement::HandleAnticheatTests(), and NamreebAnticheat::Movement::SendOrderInfo().
GetMovementSpeeds()
bool NamreebAnticheat::SessionAnticheat::GetMovementSpeeds (float * speeds) const
Definition at line 1140 of file libanticheat.cpp.
References _movementData.
GetWorldEnterTime()
uint32 NamreebAnticheat::SessionAnticheat::GetWorldEnterTime () const inline
Definition at line 197 of file libanticheat.hpp.
References _worldEnterTime.
IsBanTimerActive()
bool NamreebAnticheat::SessionAnticheat::IsBanTimerActive () const inline
Definition at line 191 of file libanticheat.hpp.
References _banTimer.
Referenced by NamreebAnticheat::Movement::HandleAnticheatTests().
IsInKnockBack()
bool NamreebAnticheat::SessionAnticheat::IsInKnockBack () const virtual
Implements SessionAnticheatInterface.
Definition at line 977 of file libanticheat.cpp.
References _movementData.
IsKickTimerActive()
bool NamreebAnticheat::SessionAnticheat::IsKickTimerActive () const inline
Definition at line 190 of file libanticheat.hpp.
References _kickTimer.
Referenced by NamreebAnticheat::Movement::HandleAnticheatTests().
IsSilenced()
bool NamreebAnticheat::SessionAnticheat::IsSilenced () const virtual
Implements SessionAnticheatInterface.
Definition at line 794 of file libanticheat.cpp.
References _session, and sAntispamMgr.
KnockBack()
void NamreebAnticheat::SessionAnticheat::KnockBack (float speedxy, float speedz, float cos, float sin) virtual
Implements SessionAnticheatInterface.
Definition at line 982 of file libanticheat.cpp.
References _movementData.
LeaveWorld()
void NamreebAnticheat::SessionAnticheat::LeaveWorld () virtual
Implements SessionAnticheatInterface.
Definition at line 809 of file libanticheat.cpp.
References _inWorld, and _movementData.
Mail()
void NamreebAnticheat::SessionAnticheat::Mail (const std::string & subject, const std::string & body, const ObjectGuid & to) virtual
Implements SessionAnticheatInterface.
Definition at line 1047 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
Movement()
bool NamreebAnticheat::SessionAnticheat::Movement (MovementInfo & mi, const WorldPacket & packet) virtual
Implements SessionAnticheatInterface.
Definition at line 930 of file libanticheat.cpp.
References _inWorld, _movementData, _session, CMSG_SET_ACTIVE_MOVER, EnterWorld(), Player::GetMover(), WorldPacket::GetOpcode(), WorldSession::GetPlayer(), MovementInfo::GetTransportGuid(), MovementInfo::HasMovementFlag(), MOVEFLAG_ONTRANSPORT, and TYPEID_PLAYER.
NewPlayer()
void NamreebAnticheat::SessionAnticheat::NewPlayer () virtual
Implements SessionAnticheatInterface.
Definition at line 799 of file libanticheat.cpp.
References _movementData, _session, and WorldSession::GetPlayer().
OnExplore()
void NamreebAnticheat::SessionAnticheat::OnExplore (const AreaTableEntry * p) virtual
Implements SessionAnticheatInterface.
Definition at line 988 of file libanticheat.cpp.
References _movementData.
OrderAck()
void NamreebAnticheat::SessionAnticheat::OrderAck (uint16 opcode, uint32 counter) virtual
Implements SessionAnticheatInterface.
Definition at line 1006 of file libanticheat.cpp.
References _movementData.
OrderSent()
void NamreebAnticheat::SessionAnticheat::OrderSent (uint16 opcode, uint32 counter) virtual
Implements SessionAnticheatInterface.
Definition at line 1000 of file libanticheat.cpp.
References _movementData.
PartyInvite()
void NamreebAnticheat::SessionAnticheat::PartyInvite (const ObjectGuid & to) virtual
Implements SessionAnticheatInterface.
Definition at line 1059 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
PendingOrderCount()
size_t NamreebAnticheat::SessionAnticheat::PendingOrderCount () const
Definition at line 1130 of file libanticheat.cpp.
References _movementData.
ReadAddonInfo()
bool NamreebAnticheat::SessionAnticheat::ReadAddonInfo (WorldPacket * authSession, WorldPacket & out) virtual
Implements SessionAnticheatInterface.
Definition at line 85 of file AddonHandler.cpp.
References _fingerprint, _session, ByteBuffer::append(), ByteBuffer::contents(), WorldSession::GetAccountId(), WorldSession::GetAccountName(), WorldSession::GetLocalAddress(), WorldSession::GetRemoteAddress(), WorldPacket::Initialize(), ByteBuffer::read(), ByteBuffer::resize(), ByteBuffer::rpos(), ByteBuffer::size(), sLog, SMSG_ADDON_INFO, and ByteBuffer::wpos().
RecordCheat()
void NamreebAnticheat::SessionAnticheat::RecordCheat (uint32 actionMask, const char * detector, const char * format, ...) virtual
Implements SessionAnticheatInterface.
Definition at line 873 of file libanticheat.cpp.
References _session, ACCOUNT_FLAG_SILENCED, WorldSession::AddAccountFlag(), BeginBanTimer(), BeginKickTimer(), CHEAT_ACTION_BAN_ACCOUNT, CHEAT_ACTION_BAN_IP, CHEAT_ACTION_INFO_LOG, CHEAT_ACTION_KICK, CHEAT_ACTION_NONE, CHEAT_ACTION_PROMPT_LOG, CHEAT_ACTION_SILENCE, WorldSession::GetAccountId(), WorldSession::GetSecurity(), LoginDatabase, Database::PExecute(), and SEC_PLAYER.
Referenced by RecordCheatInternal().
RecordCheatInternal()
void NamreebAnticheat::SessionAnticheat::RecordCheatInternal (CheatType type, const char * format = nullptr, ...)
Definition at line 1065 of file libanticheat.cpp.
References _cheatOccuranceTick, _cheatOccuranceTotal, _cheatsReported, _session, ACCOUNT_FLAG_HIDDEN, CHEAT_ACTION_BAN_ACCOUNT, CHEAT_ACTION_BAN_IP, CHEAT_ACTION_INFO_LOG, CHEAT_ACTION_KICK, CHEAT_ACTION_PROMPT_LOG, CHEAT_ACTION_SILENCE, NamreebAnticheat::CHEAT_TYPE_WARDEN, NamreebAnticheat::CHEATS_COUNT, WorldSession::GetAccountFlags(), WorldSession::GetAccountMaxLevel(), MANGOS_ASSERT, RecordCheat(), and sAnticheatConfig.
Referenced by NamreebAnticheat::Movement::CheckTeleport(), NamreebAnticheat::Movement::HandleAnticheatTests(), Warden::HandleChallengeResponse(), Warden::HandlePacket(), NamreebAnticheat::Movement::OnExplore(), NamreebAnticheat::Movement::OnTransport(), NamreebAnticheat::Movement::OrderAck(), Warden::ReadScanResults(), and NamreebAnticheat::Movement::VerifyMovementFlags().
Say()
void NamreebAnticheat::SessionAnticheat::Say (const std::string & msg) virtual
Implements SessionAnticheatInterface.
Definition at line 1029 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
SendCharEnum()
void NamreebAnticheat::SessionAnticheat::SendCharEnum (WorldPacket && packet) virtual
Implements SessionAnticheatInterface.
Definition at line 789 of file libanticheat.cpp.
References _warden.
SendCheatInfo()
void NamreebAnticheat::SessionAnticheat::SendCheatInfo (ChatHandler * handler) const
Definition at line 844 of file libanticheat.cpp.
References _cheatOccuranceTotal, _inWorld, _movementData, NamreebAnticheat::CHEATS_COUNT, ChatHandler::PSendSysMessage(), sAnticheatConfig, SendPlayerInfo(), and ChatHandler::SendSysMessage().
SendPlayerInfo()
void NamreebAnticheat::SessionAnticheat::SendPlayerInfo (ChatHandler * handler) const virtual
Implements SessionAnticheatInterface.
Definition at line 832 of file libanticheat.cpp.
References _fingerprint, _session, _warden, CLIENT_OS_WIN, WorldSession::GetGameBuild(), WorldSession::GetLocalAddress(), WorldSession::GetOS(), WorldSession::GetSecurity(), ChatHandler::GetSession(), ChatHandler::PSendSysMessage(), and sAnticheatConfig.
Referenced by SendCheatInfo().
SendSpamInfo()
void NamreebAnticheat::SessionAnticheat::SendSpamInfo (ChatHandler * handler) const
Definition at line 867 of file libanticheat.cpp.
References _antispam, and ChatHandler::SendSysMessage().
SpeedChangeAck()
bool NamreebAnticheat::SessionAnticheat::SpeedChangeAck (MovementInfo & mi, const WorldPacket & packet, float newSpeed) virtual
Implements SessionAnticheatInterface.
Definition at line 972 of file libanticheat.cpp.
References _movementData, and _session.
Teleport()
void NamreebAnticheat::SessionAnticheat::Teleport (const Position & pos) virtual
Implements SessionAnticheatInterface.
Definition at line 994 of file libanticheat.cpp.
References _movementData.
TimeSkipped()
void NamreebAnticheat::SessionAnticheat::TimeSkipped (const ObjectGuid & mover, uint32 ms) virtual
Implements SessionAnticheatInterface.
Definition at line 961 of file libanticheat.cpp.
References _movementData.
Update()
void NamreebAnticheat::SessionAnticheat::Update (uint32 diff) virtual
Implements SessionAnticheatInterface.
Definition at line 737 of file libanticheat.cpp.
References _banAccount, _banIP, _banTimer, _cheatOccuranceTick, _cheatsReported, _kickTimer, _movementData, _session, _tickTimer, _warden, AnticheatUpdateInterval, BAN_ACCOUNT, BAN_IP, WorldSession::GetAccountName(), WorldSession::GetLatency(), WorldSession::GetRemoteAddress(), WorldSession::KickPlayer(), sAnticheatConfig, and sWorld.
VerifyMovementFlags()
void NamreebAnticheat::SessionAnticheat::VerifyMovementFlags (uint32 flags, uint32 & removeFlags, bool strict) const
Definition at line 1230 of file libanticheat.cpp.
References _movementData.
VerifyTracking()
bool NamreebAnticheat::SessionAnticheat::VerifyTracking (uint16 unitTracking, uint16 resourceTracking) const
Definition at line 1149 of file libanticheat.cpp.
References _session, WorldSession::GetAccountId(), WorldSession::GetPlayer(), WorldSession::GetPlayerName(), WorldSession::GetRemoteAddress(), and sLog.
WardenPacket()
void NamreebAnticheat::SessionAnticheat::WardenPacket (WorldPacket & packet) virtual
Implements SessionAnticheatInterface.
Definition at line 1012 of file libanticheat.cpp.
References _warden.
Whisper()
void NamreebAnticheat::SessionAnticheat::Whisper (const std::string & msg, const ObjectGuid & to) virtual
Implements SessionAnticheatInterface.
Definition at line 1023 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
Yell()
void NamreebAnticheat::SessionAnticheat::Yell (const std::string & msg) virtual
Implements SessionAnticheatInterface.
Definition at line 1035 of file libanticheat.cpp.
References _antispam, _session, and sAntispamMgr.
Field Documentation
_antispam
std::shared_ptr<NamreebAnticheat::Antispam> NamreebAnticheat::SessionAnticheat::_antispam private
Definition at line 158 of file libanticheat.hpp.
Referenced by AutoReply(), Channel(), ChannelInvite(), Disconnect(), GetAntispam(), Mail(), PartyInvite(), Say(), SendSpamInfo(), Whisper(), Yell(), and ~SessionAnticheat().
_banAccount
bool NamreebAnticheat::SessionAnticheat::_banAccount private
Definition at line 144 of file libanticheat.hpp.
Referenced by BeginBanTimer(), Update(), and ~SessionAnticheat().
_banIP
bool NamreebAnticheat::SessionAnticheat::_banIP private
Definition at line 147 of file libanticheat.hpp.
Referenced by BeginBanTimer(), Update(), and ~SessionAnticheat().
_banTimer
uint32 NamreebAnticheat::SessionAnticheat::_banTimer private
Definition at line 141 of file libanticheat.hpp.
Referenced by BeginBanTimer(), BeginKickTimer(), IsBanTimerActive(), Update(), and ~SessionAnticheat().
_cheatOccuranceTick
uint32 NamreebAnticheat::SessionAnticheat::_cheatOccuranceTick[CHEATS_COUNT] private
Definition at line 134 of file libanticheat.hpp.
Referenced by RecordCheatInternal(), SessionAnticheat(), and Update().
_cheatOccuranceTotal
uint32 NamreebAnticheat::SessionAnticheat::_cheatOccuranceTotal[CHEATS_COUNT] private
Definition at line 135 of file libanticheat.hpp.
Referenced by RecordCheatInternal(), SendCheatInfo(), and SessionAnticheat().
_cheatsReported
uint32 NamreebAnticheat::SessionAnticheat::_cheatsReported private
Definition at line 131 of file libanticheat.hpp.
Referenced by RecordCheatInternal(), and Update().
_fingerprint
uint32 NamreebAnticheat::SessionAnticheat::_fingerprint private
Definition at line 150 of file libanticheat.hpp.
Referenced by CleanupFingerprintHistory(), GetFingerprint(), ReadAddonInfo(), and SendPlayerInfo().
_inWorld
bool NamreebAnticheat::SessionAnticheat::_inWorld private
Definition at line 124 of file libanticheat.hpp.
Referenced by EnterWorld(), LeaveWorld(), Movement(), and SendCheatInfo().
_kickTimer
uint32 NamreebAnticheat::SessionAnticheat::_kickTimer private
Definition at line 138 of file libanticheat.hpp.
Referenced by BeginKickTimer(), IsKickTimerActive(), Update(), and ~SessionAnticheat().
_movementData
std::unique_ptr<NamreebAnticheat::Movement> NamreebAnticheat::SessionAnticheat::_movementData private
Definition at line 155 of file libanticheat.hpp.
Referenced by EnterWorld(), ExtrapolateMovement(), GetDistanceTraveled(), GetMovementDebugString(), GetMovementSpeeds(), IsInKnockBack(), KnockBack(), LeaveWorld(), Movement(), NewPlayer(), OnExplore(), OrderAck(), OrderSent(), PendingOrderCount(), SendCheatInfo(), SpeedChangeAck(), Teleport(), TimeSkipped(), Update(), and VerifyMovementFlags().
_session
WorldSession* const NamreebAnticheat::SessionAnticheat::_session private
Definition at line 121 of file libanticheat.hpp.
Referenced by AutoReply(), Channel(), ChannelInvite(), IsSilenced(), Mail(), Movement(), NewPlayer(), PartyInvite(), ReadAddonInfo(), RecordCheat(), RecordCheatInternal(), Say(), SendPlayerInfo(), SpeedChangeAck(), Update(), VerifyTracking(), Whisper(), Yell(), and ~SessionAnticheat().
_tickTimer
uint32 NamreebAnticheat::SessionAnticheat::_tickTimer private
Definition at line 128 of file libanticheat.hpp.
Referenced by Update().
_warden
std::unique_ptr<Warden> NamreebAnticheat::SessionAnticheat::_warden private
Definition at line 122 of file libanticheat.hpp.
Referenced by SendCharEnum(), SendPlayerInfo(), Update(), and WardenPacket().
_worldEnterTime
uint32 NamreebAnticheat::SessionAnticheat::_worldEnterTime private
Definition at line 125 of file libanticheat.hpp.
Referenced by EnterWorld(), and GetWorldEnterTime().
AnticheatUpdateInterval
constexpr uint32 NamreebAnticheat::SessionAnticheat::AnticheatUpdateInterval = 4000 static constexpr private
Definition at line 119 of file libanticheat.hpp.
Referenced by Update().
The documentation for this class was generated from the following files:
libanticheat.hpp
AddonHandler.cpp
libanticheat.cpp