CMaNGOS_WoTLK: SqlDelayThread Class Reference
SqlDelayThread Class Reference
#include <SqlDelayThread.h>
Public Member Functions
SqlDelayThread (Database *db, SqlConnection *conn)
~SqlDelayThread ()
Put sql statement to delay queue.
bool Delay (SqlOperation *sql)
virtual void Stop ()
Stop event.
virtual void run ()
Main Thread loop.
Public Member Functions inherited from MaNGOS::Runnable
virtual ~Runnable ()
void incReference ()
void decReference ()
Private Member Functions
void ProcessRequests ()
Private Attributes
std::mutex m_queueMutex
std::queue< std::unique_ptr< SqlOperation > > m_sqlQueue
Queue of SQL statements.
Database * m_dbEngine
Pointer to used Database engine.
SqlConnection * m_dbConnection
Pointer to DB connection.
std::atomic< bool > m_running
Detailed Description
Definition at line 34 of file SqlDelayThread.h.
Constructor & Destructor Documentation
SqlDelayThread()
SqlDelayThread::SqlDelayThread (Database * db, SqlConnection * conn)
Definition at line 23 of file SqlDelayThread.cpp.
~SqlDelayThread()
SqlDelayThread::~SqlDelayThread ()
Put sql statement to delay queue.
Definition at line 27 of file SqlDelayThread.cpp.
References ProcessRequests().
Member Function Documentation
Delay()
bool SqlDelayThread::Delay (SqlOperation * sql) inline
Definition at line 51 of file SqlDelayThread.h.
References m_queueMutex, and m_sqlQueue.
Referenced by Database::AsyncQuery(), Database::CommitTransaction(), Database::Execute(), SqlQueryHolder::Execute(), and Database::ExecuteStmt().
ProcessRequests()
void SqlDelayThread::ProcessRequests () private
Definition at line 69 of file SqlDelayThread.cpp.
References m_dbConnection, m_queueMutex, and m_sqlQueue.
Referenced by run(), and ~SqlDelayThread().
run()
void SqlDelayThread::run (void) virtual
Main Thread loop.
Implements MaNGOS::Runnable.
Definition at line 33 of file SqlDelayThread.cpp.
References Database::GetPingIntervall(), m_dbEngine, m_running, Database::Ping(), ProcessRequests(), and MaNGOS::Thread::Sleep().
Stop()
void SqlDelayThread::Stop () virtual
Stop event.
Reimplemented in PGSQLDelayThread.
Definition at line 64 of file SqlDelayThread.cpp.
References m_running.
Referenced by Database::HaltDelayThread(), and PGSQLDelayThread::Stop().
Field Documentation
m_dbConnection
SqlConnection* SqlDelayThread::m_dbConnection private
Pointer to DB connection.
Definition at line 40 of file SqlDelayThread.h.
Referenced by ProcessRequests().
m_dbEngine
Database* SqlDelayThread::m_dbEngine private
Pointer to used Database engine.
Definition at line 39 of file SqlDelayThread.h.
Referenced by run().
m_queueMutex
std::mutex SqlDelayThread::m_queueMutex private
Definition at line 37 of file SqlDelayThread.h.
Referenced by Delay(), and ProcessRequests().
m_running
std::atomic<bool> SqlDelayThread::m_running private
Definition at line 41 of file SqlDelayThread.h.
Referenced by run(), and Stop().
m_sqlQueue
std::queue<std::unique_ptr<SqlOperation> > SqlDelayThread::m_sqlQueue private
Queue of SQL statements.
Definition at line 38 of file SqlDelayThread.h.
Referenced by Delay(), and ProcessRequests().
The documentation for this class was generated from the following files:
SqlDelayThread.h
SqlDelayThread.cpp