CMaNGOS_WoTLK: DistractMovementGenerator Class Reference
DistractMovementGenerator Class Reference
#include <IdleMovementGenerator.h>
Public Member Functions
DistractMovementGenerator (uint32 timer)
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Reset (Unit &owner) override
bool Update (Unit &owner, const uint32 &diff) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from IdleMovementGenerator
void Interrupt (Unit &) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Private Attributes
ShortTimeTracker m_timer
Detailed Description
Definition at line 38 of file IdleMovementGenerator.h.
Constructor & Destructor Documentation
DistractMovementGenerator()
DistractMovementGenerator::DistractMovementGenerator (uint32 timer) inline explicit
Definition at line 41 of file IdleMovementGenerator.h.
Member Function Documentation
Finalize()
void DistractMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from IdleMovementGenerator.
Definition at line 35 of file IdleMovementGenerator.cpp.
References Unit::clearUnitState(), and UNIT_STAT_DISTRACTED.
GetMovementGeneratorType()
MovementGeneratorType DistractMovementGenerator::GetMovementGeneratorType () const inline override virtual
Reimplemented from IdleMovementGenerator.
Definition at line 48 of file IdleMovementGenerator.h.
References DISTRACT_MOTION_TYPE.
Initialize()
void DistractMovementGenerator::Initialize (Unit & owner) override virtual
Reimplemented from IdleMovementGenerator.
Definition at line 30 of file IdleMovementGenerator.cpp.
References Unit::addUnitState(), and UNIT_STAT_DISTRACTED.
Referenced by Reset().
Reset()
void DistractMovementGenerator::Reset (Unit & owner) override virtual
Reimplemented from IdleMovementGenerator.
Definition at line 40 of file IdleMovementGenerator.cpp.
References Initialize().
Update()
bool DistractMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Reimplemented from IdleMovementGenerator.
Definition at line 45 of file IdleMovementGenerator.cpp.
References Unit::hasUnitState(), m_timer, ShortTimeTracker::Passed(), UNIT_STAT_DISTRACTED, and ShortTimeTracker::Update().
Field Documentation
m_timer
ShortTimeTracker DistractMovementGenerator::m_timer private
Definition at line 51 of file IdleMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
IdleMovementGenerator.h
IdleMovementGenerator.cpp