CMaNGOS_WoTLK: SqlStmtFieldData Class Reference
SqlStmtFieldData Class Reference
#include <SqlPreparedStatement.h>
Public Member Functions
SqlStmtFieldData ()
~SqlStmtFieldData ()
template<typename T >
SqlStmtFieldData (T param)
template<typename T1 >
void set (T1 param1)
bool toBool () const
uint8 toUint8 () const
int8 toInt8 () const
uint16 toUint16 () const
int16 toInt16 () const
uint32 toUint32 () const
int32 toInt32 () const
uint64 toUint64 () const
int64 toInt64 () const
float toFloat () const
double toDouble () const
const char * toStr () const
SqlStmtFieldType type () const
void * buff () const
size_t size () const
template<>
void set (bool val)
template<>
void set (uint8 val)
template<>
void set (int8 val)
template<>
void set (uint16 val)
template<>
void set (int16 val)
template<>
void set (uint32 val)
template<>
void set (int32 val)
template<>
void set (uint64 val)
template<>
void set (int64 val)
template<>
void set (float val)
template<>
void set (double val)
template<>
void set (const char *val)
Private Attributes
SqlStmtFieldType m_type
SqlStmtField m_binaryData
std::string m_szStringData
Detailed Description
Definition at line 65 of file SqlPreparedStatement.h.
Constructor & Destructor Documentation
SqlStmtFieldData() [1/2]
SqlStmtFieldData::SqlStmtFieldData () inline
Definition at line 68 of file SqlPreparedStatement.h.
References m_binaryData, and SqlStmtField::ui64.
~SqlStmtFieldData()
SqlStmtFieldData::~SqlStmtFieldData () inline
Definition at line 69 of file SqlPreparedStatement.h.
SqlStmtFieldData() [2/2]
template<typename T > SqlStmtFieldData::SqlStmtFieldData (T param) inline
Definition at line 72 of file SqlPreparedStatement.h.
References set().
Member Function Documentation
buff()
void* SqlStmtFieldData::buff () const inline
Definition at line 94 of file SqlPreparedStatement.h.
References FIELD_STRING, m_binaryData, m_szStringData, and m_type.
Referenced by MySqlPreparedStatement::addParam().
set() [1/13]
template<> void SqlStmtFieldData::set (bool val) inline
Definition at line 127 of file SqlPreparedStatement.h.
References FIELD_BOOL, m_binaryData, m_type, and SqlStmtField::ui8.
set() [2/13]
template<> void SqlStmtFieldData::set (const char * val) inline
Definition at line 138 of file SqlPreparedStatement.h.
References FIELD_STRING, m_szStringData, and m_type.
set() [3/13]
template<> void SqlStmtFieldData::set (double val) inline
Definition at line 137 of file SqlPreparedStatement.h.
References SqlStmtField::d, FIELD_DOUBLE, m_binaryData, and m_type.
set() [4/13]
template<> void SqlStmtFieldData::set (float val) inline
Definition at line 136 of file SqlPreparedStatement.h.
References SqlStmtField::f, FIELD_FLOAT, m_binaryData, and m_type.
set() [5/13]
template<> void SqlStmtFieldData::set (int16 val) inline
Definition at line 131 of file SqlPreparedStatement.h.
References FIELD_I16, SqlStmtField::i16, m_binaryData, and m_type.
set() [6/13]
template<> void SqlStmtFieldData::set (int32 val) inline
Definition at line 133 of file SqlPreparedStatement.h.
References FIELD_I32, SqlStmtField::i32, m_binaryData, and m_type.
set() [7/13]
template<> void SqlStmtFieldData::set (int64 val) inline
Definition at line 135 of file SqlPreparedStatement.h.
References FIELD_I64, SqlStmtField::i64, m_binaryData, and m_type.
set() [8/13]
template<> void SqlStmtFieldData::set (int8 val) inline
Definition at line 129 of file SqlPreparedStatement.h.
References FIELD_I8, SqlStmtField::i8, m_binaryData, and m_type.
set() [9/13]
template<typename T1 > void SqlStmtFieldData::set (T1 param1)
Referenced by SqlStmtFieldData().
set() [10/13]
template<> void SqlStmtFieldData::set (uint16 val) inline
Definition at line 130 of file SqlPreparedStatement.h.
References FIELD_UI16, m_binaryData, m_type, and SqlStmtField::ui16.
set() [11/13]
template<> void SqlStmtFieldData::set (uint32 val) inline
Definition at line 132 of file SqlPreparedStatement.h.
References FIELD_UI32, m_binaryData, m_type, and SqlStmtField::ui32.
set() [12/13]
template<> void SqlStmtFieldData::set (uint64 val) inline
Definition at line 134 of file SqlPreparedStatement.h.
References FIELD_UI64, m_binaryData, m_type, and SqlStmtField::ui64.
set() [13/13]
template<> void SqlStmtFieldData::set (uint8 val) inline
Definition at line 128 of file SqlPreparedStatement.h.
References FIELD_UI8, m_binaryData, m_type, and SqlStmtField::ui8.
size()
size_t SqlStmtFieldData::size () const inline
Definition at line 97 of file SqlPreparedStatement.h.
References FIELD_BOOL, FIELD_DOUBLE, FIELD_FLOAT, FIELD_I16, FIELD_I32, FIELD_I64, FIELD_I8, FIELD_NONE, FIELD_STRING, FIELD_UI16, FIELD_UI32, FIELD_UI64, FIELD_UI8, m_szStringData, and m_type.
Referenced by MySqlPreparedStatement::addParam().
toBool()
bool SqlStmtFieldData::toBool () const inline
Definition at line 78 of file SqlPreparedStatement.h.
References FIELD_BOOL, m_binaryData, m_type, MANGOS_ASSERT, and SqlStmtField::ui8.
Referenced by SqlPlainPreparedStatement::DataToString().
toDouble()
double SqlStmtFieldData::toDouble () const inline
Definition at line 88 of file SqlPreparedStatement.h.
References SqlStmtField::d, FIELD_DOUBLE, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toFloat()
float SqlStmtFieldData::toFloat () const inline
Definition at line 87 of file SqlPreparedStatement.h.
References SqlStmtField::f, FIELD_FLOAT, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toInt16()
int16 SqlStmtFieldData::toInt16 () const inline
Definition at line 82 of file SqlPreparedStatement.h.
References FIELD_I16, SqlStmtField::i16, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toInt32()
int32 SqlStmtFieldData::toInt32 () const inline
Definition at line 84 of file SqlPreparedStatement.h.
References FIELD_I32, SqlStmtField::i32, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toInt64()
int64 SqlStmtFieldData::toInt64 () const inline
Definition at line 86 of file SqlPreparedStatement.h.
References FIELD_I64, SqlStmtField::i64, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toInt8()
int8 SqlStmtFieldData::toInt8 () const inline
Definition at line 80 of file SqlPreparedStatement.h.
References FIELD_I8, SqlStmtField::i8, m_binaryData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toStr()
const char* SqlStmtFieldData::toStr () const inline
Definition at line 89 of file SqlPreparedStatement.h.
References FIELD_STRING, m_szStringData, m_type, and MANGOS_ASSERT.
Referenced by SqlPlainPreparedStatement::DataToString().
toUint16()
uint16 SqlStmtFieldData::toUint16 () const inline
Definition at line 81 of file SqlPreparedStatement.h.
References FIELD_UI16, m_binaryData, m_type, MANGOS_ASSERT, and SqlStmtField::ui16.
Referenced by SqlPlainPreparedStatement::DataToString().
toUint32()
uint32 SqlStmtFieldData::toUint32 () const inline
Definition at line 83 of file SqlPreparedStatement.h.
References FIELD_UI32, m_binaryData, m_type, MANGOS_ASSERT, and SqlStmtField::ui32.
Referenced by SqlPlainPreparedStatement::DataToString().
toUint64()
uint64 SqlStmtFieldData::toUint64 () const inline
Definition at line 85 of file SqlPreparedStatement.h.
References FIELD_UI64, m_binaryData, m_type, MANGOS_ASSERT, and SqlStmtField::ui64.
Referenced by SqlPlainPreparedStatement::DataToString().
toUint8()
uint8 SqlStmtFieldData::toUint8 () const inline
Definition at line 79 of file SqlPreparedStatement.h.
References FIELD_UI8, m_binaryData, m_type, MANGOS_ASSERT, and SqlStmtField::ui8.
Referenced by SqlPlainPreparedStatement::DataToString().
type()
SqlStmtFieldType SqlStmtFieldData::type () const inline
Definition at line 92 of file SqlPreparedStatement.h.
References m_type.
Referenced by MySqlPreparedStatement::addParam(), SqlPlainPreparedStatement::DataToString(), and MySqlPreparedStatement::ToMySQLType().
Field Documentation
m_binaryData
SqlStmtField SqlStmtFieldData::m_binaryData private
Definition at line 122 of file SqlPreparedStatement.h.
Referenced by buff(), set(), SqlStmtFieldData(), toBool(), toDouble(), toFloat(), toInt16(), toInt32(), toInt64(), toInt8(), toUint16(), toUint32(), toUint64(), and toUint8().
m_szStringData
std::string SqlStmtFieldData::m_szStringData private
Definition at line 123 of file SqlPreparedStatement.h.
Referenced by buff(), set(), size(), and toStr().
m_type
SqlStmtFieldType SqlStmtFieldData::m_type private
Definition at line 121 of file SqlPreparedStatement.h.
Referenced by buff(), set(), size(), toBool(), toDouble(), toFloat(), toInt16(), toInt32(), toInt64(), toInt8(), toStr(), toUint16(), toUint32(), toUint64(), toUint8(), and type().
The documentation for this class was generated from the following file:
SqlPreparedStatement.h