CMaNGOS_WoTLK: NamreebAnticheat::AnticheatConfig Class Reference
NamreebAnticheat::AnticheatConfig Class Reference
#include <config.hpp>
Public Member Functions
AnticheatConfig ()
void loadConfigSettings ()
uint32 getConfig (AnticheatConfigUInt32Values index) const
bool getConfig (AnticheatConfigBoolValues index) const
float getConfig (AnticheatConfigFloatValues index) const
bool EnableAnticheat () const
bool EnableExtrapolation () const
bool IsEnabled (CheatType cheatType) const
bool EnableAntiSpeedHack () const
uint32 GetFingerprintHistory () const
uint32 GetFingerprintLevel () const
uint32 GetWardenTimeout () const
uint32 GetWardenScanFrequency () const
uint32 GetWardenScanCount () const
uint32 GetWardenMinimumLevel () const
uint32 GetWardenMinimumAdvancedLevel () const
uint32 GetWardenSuspiciousEndSceneHookAction () const
std::string GetWardenModuleDirectory () const
bool CheckResponse (CheatType cheatType, uint32 tickCount, uint32 totalCount, uint32 &actionMask) const
uint32 GetKickDelay () const
uint32 GetBanDelay () const
uint32 GetIPBanDelay () const
void GetBanWaveTime (uint32 &day, uint32 &hour, uint32 &minute) const
bool EnableAntispam () const
bool EnableAntispamSilence () const
uint32 GetSpamNormalizationMask () const
uint32 GetAntispamAnalysisTimer () const
uint32 GetAntispamMaxLevel () const
uint32 GetAntispamMaxRate () const
uint32 GetAntispamMaxUniquePercentage () const
uint32 GetAntispamMinUniqueMessages () const
uint32 GetAntispamRateGracePeriod () const
uint32 GetAntispamBlacklistNotify () const
uint32 GetAntispamBlacklistNotifyCooldown () const
uint32 GetAntispamBlacklistSilence () const
uint32 GetAntispamBlacklistLevel () const
uint32 GetAntispamCacheExpiration () const
uint32 GetAntispamUniquenessThreshold () const
uint32 GetAntispamMinRepetitionMessages () const
uint32 GetAntispamRepetitionNotify () const
uint32 GetAntispamRepetitionSilence () const
uint32 GetAntispamRepetitionMovementTimeout () const
float GetAntispamRepetitionDistanceScale () const
float GetAntispamRepetitionTimeScale () const
Public Member Functions inherited from Config
bool SetSource (const std::string &file)
bool Reload ()
bool IsSet (const std::string &name) const
const std::string GetStringDefault (const std::string &name, const std::string &def="") const
bool GetBoolDefault (const std::string &name, bool def) const
int32 GetIntDefault (const std::string &name, int32 def) const
float GetFloatDefault (const std::string &name, float def) const
const std::string & GetFilename () const
Static Public Member Functions
static const char * GetDetectorName (CheatType cheatType)
Private Member Functions
void setConfig (AnticheatConfigUInt32Values index, uint32 value)
void setConfig (AnticheatConfigBoolValues index, bool value)
void setConfig (AnticheatConfigFloatValues index, float value)
void setConfig (AnticheatConfigUInt32Values index, char const *fieldname, uint32 defvalue)
void setConfig (AnticheatConfigBoolValues index, char const *fieldname, bool defvalue)
void setConfig (AnticheatConfigFloatValues index, char const *fieldname, float defvalue)
Private Attributes
uint32 m_configUInt32Values [CONFIG_UINT32_AC_COUNT]
bool m_configBoolValues [CONFIG_BOOL_AC_COUNT]
float m_configFloatValues [CONFIG_FLOAT_AC_COUNT]
std::string m_wardenModuleDir
CheatResponseRule _responseRules [CHEATS_COUNT]
Additional Inherited Members
Data Fields inherited from Config
std::mutex m_configLock
Detailed Description
Definition at line 83 of file config.hpp.
Constructor & Destructor Documentation
AnticheatConfig()
NamreebAnticheat::AnticheatConfig::AnticheatConfig ()
Definition at line 59 of file config.cpp.
References m_configBoolValues, m_configFloatValues, and m_configUInt32Values.
Member Function Documentation
CheckResponse()
bool NamreebAnticheat::AnticheatConfig::CheckResponse (CheatType cheatType, uint32 tickCount, uint32 totalCount, uint32 & actionMask) const
Definition at line 147 of file config.cpp.
References _responseRules, CHEAT_ACTION_NONE, NamreebAnticheat::CHEATS_COUNT, MANGOS_ASSERT, NamreebAnticheat::CheatResponseRule::tickAction, and NamreebAnticheat::CheatResponseRule::totalAction.
EnableAnticheat()
bool NamreebAnticheat::AnticheatConfig::EnableAnticheat () const inline
Definition at line 111 of file config.hpp.
References NamreebAnticheat::CONFIG_BOOL_AC_ENABLED, and getConfig().
EnableAntispam()
bool NamreebAnticheat::AnticheatConfig::EnableAntispam () const inline
Definition at line 143 of file config.hpp.
References NamreebAnticheat::CONFIG_BOOL_AC_ANTISPAM_ENABLED, and getConfig().
EnableAntispamSilence()
bool NamreebAnticheat::AnticheatConfig::EnableAntispamSilence () const inline
Definition at line 144 of file config.hpp.
References NamreebAnticheat::CONFIG_BOOL_AC_ANTISPAM_SILENCE, and getConfig().
EnableAntiSpeedHack()
bool NamreebAnticheat::AnticheatConfig::EnableAntiSpeedHack () const inline
Definition at line 121 of file config.hpp.
References NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_SPEED_HACK_ENABLED, and getConfig().
EnableExtrapolation()
bool NamreebAnticheat::AnticheatConfig::EnableExtrapolation () const inline
Definition at line 112 of file config.hpp.
References NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_USE_EXTRAPOLATION, and getConfig().
GetAntispamAnalysisTimer()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamAnalysisTimer () const inline
Definition at line 146 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_ANALYSIS_TIMER, and getConfig().
GetAntispamBlacklistLevel()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamBlacklistLevel () const inline
Definition at line 155 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_LEVEL, and getConfig().
GetAntispamBlacklistNotify()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamBlacklistNotify () const inline
Definition at line 152 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_NOTIFY, and getConfig().
GetAntispamBlacklistNotifyCooldown()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamBlacklistNotifyCooldown () const inline
Definition at line 153 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_NOTIFY_COOLDOWN, and getConfig().
GetAntispamBlacklistSilence()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamBlacklistSilence () const inline
Definition at line 154 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_SILENCE, and getConfig().
GetAntispamCacheExpiration()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamCacheExpiration () const inline
Definition at line 156 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_CACHE_EXPIRATION, and getConfig().
GetAntispamMaxLevel()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamMaxLevel () const inline
Definition at line 147 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_LEVEL, and getConfig().
GetAntispamMaxRate()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamMaxRate () const inline
Definition at line 148 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_RATE, and getConfig().
GetAntispamMaxUniquePercentage()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamMaxUniquePercentage () const inline
Definition at line 149 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_UNIQUE_PERCENTAGE, and getConfig().
GetAntispamMinRepetitionMessages()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamMinRepetitionMessages () const inline
Definition at line 158 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MIN_REPETITION_MESSAGES, and getConfig().
GetAntispamMinUniqueMessages()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamMinUniqueMessages () const inline
Definition at line 150 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MIN_UNIQUE_MESSAGES, and getConfig().
GetAntispamRateGracePeriod()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamRateGracePeriod () const inline
Definition at line 151 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_RATE_GRACE_PERIOD, and getConfig().
GetAntispamRepetitionDistanceScale()
float NamreebAnticheat::AnticheatConfig::GetAntispamRepetitionDistanceScale () const inline
Definition at line 162 of file config.hpp.
References NamreebAnticheat::CONFIG_FLOAT_AC_ANTISPAM_REPETITION_DISTANCE_SCALE, and getConfig().
GetAntispamRepetitionMovementTimeout()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamRepetitionMovementTimeout () const inline
Definition at line 161 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_MOVEMENT_TIMEOUT, and getConfig().
GetAntispamRepetitionNotify()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamRepetitionNotify () const inline
Definition at line 159 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_NOTIFY, and getConfig().
GetAntispamRepetitionSilence()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamRepetitionSilence () const inline
Definition at line 160 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_SILENCE, and getConfig().
GetAntispamRepetitionTimeScale()
float NamreebAnticheat::AnticheatConfig::GetAntispamRepetitionTimeScale () const inline
Definition at line 163 of file config.hpp.
References NamreebAnticheat::CONFIG_FLOAT_AC_ANTISPAM_REPETITION_TIME_SCALE, and getConfig().
GetAntispamUniquenessThreshold()
uint32 NamreebAnticheat::AnticheatConfig::GetAntispamUniquenessThreshold () const inline
Definition at line 157 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_UNIQUENESS_THRESHOLD, and getConfig().
GetBanDelay()
uint32 NamreebAnticheat::AnticheatConfig::GetBanDelay () const
Definition at line 174 of file config.cpp.
References NamreebAnticheat::CONFIG_UINT32_AC_BAN_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_BAN_DELAY_MIN, getConfig(), and urand().
GetBanWaveTime()
void NamreebAnticheat::AnticheatConfig::GetBanWaveTime (uint32 & day, uint32 & hour, uint32 & minute) const
Definition at line 190 of file config.cpp.
References NamreebAnticheat::CONFIG_UINT32_AC_BAN_WAVE_DAY, NamreebAnticheat::CONFIG_UINT32_AC_BAN_WAVE_HOUR, and getConfig().
getConfig() [1/3]
bool NamreebAnticheat::AnticheatConfig::getConfig (AnticheatConfigBoolValues index) const inline
Definition at line 108 of file config.hpp.
References m_configBoolValues.
getConfig() [2/3]
float NamreebAnticheat::AnticheatConfig::getConfig (AnticheatConfigFloatValues index) const inline
Definition at line 109 of file config.hpp.
References m_configFloatValues.
getConfig() [3/3]
uint32 NamreebAnticheat::AnticheatConfig::getConfig (AnticheatConfigUInt32Values index) const inline
Definition at line 107 of file config.hpp.
References m_configUInt32Values.
Referenced by EnableAnticheat(), EnableAntispam(), EnableAntispamSilence(), EnableAntiSpeedHack(), EnableExtrapolation(), GetAntispamAnalysisTimer(), GetAntispamBlacklistLevel(), GetAntispamBlacklistNotify(), GetAntispamBlacklistNotifyCooldown(), GetAntispamBlacklistSilence(), GetAntispamCacheExpiration(), GetAntispamMaxLevel(), GetAntispamMaxRate(), GetAntispamMaxUniquePercentage(), GetAntispamMinRepetitionMessages(), GetAntispamMinUniqueMessages(), GetAntispamRateGracePeriod(), GetAntispamRepetitionDistanceScale(), GetAntispamRepetitionMovementTimeout(), GetAntispamRepetitionNotify(), GetAntispamRepetitionSilence(), GetAntispamRepetitionTimeScale(), GetAntispamUniquenessThreshold(), GetBanDelay(), GetBanWaveTime(), GetFingerprintHistory(), GetFingerprintLevel(), GetIPBanDelay(), GetKickDelay(), GetSpamNormalizationMask(), GetWardenMinimumAdvancedLevel(), GetWardenMinimumLevel(), GetWardenScanCount(), GetWardenScanFrequency(), GetWardenSuspiciousEndSceneHookAction(), and GetWardenTimeout().
GetDetectorName()
const char * NamreebAnticheat::AnticheatConfig::GetDetectorName (CheatType cheatType) static
Definition at line 197 of file config.cpp.
References NamreebAnticheat::CHEATS_COUNT, and MANGOS_ASSERT.
Referenced by loadConfigSettings().
GetFingerprintHistory()
uint32 NamreebAnticheat::AnticheatConfig::GetFingerprintHistory () const inline
Definition at line 122 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_FINGERPRINT_HISTORY, and getConfig().
GetFingerprintLevel()
uint32 NamreebAnticheat::AnticheatConfig::GetFingerprintLevel () const inline
Definition at line 123 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_FINGERPRINT_LEVEL, and getConfig().
GetIPBanDelay()
uint32 NamreebAnticheat::AnticheatConfig::GetIPBanDelay () const
Definition at line 182 of file config.cpp.
References NamreebAnticheat::CONFIG_UINT32_AC_IP_BAN_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_IP_BAN_DELAY_MIN, getConfig(), and urand().
GetKickDelay()
uint32 NamreebAnticheat::AnticheatConfig::GetKickDelay () const
Definition at line 166 of file config.cpp.
References NamreebAnticheat::CONFIG_UINT32_AC_KICK_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_KICK_DELAY_MIN, getConfig(), and urand().
GetSpamNormalizationMask()
uint32 NamreebAnticheat::AnticheatConfig::GetSpamNormalizationMask () const inline
Definition at line 145 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_NORMALIZE_MASK, and getConfig().
GetWardenMinimumAdvancedLevel()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenMinimumAdvancedLevel () const inline
Definition at line 129 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_MINIMUM_ADVANCED_LEVEL, and getConfig().
GetWardenMinimumLevel()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenMinimumLevel () const inline
Definition at line 128 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_MINIMUM_LEVEL, and getConfig().
GetWardenModuleDirectory()
std::string NamreebAnticheat::AnticheatConfig::GetWardenModuleDirectory () const inline
Definition at line 131 of file config.hpp.
References m_wardenModuleDir.
GetWardenScanCount()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenScanCount () const inline
Definition at line 127 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SCAN_COUNT, and getConfig().
GetWardenScanFrequency()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenScanFrequency () const inline
Definition at line 126 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SCAN_FREQUENCY, and getConfig().
GetWardenSuspiciousEndSceneHookAction()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenSuspiciousEndSceneHookAction () const inline
Definition at line 130 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SUSPICIOUS_ENDSCENE_HOOK_ACTION, and getConfig().
GetWardenTimeout()
uint32 NamreebAnticheat::AnticheatConfig::GetWardenTimeout () const inline
Definition at line 125 of file config.hpp.
References NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_TIMEOUT, and getConfig().
IsEnabled()
bool NamreebAnticheat::AnticheatConfig::IsEnabled (CheatType cheatType) const inline
Definition at line 114 of file config.hpp.
References _responseRules, CHEAT_ACTION_NONE, NamreebAnticheat::CheatResponseRule::totalAction, and NamreebAnticheat::CheatResponseRule::totalCount.
loadConfigSettings()
void NamreebAnticheat::AnticheatConfig::loadConfigSettings ()
Definition at line 66 of file config.cpp.
References _responseRules, CHEAT_ACTION_INFO_LOG, CHEAT_ACTION_KICK, CHEAT_ACTION_PROMPT_LOG, NamreebAnticheat::CHEAT_TYPE_WARDEN, NamreebAnticheat::CHEATS_COUNT, NamreebAnticheat::CONFIG_BOOL_AC_ANTISPAM_ENABLED, NamreebAnticheat::CONFIG_BOOL_AC_ANTISPAM_SILENCE, NamreebAnticheat::CONFIG_BOOL_AC_ENABLED, NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_CHEAT_BAD_FALL_RESET_ENABLED, NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_SPEED_HACK_ENABLED, NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_USE_EXTRAPOLATION, NamreebAnticheat::CONFIG_BOOL_AC_WARDEN_ENABLED, NamreebAnticheat::CONFIG_FLOAT_AC_ANTISPAM_REPETITION_DISTANCE_SCALE, NamreebAnticheat::CONFIG_FLOAT_AC_ANTISPAM_REPETITION_TIME_SCALE, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_ANALYSIS_TIMER, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_LEVEL, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_NOTIFY, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_NOTIFY_COOLDOWN, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_BLACKLIST_SILENCE, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_CACHE_EXPIRATION, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_LEVEL, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_RATE, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MAX_UNIQUE_PERCENTAGE, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MIN_REPETITION_MESSAGES, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_MIN_UNIQUE_MESSAGES, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_NORMALIZE_MASK, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_RATE_GRACE_PERIOD, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_MOVEMENT_TIMEOUT, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_NOTIFY, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_REPETITION_SILENCE, NamreebAnticheat::CONFIG_UINT32_AC_ANTISPAM_UNIQUENESS_THRESHOLD, NamreebAnticheat::CONFIG_UINT32_AC_BAN_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_BAN_DELAY_MIN, NamreebAnticheat::CONFIG_UINT32_AC_FINGERPRINT_HISTORY, NamreebAnticheat::CONFIG_UINT32_AC_FINGERPRINT_LEVEL, NamreebAnticheat::CONFIG_UINT32_AC_IP_BAN_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_IP_BAN_DELAY_MIN, NamreebAnticheat::CONFIG_UINT32_AC_KICK_DELAY_MAX, NamreebAnticheat::CONFIG_UINT32_AC_KICK_DELAY_MIN, NamreebAnticheat::CONFIG_UINT32_AC_MOVEMENT_CHEAT_BAD_FALL_RESET_PENALTY, NamreebAnticheat::CONFIG_UINT32_AC_MOVEMENT_CHEAT_BAD_FALL_RESET_THRESHOLD, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_MINIMUM_ADVANCED_LEVEL, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_MINIMUM_LEVEL, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SCAN_COUNT, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SCAN_FREQUENCY, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_SUSPICIOUS_ENDSCENE_HOOK_ACTION, NamreebAnticheat::CONFIG_UINT32_AC_WARDEN_TIMEOUT, GetDetectorName(), Config::GetIntDefault(), Config::GetStringDefault(), m_wardenModuleDir, and setConfig().
setConfig() [1/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigBoolValues index, bool value) inline private
Definition at line 95 of file config.hpp.
References m_configBoolValues.
setConfig() [2/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigBoolValues index, char const * fieldname, bool defvalue) private
Definition at line 49 of file config.cpp.
References Config::GetBoolDefault(), and setConfig().
setConfig() [3/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigFloatValues index, char const * fieldname, float defvalue) private
Definition at line 54 of file config.cpp.
References Config::GetFloatDefault(), and setConfig().
setConfig() [4/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigFloatValues index, float value) inline private
Definition at line 96 of file config.hpp.
References m_configFloatValues.
setConfig() [5/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigUInt32Values index, char const * fieldname, uint32 defvalue) private
Definition at line 44 of file config.cpp.
References Config::GetIntDefault(), and setConfig().
setConfig() [6/6]
void NamreebAnticheat::AnticheatConfig::setConfig (AnticheatConfigUInt32Values index, uint32 value) inline private
Definition at line 94 of file config.hpp.
References m_configUInt32Values.
Referenced by loadConfigSettings(), and setConfig().
Field Documentation
_responseRules
CheatResponseRule NamreebAnticheat::AnticheatConfig::_responseRules[CHEATS_COUNT] private
Definition at line 92 of file config.hpp.
Referenced by CheckResponse(), IsEnabled(), and loadConfigSettings().
m_configBoolValues
bool NamreebAnticheat::AnticheatConfig::m_configBoolValues[CONFIG_BOOL_AC_COUNT] private
Definition at line 87 of file config.hpp.
Referenced by AnticheatConfig(), getConfig(), and setConfig().
m_configFloatValues
float NamreebAnticheat::AnticheatConfig::m_configFloatValues[CONFIG_FLOAT_AC_COUNT] private
Definition at line 88 of file config.hpp.
Referenced by AnticheatConfig(), getConfig(), and setConfig().
m_configUInt32Values
uint32 NamreebAnticheat::AnticheatConfig::m_configUInt32Values[CONFIG_UINT32_AC_COUNT] private
Definition at line 86 of file config.hpp.
Referenced by AnticheatConfig(), getConfig(), and setConfig().
m_wardenModuleDir
std::string NamreebAnticheat::AnticheatConfig::m_wardenModuleDir private
Definition at line 90 of file config.hpp.
Referenced by GetWardenModuleDirectory(), and loadConfigSettings().
The documentation for this class was generated from the following files:
config.hpp
config.cpp