CMaNGOS_WoTLK: BattleGroundBroadcastBuilder Class Reference
BattleGroundBroadcastBuilder Class Reference
Public Member Functions
BattleGroundBroadcastBuilder (BroadcastText const *bcd, ChatMsg msgtype, Creature const *source, Unit const *target)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
ChatMsg i_msgtype
Creature const * i_source
BroadcastText const * i_bcd
Unit const * i_target
Detailed Description
Definition at line 194 of file war_effort.cpp.
Constructor & Destructor Documentation
BattleGroundBroadcastBuilder()
BattleGroundBroadcastBuilder::BattleGroundBroadcastBuilder (BroadcastText const * bcd, ChatMsg msgtype, Creature const * source, Unit const * target) inline
Definition at line 197 of file war_effort.cpp.
Member Function Documentation
operator()()
void BattleGroundBroadcastBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 199 of file war_effort.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, GENDER_NONE, Unit::getGender(), WorldObject::GetName(), Object::GetObjectGuid(), BroadcastText::GetText(), i_bcd, i_msgtype, i_source, i_target, and BroadcastText::languageId.
Field Documentation
i_bcd
BroadcastText const* BattleGroundBroadcastBuilder::i_bcd private
Definition at line 206 of file war_effort.cpp.
Referenced by operator()().
i_msgtype
ChatMsg BattleGroundBroadcastBuilder::i_msgtype private
Definition at line 204 of file war_effort.cpp.
Referenced by operator()().
i_source
Creature const* BattleGroundBroadcastBuilder::i_source private
Definition at line 205 of file war_effort.cpp.
Referenced by operator()().
i_target
Unit const* BattleGroundBroadcastBuilder::i_target private
Definition at line 207 of file war_effort.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
war_effort.cpp