CMaNGOS_WoTLK: SARC4 Class Reference
SARC4 Class Reference
#include <SARC4.h>
Public Member Functions
SARC4 (size_t len)
SARC4 (const uint8 *seed, size_t len)
~SARC4 ()
void Init (const uint8 *seed)
void UpdateData (uint8 *data, size_t len)
Private Attributes
EVP_CIPHER_CTX * m_ctx
Detailed Description
Definition at line 25 of file SARC4.h.
Constructor & Destructor Documentation
SARC4() [1/2]
SARC4::SARC4 (size_t len)
Definition at line 21 of file SARC4.cpp.
References m_ctx.
SARC4() [2/2]
SARC4::SARC4 (const uint8 * seed, size_t len)
Definition at line 28 of file SARC4.cpp.
References m_ctx.
~SARC4()
SARC4::~SARC4 ()
Definition at line 36 of file SARC4.cpp.
References m_ctx.
Member Function Documentation
Init()
void SARC4::Init (const uint8 * seed)
Definition at line 41 of file SARC4.cpp.
References m_ctx.
Referenced by Warden::HandleChallengeResponse(), AuthCrypt::Init(), and Warden::Warden().
UpdateData()
void SARC4::UpdateData (uint8 * data, size_t len)
Definition at line 46 of file SARC4.cpp.
References m_ctx.
Referenced by Warden::DecryptData(), AuthCrypt::DecryptRecv(), Warden::EncryptData(), AuthCrypt::EncryptSend(), and AuthCrypt::Init().
Field Documentation
m_ctx
EVP_CIPHER_CTX* SARC4::m_ctx private
Definition at line 36 of file SARC4.h.
Referenced by Init(), SARC4(), UpdateData(), and ~SARC4().
The documentation for this class was generated from the following files:
SARC4.h
SARC4.cpp