CMaNGOS_WoTLK: BattleGroundSA Class Reference
BattleGroundSA Class Reference
#include <BattleGroundSA.h>
Public Member Functions
BattleGroundSA ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *player) override
Method that is called when adding a player to the battleground.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
void HandleCreatureCreate (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
void HandlePlayerClickedOnFlag (Player *player, GameObject *go) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleKillUnit (Creature *unit, Player *killer) override
void HandleGameObjectDamaged (Player *player, GameObject *object, uint32 spellId) override
bool IsConditionFulfilled (Player const *source, uint32 conditionId, WorldObject const *conditionSource, uint32 conditionSourceType) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target, uint32 miscvalue1) override
void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual bool HandleAreaTrigger (Player *, uint32)
virtual void HandleKillPlayer (Player *, Player *)
Method that handles killing players.
virtual void HandlePlayerDroppedFlag (Player *)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual Team GetPrematureWinner ()
Function that returns the premature winner.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
Private Member Functions
void UpdateTimerWorldState ()
void ProcessBattlegroundWinner ()
void SendBattlegroundWarning (int32 messageId)
void ChangeBannerState (uint8 nodeId)
void AwardBonusHonor ()
void SetupBattleground (bool initialSetup)
void EnableDemolishers ()
void SetupGraveyards ()
void TeleportPlayerToStartArea (Player *player)
PvpTeamIndex GetAttacker ()
void SetDefender (PvpTeamIndex teamIndex)
Private Attributes
PvpTeamIndex m_defendingTeamIdx
StrandGraveyardNode m_strandGraveyard [BG_SA_MAX_GRAVEYARDS]
bool m_initialSetup
bool m_noScratchAchiev
bool m_defenseAncients
bool m_defenseLineCaptured [BG_SA_MAX_DEFENSE_LINES]
uint32 m_gateStateValue [BG_SA_MAX_GATES]
uint32 m_winTime [PVP_TEAM_COUNT]
uint32 m_battleRoundTimer
uint32 m_boatStartTimer
uint8 m_scoreCount [PVP_TEAM_COUNT]
uint8 m_battleStage
ObjectGuid m_battlegroundMasterGuid
uint32 m_defenderTeleportStalkerGuid
ObjectGuid m_riggerGuid
ObjectGuid m_gorgrilGuid
ObjectGuid m_relicGuid [PVP_TEAM_COUNT]
std::set< uint32 > m_cannonsGuids
std::set< uint32 > m_demolishersGuids
GuidList m_tempDemolishersGuids
std::set< uint32 > m_gatesGuids
std::set< uint32 > m_attackerTeleportStalkersGuids
std::set< uint32 > m_triggerGuids
std::set< uint32 > m_transportShipGuids [PVP_TEAM_COUNT]
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 357 of file BattleGroundSA.h.
Constructor & Destructor Documentation
BattleGroundSA()
BattleGroundSA::BattleGroundSA ()
Definition at line 27 of file BattleGroundSA.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_SA_START_HALF_MINUTE, LANG_BG_SA_START_ONE_MINUTE, LANG_BG_SA_START_TWO_MINUTES, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundSA::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 261 of file BattleGroundSA.cpp.
References BattleGround::AddPlayer(), Object::GetObjectGuid(), m_initialSetup, BattleGround::m_playerScores, and SetupBattleground().
AlterTeleportLocation()
void BattleGroundSA::AlterTeleportLocation (Player * player, ObjectGuid & transportGuid, float & x, float & y, float & z, float & ori) override virtual
Reimplemented from BattleGround.
Definition at line 897 of file BattleGroundSA.cpp.
References ALLIANCE, BG_SA_SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, BG_SA_SPELL_HORDE_CONTROL_PHASE_SHIFT, Unit::CastSpell(), GetAttacker(), BattleGround::GetBgMap(), Player::GetTeam(), GetTeamIndexByTeamId(), TEAM_INDEX_ALLIANCE, TRIGGERED_OLD_TRIGGERED, and urand().
AwardBonusHonor()
void BattleGroundSA::AwardBonusHonor () private
Definition at line 711 of file BattleGroundSA.cpp.
References BG_SA_MAX_DEFENSE_LINES, GetAttacker(), BattleGround::GetBonusHonorFromKill(), GetTeamIdByTeamIndex(), m_defendingTeamIdx, m_defenseLineCaptured, and BattleGround::RewardHonorToTeam().
Referenced by ProcessBattlegroundWinner(), and Update().
ChangeBannerState()
void BattleGroundSA::ChangeBannerState (uint8 nodeId) private
Definition at line 732 of file BattleGroundSA.cpp.
References GAMEOBJECT_FLAGS, BattleGround::GetSingleGameObjectFromStorage(), GO_FLAG_NO_INTERACT, GO_JUST_DEACTIVATED, m_strandGraveyard, and MINUTE.
Referenced by Update().
CheckAchievementCriteriaMeet()
bool BattleGroundSA::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 875 of file BattleGroundSA.cpp.
References BG_SA_CRIT_ARTILLERY_EXPERT, BG_SA_CRIT_ARTILLERY_VETERAN, BG_SA_CRIT_DEFENSE_ANCIENTS_ALLY, BG_SA_CRIT_DEFENSE_ANCIENTS_HORDE, BG_SA_CRIT_DROP_IT, BG_SA_CRIT_DROP_IT_NOW, BG_SA_CRIT_NOT_A_SCRATCH_ALLY, BG_SA_CRIT_NOT_A_SCRATCH_HORDE, BG_SA_SPELL_CARRY_SEAFORIUM, BG_SA_VEHICLE_CANNON, Object::GetEntry(), Player::GetTeam(), GetTeamIndexByTeamId(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Unit::HasAura(), WorldObject::IsBoarded(), m_defendingTeamIdx, m_defenseAncients, and m_noScratchAchiev.
EnableDemolishers()
void BattleGroundSA::EnableDemolishers () private
Definition at line 322 of file BattleGroundSA.cpp.
References GetAttacker(), BattleGround::GetBgMap(), m_defenseAncients, m_demolishersGuids, m_noScratchAchiev, sotaTeamFactions, and TEMPFACTION_TOGGLE_NOT_SELECTABLE.
Referenced by StartingEventOpenDoors(), and Update().
EndBattleGround()
void BattleGroundSA::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 657 of file BattleGroundSA.cpp.
References ALLIANCE, BattleGround::EndBattleGround(), BattleGround::GetBonusHonorFromKill(), HORDE, and BattleGround::RewardHonorToTeam().
Referenced by ProcessBattlegroundWinner().
GetAttacker()
PvpTeamIndex BattleGroundSA::GetAttacker () inline private
Definition at line 405 of file BattleGroundSA.h.
References m_defendingTeamIdx, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by AlterTeleportLocation(), AwardBonusHonor(), EnableDemolishers(), HandleCreatureCreate(), HandleEvent(), HandlePlayerClickedOnFlag(), SetupBattleground(), SetupGraveyards(), StartingEventOpenDoors(), TeleportPlayerToStartArea(), and Update().
HandleCreatureCreate()
void BattleGroundSA::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from BattleGround.
Definition at line 368 of file BattleGroundSA.cpp.
References BG_SA_NPC_GORGRIL_RIGSPARK, BG_SA_NPC_INVISIBLE_STALKER, BG_SA_NPC_KANRETHAD, BG_SA_NPC_RIGGER_SPARKLIGHT, BG_SA_NPC_WORLD_TRIGGER, BG_SA_VEHICLE_CANNON, BG_SA_VEHICLE_DEMOLISHER, GetAttacker(), Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_attackerTeleportStalkersGuids, m_battlegroundMasterGuid, m_cannonsGuids, m_defenderTeleportStalkerGuid, m_demolishersGuids, m_gorgrilGuid, m_riggerGuid, m_tempDemolishersGuids, m_triggerGuids, Creature::SetFactionTemporary(), sotaTeamFactions, and TEMPFACTION_TOGGLE_NOT_SELECTABLE.
HandleEvent()
bool BattleGroundSA::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from BattleGround.
Definition at line 460 of file BattleGroundSA.cpp.
References ALLIANCE, BG_SA_EVENT_ID_RELIC, BG_SA_EVENT_ID_SHIP_PAUSE_1, BG_SA_EVENT_ID_SHIP_PAUSE_2, BG_SA_EVENT_SHRINE_DOOR_DESTROY, BG_SA_GO_GATE_ANCIENT_SHRINE, BG_SA_GO_GATE_BLUE_SAPHIRE, BG_SA_GO_GATE_GREEN_EMERALD, BG_SA_GO_GATE_PURPLE_AMETHYST, BG_SA_GO_GATE_RED_SUN, BG_SA_GO_GATE_YELLOW_MOON, BG_SA_GO_TITAN_RELIC_ALLIANCE, BG_SA_GO_TITAN_RELIC_HORDE, BG_SA_MAX_SIGILS, BG_SA_SOUND_WALL_ATTACKED_ALLIANCE, BG_SA_SOUND_WALL_ATTACKED_HORDE, BG_SA_SOUND_WALL_DESTROYED_ALLIANCE, BG_SA_SOUND_WALL_DESTROYED_HORDE, BG_SA_SPELL_ACHIEV_STORM_BEACH, BG_SA_STAGE_ROUND_1, BG_SA_STAGE_ROUND_2, BG_SA_STATE_VALUE_GATE_DAMAGED, BG_SA_STATE_VALUE_GATE_DESTROYED, BG_SA_STATE_VALUE_GATE_INTACT, BattleGround::CastSpellOnTeam(), BattleGround::ChangeBgObjectSpawnState(), DEBUG_LOG, GAMEOBJECT_FLAGS, GetAttacker(), BattleGround::GetBgMap(), Object::GetEntry(), Map::GetGameObject(), WorldObject::GetMap(), BattleGround::GetSingleGameObjectFromStorage(), Map::GetVariableManager(), GO_FLAG_NO_INTERACT, HORDE, Object::IsGameObject(), Object::IsPlayer(), m_battleRoundTimer, m_battleStage, m_defendingTeamIdx, m_defenseAncients, m_defenseLineCaptured, m_gateStateValue, m_relicGuid, m_scoreCount, m_winTime, BattleGround::PlaySoundToAll(), ProcessBattlegroundWinner(), RESPAWN_ONE_DAY, SCORE_GATES_DESTROYED, SendBattlegroundWarning(), GameObject::SetFaction(), WorldStateVariableManager::SetVariable(), sotaObjectData, sotaTeamFactions, strandSigils, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and UpdatePlayerScore().
HandleGameObjectCreate()
void BattleGroundSA::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 405 of file BattleGroundSA.cpp.
References BG_SA_GO_GATE_ANCIENT_SHRINE, BG_SA_GO_GATE_BLUE_SAPHIRE, BG_SA_GO_GATE_GREEN_EMERALD, BG_SA_GO_GATE_PURPLE_AMETHYST, BG_SA_GO_GATE_RED_SUN, BG_SA_GO_GATE_YELLOW_MOON, BG_SA_GO_GY_FLAG_ALLIANCE_EAST, BG_SA_GO_GY_FLAG_ALLIANCE_SOUTH, BG_SA_GO_GY_FLAG_ALLIANCE_WEST, BG_SA_GO_GY_FLAG_HORDE_EAST, BG_SA_GO_GY_FLAG_HORDE_SOUTH, BG_SA_GO_GY_FLAG_HORDE_WEST, BG_SA_GO_SIGIL_BLUE_MOON, BG_SA_GO_SIGIL_GREEN_MOON, BG_SA_GO_SIGIL_PURPLE_MOON, BG_SA_GO_SIGIL_RED_MOON, BG_SA_GO_SIGIL_YELLOW_MOON, BG_SA_GO_TITAN_RELIC_ALLIANCE, BG_SA_GO_TITAN_RELIC_HORDE, BG_SA_GO_TRANSPORT_SHIP_ALLIANCE_1, BG_SA_GO_TRANSPORT_SHIP_ALLIANCE_2, BG_SA_GO_TRANSPORT_SHIP_HORDE_1, BG_SA_GO_TRANSPORT_SHIP_HORDE_2, Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), m_gatesGuids, BattleGround::m_goEntryGuidStore, m_relicGuid, m_transportShipGuids, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
HandleGameObjectDamaged()
void BattleGroundSA::HandleGameObjectDamaged (Player * player, GameObject * object, uint32 spellId) override virtual
Reimplemented from BattleGround.
Definition at line 869 of file BattleGroundSA.cpp.
References BG_SA_SPELL_ACHIEV_SEAFORIUM_DAMAGE, BG_SA_SPELL_SEAFORIUM_BLAST, Unit::CastSpell(), and TRIGGERED_OLD_TRIGGERED.
HandleKillUnit()
void BattleGroundSA::HandleKillUnit (Creature * unit, Player * killer) override virtual
Reimplemented from BattleGround.
Definition at line 645 of file BattleGroundSA.cpp.
References BG_SA_VEHICLE_DEMOLISHER, Object::GetEntry(), m_noScratchAchiev, SCORE_DEMOLISHERS_DESTROYED, and UpdatePlayerScore().
HandlePlayerClickedOnFlag()
void BattleGroundSA::HandlePlayerClickedOnFlag (Player * player, GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 584 of file BattleGroundSA.cpp.
References BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, BG_SA_GRAVEYARD_ID_EAST, BG_SA_GRAVEYARD_ID_WEST, BG_SA_MAX_GRAVEYARDS, BG_SA_SOUND_GRAVEYARD_TAKEN_ALLIANCE, BG_SA_SOUND_GRAVEYARD_TAKEN_HORDE, BG_SA_ZONE_ID_STRAND, StrandGraveyardNode::changeTimer, DEBUG_LOG, StrandSummonData::entry, GetAttacker(), BattleGround::GetBgMap(), Object::GetEntry(), Map::GetGraveyardManager(), GetTeamIdByTeamIndex(), Map::GetVariableManager(), StrandGraveyardData::goEntryAlliance, StrandGraveyardData::goEntryHorde, StrandGraveyardNode::graveyardOwner, IN_MILLISECONDS, m_strandGraveyard, MINUTE, StrandGraveyardNode::newEntry, StrandSummonData::o, StrandGraveyardSpawnData::o, StrandGraveyardNode::oldEntry, BattleGround::PlaySoundToAll(), SendBattlegroundWarning(), GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), sotaEastSpawns, sotaGraveyardData, sotaWestSpawns, StrandGraveyardNode::spiritHealerGuid, strandGraveyardData, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_OR_CORPSE_DESPAWN, WORLD_STATE_ADD, WORLD_STATE_REMOVE, StrandSummonData::x, StrandGraveyardSpawnData::x, StrandSummonData::y, StrandGraveyardSpawnData::y, StrandSummonData::z, and StrandGraveyardSpawnData::z.
IsConditionFulfilled()
bool BattleGroundSA::IsConditionFulfilled (Player const * source, uint32 conditionId, WorldObject const * conditionSource, uint32 conditionSourceType) override virtual
Reimplemented from BattleGround.
Definition at line 936 of file BattleGroundSA.cpp.
References BG_SA_COND_DEFENDER_ALLIANCE, BG_SA_COND_DEFENDER_HORDE, m_defendingTeamIdx, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
ProcessBattlegroundWinner()
void BattleGroundSA::ProcessBattlegroundWinner () private
Definition at line 670 of file BattleGroundSA.cpp.
References ALLIANCE, AwardBonusHonor(), BG_SA_SOUND_DEFEAT_ALLIANCE, BG_SA_SOUND_DEFEAT_HORDE, BG_SA_SOUND_VICTORY_ALLIANCE, BG_SA_SOUND_VICTORY_HORDE, BattleGround::CastSpellOnTeam(), DEBUG_LOG, EndBattleGround(), HORDE, m_scoreCount, m_winTime, BattleGround::PlaySoundToTeam(), SPELL_PREPARATION, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and TEAM_NONE.
Referenced by HandleEvent(), and Update().
Reset()
void BattleGroundSA::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 36 of file BattleGroundSA.cpp.
References BG_SA_STATE_ANCIENT_GATE, BG_SA_STATE_ATTACKER_ALLIANCE, BG_SA_STATE_ATTACKER_HORDE, BG_SA_STATE_BLUE_GATE, BG_SA_STATE_BONUS_TIMER, BG_SA_STATE_DEFENSE_TOKEN_ALLIANCE, BG_SA_STATE_DEFENSE_TOKEN_HORDE, BG_SA_STATE_ENABLE_TIMER, BG_SA_STATE_GREEN_GATE, BG_SA_STATE_GY_CENTER_ALLIANCE, BG_SA_STATE_GY_CENTER_HORDE, BG_SA_STATE_GY_LEFT_ALLIANCE, BG_SA_STATE_GY_LEFT_HORDE, BG_SA_STATE_GY_RIGHT_ALLIANCE, BG_SA_STATE_GY_RIGHT_HORDE, BG_SA_STATE_LEFT_ATTACK_TOKEN_ALLIANCE, BG_SA_STATE_LEFT_ATTACK_TOKEN_HORDE, BG_SA_STATE_PURPLE_GATE, BG_SA_STATE_RED_GATE, BG_SA_STATE_RIGHT_ATTACK_TOKEN_ALLIANCE, BG_SA_STATE_RIGHT_ATTACK_TOKEN_HORDE, BG_SA_STATE_TIMER_MINUTES, BG_SA_STATE_TIMER_SEC_FIRST_DIGIT, BG_SA_STATE_TIMER_SEC_SECOND_DIGIT, BG_SA_STATE_YELLOW_GATE, BG_SA_TIMER_BOAT_START, BG_SA_TIMER_ROUND_LENGTH, BattleGround::GetBgMap(), Map::GetVariableManager(), m_battleRoundTimer, m_boatStartTimer, m_scoreCount, m_winTime, PVP_TEAM_COUNT, BattleGround::Reset(), SetDefender(), WorldStateVariableManager::SetVariableData(), and TEAM_INDEX_HORDE.
SendBattlegroundWarning()
void BattleGroundSA::SendBattlegroundWarning (int32 messageId) private
Definition at line 858 of file BattleGroundSA.cpp.
References CHAT_MSG_RAID_BOSS_EMOTE, BattleGround::GetBgMap(), Map::GetCreature(), Object::GetObjectGuid(), LANG_UNIVERSAL, m_triggerGuids, BattleGround::SendMessageToAll(), and urand().
Referenced by HandleEvent(), HandlePlayerClickedOnFlag(), StartingEventOpenDoors(), and Update().
SetDefender()
void BattleGroundSA::SetDefender (PvpTeamIndex teamIndex) private
Definition at line 295 of file BattleGroundSA.cpp.
References BG_SA_STATE_ATTACKER_ALLIANCE, BG_SA_STATE_ATTACKER_HORDE, BG_SA_STATE_DEFENSE_TOKEN_ALLIANCE, BG_SA_STATE_DEFENSE_TOKEN_HORDE, BG_SA_STATE_LEFT_ATTACK_TOKEN_ALLIANCE, BG_SA_STATE_LEFT_ATTACK_TOKEN_HORDE, BG_SA_STATE_RIGHT_ATTACK_TOKEN_ALLIANCE, BG_SA_STATE_RIGHT_ATTACK_TOKEN_HORDE, BattleGround::GetBgMap(), BattleGround::GetOtherTeamIndex(), Map::GetVariableManager(), m_defendingTeamIdx, WorldStateVariableManager::SetVariable(), TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by Reset(), and Update().
SetupBattleground()
void BattleGroundSA::SetupBattleground (bool initialSetup) private
Definition at line 746 of file BattleGroundSA.cpp.
References BG_SA_GRAVEYARD_ID_BEACH, BG_SA_GRAVEYARD_ID_SHIP, BG_SA_GRAVEYARD_ID_SHRINE, BG_SA_MAX_DEFENSE_LINES, BG_SA_MAX_GATES, BG_SA_MAX_GRAVEYARDS, BG_SA_MAX_SIGILS, BG_SA_STATE_VALUE_GATE_INTACT, BG_SA_ZONE_ID_STRAND, BattleGround::ChangeBgObjectSpawnState(), StrandGraveyardNode::changeTimer, DEBUG_LOG, GAMEOBJECT_FLAGS, GetAttacker(), BattleGround::GetBgMap(), Map::GetGraveyardManager(), BattleGround::GetSingleGameObjectFromStorage(), GetTeamIdByTeamIndex(), Map::GetVariableManager(), GO_FLAG_NO_INTERACT, StrandGraveyardData::goEntryAlliance, StrandGraveyardData::goEntryHorde, StrandGraveyardNode::graveyardOwner, m_battlegroundMasterGuid, m_battleStage, m_cannonsGuids, m_defendingTeamIdx, m_defenseLineCaptured, m_demolishersGuids, m_gatesGuids, m_gateStateValue, m_gorgrilGuid, m_riggerGuid, m_strandGraveyard, RESPAWN_IMMEDIATELY, RESPAWN_ONE_DAY, GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), sotaGraveyardData, sotaTeamFactions, strandGates, strandSigils, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and TEMPFACTION_NONE.
Referenced by AddPlayer(), and Update().
SetupGraveyards()
void BattleGroundSA::SetupGraveyards () private
Definition at line 334 of file BattleGroundSA.cpp.
References BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, BG_SA_MAX_GRAVEYARDS, GetAttacker(), BattleGround::GetBgMap(), Map::GetCreature(), m_battlegroundMasterGuid, m_strandGraveyard, StrandGraveyardSpawnData::o, StrandGraveyardNode::spiritHealerGuid, strandGraveyardData, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEMPSPAWN_DEAD_DESPAWN, StrandGraveyardSpawnData::x, StrandGraveyardSpawnData::y, and StrandGraveyardSpawnData::z.
Referenced by StartingEventOpenDoors().
StartingEventOpenDoors()
void BattleGroundSA::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 311 of file BattleGroundSA.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, BG_SA_ACHIEV_START_ID_STORM_BEACH_ALLY, BG_SA_ACHIEV_START_ID_STORM_BEACH_HORDE, BG_SA_STATE_ENABLE_TIMER, EnableDemolishers(), GetAttacker(), BattleGround::GetBgMap(), Map::GetVariableManager(), LANG_BG_SA_BEGIN, SendBattlegroundWarning(), SetupGraveyards(), WorldStateVariableManager::SetVariable(), BattleGround::StartTimedAchievement(), TEAM_INDEX_ALLIANCE, and WORLD_STATE_ADD.
TeleportPlayerToStartArea()
void BattleGroundSA::TeleportPlayerToStartArea (Player * player) private
Definition at line 280 of file BattleGroundSA.cpp.
References ALLIANCE, BG_SA_SPELL_SPLIT_TELEPORT_A_BOAT1, BG_SA_SPELL_SPLIT_TELEPORT_A_BOAT2, BG_SA_SPELL_SPLIT_TELEPORT_H_BOAT1, BG_SA_SPELL_SPLIT_TELEPORT_H_BOAT2, BG_SA_SPELL_TELEPORT_DEFENDER, Unit::CastSpell(), GetAttacker(), Player::GetTeam(), GetTeamIndexByTeamId(), TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by Update().
Update()
void BattleGroundSA::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 83 of file BattleGroundSA.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ALLIANCE, AwardBonusHonor(), BG_SA_ACHIEV_START_ID_STORM_BEACH_ALLY, BG_SA_ACHIEV_START_ID_STORM_BEACH_HORDE, BG_SA_MAX_GRAVEYARDS, BG_SA_SPELL_ALLIANCE_CONTROL_PHASE_SHIFT, BG_SA_SPELL_END_OF_ROUND, BG_SA_SPELL_HORDE_CONTROL_PHASE_SHIFT, BG_SA_STAGE_RESET, BG_SA_STAGE_ROUND_1, BG_SA_STAGE_ROUND_2, BG_SA_STAGE_SECOND_ROUND_1, BG_SA_STAGE_SECOND_ROUND_2, BG_SA_STAGE_SECOND_ROUND_3, BG_SA_STATE_ENABLE_TIMER, BG_SA_TIMER_ROUND_LENGTH, Unit::CastSpell(), BattleGround::CastSpellOnTeam(), ChangeBannerState(), StrandGraveyardNode::changeTimer, CHAT_MSG_BG_SYSTEM_NEUTRAL, EnableDemolishers(), GetAttacker(), BattleGround::GetBgMap(), BattleGround::GetStatus(), Map::GetVariableManager(), GO_STATE_ACTIVE, HORDE, LANG_BG_SA_BEGIN, LANG_BG_SA_ROUND_FINISHED, LANG_BG_SA_ROUND_START_HALF_MINUTE, LANG_BG_SA_ROUND_START_ONE_MINUTE, m_battleRoundTimer, m_battleStage, m_boatStartTimer, m_cannonsGuids, m_defendingTeamIdx, m_demolishersGuids, BattleGround::m_players, m_strandGraveyard, m_tempDemolishersGuids, m_transportShipGuids, ProcessBattlegroundWinner(), SendBattlegroundWarning(), BattleGround::SendMessageToAll(), SetDefender(), SetupBattleground(), WorldStateVariableManager::SetVariable(), sObjectMgr, sotaTeamFactions, SPELL_AURA_CONTROL_VEHICLE, SPELL_PREPARATION, BattleGround::StartTimedAchievement(), STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TeleportPlayerToStartArea(), TEMPFACTION_NONE, TRIGGERED_OLD_TRIGGERED, BattleGround::Update(), UpdateTimerWorldState(), WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
UpdatePlayerScore()
void BattleGroundSA::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 348 of file BattleGroundSA.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_DEMOLISHERS_DESTROYED, SCORE_GATES_DESTROYED, and BattleGround::UpdatePlayerScore().
Referenced by HandleEvent(), and HandleKillUnit().
UpdateTimerWorldState()
void BattleGroundSA::UpdateTimerWorldState () private
Definition at line 448 of file BattleGroundSA.cpp.
References BG_SA_STATE_ENABLE_TIMER, BG_SA_STATE_TIMER_MINUTES, BG_SA_STATE_TIMER_SEC_FIRST_DIGIT, BG_SA_STATE_TIMER_SEC_SECOND_DIGIT, BattleGround::GetBgMap(), Map::GetVariableManager(), m_battleRoundTimer, WorldStateVariableManager::SetVariable(), and WORLD_STATE_ADD.
Referenced by Update().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 359 of file BattleGroundSA.h.
Field Documentation
m_attackerTeleportStalkersGuids
std::set<uint32> BattleGroundSA::m_attackerTeleportStalkersGuids private
Definition at line 435 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate().
m_battlegroundMasterGuid
ObjectGuid BattleGroundSA::m_battlegroundMasterGuid private
Definition at line 424 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), SetupBattleground(), and SetupGraveyards().
m_battleRoundTimer
uint32 BattleGroundSA::m_battleRoundTimer private
Definition at line 418 of file BattleGroundSA.h.
Referenced by HandleEvent(), Reset(), Update(), and UpdateTimerWorldState().
m_battleStage
uint8 BattleGroundSA::m_battleStage private
Definition at line 421 of file BattleGroundSA.h.
Referenced by HandleEvent(), SetupBattleground(), and Update().
m_boatStartTimer
uint32 BattleGroundSA::m_boatStartTimer private
Definition at line 419 of file BattleGroundSA.h.
Referenced by Reset(), and Update().
m_cannonsGuids
std::set<uint32> BattleGroundSA::m_cannonsGuids private
Definition at line 431 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), SetupBattleground(), and Update().
m_defenderTeleportStalkerGuid
uint32 BattleGroundSA::m_defenderTeleportStalkerGuid private
Definition at line 425 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate().
m_defendingTeamIdx
PvpTeamIndex BattleGroundSA::m_defendingTeamIdx private
Definition at line 407 of file BattleGroundSA.h.
Referenced by AwardBonusHonor(), CheckAchievementCriteriaMeet(), GetAttacker(), HandleEvent(), IsConditionFulfilled(), SetDefender(), SetupBattleground(), and Update().
m_defenseAncients
bool BattleGroundSA::m_defenseAncients private
Definition at line 413 of file BattleGroundSA.h.
Referenced by CheckAchievementCriteriaMeet(), EnableDemolishers(), and HandleEvent().
m_defenseLineCaptured
bool BattleGroundSA::m_defenseLineCaptured[BG_SA_MAX_DEFENSE_LINES] private
Definition at line 414 of file BattleGroundSA.h.
Referenced by AwardBonusHonor(), HandleEvent(), and SetupBattleground().
m_demolishersGuids
std::set<uint32> BattleGroundSA::m_demolishersGuids private
Definition at line 432 of file BattleGroundSA.h.
Referenced by EnableDemolishers(), HandleCreatureCreate(), SetupBattleground(), and Update().
m_gatesGuids
std::set<uint32> BattleGroundSA::m_gatesGuids private
Definition at line 434 of file BattleGroundSA.h.
Referenced by HandleGameObjectCreate(), and SetupBattleground().
m_gateStateValue
uint32 BattleGroundSA::m_gateStateValue[BG_SA_MAX_GATES] private
Definition at line 416 of file BattleGroundSA.h.
Referenced by HandleEvent(), and SetupBattleground().
m_gorgrilGuid
ObjectGuid BattleGroundSA::m_gorgrilGuid private
Definition at line 427 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), and SetupBattleground().
m_initialSetup
bool BattleGroundSA::m_initialSetup private
Definition at line 411 of file BattleGroundSA.h.
Referenced by AddPlayer().
m_noScratchAchiev
bool BattleGroundSA::m_noScratchAchiev private
Definition at line 412 of file BattleGroundSA.h.
Referenced by CheckAchievementCriteriaMeet(), EnableDemolishers(), and HandleKillUnit().
m_relicGuid
ObjectGuid BattleGroundSA::m_relicGuid[PVP_TEAM_COUNT] private
Definition at line 428 of file BattleGroundSA.h.
Referenced by HandleEvent(), and HandleGameObjectCreate().
m_riggerGuid
ObjectGuid BattleGroundSA::m_riggerGuid private
Definition at line 426 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), and SetupBattleground().
m_scoreCount
uint8 BattleGroundSA::m_scoreCount[PVP_TEAM_COUNT] private
Definition at line 420 of file BattleGroundSA.h.
Referenced by HandleEvent(), ProcessBattlegroundWinner(), and Reset().
m_strandGraveyard
StrandGraveyardNode BattleGroundSA::m_strandGraveyard[BG_SA_MAX_GRAVEYARDS] private
Definition at line 409 of file BattleGroundSA.h.
Referenced by ChangeBannerState(), HandlePlayerClickedOnFlag(), SetupBattleground(), SetupGraveyards(), and Update().
m_tempDemolishersGuids
GuidList BattleGroundSA::m_tempDemolishersGuids private
Definition at line 433 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), and Update().
m_transportShipGuids
std::set<uint32> BattleGroundSA::m_transportShipGuids[PVP_TEAM_COUNT] private
Definition at line 437 of file BattleGroundSA.h.
Referenced by HandleGameObjectCreate(), and Update().
m_triggerGuids
std::set<uint32> BattleGroundSA::m_triggerGuids private
Definition at line 436 of file BattleGroundSA.h.
Referenced by HandleCreatureCreate(), and SendBattlegroundWarning().
m_winTime
uint32 BattleGroundSA::m_winTime[PVP_TEAM_COUNT] private
Definition at line 417 of file BattleGroundSA.h.
Referenced by HandleEvent(), ProcessBattlegroundWinner(), and Reset().
The documentation for this class was generated from the following files:
BattleGroundSA.h
BattleGroundSA.cpp