CMaNGOS_WoTLK: WorldObject Class Reference
WorldObject Class Reference abstract
#include <Object.h>
Public Member Functions
virtual ~WorldObject ()
virtual void Update (const uint32)
virtual void Heartbeat ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetObjectBoundingRadius () const
virtual float GetCombatReach () const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
virtual void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const
virtual void AdjustZForCollision (float, float, float &, float) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
virtual const char * GetNameForLocaleIdx (int32) const
virtual ObjectGuid const & GetOwnerGuid () const
virtual void SetOwnerGuid (ObjectGuid)
virtual ObjectGuid const GetSpawnerGuid () const
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void CleanupsBeforeDelete ()
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
virtual ReputationRank GetReactionTo (Unit const *unit) const
[Serverside] Get default WorldObject (hierarchy) reaction to a unit
virtual ReputationRank GetReactionTo (Corpse const *corpse) const
[Serverside] Get default WorldObject (hierarchy) reaction to a corpse
virtual bool IsEnemy (Unit const *unit) const
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as an enemy
virtual bool IsFriend (Unit const *unit) const
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as a friend
bool IsControlledByPlayer () const
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
virtual void UpdateVisibilityAndView ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
virtual bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const =0
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
virtual void OnEventHappened (uint16, bool, bool)
void SetNotifyOnEventState (bool state)
virtual void AddToWorld () override
virtual void RemoveFromWorld () override
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
virtual void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration)
void PrintCooldownList (ChatHandler &chat) const
virtual void InspectingLoot ()
virtual bool CanAttackSpell (Unit const *, SpellEntry const *=nullptr, bool=false) const
virtual bool CanAssistSpell (Unit const *, SpellEntry const *=nullptr) const
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
virtual HighGuid GetParentHigh () const
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
virtual uint32 GetLevel () const
virtual uint32 GetFaction () const
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
virtual bool HasQuest (uint32) const
virtual bool HasInvolvedQuest (uint32) const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Static Public Member Functions
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Data Fields
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Protected Member Functions
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Private Attributes
Map * m_currMap
uint32 m_mapId
uint32 m_InstanceId
uint32 m_phaseMask
Position m_position
ViewPoint m_viewPoint
bool m_isActiveObject
uint64 m_debugFlags
GuidSet m_clientGUIDsIAmAt
uint8 m_destLocCounter
uint32 m_castCounter
std::set< uint32 > m_stringIds
Friends
struct WorldObjectChangeAccumulator
Detailed Description
Definition at line 946 of file Object.h.
Constructor & Destructor Documentation
~WorldObject()
virtual WorldObject::~WorldObject () inline virtual
Definition at line 951 of file Object.h.
WorldObject()
WorldObject::WorldObject () explicit protected
Definition at line 1332 of file Object.cpp.
Member Function Documentation
_Create()
void WorldObject::_Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
Definition at line 1356 of file Object.cpp.
References Object::_Create(), and m_phaseMask.
Referenced by Corpse::Create(), and DynamicObject::Create().
_IsWithinCombatDist()
bool WorldObject::_IsWithinCombatDist (WorldObject const * obj, float dist2compare, bool is3D) const
Definition at line 1534 of file Object.cpp.
References DIST_CALC_NONE, GetCombinedCombatReach(), and GetDistance().
Referenced by IsWithinCombatDist(), and IsWithinCombatDistInMap().
_IsWithinDist()
bool WorldObject::_IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D) const virtual
Reimplemented in GameObject.
Definition at line 1525 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), and GetDistance().
Referenced by IsWithinDist(), and IsWithinDistInMap().
AddClientIAmAt()
void WorldObject::AddClientIAmAt (Player const * player)
Definition at line 3299 of file Object.cpp.
References Object::GetObjectGuid(), and m_clientGUIDsIAmAt.
Referenced by Player::AddAtClient().
AddCooldown()
void WorldObject::AddCooldown (SpellEntry const & spellEntry, ItemPrototype const * itemProto = nullptr, bool permanent = false, uint32 forcedDuration = 0, bool ignoreCat = false) virtual
Reimplemented in Player, and Creature.
Definition at line 2776 of file Object.cpp.
References CooldownContainer::AddCooldown(), SpellEntry::Category, SpellEntry::CategoryRecoveryTime, GetMap(), SpellEntry::Id, m_cooldownMap, and SpellEntry::RecoveryTime.
Referenced by SpellAuraHolder::_RemoveSpellAuraHolder(), Unit::_UpdateAutoRepeatSpell(), Unit::AddGameObject(), UnitAI::AddInitialCooldowns(), Unit::CalculateDamageAbsorbAndResist(), Unit::RemoveGameObject(), Spell::SendSpellCooldown(), and Creature::StartCooldown().
AddGCD()
void WorldObject::AddGCD (SpellEntry const & spellEntry, uint32 forcedDuration = 0, bool updateClient = false) virtual
Reimplemented in Player.
Definition at line 2745 of file Object.cpp.
References GetMap(), m_GCDCatMap, SpellEntry::StartRecoveryCategory, and SpellEntry::StartRecoveryTime.
Referenced by Player::AddGCD(), DarknessOfSouls::OnApply(), and Spell::Prepare().
AddObjectToRemoveList()
void WorldObject::AddObjectToRemoveList ()
Definition at line 2161 of file Object.cpp.
References Map::AddObjectToRemoveList(), and GetMap().
Referenced by DynamicObject::Delete(), GameObject::Delete(), Corpse::DeleteBonesFromWorld(), CinematicMgr::EndCinematic(), ChatHandler::HandleNpcDeleteCommand(), Creature::RemoveCorpse(), Transport::TeleportTransport(), TemporarySpawn::UnSummon(), Totem::UnSummon(), Pet::Unsummon(), and GameObject::Update().
AddStringId()
void WorldObject::AddStringId (std::string & stringId)
Definition at line 1308 of file Object.cpp.
References GetMap(), Map::GetMapDataContainer(), MapDataContainer::GetStringId(), and SetStringId().
AddToClientUpdateList()
void WorldObject::AddToClientUpdateList () override virtual
Reimplemented from Object.
Definition at line 2645 of file Object.cpp.
References Map::AddUpdateObject(), and GetMap().
AddToWorld()
void WorldObject::AddToWorld () override virtual
Reimplemented from Object.
Reimplemented in Unit, Player, Pet, GameObject, DynamicObject, Creature, and Corpse.
Definition at line 2128 of file Object.cpp.
References Map::AddStringIdObject(), Map::AddToOnEventNotified(), Object::AddToWorld(), m_currMap, m_isOnEventNotified, and m_stringIds.
Referenced by Corpse::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), and Unit::AddToWorld().
AdjustZForCollision()
virtual void WorldObject::AdjustZForCollision (float , float , float & , float) const inline virtual
Reimplemented in Unit.
Definition at line 1031 of file Object.h.
Referenced by MovePositionToFirstCollision().
BuildUpdateData()
void WorldObject::BuildUpdateData (UpdateDataMapType & update_players) override virtual
Reimplemented from Object.
Definition at line 2680 of file Object.cpp.
References Object::ClearUpdateMask(), GetVisibilityData(), and Cell::VisitWorldObjects().
CalculateSpellEffectValue()
int32 WorldObject::CalculateSpellEffectValue (Unit const * target, SpellEntry const * spellProto, SpellEffectIndex effect_index, int32 const * basePoints = nullptr, bool maximum = false, bool finalUse = true) const
Definition at line 3118 of file Object.cpp.
References SpellEntry::baseLevel, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectApplyAuraName, SpellEntry::EffectBasePoints, SpellEntry::EffectDieSides, SpellEntry::EffectPointsPerComboPoint, SpellEntry::EffectRealPointsPerLevel, Unit::GetComboPoints(), Unit::GetComboTargetGuid(), Unit::GetLevel(), Object::GetObjectGuid(), GetSpellModOwner(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, irand(), IsOnlySelfTargeting(), SpellEntry::maxLevel, GtNPCManaCostScalerEntry::ratio, sGtNPCManaCostScalerStore, SPELL_ATTR_SCALES_WITH_CREATURE_LEVEL, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_POWER_BURN_MANA, SPELL_AURA_SCHOOL_ABSORB, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_POWER_BURN, SPELL_EFFECT_POWER_DRAIN, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_SUMMON, SPELL_EFFECT_TRIGGER_MISSILE_SPELL_WITH_VALUE, SPELL_EFFECT_TRIGGER_SPELL_WITH_VALUE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, SpellEntry::spellLevel, SPELLMOD_ALL_EFFECTS, SPELLMOD_EFFECT1, SPELLMOD_EFFECT2, SPELLMOD_EFFECT3, and TYPEID_PLAYER.
Referenced by PlayerbotAI::Buff(), Spell::CalculateSpellEffectValue(), Spell::EffectSchoolDMG(), GameObject::GetSpellForLock(), Aura::HandleAuraModShapeshift(), Unit::HandleDummyAuraProc(), InebriateRemoval::OnApply(), LavaLash::OnEffectExecute(), ShadowBite::OnEffectExecute(), ShredDruid::OnHit(), Aura::PeriodicDummyTick(), Aura::PeriodicTick(), Spell::ProcSpellAuraTriggers(), Unit::SpellDamageBonusDone(), and AreaAura::Update().
CanAssistSpell()
virtual bool WorldObject::CanAssistSpell (Unit const * , SpellEntry const * = nullptr) const inline virtual
Reimplemented in Unit, GameObject, and DynamicObject.
Definition at line 1223 of file Object.h.
Referenced by Spell::CheckCast(), Spell::GetMinMaxRange(), MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::operator()(), MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::operator()(), Spell::SetTargetMap(), and MaNGOS::SpellNotifierCreatureAndPlayer::Visit().
CanAttackSpell()
virtual bool WorldObject::CanAttackSpell (Unit const * , SpellEntry const * = nullptr, bool = false) const inline virtual
Reimplemented in Unit, GameObject, and DynamicObject.
Definition at line 1222 of file Object.h.
Referenced by Spell::CheckCast(), Spell::DoSpellHitOnUnit(), MaNGOS::AnyAoETargetUnitInObjectRangeCheck::operator()(), MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), MaNGOS::SpellNotifierCreatureAndPlayer::Visit(), and MaNGOS::SpellNotifierPlayer::Visit().
CheckAndIncreaseCastCounter()
bool WorldObject::CheckAndIncreaseCastCounter ()
Definition at line 3309 of file Object.cpp.
References CONFIG_UINT32_MAX_SPELL_CASTS_IN_CHAIN, m_castCounter, and sWorld.
Referenced by Spell::cast().
CheckLockout()
bool WorldObject::CheckLockout (SpellSchoolMask schoolMask, TimePoint const & now) const protected
Definition at line 2811 of file Object.cpp.
References m_lockoutMap.
Referenced by IsSpellReady().
CleanupsBeforeDelete()
void WorldObject::CleanupsBeforeDelete () virtual
Reimplemented in Unit, Player, and Creature.
Definition at line 1340 of file Object.cpp.
References EventProcessor::KillAllEvents(), m_events, and RemoveFromWorld().
Referenced by Map::AddObjectToRemoveList(), and Unit::CleanupsBeforeDelete().
ClearDebugFlag()
void WorldObject::ClearDebugFlag (CMDebugFlags flag) inline
Definition at line 1232 of file Object.h.
References m_debugFlags.
Referenced by ChatHandler::HandleDebugObjectFlags().
DecreaseCastCounter()
void WorldObject::DecreaseCastCounter () inline
Definition at line 1272 of file Object.h.
References m_castCounter.
Referenced by Spell::cast(), and Spell::StopCast().
GetAngle() [1/2]
float WorldObject::GetAngle (const WorldObject * obj) const
Definition at line 1666 of file Object.cpp.
References GetAngleAt(), GetPositionX(), and GetPositionY().
GetAngle() [2/2]
float WorldObject::GetAngle (float x, float y) const
Definition at line 1646 of file Object.cpp.
References Position::GetAngle(), and m_position.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), FollowMovementGenerator::_getOrientation(), MaNGOS::NearUsedPosDo::add(), boss_felmystAI::Aggro(), PlayerbotAI::CastPetSpell(), Spell::CheckCast(), CheckPathToTarget(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), UnitAI::DetectOrAttack(), npc_wildaAI::DoFreeSpirits(), CreatureAI::DoRetreat(), boss_kelidan_the_breakerAI::DoSetupAdds(), npc_demoniac_scryerAI::DoSpawnButtress(), boss_grandmaster_vorpilAI::DoTeleportToPlatform(), Spell::EffectActivateObject(), EffectAuraDummy_npc_captured_beryl_sorcerer(), Spell::EffectDistract(), Spell::EffectKnockBackFromPosition(), Spell::EffectPullTowards(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), npc_manaforge_spawnAI::EnterEvadeMode(), npc_bashir_flesh_fiendAI::ExecuteActions(), PlayerbotAI::FaceTarget(), PlayerbotClassAI::FleeFromPointIfCan(), GetContactPoint(), FollowMovementGenerator::GetResetPosition(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), ChatHandler::HandleGonameCommand(), instance_trial_of_the_champion::InformChampionReachHome(), npc_simone_seductressAI::JustReachedHome(), npc_thrall_old_hillsbradAI::JustSummoned(), boss_lord_marrowgarAI::JustSummoned(), boss_doomwalkerAI::JustSummoned(), Unit::KnockBackFrom(), MotionMaster::MoveCharge(), boss_zuljinAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_champion_mountAI::MovementInform(), boss_lady_vashjAI::MovementInform(), UnitAI::OnChannelStateChange(), FlignTorch::OnDestTarget(), FaceHighestThreat::OnEffectExecute(), UnitAI::OnSpellCastStateChange(), ProcessEventId_event_go_focusing_iris(), npc_netherspite_portalAI::ReceiveAIEvent(), npc_infantryAI::ReceiveAIEvent(), Unit::SetInFront(), Spell::SetTargetMap(), npc_ethereum_prisoner_dungeonAI::StartEvent(), npc_spring_rabbitAI::StartWhatRabbitsDo(), trial_companion_commonAI::SummonedMovementInform(), npc_simone_the_inconspicuousAI::Transform(), instance_trial_of_the_champion::Update(), Spell::update(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_netherspite_portalAI::UpdateAI(), boss_devourer_of_soulsAI::UpdateAI(), npc_volatile_ooze_iccAI::UpdateAI(), npc_gas_cloud_iccAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), and Unit::UpdateSplinePosition().
GetAngleAt() [1/2]
float WorldObject::GetAngleAt (float x, float y, const WorldObject * obj) const
Definition at line 1651 of file Object.cpp.
References GetAngleAt(), Object::GetGuidStr(), GetPositionX(), GetPositionY(), and sLog.
GetAngleAt() [2/2]
float WorldObject::GetAngleAt (float x, float y, float ox, float oy) static
Definition at line 1636 of file Object.cpp.
References M_PI_F.
Referenced by GetAngle(), GetAngleAt(), and HasInArcAt().
GetAreaId()
uint32 WorldObject::GetAreaId () const
Definition at line 1396 of file Object.cpp.
References TerrainInfo::GetAreaId(), GetTerrain(), m_position, Position::x, Position::y, and Position::z.
Referenced by npc_giltharesAI::Aggro(), OutdoorPvP::BuffTeam(), BattleGroundWS::CheckAchievementCriteriaMeet(), BattleGroundAV::CheckAchievementCriteriaMeet(), world_map_eastern_kingdoms::CheckConditionCriteriaMeet(), world_map_kalimdor::CheckConditionCriteriaMeet(), world_map_outland::CheckConditionCriteriaMeet(), Spell::EffectBind(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectScriptEffect(), Spell::EffectSpiritHeal(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), go_ai_bell::GetBellSound(), go_ai_bell::GetBellZoneOrArea(), go_brewfest_music::GetZoneAlignment(), GossipHello_go_manaforge(), GossipHello_npc_innkeeper(), GossipSelect_go_manaforge(), Aura::HandleAuraDummy(), WorldSession::HandleHearthandResurrect(), ChatHandler::HandleListAreaTriggerCommand(), ChatHandler::HandleNearGraveCommand(), OutdoorPvPNA::HandlePlayerKillInsideArea(), Unit::IsAllowedDamageInArea(), NamreebAnticheat::Movement::IsTeleportAllowed(), ItemUse_item_petrov_cluster_bombs(), npc_dawnblade_blood_knight::JustRespawned(), npc_the_scourge_cauldronAI::MoveInLineOfSight(), spell_teleporting_dalaran::OnEffectExecute(), go_ai_bell::OnEventHappened(), Player::RepopAtGraveyard(), Player::RewardHonor(), Player::SendInitialPacketsBeforeAddToMap(), npc_orphan_matronAI::SummonShadeOfTheHorseman(), go_ai_bell::UpdateAI(), Creature::UpdateEntry(), and npc_scrap_reaverAI::UpdateTimers().
GetAreaName()
AreaNameInfo WorldObject::GetAreaName (LocaleConstant locale) const
Definition at line 1401 of file Object.cpp.
References TerrainInfo::GetAreaName(), GetTerrain(), m_position, Position::x, Position::y, and Position::z.
Referenced by ChatHandler::HandleGPSCommand().
GetClientGuidsIAmAt()
GuidSet& WorldObject::GetClientGuidsIAmAt () inline
Definition at line 1262 of file Object.h.
References m_clientGUIDsIAmAt.
Referenced by Spell::EffectBreakPlayerTargeting().
GetClosePoint()
void WorldObject::GetClosePoint (float & x, float & y, float & z, float bounding_radius, float distance2d = 0.0f, float angle = 0.0f, const WorldObject * obj = nullptr) const inline
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
Parameters
x,y,z - position for the found spot
bounding_radius - radius for the searcher
distance2d - range in which to find a free spot. Default = 0.0f (which usually means the units will have contact)
angle - direction in which to look for a free spot. Default = 0.0f (direction in which 'this' is looking
obj - for whom to look for a spot. Default = nullptr
Definition at line 1003 of file Object.h.
References GetNearPoint(), GetObjectBoundingRadius(), and GetOrientation().
Referenced by Spell::EffectActivateObject(), Spell::EffectCreateTamedPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonType(), Spell::EffectTransmitted(), npc_burster_wormAI::ExecuteAction(), ChatHandler::HandleCastDistCommand(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleNamegoCommand(), boss_silithidRoyaltyAI::ReceiveAIEvent(), CreatureCreatePos::SelectFinalPoint(), Spell::SetTargetMap(), npc_belnistraszAI::SpawnerSummon(), and Aura::TriggerSpell().
GetCollisionHeight()
virtual float WorldObject::GetCollisionHeight () const inline virtual
Reimplemented in Unit, GameObject, and DynamicObject.
Definition at line 1021 of file Object.h.
Referenced by GetNearPointAt(), Unit::IsVisibleForOrDetect(), IsWithinLOS(), IsWithinLOSInMap(), and MovePositionToFirstCollision().
GetCollisionWidth()
virtual float WorldObject::GetCollisionWidth () const inline virtual
Reimplemented in Unit.
Definition at line 1022 of file Object.h.
GetCombatReach()
virtual float WorldObject::GetCombatReach () const inline virtual
Reimplemented in Unit.
Definition at line 1024 of file Object.h.
Referenced by _IsWithinDist(), GameObject::_IsWithinDist(), GetCombinedCombatReach(), GetDistanceZ(), Spell::GetMinMaxRange(), IsInRange(), IsInRange2d(), IsInRange3d(), IsWithinDist2d(), and IsWithinDist3d().
GetCombinedCombatReach() [1/2]
float WorldObject::GetCombinedCombatReach (bool forMeleeRange = true, float flat_mod = 0.0f) const
Definition at line 1905 of file Object.cpp.
References ATTACK_DISTANCE, BASE_MELEERANGE_OFFSET, and GetCombatReach().
GetCombinedCombatReach() [2/2]
float WorldObject::GetCombinedCombatReach (WorldObject const * pVictim, bool forMeleeRange = true, float flat_mod = 0.0f) const
Definition at line 1900 of file Object.cpp.
References GetCombatReach().
Referenced by _IsWithinCombatDist(), boss_felmystAI::Aggro(), Unit::CanReachWithMeleeAttack(), UnitAI::DistanceYourself(), boss_skeramAI::ExecuteAction(), npc_bashir_flesh_fiendAI::ExecuteActions(), GetDistance(), GetDistance2d(), Spell::GetMinMaxRange(), and ChaseMovementGenerator::IsReachablePositionToTarget().
GetContactPoint()
void WorldObject::GetContactPoint (const WorldObject * obj, float & x, float & y, float & z, float distance2d = CONTACT_DISTANCE) const inline
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
Parameters
x,y,z - position for the found spot
obj - for whom to find a contact position. The position will be searched in direction from 'this' towards 'obj'
distance2d - distance which 'obj' and 'this' should have beetween their bounding radiuses. Default = CONTACT_DISTANCE
Definition at line 1013 of file Object.h.
References GetAngle(), GetNearPoint(), and GetObjectBoundingRadius().
Referenced by AreaTrigger_at_shadowforge_bridge(), npc_felhound_trackerAI::DoFindNewCrystal(), npc_rookery_hatcherAI::DoFindNewEgg(), npc_snufflenose_gopherAI::DoFindNewTubber(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), boss_selin_fireheartAI::DoSelectNearestCrystal(), instance_trial_of_the_champion::DoSendNextArenaWave(), instance_razorfen_downs::DoSpawnWaveIfCan(), EffectDummyCreature_npc_oil_stained_wolf(), Spell::EffectJump(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyCreature(), npc_razorthorn_ravager_pet::HandleAnimations(), ChatHandler::HandleGonameCommand(), ChildTbcAI::HandleTimeToVisitTheCaverns(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_fhwoorAI::JustSummoned(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_jennyAI::MoveInLineOfSight(), npc_apexis_flayerAI::MoveToCrystal(), boss_mr_smiteAI::PhaseEquipStart(), npc_decaying_ghoulAI::ReceiveAIEvent(), npc_domesticated_felboarAI::ReceiveAIEvent(), boss_tethyrAI::SpellHit(), instance_trial_of_the_champion::Update(), go_covertopsAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), npc_firecrackers_bunnyAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), and npc_dragonmaw_peonAI::UpdateAI().
GetCurrentCell()
Cell const& WorldObject::GetCurrentCell () const inline
Definition at line 1235 of file Object.h.
References m_currentCell.
Referenced by Map::CreatureCellRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), and ObjectGridRespawnMover::Visit().
GetDestLocCounter()
uint8 WorldObject::GetDestLocCounter () inline
Definition at line 1253 of file Object.h.
References m_destLocCounter.
Referenced by Spell::SendSpellGo().
GetDistance() [1/2]
float WorldObject::GetDistance (const WorldObject * obj, bool is3D = true, DistanceCalculation distcalc = DIST_CALC_BOUNDING_RADIUS) const
Definition at line 1416 of file Object.cpp.
References DIST_CALC_BOUNDING_RADIUS, DIST_CALC_COMBAT_REACH, DIST_CALC_COMBAT_REACH_WITH_MELEE, GetCombinedCombatReach(), GetObjectBoundingRadius(), GetPositionX(), GetPositionY(), and GetPositionZ().
Referenced by PlayerbotAI::_HandleCommandFollow(), _IsWithinCombatDist(), _IsWithinDist(), GameObject::_IsWithinDist(), FleeingMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Spell::AddGOTarget(), Spell::AddUnitTarget(), UnitAI::AttackClosestEnemy(), PlayerAI::AttackClosestEnemy(), boss_silithidRoyaltyAI::boss_silithidRoyaltyAI(), boss_viscidusAI::boss_viscidusAI(), PlayerbotAI::CanReachWithSpellAttack(), UnitAI::CanTriggerStealthAlert(), go_aura_generator::CheckAndApplyAura(), Spell::CheckRange(), Spell::CheckScriptTargeting(), UnitAI::DetectOrAttack(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), npc_wildaAI::DoFreeSpirits(), npc_general_andorovAI::DoInitializeFollowers(), PlayerbotAI::DoLoot(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), npc_flame_of_azzinothAI::DoPickChargeTarget(), instance_blackrock_spire::DoSortRoomEventMobs(), PlayerbotShamanAI::DropTotems(), EffectAuraDummy_npc_captured_beryl_sorcerer(), Spell::EffectPullTowards(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSummonDeadPet(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), npc_manaforge_spawnAI::EnterEvadeMode(), boss_nightbaneAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), Spell::FilterTargetMap(), PlayerbotAI::findNearbyCreature(), PlayerbotClassAI::FleeFromPointIfCan(), PlayerbotAI::FollowAutoReset(), UnitConditionMgr::getConditionValue(), GetDistanceOrder(), GetFirstRandomAngleCollisionPosition(), ScriptAction::GetScriptProcessTargets(), Unit::HandleDummyAuraProc(), WorldSession::HandleGameObjectUseOpcode(), ChatHandler::HandleGetDistanceCommand(), FormationMovementGenerator::HandleMasterDistanceCheck(), boss_illidan_stormrageAI::HandlePhaseTransition(), Player::HandleStealthedUnitsDetection(), ChaseMovementGenerator::HandleTargetedMovement(), npc_bt_battle_sensor::IllidariAttackNearestEnemy(), PlayerbotAI::In_Reach(), GameObject::IsAtInteractDistance(), Player::IsAtRecruitAFriendDistance(), isInBack(), isInFront(), IsInRange(), IsInRange3d(), ChaseMovementGenerator::IsReachablePositionToTarget(), GameObject::isVisibleForInState(), Unit::IsVisibleForOrDetect(), IsWithinDist3d(), npc_smolderwing::JustDidDialogueStep(), Unit::MeetsSelectAttackingRequirement(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_Shattered_Hand_Scout::MoveInLineOfSight(), Unit::NearTeleportTo(), DemonicCircleTeleport::OnCheckCast(), Spell::OnCheckTarget(), world_map_outland::OnCreatureRespawn(), spell_pulsing_shockwave::OnEffectExecute(), WebWrapMessage::OnEffectExecute(), InhibitMagic::OnHolderInit(), DemonicCircleSummon::OnPeriodicDummy(), MaNGOS::NearestAssistCreatureInCreatureRangeCheck::operator()(), MaNGOS::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), MaNGOS::NearestGameObjectFishingHoleCheck::operator()(), MaNGOS::NearestGameObjectEntryInObjectRangeCheck::operator()(), MaNGOS::AllGameObjectEntriesListInPosRangeCheck::operator()(), MaNGOS::NearestGameObjectEntryInPosRangeCheck::operator()(), MaNGOS::NearestAttackableUnitInObjectRangeCheck::operator()(), MaNGOS::AnyUnitFulfillingConditionInRangeCheck::operator()(), PlayerbotWarriorAI::Pull(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), npc_infantryAI::ReceiveAIEvent(), instance_zulaman::SendNextBearWave(), Spell::SetTargetMap(), npc_buru_eggAI::SpellHitTarget(), npc_spring_rabbitAI::StartWhatRabbitsDo(), npc_emilyAI::SummonedCreatureJustDied(), npc_kelerun_bloodmournAI::UpdateAI(), npc_solenorAI::UpdateAI(), npc_dark_nucleusAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), and Player::UpdateVisibilityOf().
GetDistance() [2/2]
float WorldObject::GetDistance (float x, float y, float z, DistanceCalculation distcalc = DIST_CALC_BOUNDING_RADIUS, bool transport = false) const
Definition at line 1447 of file Object.cpp.
References DIST_CALC_BOUNDING_RADIUS, DIST_CALC_COMBAT_REACH, DIST_CALC_COMBAT_REACH_WITH_MELEE, GetCombinedCombatReach(), GetObjectBoundingRadius(), GetPosition(), GetTransport(), Position::x, Position::y, and Position::z.
GetDistance2d()
float WorldObject::GetDistance2d (float x, float y, DistanceCalculation distcalc = DIST_CALC_BOUNDING_RADIUS) const
Definition at line 1474 of file Object.cpp.
References DIST_CALC_BOUNDING_RADIUS, DIST_CALC_COMBAT_REACH, DIST_CALC_COMBAT_REACH_WITH_MELEE, GetCombinedCombatReach(), GetObjectBoundingRadius(), GetPositionX(), and GetPositionY().
Referenced by boss_heiganAI::boss_heiganAI(), boss_void_reaverAI::boss_void_reaverAI(), boss_archimondeAI::CheckLeash(), Spell::EffectJump(), Spell::EffectPullTowards(), GameObject::GetClosestChairSlotPosition(), IsInRange2d(), IsWithinDist2d(), npc_living_poisonAI::MoveInLineOfSight(), FindCreatureData::operator()(), FindGOData::operator()(), ChatHandler::ShowTriggerListHelper(), ChatHandler::ShowTriggerTargetListHelper(), and CombatManager::Update().
GetDistanceOrder()
bool WorldObject::GetDistanceOrder (WorldObject const * obj1, WorldObject const * obj2, bool is3D = true, DistanceCalculation distcalc = DIST_CALC_NONE) const
Definition at line 1565 of file Object.cpp.
References GetDistance().
Referenced by boss_nightbaneAI::DoMoveToClosestTrigger(), instance_draktharon_keep::GetNextCrystalTarget(), ObjectDistanceOrder::operator()(), ObjectDistanceOrderReversed::operator()(), LowestHPNearestOrder::operator()(), SortHelper::operator()(), TargetDistanceOrderNear::operator()(), and TargetDistanceOrderFarAway::operator()().
GetDistanceZ()
float WorldObject::GetDistanceZ (const WorldObject * obj) const
Definition at line 1499 of file Object.cpp.
References GetCombatReach(), and GetPositionZ().
Referenced by UnitAI::MoveInLineOfSight(), GuardAI::MoveInLineOfSight(), PetAI::MoveInLineOfSight(), npc_dalaran_guardian_mageAI::MoveInLineOfSight(), and Unit::SelectHostileTarget().
GetExpireTime()
bool WorldObject::GetExpireTime (SpellEntry const & spellEntry, TimePoint & expireTime, bool & isPermanent) const protected
Definition at line 2823 of file Object.cpp.
References CooldownContainer::end(), CooldownContainer::FindBySpellId(), SpellEntry::Id, and m_cooldownMap.
Referenced by Unit::_UpdateAutoRepeatSpell(), and Player::LockOutSpells().
GetFaction()
virtual uint32 WorldObject::GetFaction () const inline virtual
Reimplemented in Unit, GameObject, and Corpse.
Definition at line 1269 of file Object.h.
Referenced by Spell::EffectSummonType().
GetFanningPoint()
bool WorldObject::GetFanningPoint (const Unit * mover, float & x, float & y, float & z, float dist, float angle) const
GetFirstCollisionPosition()
void WorldObject::GetFirstCollisionPosition (Position & pos, float dist, float angle) inline
Definition at line 1034 of file Object.h.
References GetPosition(), and MovePositionToFirstCollision().
Referenced by Spell::CheckCast(), CreatureAI::DoRetreat(), boss_halion_realAI::DoSpawnMeteorStrike(), GetFirstRandomAngleCollisionPosition(), Pet::GetPetSpawnPosition(), npc_meteor_strike_initialAI::JustSummoned(), MotionMaster::MoveCharge(), ProcessEventId_event_purify_food(), and Spell::SetTargetMap().
GetFirstRandomAngleCollisionPosition()
Position WorldObject::GetFirstRandomAngleCollisionPosition (float dist, float angle)
Definition at line 1753 of file Object.cpp.
References GetDistance(), GetFirstCollisionPosition(), GetPosition(), and M_PI_F.
Referenced by Spell::SetTargetMap(), and npc_doomfire_targetingAI::UpdateAI().
GetGCD()
TimePoint WorldObject::GetGCD (SpellEntry const * spellEntry) const
Definition at line 2764 of file Object.cpp.
References Map::GetCurrentClockTime(), GetMap(), m_GCDCatMap, and SpellEntry::StartRecoveryCategory.
GetHeartbeatDuration()
virtual uint32 WorldObject::GetHeartbeatDuration () const inline virtual
Definition at line 955 of file Object.h.
Referenced by Update().
GetInstanceData()
InstanceData * WorldObject::GetInstanceData () const
Definition at line 1411 of file Object.cpp.
References Map::GetInstanceData(), and GetMap().
Referenced by BossAI::Aggro(), Creature::AIM_Initialize(), GameObject::AIM_Initialize(), AreaTrigger_at_bartolo_ginsetti(), AreaTrigger_at_beggar(), AreaTrigger_at_blackrock_spire(), AreaTrigger_at_brewfest_barker(), AreaTrigger_at_cathedral_entrance(), AreaTrigger_at_culling_of_stratholme(), AreaTrigger_at_dark_portal(), AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_frozen_throne_tele(), AreaTrigger_at_hive_tower(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_icecrown_citadel(), AreaTrigger_at_madrigosa(), AreaTrigger_at_murkdeep(), AreaTrigger_at_naxxramas(), AreaTrigger_at_pit_of_saron(), AreaTrigger_at_putricides_trap(), AreaTrigger_at_queldelar_start(), AreaTrigger_at_rampart_skull(), AreaTrigger_at_raven_prophecy(), AreaTrigger_at_ring_of_law(), AreaTrigger_at_shade_of_eranikus(), AreaTrigger_at_shadowforge_bridge(), AreaTrigger_at_shattered_halls(), AreaTrigger_at_skadi(), AreaTrigger_at_sunwell_plateau(), AreaTrigger_at_svala_intro(), AreaTrigger_at_temple_ahnqiraj(), AreaTrigger_at_twilight_grove(), AreaTrigger_at_underbelly_a(), AreaTrigger_at_underbelly_h(), AreaTrigger_at_vaelastrasz(), AreaTrigger_at_wrath_lich_king(), AreaTrigger_at_zulfarrak(), AreaTrigger_at_zulgurub(), argent_champion_commonAI::argent_champion_commonAI(), blood_prince_council_baseAI::blood_prince_council_baseAI(), boss_aeonusAI::boss_aeonusAI(), boss_aerial_unitAI::boss_aerial_unitAI(), boss_algalonAI::boss_algalonAI(), boss_amanitarAI::boss_amanitarAI(), boss_ambassador_flamelashAI::boss_ambassador_flamelashAI(), boss_ambassador_hellmawAI::boss_ambassador_hellmawAI(), boss_anubarak_trialAI::boss_anubarak_trialAI(), boss_anubarakAI::boss_anubarakAI(), boss_anzuAI::boss_anzuAI(), boss_archaedasAI::boss_archaedasAI(), boss_auriayaAI::boss_auriayaAI(), boss_bjarngrimAI::boss_bjarngrimAI(), boss_black_knightAI::boss_black_knightAI(), boss_blood_queen_lanathelAI::boss_blood_queen_lanathelAI(), boss_brundirAI::boss_brundirAI(), boss_chrono_lord_dejaAI::boss_chrono_lord_dejaAI(), boss_dalliahAI::boss_dalliahAI(), boss_darkmaster_gandlingAI::boss_darkmaster_gandlingAI(), boss_devourer_of_soulsAI::boss_devourer_of_soulsAI(), boss_emperor_dagran_thaurissanAI::boss_emperor_dagran_thaurissanAI(), boss_eydisAI::boss_eydisAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_felmystAI::boss_felmystAI(), boss_feral_defenderAI::boss_feral_defenderAI(), boss_fjolaAI::boss_fjolaAI(), boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_freyaAI::boss_freyaAI(), boss_general_vezaxAI::boss_general_vezaxAI(), boss_gormokAI::boss_gormokAI(), boss_grand_warlock_nethekurseAI::boss_grand_warlock_nethekurseAI(), boss_grandmaster_vorpilAI::boss_grandmaster_vorpilAI(), boss_gythAI::boss_gythAI(), boss_halion_realAI::boss_halion_realAI(), boss_halion_twilightAI::boss_halion_twilightAI(), boss_harbinger_skyrissAI::boss_harbinger_skyrissAI(), boss_heart_deconstructorAI::boss_heart_deconstructorAI(), boss_hodirAI::boss_hodirAI(), boss_hydross_the_unstableAI::boss_hydross_the_unstableAI(), boss_icehowlAI::boss_icehowlAI(), boss_ignisAI::boss_ignisAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_ionarAI::boss_ionarAI(), boss_jaraxxusAI::boss_jaraxxusAI(), boss_jedogaAI::boss_jedogaAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_kologarnAI::boss_kologarnAI(), boss_leviathan_mk2AI::boss_leviathan_mk2AI(), boss_lich_king_horAI::boss_lich_king_horAI(), boss_lokenAI::boss_lokenAI(), boss_lord_marrowgarAI::boss_lord_marrowgarAI(), boss_malygosAI::boss_malygosAI(), boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI(), boss_mimironAI::boss_mimironAI(), boss_moamAI::boss_moamAI(), boss_moira_bronzebeardAI::boss_moira_bronzebeardAI(), boss_molgeimAI::boss_molgeimAI(), boss_murmurAI::boss_murmurAI(), boss_nadoxAI::boss_nadoxAI(), boss_nethermancer_sepethreaAI::boss_nethermancer_sepethreaAI(), boss_novosAI::boss_novosAI(), boss_onyxiaAI::boss_onyxiaAI(), boss_pathaleon_the_calculatorAI::boss_pathaleon_the_calculatorAI(), boss_plugger_spazzringAI::boss_plugger_spazzringAI(), boss_professor_putricideAI::boss_professor_putricideAI(), boss_pyroguard_emberseerAI::boss_pyroguard_emberseerAI(), boss_razorgoreAI::boss_razorgoreAI(), boss_razorscaleAI::boss_razorscaleAI(), boss_rotfaceAI::boss_rotfaceAI(), boss_saraAI::boss_saraAI(), boss_sartharionAI::boss_sartharionAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_savianaAI::boss_savianaAI(), boss_shade_of_akamaAI::boss_shade_of_akamaAI(), boss_sifAI::boss_sifAI(), boss_silver_hand_bossesAI::boss_silver_hand_bossesAI(), boss_sindragosaAI::boss_sindragosaAI(), boss_soccothratesAI::boss_soccothratesAI(), boss_steelbreakerAI::boss_steelbreakerAI(), boss_taldaramAI::boss_taldaramAI(), boss_teron_gorefiendAI::boss_teron_gorefiendAI(), boss_tharonjaAI::boss_tharonjaAI(), boss_the_lich_king_iccAI::boss_the_lich_king_iccAI(), boss_thermapluggAI::boss_thermapluggAI(), boss_thespiaAI::boss_thespiaAI(), boss_thorimAI::boss_thorimAI(), boss_trollgoreAI::boss_trollgoreAI(), boss_uromAI::boss_uromAI(), boss_valithria_dreamwalkerAI::boss_valithria_dreamwalkerAI(), boss_varosAI::boss_varosAI(), boss_vexallusAI::boss_vexallusAI(), boss_volazjAI::boss_volazjAI(), boss_volkhanAI::boss_volkhanAI(), boss_vx001AI::boss_vx001AI(), boss_warbringer_omroggAI::boss_warbringer_omroggAI(), boss_warchief_kargath_bladefistAI::boss_warchief_kargath_bladefistAI(), boss_warlord_kalithreshAI::boss_warlord_kalithreshAI(), boss_xt_002AI::boss_xt_002AI(), boss_ymironAI::boss_ymironAI(), boss_yogg_saronAI::boss_yogg_saronAI(), boss_zumrahAI::boss_zumrahAI(), Totem::Create(), npc_building_triggerAI::DamageTaken(), dummy_dragonAI::dummy_dragonAI(), EffectDummyCreature_npc_door_seal(), EffectDummyCreature_npc_medivh_black_morass(), EffectDummyCreature_npc_vault_warder(), EffectDummyCreature_spell_banner_of_provocation(), EffectDummyCreature_spell_boss_thermaplugg(), EffectDummyCreature_spell_guard_slip_kik(), EffectDummyCreature_spell_summon_reflections(), Spell::EffectSanctuary(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_spell_eat_ooze(), EffectScriptEffectCreature_spell_inhale_blight(), npc_ouro_moundAI::EnterEvadeMode(), boss_leotheras_the_blindAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), npc_melizza_brimbuzzleAI::GetSpeakerByEntry(), go_screaming_hall_door::go_screaming_hall_door(), GossipHello_boss_doomrel(), GossipHello_boss_majordomo(), GossipHello_go_icc_teleporter(), GossipHello_go_ulduar_teleporter(), GossipHello_npc_akama(), GossipHello_npc_arthas(), GossipHello_npc_ashli(), GossipHello_npc_aurius(), GossipHello_npc_barnes(), GossipHello_npc_barrett_ramsey(), GossipHello_npc_blastmaster_emi_shortfuse(), GossipHello_npc_brann_hos(), GossipHello_npc_brann_ulduar(), GossipHello_npc_chromie(), GossipHello_npc_disciple_of_naralex(), GossipHello_npc_echo_of_medivh(), GossipHello_npc_erozion(), GossipHello_npc_expedition_commander(), GossipHello_npc_general_andorov(), GossipHello_npc_harkor(), GossipHello_npc_harrison_jones_za(), GossipHello_npc_highlord_darion_mograine(), GossipHello_npc_human_charger(), GossipHello_npc_human_cleric(), GossipHello_npc_human_conjurer(), GossipHello_npc_human_footman(), GossipHello_npc_keeper_norgannon(), GossipHello_npc_king_llane(), GossipHello_npc_kraz(), GossipHello_npc_muradin_gunship(), GossipHello_npc_orc_grunt(), GossipHello_npc_orc_necrolyte(), GossipHello_npc_orc_warlock(), GossipHello_npc_orc_wolf(), GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), GossipHello_npc_saurfang_gunship(), GossipHello_npc_shadowfang_prisoner(), GossipHello_npc_sinclari(), GossipHello_npc_summoned_daemon(), GossipHello_npc_tanzar(), GossipHello_npc_taretha(), GossipHello_npc_thrall_old_hillsbrad(), GossipHello_npc_toc_herald(), GossipHello_npc_ulduar_keeper(), GossipHello_npc_warchief_blackhand(), GossipHello_npc_water_elemental(), GossipSelect_boss_doomrel(), GossipSelect_go_icc_teleporter(), GossipSelect_go_ulduar_teleporter(), GossipSelect_npc_barnes(), GossipSelect_npc_barrett_ramsey(), GossipSelect_npc_blastmaster_emi_shortfuse(), GossipSelect_npc_brann_ulduar(), GossipSelect_npc_chess_generic(), GossipSelect_npc_chromie(), GossipSelect_npc_disciple_of_naralex(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_echo_of_medivh(), GossipSelect_npc_highlord_darion_mograine(), GossipSelect_npc_jaina_proudmoore(), GossipSelect_npc_keeper_norgannon(), GossipSelect_npc_muradin_gunship(), GossipSelect_npc_saurfang_gunship(), GossipSelect_npc_sinclari(), GossipSelect_npc_taretha(), GossipSelect_npc_thrall(), GossipSelect_npc_thrall_old_hillsbrad(), GossipSelect_npc_tobias_seecher(), GossipSelect_npc_toc_herald(), GossipSelect_npc_ulduar_keeper(), GOUse_go_activate_tram(), GOUse_go_bar_ale_mug(), GOUse_go_bar_beer_keg(), GOUse_go_big_red_button(), GOUse_go_cage_door(), GOUse_go_celestial_access(), GOUse_go_containment_sphere(), GOUse_go_defias_cannon(), GOUse_go_eternal_flame(), GOUse_go_father_flame(), GOUse_go_fathom_stone(), GOUse_go_fire_of_akumai(), GOUse_go_gauntlet_gate(), GOUse_go_gnomeface_button(), GOUse_go_gong_of_bethekk(), GOUse_go_gundrak_altar(), GOUse_go_infernaling_summoner_portal_hound(), GOUse_go_main_chambers_access_panel(), GOUse_go_manticron_cube(), GOUse_go_nerubian_device(), GOUse_go_omen_cluster(), GOUse_go_prison_cell_lever(), GOUse_go_relic_coffer_door(), GOUse_go_sapphiron_birth(), GOUse_go_service_gate(), GOUse_go_shadowforge_brazier(), GOUse_go_shield_generator(), GOUse_go_ssc_boss_consoles(), GOUse_go_strange_pool(), GOUse_go_stratholme_postbox(), GOUse_go_twilight_portal(), GOUse_go_vashj_bridge(), GOUse_go_wooden_door(), Aura::HandleAuraDummy(), Aura::HandleModUnattackable(), npc_kalecgosAI::HandleTransform(), boss_terokkAI::JustDied(), BossAI::JustDied(), Unit::JustKilledCreature(), BossAI::JustReachedHome(), AchievementCriteriaRequirement::Meets(), mob_ahnkahar_eggAI::mob_ahnkahar_eggAI(), mob_ashtongue_channelerAI::mob_ashtongue_channelerAI(), mob_ashtongue_sorcererAI::mob_ashtongue_sorcererAI(), mob_big_oozeAI::mob_big_oozeAI(), mob_fel_orc_convertAI::mob_fel_orc_convertAI(), mob_frost_bombAI::mob_frost_bombAI(), mob_molten_golemAI::mob_molten_golemAI(), mob_spark_of_ionarAI::mob_spark_of_ionarAI(), mob_steamrigger_mechanicAI::mob_steamrigger_mechanicAI(), mob_stormforged_lieutenantAI::mob_stormforged_lieutenantAI(), mob_vrykul_skeletonAI::mob_vrykul_skeletonAI(), npc_akamaAI::npc_akamaAI(), npc_amanishi_scoutAI::npc_amanishi_scoutAI(), npc_annhyldeAI::npc_annhyldeAI(), npc_arcane_beamAI::npc_arcane_beamAI(), npc_arthasAI::npc_arthasAI(), npc_barnesAI::npc_barnesAI(), npc_beast_combat_stalkerAI::npc_beast_combat_stalkerAI(), npc_black_knight_ghoulAI::npc_black_knight_ghoulAI(), npc_blastmaster_emi_shortfuseAI::npc_blastmaster_emi_shortfuseAI(), npc_blood_orb_controlAI::npc_blood_orb_controlAI(), npc_bone_spikeAI::npc_bone_spikeAI(), npc_bot_triggerAI::npc_bot_triggerAI(), npc_brain_yogg_saronAI::npc_brain_yogg_saronAI(), npc_brann_hosAI::npc_brann_hosAI(), npc_captured_sprite_darterAI::npc_captured_sprite_darterAI(), npc_champion_mountAI::npc_champion_mountAI(), npc_chess_piece_genericAI::npc_chess_piece_genericAI(), npc_collapsing_icicleAI::npc_collapsing_icicleAI(), npc_concentrated_bulletAI::npc_concentrated_bulletAI(), npc_corrupted_soul_fragmentAI::npc_corrupted_soul_fragmentAI(), npc_creature_generatorAI::npc_creature_generatorAI(), npc_crystal_channel_targetAI::npc_crystal_channel_targetAI(), npc_deathstalker_vincentAI::npc_deathstalker_vincentAI(), npc_drijyaAI::npc_drijyaAI(), npc_echo_of_medivhAI::npc_echo_of_medivhAI(), npc_expedition_commanderAI::npc_expedition_commanderAI(), npc_fire_cycloneAI::npc_fire_cycloneAI(), npc_flash_freezeAI::npc_flash_freezeAI(), npc_focused_eyebeamAI::npc_focused_eyebeamAI(), npc_forest_frogAI::npc_forest_frogAI(), npc_giant_claw_tentacleAI::npc_giant_claw_tentacleAI(), npc_graufAI::npc_graufAI(), npc_grimstoneAI::npc_grimstoneAI(), npc_guardian_of_yoggAI::npc_guardian_of_yoggAI(), npc_halion_controllerAI::npc_halion_controllerAI(), npc_hodir_fury_reticleAI::npc_hodir_fury_reticleAI(), npc_hurley_blackbreathAI::npc_hurley_blackbreathAI(), npc_image_of_medivhAI::npc_image_of_medivhAI(), npc_impale_targetAI::npc_impale_targetAI(), npc_inner_demonAI::npc_inner_demonAI(), npc_ironhand_guardianAI::npc_ironhand_guardianAI(), npc_kindal_moonweaverAI::npc_kindal_moonweaverAI(), npc_marshal_windsorAI::npc_marshal_windsorAI(), npc_medivh_black_morassAI::npc_medivh_black_morassAI(), npc_meteor_strike_initialAI::npc_meteor_strike_initialAI(), npc_millhouse_manastormAI::npc_millhouse_manastormAI(), npc_mimiron_flamesAI::npc_mimiron_flamesAI(), npc_mistress_nagmaraAI::npc_mistress_nagmaraAI(), npc_netherspite_portalAI::npc_netherspite_portalAI(), npc_phalanxAI::npc_phalanxAI(), npc_power_sparkAI::npc_power_sparkAI(), npc_prison_event_controllerAI::npc_prison_event_controllerAI(), npc_putricides_trapAI::npc_putricides_trapAI(), npc_queen_lanathel_introAI::npc_queen_lanathel_introAI(), npc_raging_flamesAI::npc_raging_flamesAI(), npc_reginald_windsorAI::npc_reginald_windsorAI(), npc_rimefang_iccAI::npc_rimefang_iccAI(), npc_rocknotAI::npc_rocknotAI(), npc_rookery_hatcherAI::npc_rookery_hatcherAI(), npc_rubble_stalkerAI::npc_rubble_stalkerAI(), npc_runic_colossusAI::npc_runic_colossusAI(), npc_saronite_vaporAI::npc_saronite_vaporAI(), npc_shadowfang_prisonerAI::npc_shadowfang_prisonerAI(), npc_spinestalker_iccAI::npc_spinestalker_iccAI(), npc_tarethaAI::npc_tarethaAI(), npc_teleportation_portalAI::npc_teleportation_portalAI(), npc_tenebron_egg_controllerAI::npc_tenebron_egg_controllerAI(), npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI(), npc_time_riftAI::npc_time_riftAI(), npc_trial_grand_championAI::npc_trial_grand_championAI(), npc_twilight_volunteerAI::npc_twilight_volunteerAI(), npc_valentine_boss_managerAI::npc_valentine_boss_managerAI(), npc_vimgol_middle_bunnyAI::npc_vimgol_middle_bunnyAI(), npc_vimgol_visual_bunnyAI::npc_vimgol_visual_bunnyAI(), npc_voice_yogg_saronAI::npc_voice_yogg_saronAI(), npc_warden_mellicharAI::npc_warden_mellicharAI(), npc_warlock_mount_ritualAI::npc_warlock_mount_ritualAI(), DeathCloudBrutallus::OnApply(), SpectralRealmAura::OnApply(), spell_intense_cold_aura::OnApply(), spell_awaken_subboss_aura::OnApply(), InsidiousWhisper::OnApply(), PossessionTransfer::OnApply(), StormcrowAmulet::OnApply(), ThaddiusChargeDamage::OnCheckTarget(), spell_conjure_flame_sphere::OnEffectExecute(), spell_awaken_gortok::OnEffectExecute(), spell_launch_harpoon::OnEffectExecute(), DestroyEgg::OnEffectExecute(), ToAnchorOne::OnEffectExecute(), ToAnchorTwo::OnEffectExecute(), AnchorToSkull::OnEffectExecute(), SpectralRealm::OnEffectExecute(), SummonVoidSentinelSummonerVisual::OnEffectExecute(), SapphironAchievementCheck::OnEffectExecute(), ImpalingCharge::OnHit(), spell_permafrost_aura::OnPeriodicDummy(), spell_crystal_spike_aura::OnPeriodicDummy(), SummonZombieChow::OnPeriodicTrigger(), BossAI::OpenEntrances(), BossAI::OpenExits(), boss_mr_smiteAI::PhaseEquipStart(), CreatureEventAI::ProcessAction(), ProcessEventId_CharmDegrader(), ProcessEventId_CharmShivan(), ProcessEventId_event_spell_brann_achievement_fail(), ProcessEventId_event_spell_summon_raven_god(), ProcessEventId_WildhammerMessage(), QuestAccept_boss_vaelastrasz(), QuestAccept_npc_chromie(), QuestAccept_npc_gurthock(), QuestRewarded_boss_apothecary_hummel(), QuestRewarded_into_the_soulgrinder(), QuestRewarded_npc_aurius(), QuestRewarded_npc_mistress_nagmara(), QuestRewarded_npc_rocknot(), QuestRewarded_war_effort(), npc_scarlet_ghoulAI::ReceiveAIEvent(), Creature::RemoveCorpse(), CreatureGroup::RemoveObject(), boss_terokkAI::Reset(), Player::ResurrectPlayer(), Player::SendInitWorldStates(), Player::SetDeathState(), Unit::SetFeignDeath(), Unit::SetInCombatState(), npc_warp_gate::SpellHit(), npc_agent_proudwell::SummonedCreatureDespawn(), three_nature_alliesAI::three_nature_alliesAI(), trial_companion_commonAI::trial_companion_commonAI(), trial_crusader_commonAI::trial_crusader_commonAI(), Unit::TriggerEvadeEvents(), twin_jormungars_commonAI::twin_jormungars_commonAI(), Creature::Update(), DreadsteedQuestObjects::UpdateAI(), go_screaming_hall_door::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), npc_warp_gate::UpdateAI(), and Player::UpdateTerainEnvironmentFlags().
GetInstanceId()
uint32 WorldObject::GetInstanceId () const inline
Definition at line 1044 of file Object.h.
References m_InstanceId.
Referenced by Group::_addMember(), Unit::_UpdateSpells(), ObjectAccessor::AddCorpse(), Map::AddObjectToRemoveList(), PathFinder::calculate(), ObjectAccessor::ConvertCorpseForPlayer(), Map::GetCorpse(), Player::GetNextQuest(), ChatHandler::HandleGPSCommand(), WorldSession::HandleGroupInviteOpcode(), ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapStatsCommand(), ChatHandler::HandleNpcInfoCommand(), Group::InCombatToInstance(), MotionMaster::Initialize(), Unit::JustKilledCreature(), Player::LoadFromDB(), PathFinder::PathFinder(), Player::PrepareQuestMenu(), Corpse::SaveToDB(), PathFinder::SetCurrentNavMesh(), Player::Update(), Unit::Update(), MotionMaster::UpdateMotion(), and Unit::UpdateSplineMovement().
GetLevel()
virtual uint32 WorldObject::GetLevel () const inline virtual
Reimplemented in Unit, and GameObject.
Definition at line 1268 of file Object.h.
Referenced by Unit::CalcArmorReducedDamage(), and Spell::EffectSummonType().
GetMap()
Map* WorldObject::GetMap () const inline
Definition at line 1170 of file Object.h.
References m_currMap, and MANGOS_ASSERT.
Referenced by Unit::_GetPet(), Unit::_GetUnit(), PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandGet(), PlayerbotAI::_HandleCommandSkill(), PlayerbotAI::_HandleCommandSurvey(), PlayerbotAI::_HandleCommandUse(), Group::_homebindIfInstance(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Pet::_SaveSpellCooldowns(), HomeMovementGenerator< Creature >::_setTargetLocation(), Unit::_UpdateAutoRepeatSpell(), boss_algalonAI::ActivateRandomConstellation(), AddCooldown(), Creature::AddCooldown(), Player::AddCooldown(), AddGCD(), Player::AddGCD(), boss_kelidan_the_breakerAI::AddJustAggroed(), GameObject::AddModelToMap(), AddObjectToRemoveList(), Player::AddQuest(), Unit::AddSpellAuraHolder(), AddStringId(), ThreatManager::addThreat(), AddToClientUpdateList(), Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), Pet::AddToWorld(), Spell::AddUnitTarget(), Unit::AddWildGameObject(), Unit::AdjustZForCollision(), boss_malchezaarAI::Aggro(), boss_alythessAI::Aggro(), boss_sacrolashAI::Aggro(), boss_najentusAI::Aggro(), boss_warbringer_omroggAI::Aggro(), boss_soccothratesAI::Aggro(), npc_precious_the_devourerAI::Aggro(), npc_simone_seductressAI::Aggro(), mob_shadowmoon_soulstealerAI::Aggro(), GameObject::AIM_Initialize(), LootItem::AllowedForPlayer(), AreaTrigger_at_beggar(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_ghazan_surface(), AreaTrigger_at_naturalist_bite(), AreaTrigger_at_socrethar_seat(), AreaTrigger_at_teron_gorefiend(), argent_champion_commonAI::argent_champion_commonAI(), npc_dragonmaw_racerAI::AttackPlayer(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), Player::BeforeVisibilityDestroy(), CinematicMgr::BeginCinematic(), Player::BindToInstance(), boss_aeonusAI::boss_aeonusAI(), boss_aerial_unitAI::boss_aerial_unitAI(), boss_algalonAI::boss_algalonAI(), boss_ambassador_hellmawAI::boss_ambassador_hellmawAI(), boss_anetheronAI::boss_anetheronAI(), boss_anomalusAI::boss_anomalusAI(), boss_anubarakAI::boss_anubarakAI(), boss_anzuAI::boss_anzuAI(), boss_auriayaAI::boss_auriayaAI(), boss_bjarngrimAI::boss_bjarngrimAI(), boss_black_stalkerAI::boss_black_stalkerAI(), boss_brundirAI::boss_brundirAI(), boss_chrono_lord_dejaAI::boss_chrono_lord_dejaAI(), boss_coren_direbrewAI::boss_coren_direbrewAI(), boss_dalliahAI::boss_dalliahAI(), boss_darkweaver_sythAI::boss_darkweaver_sythAI(), boss_devourer_of_soulsAI::boss_devourer_of_soulsAI(), boss_eregosAI::boss_eregosAI(), boss_feral_defenderAI::boss_feral_defenderAI(), boss_festergutAI::boss_festergutAI(), boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_freyaAI::boss_freyaAI(), boss_general_vezaxAI::boss_general_vezaxAI(), boss_grand_warlock_nethekurseAI::boss_grand_warlock_nethekurseAI(), boss_grandmaster_vorpilAI::boss_grandmaster_vorpilAI(), boss_hadronoxAI::boss_hadronoxAI(), boss_harbinger_skyrissAI::boss_harbinger_skyrissAI(), boss_hodirAI::boss_hodirAI(), boss_ichoronAI::boss_ichoronAI(), boss_ignisAI::boss_ignisAI(), boss_ingvarAI::boss_ingvarAI(), boss_ionarAI::boss_ionarAI(), boss_jedogaAI::boss_jedogaAI(), boss_jeklikAI::boss_jeklikAI(), boss_kelesethAI::boss_kelesethAI(), boss_keristraszaAI::boss_keristraszaAI(), boss_kologarnAI::boss_kologarnAI(), boss_krikthirAI::boss_krikthirAI(), boss_leviathan_mk2AI::boss_leviathan_mk2AI(), boss_lokenAI::boss_lokenAI(), boss_malygosAI::boss_malygosAI(), boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI(), boss_molgeimAI::boss_molgeimAI(), boss_murmurAI::boss_murmurAI(), boss_nadoxAI::boss_nadoxAI(), boss_nethermancer_sepethreaAI::boss_nethermancer_sepethreaAI(), boss_novosAI::boss_novosAI(), boss_onyxiaAI::boss_onyxiaAI(), boss_ormorokAI::boss_ormorokAI(), boss_pandemoniusAI::boss_pandemoniusAI(), boss_pathaleon_the_calculatorAI::boss_pathaleon_the_calculatorAI(), boss_razorscaleAI::boss_razorscaleAI(), boss_renatakiAI::boss_renatakiAI(), boss_saraAI::boss_saraAI(), boss_sartharionAI::boss_sartharionAI(), boss_sifAI::boss_sifAI(), boss_sjonnirAI::boss_sjonnirAI(), boss_skadiAI::boss_skadiAI(), boss_soccothratesAI::boss_soccothratesAI(), boss_steelbreakerAI::boss_steelbreakerAI(), boss_svalaAI::boss_svalaAI(), boss_taldaramAI::boss_taldaramAI(), boss_telestraAI::boss_telestraAI(), boss_terokkAI::boss_terokkAI(), boss_tethyrAI::boss_tethyrAI(), boss_tharonjaAI::boss_tharonjaAI(), boss_thespiaAI::boss_thespiaAI(), boss_thorimAI::boss_thorimAI(), boss_thorngrinAI::boss_thorngrinAI(), boss_trollgoreAI::boss_trollgoreAI(), boss_uromAI::boss_uromAI(), boss_varosAI::boss_varosAI(), boss_veras_darkshadowAI::boss_veras_darkshadowAI(), boss_volazjAI::boss_volazjAI(), boss_volkhanAI::boss_volkhanAI(), boss_vx001AI::boss_vx001AI(), boss_warbringer_omroggAI::boss_warbringer_omroggAI(), boss_warchief_kargath_bladefistAI::boss_warchief_kargath_bladefistAI(), boss_warp_splinterAI::boss_warp_splinterAI(), boss_xevozzAI::boss_xevozzAI(), boss_xt_002AI::boss_xt_002AI(), boss_ymironAI::boss_ymironAI(), boss_yogg_saronAI::boss_yogg_saronAI(), boss_yorAI::boss_yorAI(), Unit::BreakCharmOutgoing(), npc_simon_game_bunnyAI::BuffPlayers(), OutdoorPvP::BuffTeam(), Object::BuildMovementUpdate(), Player::BuildPlayerRepop(), PathFinder::BuildPolyPath(), boss_ouroAI::Burrow(), Player::BuyItemFromVendorSlot(), boss_ionarAI::CallBackSparks(), Unit::CallForAllControlledUnits(), Unit::CanAssistInCombatAgainst(), Creature::CanRestockPickpocketLoot(), CreatureLinkingHolder::CanSpawn(), npc_thrallAI::CanUseFeralSpiritsAgain(), Spell::cast(), PlayerbotAI::CastSpell(), go_aura_generator::ChangeState(), Unit::CharmCooldownInitialize(), Unit::CheckAllControlledUnits(), go_aura_generator::CheckAndApplyAura(), PlayerbotAI::CheckBotCast(), Spell::CheckCast(), npc_theramore_spar_controller::CheckCombatantHP(), Player::CheckDuelDistance(), CreatureEventAI::CheckEvent(), npc_lord_illidan_stormrageAI::CheckEventFail(), mob_arugal_voidwalkerAI::CheckGroupStatus(), CheckPathToTarget(), Spell::CheckScriptTargeting(), Spell::CheckTarget(), BattlefieldWG::CleanupBattlefield(), npc_theramore_spar_controller::CombatantSalute(), npc_theramore_spar_controller::CombatantSeparate(), PlayerbotAI::CombatOrderRestore(), PathFinder::ComputePathToRandomPoint(), npc_spirit_guideAI::CorpseRemoved(), mob_phoenix_tkAI::CorpseRemoved(), Unit::CountGuardiansWithEntry(), Creature::Create(), Totem::Create(), Corpse::Create(), DynamicObject::Create(), Pet::CreateBaseAtCreature(), Player::CreateCorpse(), ChaseMovementGenerator::CutPath(), boss_ahuneAI::DamageTaken(), npc_frozen_coreAI::DamageTaken(), npc_dirty_larryAI::DamageTaken(), npc_death_knight_initiateAI::DamageTaken(), boss_black_knightAI::DamageTaken(), npc_grand_admiral_westwindAI::DamageTaken(), boss_hodirAI::DamageTaken(), boss_saraAI::DamageTaken(), npc_building_triggerAI::DamageTaken(), Unit::DealMeleeDamage(), DynamicObject::Delay(), GameObject::Delete(), Corpse::DeleteBonesFromWorld(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), boss_anzuAI::DespawnBirdHelpers(), npc_commanderAI::DespawnDefenders(), npc_commanderAI::DespawnDragonmaw(), npc_adyen_the_lightwardenAI::DespawnEvent(), boss_volkhanAI::DespawnGolems(), UnitAI::DespawnGuids(), boss_mechano_lord_capacitusAI::DespawnNetherCharges(), Transport::DespawnPassengers(), boss_netherspiteAI::DespawnPortals(), boss_ionarAI::DespawnSpark(), npc_colonel_julesAI::DespawnSummons(), Unit::DespawnSummonsOnDeath(), OutdoorPvPGH::DespawnVendors(), OutdoorPvPNA::DespawnVendors(), UnitAI::DetectOrAttack(), npc_scrap_reaverAI::Die(), ChaseMovementGenerator::DispatchSplineToPosition(), Spell::DoAllEffectOnTarget(), boss_icehowlAI::DoApplySurgeOfAdrenaline(), npc_eris_havenfireAI::DoAttackArchersTarget(), npc_eris_havenfireAI::DoBalanceEventEnd(), npc_grimstoneAI::DoChallengeQuestCredit(), boss_ymironAI::DoChannelSpiritYmiron(), npc_simon_game_bunnyAI::DoCleanupGame(), npc_simon_game_bunnyAI::DoCompleteLevel(), CreatureLinkingHolder::DoCreatureLinkingEvent(), boss_warchief_kargath_bladefistAI::DoDespawnAdds(), boss_jeklikAI::DoDespawnBombRiders(), boss_anubarak_trialAI::DoDespawnPursuingSpikes(), npc_keeper_remulosAI::DoDespawnSummoned(), boss_eranikusAI::DoDespawnSummoned(), boss_kaelthasAI::DoDespawnSummons(), npc_eris_havenfireAI::DoDespawnSummons(), boss_tethyrAI::DoEncounterCleanup(), Transport::DoEventIfAny(), npc_manaforge_control_consoleAI::DoFailEvent(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), boss_hydross_the_unstableAI::DoHandleBeamHelpers(), npc_eris_havenfireAI::DoHandlePhaseEnd(), npc_general_andorovAI::DoInitializeFollowers(), PlayerbotAI::DoLoot(), boss_razorscaleAI::DoMoveEngineersToHarpoon(), boss_nightbaneAI::DoMoveToClosestTrigger(), npc_general_andorovAI::DoMoveToEventLocation(), npc_flame_of_azzinothAI::DoPickChargeTarget(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), boss_skadiAI::DoPrepareForGauntlet(), boss_anubarak_trialAI::DoRefreshSpheres(), boss_moroesAI::DoRemoveGarroteAura(), boss_halazziAI::DoReuniteSpirits(), boss_lady_deathwhisperAI::DoSelectRandomCultist(), npc_highlord_darion_mograineAI::DoSendQuestCredit(), boss_taldaramAI::DoSetSpheresInMotion(), boss_lady_deathwhisperAI::DoSortSummoningStalkers(), boss_thorimAI::DoSpawnArenaDwarf(), npc_drijyaAI::DoSpawnCreature(), boss_ossirianAI::DoSpawnNextCrystal(), npc_meteor_strike_initialAI::DoStartFlameStrikes(), npc_valentine_boss_managerAI::DoStartValentineEvent(), Spell::DoSummonCritter(), boss_lady_deathwhisperAI::DoSummonCultistWave(), boss_trollgoreAI::DoSummonDrakkariInvaders(), Spell::DoSummonGuardian(), npc_warlock_mount_ritualAI::DoSummonPack(), Spell::DoSummonPet(), Spell::DoSummonTotem(), Spell::DoSummonVehicle(), Spell::DoSummonWild(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), boss_grandmaster_vorpilAI::DoTeleportToPlatform(), boss_headless_horsemanAI::DoTossHead(), npc_anubisath_sentinelAI::DoTransferAbility(), npc_anachronos_the_ancientAI::DoUnsummonArmy(), npc_demolitionist_legosoAI::DoUseExplosiveTraps(), boss_warbringer_omroggAI::DoYellForThreat(), Player::DuelComplete(), dummy_dragonAI::dummy_dragonAI(), Spell::EffectAddFarsight(), EffectAuraDummy_npc_scourged_flamespitter(), Spell::EffectBreakPlayerTargeting(), Spell::EffectCreateTamedPet(), Spell::EffectDuel(), Spell::EffectDummy(), EffectDummyCreature_spell_summon_reflections(), Spell::EffectJump(), Spell::EffectPersistentAA(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_npc_putricide(), Spell::EffectSendEvent(), Spell::EffectStuck(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), Spell::EffectTeleportGraveyard(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), Spell::EffectWMODamage(), boss_anzuAI::EnableBirdHelpers(), npc_adyen_the_lightwardenAI::EndEvent(), boss_nightbaneAI::EnterEvadeMode(), boss_felmystAI::EnterEvadeMode(), npc_tirion_fordringAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), boss_cthunAI::EnterEvadeMode(), npc_anubisath_sentinelAI::EnterEvadeMode(), npc_precious_the_devourerAI::EnterEvadeMode(), npc_beast_combat_stalkerAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), boss_vazruden_heraldAI::EnterEvadeMode(), npc_manaforge_spawnAI::EnterEvadeMode(), ConditionEntry::Evaluate(), AiDelayEventAround::Execute(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_sladranAI::ExecuteAction(), boss_rimefang_posAI::ExecuteAction(), boss_zarithrianAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), npc_adyen_the_lightwardenAI::ExecuteTimer(), PlayerbotAI::extractGOinfo(), NamreebAnticheat::Movement::ExtrapolateMovement(), npc_apprentice_mirvedaAI::FailEvent(), npc_twiggy_flatheadAI::FailEvent(), npc_adyen_the_lightwardenAI::FailEvent(), npc_commanderAI::FailEvent(), npc_dragonmaw_racerAI::FailRace(), Spell::FillAreaTargets(), HomeMovementGenerator< Creature >::Finalize(), Unit::FindGuardianWithEntry(), PlayerbotAI::findNearbyCreature(), Spell::finish(), LFGMgr::FinishDungeon(), npc_dragonmaw_racerAI::FinishRace(), npc_raging_flamesAI::FixateRandomTarget(), PlayerbotClassAI::FleeFromPointIfCan(), npc_regthar_deathgateAI::ForceDespawn(), GameObject::ForceGameObjectHealth(), MaNGOS::XP::Gain(), boss_gormokAI::GetActiveSnobold(), Spell::GetAffectiveCasterObject(), BattlefieldWG::GetBattlefieldReady(), SpellAuraHolder::GetCaster(), Spell::GetCastingObject(), Unit::GetChannelObject(), Unit::GetCharm(), Unit::GetCharmer(), boss_thorimAI::GetClosestLowerBunny(), Unit::GetCreator(), npc_a_special_surpriseAI::GetDialogueTarget(), npc_death_knight_initiateAI::GetDialogueTarget(), DynamicObject::GetDuration(), TemporarySpawn::GetDuration(), Unit::GetDynObject(), Unit::GetGameObject(), Player::GetGameObjectIfCanInteractWith(), ChatHandler::GetGameObjectWithGuid(), GetGCD(), Player::GetGossipTextId(), GetInstanceData(), FollowerAI::GetLeaderForFollower(), GameObject::GetLinkedTrap(), LootMgr::GetLoot(), go_manticron_cubeAI::GetManticronCubeLastUser(), Unit::GetMiniPet(), npc_chess_piece_genericAI::GetMovementSquare(), GetNearPointAt(), Player::GetNextQuest(), Player::GetNPCIfCanInteractWith(), Player::GetObjectByTypeMask(), npc_spring_rabbitAI::GetPartnerAI(), Unit::GetPet(), Map::GetPlayer(), npc_escortAI::GetPlayerForEscort(), npc_adyen_the_lightwardenAI::GetPlayerTarget(), Spell::GetPrefilledUnitTargetOrUnitTarget(), Unit::GetProtectorPet(), boss_thorimAI::GetRandomArenaPlayer(), boss_sacrolashAI::GetRandomTargetAtDist(), ChatHandler::getSelectedCreature(), GameObject::GetSpawner(), Unit::GetSpawner(), npc_squire_roweAI::GetSpeakerByEntry(), npc_taelan_fordringAI::GetSpeakerByEntry(), npc_keeper_remulosAI::GetSpeakerByEntry(), npc_grark_lorkrubAI::GetSpeakerByEntry(), npc_anachronos_the_ancientAI::GetSpeakerByEntry(), npc_ranshallaAI::GetSpeakerByEntry(), npc_shaheenAI::GetSpeakerByEntry(), npc_anchorite_baradaAI::GetSpeakerByEntry(), npc_spawned_oronok_tornheartAI::GetSpeakerByEntry(), npc_air_force_botsAI::GetSummonedGuard(), Unit::GetTarget(), npc_chess_piece_genericAI::GetTargetByType(), HostileRefManager::GetThreatRedirectionTarget(), Unit::GetTotem(), ObjectAccessor::GetUnit(), VisibilityData::GetVisibilityDistance(), GossipHello_npc_adyen_the_lightwarden(), WorldSession::HandleAcceptLevelGrant(), mob_torlothAI::HandleAnimation(), npc_razorthorn_ravager_pet::HandleAnimations(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), WorldSession::HandleAreaTriggerOpcode(), npc_doomguard_punisherAI::HandleAttackDelay(), npc_shivan_assassinAI::HandleAttackDelay(), npc_eye_of_shartuulAI::HandleAttackDelay(), npc_dreadmawAI::HandleAttackDelay(), WorldSession::HandleAttackSwingOpcode(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), Aura::HandleAuraDummy(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBattlemasterJoinArena(), PlayerbotAI::HandleBotOutgoingPacket(), boss_felmystAI::HandleBreath(), WorldSession::HandleChangePlayerDifficulty(), WorldSession::HandleChangeSeatsOnControlledVehicle(), ChatHandler::HandleChangeWeatherCommand(), boss_lady_vashjAI::HandleCoilfangElite(), boss_lady_vashjAI::HandleCoilfangStrider(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), ChatHandler::HandleDebugDbscript(), ChatHandler::HandleDebugDbscriptGuided(), ChatHandler::HandleDebugDbscriptSourced(), ChatHandler::HandleDebugDbscriptTargeted(), ChatHandler::HandleDebugRespawnDynguid(), ChatHandler::HandleDebugSpawnsList(), ChatHandler::HandleDebugTransports(), BattlefieldWG::HandleDestructibleBuildingEvent(), Unit::HandleDummyAuraProc(), WorldSession::HandleEjectPassenger(), boss_ahuneAI::HandleEmerge(), boss_lady_vashjAI::HandleEnchantedElemental(), BattleGroundSA::HandleEvent(), WorldSession::HandleFarSightOpcode(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), WorldSession::HandleGameobjectReportUse(), ChatHandler::HandleGameObjectRespawnCommand(), ChatHandler::HandleGameObjectTargetCommand(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleGetMirrorimageData(), ChatHandler::HandleGoHelper(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleGPSCommand(), WorldSession::HandleGrantLevel(), ChatHandler::HandleGridsLoadedCount(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleInstanceSaveDataCommand(), boss_vaelastraszAI::HandleIntro(), boss_lady_vashjAI::HandleIntroText(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleListAreaTriggerCommand(), WorldSession::HandleLootOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleMmapTestHeight(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveTeleportAckOpcode(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), ChatHandler::HandleNpcAddCommand(), ChatHandler::HandleNpcDeleteCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcWhisperCommand(), boss_gothikAI::HandleOpenGates(), boss_majordomoAI::HandleOutro(), Aura::HandlePeriodicTriggerSpell(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetRename(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), boss_illidan_stormrageAI::HandlePhaseTransition(), WorldState::HandlePlayerEnterZone(), OutdoorPvPHP::HandlePlayerKillInsideArea(), OutdoorPvPZM::HandlePlayerKillInsideArea(), WorldState::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), HandlePlayPacketSettings(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), boss_felmystAI::HandlePreBreath(), Aura::HandlePreventResurrection(), Unit::HandleProcTriggerDamageAuraProc(), boss_omor_the_unscarredAI::HandlePullBack(), mob_phoenix_tkAI::HandleRebirth(), WorldSession::HandleRequestVehicleSwitchSeat(), boss_sartharionAI::HandleResetWorldstate(), ChatHandler::HandleRespawnCommand(), WorldSession::HandleRideVehicleInteract(), ChatHandler::HandleSD2HelpCommand(), ChatHandler::HandleSD2ScriptCommand(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), mob_shadowmoon_channelerAI::HandleSetup(), ChatHandler::HandleShowTemporarySpawnList(), boss_muruAI::HandleSpawnAttack(), WorldSession::HandleSpellClick(), boss_high_astromancer_solarianAI::HandleSplitAgents(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_lady_vashjAI::HandleTaintedElemental(), WorldSession::HandleTextEmoteOpcode(), npc_kalecgosAI::HandleTransform(), ChildTbcAI::HandleTripToTheDarkPortal(), ChatHandler::HandleVariablePrint(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), Unit::HasAuraOfDifficulty(), HasGCD(), HasGCDOrCooldownWithinMargin(), HasStringId(), Helper_CreateWaypointFor(), Unit::IncrDiminishing(), AbstractWrapperMovementGenerator::Inform(), WaypointMovementGenerator< Creature >::InformAI(), CreatureEventAI::InitAI(), Creature::InitEntry(), ChaseMovementGenerator::Initialize(), FollowMovementGenerator::Initialize(), npc_anubisath_sentinelAI::InitSentinelsNear(), Creature::InspectingLoot(), Unit::InterruptSpellsCastedOnMe(), Unit::IsAboveGround(), Player::IsAtGroupRewardDistance(), Creature::IsCorpseExpired(), TemporarySpawn::IsExpired(), SpellClickInfo::IsFitToRequirements(), SpellArea::IsFitToRequirements(), IsInMap(), IsInMapIgnorePhase(), npc_shadowlord_deathwailAI::IsPlayerOrGroupInRangeAndActiveInEvent(), IsSpellOnPermanentCooldown(), IsSpellReady(), Unit::IsTargetUnderControl(), Corpse::isVisibleForInState(), GameObject::isVisibleForInState(), Unit::IsVisibleForOrDetect(), IsWithinLOS(), IsWithinLOSForMe(), LFGMgr::JoinLfg(), go_fel_cannonball_stack_trap::JustDespawned(), npc_death_knight_initiateAI::JustDidDialogueStep(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_squire_roweAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), npc_grark_lorkrubAI::JustDidDialogueStep(), npc_barnesAI::JustDidDialogueStep(), npc_valentine_boss_managerAI::JustDidDialogueStep(), npc_kiljaeden_controllerAI::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), npc_lich_king_villageAI::JustDidDialogueStep(), boss_malygosAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), npc_blastmaster_emi_shortfuseAI::JustDied(), npc_chess_piece_genericAI::JustDied(), boss_headless_horsemanAI::JustDied(), npc_deathstalker_faerleiaAI::JustDied(), boss_anetheronAI::JustDied(), npc_thrall_old_hillsbradAI::JustDied(), npc_simone_seductressAI::JustDied(), boss_gormokAI::JustDied(), npc_web_wrapAI::JustDied(), dummy_dragonAI::JustDied(), npc_flash_freezeAI::JustDied(), boss_kologarnAI::JustDied(), npc_constrictor_tentacleAI::JustDied(), boss_ymironAI::JustDied(), mob_stolen_soulAI::JustDied(), npc_shadow_demonAI::JustDied(), boss_supremusAI::JustDied(), npc_soulgrinderAI::JustDied(), boss_ahuneAI::JustDied(), boss_warbringer_omroggAI::JustDied(), npc_anchorite_baradaAI::JustDied(), npc_vindicator_sedaiAI::JustDied(), npc_salhadaarAI::JustDied(), npc_scrapped_fel_reaverAI::JustDied(), mob_torlothAI::JustDied(), npc_warden_mellicharAI::JustDied(), PallidHorrorAI::JustDied(), npc_keeper_remulosAI::JustDied(), boss_terokkAI::JustDied(), npc_inner_demonAI::JustDied(), npc_00x09hlAI::JustDied(), npc_oox22feAI::JustDied(), npc_oox17tnAI::JustDied(), Unit::JustKilledCreature(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_thermapluggAI::JustReachedHome(), boss_curatorAI::JustReachedHome(), boss_terestianAI::JustReachedHome(), boss_headless_horsemanAI::JustReachedHome(), boss_ouroAI::JustReachedHome(), npc_simone_seductressAI::JustReachedHome(), boss_malygosAI::JustReachedHome(), boss_algalonAI::JustReachedHome(), boss_warbringer_omroggAI::JustReachedHome(), npc_shattered_sun_fighterAI::JustRespawned(), npc_zulian_prowlerAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_brann_hosAI::JustRespawned(), boss_yorAI::JustRespawned(), npc_ethereum_prisoner_dungeonAI::JustRespawned(), npc_ethereum_prisonerAI::JustRespawned(), ColiseumFloor::JustSpawned(), go_imp_in_a_ball::JustSpawned(), boss_uromAI::JustSummoned(), npc_eris_havenfireAI::JustSummoned(), boss_volazjAI::JustSummoned(), npc_beast_combat_stalkerAI::JustSummoned(), npc_emilyAI::JustSummoned(), boss_kologarnAI::JustSummoned(), npc_storm_tempered_keeperAI::JustSummoned(), boss_exarch_maladaarAI::JustSummoned(), npc_warp_gate::JustSummoned(), npc_warden_mellicharAI::JustSummoned(), boss_entropiusAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_archimondeAI::JustSummoned(), boss_ayamissAI::JustSummoned(), boss_terokkAI::JustSummoned(), npc_lord_illidan_stormrageAI::JustSummoned(), Player::KilledPlayerCredit(), boss_warbringer_omroggAI::KilledUnit(), boss_tethyrAI::KilledUnit(), Unit::KnockBackWithAngle(), Movement::MoveSplineInit::Launch(), Creature::LoadCreatureAddon(), Player::LoadFromDB(), Creature::LoadFromDB(), Pet::LoadPetFromDB(), OutdoorPvPNA::LockHalaa(), OutdoorPvPGH::LockLighthouse(), LockOutSpells(), Player::LockOutSpells(), OutdoorPvPTF::LockTowers(), BattlefieldWG::LockWorkshops(), WorldSession::LogoutPlayer(), AchievementCriteriaRequirement::Meets(), UnitConditionMgr::Meets(), mob_dragonflayer_forge_masterAI::mob_dragonflayer_forge_masterAI(), mob_molten_golemAI::mob_molten_golemAI(), mob_steamrigger_mechanicAI::mob_steamrigger_mechanicAI(), mob_stormforged_lieutenantAI::mob_stormforged_lieutenantAI(), mob_vrykul_skeletonAI::mob_vrykul_skeletonAI(), Player::ModifyCooldown(), MonsterText(), FollowMovementGenerator::Move(), MotionMaster::MoveFall(), UnitAI::MoveInLineOfSight(), npc_nesingwary_trapperAI::MoveInLineOfSight(), boss_lich_king_horAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_evergrove_druidAI::MoveInLineOfSight(), npc_theramore_spar_controller::MoveIntoPosition(), npc_bashir_flesh_fiendAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_shadow_demonAI::MovementInform(), npc_scarlet_ghoulAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_concentrated_bulletAI::MovementInform(), boss_ymironAI::MovementInform(), npc_Shattered_Hand_Scout::MovementInform(), npc_snufflenose_gopherAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_hodir_fury_reticleAI::MovementInform(), npc_decaying_ghoulAI::MovementInform(), npc_cenarion_sparrowhawkAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), npc_nesingwary_trapperAI::MovementInform(), npc_grand_admiral_westwindAI::MovementInform(), boss_lady_vashjAI::MovementInform(), npc_anchorite_baradaAI::MovementInform(), npc_vindicator_sedaiAI::MovementInform(), npc_dragonmaw_racer_skyshatterAI::MovementInform(), AbstractPathMovementGenerator::MovementInform(), PointMovementGenerator::MovementInform(), MovePositionToFirstCollision(), Unit::NearTeleportTo(), NecropolisHealthAI::NecropolisHealthAI(), NecroticShard::NecroticShard(), npc_dirty_larryAI::NextStep(), MaNGOS::VisibleNotifier::Notify(), npc_aether_tech_vendorAI::npc_aether_tech_vendorAI(), npc_annhyldeAI::npc_annhyldeAI(), npc_arcatraz_defenderAI::npc_arcatraz_defenderAI(), npc_arthasAI::npc_arthasAI(), npc_commanderAI::npc_commanderAI(), npc_constrictor_tentacleAI::npc_constrictor_tentacleAI(), npc_dark_matterAI::npc_dark_matterAI(), npc_eonars_giftAI::npc_eonars_giftAI(), npc_ethereal_sphereAI::npc_ethereal_sphereAI(), npc_ethereum_prisoner_dungeonAI::npc_ethereum_prisoner_dungeonAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_guardian_of_yoggAI::npc_guardian_of_yoggAI(), npc_immortal_guardianAI::npc_immortal_guardianAI(), npc_impale_targetAI::npc_impale_targetAI(), npc_iron_constructAI::npc_iron_constructAI(), npc_iron_rootsAI::npc_iron_rootsAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_living_constellationAI::npc_living_constellationAI(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), npc_malfurionAI::npc_malfurionAI(), npc_nature_bombAI::npc_nature_bombAI(), npc_raging_flamesAI::npc_raging_flamesAI(), npc_runic_colossusAI::npc_runic_colossusAI(), npc_time_riftAI::npc_time_riftAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), npc_voice_yogg_saronAI::npc_voice_yogg_saronAI(), npc_void_travelerAI::npc_void_travelerAI(), HodirsProtectiveGaze::OnAbsorb(), SnakeWrap::OnApply(), Sacrifice::OnApply(), WidowsEmbrace::OnApply(), spell_intense_cold_aura::OnApply(), spell_awaken_subboss_aura::OnApply(), spell_create_spirit_fount_beam_aura::OnApply(), StormcrowAmulet::OnApply(), Drink::OnApply(), WaypointMovementGenerator< Creature >::OnArrived(), FaceRandomTarget::OnCast(), Spell::OnCheckCast(), FlagClickBg::OnCheckCast(), HatefulStrikePrimer::OnCheckTarget(), Replenishment::OnCheckTarget(), instance_shadow_labyrinth::OnCreatureDeath(), SummonVoidSentinelSummoner::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), spell_awaken_gortok::OnEffectExecute(), VazrudenLiquidFire::OnEffectExecute(), spell_repair_cannon::OnEffectExecute(), spell_end_of_round::OnEffectExecute(), SapphironBlizzardInit::OnEffectExecute(), spell_vortex::OnEffectExecute(), PossessDemonShartuul::OnEffectExecute(), SmashShield::OnEffectExecute(), FlagClickBg::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), SapphironAchievementCheck::OnEffectExecute(), SupremusHatefulStrikePrimer::OnEffectExecute(), HurtfulStrikePrimer::OnEffectExecute(), TribalDeath::OnEffectExecute(), go_ai_bell::OnEventHappened(), Player::OnGossipSelect(), ColiseumFloor::OnGoStateChange(), ConflagrationTargeting::OnInit(), go_ai_larva_spewer::OnLootStateChange(), go_ai_suppression::OnLootStateChange(), MammothTrapBoreanAI::OnLootStateChange(), instance_ulduar::OnObjectSpawn(), GripOfSladran::OnPeriodicDummy(), spell_permafrost_aura::OnPeriodicDummy(), Drink::OnPeriodicDummy(), KillingSpree::OnPeriodicDummy(), spell_explosive_barrage_aura::OnPeriodicTrigger(), SummonZombieChow::OnPeriodicTrigger(), SummonSkeletonsNoth::OnPeriodicTrigger(), PallidHorrorAI::OnRemoveFromWorld(), OCWAuchindounSummonAdventurer::OnSummon(), Player::OnTaxiFlightEnd(), Player::OnTaxiFlightRouteProgress(), NamreebAnticheat::Movement::OnTransport(), MaNGOS::RespawnDo::operator()(), FindCreatureData::operator()(), FindGOData::operator()(), PallidHorrorAI::PallidHorrorAI(), npc_doctorAI::PatientDied(), npc_doctorAI::PatientSaved(), Aura::PeriodicDummyTick(), PlayerbotAI::PickPocket(), LootTemplate::PlayerOrGroupFulfilsCondition(), Player::PrepareGossipMenu(), Player::PrepareQuestMenu(), PrintCooldownList(), Unit::ProcDamageAndSpellFor(), CreatureEventAI::ProcessAction(), ProcessEventId_event_summon_terokk(), ProcessEventIdRazorgorePossess(), ProcessEventTransports(), CreatureLinkingHolder::ProcessSlaveGuidList(), QuestAccept_npc_major_mills(), QuestRewarded_into_the_soulgrinder(), QuestRewarded_npc_adal(), Player::QueueOrAddResurrectRequest(), SpellCastTargets::read(), boss_illidan_stormrageAI::ReceiveAIEvent(), MouthAI::ReceiveAIEvent(), npc_major_mills::ReceiveAIEvent(), npc_jennyAI::ReceiveAIEvent(), boss_professor_putricideAI::ReceiveAIEvent(), npc_creature_generatorAI::ReceiveAIEvent(), npc_ice_spear_bunnyAI::ReceiveAIEvent(), mob_phoenix_tkAI::ReceiveAIEvent(), npc_chess_piece_genericAI::ReceiveAIEvent(), boss_razorscaleAI::ReceiveAIEvent(), npc_ghoul_feeding_bunnyAI::ReceiveAIEvent(), boss_general_vezaxAI::ReceiveAIEvent(), mob_soaring_eagleAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), npc_dawnblade_blood_knight::ReceiveAIEvent(), Creature::ReduceCorpseDecayTimer(), GameObject::Refresh(), npc_bt_battle_sensor::ReinforceAldorScryerFrontline(), CreatureAI::RelinquishFollow(), Unit::RemoveAllDynObjects(), Unit::RemoveAurasDueToSpell(), Creature::RemoveCorpse(), dummy_dragonAI::RemoveDebuff(), Unit::RemoveDynObject(), RemoveFromClientUpdateList(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), Pet::RemoveFromWorld(), Unit::RemoveGuardians(), GameObject::RemoveModelFromMap(), Unit::RemoveNotOwnTrackedTargetAuras(), RemoveStringId(), Player::RepopAtGraveyard(), npc_kelerun_bloodmournAI::Reset(), boss_aranAI::Reset(), boss_anetheronAI::Reset(), npc_beast_combat_stalkerAI::Reset(), npc_concentrated_bulletAI::Reset(), boss_malygosAI::Reset(), npc_arcane_beamAI::Reset(), boss_exarch_maladaarAI::Reset(), npc_warp_gate::Reset(), npc_salhadaarAI::Reset(), npc_doctorAI::Reset(), npc_manaforge_control_consoleAI::ResetControlConsoleAndDespawn(), Pet::ResetCorpseRespawn(), Creature::ResetEntry(), Player::ResetMap(), OutdoorPvPTF::ResetTowers(), Creature::Respawn(), GameObject::Respawn(), boss_ossirianAI::RespawnFirstCrystal(), OutdoorPvP::RespawnGO(), npc_drijyaAI::RespawnGo(), Player::ResurrectPlayer(), npc_evergrove_druidAI::ReturnToSpawn(), Player::RewardQuest(), Player::RewardReputation(), npc_xiri::RunAkamaRPEvent(), Player::SatisfyQuestCondition(), Creature::SaveRespawnTime(), GameObject::SaveRespawnTime(), ScourgeMinion::ScourgeMinion(), Unit::SelectAttackingTarget(), Unit::SelectAttackingTargets(), npc_mimiron_flamesAI::SelectClosestSpreadTarget(), Unit::SelectHostileTarget(), boss_zumrahAI::SelectNearbyShallowGrave(), boss_thorimAI::SelectRandomUpperBunny(), SendBgNeutralToPlayer(), Spell::SendChannelStart(), World::SendDefenseMessage(), World::SendDefenseMessageBroadcastText(), boss_sartharionAI::SendFlameTsunami(), npc_bt_battle_sensor::SendIllidariAttack(), Player::SendInitialPacketsBeforeAddToMap(), Player::SendInitialSpells(), Player::SendInitWorldStates(), WorldSession::SendListInventory(), SendMessageToAllWhoSeeMe(), SendMessageToSet(), Player::SendMessageToSet(), SendMessageToSetExcept(), SendMessageToSetInRange(), Player::SendMessageToSetInRange(), WorldSession::SendPetNameQuery(), Player::SendPreparedQuest(), Player::SendQuestGiverStatusMultiple(), Spell::SendSpellGo(), WorldSession::SendSpiritResurrect(), WorldSession::SendTaxiStatus(), WorldSession::SendTrainerList(), Group::SendUpdateTo(), BattlefieldWG::SendWintergraspWarning(), World::SendZoneUnderAttackMessage(), SetActiveObjectState(), OutdoorPvP::SetBannerVisual(), Player::SetBattleGroundEntryPoint(), OutdoorPvPZM::SetBeaconArtKit(), npc_twiggy_flatheadAI::SetChallengerReady(), Creature::SetDeathState(), TemporarySpawn::SetDeathState(), Unit::SetFleeing(), mob_arugal_voidwalkerAI::SetFollower(), GenericTransport::SetGoState(), Unit::SetInCombatState(), Creature::SetInCombatWithZone(), SetNotifyOnEventState(), Player::SetPosition(), Creature::SetSpellList(), SetStringId(), TemporarySpawn::SetSummonProperties(), Spell::SetTargetMap(), Camera::SetView(), boss_volkhanAI::ShatterGolems(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), npc_soulgrinderAI::SpawnCreature(), npc_regthar_deathgateAI::SpawnCreature(), instance_mount_hyjal::SpawnInvasionWave(), Transport::SpawnPassengers(), Spell::Spell(), SpellAuraHolder::SpellAuraHolder(), npc_private_hendelAI::SpellHit(), boss_ahuneAI::SpellHit(), npc_dorius_stonetenderAI::SpellHit(), npc_warp_gate::SpellHit(), npc_injured_patientAI::SpellHit(), boss_scarlet_commander_mograineAI::SpellHit(), npc_dawnblade_blood_knight::StartDuel(), npc_adyen_the_lightwardenAI::StartEvent(), Creature::StartPickpocketRestockTimer(), npc_theramore_spar_controller::StartSparring(), boss_majordomoAI::StartSummonEvent(), npc_dawnblade_blood_knight::StopDuel(), TemporarySpawn::Summon(), Totem::Summon(), SummonCreature(), npc_soulgrinderAI::SummonedCreatureDespawn(), npc_deathstalker_faerleiaAI::SummonedCreatureJustDied(), npc_regthar_deathgateAI::SummonedCreatureJustDied(), npc_apprentice_mirvedaAI::SummonedCreatureJustDied(), npc_eris_havenfireAI::SummonedCreatureJustDied(), boss_jedogaAI::SummonedCreatureJustDied(), npc_emilyAI::SummonedCreatureJustDied(), boss_varosAI::SummonedCreatureJustDied(), boss_kologarnAI::SummonedCreatureJustDied(), npc_soulgrinderAI::SummonedCreatureJustDied(), boss_terestianAI::SummonedCreatureJustDied(), boss_akilzonAI::SummonedCreatureJustDied(), npc_image_of_medivhAI::SummonedMovementInform(), npc_twiggy_flatheadAI::SummonedMovementInform(), npc_emilyAI::SummonedMovementInform(), npc_xiri::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), boss_kelthuzadAI::SummonIntroCreatures(), GameObject::SummonLinkedTrapIfAny(), npc_theramore_spar_controller::SwitchMembers(), boss_gurtogg_bloodboilAI::SwitchPhase(), Unit::TakePossessOf(), LFGMgr::TeleportPlayer(), Player::TeleportTo(), Transport::TeleportTransport(), three_nature_alliesAI::three_nature_alliesAI(), GameObject::TickCapturePoint(), npc_simone_the_inconspicuousAI::Transform(), trial_companion_commonAI::trial_companion_commonAI(), Unit::TriggerAggroLinkingEvent(), Unit::TriggerEvadeEvents(), Unit::TriggerHomeEvents(), Unit::TriggerProccedSpell(), Aura::TriggerSpell(), GameObject::TriggerSummoningRitual(), boss_kurinnaxxAI::TriggerTrap(), CreatureLinkingHolder::TryFollowMaster(), npc_commander_dawnforgeAI::TurnToEachOther(), npc_commander_dawnforgeAI::TurnToPathaleonsImage(), OutdoorPvPNA::UnlockHalaa(), OutdoorPvPGH::UnlockLighthouse(), SpellAuraHolder::UnregisterAndCleanupTrackedAuras(), TemporarySpawn::UnSummon(), OutdoorPvPEP::UnsummonFlightMaster(), boss_majordomoAI::UnsummonMajordomoAdds(), OutdoorPvPEP::UnsummonSoldiers(), CombatManager::Update(), instance_deadmines::Update(), instance_uldaman::Update(), Creature::Update(), DynamicObject::Update(), GameObject::Update(), Pet::Update(), Player::Update(), TemporarySpawn::Update(), ElevatorTransport::Update(), Transport::Update(), Unit::Update(), GameObjectAura::Update(), Spell::update(), SpellCastTargets::Update(), AchievementMgr::UpdateAchievementCriteria(), PetAI::UpdateAI(), TotemAI::UpdateAI(), npc_forest_frogAI::UpdateAI(), DreadsteedQuestObjects::UpdateAI(), boss_eranikusAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), go_screaming_hall_door::UpdateAI(), go_aura_generator_000AI::UpdateAI(), go_brewfest_music::UpdateAI(), go_midsummer_music::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), PlayerbotAI::UpdateAI(), boss_pyroguard_emberseerAI::UpdateAI(), npc_kelerun_bloodmournAI::UpdateAI(), npc_infused_crystalAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), boss_bigbadwolfAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), npc_dashel_stonefistAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_malfurionAI::UpdateAI(), npc_calvin_montagueAI::UpdateAI(), boss_archaedasAI::UpdateAI(), go_infernaling_summoner_portal_hound::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), boss_tethyrAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), npc_twiggy_flatheadAI::UpdateAI(), npc_precious_the_devourerAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), boss_jedogaAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), npc_sinkhole_kill_creditAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), boss_icehowlAI::UpdateAI(), npc_king_ymironAI::UpdateAI(), npc_web_wrapAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_sartharionAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_freyaAI::UpdateAI(), npc_nature_bombAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_sifAI::UpdateAI(), boss_heart_deconstructorAI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), boss_ymironAI::UpdateAI(), boss_murmurAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), npc_bird_spiritAI::UpdateAI(), npc_warp_gate::UpdateAI(), npc_soulgrinderAI::UpdateAI(), npc_supplicantAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), npc_danath_trollbaneAI::UpdateAI(), npc_nazgrelAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), npc_commander_dawnforgeAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), go_infernaling_summoner::UpdateAI(), guard_shattrath_aldorAI::UpdateAI(), guard_shattrath_scryerAI::UpdateAI(), npc_doctorAI::UpdateAI(), npc_injured_patientAI::UpdateAI(), npc_spring_rabbitAI::UpdateAI(), npc_redemption_targetAI::UpdateAI(), npc_mage_mirror_imageAI::UpdateAI(), npc_power_blue_flightAI::UpdateAI(), npc_flash_freezeAI::UpdateAI(), npc_warlock_mount_ritualAI::UpdateAI(), UpdateAllowedPositionZ(), Unit::UpdateAllowedPositionZ(), npc_reginald_windsorAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_harrison_jones_zaAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_harrison_jonesAI::UpdateEscortAI(), npc_maxx_a_million_escortAI::UpdateEscortAI(), npc_garments_of_questsAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), Player::UpdateEverything(), Player::UpdateForQuestWorldObjects(), TransportBase::UpdateGlobalPositionOf(), UpdateGroundPositionZ(), GameObject::UpdateModel(), GameObject::UpdateModelPosition(), UpdateObjectVisibility(), Spell::UpdateOriginalCasterPointer(), GenericTransport::UpdatePassengerPosition(), npc_runic_colossusAI::UpdateRunicSmash(), UnitAI::UpdateSpellLists(), Unit::UpdateSplinePosition(), BattlefieldWG::UpdateTenacities(), npc_scrap_reaverAI::UpdateTimers(), Player::UpdateZone(), GameObject::Use(), ObjectGridRespawnMover::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Cell::VisitWorldObjects(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_ranger_lilathaAI::WaypointReached(), npc_adyen_the_lightwardenAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_tirion_fordringAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_ranshallaAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_wounded_blood_elfAI::WaypointReached(), npc_drijyaAI::WaypointReached(), npc_galen_goodwardAI::WaypointStart(), npc_stinky_ignatzAI::WaypointStart(), and npc_commanderAI::WinEvent().
GetMapId()
uint32 WorldObject::GetMapId () const inline
Definition at line 1043 of file Object.h.
References m_mapId.
Referenced by Group::_addMember(), PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandSurvey(), Player::_LoadInventory(), Unit::_UpdateSpells(), Player::ActivateTaxiPathTo(), ObjectAccessor::AddCorpse(), Map::AddObjectToRemoveList(), Creature::AddToWorld(), boss_victor_nefariusAI::boss_victor_nefariusAI(), PathFinder::BuildPolyPath(), PathFinder::calculate(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), ObjectAccessor::ConvertCorpseForPlayer(), GameObject::DeleteFromDB(), Player::DestroyZoneLimitedItem(), Spell::DoAllEffectOnTarget(), PlayerbotAI::DoLoot(), ScriptedAI::DoTeleportPlayer(), Spell::EffectStuck(), Spell::EffectSummonPlayer(), Spell::EffectTeleportUnits(), ConditionEntry::Evaluate(), PlayerbotAI::findNearbyCreature(), LFGMgr::FinishDungeon(), MaNGOS::XP::Gain(), Player::GetAreaTriggerLockStatus(), ObjectAccessor::GetCorpseInMap(), CreatureLinkingMgr::GetLinkedTriggerInformation(), Player::GetNextQuest(), GMTicket::GMTicket(), GossipHello_boss_victor_nefarius(), GossipSelect_boss_victor_nefarius(), NamreebAnticheat::Movement::HandleAnticheatTests(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleCorpseQueryOpcode(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCommand(), ChatHandler::HandleGoGridCommand(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleGoXYCommand(), ChatHandler::HandleGoXYZCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleGroupgoCommand(), WorldSession::HandleGroupInviteOpcode(), ChatHandler::HandleInstanceUnbindCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapStatsCommand(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleTriggerActiveCommand(), ChatHandler::HandleTriggerCommand(), ChatHandler::HandleTriggerNearCommand(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), CreatureEventAI::InitAI(), Creature::InitEntry(), MotionMaster::Initialize(), FollowMovementGenerator::IsBoostAllowed(), npc_smolderwing::JustRespawned(), Player::KillPlayer(), Player::LoadFromDB(), ChatHandler::LogCommand(), AchievementCriteriaRequirement::Meets(), Unit::NearTeleportTo(), CurseOfBoundlessAgony::OnApply(), FlagClickBg::OnCheckCast(), spell_split_teleport_boat::OnEffectExecute(), spell_gunship_portal_click::OnEffectExecute(), EyeOfKilrogg::OnSummon(), Player::OnTaxiFlightSplineUpdate(), NamreebAnticheat::Movement::OnTransport(), FindCreatureData::operator()(), FindGOData::operator()(), PathFinder::PathFinder(), Player::PrepareQuestMenu(), PrintCoordinatesError(), Player::QueueOrAddResurrectRequest(), GMTicket::Recycle(), ObjectAccessor::RemoveCorpse(), Player::RepopAtGraveyard(), boss_victor_nefariusAI::Reset(), npc_kalecgosAI::Reset(), Group::RewardGroupAtKill(), Player::RewardReputation(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Creature::SaveToDB(), Player::SaveToDB(), GameObject::SaveToDB(), Spell::SelectMountByAreaAndSkill(), Map::SendInitTransports(), Player::SendInitWorldStates(), WorldSession::SendLearnNewTaxiNode(), Player::SendOverrideLightUpdate(), Map::SendRemoveTransports(), WorldSession::SendSpiritResurrect(), GroupLootRoll::SendStartRoll(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Player::SetBattleGroundEntryPoint(), PathFinder::SetCurrentNavMesh(), Pet::SetDeathState(), Spell::SetTargetMap(), CreatureEventAI::SpawnedEventConditionsCheck(), LFGMgr::TeleportPlayer(), Player::TeleportTo(), Transport::TeleportTransport(), Transport::Update(), Unit::Update(), SpellCastTargets::Update(), AchievementMgr::UpdateAchievementCriteria(), boss_victor_nefariusAI::UpdateAI(), npc_smolderwing::UpdateAI(), Player::UpdateAreaDependentAuras(), MotionMaster::UpdateMotion(), Unit::UpdateSplineMovement(), and GameObject::Use().
GetName()
char const* WorldObject::GetName () const inline
Definition at line 1058 of file Object.h.
References m_name.
Referenced by PlayerbotAI::_HandleCommandGM(), PlayerbotAI::_HandleCommandMail(), PlayerbotAI::_HandleCommandQuest(), PlayerbotAI::_HandleCommandStats(), Player::_LoadBoundInstances(), Player::_LoadInventory(), Player::_LoadItemLoot(), Player::_LoadQuestStatus(), Player::_SaveInventory(), DungeonMap::Add(), AuctionHouseObject::AddAuction(), Group::AddLeaderInvite(), ArenaTeam::AddMember(), Guild::AddMember(), BattleGround::AddOrSetPlayerToCorrectBgGroup(), GenericTransport::AddPassenger(), BattleGround::AddPlayer(), Player::BindToInstance(), Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), WorldSession::BuildPartyMemberStatsChangedPacket(), Player::BuildPlayerRepop(), Battlefield::CanAddPlayerToRaid(), Corpse::Create(), Transport::DoEventIfAny(), PlayerbotAI::DoLoot(), Player::DuelComplete(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectStuck(), Map::EnsureGridLoadedAtEnter(), ChatHandler::ExtractPlayerTarget(), PlayerbotAI::GetCombatTarget(), SocialMgr::GetFriendInfo(), Player::GetGameObjectIfCanInteractWith(), Creature::GetNameForLocaleIdx(), GameObject::GetNameForLocaleIdx(), GetNameForLocaleIdx(), ChatHandler::GetNameLink(), WorldSession::GetPlayerName(), ReputationMgr::GetReputation(), GMTicket::GMTicket(), GossipSelectWithCode_example_gossip_codebox(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleAddFriendOpcodeCallBack(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), PlayerbotAI::HandleBotOutgoingPacket(), ChatHandler::HandleCharacterTitlesCommand(), WorldSession::HandleChatIgnoredOpcode(), ChatHandler::HandleCombatListCommand(), PlayerbotAI::HandleCommand(), ChatHandler::HandleDebugHaveAtClientCommand(), ChatHandler::HandleDebugIsVisibleCommand(), ChatHandler::HandleDebugSendOpcodeCommand(), ChatHandler::HandleDebugSetValueByNameCommand(), WorldSession::HandleDuelAcceptedOpcode(), WorldSession::HandleForceSpeedChangeAckOpcodes(), ChatHandler::HandleGPSCommand(), WorldSession::HandleGrantLevel(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupDisbandOpcode(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildDeclineOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), ChatHandler::HandleLevelUpCommand(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), ChatHandler::HandleLookupTitleCommand(), WorldSession::HandleMailTakeItem(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleMessagechatOpcode(), Aura::HandleMirrorName(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMovegensCommand(), ChatHandler::HandleMovespeedShowCommand(), ChatHandler::HandleMuteCommand(), ChatHandler::HandleNamegoCommand(), WorldSession::HandleNameQueryOpcode(), ChatHandler::HandleNpcFollowCommand(), ChatHandler::HandleNpcThreatCommand(), ChatHandler::HandleNpcUnFollowCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandlePetSetAction(), BattleGroundEY::HandlePlayerClickedOnFlag(), OutdoorPvP::HandlePlayerLeaveZone(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), WorldSession::HandleReportPvPAFK(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ChatHandler::HandleResetModsCommand(), WorldSession::HandleShowingCloakOpcode(), WorldSession::HandleShowingHelmOpcode(), NamreebAnticheat::Movement::HandleSpeedChangeAck(), ChatHandler::HandleTitlesAddCommand(), ChatHandler::HandleTitlesRemoveCommand(), WorldSession::HandleWhoOpcode(), AbstractPathMovementGenerator::Initialize(), Player::IsActionButtonDataValid(), ReputationMgr::IsAtWar(), Player::LoadFromDB(), ChatHandler::LogCommand(), WorldSession::LogoutPlayer(), ChatHandler::ModifyStatCommandHelper(), MonsterSay(), MonsterTextEmote(), MonsterWhisper(), MonsterYell(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), WorldSession::moveItems(), dummy_dragonAI::MovementInform(), Player::OnTaxiFlightRouteProgress(), BattleGroundBroadcastBuilder::operator()(), MaNGOS::BattleGroundChatBuilder::operator()(), MaNGOS::BattleGroundYellBuilder::operator()(), MaNGOS::BattleGroundMessageBuilder::operator()(), MaNGOS::BattleGroundBroadcastBuilder::operator()(), MaNGOS::BattleGround2ChatBuilder::operator()(), NamreebAnticheat::Movement::OrderAck(), NamreebAnticheat::Movement::OrderSent(), PlayerbotAI::PickPocket(), Map::PlayerRelocation(), Player::QueueOrAddResurrectRequest(), GMTicket::Recycle(), Map::Remove(), DungeonMap::Remove(), BattleGroundMap::Remove(), GenericTransport::RemovePassenger(), BattleGround::RemovePlayerAtLeave(), PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), PlayerbotShamanAI::ResurrectPlayer(), PlayerbotChatHandler::revive(), Player::Say(), Channel::Say(), AchievementMgr::SendAchievementEarned(), AuctionHouseMgr::SendAuctionWonMail(), WorldSession::SendGroupInvite(), PlayerbotAI::SendOrders(), WorldSession::SendPetNameQuery(), WorldSession::SendStablePet(), BattleGroundMgr::SendToBattleGround(), PlayerbotAI::SendWhisper(), PlayerbotAI::SetCombatOrder(), Player::SetEquipmentSet(), MemberSlot::SetMemberStats(), ChatHandler::ShowAccountListHelper(), FollowerAI::StartFollow(), boss_brutallusAI::SummonedCreatureJustDied(), PlayerbotChatHandler::teleport(), LFGMgr::TeleportPlayer(), Player::TextEmote(), NamreebAnticheat::Movement::TimeSkipped(), Player::Update(), Transport::Update(), dummy_dragonAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), Player::UpdateHomebindTime(), GenericTransport::UpdatePassengerPosition(), NamreebAnticheat::Movement::VerifyMovementFlags(), Player::Whisper(), and Player::Yell().
GetNameForLocaleIdx()
virtual const char* WorldObject::GetNameForLocaleIdx (int32) const inline virtual
Reimplemented in Pet, GameObject, and Creature.
Definition at line 1062 of file Object.h.
References GetName().
Referenced by Pet::GetNameForLocaleIdx(), MaNGOS::EmoteChatBuilder::operator()(), MaNGOS::MonsterChatBuilder::operator()(), and Player::QueueOrAddResurrectRequest().
GetNameStr()
std::string const& WorldObject::GetNameStr () const inline
Definition at line 1059 of file Object.h.
References m_name.
Referenced by ChatHandler::HandleCooldownClearCommand(), PlayerNameMapHolder::Insert(), and PlayerNameMapHolder::Remove().
GetNearPoint()
void WorldObject::GetNearPoint (WorldObject const * searcher, float & x, float & y, float & z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater = false) const inline
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
Parameters
searcher - for whom a spot is searched for
x,y,z - position for the found spot of the searcher
searcher_bounding_radius - how much space the searcher will require
distance2d - distance between the middle-points
absAngle - angle in which the spot is preferred
Definition at line 991 of file Object.h.
References GetNearPointAt(), GetPositionX(), GetPositionY(), and GetPositionZ().
Referenced by boss_felmystAI::Aggro(), CheckPathToTarget(), boss_jedogaAI::DoCallVolunteers(), boss_hydross_the_unstableAI::DoSpawnAdds(), npc_demoniac_scryerAI::DoSpawnButtress(), npc_feero_ironhandAI::DoSpawnMob(), boss_uromAI::DoSpawnTrashPack(), npc_teleportation_portalAI::DoSummon(), boss_anzuAI::DoSummonBirdHelpers(), Spell::EffectScriptEffect(), Spell::EffectStuck(), npc_bashir_flesh_fiendAI::ExecuteActions(), GetClosePoint(), GetContactPoint(), instance_trial_of_the_champion::InformChampionReachHome(), boss_saraAI::JustSummoned(), npc_taelan_fordringAI::JustSummoned(), boss_doomwalkerAI::JustSummoned(), spell_slave_trigger_closest::OnEffectExecute(), spell_summon_undead::OnEffectExecute(), ProcessEventId_event_go_focusing_iris(), npc_spring_rabbitAI::StartWhatRabbitsDo(), instance_trial_of_the_champion::Update(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), and npc_injured_rainspeakerAI::WaypointReached().
GetNearPoint2d()
void WorldObject::GetNearPoint2d (float & x, float & y, float distance2d, float absAngle) const inline
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
Definition at line 979 of file Object.h.
References GetNearPoint2dAt(), GetPositionX(), and GetPositionY().
Referenced by Spell::EffectDummy(), Spell::EffectTransmitted(), boss_lord_marrowgarAI::JustSummoned(), and Spell::SetTargetMap().
GetNearPoint2dAt()
void WorldObject::GetNearPoint2dAt (const float posX, const float posY, float & x, float & y, float distance2d, float absAngle) static
Definition at line 2447 of file Object.cpp.
References MaNGOS::NormalizeMapCoord().
Referenced by GetNearPoint2d(), and GetNearPointAt().
GetNearPointAt()
void WorldObject::GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const * searcher, float & x, float & y, float & z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater = false) const
Definition at line 2456 of file Object.cpp.
References ObjectPosSelector::CheckOriginalAngle(), CONFIG_BOOL_DETECT_POS_COLLISION, GetCollisionHeight(), GetMap(), GetNearPoint2dAt(), GetObjectBoundingRadius(), ObjectPosSelector::InitializeAngle(), IsWithinLOSForMe(), ObjectPosSelector::NextAngle(), ObjectPosSelector::NextUsedAngle(), sWorld, UpdateAllowedPositionZ(), and UpdateGroundPositionZ().
Referenced by GetNearPoint().
GetObjectBoundingRadius()
virtual float WorldObject::GetObjectBoundingRadius () const inline virtual
Reimplemented in Unit, and DynamicObject.
Definition at line 1023 of file Object.h.
References DEFAULT_WORLD_OBJECT_SIZE.
Referenced by MaNGOS::NearUsedPosDo::add(), ObjectPosSelector::AddUsedArea(), PlayerbotAI::DoLoot(), Spell::EffectActivateObject(), PlayerbotAI::findNearbyCreature(), GetClosePoint(), GetContactPoint(), GetDistance(), GetDistance2d(), GetNearPointAt(), IsInRange(), IsInRange2d(), IsInRange3d(), Spell::SetTargetMap(), and Cell::Visit().
GetOrientation()
float WorldObject::GetOrientation () const inline
Definition at line 976 of file Object.h.
References m_position, and Position::o.
Referenced by GenericTransport::AddPassenger(), npc_ouro_spawnerAI::Aggro(), AreaTrigger_at_frostworn_general(), ChaseMovementGenerator::Backpedal(), VehicleInfo::Board(), Object::BuildMovementUpdate(), VehicleInfo::CalculateBoardingPositionOf(), GenericTransport::CalculatePassengerOffset(), TransportBase::CalculatePassengerOffset(), GenericTransport::CalculatePassengerOrientation(), GenericTransport::CalculatePassengerPosition(), TransportBase::CalculatePassengerPosition(), ObjectAccessor::ConvertCorpseForPlayer(), Corpse::Create(), Pet::CreateBaseAtCreature(), PlayerbotRogueAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVP(), boss_halion_realAI::DoSpawnMeteorStrike(), npc_teleportation_portalAI::DoSummon(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::DoSummonPossessed(), Spell::DoSummonTotem(), Spell::DoSummonVehicle(), Spell::DoSummonWild(), Spell::EffectActivateObject(), Spell::EffectCreateTamedPet(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectJump(), Spell::EffectLeapForward(), Spell::EffectScriptEffect(), Spell::EffectStuck(), Spell::EffectSummonDeadPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTeleportUnits(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), boss_telestraAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), ChaseMovementGenerator::FanOut(), GetClosePoint(), GameObject::GetClosestChairSlotPosition(), Pet::GetPetSpawnPosition(), GetPosition(), GameObject::GetStationaryO(), GMTicket::GMTicket(), BattleGroundDS::HandleAreaTrigger(), Aura::HandleAuraDummy(), Aura::HandleAuraModStun(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGoHelper(), ChatHandler::HandleGoWarpCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleGroupgoCommand(), boss_felmystAI::HandleLiftoff(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNpcAddCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcTempSpawn(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), BattleGroundBE::HandlePlayerUnderMap(), BattleGroundDS::HandlePlayerUnderMap(), BattleGroundNA::HandlePlayerUnderMap(), BattleGroundRL::HandlePlayerUnderMap(), BattleGroundRV::HandlePlayerUnderMap(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), HasInArc(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), VehicleInfo::Initialize(), GameObjectModel::initialize(), mob_webbed_creatureAI::JustDied(), go_fel_cannonball_stack_trap::JustSpawned(), npc_meteor_strike_initialAI::JustSummoned(), npc_taelan_fordringAI::JustSummoned(), Unit::KnockBackFrom(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), MinionspawnerAI::MinionspawnerAI(), UnitAI::OnChannelStateChange(), instance_zulaman::OnCreatureCreate(), world_map_ebon_hold::OnCreatureDeath(), spell_gunship_portal_click::OnEffectExecute(), spell_summon_players::OnEffectExecute(), spell_wailing_souls_aura::OnPeriodicDummy(), SpoutTurning::OnPeriodicTrigger(), UnitAI::OnSpellCastStateChange(), Player::OnTaxiFlightEnd(), Player::OnTaxiFlightSplineUpdate(), Spell::Prepare(), ProcessEventId_event_purify_food(), npc_chess_piece_genericAI::ReceiveAIEvent(), GMTicket::Recycle(), Relocate(), GameObjectModel::Relocate(), npc_simone_the_inconspicuousAI::Reset(), Player::ResurrectUsingRequestDataInit(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Player::SetBattleGroundEntryPoint(), GameObject::SetLocalRotation(), Player::SetPosition(), CharmInfo::SetStayPosition(), Spell::SetTargetMap(), npc_belnistraszAI::SpawnerSummon(), boss_veklorAI::SpellHit(), npc_frostbiteAI::SpellHit(), boss_lethonAI::SpellHitTarget(), boss_soccothratesAI::SpellHitTarget(), Movement::MoveSplineInit::Stop(), SummonCreature(), Player::SummonIfPossible(), GameObject::SummonLinkedTrapIfAny(), Unit::TakePossessOf(), LFGMgr::TeleportPlayer(), Player::TeleportToHomebind(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), VehicleInfo::UnBoard(), instance_stratholme::Update(), ElevatorTransport::Update(), TransportBase::Update(), Spell::update(), PlayerbotAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), npc_doomfire_targetingAI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), TransportBase::UpdateGlobalPositions(), Unit::UpdateSplinePosition(), GameObject::Use(), npc_maxx_a_million_escortAI::WaypointReached(), and npc_injured_rainspeakerAI::WaypointReached().
GetOwnerGuid()
virtual ObjectGuid const& WorldObject::GetOwnerGuid () const inline virtual
Reimplemented in Unit, GameObject, DynamicObject, and Corpse.
Definition at line 1064 of file Object.h.
References Object::GetGuidValue(), and OBJECT_FIELD_GUID.
GetParentHigh()
virtual HighGuid WorldObject::GetParentHigh () const inline virtual
Reimplemented in GameObject, and Creature.
Definition at line 1256 of file Object.h.
Referenced by Map::AddDbGuidObject(), and Map::RemoveDbGuidObject().
GetPhaseMask()
uint32 WorldObject::GetPhaseMask () const inline
Definition at line 1047 of file Object.h.
References m_phaseMask.
Referenced by Unit::AdjustZForCollision(), CheckPathToTarget(), PathFinder::ComputePathToRandomPoint(), ObjectAccessor::ConvertCorpseForPlayer(), Corpse::Create(), DynamicObject::Create(), ChaseMovementGenerator::CutPath(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::DoSummonTotem(), Spell::DoSummonVehicle(), Spell::DoSummonWild(), EffectAuraDummy_npc_scourged_flamespitter(), Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTransmitted(), ScriptAction::ExecuteDbscriptCommand(), NamreebAnticheat::Movement::ExtrapolateMovement(), PlayerbotClassAI::FleeFromPointIfCan(), Player::GetPhaseMaskForSpawn(), Map::GetReachableRandomPosition(), ChatHandler::HandleGoHelper(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleNpcInfoCommand(), Helper_CreateWaypointFor(), GameObjectModel::initialize(), InSamePhase(), Unit::IsAboveGround(), IsWithinLOS(), IsWithinLOSForMe(), Unit::KnockBackWithAngle(), Movement::MoveSplineInit::Launch(), Pet::LoadPetFromDB(), FollowMovementGenerator::Move(), MotionMaster::MoveFall(), MovePositionToFirstCollision(), SummonVoidSentinelSummoner::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), Corpse::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), Player::SetPhaseMask(), Unit::SetPhaseMask(), Spell::SetTargetMap(), instance_mount_hyjal::SpawnInvasionWave(), SummonCreature(), GameObject::SummonLinkedTrapIfAny(), Unit::TakePossessOf(), boss_onyxiaAI::UpdateAI(), UpdateAllowedPositionZ(), Unit::UpdateAllowedPositionZ(), GameObject::UpdateCollisionState(), and UpdateGroundPositionZ().
GetPosition() [1/3]
void WorldObject::GetPosition (float & x, float & y, float & z, GenericTransport * transport = nullptr) const
Definition at line 2166 of file Object.cpp.
References GenericTransport::CalculatePassengerOffset(), Object::GetObjectGuid(), GetPositionX(), GetPositionY(), GetPositionZ(), m_movementInfo, MovementInfo::t_guid, MovementInfo::t_pos, Position::x, Position::y, and Position::z.
Referenced by ChaseMovementGenerator::_getLocation(), FollowMovementGenerator::_getLocation(), GameObject::_IsWithinDist(), ChaseMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), ChaseMovementGenerator::Backpedal(), PathFinder::calculate(), Spell::CalculateDelayMomentForDst(), go_aura_generator::CheckAndApplyAura(), PathFinder::ComputePathToRandomPoint(), ChaseMovementGenerator::DispatchSplineToPosition(), boss_nightbaneAI::DoMoveToClosestTrigger(), npc_flame_of_azzinothAI::DoPickChargeTarget(), Spell::EffectBind(), Spell::EffectDummy(), Spell::EffectForceCast(), Spell::EffectKnockBackFromPosition(), Spell::EffectSchoolDMG(), Spell::EffectSummonPlayer(), Spell::EffectSummonType(), Spell::EffectTransmitted(), Spell::EffectTriggerSpell(), npc_living_mojoAI::EnterEvadeMode(), npc_flame_of_azzinothAI::ExecuteAction(), PlayerbotClassAI::FleeFromAoEIfCan(), FleeingMovementGenerator::FleeingMovementGenerator(), GetDistance(), GetFirstCollisionPosition(), GetFirstRandomAngleCollisionPosition(), Player::GetNextRaidMemberWithLowestLifePercentage(), GetPosition(), ChatHandler::HandleGetLosCommand(), ChatHandler::HandleGPSCommand(), FormationMovementGenerator::HandleMasterDistanceCheck(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapTestArea(), ChatHandler::HandleMmapTestHeight(), WorldSession::HandleMoveWorldportAckOpcode(), boss_illidan_stormrageAI::HandlePhaseTransition(), ChatHandler::HandleRespawnCommand(), ChaseMovementGenerator::HandleTargetedMovement(), FollowMovementGenerator::HandleTargetedMovement(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), WaypointMovementGenerator< Creature >::InitializeWaypointPath(), WaypointMovementGenerator< Creature >::Interrupt(), FormationMovementGenerator::Interrupt(), Unit::IsAboveGround(), GameObject::IsAtInteractDistance(), FollowMovementGenerator::IsBoostAllowed(), ChaseMovementGenerator::IsReachablePositionToTarget(), FollowMovementGenerator::IsUnstuckAllowed(), Unit::IsVisibleForOrDetect(), IsWithinLOS(), IsWithinLOSForMe(), IsWithinLOSInMap(), npc_time_riftAI::JustSummoned(), npc_putricides_trapAI::JustSummoned(), boss_soccothratesAI::JustSummoned(), Unit::KnockBackWithAngle(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), npc_magrami_spectre::MovementInform(), NetherCharge::MoveToRandomPoint(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), WaypointMovementGenerator< Creature >::OnArrived(), TriggerKTAdd::OnCheckTarget(), Spell::OnCheckTarget(), FlignTorch::OnDestTarget(), GluthDecimate::OnEffectExecute(), DemonicCircleTeleport::OnEffectExecute(), NetherVaporLightning::OnPeriodicDummy(), SummonGargoyle::OnSummon(), Player::OnTaxiFlightUpdate(), Player::QueueOrAddResurrectRequest(), Unit::SetInCombatState(), Spell::SetTargetMap(), SpellCastTargets::setUnitTarget(), boss_veklorAI::SpellHit(), Unit::TakeCharmOf(), Unit::TakePossessOf(), VehicleInfo::TeleportPassengers(), CombatManager::TriggerCombatTimer(), VehicleInfo::UnBoard(), CombatManager::Update(), go_aura_generator_000AI::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), PlayerbotAI::UpdateAI(), boss_uromAI::UpdateAI(), and TransportBase::UpdateGlobalPositionOf().
GetPosition() [2/3]
Position const& WorldObject::GetPosition (GenericTransport * transport = nullptr) const inline
Definition at line 975 of file Object.h.
References MovementInfo::GetTransportPos(), m_movementInfo, and m_position.
GetPosition() [3/3]
void WorldObject::GetPosition (WorldLocation & loc) const inline
Definition at line 973 of file Object.h.
References WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, GetOrientation(), GetPosition(), m_mapId, WorldLocation::mapid, and WorldLocation::orientation.
GetPositionX()
float WorldObject::GetPositionX () const inline
Definition at line 968 of file Object.h.
References m_position, and Position::x.
Referenced by PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandSurvey(), Player::ActivateTaxiPathTo(), Map::ActiveObjectsNearGrid(), Map::Add(), MaNGOS::NearUsedPosDo::add(), ObjectAccessor::AddCorpse(), Spell::AddGOTarget(), GenericTransport::AddPassenger(), Map::AddToActive(), Spell::AddUnitTarget(), boss_thermapluggAI::Aggro(), npc_ouro_spawnerAI::Aggro(), AreaTrigger_at_frostworn_general(), npc_dragonmaw_racerAI::AttackPlayer(), SentryTotemAI::AttackStart(), VehicleInfo::Board(), boss_razorscaleAI::boss_razorscaleAI(), Object::BuildMovementUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), FormationMovementGenerator::BuildPath(), VehicleInfo::CalculateBoardingPositionOf(), GenericTransport::CalculatePassengerOffset(), TransportBase::CalculatePassengerOffset(), GenericTransport::CalculatePassengerPosition(), TransportBase::CalculatePassengerPosition(), boss_ionarAI::CallBackSparks(), Unit::CanReachWithMeleeAttack(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckScriptTargeting(), ObjectAccessor::ConvertCorpseForPlayer(), Corpse::Create(), DynamicObject::Create(), Map::CreatePlayerOnClient(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), UnitAI::DoCastSpellIfCan(), PlayerbotAI::DoLoot(), npc_fel_guard_houndAI::DoMoveToCorpse(), boss_brundirAI::DoMoveToTarget(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), boss_midnightAI::DoPrepareMount(), go_elemental_rift::DoRespawnElementalsIfCan(), npc_ruul_snowhoofAI::DoSpawnAmbush(), npc_wildaAI::DoSpawnAssassin(), npc_demoniac_scryerAI::DoSpawnDemon(), world_map_ebon_hold::DoSpawnUndeadWave(), npc_teleportation_portalAI::DoSummon(), boss_headless_horsemanAI::DoTossHead(), Spell::EffectActivateObject(), EffectAuraDummy_npc_scourged_flamespitter(), Spell::EffectDuel(), Spell::EffectDummy(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectPullTowards(), Spell::EffectScriptEffect(), Spell::EffectStuck(), Spell::EffectTeleportUnits(), Spell::EffectTriggerMissileSpell(), npc_manaforge_spawnAI::EnterEvadeMode(), npc_tesla_coilAI::EstablishTarget(), boss_void_reaverAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), Map::ExecuteDistWorker(), PlayerbotAI::findNearbyCreature(), PlayerbotAI::findNearbyGO(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), PlayerbotClassAI::FleeFromTrapGOIfCan(), GetAInpc_ethereum_prisoner_dungeon(), GetAngle(), GetAngleAt(), GameObject::GetClosestChairSlotPosition(), GetDistance(), GetDistance2d(), GetGameObjectListWithEntryInGrid(), GetNearPoint(), GetNearPoint2d(), GetPosition(), FollowMovementGenerator::GetSpeed(), GMTicket::GMTicket(), GOUse_go_furbolg_food(), GOUse_go_stratholme_postbox(), WorldSession::HandleAreaTriggerOpcode(), Aura::HandleAuraDummy(), WorldSession::HandleBattleGroundPlayerPositionsOpcode(), ChatHandler::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), BattlefieldWG::HandleCreatureCreate(), BattleGroundIC::HandleCreatureCreate(), ChatHandler::HandleDebugSendPoiCommand(), Unit::HandleDummyAuraProc(), ChatHandler::HandleGameObjectAddCommand(), BattleGroundIC::HandleGameObjectCreate(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoWarpCommand(), ChatHandler::HandleGPSCommand(), boss_vaelastraszAI::HandleIntro(), boss_felmystAI::HandleLiftoff(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcTempSpawn(), Aura::HandlePeriodicTriggerSpell(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ChaseMovementGenerator::HandleTargetedMovement(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleTriggerActiveCommand(), ChatHandler::HandleTriggerCommand(), ChatHandler::HandleTriggerNearCommand(), HasInArc(), VehicleInfo::Initialize(), GameObjectModel::initialize(), GameObject::IsAtInteractDistance(), isInBack(), isInFront(), Unit::IsInSwimmableWater(), Unit::IsInWater(), NamreebAnticheat::Movement::IsTeleportAllowed(), Unit::IsTriggeredAtSpellProcEvent(), Unit::IsUnderwater(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_simone_seductressAI::JustReachedHome(), boss_razorscaleAI::JustReachedHome(), go_fel_cannonball_stack_trap::JustSpawned(), boss_thermapluggAI::JustSummoned(), npc_00x09hlAI::JustSummoned(), npc_crystal_channel_targetAI::JustSummoned(), boss_valanar_iccAI::JustSummoned(), boss_algalonAI::JustSummoned(), boss_ingvarAI::JustSummoned(), boss_highlord_kruulAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), npc_doom_blossomAI::JustSummoned(), npc_totem_of_spiritsAI::JustSummoned(), NamreebAnticheat::Movement::KnockBack(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), Corpse::LoadFromDB(), ChatHandler::LogCommand(), Unit::MeetsSelectAttackingRequirement(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), MinionspawnerAI::MinionspawnerAI(), mob_bt_battle_fighterAI::mob_bt_battle_fighterAI(), instance_trial_of_the_champion::MoveChampionToHome(), MotionMaster::MoveFall(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_living_poisonAI::MoveInLineOfSight(), npc_shade_of_the_horsemanAI::MovementInform(), npc_champion_mountAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_ethereal_frostworgAI::MoveToNewPoint(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), spell_strangulating_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), Spell::OnCheckTarget(), instance_zulaman::OnCreatureCreate(), instance_scholomance::OnCreatureCreate(), instance_culling_of_stratholme::OnCreatureCreate(), instance_azjol_nerub::OnCreatureCreate(), instance_trial_of_the_champion::OnCreatureCreate(), instance_gundrak::OnCreatureCreate(), instance_icecrown_citadel::OnCreatureCreate(), instance_naxxramas::OnCreatureCreate(), instance_ulduar::OnCreatureCreate(), instance_pinnacle::OnCreatureCreate(), world_map_ebon_hold::OnCreatureDeath(), instance_azjol_nerub::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), spell_gunship_portal_click::OnEffectExecute(), spell_repair_cannon::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_out_cold::OnEffectExecute(), spell_summon_players::OnEffectExecute(), instance_mount_hyjal::OnObjectCreate(), instance_onyxias_lair::OnObjectCreate(), Unit::OnRelocated(), MaNGOS::NearUsedPosDo::operator()(), npc_hungry_nether_rayAI::OwnerKilledUnit(), Map::PlayerRelocation(), Spell::Prepare(), CreatureEventAI::ProcessAction(), ProcessEventId_event_purify_food(), QuestAcceptGO_crystalline_tear(), npc_injured_minerAI::ReceiveAIEvent(), boss_head_of_horsemanAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), GMTicket::Recycle(), CreatureCreatePos::Relocate(), GameObjectModel::Relocate(), Map::Remove(), ObjectAccessor::RemoveCorpse(), Map::RemoveFromActive(), Player::RepopAtGraveyard(), npc_simone_the_inconspicuousAI::Reset(), npc_anubarak_trial_frostsphereAI::Reset(), npc_floating_spiritAI::Reset(), npc_snakesAI::Reset(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), CreatureCreatePos::SelectFinalPoint(), WorldSession::SendLearnNewTaxiNode(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Unit::SendPetDismiss(), Spell::SendSpellGo(), WorldSession::SendSpiritResurrect(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Player::SetBattleGroundEntryPoint(), Player::SetPosition(), CharmInfo::SetStayPosition(), Spell::SetTargetMap(), sortByPositionX(), boss_lady_deathwhisperAI::sortFromNorthToSouth(), instance_dire_maul::SortPylonGuards(), npc_belnistraszAI::SpawnerSummon(), npc_blackwing_orbAI::SpellHit(), boss_veklorAI::SpellHit(), npc_forest_frogAI::SpellHit(), boss_aerial_unitAI::SpellHit(), boss_soccothratesAI::SpellHitTarget(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), Movement::MoveSplineInit::Stop(), trial_companion_commonAI::SummonedMovementInform(), boss_highlord_kruulAI::SummonFormation(), npc_air_force_botsAI::SummonGuard(), boss_kelthuzadAI::SummonIntroCreatures(), GameObject::SummonLinkedTrapIfAny(), LFGMgr::TeleportPlayer(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), Map::Update(), instance_trial_of_the_champion::Update(), world_map_outland::Update(), Transport::Update(), TransportBase::Update(), Spell::update(), guard_hallows_end_helperAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), boss_taldaramAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_death_rayAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), PathFinder::updateFilter(), TransportBase::UpdateGlobalPositions(), UpdateObjectVisibility(), Unit::UpdateSplinePosition(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Cell::VisitWorldObjects(), npc_magwinAI::WaypointReached(), and example_escortAI::WaypointReached().
GetPositionY()
float WorldObject::GetPositionY () const inline
Definition at line 969 of file Object.h.
References m_position, and Position::y.
Referenced by PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandSurvey(), Player::ActivateTaxiPathTo(), Map::ActiveObjectsNearGrid(), Map::Add(), MaNGOS::NearUsedPosDo::add(), ObjectAccessor::AddCorpse(), Spell::AddGOTarget(), GenericTransport::AddPassenger(), Map::AddToActive(), Spell::AddUnitTarget(), boss_thermapluggAI::Aggro(), npc_ouro_spawnerAI::Aggro(), AreaTrigger_at_frostworn_general(), npc_dragonmaw_racerAI::AttackPlayer(), SentryTotemAI::AttackStart(), VehicleInfo::Board(), boss_razorscaleAI::boss_razorscaleAI(), Object::BuildMovementUpdate(), WorldSession::BuildPartyMemberStatsChangedPacket(), FormationMovementGenerator::BuildPath(), VehicleInfo::CalculateBoardingPositionOf(), GenericTransport::CalculatePassengerOffset(), TransportBase::CalculatePassengerOffset(), GenericTransport::CalculatePassengerPosition(), TransportBase::CalculatePassengerPosition(), boss_ionarAI::CallBackSparks(), Unit::CanReachWithMeleeAttack(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckScriptTargeting(), ObjectAccessor::ConvertCorpseForPlayer(), Corpse::Create(), DynamicObject::Create(), Map::CreatePlayerOnClient(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), UnitAI::DoCastSpellIfCan(), PlayerbotAI::DoLoot(), npc_fel_guard_houndAI::DoMoveToCorpse(), boss_brundirAI::DoMoveToTarget(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), boss_midnightAI::DoPrepareMount(), go_elemental_rift::DoRespawnElementalsIfCan(), npc_ruul_snowhoofAI::DoSpawnAmbush(), npc_wildaAI::DoSpawnAssassin(), npc_demoniac_scryerAI::DoSpawnDemon(), world_map_ebon_hold::DoSpawnUndeadWave(), npc_teleportation_portalAI::DoSummon(), boss_headless_horsemanAI::DoTossHead(), Spell::EffectActivateObject(), EffectAuraDummy_npc_scourged_flamespitter(), Spell::EffectDuel(), Spell::EffectDummy(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectPullTowards(), Spell::EffectScriptEffect(), Spell::EffectStuck(), Spell::EffectTeleportUnits(), Spell::EffectTriggerMissileSpell(), npc_manaforge_spawnAI::EnterEvadeMode(), boss_void_reaverAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), Map::ExecuteDistWorker(), PlayerbotAI::findNearbyCreature(), PlayerbotAI::findNearbyGO(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), PlayerbotClassAI::FleeFromTrapGOIfCan(), GetAngle(), GetAngleAt(), GameObject::GetClosestChairSlotPosition(), GetDistance(), GetDistance2d(), GetGameObjectListWithEntryInGrid(), GetNearPoint(), GetNearPoint2d(), GetPosition(), FollowMovementGenerator::GetSpeed(), GMTicket::GMTicket(), GOUse_go_furbolg_food(), GOUse_go_stratholme_postbox(), mob_invis_firework_helper::GroupDeterminerFunc(), WorldSession::HandleAreaTriggerOpcode(), Aura::HandleAuraDummy(), WorldSession::HandleBattleGroundPlayerPositionsOpcode(), ChatHandler::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), OutdoorPvPZM::HandleCreatureCreate(), ChatHandler::HandleDebugSendPoiCommand(), Unit::HandleDummyAuraProc(), ChatHandler::HandleGameObjectAddCommand(), BattleGroundIC::HandleGameObjectCreate(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoWarpCommand(), ChatHandler::HandleGPSCommand(), boss_felmystAI::HandleLiftoff(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandleMmapLocCommand(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcTempSpawn(), Aura::HandlePeriodicTriggerSpell(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), WorldSession::HandleRequestPartyMemberStatsOpcode(), ChaseMovementGenerator::HandleTargetedMovement(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleTriggerActiveCommand(), ChatHandler::HandleTriggerCommand(), ChatHandler::HandleTriggerNearCommand(), HasInArc(), VehicleInfo::Initialize(), GameObjectModel::initialize(), GameObject::IsAtInteractDistance(), isInBack(), isInFront(), instance_naxxramas::IsInRightSideGothArea(), Unit::IsInSwimmableWater(), Unit::IsInWater(), NamreebAnticheat::Movement::IsTeleportAllowed(), Unit::IsTriggeredAtSpellProcEvent(), Unit::IsUnderwater(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_simone_seductressAI::JustReachedHome(), boss_razorscaleAI::JustReachedHome(), go_fel_cannonball_stack_trap::JustSpawned(), boss_thermapluggAI::JustSummoned(), npc_00x09hlAI::JustSummoned(), npc_crystal_channel_targetAI::JustSummoned(), boss_valanar_iccAI::JustSummoned(), boss_algalonAI::JustSummoned(), boss_razorscaleAI::JustSummoned(), boss_ingvarAI::JustSummoned(), boss_highlord_kruulAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), npc_doom_blossomAI::JustSummoned(), npc_totem_of_spiritsAI::JustSummoned(), NamreebAnticheat::Movement::KnockBack(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), Corpse::LoadFromDB(), ChatHandler::LogCommand(), Unit::MeetsSelectAttackingRequirement(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), MinionspawnerAI::MinionspawnerAI(), instance_trial_of_the_champion::MoveChampionToHome(), MotionMaster::MoveFall(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_living_poisonAI::MoveInLineOfSight(), npc_shade_of_the_horsemanAI::MovementInform(), npc_champion_mountAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_ethereal_frostworgAI::MoveToNewPoint(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), spell_strangulating_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), spell_freezing_cloud_aura::OnApply(), Spell::OnCheckTarget(), instance_zulgurub::OnCreatureCreate(), instance_karazhan::OnCreatureCreate(), instance_scholomance::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), instance_old_hillsbrad::OnCreatureCreate(), instance_azjol_nerub::OnCreatureCreate(), instance_trial_of_the_champion::OnCreatureCreate(), instance_icecrown_citadel::OnCreatureCreate(), instance_naxxramas::OnCreatureCreate(), instance_halls_of_stone::OnCreatureCreate(), instance_ulduar::OnCreatureCreate(), world_map_ebon_hold::OnCreatureDeath(), instance_halls_of_stone::OnCreatureRespawn(), spell_gunship_portal_click::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_out_cold::OnEffectExecute(), spell_summon_players::OnEffectExecute(), instance_mount_hyjal::OnObjectCreate(), instance_onyxias_lair::OnObjectCreate(), Unit::OnRelocated(), MaNGOS::NearUsedPosDo::operator()(), npc_hungry_nether_rayAI::OwnerKilledUnit(), Map::PlayerRelocation(), Spell::Prepare(), CreatureEventAI::ProcessAction(), ProcessEventId_event_purify_food(), QuestAcceptGO_crystalline_tear(), boss_head_of_horsemanAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), GMTicket::Recycle(), CreatureCreatePos::Relocate(), GameObjectModel::Relocate(), Map::Remove(), ObjectAccessor::RemoveCorpse(), Map::RemoveFromActive(), Player::RepopAtGraveyard(), npc_simone_the_inconspicuousAI::Reset(), npc_anubarak_trial_frostsphereAI::Reset(), npc_floating_spiritAI::Reset(), npc_snakesAI::Reset(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), CreatureCreatePos::SelectFinalPoint(), WorldSession::SendLearnNewTaxiNode(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Unit::SendPetDismiss(), Spell::SendSpellGo(), WorldSession::SendSpiritResurrect(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Player::SetBattleGroundEntryPoint(), Player::SetPosition(), CharmInfo::SetStayPosition(), Spell::SetTargetMap(), sortFromEastToWest(), instance_dire_maul::SortPylonGuards(), npc_belnistraszAI::SpawnerSummon(), npc_blackwing_orbAI::SpellHit(), npc_forest_frogAI::SpellHit(), boss_tethyrAI::SpellHit(), boss_aerial_unitAI::SpellHit(), boss_soccothratesAI::SpellHitTarget(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), Movement::MoveSplineInit::Stop(), trial_companion_commonAI::SummonedMovementInform(), boss_highlord_kruulAI::SummonFormation(), npc_air_force_botsAI::SummonGuard(), boss_kelthuzadAI::SummonIntroCreatures(), GameObject::SummonLinkedTrapIfAny(), LFGMgr::TeleportPlayer(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), Map::Update(), instance_trial_of_the_champion::Update(), world_map_outland::Update(), Transport::Update(), TransportBase::Update(), Spell::update(), npc_forest_frogAI::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), boss_taldaramAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_death_rayAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), PathFinder::updateFilter(), TransportBase::UpdateGlobalPositions(), UpdateObjectVisibility(), npc_runic_colossusAI::UpdateRunicSmash(), Unit::UpdateSplinePosition(), GameObject::Use(), Cell::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Map::VisitNearbyCellsOf(), Cell::VisitWorldObjects(), npc_magwinAI::WaypointReached(), and example_escortAI::WaypointReached().
GetPositionZ()
float WorldObject::GetPositionZ () const inline
Definition at line 970 of file Object.h.
References m_position, and Position::z.
Referenced by PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandSurvey(), Player::ActivateTaxiPathTo(), Spell::AddGOTarget(), GenericTransport::AddPassenger(), Spell::AddUnitTarget(), boss_thermapluggAI::Aggro(), boss_malchezaarAI::Aggro(), npc_ouro_spawnerAI::Aggro(), AreaTrigger_at_frostworn_general(), npc_dragonmaw_racerAI::AttackPlayer(), VehicleInfo::Board(), boss_algalonAI::boss_algalonAI(), boss_arugalAI::boss_arugalAI(), boss_razorscaleAI::boss_razorscaleAI(), Object::BuildMovementUpdate(), FormationMovementGenerator::BuildPath(), VehicleInfo::CalculateBoardingPositionOf(), GenericTransport::CalculatePassengerOffset(), TransportBase::CalculatePassengerOffset(), GenericTransport::CalculatePassengerPosition(), TransportBase::CalculatePassengerPosition(), boss_ionarAI::CallBackSparks(), Unit::CanReachWithMeleeAttack(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), Spell::CheckScriptTargeting(), ObjectAccessor::ConvertCorpseForPlayer(), Totem::Create(), Corpse::Create(), npc_anubarak_trial_frostsphereAI::DamageTaken(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), ChaseMovementGenerator::DispatchSplineToPosition(), UnitAI::DoCastSpellIfCan(), PlayerbotAI::DoLoot(), npc_fel_guard_houndAI::DoMoveToCorpse(), boss_brundirAI::DoMoveToTarget(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), boss_midnightAI::DoPrepareMount(), go_elemental_rift::DoRespawnElementalsIfCan(), instance_draktharon_keep::DoSortNovosDummies(), npc_ruul_snowhoofAI::DoSpawnAmbush(), npc_wildaAI::DoSpawnAssassin(), npc_demoniac_scryerAI::DoSpawnDemon(), world_map_ebon_hold::DoSpawnUndeadWave(), npc_teleportation_portalAI::DoSummon(), boss_headless_horsemanAI::DoTossHead(), Spell::EffectActivateObject(), EffectAuraDummy_npc_scourged_flamespitter(), Spell::EffectCharge(), Spell::EffectDuel(), Spell::EffectDummy(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectPullTowards(), Spell::EffectScriptEffect(), Spell::EffectStuck(), Spell::EffectTransmitted(), Spell::EffectTriggerMissileSpell(), npc_manaforge_spawnAI::EnterEvadeMode(), boss_void_reaverAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyGO(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), PlayerbotClassAI::FleeFromTrapGOIfCan(), GetDistance(), GetDistanceZ(), GetGameObjectListWithEntryInGrid(), GetNearPoint(), GetPosition(), FollowMovementGenerator::GetSpeed(), GMTicket::GMTicket(), GossipHello_npc_akama_illidan(), GOUse_go_furbolg_food(), GOUse_go_stratholme_postbox(), WorldSession::HandleAreaTriggerOpcode(), Aura::HandleAuraDummy(), ChatHandler::HandleComeToMeCommand(), WorldSession::HandleCorpseQueryOpcode(), BattleGroundDS::HandleCreatureCreate(), BattleGroundSA::HandleCreatureCreate(), Unit::HandleDummyAuraProc(), Player::HandleFall(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleGameObjectTargetCommand(), WorldSession::HandleGameObjectUseOpcode(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoWarpCommand(), ChatHandler::HandleGPSCommand(), boss_vaelastraszAI::HandleIntro(), boss_felmystAI::HandleLiftoff(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcTempSpawn(), Aura::HandlePeriodicTriggerSpell(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), ChaseMovementGenerator::HandleTargetedMovement(), ChatHandler::HandleTeleAddCommand(), ChatHandler::HandleTriggerActiveCommand(), VehicleInfo::Initialize(), GameObjectModel::initialize(), GameObject::IsAtInteractDistance(), isInBack(), isInFront(), Unit::IsInSwimmableWater(), Unit::IsInWater(), NamreebAnticheat::Movement::IsTeleportAllowed(), Unit::IsTriggeredAtSpellProcEvent(), Unit::IsUnderwater(), npc_smolderwing::JustDidDialogueStep(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_simone_seductressAI::JustReachedHome(), boss_razorscaleAI::JustReachedHome(), go_fel_cannonball_stack_trap::JustSpawned(), npc_00x09hlAI::JustSummoned(), boss_valanar_iccAI::JustSummoned(), boss_lord_marrowgarAI::JustSummoned(), boss_algalonAI::JustSummoned(), boss_ingvarAI::JustSummoned(), boss_highlord_kruulAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), npc_doom_blossomAI::JustSummoned(), npc_totem_of_spiritsAI::JustSummoned(), NamreebAnticheat::Movement::KnockBack(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), ChatHandler::LogCommand(), Unit::MeetsSelectAttackingRequirement(), MinionspawnerAI::MinionspawnerAI(), instance_trial_of_the_champion::MoveChampionToHome(), MotionMaster::MoveFall(), boss_novosAI::MoveInLineOfSight(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_shade_of_the_horsemanAI::MovementInform(), npc_champion_mountAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_ethereal_frostworgAI::MoveToNewPoint(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), spell_strangulating_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), Spell::OnCheckTarget(), instance_shadowfang_keep::OnCreatureCreate(), instance_zulaman::OnCreatureCreate(), instance_black_temple::OnCreatureCreate(), instance_blackrock_depths::OnCreatureCreate(), instance_karazhan::OnCreatureCreate(), instance_scholomance::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), instance_old_hillsbrad::OnCreatureCreate(), instance_ahnkahet::OnCreatureCreate(), instance_azjol_nerub::OnCreatureCreate(), instance_draktharon_keep::OnCreatureCreate(), instance_gundrak::OnCreatureCreate(), instance_pit_of_saron::OnCreatureCreate(), instance_icecrown_citadel::OnCreatureCreate(), instance_halls_of_stone::OnCreatureCreate(), instance_ulduar::OnCreatureCreate(), instance_serpentshrine_cavern::OnCreatureCreate(), world_map_ebon_hold::OnCreatureDeath(), instance_halls_of_stone::OnCreatureRespawn(), spell_gunship_portal_click::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_out_cold::OnEffectExecute(), spell_align_disk_aggro::OnEffectExecute(), spell_summon_players::OnEffectExecute(), instance_dire_maul::OnObjectCreate(), instance_onyxias_lair::OnObjectCreate(), spell_summon_anubar_periodic_aura::OnPeriodicDummy(), Unit::OnRelocated(), npc_hungry_nether_rayAI::OwnerKilledUnit(), Spell::Prepare(), CreatureEventAI::ProcessAction(), ProcessEventId_event_purify_food(), QuestAcceptGO_crystalline_tear(), npc_skyguard_prisonerAI::ReceiveAIEvent(), boss_head_of_horsemanAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), GMTicket::Recycle(), GameObjectModel::Relocate(), Player::RepopAtGraveyard(), npc_simone_the_inconspicuousAI::Reset(), npc_anubarak_trial_frostsphereAI::Reset(), npc_floating_spiritAI::Reset(), npc_snakesAI::Reset(), Player::SaveRecallPosition(), Corpse::SaveToDB(), Player::SaveToDB(), Creature::SaveToDB(), GameObject::SaveToDB(), CreatureCreatePos::SelectFinalPoint(), WorldSession::SendLearnNewTaxiNode(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Unit::SendPetDismiss(), WorldSession::SendSpiritResurrect(), WorldSession::SendTaxiMenu(), WorldSession::SendTaxiStatus(), Player::SetBattleGroundEntryPoint(), Unit::SetFeatherFall(), Player::SetPosition(), CharmInfo::SetStayPosition(), Spell::SetTargetMap(), sortByHeight(), npc_belnistraszAI::SpawnerSummon(), npc_blackwing_orbAI::SpellHit(), npc_forest_frogAI::SpellHit(), boss_tethyrAI::SpellHit(), boss_aerial_unitAI::SpellHit(), boss_soccothratesAI::SpellHitTarget(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), Movement::MoveSplineInit::Stop(), trial_companion_commonAI::SummonedMovementInform(), boss_highlord_kruulAI::SummonFormation(), npc_air_force_botsAI::SummonGuard(), boss_kelthuzadAI::SummonIntroCreatures(), GameObject::SummonLinkedTrapIfAny(), LFGMgr::TeleportPlayer(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), VehicleInfo::UnBoard(), instance_trial_of_the_champion::Update(), world_map_outland::Update(), TransportBase::Update(), Spell::update(), BattleGroundDS::Update(), guard_hallows_end_helperAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_death_rayAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), NecropolisAI::UpdateAI(), NecropolisProxyAI::UpdateAI(), NecropolisRelayAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), PathFinder::updateFilter(), TransportBase::UpdateGlobalPositions(), GameObject::Use(), npc_magwinAI::WaypointReached(), and example_escortAI::WaypointReached().
GetRandomPoint()
void WorldObject::GetRandomPoint (float x, float y, float z, float distance, float & rand_x, float & rand_y, float & rand_z, float minDist = 0.0f, float const * ori = nullptr) const
Definition at line 1766 of file Object.cpp.
References M_PI_F, MaNGOS::NormalizeMapCoord(), rand_norm_f(), and UpdateAllowedPositionZ().
Referenced by AreaTrigger_at_murkdeep(), npc_dragonmaw_racerAI::AttackPlayer(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), boss_jedogaAI::DoCallVolunteers(), go_elemental_rift::DoRespawnElementalsIfCan(), instance_blackrock_spire::DoSendNextFlamewreathWave(), npc_ruul_snowhoofAI::DoSpawnAmbush(), npc_wildaAI::DoSpawnAssassin(), instance_culling_of_stratholme::DoSpawnBurningCityUndead(), boss_algalonAI::DoSpawnCollapsingStar(), npc_demoniac_scryerAI::DoSpawnDemon(), boss_razorscaleAI::DoSpawnMoleMachines(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), instance_stratholme::DoSpawnPlaguedCritters(), boss_flame_leviathanAI::DoSpawnThorimHammer(), instance_pit_of_saron::DoSpawnTyrannusUndead(), world_map_ebon_hold::DoSpawnUndeadWave(), instance_razorfen_downs::DoSpawnWaveIfCan(), boss_eranikusAI::DoSummonHealers(), npc_anachronos_the_ancientAI::DoSummonKaldorei(), boss_amanitarAI::DoSummonMushrooms(), npc_anachronos_the_ancientAI::DoSummonQiraji(), npc_eris_havenfireAI::DoSummonWave(), boss_grandmaster_vorpilAI::DoTeleportToPlatform(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), ScriptAction::ExecuteDbscriptCommand(), GOUse_go_furbolg_food(), GOUse_go_stratholme_postbox(), npc_grimstoneAI::JustSummoned(), npc_eris_havenfireAI::JustSummoned(), npc_deathstalker_faerleiaAI::JustSummoned(), boss_onyxiaAI::JustSummoned(), npc_crystal_channel_targetAI::JustSummoned(), boss_eranikusAI::JustSummoned(), npc_ethereal_frostworgAI::MoveToNewPoint(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), world_map_kalimdor::OnCreatureDeath(), instance_azjol_nerub::OnCreatureRespawn(), spell_out_cold::OnEffectExecute(), ProcessEventId_event_purify_food(), npc_scarlet_ghoulAI::ReceiveAIEvent(), instance_blackrock_depths::SetData(), boss_general_angerforgeAI::SummonAdd(), boss_kelthuzadAI::SummonIntroCreatures(), npc_grimstoneAI::SummonRingMob(), instance_stratholme::Update(), npc_beast_combat_stalkerAI::UpdateAI(), boss_novosAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_melizza_brimbuzzleAI::WaypointReached(), and npc_00x09hlAI::WaypointStart().
GetReactionTo() [1/2]
ReputationRank WorldObject::GetReactionTo (Corpse const * corpse) const virtual
[Serverside] Get default WorldObject (hierarchy) reaction to a corpse
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Game always defaults reactions to neutral.
Reimplemented in Unit, and Player.
Definition at line 881 of file Relations.cpp.
References REP_NEUTRAL.
GetReactionTo() [2/2]
ReputationRank WorldObject::GetReactionTo (Unit const * unit) const virtual
[Serverside] Get default WorldObject (hierarchy) reaction to a unit
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Game always defaults reactions to neutral.
Reimplemented in Unit, Player, GameObject, and DynamicObject.
Definition at line 868 of file Relations.cpp.
References REP_NEUTRAL.
GetSpawnerGuid()
virtual ObjectGuid const WorldObject::GetSpawnerGuid () const inline virtual
Reimplemented in Totem, TemporarySpawn, Pet, and GameObject.
Definition at line 1067 of file Object.h.
Referenced by Unit::BreakCharmOutgoing(), Spell::EffectScriptEffect(), HomeMovementGenerator< Creature >::Finalize(), Unit::GetSpawner(), Aura::HandleAuraDummy(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), ChildTbcAI::HandleTripToTheDarkPortal(), AbstractWrapperMovementGenerator::Inform(), WaypointMovementGenerator< Creature >::InformAI(), npc_shaheenAI::JustDidDialogueStep(), npc_flash_freezeAI::JustDied(), npc_constrictor_tentacleAI::JustDied(), npc_soulgrinderAI::JustDied(), npc_inner_demonAI::JustDied(), Unit::JustKilledCreature(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_volazjAI::JustSummoned(), boss_kologarnAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), npc_frequency_scanner::JustSummoned(), npc_nesingwary_trapperAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_ingvar_throw_dummyAI::MoveInLineOfSight(), AbstractPathMovementGenerator::MovementInform(), PointMovementGenerator::MovementInform(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), npc_raging_flamesAI::npc_raging_flamesAI(), npc_supplicantAI::npc_supplicantAI(), InitializeImage::OnCheckTarget(), instance_mount_hyjal::OnCreatureCreate(), instance_ahnkahet::OnCreatureDeath(), instance_blackwing_lair::OnCreatureRespawn(), instance_mount_hyjal::OnCreatureRespawn(), instance_pinnacle::OnCreatureRespawn(), LightwellRelay::OnEffectExecute(), npc_jennyAI::ReceiveAIEvent(), npc_ghoul_feeding_bunnyAI::ReceiveAIEvent(), npc_arcane_beamAI::Reset(), npc_frozen_coreAI::Reset(), npc_infused_crystalAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), npc_bird_spiritAI::UpdateAI(), npc_mage_mirror_imageAI::UpdateAI(), npc_power_blue_flightAI::UpdateAI(), npc_flash_freezeAI::UpdateAI(), and npc_spawned_oronok_tornheartAI::WaypointMotionType().
GetSpellModOwner()
virtual Player* WorldObject::GetSpellModOwner () const inline virtual
Reimplemented in Totem, Player, and Pet.
Definition at line 1275 of file Object.h.
Referenced by Creature::AddCooldown(), AreaAura::AreaAura(), Aura::Aura(), ThreatCalcHelper::CalcThreat(), Unit::CalculateDamageAbsorbAndResist(), Spell::CalculatePowerCost(), CalculateSpellDuration(), CalculateSpellEffectValue(), UnitAI::CalculateSpellRange(), Spell::cancel(), Spell::cast(), Spell::EffectHealthLeech(), Spell::EffectPersistentAA(), Spell::EffectPowerBurn(), Spell::EffectPowerDrain(), Spell::ExecuteEffects(), Spell::finish(), Unit::GetCritChance(), Unit::GetCritMultiplier(), Unit::GetHitChance(), Spell::GetMinMaxRange(), GetSpellCastTime(), Spell::handle_delayed(), Unit::IsTriggeredAtSpellProcEvent(), Unit::MeleeDamageBonusDone(), LifeTap::OnInit(), Aura::PeriodicTick(), Spell::Prepare(), SpellAuraHolder::SpellAuraHolder(), Unit::SpellBonusWithCoeffs(), Unit::SpellDamageBonusDone(), and Unit::SpellHealingBonusDone().
GetTerrain()
TerrainInfo const * WorldObject::GetTerrain () const
Definition at line 2155 of file Object.cpp.
References Map::GetTerrain(), m_currMap, and MANGOS_ASSERT.
Referenced by PathFinder::BuildPolyPath(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), NamreebAnticheat::Movement::CheckTeleport(), Spell::EffectTransmitted(), PlayerbotAI::findNearbyGO(), GetAreaId(), GetAreaName(), PathFinder::getNavTerrain(), GetZoneAndAreaId(), GetZoneId(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleListAreaTriggerCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), Aura::HandlePeriodicTriggerSpell(), Creature::InitEntry(), Unit::IsInSwimmableWater(), Unit::IsInWater(), NamreebAnticheat::Movement::IsTeleportAllowed(), Unit::IsTriggeredAtSpellProcEvent(), Unit::IsUnderwater(), Creature::LoadFromDB(), Spell::SetTargetMap(), and boss_brundirAI::UpdateAI().
GetTransOffsetO()
float WorldObject::GetTransOffsetO () const inline
Definition at line 1248 of file Object.h.
References MovementInfo::GetTransportPos(), m_movementInfo, and Position::o.
Referenced by GenericTransport::UpdatePassengerPosition().
GetTransOffsetX()
float WorldObject::GetTransOffsetX () const inline
Definition at line 1245 of file Object.h.
References MovementInfo::GetTransportPos(), m_movementInfo, and Position::x.
Referenced by Object::BuildMovementUpdate(), and GenericTransport::UpdatePassengerPosition().
GetTransOffsetY()
float WorldObject::GetTransOffsetY () const inline
Definition at line 1246 of file Object.h.
References MovementInfo::GetTransportPos(), m_movementInfo, and Position::y.
Referenced by Object::BuildMovementUpdate(), and GenericTransport::UpdatePassengerPosition().
GetTransOffsetZ()
float WorldObject::GetTransOffsetZ () const inline
Definition at line 1247 of file Object.h.
References MovementInfo::GetTransportPos(), m_movementInfo, and Position::z.
Referenced by Object::BuildMovementUpdate(), and GenericTransport::UpdatePassengerPosition().
GetTransport()
GenericTransport* WorldObject::GetTransport () const inline
Definition at line 1239 of file Object.h.
References m_transport.
Referenced by ChaseMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), VehicleInfo::Board(), Object::BuildMovementUpdate(), PathFinder::calculate(), Player::CheckMirrorTimerActivation(), PathFinder::ComputePathToRandomPoint(), ChaseMovementGenerator::DispatchSplineToPosition(), Spell::EffectAddFarsight(), Spell::EffectPersistentAA(), Spell::EffectSummonPet(), GetDistance(), FollowMovementGenerator::GetResetPosition(), GameObject::GetWorldRotation(), ChaseMovementGenerator::HandleFinalizedMovement(), WorldSession::HandleForceSpeedChangeAckOpcodes(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleMmapPathCommand(), WorldSession::HandlePlayerLogin(), NamreebAnticheat::Movement::HandleSpeedChangeAck(), ChaseMovementGenerator::HandleTargetedMovement(), FollowMovementGenerator::HandleTargetedMovement(), PathFinder::HaveTile(), WaypointMovementGenerator< Creature >::InitializeWaypointPath(), WaypointMovementGenerator< Creature >::Interrupt(), FormationMovementGenerator::Interrupt(), FollowMovementGenerator::IsBoostAllowed(), ChaseMovementGenerator::IsReachablePositionToTarget(), FollowMovementGenerator::IsUnstuckAllowed(), Unit::IsVisibleForOrDetect(), ItemUse_item_petrov_cluster_bombs(), Movement::MoveSplineInit::Launch(), Pet::LoadPetFromDB(), FollowMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), MovePositionToFirstCollision(), Unit::NearTeleportTo(), PathFinder::NormalizePath(), MaNGOS::VisibleNotifier::Notify(), WaypointMovementGenerator< Creature >::OnArrived(), RemoveFromWorld(), Unit::RemoveFromWorld(), Player::RepopAtGraveyard(), ChaseMovementGenerator::RequiresNewPosition(), Map::SendInitSelf(), Map::SendInitTransports(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Map::SendRemoveTransports(), PathFinder::SetCurrentNavMesh(), Unit::SetDeathState(), Unit::SetFacingTo(), Unit::SetInCombatState(), CharmInfo::SetStayPosition(), Spell::SetTargetMap(), Movement::MoveSplineInit::Stop(), SummonCreature(), Unit::TakeCharmOf(), Unit::TakePossessOf(), VehicleInfo::TeleportPassengers(), Player::TeleportTo(), VehicleInfo::UnBoard(), Transport::UpdateForMap(), and Unit::UpdateSplinePosition().
GetTransportInfo()
TransportInfo* WorldObject::GetTransportInfo () const inline
Definition at line 959 of file Object.h.
References m_transportInfo.
Referenced by trial_companion_commonAI::AttackStart(), WorldSession::BuildPartyMemberStatsChangedPacket(), VehicleInfo::CanBoard(), BattlefieldWG::CheckAchievementCriteriaMeet(), BattleGroundSA::CheckAchievementCriteriaMeet(), BattleGroundIC::CheckAchievementCriteriaMeet(), Spell::CheckCast(), Spell::CheckTarget(), Spell::CheckVehicle(), trial_companion_commonAI::DamageTaken(), UnitAI::DetectOrAttack(), Aura::HandleAuraDummy(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleEjectPassenger(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleRequestVehicleNextSeat(), WorldSession::HandleRequestVehicleSwitchSeat(), TransportBase::HasOnBoard(), Movement::MoveSplineInit::Launch(), instance_eye_of_eternity::OnCreatureDeath(), Unit::SetDeathState(), Spell::SetTargetMap(), Movement::MoveSplineInit::Stop(), Unit::TriggerHomeEvents(), trial_companion_commonAI::UpdateAI(), and Unit::UpdateSplinePosition().
GetTransSeat()
int8 WorldObject::GetTransSeat () const inline
Definition at line 1250 of file Object.h.
References MovementInfo::GetTransportSeat(), and m_movementInfo.
Referenced by VehicleInfo::GetSeatForPassenger().
GetTransTime()
uint32 WorldObject::GetTransTime () const inline
Definition at line 1249 of file Object.h.
References MovementInfo::GetTransportTime(), and m_movementInfo.
GetViewPoint()
ViewPoint& WorldObject::GetViewPoint () inline
Definition at line 1190 of file Object.h.
References m_viewPoint.
Referenced by Map::Add(), Camera::Camera(), Map::CreatePlayerOnClient(), Map::CreatureCellRelocation(), Map::DynamicObjectRelocation(), Camera::Event_AddedToWorld(), Camera::Event_Moved(), Map::GameObjectRelocation(), Unit::OnRelocated(), Map::PlayerRelocation(), DynamicObject::RemoveFromWorld(), Unit::RemoveFromWorld(), Camera::SetView(), Camera::UpdateForCurrentViewPoint(), UpdateVisibilityAndView(), Unit::UpdateVisibilityAndView(), and Camera::~Camera().
GetVisibilityData() [1/2]
VisibilityData& WorldObject::GetVisibilityData () inline
Definition at line 1228 of file Object.h.
References m_visibilityData.
GetVisibilityData() [2/2]
VisibilityData const& WorldObject::GetVisibilityData () const inline
Definition at line 1227 of file Object.h.
References m_visibilityData.
Referenced by BuildUpdateData(), VisibilityData::CanDetectInvisibilityOf(), UnitAI::CanTriggerStealthAlert(), GameObject::Create(), Transport::Create(), VisibilityData::GetInvisibilityDetectMask(), VisibilityData::GetInvisibilityDetectValue(), VisibilityData::GetStealthVisibilityDistance(), VisibilityData::GetVisibilityDistanceFor(), go_plague_cauldron::go_plague_cauldron(), go_portal_to_orgrimmar::go_portal_to_orgrimmar(), go_portal_to_undercity::go_portal_to_undercity(), go_scrying_orb::go_scrying_orb(), ChatHandler::HandleGetDistanceCommand(), Aura::HandleInvisibility(), Aura::HandleInvisibilityDetect(), Aura::HandleModStealth(), Aura::HandleModStealthDetect(), Aura::HandleModStealthLevel(), ChatHandler::HandleRespawnCommand(), DynamicObject::isVisibleForInState(), GameObject::isVisibleForInState(), Unit::IsVisibleForOrDetect(), Map::MessageBroadcast(), CreatureSettings::ResetStaticFlags(), Spell::SendSpellGo(), Player::SetDrunkValue(), go_brewfest_music::UpdateAI(), go_midsummer_music::UpdateAI(), Map::UpdateObjectVisibility(), Camera::UpdateVisibilityForOwner(), and Map::VisitNearbyCellsOf().
GetZoneAndAreaId()
void WorldObject::GetZoneAndAreaId (uint32 & zoneid, uint32 & areaid) const
Definition at line 1406 of file Object.cpp.
References GetTerrain(), TerrainInfo::GetZoneAndAreaId(), m_position, Position::x, Position::y, and Position::z.
Referenced by Player::AddQuest(), Spell::CheckCast(), ConditionEntry::Evaluate(), Aura::HandleAuraDummy(), ChatHandler::HandleGPSCommand(), WorldSession::HandleMoveTeleportAckOpcode(), Aura::HandlePhase(), WorldSession::HandlePlayerReconnect(), Loot::Loot(), AchievementCriteriaRequirement::Meets(), Player::ResurrectPlayer(), Player::RewardQuest(), Spell::SelectMountByAreaAndSkill(), Player::SendInitialPacketsAfterAddToMap(), Map::SendZoneDynamicInfo(), Player::SetPosition(), CreatureEventAI::SpawnedEventConditionsCheck(), Player::Update(), and GameObject::Use().
GetZoneId()
uint32 WorldObject::GetZoneId () const
Definition at line 1391 of file Object.cpp.
References GetTerrain(), TerrainInfo::GetZoneId(), m_position, Position::x, Position::y, and Position::z.
Referenced by Player::_LoadInventory(), Guild::AddMember(), WorldSession::BuildPartyMemberStatsChangedPacket(), ChangeZoneEventStatus(), Spell::CheckCast(), Creature::Create(), GameObject::Create(), DoDisplayText(), Spell::EffectSummonPlayer(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), MaNGOS::XP::Gain(), SocialMgr::GetFriendInfo(), GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), ChatHandler::HandleChangeWeatherCommand(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleLinkGraveCommand(), WorldSession::HandleMoveTeleportAckOpcode(), ChatHandler::HandleNamegoCommand(), ChatHandler::HandleNearGraveCommand(), Unit::HandleProcTriggerSpellAuraProc(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleTogglePvP(), Battlefield::HandleWarInviteResponse(), WorldSession::HandleWhoOpcode(), NamreebAnticheat::Movement::IsTeleportAllowed(), ItemUse_item_petrov_cluster_bombs(), go_large_jack_o_lanternAI::JustDespawned(), npc_shade_of_the_horsemanAI::JustDied(), Unit::JustKilledCreature(), npc_shattered_sun_fighterAI::JustRespawned(), npc_smolderwing::JustRespawned(), npc_shade_of_the_horsemanAI::JustRespawned(), go_bonfire::JustSpawned(), Player::KilledPlayerCredit(), MonsterText(), MouthAI::ReceiveAIEvent(), GameObject::RemoveFromWorld(), Player::SaveToDB(), SelectRandomFlameshockerSpawnTarget(), Player::SendInitialPacketsBeforeAddToMap(), Creature::SendZoneUnderAttackMessage(), Battlefield::SendZoneWarning(), MemberSlot::SetMemberStats(), npc_shade_of_the_horsemanAI::StartLanding(), npc_orphan_matronAI::SummonShadeOfTheHorseman(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), npc_smolderwing::UpdateAI(), npc_spirit_guide_wintergraspAI::UpdateAI(), and go_vehicle_teleporter::UpdateAI().
HandlePlayPacketSettings()
void WorldObject::HandlePlayPacketSettings (WorldPacket & msg, PlayPacketParameters & parameters) const
Definition at line 2604 of file Object.cpp.
References PlayPacketParameters::areaOrZone, GetMap(), Object::IsInWorld(), Map::MessageMapBroadcast(), Map::MessageMapBroadcastArea(), Map::MessageMapBroadcastZone(), PLAY_AREA, PLAY_MAP, PLAY_SET, PLAY_TARGET, PLAY_ZONE, SendMessageToSet(), PlayPacketParameters::setting, and PlayPacketParameters::target.
Referenced by PlayDirectSound(), PlayDistanceSound(), PlayMusic(), and PlaySpellVisual().
HasGCD()
bool WorldObject::HasGCD (SpellEntry const * spellEntry) const virtual
Definition at line 2754 of file Object.cpp.
References Map::GetCurrentClockTime(), GetMap(), m_GCDCatMap, and SpellEntry::StartRecoveryCategory.
Referenced by Player::CastItemCombatSpell(), Spell::CheckCast(), and WorldSession::HandleCastSpellOpcode().
HasGCDOrCooldownWithinMargin()
bool WorldObject::HasGCDOrCooldownWithinMargin (SpellEntry const & spellEntry, ItemPrototype const * itemProto = nullptr)
Definition at line 2915 of file Object.cpp.
References SpellEntry::Category, CooldownContainer::end(), CooldownContainer::FindByCategory(), CooldownContainer::FindBySpellId(), GetMap(), GetSpellSchoolMask(), SpellEntry::Id, ItemPrototype::ItemId, m_cooldownMap, m_GCDCatMap, m_lockoutMap, SpellEntry::PreventionType, SPELL_PREVENTION_TYPE_SILENCE, ItemPrototype::Spells, and SpellEntry::StartRecoveryCategory.
Referenced by WorldSession::HandleCastSpellOpcode().
HasInArc()
bool WorldObject::HasInArc (const WorldObject * target, float arc = M_PI_F) const
Definition at line 1696 of file Object.cpp.
References GetOrientation(), GetPositionX(), GetPositionY(), and HasInArcAt().
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), Spell::CheckCast(), Spell::CheckRange(), PlayerbotAI::FaceTarget(), ChaseMovementGenerator::HandleFinalizedMovement(), IsFacingTargetsBack(), IsFacingTargetsFront(), isInBack(), isInFront(), GameObject::isVisibleForInState(), RetaliationCreature::OnCheckCast(), Spell::SetTargetMap(), PetAI::UpdateAI(), and Unit::UpdateMeleeAttackingState().
HasInArcAt()
bool WorldObject::HasInArcAt (float x, float y, float o, const WorldObject * target, float arc = M_PI_F) const
Definition at line 1674 of file Object.cpp.
References GetAngleAt(), M_PI_F, and MapManager::NormalizeOrientation().
Referenced by HasInArc().
HasStringId() [1/2]
bool WorldObject::HasStringId (std::string & stringId) const
Definition at line 1322 of file Object.cpp.
References GetMap().
Referenced by Spell::CheckSpellScriptTargets(), and UnitConditionMgr::getConditionValue().
HasStringId() [2/2]
bool WorldObject::HasStringId (uint32 stringId) const
Definition at line 1327 of file Object.cpp.
References m_stringIds.
HaveDebugFlag()
bool WorldObject::HaveDebugFlag (CMDebugFlags flag) const inline
Definition at line 1230 of file Object.h.
References m_debugFlags.
Referenced by ChatHandler::HandleDebugObjectFlags(), and Movement::MoveSplineInit::Launch().
Heartbeat()
virtual void WorldObject::Heartbeat () inline virtual
Reimplemented in Unit, Player, GameObject, and Creature.
Definition at line 954 of file Object.h.
Referenced by Unit::Heartbeat(), and Update().
IncrementDestLocCounter()
void WorldObject::IncrementDestLocCounter () inline
Definition at line 1254 of file Object.h.
References m_destLocCounter.
Referenced by Spell::SendSpellGo().
InSamePhase() [1/2]
bool WorldObject::InSamePhase (uint32 phasemask) const inline
Definition at line 1049 of file Object.h.
References GetPhaseMask().
InSamePhase() [2/2]
bool WorldObject::InSamePhase (WorldObject const * obj) const inline
Definition at line 1048 of file Object.h.
References GetPhaseMask(), and InSamePhase().
Referenced by InSamePhase(), IsInMap(), Unit::RemoveNotOwnTrackedTargetAuras(), MaNGOS::MessageDeliverer::Visit(), MaNGOS::MessageDelivererExcept::Visit(), MaNGOS::MessageDistDeliverer::Visit(), MaNGOS::ObjectMessageDistDeliverer::Visit(), and MaNGOS::CameraDistWorker< Do >::Visit().
InspectingLoot()
virtual void WorldObject::InspectingLoot () inline virtual
Reimplemented in Creature.
Definition at line 1220 of file Object.h.
Referenced by Loot::ShowContentTo().
isActiveObject()
bool WorldObject::isActiveObject () const inline
Definition at line 1187 of file Object.h.
References ViewPoint::hasViewers(), m_isActiveObject, and m_viewPoint.
Referenced by Map::CreatureCellRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), HomeMovementGenerator< Creature >::Initialize(), LoadHelper(), SetActiveObjectState(), and Camera::SetView().
IsBoarded()
bool WorldObject::IsBoarded () const inline
Definition at line 960 of file Object.h.
References m_transportInfo.
Referenced by Object::BuildMovementUpdate(), VehicleInfo::CanBoard(), BattlefieldWG::CheckAchievementCriteriaMeet(), BattleGroundSA::CheckAchievementCriteriaMeet(), BattleGroundIC::CheckAchievementCriteriaMeet(), Spell::CheckCast(), GuardianAI::CombatStop(), UnitAI::EnterEvadeMode(), ChaseMovementGenerator::FanOut(), Aura::HandleAuraDummy(), WorldSession::HandleEjectPassenger(), TransportBase::HasOnBoard(), spell_skeletal_gryphon_escape::OnEffectExecute(), Unit::OnRelocated(), Spell::SetTargetMap(), and Unit::Update().
IsControlledByPlayer()
bool WorldObject::IsControlledByPlayer () const
Definition at line 2688 of file Object.cpp.
References Object::GetTypeId(), TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by MaNGOS::AnyAoETargetUnitInObjectRangeCheck::AnyAoETargetUnitInObjectRangeCheck(), MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::AnyUnfriendlyUnitInObjectRangeCheck(), CreatureLinkingHolder::DoCreatureLinkingEvent(), Spell::DoSpellHitOnUnit(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), mob_pure_energyAI::JustPreventedDeath(), ShadowPrison::OnCheckTarget(), GluthDecimate::OnCheckTarget(), WyvernSting::OnDurationCalculate(), GluthDecimate::OnEffectExecute(), CreatureLinkingHolder::ProcessSlave(), Unit::SetInCombatState(), Unit::SetStunned(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), and MaNGOS::SpellNotifierCreatureAndPlayer::Visit().
IsEnemy()
bool WorldObject::IsEnemy (Unit const * unit) const virtual
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as an enemy
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Game always defaults reactions to "neutral", so this is always false (neutral is not an enemy).
Reimplemented in Unit, GameObject, and DynamicObject.
Definition at line 894 of file Relations.cpp.
IsFacingTargetsBack()
bool WorldObject::IsFacingTargetsBack (const WorldObject * target, float arc = M_PI_F) const
Definition at line 1701 of file Object.cpp.
References HasInArc().
Referenced by Unit::CalculateEffectiveParryChance(), Unit::CanDazeInCombat(), Spell::CheckCast(), RetaliationWarrior::OnProc(), and RetaliationDummyCreature::OnProc().
IsFacingTargetsFront()
bool WorldObject::IsFacingTargetsFront (const WorldObject * target, float arc = M_PI_F) const
Definition at line 1717 of file Object.cpp.
References HasInArc().
Referenced by Unit::CanBlockInCombat(), Unit::CanDodgeInCombat(), Unit::CanParryInCombat(), and Spell::CheckCast().
IsFriend()
bool WorldObject::IsFriend (Unit const * unit) const virtual
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as a friend
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Game always defaults reactions to "neutral", so this is always false (neutral is not a friend).
Reimplemented in Unit, GameObject, and DynamicObject.
Definition at line 907 of file Relations.cpp.
isInBack()
bool WorldObject::isInBack (WorldObject const * target, float distance, float arc = M_PI_F) const
Definition at line 1748 of file Object.cpp.
References DIST_CALC_COMBAT_REACH, GetDistance(), GetPositionX(), GetPositionY(), GetPositionZ(), HasInArc(), and M_PI_F.
Referenced by isInBackInMap(), and MaNGOS::SpellNotifierCreatureAndPlayer::Visit().
isInBackInMap()
bool WorldObject::isInBackInMap (WorldObject const * target, float distance, float arc = M_PI_F) const
Definition at line 1738 of file Object.cpp.
References isInBack(), and IsInMap().
Referenced by CreatureEventAI::CheckEvent(), and PlayerbotRogueAI::DoNextCombatManeuver().
isInFront()
bool WorldObject::isInFront (WorldObject const * target, float distance, float arc = M_PI_F) const
Definition at line 1743 of file Object.cpp.
References DIST_CALC_COMBAT_REACH, GetDistance(), GetPositionX(), GetPositionY(), GetPositionZ(), and HasInArc().
Referenced by isInFrontInMap(), Unit::IsVisibleForOrDetect(), and MaNGOS::SpellNotifierCreatureAndPlayer::Visit().
isInFrontInMap()
bool WorldObject::isInFrontInMap (WorldObject const * target, float distance, float arc = M_PI_F) const
Definition at line 1733 of file Object.cpp.
References isInFront(), and IsInMap().
Referenced by PlayerbotAI::CastPetSpell(), CreatureEventAI::CheckEvent(), npc_chess_piece_genericAI::GetTargetByType(), and Unit::IsVisibleForOrDetect().
IsInMap()
bool WorldObject::IsInMap (const WorldObject * obj) const inline
Definition at line 1077 of file Object.h.
References GetMap(), InSamePhase(), and Object::IsInWorld().
Referenced by Group::BroadcastPacketInMap(), CreatureEventAI::CheckEvent(), PlayerbotAI::DoNextCombatManeuver(), Spell::EffectScriptEffect(), Player::GetNextRaidMemberWithLowestLifePercentage(), WorldSession::HandleLootMasterGiveOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), Player::IsAtRecruitAFriendDistance(), isInBackInMap(), isInFrontInMap(), GameObject::isVisibleForInState(), Unit::IsVisibleForOrDetect(), IsWithinCombatDistInMap(), IsWithinDistInMap(), IsWithinLOSInMap(), Aura::ReapplyAffectedPassiveAuras(), Camera::SetView(), PlayerbotAI::TurnInQuests(), and PlayerbotAI::UpdateAI().
IsInMapIgnorePhase()
bool WorldObject::IsInMapIgnorePhase (const WorldObject * obj) const inline
Definition at line 1073 of file Object.h.
References GetMap(), and Object::IsInWorld().
Referenced by Unit::IsVisibleForOrDetect(), IsWithinCombatDistInMap(), and IsWithinDistInMap().
IsInRange()
bool WorldObject::IsInRange (WorldObject const * obj, float minRange, float maxRange, bool is3D = true, bool combat = false) const
Definition at line 1572 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), GetDistance(), and GetObjectBoundingRadius().
Referenced by ScriptedAI::CanCast(), CreatureEventAI::CheckEvent(), npc_kaylaan_the_lostAI::ExecuteActions(), PlayerbotAI::In_Range(), and npc_kindal_moonweaverAI::UpdateFollowerAI().
IsInRange2d()
bool WorldObject::IsInRange2d (float x, float y, float minRange, float maxRange, bool combat = false) const
Definition at line 1593 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), GetDistance2d(), and GetObjectBoundingRadius().
IsInRange3d()
bool WorldObject::IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat = false) const
Definition at line 1614 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), GetDistance(), and GetObjectBoundingRadius().
IsNotifyOnEventObject()
virtual bool WorldObject::IsNotifyOnEventObject () inline virtual
Definition at line 1196 of file Object.h.
References m_isOnEventNotified.
IsPositionValid()
bool WorldObject::IsPositionValid () const
Definition at line 1920 of file Object.cpp.
References MaNGOS::IsValidMapCoord(), m_position, Position::o, Position::x, Position::y, and Position::z.
Referenced by GameObject::Create(), Corpse::Create(), Transport::Create(), DynamicObject::Create(), Player::LoadFromDB(), Corpse::LoadFromDB(), CreatureCreatePos::Relocate(), and Map::Update().
IsSpellOnPermanentCooldown()
bool WorldObject::IsSpellOnPermanentCooldown (SpellEntry const & spellEntry) const
Definition at line 2900 of file Object.cpp.
References CooldownContainer::end(), CooldownContainer::FindBySpellId(), World::GetCurrentClockTime(), Map::GetCurrentClockTime(), GetMap(), SpellEntry::Id, Object::IsInWorld(), and m_cooldownMap.
Referenced by Spell::SendCastResult().
IsSpellReady() [1/2]
bool WorldObject::IsSpellReady (SpellEntry const & spellEntry, ItemPrototype const * itemProto = nullptr) const
Definition at line 2848 of file Object.cpp.
References SpellEntry::Category, CheckLockout(), CooldownContainer::end(), CooldownContainer::FindByCategory(), CooldownContainer::FindBySpellId(), World::GetCurrentClockTime(), Map::GetCurrentClockTime(), GetMap(), GetSpellSchoolMask(), SpellEntry::Id, Object::IsInWorld(), ItemPrototype::ItemId, m_cooldownMap, SpellEntry::PreventionType, SPELL_PREVENTION_TYPE_SILENCE, and ItemPrototype::Spells.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), Unit::_UpdateAutoRepeatSpell(), Unit::CalculateDamageAbsorbAndResist(), PlayerbotDeathKnightAI::CanPull(), PlayerbotPaladinAI::CanPull(), CastHighestStealthRank(), Player::CastItemCombatSpell(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), Spell::CheckCast(), PlayerbotMageAI::CheckFrostCooldowns(), Spell::CheckPetCast(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNonCombatActions(), Spell::EffectStuck(), boss_aranAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kaelthasAI::ExecuteActions(), Player::GetResurrectionSpellId(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), UnitAI::IsMainSpellPrevented(), IsSpellReady(), PlayerbotDruidAI::ResurrectPlayer(), npc_creature_generatorAI::TrySummoning(), PetAI::UpdateAI(), TotemAI::UpdateAI(), npc_corrupted_lightning_totemAI::UpdateAI(), boss_grand_astromancer_capernianAI::UpdateAI(), and UnitAI::UpdateSpellLists().
IsSpellReady() [2/2]
bool WorldObject::IsSpellReady (uint32 spellId, ItemPrototype const * itemProto = nullptr) const
Definition at line 2891 of file Object.cpp.
References IsSpellReady(), SQLStorage::LookupEntry(), and sSpellTemplate.
IsUsingNewSpawningSystem()
bool WorldObject::IsUsingNewSpawningSystem () const
Definition at line 3294 of file Object.cpp.
References Object::GetDbGuid(), and Object::GetGUIDLow().
Referenced by CreatureLinkingHolder::DoCreatureLinkingEvent(), ChatHandler::HandleRespawnCommand(), Creature::LoadFromDB(), MaNGOS::RespawnDo::operator()(), CreatureLinkingHolder::ProcessSlaveGuidList(), Creature::RemoveCorpse(), Creature::SaveRespawnTime(), Creature::SetDeathState(), and GameObject::Update().
isVisibleFor()
bool WorldObject::isVisibleFor (Player const * u, WorldObject const * viewPoint) const inline
Definition at line 1164 of file Object.h.
References isVisibleForInState().
isVisibleForInState()
virtual bool WorldObject::isVisibleForInState (Player const * u, WorldObject const * viewPoint, bool inVisibleList) const pure virtual
Implemented in Unit, GameObject, DynamicObject, and Corpse.
Referenced by isVisibleFor(), and Player::UpdateVisibilityOf().
IsWithinCombatDist()
bool WorldObject::IsWithinCombatDist (WorldObject const * obj, float dist2compare, bool is3D = true) const inline
Definition at line 1081 of file Object.h.
References _IsWithinCombatDist().
Referenced by boss_kaelthasAI::ExecuteActions().
IsWithinCombatDistInMap()
bool WorldObject::IsWithinCombatDistInMap (WorldObject const * obj, float dist2compare, bool is3D = true, bool ignorePhase = false) const inline
Definition at line 1085 of file Object.h.
References _IsWithinCombatDist(), IsInMap(), and IsInMapIgnorePhase().
Referenced by KillingSpree::OnPeriodicDummy(), MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::operator()(), MaNGOS::FriendlyEligibleUnitConditionCheck::operator()(), and Spell::update().
IsWithinDist()
bool WorldObject::IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D = true) const inline
Definition at line 1095 of file Object.h.
References _IsWithinDist().
Referenced by mob_fel_orc_convertAI::Aggro(), npc_sunblade_scoutAI::ExecuteAction(), UnitAI::IsVisible(), npc_rabid_bearAI::MoveInLineOfSight(), npc_ball_of_flameAI::MoveInLineOfSight(), npc_a_special_surpriseAI::MoveInLineOfSight(), DarkFiendAI::MoveInLineOfSight(), mob_water_globuleAI::MoveInLineOfSight(), ChildTbcAI::MoveInLineOfSight(), Spell::OnCheckTarget(), NamreebAnticheat::Movement::OnTransport(), MaNGOS::AllGameObjectsMatchingOneEntryInRange::operator()(), MaNGOS::AllCreaturesOfEntryInRangeCheck::operator()(), MaNGOS::AllCreaturesMatchingOneEntryInRange::operator()(), instance_sunwell_plateau::Update(), example_creatureAI::UpdateAI(), MaNGOS::CameraDistWorker< Do >::Visit(), and MaNGOS::CameraDistLambdaWorker::Visit().
IsWithinDist2d()
bool WorldObject::IsWithinDist2d (float x, float y, float dist2compare) const
Definition at line 1516 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), and GetDistance2d().
Referenced by boss_hydross_the_unstableAI::CheckTransition(), instance_draktharon_keep::DoSortNovosDummies(), npc_highlord_darion_mograineAI::ExecuteAction(), OutdoorPvPEP::HandleGameObjectCreate(), instance_stratholme::OnCreatureCreate(), instance_blackrock_depths::OnCreatureCreate(), instance_dire_maul::OnPlayerEnter(), instance_dire_maul::SortPylonGuards(), instance_stratholme::Update(), BattleGroundDS::Update(), and npc_mistress_nagmaraAI::UpdateAI().
IsWithinDist3d()
bool WorldObject::IsWithinDist3d (float x, float y, float z, float dist2compare) const
Definition at line 1507 of file Object.cpp.
References DIST_CALC_NONE, GetCombatReach(), and GetDistance().
Referenced by ChaseMovementGenerator::DispatchSplineToPosition(), ScriptAction::ExecuteDbscriptCommand(), Player::GetNextRaidMemberWithLowestLifePercentage(), OutdoorPvPSI::HandleDropFlag(), MaNGOS::NearestGameObjectEntryInPosRangeCheck::operator()(), MaNGOS::GameObjectEntryInPosRangeCheck::operator()(), MaNGOS::GameObjectInPosRangeCheck::operator()(), Player::TeleportTo(), BattleGroundEY::Update(), npc_kernobeeAI::UpdateFollowerAI(), and MaNGOS::SpellNotifierPlayer::Visit().
IsWithinDistInMap()
bool WorldObject::IsWithinDistInMap (WorldObject const * obj, float dist2compare, bool is3D = true, bool ignorePhase = false) const inline
Definition at line 1100 of file Object.h.
References _IsWithinDist(), IsInMap(), and IsInMapIgnorePhase().
Referenced by npc_escortAI::AssistPlayerInCombat(), FollowerAI::AssistPlayerInCombat(), Spell::CheckCast(), Player::CheckDuelDistance(), UnitAI::CheckForHelp(), Spell::CheckScriptTargeting(), npc_spirit_guideAI::CorpseRemoved(), npc_eris_havenfireAI::DoAttackArchersTarget(), npc_highlord_darion_mograineAI::DoSendQuestCredit(), instance_draktharon_keep::DoSortNovosDummies(), instance_stratholme::DoSortZiggurats(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), Spell::FillRaidOrPartyTargets(), FollowerAI::GetLeaderForFollower(), Unit::GetNextRandomRaidMember(), Player::GetNPCIfCanInteractWith(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleGameobjectReportUse(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleInspectArenaTeamsOpcode(), WorldSession::HandleInspectHonorStatsOpcode(), WorldSession::HandleInspectOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePetActionHelper(), BattleGroundEY::HandlePlayerClickedOnFlag(), OutdoorPvPHP::HandlePlayerKillInsideArea(), OutdoorPvPZM::HandlePlayerKillInsideArea(), WorldSession::HandleQueryInspectAchievementsOpcode(), WorldSession::HandleReclaimCorpseOpcode(), Player::IsAtGroupRewardDistance(), npc_shadowlord_deathwailAI::IsPlayerOrGroupInRangeAndActiveInEvent(), Corpse::isVisibleForInState(), DynamicObject::isVisibleForInState(), GameObject::isVisibleForInState(), Unit::IsVisibleForOrDetect(), Creature::IsVisibleInGridForPlayer(), npc_ranger_lilathaAI::MoveInLineOfSight(), npc_rizzle_sprysprocketAI::MoveInLineOfSight(), npc_depth_chargeAI::MoveInLineOfSight(), boss_ambassador_flamelashAI::MoveInLineOfSight(), npc_draenei_survivorAI::MoveInLineOfSight(), boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_dejaAI::MoveInLineOfSight(), npc_kerlonianAI::MoveInLineOfSight(), npc_threshwackonatorAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_kittenAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_custodian_of_timeAI::MoveInLineOfSight(), npc_toogaAI::MoveInLineOfSight(), npc_mistAI::MoveInLineOfSight(), npc_ringoAI::MoveInLineOfSight(), boss_zumrahAI::MoveInLineOfSight(), boss_jedogaAI::MoveInLineOfSight(), boss_anubarakAI::MoveInLineOfSight(), boss_krikthirAI::MoveInLineOfSight(), npc_nesingwary_trapperAI::MoveInLineOfSight(), npc_nexus_drake_hatchlingAI::MoveInLineOfSight(), npc_jennyAI::MoveInLineOfSight(), npc_orphaned_mammoth_calfAI::MoveInLineOfSight(), boss_anubarak_trialAI::MoveInLineOfSight(), npc_lich_king_villageAI::MoveInLineOfSight(), npc_king_ymironAI::MoveInLineOfSight(), npc_firecrackers_bunnyAI::MoveInLineOfSight(), npc_corrupted_soul_fragmentAI::MoveInLineOfSight(), boss_lich_king_horAI::MoveInLineOfSight(), npc_queen_lanathel_introAI::MoveInLineOfSight(), npc_volatile_ooze_iccAI::MoveInLineOfSight(), npc_gas_cloud_iccAI::MoveInLineOfSight(), npc_planar_anomalyAI::MoveInLineOfSight(), npc_black_holeAI::MoveInLineOfSight(), boss_mimironAI::MoveInLineOfSight(), npc_expedition_commanderAI::MoveInLineOfSight(), boss_thorimAI::MoveInLineOfSight(), npc_runic_colossusAI::MoveInLineOfSight(), npc_scrapbotAI::MoveInLineOfSight(), boss_saraAI::MoveInLineOfSight(), npc_ominous_cloudAI::MoveInLineOfSight(), npc_charged_sphereAI::MoveInLineOfSight(), boss_exarch_maladaarAI::MoveInLineOfSight(), boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpilAI::MoveInLineOfSight(), npc_void_travelerAI::MoveInLineOfSight(), npc_daranelleAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_supplicantAI::MoveInLineOfSight(), mob_enchanted_elementalAI::MoveInLineOfSight(), mob_steamrigger_mechanicAI::MoveInLineOfSight(), boss_warlord_kalithreshAI::MoveInLineOfSight(), boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), mob_fel_orc_convertAI::MoveInLineOfSight(), npc_creditmarker_visit_with_ancestorsAI::MoveInLineOfSight(), npc_protectorate_demolitionistAI::MoveInLineOfSight(), npc_veneratus_spawn_nodeAI::MoveInLineOfSight(), npc_khadgars_servantAI::MoveInLineOfSight(), boss_soccothratesAI::MoveInLineOfSight(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_air_force_botsAI::MoveInLineOfSight(), npc_spring_rabbitAI::MoveInLineOfSight(), GuardAI::MoveInLineOfSight(), PetAI::MoveInLineOfSight(), CreatureEventAI::MoveInLineOfSight(), boss_felblood_kaelthasAI::MoveInLineOfSight(), boss_nalorakkAI::MoveInLineOfSight(), npc_amanishi_lookoutAI::MoveInLineOfSight(), npc_harkorAI::MoveInLineOfSight(), npc_ashliAI::MoveInLineOfSight(), npc_eagle_trash_aggro_triggerAI::MoveInLineOfSight(), boss_temporusAI::MoveInLineOfSight(), boss_ossirianAI::MoveInLineOfSight(), npc_general_andorovAI::MoveInLineOfSight(), boss_veknilashAI::MoveInLineOfSight(), boss_veklorAI::MoveInLineOfSight(), npc_dalaran_guardian_mageAI::MoveInLineOfSight(), boss_rimefang_posAI::MoveInLineOfSight(), boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlinaAI::MoveInLineOfSight(), npc_ingvar_throw_dummyAI::MoveInLineOfSight(), boss_ichoronAI::MoveInLineOfSight(), npc_ethereal_sphereAI::MoveInLineOfSight(), boss_nexusprince_shaffarAI::MoveInLineOfSight(), npc_cage_trap_triggerAI::MoveInLineOfSight(), boss_reliquary_of_soulsAI::MoveInLineOfSight(), npc_evergrove_druidAI::MoveInLineOfSight(), boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), boss_kaelthasAI::MoveInLineOfSight(), PlayerbotAI::MovementReset(), instance_nexus::OnCreatureRespawn(), MaNGOS::CannibalizeObjectCheck::operator()(), MaNGOS::TauntFlagObjectCheck::operator()(), MaNGOS::RaiseDeadObjectCheck::operator()(), MaNGOS::NearestAssistCreatureInCreatureRangeCheck::operator()(), MaNGOS::NearestGameObjectFishingHoleCheck::operator()(), MaNGOS::NearestGameObjectEntryInObjectRangeCheck::operator()(), MaNGOS::AllGameObjectEntriesListInObjectRangeCheck::operator()(), MaNGOS::GameObjectFocusCheck::operator()(), MaNGOS::ExplodeCorpseObjectCheck::operator()(), MaNGOS::AnyPlayerInObjectRangeCheck::operator()(), MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::operator()(), MaNGOS::AnyPlayerInCapturePointRange::operator()(), MaNGOS::NearestAttackableUnitInObjectRangeCheck::operator()(), MaNGOS::MostHPMissingInRangeCheck::operator()(), MaNGOS::MostHPPercentMissingInRangeCheck::operator()(), MaNGOS::FriendlyEligibleDispelInRangeCheck::operator()(), MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::operator()(), MaNGOS::FriendlyMissingBuffInRangeNotInCombatCheck::operator()(), MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::operator()(), MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::operator()(), MaNGOS::AnyFriendlyUnitInObjectRangeCheck::operator()(), MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::operator()(), MaNGOS::AnyUnitInObjectRangeCheck::operator()(), MaNGOS::AnyAoETargetUnitInObjectRangeCheck::operator()(), MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), npc_depleted_war_golemAI::OwnerKilledUnit(), npc_zeppitAI::OwnerKilledUnit(), npc_hungry_nether_rayAI::OwnerKilledUnit(), mobs_spectral_ghostly_citizenAI::ReceiveEmote(), Loot::Release(), ScriptedAI::SelectSpell(), Spell::SetTargetMap(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), Aura::TriggerSpell(), instance_uldaman::Update(), Pet::Update(), Player::Update(), AreaAura::Update(), PetAI::UpdateAI(), TotemAI::UpdateAI(), FollowerAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_shadow_imageAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_artoriusAI::UpdateAI(), and npc_storm_tempered_keeperAI::UpdateAI().
IsWithinLOS()
bool WorldObject::IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model = false) const
Definition at line 1551 of file Object.cpp.
References GetCollisionHeight(), GetMap(), GetPhaseMask(), GetPosition(), and Map::IsInLineOfSight().
Referenced by Spell::CheckRange(), Spell::CheckTarget(), ChaseMovementGenerator::DispatchSplineToPosition(), Spell::EffectTransmitted(), ChatHandler::HandleGetLosCommand(), Unit::IsVisibleForOrDetect(), IsWithinLOSInMap(), and Spell::SetTargetMap().
IsWithinLOSForMe()
bool WorldObject::IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model = false) const
Definition at line 1558 of file Object.cpp.
References GetMap(), GetPhaseMask(), GetPosition(), and Map::IsInLineOfSight().
Referenced by GetNearPointAt().
IsWithinLOSInMap()
bool WorldObject::IsWithinLOSInMap (const WorldObject * obj, bool ignoreM2Model = false) const
Definition at line 1543 of file Object.cpp.
References GetCollisionHeight(), GetPosition(), IsInMap(), and IsWithinLOS().
Referenced by PlayerbotAI::_HandleCommandAttack(), PlayerbotAI::_HandleCommandNeutralize(), PlayerbotAI::_HandleCommandPull(), npc_escortAI::AssistPlayerInCombat(), FollowerAI::AssistPlayerInCombat(), PlayerbotAI::CastSpell(), Spell::CheckCast(), UnitAI::CheckForHelp(), Spell::CheckTarget(), UnitAI::DetectOrAttack(), Spell::EffectDummy(), Spell::FilterTargetMap(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePetActionHelper(), Unit::MeetsSelectAttackingRequirement(), npc_rizzle_sprysprocketAI::MoveInLineOfSight(), npc_depth_chargeAI::MoveInLineOfSight(), boss_zumrahAI::MoveInLineOfSight(), boss_jedogaAI::MoveInLineOfSight(), boss_krikthirAI::MoveInLineOfSight(), boss_anubarak_trialAI::MoveInLineOfSight(), npc_queen_lanathel_introAI::MoveInLineOfSight(), npc_runic_colossusAI::MoveInLineOfSight(), boss_saraAI::MoveInLineOfSight(), boss_exarch_maladaarAI::MoveInLineOfSight(), boss_grandmaster_vorpilAI::MoveInLineOfSight(), mob_enchanted_elementalAI::MoveInLineOfSight(), boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), mob_fel_orc_convertAI::MoveInLineOfSight(), npc_veneratus_spawn_nodeAI::MoveInLineOfSight(), boss_soccothratesAI::MoveInLineOfSight(), GuardAI::MoveInLineOfSight(), PetAI::MoveInLineOfSight(), CreatureEventAI::MoveInLineOfSight(), boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_amanishi_lookoutAI::MoveInLineOfSight(), npc_eagle_trash_aggro_triggerAI::MoveInLineOfSight(), npc_dalaran_guardian_mageAI::MoveInLineOfSight(), boss_rimefang_posAI::MoveInLineOfSight(), boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlinaAI::MoveInLineOfSight(), boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_reliquary_of_soulsAI::MoveInLineOfSight(), npc_reliquary_LOS_aggro_triggerAI::MoveInLineOfSight(), boss_kaelthasAI::MoveInLineOfSight(), ABEffect000::OnCheckTarget(), DawnbladeAttack::OnCheckTarget(), GreaterInvisibilityMob::OnPeriodicTickEnd(), MaNGOS::NearestAssistCreatureInCreatureRangeCheck::operator()(), MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::operator()(), PlayerbotWarriorAI::Pull(), boss_mandokirAI::ReceiveAIEvent(), Unit::SelectRandomFriendlyTarget(), Unit::SelectRandomUnfriendlyTarget(), and PetAI::UpdateAI().
LockOutSpells()
void WorldObject::LockOutSpells (SpellSchoolMask schoolMask, uint32 duration) virtual
Reimplemented in Player, and Creature.
Definition at line 2974 of file Object.cpp.
References GetMap(), m_lockoutMap, and MAX_SPELL_SCHOOL.
Referenced by Spell::EffectInterruptCast(), Creature::LockOutSpells(), and Player::LockOutSpells().
MonsterSay()
void WorldObject::MonsterSay (const char * text, uint32 language, Unit const * target = nullptr) const
Definition at line 1925 of file Object.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_SAY, CHAT_TAG_NONE, CONFIG_FLOAT_LISTEN_RANGE_SAY, GetName(), Object::GetObjectGuid(), SendMessageToSetInRange(), and sWorld.
Referenced by ChatHandler::HandleNpcSayCommand(), npc_supplicantAI::MoveInLineOfSight(), and npc_supplicantAI::UpdateAI().
MonsterText()
void WorldObject::MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const * target) const
Function that sends a text associated to a MangosString or BroadcastText.
Definition at line 1998 of file Object.cpp.
References _DoLocalizedTextAround(), CHAT_MSG_MONSTER_EMOTE, CHAT_MSG_MONSTER_PARTY, CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_WHISPER, CHAT_MSG_MONSTER_YELL, CHAT_MSG_RAID_BOSS_EMOTE, CHAT_MSG_RAID_BOSS_WHISPER, CHAT_TYPE_BOSS_EMOTE, CHAT_TYPE_BOSS_WHISPER, CHAT_TYPE_PARTY, CHAT_TYPE_SAY, CHAT_TYPE_TEXT_EMOTE, CHAT_TYPE_WHISPER, CHAT_TYPE_YELL, CHAT_TYPE_ZONE_EMOTE, CHAT_TYPE_ZONE_YELL, CONFIG_FLOAT_LISTEN_RANGE_SAY, CONFIG_FLOAT_LISTEN_RANGE_TEXTEMOTE, CONFIG_FLOAT_LISTEN_RANGE_YELL, Map::ExecuteMapWorkerZone(), GetMap(), Object::GetTypeId(), GetZoneId(), LANG_UNIVERSAL, GroupReference::next(), sWorld, and TYPEID_PLAYER.
Referenced by DoDisplayText().
MonsterTextEmote()
void WorldObject::MonsterTextEmote (const char * text, Unit const * target, bool IsBossEmote = false) const
Definition at line 1941 of file Object.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_EMOTE, CHAT_MSG_RAID_BOSS_EMOTE, CHAT_TAG_NONE, CONFIG_FLOAT_LISTEN_RANGE_TEXTEMOTE, CONFIG_FLOAT_LISTEN_RANGE_YELL, GetName(), Object::GetObjectGuid(), LANG_UNIVERSAL, SendMessageToSetInRange(), and sWorld.
Referenced by ChatHandler::HandleNpcTextEmoteCommand(), and Battlefield::SendZoneWarning().
MonsterWhisper()
void WorldObject::MonsterWhisper (const char * text, Unit const * target, bool IsBossWhisper = false) const
Definition at line 1949 of file Object.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_WHISPER, CHAT_MSG_RAID_BOSS_WHISPER, CHAT_TAG_NONE, GetName(), Object::GetObjectGuid(), Object::GetTypeId(), LANG_UNIVERSAL, and TYPEID_PLAYER.
Referenced by Aura::HandleAuraDummy(), ChatHandler::HandleNpcWhisperCommand(), npc_mojoAI::ReceiveEmote(), and BattlefieldWG::SendPromotionWhisper().
MonsterYell()
void WorldObject::MonsterYell (const char * text, uint32 language, Unit const * target = nullptr) const
Definition at line 1933 of file Object.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_MONSTER_YELL, CHAT_TAG_NONE, CONFIG_FLOAT_LISTEN_RANGE_YELL, GetName(), Object::GetObjectGuid(), LANG_UNIVERSAL, SendMessageToSetInRange(), and sWorld.
Referenced by ChatHandler::HandleNpcYellCommand().
MovePositionToFirstCollision()
void WorldObject::MovePositionToFirstCollision (Position & pos, float dist, float angle)
Definition at line 1815 of file Object.cpp.
References AdjustZForCollision(), ATTACK_DISTANCE, PathFinder::calculate(), GenericTransport::CalculatePassengerOffset(), GenericTransport::CalculatePassengerPosition(), CONTACT_DISTANCE, GetCollisionHeight(), Map::GetHitPosition(), GetMap(), PathFinder::getPath(), PathFinder::getPathType(), GetPhaseMask(), GetTransport(), Object::IsUnit(), m_position, MaNGOS::NormalizeMapCoord(), Position::o, PATHFIND_NOPATH, UpdateAllowedPositionZ(), Position::x, Position::y, and Position::z.
Referenced by FormationMovementGenerator::BuildPath(), GetFirstCollisionPosition(), FlignTorch::OnDestTarget(), and Spell::SetTargetMap().
OnEventHappened()
virtual void WorldObject::OnEventHappened (uint16 , bool , bool) inline virtual
Reimplemented in GameObject, and Creature.
Definition at line 1197 of file Object.h.
PlayDirectSound()
void WorldObject::PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters = PlayPacketParameters(PLAY_SET)) const
Definition at line 2582 of file Object.cpp.
References HandlePlayPacketSettings(), and SMSG_PLAY_SOUND.
Referenced by DoDisplayText(), npc_felhound_trackerAI::DoFindNewCrystal(), ScriptedAI::DoPlaySoundToSet(), Spell::EffectDummy(), Spell::EffectPlaySound(), Spell::EffectScriptEffect(), boss_archimondeAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), Aura::HandleAuraDummy(), ChatHandler::HandleDebugPlaySoundCommand(), boss_kazrogalAI::JustDied(), CombatAI::KilledUnit(), npc_orphaned_mammoth_calfAI::MoveInLineOfSight(), HorsemanManiacalLaugh::OnApply(), HorsemanConflagrateTargetTest::OnEffectExecute(), CreatureEventAI::ProcessAction(), Battlefield::SendZoneWarning(), Aura::TriggerSpell(), npc_supplicantAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), and go_ai_bell::UpdateAI().
PlayDistanceSound()
void WorldObject::PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters = PlayPacketParameters(PLAY_SET)) const
Definition at line 2574 of file Object.cpp.
References Object::GetObjectGuid(), HandlePlayPacketSettings(), and SMSG_PLAY_OBJECT_SOUND.
Referenced by npc_kerlonianAI::Aggro(), npc_lazy_peonAI::Awaken(), ScriptAction::ExecuteDbscriptCommand(), Aura::HandleAuraDummy(), ChatHandler::HandleDebugPlaySoundCommand(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), npc_imp_in_a_ball::JustRespawned(), npc_lazy_peonAI::MovementInform(), npc_imp_in_a_ball::UpdateAI(), npc_supplicantAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), and npc_ancestral_wolfAI::WaypointReached().
PlayMusic()
void WorldObject::PlayMusic (uint32 sound_id, PlayPacketParameters parameters = PlayPacketParameters(PLAY_SET)) const
Definition at line 2589 of file Object.cpp.
References HandlePlayPacketSettings(), and SMSG_PLAY_MUSIC.
Referenced by boss_illidan_stormrageAI::Aggro(), Spell::EffectPlayMusic(), Spell::EffectScriptEffect(), boss_illidan_stormrageAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleDebugPlayMusicCommand(), npc_arthasAI::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), boss_archimondeAI::MovementInform(), go_brewfest_music::PlayAllianceMusic(), go_brewfest_music::PlayHordeMusic(), go_pirate_day_music::UpdateAI(), and go_ai_dmf_music::UpdateAI().
PlaySpellVisual()
void WorldObject::PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters = PlayPacketParameters(PLAY_SET)) const
Definition at line 2596 of file Object.cpp.
References Object::GetObjectGuid(), HandlePlayPacketSettings(), and SMSG_PLAY_SPELL_VISUAL.
Referenced by boss_lady_vashjAI::DoInformGeneratorStopped(), Spell::EffectDummy(), ChatHandler::HandleDebugSpellVisual(), boss_illidan_stormrageAI::HandlePhaseTransition(), FoodAnimation::OnHeartbeat(), and DrinkAnimation::OnHeartbeat().
PrintCooldownList()
void WorldObject::PrintCooldownList (ChatHandler & chat) const
Definition at line 3023 of file Object.cpp.
References ConvertMillisecondToStr(), Map::GetCurrentClockTime(), GetMap(), m_cooldownMap, m_GCDCatMap, m_lockoutMap, and ChatHandler::PSendSysMessage().
Referenced by ChatHandler::HandleCooldownListCommand().
PrintCoordinatesError()
bool WorldObject::PrintCoordinatesError (float x, float y, float z, char const * descr) const
Definition at line 2706 of file Object.cpp.
References Object::GetGuidStr(), GetMapId(), and sLog.
Referenced by Creature::GetRespawnCoord().
Relocate() [1/2]
void WorldObject::Relocate (float x, float y, float z)
Definition at line 1373 of file Object.cpp.
References MovementInfo::ChangePosition(), GetOrientation(), Object::isType(), m_movementInfo, m_position, TYPEMASK_UNIT, Position::x, Position::y, and Position::z.
Relocate() [2/2]
void WorldObject::Relocate (float x, float y, float z, float orientation)
Definition at line 1362 of file Object.cpp.
References MovementInfo::ChangePosition(), Object::isType(), m_movementInfo, m_position, Position::o, TYPEMASK_UNIT, Position::x, Position::y, and Position::z.
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), GameObject::Create(), Player::Create(), Corpse::Create(), Transport::Create(), DynamicObject::Create(), Map::CreatureRelocation(), Map::CreatureRespawnRelocation(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), Spell::DoSummonPet(), Map::DynamicObjectRelocation(), Spell::EffectCreateTamedPet(), Map::GameObjectRelocation(), ChatHandler::HandleGameObjectMoveCommand(), WorldSession::HandleMoveWorldportAckOpcode(), Player::LoadFromDB(), Creature::LoadFromDB(), Corpse::LoadFromDB(), Map::PlayerRelocation(), CreatureCreatePos::Relocate(), Player::RelocateToHomebind(), Transport::TeleportTransport(), GenericTransport::UpdatePassengerPosition(), GenericTransport::UpdatePosition(), and Unit::UpdateSplinePosition().
RemoveAllCooldowns()
virtual void WorldObject::RemoveAllCooldowns (bool = false) inline virtual
Reimplemented in Player.
Definition at line 1212 of file Object.h.
References CooldownContainer::clear(), m_cooldownMap, m_GCDCatMap, and m_lockoutMap.
Referenced by ChatHandler::HandleCooldownClearCommand(), NpcSpellClick_npc_obedienceCrystal(), and npc_obedienceCrystalAI::Reset().
RemoveClientIAmAt()
void WorldObject::RemoveClientIAmAt (Player const * player)
Definition at line 3304 of file Object.cpp.
References Object::GetObjectGuid(), and m_clientGUIDsIAmAt.
Referenced by Player::RemoveAtClient().
RemoveFromClientUpdateList()
void WorldObject::RemoveFromClientUpdateList () override virtual
Reimplemented from Object.
Definition at line 2650 of file Object.cpp.
References GetMap(), and Map::RemoveUpdateObject().
RemoveFromWorld()
void WorldObject::RemoveFromWorld () override virtual
Reimplemented from Object.
Reimplemented in Unit, Player, Pet, GameObject, DynamicObject, Creature, and Corpse.
Definition at line 2140 of file Object.cpp.
References GetTransport(), Object::IsPlayer(), m_currMap, m_isOnEventNotified, m_stringIds, Map::RemoveFromOnEventNotified(), Object::RemoveFromWorld(), and Map::RemoveStringIdObject().
Referenced by CleanupsBeforeDelete(), and GameObject::RemoveFromWorld().
RemoveSpellCategoryCooldown()
void WorldObject::RemoveSpellCategoryCooldown (uint32 category, bool updateClient = true) virtual
Reimplemented in Player.
Definition at line 2997 of file Object.cpp.
References m_cooldownMap, and CooldownContainer::RemoveByCategory().
Referenced by Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), and VigilanceTrigger::OnEffectExecute().
RemoveSpellCooldown() [1/2]
void WorldObject::RemoveSpellCooldown (SpellEntry const & spellEntry, bool updateClient = true) virtual
Reimplemented in Player.
Definition at line 2992 of file Object.cpp.
References SpellEntry::Id, m_cooldownMap, and CooldownContainer::RemoveBySpellId().
Referenced by Unit::_UpdateAutoRepeatSpell(), Spell::cancel(), CastHighestStealthRank(), boss_hakkarAI::ExecuteAction(), ChatHandler::HandleCooldownClearCommand(), Aura::HandleModMechanicImmunity(), Aura::HandleShapeshiftBoosts(), SpellAuraHolder::HandleSpellSpecificBoosts(), RaiseDeadDk::OnEffectExecute(), RighteousDefense::OnEffectExecute(), DivineStormCooldown::OnEffectExecute(), and RemoveSpellCooldown().
RemoveSpellCooldown() [2/2]
void WorldObject::RemoveSpellCooldown (uint32 spellId, bool updateClient = true)
Definition at line 2983 of file Object.cpp.
References SQLStorage::LookupEntry(), RemoveSpellCooldown(), and sSpellTemplate.
RemoveStringId()
void WorldObject::RemoveStringId (std::string & stringId)
Definition at line 1315 of file Object.cpp.
References GetMap(), Map::GetMapDataContainer(), MapDataContainer::GetStringId(), and SetStringId().
ResetGCD()
void WorldObject::ResetGCD (SpellEntry const * spellEntry = nullptr)
Definition at line 3002 of file Object.cpp.
References m_GCDCatMap, and SpellEntry::StartRecoveryCategory.
Referenced by Spell::cancel().
ResetMap()
virtual void WorldObject::ResetMap () inline virtual
Reimplemented in Player.
Definition at line 1172 of file Object.h.
References m_currMap.
Referenced by Player::ResetMap(), and Transport::TeleportTransport().
SaveRespawnTime()
virtual void WorldObject::SaveRespawnTime () inline virtual
Reimplemented in GameObject, and Creature.
Definition at line 1157 of file Object.h.
SendGameObjectCustomAnim()
void WorldObject::SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId = 0) const
Definition at line 2111 of file Object.cpp.
References SendMessageToSet(), and SMSG_GAMEOBJECT_CUSTOM_ANIM.
Referenced by go_bonfire::ChangeState(), instance_razorfen_downs::DoSpawnWaveIfCan(), Spell::EffectActivateObject(), ScriptAction::ExecuteDbscriptCommand(), GOUse_go_ossirian_crystal(), OutdoorPvP::SetBannerVisual(), GameObject::Update(), go_imp_in_a_ball::UpdateAI(), go_ai_suppression::UpdateAI(), go_ai_lightning::UpdateAI(), go_smoke_beacon::UpdateAI(), and GameObject::Use().
SendMessageToAllWhoSeeMe()
void WorldObject::SendMessageToAllWhoSeeMe (WorldPacket const & data, bool self) const virtual
Reimplemented in Player.
Definition at line 2096 of file Object.cpp.
References GetMap(), Object::IsInWorld(), and m_clientGUIDsIAmAt.
Referenced by Movement::MoveSplineInit::Launch(), Player::SendMessageToAllWhoSeeMe(), and Movement::MoveSplineInit::Stop().
SendMessageToSet()
void WorldObject::SendMessageToSet (WorldPacket const & data, bool self) const virtual
Reimplemented in Player.
Definition at line 2072 of file Object.cpp.
References GetMap(), Object::IsInWorld(), and Map::MessageBroadcast().
Referenced by GameObject::DealGameObjectDamage(), Unit::DealMeleeDamage(), Spell::Delayed(), Spell::EffectInstaKill(), Spell::EffectStealBeneficialBuff(), Spell::EvaluateResultLists(), Unit::HandleEmoteCommand(), WorldSession::HandleOnMissileTrajectoryCollision(), HandlePlayPacketSettings(), Unit::SendAIReaction(), Unit::SendAttackStateUpdate(), SpellAuraHolder::SendAuraUpdate(), Spell::SendChannelStart(), Spell::SendChannelUpdate(), Unit::SendEnchantmentLog(), Unit::SendEnergizeSpellLog(), Unit::SendEnvironmentalDamageLog(), Unit::SendFlightSplineSyncIfNeeded(), SendGameObjectCustomAnim(), Unit::SendHealSpellLog(), Unit::SendHeartBeat(), Unit::SendHighestThreatUpdate(), Spell::SendInterrupted(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), Unit::SendMoveRoot(), SendObjectDeSpawnAnim(), Unit::SendPeriodicAuraLog(), Unit::SendPetDismiss(), Unit::SendSpellDamageResist(), Spell::SendSpellGo(), Unit::SendSpellMiss(), Unit::SendSpellNonMeleeDamageLog(), Unit::SendSpellOrDamageImmune(), Spell::SendSpellStart(), Unit::SendThreatClear(), Unit::SendThreatRemove(), Unit::SendThreatUpdate(), SpellLog::SendToSet(), Unit::SetCanFly(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetPower(), Unit::SetPowerType(), Unit::SetSpeedRate(), Unit::SetSwim(), Unit::SetVehicleId(), Creature::SetWalk(), Unit::SetWaterWalk(), and Unit::Unmount().
SendMessageToSetExcept()
void WorldObject::SendMessageToSetExcept (WorldPacket const & data, Player const * skipped_receiver) const
Definition at line 2086 of file Object.cpp.
References GetMap(), Object::IsInWorld(), and Cell::VisitWorldObjects().
Referenced by WorldSession::HandleForceSpeedChangeAckOpcodes(), WorldSession::HandleMoveFlagChangeOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveTimeSkippedOpcode(), and Unit::SendTeleportPacket().
SendMessageToSetInRange()
void WorldObject::SendMessageToSetInRange (WorldPacket const & data, float dist, bool self) const virtual
Reimplemented in Player.
Definition at line 2079 of file Object.cpp.
References GetMap(), Object::IsInWorld(), and Map::MessageDistBroadcast().
Referenced by MonsterSay(), MonsterTextEmote(), and MonsterYell().
SendObjectDeSpawnAnim()
void WorldObject::SendObjectDeSpawnAnim (ObjectGuid guid) const
Definition at line 2104 of file Object.cpp.
References SendMessageToSet(), and SMSG_GAMEOBJECT_DESPAWN_ANIM.
Referenced by DynamicObject::Delete(), GameObject::Delete(), and GameObject::Update().
SetActiveObjectState()
void WorldObject::SetActiveObjectState (bool active)
Definition at line 2712 of file Object.cpp.
References Map::AddToActive(), GetMap(), isActiveObject(), Object::IsInWorld(), Object::isType(), m_isActiveObject, Map::RemoveFromActive(), and TYPEMASK_PLAYER.
Referenced by Creature::AddToWorld(), GameObject::AddToWorld(), CinematicMgr::BeginCinematic(), boss_algalonAI::boss_algalonAI(), boss_cthunAI::boss_cthunAI(), boss_highlord_kruulAI::boss_highlord_kruulAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), boss_majordomoAI::CorpseRemoved(), npc_shadowlord_deathwailAI::DoReleaseSoulstealersAndReset(), boss_archimondeAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), HomeMovementGenerator< Creature >::Finalize(), go_ai_bell::go_ai_bell(), GoNecropolis::GoNecropolis(), GossipSelect_npc_jaina_proudmoore(), GossipSelect_npc_thrall(), HomeMovementGenerator< Creature >::Initialize(), boss_cthunAI::JustDied(), npc_shadowlord_deathwailAI::JustDied(), npc_apprentice_mirvedaAI::JustRespawned(), boss_majordomoAI::JustRespawned(), mob_shadowmoon_soulstealerAI::JustRespawned(), npc_skyguard_prisonerAI::JustRespawned(), NecropolisAI::NecropolisAI(), NecropolisProxyAI::NecropolisProxyAI(), NecropolisRelayAI::NecropolisRelayAI(), NecroticShard::NecroticShard(), npc_deadsoul_orb::npc_deadsoul_orb(), npc_rizzle_sprysprocketAI::npc_rizzle_sprysprocketAI(), npc_spirit_guideAI::npc_spirit_guideAI(), npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), world_map_outland::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), instance_obsidian_sanctum::OnCreatureCreate(), world_map_kalimdor::OnObjectCreate(), Player::Player(), QuestAccept_npc_00x09hl(), QuestAccept_npc_oox17tn(), QuestAccept_npc_oox22fe(), npc_apprentice_mirvedaAI::Reset(), guard_hallows_end_helperAI::Reset(), npc_scrapped_fel_reaverAI::ResetEvent(), npc_commanderAI::ResetEvent(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), npc_scrapped_fel_reaverAI::SpellHit(), npc_commanderAI::StartEvent(), npc_apprentice_mirvedaAI::StartEvent(), SummonCreature(), GameObject::TickCapturePoint(), and npc_thrall_old_hillsbradAI::WaypointReached().
SetCurrentCell()
void WorldObject::SetCurrentCell (Cell const & cell) inline
Definition at line 1236 of file Object.h.
References m_currentCell.
Referenced by Map::AddToGrid(), and addUnitState().
SetDebugFlag()
void WorldObject::SetDebugFlag (CMDebugFlags flag) inline
Definition at line 1231 of file Object.h.
References m_debugFlags.
Referenced by ChatHandler::HandleDebugObjectFlags().
SetLocationInstanceId()
void WorldObject::SetLocationInstanceId (uint32 _instanceId) inline protected
Definition at line 1291 of file Object.h.
References m_InstanceId.
Referenced by Corpse::LoadFromDB().
SetLocationMapId()
void WorldObject::SetLocationMapId (uint32 _mapId) inline protected
Definition at line 1290 of file Object.h.
References m_mapId.
Referenced by Player::Create(), Player::LoadFromDB(), Corpse::LoadFromDB(), and Player::RelocateToHomebind().
SetMap()
void WorldObject::SetMap (Map * map)
Definition at line 2119 of file Object.cpp.
References Map::GetId(), Map::GetInstanceId(), m_currMap, m_InstanceId, m_mapId, and MANGOS_ASSERT.
Referenced by Map::Add(), Creature::Create(), GameObject::Create(), Player::Create(), Pet::Create(), Totem::Create(), Corpse::Create(), DynamicObject::Create(), WorldSession::HandleMoveWorldportAckOpcode(), Player::LoadFromDB(), LoadHelper(), and Transport::LoadTransport().
SetName()
void WorldObject::SetName (const std::string & newname) inline
Definition at line 1060 of file Object.h.
References m_name.
Referenced by Transport::Create(), Pet::CreateBaseAtCreature(), EffectDummyCreature_npc_kitten(), Spell::EffectSummonPet(), Aura::HandleMirrorName(), WorldSession::HandlePetRename(), Creature::InitEntry(), and Pet::LoadPetFromDB().
SetNotifyOnEventState()
void WorldObject::SetNotifyOnEventState (bool state)
Definition at line 2729 of file Object.cpp.
References Map::AddToOnEventNotified(), GetMap(), Object::IsInWorld(), m_isOnEventNotified, and Map::RemoveFromOnEventNotified().
Referenced by go_ai_bell::go_ai_bell().
SetOrientation()
void WorldObject::SetOrientation (float orientation)
Definition at line 1383 of file Object.cpp.
References MovementInfo::ChangeOrientation(), Object::isType(), m_movementInfo, m_position, Position::o, and TYPEMASK_UNIT.
Referenced by FollowMovementGenerator::_setOrientation(), Spell::EffectDistract(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), boss_zuljinAI::MovementInform(), boss_archimondeAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_commanderAI::MovementInform(), boss_sindragosaAI::MovementInform(), boss_lady_vashjAI::MovementInform(), npc_commander_arcusAI::npc_commander_arcusAI(), UnitAI::OnChannelStateChange(), SpoutTurning::OnPeriodicTrigger(), UnitAI::OnSpellCastStateChange(), npc_netherspite_portalAI::ReceiveAIEvent(), npc_warp_gate::Reset(), world_map_outland::ScriptAction(), Unit::SetInFront(), npc_frostbiteAI::SpellHit(), npc_commander_hobbAI::StartAttackingEvent(), npc_ethereum_prisoner_dungeonAI::StartEvent(), Aura::TriggerSpell(), ElevatorTransport::Update(), Spell::update(), npc_netherspite_portalAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), and boss_kaelthasAI::UpdateAI().
SetOwnerGuid()
virtual void WorldObject::SetOwnerGuid (ObjectGuid) inline virtual
Reimplemented in Unit, Pet, GameObject, DynamicObject, and Corpse.
Definition at line 1065 of file Object.h.
SetPhaseMask()
void WorldObject::SetPhaseMask (uint32 newPhaseMask, bool update) virtual
Reimplemented in Unit, Player, and GameObject.
Definition at line 2566 of file Object.cpp.
References Object::IsInWorld(), m_phaseMask, and UpdateVisibilityAndView().
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), Corpse::LoadFromDB(), GameObject::SetPhaseMask(), and Unit::SetPhaseMask().
SetStringId()
void WorldObject::SetStringId (uint32 stringId, bool apply)
Definition at line 1292 of file Object.cpp.
References Map::AddStringIdObject(), ByteConverter::apply(), GetMap(), Object::IsInWorld(), m_stringIds, and Map::RemoveStringIdObject().
Referenced by AddStringId(), GameObject::Create(), ScriptAction::ExecuteDbscriptCommand(), Creature::LoadFromDB(), GameObject::LoadFromDB(), RemoveStringId(), SummonCreature(), and Creature::UpdateEntry().
SetTransport()
void WorldObject::SetTransport (GenericTransport * t) inline
Definition at line 1240 of file Object.h.
References m_transport.
Referenced by GenericTransport::AddPassenger(), and GenericTransport::RemovePassenger().
SetTransportInfo()
void WorldObject::SetTransportInfo (TransportInfo * transportInfo) inline
Definition at line 961 of file Object.h.
References m_transportInfo.
Referenced by TransportBase::BoardPassenger(), and TransportBase::UnBoardPassenger().
SpawnCreature()
Creature * WorldObject::SpawnCreature (uint32 dbGuid, Map * map, uint32 forcedEntry = 0, GenericTransport * transport = nullptr) static
Definition at line 2341 of file Object.cpp.
References Map::CanSpawn(), CreatureData::id, Creature::LoadFromDB(), sLog, sObjectMgr, CreatureData::spawnMask, and TYPEID_UNIT.
Referenced by SpawnInfo::ConstructForMap(), npc_kalecgosAI::HandleTransform(), npc_kiljaeden_controllerAI::JustDidDialogueStep(), world_map_kalimdor::OnCreatureDeath(), SpawnGroup::Spawn(), instance_deadmines::SpawnFirstDeadminesPatrol(), instance_sunwell_plateau::SpawnGauntlet(), instance_sunwell_plateau::SpawnKiljaeden(), Transport::SpawnPassengers(), instance_deadmines::SpawnSecondDeadminesPatrol(), instance_deadmines::SpawnThirdDeadminesPatrol(), and instance_sunwell_plateau::SpawnTwins().
SpawnGameObject()
GameObject * WorldObject::SpawnGameObject (uint32 dbGuid, Map * map, uint32 forcedEntry = 0, GenericTransport * transport = nullptr) static
Definition at line 2323 of file Object.cpp.
References Map::CanSpawn(), GameObject::CreateGameObject(), GameObjectData::id, GameObject::LoadFromDB(), sObjectMgr, GameObjectData::spawnMask, and TYPEID_GAMEOBJECT.
Referenced by SpawnInfo::ConstructForMap(), instance_ulduar::OnObjectSpawn(), SpawnGroup::Spawn(), and Transport::SpawnPassengers().
SummonCreature() [1/2]
Creature * WorldObject::SummonCreature (TempSpawnSettings settings, Map * map, uint32 phaseMask) static
Definition at line 2182 of file Object.cpp.
References TempSpawnSettings::activeObject, GenericTransport::AddPassenger(), GenericTransport::CalculatePassengerPosition(), CONTACT_DISTANCE, TempSpawnSettings::corpseDespawnTime, Creature::Create(), TempSpawnSettings::dbscriptTarget, TempSpawnSettings::despawnTime, CreatureLinkingHolder::DoCreatureLinkingEvent(), TempSpawnSettings::entry, TempSpawnSettings::faction, TempSpawnSettings::forcedOnTop, Map::GenerateLocalLowGuid(), Map::GetCreatureLinkingHolder(), ObjectMgr::GetCreatureTemplate(), Object::GetGuidStr(), CreatureInfo::GetHighGuid(), Unit::GetMotionMaster(), Object::GetObjectGuid(), GetOrientation(), GetTransport(), Object::GetTypeId(), Unit::IsLinkingEventTrigger(), TempSpawnSettings::level, LINKING_EVENT_RESPAWN, Creature::LoadEquipment(), m_movementInfo, TempSpawnSettings::modelId, TempSpawnSettings::movegen, Position::o, TempSpawnSettings::ori, TempSpawnSettings::ownerGuid, TempSpawnSettings::pathId, TempSpawnSettings::pathOrigin, POWER_MANA, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), Creature::SelectLevel(), SetActiveObjectState(), Creature::SetCorpseDelay(), Creature::SetDefaultMovementType(), MotionMaster::SetDefaultPathId(), Unit::SetDisplayId(), Unit::setFaction(), Unit::SetHealth(), Unit::SetHover(), Unit::SetLevel(), Unit::SetOwnerGuid(), Unit::SetPower(), Creature::SetRespawnCoord(), TempSpawnSettings::setRun, Creature::SetSpawnCounting(), SetStringId(), Object::SetUInt32Value(), Creature::SetWalk(), sLog, sObjectMgr, TempSpawnSettings::spawnCounting, TempSpawnSettings::spawnDataEntry, TempSpawnSettings::spawner, TempSpawnSettings::spawnPathId, TempSpawnSettings::spawnType, TempSpawnSettings::spellId, TemporarySpawn::Summon(), MovementInfo::t_pos, TempSpawnSettings::tempSpawnMovegen, TYPEID_UNIT, UNIT_CREATED_BY_SPELL, UNIT_FIELD_FLAGS, UNIT_NPC_FLAGS, GenericTransport::UpdatePassengerPosition(), TempSpawnSettings::waypointId, Position::x, TempSpawnSettings::x, Position::y, TempSpawnSettings::y, Position::z, and TempSpawnSettings::z.
Referenced by BattleGroundAV::AddPlayer(), BattleGroundIC::AddPlayer(), boss_ambassador_flamelashAI::Aggro(), boss_croneAI::Aggro(), boss_mandokirAI::Aggro(), boss_ossirianAI::Aggro(), npc_ouro_spawnerAI::Aggro(), boss_anubarak_trialAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_warbringer_omroggAI::Aggro(), AreaTrigger_at_ancient_leaf(), AreaTrigger_at_blackrock_spire(), AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_hive_tower(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_murkdeep(), AreaTrigger_at_nats_landing(), AreaTrigger_at_rampart_skull(), AreaTrigger_at_raven_prophecy(), AreaTrigger_at_ring_of_law(), AreaTrigger_at_scent_larkorwi(), AreaTrigger_at_sentry_point(), AreaTrigger_at_shade_of_eranikus(), AreaTrigger_at_shadowforge_bridge(), AreaTrigger_at_socrethar_seat(), AreaTrigger_at_spearborn_encampment(), AreaTrigger_at_twilight_grove(), AreaTrigger_at_underbelly_a(), AreaTrigger_at_underbelly_h(), npc_dragonmaw_racerAI::AttackPlayer(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), CinematicMgr::BeginCinematic(), npc_shattered_hand_legionnaire::CallForReinforcements(), npc_grand_admiral_westwindAI::DamageTaken(), npc_private_hendelAI::DamageTaken(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), boss_onyxiaAI::DidSummonWhelps(), ChaseMovementGenerator::DispatchSplineToPosition(), BattleGroundIC::DoApplyObjectiveBenefits(), instance_ulduar::DoCallLeviathanHelp(), boss_jedogaAI::DoCallVolunteers(), boss_illidan_stormrageAI::DoCastEyeBlastIfCan(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), instance_trial_of_the_crusader::DoHandleEventEpilogue(), boss_malacrassAI::DoInitializeAdds(), boss_priestess_delrissaAI::DoInitializeCompanions(), npc_anachronos_the_ancientAI::DoInitialSummons(), boss_skadiAI::DoPrepareForGauntlet(), npc_brain_yogg_saronAI::DoPrepareIllusion(), instance_karazhan::DoPrepareOperaStage(), boss_anubarak_trialAI::DoRefreshSpheres(), go_elemental_rift::DoRespawnElementalsIfCan(), instance_scholomance::DoRespawnEntranceRoom(), instance_stratholme::DoScarletBastionDefense(), instance_blackrock_spire::DoSendNextFlamewreathWave(), instance_blackrock_spire::DoSendNextStadiumWave(), npc_daphne_stilwellAI::DoSendWave(), instance_culling_of_stratholme::DoSetupEntranceSoldiers(), instance_halls_of_reflection::DoSetupEscapeEvent(), world_map_eastern_kingdoms::DoSpawn(), boss_malygosAI::DoSpawnAdds(), boss_hydross_the_unstableAI::DoSpawnAdds(), npc_rinjiAI::DoSpawnAmbush(), npc_ruul_snowhoofAI::DoSpawnAmbush(), instance_ruins_of_ahnqiraj::DoSpawnAndorovIfCan(), boss_thorimAI::DoSpawnArenaDwarf(), instance_culling_of_stratholme::DoSpawnArthasIfNeeded(), npc_wildaAI::DoSpawnAssassin(), instance_sunken_temple::DoSpawnAtalarionIfCan(), npc_lakota_windsongAI::DoSpawnBandits(), instance_mechanar::DoSpawnBridgeWave(), instance_culling_of_stratholme::DoSpawnBurningCityUndead(), npc_demoniac_scryerAI::DoSpawnButtress(), npc_kelerun_bloodmournAI::DoSpawnChallengers(), instance_culling_of_stratholme::DoSpawnChromieIfNeeded(), boss_algalonAI::DoSpawnCollapsingStar(), boss_algalonAI::DoSpawnConstellations(), instance_culling_of_stratholme::DoSpawnCorruptorIfNeeded(), npc_drijyaAI::DoSpawnCreature(), npc_demoniac_scryerAI::DoSpawnDemon(), boss_flame_leviathanAI::DoSpawnFreyaWard(), npc_kanatiAI::DoSpawnGalak(), instance_scholomance::DoSpawnGandlingIfCan(), boss_moroesAI::DoSpawnGuests(), boss_flame_leviathanAI::DoSpawnHodirFury(), instance_ulduar::DoSpawnHodirNpcs(), instance_violet_hold::DoSpawnIntroMob(), boss_halion_realAI::DoSpawnMeteorStrike(), boss_flame_leviathanAI::DoSpawnMimironInferno(), npc_feero_ironhandAI::DoSpawnMob(), instance_blackfathom_deeps::DoSpawnMobs(), boss_razorscaleAI::DoSpawnMoleMachines(), instance_oculus::DoSpawnNextBossIfCan(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), instance_stratholme::DoSpawnPlaguedCritters(), instance_stratholme::DoSpawnScarletGuards(), instance_stratholme::DoSpawnScourgeInvaders(), boss_cthunAI::DoSpawnTentacles(), boss_flame_leviathanAI::DoSpawnThorimHammer(), instance_ulduar::DoSpawnThorimNpcs(), boss_uromAI::DoSpawnTrashPack(), instance_pit_of_saron::DoSpawnTyrannusUndead(), world_map_ebon_hold::DoSpawnUndeadWave(), instance_razorfen_downs::DoSpawnWaveIfCan(), npc_paoka_swiftmountainAI::DoSpawnWyvern(), instance_pit_of_saron::DoStartAmbushEvent(), npc_highlord_darion_mograineAI::DoStartConclusion(), npc_meteor_strike_initialAI::DoStartFlameStrikes(), instance_pit_of_saron::DoStartIntroEvent(), instance_pit_of_saron::DoStartTyrannusEvent(), npc_teleportation_portalAI::DoSummon(), boss_anzuAI::DoSummonBirdHelpers(), npc_akamaAI::DoSummonBrokenAshtongue(), boss_anzuAI::DoSummonBroodsOfAnzu(), boss_the_lurker_belowAI::DoSummonCoilfangNaga(), boss_lady_deathwhisperAI::DoSummonCultistWave(), boss_akilzonAI::DoSummonEagles(), boss_eranikusAI::DoSummonHealers(), instance_trial_of_the_champion::DoSummonHeraldIfNeeded(), instance_shattered_halls::DoSummonInitialWave(), npc_anachronos_the_ancientAI::DoSummonKaldorei(), boss_amanitarAI::DoSummonMushrooms(), npc_beast_combat_stalkerAI::DoSummonNextBeast(), npc_blastmaster_emi_shortfuseAI::DoSummonPack(), boss_netherspiteAI::DoSummonPortals(), npc_ranshallaAI::DoSummonPriestess(), npc_anachronos_the_ancientAI::DoSummonQiraji(), instance_trial_of_the_crusader::DoSummonRamsey(), instance_shattered_halls::DoSummonSHZealot(), npc_belnistraszAI::DoSummonSpawner(), boss_ambassador_flamelashAI::DoSummonSpirit(), Spell::DoSummonVehicle(), npc_shadowlord_deathwailAI::DoSummonWave(), npc_eris_havenfireAI::DoSummonWave(), Spell::DoSummonWild(), boss_headless_horsemanAI::DoTossHead(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), npc_muglashAI::DoWaveSummon(), Spell::EffectActivateObject(), Spell::EffectDummy(), EffectDummyCreature_spell_dummy_npc(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectScriptEffect(), boss_kiljaedenAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), PallidHorrorAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), npc_adyen_the_lightwardenAI::ExecuteTimer(), instance_sethekk_halls::FinishAnzuIntro(), world_map_kalimdor::GhostOPlasmEventStep(), GossipSelect_go_manaforge(), GossipSelect_npc_grandmother(), GOUse_go_cage_door(), GOUse_go_fathom_stone(), GOUse_go_furbolg_food(), GOUse_go_mausoleum_door(), GOUse_go_southfury_moonstone(), GOUse_go_stratholme_postbox(), Aura::HandleAuraDummy(), instance_blackrock_depths::HandleBarPatrol(), Unit::HandleDummyAuraProc(), BattleGroundIC::HandleEvent(), boss_vaelastraszAI::HandleIntro(), BattleGroundIC::HandleKillUnit(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapTestHeight(), ChatHandler::HandleNpcTempSpawn(), boss_majordomoAI::HandleOutro(), BattleGroundSA::HandlePlayerClickedOnFlag(), world_map_outland::HandleShartuulSpawnSequence(), Helper_CreateWaypointFor(), VehicleInfo::Initialize(), boss_victor_nefariusAI::JustDidDialogueStep(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), instance_blackrock_spire::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), instance_sunwell_plateau::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_tarethaAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), instance_trial_of_the_champion::JustDidDialogueStep(), instance_trial_of_the_crusader::JustDidDialogueStep(), boss_algalonAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), boss_thorimAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), instance_pinnacle::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), instance_arcatraz::JustDidDialogueStep(), boss_herodAI::JustDied(), boss_ickAI::JustDied(), npc_rimefang_iccAI::JustDied(), npc_spinestalker_iccAI::JustDied(), boss_flame_leviathanAI::JustDied(), boss_exarch_maladaarAI::JustDied(), NecroticShard::JustDied(), boss_forgemaster_garfrostAI::JustDied(), boss_tyrannusAI::JustDied(), mob_webbed_creatureAI::JustDied(), mob_netherweb_victimAI::JustDied(), npc_garaxxasAI::JustReachedHome(), npc_simone_seductressAI::JustReachedHome(), boss_sjonnirAI::JustReachedHome(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_soulgrinderAI::JustRespawned(), npc_vindicator_sedaiAI::JustRespawned(), npc_spawned_oronok_tornheartAI::JustRespawned(), go_fel_cannonball_stack_trap::JustSpawned(), npc_meteor_strike_initialAI::JustSummoned(), boss_saraAI::JustSummoned(), npc_taelan_fordringAI::JustSummoned(), Movement::MoveSplineInit::Launch(), MinionspawnerAI::MinionspawnerAI(), npc_veneratus_spawn_nodeAI::MoveInLineOfSight(), npc_the_scourge_cauldronAI::MoveInLineOfSight(), npc_brann_hosAI::MovementInform(), npc_vindicator_sedaiAI::MovementInform(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), NpcSpellClick_npc_storm_totem(), world_map_outland::OnCreatureDeath(), instance_karazhan::OnCreatureDeath(), world_map_ebon_hold::OnCreatureDeath(), instance_sunwell_plateau::OnCreatureDeath(), world_map_kalimdor::OnCreatureDeath(), instance_ulduar::OnCreatureDeath(), instance_azjol_nerub::OnCreatureEnterCombat(), instance_pit_of_saron::OnCreatureEnterCombat(), spell_summon_undead::OnEffectExecute(), ConjureDreamRift::OnEffectExecute(), spell_icy_blast::OnEffectExecute(), instance_stratholme::OnPlayerEnter(), instance_old_hillsbrad::OnPlayerEnter(), instance_halls_of_reflection::OnPlayerEnter(), instance_pit_of_saron::OnPlayerEnter(), instance_naxxramas::OnPlayerEnter(), instance_ruby_sanctum::OnPlayerEnter(), instance_halls_of_stone::OnPlayerEnter(), instance_ulduar::OnPlayerEnter(), instance_pinnacle::OnPlayerEnter(), instance_shattered_halls::OnPlayerEnter(), instance_mechanar::OnPlayerEnter(), CreatureEventAI::ProcessAction(), BattleGroundEY::ProcessCaptureEvent(), npc_scrapped_fel_reaverAI::ProcessEvent(), ProcessEventId_event_purify_food(), ProcessEventId_event_spell_call_captain(), ProcessEventId_event_summon_terokk(), ProcessEventId_sedai_vision(), ProcessEventId_Soulgrinder(), instance_forge_of_souls::ProcessEventNpcs(), instance_icecrown_citadel::ProcessEventNpcs(), BattleGroundAB::ProcessNodeCapture(), BattleGroundAV::ProcessPlayerDestroyedPoint(), QuestAcceptGO_crystalline_tear(), npc_taelan_fordringAI::ReceiveAIEvent(), boss_arugalAI::ReceiveAIEvent(), boss_sathrovarrAI::ReceiveAIEvent(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_highlord_darion_mograineAI::ReceiveAIEvent(), npc_halion_controllerAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), GameObjectModel::Relocate(), npc_simone_the_inconspicuousAI::Reset(), WorldState::RespawnEmeraldDragons(), WorldState::RespawnHighlordKruul(), npc_twiggy_flatheadAI::SetChallengers(), instance_stratholme::SetData(), world_map_kalimdor::SetData(), instance_blackrock_depths::SetData(), instance_sunken_temple::SetData(), instance_dire_maul::SetData(), instance_shattered_halls::SetData(), BattleGroundSA::SetupGraveyards(), world_map_outland::SpawnAlliesAtCrystalforge(), npc_regthar_deathgateAI::SpawnAllSlot(), boss_warchief_kargath_bladefistAI::SpawnAssassin(), world_map_outland::SpawnBoss(), boss_ahuneAI::SpawnBunnies(), npc_regthar_deathgateAI::SpawnCreature(), npc_commanderAI::SpawnDefenders(), npc_belnistraszAI::SpawnerSummon(), instance_sunwell_plateau::SpawnFelmyst(), instance_ulduar::SpawnFriendlyKeeper(), instance_mount_hyjal::SpawnInvasionWave(), instance_ulduar::SpawnKeeperHelper(), instance_molten_core::SpawnMajordomo(), world_map_outland::SpawnRandomBashirMob(), npc_commanderAI::SpawnSpecificDragonmaw(), world_map_outland::SpawnTowerDefenders(), instance_mount_hyjal::SpawnWave(), npc_blackwing_orbAI::SpellHit(), boss_exarch_maladaarAI::SpellHitTarget(), boss_lethonAI::SpellHitTarget(), instance_sethekk_halls::StartAnzuIntro(), world_map_outland::StartBashirLandingEvent(), npc_apprentice_mirvedaAI::StartEvent(), world_map_outland::StartTransitionPhase(), boss_general_angerforgeAI::SummonAdd(), boss_kelesethAI::SummonAdds(), SummonCreature(), SummonCultists(), npc_thrall_old_hillsbradAI::SummonedCreatureJustDied(), boss_flame_leviathanAI::SummonedMovementInform(), npc_thrall_old_hillsbradAI::SummonedMovementInform(), boss_highlord_kruulAI::SummonFormation(), npc_air_force_botsAI::SummonGuard(), WorldState::SummonMouth(), WorldState::SummonPallid(), npc_grimstoneAI::SummonRingMob(), npc_orphan_matronAI::SummonShadeOfTheHorseman(), npc_lord_illidan_stormrageAI::SummonWave(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_trial_of_the_champion::Update(), instance_naxxramas::Update(), instance_ruby_sanctum::Update(), instance_arcatraz::Update(), instance_halls_of_reflection::Update(), boss_eranikusAI::UpdateAI(), npc_regthar_deathgateAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), npc_infused_crystalAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), boss_julianneAI::UpdateAI(), npc_deathstalker_faerleiaAI::UpdateAI(), npc_dashel_stonefistAI::UpdateAI(), npc_twiggy_flatheadAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_novosAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_kologarnAI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), npc_warp_gate::UpdateAI(), npc_soulgrinderAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_commander_dawnforgeAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_doctorAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_wizzlecranks_shredderAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), Player::UpdateTerainEnvironmentFlags(), npc_ranger_lilathaAI::WaypointReached(), npc_oox22feAI::WaypointReached(), npc_clintar_dw_spiritAI::WaypointReached(), npc_oox17tnAI::WaypointReached(), npc_kayra_longmaneAI::WaypointReached(), npc_squire_roweAI::WaypointReached(), npc_reginald_windsorAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_professor_phizzlethorpeAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_barnesAI::WaypointReached(), npc_miranAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_torekAI::WaypointReached(), npc_feero_ironhandAI::WaypointReached(), npc_arthasAI::WaypointReached(), npc_prospector_remtravelAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_melizza_brimbuzzleAI::WaypointReached(), npc_areiAI::WaypointReached(), npc_willix_the_importerAI::WaypointReached(), npc_kayaAI::WaypointReached(), npc_wizzlecranks_shredderAI::WaypointReached(), npc_proudhoofAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_injured_rainspeakerAI::WaypointReached(), npc_shaheenAI::WaypointReached(), npc_wounded_blood_elfAI::WaypointReached(), npc_nagrand_captiveAI::WaypointReached(), npc_bessyAI::WaypointReached(), npc_akunoAI::WaypointReached(), npc_skywingAI::WaypointReached(), npc_skyguard_prisonerAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), example_escortAI::WaypointReached(), and npc_00x09hlAI::WaypointStart().
SummonCreature() [2/2]
Creature * WorldObject::SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject = false, bool setRun = false, uint32 pathId = 0, uint32 faction = 0, uint32 modelId = 0, bool spawnCounting = false, bool forcedOnTop = false)
Definition at line 2318 of file Object.cpp.
References GetMap(), GetPhaseMask(), and SummonCreature().
Update()
void WorldObject::Update (const uint32 diff) virtual
Reimplemented in Unit, Transport, ElevatorTransport, Totem, TemporarySpawn, Player, Pet, GameObject, DynamicObject, and Creature.
Definition at line 1346 of file Object.cpp.
References ShortTimeTracker::GetExpiry(), GetHeartbeatDuration(), Heartbeat(), m_heartBeatTimer, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), and ShortTimeTracker::Update().
Referenced by GameObject::Update(), and Unit::Update().
UpdateAllowedPositionZ()
void WorldObject::UpdateAllowedPositionZ (float x, float y, float & z, Map * atMap = nullptr) const virtual
Reimplemented in Unit.
Definition at line 1805 of file Object.cpp.
References Map::GetHeight(), GetMap(), GetPhaseMask(), and INVALID_HEIGHT.
Referenced by Spell::EffectSummonType(), GetNearPointAt(), GetRandomPoint(), MovePositionToFirstCollision(), and VehicleInfo::UnBoard().
UpdateCooldowns()
void WorldObject::UpdateCooldowns (TimePoint const & now) protected
Definition at line 2784 of file Object.cpp.
References m_cooldownMap, m_GCDCatMap, m_lockoutMap, and CooldownContainer::Update().
Referenced by Unit::Update().
UpdateGroundPositionZ()
void WorldObject::UpdateGroundPositionZ (float x, float y, float & z) const
Definition at line 1798 of file Object.cpp.
References Map::GetHeight(), GetMap(), GetPhaseMask(), and INVALID_HEIGHT.
Referenced by GetNearPointAt(), and SummonCultists().
UpdateObjectVisibility()
void WorldObject::UpdateObjectVisibility ()
Definition at line 2637 of file Object.cpp.
References MaNGOS::ComputeCellPair(), GetMap(), GetPositionX(), GetPositionY(), and Map::UpdateObjectVisibility().
Referenced by Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Aura::HandleAuraFakeInebriation(), Player::KillPlayer(), Unit::OnRelocated(), Creature::RemoveCorpse(), Player::ResurrectPlayer(), WorldSession::SendSpiritResurrect(), Player::SetGameMaster(), GameObject::Update(), UpdateVisibilityAndView(), and Unit::UpdateVisibilityAndView().
UpdateVisibilityAndView()
void WorldObject::UpdateVisibilityAndView () virtual
Reimplemented in Unit.
Definition at line 2630 of file Object.cpp.
References ViewPoint::Call_UpdateVisibilityForOwner(), ViewPoint::Event_ViewPointVisibilityChanged(), GetViewPoint(), and UpdateObjectVisibility().
Referenced by SetPhaseMask().
Friends And Related Function Documentation
WorldObjectChangeAccumulator
friend struct WorldObjectChangeAccumulator friend
Definition at line 948 of file Object.h.
Field Documentation
m_castCounter
uint32 WorldObject::m_castCounter private
Definition at line 1328 of file Object.h.
Referenced by CheckAndIncreaseCastCounter(), and DecreaseCastCounter().
m_clientGUIDsIAmAt
GuidSet WorldObject::m_clientGUIDsIAmAt private
Definition at line 1324 of file Object.h.
Referenced by AddClientIAmAt(), GetClientGuidsIAmAt(), RemoveClientIAmAt(), and SendMessageToAllWhoSeeMe().
m_cooldownMap
CooldownContainer WorldObject::m_cooldownMap protected
Definition at line 1300 of file Object.h.
Referenced by Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), AddCooldown(), Creature::AddCooldown(), Player::AddCooldown(), Unit::CharmCooldownInitialize(), GetExpireTime(), HasGCDOrCooldownWithinMargin(), IsSpellOnPermanentCooldown(), IsSpellReady(), Player::ModifyCooldown(), PrintCooldownList(), Player::RemoveAllCooldowns(), RemoveAllCooldowns(), Player::RemoveSomeCooldown(), RemoveSpellCategoryCooldown(), Player::RemoveSpellCategoryCooldown(), RemoveSpellCooldown(), Player::RemoveSpellCooldown(), Player::SendInitialSpells(), and UpdateCooldowns().
m_currentCell
Cell WorldObject::m_currentCell protected
Definition at line 1305 of file Object.h.
Referenced by GetCurrentCell(), and SetCurrentCell().
m_currMap
Map* WorldObject::m_currMap private
Definition at line 1313 of file Object.h.
Referenced by AddToWorld(), GetMap(), GetTerrain(), RemoveFromWorld(), ResetMap(), and SetMap().
m_debugFlags
uint64 WorldObject::m_debugFlags private
Definition at line 1322 of file Object.h.
Referenced by ClearDebugFlag(), HaveDebugFlag(), and SetDebugFlag().
m_destLocCounter
uint8 WorldObject::m_destLocCounter private
Definition at line 1327 of file Object.h.
Referenced by GetDestLocCounter(), and IncrementDestLocCounter().
m_events
EventProcessor WorldObject::m_events
Definition at line 1265 of file Object.h.
Referenced by Unit::AbortAINotifyEvent(), CleanupsBeforeDelete(), Unit::CleanupsBeforeDelete(), SpellEvent::Execute(), GameObject::ForcedDespawn(), Creature::ForcedDespawn(), BattleGroundQueue::InviteGroupToBg(), Spell::RecalculateDelayMomentForDest(), Unit::ScheduleAINotify(), UnitAI::SendAIEventAround(), Unit::SetInCombatState(), Spell::SpellStart(), GameObject::Update(), and Unit::Update().
m_GCDCatMap
GCDMap WorldObject::m_GCDCatMap protected
Definition at line 1298 of file Object.h.
Referenced by AddGCD(), GetGCD(), HasGCD(), HasGCDOrCooldownWithinMargin(), PrintCooldownList(), RemoveAllCooldowns(), ResetGCD(), and UpdateCooldowns().
m_heartBeatTimer
ShortTimeTracker WorldObject::m_heartBeatTimer protected
Definition at line 1311 of file Object.h.
Referenced by Update().
m_InstanceId
uint32 WorldObject::m_InstanceId private
Definition at line 1316 of file Object.h.
Referenced by GetInstanceId(), SetLocationInstanceId(), and SetMap().
m_isActiveObject
bool WorldObject::m_isActiveObject private
Definition at line 1321 of file Object.h.
Referenced by isActiveObject(), and SetActiveObjectState().
m_isOnEventNotified
bool WorldObject::m_isOnEventNotified protected
Definition at line 1307 of file Object.h.
Referenced by AddToWorld(), IsNotifyOnEventObject(), RemoveFromWorld(), and SetNotifyOnEventState().
m_lockoutMap
LockoutMap WorldObject::m_lockoutMap protected
Definition at line 1299 of file Object.h.
Referenced by CheckLockout(), HasGCDOrCooldownWithinMargin(), LockOutSpells(), PrintCooldownList(), Player::RemoveAllCooldowns(), RemoveAllCooldowns(), and UpdateCooldowns().
m_mapId
uint32 WorldObject::m_mapId private
Definition at line 1315 of file Object.h.
Referenced by GetMapId(), GetPosition(), SetLocationMapId(), and SetMap().
m_movementInfo
MovementInfo WorldObject::m_movementInfo
Definition at line 1242 of file Object.h.
Referenced by GenericTransport::AddPassenger(), GenericTransport::AddPetToTransport(), VehicleInfo::Board(), WaypointMovementGenerator< Creature >::BuildIntPath(), Object::BuildMovementUpdate(), Creature::CanFly(), Player::CanFly(), Unit::DisableSpline(), Unit::FindRootVehicle(), NamreebAnticheat::Movement::GetLastMovementInfo(), GetPosition(), Unit::GetSpeedInMotion(), Unit::GetSpeedRateInMotion(), GetTransOffsetO(), GetTransOffsetX(), GetTransOffsetY(), GetTransOffsetZ(), GetTransSeat(), GetTransTime(), Unit::GetXYFlagBasedSpeed(), PlayerbotAI::HandleBotOutgoingPacket(), ChatHandler::HandleDebugMoveflags(), WorldSession::HandleMoveNotActiveMoverOpcode(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveTimeSkippedOpcode(), WorldSession::HandleMoveWorldportAckOpcode(), ChatHandler::HandleNpcInfoCommand(), WorldSession::HandlePlayerLogin(), WorldSession::HandleSetActiveMoverOpcode(), FollowMovementGenerator::HandleTargetedMovement(), Player::HasMovementFlag(), Creature::InitEntry(), VehicleInfo::Initialize(), Unit::IsFalling(), Unit::IsFlying(), Creature::IsFlying(), Unit::IsLevitating(), Unit::IsMoving(), Unit::IsMovingForward(), Unit::IsMovingIgnoreFlying(), Player::isMovingOrTurning(), Unit::IsRooted(), Creature::IsSwimming(), Player::IsSwimming(), Unit::IsWalking(), Movement::MoveSplineInit::Launch(), Player::LoadFromDB(), Creature::LoadFromDB(), GameObject::LoadFromDB(), Movement::MoveSplineInit::MoveSplineInit(), PlayerbotMgr::OnBotLogin(), Intervene::OnCast(), Relocate(), GenericTransport::RemovePassenger(), Player::SaveToDB(), Unit::SendHeartBeat(), Unit::SendMoveRoot(), Unit::SendTeleportPacket(), Unit::SetCanFly(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetLevitate(), SetOrientation(), Unit::SetStunnedByLogout(), Unit::SetSwim(), Spell::SetTargetMap(), Creature::SetWalk(), Unit::SetWaterWalk(), Movement::MoveSplineInit::Stop(), SummonCreature(), Player::TeleportTo(), Transport::TeleportTransport(), VehicleInfo::UnBoard(), Spell::update(), PlayerbotAI::UpdateAI(), Creature::UpdateEntry(), GenericTransport::UpdatePassengerPosition(), and Unit::UpdateSplinePosition().
m_name
std::string WorldObject::m_name protected
Definition at line 1302 of file Object.h.
Referenced by Player::_LoadGlyphs(), Player::Create(), GetName(), GetNameStr(), Player::LoadFromDB(), Pet::Pet(), Pet::SavePetToDB(), Player::SaveToDB(), and SetName().
m_phaseMask
uint32 WorldObject::m_phaseMask private
Definition at line 1317 of file Object.h.
Referenced by _Create(), GetPhaseMask(), and SetPhaseMask().
m_position
Position WorldObject::m_position private
Definition at line 1319 of file Object.h.
Referenced by GetAngle(), GetAreaId(), GetAreaName(), GetOrientation(), GetPosition(), GetPositionX(), GetPositionY(), GetPositionZ(), GetZoneAndAreaId(), GetZoneId(), IsPositionValid(), MovePositionToFirstCollision(), Relocate(), and SetOrientation().
m_stringIds
std::set<uint32> WorldObject::m_stringIds private
Definition at line 1330 of file Object.h.
Referenced by AddToWorld(), HasStringId(), RemoveFromWorld(), and SetStringId().
m_transport
GenericTransport* WorldObject::m_transport
Definition at line 1243 of file Object.h.
Referenced by GetTransport(), Player::LoadFromDB(), Player::SaveToDB(), SetTransport(), Player::TeleportTo(), and Player::~Player().
m_transportInfo
TransportInfo* WorldObject::m_transportInfo protected
Definition at line 1304 of file Object.h.
Referenced by GetTransportInfo(), IsBoarded(), and SetTransportInfo().
m_viewPoint
ViewPoint WorldObject::m_viewPoint private
Definition at line 1320 of file Object.h.
Referenced by GetViewPoint(), and isActiveObject().
m_visibilityData
VisibilityData WorldObject::m_visibilityData protected
Definition at line 1309 of file Object.h.
Referenced by GetVisibilityData().
The documentation for this class was generated from the following files:
Object.h
Object.cpp
Relations.cpp