CMaNGOS_WoTLK: ChatHandler Class Reference
ChatHandler Class Reference
#include <Chat.h>
Data Structures
struct DeletedInfo
Stores informations about a deleted character.
Public Member Functions
ChatHandler (WorldSession *session)
ChatHandler (Player *player)
virtual ~ChatHandler ()
virtual const char * GetMangosString (int32 entry) const
const char * GetOnOffStr (bool value) const
virtual void SendSysMessage (const char *str)
void SendSysMessage (int32 entry)
void PSendSysMessage (const char *format,...) ATTR_PRINTF(2
void void PSendSysMessage (int32 entry,...)
bool ParseCommands (const char *text)
ChatCommand const * FindCommand (char const *text)
Search (sub)command for command line available for chat handler access level.
bool HasSentErrorMessage () const
bool ExtractInt32 (char **args, int32 &val) const
Function extract to val arg signed integer value or fail.
bool ExtractOptInt32 (char **args, int32 &val, int32 defVal) const
Function extract to val arg optional signed integer value or use default value.
bool ExtractUInt32Base (char **args, uint32 &val, uint32 base) const
Function extract to val arg unsigned integer value or fail.
bool ExtractUInt32 (char **args, uint32 &val) const
bool ExtractOptUInt32 (char **args, uint32 &val, uint32 defVal) const
Function extract to val arg optional unsigned integer value or use default value.
char * ExtractKeyFromLink (char **text, char const *linkType, char **something1=nullptr)
Function extract data from shift-link "|color|LINKTYPE:RETURN:SOMETHING1|h[name]|h|r if linkType == LINKTYPE It also extract literal/quote if not shift-link in args.
bool ExtractUint32KeyFromLink (char **text, char const *linkType, uint32 &value)
Function extract uint32 key from shift-link "|color|LINKTYPE:RETURN|h[name]|h|r if linkType == LINKTYPE It also extract direct number if not shift-link in args.
uint32 ExtractAccountId (char **args, std::string *accountName=nullptr, Player **targetIfNullArg=nullptr)
uint32 ExtractSpellIdFromLink (char **text)
ObjectGuid ExtractGuidFromLink (char **text)
GameTele const * ExtractGameTeleFromLink (char **text)
bool ExtractLocationFromLink (char **text, uint32 &mapid, float &x, float &y, float &z)
bool ExtractRaceMask (char **text, uint32 &raceMask, char const **maskName=nullptr)
std::string ExtractPlayerNameFromLink (char **text)
bool ExtractPlayerTarget (char **args, Player **player, ObjectGuid *player_guid=nullptr, std::string *player_name=nullptr)
Function extract at least one from request player data (pointer/guid/name) from args name/shift-link or selected player if no args.
WorldSession * GetSession () const
Static Public Member Functions
static char * LineFromMessage (char *&pos)
static bool HasEscapeSequences (const char *message)
static bool CheckEscapeSequences (const char *message)
static void BuildChatPacket (WorldPacket &data, ChatMsg msgtype, char const *message, Language language=LANG_UNIVERSAL, ChatTagFlags chatTag=CHAT_TAG_NONE, ObjectGuid const &senderGuid=ObjectGuid(), char const *senderName=nullptr, ObjectGuid const &targetGuid=ObjectGuid(), char const *targetName=nullptr, char const *channelName=nullptr, uint32 achievementId=0)
Prepare SMSG_GM_MESSAGECHAT/SMSG_MESSAGECHAT.
static void SkipWhiteSpaces (char **args)
Function skip all whitespaces in args string.
static bool ExtractFloat (char **args, float &val)
Function extract to val arg float value or fail.
static bool ExtractOptFloat (char **args, float &val, float defVal)
Function extract to val arg optional float value or use default value.
static char * ExtractQuotedArg (char **args, bool asis=false)
Function extract quote-like string (any characters guarded by some special character, in our cases ['")
static char * ExtractLiteralArg (char **args, char const *lit=nullptr)
Function extract name-like string (from non-numeric or special symbol until whitespace)
static char * ExtractQuotedOrLiteralArg (char **args, bool asis=false)
Function extract quote-like string or literal if quote not detected.
static bool ExtractOnOff (char **args, bool &value)
Function extract on/off literals as boolean values.
static char * ExtractLinkArg (char **args, char const *const *linkTypes=nullptr, int *foundIdx=nullptr, char **keyPair=nullptr, char **somethingPair=nullptr)
Function extract shift-link-like string (any characters guarded by | and |h|r with some additional internal structure check)
static char * ExtractArg (char **args, bool asis=false)
Function extract name/number/quote/shift-link-like string.
static char * ExtractOptNotLastArg (char **args)
Function extract name/quote/number/shift-link-like string, and return it if args have more non-whitespace data.
static char * ExtractKeyFromLink (char **text, char const *const *linkTypes, int *found_idx=nullptr, char **something1=nullptr)
Function extract data from shift-link "|color|LINKTYPE:RETURN:SOMETHING1|h[name]|h|r if LINKTYPE in linkTypes array It also extract literal/quote if not shift-link in args.
Protected Types
typedef std::list< DeletedInfo > DeletedInfoList
Protected Member Functions
ChatHandler ()
bool hasStringAbbr (const char *name, const char *part) const
virtual uint32 GetAccountId () const
virtual AccountTypes GetAccessLevel () const
virtual bool isAvailable (ChatCommand const &cmd) const
virtual std::string GetNameLink () const
virtual bool needReportToTarget (Player *chr) const
virtual LocaleConstant GetSessionDbcLocale () const
virtual int GetSessionDbLocaleIndex () const
bool HasLowerSecurity (Player *target, ObjectGuid guid=ObjectGuid(), bool strong=false)
bool HasLowerSecurityAccount (WorldSession *target, uint32 target_account, bool strong=false)
void SendGlobalSysMessage (const char *str) const
bool SetDataForCommandInTable (ChatCommand *commandTable, const char *text, uint32 security, std::string const &help)
Function find appropriate command and update command security level and help text.
void ExecuteCommand (const char *text)
Execute (sub)command available for chat handler access level with options in command line string.
void LogCommand (char const *fullcmd) const
bool ShowHelpForCommand (ChatCommand *table, const char *cmd)
bool ShowHelpForSubCommands (ChatCommand *table, char const *cmd)
ChatCommandSearchResult FindCommand (ChatCommand *table, char const *&text, ChatCommand *&command, ChatCommand **parentCommand=nullptr, std::string *cmdNamePtr=nullptr, bool allAvailable=false, bool exactlyName=false) const
Search (sub)command for command line available for chat handler access level with options and fail case additional info.
void CheckIntegrity (ChatCommand *table, ChatCommand *parentCommand) const
ChatCommand * getCommandTable ()
bool HandleAccountCommand (char *args)
bool HandleAccountCharactersCommand (char *args)
Output list of character for account.
bool HandleAccountCreateCommand (char *args)
Create an account.
bool HandleAccountDeleteCommand (char *args)
Delete a user account and all associated characters in this realm.
bool HandleAccountLockCommand (char *args)
bool HandleAccountOnlineListCommand (char *args)
Display info on users currently in the realm.
bool HandleAccountPasswordCommand (char *args)
bool HandleAccountSetAddonCommand (char *args)
Set/Unset the expansion level for an account.
bool HandleAccountSetGmLevelCommand (char *args)
bool HandleAccountSetPasswordCommand (char *args)
Set password for account.
bool HandleAuctionAllianceCommand (char *args)
bool HandleAuctionGoblinCommand (char *args)
bool HandleAuctionHordeCommand (char *args)
bool HandleAuctionItemCommand (char *args)
bool HandleAuctionCommand (char *args)
bool HandleAchievementCommand (char *args)
bool HandleAchievementAddCommand (char *args)
bool HandleAchievementRemoveCommand (char *args)
bool HandleAchievementCriteriaAddCommand (char *args)
bool HandleAchievementCriteriaRemoveCommand (char *args)
bool HandleWarnCharacterCommand (char *args)
bool HandleAddCharacterNoteCommand (char *args)
bool HandleBanAccountCommand (char *args)
bool HandleBanCharacterCommand (char *args)
bool HandleBanIPCommand (char *args)
bool HandleBanInfoAccountCommand (char *args)
bool HandleBanInfoCharacterCommand (char *args)
bool HandleBanInfoIPCommand (char *args)
bool HandleBanListAccountCommand (char *args)
bool HandleBanListCharacterCommand (char *args)
bool HandleBanListIPCommand (char *args)
bool HandleCastCommand (char *args)
bool HandleCastBackCommand (char *args)
bool HandleCastDistCommand (char *args)
bool HandleCastSelfCommand (char *args)
bool HandleCastTargetCommand (char *args)
bool HandleCharacterAchievementsCommand (char *args)
bool HandleCharacterCustomizeCommand (char *args)
bool HandleCharacterDeletedDeleteCommand (char *args)
Handles the '.character deleted delete' command, which completely deletes all deleted characters which matches the given search string.
bool HandleCharacterDeletedListCommand (char *args)
Handles the '.character deleted list' command, which shows all deleted characters which matches the given search string.
bool HandleCharacterDeletedRestoreCommand (char *args)
Handles the '.character deleted restore' command, which restores all deleted characters which matches the given search string.
bool HandleCharacterDeletedOldCommand (char *args)
Handles the '.character deleted old' command, which completely deletes all deleted characters deleted with some days ago.
bool HandleCharacterEraseCommand (char *args)
bool HandleCharacterLevelCommand (char *args)
bool HandleCharacterRenameCommand (char *args)
bool HandleCharacterReputationCommand (char *args)
bool HandleCharacterTitlesCommand (char *args)
bool HandleChannelListCommand (char *args)
bool HandleChannelStaticCommand (char *args)
bool HandleDebugAnimCommand (char *args)
bool HandleDebugArenaCommand (char *args)
bool HandleDebugBattlegroundCommand (char *args)
bool HandleDebugBattlegroundStartCommand (char *args)
bool HandleDebugListUpdateFieldsCommand (char *args)
bool HandleDebugGetItemStateCommand (char *args)
bool HandleDebugGetItemValueCommand (char *args)
bool HandleDebugGetLootRecipientCommand (char *args)
bool HandleDebugGetValueByIndexCommand (char *args)
bool HandleDebugGetValueByNameCommand (char *args)
bool HandleDebugModItemValueCommand (char *args)
bool HandleDebugModValueCommand (char *args)
bool HandleDebugSetAuraStateCommand (char *args)
bool HandleDebugSetItemValueCommand (char *args)
bool HandleDebugSetValueByIndexCommand (char *args)
bool HandleDebugSetValueByNameCommand (char *args)
bool HandleDebugSpellCheckCommand (char *args)
bool HandleDebugSpellCoefsCommand (char *args)
bool HandleDebugSpellModsCommand (char *args)
bool HandleDebugTaxiCommand (char *)
bool HandleDebugUpdateWorldStateCommand (char *args)
bool HandleDebugWaypoint (char *args)
bool HandleDebugByteFields (char *args)
bool HandleDebugSpellVisual (char *args)
bool HandleDebugMoveflags (char *args)
bool HandleDebugLootDropStats (char *args)
bool HandleDebugOverflowCommand (char *args)
bool HandleDebugChatFreezeCommand (char *args)
bool HandleDebugLfgCommand (char *args)
bool HandleDebugObjectFlags (char *args)
bool HandleDebugHaveAtClientCommand (char *args)
bool HandleDebugIsVisibleCommand (char *args)
bool HandleShowTemporarySpawnList (char *args)
bool HandleGridsLoadedCount (char *args)
bool HandleDebugPlayCinematicCommand (char *args)
bool HandleDebugPlayMovieCommand (char *args)
bool HandleDebugPlaySoundCommand (char *args)
bool HandleDebugPlayMusicCommand (char *args)
bool HandleDebugPetDismissSound (char *args)
bool HandleDebugAreaTriggersCommand (char *args)
bool HandleDebugSendBuyErrorCommand (char *args)
bool HandleDebugSendChannelNotifyCommand (char *args)
bool HandleDebugSendChatMsgCommand (char *args)
bool HandleDebugSendEquipErrorCommand (char *args)
bool HandleDebugSendLargePacketCommand (char *args)
bool HandleDebugSendOpcodeCommand (char *args)
bool HandleDebugSendPoiCommand (char *args)
bool HandleDebugSendQuestFailedMsgCommand (char *args)
bool HandleDebugSendQuestPartyMsgCommand (char *args)
bool HandleDebugSendQuestInvalidMsgCommand (char *args)
bool HandleDebugSendSellErrorCommand (char *args)
bool HandleDebugSendSetPhaseShiftCommand (char *args)
bool HandleDebugSendSpellFailCommand (char *args)
bool HandleDebugSendWorldState (char *args)
bool HandleDebugOutPacketHistory (char *args)
bool HandleDebugIncPacketHistory (char *args)
bool HandleDebugTransports (char *args)
bool HandleDebugSpawnsList (char *args)
bool HandleDebugRespawnDynguid (char *args)
bool HandleDebugPacketLog (char *args)
bool HandleDebugDbscript (char *args)
bool HandleDebugDbscriptTargeted (char *args)
bool HandleDebugDbscriptSourced (char *args)
bool HandleDebugDbscriptGuided (char *args)
bool HandleSD2HelpCommand (char *args)
bool HandleSD2ScriptCommand (char *args)
bool HandleEventListCommand (char *args)
bool HandleEventStartCommand (char *args)
bool HandleEventStopCommand (char *args)
bool HandleEventInfoCommand (char *args)
bool HandleGameObjectAddCommand (char *args)
bool HandleGameObjectDeleteCommand (char *args)
bool HandleGameObjectMoveCommand (char *args)
bool HandleGameObjectNearCommand (char *args)
bool HandleGameObjectNearSpawnedCommand (char *args)
bool HandleGameObjectPhaseCommand (char *args)
bool HandleGameObjectTargetCommand (char *args)
bool HandleGameObjectTurnCommand (char *args)
bool HandleGameObjectActivateCommand (char *args)
bool HandleGameObjectForcedDespawnCommand (char *args)
bool HandleGameObjectRespawnCommand (char *args)
bool HandleGMCommand (char *args)
bool HandleGMChatCommand (char *args)
bool HandleGMFlyCommand (char *args)
bool HandleGMListFullCommand (char *args)
Display the list of GMs.
bool HandleGMListIngameCommand (char *args)
bool HandleGMMountUpCommand (char *args)
bool HandleGMVisibleCommand (char *args)
bool HandleGoCommand (char *args)
bool HandleGoCreatureCommand (char *args)
Teleport the GM to the specified creature.
bool HandleGoGraveyardCommand (char *args)
bool HandleGoGridCommand (char *args)
bool HandleGoObjectCommand (char *args)
bool HandleGoTaxinodeCommand (char *args)
bool HandleGoTriggerCommand (char *args)
bool HandleGoWarpCommand (char *args)
bool HandleGoXYCommand (char *args)
bool HandleGoXYZCommand (char *args)
bool HandleGoZoneXYCommand (char *args)
bool HandleGuildCreateCommand (char *args)
GM command level 3 - Create a guild.
bool HandleGuildInviteCommand (char *args)
bool HandleGuildUninviteCommand (char *args)
bool HandleGuildRankCommand (char *args)
bool HandleGuildDeleteCommand (char *args)
bool HandleHonorAddCommand (char *args)
bool HandleHonorAddKillCommand (char *args)
bool HandleHonorUpdateCommand (char *args)
bool HandleInstanceListBindsCommand (char *args)
bool HandleInstanceUnbindCommand (char *args)
bool HandleInstanceStatsCommand (char *args)
bool HandleInstanceSaveDataCommand (char *args)
bool HandleLearnCommand (char *args)
bool HandleLearnAllCommand (char *args)
bool HandleLearnAllGMCommand (char *args)
bool HandleLearnAllCraftsCommand (char *args)
bool HandleLearnAllRecipesCommand (char *args)
bool HandleLearnAllDefaultCommand (char *args)
bool HandleLearnAllLangCommand (char *args)
bool HandleLearnAllMyClassCommand (char *args)
bool HandleLearnAllMyPetTalentsCommand (char *args)
bool HandleLearnAllMySpellsCommand (char *args)
bool HandleLearnAllMyTalentsCommand (char *args)
bool HandleListAreaTriggerCommand (char *args)
bool HandleListAurasCommand (char *args)
bool HandleListCreatureCommand (char *args)
bool HandleListItemCommand (char *args)
bool HandleListObjectCommand (char *args)
bool HandleListTalentsCommand (char *args)
bool HandleLookupAccountEmailCommand (char *args)
bool HandleLookupAccountIpCommand (char *args)
bool HandleLookupAccountNameCommand (char *args)
bool HandleLookupAchievementCommand (char *args)
bool HandleLookupAreaCommand (char *args)
bool HandleLookupCreatureCommand (char *args)
bool HandleLookupEventCommand (char *args)
bool HandleLookupFactionCommand (char *args)
bool HandleLookupItemCommand (char *args)
bool HandleLookupItemSetCommand (char *args)
bool HandleLookupObjectCommand (char *args)
bool HandleLookupPlayerIpCommand (char *args)
bool HandleLookupPlayerAccountCommand (char *args)
bool HandleLookupPlayerEmailCommand (char *args)
bool HandleLookupPoolCommand (char *args)
bool HandleLookupQuestCommand (char *args)
bool HandleLookupSkillCommand (char *args)
bool HandleLookupSpellCommand (char *args)
bool HandleLookupTaxiNodeCommand (char *args)
bool HandleLookupTeleCommand (char *args)
bool HandleLookupTitleCommand (char *args)
bool HandleModifyHPCommand (char *args)
bool HandleModifyManaCommand (char *args)
bool HandleModifyRageCommand (char *args)
bool HandleModifyRunicPowerCommand (char *args)
bool HandleModifyEnergyCommand (char *args)
bool HandleModifyMoneyCommand (char *args)
bool HandleModifyASpeedCommand (char *args)
bool HandleModifySpeedCommand (char *args)
bool HandleModifyBWalkCommand (char *args)
bool HandleModifyFlyCommand (char *args)
bool HandleModifySwimCommand (char *args)
bool HandleModifyScaleCommand (char *args)
bool HandleModifyMountCommand (char *args)
bool HandleModifyFactionCommand (char *args)
bool HandleModifyTalentCommand (char *args)
bool HandleModifyHonorCommand (char *args)
bool HandleModifyRepCommand (char *args)
bool HandleModifyArenaCommand (char *args)
bool HandleModifyPhaseCommand (char *args)
bool HandleModifyGenderCommand (char *args)
bool HandleModifyStrengthCommand (char *args)
bool HandleModifyAgilityCommand (char *args)
bool HandleModifyStaminaCommand (char *args)
bool HandleModifyIntellectCommand (char *args)
bool HandleModifySpiritCommand (char *args)
bool HandleModifyArmorCommand (char *args)
bool HandleModifyHolyCommand (char *args)
bool HandleModifyFireCommand (char *args)
bool HandleModifyNatureCommand (char *args)
bool HandleModifyFrostCommand (char *args)
bool HandleModifyShadowCommand (char *args)
bool HandleModifyArcaneCommand (char *args)
bool HandleModifyMeleeApCommand (char *args)
bool HandleModifyRangedApCommand (char *args)
bool HandleModifySpellPowerCommand (char *args)
bool HandleModifyMeleeCritCommand (char *args)
bool HandleModifySpellCritCommand (char *args)
bool HandleModifyMeleeHasteCommand (char *args)
bool HandleModifyRangedHasteCommand (char *args)
bool HandleModifySpellHasteCommand (char *args)
bool HandleModifyBlockCommand (char *args)
bool HandleModifyDodgeCommand (char *args)
bool HandleModifyParryCommand (char *args)
bool ModifyMountCommandHelper (Player *target, char *args)
bool ModifyStatCommandHelper (char *args, char const *statName, uint32 spellId)
bool HandleNpcAddCommand (char *args)
bool HandleNpcAddVendorItemCommand (char *args)
bool HandleNpcAIInfoCommand (char *args)
bool HandleNpcAllowMovementCommand (char *args)
bool HandleNpcChangeEntryCommand (char *args)
bool HandleNpcChangeLevelCommand (char *args)
bool HandleNpcDeleteCommand (char *args)
bool HandleNpcDelVendorItemCommand (char *args)
bool HandleNpcFactionIdCommand (char *args)
bool HandleNpcFlagCommand (char *args)
bool HandleNpcFollowCommand (char *args)
bool HandleNpcInfoCommand (char *args)
bool HandleNpcThreatCommand (char *args)
bool HandleNpcMoveCommand (char *args)
bool HandleNpcPlayEmoteCommand (char *args)
bool HandleNpcSayCommand (char *args)
bool HandleNpcListSpells (char *args)
bool HandleNpcShowLootCommand (char *args)
bool HandleNpcSetModelCommand (char *args)
bool HandleNpcSetMoveTypeCommand (char *args)
HandleNpcSetMoveTypeCommand Set the movement type for an NPC.
bool HandleNpcSetPhaseCommand (char *args)
bool HandleNpcSpawnDistCommand (char *args)
bool HandleNpcSpawnTimeCommand (char *args)
bool HandleNpcTameCommand (char *args)
bool HandleNpcTextEmoteCommand (char *args)
bool HandleNpcUnFollowCommand (char *args)
bool HandleNpcWhisperCommand (char *args)
bool HandleNpcYellCommand (char *args)
bool HandleNpcTempSpawn (char *args)
bool HandleNpcEvade (char *args)
bool HandleNpcGroupInfoCommand (char *args)
bool HandleNpcFormationInfoCommand (char *args)
bool HandleNpcFormationResetCommand (char *args)
bool HandleNpcFormationSwitchCommand (char *args)
bool HandleNpcAddWeaponCommand (char *args)
bool HandleNpcNameCommand (char *args)
bool HandleNpcSubNameCommand (char *args)
bool HandlePDumpLoadCommand (char *args)
bool HandlePDumpWriteCommand (char *args)
bool HandlePoolListCommand (char *args)
bool HandlePoolSpawnsCommand (char *args)
bool HandlePoolInfoCommand (char *args)
bool HandleQuestAddCommand (char *args)
bool HandleQuestRemoveCommand (char *args)
bool HandleQuestCompleteCommand (char *args)
bool HandleReloadAnticheatCommand (char *)
bool HandleReloadAllCommand (char *args)
bool HandleReloadAllAchievementCommand (char *args)
bool HandleReloadAllAreaCommand (char *args)
bool HandleReloadAllGossipsCommand (char *args)
bool HandleReloadAllItemCommand (char *args)
bool HandleReloadAllLootCommand (char *args)
bool HandleReloadAllNpcCommand (char *args)
bool HandleReloadAllQuestCommand (char *args)
bool HandleReloadAllScriptsCommand (char *args)
bool HandleReloadAllEventAICommand (char *args)
bool HandleReloadAllSpellCommand (char *args)
bool HandleReloadAllLocalesCommand (char *args)
bool HandleReloadConfigCommand (char *args)
bool HandleReloadAchievementCriteriaRequirementCommand (char *args)
bool HandleReloadAchievementRewardCommand (char *args)
bool HandleReloadAreaTriggerTavernCommand (char *args)
bool HandleReloadAreaTriggerTeleportCommand (char *args)
bool HandleReloadBattleEventCommand (char *args)
bool HandleReloadCreaturesStatsCommand (char *args)
bool HandleReloadCommandCommand (char *args)
bool HandleReloadConditionsCommand (char *args)
bool HandleReloadCreatureQuestRelationsCommand (char *args)
bool HandleReloadCreatureQuestInvRelationsCommand (char *args)
bool HandleReloadDBScriptsOnCreatureDeathCommand (char *args)
bool HandleReloadDBScriptsOnEventCommand (char *args)
bool HandleReloadDBScriptsOnGossipCommand (char *args)
bool HandleReloadDBScriptsOnGoUseCommand (char *args)
bool HandleReloadDBScriptsOnQuestEndCommand (char *args)
bool HandleReloadDBScriptsOnQuestStartCommand (char *args)
bool HandleReloadDBScriptsOnSpellCommand (char *args)
bool HandleReloadDBScriptsOnRelayCommand (char *args)
bool HandleReloadEventAISummonsCommand (char *args)
bool HandleReloadEventAIScriptsCommand (char *args)
bool HandleReloadGameGraveyardZoneCommand (char *args)
bool HandleReloadGameTeleCommand (char *args)
bool HandleReloadGossipMenuCommand (char *args)
bool HandleReloadQuestgiverGreetingCommand (char *args)
bool HandleReloadTrainerGreetingCommand (char *args)
bool HandleReloadGOQuestRelationsCommand (char *args)
bool HandleReloadGOQuestInvRelationsCommand (char *args)
bool HandleReloadItemConvertCommand (char *args)
bool HandleReloadItemEnchantementsCommand (char *args)
bool HandleReloadItemRequiredTragetCommand (char *args)
bool HandleReloadLocalesAchievementRewardCommand (char *args)
bool HandleReloadLocalesCreatureCommand (char *args)
bool HandleReloadLocalesGameobjectCommand (char *args)
bool HandleReloadLocalesGossipMenuOptionCommand (char *args)
bool HandleReloadLocalesItemCommand (char *args)
bool HandleReloadLocalesNpcTextCommand (char *args)
bool HandleReloadLocalesPageTextCommand (char *args)
bool HandleReloadLocalesPointsOfInterestCommand (char *args)
bool HandleReloadLocalesQuestCommand (char *args)
bool HandleReloadQuestgiverGreetingLocalesCommand (char *args)
bool HandleReloadLocalesTrainerGreetingCommand (char *args)
bool HandleReloadLootTemplatesCreatureCommand (char *args)
bool HandleReloadLootTemplatesDisenchantCommand (char *args)
bool HandleReloadLootTemplatesFishingCommand (char *args)
bool HandleReloadLootTemplatesGameobjectCommand (char *args)
bool HandleReloadLootTemplatesItemCommand (char *args)
bool HandleReloadLootTemplatesMailCommand (char *args)
bool HandleReloadLootTemplatesMillingCommand (char *args)
bool HandleReloadLootTemplatesPickpocketingCommand (char *args)
bool HandleReloadLootTemplatesProspectingCommand (char *args)
bool HandleReloadLootTemplatesReferenceCommand (char *args)
bool HandleReloadLootTemplatesSkinningCommand (char *args)
bool HandleReloadLootTemplatesSpellCommand (char *args)
bool HandleReloadMailLevelRewardCommand (char *args)
bool HandleReloadMangosStringCommand (char *args)
bool HandleReloadNpcGossipCommand (char *args)
bool HandleReloadNpcTextCommand (char *args)
bool HandleReloadNpcTrainerCommand (char *args)
bool HandleReloadNpcVendorCommand (char *args)
bool HandleReloadPageTextsCommand (char *args)
bool HandleReloadPointsOfInterestCommand (char *args)
bool HandleReloadSpellClickSpellsCommand (char *args)
bool HandleReloadQuestAreaTriggersCommand (char *args)
bool HandleReloadQuestPOICommand (char *args)
bool HandleReloadQuestTemplateCommand (char *args)
bool HandleReloadReservedNameCommand (char *args)
bool HandleReloadReputationRewardRateCommand (char *args)
bool HandleReloadReputationSpilloverTemplateCommand (char *args)
bool HandleReloadSkillDiscoveryTemplateCommand (char *args)
bool HandleReloadSkillExtraItemTemplateCommand (char *args)
bool HandleReloadSkillFishingBaseLevelCommand (char *args)
bool HandleReloadSpellAreaCommand (char *args)
bool HandleReloadSpellChainCommand (char *args)
bool HandleReloadSpellElixirCommand (char *args)
bool HandleReloadSpellLearnSpellCommand (char *args)
bool HandleReloadSpellProcEventCommand (char *args)
bool HandleReloadSpellProcItemEnchantCommand (char *args)
bool HandleReloadSpellBonusesCommand (char *args)
bool HandleReloadSpellScriptTargetCommand (char *args)
bool HandleReloadSpellTargetPositionCommand (char *args)
bool HandleReloadSpellThreatsCommand (char *args)
bool HandleReloadStringIds (char *args)
bool HandleReloadTaxiShortcuts (char *args)
bool HandleReloadSpellPetAurasCommand (char *args)
bool HandleReloadExpectedSpamRecords (char *args)
bool HandleReloadCreatureCooldownsCommand (char *args)
bool HandleReloadCreatureSpellLists (char *args)
bool HandleReloadSpawnGroupsCommand (char *args)
bool HandleResetAchievementsCommand (char *args)
bool HandleResetAllCommand (char *args)
bool HandleResetHonorCommand (char *args)
bool HandleResetLevelCommand (char *args)
bool HandleResetSpecsCommand (char *args)
bool HandleResetSpellsCommand (char *args)
bool HandleResetStatsCommand (char *args)
bool HandleResetTalentsCommand (char *args)
bool HandleResetTaxiNodesCommand (char *args)
bool HandleResetModsCommand (char *args)
bool HandleSendItemsCommand (char *args)
bool HandleSendMailCommand (char *args)
bool HandleSendMessageCommand (char *args)
Send a message to a player in game.
bool HandleSendMoneyCommand (char *args)
bool HandleSendMassItemsCommand (char *args)
bool HandleSendMassMailCommand (char *args)
bool HandleSendMassMoneyCommand (char *args)
bool HandleServerCorpsesCommand (char *args)
Triggering corpses expire check in world.
bool HandleServerExitCommand (char *args)
Exit the realm.
bool HandleServerIdleRestartCommand (char *args)
bool HandleServerIdleShutDownCommand (char *args)
bool HandleServerInfoCommand (char *args)
bool HandleServerLogFilterCommand (char *args)
Set the filters of logging.
bool HandleServerLogLevelCommand (char *args)
Set the level of logging.
bool HandleServerMotdCommand (char *args)
Display the 'Message of the day' for the realm.
bool HandleServerPLimitCommand (char *args)
bool HandleServerResetAllRaidCommand (char *args)
bool HandleServerRestartCommand (char *args)
bool HandleServerSetMotdCommand (char *args)
Define the 'Message of the day' for the realm.
bool HandleServerShutDownCommand (char *args)
bool HandleServerShutDownCancelCommand (char *args)
bool HandleTeleCommand (char *args)
bool HandleTeleAddCommand (char *args)
bool HandleTeleDelCommand (char *args)
bool HandleTeleGroupCommand (char *args)
bool HandleTeleNameCommand (char *args)
bool HandleTitlesAddCommand (char *args)
bool HandleTitlesCurrentCommand (char *args)
bool HandleTitlesRemoveCommand (char *args)
bool HandleTitlesSetMaskCommand (char *args)
bool HandleTitlesSwapCommand (char *args)
bool HandleTriggerActiveCommand (char *args)
bool HandleTriggerNearCommand (char *args)
bool HandleTriggerCommand (char *args)
bool HandleUnBanAccountCommand (char *args)
bool HandleUnBanCharacterCommand (char *args)
bool HandleUnBanIPCommand (char *args)
bool HandleWpAddCommand (char *args)
Add a waypoint to a creature .wp add [dbGuid] [pathId] [source].
bool HandleWpModifyCommand (char *args)
.wp modify waittime | scriptid | orientation | del | move [dbGuid, id] [value]
bool HandleWpShowCommand (char *args)
.wp show info | on | off | first | last [dbGuid] [pathId [wpOrigin] ]
bool HandleWpExportCommand (char *args)
[Guid if no selected unit] <filename> [pathId [wpOrigin] ]
bool HandleHelpCommand (char *args)
bool HandleCommandsCommand (char *args)
bool HandleStartCommand (char *args)
bool HandleDismountCommand (char *args)
bool HandleSaveCommand (char *args)
bool HandleNamegoCommand (char *args)
bool HandleGonameCommand (char *args)
bool HandleGroupgoCommand (char *args)
bool HandleRecallCommand (char *args)
bool HandleAnnounceCommand (char *args)
bool HandleNotifyCommand (char *args)
bool HandleGPSCommand (char *args)
bool HandleTaxiCheatCommand (char *args)
bool HandleWhispersCommand (char *args)
bool HandleWhisperRestrictionCommand (char *args)
bool HandleModifyDrunkCommand (char *args)
bool HandleSetViewCommand (char *args)
bool HandleLoadScriptsCommand (char *args)
bool HandleGUIDCommand (char *args)
bool HandleItemMoveCommand (char *args)
bool HandleDeMorphCommand (char *args)
bool HandlePInfoCommand (char *args)
bool HandleMuteCommand (char *args)
bool HandleUnmuteCommand (char *args)
bool HandleMovegensCommand (char *args)
bool HandleComeToMeCommand (char *args)
bool HandleMovespeedShowCommand (char *args)
bool HandleDebugMovement (char *args)
bool HandlePrintMovement (char *args)
bool HandleCooldownListCommand (char *args)
bool HandleCooldownClearCommand (char *args)
bool HandleCooldownClearClientSideCommand (char *args)
bool HandleCooldownClearArenaCommand (char *args)
bool HandleUnLearnCommand (char *args)
bool HandleGetDistanceCommand (char *args)
bool HandleGetLosCommand (char *args)
bool HandleModifyStandStateCommand (char *args)
bool HandleDieCommand (char *args)
bool HandleDamageCommand (char *args)
bool HandleReviveCommand (char *args)
bool HandleModifyMorphCommand (char *args)
bool HandleAuraCommand (char *args)
bool HandleUnAuraCommand (char *args)
bool HandleLinkGraveCommand (char *args)
bool HandleNearGraveCommand (char *args)
bool HandleExploreCheatCommand (char *args)
bool HandleLevelUpCommand (char *args)
bool HandleShowAreaCommand (char *args)
bool HandleHideAreaCommand (char *args)
bool HandleAddItemCommand (char *args)
bool HandleAddItemSetCommand (char *args)
bool HandleBankCommand (char *args)
bool HandleChangeWeatherCommand (char *args)
bool HandleKickPlayerCommand (char *args)
bool HandleMailBoxCommand (char *args)
bool HandleBagsCommand (char *args)
bool HandleCombatListCommand (char *args)
bool HandleCombatStopCommand (char *args)
bool HandleTicketDiscardCommand (char *args)
bool HandleTicketEscalateCommand (char *args)
bool HandleTicketGoCommand (char *args)
bool HandleTicketGoNameCommand (char *args)
bool HandleTicketNoteCommand (char *args)
bool HandleTicketReadCommand (char *args)
bool HandleTicketResolveCommand (char *args)
bool HandleTicketSortCommand (char *args)
bool HandleTicketWhisperCommand (char *args)
bool HandleTicketCommand (char *args)
bool HandleTicketsListCommand (char *args)
bool HandleTicketsQueueCommand (char *args)
bool HandleTicketsCommand (char *args)
bool HandleMaxSkillCommand (char *args)
bool HandleSetSkillCommand (char *args)
bool HandleRespawnCommand (char *args)
bool HandleRepairitemsCommand (char *args)
bool HandleStableCommand (char *args)
bool HandleWaterwalkCommand (char *args)
bool HandleQuitCommand (char *args)
Close RA connection.
bool HandleShowGearScoreCommand (char *args)
bool HandleArenaFlushPointsCommand (char *args)
bool HandleArenaSeasonRewardsCommand (char *args)
bool HandleArenaDataReset (char *args)
bool HandleArenaTeamPointSet (char *args)
bool HandleMmapPathCommand (char *args)
bool HandleMmapLocCommand (char *args)
bool HandleMmapLoadedTilesCommand (char *args)
bool HandleMmapStatsCommand (char *args)
bool HandleMmap (char *args)
bool HandleMmapTestArea (char *args)
bool HandleMmapTestHeight (char *args)
bool HandleLinkAddCommand (char *args)
bool HandleLinkRemoveCommand (char *args)
bool HandleLinkEditCommand (char *args)
bool HandleLinkToggleCommand (char *args)
bool HandleLinkCheckCommand (char *args)
bool HandleVariablePrint (char *args)
bool HandleWarEffortCommand (char *args)
bool HandleWarEffortPhaseCommand (char *args)
bool HandleWarEffortCounterCommand (char *args)
bool HandleScourgeInvasionCommand (char *args)
bool HandleScourgeInvasionStateCommand (char *args)
bool HandleScourgeInvasionBattlesWonCommand (char *args)
bool HandleScourgeInvasionStartZone (char *args)
bool HandleSunsReachReclamationPhaseCommand (char *args)
bool HandleSunsReachReclamationSubPhaseCommand (char *args)
bool HandleSunsReachReclamationCounterCommand (char *args)
bool HandleSunwellGateCommand (char *args)
bool HandleSunwellGateCounterCommand (char *args)
bool HandleExpansionRelease (char *args)
bool HandleBattlegroundStartCommand (char *args)
bool HandleBattlegroundStopCommand (char *args)
bool HandleSaveAllCommand (char *args)
Development Commands.
Player * getSelectedPlayer () const
Creature * getSelectedCreature () const
Unit * getSelectedUnit (bool self=true) const
std::string petLink (std::string const &name) const
std::string playerLink (std::string const &name) const
std::string GetNameLink (Player *chr) const
GameObject * GetGameObjectWithGuid (uint32 lowguid, uint32 entry) const
bool ShowAccountListHelper (QueryResult *result, uint32 *limit=nullptr, bool title=true, bool error=true)
void ShowAchievementListHelper (AchievementEntry const *achEntry, LocaleConstant loc, time_t const *date=nullptr, Player *target=nullptr)
void ShowAchievementCriteriaListHelper (AchievementCriteriaEntry const *criEntry, AchievementEntry const *achEntry, LocaleConstant loc, Player *target=nullptr)
void ShowFactionListHelper (FactionEntry const *factionEntry, LocaleConstant loc, FactionState const *repState=nullptr, Player *target=nullptr)
void ShowItemListHelper (uint32 itemId, int loc_idx, Player *target=nullptr)
void ShowQuestListHelper (uint32 questId, int32 loc_idx, Player *target=nullptr)
bool ShowPlayerListHelper (QueryResult *result, uint32 *limit=nullptr, bool title=true, bool error=true)
void ShowSpellListHelper (Player *target, SpellEntry const *spellInfo, LocaleConstant loc)
void ShowPoolListHelper (uint16 pool_id)
void ShowTriggerListHelper (AreaTriggerEntry const *atEntry)
void ShowTriggerTargetListHelper (uint32 id, AreaTrigger const *at, bool subpart=false)
bool LookupPlayerSearchCommand (QueryResult *result, uint32 *limit=nullptr)
bool HandleBanListHelper (QueryResult *result)
bool HandleBanHelper (BanMode mode, char *args)
bool HandleBanInfoHelper (uint32 accountid, char const *accountname)
bool HandleUnBanHelper (BanMode mode, char *args)
void HandleCharacterLevel (Player *player, ObjectGuid player_guid, uint32 oldlevel, uint32 newlevel)
void HandleLearnSkillRecipesHelper (Player *player, uint32 skill_id)
bool HandleGoHelper (Player *_player, uint32 mapid, float x, float y, float const *zPtr=nullptr, float const *ortPtr=nullptr)
bool HandleGetValueHelper (Object *target, uint32 field, char *typeStr)
void ShowAllUpdateFieldsHelper (Object const *target)
void ShowUpdateFieldHelper (Object const *target, uint16 index)
bool HandlerDebugModValueHelper (Object *target, uint32 field, char *typeStr, char *valStr)
bool HandleSetValueHelper (Object *target, uint32 field, char *typeStr, char *valStr)
bool HandleSendItemsHelper (MailDraft &draft, char *args)
bool HandleSendMailHelper (MailDraft &draft, char *args)
bool HandleSendMoneyHelper (MailDraft &draft, char *args)
template<typename T >
void ShowNpcOrGoSpawnInformation (uint32 guid)
template<typename T >
std::string PrepareStringNpcOrGoSpawnInformation (uint32 guid) const
bool GetDeletedCharacterInfoList (DeletedInfoList &foundList, std::string searchString="")
Collects all GUIDs (and related info) from deleted characters which are still in the database.
std::string GenerateDeletedCharacterGUIDsWhereStr (DeletedInfoList::const_iterator &itr, DeletedInfoList::const_iterator const &itr_end)
Generate WHERE guids list by deleted info in way preventing return too long where list for existed query string length limit.
void HandleCharacterDeletedListHelper (DeletedInfoList const &foundList)
Shows all deleted characters which matches the given search string, expected non empty list.
void HandleCharacterDeletedRestoreHelper (DeletedInfo const &delInfo)
Restore a previously deleted character.
void SetSentErrorMessage (bool val)
Private Attributes
WorldSession * m_session
bool sentErrorMessage
Static Private Attributes
static bool load_command_table = true
Detailed Description
Definition at line 80 of file Chat.h.
Member Typedef Documentation
DeletedInfoList
typedef std::list<DeletedInfo> ChatHandler::DeletedInfoList protected
Definition at line 896 of file Chat.h.
Constructor & Destructor Documentation
ChatHandler() [1/3]
ChatHandler::ChatHandler (WorldSession * session) explicit
Definition at line 1108 of file Chat.cpp.
ChatHandler() [2/3]
ChatHandler::ChatHandler (Player * player) explicit
Definition at line 1111 of file Chat.cpp.
~ChatHandler()
ChatHandler::~ChatHandler () virtual
Definition at line 1113 of file Chat.cpp.
ChatHandler() [3/3]
ChatHandler::ChatHandler () inline explicit protected
Definition at line 168 of file Chat.h.
Referenced by HandleAccountSetGmLevelCommand(), HandleAnticheatFingerprintListCommand(), HandleCharacterLevel(), HandleDebugSpellModsCommand(), HandleExploreCheatCommand(), HandleGonameCommand(), HandleGroupgoCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyRageCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleRepairitemsCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleUnmuteCommand(), HandleWaterwalkCommand(), and ModifyMountCommandHelper().
Member Function Documentation
BuildChatPacket()
void ChatHandler::BuildChatPacket (WorldPacket & data, ChatMsg msgtype, char const * message, Language language = LANG_UNIVERSAL, ChatTagFlags chatTag = CHAT_TAG_NONE, ObjectGuid const & senderGuid = ObjectGuid(), char const * senderName = nullptr, ObjectGuid const & targetGuid = ObjectGuid(), char const * targetName = nullptr, char const * channelName = nullptr, uint32 achievementId = 0) static
Prepare SMSG_GM_MESSAGECHAT/SMSG_MESSAGECHAT.
Method: BuildChatPacket build message chat packet generic way FullName: ChatHandler::BuildChatPacket Access: public static Returns: void
Parameters
WorldPacket& data : Provided packet will be filled with requested info
ChatMsg msgtype : Message type from ChatMsg enum from SharedDefines.h
ChatTagFlags chatTag : Chat tag from PlayerChatTag in Chat.h
char const* message : Message to send
Language language : Language from Language enum in SharedDefines.h
ObjectGuid const& senderGuid : May be null in some case but often required for ignore list
char const* senderName : Required for type MONSTER or BNET, but also if GM is true
ObjectGuid const& targetGuid : Often null, but needed for type MONSTER or BNET or BATTLEGROUND or ACHIEVEMENT
char const* targetName : Often null, but needed for type MONSTER or BNET or BATTLEGROUND
char const* channelName : Required only for CHAT_MSG_CHANNEL
uint32 achievementId : Required only for *ACHIEVEMENT
Definition at line 3781 of file Chat.cpp.
References CHAT_MSG_ACHIEVEMENT, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, CHAT_MSG_BG_SYSTEM_NEUTRAL, CHAT_MSG_BNET, CHAT_MSG_CHANNEL, CHAT_MSG_GUILD_ACHIEVEMENT, CHAT_MSG_MONSTER_EMOTE, CHAT_MSG_MONSTER_PARTY, CHAT_MSG_MONSTER_SAY, CHAT_MSG_MONSTER_WHISPER, CHAT_MSG_MONSTER_YELL, CHAT_MSG_RAID_BOSS_EMOTE, CHAT_MSG_RAID_BOSS_WHISPER, CHAT_MSG_WHISPER_FOREIGN, CHAT_TAG_GM, WorldPacket::Initialize(), ObjectGuid::IsPet(), ObjectGuid::IsPlayer(), LANG_ADDON, MANGOS_ASSERT, SMSG_GM_MESSAGECHAT, and SMSG_MESSAGECHAT.
Referenced by Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), MaNGOS::WorldWorldTextBuilder::do_helper(), WorldSession::HandleChatIgnoredOpcode(), HandleDebugSendChatMsgCommand(), WorldSession::HandleMessagechatOpcode(), WorldObject::MonsterSay(), WorldObject::MonsterTextEmote(), WorldObject::MonsterWhisper(), WorldObject::MonsterYell(), MaNGOS::AchievementChatBuilder::operator()(), BattleGroundBroadcastBuilder::operator()(), MaNGOS::BattleGroundChatBuilder::operator()(), MaNGOS::BattleGroundYellBuilder::operator()(), MaNGOS::BattleGroundMessageBuilder::operator()(), MaNGOS::BattleGroundBroadcastBuilder::operator()(), MaNGOS::BattleGround2ChatBuilder::operator()(), MaNGOS::BattleGround2YellBuilder::operator()(), MaNGOS::MonsterChatBuilder::operator()(), StaticMonsterChatBuilder::operator()(), Player::Say(), Channel::Say(), SendGlobalSysMessage(), World::SendGMTextFlags(), Player::SendMessageToPlayer(), SendSysMessage(), Player::TextEmote(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), Player::Whisper(), and Player::Yell().
CheckEscapeSequences()
bool ChatHandler::CheckEscapeSequences (const char * message) static
Definition at line 1720 of file Chat.cpp.
References CHAT_LINK_COLOR_ACHIEVEMENT, CHAT_LINK_COLOR_ENCHANT, CHAT_LINK_COLOR_GLYPH, CHAT_LINK_COLOR_SPELL, CHAT_LINK_COLOR_TALENT, CHAT_LINK_COLOR_TRADE, CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_SEVERITY, DEBUG_LOG, ObjectMgr::GetItemPrototype(), Quest::GetQuestId(), Quest::GetTitle(), SpellEntry::HasAttribute(), SpellEntry::Id, ItemPrototype::ItemId, ItemQualityColors, LOCALE_enUS, LOCALE_koKR, SQLStorage::LookupEntry(), MAX_LOCALE, ItemLocale::Name, AchievementEntry::name, SkillLineEntry::name, ItemPrototype::Name1, ItemRandomPropertiesEntry::nameSuffix, ItemRandomSuffixEntry::nameSuffix, ItemPrototype::Quality, TalentEntry::RankID, sAchievementStore, sGlyphPropertiesStore, sItemRandomPropertiesStore, sItemRandomSuffixStore, SkillLineAbilityEntry::skillId, sObjectMgr, SPELL_ATTR_IS_TRADESKILL, GlyphPropertiesEntry::SpellId, SpellEntry::SpellName, sSkillLineStore, sSpellMgr, sSpellTemplate, sTalentStore, STRONG_MAX_LEVEL, sWorld, and QuestLocale::Title.
Referenced by WorldSession::CheckChatMessage().
CheckIntegrity()
void ChatHandler::CheckIntegrity (ChatCommand * table, ChatCommand * parentCommand) const protected
Definition at line 1278 of file Chat.cpp.
References ChatCommand::ChildCommands, ChatCommand::Handler, ChatCommand::Name, ChatCommand::SecurityLevel, and sLog.
Referenced by getCommandTable().
ExecuteCommand()
void ChatHandler::ExecuteCommand (const char * text) protected
Execute (sub)command available for chat handler access level with options in command line string.
Parameters
text Command line string that will parsed for (sub)command search and command specific data
Command output and errors in command execution will send to chat handler.
Definition at line 1475 of file Chat.cpp.
References CHAT_COMMAND_OK, CHAT_COMMAND_UNKNOWN, CHAT_COMMAND_UNKNOWN_SUBCOMMAND, ChatCommand::ChildCommands, FindCommand(), getCommandTable(), ChatCommand::Handler, HasSentErrorMessage(), ChatCommand::Help, LANG_CMD_SYNTAX, LANG_NO_CMD, LANG_NO_SUBCMD, LogCommand(), ChatCommand::Name, SEC_PLAYER, ChatCommand::SecurityLevel, SendSysMessage(), SetSentErrorMessage(), ShowHelpForCommand(), and ShowHelpForSubCommands().
Referenced by ParseCommands().
ExtractAccountId()
uint32 ChatHandler::ExtractAccountId (char ** args, std::string * accountName = nullptr, Player ** targetIfNullArg = nullptr)
Get the account name from the command line
only target player different from self allowed (if targetPlayer!=nullptr then not console)
Definition at line 3491 of file Chat.cpp.
References ExtractLiteralArg(), ExtractUInt32(), WorldSession::GetAccountId(), getSelectedPlayer(), Player::GetSession(), LANG_ACCOUNT_NOT_EXIST, AccountMgr::normalizeString(), PSendSysMessage(), sAccountMgr, and SetSentErrorMessage().
Referenced by HandleAccountCharactersCommand(), HandleAccountDeleteCommand(), HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), HandleBanInfoAccountCommand(), and HandlePDumpLoadCommand().
ExtractArg()
char * ChatHandler::ExtractArg (char ** args, bool asis = false) static
Function extract name/number/quote/shift-link-like string.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
asis control save quote string wrappers
Returns
extracted arg string, or nullptr if args empty or not appropriate content.
Definition at line 2877 of file Chat.cpp.
References ExtractLinkArg(), and ExtractQuotedOrLiteralArg().
Referenced by ExtractOptNotLastArg(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAuctionItemCommand(), HandleBanHelper(), HandleCharacterLevelCommand(), HandleLevelUpCommand(), HandleSendItemsHelper(), and HandleUnBanHelper().
ExtractFloat()
bool ChatHandler::ExtractFloat (char ** args, float & val) static
Function extract to val arg float value or fail.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
Returns
true if value extraction successful
Definition at line 2475 of file Chat.cpp.
References isWhiteSpace(), and SkipWhiteSpaces().
Referenced by ExtractOptFloat(), HandleCastDistCommand(), HandleChangeWeatherCommand(), HandleDebugSetValueByNameCommand(), HandleGameObjectMoveCommand(), HandleGameObjectTurnCommand(), HandleGoCommand(), HandleGoGridCommand(), HandleGoXYCommand(), HandleGoZoneXYCommand(), HandleMmapTestArea(), HandleMmapTestHeight(), HandlerDebugModValueHelper(), HandleSetValueHelper(), and HandleWpModifyCommand().
ExtractGameTeleFromLink()
GameTele const * ChatHandler::ExtractGameTeleFromLink (char ** text)
Definition at line 3094 of file Chat.cpp.
References ExtractKeyFromLink(), ExtractUInt32(), and sObjectMgr.
Referenced by HandleTeleCommand(), HandleTeleGroupCommand(), and HandleTeleNameCommand().
ExtractGuidFromLink()
ObjectGuid ChatHandler::ExtractGuidFromLink (char ** text)
Definition at line 3124 of file Chat.cpp.
References ExtractKeyFromLink(), ExtractUInt32(), GUID_LINK_CREATURE, GUID_LINK_GAMEOBJECT, GUID_LINK_PLAYER, GUID_LINK_RAW, guidKeys, HIGHGUID_GAMEOBJECT, normalizePlayerName(), and sObjectMgr.
Referenced by HandleGetDistanceCommand(), and HandleGPSCommand().
ExtractInt32()
bool ChatHandler::ExtractInt32 (char ** args, int32 & val) const
Function extract to val arg signed integer value or fail.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
Returns
true if value extraction successful
Definition at line 2374 of file Chat.cpp.
References isWhiteSpace().
Referenced by ExtractOptInt32(), ExtractSpellIdFromLink(), HandleAccountSetGmLevelCommand(), HandleCharacterLevelCommand(), HandleDamageCommand(), HandleDebugByteFields(), HandleDebugSetAuraStateCommand(), HandleDebugSpellModsCommand(), HandleLevelUpCommand(), HandleModifyRepCommand(), HandleScourgeInvasionBattlesWonCommand(), HandleScourgeInvasionStartZone(), HandleServerPLimitCommand(), HandleSetSkillCommand(), HandleSunsReachReclamationSubPhaseCommand(), and ModifyStatCommandHelper().
ExtractKeyFromLink() [1/2]
char * ChatHandler::ExtractKeyFromLink (char ** text, char const *const * linkTypes, int * found_idx = nullptr, char ** something1 = nullptr) static
Function extract data from shift-link "|color|LINKTYPE:RETURN:SOMETHING1|h[name]|h|r if LINKTYPE in linkTypes array It also extract literal/quote if not shift-link in args.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces) if args have sift link with linkType != LINKTYPE then args still pointing to this arg (unmodified pointer)
linkTypes nullptr-terminated array of link types, shift-link must fit one from link type from array or extraction fail
found_idx if not nullptr then at return index in linkTypes that fit shift-link type, for non-link case return -1 if extraction fail then non modified
something1 if not nullptr then shift-link must have data field and it returned into this arg if extraction fail then non modified
Returns
extracted key, or nullptr if args empty or not appropriate content or not fit to linkType.
Definition at line 2952 of file Chat.cpp.
References ExtractLinkArg(), and ExtractQuotedOrLiteralArg().
ExtractKeyFromLink() [2/2]
char * ChatHandler::ExtractKeyFromLink (char ** text, char const * linkType, char ** something1 = nullptr)
Function extract data from shift-link "|color|LINKTYPE:RETURN:SOMETHING1|h[name]|h|r if linkType == LINKTYPE It also extract literal/quote if not shift-link in args.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces) if args have sift link with linkType != LINKTYPE then args still pointing to this arg (unmodified pointer)
linkType shift-link must fit by link type to this arg value or extraction fail
something1 if not nullptr then shift-link must have data field and it returned into this arg if extraction fail then non modified
Returns
extracted key, or nullptr if args empty or not appropriate content or not fit to linkType.
Definition at line 2924 of file Chat.cpp.
Referenced by ExtractGameTeleFromLink(), ExtractGuidFromLink(), ExtractLocationFromLink(), ExtractPlayerNameFromLink(), ExtractSpellIdFromLink(), ExtractUint32KeyFromLink(), HandleAddItemCommand(), HandleGameObjectTargetCommand(), HandleGoCreatureCommand(), HandleGoObjectCommand(), HandleGoTriggerCommand(), and HandleSetSkillCommand().
ExtractLinkArg()
char * ChatHandler::ExtractLinkArg (char ** args, char const *const * linkTypes = nullptr, int * foundIdx = nullptr, char ** keyPair = nullptr, char ** somethingPair = nullptr) static
Function extract shift-link-like string (any characters guarded by | and |h|r with some additional internal structure check)
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
linkTypes optional nullptr-terminated array of link types, shift-link must fit one from link type from array if provided or extraction fail
found_idx if not nullptr then at return index in linkTypes that fit shift-link type, if extraction fail then non modified
keyPair if not nullptr then pointer to 2-elements array for return start and end pointer for found key if extraction fail then non modified
somethingPair then pointer to 2-elements array for return start and end pointer if found. if not nullptr then shift-link must have data field, if extraction fail then non modified
Returns
shift-link-like string, or nullptr if args empty or not appropriate content.
Definition at line 2701 of file Chat.cpp.
References isWhiteSpace(), and SkipWhiteSpaces().
Referenced by ExtractArg(), and ExtractKeyFromLink().
ExtractLiteralArg()
char * ChatHandler::ExtractLiteralArg (char ** args, char const * lit = nullptr) static
Function extract name-like string (from non-numeric or special symbol until whitespace)
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
lit optional explicit literal requirement. function fail if literal is not starting substring of lit. Note: function in same way fail if no any literal or literal not fit in this case. Need additional check for select specific fail case
Returns
name/number-like string without whitespaces, or nullptr if args empty or not appropriate content.
Definition at line 2524 of file Chat.cpp.
References isWhiteSpace(), and SkipWhiteSpaces().
Referenced by instance_molten_core::ExecuteChatCommand(), instance_sunwell_plateau::ExecuteChatCommand(), instance_zulaman::ExecuteChatCommand(), instance_dark_portal::ExecuteChatCommand(), instance_mount_hyjal::ExecuteChatCommand(), instance_trial_of_the_crusader::ExecuteChatCommand(), instance_halls_of_reflection::ExecuteChatCommand(), instance_icecrown_citadel::ExecuteChatCommand(), instance_halls_of_stone::ExecuteChatCommand(), instance_violet_hold::ExecuteChatCommand(), instance_serpentshrine_cavern::ExecuteChatCommand(), instance_blood_furnace::ExecuteChatCommand(), instance_mechanar::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), ExtractAccountId(), ExtractOnOff(), ExtractQuotedOrLiteralArg(), ExtractRaceMask(), HandleAuctionItemCommand(), HandleBanListAccountCommand(), HandleBanListCharacterCommand(), HandleBanListIPCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChannelListCommand(), HandleChannelStaticCommand(), HandleCharacterEraseCommand(), HandleDebugGetItemValueCommand(), HandleDebugGetValueByIndexCommand(), HandleDebugLootDropStats(), HandleDebugModItemValueCommand(), HandleDebugModValueCommand(), HandleDebugObjectFlags(), HandleDebugSetItemValueCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSpellModsCommand(), HandleGMMountUpCommand(), HandleGoTriggerCommand(), HandleLearnCommand(), HandleLinkGraveCommand(), HandleListCreatureCommand(), HandleListObjectCommand(), HandleModifyRepCommand(), HandleNpcSetMoveTypeCommand(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandleServerLogFilterCommand(), HandleServerPLimitCommand(), HandleTicketsCommand(), HandleTicketsListCommand(), HandleUnLearnCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), HandleWpShowCommand(), and ModifyMountCommandHelper().
ExtractLocationFromLink()
bool ChatHandler::ExtractLocationFromLink (char ** text, uint32 & mapid, float & x, float & y, float & z)
Definition at line 3203 of file Chat.cpp.
References ExtractKeyFromLink(), ExtractUInt32(), ObjectMgr::GetCreatureTemplate(), ObjectMgr::GetGameObjectInfo(), WorldSession::GetPlayer(), FindCreatureData::GetResult(), FindGOData::GetResult(), LANG_AREATRIGER_NOT_HAS_TARGET, LANG_COMMAND_GOAREATRNOTFOUND, Player::LoadPositionFromDB(), LOCATION_LINK_AREATRIGGER, LOCATION_LINK_AREATRIGGER_TARGET, LOCATION_LINK_CREATURE, LOCATION_LINK_CREATURE_ENTRY, LOCATION_LINK_GAMEOBJECT, LOCATION_LINK_GAMEOBJECT_ENTRY, LOCATION_LINK_PLAYER, LOCATION_LINK_RAW, LOCATION_LINK_TAXINODE, LOCATION_LINK_TELE, locationKeys, m_session, TaxiNodesEntry::map_id, GameTele::mapId, AreaTriggerEntry::mapid, normalizePlayerName(), GameTele::position_x, GameTele::position_y, GameTele::position_z, PSendSysMessage(), sAreaTriggerStore, SetSentErrorMessage(), sObjectMgr, sTaxiNodesStore, AreaTrigger::target_mapId, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, AreaTriggerEntry::x, TaxiNodesEntry::x, AreaTriggerEntry::y, TaxiNodesEntry::y, AreaTriggerEntry::z, and TaxiNodesEntry::z.
Referenced by HandleGoCommand().
ExtractOnOff()
bool ChatHandler::ExtractOnOff (char ** args, bool & value) static
Function extract on/off literals as boolean values.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
Returns
true at success
Definition at line 2665 of file Chat.cpp.
References ExtractLiteralArg().
Referenced by HandleAccountLockCommand(), HandleChannelStaticCommand(), HandleDebugMovement(), HandleDebugObjectFlags(), HandleGMChatCommand(), HandleGMCommand(), HandleGMFlyCommand(), HandleGMVisibleCommand(), HandleMmap(), HandleServerLogFilterCommand(), HandleTaxiCheatCommand(), HandleTicketsCommand(), HandleTicketsQueueCommand(), HandleWaterwalkCommand(), HandleWhisperRestrictionCommand(), and HandleWhispersCommand().
ExtractOptFloat()
bool ChatHandler::ExtractOptFloat (char ** args, float & val, float defVal) static
Function extract to val arg optional float value or use default value.
Fail if extracted not float.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
defVal default value used if no data for extraction in args
Returns
true if value extraction successful
Definition at line 2505 of file Chat.cpp.
References ExtractFloat().
Referenced by HandleGameObjectNearCommand(), HandleGameObjectNearSpawnedCommand(), and HandleGameObjectTurnCommand().
ExtractOptInt32()
bool ChatHandler::ExtractOptInt32 (char ** args, int32 & val, int32 defVal) const
Function extract to val arg optional signed integer value or use default value.
Fail if extracted not signed integer.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
defVal default value used if no data for extraction in args
Returns
true if value extraction successful
Definition at line 2405 of file Chat.cpp.
References ExtractInt32().
Referenced by HandleAddItemCommand(), HandleCharacterDeletedOldCommand(), HandleGameObjectAddCommand(), HandleModifyRepCommand(), and HandleSetSkillCommand().
ExtractOptNotLastArg()
char * ChatHandler::ExtractOptNotLastArg (char ** args) static
Function extract name/quote/number/shift-link-like string, and return it if args have more non-whitespace data.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces) if args have only single arg then args still pointing to this arg (unmodified pointer)
Returns
extracted string, or nullptr if args empty or not appropriate content or have single arg totally.
Definition at line 2896 of file Chat.cpp.
References ExtractArg().
Referenced by HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementRemoveCommand(), HandleCharacterLevelCommand(), HandleDebugSetItemValueCommand(), HandleDebugSetValueByIndexCommand(), HandleGuildCreateCommand(), HandleGuildInviteCommand(), HandleGuildRankCommand(), HandleLevelUpCommand(), HandleMuteCommand(), and HandleTeleNameCommand().
ExtractOptUInt32()
bool ChatHandler::ExtractOptUInt32 (char ** args, uint32 & val, uint32 defVal) const
Function extract to val arg optional unsigned integer value or use default value.
Fail if extracted not unsigned integer.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
defVal default value used if no data for extraction in args
Returns
true if value extraction successful
Definition at line 2457 of file Chat.cpp.
References ExtractUInt32().
Referenced by HandleAccountOnlineListCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAuctionItemCommand(), HandleDebugSendSpellFailCommand(), HandleDieCommand(), HandleGoCommand(), HandleGoGridCommand(), HandleGoXYCommand(), HandleListAurasCommand(), HandleListCreatureCommand(), HandleListItemCommand(), HandleListObjectCommand(), HandleLookupAccountEmailCommand(), HandleLookupAccountIpCommand(), HandleLookupAccountNameCommand(), HandleLookupPlayerAccountCommand(), HandleLookupPlayerEmailCommand(), HandleLookupPlayerIpCommand(), HandleModifyFactionCommand(), HandleNpcAddVendorItemCommand(), HandleServerIdleRestartCommand(), HandleServerIdleShutDownCommand(), HandleServerRestartCommand(), HandleServerShutDownCommand(), HandleShowGearScoreCommand(), HandleTicketEscalateCommand(), HandleWpAddCommand(), HandleWpExportCommand(), and HandleWpShowCommand().
ExtractPlayerNameFromLink()
std::string ChatHandler::ExtractPlayerNameFromLink (char ** text)
Definition at line 3411 of file Chat.cpp.
References ExtractKeyFromLink(), and normalizePlayerName().
Referenced by ExtractPlayerTarget(), and HandlePDumpWriteCommand().
ExtractPlayerTarget()
bool ChatHandler::ExtractPlayerTarget (char ** args, Player ** player, ObjectGuid * player_guid = nullptr, std::string * player_name = nullptr)
Function extract at least one from request player data (pointer/guid/name) from args name/shift-link or selected player if no args.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
player optional arg One from 3 optional args must be provided at least (or more).
player_guid optional arg For function success only one from provided args need get result
player_name optional arg But if early arg get value then all later args will have its (if requested) if player_guid requested and not found then name also will not found So at success can be returned 2 cases: (player/guid/name) or (guid/name)
Returns
true if extraction successful
Definition at line 3438 of file Chat.cpp.
References ExtractPlayerNameFromLink(), WorldObject::GetName(), Object::GetObjectGuid(), getSelectedPlayer(), LANG_PLAYER_NOT_FOUND, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleAddCharacterNoteCommand(), HandleAnticheatInfoCommand(), HandleAnticheatSpaminfoCommand(), HandleBanInfoCharacterCommand(), HandleCharacterAchievementsCommand(), HandleCharacterCustomizeCommand(), HandleCharacterEraseCommand(), HandleCharacterLevelCommand(), HandleCharacterRenameCommand(), HandleCharacterReputationCommand(), HandleCharacterTitlesCommand(), HandleCombatStopCommand(), HandleGonameCommand(), HandleGroupgoCommand(), HandleGuildCreateCommand(), HandleGuildInviteCommand(), HandleGuildRankCommand(), HandleGuildUninviteCommand(), HandleKickPlayerCommand(), HandleLearnAllDefaultCommand(), HandleLevelUpCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleNpcWhisperCommand(), HandlePInfoCommand(), HandleRecallCommand(), HandleRepairitemsCommand(), HandleResetAchievementsCommand(), HandleResetHonorCommand(), HandleResetLevelCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetStatsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleReviveCommand(), HandleSendItemsCommand(), HandleSendMailCommand(), HandleSendMessageCommand(), HandleSendMoneyCommand(), HandleTeleNameCommand(), HandleUnmuteCommand(), and HandleWarnCharacterCommand().
ExtractQuotedArg()
char * ChatHandler::ExtractQuotedArg (char ** args, bool asis = false) static
Function extract quote-like string (any characters guarded by some special character, in our cases ['")
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
asis control save quote string wrappers
Returns
quote-like string, or nullptr if args empty or not appropriate content.
Definition at line 2601 of file Chat.cpp.
References isWhiteSpace(), and SkipWhiteSpaces().
Referenced by ExtractQuotedOrLiteralArg(), HandleArenaTeamPointSet(), HandleGuildCreateCommand(), HandleGuildDeleteCommand(), HandleGuildInviteCommand(), HandleSendItemsHelper(), HandleSendMailHelper(), and HandleSendMoneyHelper().
ExtractQuotedOrLiteralArg()
char * ChatHandler::ExtractQuotedOrLiteralArg (char ** args, bool asis = false) static
Function extract quote-like string or literal if quote not detected.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
asis control save quote string wrappers
Returns
quote/literal string, or nullptr if args empty or not appropriate content.
Definition at line 2650 of file Chat.cpp.
References ExtractLiteralArg(), and ExtractQuotedArg().
Referenced by ExtractArg(), ExtractKeyFromLink(), HandleAccountCreateCommand(), HandleAccountPasswordCommand(), HandleAccountSetPasswordCommand(), HandleAddCharacterNoteCommand(), HandleBanInfoIPCommand(), HandleDebugGetValueByNameCommand(), HandleDebugSetValueByNameCommand(), HandleLookupAccountEmailCommand(), HandleLookupAccountIpCommand(), HandleLookupAccountNameCommand(), HandleLookupPlayerAccountCommand(), HandleLookupPlayerEmailCommand(), HandleLookupPlayerIpCommand(), HandleMuteCommand(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandleUnBanHelper(), and HandleWarnCharacterCommand().
ExtractRaceMask()
bool ChatHandler::ExtractRaceMask (char ** text, uint32 & raceMask, char const ** maskName = nullptr)
Definition at line 3587 of file Chat.cpp.
References ExtractLiteralArg(), ExtractUInt32(), RaceMaskName::literal, and raceMaskNames.
Referenced by HandleSendMassItemsCommand(), HandleSendMassMailCommand(), and HandleSendMassMoneyCommand().
ExtractSpellIdFromLink()
uint32 ChatHandler::ExtractSpellIdFromLink (char ** text)
Definition at line 3038 of file Chat.cpp.
References ExtractInt32(), ExtractKeyFromLink(), ExtractUInt32(), MAX_TALENT_RANK, TalentEntry::RankID, sGlyphPropertiesStore, SPELL_LINK_ENCHANT, SPELL_LINK_GLYPH, SPELL_LINK_RAW, SPELL_LINK_SPELL, SPELL_LINK_TALENT, SPELL_LINK_TRADE, GlyphPropertiesEntry::SpellId, spellKeys, and sTalentStore.
Referenced by HandleAuraCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleCooldownClearCommand(), HandleDamageCommand(), HandleDebugSpellCoefsCommand(), HandleLearnCommand(), HandleUnAuraCommand(), and HandleUnLearnCommand().
ExtractUInt32()
bool ChatHandler::ExtractUInt32 (char ** args, uint32 & val) const inline
Definition at line 138 of file Chat.h.
References ExtractUInt32Base().
Referenced by instance_molten_core::ExecuteChatCommand(), instance_dark_portal::ExecuteChatCommand(), instance_mount_hyjal::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), ExtractAccountId(), ExtractGameTeleFromLink(), ExtractGuidFromLink(), ExtractLocationFromLink(), ExtractOptUInt32(), ExtractRaceMask(), ExtractSpellIdFromLink(), ExtractUint32KeyFromLink(), HandleAccountCreateCommand(), HandleAccountSetAddonCommand(), HandleAddItemCommand(), HandleArenaDataReset(), HandleArenaSeasonRewardsCommand(), HandleArenaTeamPointSet(), HandleAuctionItemCommand(), HandleChangeWeatherCommand(), HandleChannelListCommand(), HandleDamageCommand(), HandleDebugAnimCommand(), HandleDebugByteFields(), HandleDebugDbscript(), HandleDebugDbscriptGuided(), HandleDebugDbscriptSourced(), HandleDebugDbscriptTargeted(), HandleDebugGetItemValueCommand(), HandleDebugGetValueByIndexCommand(), HandleDebugLootDropStats(), HandleDebugModItemValueCommand(), HandleDebugModValueCommand(), HandleDebugPacketLog(), HandleDebugPetDismissSound(), HandleDebugPlayCinematicCommand(), HandleDebugPlayMovieCommand(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugSendChannelNotifyCommand(), HandleDebugSendChatMsgCommand(), HandleDebugSendPoiCommand(), HandleDebugSendQuestFailedMsgCommand(), HandleDebugSendQuestPartyMsgCommand(), HandleDebugSendSpellFailCommand(), HandleDebugSendWorldState(), HandleDebugSetItemValueCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpellModsCommand(), HandleDebugSpellVisual(), HandleDebugUpdateWorldStateCommand(), HandleDebugWaypoint(), HandleExpansionRelease(), HandleGameObjectPhaseCommand(), HandleGameObjectTargetCommand(), HandleGMMountUpCommand(), HandleGoCreatureCommand(), HandleGoGraveyardCommand(), HandleGoObjectCommand(), HandleGoTriggerCommand(), HandleGuildRankCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkEditCommand(), HandleLinkGraveCommand(), HandleLinkRemoveCommand(), HandleLinkToggleCommand(), HandleModifyStandStateCommand(), HandleMuteCommand(), HandleNpcFormationSwitchCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcSpawnTimeCommand(), HandleNpcTempSpawn(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandleScourgeInvasionStateCommand(), HandleSendMoneyHelper(), HandleServerIdleRestartCommand(), HandleServerIdleShutDownCommand(), HandleServerRestartCommand(), HandleServerShutDownCommand(), HandleSunsReachReclamationCounterCommand(), HandleSunsReachReclamationPhaseCommand(), HandleSunwellGateCommand(), HandleSunwellGateCounterCommand(), HandleTicketDiscardCommand(), HandleTicketEscalateCommand(), HandleTicketGoCommand(), HandleTicketGoNameCommand(), HandleTicketNoteCommand(), HandleTicketReadCommand(), HandleTicketResolveCommand(), HandleTicketsCommand(), HandleTicketsListCommand(), HandleTicketSortCommand(), HandleTicketWhisperCommand(), HandleWarEffortCounterCommand(), HandleWarEffortPhaseCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), and HandleWpShowCommand().
ExtractUInt32Base()
bool ChatHandler::ExtractUInt32Base (char ** args, uint32 & val, uint32 base) const
Function extract to val arg unsigned integer value or fail.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces)
val return extracted value if function success, in fail case original value unmodified
base set used base for extracted value format (10 for decimal, 16 for hex, etc), 0 let auto select by system internal function
Returns
true if value extraction successful
Definition at line 2424 of file Chat.cpp.
References isWhiteSpace(), and SkipWhiteSpaces().
Referenced by ExtractUInt32(), HandleAnticheatDebugExtrapCommand(), HandleAnticheatFingerprintAHistoryCommand(), HandleAnticheatFingerprintHistoryCommand(), HandleAnticheatFingerprintListCommand(), HandleAnticheatSilenceCommand(), HandleAnticheatUnsilenceCommand(), HandlerDebugModValueHelper(), and HandleSetValueHelper().
ExtractUint32KeyFromLink()
bool ChatHandler::ExtractUint32KeyFromLink (char ** text, char const * linkType, uint32 & value)
Function extract uint32 key from shift-link "|color|LINKTYPE:RETURN|h[name]|h|r if linkType == LINKTYPE It also extract direct number if not shift-link in args.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces) if args have sift link with linkType != LINKTYPE then args still pointing to this arg (unmodified pointer)
linkType shift-link must fit by link type to this arg value or extraction fail
value store result value at success return, not modified at fail
Returns
true if extraction succesful
Definition at line 2999 of file Chat.cpp.
References ExtractKeyFromLink(), and ExtractUInt32().
Referenced by HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleAddItemSetCommand(), HandleEventInfoCommand(), HandleEventStartCommand(), HandleEventStopCommand(), HandleGameObjectActivateCommand(), HandleGameObjectAddCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectForcedDespawnCommand(), HandleGameObjectMoveCommand(), HandleGameObjectPhaseCommand(), HandleGameObjectRespawnCommand(), HandleGameObjectTurnCommand(), HandleGoTaxinodeCommand(), HandleGoZoneXYCommand(), HandleListCreatureCommand(), HandleListItemCommand(), HandleListObjectCommand(), HandleModifyFactionCommand(), HandleModifyRepCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcDeleteCommand(), HandleNpcDelVendorItemCommand(), HandleNpcMoveCommand(), HandlePoolInfoCommand(), HandlePoolSpawnsCommand(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), and HandleTriggerCommand().
FindCommand() [1/2]
ChatCommand const * ChatHandler::FindCommand (char const * text)
Search (sub)command for command line available for chat handler access level.
Parameters
text Command line string that will parsed for (sub)command search
Returns
Pointer to found command structure or nullptr if appropriate command not found
Definition at line 1327 of file Chat.cpp.
References CHAT_COMMAND_OK, and getCommandTable().
Referenced by Spell::CheckCast(), ExecuteCommand(), FindCommand(), SetDataForCommandInTable(), and ShowHelpForCommand().
FindCommand() [2/2]
ChatCommandSearchResult ChatHandler::FindCommand (ChatCommand * table, char const *& text, ChatCommand *& command, ChatCommand ** parentCommand = nullptr, std::string * cmdNamePtr = nullptr, bool allAvailable = false, bool exactlyName = false) const protected
Search (sub)command for command line available for chat handler access level with options and fail case additional info.
Parameters
table Pointer to command C-style array first level command where will be searched
text Command line string that will parsed for (sub)command search, it modified at return from function and pointed to not parsed tail
command At success this is found command, at other cases this is last found parent command before subcommand search fail
parentCommand Output arg for optional return parent command for command arg.
cmdNamePtr Output arg for optional return last parsed command name.
allAvailable Optional arg (with false default value) control use command access level checks while command search.
exactlyName Optional arg (with false default value) control use exactly name in checks while command search.
Returns
one from enum value of ChatCommandSearchResult. Output args return values highly dependent from this return result:
 CHAT_COMMAND_OK       - Command found!
                         text point to non parsed tail with possible command specific data, command store found command pointer,
                         parentCommand have parent of found command or nullptr if command found in table array directly
                         cmdNamePtr store found command name in original form from command line
 CHAT_COMMAND_UNKNOWN  - Command not found in table directly
                         text only skip possible whitespaces,
                         command is nullptr
                         parentCommand is nullptr
                         cmdNamePtr store command name that not found as it extracted from command line
 CHAT_COMMAND_UNKNOWN_SUBCOMMAND - Subcommand not found in some deed subcomand lists
                         text point to non parsed tail including not found command name in command line,
                         command store last found parent command if any
                         parentCommand have parent of command in command arg or nullptr
                         cmdNamePtr store command name that not found as it extracted from command line
Definition at line 1365 of file Chat.cpp.
References CHAT_COMMAND_OK, CHAT_COMMAND_UNKNOWN, CHAT_COMMAND_UNKNOWN_SUBCOMMAND, FindCommand(), hasStringAbbr(), isAvailable(), and ChatCommand::Name.
GetAccessLevel()
AccountTypes ChatHandler::GetAccessLevel () const protected virtual
Reimplemented in CliHandler.
Definition at line 1130 of file Chat.cpp.
References WorldSession::GetSecurity(), and m_session.
Referenced by HandleAccountCommand(), HandleAccountSetGmLevelCommand(), HandlePInfoCommand(), HandleSaveCommand(), HasLowerSecurityAccount(), and isAvailable().
GetAccountId()
uint32 ChatHandler::GetAccountId () const protected virtual
Reimplemented in CliHandler.
Definition at line 1125 of file Chat.cpp.
References WorldSession::GetAccountId(), and m_session.
Referenced by HandleAccountLockCommand(), HandleAccountPasswordCommand(), HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), and LogCommand().
getCommandTable()
ChatCommand * ChatHandler::getCommandTable () protected
Definition at line 67 of file Chat.cpp.
References anticheatCommandTable, CheckIntegrity(), QueryResult::Fetch(), Field::GetCppString(), Field::GetUInt16(), HandleAccountCharactersCommand(), HandleAccountCommand(), HandleAccountCreateCommand(), HandleAccountDeleteCommand(), HandleAccountLockCommand(), HandleAccountOnlineListCommand(), HandleAccountPasswordCommand(), HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleAddCharacterNoteCommand(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleAnnounceCommand(), HandleArenaDataReset(), HandleArenaFlushPointsCommand(), HandleArenaSeasonRewardsCommand(), HandleArenaTeamPointSet(), HandleAuctionAllianceCommand(), HandleAuctionCommand(), HandleAuctionGoblinCommand(), HandleAuctionHordeCommand(), HandleAuctionItemCommand(), HandleAuraCommand(), HandleBagsCommand(), HandleBanAccountCommand(), HandleBanCharacterCommand(), HandleBanInfoAccountCommand(), HandleBanInfoCharacterCommand(), HandleBanInfoIPCommand(), HandleBanIPCommand(), HandleBankCommand(), HandleBanListAccountCommand(), HandleBanListCharacterCommand(), HandleBanListIPCommand(), HandleBattlegroundStartCommand(), HandleBattlegroundStopCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChangeWeatherCommand(), HandleChannelListCommand(), HandleChannelStaticCommand(), HandleCharacterAchievementsCommand(), HandleCharacterCustomizeCommand(), HandleCharacterDeletedDeleteCommand(), HandleCharacterDeletedListCommand(), HandleCharacterDeletedOldCommand(), HandleCharacterDeletedRestoreCommand(), HandleCharacterEraseCommand(), HandleCharacterLevelCommand(), HandleCharacterRenameCommand(), HandleCharacterReputationCommand(), HandleCharacterTitlesCommand(), HandleCombatListCommand(), HandleCombatStopCommand(), HandleComeToMeCommand(), HandleCommandsCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleCooldownClearCommand(), HandleCooldownListCommand(), HandleDamageCommand(), HandleDebugAnimCommand(), HandleDebugAreaTriggersCommand(), HandleDebugArenaCommand(), HandleDebugBattlegroundCommand(), HandleDebugByteFields(), HandleDebugChatFreezeCommand(), HandleDebugDbscript(), HandleDebugDbscriptGuided(), HandleDebugDbscriptSourced(), HandleDebugDbscriptTargeted(), HandleDebugGetItemStateCommand(), HandleDebugGetItemValueCommand(), HandleDebugGetLootRecipientCommand(), HandleDebugGetValueByIndexCommand(), HandleDebugGetValueByNameCommand(), HandleDebugHaveAtClientCommand(), HandleDebugIncPacketHistory(), HandleDebugIsVisibleCommand(), HandleDebugLfgCommand(), HandleDebugListUpdateFieldsCommand(), HandleDebugLootDropStats(), HandleDebugModItemValueCommand(), HandleDebugModValueCommand(), HandleDebugMoveflags(), HandleDebugMovement(), HandleDebugObjectFlags(), HandleDebugOutPacketHistory(), HandleDebugOverflowCommand(), HandleDebugPacketLog(), HandleDebugPetDismissSound(), HandleDebugPlayCinematicCommand(), HandleDebugPlayMovieCommand(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugRespawnDynguid(), HandleDebugSendBuyErrorCommand(), HandleDebugSendChannelNotifyCommand(), HandleDebugSendChatMsgCommand(), HandleDebugSendEquipErrorCommand(), HandleDebugSendLargePacketCommand(), HandleDebugSendOpcodeCommand(), HandleDebugSendPoiCommand(), HandleDebugSendQuestFailedMsgCommand(), HandleDebugSendQuestInvalidMsgCommand(), HandleDebugSendQuestPartyMsgCommand(), HandleDebugSendSellErrorCommand(), HandleDebugSendSetPhaseShiftCommand(), HandleDebugSendSpellFailCommand(), HandleDebugSendWorldState(), HandleDebugSetAuraStateCommand(), HandleDebugSetItemValueCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpawnsList(), HandleDebugSpellCheckCommand(), HandleDebugSpellCoefsCommand(), HandleDebugSpellModsCommand(), HandleDebugSpellVisual(), HandleDebugTaxiCommand(), HandleDebugTransports(), HandleDebugUpdateWorldStateCommand(), HandleDebugWaypoint(), HandleDeMorphCommand(), HandleDieCommand(), HandleDismountCommand(), HandleEventInfoCommand(), HandleEventListCommand(), HandleEventStartCommand(), HandleEventStopCommand(), HandleExpansionRelease(), HandleExploreCheatCommand(), HandleGameObjectActivateCommand(), HandleGameObjectAddCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectForcedDespawnCommand(), HandleGameObjectMoveCommand(), HandleGameObjectNearCommand(), HandleGameObjectNearSpawnedCommand(), HandleGameObjectPhaseCommand(), HandleGameObjectRespawnCommand(), HandleGameObjectTargetCommand(), HandleGameObjectTurnCommand(), HandleGetDistanceCommand(), HandleGetLosCommand(), HandleGMChatCommand(), HandleGMCommand(), HandleGMFlyCommand(), HandleGMListFullCommand(), HandleGMListIngameCommand(), HandleGMMountUpCommand(), HandleGMVisibleCommand(), HandleGoCommand(), HandleGoCreatureCommand(), HandleGoGraveyardCommand(), HandleGoGridCommand(), HandleGonameCommand(), HandleGoObjectCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), HandleGoWarpCommand(), HandleGoXYCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), HandleGPSCommand(), HandleGridsLoadedCount(), HandleGroupgoCommand(), HandleGUIDCommand(), HandleGuildCreateCommand(), HandleGuildDeleteCommand(), HandleGuildInviteCommand(), HandleGuildRankCommand(), HandleGuildUninviteCommand(), HandleHelpCommand(), HandleHideAreaCommand(), HandleHonorAddCommand(), HandleHonorAddKillCommand(), HandleHonorUpdateCommand(), HandleInstanceListBindsCommand(), HandleInstanceSaveDataCommand(), HandleInstanceStatsCommand(), HandleInstanceUnbindCommand(), HandleItemMoveCommand(), HandleKickPlayerCommand(), HandleLearnAllCommand(), HandleLearnAllCraftsCommand(), HandleLearnAllDefaultCommand(), HandleLearnAllGMCommand(), HandleLearnAllLangCommand(), HandleLearnAllMyClassCommand(), HandleLearnAllMyPetTalentsCommand(), HandleLearnAllMySpellsCommand(), HandleLearnAllMyTalentsCommand(), HandleLearnAllRecipesCommand(), HandleLearnCommand(), HandleLevelUpCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkEditCommand(), HandleLinkGraveCommand(), HandleLinkRemoveCommand(), HandleLinkToggleCommand(), HandleListAreaTriggerCommand(), HandleListAurasCommand(), HandleListCreatureCommand(), HandleListItemCommand(), HandleListObjectCommand(), HandleListTalentsCommand(), HandleLoadScriptsCommand(), HandleLookupAccountEmailCommand(), HandleLookupAccountIpCommand(), HandleLookupAccountNameCommand(), HandleLookupAchievementCommand(), HandleLookupAreaCommand(), HandleLookupCreatureCommand(), HandleLookupEventCommand(), HandleLookupFactionCommand(), HandleLookupItemCommand(), HandleLookupItemSetCommand(), HandleLookupObjectCommand(), HandleLookupPlayerAccountCommand(), HandleLookupPlayerEmailCommand(), HandleLookupPlayerIpCommand(), HandleLookupPoolCommand(), HandleLookupQuestCommand(), HandleLookupSkillCommand(), HandleLookupSpellCommand(), HandleLookupTaxiNodeCommand(), HandleLookupTeleCommand(), HandleLookupTitleCommand(), HandleMailBoxCommand(), HandleMaxSkillCommand(), HandleMmap(), HandleMmapLoadedTilesCommand(), HandleMmapLocCommand(), HandleMmapPathCommand(), HandleMmapStatsCommand(), HandleMmapTestArea(), HandleMmapTestHeight(), HandleModifyAgilityCommand(), HandleModifyArcaneCommand(), HandleModifyArenaCommand(), HandleModifyArmorCommand(), HandleModifyASpeedCommand(), HandleModifyBlockCommand(), HandleModifyBWalkCommand(), HandleModifyDodgeCommand(), HandleModifyDrunkCommand(), HandleModifyEnergyCommand(), HandleModifyFactionCommand(), HandleModifyFireCommand(), HandleModifyFlyCommand(), HandleModifyFrostCommand(), HandleModifyGenderCommand(), HandleModifyHolyCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyIntellectCommand(), HandleModifyManaCommand(), HandleModifyMeleeApCommand(), HandleModifyMeleeCritCommand(), HandleModifyMeleeHasteCommand(), HandleModifyMoneyCommand(), HandleModifyMorphCommand(), HandleModifyMountCommand(), HandleModifyNatureCommand(), HandleModifyParryCommand(), HandleModifyPhaseCommand(), HandleModifyRageCommand(), HandleModifyRangedApCommand(), HandleModifyRangedHasteCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifyShadowCommand(), HandleModifySpeedCommand(), HandleModifySpellCritCommand(), HandleModifySpellHasteCommand(), HandleModifySpellPowerCommand(), HandleModifySpiritCommand(), HandleModifyStaminaCommand(), HandleModifyStandStateCommand(), HandleModifyStrengthCommand(), HandleModifySwimCommand(), HandleModifyTalentCommand(), HandleMovegensCommand(), HandleMovespeedShowCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleNearGraveCommand(), HandleNotifyCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcAddWeaponCommand(), HandleNpcAIInfoCommand(), HandleNpcAllowMovementCommand(), HandleNpcChangeEntryCommand(), HandleNpcChangeLevelCommand(), HandleNpcDeleteCommand(), HandleNpcDelVendorItemCommand(), HandleNpcEvade(), HandleNpcFactionIdCommand(), HandleNpcFlagCommand(), HandleNpcFollowCommand(), HandleNpcFormationInfoCommand(), HandleNpcFormationResetCommand(), HandleNpcFormationSwitchCommand(), HandleNpcGroupInfoCommand(), HandleNpcInfoCommand(), HandleNpcListSpells(), HandleNpcMoveCommand(), HandleNpcNameCommand(), HandleNpcPlayEmoteCommand(), HandleNpcSayCommand(), HandleNpcSetModelCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcSetPhaseCommand(), HandleNpcShowLootCommand(), HandleNpcSpawnDistCommand(), HandleNpcSpawnTimeCommand(), HandleNpcSubNameCommand(), HandleNpcTameCommand(), HandleNpcTempSpawn(), HandleNpcTextEmoteCommand(), HandleNpcThreatCommand(), HandleNpcUnFollowCommand(), HandleNpcWhisperCommand(), HandleNpcYellCommand(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandlePInfoCommand(), HandlePoolInfoCommand(), HandlePoolListCommand(), HandlePoolSpawnsCommand(), HandlePrintMovement(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandleQuitCommand(), HandleRecallCommand(), HandleReloadAchievementCriteriaRequirementCommand(), HandleReloadAchievementRewardCommand(), HandleReloadAllAchievementCommand(), HandleReloadAllAreaCommand(), HandleReloadAllCommand(), HandleReloadAllEventAICommand(), HandleReloadAllGossipsCommand(), HandleReloadAllItemCommand(), HandleReloadAllLocalesCommand(), HandleReloadAllLootCommand(), HandleReloadAllNpcCommand(), HandleReloadAllQuestCommand(), HandleReloadAllScriptsCommand(), HandleReloadAllSpellCommand(), HandleReloadAreaTriggerTavernCommand(), HandleReloadAreaTriggerTeleportCommand(), HandleReloadBattleEventCommand(), HandleReloadCommandCommand(), HandleReloadConditionsCommand(), HandleReloadConfigCommand(), HandleReloadCreatureCooldownsCommand(), HandleReloadCreatureQuestInvRelationsCommand(), HandleReloadCreatureQuestRelationsCommand(), HandleReloadCreatureSpellLists(), HandleReloadCreaturesStatsCommand(), HandleReloadDBScriptsOnCreatureDeathCommand(), HandleReloadDBScriptsOnEventCommand(), HandleReloadDBScriptsOnGossipCommand(), HandleReloadDBScriptsOnGoUseCommand(), HandleReloadDBScriptsOnQuestEndCommand(), HandleReloadDBScriptsOnQuestStartCommand(), HandleReloadDBScriptsOnRelayCommand(), HandleReloadDBScriptsOnSpellCommand(), HandleReloadEventAIScriptsCommand(), HandleReloadEventAISummonsCommand(), HandleReloadExpectedSpamRecords(), HandleReloadGameGraveyardZoneCommand(), HandleReloadGameTeleCommand(), HandleReloadGOQuestInvRelationsCommand(), HandleReloadGOQuestRelationsCommand(), HandleReloadGossipMenuCommand(), HandleReloadItemConvertCommand(), HandleReloadItemEnchantementsCommand(), HandleReloadItemRequiredTragetCommand(), HandleReloadLocalesAchievementRewardCommand(), HandleReloadLocalesCreatureCommand(), HandleReloadLocalesGameobjectCommand(), HandleReloadLocalesGossipMenuOptionCommand(), HandleReloadLocalesItemCommand(), HandleReloadLocalesNpcTextCommand(), HandleReloadLocalesPageTextCommand(), HandleReloadLocalesPointsOfInterestCommand(), HandleReloadLocalesQuestCommand(), HandleReloadLocalesTrainerGreetingCommand(), HandleReloadLootTemplatesCreatureCommand(), HandleReloadLootTemplatesDisenchantCommand(), HandleReloadLootTemplatesFishingCommand(), HandleReloadLootTemplatesGameobjectCommand(), HandleReloadLootTemplatesItemCommand(), HandleReloadLootTemplatesMailCommand(), HandleReloadLootTemplatesMillingCommand(), HandleReloadLootTemplatesPickpocketingCommand(), HandleReloadLootTemplatesProspectingCommand(), HandleReloadLootTemplatesReferenceCommand(), HandleReloadLootTemplatesSkinningCommand(), HandleReloadLootTemplatesSpellCommand(), HandleReloadMailLevelRewardCommand(), HandleReloadMangosStringCommand(), HandleReloadNpcGossipCommand(), HandleReloadNpcTextCommand(), HandleReloadNpcTrainerCommand(), HandleReloadNpcVendorCommand(), HandleReloadPageTextsCommand(), HandleReloadPointsOfInterestCommand(), HandleReloadQuestAreaTriggersCommand(), HandleReloadQuestgiverGreetingCommand(), HandleReloadQuestgiverGreetingLocalesCommand(), HandleReloadQuestPOICommand(), HandleReloadQuestTemplateCommand(), HandleReloadReputationRewardRateCommand(), HandleReloadReputationSpilloverTemplateCommand(), HandleReloadReservedNameCommand(), HandleReloadSkillDiscoveryTemplateCommand(), HandleReloadSkillExtraItemTemplateCommand(), HandleReloadSkillFishingBaseLevelCommand(), HandleReloadSpawnGroupsCommand(), HandleReloadSpellAreaCommand(), HandleReloadSpellBonusesCommand(), HandleReloadSpellChainCommand(), HandleReloadSpellClickSpellsCommand(), HandleReloadSpellElixirCommand(), HandleReloadSpellLearnSpellCommand(), HandleReloadSpellPetAurasCommand(), HandleReloadSpellProcEventCommand(), HandleReloadSpellProcItemEnchantCommand(), HandleReloadSpellScriptTargetCommand(), HandleReloadSpellTargetPositionCommand(), HandleReloadSpellThreatsCommand(), HandleReloadStringIds(), HandleReloadTaxiShortcuts(), HandleReloadTrainerGreetingCommand(), HandleRepairitemsCommand(), HandleResetAchievementsCommand(), HandleResetAllCommand(), HandleResetHonorCommand(), HandleResetLevelCommand(), HandleResetModsCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetStatsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleRespawnCommand(), HandleReviveCommand(), HandleSaveAllCommand(), HandleSaveCommand(), HandleScourgeInvasionBattlesWonCommand(), HandleScourgeInvasionCommand(), HandleScourgeInvasionStartZone(), HandleScourgeInvasionStateCommand(), HandleSD2HelpCommand(), HandleSD2ScriptCommand(), HandleSendItemsCommand(), HandleSendMailCommand(), HandleSendMassItemsCommand(), HandleSendMassMailCommand(), HandleSendMassMoneyCommand(), HandleSendMessageCommand(), HandleSendMoneyCommand(), HandleServerCorpsesCommand(), HandleServerExitCommand(), HandleServerIdleRestartCommand(), HandleServerIdleShutDownCommand(), HandleServerInfoCommand(), HandleServerLogFilterCommand(), HandleServerLogLevelCommand(), HandleServerMotdCommand(), HandleServerPLimitCommand(), HandleServerResetAllRaidCommand(), HandleServerRestartCommand(), HandleServerSetMotdCommand(), HandleServerShutDownCancelCommand(), HandleServerShutDownCommand(), HandleSetSkillCommand(), HandleSetViewCommand(), HandleShowAreaCommand(), HandleShowGearScoreCommand(), HandleShowTemporarySpawnList(), HandleStableCommand(), HandleStartCommand(), HandleSunsReachReclamationCounterCommand(), HandleSunsReachReclamationPhaseCommand(), HandleSunsReachReclamationSubPhaseCommand(), HandleSunwellGateCommand(), HandleSunwellGateCounterCommand(), HandleTaxiCheatCommand(), HandleTeleAddCommand(), HandleTeleCommand(), HandleTeleDelCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTicketCommand(), HandleTicketDiscardCommand(), HandleTicketEscalateCommand(), HandleTicketGoCommand(), HandleTicketGoNameCommand(), HandleTicketNoteCommand(), HandleTicketReadCommand(), HandleTicketResolveCommand(), HandleTicketsCommand(), HandleTicketsListCommand(), HandleTicketSortCommand(), HandleTicketsQueueCommand(), HandleTicketWhisperCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleTitlesSwapCommand(), HandleTriggerActiveCommand(), HandleTriggerCommand(), HandleTriggerNearCommand(), HandleUnAuraCommand(), HandleUnBanAccountCommand(), HandleUnBanCharacterCommand(), HandleUnBanIPCommand(), HandleUnLearnCommand(), HandleUnmuteCommand(), HandleVariablePrint(), HandleWarEffortCommand(), HandleWarEffortCounterCommand(), HandleWarEffortPhaseCommand(), HandleWarnCharacterCommand(), HandleWaterwalkCommand(), HandleWhisperRestrictionCommand(), HandleWhispersCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), HandleWpShowCommand(), load_command_table, QueryResult::NextRow(), Database::Query(), SEC_ADMINISTRATOR, SEC_CONSOLE, SEC_GAMEMASTER, SEC_MODERATOR, SEC_PLAYER, SetDataForCommandInTable(), and WorldDatabase.
Referenced by ExecuteCommand(), FindCommand(), HandleCommandsCommand(), HandleHelpCommand(), ShowHelpForCommand(), and ShowHelpForSubCommands().
GetGameObjectWithGuid()
GameObject * ChatHandler::GetGameObjectWithGuid (uint32 lowguid, uint32 entry) const protected
Definition at line 3008 of file Chat.cpp.
References Map::GetGameObject(), WorldObject::GetMap(), WorldSession::GetPlayer(), HIGHGUID_GAMEOBJECT, and m_session.
Referenced by HandleGameObjectActivateCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectForcedDespawnCommand(), HandleGameObjectMoveCommand(), HandleGameObjectPhaseCommand(), and HandleGameObjectTurnCommand().
GetMangosString()
const char * ChatHandler::GetMangosString (int32 entry) const virtual
Reimplemented in CliHandler.
Definition at line 1115 of file Chat.cpp.
References WorldSession::GetMangosString(), and m_session.
Referenced by GetOnOffStr(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleBanInfoHelper(), HandleBanInfoIPCommand(), HandleChannelListCommand(), HandleChannelStaticCommand(), HandleCharacterTitlesCommand(), HandleCooldownClearCommand(), HandleDebugSpellCoefsCommand(), HandleDebugTaxiCommand(), HandleEventInfoCommand(), HandleEventListCommand(), HandleGameObjectAddCommand(), HandleGetValueHelper(), HandleGMListIngameCommand(), HandleGMVisibleCommand(), HandleGPSCommand(), HandleListAurasCommand(), HandleLookupEventCommand(), HandleLookupSkillCommand(), HandleLookupTitleCommand(), HandleModifyEnergyCommand(), HandleModifyMoneyCommand(), HandleModifyRepCommand(), HandleNamegoCommand(), HandleNearGraveCommand(), HandleNotifyCommand(), HandlePInfoCommand(), HandlePoolInfoCommand(), HandlerDebugModValueHelper(), HandleSetValueHelper(), HandleTeleNameCommand(), PrepareStringNpcOrGoSpawnInformation(), PSendSysMessage(), SendSysMessage(), ShowAchievementCriteriaListHelper(), ShowFactionListHelper(), ShowItemListHelper(), GMTicketMgr::ShowMOTD(), ShowQuestListHelper(), ShowSpellListHelper(), ShowTriggerListHelper(), and ShowTriggerTargetListHelper().
GetNameLink() [1/2]
std::string ChatHandler::GetNameLink () const protected virtual
Reimplemented in CliHandler.
Definition at line 1141 of file Chat.cpp.
References WorldSession::GetPlayer(), and m_session.
Referenced by HandleAccountSetGmLevelCommand(), HandleAddItemCommand(), HandleCharacterCustomizeCommand(), HandleCharacterLevel(), HandleCharacterRenameCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleCooldownClearCommand(), HandleDebugSpellModsCommand(), HandleExploreCheatCommand(), HandleGMFlyCommand(), HandleGMListIngameCommand(), HandleGonameCommand(), HandleGPSCommand(), HandleGroupgoCommand(), HandleKickPlayerCommand(), HandleLearnAllDefaultCommand(), HandleLearnCommand(), HandleModifyArenaCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleRecallCommand(), HandleRepairitemsCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleSendMessageCommand(), HandleSetSkillCommand(), HandleShowGearScoreCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleWaterwalkCommand(), and ModifyMountCommandHelper().
GetNameLink() [2/2]
std::string ChatHandler::GetNameLink (Player * chr) const protected
Definition at line 3615 of file Chat.cpp.
References WorldObject::GetName(), and playerLink().
GetOnOffStr()
const char * ChatHandler::GetOnOffStr (bool value) const
Definition at line 1120 of file Chat.cpp.
References GetMangosString(), LANG_OFF, and LANG_ON.
Referenced by CreatureEventAI::GetAIInformation(), ScriptedAI::GetAIInformation(), HandleGameObjectTargetCommand(), HandleServerLogFilterCommand(), and HandleWhispersCommand().
getSelectedCreature()
Creature * ChatHandler::getSelectedCreature () const protected
Definition at line 2344 of file Chat.cpp.
References Map::GetAnyTypeCreature(), WorldObject::GetMap(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), and m_session.
Referenced by HandleCastBackCommand(), HandleCastTargetCommand(), HandleComeToMeCommand(), HandleDebugByteFields(), HandleDebugGetLootRecipientCommand(), HandleDebugLootDropStats(), HandleDebugRespawnDynguid(), HandleDebugWaypoint(), HandleGUIDCommand(), HandleLevelUpCommand(), HandleModifyFactionCommand(), HandleNpcAddVendorItemCommand(), HandleNpcAIInfoCommand(), HandleNpcChangeLevelCommand(), HandleNpcDeleteCommand(), HandleNpcDelVendorItemCommand(), HandleNpcEvade(), HandleNpcFactionIdCommand(), HandleNpcFlagCommand(), HandleNpcFollowCommand(), HandleNpcFormationInfoCommand(), HandleNpcFormationResetCommand(), HandleNpcFormationSwitchCommand(), HandleNpcGroupInfoCommand(), HandleNpcInfoCommand(), HandleNpcListSpells(), HandleNpcMoveCommand(), HandleNpcPlayEmoteCommand(), HandleNpcSayCommand(), HandleNpcSetModelCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcSetPhaseCommand(), HandleNpcShowLootCommand(), HandleNpcSpawnDistCommand(), HandleNpcSpawnTimeCommand(), HandleNpcTameCommand(), HandleNpcTextEmoteCommand(), HandleNpcUnFollowCommand(), HandleNpcYellCommand(), HandlePrintMovement(), HandleResetTalentsCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), and HandleWpShowCommand().
getSelectedPlayer()
Player * ChatHandler::getSelectedPlayer () const protected
Definition at line 2317 of file Chat.cpp.
References WorldSession::GetPlayer(), Player::GetSelectionGuid(), m_session, and sObjectMgr.
Referenced by ExtractAccountId(), ExtractPlayerTarget(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleDebugGetItemStateCommand(), HandleDebugIncPacketHistory(), HandleDebugOutPacketHistory(), HandleDebugSpellModsCommand(), HandleExploreCheatCommand(), HandleGMFlyCommand(), HandleHideAreaCommand(), HandleHonorAddCommand(), HandleHonorUpdateCommand(), HandleInstanceListBindsCommand(), HandleInstanceUnbindCommand(), HandleLearnAllCommand(), HandleLearnAllRecipesCommand(), HandleLearnCommand(), HandleListTalentsCommand(), HandleLookupAchievementCommand(), HandleLookupFactionCommand(), HandleLookupQuestCommand(), HandleLookupSkillCommand(), HandleLookupSpellCommand(), HandleLookupTitleCommand(), HandleMaxSkillCommand(), HandleModifyArenaCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyDrunkCommand(), HandleModifyEnergyCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyMountCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandleSetSkillCommand(), HandleShowAreaCommand(), HandleShowGearScoreCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleTitlesSwapCommand(), HandleUnLearnCommand(), and HandleWaterwalkCommand().
getSelectedUnit()
Unit * ChatHandler::getSelectedUnit (bool self = true) const protected
Definition at line 2330 of file Chat.cpp.
References WorldSession::GetPlayer(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), and m_session.
Referenced by HandleAuraCommand(), HandleCastCommand(), HandleCastSelfCommand(), HandleCombatListCommand(), HandleCooldownClearCommand(), HandleCooldownListCommand(), HandleDamageCommand(), HandleDebugDbscript(), HandleDebugDbscriptSourced(), HandleDebugDbscriptTargeted(), HandleDebugGetValueByIndexCommand(), HandleDebugGetValueByNameCommand(), HandleDebugHaveAtClientCommand(), HandleDebugIsVisibleCommand(), HandleDebugListUpdateFieldsCommand(), HandleDebugModValueCommand(), HandleDebugMoveflags(), HandleDebugMovement(), HandleDebugObjectFlags(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugSendOpcodeCommand(), HandleDebugSendPoiCommand(), HandleDebugSetAuraStateCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpellVisual(), HandleDeMorphCommand(), HandleDieCommand(), HandleGetDistanceCommand(), HandleGetLosCommand(), HandleGMMountUpCommand(), HandleGPSCommand(), HandleHonorAddKillCommand(), HandleListAurasCommand(), HandleMmapPathCommand(), HandleMmapTestHeight(), HandleModifyMorphCommand(), HandleModifyPhaseCommand(), HandleModifyScaleCommand(), HandleModifyTalentCommand(), HandleMovegensCommand(), HandleMovespeedShowCommand(), HandleNpcChangeEntryCommand(), HandleNpcThreatCommand(), HandleResetModsCommand(), HandleRespawnCommand(), HandleSetViewCommand(), HandleUnAuraCommand(), and ModifyStatCommandHelper().
GetSession()
WorldSession* ChatHandler::GetSession () const inline
Definition at line 166 of file Chat.h.
References m_session.
Referenced by instance_molten_core::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), HandleAnticheatCheatinformCommand(), HandleAnticheatFingerprintListCommand(), HandleAnticheatSpaminformCommand(), HandleBagsCommand(), HandleChannelListCommand(), HandleChannelStaticCommand(), HandleCombatListCommand(), HandleDebugDbscript(), HandleDebugDbscriptGuided(), HandleDebugDbscriptSourced(), HandleDebugDbscriptTargeted(), HandleDebugPacketLog(), HandleDebugRespawnDynguid(), HandleDebugSpawnsList(), HandleDebugTransports(), HandleNpcTempSpawn(), HandleVariablePrint(), and NamreebAnticheat::SessionAnticheat::SendPlayerInfo().
GetSessionDbcLocale()
LocaleConstant ChatHandler::GetSessionDbcLocale () const protected virtual
Reimplemented in CliHandler.
Definition at line 3626 of file Chat.cpp.
References WorldSession::GetSessionDbcLocale(), and m_session.
Referenced by HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleCharacterAchievementsCommand(), HandleCharacterReputationCommand(), HandleCharacterTitlesCommand(), HandleGoZoneXYCommand(), HandleGPSCommand(), HandleInstanceListBindsCommand(), HandleInstanceUnbindCommand(), HandleLearnAllRecipesCommand(), HandleListAreaTriggerCommand(), HandleListAurasCommand(), HandleListTalentsCommand(), HandleLookupAchievementCommand(), HandleLookupAreaCommand(), HandleLookupFactionCommand(), HandleLookupItemSetCommand(), HandleLookupSkillCommand(), HandleLookupSpellCommand(), HandleLookupTaxiNodeCommand(), HandleLookupTitleCommand(), HandleModifyRepCommand(), HandlePoolListCommand(), HandlePoolSpawnsCommand(), HandleSetSkillCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), and ShowPlayerListHelper().
GetSessionDbLocaleIndex()
int ChatHandler::GetSessionDbLocaleIndex () const protected virtual
Reimplemented in CliHandler.
Definition at line 3631 of file Chat.cpp.
References WorldSession::GetSessionDbLocaleIndex(), and m_session.
Referenced by HandleLookupCreatureCommand(), HandleLookupItemCommand(), HandleLookupObjectCommand(), HandleLookupQuestCommand(), and HandleTriggerCommand().
HandleAccountCharactersCommand()
bool ChatHandler::HandleAccountCharactersCommand (char * args) protected
Output list of character for account.
Get the command line arguments
Get the characters for account id
Definition at line 6905 of file Level3.cpp.
References CharacterDatabase, ExtractAccountId(), Database::PQuery(), and ShowPlayerListHelper().
Referenced by getCommandTable().
HandleAccountCommand()
bool ChatHandler::HandleAccountCommand (char * args) protected
Definition at line 55 of file Level0.cpp.
References GetAccessLevel(), LANG_ACCOUNT_LEVEL, and PSendSysMessage().
Referenced by getCommandTable().
HandleAccountLockCommand()
bool ChatHandler::HandleAccountLockCommand (char * args) protected
Definition at line 248 of file Level0.cpp.
References ExtractOnOff(), GetAccountId(), LANG_COMMAND_ACCLOCKLOCKED, LANG_COMMAND_ACCLOCKUNLOCKED, LANG_RA_ONLY_COMMAND, LANG_USE_BOL, LoginDatabase, Database::PExecute(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleAccountPasswordCommand()
bool ChatHandler::HandleAccountPasswordCommand (char * args) protected
Definition at line 188 of file Level0.cpp.
References AOR_NAME_NOT_EXIST, AOR_OK, AOR_PASS_TOO_LONG, ExtractQuotedOrLiteralArg(), GetAccountId(), LANG_COMMAND_NOTCHANGEPASSWORD, LANG_COMMAND_PASSWORD, LANG_COMMAND_WRONGOLDPASSWORD, LANG_NEW_PASSWORDS_NOT_MATCH, LANG_PASSWORD_TOO_LONG, LANG_RA_ONLY_COMMAND, LogCommand(), sAccountMgr, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleAccountSetAddonCommand()
bool ChatHandler::HandleAccountSetAddonCommand (char * args) protected
Set/Unset the expansion level for an account.
Get the command line arguments
Definition at line 6921 of file Level3.cpp.
References ExtractAccountId(), ExtractOptNotLastArg(), ExtractUInt32(), GetAccountId(), HasLowerSecurityAccount(), LANG_ACCOUNT_SETADDON, LoginDatabase, Database::PExecute(), and PSendSysMessage().
Referenced by getCommandTable().
HandleAccountSetGmLevelCommand()
bool ChatHandler::HandleAccountSetGmLevelCommand (char * args) protected
only target player different from self allowed
can set security level only for target with less security and to less security that we have This will reject self apply by specify account name
account can't set security to same or grater level, need more power GM or console
Definition at line 1145 of file Level3.cpp.
References ChatHandler(), ExtractAccountId(), ExtractInt32(), ExtractOptNotLastArg(), GetAccessLevel(), GetAccountId(), GetNameLink(), Player::GetSession(), HasLowerSecurityAccount(), LANG_BAD_VALUE, LANG_YOU_CHANGE_SECURITY, LANG_YOURS_SECURITY_CHANGED, LANG_YOURS_SECURITY_IS_LOW, LoginDatabase, Database::PExecute(), PSendSysMessage(), SEC_ADMINISTRATOR, SendSysMessage(), WorldSession::SetSecurity(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleAccountSetPasswordCommand()
bool ChatHandler::HandleAccountSetPasswordCommand (char * args) protected
Set password for account.
Get the command line arguments
can set password only for target with less security This is also reject self apply in fact
Definition at line 1197 of file Level3.cpp.
References AOR_NAME_NOT_EXIST, AOR_OK, AOR_PASS_TOO_LONG, ExtractAccountId(), ExtractQuotedOrLiteralArg(), HasLowerSecurityAccount(), LANG_ACCOUNT_NOT_EXIST, LANG_COMMAND_NOTCHANGEPASSWORD, LANG_COMMAND_PASSWORD, LANG_NEW_PASSWORDS_NOT_MATCH, LANG_PASSWORD_TOO_LONG, LogCommand(), PSendSysMessage(), sAccountMgr, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleAchievementAddCommand()
bool ChatHandler::HandleAchievementAddCommand (char * args) protected
Definition at line 1320 of file Level3.cpp.
References ACHIEVEMENT_FLAG_COUNTER, CompletedAchievementData::date, ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractUint32KeyFromLink(), AchievementEntry::flags, Player::GetAchievementMgr(), AchievementMgr::GetCompleteData(), AchievementMgr::GetCriteriaProgressMaxCounter(), GetSessionDbcLocale(), AchievementEntry::ID, AchievementMgr::IsCompletedCriteria(), LANG_ACHIEVEMENT_NOT_EXIST, AchievementMgr::PROGRESS_SET, PSendSysMessage(), sAchievementMgr, sAchievementStore, AchievementMgr::SetCriteriaProgress(), SetSentErrorMessage(), and ShowAchievementListHelper().
Referenced by getCommandTable().
HandleAchievementCommand()
bool ChatHandler::HandleAchievementCommand (char * args) protected
Definition at line 1278 of file Level3.cpp.
References CompletedAchievementData::date, ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractUint32KeyFromLink(), Player::GetAchievementMgr(), AchievementMgr::GetCompleteData(), getSelectedPlayer(), GetSessionDbcLocale(), AchievementEntry::ID, LANG_ACHIEVEMENT_NOT_EXIST, LANG_COMMAND_ACHIEVEMENT_CRITERIA, PSendSysMessage(), sAchievementMgr, sAchievementStore, SendSysMessage(), SetSentErrorMessage(), ShowAchievementCriteriaListHelper(), and ShowAchievementListHelper().
Referenced by getCommandTable().
HandleAchievementCriteriaAddCommand()
bool ChatHandler::HandleAchievementCriteriaAddCommand (char * args) protected
Definition at line 1394 of file Level3.cpp.
References ExtractArg(), ExtractOptUInt32(), ExtractPlayerTarget(), ExtractUint32KeyFromLink(), Player::GetAchievementMgr(), AchievementMgr::GetCriteriaProgressCounter(), AchievementMgr::GetCriteriaProgressMaxCounter(), getSelectedPlayer(), GetSessionDbcLocale(), AchievementMgr::IsCompletedCriteria(), LANG_ACHIEVEMENT_CRITERIA_NOT_EXIST, AchievementMgr::PROGRESS_SET, PSendSysMessage(), AchievementCriteriaEntry::referredAchievement, sAchievementCriteriaStore, sAchievementStore, AchievementMgr::SetCriteriaProgress(), SetSentErrorMessage(), and ShowAchievementCriteriaListHelper().
Referenced by getCommandTable().
HandleAchievementCriteriaRemoveCommand()
bool ChatHandler::HandleAchievementCriteriaRemoveCommand (char * args) protected
Definition at line 1461 of file Level3.cpp.
References ExtractArg(), ExtractOptUInt32(), ExtractPlayerTarget(), ExtractUint32KeyFromLink(), Player::GetAchievementMgr(), AchievementMgr::GetCriteriaProgressCounter(), AchievementMgr::GetCriteriaProgressMaxCounter(), getSelectedPlayer(), GetSessionDbcLocale(), LANG_ACHIEVEMENT_CRITERIA_NOT_EXIST, AchievementMgr::PROGRESS_SET, PSendSysMessage(), AchievementCriteriaEntry::referredAchievement, sAchievementCriteriaStore, sAchievementStore, AchievementMgr::SetCriteriaProgress(), SetSentErrorMessage(), and ShowAchievementCriteriaListHelper().
Referenced by getCommandTable().
HandleAchievementRemoveCommand()
bool ChatHandler::HandleAchievementRemoveCommand (char * args) protected
Definition at line 1362 of file Level3.cpp.
References CompletedAchievementData::date, ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractUint32KeyFromLink(), Player::GetAchievementMgr(), AchievementMgr::GetCompleteData(), GetSessionDbcLocale(), AchievementEntry::ID, LANG_ACHIEVEMENT_NOT_EXIST, AchievementMgr::PROGRESS_SET, PSendSysMessage(), sAchievementMgr, sAchievementStore, AchievementMgr::SetCriteriaProgress(), SetSentErrorMessage(), and ShowAchievementListHelper().
Referenced by getCommandTable().
HandleAddCharacterNoteCommand()
bool ChatHandler::HandleAddCharacterNoteCommand (char * args) protected
Definition at line 5554 of file Level3.cpp.
References ExtractPlayerTarget(), ExtractQuotedOrLiteralArg(), WorldSession::GetAccountId(), WorldSession::GetPlayerName(), Player::GetSession(), LANG_PLAYER_NOT_FOUND, m_session, PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, and sWorld.
Referenced by getCommandTable().
HandleAddItemCommand()
bool ChatHandler::HandleAddItemCommand (char * args) protected
Definition at line 2090 of file Level3.cpp.
References Player::CanStoreNewItem(), Player::DestroyItemCount(), DETAIL_LOG, EQUIP_ERR_OK, Database::escape_string(), ExtractKeyFromLink(), ExtractOptInt32(), ExtractUInt32(), QueryResult::Fetch(), Item::GenerateItemRandomPropertyId(), Player::GetItemByPos(), ObjectMgr::GetItemPrototype(), GetMangosString(), GetNameLink(), WorldSession::GetPlayer(), getSelectedPlayer(), Field::GetUInt16(), LANG_ADDITEM, LANG_COMMAND_COULDNOTFIND, LANG_COMMAND_ITEMIDINVALID, LANG_ITEM_CANNOT_CREATE, LANG_REMOVEITEM, m_session, NULL_BAG, NULL_SLOT, Database::PQuery(), PSendSysMessage(), Player::SendNewItem(), Item::SetBinding(), SetSentErrorMessage(), Player::StoreNewItem(), and WorldDatabase.
Referenced by getCommandTable().
HandleAddItemSetCommand()
bool ChatHandler::HandleAddItemSetCommand (char * args) protected
Definition at line 2176 of file Level3.cpp.
References Player::CanStoreNewItem(), DETAIL_LOG, EQUIP_ERR_OK, ExtractUint32KeyFromLink(), GetMangosString(), SQLStorageBase::GetMaxEntry(), WorldSession::GetPlayer(), getSelectedPlayer(), ItemPrototype::ItemId, ItemPrototype::ItemSet, LANG_ADDITEMSET, LANG_ITEM_CANNOT_CREATE, LANG_NO_ITEMS_FROM_ITEMSET_FOUND, SQLStorage::LookupEntry(), m_session, NULL_BAG, NULL_SLOT, PSendSysMessage(), Player::SendEquipError(), Player::SendNewItem(), Item::SetBinding(), SetSentErrorMessage(), sItemStorage, and Player::StoreNewItem().
Referenced by getCommandTable().
HandleAnnounceCommand()
bool ChatHandler::HandleAnnounceCommand (char * args) protected
Definition at line 130 of file Level1.cpp.
References LANG_SYSTEMMESSAGE, and sWorld.
Referenced by getCommandTable().
HandleArenaDataReset()
bool ChatHandler::HandleArenaDataReset (char * args) protected
Definition at line 7257 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), sBattleGroundMgr, and SendSysMessage().
Referenced by getCommandTable().
HandleArenaFlushPointsCommand()
bool ChatHandler::HandleArenaFlushPointsCommand (char * args) protected
Definition at line 7238 of file Level3.cpp.
References sBattleGroundMgr.
Referenced by getCommandTable().
HandleArenaSeasonRewardsCommand()
bool ChatHandler::HandleArenaSeasonRewardsCommand (char * args) protected
Definition at line 7244 of file Level3.cpp.
References ExtractUInt32(), and sBattleGroundMgr.
Referenced by getCommandTable().
HandleArenaTeamPointSet()
bool ChatHandler::HandleArenaTeamPointSet (char * args) protected
Definition at line 7271 of file Level3.cpp.
References ExtractQuotedArg(), ExtractUInt32(), PSendSysMessage(), ArenaTeam::SaveToDB(), ArenaTeam::SetRatingForAll(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleAuctionAllianceCommand()
bool ChatHandler::HandleAuctionAllianceCommand (char * args) protected
Definition at line 4552 of file Level3.cpp.
References ALLIANCE, WorldSession::GetPlayer(), Player::GetTeam(), m_session, WorldSession::SendAuctionHello(), and Player::SetAuctionAccessMode().
Referenced by getCommandTable().
HandleAuctionCommand()
bool ChatHandler::HandleAuctionCommand (char * args) protected
Definition at line 4573 of file Level3.cpp.
References WorldSession::GetPlayer(), m_session, WorldSession::SendAuctionHello(), and Player::SetAuctionAccessMode().
Referenced by getCommandTable().
HandleAuctionGoblinCommand()
bool ChatHandler::HandleAuctionGoblinCommand (char * args) protected
Definition at line 4566 of file Level3.cpp.
References WorldSession::GetPlayer(), m_session, WorldSession::SendAuctionHello(), and Player::SetAuctionAccessMode().
Referenced by getCommandTable().
HandleAuctionHordeCommand()
bool ChatHandler::HandleAuctionHordeCommand (char * args) protected
Definition at line 4559 of file Level3.cpp.
References WorldSession::GetPlayer(), Player::GetTeam(), HORDE, m_session, WorldSession::SendAuctionHello(), and Player::SetAuctionAccessMode().
Referenced by getCommandTable().
HandleAuctionItemCommand()
bool ChatHandler::HandleAuctionItemCommand (char * args) protected
Definition at line 4581 of file Level3.cpp.
References AuctionHouseObject::AddAuction(), Item::CreateItem(), ExtractArg(), ExtractLiteralArg(), ExtractOptUInt32(), ExtractUInt32(), ObjectMgr::GetItemPrototype(), ItemPrototype::GetMaxStackSize(), LANG_COMMAND_INVALID_ITEM_COUNT, LANG_COMMAND_ITEMIDINVALID, MANGOS_ASSERT, ItemPrototype::MaxCount, MIN_AUCTION_TIME, PSendSysMessage(), sAuctionHouseStore, sAuctionMgr, and SetSentErrorMessage().
Referenced by getCommandTable().
HandleAuraCommand()
bool ChatHandler::HandleAuraCommand (char * args) protected
Definition at line 3861 of file Level3.cpp.
References SpellAuraHolder::AddAura(), Unit::AddSpellAuraHolder(), SpellEntry::CalculateSimpleValue(), CreateAura(), CreateSpellAuraHolder(), SpellEntry::Effect, ExtractSpellIdFromLink(), WorldSession::GetPlayer(), getSelectedUnit(), IsAreaAuraEffect(), IsSpellAppliesAura(), IsSpellHaveEffect(), LANG_SELECT_CHAR_OR_CREATURE, LANG_SPELL_NO_HAVE_AURAS, SQLStorage::LookupEntry(), m_session, MAX_EFFECT_INDEX, MAX_SPELL_EFFECTS, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), SpellAuraHolder::SetState(), SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELLAURAHOLDER_STATE_READY, and sSpellTemplate.
Referenced by getCommandTable().
HandleBagsCommand()
bool ChatHandler::HandleBagsCommand (char * args) protected
Definition at line 5457 of file Level2.cpp.
References Player::CanStoreNewItem(), EQUIP_ERR_OK, Item::GenerateItemRandomPropertyId(), WorldSession::GetPlayer(), GetSession(), NULL_BAG, NULL_SLOT, Player::SendNewItem(), and Player::StoreNewItem().
Referenced by getCommandTable().
HandleBanAccountCommand()
bool ChatHandler::HandleBanAccountCommand (char * args) protected
Definition at line 5604 of file Level3.cpp.
References BAN_ACCOUNT, and HandleBanHelper().
Referenced by getCommandTable().
HandleBanCharacterCommand()
bool ChatHandler::HandleBanCharacterCommand (char * args) protected
Definition at line 5609 of file Level3.cpp.
References BAN_CHARACTER, and HandleBanHelper().
Referenced by getCommandTable().
HandleBanHelper()
bool ChatHandler::HandleBanHelper (BanMode mode, char * args) protected
Definition at line 5619 of file Level3.cpp.
References BAN_ACCOUNT, BAN_CHARACTER, BAN_IP, BAN_NOTFOUND, BAN_SUCCESS, BAN_SYNTAX_ERROR, ExtractArg(), WorldSession::GetPlayerName(), IsIPAddress(), LANG_ACCOUNT_NOT_EXIST, LANG_BAN_NOTFOUND, LANG_BAN_YOUBANNED, LANG_BAN_YOUPERMBANNED, LANG_PLAYER_NOT_FOUND, m_session, normalizePlayerName(), AccountMgr::normalizeString(), PSendSysMessage(), secsToTimeString(), SendSysMessage(), SetSentErrorMessage(), sWorld, and TimeStringToSecs().
Referenced by HandleBanAccountCommand(), HandleBanCharacterCommand(), and HandleBanIPCommand().
HandleBanInfoAccountCommand()
bool ChatHandler::HandleBanInfoAccountCommand (char * args) protected
Definition at line 5756 of file Level3.cpp.
References ExtractAccountId(), and HandleBanInfoHelper().
Referenced by getCommandTable().
HandleBanInfoCharacterCommand()
bool ChatHandler::HandleBanInfoCharacterCommand (char * args) protected
Definition at line 5769 of file Level3.cpp.
References ExtractPlayerTarget(), WorldSession::GetAccountId(), Player::GetSession(), HandleBanInfoHelper(), LANG_BANINFO_NOCHARACTER, PSendSysMessage(), sAccountMgr, and sObjectMgr.
Referenced by getCommandTable().
HandleBanInfoHelper()
bool ChatHandler::HandleBanInfoHelper (uint32 accountid, char const * accountname) protected
Definition at line 5788 of file Level3.cpp.
References QueryResult::Fetch(), GetMangosString(), Field::GetString(), Field::GetUInt64(), Field::IsNULL(), LANG_BANINFO_BANHISTORY, LANG_BANINFO_HISTORYENTRY, LANG_BANINFO_INFINITE, LANG_BANINFO_NO, LANG_BANINFO_NOACCOUNTBAN, LANG_BANINFO_YES, LoginDatabase, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), and secsToTimeString().
Referenced by HandleBanInfoAccountCommand(), and HandleBanInfoCharacterCommand().
HandleBanInfoIPCommand()
bool ChatHandler::HandleBanInfoIPCommand (char * args) protected
Definition at line 5827 of file Level3.cpp.
References Database::escape_string(), ExtractQuotedOrLiteralArg(), QueryResult::Fetch(), GetMangosString(), Field::GetUInt64(), IsIPAddress(), LANG_BANINFO_INFINITE, LANG_BANINFO_IPENTRY, LANG_BANINFO_NEVER, LANG_BANINFO_NOIP, LoginDatabase, Database::PQuery(), PSendSysMessage(), and secsToTimeString().
Referenced by getCommandTable().
HandleBanIPCommand()
bool ChatHandler::HandleBanIPCommand (char * args) protected
Definition at line 5614 of file Level3.cpp.
References BAN_IP, and HandleBanHelper().
Referenced by getCommandTable().
HandleBankCommand()
bool ChatHandler::HandleBankCommand (char * args) protected
Definition at line 4670 of file Level3.cpp.
References Object::GetObjectGuid(), WorldSession::GetPlayer(), m_session, and WorldSession::SendShowBank().
Referenced by getCommandTable().
HandleBanListAccountCommand()
bool ChatHandler::HandleBanListAccountCommand (char * args) protected
Definition at line 5879 of file Level3.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), Database::Execute(), ExtractLiteralArg(), HandleBanListHelper(), LANG_BANLIST_NOACCOUNT, LoginDatabase, Database::PQuery(), PSendSysMessage(), and Database::Query().
Referenced by getCommandTable().
HandleBanListCharacterCommand()
bool ChatHandler::HandleBanListCharacterCommand (char * args) protected
Definition at line 5859 of file Level3.cpp.
References _CONCAT3_, _LIKE_, CharacterDatabase, Database::escape_string(), Database::Execute(), ExtractLiteralArg(), HandleBanListHelper(), LANG_BANLIST_NOCHARACTER, LoginDatabase, Database::PQuery(), and PSendSysMessage().
Referenced by getCommandTable().
HandleBanListHelper()
bool ChatHandler::HandleBanListHelper (QueryResult * result) protected
Definition at line 5910 of file Level3.cpp.
References QueryResult::Fetch(), Field::GetCppString(), QueryResult::GetFieldCount(), Field::GetString(), Field::GetUInt32(), Field::GetUInt64(), LANG_BANLIST_ACCOUNTS, LANG_BANLIST_ACCOUNTS_HEADER, LANG_BANLIST_MATCHINGACCOUNT, LoginDatabase, m_session, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), sAccountMgr, secsToTimeString(), and SendSysMessage().
Referenced by HandleBanListAccountCommand(), and HandleBanListCharacterCommand().
HandleBanListIPCommand()
bool ChatHandler::HandleBanListIPCommand (char * args) protected
Definition at line 5991 of file Level3.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), Database::Execute(), ExtractLiteralArg(), QueryResult::Fetch(), Field::GetString(), Field::GetUInt64(), LANG_BANLIST_IPS, LANG_BANLIST_IPS_HEADER, LANG_BANLIST_MATCHINGIP, LANG_BANLIST_NOIP, LoginDatabase, m_session, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), Database::Query(), and SendSysMessage().
Referenced by getCommandTable().
HandleBattlegroundStartCommand()
bool ChatHandler::HandleBattlegroundStartCommand (char * args) protected
Definition at line 5478 of file Level2.cpp.
References Player::GetBattleGround(), BattleGround::GetInstanceId(), BattleGround::GetName(), WorldSession::GetPlayer(), m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and BattleGround::SetStartDelayTime().
Referenced by getCommandTable().
HandleBattlegroundStopCommand()
bool ChatHandler::HandleBattlegroundStopCommand (char * args) protected
Definition at line 5499 of file Level2.cpp.
References BattleGround::EndBattleGround(), Player::GetBattleGround(), BattleGround::GetInstanceId(), BattleGround::GetName(), WorldSession::GetPlayer(), m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and TEAM_NONE.
Referenced by getCommandTable().
HandleCastBackCommand()
bool ChatHandler::HandleCastBackCommand (char * args) protected
Definition at line 6500 of file Level3.cpp.
References Unit::CastSpell(), ExtractLiteralArg(), ExtractSpellIdFromLink(), WorldSession::GetPlayer(), getSelectedCreature(), LANG_SELECT_CHAR_OR_CREATURE, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SendSysMessage(), Unit::SetFacingToObject(), SetSentErrorMessage(), SPELL_CAST_OK, sSpellTemplate, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleCastCommand()
bool ChatHandler::HandleCastCommand (char * args) protected
Definition at line 6463 of file Level3.cpp.
References Unit::CastSpell(), ExtractLiteralArg(), ExtractSpellIdFromLink(), WorldSession::GetPlayer(), getSelectedUnit(), SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SetSentErrorMessage(), SPELL_CAST_OK, sSpellTemplate, SpellEntry::Targets, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleCastDistCommand()
bool ChatHandler::HandleCastDistCommand (char * args) protected
Definition at line 6530 of file Level3.cpp.
References Unit::CastSpell(), ExtractFloat(), ExtractLiteralArg(), ExtractSpellIdFromLink(), WorldObject::GetClosePoint(), WorldSession::GetPlayer(), SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SetSentErrorMessage(), SPELL_CAST_OK, sSpellTemplate, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleCastSelfCommand()
bool ChatHandler::HandleCastSelfCommand (char * args) protected
Definition at line 6626 of file Level3.cpp.
References Unit::CastSpell(), ExtractLiteralArg(), ExtractSpellIdFromLink(), WorldSession::GetPlayer(), getSelectedUnit(), SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, LANG_SELECT_CHAR_OR_CREATURE, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), SPELL_CAST_OK, sSpellTemplate, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleCastTargetCommand()
bool ChatHandler::HandleCastTargetCommand (char * args) protected
Definition at line 6568 of file Level3.cpp.
References Unit::CastSpell(), ExtractLiteralArg(), ExtractSpellIdFromLink(), WorldSession::GetPlayer(), getSelectedCreature(), Unit::GetVictim(), LANG_SELECT_CHAR_OR_CREATURE, LANG_SELECTED_TARGET_NOT_HAVE_VICTIM, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SendSysMessage(), Unit::SetFacingToObject(), SetSentErrorMessage(), SPELL_CAST_OK, sSpellTemplate, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleChangeWeatherCommand()
bool ChatHandler::HandleChangeWeatherCommand (char * args) protected
Definition at line 4690 of file Level3.cpp.
References CONFIG_BOOL_WEATHER, ExtractFloat(), ExtractUInt32(), WorldObject::GetMap(), WorldSession::GetPlayer(), WorldObject::GetZoneId(), Weather::IsValidWeatherType(), LANG_NO_WEATHER, LANG_WEATHER_DISABLED, m_session, SendSysMessage(), SetSentErrorMessage(), Map::SetWeather(), sWeatherMgr, and sWorld.
Referenced by getCommandTable().
HandleChannelListCommand()
bool ChatHandler::HandleChannelListCommand (char * args) protected
Definition at line 2370 of file Level1.cpp.
References channelMgr(), ExtractLiteralArg(), ExtractUInt32(), ChannelMgr::GetChannels(), GetMangosString(), Channel::GetNumPlayers(), GetSession(), LANG_CHANNEL_CUSTOM_DETAILS_PASSWORD, LANG_CHANNEL_CUSTOM_DETAILS_STATIC, LANG_COMMAND_CHANNELS_LIST_HEADER, LANG_COMMAND_CHANNELS_NO_CHANNELS, and PSendSysMessage().
Referenced by getCommandTable().
HandleChannelStaticCommand()
bool ChatHandler::HandleChannelStaticCommand (char * args) protected
Definition at line 2420 of file Level1.cpp.
References channelMgr(), ExtractLiteralArg(), ExtractOnOff(), ChannelMgr::GetChannel(), GetMangosString(), Channel::GetName(), Channel::GetPassword(), WorldSession::GetPlayer(), GetSession(), Player::GetTeam(), Channel::IsStatic(), LANG_COMMAND_CHANNEL_STATIC_GLOBAL, LANG_COMMAND_CHANNEL_STATIC_PASSWORD, LANG_COMMAND_CHANNEL_STATIC_SUCCESS, LANG_OFF, LANG_ON, PSendSysMessage(), SetSentErrorMessage(), and Channel::SetStatic().
Referenced by getCommandTable().
HandleCharacterAchievementsCommand()
bool ChatHandler::HandleCharacterAchievementsCommand (char * args) protected
Definition at line 1546 of file Level2.cpp.
References ExtractPlayerTarget(), Player::GetAchievementMgr(), AchievementMgr::GetCompletedAchievements(), GetSessionDbcLocale(), sAchievementStore, and ShowAchievementListHelper().
Referenced by getCommandTable().
HandleCharacterCustomizeCommand()
bool ChatHandler::HandleCharacterCustomizeCommand (char * args) protected
Definition at line 3836 of file Level2.cpp.
References AT_LOGIN_CUSTOMIZE, CharacterDatabase, ExtractPlayerTarget(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), GetNameLink(), LANG_CUSTOMIZE_PLAYER, LANG_CUSTOMIZE_PLAYER_GUID, Database::PExecute(), playerLink(), PSendSysMessage(), and Player::SetAtLoginFlag().
Referenced by getCommandTable().
HandleCharacterLevel()
void ChatHandler::HandleCharacterLevel (Player * player, ObjectGuid player_guid, uint32 oldlevel, uint32 newlevel) protected
Definition at line 4344 of file Level3.cpp.
References CharacterDatabase, ChatHandler(), ObjectGuid::GetCounter(), GetNameLink(), Player::GiveLevel(), Player::InitTalentForLevel(), LANG_YOURS_LEVEL_DOWN, LANG_YOURS_LEVEL_PROGRESS_RESET, LANG_YOURS_LEVEL_UP, needReportToTarget(), Database::PExecute(), PLAYER_XP, and Object::SetUInt32Value().
Referenced by HandleCharacterLevelCommand(), and HandleLevelUpCommand().
HandleCharacterLevelCommand()
bool ChatHandler::HandleCharacterLevelCommand (char * args) protected
Definition at line 4369 of file Level3.cpp.
References ExtractArg(), ExtractInt32(), ExtractOptNotLastArg(), ExtractPlayerTarget(), Unit::GetLevel(), Player::GetLevelFromDB(), WorldSession::GetPlayer(), HandleCharacterLevel(), LANG_YOU_CHANGE_LVL, m_session, playerLink(), PSendSysMessage(), and STRONG_MAX_LEVEL.
Referenced by getCommandTable().
HandleCharacterRenameCommand()
bool ChatHandler::HandleCharacterRenameCommand (char * args) protected
Definition at line 3802 of file Level2.cpp.
References AT_LOGIN_RENAME, CharacterDatabase, ExtractPlayerTarget(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), GetNameLink(), HasLowerSecurity(), LANG_RENAME_PLAYER, LANG_RENAME_PLAYER_GUID, Database::PExecute(), playerLink(), PSendSysMessage(), and Player::SetAtLoginFlag().
Referenced by getCommandTable().
HandleCharacterReputationCommand()
bool ChatHandler::HandleCharacterReputationCommand (char * args) protected
Definition at line 3861 of file Level2.cpp.
References ExtractPlayerTarget(), Player::GetReputationMgr(), GetSessionDbcLocale(), ReputationMgr::GetStateList(), sFactionStore, and ShowFactionListHelper().
Referenced by getCommandTable().
HandleCharacterTitlesCommand()
bool ChatHandler::HandleCharacterTitlesCommand (char * args) protected
Definition at line 5139 of file Level2.cpp.
References CharTitlesEntry::bit_index, ExtractPlayerTarget(), GetMangosString(), WorldObject::GetName(), GetSessionDbcLocale(), Object::GetUInt32Value(), Player::HasTitle(), LANG_ACTIVE, LANG_KNOWN, LANG_TITLE_LIST_CHAT, LANG_TITLE_LIST_CONSOLE, localeNames, m_session, CharTitlesEntry::name, PLAYER_CHOSEN_TITLE, PSendSysMessage(), and sCharTitlesStore.
Referenced by getCommandTable().
HandleCombatListCommand()
bool ChatHandler::HandleCombatListCommand (char * args) protected
Definition at line 4175 of file Level2.cpp.
References Unit::GetCombatManager(), CombatManager::GetCombatTimer(), Object::GetEntry(), Object::GetGUIDLow(), Unit::getHostileRefManager(), WorldObject::GetName(), WorldSession::GetPlayer(), getSelectedUnit(), GetSession(), PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleCombatStopCommand()
bool ChatHandler::HandleCombatStopCommand (char * args) protected
Definition at line 4161 of file Level2.cpp.
References Unit::CombatStopWithPets(), ExtractPlayerTarget(), and HasLowerSecurity().
Referenced by getCommandTable().
HandleComeToMeCommand()
bool ChatHandler::HandleComeToMeCommand (char * args) protected
Definition at line 6609 of file Level3.cpp.
References Unit::GetMotionMaster(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), getSelectedCreature(), LANG_SELECT_CREATURE, m_session, MotionMaster::MovePoint(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleCommandsCommand()
bool ChatHandler::HandleCommandsCommand (char * args) protected
Definition at line 49 of file Level0.cpp.
References getCommandTable(), and ShowHelpForCommand().
Referenced by getCommandTable().
HandleCooldownClearArenaCommand()
bool ChatHandler::HandleCooldownClearArenaCommand (char * args) protected
Definition at line 1705 of file Level3.cpp.
References GetNameLink(), getSelectedPlayer(), LANG_PLAYER_NOT_FOUND, LANG_REMOVEALL_COOLDOWN, PSendSysMessage(), Player::RemoveArenaSpellCooldowns(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleCooldownClearClientSideCommand()
bool ChatHandler::HandleCooldownClearClientSideCommand (char * args) protected
Definition at line 1688 of file Level3.cpp.
References GetNameLink(), getSelectedPlayer(), LANG_PLAYER_NOT_FOUND, LANG_REMOVEALL_COOLDOWN, PSendSysMessage(), Player::RemoveAllCooldowns(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleCooldownClearCommand()
bool ChatHandler::HandleCooldownClearCommand (char * args) protected
Definition at line 1646 of file Level3.cpp.
References ExtractSpellIdFromLink(), GetMangosString(), GetNameLink(), WorldObject::GetNameStr(), WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), LANG_REMOVE_COOLDOWN, LANG_REMOVEALL_COOLDOWN, LANG_SELECT_CHAR_OR_CREATURE, LANG_UNKNOWN_SPELL, LANG_YOU, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), WorldObject::RemoveAllCooldowns(), WorldObject::RemoveSpellCooldown(), SendSysMessage(), SetSentErrorMessage(), sSpellTemplate, and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleCooldownListCommand()
bool ChatHandler::HandleCooldownListCommand (char * args) protected
Definition at line 1631 of file Level3.cpp.
References getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, WorldObject::PrintCooldownList(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDamageCommand()
bool ChatHandler::HandleDamageCommand (char * args) protected
Definition at line 3736 of file Level3.cpp.
References Unit::CalcArmorReducedDamage(), Unit::CalculateDamageAbsorbAndResist(), Unit::DealDamage(), Unit::DealDamageMods(), DIRECT_DAMAGE, ExtractInt32(), ExtractSpellIdFromLink(), ExtractUInt32(), WorldSession::GetPlayer(), getSelectedUnit(), Player::GetSelectionGuid(), HITINFO_NORMALSWING2, Unit::IsAlive(), LANG_SELECT_CHAR_OR_CREATURE, SQLStorage::LookupEntry(), m_session, MAX_SPELL_SCHOOL, Unit::SendAttackStateUpdate(), SendSysMessage(), SetSentErrorMessage(), SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, Unit::SpellNonMeleeDamageLog(), sSpellTemplate, and VICTIMSTATE_NORMAL.
Referenced by getCommandTable().
HandleDebugAnimCommand()
bool ChatHandler::HandleDebugAnimCommand (char * args) protected
Definition at line 782 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), Unit::HandleEmoteCommand(), and m_session.
Referenced by getCommandTable().
HandleDebugAreaTriggersCommand()
bool ChatHandler::HandleDebugAreaTriggersCommand (char * args) protected
Definition at line 343 of file debugcmds.cpp.
References WorldSession::GetPlayer(), Player::isDebuggingAreaTriggers(), LANG_DEBUG_AREATRIGGER_OFF, LANG_DEBUG_AREATRIGGER_ON, m_session, PSendSysMessage(), and Player::SetDebuggingAreaTriggers().
Referenced by getCommandTable().
HandleDebugArenaCommand()
bool ChatHandler::HandleDebugArenaCommand (char * args) protected
Definition at line 748 of file debugcmds.cpp.
References sBattleGroundMgr.
Referenced by getCommandTable().
HandleDebugBattlegroundCommand()
bool ChatHandler::HandleDebugBattlegroundCommand (char * args) protected
Definition at line 742 of file debugcmds.cpp.
References sBattleGroundMgr.
Referenced by getCommandTable().
HandleDebugBattlegroundStartCommand()
bool ChatHandler::HandleDebugBattlegroundStartCommand (char * args) protected
HandleDebugByteFields()
bool ChatHandler::HandleDebugByteFields (char * args) protected
Definition at line 1486 of file debugcmds.cpp.
References ExtractInt32(), ExtractUInt32(), getSelectedCreature(), Object::RemoveByteFlag(), Object::SetByteFlag(), UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_1, and UNIT_FIELD_BYTES_2.
Referenced by getCommandTable().
HandleDebugChatFreezeCommand()
bool ChatHandler::HandleDebugChatFreezeCommand (char * args) protected
Definition at line 1723 of file debugcmds.cpp.
References Object::GetObjectGuid(), WorldSession::GetPlayer(), LANG_UNIVERSAL, m_session, and Player::Whisper().
Referenced by getCommandTable().
HandleDebugDbscript()
bool ChatHandler::HandleDebugDbscript (char * args) protected
Definition at line 1904 of file debugcmds.cpp.
References ExtractUInt32(), WorldObject::GetMap(), WorldSession::GetPlayer(), getSelectedUnit(), GetSession(), Object::IsInWorld(), SCRIPT_TYPE_INTERNAL, and Map::ScriptsStart().
Referenced by getCommandTable().
HandleDebugDbscriptGuided()
bool ChatHandler::HandleDebugDbscriptGuided (char * args) protected
Definition at line 1977 of file debugcmds.cpp.
References ExtractUInt32(), Map::GetCreature(), WorldObject::GetMap(), WorldSession::GetPlayer(), GetSession(), Object::IsInWorld(), SCRIPT_TYPE_INTERNAL, and Map::ScriptsStart().
Referenced by getCommandTable().
HandleDebugDbscriptSourced()
bool ChatHandler::HandleDebugDbscriptSourced (char * args) protected
Definition at line 1950 of file debugcmds.cpp.
References ExtractUInt32(), Map::GetCreature(), WorldObject::GetMap(), WorldSession::GetPlayer(), getSelectedUnit(), GetSession(), Object::IsInWorld(), SCRIPT_TYPE_INTERNAL, and Map::ScriptsStart().
Referenced by getCommandTable().
HandleDebugDbscriptTargeted()
bool ChatHandler::HandleDebugDbscriptTargeted (char * args) protected
Definition at line 1923 of file debugcmds.cpp.
References ExtractUInt32(), Map::GetCreature(), WorldObject::GetMap(), WorldSession::GetPlayer(), getSelectedUnit(), GetSession(), Object::IsInWorld(), SCRIPT_TYPE_INTERNAL, and Map::ScriptsStart().
Referenced by getCommandTable().
HandleDebugGetItemStateCommand()
bool ChatHandler::HandleDebugGetItemStateCommand (char * args) protected
Definition at line 458 of file debugcmds.cpp.
References BUYBACK_SLOT_END, BUYBACK_SLOT_START, Bag::GetBagSize(), Item::GetBagSlot(), Item::GetContainer(), Object::GetGuidStr(), Player::GetItemByPos(), Bag::GetItemByPos(), Player::GetItemUpdateQueue(), Object::GetObjectGuid(), Item::GetOwnerGuid(), WorldSession::GetPlayer(), Item::GetQueuePos(), getSelectedPlayer(), Item::GetSlot(), Item::GetState(), ObjectGuid::GetString(), INVENTORY_SLOT_BAG_0, Item::IsBag(), Item::IsInUpdateQueue(), ITEM_CHANGED, ITEM_NEW, ITEM_REMOVED, ITEM_UNCHANGED, m_session, PLAYER_SLOT_END, PLAYER_SLOT_START, PSendSysMessage(), SendSysMessage(), and SIZEFMTD.
Referenced by getCommandTable().
HandleDebugGetItemValueCommand()
bool ChatHandler::HandleDebugGetItemValueCommand (char * args) protected
Definition at line 979 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractUInt32(), Player::GetItemByGuid(), WorldSession::GetPlayer(), HandleGetValueHelper(), HIGHGUID_ITEM, and m_session.
Referenced by getCommandTable().
HandleDebugGetLootRecipientCommand()
bool ChatHandler::HandleDebugGetLootRecipientCommand (char * args) protected
Definition at line 416 of file debugcmds.cpp.
References Creature::GetLootGroupRecipientId(), Creature::GetLootRecipient(), Creature::GetLootRecipientGuid(), getSelectedCreature(), ObjectGuid::GetString(), Creature::HasLootRecipient(), PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleDebugGetValueByIndexCommand()
bool ChatHandler::HandleDebugGetValueByIndexCommand (char * args) protected
Definition at line 1000 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractUInt32(), getSelectedUnit(), HandleGetValueHelper(), LANG_SELECT_CHAR_OR_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDebugGetValueByNameCommand()
bool ChatHandler::HandleDebugGetValueByNameCommand (char * args) protected
Definition at line 1199 of file debugcmds.cpp.
References ExtractQuotedOrLiteralArg(), Object::GetGuidStr(), getSelectedUnit(), Object::GetTypeMask(), UpdateFields::GetUpdateFieldDataByName(), LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and ShowUpdateFieldHelper().
Referenced by getCommandTable().
HandleDebugHaveAtClientCommand()
bool ChatHandler::HandleDebugHaveAtClientCommand (char * args) protected
Definition at line 1677 of file debugcmds.cpp.
References WorldObject::GetName(), WorldSession::GetPlayer(), getSelectedUnit(), Player::HasAtClient(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleDebugIncPacketHistory()
bool ChatHandler::HandleDebugIncPacketHistory (char * args) protected
Definition at line 1838 of file debugcmds.cpp.
References WorldSession::GetIncOpcodeHistory(), WorldSession::GetPlayer(), getSelectedPlayer(), Player::GetSession(), LookupOpcodeName(), m_session, and SendSysMessage().
Referenced by getCommandTable().
HandleDebugIsVisibleCommand()
bool ChatHandler::HandleDebugIsVisibleCommand (char * args) protected
Definition at line 1695 of file debugcmds.cpp.
References Camera::GetBody(), Player::GetCamera(), WorldObject::GetName(), WorldSession::GetPlayer(), getSelectedUnit(), Player::HasAtClient(), Unit::isVisibleForInState(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleDebugLfgCommand()
bool ChatHandler::HandleDebugLfgCommand (char * args) protected
Definition at line 2008 of file debugcmds.cpp.
References sWorld.
Referenced by getCommandTable().
HandleDebugListUpdateFieldsCommand()
bool ChatHandler::HandleDebugListUpdateFieldsCommand (char * args) protected
Definition at line 442 of file debugcmds.cpp.
References getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, SendSysMessage(), SetSentErrorMessage(), and ShowAllUpdateFieldsHelper().
Referenced by getCommandTable().
HandleDebugLootDropStats()
bool ChatHandler::HandleDebugLootDropStats (char * args) protected
Definition at line 1575 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractUInt32(), Creature::GetCreatureInfo(), getSelectedCreature(), CreatureInfo::LootId, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sLootMgr.
Referenced by getCommandTable().
HandleDebugModItemValueCommand()
bool ChatHandler::HandleDebugModItemValueCommand (char * args) protected
Definition at line 1276 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractUInt32(), Player::GetItemByGuid(), WorldSession::GetPlayer(), HandlerDebugModValueHelper(), HIGHGUID_ITEM, and m_session.
Referenced by getCommandTable().
HandleDebugModValueCommand()
bool ChatHandler::HandleDebugModValueCommand (char * args) protected
Definition at line 1301 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractUInt32(), getSelectedUnit(), HandlerDebugModValueHelper(), LANG_SELECT_CHAR_OR_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDebugMoveflags()
bool ChatHandler::HandleDebugMoveflags (char * args) protected
Definition at line 1545 of file debugcmds.cpp.
References MovementInfo::GetMovementFlags(), getSelectedUnit(), WorldObject::m_movementInfo, and PSendSysMessage().
Referenced by getCommandTable().
HandleDebugMovement()
bool ChatHandler::HandleDebugMovement (char * args) protected
Definition at line 6368 of file Level3.cpp.
References ExtractOnOff(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, LANG_USE_BOL, PSendSysMessage(), SendSysMessage(), Unit::SetDebuggingMovement(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDebugObjectFlags()
bool ChatHandler::HandleDebugObjectFlags (char * args) protected
Definition at line 1733 of file debugcmds.cpp.
References WorldObject::ClearDebugFlag(), CMDebugCommandTable, CMDEBUGFLAG_NONE, CMDebugCommandTableStruct::command, ExtractLiteralArg(), ExtractOnOff(), CMDebugCommandTableStruct::flag, Object::GetGuidStr(), getSelectedUnit(), WorldObject::HaveDebugFlag(), LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), SendSysMessage(), and WorldObject::SetDebugFlag().
Referenced by getCommandTable().
HandleDebugOutPacketHistory()
bool ChatHandler::HandleDebugOutPacketHistory (char * args) protected
Definition at line 1820 of file debugcmds.cpp.
References WorldSession::GetOutOpcodeHistory(), WorldSession::GetPlayer(), getSelectedPlayer(), Player::GetSession(), LookupOpcodeName(), m_session, and SendSysMessage().
Referenced by getCommandTable().
HandleDebugOverflowCommand()
bool ChatHandler::HandleDebugOverflowCommand (char * args) protected
Definition at line 1714 of file debugcmds.cpp.
References normalizePlayerName().
Referenced by getCommandTable().
HandleDebugPacketLog()
bool ChatHandler::HandleDebugPacketLog (char * args) protected
Definition at line 1894 of file debugcmds.cpp.
References ExtractUInt32(), GetSession(), and WorldSession::SetPacketLogging().
Referenced by getCommandTable().
HandleDebugPetDismissSound()
bool ChatHandler::HandleDebugPetDismissSound (char * args) protected
Definition at line 332 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), LANG_YOU_HEAR_SOUND, m_session, PSendSysMessage(), and Unit::SendPetDismiss().
Referenced by getCommandTable().
HandleDebugPlayCinematicCommand()
bool ChatHandler::HandleDebugPlayCinematicCommand (char * args) protected
Definition at line 221 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), LANG_CINEMATIC_NOT_EXIST, FlyByCamera::locations, M_PI, m_session, PSendSysMessage(), sCinematicSequencesStore, Player::SendCinematicStart(), SetSentErrorMessage(), sFlyByCameraStore, FlyByCamera::timeStamp, CamLocation::w, CamLocation::x, CamLocation::y, and CamLocation::z.
Referenced by getCommandTable().
HandleDebugPlayMovieCommand()
bool ChatHandler::HandleDebugPlayMovieCommand (char * args) protected
Definition at line 257 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), LANG_MOVIE_NOT_EXIST, m_session, PSendSysMessage(), Player::SendMovieStart(), SetSentErrorMessage(), and sMovieStore.
Referenced by getCommandTable().
HandleDebugPlayMusicCommand()
bool ChatHandler::HandleDebugPlayMusicCommand (char * args) protected
Definition at line 310 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), getSelectedUnit(), LANG_SOUND_NOT_EXIST, LANG_YOU_HEAR_SOUND, m_session, PLAY_TARGET, WorldObject::PlayMusic(), PSendSysMessage(), SetSentErrorMessage(), and sSoundEntriesStore.
Referenced by getCommandTable().
HandleDebugPlaySoundCommand()
bool ChatHandler::HandleDebugPlaySoundCommand (char * args) protected
Definition at line 277 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), getSelectedUnit(), Player::GetSelectionGuid(), LANG_SELECT_CHAR_OR_CREATURE, LANG_SOUND_NOT_EXIST, LANG_YOU_HEAR_SOUND, m_session, PLAY_TARGET, WorldObject::PlayDirectSound(), WorldObject::PlayDistanceSound(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sSoundEntriesStore.
Referenced by getCommandTable().
HandleDebugRespawnDynguid()
bool ChatHandler::HandleDebugRespawnDynguid (char * args) protected
Definition at line 1879 of file debugcmds.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), WorldSession::GetPlayer(), getSelectedCreature(), GetSession(), Map::GetSpawnManager(), SpawnManager::RespawnAll(), and SpawnManager::RespawnCreature().
Referenced by getCommandTable().
HandleDebugSendBuyErrorCommand()
bool ChatHandler::HandleDebugSendBuyErrorCommand (char * args) protected
Definition at line 114 of file debugcmds.cpp.
References WorldSession::GetPlayer(), m_session, and Player::SendBuyError().
Referenced by getCommandTable().
HandleDebugSendChannelNotifyCommand()
bool ChatHandler::HandleDebugSendChannelNotifyCommand (char * args) protected
Definition at line 360 of file debugcmds.cpp.
References ExtractUInt32(), m_session, WorldSession::SendPacket(), and SMSG_CHANNEL_NOTIFY.
Referenced by getCommandTable().
HandleDebugSendChatMsgCommand()
bool ChatHandler::HandleDebugSendChatMsgCommand (char * args) protected
Definition at line 378 of file debugcmds.cpp.
References BuildChatPacket(), CHAT_TAG_NONE, ExtractUInt32(), Object::GetObjectGuid(), WorldSession::GetPlayer(), WorldSession::GetPlayerName(), LANG_UNIVERSAL, m_session, and WorldSession::SendPacket().
Referenced by getCommandTable().
HandleDebugSendEquipErrorCommand()
bool ChatHandler::HandleDebugSendEquipErrorCommand (char * args) protected
Definition at line 94 of file debugcmds.cpp.
References WorldSession::GetPlayer(), m_session, and Player::SendEquipError().
Referenced by getCommandTable().
HandleDebugSendLargePacketCommand()
bool ChatHandler::HandleDebugSendLargePacketCommand (char * args) protected
Definition at line 761 of file debugcmds.cpp.
References SendSysMessage().
Referenced by getCommandTable().
HandleDebugSendOpcodeCommand()
bool ChatHandler::HandleDebugSendOpcodeCommand (char * args) protected
Definition at line 124 of file debugcmds.cpp.
References DEBUG_LOG, WorldObject::GetName(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), Object::GetPackGUID(), WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), ByteBuffer::hexlike(), LANG_COMMAND_OPCODESENT, m_session, PSendSysMessage(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleDebugSendPoiCommand()
bool ChatHandler::HandleDebugSendPoiCommand (char * args) protected
Definition at line 71 of file debugcmds.cpp.
References DETAIL_LOG, ExtractUInt32(), Object::GetGUIDLow(), WorldSession::GetPlayer(), Player::GetPlayerMenu(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PlayerMenu::SendPointOfInterest(), and SendSysMessage().
Referenced by getCommandTable().
HandleDebugSendQuestFailedMsgCommand()
bool ChatHandler::HandleDebugSendQuestFailedMsgCommand (char * args) protected
Definition at line 392 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), m_session, and Player::SendQuestFailed().
Referenced by getCommandTable().
HandleDebugSendQuestInvalidMsgCommand()
bool ChatHandler::HandleDebugSendQuestInvalidMsgCommand (char * args) protected
Definition at line 435 of file debugcmds.cpp.
References WorldSession::GetPlayer(), m_session, and Player::SendCanTakeQuestResponse().
Referenced by getCommandTable().
HandleDebugSendQuestPartyMsgCommand()
bool ChatHandler::HandleDebugSendQuestPartyMsgCommand (char * args) protected
Definition at line 406 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), m_session, and Player::SendPushToPartyResponse().
Referenced by getCommandTable().
HandleDebugSendSellErrorCommand()
bool ChatHandler::HandleDebugSendSellErrorCommand (char * args) protected
Definition at line 104 of file debugcmds.cpp.
References WorldSession::GetPlayer(), m_session, and Player::SendSellError().
Referenced by getCommandTable().
HandleDebugSendSetPhaseShiftCommand()
bool ChatHandler::HandleDebugSendSetPhaseShiftCommand (char * args) protected
Definition at line 771 of file debugcmds.cpp.
References m_session, and WorldSession::SendSetPhaseShift().
Referenced by getCommandTable().
HandleDebugSendSpellFailCommand()
bool ChatHandler::HandleDebugSendSpellFailCommand (char * args) protected
Definition at line 40 of file debugcmds.cpp.
References ExtractOptUInt32(), ExtractUInt32(), m_session, WorldSession::SendPacket(), and SMSG_CAST_RESULT.
Referenced by getCommandTable().
HandleDebugSendWorldState()
bool ChatHandler::HandleDebugSendWorldState (char * args) protected
Definition at line 1662 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), m_session, and Player::SendUpdateWorldState().
Referenced by getCommandTable().
HandleDebugSetAuraStateCommand()
bool ChatHandler::HandleDebugSetAuraStateCommand (char * args) protected
Definition at line 792 of file debugcmds.cpp.
References ExtractInt32(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, Unit::ModifyAuraState(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDebugSetItemValueCommand()
bool ChatHandler::HandleDebugSetItemValueCommand (char * args) protected
Definition at line 867 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractOptNotLastArg(), ExtractUInt32(), Player::GetItemByGuid(), WorldSession::GetPlayer(), HandleSetValueHelper(), HIGHGUID_ITEM, and m_session.
Referenced by getCommandTable().
HandleDebugSetValueByIndexCommand()
bool ChatHandler::HandleDebugSetValueByIndexCommand (char * args) protected
Definition at line 892 of file debugcmds.cpp.
References ExtractLiteralArg(), ExtractOptNotLastArg(), ExtractUInt32(), getSelectedUnit(), HandleSetValueHelper(), LANG_SELECT_CHAR_OR_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleDebugSetValueByNameCommand()
bool ChatHandler::HandleDebugSetValueByNameCommand (char * args) protected
Definition at line 1100 of file debugcmds.cpp.
References ExtractFloat(), ExtractQuotedOrLiteralArg(), ExtractUInt32(), WorldObject::GetName(), getSelectedUnit(), Object::GetTypeMask(), UpdateFields::GetUpdateFieldDataByName(), LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), SendSysMessage(), Object::SetByteValue(), Object::SetFloatValue(), SetSentErrorMessage(), Object::SetUInt16Value(), Object::SetUInt32Value(), UF_TYPE_BYTES, UF_TYPE_BYTES2, UF_TYPE_FLOAT, UF_TYPE_INT, and UF_TYPE_TWO_SHORT.
Referenced by getCommandTable().
HandleDebugSpawnsList()
bool ChatHandler::HandleDebugSpawnsList (char * args) protected
Definition at line 1869 of file debugcmds.cpp.
References WorldObject::GetMap(), WorldSession::GetPlayer(), SpawnManager::GetRespawnList(), GetSession(), Map::GetSpawnManager(), Object::IsInWorld(), and PSendSysMessage().
Referenced by getCommandTable().
HandleDebugSpellCheckCommand()
bool ChatHandler::HandleDebugSpellCheckCommand (char * args) protected
Definition at line 754 of file debugcmds.cpp.
References sLog, and sSpellMgr.
Referenced by getCommandTable().
HandleDebugSpellCoefsCommand()
bool ChatHandler::HandleDebugSpellCoefsCommand (char * args) protected
Definition at line 1326 of file debugcmds.cpp.
References SpellBonusEntry::ap_bonus, SpellBonusEntry::ap_dot_bonus, CalculateDefaultCoefficient(), SpellBonusEntry::direct_damage, DOT, SpellBonusEntry::dot_damage, SpellEntry::Effect, SpellEntry::EffectApplyAuraName, ExtractSpellIdFromLink(), GetMangosString(), LANG_DIRECT_DAMAGE, LANG_DIRECT_HEAL, LANG_DOT_DAMAGE, LANG_DOT_HEAL, LANG_SPELLCOEFS, SQLStorage::LookupEntry(), PSendSysMessage(), SCALE_SPELLPOWER_HEALING, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_SCHOOL_ABSORB, SPELL_DIRECT_DAMAGE, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, sSpellMgr, and sSpellTemplate.
Referenced by getCommandTable().
HandleDebugSpellModsCommand()
bool ChatHandler::HandleDebugSpellModsCommand (char * args) protected
Definition at line 1377 of file debugcmds.cpp.
References ChatHandler(), ExtractInt32(), ExtractLiteralArg(), ExtractUInt32(), GetNameLink(), getSelectedPlayer(), Player::GetSession(), HasLowerSecurity(), LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_SPELLMODS, LANG_YOURS_SPELLMODS_CHANGED, MAX_SPELLMOD, needReportToTarget(), PSendSysMessage(), WorldSession::SendPacket(), SendSysMessage(), SetSentErrorMessage(), SMSG_SET_FLAT_SPELL_MODIFIER, and SMSG_SET_PCT_SPELL_MODIFIER.
Referenced by getCommandTable().
HandleDebugSpellVisual()
bool ChatHandler::HandleDebugSpellVisual (char * args) protected
Definition at line 1531 of file debugcmds.cpp.
References ExtractUInt32(), getSelectedUnit(), and WorldObject::PlaySpellVisual().
Referenced by getCommandTable().
HandleDebugTaxiCommand()
bool ChatHandler::HandleDebugTaxiCommand (char *) protected
Definition at line 1430 of file debugcmds.cpp.
References GetMangosString(), WorldSession::GetPlayer(), Player::IsTaxiDebug(), LANG_COMMAND_TAXI_DEBUG, LANG_OFF, LANG_ON, m_session, PSendSysMessage(), and Player::ToggleTaxiDebug().
Referenced by getCommandTable().
HandleDebugTransports()
bool ChatHandler::HandleDebugTransports (char * args) protected
Definition at line 1856 of file debugcmds.cpp.
References WorldObject::GetMap(), WorldSession::GetPlayer(), GetSession(), Map::GetTransports(), Object::IsInWorld(), PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleDebugUpdateWorldStateCommand()
bool ChatHandler::HandleDebugUpdateWorldStateCommand (char * args) protected
Definition at line 207 of file debugcmds.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), m_session, and Player::SendUpdateWorldState().
Referenced by getCommandTable().
HandleDebugWaypoint()
bool ChatHandler::HandleDebugWaypoint (char * args) protected
Definition at line 1468 of file debugcmds.cpp.
References ExtractUInt32(), Unit::GetMotionMaster(), MotionMaster::GetPathId(), getSelectedCreature(), MotionMaster::MoveWaypoint(), and PSendSysMessage().
Referenced by getCommandTable().
HandleDeMorphCommand()
bool ChatHandler::HandleDeMorphCommand (char * args) protected
Definition at line 2802 of file Level2.cpp.
References Unit::DeMorph(), WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), m_session, and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleDieCommand()
bool ChatHandler::HandleDieCommand (char * args) protected
Definition at line 3696 of file Level3.cpp.
References Unit::DealDamage(), Unit::DealDamageMods(), DIRECT_DAMAGE, ExtractOptUInt32(), Unit::GetHealth(), WorldSession::GetPlayer(), getSelectedUnit(), Player::GetSelectionGuid(), Object::GetTypeId(), HasLowerSecurity(), INSTAKILL, Unit::IsAlive(), LANG_SELECT_CHAR_OR_CREATURE, m_session, SendSysMessage(), SetSentErrorMessage(), SPELL_SCHOOL_MASK_NORMAL, and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleDismountCommand()
bool ChatHandler::HandleDismountCommand (char * args) protected
Definition at line 112 of file Level0.cpp.
References WorldSession::GetPlayer(), Unit::IsMounted(), Unit::IsTaxiFlying(), LANG_CHAR_NON_MOUNTED, LANG_YOU_IN_FLIGHT, m_session, Unit::RemoveSpellsCausingAura(), SendSysMessage(), SetSentErrorMessage(), SPELL_AURA_MOUNTED, and Player::Unmount().
Referenced by getCommandTable().
HandleEventInfoCommand()
bool ChatHandler::HandleEventInfoCommand (char * args) protected
Definition at line 4044 of file Level2.cpp.
References GameEventData::description, GameEventData::end, ExtractUint32KeyFromLink(), GetMangosString(), LANG_ACTIVE, LANG_EVENT_INFO, LANG_EVENT_NOT_EXIST, GameEventData::length, MINUTE, GameEventData::occurence, PSendSysMessage(), secsToTimeString(), SendSysMessage(), SetSentErrorMessage(), sGameEventMgr, GameEventData::start, and TimeToTimestampStr().
Referenced by getCommandTable().
HandleEventListCommand()
bool ChatHandler::HandleEventListCommand (char * args) protected
Definition at line 4000 of file Level2.cpp.
References GameEventData::description, GetMangosString(), LANG_ACTIVE, LANG_EVENT_ENTRY_LIST_CHAT, LANG_EVENT_ENTRY_LIST_CONSOLE, LANG_FACTION_INACTIVE, LANG_NOEVENTFOUND, m_session, PSendSysMessage(), SendSysMessage(), and sGameEventMgr.
Referenced by getCommandTable().
HandleEventStartCommand()
bool ChatHandler::HandleEventStartCommand (char * args) protected
Definition at line 4083 of file Level2.cpp.
References GameEventData::description, ExtractUint32KeyFromLink(), GameEventData::isValid(), LANG_EVENT_ALREADY_ACTIVE, LANG_EVENT_NOT_EXIST, LANG_EVENT_STARTED, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sGameEventMgr.
Referenced by getCommandTable().
HandleEventStopCommand()
bool ChatHandler::HandleEventStopCommand (char * args) protected
Definition at line 4122 of file Level2.cpp.
References GameEventData::description, ExtractUint32KeyFromLink(), GameEventData::isValid(), LANG_EVENT_NOT_ACTIVE, LANG_EVENT_NOT_EXIST, LANG_EVENT_STOPPED, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sGameEventMgr.
Referenced by getCommandTable().
HandleExpansionRelease()
bool ChatHandler::HandleExpansionRelease (char * args) protected
Definition at line 7878 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), SendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleExploreCheatCommand()
bool ChatHandler::HandleExploreCheatCommand (char * args) protected
Definition at line 4301 of file Level3.cpp.
References ChatHandler(), GetNameLink(), WorldSession::GetPlayer(), getSelectedPlayer(), LANG_NO_CHAR_SELECTED, LANG_YOU_SET_EXPLORE_ALL, LANG_YOU_SET_EXPLORE_NOTHING, LANG_YOURS_EXPLORE_SET_ALL, LANG_YOURS_EXPLORE_SET_NOTHING, m_session, needReportToTarget(), PLAYER_EXPLORED_ZONES_1, PLAYER_EXPLORED_ZONES_SIZE, PSendSysMessage(), SendSysMessage(), Object::SetFlag(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGameObjectActivateCommand()
bool ChatHandler::HandleGameObjectActivateCommand (char * args) protected
Definition at line 1322 of file Level2.cpp.
References ExtractUint32KeyFromLink(), GameObjectInfo::GetAutoCloseTime(), Object::GetEntry(), GetGameObjectWithGuid(), GameObject::GetGOInfo(), GO_READY, LANG_COMMAND_OBJNOTFOUND, PSendSysMessage(), GameObject::SetLootState(), SetSentErrorMessage(), sObjectMgr, and GameObject::UseDoorOrButton().
Referenced by getCommandTable().
HandleGameObjectAddCommand()
bool ChatHandler::HandleGameObjectAddCommand (char * args) protected
Definition at line 1131 of file Level2.cpp.
References GameObject::Create(), GameObject::CreateGameObject(), DEBUG_LOG, GameObjectInfo::displayId, ExtractOptInt32(), ExtractUint32KeyFromLink(), ObjectMgr::GetGameObjectInfo(), Map::GetId(), GetMangosString(), WorldObject::GetMap(), WorldObject::GetOrientation(), Player::GetPhaseMaskForSpawn(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Map::GetSpawnMode(), GameObjectInfo::id, LANG_GAMEOBJECT_ADD, LANG_GAMEOBJECT_CURRENT, LANG_GAMEOBJECT_HAVE_INVALID_DATA, LANG_GAMEOBJECT_NOT_EXIST, LANG_NO_FREE_STATIC_GUID_FOR_SPAWN, GameObject::LoadFromDB(), m_session, GameObjectInfo::name, PSendSysMessage(), GameObject::SaveToDB(), SendSysMessage(), GameObject::SetRespawnTime(), SetSentErrorMessage(), sGameObjectDisplayInfoStore, sLog, sObjectMgr, and GameObjectInfo::type.
Referenced by getCommandTable().
HandleGameObjectDeleteCommand()
bool ChatHandler::HandleGameObjectDeleteCommand (char * args) protected
Definition at line 979 of file Level2.cpp.
References GameObject::Delete(), GameObject::DeleteFromDB(), ExtractUint32KeyFromLink(), GetGameObjectWithGuid(), Object::GetGUIDLow(), GameObject::GetOwnerGuid(), WorldSession::GetPlayer(), ObjectAccessor::GetUnit(), Object::IsPlayer(), LANG_COMMAND_DELOBJMESSAGE, LANG_COMMAND_DELOBJREFERCREATURE, LANG_COMMAND_OBJNOTFOUND, m_session, PSendSysMessage(), Unit::RemoveGameObject(), GameObject::SetRespawnTime(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleGameObjectForcedDespawnCommand()
bool ChatHandler::HandleGameObjectForcedDespawnCommand (char * args) protected
Definition at line 1354 of file Level2.cpp.
References ExtractUint32KeyFromLink(), GetGameObjectWithGuid(), GO_JUST_DEACTIVATED, LANG_COMMAND_OBJNOTFOUND, PSendSysMessage(), GameObject::SetForcedDespawn(), GameObject::SetLootState(), GameObject::SetRespawnDelay(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleGameObjectMoveCommand()
bool ChatHandler::HandleGameObjectMoveCommand (char * args) protected
Definition at line 1059 of file Level2.cpp.
References Map::Add(), ExtractFloat(), ExtractUint32KeyFromLink(), GetGameObjectWithGuid(), GameObject::GetGOInfo(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), MapManager::IsValidMapCoord(), LANG_COMMAND_MOVEOBJMESSAGE, LANG_COMMAND_OBJNOTFOUND, LANG_INVALID_TARGET_COORD, m_session, GameObjectInfo::name, PSendSysMessage(), GameObject::Refresh(), WorldObject::Relocate(), Map::Remove(), GameObject::SaveToDB(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleGameObjectNearCommand()
bool ChatHandler::HandleGameObjectNearCommand (char * args) protected
Definition at line 1244 of file Level2.cpp.
References ExtractOptFloat(), QueryResult::Fetch(), Field::GetFloat(), ObjectMgr::GetGameObjectInfo(), WorldObject::GetMap(), Map::GetMapDataContainer(), WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), MapDataContainer::GetSpawnGroupByGuid(), Field::GetUInt16(), Field::GetUInt32(), LANG_COMMAND_NEAROBJMESSAGE, LANG_GO_MIXED_LIST_CHAT, m_session, GameObjectInfo::name, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), SendSysMessage(), TYPEID_GAMEOBJECT, and WorldDatabase.
Referenced by getCommandTable().
HandleGameObjectNearSpawnedCommand()
bool ChatHandler::HandleGameObjectNearSpawnedCommand (char * args) protected
Definition at line 1383 of file Level2.cpp.
References ExtractOptFloat(), ObjectGuid::GetCounter(), ObjectMgr::GetGameObjectInfo(), WorldObject::GetMap(), Map::GetMapDataContainer(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), MapDataContainer::GetSpawnGroupByGuid(), LANG_COMMAND_NEAROBJMESSAGE, LANG_GO_MIXED_LIST_CHAT, m_session, GameObjectInfo::name, PSendSysMessage(), TYPEID_GAMEOBJECT, and Cell::VisitGridObjects().
Referenced by getCommandTable().
HandleGameObjectPhaseCommand()
bool ChatHandler::HandleGameObjectPhaseCommand (char * args) protected
Definition at line 1208 of file Level2.cpp.
References ExtractUInt32(), ExtractUint32KeyFromLink(), GetGameObjectWithGuid(), LANG_BAD_VALUE, LANG_COMMAND_OBJNOTFOUND, PSendSysMessage(), GameObject::SaveToDB(), SendSysMessage(), GameObject::SetPhaseMask(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleGameObjectRespawnCommand()
bool ChatHandler::HandleGameObjectRespawnCommand (char * args) protected
Definition at line 1297 of file Level2.cpp.
References ExtractUint32KeyFromLink(), Map::GetGameObject(), WorldObject::GetMap(), WorldSession::GetPlayer(), GameObject::IsSpawned(), LANG_COMMAND_OBJNOTFOUND, m_session, PSendSysMessage(), GameObject::Respawn(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGameObjectTargetCommand()
bool ChatHandler::HandleGameObjectTargetCommand (char * args) protected
Definition at line 845 of file Level2.cpp.
References _CONCAT3_, _LIKE_, GameObjectInfo::door, Database::escape_string(), ExtractKeyFromLink(), ExtractUInt32(), QueryResult::Fetch(), GAMEOBJECT_TYPE_DOOR, Object::GetDbGuid(), Field::GetFloat(), Map::GetGameObject(), ObjectMgr::GetGameObjectInfo(), GameObject::GetGoState(), GameObject::GetGoType(), Object::GetGUIDLow(), GameObject::GetLootState(), WorldObject::GetMap(), Map::GetMapDataContainer(), WorldObject::GetMapId(), GetOnOffStr(), Map::GetPersistentState(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GameObject::GetRespawnDelay(), GameObject::GetRespawnTimeEx(), MapDataContainer::GetSpawnGroupByGuid(), Field::GetUInt16(), Field::GetUInt32(), GameObject::IsCollisionEnabled(), MapPersistentState::IsSpawnedPoolObject(), LANG_COMMAND_GO_STATUS, LANG_COMMAND_GO_STATUS_DOOR, LANG_COMMAND_RAWPAWNTIMES, LANG_COMMAND_TARGETOBJNOTFOUND, LANG_GAMEOBJECT_DETAIL, LANG_GAMEOBJECT_NOT_EXIST, m_session, GameObjectInfo::name, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), secsToTimeString(), SendSysMessage(), sGameEventMgr, sObjectMgr, sPoolMgr, TYPEID_GAMEOBJECT, and WorldDatabase.
Referenced by getCommandTable().
HandleGameObjectTurnCommand()
bool ChatHandler::HandleGameObjectTurnCommand (char * args) protected
Definition at line 1025 of file Level2.cpp.
References ExtractFloat(), ExtractOptFloat(), ExtractUint32KeyFromLink(), GetGameObjectWithGuid(), GameObject::GetGOInfo(), Object::GetGUIDLow(), LANG_COMMAND_OBJNOTFOUND, LANG_COMMAND_TURNOBJMESSAGE, GameObjectInfo::name, PSendSysMessage(), GameObject::SaveToDB(), GameObject::SetLocalRotationAngles(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleGetDistanceCommand()
bool ChatHandler::HandleGetDistanceCommand (char * args) protected
Definition at line 3630 of file Level3.cpp.
References DIST_CALC_BOUNDING_RADIUS, DIST_CALC_COMBAT_REACH, DIST_CALC_NONE, ExtractGuidFromLink(), Unit::GetAttackDistance(), WorldObject::GetDistance(), Player::GetObjectByTypeMask(), WorldSession::GetPlayer(), getSelectedUnit(), VisibilityData::GetStealthVisibilityDistance(), WorldObject::GetVisibilityData(), LANG_PLAYER_NOT_FOUND, LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and TYPEMASK_CREATURE_OR_GAMEOBJECT.
Referenced by getCommandTable().
HandleGetLosCommand()
bool ChatHandler::HandleGetLosCommand (char * args) protected
Definition at line 3678 of file Level3.cpp.
References Unit::GetCollisionHeight(), WorldSession::GetPlayer(), WorldObject::GetPosition(), getSelectedUnit(), WorldObject::IsWithinLOS(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleGetValueHelper()
bool ChatHandler::HandleGetValueHelper (Object * target, uint32 field, char * typeStr) protected
Definition at line 917 of file debugcmds.cpp.
References DEBUG_LOG, Object::GetFloatValue(), GetMangosString(), Object::GetObjectGuid(), ObjectGuid::GetString(), Object::GetUInt32Value(), Object::GetValuesCount(), LANG_GET_BITSTR, LANG_GET_BITSTR_FIELD, LANG_GET_FLOAT, LANG_GET_FLOAT_FIELD, LANG_GET_HEX, LANG_GET_HEX_FIELD, LANG_GET_UINT, LANG_GET_UINT_FIELD, LANG_TOO_BIG_INDEX, and PSendSysMessage().
Referenced by HandleDebugGetItemValueCommand(), and HandleDebugGetValueByIndexCommand().
HandleGMChatCommand()
bool ChatHandler::HandleGMChatCommand (char * args) protected
Definition at line 2082 of file Level1.cpp.
References ExtractOnOff(), WorldSession::GetPlayer(), Player::isGMChat(), LANG_GM_CHAT_OFF, LANG_GM_CHAT_ON, LANG_USE_BOL, m_session, WorldSession::SendNotification(), SendSysMessage(), Player::SetGMChat(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGMCommand()
bool ChatHandler::HandleGMCommand (char * args) protected
Definition at line 156 of file Level1.cpp.
References ExtractOnOff(), WorldSession::GetPlayer(), Player::IsGameMaster(), LANG_GM_OFF, LANG_GM_ON, LANG_USE_BOL, m_session, WorldSession::SendNotification(), SendSysMessage(), Player::SetGameMaster(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGMFlyCommand()
bool ChatHandler::HandleGMFlyCommand (char * args) protected
Definition at line 6106 of file Level3.cpp.
References ExtractOnOff(), GetNameLink(), WorldSession::GetPlayer(), getSelectedPlayer(), LANG_COMMAND_FLYMODE_STATUS, LANG_USE_BOL, m_session, PSendSysMessage(), SendSysMessage(), Unit::SetCanFly(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGMListFullCommand()
bool ChatHandler::HandleGMListFullCommand (char * args) protected
Display the list of GMs.
Get the accounts with GM Level >0
Circle through them. Display username and GM level
Definition at line 6808 of file Level3.cpp.
References QueryResult::Fetch(), LANG_GMLIST, LANG_GMLIST_EMPTY, LANG_GMLIST_HEADER, LoginDatabase, QueryResult::NextRow(), PSendSysMessage(), Database::Query(), and SendSysMessage().
Referenced by getCommandTable().
HandleGMListIngameCommand()
bool ChatHandler::HandleGMListIngameCommand (char * args) protected
Definition at line 156 of file Level0.cpp.
References CONFIG_UINT32_GM_LEVEL_IN_GM_LIST, GetMangosString(), GetNameLink(), WorldSession::GetPlayer(), WorldSession::GetSecurity(), Player::GetSession(), Player::isAcceptWhispers(), Player::IsGameMaster(), Player::IsVisibleGloballyFor(), LANG_GM_ACCEPTS_WHISPER, LANG_GM_NO_WHISPER, LANG_GMS_NOT_LOGGED, LANG_GMS_ON_SRV, m_session, PSendSysMessage(), SEC_PLAYER, SendSysMessage(), sObjectAccessor, and sWorld.
Referenced by getCommandTable().
HandleGMMountUpCommand()
bool ChatHandler::HandleGMMountUpCommand (char * args) protected
Definition at line 190 of file Level1.cpp.
References ExtractLiteralArg(), ExtractUInt32(), WorldSession::GetPlayer(), getSelectedUnit(), LANG_BAD_VALUE, LANG_COMMAND_NOCREATUREFOUND, m_session, ModifyMountCommandHelper(), Player::Mount(), sCreatureDisplayInfoStore, SendSysMessage(), SetSentErrorMessage(), and TYPEID_UNIT.
Referenced by getCommandTable().
HandleGMVisibleCommand()
bool ChatHandler::HandleGMVisibleCommand (char * args) protected
Definition at line 232 of file Level1.cpp.
References Unit::CastSpell(), CONFIG_UINT32_GM_INVISIBLE_AURA, ExtractOnOff(), GetMangosString(), WorldSession::GetPlayer(), SpellEntry::Id, Player::isGMVisible(), IsSpellAppliesAura(), LANG_INVISIBLE, LANG_INVISIBLE_INVISIBLE, LANG_INVISIBLE_VISIBLE, LANG_USE_BOL, LANG_VISIBLE, LANG_YOU_ARE, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), Unit::RemoveAurasDueToSpell(), WorldSession::SendNotification(), SendSysMessage(), Player::SetGMVisible(), SetSentErrorMessage(), sSpellTemplate, sWorld, and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleGoCommand()
bool ChatHandler::HandleGoCommand (char * args) protected
Definition at line 1844 of file Level1.cpp.
References ExtractFloat(), ExtractLocationFromLink(), ExtractOptUInt32(), WorldObject::GetMapId(), WorldSession::GetPlayer(), HandleGoHelper(), and m_session.
Referenced by getCommandTable().
HandleGoCreatureCommand()
bool ChatHandler::HandleGoCreatureCommand (char * args) protected
Teleport the GM to the specified creature.
.go creature <GUID> --> TP using creature.guid .go creature azuregos --> TP player to the mob with this name Warning: If there is more than one mob with this name you will be teleported to the first one that is found. .go creature id 6109 --> TP player to the mob, that has this creature_template.entry Warning: If there is more than one mob with this "id" you will be teleported to the first one that is found.
Definition at line 511 of file Level2.cpp.
References CREATURE_LINK_ENTRY, CREATURE_LINK_GUID, CREATURE_LINK_RAW, creatureKeys, Database::escape_string(), ExtractKeyFromLink(), ExtractUInt32(), QueryResult::Fetch(), ObjectMgr::GetCreatureTemplate(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), FindCreatureData::GetResult(), Field::GetUInt32(), HandleGoHelper(), HIGHGUID_UNIT, LANG_COMMAND_GOCREATNOTFOUND, m_session, CreatureData::mapid, QueryResult::NextRow(), CreatureData::posX, CreatureData::posY, CreatureData::posZ, Database::PQuery(), SendSysMessage(), SetSentErrorMessage(), sMapMgr, sObjectMgr, and WorldDatabase.
Referenced by getCommandTable().
HandleGoGraveyardCommand()
bool ChatHandler::HandleGoGraveyardCommand (char * args) protected
Definition at line 467 of file Level2.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), HandleGoHelper(), LANG_COMMAND_GRAVEYARDNOEXIST, SQLStorage::LookupEntry(), m_session, WorldSafeLocsEntry::map_id, PSendSysMessage(), SetSentErrorMessage(), sWorldSafeLocsStore, WorldSafeLocsEntry::x, WorldSafeLocsEntry::y, and WorldSafeLocsEntry::z.
Referenced by getCommandTable().
HandleGoGridCommand()
bool ChatHandler::HandleGoGridCommand (char * args) protected
Definition at line 1987 of file Level1.cpp.
References CENTER_GRID_ID, ExtractFloat(), ExtractOptUInt32(), WorldObject::GetMapId(), WorldSession::GetPlayer(), HandleGoHelper(), m_session, and SIZE_OF_GRIDS.
Referenced by getCommandTable().
HandleGoHelper()
bool ChatHandler::HandleGoHelper (Player * _player, uint32 mapid, float x, float y, float const * zPtr = nullptr, float const * ortPtr = nullptr) protected
Definition at line 1774 of file Level1.cpp.
References Map::GetHeight(), WorldObject::GetMap(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), TerrainInfo::GetWaterOrGroundLevel(), MapManager::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, MAX_HEIGHT, PSendSysMessage(), Player::SaveRecallPosition(), SetSentErrorMessage(), sTerrainMgr, Player::TaxiFlightInterrupt(), and Player::TeleportTo().
Referenced by HandleGoCommand(), HandleGoCreatureCommand(), HandleGoGraveyardCommand(), HandleGoGridCommand(), HandleGonameCommand(), HandleGoObjectCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), HandleGoXYCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), HandleRecallCommand(), HandleTeleCommand(), HandleTeleNameCommand(), and HandleTicketGoCommand().
HandleGonameCommand()
bool ChatHandler::HandleGonameCommand (char * args) protected
Definition at line 515 of file Level1.cpp.
References Player::BindToInstance(), Group::BindToInstance(), DungeonPersistentState::CanReset(), ChatHandler(), ExtractPlayerTarget(), WorldObject::GetAngle(), Player::GetBattleGroundId(), Player::GetBattleGroundTypeId(), Group::GetBoundInstance(), Player::GetBoundInstance(), WorldObject::GetContactPoint(), Player::GetDifficulty(), Player::GetDungeonDifficulty(), Player::GetGroup(), WorldObject::GetMap(), WorldObject::GetMapId(), GetNameLink(), Object::GetObjectGuid(), WorldSession::GetPlayer(), Player::GetRaidDifficulty(), WorldObject::GetTransport(), HandleGoHelper(), HasLowerSecurity(), Map::IsBattleGroundOrArena(), Map::IsDungeon(), Player::IsGameMaster(), Group::IsLeader(), Map::IsRaid(), LANG_APPEARING_AT, LANG_APPEARING_TO, LANG_CANNOT_GO_TO_BG_FROM_BG, LANG_CANNOT_GO_TO_BG_GM, LANG_CANNOT_GO_TO_INST_GM, LANG_CANNOT_GO_TO_INST_PARTY, LANG_CANT_TELEPORT_SELF, Player::LoadPositionFromDB(), m_session, needReportToTarget(), playerLink(), PSendSysMessage(), Player::SaveRecallPosition(), SendSysMessage(), Player::SetBattleGroundEntryPoint(), Player::SetBattleGroundId(), Player::SetDungeonDifficulty(), Player::SetRaidDifficulty(), SetSentErrorMessage(), Player::TaxiFlightInterrupt(), TELE_TO_GM_MODE, and Player::TeleportTo().
Referenced by getCommandTable(), and HandleTicketGoNameCommand().
HandleGoObjectCommand()
bool ChatHandler::HandleGoObjectCommand (char * args) protected
Definition at line 708 of file Level2.cpp.
References CREATURE_LINK_ENTRY, Database::escape_string(), ExtractKeyFromLink(), ExtractUInt32(), QueryResult::Fetch(), GAMEOBJECT_LINK_ENTRY, GAMEOBJECT_LINK_GUID, GAMEOBJECT_LINK_RAW, gameobjectKeys, ObjectMgr::GetGameObjectInfo(), WorldSession::GetPlayer(), FindGOData::GetResult(), Field::GetUInt32(), HandleGoHelper(), LANG_COMMAND_GOOBJNOTFOUND, m_session, GameObjectData::mapid, QueryResult::NextRow(), GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, Database::PQuery(), SendSysMessage(), SetSentErrorMessage(), sObjectMgr, and WorldDatabase.
Referenced by getCommandTable().
HandleGoTaxinodeCommand()
bool ChatHandler::HandleGoTaxinodeCommand (char * args) protected
Definition at line 1818 of file Level1.cpp.
References ExtractUint32KeyFromLink(), WorldSession::GetPlayer(), HandleGoHelper(), LANG_COMMAND_GOTAXINODENOTFOUND, LANG_INVALID_TARGET_COORD, m_session, TaxiNodesEntry::map_id, PSendSysMessage(), SetSentErrorMessage(), sTaxiNodesStore, TaxiNodesEntry::x, TaxiNodesEntry::y, and TaxiNodesEntry::z.
Referenced by getCommandTable().
HandleGoTriggerCommand()
bool ChatHandler::HandleGoTriggerCommand (char * args) protected
Definition at line 422 of file Level2.cpp.
References areatriggerKeys, ExtractKeyFromLink(), ExtractLiteralArg(), ExtractUInt32(), WorldSession::GetPlayer(), HandleGoHelper(), LANG_AREATRIGER_NOT_HAS_TARGET, LANG_COMMAND_GOAREATRNOTFOUND, m_session, AreaTriggerEntry::mapid, PSendSysMessage(), sAreaTriggerStore, SetSentErrorMessage(), sObjectMgr, AreaTrigger::target_mapId, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by getCommandTable().
HandleGoWarpCommand()
bool ChatHandler::HandleGoWarpCommand (char * args) protected
Definition at line 2010 of file Level1.cpp.
References WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), M_PI_F, m_session, and Unit::NearTeleportTo().
Referenced by getCommandTable().
HandleGoXYCommand()
bool ChatHandler::HandleGoXYCommand (char * args) protected
Definition at line 1874 of file Level1.cpp.
References ExtractFloat(), ExtractOptUInt32(), WorldObject::GetMapId(), WorldSession::GetPlayer(), HandleGoHelper(), and m_session.
Referenced by getCommandTable().
HandleGoXYZCommand()
bool ChatHandler::HandleGoXYZCommand (char * args) protected
Definition at line 1894 of file Level1.cpp.
References WorldObject::GetMapId(), WorldSession::GetPlayer(), HandleGoHelper(), MapManager::IsValidMapCoord(), LANG_INVALID_TARGET_COORD, m_session, PSendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGoZoneXYCommand()
bool ChatHandler::HandleGoZoneXYCommand (char * args) protected
Definition at line 1932 of file Level1.cpp.
References AreaTableEntry::area_name, ExtractFloat(), ExtractUint32KeyFromLink(), GetAreaEntryByAreaID(), WorldSession::GetPlayer(), GetSessionDbcLocale(), WorldObject::GetZoneId(), HandleGoHelper(), AreaTableEntry::ID, MapEntry::Instanceable(), LANG_INVALID_ZONE_COORD, LANG_INVALID_ZONE_MAP, m_session, AreaTableEntry::mapid, MapEntry::MapID, MapEntry::name, PSendSysMessage(), SetSentErrorMessage(), sMapStore, AreaTableEntry::zone, and Zone2MapCoordinates().
Referenced by getCommandTable().
HandleGPSCommand()
bool ChatHandler::HandleGPSCommand (char * args) protected
Definition at line 271 of file Level1.cpp.
References AreaTableEntry::area_name, AreaNameInfo::areaName, Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), MaNGOS::ComputeGridPair(), VMAP::VMapFactory::createOrGetVMapManager(), DEBUG_LOG, GridMapLiquidData::depth_level, GridMap::ExistMap(), GridMap::ExistVMap(), ExtractGuidFromLink(), GetAreaEntryByAreaID(), WorldObject::GetAreaName(), Object::GetEntry(), Object::GetGUIDLow(), Map::GetHeight(), TerrainInfo::GetHeightStatic(), WorldObject::GetInstanceId(), TerrainInfo::getLiquidStatus(), GetMangosString(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), GetNameLink(), Player::GetObjectByTypeMask(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), WorldSession::GetPlayer(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), getSelectedUnit(), GetSessionDbcLocale(), WorldObject::GetTerrain(), WorldObject::GetTransport(), Object::GetTypeId(), WorldObject::GetZoneAndAreaId(), Cell::GridX(), Cell::GridY(), TerrainInfo::IsOutdoors(), LANG_CONSOLE_COMMAND, LANG_LIQUID_STATUS, LANG_MAP_POSITION, LANG_PLAYER_NOT_FOUND, LANG_SELECT_CHAR_OR_CREATURE, GridMapLiquidData::level, m_session, Map2ZoneCoordinates(), MAP_ALL_LIQUIDS, MAX_HEIGHT, MapEntry::name, Position::o, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), sMapStore, sWorld, GridMapLiquidData::type_flags, TYPEID_PLAYER, TYPEMASK_CREATURE_OR_GAMEOBJECT, AreaNameInfo::wmoNameOverride, Position::x, CoordPair< LIMIT >::x_coord, Position::y, CoordPair< LIMIT >::y_coord, and Position::z.
Referenced by getCommandTable().
HandleGridsLoadedCount()
bool ChatHandler::HandleGridsLoadedCount (char * args) protected
Definition at line 1458 of file debugcmds.cpp.
References Map::GetLoadedGridsCount(), WorldObject::GetMap(), WorldSession::GetPlayer(), m_session, and PSendSysMessage().
Referenced by getCommandTable().
HandleGroupgoCommand()
bool ChatHandler::HandleGroupgoCommand (char * args) protected
Definition at line 1688 of file Level1.cpp.
References ChatHandler(), ExtractPlayerTarget(), WorldObject::GetClosePoint(), Group::GetFirstMember(), Player::GetGroup(), Map::GetInstanceId(), Group::GetLeaderGuid(), WorldObject::GetMap(), WorldObject::GetMapId(), GetNameLink(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), Player::GetSession(), HasLowerSecurity(), Map::Instanceable(), Map::IsBattleGroundOrArena(), Player::IsBeingTeleported(), LANG_CANNOT_SUMMON_TO_INST, LANG_IS_TELEPORTED, LANG_NOT_IN_GROUP, LANG_SUMMONED_BY, LANG_SUMMONING, m_session, needReportToTarget(), GroupReference::next(), PSendSysMessage(), Player::SaveRecallPosition(), SendSysMessage(), SetSentErrorMessage(), Player::TaxiFlightInterrupt(), and Player::TeleportTo().
Referenced by getCommandTable().
HandleGUIDCommand()
bool ChatHandler::HandleGUIDCommand (char * args) protected
Definition at line 1417 of file Level2.cpp.
References Object::GetDbGuid(), Object::GetObjectGuid(), getSelectedCreature(), ObjectGuid::GetString(), LANG_NO_SELECTION, LANG_OBJECT_GUID, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleGuildCreateCommand()
bool ChatHandler::HandleGuildCreateCommand (char * args) protected
GM command level 3 - Create a guild.
This command allows a GM (level 3) to create a guild.
The "args" parameter contains the name of the guild leader and then the name of the guild.
Definition at line 3481 of file Level3.cpp.
References Guild::Create(), ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractQuotedArg(), Player::GetGuildId(), LANG_GUILD_NOT_CREATED, LANG_PLAYER_IN_GUILD, SendSysMessage(), SetSentErrorMessage(), and sGuildMgr.
Referenced by getCommandTable().
HandleGuildDeleteCommand()
bool ChatHandler::HandleGuildDeleteCommand (char * args) protected
Definition at line 3609 of file Level3.cpp.
References Guild::Disband(), ExtractQuotedArg(), and sGuildMgr.
Referenced by getCommandTable().
HandleGuildInviteCommand()
bool ChatHandler::HandleGuildInviteCommand (char * args) protected
Definition at line 3515 of file Level3.cpp.
References Guild::AddMember(), ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractQuotedArg(), Guild::GetLowestRank(), and sGuildMgr.
Referenced by getCommandTable().
HandleGuildRankCommand()
bool ChatHandler::HandleGuildRankCommand (char * args) protected
Definition at line 3565 of file Level3.cpp.
References MemberSlot::ChangeRank(), ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractUInt32(), Player::GetGuildId(), Player::GetGuildIdFromDB(), Guild::GetLeaderGuid(), Guild::GetLowestRank(), Guild::GetMemberSlot(), GR_GUILDMASTER, GR_OFFICER, Guild::SetLeader(), and sGuildMgr.
Referenced by getCommandTable().
HandleGuildUninviteCommand()
bool ChatHandler::HandleGuildUninviteCommand (char * args) protected
Definition at line 3541 of file Level3.cpp.
References Guild::DelMember(), Guild::Disband(), ExtractPlayerTarget(), Player::GetGuildId(), Player::GetGuildIdFromDB(), and sGuildMgr.
Referenced by getCommandTable().
HandleHelpCommand()
bool ChatHandler::HandleHelpCommand (char * args) protected
Definition at line 33 of file Level0.cpp.
References getCommandTable(), LANG_NO_CMD, SendSysMessage(), and ShowHelpForCommand().
Referenced by getCommandTable().
HandleHideAreaCommand()
bool ChatHandler::HandleHideAreaCommand (char * args) protected
Definition at line 4521 of file Level3.cpp.
References GetAreaFlagByAreaID(), getSelectedPlayer(), Object::GetUInt32Value(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_UNEXPLORE_AREA, PLAYER_EXPLORED_ZONES_1, PLAYER_EXPLORED_ZONES_SIZE, SendSysMessage(), SetSentErrorMessage(), and Object::SetUInt32Value().
Referenced by getCommandTable().
HandleHonorAddCommand()
bool ChatHandler::HandleHonorAddCommand (char * args) protected
Definition at line 3894 of file Level2.cpp.
References getSelectedPlayer(), HasLowerSecurity(), LANG_PLAYER_NOT_FOUND, Player::RewardHonor(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleHonorAddKillCommand()
bool ChatHandler::HandleHonorAddKillCommand (char * args) protected
Definition at line 3916 of file Level2.cpp.
References WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), LANG_PLAYER_NOT_FOUND, m_session, Player::RewardHonor(), SendSysMessage(), SetSentErrorMessage(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleHonorUpdateCommand()
bool ChatHandler::HandleHonorUpdateCommand (char * args) protected
Definition at line 3934 of file Level2.cpp.
References getSelectedPlayer(), HasLowerSecurity(), LANG_PLAYER_NOT_FOUND, SendSysMessage(), SetSentErrorMessage(), and Player::UpdateHonorFields().
Referenced by getCommandTable().
HandleInstanceListBindsCommand()
bool ChatHandler::HandleInstanceListBindsCommand (char * args) protected
Definition at line 6667 of file Level3.cpp.
References DungeonPersistentState::CanReset(), EXTEND_STATE_EXPIRED, EXTEND_STATE_EXTENDED, Player::GetBoundInstances(), MapPersistentState::GetDifficulty(), Player::GetGroup(), MapPersistentState::GetInstanceId(), WorldSession::GetPlayer(), DungeonPersistentState::GetResetTime(), getSelectedPlayer(), GetSessionDbcLocale(), m_session, MAX_DIFFICULTY, PSendSysMessage(), secsToTimeString(), and sMapStore.
Referenced by getCommandTable().
HandleInstanceSaveDataCommand()
bool ChatHandler::HandleInstanceSaveDataCommand (char * args) protected
Definition at line 6789 of file Level3.cpp.
References Map::GetInstanceData(), WorldObject::GetMap(), WorldSession::GetPlayer(), m_session, PSendSysMessage(), InstanceData::SaveToDB(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleInstanceStatsCommand()
bool ChatHandler::HandleInstanceStatsCommand (char * args) protected
Definition at line 6776 of file Level3.cpp.
References PSendSysMessage(), sMapMgr, and sMapPersistentStateMgr.
Referenced by getCommandTable().
HandleInstanceUnbindCommand()
bool ChatHandler::HandleInstanceUnbindCommand (char * args) protected
Definition at line 6720 of file Level3.cpp.
References DungeonPersistentState::CanReset(), Player::GetBoundInstances(), MapPersistentState::GetDifficulty(), MapPersistentState::GetInstanceId(), WorldObject::GetMapId(), WorldSession::GetPlayer(), DungeonPersistentState::GetResetTime(), getSelectedPlayer(), GetSessionDbcLocale(), isNumeric(), m_session, MAX_DIFFICULTY, PSendSysMessage(), secsToTimeString(), sMapStore, and Player::UnbindInstance().
Referenced by getCommandTable().
HandleItemMoveCommand()
bool ChatHandler::HandleItemMoveCommand (char * args) protected
Definition at line 2766 of file Level2.cpp.
References WorldSession::GetPlayer(), INVENTORY_SLOT_BAG_0, Player::IsValidPos(), m_session, and Player::SwapItem().
Referenced by getCommandTable().
HandleKickPlayerCommand()
bool ChatHandler::HandleKickPlayerCommand (char * args) protected
Definition at line 2847 of file Level2.cpp.
References ExtractPlayerTarget(), GetNameLink(), WorldSession::GetPlayer(), Player::GetSession(), HasLowerSecurity(), WorldSession::KickPlayer(), LANG_COMMAND_KICKMESSAGE, LANG_COMMAND_KICKSELF, m_session, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleLearnAllCommand()
bool ChatHandler::HandleLearnAllCommand (char * args) protected
Definition at line 1722 of file Level3.cpp.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, SQLStorageBase::GetMaxEntry(), getSelectedPlayer(), GetTalentSpellCost(), SpellEntry::HasAttribute(), IsSpellHaveEffect(), SpellMgr::IsSpellValid(), LANG_COMMAND_LEARN_MANY_SPELLS, LANG_PLAYER_NOT_FOUND, Player::learnSpell(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, SendSysMessage(), SetSentErrorMessage(), SPELL_ATTR_DO_NOT_DISPLAY, SPELL_ATTR_EX2_USE_SHAPESHIFT_BAR, SPELL_ATTR_PASSIVE, SPELL_EFFECT_LEARN_SPELL, SPELL_EFFECT_PROFICIENCY, SpellEntry::SpellFamilyName, sSpellMgr, sSpellTemplate, and TARGET_NONE.
Referenced by getCommandTable().
HandleLearnAllCraftsCommand()
bool ChatHandler::HandleLearnAllCraftsCommand (char * args) protected
Definition at line 4229 of file Level2.cpp.
References SkillLineEntry::canLink, SkillLineEntry::categoryId, WorldSession::GetPlayer(), HandleLearnSkillRecipesHelper(), SkillLineEntry::id, LANG_COMMAND_LEARN_ALL_CRAFT, m_session, SendSysMessage(), SKILL_CATEGORY_PROFESSION, SKILL_CATEGORY_SECONDARY, and sSkillLineStore.
Referenced by getCommandTable().
HandleLearnAllDefaultCommand()
bool ChatHandler::HandleLearnAllDefaultCommand (char * args) protected
Definition at line 2025 of file Level3.cpp.
References ExtractPlayerTarget(), GetNameLink(), LANG_COMMAND_LEARN_ALL_DEFAULT_AND_QUEST, Player::LearnDefaultSkills(), Player::learnDefaultSpells(), Player::learnQuestRewardedSpells(), and PSendSysMessage().
Referenced by getCommandTable().
HandleLearnAllGMCommand()
bool ChatHandler::HandleLearnAllGMCommand (char * args) protected
Definition at line 1778 of file Level3.cpp.
References WorldSession::GetPlayer(), SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, LANG_LEARNING_GM_SKILLS, Player::learnSpell(), SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SendSysMessage(), and sSpellTemplate.
Referenced by getCommandTable().
HandleLearnAllLangCommand()
bool ChatHandler::HandleLearnAllLangCommand (char * args) protected
Definition at line 2013 of file Level3.cpp.
References WorldSession::GetPlayer(), LANG_COMMAND_LEARN_ALL_LANG, lang_description, LANGUAGES_COUNT, Player::learnSpell(), m_session, SendSysMessage(), and LanguageDesc::spell_id.
Referenced by getCommandTable().
HandleLearnAllMyClassCommand()
bool ChatHandler::HandleLearnAllMyClassCommand (char * args) protected
Definition at line 1835 of file Level3.cpp.
References HandleLearnAllMySpellsCommand(), and HandleLearnAllMyTalentsCommand().
Referenced by getCommandTable().
HandleLearnAllMyPetTalentsCommand()
bool ChatHandler::HandleLearnAllMyPetTalentsCommand (char * args) protected
Definition at line 1935 of file Level3.cpp.
References CreatureInfo::Family, Creature::GetCreatureInfo(), Unit::GetPet(), WorldSession::GetPlayer(), SpellMgr::IsSpellValid(), LANG_COMMAND_LEARN_PET_TALENTS, LANG_NO_PET_FOUND, LANG_WRONG_PET_TYPE, Pet::learnSpellHighRank(), SQLStorage::LookupEntry(), m_session, MAX_TALENT_RANK, TalentTabEntry::petTalentMask, CreatureFamilyEntry::petTalentType, TalentEntry::RankID, sCreatureFamilyStore, SendSysMessage(), Player::SendTalentsInfoData(), SetSentErrorMessage(), sSpellTemplate, sTalentStore, sTalentTabStore, and TalentEntry::TalentTab.
Referenced by getCommandTable().
HandleLearnAllMySpellsCommand()
bool ChatHandler::HandleLearnAllMySpellsCommand (char * args) protected
Definition at line 1842 of file Level3.cpp.
References Unit::getClass(), WorldSession::GetPlayer(), GetTalentSpellCost(), SpellEntry::Id, Player::IsSpellFitByClassAndRace(), SpellMgr::IsSpellValid(), LANG_COMMAND_LEARN_CLASS_SPELLS, Player::learnSpell(), SQLStorage::LookupEntry(), m_session, sChrClassesStore, SendSysMessage(), ChrClassesEntry::spellfamily, SpellEntry::SpellFamilyName, SkillLineAbilityEntry::spellId, SpellEntry::spellLevel, sSkillLineAbilityStore, sSpellMgr, and sSpellTemplate.
Referenced by getCommandTable(), and HandleLearnAllMyClassCommand().
HandleLearnAllMyTalentsCommand()
bool ChatHandler::HandleLearnAllMyTalentsCommand (char * args) protected
Definition at line 1888 of file Level3.cpp.
References TalentTabEntry::ClassMask, Unit::getClassMask(), WorldSession::GetPlayer(), SpellMgr::IsSpellValid(), LANG_COMMAND_LEARN_CLASS_TALENTS, Player::learnSpellHighRank(), SQLStorage::LookupEntry(), m_session, MAX_TALENT_RANK, TalentEntry::RankID, SendSysMessage(), Player::SendTalentsInfoData(), sSpellTemplate, sTalentStore, sTalentTabStore, and TalentEntry::TalentTab.
Referenced by getCommandTable(), and HandleLearnAllMyClassCommand().
HandleLearnAllRecipesCommand()
bool ChatHandler::HandleLearnAllRecipesCommand (char * args) protected
Definition at line 4248 of file Level2.cpp.
References SkillLineEntry::canLink, SkillLineEntry::categoryId, getSelectedPlayer(), GetSessionDbcLocale(), Player::GetSkillMaxPure(), HandleLearnSkillRecipesHelper(), SkillLineEntry::id, LANG_COMMAND_LEARN_ALL_RECIPES, LANG_PLAYER_NOT_FOUND, MAX_LOCALE, SkillLineEntry::name, PSendSysMessage(), SendSysMessage(), Player::SetSkill(), SKILL_CATEGORY_PROFESSION, SKILL_CATEGORY_SECONDARY, sSkillLineStore, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLearnCommand()
bool ChatHandler::HandleLearnCommand (char * args) protected
Definition at line 2039 of file Level3.cpp.
References ExtractLiteralArg(), ExtractSpellIdFromLink(), GetNameLink(), WorldSession::GetPlayer(), getSelectedPlayer(), GetTalentSpellCost(), Player::HasSpell(), SpellMgr::IsSpellValid(), LANG_COMMAND_SPELL_BROKEN, LANG_PLAYER_NOT_FOUND, LANG_TARGET_KNOWN_SPELL, LANG_YOU_KNOWN_SPELL, Player::learnSpell(), Player::learnSpellHighRank(), SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SendSysMessage(), Player::SendTalentsInfoData(), SetSentErrorMessage(), sSpellMgr, and sSpellTemplate.
Referenced by getCommandTable().
HandleLearnSkillRecipesHelper()
void ChatHandler::HandleLearnSkillRecipesHelper (Player * player, uint32 skill_id) protected
Definition at line 4195 of file Level2.cpp.
References SkillLineAbilityEntry::classmask, SkillLineAbilityEntry::forward_spellid, Unit::getClassMask(), SpellMgr::IsSpellValid(), Player::learnSpell(), SQLStorage::LookupEntry(), SkillLineAbilityEntry::racemask, SkillLineAbilityEntry::skillId, SkillLineAbilityEntry::spellId, sSkillLineAbilityStore, and sSpellTemplate.
Referenced by HandleLearnAllCraftsCommand(), and HandleLearnAllRecipesCommand().
HandleLevelUpCommand()
bool ChatHandler::HandleLevelUpCommand (char * args) protected
Definition at line 4417 of file Level3.cpp.
References ExtractArg(), ExtractInt32(), ExtractOptNotLastArg(), ExtractPlayerTarget(), Unit::GetLevel(), Player::GetLevelFromDB(), WorldObject::GetName(), Unit::GetOwner(), Pet::getPetType(), WorldSession::GetPlayer(), getSelectedCreature(), Object::GetTypeId(), Pet::GivePetLevel(), HandleCharacterLevel(), HUNTER_PET, Creature::IsPet(), LANG_YOU_CHANGE_LVL, m_session, petLink(), playerLink(), PSendSysMessage(), STRONG_MAX_LEVEL, and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleLinkAddCommand()
bool ChatHandler::HandleLinkAddCommand (char * args) protected
Definition at line 7510 of file Level3.cpp.
References ExtractUInt32(), QueryResult::Fetch(), ObjectGuid::GetCounter(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), Field::GetUInt32(), LANG_SELECT_CHAR_OR_CREATURE, m_session, Database::PExecute(), Database::PQuery(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleLinkCheckCommand()
bool ChatHandler::HandleLinkCheckCommand (char * args) protected
Definition at line 7671 of file Level3.cpp.
References ExtractUInt32(), QueryResult::Fetch(), ObjectGuid::GetCounter(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), Field::GetUInt32(), LANG_SELECT_CHAR_OR_CREATURE, m_session, Database::PQuery(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleLinkEditCommand()
bool ChatHandler::HandleLinkEditCommand (char * args) protected
Definition at line 7572 of file Level3.cpp.
References ExtractUInt32(), ObjectGuid::GetCounter(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), LANG_SELECT_CHAR_OR_CREATURE, m_session, Database::PExecute(), Database::PQuery(), SendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleLinkGraveCommand()
bool ChatHandler::HandleLinkGraveCommand (char * args) protected
Definition at line 3938 of file Level3.cpp.
References GraveyardManager::AddGraveYardLink(), ALLIANCE, ExtractLiteralArg(), ExtractUInt32(), GetAreaEntryByAreaID(), Map::GetGraveyardManager(), WorldObject::GetMap(), WorldSession::GetPlayer(), WorldObject::GetZoneId(), GRAVEYARD_AREALINK, HORDE, LANG_COMMAND_GRAVEYARDALRLINKED, LANG_COMMAND_GRAVEYARDLINKED, LANG_COMMAND_GRAVEYARDNOEXIST, LANG_COMMAND_GRAVEYARDWRONGZONE, SQLStorage::LookupEntry(), m_session, PSendSysMessage(), SetSentErrorMessage(), sWorldSafeLocsStore, TEAM_BOTH_ALLOWED, and AreaTableEntry::zone.
Referenced by getCommandTable().
HandleLinkRemoveCommand()
bool ChatHandler::HandleLinkRemoveCommand (char * args) protected
Definition at line 7545 of file Level3.cpp.
References ExtractUInt32(), ObjectGuid::GetCounter(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), LANG_SELECT_CHAR_OR_CREATURE, m_session, Database::PExecute(), Database::PQuery(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleLinkToggleCommand()
bool ChatHandler::HandleLinkToggleCommand (char * args) protected
Definition at line 7620 of file Level3.cpp.
References ExtractUInt32(), ObjectGuid::GetCounter(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), LANG_SELECT_CHAR_OR_CREATURE, m_session, Database::PExecute(), Database::PQuery(), SendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleListAreaTriggerCommand()
bool ChatHandler::HandleListAreaTriggerCommand (char * args) protected
Definition at line 4788 of file Level3.cpp.
References AreaTableEntry::area_name, GetAreaEntryByAreaID(), WorldObject::GetAreaId(), TerrainInfo::GetAreaId(), Map::GetId(), WorldObject::GetMap(), Map::GetMapName(), WorldSession::GetPlayer(), GetSessionDbcLocale(), WorldObject::GetTerrain(), Map::IsContinent(), LANG_AREATRIGGER_LIST, LANG_COMMAND_NOTRIGGERFOUND, m_session, AreaTriggerEntry::mapid, PSendSysMessage(), sAreaTriggerStore, SendSysMessage(), ShowTriggerListHelper(), AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by getCommandTable().
HandleListAurasCommand()
bool ChatHandler::HandleListAurasCommand (char * args) protected
Definition at line 4845 of file Level3.cpp.
References ExtractOptUInt32(), SpellAuraHolder::GetAuraByEffectIndex(), Aura::GetAuraDuration(), Aura::GetAuraMaxDuration(), Unit::GetAurasByType(), SpellAuraHolder::GetCasterGuid(), Aura::GetEffIndex(), SpellAuraHolder::GetId(), Aura::GetId(), GetMangosString(), Aura::GetModifier(), getSelectedUnit(), GetSessionDbcLocale(), Unit::GetSpellAuraHolderMap(), SpellAuraHolder::GetSpellProto(), SpellAuraHolder::GetStackAmount(), ObjectGuid::GetString(), GetTalentSpellCost(), SpellAuraHolder::IsPassive(), LANG_COMMAND_TARGET_AURADETAIL, LANG_COMMAND_TARGET_AURASIMPLE, LANG_COMMAND_TARGET_LISTAURAS, LANG_COMMAND_TARGET_LISTAURATYPE, LANG_PASSIVE, LANG_SELECT_CHAR_OR_CREATURE, LANG_TALENT, Modifier::m_auraname, m_session, MAX_EFFECT_INDEX, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), SpellEntry::SpellName, and TOTAL_AURAS.
Referenced by getCommandTable().
HandleListCreatureCommand()
bool ChatHandler::HandleListCreatureCommand (char * args) protected
Definition at line 2690 of file Level3.cpp.
References ExtractLiteralArg(), ExtractOptUInt32(), ExtractUint32KeyFromLink(), ObjectMgr::GetCreatureTemplate(), Field::GetFloat(), WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTerrain(), Field::GetUInt16(), Field::GetUInt32(), TerrainInfo::GetZoneAndAreaId(), LANG_COMMAND_INVALIDCREATUREID, LANG_CREATURE_LIST_CHAT, LANG_CREATURE_LIST_CONSOLE, m_session, CreatureInfo::Name, operator<(), Database::PQuery(), PSendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleListItemCommand()
bool ChatHandler::HandleListItemCommand (char * args) protected
Definition at line 2240 of file Level3.cpp.
References CharacterDatabase, ExtractOptUInt32(), ExtractUint32KeyFromLink(), QueryResult::Fetch(), Field::GetCppString(), ObjectMgr::GetItemPrototype(), QueryResult::GetRowCount(), Field::GetUInt32(), Player::IsBankPos(), Player::IsEquipmentPos(), Player::IsInventoryPos(), LANG_COMMAND_ITEMIDINVALID, LANG_COMMAND_LISTITEMMESSAGE, LANG_COMMAND_NOITEMFOUND, LANG_ITEMLIST_AUCTION, LANG_ITEMLIST_GUILD, LANG_ITEMLIST_MAIL, LANG_ITEMLIST_SLOT, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleListObjectCommand()
bool ChatHandler::HandleListObjectCommand (char * args) protected
Definition at line 2460 of file Level3.cpp.
References ExtractLiteralArg(), ExtractOptUInt32(), ExtractUint32KeyFromLink(), Field::GetFloat(), ObjectMgr::GetGameObjectInfo(), WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTerrain(), Field::GetUInt16(), Field::GetUInt32(), TerrainInfo::GetZoneAndAreaId(), LANG_COMMAND_LISTOBJINVALIDID, LANG_GO_LIST_CHAT, LANG_GO_LIST_CONSOLE, m_session, GameObjectInfo::name, operator<(), Database::PQuery(), PSendSysMessage(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleListTalentsCommand()
bool ChatHandler::HandleListTalentsCommand (char * args) protected
Definition at line 4940 of file Level3.cpp.
References getSelectedPlayer(), GetSessionDbcLocale(), Player::GetSpellMap(), GetTalentSpellCost(), LANG_LIST_TALENTS_COUNT, LANG_LIST_TALENTS_TITLE, LANG_NO_CHAR_SELECTED, SQLStorage::LookupEntry(), PLAYERSPELL_REMOVED, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), ShowSpellListHelper(), and sSpellTemplate.
Referenced by getCommandTable().
HandleLoadScriptsCommand()
bool ChatHandler::HandleLoadScriptsCommand (char * args) protected
Definition at line 1140 of file Level3.cpp.
Referenced by getCommandTable().
HandleLookupAccountEmailCommand()
bool ChatHandler::HandleLookupAccountEmailCommand (char * args) protected
Definition at line 4325 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, Database::PQuery(), and ShowAccountListHelper().
Referenced by getCommandTable().
HandleLookupAccountIpCommand()
bool ChatHandler::HandleLookupAccountIpCommand (char * args) protected
Definition at line 4343 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, Database::PQuery(), and ShowAccountListHelper().
Referenced by getCommandTable().
HandleLookupAccountNameCommand()
bool ChatHandler::HandleLookupAccountNameCommand (char * args) protected
Definition at line 4362 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, AccountMgr::normalizeString(), Database::PQuery(), and ShowAccountListHelper().
Referenced by getCommandTable().
HandleLookupAchievementCommand()
bool ChatHandler::HandleLookupAchievementCommand (char * args) protected
Definition at line 1486 of file Level2.cpp.
References CompletedAchievementData::date, Player::GetAchievementMgr(), AchievementMgr::GetCompleteData(), getSelectedPlayer(), GetSessionDbcLocale(), LANG_COMMAND_ACHIEVEMENT_NOTFOUND, MAX_LOCALE, AchievementEntry::name, sAchievementStore, SendSysMessage(), ShowAchievementListHelper(), Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupAreaCommand()
bool ChatHandler::HandleLookupAreaCommand (char * args) protected
Definition at line 1385 of file Level1.cpp.
References AreaTableEntry::area_name, GetSessionDbcLocale(), AreaTableEntry::ID, LANG_COMMAND_NOAREAFOUND, localeNames, m_session, MAX_LOCALE, sAreaStore, SendSysMessage(), Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupCreatureCommand()
bool ChatHandler::HandleLookupCreatureCommand (char * args) protected
Definition at line 3303 of file Level3.cpp.
References SQLStorageBase::GetMaxEntry(), GetSessionDbLocaleIndex(), LANG_COMMAND_NOCREATUREFOUND, LANG_CREATURE_ENTRY_LIST_CHAT, LANG_CREATURE_ENTRY_LIST_CONSOLE, SQLStorage::LookupEntry(), m_session, CreatureInfo::Name, PSendSysMessage(), sCreatureStorage, SendSysMessage(), sObjectMgr, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupEventCommand()
bool ChatHandler::HandleLookupEventCommand (char * args) protected
Definition at line 3952 of file Level2.cpp.
References GameEventData::description, GetMangosString(), LANG_ACTIVE, LANG_EVENT_ENTRY_LIST_CHAT, LANG_EVENT_ENTRY_LIST_CONSOLE, LANG_NOEVENTFOUND, m_session, PSendSysMessage(), SendSysMessage(), sGameEventMgr, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupFactionCommand()
bool ChatHandler::HandleLookupFactionCommand (char * args) protected
Definition at line 1601 of file Level2.cpp.
References Player::GetReputationMgr(), getSelectedPlayer(), GetSessionDbcLocale(), ReputationMgr::GetState(), LANG_COMMAND_FACTION_NOTFOUND, MAX_LOCALE, FactionEntry::name, SendSysMessage(), sFactionStore, ShowFactionListHelper(), Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupItemCommand()
bool ChatHandler::HandleLookupItemCommand (char * args) protected
Definition at line 2943 of file Level3.cpp.
References SQLStorageBase::GetMaxEntry(), WorldSession::GetPlayer(), GetSessionDbLocaleIndex(), LANG_COMMAND_NOITEMFOUND, SQLStorage::LookupEntry(), m_session, ItemPrototype::Name1, SendSysMessage(), ShowItemListHelper(), sItemStorage, sObjectMgr, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupItemSetCommand()
bool ChatHandler::HandleLookupItemSetCommand (char * args) protected
Definition at line 2985 of file Level3.cpp.
References GetSessionDbcLocale(), LANG_COMMAND_NOITEMSETFOUND, LANG_ITEMSET_LIST_CHAT, LANG_ITEMSET_LIST_CONSOLE, localeNames, m_session, MAX_LOCALE, ItemSetEntry::name, PSendSysMessage(), SendSysMessage(), sItemSetStore, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupObjectCommand()
bool ChatHandler::HandleLookupObjectCommand (char * args) protected
Definition at line 3350 of file Level3.cpp.
References SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), GetSessionDbLocaleIndex(), LANG_COMMAND_NOGAMEOBJECTFOUND, LANG_GO_ENTRY_LIST_CHAT, LANG_GO_ENTRY_LIST_CONSOLE, m_session, GameObjectLocale::Name, PSendSysMessage(), SendSysMessage(), sGOStorage, sObjectMgr, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupPlayerAccountCommand()
bool ChatHandler::HandleLookupPlayerAccountCommand (char * args) protected
Definition at line 4453 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, LookupPlayerSearchCommand(), AccountMgr::normalizeString(), and Database::PQuery().
Referenced by getCommandTable().
HandleLookupPlayerEmailCommand()
bool ChatHandler::HandleLookupPlayerEmailCommand (char * args) protected
Definition at line 4474 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, LookupPlayerSearchCommand(), and Database::PQuery().
Referenced by getCommandTable().
HandleLookupPlayerIpCommand()
bool ChatHandler::HandleLookupPlayerIpCommand (char * args) protected
Definition at line 4435 of file Level2.cpp.
References _CONCAT3_, _LIKE_, Database::escape_string(), ExtractOptUInt32(), ExtractQuotedOrLiteralArg(), LoginDatabase, LookupPlayerSearchCommand(), and Database::PQuery().
Referenced by getCommandTable().
HandleLookupPoolCommand()
bool ChatHandler::HandleLookupPoolCommand (char * args) protected
Definition at line 4557 of file Level2.cpp.
References PoolTemplateData::description, LANG_NO_POOL, SendSysMessage(), ShowPoolListHelper(), sPoolMgr, and strToLower().
Referenced by getCommandTable().
HandleLookupQuestCommand()
bool ChatHandler::HandleLookupQuestCommand (char * args) protected
Definition at line 3261 of file Level3.cpp.
References Quest::GetQuestId(), getSelectedPlayer(), GetSessionDbLocaleIndex(), Quest::GetTitle(), LANG_COMMAND_NOQUESTFOUND, SendSysMessage(), ShowQuestListHelper(), sObjectMgr, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupSkillCommand()
bool ChatHandler::HandleLookupSkillCommand (char * args) protected
Definition at line 3045 of file Level3.cpp.
References GetMangosString(), getSelectedPlayer(), GetSessionDbcLocale(), Player::GetSkillBonusPermanent(), Player::GetSkillBonusTemporary(), Player::GetSkillMaxPure(), Player::GetSkillValuePure(), Player::HasSkill(), LANG_COMMAND_NOSKILLFOUND, LANG_KNOWN, LANG_SKILL_LIST_CHAT, LANG_SKILL_LIST_CONSOLE, LANG_SKILL_VALUES, localeNames, m_session, MAX_LOCALE, SkillLineEntry::name, PSendSysMessage(), SendSysMessage(), sSkillLineStore, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupSpellCommand()
bool ChatHandler::HandleLookupSpellCommand (char * args) protected
Definition at line 3170 of file Level3.cpp.
References DEFAULT_LOCALE, SQLStorageBase::GetMaxEntry(), getSelectedPlayer(), GetSessionDbcLocale(), LANG_COMMAND_NOSPELLFOUND, SQLStorage::LookupEntry(), MAX_LOCALE, SendSysMessage(), ShowSpellListHelper(), SpellEntry::SpellName, sSpellTemplate, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleLookupTaxiNodeCommand()
bool ChatHandler::HandleLookupTaxiNodeCommand (char * args) protected
Definition at line 3411 of file Level3.cpp.
References GetSessionDbcLocale(), LANG_COMMAND_NOTAXINODEFOUND, LANG_TAXINODE_ENTRY_LIST_CHAT, LANG_TAXINODE_ENTRY_LIST_CONSOLE, localeNames, m_session, TaxiNodesEntry::map_id, MAX_LOCALE, TaxiNodesEntry::name, PSendSysMessage(), SendSysMessage(), sTaxiNodesStore, Utf8FitTo(), Utf8toWStr(), wstrToLower(), TaxiNodesEntry::x, TaxiNodesEntry::y, and TaxiNodesEntry::z.
Referenced by getCommandTable().
HandleLookupTeleCommand()
bool ChatHandler::HandleLookupTeleCommand (char * args) protected
Definition at line 1452 of file Level1.cpp.
References LANG_COMMAND_TELE_LOCATION, LANG_COMMAND_TELE_NOLOCATION, LANG_COMMAND_TELE_PARAMETER, m_session, GameTele::name, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), sObjectMgr, Utf8toWStr(), GameTele::wnameLow, and wstrToLower().
Referenced by getCommandTable().
HandleLookupTitleCommand()
bool ChatHandler::HandleLookupTitleCommand (char * args) protected
Definition at line 4891 of file Level2.cpp.
References CharTitlesEntry::bit_index, GetMangosString(), WorldObject::GetName(), getSelectedPlayer(), GetSessionDbcLocale(), Object::GetUInt32Value(), Player::HasTitle(), LANG_ACTIVE, LANG_COMMAND_NOTITLEFOUND, LANG_KNOWN, LANG_TITLE_LIST_CHAT, LANG_TITLE_LIST_CONSOLE, localeNames, m_session, MAX_LOCALE, CharTitlesEntry::name, PLAYER_CHOSEN_TITLE, PSendSysMessage(), sCharTitlesStore, SendSysMessage(), Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleMailBoxCommand()
bool ChatHandler::HandleMailBoxCommand (char * args) protected
Definition at line 4677 of file Level3.cpp.
References Object::GetObjectGuid(), WorldSession::GetPlayer(), m_session, and WorldSession::SendShowMailBox().
Referenced by getCommandTable().
HandleMaxSkillCommand()
bool ChatHandler::HandleMaxSkillCommand (char * args) protected
Definition at line 1520 of file Level3.cpp.
References getSelectedPlayer(), LANG_NO_CHAR_SELECTED, SendSysMessage(), SetSentErrorMessage(), and Player::UpdateSkillsForLevel().
Referenced by getCommandTable().
HandleMmap()
bool ChatHandler::HandleMmap (char * args) protected
Definition at line 7383 of file Level3.cpp.
References CONFIG_BOOL_MMAP_ENABLED, ExtractOnOff(), PSendSysMessage(), SendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleMmapLoadedTilesCommand()
bool ChatHandler::HandleMmapLoadedTilesCommand (char * args) protected
Definition at line 5383 of file Level2.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), MMAP::MMapManager::GetNavMesh(), MMAP::MMapManager::GetNavMeshQuery(), WorldSession::GetPlayer(), m_session, and PSendSysMessage().
Referenced by getCommandTable().
HandleMmapLocCommand()
bool ChatHandler::HandleMmapLocCommand (char * args) protected
Definition at line 5328 of file Level2.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), MMAP::MMapManager::GetNavMesh(), MMAP::MMapManager::GetNavMeshQuery(), WorldSession::GetPlayer(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), INVALID_POLYREF, m_session, PSendSysMessage(), SIZE_OF_GRIDS, and VERTEX_SIZE.
Referenced by getCommandTable().
HandleMmapPathCommand()
bool ChatHandler::HandleMmapPathCommand (char * args) protected
Definition at line 5220 of file Level2.cpp.
References PathFinder::calculate(), MMAP::MMapFactory::createOrGetMMapManager(), PathFinder::getActualEndPosition(), PathFinder::getEndPosition(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), WorldObject::GetName(), PathFinder::getPath(), PathFinder::getPathType(), WorldSession::GetPlayer(), WorldObject::GetPosition(), getSelectedUnit(), PathFinder::getStartPosition(), WorldObject::GetTransport(), Player::IsGameMaster(), Movement::MoveSplineInit::Launch(), m_session, Movement::MoveSplineInit::MovebyPath(), PSendSysMessage(), PathFinder::setUseStrightPath(), Movement::MoveSplineInit::SetWalk(), SIZEFMTD, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, and VISUAL_WAYPOINT.
Referenced by getCommandTable().
HandleMmapStatsCommand()
bool ChatHandler::HandleMmapStatsCommand (char * args) protected
Definition at line 5410 of file Level2.cpp.
References CONFIG_BOOL_MMAP_ENABLED, MMAP::MMapFactory::createOrGetMMapManager(), WorldObject::GetInstanceId(), MMAP::MMapManager::getLoadedMapsCount(), MMAP::MMapManager::getLoadedTilesCount(), WorldObject::GetMapId(), MMAP::MMapManager::GetNavMesh(), WorldSession::GetPlayer(), m_session, PSendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleMmapTestArea()
bool ChatHandler::HandleMmapTestArea (char * args) protected
Definition at line 7407 of file Level3.cpp.
References PathFinder::calculate(), ExtractFloat(), WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), WorldSession::GetPlayer(), WorldObject::GetPosition(), m_session, PSendSysMessage(), SIZEFMTD, and Cell::VisitGridObjects().
Referenced by getCommandTable().
HandleMmapTestHeight()
bool ChatHandler::HandleMmapTestHeight (char * args) protected
Definition at line 7446 of file Level3.cpp.
References Unit::CastSpell(), ExtractFloat(), Object::GetGuidStr(), WorldObject::GetMap(), WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), WorldSession::GetPlayer(), WorldObject::GetPosition(), Map::GetReachableRandomPosition(), getSelectedUnit(), Object::GetTypeId(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, TRIGGERED_NONE, TYPEID_PLAYER, TYPEID_UNIT, and VISUAL_WAYPOINT.
Referenced by getCommandTable().
HandleModifyAgilityCommand()
bool ChatHandler::HandleModifyAgilityCommand (char * args) protected
Definition at line 8014 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_AGILITY.
Referenced by getCommandTable().
HandleModifyArcaneCommand()
bool ChatHandler::HandleModifyArcaneCommand (char * args) protected
Definition at line 8064 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_ARCANE.
Referenced by getCommandTable().
HandleModifyArenaCommand()
bool ChatHandler::HandleModifyArenaCommand (char * args) protected
Definition at line 3820 of file Level3.cpp.
References Player::GetArenaPoints(), GetNameLink(), getSelectedPlayer(), LANG_COMMAND_MODIFY_ARENA, LANG_PLAYER_NOT_FOUND, Player::ModifyArenaPoints(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyArmorCommand()
bool ChatHandler::HandleModifyArmorCommand (char * args) protected
Definition at line 8034 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_ARMOR.
Referenced by getCommandTable().
HandleModifyASpeedCommand()
bool ChatHandler::HandleModifyASpeedCommand (char * args) protected
Definition at line 1013 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), Unit::IsTaxiFlying(), LANG_BAD_VALUE, LANG_CHAR_IN_FLIGHT, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_ASPEED, LANG_YOURS_ASPEED_CHANGED, MOVE_FLIGHT, MOVE_RUN, MOVE_SWIM, MOVE_WALK, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::UpdateSpeed().
Referenced by getCommandTable().
HandleModifyBlockCommand()
bool ChatHandler::HandleModifyBlockCommand (char * args) protected
Definition at line 8110 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_BLOCK_CHANCE.
Referenced by getCommandTable().
HandleModifyBWalkCommand()
bool ChatHandler::HandleModifyBWalkCommand (char * args) protected
Definition at line 1151 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), Unit::IsTaxiFlying(), LANG_BAD_VALUE, LANG_CHAR_IN_FLIGHT, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_BACK_SPEED, LANG_YOURS_BACK_SPEED_CHANGED, MOVE_RUN_BACK, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::UpdateSpeed().
Referenced by getCommandTable().
HandleModifyDodgeCommand()
bool ChatHandler::HandleModifyDodgeCommand (char * args) protected
Definition at line 8115 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_DODGE_CHANCE.
Referenced by getCommandTable().
HandleModifyDrunkCommand()
bool ChatHandler::HandleModifyDrunkCommand (char * args) protected
Definition at line 2066 of file Level1.cpp.
References getSelectedPlayer().
Referenced by getCommandTable().
HandleModifyEnergyCommand()
bool ChatHandler::HandleModifyEnergyCommand (char * args) protected
Definition at line 753 of file Level1.cpp.
References ChatHandler(), DETAIL_LOG, GetMangosString(), Unit::GetMaxPower(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_CURRENT_ENERGY, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_ENERGY, LANG_YOURS_ENERGY_CHANGED, needReportToTarget(), POWER_ENERGY, PSendSysMessage(), SendSysMessage(), Unit::SetMaxPower(), Unit::SetPower(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyFactionCommand()
bool ChatHandler::HandleModifyFactionCommand (char * args) protected
Definition at line 865 of file Level1.cpp.
References ExtractOptUInt32(), ExtractUint32KeyFromLink(), Unit::GetFaction(), Object::GetGUIDLow(), getSelectedCreature(), Object::GetUInt32Value(), LANG_CURRENT_FACTION, LANG_NO_CHAR_SELECTED, LANG_SELECT_CREATURE, LANG_WRONG_FACTION, LANG_YOU_CHANGE_FACTION, PSendSysMessage(), SendSysMessage(), Unit::setFaction(), SetSentErrorMessage(), Object::SetUInt32Value(), sFactionTemplateStore, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_FLAGS, and UNIT_NPC_FLAGS.
Referenced by getCommandTable().
HandleModifyFireCommand()
bool ChatHandler::HandleModifyFireCommand (char * args) protected
Definition at line 8044 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_FIRE.
Referenced by getCommandTable().
HandleModifyFlyCommand()
bool ChatHandler::HandleModifyFlyCommand (char * args) protected
Definition at line 1196 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_FLY_SPEED, LANG_YOURS_FLY_SPEED_CHANGED, MOVE_FLIGHT, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::UpdateSpeed().
Referenced by getCommandTable().
HandleModifyFrostCommand()
bool ChatHandler::HandleModifyFrostCommand (char * args) protected
Definition at line 8054 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_FROST.
Referenced by getCommandTable().
HandleModifyGenderCommand()
bool ChatHandler::HandleModifyGenderCommand (char * args) protected
Definition at line 7294 of file Level3.cpp.
References ChatHandler(), GENDER_FEMALE, GENDER_MALE, Unit::getClass(), Player::GetDrunkValue(), Unit::getGender(), GetNameLink(), Unit::getRace(), getSelectedPlayer(), Player::InitDisplayIds(), LANG_MUST_MALE_OR_FEMALE, LANG_PLAYER_NOT_FOUND, LANG_YOU_CHANGE_GENDER, LANG_YOUR_GENDER_CHANGED, needReportToTarget(), PLAYER_BYTES_3, PSendSysMessage(), SendSysMessage(), Object::SetByteValue(), SetSentErrorMessage(), Object::SetUInt16Value(), sObjectMgr, UNIT_BYTES_0_OFFSET_GENDER, and UNIT_FIELD_BYTES_0.
Referenced by getCommandTable().
HandleModifyHolyCommand()
bool ChatHandler::HandleModifyHolyCommand (char * args) protected
Definition at line 8039 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_HOLY.
Referenced by getCommandTable().
HandleModifyHonorCommand()
bool ChatHandler::HandleModifyHonorCommand (char * args) protected
Definition at line 1339 of file Level1.cpp.
References Player::GetHonorPoints(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_COMMAND_MODIFY_HONOR, LANG_PLAYER_NOT_FOUND, Player::ModifyHonorPoints(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyHPCommand()
bool ChatHandler::HandleModifyHPCommand (char * args) protected
Definition at line 677 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_HP, LANG_YOURS_HP_CHANGED, needReportToTarget(), PSendSysMessage(), SendSysMessage(), Unit::SetHealth(), Unit::SetMaxHealth(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyIntellectCommand()
bool ChatHandler::HandleModifyIntellectCommand (char * args) protected
Definition at line 8024 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_INTELLECT.
Referenced by getCommandTable().
HandleModifyManaCommand()
bool ChatHandler::HandleModifyManaCommand (char * args) protected
Definition at line 715 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_MANA, LANG_YOURS_MANA_CHANGED, needReportToTarget(), POWER_MANA, PSendSysMessage(), SendSysMessage(), Unit::SetMaxPower(), Unit::SetPower(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyMeleeApCommand()
bool ChatHandler::HandleModifyMeleeApCommand (char * args) protected
Definition at line 8069 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_MELEE_AP.
Referenced by getCommandTable().
HandleModifyMeleeCritCommand()
bool ChatHandler::HandleModifyMeleeCritCommand (char * args) protected
Definition at line 8085 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_MELEE_CRIT.
Referenced by getCommandTable().
HandleModifyMeleeHasteCommand()
bool ChatHandler::HandleModifyMeleeHasteCommand (char * args) protected
Definition at line 8095 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_MELEE_HASTE.
Referenced by getCommandTable().
HandleModifyMoneyCommand()
bool ChatHandler::HandleModifyMoneyCommand (char * args) protected
Definition at line 1277 of file Level1.cpp.
References ChatHandler(), DETAIL_LOG, GetMangosString(), Player::GetMoney(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_CURRENT_MONEY, LANG_NEW_MONEY, LANG_NO_CHAR_SELECTED, LANG_YOU_GIVE_MONEY, LANG_YOU_TAKE_ALL_MONEY, LANG_YOU_TAKE_MONEY, LANG_YOURS_ALL_MONEY_GONE, LANG_YOURS_MONEY_GIVEN, LANG_YOURS_MONEY_TAKEN, MAX_MONEY_AMOUNT, Player::ModifyMoney(), needReportToTarget(), PSendSysMessage(), SendSysMessage(), Player::SetMoney(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyMorphCommand()
bool ChatHandler::HandleModifyMorphCommand (char * args) protected
Definition at line 2818 of file Level2.cpp.
References WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), LANG_BAD_VALUE, m_session, sCreatureDisplayInfoStore, SendSysMessage(), Unit::SetDisplayId(), SetSentErrorMessage(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleModifyMountCommand()
bool ChatHandler::HandleModifyMountCommand (char * args) protected
Definition at line 1271 of file Level1.cpp.
References getSelectedPlayer(), and ModifyMountCommandHelper().
Referenced by getCommandTable().
HandleModifyNatureCommand()
bool ChatHandler::HandleModifyNatureCommand (char * args) protected
Definition at line 8049 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_NATURE.
Referenced by getCommandTable().
HandleModifyParryCommand()
bool ChatHandler::HandleModifyParryCommand (char * args) protected
Definition at line 8120 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_PARRY_CHANCE.
Referenced by getCommandTable().
HandleModifyPhaseCommand()
bool ChatHandler::HandleModifyPhaseCommand (char * args) protected
Definition at line 2871 of file Level2.cpp.
References WorldSession::GetPlayer(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), m_session, Unit::SetPhaseMask(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleModifyRageCommand()
bool ChatHandler::HandleModifyRageCommand (char * args) protected
Definition at line 793 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_RAGE, LANG_YOURS_RAGE_CHANGED, needReportToTarget(), POWER_RAGE, PSendSysMessage(), SendSysMessage(), Unit::SetMaxPower(), Unit::SetPower(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyRangedApCommand()
bool ChatHandler::HandleModifyRangedApCommand (char * args) protected
Definition at line 8075 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RANGE_AP.
Referenced by getCommandTable().
HandleModifyRangedHasteCommand()
bool ChatHandler::HandleModifyRangedHasteCommand (char * args) protected
Definition at line 8100 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RANGE_HASTE.
Referenced by getCommandTable().
HandleModifyRepCommand()
bool ChatHandler::HandleModifyRepCommand (char * args) protected
Definition at line 1661 of file Level2.cpp.
References ExtractInt32(), ExtractLiteralArg(), ExtractOptInt32(), ExtractUint32KeyFromLink(), GetMangosString(), GetNameLink(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), getSelectedPlayer(), GetSessionDbcLocale(), HasLowerSecurity(), FactionEntry::HasReputation(), LANG_COMMAND_FACTION_DELTA, LANG_COMMAND_FACTION_INVPARAM, LANG_COMMAND_FACTION_NOREP_ERROR, LANG_COMMAND_FACTION_UNKNOWN, LANG_COMMAND_MODIFY_REP, LANG_PLAYER_NOT_FOUND, MAX_REPUTATION_RANK, FactionEntry::name, ReputationMgr::PointsInRank, PSendSysMessage(), ReputationRankStrIndex, SendSysMessage(), ReputationMgr::SetReputation(), SetSentErrorMessage(), sFactionStore, Utf8toWStr(), and wstrToLower().
Referenced by getCommandTable().
HandleModifyRunicPowerCommand()
bool ChatHandler::HandleModifyRunicPowerCommand (char * args) protected
Definition at line 831 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), LANG_BAD_VALUE, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_RUNIC_POWER, LANG_YOURS_RUNIC_POWER_CHANGED, needReportToTarget(), POWER_RUNIC_POWER, PSendSysMessage(), SendSysMessage(), Unit::SetMaxPower(), Unit::SetPower(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleModifyScaleCommand()
bool ChatHandler::HandleModifyScaleCommand (char * args) protected
Definition at line 1232 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), LANG_BAD_VALUE, LANG_SELECT_CHAR_OR_CREATURE, LANG_YOU_CHANGE_SIZE, LANG_YOURS_SIZE_CHANGED, needReportToTarget(), PSendSysMessage(), SendSysMessage(), Object::SetObjectScale(), SetSentErrorMessage(), TYPEID_PLAYER, and Unit::UpdateModelData().
Referenced by getCommandTable().
HandleModifyShadowCommand()
bool ChatHandler::HandleModifyShadowCommand (char * args) protected
Definition at line 8059 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_RES_SHADOW.
Referenced by getCommandTable().
HandleModifySpeedCommand()
bool ChatHandler::HandleModifySpeedCommand (char * args) protected
Definition at line 1061 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), Unit::IsTaxiFlying(), LANG_BAD_VALUE, LANG_CHAR_IN_FLIGHT, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_SPEED, LANG_YOURS_SPEED_CHANGED, MOVE_RUN, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::UpdateSpeed().
Referenced by getCommandTable().
HandleModifySpellCritCommand()
bool ChatHandler::HandleModifySpellCritCommand (char * args) protected
Definition at line 8090 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_SPELL_CRIT.
Referenced by getCommandTable().
HandleModifySpellHasteCommand()
bool ChatHandler::HandleModifySpellHasteCommand (char * args) protected
Definition at line 8105 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_SPELL_HASTE.
Referenced by getCommandTable().
HandleModifySpellPowerCommand()
bool ChatHandler::HandleModifySpellPowerCommand (char * args) protected
Definition at line 8080 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_SPELL_POWER.
Referenced by getCommandTable().
HandleModifySpiritCommand()
bool ChatHandler::HandleModifySpiritCommand (char * args) protected
Definition at line 8029 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_SPIRIT.
Referenced by getCommandTable().
HandleModifyStaminaCommand()
bool ChatHandler::HandleModifyStaminaCommand (char * args) protected
Definition at line 8019 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_STAMINA.
Referenced by getCommandTable().
HandleModifyStandStateCommand()
bool ChatHandler::HandleModifyStandStateCommand (char * args) protected
Definition at line 3880 of file Level2.cpp.
References ExtractUInt32(), WorldSession::GetPlayer(), Unit::HandleEmoteState(), m_session, and sEmotesStore.
Referenced by getCommandTable().
HandleModifyStrengthCommand()
bool ChatHandler::HandleModifyStrengthCommand (char * args) protected
Definition at line 8009 of file Level3.cpp.
References ModifyStatCommandHelper(), and SPELL_MOD_STRENGTH.
Referenced by getCommandTable().
HandleModifySwimCommand()
bool ChatHandler::HandleModifySwimCommand (char * args) protected
Definition at line 1106 of file Level1.cpp.
References ChatHandler(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), Unit::IsTaxiFlying(), LANG_BAD_VALUE, LANG_CHAR_IN_FLIGHT, LANG_NO_CHAR_SELECTED, LANG_YOU_CHANGE_SWIM_SPEED, LANG_YOURS_SWIM_SPEED_CHANGED, MOVE_SWIM, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::UpdateSpeed().
Referenced by getCommandTable().
HandleModifyTalentCommand()
bool ChatHandler::HandleModifyTalentCommand (char * args) protected
Definition at line 929 of file Level1.cpp.
References Unit::GetOwner(), getSelectedUnit(), Object::GetTypeId(), HasLowerSecurity(), LANG_NO_CHAR_SELECTED, SendSysMessage(), SetSentErrorMessage(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleMovegensCommand()
bool ChatHandler::HandleMovegensCommand (char * args) protected
Definition at line 6270 of file Level3.cpp.
References MotionMaster::begin(), CHASE_MOTION_TYPE, ChaseModes, CONFUSED_MOTION_TYPE, DISTRACT_MOTION_TYPE, EFFECT_MOTION_TYPE, MotionMaster::end(), FLEEING_MOTION_TYPE, FOLLOW_MOTION_TYPE, FORMATION_MOTION_TYPE, TargetedMovementGeneratorMedium< T, D >::GetAngle(), ChaseMovementGenerator::GetCurrentMode(), TargetedMovementGeneratorMedium< T, D >::GetCurrentTarget(), MotionMaster::GetDestination(), Unit::GetFormationSlot(), Object::GetGUIDLow(), Object::GetGuidStr(), Unit::GetMotionMaster(), WorldObject::GetName(), TargetedMovementGeneratorMedium< T, D >::GetOffset(), getSelectedUnit(), Object::GetTypeId(), HOME_MOTION_TYPE, IDLE_MOTION_TYPE, LANG_MOVEGENS_CHASE_CREATURE, LANG_MOVEGENS_CHASE_NULL, LANG_MOVEGENS_CHASE_PLAYER, LANG_MOVEGENS_CONFUSED, LANG_MOVEGENS_DISTRACT, LANG_MOVEGENS_EFFECT, LANG_MOVEGENS_FEAR, LANG_MOVEGENS_FLIGHT, LANG_MOVEGENS_FOLLOW_CREATURE, LANG_MOVEGENS_FOLLOW_NULL, LANG_MOVEGENS_FOLLOW_PLAYER, LANG_MOVEGENS_HOME_CREATURE, LANG_MOVEGENS_HOME_PLAYER, LANG_MOVEGENS_IDLE, LANG_MOVEGENS_POINT, LANG_MOVEGENS_RANDOM, LANG_MOVEGENS_UNKNOWN, LANG_MOVEGENS_WAYPOINT, LANG_SELECT_CHAR_OR_CREATURE, POINT_MOTION_TYPE, PSendSysMessage(), RANDOM_MOTION_TYPE, SendSysMessage(), SetSentErrorMessage(), TAXI_MOTION_TYPE, TYPEID_PLAYER, TYPEID_UNIT, and WAYPOINT_MOTION_TYPE.
Referenced by getCommandTable().
HandleMovespeedShowCommand()
bool ChatHandler::HandleMovespeedShowCommand (char * args) protected
Definition at line 6352 of file Level3.cpp.
References WorldObject::GetName(), getSelectedUnit(), Unit::GetSpeed(), LANG_SELECT_CHAR_OR_CREATURE, MOVE_FLIGHT, MOVE_RUN, MOVE_SWIM, MOVE_WALK, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleMuteCommand()
bool ChatHandler::HandleMuteCommand (char * args) protected
Definition at line 67 of file Level2.cpp.
References ChatHandler(), ExtractOptNotLastArg(), ExtractPlayerTarget(), ExtractQuotedOrLiteralArg(), ExtractUInt32(), WorldSession::GetAccountId(), WorldObject::GetName(), WorldSession::GetPlayerName(), Player::GetSession(), HasLowerSecurity(), LANG_YOU_DISABLE_CHAT, LANG_YOUR_CHAT_DISABLED, LoginDatabase, WorldSession::m_muteTime, m_session, Database::PExecute(), playerLink(), PSendSysMessage(), sObjectMgr, sWorld, and UI64FMTD.
Referenced by getCommandTable().
HandleNamegoCommand()
bool ChatHandler::HandleNamegoCommand (char * args) protected
Definition at line 398 of file Level1.cpp.
References ChatHandler(), ExtractPlayerTarget(), Player::GetBattleGroundId(), Player::GetBattleGroundTypeId(), WorldObject::GetClosePoint(), Player::GetGroup(), Map::GetInstanceId(), Group::GetLeaderGuid(), GetMangosString(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetZoneId(), HasLowerSecurity(), Map::Instanceable(), Map::IsBattleGroundOrArena(), Player::IsBeingTeleported(), Map::IsDungeon(), Player::IsGameMaster(), Object::IsInWorld(), LANG_CANNOT_GO_TO_BG_FROM_BG, LANG_CANNOT_GO_TO_BG_GM, LANG_CANNOT_SUMMON_TO_INST, LANG_CANT_TELEPORT_SELF, LANG_IS_TELEPORTED, LANG_OFFLINE, LANG_SUMMONED_BY, LANG_SUMMONING, m_session, needReportToTarget(), playerLink(), PSendSysMessage(), Player::SavePositionInDB(), Player::SaveRecallPosition(), Player::SetBattleGroundEntryPoint(), Player::SetBattleGroundId(), SetSentErrorMessage(), Player::TaxiFlightInterrupt(), and Player::TeleportTo().
Referenced by getCommandTable(), and PlayerbotChatHandler::teleport().
HandleNearGraveCommand()
bool ChatHandler::HandleNearGraveCommand (char * args) protected
Definition at line 3984 of file Level3.cpp.
References ALLIANCE, GraveyardManager::FindGraveYardData(), WorldObject::GetAreaId(), GraveyardManager::GetClosestGraveYard(), Map::GetGraveyardManager(), GetMangosString(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetZoneId(), HORDE, WorldSafeLocsEntry::ID, LANG_COMMAND_GRAVEYARD_ALLIANCE, LANG_COMMAND_GRAVEYARD_ANY, LANG_COMMAND_GRAVEYARD_HORDE, LANG_COMMAND_GRAVEYARD_NOTEAM, LANG_COMMAND_GRAVEYARDERROR, LANG_COMMAND_GRAVEYARDNEAREST, LANG_COMMAND_ZONENOGRAFACTION, LANG_COMMAND_ZONENOGRAVEYARDS, m_session, PSendSysMessage(), SetSentErrorMessage(), GraveYardData::team, and TEAM_BOTH_ALLOWED.
Referenced by getCommandTable().
HandleNotifyCommand()
bool ChatHandler::HandleNotifyCommand (char * args) protected
Definition at line 140 of file Level1.cpp.
References GetMangosString(), LANG_GLOBAL_NOTIFY, SMSG_NOTIFICATION, and sWorld.
Referenced by getCommandTable().
HandleNpcAddCommand()
bool ChatHandler::HandleNpcAddCommand (char * args) protected
Definition at line 1759 of file Level2.cpp.
References Creature::Create(), ExtractUint32KeyFromLink(), ObjectMgr::GetCreatureTemplate(), Object::GetGUIDLow(), Map::GetId(), WorldObject::GetMap(), WorldObject::GetOrientation(), Player::GetPhaseMaskForSpawn(), WorldSession::GetPlayer(), Map::GetSpawnMode(), LANG_COMMAND_INVALIDCREATUREID, LANG_NO_FREE_STATIC_GUID_FOR_SPAWN, Creature::LoadFromDB(), m_session, PSendSysMessage(), Creature::SaveToDB(), SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleNpcAddVendorItemCommand()
bool ChatHandler::HandleNpcAddVendorItemCommand (char * args) protected
Definition at line 1848 of file Level2.cpp.
References ExtractOptUInt32(), ExtractUint32KeyFromLink(), Object::GetEntry(), ObjectMgr::GetItemPrototype(), WorldSession::GetPlayer(), getSelectedCreature(), LANG_COMMAND_NEEDITEMSEND, LANG_ITEM_ADDED_TO_LIST, m_session, ItemPrototype::Name1, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleNpcAddWeaponCommand()
bool ChatHandler::HandleNpcAddWeaponCommand (char * args) protected
Definition at line 4232 of file Level3.cpp.
Referenced by getCommandTable().
HandleNpcAIInfoCommand()
bool ChatHandler::HandleNpcAIInfoCommand (char * args) protected
Definition at line 1924 of file Level2.cpp.
References Creature::AI(), UnitAI::GetAIInformation(), Creature::GetAIName(), Object::GetEntry(), Creature::GetScriptName(), getSelectedCreature(), LANG_NPC_AI_HEADER, LANG_NPC_AI_NAMES, LANG_SELECT_CREATURE, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcAllowMovementCommand()
bool ChatHandler::HandleNpcAllowMovementCommand (char * args) protected
Definition at line 4054 of file Level3.cpp.
References LANG_CREATURE_MOVE_DISABLED, LANG_CREATURE_MOVE_ENABLED, SendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleNpcChangeEntryCommand()
bool ChatHandler::HandleNpcChangeEntryCommand (char * args) protected
Definition at line 4069 of file Level3.cpp.
References getSelectedUnit(), Object::GetTypeId(), LANG_DONE, LANG_ERROR, LANG_SELECT_CREATURE, SendSysMessage(), SetSentErrorMessage(), TYPEID_UNIT, and Creature::UpdateEntry().
Referenced by getCommandTable().
HandleNpcChangeLevelCommand()
bool ChatHandler::HandleNpcChangeLevelCommand (char * args) protected
Definition at line 1954 of file Level2.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, getSelectedCreature(), Creature::HasStaticDBSpawnData(), Creature::IsPet(), LANG_BAD_VALUE, LANG_SELECT_CREATURE, Creature::SaveToDB(), SendSysMessage(), Unit::SetHealth(), Unit::SetLevel(), Unit::SetMaxHealth(), SetSentErrorMessage(), and sWorld.
Referenced by getCommandTable().
HandleNpcDeleteCommand()
bool ChatHandler::HandleNpcDeleteCommand (char * args) protected
Definition at line 2016 of file Level2.cpp.
References WorldObject::AddObjectToRemoveList(), Creature::AddToRemoveListInMaps(), Unit::CombatStop(), CREATURE_SUBTYPE_GENERIC, CREATURE_SUBTYPE_PET, CREATURE_SUBTYPE_TEMPORARY_SUMMON, CREATURE_SUBTYPE_TOTEM, Creature::DeleteFromDB(), ExtractUint32KeyFromLink(), Map::GetCreature(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldSession::GetPlayer(), getSelectedCreature(), Creature::GetSubtype(), LANG_COMMAND_DELCREATMESSAGE, LANG_SELECT_CREATURE, m_session, PET_SAVE_AS_CURRENT, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleNpcDelVendorItemCommand()
bool ChatHandler::HandleNpcDelVendorItemCommand (char * args) protected
Definition at line 1889 of file Level2.cpp.
References ExtractUint32KeyFromLink(), Object::GetEntry(), ObjectMgr::GetItemPrototype(), getSelectedCreature(), Unit::isVendor(), LANG_COMMAND_NEEDITEMSEND, LANG_COMMAND_VENDORSELECTION, LANG_ITEM_DELETED_FROM_LIST, LANG_ITEM_NOT_IN_LIST, ItemPrototype::Name1, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleNpcEvade()
bool ChatHandler::HandleNpcEvade (char * args) protected
Definition at line 1831 of file Level2.cpp.
References Creature::AI(), UnitAI::EnterEvadeMode(), getSelectedCreature(), LANG_SELECT_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcFactionIdCommand()
bool ChatHandler::HandleNpcFactionIdCommand (char * args) protected
Definition at line 2262 of file Level2.cpp.
References Creature::GetCreatureInfo(), Object::GetEntry(), getSelectedCreature(), LANG_SELECT_CREATURE, LANG_WRONG_FACTION, Database::PExecuteLog(), PSendSysMessage(), SendSysMessage(), Unit::setFaction(), SetSentErrorMessage(), sFactionTemplateStore, and WorldDatabase.
Referenced by getCommandTable().
HandleNpcFlagCommand()
bool ChatHandler::HandleNpcFlagCommand (char * args) protected
Definition at line 1991 of file Level2.cpp.
References Object::GetEntry(), getSelectedCreature(), LANG_SELECT_CREATURE, LANG_VALUE_SAVED_REJOIN, Database::PExecuteLog(), SendSysMessage(), SetSentErrorMessage(), Object::SetUInt32Value(), UNIT_NPC_FLAGS, and WorldDatabase.
Referenced by getCommandTable().
HandleNpcFollowCommand()
bool ChatHandler::HandleNpcFollowCommand (char * args) protected
Definition at line 2381 of file Level2.cpp.
References Unit::GetMotionMaster(), WorldObject::GetName(), WorldSession::GetPlayer(), getSelectedCreature(), LANG_CREATURE_FOLLOW_YOU_NOW, LANG_SELECT_CREATURE, m_session, MotionMaster::MoveFollow(), PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, PSendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcFormationInfoCommand()
bool ChatHandler::HandleNpcFormationInfoCommand (char * args) protected
Definition at line 2585 of file Level2.cpp.
References Unit::GetFormationSlot(), getSelectedCreature(), LANG_SELECT_CREATURE, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcFormationResetCommand()
bool ChatHandler::HandleNpcFormationResetCommand (char * args) protected
Definition at line 2608 of file Level2.cpp.
References Unit::GetFormationSlot(), getSelectedCreature(), LANG_SELECT_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcFormationSwitchCommand()
bool ChatHandler::HandleNpcFormationSwitchCommand (char * args) protected
Definition at line 2634 of file Level2.cpp.
References ExtractUInt32(), Unit::GetFormationSlot(), getSelectedCreature(), LANG_SELECT_CREATURE, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and SPAWN_GROUP_FORMATION_TYPE_COUNT.
Referenced by getCommandTable().
HandleNpcGroupInfoCommand()
bool ChatHandler::HandleNpcGroupInfoCommand (char * args) protected
Definition at line 2514 of file Level2.cpp.
References Creature::GetCreatureGroup(), Unit::GetFormationSlot(), Unit::GetMaster(), getSelectedCreature(), LANG_SELECT_CREATURE, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcInfoCommand()
bool ChatHandler::HandleNpcInfoCommand (char * args) protected
Definition at line 4093 of file Level3.cpp.
References Creature::AI(), CreatureInfo::DifficultyEntry, CreatureInfo::Entry, CreatureInfo::ExtraFlags, Object::GetByteValue(), Unit::GetCombatManager(), UnitAI::GetCombatScriptStatus(), CombatManager::GetCombatTimer(), Creature::GetCorpseDecayTimer(), Unit::GetCreateHealth(), Creature::GetCreatureGroup(), Creature::GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), Unit::GetDisplayId(), Object::GetEntry(), Unit::GetFaction(), Object::GetGUIDLow(), Object::GetGuidStr(), Unit::GetHealth(), WorldObject::GetInstanceId(), Unit::GetLevel(), Unit::GetMaxHealth(), Unit::GetNativeDisplayId(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Creature::GetRespawnDelay(), Creature::GetRespawnTimeEx(), getSelectedCreature(), Creature::GetSpellList(), Object::GetUInt32Value(), CombatManager::IsInEvadeMode(), CombatManager::IsLeashingDisabled(), LANG_COMMAND_RAWPAWNTIMES, LANG_NPCINFO_CHAR, LANG_NPCINFO_CHAR_DIFFICULTY, LANG_NPCINFO_DUNGEON_ID, LANG_NPCINFO_FLAGS, LANG_NPCINFO_HEALTH, LANG_NPCINFO_LEVEL, LANG_NPCINFO_LOOT, LANG_NPCINFO_PHASEMASK, LANG_NPCINFO_POSITION, LANG_NPCINFO_TRAINER, LANG_NPCINFO_VENDOR, LANG_SELECT_CREATURE, CreatureInfo::LootId, WorldObject::m_movementInfo, MAX_DIFFICULTY, MovementInfo::moveFlags, CreatureInfo::PickpocketLootId, PSendSysMessage(), secsToTimeString(), SendSysMessage(), SetSentErrorMessage(), CreatureInfo::SkinningLootId, sObjectMgr, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_1, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_NPC_FLAG_TRAINER, UNIT_NPC_FLAG_VENDOR, and UNIT_NPC_FLAGS.
Referenced by getCommandTable().
HandleNpcListSpells()
bool ChatHandler::HandleNpcListSpells (char * args) protected
Definition at line 23 of file NpcCommands.cpp.
References CreatureSpellListSpell::Availability, CreatureSpellListTargeting::Comment, CreatureSpellList::Disabled, CreatureSpellListSpell::Flags, getSelectedCreature(), Creature::GetSpellList(), CreatureSpellListTargeting::Id, CreatureSpellListSpell::InitialMax, CreatureSpellListSpell::InitialMin, CreatureSpellList::Name, CreatureSpellListSpell::Probability, PSendSysMessage(), CreatureSpellListSpell::RepeatMax, CreatureSpellListSpell::RepeatMin, CreatureSpellListSpell::SpellId, CreatureSpellList::Spells, and CreatureSpellListSpell::Target.
Referenced by getCommandTable().
HandleNpcMoveCommand()
bool ChatHandler::HandleNpcMoveCommand (char * args) protected
Definition at line 2076 of file Level2.cpp.
References Map::CreatureRelocation(), ExtractUint32KeyFromLink(), Map::GetCreature(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), CreatureData::GetObjectGuid(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), getSelectedCreature(), MotionMaster::Initialize(), Unit::IsAlive(), JUST_DIED, LANG_COMMAND_CREATGUIDNOTFOUND, LANG_COMMAND_CREATUREATSAMEMAP, LANG_COMMAND_CREATUREMOVED, m_session, CreatureData::mapid, Database::PExecuteLog(), PSendSysMessage(), Creature::Respawn(), Creature::SetDeathState(), SetSentErrorMessage(), sObjectMgr, and WorldDatabase.
Referenced by getCommandTable().
HandleNpcNameCommand()
bool ChatHandler::HandleNpcNameCommand (char * args) protected
Definition at line 2674 of file Level2.cpp.
Referenced by getCommandTable().
HandleNpcPlayEmoteCommand()
bool ChatHandler::HandleNpcPlayEmoteCommand (char * args) protected
Definition at line 4213 of file Level3.cpp.
References getSelectedCreature(), Unit::HandleEmote(), LANG_SELECT_CREATURE, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcSayCommand()
bool ChatHandler::HandleNpcSayCommand (char * args) protected
Definition at line 47 of file Level1.cpp.
References WorldSession::GetPlayer(), getSelectedCreature(), LANG_SELECT_CREATURE, LANG_UNIVERSAL, m_session, WorldObject::MonsterSay(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcSetModelCommand()
bool ChatHandler::HandleNpcSetModelCommand (char * args) protected
Definition at line 2237 of file Level2.cpp.
References getSelectedCreature(), Creature::HasStaticDBSpawnData(), Creature::IsPet(), LANG_SELECT_CREATURE, Creature::SaveToDB(), SendSysMessage(), Unit::SetDisplayId(), Unit::SetNativeDisplayId(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcSetMoveTypeCommand()
bool ChatHandler::HandleNpcSetMoveTypeCommand (char * args) protected
HandleNpcSetMoveTypeCommand Set the movement type for an NPC.
Valid movement types are:
stay - NPC wont move
random - NPC will move randomly according to the spawndist
way - NPC will move with given waypoints set
additional parameter: NODEL - so no waypoints are deleted, if you change the movement type
Definition at line 2148 of file Level2.cpp.
References ExtractLiteralArg(), ExtractUInt32(), Map::GetCreature(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), CreatureData::GetObjectGuid(), WorldSession::GetPlayer(), getSelectedCreature(), Creature::HasStaticDBSpawnData(), IDLE_MOTION_TYPE, MotionMaster::Initialize(), Unit::IsAlive(), JUST_DIED, LANG_COMMAND_CREATGUIDNOTFOUND, LANG_COMMAND_CREATUREATSAMEMAP, LANG_MOVE_TYPE_SET, LANG_MOVE_TYPE_SET_NODEL, LINEAR_WP_MOTION_TYPE, m_session, CreatureData::mapid, PSendSysMessage(), RANDOM_MOTION_TYPE, Creature::Respawn(), Creature::SaveToDB(), Creature::SetDeathState(), Creature::SetDefaultMovementType(), SetSentErrorMessage(), sObjectMgr, sWaypointMgr, and WAYPOINT_MOTION_TYPE.
Referenced by getCommandTable().
HandleNpcSetPhaseCommand()
bool ChatHandler::HandleNpcSetPhaseCommand (char * args) protected
Definition at line 2462 of file Level2.cpp.
References getSelectedCreature(), Creature::HasStaticDBSpawnData(), LANG_BAD_VALUE, LANG_SELECT_CREATURE, Creature::SaveToDB(), SendSysMessage(), Unit::SetPhaseMask(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcShowLootCommand()
bool ChatHandler::HandleNpcShowLootCommand (char * args) protected
Definition at line 2492 of file Level2.cpp.
References getSelectedCreature(), LANG_SELECT_CREATURE, Object::m_loot, m_session, Loot::PrintLootList(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcSpawnDistCommand()
bool ChatHandler::HandleNpcSpawnDistCommand (char * args) protected
Definition at line 2299 of file Level2.cpp.
References Object::GetGUIDLow(), Creature::GetRespawnRadius(), getSelectedCreature(), IDLE_MOTION_TYPE, Unit::IsAlive(), JUST_DIED, LANG_BAD_VALUE, LANG_COMMAND_SPAWNDIST, LANG_SELECT_CREATURE, CreatureData::movementType, Database::PExecuteLog(), PSendSysMessage(), RANDOM_MOTION_TYPE, Creature::Respawn(), SendSysMessage(), Creature::SetDeathState(), Creature::SetDefaultMovementType(), Creature::SetRespawnRadius(), SetSentErrorMessage(), sObjectMgr, CreatureData::spawndist, and WorldDatabase.
Referenced by getCommandTable().
HandleNpcSpawnTimeCommand()
bool ChatHandler::HandleNpcSpawnTimeCommand (char * args) protected
Definition at line 2358 of file Level2.cpp.
References ExtractUInt32(), Object::GetGUIDLow(), getSelectedCreature(), LANG_COMMAND_SPAWNTIME, LANG_SELECT_CREATURE, Database::PExecuteLog(), PSendSysMessage(), Creature::SetRespawnDelay(), SetSentErrorMessage(), and WorldDatabase.
Referenced by getCommandTable().
HandleNpcSubNameCommand()
bool ChatHandler::HandleNpcSubNameCommand (char * args) protected
Definition at line 2720 of file Level2.cpp.
Referenced by getCommandTable().
HandleNpcTameCommand()
bool ChatHandler::HandleNpcTameCommand (char * args) protected
Definition at line 2437 of file Level2.cpp.
References Unit::CastSpell(), Unit::GetPetGuid(), WorldSession::GetPlayer(), getSelectedCreature(), Creature::IsPet(), LANG_SELECT_CREATURE, LANG_YOU_ALREADY_HAVE_PET, m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and TRIGGERED_OLD_TRIGGERED.
Referenced by getCommandTable().
HandleNpcTempSpawn()
bool ChatHandler::HandleNpcTempSpawn (char * args) protected
Definition at line 1807 of file Level2.cpp.
References ExtractUInt32(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSession(), SendSysMessage(), SetSentErrorMessage(), WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_DESPAWN.
Referenced by getCommandTable().
HandleNpcTextEmoteCommand()
bool ChatHandler::HandleNpcTextEmoteCommand (char * args) protected
Definition at line 84 of file Level1.cpp.
References WorldSession::GetPlayer(), getSelectedCreature(), LANG_SELECT_CREATURE, m_session, WorldObject::MonsterTextEmote(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcThreatCommand()
bool ChatHandler::HandleNpcThreatCommand (char * args) protected
Definition at line 4185 of file Level3.cpp.
References Object::GetEntry(), Object::GetGUIDLow(), WorldObject::GetName(), getSelectedUnit(), ThreatManager::getThreat(), ThreatManager::getThreatList(), Unit::getThreatManager(), LANG_NPC_THREAT_PLAYER, LANG_NPC_THREAT_SELECTED_CREATURE, LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcUnFollowCommand()
bool ChatHandler::HandleNpcUnFollowCommand (char * args) protected
Definition at line 2400 of file Level2.cpp.
References FOLLOW_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), TargetedMovementGeneratorMedium< T, D >::GetCurrentTarget(), Unit::GetMotionMaster(), WorldObject::GetName(), WorldSession::GetPlayer(), getSelectedCreature(), LANG_CREATURE_NOT_FOLLOW_YOU, LANG_CREATURE_NOT_FOLLOW_YOU_NOW, LANG_SELECT_CREATURE, m_session, MotionMaster::MovementExpired(), PSendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleNpcWhisperCommand()
bool ChatHandler::HandleNpcWhisperCommand (char * args) protected
Definition at line 104 of file Level1.cpp.
References ExtractPlayerTarget(), Map::GetCreature(), WorldObject::GetMap(), WorldSession::GetPlayer(), Player::GetSelectionGuid(), HasLowerSecurity(), m_session, and WorldObject::MonsterWhisper().
Referenced by getCommandTable().
HandleNpcYellCommand()
bool ChatHandler::HandleNpcYellCommand (char * args) protected
Definition at line 65 of file Level1.cpp.
References WorldSession::GetPlayer(), getSelectedCreature(), LANG_SELECT_CREATURE, LANG_UNIVERSAL, m_session, WorldObject::MonsterYell(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandlePDumpLoadCommand()
bool ChatHandler::HandlePDumpLoadCommand (char * args) protected
Definition at line 6125 of file Level3.cpp.
References CHAR_NAME_SUCCESS, ObjectMgr::CheckPlayerName(), DUMP_FILE_BROKEN, DUMP_FILE_OPEN_ERROR, DUMP_SUCCESS, DUMP_TOO_MANY_CHARS, ExtractAccountId(), ExtractLiteralArg(), ExtractQuotedOrLiteralArg(), ExtractUInt32(), HIGHGUID_PLAYER, LANG_ACCOUNT_CHARACTER_LIST_FULL, LANG_CHARACTER_GUID_IN_USE, LANG_COMMAND_IMPORT_FAILED, LANG_COMMAND_IMPORT_SUCCESS, LANG_DUMP_BROKEN, LANG_FILE_OPEN_FAIL, LANG_INVALID_CHARACTER_GUID, LANG_INVALID_CHARACTER_NAME, PlayerDumpReader::LoadDump(), normalizePlayerName(), PSendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandlePDumpWriteCommand()
bool ChatHandler::HandlePDumpWriteCommand (char * args) protected
Definition at line 6208 of file Level3.cpp.
References DUMP_FILE_OPEN_ERROR, DUMP_SUCCESS, ExtractLiteralArg(), ExtractPlayerNameFromLink(), ExtractQuotedOrLiteralArg(), ExtractUInt32(), ObjectGuid::GetCounter(), HIGHGUID_PLAYER, LANG_COMMAND_EXPORT_FAILED, LANG_COMMAND_EXPORT_SUCCESS, LANG_FILE_OPEN_FAIL, LANG_PLAYER_NOT_FOUND, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandlePInfoCommand()
bool ChatHandler::HandlePInfoCommand (char * args) protected
Definition at line 2892 of file Level2.cpp.
References CharacterDatabase, ExtractPlayerTarget(), QueryResult::Fetch(), GetAccessLevel(), WorldSession::GetAccountId(), WorldSession::GetAnticheat(), ObjectGuid::GetCounter(), Field::GetCppString(), WorldSession::GetLatency(), Unit::GetLevel(), GetMangosString(), Player::GetMoney(), Player::GetSession(), Player::GetTotalPlayedTime(), Field::GetUInt32(), GOLD, HasLowerSecurity(), LANG_ERROR, LANG_OFFLINE, LANG_PINFO_ACCOUNT, LANG_PINFO_LEVEL, LoginDatabase, playerLink(), Database::PQuery(), PSendSysMessage(), SEC_PLAYER, secsToTimeString(), SessionAnticheatInterface::SendPlayerInfo(), and SILVER.
Referenced by getCommandTable().
HandlePoolInfoCommand()
bool ChatHandler::HandlePoolInfoCommand (char * args) protected
Definition at line 4655 of file Level2.cpp.
References PoolTemplateData::AutoSpawn, PoolTemplateData::description, ExtractUint32KeyFromLink(), ObjectMgr::GetCreatureTemplate(), PoolGroup< T >::GetEqualChanced(), PoolGroup< T >::GetExplicitlyChanced(), ObjectMgr::GetGameObjectInfo(), GetMangosString(), WorldObject::GetMap(), Map::GetPersistentState(), WorldSession::GetPlayer(), SpawnedPoolData::GetSpawnedCreatures(), SpawnedPoolData::GetSpawnedGameobjects(), MapPersistentState::GetSpawnedPoolData(), SpawnedPoolData::GetSpawnedPools(), LANG_ACTIVE, LANG_POOL_CHANCE_CREATURE_LIST_CHAT, LANG_POOL_CHANCE_CREATURE_LIST_CONSOLE, LANG_POOL_CHANCE_CREATURE_LIST_HEADER, LANG_POOL_CHANCE_GO_LIST_CHAT, LANG_POOL_CHANCE_GO_LIST_CONSOLE, LANG_POOL_CHANCE_GO_LIST_HEADER, LANG_POOL_CHANCE_POOL_LIST_CHAT, LANG_POOL_CHANCE_POOL_LIST_CONSOLE, LANG_POOL_CHANCE_POOL_LIST_HEADER, LANG_POOL_CREATURE_LIST_CHAT, LANG_POOL_CREATURE_LIST_CONSOLE, LANG_POOL_CREATURE_LIST_HEADER, LANG_POOL_ENTRY_LOWER_MAX_POOL, LANG_POOL_GO_LIST_CHAT, LANG_POOL_GO_LIST_CONSOLE, LANG_POOL_GO_LIST_HEADER, LANG_POOL_INFO_HEADER, LANG_POOL_INFO_HEADER_CHAT, LANG_POOL_INFO_HEADER_CONSOLE, LANG_POOL_POOL_LIST_CHAT, LANG_POOL_POOL_LIST_CONSOLE, LANG_POOL_POOL_LIST_HEADER, m_session, PoolTemplateData::MaxLimit, PSendSysMessage(), SendSysMessage(), sObjectMgr, and sPoolMgr.
Referenced by getCommandTable().
HandlePoolListCommand()
bool ChatHandler::HandlePoolListCommand (char * args) protected
Definition at line 4588 of file Level2.cpp.
References WorldObject::GetMap(), MapPersistentState::GetMapEntry(), MapPersistentState::GetMapId(), Map::GetPersistentState(), WorldSession::GetPlayer(), GetSessionDbcLocale(), MapEntry::Instanceable(), LANG_NO_POOL_FOR_MAP, LANG_POOL_LIST_NON_INSTANCE, m_session, MapEntry::name, PSendSysMessage(), SetSentErrorMessage(), ShowPoolListHelper(), and sPoolMgr.
Referenced by getCommandTable().
HandlePoolSpawnsCommand()
bool ChatHandler::HandlePoolSpawnsCommand (char * args) protected
Definition at line 4619 of file Level2.cpp.
References ExtractUint32KeyFromLink(), ObjectMgr::GetCreatureTemplate(), ObjectMgr::GetGameObjectInfo(), WorldObject::GetMap(), MapPersistentState::GetMapEntry(), MapPersistentState::GetMapId(), Map::GetPersistentState(), WorldSession::GetPlayer(), GetSessionDbcLocale(), SpawnedPoolData::GetSpawnedCreatures(), SpawnedPoolData::GetSpawnedGameobjects(), MapPersistentState::GetSpawnedPoolData(), MapEntry::Instanceable(), LANG_CREATURE_LIST_CHAT, LANG_GO_LIST_CHAT, LANG_POOL_SPAWNS_NON_INSTANCE, m_session, MapEntry::name, PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, and sPoolMgr.
Referenced by getCommandTable().
HandlePrintMovement()
bool ChatHandler::HandlePrintMovement (char * args) protected
Definition at line 6391 of file Level3.cpp.
References CHASE_MOTION_TYPE, Unit::GetMotionMaster(), ChaseMovementGenerator::GetPrintout(), getSelectedCreature(), LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sLog.
Referenced by getCommandTable().
HandleQuestAddCommand()
bool ChatHandler::HandleQuestAddCommand (char * args) protected
Definition at line 5362 of file Level3.cpp.
References Player::AddQuest(), Player::CanAddQuest(), Player::CanCompleteQuest(), Player::CompleteQuest(), ExtractUint32KeyFromLink(), SQLStorageBase::GetMaxEntry(), Quest::GetQuestId(), getSelectedPlayer(), Player::IsCurrentQuest(), ItemPrototype::ItemId, LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_STARTFROMITEM, LANG_NO_CHAR_SELECTED, SQLStorage::LookupEntry(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), sItemStorage, sObjectMgr, and ItemPrototype::StartQuest.
Referenced by getCommandTable().
HandleQuestCompleteCommand()
bool ChatHandler::HandleQuestCompleteCommand (char * args) protected
Definition at line 5461 of file Level3.cpp.
References Player::CanStoreNewItem(), Player::CastedCreatureOrGO(), Player::CompleteQuest(), EQUIP_ERR_OK, ExtractUint32KeyFromLink(), ObjectMgr::GetCreatureTemplate(), Player::GetItemCount(), Quest::GetPlayersSlain(), Player::GetQuestStatus(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveValue(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), Quest::GetRewOrReqMoney(), getSelectedPlayer(), Quest::HasSpecialFlag(), HIGHGUID_GAMEOBJECT, HIGHGUID_UNIT, Player::KilledMonster(), Player::KilledPlayerCreditForQuest(), LANG_COMMAND_QUEST_NOTFOUND, LANG_NO_CHAR_SELECTED, Player::ModifyMoney(), NULL_BAG, NULL_SLOT, PSendSysMessage(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_SPECIAL_FLAGS_PLAYER_KILL, QUEST_STATUS_NONE, Quest::ReqCreatureOrGOCount, Quest::ReqCreatureOrGOId, Quest::ReqItemCount, Quest::ReqItemId, Quest::ReqSpell, Player::SendNewItem(), SendSysMessage(), ReputationMgr::SetReputation(), SetSentErrorMessage(), sFactionStore, sObjectMgr, and Player::StoreNewItem().
Referenced by getCommandTable().
HandleQuestRemoveCommand()
bool ChatHandler::HandleQuestRemoveCommand (char * args) protected
Definition at line 5413 of file Level3.cpp.
References ExtractUint32KeyFromLink(), Player::GetQuestSlotQuestId(), Player::getQuestStatusMap(), getSelectedPlayer(), LANG_COMMAND_QUEST_NOTFOUND, LANG_COMMAND_QUEST_REMOVED, LANG_NO_CHAR_SELECTED, MAX_QUEST_LOG_SIZE, PSendSysMessage(), QUEST_STATUS_NONE, SendSysMessage(), Player::SetQuestSlot(), Player::SetQuestStatus(), SetSentErrorMessage(), sObjectMgr, and Player::TakeQuestSourceItem().
Referenced by PlayerbotChatHandler::dropQuest(), and getCommandTable().
HandlerDebugModValueHelper()
bool ChatHandler::HandlerDebugModValueHelper (Object * target, uint32 field, char * typeStr, char * valStr) protected
Definition at line 1021 of file debugcmds.cpp.
References DEBUG_LOG, ExtractFloat(), ExtractUInt32Base(), Object::GetFloatValue(), GetMangosString(), Object::GetObjectGuid(), ObjectGuid::GetString(), Object::GetUInt32Value(), Object::GetValuesCount(), LANG_CHANGE_FLOAT, LANG_CHANGE_FLOAT_FIELD, LANG_CHANGE_HEX, LANG_CHANGE_HEX_FIELD, LANG_CHANGE_INT32, LANG_CHANGE_INT32_FIELD, LANG_TOO_BIG_INDEX, OBJECT_FIELD_ENTRY, PSendSysMessage(), Object::SetFloatValue(), and Object::SetUInt32Value().
Referenced by HandleDebugModItemValueCommand(), and HandleDebugModValueCommand().
HandleRecallCommand()
bool ChatHandler::HandleRecallCommand (char * args) protected
Definition at line 656 of file Level1.cpp.
References ExtractPlayerTarget(), GetNameLink(), HandleGoHelper(), HasLowerSecurity(), Player::IsBeingTeleported(), LANG_IS_TELEPORTED, Player::m_recallMap, Player::m_recallO, Player::m_recallX, Player::m_recallY, Player::m_recallZ, PSendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleReloadAchievementCriteriaRequirementCommand()
bool ChatHandler::HandleReloadAchievementCriteriaRequirementCommand (char * args) protected
Definition at line 343 of file Level3.cpp.
References sAchievementMgr, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllAchievementCommand().
HandleReloadAchievementRewardCommand()
bool ChatHandler::HandleReloadAchievementRewardCommand (char * args) protected
Definition at line 351 of file Level3.cpp.
References sAchievementMgr, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllAchievementCommand().
HandleReloadAllAchievementCommand()
bool ChatHandler::HandleReloadAllAchievementCommand (char * args) protected
Definition at line 208 of file Level3.cpp.
References HandleReloadAchievementCriteriaRequirementCommand(), and HandleReloadAchievementRewardCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllAreaCommand()
bool ChatHandler::HandleReloadAllAreaCommand (char * args) protected
Definition at line 215 of file Level3.cpp.
References HandleReloadAreaTriggerTavernCommand(), HandleReloadAreaTriggerTeleportCommand(), HandleReloadGameGraveyardZoneCommand(), and HandleReloadTaxiShortcuts().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllCommand()
bool ChatHandler::HandleReloadAllCommand (char * args) protected
Definition at line 185 of file Level3.cpp.
References HandleReloadAllAchievementCommand(), HandleReloadAllAreaCommand(), HandleReloadAllEventAICommand(), HandleReloadAllGossipsCommand(), HandleReloadAllItemCommand(), HandleReloadAllLocalesCommand(), HandleReloadAllLootCommand(), HandleReloadAllNpcCommand(), HandleReloadAllQuestCommand(), HandleReloadAllSpellCommand(), HandleReloadCommandCommand(), HandleReloadGameTeleCommand(), HandleReloadMailLevelRewardCommand(), HandleReloadMangosStringCommand(), HandleReloadReservedNameCommand(), and HandleReloadSkillFishingBaseLevelCommand().
Referenced by getCommandTable().
HandleReloadAllEventAICommand()
bool ChatHandler::HandleReloadAllEventAICommand (char * args) protected
Definition at line 272 of file Level3.cpp.
References HandleReloadEventAIScriptsCommand(), and HandleReloadEventAISummonsCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllGossipsCommand()
bool ChatHandler::HandleReloadAllGossipsCommand (char * args) protected
Definition at line 297 of file Level3.cpp.
References HandleReloadDBScriptsOnGossipCommand(), HandleReloadGossipMenuCommand(), HandleReloadNpcGossipCommand(), and HandleReloadPointsOfInterestCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllItemCommand()
bool ChatHandler::HandleReloadAllItemCommand (char * args) protected
Definition at line 307 of file Level3.cpp.
References HandleReloadItemConvertCommand(), HandleReloadItemEnchantementsCommand(), HandleReloadItemRequiredTragetCommand(), and HandleReloadPageTextsCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllLocalesCommand()
bool ChatHandler::HandleReloadAllLocalesCommand (char * args) protected
Definition at line 316 of file Level3.cpp.
References HandleReloadLocalesAchievementRewardCommand(), HandleReloadLocalesCreatureCommand(), HandleReloadLocalesGameobjectCommand(), HandleReloadLocalesGossipMenuOptionCommand(), HandleReloadLocalesItemCommand(), HandleReloadLocalesNpcTextCommand(), HandleReloadLocalesPageTextCommand(), HandleReloadLocalesPointsOfInterestCommand(), and HandleReloadLocalesQuestCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllLootCommand()
bool ChatHandler::HandleReloadAllLootCommand (char * args) protected
Definition at line 225 of file Level3.cpp.
References LoadLootTables(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllNpcCommand()
bool ChatHandler::HandleReloadAllNpcCommand (char * args) protected
Definition at line 234 of file Level3.cpp.
References HandleReloadNpcGossipCommand(), HandleReloadNpcTrainerCommand(), HandleReloadNpcVendorCommand(), HandleReloadPointsOfInterestCommand(), and HandleReloadSpellClickSpellsCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllQuestCommand()
bool ChatHandler::HandleReloadAllQuestCommand (char * args) protected
Definition at line 245 of file Level3.cpp.
References HandleReloadQuestAreaTriggersCommand(), HandleReloadQuestPOICommand(), HandleReloadQuestTemplateCommand(), SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAllScriptsCommand()
bool ChatHandler::HandleReloadAllScriptsCommand (char * args) protected
Definition at line 257 of file Level3.cpp.
References HandleReloadDBScriptsOnCreatureDeathCommand(), HandleReloadDBScriptsOnEventCommand(), HandleReloadDBScriptsOnGossipCommand(), HandleReloadDBScriptsOnGoUseCommand(), HandleReloadDBScriptsOnQuestEndCommand(), HandleReloadDBScriptsOnQuestStartCommand(), HandleReloadDBScriptsOnRelayCommand(), HandleReloadDBScriptsOnSpellCommand(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadAllSpellCommand()
bool ChatHandler::HandleReloadAllSpellCommand (char * args) protected
Definition at line 279 of file Level3.cpp.
References HandleReloadSkillDiscoveryTemplateCommand(), HandleReloadSkillExtraItemTemplateCommand(), HandleReloadSpellAreaCommand(), HandleReloadSpellBonusesCommand(), HandleReloadSpellChainCommand(), HandleReloadSpellElixirCommand(), HandleReloadSpellLearnSpellCommand(), HandleReloadSpellPetAurasCommand(), HandleReloadSpellProcEventCommand(), HandleReloadSpellProcItemEnchantCommand(), HandleReloadSpellScriptTargetCommand(), HandleReloadSpellTargetPositionCommand(), and HandleReloadSpellThreatsCommand().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadAnticheatCommand()
bool ChatHandler::HandleReloadAnticheatCommand (char *) protected
Definition at line 2459 of file Level1.cpp.
References sAnticheatLib, and SendSysMessage().
HandleReloadAreaTriggerTavernCommand()
bool ChatHandler::HandleReloadAreaTriggerTavernCommand (char * args) protected
Definition at line 359 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllAreaCommand().
HandleReloadAreaTriggerTeleportCommand()
bool ChatHandler::HandleReloadAreaTriggerTeleportCommand (char * args) protected
Definition at line 367 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllAreaCommand().
HandleReloadBattleEventCommand()
bool ChatHandler::HandleReloadBattleEventCommand (char * args) protected
Definition at line 846 of file Level3.cpp.
References sBattleGroundMgr, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadCommandCommand()
bool ChatHandler::HandleReloadCommandCommand (char * args) protected
Definition at line 375 of file Level3.cpp.
References load_command_table, and SendGlobalSysMessage().
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadConditionsCommand()
bool ChatHandler::HandleReloadConditionsCommand (char * args) protected
Definition at line 398 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadConfigCommand()
bool ChatHandler::HandleReloadConfigCommand (char * args) protected
Definition at line 330 of file Level3.cpp.
References PacketLog::instance(), metric::metric::instance(), PacketLog::Reinitialize(), metric::metric::reload_config(), SendGlobalSysMessage(), sLog, sMapMgr, and sWorld.
Referenced by getCommandTable().
HandleReloadCreatureCooldownsCommand()
bool ChatHandler::HandleReloadCreatureCooldownsCommand (char * args) protected
Definition at line 1103 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadCreatureQuestInvRelationsCommand()
bool ChatHandler::HandleReloadCreatureQuestInvRelationsCommand (char * args) protected
Definition at line 390 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadCreatureQuestRelationsCommand()
bool ChatHandler::HandleReloadCreatureQuestRelationsCommand (char * args) protected
Definition at line 382 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadCreatureSpellLists()
bool ChatHandler::HandleReloadCreatureSpellLists (char * args) protected
Definition at line 1111 of file Level3.cpp.
References Map::GetMapDataContainer(), Map::GetMessager(), SendGlobalSysMessage(), sLog, sMapMgr, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadCreaturesStatsCommand()
bool ChatHandler::HandleReloadCreaturesStatsCommand (char * args) protected
Definition at line 1087 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadDBScriptsOnCreatureDeathCommand()
bool ChatHandler::HandleReloadDBScriptsOnCreatureDeathCommand (char * args) protected
Definition at line 959 of file Level3.cpp.
References SCRIPT_TYPE_CREATURE_DEATH, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnEventCommand()
bool ChatHandler::HandleReloadDBScriptsOnEventCommand (char * args) protected
Definition at line 932 of file Level3.cpp.
References SCRIPT_TYPE_EVENT, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnGossipCommand()
bool ChatHandler::HandleReloadDBScriptsOnGossipCommand (char * args) protected
Definition at line 880 of file Level3.cpp.
References SCRIPT_TYPE_GOSSIP, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), HandleReloadAllGossipsCommand(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnGoUseCommand()
bool ChatHandler::HandleReloadDBScriptsOnGoUseCommand (char * args) protected
Definition at line 945 of file Level3.cpp.
References SCRIPT_TYPE_GAMEOBJECT, SCRIPT_TYPE_GAMEOBJECT_TEMPLATE, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnQuestEndCommand()
bool ChatHandler::HandleReloadDBScriptsOnQuestEndCommand (char * args) protected
Definition at line 919 of file Level3.cpp.
References SCRIPT_TYPE_QUEST_END, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnQuestStartCommand()
bool ChatHandler::HandleReloadDBScriptsOnQuestStartCommand (char * args) protected
Definition at line 906 of file Level3.cpp.
References SCRIPT_TYPE_QUEST_START, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnRelayCommand()
bool ChatHandler::HandleReloadDBScriptsOnRelayCommand (char * args) protected
Definition at line 972 of file Level3.cpp.
References SCRIPT_TYPE_RELAY, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadDBScriptsOnSpellCommand()
bool ChatHandler::HandleReloadDBScriptsOnSpellCommand (char * args) protected
Definition at line 893 of file Level3.cpp.
References SCRIPT_TYPE_SPELL, SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable(), and HandleReloadAllScriptsCommand().
HandleReloadEventAIScriptsCommand()
bool ChatHandler::HandleReloadEventAIScriptsCommand (char * args) protected
Definition at line 862 of file Level3.cpp.
References Map::GetMapDataContainer(), Map::GetMessager(), SendGlobalSysMessage(), sEventAIMgr, sLog, and sMapMgr.
Referenced by getCommandTable(), and HandleReloadAllEventAICommand().
HandleReloadEventAISummonsCommand()
bool ChatHandler::HandleReloadEventAISummonsCommand (char * args) protected
Definition at line 854 of file Level3.cpp.
References SendGlobalSysMessage(), sEventAIMgr, and sLog.
Referenced by getCommandTable(), and HandleReloadAllEventAICommand().
HandleReloadExpectedSpamRecords()
bool ChatHandler::HandleReloadExpectedSpamRecords (char * args) protected
Definition at line 1095 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sWorld.
Referenced by getCommandTable().
HandleReloadGameGraveyardZoneCommand()
bool ChatHandler::HandleReloadGameGraveyardZoneCommand (char * args) protected
Definition at line 985 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sWorld.
Referenced by getCommandTable(), and HandleReloadAllAreaCommand().
HandleReloadGameTeleCommand()
bool ChatHandler::HandleReloadGameTeleCommand (char * args) protected
Definition at line 996 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadGOQuestInvRelationsCommand()
bool ChatHandler::HandleReloadGOQuestInvRelationsCommand (char * args) protected
Definition at line 451 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadGOQuestRelationsCommand()
bool ChatHandler::HandleReloadGOQuestRelationsCommand (char * args) protected
Definition at line 443 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadGossipMenuCommand()
bool ChatHandler::HandleReloadGossipMenuCommand (char * args) protected
Definition at line 406 of file Level3.cpp.
References SendGlobalSysMessage(), and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllGossipsCommand().
HandleReloadItemConvertCommand()
bool ChatHandler::HandleReloadItemConvertCommand (char * args) protected
Definition at line 830 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllItemCommand().
HandleReloadItemEnchantementsCommand()
bool ChatHandler::HandleReloadItemEnchantementsCommand (char * args) protected
Definition at line 822 of file Level3.cpp.
References LoadRandomEnchantmentsTable(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllItemCommand().
HandleReloadItemRequiredTragetCommand()
bool ChatHandler::HandleReloadItemRequiredTragetCommand (char * args) protected
Definition at line 838 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllItemCommand().
HandleReloadLocalesAchievementRewardCommand()
bool ChatHandler::HandleReloadLocalesAchievementRewardCommand (char * args) protected
Definition at line 1007 of file Level3.cpp.
References sAchievementMgr, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesCreatureCommand()
bool ChatHandler::HandleReloadLocalesCreatureCommand (char * args) protected
Definition at line 1015 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesGameobjectCommand()
bool ChatHandler::HandleReloadLocalesGameobjectCommand (char * args) protected
Definition at line 1023 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesGossipMenuOptionCommand()
bool ChatHandler::HandleReloadLocalesGossipMenuOptionCommand (char * args) protected
Definition at line 1031 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesItemCommand()
bool ChatHandler::HandleReloadLocalesItemCommand (char * args) protected
Definition at line 1039 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesNpcTextCommand()
bool ChatHandler::HandleReloadLocalesNpcTextCommand (char * args) protected
Definition at line 1047 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesPageTextCommand()
bool ChatHandler::HandleReloadLocalesPageTextCommand (char * args) protected
Definition at line 1055 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesPointsOfInterestCommand()
bool ChatHandler::HandleReloadLocalesPointsOfInterestCommand (char * args) protected
Definition at line 1063 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesQuestCommand()
bool ChatHandler::HandleReloadLocalesQuestCommand (char * args) protected
Definition at line 1071 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllLocalesCommand().
HandleReloadLocalesTrainerGreetingCommand()
bool ChatHandler::HandleReloadLocalesTrainerGreetingCommand (char * args) protected
Definition at line 435 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadLootTemplatesCreatureCommand()
bool ChatHandler::HandleReloadLootTemplatesCreatureCommand (char * args) protected
Definition at line 480 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Creature(), LootTemplates_Creature, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesDisenchantCommand()
bool ChatHandler::HandleReloadLootTemplatesDisenchantCommand (char * args) protected
Definition at line 489 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Disenchant(), LootTemplates_Disenchant, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesFishingCommand()
bool ChatHandler::HandleReloadLootTemplatesFishingCommand (char * args) protected
Definition at line 498 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Fishing(), LootTemplates_Fishing, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesGameobjectCommand()
bool ChatHandler::HandleReloadLootTemplatesGameobjectCommand (char * args) protected
Definition at line 507 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Gameobject(), LootTemplates_Gameobject, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesItemCommand()
bool ChatHandler::HandleReloadLootTemplatesItemCommand (char * args) protected
Definition at line 516 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Item(), LootTemplates_Item, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesMailCommand()
bool ChatHandler::HandleReloadLootTemplatesMailCommand (char * args) protected
Definition at line 552 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Mail(), LootTemplates_Mail, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesMillingCommand()
bool ChatHandler::HandleReloadLootTemplatesMillingCommand (char * args) protected
Definition at line 525 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Milling(), LootTemplates_Milling, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesPickpocketingCommand()
bool ChatHandler::HandleReloadLootTemplatesPickpocketingCommand (char * args) protected
Definition at line 534 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Pickpocketing(), LootTemplates_Pickpocketing, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesProspectingCommand()
bool ChatHandler::HandleReloadLootTemplatesProspectingCommand (char * args) protected
Definition at line 543 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Prospecting(), LootTemplates_Prospecting, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesReferenceCommand()
bool ChatHandler::HandleReloadLootTemplatesReferenceCommand (char * args) protected
Definition at line 561 of file Level3.cpp.
References CheckLootTemplates_Reference(), LoadLootTemplates_Reference(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesSkinningCommand()
bool ChatHandler::HandleReloadLootTemplatesSkinningCommand (char * args) protected
Definition at line 571 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Skinning(), LootTemplates_Skinning, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadLootTemplatesSpellCommand()
bool ChatHandler::HandleReloadLootTemplatesSpellCommand (char * args) protected
Definition at line 580 of file Level3.cpp.
References LootStore::CheckLootRefs(), LoadLootTemplates_Spell(), LootTemplates_Spell, SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable().
HandleReloadMailLevelRewardCommand()
bool ChatHandler::HandleReloadMailLevelRewardCommand (char * args) protected
Definition at line 1079 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadMangosStringCommand()
bool ChatHandler::HandleReloadMangosStringCommand (char * args) protected
Definition at line 589 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadNpcGossipCommand()
bool ChatHandler::HandleReloadNpcGossipCommand (char * args) protected
Definition at line 597 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), HandleReloadAllGossipsCommand(), and HandleReloadAllNpcCommand().
HandleReloadNpcTextCommand()
bool ChatHandler::HandleReloadNpcTextCommand (char * args) protected
Definition at line 605 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadNpcTrainerCommand()
bool ChatHandler::HandleReloadNpcTrainerCommand (char * args) protected
Definition at line 613 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllNpcCommand().
HandleReloadNpcVendorCommand()
bool ChatHandler::HandleReloadNpcVendorCommand (char * args) protected
Definition at line 625 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllNpcCommand().
HandleReloadPageTextsCommand()
bool ChatHandler::HandleReloadPageTextsCommand (char * args) protected
Definition at line 814 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllItemCommand().
HandleReloadPointsOfInterestCommand()
bool ChatHandler::HandleReloadPointsOfInterestCommand (char * args) protected
Definition at line 638 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), HandleReloadAllGossipsCommand(), and HandleReloadAllNpcCommand().
HandleReloadQuestAreaTriggersCommand()
bool ChatHandler::HandleReloadQuestAreaTriggersCommand (char * args) protected
Definition at line 459 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllQuestCommand().
HandleReloadQuestgiverGreetingCommand()
bool ChatHandler::HandleReloadQuestgiverGreetingCommand (char * args) protected
Definition at line 413 of file Level3.cpp.
References SendGlobalSysMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleReloadQuestgiverGreetingLocalesCommand()
bool ChatHandler::HandleReloadQuestgiverGreetingLocalesCommand (char * args) protected
Definition at line 420 of file Level3.cpp.
References SendGlobalSysMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleReloadQuestPOICommand()
bool ChatHandler::HandleReloadQuestPOICommand (char * args) protected
Definition at line 646 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllQuestCommand().
HandleReloadQuestTemplateCommand()
bool ChatHandler::HandleReloadQuestTemplateCommand (char * args) protected
dependent also from gameobject but this table not reloaded anyway
Definition at line 467 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllQuestCommand().
HandleReloadReputationRewardRateCommand()
bool ChatHandler::HandleReloadReputationRewardRateCommand (char * args) protected
Definition at line 670 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadReputationSpilloverTemplateCommand()
bool ChatHandler::HandleReloadReputationSpilloverTemplateCommand (char * args) protected
Definition at line 678 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadReservedNameCommand()
bool ChatHandler::HandleReloadReservedNameCommand (char * args) protected
Definition at line 662 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadSkillDiscoveryTemplateCommand()
bool ChatHandler::HandleReloadSkillDiscoveryTemplateCommand (char * args) protected
Definition at line 686 of file Level3.cpp.
References LoadSkillDiscoveryTable(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSkillExtraItemTemplateCommand()
bool ChatHandler::HandleReloadSkillExtraItemTemplateCommand (char * args) protected
Definition at line 694 of file Level3.cpp.
References LoadSkillExtraItemTable(), SendGlobalSysMessage(), and sLog.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSkillFishingBaseLevelCommand()
bool ChatHandler::HandleReloadSkillFishingBaseLevelCommand (char * args) protected
Definition at line 702 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllCommand().
HandleReloadSpawnGroupsCommand()
bool ChatHandler::HandleReloadSpawnGroupsCommand (char * args) protected
Definition at line 1132 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleReloadSpellAreaCommand()
bool ChatHandler::HandleReloadSpellAreaCommand (char * args) protected
Definition at line 710 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellBonusesCommand()
bool ChatHandler::HandleReloadSpellBonusesCommand (char * args) protected
Definition at line 718 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellChainCommand()
bool ChatHandler::HandleReloadSpellChainCommand (char * args) protected
Definition at line 726 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellClickSpellsCommand()
bool ChatHandler::HandleReloadSpellClickSpellsCommand (char * args) protected
Definition at line 654 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllNpcCommand().
HandleReloadSpellElixirCommand()
bool ChatHandler::HandleReloadSpellElixirCommand (char * args) protected
Definition at line 734 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellLearnSpellCommand()
bool ChatHandler::HandleReloadSpellLearnSpellCommand (char * args) protected
Definition at line 742 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellPetAurasCommand()
bool ChatHandler::HandleReloadSpellPetAurasCommand (char * args) protected
Definition at line 806 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellProcEventCommand()
bool ChatHandler::HandleReloadSpellProcEventCommand (char * args) protected
Definition at line 750 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellProcItemEnchantCommand()
bool ChatHandler::HandleReloadSpellProcItemEnchantCommand (char * args) protected
Definition at line 758 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellScriptTargetCommand()
bool ChatHandler::HandleReloadSpellScriptTargetCommand (char * args) protected
Definition at line 766 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellTargetPositionCommand()
bool ChatHandler::HandleReloadSpellTargetPositionCommand (char * args) protected
Definition at line 774 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadSpellThreatsCommand()
bool ChatHandler::HandleReloadSpellThreatsCommand (char * args) protected
Definition at line 782 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sSpellMgr.
Referenced by getCommandTable(), and HandleReloadAllSpellCommand().
HandleReloadStringIds()
bool ChatHandler::HandleReloadStringIds (char * args) protected
Definition at line 790 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sScriptMgr.
Referenced by getCommandTable().
HandleReloadTaxiShortcuts()
bool ChatHandler::HandleReloadTaxiShortcuts (char * args) protected
Definition at line 798 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable(), and HandleReloadAllAreaCommand().
HandleReloadTrainerGreetingCommand()
bool ChatHandler::HandleReloadTrainerGreetingCommand (char * args) protected
Definition at line 427 of file Level3.cpp.
References SendGlobalSysMessage(), sLog, and sObjectMgr.
Referenced by getCommandTable().
HandleRepairitemsCommand()
bool ChatHandler::HandleRepairitemsCommand (char * args) protected
Definition at line 4838 of file Level2.cpp.
References ChatHandler(), Player::DurabilityRepairAll(), ExtractPlayerTarget(), GetNameLink(), HasLowerSecurity(), LANG_YOU_REPAIR_ITEMS, LANG_YOUR_ITEMS_REPAIRED, needReportToTarget(), and PSendSysMessage().
Referenced by getCommandTable().
HandleResetAchievementsCommand()
bool ChatHandler::HandleResetAchievementsCommand (char * args) protected
Definition at line 4977 of file Level3.cpp.
References AchievementMgr::DeleteFromDB(), ExtractPlayerTarget(), Player::GetAchievementMgr(), and AchievementMgr::Reset().
Referenced by getCommandTable().
HandleResetAllCommand()
bool ChatHandler::HandleResetAllCommand (char * args) protected
Definition at line 5237 of file Level3.cpp.
References AT_LOGIN_RESET_PET_TALENTS, AT_LOGIN_RESET_SPELLS, AT_LOGIN_RESET_TALENTS, CharacterDatabase, LANG_RESETALL_SPELLS, LANG_RESETALL_TALENTS, LANG_RESETALL_UNKNOWN_CASE, m_session, Database::PExecute(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), sObjectAccessor, and sWorld.
Referenced by getCommandTable().
HandleResetHonorCommand()
bool ChatHandler::HandleResetHonorCommand (char * args) protected
Definition at line 4992 of file Level3.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ExtractPlayerTarget(), PLAYER_FIELD_KILLS, PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, PLAYER_FIELD_TODAY_CONTRIBUTION, PLAYER_FIELD_YESTERDAY_CONTRIBUTION, Player::SetHonorPoints(), Object::SetUInt32Value(), and Player::UpdateAchievementCriteria().
Referenced by getCommandTable().
HandleResetLevelCommand()
bool ChatHandler::HandleResetLevelCommand (char * args) protected
Definition at line 5045 of file Level3.cpp.
References Player::_ApplyAllLevelScaleItemMods(), CLASS_DEATH_KNIGHT, CONFIG_UINT32_START_HEROIC_PLAYER_LEVEL, CONFIG_UINT32_START_PLAYER_LEVEL, ExtractPlayerTarget(), Unit::getClass(), Unit::GetPet(), HandleResetStatsOrLevelHelper(), Player::InitGlyphsForLevel(), Player::InitRunes(), Player::InitStatsForLevel(), Player::InitTalentForLevel(), Player::InitTaxiNodesForLevel(), PLAYER_XP, Unit::SetLevel(), Object::SetUInt32Value(), and sWorld.
Referenced by getCommandTable().
HandleResetModsCommand()
bool ChatHandler::HandleResetModsCommand (char * args) protected
Definition at line 7932 of file Level3.cpp.
References WorldObject::GetName(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, PSendSysMessage(), Unit::RemoveAurasDueToSpell(), SetSentErrorMessage(), SPELL_MOD_AGILITY, SPELL_MOD_ARMOR, SPELL_MOD_BLOCK_CHANCE, SPELL_MOD_DODGE_CHANCE, SPELL_MOD_INTELLECT, SPELL_MOD_MELEE_AP, SPELL_MOD_MELEE_CRIT, SPELL_MOD_MELEE_HASTE, SPELL_MOD_PARRY_CHANCE, SPELL_MOD_RANGE_AP, SPELL_MOD_RANGE_HASTE, SPELL_MOD_RES_ARCANE, SPELL_MOD_RES_FIRE, SPELL_MOD_RES_FROST, SPELL_MOD_RES_HOLY, SPELL_MOD_RES_NATURE, SPELL_MOD_RES_SHADOW, SPELL_MOD_SPELL_CRIT, SPELL_MOD_SPELL_HASTE, SPELL_MOD_SPELL_POWER, SPELL_MOD_SPIRIT, SPELL_MOD_STAMINA, and SPELL_MOD_STRENGTH.
Referenced by getCommandTable().
HandleResetSpecsCommand()
bool ChatHandler::HandleResetSpecsCommand (char * args) protected
Definition at line 5121 of file Level3.cpp.
References AT_LOGIN_RESET_PET_TALENTS, AT_LOGIN_RESET_TALENTS, CharacterDatabase, ChatHandler(), ExtractPlayerTarget(), ObjectGuid::GetCounter(), GetNameLink(), Unit::GetPet(), WorldSession::GetPlayer(), LANG_NO_CHAR_SELECTED, LANG_RESET_TALENTS, LANG_RESET_TALENTS_OFFLINE, LANG_RESET_TALENTS_ONLINE, m_session, Database::PExecute(), playerLink(), PSendSysMessage(), Player::resetTalents(), Pet::resetTalentsForAllPetsOf(), SendSysMessage(), Player::SendTalentsInfoData(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleResetSpellsCommand()
bool ChatHandler::HandleResetSpellsCommand (char * args) protected
Definition at line 5096 of file Level3.cpp.
References AT_LOGIN_RESET_SPELLS, CharacterDatabase, ChatHandler(), ExtractPlayerTarget(), ObjectGuid::GetCounter(), GetNameLink(), WorldSession::GetPlayer(), LANG_RESET_SPELLS, LANG_RESET_SPELLS_OFFLINE, LANG_RESET_SPELLS_ONLINE, m_session, Database::PExecute(), PSendSysMessage(), and Player::resetSpells().
Referenced by getCommandTable().
HandleResetStatsCommand()
bool ChatHandler::HandleResetStatsCommand (char * args) protected
Definition at line 5078 of file Level3.cpp.
References ExtractPlayerTarget(), HandleResetStatsOrLevelHelper(), Player::InitGlyphsForLevel(), Player::InitRunes(), Player::InitStatsForLevel(), Player::InitTalentForLevel(), and Player::InitTaxiNodesForLevel().
Referenced by getCommandTable().
HandleResetTalentsCommand()
bool ChatHandler::HandleResetTalentsCommand (char * args) protected
Definition at line 5158 of file Level3.cpp.
References ChatHandler(), ExtractPlayerTarget(), GetNameLink(), Unit::GetOwner(), Unit::GetPet(), WorldSession::GetPlayer(), getSelectedCreature(), Object::GetTypeId(), Creature::IsPet(), LANG_NO_CHAR_SELECTED, LANG_RESET_PET_TALENTS, LANG_RESET_PET_TALENTS_ONLINE, LANG_RESET_TALENTS, LANG_RESET_TALENTS_ONLINE, m_session, PSendSysMessage(), Player::resetTalents(), Pet::resetTalentsForAllPetsOf(), SendSysMessage(), Player::SendTalentsInfoData(), SetSentErrorMessage(), and TYPEID_PLAYER.
Referenced by getCommandTable().
HandleResetTaxiNodesCommand()
bool ChatHandler::HandleResetTaxiNodesCommand (char * args) protected
Definition at line 5206 of file Level3.cpp.
References AT_LOGIN_RESET_TAXINODES, CharacterDatabase, ChatHandler(), ExtractPlayerTarget(), ObjectGuid::GetCounter(), GetNameLink(), WorldSession::GetPlayer(), Player::InitTaxiNodesForLevel(), LANG_NO_CHAR_SELECTED, m_session, Database::PExecute(), playerLink(), PSendSysMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleRespawnCommand()
bool ChatHandler::HandleRespawnCommand (char * args) protected
Definition at line 6067 of file Level3.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Map::GetMapDataContainer(), Map::GetPersistentState(), WorldSession::GetPlayer(), WorldObject::GetPosition(), getSelectedUnit(), Player::GetSelectionGuid(), MapDataContainer::GetSpawnGroupByGuid(), Map::GetSpawnManager(), Object::GetTypeId(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), Unit::IsDead(), WorldObject::IsUsingNewSpawningSystem(), LANG_SELECT_CREATURE, m_session, Creature::Respawn(), SpawnManager::RespawnCreature(), SpawnManager::RespawnSpawnGroupsInVicinity(), MapPersistentState::SaveCreatureRespawnTime(), SendSysMessage(), SetSentErrorMessage(), TYPEID_UNIT, and Cell::VisitGridObjects().
Referenced by getCommandTable().
HandleReviveCommand()
bool ChatHandler::HandleReviveCommand (char * args) protected
Definition at line 3842 of file Level3.cpp.
References ExtractPlayerTarget(), Player::ResurrectPlayer(), sObjectAccessor, and Player::SpawnCorpseBones().
Referenced by getCommandTable(), and PlayerbotChatHandler::revive().
HandleSaveAllCommand()
bool ChatHandler::HandleSaveAllCommand (char * args) protected
Development Commands.
Definition at line 1528 of file Level1.cpp.
References LANG_PLAYERS_SAVED, SendSysMessage(), and sObjectAccessor.
Referenced by getCommandTable().
HandleSaveCommand()
bool ChatHandler::HandleSaveCommand (char * args) protected
Definition at line 136 of file Level0.cpp.
References CONFIG_UINT32_INTERVAL_SAVE, GetAccessLevel(), WorldSession::GetPlayer(), Player::GetSaveTimer(), IN_MILLISECONDS, LANG_PLAYER_SAVED, m_session, Player::SaveToDB(), SEC_PLAYER, SendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleScourgeInvasionBattlesWonCommand()
bool ChatHandler::HandleScourgeInvasionBattlesWonCommand (char * args) protected
Definition at line 7776 of file Level3.cpp.
References ExtractInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleScourgeInvasionCommand()
bool ChatHandler::HandleScourgeInvasionCommand (char * args) protected
Definition at line 7758 of file Level3.cpp.
Referenced by getCommandTable().
HandleScourgeInvasionStartZone()
bool ChatHandler::HandleScourgeInvasionStartZone (char * args) protected
Definition at line 7789 of file Level3.cpp.
References ExtractInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleScourgeInvasionStateCommand()
bool ChatHandler::HandleScourgeInvasionStateCommand (char * args) protected
Definition at line 7763 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), SI_STATE_MAX, and sWorldState.
Referenced by getCommandTable().
HandleSD2HelpCommand()
bool ChatHandler::HandleSD2HelpCommand (char * args) protected
Definition at line 1555 of file debugcmds.cpp.
References Map::GetInstanceData(), WorldObject::GetMap(), WorldSession::GetPlayer(), m_session, and PSendSysMessage().
Referenced by getCommandTable().
HandleSD2ScriptCommand()
bool ChatHandler::HandleSD2ScriptCommand (char * args) protected
Definition at line 1565 of file debugcmds.cpp.
References Map::GetInstanceData(), WorldObject::GetMap(), WorldSession::GetPlayer(), m_session, and PSendSysMessage().
Referenced by getCommandTable().
HandleSendItemsCommand()
bool ChatHandler::HandleSendItemsCommand (char * args) protected
Definition at line 7071 of file Level3.cpp.
References ExtractPlayerTarget(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendItemsHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, playerLink(), PSendSysMessage(), and MailDraft::SendMailTo().
Referenced by getCommandTable().
HandleSendItemsHelper()
bool ChatHandler::HandleSendItemsHelper (MailDraft & draft, char * args) protected
Definition at line 6992 of file Level3.cpp.
References MailDraft::AddItem(), Item::CreateItem(), ExtractArg(), ExtractQuotedArg(), ObjectMgr::GetItemPrototype(), ItemPrototype::GetMaxStackSize(), WorldSession::GetPlayer(), LANG_COMMAND_INVALID_ITEM_COUNT, LANG_COMMAND_ITEMIDINVALID, LANG_COMMAND_MAIL_ITEMS_LIMIT, m_session, MAX_MAIL_ITEMS, ItemPrototype::MaxCount, PSendSysMessage(), SetSentErrorMessage(), and MailDraft::SetSubjectAndBody().
Referenced by HandleSendItemsCommand(), and HandleSendMassItemsCommand().
HandleSendMailCommand()
bool ChatHandler::HandleSendMailCommand (char * args) protected
Definition at line 1536 of file Level1.cpp.
References ExtractPlayerTarget(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendMailHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, playerLink(), PSendSysMessage(), and MailDraft::SendMailTo().
Referenced by getCommandTable().
HandleSendMailHelper()
bool ChatHandler::HandleSendMailHelper (MailDraft & draft, char * args) protected
Definition at line 6947 of file Level3.cpp.
References ExtractQuotedArg(), and MailDraft::SetSubjectAndBody().
Referenced by HandleSendMailCommand(), and HandleSendMassMailCommand().
HandleSendMassItemsCommand()
bool ChatHandler::HandleSendMassItemsCommand (char * args) protected
Definition at line 7096 of file Level3.cpp.
References ExtractRaceMask(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendItemsHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, PSendSysMessage(), and sMassMailMgr.
Referenced by getCommandTable().
HandleSendMassMailCommand()
bool ChatHandler::HandleSendMassMailCommand (char * args) protected
Definition at line 6964 of file Level3.cpp.
References ExtractRaceMask(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendMailHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, PSendSysMessage(), and sMassMailMgr.
Referenced by getCommandTable().
HandleSendMassMoneyCommand()
bool ChatHandler::HandleSendMassMoneyCommand (char * args) protected
format: raceMask "subject text" "mail text" money
Definition at line 7176 of file Level3.cpp.
References ExtractRaceMask(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendMoneyHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, PSendSysMessage(), and sMassMailMgr.
Referenced by getCommandTable().
HandleSendMessageCommand()
bool ChatHandler::HandleSendMessageCommand (char * args) protected
Send a message to a player in game.
Find the player
message
Check that he is not logging out.
Send the message
Definition at line 7206 of file Level3.cpp.
References ExtractPlayerTarget(), GetNameLink(), Player::GetSession(), WorldSession::isLogingOut(), LANG_PLAYER_NOT_FOUND, LANG_SENDMESSAGE, PSendSysMessage(), WorldSession::SendAreaTriggerMessage(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleSendMoneyCommand()
bool ChatHandler::HandleSendMoneyCommand (char * args) protected
format: name "subject text" "mail text" money
Definition at line 7150 of file Level3.cpp.
References ExtractPlayerTarget(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), WorldSession::GetPlayer(), HandleSendMoneyHelper(), LANG_MAIL_SENT, m_session, MAIL_NORMAL, MAIL_STATIONERY_GM, playerLink(), PSendSysMessage(), and MailDraft::SendMailTo().
Referenced by getCommandTable().
HandleSendMoneyHelper()
bool ChatHandler::HandleSendMoneyHelper (MailDraft & draft, char * args) protected
format: "subject text" "mail text" money
Definition at line 7125 of file Level3.cpp.
References ExtractQuotedArg(), ExtractUInt32(), MailDraft::SetMoney(), and MailDraft::SetSubjectAndBody().
Referenced by HandleSendMassMoneyCommand(), and HandleSendMoneyCommand().
HandleServerCorpsesCommand()
bool ChatHandler::HandleServerCorpsesCommand (char * args) protected
Triggering corpses expire check in world.
Definition at line 4832 of file Level2.cpp.
References sObjectAccessor.
Referenced by getCommandTable().
HandleServerIdleRestartCommand()
bool ChatHandler::HandleServerIdleRestartCommand (char * args) protected
Definition at line 5322 of file Level3.cpp.
References ExtractOptUInt32(), ExtractUInt32(), RESTART_EXIT_CODE, SHUTDOWN_MASK_IDLE, SHUTDOWN_MASK_RESTART, and sWorld.
Referenced by getCommandTable().
HandleServerIdleShutDownCommand()
bool ChatHandler::HandleServerIdleShutDownCommand (char * args) protected
Definition at line 5342 of file Level3.cpp.
References ExtractOptUInt32(), ExtractUInt32(), SHUTDOWN_EXIT_CODE, SHUTDOWN_MASK_IDLE, and sWorld.
Referenced by getCommandTable().
HandleServerInfoCommand()
bool ChatHandler::HandleServerInfoCommand (char * args) protected
Definition at line 89 of file Level0.cpp.
References _FULLVERSION, LANG_CONNECTED_USERS, LANG_UPTIME, LANG_USING_EVENT_AI, LANG_USING_WORLD_DB, m_session, PSendSysMessage(), secsToTimeString(), SendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleServerMotdCommand()
bool ChatHandler::HandleServerMotdCommand (char * args) protected
Display the 'Message of the day' for the realm.
Definition at line 281 of file Level0.cpp.
References LANG_MOTD_CURRENT, PSendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleServerPLimitCommand()
bool ChatHandler::HandleServerPLimitCommand (char * args) protected
Definition at line 6412 of file Level3.cpp.
References DEFAULT_PLAYER_LIMIT, ExtractInt32(), ExtractLiteralArg(), PSendSysMessage(), sConfig, SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, SEC_PLAYER, and sWorld.
Referenced by getCommandTable().
HandleServerResetAllRaidCommand()
bool ChatHandler::HandleServerResetAllRaidCommand (char * args) protected
Definition at line 7503 of file Level3.cpp.
References PSendSysMessage(), and sMapPersistentStateMgr.
Referenced by getCommandTable().
HandleServerRestartCommand()
bool ChatHandler::HandleServerRestartCommand (char * args) protected
Definition at line 5302 of file Level3.cpp.
References ExtractOptUInt32(), ExtractUInt32(), RESTART_EXIT_CODE, SHUTDOWN_MASK_RESTART, and sWorld.
Referenced by getCommandTable().
HandleServerSetMotdCommand()
bool ChatHandler::HandleServerSetMotdCommand (char * args) protected
Define the 'Message of the day' for the realm.
Definition at line 6836 of file Level3.cpp.
References LANG_MOTD_NEW, PSendSysMessage(), and sWorld.
Referenced by getCommandTable().
HandleServerShutDownCancelCommand()
bool ChatHandler::HandleServerShutDownCancelCommand (char * args) protected
Definition at line 5276 of file Level3.cpp.
References sWorld.
Referenced by getCommandTable().
HandleServerShutDownCommand()
bool ChatHandler::HandleServerShutDownCommand (char * args) protected
Definition at line 5282 of file Level3.cpp.
References ExtractOptUInt32(), ExtractUInt32(), SHUTDOWN_EXIT_CODE, and sWorld.
Referenced by getCommandTable().
HandleSetSkillCommand()
bool ChatHandler::HandleSetSkillCommand (char * args) protected
Definition at line 1535 of file Level3.cpp.
References ExtractInt32(), ExtractKeyFromLink(), ExtractOptInt32(), GetNameLink(), getSelectedPlayer(), GetSessionDbcLocale(), Player::GetSkillMaxPure(), Player::GetSkillValue(), LANG_INVALID_SKILL_ID, LANG_NO_CHAR_SELECTED, LANG_SET_SKILL, LANG_SET_SKILL_ERROR, SkillLineEntry::name, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), Player::SetSkill(), and sSkillLineStore.
Referenced by getCommandTable().
HandleSetValueHelper()
bool ChatHandler::HandleSetValueHelper (Object * target, uint32 field, char * typeStr, char * valStr) protected
Definition at line 818 of file debugcmds.cpp.
References DEBUG_LOG, ExtractFloat(), ExtractUInt32Base(), GetMangosString(), Object::GetObjectGuid(), ObjectGuid::GetString(), Object::GetValuesCount(), LANG_SET_FLOAT, LANG_SET_FLOAT_FIELD, LANG_SET_UINT, LANG_SET_UINT_FIELD, LANG_TOO_BIG_INDEX, OBJECT_FIELD_ENTRY, PSendSysMessage(), Object::SetFloatValue(), and Object::SetUInt32Value().
Referenced by HandleDebugSetItemValueCommand(), and HandleDebugSetValueByIndexCommand().
HandleSetViewCommand()
bool ChatHandler::HandleSetViewCommand (char * args) protected
Definition at line 2356 of file Level1.cpp.
References Player::GetCamera(), WorldSession::GetPlayer(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, m_session, PSendSysMessage(), SetSentErrorMessage(), and Camera::SetView().
Referenced by getCommandTable().
HandleShowAreaCommand()
bool ChatHandler::HandleShowAreaCommand (char * args) protected
Definition at line 4490 of file Level3.cpp.
References GetAreaFlagByAreaID(), getSelectedPlayer(), Object::GetUInt32Value(), LANG_BAD_VALUE, LANG_EXPLORE_AREA, LANG_NO_CHAR_SELECTED, PLAYER_EXPLORED_ZONES_1, PLAYER_EXPLORED_ZONES_SIZE, SendSysMessage(), SetSentErrorMessage(), and Object::SetUInt32Value().
Referenced by getCommandTable().
HandleShowGearScoreCommand()
bool ChatHandler::HandleShowGearScoreCommand (char * args) protected
Definition at line 7355 of file Level3.cpp.
References ExtractOptUInt32(), Player::GetEquipGearScore(), GetNameLink(), getSelectedPlayer(), LANG_GEARSCORE, LANG_PLAYER_NOT_FOUND, PSendSysMessage(), Player::ResetCachedGearScore(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleShowTemporarySpawnList()
bool ChatHandler::HandleShowTemporarySpawnList (char * args) protected
Definition at line 1438 of file debugcmds.cpp.
References WorldObject::GetMap(), WorldSession::GetPlayer(), Map::GetTempCreatures(), Map::GetTempPets(), m_session, PSendSysMessage(), and SendSysMessage().
Referenced by getCommandTable().
HandleStableCommand()
bool ChatHandler::HandleStableCommand (char * args) protected
Definition at line 4683 of file Level3.cpp.
References Object::GetObjectGuid(), WorldSession::GetPlayer(), m_session, and WorldSession::SendStablePet().
Referenced by getCommandTable().
HandleStartCommand()
bool ChatHandler::HandleStartCommand (char * args) protected
Definition at line 66 of file Level0.cpp.
References Unit::CastSpell(), WorldSession::GetPlayer(), Unit::IsInCombat(), Unit::IsTaxiFlying(), LANG_YOU_IN_COMBAT, LANG_YOU_IN_FLIGHT, m_session, SendSysMessage(), SetSentErrorMessage(), and TRIGGERED_NONE.
Referenced by getCommandTable().
HandleSunsReachReclamationCounterCommand()
bool ChatHandler::HandleSunsReachReclamationCounterCommand (char * args) protected
Definition at line 7826 of file Level3.cpp.
References COUNTERS_MAX, ExtractUInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleSunsReachReclamationPhaseCommand()
bool ChatHandler::HandleSunsReachReclamationPhaseCommand (char * args) protected
Definition at line 7802 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleSunsReachReclamationSubPhaseCommand()
bool ChatHandler::HandleSunsReachReclamationSubPhaseCommand (char * args) protected
Definition at line 7814 of file Level3.cpp.
References ExtractInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleSunwellGateCommand()
bool ChatHandler::HandleSunwellGateCommand (char * args) protected
Definition at line 7846 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleSunwellGateCounterCommand()
bool ChatHandler::HandleSunwellGateCounterCommand (char * args) protected
Definition at line 7858 of file Level3.cpp.
References COUNTERS_MAX_GATES, ExtractUInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleTaxiCheatCommand()
bool ChatHandler::HandleTaxiCheatCommand (char * args) protected
Definition at line 977 of file Level1.cpp.
References ChatHandler(), ExtractOnOff(), GetNameLink(), WorldSession::GetPlayer(), getSelectedPlayer(), HasLowerSecurity(), LANG_USE_BOL, LANG_YOU_GIVE_TAXIS, LANG_YOU_REMOVE_TAXIS, LANG_YOURS_TAXIS_ADDED, LANG_YOURS_TAXIS_REMOVED, m_session, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Player::SetTaxiCheater().
Referenced by getCommandTable().
HandleTeleAddCommand()
bool ChatHandler::HandleTeleAddCommand (char * args) protected
Definition at line 4730 of file Level3.cpp.
References WorldObject::GetMapId(), WorldObject::GetOrientation(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), LANG_COMMAND_TP_ADDED, LANG_COMMAND_TP_ADDEDERR, LANG_COMMAND_TP_ALREADYEXIST, m_session, GameTele::mapId, GameTele::name, GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleTeleCommand()
bool ChatHandler::HandleTeleCommand (char * args) protected
Definition at line 1365 of file Level1.cpp.
References ExtractGameTeleFromLink(), WorldSession::GetPlayer(), HandleGoHelper(), LANG_COMMAND_TELE_NOTFOUND, m_session, GameTele::mapId, GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleTeleDelCommand()
bool ChatHandler::HandleTeleDelCommand (char * args) protected
Definition at line 4770 of file Level3.cpp.
References LANG_COMMAND_TELE_NOTFOUND, LANG_COMMAND_TP_DELETED, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by getCommandTable().
HandleTeleGroupCommand()
bool ChatHandler::HandleTeleGroupCommand (char * args) protected
Definition at line 1617 of file Level1.cpp.
References ChatHandler(), ExtractGameTeleFromLink(), Group::GetFirstMember(), Player::GetGroup(), GetNameLink(), getSelectedPlayer(), Player::GetSession(), HasLowerSecurity(), MapEntry::IsBattleGroundOrArena(), Player::IsBeingTeleported(), LANG_COMMAND_TELE_NOTFOUND, LANG_IS_TELEPORTED, LANG_NO_CHAR_SELECTED, LANG_NOT_IN_GROUP, LANG_TELEPORTED_TO_BY, LANG_TELEPORTING_TO, GameTele::mapId, GameTele::name, needReportToTarget(), GroupReference::next(), GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, PSendSysMessage(), Player::SaveRecallPosition(), SendSysMessage(), SetSentErrorMessage(), sMapStore, Player::TaxiFlightInterrupt(), and Player::TeleportTo().
Referenced by getCommandTable().
HandleTeleNameCommand()
bool ChatHandler::HandleTeleNameCommand (char * args) protected
Definition at line 1562 of file Level1.cpp.
References ChatHandler(), ExtractGameTeleFromLink(), ExtractOptNotLastArg(), ExtractPlayerTarget(), GetMangosString(), GetNameLink(), HandleGoHelper(), HasLowerSecurity(), Player::IsBeingTeleported(), LANG_COMMAND_TELE_NOTFOUND, LANG_IS_TELEPORTED, LANG_OFFLINE, LANG_TELEPORTED_TO_BY, LANG_TELEPORTING_TO, GameTele::mapId, GameTele::name, needReportToTarget(), GameTele::orientation, playerLink(), GameTele::position_x, GameTele::position_y, GameTele::position_z, PSendSysMessage(), Player::SavePositionInDB(), SendSysMessage(), SetSentErrorMessage(), and sTerrainMgr.
Referenced by getCommandTable().
HandleTicketCommand()
bool ChatHandler::HandleTicketCommand (char * args) protected
Definition at line 244 of file TicketCommands.cpp.
References HandleTicketReadCommand().
Referenced by getCommandTable().
HandleTicketDiscardCommand()
bool ChatHandler::HandleTicketDiscardCommand (char * args) protected
Definition at line 45 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketEscalateCommand()
bool ChatHandler::HandleTicketEscalateCommand (char * args) protected
Definition at line 72 of file TicketCommands.cpp.
References ExtractOptUInt32(), ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, SEC_PLAYER, SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketGoCommand()
bool ChatHandler::HandleTicketGoCommand (char * args) protected
Definition at line 89 of file TicketCommands.cpp.
References ExtractUInt32(), GMTicket::GetIdTag(), GMTicket::GetMapId(), WorldSession::GetPlayer(), GMTicket::GetPositionO(), GMTicket::GetPositionX(), GMTicket::GetPositionY(), GMTicket::GetPositionZ(), HandleGoHelper(), LANG_COMMAND_TICKET_NOT_FOUND, m_session, PSendSysMessage(), SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketGoNameCommand()
bool ChatHandler::HandleTicketGoNameCommand (char * args) protected
Definition at line 108 of file TicketCommands.cpp.
References ExtractUInt32(), GMTicket::GetAuthorName(), GMTicket::GetIdTag(), HandleGonameCommand(), LANG_COMMAND_TICKET_NOT_FOUND, mangos_strdup(), PSendSysMessage(), SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketNoteCommand()
bool ChatHandler::HandleTicketNoteCommand (char * args) protected
Definition at line 128 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketReadCommand()
bool ChatHandler::HandleTicketReadCommand (char * args) protected
Definition at line 146 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, GMTicketMgr::Print(), SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable(), and HandleTicketCommand().
HandleTicketResolveCommand()
bool ChatHandler::HandleTicketResolveCommand (char * args) protected
Definition at line 165 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketsCommand()
bool ChatHandler::HandleTicketsCommand (char * args) protected
Definition at line 308 of file TicketCommands.cpp.
References ExtractLiteralArg(), ExtractOnOff(), ExtractUInt32(), WorldSession::GetPlayer(), HandleTicketsListCommand(), LANG_USE_BOL, m_session, SendSysMessage(), Player::SetAcceptTicket(), SetSentErrorMessage(), sTicketMgr, and strToLower().
Referenced by getCommandTable().
HandleTicketsListCommand()
bool ChatHandler::HandleTicketsListCommand (char * args) protected
Definition at line 249 of file TicketCommands.cpp.
References ExtractLiteralArg(), ExtractUInt32(), LANG_COMMAND_TICKETS_BAD_CATEGORY, LANG_COMMAND_TICKETS_LISTING, LANG_COMMAND_TICKETS_NO_TICKETS, m_session, PSendSysMessage(), SetSentErrorMessage(), sGMTicketCategoryStore, and sTicketMgr.
Referenced by getCommandTable(), and HandleTicketsCommand().
HandleTicketSortCommand()
bool ChatHandler::HandleTicketSortCommand (char * args) protected
Definition at line 192 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), LANG_COMMAND_TICKETS_BAD_CATEGORY, m_session, PSendSysMessage(), SetSentErrorMessage(), sGMTicketCategoryStore, and sTicketMgr.
Referenced by getCommandTable().
HandleTicketsQueueCommand()
bool ChatHandler::HandleTicketsQueueCommand (char * args) protected
Definition at line 292 of file TicketCommands.cpp.
References ExtractOnOff(), LANG_USE_BOL, SendSysMessage(), SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTicketWhisperCommand()
bool ChatHandler::HandleTicketWhisperCommand (char * args) protected
Definition at line 217 of file TicketCommands.cpp.
References ExtractUInt32(), HandleTicketMgrCommandResult(), m_session, SetSentErrorMessage(), and sTicketMgr.
Referenced by getCommandTable().
HandleTitlesAddCommand()
bool ChatHandler::HandleTitlesAddCommand (char * args) protected
Definition at line 4967 of file Level2.cpp.
References ExtractUint32KeyFromLink(), WorldObject::GetName(), GetNameLink(), getSelectedPlayer(), GetSessionDbcLocale(), HasLowerSecurity(), LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_ADD_RES, CharTitlesEntry::name, PSendSysMessage(), sCharTitlesStore, SendSysMessage(), SetSentErrorMessage(), and Player::SetTitle().
Referenced by getCommandTable().
HandleTitlesCurrentCommand()
bool ChatHandler::HandleTitlesCurrentCommand (char * args) protected
Definition at line 5176 of file Level2.cpp.
References CharTitlesEntry::bit_index, ExtractUint32KeyFromLink(), GetNameLink(), getSelectedPlayer(), GetSessionDbcLocale(), HasLowerSecurity(), LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_CURRENT_RES, CharTitlesEntry::name, PLAYER_CHOSEN_TITLE, PSendSysMessage(), sCharTitlesStore, SendSysMessage(), SetSentErrorMessage(), Player::SetTitle(), and Object::SetUInt32Value().
Referenced by getCommandTable().
HandleTitlesRemoveCommand()
bool ChatHandler::HandleTitlesRemoveCommand (char * args) protected
Definition at line 5013 of file Level2.cpp.
References ExtractUint32KeyFromLink(), Object::GetInt32Value(), WorldObject::GetName(), GetNameLink(), getSelectedPlayer(), GetSessionDbcLocale(), HasLowerSecurity(), Player::HasTitle(), LANG_CURRENT_TITLE_RESET, LANG_INVALID_TITLE_ID, LANG_NO_CHAR_SELECTED, LANG_TITLE_REMOVE_RES, CharTitlesEntry::name, PLAYER_CHOSEN_TITLE, PSendSysMessage(), sCharTitlesStore, SendSysMessage(), SetSentErrorMessage(), Player::SetTitle(), and Object::SetUInt32Value().
Referenced by getCommandTable().
HandleTitlesSetMaskCommand()
bool ChatHandler::HandleTitlesSetMaskCommand (char * args) protected
Definition at line 5067 of file Level2.cpp.
References Object::GetInt32Value(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), Player::HasTitle(), LANG_CURRENT_TITLE_RESET, LANG_DONE, LANG_NO_CHAR_SELECTED, PLAYER__FIELD_KNOWN_TITLES, PLAYER_CHOSEN_TITLE, PSendSysMessage(), sCharTitlesStore, SendSysMessage(), SetSentErrorMessage(), Object::SetUInt32Value(), Object::SetUInt64Value(), and UI64FMTD.
Referenced by getCommandTable().
HandleTitlesSwapCommand()
bool ChatHandler::HandleTitlesSwapCommand (char * args) protected
Definition at line 5108 of file Level2.cpp.
References getSelectedPlayer(), Player::HasTitle(), sCharTitlesStore, and Player::SetTitle().
Referenced by getCommandTable().
HandleTriggerActiveCommand()
bool ChatHandler::HandleTriggerActiveCommand (char * args) protected
Definition at line 328 of file Level2.cpp.
References WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), IsPointInAreaTriggerZone(), LANG_COMMAND_NOTRIGGERFOUND, m_session, sAreaTriggerStore, SendSysMessage(), and ShowTriggerListHelper().
Referenced by getCommandTable().
HandleTriggerCommand()
bool ChatHandler::HandleTriggerCommand (char * args) protected
Definition at line 213 of file Level2.cpp.
References ExtractUint32KeyFromLink(), WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), GetSessionDbLocaleIndex(), AreaTrigger::heroicKey, AreaTrigger::heroicKey2, AreaTriggerEntry::id, LANG_COMMAND_GOAREATRNOTFOUND, LANG_COMMAND_NOTRIGGERFOUND, LANG_TRIGGER_EXPLORE_QUEST, LANG_TRIGGER_REQ_ITEMS, LANG_TRIGGER_REQ_KEYS_HEROIC, LANG_TRIGGER_REQ_LEVEL, LANG_TRIGGER_REQ_QUEST_HEROIC, LANG_TRIGGER_REQ_QUEST_NORMAL, m_session, MAP_SIZE, AreaTriggerEntry::mapid, PSendSysMessage(), AreaTrigger::requiredItem, AreaTrigger::requiredItem2, AreaTrigger::requiredLevel, AreaTrigger::requiredQuest, AreaTrigger::requiredQuestHeroic, sAreaTriggerStore, SendSysMessage(), SetSentErrorMessage(), ShowItemListHelper(), ShowQuestListHelper(), ShowTriggerListHelper(), sObjectMgr, AreaTriggerEntry::x, and AreaTriggerEntry::y.
Referenced by getCommandTable().
HandleTriggerNearCommand()
bool ChatHandler::HandleTriggerNearCommand (char * args) protected
Definition at line 355 of file Level2.cpp.
References WorldObject::GetMapId(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), AreaTriggerEntry::id, LANG_COMMAND_NOTRIGGERFOUND, m_session, AreaTriggerEntry::mapid, sAreaTriggerStore, SendSysMessage(), ShowTriggerListHelper(), ShowTriggerTargetListHelper(), sObjectMgr, AreaTrigger::target_mapId, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTriggerEntry::x, and AreaTriggerEntry::y.
Referenced by getCommandTable().
HandleUnAuraCommand()
bool ChatHandler::HandleUnAuraCommand (char * args) protected
Definition at line 3911 of file Level3.cpp.
References ExtractSpellIdFromLink(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, Unit::RemoveAllAuras(), Unit::RemoveAurasDueToSpell(), SendSysMessage(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleUnBanAccountCommand()
bool ChatHandler::HandleUnBanAccountCommand (char * args) protected
Definition at line 5691 of file Level3.cpp.
References BAN_ACCOUNT, and HandleUnBanHelper().
Referenced by getCommandTable().
HandleUnBanCharacterCommand()
bool ChatHandler::HandleUnBanCharacterCommand (char * args) protected
Definition at line 5696 of file Level3.cpp.
References BAN_CHARACTER, and HandleUnBanHelper().
Referenced by getCommandTable().
HandleUnBanHelper()
bool ChatHandler::HandleUnBanHelper (BanMode mode, char * args) protected
Definition at line 5706 of file Level3.cpp.
References BAN_ACCOUNT, BAN_CHARACTER, BAN_IP, ExtractArg(), ExtractQuotedOrLiteralArg(), WorldSession::GetPlayerName(), IsIPAddress(), LANG_ACCOUNT_NOT_EXIST, LANG_PLAYER_NOT_FOUND, LANG_UNBAN_ERROR, LANG_UNBAN_UNBANNED, m_session, normalizePlayerName(), AccountMgr::normalizeString(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and sWorld.
Referenced by HandleUnBanAccountCommand(), HandleUnBanCharacterCommand(), and HandleUnBanIPCommand().
HandleUnBanIPCommand()
bool ChatHandler::HandleUnBanIPCommand (char * args) protected
Definition at line 5701 of file Level3.cpp.
References BAN_IP, and HandleUnBanHelper().
Referenced by getCommandTable().
HandleUnLearnCommand()
bool ChatHandler::HandleUnLearnCommand (char * args) protected
Definition at line 1595 of file Level3.cpp.
References ExtractLiteralArg(), ExtractSpellIdFromLink(), getSelectedPlayer(), GetTalentSpellCost(), Player::HasSpell(), LANG_FORGET_SPELL, LANG_NO_CHAR_SELECTED, Player::removeSpell(), SendSysMessage(), Player::SendTalentsInfoData(), SetSentErrorMessage(), and sSpellMgr.
Referenced by getCommandTable().
HandleUnmuteCommand()
bool ChatHandler::HandleUnmuteCommand (char * args) protected
Definition at line 126 of file Level2.cpp.
References Player::CanSpeak(), ChatHandler(), ExtractPlayerTarget(), WorldSession::GetAccountId(), Player::GetSession(), HasLowerSecurity(), LANG_CHAT_ALREADY_ENABLED, LANG_YOU_ENABLE_CHAT, LANG_YOUR_CHAT_ENABLED, LoginDatabase, WorldSession::m_muteTime, Database::PExecute(), playerLink(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), sObjectMgr, and sWorld.
Referenced by getCommandTable().
HandleVariablePrint()
bool ChatHandler::HandleVariablePrint (char * args) protected
Definition at line 7712 of file Level3.cpp.
References WorldObject::GetMap(), WorldSession::GetPlayer(), GetSession(), WorldStateVariableManager::GetVariableList(), Map::GetVariableManager(), and PSendSysMessage().
Referenced by getCommandTable().
HandleWarEffortCommand()
bool ChatHandler::HandleWarEffortCommand (char * args) protected
Definition at line 7720 of file Level3.cpp.
References PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleWarEffortCounterCommand()
bool ChatHandler::HandleWarEffortCounterCommand (char * args) protected
Definition at line 7738 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), RESOURCE_MAX, and sWorldState.
Referenced by getCommandTable().
HandleWarEffortPhaseCommand()
bool ChatHandler::HandleWarEffortPhaseCommand (char * args) protected
Definition at line 7726 of file Level3.cpp.
References ExtractUInt32(), PSendSysMessage(), and sWorldState.
Referenced by getCommandTable().
HandleWarnCharacterCommand()
bool ChatHandler::HandleWarnCharacterCommand (char * args) protected
Definition at line 5579 of file Level3.cpp.
References ExtractPlayerTarget(), ExtractQuotedOrLiteralArg(), WorldSession::GetAccountId(), WorldSession::GetPlayerName(), Player::GetSession(), LANG_PLAYER_NOT_FOUND, m_session, PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, and sWorld.
Referenced by getCommandTable().
HandleWaterwalkCommand()
bool ChatHandler::HandleWaterwalkCommand (char * args) protected
Definition at line 4857 of file Level2.cpp.
References ChatHandler(), ExtractOnOff(), GetNameLink(), getSelectedPlayer(), HasLowerSecurity(), LANG_NO_CHAR_SELECTED, LANG_USE_BOL, LANG_YOU_SET_WATERWALK, LANG_YOUR_WATERWALK_SET, needReportToTarget(), PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Unit::SetWaterWalk().
Referenced by getCommandTable().
HandleWhisperRestrictionCommand()
bool ChatHandler::HandleWhisperRestrictionCommand (char * args) protected
Definition at line 287 of file Level0.cpp.
References ExtractOnOff(), WorldSession::GetPlayer(), Player::isEnabledWhisperRestriction(), LANG_USE_BOL, m_session, PSendSysMessage(), SendSysMessage(), SetSentErrorMessage(), and Player::SetWhisperRestriction().
Referenced by getCommandTable().
HandleWhispersCommand()
bool ChatHandler::HandleWhispersCommand (char * args) protected
Definition at line 1495 of file Level1.cpp.
References ExtractOnOff(), GetOnOffStr(), WorldSession::GetPlayer(), Player::isAcceptWhispers(), LANG_COMMAND_WHISPERACCEPTING, LANG_COMMAND_WHISPEROFF, LANG_COMMAND_WHISPERON, LANG_USE_BOL, m_session, PSendSysMessage(), SendSysMessage(), Player::SetAcceptWhispers(), and SetSentErrorMessage().
Referenced by getCommandTable().
HandleWpAddCommand()
bool ChatHandler::HandleWpAddCommand (char * args) protected
Add a waypoint to a creature .wp add [dbGuid] [pathId] [source].
The user can either select an npc or provide its dbGuid. Also the user can specify pathId and source if wanted.
The user can even select a visual waypoint - then the new waypoint is placed after the selected one - this makes insertion of new waypoints possible.
.wp add [pathId] [source] -> adds a waypoint to the currently selected creature, to path pathId in source-storage
.wp add guid [pathId] [source] -> if no npc is selected, expect the creature provided with guid argument
Returns
true - command did succeed, false - something went wrong
< into which storage
< along which path
< pointId if a waypoint was selected, in this case insert after
targetCreature - first argument must be dbGuid
Definition at line 3045 of file Level2.cpp.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, DEBUG_LOG, ExtractOptUInt32(), ExtractUInt32(), QueryResult::Fetch(), Map::GetAnyTypeCreature(), ObjectMgr::GetCreatureTemplate(), MotionMaster::GetCurrent(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetGuidStr(), CreatureInfo::GetHighGuid(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), Object::GetObjectGuid(), CreatureData::GetObjectGuid(), WorldObject::GetOrientation(), WaypointManager::GetOriginString(), TemporarySpawnWaypoint::GetPathId(), TemporarySpawnWaypoint::GetPathOrigin(), WorldSession::GetPlayer(), WorldObject::GetPosition(), getSelectedCreature(), TemporarySpawn::GetSpawnerGuid(), ObjectGuid::GetString(), Creature::GetSubtype(), Field::GetUInt32(), TemporarySpawnWaypoint::GetWaypointId(), Creature::HasStaticDBSpawnData(), Helper_CreateWaypointFor(), HIGHGUID_UNIT, LANG_COMMAND_CREATUREATSAMEMAP, LANG_WAYPOINT_ADDED, LANG_WAYPOINT_CREATNOTFOUND, LANG_WAYPOINT_NOGUID, LANG_WAYPOINT_NOTCREATED, LANG_WAYPOINT_NOTFOUND_NPC, LANG_WAYPOINT_VP_NOTCREATED, LANG_WAYPOINT_VP_SELECT, m_session, CreatureData::mapid, PATH_FROM_ENTRY, PATH_FROM_GUID, PATH_NO_PATH, Database::PQuery(), PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, sWaypointMgr, UnsummonVisualWaypoints(), VISUAL_WAYPOINT, WAYPOINT_MOTION_TYPE, and WorldDatabase.
Referenced by getCommandTable().
HandleWpExportCommand()
bool ChatHandler::HandleWpExportCommand (char * args) protected
[Guid if no selected unit] <filename> [pathId [wpOrigin] ]
Definition at line 3643 of file Level2.cpp.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, ExtractLiteralArg(), ExtractOptUInt32(), ExtractUInt32(), Map::GetAnyTypeCreature(), MotionMaster::GetCurrent(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), CreatureData::GetObjectGuid(), TemporarySpawnWaypoint::GetPathId(), MotionMaster::GetPathId(), TemporarySpawnWaypoint::GetPathOrigin(), WorldSession::GetPlayer(), getSelectedCreature(), TemporarySpawn::GetSpawnerGuid(), ObjectGuid::GetString(), LANG_COMMAND_CREATUREATSAMEMAP, LANG_WAYPOINT_ARGUMENTREQ, LANG_WAYPOINT_CREATNOTFOUND, LANG_WAYPOINT_EXPORTED, LANG_WAYPOINT_NOGUID, LANG_WAYPOINT_NOTFOUND_NPC, LANG_WAYPOINT_NOTHINGTOEXPORT, LANG_WAYPOINT_VP_SELECT, m_session, CreatureData::mapid, PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, PATH_NO_PATH, PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, sWaypointMgr, VISUAL_WAYPOINT, and WAYPOINT_MOTION_TYPE.
Referenced by getCommandTable().
HandleWpModifyCommand()
bool ChatHandler::HandleWpModifyCommand (char * args) protected
.wp modify waittime | scriptid | orientation | del | move [dbGuid, id] [value]
waittime <Delay> User has selected a visual waypoint before. Delay <Delay> is added to this waypoint. Everytime the NPC comes to this waypoint, it will wait Delay millieseconds.
waittime <DBGuid> <WPNUM> <Delay> User has not selected visual waypoint before. For the waypoint <WPNUM> for the NPC with <DBGuid> an delay Delay is added to this waypoint Everytime the NPC comes to this waypoint, it will wait Delay millieseconds.
scriptid <scriptId> User has selected a visual waypoint before. <scriptId> is added to this waypoint. Everytime the NPC comes to this waypoint, the DBScript scriptId is executed.
scriptid <DBGuid> <WPNUM> <scriptId> User has not selected visual waypoint before. For the waypoint <WPNUM> for the NPC with <DBGuid> an emote <scriptId> is added. Everytime the NPC comes to this waypoint, the DBScript scriptId is executed.
orientation [DBGuid, WpNum] <Orientation> Set the orientation of the selected waypoint or waypoint given with DbGuid/ WpId to the value of <Orientation>.
del [DBGuid, WpId] Remove the selected waypoint or waypoint given with DbGuid/ WpId.
move [DBGuid, WpId] Move the selected waypoint or waypoint given with DbGuid/ WpId to player's current positiion.
Definition at line 3221 of file Level2.cpp.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, DEBUG_LOG, ExtractFloat(), ExtractLiteralArg(), ExtractUInt32(), Map::GetAnyTypeCreature(), ObjectMgr::GetCreatureTemplate(), MotionMaster::GetCurrent(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetGuidStr(), CreatureInfo::GetHighGuid(), WorldObject::GetMap(), Unit::GetMotionMaster(), CreatureData::GetObjectGuid(), WorldObject::GetOrientation(), WaypointManager::GetOriginString(), TemporarySpawnWaypoint::GetPathId(), TemporarySpawnWaypoint::GetPathOrigin(), WorldSession::GetPlayer(), WorldObject::GetPosition(), getSelectedCreature(), TemporarySpawn::GetSpawnerGuid(), ObjectGuid::GetString(), Creature::GetSubtype(), TemporarySpawnWaypoint::GetWaypointId(), Helper_CreateWaypointFor(), HIGHGUID_UNIT, MotionMaster::Initialize(), Unit::IsAlive(), JUST_DIED, LANG_WAYPOINT_CHANGED, LANG_WAYPOINT_CHANGED_NO, LANG_WAYPOINT_CREATNOTFOUND, LANG_WAYPOINT_INFO_UNK_SCRIPTID, LANG_WAYPOINT_NOGUID, LANG_WAYPOINT_NOTFOUND, LANG_WAYPOINT_NOTFOUND_NPC, LANG_WAYPOINT_NOTFOUNDPATH, LANG_WAYPOINT_NOWAYPOINTGIVEN, LANG_WAYPOINT_REMOVED, LANG_WAYPOINT_VP_NOTCREATED, LANG_WAYPOINT_VP_SELECT, m_session, Unit::NearTeleportTo(), PATH_NO_PATH, PSendSysMessage(), RANDOM_MOTION_TYPE, Creature::Respawn(), Creature::SaveToDB(), SendSysMessage(), Creature::SetDeathState(), Creature::SetDefaultMovementType(), SetSentErrorMessage(), sObjectMgr, sWaypointMgr, VISUAL_WAYPOINT, and WAYPOINT_MOTION_TYPE.
Referenced by getCommandTable().
HandleWpShowCommand()
bool ChatHandler::HandleWpShowCommand (char * args) protected
.wp show info | on | off | first | last [dbGuid] [pathId [wpOrigin] ]
info -> User has selected a visual waypoint before
on -> User has selected an NPC; all visual waypoints for this NPC are added to the world
on <dbGuid> -> User did not select an NPC - instead the dbGuid of the NPC is provided. All visual waypoints for this NPC are added from the world.
off -> User has selected an NPC; all visual waypoints for this NPC are removed from the world.
< info, on, off, first, last
< Npc that is moving
Definition at line 3437 of file Level2.cpp.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, DEBUG_LOG, ExtractLiteralArg(), ExtractOptUInt32(), ExtractUInt32(), Map::GetAnyTypeCreature(), Map::GetCreature(), Creature::GetCreatureGroup(), ObjectMgr::GetCreatureTemplate(), MotionMaster::GetCurrent(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetDbGuid(), Object::GetEntry(), CreatureGroup::GetFormationEntry(), Object::GetGUIDLow(), Object::GetGuidStr(), CreatureInfo::GetHighGuid(), WorldObject::GetMap(), Unit::GetMotionMaster(), Object::GetObjectGuid(), CreatureData::GetObjectGuid(), WaypointManager::GetOriginString(), TemporarySpawnWaypoint::GetPathId(), TemporarySpawnWaypoint::GetPathOrigin(), WorldSession::GetPlayer(), Creature::GetScriptName(), getSelectedCreature(), TemporarySpawn::GetSpawnerGuid(), ObjectGuid::GetString(), Creature::GetSubtype(), TemporarySpawnWaypoint::GetWaypointId(), Helper_CreateWaypointFor(), HIGHGUID_UNIT, LANG_WAYPOINT_CREATNOTFOUND, LANG_WAYPOINT_INFO_AISCRIPT, LANG_WAYPOINT_INFO_ORI, LANG_WAYPOINT_INFO_SCRIPTID, LANG_WAYPOINT_INFO_TITLE, LANG_WAYPOINT_INFO_WAITTIME, LANG_WAYPOINT_NOTFOUND, LANG_WAYPOINT_NOTFOUND_NPC, LANG_WAYPOINT_NOTFOUNDPATH, LANG_WAYPOINT_VP_ALLREMOVED, LANG_WAYPOINT_VP_NOTCREATED, LANG_WAYPOINT_VP_SELECT, LINEAR_WP_MOTION_TYPE, m_session, PATH_FROM_EXTERNAL, PATH_MOTION_TYPE, PATH_NO_PATH, PSendSysMessage(), SetSentErrorMessage(), sObjectMgr, sWaypointMgr, UnsummonVisualWaypoints(), VISUAL_WAYPOINT, and WAYPOINT_MOTION_TYPE.
Referenced by getCommandTable().
HasEscapeSequences()
bool ChatHandler::HasEscapeSequences (const char * message) static
Definition at line 1697 of file Chat.cpp.
Referenced by WorldSession::CheckChatChannelNameAndPassword().
HasLowerSecurity()
bool ChatHandler::HasLowerSecurity (Player * target, ObjectGuid guid = ObjectGuid(), bool strong = false) protected
Definition at line 1146 of file Chat.cpp.
References Player::GetSession(), HasLowerSecurityAccount(), LANG_PLAYER_NOT_FOUND, SendSysMessage(), SetSentErrorMessage(), and sObjectMgr.
Referenced by HandleCharacterRenameCommand(), HandleCombatStopCommand(), HandleDebugSpellModsCommand(), HandleDeMorphCommand(), HandleDieCommand(), HandleGonameCommand(), HandleGroupgoCommand(), HandleHonorAddCommand(), HandleHonorAddKillCommand(), HandleHonorUpdateCommand(), HandleKickPlayerCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFlyCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyMorphCommand(), HandleModifyPhaseCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleModifyTalentCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleNpcWhisperCommand(), HandlePInfoCommand(), HandleRecallCommand(), HandleRepairitemsCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleUnmuteCommand(), HandleWaterwalkCommand(), and ModifyMountCommandHelper().
HasLowerSecurityAccount()
bool ChatHandler::HasLowerSecurityAccount (WorldSession * target, uint32 target_account, bool strong = false) protected
Definition at line 1166 of file Chat.cpp.
References CONFIG_BOOL_GM_LOWER_SECURITY, GetAccessLevel(), WorldSession::GetSecurity(), LANG_YOURS_SECURITY_IS_LOW, sAccountMgr, SEC_PLAYER, SendSysMessage(), SetSentErrorMessage(), and sWorld.
Referenced by HandleAccountDeleteCommand(), HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), and HasLowerSecurity().
HasSentErrorMessage()
bool ChatHandler::HasSentErrorMessage () const inline
Definition at line 105 of file Chat.h.
References sentErrorMessage.
Referenced by ExecuteCommand(), and World::ProcessCliCommands().
hasStringAbbr()
bool ChatHandler::hasStringAbbr (const char * name, const char * part) const protected
Definition at line 1191 of file Chat.cpp.
Referenced by FindCommand().
isAvailable()
bool ChatHandler::isAvailable (ChatCommand const & cmd) const protected virtual
Reimplemented in CliHandler.
Definition at line 1135 of file Chat.cpp.
References GetAccessLevel(), and ChatCommand::SecurityLevel.
Referenced by FindCommand(), and ShowHelpForSubCommands().
LineFromMessage()
static char* ChatHandler::LineFromMessage (char *& pos) inline static
Definition at line 87 of file Chat.h.
Referenced by SendGlobalSysMessage(), and SendSysMessage().
LogCommand()
void ChatHandler::LogCommand (char const * fullcmd) const protected
Definition at line 3763 of file Chat.cpp.
References GetAccountId(), WorldObject::GetMapId(), WorldObject::GetName(), WorldSession::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetSelectionGuid(), ObjectGuid::GetString(), m_session, and sLog.
Referenced by ExecuteCommand(), HandleAccountPasswordCommand(), and HandleAccountSetPasswordCommand().
LookupPlayerSearchCommand()
bool ChatHandler::LookupPlayerSearchCommand (QueryResult * result, uint32 * limit = nullptr) protected
Get the characters for account id
Definition at line 4492 of file Level2.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetCppString(), QueryResult::GetRowCount(), Field::GetUInt32(), LANG_LOOKUP_PLAYER_ACCOUNT, LANG_NO_PLAYERS_FOUND, QueryResult::NextRow(), Database::PQuery(), PSendSysMessage(), SetSentErrorMessage(), and ShowPlayerListHelper().
Referenced by HandleLookupPlayerAccountCommand(), HandleLookupPlayerEmailCommand(), and HandleLookupPlayerIpCommand().
ModifyMountCommandHelper()
bool ChatHandler::ModifyMountCommandHelper (Player * target, char * args) protected
Definition at line 2115 of file Level1.cpp.
References ALLIANCE, Unit::CastSpell(), ChatHandler(), ExtractLiteralArg(), Unit::GetLevel(), GetNameLink(), WorldSession::GetSecurity(), Player::GetTeam(), Unit::HasAura(), HasLowerSecurity(), Unit::IsFlying(), Unit::IsTaxiFlying(), LANG_MOUNT_GIVED, LANG_NO_CHAR_SELECTED, LANG_NO_MOUNT, LANG_YOU_GIVE_MOUNT, LANG_YOU_IN_FLIGHT, m_session, needReportToTarget(), PSendSysMessage(), SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_MODERATOR, SendSysMessage(), SetSentErrorMessage(), SPELL_CAST_OK, TRIGGERED_DO_NOT_PROC, TRIGGERED_INSTANT_CAST, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by HandleGMMountUpCommand(), and HandleModifyMountCommand().
ModifyStatCommandHelper()
bool ChatHandler::ModifyStatCommandHelper (char * args, char const * statName, uint32 spellId) protected
Definition at line 7972 of file Level3.cpp.
References Unit::CastCustomSpell(), ExtractInt32(), Unit::GetMaxPower(), WorldObject::GetName(), getSelectedUnit(), LANG_SELECT_CHAR_OR_CREATURE, POWER_MANA, PSendSysMessage(), Unit::RemoveAurasDueToSpell(), Unit::SetHealthPercent(), Unit::SetPower(), SetSentErrorMessage(), SPELL_MOD_INTELLECT, SPELL_MOD_STAMINA, and TRIGGERED_OLD_TRIGGERED.
Referenced by HandleModifyAgilityCommand(), HandleModifyArcaneCommand(), HandleModifyArmorCommand(), HandleModifyBlockCommand(), HandleModifyDodgeCommand(), HandleModifyFireCommand(), HandleModifyFrostCommand(), HandleModifyHolyCommand(), HandleModifyIntellectCommand(), HandleModifyMeleeApCommand(), HandleModifyMeleeCritCommand(), HandleModifyMeleeHasteCommand(), HandleModifyNatureCommand(), HandleModifyParryCommand(), HandleModifyRangedApCommand(), HandleModifyRangedHasteCommand(), HandleModifyShadowCommand(), HandleModifySpellCritCommand(), HandleModifySpellHasteCommand(), HandleModifySpellPowerCommand(), HandleModifySpiritCommand(), HandleModifyStaminaCommand(), and HandleModifyStrengthCommand().
needReportToTarget()
bool ChatHandler::needReportToTarget (Player * chr) const protected virtual
Reimplemented in CliHandler.
Definition at line 3620 of file Chat.cpp.
References WorldSession::GetPlayer(), Player::IsVisibleGloballyFor(), and m_session.
Referenced by HandleCharacterLevel(), HandleDebugSpellModsCommand(), HandleExploreCheatCommand(), HandleGonameCommand(), HandleGroupgoCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyRageCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleNamegoCommand(), HandleRepairitemsCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleWaterwalkCommand(), and ModifyMountCommandHelper().
ParseCommands()
bool ChatHandler::ParseCommands (const char * text)
chat case (.command or !command format)
ignore single . and ! in line
ignore messages staring from many dots.
skip first . or ! (in console allowed use command with . and ! and without its)
Definition at line 1578 of file Chat.cpp.
References CONFIG_BOOL_PLAYER_COMMANDS, ExecuteCommand(), WorldSession::GetSecurity(), m_session, MANGOS_ASSERT, SEC_PLAYER, and sWorld.
Referenced by GMTicketMgr::HookGMTicketWhisper(), and World::ProcessCliCommands().
petLink()
std::string ChatHandler::petLink (std::string const & name) const inline protected
Definition at line 843 of file Chat.h.
References m_session.
Referenced by HandleLevelUpCommand().
playerLink()
std::string ChatHandler::playerLink (std::string const & name) const inline protected
Definition at line 844 of file Chat.h.
References m_session.
Referenced by GetNameLink(), HandleCharacterCustomizeCommand(), HandleCharacterLevelCommand(), HandleCharacterRenameCommand(), HandleGonameCommand(), HandleLevelUpCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandlePInfoCommand(), HandleResetSpecsCommand(), HandleResetTaxiNodesCommand(), HandleSendItemsCommand(), HandleSendMailCommand(), HandleSendMoneyCommand(), HandleTeleNameCommand(), and HandleUnmuteCommand().
PrepareStringNpcOrGoSpawnInformation()
template<typename T > template std::string ChatHandler::PrepareStringNpcOrGoSpawnInformation< GameObject > (uint32 guid) const protected
Definition at line 3731 of file Chat.cpp.
References GetMangosString(), LANG_NPC_GO_INFO_EVENT_STRING, LANG_NPC_GO_INFO_POOL_EVENT_STRING, LANG_NPC_GO_INFO_POOL_STRING, sGameEventMgr, and sPoolMgr.
PSendSysMessage() [1/2]
void ChatHandler::PSendSysMessage (const char * format, ...)
Definition at line 1268 of file Chat.cpp.
References SendSysMessage().
Referenced by BattleGroundQueue::AddGroup(), PlayerbotAI::AddQuest(), LootMgr::CheckDropStats(), instance_molten_core::ExecuteChatCommand(), instance_dark_portal::ExecuteChatCommand(), instance_mount_hyjal::ExecuteChatCommand(), instance_blood_furnace::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), ExtractAccountId(), ExtractLocationFromLink(), TimerManager::GetAIInformation(), CreatureEventAI::GetAIInformation(), npc_escortAI::GetAIInformation(), CombatActions::GetAIInformation(), ScriptedAI::GetAIInformation(), Scripted_NoMovementAI::GetAIInformation(), boss_thermapluggAI::GetAIInformation(), npc_highlord_darion_mograineAI::GetAIInformation(), mob_arugal_voidwalkerAI::GetAIInformation(), boss_brutallusAI::GetAIInformation(), boss_kiljaedenAI::GetAIInformation(), npc_arthasAI::GetAIInformation(), npc_anubisath_sentinelAI::GetAIInformation(), boss_illidan_stormrageAI::GetAIInformation(), npc_simon_game_bunnyAI::GetAIInformation(), npc_commanderAI::GetAIInformation(), boss_kaelthasAI::GetAIInformation(), GetDeletedCharacterInfoList(), HandleAccountCommand(), HandleAccountCreateCommand(), HandleAccountDeleteCommand(), HandleAccountLockCommand(), HandleAccountSetAddonCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleAddCharacterNoteCommand(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleAnticheatDebugExtrapCommand(), HandleAnticheatEnableCommand(), HandleAnticheatFingerprintAHistoryCommand(), HandleAnticheatFingerprintHistoryCommand(), HandleAnticheatInfoCommand(), HandleAnticheatSilenceCommand(), HandleAnticheatUnsilenceCommand(), WorldSession::HandleAreaTriggerOpcode(), HandleArenaDataReset(), HandleArenaTeamPointSet(), HandleAuctionItemCommand(), HandleAuraCommand(), HandleBanHelper(), HandleBanInfoCharacterCommand(), HandleBanInfoHelper(), HandleBanInfoIPCommand(), HandleBanListAccountCommand(), HandleBanListCharacterCommand(), HandleBanListHelper(), HandleBanListIPCommand(), HandleBattlegroundStartCommand(), HandleBattlegroundStopCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChannelListCommand(), HandleChannelStaticCommand(), HandleCharacterCustomizeCommand(), HandleCharacterDeletedListHelper(), HandleCharacterDeletedRestoreHelper(), HandleCharacterEraseCommand(), HandleCharacterLevelCommand(), HandleCharacterRenameCommand(), HandleCharacterTitlesCommand(), HandleCombatListCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleCooldownClearCommand(), HandleDebugAreaTriggersCommand(), HandleDebugGetItemStateCommand(), HandleDebugGetLootRecipientCommand(), HandleDebugGetValueByNameCommand(), HandleDebugHaveAtClientCommand(), HandleDebugIsVisibleCommand(), HandleDebugLootDropStats(), HandleDebugMoveflags(), HandleDebugMovement(), HandleDebugObjectFlags(), HandleDebugPetDismissSound(), HandleDebugPlayCinematicCommand(), HandleDebugPlayMovieCommand(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugSendOpcodeCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpawnsList(), HandleDebugSpellCoefsCommand(), HandleDebugSpellModsCommand(), HandleDebugTaxiCommand(), HandleDebugTransports(), HandleDebugWaypoint(), HandleEventInfoCommand(), HandleEventListCommand(), HandleEventStartCommand(), HandleEventStopCommand(), HandleExpansionRelease(), HandleExploreCheatCommand(), HandleGameObjectActivateCommand(), HandleGameObjectAddCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectForcedDespawnCommand(), HandleGameObjectMoveCommand(), HandleGameObjectNearCommand(), HandleGameObjectNearSpawnedCommand(), HandleGameObjectPhaseCommand(), HandleGameObjectRespawnCommand(), HandleGameObjectTargetCommand(), HandleGameObjectTurnCommand(), HandleGetDistanceCommand(), HandleGetLosCommand(), HandleGetValueHelper(), HandleGMFlyCommand(), HandleGMListFullCommand(), HandleGMListIngameCommand(), HandleGMVisibleCommand(), HandleGoGraveyardCommand(), HandleGoHelper(), HandleGonameCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), HandleGPSCommand(), HandleGridsLoadedCount(), HandleGroupgoCommand(), HandleGUIDCommand(), HandleInstanceListBindsCommand(), HandleInstanceSaveDataCommand(), HandleInstanceStatsCommand(), HandleInstanceUnbindCommand(), HandleKickPlayerCommand(), HandleLearnAllDefaultCommand(), HandleLearnAllGMCommand(), HandleLearnAllRecipesCommand(), HandleLearnCommand(), HandleLevelUpCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkGraveCommand(), HandleLinkRemoveCommand(), HandleListAreaTriggerCommand(), HandleListAurasCommand(), HandleListCreatureCommand(), HandleListItemCommand(), HandleListObjectCommand(), HandleListTalentsCommand(), HandleLookupCreatureCommand(), HandleLookupEventCommand(), HandleLookupItemSetCommand(), HandleLookupObjectCommand(), HandleLookupSkillCommand(), HandleLookupTaxiNodeCommand(), HandleLookupTeleCommand(), HandleLookupTitleCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleMessagechatOpcode(), HandleMmap(), HandleMmapLoadedTilesCommand(), HandleMmapLocCommand(), HandleMmapPathCommand(), HandleMmapStatsCommand(), HandleMmapTestArea(), HandleMmapTestHeight(), HandleModifyArenaCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFactionCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleMovegensCommand(), HandleMovespeedShowCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleNearGraveCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcAIInfoCommand(), HandleNpcDelVendorItemCommand(), HandleNpcFactionIdCommand(), HandleNpcFollowCommand(), HandleNpcFormationInfoCommand(), HandleNpcFormationSwitchCommand(), HandleNpcGroupInfoCommand(), HandleNpcInfoCommand(), HandleNpcListSpells(), HandleNpcMoveCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcShowLootCommand(), HandleNpcSpawnDistCommand(), HandleNpcSpawnTimeCommand(), HandleNpcTameCommand(), HandleNpcThreatCommand(), HandleNpcUnFollowCommand(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandlePInfoCommand(), HandlePoolInfoCommand(), HandlePoolListCommand(), HandlePoolSpawnsCommand(), HandlePrintMovement(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandlerDebugModValueHelper(), HandleRecallCommand(), HandleRepairitemsCommand(), HandleResetAllCommand(), HandleResetModsCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleScourgeInvasionBattlesWonCommand(), HandleScourgeInvasionStartZone(), HandleScourgeInvasionStateCommand(), HandleSD2HelpCommand(), HandleSD2ScriptCommand(), HandleSendItemsCommand(), HandleSendItemsHelper(), HandleSendMailCommand(), HandleSendMassItemsCommand(), HandleSendMassMailCommand(), HandleSendMassMoneyCommand(), HandleSendMessageCommand(), HandleSendMoneyCommand(), HandleServerInfoCommand(), HandleServerLogFilterCommand(), HandleServerLogLevelCommand(), HandleServerMotdCommand(), HandleServerPLimitCommand(), HandleServerResetAllRaidCommand(), HandleServerSetMotdCommand(), HandleSetSkillCommand(), HandleSetValueHelper(), HandleSetViewCommand(), HandleShowGearScoreCommand(), HandleShowTemporarySpawnList(), HandleSunsReachReclamationCounterCommand(), HandleSunsReachReclamationPhaseCommand(), HandleSunsReachReclamationSubPhaseCommand(), HandleSunwellGateCommand(), HandleSunwellGateCounterCommand(), HandleTaxiCheatCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTicketGoCommand(), HandleTicketGoNameCommand(), HandleTicketMgrCommandResult(), HandleTicketsListCommand(), HandleTicketSortCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleTriggerCommand(), HandleUnBanHelper(), HandleUnmuteCommand(), HandleVariablePrint(), HandleWarEffortCommand(), HandleWarEffortCounterCommand(), HandleWarEffortPhaseCommand(), HandleWarnCharacterCommand(), HandleWaterwalkCommand(), HandleWhisperRestrictionCommand(), HandleWhispersCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), HandleWpShowCommand(), SpellMgr::IsSpellValid(), ObjectMgr::IsVendorItemValid(), LookupPlayerSearchCommand(), ModifyMountCommandHelper(), ModifyStatCommandHelper(), Player::OnGossipSelect(), Player::OnTaxiFlightRouteProgress(), Player::OnTaxiFlightRouteStart(), Player::PrepareGossipMenu(), GMTicketMgr::Print(), WorldObject::PrintCooldownList(), Loot::PrintLootList(), NamreebAnticheat::SessionAnticheat::SendCheatInfo(), NamreebAnticheat::Movement::SendOrderInfo(), NamreebAnticheat::SessionAnticheat::SendPlayerInfo(), WardenWin::SendPlayerInfo(), ShowAccountListHelper(), ShowAllUpdateFieldsHelper(), ShowHelpForSubCommands(), ShowItemListHelper(), GMTicketMgr::ShowMOTD(), ShowNpcOrGoSpawnInformation(), ShowPlayerListHelper(), ShowPoolListHelper(), ShowQuestListHelper(), ShowTriggerListHelper(), ShowTriggerTargetListHelper(), and ShowUpdateFieldHelper().
PSendSysMessage() [2/2]
void ChatHandler::PSendSysMessage (int32 entry, ...)
Definition at line 1257 of file Chat.cpp.
References GetMangosString(), and SendSysMessage().
SendGlobalSysMessage()
void ChatHandler::SendGlobalSysMessage (const char * str) const protected
Definition at line 1233 of file Chat.cpp.
References BuildChatPacket(), CHAT_MSG_SYSTEM, Object::GetObjectGuid(), WorldSession::GetPlayer(), LineFromMessage(), m_session, mangos_strdup(), and sWorld.
Referenced by HandleReloadAchievementCriteriaRequirementCommand(), HandleReloadAchievementRewardCommand(), HandleReloadAllLootCommand(), HandleReloadAllQuestCommand(), HandleReloadAllScriptsCommand(), HandleReloadAreaTriggerTavernCommand(), HandleReloadAreaTriggerTeleportCommand(), HandleReloadBattleEventCommand(), HandleReloadCommandCommand(), HandleReloadConditionsCommand(), HandleReloadConfigCommand(), HandleReloadCreatureCooldownsCommand(), HandleReloadCreatureQuestInvRelationsCommand(), HandleReloadCreatureQuestRelationsCommand(), HandleReloadCreatureSpellLists(), HandleReloadCreaturesStatsCommand(), HandleReloadDBScriptsOnCreatureDeathCommand(), HandleReloadDBScriptsOnEventCommand(), HandleReloadDBScriptsOnGossipCommand(), HandleReloadDBScriptsOnGoUseCommand(), HandleReloadDBScriptsOnQuestEndCommand(), HandleReloadDBScriptsOnQuestStartCommand(), HandleReloadDBScriptsOnRelayCommand(), HandleReloadDBScriptsOnSpellCommand(), HandleReloadEventAIScriptsCommand(), HandleReloadEventAISummonsCommand(), HandleReloadExpectedSpamRecords(), HandleReloadGameGraveyardZoneCommand(), HandleReloadGameTeleCommand(), HandleReloadGOQuestInvRelationsCommand(), HandleReloadGOQuestRelationsCommand(), HandleReloadGossipMenuCommand(), HandleReloadItemConvertCommand(), HandleReloadItemEnchantementsCommand(), HandleReloadItemRequiredTragetCommand(), HandleReloadLocalesAchievementRewardCommand(), HandleReloadLocalesCreatureCommand(), HandleReloadLocalesGameobjectCommand(), HandleReloadLocalesGossipMenuOptionCommand(), HandleReloadLocalesItemCommand(), HandleReloadLocalesNpcTextCommand(), HandleReloadLocalesPageTextCommand(), HandleReloadLocalesPointsOfInterestCommand(), HandleReloadLocalesQuestCommand(), HandleReloadLocalesTrainerGreetingCommand(), HandleReloadLootTemplatesCreatureCommand(), HandleReloadLootTemplatesDisenchantCommand(), HandleReloadLootTemplatesFishingCommand(), HandleReloadLootTemplatesGameobjectCommand(), HandleReloadLootTemplatesItemCommand(), HandleReloadLootTemplatesMailCommand(), HandleReloadLootTemplatesMillingCommand(), HandleReloadLootTemplatesPickpocketingCommand(), HandleReloadLootTemplatesProspectingCommand(), HandleReloadLootTemplatesReferenceCommand(), HandleReloadLootTemplatesSkinningCommand(), HandleReloadLootTemplatesSpellCommand(), HandleReloadMailLevelRewardCommand(), HandleReloadMangosStringCommand(), HandleReloadNpcGossipCommand(), HandleReloadNpcTextCommand(), HandleReloadNpcTrainerCommand(), HandleReloadNpcVendorCommand(), HandleReloadPageTextsCommand(), HandleReloadPointsOfInterestCommand(), HandleReloadQuestAreaTriggersCommand(), HandleReloadQuestgiverGreetingCommand(), HandleReloadQuestgiverGreetingLocalesCommand(), HandleReloadQuestPOICommand(), HandleReloadQuestTemplateCommand(), HandleReloadReputationRewardRateCommand(), HandleReloadReputationSpilloverTemplateCommand(), HandleReloadReservedNameCommand(), HandleReloadSkillDiscoveryTemplateCommand(), HandleReloadSkillExtraItemTemplateCommand(), HandleReloadSkillFishingBaseLevelCommand(), HandleReloadSpawnGroupsCommand(), HandleReloadSpellAreaCommand(), HandleReloadSpellBonusesCommand(), HandleReloadSpellChainCommand(), HandleReloadSpellClickSpellsCommand(), HandleReloadSpellElixirCommand(), HandleReloadSpellLearnSpellCommand(), HandleReloadSpellPetAurasCommand(), HandleReloadSpellProcEventCommand(), HandleReloadSpellProcItemEnchantCommand(), HandleReloadSpellScriptTargetCommand(), HandleReloadSpellTargetPositionCommand(), HandleReloadSpellThreatsCommand(), HandleReloadStringIds(), HandleReloadTaxiShortcuts(), and HandleReloadTrainerGreetingCommand().
SendSysMessage() [1/2]
void ChatHandler::SendSysMessage (const char * str) virtual
Reimplemented in CliHandler.
Definition at line 1216 of file Chat.cpp.
References BuildChatPacket(), CHAT_MSG_SYSTEM, LineFromMessage(), m_session, mangos_strdup(), and WorldSession::SendPacket().
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandGM(), PlayerbotAI::_HandleCommandHelp(), PlayerbotAI::_HandleCommandMail(), PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandQuest(), PlayerbotAI::_HandleCommandSpells(), PlayerbotAI::_HandleCommandStats(), Player::_SaveInventory(), ExecuteCommand(), ExtractPlayerTarget(), HandleAccountCreateCommand(), HandleAccountLockCommand(), HandleAccountPasswordCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), HandleAchievementCommand(), HandleAnticheatBlacklistCommand(), HandleAnticheatCheatinformCommand(), HandleAnticheatDebugExtrapCommand(), HandleAnticheatSpaminfoCommand(), HandleAnticheatSpaminformCommand(), HandleArenaDataReset(), HandleAuraCommand(), HandleBanHelper(), HandleBanListHelper(), HandleBanListIPCommand(), HandleBattlegroundStartCommand(), HandleBattlegroundStopCommand(), WorldSession::HandleCancelMountAuraOpcode(), HandleCastBackCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChangeWeatherCommand(), HandleCharacterDeletedDeleteCommand(), HandleCharacterDeletedListCommand(), HandleCharacterDeletedListHelper(), HandleCharacterDeletedRestoreCommand(), HandleCombatListCommand(), HandleComeToMeCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleCooldownClearCommand(), HandleCooldownListCommand(), HandleDamageCommand(), HandleDebugGetItemStateCommand(), HandleDebugGetLootRecipientCommand(), HandleDebugGetValueByIndexCommand(), HandleDebugGetValueByNameCommand(), HandleDebugHaveAtClientCommand(), HandleDebugIncPacketHistory(), HandleDebugIsVisibleCommand(), HandleDebugListUpdateFieldsCommand(), HandleDebugLootDropStats(), HandleDebugModValueCommand(), HandleDebugMovement(), HandleDebugObjectFlags(), HandleDebugOutPacketHistory(), HandleDebugPlaySoundCommand(), HandleDebugSendLargePacketCommand(), HandleDebugSendPoiCommand(), HandleDebugSetAuraStateCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpellModsCommand(), HandleDebugTransports(), HandleDieCommand(), HandleDismountCommand(), HandleEventInfoCommand(), HandleEventListCommand(), HandleEventStartCommand(), HandleEventStopCommand(), HandleExpansionRelease(), HandleExploreCheatCommand(), HandleGameObjectAddCommand(), HandleGameObjectNearCommand(), HandleGameObjectPhaseCommand(), HandleGameObjectTargetCommand(), HandleGetDistanceCommand(), HandleGetLosCommand(), HandleGMChatCommand(), HandleGMCommand(), HandleGMFlyCommand(), HandleGMListFullCommand(), HandleGMListIngameCommand(), HandleGMMountUpCommand(), HandleGMVisibleCommand(), HandleGoCreatureCommand(), HandleGonameCommand(), HandleGoObjectCommand(), HandleGPSCommand(), HandleGroupgoCommand(), HandleGUIDCommand(), HandleGuildCreateCommand(), HandleHelpCommand(), HandleHideAreaCommand(), HandleHonorAddCommand(), HandleHonorAddKillCommand(), HandleHonorUpdateCommand(), HandleKickPlayerCommand(), HandleLearnAllCommand(), HandleLearnAllCraftsCommand(), HandleLearnAllGMCommand(), HandleLearnAllLangCommand(), HandleLearnAllMyPetTalentsCommand(), HandleLearnAllMySpellsCommand(), HandleLearnAllMyTalentsCommand(), HandleLearnAllRecipesCommand(), HandleLearnCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkEditCommand(), HandleLinkRemoveCommand(), HandleLinkToggleCommand(), HandleListAreaTriggerCommand(), HandleListAurasCommand(), HandleListItemCommand(), HandleListTalentsCommand(), HandleLookupAchievementCommand(), HandleLookupAreaCommand(), HandleLookupCreatureCommand(), HandleLookupEventCommand(), HandleLookupFactionCommand(), HandleLookupItemCommand(), HandleLookupItemSetCommand(), HandleLookupObjectCommand(), HandleLookupPoolCommand(), HandleLookupQuestCommand(), HandleLookupSkillCommand(), HandleLookupSpellCommand(), HandleLookupTaxiNodeCommand(), HandleLookupTeleCommand(), HandleLookupTitleCommand(), HandleMaxSkillCommand(), HandleMmap(), HandleModifyArenaCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFactionCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyMorphCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleModifyTalentCommand(), HandleMovegensCommand(), HandleMovespeedShowCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcAIInfoCommand(), HandleNpcAllowMovementCommand(), HandleNpcChangeEntryCommand(), HandleNpcChangeLevelCommand(), HandleNpcDeleteCommand(), HandleNpcDelVendorItemCommand(), HandleNpcEvade(), HandleNpcFactionIdCommand(), HandleNpcFlagCommand(), HandleNpcFormationInfoCommand(), HandleNpcFormationResetCommand(), HandleNpcFormationSwitchCommand(), HandleNpcGroupInfoCommand(), HandleNpcInfoCommand(), HandleNpcPlayEmoteCommand(), HandleNpcSayCommand(), HandleNpcSetModelCommand(), HandleNpcSetPhaseCommand(), HandleNpcShowLootCommand(), HandleNpcSpawnDistCommand(), HandleNpcTameCommand(), HandleNpcTempSpawn(), HandleNpcTextEmoteCommand(), HandleNpcThreatCommand(), HandleNpcYellCommand(), HandlePDumpWriteCommand(), HandlePoolInfoCommand(), HandlePrintMovement(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandleQuitCommand(), HandleReloadAnticheatCommand(), HandleResetAllCommand(), HandleResetSpecsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleRespawnCommand(), HandleSaveAllCommand(), HandleSaveCommand(), HandleSendMessageCommand(), HandleServerExitCommand(), HandleServerInfoCommand(), HandleServerLogFilterCommand(), HandleSetSkillCommand(), HandleShowAreaCommand(), HandleShowTemporarySpawnList(), HandleStartCommand(), HandleTaxiCheatCommand(), HandleTeleAddCommand(), HandleTeleCommand(), HandleTeleDelCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTicketsCommand(), HandleTicketsQueueCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleTriggerActiveCommand(), HandleTriggerCommand(), HandleTriggerNearCommand(), HandleUnAuraCommand(), HandleUnBanHelper(), HandleUnLearnCommand(), HandleUnmuteCommand(), HandleWaterwalkCommand(), HandleWhisperRestrictionCommand(), HandleWhispersCommand(), HandleWpModifyCommand(), HasLowerSecurity(), HasLowerSecurityAccount(), ObjectMgr::IsVendorItemValid(), ModifyMountCommandHelper(), GMTicketMgr::Print(), Loot::PrintLootList(), PSendSysMessage(), NamreebAnticheat::SessionAnticheat::SendCheatInfo(), PlayerbotAI::SendNotEquipList(), WardenWin::SendPlayerInfo(), NamreebAnticheat::SessionAnticheat::SendSpamInfo(), SendSysMessage(), ShowAccountListHelper(), ShowAchievementCriteriaListHelper(), ShowAchievementListHelper(), instance_molten_core::ShowChatCommands(), instance_sunwell_plateau::ShowChatCommands(), instance_zulaman::ShowChatCommands(), instance_dark_portal::ShowChatCommands(), instance_mount_hyjal::ShowChatCommands(), instance_trial_of_the_crusader::ShowChatCommands(), instance_icecrown_citadel::ShowChatCommands(), instance_halls_of_stone::ShowChatCommands(), instance_violet_hold::ShowChatCommands(), instance_serpentshrine_cavern::ShowChatCommands(), instance_blood_furnace::ShowChatCommands(), instance_mechanar::ShowChatCommands(), world_map_outland::ShowChatCommands(), ShowFactionListHelper(), ShowHelpForCommand(), ShowHelpForSubCommands(), ShowPlayerListHelper(), ShowSpellListHelper(), ShowUpdateFieldHelper(), PlayerbotChatHandler::sysmessage(), and Player::Whisper().
SendSysMessage() [2/2]
void ChatHandler::SendSysMessage (int32 entry)
Definition at line 1252 of file Chat.cpp.
References GetMangosString(), and SendSysMessage().
SetDataForCommandInTable()
bool ChatHandler::SetDataForCommandInTable (ChatCommand * commandTable, const char * text, uint32 security, std::string const & help) protected
Function find appropriate command and update command security level and help text.
Parameters
commandTable Table for first level command search
text Command line string that will parsed for (sub)command search
security New security level for command
help New help text for command
Returns
true if command has been found, and false in other case
All problems found while command search and updated output as to DB errors log
Definition at line 1538 of file Chat.cpp.
References CHAT_COMMAND_OK, CHAT_COMMAND_UNKNOWN, CHAT_COMMAND_UNKNOWN_SUBCOMMAND, DETAIL_LOG, FindCommand(), ChatCommand::Help, ChatCommand::SecurityLevel, and sLog.
Referenced by getCommandTable().
SetSentErrorMessage()
void ChatHandler::SetSentErrorMessage (bool val) inline protected
Definition at line 902 of file Chat.h.
References sentErrorMessage.
Referenced by ExecuteCommand(), ExtractAccountId(), ExtractLocationFromLink(), ExtractPlayerTarget(), GetDeletedCharacterInfoList(), HandleAccountCreateCommand(), HandleAccountDeleteCommand(), HandleAccountLockCommand(), HandleAccountPasswordCommand(), HandleAccountSetGmLevelCommand(), HandleAccountSetPasswordCommand(), HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), HandleAchievementCriteriaRemoveCommand(), HandleAchievementRemoveCommand(), HandleAddCharacterNoteCommand(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleArenaTeamPointSet(), HandleAuctionItemCommand(), HandleAuraCommand(), HandleBanHelper(), HandleBattlegroundStartCommand(), HandleBattlegroundStopCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChangeWeatherCommand(), HandleChannelStaticCommand(), HandleComeToMeCommand(), HandleCooldownClearArenaCommand(), HandleCooldownClearClientSideCommand(), HandleCooldownClearCommand(), HandleCooldownListCommand(), HandleDamageCommand(), HandleDebugGetValueByIndexCommand(), HandleDebugGetValueByNameCommand(), HandleDebugListUpdateFieldsCommand(), HandleDebugLootDropStats(), HandleDebugModValueCommand(), HandleDebugMovement(), HandleDebugPlayCinematicCommand(), HandleDebugPlayMovieCommand(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugSetAuraStateCommand(), HandleDebugSetValueByIndexCommand(), HandleDebugSetValueByNameCommand(), HandleDebugSpellModsCommand(), HandleDieCommand(), HandleDismountCommand(), HandleEventInfoCommand(), HandleEventStartCommand(), HandleEventStopCommand(), HandleExploreCheatCommand(), HandleGameObjectActivateCommand(), HandleGameObjectAddCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectForcedDespawnCommand(), HandleGameObjectMoveCommand(), HandleGameObjectPhaseCommand(), HandleGameObjectRespawnCommand(), HandleGameObjectTurnCommand(), HandleGetDistanceCommand(), HandleGMChatCommand(), HandleGMCommand(), HandleGMFlyCommand(), HandleGMMountUpCommand(), HandleGMVisibleCommand(), HandleGoCreatureCommand(), HandleGoGraveyardCommand(), HandleGoHelper(), HandleGonameCommand(), HandleGoObjectCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), HandleGPSCommand(), HandleGroupgoCommand(), HandleGUIDCommand(), HandleGuildCreateCommand(), HandleHideAreaCommand(), HandleHonorAddCommand(), HandleHonorAddKillCommand(), HandleHonorUpdateCommand(), HandleInstanceSaveDataCommand(), HandleKickPlayerCommand(), HandleLearnAllCommand(), HandleLearnAllMyPetTalentsCommand(), HandleLearnCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkEditCommand(), HandleLinkGraveCommand(), HandleLinkRemoveCommand(), HandleLinkToggleCommand(), HandleListAurasCommand(), HandleListCreatureCommand(), HandleListItemCommand(), HandleListObjectCommand(), HandleListTalentsCommand(), HandleLookupTeleCommand(), HandleMaxSkillCommand(), HandleModifyArenaCommand(), HandleModifyASpeedCommand(), HandleModifyBWalkCommand(), HandleModifyEnergyCommand(), HandleModifyFactionCommand(), HandleModifyFlyCommand(), HandleModifyGenderCommand(), HandleModifyHonorCommand(), HandleModifyHPCommand(), HandleModifyManaCommand(), HandleModifyMoneyCommand(), HandleModifyMorphCommand(), HandleModifyRageCommand(), HandleModifyRepCommand(), HandleModifyRunicPowerCommand(), HandleModifyScaleCommand(), HandleModifySpeedCommand(), HandleModifySwimCommand(), HandleModifyTalentCommand(), HandleMovegensCommand(), HandleMovespeedShowCommand(), HandleNamegoCommand(), HandleNearGraveCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcAIInfoCommand(), HandleNpcChangeEntryCommand(), HandleNpcChangeLevelCommand(), HandleNpcDeleteCommand(), HandleNpcDelVendorItemCommand(), HandleNpcEvade(), HandleNpcFactionIdCommand(), HandleNpcFlagCommand(), HandleNpcFollowCommand(), HandleNpcFormationInfoCommand(), HandleNpcFormationResetCommand(), HandleNpcFormationSwitchCommand(), HandleNpcGroupInfoCommand(), HandleNpcInfoCommand(), HandleNpcMoveCommand(), HandleNpcPlayEmoteCommand(), HandleNpcSayCommand(), HandleNpcSetModelCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcSetPhaseCommand(), HandleNpcShowLootCommand(), HandleNpcSpawnDistCommand(), HandleNpcSpawnTimeCommand(), HandleNpcTameCommand(), HandleNpcTempSpawn(), HandleNpcTextEmoteCommand(), HandleNpcThreatCommand(), HandleNpcUnFollowCommand(), HandleNpcYellCommand(), HandlePDumpLoadCommand(), HandlePDumpWriteCommand(), HandlePoolListCommand(), HandlePoolSpawnsCommand(), HandlePrintMovement(), HandleQuestAddCommand(), HandleQuestCompleteCommand(), HandleQuestRemoveCommand(), HandleRecallCommand(), HandleResetAllCommand(), HandleResetModsCommand(), HandleResetSpecsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleRespawnCommand(), HandleSendItemsHelper(), HandleSendMessageCommand(), HandleServerLogFilterCommand(), HandleSetSkillCommand(), HandleSetViewCommand(), HandleShowAreaCommand(), HandleShowGearScoreCommand(), HandleStartCommand(), HandleTaxiCheatCommand(), HandleTeleAddCommand(), HandleTeleCommand(), HandleTeleDelCommand(), HandleTeleGroupCommand(), HandleTeleNameCommand(), HandleTicketDiscardCommand(), HandleTicketEscalateCommand(), HandleTicketGoCommand(), HandleTicketGoNameCommand(), HandleTicketNoteCommand(), HandleTicketReadCommand(), HandleTicketResolveCommand(), HandleTicketsCommand(), HandleTicketsListCommand(), HandleTicketSortCommand(), HandleTicketsQueueCommand(), HandleTicketWhisperCommand(), HandleTitlesAddCommand(), HandleTitlesCurrentCommand(), HandleTitlesRemoveCommand(), HandleTitlesSetMaskCommand(), HandleTriggerCommand(), HandleUnAuraCommand(), HandleUnBanHelper(), HandleUnLearnCommand(), HandleUnmuteCommand(), HandleWarnCharacterCommand(), HandleWaterwalkCommand(), HandleWhisperRestrictionCommand(), HandleWhispersCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), HandleWpShowCommand(), HasLowerSecurity(), HasLowerSecurityAccount(), LookupPlayerSearchCommand(), ModifyMountCommandHelper(), ModifyStatCommandHelper(), and ShowPlayerListHelper().
ShowAccountListHelper()
bool ChatHandler::ShowAccountListHelper (QueryResult * result, uint32 * limit = nullptr, bool title = true, bool error = true) protected
Display the list of account/characters online
Circle through accounts
Definition at line 4383 of file Level2.cpp.
References QueryResult::Fetch(), WorldObject::GetName(), WorldSession::GetPlayer(), Field::GetUInt32(), LANG_ACCOUNT_LIST_BAR, LANG_ACCOUNT_LIST_EMPTY, LANG_ACCOUNT_LIST_HEADER, LANG_ACCOUNT_LIST_LINE_CHAT, LANG_ACCOUNT_LIST_LINE_CONSOLE, m_session, QueryResult::NextRow(), PSendSysMessage(), SendSysMessage(), and sWorld.
Referenced by HandleAccountOnlineListCommand(), HandleLookupAccountEmailCommand(), HandleLookupAccountIpCommand(), and HandleLookupAccountNameCommand().
ShowAchievementCriteriaListHelper()
void ChatHandler::ShowAchievementCriteriaListHelper (AchievementCriteriaEntry const * criEntry, AchievementEntry const * achEntry, LocaleConstant loc, Player * target = nullptr) protected
Definition at line 1252 of file Level3.cpp.
References ACHIEVEMENT_FLAG_COUNTER, AchievementEntry::flags, Player::GetAchievementMgr(), AchievementMgr::GetCriteriaProgressCounter(), AchievementMgr::GetCriteriaProgressMaxCounter(), GetMangosString(), AchievementCriteriaEntry::ID, AchievementMgr::IsCompletedCriteria(), LANG_COMPLETE, LANG_COUNTER, localeNames, m_session, AchievementCriteriaEntry::name, and SendSysMessage().
Referenced by HandleAchievementCommand(), HandleAchievementCriteriaAddCommand(), and HandleAchievementCriteriaRemoveCommand().
ShowAchievementListHelper()
void ChatHandler::ShowAchievementListHelper (AchievementEntry const * achEntry, LocaleConstant loc, time_t const * date = nullptr, Player * target = nullptr) protected
Definition at line 1432 of file Level2.cpp.
References Player::GetAchievementMgr(), Object::GetObjectGuid(), ObjectGuid::GetRawValue(), AchievementEntry::ID, localeNames, m_session, AchievementEntry::name, sAchievementMgr, SendSysMessage(), and TimeToTimestampStr().
Referenced by HandleAchievementAddCommand(), HandleAchievementCommand(), HandleAchievementRemoveCommand(), HandleCharacterAchievementsCommand(), and HandleLookupAchievementCommand().
ShowAllUpdateFieldsHelper()
void ChatHandler::ShowAllUpdateFieldsHelper (Object const * target) protected
Definition at line 1229 of file debugcmds.cpp.
References Object::GetGuidStr(), Object::GetUInt32Value(), Object::GetValuesCount(), PSendSysMessage(), and ShowUpdateFieldHelper().
Referenced by HandleDebugListUpdateFieldsCommand().
ShowFactionListHelper()
void ChatHandler::ShowFactionListHelper (FactionEntry const * factionEntry, LocaleConstant loc, FactionState const * repState = nullptr, Player * target = nullptr) protected
Definition at line 1563 of file Level2.cpp.
References FACTION_FLAG_AT_WAR, FACTION_FLAG_HIDDEN, FACTION_FLAG_INACTIVE, FACTION_FLAG_INVISIBLE_FORCED, FACTION_FLAG_PEACE_FORCED, FACTION_FLAG_VISIBLE, FactionState::Flags, GetMangosString(), ReputationMgr::GetRank(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), FactionEntry::ID, LANG_FACTION_ATWAR, LANG_FACTION_HIDDEN, LANG_FACTION_INACTIVE, LANG_FACTION_INVISIBLE_FORCED, LANG_FACTION_NOREPUTATION, LANG_FACTION_PEACE_FORCED, LANG_FACTION_VISIBLE, localeNames, m_session, FactionEntry::name, ReputationRankStrIndex, and SendSysMessage().
Referenced by HandleCharacterReputationCommand(), and HandleLookupFactionCommand().
ShowHelpForCommand()
bool ChatHandler::ShowHelpForCommand (ChatCommand * table, const char * cmd) protected
Definition at line 1646 of file Chat.cpp.
References CHAT_COMMAND_OK, CHAT_COMMAND_UNKNOWN, CHAT_COMMAND_UNKNOWN_SUBCOMMAND, ChatCommand::ChildCommands, FindCommand(), getCommandTable(), ChatCommand::Help, LANG_NO_HELP_CMD, ChatCommand::Name, SendSysMessage(), and ShowHelpForSubCommands().
Referenced by ExecuteCommand(), HandleCommandsCommand(), and HandleHelpCommand().
ShowHelpForSubCommands()
bool ChatHandler::ShowHelpForSubCommands (ChatCommand * table, char const * cmd) protected
Definition at line 1610 of file Chat.cpp.
References getCommandTable(), isAvailable(), LANG_AVIABLE_CMD, LANG_SUBCMDS_LIST, m_session, ChatCommand::Name, PSendSysMessage(), and SendSysMessage().
Referenced by ExecuteCommand(), and ShowHelpForCommand().
ShowItemListHelper()
void ChatHandler::ShowItemListHelper (uint32 itemId, int loc_idx, Player * target = nullptr) protected
Definition at line 2920 of file Level3.cpp.
References Player::CanUseItem(), GetMangosString(), ItemPrototype::ItemId, LANG_COMMAND_ITEM_USABLE, LANG_ITEM_LIST_CHAT, LANG_ITEM_LIST_CONSOLE, SQLStorage::LookupEntry(), m_session, ItemPrototype::Name1, PSendSysMessage(), sItemStorage, and sObjectMgr.
Referenced by HandleLookupItemCommand(), and HandleTriggerCommand().
ShowNpcOrGoSpawnInformation()
template<typename T > template void ChatHandler::ShowNpcOrGoSpawnInformation< GameObject > (uint32 guid) protected
Definition at line 3689 of file Chat.cpp.
References GameEventData::description, PoolTemplateData::description, LANG_NPC_GO_INFO_GAME_EVENT_D, LANG_NPC_GO_INFO_GAME_EVENT_S, LANG_NPC_GO_INFO_POOL, LANG_NPC_GO_INFO_POOL_GAME_EVENT_D, LANG_NPC_GO_INFO_POOL_GAME_EVENT_S, LANG_NPC_GO_INFO_TOP_POOL, PSendSysMessage(), sGameEventMgr, and sPoolMgr.
ShowPlayerListHelper()
bool ChatHandler::ShowPlayerListHelper (QueryResult * result, uint32 * limit = nullptr, bool title = true, bool error = true) protected
Circle through them. Display username and GM level
Definition at line 6843 of file Level3.cpp.
References QueryResult::Fetch(), Field::GetCppString(), GetSessionDbcLocale(), Field::GetUInt32(), Field::GetUInt8(), LANG_CHARACTERS_LIST_BAR, LANG_CHARACTERS_LIST_HEADER, LANG_CHARACTERS_LIST_LINE_CHAT, LANG_CHARACTERS_LIST_LINE_CONSOLE, LANG_NO_PLAYERS_FOUND, m_session, ChrClassesEntry::name, ChrRacesEntry::name, QueryResult::NextRow(), PSendSysMessage(), sChrClassesStore, sChrRacesStore, SendSysMessage(), and SetSentErrorMessage().
Referenced by HandleAccountCharactersCommand(), and LookupPlayerSearchCommand().
ShowPoolListHelper()
void ChatHandler::ShowPoolListHelper (uint16 pool_id) protected
Definition at line 4544 of file Level2.cpp.
References PoolTemplateData::AutoSpawn, PoolTemplateData::description, LANG_POOL_ENTRY_LIST_CHAT, LANG_POOL_ENTRY_LIST_CONSOLE, m_session, PoolTemplateData::MaxLimit, PSendSysMessage(), and sPoolMgr.
Referenced by HandleLookupPoolCommand(), and HandlePoolListCommand().
ShowQuestListHelper()
void ChatHandler::ShowQuestListHelper (uint32 questId, int32 loc_idx, Player * target = nullptr) protected
Definition at line 3229 of file Level3.cpp.
References GetMangosString(), Quest::GetQuestId(), Quest::GetQuestLevel(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Quest::GetTitle(), LANG_COMMAND_QUEST_ACTIVE, LANG_COMMAND_QUEST_COMPLETE, LANG_COMMAND_QUEST_REWARDED, LANG_QUEST_LIST_CHAT, LANG_QUEST_LIST_CONSOLE, m_session, PSendSysMessage(), QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, and sObjectMgr.
Referenced by HandleLookupQuestCommand(), and HandleTriggerCommand().
ShowSpellListHelper()
void ChatHandler::ShowSpellListHelper (Player * target, SpellEntry const * spellInfo, LocaleConstant loc) protected
Definition at line 3123 of file Level3.cpp.
References SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectTriggerSpell, GetMangosString(), GetTalentSpellCost(), Unit::HasAura(), Player::HasSpell(), SpellEntry::Id, IsPassiveSpell(), LANG_ACTIVE, LANG_KNOWN, LANG_LEARN, LANG_PASSIVE, LANG_SPELL_RANK, LANG_TALENT, localeNames, m_session, SendSysMessage(), SPELL_EFFECT_LEARN_SPELL, SpellEntry::SpellName, and sSpellMgr.
Referenced by HandleListTalentsCommand(), and HandleLookupSpellCommand().
ShowTriggerListHelper()
void ChatHandler::ShowTriggerListHelper (AreaTriggerEntry const * atEntry) protected
Definition at line 191 of file Level2.cpp.
References WorldObject::GetDistance2d(), GetMangosString(), WorldSession::GetPlayer(), AreaTriggerEntry::id, LANG_TRIGGER_DIST, LANG_TRIGGER_LIST_CHAT, LANG_TRIGGER_LIST_CONSOLE, LANG_TRIGGER_QUEST, LANG_TRIGGER_TAVERN, m_session, AreaTriggerEntry::mapid, PSendSysMessage(), ShowTriggerTargetListHelper(), sObjectMgr, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by HandleListAreaTriggerCommand(), HandleTriggerActiveCommand(), HandleTriggerCommand(), and HandleTriggerNearCommand().
ShowTriggerTargetListHelper()
void ChatHandler::ShowTriggerTargetListHelper (uint32 id, AreaTrigger const * at, bool subpart = false) protected
Definition at line 170 of file Level2.cpp.
References WorldObject::GetDistance2d(), GetMangosString(), WorldSession::GetPlayer(), LANG_TRIGGER_DIST, LANG_TRIGGER_TARGET_LIST_CHAT, LANG_TRIGGER_TARGET_LIST_CONSOLE, m_session, PSendSysMessage(), AreaTrigger::target_mapId, AreaTrigger::target_X, AreaTrigger::target_Y, and AreaTrigger::target_Z.
Referenced by HandleTriggerNearCommand(), and ShowTriggerListHelper().
ShowUpdateFieldHelper()
void ChatHandler::ShowUpdateFieldHelper (Object const * target, uint16 index) protected
Definition at line 1242 of file debugcmds.cpp.
References Object::GetByteValue(), Object::GetFloatValue(), Object::GetGuidValue(), ObjectGuid::GetString(), Object::GetTypeMask(), Object::GetUInt16Value(), Object::GetUInt32Value(), UpdateFields::GetUpdateFieldDataByTypeMaskAndOffset(), PSendSysMessage(), SendSysMessage(), UF_TYPE_BYTES, UF_TYPE_BYTES2, UF_TYPE_FLOAT, UF_TYPE_GUID, UF_TYPE_INT, and UF_TYPE_TWO_SHORT.
Referenced by HandleDebugGetValueByNameCommand(), and ShowAllUpdateFieldsHelper().
SkipWhiteSpaces()
void ChatHandler::SkipWhiteSpaces (char ** args) static
Function skip all whitespaces in args string.
Parameters
args variable pointer to non parsed args string, updated at function call to new position (with skipped white spaces) allowed nullptr string pointer stored in *args
Definition at line 2358 of file Chat.cpp.
References isWhiteSpace().
Referenced by ExtractFloat(), ExtractLinkArg(), ExtractLiteralArg(), ExtractQuotedArg(), and ExtractUInt32Base().
Field Documentation
load_command_table
bool ChatHandler::load_command_table = true static private
Definition at line 907 of file Chat.h.
Referenced by getCommandTable(), and HandleReloadCommandCommand().
m_session
WorldSession* ChatHandler::m_session private
Definition at line 904 of file Chat.h.
Referenced by ExtractLocationFromLink(), GetAccessLevel(), GetAccountId(), GetGameObjectWithGuid(), GetMangosString(), GetNameLink(), getSelectedCreature(), getSelectedPlayer(), getSelectedUnit(), GetSession(), GetSessionDbcLocale(), GetSessionDbLocaleIndex(), HandleAddCharacterNoteCommand(), HandleAddItemCommand(), HandleAddItemSetCommand(), HandleAuctionAllianceCommand(), HandleAuctionCommand(), HandleAuctionGoblinCommand(), HandleAuctionHordeCommand(), HandleAuraCommand(), HandleBanHelper(), HandleBankCommand(), HandleBanListHelper(), HandleBanListIPCommand(), HandleBattlegroundStartCommand(), HandleBattlegroundStopCommand(), HandleCastBackCommand(), HandleCastCommand(), HandleCastDistCommand(), HandleCastSelfCommand(), HandleCastTargetCommand(), HandleChangeWeatherCommand(), HandleCharacterDeletedListHelper(), HandleCharacterLevelCommand(), HandleCharacterTitlesCommand(), HandleComeToMeCommand(), HandleCooldownClearCommand(), HandleDamageCommand(), HandleDebugAnimCommand(), HandleDebugAreaTriggersCommand(), HandleDebugChatFreezeCommand(), HandleDebugGetItemStateCommand(), HandleDebugGetItemValueCommand(), HandleDebugHaveAtClientCommand(), HandleDebugIncPacketHistory(), HandleDebugIsVisibleCommand(), HandleDebugModItemValueCommand(), HandleDebugOutPacketHistory(), HandleDebugPetDismissSound(), HandleDebugPlayCinematicCommand(), HandleDebugPlayMovieCommand(), HandleDebugPlayMusicCommand(), HandleDebugPlaySoundCommand(), HandleDebugSendBuyErrorCommand(), HandleDebugSendChannelNotifyCommand(), HandleDebugSendChatMsgCommand(), HandleDebugSendEquipErrorCommand(), HandleDebugSendOpcodeCommand(), HandleDebugSendPoiCommand(), HandleDebugSendQuestFailedMsgCommand(), HandleDebugSendQuestInvalidMsgCommand(), HandleDebugSendQuestPartyMsgCommand(), HandleDebugSendSellErrorCommand(), HandleDebugSendSetPhaseShiftCommand(), HandleDebugSendSpellFailCommand(), HandleDebugSendWorldState(), HandleDebugSetItemValueCommand(), HandleDebugTaxiCommand(), HandleDebugUpdateWorldStateCommand(), HandleDeMorphCommand(), HandleDieCommand(), HandleDismountCommand(), HandleEventListCommand(), HandleExploreCheatCommand(), HandleGameObjectAddCommand(), HandleGameObjectDeleteCommand(), HandleGameObjectMoveCommand(), HandleGameObjectNearCommand(), HandleGameObjectNearSpawnedCommand(), HandleGameObjectRespawnCommand(), HandleGameObjectTargetCommand(), HandleGetDistanceCommand(), HandleGetLosCommand(), HandleGMChatCommand(), HandleGMCommand(), HandleGMFlyCommand(), HandleGMListIngameCommand(), HandleGMMountUpCommand(), HandleGMVisibleCommand(), HandleGoCommand(), HandleGoCreatureCommand(), HandleGoGraveyardCommand(), HandleGoGridCommand(), HandleGonameCommand(), HandleGoObjectCommand(), HandleGoTaxinodeCommand(), HandleGoTriggerCommand(), HandleGoWarpCommand(), HandleGoXYCommand(), HandleGoXYZCommand(), HandleGoZoneXYCommand(), HandleGPSCommand(), HandleGridsLoadedCount(), HandleGroupgoCommand(), HandleHonorAddKillCommand(), HandleInstanceListBindsCommand(), HandleInstanceSaveDataCommand(), HandleInstanceUnbindCommand(), HandleItemMoveCommand(), HandleKickPlayerCommand(), HandleLearnAllCraftsCommand(), HandleLearnAllGMCommand(), HandleLearnAllLangCommand(), HandleLearnAllMyPetTalentsCommand(), HandleLearnAllMySpellsCommand(), HandleLearnAllMyTalentsCommand(), HandleLearnCommand(), HandleLevelUpCommand(), HandleLinkAddCommand(), HandleLinkCheckCommand(), HandleLinkEditCommand(), HandleLinkGraveCommand(), HandleLinkRemoveCommand(), HandleLinkToggleCommand(), HandleListAreaTriggerCommand(), HandleListAurasCommand(), HandleListCreatureCommand(), HandleListObjectCommand(), HandleLookupAreaCommand(), HandleLookupCreatureCommand(), HandleLookupEventCommand(), HandleLookupItemCommand(), HandleLookupItemSetCommand(), HandleLookupObjectCommand(), HandleLookupSkillCommand(), HandleLookupTaxiNodeCommand(), HandleLookupTeleCommand(), HandleLookupTitleCommand(), HandleMailBoxCommand(), HandleMmapLoadedTilesCommand(), HandleMmapLocCommand(), HandleMmapPathCommand(), HandleMmapStatsCommand(), HandleMmapTestArea(), HandleMmapTestHeight(), HandleModifyMorphCommand(), HandleModifyPhaseCommand(), HandleModifyStandStateCommand(), HandleMuteCommand(), HandleNamegoCommand(), HandleNearGraveCommand(), HandleNpcAddCommand(), HandleNpcAddVendorItemCommand(), HandleNpcDeleteCommand(), HandleNpcFollowCommand(), HandleNpcMoveCommand(), HandleNpcSayCommand(), HandleNpcSetMoveTypeCommand(), HandleNpcShowLootCommand(), HandleNpcTameCommand(), HandleNpcTextEmoteCommand(), HandleNpcUnFollowCommand(), HandleNpcWhisperCommand(), HandleNpcYellCommand(), HandlePoolInfoCommand(), HandlePoolListCommand(), HandlePoolSpawnsCommand(), HandleResetAllCommand(), HandleResetSpecsCommand(), HandleResetSpellsCommand(), HandleResetTalentsCommand(), HandleResetTaxiNodesCommand(), HandleRespawnCommand(), HandleSaveCommand(), HandleSD2HelpCommand(), HandleSD2ScriptCommand(), HandleSendItemsCommand(), HandleSendItemsHelper(), HandleSendMailCommand(), HandleSendMassItemsCommand(), HandleSendMassMailCommand(), HandleSendMassMoneyCommand(), HandleSendMoneyCommand(), HandleServerInfoCommand(), HandleSetViewCommand(), HandleShowTemporarySpawnList(), HandleStableCommand(), HandleStartCommand(), HandleTaxiCheatCommand(), HandleTeleAddCommand(), HandleTeleCommand(), HandleTicketDiscardCommand(), HandleTicketEscalateCommand(), HandleTicketGoCommand(), HandleTicketNoteCommand(), HandleTicketReadCommand(), HandleTicketResolveCommand(), HandleTicketsCommand(), HandleTicketsListCommand(), HandleTicketSortCommand(), HandleTicketWhisperCommand(), HandleTriggerActiveCommand(), HandleTriggerCommand(), HandleTriggerNearCommand(), HandleUnBanHelper(), HandleWarnCharacterCommand(), HandleWhisperRestrictionCommand(), HandleWhispersCommand(), HandleWpAddCommand(), HandleWpExportCommand(), HandleWpModifyCommand(), HandleWpShowCommand(), LogCommand(), ModifyMountCommandHelper(), needReportToTarget(), ParseCommands(), petLink(), playerLink(), SendGlobalSysMessage(), SendSysMessage(), ShowAccountListHelper(), ShowAchievementCriteriaListHelper(), ShowAchievementListHelper(), ShowFactionListHelper(), ShowHelpForSubCommands(), ShowItemListHelper(), ShowPlayerListHelper(), ShowPoolListHelper(), ShowQuestListHelper(), ShowSpellListHelper(), ShowTriggerListHelper(), and ShowTriggerTargetListHelper().
sentErrorMessage
bool ChatHandler::sentErrorMessage private
Definition at line 908 of file Chat.h.
Referenced by HasSentErrorMessage(), and SetSentErrorMessage().
The documentation for this class was generated from the following files:
Chat.h
Chat.cpp
debugcmds.cpp
Level0.cpp
Level1.cpp
Level2.cpp
Level3.cpp
NpcCommands.cpp
TicketCommands.cpp
CliRunnable.cpp