CMaNGOS_WoTLK: DialogueHelper Class Reference
DialogueHelper Class Reference
Helper class handling a dialogue given as static const array of DialogueEntry or DialogueEntryTwoSide.
#include <sc_instance.h>
Public Member Functions
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
Protected Member Functions
virtual void JustDidDialogueStep (int32)
Will be called when a dialogue step was done.
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Member Functions
void DoNextDialogueStep ()
Internal helper function to do the actual say of a DialogueEntry.
Private Attributes
ScriptedInstance * m_instance
DialogueEntry const * m_dialogueArray
DialogueEntry const * m_currentEntry
DialogueEntryTwoSide const * m_dialogueTwoSideArray
DialogueEntryTwoSide const * m_currentEntryTwoSide
uint32 m_timer
bool m_isFirstSide
bool m_canSimulate
Detailed Description
Helper class handling a dialogue given as static const array of DialogueEntry or DialogueEntryTwoSide.
Definition at line 110 of file sc_instance.h.
Constructor & Destructor Documentation
DialogueHelper() [1/2]
DialogueHelper::DialogueHelper (DialogueEntry const * dialogueArray)
Constructor for DialogueHelper.
Parameters
pDialogueArray The static const array of DialogueEntry holding the information about the dialogue. This array MUST be terminated by {0,0,0}
Definition at line 294 of file sc_instance.cpp.
DialogueHelper() [2/2]
DialogueHelper::DialogueHelper (DialogueEntryTwoSide const * dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
Parameters
pDialogueTwoSideArray The static const array of DialogueEntryTwoSide holding the information about the dialogue. This array MUST be terminated by {0,0,0,0,0}
Definition at line 310 of file sc_instance.cpp.
~DialogueHelper()
virtual DialogueHelper::~DialogueHelper () virtual default
Member Function Documentation
DialogueUpdate()
void DialogueHelper::DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
Definition at line 428 of file sc_instance.cpp.
References DoNextDialogueStep(), and m_timer.
Referenced by instance_blackrock_spire::Update(), instance_shadowfang_keep::Update(), instance_sunwell_plateau::Update(), instance_trial_of_the_champion::Update(), instance_trial_of_the_crusader::Update(), instance_icecrown_citadel::Update(), instance_naxxramas::Update(), instance_pinnacle::Update(), instance_arcatraz::Update(), instance_halls_of_reflection::Update(), instance_pit_of_saron::Update(), instance_ulduar::Update(), instance_temple_of_ahnqiraj::Update(), boss_victor_nefariusAI::UpdateAI(), npc_death_knight_initiateAI::UpdateAI(), npc_highlord_darion_mograineAI::UpdateAI(), boss_brutallusAI::UpdateAI(), boss_alythessAI::UpdateAI(), npc_kiljaeden_controllerAI::UpdateAI(), boss_kiljaedenAI::UpdateAI(), npc_general_andorovAI::UpdateAI(), boss_baltharusAI::UpdateAI(), boss_illidan_stormrageAI::UpdateAI(), npc_akama_illidanAI::UpdateAI(), boss_maievAI::UpdateAI(), npc_akamaAI::UpdateAI(), mob_blood_elf_council_voice_triggerAI::UpdateAI(), npc_image_of_medivhAI::UpdateAI(), npc_queen_lanathel_introAI::UpdateAI(), npc_a_special_surpriseAI::UpdateAI(), npc_valentine_boss_managerAI::UpdateAI(), npc_smolderwing::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), npc_lich_king_villageAI::UpdateAI(), npc_king_ymironAI::UpdateAI(), boss_malygosAI::UpdateAI(), npc_brann_hosAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_mimironAI::UpdateAI(), npc_expedition_commanderAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_saraAI::UpdateAI(), npc_brain_yogg_saronAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), npc_spawned_oronok_tornheartAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_barnesAI::UpdateEscortAI(), npc_squire_roweAI::UpdateEscortAI(), npc_grark_lorkrubAI::UpdateEscortAI(), npc_tapoke_slim_jahnAI::UpdateEscortAI(), npc_demolitionist_legosoAI::UpdateEscortAI(), npc_arthasAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_tarethaAI::UpdateEscortAI(), npc_melizza_brimbuzzleAI::UpdateEscortAI(), npc_areiAI::UpdateEscortAI(), npc_ranshallaAI::UpdateEscortAI(), and npc_shaheenAI::UpdateEscortAI().
DisableDialogue()
void DialogueHelper::DisableDialogue () inline
Definition at line 129 of file sc_instance.h.
References m_timer.
Referenced by boss_illidan_stormrageAI::JustRespawned().
DoNextDialogueStep()
void DialogueHelper::DoNextDialogueStep () private
Internal helper function to do the actual say of a DialogueEntry.
Definition at line 366 of file sc_instance.cpp.
References ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), GetDialogueTarget(), ScriptedInstance::GetSingleCreatureFromStorage(), GetSpeakerByEntry(), JustDidDialogueStep(), m_canSimulate, m_currentEntry, m_currentEntryTwoSide, m_dialogueArray, m_instance, m_isFirstSide, m_timer, DialogueEntry::sayerEntry, DialogueEntryTwoSide::sayerEntry, DialogueEntryTwoSide::sayerEntryAlt, DialogueEntry::textEntry, DialogueEntryTwoSide::textEntry, DialogueEntryTwoSide::textEntryAlt, DialogueEntry::timer, and DialogueEntryTwoSide::timer.
Referenced by DialogueUpdate(), and StartNextDialogueText().
GetDialogueTarget()
virtual Unit* DialogueHelper::GetDialogueTarget () inline protected virtual
Will be called to get a target; OPTIONAL.
Reimplemented in npc_death_knight_initiateAI, and npc_a_special_surpriseAI.
Definition at line 137 of file sc_instance.h.
Referenced by DoNextDialogueStep().
GetSpeakerByEntry()
virtual Creature* DialogueHelper::GetSpeakerByEntry (uint32) inline protected virtual
Will be called to get a speaker, MUST be implemented if not used in instances.
Reimplemented in npc_spawned_oronok_tornheartAI, npc_anchorite_baradaAI, npc_shaheenAI, npc_king_ymironAI, npc_lich_king_villageAI, npc_ranshallaAI, npc_anachronos_the_ancientAI, npc_areiAI, npc_smolderwing, npc_melizza_brimbuzzleAI, npc_demolitionist_legosoAI, npc_tapoke_slim_jahnAI, npc_a_special_surpriseAI, npc_grark_lorkrubAI, npc_keeper_remulosAI, npc_taelan_fordringAI, npc_squire_roweAI, and npc_death_knight_initiateAI.
Definition at line 135 of file sc_instance.h.
Referenced by DoNextDialogueStep().
InitializeDialogueHelper()
void DialogueHelper::InitializeDialogueHelper (ScriptedInstance * instance, bool canSimulateText = false) inline
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
Definition at line 120 of file sc_instance.h.
References m_canSimulate, and m_instance.
Referenced by boss_algalonAI::boss_algalonAI(), boss_alythessAI::boss_alythessAI(), boss_baltharusAI::boss_baltharusAI(), boss_brutallusAI::boss_brutallusAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_maievAI::boss_maievAI(), boss_malygosAI::boss_malygosAI(), boss_mimironAI::boss_mimironAI(), boss_saraAI::boss_saraAI(), boss_soccothratesAI::boss_soccothratesAI(), boss_thorimAI::boss_thorimAI(), boss_victor_nefariusAI::boss_victor_nefariusAI(), instance_blackrock_spire::Initialize(), instance_shadowfang_keep::Initialize(), instance_sunwell_plateau::Initialize(), instance_temple_of_ahnqiraj::Initialize(), instance_trial_of_the_champion::Initialize(), instance_trial_of_the_crusader::Initialize(), instance_halls_of_reflection::Initialize(), instance_pit_of_saron::Initialize(), instance_icecrown_citadel::Initialize(), instance_naxxramas::Initialize(), instance_ulduar::Initialize(), instance_pinnacle::Initialize(), instance_arcatraz::Initialize(), mob_blood_elf_council_voice_triggerAI::mob_blood_elf_council_voice_triggerAI(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_akamaAI::npc_akamaAI(), npc_arthasAI::npc_arthasAI(), npc_barnesAI::npc_barnesAI(), npc_brain_yogg_saronAI::npc_brain_yogg_saronAI(), npc_brann_hosAI::npc_brann_hosAI(), npc_expedition_commanderAI::npc_expedition_commanderAI(), npc_general_andorovAI::npc_general_andorovAI(), npc_highlord_darion_mograineAI::npc_highlord_darion_mograineAI(), npc_image_of_medivhAI::npc_image_of_medivhAI(), npc_kiljaeden_controllerAI::npc_kiljaeden_controllerAI(), npc_millhouse_manastormAI::npc_millhouse_manastormAI(), npc_queen_lanathel_introAI::npc_queen_lanathel_introAI(), npc_reginald_windsorAI::npc_reginald_windsorAI(), npc_tarethaAI::npc_tarethaAI(), npc_thrall_old_hillsbradAI::npc_thrall_old_hillsbradAI(), and npc_valentine_boss_managerAI::npc_valentine_boss_managerAI().
JustDidDialogueStep()
virtual void DialogueHelper::JustDidDialogueStep (int32) inline protected virtual
Will be called when a dialogue step was done.
Reimplemented in boss_soccothratesAI, npc_millhouse_manastormAI, instance_arcatraz, npc_spawned_oronok_tornheartAI, npc_anchorite_baradaAI, npc_akama_illidanAI, npc_shaheenAI, instance_pinnacle, instance_ulduar, npc_brain_yogg_saronAI, boss_saraAI, boss_thorimAI, npc_expedition_commanderAI, boss_mimironAI, boss_algalonAI, npc_brann_hosAI, boss_malygosAI, instance_icecrown_citadel, npc_queen_lanathel_introAI, instance_pit_of_saron, instance_halls_of_reflection, npc_king_ymironAI, npc_lich_king_villageAI, instance_trial_of_the_crusader, instance_trial_of_the_champion, npc_ranshallaAI, npc_anachronos_the_ancientAI, npc_areiAI, npc_smolderwing, npc_melizza_brimbuzzleAI, npc_tarethaAI, npc_thrall_old_hillsbradAI, npc_arthasAI, npc_demolitionist_legosoAI, npc_tapoke_slim_jahnAI, instance_sunwell_plateau, boss_kiljaedenAI, npc_kiljaeden_controllerAI, boss_brutallusAI, npc_valentine_boss_managerAI, npc_a_special_surpriseAI, npc_image_of_medivhAI, npc_barnesAI, npc_grark_lorkrubAI, instance_blackrock_spire, npc_akamaAI, boss_maievAI, boss_illidan_stormrageAI, instance_temple_of_ahnqiraj, npc_general_andorovAI, npc_keeper_remulosAI, npc_taelan_fordringAI, npc_reginald_windsorAI, npc_squire_roweAI, instance_shadowfang_keep, npc_highlord_darion_mograineAI, npc_death_knight_initiateAI, and boss_victor_nefariusAI.
Definition at line 133 of file sc_instance.h.
Referenced by DoNextDialogueStep().
SetDialogueSide()
void DialogueHelper::SetDialogueSide (bool isFirstSide) inline
Set if take first entries or second entries.
Definition at line 122 of file sc_instance.h.
References m_isFirstSide.
Referenced by instance_trial_of_the_champion::OnPlayerEnter(), instance_trial_of_the_crusader::OnPlayerEnter(), and instance_halls_of_reflection::OnPlayerEnter().
StartNextDialogueText()
void DialogueHelper::StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
Parameters
iTextEntry The TextEntry of the dialogue that will be started (must be always the entry of first side)
Definition at line 326 of file sc_instance.cpp.
References DoNextDialogueStep(), Map::GetId(), InstanceData::instance, m_currentEntry, m_currentEntryTwoSide, m_dialogueArray, m_dialogueTwoSideArray, m_instance, script_error_log(), DialogueEntry::textEntry, and DialogueEntryTwoSide::textEntry.
Referenced by boss_algalonAI::Aggro(), boss_thorimAI::Aggro(), boss_mimironAI::DamageTaken(), boss_thorimAI::DamageTaken(), boss_saraAI::DamageTaken(), instance_icecrown_citadel::DoHandleCitadelAreaTrigger(), instance_temple_of_ahnqiraj::DoHandleTempleAreaTrigger(), npc_general_andorovAI::DoMoveToEventLocation(), instance_trial_of_the_champion::DoPrepareArgentChallenge(), instance_trial_of_the_champion::DoPrepareBlackKnight(), instance_trial_of_the_champion::DoPrepareChampions(), npc_brain_yogg_saronAI::DoPrepareIllusion(), instance_blackrock_spire::DoSendNextStadiumWave(), boss_illidan_stormrageAI::DoStartCombatEvent(), npc_reginald_windsorAI::DoStartEscort(), boss_victor_nefariusAI::DoStartIntro(), boss_brutallusAI::DoStartIntro(), npc_reginald_windsorAI::DoStartKeepEvent(), instance_pit_of_saron::DoStartTyrannusEvent(), npc_valentine_boss_managerAI::DoStartValentineEvent(), boss_kiljaedenAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_brann_hosAI::ForceEndTribunalEvent(), npc_demolitionist_legosoAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustReachedHome(), npc_tapoke_slim_jahnAI::JustReachedHome(), boss_algalonAI::JustReachedHome(), npc_smolderwing::JustRespawned(), boss_maievAI::KilledUnit(), npc_lich_king_villageAI::MoveInLineOfSight(), npc_queen_lanathel_introAI::MoveInLineOfSight(), boss_baltharusAI::MoveInLineOfSight(), boss_soccothratesAI::MoveInLineOfSight(), npc_a_special_surpriseAI::MoveInLineOfSight(), npc_akamaAI::MovementInform(), npc_akama_illidanAI::MovementInform(), npc_highlord_darion_mograineAI::MovementInform(), boss_algalonAI::MovementInform(), npc_general_andorovAI::MovementInform(), npc_anachronos_the_ancientAI::MovementInform(), npc_brann_hosAI::MovementInform(), npc_anchorite_baradaAI::MovementInform(), npc_millhouse_manastormAI::npc_millhouse_manastormAI(), npc_shaheenAI::npc_shaheenAI(), npc_spawned_oronok_tornheartAI::npc_spawned_oronok_tornheartAI(), instance_shadowfang_keep::OnCreatureCreate(), instance_blackrock_spire::OnCreatureDeath(), instance_ulduar::OnCreatureDeath(), instance_trial_of_the_champion::OnCreatureEnterCombat(), npc_spawned_oronok_tornheartAI::PointMovementInform(), boss_alythessAI::ReceiveAIEvent(), boss_mimironAI::ReceiveAIEvent(), npc_taelan_fordringAI::ReceiveAIEvent(), npc_shaheenAI::ReceiveAIEvent(), npc_death_knight_initiateAI::ReceiveAIEvent(), npc_king_ymironAI::ReceiveAIEvent(), boss_malygosAI::ReceiveAIEvent(), boss_algalonAI::ReceiveAIEvent(), npc_expedition_commanderAI::ReceiveAIEvent(), npc_anchorite_baradaAI::ReceiveAIEvent(), npc_demolitionist_legosoAI::ReceiveAIEvent(), npc_highlord_darion_mograineAI::ReceiveAIEvent(), instance_shadowfang_keep::SetData(), instance_blackrock_spire::SetData(), instance_sunwell_plateau::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_halls_of_reflection::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_pinnacle::SetData(), instance_arcatraz::SetData(), npc_image_of_medivhAI::SpellHit(), mob_blood_elf_council_voice_triggerAI::StartVoiceEvent(), npc_areiAI::SummonedCreatureJustDied(), npc_shaheenAI::SummonedCreatureJustDied(), npc_kiljaeden_controllerAI::SummonedCreatureJustDied(), npc_image_of_medivhAI::SummonedMovementInform(), npc_shaheenAI::SummonedMovementInform(), npc_anachronos_the_ancientAI::SummonedMovementInform(), npc_ranshallaAI::SummonedMovementInform(), npc_squire_roweAI::SummonedMovementInform(), npc_taelan_fordringAI::SummonedMovementInform(), mob_blood_elf_council_voice_triggerAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_mimironAI::UpdateAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_reginald_windsorAI::WaypointReached(), npc_taelan_fordringAI::WaypointReached(), npc_keeper_remulosAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_tarethaAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_barnesAI::WaypointReached(), npc_arthasAI::WaypointReached(), npc_melizza_brimbuzzleAI::WaypointReached(), npc_ranshallaAI::WaypointReached(), npc_shaheenAI::WaypointReached(), and npc_demolitionist_legosoAI::WaypointReached().
Field Documentation
m_canSimulate
bool DialogueHelper::m_canSimulate private
Definition at line 151 of file sc_instance.h.
Referenced by DoNextDialogueStep(), and InitializeDialogueHelper().
m_currentEntry
DialogueEntry const* DialogueHelper::m_currentEntry private
Definition at line 145 of file sc_instance.h.
Referenced by DoNextDialogueStep(), and StartNextDialogueText().
m_currentEntryTwoSide
DialogueEntryTwoSide const* DialogueHelper::m_currentEntryTwoSide private
Definition at line 147 of file sc_instance.h.
Referenced by DoNextDialogueStep(), and StartNextDialogueText().
m_dialogueArray
DialogueEntry const* DialogueHelper::m_dialogueArray private
Definition at line 144 of file sc_instance.h.
Referenced by DoNextDialogueStep(), and StartNextDialogueText().
m_dialogueTwoSideArray
DialogueEntryTwoSide const* DialogueHelper::m_dialogueTwoSideArray private
Definition at line 146 of file sc_instance.h.
Referenced by StartNextDialogueText().
m_instance
ScriptedInstance* DialogueHelper::m_instance private
Definition at line 142 of file sc_instance.h.
Referenced by DoNextDialogueStep(), InitializeDialogueHelper(), and StartNextDialogueText().
m_isFirstSide
bool DialogueHelper::m_isFirstSide private
Definition at line 150 of file sc_instance.h.
Referenced by DoNextDialogueStep(), and SetDialogueSide().
m_timer
uint32 DialogueHelper::m_timer private
Definition at line 149 of file sc_instance.h.
Referenced by DialogueUpdate(), DisableDialogue(), and DoNextDialogueStep().
The documentation for this class was generated from the following files:
sc_instance.h
sc_instance.cpp