CMaNGOS_WoTLK: PlayerbotAI Class Reference
PlayerbotAI Class Reference
#include <PlayerbotAI.h>
Data Structures
struct AttackerInfo
Public Types
enum ScenarioType {
SCENARIO_PVE , SCENARIO_PVE_ELITE , SCENARIO_PVE_RAID , SCENARIO_PVP_DUEL ,
SCENARIO_PVP_BG , SCENARIO_PVP_ARENA , SCENARIO_PVP_OPENWORLD
}
enum CombatStyle { COMBAT_MELEE = 0x01 , COMBAT_RANGED = 0x02 }
enum CombatOrderType {
ORDERS_NONE = 0x0000 , ORDERS_TANK = 0x0001 , ORDERS_ASSIST = 0x0002 , ORDERS_HEAL = 0x0004 ,
ORDERS_NODISPEL = 0x0008 , ORDERS_PROTECT = 0x0010 , ORDERS_PASSIVE = 0x0020 , ORDERS_TEMP_WAIT_TANKAGGRO = 0x0040 ,
ORDERS_TEMP_WAIT_OOC = 0x0080 , ORDERS_RESIST_FIRE = 0x0100 , ORDERS_RESIST_NATURE = 0x0200 , ORDERS_RESIST_FROST = 0x0400 ,
ORDERS_RESIST_SHADOW = 0x0800 , ORDERS_MAIN_TANK = 0x1000 , ORDERS_MAIN_HEAL = 0x2000 , ORDERS_NOT_MAIN_HEAL = 0x4000 ,
ORDERS_PRIMARY = 0x7007 , ORDERS_SECONDARY = 0x0F78 , ORDERS_RESIST = 0x0F00 , ORDERS_TEMP = 0x00C0 ,
ORDERS_RESET = 0xFFFF
}
enum CombatTargetType { TARGET_NORMAL = 0x00 , TARGET_THREATEN = 0x01 }
enum BotState {
BOTSTATE_LOADING , BOTSTATE_NORMAL , BOTSTATE_COMBAT , BOTSTATE_DEAD ,
BOTSTATE_DEADRELEASED , BOTSTATE_LOOTING , BOTSTATE_FLYING , BOTSTATE_TAME ,
BOTSTATE_DELAYED
}
enum CollectionFlags {
COLLECT_FLAG_NOTHING = 0x00 , COLLECT_FLAG_COMBAT = 0x01 , COLLECT_FLAG_QUEST = 0x02 , COLLECT_FLAG_PROFESSION = 0x04 ,
COLLECT_FLAG_LOOT = 0x08 , COLLECT_FLAG_SKIN = 0x10 , COLLECT_FLAG_NEAROBJECT = 0x20
}
enum MovementOrderType { MOVEMENT_NONE = 0x00 , MOVEMENT_FOLLOW = 0x01 , MOVEMENT_STAY = 0x02 }
enum TaskFlags {
NONE = 0x00 , SELL_ITEMS = 0x01 , BUY_ITEMS = 0x02 , REPAIR_ITEMS = 0x03 ,
ADD_AUCTION = 0x04 , REMOVE_AUCTION = 0x05 , RESET_TALENTS = 0x06 , BANK_WITHDRAW = 0x07 ,
BANK_DEPOSIT = 0x08 , LIST_QUEST = 0x09 , END_QUEST = 0x0A , TAKE_QUEST = 0x0B
}
enum AnnounceFlags { NOTHING = 0x00 , INVENTORY_FULL = 0x01 , CANT_AFFORD = 0x02 , CANT_USE_TOO_FAR = 0x03 }
enum ATTACKERINFOTYPE {
AIT_NONE = 0x00 , AIT_LOWESTTHREAT = 0x01 , AIT_HIGHESTTHREAT = 0x02 , AIT_VICTIMSELF = 0x04 ,
AIT_VICTIMNOTSELF = 0x08
}
enum HELPERLINKABLES {
HL_NONE , HL_PROFESSION , HL_ITEM , HL_TALENT ,
HL_SKILL , HL_OPTION , HL_PETAGGRO , HL_QUEST ,
HL_GAMEOBJECT , HL_SPELL , HL_TARGET , HL_NAME ,
HL_AUCTION , HL_MAIL , HL_RECIPE
}
typedef std::pair< enum TaskFlags, uint32 > taskPair
typedef std::list< taskPair > BotTaskList
typedef std::list< enum NPCFlags > BotNPCList
typedef std::map< uint32, uint32 > BotNeedItem
typedef std::pair< uint32, uint32 > talentPair
typedef std::list< ObjectGuid > BotObjectList
typedef std::list< uint32 > BotEntryList
typedef std::vector< uint32 > BotTaxiNode
typedef std::set< ObjectGuid > BotObjectSet
typedef std::map< ObjectGuid, AttackerInfo > AttackerInfoList
typedef std::map< uint32, float > SpellRanges
Public Member Functions
PlayerbotAI (PlayerbotMgr &mgr, Player *const bot, bool debugWhisper)
virtual ~PlayerbotAI ()
void UpdateAI (const uint32 p_time)
void HandleCommand (const std::string &text, Player &fromPlayer)
void HandleBotOutgoingPacket (const WorldPacket &packet)
ScenarioType GetScenarioType ()
CombatStyle GetCombatStyle ()
void SetCombatStyle (CombatStyle cs)
PlayerbotClassAI * GetClassAI ()
void ReloadAI ()
uint32 getSpellId (const char *args, bool master=false) const
uint32 getPetSpellId (const char *args) const
uint32 initSpell (uint32 spellId)
uint32 initPetSpell (uint32 spellIconId)
void extractMailIds (const std::string &text, std::list< uint32 > &mailIds) const
void extractQuestIds (const std::string &text, std::list< uint32 > &questIds) const
void extractAuctionIds (const std::string &text, std::list< uint32 > &auctionIds) const
void extractTalentIds (const std::string &text, std::list< talentPair > &talentIds) const
void extractItemIds (const std::string &text, std::list< uint32 > &itemIds) const
void extractSpellId (const std::string &text, uint32 &spellId) const
void extractSpellIdList (const std::string &text, BotEntryList &m_spellsToLearn) const
uint32 extractMoney (const std::string &text) const
void extractGOinfo (const std::string &text, BotObjectList &m_lootTargets) const
void findItemsInEquip (std::list< uint32 > &itemIdSearchList, std::list< Item * > &foundItemList) const
void findItemsInInv (std::list< uint32 > &itemIdSearchList, std::list< Item * > &foundItemList) const
void findNearbyGO ()
void findNearbyCreature ()
void findNearbyCorpse ()
void GiveLevel (uint32 level)
GiveLevel sets the bot's level to 'level' Not the clearest of function names, we're just mirroring Player.cpp's function name.
uint32 TalentSpecDBContainsError ()
Checks whether the TalentSpec database contains any obvious errors.
uint32 GetTalentSpecsAmount ()
uint32 GetTalentSpecsAmount (long specClass)
std::list< TalentSpec > GetTalentSpecs (long specClass)
GetTalentSpecs queries DB for the talentspecs (for a class), returning them in a list of TS structures.
TalentSpec GetTalentSpec (long specClass, long choice)
GetTalentSpec queries DB for a talentspec given a class and a choice.
TalentSpec GetActiveTalentSpec ()
void ClearActiveTalentSpec ()
void SetActiveTalentSpec (TalentSpec ts)
bool ApplyActiveTalentSpec ()
ApplyActiveTalentSpec takes the active talent spec and attempts to apply it.
bool IsElite (Unit *target, bool isWorldBoss=false) const
IsElite() Playerbot wrapper to know if a target is elite or not.
void FaceTarget (Unit *target)
void MakeSpellLink (const SpellEntry *sInfo, std::ostringstream &out)
void MakeWeaponSkillLink (const SpellEntry *sInfo, std::ostringstream &out, uint32 skillid)
bool canObeyCommandFrom (const Player &player) const
Spell * GetCurrentSpell () const
uint32 GetCurrentSpellId ()
bool HasAura (uint32 spellId, const Unit &player) const
bool HasAura (const char *spellName, const Unit &player) const
bool HasAura (const char *spellName) const
bool CanReceiveSpecificSpell (uint8 spec, Unit *target) const
bool PickPocket (Unit *pTarget)
bool HasTool (uint32 TC)
bool HasSpellReagents (uint32 spellId)
void ItemCountInInv (uint32 itemid, uint32 &count)
uint32 GetSpellCharges (uint32 spellId)
uint8 GetHealthPercent (const Unit &target) const
uint8 GetHealthPercent () const
uint8 GetManaPercent (const Unit &target) const
uint8 GetManaPercent () const
uint8 GetRageAmount (const Unit &target) const
uint8 GetRageAmount () const
uint8 GetEnergyAmount (const Unit &target) const
uint8 GetEnergyAmount () const
uint8 GetRunicPower (const Unit &target) const
uint8 GetRunicPower () const
Item * FindFood () const
Item * FindDrink () const
Item * FindBandage () const
Item * FindPoison () const
Item * FindMount (uint32 matchingRidingSkill) const
Item * FindItem (uint32 ItemId, bool Equipped_too=false)
Item * FindItemInBank (uint32 ItemId)
Item * FindKeyForLockValue (uint32 reqSkillValue)
Item * FindBombForLockValue (uint32 reqSkillValue)
Item * FindConsumable (uint32 displayId) const
Item * FindManaRegenItem () const
FindManaRegenItem() return Item* Returns items like runes or potion that can help the bot to instantly resplenish some of its mana.
bool FindAmmo () const
uint8 _findItemSlot (Item *target)
bool CanStore ()
void TellMaster (const std::string &text) const
void TellMaster (const char *fmt,...) const
void SendWhisper (const std::string &text, Player &player) const
SpellCastResult CastSpell (const char *args)
SpellCastResult CastSpell (uint32 spellId)
SpellCastResult CastSpell (uint32 spellId, Unit &target)
SpellCastResult CheckBotCast (const SpellEntry *sInfo)
SpellCastResult CastPetSpell (uint32 spellId, Unit *target=nullptr)
SpellCastResult Buff (uint32 spellId, Unit *target, void(*beforeCast)(Player *)=nullptr)
SpellCastResult SelfBuff (uint32 spellId)
bool In_Range (Unit *Target, uint32 spellId)
bool In_Reach (Unit *Target, uint32 spellId)
bool CanReachWithSpellAttack (Unit *target)
void UseItem (Item *item, uint32 targetFlag, ObjectGuid targetGUID)
void UseItem (Item *item, uint8 targetInventorySlot)
void UseItem (Item *item, Unit *target)
void UseItem (Item *item)
void TryEmergency (Unit *pAttacker)
TryEmergency() Playerbot function to select an item that the bot will use to heal itself on low health without waiting for a heal from a healer.
void PlaySound (uint32 soundid)
void Announce (AnnounceFlags msg)
void EquipItem (Item *src_Item)
void SendNotEquipList (Player &player)
void BotDataRestore ()
BotDataRestore() Restores autoequip - the toggle status for the 'equip auto' command.
void CombatOrderRestore ()
CombatOrderRestore() Restores all saved attributes.
void AutoUpgradeEquipment ()
void FollowAutoReset ()
void AutoEquipComparison (Item *pItem, Item *pItem2)
bool ItemStatComparison (const ItemPrototype *pProto, const ItemPrototype *pProto2)
void InterruptCurrentCastingSpell ()
void Attack (Unit *forcedTarget=nullptr)
void GetCombatTarget (Unit *forcedTarget=0)
void GetDuelTarget (Unit *forcedTarget)
Unit * GetCurrentTarget ()
void DoNextCombatManeuver ()
void DoCombatMovement ()
void SetIgnoreUpdateTime (uint8 t=0)
time_t CurrentTime ()
Player * GetPlayerBot () const
Player * GetPlayer () const
Player * GetMaster () const
BotState GetState ()
void SetState (BotState state)
void SetQuestNeedItems ()
void SetQuestNeedCreatures ()
void SendQuestNeedList ()
bool IsInQuestItemList (uint32 itemid)
bool IsInQuestCreatureList (uint32 id)
bool IsItemUseful (uint32 itemid)
void SendOrders (Player &player)
bool DoTeleport (WorldObject &obj)
void DoLoot ()
void DoFlight ()
void GetTaxi (ObjectGuid guid, BotTaxiNode &nodes)
void BeingRolledOn (ObjectGuid target)
bool HasCollectFlag (uint8 flag)
void SetCollectFlag (uint8 flag)
uint32 EstRepairAll ()
uint32 EstRepair (uint16 pos)
void AcceptQuest (Quest const *qInfo, Player *pGiver)
void TurnInQuests (WorldObject *questgiver)
void ListQuests (WorldObject *questgiver)
bool AddQuest (const uint32 entry, WorldObject *questgiver)
void MakeQuestLink (Quest const *quest, std::ostringstream &out)
bool IsInCombat ()
bool IsRegenerating ()
IsRegenerating() return boolean Returns true if bot is having at least one aura associated with regenerating mana (drinking) or health (food)
bool IsGroupReady ()
Player * GetGroupTank ()
Player * GetGroupHealer ()
void SetGroupCombatOrder (CombatOrderType co)
void ClearGroupCombatOrder (CombatOrderType co)
void SetGroupIgnoreUpdateTime (uint8 t)
bool GroupHoTOnTank ()
bool CanPull (Player &fromPlayer)
bool CastPull ()
bool GroupTankHoldsAggro ()
bool CastNeutralize ()
void UpdateAttackerInfo ()
Unit * FindAttacker (ATTACKERINFOTYPE ait=AIT_NONE, Unit *victim=0)
uint32 GetAttackerCount ()
void SetCombatOrderByStr (std::string str, Unit *target=0)
void SetCombatOrder (CombatOrderType co, Unit *target=0)
void ClearCombatOrder (CombatOrderType co)
CombatOrderType GetCombatOrder ()
bool IsMainTank ()
bool IsTank ()
bool IsMainHealer ()
bool IsHealer ()
bool HasDispelOrder ()
bool IsDPS ()
bool Impulse ()
void SetMovementOrder (MovementOrderType mo, Unit *followTarget=0)
MovementOrderType GetMovementOrder ()
void MovementReset ()
void MovementClear ()
void SetInFront (const Unit *obj)
void ItemLocalization (std::string &itemName, const uint32 itemID) const
void QuestLocalization (std::string &questTitle, const uint32 questID) const
void CreatureLocalization (std::string &creatureName, const uint32 entry) const
void GameObjectLocalization (std::string &gameobjectName, const uint32 entry) const
uint32 GetFreeBagSpace () const
bool DropGarbage (bool bVerbose)
void SellGarbage (Player &player, bool listNonTrash=true, bool bDetailTrashSold=false, bool verbose=true)
void Sell (const uint32 itemid)
void Buy (Creature *vendor, const uint32 itemid)
std::string DropItem (const uint32 itemid)
void AddAuction (const uint32 itemid, Creature *aCreature)
void ListAuctions ()
bool RemoveAuction (const uint32 auctionid)
void Repair (const uint32 itemid, Creature *rCreature)
bool Talent (Creature *tCreature)
void InspectUpdate ()
bool Withdraw (const uint32 itemid)
bool Deposit (const uint32 itemid)
void BankBalance ()
std::string Cash (uint32 copper)
std::string AuctionResult (std::string subject, std::string body)
Static Public Member Functions
static bool IsNeutralized (Unit *target)
static bool IsImmuneToSchool (Unit *pTarget, SpellSchoolMask SchoolMask)
IsImmuneToSchool() Playerbot wrapper to know if a target is immune or not to a specific damage school.
Data Fields
uint8 m_DelayAttack
time_t m_DelayAttackInit
Unit * gPrimtarget
Unit * gSectarget
uint32 gQuestFetch
bool m_AutoEquipToggle
uint32 SellWhite
uint8 DistOverRide
float gDist [2]
float gTempDist
float gTempDist2
uint8 m_FollowAutoGo
uint8 IsUpOrDown
Protected Member Functions
bool ValidateTalent (uint16 talent, long charClass)
ValidateTalent tests a talent against class to see if it belongs to that class.
bool ValidateGlyph (uint16 glyph, long charClass)
ValidateGlyph tests a glyph against class to see if it belongs to that class - accepts both Major and Minor glyphs.
bool ValidateMajorGlyph (uint16 glyph, long charClass)
ValidateMajorGlyph tests a glyph against class to see if it belongs to that class - only accepts Major glyphs.
bool ValidateMinorGlyph (uint16 glyph, long charClass)
ValidateMinorGlyph tests a glyph against class to see if it belongs to that class - only accepts Minor glyphs.
Private Member Functions
bool ExtractCommand (const std::string sLookingFor, std::string &text, bool bUseShort=false)
ExtractCommand looks for a command in a text string sLookingFor - string you're looking for (e.g.
void _HandleCommandReset (std::string &text, Player &fromPlayer)
void _HandleCommandOrders (std::string &text, Player &fromPlayer)
void _HandleCommandFollow (std::string &text, Player &fromPlayer)
void _HandleCommandStay (std::string &text, Player &fromPlayer)
void _HandleCommandAttack (std::string &text, Player &fromPlayer)
void _HandleCommandPull (std::string &text, Player &fromPlayer)
void _HandleCommandNeutralize (std::string &text, Player &fromPlayer)
void _HandleCommandCast (std::string &text, Player &fromPlayer)
void _HandleCommandSell (std::string &text, Player &fromPlayer)
void _HandleCommandBuy (std::string &text, Player &fromPlayer)
void _HandleCommandDrop (std::string &text, Player &fromPlayer)
void _HandleCommandRepair (std::string &text, Player &fromPlayer)
void _HandleCommandAuction (std::string &text, Player &fromPlayer)
void _HandleCommandMail (std::string &text, Player &fromPlayer)
void _HandleCommandBank (std::string &text, Player &fromPlayer)
void _HandleCommandTalent (std::string &text, Player &fromPlayer)
void _HandleCommandUse (std::string &text, Player &fromPlayer)
void _HandleCommandEquip (std::string &text, Player &fromPlayer)
void _HandleCommandFind (std::string &text, Player &fromPlayer)
void _HandleCommandGet (std::string &text, Player &fromPlayer)
void _HandleCommandCollect (std::string &text, Player &fromPlayer)
void _HandleCommandQuest (std::string &text, Player &fromPlayer)
void _HandleCommandCraft (std::string &text, Player &fromPlayer)
void _HandleCommandEnchant (std::string &text, Player &fromPlayer)
void _HandleCommandProcess (std::string &text, Player &fromPlayer)
void _HandleCommandPet (std::string &text, Player &fromPlayer)
void _HandleCommandSpells (std::string &text, Player &fromPlayer)
void _HandleCommandSurvey (std::string &text, Player &fromPlayer)
void _HandleCommandSkill (std::string &text, Player &fromPlayer)
bool _HandleCommandSkillLearnHelper (TrainerSpell const *tSpell, uint32 spellId, uint32 cost)
void _HandleCommandStats (std::string &text, Player &fromPlayer)
void _HandleCommandHelp (std::string &text, Player &fromPlayer)
void _HandleCommandHelp (const char *szText, Player &fromPlayer)
void _HandleCommandGM (std::string &text, Player &fromPlayer)
std::string _HandleCommandHelpHelper (std::string sCommand, std::string sExplain, HELPERLINKABLES reqLink=HL_NONE, bool bReqLinkMultiples=false, bool bCommandShort=false)
bool TradeItem (const Item &item, int8 slot=-1)
bool TradeCopper (uint32 copper)
void UpdateAttackersForTarget (Unit *victim)
void _doSellItem (Item *const item, std::ostringstream &report, std::ostringstream &canSell, uint32 &TotalCost, uint32 &TotalSold)
void MakeItemLink (const Item *item, std::ostringstream &out, bool IncludeQuantity=true)
void MakeItemText (const Item *item, std::ostringstream &out, bool IncludeQuantity=true)
void MakeItemLink (const ItemPrototype *item, std::ostringstream &out)
Private Attributes
PlayerbotMgr & m_mgr
Player *const m_bot
PlayerbotClassAI * m_classAI
time_t m_ignoreAIUpdatesUntilTime
CombatStyle m_combatStyle
CombatOrderType m_combatOrder
MovementOrderType m_movementOrder
TalentSpec m_activeTalentSpec
ScenarioType m_ScenarioType
BotState m_botState
BotNeedItem m_needItemList
BotNeedItem m_needCreatureOrGOList
BotNPCList m_findNPC
BotTaskList m_tasks
BotObjectList m_lootTargets
BotEntryList m_spellsToLearn
ObjectGuid m_lootCurrent
ObjectGuid m_lootPrev
BotEntryList m_collectObjects
BotTaxiNode m_taxiNodes
BotEntryList m_noToolList
BotObjectList m_being_rolled_on
uint8 m_collectionFlags
uint32 m_collectDist
bool m_inventory_full
uint32 m_itemTarget
bool m_dropWhite
uint32 m_CurrentlyCastingSpellId
uint32 m_CraftSpellId
uint32 m_spellIdCommand
ObjectGuid m_targetGuidCommand
ObjectGuid m_taxiMaster
BotObjectSet m_ignorePlayersChat
AttackerInfoList m_attackerInfo
bool m_ignoreNeutralizeEffect
bool m_targetChanged
CombatTargetType m_targetType
Unit * m_targetCombat
Unit * m_targetAssist
Unit * m_targetProtect
Unit * m_followTarget
uint32 FISHING
uint32 HERB_GATHERING
uint32 MINING
uint32 SKINNING
uint32 ASPECT_OF_THE_MONKEY
SpellRanges m_spellRangeMap
float m_destX
float m_destY
float m_destZ
bool m_bDebugCommandChat
bool m_debugWhisper = false
Detailed Description
Definition at line 1563 of file PlayerbotAI.h.
Member Typedef Documentation
AttackerInfoList
typedef std::map<ObjectGuid, AttackerInfo> PlayerbotAI::AttackerInfoList
Definition at line 1701 of file PlayerbotAI.h.
BotEntryList
typedef std::list<uint32> PlayerbotAI::BotEntryList
Definition at line 1679 of file PlayerbotAI.h.
BotNeedItem
typedef std::map<uint32, uint32> PlayerbotAI::BotNeedItem
Definition at line 1676 of file PlayerbotAI.h.
BotNPCList
typedef std::list<enum NPCFlags> PlayerbotAI::BotNPCList
Definition at line 1675 of file PlayerbotAI.h.
BotObjectList
typedef std::list<ObjectGuid> PlayerbotAI::BotObjectList
Definition at line 1678 of file PlayerbotAI.h.
BotObjectSet
typedef std::set<ObjectGuid> PlayerbotAI::BotObjectSet
Definition at line 1681 of file PlayerbotAI.h.
BotTaskList
typedef std::list<taskPair> PlayerbotAI::BotTaskList
Definition at line 1674 of file PlayerbotAI.h.
BotTaxiNode
typedef std::vector<uint32> PlayerbotAI::BotTaxiNode
Definition at line 1680 of file PlayerbotAI.h.
SpellRanges
typedef std::map<uint32, float> PlayerbotAI::SpellRanges
Definition at line 1702 of file PlayerbotAI.h.
talentPair
typedef std::pair<uint32, uint32> PlayerbotAI::talentPair
Definition at line 1677 of file PlayerbotAI.h.
taskPair
typedef std::pair<enum TaskFlags, uint32> PlayerbotAI::taskPair
Definition at line 1673 of file PlayerbotAI.h.
Member Enumeration Documentation
AnnounceFlags
enum PlayerbotAI::AnnounceFlags
Enumerator
NOTHING
INVENTORY_FULL
CANT_AFFORD
CANT_USE_TOO_FAR
Definition at line 1665 of file PlayerbotAI.h.
ATTACKERINFOTYPE
enum PlayerbotAI::ATTACKERINFOTYPE
Enumerator
AIT_NONE
AIT_LOWESTTHREAT
AIT_HIGHESTTHREAT
AIT_VICTIMSELF
AIT_VICTIMNOTSELF
Definition at line 1684 of file PlayerbotAI.h.
BotState
enum PlayerbotAI::BotState
Enumerator
BOTSTATE_LOADING
BOTSTATE_NORMAL
BOTSTATE_COMBAT
BOTSTATE_DEAD
BOTSTATE_DEADRELEASED
BOTSTATE_LOOTING
BOTSTATE_FLYING
BOTSTATE_TAME
BOTSTATE_DELAYED
Definition at line 1618 of file PlayerbotAI.h.
CollectionFlags
enum PlayerbotAI::CollectionFlags
Enumerator
COLLECT_FLAG_NOTHING
COLLECT_FLAG_COMBAT
COLLECT_FLAG_QUEST
COLLECT_FLAG_PROFESSION
COLLECT_FLAG_LOOT
COLLECT_FLAG_SKIN
COLLECT_FLAG_NEAROBJECT
Definition at line 1631 of file PlayerbotAI.h.
CombatOrderType
enum PlayerbotAI::CombatOrderType
Enumerator
ORDERS_NONE
ORDERS_TANK
ORDERS_ASSIST
ORDERS_HEAL
ORDERS_NODISPEL
ORDERS_PROTECT
ORDERS_PASSIVE
ORDERS_TEMP_WAIT_TANKAGGRO
ORDERS_TEMP_WAIT_OOC
ORDERS_RESIST_FIRE
ORDERS_RESIST_NATURE
ORDERS_RESIST_FROST
ORDERS_RESIST_SHADOW
ORDERS_MAIN_TANK
ORDERS_MAIN_HEAL
ORDERS_NOT_MAIN_HEAL
ORDERS_PRIMARY
ORDERS_SECONDARY
ORDERS_RESIST
ORDERS_TEMP
ORDERS_RESET
Definition at line 1585 of file PlayerbotAI.h.
CombatStyle
enum PlayerbotAI::CombatStyle
Enumerator
COMBAT_MELEE
COMBAT_RANGED
Definition at line 1577 of file PlayerbotAI.h.
CombatTargetType
enum PlayerbotAI::CombatTargetType
Enumerator
TARGET_NORMAL
TARGET_THREATEN
Definition at line 1612 of file PlayerbotAI.h.
HELPERLINKABLES
enum PlayerbotAI::HELPERLINKABLES
Enumerator
HL_NONE
HL_PROFESSION
HL_ITEM
HL_TALENT
HL_SKILL
HL_OPTION
HL_PETAGGRO
HL_QUEST
HL_GAMEOBJECT
HL_SPELL
HL_TARGET
HL_NAME
HL_AUCTION
HL_MAIL
HL_RECIPE
Definition at line 1704 of file PlayerbotAI.h.
MovementOrderType
enum PlayerbotAI::MovementOrderType
Enumerator
MOVEMENT_NONE
MOVEMENT_FOLLOW
MOVEMENT_STAY
Definition at line 1642 of file PlayerbotAI.h.
ScenarioType
enum PlayerbotAI::ScenarioType
Enumerator
SCENARIO_PVE
SCENARIO_PVE_ELITE
SCENARIO_PVE_RAID
SCENARIO_PVP_DUEL
SCENARIO_PVP_BG
SCENARIO_PVP_ARENA
SCENARIO_PVP_OPENWORLD
Definition at line 1566 of file PlayerbotAI.h.
TaskFlags
enum PlayerbotAI::TaskFlags
Enumerator
NONE
SELL_ITEMS
BUY_ITEMS
REPAIR_ITEMS
ADD_AUCTION
REMOVE_AUCTION
RESET_TALENTS
BANK_WITHDRAW
BANK_DEPOSIT
LIST_QUEST
END_QUEST
TAKE_QUEST
Definition at line 1649 of file PlayerbotAI.h.
Constructor & Destructor Documentation
PlayerbotAI()
PlayerbotAI::PlayerbotAI (PlayerbotMgr & mgr, Player *const bot, bool debugWhisper)
Definition at line 90 of file PlayerbotAI.cpp.
References BotDataRestore(), BOTSTATE_LOADING, ClearActiveTalentSpec(), COLLECT_FLAG_COMBAT, COLLECT_FLAG_LOOT, COLLECT_FLAG_NEAROBJECT, COLLECT_FLAG_PROFESSION, COLLECT_FLAG_QUEST, COLLECT_FLAG_SKIN, CurrentTime(), DistOverRide, FOLLOWAUTOGO_OFF, GetMaster(), gTempDist, gTempDist2, Player::HasSkill(), IsUpOrDown, m_AutoEquipToggle, m_bot, m_botState, m_collectDist, m_collectionFlags, PlayerbotMgr::m_confCollectCombat, PlayerbotMgr::m_confCollectDistance, PlayerbotMgr::m_confCollectLoot, PlayerbotMgr::m_confCollectObjects, PlayerbotMgr::m_confCollectProfession, PlayerbotMgr::m_confCollectQuest, PlayerbotMgr::m_confCollectSkin, m_DelayAttackInit, m_dropWhite, m_mgr, m_targetAssist, m_targetChanged, m_targetCombat, m_targetProtect, m_targetType, MOVEMENT_FOLLOW, ReloadAI(), SetCollectFlag(), SetMovementOrder(), SetQuestNeedCreatures(), SetQuestNeedItems(), SKILL_SKINNING, and TARGET_NORMAL.
~PlayerbotAI()
PlayerbotAI::~PlayerbotAI () virtual
Definition at line 148 of file PlayerbotAI.cpp.
References m_classAI.
Member Function Documentation
_doSellItem()
void PlayerbotAI::_doSellItem (Item *const item, std::ostringstream & report, std::ostringstream & canSell, uint32 & TotalCost, uint32 & TotalSold) private
Definition at line 8143 of file PlayerbotAI.cpp.
References Player::AddItemToBuyBackSlot(), Item::CanBeTraded(), Cash(), ItemPrototype::Class, ItemPrototype::FoodType, PlayerbotMgr::gConfigSellLevelDiff, Item::GetBagSlot(), Item::GetCount(), Unit::GetLevel(), Item::GetProto(), Item::GetSlot(), Item::GetSpellCharges(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_UNCOMMON, ITEM_SUBCLASS_FOOD, ITEM_SUBCLASS_QUEST, ITEM_SUBCLASS_WEAPON_MISC, m_bot, m_mgr, MakeItemLink(), MAX_ITEM_PROTO_SPELLS, Player::ModifyMoney(), Player::MoveItemFromInventory(), ItemPrototype::Quality, ItemPrototype::RequiredLevel, ItemPrototype::SellPrice, SellWhite, _Spell::SpellCharges, ItemPrototype::Spells, and ItemPrototype::SubClass.
Referenced by SellGarbage().
_findItemSlot()
uint8 PlayerbotAI::_findItemSlot (Item * target)
Definition at line 5727 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_START, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, ItemPrototype::ItemId, and m_bot.
Referenced by _HandleCommandUse().
_HandleCommandAttack()
void PlayerbotAI::_HandleCommandAttack (std::string & text, Player & fromPlayer) private
Definition at line 9509 of file PlayerbotAI.cpp.
References Attack(), Unit::CanAttack(), DoTeleport(), EMOTE_ONESHOT_TALK, Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), Unit::HandleEmoteCommand(), WorldObject::IsWithinLOSInMap(), m_bot, m_followTarget, and SendWhisper().
Referenced by HandleCommand().
_HandleCommandAuction()
void PlayerbotAI::_HandleCommandAuction (std::string & text, Player & fromPlayer) private
Definition at line 9865 of file PlayerbotAI.cpp.
References ADD_AUCTION, extractAuctionIds(), ExtractCommand(), extractItemIds(), FollowAutoReset(), m_findNPC, m_tasks, REMOVE_AUCTION, SendWhisper(), and UNIT_NPC_FLAG_AUCTIONEER.
Referenced by HandleCommand().
_HandleCommandBank()
void PlayerbotAI::_HandleCommandBank (std::string & text, Player & fromPlayer) private
Definition at line 10183 of file PlayerbotAI.cpp.
References BANK_DEPOSIT, BANK_WITHDRAW, ExtractCommand(), extractItemIds(), FollowAutoReset(), m_findNPC, m_tasks, SendWhisper(), and UNIT_NPC_FLAG_BANKER.
Referenced by HandleCommand().
_HandleCommandBuy()
void PlayerbotAI::_HandleCommandBuy (std::string & text, Player & fromPlayer) private
Definition at line 9776 of file PlayerbotAI.cpp.
References BUY_ITEMS, extractItemIds(), FollowAutoReset(), m_findNPC, m_tasks, SendWhisper(), and VENDOR_MASK.
Referenced by HandleCommand().
_HandleCommandCast()
void PlayerbotAI::_HandleCommandCast (std::string & text, Player & fromPlayer) private
Definition at line 9705 of file PlayerbotAI.cpp.
References extractSpellId(), Object::GetObjectGuid(), Player::GetSelectionGuid(), getSpellId(), Unit::HasAura(), Player::HasSpell(), m_bot, m_spellIdCommand, m_targetGuidCommand, Unit::RemoveAurasByCasterSpell(), and SendWhisper().
Referenced by HandleCommand().
_HandleCommandCollect()
void PlayerbotAI::_HandleCommandCollect (std::string & text, Player & fromPlayer) private
Definition at line 10568 of file PlayerbotAI.cpp.
References COLLECT_FLAG_COMBAT, COLLECT_FLAG_LOOT, COLLECT_FLAG_NEAROBJECT, COLLECT_FLAG_PROFESSION, COLLECT_FLAG_QUEST, COLLECT_FLAG_SKIN, ExtractCommand(), ObjectMgr::GetGameObjectInfo(), HasCollectFlag(), Player::HasSkill(), m_bot, m_collectDist, m_collectionFlags, m_collectObjects, PlayerbotMgr::m_confCollectDistanceMax, m_mgr, GameObjectInfo::name, SendWhisper(), SetCollectFlag(), and SKILL_SKINNING.
Referenced by HandleCommand().
_HandleCommandCraft()
void PlayerbotAI::_HandleCommandCraft (std::string & text, Player & fromPlayer) private
Definition at line 10769 of file PlayerbotAI.cpp.
References BOTSTATE_DELAYED, SkillLineEntry::categoryId, Spell::CheckCast(), SkillLineAbilityEntry::classmask, DEBUG_LOG, SpellEntry::Effect, EFFECT_INDEX_0, ExtractCommand(), extractSpellId(), SkillLineAbilityEntry::forward_spellid, Unit::getClassMask(), GetSpellCharges(), Player::HasSkill(), Player::HasSpell(), HasTool(), IsPrimaryProfessionSkill(), SQLStorage::LookupEntry(), m_bot, m_CraftSpellId, m_noToolList, m_spellsToLearn, MakeSpellLink(), Spell::SendCastResult(), ChatHandler::SendSysMessage(), SendWhisper(), SetIgnoreUpdateTime(), SetState(), SKILL_ALCHEMY, SKILL_BLACKSMITHING, SKILL_CATEGORY_PROFESSION, SKILL_CATEGORY_SECONDARY, SKILL_COOKING, SKILL_ENCHANTING, SKILL_ENGINEERING, SKILL_FIRST_AID, SKILL_INSCRIPTION, SKILL_JEWELCRAFTING, SKILL_LEATHERWORKING, SKILL_MINING, SKILL_TAILORING, SkillLineAbilityEntry::skillId, SPELL_CAST_OK, SPELL_EFFECT_CREATE_ITEM, SkillLineAbilityEntry::spellId, Spell::SpellStart(), sSkillLineAbilityStore, sSkillLineStore, and sSpellTemplate.
Referenced by HandleCommand().
_HandleCommandDrop()
void PlayerbotAI::_HandleCommandDrop (std::string & text, Player & fromPlayer) private
Definition at line 9795 of file PlayerbotAI.cpp.
References DropItem(), ExtractCommand(), extractItemIds(), m_dropWhite, and SendWhisper().
Referenced by HandleCommand().
_HandleCommandEnchant()
void PlayerbotAI::_HandleCommandEnchant (std::string & text, Player & fromPlayer) private
Definition at line 10672 of file PlayerbotAI.cpp.
References BOTSTATE_DELAYED, SkillLineEntry::categoryId, SkillLineAbilityEntry::classmask, SpellEntry::Effect, EFFECT_INDEX_0, extractItemIds(), extractSpellId(), findItemsInEquip(), findItemsInInv(), SkillLineAbilityEntry::forward_spellid, Unit::getClassMask(), GetSpellCharges(), Player::HasSkill(), Player::HasSpell(), HasTool(), IsPrimaryProfessionSkill(), SQLStorage::LookupEntry(), m_bot, m_noToolList, m_spellsToLearn, MakeSpellLink(), ChatHandler::SendSysMessage(), SendWhisper(), SetIgnoreUpdateTime(), SpellCastTargets::setItemTarget(), SetState(), SKILL_CATEGORY_PROFESSION, SKILL_ENCHANTING, SkillLineAbilityEntry::skillId, SPELL_EFFECT_ENCHANT_ITEM, SkillLineAbilityEntry::spellId, Spell::SpellStart(), sSkillLineAbilityStore, sSkillLineStore, and sSpellTemplate.
Referenced by HandleCommand().
_HandleCommandEquip()
void PlayerbotAI::_HandleCommandEquip (std::string & text, Player & fromPlayer) private
Definition at line 10442 of file PlayerbotAI.cpp.
References AutoUpgradeEquipment(), CharacterDatabase, Database::DirectPExecute(), EquipItem(), ExtractCommand(), extractItemIds(), findItemsInInv(), Object::GetGUIDLow(), InspectUpdate(), m_AutoEquipToggle, m_bot, SendNotEquipList(), and SendWhisper().
Referenced by HandleCommand().
_HandleCommandFind()
void PlayerbotAI::_HandleCommandFind (std::string & text, Player & fromPlayer) private
Definition at line 10503 of file PlayerbotAI.cpp.
References extractGOinfo(), FORCED_MOVEMENT_RUN, Map::GetGameObject(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_bot, m_lootCurrent, m_lootTargets, MOVEMENT_STAY, MotionMaster::MovePoint(), SendWhisper(), and SetMovementOrder().
Referenced by HandleCommand().
_HandleCommandFollow()
void PlayerbotAI::_HandleCommandFollow (std::string & text, Player & fromPlayer) private
Definition at line 9393 of file PlayerbotAI.cpp.
References CharacterDatabase, Database::DirectPExecute(), DistOverRide, ExtractCommand(), FOLLOWAUTOGO_INIT, FOLLOWAUTOGO_OFF, FOLLOWAUTOGO_SET, WorldObject::GetDistance(), Object::GetGUIDLow(), GetMaster(), gTempDist, gTempDist2, IsUpOrDown, m_bot, MOVEMENT_FOLLOW, SendWhisper(), and SetMovementOrder().
Referenced by HandleCommand().
_HandleCommandGet()
void PlayerbotAI::_HandleCommandGet (std::string & text, Player & fromPlayer) private
Definition at line 10531 of file PlayerbotAI.cpp.
References BOTSTATE_LOOTING, EMOTE_ONESHOT_TALK, extractGOinfo(), Map::GetCreature(), Creature::GetCreatureInfo(), WorldObject::GetMap(), CreatureInfo::GetRequiredLootSkill(), Player::GetSelectionGuid(), Unit::HandleEmoteCommand(), Object::HasFlag(), Player::HasSkill(), m_bot, m_lootTargets, SendWhisper(), SetState(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
Referenced by HandleCommand().
_HandleCommandGM()
void PlayerbotAI::_HandleCommandGM (std::string & text, Player & fromPlayer) private
Definition at line 11891 of file PlayerbotAI.cpp.
References CharacterDatabase, DEBUG_LOG, Database::DirectPExecute(), ExtractCommand(), extractQuestIds(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), m_attackerInfo, m_bDebugCommandChat, m_bot, m_lootTargets, MakeQuestLink(), Database::PQuery(), SEC_PLAYER, ChatHandler::SendSysMessage(), SendWhisper(), sObjectMgr, and TalentSpecDBContainsError().
Referenced by HandleCommand().
_HandleCommandHelp() [1/2]
void PlayerbotAI::_HandleCommandHelp (const char * szText, Player & fromPlayer) inline private
Definition at line 2058 of file PlayerbotAI.h.
References _HandleCommandHelp().
Referenced by _HandleCommandHelp().
_HandleCommandHelp() [2/2]
void PlayerbotAI::_HandleCommandHelp (std::string & text, Player & fromPlayer) private
Definition at line 12029 of file PlayerbotAI.cpp.
References _HandleCommandHelpHelper(), ExtractCommand(), WorldSession::GetSecurity(), Player::GetSession(), HL_AUCTION, HL_GAMEOBJECT, HL_ITEM, HL_MAIL, HL_NAME, HL_NONE, HL_OPTION, HL_PETAGGRO, HL_PROFESSION, HL_QUEST, HL_RECIPE, HL_SKILL, HL_SPELL, HL_TALENT, HL_TARGET, SEC_PLAYER, ChatHandler::SendSysMessage(), and SendWhisper().
Referenced by _HandleCommandPet(), and HandleCommand().
_HandleCommandHelpHelper()
std::string PlayerbotAI::_HandleCommandHelpHelper (std::string sCommand, std::string sExplain, HELPERLINKABLES reqLink = HL_NONE, bool bReqLinkMultiples = false, bool bCommandShort = false) private
Definition at line 12611 of file PlayerbotAI.cpp.
References DEBUG_LOG, HL_AUCTION, HL_GAMEOBJECT, HL_ITEM, HL_MAIL, HL_NAME, HL_NONE, HL_OPTION, HL_PETAGGRO, HL_PROFESSION, HL_QUEST, HL_RECIPE, HL_SKILL, HL_SPELL, HL_TALENT, and HL_TARGET.
Referenced by _HandleCommandHelp().
_HandleCommandMail()
void PlayerbotAI::_HandleCommandMail (std::string & text, Player & fromPlayer) private
Definition at line 9890 of file PlayerbotAI.cpp.
References Announce(), AuctionResult(), Database::BeginTransaction(), Player::CanStoreItem(), CANT_USE_TOO_FAR, Cash(), CharacterDatabase, Mail::COD, Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, CurrentTime(), Mail::deliver_time, EQUIP_ERR_OK, ExtractCommand(), extractGOinfo(), extractMailIds(), GAMEOBJECT_TYPE_MAILBOX, WorldSession::GetAccountId(), Item::GetCount(), Object::GetEntry(), Player::GetGameObjectIfCanInteractWith(), Object::GetGUIDLow(), Player::GetMail(), GetMaster(), Player::GetMItem(), Player::GetMoney(), WorldObject::GetName(), Item::GetProto(), Player::GetSession(), Mail::HasItems(), HIGHGUID_PLAYER, Mail::items, LANG_UNKNOWN, m_bot, m_lootTargets, Player::m_mailsUpdated, MAIL_AUCTION, MAIL_CALENDAR, MAIL_CHECK_MASK_COD_PAYMENT, MAIL_CREATURE, MAIL_DELETED, MAIL_ERR_EQUIP_ERROR, MAIL_ERR_INTERNAL_ERROR, MAIL_ERR_NOT_ENOUGH_MONEY, MAIL_GAMEOBJECT, MAIL_ITEM_TAKEN, MAIL_MONEY_TAKEN, MAIL_NORMAL, MAIL_OK, MAIL_STATE_CHANGED, MAIL_STATE_DELETED, MakeItemLink(), Player::ModifyMoney(), Mail::money, Player::MoveItemToInventory(), ItemPrototype::Name1, NULL_BAG, NULL_SLOT, Database::PExecute(), Mail::removedItems, Mail::RemoveItem(), Player::RemoveMail(), Player::RemoveMItem(), SEC_PLAYER, Mail::sender, Player::SendMailResult(), MailDraft::SendMailTo(), ChatHandler::SendSysMessage(), MailDraft::SetMoney(), sLog, sObjectMgr, Mail::state, Mail::subject, sWorld, and TellMaster().
Referenced by HandleCommand().
_HandleCommandNeutralize()
void PlayerbotAI::_HandleCommandNeutralize (std::string & text, Player & fromPlayer) private
Definition at line 9649 of file PlayerbotAI.cpp.
References Unit::CanAssist(), CastNeutralize(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), IsNeutralized(), WorldObject::IsWithinLOSInMap(), m_bot, m_targetGuidCommand, SendWhisper(), and Player::SetSelectionGuid().
Referenced by HandleCommand().
_HandleCommandOrders()
void PlayerbotAI::_HandleCommandOrders (std::string & text, Player & fromPlayer) private
Definition at line 9324 of file PlayerbotAI.cpp.
References CharacterDatabase, CombatOrderRestore(), Database::DirectPExecute(), ExtractCommand(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), GetMaster(), Object::GetObjectGuid(), ObjectGuid::GetRawValue(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), m_bot, m_DelayAttack, ORDERS_ASSIST, ORDERS_PROTECT, Database::PQuery(), SendOrders(), SendWhisper(), ObjectGuid::Set(), SetCombatOrder(), SetCombatOrderByStr(), sObjectMgr, and TellMaster().
Referenced by HandleCommand().
_HandleCommandPet()
void PlayerbotAI::_HandleCommandPet (std::string & text, Player & fromPlayer) private
Definition at line 11174 of file PlayerbotAI.cpp.
References _HandleCommandHelp(), ACT_ENABLED, Pet::AI(), ASPECT_OF_THE_MONKEY, BOTSTATE_TAME, CastPetSpell(), CastSpell(), CMSG_PET_ABANDON, EFFECT_INDEX_0, ExtractCommand(), extractSpellId(), GetMaster(), Object::GetObjectGuid(), Unit::GetPet(), Unit::GetPetGuid(), getPetSpellId(), UnitAI::GetReactState(), Player::GetSelectionGuid(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), ObjectAccessor::GetUnit(), Unit::HasAura(), Pet::HasSpell(), Player::HasSpell(), IsPassiveSpell(), IsPositiveSpell(), SQLStorage::LookupEntry(), m_bot, Pet::m_spells, m_targetGuidCommand, PETSPELL_REMOVED, WorldSession::QueuePacket(), REACT_AGGRESSIVE, REACT_DEFENSIVE, REACT_PASSIVE, Unit::RemoveAurasByCasterSpell(), ChatHandler::SendSysMessage(), SendWhisper(), UnitAI::SetReactState(), SetState(), SpellEntry::SpellName, sSpellTemplate, TAME_BEAST_1, and Pet::ToggleAutocast().
Referenced by HandleCommand().
_HandleCommandProcess()
void PlayerbotAI::_HandleCommandProcess (std::string & text, Player & fromPlayer) private
Definition at line 10323 of file PlayerbotAI.cpp.
References DISENCHANTING_1, ExtractCommand(), extractItemIds(), findItemsInInv(), Item::GetProto(), Player::GetSkillValuePure(), Player::HasSkill(), ItemPrototype::ItemId, SQLStorage::LookupEntry(), m_bot, m_itemTarget, MILLING_1, PROSPECTING_1, SendWhisper(), SpellCastTargets::setItemTarget(), SKILL_ENCHANTING, SKILL_INSCRIPTION, SKILL_JEWELCRAFTING, Spell::SpellStart(), and sSpellTemplate.
Referenced by HandleCommand().
_HandleCommandPull()
void PlayerbotAI::_HandleCommandPull (std::string & text, Player & fromPlayer) private
Definition at line 9537 of file PlayerbotAI.cpp.
References Unit::CanAssist(), CanPull(), CastPull(), ExtractCommand(), GetCombatTarget(), GetCurrentTarget(), Player::GetGroup(), Group::GetMemberSlots(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), GroupHoTOnTank(), WorldObject::IsWithinLOSInMap(), m_bot, ORDERS_TEMP_WAIT_TANKAGGRO, SendWhisper(), SetGroupCombatOrder(), SetGroupIgnoreUpdateTime(), Player::SetSelectionGuid(), and sObjectMgr.
Referenced by HandleCommand().
_HandleCommandQuest()
void PlayerbotAI::_HandleCommandQuest (std::string & text, Player & fromPlayer) private
Definition at line 10974 of file PlayerbotAI.cpp.
References Player::CanStoreNewItem(), Player::CastedCreatureOrGO(), CharacterDatabase, Player::CompleteQuest(), PlayerbotChatHandler::dropQuest(), END_QUEST, EQUIP_ERR_OK, ExtractCommand(), extractQuestIds(), FindItem(), FollowAutoReset(), ObjectMgr::GetCreatureTemplate(), Player::GetGroup(), Player::GetItemCount(), GetMaster(), Group::GetMemberSlots(), WorldObject::GetName(), Object::GetObjectGuid(), Item::GetProto(), Player::GetQuestSlotQuestId(), Player::GetQuestStatus(), Quest::GetRepObjectiveFaction(), Quest::GetRepObjectiveValue(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), Quest::GetRewOrReqMoney(), Quest::GetSrcItemId(), gQuestFetch, Player::KilledMonster(), LIST_QUEST, m_bot, m_findNPC, m_tasks, MakeItemLink(), MakeQuestLink(), MAX_QUEST_LOG_SIZE, Player::ModifyMoney(), NULL_BAG, NULL_SLOT, Database::PQuery(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, Quest::ReqCreatureOrGOCount, Quest::ReqCreatureOrGOId, Quest::ReqItemCount, Quest::ReqItemId, Quest::ReqSpell, Player::SendNewItem(), SendQuestNeedList(), ChatHandler::SendSysMessage(), SendWhisper(), SetQuestNeedCreatures(), SetQuestNeedItems(), ReputationMgr::SetReputation(), Player::SetSelectionGuid(), sFactionStore, sObjectMgr, Player::StoreNewItem(), PlayerbotChatHandler::sysmessage(), TAKE_QUEST, and UNIT_NPC_FLAG_QUESTGIVER.
Referenced by HandleCommand().
_HandleCommandRepair()
void PlayerbotAI::_HandleCommandRepair (std::string & text, Player & fromPlayer) private
Definition at line 9836 of file PlayerbotAI.cpp.
References ExtractCommand(), extractItemIds(), FollowAutoReset(), m_findNPC, m_tasks, REPAIR_ITEMS, SendWhisper(), and UNIT_NPC_FLAG_REPAIR.
Referenced by HandleCommand().
_HandleCommandReset()
void PlayerbotAI::_HandleCommandReset (std::string & text, Player & fromPlayer) private
Definition at line 9306 of file PlayerbotAI.cpp.
References BOTSTATE_NORMAL, ClearActiveTalentSpec(), m_lootCurrent, m_lootTargets, m_targetCombat, MovementReset(), SendWhisper(), SetQuestNeedCreatures(), SetQuestNeedItems(), SetState(), and UpdateAttackerInfo().
Referenced by HandleCommand().
_HandleCommandSell()
void PlayerbotAI::_HandleCommandSell (std::string & text, Player & fromPlayer) private
Definition at line 9745 of file PlayerbotAI.cpp.
References ExtractCommand(), extractItemIds(), FollowAutoReset(), m_findNPC, m_tasks, SELL_ITEMS, SellWhite, SendWhisper(), and VENDOR_MASK.
Referenced by HandleCommand().
_HandleCommandSkill()
void PlayerbotAI::_HandleCommandSkill (std::string & text, Player & fromPlayer) private
Definition at line 11519 of file PlayerbotAI.cpp.
References _HandleCommandSkillLearnHelper(), Announce(), CANT_AFFORD, Cash(), SkillLineEntry::categoryId, SpellEntry::Effect, ExtractCommand(), extractSpellIdList(), TrainerSpellData::Find(), SkillLineAbilityEntry::forward_spellid, Map::GetCreature(), WorldObject::GetMap(), GetMaster(), Player::GetMoney(), Object::GetObjectGuid(), GetPlayer(), Player::GetReputationPriceDiscount(), Player::GetSelectionGuid(), Player::GetSession(), Player::GetSkillValue(), Creature::GetTrainerSpells(), Player::GetTrainerSpellState(), Creature::GetTrainerTemplateSpells(), ObjectAccessor::GetUnit(), Player::HasSpell(), WorldPacket::Initialize(), IsPrimaryProfessionSkill(), TrainerSpell::isProvidedReqLevel, Player::IsSpellFitByClassAndRace(), Unit::isTrainer(), Creature::IsTrainerOf(), TrainerSpell::learnedSpell, SkillLineAbilityEntry::learnOnGetSkill, SQLStorage::LookupEntry(), m_bot, m_spellsToLearn, MakeSpellLink(), MakeWeaponSkillLink(), ReloadAI(), TrainerSpell::reqLevel, WorldSession::SendPacket(), SendWhisper(), Player::SetSkill(), SpellLearnSkillNode::skill, SKILL_CATEGORY_WEAPON, SkillLineAbilityEntry::skillId, SMSG_PLAY_SPELL_IMPACT, SMSG_PLAY_SPELL_VISUAL, SMSG_TRAINER_BUY_SUCCEEDED, TrainerSpell::spell, SPELL_EFFECT_WEAPON, TrainerSpell::spellCost, SkillLineAbilityEntry::spellId, TrainerSpellData::spellList, sSkillLineAbilityStore, sSkillLineStore, sSpellMgr, sSpellTemplate, and TRAINER_SPELL_GREEN.
Referenced by HandleCommand().
_HandleCommandSkillLearnHelper()
bool PlayerbotAI::_HandleCommandSkillLearnHelper (TrainerSpell const * tSpell, uint32 spellId, uint32 cost) private
Definition at line 11833 of file PlayerbotAI.cpp.
References Announce(), CANT_AFFORD, Player::GetMoney(), Player::GetTrainerSpellState(), Player::HasSpell(), TrainerSpell::isProvidedReqLevel, Player::IsSpellFitByClassAndRace(), TrainerSpell::learnedSpell, Player::learnSpell(), m_bot, Player::ModifyMoney(), TrainerSpell::reqLevel, sSpellMgr, and TRAINER_SPELL_GREEN.
Referenced by _HandleCommandSkill().
_HandleCommandSpells()
void PlayerbotAI::_HandleCommandSpells (std::string & text, Player & fromPlayer) private
Definition at line 11368 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), Player::GetSpellMap(), IsPassiveSpell(), IsPositiveSpell(), IsProfessionOrRidingSkill(), SQLStorage::LookupEntry(), m_bot, PLAYERSPELL_REMOVED, ChatHandler::SendSysMessage(), SendWhisper(), SpellEntry::SpellName, sSpellMgr, and sSpellTemplate.
Referenced by HandleCommand().
_HandleCommandStats()
void PlayerbotAI::_HandleCommandStats (std::string & text, Player & fromPlayer) private
Definition at line 11866 of file PlayerbotAI.cpp.
References Cash(), EstRepairAll(), GetFreeBagSpace(), Player::GetMoney(), WorldObject::GetName(), m_bot, ChatHandler::SendSysMessage(), and SendWhisper().
Referenced by HandleCommand().
_HandleCommandStay()
void PlayerbotAI::_HandleCommandStay (std::string & text, Player & fromPlayer) private
Definition at line 9499 of file PlayerbotAI.cpp.
References MOVEMENT_STAY, SendWhisper(), and SetMovementOrder().
Referenced by HandleCommand().
_HandleCommandSurvey()
void PlayerbotAI::_HandleCommandSurvey (std::string & text, Player & fromPlayer) private
Definition at line 11457 of file PlayerbotAI.cpp.
References QueryResult::Fetch(), Map::GetGameObject(), GameObject::GetGOInfo(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Field::GetUInt32(), HIGHGUID_GAMEOBJECT, GameObject::IsSpawned(), m_bot, GameObjectInfo::name, QueryResult::NextRow(), Database::PQuery(), SendWhisper(), sGameEventMgr, and WorldDatabase.
Referenced by HandleCommand().
_HandleCommandTalent()
void PlayerbotAI::_HandleCommandTalent (std::string & text, Player & fromPlayer) private
Definition at line 10214 of file PlayerbotAI.cpp.
References ApplyActiveTalentSpec(), ClearActiveTalentSpec(), DEBUG_LOG, ExtractCommand(), extractTalentIds(), FollowAutoReset(), Unit::getClass(), GetTalentSpec(), GetTalentSpecs(), GetTalentSpecsAmount(), InspectUpdate(), Player::LearnTalent(), m_bot, m_findNPC, m_tasks, RESET_TALENTS, Player::resetTalentsCost(), Player::SendTalentsInfoData(), SendWhisper(), SetActiveTalentSpec(), TalentSpec::specClass, TalentSpec::specName, TalentSpec::specPurpose, TSP_NONE, and UNIT_NPC_FLAG_TRAINER_CLASS.
Referenced by HandleCommand().
_HandleCommandUse()
void PlayerbotAI::_HandleCommandUse (std::string & text, Player & fromPlayer) private
Definition at line 10388 of file PlayerbotAI.cpp.
References _findItemSlot(), BOTSTATE_DELAYED, extractGOinfo(), extractItemIds(), findItemsInEquip(), findItemsInInv(), Map::GetGameObject(), WorldObject::GetMap(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), m_bot, m_lootTargets, SendWhisper(), SetIgnoreUpdateTime(), SetState(), TARGET_FLAG_GAMEOBJECT, and UseItem().
Referenced by HandleCommand().
AcceptQuest()
void PlayerbotAI::AcceptQuest (Quest const * qInfo, Player * pGiver)
Definition at line 4151 of file PlayerbotAI.cpp.
References Player::AddQuest(), Player::CanAddQuest(), Player::CanCompleteQuest(), Player::CanShareQuest(), Player::CanTakeQuest(), Unit::CastSpell(), Player::ClearDividerGuid(), Player::CompleteQuest(), Player::GetDividerGuid(), Quest::GetQuestId(), Quest::GetSrcSpell(), m_bot, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_PARTY_MSG_ACCEPT_QUEST, Quest::ReqCreatureOrGOCount, Quest::ReqItemCount, Player::SendPushToPartyResponse(), SetQuestNeedCreatures(), SetQuestNeedItems(), and TRIGGERED_OLD_TRIGGERED.
AddAuction()
void PlayerbotAI::AddAuction (const uint32 itemid, Creature * aCreature)
Definition at line 8678 of file PlayerbotAI.cpp.
References ItemPrototype::BuyPrice, CMSG_AUCTION_SELL_ITEM, CurrentTime(), FindItem(), Item::GetCount(), Creature::GetCreatureInfo(), Object::GetObjectGuid(), Item::GetProto(), Player::GetSession(), m_bot, MakeItemLink(), CreatureInfo::Name, ItemPrototype::Quality, WorldSession::QueuePacket(), ItemPrototype::SellPrice, TellMaster(), and urand().
Referenced by findNearbyCreature().
AddQuest()
bool PlayerbotAI::AddQuest (const uint32 entry, WorldObject * questgiver)
Definition at line 8557 of file PlayerbotAI.cpp.
References Player::AddQuest(), Player::CanAddQuest(), Player::CanCompleteQuest(), Player::CanTakeQuest(), Player::CompleteQuest(), GetMaster(), Player::GetQuestStatus(), LANG_COMMAND_QUEST_NOTFOUND, m_bot, MakeQuestLink(), ChatHandler::PSendSysMessage(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_COMPLETE, Quest::ReqCreatureOrGOCount, Quest::ReqItemCount, Player::SatisfyQuestLog(), Player::SatisfyQuestStatus(), SetQuestNeedCreatures(), SetQuestNeedItems(), sObjectMgr, and TellMaster().
Referenced by CastSpell(), findNearbyCreature(), and ListQuests().
Announce()
void PlayerbotAI::Announce (AnnounceFlags msg)
Definition at line 4923 of file PlayerbotAI.cpp.
References CANT_AFFORD, CANT_USE_TOO_FAR, GENDER_MALE, Unit::getGender(), Unit::getRace(), INVENTORY_FULL, m_bot, PlaySound(), RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, and RACE_UNDEAD.
Referenced by _HandleCommandMail(), _HandleCommandSkill(), _HandleCommandSkillLearnHelper(), and HandleBotOutgoingPacket().
ApplyActiveTalentSpec()
bool PlayerbotAI::ApplyActiveTalentSpec ()
ApplyActiveTalentSpec takes the active talent spec and attempts to apply it.
return true -> ok, talentspec applied as fully as possible return false -> talentspec was not or only partially applied
Definition at line 6556 of file PlayerbotAI.cpp.
References PlayerTalent::currentRank, DEBUG_LOG, Player::GetActiveSpec(), Unit::getClass(), Player::GetFreeTalentPoints(), Player::GetKnownTalentById(), Player::LearnTalent(), m_activeTalentSpec, m_bot, PLAYERSPELL_REMOVED, TalentSpec::specClass, TalentSpec::specPurpose, PlayerTalent::state, PlayerTalent::talentEntry, TalentSpec::talentId, TalentEntry::TalentID, TellMaster(), and TSP_NONE.
Referenced by _HandleCommandTalent(), and GiveLevel().
Attack()
void PlayerbotAI::Attack (Unit * forcedTarget = nullptr)
Definition at line 3112 of file PlayerbotAI.cpp.
References Unit::Attack(), BOTSTATE_COMBAT, COLLECT_FLAG_COMBAT, CurrentTime(), GetCombatTarget(), Object::GetObjectGuid(), HasCollectFlag(), m_bot, m_botState, m_DelayAttackInit, m_lootTargets, m_targetCombat, and SetState().
Referenced by _HandleCommandAttack(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), DoNextCombatManeuver(), and PlayerbotWarriorAI::Pull().
AuctionResult()
std::string PlayerbotAI::AuctionResult (std::string subject, std::string body)
Definition at line 8437 of file PlayerbotAI.cpp.
References AUCTION_CANCELED, AUCTION_CANCELLED_TO_BIDDER, AUCTION_EXPIRED, AUCTION_OUTBIDDED, AUCTION_SALE_PENDING, AUCTION_SUCCESSFUL, AUCTION_WON, Cash(), ObjectMgr::GetItemPrototype(), and ItemPrototype::Name1.
Referenced by _HandleCommandMail().
AutoEquipComparison()
void PlayerbotAI::AutoEquipComparison (Item * pItem, Item * pItem2)
Definition at line 655 of file PlayerbotAI.cpp.
References ItemPrototype::Armor, ItemPrototype::Class, EquipItem(), ItemPrototype::getDPS(), Item::GetProto(), Player::HasSkill(), InspectUpdate(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, ItemPrototype::ItemLevel, ItemStatComparison(), m_bot, MAX_ITEM_SUBCLASS_ARMOR, ItemPrototype::Quality, SKILL_CLOTH, SKILL_LEATHER, SKILL_MAIL, SKILL_PLATE_MAIL, SKILL_SHIELD, ItemPrototype::StatsCount, and ItemPrototype::SubClass.
Referenced by AutoUpgradeEquipment().
AutoUpgradeEquipment()
void PlayerbotAI::AutoUpgradeEquipment ()
Definition at line 536 of file PlayerbotAI.cpp.
References AutoEquipComparison(), Player::CanEquipItem(), Player::CanTakeQuest(), EQUIP_ERR_OK, EquipItem(), ItemPrototype::Flags, Bag::GetBagSize(), Player::GetItemByPos(), GetMaster(), Item::GetProto(), Player::GetQuestStatus(), InspectUpdate(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, Item::IsBag(), ITEM_FLAG_HAS_LOOT, ItemStatComparison(), LANG_UNIVERSAL, m_AutoEquipToggle, m_bot, MAX_ITEM_PROTO_SPELLS, NULL_SLOT, QUEST_STATUS_COMPLETE, QUEST_STATUS_UNAVAILABLE, Player::Say(), sObjectMgr, _Spell::SpellId, ItemPrototype::Spells, ItemPrototype::StartQuest, ItemPrototype::StatsCount, and UseItem().
Referenced by _HandleCommandEquip(), DoLoot(), findNearbyCreature(), HandleBotOutgoingPacket(), TurnInQuests(), and UpdateAI().
BankBalance()
void PlayerbotAI::BankBalance ()
Definition at line 8264 of file PlayerbotAI.cpp.
References BANK_SLOT_BAG_END, BANK_SLOT_BAG_START, BANK_SLOT_ITEM_END, BANK_SLOT_ITEM_START, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, ItemPrototype::ItemId, ItemLocalization(), m_bot, MakeItemLink(), ItemPrototype::Name1, and TellMaster().
Referenced by findNearbyCreature().
BeingRolledOn()
void PlayerbotAI::BeingRolledOn (ObjectGuid target) inline
Definition at line 1942 of file PlayerbotAI.h.
References m_being_rolled_on.
BotDataRestore()
void PlayerbotAI::BotDataRestore ()
BotDataRestore() Restores autoequip - the toggle status for the 'equip auto' command.
Restores gDelayAttack - the other attributes need a valid target. This function is to be called when the targets may or may not be online (such as upon login). See CombatOrderRestore() for full orders restore.
Definition at line 4556 of file PlayerbotAI.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetBool(), Object::GetGUIDLow(), Field::GetUInt8(), m_AutoEquipToggle, m_bot, m_DelayAttack, Database::PQuery(), and sLog.
Referenced by PlayerbotAI().
Buff()
SpellCastResult PlayerbotAI::Buff (uint32 spellId, Unit * target, void(*)(Player *) beforeCast = nullptr)
Definition at line 5650 of file PlayerbotAI.cpp.
References WorldObject::CalculateSpellEffectValue(), CastSpell(), SpellEntry::EffectApplyAuraName, SpellEntry::EffectMiscValue, Unit::GetAurasByType(), Unit::GetLevel(), Unit::HasAura(), SpellEntry::Id, SQLStorage::LookupEntry(), m_bot, MAX_EFFECT_INDEX, SPELL_AURA_NONE, SPELL_FAILED_AURA_BOUNCED, SPELL_FAILED_BAD_IMPLICIT_TARGETS, SPELL_FAILED_NOT_KNOWN, SPELL_NOT_FOUND, sSpellMgr, and sSpellTemplate.
Referenced by PlayerbotDruidAI::BuffHelper(), PlayerbotMageAI::BuffHelper(), PlayerbotPaladinAI::BuffHelper(), and PlayerbotPriestAI::BuffHelper().
Buy()
void PlayerbotAI::Buy (Creature * vendor, const uint32 itemid)
Definition at line 8709 of file PlayerbotAI.cpp.
References ALLIANCE, ItemPrototype::AllowableClass, ItemPrototype::AllowableRace, BIND_WHEN_PICKED_UP, ItemPrototype::Bonding, Player::BuyItemFromVendorSlot(), ItemPrototype::Flags, ItemPrototype::Flags2, Unit::getClassMask(), VendorItemData::GetItem(), VendorItemData::GetItemCount(), ObjectMgr::GetItemPrototype(), Object::GetObjectGuid(), Unit::getRaceMask(), Player::GetReputationRank(), Player::GetTeam(), Creature::GetVendorItems(), Creature::GetVendorTemplateItems(), HORDE, VendorItem::item, ITEM_FLAG2_FACTION_ALLIANCE, ITEM_FLAG2_FACTION_HORDE, ITEM_FLAG_IS_BOUND_TO_ACCOUNT, m_bot, NULL_BAG, NULL_SLOT, ItemPrototype::RequiredReputationFaction, ItemPrototype::RequiredReputationRank, and sObjectMgr.
Referenced by findNearbyCreature().
canObeyCommandFrom()
bool PlayerbotAI::canObeyCommandFrom (const Player & player) const
Definition at line 5393 of file PlayerbotAI.cpp.
References WorldSession::GetAccountId(), GetMaster(), and Player::GetSession().
Referenced by HandleBotOutgoingPacket(), and HandleCommand().
CanPull()
bool PlayerbotAI::CanPull (Player & fromPlayer)
Definition at line 3540 of file PlayerbotAI.cpp.
References GetClassAI(), Player::GetGroup(), IsGroupReady(), IsTank(), m_bot, and SendWhisper().
Referenced by _HandleCommandPull().
CanReachWithSpellAttack()
bool PlayerbotAI::CanReachWithSpellAttack (Unit * target)
Definition at line 158 of file PlayerbotAI.cpp.
References DIST_CALC_COMBAT_REACH_WITH_MELEE, EFFECT_INDEX_0, WorldObject::GetDistance(), SpellEntry::HasAttribute(), Unit::HasAura(), IsPositiveSpell(), SQLStorage::LookupEntry(), m_bot, m_spellRangeMap, SPELL_ATTR_USES_RANGED_SLOT, and sSpellTemplate.
Referenced by DoCombatMovement().
CanReceiveSpecificSpell()
bool PlayerbotAI::CanReceiveSpecificSpell (uint8 spec, Unit * target) const
Definition at line 5714 of file PlayerbotAI.cpp.
References Object::GetObjectGuid(), Unit::GetSpellAuraHolderMap(), GetSpellSpecific(), IsSpellSpecificUniquePerCaster(), and m_bot.
CanStore()
bool PlayerbotAI::CanStore ()
Definition at line 7750 of file PlayerbotAI.cpp.
References ItemPrototype::Class, Bag::GetFreeSlots(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONTAINER, ITEM_SUBCLASS_CONTAINER, m_bot, and ItemPrototype::SubClass.
Referenced by PlayerbotMageAI::DoNonCombatActions(), and PlayerbotWarlockAI::DoNonCombatActions().
Cash()
std::string PlayerbotAI::Cash (uint32 copper)
Definition at line 8506 of file PlayerbotAI.cpp.
Referenced by _doSellItem(), _HandleCommandMail(), _HandleCommandSkill(), _HandleCommandStats(), AuctionResult(), HandleBotOutgoingPacket(), ListAuctions(), Sell(), and SellGarbage().
CastNeutralize()
bool PlayerbotAI::CastNeutralize ()
Definition at line 3626 of file PlayerbotAI.cpp.
References CLASS_DRUID, CREATURE_TYPE_BEAST, CREATURE_TYPE_HUMANOID, Unit::getClass(), GetClassAI(), Object::GetTypeId(), ObjectAccessor::GetUnit(), Unit::HasAuraType(), m_bot, m_spellIdCommand, m_targetGuidCommand, SPELL_AURA_MOD_SHAPESHIFT, and TYPEID_UNIT.
Referenced by _HandleCommandNeutralize().
CastPetSpell()
SpellCastResult PlayerbotAI::CastPetSpell (uint32 spellId, Unit * target = nullptr)
Definition at line 5597 of file PlayerbotAI.cpp.
References Unit::CanAssist(), Unit::CanAttack(), Unit::CastSpell(), Unit::FindCurrentSpellBySpellId(), WorldObject::GetAngle(), Unit::GetPet(), Player::GetSelectionGuid(), ObjectAccessor::GetUnit(), WorldObject::isInFrontInMap(), IsPositiveSpell(), WorldObject::IsSpellReady(), SQLStorage::LookupEntry(), m_bot, Unit::SetFacingTo(), SPELL_CAST_OK, SPELL_FAILED_NO_PET, SPELL_FAILED_NOT_KNOWN, SPELL_FAILED_NOT_READY, SPELL_FAILED_TARGET_FRIENDLY, SPELL_NOT_FOUND, sSpellTemplate, TellMaster(), and TRIGGERED_NONE.
Referenced by _HandleCommandPet(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), and PlayerbotWarlockAI::DoNonCombatActions().
CastPull()
bool PlayerbotAI::CastPull ()
Definition at line 3573 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_PALADIN, CLASS_WARRIOR, Unit::getClass(), GetClassAI(), GetCurrentTarget(), IsTank(), and m_bot.
Referenced by _HandleCommandPull().
CastSpell() [1/3]
SpellCastResult PlayerbotAI::CastSpell (const char * args)
Definition at line 5442 of file PlayerbotAI.cpp.
References getSpellId(), and SPELL_NOT_FOUND.
Referenced by _HandleCommandPet(), Buff(), CastSpell(), PlayerbotClassAI::CastSpellNoRanged(), PlayerbotClassAI::CastSpellWand(), PlayerbotPaladinAI::CheckAuras(), PlayerbotWarlockAI::CheckDemon(), PlayerbotPaladinAI::CheckSeals(), PlayerbotShamanAI::CheckShields(), PlayerbotWarriorAI::CheckShouts(), PlayerbotPaladinAI::DispelPlayer(), PlayerbotShamanAI::DispelPlayer(), PlayerbotRogueAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVP(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), DoLoot(), PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVP(), PlayerbotDruidAI::DoNextCombatManeuverPVP(), PlayerbotHunterAI::DoNextCombatManeuverPVP(), PlayerbotMageAI::DoNextCombatManeuverPVP(), PlayerbotPaladinAI::DoNextCombatManeuverPVP(), PlayerbotShamanAI::DoNextCombatManeuverPVP(), PlayerbotWarlockAI::DoNextCombatManeuverPVP(), PlayerbotWarriorAI::DoNextCombatManeuverPVP(), PlayerbotDeathKnightAI::DoNonCombatActions(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), PlayerbotShamanAI::DropTotems(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), PlayerbotDeathKnightAI::Pull(), PlayerbotPaladinAI::Pull(), PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), PlayerbotShamanAI::ResurrectPlayer(), SelfBuff(), UpdateAI(), and PlayerbotShamanAI::UseCooldowns().
CastSpell() [2/3]
SpellCastResult PlayerbotAI::CastSpell (uint32 spellId)
Definition at line 5457 of file PlayerbotAI.cpp.
References AddQuest(), Unit::CanAssist(), Unit::CanAttack(), SpellEntry::CastingTimeIndex, Unit::CastSpell(), SpellCastTimesEntry::CastTime, CheckBotCast(), Spell::CheckPower(), MotionMaster::Clear(), CMSG_CAST_SPELL, CMSG_GAMEOBJ_REPORT_USE, DEBUG_LOG, SpellEntry::Effect, GAMEOBJECT_TYPE_QUESTGIVER, Map::GetGameObject(), GameObject::GetGoType(), QuestMenu::GetItem(), WorldObject::GetMap(), Unit::GetMotionMaster(), Player::GetPlayerMenu(), PlayerMenu::GetQuestMenu(), Player::GetSelectionGuid(), Player::GetSession(), ObjectAccessor::GetUnit(), In_Range(), IsAutoRepeatRangedSpell(), IsPositiveSpell(), WorldObject::IsSpellReady(), WorldObject::IsWithinLOSInMap(), SQLStorage::LookupEntry(), m_bot, m_CurrentlyCastingSpellId, m_lootCurrent, QuestMenuItem::m_qId, QuestMenu::MenuItemCount(), MotionMaster::MoveIdle(), Player::PrepareQuestMenu(), WorldSession::QueuePacket(), SetIgnoreUpdateTime(), Unit::SetInFront(), SPELL_CAST_OK, SPELL_EFFECT_OPEN_LOCK, SPELL_EFFECT_SKINNING, SPELL_FAILED_BAD_IMPLICIT_TARGETS, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_NOT_KNOWN, SPELL_FAILED_NOT_READY, SPELL_FAILED_OUT_OF_RANGE, SPELL_FAILED_TARGET_FRIENDLY, SPELL_NOT_FOUND, SpellEntry::SpellName, sSpellCastTimesStore, sSpellTemplate, Unit::StopMoving(), TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_UNIT, TellMaster(), TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TurnInQuests(), and ObjectGuid::WriteAsPacked().
CastSpell() [3/3]
SpellCastResult PlayerbotAI::CastSpell (uint32 spellId, Unit & target)
Definition at line 5448 of file PlayerbotAI.cpp.
References CastSpell(), Object::GetObjectGuid(), Player::GetSelectionGuid(), m_bot, and Player::SetSelectionGuid().
CheckBotCast()
SpellCastResult PlayerbotAI::CheckBotCast (const SpellEntry * sInfo)
Definition at line 5420 of file PlayerbotAI.cpp.
References Spell::CheckCast(), Map::GetCreature(), Map::GetGameObject(), WorldObject::GetMap(), ObjectGuid::IsCreature(), ObjectGuid::IsGameObject(), m_bot, m_lootCurrent, Spell::m_targets, SpellCastTargets::setGOTarget(), SpellCastTargets::setUnitTarget(), and SPELL_FAILED_ERROR.
Referenced by CastSpell(), and PlayerbotHunterAI::DoNextCombatManeuverPVE().
ClearActiveTalentSpec()
void PlayerbotAI::ClearActiveTalentSpec () inline
Definition at line 1805 of file PlayerbotAI.h.
References TalentSpec::glyphIdMajor, TalentSpec::glyphIdMinor, m_activeTalentSpec, TalentSpec::specClass, TalentSpec::specName, TalentSpec::specPurpose, TalentSpec::talentId, and TSP_NONE.
Referenced by _HandleCommandReset(), _HandleCommandTalent(), and PlayerbotAI().
ClearCombatOrder()
void PlayerbotAI::ClearCombatOrder (CombatOrderType co)
Definition at line 4758 of file PlayerbotAI.cpp.
References m_combatOrder, ORDERS_ASSIST, ORDERS_HEAL, ORDERS_MAIN_HEAL, ORDERS_MAIN_TANK, ORDERS_NONE, ORDERS_PASSIVE, ORDERS_PRIMARY, ORDERS_RESET, ORDERS_SECONDARY, ORDERS_TANK, and SetCombatOrder().
Referenced by ClearGroupCombatOrder(), DoNextCombatManeuver(), and UpdateAI().
ClearGroupCombatOrder()
void PlayerbotAI::ClearGroupCombatOrder (CombatOrderType co)
Definition at line 3461 of file PlayerbotAI.cpp.
References ClearCombatOrder(), Player::GetGroup(), Group::GetMemberSlots(), m_bot, and sObjectMgr.
Referenced by PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), and PlayerbotWarriorAI::DoFirstCombatManeuver().
CombatOrderRestore()
void PlayerbotAI::CombatOrderRestore ()
CombatOrderRestore() Restores all saved attributes.
This function is to be called when the targets are assumed to be online. Restores m_DelayAttack - the other attributes need a valid target. This function is to be called when the targets
Definition at line 4581 of file PlayerbotAI.cpp.
References CharacterDatabase, DistOverRide, QueryResult::Fetch(), FOLLOWAUTOGO_OFF, Object::GetGUIDLow(), WorldObject::GetMap(), GetMaster(), Field::GetString(), Field::GetUInt8(), ObjectAccessor::GetUnit(), Map::GetWorldObject(), gPrimtarget, gSectarget, gTempDist, gTempDist2, IsUpOrDown, m_bot, m_DelayAttack, MOVEMENT_FOLLOW, ORDERS_PRIMARY, ORDERS_SECONDARY, Database::PQuery(), SetCombatOrder(), SetMovementOrder(), sLog, and TellMaster().
Referenced by _HandleCommandOrders().
CreatureLocalization()
void PlayerbotAI::CreatureLocalization (std::string & creatureName, const uint32 entry) const
Definition at line 8112 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), CreatureLocale::Name, sObjectMgr, and Utf8FitTo().
Referenced by SendQuestNeedList().
CurrentTime()
time_t PlayerbotAI::CurrentTime () inline
Definition at line 1923 of file PlayerbotAI.h.
Referenced by _HandleCommandMail(), AddAuction(), Attack(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), ListAuctions(), PlayerbotAI(), SendOrders(), SetCombatOrder(), PlayerbotClassAI::SetWait(), and UpdateAI().
Deposit()
bool PlayerbotAI::Deposit (const uint32 itemid)
Definition at line 8238 of file PlayerbotAI.cpp.
References Player::BankItem(), Player::CanBankItem(), EQUIP_ERR_OK, FindItem(), Item::GetBagSlot(), Item::GetSlot(), m_bot, MakeItemLink(), NULL_BAG, NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), and TellMaster().
Referenced by findNearbyCreature().
DoCombatMovement()
void PlayerbotAI::DoCombatMovement ()
Definition at line 3330 of file PlayerbotAI.cpp.
References Unit::CanReachWithMeleeAttack(), CanReachWithSpellAttack(), MotionMaster::Clear(), COMBAT_MELEE, COMBAT_RANGED, GetClassAI(), Unit::GetMotionMaster(), Unit::hasUnitState(), IsHealer(), m_bot, m_combatStyle, m_movementOrder, m_targetCombat, MotionMaster::MoveChase(), MOVEMENT_STAY, MovementClear(), and UNIT_STAT_CHASE.
Referenced by DoNextCombatManeuver().
DoFlight()
void PlayerbotAI::DoFlight ()
Definition at line 3788 of file PlayerbotAI.cpp.
References Player::ActivateTaxiPathTo(), DEBUG_LOG, Player::GetNPCIfCanInteractWith(), ObjectGuid::GetString(), m_bot, m_taxiMaster, m_taxiNodes, and UNIT_NPC_FLAG_FLIGHTMASTER.
Referenced by UpdateAI().
DoLoot()
void PlayerbotAI::DoLoot ()
Definition at line 3802 of file PlayerbotAI.cpp.
References AutoUpgradeEquipment(), BOTSTATE_NORMAL, Loot::CanLoot(), CastSpell(), MotionMaster::Clear(), CMSG_LOOT, COLLECT_FLAG_NEAROBJECT, COLLECT_FLAG_SKIN, CONTACT_DISTANCE, DEBUG_LOG, FindBombForLockValue(), FindKeyForLockValue(), FORCED_MOVEMENT_RUN, GAMEOBJECT_TYPE_CHEST, Creature::GetCreatureInfo(), WorldObject::GetDistance(), Object::GetEntry(), GameObject::GetGOInfo(), GameObject::GetGoType(), Player::GetItemByEntry(), Unit::GetLevel(), GameObjectInfo::GetLockId(), WorldObject::GetMap(), WorldObject::GetMapId(), GetMaster(), Unit::GetMotionMaster(), WorldObject::GetName(), WorldObject::GetObjectBoundingRadius(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), CreatureInfo::GetRequiredLootSkill(), Player::GetSession(), Player::GetSkillValue(), Map::GetWorldObject(), HasCollectFlag(), Object::HasFlag(), Player::HasItemCount(), Player::HasSkill(), HasTool(), HERB_GATHERING, LockEntry::Index, INTERACTION_DISTANCE, ObjectGuid::IsAnyTypeCreature(), Creature::IsDespawned(), ObjectGuid::IsEmpty(), ObjectGuid::IsGameObject(), GameObject::IsSpawned(), LOCK_KEY_ITEM, LOCK_KEY_SKILL, LOCKTYPE_CLOSE, LOCKTYPE_OPEN, LOCKTYPE_OPEN_ATTACKING, LOCKTYPE_OPEN_FROM_VEHICLE, LOCKTYPE_OPEN_KNEELING, LOCKTYPE_OPEN_TINKERING, LOCKTYPE_QUICK_CLOSE, LOCKTYPE_QUICK_OPEN, LOCKTYPE_SLOW_CLOSE, LOCKTYPE_SLOW_OPEN, m_being_rolled_on, m_bot, m_collectObjects, PlayerbotMgr::m_confCollectDistanceMax, m_debugWhisper, m_inventory_full, Object::m_loot, m_lootCurrent, m_lootTargets, m_mgr, MINING, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), CreatureInfo::Name, GameObjectInfo::name, PICK_LOCK_1, WorldSession::QueuePacket(), Object::RemoveFlag(), SetIgnoreUpdateTime(), SetState(), LockEntry::Skill, SKILL_BLACKSMITHING, SKILL_ENGINEERING, SKILL_HERBALISM, SKILL_LOCKPICKING, SKILL_MINING, SKILL_NONE, SKILL_SKINNING, SkillByLockType(), SKINNING, sLockStore, SPELL_CAST_OK, TARGET_FLAG_GAMEOBJECT, TC_MINING_PICK, TC_SKINNING_KNIFE, TellMaster(), LockEntry::Type, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, UNIT_FIELD_FLAGS, UNIT_FLAG_LOOTING, UNIT_FLAG_SKINNABLE, and UseItem().
Referenced by UpdateAI().
DoNextCombatManeuver()
void PlayerbotAI::DoNextCombatManeuver ()
Definition at line 3258 of file PlayerbotAI.cpp.
References Attack(), Unit::AttackStop(), Unit::CanAttack(), ClearCombatOrder(), DoCombatMovement(), GetClassAI(), GetCombatOrder(), GetDuelTarget(), GetMaster(), Unit::InterruptNonMeleeSpells(), Unit::IsDead(), WorldObject::IsInMap(), Object::IsInWorld(), m_bot, m_combatOrder, m_ScenarioType, m_targetChanged, m_targetCombat, m_targetType, MovementReset(), ORDERS_PASSIVE, ORDERS_TEMP, ORDERS_TEMP_WAIT_OOC, ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_CONTINUE, RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, RETURN_NO_ACTION_UNKNOWN, SCENARIO_PVP_DUEL, SetQuestNeedCreatures(), Player::SetSelectionGuid(), TARGET_NORMAL, and TellMaster().
Referenced by UpdateAI().
DoTeleport()
bool PlayerbotAI::DoTeleport (WorldObject & obj)
Definition at line 8062 of file PlayerbotAI.cpp.
References GetMaster(), m_attackerInfo, m_bot, m_targetCombat, SetIgnoreUpdateTime(), PlayerbotChatHandler::sysmessage(), and PlayerbotChatHandler::teleport().
Referenced by _HandleCommandAttack(), MovementReset(), and UpdateAI().
DropGarbage()
bool PlayerbotAI::DropGarbage (bool bVerbose)
Definition at line 8871 of file PlayerbotAI.cpp.
References Item::CanBeTraded(), ItemPrototype::Class, DropItem(), ItemPrototype::FoodType, PlayerbotMgr::gConfigSellLevelDiff, Bag::GetBagSize(), Player::GetItemByPos(), Unit::GetLevel(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_UNCOMMON, ITEM_SUBCLASS_FOOD, ITEM_SUBCLASS_QUEST, ITEM_SUBCLASS_WEAPON_MISC, ItemPrototype::ItemId, m_bot, m_dropWhite, m_mgr, ItemPrototype::Quality, ItemPrototype::RequiredLevel, ItemPrototype::SellPrice, ItemPrototype::SubClass, and TellMaster().
Referenced by HandleBotOutgoingPacket().
DropItem()
std::string PlayerbotAI::DropItem (const uint32 itemid)
Definition at line 8960 of file PlayerbotAI.cpp.
References Player::DestroyItem(), FindItem(), Item::GetBagSlot(), Item::GetSlot(), m_bot, and MakeItemText().
Referenced by _HandleCommandDrop(), and DropGarbage().
EquipItem()
void PlayerbotAI::EquipItem (Item * src_Item)
Definition at line 7938 of file PlayerbotAI.cpp.
References Player::AutoUnequipOffhandIfNeed(), Player::CanEquipItem(), Player::CanStoreItem(), Player::CanUnequipItem(), EQUIP_ERR_OK, Player::EquipItem(), Item::GetBagSlot(), Player::GetItemByPos(), Item::GetPos(), Item::GetSlot(), Item::IsBag(), Player::IsInventoryPos(), m_bot, NULL_BAG, NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), and Player::StoreItem().
Referenced by _HandleCommandEquip(), AutoEquipComparison(), and AutoUpgradeEquipment().
EstRepair()
uint32 PlayerbotAI::EstRepair (uint16 pos)
Definition at line 4462 of file PlayerbotAI.cpp.
References ItemPrototype::Class, Player::GetItemByPos(), Item::GetProto(), Object::GetUInt32Value(), ITEM_FIELD_DURABILITY, ITEM_FIELD_MAXDURABILITY, ItemPrototype::ItemLevel, ItemSubClassToDurabilityMultiplierId(), m_bot, DurabilityCostsEntry::multiplier, ItemPrototype::Quality, DurabilityQualityEntry::quality_mod, sDurabilityCostsStore, sDurabilityQualityStore, sLog, and ItemPrototype::SubClass.
Referenced by EstRepairAll(), and Repair().
EstRepairAll()
uint32 PlayerbotAI::EstRepairAll ()
Definition at line 4446 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_START, EstRepair(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, and MAX_BAG_SIZE.
Referenced by _HandleCommandStats(), and Repair().
extractAuctionIds()
void PlayerbotAI::extractAuctionIds (const std::string & text, std::list< uint32 > & auctionIds) const
Definition at line 7071 of file PlayerbotAI.cpp.
Referenced by _HandleCommandAuction().
ExtractCommand()
bool PlayerbotAI::ExtractCommand (const std::string sLookingFor, std::string & text, bool bUseShort = false) private
ExtractCommand looks for a command in a text string sLookingFor - string you're looking for (e.g.
"help") text - string which may or may not start with sLookingFor bUseShort - does this command accept the shorthand command? If true, "help" would ALSO look for "h"
returns true if the string has been found returns false if the string has not been found
Definition at line 9271 of file PlayerbotAI.cpp.
Referenced by _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandCollect(), _HandleCommandCraft(), _HandleCommandDrop(), _HandleCommandEquip(), _HandleCommandFollow(), _HandleCommandGM(), _HandleCommandHelp(), _HandleCommandMail(), _HandleCommandOrders(), _HandleCommandPet(), _HandleCommandProcess(), _HandleCommandPull(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandSell(), _HandleCommandSkill(), _HandleCommandTalent(), and HandleCommand().
extractGOinfo()
void PlayerbotAI::extractGOinfo (const std::string & text, BotObjectList & m_lootTargets) const
Definition at line 7188 of file PlayerbotAI.cpp.
References Map::GetGameObject(), WorldObject::GetMap(), HIGHGUID_GAMEOBJECT, m_bot, and m_lootTargets.
Referenced by _HandleCommandFind(), _HandleCommandGet(), _HandleCommandMail(), and _HandleCommandUse().
extractItemIds()
void PlayerbotAI::extractItemIds (const std::string & text, std::list< uint32 > & itemIds) const
Definition at line 6179 of file PlayerbotAI.cpp.
Referenced by _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandDrop(), _HandleCommandEnchant(), _HandleCommandEquip(), _HandleCommandProcess(), _HandleCommandRepair(), _HandleCommandSell(), _HandleCommandUse(), and HandleCommand().
extractMailIds()
void PlayerbotAI::extractMailIds (const std::string & text, std::list< uint32 > & mailIds) const
Definition at line 6199 of file PlayerbotAI.cpp.
Referenced by _HandleCommandMail().
extractMoney()
uint32 PlayerbotAI::extractMoney (const std::string & text) const
Definition at line 7227 of file PlayerbotAI.cpp.
Referenced by HandleCommand().
extractQuestIds()
void PlayerbotAI::extractQuestIds (const std::string & text, std::list< uint32 > & questIds) const
Definition at line 6892 of file PlayerbotAI.cpp.
Referenced by _HandleCommandGM(), and _HandleCommandQuest().
extractSpellId()
void PlayerbotAI::extractSpellId (const std::string & text, uint32 & spellId) const
Definition at line 7091 of file PlayerbotAI.cpp.
Referenced by _HandleCommandCast(), _HandleCommandCraft(), _HandleCommandEnchant(), and _HandleCommandPet().
extractSpellIdList()
void PlayerbotAI::extractSpellIdList (const std::string & text, BotEntryList & m_spellsToLearn) const
Definition at line 7118 of file PlayerbotAI.cpp.
References m_spellsToLearn.
Referenced by _HandleCommandSkill().
extractTalentIds()
void PlayerbotAI::extractTalentIds (const std::string & text, std::list< talentPair > & talentIds) const
Definition at line 7150 of file PlayerbotAI.cpp.
Referenced by _HandleCommandTalent().
FaceTarget()
void PlayerbotAI::FaceTarget (Unit * target)
Definition at line 7719 of file PlayerbotAI.cpp.
References WorldObject::GetAngle(), WorldObject::HasInArc(), m_bot, and Unit::SetFacingTo().
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS().
FindAmmo()
bool PlayerbotAI::FindAmmo () const
Definition at line 3061 of file PlayerbotAI.cpp.
References Player::CheckAmmoCompatibility(), ItemPrototype::Class, EQUIPMENT_SLOT_START, Object::GetEntry(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, ITEM_CLASS_PROJECTILE, m_bot, and Player::SetAmmo().
Referenced by PlayerbotHunterAI::DoFirstCombatManeuver().
FindAttacker()
Unit * PlayerbotAI::FindAttacker (ATTACKERINFOTYPE ait = AIT_NONE, Unit * victim = 0)
Definition at line 4507 of file PlayerbotAI.cpp.
References AIT_HIGHESTTHREAT, AIT_LOWESTTHREAT, AIT_VICTIMNOTSELF, AIT_VICTIMSELF, m_attackerInfo, and m_bot.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), GetCombatTarget(), and GroupTankHoldsAggro().
FindBandage()
Item * PlayerbotAI::FindBandage () const
Definition at line 2897 of file PlayerbotAI.cpp.
References Player::CanUseItem(), ItemPrototype::Class, EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONSUMABLE, ITEM_SUBCLASS_BANDAGE, m_bot, and ItemPrototype::SubClass.
Referenced by PlayerbotClassAI::EatDrinkBandage(), and TryEmergency().
FindBombForLockValue()
Item * PlayerbotAI::FindBombForLockValue (uint32 reqSkillValue)
Definition at line 5883 of file PlayerbotAI.cpp.
References ELEMENTAL_SEAFORIUM_CHARGE, Player::GetItemByEntry(), LARGE_SEAFORIUM_CHARGE, m_bot, POWERFUL_SEAFORIUM_CHARGE, and SMALL_SEAFORIUM_CHARGE.
Referenced by DoLoot().
FindConsumable()
Item * PlayerbotAI::FindConsumable (uint32 displayId) const
Definition at line 2977 of file PlayerbotAI.cpp.
References Player::CanUseItem(), ItemPrototype::Class, ItemPrototype::DisplayInfoID, EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONSUMABLE, and m_bot.
Referenced by PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), FindManaRegenItem(), and TryEmergency().
FindDrink()
Item * PlayerbotAI::FindDrink () const
Definition at line 2846 of file PlayerbotAI.cpp.
References Player::CanUseItem(), ItemPrototype::Class, EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONSUMABLE, ITEM_SUBCLASS_FOOD, m_bot, _Spell::SpellCategory, ItemPrototype::Spells, and ItemPrototype::SubClass.
Referenced by PlayerbotMageAI::DoNonCombatActions(), and PlayerbotClassAI::EatDrinkBandage().
FindFood()
Item * PlayerbotAI::FindFood () const
Definition at line 2796 of file PlayerbotAI.cpp.
References Player::CanUseItem(), ItemPrototype::Class, EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONSUMABLE, ITEM_SUBCLASS_FOOD, m_bot, _Spell::SpellCategory, ItemPrototype::Spells, and ItemPrototype::SubClass.
Referenced by PlayerbotMageAI::DoNonCombatActions(), and PlayerbotClassAI::EatDrinkBandage().
FindItem()
Item * PlayerbotAI::FindItem (uint32 ItemId, bool Equipped_too = false)
Definition at line 5773 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_START, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ItemPrototype::ItemId, and m_bot.
Referenced by _HandleCommandQuest(), AddAuction(), Deposit(), DropItem(), Repair(), and Sell().
FindItemInBank()
Item * PlayerbotAI::FindItemInBank (uint32 ItemId)
Definition at line 5823 of file PlayerbotAI.cpp.
References BANK_SLOT_BAG_END, BANK_SLOT_BAG_START, BANK_SLOT_ITEM_END, BANK_SLOT_ITEM_START, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, ItemPrototype::ItemId, and m_bot.
Referenced by Withdraw().
findItemsInEquip()
void PlayerbotAI::findItemsInEquip (std::list< uint32 > & itemIdSearchList, std::list< Item * > & foundItemList) const
Definition at line 7264 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_END, EQUIPMENT_SLOT_START, Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, ItemPrototype::ItemId, and m_bot.
Referenced by _HandleCommandEnchant(), _HandleCommandUse(), and HandleCommand().
findItemsInInv()
void PlayerbotAI::findItemsInInv (std::list< uint32 > & itemIdSearchList, std::list< Item * > & foundItemList) const
Definition at line 7286 of file PlayerbotAI.cpp.
References Bag::GetBagSize(), Player::GetItemByPos(), Object::GetObjectGuid(), Item::GetProto(), Player::GetTradeData(), Player::GetTrader(), TradeData::HasItem(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ItemPrototype::ItemId, and m_bot.
Referenced by _HandleCommandEnchant(), _HandleCommandEquip(), _HandleCommandProcess(), _HandleCommandUse(), and HandleCommand().
FindKeyForLockValue()
Item * PlayerbotAI::FindKeyForLockValue (uint32 reqSkillValue)
Definition at line 5865 of file PlayerbotAI.cpp.
References ARCANITE_SKELETON_KEY, COBALT_SKELETON_KEY, Player::GetItemByEntry(), GOLDEN_SKELETON_KEY, m_bot, SILVER_SKELETON_KEY, TITANIUM_SKELETON_KEY, and TRUESILVER_SKELETON_KEY.
Referenced by DoLoot().
FindManaRegenItem()
Item * PlayerbotAI::FindManaRegenItem () const
FindManaRegenItem() return Item* Returns items like runes or potion that can help the bot to instantly resplenish some of its mana.
return nullptr if no relevant item is found in bot inventory, else return a consumable item providing mana
Definition at line 3032 of file PlayerbotAI.cpp.
References countof, DARK_RUNE, DEMONIC_RUNE, FindConsumable(), Unit::GetHealth(), m_bot, and uPriorizedManaPotionIds.
FindMount()
Item * PlayerbotAI::FindMount (uint32 matchingRidingSkill) const
Definition at line 2714 of file PlayerbotAI.cpp.
References Player::CanUseItem(), Spell::CheckCast(), EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, SQLStorage::LookupEntry(), m_bot, MAX_ITEM_PROTO_SPELLS, ItemPrototype::RequiredSkill, ItemPrototype::RequiredSkillRank, SKILL_RIDING, SPELL_CAST_OK, _Spell::SpellId, ItemPrototype::Spells, and sSpellTemplate.
findNearbyCorpse()
void PlayerbotAI::findNearbyCorpse ()
Definition at line 7393 of file PlayerbotAI.cpp.
References Unit::CanAssist(), Loot::CanLoot(), Creature::GetCreatureInfo(), Object::GetObjectGuid(), CreatureInfo::GetRequiredLootSkill(), Object::HasFlag(), Player::HasSkill(), Creature::IsCorpse(), Creature::IsDespawned(), m_bot, PlayerbotMgr::m_confCollectDistance, Object::m_loot, m_lootTargets, m_mgr, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, and Cell::VisitAllObjects().
Referenced by UpdateAI().
findNearbyCreature()
void PlayerbotAI::findNearbyCreature ()
Definition at line 7429 of file PlayerbotAI.cpp.
References ADD_AUCTION, AddAuction(), AddQuest(), AutoUpgradeEquipment(), BANK_DEPOSIT, BANK_WITHDRAW, BankBalance(), Buy(), BUY_ITEMS, Creature::CanTrainAndResetTalentsOf(), MotionMaster::Clear(), MaNGOS::ComputeCellPair(), CONTACT_DISTANCE, DEBUG_LOG, Deposit(), EMOTE_ONESHOT_TALK, END_QUEST, FORCED_MOVEMENT_RUN, WorldObject::GetContactPoint(), Creature::GetCreatureInfo(), Player::GetDefaultGossipMenuForSource(), WorldObject::GetDistance(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMotionMaster(), WorldObject::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetUInt32Value(), Map::GetWorldObject(), GOSSIP_OPTION_ARMORER, GOSSIP_OPTION_AUCTIONEER, GOSSIP_OPTION_BANKER, GOSSIP_OPTION_GOSSIP, GOSSIP_OPTION_INNKEEPER, GOSSIP_OPTION_QUESTGIVER, GOSSIP_OPTION_TAXIVENDOR, GOSSIP_OPTION_TRAINER, GOSSIP_OPTION_UNLEARNTALENTS, GOSSIP_OPTION_VENDOR, CreatureInfo::GossipMenuId, Unit::HandleEmoteCommand(), InspectUpdate(), INTERACTION_DISTANCE, LIST_QUEST, ListAuctions(), ListQuests(), m_bot, m_findNPC, m_tasks, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), REMOVE_AUCTION, RemoveAuction(), Repair(), REPAIR_ITEMS, RESET_TALENTS, Sell(), SELL_ITEMS, SetIgnoreUpdateTime(), sObjectMgr, TAKE_QUEST, Talent(), TurnInQuests(), UNIT_NPC_FLAG_TRAINER_CLASS, UNIT_NPC_FLAGS, Cell::Visit(), and Withdraw().
Referenced by UpdateAI().
findNearbyGO()
void PlayerbotAI::findNearbyGO ()
Definition at line 7339 of file PlayerbotAI.cpp.
References ObjectMgr::GetGameObjectInfo(), TerrainInfo::GetHeightStatic(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTerrain(), INVALID_HEIGHT, IsInQuestItemList(), GameObject::IsSpawned(), m_bot, m_collectDist, m_collectObjects, m_lootTargets, GameObjectInfo::questItems, and Cell::VisitGridObjects().
Referenced by UpdateAI().
FindPoison()
Item * PlayerbotAI::FindPoison () const
Definition at line 2937 of file PlayerbotAI.cpp.
References Player::CanUseItem(), ItemPrototype::Class, EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONSUMABLE, m_bot, and ItemPrototype::SubClass.
FollowAutoReset()
void PlayerbotAI::FollowAutoReset ()
Definition at line 519 of file PlayerbotAI.cpp.
References FOLLOWAUTOGO_OFF, FOLLOWAUTOGO_RESET, WorldObject::GetDistance(), GetMaster(), m_bot, m_followTarget, MOVEMENT_FOLLOW, and SetMovementOrder().
Referenced by _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandSell(), and _HandleCommandTalent().
GameObjectLocalization()
void PlayerbotAI::GameObjectLocalization (std::string & gameobjectName, const uint32 entry) const
Definition at line 8127 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), GameObjectLocale::Name, sObjectMgr, and Utf8FitTo().
Referenced by SendQuestNeedList().
GetActiveTalentSpec()
TalentSpec PlayerbotAI::GetActiveTalentSpec () inline
Definition at line 1804 of file PlayerbotAI.h.
References m_activeTalentSpec.
GetAttackerCount()
uint32 PlayerbotAI::GetAttackerCount () inline
Definition at line 1975 of file PlayerbotAI.h.
References m_attackerInfo.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), and PlayerbotMageAI::DoNextCombatManeuverPVE().
GetClassAI()
PlayerbotClassAI* PlayerbotAI::GetClassAI () inline
Definition at line 1745 of file PlayerbotAI.h.
References m_classAI.
Referenced by PlayerbotPaladinAI::BuffHelper(), CanPull(), CastNeutralize(), CastPull(), DoCombatMovement(), DoNextCombatManeuver(), PlayerbotClassAI::FindTargetAndHeal(), GroupHoTOnTank(), and UpdateAI().
GetCombatOrder()
CombatOrderType PlayerbotAI::GetCombatOrder () inline
Definition at line 1979 of file PlayerbotAI.h.
References m_combatOrder.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::CastHoTOnTank(), PlayerbotPaladinAI::CheckAuras(), PlayerbotDruidAI::CheckForms(), PlayerbotPaladinAI::CheckSeals(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), DoNextCombatManeuver(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotShamanAI::DropTotems(), PlayerbotClassAI::FindTargetAndHeal(), and UpdateAI().
GetCombatStyle()
CombatStyle PlayerbotAI::GetCombatStyle () inline
Definition at line 1742 of file PlayerbotAI.h.
References m_combatStyle.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), PlayerbotClassAI::CastSpellWand(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), and PlayerbotHunterAI::DoNonCombatActions().
GetCombatTarget()
void PlayerbotAI::GetCombatTarget (Unit * forcedTarget = 0)
Definition at line 3141 of file PlayerbotAI.cpp.
References AIT_HIGHESTTHREAT, AIT_LOWESTTHREAT, AIT_VICTIMNOTSELF, FindAttacker(), WorldObject::GetName(), Object::GetObjectGuid(), Unit::getStandState(), Object::GetTypeId(), IsNeutralized(), m_bot, m_combatOrder, PlayerbotMgr::m_confDebugWhisper, m_ignoreNeutralizeEffect, m_mgr, m_targetAssist, m_targetChanged, m_targetCombat, m_targetProtect, m_targetType, ORDERS_ASSIST, ORDERS_MAIN_TANK, ORDERS_PROTECT, ORDERS_TANK, SetIgnoreUpdateTime(), Player::SetSelectionGuid(), Unit::SetStandState(), TARGET_NORMAL, TARGET_THREATEN, TellMaster(), TYPEID_PLAYER, UNIT_STAND_STATE_STAND, and UpdateAttackerInfo().
Referenced by _HandleCommandPull(), and Attack().
GetCurrentSpell()
Spell * PlayerbotAI::GetCurrentSpell () const
Definition at line 5355 of file PlayerbotAI.cpp.
References Unit::FindCurrentSpellBySpellId(), m_bot, and m_CurrentlyCastingSpellId.
Referenced by HandleBotOutgoingPacket(), and UpdateAI().
GetCurrentSpellId()
uint32 PlayerbotAI::GetCurrentSpellId () inline
Definition at line 1824 of file PlayerbotAI.h.
References m_CurrentlyCastingSpellId.
Referenced by PlayerbotWarriorAI::Pull().
GetCurrentTarget()
Unit* PlayerbotAI::GetCurrentTarget () inline
Definition at line 1919 of file PlayerbotAI.h.
References m_targetCombat.
Referenced by _HandleCommandPull(), CastPull(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), and PlayerbotWarriorAI::Pull().
GetDuelTarget()
void PlayerbotAI::GetDuelTarget (Unit * forcedTarget)
Definition at line 3244 of file PlayerbotAI.cpp.
References Unit::Attack(), BOTSTATE_COMBAT, COMBAT_MELEE, m_bot, m_botState, m_combatStyle, m_targetChanged, m_targetCombat, m_targetType, SetState(), and TARGET_THREATEN.
Referenced by DoNextCombatManeuver().
GetEnergyAmount() [1/2]
uint8 PlayerbotAI::GetEnergyAmount () const
Definition at line 2674 of file PlayerbotAI.cpp.
References m_bot.
GetEnergyAmount() [2/2]
uint8 PlayerbotAI::GetEnergyAmount (const Unit & target) const
Definition at line 2669 of file PlayerbotAI.cpp.
References Unit::GetPower(), and POWER_ENERGY.
Referenced by PlayerbotRogueAI::DoNextCombatManeuver().
GetFreeBagSpace()
uint32 PlayerbotAI::GetFreeBagSpace () const
Definition at line 3763 of file PlayerbotAI.cpp.
References ItemPrototype::Class, Bag::GetFreeSlots(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ITEM_CLASS_CONTAINER, ITEM_SUBCLASS_CONTAINER, m_bot, and ItemPrototype::SubClass.
Referenced by _HandleCommandStats(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), and PlayerbotWarlockAI::DoNonCombatActions().
GetGroupHealer()
Player * PlayerbotAI::GetGroupHealer ()
Definition at line 3422 of file PlayerbotAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), m_bot, and sObjectMgr.
GetGroupTank()
Player * PlayerbotAI::GetGroupTank ()
Definition at line 3389 of file PlayerbotAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), JOB_TANK, m_bot, and sObjectMgr.
Referenced by PlayerbotDruidAI::CastHoTOnTank(), PlayerbotPriestAI::CastHoTOnTank(), PlayerbotRogueAI::DoNextCombatManeuver(), and GroupTankHoldsAggro().
GetHealthPercent() [1/2]
uint8 PlayerbotAI::GetHealthPercent () const
Definition at line 2644 of file PlayerbotAI.cpp.
References m_bot.
GetHealthPercent() [2/2]
uint8 PlayerbotAI::GetHealthPercent (const Unit & target) const
Definition at line 2639 of file PlayerbotAI.cpp.
References Unit::GetHealth(), and Unit::GetMaxHealth().
Referenced by PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), PlayerbotClassAI::EatDrinkBandage(), and PlayerbotPriestAI::HealPlayer().
GetManaPercent() [1/2]
uint8 PlayerbotAI::GetManaPercent () const
Definition at line 2654 of file PlayerbotAI.cpp.
References m_bot.
Referenced by TryEmergency().
GetManaPercent() [2/2]
uint8 PlayerbotAI::GetManaPercent (const Unit & target) const
Definition at line 2649 of file PlayerbotAI.cpp.
References Unit::GetMaxPower(), Unit::GetPower(), and POWER_MANA.
Referenced by PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotClassAI::EatDrinkBandage(), PlayerbotPriestAI::HealPlayer(), and PlayerbotShamanAI::UseCooldowns().
GetMaster()
Player * PlayerbotAI::GetMaster () const
Definition at line 153 of file PlayerbotAI.cpp.
References PlayerbotMgr::GetMaster(), and m_mgr.
Referenced by _HandleCommandFollow(), _HandleCommandMail(), _HandleCommandOrders(), _HandleCommandPet(), _HandleCommandQuest(), _HandleCommandSkill(), _HandleCommandSpells(), AddQuest(), AutoUpgradeEquipment(), canObeyCommandFrom(), CombatOrderRestore(), CreatureLocalization(), DoLoot(), DoNextCombatManeuver(), DoTeleport(), FollowAutoReset(), GameObjectLocalization(), getPetSpellId(), getSpellId(), HandleBotOutgoingPacket(), HandleCommand(), InspectUpdate(), IsInCombat(), ItemLocalization(), MakeSpellLink(), MakeWeaponSkillLink(), PlayerbotAI(), PlaySound(), QuestLocalization(), ReloadAI(), SendNotEquipList(), TellMaster(), UpdateAI(), and UpdateAttackerInfo().
GetMovementOrder()
MovementOrderType PlayerbotAI::GetMovementOrder () inline
Definition at line 1988 of file PlayerbotAI.h.
References m_movementOrder.
getPetSpellId()
uint32 PlayerbotAI::getPetSpellId (const char * args) const
Definition at line 280 of file PlayerbotAI.cpp.
References GetMaster(), Unit::GetPet(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), IsPassiveSpell(), SQLStorage::LookupEntry(), m_bot, Pet::m_spells, PETSPELL_REMOVED, SpellEntry::Reagent, SpellEntry::SpellName, sSpellTemplate, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by _HandleCommandPet().
GetPlayer()
Player* PlayerbotAI::GetPlayer () const inline
Definition at line 1926 of file PlayerbotAI.h.
References m_bot.
Referenced by _HandleCommandSkill().
GetPlayerBot()
Player* PlayerbotAI::GetPlayerBot () const inline
Definition at line 1925 of file PlayerbotAI.h.
References m_bot.
GetRageAmount() [1/2]
uint8 PlayerbotAI::GetRageAmount () const
Definition at line 2664 of file PlayerbotAI.cpp.
References m_bot.
GetRageAmount() [2/2]
uint8 PlayerbotAI::GetRageAmount (const Unit & target) const
Definition at line 2659 of file PlayerbotAI.cpp.
References Unit::GetPower(), and POWER_RAGE.
Referenced by PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), and PlayerbotWarriorAI::DoNextCombatManeuverPVE().
GetRunicPower() [1/2]
uint8 PlayerbotAI::GetRunicPower () const
Definition at line 2684 of file PlayerbotAI.cpp.
References m_bot.
GetRunicPower() [2/2]
uint8 PlayerbotAI::GetRunicPower (const Unit & target) const
Definition at line 2679 of file PlayerbotAI.cpp.
References Unit::GetPower(), and POWER_RUNIC_POWER.
GetScenarioType()
ScenarioType PlayerbotAI::GetScenarioType () inline
Definition at line 1741 of file PlayerbotAI.h.
References m_ScenarioType.
Referenced by PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), PlayerbotDeathKnightAI::DoNextCombatManeuver(), PlayerbotDruidAI::DoNextCombatManeuver(), PlayerbotHunterAI::DoNextCombatManeuver(), PlayerbotMageAI::DoNextCombatManeuver(), PlayerbotPaladinAI::DoNextCombatManeuver(), PlayerbotPriestAI::DoNextCombatManeuver(), PlayerbotShamanAI::DoNextCombatManeuver(), PlayerbotWarlockAI::DoNextCombatManeuver(), PlayerbotWarriorAI::DoNextCombatManeuver(), PlayerbotRogueAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), and PlayerbotShamanAI::DoNextCombatManeuverPVP().
GetSpellCharges()
uint32 PlayerbotAI::GetSpellCharges (uint32 spellId)
Definition at line 6108 of file PlayerbotAI.cpp.
References Player::CanNoReagentCast(), Player::HasItemTotemCategory(), ItemCountInInv(), SQLStorage::LookupEntry(), m_bot, m_noToolList, MAX_SPELL_REAGENTS, MAX_SPELL_TOTEM_CATEGORIES, SpellEntry::Reagent, SpellEntry::ReagentCount, sSpellTemplate, and SpellEntry::TotemCategory.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), and UpdateAI().
getSpellId()
uint32 PlayerbotAI::getSpellId (const char * args, bool master = false) const
Definition at line 217 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), Player::GetSpellMap(), IsPassiveSpell(), SQLStorage::LookupEntry(), m_bot, PLAYERSPELL_REMOVED, SpellEntry::Reagent, SpellEntry::SpellName, sSpellTemplate, Utf8FitTo(), Utf8toWStr(), and wstrToLower().
Referenced by _HandleCommandCast(), CastSpell(), and HasAura().
GetState()
BotState PlayerbotAI::GetState () inline
Definition at line 1929 of file PlayerbotAI.h.
References m_botState.
GetTalentSpec()
TalentSpec PlayerbotAI::GetTalentSpec (long specClass, long choice)
GetTalentSpec queries DB for a talentspec given a class and a choice.
The choice applies to the results for that class only, and is volatile.
*** for the most part, GetTalentSpec assumes ALL SPECS ARE VALID ***
Definition at line 6463 of file PlayerbotAI.cpp.
References CharacterDatabase, CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, QueryResult::Fetch(), Field::GetCppString(), Field::GetInt16(), GetTalentSpecsAmount(), Field::GetUInt16(), TalentSpec::glyphIdMajor, TalentSpec::glyphIdMinor, QueryResult::NextRow(), Database::PQuery(), sLog, TalentSpec::specClass, TalentSpec::specName, TalentSpec::specPurpose, TalentSpec::talentId, TellMaster(), and TSP_NONE.
Referenced by _HandleCommandTalent().
GetTalentSpecs()
std::list< TalentSpec > PlayerbotAI::GetTalentSpecs (long specClass)
GetTalentSpecs queries DB for the talentspecs (for a class), returning them in a list of TS structures.
*** for the most part, GetTalentSpecs assumes ALL SPECS ARE VALID ***
Definition at line 6391 of file PlayerbotAI.cpp.
References CharacterDatabase, CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, QueryResult::Fetch(), Field::GetCppString(), Field::GetInt16(), Field::GetUInt16(), TalentSpec::glyphIdMajor, QueryResult::NextRow(), Database::PQuery(), sLog, TalentSpec::specClass, TalentSpec::specName, TalentSpec::specPurpose, TalentSpec::talentId, and TellMaster().
Referenced by _HandleCommandTalent().
GetTalentSpecsAmount() [1/2]
uint32 PlayerbotAI::GetTalentSpecsAmount ()
Definition at line 6346 of file PlayerbotAI.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetUInt32(), Database::Query(), and sLog.
Referenced by _HandleCommandTalent(), and GetTalentSpec().
GetTalentSpecsAmount() [2/2]
uint32 PlayerbotAI::GetTalentSpecsAmount (long specClass)
Definition at line 6366 of file PlayerbotAI.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetUInt32(), Database::PQuery(), and sLog.
GetTaxi()
void PlayerbotAI::GetTaxi (ObjectGuid guid, BotTaxiNode & nodes)
Definition at line 8978 of file PlayerbotAI.cpp.
References BOTSTATE_FLYING, DEBUG_LOG, Player::GetNPCIfCanInteractWith(), ObjectGuid::GetString(), PlayerTaxi::IsTaximaskNodeKnown(), m_bot, Player::m_taxi, m_taxiMaster, m_taxiNodes, MOVEMENT_STAY, SetState(), and UNIT_NPC_FLAG_FLIGHTMASTER.
GiveLevel()
void PlayerbotAI::GiveLevel (uint32 level)
GiveLevel sets the bot's level to 'level' Not the clearest of function names, we're just mirroring Player.cpp's function name.
Definition at line 7655 of file PlayerbotAI.cpp.
References ApplyActiveTalentSpec().
GroupHoTOnTank()
bool PlayerbotAI::GroupHoTOnTank ()
Definition at line 3499 of file PlayerbotAI.cpp.
References GetClassAI(), Player::GetGroup(), Group::GetMemberSlots(), m_bot, SetIgnoreUpdateTime(), and sObjectMgr.
Referenced by _HandleCommandPull().
GroupTankHoldsAggro()
bool PlayerbotAI::GroupTankHoldsAggro ()
Definition at line 3602 of file PlayerbotAI.cpp.
References AIT_VICTIMNOTSELF, FindAttacker(), Player::GetGroup(), GetGroupTank(), m_bot, and UpdateAttackerInfo().
Referenced by PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), and PlayerbotWarriorAI::DoFirstCombatManeuver().
HandleBotOutgoingPacket()
void PlayerbotAI::HandleBotOutgoingPacket (const WorldPacket & packet)
Definition at line 1545 of file PlayerbotAI.cpp.
References Guild::AddMember(), MovementInfo::AddMovementFlag(), Announce(), ByteBuffer::appendPackGUID(), AUCTION_ERR_BID_OWN, AUCTION_ERR_DATABASE, AUCTION_ERR_ITEM_NOT_FOUND, AUCTION_ERR_NOT_ENOUGH_MONEY, AUCTION_OK, AURA_INTERRUPT_FLAG_STANDING_CANCELS, SpellEntry::AuraInterruptFlags, AutoUpgradeEquipment(), BOTSTATE_DELAYED, BOTSTATE_LOADING, BOTSTATE_NORMAL, Guild::BroadcastEvent(), BUY_ERR_CANT_CARRY_MORE, BUY_ERR_CANT_FIND_ITEM, BUY_ERR_DISTANCE_TOO_FAR, BUY_ERR_ITEM_ALREADY_SOLD, BUY_ERR_ITEM_SOLD_OUT, BUY_ERR_NOT_ENOUGHT_MONEY, BUY_ERR_RANK_REQUIRE, BUY_ERR_REPUTATION_REQUIRE, BUY_ERR_SELLER_DONT_LIKE_YOU, Item::CanBeTraded(), Spell::cancel(), canObeyCommandFrom(), Player::CanStoreNewItem(), CANT_AFFORD, Cash(), CHAT_MSG_PARTY, CHAT_MSG_PARTY_LEADER, CHAT_MSG_RAID, CHAT_MSG_RAID_LEADER, CHAT_MSG_WHISPER, ByteBuffer::clear(), MotionMaster::Clear(), CMSG_AUTOSTORE_LOOT_ITEM, CMSG_CANCEL_TRADE, CMSG_DUEL_ACCEPTED, CMSG_LOOT_MONEY, CMSG_LOOT_RELEASE, CMSG_RESURRECT_RESPONSE, COLLECT_FLAG_LOOT, COLLECT_FLAG_SKIN, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD, CREATURE_LOOT_STATUS_LOOTED, DEBUG_LOG, DropGarbage(), EMOTE_ONESHOT_APPLAUD, EMOTE_ONESHOT_CHICKEN, EQUIP_ERR_ALREADY_LOOTED, EQUIP_ERR_BANK_FULL, EQUIP_ERR_CANT_CARRY_MORE_OF_THIS, EQUIP_ERR_INVENTORY_FULL, EQUIP_ERR_ITEM_LOCKED, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_ITEM_UNIQUE_EQUIPABLE, EQUIP_ERR_LOOT_CANT_LOOT_THAT_NOW, EQUIP_ERR_MISSING_REAGENT, EQUIP_ERR_NONE, EQUIP_ERR_NOT_IN_COMBAT, EQUIP_ERR_OK, EQUIP_ERR_TOO_FAR_AWAY_FROM_BANK, ObjectAccessor::FindPlayer(), GE_JOINED, Bag::GetBagSize(), Map::GetCreature(), Creature::GetCreatureInfo(), GetCurrentSpell(), Map::GetGameObject(), Player::GetGroup(), Player::GetGroupInvite(), Player::GetGuildId(), Player::GetGuildIdInvited(), Player::GetItemByPos(), ObjectMgr::GetItemPrototype(), Group::GetLeaderGuid(), Guild::GetLeaderGuid(), Unit::GetLevel(), Creature::GetLootStatus(), Guild::GetLowestRank(), WorldObject::GetMap(), GetMaster(), Player::GetMoney(), Unit::GetMotionMaster(), WorldObject::GetName(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), Item::GetProto(), CreatureInfo::GetRequiredLootSkill(), Player::GetSession(), Player::GetSkillValue(), Player::GetTeam(), Player::GetTrader(), GUILD_EVENT_LOG_JOIN_GUILD, WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleBeginTradeOpcode(), HandleCommand(), Unit::HandleEmoteCommand(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupDisbandOpcode(), WorldSession::HandleGroupSetLeaderOpcode(), HasCollectFlag(), Player::HasSkill(), INVENTORY_FULL, INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, Unit::IsAlive(), Player::IsBeingTeleportedFar(), Player::IsBeingTeleportedNear(), ObjectGuid::IsGameObject(), IsInQuestItemList(), IsItemUseful(), Group::IsMember(), ItemPrototype::ItemId, ItemLocalization(), LANG_ADDON, Guild::LogGuildEvent(), SQLStorage::LookupEntry(), LOOT_CORPSE, LOOT_SKINNING, LOOT_SLOT_NORMAL, LOOT_SLOT_OWNER, m_being_rolled_on, m_bot, m_botState, m_collectObjects, m_CurrentlyCastingSpellId, m_debugWhisper, m_inventory_full, m_itemTarget, m_lootCurrent, m_lootPrev, WorldObject::m_movementInfo, m_needItemList, M_PI_F, m_ScenarioType, m_targetCombat, MakeItemLink(), MOVEFLAG_FLYING, MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), MSG_MOVE_FALL_LAND, MSG_MOVE_HEARTBEAT, MSG_MOVE_TELEPORT_ACK, MSG_MOVE_WORLDPORT_ACK, ItemPrototype::Name1, NULL_BAG, NULL_SLOT, PARTY_OP_LEAVE, PETTAME_ANOTHERSUMMONACTIVE, PETTAME_CANTCONTROLEXOTIC, PETTAME_CREATUREALREADYOWNED, PETTAME_DEAD, PETTAME_INTERNALERROR, PETTAME_INVALIDCREATURE, PETTAME_NOPETAVAILABLE, PETTAME_NOTDEAD, PETTAME_NOTTAMEABLE, PETTAME_TOOHIGHLEVEL, PETTAME_TOOMANY, PETTAME_UNITSCANTTAME, PETTAME_UNKNOWNERROR, WorldSession::QueuePacket(), rand_float(), ByteBuffer::read_skip(), ObjectGuid::ReadAsPacked(), ReloadAI(), MovementInfo::RemoveMovementFlag(), SpellEntry::RequiresSpellFocus, ByteBuffer::resize(), SCENARIO_PVE, SCENARIO_PVP_DUEL, SendWhisper(), SetIgnoreUpdateTime(), Unit::SetInFront(), SetQuestNeedItems(), Player::SetSelectionGuid(), SetState(), sGuildMgr, SKILL_SKINNING, CreatureInfo::SkinningLootId, sLootMgr, SMSG_AUCTION_COMMAND_RESULT, SMSG_BUY_FAILED, SMSG_CAST_RESULT, SMSG_DUEL_COMPLETE, SMSG_DUEL_OUTOFBOUNDS, SMSG_DUEL_REQUESTED, SMSG_DUEL_WINNER, SMSG_GROUP_INVITE, SMSG_GROUP_SET_LEADER, SMSG_GUILD_INVITE, SMSG_INVENTORY_CHANGE_FAILURE, SMSG_ITEM_PUSH_RESULT, SMSG_LOOT_RELEASE_RESPONSE, SMSG_LOOT_RESPONSE, SMSG_LOOT_ROLL_WON, SMSG_MESSAGECHAT, SMSG_MOVE_SET_CAN_FLY, SMSG_MOVE_UNSET_CAN_FLY, SMSG_NEW_WORLD, SMSG_PARTY_COMMAND_RESULT, SMSG_PARTYKILLLOG, SMSG_PET_TAME_FAILURE, SMSG_RESURRECT_REQUEST, SMSG_SPELL_FAILURE, SMSG_SPELL_GO, SMSG_SPELL_START, SMSG_TRADE_STATUS, SMSG_TRANSFER_PENDING, sObjectMgr, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_CANT_BE_DISENCHANTED, SPELL_FAILED_CANT_BE_MILLED, SPELL_FAILED_CANT_BE_PROSPECTED, SPELL_FAILED_EQUIPPED_ITEM_CLASS, SPELL_FAILED_INTERRUPTED, SPELL_FAILED_NEED_MORE_ITEMS, SPELL_FAILED_REAGENTS, SPELL_FAILED_REQUIRES_SPELL_FOCUS, SPELL_FAILED_UNIT_NOT_INFRONT, SpellEntry::SpellName, sSpellTemplate, sWorld, and TellMaster().
HandleCommand()
void PlayerbotAI::HandleCommand (const std::string & text, Player & fromPlayer)
Definition at line 9004 of file PlayerbotAI.cpp.
References _HandleCommandAttack(), _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandCast(), _HandleCommandCollect(), _HandleCommandCraft(), _HandleCommandDrop(), _HandleCommandEnchant(), _HandleCommandEquip(), _HandleCommandFind(), _HandleCommandFollow(), _HandleCommandGet(), _HandleCommandGM(), _HandleCommandHelp(), _HandleCommandMail(), _HandleCommandNeutralize(), _HandleCommandOrders(), _HandleCommandPet(), _HandleCommandProcess(), _HandleCommandPull(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandReset(), _HandleCommandSell(), _HandleCommandSkill(), _HandleCommandSpells(), _HandleCommandStats(), _HandleCommandStay(), _HandleCommandSurvey(), _HandleCommandTalent(), _HandleCommandUse(), canObeyCommandFrom(), Player::CanRewardQuest(), DEBUG_LOG, EMOTE_ONESHOT_NO, EMOTE_ONESHOT_TALK, ExtractCommand(), extractItemIds(), extractMoney(), findItemsInEquip(), findItemsInInv(), QuestMenu::GetItem(), GetMaster(), WorldObject::GetName(), Player::GetObjectByTypeMask(), Object::GetObjectGuid(), Player::GetPlayerMenu(), PlayerMenu::GetQuestMenu(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Quest::GetRewChoiceItemsCount(), WorldSession::GetSecurity(), Player::GetSelectionGuid(), Player::GetSession(), Player::GetTrader(), Unit::HandleEmoteCommand(), ItemPrototype::ItemId, m_bDebugCommandChat, m_bot, m_debugWhisper, m_findNPC, m_ignorePlayersChat, m_inventory_full, QuestMenuItem::m_qId, m_tasks, MakeItemLink(), QuestMenu::MenuItemCount(), ItemPrototype::Name1, QUEST_STATUS_COMPLETE, Player::RewardQuest(), Quest::RewChoiceItemId, SEC_PLAYER, SendWhisper(), sObjectMgr, TellMaster(), TRADE_SLOT_NONTRADED, TradeCopper(), TradeItem(), TYPEMASK_CREATURE_OR_GAMEOBJECT, and utf8limit().
Referenced by HandleBotOutgoingPacket().
HasAura() [1/3]
bool PlayerbotAI::HasAura (const char * spellName) const
Definition at line 2702 of file PlayerbotAI.cpp.
References HasAura(), and m_bot.
HasAura() [2/3]
bool PlayerbotAI::HasAura (const char * spellName, const Unit & player) const
Definition at line 2707 of file PlayerbotAI.cpp.
References getSpellId(), and HasAura().
HasAura() [3/3]
bool PlayerbotAI::HasAura (uint32 spellId, const Unit & player) const
Definition at line 2689 of file PlayerbotAI.cpp.
References Unit::GetSpellAuraHolderMap().
Referenced by PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), and HasAura().
HasCollectFlag()
bool PlayerbotAI::HasCollectFlag (uint8 flag) inline
Definition at line 1944 of file PlayerbotAI.h.
References m_collectionFlags.
Referenced by _HandleCommandCollect(), Attack(), DoLoot(), HandleBotOutgoingPacket(), IsItemUseful(), SetCollectFlag(), SetQuestNeedItems(), and UpdateAI().
HasDispelOrder()
bool PlayerbotAI::HasDispelOrder () inline
Definition at line 1984 of file PlayerbotAI.h.
References m_combatOrder, and ORDERS_NODISPEL.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverHeal(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), and PlayerbotShamanAI::DoNonCombatActions().
HasSpellReagents()
bool PlayerbotAI::HasSpellReagents (uint32 spellId)
Definition at line 6084 of file PlayerbotAI.cpp.
References Player::CanNoReagentCast(), Player::HasItemCount(), SQLStorage::LookupEntry(), m_bot, MAX_SPELL_REAGENTS, SpellEntry::Reagent, SpellEntry::ReagentCount, and sSpellTemplate.
Referenced by PlayerbotPaladinAI::BuffHelper(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), and PlayerbotPriestAI::DoNonCombatActions().
HasTool()
bool PlayerbotAI::HasTool (uint32 TC)
Definition at line 5897 of file PlayerbotAI.cpp.
References Player::HasItemTotemCategory(), m_bot, TC_ADAMANTITE_ROD, TC_ARCANITE_ROD, TC_ARCLIGHT_SPANNER, TC_BLACKSMITH_HAMMER, TC_COPPER_ROD, TC_ETERNIUM_ROD, TC_FEL_IRON_ROD, TC_GOLDEN_ROD, TC_MINING_PICK, TC_RUNED_AZURITE_ROD, TC_RUNED_COBALT_ROD, TC_RUNED_TITANIUM_ROD, TC_SILVER_ROD, TC_SKINNING_KNIFE, TC_TRUESILVER_ROD, TC_VIRTUOSO_INKING_SET, and TellMaster().
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), and DoLoot().
Impulse()
bool PlayerbotAI::Impulse () inline
Definition at line 1986 of file PlayerbotAI.h.
Referenced by PlayerbotHunterAI::DoNextCombatManeuverPVE().
In_Range()
bool PlayerbotAI::In_Range (Unit * Target, uint32 spellId)
Definition at line 5398 of file PlayerbotAI.cpp.
References GetSpellRangeStore(), WorldObject::IsInRange(), SQLStorage::LookupEntry(), m_bot, SpellRangeEntry::maxRange, SpellRangeEntry::minRange, SpellEntry::rangeIndex, and sSpellTemplate.
Referenced by CastSpell(), PlayerbotWarriorAI::Pull(), and UpdateAI().
In_Reach()
bool PlayerbotAI::In_Reach (Unit * Target, uint32 spellId)
Definition at line 196 of file PlayerbotAI.cpp.
References DIST_CALC_COMBAT_REACH_WITH_MELEE, WorldObject::GetDistance(), m_bot, and m_spellRangeMap.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), PlayerbotPriestAI::CastHoTOnTank(), PlayerbotPriestAI::DoFirstCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVP(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), PlayerbotWarlockAI::DoNextCombatManeuverPVP(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), and PlayerbotShamanAI::ResurrectPlayer().
initPetSpell()
uint32 PlayerbotAI::initPetSpell (uint32 spellIconId)
Definition at line 385 of file PlayerbotAI.cpp.
References Unit::GetPet(), IsPassiveSpell(), SQLStorage::LookupEntry(), m_bot, Pet::m_spells, PETSPELL_REMOVED, SpellEntry::SpellIconID, and sSpellTemplate.
Referenced by PlayerbotWarlockAI::DoNonCombatActions().
initSpell()
uint32 PlayerbotAI::initSpell (uint32 spellId)
Definition at line 343 of file PlayerbotAI.cpp.
References DEBUG_LOG, GetSpellMaxRange(), Player::GetSpellModOwner(), Player::HasSpell(), SpellEntry::Id, IsPositiveSpell(), SQLStorage::LookupEntry(), m_bot, m_spellRangeMap, SpellChainNode::prev, SpellEntry::rangeIndex, SpellChainNode::req, SPELLMOD_RANGE, SpellEntry::SpellName, sSpellMgr, sSpellRangeStore, and sSpellTemplate.
Referenced by PlayerbotDeathKnightAI::PlayerbotDeathKnightAI(), PlayerbotDruidAI::PlayerbotDruidAI(), PlayerbotHunterAI::PlayerbotHunterAI(), PlayerbotMageAI::PlayerbotMageAI(), PlayerbotPaladinAI::PlayerbotPaladinAI(), PlayerbotPriestAI::PlayerbotPriestAI(), PlayerbotRogueAI::PlayerbotRogueAI(), PlayerbotShamanAI::PlayerbotShamanAI(), PlayerbotWarlockAI::PlayerbotWarlockAI(), PlayerbotWarriorAI::PlayerbotWarriorAI(), and ReloadAI().
InspectUpdate()
void PlayerbotAI::InspectUpdate ()
Definition at line 8319 of file PlayerbotAI.cpp.
References Player::BuildEnchantmentsInfoData(), Player::BuildPlayerTalentsInfoData(), GetMaster(), Object::GetPackGUID(), Player::GetSession(), m_bot, WorldSession::SendPacket(), and SMSG_INSPECT_RESULTS.
Referenced by _HandleCommandEquip(), _HandleCommandTalent(), AutoEquipComparison(), AutoUpgradeEquipment(), and findNearbyCreature().
InterruptCurrentCastingSpell()
void PlayerbotAI::InterruptCurrentCastingSpell ()
Definition at line 3100 of file PlayerbotAI.cpp.
References CMSG_CANCEL_CAST, Player::GetSession(), m_bot, m_CurrentlyCastingSpellId, m_targetGuidCommand, and WorldSession::QueuePacket().
Referenced by PlayerbotClassAI::FleeFromPointIfCan(), and UpdateAI().
IsDPS()
bool PlayerbotAI::IsDPS () inline
Definition at line 1985 of file PlayerbotAI.h.
References m_combatOrder, and ORDERS_ASSIST.
IsElite()
bool PlayerbotAI::IsElite (Unit * target, bool isWorldBoss = false) const
IsElite() Playerbot wrapper to know if a target is elite or not.
This is used by the AI to switch from one action to another return bool Returns true if bot's target is a creature with elite rank (elite rare, elite, worldboss)
params:target Unit* the target to check if it is elite params:isWorldBoss bool if true, the function will return true only if the target is a worldboss. This allow to enable specific code if the target is a worldboss return false if the target is not elite/rare elite/worldboss or if isWorldBoss was provided as true and that the target is not a worldboss
Definition at line 7671 of file PlayerbotAI.cpp.
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), and PlayerbotPriestAI::DoNextCombatManeuverPVE().
IsGroupReady()
bool PlayerbotAI::IsGroupReady ()
Definition at line 3366 of file PlayerbotAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), Unit::IsAlive(), Unit::IsInCombat(), m_bot, and sObjectMgr.
Referenced by CanPull(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), and PlayerbotWarriorAI::DoFirstCombatManeuver().
IsHealer()
bool PlayerbotAI::IsHealer () inline
Definition at line 1983 of file PlayerbotAI.h.
References IsMainHealer(), m_combatOrder, ORDERS_HEAL, and ORDERS_NOT_MAIN_HEAL.
Referenced by PlayerbotPaladinAI::CastHoTOnTank(), PlayerbotPriestAI::CastHoTOnTank(), PlayerbotShamanAI::CastHoTOnTank(), PlayerbotDruidAI::CheckForms(), PlayerbotPaladinAI::CheckSeals(), DoCombatMovement(), PlayerbotPriestAI::DoFirstCombatManeuverPVE(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotClassAI::FindTargetAndHeal(), and TryEmergency().
IsImmuneToSchool()
bool PlayerbotAI::IsImmuneToSchool (Unit * target, SpellSchoolMask schoolMask) static
IsImmuneToSchool() Playerbot wrapper to know if a target is immune or not to a specific damage school.
This is used by the AI to prevent using an ability the target is immuned to return bool Returns true if bot's target is a creature with immunity to specified damage school
params:target Unit* the target to check if it is immune params:schoolMask the school mask to be checked against the creature template or current spell immunity return false if the target is not immune, also return false by default
Definition at line 7739 of file PlayerbotAI.cpp.
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), and PlayerbotWarlockAI::DoNextCombatManeuverPVE().
IsInCombat()
bool PlayerbotAI::IsInCombat ()
Definition at line 4300 of file PlayerbotAI.cpp.
References Group::GetFirstMember(), Player::GetGroup(), GetMaster(), Unit::GetPet(), Reference< TO, FROM >::getSource(), Unit::IsInCombat(), m_bot, and GroupReference::next().
Referenced by PlayerbotPriestAI::HealPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), PlayerbotShamanAI::ResurrectPlayer(), SendOrders(), and UpdateAI().
IsInQuestCreatureList()
bool PlayerbotAI::IsInQuestCreatureList (uint32 id) inline
Definition at line 1935 of file PlayerbotAI.h.
References m_needCreatureOrGOList.
IsInQuestItemList()
bool PlayerbotAI::IsInQuestItemList (uint32 itemid) inline
Definition at line 1934 of file PlayerbotAI.h.
References m_needItemList.
Referenced by findNearbyGO(), and HandleBotOutgoingPacket().
IsItemUseful()
bool PlayerbotAI::IsItemUseful (uint32 itemid)
Definition at line 1238 of file PlayerbotAI.cpp.
References ItemPrototype::Class, COLLECT_FLAG_PROFESSION, COLLECT_FLAG_QUEST, ObjectMgr::GetItemPrototype(), HasCollectFlag(), Player::HasItemCount(), Player::HasSkill(), Player::HasSpell(), ITEM_CLASS_ARMOR, ITEM_CLASS_GEM, ITEM_CLASS_KEY, ITEM_CLASS_QUEST, ITEM_CLASS_RECIPE, ITEM_CLASS_TRADE_GOODS, ITEM_CLASS_WEAPON, ITEM_QUALITY_NORMAL, ITEM_SUBCLASS_ALCHEMY_RECIPE, ITEM_SUBCLASS_BLACKSMITHING, ITEM_SUBCLASS_CLOTH, ITEM_SUBCLASS_COOKING_RECIPE, ITEM_SUBCLASS_DEVICES, ITEM_SUBCLASS_ELEMENTAL, ITEM_SUBCLASS_ENCHANTING, ITEM_SUBCLASS_ENCHANTING_FORMULA, ITEM_SUBCLASS_ENGINEERING_SCHEMATIC, ITEM_SUBCLASS_EXPLOSIVES, ITEM_SUBCLASS_FIRST_AID_MANUAL, ITEM_SUBCLASS_FISHING_MANUAL, ITEM_SUBCLASS_HERB, ITEM_SUBCLASS_JEWELCRAFTING, ITEM_SUBCLASS_JEWELCRAFTING_RECIPE, ITEM_SUBCLASS_LEATHER, ITEM_SUBCLASS_LEATHERWORKING_PATTERN, ITEM_SUBCLASS_MEAT, ITEM_SUBCLASS_METAL_STONE, ITEM_SUBCLASS_PARTS, ITEM_SUBCLASS_TAILORING_PATTERN, m_bot, MAX_ITEM_SUBCLASS_ARMOR, MAX_ITEM_SUBCLASS_WEAPON, ItemPrototype::MaxCount, ItemPrototype::Quality, SKILL_2H_AXES, SKILL_2H_MACES, SKILL_2H_SWORDS, SKILL_ALCHEMY, SKILL_ASSASSINATION, SKILL_AXES, SKILL_BLACKSMITHING, SKILL_BOWS, SKILL_CLOTH, SKILL_COOKING, SKILL_CROSSBOWS, SKILL_DAGGERS, SKILL_ENCHANTING, SKILL_ENGINEERING, SKILL_FIRST_AID, SKILL_FISHING, SKILL_GUNS, SKILL_HERBALISM, SKILL_INSCRIPTION, SKILL_JEWELCRAFTING, SKILL_LEATHER, SKILL_LEATHERWORKING, SKILL_MACES, SKILL_MAIL, SKILL_MINING, SKILL_PLATE_MAIL, SKILL_POLEARMS, SKILL_SHIELD, SKILL_STAVES, SKILL_SWORDS, SKILL_TAILORING, SKILL_THROWN, SKILL_UNARMED, SKILL_WANDS, _Spell::SpellId, ItemPrototype::Spells, ItemPrototype::StartQuest, and ItemPrototype::SubClass.
Referenced by HandleBotOutgoingPacket().
IsMainHealer()
bool PlayerbotAI::IsMainHealer () inline
Definition at line 1982 of file PlayerbotAI.h.
References m_combatOrder, and ORDERS_MAIN_HEAL.
Referenced by PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotClassAI::FindTargetAndHeal(), and IsHealer().
IsMainTank()
bool PlayerbotAI::IsMainTank () inline
Definition at line 1980 of file PlayerbotAI.h.
References m_combatOrder, and ORDERS_MAIN_TANK.
Referenced by IsTank().
IsNeutralized()
bool PlayerbotAI::IsNeutralized (Unit * target) static
Definition at line 7702 of file PlayerbotAI.cpp.
References aurasIds, EFFECT_INDEX_0, and Unit::HasAura().
Referenced by _HandleCommandNeutralize(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), and GetCombatTarget().
IsRegenerating()
bool PlayerbotAI::IsRegenerating ()
IsRegenerating() return boolean Returns true if bot is having at least one aura associated with regenerating mana (drinking) or health (food)
params: null If false is returned, the bot will change his/her stand state to STAND if not already standing.
Definition at line 4332 of file PlayerbotAI.cpp.
References SpellEntry::Category, SpellEntry::DurationIndex, SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, Unit::GetSpellAuraHolderMap(), Unit::getStandState(), SpellEntry::HasAttribute(), m_bot, MAX_EFFECT_INDEX, Unit::SetStandState(), SPELL_ATTR_ALLOW_WHILE_SITTING, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_REGEN, SPELL_EFFECT_APPLY_AURA, and UNIT_STAND_STATE_STAND.
Referenced by UpdateAI().
IsTank()
bool PlayerbotAI::IsTank () inline
Definition at line 1981 of file PlayerbotAI.h.
References IsMainTank(), m_combatOrder, and ORDERS_TANK.
Referenced by CanPull(), CastPull(), PlayerbotPaladinAI::CheckSeals(), and PlayerbotPaladinAI::DoNonCombatActions().
ItemCountInInv()
void PlayerbotAI::ItemCountInInv (uint32 itemid, uint32 & count)
Definition at line 6154 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_START, Item::GetCount(), Object::GetEntry(), Player::GetItemByPos(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, Item::IsInTrade(), and m_bot.
Referenced by GetSpellCharges().
ItemLocalization()
void PlayerbotAI::ItemLocalization (std::string & itemName, const uint32 itemID) const
Definition at line 8082 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), ItemLocale::Name, sObjectMgr, and Utf8FitTo().
Referenced by BankBalance(), HandleBotOutgoingPacket(), ListAuctions(), MakeItemLink(), MakeItemText(), SellGarbage(), and SendQuestNeedList().
ItemStatComparison()
bool PlayerbotAI::ItemStatComparison (const ItemPrototype * pProto, const ItemPrototype * pProto2)
Definition at line 721 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, Unit::getClass(), ITEM_MOD_AGILITY, ITEM_MOD_ARMOR_PENETRATION_RATING, ITEM_MOD_ATTACK_POWER, ITEM_MOD_BLOCK_RATING, ITEM_MOD_BLOCK_VALUE, ITEM_MOD_CRIT_MELEE_RATING, ITEM_MOD_CRIT_RANGED_RATING, ITEM_MOD_CRIT_RATING, ITEM_MOD_CRIT_SPELL_RATING, ITEM_MOD_CRIT_TAKEN_MELEE_RATING, ITEM_MOD_CRIT_TAKEN_RANGED_RATING, ITEM_MOD_CRIT_TAKEN_RATING, ITEM_MOD_CRIT_TAKEN_SPELL_RATING, ITEM_MOD_DEFENSE_SKILL_RATING, ITEM_MOD_DODGE_RATING, ITEM_MOD_EXPERTISE_RATING, ITEM_MOD_HASTE_MELEE_RATING, ITEM_MOD_HASTE_RANGED_RATING, ITEM_MOD_HASTE_RATING, ITEM_MOD_HASTE_SPELL_RATING, ITEM_MOD_HEALTH, ITEM_MOD_HEALTH_REGEN, ITEM_MOD_HIT_MELEE_RATING, ITEM_MOD_HIT_RANGED_RATING, ITEM_MOD_HIT_RATING, ITEM_MOD_HIT_SPELL_RATING, ITEM_MOD_HIT_TAKEN_MELEE_RATING, ITEM_MOD_HIT_TAKEN_RANGED_RATING, ITEM_MOD_HIT_TAKEN_RATING, ITEM_MOD_HIT_TAKEN_SPELL_RATING, ITEM_MOD_INTELLECT, ITEM_MOD_MANA, ITEM_MOD_MANA_REGENERATION, ITEM_MOD_PARRY_RATING, ITEM_MOD_RANGED_ATTACK_POWER, ITEM_MOD_RESILIENCE_RATING, ITEM_MOD_SPELL_DAMAGE_DONE, ITEM_MOD_SPELL_PENETRATION, ITEM_MOD_SPELL_POWER, ITEM_MOD_SPIRIT, ITEM_MOD_STAMINA, ITEM_MOD_STRENGTH, ItemPrototype::ItemStat, _ItemStat::ItemStatType, _ItemStat::ItemStatValue, m_bot, and MAX_ITEM_PROTO_STATS.
Referenced by AutoEquipComparison(), and AutoUpgradeEquipment().
ListAuctions()
void PlayerbotAI::ListAuctions ()
Definition at line 8618 of file PlayerbotAI.cpp.
References Cash(), CharacterDatabase, CurrentTime(), QueryResult::Fetch(), Item::GetCount(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), Item::GetProto(), Field::GetUInt32(), HIGHGUID_PLAYER, ItemLocalization(), m_bot, ItemPrototype::Name1, QueryResult::NextRow(), Database::PQuery(), sAuctionMgr, sObjectMgr, and TellMaster().
Referenced by findNearbyCreature().
ListQuests()
void PlayerbotAI::ListQuests (WorldObject * questgiver)
Definition at line 8525 of file PlayerbotAI.cpp.
References AddQuest(), QuestMenu::GetItem(), Object::GetObjectGuid(), Player::GetPlayerMenu(), PlayerMenu::GetQuestMenu(), gQuestFetch, m_bot, QuestMenuItem::m_qId, MakeQuestLink(), QuestMenu::MenuItemCount(), Player::PrepareQuestMenu(), Player::SatisfyQuestStatus(), sObjectMgr, and TellMaster().
Referenced by findNearbyCreature().
MakeItemLink() [1/2]
void PlayerbotAI::MakeItemLink (const Item * item, std::ostringstream & out, bool IncludeQuantity = true) private
Definition at line 6981 of file PlayerbotAI.cpp.
References SpellItemEnchantmentEntry::GemID, Item::GetCount(), Item::GetEnchantmentId(), Item::GetProto(), ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_HEIRLOOM, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, ItemPrototype::ItemId, ItemLocalization(), MAX_GEM_SOCKETS, ItemPrototype::Name1, PERM_ENCHANTMENT_SLOT, ItemPrototype::Quality, SOCK_ENCHANTMENT_SLOT, and sSpellItemEnchantmentStore.
Referenced by _doSellItem(), _HandleCommandMail(), _HandleCommandQuest(), AddAuction(), BankBalance(), Deposit(), HandleBotOutgoingPacket(), HandleCommand(), Sell(), SendNotEquipList(), TurnInQuests(), and Withdraw().
MakeItemLink() [2/2]
void PlayerbotAI::MakeItemLink (const ItemPrototype * item, std::ostringstream & out) private
Definition at line 6942 of file PlayerbotAI.cpp.
References ItemPrototype::BuyCount, ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_HEIRLOOM, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, ItemPrototype::ItemId, ItemLocalization(), ItemPrototype::Name1, and ItemPrototype::Quality.
MakeItemText()
void PlayerbotAI::MakeItemText (const Item * item, std::ostringstream & out, bool IncludeQuantity = true) private
Definition at line 7043 of file PlayerbotAI.cpp.
References Item::GetCount(), Item::GetProto(), ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_HEIRLOOM, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, ItemPrototype::ItemId, ItemLocalization(), ItemPrototype::Name1, and ItemPrototype::Quality.
Referenced by DropItem().
MakeQuestLink()
void PlayerbotAI::MakeQuestLink (Quest const * quest, std::ostringstream & out)
Definition at line 6913 of file PlayerbotAI.cpp.
References Quest::GetQuestId(), Quest::GetQuestLevel(), Quest::GetTitle(), and QuestLocalization().
Referenced by _HandleCommandGM(), _HandleCommandQuest(), AddQuest(), ListQuests(), and TurnInQuests().
MakeSpellLink()
void PlayerbotAI::MakeSpellLink (const SpellEntry * sInfo, std::ostringstream & out)
Definition at line 6928 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), SpellEntry::Id, and SpellEntry::SpellName.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), and _HandleCommandSkill().
MakeWeaponSkillLink()
void PlayerbotAI::MakeWeaponSkillLink (const SpellEntry * sInfo, std::ostringstream & out, uint32 skillid)
Definition at line 6921 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), Player::GetSkillMax(), Player::GetSkillValue(), SpellEntry::Id, m_bot, and SpellEntry::SpellName.
Referenced by _HandleCommandSkill().
MovementClear()
void PlayerbotAI::MovementClear ()
Definition at line 4904 of file PlayerbotAI.cpp.
References Unit::clearUnitState(), Unit::GetMotionMaster(), MotionMaster::Initialize(), Unit::IsStandState(), m_bot, Unit::SetStandState(), UNIT_STAND_STATE_STAND, and UNIT_STAT_FOLLOW.
Referenced by DoCombatMovement(), and MovementReset().
MovementReset()
void PlayerbotAI::MovementReset ()
Definition at line 4790 of file PlayerbotAI.cpp.
References DistOverRide, DoTeleport(), FOLLOWAUTOGO_INIT, FOLLOWAUTOGO_OFF, FOLLOWAUTOGO_RESET, FOLLOWAUTOGO_RUN, gDist, Player::GetCorpse(), Unit::GetMotionMaster(), Object::GetTypeId(), gTempDist, gTempDist2, Unit::IsAlive(), Player::IsBeingTeleported(), Unit::IsInCombat(), Unit::IsTaxiFlying(), IsUpOrDown, WorldObject::IsWithinDistInMap(), m_bot, m_combatOrder, PlayerbotMgr::m_confFollowDistance, m_followTarget, m_mgr, m_movementOrder, M_PI_F, MotionMaster::MoveFollow(), MOVEMENT_FOLLOW, MovementClear(), ORDERS_ASSIST, ORDERS_TANK, rand_float(), SetIgnoreUpdateTime(), and TYPEID_PLAYER.
Referenced by _HandleCommandReset(), DoNextCombatManeuver(), SetMovementOrder(), and UpdateAI().
PickPocket()
bool PlayerbotAI::PickPocket (Unit * pTarget)
Definition at line 6026 of file PlayerbotAI.cpp.
References Loot::AutoStore(), Map::GetCreature(), Loot::GetGoldAmount(), Loot::GetLootType(), WorldObject::GetMap(), WorldObject::GetName(), Object::GetObjectGuid(), LOOT_PICKPOCKETING, m_bot, PlayerbotMgr::m_confDebugWhisper, Object::m_loot, m_mgr, Player::ModifyMoney(), NULL_BAG, NULL_SLOT, Loot::Release(), Loot::SendGold(), sLog, and TellMaster().
Referenced by PlayerbotRogueAI::DoNextCombatManeuver().
PlaySound()
void PlayerbotAI::PlaySound (uint32 soundid)
Definition at line 4915 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::SendPacket(), and SMSG_PLAY_SOUND.
Referenced by Announce().
QuestLocalization()
void PlayerbotAI::QuestLocalization (std::string & questTitle, const uint32 questID) const
Definition at line 8097 of file PlayerbotAI.cpp.
References GetMaster(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), sObjectMgr, QuestLocale::Title, and Utf8FitTo().
Referenced by MakeQuestLink().
ReloadAI()
void PlayerbotAI::ReloadAI ()
Definition at line 1402 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, COMBAT_MELEE, COMBAT_RANGED, DRUID_SPEC_FERAL, Unit::getClass(), GetMaster(), HERB_GATHERING, HERB_GATHERING_1, initSpell(), m_bot, m_classAI, m_combatStyle, MINING, MINING_1, SHAMAN_SPEC_ENHANCEMENT, SKINNING, and SKINNING_1.
Referenced by _HandleCommandSkill(), HandleBotOutgoingPacket(), and PlayerbotAI().
RemoveAuction()
bool PlayerbotAI::RemoveAuction (const uint32 auctionid)
Definition at line 8373 of file PlayerbotAI.cpp.
References MailDraft::AddItem(), AUCTION_CANCELED, AUCTION_OK, AUCTION_REMOVED, AuctionEntry::auctionHouseEntry, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CharacterDatabase, AuctionEntry::DeleteFromDB(), AuctionEntry::deposit, AuctionEntry::expireTime, QueryResult::Fetch(), Player::GetSession(), Field::GetUInt32(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemGuidLow, AuctionEntry::itemTemplate, m_bot, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, Database::PQuery(), sAuctionHouseStore, sAuctionMgr, WorldSession::SendAuctionCommandResult(), MailDraft::SendMailTo(), sLog, and AuctionEntry::startbid.
Referenced by findNearbyCreature().
Repair()
void PlayerbotAI::Repair (const uint32 itemid, Creature * rCreature)
Definition at line 8328 of file PlayerbotAI.cpp.
References CMSG_REPAIR_ITEM, DEBUG_LOG, EstRepair(), EstRepairAll(), FindItem(), Guild::GetGuildBankMoney(), Player::GetGuildId(), Player::GetMoney(), Object::GetObjectGuid(), Item::GetPos(), Player::GetRank(), Player::GetSession(), GR_RIGHT_WITHDRAW_REPAIR, Guild::HasRankRight(), m_bot, WorldSession::QueuePacket(), sGuildMgr, and TellMaster().
Referenced by findNearbyCreature().
SelfBuff()
SpellCastResult PlayerbotAI::SelfBuff (uint32 spellId)
Definition at line 5702 of file PlayerbotAI.cpp.
References CastSpell(), Unit::HasAura(), m_bot, SPELL_FAILED_AURA_BOUNCED, and SPELL_FAILED_NOT_KNOWN.
Referenced by PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), and PlayerbotWarlockAI::DoNonCombatActions().
Sell()
void PlayerbotAI::Sell (const uint32 itemid)
Definition at line 8762 of file PlayerbotAI.cpp.
References Player::AddItemToBuyBackSlot(), Cash(), FindItem(), Item::GetBagSlot(), Item::GetCount(), Item::GetProto(), Item::GetSlot(), Item::GetSpellCharges(), m_bot, MakeItemLink(), MAX_ITEM_PROTO_SPELLS, Player::ModifyMoney(), Player::MoveItemFromInventory(), ItemPrototype::SellPrice, _Spell::SpellCharges, ItemPrototype::Spells, and TellMaster().
Referenced by findNearbyCreature().
SellGarbage()
void PlayerbotAI::SellGarbage (Player & player, bool listNonTrash = true, bool bDetailTrashSold = false, bool verbose = true)
Definition at line 8803 of file PlayerbotAI.cpp.
References _doSellItem(), Cash(), Bag::GetBagSize(), Player::GetItemByPos(), Item::GetProto(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, ItemPrototype::ItemId, ItemLocalization(), m_bot, ItemPrototype::Name1, and TellMaster().
SendNotEquipList()
void PlayerbotAI::SendNotEquipList (Player & player)
Definition at line 415 of file PlayerbotAI.cpp.
References Player::CanEquipItem(), EQUIP_ERR_OK, Bag::GetBagSize(), Player::GetItemByPos(), GetMaster(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, Item::IsBag(), m_bot, MakeItemLink(), NULL_SLOT, ChatHandler::SendSysMessage(), and TellMaster().
Referenced by _HandleCommandEquip().
SendOrders()
void PlayerbotAI::SendOrders (Player & player)
Definition at line 1469 of file PlayerbotAI.cpp.
References BOTSTATE_COMBAT, BOTSTATE_DEAD, BOTSTATE_DEADRELEASED, BOTSTATE_FLYING, BOTSTATE_LOOTING, BOTSTATE_NORMAL, BOTSTATE_TAME, CurrentTime(), WorldObject::GetName(), IsInCombat(), m_attackerInfo, m_botState, m_combatOrder, PlayerbotMgr::m_confDebugWhisper, m_DelayAttack, m_followTarget, m_ignoreAIUpdatesUntilTime, m_mgr, m_movementOrder, m_targetAssist, m_targetProtect, MOVEMENT_FOLLOW, MOVEMENT_NONE, MOVEMENT_STAY, ORDERS_ASSIST, ORDERS_HEAL, ORDERS_MAIN_HEAL, ORDERS_MAIN_TANK, ORDERS_NODISPEL, ORDERS_NONE, ORDERS_NOT_MAIN_HEAL, ORDERS_PASSIVE, ORDERS_PRIMARY, ORDERS_PROTECT, ORDERS_RESIST, ORDERS_RESIST_FIRE, ORDERS_RESIST_FROST, ORDERS_RESIST_NATURE, ORDERS_RESIST_SHADOW, ORDERS_TANK, and TellMaster().
Referenced by _HandleCommandOrders().
SendQuestNeedList()
void PlayerbotAI::SendQuestNeedList ()
Definition at line 1193 of file PlayerbotAI.cpp.
References CreatureLocalization(), CreatureInfo::Entry, GameObjectLocalization(), ObjectMgr::GetCreatureTemplate(), ObjectMgr::GetGameObjectInfo(), Player::HasQuestForGO(), GameObjectInfo::id, ItemPrototype::ItemId, ItemLocalization(), m_bot, m_needCreatureOrGOList, m_needItemList, CreatureInfo::Name, GameObjectInfo::name, ItemPrototype::Name1, sObjectMgr, and TellMaster().
Referenced by _HandleCommandQuest().
SendWhisper()
void PlayerbotAI::SendWhisper (const std::string & text, Player & player) const
Definition at line 5380 of file PlayerbotAI.cpp.
References CHAT_MSG_WHISPER, CMSG_MESSAGECHAT, WorldObject::GetName(), Player::GetSession(), LANG_UNIVERSAL, m_bot, and WorldSession::QueuePacket().
Referenced by _HandleCommandAttack(), _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandCast(), _HandleCommandCollect(), _HandleCommandCraft(), _HandleCommandDrop(), _HandleCommandEnchant(), _HandleCommandEquip(), _HandleCommandFind(), _HandleCommandFollow(), _HandleCommandGet(), _HandleCommandGM(), _HandleCommandHelp(), _HandleCommandNeutralize(), _HandleCommandOrders(), _HandleCommandPet(), _HandleCommandProcess(), _HandleCommandPull(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandReset(), _HandleCommandSell(), _HandleCommandSkill(), _HandleCommandSpells(), _HandleCommandStats(), _HandleCommandStay(), _HandleCommandSurvey(), _HandleCommandTalent(), _HandleCommandUse(), CanPull(), HandleBotOutgoingPacket(), HandleCommand(), and TellMaster().
SetActiveTalentSpec()
void PlayerbotAI::SetActiveTalentSpec (TalentSpec ts) inline
Definition at line 1806 of file PlayerbotAI.h.
References m_activeTalentSpec.
Referenced by _HandleCommandTalent().
SetCollectFlag()
void PlayerbotAI::SetCollectFlag (uint8 flag) inline
Definition at line 1945 of file PlayerbotAI.h.
References HasCollectFlag(), and m_collectionFlags.
Referenced by _HandleCommandCollect(), and PlayerbotAI().
SetCombatOrder()
void PlayerbotAI::SetCombatOrder (CombatOrderType co, Unit * target = 0)
Definition at line 4645 of file PlayerbotAI.cpp.
References CharacterDatabase, CurrentTime(), Database::DirectPExecute(), Object::GetGUIDLow(), WorldObject::GetName(), m_bot, m_combatOrder, m_DelayAttack, m_DelayAttackInit, m_targetAssist, m_targetProtect, ORDERS_ASSIST, ORDERS_HEAL, ORDERS_MAIN_HEAL, ORDERS_MAIN_TANK, ORDERS_NONE, ORDERS_NOT_MAIN_HEAL, ORDERS_PASSIVE, ORDERS_PRIMARY, ORDERS_PROTECT, ORDERS_RESET, ORDERS_SECONDARY, ORDERS_TANK, ORDERS_TEMP, and TellMaster().
Referenced by _HandleCommandOrders(), ClearCombatOrder(), CombatOrderRestore(), SetCombatOrderByStr(), and SetGroupCombatOrder().
SetCombatOrderByStr()
void PlayerbotAI::SetCombatOrderByStr (std::string str, Unit * target = 0)
Definition at line 4621 of file PlayerbotAI.cpp.
References FOLLOWAUTOGO_INIT, FOLLOWAUTOGO_OFF, ORDERS_ASSIST, ORDERS_HEAL, ORDERS_MAIN_HEAL, ORDERS_MAIN_TANK, ORDERS_NODISPEL, ORDERS_NOT_MAIN_HEAL, ORDERS_PASSIVE, ORDERS_PROTECT, ORDERS_RESET, ORDERS_RESIST_FIRE, ORDERS_RESIST_FROST, ORDERS_RESIST_NATURE, ORDERS_RESIST_SHADOW, ORDERS_TANK, ORDERS_TEMP_WAIT_TANKAGGRO, and SetCombatOrder().
Referenced by _HandleCommandOrders().
SetCombatStyle()
void PlayerbotAI::SetCombatStyle (CombatStyle cs) inline
Definition at line 1743 of file PlayerbotAI.h.
References m_combatStyle.
Referenced by PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), and PlayerbotHunterAI::DoNonCombatActions().
SetGroupCombatOrder()
void PlayerbotAI::SetGroupCombatOrder (CombatOrderType co)
Definition at line 3442 of file PlayerbotAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), m_bot, SetCombatOrder(), and sObjectMgr.
Referenced by _HandleCommandPull().
SetGroupIgnoreUpdateTime()
void PlayerbotAI::SetGroupIgnoreUpdateTime (uint8 t)
Definition at line 3480 of file PlayerbotAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), m_bot, SetIgnoreUpdateTime(), and sObjectMgr.
Referenced by _HandleCommandPull(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), and PlayerbotWarriorAI::DoFirstCombatManeuver().
SetIgnoreUpdateTime()
void PlayerbotAI::SetIgnoreUpdateTime (uint8 t = 0) inline
Definition at line 1922 of file PlayerbotAI.h.
References m_ignoreAIUpdatesUntilTime.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), _HandleCommandUse(), CastSpell(), DoLoot(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotRogueAI::DoNonCombatActions(), DoTeleport(), findNearbyCreature(), PlayerbotClassAI::FleeFromPointIfCan(), GetCombatTarget(), GroupHoTOnTank(), HandleBotOutgoingPacket(), MovementReset(), SetGroupIgnoreUpdateTime(), TryEmergency(), UpdateAI(), and UseItem().
SetInFront()
void PlayerbotAI::SetInFront (const Unit * obj)
SetMovementOrder()
void PlayerbotAI::SetMovementOrder (MovementOrderType mo, Unit * followTarget = 0)
Definition at line 4782 of file PlayerbotAI.cpp.
References BOTSTATE_LOADING, m_botState, m_followTarget, m_movementOrder, and MovementReset().
Referenced by _HandleCommandFind(), _HandleCommandFollow(), _HandleCommandStay(), CombatOrderRestore(), FollowAutoReset(), PlayerbotAI(), and UpdateAI().
SetQuestNeedCreatures()
void PlayerbotAI::SetQuestNeedCreatures ()
Definition at line 3659 of file PlayerbotAI.cpp.
References Player::GetQuestSlotQuestId(), Player::getQuestStatusMap(), m_bot, QuestStatusData::m_creatureOrGOcount, m_needCreatureOrGOList, QuestStatusData::m_status, MAX_QUEST_LOG_SIZE, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_INCOMPLETE, Quest::ReqCreatureOrGOCount, Quest::ReqCreatureOrGOId, and sObjectMgr.
Referenced by _HandleCommandQuest(), _HandleCommandReset(), AcceptQuest(), AddQuest(), DoNextCombatManeuver(), and PlayerbotAI().
SetQuestNeedItems()
void PlayerbotAI::SetQuestNeedItems ()
Definition at line 3690 of file PlayerbotAI.cpp.
References COLLECT_FLAG_NEAROBJECT, COLLECT_FLAG_QUEST, QueryResult::Fetch(), GAMEOBJECT_TYPE_CHEST, ObjectMgr::GetGameObjectInfo(), Player::GetQuestSlotQuestId(), Player::getQuestStatusMap(), Field::GetUInt32(), HasCollectFlag(), m_bot, m_collectObjects, QuestStatusData::m_itemcount, m_needItemList, QuestStatusData::m_status, MAX_QUEST_LOG_SIZE, QueryResult::NextRow(), Database::PQuery(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_STATUS_INCOMPLETE, Quest::ReqItemCount, Quest::ReqItemId, sObjectMgr, GameObjectInfo::type, and WorldDatabase.
Referenced by _HandleCommandQuest(), _HandleCommandReset(), AcceptQuest(), AddQuest(), HandleBotOutgoingPacket(), and PlayerbotAI().
SetState()
void PlayerbotAI::SetState (BotState state)
Definition at line 3757 of file PlayerbotAI.cpp.
References m_botState.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), _HandleCommandGet(), _HandleCommandPet(), _HandleCommandReset(), _HandleCommandUse(), Attack(), DoLoot(), GetDuelTarget(), GetTaxi(), HandleBotOutgoingPacket(), and UpdateAI().
Talent()
bool PlayerbotAI::Talent (Creature * tCreature)
Definition at line 8303 of file PlayerbotAI.cpp.
References Unit::CastSpell(), Player::GetSession(), m_bot, MSG_TALENT_WIPE_CONFIRM, WorldSession::QueuePacket(), Player::resetTalents(), Player::SendTalentsInfoData(), and TRIGGERED_OLD_TRIGGERED.
Referenced by findNearbyCreature().
TalentSpecDBContainsError()
uint32 PlayerbotAI::TalentSpecDBContainsError ()
Checks whether the TalentSpec database contains any obvious errors.
return 0 -> all ok return x -> return the talentspec_id of the first talentspec that errors out
Definition at line 6227 of file PlayerbotAI.cpp.
References CharacterDatabase, CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, QueryResult::Fetch(), Field::GetCppString(), Field::GetInt32(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), TellMaster(), ValidateGlyph(), ValidateMajorGlyph(), ValidateMinorGlyph(), and ValidateTalent().
Referenced by _HandleCommandGM().
TellMaster() [1/2]
void PlayerbotAI::TellMaster (const char * fmt, ...) const
Definition at line 5369 of file PlayerbotAI.cpp.
References TellMaster().
TellMaster() [2/2]
void PlayerbotAI::TellMaster (const std::string & text) const
Definition at line 5364 of file PlayerbotAI.cpp.
References GetMaster(), and SendWhisper().
Referenced by _HandleCommandMail(), _HandleCommandOrders(), AddAuction(), AddQuest(), ApplyActiveTalentSpec(), BankBalance(), CastPetSpell(), CastSpell(), CombatOrderRestore(), Deposit(), DoLoot(), DoNextCombatManeuver(), PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), DropGarbage(), PlayerbotClassAI::EatDrinkBandage(), GetCombatTarget(), GetTalentSpec(), GetTalentSpecs(), HandleBotOutgoingPacket(), HandleCommand(), HasTool(), ListAuctions(), ListQuests(), PlayerbotDruidAI::Neutralize(), PlayerbotPriestAI::Neutralize(), PickPocket(), PlayerbotWarriorAI::Pull(), Repair(), Sell(), SellGarbage(), SendNotEquipList(), SendOrders(), SendQuestNeedList(), SetCombatOrder(), TalentSpecDBContainsError(), TellMaster(), TurnInQuests(), UpdateAI(), UseItem(), and Withdraw().
TradeCopper()
bool PlayerbotAI::TradeCopper (uint32 copper) private
Definition at line 8050 of file PlayerbotAI.cpp.
References CMSG_SET_TRADE_GOLD, Player::GetSession(), m_bot, and WorldSession::QueuePacket().
Referenced by HandleCommand().
TradeItem()
bool PlayerbotAI::TradeItem (const Item & item, int8 slot = -1) private
Definition at line 8012 of file PlayerbotAI.cpp.
References Item::CanBeTraded(), CMSG_SET_TRADE_ITEM, Item::GetBagSlot(), TradeData::GetItem(), Player::GetSession(), Item::GetSlot(), Player::GetTradeData(), Player::GetTrader(), Item::IsInTrade(), m_bot, WorldSession::QueuePacket(), TradeData::SetItem(), TRADE_SLOT_COUNT, TRADE_SLOT_NONTRADED, and TRADE_SLOT_TRADED_COUNT.
Referenced by HandleCommand().
TryEmergency()
void PlayerbotAI::TryEmergency (Unit * pAttacker)
TryEmergency() Playerbot function to select an item that the bot will use to heal itself on low health without waiting for a heal from a healer.
params:pAttacker Unit* the creature that is attacking the bot return nothing
Definition at line 7904 of file PlayerbotAI.cpp.
References countof, FindBandage(), FindConsumable(), GetManaPercent(), Unit::HasAura(), IsHealer(), m_bot, SetIgnoreUpdateTime(), uPriorizedHealingItemIds, and UseItem().
TurnInQuests()
void PlayerbotAI::TurnInQuests (WorldObject * questgiver)
Definition at line 4211 of file PlayerbotAI.cpp.
References AutoUpgradeEquipment(), Player::CanRewardQuest(), QuestMenu::GetItem(), Object::GetObjectGuid(), Player::GetPlayerMenu(), PlayerMenu::GetQuestMenu(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Quest::GetRewChoiceItemsCount(), WorldObject::IsInMap(), m_bot, QuestMenuItem::m_qId, MakeItemLink(), MakeQuestLink(), QuestMenu::MenuItemCount(), Player::PrepareQuestMenu(), QUEST_STATUS_AVAILABLE, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, Player::RewardQuest(), Quest::RewChoiceItemId, Player::SetSelectionGuid(), sObjectMgr, and TellMaster().
Referenced by CastSpell(), and findNearbyCreature().
UpdateAI()
void PlayerbotAI::UpdateAI (const uint32 p_time)
Definition at line 5031 of file PlayerbotAI.cpp.
References MovementInfo::AddMovementFlag(), AutoUpgradeEquipment(), BOTSTATE_COMBAT, BOTSTATE_DEAD, BOTSTATE_DEADRELEASED, BOTSTATE_DELAYED, BOTSTATE_FLYING, BOTSTATE_LOADING, BOTSTATE_LOOTING, BOTSTATE_NORMAL, BOTSTATE_TAME, Player::BuildPlayerRepop(), CastSpell(), Spell::CheckCast(), MotionMaster::Clear(), ClearCombatOrder(), Unit::clearUnitState(), PlayerbotClassAI::ClearWait(), COLLECT_FLAG_COMBAT, COLLECT_FLAG_LOOT, COLLECT_FLAG_NEAROBJECT, WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, CORPSE_RESURRECTABLE_PVP, CREATURE_TYPEFLAGS_TAMEABLE, CurrentTime(), DistOverRide, DoFlight(), DoLoot(), DoNextCombatManeuver(), PlayerbotClassAI::DoNonCombatActions(), DoTeleport(), EFFECT_INDEX_1, findNearbyCorpse(), findNearbyCreature(), findNearbyGO(), FOLLOWAUTOGO_INIT, FOLLOWAUTOGO_SET, WorldObject::GetAngle(), GetClassAI(), Unit::GetCollisionHeight(), GetCombatOrder(), Player::GetCorpse(), Player::GetCorpseReclaimDelay(), MotionMaster::GetCurrentMovementGeneratorType(), GetCurrentSpell(), Corpse::GetGhostTime(), WorldObject::GetMap(), GetMaster(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::GetPetGuid(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetSession(), GetSpellCharges(), Map::GetTerrain(), Player::GetTrader(), Corpse::GetType(), ObjectAccessor::GetUnit(), WorldSession::HandleCancelMountAuraOpcode(), Unit::HasAura(), HasCollectFlag(), Unit::hasUnitState(), SpellEntry::Id, IDLE_MOTION_TYPE, In_Range(), InterruptCurrentCastingSpell(), Unit::IsAlive(), Spell::IsAutoRepeat(), Player::IsBeingTeleported(), Spell::IsChannelActive(), Unit::IsDead(), IsInCombat(), Unit::IsInCombat(), WorldObject::IsInMap(), Player::IsInWater(), Unit::IsMounted(), IsPositiveSpell(), IsRegenerating(), TerrainInfo::IsSwimmable(), Player::IsSwimming(), WorldObject::IsWithinDistInMap(), SQLStorage::LookupEntry(), m_attackerInfo, m_bot, m_botState, m_combatOrder, m_CraftSpellId, m_DelayAttack, m_DelayAttackInit, m_findNPC, m_followTarget, m_ignoreAIUpdatesUntilTime, m_lootCurrent, m_lootTargets, WorldObject::m_movementInfo, m_ScenarioType, m_spellIdCommand, Spell::m_spellInfo, m_targetCombat, m_targetGuidCommand, WorldLocation::mapid, MotionMaster::MoveChase(), MOVEFLAG_SWIMMING, MOVEMENT_FOLLOW, MovementReset(), ORDERS_ASSIST, ORDERS_TANK, ORDERS_TEMP, ORDERS_TEMP_WAIT_OOC, ORDERS_TEMP_WAIT_TANKAGGRO, MovementInfo::RemoveMovementFlag(), PlayerbotChatHandler::revive(), SCENARIO_PVP_DUEL, Unit::SetFacingTo(), SetIgnoreUpdateTime(), SetMovementOrder(), Player::SetSelectionGuid(), SetState(), SpellCastTargets::setUnitTarget(), SPELL_CAST_OK, Spell::SpellStart(), sSpellTemplate, PlayerbotChatHandler::sysmessage(), TAME_BEAST_1, Player::TeleportTo(), TellMaster(), and UNIT_STAT_CHASE.
UpdateAttackerInfo()
void PlayerbotAI::UpdateAttackerInfo ()
Definition at line 4378 of file PlayerbotAI.cpp.
References Group::GetFirstMember(), Player::GetGroup(), GetMaster(), Unit::GetPet(), Reference< TO, FROM >::getSource(), ThreatManager::getThreatList(), Unit::getThreatManager(), m_attackerInfo, m_bot, GroupReference::next(), and UpdateAttackersForTarget().
Referenced by _HandleCommandReset(), GetCombatTarget(), and GroupTankHoldsAggro().
UpdateAttackersForTarget()
void PlayerbotAI::UpdateAttackersForTarget (Unit * victim) private
Definition at line 4362 of file PlayerbotAI.cpp.
References HostileRefManager::getFirst(), Unit::getHostileRefManager(), Object::GetObjectGuid(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), ThreatManager::getThreat(), Unit::GetVictim(), m_attackerInfo, and HostileReference::next().
Referenced by UpdateAttackerInfo().
UseItem() [1/4]
void PlayerbotAI::UseItem (Item * item)
Definition at line 7776 of file PlayerbotAI.cpp.
References m_bot, and UseItem().
UseItem() [2/4]
void PlayerbotAI::UseItem (Item * item, uint32 targetFlag, ObjectGuid targetGUID)
Definition at line 7804 of file PlayerbotAI.cpp.
References SpellEntry::CastingTimeIndex, SpellCastTimesEntry::CastTime, ItemPrototype::Class, MotionMaster::Clear(), CMSG_OPEN_ITEM, CMSG_QUESTGIVER_ACCEPT_QUEST, CMSG_USE_ITEM, ItemPrototype::Flags, Item::GetBagSlot(), Object::GetEntry(), Unit::GetMotionMaster(), Object::GetObjectGuid(), Item::GetProto(), Player::GetSession(), Item::GetSlot(), GetSpellDuration(), Quest::GetTitle(), ITEM_CLASS_CONSUMABLE, ITEM_FLAG_HAS_LOOT, ITEM_SUBCLASS_FOOD, SQLStorage::LookupEntry(), m_bot, MAX_ITEM_PROTO_SPELLS, WorldSession::QueuePacket(), SetIgnoreUpdateTime(), sObjectMgr, _Spell::SpellId, ItemPrototype::Spells, sSpellCastTimesStore, sSpellTemplate, ItemPrototype::StartQuest, ItemPrototype::SubClass, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_UNIT, TellMaster(), and ObjectGuid::WriteAsPacked().
Referenced by _HandleCommandUse(), AutoUpgradeEquipment(), DoLoot(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotClassAI::EatDrinkBandage(), TryEmergency(), and UseItem().
UseItem() [3/4]
void PlayerbotAI::UseItem (Item * item, uint8 targetInventorySlot)
Definition at line 7782 of file PlayerbotAI.cpp.
References EQUIPMENT_SLOT_END, Player::GetItemByPos(), Object::GetObjectGuid(), INVENTORY_SLOT_BAG_0, m_bot, TARGET_FLAG_ITEM, and UseItem().
UseItem() [4/4]
void PlayerbotAI::UseItem (Item * item, Unit * target)
Definition at line 7795 of file PlayerbotAI.cpp.
References Object::GetObjectGuid(), TARGET_FLAG_UNIT, and UseItem().
ValidateGlyph()
bool PlayerbotAI::ValidateGlyph (uint16 glyph, long charClass) protected
ValidateGlyph tests a glyph against class to see if it belongs to that class - accepts both Major and Minor glyphs.
uint16 glyph: glyph ID long charClass: member of the Classes enum or ClassesCombatPets enum
return true -> ok return false -> not a valid glyph for that class
Definition at line 6732 of file PlayerbotAI.cpp.
References ValidateMajorGlyph(), and ValidateMinorGlyph().
Referenced by TalentSpecDBContainsError().
ValidateMajorGlyph()
bool PlayerbotAI::ValidateMajorGlyph (uint16 glyph, long charClass) protected
ValidateMajorGlyph tests a glyph against class to see if it belongs to that class - only accepts Major glyphs.
uint16 glyph: glyph ID long charClass: member of the Classes enum or ClassesCombatPets enum
return true -> ok return false -> not a valid major glyph for that class
Definition at line 6747 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, DEATH_KNIGHT_MAJOR_GLYPH_OF_ANTIMAGIC_SHELL, DEATH_KNIGHT_MAJOR_GLYPH_OF_BLOOD_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_BONE_SHIELD, DEATH_KNIGHT_MAJOR_GLYPH_OF_CHAINS_OF_ICE, DEATH_KNIGHT_MAJOR_GLYPH_OF_DANCING_RUNE_WEAPON, DEATH_KNIGHT_MAJOR_GLYPH_OF_DARK_COMMAND, DEATH_KNIGHT_MAJOR_GLYPH_OF_DARK_DEATH, DEATH_KNIGHT_MAJOR_GLYPH_OF_DEATH_AND_DECAY, DEATH_KNIGHT_MAJOR_GLYPH_OF_DEATH_GRIP, DEATH_KNIGHT_MAJOR_GLYPH_OF_DEATH_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_DISEASE, DEATH_KNIGHT_MAJOR_GLYPH_OF_FROST_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_HEART_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_HOWLING_BLAST, DEATH_KNIGHT_MAJOR_GLYPH_OF_HUNGERING_COLD, DEATH_KNIGHT_MAJOR_GLYPH_OF_ICEBOUND_FORTITUDE, DEATH_KNIGHT_MAJOR_GLYPH_OF_ICY_TOUCH, DEATH_KNIGHT_MAJOR_GLYPH_OF_OBLITERATE, DEATH_KNIGHT_MAJOR_GLYPH_OF_PLAGUE_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_RUNE_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_RUNE_TAP, DEATH_KNIGHT_MAJOR_GLYPH_OF_SCOURGE_STRIKE, DEATH_KNIGHT_MAJOR_GLYPH_OF_STRANGULATE, DEATH_KNIGHT_MAJOR_GLYPH_OF_THE_GHOUL, DEATH_KNIGHT_MAJOR_GLYPH_OF_UNBREAKABLE_ARMOR, DEATH_KNIGHT_MAJOR_GLYPH_OF_UNHOLY_BLIGHT, DEATH_KNIGHT_MAJOR_GLYPH_OF_VAMPIRIC_BLOOD, DEBUG_LOG, DRUID_MAJOR_GLYPH_OF_BARKSKIN, DRUID_MAJOR_GLYPH_OF_BERSERK, DRUID_MAJOR_GLYPH_OF_CLAW, DRUID_MAJOR_GLYPH_OF_ENTANGLING_ROOTS, DRUID_MAJOR_GLYPH_OF_FOCUS, DRUID_MAJOR_GLYPH_OF_FRENZIED_REGENERATION, DRUID_MAJOR_GLYPH_OF_HEALING_TOUCH, DRUID_MAJOR_GLYPH_OF_HURRICANE, DRUID_MAJOR_GLYPH_OF_INNERVATE, DRUID_MAJOR_GLYPH_OF_INSECT_SWARM, DRUID_MAJOR_GLYPH_OF_LIFEBLOOM, DRUID_MAJOR_GLYPH_OF_MANGLE, DRUID_MAJOR_GLYPH_OF_MAUL, DRUID_MAJOR_GLYPH_OF_MONSOON, DRUID_MAJOR_GLYPH_OF_MOONFIRE, DRUID_MAJOR_GLYPH_OF_NOURISH, DRUID_MAJOR_GLYPH_OF_RAKE, DRUID_MAJOR_GLYPH_OF_RAPID_REJUVENATION, DRUID_MAJOR_GLYPH_OF_REBIRTH, DRUID_MAJOR_GLYPH_OF_REGROWTH, DRUID_MAJOR_GLYPH_OF_REJUVENATION, DRUID_MAJOR_GLYPH_OF_RIP, DRUID_MAJOR_GLYPH_OF_SAVAGE_ROAR, DRUID_MAJOR_GLYPH_OF_SHRED, DRUID_MAJOR_GLYPH_OF_STARFALL, DRUID_MAJOR_GLYPH_OF_STARFIRE, DRUID_MAJOR_GLYPH_OF_SURVIVAL_INSTINCTS, DRUID_MAJOR_GLYPH_OF_SWIFTMEND, DRUID_MAJOR_GLYPH_OF_WILD_GROWTH, DRUID_MAJOR_GLYPH_OF_WRATH, HUNTER_MAJOR_GLYPH_OF_AIMED_SHOT, HUNTER_MAJOR_GLYPH_OF_ARCANE_SHOT, HUNTER_MAJOR_GLYPH_OF_ASPECT_OF_THE_VIPER, HUNTER_MAJOR_GLYPH_OF_BESTIAL_WRATH, HUNTER_MAJOR_GLYPH_OF_CHIMERA_SHOT, HUNTER_MAJOR_GLYPH_OF_DETERRENCE, HUNTER_MAJOR_GLYPH_OF_DISENGAGE, HUNTER_MAJOR_GLYPH_OF_EXPLOSIVE_SHOT, HUNTER_MAJOR_GLYPH_OF_EXPLOSIVE_TRAP, HUNTER_MAJOR_GLYPH_OF_FREEZING_TRAP, HUNTER_MAJOR_GLYPH_OF_FROST_TRAP, HUNTER_MAJOR_GLYPH_OF_HUNTERS_MARK, HUNTER_MAJOR_GLYPH_OF_IMMOLATION_TRAP, HUNTER_MAJOR_GLYPH_OF_KILL_SHOT, HUNTER_MAJOR_GLYPH_OF_MENDING, HUNTER_MAJOR_GLYPH_OF_MULTISHOT, HUNTER_MAJOR_GLYPH_OF_RAPID_FIRE, HUNTER_MAJOR_GLYPH_OF_RAPTOR_STRIKE, HUNTER_MAJOR_GLYPH_OF_SCATTER_SHOT, HUNTER_MAJOR_GLYPH_OF_SERPENT_STING, HUNTER_MAJOR_GLYPH_OF_SNAKE_TRAP, HUNTER_MAJOR_GLYPH_OF_STEADY_SHOT, HUNTER_MAJOR_GLYPH_OF_THE_BEAST, HUNTER_MAJOR_GLYPH_OF_TRUESHOT_AURA, HUNTER_MAJOR_GLYPH_OF_VOLLEY, HUNTER_MAJOR_GLYPH_OF_WYVERN_STING, MAGE_MAJOR_GLYPH_OF_ARCANE_BARRAGE, MAGE_MAJOR_GLYPH_OF_ARCANE_BLAST, MAGE_MAJOR_GLYPH_OF_ARCANE_EXPLOSION, MAGE_MAJOR_GLYPH_OF_ARCANE_MISSILES, MAGE_MAJOR_GLYPH_OF_ARCANE_POWER, MAGE_MAJOR_GLYPH_OF_BLINK, MAGE_MAJOR_GLYPH_OF_DEEP_FREEZE, MAGE_MAJOR_GLYPH_OF_ETERNAL_WATER, MAGE_MAJOR_GLYPH_OF_EVOCATION, MAGE_MAJOR_GLYPH_OF_FIRE_BLAST, MAGE_MAJOR_GLYPH_OF_FIREBALL, MAGE_MAJOR_GLYPH_OF_FROST_NOVA, MAGE_MAJOR_GLYPH_OF_FROSTBOLT, MAGE_MAJOR_GLYPH_OF_FROSTFIRE, MAGE_MAJOR_GLYPH_OF_ICE_ARMOR, MAGE_MAJOR_GLYPH_OF_ICE_BARRIER, MAGE_MAJOR_GLYPH_OF_ICE_BLOCK, MAGE_MAJOR_GLYPH_OF_ICE_LANCE, MAGE_MAJOR_GLYPH_OF_ICY_VEINS, MAGE_MAJOR_GLYPH_OF_INVISIBILITY, MAGE_MAJOR_GLYPH_OF_LIVING_BOMB, MAGE_MAJOR_GLYPH_OF_MAGE_ARMOR, MAGE_MAJOR_GLYPH_OF_MANA_GEM, MAGE_MAJOR_GLYPH_OF_MIRROR_IMAGE, MAGE_MAJOR_GLYPH_OF_MOLTEN_ARMOR, MAGE_MAJOR_GLYPH_OF_POLYMORPH, MAGE_MAJOR_GLYPH_OF_REMOVE_CURSE, MAGE_MAJOR_GLYPH_OF_SCORCH, MAGE_MAJOR_GLYPH_OF_WATER_ELEMENTAL, PALADIN_MAJOR_GLYPH_OF_AVENGERS_SHIELD, PALADIN_MAJOR_GLYPH_OF_AVENGING_WRATH, PALADIN_MAJOR_GLYPH_OF_BEACON_OF_LIGHT, PALADIN_MAJOR_GLYPH_OF_CLEANSING, PALADIN_MAJOR_GLYPH_OF_CONSECRATION, PALADIN_MAJOR_GLYPH_OF_CRUSADER_STRIKE, PALADIN_MAJOR_GLYPH_OF_DIVINE_PLEA, PALADIN_MAJOR_GLYPH_OF_DIVINE_STORM, PALADIN_MAJOR_GLYPH_OF_DIVINITY, PALADIN_MAJOR_GLYPH_OF_EXORCISM, PALADIN_MAJOR_GLYPH_OF_FLASH_OF_LIGHT, PALADIN_MAJOR_GLYPH_OF_HAMMER_OF_JUSTICE, PALADIN_MAJOR_GLYPH_OF_HAMMER_OF_THE_RIGHTEOUS, PALADIN_MAJOR_GLYPH_OF_HAMMER_OF_WRATH, PALADIN_MAJOR_GLYPH_OF_HOLY_LIGHT, PALADIN_MAJOR_GLYPH_OF_HOLY_SHOCK, PALADIN_MAJOR_GLYPH_OF_HOLY_WRATH, PALADIN_MAJOR_GLYPH_OF_JUDGEMENT, PALADIN_MAJOR_GLYPH_OF_RIGHTEOUS_DEFENSE, PALADIN_MAJOR_GLYPH_OF_SALVATION, PALADIN_MAJOR_GLYPH_OF_SEAL_OF_COMMAND, PALADIN_MAJOR_GLYPH_OF_SEAL_OF_LIGHT, PALADIN_MAJOR_GLYPH_OF_SEAL_OF_RIGHTEOUSNESS, PALADIN_MAJOR_GLYPH_OF_SEAL_OF_VENGEANCE, PALADIN_MAJOR_GLYPH_OF_SEAL_OF_WISDOM, PALADIN_MAJOR_GLYPH_OF_SHIELD_OF_RIGHTEOUSNESS, PALADIN_MAJOR_GLYPH_OF_SPIRITUAL_ATTUNEMENT, PALADIN_MAJOR_GLYPH_OF_TURN_EVIL, PRIEST_MAJOR_GLYPH_OF_CIRCLE_OF_HEALING, PRIEST_MAJOR_GLYPH_OF_DISPEL_MAGIC, PRIEST_MAJOR_GLYPH_OF_DISPERSION, PRIEST_MAJOR_GLYPH_OF_FADE, PRIEST_MAJOR_GLYPH_OF_FEAR_WARD, PRIEST_MAJOR_GLYPH_OF_FLASH_HEAL, PRIEST_MAJOR_GLYPH_OF_GUARDIAN_SPIRIT, PRIEST_MAJOR_GLYPH_OF_HOLY_NOVA, PRIEST_MAJOR_GLYPH_OF_HYMN_OF_HOPE, PRIEST_MAJOR_GLYPH_OF_INNER_FIRE, PRIEST_MAJOR_GLYPH_OF_LIGHTWELL, PRIEST_MAJOR_GLYPH_OF_MASS_DISPEL, PRIEST_MAJOR_GLYPH_OF_MIND_CONTROL, PRIEST_MAJOR_GLYPH_OF_MIND_FLAY, PRIEST_MAJOR_GLYPH_OF_MIND_SEAR, PRIEST_MAJOR_GLYPH_OF_PAIN_SUPPRESSION, PRIEST_MAJOR_GLYPH_OF_PENANCE, PRIEST_MAJOR_GLYPH_OF_POWER_WORD_SHIELD, PRIEST_MAJOR_GLYPH_OF_PRAYER_OF_HEALING, PRIEST_MAJOR_GLYPH_OF_PSYCHIC_SCREAM, PRIEST_MAJOR_GLYPH_OF_RENEW, PRIEST_MAJOR_GLYPH_OF_SCOURGE_IMPRISONMENT, PRIEST_MAJOR_GLYPH_OF_SHADOW, PRIEST_MAJOR_GLYPH_OF_SHADOW_WORD_DEATH, PRIEST_MAJOR_GLYPH_OF_SHADOW_WORD_PAIN, PRIEST_MAJOR_GLYPH_OF_SMITE, PRIEST_MAJOR_GLYPH_OF_SPIRIT_OF_REDEMPTION, ROGUE_MAJOR_GLYPH_OF_ADRENALINE_RUSH, ROGUE_MAJOR_GLYPH_OF_AMBUSH, ROGUE_MAJOR_GLYPH_OF_BACKSTAB, ROGUE_MAJOR_GLYPH_OF_BLADE_FLURRY, ROGUE_MAJOR_GLYPH_OF_CLOAK_OF_SHADOWS, ROGUE_MAJOR_GLYPH_OF_CRIPPLING_POISON, ROGUE_MAJOR_GLYPH_OF_DEADLY_THROW, ROGUE_MAJOR_GLYPH_OF_EVASION, ROGUE_MAJOR_GLYPH_OF_EVISCERATE, ROGUE_MAJOR_GLYPH_OF_EXPOSE_ARMOR, ROGUE_MAJOR_GLYPH_OF_FAN_OF_KNIVES, ROGUE_MAJOR_GLYPH_OF_FEINT, ROGUE_MAJOR_GLYPH_OF_GARROTE, ROGUE_MAJOR_GLYPH_OF_GHOSTLY_STRIKE, ROGUE_MAJOR_GLYPH_OF_GOUGE, ROGUE_MAJOR_GLYPH_OF_HEMORRHAGE, ROGUE_MAJOR_GLYPH_OF_HUNGER_FOR_BLOOD, ROGUE_MAJOR_GLYPH_OF_KILLING_SPREE, ROGUE_MAJOR_GLYPH_OF_MUTILATE, ROGUE_MAJOR_GLYPH_OF_PREPARATION, ROGUE_MAJOR_GLYPH_OF_RUPTURE, ROGUE_MAJOR_GLYPH_OF_SAP, ROGUE_MAJOR_GLYPH_OF_SHADOW_DANCE, ROGUE_MAJOR_GLYPH_OF_SINISTER_STRIKE, ROGUE_MAJOR_GLYPH_OF_SLICE_AND_DICE, ROGUE_MAJOR_GLYPH_OF_SPRINT, ROGUE_MAJOR_GLYPH_OF_TRICKS_OF_THE_TRADE, ROGUE_MAJOR_GLYPH_OF_VIGOR, SHAMAN_MAJOR_GLYPH_OF_CHAIN_HEAL, SHAMAN_MAJOR_GLYPH_OF_CHAIN_LIGHTNING, SHAMAN_MAJOR_GLYPH_OF_EARTH_SHIELD, SHAMAN_MAJOR_GLYPH_OF_EARTHLIVING_WEAPON, SHAMAN_MAJOR_GLYPH_OF_ELEMENTAL_MASTERY, SHAMAN_MAJOR_GLYPH_OF_FERAL_SPIRIT, SHAMAN_MAJOR_GLYPH_OF_FIRE_ELEMENTAL_TOTEM, SHAMAN_MAJOR_GLYPH_OF_FIRE_NOVA, SHAMAN_MAJOR_GLYPH_OF_FLAME_SHOCK, SHAMAN_MAJOR_GLYPH_OF_FLAMETONGUE_WEAPON, SHAMAN_MAJOR_GLYPH_OF_FROST_SHOCK, SHAMAN_MAJOR_GLYPH_OF_HEALING_STREAM_TOTEM, SHAMAN_MAJOR_GLYPH_OF_HEALING_WAVE, SHAMAN_MAJOR_GLYPH_OF_HEX, SHAMAN_MAJOR_GLYPH_OF_LAVA, SHAMAN_MAJOR_GLYPH_OF_LAVA_LASH, SHAMAN_MAJOR_GLYPH_OF_LESSER_HEALING_WAVE, SHAMAN_MAJOR_GLYPH_OF_LIGHTNING_BOLT, SHAMAN_MAJOR_GLYPH_OF_LIGHTNING_SHIELD, SHAMAN_MAJOR_GLYPH_OF_RIPTIDE, SHAMAN_MAJOR_GLYPH_OF_SHOCKING, SHAMAN_MAJOR_GLYPH_OF_STONECLAW_TOTEM, SHAMAN_MAJOR_GLYPH_OF_STORMSTRIKE, SHAMAN_MAJOR_GLYPH_OF_THUNDER, SHAMAN_MAJOR_GLYPH_OF_TOTEM_OF_WRATH, SHAMAN_MAJOR_GLYPH_OF_WATER_MASTERY, SHAMAN_MAJOR_GLYPH_OF_WINDFURY_WEAPON, WARLOCK_MAJOR_GLYPH_OF_CHAOS_BOLT, WARLOCK_MAJOR_GLYPH_OF_CONFLAGRATE, WARLOCK_MAJOR_GLYPH_OF_CORRUPTION, WARLOCK_MAJOR_GLYPH_OF_CURSE_OF_AGONY, WARLOCK_MAJOR_GLYPH_OF_DEATH_COIL, WARLOCK_MAJOR_GLYPH_OF_DEMONIC_CIRCLE, WARLOCK_MAJOR_GLYPH_OF_FEAR, WARLOCK_MAJOR_GLYPH_OF_FELGUARD, WARLOCK_MAJOR_GLYPH_OF_FELHUNTER, WARLOCK_MAJOR_GLYPH_OF_HAUNT, WARLOCK_MAJOR_GLYPH_OF_HEALTH_FUNNEL, WARLOCK_MAJOR_GLYPH_OF_HEALTHSTONE, WARLOCK_MAJOR_GLYPH_OF_HOWL_OF_TERROR, WARLOCK_MAJOR_GLYPH_OF_IMMOLATE, WARLOCK_MAJOR_GLYPH_OF_IMP, WARLOCK_MAJOR_GLYPH_OF_INCINERATE, WARLOCK_MAJOR_GLYPH_OF_LIFE_TAP, WARLOCK_MAJOR_GLYPH_OF_METAMORPHOSIS, WARLOCK_MAJOR_GLYPH_OF_QUICK_DECAY, WARLOCK_MAJOR_GLYPH_OF_SEARING_PAIN, WARLOCK_MAJOR_GLYPH_OF_SHADOW_BOLT, WARLOCK_MAJOR_GLYPH_OF_SHADOWBURN, WARLOCK_MAJOR_GLYPH_OF_SHADOWFLAME, WARLOCK_MAJOR_GLYPH_OF_SIPHON_LIFE, WARLOCK_MAJOR_GLYPH_OF_SOUL_LINK, WARLOCK_MAJOR_GLYPH_OF_SOULSTONE, WARLOCK_MAJOR_GLYPH_OF_SUCCUBUS, WARLOCK_MAJOR_GLYPH_OF_UNSTABLE_AFFLICTION, WARLOCK_MAJOR_GLYPH_OF_VOIDWALKER, WARRIOR_MAJOR_GLYPH_OF_BARBARIC_INSULTS, WARRIOR_MAJOR_GLYPH_OF_BLADESTORM, WARRIOR_MAJOR_GLYPH_OF_BLOCKING, WARRIOR_MAJOR_GLYPH_OF_BLOODTHIRST, WARRIOR_MAJOR_GLYPH_OF_CLEAVING, WARRIOR_MAJOR_GLYPH_OF_DEVASTATE, WARRIOR_MAJOR_GLYPH_OF_ENRAGED_REGENERATION, WARRIOR_MAJOR_GLYPH_OF_EXECUTION, WARRIOR_MAJOR_GLYPH_OF_HAMSTRING, WARRIOR_MAJOR_GLYPH_OF_HEROIC_STRIKE, WARRIOR_MAJOR_GLYPH_OF_INTERVENE, WARRIOR_MAJOR_GLYPH_OF_LAST_STAND, WARRIOR_MAJOR_GLYPH_OF_MORTAL_STRIKE, WARRIOR_MAJOR_GLYPH_OF_OVERPOWER, WARRIOR_MAJOR_GLYPH_OF_RAPID_CHARGE, WARRIOR_MAJOR_GLYPH_OF_RENDING, WARRIOR_MAJOR_GLYPH_OF_RESONATING_POWER, WARRIOR_MAJOR_GLYPH_OF_REVENGE, WARRIOR_MAJOR_GLYPH_OF_SHIELD_WALL, WARRIOR_MAJOR_GLYPH_OF_SHOCKWAVE, WARRIOR_MAJOR_GLYPH_OF_SPELL_REFLECTION, WARRIOR_MAJOR_GLYPH_OF_SUNDER_ARMOR, WARRIOR_MAJOR_GLYPH_OF_SWEEPING_STRIKES, WARRIOR_MAJOR_GLYPH_OF_TAUNT, WARRIOR_MAJOR_GLYPH_OF_VICTORY_RUSH, WARRIOR_MAJOR_GLYPH_OF_VIGILANCE, and WARRIOR_MAJOR_GLYPH_OF_WHIRLWIND.
Referenced by TalentSpecDBContainsError(), and ValidateGlyph().
ValidateMinorGlyph()
bool PlayerbotAI::ValidateMinorGlyph (uint16 glyph, long charClass) protected
ValidateMinorGlyph tests a glyph against class to see if it belongs to that class - only accepts Minor glyphs.
uint16 glyph: glyph ID long charClass: member of the Classes enum or ClassesCombatPets enum
return true -> ok return false -> not a valid minor glyph for that class
Definition at line 6824 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, DEATH_KNIGHT_MINOR_GLYPH_OF_BLOOD_TAP, DEATH_KNIGHT_MINOR_GLYPH_OF_CORPSE_EXPLOSION, DEATH_KNIGHT_MINOR_GLYPH_OF_DEATHS_EMBRACE, DEATH_KNIGHT_MINOR_GLYPH_OF_HORN_OF_WINTER, DEATH_KNIGHT_MINOR_GLYPH_OF_PESTILENCE, DEATH_KNIGHT_MINOR_GLYPH_OF_RAISE_DEAD, DEATH_KNIGHT_MINOR_GLYPH_OF_RAISE_DEAD2, DEBUG_LOG, DRUID_MINOR_GLYPH_OF_AQUATIC_FORM, DRUID_MINOR_GLYPH_OF_CHALLENGING_ROAR, DRUID_MINOR_GLYPH_OF_DASH, DRUID_MINOR_GLYPH_OF_THE_WILD, DRUID_MINOR_GLYPH_OF_THORNS, DRUID_MINOR_GLYPH_OF_TYPHOON, DRUID_MINOR_GLYPH_OF_UNBURDENED_REBIRTH, HUNTER_MINOR_GLYPH_OF_FEIGN_DEATH, HUNTER_MINOR_GLYPH_OF_MEND_PET, HUNTER_MINOR_GLYPH_OF_POSSESSED_STRENGTH, HUNTER_MINOR_GLYPH_OF_REVIVE_PET, HUNTER_MINOR_GLYPH_OF_SCARE_BEAST, HUNTER_MINOR_GLYPH_OF_THE_PACK, MAGE_MINOR_GLYPH_OF_ARCANE_INTELLECT, MAGE_MINOR_GLYPH_OF_BLAST_WAVE, MAGE_MINOR_GLYPH_OF_FIRE_WARD, MAGE_MINOR_GLYPH_OF_FROST_ARMOR, MAGE_MINOR_GLYPH_OF_FROST_WARD, MAGE_MINOR_GLYPH_OF_SLOW_FALL, MAGE_MINOR_GLYPH_OF_THE_PENGUIN, PALADIN_MINOR_GLYPH_OF_BLESSING_OF_KINGS, PALADIN_MINOR_GLYPH_OF_BLESSING_OF_MIGHT, PALADIN_MINOR_GLYPH_OF_BLESSING_OF_WISDOM, PALADIN_MINOR_GLYPH_OF_LAY_ON_HANDS, PALADIN_MINOR_GLYPH_OF_SENSE_UNDEAD, PALADIN_MINOR_GLYPH_OF_THE_WISE, PRIEST_MINOR_GLYPH_OF_FADING, PRIEST_MINOR_GLYPH_OF_FORTITUDE, PRIEST_MINOR_GLYPH_OF_LEVITATE, PRIEST_MINOR_GLYPH_OF_SHACKLE_UNDEAD, PRIEST_MINOR_GLYPH_OF_SHADOW_PROTECTION, PRIEST_MINOR_GLYPH_OF_SHADOWFIEND, ROGUE_MINOR_GLYPH_OF_BLURRED_SPEED, ROGUE_MINOR_GLYPH_OF_DISTRACT, ROGUE_MINOR_GLYPH_OF_PICK_LOCK, ROGUE_MINOR_GLYPH_OF_PICK_POCKET, ROGUE_MINOR_GLYPH_OF_SAFE_FALL, ROGUE_MINOR_GLYPH_OF_VANISH, SHAMAN_MINOR_GLYPH_OF_ASTRAL_RECALL, SHAMAN_MINOR_GLYPH_OF_GHOST_WOLF, SHAMAN_MINOR_GLYPH_OF_RENEWED_LIFE, SHAMAN_MINOR_GLYPH_OF_THUNDERSTORM, SHAMAN_MINOR_GLYPH_OF_WATER_BREATHING, SHAMAN_MINOR_GLYPH_OF_WATER_SHIELD, SHAMAN_MINOR_GLYPH_OF_WATER_WALKING, WARLOCK_MINOR_GLYPH_OF_DRAIN_SOUL, WARLOCK_MINOR_GLYPH_OF_ENSLAVE_DEMON, WARLOCK_MINOR_GLYPH_OF_KILROGG, WARLOCK_MINOR_GLYPH_OF_SOULS, WARLOCK_MINOR_GLYPH_OF_UNENDING_BREATH, WARRIOR_MINOR_GLYPH_OF_BATTLE, WARRIOR_MINOR_GLYPH_OF_BLOODRAGE, WARRIOR_MINOR_GLYPH_OF_CHARGE, WARRIOR_MINOR_GLYPH_OF_COMMAND, WARRIOR_MINOR_GLYPH_OF_ENDURING_VICTORY, WARRIOR_MINOR_GLYPH_OF_MOCKING_BLOW, and WARRIOR_MINOR_GLYPH_OF_THUNDER_CLAP.
Referenced by TalentSpecDBContainsError(), and ValidateGlyph().
ValidateTalent()
bool PlayerbotAI::ValidateTalent (uint16 talent, long charClass) protected
ValidateTalent tests a talent against class to see if it belongs to that class.
uint16 talent: talent ID long charClass: member of the Classes enum or ClassesCombatPets enum
return true -> ok return false -> not a valid talent for that class
Definition at line 6646 of file PlayerbotAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PET_CUNNING, CLASS_PET_FEROCITY, CLASS_PET_TENACITY, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, DEATHKNIGHT_ABOMINATIONS_MIGHT, DEATHKNIGHT_ACCLIMATION, DEATHKNIGHT_ANNIHILATION, DEATHKNIGHT_ANTICIPATION, DEATHKNIGHT_ANTIMAGIC_ZONE, DEATHKNIGHT_BLACK_ICE, DEATHKNIGHT_BLADE_BARRIER, DEATHKNIGHT_BLADED_ARMOR, DEATHKNIGHT_BLOOD_GORGED, DEATHKNIGHT_BLOOD_OF_THE_NORTH, DEATHKNIGHT_BLOOD_WORMS, DEATHKNIGHT_BLOODCAKED_BLADE, DEATHKNIGHT_BLOODY_STRIKES, DEATHKNIGHT_BLOODY_VENGEANCE, DEATHKNIGHT_BONE_SHIELD, DEATHKNIGHT_BUTCHERY, DEATHKNIGHT_CHILL_OF_THE_GRAVE, DEATHKNIGHT_CHILLBLAINS, DEATHKNIGHT_CORPSE_EXPLOSION, DEATHKNIGHT_CRYPT_FEVER, DEATHKNIGHT_DANCING_RUNE_WEAPON, DEATHKNIGHT_DARK_CONVICTION, DEATHKNIGHT_DEATH_RUNE_MASTERY, DEATHKNIGHT_DEATHCHILL, DEATHKNIGHT_DESECRATION, DEATHKNIGHT_DESOLATION, DEATHKNIGHT_DIRGE, DEATHKNIGHT_EBON_PLAGUEBRINGER, DEATHKNIGHT_ENDLESS_WINTER, DEATHKNIGHT_EPIDEMIC, DEATHKNIGHT_FRIGID_DREADPLATE, DEATHKNIGHT_FROST_STRIKE, DEATHKNIGHT_GHOUL_FRENZY, DEATHKNIGHT_GLACIER_ROT, DEATHKNIGHT_GUILE_OF_GOREFIEND, DEATHKNIGHT_HEART_STRIKE, DEATHKNIGHT_HOWLING_BLAST, DEATHKNIGHT_HUNGERING_COLD, DEATHKNIGHT_HYSTERIA, DEATHKNIGHT_ICY_REACH, DEATHKNIGHT_ICY_TALONS, DEATHKNIGHT_IMPROVED_BLOOD_PRESENCE, DEATHKNIGHT_IMPROVED_DEATH_STRIKE, DEATHKNIGHT_IMPROVED_FROST_PRESENCE, DEATHKNIGHT_IMPROVED_ICY_TALONS, DEATHKNIGHT_IMPROVED_ICY_TOUCH, DEATHKNIGHT_IMPROVED_RUNE_TAP, DEATHKNIGHT_IMPROVED_UNHOLY_PRESENCE, DEATHKNIGHT_IMPURITY, DEATHKNIGHT_KILLING_MACHINE, DEATHKNIGHT_LICHBORNE, DEATHKNIGHT_MAGIC_SUPPRESSION, DEATHKNIGHT_MARK_OF_BLOOD, DEATHKNIGHT_MASTER_OF_GHOULS, DEATHKNIGHT_MERCILESS_COMBAT, DEATHKNIGHT_MIGHT_OF_MOGRAINE, DEATHKNIGHT_MORBIDITY, DEATHKNIGHT_NECROSIS, DEATHKNIGHT_NERVES_OF_COLD_STEEL, DEATHKNIGHT_NIGHT_OF_THE_DEAD, DEATHKNIGHT_ON_A_PALE_HORSE, DEATHKNIGHT_OUTBREAK, DEATHKNIGHT_RAGE_OF_RIVENDARE, DEATHKNIGHT_RAVENOUS_DEAD, DEATHKNIGHT_REAPING, DEATHKNIGHT_RIME, DEATHKNIGHT_RUNE_TAP, DEATHKNIGHT_RUNIC_POWER_MASTERY, DEATHKNIGHT_SCENT_OF_BLOOD, DEATHKNIGHT_SCOURGE_STRIKE, DEATHKNIGHT_SPELL_DEFLECTION, DEATHKNIGHT_SUBVERSION, DEATHKNIGHT_SUDDEN_DOOM, DEATHKNIGHT_SUMMON_GARGOYLE, DEATHKNIGHT_THREAT_OF_THASSARIAN, DEATHKNIGHT_TOUGHNESS, DEATHKNIGHT_TUNDRA_STALKER, DEATHKNIGHT_TWOHANDED_WEAPON_SPECIALIZATION, DEATHKNIGHT_UNBREAKABLE_ARMOR, DEATHKNIGHT_UNHOLY_BLIGHT, DEATHKNIGHT_UNHOLY_COMMAND, DEATHKNIGHT_VAMPIRIC_BLOOD, DEATHKNIGHT_VENDETTA, DEATHKNIGHT_VETERAN_OF_THE_THIRD_WAR, DEATHKNIGHT_VICIOUS_STRIKES, DEATHKNIGHT_VIRULENCE, DEATHKNIGHT_WANDERING_PLAGUE, DEATHKNIGHT_WILL_OF_THE_NECROPOLIS, DEBUG_LOG, DRUID_BALANCE_OF_POWER, DRUID_BERSERK, DRUID_BRAMBLES, DRUID_BRUTAL_IMPACT, DRUID_CELESTIAL_FOCUS, DRUID_DREAMSTATE, DRUID_EARTH_AND_MOON, DRUID_ECLIPSE, DRUID_EMPOWERED_REJUVENATION, DRUID_EMPOWERED_TOUCH, DRUID_FERAL_AGGRESSION, DRUID_FERAL_CHARGE, DRUID_FERAL_INSTINCT, DRUID_FERAL_SWIFTNESS, DRUID_FEROCITY, DRUID_FORCE_OF_NATURE, DRUID_FUROR, DRUID_GALE_WINDS, DRUID_GENESIS, DRUID_GIFT_OF_NATURE, DRUID_GIFT_OF_THE_EARTHMOTHER, DRUID_HEART_OF_THE_WILD, DRUID_IMPROVED_BARKSKIN, DRUID_IMPROVED_FAERIE_FIRE, DRUID_IMPROVED_INSECT_SWARM, DRUID_IMPROVED_LEADER_OF_THE_PACK, DRUID_IMPROVED_MANGLE, DRUID_IMPROVED_MARK_OF_THE_WILD, DRUID_IMPROVED_MOONFIRE, DRUID_IMPROVED_MOONKIN_FORM, DRUID_IMPROVED_REJUVENATION, DRUID_IMPROVED_TRANQUILITY, DRUID_IMPROVED_TREE_OF_LIFE, DRUID_INFECTED_WOUNDS, DRUID_INSECT_SWARM, DRUID_INTENSITY, DRUID_KING_OF_THE_JUNGLE, DRUID_LEADER_OF_THE_PACK, DRUID_LIVING_SEED, DRUID_LIVING_SPIRIT, DRUID_LUNAR_GUIDANCE, DRUID_MANGLE, DRUID_MASTER_SHAPESHIFTER, DRUID_MOONFURY, DRUID_MOONGLOW, DRUID_MOONKIN_FORM, DRUID_NATURAL_PERFECTION, DRUID_NATURAL_REACTION, DRUID_NATURAL_SHAPESHIFTER, DRUID_NATURALIST, DRUID_NATURES_BOUNTY, DRUID_NATURES_FOCUS, DRUID_NATURES_GRACE, DRUID_NATURES_MAJESTY, DRUID_NATURES_REACH, DRUID_NATURES_SPLENDOR, DRUID_NATURES_SWIFTNESS, DRUID_NURTURING_INSTINCT, DRUID_OMEN_OF_CLARITY, DRUID_OWLKIN_FRENZY, DRUID_PREDATORY_INSTINCTS, DRUID_PREDATORY_STRIKES, DRUID_PRIMAL_FURY, DRUID_PRIMAL_GORE, DRUID_PRIMAL_PRECISION, DRUID_PRIMAL_TENACITY, DRUID_PROTECTOR_OF_THE_PACK, DRUID_REND_AND_TEAR, DRUID_REVITALIZE, DRUID_SAVAGE_FURY, DRUID_SHARPENED_CLAWS, DRUID_SHREDDING_ATTACKS, DRUID_STARFALL, DRUID_STARLIGHT_WRATH, DRUID_SUBTLETY, DRUID_SURVIVAL_INSTINCTS, DRUID_SURVIVAL_OF_THE_FITTEST, DRUID_SWIFTMEND, DRUID_THICK_HIDE, DRUID_TRANQUIL_SPIRIT, DRUID_TREE_OF_LIFE, DRUID_TYPHOON, DRUID_VENGEANCE, DRUID_WILD_GROWTH, DRUID_WRATH_OF_CENARIUS, HUNTER_AIMED_SHOT, HUNTER_ANIMAL_HANDLER, HUNTER_ASPECT_MASTERY, HUNTER_BARRAGE, HUNTER_BEAST_MASTERY, HUNTER_BESTIAL_DISCIPLINE, HUNTER_BESTIAL_WRATH, HUNTER_BLACK_ARROW, HUNTER_CAREFUL_AIM, HUNTER_CATLIKE_REFLEXES, HUNTER_CHIMERA_SHOT, HUNTER_COBRA_STRIKES, HUNTER_COMBAT_EXPERIENCE, HUNTER_CONCUSSIVE_BARRAGE, HUNTER_COUNTERATTACK, HUNTER_DEFLECTION, HUNTER_EFFICIENCY, HUNTER_ENDURANCE_TRAINING, HUNTER_ENTRAPMENT, HUNTER_EXPLOSIVE_SHOT, HUNTER_EXPOSE_WEAKNESS, HUNTER_FEROCIOUS_INSPIRATION, HUNTER_FEROCITY, HUNTER_FOCUSED_AIM, HUNTER_FOCUSED_FIRE, HUNTER_FRENZY, HUNTER_GO_FOR_THE_THROAT, HUNTER_HAWK_EYE, HUNTER_HUNTER_VS_WILD, HUNTER_HUNTING_PARTY, HUNTER_IMPROVED_ARCANE_SHOT, HUNTER_IMPROVED_ASPECT_OF_THE_HAWK, HUNTER_IMPROVED_ASPECT_OF_THE_MONKEY, HUNTER_IMPROVED_BARRAGE, HUNTER_IMPROVED_CONCUSSIVE_SHOT, HUNTER_IMPROVED_HUNTERS_MARK, HUNTER_IMPROVED_MEND_PET, HUNTER_IMPROVED_REVIVE_PET, HUNTER_IMPROVED_STEADY_SHOT, HUNTER_IMPROVED_STINGS, HUNTER_IMPROVED_TRACKING, HUNTER_INTIMIDATION, HUNTER_INVIGORATION, HUNTER_KILLER_INSTINCT, HUNTER_KINDRED_SPIRITS, HUNTER_LETHAL_SHOTS, HUNTER_LIGHTNING_REFLEXES, HUNTER_LOCK_AND_LOAD, HUNTER_LONGEVITY, HUNTER_MARKED_FOR_DEATH, HUNTER_MASTER_MARKSMAN, HUNTER_MASTER_TACTICIAN, HUNTER_MORTAL_SHOTS, HUNTER_NOXIOUS_STINGS, HUNTER_PATHFINDING, HUNTER_PIERCING_SHOTS, HUNTER_POINT_OF_NO_ESCAPE, HUNTER_RANGED_WEAPON_SPECIALIZATION, HUNTER_RAPID_KILLING, HUNTER_RAPID_RECUPERATION, HUNTER_READINESS, HUNTER_RESOURCEFULNESS, HUNTER_SAVAGE_STRIKES, HUNTER_SCATTER_SHOT, HUNTER_SERPENTS_SWIFTNESS, HUNTER_SILENCING_SHOT, HUNTER_SNIPER_TRAINING, HUNTER_SPIRIT_BOND, HUNTER_SUREFOOTED, HUNTER_SURVIVAL_INSTINCTS, HUNTER_SURVIVAL_TACTICS, HUNTER_SURVIVALIST, HUNTER_THE_BEAST_WITHIN, HUNTER_THICK_HIDE, HUNTER_THRILL_OF_THE_HUNT, HUNTER_TNT, HUNTER_TRAP_MASTERY, HUNTER_TRUESHOT_AURA, HUNTER_UNLEASHED_FURY, HUNTER_WILD_QUIVER, HUNTER_WYVERN_STING, MAGE_ARCANE_BARRAGE, MAGE_ARCANE_CONCENTRATION, MAGE_ARCANE_EMPOWERMENT, MAGE_ARCANE_FLOWS, MAGE_ARCANE_FOCUS, MAGE_ARCANE_FORTITUDE, MAGE_ARCANE_INSTABILITY, MAGE_ARCANE_MEDITATION, MAGE_ARCANE_MIND, MAGE_ARCANE_POTENCY, MAGE_ARCANE_POWER, MAGE_ARCANE_SHIELDING, MAGE_ARCANE_STABILITY, MAGE_ARCANE_SUBTLETY, MAGE_ARCTIC_REACH, MAGE_ARCTIC_WINDS, MAGE_BLAST_WAVE, MAGE_BLAZING_SPEED, MAGE_BRAIN_FREEZE, MAGE_BURNING_DETERMINATION, MAGE_BURNING_SOUL, MAGE_BURNOUT, MAGE_CHILLD_TO_THE_BONE, MAGE_COLD_AS_ICE, MAGE_COLD_SNAP, MAGE_COMBUSTION, MAGE_CRITICAL_MASS, MAGE_DEEP_FREEZE, MAGE_DRAGONS_BREATH, MAGE_EMPOWERED_FIRE, MAGE_EMPOWERED_FROSTBOLT, MAGE_ENDURING_WINTER, MAGE_FIERY_PAYBACK, MAGE_FINGERS_OF_FROST, MAGE_FIRE_POWER, MAGE_FIRESTARTER, MAGE_FLAME_THROWING, MAGE_FOCUS_MAGIC, MAGE_FROST_CHANNELING, MAGE_FROST_WARDING, MAGE_FROSTBITE, MAGE_FROZEN_CORE, MAGE_HOT_STREAK, MAGE_ICE_BARRIER, MAGE_ICE_FLOES, MAGE_ICE_SHARDS, MAGE_ICY_VEINS, MAGE_IGNITE, MAGE_IMPACT, MAGE_IMPROVED_BLINK, MAGE_IMPROVED_BLIZZARD, MAGE_IMPROVED_CONE_OF_COLD, MAGE_IMPROVED_COUNTERSPELL, MAGE_IMPROVED_FIRE_BLAST, MAGE_IMPROVED_FIREBALL, MAGE_IMPROVED_FROSTBOLT, MAGE_IMPROVED_SCORCH, MAGE_INCANTERS_ABSORPTION, MAGE_INCINERATION, MAGE_LIVING_BOMB, MAGE_MAGIC_ABSORPTION, MAGE_MAGIC_ATTUNEMENT, MAGE_MASTER_OF_ELEMENTS, MAGE_MIND_MASTERY, MAGE_MISSILE_BARRAGE, MAGE_MOLTEN_FURY, MAGE_MOLTEN_SHIELDS, MAGE_NETHERWIND_PRESENCE, MAGE_PERMAFROST, MAGE_PIERCING_ICE, MAGE_PLAYING_WITH_FIRE, MAGE_PRECISION, MAGE_PRESENCE_OF_MIND, MAGE_PRISMATIC_CLOAK, MAGE_PYROBLAST, MAGE_PYROMANIAC, MAGE_SHATTER, MAGE_SHATTERED_BARRIER, MAGE_SLOW, MAGE_SPELL_IMPACT, MAGE_SPELL_POWER, MAGE_STUDENT_OF_THE_MIND, MAGE_SUMMON_WATER_ELEMENTAL, MAGE_TORMENT_THE_WEAK, MAGE_WINTERS_CHILL, MAGE_WORLD_IN_FLAMES, PALADIN_ANTICIPATION, PALADIN_ARDENT_DEFENDER, PALADIN_AURA_MASTERY, PALADIN_AVENGERS_SHIELD, PALADIN_BEACON_OF_LIGHT, PALADIN_BENEDICTION, PALADIN_BLESSED_HANDS, PALADIN_BLESSED_LIFE, PALADIN_BLESSING_OF_SANCTUARY, PALADIN_COMBAT_EXPERTISE, PALADIN_CONVICTION, PALADIN_CRUSADE, PALADIN_CRUSADER_STRIKE, PALADIN_DEFLECTION, PALADIN_DIVINE_FAVOR, PALADIN_DIVINE_GUARDIAN, PALADIN_DIVINE_ILLUMINATION, PALADIN_DIVINE_INTELLECT, PALADIN_DIVINE_PURPOSE, PALADIN_DIVINE_SACRIFICE, PALADIN_DIVINE_STORM, PALADIN_DIVINE_STRENGTH, PALADIN_DIVINITY, PALADIN_ENLIGHTENED_JUDGEMENTS, PALADIN_EYE_FOR_AN_EYE, PALADIN_FANATICISM, PALADIN_GUARDED_BY_THE_LIGHT, PALADIN_GUARDIANS_FAVOR, PALADIN_HAMMER_OF_THE_RIGHTEOUS, PALADIN_HEALING_LIGHT, PALADIN_HEART_OF_THE_CRUSADER, PALADIN_HOLY_GUIDANCE, PALADIN_HOLY_POWER, PALADIN_HOLY_SHIELD, PALADIN_HOLY_SHOCK, PALADIN_ILLUMINATION, PALADIN_IMPROVED_BLESSING_OF_MIGHT, PALADIN_IMPROVED_BLESSING_OF_WISDOM, PALADIN_IMPROVED_CONCENTRATION_AURA, PALADIN_IMPROVED_DEVOTION_AURA, PALADIN_IMPROVED_HAMMER_OF_JUSTICE, PALADIN_IMPROVED_JUDGEMENTS, PALADIN_IMPROVED_LAY_ON_HANDS, PALADIN_IMPROVED_RIGHTEOUS_FURY, PALADIN_INFUSION_OF_LIGHT, PALADIN_JUDGEMENT_OF_THE_JUST, PALADIN_JUDGEMENTS_OF_THE_PURE, PALADIN_JUDGEMENTS_OF_THE_WISE, PALADIN_LIGHTS_GRACE, PALADIN_ONEHANDED_WEAPON_SPECIALIZATION, PALADIN_PURE_OF_HEART, PALADIN_PURIFYING_POWER, PALADIN_PURSUIT_OF_JUSTICE, PALADIN_RECKONING, PALADIN_REDOUBT, PALADIN_REPENTANCE, PALADIN_RIGHTEOUS_VENGEANCE, PALADIN_SACRED_CLEANSING, PALADIN_SACRED_DUTY, PALADIN_SANCTIFIED_LIGHT, PALADIN_SANCTIFIED_RETRIBUTION, PALADIN_SANCTIFIED_WRATH, PALADIN_SANCTITY_OF_BATTLE, PALADIN_SEAL_OF_COMMAND, PALADIN_SEALS_OF_THE_PURE, PALADIN_SHEATH_OF_LIGHT, PALADIN_SHIELD_OF_THE_TEMPLAR, PALADIN_SPIRITUAL_ATTUNEMENT, PALADIN_SPIRITUAL_FOCUS, PALADIN_STOICISM, PALADIN_SWIFT_RETRIBUTION, PALADIN_THE_ART_OF_WAR, PALADIN_TOUCHER_BY_THE_LIGHT, PALADIN_TOUGHNESS, PALADIN_TWOHANDED_WEAPON_SPECIALIZATION, PALADIN_UNYIELDING_FAITH, PALADIN_VENGEANCE, PALADIN_VINDICATION, PET_CUNNING_BOARS_SPEED, PET_CUNNING_BULLHEADED, PET_CUNNING_CARRION_FEEDER, PET_CUNNING_COBRA_REFLEXES, PET_CUNNING_CORNERED, PET_CUNNING_CULLING_THE_HERD, PET_CUNNING_DASHDIVE1, PET_CUNNING_DASHDIVE2, PET_CUNNING_FEEDING_FRENZY, PET_CUNNING_GRACE_OF_THE_MANTIS, PET_CUNNING_GREAT_RESISTANCE, PET_CUNNING_GREAT_STAMINA, PET_CUNNING_LIONHEARTED, PET_CUNNING_MOBILITY1, PET_CUNNING_MOBILITY2, PET_CUNNING_NATURAL_ARMOR, PET_CUNNING_OWLS_FOCUS, PET_CUNNING_ROAR_OF_RECOVERY, PET_CUNNING_ROAR_OF_SACRIFICE, PET_CUNNING_SPIKED_COLLAR, PET_CUNNING_WILD_HUNT, PET_CUNNING_WOLVERINE_BITE, PET_FEROCITY_BLOODTHIRSTY, PET_FEROCITY_BOARS_SPEED, PET_FEROCITY_CALL_OF_THE_WILD, PET_FEROCITY_CHARGESWOOP1, PET_FEROCITY_CHARGESWOOP2, PET_FEROCITY_COBRA_REFLEXES, PET_FEROCITY_CULLING_THE_HERD, PET_FEROCITY_DASHDIVE1, PET_FEROCITY_DASHDIVE2, PET_FEROCITY_GREAT_RESISTANCE, PET_FEROCITY_GREAT_STAMINA, PET_FEROCITY_HEART_OF_THE_PHOENIX, PET_FEROCITY_IMPROVED_COWER, PET_FEROCITY_LICK_YOUR_WOUNDS, PET_FEROCITY_LIONHEARTED, PET_FEROCITY_NATURAL_ARMOR, PET_FEROCITY_RABID, PET_FEROCITY_SHARK_ATTACK, PET_FEROCITY_SPIDERS_BITE, PET_FEROCITY_SPIKED_COLLAR, PET_FEROCITY_WILD_HUNT, PET_TENACITY_BLOOD_OF_THE_RHINO, PET_TENACITY_BOARS_SPEED, PET_TENACITY_CHARGE, PET_TENACITY_COBRA_REFLEXES, PET_TENACITY_CULLING_THE_HERD, PET_TENACITY_GRACE_OF_THE_MANTIS, PET_TENACITY_GREAT_RESISTANCE, PET_TENACITY_GREAT_STAMINA, PET_TENACITY_GUARD_DOG, PET_TENACITY_INTERVENE, PET_TENACITY_LAST_STAND, PET_TENACITY_LIONHEARTED, PET_TENACITY_NATURAL_ARMOR, PET_TENACITY_PET_BARDING, PET_TENACITY_ROAR_OF_SACRIFICE, PET_TENACITY_SILVERBACK, PET_TENACITY_SPIKED_COLLAR, PET_TENACITY_TAUNT, PET_TENACITY_THUNDERSTOMP, PET_TENACITY_WILD_HUNT, PRIEST_ABSOLUTION, PRIEST_ASPIRATION, PRIEST_BLESSED_RECOVERY, PRIEST_BLESSED_RESILIENCE, PRIEST_BODY_AND_SOUL, PRIEST_BORROWED_TIME, PRIEST_CIRCLE_OF_HEALING, PRIEST_DARKNESS, PRIEST_DESPERATE_PRAYER, PRIEST_DISPERSION, PRIEST_DIVINE_AEGIS, PRIEST_DIVINE_FURY, PRIEST_DIVINE_PROVIDENCE, PRIEST_EMPOWERED_HEALING, PRIEST_EMPOWERED_RENEW, PRIEST_ENLIGHTENMENT, PRIEST_FOCUSED_MIND, PRIEST_FOCUSED_POWER, PRIEST_FOCUSED_WILL, PRIEST_GRACE, PRIEST_GUARDIAN_SPIRIT, PRIEST_HEALING_FOCUS, PRIEST_HEALING_PRAYERS, PRIEST_HOLY_CONCENTRATION, PRIEST_HOLY_REACH, PRIEST_HOLY_SPECIALIZATION, PRIEST_IMPROVED_DEVOURING_PLAGUE, PRIEST_IMPROVED_FLASH_HEAL, PRIEST_IMPROVED_HEALIN, PRIEST_IMPROVED_INNER_FIRE, PRIEST_IMPROVED_MANA_BURN, PRIEST_IMPROVED_MIND_BLAST, PRIEST_IMPROVED_POWER_WORD_FORTITUDE, PRIEST_IMPROVED_POWER_WORD_SHIELD, PRIEST_IMPROVED_PSYCHIC_SCREAM, PRIEST_IMPROVED_RENEW, PRIEST_IMPROVED_SHADOW_WORD_PAIN, PRIEST_IMPROVED_SHADOWFORM, PRIEST_IMPROVED_SPIRIT_TAP, PRIEST_IMPROVED_VAMPIRIC_EMBRACE, PRIEST_INNER_FOCUS, PRIEST_INSPIRATION, PRIEST_LIGHTWELL, PRIEST_MARTYRDOM, PRIEST_MEDITATION, PRIEST_MENTAL_AGILITY, PRIEST_MENTAL_STRENGTH, PRIEST_MIND_FLAY, PRIEST_MIND_MELT, PRIEST_MISERY, PRIEST_PAIN_AND_SUFFERING, PRIEST_PAIN_SUPPRESSION, PRIEST_PENANCE, PRIEST_POWER_INFUSION, PRIEST_PSYCHIC_HORROR, PRIEST_RAPTURE, PRIEST_REFLECTIVE_SHIELD, PRIEST_RENEWED_HOPE, PRIEST_SEARING_LIGHT, PRIEST_SERENDIPITY, PRIEST_SHADOW_AFFINITY, PRIEST_SHADOW_FOCUS, PRIEST_SHADOW_POWER, PRIEST_SHADOW_REACH, PRIEST_SHADOW_WEAVING, PRIEST_SHADOWFORM, PRIEST_SILENCE, PRIEST_SILENT_RESOLVE, PRIEST_SOUL_WARDING, PRIEST_SPELL_WARDING, PRIEST_SPIRIT_OF_REDEMPTION, PRIEST_SPIRIT_TAP, PRIEST_SPIRITUAL_GUIDANCE, PRIEST_SPIRITUAL_HEALING, PRIEST_SURGE_OF_LIGHT, PRIEST_TEST_OF_FAITH, PRIEST_TWIN_DISCIPLINES, PRIEST_TWISTED_FAITH, PRIEST_UNBREAKABLE_WILL, PRIEST_VAMPIRIC_EMBRACE, PRIEST_VAMPIRIC_TOUCH, PRIEST_VEILED_SHADOWS, ROGUE_ADRENALINE_RUSH, ROGUE_AGGRESSION, ROGUE_BLADE_FLURRY, ROGUE_BLADE_TWISTING, ROGUE_BLOOD_SPATTER, ROGUE_CAMOUFLAGE, ROGUE_CHEAT_DEATH, ROGUE_CLOSE_QUARTERS_COMBAT, ROGUE_COLD_BLOOD, ROGUE_COMBAT_POTENCY, ROGUE_CUT_TO_THE_CHASE, ROGUE_DEADENED_NERVES, ROGUE_DEADLINESS, ROGUE_DEADLY_BREW, ROGUE_DEFLECTION, ROGUE_DIRTY_DEEDS, ROGUE_DIRTY_TRICKS, ROGUE_DUAL_WIELD_SPECIALIZATION, ROGUE_ELUSIVENESS, ROGUE_ENDURANCE, ROGUE_ENVELOPING_SHADOWS, ROGUE_FILTHY_TRICKS, ROGUE_FIND_WEAKNESS, ROGUE_FLEET_FOOTED, ROGUE_FOCUSED_ATTACKS, ROGUE_GHOSTLY_STRIKE, ROGUE_HACK_AND_SLASH, ROGUE_HEIGHTENED_SENSES, ROGUE_HEMORRHAGE, ROGUE_HONOR_AMONG_THIEVES, ROGUE_HUNGER_FOR_BLOOD, ROGUE_IMPROVED_AMBUSH, ROGUE_IMPROVED_EVISCERATE, ROGUE_IMPROVED_EXPOSE_ARMOR, ROGUE_IMPROVED_GOUGE, ROGUE_IMPROVED_KICK, ROGUE_IMPROVED_KIDNEY_SHOT, ROGUE_IMPROVED_POISONS, ROGUE_IMPROVED_SINISTER_STRIKE, ROGUE_IMPROVED_SLICE_AND_DICE, ROGUE_IMPROVED_SPRINT, ROGUE_INITIATIVE, ROGUE_KILLING_SPREE, ROGUE_LETHALITY, ROGUE_LIGHTNING_REFLEXES, ROGUE_MACE_SPECIALIZATION, ROGUE_MALICE, ROGUE_MASTER_OF_DECEPTION, ROGUE_MASTER_OF_SUBTLETY, ROGUE_MASTER_POISONER, ROGUE_MURDER, ROGUE_MUTILATE, ROGUE_NERVES_OF_STEEL, ROGUE_OPPORTUNITY, ROGUE_OVERKILL, ROGUE_PRECISION, ROGUE_PREMEDITATION, ROGUE_PREPARATION, ROGUE_PREY_ON_THE_WEAK, ROGUE_PUNCTURING_WOUNDS, ROGUE_QUICK_RECOVERY, ROGUE_RELENTLESS_STRIKES, ROGUE_REMORSELESS_ATTACKS, ROGUE_RIPOSTE, ROGUE_RUTHLESSNESS, ROGUE_SAVAGE_COMBAT, ROGUE_SEAL_FATE, ROGUE_SERRATED_BLADES, ROGUE_SETUP, ROGUE_SHADOW_DANCE, ROGUE_SHADOWSTEP, ROGUE_SINISTER_CALLING, ROGUE_SLAUGHTER_FROM_THE_SHADOWS, ROGUE_SLEIGHT_OF_HAND, ROGUE_SURPRISE_ATTACKS, ROGUE_THROWING_SPECIALIZATION, ROGUE_TURN_THE_TABLES, ROGUE_UNFAIR_ADVANTAGE, ROGUE_VIGOR, ROGUE_VILE_POISONS, ROGUE_VITALITY, ROGUE_WAYLAY, ROGUE_WEAPON_EXPERTISE, SHAMAN_ANCESTRAL_AWAKENING, SHAMAN_ANCESTRAL_HEALING, SHAMAN_ANCESTRAL_KNOWLEDGE, SHAMAN_ANTICIPATION, SHAMAN_ASTRAL_SHIFT, SHAMAN_BLESSING_OF_THE_ETERNALS, SHAMAN_BOOMING_ECHOES, SHAMAN_CALL_OF_FLAME, SHAMAN_CALL_OF_THUNDER, SHAMAN_CLEANSE_SPIRIT, SHAMAN_CONCUSSION, SHAMAN_CONVECTION, SHAMAN_DUAL_WIELD, SHAMAN_DUAL_WIELD_SPECIALIZATION, SHAMAN_EARTH_SHIELD, SHAMAN_EARTHEN_POWER, SHAMAN_EARTHS_GRASP, SHAMAN_ELEMENTAL_DEVASTATION, SHAMAN_ELEMENTAL_FOCUS, SHAMAN_ELEMENTAL_FURY, SHAMAN_ELEMENTAL_MASTERY, SHAMAN_ELEMENTAL_OATH, SHAMAN_ELEMENTAL_PRECISION, SHAMAN_ELEMENTAL_REACH, SHAMAN_ELEMENTAL_WARDING, SHAMAN_ELEMENTAL_WEAPONS, SHAMAN_ENHANCING_TOTEMS, SHAMAN_EYE_OF_THE_STORM, SHAMAN_FERAL_SPIRIT, SHAMAN_FLURRY, SHAMAN_FOCUSED_MIND, SHAMAN_FROZEN_POWER, SHAMAN_GUARDIAN_TOTEMS, SHAMAN_HEALING_FOCUS, SHAMAN_HEALING_GRACE, SHAMAN_HEALING_WAY, SHAMAN_IMPROVED_CHAIN_HEAL, SHAMAN_IMPROVED_EARTH_SHIELD, SHAMAN_IMPROVED_FIRE_NOVA, SHAMAN_IMPROVED_GHOST_WOLF, SHAMAN_IMPROVED_HEALING_WAVE, SHAMAN_IMPROVED_REINCARNATION, SHAMAN_IMPROVED_SHIELDS, SHAMAN_IMPROVED_STORMSTRIKE, SHAMAN_IMPROVED_WATER_SHIELD, SHAMAN_IMPROVED_WINDFURY_TOTEM, SHAMAN_LAVA_FLOWS, SHAMAN_LAVA_LASH, SHAMAN_LIGHTNING_MASTERY, SHAMAN_LIGHTNING_OVERLOAD, SHAMAN_MAELSTROM_WEAPON, SHAMAN_MANA_TIDE_TOTEM, SHAMAN_MENTAL_DEXTERITY, SHAMAN_MENTAL_QUICKNESS, SHAMAN_NATURES_BLESSING, SHAMAN_NATURES_GUARDIAN, SHAMAN_NATURES_SWIFTNESS, SHAMAN_PURIFICATION, SHAMAN_RESTORATIVE_TOTEMS, SHAMAN_REVERBERATION, SHAMAN_RIPTIDE, SHAMAN_SHAMANISM, SHAMAN_SHAMANISTIC_FOCUS, SHAMAN_SHAMANISTIC_RAGE, SHAMAN_SPIRIT_WEAPONS, SHAMAN_STATIC_SHOCK, SHAMAN_STORM_EARTH_AND_FIRE, SHAMAN_STORMSTRIKE, SHAMAN_THUNDERING_STRIKES, SHAMAN_THUNDERSTORM, SHAMAN_TIDAL_FOCUS, SHAMAN_TIDAL_FORCE, SHAMAN_TIDAL_MASTERY, SHAMAN_TIDAL_WAVES, SHAMAN_TOTEM_OF_WRATH, SHAMAN_TOTEMIC_FOCUS, SHAMAN_TOUGHNESS, SHAMAN_UNLEASHED_RAGE, SHAMAN_UNRELENTING_STORM, SHAMAN_WEAPON_MASTERY, WARLOCK_AFTERMATH, WARLOCK_AMPLIFY_CURSE, WARLOCK_BACKDRAFT, WARLOCK_BACKLASH, WARLOCK_BANE, WARLOCK_CATACLYSM, WARLOCK_CHAOS_BOLT, WARLOCK_CONFLAGRATE, WARLOCK_CONTAGION, WARLOCK_CURSE_OF_EXHAUSTION, WARLOCK_DARK_PACT, WARLOCK_DEATHS_EMBRACE, WARLOCK_DECIMATION, WARLOCK_DEMONIC_AEGIS, WARLOCK_DEMONIC_BRUTALITY, WARLOCK_DEMONIC_EMBRACE, WARLOCK_DEMONIC_EMPOWERMENT, WARLOCK_DEMONIC_KNOWLEDGE, WARLOCK_DEMONIC_PACT, WARLOCK_DEMONIC_POWER, WARLOCK_DEMONIC_RESILIENCE, WARLOCK_DEMONIC_TACTICS, WARLOCK_DESTRUCTIVE_REACH, WARLOCK_DEVASTATION, WARLOCK_EMBERSTORM, WARLOCK_EMPOWERED_CORRUPTION, WARLOCK_EMPOWERED_IMP, WARLOCK_ERADICATION, WARLOCK_EVERLASTING_AFFLICTION, WARLOCK_FEL_CONCENTRATION, WARLOCK_FEL_DOMINATION, WARLOCK_FEL_SYNERGY, WARLOCK_FEL_VITALITY, WARLOCK_FIRE_AND_BRIMSTONE, WARLOCK_GRIM_REACH, WARLOCK_HAUNT, WARLOCK_IMPROVED_CORRUPTION, WARLOCK_IMPROVED_CURSE_OF_AGONY, WARLOCK_IMPROVED_CURSE_OF_WEAKNESS, WARLOCK_IMPROVED_DEMONIC_TACTICS, WARLOCK_IMPROVED_DRAIN_SOUL, WARLOCK_IMPROVED_FEAR, WARLOCK_IMPROVED_FELHUNTER, WARLOCK_IMPROVED_HEALTH_FUNNEL, WARLOCK_IMPROVED_HEALTHSTONE, WARLOCK_IMPROVED_HOWL_OF_TERROR, WARLOCK_IMPROVED_IMMOLATE, WARLOCK_IMPROVED_IMP, WARLOCK_IMPROVED_LIFE_TAP, WARLOCK_IMPROVED_SEARING_PAIN, WARLOCK_IMPROVED_SHADOW_BOLT, WARLOCK_IMPROVED_SOUL_LEECH, WARLOCK_IMPROVED_SUCCUBUS, WARLOCK_INTENSITY, WARLOCK_MALEDICTION, WARLOCK_MANA_FEED, WARLOCK_MASTER_CONJURER, WARLOCK_MASTER_DEMONOLOGIST, WARLOCK_MASTER_SUMMONER, WARLOCK_METAMORPHOSIS, WARLOCK_MOLTEN_CORE, WARLOCK_MOLTEN_SKIN, WARLOCK_NEMESIS, WARLOCK_NETHER_PROTECTION, WARLOCK_NIGHTFALL, WARLOCK_PANDEMIC, WARLOCK_PYROCLASM, WARLOCK_RUIN, WARLOCK_SHADOW_AND_FLAME, WARLOCK_SHADOW_EMBRACE, WARLOCK_SHADOW_MASTERY, WARLOCK_SHADOWBURN, WARLOCK_SHADOWFURY, WARLOCK_SIPHON_LIFE, WARLOCK_SOUL_LEECH, WARLOCK_SOUL_LINK, WARLOCK_SOUL_SIPHON, WARLOCK_SUMMON_FELGUARD, WARLOCK_SUPPRESSION, WARLOCK_UNHOLY_POWER, WARLOCK_UNSTABLE_AFFLICTION, WARRIOR_ANGER_MANAGEMENT, WARRIOR_ANTICIPATION, WARRIOR_ARMORED_TO_THE_TEETH, WARRIOR_BLADESTORM, WARRIOR_BLOOD_CRAZE, WARRIOR_BLOOD_FRENZY, WARRIOR_BLOODSURGE, WARRIOR_BLOODTHIRST, WARRIOR_BOOMING_VOICE, WARRIOR_COMMANDING_PRESENCE, WARRIOR_CONCUSSION_BLOW, WARRIOR_CRITICAL_BLOCK, WARRIOR_CRUELTY, WARRIOR_DAMAGE_SHIELD, WARRIOR_DEATH_WISH, WARRIOR_DEEP_WOUNDS, WARRIOR_DEFLECTION, WARRIOR_DEVASTATE, WARRIOR_DUAL_WIELD_SPECIALIZATION, WARRIOR_ENDLESS_RAGE, WARRIOR_ENRAGE, WARRIOR_FLURRY, WARRIOR_FOCUSED_RAGE, WARRIOR_FURIOUS_ATTACKS, WARRIOR_GAG_ORDER, WARRIOR_HEROIC_FURY, WARRIOR_IMPALE, WARRIOR_IMPROVED_BERSERKER_RAGE, WARRIOR_IMPROVED_BERSERKER_STANCE, WARRIOR_IMPROVED_BLOODRAGE, WARRIOR_IMPROVED_CHARGE, WARRIOR_IMPROVED_CLEAVE, WARRIOR_IMPROVED_DEFENSIVE_STANCE, WARRIOR_IMPROVED_DEMORALIZING_SHOUT, WARRIOR_IMPROVED_DISARM, WARRIOR_IMPROVED_DISCIPLINES, WARRIOR_IMPROVED_EXECUTE, WARRIOR_IMPROVED_HAMSTRING, WARRIOR_IMPROVED_HEROIC_STRIKE, WARRIOR_IMPROVED_INTERCEPT, WARRIOR_IMPROVED_MORTAL_STRIKE, WARRIOR_IMPROVED_OVERPOWER, WARRIOR_IMPROVED_REND, WARRIOR_IMPROVED_REVENGE, WARRIOR_IMPROVED_SLAM, WARRIOR_IMPROVED_SPELL_REFLECTION, WARRIOR_IMPROVED_THUNDER_CLAP, WARRIOR_IMPROVED_WHIRLWIND, WARRIOR_INCITE, WARRIOR_INTENSIFY_RAGE, WARRIOR_IRON_WILL, WARRIOR_JUGGERNAUT, WARRIOR_LAST_STAND, WARRIOR_MACE_SPECIALIZATION, WARRIOR_MORTAL_STRIKE, WARRIOR_ONEHANDED_WEAPON_SPECIALIZATION, WARRIOR_PIERCING_HOWL, WARRIOR_POLEAXE_SPECIALIZATION, WARRIOR_PRECISION, WARRIOR_PUNCTURE, WARRIOR_RAMPAGE, WARRIOR_SAFEGUARD, WARRIOR_SECOND_WIND, WARRIOR_SHIELD_MASTERY, WARRIOR_SHIELD_SPECIALIZATION, WARRIOR_SHOCKWAVE, WARRIOR_STRENGTH_OF_ARMS, WARRIOR_SUDDEN_DEATH, WARRIOR_SWEEPING_STRIKES, WARRIOR_SWORD_AND_BOARD, WARRIOR_SWORD_SPECIALIZATION, WARRIOR_TACTICAL_MASTERY, WARRIOR_TASTE_FOR_BLOOD, WARRIOR_TITANS_GRIP, WARRIOR_TOUGHNESS, WARRIOR_TRAUMA, WARRIOR_TWOHANDED_WEAPON_SPECIALIZATION, WARRIOR_UNBRIDLED_WRATH, WARRIOR_UNENDING_FURY, WARRIOR_UNRELENTING_ASSAULT, WARRIOR_VIGILANCE, WARRIOR_VITALITY, WARRIOR_WARBRINGER, WARRIOR_WEAPON_MASTERY, and WARRIOR_WRECKING_CREW.
Referenced by TalentSpecDBContainsError().
Withdraw()
bool PlayerbotAI::Withdraw (const uint32 itemid)
Definition at line 8212 of file PlayerbotAI.cpp.
References Player::CanStoreItem(), EQUIP_ERR_OK, FindItemInBank(), Item::GetBagSlot(), Item::GetSlot(), m_bot, MakeItemLink(), NULL_BAG, NULL_SLOT, Player::RemoveItem(), Player::SendEquipError(), Player::StoreItem(), and TellMaster().
Referenced by findNearbyCreature().
Field Documentation
ASPECT_OF_THE_MONKEY
uint32 PlayerbotAI::ASPECT_OF_THE_MONKEY private
Definition at line 2149 of file PlayerbotAI.h.
Referenced by _HandleCommandPet().
DistOverRide
uint8 PlayerbotAI::DistOverRide
Definition at line 1903 of file PlayerbotAI.h.
Referenced by _HandleCommandFollow(), CombatOrderRestore(), MovementReset(), PlayerbotAI(), and UpdateAI().
FISHING
uint32 PlayerbotAI::FISHING private
Definition at line 2145 of file PlayerbotAI.h.
gDist
float PlayerbotAI::gDist[2]
Definition at line 1904 of file PlayerbotAI.h.
Referenced by MovementReset().
gPrimtarget
Unit* PlayerbotAI::gPrimtarget
Definition at line 1897 of file PlayerbotAI.h.
Referenced by CombatOrderRestore().
gQuestFetch
uint32 PlayerbotAI::gQuestFetch
Definition at line 1899 of file PlayerbotAI.h.
Referenced by _HandleCommandQuest(), and ListQuests().
gSectarget
Unit* PlayerbotAI::gSectarget
Definition at line 1898 of file PlayerbotAI.h.
Referenced by CombatOrderRestore().
gTempDist
float PlayerbotAI::gTempDist
Definition at line 1905 of file PlayerbotAI.h.
Referenced by _HandleCommandFollow(), CombatOrderRestore(), MovementReset(), and PlayerbotAI().
gTempDist2
float PlayerbotAI::gTempDist2
Definition at line 1906 of file PlayerbotAI.h.
Referenced by _HandleCommandFollow(), CombatOrderRestore(), MovementReset(), and PlayerbotAI().
HERB_GATHERING
uint32 PlayerbotAI::HERB_GATHERING private
Definition at line 2146 of file PlayerbotAI.h.
Referenced by DoLoot(), and ReloadAI().
IsUpOrDown
uint8 PlayerbotAI::IsUpOrDown
Definition at line 1908 of file PlayerbotAI.h.
Referenced by _HandleCommandFollow(), CombatOrderRestore(), MovementReset(), and PlayerbotAI().
m_activeTalentSpec
TalentSpec PlayerbotAI::m_activeTalentSpec private
Definition at line 2091 of file PlayerbotAI.h.
Referenced by ApplyActiveTalentSpec(), ClearActiveTalentSpec(), GetActiveTalentSpec(), and SetActiveTalentSpec().
m_attackerInfo
AttackerInfoList PlayerbotAI::m_attackerInfo private
Definition at line 2132 of file PlayerbotAI.h.
Referenced by _HandleCommandGM(), DoTeleport(), FindAttacker(), GetAttackerCount(), SendOrders(), UpdateAI(), UpdateAttackerInfo(), and UpdateAttackersForTarget().
m_AutoEquipToggle
bool PlayerbotAI::m_AutoEquipToggle
Definition at line 1901 of file PlayerbotAI.h.
Referenced by _HandleCommandEquip(), AutoUpgradeEquipment(), BotDataRestore(), and PlayerbotAI().
m_bDebugCommandChat
bool PlayerbotAI::m_bDebugCommandChat private
Definition at line 2155 of file PlayerbotAI.h.
Referenced by _HandleCommandGM(), and HandleCommand().
m_being_rolled_on
BotObjectList PlayerbotAI::m_being_rolled_on private
Definition at line 2112 of file PlayerbotAI.h.
Referenced by BeingRolledOn(), DoLoot(), and HandleBotOutgoingPacket().
m_bot
Player* const PlayerbotAI::m_bot private
Definition at line 2080 of file PlayerbotAI.h.
Referenced by _doSellItem(), _findItemSlot(), _HandleCommandAttack(), _HandleCommandCast(), _HandleCommandCollect(), _HandleCommandCraft(), _HandleCommandEnchant(), _HandleCommandEquip(), _HandleCommandFind(), _HandleCommandFollow(), _HandleCommandGet(), _HandleCommandGM(), _HandleCommandMail(), _HandleCommandNeutralize(), _HandleCommandOrders(), _HandleCommandPet(), _HandleCommandProcess(), _HandleCommandPull(), _HandleCommandQuest(), _HandleCommandSkill(), _HandleCommandSkillLearnHelper(), _HandleCommandSpells(), _HandleCommandStats(), _HandleCommandSurvey(), _HandleCommandTalent(), _HandleCommandUse(), AcceptQuest(), AddAuction(), AddQuest(), Announce(), ApplyActiveTalentSpec(), Attack(), AutoEquipComparison(), AutoUpgradeEquipment(), BankBalance(), BotDataRestore(), Buff(), Buy(), CanPull(), CanReachWithSpellAttack(), CanReceiveSpecificSpell(), CanStore(), CastNeutralize(), CastPetSpell(), CastPull(), CastSpell(), CheckBotCast(), ClearGroupCombatOrder(), CombatOrderRestore(), Deposit(), DoCombatMovement(), DoFlight(), DoLoot(), DoNextCombatManeuver(), DoTeleport(), DropGarbage(), DropItem(), EquipItem(), EstRepair(), extractGOinfo(), FaceTarget(), FindAmmo(), FindAttacker(), FindBandage(), FindBombForLockValue(), FindConsumable(), FindDrink(), FindFood(), FindItem(), FindItemInBank(), findItemsInEquip(), findItemsInInv(), FindKeyForLockValue(), FindManaRegenItem(), FindMount(), findNearbyCorpse(), findNearbyCreature(), findNearbyGO(), FindPoison(), FollowAutoReset(), GetCombatTarget(), GetCurrentSpell(), GetDuelTarget(), GetEnergyAmount(), GetFreeBagSpace(), GetGroupHealer(), GetGroupTank(), GetHealthPercent(), GetManaPercent(), getPetSpellId(), GetPlayer(), GetPlayerBot(), GetRageAmount(), GetRunicPower(), GetSpellCharges(), getSpellId(), GetTaxi(), GroupHoTOnTank(), GroupTankHoldsAggro(), HandleBotOutgoingPacket(), HandleCommand(), HasAura(), HasSpellReagents(), HasTool(), In_Range(), In_Reach(), initPetSpell(), initSpell(), InspectUpdate(), InterruptCurrentCastingSpell(), IsGroupReady(), IsInCombat(), IsItemUseful(), IsRegenerating(), ItemCountInInv(), ItemStatComparison(), ListAuctions(), ListQuests(), MakeWeaponSkillLink(), MovementClear(), MovementReset(), PickPocket(), PlayerbotAI(), ReloadAI(), RemoveAuction(), Repair(), SelfBuff(), Sell(), SellGarbage(), SendNotEquipList(), SendQuestNeedList(), SendWhisper(), SetCombatOrder(), SetGroupCombatOrder(), SetGroupIgnoreUpdateTime(), SetQuestNeedCreatures(), SetQuestNeedItems(), Talent(), TradeCopper(), TradeItem(), TryEmergency(), TurnInQuests(), UpdateAI(), UpdateAttackerInfo(), UseItem(), and Withdraw().
m_botState
BotState PlayerbotAI::m_botState private
Definition at line 2096 of file PlayerbotAI.h.
Referenced by Attack(), GetDuelTarget(), GetState(), HandleBotOutgoingPacket(), PlayerbotAI(), SendOrders(), SetMovementOrder(), SetState(), and UpdateAI().
m_classAI
PlayerbotClassAI* PlayerbotAI::m_classAI private
Definition at line 2081 of file PlayerbotAI.h.
Referenced by GetClassAI(), ReloadAI(), and ~PlayerbotAI().
m_collectDist
uint32 PlayerbotAI::m_collectDist private
Definition at line 2115 of file PlayerbotAI.h.
Referenced by _HandleCommandCollect(), findNearbyGO(), and PlayerbotAI().
m_collectionFlags
uint8 PlayerbotAI::m_collectionFlags private
Definition at line 2114 of file PlayerbotAI.h.
Referenced by _HandleCommandCollect(), HasCollectFlag(), PlayerbotAI(), and SetCollectFlag().
m_collectObjects
BotEntryList PlayerbotAI::m_collectObjects private
Definition at line 2109 of file PlayerbotAI.h.
Referenced by _HandleCommandCollect(), DoLoot(), findNearbyGO(), HandleBotOutgoingPacket(), and SetQuestNeedItems().
m_combatOrder
CombatOrderType PlayerbotAI::m_combatOrder private
Definition at line 2088 of file PlayerbotAI.h.
Referenced by ClearCombatOrder(), DoNextCombatManeuver(), GetCombatOrder(), GetCombatTarget(), HasDispelOrder(), IsDPS(), IsHealer(), IsMainHealer(), IsMainTank(), IsTank(), MovementReset(), SendOrders(), SetCombatOrder(), and UpdateAI().
m_combatStyle
CombatStyle PlayerbotAI::m_combatStyle private
Definition at line 2087 of file PlayerbotAI.h.
Referenced by DoCombatMovement(), GetCombatStyle(), GetDuelTarget(), ReloadAI(), and SetCombatStyle().
m_CraftSpellId
uint32 PlayerbotAI::m_CraftSpellId private
Definition at line 2121 of file PlayerbotAI.h.
Referenced by _HandleCommandCraft(), and UpdateAI().
m_CurrentlyCastingSpellId
uint32 PlayerbotAI::m_CurrentlyCastingSpellId private
Definition at line 2120 of file PlayerbotAI.h.
Referenced by CastSpell(), GetCurrentSpell(), GetCurrentSpellId(), HandleBotOutgoingPacket(), and InterruptCurrentCastingSpell().
m_debugWhisper
bool PlayerbotAI::m_debugWhisper = false private
Definition at line 2157 of file PlayerbotAI.h.
Referenced by DoLoot(), HandleBotOutgoingPacket(), and HandleCommand().
m_DelayAttack
uint8 PlayerbotAI::m_DelayAttack
Definition at line 1895 of file PlayerbotAI.h.
Referenced by _HandleCommandOrders(), BotDataRestore(), CombatOrderRestore(), SendOrders(), SetCombatOrder(), and UpdateAI().
m_DelayAttackInit
time_t PlayerbotAI::m_DelayAttackInit
Definition at line 1896 of file PlayerbotAI.h.
Referenced by Attack(), PlayerbotAI(), SetCombatOrder(), and UpdateAI().
m_destX
float PlayerbotAI::m_destX private
Definition at line 2153 of file PlayerbotAI.h.
m_destY
float PlayerbotAI::m_destY private
Definition at line 2153 of file PlayerbotAI.h.
m_destZ
float PlayerbotAI::m_destZ private
Definition at line 2153 of file PlayerbotAI.h.
m_dropWhite
bool PlayerbotAI::m_dropWhite private
Definition at line 2118 of file PlayerbotAI.h.
Referenced by _HandleCommandDrop(), DropGarbage(), and PlayerbotAI().
m_findNPC
BotNPCList PlayerbotAI::m_findNPC private
Definition at line 2103 of file PlayerbotAI.h.
Referenced by _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandSell(), _HandleCommandTalent(), findNearbyCreature(), HandleCommand(), and UpdateAI().
m_FollowAutoGo
uint8 PlayerbotAI::m_FollowAutoGo
Definition at line 1907 of file PlayerbotAI.h.
m_followTarget
Unit* PlayerbotAI::m_followTarget private
Definition at line 2143 of file PlayerbotAI.h.
Referenced by _HandleCommandAttack(), FollowAutoReset(), MovementReset(), SendOrders(), SetMovementOrder(), and UpdateAI().
m_ignoreAIUpdatesUntilTime
time_t PlayerbotAI::m_ignoreAIUpdatesUntilTime private
Definition at line 2085 of file PlayerbotAI.h.
Referenced by SendOrders(), SetIgnoreUpdateTime(), and UpdateAI().
m_ignoreNeutralizeEffect
bool PlayerbotAI::m_ignoreNeutralizeEffect private
Definition at line 2135 of file PlayerbotAI.h.
Referenced by GetCombatTarget().
m_ignorePlayersChat
BotObjectSet PlayerbotAI::m_ignorePlayersChat private
Definition at line 2130 of file PlayerbotAI.h.
Referenced by HandleCommand().
m_inventory_full
bool PlayerbotAI::m_inventory_full private
Definition at line 2116 of file PlayerbotAI.h.
Referenced by DoLoot(), HandleBotOutgoingPacket(), and HandleCommand().
m_itemTarget
uint32 PlayerbotAI::m_itemTarget private
Definition at line 2117 of file PlayerbotAI.h.
Referenced by _HandleCommandProcess(), and HandleBotOutgoingPacket().
m_lootCurrent
ObjectGuid PlayerbotAI::m_lootCurrent private
Definition at line 2107 of file PlayerbotAI.h.
Referenced by _HandleCommandFind(), _HandleCommandReset(), CastSpell(), CheckBotCast(), DoLoot(), HandleBotOutgoingPacket(), and UpdateAI().
m_lootPrev
ObjectGuid PlayerbotAI::m_lootPrev private
Definition at line 2108 of file PlayerbotAI.h.
Referenced by HandleBotOutgoingPacket().
m_lootTargets
BotObjectList PlayerbotAI::m_lootTargets private
Definition at line 2105 of file PlayerbotAI.h.
Referenced by _HandleCommandFind(), _HandleCommandGet(), _HandleCommandGM(), _HandleCommandMail(), _HandleCommandReset(), _HandleCommandUse(), Attack(), DoLoot(), extractGOinfo(), findNearbyCorpse(), findNearbyGO(), and UpdateAI().
m_mgr
PlayerbotMgr& PlayerbotAI::m_mgr private
Definition at line 2079 of file PlayerbotAI.h.
Referenced by _doSellItem(), _HandleCommandCollect(), DoLoot(), DropGarbage(), findNearbyCorpse(), GetCombatTarget(), GetMaster(), MovementReset(), PickPocket(), PlayerbotAI(), and SendOrders().
m_movementOrder
MovementOrderType PlayerbotAI::m_movementOrder private
Definition at line 2089 of file PlayerbotAI.h.
Referenced by DoCombatMovement(), GetMovementOrder(), MovementReset(), SendOrders(), and SetMovementOrder().
m_needCreatureOrGOList
BotNeedItem PlayerbotAI::m_needCreatureOrGOList private
Definition at line 2100 of file PlayerbotAI.h.
Referenced by IsInQuestCreatureList(), SendQuestNeedList(), and SetQuestNeedCreatures().
m_needItemList
BotNeedItem PlayerbotAI::m_needItemList private
Definition at line 2099 of file PlayerbotAI.h.
Referenced by HandleBotOutgoingPacket(), IsInQuestItemList(), SendQuestNeedList(), and SetQuestNeedItems().
m_noToolList
BotEntryList PlayerbotAI::m_noToolList private
Definition at line 2111 of file PlayerbotAI.h.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), and GetSpellCharges().
m_ScenarioType
ScenarioType PlayerbotAI::m_ScenarioType private
Definition at line 2093 of file PlayerbotAI.h.
Referenced by DoNextCombatManeuver(), GetScenarioType(), HandleBotOutgoingPacket(), and UpdateAI().
m_spellIdCommand
uint32 PlayerbotAI::m_spellIdCommand private
Definition at line 2126 of file PlayerbotAI.h.
Referenced by _HandleCommandCast(), CastNeutralize(), and UpdateAI().
m_spellRangeMap
SpellRanges PlayerbotAI::m_spellRangeMap private
Definition at line 2151 of file PlayerbotAI.h.
Referenced by CanReachWithSpellAttack(), In_Reach(), and initSpell().
m_spellsToLearn
BotEntryList PlayerbotAI::m_spellsToLearn private
Definition at line 2106 of file PlayerbotAI.h.
Referenced by _HandleCommandCraft(), _HandleCommandEnchant(), _HandleCommandSkill(), and extractSpellIdList().
m_targetAssist
Unit* PlayerbotAI::m_targetAssist private
Definition at line 2140 of file PlayerbotAI.h.
Referenced by GetCombatTarget(), PlayerbotAI(), SendOrders(), and SetCombatOrder().
m_targetChanged
bool PlayerbotAI::m_targetChanged private
Definition at line 2136 of file PlayerbotAI.h.
Referenced by DoNextCombatManeuver(), GetCombatTarget(), GetDuelTarget(), and PlayerbotAI().
m_targetCombat
Unit* PlayerbotAI::m_targetCombat private
Definition at line 2139 of file PlayerbotAI.h.
Referenced by _HandleCommandReset(), Attack(), DoCombatMovement(), DoNextCombatManeuver(), DoTeleport(), GetCombatTarget(), GetCurrentTarget(), GetDuelTarget(), HandleBotOutgoingPacket(), PlayerbotAI(), and UpdateAI().
m_targetGuidCommand
ObjectGuid PlayerbotAI::m_targetGuidCommand private
Definition at line 2127 of file PlayerbotAI.h.
Referenced by _HandleCommandCast(), _HandleCommandNeutralize(), _HandleCommandPet(), CastNeutralize(), InterruptCurrentCastingSpell(), and UpdateAI().
m_targetProtect
Unit* PlayerbotAI::m_targetProtect private
Definition at line 2141 of file PlayerbotAI.h.
Referenced by GetCombatTarget(), PlayerbotAI(), SendOrders(), and SetCombatOrder().
m_targetType
CombatTargetType PlayerbotAI::m_targetType private
Definition at line 2137 of file PlayerbotAI.h.
Referenced by DoNextCombatManeuver(), GetCombatTarget(), GetDuelTarget(), and PlayerbotAI().
m_tasks
BotTaskList PlayerbotAI::m_tasks private
Definition at line 2104 of file PlayerbotAI.h.
Referenced by _HandleCommandAuction(), _HandleCommandBank(), _HandleCommandBuy(), _HandleCommandQuest(), _HandleCommandRepair(), _HandleCommandSell(), _HandleCommandTalent(), findNearbyCreature(), and HandleCommand().
m_taxiMaster
ObjectGuid PlayerbotAI::m_taxiMaster private
Definition at line 2128 of file PlayerbotAI.h.
Referenced by DoFlight(), and GetTaxi().
m_taxiNodes
BotTaxiNode PlayerbotAI::m_taxiNodes private
Definition at line 2110 of file PlayerbotAI.h.
Referenced by DoFlight(), and GetTaxi().
MINING
uint32 PlayerbotAI::MINING private
Definition at line 2147 of file PlayerbotAI.h.
Referenced by DoLoot(), and ReloadAI().
SellWhite
uint32 PlayerbotAI::SellWhite
Definition at line 1902 of file PlayerbotAI.h.
Referenced by _doSellItem(), and _HandleCommandSell().
SKINNING
uint32 PlayerbotAI::SKINNING private
Definition at line 2148 of file PlayerbotAI.h.
Referenced by DoLoot(), and ReloadAI().
The documentation for this class was generated from the following files:
PlayerbotAI.h
PlayerbotAI.cpp