CMaNGOS_WoTLK: ObjectGridStoper Class Reference
ObjectGridStoper Class Reference
#include <ObjectGridLoader.h>
Public Member Functions
ObjectGridStoper (NGridType &grid)
void StopN ()
void Stop (GridType &grid)
void Visit (CreatureMapType &m)
template<class NONACTIVE >
void Visit (GridRefManager< NONACTIVE > &)
Private Attributes
NGridType & i_grid
Detailed Description
Definition at line 81 of file ObjectGridLoader.h.
Constructor & Destructor Documentation
ObjectGridStoper()
ObjectGridStoper::ObjectGridStoper (NGridType & grid) inline
Definition at line 84 of file ObjectGridLoader.h.
Member Function Documentation
Stop()
void ObjectGridStoper::Stop (GridType & grid)
Definition at line 298 of file ObjectGridLoader.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
StopN()
void ObjectGridStoper::StopN () inline
Definition at line 86 of file ObjectGridLoader.h.
References i_grid, MAX_NUMBER_OF_CELLS, and GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Stop().
Referenced by Map::UnloadGrid().
Visit() [1/2]
void ObjectGridStoper::Visit (CreatureMapType & m)
Definition at line 305 of file ObjectGridLoader.cpp.
Visit() [2/2]
template<class NONACTIVE > void ObjectGridStoper::Visit (GridRefManager< NONACTIVE > &) inline
Definition at line 101 of file ObjectGridLoader.h.
Field Documentation
i_grid
NGridType& ObjectGridStoper::i_grid private
Definition at line 103 of file ObjectGridLoader.h.
Referenced by StopN().
The documentation for this class was generated from the following files:
ObjectGridLoader.h
ObjectGridLoader.cpp