CMaNGOS_WoTLK: RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc > Class Template Reference
RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc > Class Template Reference
#include <RegularGrid.h>
Data Structures
struct Cell
class IteratorPair
Public Types
enum { CELL_NUMBER = 64 }
typedef std::unordered_multimap< const T *, Node * > MemberTable
Public Member Functions
RegularGrid2D ()
~RegularGrid2D ()
void insert (const T &value)
template<class M >
auto MapEqualRange (M &map, typename M::key_type const &key) -> IteratorPair< decltype(map.begin())>
void remove (const T &value)
void balance ()
bool contains (const T &value) const
int size () const
Node & getGrid (int x, int y)
template<typename RayCallback >
void intersectRay (const Ray &ray, RayCallback &intersectCallback, float max_dist, bool ignoreM2Model)
template<typename RayCallback >
void intersectRay (const Ray &ray, RayCallback &intersectCallback, float &max_dist, const Vector3 &end, bool ignoreM2Model)
template<typename IsectCallback >
void intersectPoint (const Vector3 &point, IsectCallback &intersectCallback)
template<typename RayCallback >
void intersectZAllignedRay (const Ray &ray, RayCallback &intersectCallback, float &max_dist)
Data Fields
MemberTable memberTable
Node * nodes [CELL_NUMBER][CELL_NUMBER]
Detailed Description
template<class T, class Node, class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>>
class RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >
Definition at line 46 of file RegularGrid.h.
Member Typedef Documentation
MemberTable
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> typedef std::unordered_multimap<const T*, Node*> RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::MemberTable
Definition at line 58 of file RegularGrid.h.
Member Enumeration Documentation
anonymous enum
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> anonymous enum
Enumerator
CELL_NUMBER
Definition at line 50 of file RegularGrid.h.
Constructor & Destructor Documentation
RegularGrid2D()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::RegularGrid2D () inline
Definition at line 63 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes.
~RegularGrid2D()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::~RegularGrid2D () inline
Definition at line 68 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::CELL_NUMBER, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes.
Member Function Documentation
balance()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::balance () inline
Definition at line 121 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::CELL_NUMBER, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes.
Referenced by DynTreeImpl::balance().
contains()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> bool RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::contains (const T & value) const inline
Definition at line 129 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::memberTable.
Referenced by DynamicMapTree::contains().
getGrid()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> Node& RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::getGrid (int x, int y) inline
Definition at line 146 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::CELL_NUMBER, MANGOS_ASSERT, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert().
insert()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert (const T & value) inline
Definition at line 75 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::ComputeCell(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::getGrid(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::memberTable, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
Referenced by DynTreeImpl::insert().
intersectPoint()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> template<typename IsectCallback > void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint (const Vector3 & point, IsectCallback & intersectCallback) inline
Definition at line 238 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::ComputeCell(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
intersectRay() [1/2]
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> template<typename RayCallback > void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay (const Ray & ray, RayCallback & intersectCallback, float & max_dist, const Vector3 & end, bool ignoreM2Model) inline
Definition at line 161 of file RegularGrid.h.
References CELL_SIZE, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::ComputeCell(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
intersectRay() [2/2]
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> template<typename RayCallback > void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay (const Ray & ray, RayCallback & intersectCallback, float max_dist, bool ignoreM2Model) inline
Definition at line 155 of file RegularGrid.h.
Referenced by DynamicMapTree::getIntersectionTime(), and DynamicMapTree::isInLineOfSight().
intersectZAllignedRay()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> template<typename RayCallback > void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay (const Ray & ray, RayCallback & intersectCallback, float & max_dist) inline
Definition at line 249 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::ComputeCell(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
Referenced by DynamicMapTree::getHeight().
MapEqualRange()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> template<class M > auto RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::MapEqualRange (M & map, typename M::key_type const & key) -> IteratorPair<decltype(map.begin())> inline
Definition at line 108 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::remove().
remove()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> void RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::remove (const T & value) inline
Definition at line 113 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::MapEqualRange(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::memberTable.
Referenced by DynTreeImpl::remove().
size()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> int RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::size () const inline
Definition at line 130 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::memberTable.
Referenced by DynamicMapTree::size(), and DynTreeImpl::update().
Field Documentation
memberTable
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> MemberTable RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::memberTable
Definition at line 60 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::contains(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::remove(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::size().
nodes
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> Node* RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::nodes[CELL_NUMBER][CELL_NUMBER]
Definition at line 61 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::balance(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::getGrid(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::RegularGrid2D(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::~RegularGrid2D().
The documentation for this class was generated from the following file:
RegularGrid.h