CMaNGOS_WoTLK: ChannelMgr Class Reference
ChannelMgr Class Reference
#include <ChannelMgr.h>
Public Types
typedef std::map< std::wstring, Channel * > ChannelMap
Public Member Functions
ChannelMgr ()
~ChannelMgr ()
const ChannelMap & GetChannels () const
Channel * GetJoinChannel (const std::string &name, uint32 channel_id)
Channel * GetChannel (const std::string &name, Player *p, bool pkt=true)
void LeftChannel (const std::string &name)
Private Attributes
ChannelMap channels
Detailed Description
Definition at line 26 of file ChannelMgr.h.
Member Typedef Documentation
ChannelMap
typedef std::map<std::wstring, Channel*> ChannelMgr::ChannelMap
Definition at line 29 of file ChannelMgr.h.
Constructor & Destructor Documentation
ChannelMgr()
ChannelMgr::ChannelMgr () inline
Definition at line 30 of file ChannelMgr.h.
~ChannelMgr()
ChannelMgr::~ChannelMgr ()
Definition at line 39 of file ChannelMgr.cpp.
References channels.
Member Function Documentation
GetChannel()
Channel * ChannelMgr::GetChannel (const std::string & name, Player * p, bool pkt = true)
Definition at line 63 of file ChannelMgr.cpp.
References channels, Player::GetSession(), Channel::MakeNotMember(), WorldSession::SendPacket(), Utf8toWStr(), and wstrToLower().
Referenced by ChatHandler::HandleChannelStaticCommand().
GetChannels()
const ChannelMap& ChannelMgr::GetChannels () const inline
Definition at line 33 of file ChannelMgr.h.
References channels.
Referenced by ChatHandler::HandleChannelListCommand().
GetJoinChannel()
Channel * ChannelMgr::GetJoinChannel (const std::string & name, uint32 channel_id)
Definition at line 47 of file ChannelMgr.cpp.
References channels, Utf8toWStr(), and wstrToLower().
Referenced by Player::UpdateLocalChannels().
LeftChannel()
void ChannelMgr::LeftChannel (const std::string & name)
Definition at line 85 of file ChannelMgr.cpp.
References channels, Channel::GetNumPlayers(), Channel::IsConstant(), Utf8toWStr(), and wstrToLower().
Referenced by Player::UpdateLocalChannels().
Field Documentation
channels
ChannelMap ChannelMgr::channels private
Definition at line 39 of file ChannelMgr.h.
Referenced by GetChannel(), GetChannels(), GetJoinChannel(), LeftChannel(), and ~ChannelMgr().
The documentation for this class was generated from the following files:
ChannelMgr.h
ChannelMgr.cpp