CMaNGOS_WoTLK: CombatAI Class Reference
CombatAI Class Reference
#include <CombatAI.h>
Public Member Functions
CombatAI (Creature *creature, uint32 combatActions)
void Reset () override
void HandleDelayedInstantAnimation (SpellEntry const *spellInfo) override
void HandleTargetRestoration ()
bool IsTargetingRestricted ()
void StopTargeting (bool state)
void OnTaunt () override
void AddOnKillText (int32 text)
template<typename... Targs>
void AddOnKillText (int32 value, Targs... fargs)
void AddOnKillSound (int32 soundId)
void KilledUnit (Unit *) override
Called when the creature kills a unit.
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void ReceiveAIEvent (AIEventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
virtual void Aggro (Unit *)
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void MoveInLineOfSight (Unit *)
== Reactions At =================================
virtual void JustReachedHome ()
Called at reaching home after MoveTargetedHome.
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void JustDied (Unit *)
Called when the creature is killed.
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (Creature *)
Called when the creature summon successfully other creature.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Private Attributes
ObjectGuid m_storedTarget
std::vector< std::pair< int32, bool > > m_onDeathReactions
bool m_onKillCooldown
bool m_stopTargeting
Additional Inherited Members
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 26 of file CombatAI.h.
Constructor & Destructor Documentation
CombatAI()
CombatAI::CombatAI (Creature * creature, uint32 combatActions)
Definition at line 31 of file CombatAI.cpp.
References ACTION_CASTING_RESTORE, ACTION_ON_KILL_COOLDOWN, TimerManager::AddCustomAction(), HandleTargetRestoration(), and m_onKillCooldown.
Member Function Documentation
AddOnKillSound()
void CombatAI::AddOnKillSound (int32 soundId)
Definition at line 84 of file CombatAI.cpp.
References m_onDeathReactions.
Referenced by boss_essence_of_angerAI::boss_essence_of_angerAI(), and boss_majordomoAI::boss_majordomoAI().
AddOnKillText() [1/2]
void CombatAI::AddOnKillText (int32 text)
Definition at line 79 of file CombatAI.cpp.
References m_onDeathReactions.
Referenced by AddOnKillText(), boss_akilzonAI::boss_akilzonAI(), boss_alythessAI::boss_alythessAI(), boss_anetheronAI::boss_anetheronAI(), boss_anubrekhanAI::boss_anubrekhanAI(), boss_archimondeAI::boss_archimondeAI(), boss_attumenAI::boss_attumenAI(), boss_azgalorAI::boss_azgalorAI(), boss_blackheart_the_inciterAI::boss_blackheart_the_inciterAI(), boss_brutallusAI::boss_brutallusAI(), boss_curatorAI::boss_curatorAI(), boss_essence_of_angerAI::boss_essence_of_angerAI(), boss_essence_of_desireAI::boss_essence_of_desireAI(), boss_essence_of_sufferingAI::boss_essence_of_sufferingAI(), boss_faerlinaAI::boss_faerlinaAI(), boss_felmystAI::boss_felmystAI(), boss_feugenAI::boss_feugenAI(), boss_galdarahAI::boss_galdarahAI(), boss_gathios_the_shattererAI::boss_gathios_the_shattererAI(), boss_gothikAI::boss_gothikAI(), boss_gruulAI::boss_gruulAI(), boss_gurtogg_bloodboilAI::boss_gurtogg_bloodboilAI(), boss_halazziAI::boss_halazziAI(), boss_heiganAI::boss_heiganAI(), boss_high_king_maulgarAI::boss_high_king_maulgarAI(), boss_high_nethermancer_zerevorAI::boss_high_nethermancer_zerevorAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_janalaiAI::boss_janalaiAI(), boss_kalecgosAI::boss_kalecgosAI(), boss_kazrogalAI::boss_kazrogalAI(), boss_kelthuzadAI::boss_kelthuzadAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_lady_blaumeuxAI::boss_lady_blaumeuxAI(), boss_lady_malandeAI::boss_lady_malandeAI(), boss_maiden_of_virtueAI::boss_maiden_of_virtueAI(), boss_majordomoAI::boss_majordomoAI(), boss_malacrassAI::boss_malacrassAI(), boss_malchezaarAI::boss_malchezaarAI(), boss_moroesAI::boss_moroesAI(), boss_najentusAI::boss_najentusAI(), boss_nalorakkAI::boss_nalorakkAI(), boss_nothAI::boss_nothAI(), boss_ossirianAI::boss_ossirianAI(), boss_patchwerkAI::boss_patchwerkAI(), boss_rage_winterchillAI::boss_rage_winterchillAI(), boss_ragnarosAI::boss_ragnarosAI(), boss_razuviousAI::boss_razuviousAI(), boss_rivendare_naxxAI::boss_rivendare_naxxAI(), boss_sacrolashAI::boss_sacrolashAI(), boss_sarturaAI::boss_sarturaAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_shahrazAI::boss_shahrazAI(), boss_sir_zeliekAI::boss_sir_zeliekAI(), boss_skeramAI::boss_skeramAI(), boss_sladranAI::boss_sladranAI(), boss_stalaggAI::boss_stalaggAI(), boss_temporusAI::boss_temporusAI(), boss_terestianAI::boss_terestianAI(), boss_teron_gorefiendAI::boss_teron_gorefiendAI(), boss_thaddiusAI::boss_thaddiusAI(), boss_thane_korthazzAI::boss_thane_korthazzAI(), boss_veklorAI::boss_veklorAI(), boss_veras_darkshadowAI::boss_veras_darkshadowAI(), boss_vexallusAI::boss_vexallusAI(), and boss_zuljinAI::boss_zuljinAI().
AddOnKillText() [2/2]
template<typename... Targs> void CombatAI::AddOnKillText (int32 value, Targs... fargs) inline
Definition at line 41 of file CombatAI.h.
References AddOnKillText().
HandleDelayedInstantAnimation()
void CombatAI::HandleDelayedInstantAnimation (SpellEntry const * spellInfo) override virtual
Reimplemented from UnitAI.
Definition at line 44 of file CombatAI.cpp.
References ACTION_CASTING_RESTORE, Object::GetObjectGuid(), Unit::GetTarget(), CreatureAI::m_creature, m_storedTarget, and CombatActions::ResetTimer().
HandleTargetRestoration()
void CombatAI::HandleTargetRestoration ()
Definition at line 51 of file CombatAI.cpp.
References UnitAI::GetCombatScriptStatus(), Object::GetObjectGuid(), Unit::GetTarget(), Unit::GetVictim(), Unit::IsNonMeleeSpellCasted(), m_storedTarget, UnitAI::m_unit, and Unit::SetTarget().
Referenced by CombatAI(), and boss_nothAI::ExecuteAction().
IsTargetingRestricted()
bool CombatAI::IsTargetingRestricted () virtual
Reimplemented from UnitAI.
Definition at line 68 of file CombatAI.cpp.
References UnitAI::IsTargetingRestricted(), m_stopTargeting, and m_storedTarget.
KilledUnit()
void CombatAI::KilledUnit (Unit *) override virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented from UnitAI.
Reimplemented in boss_xevozzAI, boss_ichoronAI, boss_void_reaverAI, boss_high_astromancer_solarianAI, boss_magtheridonAI, boss_leotheras_the_blindAI, boss_maievAI, boss_svalaAI, boss_skadiAI, boss_kelesethAI, boss_ingvarAI, boss_sjonnirAI, boss_zarithrianAI, boss_baltharusAI, boss_eregosAI, boss_telestraAI, boss_ormorokAI, boss_keristraszaAI, boss_anomalusAI, boss_kelthuzadAI, boss_gluthAI, boss_anubrekhanAI, boss_lady_deathwhisperAI, boss_deathbringer_saurfangAI, boss_forgemaster_garfrostAI, boss_bronjahmAI, boss_krikthirAI, boss_hadronoxAI, boss_buruAI, boss_azuregosAI, boss_mandokirAI, boss_spirit_lynxAI, boss_arugalAI, priestess_companion_commonAI, boss_priestess_delrissaAI, boss_nefarianAI, boss_tyrannusAI, boss_krickAI, boss_ickAI, mob_ohganAI, boss_vaelastraszAI, boss_watchkeeper_gargolmarAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_the_makerAI, boss_kelidan_the_breakerAI, boss_swamplord_muselekAI, boss_morogrim_tidewalkerAI, boss_lady_vashjAI, boss_talon_king_ikissAI, boss_nexusprince_shaffarAI, boss_moorabiAI, boss_veknilashAI, boss_high_inquisitor_whitemaneAI, boss_scarlet_commander_mograineAI, boss_selin_fireheartAI, boss_aranAI, and boss_midnightAI.
Definition at line 89 of file CombatAI.cpp.
References ACTION_ON_KILL_COOLDOWN, DoBroadcastText(), Unit::IsAlive(), Object::IsPlayer(), CreatureAI::m_creature, m_onDeathReactions, m_onKillCooldown, WorldObject::PlayDirectSound(), CombatActions::ResetTimer(), and urand().
Referenced by boss_ickAI::KilledUnit(), boss_krickAI::KilledUnit(), boss_tyrannusAI::KilledUnit(), boss_hadronoxAI::KilledUnit(), boss_krikthirAI::KilledUnit(), boss_bronjahmAI::KilledUnit(), boss_forgemaster_garfrostAI::KilledUnit(), boss_deathbringer_saurfangAI::KilledUnit(), boss_lady_deathwhisperAI::KilledUnit(), boss_anubrekhanAI::KilledUnit(), boss_anomalusAI::KilledUnit(), boss_keristraszaAI::KilledUnit(), boss_ormorokAI::KilledUnit(), boss_telestraAI::KilledUnit(), boss_eregosAI::KilledUnit(), boss_baltharusAI::KilledUnit(), boss_zarithrianAI::KilledUnit(), boss_sjonnirAI::KilledUnit(), boss_ingvarAI::KilledUnit(), boss_kelesethAI::KilledUnit(), boss_skadiAI::KilledUnit(), boss_svalaAI::KilledUnit(), boss_ichoronAI::KilledUnit(), and boss_xevozzAI::KilledUnit().
OnTaunt()
void CombatAI::OnTaunt () override virtual
Reimplemented from UnitAI.
Definition at line 73 of file CombatAI.cpp.
References ACTION_CASTING_RESTORE, m_storedTarget, and CombatActions::ResetTimer().
Reset()
void CombatAI::Reset () override virtual
Reimplemented from CreatureAI.
Reimplemented in PallidHorrorAI, npc_shaman_fire_elementalAI, npc_burster_wormAI, boss_high_astromancer_solarianAI, boss_alarAI, npc_shartuulAI, npc_dreadmawAI, npc_eye_of_shartuulAI, npc_shivan_assassinAI, npc_doomguard_punisherAI, mob_torlothAI, npc_razorthorn_ravager, npc_magister_aledisAI, npc_shattered_hand_legionnaire, boss_magtheridonAI, boss_omor_the_unscarredAI, boss_vazruden_heraldAI, boss_kelidan_the_breakerAI, boss_high_king_maulgarAI, boss_gruulAI, boss_swamplord_muselekAI, boss_black_stalkerAI, boss_ahuneAI, boss_the_lurker_belowAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, boss_terokkAI, boss_gathios_the_shattererAI, boss_illidari_councilAI, boss_najentusAI, boss_teron_gorefiendAI, boss_supremusAI, npc_akamaAI, boss_essence_of_angerAI, boss_shahrazAI, boss_maievAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_bonechewer_combatant, npc_bonechewer_brawler, boss_talon_king_ikissAI, boss_shirrakAI, boss_skadiAI, boss_ingvarAI, boss_sjonnirAI, boss_baltharusAI, boss_eregosAI, boss_telestraAI, boss_keristraszaAI, boss_anomalusAI, boss_feugenAI, boss_stalaggAI, boss_thaddiusAddsAI, boss_thaddiusAI, boss_sapphironAI, boss_razuviousAI, boss_patchwerkAI, boss_nothAI, boss_maexxnaAI, boss_loathebAI, boss_kelthuzadAI, boss_heiganAI, boss_gothikAI, boss_gluthAI, boss_sir_zeliekAI, boss_thane_korthazzAI, boss_rivendare_naxxAI, boss_lady_blaumeuxAI, boss_anubrekhanAI, boss_lady_deathwhisperAI, boss_deathbringer_saurfangAI, boss_moorabiAI, boss_galdarahAI, boss_drakkari_colossusAI, npc_anubisath_sentinelAI, boss_viscidusAI, boss_veklorAI, boss_veknilashAI, boss_skeramAI, boss_ouroAI, boss_fankrissAI, npc_giant_claw_tentacleAI, boss_cthunAI, boss_eye_of_cthunAI, boss_yaujAI, boss_vemAI, boss_kriAI, boss_silithidRoyaltyAI, boss_ossirianAI, boss_moamAI, boss_buruAI, boss_ayamissAI, npc_corrupted_furbolgAI, hyjalAI, boss_kazrogalAI, boss_archimondeAI, boss_anetheronAI, boss_azuregosAI, mob_zealot_zathAI, mob_zealot_lorkhanAI, boss_thekalAI, boss_thekalBaseAI, boss_renatakiAI, boss_marliAI, boss_mandokirAI, npc_gurubashi_bat_riderAI, boss_jeklikAI, boss_hakkarAI, boss_arlokkAI, boss_zuljinAI, boss_nalorakkAI, boss_malacrassAI, boss_janalaiAI, boss_halazziAI, boss_akilzonAI, npc_sunblade_protectorAI, npc_sunblade_scoutAI, npc_singularityAI, boss_muruAI, boss_kiljaedenAI, boss_kalecgos_humanoidAI, boss_sathrovarrAI, boss_kalecgosAI, boss_felmystAI, boss_sacrolashAI, boss_alythessAI, boss_brutallusAI, boss_arugalAI, boss_apothecary_hummelAI, boss_scarlet_commander_mograineAI, npc_death_knight_initiateAI, boss_ragnarosAI, boss_majordomoAI, boss_magmadarAI, mob_core_ragerAI, boss_golemaggAI, npc_kalecgosAI, boss_vexallusAI, boss_selin_fireheartAI, npc_eramas_brightblazeAI, npc_kagani_nightstrikeAI, boss_priestess_delrissaAI, boss_felblood_kaelthasAI, boss_dorotheeAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_nightbaneAI, boss_netherspiteAI, boss_moroesAI, boss_midnightAI, boss_curatorAI, boss_victor_nefariusAI, boss_vaelastraszAI, boss_razorgoreAI, and boss_ormorokAI.
Definition at line 37 of file CombatAI.cpp.
References m_onKillCooldown, m_storedTarget, and CreatureAI::Reset().
Referenced by boss_azgalorAI::boss_azgalorAI(), boss_baron_geddonAI::boss_baron_geddonAI(), boss_broodlordAI::boss_broodlordAI(), boss_garrAI::boss_garrAI(), boss_gehennasAI::boss_gehennasAI(), boss_lucifronAI::boss_lucifronAI(), boss_rage_winterchillAI::boss_rage_winterchillAI(), boss_sarturaAI::boss_sarturaAI(), boss_shazzrahAI::boss_shazzrahAI(), boss_spirit_lynxAI::boss_spirit_lynxAI(), boss_sulfuronAI::boss_sulfuronAI(), boss_temporusAI::boss_temporusAI(), npc_general_andorovAI::EnterEvadeMode(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_garaxxasAI::JustReachedHome(), boss_ormorokAI::Reset(), boss_razorgoreAI::Reset(), boss_vaelastraszAI::Reset(), boss_victor_nefariusAI::Reset(), boss_curatorAI::Reset(), boss_midnightAI::Reset(), boss_moroesAI::Reset(), boss_netherspiteAI::Reset(), boss_nightbaneAI::Reset(), boss_malchezaarAI::Reset(), boss_aranAI::Reset(), boss_terestianAI::Reset(), boss_dorotheeAI::Reset(), boss_felblood_kaelthasAI::Reset(), boss_priestess_delrissaAI::Reset(), npc_kagani_nightstrikeAI::Reset(), npc_eramas_brightblazeAI::Reset(), boss_selin_fireheartAI::Reset(), boss_vexallusAI::Reset(), boss_golemaggAI::Reset(), mob_core_ragerAI::Reset(), boss_magmadarAI::Reset(), boss_ragnarosAI::Reset(), npc_death_knight_initiateAI::Reset(), boss_scarlet_commander_mograineAI::Reset(), boss_apothecary_hummelAI::Reset(), boss_brutallusAI::Reset(), boss_alythessAI::Reset(), boss_sacrolashAI::Reset(), boss_felmystAI::Reset(), boss_kalecgosAI::Reset(), boss_sathrovarrAI::Reset(), boss_kalecgos_humanoidAI::Reset(), boss_kiljaedenAI::Reset(), boss_muruAI::Reset(), npc_sunblade_scoutAI::Reset(), npc_sunblade_protectorAI::Reset(), boss_akilzonAI::Reset(), boss_halazziAI::Reset(), boss_janalaiAI::Reset(), boss_malacrassAI::Reset(), boss_nalorakkAI::Reset(), boss_zuljinAI::Reset(), boss_arlokkAI::Reset(), boss_hakkarAI::Reset(), boss_jeklikAI::Reset(), npc_gurubashi_bat_riderAI::Reset(), boss_mandokirAI::Reset(), boss_marliAI::Reset(), boss_renatakiAI::Reset(), boss_thekalBaseAI::Reset(), boss_azuregosAI::Reset(), boss_anetheronAI::Reset(), boss_archimondeAI::Reset(), boss_kazrogalAI::Reset(), hyjalAI::Reset(), npc_corrupted_furbolgAI::Reset(), boss_ayamissAI::Reset(), boss_buruAI::Reset(), boss_moamAI::Reset(), boss_ossirianAI::Reset(), boss_silithidRoyaltyAI::Reset(), boss_eye_of_cthunAI::Reset(), boss_cthunAI::Reset(), boss_fankrissAI::Reset(), boss_ouroAI::Reset(), boss_skeramAI::Reset(), boss_veknilashAI::Reset(), boss_veklorAI::Reset(), boss_viscidusAI::Reset(), npc_anubisath_sentinelAI::Reset(), boss_drakkari_colossusAI::Reset(), boss_galdarahAI::Reset(), boss_moorabiAI::Reset(), boss_deathbringer_saurfangAI::Reset(), boss_lady_deathwhisperAI::Reset(), boss_lady_blaumeuxAI::Reset(), boss_rivendare_naxxAI::Reset(), boss_thane_korthazzAI::Reset(), boss_sir_zeliekAI::Reset(), boss_gluthAI::Reset(), boss_gothikAI::Reset(), boss_heiganAI::Reset(), boss_kelthuzadAI::Reset(), boss_maexxnaAI::Reset(), boss_patchwerkAI::Reset(), boss_razuviousAI::Reset(), boss_sapphironAI::Reset(), boss_thaddiusAI::Reset(), boss_thaddiusAddsAI::Reset(), boss_anomalusAI::Reset(), boss_keristraszaAI::Reset(), boss_telestraAI::Reset(), boss_eregosAI::Reset(), boss_baltharusAI::Reset(), boss_sjonnirAI::Reset(), boss_ingvarAI::Reset(), boss_skadiAI::Reset(), boss_shirrakAI::Reset(), boss_talon_king_ikissAI::Reset(), npc_bonechewer_brawler::Reset(), npc_bonechewer_combatant::Reset(), boss_gurtogg_bloodboilAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_maievAI::Reset(), boss_shahrazAI::Reset(), boss_essence_of_angerAI::Reset(), npc_akamaAI::Reset(), boss_supremusAI::Reset(), boss_teron_gorefiendAI::Reset(), boss_najentusAI::Reset(), boss_illidari_councilAI::Reset(), boss_terokkAI::Reset(), boss_fathomguard_sharkkisAI::Reset(), boss_fathomguard_tidalvessAI::Reset(), boss_lady_vashjAI::Reset(), boss_leotheras_the_blindAI::Reset(), boss_morogrim_tidewalkerAI::Reset(), boss_the_lurker_belowAI::Reset(), boss_ahuneAI::Reset(), boss_black_stalkerAI::Reset(), boss_swamplord_muselekAI::Reset(), boss_gruulAI::Reset(), boss_high_king_maulgarAI::Reset(), boss_kelidan_the_breakerAI::Reset(), boss_vazruden_heraldAI::Reset(), boss_omor_the_unscarredAI::Reset(), boss_magtheridonAI::Reset(), npc_magister_aledisAI::Reset(), mob_torlothAI::Reset(), npc_doomguard_punisherAI::Reset(), npc_shivan_assassinAI::Reset(), npc_eye_of_shartuulAI::Reset(), npc_dreadmawAI::Reset(), npc_shartuulAI::Reset(), boss_alarAI::Reset(), boss_high_astromancer_solarianAI::Reset(), npc_burster_wormAI::Reset(), npc_shaman_fire_elementalAI::Reset(), and PallidHorrorAI::Reset().
StopTargeting()
void CombatAI::StopTargeting (bool state) inline
Definition at line 36 of file CombatAI.h.
References m_stopTargeting.
Referenced by boss_muruAI::Aggro(), and boss_nothAI::ExecuteAction().
Field Documentation
m_onDeathReactions
std::vector<std::pair<int32, bool> > CombatAI::m_onDeathReactions private
Definition at line 53 of file CombatAI.h.
Referenced by AddOnKillSound(), AddOnKillText(), and KilledUnit().
m_onKillCooldown
bool CombatAI::m_onKillCooldown private
Definition at line 54 of file CombatAI.h.
Referenced by CombatAI(), KilledUnit(), and Reset().
m_stopTargeting
bool CombatAI::m_stopTargeting private
Definition at line 56 of file CombatAI.h.
Referenced by IsTargetingRestricted(), and StopTargeting().
m_storedTarget
ObjectGuid CombatAI::m_storedTarget private
Definition at line 51 of file CombatAI.h.
Referenced by HandleDelayedInstantAnimation(), HandleTargetRestoration(), IsTargetingRestricted(), OnTaunt(), and Reset().
The documentation for this class was generated from the following files:
CombatAI.h
CombatAI.cpp