CMaNGOS_WoTLK: instance_dire_maul Class Reference
instance_dire_maul Class Reference
#include <dire_maul.h>
Public Member Functions
instance_dire_maul (Map *pMap)
~instance_dire_maul ()
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
const char * Save () const override
void Load (const char *chrIn) override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
void Update (const uint32 diff) override
GuidVector GetRitualSymbolGuids ()
void ProcessDreadsteedRitualStart ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
bool CheckAllGeneratorsDestroyed ()
void ProcessForceFieldOpening ()
void SortPylonGuards ()
void PylonGuardJustDied (Creature *pCreature)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_bWallDestroyed
GuidList m_lFelvineShardGUIDs
ObjectGuid m_aCrystalGeneratorGuid [MAX_GENERATORS]
GuidList m_luiHighborneSummonerGUIDs
GuidList m_lGeneratorGuardGUIDs
GuidList m_lDreadsteedPortalsGUIDs
std::set< uint32 > m_sSortedGeneratorGuards [MAX_GENERATORS]
GuidVector m_lRitualSymbolGUIDs
bool m_bDoNorthBeforeWest
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 125 of file dire_maul.h.
Constructor & Destructor Documentation
instance_dire_maul()
instance_dire_maul::instance_dire_maul (Map * pMap)
Definition at line 27 of file instance_dire_maul.cpp.
References Initialize().
~instance_dire_maul()
instance_dire_maul::~instance_dire_maul () inline
Definition at line 129 of file dire_maul.h.
Member Function Documentation
CheckAllGeneratorsDestroyed()
bool instance_dire_maul::CheckAllGeneratorsDestroyed () protected
Definition at line 520 of file instance_dire_maul.cpp.
References DONE, m_auiEncounter, TYPE_PYLON_1, TYPE_PYLON_2, TYPE_PYLON_3, TYPE_PYLON_4, and TYPE_PYLON_5.
Referenced by OnObjectCreate(), and SetData().
CheckConditionCriteriaMeet()
bool instance_dire_maul::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 491 of file instance_dire_maul.cpp.
References DONE, GetData(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, INSTANCE_CONDITION_ID_HARD_MODE_3, INSTANCE_CONDITION_ID_HARD_MODE_4, INSTANCE_CONDITION_ID_HARD_MODE_5, INSTANCE_CONDITION_ID_HARD_MODE_6, INSTANCE_CONDITION_ID_NORMAL_MODE, script_error_log(), TYPE_CHORUSH, TYPE_FENGUS, TYPE_KROMCRUSH, TYPE_MOLDAR, TYPE_SLIPKIK, and TYPE_STOMPER_KREEG.
GetData()
uint32 instance_dire_maul::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 378 of file instance_dire_maul.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by CheckConditionCriteriaMeet(), PylonGuardJustDied(), SortPylonGuards(), and Update().
GetRitualSymbolGuids()
GuidVector instance_dire_maul::GetRitualSymbolGuids ()
Definition at line 515 of file instance_dire_maul.cpp.
References m_lRitualSymbolGUIDs.
Referenced by npc_warlock_mount_ritualAI::DoSummonPack().
Initialize()
void instance_dire_maul::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 34 of file instance_dire_maul.cpp.
References m_auiEncounter.
Referenced by instance_dire_maul().
Load()
void instance_dire_maul::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 460 of file instance_dire_maul.cpp.
References DONE, IN_PROGRESS, m_auiEncounter, m_bWallDestroyed, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, and TYPE_ALZZIN.
OnCreatureCreate()
void instance_dire_maul::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 73 of file instance_dire_maul.cpp.
References DONE, FACTION_HOSTILE, Object::GetEntry(), Object::GetObjectGuid(), m_auiEncounter, m_lGeneratorGuardGUIDs, m_luiHighborneSummonerGUIDs, ScriptedInstance::m_npcEntryGuidStore, NPC_ARCANE_ABERRATION, NPC_CAPTAIN_KROMCRUSH, NPC_CHO_RUSH_THE_OBSERVER, NPC_GUARD_SLIPKIK, NPC_HIGHBORNE_SUMMONER, NPC_IMMOLTHAR, NPC_JEEVEE, NPC_KING_GORDOK, NPC_MANA_REMNANT, NPC_OLD_IRONBARK, NPC_PRINCE_TORTHELDRIN, NPC_WARLOCK_DUMMY_INFERNAL, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, TYPE_IMMOLTHAR, TYPE_KING_GORDOK, and UNIT_STAND_STATE_SIT.
OnCreatureDeath()
void instance_dire_maul::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 403 of file instance_dire_maul.cpp.
References DONE, Object::GetEntry(), NPC_ARCANE_ABERRATION, NPC_CAPTAIN_KROMCRUSH, NPC_CHO_RUSH_THE_OBSERVER, NPC_GUARD_FENGUS, NPC_GUARD_MOLDAR, NPC_GUARD_SLIPKIK, NPC_IMMOLTHAR, NPC_IRONBARK_REDEEMED, NPC_KING_GORDOK, NPC_LORD_HELNURATH, NPC_MANA_REMNANT, NPC_STOMPER_KREEG, NPC_TENDRIS_WARPWOOD, NPC_ZEVRIM_THORNHOOF, PylonGuardJustDied(), SetData(), TYPE_CHORUSH, TYPE_DREADSTEED, TYPE_FENGUS, TYPE_IMMOLTHAR, TYPE_IRONBARK, TYPE_KING_GORDOK, TYPE_KROMCRUSH, TYPE_MOLDAR, TYPE_SLIPKIK, TYPE_STOMPER_KREEG, TYPE_WARPWOOD, and TYPE_ZEVRIM.
OnCreatureEnterCombat()
void instance_dire_maul::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 386 of file instance_dire_maul.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_ARCANE_ABERRATION, NPC_IMMOLTHAR, NPC_MANA_REMNANT, SetData(), SortPylonGuards(), and TYPE_IMMOLTHAR.
OnObjectCreate()
void instance_dire_maul::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 114 of file instance_dire_maul.cpp.
References CheckAllGeneratorsDestroyed(), DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), GO_BELL_OF_DETHMOORA, GO_CONSERVATORY_DOOR, GO_CORRUPT_VINE, GO_CRUMBLE_WALL, GO_CRYSTAL_GENERATOR_1, GO_CRYSTAL_GENERATOR_2, GO_CRYSTAL_GENERATOR_3, GO_CRYSTAL_GENERATOR_4, GO_CRYSTAL_GENERATOR_5, GO_DOOMSDAY_CANDLE, GO_DREADSTEED_PORTAL, GO_FELVINE_SHARD, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_FORCEFIELD, GO_MOUNT_QUEST_SYMBOL1, GO_MOUNT_QUEST_SYMBOL2, GO_MOUNT_QUEST_SYMBOL3, GO_NORTH_LIBRARY_DOOR, GO_PRINCES_CHEST_AURA, GO_RITUAL_CANDLE_AURA, GO_STATE_ACTIVE, GO_WARLOCK_RITUAL_CIRCLE, GO_WARPWOOD_DOOR, GO_WEST_LIBRARY_DOOR, GO_WHEEL_OF_BLACK_MARCH, m_aCrystalGeneratorGuid, m_auiEncounter, m_bDoNorthBeforeWest, m_bWallDestroyed, ScriptedInstance::m_goEntryGuidStore, m_lDreadsteedPortalsGUIDs, m_lFelvineShardGUIDs, m_lRitualSymbolGUIDs, Object::RemoveFlag(), Object::SetFlag(), GameObject::SetGoState(), TYPE_ALZZIN, TYPE_IRONBARK, TYPE_PYLON_1, TYPE_PYLON_2, TYPE_PYLON_3, TYPE_PYLON_4, TYPE_PYLON_5, and TYPE_WARPWOOD.
OnPlayerEnter()
void instance_dire_maul::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 60 of file instance_dire_maul.cpp.
References DONE, ScriptedInstance::DoToggleGameObjectFlags(), GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_WEST_LIBRARY_DOOR, WorldObject::IsWithinDist2d(), m_auiEncounter, m_bDoNorthBeforeWest, and TYPE_WARPWOOD.
ProcessDreadsteedRitualStart()
void instance_dire_maul::ProcessDreadsteedRitualStart ()
Definition at line 607 of file instance_dire_maul.cpp.
References ScriptedInstance::DoRespawnGameObject(), Map::GetGameObject(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_WARLOCK_RITUAL_CIRCLE, InstanceData::instance, and m_lDreadsteedPortalsGUIDs.
Referenced by npc_warlock_mount_ritualAI::UpdateAI().
ProcessForceFieldOpening()
void instance_dire_maul::ProcessForceFieldOpening () protected
Definition at line 525 of file instance_dire_maul.cpp.
References Creature::AI(), UnitAI::AttackStart(), DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_FORCEFIELD, InstanceData::instance, Unit::IsDead(), m_luiHighborneSummonerGUIDs, NPC_IMMOLTHAR, and SAY_KILL_IMMOLTHAR.
Referenced by SetData().
PylonGuardJustDied()
void instance_dire_maul::PylonGuardJustDied (Creature * pCreature) protected
Definition at line 587 of file instance_dire_maul.cpp.
References DONE, GetData(), Object::GetGUIDLow(), m_sSortedGeneratorGuards, MAX_GENERATORS, SetData(), and TYPE_PYLON_1.
Referenced by OnCreatureDeath().
Save()
const char* instance_dire_maul::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 144 of file dire_maul.h.
References m_strInstData.
SetData()
void instance_dire_maul::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 202 of file instance_dire_maul.cpp.
References afMizzleSpawnLoc, CheckAllGeneratorsDestroyed(), DONE, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), FACTION_FRIENDLY, FACTION_HOSTILE, FAIL, Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_BELL_OF_DETHMOORA, GO_CORRUPT_VINE, GO_CRUMBLE_WALL, GO_DOOMSDAY_CANDLE, GO_JUST_DEACTIVATED, GO_PRINCES_CHEST_AURA, GO_WARLOCK_RITUAL_CIRCLE, GO_WARPWOOD_DOOR, GO_WHEEL_OF_BLACK_MARCH, InstanceData::instance, m_aCrystalGeneratorGuid, m_auiEncounter, m_bWallDestroyed, m_lDreadsteedPortalsGUIDs, m_lFelvineShardGUIDs, m_lRitualSymbolGUIDs, m_strInstData, NPC_CAPTAIN_KROMCRUSH, NPC_CHO_RUSH_THE_OBSERVER, NPC_IRONBARK_REDEEMED, NPC_MIZZLE_THE_CRAFTY, NPC_OLD_IRONBARK, NPC_PRINCE_TORTHELDRIN, NPC_WARLOCK_DUMMY_INFERNAL, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, ProcessForceFieldOpening(), InstanceData::SaveToDB(), SAY_CHORUSH_KING_DEAD, SAY_FREE_IMMOLTHAR, SAY_IRONBARK_REDEEM, GameObject::SetLootState(), SPECIAL, WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, TEMPSPAWN_DEAD_DESPAWN, TYPE_ALZZIN, TYPE_CHORUSH, TYPE_DREADSTEED, TYPE_FENGUS, TYPE_IMMOLTHAR, TYPE_IRONBARK, TYPE_KING_GORDOK, TYPE_KROMCRUSH, TYPE_MOLDAR, TYPE_PRINCE, TYPE_PYLON_1, TYPE_PYLON_2, TYPE_PYLON_3, TYPE_PYLON_4, TYPE_PYLON_5, TYPE_SLIPKIK, TYPE_STOMPER_KREEG, TYPE_WARPWOOD, TYPE_ZEVRIM, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), PylonGuardJustDied(), Update(), and npc_warlock_mount_ritualAI::UpdateAI().
SortPylonGuards()
void instance_dire_maul::SortPylonGuards () protected
Definition at line 554 of file instance_dire_maul.cpp.
References DONE, Map::GetCreature(), GetData(), Map::GetGameObject(), Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), InstanceData::instance, Unit::IsDead(), WorldObject::IsWithinDist2d(), m_aCrystalGeneratorGuid, m_lGeneratorGuardGUIDs, m_sSortedGeneratorGuards, MAX_GENERATORS, and TYPE_PYLON_1.
Referenced by OnCreatureEnterCombat().
Update()
void instance_dire_maul::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 39 of file instance_dire_maul.cpp.
References FAIL, Map::GetCreature(), GetData(), Map::GetGameObject(), GameObject::GetGoState(), Map::GetPlayersCountExceptGMs(), GO_BELL_OF_DETHMOORA, GO_DOOMSDAY_CANDLE, GO_STATE_ACTIVE, GO_WHEEL_OF_BLACK_MARCH, IN_PROGRESS, InstanceData::instance, ScriptedInstance::m_goEntryGuidStore, ScriptedInstance::m_npcEntryGuidStore, NPC_JEEVEE, SetData(), and TYPE_DREADSTEED.
Field Documentation
m_aCrystalGeneratorGuid
ObjectGuid instance_dire_maul::m_aCrystalGeneratorGuid[MAX_GENERATORS] protected
Definition at line 167 of file dire_maul.h.
Referenced by OnObjectCreate(), SetData(), and SortPylonGuards().
m_auiEncounter
uint32 instance_dire_maul::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 159 of file dire_maul.h.
Referenced by CheckAllGeneratorsDestroyed(), GetData(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), OnPlayerEnter(), and SetData().
m_bDoNorthBeforeWest
bool instance_dire_maul::m_bDoNorthBeforeWest protected
Definition at line 177 of file dire_maul.h.
Referenced by OnObjectCreate(), and OnPlayerEnter().
m_bWallDestroyed
bool instance_dire_maul::m_bWallDestroyed protected
Definition at line 163 of file dire_maul.h.
Referenced by Load(), OnObjectCreate(), and SetData().
m_lDreadsteedPortalsGUIDs
GuidList instance_dire_maul::m_lDreadsteedPortalsGUIDs protected
Definition at line 171 of file dire_maul.h.
Referenced by OnObjectCreate(), ProcessDreadsteedRitualStart(), and SetData().
m_lFelvineShardGUIDs
GuidList instance_dire_maul::m_lFelvineShardGUIDs protected
Definition at line 164 of file dire_maul.h.
Referenced by OnObjectCreate(), and SetData().
m_lGeneratorGuardGUIDs
GuidList instance_dire_maul::m_lGeneratorGuardGUIDs protected
Definition at line 170 of file dire_maul.h.
Referenced by OnCreatureCreate(), and SortPylonGuards().
m_lRitualSymbolGUIDs
GuidVector instance_dire_maul::m_lRitualSymbolGUIDs protected
Definition at line 174 of file dire_maul.h.
Referenced by GetRitualSymbolGuids(), OnObjectCreate(), and SetData().
m_luiHighborneSummonerGUIDs
GuidList instance_dire_maul::m_luiHighborneSummonerGUIDs protected
Definition at line 169 of file dire_maul.h.
Referenced by OnCreatureCreate(), and ProcessForceFieldOpening().
m_sSortedGeneratorGuards
std::set<uint32> instance_dire_maul::m_sSortedGeneratorGuards[MAX_GENERATORS] protected
Definition at line 172 of file dire_maul.h.
Referenced by PylonGuardJustDied(), and SortPylonGuards().
m_strInstData
std::string instance_dire_maul::m_strInstData protected
Definition at line 160 of file dire_maul.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
dire_maul.h
instance_dire_maul.cpp