CMaNGOS_WoTLK: OutdoorPvPSI Class Reference
OutdoorPvPSI Class Reference
#include <OutdoorPvPSI.h>
Public Member Functions
OutdoorPvPSI ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
bool HandleAreaTrigger (Player *player, uint32 triggerId) override
bool HandleGameObjectUse (Player *player, GameObject *go) override
bool HandleDropFlag (Player *player, uint32 spellId) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectCreate (GameObject *)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Attributes
uint8 m_resourcesAlliance
uint8 m_resourcesHorde
Team m_zoneOwner
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 59 of file OutdoorPvPSI.h.
Constructor & Destructor Documentation
OutdoorPvPSI()
OutdoorPvPSI::OutdoorPvPSI ()
Definition at line 29 of file OutdoorPvPSI.cpp.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPSI::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 37 of file OutdoorPvPSI.cpp.
References FillInitialWorldState(), m_resourcesAlliance, m_resourcesHorde, MAX_SILITHYST, WORLD_STATE_SI_GATHERED_A, WORLD_STATE_SI_GATHERED_H, and WORLD_STATE_SI_SILITHYST_MAX.
HandleAreaTrigger()
bool OutdoorPvPSI::HandleAreaTrigger (Player * player, uint32 triggerId) override virtual
Reimplemented from OutdoorPvP.
Definition at line 67 of file OutdoorPvPSI.cpp.
References ALLIANCE, AREATRIGGER_SILITHUS_ALLIANCE, AREATRIGGER_SILITHUS_HORDE, OutdoorPvP::BuffTeam(), Unit::CastSpell(), FACTION_CENARION_CIRCLE, Player::GetQuestStatus(), Player::GetReputationMgr(), Player::GetTeam(), Unit::HasAura(), HONOR_REWARD_SILITHYST, HORDE, Unit::IsDead(), Player::IsGameMaster(), Player::KilledMonsterCredit(), LANG_OPVP_SI_CAPTURE_A, LANG_OPVP_SI_CAPTURE_H, m_resourcesAlliance, m_resourcesHorde, m_zoneOwner, MAX_SILITHYST, ReputationMgr::ModifyReputation(), NPC_SILITHUS_DUST_QUEST_ALLIANCE, NPC_SILITHUS_DUST_QUEST_HORDE, QUEST_SCOURING_DESERT_ALLIANCE, QUEST_SCOURING_DESERT_HORDE, QUEST_STATUS_INCOMPLETE, Unit::RemoveAurasDueToSpell(), REPUTATION_REWARD_SILITHYST, Player::RewardHonor(), OutdoorPvP::SendUpdateWorldState(), sFactionStore, SPELL_CENARION_FAVOR, SPELL_SILITHYST, SPELL_TRACES_OF_SILITHYST, sWorld, TRIGGERED_OLD_TRIGGERED, WORLD_STATE_SI_GATHERED_A, WORLD_STATE_SI_GATHERED_H, and ZONE_ID_SILITHUS.
HandleDropFlag()
bool OutdoorPvPSI::HandleDropFlag (Player * player, uint32 spellId) override virtual
Reimplemented from OutdoorPvP.
Definition at line 162 of file OutdoorPvPSI.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetTeam(), HORDE, WorldObject::IsWithinDist3d(), silithusFlagDropLocations, SPELL_SILITHYST, SPELL_SILITHYST_FLAG_DROP, TRIGGERED_OLD_TRIGGERED, SilithusSpawnLocation::x, SilithusSpawnLocation::y, and SilithusSpawnLocation::z.
HandleGameObjectUse()
bool OutdoorPvPSI::HandleGameObjectUse (Player * player, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 190 of file OutdoorPvPSI.cpp.
References Unit::CastSpell(), Object::GetEntry(), GO_JUST_DEACTIVATED, GO_SILITHYST_GEYSER, GO_SILITHYST_MOUND, GameObject::SetLootState(), SPELL_SILITHYST, TRIGGERED_OLD_TRIGGERED, and Player::UpdatePvP().
HandlePlayerEnterZone()
void OutdoorPvPSI::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 45 of file OutdoorPvPSI.cpp.
References Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), m_zoneOwner, Unit::RemoveAurasDueToSpell(), SPELL_CENARION_FAVOR, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerLeaveZone()
void OutdoorPvPSI::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 58 of file OutdoorPvPSI.cpp.
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and SPELL_CENARION_FAVOR.
Field Documentation
m_resourcesAlliance
uint8 OutdoorPvPSI::m_resourcesAlliance private
Definition at line 73 of file OutdoorPvPSI.h.
Referenced by FillInitialWorldStates(), and HandleAreaTrigger().
m_resourcesHorde
uint8 OutdoorPvPSI::m_resourcesHorde private
Definition at line 74 of file OutdoorPvPSI.h.
Referenced by FillInitialWorldStates(), and HandleAreaTrigger().
m_zoneOwner
Team OutdoorPvPSI::m_zoneOwner private
Definition at line 75 of file OutdoorPvPSI.h.
Referenced by HandleAreaTrigger(), and HandlePlayerEnterZone().
The documentation for this class was generated from the following files:
OutdoorPvPSI.h
OutdoorPvPSI.cpp