CMaNGOS_WoTLK: ScriptAction Class Reference
ScriptAction Class Reference
#include <ScriptMgr.h>
Public Member Functions
ScriptAction (ScriptMapType scriptType, Map *_map, ObjectGuid _sourceGuid, ObjectGuid _targetGuid, ObjectGuid _ownerGuid, std::shared_ptr< ScriptInfo > _script)
bool HandleScriptStep ()
Handle one Script Step.
bool ExecuteDbscriptCommand (WorldObject *pSource, WorldObject *pTarget, Object *pSourceOrItem)
const char * GetTableName () const
uint32 GetId () const
ObjectGuid GetSourceGuid () const
ObjectGuid GetTargetGuid () const
ObjectGuid GetOwnerGuid () const
bool IsSameScript (const char *table, uint32 id, ObjectGuid sourceGuid, ObjectGuid targetGuid, ObjectGuid ownerGuid) const
Private Member Functions
bool GetScriptCommandObject (const ObjectGuid guid, bool includeItem, Object *&resultObject) const
Helper function to get Object source or target for Script-Command returns false iff an error happened.
bool GetScriptProcessTargets (WorldObject *originalSource, WorldObject *originalTarget, std::vector< WorldObject * > &finalSources, std::vector< WorldObject * > &finalTargets) const
Select source and target for a script command Returns false if an error happened.
bool LogIfNotCreature (WorldObject *pWorldObject) const
Helper to log error information.
bool LogIfNotUnit (WorldObject *pWorldObject) const
bool LogIfNotGameObject (WorldObject *pWorldObject) const
bool LogIfNotPlayer (WorldObject *pWorldObject) const
Player * GetPlayerTargetOrSourceAndLog (WorldObject *pSource, WorldObject *pTarget) const
Helper to get a player if possible (target preferred)
Private Attributes
ScriptMapType m_scriptType
const char * m_table
Map * m_map
ObjectGuid m_sourceGuid
ObjectGuid m_targetGuid
ObjectGuid m_ownerGuid
std::shared_ptr< ScriptInfo > m_script
Detailed Description
Definition at line 608 of file ScriptMgr.h.
Constructor & Destructor Documentation
ScriptAction()
ScriptAction::ScriptAction (ScriptMapType scriptType, Map * _map, ObjectGuid _sourceGuid, ObjectGuid _targetGuid, ObjectGuid _ownerGuid, std::shared_ptr< ScriptInfo > _script)
Definition at line 1655 of file ScriptMgr.cpp.
Member Function Documentation
ExecuteDbscriptCommand()
bool ScriptAction::ExecuteDbscriptCommand (WorldObject * pSource, WorldObject * pTarget, Object * pSourceOrItem)
Definition at line 1723 of file ScriptMgr.cpp.
References Player::ActivateTaxiPathTo(), Unit::AI(), Creature::AI(), Player::AreaExploredOrEventHappens(), UnitAI::AttackClosestEnemy(), UnitAI::AttackStart(), Unit::CanAttackNow(), Creature::ChooseDisplayId(), MotionMaster::Clear(), CONDITION_FROM_DBSCRIPTS, TempSpawnSettings::dbscriptTarget, Player::DestroyItemCount(), DETAIL_FILTER_LOG, DoDisplayText(), EFFECT_MOTION_TYPE, CreatureInfo::EquipmentTemplateId, Player::FailQuest(), FALL_MOTION_TYPE, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGNODE, WorldObject::GetAreaId(), WorldObject::GetContactPoint(), Map::GetCreature(), Creature::GetCreatureGroup(), CreatureGroup::GetCreatureGroup(), Creature::GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), PoolGroup< T >::GetEqualChanced(), PoolGroup< T >::GetExplicitlyChanced(), CreatureGroup::GetFormationData(), Unit::GetFormationSlot(), Map::GetGameObject(), GameObject::GetGoState(), GameObject::GetGoType(), Player::GetGroup(), SpawnGroup::GetGroupId(), Object::GetGUIDLow(), Object::GetGuidStr(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Unit::GetMotionMaster(), Object::GetObjectGuid(), CreatureData::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), GetPlayerTargetOrSourceAndLog(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetQuestStatus(), WorldObject::GetRandomPoint(), Creature::GetRespawnCoord(), Creature::GetRespawnPosition(), SpawnManager::GetSpawnGroup(), Map::GetSpawnManager(), Unit::GetSpeed(), Object::GetTypeId(), Object::GetValuesCount(), Map::GetVariableManager(), WorldObject::GetZoneId(), GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_READY, GO_STATE_READY, SpellEntry::HasAttribute(), Object::HasFlag(), HIGHGUID_GAMEOBJECT, GameObjectData::id, IDLE_MOTION_TYPE, Unit::InterruptSpell(), Object::IsCreature(), Object::IsGameObject(), Unit::IsInCombat(), Object::IsPlayer(), GameObject::IsSpawned(), GameObject::IsSpawnedByDefault(), Object::isType(), Object::IsUnit(), Unit::IsWalking(), WorldObject::IsWithinDist3d(), WorldObject::IsWithinDistInMap(), Player::KilledMonsterCredit(), LINEAR_WP_MOTION_TYPE, Creature::LoadEquipment(), LOG_FILTER_DB_SCRIPT, LogIfNotCreature(), LogIfNotGameObject(), LogIfNotPlayer(), LogIfNotUnit(), SQLStorage::LookupEntry(), m_map, M_PI_F, m_script, m_table, MAIL_CHECK_MASK_HAS_BODY, MAIL_CREATURE, MAX_TEXT_ID, Unit::Mount(), MOVE_RUN, MotionMaster::MoveFall(), CreatureGroup::MoveHome(), MotionMaster::MoveIdle(), MotionMaster::MoveJumpFacingVerticalSpeed(), MotionMaster::MoveLinearWP(), MotionMaster::MovePath(), MotionMaster::MovePathAndJumpVerticalSpeed(), MotionMaster::MovePoint(), MotionMaster::MoveRandomAroundPoint(), MotionMaster::MoveWaypoint(), GroupReference::next(), OBJECT_FIELD_ENTRY, PATH_FROM_WAYPOINT_PATH, PATH_MOTION_TYPE, PATH_NO_PATH, PLAY_AREA, PLAY_SET, PLAY_TARGET, PLAY_ZONE, WorldObject::PlayDirectSound(), Map::PlayDirectSoundToMap(), WorldObject::PlayDistanceSound(), PLAYER_FLAGS, PLAYER_FLAGS_XP_USER_DISABLED, WorldObject::PlayMusic(), QUEST_STATUS_INCOMPLETE, RANDOM_MOTION_TYPE, UnitAI::ReceiveAIEvent(), GameObject::Refresh(), Object::RemoveByteFlag(), Object::RemoveFlag(), GameObject::ResetDoorOrButton(), GameObject::Respawn(), Player::RewardPlayerAndGroupAtEventCredit(), SCRIPT_COMMAND_ACTIVATE_OBJECT, SCRIPT_COMMAND_ATTACK_START, SCRIPT_COMMAND_CAST_CUSTOM_SPELL, SCRIPT_COMMAND_CAST_SPELL, SCRIPT_COMMAND_CLOSE_DOOR, SCRIPT_COMMAND_CREATE_ITEM, SCRIPT_COMMAND_DESPAWN_GO, SCRIPT_COMMAND_DESPAWN_SELF, SCRIPT_COMMAND_EMOTE, SCRIPT_COMMAND_FIELD_SET, SCRIPT_COMMAND_FLAG_REMOVE, SCRIPT_COMMAND_FLAG_SET, SCRIPT_COMMAND_GO_LOCK_STATE, SCRIPT_COMMAND_INTERRUPT_SPELL, SCRIPT_COMMAND_KILL_CREDIT, SCRIPT_COMMAND_MODIFY_NPC_FLAGS, SCRIPT_COMMAND_MODIFY_UNIT_FLAGS, SCRIPT_COMMAND_MORPH_TO_ENTRY_OR_MODEL, SCRIPT_COMMAND_MOUNT_TO_ENTRY_OR_MODEL, SCRIPT_COMMAND_MOVE_DYNAMIC, SCRIPT_COMMAND_MOVE_TO, SCRIPT_COMMAND_MOVEMENT, SCRIPT_COMMAND_OPEN_DOOR, SCRIPT_COMMAND_PAUSE_WAYPOINTS, SCRIPT_COMMAND_PLAY_MOVIE, SCRIPT_COMMAND_PLAY_SOUND, SCRIPT_COMMAND_QUEST_EXPLORED, SCRIPT_COMMAND_REMOVE_AURA, SCRIPT_COMMAND_RESET_GO, SCRIPT_COMMAND_RESPAWN, SCRIPT_COMMAND_RESPAWN_GAMEOBJECT, SCRIPT_COMMAND_SEND_AI_EVENT, SCRIPT_COMMAND_SEND_MAIL, SCRIPT_COMMAND_SEND_TAXI_PATH, SCRIPT_COMMAND_SET_ACTIVEOBJECT, SCRIPT_COMMAND_SET_DATA_64, SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS, SCRIPT_COMMAND_SET_FACING, SCRIPT_COMMAND_SET_FACTION, SCRIPT_COMMAND_SET_GOSSIP_MENU, SCRIPT_COMMAND_SET_HOVER, SCRIPT_COMMAND_SET_RUN, SCRIPT_COMMAND_SET_SHEATHE, SCRIPT_COMMAND_SET_STRING_ID, SCRIPT_COMMAND_SET_WORLDSTATE, SCRIPT_COMMAND_SPAWN_GROUP, SCRIPT_COMMAND_STAND_STATE, SCRIPT_COMMAND_START_RELAY_SCRIPT, SCRIPT_COMMAND_TALK, SCRIPT_COMMAND_TELEPORT_TO, SCRIPT_COMMAND_TEMP_SPAWN_CREATURE, SCRIPT_COMMAND_TERMINATE_COND, SCRIPT_COMMAND_TERMINATE_SCRIPT, SCRIPT_COMMAND_UPDATE_TEMPLATE, SCRIPT_COMMAND_XP_USER, SCRIPT_COMMAND_ZONE_PULSE, SCRIPT_FLAG_BUDDY_BY_GUID, SCRIPT_FLAG_COMMAND_ADDITIONAL, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), UnitAI::SendAIEvent(), WorldObject::SendGameObjectCustomAnim(), MailDraft::SendMailTo(), Player::SendMovieStart(), Player::SendNewItem(), WorldObject::SetActiveObjectState(), Creature::SetBaseRunSpeed(), Object::SetByteFlag(), InstanceData::SetData64(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Object::SetFlag(), CreatureGroup::SetFormationData(), Creature::SetInCombatWithZone(), GameObject::SetLootState(), MailDraft::SetMoney(), FormationData::SetOptions(), GameObject::SetRespawnTime(), FormationData::SetSpread(), WorldObject::SetStringId(), Object::SetUInt32Value(), WorldStateVariableManager::SetVariable(), Creature::SetVirtualItem(), Creature::SetWalk(), sLog, sObjectMgr, SPAWN_GROUP_FORMATION_TYPE_COUNT, TempSpawnSettings::spawnDataEntry, CreatureInfo::SpeedRun, SPELL_ATTR_EX_EXCLUDE_CASTER, sPoolMgr, sScriptMgr, sSpellTemplate, Unit::StopMoving(), Player::StoreNewItemInInventorySlot(), WorldObject::SummonCreature(), FormationData::SwitchFormation(), Player::TeleportTo(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_DO_NOT_PROC, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, TYPEMASK_CREATURE_OR_GAMEOBJECT, TYPEMASK_UNIT, UNIT_BYTE1_FLAG_FLY_ANIM, UNIT_BYTES_1_OFFSET_MISC_FLAGS, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_NPC_FLAGS, Unit::Unmount(), Unit::UpdateAllowedPositionZ(), Creature::UpdateEntry(), Unit::UpdateSpeed(), urand(), GameObject::Use(), GameObject::UseOpenableObject(), VIRTUAL_ITEM_SLOT_0, VIRTUAL_ITEM_SLOT_1, VIRTUAL_ITEM_SLOT_2, Cell::VisitGridObjects(), and WAYPOINT_MOTION_TYPE.
Referenced by HandleScriptStep().
GetId()
uint32 ScriptAction::GetId () const inline
Definition at line 617 of file ScriptMgr.h.
References m_script.
Referenced by IsSameScript().
GetOwnerGuid()
ObjectGuid ScriptAction::GetOwnerGuid () const inline
Definition at line 620 of file ScriptMgr.h.
References m_ownerGuid.
GetPlayerTargetOrSourceAndLog()
Player * ScriptAction::GetPlayerTargetOrSourceAndLog (WorldObject * pSource, WorldObject * pTarget) const private
Helper to get a player if possible (target preferred)
Definition at line 1644 of file ScriptMgr.cpp.
References Object::GetTypeId(), m_script, m_table, sLog, and TYPEID_PLAYER.
Referenced by ExecuteDbscriptCommand().
GetScriptCommandObject()
bool ScriptAction::GetScriptCommandObject (const ObjectGuid guid, bool includeItem, Object *& resultObject) const private
Helper function to get Object source or target for Script-Command returns false iff an error happened.
Definition at line 1280 of file ScriptMgr.cpp.
References HashMapHolder< T >::Find(), Map::GetCreature(), Map::GetGameObject(), ObjectGuid::GetHigh(), Map::GetPet(), Map::GetPlayer(), ObjectGuid::GetString(), Map::GetTransport(), HIGHGUID_CORPSE, HIGHGUID_GAMEOBJECT, HIGHGUID_ITEM, HIGHGUID_MO_TRANSPORT, HIGHGUID_PET, HIGHGUID_PLAYER, HIGHGUID_UNIT, HIGHGUID_VEHICLE, Object::IsInWorld(), m_map, m_ownerGuid, m_script, m_table, and sLog.
Referenced by HandleScriptStep().
GetScriptProcessTargets()
bool ScriptAction::GetScriptProcessTargets (WorldObject * originalSource, WorldObject * originalTarget, std::vector< WorldObject * > & finalSources, std::vector< WorldObject * > & finalTargets) const private
Select source and target for a script command Returns false if an error happened.
Definition at line 1332 of file ScriptMgr.cpp.
References SpawnGroupEntry::DbGuids, DETAIL_FILTER_LOG, DIST_CALC_NONE, Map::GetCreature(), WorldObject::GetDistance(), Object::GetEntry(), PoolGroup< T >::GetEqualChanced(), PoolGroup< T >::GetExplicitlyChanced(), Map::GetGameObject(), Object::GetGuidStr(), Map::GetId(), Map::GetMapDataContainer(), CreatureData::GetObjectGuid(), MapDataContainer::GetSpawnGroup(), Object::GetTypeId(), Map::GetWorldObjects(), LOG_FILTER_DB_SCRIPT, m_map, m_script, m_table, SCRIPT_COMMAND_TERMINATE_SCRIPT, SCRIPT_FLAG_ALL_ELIGIBLE_BUDDIES, SCRIPT_FLAG_BUDDY_AS_TARGET, SCRIPT_FLAG_BUDDY_BY_GUID, SCRIPT_FLAG_BUDDY_BY_POOL, SCRIPT_FLAG_BUDDY_BY_SPAWN_GROUP, SCRIPT_FLAG_BUDDY_BY_STRING_ID, SCRIPT_FLAG_BUDDY_IS_PET, SCRIPT_FLAG_REVERSE_DIRECTION, SCRIPT_FLAG_SOURCE_TARGETS_SELF, sLog, sObjectMgr, SPAWN_GROUP_CREATURE, sPoolMgr, SpawnGroupEntry::Type, TYPEID_PLAYER, Cell::VisitAllObjects(), Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
Referenced by HandleScriptStep().
GetSourceGuid()
ObjectGuid ScriptAction::GetSourceGuid () const inline
Definition at line 618 of file ScriptMgr.h.
References m_sourceGuid.
GetTableName()
const char* ScriptAction::GetTableName () const inline
Definition at line 616 of file ScriptMgr.h.
References m_table.
GetTargetGuid()
ObjectGuid ScriptAction::GetTargetGuid () const inline
Definition at line 619 of file ScriptMgr.h.
References m_targetGuid.
HandleScriptStep()
bool ScriptAction::HandleScriptStep ()
Handle one Script Step.
Definition at line 1663 of file ScriptMgr.cpp.
References DETAIL_FILTER_LOG, ExecuteDbscriptCommand(), GetScriptCommandObject(), GetScriptProcessTargets(), ObjectGuid::GetString(), Object::isType(), LOG_FILTER_DB_SCRIPT, m_script, m_sourceGuid, m_table, m_targetGuid, TYPEMASK_ITEM, and TYPEMASK_WORLDOBJECT.
Referenced by Map::ScriptCommandStart(), and Map::ScriptsStart().
IsSameScript()
bool ScriptAction::IsSameScript (const char * table, uint32 id, ObjectGuid sourceGuid, ObjectGuid targetGuid, ObjectGuid ownerGuid) const inline
Definition at line 622 of file ScriptMgr.h.
References GetId(), m_ownerGuid, m_sourceGuid, m_table, and m_targetGuid.
LogIfNotCreature()
bool ScriptAction::LogIfNotCreature (WorldObject * pWorldObject) const private
Helper to log error information.
Definition at line 1606 of file ScriptMgr.cpp.
References Object::GetTypeId(), m_script, m_table, sLog, and TYPEID_UNIT.
Referenced by ExecuteDbscriptCommand().
LogIfNotGameObject()
bool ScriptAction::LogIfNotGameObject (WorldObject * pWorldObject) const private
Definition at line 1624 of file ScriptMgr.cpp.
References Object::GetTypeId(), m_script, m_table, sLog, and TYPEID_GAMEOBJECT.
Referenced by ExecuteDbscriptCommand().
LogIfNotPlayer()
bool ScriptAction::LogIfNotPlayer (WorldObject * pWorldObject) const private
Definition at line 1633 of file ScriptMgr.cpp.
References Object::GetTypeId(), m_script, m_table, sLog, and TYPEID_PLAYER.
Referenced by ExecuteDbscriptCommand().
LogIfNotUnit()
bool ScriptAction::LogIfNotUnit (WorldObject * pWorldObject) const private
Definition at line 1615 of file ScriptMgr.cpp.
References Object::isType(), m_script, m_table, sLog, and TYPEMASK_UNIT.
Referenced by ExecuteDbscriptCommand().
Field Documentation
m_map
Map* ScriptAction::m_map private
Definition at line 633 of file ScriptMgr.h.
Referenced by ExecuteDbscriptCommand(), GetScriptCommandObject(), and GetScriptProcessTargets().
m_ownerGuid
ObjectGuid ScriptAction::m_ownerGuid private
Definition at line 636 of file ScriptMgr.h.
Referenced by GetOwnerGuid(), GetScriptCommandObject(), and IsSameScript().
m_script
std::shared_ptr<ScriptInfo> ScriptAction::m_script private
Definition at line 637 of file ScriptMgr.h.
Referenced by ExecuteDbscriptCommand(), GetId(), GetPlayerTargetOrSourceAndLog(), GetScriptCommandObject(), GetScriptProcessTargets(), HandleScriptStep(), LogIfNotCreature(), LogIfNotGameObject(), LogIfNotPlayer(), and LogIfNotUnit().
m_scriptType
ScriptMapType ScriptAction::m_scriptType private
Definition at line 631 of file ScriptMgr.h.
m_sourceGuid
ObjectGuid ScriptAction::m_sourceGuid private
Definition at line 634 of file ScriptMgr.h.
Referenced by GetSourceGuid(), HandleScriptStep(), and IsSameScript().
m_table
const char* ScriptAction::m_table private
Definition at line 632 of file ScriptMgr.h.
Referenced by ExecuteDbscriptCommand(), GetPlayerTargetOrSourceAndLog(), GetScriptCommandObject(), GetScriptProcessTargets(), GetTableName(), HandleScriptStep(), IsSameScript(), LogIfNotCreature(), LogIfNotGameObject(), LogIfNotPlayer(), and LogIfNotUnit().
m_targetGuid
ObjectGuid ScriptAction::m_targetGuid private
Definition at line 635 of file ScriptMgr.h.
Referenced by GetTargetGuid(), HandleScriptStep(), and IsSameScript().
The documentation for this class was generated from the following files:
ScriptMgr.h
ScriptMgr.cpp