CMaNGOS_WoTLK: instance_sethekk_halls Class Reference
instance_sethekk_halls Class Reference
#include <sethekk_halls.h>
Public Member Functions
instance_sethekk_halls (Map *pMap)
~instance_sethekk_halls ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void StartAnzuIntro (Player *player)
void FinishAnzuIntro ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_anzuTimer
uint32 m_anzuStage
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 42 of file sethekk_halls.h.
Constructor & Destructor Documentation
instance_sethekk_halls()
instance_sethekk_halls::instance_sethekk_halls (Map * pMap)
Definition at line 28 of file sethekk_halls.cpp.
References Initialize().
~instance_sethekk_halls()
instance_sethekk_halls::~instance_sethekk_halls () inline
Definition at line 46 of file sethekk_halls.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_sethekk_halls::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 280 of file sethekk_halls.cpp.
References ACHIEV_CRITA_TURKEY_TIME, Player::HasItemOrGemWithIdEquipped(), ITEM_PILGRIMS_ATTIRE, ITEM_PILGRIMS_DRESS, ITEM_PILGRIMS_HAT, and ITEM_PILGRIMS_ROBE.
FinishAnzuIntro()
void instance_sethekk_halls::FinishAnzuIntro ()
Definition at line 199 of file sethekk_halls.cpp.
References DAY, Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_JUST_DEACTIVATED, GO_MOONSTONE, GO_RAVENS_CLAW, GO_TEST_RIFT, InstanceData::instance, NPC_ANZU, NPC_INVIS_RAVEN_GOD_CASTER, NPC_INVIS_RAVEN_GOD_PORTAL, NPC_INVIS_RAVEN_GOD_TARGET, GameObject::SetLootState(), GameObject::SetRespawnTime(), WorldObject::SummonCreature(), and TEMPSPAWN_MANUAL_DESPAWN.
Referenced by Update().
GetData()
uint32 instance_sethekk_halls::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 117 of file sethekk_halls.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Initialize()
void instance_sethekk_halls::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 32 of file sethekk_halls.cpp.
References m_auiEncounter.
Referenced by instance_sethekk_halls().
Load()
void instance_sethekk_halls::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 125 of file sethekk_halls.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_sethekk_halls::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 37 of file sethekk_halls.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_ANZU, NPC_INVIS_RAVEN_GOD_CASTER, NPC_INVIS_RAVEN_GOD_PORTAL, and NPC_INVIS_RAVEN_GOD_TARGET.
OnObjectCreate()
void instance_sethekk_halls::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 52 of file sethekk_halls.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_FLAG_INTERACT_COND, GO_FLAG_NO_INTERACT, GO_IKISS_CHEST, GO_IKISS_SWING_DOOR, GO_MOONSTONE, GO_RAVENS_CLAW, GO_STATE_ACTIVE, GO_TEST_RIFT, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), and TYPE_IKISS.
Save()
const char* instance_sethekk_halls::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 58 of file sethekk_halls.h.
References m_strInstData.
SetData()
void instance_sethekk_halls::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 75 of file sethekk_halls.cpp.
References DAY, DONE, ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, ScriptedInstance::GetSingleGameObjectFromStorage(), GO_FLAG_INTERACT_COND, GO_FLAG_NO_INTERACT, GO_IKISS_CHEST, GO_IKISS_SWING_DOOR, GO_RAVENS_CLAW, m_auiEncounter, m_strInstData, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_ANZU, TYPE_IKISS, and TYPE_SYTH.
Referenced by boss_anzuAI::Aggro(), boss_anzuAI::JustDied(), and boss_anzuAI::JustReachedHome().
StartAnzuIntro()
void instance_sethekk_halls::StartAnzuIntro (Player * player)
Definition at line 176 of file sethekk_halls.cpp.
References Unit::CastSpell(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_MOONSTONE, GO_READY, GO_TEST_RIFT, IN_MILLISECONDS, m_anzuStage, m_anzuTimer, MINUTE, NPC_INVIS_RAVEN_GOD_CASTER, NPC_INVIS_RAVEN_GOD_PORTAL, NPC_INVIS_RAVEN_GOD_TARGET, GameObject::Refresh(), GameObject::SetLootState(), GameObject::SetRespawnTime(), SPELL_OTHERWORLDLY_PORTAL, SPELL_PURPLE_BANISH_STATE, SPELL_RAVEN_GOD_SUMMON_BEAMS, WorldObject::SummonCreature(), TEMPSPAWN_MANUAL_DESPAWN, TRIGGER_COUNT, TRIGGERED_NONE, and triggerPositions.
Update()
void instance_sethekk_halls::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 220 of file sethekk_halls.cpp.
References Unit::CastSpell(), FinishAnzuIntro(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), m_anzuStage, m_anzuTimer, MotionMaster::MovePoint(), NPC_INVIS_RAVEN_GOD_TARGET, SPELL_RED_LIGHTNING_BOLT, SPELL_ULTRIS_DESTROYED, and TRIGGERED_NONE.
Field Documentation
m_anzuStage
uint32 instance_sethekk_halls::m_anzuStage private
Definition at line 70 of file sethekk_halls.h.
Referenced by StartAnzuIntro(), and Update().
m_anzuTimer
uint32 instance_sethekk_halls::m_anzuTimer private
Definition at line 69 of file sethekk_halls.h.
Referenced by StartAnzuIntro(), and Update().
m_auiEncounter
uint32 instance_sethekk_halls::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 66 of file sethekk_halls.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_strInstData
std::string instance_sethekk_halls::m_strInstData private
Definition at line 67 of file sethekk_halls.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
sethekk_halls.h
sethekk_halls.cpp