CMaNGOS_WoTLK: SpawnedPoolData Class Reference
SpawnedPoolData Class Reference
#include <PoolManager.h>
Public Member Functions
SpawnedPoolData ()
template<typename T >
bool IsSpawnedObject (uint32 db_guid_or_pool_id) const
uint32 GetSpawnedObjects (uint32 pool_id) const
template<typename T >
void AddSpawn (uint32 db_guid_or_pool_id, uint32 pool_id)
template<typename T >
void RemoveSpawn (uint32 db_guid_or_pool_id, uint32 pool_id)
bool IsInitialized () const
void SetInitialized ()
SpawnedPoolObjects const & GetSpawnedCreatures () const
SpawnedPoolObjects const & GetSpawnedGameobjects () const
SpawnedPoolPools const & GetSpawnedPools () const
template<>
bool IsSpawnedObject (uint32 db_guid) const
template<>
bool IsSpawnedObject (uint32 db_guid) const
template<>
bool IsSpawnedObject (uint32 sub_pool_id) const
template<>
void AddSpawn (uint32 db_guid, uint32 pool_id)
template<>
void AddSpawn (uint32 db_guid, uint32 pool_id)
template<>
void AddSpawn (uint32 sub_pool_id, uint32 pool_id)
template<>
void RemoveSpawn (uint32 db_guid, uint32 pool_id)
template<>
void RemoveSpawn (uint32 db_guid, uint32 pool_id)
template<>
void RemoveSpawn (uint32 sub_pool_id, uint32 pool_id)
Private Attributes
SpawnedPoolObjects mSpawnedCreatures
SpawnedPoolObjects mSpawnedGameobjects
SpawnedPoolPools mSpawnedPools
bool m_isInitialized
Detailed Description
Definition at line 67 of file PoolManager.h.
Constructor & Destructor Documentation
SpawnedPoolData()
SpawnedPoolData::SpawnedPoolData () inline
Definition at line 70 of file PoolManager.h.
Member Function Documentation
AddSpawn() [1/4]
template<> void SpawnedPoolData::AddSpawn (uint32 db_guid, uint32 pool_id)
Definition at line 63 of file PoolManager.cpp.
References mSpawnedCreatures, and mSpawnedPools.
AddSpawn() [2/4]
template<> void SpawnedPoolData::AddSpawn (uint32 db_guid, uint32 pool_id)
Definition at line 70 of file PoolManager.cpp.
References mSpawnedGameobjects, and mSpawnedPools.
AddSpawn() [3/4]
template<typename T > void SpawnedPoolData::AddSpawn (uint32 db_guid_or_pool_id, uint32 pool_id)
Referenced by PoolGroup< T >::SpawnObject().
AddSpawn() [4/4]
template<> void SpawnedPoolData::AddSpawn (uint32 sub_pool_id, uint32 pool_id)
Definition at line 77 of file PoolManager.cpp.
References mSpawnedPools.
GetSpawnedCreatures()
SpawnedPoolObjects const& SpawnedPoolData::GetSpawnedCreatures () const inline
Definition at line 86 of file PoolManager.h.
References mSpawnedCreatures.
Referenced by ChatHandler::HandlePoolInfoCommand(), and ChatHandler::HandlePoolSpawnsCommand().
GetSpawnedGameobjects()
SpawnedPoolObjects const& SpawnedPoolData::GetSpawnedGameobjects () const inline
Definition at line 87 of file PoolManager.h.
References mSpawnedGameobjects.
Referenced by ChatHandler::HandlePoolInfoCommand(), and ChatHandler::HandlePoolSpawnsCommand().
GetSpawnedObjects()
uint32 SpawnedPoolData::GetSpawnedObjects (uint32 pool_id) const
Definition at line 35 of file PoolManager.cpp.
References mSpawnedPools.
Referenced by PoolGroup< T >::SpawnObject().
GetSpawnedPools()
SpawnedPoolPools const& SpawnedPoolData::GetSpawnedPools () const inline
Definition at line 88 of file PoolManager.h.
References mSpawnedPools.
Referenced by ChatHandler::HandlePoolInfoCommand().
IsInitialized()
bool SpawnedPoolData::IsInitialized () const inline
Definition at line 83 of file PoolManager.h.
References m_isInitialized.
IsSpawnedObject() [1/4]
template<> bool SpawnedPoolData::IsSpawnedObject (uint32 db_guid) const
Definition at line 43 of file PoolManager.cpp.
References mSpawnedCreatures.
IsSpawnedObject() [2/4]
template<> bool SpawnedPoolData::IsSpawnedObject (uint32 db_guid) const
Definition at line 50 of file PoolManager.cpp.
References mSpawnedGameobjects.
IsSpawnedObject() [3/4]
template<typename T > bool SpawnedPoolData::IsSpawnedObject (uint32 db_guid_or_pool_id) const
Referenced by PoolGroup< T >::DespawnObject(), MapPersistentState::IsSpawnedPoolObject(), PoolGroup< T >::RollOne(), and PoolGroup< T >::SpawnObject().
IsSpawnedObject() [4/4]
template<> bool SpawnedPoolData::IsSpawnedObject (uint32 sub_pool_id) const
Definition at line 57 of file PoolManager.cpp.
References mSpawnedPools.
RemoveSpawn() [1/4]
template<> void SpawnedPoolData::RemoveSpawn (uint32 db_guid, uint32 pool_id)
Definition at line 84 of file PoolManager.cpp.
References mSpawnedCreatures, and mSpawnedPools.
RemoveSpawn() [2/4]
template<> void SpawnedPoolData::RemoveSpawn (uint32 db_guid, uint32 pool_id)
Definition at line 93 of file PoolManager.cpp.
References mSpawnedGameobjects, and mSpawnedPools.
RemoveSpawn() [3/4]
template<typename T > void SpawnedPoolData::RemoveSpawn (uint32 db_guid_or_pool_id, uint32 pool_id)
Referenced by PoolGroup< T >::DespawnObject().
RemoveSpawn() [4/4]
template<> void SpawnedPoolData::RemoveSpawn (uint32 sub_pool_id, uint32 pool_id)
Definition at line 102 of file PoolManager.cpp.
References mSpawnedPools.
SetInitialized()
void SpawnedPoolData::SetInitialized () inline
Definition at line 84 of file PoolManager.h.
References m_isInitialized.
Referenced by MapPersistentState::InitPools().
Field Documentation
m_isInitialized
bool SpawnedPoolData::m_isInitialized private
Definition at line 93 of file PoolManager.h.
Referenced by IsInitialized(), and SetInitialized().
mSpawnedCreatures
SpawnedPoolObjects SpawnedPoolData::mSpawnedCreatures private
Definition at line 90 of file PoolManager.h.
Referenced by AddSpawn(), GetSpawnedCreatures(), IsSpawnedObject(), and RemoveSpawn().
mSpawnedGameobjects
SpawnedPoolObjects SpawnedPoolData::mSpawnedGameobjects private
Definition at line 91 of file PoolManager.h.
Referenced by AddSpawn(), GetSpawnedGameobjects(), IsSpawnedObject(), and RemoveSpawn().
mSpawnedPools
SpawnedPoolPools SpawnedPoolData::mSpawnedPools private
Definition at line 92 of file PoolManager.h.
Referenced by AddSpawn(), GetSpawnedObjects(), GetSpawnedPools(), IsSpawnedObject(), and RemoveSpawn().
The documentation for this class was generated from the following files:
PoolManager.h
PoolManager.cpp