CMaNGOS_WoTLK: metric::metric Class Reference
metric::metric Class Reference
#include <Metric.h>
Public Member Functions
metric ()
~metric ()
void initialize ()
void reload_config ()
void report (std::string measurement, std::string key, boost::any value, std::map< std::string, std::string > tags={})
void report (std::string measurement, std::map< std::string, boost::any > fields, std::map< std::string, std::string > tags={})
Static Public Member Functions
static metric & instance ()
Private Member Functions
void schedule_timer ()
void prepare_send (const boost::system::error_code &ec)
void send ()
Private Attributes
boost::asio::io_service m_queueService
boost::asio::io_service m_writeService
std::unique_ptr< boost::asio::deadline_timer > m_sendTimer
std::unique_ptr< boost::asio::io_service::work > m_queueServiceWork
std::unique_ptr< boost::asio::io_service::work > m_writeServiceWork
std::thread m_queueServiceThread
std::thread m_writeServiceThread
bool m_enabled
MetricConnectionInfo m_connectionInfo
std::mutex m_queueWriteLock
std::vector< std::unique_ptr< Measurement > > m_measurementQueue
Detailed Description
Definition at line 108 of file Metric.h.
Constructor & Destructor Documentation
metric()
metric::metric::metric ()
Definition at line 77 of file Metric.cpp.
~metric()
metric::metric::~metric ()
Definition at line 82 of file Metric.cpp.
Member Function Documentation
initialize()
void metric::metric::initialize ()
Definition at line 98 of file Metric.cpp.
References sConfig.
instance()
metric::metric & metric::metric::instance () static
Definition at line 127 of file Metric.cpp.
Referenced by ChatHandler::HandleReloadConfigCommand().
prepare_send()
void metric::metric::prepare_send (const boost::system::error_code & ec) private
Definition at line 181 of file Metric.cpp.
References sLog.
Referenced by schedule_timer().
reload_config()
void metric::metric::reload_config ()
Definition at line 133 of file Metric.cpp.
References sConfig.
Referenced by ChatHandler::HandleReloadConfigCommand().
report() [1/2]
void metric::metric::report (std::string measurement, std::map< std::string, boost::any > fields, std::map< std::string, std::string > tags = {})
Definition at line 158 of file Metric.cpp.
report() [2/2]
void metric::metric::report (std::string measurement, std::string key, boost::any value, std::map< std::string, std::string > tags = {})
Definition at line 153 of file Metric.cpp.
schedule_timer()
void metric::metric::schedule_timer () private
Definition at line 170 of file Metric.cpp.
References prepare_send().
send()
void metric::metric::send () private
Definition at line 195 of file Metric.cpp.
References sLog.
Field Documentation
m_connectionInfo
MetricConnectionInfo metric::metric::m_connectionInfo private
Definition at line 133 of file Metric.h.
m_enabled
bool metric::metric::m_enabled private
Definition at line 132 of file Metric.h.
m_measurementQueue
std::vector<std::unique_ptr<Measurement> > metric::metric::m_measurementQueue private
Definition at line 136 of file Metric.h.
m_queueService
boost::asio::io_service metric::metric::m_queueService private
Definition at line 123 of file Metric.h.
m_queueServiceThread
std::thread metric::metric::m_queueServiceThread private
Definition at line 129 of file Metric.h.
m_queueServiceWork
std::unique_ptr<boost::asio::io_service::work> metric::metric::m_queueServiceWork private
Definition at line 127 of file Metric.h.
m_queueWriteLock
std::mutex metric::metric::m_queueWriteLock private
Definition at line 135 of file Metric.h.
m_sendTimer
std::unique_ptr<boost::asio::deadline_timer> metric::metric::m_sendTimer private
Definition at line 126 of file Metric.h.
m_writeService
boost::asio::io_service metric::metric::m_writeService private
Definition at line 124 of file Metric.h.
m_writeServiceThread
std::thread metric::metric::m_writeServiceThread private
Definition at line 130 of file Metric.h.
m_writeServiceWork
std::unique_ptr<boost::asio::io_service::work> metric::metric::m_writeServiceWork private
Definition at line 128 of file Metric.h.
The documentation for this class was generated from the following files:
Metric.h
Metric.cpp