CMaNGOS_WoTLK: WorldStateExpressionMgr Class Reference
WorldStateExpressionMgr Class Reference
#include <WorldStateExpression.h>
Public Member Functions
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > Load ()
bool Meets (Map const *map, int32 Id)
bool Exists (int32 Id)
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > Get ()
Private Attributes
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > m_expressions
Detailed Description
Definition at line 97 of file WorldStateExpression.h.
Member Function Documentation
Exists()
bool WorldStateExpressionMgr::Exists (int32 Id)
Definition at line 464 of file WorldStateExpression.cpp.
References m_expressions.
Referenced by CombatConditionMgr::Load().
Get()
std::shared_ptr<std::map<int32, WorldStateExpressionEntry> > WorldStateExpressionMgr::Get () inline
Definition at line 106 of file WorldStateExpression.h.
References m_expressions.
Load()
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > WorldStateExpressionMgr::Load ()
Definition at line 385 of file WorldStateExpression.cpp.
References MaNGOS::Count(), WorldStateExpressionEntry::Expression, Field::GetCppString(), Field::GetUInt32(), WorldStateExpressionEntry::Id, m_expressions, Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
Meets()
bool WorldStateExpressionMgr::Meets (Map const * map, int32 Id)
Definition at line 422 of file WorldStateExpression.cpp.
References AND, ByteBuffer::empty(), EvalRelOp(), WorldStateExpressionEntry::Expression, Map::GetMapDataContainer(), MapDataContainer::GetWorldStateExpressions(), HexToBytes(), NONE, OR, ByteBuffer::read(), ByteBuffer::rpos(), ByteBuffer::size(), and XOR.
Referenced by CombatConditionMgr::Meets().
Field Documentation
m_expressions
std::shared_ptr<std::map<int32, WorldStateExpressionEntry> > WorldStateExpressionMgr::m_expressions private
Definition at line 108 of file WorldStateExpression.h.
Referenced by Exists(), Get(), and Load().
The documentation for this class was generated from the following files:
WorldStateExpression.h
WorldStateExpression.cpp