CMaNGOS_WoTLK: BattleGround Class Reference
BattleGround Class Reference
#include <BattleGround.h>
Data Structures
struct EventObjects
Public Types
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Public Member Functions
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void Update (uint32 diff)
Update method.
virtual void Reset ()
Method that is called when no players remains in battleground.
virtual void StartingEventCloseDoors ()
virtual void StartingEventOpenDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
virtual void EndBattleGround (Team)
Method that ends battleground.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
virtual void UpdatePlayerScore (Player *, uint32, uint32)
Method that updates player score.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual bool HandleAreaTrigger (Player *, uint32)
virtual void HandleKillPlayer (Player *, Player *)
Method that handles killing players.
virtual void HandleKillUnit (Creature *, Player *)
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectCreate (GameObject *)
virtual void HandlePlayerDroppedFlag (Player *)
virtual void HandlePlayerClickedOnFlag (Player *, GameObject *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
virtual void AddPlayer (Player *)
Method that is called when adding a player to the battleground.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual Team GetPrematureWinner ()
Function that returns the premature winner.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Static Public Member Functions
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Private Types
typedef std::deque< ObjectGuid > OfflineQueue
Private Attributes
BattleGroundTypeId m_typeId
BattleGroundTypeId m_randomTypeId
BattleGroundStatus m_status
BattleGroundBracketId m_bracketId
ArenaType m_arenaType
BattleGroundWinner m_winner
uint32 m_clientInstanceId
uint32 m_startTime
uint32 m_validStartPositionTimer
uint32 m_prematureCountDownTimer
int32 m_endTime
int32 m_startDelayTime
bool m_arenaBuffSpawned
bool m_hasBgFreeSlotQueue
bool m_isRated
bool m_prematureCountDown
bool m_isArena
char const * m_name
OfflineQueue m_offlineQueue
uint32 m_invitedAlliance
uint32 m_invitedHorde
Group * m_bgRaids [PVP_TEAM_COUNT]
uint32 m_playersCount [PVP_TEAM_COUNT]
uint32 m_arenaTeamIds [PVP_TEAM_COUNT]
int32 m_arenaTeamRatingChanges [PVP_TEAM_COUNT]
uint32 m_levelMin
uint32 m_levelMax
uint32 m_maxPlayersPerTeam
uint32 m_maxPlayers
uint32 m_minPlayersPerTeam
uint32 m_minPlayers
uint32 m_mapId
BattleGroundMap * m_bgMap
float m_teamStartLocX [PVP_TEAM_COUNT]
float m_teamStartLocY [PVP_TEAM_COUNT]
float m_teamStartLocZ [PVP_TEAM_COUNT]
float m_teamStartLocO [PVP_TEAM_COUNT]
float m_startMaxDist
uint32 m_playerSkinReflootId
Friends
class BattleGroundMgr
Detailed Description
Definition at line 334 of file BattleGround.h.
Member Typedef Documentation
BattleGroundPlayerMap
typedef std::map<ObjectGuid, BattleGroundPlayer> BattleGround::BattleGroundPlayerMap
Definition at line 425 of file BattleGround.h.
BattleGroundScoreMap
typedef std::map<ObjectGuid, BattleGroundScore*> BattleGround::BattleGroundScoreMap
Definition at line 430 of file BattleGround.h.
EntryGuidMap
typedef std::map<uint32, ObjectGuid> BattleGround::EntryGuidMap
Definition at line 439 of file BattleGround.h.
OfflineQueue
typedef std::deque<ObjectGuid> BattleGround::OfflineQueue private
Definition at line 730 of file BattleGround.h.
Constructor & Destructor Documentation
BattleGround()
BattleGround::BattleGround ()
Definition at line 217 of file BattleGround.cpp.
References ARENA_TYPE_NONE, BATTLEGROUND_TYPE_NONE, BG_BRACKET_ID_TEMPLATE, BG_START_DELAY_1M, BG_START_DELAY_2M, BG_START_DELAY_30S, BG_START_DELAY_NONE, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_WS_HAS_BEGUN, LANG_BG_WS_START_HALF_MINUTE, LANG_BG_WS_START_ONE_MINUTE, m_arenaTeamIds, m_arenaTeamRatingChanges, m_arenaType, m_bgMap, m_bgRaids, m_bracketId, m_clientInstanceId, m_endTime, m_events, m_hasBgFreeSlotQueue, m_invitedAlliance, m_invitedHorde, m_isArena, m_isRandom, m_isRated, m_levelMax, m_levelMin, m_mapId, m_maxPlayers, m_maxPlayersPerTeam, m_minPlayers, m_minPlayersPerTeam, m_name, m_playersCount, m_prematureCountDown, m_prematureCountDownTimer, m_randomTypeId, m_startDelayTimes, m_startMessageIds, m_startTime, m_status, m_teamStartLocO, m_teamStartLocX, m_teamStartLocY, m_teamStartLocZ, m_typeId, m_validStartPositionTimer, m_winner, STATUS_NONE, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and WINNER_NONE.
~BattleGround()
BattleGround::~BattleGround () virtual
Deconstructor.
Definition at line 289 of file BattleGround.cpp.
References BG_BRACKET_ID_TEMPLATE, GetBracketId(), GetClientInstanceId(), GetInstanceId(), GetTypeId(), m_bgMap, m_playerScores, RemoveFromBgFreeSlotQueue(), sBattleGroundMgr, and BattleGroundMap::SetUnload().
Member Function Documentation
AddOrSetPlayerToCorrectBgGroup()
void BattleGround::AddOrSetPlayerToCorrectBgGroup (Player * plr, ObjectGuid playerGuid, Team team)
Method that handles adding players to the correct BG group.
Parameters
player
objectGuid
team
Definition at line 1615 of file BattleGround.cpp.
References GetBgRaid(), WorldObject::GetName(), Player::GetOriginalGroup(), Player::SetBattleRaid(), and SetBgRaid().
Referenced by AddPlayer(), and Player::LoadFromDB().
AddPlayer()
void BattleGround::AddPlayer (Player * player) virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented in BattleGroundIC, BattleGroundWS, BattleGroundSA, BattleGroundEY, BattleGroundAV, and BattleGroundAB.
Definition at line 1514 of file BattleGround.cpp.
References ACHIEVEMENT_CRITERIA_CONDITION_MAP, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, AddOrSetPlayerToCorrectBgGroup(), ALLIANCE, Unit::CastSpell(), Player::DestroyConjuredItems(), DETAIL_LOG, Player::GetAchievementMgr(), GetAlivePlayersCountByTeam(), GetBgMap(), Player::GetBGTeam(), GetMapId(), WorldObject::GetName(), Object::GetObjectGuid(), GetStatus(), Player::GetTeam(), Map::GetVariableManager(), HORDE, Player::isAFK(), IsArena(), m_players, m_playerScores, BattleGroundPlayer::offlineRemoveTime, PlayerAddedToBgCheckIfBgIsRunning(), BattleGroundPlayer::playerTeam, Player::RemoveAllEnchantments(), Unit::RemoveArenaAuras(), Player::RemoveArenaSpellCooldowns(), AchievementMgr::ResetAchievementCriteria(), sBattleGroundMgr, SendPacketToTeam(), WorldStateVariableManager::SetVariable(), SPELL_ALLIANCE_GOLD_FLAG, SPELL_ALLIANCE_GREEN_FLAG, SPELL_ARENA_DAMPENING, SPELL_ARENA_PREPARATION, SPELL_BATTLEGROUND_DAMPENING, SPELL_HORDE_GOLD_FLAG, SPELL_HORDE_GREEN_FLAG, SPELL_PREPARATION, STATUS_WAIT_JOIN, BattleGroundScore::Team, TEMP_ENCHANTMENT_SLOT, Player::ToggleAFK(), TRIGGERED_OLD_TRIGGERED, Player::UnsummonPetTemporaryIfAny(), UpdatePlayersCountByTeam(), WORLD_STATE_ARENA_COUNT_A, and WORLD_STATE_ARENA_COUNT_H.
Referenced by BattleGroundAB::AddPlayer(), BattleGroundAV::AddPlayer(), BattleGroundEY::AddPlayer(), BattleGroundSA::AddPlayer(), BattleGroundWS::AddPlayer(), and BattleGroundIC::AddPlayer().
AddToBgFreeSlotQueue()
void BattleGround::AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
Definition at line 1713 of file BattleGround.cpp.
References IsBattleGround(), m_hasBgFreeSlotQueue, m_typeId, and sBattleGroundMgr.
Referenced by RemovePlayerAtLeave(), and StartBattleGround().
AlterTeleportLocation()
virtual void BattleGround::AlterTeleportLocation (Player * player, ObjectGuid & transportGuid, float & x, float & y, float & z, float & ori) inline virtual
Reimplemented in BattleGroundSA.
Definition at line 675 of file BattleGround.h.
BlockMovement()
void BattleGround::BlockMovement (Player * player) static
Method that blocks player movement - called at the end of battleground.
Definition at line 1257 of file BattleGround.cpp.
References Object::SetFlag(), UNIT_FIELD_FLAGS, UNIT_FLAG_CLIENT_CONTROL_LOST, and Player::UpdateClientControl().
Referenced by EndBattleGround(), and PlayerAddedToBgCheckIfBgIsRunning().
BroadcastWorker()
template<class Do > void BattleGround::BroadcastWorker (Do & _do)
Definition at line 210 of file BattleGround.cpp.
References ObjectAccessor::FindPlayer(), and m_players.
Referenced by PSendMessageToAll(), SendBcdToAll(), SendBcdToTeam(), SendMessage2ToAll(), SendMessageToAll(), SendYell2ToAll(), and SendYellToAll().
CastSpellOnTeam()
void BattleGround::CastSpellOnTeam (uint32 spellId, Team teamId)
Method casts spell to an entire battleground team.
Parameters
spell Id
team
Definition at line 666 of file BattleGround.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetTeam(), HORDE, m_players, sLog, sObjectMgr, and TRIGGERED_OLD_TRIGGERED.
Referenced by BattleGroundIC::DoApplyTeamBuff(), BattleGroundSA::HandleEvent(), BattleGroundAV::HandleKillUnit(), BattleGroundSA::ProcessBattlegroundWinner(), BattleGroundAB::ProcessNodeCapture(), and BattleGroundSA::Update().
ChangeBgCreatureSpawnState()
void BattleGround::ChangeBgCreatureSpawnState (uint32 dbGuid, uint32 respawntime)
Method that changes the battleground creature spawn state.
Parameters
gameobject guid
respawn time (can be 0 or 1 day)
Definition at line 2036 of file BattleGround.cpp.
References Map::Add(), Creature::ForcedDespawn(), GetBgMap(), Map::GetCreature(), Map::GetSpawnManager(), Creature::Respawn(), SpawnManager::RespawnCreature(), and Creature::SetRespawnDelay().
Referenced by OnObjectDBLoad(), and SpawnEvent().
ChangeBgObjectSpawnState()
void BattleGround::ChangeBgObjectSpawnState (uint32 dbGuid, uint32 respawntime)
Method that changes the battleground gameobject spawn state.
Parameters
gameobject guid
respawn time (can be 0 or 1 day)
Definition at line 1997 of file BattleGround.cpp.
References GetBgMap(), Map::GetGameObject(), GameObject::GetLootState(), Map::GetSpawnManager(), GO_JUST_DEACTIVATED, GO_READY, GameObject::IsSpawnedByDefault(), GameObject::Refresh(), GameObject::Respawn(), RESPAWN_ONE_DAY, SpawnManager::RespawnGameObject(), GameObject::SetForcedDespawn(), GameObject::SetLootState(), GameObject::SetRespawnDelay(), and GameObject::SetRespawnTime().
Referenced by BattleGroundIC::DoApplyObjectiveBenefits(), BattleGroundIC::DoChangeBannerState(), BattleGroundIC::DoResetObjective(), BattleGroundSA::HandleEvent(), OnObjectDBLoad(), BattleGroundEY::RespawnFlagAtCenter(), BattleGroundSA::SetupBattleground(), and SpawnEvent().
CheckAchievementCriteriaMeet()
virtual bool BattleGround::CheckAchievementCriteriaMeet (uint32 , Player const * , Unit const * , uint32) inline virtual
Reimplemented in BattleGroundIC, BattleGroundEY, BattleGroundAV, BattleGroundWS, BattleGroundSA, and BattleGroundAB.
Definition at line 652 of file BattleGround.h.
CheckArenaWinConditions()
void BattleGround::CheckArenaWinConditions ()
Method that checks arena win conditions.
Definition at line 2324 of file BattleGround.cpp.
References ALLIANCE, EndBattleGround(), GetAlivePlayersCountByTeam(), GetPlayersCountByTeam(), and HORDE.
Referenced by HandleKillPlayer(), RemovePlayer(), and Update().
DecreaseInvitedCount()
void BattleGround::DecreaseInvitedCount (Team team) inline
Definition at line 408 of file BattleGround.h.
References ALLIANCE, m_invitedAlliance, and m_invitedHorde.
Referenced by BattleGroundQueue::RemovePlayer(), and RemovePlayerAtLeave().
DoorClose()
void BattleGround::DoorClose (uint32 dbGuid)
Method that handles door closing.
Parameters
gameobject guid
Definition at line 1809 of file BattleGround.cpp.
References GetBgMap(), Map::GetGameObject(), GameObject::GetGoState(), GameObject::GetLootState(), GO_ACTIVATED, GO_READY, GO_STATE_READY, RESPAWN_ONE_DAY, GameObject::SetLootState(), sLog, and GameObject::UseDoorOrButton().
DoorOpen()
void BattleGround::DoorOpen (uint32 dbGuid)
Method that handles opens doors.
Parameters
gameobject guid
Definition at line 1831 of file BattleGround.cpp.
References GetBgMap(), Map::GetGameObject(), GO_READY, RESPAWN_ONE_DAY, GameObject::SetLootState(), sLog, and GameObject::UseDoorOrButton().
Referenced by OnObjectDBLoad(), and OpenDoorEvent().
EndBattleGround()
void BattleGround::EndBattleGround (Team winner) virtual
Method that ends battleground.
Parameters
winner team
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundIC, BattleGroundEY, BattleGroundAV, and BattleGroundAB.
Definition at line 788 of file BattleGround.cpp.
References ACHIEVEMENT_CRITERIA_CONDITION_NO_LOOSE, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, SqlStatement::addUInt32(), ALLIANCE, ARENA_TIMELIMIT_POINTS_LOSS, BATTLEGROUND_AV, BG_REWARD_LOOSER_HONOR_FIRST, BG_REWARD_LOOSER_HONOR_LAST, BG_REWARD_WINNER_ARENA_FIRST, BG_REWARD_WINNER_ARENA_LAST, BG_REWARD_WINNER_HONOR_FIRST, BG_REWARD_WINNER_HONOR_LAST, BattleGroundMgr::BgQueueTypeId(), BlockMovement(), CharacterDatabase, CHAT_MSG_BG_SYSTEM_NEUTRAL, Unit::CombatStop(), Unit::CombatStopWithPets(), CONFIG_BOOL_BATTLEGROUND_SCORE_STATISTICS, Database::CreateStatement(), DEBUG_LOG, SqlStatement::Execute(), QueryResult::Fetch(), Player::GetAchievementMgr(), GetArenaTeamIdForTeam(), GetArenaType(), BattleGroundScore::GetAttr1(), BattleGroundScore::GetAttr2(), BattleGroundScore::GetAttr3(), BattleGroundScore::GetAttr4(), BattleGroundScore::GetAttr5(), Player::GetBattleGroundQueueIndex(), GetBgMap(), Player::GetBGTeam(), BattleGroundScore::GetBonusHonor(), GetBonusHonorFromKill(), BattleGroundScore::GetDamageDone(), BattleGroundScore::GetDeaths(), Object::GetGUIDLow(), BattleGroundScore::GetHealingDone(), BattleGroundScore::GetHonorableKills(), BattleGroundScore::GetKillingBlows(), ArenaTeam::GetMember(), GetMinLevel(), Object::GetObjectGuid(), Map::GetObjectsStore(), GetOtherTeam(), Player::GetSession(), GetStartTime(), ArenaTeam::GetStats(), GetTypeId(), Field::GetUInt64(), Unit::HasAuraType(), Player::HasWonRandomBattleground(), HORDE, Unit::IsAlive(), IsArena(), IsBattleGround(), Unit::IsClientControlled(), IsRandom(), IsRated(), ITEM_LOSER_COUNT, ITEM_WINNER_COUNT, LANG_ARENA_GOLD_WINS, LANG_ARENA_GREEN_WINS, LANG_BG_A_WINS, LANG_BG_H_WINS, ArenaTeam::LostAgainst(), m_endTime, m_players, m_playerScores, ArenaTeam::MemberLost(), ArenaTeam::MemberWon(), Player::ModifyArenaPoints(), ArenaTeam::NotifyStatsChanged(), ArenaTeam::OfflineMemberLost(), ArenaTeamMember::personal_rating, SqlStatement::PExecute(), PlaySoundToTeam(), Database::Query(), ArenaTeamStats::rating, RemoveFromBgFreeSlotQueue(), Unit::RemoveSpellsCausingAura(), AchievementMgr::ResetAchievementCriteria(), Player::ResurrectPlayer(), RewardMark(), RewardQuestComplete(), ArenaTeam::SaveToDB(), sBattleGroundMgr, SCORE_BONUS_HONOR, SendMessageToAll(), WorldSession::SendPacket(), SetArenaTeamRatingChangeForTeam(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Player::SetRandomBattlegroundWinner(), SetStatus(), Unit::SetStunned(), SetWinner(), sLog, sObjectMgr, SOUND_ALLIANCE_WINS, SOUND_HORDE_WINS, Player::SpawnCorpseBones(), SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_SPIRIT_OF_REDEMPTION, STATUS_IN_PROGRESS, STATUS_WAIT_LEAVE, sWorld, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_INDEX_NEUTRAL, TEAM_NONE, TIME_TO_AUTOREMOVE, AchievementMgr::UpdateAchievementCriteria(), UpdatePlayerScore(), WINNER_ALLIANCE, WINNER_HORDE, WINNER_NONE, and ArenaTeam::WonAgainst().
Referenced by CheckArenaWinConditions(), BattleGroundAB::EndBattleGround(), BattleGroundAV::EndBattleGround(), BattleGroundEY::EndBattleGround(), BattleGroundIC::EndBattleGround(), BattleGroundSA::EndBattleGround(), BattleGroundWS::EndBattleGround(), EventPlayerLoggedOut(), ChatHandler::HandleBattlegroundStopCommand(), and Update().
EndNow()
void BattleGround::EndNow () protected
Function that ends the battleground immediately.
Definition at line 2180 of file BattleGround.cpp.
References RemoveFromBgFreeSlotQueue(), SetEndTime(), SetStatus(), and STATUS_WAIT_LEAVE.
EventPlayerLoggedIn()
void BattleGround::EventPlayerLoggedIn (Player * player)
Method that handles players logging out from ongoing battlegrounds.
Parameters
player
Definition at line 1645 of file BattleGround.cpp.
References Object::GetObjectGuid(), m_offlineQueue, m_players, and PlayerAddedToBgCheckIfBgIsRunning().
Referenced by Player::LoadFromDB().
EventPlayerLoggedOut()
void BattleGround::EventPlayerLoggedOut (Player * player)
Method that handles players logging out from ongoing battlegrounds.
Parameters
player
Definition at line 1670 of file BattleGround.cpp.
References EndBattleGround(), GetAlivePlayersCountByTeam(), Object::GetObjectGuid(), GetOtherTeam(), GetPlayersCountByTeam(), GetStatus(), Player::GetTeam(), IsArena(), m_offlineQueue, m_players, MAX_OFFLINE_TIME, RemovePlayer(), STATUS_IN_PROGRESS, and sWorld.
FillInitialWorldStates()
virtual void BattleGround::FillInitialWorldStates (WorldPacket & , uint32 &) inline virtual
Definition at line 471 of file BattleGround.h.
GetAlivePlayersCountByTeam()
uint32 BattleGround::GetAlivePlayersCountByTeam (Team team) const
Function that counts the alive players by team.
Parameters
team
Definition at line 2306 of file BattleGround.cpp.
References FORM_SPIRITOFREDEMPTION, Unit::GetShapeshiftForm(), Unit::IsAlive(), m_players, and sObjectMgr.
Referenced by AddPlayer(), CheckArenaWinConditions(), EventPlayerLoggedOut(), HandleKillPlayer(), and RemovePlayer().
GetArenaTeamIdForTeam()
uint32 BattleGround::GetArenaTeamIdForTeam (Team team) const inline
Definition at line 550 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_arenaTeamIds.
Referenced by EndBattleGround(), and RemovePlayerAtLeave().
GetArenaTeamRatingChangeForTeam()
int32 BattleGround::GetArenaTeamRatingChangeForTeam (Team team) const inline
Definition at line 552 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_arenaTeamRatingChanges.
GetArenaType()
ArenaType BattleGround::GetArenaType () const inline
Definition at line 373 of file BattleGround.h.
References m_arenaType.
Referenced by EndBattleGround(), BgQueueInviteEvent::Execute(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), BattleGroundQueue::InviteGroupToBg(), Player::LoadFromDB(), PlayerAddedToBgCheckIfBgIsRunning(), RemovePlayerAtLeave(), Update(), and AchievementMgr::UpdateAchievementCriteria().
GetBattlemasterEntry()
uint32 BattleGround::GetBattlemasterEntry () const
Function that returns the battleground master entry.
Definition at line 1062 of file BattleGround.cpp.
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_SA, BATTLEGROUND_WS, and GetTypeId().
Referenced by SendRewardMarkByMail().
GetBgMap()
BattleGroundMap* BattleGround::GetBgMap () const inline
Definition at line 449 of file BattleGround.h.
References m_bgMap, and MANGOS_ASSERT.
Referenced by AddPlayer(), BattleGroundEY::AddPoints(), BattleGroundSA::AlterTeleportLocation(), ChangeBgCreatureSpawnState(), ChangeBgObjectSpawnState(), BattleGroundAV::ChangeMineOwner(), BattleGroundAB::CheckAchievementCriteriaMeet(), BattleGroundWS::CheckAchievementCriteriaMeet(), BattleGroundEY::CheckVictory(), BattleGroundIC::DoApplyObjectiveBenefits(), BattleGroundIC::DoCaptureObjective(), DoorClose(), DoorOpen(), BattleGroundIC::DoResetObjective(), BattleGroundRV::DoSwitchPillars(), BattleGroundAB::DoUpdateNodeWorldstate(), BattleGroundSA::EnableDemolishers(), BattleGroundEY::EndBattleGround(), EndBattleGround(), BattleGroundWS::GetFlagState(), GetInstanceId(), BattleGroundAB::GetPrematureWinner(), BattleGroundAV::GetPrematureWinner(), BattleGroundEY::GetPrematureWinner(), BattleGroundWS::GetPrematureWinner(), BattleGroundIC::GetReinforcements(), GetSingleCreatureFromStorage(), GetSingleGameObjectFromStorage(), BattleGroundWS::HandleAreaTrigger(), BattleGroundIC::HandleEvent(), BattleGroundSA::HandleEvent(), HandleKillPlayer(), BattleGroundIC::HandleKillUnit(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), HandleTriggerBuff(), BattleGroundAV::InitializeNode(), BattleGroundWS::IsFlagHeldFor45Seconds(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAB::ProcessNodeCapture(), BattleGroundAV::ProcessPlayerAssaultsPoint(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundEY::ProcessPlayerFlagScoreEvent(), RemovePlayer(), Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundSA::Reset(), BattleGroundWS::Reset(), BattleGroundEY::RespawnDroppedFlag(), BattleGroundWS::RespawnDroppedFlag(), BattleGroundWS::RespawnFlagAtBase(), BattleGroundSA::SendBattlegroundWarning(), SendMessageToAll(), BattleGroundSA::SetDefender(), BattleGroundEY::SetFlagState(), BattleGroundIC::SetReinforcements(), BattleGroundEY::SetTowerOwner(), BattleGroundSA::SetupBattleground(), BattleGroundSA::SetupGraveyards(), BattleGroundAB::StartingEventOpenDoors(), BattleGroundAV::StartingEventOpenDoors(), BattleGroundEY::StartingEventOpenDoors(), BattleGroundIC::StartingEventOpenDoors(), BattleGroundSA::StartingEventOpenDoors(), BattleGroundWS::StartingEventOpenDoors(), StartTimedAchievement(), BattleGroundAB::Update(), BattleGroundIC::Update(), BattleGroundSA::Update(), BattleGroundWS::Update(), BattleGroundDS::Update(), BattleGroundAV::UpdateNodeWorldState(), BattleGroundEY::UpdateResources(), BattleGroundAV::UpdateScore(), and BattleGroundSA::UpdateTimerWorldState().
GetBgRaid()
Group* BattleGround::GetBgRaid (Team team) const inline
Definition at line 532 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_bgRaids.
Referenced by AddOrSetPlayerToCorrectBgGroup(), RemovePlayerAtLeave(), and Group::~Group().
GetBonusHonorFromKill()
uint32 BattleGround::GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
Parameters
kills
Definition at line 1053 of file BattleGround.cpp.
References GetMaxLevel(), and MaNGOS::Honor::hk_honor_at_level().
Referenced by BattleGroundEY::AddPoints(), BattleGroundSA::AwardBonusHonor(), BattleGroundAB::EndBattleGround(), BattleGroundAV::EndBattleGround(), BattleGroundEY::EndBattleGround(), BattleGroundIC::EndBattleGround(), BattleGroundSA::EndBattleGround(), BattleGroundWS::EndBattleGround(), EndBattleGround(), BattleGroundAV::HandleKillUnit(), BattleGroundIC::HandleKillUnit(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundAB::Update(), and BattleGroundIC::Update().
GetBracketId()
BattleGroundBracketId BattleGround::GetBracketId () const inline
Definition at line 355 of file BattleGround.h.
References m_bracketId.
Referenced by BattleGroundQueue::InviteGroupToBg(), RemovePlayerAtLeave(), Update(), and ~BattleGround().
GetClientInstanceId()
uint32 BattleGround::GetClientInstanceId () const inline
Definition at line 360 of file BattleGround.h.
References m_clientInstanceId.
Referenced by BattleGroundMgr::BuildBattleGroundStatusPacket(), BattleGroundQueue::FillPlayersToBg(), and ~BattleGround().
GetEndTime()
uint32 BattleGround::GetEndTime () const inline
Definition at line 362 of file BattleGround.h.
References m_endTime.
Referenced by WorldSession::HandleBattlefieldStatusOpcode(), and PlayerAddedToBgCheckIfBgIsRunning().
GetFreeSlotsForTeam()
uint32 BattleGround::GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
Parameters
team
Definition at line 1747 of file BattleGround.cpp.
References GetInvitedCount(), GetMaxPlayersPerTeam(), GetStatus(), STATUS_IN_PROGRESS, and STATUS_WAIT_JOIN.
Referenced by BattleGroundQueue::FillPlayersToBg().
GetInstanceId()
uint32 BattleGround::GetInstanceId () const inline
Definition at line 358 of file BattleGround.h.
References GetBgMap(), Map::GetInstanceId(), and m_bgMap.
Referenced by BattleGroundMgr::CreateBattleGround(), WorldSession::HandleBattlefieldPortOpcode(), ChatHandler::HandleBattlegroundStartCommand(), ChatHandler::HandleBattlegroundStopCommand(), BattleGroundQueue::InviteGroupToBg(), Player::LoadFromDB(), RemoveFromBgFreeSlotQueue(), StartBattleGround(), and ~BattleGround().
GetInvitedCount()
uint32 BattleGround::GetInvitedCount (Team team) const inline
Definition at line 410 of file BattleGround.h.
References ALLIANCE, m_invitedAlliance, and m_invitedHorde.
Referenced by GetFreeSlotsForTeam(), and Update().
GetMapId()
uint32 BattleGround::GetMapId () const inline
Definition at line 445 of file BattleGround.h.
References m_mapId.
Referenced by AddPlayer(), BattleGroundMgr::BuildBattleGroundStatusPacket(), Group::CanJoinBattleGroundQueue(), MapManager::CreateBattleGroundMap(), BattleGroundMgr::CreateNewBattleGround(), BattleGroundDS::HandleAreaTrigger(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), BattleGroundBE::HandlePlayerUnderMap(), BattleGroundDS::HandlePlayerUnderMap(), BattleGroundNA::HandlePlayerUnderMap(), BattleGroundRL::HandlePlayerUnderMap(), BattleGroundRV::HandlePlayerUnderMap(), BattleGroundMgr::SendToBattleGround(), BattleGroundQueue::Update(), and Update().
GetMaxLevel()
uint32 BattleGround::GetMaxLevel () const inline
Definition at line 367 of file BattleGround.h.
References m_levelMax.
Referenced by BattleGroundMgr::BuildBattleGroundStatusPacket(), Player::GetBGAccessByLevel(), GetBonusHonorFromKill(), WorldSession::HandleBattlefieldPortOpcode(), and Update().
GetMaxPlayers()
uint32 BattleGround::GetMaxPlayers () const inline
Definition at line 363 of file BattleGround.h.
References m_maxPlayers.
Referenced by HasFreeSlots().
GetMaxPlayersPerTeam()
uint32 BattleGround::GetMaxPlayersPerTeam () const inline
Definition at line 369 of file BattleGround.h.
References m_maxPlayersPerTeam.
Referenced by GetFreeSlotsForTeam(), WorldSession::HandleBattlemasterJoinOpcode(), and BattleGroundQueue::Update().
GetMinLevel()
uint32 BattleGround::GetMinLevel () const inline
Definition at line 366 of file BattleGround.h.
References m_levelMin.
Referenced by BattleGroundMgr::BuildBattleGroundStatusPacket(), MapManager::CreateBattleGroundMap(), EndBattleGround(), Player::GetBGAccessByLevel(), and Update().
GetMinPlayers()
uint32 BattleGround::GetMinPlayers () const inline
Definition at line 364 of file BattleGround.h.
References m_minPlayers.
GetMinPlayersPerTeam()
uint32 BattleGround::GetMinPlayersPerTeam () const inline
Definition at line 370 of file BattleGround.h.
References m_minPlayersPerTeam.
Referenced by WorldSession::HandleBattlemasterJoinOpcode(), BattleGroundQueue::Update(), and Update().
GetName()
char const* BattleGround::GetName () const inline
Definition at line 353 of file BattleGround.h.
References m_name.
Referenced by ChatHandler::HandleBattlegroundStartCommand(), ChatHandler::HandleBattlegroundStopCommand(), SendRewardMarkByMail(), and Update().
GetOtherTeam()
static Team BattleGround::GetOtherTeam (Team team) inline static
Definition at line 640 of file BattleGround.h.
References ALLIANCE, HORDE, and TEAM_NONE.
Referenced by EndBattleGround(), EventPlayerLoggedOut(), and RemovePlayerAtLeave().
GetOtherTeamIndex()
static PvpTeamIndex BattleGround::GetOtherTeamIndex (PvpTeamIndex teamIdx) inline static
Definition at line 643 of file BattleGround.h.
References TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by BattleGroundWS::HandleEvent(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), BattleGroundWS::IsFlagHeldFor45Seconds(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundWS::RemovePlayer(), BattleGroundWS::RespawnFlagAtBase(), BattleGroundSA::SetDefender(), and BattleGroundAB::Update().
GetPlayers()
BattleGroundPlayerMap const& BattleGround::GetPlayers () const inline
Definition at line 426 of file BattleGround.h.
References m_players.
Referenced by StartTimedAchievement(), Update(), and BattleGroundDS::Update().
GetPlayerScoresBegin()
BattleGroundScoreMap::const_iterator BattleGround::GetPlayerScoresBegin () const inline
Definition at line 431 of file BattleGround.h.
References m_playerScores.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket().
GetPlayerScoresEnd()
BattleGroundScoreMap::const_iterator BattleGround::GetPlayerScoresEnd () const inline
Definition at line 432 of file BattleGround.h.
References m_playerScores.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket().
GetPlayerScoresSize()
uint32 BattleGround::GetPlayerScoresSize () const inline
Definition at line 433 of file BattleGround.h.
References m_playerScores.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket().
GetPlayersCountByTeam()
uint32 BattleGround::GetPlayersCountByTeam (Team team) const inline
Definition at line 538 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_playersCount.
Referenced by CheckArenaWinConditions(), EventPlayerLoggedOut(), GetPrematureWinner(), and Update().
GetPlayerSkinRefLootId()
uint32 BattleGround::GetPlayerSkinRefLootId () const inline
Definition at line 672 of file BattleGround.h.
References m_playerSkinReflootId.
Referenced by Loot::Loot().
GetPlayersSize()
uint32 BattleGround::GetPlayersSize () const inline
Definition at line 427 of file BattleGround.h.
References m_players.
Referenced by HasFreeSlots(), and Update().
GetPlayerTeam()
Team BattleGround::GetPlayerTeam (ObjectGuid guid)
Function that returns the team of the given player - used mainly in arenas.
Parameters
player objectguid
Definition at line 2260 of file BattleGround.cpp.
References m_players, and TEAM_NONE.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and RemovePlayerAtLeave().
GetPrematureWinner()
Team BattleGround::GetPrematureWinner () virtual
Function that returns the premature winner.
Reimplemented in BattleGroundWS, BattleGroundEY, BattleGroundAV, and BattleGroundAB.
Definition at line 1847 of file BattleGround.cpp.
References ALLIANCE, GetPlayersCountByTeam(), HORDE, and TEAM_NONE.
Referenced by BattleGroundAB::GetPrematureWinner(), BattleGroundAV::GetPrematureWinner(), BattleGroundEY::GetPrematureWinner(), BattleGroundWS::GetPrematureWinner(), and Update().
GetSingleCreatureFromStorage()
Creature * BattleGround::GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog = false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
Can return nullptr
Parameters
creature entry
skip debug log
Definition at line 2385 of file BattleGround.cpp.
References GetBgMap(), Map::GetCreature(), m_npcEntryGuidStore, and script_error_log().
Referenced by BattleGroundAV::DoSendYellToTeam(), BattleGroundAV::EndBattleGround(), BattleGroundAV::ProcessPlayerDestroyedPoint(), and BattleGroundAV::Update().
GetSingleCreatureGuid()
uint32 BattleGround::GetSingleCreatureGuid (uint8 event1, uint8 event2)
Function returns a creature guid from event map.
Parameters
event1
event2
Definition at line 1883 of file BattleGround.cpp.
References m_eventObjects, and MAKE_PAIR32.
GetSingleGameObjectFromStorage()
GameObject * BattleGround::GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Can return nullptr
Parameters
gameobject entry
Definition at line 2367 of file BattleGround.cpp.
References GetBgMap(), Map::GetGameObject(), m_goEntryGuidStore, and sLog.
Referenced by BattleGroundSA::ChangeBannerState(), BattleGroundIC::DoCaptureObjective(), BattleGroundIC::DoChangeBannerState(), BattleGroundIC::HandleEvent(), BattleGroundSA::HandleEvent(), BattleGroundAB::ProcessNodeCapture(), and BattleGroundSA::SetupBattleground().
GetStartDelayTime()
int32 BattleGround::GetStartDelayTime () const inline
Definition at line 372 of file BattleGround.h.
References m_startDelayTime.
Referenced by Update().
GetStartMaxDist()
float BattleGround::GetStartMaxDist () const inline
Definition at line 467 of file BattleGround.h.
References m_startMaxDist.
Referenced by Update().
GetStartTime()
uint32 BattleGround::GetStartTime () const inline
Definition at line 361 of file BattleGround.h.
References m_startTime.
Referenced by EndBattleGround(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), and PlayerAddedToBgCheckIfBgIsRunning().
GetStatus()
BattleGroundStatus BattleGround::GetStatus () const inline
Definition at line 359 of file BattleGround.h.
References m_status.
Referenced by AddPlayer(), BattleGroundMgr::BuildPvpLogDataPacket(), EventPlayerLoggedOut(), GetFreeSlotsForTeam(), SpellMgr::GetSpellAllowedInLocationError(), BattleGroundDS::HandleAreaTrigger(), BattleGroundRV::HandleAreaTrigger(), BattleGroundEY::HandleAreaTrigger(), BattleGroundWS::HandleAreaTrigger(), HandleKillPlayer(), BattleGroundAV::HandleKillPlayer(), BattleGroundEY::HandleKillPlayer(), BattleGroundIC::HandleKillPlayer(), BattleGroundWS::HandleKillPlayer(), BattleGroundAV::HandleKillUnit(), BattleGroundIC::HandleKillUnit(), BattleGroundEY::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerClickedOnFlag(), BattleGroundAV::HandlePlayerClickedOnFlag(), BattleGroundEY::HandlePlayerDroppedFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), BattleGroundAV::HandleQuestComplete(), Player::LoadFromDB(), OnObjectDBLoad(), PlayerAddedToBgCheckIfBgIsRunning(), BattleGroundAV::ProcessPlayerDefendsPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundEY::ProcessPlayerFlagScoreEvent(), RemovePlayer(), RemovePlayerAtLeave(), BattleGroundWS::RespawnDroppedFlag(), Update(), BattleGroundAB::Update(), BattleGroundAV::Update(), BattleGroundEY::Update(), BattleGroundSA::Update(), BattleGroundWS::Update(), and BattleGroundRV::Update().
GetTeamStartLoc()
void BattleGround::GetTeamStartLoc (Team team, float & x, float & y, float & z, float & o) const inline
Definition at line 457 of file BattleGround.h.
References GetTeamIndexByTeamId(), m_teamStartLocO, m_teamStartLocX, m_teamStartLocY, and m_teamStartLocZ.
Referenced by BattleGroundMgr::SendToBattleGround(), and Update().
GetTypeId()
BattleGroundTypeId BattleGround::GetTypeId (bool getRandom = false) const inline
Definition at line 354 of file BattleGround.h.
References m_randomTypeId, and m_typeId.
Referenced by BattleGroundMgr::BuildBattleGroundStatusPacket(), BattleGroundMgr::BuildPvpLogDataPacket(), Group::CanJoinBattleGroundQueue(), BattleGroundMgr::CreateBattleGround(), MapManager::CreateBattleGroundMap(), EndBattleGround(), BgQueueInviteEvent::Execute(), GetBattlemasterEntry(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattleGroundPlayerPositionsOpcode(), WorldSession::HandleBattlemasterJoinArena(), BattleGroundQueue::InviteGroupToBg(), Player::LoadFromDB(), PlayerAddedToBgCheckIfBgIsRunning(), RemovePlayerAtLeave(), Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundWS::Reset(), RewardMark(), RewardQuestComplete(), StartBattleGround(), Update(), and ~BattleGround().
GetWinner()
BattleGroundWinner BattleGround::GetWinner () const inline
Definition at line 374 of file BattleGround.h.
References m_winner.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and BattleGroundWS::CheckAchievementCriteriaMeet().
HandleAreaTrigger()
virtual bool BattleGround::HandleAreaTrigger (Player * , uint32) inline virtual
Reimplemented in BattleGroundWS, BattleGroundEY, BattleGroundAV, BattleGroundAB, BattleGroundRV, and BattleGroundDS.
Definition at line 558 of file BattleGround.h.
HandleCreatureCreate()
virtual void BattleGround::HandleCreatureCreate (Creature *) inline virtual
Reimplemented in BattleGroundSA, BattleGroundIC, BattleGroundDS, and BattleGroundAV.
Definition at line 570 of file BattleGround.h.
HandleEvent()
virtual bool BattleGround::HandleEvent (uint32 , Object * , Object *) inline virtual
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundIC, and BattleGroundEY.
Definition at line 567 of file BattleGround.h.
Referenced by StartEvents_Event().
HandleGameObjectCreate()
virtual void BattleGround::HandleGameObjectCreate (GameObject *) inline virtual
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundIC, BattleGroundEY, BattleGroundAB, BattleGroundRV, BattleGroundDS, and BattleGroundAV.
Definition at line 573 of file BattleGround.h.
HandleGameObjectDamaged()
virtual void BattleGround::HandleGameObjectDamaged (Player * , GameObject * , uint32) inline virtual
Reimplemented in BattleGroundSA, and BattleGroundIC.
Definition at line 582 of file BattleGround.h.
HandleKillPlayer()
void BattleGround::HandleKillPlayer (Player * player, Player * killer) virtual
Method that handles killing players.
also handles generic logic for arena updates
Parameters
victim player
killer player
Reimplemented in BattleGroundWS, BattleGroundIC, BattleGroundEY, and BattleGroundAV.
Definition at line 2208 of file BattleGround.cpp.
References ACHIEVEMENT_CRITERIA_CONDITION_NO_DEATH, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ALLIANCE, CheckArenaWinConditions(), Player::GetAchievementMgr(), GetAlivePlayersCountByTeam(), GetBgMap(), GetStatus(), Player::GetTeam(), Map::GetVariableManager(), HORDE, IsArena(), Player::IsAtGroupRewardDistance(), m_players, AchievementMgr::ResetAchievementCriteria(), SCORE_DEATHS, SCORE_HONORABLE_KILLS, SCORE_KILLING_BLOWS, Object::SetFlag(), WorldStateVariableManager::SetVariable(), sObjectMgr, STATUS_IN_PROGRESS, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, UpdatePlayerScore(), WORLD_STATE_ARENA_COUNT_A, and WORLD_STATE_ARENA_COUNT_H.
Referenced by BattleGroundAV::HandleKillPlayer(), BattleGroundEY::HandleKillPlayer(), BattleGroundIC::HandleKillPlayer(), and BattleGroundWS::HandleKillPlayer().
HandleKillUnit()
virtual void BattleGround::HandleKillUnit (Creature * , Player *) inline virtual
Reimplemented in BattleGroundSA, BattleGroundIC, and BattleGroundAV.
Definition at line 564 of file BattleGround.h.
HandlePlayerClickedOnFlag()
virtual void BattleGround::HandlePlayerClickedOnFlag (Player * , GameObject *) inline virtual
Reimplemented in BattleGroundAV, BattleGroundWS, BattleGroundAB, BattleGroundSA, BattleGroundIC, and BattleGroundEY.
Definition at line 579 of file BattleGround.h.
HandlePlayerDroppedFlag()
virtual void BattleGround::HandlePlayerDroppedFlag (Player *) inline virtual
Reimplemented in BattleGroundWS, and BattleGroundEY.
Definition at line 576 of file BattleGround.h.
HandlePlayerUnderMap()
virtual bool BattleGround::HandlePlayerUnderMap (Player *) inline virtual
Reimplemented in BattleGroundRV, BattleGroundRL, BattleGroundNA, BattleGroundDS, and BattleGroundBE.
Definition at line 634 of file BattleGround.h.
HandleTriggerBuff()
void BattleGround::HandleTriggerBuff (ObjectGuid go_guid)
Method that handles buff triggering based on trap gameobjects.
Parameters
gameobject guid
Definition at line 2192 of file BattleGround.cpp.
References GAMEOBJECT_TYPE_TRAP, GetBgMap(), Map::GetGameObject(), GameObject::GetGoType(), GO_JUST_DEACTIVATED, GameObject::IsSpawned(), and GameObject::SetLootState().
HasFreeSlots()
bool BattleGround::HasFreeSlots () const inline
Definition at line 416 of file BattleGround.h.
References GetMaxPlayers(), and GetPlayersSize().
Referenced by BattleGroundQueue::Update().
IncreaseInvitedCount()
void BattleGround::IncreaseInvitedCount (Team team) inline
Definition at line 409 of file BattleGround.h.
References ALLIANCE, m_invitedAlliance, and m_invitedHorde.
Referenced by BattleGroundQueue::InviteGroupToBg().
IsActiveEvent()
bool BattleGround::IsActiveEvent (uint8 event1, uint8 event2) inline
Definition at line 604 of file BattleGround.h.
References m_activeEvents.
Referenced by OnObjectDBLoad(), and OpenDoorEvent().
IsArena()
bool BattleGround::IsArena () const inline
Definition at line 420 of file BattleGround.h.
References m_isArena.
Referenced by AddPlayer(), BattleGroundMgr::BuildPvpLogDataPacket(), Group::CanJoinBattleGroundQueue(), BattleGroundMgr::CreateNewBattleGround(), EndBattleGround(), EventPlayerLoggedOut(), BattleGroundMgr::GetBattleGroundThroughClientInstance(), SpellMgr::GetSpellAllowedInLocationError(), HandleKillPlayer(), WorldSession::HandlePVPLogDataOpcode(), Player::InArena(), BattleGroundQueue::InviteGroupToBg(), RemovePlayer(), RemovePlayerAtLeave(), Reset(), BattleGroundQueue::Update(), Update(), and AchievementMgr::UpdateAchievementCriteria().
IsBattleGround()
bool BattleGround::IsBattleGround () const inline
Definition at line 421 of file BattleGround.h.
References m_isArena.
Referenced by AddToBgFreeSlotQueue(), BattleGroundQueue::CheckNormalMatch(), EndBattleGround(), RemovePlayerAtLeave(), BattleGroundQueue::Update(), and UpdatePlayerScore().
IsConditionFulfilled()
virtual bool BattleGround::IsConditionFulfilled (Player const * , uint32 , WorldObject const * , uint32) inline virtual
Reimplemented in BattleGroundSA, and BattleGroundAV.
Definition at line 649 of file BattleGround.h.
IsDoorEvent()
bool BattleGround::IsDoorEvent (uint8 event1, uint8 event2) const
Function that checks if event handles doors.
Parameters
event1
event2
Definition at line 1920 of file BattleGround.cpp.
References BG_EVENT_DOOR, and sLog.
Referenced by OnObjectDBLoad(), and OpenDoorEvent().
IsPlayerInBattleGround()
bool BattleGround::IsPlayerInBattleGround (ObjectGuid guid)
Function that returns returns if player is in battleground.
Parameters
player objectguid
Definition at line 2273 of file BattleGround.cpp.
References m_players.
Referenced by Player::LoadFromDB().
IsRandom()
bool BattleGround::IsRandom () const inline
Definition at line 375 of file BattleGround.h.
References m_isRandom.
Referenced by EndBattleGround().
IsRated()
bool BattleGround::IsRated () const inline
Definition at line 422 of file BattleGround.h.
References m_isRated.
Referenced by BattleGroundMgr::BuildBattleGroundStatusPacket(), EndBattleGround(), BattleGroundQueue::InviteGroupToBg(), and RemovePlayerAtLeave().
ModifyStartDelayTime()
void BattleGround::ModifyStartDelayTime (int diff) inline
Definition at line 398 of file BattleGround.h.
References m_startDelayTime.
Referenced by Update().
OnObjectDBLoad() [1/2]
void BattleGround::OnObjectDBLoad (Creature * creature)
Function that handles creature load from DB event map.
Parameters
creature
Definition at line 1866 of file BattleGround.cpp.
References BG_EVENT_NONE, ChangeBgCreatureSpawnState(), BattleGroundEventIdx::event1, BattleGroundEventIdx::event2, Object::GetDbGuid(), IsActiveEvent(), m_eventObjects, MAKE_PAIR32, RESPAWN_ONE_DAY, and sBattleGroundMgr.
Referenced by LoadHelper().
OnObjectDBLoad() [2/2]
void BattleGround::OnObjectDBLoad (GameObject * obj)
Method that handles gameobject load from DB event map.
Parameters
gameobject
Definition at line 1897 of file BattleGround.cpp.
References BG_EVENT_NONE, ChangeBgObjectSpawnState(), DoorOpen(), BattleGroundEventIdx::event1, BattleGroundEventIdx::event2, Object::GetDbGuid(), Object::GetObjectGuid(), GetStatus(), IsActiveEvent(), IsDoorEvent(), m_eventObjects, MAKE_PAIR32, RESPAWN_ONE_DAY, sBattleGroundMgr, and STATUS_IN_PROGRESS.
OpenDoorEvent()
void BattleGround::OpenDoorEvent (uint8 event1, uint8 event2 = 0)
Method that handles door opening.
Parameters
event1
event2
Definition at line 1940 of file BattleGround.cpp.
References DoorOpen(), IsActiveEvent(), IsDoorEvent(), m_eventObjects, MAKE_PAIR32, and sLog.
Referenced by BattleGroundAB::StartingEventOpenDoors(), BattleGroundAV::StartingEventOpenDoors(), BattleGroundBE::StartingEventOpenDoors(), BattleGroundDS::StartingEventOpenDoors(), BattleGroundEY::StartingEventOpenDoors(), BattleGroundNA::StartingEventOpenDoors(), BattleGroundRL::StartingEventOpenDoors(), BattleGroundRV::StartingEventOpenDoors(), and BattleGroundWS::StartingEventOpenDoors().
PlayerAddedToBgCheckIfBgIsRunning()
void BattleGround::PlayerAddedToBgCheckIfBgIsRunning (Player * player) protected
Method that handles player added to battleground when battleground is in progress.
Parameters
player
Definition at line 2284 of file BattleGround.cpp.
References BattleGroundMgr::BgQueueTypeId(), BlockMovement(), GetArenaType(), Player::GetBattleGroundQueueIndex(), Player::GetBGTeam(), GetEndTime(), Player::GetSession(), GetStartTime(), GetStatus(), GetTypeId(), sBattleGroundMgr, WorldSession::SendPacket(), STATUS_IN_PROGRESS, and STATUS_WAIT_LEAVE.
Referenced by AddPlayer(), and EventPlayerLoggedIn().
PlaySoundToAll()
void BattleGround::PlaySoundToAll (uint32 soundId)
Method that plays sound to all players.
Parameters
sound Id
team
Definition at line 620 of file BattleGround.cpp.
References sBattleGroundMgr, and SendPacketToAll().
Referenced by BattleGroundAV::ChangeMineOwner(), BattleGroundIC::DoCaptureObjective(), BattleGroundSA::HandleEvent(), BattleGroundEY::HandlePlayerClickedOnFlag(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAV::ProcessPlayerAssaultsPoint(), BattleGroundAV::ProcessPlayerDefendsPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundEY::ProcessPlayerFlagScoreEvent(), BattleGroundWS::RespawnDroppedFlag(), BattleGroundWS::RespawnFlagAtBase(), BattleGroundEY::RespawnFlagAtCenter(), Update(), BattleGroundAB::Update(), and BattleGroundAV::UpdateScore().
PlaySoundToTeam()
void BattleGround::PlaySoundToTeam (uint32 soundId, Team teamId)
Method that plays sound to the given team.
Parameters
sound Id
team
Definition at line 633 of file BattleGround.cpp.
References ALLIANCE, Player::GetSession(), Player::GetTeam(), HORDE, m_players, sBattleGroundMgr, WorldSession::SendPacket(), sLog, and sObjectMgr.
Referenced by EndBattleGround(), and BattleGroundSA::ProcessBattlegroundWinner().
PSendMessageToAll()
void BattleGround::PSendMessageToAll (int32 entry, ChatMsg type, Player const * source, ...)
Method that sends message to all players.
Parameters
text entry
chat type
player
Definition at line 2114 of file BattleGround.cpp.
References BroadcastWorker().
Referenced by BattleGroundEY::HandlePlayerClickedOnFlag(), and Update().
RemoveFromBgFreeSlotQueue()
void BattleGround::RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
Definition at line 1726 of file BattleGround.cpp.
References GetInstanceId(), m_hasBgFreeSlotQueue, m_typeId, and sBattleGroundMgr.
Referenced by EndBattleGround(), EndNow(), BattleGroundQueue::Update(), and ~BattleGround().
RemovePlayer()
void BattleGround::RemovePlayer (Player * , ObjectGuid) protected virtual
Method that handles generic logic when removing a player.
used mainly for arena logic
Parameters
player
guid
Reimplemented in BattleGroundWS, and BattleGroundEY.
Definition at line 1695 of file BattleGround.cpp.
References ALLIANCE, CheckArenaWinConditions(), GetAlivePlayersCountByTeam(), GetBgMap(), GetStatus(), Map::GetVariableManager(), HORDE, IsArena(), WorldStateVariableManager::SetVariable(), STATUS_WAIT_LEAVE, WORLD_STATE_ARENA_COUNT_A, and WORLD_STATE_ARENA_COUNT_H.
Referenced by EventPlayerLoggedOut(), and RemovePlayerAtLeave().
RemovePlayerAtLeave()
void BattleGround::RemovePlayerAtLeave (ObjectGuid playerGuid, bool isOnTransport, bool doSendPacket) virtual
Method that handles player removal on leaving battleground.
Parameters
player guid
isOnTransport
send Packet update
Definition at line 1273 of file BattleGround.cpp.
References AddToBgFreeSlotQueue(), ALLIANCE, ARENA_TYPE_NONE, BATTLEGROUND_AA, BATTLEGROUND_TYPE_NONE, BattleGroundMgr::BgQueueTypeId(), Player::ClearAfkReports(), DecreaseInvitedCount(), DETAIL_LOG, GetArenaTeamIdForTeam(), GetArenaType(), Player::GetBattleGroundQueueIndex(), GetBgRaid(), GetBracketId(), WorldObject::GetName(), GetOtherTeam(), GetPlayerTeam(), ArenaTeam::GetRating(), Player::GetSession(), GetStatus(), Player::GetTeam(), GetTypeId(), Unit::HasAuraType(), HORDE, Unit::IsAlive(), IsArena(), IsBattleGround(), IsRated(), m_players, m_playerScores, ArenaTeam::MemberLost(), ArenaTeam::OfflineMemberLost(), PET_SAVE_NOT_IN_SLOT, Unit::RemoveArenaAuras(), Unit::RemoveAurasDueToSpell(), Player::RemoveBattleGroundQueueId(), Object::RemoveFlag(), Player::RemovePet(), RemovePlayer(), Unit::RemoveSpellsCausingAura(), Player::ResummonPetTemporaryUnSummonedIfAny(), Player::ResurrectPlayer(), sBattleGroundMgr, WorldSession::SendPacket(), SendPacketToTeam(), Player::SetBattleGroundId(), SetBgRaid(), Player::SetBGTeam(), sObjectMgr, Player::SpawnCorpseBones(), SPELL_ARENA_DAMPENING, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_MOUNTED, SPELL_AURA_SPIRIT_OF_REDEMPTION, SPELL_BATTLEGROUND_DAMPENING, STATUS_IN_PROGRESS, STATUS_NONE, STATUS_WAIT_JOIN, STATUS_WAIT_LEAVE, TEAM_NONE, Player::TeleportToBGEntryPoint(), UNIT_FIELD_FLAGS, UNIT_FLAG_CLIENT_CONTROL_LOST, and UpdatePlayersCountByTeam().
Referenced by Player::LoadFromDB(), and Update().
Reset()
void BattleGround::Reset () virtual
Method that is called when no players remains in battleground.
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundIC, BattleGroundEY, BattleGroundDS, BattleGroundAV, and BattleGroundAB.
Definition at line 1419 of file BattleGround.cpp.
References ARENA_BUFF_EVENT, ARENA_TYPE_NONE, BATTLEGROUND_BE, BATTLEGROUND_NA, BATTLEGROUND_RL, BG_EVENT_DOOR, BG_EVENT_NONE, GetBgMap(), GetTypeId(), Map::GetVariableManager(), IsArena(), m_activeEvents, m_arenaBuffSpawned, m_events, m_hasBgFreeSlotQueue, m_invitedAlliance, m_invitedHorde, m_players, m_playerScores, SetArenaType(), SetEndTime(), SetRated(), SetStartTime(), SetStatus(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), SetWinner(), sLog, STATUS_WAIT_QUEUE, WINNER_NONE, WORLD_STATE_ADD, WORLD_STATE_ARENA_BE_HUD_ENABLED, WORLD_STATE_ARENA_COUNT_A, WORLD_STATE_ARENA_COUNT_H, WORLD_STATE_ARENA_HUD_ENABLED, WORLD_STATE_ARENA_NA_HUD_ENABLED, and WORLD_STATE_ARENA_RL_HUD_ENABLED.
Referenced by BattleGroundMgr::CreateNewBattleGround(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundDS::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundSA::Reset(), and BattleGroundWS::Reset().
RewardHonorToTeam()
void BattleGround::RewardHonorToTeam (uint32 honor, Team teamId)
Method that rewards honor to team - called at the end of the battleground.
Parameters
honor
team
Definition at line 695 of file BattleGround.cpp.
References ALLIANCE, Player::GetTeam(), HORDE, m_players, SCORE_BONUS_HONOR, sLog, sObjectMgr, TEAM_NONE, and UpdatePlayerScore().
Referenced by BattleGroundEY::AddPoints(), BattleGroundSA::AwardBonusHonor(), BattleGroundAB::EndBattleGround(), BattleGroundAV::EndBattleGround(), BattleGroundEY::EndBattleGround(), BattleGroundIC::EndBattleGround(), BattleGroundSA::EndBattleGround(), BattleGroundWS::EndBattleGround(), BattleGroundAV::HandleKillUnit(), BattleGroundIC::HandleKillUnit(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundAB::Update(), and BattleGroundIC::Update().
RewardItem()
void BattleGround::RewardItem (Player * player, uint32 itemId, uint32 count)
Method that rewards item - called at the end of the battleground.
Parameters
player
mark
count
Definition at line 1147 of file BattleGround.cpp.
References Player::CanStoreNewItem(), EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, Unit::GetDummyAura(), NULL_BAG, NULL_SLOT, Player::SendNewItem(), SendRewardMarkByMail(), sLog, SPELL_AURA_PLAYER_INACTIVE, and Player::StoreNewItem().
RewardMark()
void BattleGround::RewardMark (Player * player, uint32 count)
Method that rewards battleground mark - called at the end of the battleground.
Parameters
player
count
Definition at line 1083 of file BattleGround.cpp.
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_SA, BATTLEGROUND_WS, GetTypeId(), ITEM_WINNER_COUNT, RewardSpellCast(), SPELL_AB_MARK_LOSER, SPELL_AB_MARK_WINNER, SPELL_AV_MARK_LOSER, SPELL_AV_MARK_WINNER, SPELL_SA_MARK_LOSER, SPELL_SA_MARK_WINNER, SPELL_WS_MARK_LOSER, and SPELL_WS_MARK_WINNER.
Referenced by EndBattleGround().
RewardQuestComplete()
void BattleGround::RewardQuestComplete (Player * player)
Method that rewards player quest complete - called at the end of the battleground.
Parameters
player
Definition at line 1216 of file BattleGround.cpp.
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_SA, BATTLEGROUND_WS, GetTypeId(), RewardSpellCast(), SPELL_AB_QUEST_REWARD_1, SPELL_AB_QUEST_REWARD_2, SPELL_AB_QUEST_REWARD_3, SPELL_AB_QUEST_REWARD_4, SPELL_AV_QUEST_REWARD_1, SPELL_AV_QUEST_REWARD_2, SPELL_AV_QUEST_REWARD_3, SPELL_EY_QUEST_REWARD_1, SPELL_EY_QUEST_REWARD_2, SPELL_IC_QUEST_REWARD, SPELL_SA_QUEST_REWARD, SPELL_WS_QUEST_REWARD_1, SPELL_WS_QUEST_REWARD_2, SPELL_WS_QUEST_REWARD_3, SPELL_WS_QUEST_REWARD_4, and SPELL_WS_QUEST_REWARD_5.
Referenced by EndBattleGround().
RewardReputationToTeam()
void BattleGround::RewardReputationToTeam (uint32 factionId, uint32 reputation, Team teamId)
Method that rewards reputation to team - called at the end of the battleground.
Parameters
faction Id
reputation
team
Definition at line 728 of file BattleGround.cpp.
References ALLIANCE, Player::GetReputationMgr(), Player::GetTeam(), HORDE, m_players, ReputationMgr::ModifyReputation(), sFactionStore, sLog, and sObjectMgr.
Referenced by BattleGroundAV::EndBattleGround(), BattleGroundAV::HandleKillUnit(), BattleGroundAV::HandleQuestComplete(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), and BattleGroundAB::Update().
RewardSpellCast()
void BattleGround::RewardSpellCast (Player * player, uint32 spellId) const
Method that rewards spell cast - called at the end of the battleground.
Parameters
player
spellId
Definition at line 1124 of file BattleGround.cpp.
References Unit::CastSpell(), Unit::GetDummyAura(), SQLStorage::LookupEntry(), sLog, SPELL_AURA_PLAYER_INACTIVE, sSpellTemplate, and TRIGGERED_OLD_TRIGGERED.
Referenced by RewardMark(), and RewardQuestComplete().
SendBcdToAll()
void BattleGround::SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const * source)
Definition at line 2158 of file BattleGround.cpp.
References BroadcastWorker(), and sObjectMgr.
Referenced by BattleGroundAV::EndBattleGround().
SendBcdToTeam()
void BattleGround::SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const * source, Team team)
Definition at line 2165 of file BattleGround.cpp.
References BroadcastWorker(), and sObjectMgr.
Referenced by BattleGroundAV::Update().
SendMessage2ToAll()
void BattleGround::SendMessage2ToAll (int32 entry, ChatMsg type, Player const * source, int32 arg1 = 0, int32 arg2 = 0)
Method that sends message to all players.
Parameters
text entry
chat type
player source
arg1
arg2
Definition at line 2135 of file BattleGround.cpp.
References BroadcastWorker().
Referenced by BattleGroundIC::DoCaptureObjective(), BattleGroundIC::HandleEvent(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), and BattleGroundAB::Update().
SendMessageToAll() [1/2]
void BattleGround::SendMessageToAll (int32 entry, ChatMsg type, Player const * source = nullptr)
Method that sends message to all players.
Parameters
text entry
chat type
player source
Definition at line 2067 of file BattleGround.cpp.
References BroadcastWorker().
Referenced by EndBattleGround(), BattleGroundEY::HandlePlayerDroppedFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundEY::ProcessPlayerFlagScoreEvent(), BattleGroundWS::RespawnDroppedFlag(), BattleGroundWS::RespawnFlagAtBase(), BattleGroundEY::RespawnFlagAtCenter(), BattleGroundSA::SendBattlegroundWarning(), Update(), BattleGroundAB::Update(), BattleGroundSA::Update(), and BattleGroundAV::UpdateScore().
SendMessageToAll() [2/2]
void BattleGround::SendMessageToAll (int32 entry, ChatMsg type, uint32 language, ObjectGuid guid)
Method that sends message to all players.
Parameters
text entry
chat type
language
creature source
Definition at line 2096 of file BattleGround.cpp.
References BroadcastWorker(), GetBgMap(), and Map::GetCreature().
SendPacketToAll()
void BattleGround::SendPacketToAll (WorldPacket const & packet)
Method that sends packet to all players.
Parameters
packet
Definition at line 567 of file BattleGround.cpp.
References m_players, sLog, and sObjectMgr.
Referenced by PlaySoundToAll(), and UpdateWorldState().
SendPacketToTeam()
void BattleGround::SendPacketToTeam (Team teamId, WorldPacket const & packet, Player * sender = nullptr, bool toSelf = true)
Method that sends packet to the team.
Parameters
team Id
packet
sender
self
Definition at line 589 of file BattleGround.cpp.
References ALLIANCE, Player::GetSession(), Player::GetTeam(), HORDE, m_players, WorldSession::SendPacket(), sLog, and sObjectMgr.
Referenced by AddPlayer(), and RemovePlayerAtLeave().
SendRewardMarkByMail()
void BattleGround::SendRewardMarkByMail (Player * player, uint32 mark, uint32 count) const
Method that sends reward by mail - called at the end of the battleground.
Parameters
player
mark
count
Definition at line 1181 of file BattleGround.cpp.
References MailDraft::AddItem(), Item::CreateItem(), GetBattlemasterEntry(), ObjectMgr::GetItemPrototype(), WorldSession::GetMangosString(), GetName(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), ItemPrototype::ItemId, LANG_BG_MARK_BY_MAIL, MAIL_CREATURE, ItemPrototype::Name1, MailDraft::SendMailTo(), and sObjectMgr.
Referenced by RewardItem().
SendYell2ToAll()
void BattleGround::SendYell2ToAll (int32 entry, uint32 language, Creature const * source, int32 arg1, int32 arg2)
Method that sends yell to all players.
Parameters
text entry
language
creature source
arg1
arg2
Definition at line 2151 of file BattleGround.cpp.
References BroadcastWorker().
Referenced by BattleGroundAV::DoSendYellToTeam().
SendYellToAll()
void BattleGround::SendYellToAll (int32 entry, uint32 language, Creature const * source)
Method that sends yell to all players.
Parameters
text entry
language
creature source
Definition at line 2081 of file BattleGround.cpp.
References BroadcastWorker().
Referenced by BattleGroundAV::DoSendYellToTeam().
SetArenaorBGType()
void BattleGround::SetArenaorBGType (bool isArena) inline
Definition at line 394 of file BattleGround.h.
References m_isArena.
Referenced by BattleGroundMgr::CreateBattleGround().
SetArenaTeamIdForTeam()
void BattleGround::SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId) inline
Definition at line 549 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_arenaTeamIds.
Referenced by BattleGroundQueue::InviteGroupToBg().
SetArenaTeamRatingChangeForTeam()
void BattleGround::SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange) inline
Definition at line 551 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_arenaTeamRatingChanges.
Referenced by EndBattleGround().
SetArenaType()
void BattleGround::SetArenaType (ArenaType type) inline
Definition at line 393 of file BattleGround.h.
References m_arenaType.
Referenced by BattleGroundMgr::CreateNewBattleGround(), and Reset().
SetBgMap()
void BattleGround::SetBgMap (BattleGroundMap * map) inline
Definition at line 448 of file BattleGround.h.
References m_bgMap.
Referenced by MapManager::CreateBattleGroundMap().
SetBgRaid()
void BattleGround::SetBgRaid (Team team, Group * bgRaid)
Method that sets battleground group as raid.
Parameters
team
battleground raid
Definition at line 2338 of file BattleGround.cpp.
References GetTeamIndexByTeamId(), m_bgRaids, and Group::SetBattlegroundGroup().
Referenced by AddOrSetPlayerToCorrectBgGroup(), RemovePlayerAtLeave(), and Group::~Group().
SetBracket()
void BattleGround::SetBracket (PvPDifficultyEntry const * bracketEntry)
Method that sets the battleground bracket.
Parameters
bracket entry
Definition at line 2356 of file BattleGround.cpp.
References PvPDifficultyEntry::GetBracketId(), m_bracketId, PvPDifficultyEntry::maxLevel, PvPDifficultyEntry::minLevel, and SetLevelRange().
Referenced by BattleGroundMgr::CreateNewBattleGround().
SetClientInstanceId()
void BattleGround::SetClientInstanceId (uint32 instanceId) inline
Definition at line 386 of file BattleGround.h.
References m_clientInstanceId.
Referenced by BattleGroundMgr::CreateNewBattleGround().
SetEndTime()
void BattleGround::SetEndTime (uint32 time) inline
Definition at line 388 of file BattleGround.h.
References m_endTime.
Referenced by EndNow(), and Reset().
SetLevelRange()
void BattleGround::SetLevelRange (uint32 min, uint32 max) inline
Definition at line 391 of file BattleGround.h.
References m_levelMax, and m_levelMin.
Referenced by BattleGroundMgr::CreateBattleGround(), and SetBracket().
SetMapId()
void BattleGround::SetMapId (uint32 mapId) inline
Definition at line 444 of file BattleGround.h.
References m_mapId.
Referenced by BattleGroundMgr::CreateBattleGround().
SetMaxPlayers()
void BattleGround::SetMaxPlayers (uint32 maxPlayers) inline
Definition at line 389 of file BattleGround.h.
References m_maxPlayers.
Referenced by BattleGroundMgr::CreateBattleGround().
SetMaxPlayersPerTeam()
void BattleGround::SetMaxPlayersPerTeam (uint32 maxPlayers) inline
Definition at line 401 of file BattleGround.h.
References m_maxPlayersPerTeam.
Referenced by BattleGroundMgr::CreateBattleGround().
SetMinPlayers()
void BattleGround::SetMinPlayers (uint32 minPlayers) inline
Definition at line 390 of file BattleGround.h.
References m_minPlayers.
Referenced by BattleGroundMgr::CreateBattleGround().
SetMinPlayersPerTeam()
void BattleGround::SetMinPlayersPerTeam (uint32 minPlayers) inline
Definition at line 402 of file BattleGround.h.
References m_minPlayersPerTeam.
Referenced by BattleGroundMgr::CreateBattleGround().
SetName()
void BattleGround::SetName (char const * name) inline
Definition at line 380 of file BattleGround.h.
References m_name.
Referenced by BattleGroundMgr::CreateBattleGround().
SetPlayerSkinRefLootId()
void BattleGround::SetPlayerSkinRefLootId (uint32 reflootId) inline
Definition at line 673 of file BattleGround.h.
References m_playerSkinReflootId.
Referenced by BattleGroundMgr::CreateBattleGround().
SetRandom()
void BattleGround::SetRandom (bool isRandom) inline
Definition at line 396 of file BattleGround.h.
References m_isRandom.
Referenced by BattleGroundMgr::CreateNewBattleGround().
SetRandomTypeId()
void BattleGround::SetRandomTypeId (BattleGroundTypeId typeId) inline
Definition at line 382 of file BattleGround.h.
References m_randomTypeId.
Referenced by BattleGroundMgr::CreateNewBattleGround().
SetRated()
void BattleGround::SetRated (bool state) inline
Definition at line 392 of file BattleGround.h.
References m_isRated.
Referenced by BattleGroundMgr::CreateNewBattleGround(), WorldSession::HandleBattlemasterJoinArena(), and Reset().
SetStartDelayTime()
void BattleGround::SetStartDelayTime (int time) inline
Definition at line 399 of file BattleGround.h.
References m_startDelayTime.
Referenced by ChatHandler::HandleBattlegroundStartCommand(), and Update().
SetStartMaxDist()
void BattleGround::SetStartMaxDist (float startMaxDist) inline
Definition at line 466 of file BattleGround.h.
References m_startMaxDist.
Referenced by BattleGroundMgr::CreateBattleGround().
SetStartTime()
void BattleGround::SetStartTime (uint32 time) inline
Definition at line 387 of file BattleGround.h.
References m_startTime.
Referenced by Reset(), and StartBattleGround().
SetStatus()
void BattleGround::SetStatus (BattleGroundStatus status) inline
Definition at line 385 of file BattleGround.h.
References m_status.
Referenced by BattleGroundMgr::CreateNewBattleGround(), EndBattleGround(), EndNow(), Reset(), and Update().
SetTeamStartLoc()
void BattleGround::SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
Parameters
team Id
x
y
z
o
Definition at line 553 of file BattleGround.cpp.
References GetTeamIndexByTeamId(), m_teamStartLocO, m_teamStartLocX, m_teamStartLocY, and m_teamStartLocZ.
Referenced by BattleGroundMgr::CreateBattleGround().
SetTypeId()
void BattleGround::SetTypeId (BattleGroundTypeId typeId) inline
Definition at line 381 of file BattleGround.h.
References m_typeId.
Referenced by BattleGroundMgr::CreateBattleGround(), and BattleGroundMgr::CreateNewBattleGround().
SetWinner()
void BattleGround::SetWinner (BattleGroundWinner winner) inline
Definition at line 395 of file BattleGround.h.
References m_winner.
Referenced by EndBattleGround(), and Reset().
SpawnEvent()
void BattleGround::SpawnEvent (uint8 event1, uint8 event2, bool spawn)
Method that handles event spawn.
Parameters
event1
event2
spawn
Definition at line 1965 of file BattleGround.cpp.
References BG_EVENT_NONE, ChangeBgCreatureSpawnState(), ChangeBgObjectSpawnState(), m_activeEvents, m_eventObjects, MAKE_PAIR32, RESPAWN_IMMEDIATELY, and RESPAWN_ONE_DAY.
Referenced by BattleGroundAV::ChangeMineOwner(), BattleGroundAB::DoUpdateBanner(), BattleGroundAV::HandleKillUnit(), BattleGroundAV::PopulateNode(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundEY::ProcessPlayerFlagScoreEvent(), BattleGroundWS::RespawnFlagAtBase(), BattleGroundEY::RespawnFlagAtCenter(), BattleGroundWS::StartingEventOpenDoors(), and Update().
StartBattleGround()
void BattleGround::StartBattleGround ()
Method that starts the battleground.
Definition at line 1483 of file BattleGround.cpp.
References AddToBgFreeSlotQueue(), GetInstanceId(), GetTypeId(), sBattleGroundMgr, and SetStartTime().
Referenced by BattleGroundQueue::Update().
StartingEventCloseDoors()
virtual void BattleGround::StartingEventCloseDoors () inline virtual
Definition at line 348 of file BattleGround.h.
Referenced by Update().
StartingEventOpenDoors()
virtual void BattleGround::StartingEventOpenDoors () inline virtual
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundRV, BattleGroundRL, BattleGroundNA, BattleGroundIC, BattleGroundEY, BattleGroundDS, BattleGroundBE, BattleGroundAV, and BattleGroundAB.
Definition at line 349 of file BattleGround.h.
Referenced by Update().
StartTimedAchievement()
void BattleGround::StartTimedAchievement (AchievementCriteriaTypes type, uint32 entry)
Method that starts timed achievements for all battleground players.
Parameters
achiev criteria type
entry
Definition at line 1502 of file BattleGround.cpp.
References GetBgMap(), and GetPlayers().
Referenced by BattleGroundAB::StartingEventOpenDoors(), BattleGroundAV::StartingEventOpenDoors(), BattleGroundEY::StartingEventOpenDoors(), BattleGroundSA::StartingEventOpenDoors(), BattleGroundWS::StartingEventOpenDoors(), and BattleGroundSA::Update().
Update()
void BattleGround::Update (uint32 diff) virtual
Update method.
Parameters
diff
Reimplemented in BattleGroundRV, BattleGroundDS, BattleGroundWS, BattleGroundSA, BattleGroundIC, BattleGroundEY, BattleGroundAV, and BattleGroundAB.
Definition at line 317 of file BattleGround.cpp.
References ALLIANCE, ARENA_BUFF_EVENT, ARENA_FORCED_DRAW, ARENA_SPAWN_BUFF_OBJECTS, AT_LOGIN_ADD_BG_DESERTER, BG_STARTING_EVENT_1, BG_STARTING_EVENT_2, BG_STARTING_EVENT_3, BG_STARTING_EVENT_4, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, CharacterDatabase, CHAT_MSG_BG_SYSTEM_NEUTRAL, CHAT_MSG_SYSTEM, CHECK_PLAYER_POSITION_INVERVAL, CheckArenaWinConditions(), CONFIG_BOOL_BATTLEGROUND_QUEUE_ANNOUNCER_START, EndBattleGround(), GetArenaType(), GetBracketId(), GetInvitedCount(), GetMapId(), GetMaxLevel(), GetMinLevel(), GetMinPlayersPerTeam(), GetName(), GetPlayers(), GetPlayersCountByTeam(), GetPlayersSize(), GetPrematureWinner(), GetStartDelayTime(), GetStartMaxDist(), GetStatus(), GetTeamStartLoc(), GetTypeId(), HORDE, IN_MILLISECONDS, IsArena(), LANG_ARENA_STARTED_ANNOUNCE_WORLD, LANG_BATTLEGROUND_PREMATURE_FINISH_WARNING, LANG_BATTLEGROUND_PREMATURE_FINISH_WARNING_SECS, LANG_BG_STARTED_ANNOUNCE_WORLD, m_arenaBuffSpawned, m_endTime, m_events, m_offlineQueue, m_players, m_prematureCountDown, m_prematureCountDownTimer, m_startDelayTimes, m_startMessageIds, m_startTime, m_validStartPositionTimer, MINUTE, ModifyStartDelayTime(), Database::PExecute(), PlaySoundToAll(), PSendMessageToAll(), RemovePlayerAtLeave(), sBattleGroundMgr, SendMessageToAll(), SetStartDelayTime(), SetStatus(), sObjectMgr, SOUND_BG_START, SpawnEvent(), SPELL_ARENA_PREPARATION, SPELL_ATTR_EX5_REMOVE_ENTERING_ARENA, SPELL_PREPARATION, StartingEventCloseDoors(), StartingEventOpenDoors(), STATUS_IN_PROGRESS, STATUS_WAIT_JOIN, STATUS_WAIT_LEAVE, sWorld, and TEAM_NONE.
Referenced by BattleGroundMap::Update(), BattleGroundAB::Update(), BattleGroundAV::Update(), BattleGroundEY::Update(), BattleGroundIC::Update(), BattleGroundSA::Update(), BattleGroundWS::Update(), BattleGroundDS::Update(), and BattleGroundRV::Update().
UpdatePlayerScore()
void BattleGround::UpdatePlayerScore (Player * player, uint32 type, uint32 value) virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented in BattleGroundWS, BattleGroundSA, BattleGroundIC, BattleGroundEY, BattleGroundAV, and BattleGroundAB.
Definition at line 1763 of file BattleGround.cpp.
References Object::GetObjectGuid(), IsBattleGround(), m_playerScores, Player::RewardHonor(), SCORE_BONUS_HONOR, SCORE_DAMAGE_DONE, SCORE_DEATHS, SCORE_HEALING_DONE, SCORE_HONORABLE_KILLS, SCORE_KILLING_BLOWS, and sLog.
Referenced by EndBattleGround(), HandleKillPlayer(), RewardHonorToTeam(), BattleGroundAB::UpdatePlayerScore(), BattleGroundAV::UpdatePlayerScore(), BattleGroundEY::UpdatePlayerScore(), BattleGroundIC::UpdatePlayerScore(), BattleGroundSA::UpdatePlayerScore(), and BattleGroundWS::UpdatePlayerScore().
UpdatePlayersCountByTeam()
void BattleGround::UpdatePlayersCountByTeam (Team team, bool remove) inline
Definition at line 540 of file BattleGround.h.
References GetTeamIndexByTeamId(), and m_playersCount.
Referenced by AddPlayer(), and RemovePlayerAtLeave().
UpdateWorldState()
void BattleGround::UpdateWorldState (uint32 field, uint32 value)
Method that updates world state for all players.
Parameters
field
value
Definition at line 762 of file BattleGround.cpp.
References sBattleGroundMgr, and SendPacketToAll().
UpdateWorldStateForPlayer()
void BattleGround::UpdateWorldStateForPlayer (uint32 field, uint32 value, Player * player) const
Method that updates world state for a give player.
Parameters
field
value
player
Definition at line 776 of file BattleGround.cpp.
References Player::GetSession(), sBattleGroundMgr, and WorldSession::SendPacket().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 336 of file BattleGround.h.
Field Documentation
m_activeEvents
std::map<uint8, uint8> BattleGround::m_activeEvents
Definition at line 670 of file BattleGround.h.
Referenced by BattleGroundAV::InitializeNode(), IsActiveEvent(), Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundWS::Reset(), and SpawnEvent().
m_arenaBuffSpawned
bool BattleGround::m_arenaBuffSpawned private
Definition at line 721 of file BattleGround.h.
Referenced by Reset(), and Update().
m_arenaTeamIds
uint32 BattleGround::m_arenaTeamIds[PVP_TEAM_COUNT] private
Definition at line 746 of file BattleGround.h.
Referenced by BattleGround(), BattleGroundMgr::BuildPvpLogDataPacket(), GetArenaTeamIdForTeam(), and SetArenaTeamIdForTeam().
m_arenaTeamRatingChanges
int32 BattleGround::m_arenaTeamRatingChanges[PVP_TEAM_COUNT] private
Definition at line 748 of file BattleGround.h.
Referenced by BattleGround(), BattleGroundMgr::BuildPvpLogDataPacket(), GetArenaTeamRatingChangeForTeam(), and SetArenaTeamRatingChangeForTeam().
m_arenaType
ArenaType BattleGround::m_arenaType private
Definition at line 711 of file BattleGround.h.
Referenced by BattleGround(), GetArenaType(), and SetArenaType().
m_bgMap
BattleGroundMap* BattleGround::m_bgMap private
Definition at line 760 of file BattleGround.h.
Referenced by BattleGround(), GetBgMap(), GetInstanceId(), SetBgMap(), and ~BattleGround().
m_bgRaids
Group* BattleGround::m_bgRaids[PVP_TEAM_COUNT] private
Definition at line 740 of file BattleGround.h.
Referenced by BattleGround(), GetBgRaid(), and SetBgRaid().
m_bracketId
BattleGroundBracketId BattleGround::m_bracketId private
Definition at line 710 of file BattleGround.h.
Referenced by BattleGround(), GetBracketId(), and SetBracket().
m_buffChange
bool BattleGround::m_buffChange protected
Definition at line 698 of file BattleGround.h.
m_clientInstanceId
uint32 BattleGround::m_clientInstanceId private
Definition at line 714 of file BattleGround.h.
Referenced by BattleGround(), GetClientInstanceId(), and SetClientInstanceId().
m_endTime
int32 BattleGround::m_endTime private
Definition at line 718 of file BattleGround.h.
Referenced by BattleGround(), EndBattleGround(), GetEndTime(), SetEndTime(), and Update().
m_eventObjects
std::map<uint32, EventObjects> BattleGround::m_eventObjects
Definition at line 666 of file BattleGround.h.
Referenced by GetSingleCreatureGuid(), OnObjectDBLoad(), OpenDoorEvent(), and SpawnEvent().
m_events
uint8 BattleGround::m_events protected
Definition at line 693 of file BattleGround.h.
Referenced by BattleGround(), Reset(), and Update().
m_goEntryGuidStore
EntryGuidMap BattleGround::m_goEntryGuidStore protected
Definition at line 702 of file BattleGround.h.
Referenced by GetSingleGameObjectFromStorage(), BattleGroundAV::HandleGameObjectCreate(), BattleGroundAB::HandleGameObjectCreate(), BattleGroundIC::HandleGameObjectCreate(), and BattleGroundSA::HandleGameObjectCreate().
m_hasBgFreeSlotQueue
bool BattleGround::m_hasBgFreeSlotQueue private
Definition at line 722 of file BattleGround.h.
Referenced by AddToBgFreeSlotQueue(), BattleGround(), RemoveFromBgFreeSlotQueue(), and Reset().
m_invitedAlliance
uint32 BattleGround::m_invitedAlliance private
Definition at line 736 of file BattleGround.h.
Referenced by BattleGround(), DecreaseInvitedCount(), GetInvitedCount(), IncreaseInvitedCount(), and Reset().
m_invitedHorde
uint32 BattleGround::m_invitedHorde private
Definition at line 737 of file BattleGround.h.
Referenced by BattleGround(), DecreaseInvitedCount(), GetInvitedCount(), IncreaseInvitedCount(), and Reset().
m_isArena
bool BattleGround::m_isArena private
Definition at line 725 of file BattleGround.h.
Referenced by BattleGround(), IsArena(), IsBattleGround(), and SetArenaorBGType().
m_isRandom
bool BattleGround::m_isRandom protected
Definition at line 699 of file BattleGround.h.
Referenced by BattleGround(), IsRandom(), and SetRandom().
m_isRated
bool BattleGround::m_isRated private
Definition at line 723 of file BattleGround.h.
Referenced by BattleGround(), IsRated(), and SetRated().
m_levelMax
uint32 BattleGround::m_levelMax private
Definition at line 752 of file BattleGround.h.
Referenced by BattleGround(), GetMaxLevel(), and SetLevelRange().
m_levelMin
uint32 BattleGround::m_levelMin private
Definition at line 751 of file BattleGround.h.
Referenced by BattleGround(), GetMinLevel(), and SetLevelRange().
m_mapId
uint32 BattleGround::m_mapId private
Definition at line 759 of file BattleGround.h.
Referenced by BattleGround(), GetMapId(), and SetMapId().
m_maxPlayers
uint32 BattleGround::m_maxPlayers private
Definition at line 754 of file BattleGround.h.
Referenced by BattleGround(), GetMaxPlayers(), and SetMaxPlayers().
m_maxPlayersPerTeam
uint32 BattleGround::m_maxPlayersPerTeam private
Definition at line 753 of file BattleGround.h.
Referenced by BattleGround(), GetMaxPlayersPerTeam(), and SetMaxPlayersPerTeam().
m_minPlayers
uint32 BattleGround::m_minPlayers private
Definition at line 756 of file BattleGround.h.
Referenced by BattleGround(), GetMinPlayers(), and SetMinPlayers().
m_minPlayersPerTeam
uint32 BattleGround::m_minPlayersPerTeam private
Definition at line 755 of file BattleGround.h.
Referenced by BattleGround(), GetMinPlayersPerTeam(), and SetMinPlayersPerTeam().
m_name
char const* BattleGround::m_name private
Definition at line 727 of file BattleGround.h.
Referenced by BattleGround(), GetName(), and SetName().
m_npcEntryGuidStore
EntryGuidMap BattleGround::m_npcEntryGuidStore protected
Definition at line 703 of file BattleGround.h.
Referenced by GetSingleCreatureFromStorage(), and BattleGroundAV::HandleCreatureCreate().
m_offlineQueue
OfflineQueue BattleGround::m_offlineQueue private
Definition at line 731 of file BattleGround.h.
Referenced by EventPlayerLoggedIn(), EventPlayerLoggedOut(), and Update().
m_players
BattleGroundPlayerMap BattleGround::m_players protected
Definition at line 688 of file BattleGround.h.
Referenced by AddPlayer(), BroadcastWorker(), CastSpellOnTeam(), BattleGroundAV::ChangeMineOwner(), BattleGroundIC::DoApplyTeamBuff(), EndBattleGround(), EventPlayerLoggedIn(), EventPlayerLoggedOut(), GetAlivePlayersCountByTeam(), GetPlayers(), GetPlayersSize(), GetPlayerTeam(), HandleKillPlayer(), IsPlayerInBattleGround(), PlaySoundToTeam(), RemovePlayerAtLeave(), Reset(), RewardHonorToTeam(), RewardReputationToTeam(), SendPacketToAll(), SendPacketToTeam(), Update(), and BattleGroundSA::Update().
m_playerScores
BattleGroundScoreMap BattleGround::m_playerScores protected
Definition at line 682 of file BattleGround.h.
Referenced by AddPlayer(), BattleGroundAB::AddPlayer(), BattleGroundAV::AddPlayer(), BattleGroundEY::AddPlayer(), BattleGroundSA::AddPlayer(), BattleGroundWS::AddPlayer(), BattleGroundIC::AddPlayer(), EndBattleGround(), GetPlayerScoresBegin(), GetPlayerScoresEnd(), GetPlayerScoresSize(), RemovePlayerAtLeave(), Reset(), UpdatePlayerScore(), BattleGroundAB::UpdatePlayerScore(), BattleGroundAV::UpdatePlayerScore(), BattleGroundEY::UpdatePlayerScore(), BattleGroundIC::UpdatePlayerScore(), BattleGroundSA::UpdatePlayerScore(), BattleGroundWS::UpdatePlayerScore(), and ~BattleGround().
m_playersCount
uint32 BattleGround::m_playersCount[PVP_TEAM_COUNT] private
Definition at line 743 of file BattleGround.h.
Referenced by BattleGround(), GetPlayersCountByTeam(), and UpdatePlayersCountByTeam().
m_playerSkinReflootId
uint32 BattleGround::m_playerSkinReflootId private
Definition at line 767 of file BattleGround.h.
Referenced by GetPlayerSkinRefLootId(), and SetPlayerSkinRefLootId().
m_prematureCountDown
bool BattleGround::m_prematureCountDown private
Definition at line 724 of file BattleGround.h.
Referenced by BattleGround(), and Update().
m_prematureCountDownTimer
uint32 BattleGround::m_prematureCountDownTimer private
Definition at line 717 of file BattleGround.h.
Referenced by BattleGround(), and Update().
m_randomTypeId
BattleGroundTypeId BattleGround::m_randomTypeId private
Definition at line 708 of file BattleGround.h.
Referenced by BattleGround(), GetTypeId(), and SetRandomTypeId().
m_startDelayTime
int32 BattleGround::m_startDelayTime private
Definition at line 719 of file BattleGround.h.
Referenced by GetStartDelayTime(), ModifyStartDelayTime(), and SetStartDelayTime().
m_startDelayTimes
BattleGroundStartTimeIntervals BattleGround::m_startDelayTimes[BG_STARTING_EVENT_COUNT] protected
Definition at line 694 of file BattleGround.h.
Referenced by BattleGround(), BattleGroundBE::BattleGroundBE(), BattleGroundDS::BattleGroundDS(), BattleGroundNA::BattleGroundNA(), BattleGroundRL::BattleGroundRL(), BattleGroundRV::BattleGroundRV(), and Update().
m_startMaxDist
float BattleGround::m_startMaxDist private
Definition at line 765 of file BattleGround.h.
Referenced by GetStartMaxDist(), and SetStartMaxDist().
m_startMessageIds
uint32 BattleGround::m_startMessageIds[BG_STARTING_EVENT_COUNT] protected
Definition at line 696 of file BattleGround.h.
Referenced by BattleGround(), BattleGroundAB::BattleGroundAB(), BattleGroundAV::BattleGroundAV(), BattleGroundBE::BattleGroundBE(), BattleGroundDS::BattleGroundDS(), BattleGroundEY::BattleGroundEY(), BattleGroundIC::BattleGroundIC(), BattleGroundNA::BattleGroundNA(), BattleGroundRL::BattleGroundRL(), BattleGroundRV::BattleGroundRV(), BattleGroundSA::BattleGroundSA(), BattleGroundWS::BattleGroundWS(), and Update().
m_startTime
uint32 BattleGround::m_startTime private
Definition at line 715 of file BattleGround.h.
Referenced by BattleGround(), GetStartTime(), SetStartTime(), and Update().
m_status
BattleGroundStatus BattleGround::m_status private
Definition at line 709 of file BattleGround.h.
Referenced by BattleGround(), GetStatus(), and SetStatus().
m_teamStartLocO
float BattleGround::m_teamStartLocO[PVP_TEAM_COUNT] private
Definition at line 764 of file BattleGround.h.
Referenced by BattleGround(), GetTeamStartLoc(), and SetTeamStartLoc().
m_teamStartLocX
float BattleGround::m_teamStartLocX[PVP_TEAM_COUNT] private
Definition at line 761 of file BattleGround.h.
Referenced by BattleGround(), GetTeamStartLoc(), and SetTeamStartLoc().
m_teamStartLocY
float BattleGround::m_teamStartLocY[PVP_TEAM_COUNT] private
Definition at line 762 of file BattleGround.h.
Referenced by BattleGround(), GetTeamStartLoc(), and SetTeamStartLoc().
m_teamStartLocZ
float BattleGround::m_teamStartLocZ[PVP_TEAM_COUNT] private
Definition at line 763 of file BattleGround.h.
Referenced by BattleGround(), GetTeamStartLoc(), and SetTeamStartLoc().
m_typeId
BattleGroundTypeId BattleGround::m_typeId private
Definition at line 707 of file BattleGround.h.
Referenced by AddToBgFreeSlotQueue(), BattleGround(), GetTypeId(), RemoveFromBgFreeSlotQueue(), and SetTypeId().
m_validStartPositionTimer
uint32 BattleGround::m_validStartPositionTimer private
Definition at line 716 of file BattleGround.h.
Referenced by BattleGround(), and Update().
m_winner
BattleGroundWinner BattleGround::m_winner private
Definition at line 712 of file BattleGround.h.
Referenced by BattleGround(), GetWinner(), and SetWinner().
The documentation for this class was generated from the following files:
BattleGround.h
BattleGround.cpp