CMaNGOS_WoTLK: Aura Class Reference
Aura Class Reference
#include <SpellAuras.h>
Public Member Functions
void HandleNULL (bool, bool)
void HandleUnused (bool, bool)
void HandleNoImmediateEffect (bool, bool)
void HandleBindSight (bool apply, bool Real)
void HandleModPossess (bool apply, bool Real)
void HandlePeriodicDamage (bool apply, bool Real)
void HandleAuraDummy (bool apply, bool Real)
void HandleAuraPeriodicDummy (bool apply, bool Real)
void HandleModConfuse (bool apply, bool Real)
void HandleModCharm (bool apply, bool Real)
void HandleModFear (bool apply, bool Real)
void HandlePeriodicHeal (bool apply, bool Real)
void HandleModAttackSpeed (bool apply, bool Real)
void HandleModMeleeRangedSpeedPct (bool apply, bool Real)
void HandleModCombatSpeedPct (bool apply, bool Real)
void HandleModThreat (bool apply, bool Real)
void HandleModTaunt (bool Apply, bool Real)
void HandleFeignDeath (bool apply, bool Real)
void HandleAuraModDisarm (bool apply, bool Real)
void HandleAuraModStalked (bool apply, bool Real)
void HandleAuraWaterWalk (bool apply, bool Real)
void HandleAuraFeatherFall (bool apply, bool Real)
void HandleAuraHover (bool apply, bool Real)
void HandleAddModifier (bool apply, bool Real)
void HandleAuraModStun (bool apply, bool Real)
void HandleModDamageDone (bool apply, bool Real)
void HandleAuraDamageShield (bool apply, bool real)
void HandleAuraUntrackable (bool apply, bool Real)
void HandleAuraEmpathy (bool apply, bool Real)
void HandleModOffhandDamagePercent (bool apply, bool Real)
void HandleAuraModRangedAttackPower (bool apply, bool Real)
void HandleAuraModIncreaseEnergyPercent (bool apply, bool Real)
void HandleAuraModIncreaseHealthPercent (bool apply, bool Real)
void HandleAuraModRegenInterrupt (bool apply, bool Real)
void HandleModMeleeSpeedPct (bool apply, bool Real)
void HandlePeriodicTriggerSpell (bool apply, bool Real)
void HandlePeriodicTriggerSpellWithValue (bool apply, bool Real)
void HandlePeriodicEnergize (bool apply, bool Real)
void HandleAuraModResistanceExclusive (bool apply, bool Real)
void HandleAuraSafeFall (bool Apply, bool Real)
void HandleAuraModPetTalentsPoints (bool Apply, bool Real)
void HandleModStealth (bool apply, bool Real)
void HandleModStealthDetect (bool apply, bool real)
void HandleInvisibility (bool apply, bool Real)
void HandleInvisibilityDetect (bool apply, bool Real)
void HandleAuraModTotalHealthPercentRegen (bool apply, bool Real)
void HandleAuraModTotalManaPercentRegen (bool apply, bool Real)
void HandleAuraModResistance (bool apply, bool Real)
void HandleAuraModRoot (bool apply, bool Real)
void HandleAuraModSilence (bool apply, bool Real)
void HandleAuraModStat (bool apply, bool Real)
void HandleDetectAmore (bool apply, bool Real)
void HandleAuraFakeInebriation (bool apply, bool Real)
void HandleAuraModIncreaseSpeed (bool Apply, bool Real)
void HandleAuraModIncreaseMountedSpeed (bool apply, bool Real)
void HandleAuraModIncreaseFlightSpeed (bool apply, bool Real)
void HandleAuraModDecreaseSpeed (bool apply, bool Real)
void HandleAuraModUseNormalSpeed (bool Apply, bool Real)
void HandleAuraModIncreaseHealth (bool apply, bool Real)
void HandleAuraModIncreaseEnergy (bool apply, bool Real)
void HandleAuraModShapeshift (bool apply, bool Real)
void HandleAuraModEffectImmunity (bool apply, bool Real)
void HandleAuraModStateImmunity (bool apply, bool Real)
void HandleAuraModSchoolImmunity (bool apply, bool Real)
void HandleAuraModDmgImmunity (bool apply, bool Real)
void HandleAuraModDispelImmunity (bool apply, bool Real)
void HandleAuraProcTriggerSpell (bool apply, bool Real)
void HandleAuraTrackCreatures (bool apply, bool Real)
void HandleAuraTrackResources (bool apply, bool Real)
void HandleAuraModParryPercent (bool apply, bool Real)
void HandleAuraModDodgePercent (bool apply, bool Real)
void HandleAuraModBlockPercent (bool apply, bool Real)
void HandleAuraModCritPercent (bool apply, bool Real)
void HandlePeriodicLeech (bool apply, bool Real)
void HandleModHitChance (bool apply, bool Real)
void HandleModSpellHitChance (bool apply, bool Real)
void HandleAuraModScale (bool apply, bool Real)
void HandlePeriodicManaLeech (bool apply, bool Real)
void HandlePeriodicHealthFunnel (bool apply, bool Real)
void HandleModCastingSpeed (bool apply, bool Real)
void HandleAuraMounted (bool apply, bool Real)
void HandleWaterBreathing (bool apply, bool real)
void HandleModStealthLevel (bool apply, bool real)
void HandleModWaterBreathing (bool apply, bool Real)
void HandleModBaseResistance (bool apply, bool Real)
void HandleModRegen (bool apply, bool Real)
void HandleModPowerRegen (bool apply, bool Real)
void HandleModPowerRegenPCT (bool Apply, bool Real)
void HandleModHealingPCT (bool apply, bool real)
void HandleChannelDeathItem (bool apply, bool Real)
void HandleDamagePercentTaken (bool apply, bool Real)
void HandlePeriodicDamagePCT (bool apply, bool Real)
void HandleAuraModAttackPower (bool apply, bool Real)
void HandleAuraTransform (bool apply, bool Real)
void HandleModSpellCritChance (bool apply, bool Real)
void HandleAuraModIncreaseSwimSpeed (bool Apply, bool Real)
void HandleModPowerCostPCT (bool apply, bool Real)
void HandleModPowerCost (bool apply, bool Real)
void HandleFarSight (bool apply, bool Real)
void HandleModPossessPet (bool apply, bool Real)
void HandleModMechanicImmunity (bool apply, bool Real)
void HandleModMechanicImmunityMask (bool apply, bool Real)
void HandleAuraModSkill (bool apply, bool Real)
void HandleModDamagePercentDone (bool apply, bool Real)
void HandleModPercentStat (bool apply, bool Real)
void HandleModResistancePercent (bool apply, bool Real)
void HandleAuraModBaseResistancePercent (bool apply, bool Real)
void HandleAuraTrackStealthed (bool apply, bool Real)
void HandleForceReaction (bool apply, bool Real)
void HandleAuraModRangedHaste (bool apply, bool Real)
void HandleRangedAmmoHaste (bool apply, bool Real)
void HandleModHealingDone (bool Apply, bool Real)
void HandleModTotalPercentStat (bool apply, bool Real)
void HandleAuraModTotalThreat (bool apply, bool Real)
void HandleModUnattackable (bool Apply, bool Real)
void HandleAuraModPacify (bool apply, bool Real)
void HandleAuraGhost (bool apply, bool Real)
void HandleAuraAllowFlight (bool apply, bool Real)
void HandleModRating (bool apply, bool Real)
void HandleModRatingFromStat (bool apply, bool Real)
void HandleModTargetResistance (bool apply, bool Real)
void HandleAuraModAttackPowerPercent (bool apply, bool Real)
void HandleAuraModRangedAttackPowerPercent (bool apply, bool Real)
void HandleAuraModRangedAttackPowerOfStatPercent (bool apply, bool Real)
void HandleAuraModAttackPowerOfStatPercent (bool apply, bool Real)
void HandleAuraModAttackPowerOfArmor (bool apply, bool Real)
void HandleSpiritOfRedemption (bool apply, bool Real)
void HandleAoECharm (bool apply, bool Real)
void HandleModManaRegen (bool apply, bool Real)
void HandleComprehendLanguage (bool apply, bool Real)
void HandleShieldBlockValue (bool apply, bool Real)
void HandleModSpellCritChanceShool (bool apply, bool Real)
void HandleAuraRetainComboPoints (bool apply, bool Real)
void HandleModSpellDamagePercentFromStat (bool apply, bool Real)
void HandleModSpellHealingPercentFromStat (bool apply, bool Real)
void HandleAuraModDispelResist (bool apply, bool Real)
void HandleAuraControlVehicle (bool apply, bool Real)
Such auras are applied from a caster(=player) to a vehicle.
void HandleModSpellDamagePercentFromAttackPower (bool apply, bool Real)
void HandleModSpellHealingPercentFromAttackPower (bool apply, bool Real)
void HandleAuraModPacifyAndSilence (bool apply, bool Real)
void HandleAuraModIncreaseMaxHealth (bool apply, bool Real)
void HandleAuraModExpertise (bool apply, bool Real)
void HandleForceMoveForward (bool apply, bool Real)
void HandleAuraModResistenceOfStatPercent (bool apply, bool Real)
void HandleAuraPowerBurn (bool apply, bool Real)
void HandleSchoolAbsorb (bool apply, bool Real)
void HandlePreventFleeing (bool apply, bool Real)
void HandleManaShield (bool apply, bool Real)
void HandleArenaPreparation (bool apply, bool Real)
void HandleAuraMirrorImage (bool apply, bool Real)
void HandleAuraConvertRune (bool apply, bool Real)
void HandleAuraIncreaseBaseHealthPercent (bool apply, bool Real)
void HandleNoReagentUseAura (bool Apply, bool Real)
void HandlePhase (bool apply, bool Real)
void HandleModTargetArmorPct (bool Apply, bool Real)
void HandleAuraModAllCritChance (bool apply, bool Real)
void HandleAuraOpenStable (bool apply, bool Real)
void HandleAuraAddMechanicAbilities (bool apply, bool Real)
void HandleAuraStopNaturalManaRegen (bool apply, bool Real)
void HandleAuraSetVehicleId (bool apply, bool Real)
void HandleMirrorName (bool apply, bool Real)
void HandlePreventResurrection (bool apply, bool Real)
void HandleFactionOverride (bool apply, bool Real)
void HandlePrayerOfMending (bool apply, bool Real)
void HandleTriggerLinkedAura (bool apply, bool Real)
void HandleAuraDetaunt (bool Apply, bool Real)
void HandleOverrideClassScript (bool apply, bool real)
void HandleAuraAllowOnlyAbility (bool apply, bool real)
virtual ~Aura ()
void SetModifier (AuraType type, int32 amount, uint32 periodicTime, int32 miscValue)
Modifier * GetModifier ()
Modifier const * GetModifier () const
int32 GetMiscValue () const
int32 GetMiscBValue () const
SpellEntry const * GetSpellProto () const
uint32 GetId () const
ObjectGuid const & GetCastItemGuid () const
ObjectGuid const & GetCasterGuid () const
Unit * GetCaster () const
Unit * GetTarget () const
SpellEffectIndex GetEffIndex () const
int32 GetBasePoints () const
int32 GetAmount () const
void SetAmount (int32 amount)
int32 GetAuraMaxDuration () const
int32 GetAuraDuration () const
time_t GetAuraApplyTime () const
uint32 GetAuraTicks () const
uint32 GetAuraMaxTicks () const
uint32 GetStackAmount () const
void SetLoadedState (int32 damage, uint32 periodicTime)
bool IsPositive () const
bool IsPersistent () const
bool IsAreaAura () const
bool IsPeriodic () const
bool IsSaveToDbAura () const
void ApplyModifier (bool apply, bool Real=false)
void UpdateAuraScaling ()
void UpdateAura (uint32 diff)
void SetRemoveMode (AuraRemoveMode mode)
AuraRemoveMode GetRemoveMode ()
virtual Unit * GetTriggerTarget () const
void HandleShapeshiftBoosts (bool apply)
void TriggerSpell ()
void TriggerSpellWithValue ()
ClassFamilyMask const & GetAuraSpellClassMask () const
bool isAffectedOnSpell (SpellEntry const *spell) const
bool CanProcFrom (SpellEntry const *spell, uint32 procFlag, uint32 EventProcEx, uint32 procEx, bool active, bool useClassMask) const
SpellAuraHolder * GetHolder ()
SpellAuraHolder const * GetHolder () const
bool IsLastAuraOnHolder ()
bool HasMechanic (uint32 mechanic) const
SpellModifier * GetSpellModifier ()
void UseMagnet ()
bool IsMagnetUsed () const
AuraScript * GetAuraScript () const
void SetScriptValue (uint64 value)
uint64 GetScriptValue ()
void SetScriptStorage (ScriptStorage *storage)
ScriptStorage * GetScriptStorage ()
void OnAuraInit ()
int32 OnAuraValueCalculate (Unit *caster, int32 currentValue)
void OnDamageCalculate (Unit *victim, int32 &advertisedBenefit, float &totalMod)
void OnApply (bool apply)
void OnAfterApply (bool apply)
bool OnCheckProc (ProcExecutionData &data)
SpellAuraProcResult OnProc (ProcExecutionData &data)
void OnAbsorb (int32 &currentAbsorb, int32 &remainingDamage, uint32 &reflectedSpellId, int32 &reflectDamage, bool &preventedDeath, bool &dropCharge)
void OnManaAbsorb (int32 &currentAbsorb)
void OnAuraDeathPrevention (int32 &remainingDamage)
void OnPeriodicTrigger (PeriodicTriggerData &data)
void OnPeriodicDummy ()
void OnPeriodicTickEnd ()
void OnPeriodicCalculateAmount (uint32 &amount)
void OnHeartbeat ()
uint32 GetAuraScriptCustomizationValue ()
void ForcePeriodicity (uint32 periodicTime)
Static Public Member Functions
static uint32 CalculateAuraEffectValue (Unit *caster, Unit *target, SpellEntry const *spellProto, SpellEffectIndex effIdx, uint32 value)
Protected Member Functions
Aura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster=nullptr, Item *castItem=nullptr)
virtual void Update (uint32 diff)
void PeriodicTick ()
void PeriodicDummyTick ()
bool IsCritFromAbilityAura (Unit *caster, uint32 &damage) const
void ReapplyAffectedPassiveAuras ()
void PickTargetsForSpellTrigger (Unit *&triggerCaster, Unit *&triggerTarget, WorldObject *&triggerTargetObject, SpellEntry const *spellInfo)
void CastTriggeredSpell (PeriodicTriggerData &data)
Protected Attributes
Modifier m_modifier
SpellModifier * m_spellmod
time_t m_applyTime
int32 m_currentBasePoints
int32 m_periodicTimer
uint32 m_periodicTick
AuraRemoveMode m_removeMode: 8
SpellEffectIndex m_effIndex: 8
bool m_positive: 1
bool m_isPeriodic: 1
bool m_isAreaAura: 1
bool m_isPersistent: 1
bool m_magnetUsed: 1
SpellAuraHolder *const m_spellAuraHolder
uint64 m_scriptValue
ScriptStorage * m_storage
Private Member Functions
void ReapplyAffectedPassiveAuras (Unit *target, bool owner_mode)
Friends
struct ReapplyAffectedPassiveAurasHelper
Aura * CreateAura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster, Item *castItem, uint64 scriptValue)
Detailed Description
Definition at line 277 of file SpellAuras.h.
Constructor & Destructor Documentation
~Aura()
Aura::~Aura () virtual
Definition at line 453 of file SpellAuras.cpp.
References m_spellmod, and m_storage.
Aura()
Aura::Aura (SpellEntry const * spellproto, SpellEffectIndex eff, int32 const * currentDamage, int32 const * currentBasePoints, SpellAuraHolder * holder, Unit * target, Unit * caster = nullptr, Item * castItem = nullptr) protected
Definition at line 384 of file SpellAuras.cpp.
References Player::ApplySpellMod(), CalculateAuraEffectValue(), SpellEntry::CalculateSimpleValue(), DEBUG_FILTER_LOG, SpellEntry::EffectAmplitude, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectMiscValue, ItemRandomSuffixEntry::enchant_id, Object::GetFloatValue(), Item::GetItemRandomPropertyId(), Item::GetItemSuffixFactor(), WorldObject::GetSpellModOwner(), SpellAuraHolder::GetStackAmount(), Unit::HasAffectedAura(), SpellEntry::HasAttribute(), SpellEntry::Id, IsPositiveAuraEffect(), LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), m_applyTime, m_currentBasePoints, m_effIndex, m_modifier, m_periodicTimer, m_positive, MANGOS_ASSERT, OnAuraValueCalculate(), Modifier::periodictime, ItemRandomSuffixEntry::prefix, SetModifier(), sItemRandomSuffixStore, SPELL_ATTR_EX5_EXTRA_INITIAL_PERIOD, SPELL_ATTR_EX5_SPELL_HASTE_AFFECTS_PERIODIC, SPELL_AURA_PERIODIC_HASTE, SpellItemEnchantmentEntry::spellid, SPELLMOD_ACTIVATION_TIME, sSpellItemEnchantmentStore, sSpellTemplate, and UNIT_MOD_CAST_SPEED.
Member Function Documentation
ApplyModifier()
void Aura::ApplyModifier (bool apply, bool Real = false)
Definition at line 909 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_GAINED_STACK, AuraHandler, GetSpellProto(), GetTarget(), Modifier::m_auraname, m_modifier, m_removeMode, OnAfterApply(), OnApply(), Unit::RegisterScalingAura(), SPELL_ATTR_EX4_OWNER_POWER_SCALING, and TOTAL_AURAS.
Referenced by PeriodicDummyTick(), Unit::RemoveAura(), AreaAura::Update(), UpdateAuraScaling(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
CalculateAuraEffectValue()
uint32 Aura::CalculateAuraEffectValue (Unit * caster, Unit * target, SpellEntry const * spellProto, SpellEffectIndex effIdx, uint32 value) static
Definition at line 11469 of file SpellAuras.cpp.
References Unit::CalculateLevelPenalty(), SpellEntry::EffectApplyAuraName, GetSpellSchoolMask(), SpellEntry::Id, SPELL_AURA_SCHOOL_ABSORB, Unit::SpellBaseHealingBonusDone(), and sSpellMgr.
Referenced by Aura(), and Spell::CheckCast().
CanProcFrom()
bool Aura::CanProcFrom (SpellEntry const * spell, uint32 procFlag, uint32 EventProcEx, uint32 procEx, bool active, bool useClassMask) const
Definition at line 952 of file SpellAuras.cpp.
References GetAuraSpellClassMask(), GetEffIndex(), GetHolder(), GetSpellProto(), IsCastEndProcModifierAura(), ClassFamilyMask::IsFitToFamilyMask(), PROC_EX_CAST_END, PROC_EX_CRITICAL_HIT, PROC_EX_EX_TRIGGER_ALWAYS, PROC_EX_NONE, PROC_EX_NORMAL_HIT, and SpellEntry::SpellFamilyFlags.
Referenced by Unit::ProcDamageAndSpellFor().
CastTriggeredSpell()
void Aura::CastTriggeredSpell (PeriodicTriggerData & data) protected
Definition at line 1119 of file SpellAuras.cpp.
References PeriodicTriggerData::basePoints, PeriodicTriggerData::caster, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, GetCastItemGuid(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellProto(), SpellEntry::HasAttribute(), Spell::m_currentBasePoints, SpellCastTargets::setDestination(), Spell::SetForwardedCastItem(), SpellCastTargets::setSource(), SpellCastTargets::setUnitTarget(), SPELL_ATTR_EX2_RETAIN_ITEM_CAST, PeriodicTriggerData::spellInfo, Spell::SpellStart(), PeriodicTriggerData::target, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_SOURCE_LOCATION, PeriodicTriggerData::targetObject, SpellEntry::Targets, and TRIGGERED_OLD_TRIGGERED.
Referenced by TriggerSpell(), and TriggerSpellWithValue().
ForcePeriodicity()
void Aura::ForcePeriodicity (uint32 periodicTime)
Definition at line 11575 of file SpellAuras.cpp.
References m_isPeriodic, m_modifier, m_periodicTimer, and Modifier::periodictime.
Referenced by AnastariPossess::OnApply(), EredarPreGateBeam::OnApply(), GreaterInvisibilityMob::OnApply(), AuchenaiPossess::OnApply(), AllergiesAura::OnApply(), NetherChargePassive::OnApply(), FakeAggroRadius8YD::OnAuraInit(), Drink::OnPeriodicDummy(), and DeathRuneDK::OnProc().
GetAmount()
int32 Aura::GetAmount () const inline
Definition at line 479 of file SpellAuras.h.
References Modifier::m_amount, and m_modifier.
Referenced by HandleModCastingSpeed(), HandleModMeleeRangedSpeedPct(), HandleTriggerLinkedAura(), Unit::Mount(), WillOfTheNecropolis::OnAbsorb(), FetchAlchemistsApprentice::OnApply(), CryptFeverServerside::OnAuraValueCalculate(), FormScalingAttackPowerAuras::OnAuraValueCalculate(), FingersOfFrostProc::OnCheckProc(), ParachutePeriodicDummy::OnPeriodicDummy(), Drink::OnPeriodicDummy(), ExplosiveShot::OnPeriodicDummy(), PreyOnTheWeak::OnPeriodicDummy(), RapidRecuperationPeriodic::OnPeriodicTrigger(), SwiftHandOfJustice::OnProc(), LockAndLoad::OnProc(), EarthShield::OnProc(), ItemShamanT10Elemental2PBonus::OnProc(), AncestralAwakening::OnProc(), SoulLeech::OnProc(), and Unit::Unmount().
GetAuraApplyTime()
time_t Aura::GetAuraApplyTime () const inline
Definition at line 484 of file SpellAuras.h.
References m_applyTime.
GetAuraDuration()
int32 Aura::GetAuraDuration () const inline
Definition at line 483 of file SpellAuras.h.
References SpellAuraHolder::GetAuraDuration(), and GetHolder().
Referenced by Spell::EffectHeal(), HandleAuraDummy(), HandleAuraPeriodicDummy(), ChatHandler::HandleListAurasCommand(), npc_air_force_botsAI::MoveInLineOfSight(), SetLoadedState(), TriggerSpell(), and AreaAura::Update().
GetAuraMaxDuration()
int32 Aura::GetAuraMaxDuration () const inline
Definition at line 482 of file SpellAuras.h.
References SpellAuraHolder::GetAuraMaxDuration(), and GetHolder().
Referenced by GetAuraMaxTicks(), ChatHandler::HandleListAurasCommand(), and TriggerSpell().
GetAuraMaxTicks()
uint32 Aura::GetAuraMaxTicks () const inline
Definition at line 486 of file SpellAuras.h.
References GetAuraMaxDuration(), m_modifier, and Modifier::periodictime.
Referenced by Spell::EffectScriptEffect(), HandlePeriodicEnergize(), AQWhirlwind::OnEffectExecute(), PeriodicTick(), and SetLoadedState().
GetAuraScript()
AuraScript* Aura::GetAuraScript () const inline
Definition at line 543 of file SpellAuras.h.
References SpellAuraHolder::GetAuraScript(), and GetHolder().
Referenced by GetAuraScriptCustomizationValue(), OnAbsorb(), OnAfterApply(), OnApply(), OnAuraDeathPrevention(), OnAuraInit(), OnAuraValueCalculate(), OnCheckProc(), OnDamageCalculate(), OnHeartbeat(), OnManaAbsorb(), OnPeriodicCalculateAmount(), OnPeriodicDummy(), OnPeriodicTickEnd(), OnPeriodicTrigger(), OnProc(), and TriggerSpell().
GetAuraScriptCustomizationValue()
uint32 Aura::GetAuraScriptCustomizationValue ()
Definition at line 11568 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by HandleAuraModShapeshift(), and HandleAuraTransform().
GetAuraSpellClassMask()
ClassFamilyMask const& Aura::GetAuraSpellClassMask () const inline
Definition at line 524 of file SpellAuras.h.
References SpellEntry::GetEffectSpellClassMask(), SpellAuraHolder::GetSpellProto(), m_effIndex, and m_spellAuraHolder.
Referenced by CanProcFrom(), isAffectedOnSpell(), and SpellModifier::SpellModifier().
GetAuraTicks()
uint32 Aura::GetAuraTicks () const inline
Definition at line 485 of file SpellAuras.h.
References m_periodicTick.
Referenced by Spell::EffectDummy(), Unit::HandleProcTriggerSpellAuraProc(), AQWhirlwind::OnEffectExecute(), SpellBurnDamageBrutallus::OnPeriodicCalculateAmount(), CurseOfBoundlessAgony::OnPeriodicCalculateAmount(), CurseOfAgony::OnPeriodicCalculateAmount(), spell_frost_tomb_aura::OnPeriodicDummy(), spell_summon_gauntlet_mobs_periodic_aura::OnPeriodicDummy(), RamTrot::OnPeriodicDummy(), RamCanter::OnPeriodicDummy(), RamGallop::OnPeriodicDummy(), MoleMachinePortSchedule::OnPeriodicDummy(), MoleMachinePortalSchedule::OnPeriodicDummy(), Drink::OnPeriodicDummy(), NetherChargePassive::OnPeriodicTickEnd(), CurseOfBoundlessAgony::OnPeriodicTickEnd(), WebWrapDamage::OnPeriodicTickEnd(), PlagueWaveController::OnPeriodicTrigger(), SummonSkeletonsNoth::OnPeriodicTrigger(), PeriodicDummyTick(), PeriodicTick(), and TriggerSpell().
GetBasePoints()
int32 Aura::GetBasePoints () const inline
Definition at line 478 of file SpellAuras.h.
References m_currentBasePoints.
Referenced by HandleAuraControlVehicle(), HandleAuraFakeInebriation(), HandlePeriodicEnergize(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::RemoveAurasDueToSpellBySteal().
GetCaster()
Unit* Aura::GetCaster () const inline
Definition at line 474 of file SpellAuras.h.
References SpellAuraHolder::GetCaster(), and GetHolder().
Referenced by EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_npc(), Polymorph::GetAuraScriptCustomizationValue(), HandleAoECharm(), HandleAuraControlVehicle(), HandleAuraDamageShield(), HandleAuraDetaunt(), HandleAuraDummy(), HandleAuraEmpathy(), HandleAuraMirrorImage(), HandleAuraModDmgImmunity(), HandleAuraModRoot(), HandleAuraModSchoolImmunity(), HandleAuraModStat(), HandleAuraModStun(), HandleAuraModTotalThreat(), HandleAuraPeriodicDummy(), HandleAuraProcTriggerSpell(), HandleBindSight(), HandleChannelDeathItem(), Unit::HandleDummyAuraProc(), HandleFarSight(), HandleManaShield(), HandleMirrorName(), HandleModCharm(), HandleModPossess(), HandleModPossessPet(), HandlePeriodicDamage(), HandlePeriodicEnergize(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), HandlePeriodicTriggerSpell(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), HandleSchoolAbsorb(), Unit::HandleSpellCritChanceAuraProc(), HandleTriggerLinkedAura(), ArdentDefender::OnAbsorb(), PossessRazorgore::OnApply(), Enfeeble::OnApply(), Sacrifice::OnApply(), spell_mana_rage_selin::OnApply(), AnastariPossess::OnApply(), HexOfJammalanAura::OnApply(), SinisterReflectionClone::OnApply(), VengeanceOfTheBlueFlight::OnApply(), ThreateningGaze::OnApply(), RenatakiVanishTeleport::OnApply(), HuhuranWyvernSting::OnApply(), FlyingMachineControls::OnApply(), spell_pursuit::OnApply(), MutatingInjection::OnApply(), spell_vortex_aura::OnApply(), spell_ride_oculus_drake_saddle::OnApply(), CharmDrakuruServant::OnApply(), ArgentStandUnitRideGargoyle::OnApply(), HaveWitheredBatwing::OnApply(), HaveAmberseed::OnApply(), HaveChilledSerpentMucus::OnApply(), FetchAlchemistsApprentice::OnApply(), ShapeOfTheBeast::OnApply(), SupremusRandomTarget::OnApply(), ShadowOfDeath::OnApply(), VerasDeadlyPoisonTick::OnApply(), InsidiousWhisper::OnApply(), ScrapReaverSpell::OnApply(), StormcrowAmulet::OnApply(), HorsemanManiacalLaugh::OnApply(), AuchenaiPossess::OnApply(), CallOfTheFalcon::OnApply(), DeathKnightDisease::OnApply(), ShadowAffinityDots::OnApply(), CurseOfDoom::OnApply(), SeedOfCorruption::OnApply(), Overpower::OnApply(), DemoniacVisitation::OnApply(), DigestiveAcidPeriodic::OnPeriodicCalculateAmount(), spell_alluring_perfume_spill_aura::OnPeriodicDummy(), spell_irresistible_cologne_spill_aura::OnPeriodicDummy(), spell_leeching_swarm_aura::OnPeriodicDummy(), spell_wailing_souls_aura::OnPeriodicDummy(), RandomIngredientAura::OnPeriodicDummy(), SummonIceSpearKnockbackDelayer::OnPeriodicDummy(), MoleMachinePortSchedule::OnPeriodicDummy(), HorsemanStartFirePeriodic::OnPeriodicDummy(), HorsemanFire::OnPeriodicDummy(), HorsemanConflagratePeriodic::OnPeriodicDummy(), SummonGargoyle::OnPeriodicDummy(), ExplosiveShot::OnPeriodicDummy(), Regrowth::OnPeriodicTickEnd(), MageIgnite::OnPeriodicTickEnd(), FrostBlast::OnPeriodicTrigger(), spell_enervating_brand_aura::OnPeriodicTrigger(), spell_emblazon_runeblade_aura::OnPeriodicTrigger(), spell_siphon_of_acherus_aura::OnPeriodicTrigger(), PeriodicSummonEyeTrigger::OnPeriodicTrigger(), PeriodicRotate::OnPeriodicTrigger(), ArmyOfTheDead::OnPeriodicTrigger(), spell_ley_line_focus_item::OnPeriodicTrigger(), ZombieChowSearch::OnPeriodicTrigger(), SummonZombieChow::OnPeriodicTrigger(), ThaddiusCharge::OnPeriodicTrigger(), Icecrown25MeleeTrinket::OnProc(), spell_seed_of_corruption_npc::OnProc(), RoarOfSacrifice::OnProc(), EarthShield::OnProc(), SeedOfCorruption::OnProc(), Vigilance::OnProc(), PeriodicDummyTick(), PeriodicTick(), PickTargetsForSpellTrigger(), ReapplyAffectedPassiveAuras(), TriggerSpell(), AreaAura::Update(), PersistentAreaAura::Update(), UpdateAuraScaling(), and Unit::UpdateVisibilityAndView().
GetCasterGuid()
ObjectGuid const& Aura::GetCasterGuid () const inline
Definition at line 473 of file SpellAuras.h.
References SpellAuraHolder::GetCasterGuid(), and GetHolder().
Referenced by Unit::CalculateSpellCritChance(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Spell::EffectHeal(), Unit::GetCritTakenChance(), HandleAoECharm(), HandleAuraDummy(), HandleAuraModStat(), HandleDamagePercentTaken(), Unit::HandleDummyAuraProc(), HandleFeignDeath(), HandleModCharm(), HandleModConfuse(), Unit::HandleModDamageFromCasterAuraProc(), HandleModFear(), HandleModPossess(), HandlePeriodicTriggerSpell(), HandlePreventFleeing(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::HandleRemoveByDamageChanceProc(), HandleSchoolAbsorb(), HandleTriggerLinkedAura(), IsSaveToDbAura(), PowerCircleAura::OnApply(), spell_feigh_death_pos_aura::OnApply(), PainSuppression::OnApply(), SpellReflectionRaid::OnApply(), PlagueWaveController::OnPeriodicTrigger(), spell_seed_of_corruption_npc::OnProc(), SeedOfCorruption::OnProc(), PeriodicTick(), ReapplyAffectedPassiveAuras(), Unit::RemoveSingleAuraFromSpellAuraHolder(), Unit::SendPeriodicAuraLog(), TriggerSpell(), TriggerSpellWithValue(), AreaAura::Update(), and GameObjectAura::Update().
GetCastItemGuid()
ObjectGuid const& Aura::GetCastItemGuid () const inline
Definition at line 472 of file SpellAuras.h.
References SpellAuraHolder::GetCastItemGuid(), and GetHolder().
Referenced by CastTriggeredSpell(), Unit::HandleAddPctModifierAuraProc(), HandleAuraDummy(), Unit::HandleDummyAuraProc(), Unit::HandleHasteAuraProc(), Unit::HandleManaShieldAuraProc(), Unit::HandleModDamagePercentDoneAuraProc(), Unit::HandleOverrideClassScriptAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), and Unit::HandleSpellCritChanceAuraProc().
GetEffIndex()
SpellEffectIndex Aura::GetEffIndex () const inline
Definition at line 477 of file SpellAuras.h.
References m_effIndex.
Referenced by CanProcFrom(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_crystal_channel_target(), EffectAuraDummy_npc_depleted_war_golem(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_oil_stained_wolf(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectAuraDummy_spell_aura_dummy_crates_carried(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), EffectAuraDummy_spell_aura_dummy_noxxion_spawns(), EffectAuraDummy_spell_aura_dummy_npc(), EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), EffectAuraDummy_spell_aura_dummy_sacrifice_beam(), HandleAuraModStat(), Unit::HandleDummyAuraProc(), ChatHandler::HandleListAurasCommand(), HandlePeriodicTriggerSpell(), Unit::HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), IsLastAuraOnHolder(), SnakeWrap::OnApply(), NetherChargeTimer::OnApply(), ArenaPreparation::OnApply(), PossessRazorgore::OnApply(), UnarmedWoodcutter::OnApply(), Enfeeble::OnApply(), spell_mana_rage_selin::OnApply(), EyeOfAcherus::OnApply(), DeathCloudBrutallus::OnApply(), FogOfCorruptionCharm::OnApply(), Encapsulate::OnApply(), SpectralRealmAura::OnApply(), DarknessOfSouls::OnApply(), VengeanceOfTheBlueFlight::OnApply(), CThunMouthTentacle::OnApply(), MutateBug::OnApply(), ViscidusFreeze::OnApply(), FlyingMachineControls::OnApply(), spell_ride_oculus_drake_saddle::OnApply(), CharmGeist::OnApply(), ShadowOfDeath::OnApply(), ShadowGraspCube::OnApply(), CharmRavager::OnApply(), ScrapReaverSpell::OnApply(), PossessionTransfer::OnApply(), WrathOfTheAstromancer::OnApply(), OgrilaFlasks::OnApply(), InebriateRemoval::OnApply(), Drink::OnApply(), DeathKnightDisease::OnApply(), DancingRuneWeapon::OnApply(), Brambles::OnApply(), GlyphOfShadowWordDeath::OnApply(), DirtyDeeds::OnApply(), KillingSpree::OnApply(), SeedOfCorruption::OnApply(), KillingSpree::OnAuraInit(), OnAuraValueCalculate(), DancingRuneWeapon::OnCheckProc(), DirtyDeeds::OnDamageCalculate(), DigestiveAcidPeriodic::OnPeriodicCalculateAmount(), SpellBurnDamageBrutallus::OnPeriodicCalculateAmount(), SummonIceSpearKnockbackDelayer::OnPeriodicDummy(), Drink::OnPeriodicDummy(), spell_seed_of_corruption_npc::OnProc(), DancingRuneWeapon::OnProc(), LockAndLoad::OnProc(), SeedOfCorruption::OnProc(), Vigilance::OnProc(), PeriodicDummyTick(), PeriodicTick(), Unit::RemoveAura(), Unit::RemoveAurasDueToSpellBySteal(), TriggerSpell(), AreaAura::Update(), PersistentAreaAura::Update(), and UpdateAuraScaling().
GetHolder() [1/2]
SpellAuraHolder* Aura::GetHolder () inline
Definition at line 528 of file SpellAuras.h.
References m_spellAuraHolder.
Referenced by CanProcFrom(), Spell::EffectDummy(), GetAuraDuration(), GetAuraMaxDuration(), GetAuraScript(), GetCaster(), GetCasterGuid(), GetCastItemGuid(), GetId(), GetSpellProto(), GetStackAmount(), GetTarget(), Unit::HandleAddFlatModifierAuraProc(), HandleAddModifier(), Unit::HandleAddPctModifierAuraProc(), HandleAuraDummy(), HandleAuraModEffectImmunity(), HandleAuraModShapeshift(), HandleAuraPeriodicDummy(), HandleAuraProcTriggerSpell(), HandleAuraSafeFall(), HandleAuraTransform(), Unit::HandleDummyAuraProc(), Unit::HandleModRating(), Unit::HandlePeriodicAuraProc(), HandlePhase(), Unit::HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), IsLastAuraOnHolder(), IsSaveToDbAura(), ArdentDefender::OnAbsorb(), Drink::OnApply(), DirtyDeeds::OnDamageCalculate(), WarriorDevastate::OnEffectExecute(), Drink::OnPeriodicDummy(), FlagAuraBg::OnProc(), LockAndLoad::OnProc(), PeriodicDummyTick(), PeriodicTick(), Spell::PreCastCheck(), Unit::RemoveAura(), Unit::RemoveSpellsCausingAura(), Unit::TriggerProccedSpell(), TriggerSpell(), PersistentAreaAura::Update(), and GameObjectAura::Update().
GetHolder() [2/2]
SpellAuraHolder const* Aura::GetHolder () const inline
Definition at line 529 of file SpellAuras.h.
References m_spellAuraHolder.
GetId()
uint32 Aura::GetId (void) const inline
Definition at line 471 of file SpellAuras.h.
References GetHolder(), SpellAuraHolder::GetSpellProto(), and SpellEntry::Id.
Referenced by Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_crystal_channel_target(), EffectAuraDummy_npc_depleted_war_golem(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_oil_stained_wolf(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectAuraDummy_spell_aura_dummy_crates_carried(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), EffectAuraDummy_spell_aura_dummy_noxxion_spawns(), EffectAuraDummy_spell_aura_dummy_npc(), EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), EffectAuraDummy_spell_aura_dummy_sacrifice_beam(), Spell::EffectEnergize(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), HandleAoECharm(), HandleAuraDummy(), HandleAuraModDmgImmunity(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseHealth(), HandleAuraModIncreaseHealthPercent(), HandleAuraModPacifyAndSilence(), HandleAuraModSchoolImmunity(), HandleAuraModShapeshift(), HandleAuraModStat(), HandleAuraModStun(), HandleAuraModTotalHealthPercentRegen(), HandleAuraModTotalManaPercentRegen(), HandleAuraProcTriggerSpell(), HandleAuraSafeFall(), HandleAuraTransform(), Unit::HandleDummyAuraProc(), HandleFeignDeath(), HandleInvisibility(), Unit::HandleInvisibilityAuraProc(), ChatHandler::HandleListAurasCommand(), HandleModCastingSpeed(), HandleModCharm(), HandleModConfuse(), HandleModDamagePercentDone(), HandleModFear(), HandleModHealingPCT(), HandleModMechanicImmunity(), HandleModMechanicImmunityMask(), HandleModMeleeRangedSpeedPct(), HandleModMeleeSpeedPct(), HandleModPossess(), HandleModPowerCostPCT(), HandleModThreat(), HandlePeriodicEnergize(), HandlePeriodicManaLeech(), HandlePeriodicTriggerSpell(), HandlePhase(), HandlePreventFleeing(), Unit::HandleProcTriggerDamageAuraProc(), Unit::HandleRemoveByDamageChanceProc(), spell_feigh_death_pos_aura::OnApply(), ForcedObedience::OnApply(), spell_telestra_clone_dies_aura::OnApply(), spell_freezing_cloud_aura::OnApply(), ShivanShapeshiftForm::OnApply(), BraziersHit::OnApply(), TorchesCaught::OnApply(), DeathKnightDisease::OnApply(), RapidKilling::OnApply(), SeedOfCorruption::OnApply(), Overpower::OnApply(), SpellReflectionRaid::OnApply(), DirtyDeeds::OnDamageCalculate(), FoodAnimation::OnHeartbeat(), DrinkAnimation::OnHeartbeat(), spell_summon_anubar_periodic_aura::OnPeriodicDummy(), spell_wailing_souls_aura::OnPeriodicDummy(), RocketPackPeriodic::OnPeriodicDummy(), ParachutePeriodicDummy::OnPeriodicDummy(), RandomIngredientAura::OnPeriodicDummy(), GiddyUp::OnPeriodicDummy(), MoleMachinePortSchedule::OnPeriodicDummy(), MoleMachinePortalSchedule::OnPeriodicDummy(), HorsemanManiacalLaughDelayed::OnPeriodicDummy(), MarkOfKazrogal::OnPeriodicTickEnd(), CurseOfPain::OnPeriodicTickEnd(), spell_mana_barrier_aura::OnPeriodicTrigger(), PeriodicRotate::OnPeriodicTrigger(), ThaddiusCharge::OnPeriodicTrigger(), SpoutTurning::OnPeriodicTrigger(), FingersOfFrostDummy::OnProc(), spell_seed_of_corruption_npc::OnProc(), SeedOfCorruption::OnProc(), SoulLeech::OnProc(), PeriodicDummyTick(), PeriodicTick(), ReapplyAffectedPassiveAuras(), Unit::SendPeriodicAuraLog(), TriggerSpell(), AreaAura::Update(), and PersistentAreaAura::Update().
GetMiscBValue()
int32 Aura::GetMiscBValue () const inline
Definition at line 468 of file SpellAuras.h.
References SpellEntry::EffectMiscValueB, SpellAuraHolder::GetSpellProto(), m_effIndex, and m_spellAuraHolder.
GetMiscValue()
int32 Aura::GetMiscValue () const inline
Definition at line 467 of file SpellAuras.h.
References SpellEntry::EffectMiscValue, SpellAuraHolder::GetSpellProto(), m_effIndex, and m_spellAuraHolder.
Referenced by HandleAuraAddMechanicAbilities(), HandleAuraDummy(), HandleAuraSetVehicleId(), HandleDetectAmore(), HandleFactionOverride(), and HandlePhase().
GetModifier() [1/2]
Modifier* Aura::GetModifier () inline
Definition at line 465 of file SpellAuras.h.
References m_modifier.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), Player::_LoadAuras(), Pet::_LoadAuras(), Unit::AddAuraToModList(), Unit::CalculateDamageAbsorbAndResist(), Unit::CalculateSpellCritChance(), Spell::EffectHeal(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Unit::HandleAddFlatModifierAuraProc(), HandleAuraModDisarm(), HandleAuraModSkill(), Unit::HandleDummyAuraProc(), ChatHandler::HandleListAurasCommand(), Unit::HandleMechanicImmuneResistanceAuraProc(), Unit::HandleModPowerCostSchoolAuraProc(), Unit::HandleOverrideClassScriptAuraProc(), Unit::HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::HandleReflectSpellsSchoolAuraProc(), HandleShapeshiftBoosts(), SpellAuraHolder::HandleSpellSpecificBoosts(), IsSimilarExistingAuraStronger(), ArenaPreparation::OnApply(), InsidiousWhisper::OnApply(), Drink::OnApply(), DeathKnightDisease::OnApply(), ShadowAffinityDots::OnApply(), GossipNPCAppearanceAllBrewfest::OnApply(), IncreasedHealingDoneDummy::OnDamageCalculate(), IncreasedHolyLightHealing::OnDamageCalculate(), GlyphOfLightwell::OnDamageCalculate(), DirtyDeeds::OnDamageCalculate(), GlyphOfShadowWordDeath::OnDamageCalculate(), SpellBurnDamageBrutallus::OnPeriodicCalculateAmount(), spell_leeching_swarm_aura::OnPeriodicDummy(), Drink::OnPeriodicDummy(), spell_seed_of_corruption_npc::OnProc(), UnholyBlightDK::OnProc(), DeathRuneDK::OnProc(), SeedOfCorruption::OnProc(), SiphonLifeWotlk::OnProc(), PeriodicDummyTick(), Unit::ProcDamageAndSpellFor(), Unit::RemoveAura(), Unit::RemoveAurasDueToSpellBySteal(), Unit::RestoreDisplayId(), Unit::SendPeriodicAuraLog(), Unit::SpellDamageBonusDone(), TriggerSpell(), TriggerSpellWithValue(), AreaAura::Update(), and UpdateAuraScaling().
GetModifier() [2/2]
Modifier const* Aura::GetModifier () const inline
Definition at line 466 of file SpellAuras.h.
References m_modifier.
GetRemoveMode()
AuraRemoveMode Aura::GetRemoveMode () inline
Definition at line 514 of file SpellAuras.h.
References m_removeMode.
Referenced by InactiveBattleground::OnApply(), Enfeeble::OnApply(), spell_mana_rage_selin::OnApply(), HexOfJammalanAura::OnApply(), DarkFlameShadowAura::OnApply(), DarkFlameFireAura::OnApply(), CurseOfBoundlessAgony::OnApply(), DarknessOfSouls::OnApply(), HuhuranWyvernSting::OnApply(), MutatingInjection::OnApply(), spell_fiery_combustion_aura::OnApply(), spell_soul_consumption_aura::OnApply(), spell_protective_bubble_aura::OnApply(), ScourgeDisguiseExpiring::OnApply(), FetchAlchemistsApprentice::OnApply(), ParasiticShadowfiendAura::OnApply(), InsidiousWhisper::OnApply(), RingOfFlame::OnApply(), BuildPortableFelCannon::OnApply(), WrathOfTheAstromancer::OnApply(), GiddyUp::OnApply(), GDRPeriodicDamage::OnApply(), GettingSleepyAura::OnApply(), FingersOfFrostDummy::OnApply(), ShadowAffinityDots::OnApply(), CurseOfDoom::OnApply(), SeedOfCorruption::OnApply(), and SpellReflectionRaid::OnApply().
GetScriptStorage()
ScriptStorage* Aura::GetScriptStorage () inline
Definition at line 548 of file SpellAuras.h.
References m_storage.
Referenced by KillingSpree::OnPeriodicDummy().
GetScriptValue()
uint64 Aura::GetScriptValue () inline
Definition at line 546 of file SpellAuras.h.
References m_scriptValue.
Referenced by GDRPeriodicDamage::OnApply(), Icecrown25MeleeTrinket::OnAuraInit(), DemonicKnowledge::OnAuraValueCalculate(), RandomIngredientAura::OnPeriodicDummy(), Icecrown25MeleeTrinket::OnProc(), and LightwellRenew::OnProc().
GetSpellModifier()
SpellModifier* Aura::GetSpellModifier () inline
Definition at line 535 of file SpellAuras.h.
References m_spellmod.
GetSpellProto()
SpellEntry const* Aura::GetSpellProto () const inline
Definition at line 470 of file SpellAuras.h.
References GetHolder(), and SpellAuraHolder::GetSpellProto().
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), ApplyModifier(), Unit::ApplySpellDispelImmunity(), Unit::CalculateDamageAbsorbAndResist(), CanProcFrom(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), CastTriggeredSpell(), Spell::EffectHeal(), Unit::HandleAddFlatModifierAuraProc(), HandleAddModifier(), Unit::HandleAddPctModifierAuraProc(), HandleAuraConvertRune(), HandleAuraDamageShield(), HandleAuraDummy(), HandleAuraModCritPercent(), HandleAuraModEffectImmunity(), HandleAuraModIncreaseFlightSpeed(), HandleAuraModIncreaseMountedSpeed(), HandleAuraModRoot(), HandleAuraModSchoolImmunity(), HandleAuraModSkill(), HandleAuraModStat(), HandleAuraModStateImmunity(), HandleAuraModStun(), HandleAuraPeriodicDummy(), HandleAuraTransform(), WorldSession::HandleCastSpellOpcode(), HandleChannelDeathItem(), HandleDamagePercentTaken(), Unit::HandleDummyAuraProc(), HandleFeignDeath(), Unit::HandleHasteAuraProc(), HandleInvisibility(), Unit::HandleInvisibilityAuraProc(), HandleManaShield(), Unit::HandleManaShieldAuraProc(), HandleModDamageDone(), HandleModDamagePercentDone(), Unit::HandleModDamagePercentDoneAuraProc(), HandleModMechanicImmunity(), HandleModMechanicImmunityMask(), HandleModPossess(), Unit::HandleModRating(), Unit::HandleModResistanceAuraProc(), HandleModStealth(), HandleModTotalPercentStat(), Unit::HandlePeriodicAuraProc(), HandlePeriodicDamage(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), HandlePeriodicTriggerSpell(), WorldSession::HandlePetCastSpellOpcode(), Unit::HandleProcTriggerDamageAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::HandleRemoveByDamageChanceProc(), HandleSchoolAbsorb(), Unit::HandleSpellCritChanceAuraProc(), HandleTriggerLinkedAura(), HasMechanic(), isAffectedOnSpell(), IsCritFromAbilityAura(), Player::Mount(), NetherChargeTimer::OnApply(), TriggerStrafe::OnApply(), DarknessOfSouls::OnApply(), spell_dark_transformation_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_dark_adherent_martyrdom_aura::OnApply(), spell_ingvar_transform_aura::OnApply(), TagGreaterFelfireDiemetradon::OnApply(), PossessionTransfer::OnApply(), WrathOfTheAstromancer::OnApply(), OgrilaFlasks::OnApply(), InebriateRemoval::OnApply(), OnAuraValueCalculate(), WarriorDevastate::OnEffectExecute(), GripOfSladran::OnPeriodicDummy(), spell_parachute_aura::OnPeriodicDummy(), spell_mana_barrier_aura::OnPeriodicTrigger(), WrathOfTheTitansProcAura::OnProc(), Icecrown25MeleeTrinket::OnProc(), spell_seed_of_corruption_npc::OnProc(), Vigilance::OnProc(), PeriodicDummyTick(), PeriodicTick(), ReapplyAffectedPassiveAuras(), Unit::RemoveAurasDueToSpellBySteal(), Unit::SendPeriodicAuraLog(), Spell::SpellStart(), TriggerSpell(), TriggerSpellWithValue(), AreaAura::Update(), and UpdateAuraScaling().
GetStackAmount()
uint32 Aura::GetStackAmount () const inline
Definition at line 491 of file SpellAuras.h.
References GetHolder(), and SpellAuraHolder::GetStackAmount().
Referenced by Spell::EffectSchoolDMG(), Unit::HandleAddFlatModifierAuraProc(), HandleAuraDamageShield(), HandleAuraDummy(), Unit::HandleDummyAuraProc(), Unit::HandleModRating(), HandlePeriodicDamage(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), Unit::HandleProcTriggerSpellAuraProc(), IsSimilarExistingAuraStronger(), spell_intense_cold_aura::OnApply(), spell_petrifying_grip_aura::OnApply(), GronnLordsGrasp::OnApply(), BraziersHit::OnApply(), TorchesCaught::OnApply(), WarriorDevastate::OnEffectExecute(), GripOfSladran::OnPeriodicDummy(), spell_permafrost_aura::OnPeriodicDummy(), BloodReserveEnchant::OnProc(), PeriodicDummyTick(), PeriodicTick(), and SetModifier().
GetTarget()
Unit* Aura::GetTarget () const inline
Definition at line 475 of file SpellAuras.h.
References GetHolder(), and SpellAuraHolder::GetTarget().
Referenced by ApplyModifier(), EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_crystal_channel_target(), EffectAuraDummy_npc_depleted_war_golem(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_oil_stained_wolf(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectAuraDummy_spell_aura_dummy_crates_carried(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), EffectAuraDummy_spell_aura_dummy_noxxion_spawns(), EffectAuraDummy_spell_aura_dummy_npc(), EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), EffectAuraDummy_spell_aura_dummy_sacrifice_beam(), OrbOfDeception::GetAuraScriptCustomizationValue(), GossipNPCAppearanceAllSpiritOfCompetition::GetAuraScriptCustomizationValue(), GossipNPCAppearanceAllPirateDay::GetAuraScriptCustomizationValue(), HandleAddModifier(), HandleAoECharm(), HandleArenaPreparation(), HandleAuraAddMechanicAbilities(), HandleAuraAllowFlight(), HandleAuraAllowOnlyAbility(), HandleAuraControlVehicle(), HandleAuraConvertRune(), HandleAuraDamageShield(), HandleAuraDummy(), HandleAuraEmpathy(), HandleAuraFakeInebriation(), HandleAuraFeatherFall(), HandleAuraGhost(), HandleAuraHover(), HandleAuraIncreaseBaseHealthPercent(), HandleAuraMirrorImage(), HandleAuraModAllCritChance(), HandleAuraModAttackPower(), HandleAuraModAttackPowerOfArmor(), HandleAuraModAttackPowerOfStatPercent(), HandleAuraModAttackPowerPercent(), HandleAuraModBaseResistancePercent(), HandleAuraModBlockPercent(), HandleAuraModCritPercent(), HandleAuraModDecreaseSpeed(), HandleAuraModDisarm(), HandleAuraModDispelImmunity(), HandleAuraModDmgImmunity(), HandleAuraModDodgePercent(), HandleAuraModEffectImmunity(), HandleAuraModExpertise(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseEnergyPercent(), HandleAuraModIncreaseFlightSpeed(), HandleAuraModIncreaseHealth(), HandleAuraModIncreaseHealthPercent(), HandleAuraModIncreaseMaxHealth(), HandleAuraModIncreaseMountedSpeed(), HandleAuraModIncreaseSpeed(), HandleAuraModIncreaseSwimSpeed(), HandleAuraModPacify(), HandleAuraModPacifyAndSilence(), HandleAuraModParryPercent(), HandleAuraModPetTalentsPoints(), HandleAuraModRangedAttackPower(), HandleAuraModRangedAttackPowerOfStatPercent(), HandleAuraModRangedAttackPowerPercent(), HandleAuraModRangedHaste(), HandleAuraModRegenInterrupt(), HandleAuraModResistance(), HandleAuraModResistanceExclusive(), HandleAuraModResistenceOfStatPercent(), HandleAuraModRoot(), HandleAuraModScale(), HandleAuraModSchoolImmunity(), HandleAuraModShapeshift(), HandleAuraModSilence(), HandleAuraModSkill(), HandleAuraModStalked(), HandleAuraModStat(), HandleAuraModStateImmunity(), HandleAuraModStun(), HandleAuraModTotalHealthPercentRegen(), HandleAuraModTotalManaPercentRegen(), HandleAuraModTotalThreat(), HandleAuraModUseNormalSpeed(), HandleAuraMounted(), HandleAuraOpenStable(), HandleAuraPeriodicDummy(), HandleAuraProcTriggerSpell(), HandleAuraRetainComboPoints(), HandleAuraSafeFall(), HandleAuraSetVehicleId(), HandleAuraStopNaturalManaRegen(), HandleAuraTrackCreatures(), HandleAuraTrackResources(), HandleAuraTrackStealthed(), HandleAuraTransform(), HandleAuraUntrackable(), HandleAuraWaterWalk(), HandleBindSight(), HandleChannelDeathItem(), HandleComprehendLanguage(), HandleDamagePercentTaken(), HandleDetectAmore(), HandleFactionOverride(), HandleFarSight(), HandleFeignDeath(), HandleForceMoveForward(), HandleForceReaction(), HandleInvisibility(), HandleInvisibilityDetect(), HandleManaShield(), HandleMirrorName(), HandleModAttackSpeed(), HandleModBaseResistance(), HandleModCastingSpeed(), HandleModCharm(), HandleModCombatSpeedPct(), HandleModConfuse(), HandleModDamageDone(), HandleModDamagePercentDone(), HandleModFear(), HandleModHealingDone(), HandleModHealingPCT(), HandleModHitChance(), HandleModManaRegen(), HandleModMechanicImmunity(), HandleModMechanicImmunityMask(), HandleModMeleeRangedSpeedPct(), HandleModMeleeSpeedPct(), HandleModOffhandDamagePercent(), HandleModPercentStat(), HandleModPossess(), HandleModPossessPet(), HandleModPowerCost(), HandleModPowerCostPCT(), HandleModPowerRegen(), HandleModPowerRegenPCT(), HandleModRating(), HandleModRatingFromStat(), HandleModResistancePercent(), HandleModSpellCritChance(), HandleModSpellCritChanceShool(), HandleModSpellDamagePercentFromAttackPower(), HandleModSpellDamagePercentFromStat(), HandleModSpellHealingPercentFromAttackPower(), HandleModSpellHealingPercentFromStat(), HandleModSpellHitChance(), HandleModStealth(), HandleModStealthDetect(), HandleModStealthLevel(), HandleModTargetArmorPct(), HandleModTargetResistance(), HandleModTaunt(), HandleModThreat(), HandleModTotalPercentStat(), HandleModUnattackable(), HandleModWaterBreathing(), HandleNoReagentUseAura(), HandleOverrideClassScript(), HandlePeriodicDamage(), HandlePeriodicEnergize(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), HandlePeriodicManaLeech(), HandlePeriodicTriggerSpell(), HandlePhase(), HandlePreventFleeing(), HandlePreventResurrection(), HandleRangedAmmoHaste(), HandleSchoolAbsorb(), HandleShapeshiftBoosts(), HandleShieldBlockValue(), HandleSpiritOfRedemption(), HandleTriggerLinkedAura(), HandleWaterBreathing(), IsCritFromAbilityAura(), IsSaveToDbAura(), WillOfTheNecropolis::OnAbsorb(), HodirsProtectiveGaze::OnAbsorb(), SnakeWrap::OnApply(), NetherChargeTimer::OnApply(), AshbringerItemAura::OnApply(), X52RocketHelmetAura::OnApply(), PowerCircleAura::OnApply(), IncreasedHealingDoneDummy::OnApply(), IncreasedHolyLightHealing::OnApply(), ArenaPreparation::OnApply(), InactiveBattleground::OnApply(), spell_repair_cannon_aura::OnApply(), DirebrewDisarmPrecast::OnApply(), PossessRazorgore::OnApply(), UnarmedWoodcutter::OnApply(), SparAuras::OnApply(), MoroesVanish::OnApply(), Enfeeble::OnApply(), spell_mana_rage_selin::OnApply(), EyeOfAcherus::OnApply(), AnastariPossess::OnApply(), HexOfJammalanAura::OnApply(), DeathCloudBrutallus::OnApply(), spell_break_ice::OnApply(), DarkFlameShadowAura::OnApply(), DarkFlameFireAura::OnApply(), FogOfCorruptionCharm::OnApply(), TriggerStrafe::OnApply(), Encapsulate::OnApply(), SpectralRealmAura::OnApply(), CurseOfBoundlessAgony::OnApply(), DarknessOfSouls::OnApply(), SinisterReflectionClone::OnApply(), OpenPortalFromShattrath::OnApply(), VengeanceOfTheBlueFlight::OnApply(), ShieldOfTheBlue::OnApply(), SpellFury::OnApply(), CallOfTheBeast::OnApply(), ThreateningGaze::OnApply(), RenatakiVanishTeleport::OnApply(), EternalSilence::OnApply(), CThunMouthTentacle::OnApply(), HuhuranWyvernSting::OnApply(), TrueFulfillment::OnApply(), MutateBug::OnApply(), ViscidusFreeze::OnApply(), spell_remove_mushroom_power::OnApply(), spell_web_door_aura::OnApply(), FlyingMachineControls::OnApply(), spell_corrupt_soul_aura::OnApply(), spell_strangulating_aura::OnApply(), spell_feigh_death_pos_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), spell_dark_transformation_aura::OnApply(), spell_dark_empowerment_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_dark_adherent_martyrdom_aura::OnApply(), RocketPack::OnApply(), WidowsEmbrace::OnApply(), MutatingInjection::OnApply(), AuraPreWarning::OnApply(), AuraWarning::OnApply(), ForcedObedience::OnApply(), ThaddiusCharge::OnApply(), spell_vortex_aura::OnApply(), spell_intense_cold_aura::OnApply(), spell_crystal_spike_visual_aura::OnApply(), spell_telestra_clone_dies_aura::OnApply(), spell_ride_oculus_drake_saddle::OnApply(), spell_twilight_shift_aura::OnApply(), spell_leave_twilight_realm_aura::OnApply(), spell_fiery_combustion_aura::OnApply(), spell_soul_consumption_aura::OnApply(), spell_petrifying_grip_aura::OnApply(), spell_carve_stone_aura::OnApply(), spell_ingvar_transform_aura::OnApply(), spell_awaken_subboss_aura::OnApply(), spell_freezing_cloud_aura::OnApply(), spell_create_spirit_fount_beam_aura::OnApply(), spell_protective_bubble_aura::OnApply(), spell_drained_aura::OnApply(), spell_void_shift_aura::OnApply(), CharmGeist::OnApply(), CharmDrakuruServant::OnApply(), DrakuramasTeleportScript01::OnApply(), DrakuramasTeleportScript02::OnApply(), DrakuramasTeleportScript03::OnApply(), DropDisguise::OnApply(), ScourgeDisguiseExpiring::OnApply(), HaveWitheredBatwing::OnApply(), HaveMuddyMireMaggot::OnApply(), HaveAmberseed::OnApply(), HaveChilledSerpentMucus::OnApply(), FetchAlchemistsApprentice::OnApply(), HarpoonersMark::OnApply(), ParasiticShadowfiendAura::OnApply(), SupremusRandomTarget::OnApply(), ShadowOfDeath::OnApply(), ShadowOfDeathRemove::OnApply(), VerasVanish::OnApply(), VerasDeadlyPoisonTick::OnApply(), Soaring::OnApply(), CoaxMarmot::OnApply(), VashjPersuasion::OnApply(), InsidiousWhisper::OnApply(), LeoWhirlwindAura::OnApply(), GronnLordsGrasp::OnApply(), ShadowGraspCube::OnApply(), ShadowGraspMagth::OnApply(), LivingFlareMaster::OnApply(), LivingFlareUnstable::OnApply(), CharmRavager::OnApply(), ScrapReaverSpell::OnApply(), RingOfFlame::OnApply(), TagGreaterFelfireDiemetradon::OnApply(), DragonmawIllusionBase::OnApply(), DragonmawIllusionTransform::OnApply(), PossessionTransfer::OnApply(), FlyingAttackAura::OnApply(), ShivanShapeshiftForm::OnApply(), BuildPortableFelCannon::OnApply(), WrathOfTheAstromancer::OnApply(), WOTAOldDOT::OnApply(), ShadowyDisguise::OnApply(), GiddyUp::OnApply(), RamsteinsSwiftWorkRam::OnApply(), AppleTrapFriendly::OnApply(), BrewfestBarkerBunny::OnApply(), GDRPeriodicDamage::OnApply(), OgrilaFlasks::OnApply(), TestRibbonPoleChannel::OnApply(), BraziersHit::OnApply(), TorchesCaught::OnApply(), InebriateRemoval::OnApply(), AuchenaiPossess::OnApply(), GettingSleepyAura::OnApply(), Drink::OnApply(), Stoned::OnApply(), SleepVisualFlavor::OnApply(), CallOfTheFalcon::OnApply(), DeathKnightDisease::OnApply(), DancingRuneWeapon::OnApply(), Brambles::OnApply(), RapidKilling::OnApply(), FingersOfFrostDummy::OnApply(), PainSuppression::OnApply(), LightwellRenew::OnApply(), GlyphOfLightwell::OnApply(), GlyphOfShadowWordDeath::OnApply(), DirtyDeeds::OnApply(), KillingSpree::OnApply(), SentryTotem::OnApply(), CurseOfDoom::OnApply(), SeedOfCorruption::OnApply(), DemonicCircleSummon::OnApply(), Overpower::OnApply(), SpellReflectionRaid::OnApply(), CurseOfBoundlessAgonyRemoval::OnApply(), DemoniacVisitation::OnApply(), GossipNPCAppearanceAllBrewfest::OnApply(), ShadowOfDeath::OnAuraDeathPrevention(), ScriptDevAIMgr::OnAuraDummy(), Icecrown25MeleeTrinket::OnAuraInit(), OnAuraValueCalculate(), BloodReserveEnchant::OnCheckProc(), SuddenDoom::OnCheckProc(), LockAndLoad::OnCheckProc(), DeathRuneDK::OnCheckProc(), FoodAnimation::OnHeartbeat(), DrinkAnimation::OnHeartbeat(), DigestiveAcidPeriodic::OnPeriodicCalculateAmount(), DeathAndDecay::OnPeriodicCalculateAmount(), DirebrewDisarmPrecast::OnPeriodicDummy(), spell_alluring_perfume_spill_aura::OnPeriodicDummy(), spell_irresistible_cologne_spill_aura::OnPeriodicDummy(), ForsakenSkill::OnPeriodicDummy(), SummonBloodElvesPeriodic::OnPeriodicDummy(), TransformVisualPeriodic::OnPeriodicDummy(), spell_summon_anubar_periodic_aura::OnPeriodicDummy(), spell_leeching_swarm_aura::OnPeriodicDummy(), MojoFrenzy::OnPeriodicDummy(), GripOfSladran::OnPeriodicDummy(), spell_soulstorm_visual_aura::OnPeriodicDummy(), spell_wailing_souls_aura::OnPeriodicDummy(), spell_permafrost_aura::OnPeriodicDummy(), RocketPackPeriodic::OnPeriodicDummy(), spell_crystal_spike_aura::OnPeriodicDummy(), spell_parachute_aura::OnPeriodicDummy(), ParachutePeriodicDummy::OnPeriodicDummy(), spell_summon_iron_dwarf_aura::OnPeriodicDummy(), spell_summon_iron_trogg_aura::OnPeriodicDummy(), spell_summon_malformed_ooze_aura::OnPeriodicDummy(), spell_summon_earthen_dwarf_aura::OnPeriodicDummy(), spell_frost_tomb_aura::OnPeriodicDummy(), spell_summon_gauntlet_mobs_periodic_aura::OnPeriodicDummy(), spell_splatter_aura::OnPeriodicDummy(), RandomIngredientAura::OnPeriodicDummy(), HarpoonersMark::OnPeriodicDummy(), SummonIceSpearKnockbackDelayer::OnPeriodicDummy(), NetherVaporLightning::OnPeriodicDummy(), GiddyUp::OnPeriodicDummy(), RamNeutral::OnPeriodicDummy(), RamTrot::OnPeriodicDummy(), RamCanter::OnPeriodicDummy(), RamGallop::OnPeriodicDummy(), MoleMachinePortSchedule::OnPeriodicDummy(), MoleMachinePortalSchedule::OnPeriodicDummy(), TrickyTreat::OnPeriodicDummy(), RibbonPoleDancerCheckAura::OnPeriodicDummy(), GossipNPCPeriodicTalk::OnPeriodicDummy(), HorsemanManiacalLaughDelayed::OnPeriodicDummy(), AllergiesAura::OnPeriodicDummy(), Drink::OnPeriodicDummy(), DeathRuneDK::OnPeriodicDummy(), FakeAggroRadius8YD::OnPeriodicDummy(), SummonGargoyle::OnPeriodicDummy(), ForceOfNatureSummon::OnPeriodicDummy(), ExplosiveShot::OnPeriodicDummy(), KillingSpree::OnPeriodicDummy(), PreyOnTheWeak::OnPeriodicDummy(), DemonicCircleSummon::OnPeriodicDummy(), NetherChargePassive::OnPeriodicTickEnd(), AnastariPossess::OnPeriodicTickEnd(), CurseOfBoundlessAgony::OnPeriodicTickEnd(), CurseOfBoundlessAgonyRemoval::OnPeriodicTickEnd(), SpellShadowPulsePeriodic::OnPeriodicTickEnd(), ActivateSunbladeProtectorChannel::OnPeriodicTickEnd(), MarkOfKazrogal::OnPeriodicTickEnd(), WebWrapDamage::OnPeriodicTickEnd(), TerokkAncientFlames::OnPeriodicTickEnd(), EredarPreGateBeam::OnPeriodicTickEnd(), GravityLapseKnockup::OnPeriodicTickEnd(), TestRibbonPoleChannel::OnPeriodicTickEnd(), GreaterInvisibilityMob::OnPeriodicTickEnd(), AuchenaiPossess::OnPeriodicTickEnd(), CurseOfPain::OnPeriodicTickEnd(), Regrowth::OnPeriodicTickEnd(), spell_gunship_cannon_fire_aura::OnPeriodicTrigger(), spell_explosive_barrage_aura::OnPeriodicTrigger(), spell_mana_barrier_aura::OnPeriodicTrigger(), FrostBlast::OnPeriodicTrigger(), spell_enervating_brand_aura::OnPeriodicTrigger(), Armageddon::OnPeriodicTrigger(), ShadowSpike::OnPeriodicTrigger(), EarthquakeGuardian::OnPeriodicTrigger(), PeriodicRotate::OnPeriodicTrigger(), PeriodicScarabTrigger::OnPeriodicTrigger(), ArmyOfTheDead::OnPeriodicTrigger(), SummonSkeletonsNoth::OnPeriodicTrigger(), PeriodicIceBolt::OnPeriodicTrigger(), ThaddiusCharge::OnPeriodicTrigger(), SpellAbsorption::OnPeriodicTrigger(), VerasDeadlyPoison::OnPeriodicTrigger(), SpoutTurning::OnPeriodicTrigger(), RapidRecuperationPeriodic::OnPeriodicTrigger(), FingersOfFrostDummy::OnProc(), FlagAuraBg::OnProc(), ViscidusFreeze::OnProc(), ViscidusFrostWeakness::OnProc(), SwiftHandOfJustice::OnProc(), BloodReserveEnchant::OnProc(), UnholyBlightDK::OnProc(), DeathRuneDK::OnProc(), HealthLeechPassive::OnProc(), SuddenDoom::OnProc(), DancingRuneWeapon::OnProc(), RoarOfSacrifice::OnProc(), JudgementsOfTheWise::OnProc(), EarthShield::OnProc(), ItemShamanT10Elemental2PBonus::OnProc(), AncestralAwakening::OnProc(), SoulLeech::OnProc(), SiphonLifeWotlk::OnProc(), PeriodicDummyTick(), PeriodicTick(), PickTargetsForSpellTrigger(), ReapplyAffectedPassiveAuras(), Unit::SendPeriodicAuraLog(), TriggerSpell(), AreaAura::Update(), PersistentAreaAura::Update(), and GameObjectAura::Update().
GetTriggerTarget()
virtual Unit* Aura::GetTriggerTarget () const inline virtual
Definition at line 516 of file SpellAuras.h.
References SpellAuraHolder::GetTarget(), and m_spellAuraHolder.
Referenced by PlagueWaveController::OnPeriodicTrigger(), TriggerSpell(), and TriggerSpellWithValue().
HandleAddModifier()
void Aura::HandleAddModifier (bool apply, bool Real)
Definition at line 1157 of file SpellAuras.cpp.
References ByteConverter::apply(), GetHolder(), GetSpellProto(), GetTarget(), SpellEntry::Id, Modifier::m_amount, Modifier::m_auraname, Modifier::m_miscvalue, m_modifier, m_spellmod, MAX_SPELLMOD, ReapplyAffectedPassiveAuras(), SpellAuraHolder::SetAuraCharges(), SpellEntry::spellPriority, SpellEntry::StackAmount, and TYPEID_PLAYER.
HandleAoECharm()
void Aura::HandleAoECharm (bool apply, bool Real)
Definition at line 4891 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), GetCasterGuid(), GetId(), Object::GetObjectGuid(), GetTarget(), Unit::TakeCharmOf(), and Unit::Uncharm().
HandleArenaPreparation()
void Aura::HandleArenaPreparation (bool apply, bool Real)
Definition at line 9417 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModFlag(), Unit::GetMaxHealth(), Unit::GetMaxPower(), GetTarget(), POWER_ENERGY, POWER_MANA, POWER_RAGE, POWER_RUNIC_POWER, Unit::SetHealth(), Unit::SetPower(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PREPARATION.
HandleAuraAddMechanicAbilities()
void Aura::HandleAuraAddMechanicAbilities (bool apply, bool Real)
Definition at line 9488 of file SpellAuras.cpp.
References ByteConverter::apply(), GetMiscValue(), GetTarget(), Object::GetTypeId(), PLAYER_FIELD_BYTES2, Object::SetUInt16Value(), sOverrideSpellDataStore, OverrideSpellDataEntry::Spells, and TYPEID_PLAYER.
HandleAuraAllowFlight()
void Aura::HandleAuraAllowFlight (bool apply, bool Real)
Definition at line 7894 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), and Unit::SetCanFly().
HandleAuraAllowOnlyAbility()
void Aura::HandleAuraAllowOnlyAbility (bool apply, bool real)
Definition at line 9808 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), PLAYER_ALLOW_ONLY_ABILITY, PLAYER_FLAGS, Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_ALLOW_ONLY_ABILITY, and TYPEID_PLAYER.
HandleAuraControlVehicle()
void Aura::HandleAuraControlVehicle (bool apply, bool Real)
Such auras are applied from a caster(=player) to a vehicle.
This has been verified using spell #49256
Definition at line 9445 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_TRACKING, VehicleInfo::Board(), UpdateData::BuildPacket(), Object::BuildValuesUpdateBlockForPlayer(), GetBasePoints(), GetCaster(), GetTarget(), Object::GetValuesCount(), Unit::GetVehicleInfo(), UpdateData::HasData(), UpdateMask::HasData(), Unit::IsVehicle(), m_removeMode, Object::MarkUpdateFieldsWithFlagForUpdate(), UpdateMask::SetCount(), UF_FLAG_OWNER_ONLY, and VehicleInfo::UnBoard().
HandleAuraConvertRune()
void Aura::HandleAuraConvertRune (bool apply, bool Real)
Definition at line 9600 of file SpellAuras.cpp.
References Player::AddRuneByAuraEffect(), ByteConverter::apply(), CLASS_DEATH_KNIGHT, Unit::getClass(), Player::GetCurrentRune(), Player::GetRuneCooldown(), GetSpellProto(), GetTarget(), m_effIndex, MAX_RUNES, Player::RemoveRunesByAura(), and TYPEID_PLAYER.
HandleAuraDamageShield()
void Aura::HandleAuraDamageShield (bool apply, bool real)
Definition at line 6252 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), GetSpellProto(), GetStackAmount(), GetTarget(), Modifier::m_amount, m_modifier, SPELL_DIRECT_DAMAGE, and Unit::SpellDamageBonusDone().
HandleAuraDetaunt()
void Aura::HandleAuraDetaunt (bool Apply, bool Real)
Definition at line 9662 of file SpellAuras.cpp.
References Unit::CanHaveThreatList(), GetCaster(), Unit::IsAlive(), and Unit::TauntUpdate().
HandleAuraDummy()
void Aura::HandleAuraDummy (bool apply, bool Real)
Definition at line 2403 of file SpellAuras.cpp.
References Unit::AddPetAura(), Unit::AddThreat(), Unit::addUnitState(), Unit::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_E, ByteConverter::apply(), Object::ApplyModFlag(), Object::ApplyModPositiveFloatValue(), Unit::ApplySpellImmune(), AREA_FLAG_CANNOT_FLY, AREA_FLAG_OUTDOOR_PVP, AURA_REMOVE_BY_DEATH, AURA_REMOVE_BY_DEFAULT, AURA_REMOVE_BY_DISPEL, AURA_REMOVE_BY_EXPIRE, AURA_REMOVE_BY_STACK, AURA_STATE_UNKNOWN22, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::clearUnitState(), CONDITION_FROM_HARDCODED, Unit::DealDamage(), DIRECT_DAMAGE, EFFECT_INDEX_0, EMOTE_STATE_NONE, EMOTE_STATE_WORK, Unit::FixateTarget(), AreaTableEntry::flags, FORM_CAT, FORM_MOONKIN, GENDER_MALE, GetAreaEntryByAreaID(), WorldObject::GetAreaId(), GetAuraDuration(), Unit::GetBaseRunSpeed(), GetCaster(), GetCasterGuid(), GetCastItemGuid(), Unit::getClass(), Map::GetCreature(), Map::GetDifficulty(), Object::GetEntry(), Unit::getGender(), Unit::GetHealth(), GetHolder(), Unit::getHostileRefManager(), GetId(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMiniPet(), GetMiscValue(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::GetOwner(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetSession(), Unit::GetShapeshiftForm(), WorldObject::GetSpawnerGuid(), GetSpellProto(), GetSpellSchoolMask(), GetStackAmount(), GetTarget(), HostileRefManager::GetThreatRedirectionTarget(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), Object::GetUInt32Value(), Unit::GetVehicleInfo(), WorldObject::GetZoneAndAreaId(), Unit::HandleEmote(), Unit::HasAura(), Unit::HasAuraType(), IMMUNITY_MECHANIC, IN_MILLISECONDS, INSTANCE_CONDITION_ID_LURKER, INSTANCE_CONDITION_ID_SCALDING_WATER, Unit::IsAlive(), WorldObject::IsBoarded(), Object::IsCreature(), Map::IsDungeon(), Object::IsInWorld(), Unit::IsNoWeaponShapeShift(), TransportInfo::IsOnVehicle(), Object::IsPlayer(), IsQuestTameSpell(), IsSpellHaveAura(), LANG_NO_FLY_ZONE, Modifier::m_amount, Unit::m_AuraFlags, m_effIndex, m_isPeriodic, m_modifier, m_periodicTimer, m_removeMode, SpellEntry::ManaCostPercentage, Unit::ModifyAuraState(), WorldObject::MonsterWhisper(), MOVE_RUN, MotionMaster::MoveFollow(), MotionMaster::MovePoint(), OBJECT_FIELD_SCALE_X, Modifier::periodictime, PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, PET_SAVE_REAGENTS, PLAY_TARGET, WorldObject::PlayDirectSound(), WorldObject::PlayDistanceSound(), QUEST_STATUS_INCOMPLETE, RAID_DIFFICULTY_10MAN_HEROIC, RAID_DIFFICULTY_10MAN_NORMAL, Unit::RemoveAurasDueToSpell(), Unit::RemoveAuraStack(), Object::RemoveFlag(), Unit::RemovePetAura(), Player::ResetDeathTimer(), HostileRefManager::ResetThreatRedirection(), roll_chance_i(), Spell::SelectMountByAreaAndSkill(), UnitAI::SendAIEvent(), WorldSession::SendPacket(), SpellAuraHolder::SetAuraCharges(), Unit::SetBaseRunSpeed(), Unit::setFaction(), Unit::SetFeignDeath(), Unit::SetFleeing(), Player::SetGhouled(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetStandState(), Unit::SetVisibility(), sLog, SMSG_FORCED_DEATH_UPDATE, sObjectMgr, SPELL_AURA_CONTROL_VEHICLE, SPELL_AURA_MOUNTED, SPELL_DIRECT_DAMAGE, SPELL_SCHOOL_MASK_NORMAL, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, Unit::SpellHealingBonusTaken(), SpellEntry::SpellIconID, sScriptDevAIMgr, sSpellMgr, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, VehicleInfo::UnBoard(), UNIT_AURAFLAG_ALIVE_INVISIBLE, UNIT_CREATED_BY_SPELL, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_FEIGN_DEATH, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_UNINTERACTIBLE, UNIT_STAND_STATE_CUSTOM, UNIT_STAND_STATE_SLEEP, UNIT_STAND_STATE_STAND, UNIT_STAT_MELEE_ATTACKING, UNIT_STAT_ROOT, UNIT_STAT_STUNNED, Unit::UpdateModelData(), Unit::UpdateSpeed(), urand(), VIRTUAL_ITEM_SLOT_0, VIRTUAL_ITEM_SLOT_1, VIRTUAL_ITEM_SLOT_2, and VISIBILITY_OFF.
HandleAuraEmpathy()
void Aura::HandleAuraEmpathy (bool apply, bool Real)
Definition at line 7816 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModUInt32Value(), Object::BuildValuesUpdateBlockForPlayerWithFlags(), CREATURE_TYPE_BEAST, CreatureInfo::CreatureType, GetCaster(), ObjectMgr::GetCreatureTemplate(), Object::GetEntry(), GetTarget(), Object::GetTypeId(), Object::IsPlayer(), UpdateData::SendData(), TYPEID_PLAYER, TYPEID_UNIT, UF_FLAG_DYNAMIC, UF_FLAG_SPECIAL_INFO, UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_SPECIALINFO.
HandleAuraFakeInebriation()
void Aura::HandleAuraFakeInebriation (bool apply, bool Real)
Definition at line 5492 of file SpellAuras.cpp.
References ByteConverter::apply(), GetBasePoints(), Object::GetInt32Value(), GetTarget(), Object::GetTypeId(), PLAYER_FAKE_INEBRIATION, Object::SetInt32Value(), TYPEID_PLAYER, and WorldObject::UpdateObjectVisibility().
HandleAuraFeatherFall()
void Aura::HandleAuraFeatherFall (bool apply, bool Real)
Definition at line 3966 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), and Unit::SetFeatherFall().
HandleAuraGhost()
void Aura::HandleAuraGhost (bool apply, bool Real)
Definition at line 7864 of file SpellAuras.cpp.
References ByteConverter::apply(), Player::GetGroup(), GetTarget(), GROUP_UPDATE_FLAG_STATUS, Unit::HasAuraType(), Object::IsPlayer(), PLAYER_FLAGS, PLAYER_FLAGS_GHOST, Object::RemoveFlag(), Unit::RemoveVisFlags(), Object::SetFlag(), Player::SetGroupUpdateFlag(), Unit::SetVisFlags(), Unit::SetWaterWalk(), SPELL_AURA_WATER_WALK, and UNIT_VIS_FLAG_GHOST.
HandleAuraHover()
void Aura::HandleAuraHover (bool apply, bool Real)
Definition at line 3975 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), and Unit::SetHover().
HandleAuraIncreaseBaseHealthPercent()
void Aura::HandleAuraIncreaseBaseHealthPercent (bool apply, bool Real)
Definition at line 7061 of file SpellAuras.cpp.
References ByteConverter::apply(), BASE_PCT, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, and UNIT_MOD_HEALTH.
HandleAuraMirrorImage()
void Aura::HandleAuraMirrorImage (bool apply, bool Real)
Definition at line 9536 of file SpellAuras.cpp.
References ByteConverter::apply(), CreatureModelInfo::gender, GetCaster(), Unit::getClass(), Unit::getGender(), Unit::GetNativeDisplayId(), Unit::GetPowerType(), Unit::getRace(), GetTarget(), Object::IsCreature(), Object::RemoveFlag(), Object::SetByteValue(), Unit::SetDisplayId(), Object::SetFlag(), sObjectMgr, UNIT_BYTES_0_OFFSET_CLASS, UNIT_BYTES_0_OFFSET_GENDER, UNIT_BYTES_0_OFFSET_POWER_TYPE, UNIT_BYTES_0_OFFSET_RACE, UNIT_FIELD_BYTES_0, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_CLONED, and CreatureInfo::UnitClass.
HandleAuraModAllCritChance()
void Aura::HandleAuraModAllCritChance (bool apply, bool Real)
Definition at line 9708 of file SpellAuras.cpp.
References ByteConverter::apply(), CRIT_PERCENTAGE, FLAT_MOD, GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_modifier, OFFHAND_CRIT_PERCENTAGE, RANGED_CRIT_PERCENTAGE, and TYPEID_PLAYER.
HandleAuraModAttackPower()
void Aura::HandleAuraModAttackPower (bool apply, bool Real)
Definition at line 7312 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, TOTAL_VALUE, and UNIT_MOD_ATTACK_POWER.
HandleAuraModAttackPowerOfArmor()
void Aura::HandleAuraModAttackPowerOfArmor (bool apply, bool Real)
Definition at line 7362 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleAuraModAttackPowerOfStatPercent()
void Aura::HandleAuraModAttackPowerOfStatPercent (bool apply, bool Real)
Definition at line 7351 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleAuraModAttackPowerPercent()
void Aura::HandleAuraModAttackPowerPercent (bool apply, bool Real)
Definition at line 7325 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, TOTAL_PCT, and UNIT_MOD_ATTACK_POWER.
HandleAuraModBaseResistancePercent()
void Aura::HandleAuraModBaseResistancePercent (bool apply, bool Real)
Definition at line 6585 of file SpellAuras.cpp.
References ByteConverter::apply(), BASE_PCT, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, and UNIT_MOD_RESISTANCE_START.
HandleAuraModBlockPercent()
void Aura::HandleAuraModBlockPercent (bool apply, bool Real)
Definition at line 7097 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, Unit::m_modBlockChance, m_modifier, and TYPEID_PLAYER.
HandleAuraModCritPercent()
void Aura::HandleAuraModCritPercent (bool apply, bool Real)
Definition at line 7123 of file SpellAuras.cpp.
References ByteConverter::apply(), CRIT_PERCENTAGE, SpellEntry::EquippedItemClass, FLAT_MOD, GetSpellProto(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, Unit::m_modCritChance, m_modifier, MAX_ATTACK, OFFHAND_CRIT_PERCENTAGE, RANGED_CRIT_PERCENTAGE, and TYPEID_PLAYER.
HandleAuraModDecreaseSpeed()
void Aura::HandleAuraModDecreaseSpeed (bool apply, bool Real)
Definition at line 5574 of file SpellAuras.cpp.
References GetTarget(), MOVE_FLIGHT, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, and Unit::UpdateSpeed().
HandleAuraModDisarm()
void Aura::HandleAuraModDisarm (bool apply, bool Real)
Definition at line 4988 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModFlag(), BASE_ATTACK, BASE_ATTACK_TIME, GetModifier(), GetTarget(), Object::GetTypeId(), Unit::HasAuraType(), Unit::IsNoWeaponShapeShift(), OFF_ATTACK, RANGED_ATTACK, Unit::SetAttackTime(), SPELL_AURA_MOD_DISARM, SPELL_AURA_MOD_DISARM_OFFHAND, SPELL_AURA_MOD_DISARM_RANGED, TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_DISARM_OFFHAND, UNIT_FLAG2_DISARM_RANGED, UNIT_FLAG_DISARMED, and Unit::UpdateDamagePhysical().
HandleAuraModDispelImmunity()
void Aura::HandleAuraModDispelImmunity (bool apply, bool Real)
Definition at line 5802 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellDispelImmunity(), GetTarget(), Modifier::m_miscvalue, and m_modifier.
HandleAuraModDispelResist()
void Aura::HandleAuraModDispelResist (bool apply, bool Real)
Definition at line 6693 of file SpellAuras.cpp.
References ByteConverter::apply().
HandleAuraModDmgImmunity()
void Aura::HandleAuraModDmgImmunity (bool apply, bool Real)
Definition at line 5790 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), GetCaster(), Unit::getHostileRefManager(), GetId(), GetTarget(), HostileRefManager::HandleSuppressed(), IMMUNITY_DAMAGE, Modifier::m_miscvalue, m_modifier, and TRIGGERED_OLD_TRIGGERED.
HandleAuraModDodgePercent()
void Aura::HandleAuraModDodgePercent (bool apply, bool Real)
Definition at line 7083 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, Unit::m_modDodgeChance, m_modifier, and TYPEID_PLAYER.
HandleAuraModEffectImmunity()
void Aura::HandleAuraModEffectImmunity (bool apply, bool Real)
Definition at line 5676 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_INTERRUPT_FLAG_INVULNERABILITY_BUFF_CANCELS, Player::GetBattleGround(), Player::GetCachedZoneId(), GetHolder(), GetSpellProto(), GetTarget(), Object::GetTypeId(), SpellEntry::Id, IMMUNITY_EFFECT, IsPositive(), PvPInfo::isPvPFlagCarrier, Modifier::m_miscvalue, m_modifier, Player::pvpInfo, Unit::RemoveAurasWithInterruptFlags(), sOutdoorPvPMgr, and TYPEID_PLAYER.
HandleAuraModExpertise()
void Aura::HandleAuraModExpertise (bool apply, bool Real)
Definition at line 7942 of file SpellAuras.cpp.
References BASE_ATTACK, GetTarget(), OFF_ATTACK, and TYPEID_PLAYER.
HandleAuraModIncreaseEnergy()
void Aura::HandleAuraModIncreaseEnergy (bool apply, bool Real)
Definition at line 7002 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_GAINED_STACK, GetId(), Unit::GetPower(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Modifier::m_recentAmount, m_removeMode, Unit::SetPower(), TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_POWER_START.
HandleAuraModIncreaseEnergyPercent()
void Aura::HandleAuraModIncreaseEnergyPercent (bool apply, bool Real)
Definition at line 7025 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Unit::ModifyPower(), TOTAL_PCT, and UNIT_MOD_POWER_START.
HandleAuraModIncreaseFlightSpeed()
void Aura::HandleAuraModIncreaseFlightSpeed (bool apply, bool Real)
Definition at line 5539 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), Unit::CastSpell(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HasAura(), IMMUNITY_MECHANIC, Modifier::m_auraname, m_modifier, MECHANIC_POLYMORPH, MOVE_FLIGHT, Unit::SetCanFly(), SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and Unit::UpdateSpeed().
HandleAuraModIncreaseHealth()
void Aura::HandleAuraModIncreaseHealth (bool apply, bool Real)
Definition at line 6894 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_DEATH, AURA_REMOVE_BY_EXPIRE, AURA_REMOVE_BY_GAINED_STACK, Unit::CastSpell(), Unit::GetHealth(), Unit::GetHealthPercent(), GetId(), Unit::GetMaxHealth(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, Modifier::m_recentAmount, m_removeMode, Unit::ModifyHealth(), Unit::SetHealth(), Unit::SetHealthPercent(), TOTAL_VALUE, TRIGGERED_OLD_TRIGGERED, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseHealthPercent()
void Aura::HandleAuraModIncreaseHealthPercent (bool apply, bool Real)
Definition at line 7036 of file SpellAuras.cpp.
References ByteConverter::apply(), GetId(), Unit::GetMaxHealth(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, Unit::ModifyHealth(), Unit::SetHealth(), TOTAL_PCT, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseMaxHealth()
void Aura::HandleAuraModIncreaseMaxHealth (bool apply, bool Real)
Definition at line 6986 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::GetHealth(), Unit::GetMaxHealth(), GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, Unit::SetHealth(), TOTAL_VALUE, and UNIT_MOD_HEALTH.
HandleAuraModIncreaseMountedSpeed()
void Aura::HandleAuraModIncreaseMountedSpeed (bool apply, bool Real)
Definition at line 5523 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), GetSpellProto(), GetTarget(), Unit::HasAura(), MOVE_RUN, TRIGGERED_OLD_TRIGGERED, and Unit::UpdateSpeed().
HandleAuraModIncreaseSpeed()
void Aura::HandleAuraModIncreaseSpeed (bool Apply, bool Real)
Definition at line 5514 of file SpellAuras.cpp.
References GetTarget(), MOVE_RUN, and Unit::UpdateSpeed().
HandleAuraModIncreaseSwimSpeed()
void Aura::HandleAuraModIncreaseSwimSpeed (bool Apply, bool Real)
Definition at line 5565 of file SpellAuras.cpp.
References GetTarget(), MOVE_SWIM, and Unit::UpdateSpeed().
HandleAuraModPacify()
void Aura::HandleAuraModPacify (bool apply, bool Real)
Definition at line 7847 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PACIFIED.
Referenced by HandleAuraModPacifyAndSilence().
HandleAuraModPacifyAndSilence()
void Aura::HandleAuraModPacifyAndSilence (bool apply, bool Real)
Definition at line 7855 of file SpellAuras.cpp.
References AI_EVENT_CUSTOM_A, ByteConverter::apply(), GetId(), GetTarget(), HandleAuraModPacify(), and HandleAuraModSilence().
HandleAuraModParryPercent()
void Aura::HandleAuraModParryPercent (bool apply, bool Real)
Definition at line 7070 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_modifier, Unit::m_modParryChance, and TYPEID_PLAYER.
HandleAuraModPetTalentsPoints()
void Aura::HandleAuraModPetTalentsPoints (bool Apply, bool Real)
Definition at line 4813 of file SpellAuras.cpp.
References GetTarget().
HandleAuraModRangedAttackPower()
void Aura::HandleAuraModRangedAttackPower (bool apply, bool Real)
Definition at line 7317 of file SpellAuras.cpp.
References ByteConverter::apply(), CLASSMASK_WAND_USERS, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, TOTAL_VALUE, and UNIT_MOD_ATTACK_POWER_RANGED.
HandleAuraModRangedAttackPowerOfStatPercent()
void Aura::HandleAuraModRangedAttackPowerOfStatPercent (bool apply, bool Real)
Definition at line 7340 of file SpellAuras.cpp.
References CLASSMASK_WAND_USERS, GetTarget(), and TYPEID_PLAYER.
HandleAuraModRangedAttackPowerPercent()
void Aura::HandleAuraModRangedAttackPowerPercent (bool apply, bool Real)
Definition at line 7331 of file SpellAuras.cpp.
References ByteConverter::apply(), CLASSMASK_WAND_USERS, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, m_modifier, TOTAL_PCT, and UNIT_MOD_ATTACK_POWER_RANGED.
HandleAuraModRangedHaste()
void Aura::HandleAuraModRangedHaste (bool apply, bool Real)
Definition at line 7296 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), GetTarget(), Modifier::m_amount, m_modifier, and RANGED_ATTACK.
HandleAuraModRegenInterrupt()
void Aura::HandleAuraModRegenInterrupt (bool apply, bool Real)
Definition at line 7111 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleAuraModResistance()
void Aura::HandleAuraModResistance (bool apply, bool Real)
Definition at line 6532 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsMod(), GetTarget(), Unit::GetTotalResistanceValue(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, TOTAL_VALUE, and UNIT_MOD_RESISTANCE_START.
HandleAuraModResistanceExclusive()
void Aura::HandleAuraModResistanceExclusive (bool apply, bool Real)
Definition at line 6485 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsMod(), Unit::GetAurasByType(), GetTarget(), Unit::GetTotalResistanceValue(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_auraname, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, TOTAL_VALUE, and UNIT_MOD_RESISTANCE_START.
HandleAuraModResistenceOfStatPercent()
void Aura::HandleAuraModResistenceOfStatPercent (bool apply, bool Real)
Definition at line 6761 of file SpellAuras.cpp.
References GetTarget(), Modifier::m_miscvalue, m_modifier, sLog, SPELL_SCHOOL_MASK_NORMAL, TYPEID_PLAYER, and Unit::UpdateArmor().
HandleAuraModRoot()
void Aura::HandleAuraModRoot (bool apply, bool Real)
Definition at line 5335 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_STATE_FROZEN, frozenAuraTypes, Unit::GetAurasByType(), GetCaster(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), Unit::HasAuraType(), Unit::ModifyAuraState(), Unit::SetImmobilizedState(), SPELL_AURA_MOD_ROOT, SPELL_AURA_NONE, and SPELL_SCHOOL_MASK_FROST.
HandleAuraModScale()
void Aura::HandleAuraModScale (bool apply, bool Real)
Definition at line 4675 of file SpellAuras.cpp.
References GetTarget(), Unit::GetTotalAuraModifier(), Object::SetObjectScale(), SPELL_AURA_MOD_SCALE, SPELL_AURA_MOD_SCALE_2, and Unit::UpdateModelData().
HandleAuraModSchoolImmunity()
void Aura::HandleAuraModSchoolImmunity (bool apply, bool Real)
Definition at line 5735 of file SpellAuras.cpp.
References Unit::addUnitState(), ByteConverter::apply(), Unit::ApplySpellImmune(), AURA_INTERRUPT_FLAG_INVULNERABILITY_BUFF_CANCELS, Unit::clearUnitState(), GetCaster(), Unit::getHostileRefManager(), GetId(), Unit::GetSpellAuraHolderMap(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), HostileRefManager::HandleSuppressed(), SpellEntry::HasAttribute(), Unit::HasAuraType(), SpellEntry::Id, IMMUNITY_SCHOOL, IsPositiveSpell(), Modifier::m_miscvalue, m_modifier, MECHANIC_BANISH, Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasWithInterruptFlags(), Object::RemoveFlag(), Object::SetFlag(), SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, SPELL_ATTR_NO_IMMUNITIES, SPELL_AURA_SCHOOL_IMMUNITY, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE, and UNIT_STAT_ISOLATED.
HandleAuraModShapeshift()
void Aura::HandleAuraModShapeshift (bool apply, bool Real)
Definition at line 4005 of file SpellAuras.cpp.
References ByteConverter::apply(), ApplyPercentModFloatVar(), AURA_INTERRUPT_FLAG_SHAPESHIFTING, WorldObject::CalculateSpellEffectValue(), Unit::CastCustomSpell(), Unit::CastSpell(), CLASS_DRUID, SpellEntry::Dispel, EFFECT_INDEX_0, FORM_AQUA, FORM_BATTLESTANCE, FORM_BEAR, FORM_BERSERKERSTANCE, FORM_CAT, FORM_DEFENSIVESTANCE, FORM_DIREBEAR, FORM_FLIGHT, FORM_FLIGHT_EPIC, FORM_MOONKIN, FORM_NONE, FORM_TRAVEL, FORM_TREE, GetAllSpellMechanicMask(), Unit::GetAurasByType(), GetAuraScriptCustomizationValue(), Unit::getClass(), Unit::GetDummyAura(), GetHolder(), GetId(), Unit::GetOverrideScript(), Unit::GetPower(), Unit::GetPowerType(), Unit::getRace(), Unit::getRaceMask(), Unit::GetShapeshiftForm(), Unit::GetSpellAuraHolder(), GetTarget(), Object::GetTypeId(), HandleShapeshiftBoosts(), Unit::HasAura(), Unit::HasSpell(), HORDE, SpellEntry::Id, irand(), SQLStorage::LookupEntry(), SpellAuraHolder::m_auras, Modifier::m_miscvalue, m_modifier, Unit::m_threatModifier, MAX_SPELL_SCHOOL, MECHANIC_NOT_REMOVED_BY_SHAPESHIFT, MECHANIC_SNARE, SpellShapeshiftFormEntry::modelID_A, SpellShapeshiftFormEntry::modelID_H, PLAYERSPELL_REMOVED, POWER_ENERGY, POWER_MANA, POWER_RAGE, Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasDueToSpellByCancel(), Unit::RemoveAurasWithInterruptFlags(), Unit::RemoveSpellsCausingAura(), Unit::RestoreDisplayId(), Unit::SetDisplayId(), Unit::SetPower(), Unit::SetPowerType(), Unit::SetShapeshiftForm(), sLog, sObjectMgr, SPELL_AURA_DUMMY, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_SHAPESHIFT, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellShapeshiftFormEntry::spellId, sSpellShapeshiftFormStore, sSpellTemplate, Player::TeamForRace(), TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandleAuraModSilence()
void Aura::HandleAuraModSilence (bool apply, bool Real)
Definition at line 5386 of file SpellAuras.cpp.
References ByteConverter::apply(), CURRENT_MAX_SPELL, CURRENT_MELEE_SPELL, Unit::GetCurrentSpell(), GetTarget(), Unit::HasAuraType(), Unit::InterruptSpell(), Object::RemoveFlag(), Object::SetFlag(), SPELL_AURA_MOD_SILENCE, SPELL_PREVENTION_TYPE_SILENCE, UNIT_FIELD_FLAGS, and UNIT_FLAG_SILENCED.
Referenced by HandleAuraModPacifyAndSilence().
HandleAuraModSkill()
void Aura::HandleAuraModSkill (bool apply, bool Real)
Definition at line 4540 of file SpellAuras.cpp.
References ByteConverter::apply(), GetModifier(), GetSpellProto(), GetTarget(), Modifier::m_amount, Modifier::m_auraname, m_effIndex, Player::ModifySkillBonus(), SPELL_AURA_MOD_SKILL_TALENT, and TYPEID_PLAYER.
HandleAuraModStalked()
void Aura::HandleAuraModStalked (bool apply, bool Real)
Definition at line 5846 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::RemoveFlag(), Object::SetFlag(), UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_TRACK_UNIT.
HandleAuraModStat()
void Aura::HandleAuraModStat (bool apply, bool Real)
Definition at line 6603 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyStatBuffMod(), AURA_REMOVE_BY_GAINED_STACK, Unit::CastCustomSpell(), Unit::GetAurasByType(), GetCaster(), GetCasterGuid(), GetEffIndex(), GetId(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Modifier::m_recentAmount, m_removeMode, MAX_STATS, Unit::RemoveAurasTriggeredBySpell(), sLog, SPELL_AURA_OVERRIDE_CLASS_SCRIPTS, STAT_STRENGTH, TOTAL_VALUE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleAuraModStateImmunity()
void Aura::HandleAuraModStateImmunity (bool apply, bool Real)
Definition at line 5715 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), Unit::GetAurasByType(), GetSpellProto(), GetTarget(), IMMUNITY_STATE, Modifier::m_miscvalue, m_modifier, Unit::RemoveAurasDueToSpell(), and SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT.
HandleAuraModStun()
void Aura::HandleAuraModStun (bool apply, bool Real)
Definition at line 5045 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_D, ByteConverter::apply(), AURA_INTERRUPT_FLAG_DAMAGE, AURA_STATE_FROZEN, Unit::CastSpell(), frozenAuraTypes, Unit::GetAurasByType(), GetCaster(), Unit::getHostileRefManager(), GetId(), Object::GetObjectGuid(), WorldObject::GetOrientation(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), Object::GetTypeId(), HostileRefManager::HandleSuppressed(), Unit::HasAuraType(), Object::IsInWorld(), Object::IsPlayer(), Unit::IsStunned(), SQLStorage::LookupEntry(), Unit::ModifyAuraState(), Unit::SetFacingTo(), Unit::SetStandState(), Unit::SetStunned(), sLog, SPELL_AURA_MOD_STUN, SPELL_AURA_NONE, SPELL_SCHOOL_MASK_FROST, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and UNIT_STAND_STATE_DEAD.
HandleAuraModTotalHealthPercentRegen()
void Aura::HandleAuraModTotalHealthPercentRegen (bool apply, bool Real)
Definition at line 6781 of file SpellAuras.cpp.
References ByteConverter::apply(), GetId(), GetTarget(), m_isPeriodic, Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
HandleAuraModTotalManaPercentRegen()
void Aura::HandleAuraModTotalManaPercentRegen (bool apply, bool Real)
Definition at line 6793 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, ByteConverter::apply(), AURA_REMOVE_BY_DEFAULT, GetId(), GetTarget(), Object::GetTypeId(), m_isPeriodic, m_modifier, m_periodicTimer, m_removeMode, Modifier::periodictime, UnitAI::SendAIEvent(), and TYPEID_UNIT.
HandleAuraModTotalThreat()
void Aura::HandleAuraModTotalThreat (bool apply, bool Real)
Definition at line 5456 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), Unit::getHostileRefManager(), GetTarget(), Object::GetTypeId(), Unit::IsAlive(), Modifier::m_amount, m_modifier, HostileRefManager::threatTemporaryFade(), and TYPEID_PLAYER.
HandleAuraModUseNormalSpeed()
void Aura::HandleAuraModUseNormalSpeed (bool Apply, bool Real)
Definition at line 5588 of file SpellAuras.cpp.
References GetTarget(), MOVE_FLIGHT, MOVE_RUN, MOVE_SWIM, and Unit::UpdateSpeed().
HandleAuraMounted()
void Aura::HandleAuraMounted (bool apply, bool Real)
Definition at line 3908 of file SpellAuras.cpp.
References ByteConverter::apply(), Creature::ChooseDisplayId(), CreatureInfo::Entry, ObjectMgr::GetCreatureTemplate(), GetTarget(), Object::GetTypeId(), VehicleInfo::GetVehicleEntry(), Unit::GetVehicleInfo(), Unit::IsVehicle(), Modifier::m_amount, VehicleEntry::m_ID, Modifier::m_miscvalue, m_modifier, CreatureModelInfo::modelid, Unit::Mount(), Object::RemoveFlag(), Object::SetFlag(), Unit::SetVehicleId(), sLog, sObjectMgr, TYPEID_PLAYER, UNIT_NPC_FLAG_PLAYER_VEHICLE, UNIT_NPC_FLAGS, Unit::Unmount(), and CreatureInfo::VehicleTemplateId.
HandleAuraOpenStable()
void Aura::HandleAuraOpenStable (bool apply, bool Real)
Definition at line 9523 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::GetObjectGuid(), Player::GetSession(), GetTarget(), WorldSession::SendStablePet(), and TYPEID_PLAYER.
HandleAuraPeriodicDummy()
void Aura::HandleAuraPeriodicDummy (bool apply, bool Real)
Definition at line 6058 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, ByteConverter::apply(), Unit::CastSpell(), EQUIPMENT_SLOT_MAINHAND, GetAuraDuration(), GetCaster(), Unit::GetCharm(), GetHolder(), Unit::GetSpellAuraHolder(), GetSpellProto(), GetTarget(), Object::GetTypeId(), SpellEntry::Id, INVENTORY_SLOT_BAG_0, m_isPeriodic, Unit::RemoveAurasDueToSpell(), UnitAI::SendAIEvent(), SPELLFAMILY_GENERIC, SPELLFAMILY_ROGUE, SpellEntry::SpellFamilyName, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, and VIRTUAL_ITEM_SLOT_0.
HandleAuraPowerBurn()
void Aura::HandleAuraPowerBurn (bool apply, bool Real)
Definition at line 6048 of file SpellAuras.cpp.
References ByteConverter::apply(), and m_isPeriodic.
HandleAuraProcTriggerSpell()
void Aura::HandleAuraProcTriggerSpell (bool apply, bool Real)
Definition at line 5811 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), GetCaster(), GetHolder(), Unit::getHostileRefManager(), GetId(), GetTarget(), Unit::RemoveAurasDueToSpell(), HostileRefManager::ResetThreatRedirection(), Unit::SetAlwaysHit(), SpellAuraHolder::SetAuraCharges(), and TRIGGERED_OLD_TRIGGERED.
HandleAuraRetainComboPoints()
void Aura::HandleAuraRetainComboPoints (bool apply, bool Real)
Definition at line 7977 of file SpellAuras.cpp.
References Unit::AddComboPoints(), ByteConverter::apply(), AURA_REMOVE_BY_EXPIRE, Unit::GetComboTargetGuid(), GetTarget(), ObjectAccessor::GetUnit(), Modifier::m_amount, m_modifier, m_removeMode, and TYPEID_PLAYER.
HandleAuraSafeFall()
void Aura::HandleAuraSafeFall (bool Apply, bool Real)
Definition at line 9676 of file SpellAuras.cpp.
References GetHolder(), GetId(), GetTarget(), SPELLAURAHOLDER_STATE_DB_LOAD, and TYPEID_PLAYER.
HandleAuraSetVehicleId()
void Aura::HandleAuraSetVehicleId (bool apply, bool Real)
Definition at line 9735 of file SpellAuras.cpp.
References ByteConverter::apply(), GetMiscValue(), GetTarget(), and Unit::SetVehicleId().
HandleAuraStopNaturalManaRegen()
void Aura::HandleAuraStopNaturalManaRegen (bool apply, bool Real)
Definition at line 9727 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModFlag(), GetTarget(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_REGENERATE_POWER.
HandleAuraTrackCreatures()
void Aura::HandleAuraTrackCreatures (bool apply, bool Real)
Definition at line 4645 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_miscvalue, m_modifier, PLAYER_TRACK_CREATURES, Object::RemoveFlag(), Object::SetFlag(), and TYPEID_PLAYER.
HandleAuraTrackResources()
void Aura::HandleAuraTrackResources (bool apply, bool Real)
Definition at line 4656 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_miscvalue, m_modifier, PLAYER_TRACK_RESOURCES, Object::RemoveFlag(), Object::SetFlag(), and TYPEID_PLAYER.
HandleAuraTrackStealthed()
void Aura::HandleAuraTrackStealthed (bool apply, bool Real)
Definition at line 4667 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModByteFlag(), GetTarget(), PLAYER_FIELD_BYTE_TRACK_STEALTHED, PLAYER_FIELD_BYTES, and TYPEID_PLAYER.
HandleAuraTransform()
void Aura::HandleAuraTransform (bool apply, bool Real)
Definition at line 4294 of file SpellAuras.cpp.
References ByteConverter::apply(), Creature::ChooseDisplayId(), CreatureInfo::EquipmentTemplateId, GENDER_FEMALE, GENDER_MALE, GENDER_NONE, GetAuraScriptCustomizationValue(), Creature::GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), Unit::getGender(), GetHolder(), GetId(), Unit::getRace(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::IsMounted(), Creature::LoadEquipment(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, SpellEntry::Mechanic, MECHANIC_POLYMORPH, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_GOBLIN, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD, Unit::RemoveSpellsCausingAura(), Unit::RestoreDisplayId(), roll_chance_i(), Unit::SetDisplayId(), sLog, SPELL_AURA_MOUNTED, TYPEID_PLAYER, TYPEID_UNIT, and Unit::Unmount().
HandleAuraUntrackable()
void Aura::HandleAuraUntrackable (bool apply, bool Real)
Definition at line 7839 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Unit::RemoveVisFlags(), Unit::SetVisFlags(), and UNIT_VIS_FLAG_UNTRACKABLE.
HandleAuraWaterWalk()
void Aura::HandleAuraWaterWalk (bool apply, bool Real)
Definition at line 3957 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), and Unit::SetWaterWalk().
HandleBindSight()
void Aura::HandleBindSight (bool apply, bool Real)
Definition at line 4619 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), GetTarget(), Object::GetTypeId(), Camera::ResetView(), Camera::SetView(), and TYPEID_PLAYER.
HandleChannelDeathItem()
void Aura::HandleChannelDeathItem (bool apply, bool Real)
Definition at line 4555 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_DEATH, Unit::CastSpell(), SpellEntry::EffectItemType, EQUIP_ERR_OK, Unit::GetAurasByType(), GetCaster(), Object::GetObjectGuid(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HasAura(), Modifier::m_amount, m_effIndex, m_modifier, m_removeMode, NULL_BAG, NULL_SLOT, roll_chance_i(), SPELL_AURA_CHANNEL_DEATH_ITEM, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and TYPEID_UNIT.
HandleComprehendLanguage()
void Aura::HandleComprehendLanguage (bool apply, bool Real)
Definition at line 6886 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_COMPREHEND_LANG.
HandleDamagePercentTaken()
void Aura::HandleDamagePercentTaken (bool apply, bool Real)
Definition at line 6221 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), EFFECT_INDEX_0, Unit::GetAura(), GetCasterGuid(), Object::GetObjectGuid(), GetSpellProto(), GetTarget(), Object::GetTypeId(), SpellEntry::Id, SpellEntry::IsFitToFamily(), Modifier::m_amount, m_isPeriodic, m_modifier, SPELLFAMILY_PALADIN, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandleDetectAmore()
void Aura::HandleDetectAmore (bool apply, bool Real)
Definition at line 5327 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModByteFlag(), GetMiscValue(), GetTarget(), and PLAYER_FIELD_BYTES2.
HandleFactionOverride()
void Aura::HandleFactionOverride (bool apply, bool Real)
Definition at line 9758 of file SpellAuras.cpp.
References ByteConverter::apply(), GetMiscValue(), GetTarget(), Unit::RemoveUnattackableTargets(), Unit::RestoreOriginalFaction(), Unit::setFaction(), and sFactionTemplateStore.
HandleFarSight()
void Aura::HandleFarSight (bool apply, bool Real)
Definition at line 4632 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), GetTarget(), Object::GetTypeId(), Camera::ResetView(), Camera::SetView(), and TYPEID_PLAYER.
HandleFeignDeath()
void Aura::HandleFeignDeath (bool apply, bool Real)
Definition at line 4944 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CalculateSpellMissChance(), Unit::getAttackers(), GetCasterGuid(), GetId(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), Unit::HasAuraType(), Object::HasFlag(), Unit::InterruptSpellsCastedOnMe(), roll_chance_f(), Unit::SetFeignDeath(), SPELL_AURA_FEIGN_DEATH, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
HandleForceMoveForward()
void Aura::HandleForceMoveForward (bool apply, bool Real)
Definition at line 7931 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::RemoveFlag(), Object::SetFlag(), UNIT_FIELD_FLAGS_2, and UNIT_FLAG2_FORCE_MOVE.
HandleForceReaction()
void Aura::HandleForceReaction (bool apply, bool Real)
Definition at line 4519 of file SpellAuras.cpp.
References ByteConverter::apply(), ReputationMgr::ApplyForceReaction(), Player::GetReputationMgr(), Player::GetReputationRank(), GetTarget(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, REP_FRIENDLY, ReputationMgr::SendForceReactions(), Unit::StopAttackFaction(), and TYPEID_PLAYER.
HandleInvisibility()
void Aura::HandleInvisibility (bool apply, bool Real)
Definition at line 5260 of file SpellAuras.cpp.
References VisibilityData::AddInvisibilityValue(), ByteConverter::apply(), AURA_INTERRUPT_FLAG_STEALTH_INVIS_CANCELS, Unit::CastSpell(), GetId(), VisibilityData::GetInvisibilityMask(), VisibilityData::GetInvisibilityValue(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::GetVisibility(), WorldObject::GetVisibilityData(), Unit::HasAuraType(), Object::IsInWorld(), Modifier::m_amount, m_effIndex, Modifier::m_miscvalue, m_modifier, PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW, PLAYER_FIELD_BYTES2, Unit::RemoveAurasWithInterruptFlags(), Object::RemoveByteFlag(), Object::SetByteFlag(), VisibilityData::SetInvisibilityMask(), Unit::SetVisibilityWithoutUpdate(), SPELL_AURA_MOD_STEALTH, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, Unit::UpdateVisibilityAndView(), VISIBILITY_GROUP_INVISIBILITY, VISIBILITY_OFF, and VISIBILITY_ON.
HandleInvisibilityDetect()
void Aura::HandleInvisibilityDetect (bool apply, bool Real)
Definition at line 5311 of file SpellAuras.cpp.
References VisibilityData::AddInvisibilityDetectValue(), ByteConverter::apply(), Unit::GetAurasByType(), GetTarget(), Object::GetTypeId(), WorldObject::GetVisibilityData(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, VisibilityData::SetInvisibilityDetectMask(), SPELL_AURA_MOD_INVISIBILITY_DETECTION, and TYPEID_PLAYER.
HandleManaShield()
void Aura::HandleManaShield (bool apply, bool Real)
Definition at line 9384 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), Modifier::m_amount, m_modifier, SPELLFAMILY_MAGE, and TYPEID_PLAYER.
HandleMirrorName()
void Aura::HandleMirrorName (bool apply, bool Real)
Definition at line 9577 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCaster(), WorldObject::GetName(), GetTarget(), Object::GetTypeId(), CreatureInfo::Name, WorldObject::SetName(), and TYPEID_UNIT.
HandleModAttackSpeed()
void Aura::HandleModAttackSpeed (bool apply, bool Real)
Definition at line 7281 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), BASE_ATTACK, GetTarget(), Modifier::m_amount, and m_modifier.
HandleModBaseResistance()
void Aura::HandleModBaseResistance (bool apply, bool Real)
Definition at line 6571 of file SpellAuras.cpp.
References ByteConverter::apply(), BASE_VALUE, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, and UNIT_MOD_RESISTANCE_START.
HandleModCastingSpeed()
void Aura::HandleModCastingSpeed (bool apply, bool Real)
Definition at line 7228 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyCastTimePercentMod(), GetAmount(), Unit::GetAurasByType(), GetId(), GetTarget(), Modifier::m_amount, Modifier::m_auraname, and m_modifier.
HandleModCharm()
void Aura::HandleModCharm (bool apply, bool Real)
Definition at line 4823 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::BreakCharmOutgoing(), UpdateData::BuildPacket(), Object::BuildValuesUpdateBlockForPlayer(), Creature::ForcedDespawn(), GetCaster(), GetCasterGuid(), GetId(), Object::GetObjectGuid(), GetTarget(), Object::GetTypeId(), Object::GetValuesCount(), UpdateData::HasData(), UpdateMask::HasData(), Object::MarkUpdateFieldsWithFlagForUpdate(), Unit::RemoveAurasDueToSpell(), Player::SendDirectMessage(), UpdateMask::SetCount(), Unit::TakeCharmOf(), TYPEID_PLAYER, TYPEID_UNIT, UF_FLAG_OWNER_ONLY, and Unit::Uncharm().
HandleModCombatSpeedPct()
void Aura::HandleModCombatSpeedPct (bool apply, bool Real)
Definition at line 7272 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), Unit::ApplyCastTimePercentMod(), BASE_ATTACK, GetTarget(), Modifier::m_amount, m_modifier, OFF_ATTACK, and RANGED_ATTACK.
HandleModConfuse()
void Aura::HandleModConfuse (bool apply, bool Real)
Definition at line 4913 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCasterGuid(), Unit::getHostileRefManager(), GetId(), GetTarget(), HostileRefManager::HandleSuppressed(), Unit::SetConfused(), and SPELL_AURA_MOD_CONFUSE.
HandleModDamageDone()
void Aura::HandleModDamageDone (bool apply, bool Real)
Definition at line 7375 of file SpellAuras.cpp.
References ByteConverter::apply(), SpellEntry::EquippedItemClass, Unit::GetPet(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Object::IsPlayer(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_ATTACK, SPELL_SCHOOL_MASK_NORMAL, TOTAL_VALUE, TYPEID_PLAYER, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, UNIT_MOD_DAMAGE_RANGED, and Unit::UpdateScalingAuras().
HandleModDamagePercentDone()
void Aura::HandleModDamagePercentDone (bool apply, bool Real)
Definition at line 7423 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModSignedFloatValue(), AURA_REMOVE_BY_EXPIRE, Unit::CastSpell(), DEBUG_FILTER_LOG, SpellEntry::EquippedItemClass, SpellEntry::EquippedItemInventoryTypeMask, GetId(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), LOG_FILTER_SPELL_CAST, Modifier::m_amount, Modifier::m_miscvalue, m_modifier, m_positive, m_removeMode, MAX_ATTACK, MAX_SPELL_SCHOOL, PLAYER_FIELD_MOD_DAMAGE_DONE_PCT, SPELL_SCHOOL_HOLY, SPELL_SCHOOL_MASK_MAGIC, SPELL_SCHOOL_MASK_NORMAL, TOTAL_PCT, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, and UNIT_MOD_DAMAGE_RANGED.
HandleModFear()
void Aura::HandleModFear (bool apply, bool Real)
Definition at line 4927 of file SpellAuras.cpp.
References ByteConverter::apply(), GetCasterGuid(), Unit::getHostileRefManager(), GetId(), GetTarget(), HostileRefManager::HandleSuppressed(), Unit::SetFleeing(), and SPELL_AURA_MOD_FEAR.
HandleModHealingDone()
void Aura::HandleModHealingDone (bool Apply, bool Real)
Definition at line 6719 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModHealingPCT()
void Aura::HandleModHealingPCT (bool apply, bool real)
Definition at line 6858 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), GetId(), GetTarget(), Unit::RemoveAurasDueToSpell(), and TRIGGERED_OLD_TRIGGERED.
HandleModHitChance()
void Aura::HandleModHitChance (bool apply, bool Real)
Definition at line 7158 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_modifier, Unit::m_modMeleeHitChance, Unit::m_modRangedHitChance, and TYPEID_PLAYER.
HandleModManaRegen()
void Aura::HandleModManaRegen (bool apply, bool Real)
Definition at line 6873 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModMechanicImmunity()
void Aura::HandleModMechanicImmunity (bool apply, bool Real)
Definition at line 5605 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), EFFECT_INDEX_0, GetId(), Unit::GetOwner(), GetSpellProto(), GetTarget(), Object::GetTypeId(), SpellEntry::Id, IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK, IMMUNITY_MECHANIC, IsSpellRemoveAllMovementAndControlLossEffects(), m_effIndex, Modifier::m_miscvalue, m_modifier, MECHANIC_IMMUNE_SHIELD, Unit::RemoveAurasAtMechanicImmunity(), Unit::RemoveRankAurasDueToSpell(), WorldObject::RemoveSpellCooldown(), Unit::RemoveSpellsCausingAura(), SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, SPELL_AURA_MOD_STALKED, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandleModMechanicImmunityMask()
void Aura::HandleModMechanicImmunityMask (bool apply, bool Real)
Definition at line 5665 of file SpellAuras.cpp.
References ByteConverter::apply(), GetId(), GetSpellProto(), GetTarget(), Modifier::m_miscvalue, m_modifier, Unit::RemoveAurasAtMechanicImmunity(), and SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT.
HandleModMeleeRangedSpeedPct()
void Aura::HandleModMeleeRangedSpeedPct (bool apply, bool Real)
Definition at line 7248 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), BASE_ATTACK, GetAmount(), Unit::GetAurasByType(), GetId(), GetTarget(), Modifier::m_amount, Modifier::m_auraname, m_modifier, OFF_ATTACK, and RANGED_ATTACK.
HandleModMeleeSpeedPct()
void Aura::HandleModMeleeSpeedPct (bool apply, bool Real)
Definition at line 7286 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_C, ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), BASE_ATTACK, GetId(), GetTarget(), Modifier::m_amount, m_modifier, OFF_ATTACK, and UnitAI::SendAIEvent().
HandleModOffhandDamagePercent()
void Aura::HandleModOffhandDamagePercent (bool apply, bool Real)
Definition at line 7489 of file SpellAuras.cpp.
References ByteConverter::apply(), DEBUG_FILTER_LOG, GetTarget(), Unit::HandleStatModifier(), LOG_FILTER_SPELL_CAST, Modifier::m_amount, m_modifier, TOTAL_PCT, and UNIT_MOD_DAMAGE_OFFHAND.
HandleModPercentStat()
void Aura::HandleModPercentStat (bool apply, bool Real)
Definition at line 6654 of file SpellAuras.cpp.
References ByteConverter::apply(), BASE_PCT, GetTarget(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_STATS, sLog, STAT_STRENGTH, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleModPossess()
void Aura::HandleModPossess (bool apply, bool Real)
Definition at line 4684 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::BreakCharmOutgoing(), UpdateData::BuildPacket(), Object::BuildValuesUpdateBlockForPlayerWithFlags(), Unit::CastSpell(), CURRENT_CHANNELED_SPELL, Creature::ForcedDespawn(), GetCaster(), GetCasterGuid(), GetId(), Object::GetObjectGuid(), Creature::GetRespawnCoord(), GetSpellProto(), GetTarget(), Object::GetTypeId(), UpdateData::HasData(), Unit::InterruptSpell(), Object::IsPlayer(), Unit::NearTeleportTo(), Unit::RemoveAurasDueToSpell(), Unit::TakePossessOf(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, UF_FLAG_OWNER_ONLY, Unit::Uncharm(), and urand().
HandleModPossessPet()
void Aura::HandleModPossessPet (bool apply, bool Real)
Definition at line 4789 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::BreakCharmOutgoing(), GetCaster(), GetTarget(), Object::GetTypeId(), Creature::IsPet(), Unit::TakePossessOf(), TYPEID_PLAYER, TYPEID_UNIT, and Unit::Uncharm().
HandleModPowerCost()
void Aura::HandleModPowerCost (bool apply, bool Real)
Definition at line 7522 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModInt32Value(), GetTarget(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, and UNIT_FIELD_POWER_COST_MODIFIER.
HandleModPowerCostPCT()
void Aura::HandleModPowerCostPCT (bool apply, bool Real)
Definition at line 7504 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModSignedFloatValue(), AURA_REMOVE_BY_EXPIRE, AURA_REMOVE_BY_GAINED_STACK, Unit::CastSpell(), GetId(), GetTarget(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Modifier::m_recentAmount, m_removeMode, MAX_SPELL_SCHOOL, TRIGGERED_OLD_TRIGGERED, and UNIT_FIELD_POWER_COST_MULTIPLIER.
HandleModPowerRegen()
void Aura::HandleModPowerRegen (bool apply, bool Real)
Definition at line 6819 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::GetPowerType(), GetTarget(), m_isPeriodic, Modifier::m_miscvalue, m_modifier, m_periodicTimer, Modifier::periodictime, POWER_MANA, POWER_RAGE, and TYPEID_PLAYER.
HandleModPowerRegenPCT()
void Aura::HandleModPowerRegenPCT (bool Apply, bool Real)
Definition at line 6842 of file SpellAuras.cpp.
References GetTarget(), Modifier::m_miscvalue, m_modifier, POWER_ENERGY, POWER_MANA, and TYPEID_PLAYER.
HandleModRating()
void Aura::HandleModRating (bool apply, bool Real)
Definition at line 7903 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_COMBAT_RATING, and TYPEID_PLAYER.
HandleModRatingFromStat()
void Aura::HandleModRatingFromStat (bool apply, bool Real)
Definition at line 7917 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_miscvalue, m_modifier, MAX_COMBAT_RATING, and TYPEID_PLAYER.
HandleModRegen()
void Aura::HandleModRegen (bool apply, bool Real)
Definition at line 6810 of file SpellAuras.cpp.
References ByteConverter::apply(), m_isPeriodic, m_modifier, m_periodicTimer, and Modifier::periodictime.
HandleModResistancePercent()
void Aura::HandleModResistancePercent (bool apply, bool Real)
Definition at line 6551 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyResistanceBuffModsMod(), GetTarget(), Unit::GetTotalResistanceValue(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, TOTAL_PCT, and UNIT_MOD_RESISTANCE_START.
HandleModSpellCritChance()
void Aura::HandleModSpellCritChance (bool apply, bool Real)
Definition at line 7186 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_modifier, Unit::m_modSpellCritChance, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, and TYPEID_UNIT.
HandleModSpellCritChanceShool()
void Aura::HandleModSpellCritChanceShool (bool apply, bool Real)
Definition at line 7204 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Unit::m_modSpellCritChance, MAX_SPELL_SCHOOL, SPELL_SCHOOL_NORMAL, and TYPEID_UNIT.
HandleModSpellDamagePercentFromAttackPower()
void Aura::HandleModSpellDamagePercentFromAttackPower (bool apply, bool Real)
Definition at line 6699 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModSpellDamagePercentFromStat()
void Aura::HandleModSpellDamagePercentFromStat (bool apply, bool Real)
Definition at line 6673 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModSpellHealingPercentFromAttackPower()
void Aura::HandleModSpellHealingPercentFromAttackPower (bool apply, bool Real)
Definition at line 6710 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModSpellHealingPercentFromStat()
void Aura::HandleModSpellHealingPercentFromStat (bool apply, bool Real)
Definition at line 6684 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModSpellHitChance()
void Aura::HandleModSpellHitChance (bool apply, bool Real)
Definition at line 7174 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_amount, m_modifier, Unit::m_modSpellHitChance, and TYPEID_PLAYER.
HandleModStealth()
void Aura::HandleModStealth (bool apply, bool Real)
Definition at line 5158 of file SpellAuras.cpp.
References VisibilityData::AddStealthStrength(), ByteConverter::apply(), AURA_INTERRUPT_FLAG_STEALTH_INVIS_CANCELS, Unit::CastCustomSpell(), Unit::CastSpell(), Unit::GetAurasByType(), Unit::GetSpellAuraHolder(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::GetVisibility(), WorldObject::GetVisibilityData(), Unit::HasAuraType(), IN_MILLISECONDS, Modifier::m_amount, Modifier::m_miscvalue, m_modifier, PLAYER_FIELD_BYTE2_STEALTH, PLAYER_FIELD_BYTES2, Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasWithInterruptFlags(), Object::RemoveByteFlag(), Unit::RemoveVisFlags(), Object::SetByteFlag(), Unit::SetVisFlags(), Unit::SetVisibility(), SPELL_AURA_DUMMY, SPELL_AURA_MOD_INVISIBILITY, SPELL_AURA_MOD_STEALTH, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, UNIT_VIS_FLAG_CREEP, VISIBILITY_GROUP_INVISIBILITY, VISIBILITY_GROUP_NO_DETECT, VISIBILITY_GROUP_STEALTH, VISIBILITY_OFF, and VISIBILITY_ON.
HandleModStealthDetect()
void Aura::HandleModStealthDetect (bool apply, bool real)
Definition at line 5250 of file SpellAuras.cpp.
References VisibilityData::AddStealthDetectionStrength(), ByteConverter::apply(), GetTarget(), WorldObject::GetVisibilityData(), Modifier::m_amount, Modifier::m_miscvalue, and m_modifier.
HandleModStealthLevel()
void Aura::HandleModStealthLevel (bool apply, bool real)
Definition at line 5255 of file SpellAuras.cpp.
References VisibilityData::AddStealthStrength(), ByteConverter::apply(), GetTarget(), WorldObject::GetVisibilityData(), Modifier::m_amount, Modifier::m_miscvalue, and m_modifier.
HandleModTargetArmorPct()
void Aura::HandleModTargetArmorPct (bool Apply, bool Real)
Definition at line 9700 of file SpellAuras.cpp.
References GetTarget(), and TYPEID_PLAYER.
HandleModTargetResistance()
void Aura::HandleModTargetResistance (bool apply, bool Real)
Definition at line 7951 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModInt32Value(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE, PLAYER_FIELD_MOD_TARGET_RESISTANCE, SPELL_SCHOOL_MASK_NORMAL, SPELL_SCHOOL_MASK_SPELL, and TYPEID_PLAYER.
HandleModTaunt()
void Aura::HandleModTaunt (bool Apply, bool Real)
Definition at line 5475 of file SpellAuras.cpp.
References Unit::AI(), Unit::CanHaveThreatList(), GetTarget(), Unit::IsAlive(), UnitAI::OnTaunt(), and Unit::TauntUpdate().
HandleModThreat()
void Aura::HandleModThreat (bool apply, bool Real)
Definition at line 5414 of file SpellAuras.cpp.
References ByteConverter::apply(), ApplyPercentModFloatVar(), FORM_DEFENSIVESTANCE, GetId(), Unit::GetLevel(), Unit::GetShapeshiftForm(), GetTarget(), Unit::IsAlive(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, Unit::m_threatModifier, and MAX_SPELL_SCHOOL.
HandleModTotalPercentStat()
void Aura::HandleModTotalPercentStat (bool apply, bool Real)
Definition at line 6728 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyStatPercentBuffMod(), Unit::GetHealth(), Unit::GetMaxHealth(), GetSpellProto(), GetTarget(), Object::GetTypeId(), Unit::HandleStatModifier(), Modifier::m_amount, Modifier::m_miscvalue, m_modifier, MAX_STATS, Unit::SetHealth(), sLog, SPELL_ATTR_IS_ABILITY, STAT_STAMINA, STAT_STRENGTH, TOTAL_PCT, TYPEID_PLAYER, and UNIT_MOD_STAT_START.
HandleModUnattackable()
void Aura::HandleModUnattackable (bool Apply, bool Real)
Definition at line 7995 of file SpellAuras.cpp.
References ByteConverter::apply(), Object::ApplyModFlag(), Unit::AttackStop(), Unit::CombatStop(), CONFIG_BOOL_INSTANCE_STRICT_COMBAT_LOCKDOWN, WorldObject::GetInstanceData(), GetTarget(), Object::HasFlag(), InstanceData::IsEncounterInProgress(), sWorld, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and UNIT_FLAG_UNTARGETABLE.
HandleModWaterBreathing()
void Aura::HandleModWaterBreathing (bool apply, bool Real)
Definition at line 3997 of file SpellAuras.cpp.
References GetTarget(), Unit::GetTotalAuraMultiplier(), Object::GetTypeId(), SPELL_AURA_MOD_WATER_BREATHING, and TYPEID_PLAYER.
HandleNoImmediateEffect()
void Aura::HandleNoImmediateEffect (bool , bool) inline
Definition at line 292 of file SpellAuras.h.
HandleNoReagentUseAura()
void Aura::HandleNoReagentUseAura (bool Apply, bool Real)
Definition at line 7533 of file SpellAuras.cpp.
References ClassFamilyMask::Flags, ClassFamilyMask::Flags2, Unit::GetAurasByType(), GetTarget(), Object::GetTypeId(), PLAYER_NO_REAGENT_COST_1, Object::SetUInt32Value(), Object::SetUInt64Value(), SPELL_AURA_NO_REAGENT_USE, and TYPEID_PLAYER.
HandleNULL()
void Aura::HandleNULL (bool , bool) inline
Definition at line 284 of file SpellAuras.h.
HandleOverrideClassScript()
void Aura::HandleOverrideClassScript (bool apply, bool real)
Definition at line 9803 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Modifier::m_miscvalue, m_modifier, and Unit::RegisterOverrideScriptAura().
HandlePeriodicDamage()
void Aura::HandlePeriodicDamage (bool apply, bool Real)
Definition at line 6268 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_DEATH, AURA_REMOVE_BY_DEFAULT, AURA_REMOVE_BY_EXPIRE, BASE_ATTACK, SpellEntry::CalculateSimpleValue(), Unit::CastSpell(), SpellEntry::DmgClass, DOT, EFFECT_INDEX_1, EFFECT_INDEX_2, Unit::GetAttackTime(), Unit::GetAurasByType(), Unit::GetBaseWeaponDamage(), GetCaster(), Unit::GetComboPoints(), Unit::GetHealth(), Unit::GetMaxHealth(), GetSpellProto(), GetSpellSchoolMask(), GetStackAmount(), GetTarget(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), GetWeaponAttackType(), SpellEntry::Id, Modifier::m_amount, Modifier::m_auraname, m_isPeriodic, m_modifier, m_removeMode, MAXDAMAGE, Unit::MeleeDamageBonusDone(), MINDAMAGE, SpellEntry::SchoolMask, SPELL_AURA_DUMMY, SPELL_AURA_PERIODIC_DAMAGE, SPELL_DAMAGE_CLASS_MAGIC, SPELL_DAMAGE_CLASS_NONE, Unit::SpellBaseDamageBonusDone(), Unit::SpellDamageBonusDone(), SPELLFAMILY_DRUID, SPELLFAMILY_PALADIN, SPELLFAMILY_ROGUE, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellVisual, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandlePeriodicDamagePCT()
void Aura::HandlePeriodicDamagePCT (bool apply, bool Real)
Definition at line 6413 of file SpellAuras.cpp.
References ByteConverter::apply(), and m_isPeriodic.
HandlePeriodicEnergize()
void Aura::HandlePeriodicEnergize (bool apply, bool Real)
Definition at line 6001 of file SpellAuras.cpp.
References ByteConverter::apply(), GetAuraMaxTicks(), GetBasePoints(), GetCaster(), Unit::GetCreateMana(), GetId(), Unit::GetMaxPower(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_isPeriodic, m_modifier, POWER_MANA, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandlePeriodicHeal()
void Aura::HandlePeriodicHeal (bool apply, bool Real)
Definition at line 6172 of file SpellAuras.cpp.
References ByteConverter::apply(), BASE_ATTACK, Unit::CastCustomSpell(), DOT, GetCaster(), Unit::GetMaxHealth(), GetSpellProto(), GetSpellSchoolMask(), GetStackAmount(), GetTarget(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), Unit::HasAura(), Modifier::m_amount, m_isPeriodic, m_modifier, Unit::SpellBaseDamageBonusDone(), SPELLFAMILY_DRUID, Unit::SpellHealingBonusDone(), TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
HandlePeriodicHealthFunnel()
void Aura::HandlePeriodicHealthFunnel (bool apply, bool Real)
Definition at line 6456 of file SpellAuras.cpp.
References ByteConverter::apply(), DOT, GetCaster(), GetSpellProto(), GetStackAmount(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_isPeriodic, m_modifier, Unit::SpellDamageBonusDone(), and TYPEID_PLAYER.
HandlePeriodicLeech()
void Aura::HandlePeriodicLeech (bool apply, bool Real)
Definition at line 6418 of file SpellAuras.cpp.
References ByteConverter::apply(), DOT, GetCaster(), GetSpellProto(), GetStackAmount(), GetTarget(), Object::GetTypeId(), Modifier::m_amount, m_isPeriodic, m_modifier, Unit::SpellDamageBonusDone(), and TYPEID_PLAYER.
HandlePeriodicManaLeech()
void Aura::HandlePeriodicManaLeech (bool apply, bool Real)
Definition at line 6439 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_EXPIRE, Unit::CastSpell(), GetId(), GetTarget(), m_isPeriodic, m_removeMode, and TRIGGERED_OLD_TRIGGERED.
HandlePeriodicTriggerSpell()
void Aura::HandlePeriodicTriggerSpell (bool apply, bool Real)
Definition at line 5859 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, ByteConverter::apply(), AURA_REMOVE_BY_DEFAULT, AURA_REMOVE_BY_EXPIRE, AURA_REMOVE_BY_STACK, Unit::CastSpell(), GetCaster(), GetCasterGuid(), GetEffIndex(), GetId(), WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellProto(), GetTarget(), WorldObject::GetTerrain(), Object::GetTypeId(), Map::GetUnit(), TerrainInfo::GetWaterLevel(), Unit::HasAura(), Unit::IsInWater(), Unit::IsVehicle(), m_isPeriodic, m_removeMode, MAX_EFFECT_INDEX, Unit::RemoveAurasDueToSpellByCancel(), Unit::RemoveSpellsCausingAura(), SPELL_AURA_CONTROL_VEHICLE, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and TYPEID_UNIT.
HandlePeriodicTriggerSpellWithValue()
void Aura::HandlePeriodicTriggerSpellWithValue (bool apply, bool Real)
Definition at line 5996 of file SpellAuras.cpp.
References ByteConverter::apply(), and m_isPeriodic.
HandlePhase()
void Aura::HandlePhase (bool apply, bool Real)
Definition at line 9631 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::GetAurasByType(), GetHolder(), GetId(), GetMiscValue(), GetTarget(), Object::GetTypeId(), WorldObject::GetZoneAndAreaId(), PHASEMASK_NORMAL, Unit::RemoveAurasDueToSpell(), Unit::SetPhaseMask(), SPELL_AURA_PHASE, sSpellMgr, and TYPEID_PLAYER.
HandlePrayerOfMending()
void Aura::HandlePrayerOfMending (bool apply, bool Real)
Definition at line 6053 of file SpellAuras.cpp.
HandlePreventFleeing()
void Aura::HandlePreventFleeing (bool apply, bool Real)
Definition at line 9368 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::GetAurasByType(), GetCasterGuid(), GetId(), GetTarget(), Unit::SetFleeing(), and SPELL_AURA_MOD_FEAR.
HandlePreventResurrection()
void Aura::HandlePreventResurrection (bool apply, bool Real)
Definition at line 9743 of file SpellAuras.cpp.
References ByteConverter::apply(), WorldObject::GetMap(), GetTarget(), Object::GetTypeId(), Map::Instanceable(), PLAYER_FIELD_BYTE_RELEASE_TIMER, PLAYER_FIELD_BYTES, Object::RemoveByteFlag(), Object::SetByteFlag(), and TYPEID_PLAYER.
HandleRangedAmmoHaste()
void Aura::HandleRangedAmmoHaste (bool apply, bool Real)
Definition at line 7301 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplyAttackTimePercentMod(), GetTarget(), Modifier::m_amount, m_modifier, RANGED_ATTACK, and TYPEID_PLAYER.
HandleSchoolAbsorb()
void Aura::HandleSchoolAbsorb (bool apply, bool Real)
Definition at line 8048 of file SpellAuras.cpp.
References ByteConverter::apply(), AURA_REMOVE_BY_DISPEL, AURA_REMOVE_BY_SHIELD_BREAK, Unit::CastCustomSpell(), Unit::CastSpell(), SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, Unit::GetAurasByType(), GetCaster(), GetCasterGuid(), Unit::GetMaxPower(), Unit::GetPowerType(), GetSpellProto(), GetTarget(), Unit::HasAura(), SpellEntry::Id, m_removeMode, SpellEntry::Mechanic, MECHANIC_SHIELD, POWER_ENERGY, POWER_MANA, POWER_RAGE, POWER_RUNIC_POWER, roll_chance_i(), sLog, SPELL_AURA_DUMMY, SPELLFAMILY_PRIEST, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, sSpellMgr, and TRIGGERED_OLD_TRIGGERED.
HandleShapeshiftBoosts()
void Aura::HandleShapeshiftBoosts (bool apply)
Definition at line 7555 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastCustomSpell(), Unit::CastSpell(), EFFECT_INDEX_2, FORM_AMBIENT, FORM_AQUA, FORM_BATTLESTANCE, FORM_BEAR, FORM_BERSERKERSTANCE, FORM_BLB_PLAYER, FORM_CAT, FORM_CREATUREBEAR, FORM_CREATURECAT, FORM_DEFENSIVESTANCE, FORM_DIREBEAR, FORM_FLIGHT, FORM_FLIGHT_EPIC, FORM_FRENZY, FORM_GHOSTWOLF, FORM_GHOUL, FORM_METAMORPHOSIS, FORM_MOONKIN, FORM_NONE, FORM_SHADOW, FORM_SHADOW_DANCE, FORM_SPIRITOFREDEMPTION, FORM_STEALTH, FORM_STEVES_GHOUL, FORM_TEST, FORM_TEST_OF_STRENGTH, FORM_THARONJA_SKELETON, FORM_TRAVEL, FORM_TREE, FORM_UNDEAD, FORM_ZOMBIE, Unit::GetAurasByType(), GetModifier(), Unit::GetSpellAuraHolderMap(), GetTarget(), Object::GetTypeId(), SpellEntry::HasAttribute(), IsNeedCastSpellAtFormApply(), IsPassiveSpell(), SQLStorage::LookupEntry(), PLAYERSPELL_REMOVED, Unit::RemoveAurasDueToSpell(), WorldObject::RemoveSpellCooldown(), sLog, SPELL_ATTR_EX2_ALLOW_WHILE_NOT_SHAPESHIFTED, SPELL_AURA_DUMMY, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELLFAMILY_DRUID, sSpellTemplate, SpellEntry::Stances, SpellEntry::StancesNot, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
Referenced by HandleAuraModShapeshift().
HandleShieldBlockValue()
void Aura::HandleShieldBlockValue (bool apply, bool Real)
Definition at line 7967 of file SpellAuras.cpp.
References ByteConverter::apply(), FLAT_MOD, GetTarget(), Modifier::m_amount, Modifier::m_auraname, m_modifier, PCT_MOD, SHIELD_BLOCK_VALUE, SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT, and TYPEID_PLAYER.
HandleSpiritOfRedemption()
void Aura::HandleSpiritOfRedemption (bool apply, bool Real)
Definition at line 8016 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::ApplySpellImmune(), Unit::CastSpell(), Unit::GetMaxPower(), GetTarget(), Object::GetTypeId(), IMMUNITY_DAMAGE, Unit::InterruptNonMeleeSpells(), Unit::IsNonMeleeSpellCasted(), Unit::IsStandState(), POWER_MANA, Unit::SetPower(), Unit::SetStandState(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and UNIT_STAND_STATE_STAND.
HandleTriggerLinkedAura()
void Aura::HandleTriggerLinkedAura (bool apply, bool Real)
Definition at line 9775 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), SpellEntry::EffectTriggerSpell, GetAmount(), GetCaster(), GetCasterGuid(), GetSpellProto(), GetTarget(), SpellEntry::Id, SQLStorage::LookupEntry(), m_effIndex, Unit::RemoveAurasByCasterSpell(), SpellCastArgs::SetBasePoints(), SpellCastArgs::SetTarget(), sLog, sSpellTemplate, and TRIGGERED_OLD_TRIGGERED.
HandleUnused()
void Aura::HandleUnused (bool , bool) inline
Definition at line 288 of file SpellAuras.h.
HandleWaterBreathing()
void Aura::HandleWaterBreathing (bool apply, bool real)
Definition at line 3984 of file SpellAuras.cpp.
References ByteConverter::apply(), GetTarget(), Unit::GetTotalAuraMultiplier(), Object::GetTypeId(), Unit::HasAuraType(), SPELL_AURA_MOD_WATER_BREATHING, SPELL_AURA_WATER_BREATHING, and TYPEID_PLAYER.
HasMechanic()
bool Aura::HasMechanic (uint32 mechanic) const
Definition at line 9834 of file SpellAuras.cpp.
References SpellEntry::EffectMechanic, GetSpellProto(), m_effIndex, and SpellEntry::Mechanic.
isAffectedOnSpell()
bool Aura::isAffectedOnSpell (SpellEntry const * spell) const
Definition at line 947 of file SpellAuras.cpp.
References GetAuraSpellClassMask(), GetSpellProto(), and SpellEntry::IsFitToFamily().
Referenced by Unit::GetCritTakenChance(), and ReapplyAffectedPassiveAuras().
IsAreaAura()
bool Aura::IsAreaAura () const inline
Definition at line 504 of file SpellAuras.h.
References m_isAreaAura.
Referenced by IsSaveToDbAura().
IsCritFromAbilityAura()
bool Aura::IsCritFromAbilityAura (Unit * caster, uint32 & damage) const protected
Definition at line 9685 of file SpellAuras.cpp.
References Unit::CalculateCritAmount(), GetSpellProto(), GetSpellSchoolMask(), GetTarget(), Unit::HasAffectedAura(), Unit::RollSpellCritOutcome(), SPELL_AURA_ABILITY_PERIODIC_CRIT, and SPELLFAMILY_ROGUE.
Referenced by PeriodicTick().
IsLastAuraOnHolder()
bool Aura::IsLastAuraOnHolder ()
Definition at line 9826 of file SpellAuras.cpp.
References GetEffIndex(), GetHolder(), and MAX_EFFECT_INDEX.
Referenced by Unit::RemoveSingleAuraFromSpellAuraHolder().
IsMagnetUsed()
bool Aura::IsMagnetUsed () const inline
Definition at line 538 of file SpellAuras.h.
References m_magnetUsed.
Referenced by Unit::HandleMagnetAuraProc().
IsPeriodic()
bool Aura::IsPeriodic () const inline
Definition at line 505 of file SpellAuras.h.
References m_isPeriodic.
IsPersistent()
bool Aura::IsPersistent () const inline
Definition at line 503 of file SpellAuras.h.
References m_isPersistent.
Referenced by IsSaveToDbAura().
IsPositive()
bool Aura::IsPositive () const inline
Definition at line 502 of file SpellAuras.h.
References m_positive.
Referenced by UnitConditionMgr::getConditionValue(), and HandleAuraModEffectImmunity().
IsSaveToDbAura()
bool Aura::IsSaveToDbAura () const
Definition at line 898 of file SpellAuras.cpp.
References GetCasterGuid(), GetHolder(), GetTarget(), IsAreaAura(), and IsPersistent().
OnAbsorb()
void Aura::OnAbsorb (int32 & currentAbsorb, int32 & remainingDamage, uint32 & reflectedSpellId, int32 & reflectDamage, bool & preventedDeath, bool & dropCharge)
Definition at line 11537 of file SpellAuras.cpp.
References GetAuraScript().
OnAfterApply()
void Aura::OnAfterApply (bool apply)
Definition at line 11517 of file SpellAuras.cpp.
References ByteConverter::apply(), and GetAuraScript().
Referenced by ApplyModifier().
OnApply()
void Aura::OnApply (bool apply)
Definition at line 11511 of file SpellAuras.cpp.
References ByteConverter::apply(), and GetAuraScript().
Referenced by ApplyModifier().
OnAuraDeathPrevention()
void Aura::OnAuraDeathPrevention (int32 & remainingDamage)
Definition at line 11549 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by Unit::CalculateDamageAbsorbAndResist().
OnAuraInit()
void Aura::OnAuraInit ()
Definition at line 11489 of file SpellAuras.cpp.
References GetAuraScript().
OnAuraValueCalculate()
int32 Aura::OnAuraValueCalculate (Unit * caster, int32 currentValue)
Definition at line 11495 of file SpellAuras.cpp.
References GetAuraScript(), GetEffIndex(), GetSpellProto(), and GetTarget().
Referenced by Aura(), and UpdateAuraScaling().
OnCheckProc()
bool Aura::OnCheckProc (ProcExecutionData & data)
Definition at line 11523 of file SpellAuras.cpp.
References GetAuraScript().
OnDamageCalculate()
void Aura::OnDamageCalculate (Unit * victim, int32 & advertisedBenefit, float & totalMod)
Definition at line 11505 of file SpellAuras.cpp.
References GetAuraScript().
OnHeartbeat()
void Aura::OnHeartbeat ()
Definition at line 11561 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by Unit::Heartbeat().
OnManaAbsorb()
void Aura::OnManaAbsorb (int32 & currentAbsorb)
Definition at line 11543 of file SpellAuras.cpp.
References GetAuraScript().
OnPeriodicCalculateAmount()
void Aura::OnPeriodicCalculateAmount (uint32 & amount)
Definition at line 11555 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by PeriodicTick().
OnPeriodicDummy()
void Aura::OnPeriodicDummy ()
Definition at line 11591 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by PeriodicDummyTick().
OnPeriodicTickEnd()
void Aura::OnPeriodicTickEnd ()
Definition at line 11597 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by PeriodicTick().
OnPeriodicTrigger()
void Aura::OnPeriodicTrigger (PeriodicTriggerData & data)
Definition at line 11585 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by TriggerSpell(), and TriggerSpellWithValue().
OnProc()
SpellAuraProcResult Aura::OnProc (ProcExecutionData & data)
Definition at line 11530 of file SpellAuras.cpp.
References GetAuraScript(), and SPELL_AURA_PROC_OK.
Referenced by Unit::ProcDamageAndSpellFor().
PeriodicDummyTick()
void Aura::PeriodicDummyTick () protected
Definition at line 8831 of file SpellAuras.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, ApplyModifier(), WorldObject::CalculateSpellEffectValue(), Unit::CastCustomSpell(), Unit::CastSpell(), Unit::DealDamage(), DIRECT_DAMAGE, EFFECT_INDEX_0, EFFECT_INDEX_1, SpellEntry::EffectRadiusIndex, SpellEntry::EffectTriggerSpell, Unit::GetArmor(), Unit::GetAura(), GetAuraTicks(), GetCaster(), GetEffIndex(), Unit::GetHealth(), GetHolder(), GetId(), WorldObject::GetMap(), Unit::GetMaxHealth(), GetModifier(), Unit::GetPower(), Unit::GetPowerType(), Unit::GetSpellAuraHolder(), GetSpellProto(), GetSpellRadius(), GetStackAmount(), GetTarget(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasAura(), Object::HasFlag(), SpellEntry::Id, Unit::IsInSwimmableWater(), Unit::IsMoving(), Map::IsRegularDifficulty(), Modifier::m_amount, m_effIndex, m_modifier, OnPeriodicDummy(), POWER_RAGE, Unit::RemoveAuraHolderFromStack(), Unit::RemoveAurasDueToSpell(), roll_chance_i(), UnitAI::SendAIEvent(), Unit::SetPower(), SPELL_SCHOOL_MASK_NONE, SPELL_SCHOOL_MASK_NORMAL, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_SHAMAN, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, sScriptDevAIMgr, sSpellRadiusStore, Unit::Suicide(), TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, UNIT_FLAG_SILENCED, UNIT_FLAG_STUNNED, and urand().
Referenced by PeriodicTick().
PeriodicTick()
void Aura::PeriodicTick () protected
Definition at line 8134 of file SpellAuras.cpp.
References SpellNonMeleeDamage::absorb, Unit::AddThreat(), AURA_INTERRUPT_FLAG_STANDING_CANCELS, SpellEntry::AuraInterruptFlags, BASE_ATTACK, Unit::CalculateAbsorbResistBlock(), Unit::CalculateDamageAbsorbAndResist(), Unit::CalculateHealAbsorb(), Unit::CalculateSpellDamage(), WorldObject::CalculateSpellEffectValue(), Unit::CastCustomSpell(), Unit::CastSpell(), createProcExtendMask(), SpellPeriodicAuraLogInfo::critical, CURRENT_FIRST_NON_MELEE_SPELL, CURRENT_MAX_SPELL, SpellNonMeleeDamage::damage, Unit::DealDamage(), Unit::DealDamageMods(), Unit::DealHeal(), Unit::DealSpellDamage(), DETAIL_FILTER_LOG, SpellEntry::DmgClass, DOT, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectMultipleValue, EMOTE_ONESHOT_EAT, EMOTE_STATE_CANNIBALIZE, Unit::GetAura(), GetAuraMaxTicks(), GetAuraTicks(), GetCaster(), GetCasterGuid(), Unit::GetCurrentSpell(), GetEffectMechanic(), GetEffIndex(), Object::GetGuidStr(), Unit::GetHealth(), GetHolder(), Unit::getHostileRefManager(), GetId(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Unit::GetPower(), Unit::GetPowerType(), Unit::GetResilienceRatingDamageReduction(), WorldObject::GetSpellModOwner(), GetSpellProto(), GetSpellSchoolMask(), GetStackAmount(), GetTarget(), Object::GetTypeId(), GetWeaponAttackType(), Unit::HandleEmoteCommand(), SpellEntry::HasAttribute(), Unit::HasAura(), CleanDamage::hitOutCome, SpellEntry::Id, Unit::IsAlive(), IsCritFromAbilityAura(), Unit::IsCrowdControlled(), Unit::IsImmuneToDamage(), Unit::IsImmuneToSchool(), Unit::IsInCombat(), Unit::IsNonMeleeSpellCasted(), IsReflectableSpell(), IsResistableSpell(), LOG_FILTER_PERIODIC_AFFECTS, Modifier::m_amount, Modifier::m_auraname, Modifier::m_baseAmount, m_effIndex, Modifier::m_miscvalue, m_modifier, m_scriptValue, SpellEntry::ManaCostPercentage, MANGOS_ASSERT, MAX_POWERS, MECHANIC_BLEED, MELEE_HIT_CRIT, MELEE_HIT_NORMAL, Unit::MeleeDamageBonusTaken(), Unit::ModifyHealth(), Unit::ModifyPower(), OnPeriodicCalculateAmount(), OnPeriodicTickEnd(), PeriodicDummyTick(), SpellNonMeleeDamage::periodicLog, POWER_MANA, POWER_RAGE, POWER_RUNIC_POWER, PROC_EX_CRITICAL_HIT, PROC_EX_INTERNAL_HOT, PROC_EX_NORMAL_HIT, PROC_FLAG_DEAL_HARMFUL_PERIODIC, PROC_FLAG_TAKE_ANY_DAMAGE, PROC_FLAG_TAKE_HARMFUL_PERIODIC, Unit::ProcDamageAndSpell(), Unit::RemoveAurasDueToSpell(), roll_chance_i(), SpellEntry::SchoolMask, SCORE_HEALING_DONE, Unit::SendPeriodicAuraLog(), Unit::SendSpellNonMeleeDamageLog(), Unit::SendSpellOrDamageImmune(), sLog, SPELL_ATTR_DO_NOT_LOG_IMMUNE_MISSES, SPELL_ATTR_EX5_NO_PARTIAL_RESISTS, SPELL_ATTR_NO_IMMUNITIES, SPELL_AURA_DUMMY, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_REGEN, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_MANA, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_DUMMY, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_HEALTH_FUNNEL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_POWER_BURN_MANA, SPELL_DAMAGE_CLASS_MAGIC, SPELL_DAMAGE_CLASS_NONE, SPELL_DIRECT_DAMAGE, SPELL_EFFECT_DUMMY, SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_MISS_NONE, Unit::SpellDamageBonusTaken(), SPELLFAMILY_DRUID, SPELLFAMILY_WARLOCK, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, Unit::SpellHealingBonusTaken(), Unit::SpellHitResult(), SpellEntry::SpellIconID, SPELLMOD_ALL_EFFECTS, SPELLMOD_MULTIPLE_VALUE, SpellEntry::SpellVisual, sSpellMgr, SpellNonMeleeDamage::target, HostileRefManager::threatAssist(), TRIGGERED_OLD_TRIGGERED, TriggerSpell(), TriggerSpellWithValue(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by Update().
PickTargetsForSpellTrigger()
void Aura::PickTargetsForSpellTrigger (Unit *& triggerCaster, Unit *& triggerTarget, WorldObject *& triggerTargetObject, SpellEntry const * spellInfo) protected
Definition at line 1083 of file SpellAuras.cpp.
References SpellEntry::EffectImplicitTargetA, GetCaster(), Unit::GetChannelObject(), GetTarget(), Unit::GetTarget(), TARGET_LOCATION_CASTER_DEST, TARGET_LOCATION_CASTER_SRC, TARGET_LOCATION_CHANNEL_TARGET_DEST, TARGET_LOCATION_UNIT_RANDOM_SIDE, TARGET_UNIT, TARGET_UNIT_CASTER, TARGET_UNIT_CHANNEL_TARGET, TARGET_UNIT_ENEMY, TARGET_UNIT_FRIEND, and TARGET_UNIT_SCRIPT_NEAR_CASTER.
Referenced by TriggerSpell(), and TriggerSpellWithValue().
ReapplyAffectedPassiveAuras() [1/2]
void Aura::ReapplyAffectedPassiveAuras () protected
Definition at line 1049 of file SpellAuras.cpp.
References Unit::CallForAllControlledUnits(), CONTROLLED_PET, CONTROLLED_TOTEMS, GetSpellProto(), GetTarget(), WorldObject::IsInMap(), Modifier::m_miscvalue, m_modifier, GroupReference::next(), ReapplyAffectedPassiveAurasHelper, SPELLMOD_ACTIVATION_TIME, SPELLMOD_CASTING_TIME, SPELLMOD_CHARGES, SPELLMOD_COOLDOWN, SPELLMOD_COST, SPELLMOD_DURATION, SPELLMOD_GLOBAL_COOLDOWN, and SPELLMOD_NOT_LOSE_CASTING_TIME.
Referenced by HandleAddModifier(), and ReapplyAffectedPassiveAurasHelper::operator()().
ReapplyAffectedPassiveAuras() [2/2]
void Aura::ReapplyAffectedPassiveAuras (Unit * target, bool owner_mode) private
Definition at line 992 of file SpellAuras.cpp.
References Unit::CastSpell(), GetCaster(), GetCasterGuid(), GetId(), Player::GetItemByGuid(), Object::GetObjectGuid(), Unit::GetSpellAuraHolderMap(), GetTarget(), Object::GetTypeId(), isAffectedOnSpell(), Unit::RemoveAurasDueToSpell(), TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
SetAmount()
void Aura::SetAmount (int32 amount) inline
Definition at line 480 of file SpellAuras.h.
References Modifier::m_amount, and m_modifier.
SetLoadedState()
void Aura::SetLoadedState (int32 damage, uint32 periodicTime) inline
Definition at line 493 of file SpellAuras.h.
References GetAuraDuration(), GetAuraMaxTicks(), Modifier::m_amount, m_modifier, m_periodicTick, and Modifier::periodictime.
Referenced by Player::_LoadAuras(), and Pet::_LoadAuras().
SetModifier()
void Aura::SetModifier (AuraType type, int32 amount, uint32 periodicTime, int32 miscValue)
Definition at line 543 of file SpellAuras.cpp.
References GetStackAmount(), Modifier::m_amount, Modifier::m_auraname, Modifier::m_baseAmount, Modifier::m_miscvalue, m_modifier, and Modifier::periodictime.
Referenced by Aura().
SetRemoveMode()
void Aura::SetRemoveMode (AuraRemoveMode mode) inline
Definition at line 513 of file SpellAuras.h.
References m_removeMode.
Referenced by Unit::RemoveAura(), and UpdateAuraScaling().
SetScriptStorage()
void Aura::SetScriptStorage (ScriptStorage * storage) inline
Definition at line 547 of file SpellAuras.h.
References m_storage.
Referenced by KillingSpree::OnAuraInit().
SetScriptValue()
void Aura::SetScriptValue (uint64 value) inline
Definition at line 545 of file SpellAuras.h.
References m_scriptValue.
Referenced by LightwellRenew::OnApply(), Icecrown25MeleeTrinket::OnAuraInit(), DemonicKnowledge::OnAuraValueCalculate(), and LightwellRenew::OnProc().
TriggerSpell()
void Aura::TriggerSpell ()
Definition at line 1209 of file SpellAuras.cpp.
References Unit::AI(), Creature::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, AI_EVENT_CUSTOM_C, AI_EVENT_CUSTOM_F, ATTACKING_TARGET_RANDOM, ATTACKING_TARGET_TOPAGGRO, UnitAI::AttackStart(), Loot::AutoStore(), Unit::CalculateHealAbsorb(), Unit::CastCustomSpell(), Unit::CastSpell(), CastTriggeredSpell(), Unit::CombatStop(), CREATURE_TYPE_GAS_CLOUD, Unit::DealDamage(), Unit::DealDamageMods(), EFFECT_INDEX_1, SpellEntry::EffectTriggerSpell, Unit::FixateTarget(), Creature::ForcedDespawn(), GetAuraDuration(), GetAuraMaxDuration(), Unit::GetAurasByType(), GetAuraScript(), GetAuraTicks(), GetCaster(), GetCasterGuid(), WorldObject::GetClosePoint(), Creature::GetCreatureInfo(), Map::GetDifficulty(), GetEffIndex(), GetHolder(), GetId(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMaxPower(), GetModifier(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), GetPlayerListWithEntryInWorld(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetPower(), GetSpellProto(), GetTarget(), ThreatManager::getThreat(), ThreatManager::getThreatList(), Unit::getThreatManager(), GetTriggerTarget(), Object::GetTypeId(), Map::GetUnit(), Unit::GetVictim(), Unit::HandleStatModifier(), Unit::HasAura(), Unit::InterruptNonMeleeSpells(), Unit::IsAlive(), Unit::IsMoving(), WorldObject::IsWithinDistInMap(), SQLStorage::LookupEntry(), LOOT_SKINNING, Modifier::m_amount, SpellAuraHolder::m_auras, m_effIndex, Modifier::m_miscvalue, m_modifier, M_PI_F, Unit::ModifyHealth(), Unit::ModifyPower(), ThreatManager::modifyThreatPercent(), MapManager::NormalizeOrientation(), OnPeriodicTrigger(), Modifier::periodictime, PickTargetsForSpellTrigger(), WorldObject::PlayDirectSound(), POWER_MANA, POWER_RAGE, Unit::RemoveAurasDueToSpell(), Unit::RemoveAuraStack(), Unit::RemoveSpellsCausingAura(), SELECT_FLAG_PLAYER, SELECT_FLAG_POWER_MANA, Unit::SelectAttackingTarget(), Unit::SelectRandomUnfriendlyTarget(), SELF_DAMAGE, UnitAI::SendAIEvent(), Unit::SendEnergizeSpellLog(), Unit::SetFacingTo(), WorldObject::SetOrientation(), CreatureInfo::SkinningLootId, sLog, SPELL_AURA_MOD_STAT, SPELL_AURA_PHASE, SPELL_SCHOOL_MASK_FIRE, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_WARRIOR, PeriodicTriggerData::spellInfo, sScriptDevAIMgr, sSpellTemplate, STAT_INTELLECT, STAT_SPIRIT, Unit::Suicide(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TOTAL_PCT, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, UNIT_MOD_POWER_START, and urand().
Referenced by PeriodicTick().
TriggerSpellWithValue()
void Aura::TriggerSpellWithValue ()
Definition at line 2363 of file SpellAuras.cpp.
References CastTriggeredSpell(), SpellEntry::EffectDieSides, SpellEntry::EffectTriggerSpell, GetCasterGuid(), GetModifier(), GetSpellProto(), GetTriggerTarget(), SQLStorage::LookupEntry(), Modifier::m_amount, m_effIndex, OnPeriodicTrigger(), PickTargetsForSpellTrigger(), PeriodicTriggerData::spellInfo, and sSpellTemplate.
Referenced by PeriodicTick().
Update()
void Aura::Update (uint32 diff) protected virtual
Reimplemented in GameObjectAura, PersistentAreaAura, and AreaAura.
Definition at line 552 of file SpellAuras.cpp.
References m_isPeriodic, m_modifier, m_periodicTick, m_periodicTimer, PeriodicTick(), and Modifier::periodictime.
Referenced by AreaAura::Update(), PersistentAreaAura::Update(), GameObjectAura::Update(), and UpdateAura().
UpdateAura()
void Aura::UpdateAura (uint32 diff) inline
Definition at line 511 of file SpellAuras.h.
References Update().
UpdateAuraScaling()
void Aura::UpdateAuraScaling ()
Definition at line 928 of file SpellAuras.cpp.
References ApplyModifier(), AURA_REMOVE_BY_GAINED_STACK, GetCaster(), GetEffIndex(), GetModifier(), GetSpellProto(), IsAuraRemoveOnStacking(), Modifier::m_amount, Modifier::m_recentAmount, OnAuraValueCalculate(), and SetRemoveMode().
UseMagnet()
void Aura::UseMagnet () inline
Definition at line 537 of file SpellAuras.h.
References m_magnetUsed.
Friends And Related Function Documentation
CreateAura
Aura* CreateAura (SpellEntry const * spellproto, SpellEffectIndex eff, int32 const * currentDamage, int32 const * currentBasePoints, SpellAuraHolder * holder, Unit * target, Unit * caster, Item * castItem, uint64 scriptValue) friend
Definition at line 524 of file SpellAuras.cpp.
ReapplyAffectedPassiveAurasHelper
friend struct ReapplyAffectedPassiveAurasHelper friend
Definition at line 279 of file SpellAuras.h.
Referenced by ReapplyAffectedPassiveAuras().
Field Documentation
m_applyTime
time_t Aura::m_applyTime protected
Definition at line 588 of file SpellAuras.h.
Referenced by Aura(), and GetAuraApplyTime().
m_currentBasePoints
int32 Aura::m_currentBasePoints protected
Definition at line 590 of file SpellAuras.h.
Referenced by Aura(), GetBasePoints(), and AreaAura::Update().
m_effIndex
SpellEffectIndex Aura::m_effIndex protected
Definition at line 596 of file SpellAuras.h.
Referenced by AreaAura::AreaAura(), Aura(), GetAuraSpellClassMask(), GetEffIndex(), GetMiscBValue(), GetMiscValue(), HandleAuraConvertRune(), HandleAuraDummy(), HandleAuraModSkill(), HandleChannelDeathItem(), HandleInvisibility(), HandleModMechanicImmunity(), HandleTriggerLinkedAura(), HasMechanic(), PeriodicDummyTick(), PeriodicTick(), TriggerSpell(), TriggerSpellWithValue(), and AreaAura::Update().
m_isAreaAura
bool Aura::m_isAreaAura protected
Definition at line 600 of file SpellAuras.h.
Referenced by AreaAura::AreaAura(), GameObjectAura::GameObjectAura(), and IsAreaAura().
m_isPeriodic
bool Aura::m_isPeriodic protected
Definition at line 599 of file SpellAuras.h.
Referenced by ForcePeriodicity(), HandleAuraDummy(), HandleAuraModTotalHealthPercentRegen(), HandleAuraModTotalManaPercentRegen(), HandleAuraPeriodicDummy(), HandleAuraPowerBurn(), HandleDamagePercentTaken(), HandleModPowerRegen(), HandleModRegen(), HandlePeriodicDamage(), HandlePeriodicDamagePCT(), HandlePeriodicEnergize(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), HandlePeriodicManaLeech(), HandlePeriodicTriggerSpell(), HandlePeriodicTriggerSpellWithValue(), IsPeriodic(), and Update().
m_isPersistent
bool Aura::m_isPersistent protected
Definition at line 601 of file SpellAuras.h.
Referenced by IsPersistent(), and PersistentAreaAura::PersistentAreaAura().
m_magnetUsed
bool Aura::m_magnetUsed protected
Definition at line 602 of file SpellAuras.h.
Referenced by IsMagnetUsed(), and UseMagnet().
m_modifier
Modifier Aura::m_modifier protected
Definition at line 585 of file SpellAuras.h.
Referenced by ApplyModifier(), AreaAura::AreaAura(), Aura(), ForcePeriodicity(), GetAmount(), GetAuraMaxTicks(), GetModifier(), HandleAddModifier(), HandleAuraDamageShield(), HandleAuraDummy(), HandleAuraIncreaseBaseHealthPercent(), HandleAuraModAllCritChance(), HandleAuraModAttackPower(), HandleAuraModAttackPowerPercent(), HandleAuraModBaseResistancePercent(), HandleAuraModBlockPercent(), HandleAuraModCritPercent(), HandleAuraModDispelImmunity(), HandleAuraModDmgImmunity(), HandleAuraModDodgePercent(), HandleAuraModEffectImmunity(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseEnergyPercent(), HandleAuraModIncreaseFlightSpeed(), HandleAuraModIncreaseHealth(), HandleAuraModIncreaseHealthPercent(), HandleAuraModIncreaseMaxHealth(), HandleAuraModParryPercent(), HandleAuraModRangedAttackPower(), HandleAuraModRangedAttackPowerPercent(), HandleAuraModRangedHaste(), HandleAuraModResistance(), HandleAuraModResistanceExclusive(), HandleAuraModResistenceOfStatPercent(), HandleAuraModSchoolImmunity(), HandleAuraModShapeshift(), HandleAuraModStat(), HandleAuraModStateImmunity(), HandleAuraModTotalManaPercentRegen(), HandleAuraModTotalThreat(), HandleAuraMounted(), HandleAuraRetainComboPoints(), HandleAuraTrackCreatures(), HandleAuraTrackResources(), HandleAuraTransform(), HandleChannelDeathItem(), HandleDamagePercentTaken(), HandleForceReaction(), HandleInvisibility(), HandleInvisibilityDetect(), HandleManaShield(), HandleModAttackSpeed(), HandleModBaseResistance(), HandleModCastingSpeed(), HandleModCombatSpeedPct(), HandleModDamageDone(), HandleModDamagePercentDone(), HandleModHitChance(), HandleModMechanicImmunity(), HandleModMechanicImmunityMask(), HandleModMeleeRangedSpeedPct(), HandleModMeleeSpeedPct(), HandleModOffhandDamagePercent(), HandleModPercentStat(), HandleModPowerCost(), HandleModPowerCostPCT(), HandleModPowerRegen(), HandleModPowerRegenPCT(), HandleModRating(), HandleModRatingFromStat(), HandleModRegen(), HandleModResistancePercent(), HandleModSpellCritChance(), HandleModSpellCritChanceShool(), HandleModSpellHitChance(), HandleModStealth(), HandleModStealthDetect(), HandleModStealthLevel(), HandleModTargetResistance(), HandleModThreat(), HandleModTotalPercentStat(), HandleOverrideClassScript(), HandlePeriodicDamage(), HandlePeriodicEnergize(), HandlePeriodicHeal(), HandlePeriodicHealthFunnel(), HandlePeriodicLeech(), HandleRangedAmmoHaste(), HandleShieldBlockValue(), PeriodicDummyTick(), PeriodicTick(), ReapplyAffectedPassiveAuras(), SetAmount(), SetLoadedState(), SetModifier(), TriggerSpell(), Update(), and AreaAura::Update().
m_periodicTick
uint32 Aura::m_periodicTick protected
Definition at line 592 of file SpellAuras.h.
Referenced by GetAuraTicks(), SetLoadedState(), and Update().
m_periodicTimer
int32 Aura::m_periodicTimer protected
Definition at line 591 of file SpellAuras.h.
Referenced by Aura(), ForcePeriodicity(), HandleAuraDummy(), HandleAuraModTotalManaPercentRegen(), HandleModPowerRegen(), HandleModRegen(), and Update().
m_positive
bool Aura::m_positive protected
Definition at line 598 of file SpellAuras.h.
Referenced by Aura(), HandleModDamagePercentDone(), and IsPositive().
m_removeMode
AuraRemoveMode Aura::m_removeMode protected
Definition at line 594 of file SpellAuras.h.
Referenced by ApplyModifier(), GetRemoveMode(), HandleAuraControlVehicle(), HandleAuraDummy(), HandleAuraModIncreaseEnergy(), HandleAuraModIncreaseHealth(), HandleAuraModStat(), HandleAuraModTotalManaPercentRegen(), HandleAuraRetainComboPoints(), HandleChannelDeathItem(), HandleModDamagePercentDone(), HandleModPowerCostPCT(), HandlePeriodicDamage(), HandlePeriodicManaLeech(), HandlePeriodicTriggerSpell(), HandleSchoolAbsorb(), and SetRemoveMode().
m_scriptValue
uint64 Aura::m_scriptValue protected
Definition at line 607 of file SpellAuras.h.
Referenced by GetScriptValue(), PeriodicTick(), and SetScriptValue().
m_spellAuraHolder
SpellAuraHolder* const Aura::m_spellAuraHolder protected
Definition at line 604 of file SpellAuras.h.
Referenced by GetAuraSpellClassMask(), GetHolder(), GetMiscBValue(), GetMiscValue(), and GetTriggerTarget().
m_spellmod
SpellModifier* Aura::m_spellmod protected
Definition at line 586 of file SpellAuras.h.
Referenced by GetSpellModifier(), HandleAddModifier(), and ~Aura().
m_storage
ScriptStorage* Aura::m_storage protected
Definition at line 608 of file SpellAuras.h.
Referenced by GetScriptStorage(), SetScriptStorage(), and ~Aura().
The documentation for this class was generated from the following files:
SpellAuras.h
SpellAuras.cpp