CMaNGOS_WoTLK: UnitAI Class Reference
UnitAI Class Reference abstract
#include <UnitAI.h>
Public Member Functions
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void GetAIInformation (ChatHandler &)
== Information about AI ========================
virtual void MoveInLineOfSight (Unit *)
== Reactions At =================================
virtual void EnterCombat (Unit *)
Called for reaction at enter to combat if not in combat yet.
virtual void EnterEvadeMode ()
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
virtual void JustReachedHome ()
Called at reaching home after MoveTargetedHome.
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void DamageTaken (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustDied (Unit *)
Called when the creature is killed.
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void KilledUnit (Unit *)
Called when the creature kills a unit.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (Creature *)
Called when the creature summon successfully other creature.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void JustRespawned ()
Called when creature is respawned (for reseting variables)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void AttackStart (Unit *)
== Triggered Actions Requested ==================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void ReceiveAIEvent (AIEventType, Unit *, Unit *, uint32)
Called when an AI Event is received.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnCallForHelp (Unit *)
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
virtual bool DoRetreat ()
void DoDistance ()
virtual void DoCallForHelp (float radius)
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void TimedFleeingEnded ()
virtual void RetreatingArrived ()
virtual void RetreatingEnded ()
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual void HandleAssistanceCall (Unit *, Unit *)
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
virtual CreatureSpellList const & GetSpellList () const =0
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
virtual void RequestFollow (Unit *)
virtual void RelinquishFollow (ObjectGuid)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Protected Member Functions
virtual std::string GetAIName ()
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 116 of file UnitAI.h.
Constructor & Destructor Documentation
UnitAI() [1/2]
UnitAI::UnitAI (Unit * unit) explicit
Definition at line 36 of file UnitAI.cpp.
UnitAI() [2/2]
UnitAI::UnitAI (Unit * unit, uint32 combatActions) explicit
Definition at line 40 of file UnitAI.cpp.
References TimerManager::AddCustomAction(), GENERIC_ACTION_DISTANCE, GENERIC_ACTION_SPELL_LIST, m_distancingCooldown, and m_spellListCooldown.
~UnitAI()
UnitAI::~UnitAI () virtual
Definition at line 65 of file UnitAI.cpp.
Member Function Documentation
AddDistanceSpell()
void UnitAI::AddDistanceSpell (uint32 spellId) inline
Definition at line 513 of file UnitAI.h.
References m_distanceSpells.
Referenced by boss_lady_vashjAI::boss_lady_vashjAI(), boss_nexusprince_shaffarAI::boss_nexusprince_shaffarAI(), boss_telestraAI::boss_telestraAI(), CreatureEventAI::InitAI(), npc_garaxxasAI::npc_garaxxasAI(), npc_magister_aledisAI::npc_magister_aledisAI(), and npc_yazzaiAI::npc_yazzaiAI().
AddInitialCooldowns()
void UnitAI::AddInitialCooldowns ()
Definition at line 1366 of file UnitAI.cpp.
References WorldObject::AddCooldown(), GetSpellList(), SQLStorage::LookupEntry(), m_unit, CreatureSpellList::Spells, sSpellTemplate, and urand().
Referenced by EnterCombat(), boss_nothAI::ExecuteAction(), boss_gothikAI::HandleGroundPhase(), boss_heiganAI::HandleGroundPhase(), SpellListChanged(), and boss_kelthuzadAI::StartPhase2().
AddMainSpell()
void UnitAI::AddMainSpell (uint32 spellId)
Definition at line 983 of file UnitAI.cpp.
References Spell::CalculatePowerCost(), GetSpellMinRange(), SQLStorage::LookupEntry(), m_mainAttackMask, m_mainSpellCost, m_mainSpellId, m_mainSpellInfo, m_mainSpellMinRange, m_mainSpells, m_unit, SpellEntry::rangeIndex, SpellEntry::SchoolMask, sSpellRangeStore, and sSpellTemplate.
Referenced by boss_aranAI::boss_aranAI(), boss_arugalAI::boss_arugalAI(), boss_bronjahmAI::boss_bronjahmAI(), boss_eregosAI::boss_eregosAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_high_nethermancer_zerevorAI::boss_high_nethermancer_zerevorAI(), boss_kelesethAI::boss_kelesethAI(), boss_kiggler_the_crazedAI::boss_kiggler_the_crazedAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_lady_malandeAI::boss_lady_malandeAI(), boss_lady_vashjAI::boss_lady_vashjAI(), boss_swamplord_muselekAI::boss_swamplord_muselekAI(), boss_telestraAI::boss_telestraAI(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), CreatureEventAI::InitAI(), npc_ellrys_duskhallowAI::npc_ellrys_duskhallowAI(), and SpellListChanged().
AssistPlayerInCombat()
virtual bool UnitAI::AssistPlayerInCombat (Unit *) inline virtual
Reimplemented in FollowerAI, and npc_escortAI.
Definition at line 385 of file UnitAI.h.
Referenced by MoveInLineOfSight().
AttackClosestEnemy()
void UnitAI::AttackClosestEnemy () virtual
Reimplemented in PlayerAI.
Definition at line 900 of file UnitAI.cpp.
References AttackSpecificEnemy(), DIST_CALC_NONE, WorldObject::GetDistance(), and m_unit.
Referenced by boss_eye_of_cthunAI::Aggro(), boss_cthunAI::Aggro(), boss_essence_of_angerAI::boss_essence_of_angerAI(), Spell::EffectSummonType(), essence_base_AI::essence_base_AI(), ScriptAction::ExecuteDbscriptCommand(), boss_dorotheeAI::HandleAggro(), boss_attumenAI::HandleAttackDelay(), boss_nightbaneAI::HandleAttackDelay(), boss_kiljaedenAI::HandleAttackDelay(), boss_entropiusAI::HandleAttackDelay(), boss_ahuneAI::HandleAttackDelay(), boss_vazruden_heraldAI::HandleAttackDelay(), mob_phoenix_tkAI::HandleAttackDelay(), boss_ragnarosAI::HandleEnterCombat(), boss_felmystAI::HandleFelmystSpawnDelay(), boss_gothikAI::HandleGroundPhase(), boss_the_lurker_belowAI::HandleInitialAggro(), boss_alarAI::HandleRebirth(), boss_ouroAI::HandleSpawnDelay(), boss_vaelastraszAI::HandleSpeech(), boss_illidan_stormrageAI::JustDidDialogueStep(), mob_water_globuleAI::JustRespawned(), npc_shaman_elementalAI::JustRespawned(), boss_terestianAI::JustSummoned(), boss_ragnarosAI::JustSummoned(), npc_darknessAI::JustSummoned(), boss_halazziAI::JustSummoned(), boss_sladranAI::JustSummoned(), boss_anubrekhanAI::JustSummoned(), boss_emerald_dragonAI::JustSummoned(), npc_shattered_hands_zealotAI::MovementInform(), boss_lady_blaumeuxAI::MovementInform(), boss_rivendare_naxxAI::MovementInform(), boss_thane_korthazzAI::MovementInform(), boss_sir_zeliekAI::MovementInform(), boss_broggokAI::MovementInform(), boss_high_inquisitor_whitemaneAI::MovementInform(), MutateBug::OnApply(), ActivateSunbladeProtectorChannel::OnPeriodicTickEnd(), CreatureEventAI::ProcessAction(), boss_leotheras_the_blindAI::ReceiveAIEvent(), boss_muruAI::SummonedMovementInform(), boss_strawmanAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), and boss_julianneAI::UpdateAI().
AttackedBy()
void UnitAI::AttackedBy (Unit * attacker) virtual
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
Parameters
pAttacker Unit* who attacked the creature
Reimplemented in mob_fel_orc_convertAI, npc_feero_ironhandAI, npc_dirty_larryAI, mob_lumpAI, boss_ionarAI, npc_disciple_of_naralexAI, npc_belnistraszAI, npc_private_hendelAI, npc_blastmaster_emi_shortfuseAI, boss_mr_smiteAI, boss_hadronoxAI, PetAI, npc_drijyaAI, npc_demoniac_scryerAI, npc_dalaran_guardian_mageAI, npc_scarlet_courierAI, ScriptedPetAI, and NullCreatureAI.
Definition at line 137 of file UnitAI.cpp.
References AttackStart(), Unit::GetVictim(), Unit::IsInCombat(), and m_unit.
Referenced by Unit::AttackedBy(), boss_hadronoxAI::AttackedBy(), npc_belnistraszAI::AttackedBy(), and mob_fel_orc_convertAI::AttackedBy().
AttackSpecificEnemy()
void UnitAI::AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
Definition at line 887 of file UnitAI.cpp.
References AttackStart(), ThreatManager::getThreatList(), Unit::getThreatManager(), and m_unit.
Referenced by AttackClosestEnemy(), and PlayerAI::AttackClosestEnemy().
AttackStart()
void UnitAI::AttackStart (Unit * who) virtual
== Triggered Actions Requested ==================
Called when creature attack expected (if creature can and no have current victim) Note: for reaction at hostile action must be called AttackedBy function. Note: Usually called by MoveInLineOfSight, in Unit::SelectHostileTarget or when the AI is forced to attack an enemy
Parameters
pWho Unit* who is possible target
Reimplemented in SentryTotemAI, npc_shadow_demonAI, npc_living_mojoAI, TotemAI, PetAI, CreatureAI, npc_anchorite_baradaAI, boss_vazruden_heraldAI, mob_steamrigger_mechanicAI, boss_skadiAI, mob_vrykul_skeletonAI, npc_guardian_of_yoggAI, boss_saraAI, boss_sifAI, boss_thorimAI, boss_hodirAI, boss_freyaAI, boss_algalonAI, boss_ionarAI, boss_uromAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_professor_putricideAI, npc_jaina_sylvanas_horAI, boss_lich_king_horAI, boss_champion_hunterAI, boss_champion_mageAI, trial_companion_commonAI, boss_onyxiaAI, npc_blastmaster_emi_shortfuseAI, boss_mr_smiteAI, npc_hurley_blackbreathAI, npc_spirit_shadeAI, npc_warden_mellicharAI, npc_protectorate_demolitionistAI, npc_demoniac_scryerAI, npc_ancestral_wolfAI, mob_underbog_mushroomAI, mob_naga_distillerAI, npc_ice_spear_bunnyAI, npc_frozen_coreAI, mob_enchanted_elementalAI, npc_simon_game_bunnyAI, mob_illidari_councilAI, boss_reliquary_of_soulsAI, npc_blade_of_azzinothAI, npc_cage_trap_triggerAI, npc_void_travelerAI, npc_charged_sphereAI, npc_keeper_thorimAI, npc_keeper_mimironAI, npc_death_rayAI, npc_ominous_cloudAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, npc_xt_toy_pileAI, boss_heart_deconstructorAI, npc_thunder_orbAI, npc_harpoon_fire_stateAI, npc_computerAI, boss_leviathan_mk2_turretAI, npc_rocket_strikeAI, npc_frost_bombAI, npc_mimiron_flamesAI, npc_bot_triggerAI, npc_proximity_mineAI, boss_mimironAI, npc_rubble_stalkerAI, npc_focused_eyebeamAI, npc_scorchAI, npc_icicle_targetAI, npc_flash_freezeAI, npc_saronite_vaporAI, npc_healthy_sporeAI, npc_iron_rootsAI, npc_eonars_giftAI, npc_mimiron_infernoAI, npc_freya_wardAI, npc_hodir_furyAI, npc_hodir_fury_reticleAI, npc_collapsing_starAI, npc_black_holeAI, npc_worm_holeAI, npc_living_constellationAI, npc_web_wrapAI, npc_putricides_trapAI, mob_frost_bombAI, npc_puddle_stalkerAI, npc_choking_gas_bombAI, npc_growing_ooze_puddleAI, npc_orange_gas_stalkerAI, npc_kinetic_bombAI, npc_ball_of_flameAI, npc_crystal_channel_targetAI, npc_beast_combat_stalkerAI, npc_black_knight_gryphonAI, npc_seaforium_depth_chargeAI, mob_ahnkahar_eggAI, npc_twilight_volunteerAI, npc_amanitar_mushroomAI, npc_medivh_black_morassAI, mob_webbed_creatureAI, boss_head_of_horsemanAI, npc_image_arcanagosAI, npc_image_of_medivhAI, npc_chess_piece_genericAI, npc_echo_of_medivhAI, ScriptedPetAI, and NullCreatureAI.
Definition at line 282 of file UnitAI.cpp.
References Unit::Attack(), Unit::EngageInCombatWith(), Unit::GetVictim(), HandleMovementOnAttackStart(), HasReactState(), m_meleeEnabled, m_unit, and REACT_PASSIVE.
Referenced by boss_kelidan_the_breakerAI::AddJustAggroed(), AreaTrigger_at_nats_landing(), AttackedBy(), AttackPlayerWithQuest(), npc_shadow_imageAI::AttackRandomTarget(), AttackSpecificEnemy(), CheckForHelp(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), DetectOrAttack(), npc_threshwackonatorAI::DoAtEnd(), npc_eris_havenfireAI::DoAttackArchersTarget(), CreatureLinkingHolder::DoCreatureLinkingEvent(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_spell_aura_dummy_npc(), Spell::EffectDummy(), EffectDummyCreature_npc_vault_warder(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), Spell::EffectThreat(), ScriptAction::ExecuteDbscriptCommand(), PlayerAI::ExecuteSpells(), GossipSelect_example_creature(), GossipSelect_npc_salsalabim(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_silvermoon_harry(), boss_nefarianAI::HandleAttackStart(), WorldSession::HandlePetActionHelper(), npc_bt_battle_sensor::IllidariAttackNearestEnemy(), boss_brutallusAI::JustDidDialogueStep(), boss_uromAI::JustSummoned(), npc_professor_phizzlethorpeAI::JustSummoned(), boss_general_angerforgeAI::JustSummoned(), boss_overlordwyrmthalakAI::JustSummoned(), npc_grark_lorkrubAI::JustSummoned(), npc_eris_havenfireAI::JustSummoned(), npc_apprentice_mirvedaAI::JustSummoned(), npc_infused_crystalAI::JustSummoned(), boss_dorotheeAI::JustSummoned(), boss_julianneAI::JustSummoned(), npc_miranAI::JustSummoned(), boss_headless_horsemanAI::JustSummoned(), boss_cannon_master_willeyAI::JustSummoned(), npc_anchorite_truuenAI::JustSummoned(), npc_tapoke_slim_jahnAI::JustSummoned(), example_escortAI::JustSummoned(), npc_muglashAI::JustSummoned(), npc_torekAI::JustSummoned(), npc_feero_ironhandAI::JustSummoned(), npc_arthasAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_volcorAI::JustSummoned(), npc_areiAI::JustSummoned(), boss_noxxionAI::JustSummoned(), npc_willix_the_importerAI::JustSummoned(), mob_anubisath_guardianAI::JustSummoned(), npc_solenorAI::JustSummoned(), npc_kayaAI::JustSummoned(), npc_wizzlecranks_shredderAI::JustSummoned(), npc_lakota_windsongAI::JustSummoned(), boss_zumrahAI::JustSummoned(), mob_ahnkahar_eggAI::JustSummoned(), boss_volazjAI::JustSummoned(), boss_krikthirAI::JustSummoned(), npc_proudhoofAI::JustSummoned(), boss_black_knightAI::JustSummoned(), boss_anubarak_trialAI::JustSummoned(), npc_destructive_wardAI::JustSummoned(), boss_novosAI::JustSummoned(), npc_harrison_jonesAI::JustSummoned(), npc_squad_leaderAI::JustSummoned(), boss_devourer_of_soulsAI::JustSummoned(), boss_lich_king_horAI::JustSummoned(), boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricideAI::JustSummoned(), boss_ormorokAI::JustSummoned(), boss_telestraAI::JustSummoned(), boss_eregosAI::JustSummoned(), boss_ionarAI::JustSummoned(), boss_volkhanAI::JustSummoned(), boss_molgeimAI::JustSummoned(), boss_freyaAI::JustSummoned(), boss_kologarnAI::JustSummoned(), boss_aerial_unitAI::JustSummoned(), boss_exarch_maladaarAI::JustSummoned(), npc_shaheenAI::JustSummoned(), boss_darkweaver_sythAI::JustSummoned(), npc_warp_gate::JustSummoned(), boss_warchief_kargath_bladefistAI::JustSummoned(), npc_demoniac_scryerAI::JustSummoned(), npc_wounded_blood_elfAI::JustSummoned(), npc_colonel_julesAI::JustSummoned(), npc_nagrand_captiveAI::JustSummoned(), npc_protectorate_demolitionistAI::JustSummoned(), npc_drijyaAI::JustSummoned(), npc_salhadaarAI::JustSummoned(), npc_wildaAI::JustSummoned(), npc_warden_mellicharAI::JustSummoned(), boss_harbinger_skyrissAI::JustSummoned(), boss_high_botanist_freywinnAI::JustSummoned(), boss_lajAI::JustSummoned(), boss_high_astromancer_solarianAI::JustSummoned(), boss_pathaleon_the_calculatorAI::JustSummoned(), npc_akunoAI::JustSummoned(), npc_letollAI::JustSummoned(), npc_skywingAI::JustSummoned(), npc_skyguard_prisonerAI::JustSummoned(), boss_coren_direbrewAI::JustSummoned(), boss_midnightAI::JustSummoned(), boss_nightbaneAI::JustSummoned(), boss_aranAI::JustSummoned(), boss_felblood_kaelthasAI::JustSummoned(), npc_zelfanAI::JustSummoned(), boss_vexallusAI::JustSummoned(), boss_sathrovarrAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_jeklikAI::JustSummoned(), boss_mandokirAI::JustSummoned(), boss_archimondeAI::JustSummoned(), npc_oox22feAI::JustSummoned(), npc_clintar_dw_spiritAI::JustSummoned(), npc_keeper_remulosAI::JustSummoned(), boss_ayamissAI::JustSummoned(), npc_buru_eggAI::JustSummoned(), boss_moamAI::JustSummoned(), npc_oox17tnAI::JustSummoned(), boss_eye_of_cthunAI::JustSummoned(), boss_cthunAI::JustSummoned(), boss_fankrissAI::JustSummoned(), boss_skeramAI::JustSummoned(), npc_kanatiAI::JustSummoned(), boss_drakkari_colossusAI::JustSummoned(), boss_deathbringer_saurfangAI::JustSummoned(), boss_loathebAI::JustSummoned(), boss_nexusprince_shaffarAI::JustSummoned(), npc_grand_collectorAI::JustSummoned(), npc_akama_illidanAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_fathomguard_sharkkisAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_leotheras_the_blindAI::JustSummoned(), boss_morogrim_tidewalkerAI::JustSummoned(), boss_ahuneAI::JustSummoned(), boss_omor_the_unscarredAI::JustSummoned(), npc_lord_illidan_stormrageAI::JustSummoned(), npc_air_force_botsAI::MoveInLineOfSight(), ScourgeMinion::MoveInLineOfSight(), PallidHorrorAI::MoveInLineOfSight(), boss_eranikusAI::MovementInform(), trial_companion_commonAI::MovementInform(), spell_awaken_subboss_aura::OnApply(), SupremusRandomTarget::OnApply(), instance_shadowfang_keep::OnCreatureRespawn(), instance_naxxramas::OnCreatureRespawn(), instance_nexus::OnCreatureRespawn(), instance_utgarde_keep::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), spell_awaken_gortok::OnEffectExecute(), RandomAggro::OnEffectExecute(), AggroRadius8YD::OnEffectExecute(), GuardianAggroSpell::OnEffectExecute(), TribalDeath::OnEffectExecute(), GreaterInvisibilityMob::OnPeriodicTickEnd(), Shadowfiend::OnSummon(), CreatureEventAI::ProcessAction(), instance_dire_maul::ProcessForceFieldOpening(), CreatureLinkingHolder::ProcessSlave(), QuestAccept_npc_bartleby(), QuestAccept_npc_calvin_montague(), QuestAccept_npc_private_hendel(), boss_alarAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), Unit::SelectHostileTarget(), npc_twiggy_flatheadAI::SetChallengerReady(), Unit::SetInCombatState(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), npc_theramore_spar_controller::StartSparring(), npc_crystal_channel_targetAI::SummonedMovementInform(), npc_emilyAI::SummonedMovementInform(), npc_dorius_stonetenderAI::SummonedMovementInform(), npc_creature_generatorAI::SummonedMovementInform(), npc_scrapped_fel_reaverAI::SummonedMovementInform(), boss_eranikusAI::SummonedMovementInform(), Aura::TriggerSpell(), instance_stratholme::Update(), instance_uldaman::Update(), npc_scarlet_courierAI::UpdateAI(), and npc_saeed_escortAI::UpdateAI().
CalculateSpellRange()
float UnitAI::CalculateSpellRange (SpellEntry const * spellInfo) const
Definition at line 714 of file UnitAI.cpp.
References GetSpellMaxRange(), WorldObject::GetSpellModOwner(), SpellEntry::Id, m_unit, SpellEntry::rangeIndex, SPELLMOD_RANGE, and sSpellRangeStore.
Referenced by ChooseTarget(), DoFindFriendlyEligibleDispel(), DoFindFriendlyMissingBuff(), and UpdateSpellLists().
CanCastSpell() [1/2]
bool UnitAI::CanCastSpell ()
Definition at line 796 of file UnitAI.cpp.
References Unit::CanCastSpellInCombat(), Unit::hasUnitState(), Unit::IsNonMeleeSpellCasted(), m_combatScriptHappening, m_unit, UNIT_STAT_PROPELLED, and UNIT_STAT_RETREATING.
Referenced by DoCastSpellIfCan(), and UpdateSpellLists().
CanCastSpell() [2/2]
CanCastResult UnitAI::CanCastSpell (Unit * target, const SpellEntry * spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
Definition at line 143 of file UnitAI.cpp.
References CAST_FAIL_OTHER, CAST_OK, Spell::CheckTargetCreatureType(), CURRENT_AUTOREPEAT_SPELL, Unit::GetCurrentSpell(), SpellEntry::Id, IsNextMeleeSwingSpell(), and m_unit.
CanExecuteCombatAction()
bool UnitAI::CanExecuteCombatAction () virtual
Definition at line 791 of file UnitAI.cpp.
References Unit::CanReactInCombat(), Object::HasFlag(), Unit::hasUnitState(), Unit::IsNonMeleeSpellCasted(), m_combatScriptHappening, m_unit, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, UNIT_FLAG_SILENCED, UNIT_STAT_PROPELLED, and UNIT_STAT_RETREATING.
Referenced by CreatureEventAI::CheckEvent(), boss_illidan_stormrageAI::DoCastEyeBlastIfCan(), boss_felmystAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), boss_muruAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), ExecuteActions(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), boss_yorAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), npc_skyguard_rangerAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_grand_collectorAI::ExecuteActions(), npc_apexis_flayerAI::ExecuteActions(), PlayerAI::ExecuteSpells(), CreatureEventAI::ProcessEvent(), boss_lord_sanguinarAI::UpdateAI(), and UpdateAI().
CanHandleCharm()
virtual bool UnitAI::CanHandleCharm () inline virtual
Reimplemented in npc_scrap_reaverAI, npc_razorthorn_ravager, npc_fel_cannon, and npc_chess_piece_genericAI.
Definition at line 478 of file UnitAI.h.
Referenced by Unit::TakeCharmOf().
CanTriggerStealthAlert()
bool UnitAI::CanTriggerStealthAlert (Unit * who, float attackRadius) const
Definition at line 563 of file UnitAI.cpp.
References DIST_CALC_NONE, WorldObject::GetDistance(), VisibilityData::GetStealthVisibilityDistance(), Object::GetTypeId(), WorldObject::GetVisibilityData(), Unit::HasStealthAura(), Unit::hasUnitState(), m_unit, TYPEID_PLAYER, UNIT_STAT_CAN_NOT_REACT_OR_LOST_CONTROL, and UNIT_STAT_DISTRACTED.
Referenced by DetectOrAttack().
CheckForHelp()
void UnitAI::CheckForHelp (Unit * who, Unit * me, float distance)
Definition at line 504 of file UnitAI.cpp.
References Unit::AI(), AttackStart(), Unit::CanAssistInCombatAgainst(), Unit::CanAttackOnSight(), Unit::CanCallForAssistance(), Unit::CanCheckForHelp(), Unit::CanInitiateAttack(), GetAIOrder(), Unit::getAttackerForHelper(), Unit::GetMotionMaster(), Unit::hasUnitState(), MotionMaster::InterruptPanic(), Unit::isInAccessablePlaceFor(), Unit::IsInCombat(), Unit::IsVisibleForOrDetect(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), ORDER_FLEEING, UNIT_STAT_PANIC, and UNIT_STAT_RETREATING.
Referenced by MoveInLineOfSight().
ChooseTarget()
std::pair< bool, Unit * > UnitAI::ChooseTarget (CreatureSpellListTargeting * targetData, uint32 spellId) const
Definition at line 1297 of file UnitAI.cpp.
References CalculateSpellRange(), DoFindFriendlyEligibleDispel(), DoFindFriendlyMissingBuff(), DoSelectConditionalFriendly(), DoSelectLowestHpFriendly(), ThreatManager::getThreatList(), Unit::getThreatManager(), Unit::GetVictim(), CreatureSpellListTargeting::Id, SQLStorage::LookupEntry(), m_unit, CreatureSpellListTargeting::Param1, CreatureSpellListTargeting::Param2, CreatureSpellListTargeting::Param3, SELECT_FLAG_USE_EFFECT_RADIUS, SELECT_FLAG_USE_EFFECT_RADIUS_OF_TRIGGERED_SPELL, Unit::SelectAttackingTarget(), SPELL_LIST_TARGET_CURRENT, SPELL_LIST_TARGET_CURRENT_NOT_ALONE, SPELL_LIST_TARGET_DISPELLABLE_FRIENDLY, SPELL_LIST_TARGET_DISPELLABLE_FRIENDLY_NO_SELF, SPELL_LIST_TARGET_FRIENDLY_MISSING_BUFF, SPELL_LIST_TARGET_FRIENDLY_MISSING_BUFF_NO_SELF, SPELL_LIST_TARGET_NONE, SPELL_LIST_TARGET_SELF, SPELL_LIST_TARGETING_ATTACK, SPELL_LIST_TARGETING_HARDCODED, SPELL_LIST_TARGETING_SUPPORT, sSpellTemplate, CreatureSpellListTargeting::Type, CreatureSpellListTargeting::UnitCondition, and urand().
Referenced by UpdateSpellLists().
ClearCombatOnlyRoot()
void UnitAI::ClearCombatOnlyRoot ()
Definition at line 927 of file UnitAI.cpp.
References m_combatOnlyRoot, m_unit, and Unit::SetImmobilizedState().
Referenced by npc_death_knight_initiateAI::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), EnterEvadeMode(), JustDied(), spell_assemble_cage::OnEffectExecute(), and CreatureEventAI::Reset().
CombatStop()
virtual void UnitAI::CombatStop () inline virtual
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
Reimplemented in ScriptedPetAI, and GuardianAI.
Definition at line 303 of file UnitAI.h.
Referenced by Unit::CombatStop().
CorpseRemoved()
virtual void UnitAI::CorpseRemoved (uint32 &) inline virtual
Called when the corpse of this creature gets removed.
Parameters
uiRespawnDelay Delay (in seconds). If != 0, then this is the time after which the creature will respawn, if = 0 the default respawn-delay will be used
Reimplemented in npc_thrall_old_hillsbradAI, boss_felmystAI, boss_shade_of_akamaAI, npc_akamaAI, npc_akama_illidanAI, boss_illidan_stormrageAI, boss_malacrassAI, boss_majordomoAI, boss_nightbaneAI, CreatureEventAI, npc_cage_trap_triggerAI, mob_phoenix_tkAI, npc_spirit_guideAI, FollowerAI, and npc_escortAI.
Definition at line 198 of file UnitAI.h.
Referenced by CreatureEventAI::CorpseRemoved(), boss_felmystAI::CorpseRemoved(), and Creature::RemoveCorpse().
CreatureGroupMemberDied()
virtual void UnitAI::CreatureGroupMemberDied (Unit *) inline virtual
Reimplemented in npc_cork_gizeltonAI.
Definition at line 566 of file UnitAI.h.
DamageDeal()
virtual void UnitAI::DamageDeal (Unit * , uint32 & , DamageEffectType , SpellEntry const *) inline virtual
Called at any Damage to any victim (before damage apply)
Parameters
pDoneTo Unit* to whom Damage of amount uiDamage will be dealt
uiDamage Amount of Damage that will be dealt, can be changed here
Reimplemented in npc_serpentshrine_parasiteAI.
Definition at line 177 of file UnitAI.h.
DamageTaken()
virtual void UnitAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellEntry const *) inline virtual
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
Parameters
pDealer Unit* who will deal Damage to the creature
uiDamage Amount of Damage that will be dealt, can be changed here
Reimplemented in boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, npc_iron_constructAI, three_nature_alliesAI, npc_silvermoon_harryAI, npc_anubarak_trial_frostsphereAI, npc_salsalabimAI, mob_vrykul_skeletonAI, npc_immortal_guardianAI, trial_crusader_commonAI, npc_dark_nucleusAI, NecroticShard, boss_halion_twilightAI, boss_halion_realAI, npc_private_hendelAI, mobs_risen_husk_spiritAI, npc_calvin_montagueAI, npc_bartlebyAI, npc_warchief_blackhandAI, npc_king_llaneAI, boss_essence_of_desireAI, boss_zuljinAI, boss_head_of_horsemanAI, CreatureEventAI, CreatureAI, npc_building_triggerAI, boss_ingvarAI, boss_saraAI, boss_thorimAI, boss_mimironAI, boss_hodirAI, boss_freyaAI, boss_feral_defenderAI, boss_algalonAI, mob_molten_golemAI, boss_deathbringer_saurfangAI, blood_prince_council_baseAI, npc_kinetic_bombAI, npc_grand_admiral_westwindAI, trial_companion_commonAI, boss_black_knightAI, argent_champion_commonAI, npc_death_knight_initiateAI, npc_venture_co_lookoutAI, npc_gallywixAI, boss_twin_emperorsAI, advisor_base_ai, npc_dirty_larryAI, npc_kaylaan_the_lostAI, npc_rethhedronAI, mob_lumpAI, npc_blade_dance_targetAI, boss_illidari_councilAI, npc_akamaAI, npc_tapoke_slim_jahnAI, npc_dashel_stonefistAI, npc_deathstalker_vincentAI, boss_headless_horsemanAI, boss_romuloAI, boss_julianneAI, npc_frozen_coreAI, boss_ahuneAI, and mob_anubisath_guardianAI.
Definition at line 186 of file UnitAI.h.
Referenced by Unit::DealDamageMods().
DespawnGuids()
void UnitAI::DespawnGuids (GuidVector & spawns) protected
Definition at line 936 of file UnitAI.cpp.
References Map::GetAnyTypeCreature(), Map::GetGameObject(), WorldObject::GetMap(), GO_JUST_DEACTIVATED, and m_unit.
Referenced by boss_reliquary_of_soulsAI::boss_reliquary_of_soulsAI(), CreatureEventAI::CorpseRemoved(), boss_teron_gorefiendAI::DespawnSummons(), boss_zuljinAI::DoDespawnVortexes(), CreatureEventAI::EnterEvadeMode(), boss_felblood_kaelthasAI::EnterEvadeMode(), boss_kiljaedenAI::EnterEvadeMode(), boss_muruAI::EnterEvadeMode(), boss_kelthuzadAI::EnterEvadeMode(), boss_nothAI::EnterEvadeMode(), boss_lady_vashjAI::EnterEvadeMode(), boss_ahuneAI::EnterEvadeMode(), boss_warp_splinterAI::EnterEvadeMode(), boss_skeramAI::ExecuteAction(), npc_lord_illidan_stormrageAI::FailEvent(), boss_felblood_kaelthasAI::HandleOutro(), boss_vexallusAI::JustDied(), boss_kiljaedenAI::JustDied(), boss_skeramAI::JustDied(), boss_kelthuzadAI::JustDied(), boss_lady_vashjAI::JustDied(), boss_ahuneAI::JustDied(), CreatureEventAI::JustDied(), npc_garaxxasAI::JustDied(), npc_apokoAI::JustReachedHome(), npc_zelfanAI::JustReachedHome(), boss_illidan_stormrageAI::ReceiveAIEvent(), npc_akama_illidanAI::ReceiveAIEvent(), npc_creature_generatorAI::ReceiveAIEvent(), boss_felblood_kaelthasAI::Reset(), boss_vexallusAI::Reset(), boss_ragnarosAI::Reset(), boss_kiljaedenAI::Reset(), boss_akilzonAI::Reset(), boss_halazziAI::Reset(), boss_janalaiAI::Reset(), boss_ayamissAI::Reset(), boss_moamAI::Reset(), boss_ossirianAI::Reset(), boss_fankrissAI::Reset(), boss_gothikAI::Reset(), boss_reliquary_of_soulsAI::Reset(), boss_terokkAI::Reset(), boss_fathomlord_karathressAI::Reset(), boss_fathomguard_tidalvessAI::Reset(), boss_fathomguard_caribdisAI::Reset(), boss_lady_vashjAI::Reset(), boss_mekgineer_steamriggerAI::Reset(), boss_alarAI::Reset(), and boss_terokkAI::SummonedMovementInform().
DetectOrAttack()
void UnitAI::DetectOrAttack (Unit * who)
Definition at line 532 of file UnitAI.cpp.
References AI_REACTION_ALERT, AttackStart(), CanTriggerStealthAlert(), DIST_CALC_NONE, Unit::EngageInCombatWith(), WorldObject::GetAngle(), Unit::GetAttackDistance(), Unit::GetCombatManager(), WorldObject::GetDistance(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetTransportInfo(), Unit::GetVictim(), Map::IsDungeon(), CombatManager::IsEvadingHome(), Unit::IsInCombat(), WorldObject::IsWithinLOSInMap(), m_unit, MotionMaster::MoveDistract(), OnStealthAlert(), Unit::SendAIReaction(), Unit::SetFacingTo(), and TIME_INTERVAL_LOOK.
Referenced by MoveInLineOfSight().
DistanceYourself()
void UnitAI::DistanceYourself ()
Definition at line 1043 of file UnitAI.cpp.
References Unit::CanReachWithMeleeAttack(), MotionMaster::DistanceYourself(), DISTANCING_CONSTANT, WorldObject::GetCombinedCombatReach(), Unit::GetMotionMaster(), Unit::GetVictim(), IsEligibleForDistancing(), m_mainSpellMinRange, and m_unit.
Referenced by npc_yazzaiAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), JustStoppedMovementOfTarget(), and UpdateAI().
DistancingEnded()
void UnitAI::DistancingEnded () virtual
Reimplemented in boss_swamplord_muselekAI.
Definition at line 1062 of file UnitAI.cpp.
References m_currentRangedMode, SetCombatScriptStatus(), and SetCurrentRangedMode().
Referenced by boss_swamplord_muselekAI::DistancingEnded(), ChaseMovementGenerator::Finalize(), ChaseMovementGenerator::HandleFinalizedMovement(), and ChaseMovementGenerator::HandleMovementFailure().
DistancingStarted()
void UnitAI::DistancingStarted () virtual
Definition at line 1057 of file UnitAI.cpp.
References SetCombatScriptStatus().
Referenced by ChaseMovementGenerator::DistanceYourself().
DoCallForHelp()
virtual void UnitAI::DoCallForHelp (float radius) inline virtual
Reimplemented in CreatureAI.
Definition at line 466 of file UnitAI.h.
DoCastSpellIfCan()
CanCastResult UnitAI::DoCastSpellIfCan (Unit * target, uint32 spellId, uint32 castFlags = 0) virtual
Function to cast a spell if possible.
Parameters
pTarget Unit* onto whom the spell should be cast
uiSpell ID of the spell that the creature will try to cast
uiCastFlags Some flags to define how to cast, see enum CastFlags
OriginalCasterGuid the original caster of the spell if required, empty by default
Definition at line 160 of file UnitAI.cpp.
References CanCastSpell(), CAST_AURA_NOT_PRESENT, CAST_FAIL_CAST_PREVENTED, CAST_FAIL_COOLDOWN, CAST_FAIL_EVADE, CAST_FAIL_IS_CASTING, CAST_FAIL_MISCELLANEOUS, CAST_FAIL_NOT_IN_LOS, CAST_FAIL_OTHER, CAST_FAIL_POWER, CAST_FAIL_STATE, CAST_FAIL_TARGET_AURA, CAST_FAIL_TOO_CLOSE, CAST_FAIL_TOO_FAR, CAST_FORCE_CAST, CAST_FORCE_TARGET_SELF, CAST_IGNORE_UNSELECTABLE_TARGET, CAST_INTERRUPT_PREVIOUS, CAST_OK, CAST_ONLY_XYZ, CAST_SWITCH_CASTER_TARGET, CAST_TRIGGERED, Unit::CastSpell(), CURRENT_MELEE_SPELL, GetAIOrder(), Object::GetGuidStr(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellCastResultString(), ObjectGuid::GetString(), HandleSpellCastResult(), Unit::HasAura(), Unit::InterruptNonMeleeSpells(), Unit::InterruptSpell(), Unit::IsCrowdControlled(), Unit::IsNonMeleeSpellCasted(), SQLStorage::LookupEntry(), m_unit, ORDER_EVADE, sLog, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_CASTER_AURASTATE, SPELL_FAILED_CONFUSED, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_FLEEING, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_NO_POWER, SPELL_FAILED_NOT_READY, SPELL_FAILED_OUT_OF_RANGE, SPELL_FAILED_PACIFIED, SPELL_FAILED_PREVENTED_BY_MECHANIC, SPELL_FAILED_SILENCED, SPELL_FAILED_STUNNED, SPELL_FAILED_TARGET_AURASTATE, SPELL_FAILED_TARGET_NO_WEAPONS, SPELL_FAILED_TOO_CLOSE, sSpellTemplate, TRIGGERED_IGNORE_UNSELECTABLE_FLAG, TRIGGERED_NONE, TRIGGERED_NORMAL_COMBAT_CAST, and TRIGGERED_OLD_TRIGGERED.
Referenced by boss_anetheronAI::Aggro(), boss_ambassador_flamelashAI::Aggro(), boss_general_angerforgeAI::Aggro(), boss_vaelastraszAI::Aggro(), boss_kazzakAI::Aggro(), boss_netherspiteAI::Aggro(), boss_strawmanAI::Aggro(), boss_garrAI::Aggro(), boss_herodAI::Aggro(), boss_scarlet_commander_mograineAI::Aggro(), npc_reginald_windsorAI::Aggro(), boss_alythessAI::Aggro(), boss_sacrolashAI::Aggro(), boss_muruAI::Aggro(), npc_taelan_fordringAI::Aggro(), npc_tirion_fordringAI::Aggro(), npc_tapoke_slim_jahnAI::Aggro(), boss_jeklikAI::Aggro(), npc_gurubashi_bat_riderAI::Aggro(), boss_marliAI::Aggro(), boss_azuregosAI::Aggro(), npc_arthasAI::Aggro(), mob_anubisath_guardianAI::Aggro(), boss_eye_of_cthunAI::Aggro(), boss_cthunAI::Aggro(), boss_viscidusAI::Aggro(), npc_anubisath_defenderAI::Aggro(), boss_volazjAI::Aggro(), boss_black_knightAI::Aggro(), boss_fjolaAI::Aggro(), boss_eydisAI::Aggro(), boss_novosAI::Aggro(), boss_moorabiAI::Aggro(), npc_father_kamarosAI::Aggro(), boss_blood_queen_lanathelAI::Aggro(), boss_deathbringer_saurfangAI::Aggro(), boss_festergutAI::Aggro(), boss_lady_deathwhisperAI::Aggro(), boss_rotfaceAI::Aggro(), npc_rimefang_iccAI::Aggro(), boss_sapphironAI::Aggro(), mob_tenebronAI::Aggro(), mob_shadronAI::Aggro(), mob_vesperonAI::Aggro(), boss_halion_realAI::Aggro(), boss_halion_twilightAI::Aggro(), boss_lokenAI::Aggro(), boss_sjonnirAI::Aggro(), boss_brundirAI::Aggro(), boss_molgeimAI::Aggro(), boss_steelbreakerAI::Aggro(), boss_algalonAI::Aggro(), boss_freyaAI::Aggro(), npc_snaplasherAI::Aggro(), boss_general_vezaxAI::Aggro(), boss_hodirAI::Aggro(), boss_vx001AI::Aggro(), boss_aerial_unitAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_gurtogg_bloodboilAI::Aggro(), boss_doomlordkazzakAI::Aggro(), boss_doomwalkerAI::Aggro(), boss_ahuneAI::Aggro(), npc_wildaAI::Aggro(), boss_nethermancer_sepethreaAI::Aggro(), boss_highlord_kruulAI::Aggro(), boss_lethonAI::Aggro(), npc_burster_wormAI::Aggro(), mob_phoenix_tkAI::Aggro(), boss_kelthuzadAI::Aggro(), boss_essence_of_sufferingAI::Aggro(), boss_essence_of_desireAI::Aggro(), boss_essence_of_angerAI::Aggro(), boss_eadricAI::Aggro(), npc_black_knight_ghoulAI::Aggro(), boss_crusader_druid_restoAI::Aggro(), boss_jaraxxusAI::Aggro(), npc_warden_mellicharAI::Aggro(), npc_dawnblade_blood_knight::Aggro(), boss_majordomoAI::Aggro(), boss_arugalAI::Aggro(), boss_buruAI::Aggro(), boss_forgemaster_garfrostAI::Aggro(), boss_gluthAI::Aggro(), boss_nothAI::Aggro(), boss_keristraszaAI::Aggro(), boss_ichoronAI::Aggro(), npc_shadow_imageAI::AttackRandomTarget(), boss_uromAI::AttackStart(), blood_prince_council_baseAI::blood_prince_council_baseAI(), boss_anubrekhanAI::boss_anubrekhanAI(), boss_chromaggusAI::boss_chromaggusAI(), boss_gluthAI::boss_gluthAI(), boss_highlord_kruulAI::boss_highlord_kruulAI(), boss_ichoronAI::boss_ichoronAI(), boss_jedogaAI::boss_jedogaAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_leviathan_mk2AI::boss_leviathan_mk2AI(), boss_maievAI::boss_maievAI(), boss_moorabiAI::boss_moorabiAI(), boss_reliquary_of_soulsAI::boss_reliquary_of_soulsAI(), boss_sjonnirAI::boss_sjonnirAI(), boss_thekalAI::boss_thekalAI(), boss_vazrudenAI::boss_vazrudenAI(), boss_vx001AI::boss_vx001AI(), npc_simon_game_bunnyAI::BuffPlayers(), boss_ouroAI::Burrow(), boss_malacrassAI::CanUseSpecialAbility(), boss_silver_hand_bossesAI::CanUseSpecialAbility(), mobs_spitelashesAI::CanUseSpecialAbility(), trial_crusader_commonAI::CanUseSpecialAbility(), npc_aoe_damage_triggerAI::CastConsumption(), npc_theramore_spar_controller::CheckCombatantHP(), mob_anubisath_guardianAI::DamageTaken(), boss_ahuneAI::DamageTaken(), npc_frozen_coreAI::DamageTaken(), boss_julianneAI::DamageTaken(), advisor_base_ai::DamageTaken(), npc_death_knight_initiateAI::DamageTaken(), boss_black_knightAI::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), boss_feral_defenderAI::DamageTaken(), boss_freyaAI::DamageTaken(), boss_ingvarAI::DamageTaken(), npc_immortal_guardianAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), npc_iron_constructAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), boss_vx001AI::DamageTaken(), boss_aerial_unitAI::DamageTaken(), boss_skadiAI::DoBoardGrauf(), npc_king_llaneAI::DoCastPrimarySpell(), npc_warchief_blackhandAI::DoCastPrimarySpell(), npc_human_conjurerAI::DoCastPrimarySpell(), npc_orc_warlockAI::DoCastPrimarySpell(), npc_human_footmanAI::DoCastPrimarySpell(), npc_orc_gruntAI::DoCastPrimarySpell(), npc_water_elementalAI::DoCastPrimarySpell(), npc_summoned_daemonAI::DoCastPrimarySpell(), npc_human_chargerAI::DoCastPrimarySpell(), npc_orc_wolfAI::DoCastPrimarySpell(), npc_human_clericAI::DoCastPrimarySpell(), npc_orc_necrolyteAI::DoCastPrimarySpell(), npc_king_llaneAI::DoCastSecondarySpell(), npc_warchief_blackhandAI::DoCastSecondarySpell(), npc_human_conjurerAI::DoCastSecondarySpell(), npc_orc_warlockAI::DoCastSecondarySpell(), npc_human_footmanAI::DoCastSecondarySpell(), npc_orc_gruntAI::DoCastSecondarySpell(), npc_water_elementalAI::DoCastSecondarySpell(), npc_summoned_daemonAI::DoCastSecondarySpell(), npc_human_chargerAI::DoCastSecondarySpell(), npc_orc_wolfAI::DoCastSecondarySpell(), npc_human_clericAI::DoCastSecondarySpell(), npc_orc_necrolyteAI::DoCastSecondarySpell(), npc_ranshallaAI::DoChannelTorchSpell(), npc_simon_game_bunnyAI::DoCleanupGame(), npc_simon_game_bunnyAI::DoCompleteGame(), npc_simon_game_bunnyAI::DoCompleteLevel(), boss_drakkari_colossusAI::DoEmergeElemental(), CreatureAI::DoFakeDeath(), boss_mimironAI::DoFlyToNextRandomSeat(), boss_veknilashAI::DoHandleBerserk(), boss_veklorAI::DoHandleBerserk(), boss_veknilashAI::DoHandleBugAbility(), boss_veklorAI::DoHandleBugAbility(), boss_pyroguard_emberseerAI::DoHandleEmberseerGrowing(), boss_julianneAI::DoHandleRomuloResurrect(), boss_galdarahAI::DoPhaseSwitch(), npc_simon_game_bunnyAI::DoPrepareLevel(), mob_phoenix_tkAI::DoRebirth(), boss_headless_horsemanAI::DoRejoinHead(), boss_head_of_horsemanAI::DoRejoinHead(), boss_halazziAI::DoReuniteSpirits(), npc_redemption_targetAI::DoReviveSelf(), boss_kelidan_the_breakerAI::DoSetupAdds(), npc_simon_game_bunnyAI::DoSetupLevel(), npc_simon_game_bunnyAI::DoSetupPlayerLevel(), boss_cthunAI::DoSpawnTentacles(), boss_silithidRoyaltyAI::DoSpecialAbility(), boss_emerissAI::DoSpecialDragonAbility(), boss_lethonAI::DoSpecialDragonAbility(), boss_taerarAI::DoSpecialDragonAbility(), boss_ysondreAI::DoSpecialDragonAbility(), boss_vazruden_heraldAI::DoSplit(), npc_highlord_darion_mograineAI::DoStartConclusion(), mob_illidari_councilAI::DoStartEvent(), boss_algalonAI::DoStartIntroEvent(), npc_lady_sylvanas_windrunnerAI::DoStartLamentEvent(), boss_lajAI::DoSummons(), boss_high_botanist_freywinnAI::DoSummonSeedling(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), boss_skeramAI::DoTeleport(), boss_headless_horsemanAI::DoTossHead(), boss_ichoronAI::EndSplitPhase(), npc_flame_of_azzinothAI::Enrage(), boss_emerald_dragonAI::EnterCombat(), boss_ragnarosAI::EnterEvadeMode(), boss_kiljaedenAI::EnterEvadeMode(), boss_halazziAI::EnterEvadeMode(), boss_viscidusAI::EnterEvadeMode(), boss_fjolaAI::EnterEvadeMode(), boss_teron_gorefiendAI::EnterEvadeMode(), boss_baron_geddonAI::ExecuteAction(), npc_sunblade_scoutAI::ExecuteAction(), npc_sunblade_protectorAI::ExecuteAction(), mob_ohganAI::ExecuteAction(), boss_thekalAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_watchkeeper_gargolmarAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_broodlordAI::ExecuteAction(), boss_chromaggusAI::ExecuteAction(), boss_ebonrocAI::ExecuteAction(), boss_firemawAI::ExecuteAction(), boss_flamegorAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_razorgoreAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_victor_nefariusAI::ExecuteAction(), npc_dawnblade_blood_knight::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_maiden_of_virtueAI::ExecuteAction(), boss_midnightAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_netherspiteAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_dorotheeAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), priestess_commonAI::ExecuteAction(), boss_priestess_delrissaAI::ExecuteAction(), priestess_companion_commonAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), npc_ellrys_duskhallowAI::ExecuteAction(), npc_eramas_brightblazeAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), npc_warlord_salarisAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), npc_apokoAI::ExecuteAction(), npc_zelfanAI::ExecuteAction(), boss_selin_fireheartAI::ExecuteAction(), boss_vexallusAI::ExecuteAction(), boss_garrAI::ExecuteAction(), boss_gehennasAI::ExecuteAction(), boss_golemaggAI::ExecuteAction(), mob_core_ragerAI::ExecuteAction(), boss_lucifronAI::ExecuteAction(), boss_magmadarAI::ExecuteAction(), boss_majordomoAI::ExecuteAction(), boss_ragnarosAI::ExecuteAction(), boss_shazzrahAI::ExecuteAction(), boss_sulfuronAI::ExecuteAction(), mob_flamewaker_priestAI::ExecuteAction(), npc_death_knight_initiateAI::ExecuteAction(), npc_highlord_darion_mograineAI::ExecuteAction(), boss_scarlet_commander_mograineAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_apothecary_hummelAI::ExecuteAction(), mob_arugal_voidwalkerAI::ExecuteAction(), boss_arugalAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kalecgos_humanoidAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), npc_sinister_reflectionAI::ExecuteAction(), boss_muruAI::ExecuteAction(), boss_entropiusAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_spirit_lynxAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_malacrassAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_zuljinAI::ExecuteAction(), boss_arlokkAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), npc_gurubashi_bat_riderAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_venoxisAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), boss_temporusAI::ExecuteAction(), boss_anetheronAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_azgalorAI::ExecuteAction(), boss_kazrogalAI::ExecuteAction(), boss_rage_winterchillAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), npc_thrallAI::ExecuteAction(), npc_tyrande_whisperwindAI::ExecuteAction(), npc_corrupted_furbolgAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_moamAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), npc_general_andorovAI::ExecuteAction(), npc_kaldorei_eliteAI::ExecuteAction(), boss_kriAI::ExecuteAction(), boss_vemAI::ExecuteAction(), boss_yaujAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_cthunAI::ExecuteAction(), npc_giant_claw_tentacleAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_veknilashAI::ExecuteAction(), boss_veklorAI::ExecuteAction(), boss_viscidusAI::ExecuteAction(), npc_anubisath_sentinelAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_hadronoxAI::ExecuteAction(), boss_krikthirAI::ExecuteAction(), npc_nerubian_burrowerAI::ExecuteAction(), boss_drakkari_elementalAI::ExecuteAction(), boss_drakkari_colossusAI::ExecuteAction(), npc_living_mojoAI::ExecuteAction(), boss_moorabiAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_ickAI::ExecuteAction(), boss_krickAI::ExecuteAction(), boss_tyrannusAI::ExecuteAction(), boss_rimefang_posAI::ExecuteAction(), boss_deathbringer_saurfangAI::ExecuteAction(), boss_lady_deathwhisperAI::ExecuteAction(), boss_gothikAI::ExecuteAction(), boss_grobbulusAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_loathebAI::ExecuteAction(), boss_maexxnaAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_patchwerkAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_thaddiusAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_keristraszaAI::ExecuteAction(), boss_ormorokAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_eregosAI::ExecuteAction(), boss_baltharusAI::ExecuteAction(), boss_zarithrianAI::ExecuteAction(), boss_sjonnirAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), boss_kelesethAI::ExecuteAction(), mob_dragonflayer_forge_masterAI::ExecuteAction(), boss_skadiAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_ichoronAI::ExecuteAction(), boss_xevozzAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_nexusprince_shaffarAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), npc_bonechewer_combatant::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_akama_illidanAI::ExecuteAction(), boss_maievAI::ExecuteAction(), npc_flame_of_azzinothAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_essence_of_sufferingAI::ExecuteAction(), boss_essence_of_desireAI::ExecuteAction(), boss_essence_of_angerAI::ExecuteAction(), npc_akamaAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_gathios_the_shattererAI::ExecuteAction(), boss_high_nethermancer_zerevorAI::ExecuteAction(), boss_lady_malandeAI::ExecuteAction(), boss_veras_darkshadowAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_fathomguard_sharkkisAI::ExecuteAction(), boss_fathomguard_tidalvessAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_black_stalkerAI::ExecuteAction(), boss_hungarfenAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_olm_the_summonerAI::ExecuteAction(), boss_kiggler_the_crazedAI::ExecuteAction(), boss_blindeye_the_seerAI::ExecuteAction(), boss_krosh_firehandAI::ExecuteAction(), boss_broggokAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), mob_shadowmoon_channelerAI::ExecuteAction(), boss_the_makerAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_vazrudenAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), mob_hellfire_channelerAI::ExecuteAction(), npc_shattered_hand_legionnaire::ExecuteAction(), npc_magister_aledisAI::ExecuteAction(), npc_razorthorn_ravager::ExecuteAction(), mob_torlothAI::ExecuteAction(), npc_commanderAI::ExecuteAction(), npc_doomguard_punisherAI::ExecuteAction(), npc_shivan_assassinAI::ExecuteAction(), npc_eye_of_shartuulAI::ExecuteAction(), npc_dreadmawAI::ExecuteAction(), npc_shartuulAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), mob_solarium_priestAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), npc_shaman_fire_elementalAI::ExecuteAction(), npc_shaman_earth_elementalAI::ExecuteAction(), npc_nether_rayAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), npc_kaylaan_the_lostAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), boss_yorAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), npc_skyguard_rangerAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_grand_collectorAI::ExecuteActions(), npc_apexis_flayerAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteAssassinActions(), mob_bt_battle_fighterAI::ExecuteCaalenActions(), mob_bt_battle_fighterAI::ExecuteMagisterActions(), mob_bt_battle_fighterAI::ExecuteRavagerActions(), mob_bt_battle_fighterAI::ExecuteShadowlordActions(), PlayerAI::ExecuteSpells(), mob_bt_battle_fighterAI::ExecuteSuccubusActions(), mob_bt_battle_fighterAI::ExecuteVindicatorActions(), boss_sartharionAI::FetchDragons(), npc_anzu_bird_spiritAI::FreezeSpirits(), npc_disobedient_dragonmaw_peonAI::HandleAngry(), boss_entropiusAI::HandleAttackDelay(), boss_leotheras_the_blindAI::HandleBanish(), boss_talon_king_ikissAI::HandleBlink(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), boss_felmystAI::HandleBreath(), npc_burster_wormAI::HandleChaseSequence(), boss_felmystAI::HandleDemonicVapor(), boss_alarAI::HandleDiveBomb(), boss_aranAI::HandleDrinking(), boss_felmystAI::HandleDummyNuke(), mob_phoenix_tkAI::HandleEmberBlast(), boss_cthunAI::HandleEmerge(), npc_nerubian_burrowerAI::HandleEmerge(), boss_ahuneAI::HandleEmerge(), boss_cthunAI::HandleEndWeaken(), npc_grand_collectorAI::HandleEvent(), boss_viscidusAI::HandleExplode(), boss_felmystAI::HandleFelmystSpawnDelay(), boss_felblood_kaelthasAI::HandleGravityLapse(), boss_skeramAI::HandleInitImages(), boss_majordomoAI::HandleOutro(), boss_archimondeAI::HandleOutro(), boss_telestraAI::HandlePersonalityMerge(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_ragnarosAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_magtheridonAI::HandlePhaseTransition(), boss_buruAI::HandlePhaseTwo(), npc_ethereal_sphereAI::HandlePlayerSummon(), boss_omor_the_unscarredAI::HandlePullBack(), boss_high_inquisitor_whitemaneAI::HandleResurrection(), boss_scarlet_commander_mograineAI::HandleRevivedTimer(), npc_singularityAI::HandleSpawn(), boss_ouroAI::HandleSpawnDelay(), npc_shadowfang_prisonerAI::HandleSpeech(), boss_heiganAI::HandleStartChanneling(), npc_kalecgosAI::HandleTransform(), npc_flame_tsunamiAI::HandleTsunamiDamage(), npc_flame_tsunamiAI::HandleTsunamiVisual(), boss_cthunAI::HandleWeaken(), boss_victor_nefariusAI::JustDidDialogueStep(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), boss_illidan_stormrageAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), npc_image_of_medivhAI::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_areiAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_lich_king_villageAI::JustDidDialogueStep(), npc_king_ymironAI::JustDidDialogueStep(), boss_malygosAI::JustDidDialogueStep(), boss_algalonAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), boss_thorimAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_millhouse_manastormAI::JustDidDialogueStep(), npc_eye_of_acherusAI::JustDied(), boss_brutallusAI::JustDied(), boss_zuljinAI::JustDied(), npc_thrall_old_hillsbradAI::JustDied(), npc_buru_eggAI::JustDied(), boss_amanitarAI::JustDied(), boss_volazjAI::JustDied(), boss_black_knightAI::JustDied(), boss_fjolaAI::JustDied(), boss_tharonjaAI::JustDied(), npc_living_mojoAI::JustDied(), boss_festergutAI::JustDied(), boss_rotfaceAI::JustDied(), boss_the_lich_king_iccAI::JustDied(), boss_razuviousAI::JustDied(), boss_thaddiusAI::JustDied(), npc_power_sparkAI::JustDied(), boss_uromAI::JustDied(), boss_varosAI::JustDied(), boss_brundirAI::JustDied(), boss_molgeimAI::JustDied(), boss_steelbreakerAI::JustDied(), npc_iron_rootsAI::JustDied(), npc_saronite_vaporAI::JustDied(), boss_ignisAI::JustDied(), boss_kologarnAI::JustDied(), npc_guardian_of_yoggAI::JustDied(), mob_stolen_soulAI::JustDied(), npc_enslaved_soulAI::JustDied(), boss_shade_of_akamaAI::JustDied(), boss_teron_gorefiendAI::JustDied(), boss_fathomguard_sharkkisAI::JustDied(), boss_fathomguard_tidalvessAI::JustDied(), boss_fathomguard_caribdisAI::JustDied(), boss_ahuneAI::JustDied(), boss_hungarfenAI::JustDied(), npc_shade_of_the_horsemanAI::JustDied(), mob_fireswornAI::JustDied(), boss_krickAI::JustDied(), mob_tenebronAI::JustDied(), mob_shadronAI::JustDied(), mob_vesperonAI::JustDied(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_kalecgosAI::JustPreventedDeath(), boss_sathrovarrAI::JustPreventedDeath(), boss_illidan_stormrageAI::JustPreventedDeath(), boss_apothecary_hummelAI::JustPreventedDeath(), boss_moira_bronzebeardAI::JustReachedHome(), boss_mr_smiteAI::JustReachedHome(), boss_terestianAI::JustReachedHome(), npc_ellrys_duskhallowAI::JustReachedHome(), hyjalAI::JustReachedHome(), boss_silithidRoyaltyAI::JustReachedHome(), boss_eye_of_cthunAI::JustReachedHome(), boss_jaraxxusAI::JustReachedHome(), boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergutAI::JustReachedHome(), boss_lady_deathwhisperAI::JustReachedHome(), boss_rotfaceAI::JustReachedHome(), boss_algalonAI::JustReachedHome(), npc_iron_constructAI::JustReachedHome(), boss_kologarnAI::JustReachedHome(), boss_leviathan_mk2AI::JustReachedHome(), boss_kelesethAI::JustReachedHome(), boss_hungarfenAI::JustReachedHome(), boss_magtheridonAI::JustReachedHome(), npc_burster_wormAI::JustReachedHome(), boss_nefarianAI::JustRespawned(), boss_terestianAI::JustRespawned(), npc_ellrys_duskhallowAI::JustRespawned(), boss_apothecary_hummelAI::JustRespawned(), boss_kiljaedenAI::JustRespawned(), npc_darknessAI::JustRespawned(), npc_zulian_prowlerAI::JustRespawned(), boss_renatakiAI::JustRespawned(), npc_soulflayerAI::JustRespawned(), boss_skeramAI::JustRespawned(), npc_nerubian_burrowerAI::JustRespawned(), boss_kelesethAI::JustRespawned(), npc_decaying_ghoulAI::JustRespawned(), boss_yorAI::JustRespawned(), npc_ethereum_prisoner_dungeonAI::JustRespawned(), boss_anzuAI::JustRespawned(), npc_disruptor_towerAI::JustRespawned(), npc_enslaved_soulAI::JustRespawned(), npc_caribdis_cyclone::JustRespawned(), mob_underbog_mushroomAI::JustRespawned(), boss_kelidan_the_breakerAI::JustRespawned(), mob_torlothAI::JustRespawned(), npc_nether_vaporAI::JustRespawned(), NetherCharge::JustRespawned(), npc_skyguard_prisonerAI::JustRespawned(), npc_ethereum_prisonerAI::JustRespawned(), GossipNPCAI::JustRespawned(), npc_injured_rainspeakerAI::JustStartedEscort(), npc_highlord_darion_mograineAI::JustSummoned(), npc_time_riftAI::JustSummoned(), boss_professor_putricideAI::JustSummoned(), boss_rotfaceAI::JustSummoned(), boss_malygosAI::JustSummoned(), boss_auriayaAI::JustSummoned(), boss_ymironAI::JustSummoned(), npc_teleportation_portalAI::JustSummoned(), npc_dragonmaw_racerAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_terestianAI::JustSummoned(), npc_zelfanAI::JustSummoned(), boss_ragnarosAI::JustSummoned(), npc_portal_targetAI::JustSummoned(), boss_anetheronAI::JustSummoned(), boss_ichoronAI::JustSummoned(), boss_anzuAI::JustSummoned(), boss_illidan_stormrageAI::JustSummoned(), npc_blade_of_azzinothAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_kaelthasAI::JustSummoned(), boss_volazjAI::KilledUnit(), boss_headless_horsemanAI::KilledUnit(), npc_rocket_strikeAI::KilledUnit(), boss_mandokirAI::KilledUnit(), mob_hellfire_channelerAI::mob_hellfire_channelerAI(), mob_illidari_councilAI::mob_illidari_councilAI(), boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_dejaAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_jennyAI::MoveInLineOfSight(), boss_anubarak_trialAI::MoveInLineOfSight(), npc_lich_king_villageAI::MoveInLineOfSight(), npc_corrupted_soul_fragmentAI::MoveInLineOfSight(), boss_lich_king_horAI::MoveInLineOfSight(), npc_ball_of_flameAI::MoveInLineOfSight(), npc_volatile_ooze_iccAI::MoveInLineOfSight(), npc_gas_cloud_iccAI::MoveInLineOfSight(), npc_power_sparkAI::MoveInLineOfSight(), npc_planar_anomalyAI::MoveInLineOfSight(), npc_black_holeAI::MoveInLineOfSight(), npc_scrapbotAI::MoveInLineOfSight(), npc_ominous_cloudAI::MoveInLineOfSight(), npc_charged_sphereAI::MoveInLineOfSight(), npc_void_travelerAI::MoveInLineOfSight(), mob_enchanted_elementalAI::MoveInLineOfSight(), mob_steamrigger_mechanicAI::MoveInLineOfSight(), npc_spirit_shadeAI::MoveInLineOfSight(), DarkFiendAI::MoveInLineOfSight(), boss_temporusAI::MoveInLineOfSight(), boss_veknilashAI::MoveInLineOfSight(), boss_veklorAI::MoveInLineOfSight(), npc_dalaran_guardian_mageAI::MoveInLineOfSight(), boss_rimefang_posAI::MoveInLineOfSight(), npc_living_poisonAI::MoveInLineOfSight(), npc_ethereal_sphereAI::MoveInLineOfSight(), mob_water_globuleAI::MoveInLineOfSight(), npc_bashir_flesh_fiendAI::MovementInform(), mob_ashtongue_sorcererAI::MovementInform(), npc_shade_of_the_horsemanAI::MovementInform(), npc_core_of_entropiusAI::MovementInform(), npc_amanishi_scoutAI::MovementInform(), boss_forgemaster_garfrostAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), boss_alarAI::MovementInform(), boss_archimondeAI::MovementInform(), npc_shadow_demonAI::MovementInform(), npc_ethereal_frostworgAI::MovementInform(), boss_selin_fireheartAI::MovementInform(), boss_sapphironAI::MovementInform(), npc_chess_piece_genericAI::MovementInform(), npc_lazy_peonAI::MovementInform(), boss_tethyrAI::MovementInform(), trial_companion_commonAI::MovementInform(), boss_ymironAI::MovementInform(), boss_professor_putricideAI::MovementInform(), boss_the_lich_king_iccAI::MovementInform(), npc_magrami_spectre::MovementInform(), boss_blood_queen_lanathelAI::MovementInform(), boss_sindragosaAI::MovementInform(), npc_rookery_hatcherAI::MovementInform(), boss_jedogaAI::MovementInform(), boss_hadronoxAI::MovementInform(), npc_scourged_flamespitterAI::MovementInform(), npc_kinetic_bombAI::MovementInform(), boss_malygosAI::MovementInform(), boss_savianaAI::MovementInform(), boss_volkhanAI::MovementInform(), npc_dark_matterAI::MovementInform(), boss_leviathan_mk2AI::MovementInform(), npc_fel_guard_houndAI::MovementInform(), npc_rethhedronAI::MovementInform(), npc_domesticated_felboarAI::MovementInform(), npc_sunblade_scoutAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), npc_anachronos_the_ancientAI::MovementInform(), npc_oil_stained_wolfAI::MovementInform(), boss_icehowlAI::MovementInform(), npc_grand_admiral_westwindAI::MovementInform(), boss_lich_king_horAI::MovementInform(), npc_graufAI::MovementInform(), npc_advanced_target_dummyAI::npc_advanced_target_dummyAI(), npc_corrupted_soul_fragmentAI::npc_corrupted_soul_fragmentAI(), npc_darknessAI::npc_darknessAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_doom_blossomAI::npc_doom_blossomAI(), npc_doomguard_punisherAI::npc_doomguard_punisherAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_infernal_houndAI::npc_infernal_houndAI(), npc_jennyAI::npc_jennyAI(), npc_krunAI::npc_krunAI(), npc_malfurionAI::npc_malfurionAI(), npc_scarlet_ghoulAI::npc_scarlet_ghoulAI(), npc_shade_of_the_horsemanAI::npc_shade_of_the_horsemanAI(), npc_shartuulAI::npc_shartuulAI(), npc_shivan_assassinAI::npc_shivan_assassinAI(), npc_time_riftAI::npc_time_riftAI(), MutateBug::OnApply(), SpectralBlast::OnEffectExecute(), StunRopeAttunement::OnEffectExecute(), ZombieChowSearch::OnPeriodicTrigger(), boss_thekalAI::OnRevive(), mob_phoenix_tkAI::OnSpellCooldownAdded(), npc_anubarak_trial_spikeAI::PermafrostHit(), boss_mr_smiteAI::PhaseEquipEnd(), boss_mr_smiteAI::PhaseEquipProcess(), CreatureEventAI::ProcessAction(), boss_lich_king_horAI::ReceiveAIEvent(), boss_aranAI::ReceiveAIEvent(), boss_shazzrahAI::ReceiveAIEvent(), twin_jormungars_commonAI::ReceiveAIEvent(), boss_professor_putricideAI::ReceiveAIEvent(), boss_halion_realAI::ReceiveAIEvent(), boss_freyaAI::ReceiveAIEvent(), npc_skyguard_aether_techAI::ReceiveAIEvent(), npc_ice_spear_bunnyAI::ReceiveAIEvent(), npc_sinister_reflectionAI::ReceiveAIEvent(), npc_anubarak_trial_spikeAI::ReceiveAIEvent(), npc_voice_yogg_saronAI::ReceiveAIEvent(), npc_brain_yogg_saronAI::ReceiveAIEvent(), npc_simon_game_bunnyAI::ReceiveAIEvent(), npc_netherspite_portalAI::ReceiveAIEvent(), npc_chess_piece_genericAI::ReceiveAIEvent(), npc_scarlet_ghoulAI::ReceiveAIEvent(), boss_head_of_horsemanAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), boss_crusader_druid_balanceAI::ReceiveAIEvent(), boss_crusader_hunterAI::ReceiveAIEvent(), boss_crusader_mageAI::ReceiveAIEvent(), boss_crusader_death_knightAI::ReceiveAIEvent(), boss_crusader_warriorAI::ReceiveAIEvent(), boss_crusader_paladin_retriAI::ReceiveAIEvent(), boss_crusader_rogueAI::ReceiveAIEvent(), boss_malygosAI::ReceiveAIEvent(), boss_algalonAI::ReceiveAIEvent(), boss_xt_002AI::ReceiveAIEvent(), boss_heart_deconstructorAI::ReceiveAIEvent(), npc_ghoul_feeding_bunnyAI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), boss_crusader_druid_restoAI::ReceiveAIEvent(), boss_crusader_paladin_holyAI::ReceiveAIEvent(), boss_crusader_priest_discAI::ReceiveAIEvent(), boss_crusader_shaman_restoAI::ReceiveAIEvent(), boss_crusader_priest_shadowAI::ReceiveAIEvent(), boss_crusader_warlockAI::ReceiveAIEvent(), boss_skadiAI::ReceiveAIEvent(), mob_big_oozeAI::ReceiveAIEvent(), npc_champion_mountAI::ReceiveAIEvent(), mob_core_ragerAI::ReceiveAIEvent(), boss_ichoronAI::ReceiveAIEvent(), npc_isillienAI::ReceiveAIEvent(), boss_gythAI::Reset(), boss_razorgoreAI::Reset(), boss_mr_smiteAI::Reset(), mob_arcane_sphereAI::Reset(), npc_eramas_brightblazeAI::Reset(), boss_selin_fireheartAI::Reset(), mob_fireswornAI::Reset(), boss_golemaggAI::Reset(), mob_core_ragerAI::Reset(), boss_magmadarAI::Reset(), boss_ragnarosAI::Reset(), boss_headless_horsemanAI::Reset(), boss_brutallusAI::Reset(), boss_alythessAI::Reset(), boss_sacrolashAI::Reset(), boss_felmystAI::Reset(), boss_sathrovarrAI::Reset(), boss_kalecgos_humanoidAI::Reset(), boss_kiljaedenAI::Reset(), npc_sunblade_scoutAI::Reset(), npc_sunblade_protectorAI::Reset(), boss_archaedasAI::Reset(), boss_hakkarAI::Reset(), boss_jeklikAI::Reset(), npc_gurubashi_bat_riderAI::Reset(), npc_soulflayerAI::Reset(), npc_ruul_snowhoofAI::Reset(), boss_aeonusAI::Reset(), hyjalAI::Reset(), npc_building_triggerAI::Reset(), npc_kerlonianAI::Reset(), npc_corrupted_furbolgAI::Reset(), boss_ossirianAI::Reset(), npc_solenorAI::Reset(), npc_giant_claw_tentacleAI::Reset(), npc_ouro_spawnerAI::Reset(), npc_ouro_moundAI::Reset(), boss_veknilashAI::Reset(), npc_impale_targetAI::Reset(), trial_companion_commonAI::Reset(), boss_anubarak_trialAI::Reset(), npc_anubarak_trial_spikeAI::Reset(), boss_jaraxxusAI::Reset(), boss_acidmawAI::Reset(), boss_fjolaAI::Reset(), boss_eydisAI::Reset(), npc_firecrackers_bunnyAI::Reset(), npc_jaina_sylvanas_horAI::Reset(), npc_ball_of_flameAI::Reset(), npc_kinetic_bombAI::Reset(), npc_dark_nucleusAI::Reset(), mob_little_oozeAI::Reset(), mob_big_oozeAI::Reset(), mob_frost_bombAI::Reset(), boss_anubrekhanAI::Reset(), boss_gluthAI::Reset(), boss_maexxnaAI::Reset(), boss_thaddiusAI::Reset(), npc_tesla_coilAI::Reset(), npc_power_sparkAI::Reset(), boss_keristraszaAI::Reset(), npc_planar_anomalyAI::Reset(), npc_arcane_beamAI::Reset(), boss_bjarngrimAI::Reset(), boss_feral_defenderAI::Reset(), boss_flame_leviathanAI::Reset(), npc_healthy_sporeAI::Reset(), npc_icicle_targetAI::Reset(), npc_iron_constructAI::Reset(), boss_kologarnAI::Reset(), npc_mimiron_flamesAI::Reset(), npc_rocket_strikeAI::Reset(), npc_brain_yogg_saronAI::Reset(), npc_teleportation_portalAI::Reset(), boss_shirrakAI::Reset(), npc_bashir_flesh_fiendAI::Reset(), npc_greater_shadowfiend::Reset(), boss_gurtogg_bloodboilAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_shahrazAI::Reset(), boss_essence_of_angerAI::Reset(), npc_akamaAI::Reset(), boss_najentusAI::Reset(), boss_illidari_councilAI::Reset(), mobs_nether_drakeAI::Reset(), boss_morogrim_tidewalkerAI::Reset(), npc_frozen_coreAI::Reset(), boss_warchief_kargath_bladefistAI::Reset(), npc_ancestral_wolfAI::Reset(), boss_dalliahAI::Reset(), boss_soccothratesAI::Reset(), boss_lord_sanguinarAI::Reset(), npc_raging_flamesAI::Reset(), npc_infernal_houndAI::Reset(), boss_emerissAI::Reset(), boss_taerarAI::Reset(), npc_the_cleanerAI::Reset(), npc_shaman_fire_elementalAI::Reset(), npc_snakesAI::Reset(), mob_vrykul_skeletonAI::Revive(), npc_anubisath_sentinelAI::SetAbility(), boss_viscidusAI::SetPhase(), npc_kerlonianAI::SetSleeping(), npc_klinfranAI::SpellHit(), boss_onyxiaAI::SpellHit(), npc_solenorAI::SpellHit(), npc_simone_seductressAI::SpellHit(), npc_artoriusAI::SpellHit(), boss_anubarak_trialAI::SpellHit(), boss_brundirAI::SpellHit(), boss_steelbreakerAI::SpellHit(), boss_halazziAI::SpellHit(), boss_zuljinAI::SpellHit(), boss_essence_of_angerAI::SpellHit(), npc_saplingAI::SpellHit(), npc_buru_eggAI::SpellHit(), boss_garrAI::SpellHit(), mob_fireswornAI::SpellHit(), boss_kaelthasAI::SpellHit(), npc_forest_frogAI::SpellHit(), boss_nothAI::SpellHit(), npc_image_of_medivhAI::SpellHit(), npc_image_arcanagosAI::SpellHit(), boss_ignisAI::SpellHit(), npc_iron_constructAI::SpellHit(), boss_aerial_unitAI::SpellHit(), boss_volazjAI::SpellHitTarget(), boss_icehowlAI::SpellHitTarget(), boss_bronjahmAI::SpellHitTarget(), boss_kaelthasAI::SpellHitTarget(), boss_zuljinAI::SpiritAcquired(), npc_dragonmaw_racerAI::StartAttack(), npc_ethereum_prisonerAI::StartEvent(), npc_shade_of_the_horsemanAI::StartLanding(), boss_alarAI::StartPhaseTransition(), npc_dragonmaw_racerAI::StartRace(), npc_brann_hosAI::StartTribunalEvent(), npc_burster_wormAI::Submerge(), npc_deathstalker_faerleiaAI::SummonedCreatureJustDied(), npc_brain_yogg_saronAI::SummonedCreatureJustDied(), boss_ahuneAI::SummonedCreatureJustDied(), boss_majordomoAI::SummonedCreatureJustDied(), boss_mandokirAI::SummonedCreatureJustDied(), boss_jedogaAI::SummonedMovementInform(), boss_warp_splinterAI::SummonTreants(), boss_gurtogg_bloodboilAI::SwitchPhase(), boss_netherspiteAI::SwitchPhases(), boss_darkweaver_sythAI::SythSummoning(), boss_veklorAI::TeleportTwin(), npc_creature_generatorAI::TrySummoning(), guardAI::UpdateAI(), npc_ironhand_guardianAI::UpdateAI(), npc_shattered_sun_marksmanAI::UpdateAI(), npc_portal_targetAI::UpdateAI(), mob_soaring_eagleAI::UpdateAI(), npc_corrupted_lightning_totemAI::UpdateAI(), npc_amanishi_hatcherAI::UpdateAI(), npc_forest_frogAI::UpdateAI(), npc_amanishi_tempestAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_ashliAI::UpdateAI(), npc_amanishi_scoutAI::UpdateAI(), boss_archimondeAI::UpdateAI(), boss_noxxionAI::UpdateAI(), boss_eranikusAI::UpdateAI(), npc_anzu_bird_spiritAI::UpdateAI(), npc_adyen_the_lightwardenAI::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), boss_thorngrinAI::UpdateAI(), boss_mechano_lord_capacitusAI::UpdateAI(), boss_highlord_kruulAI::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), npc_snakesAI::UpdateAI(), npc_advanced_target_dummyAI::UpdateAI(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), npc_scourged_flamespitterAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), boss_plugger_spazzringAI::UpdateAI(), boss_emperor_dagran_thaurissanAI::UpdateAI(), boss_moira_bronzebeardAI::UpdateAI(), boss_general_angerforgeAI::UpdateAI(), boss_high_interrogator_gerstahnAI::UpdateAI(), boss_gythAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseerAI::UpdateAI(), npc_rookery_hatcherAI::UpdateAI(), npc_klinfranAI::UpdateAI(), boss_mr_smiteAI::UpdateAI(), npc_apprentice_mirvedaAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), npc_fiendish_portalAI::UpdateAI(), boss_strawmanAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_bigbadwolfAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_romuloAI::UpdateAI(), npc_echo_of_medivhAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), npc_eye_of_acherusAI::UpdateAI(), boss_arcanist_doanAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_herodAI::UpdateAI(), boss_darkmaster_gandlingAI::UpdateAI(), boss_jandicebarovAI::UpdateAI(), npc_spectral_tutorAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), boss_cannon_master_willeyAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), boss_maleki_the_pallidAI::UpdateAI(), npc_shadow_imageAI::UpdateAI(), boss_archaedasAI::UpdateAI(), npc_soulflayerAI::UpdateAI(), example_creatureAI::UpdateAI(), mobs_spitelashesAI::UpdateAI(), boss_mawsAI::UpdateAI(), boss_aeonusAI::UpdateAI(), boss_chrono_lord_dejaAI::UpdateAI(), npc_rabid_bearAI::UpdateAI(), npc_magrami_spectre::UpdateAI(), npc_lazy_peonAI::UpdateAI(), mobs_risen_husk_spiritAI::UpdateAI(), boss_tethyrAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), mob_anubisath_guardianAI::UpdateAI(), npc_solenorAI::UpdateAI(), mob_aquementasAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), npc_simone_the_inconspicuousAI::UpdateAI(), npc_artoriusAI::UpdateAI(), boss_zumrahAI::UpdateAI(), boss_amanitarAI::UpdateAI(), boss_jedogaAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_volazjAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_oil_stained_wolfAI::UpdateAI(), npc_sinkhole_kill_creditAI::UpdateAI(), npc_seaforium_depth_chargeAI::UpdateAI(), boss_eadricAI::UpdateAI(), boss_paletressAI::UpdateAI(), boss_black_knightAI::UpdateAI(), npc_black_knight_ghoulAI::UpdateAI(), trial_companion_commonAI::UpdateAI(), npc_trial_grand_championAI::UpdateAI(), boss_anubarak_trialAI::UpdateAI(), npc_anubarak_trial_spikeAI::UpdateAI(), npc_anubarak_trial_frostsphereAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), boss_jaraxxusAI::UpdateAI(), boss_gormokAI::UpdateAI(), twin_jormungars_commonAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_fjolaAI::UpdateAI(), boss_eydisAI::UpdateAI(), npc_destructive_wardAI::UpdateAI(), boss_novosAI::UpdateAI(), boss_tharonjaAI::UpdateAI(), boss_trollgoreAI::UpdateAI(), npc_ancient_male_vrykulAI::UpdateAI(), npc_silvermoon_harryAI::UpdateAI(), npc_infantryAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_devourer_of_soulsAI::UpdateAI(), boss_lich_king_horAI::UpdateAI(), npc_collapsing_icicleAI::UpdateAI(), npc_dark_nucleusAI::UpdateAI(), npc_blood_orb_controlAI::UpdateAI(), blood_prince_council_baseAI::UpdateAI(), boss_valanar_iccAI::UpdateAI(), boss_keleseth_iccAI::UpdateAI(), boss_taldaram_iccAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_festergutAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), npc_bone_spikeAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), npc_volatile_ooze_iccAI::UpdateAI(), npc_gas_cloud_iccAI::UpdateAI(), boss_rotfaceAI::UpdateAI(), mob_little_oozeAI::UpdateAI(), mob_big_oozeAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_spinestalker_iccAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), npc_planar_anomalyAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_varosAI::UpdateAI(), boss_sartharionAI::UpdateAI(), dummy_dragonAI::UpdateAI(), mob_twilight_eggsAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), npc_meteor_strike_initialAI::UpdateAI(), npc_orb_carrierAI::UpdateAI(), boss_savianaAI::UpdateAI(), boss_bjarngrimAI::UpdateAI(), mob_stormforged_lieutenantAI::UpdateAI(), boss_ionarAI::UpdateAI(), boss_lokenAI::UpdateAI(), boss_volkhanAI::UpdateAI(), mob_molten_golemAI::UpdateAI(), npc_dark_matterAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_molgeimAI::UpdateAI(), boss_steelbreakerAI::UpdateAI(), boss_algalonAI::UpdateAI(), npc_living_constellationAI::UpdateAI(), npc_worm_holeAI::UpdateAI(), boss_auriayaAI::UpdateAI(), boss_feral_defenderAI::UpdateAI(), boss_flame_leviathanAI::UpdateAI(), npc_freya_wardAI::UpdateAI(), npc_mimiron_infernoAI::UpdateAI(), boss_freyaAI::UpdateAI(), npc_water_spiritAI::UpdateAI(), npc_storm_lasherAI::UpdateAI(), npc_eonars_giftAI::UpdateAI(), npc_nature_bombAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_hodirAI::UpdateAI(), boss_ignisAI::UpdateAI(), boss_kologarnAI::UpdateAI(), boss_mimironAI::UpdateAI(), boss_leviathan_mk2AI::UpdateAI(), boss_vx001AI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_proximity_mineAI::UpdateAI(), npc_bot_triggerAI::UpdateAI(), npc_mimiron_flamesAI::UpdateAI(), npc_frost_bombAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), npc_razorscale_spawnerAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_sifAI::UpdateAI(), npc_runic_colossusAI::UpdateAI(), npc_thunder_orbAI::UpdateAI(), boss_xt_002AI::UpdateAI(), boss_heart_deconstructorAI::UpdateAI(), boss_saraAI::UpdateAI(), boss_yogg_saronAI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), npc_brain_yogg_saronAI::UpdateAI(), npc_guardian_of_yoggAI::UpdateAI(), npc_immortal_guardianAI::UpdateAI(), npc_death_rayAI::UpdateAI(), npc_keeper_mimironAI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mob_vrykul_skeletonAI::UpdateAI(), boss_ymironAI::UpdateAI(), npc_ghoul_feeding_bunnyAI::UpdateAI(), npc_decaying_ghoulAI::UpdateAI(), mob_stolen_soulAI::UpdateAI(), boss_exarch_maladaarAI::UpdateAI(), boss_pandemoniusAI::UpdateAI(), boss_darkweaver_sythAI::UpdateAI(), boss_ambassador_hellmawAI::UpdateAI(), boss_grandmaster_vorpilAI::UpdateAI(), boss_murmurAI::UpdateAI(), mob_ashtongue_channelerAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_vimgol_AI::UpdateAI(), npc_vimgol_visual_bunnyAI::UpdateAI(), npc_bloodmaul_dire_wolfAI::UpdateAI(), boss_doomlordkazzakAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_fathomguard_caribdisAI::UpdateAI(), boss_hydross_the_unstableAI::UpdateAI(), npc_inner_demonAI::UpdateAI(), boss_thespiaAI::UpdateAI(), boss_mekgineer_steamriggerAI::UpdateAI(), mob_underbog_mushroomAI::UpdateAI(), boss_grand_warlock_nethekurseAI::UpdateAI(), mob_fel_orc_convertAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_aeranasAI::UpdateAI(), npc_fel_guard_houndAI::UpdateAI(), mob_lumpAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_spawned_oronok_tornheartAI::UpdateAI(), npc_domesticated_felboarAI::UpdateAI(), npc_salsalabimAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), npc_warden_mellicharAI::UpdateAI(), npc_arcatraz_defenderAI::UpdateAI(), boss_dalliahAI::UpdateAI(), boss_harbinger_skyrissAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), boss_high_botanist_freywinnAI::UpdateAI(), boss_lajAI::UpdateAI(), boss_warp_splinterAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), boss_thaladred_the_darkenerAI::UpdateAI(), boss_lord_sanguinarAI::UpdateAI(), boss_grand_astromancer_capernianAI::UpdateAI(), boss_master_engineer_telonicusAI::UpdateAI(), boss_nethermancer_sepethreaAI::UpdateAI(), npc_raging_flamesAI::UpdateAI(), boss_pathaleon_the_calculatorAI::UpdateAI(), mob_nether_wraithAI::UpdateAI(), mob_unkor_the_ruthlessAI::UpdateAI(), npc_cooshcooshAI::UpdateAI(), boss_emerald_dragonAI::UpdateAI(), guard_shattrath_aldorAI::UpdateAI(), guard_shattrath_scryerAI::UpdateAI(), npc_spring_rabbitAI::UpdateAI(), npc_mage_mirror_imageAI::UpdateAI(), npc_flash_freezeAI::UpdateAI(), boss_champion_warriorAI::UpdateChampionAI(), boss_champion_mageAI::UpdateChampionAI(), boss_champion_shamanAI::UpdateChampionAI(), boss_champion_hunterAI::UpdateChampionAI(), boss_champion_rogueAI::UpdateCompanionAI(), mob_tenebronAI::UpdateDragonAI(), boss_emerissAI::UpdateDragonAI(), boss_taerarAI::UpdateDragonAI(), boss_ysondreAI::UpdateDragonAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_tirion_fordringAI::UpdateEscortAI(), npc_daphne_stilwellAI::UpdateEscortAI(), npc_captured_sprite_darterAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_kineloryAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_phalanxAI::UpdateEscortAI(), npc_hurley_blackbreathAI::UpdateEscortAI(), npc_corporal_keeshan_escortAI::UpdateEscortAI(), npc_torekAI::UpdateEscortAI(), npc_arthasAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_captured_arkonarinAI::UpdateEscortAI(), npc_areiAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_proudhoofAI::UpdateEscortAI(), npc_apothecary_hanesAI::UpdateEscortAI(), npc_squad_leaderAI::UpdateEscortAI(), npc_father_kamarosAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_nagrand_captiveAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_captured_vanguardAI::UpdateEscortAI(), npc_wildaAI::UpdateEscortAI(), npc_akunoAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_skywingAI::UpdateEscortAI(), npc_fhwoorAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_nexus_drake_hatchlingAI::UpdateFollowerAI(), UpdateSpellLists(), boss_kelthuzadAI::UpdateSummoning(), npc_shadowfang_prisonerAI::WaypointReached(), npc_squire_roweAI::WaypointReached(), npc_reginald_windsorAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_ruul_snowhoofAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_rocknotAI::WaypointReached(), npc_marshal_windsorAI::WaypointReached(), npc_barnesAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_custodian_of_timeAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_father_kamarosAI::WaypointReached(), npc_injured_rainspeakerAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), npc_wildaAI::WaypointReached(), and npc_isla_starmaneAI::WaypointStart().
DoDistance()
void UnitAI::DoDistance ()
DoFindFriendlyEligibleDispel() [1/3]
CreatureList UnitAI::DoFindFriendlyEligibleDispel (float range, uint32 dispelMask = 0, uint32 mechanicMask = 0, bool self = true) const
Definition at line 771 of file UnitAI.cpp.
References m_unit, and Cell::VisitGridObjects().
DoFindFriendlyEligibleDispel() [2/3]
CreatureList UnitAI::DoFindFriendlyEligibleDispel (SpellEntry const * spellInfo, bool self = true) const
Definition at line 729 of file UnitAI.cpp.
References CalculateSpellRange(), DoFindFriendlyEligibleDispel(), SpellEntry::Effect, SpellEntry::EffectMiscValue, GetDispellMask(), MAX_EFFECT_INDEX, SPELL_EFFECT_DISPEL, and SPELL_EFFECT_DISPEL_MECHANIC.
DoFindFriendlyEligibleDispel() [3/3]
CreatureList UnitAI::DoFindFriendlyEligibleDispel (uint32 spellId, bool self = true) const
Definition at line 724 of file UnitAI.cpp.
References SQLStorage::LookupEntry(), and sSpellTemplate.
Referenced by CreatureEventAI::CheckEvent(), ChooseTarget(), DoFindFriendlyEligibleDispel(), npc_zelfanAI::ExecuteAction(), and boss_yaujAI::ExecuteAction().
DoFindFriendlyMissingBuff() [1/2]
CreatureList UnitAI::DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self = true) const
Definition at line 744 of file UnitAI.cpp.
References SQLStorage::LookupEntry(), and sSpellTemplate.
Referenced by CreatureEventAI::CheckEvent(), and ChooseTarget().
DoFindFriendlyMissingBuff() [2/2]
CreatureList UnitAI::DoFindFriendlyMissingBuff (SpellEntry const * spellInfo, bool inCombat, bool self = true) const
Definition at line 749 of file UnitAI.cpp.
References CalculateSpellRange(), SpellEntry::Id, m_unit, and Cell::VisitGridObjects().
DoFlee()
bool UnitAI::DoFlee (uint32 duration = 0)
Definition at line 836 of file UnitAI.cpp.
References CONFIG_UINT32_CREATURE_FAMILY_FLEE_DELAY, Unit::GetVictim(), m_unit, ORDER_FLEEING, SetAIOrder(), SetCombatScriptStatus(), Unit::SetInPanic(), and sWorld.
Referenced by CreatureAI::EnterCombat(), npc_corrupted_furbolgAI::ExecuteAction(), CreatureEventAI::ProcessAction(), and npc_kindal_moonweaverAI::UpdateFollowerAI().
DoMeleeAttackIfReady()
bool UnitAI::DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
== Helper functions ============================= This function is used to do the actual melee damage (if possible)
Definition at line 295 of file UnitAI.cpp.
References GetAIOrder(), Unit::hasUnitState(), m_unit, ORDER_NONE, UNIT_STAT_MELEE_ATTACKING, and Unit::UpdateMeleeAttackingState().
Referenced by npc_skyguard_rangerAI::UpdateAI(), GuardAI::UpdateAI(), PetAI::UpdateAI(), guardAI::UpdateAI(), boss_kazzakAI::UpdateAI(), npc_shattered_sun_marksmanAI::UpdateAI(), npc_amanishi_hatcherAI::UpdateAI(), npc_amanishi_tempestAI::UpdateAI(), npc_amanishi_scoutAI::UpdateAI(), boss_archimondeAI::UpdateAI(), npc_aged_dying_ancient_kodoAI::UpdateAI(), boss_noxxionAI::UpdateAI(), boss_eranikusAI::UpdateAI(), npc_taskmaster_fizzuleAI::UpdateAI(), boss_yorAI::UpdateAI(), boss_anzuAI::UpdateAI(), npc_bashir_flesh_fiendAI::UpdateAI(), npc_grand_collectorAI::UpdateAI(), npc_akamaAI::UpdateAI(), npc_apexis_flayerAI::UpdateAI(), boss_warlord_kalithreshAI::UpdateAI(), npc_scrap_reaverAI::UpdateAI(), npc_adyen_the_lightwardenAI::UpdateAI(), npc_kaylaan_the_lostAI::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), npc_dirty_larryAI::UpdateAI(), boss_thorngrinAI::UpdateAI(), boss_mechano_lord_capacitusAI::UpdateAI(), boss_highlord_kruulAI::UpdateAI(), npc_snakesAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_scourged_flamespitterAI::UpdateAI(), boss_plugger_spazzringAI::UpdateAI(), boss_ambassador_flamelashAI::UpdateAI(), boss_emperor_dagran_thaurissanAI::UpdateAI(), boss_general_angerforgeAI::UpdateAI(), boss_high_interrogator_gerstahnAI::UpdateAI(), boss_gythAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), boss_pyroguard_emberseerAI::UpdateAI(), npc_rookery_hatcherAI::UpdateAI(), npc_klinfranAI::UpdateAI(), boss_mr_smiteAI::UpdateAI(), npc_apprentice_mirvedaAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), boss_strawmanAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_bigbadwolfAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_romuloAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), boss_arcanist_doanAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_herodAI::UpdateAI(), boss_darkmaster_gandlingAI::UpdateAI(), boss_jandicebarovAI::UpdateAI(), npc_spectral_tutorAI::UpdateAI(), npc_deathstalker_faerleiaAI::UpdateAI(), npc_dashel_stonefistAI::UpdateAI(), mob_yennikuAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), boss_cannon_master_willeyAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), boss_maleki_the_pallidAI::UpdateAI(), boss_silver_hand_bossesAI::UpdateAI(), mobs_spectral_ghostly_citizenAI::UpdateAI(), npc_calvin_montagueAI::UpdateAI(), boss_archaedasAI::UpdateAI(), npc_soulflayerAI::UpdateAI(), example_creatureAI::UpdateAI(), mobs_spitelashesAI::UpdateAI(), boss_mawsAI::UpdateAI(), boss_aeonusAI::UpdateAI(), boss_chrono_lord_dejaAI::UpdateAI(), npc_rabid_bearAI::UpdateAI(), npc_magrami_spectre::UpdateAI(), mobs_risen_husk_spiritAI::UpdateAI(), npc_smolderwing::UpdateAI(), boss_onyxiaAI::UpdateAI(), mob_anubisath_guardianAI::UpdateAI(), npc_solenorAI::UpdateAI(), mob_aquementasAI::UpdateAI(), npc_plucky_johnsonAI::UpdateAI(), npc_precious_the_devourerAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), npc_simone_the_inconspicuousAI::UpdateAI(), npc_artoriusAI::UpdateAI(), boss_zumrahAI::UpdateAI(), boss_amanitarAI::UpdateAI(), boss_jedogaAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_volazjAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_oil_stained_wolfAI::UpdateAI(), boss_eadricAI::UpdateAI(), boss_paletressAI::UpdateAI(), boss_black_knightAI::UpdateAI(), npc_black_knight_ghoulAI::UpdateAI(), trial_companion_commonAI::UpdateAI(), npc_trial_grand_championAI::UpdateAI(), boss_anubarak_trialAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), boss_jaraxxusAI::UpdateAI(), boss_gormokAI::UpdateAI(), twin_jormungars_commonAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_fjolaAI::UpdateAI(), boss_eydisAI::UpdateAI(), boss_tharonjaAI::UpdateAI(), boss_trollgoreAI::UpdateAI(), npc_silvermoon_harryAI::UpdateAI(), npc_infantryAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_devourer_of_soulsAI::UpdateAI(), boss_lich_king_horAI::UpdateAI(), npc_jaina_sylvanas_horAI::UpdateAI(), boss_valanar_iccAI::UpdateAI(), boss_taldaram_iccAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_festergutAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_rotfaceAI::UpdateAI(), mob_little_oozeAI::UpdateAI(), mob_big_oozeAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), npc_spinestalker_iccAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_varosAI::UpdateAI(), boss_sartharionAI::UpdateAI(), dummy_dragonAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), boss_savianaAI::UpdateAI(), npc_tipsy_mcmanusAI::UpdateAI(), boss_bjarngrimAI::UpdateAI(), mob_stormforged_lieutenantAI::UpdateAI(), boss_ionarAI::UpdateAI(), boss_lokenAI::UpdateAI(), boss_volkhanAI::UpdateAI(), mob_molten_golemAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_molgeimAI::UpdateAI(), boss_steelbreakerAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_auriayaAI::UpdateAI(), boss_feral_defenderAI::UpdateAI(), boss_flame_leviathanAI::UpdateAI(), boss_freyaAI::UpdateAI(), npc_water_spiritAI::UpdateAI(), npc_storm_lasherAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_hodirAI::UpdateAI(), boss_ignisAI::UpdateAI(), boss_kologarnAI::UpdateAI(), boss_leviathan_mk2AI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), npc_runic_colossusAI::UpdateAI(), boss_xt_002AI::UpdateAI(), npc_guardian_of_yoggAI::UpdateAI(), npc_immortal_guardianAI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), mob_vrykul_skeletonAI::UpdateAI(), boss_ymironAI::UpdateAI(), npc_decaying_ghoulAI::UpdateAI(), mob_stolen_soulAI::UpdateAI(), boss_exarch_maladaarAI::UpdateAI(), boss_pandemoniusAI::UpdateAI(), boss_darkweaver_sythAI::UpdateAI(), boss_ambassador_hellmawAI::UpdateAI(), boss_grandmaster_vorpilAI::UpdateAI(), boss_murmurAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_vimgol_AI::UpdateAI(), npc_bloodmaul_dire_wolfAI::UpdateAI(), boss_doomlordkazzakAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_fathomguard_caribdisAI::UpdateAI(), boss_hydross_the_unstableAI::UpdateAI(), npc_spawn_of_hydrossAI::UpdateAI(), npc_inner_demonAI::UpdateAI(), boss_thespiaAI::UpdateAI(), boss_mekgineer_steamriggerAI::UpdateAI(), boss_grand_warlock_nethekurseAI::UpdateAI(), mob_fel_orc_convertAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_aeranasAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), mob_lumpAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_spawned_oronok_tornheartAI::UpdateAI(), npc_domesticated_felboarAI::UpdateAI(), mob_bt_battle_fighterAI::UpdateAI(), npc_salsalabimAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), npc_arcatraz_defenderAI::UpdateAI(), boss_dalliahAI::UpdateAI(), boss_harbinger_skyrissAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), boss_high_botanist_freywinnAI::UpdateAI(), boss_lajAI::UpdateAI(), boss_warp_splinterAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), boss_thaladred_the_darkenerAI::UpdateAI(), boss_lord_sanguinarAI::UpdateAI(), boss_master_engineer_telonicusAI::UpdateAI(), boss_nethermancer_sepethreaAI::UpdateAI(), npc_raging_flamesAI::UpdateAI(), boss_pathaleon_the_calculatorAI::UpdateAI(), mob_nether_wraithAI::UpdateAI(), mob_unkor_the_ruthlessAI::UpdateAI(), npc_avatar_of_terokkAI::UpdateAI(), npc_minion_of_terokkAI::UpdateAI(), npc_cooshcooshAI::UpdateAI(), boss_emerald_dragonAI::UpdateAI(), guard_shattrath_aldorAI::UpdateAI(), guard_shattrath_scryerAI::UpdateAI(), npc_chicken_cluckAI::UpdateAI(), npc_the_cleanerAI::UpdateAI(), UpdateAI(), PossessedAI::UpdateAI(), npc_shattered_sun_warriorAI::UpdateAI(), npc_hive_zara_larvaAI::UpdateAI(), npc_iron_constructAI::UpdateAI(), boss_shade_of_akamaAI::UpdateAI(), mob_steamrigger_mechanicAI::UpdateAI(), npc_manaforge_spawnAI::UpdateAI(), npc_saplingAI::UpdateAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_galen_goodwardAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_tirion_fordringAI::UpdateEscortAI(), npc_daphne_stilwellAI::UpdateEscortAI(), npc_captured_sprite_darterAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_kineloryAI::UpdateEscortAI(), npc_phalanxAI::UpdateEscortAI(), npc_hurley_blackbreathAI::UpdateEscortAI(), npc_grark_lorkrubAI::UpdateEscortAI(), npc_rinjiAI::UpdateEscortAI(), npc_corporal_keeshan_escortAI::UpdateEscortAI(), mob_scarlet_traineeAI::UpdateEscortAI(), npc_tapoke_slim_jahnAI::UpdateEscortAI(), example_escortAI::UpdateEscortAI(), npc_muglashAI::UpdateEscortAI(), npc_torekAI::UpdateEscortAI(), npc_demolitionist_legosoAI::UpdateEscortAI(), npc_arthasAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_melizza_brimbuzzleAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_captured_arkonarinAI::UpdateEscortAI(), npc_areiAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_wizzlecranks_shredderAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_ranshallaAI::UpdateEscortAI(), npc_lurgglbrAI::UpdateEscortAI(), npc_proudhoofAI::UpdateEscortAI(), npc_harrison_jonesAI::UpdateEscortAI(), npc_apothecary_hanesAI::UpdateEscortAI(), npc_squad_leaderAI::UpdateEscortAI(), npc_father_kamarosAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_shaheenAI::UpdateEscortAI(), npc_nagrand_captiveAI::UpdateEscortAI(), npc_maxx_a_million_escortAI::UpdateEscortAI(), npc_captured_vanguardAI::UpdateEscortAI(), npc_wildaAI::UpdateEscortAI(), npc_akunoAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_fhwoorAI::UpdateEscortAI(), npc_garments_of_questsAI::UpdateEscortAI(), npc_marshal_windsorAI::UpdateEscortAI(), npc_dorius_stonetenderAI::UpdateEscortAI(), npc_morokkAI::UpdateEscortAI(), npc_injured_rainspeakerAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), FollowerAI::UpdateFollowerAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), npc_nexus_drake_hatchlingAI::UpdateFollowerAI(), npc_kerlonianAI::UpdateFollowerAI(), npc_kittenAI::UpdateFollowerAI(), npc_toogaAI::UpdateFollowerAI(), npc_ringoAI::UpdateFollowerAI(), and ScriptedPetAI::UpdatePetAI().
DoResetThreat()
void UnitAI::DoResetThreat ()
Definition at line 780 of file UnitAI.cpp.
References Unit::CanHaveThreatList(), Object::GetEntry(), Unit::getThreatManager(), ThreatManager::isThreatListEmpty(), m_unit, ThreatManager::modifyAllThreatPercent(), and script_error_log().
Referenced by mob_water_globuleAI::AcquireNewTarget(), npc_shadow_imageAI::AttackRandomTarget(), npc_dark_nucleusAI::DamageTaken(), boss_buruAI::DoAttackNewTarget(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_julianneAI::DoRemoveFakeDeath(), boss_romuloAI::DoRemoveFakeDeath(), boss_skeramAI::DoTeleport(), Spell::EffectScriptEffect(), boss_nightbaneAI::ExecuteAction(), priestess_commonAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_venoxisAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_yaujAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), npc_raging_flamesAI::FixateRandomTarget(), boss_talon_king_ikissAI::HandleBlink(), boss_gothikAI::HandleGroundPhase(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_alarAI::HandleRebirth(), dummy_blackheart_the_inciterAI::JustRespawned(), boss_nightbaneAI::MovementInform(), boss_doomwalkerAI::MovementInform(), spell_pursuit::OnApply(), LeoWhirlwindProc::OnEffectExecute(), boss_nothAI::OnSpellCast(), npc_anubarak_trial_spikeAI::PermafrostHit(), npc_feather_vortexAI::PickNewTarget(), npc_ouro_moundAI::PickNewTarget(), boss_shazzrahAI::ReceiveAIEvent(), boss_arlokkAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), boss_leotheras_the_blindAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), mob_vrykul_skeletonAI::Revive(), boss_thekalBaseAI::Revive(), three_nature_alliesAI::SpellHit(), boss_zuljinAI::SpellHit(), boss_netherspiteAI::SwitchPhases(), boss_veklorAI::TeleportTwin(), trial_companion_commonAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), boss_feral_defenderAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_hydross_the_unstableAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), advisor_base_ai::UpdateAI(), and boss_thaladred_the_darkenerAI::UpdateAI().
DoRetreat()
virtual bool UnitAI::DoRetreat () inline virtual
Reimplemented in CreatureAI.
Definition at line 464 of file UnitAI.h.
DoSelectConditionalFriendly()
Unit * UnitAI::DoSelectConditionalFriendly (float range, int32 unitConditionId) const
Definition at line 702 of file UnitAI.cpp.
References m_unit, and Cell::VisitGridObjects().
Referenced by ChooseTarget().
DoSelectLowestHpFriendly()
Unit * UnitAI::DoSelectLowestHpFriendly (float range, float minMissing = 1.f, bool percent = false, bool targetSelf = true) const
Definition at line 680 of file UnitAI.cpp.
References m_unit, and Cell::VisitGridObjects().
Referenced by boss_malacrassAI::CanUseSpecialAbility(), boss_silver_hand_bossesAI::CanUseSpecialAbility(), mobs_spitelashesAI::CanUseSpecialAbility(), trial_crusader_commonAI::CanUseSpecialAbility(), CreatureEventAI::CheckEvent(), ChooseTarget(), npc_dawnblade_blood_knight::ExecuteAction(), boss_priestess_delrissaAI::ExecuteAction(), npc_apokoAI::ExecuteAction(), mob_flamewaker_priestAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), mob_arugal_voidwalkerAI::ExecuteAction(), npc_sinister_reflectionAI::ExecuteAction(), boss_blindeye_the_seerAI::ExecuteAction(), mob_hellfire_channelerAI::ExecuteAction(), mob_solarium_priestAI::ExecuteAction(), mob_bt_battle_fighterAI::ExecuteVindicatorActions(), boss_julianneAI::UpdateAI(), boss_zumrahAI::UpdateAI(), boss_paletressAI::UpdateAI(), boss_champion_shamanAI::UpdateChampionAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_kineloryAI::UpdateEscortAI(), and npc_arthasAI::UpdateEscortAI().
DoStartMovement()
void UnitAI::DoStartMovement (Unit * victim)
Definition at line 819 of file UnitAI.cpp.
References Unit::GetMotionMaster(), m_attackAngle, m_attackDistance, m_chaseRun, m_moveFurther, m_unit, and MotionMaster::MoveChase().
Referenced by JumpingEnded(), CreatureAI::RetreatingEnded(), SetCombatMovement(), SetCurrentRangedMode(), and TimedFleeingEnded().
EnterCombat()
void UnitAI::EnterCombat (Unit *) virtual
Called for reaction at enter to combat if not in combat yet.
Parameters
enemy Unit* of whom the Creature enters combat with, can be nullptr
Reimplemented in boss_emerald_dragonAI, boss_tethyrAI, ScriptedAI, CreatureEventAI, CreatureAI, and boss_high_inquisitor_whitemaneAI.
Definition at line 105 of file UnitAI.cpp.
References AddInitialCooldowns(), GetSpellList(), and m_spellListCooldown.
Referenced by CreatureAI::EnterCombat(), and Unit::SetInCombatState().
EnterEvadeMode()
void UnitAI::EnterEvadeMode () virtual
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
Reimplemented in npc_the_cleanerAI, npc_injured_patientAI, boss_alarAI, boss_warp_splinterAI, boss_soccothratesAI, boss_dalliahAI, npc_millhouse_manastormAI, npc_shivan_assassinAI, npc_spawned_oronok_tornheartAI, mob_shadowmoon_soulstealerAI, mob_torlothAI, npc_scrapped_fel_reaverAI, npc_manaforge_spawnAI, npc_maghar_escortAI, npc_magister_aledisAI, npc_anchorite_baradaAI, boss_magtheridonAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_vazruden_heraldAI, boss_ahuneAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_fathomguard_caribdisAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, npc_fel_cannon, boss_teron_gorefiendAI, npc_enslaved_soulAI, boss_essence_of_angerAI, essence_base_AI, boss_maievAI, boss_xevozzAI, boss_ichoronAI, boss_saraAI, boss_sifAI, boss_thorimAI, boss_vx001AI, boss_hodirAI, boss_freyaAI, mob_molten_golemAI, boss_uromAI, npc_tesla_coilAI, boss_nothAI, boss_kelthuzadAI, boss_heiganAI, boss_gothikAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_deathbringer_saurfangAI, blood_prince_council_baseAI, npc_grand_admiral_westwindAI, npc_infantryAI, npc_living_mojoAI, boss_fjolaAI, npc_beast_combat_stalkerAI, boss_jaraxxusAI, npc_nexus_drake_hatchlingAI, boss_volazjAI, npc_disciple_of_naralexAI, npc_precious_the_devourerAI, npc_taskmaster_fizzuleAI, npc_anubisath_sentinelAI, boss_viscidusAI, OuroScarab, npc_ouro_moundAI, boss_cthunAI, npc_solenorAI, npc_kaldorei_eliteAI, npc_general_andorovAI, boss_ayamissAI, boss_eranikusAI, npc_thrall_old_hillsbradAI, hyjalAI, boss_archimondeAI, boss_azuregosAI, boss_thekalAI, boss_mandokirAI, boss_jeklikAI, boss_zuljinAI, boss_halazziAI, npc_tirion_fordringAI, npc_isillienAI, npc_taelan_fordringAI, boss_entropiusAI, boss_muruAI, boss_kiljaedenAI, boss_kalecgos_humanoidAI, boss_sathrovarrAI, boss_kalecgosAI, boss_felmystAI, boss_sacrolashAI, boss_alythessAI, boss_baroness_anastariAI, mob_yennikuAI, npc_spectral_tutorAI, boss_high_inquisitor_whitemaneAI, boss_scarlet_commander_mograineAI, npc_death_knight_initiateAI, boss_ragnarosAI, priestess_companion_commonAI, boss_felblood_kaelthasAI, npc_chess_piece_genericAI, boss_nightbaneAI, boss_netherspiteAI, boss_attumenAI, boss_midnightAI, boss_nefarianAI, boss_coren_direbrewAI, ScriptedAI, FollowerAI, PlayerAI, CreatureEventAI, TotemAI, PetAI, NullCreatureAI, and GuardianAI.
Definition at line 114 of file UnitAI.cpp.
References ClearCombatOnlyRoot(), Unit::CombatStopWithPets(), Unit::GetMotionMaster(), GetReactState(), Unit::IsAlive(), WorldObject::IsBoarded(), Unit::IsImmobilizedState(), m_unit, MotionMaster::MoveTargetedHome(), REACT_PASSIVE, Unit::RemoveAllAurasOnEvade(), Unit::TriggerEvadeEvents(), and Unit::TriggerHomeEvents().
Referenced by boss_moroesAI::DoSpawnGuests(), EffectDummyCreature_npc_taelan_fordring(), EffectDummyCreature_spell_capture_grark(), EffectScriptEffectCreature_spell_stun_break(), CreatureEventAI::EnterEvadeMode(), ScriptedAI::EnterEvadeMode(), Unit::EvadeTimerExpired(), GossipSelect_npc_silvermoon_harry(), Unit::HandleExitCombat(), ChatHandler::HandleNpcEvade(), npc_dirty_larryAI::NextStep(), CreatureLinkingHolder::ProcessSlave(), Unit::SelectHostileTarget(), boss_cthunAI::SummonedCreatureDespawn(), CreatureAI::TimedFleeingEnded(), and boss_eranikusAI::UpdateAI().
ExecuteAction()
virtual void UnitAI::ExecuteAction (uint32) inline virtual
Reimplemented in npc_caribdis_cyclone, PallidHorrorAI, ScourgeMinion, npc_nether_rayAI, npc_shaman_earth_elementalAI, npc_shaman_fire_elementalAI, npc_burster_wormAI, boss_void_reaverAI, mob_solarium_priestAI, boss_high_astromancer_solarianAI, npc_shartuulAI, npc_dreadmawAI, npc_eye_of_shartuulAI, npc_shivan_assassinAI, npc_doomguard_punisherAI, npc_commanderAI, mob_torlothAI, npc_razorthorn_ravager, npc_magister_aledisAI, npc_shattered_hand_legionnaire, mob_hellfire_channelerAI, boss_magtheridonAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_vazruden_heraldAI, boss_the_makerAI, mob_shadowmoon_channelerAI, boss_kelidan_the_breakerAI, boss_broggokAI, boss_krosh_firehandAI, boss_blindeye_the_seerAI, boss_kiggler_the_crazedAI, boss_olm_the_summonerAI, boss_high_king_maulgarAI, boss_gruulAI, boss_swamplord_muselekAI, boss_hungarfenAI, boss_black_stalkerAI, boss_the_lurker_belowAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, boss_terokkAI, boss_veras_darkshadowAI, boss_lady_malandeAI, boss_high_nethermancer_zerevorAI, boss_gathios_the_shattererAI, boss_najentusAI, boss_teron_gorefiendAI, boss_supremusAI, npc_akamaAI, boss_essence_of_angerAI, boss_essence_of_desireAI, boss_essence_of_sufferingAI, boss_shahrazAI, npc_flame_of_azzinothAI, boss_maievAI, npc_akama_illidanAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_bonechewer_combatant, npc_bonechewer_brawler, boss_blackheart_the_inciterAI, boss_nexusprince_shaffarAI, boss_shirrakAI, npc_ethereal_sphereAI, boss_xevozzAI, boss_ichoronAI, boss_svalaAI, boss_skadiAI, mob_dragonflayer_forge_masterAI, boss_kelesethAI, boss_ingvarAI, boss_sjonnirAI, boss_zarithrianAI, boss_baltharusAI, boss_eregosAI, boss_telestraAI, boss_ormorokAI, boss_keristraszaAI, boss_anomalusAI, boss_thaddiusAI, boss_sapphironAI, boss_patchwerkAI, boss_nothAI, boss_maexxnaAI, boss_loathebAI, boss_kelthuzadAI, boss_heiganAI, boss_grobbulusAI, boss_gothikAI, boss_sir_zeliekAI, boss_thane_korthazzAI, boss_rivendare_naxxAI, boss_lady_blaumeuxAI, boss_lady_deathwhisperAI, boss_deathbringer_saurfangAI, boss_rimefang_posAI, boss_tyrannusAI, boss_krickAI, boss_ickAI, boss_forgemaster_garfrostAI, boss_bronjahmAI, boss_sladranAI, boss_moorabiAI, boss_galdarahAI, npc_living_mojoAI, boss_drakkari_colossusAI, boss_drakkari_elementalAI, npc_nerubian_burrowerAI, boss_krikthirAI, boss_hadronoxAI, npc_anubisath_defenderAI, npc_anubisath_sentinelAI, boss_viscidusAI, boss_veklorAI, boss_veknilashAI, boss_twin_emperorsAI, boss_skeramAI, boss_sarturaAI, OuroScarab, boss_ouroAI, boss_huhuranAI, boss_fankrissAI, npc_giant_claw_tentacleAI, boss_cthunAI, boss_eye_of_cthunAI, boss_yaujAI, boss_vemAI, boss_kriAI, npc_kaldorei_eliteAI, npc_general_andorovAI, boss_ossirianAI, boss_moamAI, boss_kurinnaxxAI, boss_buruAI, boss_ayamissAI, npc_corrupted_furbolgAI, npc_tyrande_whisperwindAI, npc_thrallAI, npc_jaina_proudmooreAI, hyjalAI, boss_rage_winterchillAI, boss_kazrogalAI, boss_azgalorAI, boss_archimondeAI, boss_anetheronAI, boss_temporusAI, boss_azuregosAI, boss_venoxisAI, boss_marliAI, npc_gurubashi_bat_riderAI, boss_jeklikAI, boss_hakkarAI, boss_arlokkAI, boss_zuljinAI, boss_nalorakkAI, boss_malacrassAI, boss_janalaiAI, boss_spirit_lynxAI, boss_halazziAI, boss_akilzonAI, boss_entropiusAI, boss_muruAI, npc_sinister_reflectionAI, boss_kiljaedenAI, boss_kalecgos_humanoidAI, boss_sathrovarrAI, boss_kalecgosAI, boss_felmystAI, boss_sacrolashAI, boss_alythessAI, boss_brutallusAI, boss_arugalAI, mob_arugal_voidwalkerAI, boss_apothecary_hummelAI, boss_high_inquisitor_whitemaneAI, boss_scarlet_commander_mograineAI, npc_highlord_darion_mograineAI, npc_death_knight_initiateAI, mob_flamewaker_priestAI, boss_sulfuronAI, boss_shazzrahAI, boss_ragnarosAI, boss_majordomoAI, boss_magmadarAI, boss_lucifronAI, mob_core_ragerAI, boss_golemaggAI, boss_gehennasAI, boss_garrAI, boss_vexallusAI, boss_selin_fireheartAI, npc_zelfanAI, npc_apokoAI, npc_garaxxasAI, npc_warlord_salarisAI, npc_yazzaiAI, npc_eramas_brightblazeAI, npc_ellrys_duskhallowAI, npc_kagani_nightstrikeAI, priestess_companion_commonAI, boss_priestess_delrissaAI, priestess_commonAI, boss_felblood_kaelthasAI, boss_dorotheeAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_nightbaneAI, boss_netherspiteAI, boss_moroesAI, boss_attumenAI, boss_midnightAI, boss_maiden_of_virtueAI, boss_curatorAI, npc_dawnblade_blood_knight, boss_victor_nefariusAI, boss_vaelastraszAI, boss_razorgoreAI, boss_nefarianAI, boss_flamegorAI, boss_firemawAI, boss_ebonrocAI, boss_chromaggusAI, boss_broodlordAI, boss_coren_direbrewAI, boss_alarAI, boss_watchkeeper_gargolmarAI, boss_ahuneAI, boss_talon_king_ikissAI, boss_thekalAI, mob_ohganAI, npc_sunblade_protectorAI, npc_sunblade_scoutAI, and boss_baron_geddonAI.
Definition at line 509 of file UnitAI.h.
Referenced by ExecuteActions().
ExecuteActions()
void UnitAI::ExecuteActions () virtual
Implements CombatActions.
Reimplemented in npc_vindicator_sedaiAI, npc_apexis_flayerAI, npc_grand_collectorAI, npc_bashir_flesh_fiendAI, npc_skyguard_rangerAI, boss_anzuAI, npc_ethereum_prisoner_dungeonAI, boss_yorAI, priestess_commonAI, boss_highlord_kruulAI, boss_kaelthasAI, mob_bt_battle_fighterAI, npc_kaylaan_the_lostAI, boss_warlord_kalithreshAI, and boss_kazzakAI.
Definition at line 957 of file UnitAI.cpp.
References CanExecuteCombatAction(), Unit::CastSpell(), ExecuteAction(), CombatActions::GetActionReadyStatus(), CombatActions::GetCombatActionCount(), GetCombatScriptStatus(), MotionMaster::GetCurrent(), Unit::GetMotionMaster(), Unit::GetVictim(), IsCombatMovement(), MovementGenerator::IsReachable(), m_teleportUnreachable, m_unit, and TRIGGERED_OLD_TRIGGERED.
Referenced by boss_archimondeAI::UpdateAI(), npc_akamaAI::UpdateAI(), npc_commanderAI::UpdateAI(), and UpdateAI().
GetAIInformation()
virtual void UnitAI::GetAIInformation (ChatHandler &) inline virtual
== Information about AI ========================
This funcion is used to display information about the AI. It is called when the .npc aiinfo command is used. Use this for on-the-fly debugging
Parameters
reader is a ChatHandler to send messages to.
Reimplemented from CombatActions.
Reimplemented in boss_kaelthasAI, npc_commanderAI, npc_simon_game_bunnyAI, boss_illidan_stormrageAI, npc_anubisath_sentinelAI, npc_arthasAI, boss_kiljaedenAI, boss_brutallusAI, mob_arugal_voidwalkerAI, npc_highlord_darion_mograineAI, boss_thermapluggAI, Scripted_NoMovementAI, ScriptedAI, npc_escortAI, and CreatureEventAI.
Definition at line 131 of file UnitAI.h.
Referenced by ChatHandler::HandleNpcAIInfoCommand().
GetAIName()
virtual std::string UnitAI::GetAIName () inline protected virtual
Reimplemented in ScriptedAI, CreatureEventAI, TotemAI, PossessedAI, PetAI, NullCreatureAI, GuardianAI, and GuardAI.
Definition at line 572 of file UnitAI.h.
GetAIOrder()
AIOrders UnitAI::GetAIOrder () const inline
Definition at line 461 of file UnitAI.h.
References m_currentAIOrder.
Referenced by CheckForHelp(), DoCastSpellIfCan(), DoMeleeAttackIfReady(), CreatureAI::RetreatingEnded(), TimedFleeingEnded(), and CreatureAI::TimedFleeingEnded().
GetAttackDistance()
uint32 UnitAI::GetAttackDistance () inline
Definition at line 435 of file UnitAI.h.
References m_attackDistance.
Referenced by CheckPathToTarget().
GetCombatScriptStatus()
bool UnitAI::GetCombatScriptStatus () const inline
Definition at line 458 of file UnitAI.h.
References m_combatScriptHappening.
Referenced by ChaseMovementGenerator::Backpedal(), boss_netherspiteAI::boss_netherspiteAI(), ExecuteActions(), boss_kaelthasAI::ExecuteActions(), priestess_commonAI::ExecuteActions(), DarkFiendAI::FindTarget(), CreatureEventAI::GetAIInformation(), GOUse_go_cage_trap(), DarkFiendAI::HandleAttackDelay(), ChatHandler::HandleNpcInfoCommand(), CombatAI::HandleTargetRestoration(), IsTargetingRestricted(), JumpingEnded(), DarkFiendAI::MoveInLineOfSight(), npc_cage_trap_triggerAI::MoveInLineOfSight(), Unit::SelectHostileTarget(), npc_amanishi_scoutAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), and boss_warchief_kargath_bladefistAI::UpdateAI().
GetCurrentRangedMode()
bool UnitAI::GetCurrentRangedMode () inline
Definition at line 518 of file UnitAI.h.
References m_currentRangedMode.
Referenced by boss_felblood_kaelthasAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), boss_lady_malandeAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_kiggler_the_crazedAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::GetSubsequentActionTimer(), and UpdateSpellLists().
GetCurrentWaypointPath()
virtual uint32 UnitAI::GetCurrentWaypointPath () const inline virtual
Reimplemented in npc_escortAI.
Definition at line 560 of file UnitAI.h.
Referenced by WaypointMovementGenerator< Creature >::OnArrived(), and WaypointMovementGenerator< Creature >::SendNextWayPointPath().
GetMainAttackSchoolMask()
SpellSchoolMask UnitAI::GetMainAttackSchoolMask () const
Definition at line 1152 of file UnitAI.cpp.
References Unit::GetMeleeDamageSchoolMask(), m_currentRangedMode, m_mainAttackMask, and m_unit.
GetReactState()
ReactStates UnitAI::GetReactState () const inline
Definition at line 452 of file UnitAI.h.
References m_reactState.
Referenced by PlayerbotAI::_HandleCommandPet(), VehicleInfo::ApplySeatMods(), boss_hadronoxAI::AttackedBy(), Player::CharmSpellInitialize(), EnterEvadeMode(), npc_enslaved_soulAI::EnterEvadeMode(), MoveInLineOfSight(), Player::PetSpellInitialize(), CombatManager::Update(), and Player::VehicleSpellInitialize().
GetScriptData()
virtual uint32 UnitAI::GetScriptData () inline virtual
== Data Fetch bind ==============================
Reimplemented in npc_vimgol_visual_bunnyAI.
Definition at line 286 of file UnitAI.h.
Referenced by Spell::OnCheckTarget().
GetSpellList()
virtual CreatureSpellList const& UnitAI::GetSpellList () const pure virtual
Implemented in PlayerAI, PossessedAI, and CreatureAI.
Referenced by AddInitialCooldowns(), EnterCombat(), SpellListChanged(), and UpdateSpellLists().
HandleAssistanceCall()
virtual void UnitAI::HandleAssistanceCall (Unit * , Unit *) inline virtual
Reimplemented in CreatureAI.
Definition at line 498 of file UnitAI.h.
HandleDelayedInstantAnimation()
void UnitAI::HandleDelayedInstantAnimation (SpellEntry const *) virtual
Reimplemented in CombatAI.
Definition at line 496 of file UnitAI.cpp.
References Unit::GetVictim(), IsTargetingRestricted(), m_unit, and Unit::SetTarget().
Referenced by OnSpellCastStateChange().
HandleMovementOnAttackStart()
void UnitAI::HandleMovementOnAttackStart (Unit * victim, bool targetChange) const virtual
Definition at line 335 of file UnitAI.cpp.
References MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), Unit::hasUnitState(), Unit::InterruptMoving(), m_attackAngle, m_attackDistance, m_dismountOnAggro, m_moveFurther, m_unit, MotionMaster::MoveChase(), MotionMaster::MoveIdle(), RANDOM_MOTION_TYPE, UNIT_STAT_CAN_NOT_REACT, UNIT_STAT_NO_COMBAT_MOVEMENT, UNIT_STAT_PROPELLED, Unit::Unmount(), and WAYPOINT_MOTION_TYPE.
Referenced by AttackStart(), CreatureAI::AttackStart(), and PetAI::AttackStart().
HandleSpellCastResult()
CanCastResult UnitAI::HandleSpellCastResult (CanCastResult result, SpellEntry const * spellInfo)
Definition at line 855 of file UnitAI.cpp.
References CAST_FAIL_CAST_PREVENTED, CAST_FAIL_POWER, CAST_FAIL_TOO_CLOSE, CAST_OK, SpellEntry::Id, m_currentRangedMode, m_mainSpells, m_rangedMode, and SetCurrentRangedMode().
Referenced by DoCastSpellIfCan().
HasReactState()
bool UnitAI::HasReactState (ReactStates state) const inline
Definition at line 453 of file UnitAI.h.
References m_reactState.
Referenced by ScriptedPetAI::AttackedBy(), PetAI::AttackedBy(), AttackStart(), CreatureAI::AttackStart(), MoveInLineOfSight(), PetAI::MoveInLineOfSight(), PetAI::UpdateAI(), ScriptedPetAI::UpdateAI(), and npc_scrap_reaverAI::UpdateAI().
HealedBy()
virtual void UnitAI::HealedBy (Unit * , uint32 &) inline virtual
Called at any Heal received from any Unit.
Parameters
pHealer Unit* which deals the heal
uiHealedAmount Amount of healing received
Reimplemented in trial_crusader_commonAI, CreatureEventAI, NecroticShard, boss_twin_emperorsAI, and boss_illidari_councilAI.
Definition at line 170 of file UnitAI.h.
Referenced by Unit::DealHeal().
IsCombatMovement()
bool UnitAI::IsCombatMovement () const
Definition at line 330 of file UnitAI.cpp.
References Unit::hasUnitState(), m_unit, and UNIT_STAT_NO_COMBAT_MOVEMENT.
Referenced by CreatureEventAI::CheckEvent(), npc_escortAI::CorpseRemoved(), FollowerAI::CorpseRemoved(), ExecuteActions(), ScriptedAI::GetAIInformation(), boss_onyxiaAI::Reset(), and UpdateAI().
IsEligibleForDistancing()
bool UnitAI::IsEligibleForDistancing () const
Definition at line 1170 of file UnitAI.cpp.
References Unit::GetPower(), Unit::GetPowerType(), m_mainSpellCost, m_mainSpellInfo, m_unit, and POWER_MANA.
Referenced by DistanceYourself(), and UpdateAI().
IsMainSpellPrevented()
bool UnitAI::IsMainSpellPrevented (SpellEntry const * spellInfo) const
Definition at line 1157 of file UnitAI.cpp.
References Object::HasFlag(), WorldObject::IsSpellReady(), m_unit, SpellEntry::PreventionType, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
Referenced by OnSpellInterrupt(), and UpdateAI().
IsMeleeEnabled()
bool UnitAI::IsMeleeEnabled () const inline
Definition at line 502 of file UnitAI.h.
References m_meleeEnabled.
Referenced by AbstractWrapperMovementGenerator::Initialize().
IsPreventingDeath()
virtual bool UnitAI::IsPreventingDeath () const inline virtual
Definition at line 500 of file UnitAI.h.
IsRangedUnit()
bool UnitAI::IsRangedUnit () inline
Definition at line 545 of file UnitAI.h.
References m_currentRangedMode.
Referenced by MoveInLineOfSight(), and GuardAI::MoveInLineOfSight().
IsTargetingRestricted()
virtual bool UnitAI::IsTargetingRestricted () inline virtual
Reimplemented in CombatAI.
Definition at line 494 of file UnitAI.h.
References GetCombatScriptStatus().
Referenced by HandleDelayedInstantAnimation(), CombatAI::IsTargetingRestricted(), OnChannelStateChange(), and OnSpellCastStateChange().
IsVisible()
bool UnitAI::IsVisible (Unit * pl) const virtual
== State checks =================================
Check if unit is visible for MoveInLineOfSight Note: This check is by default only the state-depending (visibility, range), NOT LineOfSight
Parameters
pWho Unit* who is checked if it is visisble for the creature
Reimplemented in TotemAI, and NullCreatureAI.
Definition at line 675 of file UnitAI.cpp.
References Unit::IsVisibleForOrDetect(), WorldObject::IsWithinDist(), m_unit, and m_visibilityDistance.
Referenced by CreatureVisitCreatureWorker(), PlayerVisitCreatureWorker(), PlayerVisitPlayerWorker(), and UnitVisitObjectsNotifierWorker().
JumpingEnded()
void UnitAI::JumpingEnded () virtual
Definition at line 880 of file UnitAI.cpp.
References DoStartMovement(), GetCombatScriptStatus(), Unit::GetVictim(), Unit::IsAlive(), and m_unit.
JustDied()
void UnitAI::JustDied (Unit *) virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented in mob_netherweb_victimAI, mob_fel_orc_convertAI, mob_vesperonAI, mob_shadronAI, mob_tenebronAI, npc_harrison_jonesAI, trial_crusader_commonAI, npc_twilight_volunteerAI, npc_oox17tnAI, npc_oox22feAI, mob_webbed_creatureAI, example_escortAI, boss_silver_hand_bossesAI, npc_orc_necrolyteAI, npc_human_clericAI, npc_orc_wolfAI, npc_human_chargerAI, npc_summoned_daemonAI, npc_water_elementalAI, npc_orc_gruntAI, npc_human_footmanAI, npc_orc_warlockAI, npc_human_conjurerAI, npc_warchief_blackhandAI, npc_king_llaneAI, npc_00x09hlAI, BossAI, SentryTotemAI, boss_emerald_dragonAI, mob_nether_wraithAI, npc_captured_vanguardAI, mob_shadowmoon_channelerAI, npc_inner_demonAI, boss_terokkAI, boss_veras_darkshadowAI, boss_lady_malandeAI, boss_high_nethermancer_zerevorAI, boss_gathios_the_shattererAI, boss_xevozzAI, boss_ichoronAI, boss_telestraAI, boss_keristraszaAI, boss_anomalusAI, boss_tyrannusAI, boss_krickAI, boss_forgemaster_garfrostAI, boss_veklorAI, boss_veknilashAI, boss_silithidRoyaltyAI, npc_general_andorovAI, npc_keeper_remulosAI, npc_daphne_stilwellAI, npc_a_special_surpriseAI, mob_fireswornAI, npc_garaxxasAI, FollowerAI, npc_escortAI, CreatureEventAI, PetAI, GuardianAI, SilithusBossAI, npc_shade_of_the_horsemanAI, PallidHorrorAI, ScourgeMinion, npc_cultist_engineer, NecroticShard, NecropolisHealthAI, npc_spirit_shadeAI, boss_highlord_kruulAI, npc_avatar_of_terokkAI, boss_pathaleon_the_calculatorAI, boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitusAI, boss_void_reaverAI, boss_master_engineer_telonicusAI, boss_grand_astromancer_capernianAI, boss_lord_sanguinarAI, boss_thaladred_the_darkenerAI, boss_kaelthasAI, boss_high_astromancer_solarianAI, boss_alarAI, boss_warp_splinterAI, boss_thorngrinAI, boss_high_botanist_freywinnAI, boss_soccothratesAI, boss_harbinger_skyrissAI, boss_dalliahAI, npc_warden_mellicharAI, npc_millhouse_manastormAI, npc_commanderAI, mob_shadowmoon_soulstealerAI, npc_shadowlord_deathwailAI, mob_torlothAI, npc_adyen_the_lightwardenAI, npc_scrapped_fel_reaverAI, npc_salhadaarAI, npc_dimensiusAI, npc_vindicator_sedaiAI, npc_anchorite_baradaAI, boss_warchief_kargath_bladefistAI, boss_warbringer_omroggAI, boss_grand_warlock_nethekurseAI, mob_hellfire_channelerAI, boss_magtheridonAI, boss_watchkeeper_gargolmarAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_vazruden_heraldAI, boss_the_makerAI, boss_kelidan_the_breakerAI, boss_broggokAI, Council_Base_AI, boss_high_king_maulgarAI, boss_gruulAI, boss_swamplord_muselekAI, boss_hungarfenAI, boss_warlord_kalithreshAI, boss_mekgineer_steamriggerAI, boss_thespiaAI, boss_ahuneAI, boss_the_lurker_belowAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_hydross_the_unstableAI, boss_fathomguard_caribdisAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, boss_fathomlord_karathressAI, boss_doomwalkerAI, boss_doomlordkazzakAI, npc_soulgrinderAI, npc_vimgol_AI, mob_illidari_councilAI, boss_najentusAI, boss_teron_gorefiendAI, boss_supremusAI, mob_ashtongue_sorcererAI, mob_ashtongue_channelerAI, boss_shade_of_akamaAI, npc_enslaved_soulAI, boss_essence_of_angerAI, boss_shahrazAI, npc_shadow_demonAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_disruptor_towerAI, boss_grandmaster_vorpilAI, boss_blackheart_the_inciterAI, boss_ambassador_hellmawAI, boss_talon_king_ikissAI, boss_darkweaver_sythAI, boss_anzuAI, boss_pandemoniusAI, boss_nexusprince_shaffarAI, boss_shirrakAI, boss_exarch_maladaarAI, mob_stolen_soulAI, boss_ymironAI, boss_svalaAI, npc_graufAI, boss_skadiAI, mob_dragonflayer_forge_masterAI, boss_kelesethAI, boss_ingvarAI, npc_constrictor_tentacleAI, npc_guardian_of_yoggAI, boss_yogg_saronAI, boss_heart_deconstructorAI, boss_xt_002AI, boss_razorscaleAI, boss_leviathan_mk2AI, boss_kologarnAI, boss_ignisAI, npc_flash_freezeAI, npc_saronite_vaporAI, boss_general_vezaxAI, npc_iron_rootsAI, boss_flame_leviathanAI, boss_feral_defenderAI, boss_auriayaAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, npc_brann_hosAI, boss_sjonnirAI, boss_volkhanAI, boss_lokenAI, boss_ionarAI, boss_bjarngrimAI, boss_zarithrianAI, boss_savianaAI, boss_halion_twilightAI, boss_halion_realAI, boss_baltharusAI, dummy_dragonAI, boss_sartharionAI, boss_varosAI, boss_uromAI, boss_eregosAI, boss_ormorokAI, npc_power_sparkAI, boss_malygosAI, boss_feugenAI, boss_stalaggAI, boss_thaddiusAI, boss_razuviousAI, npc_web_wrapAI, boss_kelthuzadAI, boss_sir_zeliekAI, boss_thane_korthazzAI, boss_rivendare_naxxAI, boss_lady_blaumeuxAI, boss_valithria_dreamwalkerAI, boss_the_lich_king_iccAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_rotfaceAI, boss_professor_putricideAI, npc_bone_spikeAI, boss_lord_marrowgarAI, boss_lady_deathwhisperAI, boss_festergutAI, boss_blood_queen_lanathelAI, boss_taldaram_iccAI, boss_keleseth_iccAI, boss_valanar_iccAI, npc_blood_orb_controlAI, boss_ickAI, boss_devourer_of_soulsAI, npc_corrupted_soul_fragmentAI, boss_bronjahmAI, npc_snakeWrapAI, boss_moorabiAI, npc_living_mojoAI, boss_drakkari_elementalAI, boss_trollgoreAI, boss_tharonjaAI, boss_novosAI, boss_eydisAI, boss_fjolaAI, boss_gormokAI, boss_jaraxxusAI, boss_anubarak_trialAI, boss_black_knightAI, boss_krikthirAI, boss_hadronoxAI, boss_anubarakAI, boss_volazjAI, boss_taldaramAI, boss_nadoxAI, boss_jedogaAI, boss_amanitarAI, npc_artoriusAI, npc_simone_seductressAI, npc_anubisath_sentinelAI, boss_viscidusAI, boss_twin_emperorsAI, boss_skeramAI, boss_sarturaAI, boss_ouroAI, boss_huhuranAI, boss_fankrissAI, boss_cthunAI, boss_eye_of_cthunAI, npc_solenorAI, boss_ossirianAI, npc_buru_eggAI, boss_onyxiaAI, boss_tethyrAI, npc_thrall_old_hillsbradAI, hyjalAI, boss_rage_winterchillAI, boss_kazrogalAI, boss_azgalorAI, boss_anetheronAI, npc_medivh_black_morassAI, boss_temporusAI, boss_chrono_lord_dejaAI, boss_aeonusAI, npc_arthasAI, boss_venoxisAI, boss_thekalAI, boss_marliAI, boss_mandokirAI, boss_jeklikAI, boss_arlokkAI, boss_zuljinAI, boss_nalorakkAI, boss_malacrassAI, boss_janalaiAI, boss_halazziAI, boss_akilzonAI, boss_archaedasAI, boss_entropiusAI, boss_kiljaedenAI, boss_kalecgos_humanoidAI, boss_sathrovarrAI, boss_felmystAI, boss_sacrolashAI, boss_alythessAI, boss_brutallusAI, boss_dathrohan_balnazzarAI, npc_deathstalker_faerleiaAI, mob_arugal_voidwalkerAI, boss_herodAI, boss_headless_horsemanAI, npc_scarlet_courierAI, npc_eye_of_acherusAI, boss_sulfuronAI, boss_shazzrahAI, boss_ragnarosAI, boss_magmadarAI, boss_lucifronAI, boss_golemaggAI, boss_gehennasAI, boss_garrAI, boss_baron_geddonAI, boss_vexallusAI, boss_selin_fireheartAI, boss_priestess_delrissaAI, boss_felblood_kaelthasAI, npc_chess_piece_genericAI, boss_romuloAI, boss_julianneAI, boss_bigbadwolfAI, boss_croneAI, boss_roarAI, boss_tinheadAI, boss_strawmanAI, boss_dorotheeAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_nightbaneAI, boss_netherspiteAI, boss_moroesAI, boss_attumenAI, boss_maiden_of_virtueAI, boss_curatorAI, npc_blastmaster_emi_shortfuseAI, boss_thermapluggAI, npc_apprentice_mirvedaAI, npc_klinfranAI, boss_kazzakAI, boss_vaelastraszAI, boss_nefarianAI, boss_flamegorAI, boss_firemawAI, boss_ebonrocAI, boss_chromaggusAI, boss_broodlordAI, boss_pyroguard_emberseerAI, boss_emperor_dagran_thaurissanAI, boss_coren_direbrewAI, boss_ambassador_flamelashAI, boss_plugger_spazzringAI, guardAI, and boss_mawsAI.
Definition at line 132 of file UnitAI.cpp.
References ClearCombatOnlyRoot().
Referenced by PetAI::JustDied(), CreatureEventAI::JustDied(), npc_garaxxasAI::JustDied(), boss_gathios_the_shattererAI::JustDied(), boss_high_nethermancer_zerevorAI::JustDied(), boss_lady_malandeAI::JustDied(), boss_veras_darkshadowAI::JustDied(), BossAI::JustDied(), and Unit::JustKilledCreature().
JustGotCharmed()
virtual void UnitAI::JustGotCharmed (Unit * charmer) inline virtual
Reimplemented in PlayerAI, and npc_razorthorn_ravager.
Definition at line 479 of file UnitAI.h.
JustReachedHome()
virtual void UnitAI::JustReachedHome () inline virtual
Called at reaching home after MoveTargetedHome.
Reimplemented in npc_burster_wormAI, boss_pathaleon_the_calculatorAI, boss_nethermancer_sepethreaAI, boss_void_reaverAI, advisor_base_ai, boss_kaelthasAI, boss_high_astromancer_solarianAI, boss_alarAI, boss_harbinger_skyrissAI, npc_shartuulAI, npc_dreadmawAI, npc_eye_of_shartuulAI, npc_shivan_assassinAI, npc_doomguard_punisherAI, mob_bt_battle_fighterAI, mob_mature_netherwing_drakeAI, npc_kaylaan_the_lostAI, npc_salhadaarAI, npc_captured_vanguardAI, npc_maghar_escortAI, npc_laughing_skullAI, npc_vindicator_sedaiAI, boss_warchief_kargath_bladefistAI, boss_warbringer_omroggAI, boss_grand_warlock_nethekurseAI, mob_hellfire_channelerAI, boss_magtheridonAI, boss_vazrudenAI, boss_vazruden_heraldAI, boss_the_makerAI, mob_shadowmoon_channelerAI, boss_kelidan_the_breakerAI, boss_high_king_maulgarAI, boss_gruulAI, boss_swamplord_muselekAI, boss_hungarfenAI, boss_warlord_kalithreshAI, boss_mekgineer_steamriggerAI, boss_thespiaAI, boss_ahuneAI, boss_the_lurker_belowAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_hydross_the_unstableAI, boss_fathomlord_karathressAI, npc_evergrove_druidAI, boss_illidari_councilAI, boss_najentusAI, boss_supremusAI, boss_shahrazAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_bonechewer_combatant, npc_bonechewer_brawler, boss_grandmaster_vorpilAI, boss_blackheart_the_inciterAI, boss_ambassador_hellmawAI, boss_talon_king_ikissAI, boss_darkweaver_sythAI, boss_anzuAI, boss_ymironAI, boss_svalaAI, npc_graufAI, boss_skadiAI, mob_dragonflayer_forge_masterAI, boss_kelesethAI, boss_ingvarAI, npc_guardian_of_yoggAI, boss_yogg_saronAI, boss_xt_002AI, boss_thorimAI, boss_razorscaleAI, boss_aerial_unitAI, boss_leviathan_mk2AI, boss_kologarnAI, npc_iron_constructAI, boss_ignisAI, boss_hodirAI, boss_general_vezaxAI, boss_freyaAI, boss_flame_leviathanAI, boss_auriayaAI, boss_algalonAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, boss_sjonnirAI, boss_volkhanAI, boss_lokenAI, boss_ionarAI, boss_bjarngrimAI, boss_zarithrianAI, boss_savianaAI, boss_halion_twilightAI, boss_halion_realAI, boss_baltharusAI, dummy_dragonAI, boss_sartharionAI, boss_varosAI, boss_uromAI, boss_eregosAI, boss_telestraAI, boss_malygosAI, boss_thaddiusAddsAI, boss_thaddiusAI, boss_valithria_dreamwalkerAI, boss_the_lich_king_iccAI, boss_sindragosaAI, boss_rotfaceAI, boss_professor_putricideAI, boss_lord_marrowgarAI, boss_lady_deathwhisperAI, boss_festergutAI, boss_deathbringer_saurfangAI, boss_blood_queen_lanathelAI, npc_blood_orb_controlAI, boss_tyrannusAI, boss_ickAI, boss_forgemaster_garfrostAI, boss_devourer_of_soulsAI, boss_bronjahmAI, boss_drakkari_elementalAI, boss_trollgoreAI, boss_tharonjaAI, boss_novosAI, boss_jaraxxusAI, trial_crusader_commonAI, boss_anubarak_trialAI, trial_companion_commonAI, boss_black_knightAI, argent_champion_commonAI, boss_anubarakAI, boss_volazjAI, boss_taldaramAI, boss_nadoxAI, boss_jedogaAI, boss_amanitarAI, npc_simone_seductressAI, npc_giltharesAI, boss_twin_emperorsAI, boss_skeramAI, boss_sarturaAI, boss_ouroAI, boss_huhuranAI, boss_fankrissAI, boss_cthunAI, boss_eye_of_cthunAI, boss_silithidRoyaltyAI, boss_onyxiaAI, npc_morokkAI, hyjalAI, boss_venoxisAI, boss_thekalAI, boss_marliAI, boss_jeklikAI, boss_arlokkAI, boss_nalorakkAI, boss_malacrassAI, boss_janalaiAI, boss_halazziAI, boss_akilzonAI, npc_tapoke_slim_jahnAI, npc_daphne_stilwellAI, npc_taelan_fordringAI, boss_archaedasAI, npc_sunblade_protectorAI, boss_brutallusAI, boss_headless_horsemanAI, npc_scarlet_courierAI, npc_death_knight_initiateAI, boss_sulfuronAI, boss_shazzrahAI, boss_majordomoAI, boss_magmadarAI, boss_lucifronAI, boss_golemaggAI, boss_gehennasAI, boss_garrAI, boss_baron_geddonAI, boss_vexallusAI, boss_selin_fireheartAI, npc_zelfanAI, npc_apokoAI, npc_garaxxasAI, npc_ellrys_duskhallowAI, boss_priestess_delrissaAI, boss_romuloAI, boss_julianneAI, boss_bigbadwolfAI, boss_croneAI, boss_roarAI, boss_tinheadAI, boss_strawmanAI, boss_dorotheeAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_moroesAI, boss_attumenAI, boss_midnightAI, boss_maiden_of_virtueAI, boss_curatorAI, npc_dawnblade_blood_knight, boss_thermapluggAI, boss_mr_smiteAI, boss_victor_nefariusAI, boss_vaelastraszAI, boss_razorgoreAI, boss_flamegorAI, boss_firemawAI, boss_ebonrocAI, boss_chromaggusAI, boss_broodlordAI, boss_pyroguard_emberseerAI, boss_moira_bronzebeardAI, boss_ambassador_flamelashAI, BossAI, and CreatureEventAI.
Definition at line 158 of file UnitAI.h.
Referenced by npc_dawnblade_blood_knight::JustReachedHome(), npc_ellrys_duskhallowAI::JustReachedHome(), npc_giltharesAI::JustReachedHome(), npc_bonechewer_brawler::JustReachedHome(), npc_bonechewer_combatant::JustReachedHome(), and Unit::TriggerHomeEvents().
JustRespawned()
virtual void UnitAI::JustRespawned () inline virtual
Called when creature is respawned (for reseting variables)
Reimplemented in SilithusBossAI, npc_shade_of_the_horsemanAI, GossipNPCAI, npc_imp_in_a_ball, mob_phoenix_tkAI, npc_fire_nova_totemAI, npc_shaman_elementalAI, npc_ethereum_prisonerAI, boss_highlord_kruulAI, npc_kayra_longmaneAI, npc_minion_of_terokkAI, npc_avatar_of_terokkAI, npc_skyguard_prisonerAI, NetherCharge, npc_nether_vaporAI, StunField, npc_spawned_oronok_tornheartAI, mob_shadowmoon_soulstealerAI, npc_shadowlord_deathwailAI, mob_torlothAI, mob_enslaved_netherwing_drakeAI, npc_scrapped_fel_reaverAI, npc_scrap_reaverAI, npc_salhadaarAI, npc_captured_vanguardAI, npc_rethhedronAI, npc_nagrand_captiveAI, npc_vindicator_sedaiAI, npc_living_flareAI, npc_wounded_blood_elfAI, boss_kelidan_the_breakerAI, mob_underbog_mushroomAI, npc_serpentshrine_parasiteAI, mob_water_globuleAI, npc_inner_demonAI, npc_caribdis_cyclone, boss_doomwalkerAI, boss_doomlordkazzakAI, npc_evergrove_druidAI, npc_soulgrinderAI, npc_frequency_scanner, npc_bird_spiritAI, npc_shadow_constructAI, npc_doom_blossomAI, boss_shade_of_akamaAI, npc_enslaved_soulAI, npc_parasitic_shadowfiendAI, npc_shadow_demonAI, npc_akama_illidanAI, boss_illidan_stormrageAI, npc_grand_collectorAI, npc_disruptor_towerAI, dummy_blackheart_the_inciterAI, boss_anzuAI, npc_ethereum_prisoner_dungeonAI, boss_yorAI, npc_decaying_ghoulAI, boss_kelesethAI, npc_brann_hosAI, boss_thaddiusAddsAI, npc_web_wrapAI, boss_forgemaster_garfrostAI, npc_corrupted_soul_fragmentAI, boss_bronjahmAI, npc_infantryAI, npc_nerubian_burrowerAI, npc_proudhoofAI, npc_nexus_drake_hatchlingAI, npc_disciple_of_naralexAI, boss_skeramAI, OuroScarab, npc_ouro_moundAI, boss_ouroAI, npc_ouro_triggerAI, npc_general_andorovAI, npc_smolderwing, npc_morokkAI, npc_magrami_spectre, npc_rabid_bearAI, npc_theryluneAI, npc_thrall_old_hillsbradAI, hyjalAI, boss_rage_winterchillAI, boss_kazrogalAI, boss_azgalorAI, boss_archimondeAI, boss_anetheronAI, npc_soulflayerAI, boss_renatakiAI, npc_zulian_prowlerAI, npc_feather_vortexAI, npc_corrupted_lightning_totemAI, mob_soaring_eagleAI, npc_singularityAI, npc_darknessAI, boss_kiljaedenAI, boss_felmystAI, npc_shadow_imageAI, mobs_spectral_ghostly_citizenAI, boss_apothecary_hummelAI, boss_high_inquisitor_whitemaneAI, boss_headless_horsemanAI, boss_majordomoAI, npc_kalecgosAI, mob_fel_crystalAI, boss_selin_fireheartAI, npc_ellrys_duskhallowAI, boss_terestianAI, boss_nightbaneAI, npc_dawnblade_blood_knight, npc_shattered_sun_fighterAI, npc_rinjiAI, npc_ranger_lilathaAI, npc_apprentice_mirvedaAI, boss_kazzakAI, boss_nefarianAI, ScriptedAI, CreatureEventAI, GuardianAI, boss_kaelthasAI, npc_regthar_deathgateAI, and npc_demonic_vaporAI.
Definition at line 260 of file UnitAI.h.
Referenced by CreatureEventAI::JustRespawned(), and Creature::Update().
JustRootedTarget()
virtual void UnitAI::JustRootedTarget (SpellEntry const * spellInfo, Unit * victim) inline virtual
Definition at line 474 of file UnitAI.h.
References JustStoppedMovementOfTarget().
JustStoppedMovementOfTarget()
void UnitAI::JustStoppedMovementOfTarget (SpellEntry const * spell, Unit * victim) virtual
Definition at line 1069 of file UnitAI.cpp.
References DistanceYourself(), Unit::GetVictim(), SpellEntry::Id, m_distanceSpells, and m_unit.
Referenced by JustRootedTarget(), and JustStunnedTarget().
JustStunnedTarget()
virtual void UnitAI::JustStunnedTarget (SpellEntry const * spellInfo, Unit * victim) inline virtual
Definition at line 475 of file UnitAI.h.
References JustStoppedMovementOfTarget().
JustSummoned() [1/2]
virtual void UnitAI::JustSummoned (Creature *) inline virtual
Called when the creature summon successfully other creature.
Parameters
pSummoned Creature that got summoned
Reimplemented in mob_phoenix_tkAI, boss_emerald_dragonAI, boss_kaelthasAI, boss_alarAI, boss_warp_splinterAI, boss_soccothratesAI, StunField, npc_totem_of_spiritsAI, npc_lord_illidan_stormrageAI, npc_adyen_the_lightwardenAI, npc_scrapped_fel_reaverAI, boss_omor_the_unscarredAI, boss_vazruden_heraldAI, boss_broggokAI, boss_mekgineer_steamriggerAI, boss_ahuneAI, boss_the_lurker_belowAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_fathomguard_caribdisAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, boss_fathomlord_karathressAI, boss_terokkAI, boss_doomwalkerAI, npc_soulgrinderAI, boss_veras_darkshadowAI, npc_doom_blossomAI, boss_teron_gorefiendAI, boss_supremusAI, npc_creature_generatorAI, npc_akamaAI, npc_blade_of_azzinothAI, npc_flame_of_azzinothAI, npc_akama_illidanAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_grand_collectorAI, npc_disruptor_towerAI, boss_anzuAI, boss_nexusprince_shaffarAI, boss_xevozzAI, boss_ichoronAI, npc_ethereal_frostworgAI, boss_nothAI, boss_maexxnaAI, boss_loathebAI, boss_kelthuzadAI, boss_grobbulusAI, boss_gothikAI, boss_anubrekhanAI, boss_deathbringer_saurfangAI, boss_rimefang_posAI, boss_krickAI, boss_sladranAI, boss_galdarahAI, boss_drakkari_colossusAI, npc_kanatiAI, boss_viscidusAI, boss_skeramAI, npc_ouro_moundAI, npc_ouro_spawnerAI, boss_ouroAI, boss_fankrissAI, boss_cthunAI, boss_eye_of_cthunAI, boss_yaujAI, npc_oox17tnAI, boss_ossirianAI, boss_moamAI, npc_buru_eggAI, boss_ayamissAI, boss_eranikusAI, npc_keeper_remulosAI, npc_clintar_dw_spiritAI, npc_oox22feAI, boss_archimondeAI, boss_anetheronAI, boss_mandokirAI, boss_jeklikAI, npc_amanishi_tempestAI, boss_zuljinAI, boss_janalaiAI, boss_halazziAI, boss_akilzonAI, npc_daphne_stilwellAI, npc_taelan_fordringAI, npc_darknessAI, npc_portal_targetAI, boss_entropiusAI, boss_muruAI, boss_kiljaedenAI, boss_sathrovarrAI, npc_demonic_vaporAI, boss_sacrolashAI, boss_brutallusAI, npc_squire_roweAI, boss_ragnarosAI, boss_majordomoAI, boss_vexallusAI, npc_zelfanAI, npc_apokoAI, npc_ellrys_duskhallowAI, boss_felblood_kaelthasAI, npc_fiendish_portalAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_nightbaneAI, boss_netherspiteAI, boss_attumenAI, boss_midnightAI, boss_curatorAI, boss_vaelastraszAI, boss_nefarianAI, boss_coren_direbrewAI, CreatureEventAI, npc_xiri, boss_highlord_kruulAI, npc_fhwoorAI, npc_skyguard_prisonerAI, npc_skywingAI, npc_letollAI, npc_akunoAI, boss_pathaleon_the_calculatorAI, boss_high_astromancer_solarianAI, boss_lajAI, boss_high_botanist_freywinnAI, boss_harbinger_skyrissAI, npc_warden_mellicharAI, npc_dragonmaw_racerAI, npc_spawned_oronok_tornheartAI, npc_wildaAI, npc_salhadaarAI, npc_dimensiusAI, npc_drijyaAI, npc_protectorate_demolitionistAI, npc_commander_dawnforgeAI, npc_manaforge_control_consoleAI, npc_nagrand_captiveAI, npc_credit_marker_they_must_burnAI, npc_colonel_julesAI, npc_wounded_blood_elfAI, npc_demoniac_scryerAI, boss_warchief_kargath_bladefistAI, boss_warbringer_omroggAI, npc_frozen_coreAI, npc_warp_gate, npc_vimgol_middle_bunnyAI, boss_grandmaster_vorpilAI, boss_darkweaver_sythAI, npc_shaheenAI, boss_exarch_maladaarAI, npc_teleportation_portalAI, npc_prison_event_controllerAI, boss_ymironAI, boss_svalaAI, boss_ingvarAI, npc_storm_tempered_keeperAI, npc_ominous_cloudAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, boss_saraAI, boss_heart_deconstructorAI, boss_thorimAI, npc_razorscale_spawnerAI, boss_razorscaleAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_mimironAI, npc_rubble_stalkerAI, boss_kologarnAI, boss_ignisAI, boss_hodirAI, boss_general_vezaxAI, boss_freyaAI, npc_freya_wardAI, npc_hodir_fury_reticleAI, boss_flame_leviathanAI, boss_feral_defenderAI, boss_auriayaAI, npc_worm_holeAI, boss_algalonAI, boss_molgeimAI, boss_brundirAI, boss_volkhanAI, boss_ionarAI, npc_meteor_strike_initialAI, boss_halion_realAI, npc_fire_cycloneAI, mob_twilight_eggsAI, mob_vesperonAI, mob_shadronAI, mob_tenebronAI, boss_eregosAI, boss_telestraAI, boss_ormorokAI, boss_anomalusAI, boss_malygosAI, npc_putricides_trapAI, mob_big_oozeAI, mob_little_oozeAI, boss_rotfaceAI, boss_professor_putricideAI, boss_lord_marrowgarAI, boss_lady_deathwhisperAI, boss_festergutAI, boss_taldaram_iccAI, boss_keleseth_iccAI, boss_valanar_iccAI, boss_lich_king_horAI, boss_devourer_of_soulsAI, npc_grand_admiral_westwindAI, npc_squad_leaderAI, npc_emilyAI, npc_harrison_jonesAI, boss_trollgoreAI, npc_crystal_channel_targetAI, boss_novosAI, npc_destructive_wardAI, boss_fjolaAI, boss_icehowlAI, twin_jormungars_commonAI, boss_gormokAI, npc_beast_combat_stalkerAI, boss_jaraxxusAI, boss_anubarak_trialAI, boss_black_knightAI, boss_paletressAI, npc_proudhoofAI, npc_sinkhole_kill_creditAI, boss_krikthirAI, boss_volazjAI, boss_taldaramAI, mob_ahnkahar_eggAI, boss_jedogaAI, boss_amanitarAI, boss_zumrahAI, npc_lakota_windsongAI, npc_wizzlecranks_shredderAI, npc_twiggy_flatheadAI, npc_kayaAI, npc_solenorAI, npc_anachronos_the_ancientAI, mob_anubisath_guardianAI, npc_willix_the_importerAI, npc_belnistraszAI, boss_onyxiaAI, boss_noxxionAI, npc_areiAI, npc_ogronAI, mobs_risen_husk_spiritAI, npc_warlock_mount_ritualAI, npc_volcorAI, npc_tarethaAI, npc_thrall_old_hillsbradAI, npc_time_riftAI, npc_arthasAI, npc_feero_ironhandAI, npc_torekAI, npc_muglashAI, example_escortAI, npc_tapoke_slim_jahnAI, npc_anchorite_truuenAI, npc_lady_sylvanas_windrunnerAI, boss_cannon_master_willeyAI, npc_deathstalker_faerleiaAI, boss_jandicebarovAI, boss_headless_horsemanAI, npc_highlord_darion_mograineAI, npc_miranAI, npc_image_of_medivhAI, npc_barnesAI, npc_echo_of_medivhAI, boss_julianneAI, boss_croneAI, boss_dorotheeAI, npc_rinjiAI, npc_00x09hlAI, npc_blastmaster_emi_shortfuseAI, boss_thermapluggAI, npc_infused_crystalAI, npc_apprentice_mirvedaAI, npc_eris_havenfireAI, npc_grark_lorkrubAI, boss_overlordwyrmthalakAI, boss_gythAI, boss_general_angerforgeAI, boss_ambassador_flamelashAI, npc_grimstoneAI, npc_professor_phizzlethorpeAI, boss_baltharusAI, boss_uromAI, npc_frequency_scanner, npc_thrallAI, npc_disciple_of_naralexAI, npc_prospector_remtravelAI, and npc_rizzle_sprysprocketAI.
Definition at line 222 of file UnitAI.h.
Referenced by Spell::DoSummonPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTransmitted(), and Totem::Summon().
JustSummoned() [2/2]
virtual void UnitAI::JustSummoned (GameObject *) inline virtual
Called when the creature summon successfully a gameobject.
Parameters
pGo GameObject that was summoned
Reimplemented in npc_garaxxasAI, npc_ice_spear_bunnyAI, npc_warp_gate, npc_razorscale_spawnerAI, npc_nature_bombAI, npc_sinkhole_kill_creditAI, boss_kurinnaxxAI, npc_frequency_scanner, boss_ouroAI, and boss_coren_direbrewAI.
Definition at line 228 of file UnitAI.h.
KilledUnit()
virtual void UnitAI::KilledUnit (Unit *) inline virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented in boss_xevozzAI, boss_ichoronAI, boss_void_reaverAI, boss_high_astromancer_solarianAI, boss_thorngrinAI, npc_scrap_reaverAI, boss_magtheridonAI, boss_leotheras_the_blindAI, boss_maievAI, boss_svalaAI, boss_skadiAI, boss_kelesethAI, boss_ingvarAI, boss_sjonnirAI, boss_zarithrianAI, boss_baltharusAI, boss_eregosAI, boss_telestraAI, boss_ormorokAI, boss_keristraszaAI, boss_anomalusAI, boss_kelthuzadAI, boss_gluthAI, boss_anubrekhanAI, boss_lady_deathwhisperAI, boss_deathbringer_saurfangAI, boss_forgemaster_garfrostAI, boss_bronjahmAI, boss_krikthirAI, boss_hadronoxAI, boss_buruAI, boss_eranikusAI, boss_azuregosAI, boss_mandokirAI, boss_spirit_lynxAI, boss_arugalAI, priestess_companion_commonAI, boss_priestess_delrissaAI, boss_nefarianAI, CreatureEventAI, boss_tyrannusAI, boss_krickAI, boss_ickAI, boss_the_lich_king_iccAI, boss_emerissAI, boss_emerald_dragonAI, boss_highlord_kruulAI, boss_mechano_lord_capacitusAI, boss_harbinger_skyrissAI, boss_warchief_kargath_bladefistAI, boss_doomwalkerAI, boss_doomlordkazzakAI, boss_yogg_saronAI, boss_saraAI, boss_xt_002AI, boss_thorimAI, npc_rocket_strikeAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_kologarnAI, boss_ignisAI, boss_hodirAI, boss_freyaAI, boss_algalonAI, boss_savianaAI, boss_halion_twilightAI, boss_halion_realAI, boss_valithria_dreamwalkerAI, boss_rotfaceAI, npc_bone_spikeAI, boss_lord_marrowgarAI, boss_taldaram_iccAI, boss_keleseth_iccAI, boss_valanar_iccAI, boss_devourer_of_soulsAI, boss_trollgoreAI, boss_eydisAI, boss_fjolaAI, boss_jaraxxusAI, trial_crusader_commonAI, boss_anubarak_trialAI, boss_tethyrAI, mob_ohganAI, boss_headless_horsemanAI, boss_romuloAI, boss_julianneAI, boss_kazzakAI, boss_vaelastraszAI, boss_pathaleon_the_calculatorAI, boss_nethermancer_sepethreaAI, boss_kaelthasAI, boss_warp_splinterAI, boss_high_botanist_freywinnAI, boss_soccothratesAI, boss_dalliahAI, npc_millhouse_manastormAI, npc_wounded_blood_elfAI, boss_warbringer_omroggAI, boss_grand_warlock_nethekurseAI, boss_watchkeeper_gargolmarAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_the_makerAI, boss_kelidan_the_breakerAI, boss_swamplord_muselekAI, boss_warlord_kalithreshAI, boss_mekgineer_steamriggerAI, boss_thespiaAI, boss_morogrim_tidewalkerAI, boss_lady_vashjAI, boss_hydross_the_unstableAI, boss_fathomlord_karathressAI, boss_grandmaster_vorpilAI, boss_ambassador_hellmawAI, boss_talon_king_ikissAI, boss_darkweaver_sythAI, boss_pandemoniusAI, boss_nexusprince_shaffarAI, boss_exarch_maladaarAI, boss_ymironAI, boss_general_vezaxAI, boss_flame_leviathanAI, boss_auriayaAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, npc_brann_hosAI, boss_volkhanAI, boss_lokenAI, boss_ionarAI, boss_bjarngrimAI, mob_vesperonAI, mob_shadronAI, mob_tenebronAI, boss_sartharionAI, boss_varosAI, boss_uromAI, boss_malygosAI, boss_sindragosaAI, boss_professor_putricideAI, boss_festergutAI, boss_blood_queen_lanathelAI, boss_moorabiAI, boss_tharonjaAI, boss_novosAI, boss_black_knightAI, boss_paletressAI, boss_eadricAI, boss_anubarakAI, boss_volazjAI, boss_taldaramAI, boss_nadoxAI, boss_jedogaAI, boss_zumrahAI, boss_veknilashAI, boss_onyxiaAI, npc_thrall_old_hillsbradAI, boss_chrono_lord_dejaAI, boss_aeonusAI, npc_arthasAI, boss_archaedasAI, boss_high_inquisitor_whitemaneAI, boss_scarlet_commander_mograineAI, boss_herodAI, boss_selin_fireheartAI, boss_roarAI, boss_tinheadAI, boss_strawmanAI, boss_aranAI, boss_midnightAI, boss_thermapluggAI, boss_emperor_dagran_thaurissanAI, ScriptedPetAI, and CombatAI.
Definition at line 210 of file UnitAI.h.
MoveInLineOfSight()
void UnitAI::MoveInLineOfSight (Unit * who) virtual
== Reactions At =================================
Called if IsVisible(Unit* pWho) is true at each (relative) override pWho move, reaction at visibility zone enter Note: The Unit* pWho can be out of Line of Sight, usually this is only visibiliy (by state) and range dependendend Note: This function is not called for creatures who are in evade mode
Parameters
pWho Unit* who moved in the visibility range and is visisble
Reimplemented in ChildTbcAI, boss_kaelthasAI, boss_watchkeeper_gargolmarAI, mob_water_globuleAI, npc_evergrove_druidAI, npc_reliquary_LOS_aggro_triggerAI, boss_reliquary_of_soulsAI, npc_cage_trap_triggerAI, boss_nexusprince_shaffarAI, npc_ethereal_sphereAI, boss_ichoronAI, npc_ingvar_throw_dummyAI, npc_living_poisonAI, boss_kelthuzadAI, boss_faerlinaAI, boss_anubrekhanAI, boss_rimefang_posAI, npc_dalaran_guardian_mageAI, boss_veklorAI, boss_veknilashAI, npc_general_andorovAI, boss_ossirianAI, npc_hive_zara_larvaAI, boss_temporusAI, npc_eagle_trash_aggro_triggerAI, npc_ashliAI, npc_harkorAI, npc_amanishi_lookoutAI, boss_nalorakkAI, npc_taelan_fordringAI, npc_the_scourge_cauldronAI, DarkFiendAI, npc_a_special_surpriseAI, boss_felblood_kaelthasAI, boss_aranAI, CreatureEventAI, TotemAI, PetAI, GuardAI, PallidHorrorAI, ScourgeMinion, npc_spring_rabbitAI, npc_air_force_botsAI, npc_spirit_shadeAI, boss_soccothratesAI, npc_khadgars_servantAI, npc_veneratus_spawn_nodeAI, npc_protectorate_demolitionistAI, npc_creditmarker_visit_with_ancestorsAI, npc_Shattered_Hand_Scout, mob_fel_orc_convertAI, boss_grand_warlock_nethekurseAI, boss_warlord_kalithreshAI, mob_steamrigger_mechanicAI, mob_enchanted_elementalAI, npc_spawn_of_hydrossAI, npc_supplicantAI, npc_light_orb_collectorAI, npc_bloodmaul_stout_triggerAI, npc_daranelleAI, mobs_nether_drakeAI, npc_void_travelerAI, boss_grandmaster_vorpilAI, boss_talon_king_ikissAI, boss_exarch_maladaarAI, boss_skadiAI, mob_vrykul_skeletonAI, npc_charged_sphereAI, npc_death_rayAI, npc_ominous_cloudAI, boss_saraAI, npc_scrapbotAI, npc_runic_colossusAI, boss_thorimAI, npc_expedition_commanderAI, boss_mimironAI, boss_freyaAI, npc_black_holeAI, boss_baltharusAI, npc_planar_anomalyAI, npc_power_sparkAI, npc_gas_cloud_iccAI, npc_volatile_ooze_iccAI, npc_ball_of_flameAI, npc_queen_lanathel_introAI, npc_jaina_sylvanas_horAI, boss_lich_king_horAI, npc_corrupted_soul_fragmentAI, npc_firecrackers_bunnyAI, npc_king_ymironAI, npc_lich_king_villageAI, boss_novosAI, boss_icehowlAI, boss_dreadscaleAI, boss_gormokAI, trial_crusader_commonAI, boss_anubarak_trialAI, trial_companion_commonAI, boss_black_knightAI, npc_orphaned_mammoth_calfAI, npc_jennyAI, npc_nexus_drake_hatchlingAI, npc_nesingwary_trapperAI, boss_krikthirAI, boss_anubarakAI, boss_jedogaAI, boss_zumrahAI, npc_ringoAI, npc_mistAI, npc_toogaAI, npc_custodian_of_timeAI, npc_shay_leafrunnerAI, npc_kittenAI, npc_ogronAI, npc_aged_dying_ancient_kodoAI, npc_rabid_bearAI, npc_volcorAI, npc_threshwackonatorAI, npc_kerlonianAI, boss_chrono_lord_dejaAI, boss_aeonusAI, npc_draenei_survivorAI, boss_headless_horsemanAI, npc_blastmaster_emi_shortfuseAI, npc_grark_lorkrubAI, boss_ambassador_flamelashAI, npc_depth_chargeAI, npc_rizzle_sprysprocketAI, npc_ranger_lilathaAI, mob_netherweb_victimAI, npc_saplingAI, npc_void_conduitAI, npc_ancestral_wolfAI, mob_underbog_mushroomAI, mob_naga_distillerAI, npc_ice_spear_bunnyAI, npc_frozen_coreAI, npc_fel_cannon, npc_simon_game_bunnyAI, mob_illidari_councilAI, npc_blade_of_azzinothAI, npc_keeper_thorimAI, npc_keeper_mimironAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, npc_xt_toy_pileAI, boss_heart_deconstructorAI, npc_thunder_orbAI, boss_sifAI, npc_harpoon_fire_stateAI, npc_computerAI, boss_leviathan_mk2_turretAI, npc_rocket_strikeAI, npc_frost_bombAI, npc_mimiron_flamesAI, npc_bot_triggerAI, npc_proximity_mineAI, npc_rubble_stalkerAI, npc_focused_eyebeamAI, npc_scorchAI, npc_icicle_targetAI, npc_flash_freezeAI, npc_saronite_vaporAI, npc_healthy_sporeAI, npc_iron_rootsAI, npc_eonars_giftAI, npc_mimiron_infernoAI, npc_freya_wardAI, npc_hodir_furyAI, npc_hodir_fury_reticleAI, npc_collapsing_starAI, npc_worm_holeAI, npc_living_constellationAI, npc_tesla_coilAI, npc_web_wrapAI, npc_putricides_trapAI, npc_puddle_stalkerAI, npc_choking_gas_bombAI, npc_growing_ooze_puddleAI, npc_orange_gas_stalkerAI, npc_kinetic_bombAI, npc_crystal_channel_targetAI, npc_champion_mountAI, npc_black_knight_gryphonAI, npc_seaforium_depth_chargeAI, mob_ahnkahar_eggAI, npc_twilight_volunteerAI, npc_amanitar_mushroomAI, mob_webbed_creatureAI, npc_tirion_fordringAI, npc_isillienAI, boss_head_of_horsemanAI, npc_image_arcanagosAI, npc_image_of_medivhAI, npc_chess_piece_genericAI, npc_echo_of_medivhAI, npc_converted_sentryAI, and NullCreatureAI.
Definition at line 69 of file UnitAI.cpp.
References AssistPlayerInCombat(), Unit::CanAttackOnSight(), Unit::CanFly(), Unit::CanInitiateAttack(), CheckForHelp(), CONFIG_FLOAT_CREATURE_CHECK_FOR_HELP_RADIUS, CREATURE_Z_ATTACK_RANGE_MELEE, CREATURE_Z_ATTACK_RANGE_RANGED, DetectOrAttack(), WorldObject::GetDistanceZ(), WorldObject::GetMap(), Object::GetObjectGuid(), GetReactState(), Unit::GetVictim(), HasReactState(), ObjectGuid::IsCreature(), Map::IsDungeon(), Unit::IsFlying(), Unit::isInAccessablePlaceFor(), Unit::IsInCombat(), Unit::IsNeutralToAll(), IsRangedUnit(), m_unit, REACT_AGGRESSIVE, REACT_DEFENSIVE, and sWorld.
Referenced by CreatureVisitCreatureWorker(), npc_ranger_lilathaAI::MoveInLineOfSight(), npc_rizzle_sprysprocketAI::MoveInLineOfSight(), boss_ambassador_flamelashAI::MoveInLineOfSight(), npc_grark_lorkrubAI::MoveInLineOfSight(), npc_blastmaster_emi_shortfuseAI::MoveInLineOfSight(), boss_headless_horsemanAI::MoveInLineOfSight(), boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_dejaAI::MoveInLineOfSight(), npc_kerlonianAI::MoveInLineOfSight(), npc_threshwackonatorAI::MoveInLineOfSight(), npc_volcorAI::MoveInLineOfSight(), npc_rabid_bearAI::MoveInLineOfSight(), npc_ogronAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_toogaAI::MoveInLineOfSight(), npc_mistAI::MoveInLineOfSight(), npc_ringoAI::MoveInLineOfSight(), boss_zumrahAI::MoveInLineOfSight(), boss_jedogaAI::MoveInLineOfSight(), boss_anubarakAI::MoveInLineOfSight(), npc_nesingwary_trapperAI::MoveInLineOfSight(), npc_nexus_drake_hatchlingAI::MoveInLineOfSight(), npc_orphaned_mammoth_calfAI::MoveInLineOfSight(), boss_black_knightAI::MoveInLineOfSight(), trial_companion_commonAI::MoveInLineOfSight(), boss_anubarak_trialAI::MoveInLineOfSight(), trial_crusader_commonAI::MoveInLineOfSight(), boss_gormokAI::MoveInLineOfSight(), boss_dreadscaleAI::MoveInLineOfSight(), boss_icehowlAI::MoveInLineOfSight(), boss_novosAI::MoveInLineOfSight(), boss_lich_king_horAI::MoveInLineOfSight(), npc_jaina_sylvanas_horAI::MoveInLineOfSight(), npc_volatile_ooze_iccAI::MoveInLineOfSight(), npc_gas_cloud_iccAI::MoveInLineOfSight(), boss_baltharusAI::MoveInLineOfSight(), boss_freyaAI::MoveInLineOfSight(), npc_expedition_commanderAI::MoveInLineOfSight(), boss_thorimAI::MoveInLineOfSight(), npc_runic_colossusAI::MoveInLineOfSight(), boss_saraAI::MoveInLineOfSight(), mob_vrykul_skeletonAI::MoveInLineOfSight(), boss_skadiAI::MoveInLineOfSight(), boss_exarch_maladaarAI::MoveInLineOfSight(), boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpilAI::MoveInLineOfSight(), mobs_nether_drakeAI::MoveInLineOfSight(), npc_daranelleAI::MoveInLineOfSight(), npc_spawn_of_hydrossAI::MoveInLineOfSight(), boss_warlord_kalithreshAI::MoveInLineOfSight(), boss_grand_warlock_nethekurseAI::MoveInLineOfSight(), boss_soccothratesAI::MoveInLineOfSight(), npc_spring_rabbitAI::MoveInLineOfSight(), ScourgeMinion::MoveInLineOfSight(), PallidHorrorAI::MoveInLineOfSight(), CreatureEventAI::MoveInLineOfSight(), boss_aranAI::MoveInLineOfSight(), boss_felblood_kaelthasAI::MoveInLineOfSight(), npc_taelan_fordringAI::MoveInLineOfSight(), boss_nalorakkAI::MoveInLineOfSight(), npc_amanishi_lookoutAI::MoveInLineOfSight(), npc_harkorAI::MoveInLineOfSight(), npc_ashliAI::MoveInLineOfSight(), boss_temporusAI::MoveInLineOfSight(), npc_hive_zara_larvaAI::MoveInLineOfSight(), boss_ossirianAI::MoveInLineOfSight(), npc_general_andorovAI::MoveInLineOfSight(), boss_veknilashAI::MoveInLineOfSight(), boss_veklorAI::MoveInLineOfSight(), boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlinaAI::MoveInLineOfSight(), boss_kelthuzadAI::MoveInLineOfSight(), boss_ichoronAI::MoveInLineOfSight(), npc_ethereal_sphereAI::MoveInLineOfSight(), boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), PlayerVisitCreatureWorker(), PlayerVisitPlayerWorker(), and UnitVisitObjectsNotifierWorker().
MovementInform()
virtual void UnitAI::MovementInform (uint32 , uint32) inline virtual
Called at waypoint reached or point movement finished.
Parameters
uiMovementType Type of the movement (enum MovementGeneratorType)
uiData Data related to the finished movement (ie point-id)
Reimplemented in npc_vimgol_AI, npc_living_flareAI, npc_bird_spiritAI, npc_dragonmaw_racer_skyshatterAI, npc_dragonmaw_racer_mulverickAI, npc_dragonmaw_racer_ichmanAI, npc_krunAI, npc_vindicator_sedaiAI, npc_apexis_flayerAI, npc_hungry_nether_rayAI, npc_dragonmaw_peonAI, npc_anchorite_baradaAI, npc_colonel_julesAI, boss_lady_vashjAI, npc_graufAI, npc_saronite_vaporAI, npc_brann_hosAI, mob_spark_of_ionarAI, npc_flame_tsunamiAI, dummy_dragonAI, boss_lord_marrowgarAI, boss_lich_king_horAI, npc_grand_admiral_westwindAI, npc_barrett_ramseyAI, boss_icehowlAI, npc_oil_stained_wolfAI, npc_nesingwary_trapperAI, npc_anachronos_the_ancientAI, npc_general_andorovAI, npc_kyle_the_frenziedAI, npc_arthasAI, boss_headless_horsemanAI, npc_scarlet_courierAI, npc_eye_of_acherusAI, boss_warlord_kalithreshAI, npc_sunblade_scoutAI, npc_cenarion_sparrowhawkAI, boss_soccothratesAI, boss_dalliahAI, npc_domesticated_felboarAI, mob_enslaved_netherwing_drakeAI, mob_mature_netherwing_drakeAI, npc_rethhedronAI, npc_fel_guard_houndAI, mobs_nether_drakeAI, npc_decaying_ghoulAI, boss_leviathan_mk2AI, npc_hodir_fury_reticleAI, boss_flame_leviathanAI, boss_algalonAI, boss_brundirAI, npc_dark_matterAI, boss_volkhanAI, boss_savianaAI, boss_malygosAI, npc_kinetic_bombAI, npc_queen_lanathel_introAI, npc_scourged_flamespitterAI, boss_hadronoxAI, boss_taldaramAI, boss_jedogaAI, npc_snufflenose_gopherAI, boss_onyxiaAI, npc_felhound_trackerAI, boss_jeklikAI, npc_rookery_hatcherAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_blood_queen_lanathelAI, boss_jaraxxusAI, npc_magrami_spectre, npc_spring_rabbitAI, npc_Shattered_Hand_Scout, npc_deadsoul_orb, npc_spirit_prisoner_of_bladespire, boss_the_lich_king_iccAI, boss_professor_putricideAI, boss_mr_smiteAI, boss_ymironAI, npc_annhyldeAI, boss_thorimAI, npc_concentrated_bulletAI, npc_champion_mountAI, trial_companion_commonAI, npc_toogaAI, boss_tethyrAI, npc_lazy_peonAI, boss_high_inquisitor_whitemaneAI, npc_scarlet_ghoulAI, npc_chess_piece_genericAI, npc_highlord_darion_mograineAI, boss_sapphironAI, npc_living_mojoAI, boss_eranikusAI, npc_amanishi_hatcherAI, mob_soaring_eagleAI, npc_kalecgosAI, boss_nefarianAI, npc_dragonmaw_racer_corlokAI, npc_dragonmaw_racer_tropeAI, npc_dragonmaw_racer_muckjawAI, boss_shade_of_akamaAI, npc_akama_illidanAI, boss_illidan_stormrageAI, ArgentStandUnit, npc_corrupted_furbolgAI, boss_mandokirAI, npc_tirion_fordringAI, boss_selin_fireheartAI, npc_escortAI, npc_ethereal_frostworgAI, npc_smolderwing, npc_shadow_demonAI, GargoyleDeathKnightAI, mob_bt_battle_fighterAI, npc_commanderAI, npc_disobedient_dragonmaw_peonAI, npc_adyen_the_lightwardenAI, boss_doomwalkerAI, npc_skyguard_rangerAI, npc_skyguard_aether_techAI, boss_archimondeAI, npc_forest_frogAI, npc_razorthorn_ravager_pet, NetherCharge, npc_doom_blossomAI, boss_kaelthasAI, boss_alarAI, npc_spawned_oronok_tornheartAI, npc_shadowlord_deathwailAI, boss_vazruden_heraldAI, boss_broggokAI, npc_akamaAI, npc_aether_tech_vendorAI, boss_sir_zeliekAI, boss_thane_korthazzAI, boss_rivendare_naxxAI, boss_lady_blaumeuxAI, boss_forgemaster_garfrostAI, boss_ayamissAI, npc_amanishi_scoutAI, npc_ashliAI, npc_krazAI, npc_tanzarAI, npc_harkorAI, npc_amanishi_lookoutAI, boss_zuljinAI, boss_nalorakkAI, npc_core_of_entropiusAI, boss_kalecgosAI, boss_felmystAI, boss_nightbaneAI, boss_midnightAI, FollowerAI, boss_silithidRoyaltyAI, npc_shade_of_the_horsemanAI, guard_hallows_end_helperAI, ChildTbcAI, npc_shartuulAI, npc_shattered_hands_zealotAI, mob_ashtongue_sorcererAI, and npc_bashir_flesh_fiendAI.
Definition at line 267 of file UnitAI.h.
Referenced by WaypointMovementGenerator< Creature >::InformAI().
OnCallForHelp()
virtual void UnitAI::OnCallForHelp (Unit *) inline virtual
Reimplemented in CreatureAI.
Definition at line 420 of file UnitAI.h.
Referenced by MaNGOS::CallOfHelpCreatureInRangeDo::operator()().
OnChannelStateChange()
void UnitAI::OnChannelStateChange (Spell const * spell, bool state, WorldObject * target = nullptr) virtual
Definition at line 439 of file UnitAI.cpp.
References AURA_INTERRUPT_FLAG_TURNING, SpellEntry::ChannelInterruptFlags, EFFECT_INDEX_0, SpellEntry::EffectImplicitTargetA, WorldObject::GetAngle(), WorldObject::GetOrientation(), Unit::GetVictim(), SpellEntry::HasAttribute(), SpellEntry::Id, IsTargetingRestricted(), m_currentSpell, Spell::m_spellInfo, m_unit, Unit::SetFacingTo(), WorldObject::SetOrientation(), Unit::SetTarget(), SPELL_ATTR_EX4_ALLOW_CAST_WHILE_CASTING, SPELL_ATTR_EX_TRACK_TARGET_IN_CHANNEL, TARGET_UNIT, TARGET_UNIT_ENEMY, and TARGET_UNIT_SCRIPT_NEAR_CASTER.
Referenced by Spell::SendChannelStart(), and Spell::SendChannelUpdate().
OnEventHappened()
virtual void UnitAI::OnEventHappened (uint16 , bool , bool) inline virtual
Called when a Game Event starts or ends.
Parameters
eventId to specify id of event from database
activate to specify if it started or stopped
resume to specify whether it launched normally or was resumed after a restart
Definition at line 380 of file UnitAI.h.
Referenced by Creature::OnEventHappened().
OnHeartbeat()
virtual void UnitAI::OnHeartbeat () inline virtual
Definition at line 415 of file UnitAI.h.
Referenced by Unit::Heartbeat().
OnLeash()
virtual void UnitAI::OnLeash () inline virtual
Reimplemented in boss_warchief_kargath_bladefistAI, and boss_broodlordAI.
Definition at line 410 of file UnitAI.h.
OnSpellCast()
virtual void UnitAI::OnSpellCast (SpellEntry const * , Unit *) inline virtual
Reimplemented in boss_nothAI, boss_maexxnaAI, boss_kelthuzadAI, boss_moorabiAI, boss_arlokkAI, CreatureEventAI, boss_jeklikAI, boss_sir_zeliekAI, and boss_lady_blaumeuxAI.
Definition at line 400 of file UnitAI.h.
Referenced by UpdateSpellLists().
OnSpellCastStateChange()
void UnitAI::OnSpellCastStateChange (Spell const * spell, bool state, WorldObject * target = nullptr) virtual
Definition at line 355 of file UnitAI.cpp.
References AURA_INTERRUPT_FLAG_MOVING, SpellEntry::ChannelInterruptFlags, EFFECT_INDEX_0, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, WorldObject::GetAngle(), Spell::GetCastTime(), WorldObject::GetOrientation(), Unit::GetVictim(), HandleDelayedInstantAnimation(), SpellEntry::HasAttribute(), Unit::HasTarget(), SpellEntry::Id, SpellEntry::InterruptFlags, Unit::InterruptMoving(), IsChanneledSpell(), IsTargetingRestricted(), m_currentSpell, Spell::m_spellInfo, m_unit, MAX_EFFECT_INDEX, Unit::SetFacingTo(), WorldObject::SetOrientation(), Unit::SetTarget(), SPELL_ATTR_EX4_ALLOW_CAST_WHILE_CASTING, SPELL_ATTR_EX5_AI_DOESNT_FACE_TARGET, SPELL_ATTR_ON_NEXT_SWING, SPELL_ATTR_ON_NEXT_SWING_NO_DAMAGE, SPELL_INTERRUPT_FLAG_MOVEMENT, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_24, TARGET_LOCATION_CASTER_DEST, TARGET_LOCATION_CASTER_SRC, TARGET_UNIT_ENEMY, TARGET_UNIT_FRIEND, and TARGET_UNIT_SCRIPT_NEAR_CASTER.
Referenced by Spell::finish(), and Spell::Prepare().
OnSpellCooldownAdded()
void UnitAI::OnSpellCooldownAdded (SpellEntry const * spellInfo) virtual
Reimplemented in mob_phoenix_tkAI, boss_lady_malandeAI, boss_teron_gorefiendAI, boss_thaddiusAI, boss_azgalorAI, boss_archimondeAI, boss_anetheronAI, boss_felmystAI, npc_nether_rayAI, boss_omor_the_unscarredAI, and boss_temporusAI.
Definition at line 977 of file UnitAI.cpp.
References SpellEntry::Id, m_mainSpells, m_rangedModeSetting, SetCurrentRangedMode(), and TYPE_FULL_CASTER.
Referenced by Spell::cast(), boss_omor_the_unscarredAI::OnSpellCooldownAdded(), and boss_archimondeAI::OnSpellCooldownAdded().
OnSpellInterrupt()
void UnitAI::OnSpellInterrupt (SpellEntry const * spellInfo) virtual
Reimplemented in boss_kaelthasAI, boss_lady_malandeAI, and boss_essence_of_desireAI.
Definition at line 1077 of file UnitAI.cpp.
References SpellEntry::Id, IsMainSpellPrevented(), SQLStorage::LookupEntry(), m_mainSpells, m_rangedMode, m_rangedModeSetting, SetCurrentRangedMode(), sSpellTemplate, and TYPE_NO_MELEE_MODE.
Referenced by Unit::InterruptSpell().
OnStealthAlert()
virtual void UnitAI::OnStealthAlert (Unit * who) inline virtual
Reimplemented in npc_foreman_silixizAI, npc_venture_co_lookoutAI, npc_gallywixAI, and npc_foreman_klaven_mortwakeAI.
Definition at line 405 of file UnitAI.h.
Referenced by DetectOrAttack().
OnTaunt()
virtual void UnitAI::OnTaunt () inline virtual
Reimplemented in CombatAI.
Definition at line 496 of file UnitAI.h.
Referenced by Aura::HandleModTaunt().
OnUnsummon()
virtual void UnitAI::OnUnsummon () inline virtual
Reimplemented in SentryTotemAI, PetAI, and GuardianAI.
Definition at line 425 of file UnitAI.h.
Referenced by GuardianAI::OnUnsummon(), PetAI::OnUnsummon(), SentryTotemAI::OnUnsummon(), Totem::UnSummon(), and Pet::Unsummon().
OwnerKilledUnit()
virtual void UnitAI::OwnerKilledUnit (Unit *) inline virtual
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
Parameters
pVictim Victim that got killed (by owner of creature)
Reimplemented in npc_scrap_reaverAI, npc_hungry_nether_rayAI, npc_zeppitAI, npc_depleted_war_golemAI, and ScriptedPetAI.
Definition at line 216 of file UnitAI.h.
Referenced by PetOwnerKilledUnitHelper::operator()().
ReceiveAIEvent()
virtual void UnitAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) inline virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented in hyjalAI, ScriptedAI, boss_rimefang_posAI, npc_tirion_fordringAI, npc_isillienAI, npc_dawnblade_blood_knight, CreatureEventAI, npc_headless_horseman_fireAI, npc_xiri, npc_bt_battle_sensor, npc_adyen_the_lightwardenAI, npc_evergrove_druidAI, npc_akamaAI, boss_ichoronAI, boss_galdarahAI, mob_core_ragerAI, npc_shattered_sun_marksmanAI, npc_prison_event_controllerAI, npc_halion_controllerAI, mob_soaring_eagleAI, npc_domesticated_felboarAI, npc_nazgrelAI, npc_danath_trollbaneAI, npc_champion_mountAI, trial_companion_commonAI, npc_highlord_darion_mograineAI, mob_big_oozeAI, npc_emilyAI, npc_arthasAI, npc_demolitionist_legosoAI, npc_supplicantAI, npc_graufAI, boss_skadiAI, boss_general_vezaxAI, npc_power_sparkAI, boss_crusader_warlockAI, boss_crusader_priest_shadowAI, boss_crusader_shaman_restoAI, boss_crusader_priest_discAI, boss_crusader_paladin_holyAI, boss_crusader_druid_restoAI, boss_ingvarAI, npc_brann_hosAI, boss_varosAI, npc_infantryAI, npc_anchorite_baradaAI, npc_decaying_ghoulAI, npc_ghoul_feeding_bunnyAI, npc_keeper_mimironAI, boss_heart_deconstructorAI, boss_xt_002AI, boss_sifAI, npc_razorscale_spawnerAI, npc_expedition_commanderAI, boss_razorscaleAI, boss_kologarnAI, npc_living_constellationAI, boss_algalonAI, mob_tenebronAI, boss_malygosAI, npc_king_ymironAI, boss_crusader_rogueAI, boss_crusader_paladin_retriAI, boss_crusader_warriorAI, boss_crusader_death_knightAI, boss_crusader_mageAI, boss_crusader_hunterAI, boss_crusader_druid_balanceAI, boss_black_knightAI, npc_nexus_drake_hatchlingAI, npc_kerlonianAI, boss_kalecgosAI, npc_valentine_boss_managerAI, boss_head_of_horsemanAI, boss_headless_horsemanAI, npc_scarlet_ghoulAI, npc_death_knight_initiateAI, npc_chess_piece_genericAI, npc_netherspite_portalAI, npc_fhwoorAI, npc_skyguard_prisonerAI, npc_drijyaAI, npc_nagrand_captiveAI, npc_simon_game_bunnyAI, npc_shaheenAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, boss_yogg_saronAI, npc_injured_minerAI, npc_tipsy_mcmanusAI, npc_grand_admiral_westwindAI, npc_father_kamarosAI, npc_squad_leaderAI, npc_apothecary_hanesAI, npc_harrison_jonesAI, npc_proudhoofAI, npc_mootoo_the_youngerAI, npc_bonker_togglevoltAI, npc_shay_leafrunnerAI, npc_areiAI, npc_captured_arkonarinAI, npc_stinky_ignatzAI, npc_tapoke_slim_jahnAI, npc_anchorite_truuenAI, npc_dorius_stonetenderAI, npc_corporal_keeshan_escortAI, npc_kernobeeAI, npc_kineloryAI, boss_alarAI, mob_shadowmoon_channelerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, npc_bonechewer_brawler, npc_anubarak_trial_spikeAI, boss_ossirianAI, boss_renatakiAI, boss_mandokirAI, boss_akilzonAI, npc_sinister_reflectionAI, boss_sathrovarrAI, boss_arugalAI, boss_bigbadwolfAI, boss_coren_direbrewAI, npc_dreadmawAI, npc_eye_of_shartuulAI, npc_shivan_assassinAI, npc_doomguard_punisherAI, ScourgeMinion, npc_cultist_engineer, boss_silithidRoyaltyAI, npc_amanishi_hatcherAI, npc_taelan_fordringAI, boss_selin_fireheartAI, npc_orphan_matronAI, mob_phoenix_tkAI, boss_kaelthasAI, npc_lord_illidan_stormrageAI, npc_scrap_reaverAI, npc_energy_ballAI, npc_salhadaarAI, npc_manaforge_control_consoleAI, npc_razorthorn_ravager_pet, npc_shattered_hand_legionnaire, boss_magtheridonAI, boss_vazruden_heraldAI, npc_ice_spear_bunnyAI, boss_terokkAI, npc_spirit_prisoner_of_bladespire, npc_bloodmaul_dire_wolfAI, mob_blood_elf_council_voice_triggerAI, boss_teron_gorefiendAI, boss_supremusAI, npc_creature_generatorAI, boss_reliquary_of_soulsAI, npc_shadow_demonAI, npc_akama_illidanAI, npc_skyguard_aether_techAI, boss_murmurAI, boss_ambassador_hellmawAI, boss_anzuAI, npc_teleportation_portalAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_mimironAI, boss_freyaAI, boss_halion_twilightAI, boss_halion_realAI, boss_professor_putricideAI, boss_lady_deathwhisperAI, twin_jormungars_commonAI, npc_jennyAI, boss_taldaramAI, boss_viscidusAI, boss_cthunAI, npc_general_andorovAI, npc_major_mills, boss_arlokkAI, npc_amanishi_scoutAI, npc_ashliAI, npc_krazAI, npc_tanzarAI, npc_harkorAI, npc_amanishi_lookoutAI, npc_harrison_jones_zaAI, boss_janalaiAI, boss_muruAI, boss_kiljaedenAI, boss_sacrolashAI, boss_alythessAI, boss_shazzrahAI, mob_pure_energyAI, boss_aranAI, boss_moroesAI, boss_razorgoreAI, boss_pyroguard_emberseerAI, npc_spirit_guideAI, npc_charged_sphereAI, npc_descent_madnessAI, npc_bot_triggerAI, boss_lich_king_horAI, MouthAI, boss_maievAI, boss_illidan_stormrageAI, npc_skyguard_rangerAI, npc_anzu_bird_spiritAI, boss_telestraAI, boss_zuljinAI, boss_malacrassAI, and boss_felblood_kaelthasAI.
Definition at line 372 of file UnitAI.h.
Referenced by AiDelayEventAround::Execute(), ScriptAction::ExecuteDbscriptCommand(), and SendAIEvent().
ReceiveEmote()
virtual void UnitAI::ReceiveEmote (Player * , uint32) inline virtual
Called at text emote receive from player.
Parameters
pPlayer Player* who sent the emote
uiEmote ID of the emote the player used with the creature as target
Reimplemented in npc_plucky_johnsonAI, npc_felhound_trackerAI, npc_chicken_cluckAI, npc_supplicantAI, mobs_spectral_ghostly_citizenAI, npc_mojoAI, guardAI_stormwind, guardAI_orgrimmar, CreatureEventAI, example_creatureAI, and npc_taskmaster_fizzuleAI.
Definition at line 282 of file UnitAI.h.
Referenced by WorldSession::HandleTextEmoteOpcode().
RelinquishFollow()
virtual void UnitAI::RelinquishFollow (ObjectGuid) inline virtual
Reimplemented in CreatureAI.
Definition at line 569 of file UnitAI.h.
Referenced by FollowMovementGenerator::Finalize(), and Creature::RemoveFromWorld().
RequestFollow()
virtual void UnitAI::RequestFollow (Unit *) inline virtual
Reimplemented in CreatureAI.
Definition at line 568 of file UnitAI.h.
Referenced by TailsUpSummonFemaleFrostLeopard::OnSummon(), and TailsUpSummonFemaleIcepawBear::OnSummon().
RetreatingArrived()
virtual void UnitAI::RetreatingArrived () inline virtual
Reimplemented in CreatureAI.
Definition at line 483 of file UnitAI.h.
RetreatingEnded()
virtual void UnitAI::RetreatingEnded () inline virtual
Reimplemented in CreatureAI.
Definition at line 484 of file UnitAI.h.
SendAIEvent()
void UnitAI::SendAIEvent (AIEventType eventType, Unit * invoker, Unit * receiver, uint32 miscValue = 0) const
Send an AI Event to a Creature.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pInvoker Unit that triggered this event (like an attacker)
pReceiver Creature to receive this event
Definition at line 669 of file UnitAI.cpp.
References Unit::AI(), m_unit, MANGOS_ASSERT, and ReceiveAIEvent().
Referenced by boss_algalonAI::ActivateRandomConstellation(), boss_kalecgosAI::Aggro(), boss_halion_realAI::Aggro(), boss_halion_realAI::DamageTaken(), boss_halion_twilightAI::DamageTaken(), trial_crusader_commonAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), boss_vx001AI::DamageTaken(), boss_aerial_unitAI::DamageTaken(), boss_skadiAI::DoBoardGrauf(), boss_kaelthasAI::DoDespawnSummons(), boss_saraAI::DoInitialiseKeepers(), boss_kelidan_the_breakerAI::DoSetupAdds(), npc_teleportation_portalAI::DoSummon(), boss_akilzonAI::DoSummonEagles(), instance_black_temple::DoTeleportAkamaIfCan(), EffectAuraDummy_npc_nexus_drake_hatchling(), Spell::EffectDummy(), EffectDummyCreature_awaken_kerlonian(), EffectDummyCreature_black_knight_res(), EffectDummyCreature_npc_bot_trigger(), EffectDummyCreature_npc_chess_generic(), EffectDummyCreature_npc_death_knight_initiate(), EffectDummyCreature_npc_decaying_ghoul(), EffectDummyCreature_npc_grand_admiral_westwind(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_putricide(), EffectDummyCreature_npc_scarlet_ghoul(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_npc_shay_leafrunner(), EffectDummyCreature_npc_simon_game_bunny(), EffectDummyCreature_npc_teleportation_portal(), EffectDummyCreature_npc_wants_fruit_credit(), EffectDummyCreature_worm_emerge(), EffectScriptEffectCreature_boss_freya(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_spell_diminution_powder(), EffectScriptEffectCreature_spell_stun_break(), EffectScriptEffectCreature_spell_unstable_ooze(), boss_sathrovarrAI::EnterEvadeMode(), boss_tyrannusAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), mob_torlothAI::FailEvent(), GossipSelect_npc_anchorite_barada(), GossipSelect_npc_arthas(), GossipSelect_npc_brann_hos(), GossipSelect_npc_expedition_commander(), GossipSelect_npc_highlord_darion_mograine(), GossipSelect_npc_injured_miner(), GossipSelect_npc_orphan_matron(), GossipSelect_npc_tipsy_mcmanus(), WorldState::HandleActiveZone(), Aura::HandleAuraDummy(), Aura::HandleAuraModTotalManaPercentRegen(), Aura::HandleAuraPeriodicDummy(), Unit::HandleDummyAuraProc(), npc_bonechewer_combatant::HandleEventStart(), BattleGroundIC::HandleKillUnit(), Aura::HandleModMeleeSpeedPct(), npc_taelan_fordringAI::JustDidDialogueStep(), boss_maievAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), boss_golemaggAI::JustDied(), boss_eye_of_cthunAI::JustDied(), boss_gormokAI::JustDied(), npc_saronite_vaporAI::JustDied(), boss_heart_deconstructorAI::JustDied(), npc_graufAI::JustDied(), boss_shade_of_akamaAI::JustDied(), mob_ashtongue_channelerAI::JustDied(), mob_ashtongue_sorcererAI::JustDied(), mob_torlothAI::JustDied(), boss_sathrovarrAI::JustPreventedDeath(), npc_kaylaan_the_lostAI::JustReachedHome(), npc_rubble_stalkerAI::JustSummoned(), boss_razorscaleAI::JustSummoned(), npc_voice_yogg_saronAI::JustSummoned(), npc_storm_tempered_keeperAI::JustSummoned(), npc_taelan_fordringAI::JustSummoned(), boss_saraAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_eagle_trash_aggro_triggerAI::MoveInLineOfSight(), npc_ingvar_throw_dummyAI::MoveInLineOfSight(), boss_shade_of_akamaAI::MovementInform(), boss_thorimAI::MovementInform(), npc_deadsoul_orb::MovementInform(), boss_leviathan_mk2AI::MovementInform(), npc_decaying_ghoulAI::MovementInform(), npc_saronite_vaporAI::MovementInform(), MoroesVanish::OnApply(), DarknessOfSouls::OnApply(), SinisterReflectionClone::OnApply(), SpellFury::OnApply(), spell_telestra_clone_dies_aura::OnApply(), spell_protective_bubble_aura::OnApply(), spell_drained_aura::OnApply(), SupremusRandomTarget::OnApply(), ScrapReaverSpell::OnApply(), DarknessMuru::OnCast(), world_map_outland::OnCreatureCreate(), instance_ulduar::OnCreatureDeath(), instance_sunwell_plateau::OnCreatureRespawn(), PortalAttunement::OnEffectExecute(), SendHead::OnEffectExecute(), HeadRequestsBody::OnEffectExecute(), SpectralRealmNotify::OnEffectExecute(), ArlokkVanish::OnEffectExecute(), RenatakiVanish::OnEffectExecute(), spell_pursuing_spikes::OnEffectExecute(), spell_tag_troll::OnEffectExecute(), spell_arcane_storm::OnEffectExecute(), spell_summon_telestra_clones::OnEffectExecute(), spell_water_globule_merge::OnEffectExecute(), FixateBT::OnEffectExecute(), ExposeRazorthornRoot::OnEffectExecute(), SummonIceSpearKnockbackDelayer::OnPeriodicDummy(), TerokkAncientFlames::OnPeriodicTickEnd(), spell_mana_barrier_aura::OnPeriodicTrigger(), SummonPlagueSpray::OnSummon(), SummonBoss::OnSummon(), Aura::PeriodicDummyTick(), BattleGroundEY::ProcessCaptureEvent(), QuestAccept_npc_anchorite_truuen(), QuestAccept_npc_apothecary_hanes(), QuestAccept_npc_arei(), QuestAccept_npc_bonker_togglevolt(), QuestAccept_npc_captured_arkonarin(), QuestAccept_npc_corporal_keeshan(), QuestAccept_npc_demolitionist_legoso(), QuestAccept_npc_dorius_stonetender(), QuestAccept_npc_drijya(), QuestAccept_npc_emily(), QuestAccept_npc_father_kamaros(), QuestAccept_npc_fhwoor(), QuestAccept_npc_harrison_jones(), QuestAccept_npc_injured_miner(), QuestAccept_npc_kernobee(), QuestAccept_npc_kinelory(), QuestAccept_npc_mikhail(), QuestAccept_npc_mootoo_the_younger(), QuestAccept_npc_nagrand_captive(), QuestAccept_npc_orphan_matron(), QuestAccept_npc_proudhoof(), QuestAccept_npc_shaheen(), QuestAccept_npc_shay_leafrunner(), QuestAccept_npc_skyguard_prisoner(), QuestAccept_npc_squad_leader(), QuestAccept_npc_stinky_ignatz(), QuestAccept_npc_taelan_fordring(), QuestComplete_npc_nazgrel(), QuestComplete_npc_trollbane(), QuestRewarded_boss_apothecary_hummel(), QuestRewarded_npc_coren_direbrew(), QuestRewarded_npc_taelan_fordring(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_yogg_saronAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), npc_arcane_beamAI::Reset(), world_map_outland::SpawnAlliesAtCrystalforge(), world_map_outland::StartBashirLandingEvent(), npc_dawnblade_blood_knight::StartDuel(), world_map_outland::StartTransitionPhase(), npc_dawnblade_blood_knight::StopDuel(), boss_akilzonAI::SummonedCreatureJustDied(), SummonElves(), Aura::TriggerSpell(), world_map_ebon_hold::Update(), npc_bonechewer_combatant::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), trial_companion_commonAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), boss_gormokAI::UpdateAI(), npc_tenebron_egg_controllerAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), boss_xt_002AI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), npc_brain_yogg_saronAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), boss_murmurAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), and npc_isillienAI::UpdateEscortAI().
SendAIEventAround()
void UnitAI::SendAIEventAround (AIEventType eventType, Unit * invoker, uint32 delay, float radius, uint32 miscValue = 0) const
== Event Handling ===============================
Send an AI Event to nearby Creatures around
Parameters
uiType number to specify the event, default cases listed in enum AIEventType
pInvoker Unit that triggered this event (like an attacker)
uiDelay delay time until the Event will be triggered
fRadius range in which for receiver is searched
Definition at line 628 of file UnitAI.cpp.
References EventProcessor::AddEvent(), AI_EVENT_CALL_ASSISTANCE, AI_EVENT_CUSTOM_EVENTAI_A, AI_EVENT_CUSTOM_EVENTAI_F, AI_EVENT_GOT_CCED, AI_EVENT_START_ESCORT, EventProcessor::CalculateTime(), Object::GetObjectGuid(), WorldObject::m_events, m_unit, and Cell::VisitAllObjects().
Referenced by Creature::CallAssistance(), CreatureEventAI::DamageTaken(), trial_crusader_commonAI::DamageTaken(), boss_anomalusAI::DoResumeCombat(), boss_deathbringer_saurfangAI::HandleDeath(), CreatureEventAI::HealedBy(), trial_crusader_commonAI::HealedBy(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), CreatureEventAI::JustDied(), trial_crusader_commonAI::JustDied(), boss_malygosAI::MovementInform(), CreatureEventAI::ProcessAction(), npc_squad_leaderAI::ReceiveAIEvent(), trial_crusader_commonAI::UpdateAI(), and boss_malygosAI::UpdateAI().
SetAIImmobilizedState()
void UnitAI::SetAIImmobilizedState (bool apply, bool combatOnly = false)
Definition at line 914 of file UnitAI.cpp.
References Unit::addUnitState(), ByteConverter::apply(), Unit::clearUnitState(), m_combatOnlyRoot, m_unit, Unit::SetImmobilizedState(), and UNIT_STAT_AI_ROOT.
Referenced by npc_burster_wormAI::Aggro(), boss_ahuneAI::boss_ahuneAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_murmurAI::boss_murmurAI(), CreatureAI::CreatureAI(), boss_heiganAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_nothAI::JustSummoned(), npc_snakeWrapAI::npc_snakeWrapAI(), npc_tesla_coilAI::npc_tesla_coilAI(), CreatureEventAI::ProcessAction(), boss_heiganAI::Reset(), boss_nothAI::Reset(), and CreatureSettings::updateFlag().
SetAIOrder()
void UnitAI::SetAIOrder (AIOrders order) inline
Definition at line 460 of file UnitAI.h.
References m_currentAIOrder.
Referenced by DoFlee(), CreatureAI::DoRetreat(), CreatureAI::EnterCombat(), CreatureAI::OnCallForHelp(), CreatureEventAI::Reset(), CreatureAI::RetreatingEnded(), CombatManager::SetEvadeState(), TimedFleeingEnded(), and CreatureAI::TimedFleeingEnded().
SetCombatMovement()
void UnitAI::SetCombatMovement (bool enable, bool stopOrStartMovement = false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
Definition at line 300 of file UnitAI.cpp.
References Unit::addUnitState(), CHASE_MOTION_TYPE, Unit::clearUnitState(), DoStartMovement(), MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), Unit::GetVictim(), Unit::InterruptMoving(), Unit::IsCrowdControlled(), m_unit, and UNIT_STAT_NO_COMBAT_MOVEMENT.
Referenced by npc_daphne_stilwellAI::Aggro(), npc_amanishi_scoutAI::Aggro(), boss_lady_blaumeuxAI::Aggro(), boss_rivendare_naxxAI::Aggro(), boss_thane_korthazzAI::Aggro(), boss_sir_zeliekAI::Aggro(), boss_gothikAI::Aggro(), mob_bt_battle_fighterAI::Aggro(), boss_sindragosaAI::AttackStart(), boss_aerial_unitAI::boss_aerial_unitAI(), boss_arlokkAI::boss_arlokkAI(), boss_entropiusAI::boss_entropiusAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_lich_king_horAI::boss_lich_king_horAI(), boss_maievAI::boss_maievAI(), boss_nefarianAI::boss_nefarianAI(), boss_omor_the_unscarredAI::boss_omor_the_unscarredAI(), boss_renatakiAI::boss_renatakiAI(), boss_rimefang_posAI::boss_rimefang_posAI(), boss_supremusAI::boss_supremusAI(), boss_thekalAI::boss_thekalAI(), boss_vx001AI::boss_vx001AI(), npc_escortAI::CorpseRemoved(), FollowerAI::CorpseRemoved(), npc_rethhedronAI::DamageTaken(), advisor_base_ai::DamageTaken(), trial_companion_commonAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), DarkFiendAI::DarkFiendAI(), boss_buruAI::DoAttackNewTarget(), boss_ymironAI::DoChannelSpiritYmiron(), boss_drakkari_colossusAI::DoEmergeElemental(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_vazruden_heraldAI::DoMoveToCenter(), boss_midnightAI::DoPrepareMount(), boss_julianneAI::DoRemoveFakeDeath(), boss_romuloAI::DoRemoveFakeDeath(), boss_julianneAI::DoSetFakeDeath(), boss_romuloAI::DoSetFakeDeath(), mob_phoenix_tkAI::DoSetFakeDeath(), npc_Shattered_Hand_Scout::DoStartRunning(), boss_lady_deathwhisperAI::DoStartSecondPhase(), dummy_blackheart_the_inciterAI::dummy_blackheart_the_inciterAI(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), npc_sunblade_scoutAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_warlord_kalithreshAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteMagisterActions(), boss_zuljinAI::ExecutePhaseTransition(), mob_torlothAI::HandleAnimation(), boss_entropiusAI::HandleAttackDelay(), DarkFiendAI::HandleAttackDelay(), boss_vazruden_heraldAI::HandleAttackDelay(), boss_nefarianAI::HandleAttackStart(), boss_talon_king_ikissAI::HandleBlink(), boss_skeramAI::HandleBlinkDelay(), boss_twin_emperorsAI::HandleDelayedAttack(), boss_silithidRoyaltyAI::HandleDevourDelay(), boss_alarAI::HandleDiveBomb(), boss_aranAI::HandleDrinking(), boss_alythessAI::HandleEmpowerDelay(), boss_sacrolashAI::HandleEmpowerDelay(), boss_felmystAI::HandleFelmystSpawnDelay(), boss_gothikAI::HandleGroundPhase(), boss_heiganAI::HandleGroundPhase(), boss_blackheart_the_inciterAI::HandleInciteEnd(), boss_telestraAI::HandlePersonalityMerge(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_magtheridonAI::HandlePhaseTransition(), boss_buruAI::HandlePhaseTwo(), boss_alarAI::HandleRebirth(), boss_high_inquisitor_whitemaneAI::HandleResurrectionCombat(), npc_singularityAI::HandleSpawn(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_felmystAI::HandleTransitionDelay(), boss_victor_nefariusAI::JustDidDialogueStep(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), boss_thekalBaseAI::JustPreventedDeath(), mob_pure_energyAI::JustPreventedDeath(), boss_apothecary_hummelAI::JustPreventedDeath(), boss_jedogaAI::JustReachedHome(), boss_bronjahmAI::JustReachedHome(), boss_forgemaster_garfrostAI::JustReachedHome(), boss_lady_deathwhisperAI::JustReachedHome(), boss_savianaAI::JustReachedHome(), npc_shattered_sun_fighterAI::JustRespawned(), mobs_spectral_ghostly_citizenAI::JustRespawned(), npc_singularityAI::JustRespawned(), boss_bronjahmAI::JustRespawned(), npc_rethhedronAI::JustRespawned(), npc_colonel_julesAI::JustSummoned(), boss_felblood_kaelthasAI::JustSummoned(), npc_demonic_vaporAI::JustSummoned(), boss_kiljaedenAI::JustSummoned(), boss_muruAI::JustSummoned(), npc_portal_targetAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_zuljinAI::JustSummoned(), boss_ichoronAI::JustSummoned(), boss_illidan_stormrageAI::JustSummoned(), npc_flame_of_azzinothAI::JustSummoned(), boss_supremusAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_maievAI::KilledUnit(), mob_blood_elf_council_voice_triggerAI::mob_blood_elf_council_voice_triggerAI(), mob_illidari_councilAI::mob_illidari_councilAI(), mob_pure_energyAI::mob_pure_energyAI(), mob_soaring_eagleAI::mob_soaring_eagleAI(), boss_kaelthasAI::MoveInLineOfSight(), boss_nightbaneAI::MovementInform(), boss_ayamissAI::MovementInform(), boss_rivendare_naxxAI::MovementInform(), boss_thane_korthazzAI::MovementInform(), boss_alarAI::MovementInform(), boss_kaelthasAI::MovementInform(), boss_blood_queen_lanathelAI::MovementInform(), boss_sindragosaAI::MovementInform(), npc_rimefang_iccAI::MovementInform(), boss_jeklikAI::MovementInform(), boss_jedogaAI::MovementInform(), boss_malygosAI::MovementInform(), boss_savianaAI::MovementInform(), boss_volkhanAI::MovementInform(), boss_brundirAI::MovementInform(), npc_sunblade_scoutAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), boss_icehowlAI::MovementInform(), npc_amanishi_hatcherAI::npc_amanishi_hatcherAI(), npc_bashir_flesh_fiendAI::npc_bashir_flesh_fiendAI(), npc_corrupted_lightning_totemAI::npc_corrupted_lightning_totemAI(), npc_darknessAI::npc_darknessAI(), npc_demonic_vaporAI::npc_demonic_vaporAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_doom_blossomAI::npc_doom_blossomAI(), npc_eagle_trash_aggro_triggerAI::npc_eagle_trash_aggro_triggerAI(), npc_fire_nova_totemAI::npc_fire_nova_totemAI(), npc_jaina_sylvanas_horAI::npc_jaina_sylvanas_horAI(), npc_living_poisonAI::npc_living_poisonAI(), npc_ouro_triggerAI::npc_ouro_triggerAI(), npc_power_blue_flightAI::npc_power_blue_flightAI(), npc_reliquary_combat_triggerAI::npc_reliquary_combat_triggerAI(), npc_scrapped_fel_reaverAI::npc_scrapped_fel_reaverAI(), npc_shield_orbAI::npc_shield_orbAI(), npc_tesla_coilAI::npc_tesla_coilAI(), npc_warden_mellicharAI::npc_warden_mellicharAI(), instance_temple_of_ahnqiraj::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureRespawn(), instance_zulaman::OnCreatureRespawn(), instance_temple_of_ahnqiraj::OnCreatureRespawn(), DarkFiendDummy::OnEffectExecute(), mob_phoenix_tkAI::OnSpellCooldownAdded(), SummonGargoyle::OnSummon(), npc_anubarak_trial_spikeAI::PermafrostHit(), CreatureEventAI::ProcessAction(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_alythessAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), npc_amanishi_scoutAI::ReceiveAIEvent(), twin_jormungars_commonAI::ReceiveAIEvent(), boss_leviathan_mk2AI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), boss_silithidRoyaltyAI::ReceiveAIEvent(), boss_renatakiAI::ReceiveAIEvent(), npc_anubarak_trial_spikeAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), npc_ironhand_guardianAI::Reset(), boss_kazzakAI::Reset(), boss_midnightAI::Reset(), boss_moroesAI::Reset(), boss_netherspiteAI::Reset(), boss_nightbaneAI::Reset(), boss_aranAI::Reset(), boss_dorotheeAI::Reset(), boss_felblood_kaelthasAI::Reset(), boss_selin_fireheartAI::Reset(), mob_fel_crystalAI::Reset(), boss_vexallusAI::Reset(), boss_apothecary_hummelAI::Reset(), boss_felmystAI::Reset(), npc_kiljaeden_controllerAI::Reset(), boss_kiljaedenAI::Reset(), boss_muruAI::Reset(), npc_portal_targetAI::Reset(), boss_zuljinAI::Reset(), boss_arlokkAI::Reset(), boss_jeklikAI::Reset(), boss_renatakiAI::Reset(), boss_thekalBaseAI::Reset(), boss_archimondeAI::Reset(), npc_doomfire_targetingAI::Reset(), boss_eranikusAI::Reset(), boss_onyxiaAI::Reset(), boss_ayamissAI::Reset(), boss_buruAI::Reset(), npc_buru_eggAI::Reset(), boss_eye_of_cthunAI::Reset(), boss_cthunAI::Reset(), boss_ouroAI::Reset(), boss_volazjAI::Reset(), npc_anubarak_trial_spikeAI::Reset(), boss_acidmawAI::Reset(), boss_drakkari_colossusAI::Reset(), boss_lord_marrowgarAI::Reset(), npc_rimefang_iccAI::Reset(), mob_frost_bombAI::Reset(), boss_gothikAI::Reset(), boss_kelthuzadAI::Reset(), npc_obedienceCrystalAI::Reset(), boss_sapphironAI::Reset(), boss_malygosAI::Reset(), boss_telestraAI::Reset(), npc_hodir_fury_reticleAI::Reset(), boss_leviathan_mk2AI::Reset(), boss_aerial_unitAI::Reset(), boss_razorscaleAI::Reset(), boss_thorimAI::Reset(), boss_sifAI::Reset(), boss_talon_king_ikissAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_reliquary_of_soulsAI::Reset(), npc_akamaAI::Reset(), boss_shade_of_akamaAI::Reset(), boss_najentusAI::Reset(), boss_lady_vashjAI::Reset(), boss_leotheras_the_blindAI::Reset(), boss_ahuneAI::Reset(), boss_warlord_kalithreshAI::Reset(), boss_black_stalkerAI::Reset(), boss_swamplord_muselekAI::Reset(), boss_gruulAI::Reset(), boss_magtheridonAI::Reset(), boss_grand_warlock_nethekurseAI::Reset(), boss_warchief_kargath_bladefistAI::Reset(), npc_magister_aledisAI::Reset(), mob_torlothAI::Reset(), mob_shadowmoon_soulstealerAI::Reset(), mob_bt_battle_fighterAI::Reset(), StunField::Reset(), boss_high_botanist_freywinnAI::Reset(), boss_alarAI::Reset(), boss_high_astromancer_solarianAI::Reset(), boss_kaelthasAI::Reset(), advisor_base_ai::Reset(), boss_highlord_kruulAI::Reset(), npc_burster_wormAI::Reset(), boss_thekalBaseAI::Revive(), Scripted_NoMovementAI::Scripted_NoMovementAI(), mobs_spectral_ghostly_citizenAI::SpellHit(), boss_leviathan_mk2AI::SpellHit(), boss_zuljinAI::SpellHit(), npc_saplingAI::SpellHit(), boss_najentusAI::SpellHit(), boss_maievAI::SpellHit(), boss_drakkari_colossusAI::SpellHit(), boss_volazjAI::SpellHitTarget(), boss_bronjahmAI::SpellHitTarget(), boss_soccothratesAI::SpellHitTarget(), boss_twin_emperorsAI::StartDelayedAttack(), boss_kelthuzadAI::StartPhase2(), boss_skeramAI::StopAttacking(), boss_high_botanist_freywinnAI::SummonedCreatureJustDied(), boss_muruAI::SummonedMovementInform(), boss_the_lurker_belowAI::SummonedMovementInform(), boss_netherspiteAI::SwitchPhases(), mobs_spectral_ghostly_citizenAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), boss_jedogaAI::UpdateAI(), boss_volazjAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_savianaAI::UpdateAI(), boss_volkhanAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_ymironAI::UpdateAI(), boss_grandmaster_vorpilAI::UpdateAI(), boss_grand_warlock_nethekurseAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), boss_high_botanist_freywinnAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), advisor_base_ai::UpdateAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), and npc_daphne_stilwellAI::WaypointReached().
SetCombatScriptStatus()
void UnitAI::SetCombatScriptStatus (bool state) inline
Definition at line 457 of file UnitAI.h.
References m_combatScriptHappening.
Referenced by npc_amanishi_scoutAI::Aggro(), boss_lady_blaumeuxAI::Aggro(), boss_rivendare_naxxAI::Aggro(), boss_thane_korthazzAI::Aggro(), boss_sir_zeliekAI::Aggro(), boss_gothikAI::Aggro(), boss_alarAI::Aggro(), npc_burster_wormAI::Aggro(), boss_felmystAI::Aggro(), boss_arlokkAI::boss_arlokkAI(), boss_maievAI::boss_maievAI(), boss_renatakiAI::boss_renatakiAI(), boss_supremusAI::boss_supremusAI(), boss_thekalAI::boss_thekalAI(), boss_ouroAI::Burrow(), npc_rethhedronAI::DamageTaken(), advisor_base_ai::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), boss_ingvarAI::DamageTaken(), DistancingEnded(), DistancingStarted(), boss_alarAI::DoFlameQuills(), DoFlee(), boss_vazruden_heraldAI::DoMoveToCenter(), boss_vazruden_heraldAI::DoMoveToCombat(), boss_alarAI::DoPlatformMove(), boss_midnightAI::DoPrepareMount(), CreatureAI::DoRetreat(), boss_selin_fireheartAI::DoSelectNearestCrystal(), mob_phoenix_tkAI::DoSetFakeDeath(), ChildTbcAI::EndQuestSequence(), boss_high_inquisitor_whitemaneAI::EnterCombat(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), npc_sunblade_scoutAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), boss_warlord_kalithreshAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), boss_zuljinAI::ExecutePhaseTransition(), npc_razorthorn_ravager_pet::HandleAnimations(), boss_nightbaneAI::HandleAttackDelay(), boss_vazruden_heraldAI::HandleAttackDelay(), boss_talon_king_ikissAI::HandleBlink(), boss_skeramAI::HandleBlinkDelay(), npc_burster_wormAI::HandleChaseSequence(), boss_twin_emperorsAI::HandleDelayedAttack(), boss_silithidRoyaltyAI::HandleDevourDelay(), boss_alarAI::HandleDiveBomb(), boss_aranAI::HandleDrinking(), boss_ahuneAI::HandleEmerge(), boss_alythessAI::HandleEmpowerDelay(), boss_sacrolashAI::HandleEmpowerDelay(), boss_eye_of_cthunAI::HandleEndDarkGlare(), boss_felmystAI::HandleFelmystSpawnDelay(), boss_felblood_kaelthasAI::HandleGravityLapse(), boss_heiganAI::HandleGroundPhase(), boss_blackheart_the_inciterAI::HandleInciteEnd(), boss_felblood_kaelthasAI::HandleOutro(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_magtheridonAI::HandlePhaseTransition(), boss_buruAI::HandlePhaseTwo(), boss_alarAI::HandleRebirth(), boss_high_inquisitor_whitemaneAI::HandleResurrectionCombat(), boss_scarlet_commander_mograineAI::HandleRevivedTimer(), boss_ouroAI::HandleSpawnDelay(), boss_muruAI::HandleSpawnEntropius(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_the_lurker_belowAI::HandleSpoutEnd(), boss_the_lurker_belowAI::HandleSubmergeActions(), boss_felmystAI::HandleTransitionDelay(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), boss_thekalBaseAI::JustPreventedDeath(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), essence_base_AI::JustPreventedDeath(), boss_apothecary_hummelAI::JustPreventedDeath(), boss_majordomoAI::JustReachedHome(), boss_ingvarAI::JustReachedHome(), mobs_spectral_ghostly_citizenAI::JustRespawned(), npc_akama_illidanAI::JustRespawned(), npc_rethhedronAI::JustRespawned(), boss_doomwalkerAI::JustSummoned(), boss_maievAI::KilledUnit(), boss_kaelthasAI::MoveInLineOfSight(), boss_nightbaneAI::MovementInform(), boss_ayamissAI::MovementInform(), boss_lady_blaumeuxAI::MovementInform(), boss_rivendare_naxxAI::MovementInform(), boss_thane_korthazzAI::MovementInform(), boss_sir_zeliekAI::MovementInform(), boss_vazruden_heraldAI::MovementInform(), boss_alarAI::MovementInform(), boss_kaelthasAI::MovementInform(), boss_doomwalkerAI::MovementInform(), GargoyleDeathKnightAI::MovementInform(), boss_selin_fireheartAI::MovementInform(), boss_illidan_stormrageAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_sapphironAI::MovementInform(), npc_sunblade_scoutAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), boss_lady_vashjAI::MovementInform(), npc_amanishi_hatcherAI::npc_amanishi_hatcherAI(), npc_bashir_flesh_fiendAI::npc_bashir_flesh_fiendAI(), npc_burster_wormAI::npc_burster_wormAI(), npc_kagani_nightstrikeAI::npc_kagani_nightstrikeAI(), ThaddiusLightningVisual::OnEffectExecute(), DarkFiendDummy::OnEffectExecute(), mob_phoenix_tkAI::OnSpellCooldownAdded(), SummonGargoyle::OnSummon(), boss_zuljinAI::ReceiveAIEvent(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), boss_alythessAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), npc_amanishi_scoutAI::ReceiveAIEvent(), boss_arlokkAI::ReceiveAIEvent(), npc_akama_illidanAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), boss_silithidRoyaltyAI::ReceiveAIEvent(), boss_renatakiAI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), CreatureEventAI::Reset(), boss_victor_nefariusAI::Reset(), boss_kazzakAI::Reset(), boss_midnightAI::Reset(), boss_moroesAI::Reset(), boss_nightbaneAI::Reset(), boss_dorotheeAI::Reset(), boss_felblood_kaelthasAI::Reset(), npc_kagani_nightstrikeAI::Reset(), boss_selin_fireheartAI::Reset(), boss_scarlet_commander_mograineAI::Reset(), boss_apothecary_hummelAI::Reset(), boss_alythessAI::Reset(), boss_sacrolashAI::Reset(), boss_felmystAI::Reset(), boss_muruAI::Reset(), boss_zuljinAI::Reset(), boss_arlokkAI::Reset(), boss_renatakiAI::Reset(), boss_thekalBaseAI::Reset(), boss_archimondeAI::Reset(), npc_corrupted_furbolgAI::Reset(), boss_ayamissAI::Reset(), boss_buruAI::Reset(), boss_eye_of_cthunAI::Reset(), boss_lady_blaumeuxAI::Reset(), boss_rivendare_naxxAI::Reset(), boss_thane_korthazzAI::Reset(), boss_sir_zeliekAI::Reset(), boss_gothikAI::Reset(), boss_kelthuzadAI::Reset(), boss_sapphironAI::Reset(), boss_thaddiusAI::Reset(), boss_talon_king_ikissAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_lady_vashjAI::Reset(), boss_leotheras_the_blindAI::Reset(), boss_the_lurker_belowAI::Reset(), boss_ahuneAI::Reset(), boss_warlord_kalithreshAI::Reset(), boss_black_stalkerAI::Reset(), boss_swamplord_muselekAI::Reset(), boss_magtheridonAI::Reset(), boss_warchief_kargath_bladefistAI::Reset(), npc_magister_aledisAI::Reset(), mob_bt_battle_fighterAI::Reset(), boss_alarAI::Reset(), boss_kaelthasAI::Reset(), advisor_base_ai::Reset(), boss_highlord_kruulAI::Reset(), CreatureAI::RetreatingEnded(), boss_thekalBaseAI::Revive(), mobs_spectral_ghostly_citizenAI::SpellHit(), boss_zuljinAI::SpellHit(), npc_saplingAI::SpellHit(), boss_maievAI::SpellHit(), boss_twin_emperorsAI::StartDelayedAttack(), boss_kelthuzadAI::StartPhase2(), boss_alarAI::StartPhaseTransition(), ChildTbcAI::StartQuestSequence(), boss_skeramAI::StopAttacking(), boss_majordomoAI::SummonedCreatureJustDied(), TimedFleeingEnded(), CreatureAI::TimedFleeingEnded(), mobs_spectral_ghostly_citizenAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), advisor_base_ai::UpdateAI(), and npc_disciple_of_naralexAI::UpdateEscortAI().
SetCurrentRangedMode()
void UnitAI::SetCurrentRangedMode (bool state)
Definition at line 1015 of file UnitAI.cpp.
References DoStartMovement(), Unit::GetVictim(), Unit::hasUnitState(), m_attackDistance, m_chaseDistance, m_currentRangedMode, m_meleeEnabled, m_rangedModeSetting, m_unit, Unit::MeleeAttackStart(), Unit::SetIgnoreRangedTargets(), TYPE_NO_MELEE_MODE, UNIT_STAT_MELEE_ATTACKING, UNIT_STAT_ROOT, and UNIT_STAT_STUNNED.
Referenced by DistancingEnded(), HandleSpellCastResult(), OnSpellCooldownAdded(), OnSpellInterrupt(), SetRangedMode(), and UpdateAI().
SetFollowMovement()
void UnitAI::SetFollowMovement (bool enable)
Definition at line 319 of file UnitAI.cpp.
References Unit::addUnitState(), Unit::clearUnitState(), FOLLOW_MOTION_TYPE, MotionMaster::GetCurrentMovementGeneratorType(), Unit::GetMotionMaster(), Unit::InterruptMoving(), Unit::IsMoving(), m_unit, and UNIT_STAT_NO_FOLLOW_MOVEMENT.
Referenced by ChildTbcAI::EndQuestSequence(), TargetCrystal::OnCast(), spell_effect_summon_no_follow_movement::OnSummon(), ArmyOfTheDeadGhoul::OnSummon(), SummonGargoyle::OnSummon(), CreatureEventAI::ProcessAction(), and ChildTbcAI::StartQuestSequence().
SetMeleeEnabled()
void UnitAI::SetMeleeEnabled (bool state)
Definition at line 801 of file UnitAI.cpp.
References Unit::GetVictim(), Unit::hasUnitState(), Unit::IsInCombat(), m_meleeEnabled, m_unit, Unit::MeleeAttackStart(), Unit::MeleeAttackStop(), and UNIT_STAT_MELEE_ATTACKING.
Referenced by boss_gothikAI::Aggro(), boss_arlokkAI::boss_arlokkAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_high_nethermancer_zerevorAI::boss_high_nethermancer_zerevorAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_maievAI::boss_maievAI(), boss_nefarianAI::boss_nefarianAI(), boss_renatakiAI::boss_renatakiAI(), boss_thekalAI::boss_thekalAI(), boss_ouroAI::Burrow(), CreatureAI::CreatureAI(), DarkFiendAI::DarkFiendAI(), boss_vazruden_heraldAI::DoMoveToCenter(), boss_selin_fireheartAI::DoSelectNearestCrystal(), mob_phoenix_tkAI::DoSetFakeDeath(), boss_lady_deathwhisperAI::DoStartSecondPhase(), boss_high_inquisitor_whitemaneAI::EnterCombat(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), npc_sunblade_scoutAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), boss_warlord_kalithreshAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), boss_zuljinAI::ExecutePhaseTransition(), boss_kiljaedenAI::HandleAttackDelay(), boss_ahuneAI::HandleAttackDelay(), boss_vazruden_heraldAI::HandleAttackDelay(), boss_nefarianAI::HandleAttackStart(), boss_talon_king_ikissAI::HandleBlink(), boss_skeramAI::HandleBlinkDelay(), npc_burster_wormAI::HandleChaseSequence(), boss_twin_emperorsAI::HandleDelayedAttack(), boss_silithidRoyaltyAI::HandleDevourDelay(), boss_alarAI::HandleDiveBomb(), boss_aranAI::HandleDrinking(), boss_ahuneAI::HandleEmerge(), boss_sacrolashAI::HandleEmpowerDelay(), boss_felmystAI::HandleFelmystSpawnDelay(), boss_felblood_kaelthasAI::HandleGravityLapse(), boss_gothikAI::HandleGroundPhase(), boss_heiganAI::HandleGroundPhase(), boss_the_lurker_belowAI::HandleInitialAggro(), boss_felblood_kaelthasAI::HandleOutro(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_ragnarosAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_magtheridonAI::HandlePhaseTransition(), boss_buruAI::HandlePhaseTwo(), boss_alarAI::HandleRebirth(), boss_high_inquisitor_whitemaneAI::HandleResurrectionCombat(), boss_ouroAI::HandleSpawnDelay(), boss_felmystAI::HandleTransitionDelay(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), boss_apothecary_hummelAI::JustPreventedDeath(), boss_forgemaster_garfrostAI::JustReachedHome(), boss_lady_deathwhisperAI::JustReachedHome(), npc_shattered_sun_fighterAI::JustRespawned(), npc_singularityAI::JustRespawned(), boss_curatorAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_maievAI::KilledUnit(), mob_pure_energyAI::mob_pure_energyAI(), mob_soaring_eagleAI::mob_soaring_eagleAI(), boss_nightbaneAI::MovementInform(), boss_selin_fireheartAI::MovementInform(), npc_sunblade_scoutAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), npc_burster_wormAI::npc_burster_wormAI(), npc_corrupted_lightning_totemAI::npc_corrupted_lightning_totemAI(), npc_demonic_vaporAI::npc_demonic_vaporAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_feather_vortexAI::npc_feather_vortexAI(), npc_fire_nova_totemAI::npc_fire_nova_totemAI(), npc_kagani_nightstrikeAI::npc_kagani_nightstrikeAI(), npc_living_poisonAI::npc_living_poisonAI(), DarkFiendDummy::OnEffectExecute(), boss_thekalAI::OnRevive(), mob_phoenix_tkAI::OnSpellCooldownAdded(), SummonGargoyle::OnSummon(), CreatureEventAI::ProcessAction(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_razorgoreAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), boss_arlokkAI::ReceiveAIEvent(), boss_anzuAI::ReceiveAIEvent(), boss_silithidRoyaltyAI::ReceiveAIEvent(), boss_renatakiAI::ReceiveAIEvent(), boss_netherspiteAI::Reset(), boss_nightbaneAI::Reset(), boss_felblood_kaelthasAI::Reset(), boss_selin_fireheartAI::Reset(), mob_fel_crystalAI::Reset(), boss_apothecary_hummelAI::Reset(), boss_alythessAI::Reset(), boss_felmystAI::Reset(), boss_kiljaedenAI::Reset(), boss_zuljinAI::Reset(), boss_arlokkAI::Reset(), boss_renatakiAI::Reset(), boss_thekalAI::Reset(), boss_archimondeAI::Reset(), boss_ayamissAI::Reset(), boss_buruAI::Reset(), boss_eye_of_cthunAI::Reset(), boss_cthunAI::Reset(), boss_ouroAI::Reset(), boss_gothikAI::Reset(), boss_heiganAI::Reset(), boss_sapphironAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_leotheras_the_blindAI::Reset(), boss_the_lurker_belowAI::Reset(), boss_ahuneAI::Reset(), boss_gruulAI::Reset(), boss_warchief_kargath_bladefistAI::Reset(), mob_shadowmoon_soulstealerAI::Reset(), boss_alarAI::Reset(), boss_kaelthasAI::Reset(), npc_burster_wormAI::Reset(), boss_zuljinAI::SpellHit(), npc_saplingAI::SpellHit(), boss_maievAI::SpellHit(), boss_twin_emperorsAI::StartDelayedAttack(), boss_alarAI::StartPhaseTransition(), boss_skeramAI::StopAttacking(), boss_netherspiteAI::SwitchPhases(), boss_warchief_kargath_bladefistAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), and CreatureSettings::updateFlag().
SetMoveChaseParams()
void UnitAI::SetMoveChaseParams (float dist, float angle, bool moveFurther) inline
Definition at line 436 of file UnitAI.h.
References m_attackAngle, m_attackDistance, and m_moveFurther.
Referenced by boss_leotheras_the_blindAI::JustSummoned(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), and DancingRuneWeapon::OnSummon().
SetRangedMode()
void UnitAI::SetRangedMode (bool state, float distance, RangeModeType type)
Definition at line 997 of file UnitAI.cpp.
References Unit::IsInCombat(), m_attackDistance, m_chaseDistance, m_currentRangedMode, m_rangedMode, m_rangedModeSetting, m_unit, and SetCurrentRangedMode().
Referenced by boss_alythessAI::boss_alythessAI(), boss_aranAI::boss_aranAI(), boss_arugalAI::boss_arugalAI(), boss_bronjahmAI::boss_bronjahmAI(), boss_dorotheeAI::boss_dorotheeAI(), boss_eregosAI::boss_eregosAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_high_nethermancer_zerevorAI::boss_high_nethermancer_zerevorAI(), boss_kelesethAI::boss_kelesethAI(), boss_kiggler_the_crazedAI::boss_kiggler_the_crazedAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_krosh_firehandAI::boss_krosh_firehandAI(), boss_lady_malandeAI::boss_lady_malandeAI(), boss_lady_vashjAI::boss_lady_vashjAI(), boss_nexusprince_shaffarAI::boss_nexusprince_shaffarAI(), boss_omor_the_unscarredAI::boss_omor_the_unscarredAI(), boss_swamplord_muselekAI::boss_swamplord_muselekAI(), boss_telestraAI::boss_telestraAI(), boss_arugalAI::ExecuteAction(), GargoyleDeathKnightAI::GargoyleDeathKnightAI(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), mob_solarium_priestAI::mob_solarium_priestAI(), npc_ellrys_duskhallowAI::npc_ellrys_duskhallowAI(), npc_garaxxasAI::npc_garaxxasAI(), npc_magister_aledisAI::npc_magister_aledisAI(), npc_shartuulAI::npc_shartuulAI(), npc_yazzaiAI::npc_yazzaiAI(), CreatureEventAI::ProcessAction(), and boss_illidan_stormrageAI::Reset().
SetReactState()
void UnitAI::SetReactState (ReactStates st) inline
Definition at line 451 of file UnitAI.h.
References m_reactState.
Referenced by PlayerbotAI::_HandleCommandPet(), boss_muruAI::Aggro(), npc_warden_mellicharAI::Aggro(), mob_shadowmoon_soulstealerAI::Aggro(), VehicleInfo::ApplySeatMods(), boss_hadronoxAI::AttackedBy(), boss_ambassador_hellmawAI::boss_ambassador_hellmawAI(), boss_attumenAI::boss_attumenAI(), boss_croneAI::boss_croneAI(), boss_dorotheeAI::boss_dorotheeAI(), boss_entropiusAI::boss_entropiusAI(), boss_essence_of_angerAI::boss_essence_of_angerAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_maievAI::boss_maievAI(), boss_nefarianAI::boss_nefarianAI(), boss_rimefang_posAI::boss_rimefang_posAI(), boss_roarAI::boss_roarAI(), boss_strawmanAI::boss_strawmanAI(), boss_the_lurker_belowAI::boss_the_lurker_belowAI(), boss_tinheadAI::boss_tinheadAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), npc_theramore_spar_controller::CombatantSeparate(), CreatureAI::CreatureAI(), npc_rethhedronAI::DamageTaken(), npc_dirty_larryAI::DamageTaken(), npc_calvin_montagueAI::DamageTaken(), DarkFiendAI::DarkFiendAI(), npc_scrap_reaverAI::Die(), Spell::DoSummonPet(), Spell::EffectSummonPet(), Spell::EffectTameCreature(), boss_high_inquisitor_whitemaneAI::EnterCombat(), mob_shadowmoon_soulstealerAI::EnterEvadeMode(), essence_base_AI::essence_base_AI(), boss_heiganAI::ExecuteAction(), npc_magister_aledisAI::ExecuteAction(), boss_dorotheeAI::HandleAggro(), boss_attumenAI::HandleAttackDelay(), boss_kiljaedenAI::HandleAttackDelay(), npc_sinister_reflectionAI::HandleAttackDelay(), boss_entropiusAI::HandleAttackDelay(), DarkFiendAI::HandleAttackDelay(), boss_ahuneAI::HandleAttackDelay(), mob_phoenix_tkAI::HandleAttackDelay(), boss_nefarianAI::HandleAttackStart(), OuroScarab::HandleDelayedAttack(), boss_cthunAI::HandleEmerge(), npc_grand_collectorAI::HandleEvent(), boss_gothikAI::HandleGroundPhase(), boss_the_lurker_belowAI::HandleInitialAggro(), boss_felblood_kaelthasAI::HandleIntro(), npc_scrap_reaverAI::HandleKill(), WorldSession::HandlePetActionHelper(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_alarAI::HandleRebirth(), npc_singularityAI::HandleSpawn(), VehicleInfo::Initialize(), instance_blackrock_spire::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), CreatureEventAI::JustRespawned(), npc_singularityAI::JustRespawned(), npc_akama_illidanAI::JustRespawned(), npc_living_flareAI::JustRespawned(), npc_rethhedronAI::JustRespawned(), npc_shadowlord_deathwailAI::JustRespawned(), mob_shadowmoon_soulstealerAI::JustRespawned(), npc_highlord_darion_mograineAI::JustSummoned(), npc_time_riftAI::JustSummoned(), boss_taldaramAI::JustSummoned(), boss_jaraxxusAI::JustSummoned(), twin_jormungars_commonAI::JustSummoned(), boss_icehowlAI::JustSummoned(), boss_devourer_of_soulsAI::JustSummoned(), boss_malygosAI::JustSummoned(), boss_ormorokAI::JustSummoned(), boss_terestianAI::JustSummoned(), boss_felblood_kaelthasAI::JustSummoned(), npc_demonic_vaporAI::JustSummoned(), boss_kiljaedenAI::JustSummoned(), boss_muruAI::JustSummoned(), npc_portal_targetAI::JustSummoned(), boss_zuljinAI::JustSummoned(), boss_anetheronAI::JustSummoned(), boss_archimondeAI::JustSummoned(), boss_viscidusAI::JustSummoned(), boss_sladranAI::JustSummoned(), boss_krickAI::JustSummoned(), boss_rimefang_posAI::JustSummoned(), boss_xevozzAI::JustSummoned(), boss_anzuAI::JustSummoned(), boss_gurtogg_bloodboilAI::JustSummoned(), boss_illidan_stormrageAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_supremusAI::JustSummoned(), boss_terokkAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_kaelthasAI::JustSummoned(), mob_phoenix_tkAI::JustSummoned(), Pet::LoadPetFromDB(), MinionspawnerAI::MinionspawnerAI(), mob_ashtongue_channelerAI::mob_ashtongue_channelerAI(), mob_blood_elf_council_voice_triggerAI::mob_blood_elf_council_voice_triggerAI(), mob_hellfire_channelerAI::mob_hellfire_channelerAI(), mob_illidari_councilAI::mob_illidari_councilAI(), mob_netherweb_victimAI::mob_netherweb_victimAI(), mob_phoenix_tkAI::mob_phoenix_tkAI(), mob_soaring_eagleAI::mob_soaring_eagleAI(), mob_twilight_eggsAI::mob_twilight_eggsAI(), mob_water_globuleAI::mob_water_globuleAI(), MouthAI::MouthAI(), npc_shade_of_the_horsemanAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_hadronoxAI::MovementInform(), NetherCharge::NetherCharge(), npc_dirty_larryAI::NextStep(), npc_a_special_surpriseAI::npc_a_special_surpriseAI(), npc_advanced_target_dummyAI::npc_advanced_target_dummyAI(), npc_aether_tech_vendorAI::npc_aether_tech_vendorAI(), npc_amanishi_hatcherAI::npc_amanishi_hatcherAI(), npc_ancestral_wolfAI::npc_ancestral_wolfAI(), npc_annhyldeAI::npc_annhyldeAI(), npc_anubarak_trial_frostsphereAI::npc_anubarak_trial_frostsphereAI(), npc_aoe_damage_triggerAI::npc_aoe_damage_triggerAI(), npc_arcane_beamAI::npc_arcane_beamAI(), npc_bone_spikeAI::npc_bone_spikeAI(), npc_collapsing_icicleAI::npc_collapsing_icicleAI(), npc_concentrated_bulletAI::npc_concentrated_bulletAI(), npc_corrupted_soul_fragmentAI::npc_corrupted_soul_fragmentAI(), npc_cultist_engineer::npc_cultist_engineer(), npc_dark_matterAI::npc_dark_matterAI(), npc_darknessAI::npc_darknessAI(), npc_defias_traitorAI::npc_defias_traitorAI(), npc_demonic_vaporAI::npc_demonic_vaporAI(), npc_destructive_wardAI::npc_destructive_wardAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_doom_blossomAI::npc_doom_blossomAI(), npc_drijyaAI::npc_drijyaAI(), npc_eagle_trash_aggro_triggerAI::npc_eagle_trash_aggro_triggerAI(), npc_enslaved_soulAI::npc_enslaved_soulAI(), npc_fire_cycloneAI::npc_fire_cycloneAI(), npc_fire_nova_totemAI::npc_fire_nova_totemAI(), npc_flame_of_azzinothAI::npc_flame_of_azzinothAI(), npc_flame_tsunamiAI::npc_flame_tsunamiAI(), npc_grand_collectorAI::npc_grand_collectorAI(), npc_graufAI::npc_graufAI(), npc_gurubashi_bat_riderAI::npc_gurubashi_bat_riderAI(), npc_halion_controllerAI::npc_halion_controllerAI(), npc_hive_zara_larvaAI::npc_hive_zara_larvaAI(), npc_ingvar_throw_dummyAI::npc_ingvar_throw_dummyAI(), npc_jennyAI::npc_jennyAI(), npc_khadgars_servantAI::npc_khadgars_servantAI(), npc_krunAI::npc_krunAI(), npc_lakota_windsongAI::npc_lakota_windsongAI(), npc_laughing_skullAI::npc_laughing_skullAI(), npc_living_poisonAI::npc_living_poisonAI(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), npc_nether_vaporAI::npc_nether_vaporAI(), npc_ouro_moundAI::npc_ouro_moundAI(), npc_ouro_triggerAI::npc_ouro_triggerAI(), npc_paoka_swiftmountainAI::npc_paoka_swiftmountainAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), npc_planar_anomalyAI::npc_planar_anomalyAI(), npc_power_sparkAI::npc_power_sparkAI(), npc_reliquary_combat_triggerAI::npc_reliquary_combat_triggerAI(), npc_reliquary_LOS_aggro_triggerAI::npc_reliquary_LOS_aggro_triggerAI(), npc_scarlet_ghoulAI::npc_scarlet_ghoulAI(), npc_scrapped_fel_reaverAI::npc_scrapped_fel_reaverAI(), npc_shade_of_the_horsemanAI::npc_shade_of_the_horsemanAI(), npc_shadow_demonAI::npc_shadow_demonAI(), npc_shield_orbAI::npc_shield_orbAI(), npc_sinister_reflectionAI::npc_sinister_reflectionAI(), npc_skyguard_aether_techAI::npc_skyguard_aether_techAI(), npc_snakeWrapAI::npc_snakeWrapAI(), npc_soulgrinderAI::npc_soulgrinderAI(), npc_spawn_of_hydrossAI::npc_spawn_of_hydrossAI(), npc_stinky_ignatzAI::npc_stinky_ignatzAI(), npc_tenebron_egg_controllerAI::npc_tenebron_egg_controllerAI(), npc_time_riftAI::npc_time_riftAI(), npc_totem_of_spiritsAI::npc_totem_of_spiritsAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), instance_karazhan::OnCreatureRespawn(), instance_shadowfang_keep::OnCreatureRespawn(), instance_sunwell_plateau::OnCreatureRespawn(), instance_zulaman::OnCreatureRespawn(), instance_nexus::OnCreatureRespawn(), instance_utgarde_keep::OnCreatureRespawn(), instance_pinnacle::OnCreatureRespawn(), world_map_outland::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_trial_of_the_crusader::OnCreatureRespawn(), instance_pit_of_saron::OnCreatureRespawn(), instance_icecrown_citadel::OnCreatureRespawn(), instance_eye_of_eternity::OnCreatureRespawn(), instance_oculus::OnCreatureRespawn(), instance_ruby_sanctum::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), instance_violet_hold::OnCreatureRespawn(), spell_tag_troll::OnEffectExecute(), GluthDecimate::OnEffectExecute(), DarkFiendDummy::OnEffectExecute(), Bloodworm::OnSummon(), OuroScarab::OuroScarab(), QuestAccept_npc_dashel_stonefist(), boss_ambassador_hellmawAI::ReceiveAIEvent(), npc_akama_illidanAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), boss_leotheras_the_blindAI::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), npc_dawnblade_blood_knight::ReceiveAIEvent(), hyjalAI::ReceiveAIEvent(), VehicleInfo::RemoveSeatMods(), npc_ironhand_guardianAI::Reset(), boss_felblood_kaelthasAI::Reset(), mob_fel_crystalAI::Reset(), npc_dashel_stonefistAI::Reset(), boss_felmystAI::Reset(), boss_kiljaedenAI::Reset(), boss_muruAI::Reset(), npc_portal_targetAI::Reset(), npc_calvin_montagueAI::Reset(), npc_tapoke_slim_jahnAI::Reset(), npc_building_triggerAI::Reset(), npc_corrupted_furbolgAI::Reset(), npc_buru_eggAI::Reset(), boss_cthunAI::Reset(), boss_gothikAI::Reset(), boss_heiganAI::Reset(), boss_nothAI::Reset(), boss_reliquary_of_soulsAI::Reset(), npc_frequency_scanner::Reset(), boss_leotheras_the_blindAI::Reset(), boss_ahuneAI::Reset(), boss_magtheridonAI::Reset(), npc_fel_guard_houndAI::Reset(), npc_magister_aledisAI::Reset(), npc_zeppitAI::Reset(), StunField::Reset(), boss_alarAI::Reset(), npc_hungry_nether_rayAI::Reset(), guard_hallows_end_helperAI::Reset(), boss_alarAI::StartPhaseTransition(), npc_theramore_spar_controller::StartSparring(), boss_muruAI::SummonedMovementInform(), npc_creature_generatorAI::SummonedMovementInform(), npc_theramore_spar_controller::SwitchMembers(), Unit::TakeCharmOf(), Unit::TakePossessOf(), boss_strawmanAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_ambassador_hellmawAI::UpdateAI(), npc_spawn_of_hydrossAI::UpdateAI(), advisor_base_ai::UpdateAI(), npc_morokkAI::UpdateEscortAI(), npc_prospector_anvilwardAI::WaypointReached(), and npc_tapoke_slim_jahnAI::WaypointReached().
SpellHit()
virtual void UnitAI::SpellHit (Unit * , const SpellEntry *) inline virtual
Called when hit by a spell.
Parameters
pCaster Caster who casted the spell
pSpell The spell that hit the creature
Reimplemented in CreatureEventAI, TotemAI, boss_scarlet_commander_mograineAI, mob_mature_netherwing_drakeAI, npc_kyle_the_frenziedAI, npc_garments_of_questsAI, npc_injured_patientAI, mob_enslaved_netherwing_drakeAI, npc_warp_gate, mobs_nether_drakeAI, boss_aerial_unitAI, npc_iron_constructAI, boss_ignisAI, boss_malygosAI, blood_prince_council_baseAI, boss_tethyrAI, npc_rabid_bearAI, npc_draenei_survivorAI, mobs_spitelashesAI, mob_restless_soulAI, mob_yennikuAI, npc_dorius_stonetenderAI, npc_image_arcanagosAI, npc_image_of_medivhAI, npc_chess_piece_genericAI, boss_romuloAI, boss_plugger_spazzringAI, NecroticShard, advisor_base_ai, boss_nothAI, boss_ossirianAI, npc_frostbiteAI, npc_disobedient_dragonmaw_peonAI, npc_scrapped_fel_reaverAI, npc_evergrove_druidAI, boss_drakkari_colossusAI, npc_taskmaster_fizzuleAI, npc_forest_frogAI, NecropolisProxyAI, boss_maievAI, ScourgeMinion, NecropolisRelayAI, NecropolisHealthAI, NecropolisAI, npc_aged_dying_ancient_kodoAI, boss_kaelthasAI, boss_alarAI, npc_living_flareAI, boss_magtheridonAI, boss_najentusAI, boss_faerlinaAI, boss_veklorAI, npc_portal_targetAI, mob_fireswornAI, boss_garrAI, mob_fel_crystalAI, boss_attumenAI, npc_blackwing_orbAI, npc_buru_eggAI, npc_mojoAI, guardAI_stormwind, npc_saplingAI, boss_shade_of_akamaAI, boss_essence_of_angerAI, boss_razuviousAI, boss_kelthuzadAI, boss_zuljinAI, boss_halazziAI, npc_void_conduitAI, npc_energy_ballAI, boss_ahuneAI, boss_fathomlord_karathressAI, npc_fel_cannon, npc_ominous_cloudAI, npc_thunder_orbAI, npc_runic_colossusAI, boss_thorimAI, boss_vx001AI, boss_leviathan_mk2AI, three_nature_alliesAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, npc_dark_matterAI, mob_molten_golemAI, boss_uromAI, boss_trollgoreAI, boss_anubarak_trialAI, npc_artoriusAI, npc_ranshallaAI, npc_simone_seductressAI, npc_ringoAI, npc_solenorAI, boss_onyxiaAI, npc_private_hendelAI, npc_rizzle_sprysprocketAI, mobs_spectral_ghostly_citizenAI, boss_headless_horsemanAI, and npc_klinfranAI.
Definition at line 241 of file UnitAI.h.
Referenced by Spell::DoAllEffectOnTarget().
SpellHitTarget() [1/2]
virtual void UnitAI::SpellHitTarget (Unit * , const SpellEntry *) inline virtual
Reimplemented in NecropolisHealthAI, boss_warchief_kargath_bladefistAI, npc_feather_vortexAI, boss_zuljinAI, npc_amanishi_hatcherAI, npc_burster_wormAI, boss_kaelthasAI, npc_dreadmawAI, mob_water_globuleAI, boss_leotheras_the_blindAI, dummy_blackheart_the_inciterAI, boss_malacrassAI, boss_brutallusAI, boss_soccothratesAI, npc_kaylaan_the_lostAI, boss_swamplord_muselekAI, boss_grobbulusAI, boss_ouroAI, CreatureEventAI, npc_netherspite_portalAI, boss_kiggler_the_crazedAI, npc_spirit_guide_wintergraspAI, npc_black_knight_ghoulAI, npc_spirit_guideAI, npc_shadowlord_deathwailAI, boss_heart_deconstructorAI, npc_runic_colossusAI, boss_thorimAI, npc_focused_eyebeamAI, boss_flame_leviathanAI, npc_black_holeAI, npc_worm_holeAI, boss_bronjahmAI, npc_jaina_sylvanas_horAI, boss_lich_king_horAI, boss_icehowlAI, boss_dreadscaleAI, boss_acidmawAI, boss_lethonAI, npc_demoniac_scryerAI, boss_exarch_maladaarAI, npc_voice_yogg_saronAI, boss_general_vezaxAI, boss_brundirAI, npc_fire_cycloneAI, npc_collapsing_icicleAI, boss_volazjAI, boss_onyxiaAI, npc_rizzle_sprysprocketAI, npc_ashliAI, NecroticShard, NecropolisProxyAI, NecropolisRelayAI, boss_devourer_of_soulsAI, boss_marliAI, boss_gruulAI, and npc_nagrand_captiveAI.
Definition at line 249 of file UnitAI.h.
SpellHitTarget() [2/2]
virtual void UnitAI::SpellHitTarget (Unit * target, const SpellEntry * spellInfo, SpellMissInfo) inline virtual
Called when spell hits creature's target.
Parameters
pTarget Target that we hit with the spell
pSpell Spell with which we hit pTarget
Reimplemented in boss_moorabiAI, npc_buru_eggAI, boss_buruAI, boss_ragnarosAI, boss_flamegorAI, boss_firemawAI, and boss_ebonrocAI.
Definition at line 248 of file UnitAI.h.
References SpellHitTarget().
Referenced by Spell::DoAllEffectOnTarget(), and SpellHitTarget().
SpellListChanged()
void UnitAI::SpellListChanged ()
Definition at line 1178 of file UnitAI.cpp.
References AddInitialCooldowns(), AddMainSpell(), CreatureSpellList::Disabled, GetSpellList(), Unit::IsInCombat(), m_mainAttackMask, m_mainSpellCost, m_mainSpellId, m_mainSpellInfo, m_mainSpellMinRange, m_mainSpells, m_spellListCooldown, m_unit, SPELL_LIST_FLAG_RANGED_ACTION, SPELL_SCHOOL_MASK_NONE, and CreatureSpellList::Spells.
Referenced by Creature::SetSpellList().
SummonedCreatureDespawn()
virtual void UnitAI::SummonedCreatureDespawn (Creature *) inline virtual
Called when a summoned creature gets TemporarySummon::UnSummon ed.
Parameters
pSummoned Summoned creature that despawned
Reimplemented in PallidHorrorAI, npc_scrapped_fel_reaverAI, boss_lady_vashjAI, boss_xevozzAI, boss_anubrekhanAI, npc_daphne_stilwellAI, boss_brutallusAI, npc_squire_roweAI, npc_apprentice_mirvedaAI, boss_coren_direbrewAI, CreatureEventAI, npc_soulgrinderAI, npc_teleportation_portalAI, boss_taldaramAI, npc_time_riftAI, npc_agent_proudwell, boss_thermapluggAI, boss_cthunAI, and mob_anubisath_guardianAI.
Definition at line 234 of file UnitAI.h.
Referenced by TemporarySpawn::UnSummon().
SummonedCreatureJustDied()
virtual void UnitAI::SummonedCreatureJustDied (Creature *) inline virtual
Called when a summoned creature is killed.
Parameters
pSummoned Summoned Creature* that got killed
Reimplemented in PallidHorrorAI, npc_commanderAI, npc_scrapped_fel_reaverAI, boss_lady_vashjAI, boss_reliquary_of_soulsAI, npc_blade_of_azzinothAI, boss_anzuAI, boss_ichoronAI, npc_ethereal_frostworgAI, boss_loathebAI, boss_gothikAI, boss_viscidusAI, boss_fankrissAI, boss_cthunAI, boss_moamAI, npc_keeper_remulosAI, boss_anetheronAI, boss_mandokirAI, boss_akilzonAI, npc_daphne_stilwellAI, boss_kiljaedenAI, npc_kiljaeden_controllerAI, boss_brutallusAI, boss_ragnarosAI, boss_majordomoAI, boss_priestess_delrissaAI, boss_terestianAI, boss_nightbaneAI, CreatureEventAI, boss_taerarAI, npc_fhwoorAI, boss_high_botanist_freywinnAI, npc_dimensiusAI, npc_colonel_julesAI, boss_ahuneAI, npc_soulgrinderAI, npc_shaheenAI, npc_teleportation_portalAI, npc_prison_event_controllerAI, npc_brain_yogg_saronAI, boss_kologarnAI, boss_freyaAI, boss_algalonAI, mob_vesperonAI, mob_shadronAI, boss_varosAI, boss_anomalusAI, npc_putricides_trapAI, boss_lady_deathwhisperAI, boss_lich_king_horAI, npc_emilyAI, npc_harrison_jonesAI, boss_novosAI, npc_beast_combat_stalkerAI, boss_paletressAI, mob_ahnkahar_eggAI, boss_jedogaAI, boss_amanitarAI, npc_twiggy_flatheadAI, npc_anachronos_the_ancientAI, npc_areiAI, npc_captured_arkonarinAI, npc_thrall_old_hillsbradAI, npc_time_riftAI, npc_arthasAI, npc_feero_ironhandAI, npc_miranAI, boss_dorotheeAI, npc_blastmaster_emi_shortfuseAI, npc_eris_havenfireAI, npc_apprentice_mirvedaAI, npc_regthar_deathgateAI, npc_lord_illidan_stormrageAI, mob_phoenix_tkAI, boss_fathomguard_sharkkisAI, npc_disciple_of_naralexAI, boss_malacrassAI, npc_deathstalker_faerleiaAI, npc_infused_crystalAI, npc_grark_lorkrubAI, and npc_grimstoneAI.
Definition at line 204 of file UnitAI.h.
Referenced by Unit::JustKilledCreature().
SummonedJustReachedHome()
virtual void UnitAI::SummonedJustReachedHome (Creature *) inline virtual
Called at reaching home after MoveTargetedHome.
Reimplemented in npc_adyen_the_lightwardenAI, boss_maexxnaAI, and npc_keeper_remulosAI.
Definition at line 163 of file UnitAI.h.
SummonedMovementInform()
virtual void UnitAI::SummonedMovementInform (Creature * , uint32 , uint32) inline virtual
Called if a temporary summoned of m_creature reach a move point.
Parameters
pSummoned Summoned Creature that finished some movement
uiMotionType Type of the movement (enum MovementGeneratorType)
uiData Data related to the finished movement (ie point-id)
Reimplemented in npc_totem_of_spiritsAI, npc_shattered_hand_legionnaire, npc_taelan_fordringAI, boss_eranikusAI, npc_keeper_remulosAI, boss_reliquary_of_soulsAI, boss_illidan_stormrageAI, npc_adyen_the_lightwardenAI, boss_the_lurker_belowAI, boss_kelthuzadAI, boss_viscidusAI, npc_kiljaeden_controllerAI, boss_brutallusAI, npc_reginald_windsorAI, npc_squire_roweAI, npc_scrapped_fel_reaverAI, boss_lady_vashjAI, boss_terokkAI, npc_creature_generatorAI, npc_akamaAI, npc_daphne_stilwellAI, boss_muruAI, npc_xiri, npc_dorius_stonetenderAI, boss_varosAI, npc_emilyAI, boss_jedogaAI, npc_ranshallaAI, npc_anachronos_the_ancientAI, npc_thrall_old_hillsbradAI, boss_flame_leviathanAI, npc_twiggy_flatheadAI, boss_onyxiaAI, npc_shaheenAI, npc_prison_event_controllerAI, boss_skadiAI, npc_putricides_trapAI, npc_crystal_channel_targetAI, trial_companion_commonAI, npc_time_riftAI, npc_image_of_medivhAI, boss_thermapluggAI, npc_eris_havenfireAI, and npc_manaforge_control_consoleAI.
Definition at line 275 of file UnitAI.h.
TimedFleeingEnded()
void UnitAI::TimedFleeingEnded () virtual
Reimplemented in CreatureAI.
Definition at line 825 of file UnitAI.cpp.
References DoStartMovement(), GetAIOrder(), Unit::GetVictim(), Unit::IsAlive(), m_unit, ORDER_FLEEING, ORDER_NONE, SetAIOrder(), and SetCombatScriptStatus().
Referenced by PanicMovementGenerator::Finalize(), PanicMovementGenerator::Interrupt(), and CreatureAI::TimedFleeingEnded().
UpdateAI()
void UnitAI::UpdateAI (const uint32 diff) virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented in NecropolisRelayAI, NecropolisProxyAI, NecropolisAI, ScourgeMinion, NecropolisHealthAI, npc_warlock_mount_ritualAI, npc_guardianAI, npc_frostbiteAI, npc_saplingAI, npc_veneratus_spawn_nodeAI, mob_shadowmoon_soulstealerAI, npc_manaforge_spawnAI, npc_Shattered_Hand_Scout, mob_naga_distillerAI, mob_steamrigger_mechanicAI, npc_ice_spear_bunnyAI, npc_frozen_coreAI, mob_enchanted_elementalAI, npc_simon_game_bunnyAI, mob_ashtongue_sorcererAI, boss_shade_of_akamaAI, npc_blade_of_azzinothAI, npc_shadow_demonAI, npc_cage_trap_triggerAI, dummy_blackheart_the_inciterAI, npc_charged_sphereAI, npc_keeper_thorimAI, npc_xt_toy_pileAI, npc_harpoon_fire_stateAI, npc_computerAI, boss_leviathan_mk2_turretAI, npc_rocket_strikeAI, npc_rubble_stalkerAI, npc_focused_eyebeamAI, npc_scorchAI, npc_iron_constructAI, npc_icicle_targetAI, npc_flash_freezeAI, npc_healthy_sporeAI, npc_iron_rootsAI, npc_hodir_furyAI, npc_collapsing_starAI, npc_black_holeAI, boss_valithria_dreamwalkerAI, npc_puddle_stalkerAI, npc_choking_gas_bombAI, npc_growing_ooze_puddleAI, npc_orange_gas_stalkerAI, npc_kinetic_bombAI, npc_ball_of_flameAI, npc_crystal_channel_targetAI, npc_dalaran_guardian_mageAI, npc_black_knight_gryphonAI, npc_twilight_volunteerAI, npc_amanitar_mushroomAI, npc_buru_eggAI, npc_hive_zara_larvaAI, npc_time_riftAI, npc_medivh_black_morassAI, npc_power_blue_flightAI, boss_head_of_horsemanAI, npc_image_arcanagosAI, npc_grandmotherAI, npc_shattered_sun_warriorAI, npc_shattered_sun_fighterAI, npc_spirit_guideAI, PossessedAI, NullCreatureAI, npc_mage_mirror_imageAI, npc_the_cleanerAI, npc_redemption_targetAI, npc_spring_rabbitAI, npc_injured_patientAI, npc_doctorAI, npc_chicken_cluckAI, guard_shattrath_scryerAI, guard_shattrath_aldorAI, npc_spirit_shadeAI, boss_emerald_dragonAI, npc_cooshcooshAI, npc_minion_of_terokkAI, npc_avatar_of_terokkAI, npc_cenarion_sparrowhawkAI, npc_hungry_nether_rayAI, mob_unkor_the_ruthlessAI, mob_nether_wraithAI, boss_pathaleon_the_calculatorAI, npc_raging_flamesAI, boss_nethermancer_sepethreaAI, boss_master_engineer_telonicusAI, boss_grand_astromancer_capernianAI, boss_lord_sanguinarAI, boss_thaladred_the_darkenerAI, advisor_base_ai, boss_kaelthasAI, boss_warp_splinterAI, boss_lajAI, boss_high_botanist_freywinnAI, boss_soccothratesAI, boss_harbinger_skyrissAI, boss_dalliahAI, npc_arcatraz_defenderAI, npc_warden_mellicharAI, npc_millhouse_manastormAI, npc_salsalabimAI, mob_bt_battle_fighterAI, npc_domesticated_felboarAI, npc_spawned_oronok_tornheartAI, npc_shadowlord_deathwailAI, npc_lord_illidan_stormrageAI, npc_dragonmaw_peonAI, mob_enslaved_netherwing_drakeAI, mob_mature_netherwing_drakeAI, npc_void_conduitAI, npc_energy_ballAI, npc_salhadaarAI, npc_dimensiusAI, npc_saeed_escortAI, npc_commander_dawnforgeAI, npc_manaforge_control_consoleAI, npc_rethhedronAI, mob_lumpAI, npc_credit_marker_they_must_burnAI, npc_nazgrelAI, npc_danath_trollbaneAI, npc_living_flareAI, npc_anchorite_baradaAI, npc_colonel_julesAI, npc_fel_guard_houndAI, npc_demoniac_scryerAI, npc_aeranasAI, boss_warchief_kargath_bladefistAI, boss_warbringer_omroggAI, mob_omrogg_headsAI, mob_fel_orc_convertAI, boss_grand_warlock_nethekurseAI, mob_underbog_mushroomAI, boss_mekgineer_steamriggerAI, boss_thespiaAI, npc_inner_demonAI, npc_spawn_of_hydrossAI, boss_hydross_the_unstableAI, boss_fathomguard_caribdisAI, boss_fathomlord_karathressAI, boss_doomwalkerAI, boss_doomlordkazzakAI, npc_evergrove_druidAI, npc_supplicantAI, npc_soulgrinderAI, npc_warp_gate, npc_fel_cannon, npc_frequency_scanner, npc_bloodmaul_dire_wolfAI, npc_bird_spiritAI, npc_vimgol_middle_bunnyAI, npc_vimgol_visual_bunnyAI, npc_vimgol_AI, npc_obelisk_triggerAI, npc_light_orb_collectorAI, npc_bloodmaul_stout_triggerAI, mobs_nether_drakeAI, mob_ashtongue_channelerAI, boss_murmurAI, npc_void_travelerAI, boss_grandmaster_vorpilAI, boss_ambassador_hellmawAI, boss_darkweaver_sythAI, boss_pandemoniusAI, boss_exarch_maladaarAI, mob_stolen_soulAI, npc_decaying_ghoulAI, npc_ghoul_feeding_bunnyAI, npc_spirit_guide_wintergraspAI, npc_teleportation_portalAI, boss_ymironAI, npc_graufAI, mob_vrykul_skeletonAI, npc_ingvar_throw_dummyAI, npc_annhyldeAI, npc_storm_tempered_keeperAI, npc_keeper_mimironAI, npc_death_rayAI, npc_ominous_cloudAI, npc_immortal_guardianAI, npc_guardian_of_yoggAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, boss_yogg_saronAI, boss_saraAI, boss_heart_deconstructorAI, boss_xt_002AI, npc_thunder_orbAI, npc_runic_colossusAI, boss_sifAI, boss_thorimAI, npc_razorscale_spawnerAI, npc_expedition_commanderAI, boss_razorscaleAI, npc_frost_bombAI, npc_mimiron_flamesAI, npc_bot_triggerAI, npc_proximity_mineAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_mimironAI, boss_kologarnAI, boss_ignisAI, boss_hodirAI, boss_general_vezaxAI, npc_nature_bombAI, npc_eonars_giftAI, npc_storm_lasherAI, npc_water_spiritAI, boss_freyaAI, npc_mimiron_infernoAI, npc_freya_wardAI, npc_hodir_fury_reticleAI, boss_flame_leviathanAI, boss_feral_defenderAI, boss_auriayaAI, npc_worm_holeAI, npc_living_constellationAI, boss_algalonAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, npc_dark_matterAI, npc_brann_hosAI, mob_molten_golemAI, boss_volkhanAI, boss_lokenAI, boss_ionarAI, mob_stormforged_lieutenantAI, boss_bjarngrimAI, npc_tipsy_mcmanusAI, boss_savianaAI, npc_orb_carrierAI, npc_meteor_strike_initialAI, npc_halion_controllerAI, boss_halion_twilightAI, boss_halion_realAI, npc_tenebron_egg_controllerAI, mob_twilight_eggsAI, dummy_dragonAI, boss_sartharionAI, boss_varosAI, boss_uromAI, npc_planar_anomalyAI, boss_malygosAI, npc_web_wrapAI, npc_putricides_trapAI, boss_the_lich_king_iccAI, mob_frost_bombAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, mob_big_oozeAI, mob_little_oozeAI, boss_rotfaceAI, npc_gas_cloud_iccAI, npc_volatile_ooze_iccAI, boss_professor_putricideAI, npc_bone_spikeAI, boss_lord_marrowgarAI, boss_festergutAI, boss_blood_queen_lanathelAI, boss_taldaram_iccAI, boss_keleseth_iccAI, boss_valanar_iccAI, blood_prince_council_baseAI, npc_blood_orb_controlAI, npc_dark_nucleusAI, npc_collapsing_icicleAI, npc_jaina_sylvanas_horAI, boss_lich_king_horAI, boss_devourer_of_soulsAI, npc_grand_admiral_westwindAI, npc_infantryAI, npc_firecrackers_bunnyAI, npc_king_ymironAI, npc_lich_king_villageAI, npc_silvermoon_harryAI, npc_ancient_male_vrykulAI, boss_trollgoreAI, boss_tharonjaAI, boss_novosAI, npc_destructive_wardAI, boss_eydisAI, boss_fjolaAI, boss_icehowlAI, twin_jormungars_commonAI, boss_gormokAI, npc_beast_combat_stalkerAI, boss_jaraxxusAI, trial_crusader_commonAI, npc_anubarak_trial_frostsphereAI, npc_anubarak_trial_spikeAI, boss_anubarak_trialAI, npc_champion_mountAI, npc_trial_grand_championAI, trial_companion_commonAI, npc_black_knight_ghoulAI, boss_black_knightAI, boss_paletressAI, boss_eadricAI, npc_seaforium_depth_chargeAI, npc_sinkhole_kill_creditAI, npc_oil_stained_wolfAI, npc_nesingwary_trapperAI, npc_impale_targetAI, boss_anubarakAI, boss_volazjAI, boss_taldaramAI, boss_nadoxAI, boss_jedogaAI, boss_amanitarAI, boss_zumrahAI, npc_artoriusAI, npc_simone_the_inconspicuousAI, npc_simone_seductressAI, npc_precious_the_devourerAI, npc_plucky_johnsonAI, npc_twiggy_flatheadAI, mob_aquementasAI, npc_solenorAI, npc_anachronos_the_ancientAI, mob_anubisath_guardianAI, npc_snufflenose_gopherAI, boss_onyxiaAI, npc_smolderwing, boss_tethyrAI, mob_invis_firework_helper, npc_restless_apparitionAI, mobs_risen_husk_spiritAI, npc_lazy_peonAI, npc_magrami_spectre, npc_rabid_bearAI, npc_thrall_old_hillsbradAI, npc_doomfire_targetingAI, boss_chrono_lord_dejaAI, boss_aeonusAI, npc_draenei_survivorAI, boss_mawsAI, npc_felhound_trackerAI, mobs_spitelashesAI, example_creatureAI, npc_soulflayerAI, boss_archaedasAI, npc_calvin_montagueAI, npc_shadow_imageAI, npc_malfurionAI, mobs_spectral_ghostly_citizenAI, mob_restless_soulAI, boss_silver_hand_bossesAI, boss_maleki_the_pallidAI, boss_dathrohan_balnazzarAI, boss_cannon_master_willeyAI, boss_baroness_anastariAI, mob_yennikuAI, npc_dashel_stonefistAI, npc_deathstalker_faerleiaAI, npc_valentine_boss_managerAI, npc_spectral_tutorAI, boss_jandicebarovAI, boss_darkmaster_gandlingAI, boss_herodAI, boss_headless_horsemanAI, boss_arcanist_doanAI, npc_scarlet_courierAI, npc_scarlet_ghoulAI, npc_eye_of_acherusAI, npc_a_special_surpriseAI, npc_chess_piece_genericAI, npc_echo_of_medivhAI, boss_romuloAI, boss_julianneAI, boss_bigbadwolfAI, boss_croneAI, boss_roarAI, boss_tinheadAI, boss_strawmanAI, npc_fiendish_portalAI, npc_netherspite_portalAI, npc_converted_sentryAI, boss_thermapluggAI, npc_infused_crystalAI, npc_apprentice_mirvedaAI, npc_kelerun_bloodmournAI, npc_eris_havenfireAI, boss_mr_smiteAI, npc_klinfranAI, npc_blackwing_orbAI, npc_rookery_hatcherAI, boss_pyroguard_emberseerAI, boss_overlordwyrmthalakAI, boss_gythAI, boss_high_interrogator_gerstahnAI, boss_general_angerforgeAI, boss_moira_bronzebeardAI, boss_emperor_dagran_thaurissanAI, boss_ambassador_flamelashAI, boss_plugger_spazzringAI, npc_mistress_nagmaraAI, npc_queen_lanathel_introAI, npc_scourged_flamespitterAI, npc_regthar_deathgateAI, npc_image_of_medivhAI, npc_headless_horseman_fireAI, npc_shade_of_the_horsemanAI, npc_orphanAI, npc_xiri, npc_imp_in_a_ball, npc_advanced_target_dummyAI, npc_mojoAI, npc_snakesAI, generic_creatureAI, guardAI_stormwind, guard_hallows_end_helperAI, npc_brewfest_barker, boss_highlord_kruulAI, boss_mechano_lord_capacitusAI, boss_thorngrinAI, npc_dirty_larryAI, npc_bt_battle_sensor, npc_dragonmaw_racerAI, npc_commanderAI, npc_disobedient_dragonmaw_peonAI, npc_totem_of_spiritsAI, npc_kaylaan_the_lostAI, npc_adyen_the_lightwardenAI, npc_scrap_reaverAI, npc_vindicator_sedaiAI, boss_warlord_kalithreshAI, mob_water_globuleAI, npc_apexis_flayerAI, mob_blood_elf_council_voice_triggerAI, npc_shadow_constructAI, npc_creature_generatorAI, npc_akamaAI, boss_maievAI, npc_akama_illidanAI, boss_illidan_stormrageAI, npc_bonechewer_combatant, npc_grand_collectorAI, npc_bashir_flesh_fiendAI, npc_anzu_bird_spiritAI, boss_anzuAI, npc_ethereum_prisoner_dungeonAI, boss_yorAI, boss_baltharusAI, boss_telestraAI, npc_taskmaster_fizzuleAI, npc_general_andorovAI, npc_kyle_the_frenziedAI, boss_eranikusAI, boss_noxxionAI, npc_aged_dying_ancient_kodoAI, npc_bartolo_ginsetti, boss_archimondeAI, npc_amanishi_scoutAI, npc_ashliAI, npc_krazAI, npc_tanzarAI, npc_harkorAI, npc_amanishi_tempestAI, npc_forest_frogAI, npc_amanishi_hatcherAI, npc_corrupted_lightning_totemAI, mob_soaring_eagleAI, npc_portal_targetAI, boss_kiljaedenAI, npc_kiljaeden_controllerAI, boss_alythessAI, boss_brutallusAI, npc_deathstalker_vincentAI, npc_highlord_darion_mograineAI, npc_death_knight_initiateAI, mob_arcane_sphereAI, npc_shattered_sun_marksmanAI, boss_kazzakAI, boss_victor_nefariusAI, npc_ironhand_guardianAI, ScriptedPetAI, guardAI, FollowerAI, npc_escortAI, TotemAI, PetAI, GuardianAI, GuardAI, npc_scrapped_fel_reaverAI, and npc_skyguard_rangerAI.
Definition at line 1107 of file UnitAI.cpp.
References CanExecuteCombatAction(), Unit::CanReachWithMeleeAttack(), DistanceYourself(), DoMeleeAttackIfReady(), ExecuteActions(), GENERIC_ACTION_DISTANCE, Unit::GetVictim(), Unit::hasUnitState(), IsCombatMovement(), IsEligibleForDistancing(), Unit::IsImmobilizedState(), Unit::IsInCombat(), IsMainSpellPrevented(), m_currentRangedMode, m_distancingCooldown, m_mainSpellInfo, m_meleeEnabled, m_rangedMode, m_rangedModeSetting, m_unit, Unit::MeleeAttackStart(), Unit::MeleeAttackStop(), CombatActions::ResetTimer(), Unit::SelectHostileTarget(), SetCurrentRangedMode(), TYPE_DISTANCER, TYPE_PROXIMITY, UNIT_STAT_MELEE_ATTACKING, UpdateEventTimers(), UpdateSpellLists(), and CombatActions::UpdateTimers().
Referenced by Unit::Update(), GuardianAI::UpdateAI(), boss_victor_nefariusAI::UpdateAI(), npc_death_knight_initiateAI::UpdateAI(), npc_highlord_darion_mograineAI::UpdateAI(), npc_deathstalker_vincentAI::UpdateAI(), boss_brutallusAI::UpdateAI(), boss_alythessAI::UpdateAI(), boss_kiljaedenAI::UpdateAI(), npc_general_andorovAI::UpdateAI(), boss_telestraAI::UpdateAI(), boss_baltharusAI::UpdateAI(), npc_bonechewer_combatant::UpdateAI(), boss_illidan_stormrageAI::UpdateAI(), npc_akama_illidanAI::UpdateAI(), boss_maievAI::UpdateAI(), npc_creature_generatorAI::UpdateAI(), mob_water_globuleAI::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), npc_xiri::UpdateAI(), npc_danath_trollbaneAI::UpdateAI(), npc_nazgrelAI::UpdateAI(), NecropolisHealthAI::UpdateAI(), ScourgeMinion::UpdateAI(), and npc_escortAI::UpdateEscortAI().
UpdateEventTimers()
virtual void UnitAI::UpdateEventTimers (const uint32) inline virtual
Reimplemented in CreatureEventAI.
Definition at line 505 of file UnitAI.h.
Referenced by UpdateAI().
UpdateSpellLists()
void UnitAI::UpdateSpellLists ()
Definition at line 1204 of file UnitAI.cpp.
References CalculateSpellRange(), CanCastSpell(), CAST_OK, CreatureSpellList::ChanceRangedAttack, CreatureSpellList::ChanceSupportAction, ChooseTarget(), CreatureSpellListSpell::CombatCondition, CreatureSpellListSpell::DisabledForAI, DoCastSpellIfCan(), CreatureSpellListSpell::Flags, GENERIC_ACTION_SPELL_LIST, GetCurrentRangedMode(), WorldObject::GetMap(), GetRandomGenerator(), GetSpellList(), Unit::IsInCombat(), WorldObject::IsSpellReady(), SQLStorage::LookupEntry(), m_spellListCooldown, m_unit, OnSpellCast(), CreatureSpellListSpell::Probability, CombatActions::ResetTimer(), SCRIPT_TYPE_RELAY, CreatureSpellListSpell::ScriptId, Map::ScriptsStart(), sObjectMgr, SPELL_LIST_FLAG_RANGED_ACTION, SPELL_LIST_FLAG_SUPPORT_ACTION, CreatureSpellListSpell::SpellId, CreatureSpellList::Spells, sSpellTemplate, CreatureSpellListSpell::Target, and urand().
Referenced by UpdateAI().
Field Documentation
m_attackAngle
float UnitAI::m_attackAngle protected
Definition at line 582 of file UnitAI.h.
Referenced by boss_lady_vashjAI::DoInformGeneratorStopped(), DoStartMovement(), ScriptedAI::DoStartMovement(), boss_moroesAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), HandleMovementOnAttackStart(), PetAI::PetAI(), CreatureEventAI::ProcessAction(), boss_moroesAI::ReceiveAIEvent(), boss_kaelthasAI::Reset(), SetMoveChaseParams(), and boss_grand_astromancer_capernianAI::UpdateAI().
m_attackDistance
float UnitAI::m_attackDistance protected
How should an enemy be chased.
Definition at line 581 of file UnitAI.h.
Referenced by boss_champion_mageAI::AttackStart(), boss_champion_hunterAI::AttackStart(), boss_lady_vashjAI::DoInformGeneratorStopped(), DoStartMovement(), ScriptedAI::DoStartMovement(), boss_leotheras_the_blindAI::ExecuteAction(), boss_kaelthasAI::ExecuteActions(), GetAttackDistance(), HandleMovementOnAttackStart(), boss_leotheras_the_blindAI::HandlePhaseTransition(), npc_commanderAI::npc_commanderAI(), npc_millhouse_manastormAI::npc_millhouse_manastormAI(), boss_lady_malandeAI::OnSpellCooldownAdded(), boss_lady_malandeAI::OnSpellInterrupt(), PetAI::PetAI(), CreatureEventAI::ProcessAction(), boss_maievAI::ReceiveAIEvent(), CreatureAI::Reset(), CreatureEventAI::Reset(), boss_moira_bronzebeardAI::Reset(), boss_felblood_kaelthasAI::Reset(), boss_veklorAI::Reset(), boss_zumrahAI::Reset(), npc_scourged_flamespitterAI::Reset(), npc_trial_grand_championAI::Reset(), npc_champion_mountAI::Reset(), boss_crusader_druid_restoAI::Reset(), boss_crusader_paladin_holyAI::Reset(), boss_crusader_priest_discAI::Reset(), boss_crusader_shaman_restoAI::Reset(), boss_crusader_druid_balanceAI::Reset(), boss_crusader_hunterAI::Reset(), boss_crusader_mageAI::Reset(), boss_crusader_priest_shadowAI::Reset(), boss_crusader_warlockAI::Reset(), npc_dark_nucleusAI::Reset(), boss_keleseth_iccAI::Reset(), boss_leotheras_the_blindAI::Reset(), npc_rethhedronAI::Reset(), npc_wildaAI::Reset(), boss_kaelthasAI::Reset(), boss_grand_astromancer_capernianAI::Reset(), SetCurrentRangedMode(), SetMoveChaseParams(), SetRangedMode(), npc_trial_grand_championAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), and boss_grand_astromancer_capernianAI::UpdateAI().
m_chaseDistance
float UnitAI::m_chaseDistance protected
Definition at line 608 of file UnitAI.h.
Referenced by CreatureAI::Reset(), CreatureEventAI::Reset(), SetCurrentRangedMode(), and SetRangedMode().
m_chaseRun
bool UnitAI::m_chaseRun protected
Definition at line 584 of file UnitAI.h.
Referenced by DoStartMovement(), and CreatureEventAI::ProcessAction().
m_combatMovementStarted
bool UnitAI::m_combatMovementStarted protected
Definition at line 589 of file UnitAI.h.
m_combatOnlyRoot
bool UnitAI::m_combatOnlyRoot protected
Definition at line 594 of file UnitAI.h.
Referenced by ClearCombatOnlyRoot(), and SetAIImmobilizedState().
m_combatScriptHappening
bool UnitAI::m_combatScriptHappening protected
Definition at line 598 of file UnitAI.h.
Referenced by CanCastSpell(), CanExecuteCombatAction(), npc_kaylaan_the_lostAI::ExecuteActions(), GetCombatScriptStatus(), and SetCombatScriptStatus().
m_currentAIOrder
AIOrders UnitAI::m_currentAIOrder protected
Definition at line 599 of file UnitAI.h.
Referenced by GetAIOrder(), and SetAIOrder().
m_currentRangedMode
bool UnitAI::m_currentRangedMode protected
Definition at line 609 of file UnitAI.h.
Referenced by CreatureEventAI::CheckEvent(), DistancingEnded(), CreatureEventAI::GetAIInformation(), GetCurrentRangedMode(), GetMainAttackSchoolMask(), HandleSpellCastResult(), IsRangedUnit(), CreatureAI::Reset(), CreatureEventAI::Reset(), SetCurrentRangedMode(), SetRangedMode(), and UpdateAI().
m_currentSpell
Spell const* UnitAI::m_currentSpell protected
Definition at line 601 of file UnitAI.h.
Referenced by OnChannelStateChange(), and OnSpellCastStateChange().
m_dismountOnAggro
bool UnitAI::m_dismountOnAggro protected
Definition at line 591 of file UnitAI.h.
Referenced by CreatureAI::CreatureAI(), and HandleMovementOnAttackStart().
m_distanceSpells
std::unordered_set<uint32> UnitAI::m_distanceSpells protected
Definition at line 611 of file UnitAI.h.
Referenced by AddDistanceSpell(), and JustStoppedMovementOfTarget().
m_distancingCooldown
bool UnitAI::m_distancingCooldown protected
Definition at line 617 of file UnitAI.h.
Referenced by UnitAI(), and UpdateAI().
m_mainAttackMask
SpellSchoolMask UnitAI::m_mainAttackMask protected
Definition at line 616 of file UnitAI.h.
Referenced by AddMainSpell(), GetMainAttackSchoolMask(), and SpellListChanged().
m_mainSpellCost
uint32 UnitAI::m_mainSpellCost protected
Definition at line 613 of file UnitAI.h.
Referenced by AddMainSpell(), IsEligibleForDistancing(), and SpellListChanged().
m_mainSpellId
uint32 UnitAI::m_mainSpellId protected
Definition at line 612 of file UnitAI.h.
Referenced by AddMainSpell(), and SpellListChanged().
m_mainSpellInfo
SpellEntry const* UnitAI::m_mainSpellInfo protected
Definition at line 614 of file UnitAI.h.
Referenced by AddMainSpell(), IsEligibleForDistancing(), CreatureEventAI::ProcessAction(), SpellListChanged(), and UpdateAI().
m_mainSpellMinRange
float UnitAI::m_mainSpellMinRange protected
Definition at line 615 of file UnitAI.h.
Referenced by AddMainSpell(), DistanceYourself(), and SpellListChanged().
m_mainSpells
std::unordered_set<uint32> UnitAI::m_mainSpells protected
Definition at line 610 of file UnitAI.h.
Referenced by AddMainSpell(), HandleSpellCastResult(), OnSpellCooldownAdded(), OnSpellInterrupt(), and SpellListChanged().
m_meleeEnabled
bool UnitAI::m_meleeEnabled protected
Definition at line 593 of file UnitAI.h.
Referenced by AttackStart(), ScriptedPetAI::AttackStart(), CreatureAI::AttackStart(), PetAI::AttackStart(), npc_rethhedronAI::DamageTaken(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), CreatureEventAI::GetAIInformation(), boss_blackheart_the_inciterAI::HandleInciteEnd(), boss_the_lurker_belowAI::HandleSpoutEnd(), IsMeleeEnabled(), npc_rethhedronAI::JustRespawned(), npc_commanderAI::npc_commanderAI(), PetAI::PetAI(), boss_moira_bronzebeardAI::Reset(), boss_veklorAI::Reset(), SetCurrentRangedMode(), SetMeleeEnabled(), PetAI::UpdateAI(), and UpdateAI().
m_moveFurther
bool UnitAI::m_moveFurther protected
Definition at line 583 of file UnitAI.h.
Referenced by boss_lady_vashjAI::DoInformGeneratorStopped(), DoStartMovement(), ScriptedAI::DoStartMovement(), boss_leotheras_the_blindAI::ExecuteAction(), HandleMovementOnAttackStart(), boss_maievAI::ReceiveAIEvent(), SetMoveChaseParams(), and boss_grand_astromancer_capernianAI::UpdateAI().
m_rangedMode
bool UnitAI::m_rangedMode protected
Definition at line 606 of file UnitAI.h.
Referenced by HandleSpellCastResult(), OnSpellInterrupt(), CreatureAI::Reset(), CreatureEventAI::Reset(), SetRangedMode(), and UpdateAI().
m_rangedModeSetting
RangeModeType UnitAI::m_rangedModeSetting protected
Definition at line 607 of file UnitAI.h.
Referenced by OnSpellCooldownAdded(), OnSpellInterrupt(), SetCurrentRangedMode(), SetRangedMode(), and UpdateAI().
m_reactState
ReactStates UnitAI::m_reactState protected
Definition at line 596 of file UnitAI.h.
Referenced by GetReactState(), HasReactState(), CreatureEventAI::ProcessAction(), SetReactState(), and GuardianAI::UpdateAI().
m_spellListCooldown
bool UnitAI::m_spellListCooldown protected
Definition at line 620 of file UnitAI.h.
Referenced by EnterCombat(), SpellListChanged(), UnitAI(), and UpdateSpellLists().
m_teleportUnreachable
bool UnitAI::m_teleportUnreachable protected
Definition at line 603 of file UnitAI.h.
Referenced by CreatureAI::AddUnreachabilityCheck(), and ExecuteActions().
m_unit
Unit* UnitAI::m_unit protected
== Fields =======================================
Pointer to the Creature controlled by this AI
Definition at line 578 of file UnitAI.h.
Referenced by AddInitialCooldowns(), AddMainSpell(), AttackClosestEnemy(), PlayerAI::AttackClosestEnemy(), AttackedBy(), PetAI::AttackedBy(), AttackSpecificEnemy(), AttackStart(), CreatureAI::AttackStart(), PetAI::AttackStart(), CalculateSpellRange(), CanCastSpell(), CanExecuteCombatAction(), CanTriggerStealthAlert(), ChooseTarget(), ClearCombatOnlyRoot(), CreatureAI::CreatureAI(), DespawnGuids(), DetectOrAttack(), DistanceYourself(), DoCastSpellIfCan(), DoFindFriendlyEligibleDispel(), DoFindFriendlyMissingBuff(), DoFlee(), DoMeleeAttackIfReady(), DoResetThreat(), DoSelectConditionalFriendly(), DoSelectLowestHpFriendly(), DoStartMovement(), EnterEvadeMode(), PetAI::EnterEvadeMode(), ExecuteActions(), boss_kaelthasAI::ExecuteActions(), priestess_commonAI::ExecuteActions(), GetMainAttackSchoolMask(), npc_razorthorn_ravager_pet::HandleAnimations(), HandleDelayedInstantAnimation(), HandleMovementOnAttackStart(), CombatAI::HandleTargetRestoration(), IsCombatMovement(), IsEligibleForDistancing(), IsMainSpellPrevented(), IsVisible(), JumpingEnded(), GuardianAI::JustDied(), PetAI::JustDied(), JustStoppedMovementOfTarget(), MoveInLineOfSight(), PetAI::MoveInLineOfSight(), OnChannelStateChange(), OnSpellCastStateChange(), GuardianAI::OnUnsummon(), PetAI::OnUnsummon(), PetAI::PetAI(), ScriptedAI::SelectSpell(), SendAIEvent(), SendAIEventAround(), SetAIImmobilizedState(), SetCombatMovement(), SetCurrentRangedMode(), SetFollowMovement(), SetMeleeEnabled(), SetRangedMode(), SpellListChanged(), npc_ethereum_prisoner_dungeonAI::StartEvent(), TimedFleeingEnded(), npc_creature_generatorAI::TrySummoning(), PetAI::UpdateAI(), UpdateAI(), PetAI::UpdateAllies(), npc_daphne_stilwellAI::UpdateEscortAI(), and UpdateSpellLists().
m_visibilityDistance
float UnitAI::m_visibilityDistance protected
Definition at line 587 of file UnitAI.h.
Referenced by CreatureAI::CreatureAI(), IsVisible(), and PetAI::PetAI().
The documentation for this class was generated from the following files:
UnitAI.h
UnitAI.cpp