CMaNGOS_WoTLK: instance_blackwing_lair Class Reference
instance_blackwing_lair Class Reference
#include <blackwing_lair.h>
Public Member Functions
instance_blackwing_lair (Map *pMap)
~instance_blackwing_lair ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetData64 (uint32 uiData, uint64 uiGuid) override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void InitiateBreath (uint32 uiEventId)
void InitiateDrakonid (uint32 uiEventId)
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void CleanupNefarianStage (bool fullCleanup)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
std::string m_strInstData
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 m_uiResetTimer
uint32 m_uiDefenseTimer
uint32 m_uiScepterEpicTimer
uint32 m_uiNefarianSpawnTimer
uint8 m_uiScepterQuestStep
uint8 m_uiDragonspawnCount
uint8 m_uiBlackwingDefCount
uint8 m_uiDeadDrakonidsCount
bool m_bIsMainGateOpen
GuidList m_lDragonEggsGuids
GuidList m_lDrakonidBonesGuids
GuidList m_lDefendersGuids
GuidList m_lUsedEggsGuids
GuidList m_lDrakonidSpawnerGuids
GuidList m_drakonids
GuidVector m_vGeneratorGuids
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 127 of file blackwing_lair.h.
Constructor & Destructor Documentation
instance_blackwing_lair()
instance_blackwing_lair::instance_blackwing_lair (Map * pMap)
Definition at line 27 of file blackwing_lair.cpp.
References Initialize().
~instance_blackwing_lair()
instance_blackwing_lair::~instance_blackwing_lair () inline
Definition at line 131 of file blackwing_lair.h.
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_blackwing_lair::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 447 of file blackwing_lair.cpp.
References DONE, FAIL, GetData(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, script_error_log(), and TYPE_QUEST_SCEPTER.
CleanupNefarianStage()
void instance_blackwing_lair::CleanupNefarianStage (bool fullCleanup) protected
Definition at line 689 of file blackwing_lair.cpp.
References Map::GetCreature(), Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_JUST_DEACTIVATED, InstanceData::instance, m_drakonids, m_lDrakonidBonesGuids, m_lDrakonidSpawnerGuids, m_uiDeadDrakonidsCount, and NPC_LORD_VICTOR_NEFARIUS.
Referenced by SetData().
GetData()
uint32 instance_blackwing_lair::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 317 of file blackwing_lair.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by CheckConditionCriteriaMeet(), InitiateBreath(), InitiateDrakonid(), OnCreatureDeath(), OnCreatureRespawn(), OnObjectCreate(), SetData(), and Update().
Initialize()
void instance_blackwing_lair::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 41 of file blackwing_lair.cpp.
References m_auiEncounter.
Referenced by instance_blackwing_lair().
InitiateBreath()
void instance_blackwing_lair::InitiateBreath (uint32 uiEventId)
Definition at line 619 of file blackwing_lair.cpp.
References debug_log(), GetData(), NOT_STARTED, SetData(), TYPE_CHROMA_LBREATH, and TYPE_CHROMA_RBREATH.
InitiateDrakonid()
void instance_blackwing_lair::InitiateDrakonid (uint32 uiEventId)
Definition at line 654 of file blackwing_lair.cpp.
References debug_log(), GetData(), NOT_STARTED, NPC_BLACK_SPAWNER, NPC_BLUE_SPAWNER, NPC_BRONZE_SPAWNER, NPC_GREEN_SPAWNER, NPC_RED_SPAWNER, SetData(), TYPE_NEFA_LTUNNEL, and TYPE_NEFA_RTUNNEL.
IsEncounterInProgress()
bool instance_blackwing_lair::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 46 of file blackwing_lair.cpp.
References IN_PROGRESS, and m_auiEncounter.
Load()
void instance_blackwing_lair::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 292 of file blackwing_lair.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_blackwing_lair::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 56 of file blackwing_lair.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), Creature::IsTemporarySummon(), m_drakonids, m_lDefendersGuids, m_lDrakonidSpawnerGuids, ScriptedInstance::m_npcEntryGuidStore, m_uiBlackwingDefCount, m_uiDragonspawnCount, m_vGeneratorGuids, NPC_BLACK_DRAKONID, NPC_BLACK_SPAWNER, NPC_BLACKWING_LEGIONNAIRE, NPC_BLACKWING_MAGE, NPC_BLACKWING_ORB_TRIGGER, NPC_BLUE_DRAKONID, NPC_BLUE_SPAWNER, NPC_BRONZE_DRAKONID, NPC_BRONZE_SPAWNER, NPC_CHROMATIC_DRAKONID, NPC_DRAGONSPAWN, NPC_GREEN_DRAKONID, NPC_GREEN_SPAWNER, NPC_LORD_VICTOR_NEFARIUS, NPC_MONSTER_GENERATOR, NPC_NEFARIANS_TROOPS, NPC_RAZORGORE, NPC_RED_DRAKONID, NPC_RED_SPAWNER, and NPC_VAELASTRASZ.
OnCreatureDeath()
void instance_blackwing_lair::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 377 of file blackwing_lair.cpp.
References DONE, ScriptedInstance::DoToggleGameObjectFlags(), GetData(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_FLAG_NO_INTERACT, GO_ORB_OF_DOMINATION, IN_PROGRESS, m_uiBlackwingDefCount, m_uiDeadDrakonidsCount, m_uiDragonspawnCount, MAX_DRAKONID_SUMMONS, NPC_BLACK_DRAKONID, NPC_BLACKWING_LEGIONNAIRE, NPC_BLACKWING_MAGE, NPC_BLACKWING_ORB_TRIGGER, NPC_BLUE_DRAKONID, NPC_BRONZE_DRAKONID, NPC_CHROMATIC_DRAKONID, NPC_DRAGONSPAWN, NPC_GREEN_DRAKONID, NPC_GRETHOK_CONTROLLER, NPC_RAZORGORE, NPC_RED_DRAKONID, SetData(), SPECIAL, TYPE_NEFARIAN, and TYPE_RAZORGORE.
OnCreatureEnterCombat()
void instance_blackwing_lair::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 368 of file blackwing_lair.cpp.
References Object::GetEntry(), IN_PROGRESS, m_uiDefenseTimer, NPC_GRETHOK_CONTROLLER, SetData(), and TYPE_RAZORGORE.
OnCreatureRespawn()
void instance_blackwing_lair::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 417 of file blackwing_lair.cpp.
References FAIL, GetData(), Object::GetEntry(), ObjectGuid::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), WorldObject::GetSpawnerGuid(), NPC_BLACK_DRAKONID, NPC_BLACKWING_LEGIONNAIRE, NPC_BLACKWING_MAGE, NPC_BLUE_DRAKONID, NPC_BRONZE_DRAKONID, NPC_CHROMATIC_DRAKONID, NPC_DRAGONSPAWN, NPC_GREEN_DRAKONID, NPC_GRETHOK_CONTROLLER, NPC_MONSTER_GENERATOR, NPC_RAZORGORE, NPC_RED_DRAKONID, Creature::SetCorpseDelay(), Creature::SetInCombatWithZone(), Creature::SetNoLoot(), and TYPE_RAZORGORE.
OnObjectCreate()
void instance_blackwing_lair::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 103 of file blackwing_lair.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), GO_BLACK_DRAGON_EGG, GO_DOOR_CHROMAGGUS_EXIT, GO_DOOR_LASHLAYER, GO_DOOR_NEFARIAN, GO_DOOR_RAZORGORE_ENTER, GO_DOOR_RAZORGORE_EXIT, GO_DOOR_VAELASTRASZ, GO_DRAKONID_BONES, GO_JUST_DEACTIVATED, GO_ORB_OF_DOMINATION, GO_STATE_ACTIVE, GO_SUPPRESSION_DEVICE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_lDragonEggsGuids, m_lDrakonidBonesGuids, GameObject::SetGoState(), GameObject::SetLootState(), TYPE_CHROMAGGUS, TYPE_LASHLAYER, TYPE_RAZORGORE, and TYPE_VAELASTRASZ.
Save()
const char* instance_blackwing_lair::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 149 of file blackwing_lair.h.
References m_strInstData.
SetData()
void instance_blackwing_lair::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 145 of file blackwing_lair.cpp.
References CleanupNefarianStage(), DONE, DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DOOR_CHROMAGGUS_EXIT, GO_DOOR_LASHLAYER, GO_DOOR_NEFARIAN, GO_DOOR_RAZORGORE_ENTER, GO_DOOR_RAZORGORE_EXIT, GO_DOOR_VAELASTRASZ, GO_FLAG_NO_INTERACT, GO_ORB_OF_DOMINATION, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bIsMainGateOpen, m_lDefendersGuids, m_lUsedEggsGuids, m_strInstData, m_uiBlackwingDefCount, m_uiDragonspawnCount, m_uiNefarianSpawnTimer, m_uiResetTimer, m_uiScepterEpicTimer, m_uiScepterQuestStep, NPC_BLACKWING_ORB_TRIGGER, NPC_RAZORGORE, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_RAZORGORE_DEATH, SPECIAL, SPELL_FIREBALL, TRIGGERED_OLD_TRIGGERED, TYPE_CHROMA_LBREATH, TYPE_CHROMA_RBREATH, TYPE_CHROMAGGUS, TYPE_EBONROC, TYPE_FIREMAW, TYPE_FLAMEGOR, TYPE_LASHLAYER, TYPE_NEFA_LTUNNEL, TYPE_NEFA_RTUNNEL, TYPE_NEFARIAN, TYPE_QUEST_SCEPTER, TYPE_RAZORGORE, and TYPE_VAELASTRASZ.
Referenced by InitiateBreath(), InitiateDrakonid(), boss_razorgoreAI::JustPreventedDeath(), boss_razorgoreAI::JustReachedHome(), OnCreatureDeath(), OnCreatureEnterCombat(), SetData64(), and Update().
SetData64()
void instance_blackwing_lair::SetData64 (uint32 uiData, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 325 of file blackwing_lair.cpp.
References AI_EVENT_CUSTOM_A, DATA_DRAGON_EGG, DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), EMOTE_ORB_SHUT_OFF, EMOTE_TROOPS_FLEE, Map::GetCreature(), Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_FLAG_NO_INTERACT, GO_ORB_OF_DOMINATION, InstanceData::instance, m_lDefendersGuids, m_lDragonEggsGuids, m_lUsedEggsGuids, m_uiBlackwingDefCount, m_uiDragonspawnCount, NPC_NEFARIANS_TROOPS, NPC_RAZORGORE, SetData(), SPECIAL, SPELL_POSSESS, and TYPE_RAZORGORE.
Update()
void instance_blackwing_lair::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 462 of file blackwing_lair.cpp.
References aNefarianLocs, Unit::CastSpell(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), EMOTE_REDSHARD_TAUNT_1, EMOTE_REDSHARD_TAUNT_2, FAIL, Map::GetCreature(), GetData(), Map::GetGameObject(), GetRandomGenerator(), ScriptedInstance::GetSingleCreatureFromStorage(), HOUR, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_lDragonEggsGuids, m_uiBlackwingDefCount, m_uiDefenseTimer, m_uiDragonspawnCount, m_uiNefarianSpawnTimer, m_uiResetTimer, m_uiScepterEpicTimer, m_uiScepterQuestStep, m_vGeneratorGuids, MAX_BLACKWING_DEFENDER, MAX_DRAGONSPAWN, MAX_EGGS_DEFENDERS, MINUTE, NOT_STARTED, NPC_LORD_VICTOR_NEFARIUS, NPC_NEFARIAN, NPC_RAZORGORE, SetData(), SPECIAL, SPELL_SHADOWBLINK_OUTRO, SPELL_SUMMON_DRAGONSPAWN, SPELL_SUMMON_LEGIONNAIRE, SPELL_SUMMON_MAGE, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPE_NEFARIAN, TYPE_QUEST_SCEPTER, TYPE_RAZORGORE, urand(), YELL_REDSHARD_TAUNT_1, YELL_REDSHARD_TAUNT_2, YELL_REDSHARD_TAUNT_3, YELL_REDSHARD_TAUNT_4, YELL_REDSHARD_TAUNT_5, YELL_REDSHARD_TAUNT_6, and YELL_REDSHARD_TAUNT_7.
Field Documentation
m_auiEncounter
uint32 instance_blackwing_lair::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 161 of file blackwing_lair.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), and SetData().
m_bIsMainGateOpen
bool instance_blackwing_lair::m_bIsMainGateOpen protected
Definition at line 174 of file blackwing_lair.h.
Referenced by SetData().
m_drakonids
GuidList instance_blackwing_lair::m_drakonids protected
Definition at line 181 of file blackwing_lair.h.
Referenced by CleanupNefarianStage(), and OnCreatureCreate().
m_lDefendersGuids
GuidList instance_blackwing_lair::m_lDefendersGuids protected
Definition at line 178 of file blackwing_lair.h.
Referenced by OnCreatureCreate(), SetData(), and SetData64().
m_lDragonEggsGuids
GuidList instance_blackwing_lair::m_lDragonEggsGuids protected
Definition at line 176 of file blackwing_lair.h.
Referenced by OnObjectCreate(), SetData64(), and Update().
m_lDrakonidBonesGuids
GuidList instance_blackwing_lair::m_lDrakonidBonesGuids protected
Definition at line 177 of file blackwing_lair.h.
Referenced by CleanupNefarianStage(), and OnObjectCreate().
m_lDrakonidSpawnerGuids
GuidList instance_blackwing_lair::m_lDrakonidSpawnerGuids protected
Definition at line 180 of file blackwing_lair.h.
Referenced by CleanupNefarianStage(), and OnCreatureCreate().
m_lUsedEggsGuids
GuidList instance_blackwing_lair::m_lUsedEggsGuids protected
Definition at line 179 of file blackwing_lair.h.
Referenced by SetData(), and SetData64().
m_strInstData
std::string instance_blackwing_lair::m_strInstData protected
Definition at line 160 of file blackwing_lair.h.
Referenced by Save(), and SetData().
m_uiBlackwingDefCount
uint8 instance_blackwing_lair::m_uiBlackwingDefCount protected
Definition at line 171 of file blackwing_lair.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), SetData(), SetData64(), and Update().
m_uiDeadDrakonidsCount
uint8 instance_blackwing_lair::m_uiDeadDrakonidsCount protected
Definition at line 172 of file blackwing_lair.h.
Referenced by CleanupNefarianStage(), and OnCreatureDeath().
m_uiDefenseTimer
uint32 instance_blackwing_lair::m_uiDefenseTimer protected
Definition at line 166 of file blackwing_lair.h.
Referenced by OnCreatureEnterCombat(), and Update().
m_uiDragonspawnCount
uint8 instance_blackwing_lair::m_uiDragonspawnCount protected
Definition at line 170 of file blackwing_lair.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), SetData(), SetData64(), and Update().
m_uiNefarianSpawnTimer
uint32 instance_blackwing_lair::m_uiNefarianSpawnTimer protected
Definition at line 168 of file blackwing_lair.h.
Referenced by SetData(), and Update().
m_uiResetTimer
uint32 instance_blackwing_lair::m_uiResetTimer protected
Definition at line 165 of file blackwing_lair.h.
Referenced by SetData(), and Update().
m_uiScepterEpicTimer
uint32 instance_blackwing_lair::m_uiScepterEpicTimer protected
Definition at line 167 of file blackwing_lair.h.
Referenced by SetData(), and Update().
m_uiScepterQuestStep
uint8 instance_blackwing_lair::m_uiScepterQuestStep protected
Definition at line 169 of file blackwing_lair.h.
Referenced by SetData(), and Update().
m_vGeneratorGuids
GuidVector instance_blackwing_lair::m_vGeneratorGuids protected
Definition at line 182 of file blackwing_lair.h.
Referenced by OnCreatureCreate(), and Update().
The documentation for this class was generated from the following files:
blackwing_lair.h
blackwing_lair.cpp