CMaNGOS_WoTLK: Group Class Reference
Group Class Reference
request member stats checken
#include <Group.h>
Data Structures
struct MemberSlot
Public Types
typedef std::list< MemberSlot > MemberSlotList
typedef MemberSlotList::const_iterator member_citerator
typedef std::unordered_map< uint32, InstanceGroupBind > BoundInstancesMap
Public Member Functions
Group ()
~Group ()
bool Create (ObjectGuid guid, const char *name)
bool LoadGroupFromDB (Field *fields)
bool LoadMemberFromDB (uint32 guidLow, uint8 subgroup, bool assistant)
bool AddInvite (Player *player)
uint32 RemoveInvite (Player *player)
void RemoveAllInvites ()
bool AddLeaderInvite (Player *player)
bool AddMember (ObjectGuid guid, const char *name)
uint32 RemoveMember (ObjectGuid guid, uint8 method)
void ChangeLeader (ObjectGuid guid)
void Disband (bool hideDestroy=false)
uint32 GetId () const
ObjectGuid GetObjectGuid () const
std::string GetGuidStr () const
bool IsFull () const
bool IsRaidGroup () const
bool IsLFGGroup () const
bool IsBattleGroup () const
bool IsCreated () const
ObjectGuid const & GetLeaderGuid () const
const char * GetLeaderName () const
bool IsMember (ObjectGuid guid) const
bool IsLeader (ObjectGuid guid) const
ObjectGuid GetMemberGuid (const std::string &name)
bool IsAssistant (ObjectGuid guid) const
Player * GetInvited (ObjectGuid guid) const
Player * GetInvited (const std::string &name) const
bool HasFreeSlotSubGroup (uint8 subgroup) const
bool SameSubGroup (Player const *member1, Player const *member2) const
MemberSlotList const & GetMemberSlots () const
GroupReference * GetFirstMember ()
GroupReference const * GetFirstMember () const
uint32 GetMembersCount () const
uint32 GetMembersMinCount () const
uint32 GetInviteesCount () const
void GetDataForXPAtKill (Unit const *victim, uint32 &count, uint32 &sum_level, Player *&member_with_max_level, Player *&not_gray_member_with_max_level, Player *additional=nullptr)
uint8 GetMemberGroup (ObjectGuid guid) const
void ConvertToRaid ()
void ConvertToLFG ()
void SetBattlegroundGroup (BattleGround *bg)
void SetBattlefieldGroup (Battlefield *bf)
GroupJoinBattlegroundResult CanJoinBattleGroundQueue (BattleGround const *bgOrTemplate, BattleGroundQueueTypeId bgQueueTypeId, uint32 MinPlayerCount, uint32 MaxPlayerCount, bool isRated, uint32 arenaSlot)
void ChangeMembersGroup (ObjectGuid guid, uint8 group)
void ChangeMembersGroup (Player *player, uint8 group)
ObjectGuid GetMainTankGuid () const
ObjectGuid GetMainAssistantGuid () const
void SetAssistant (ObjectGuid guid, bool state)
void SetMainTank (ObjectGuid guid)
void SetMainAssistant (ObjectGuid guid)
void SetTargetIcon (uint8 id, ObjectGuid whoGuid, ObjectGuid targetGuid)
Difficulty GetDifficulty (bool isRaid) const
Difficulty GetDungeonDifficulty () const
Difficulty GetRaidDifficulty () const
void SetDungeonDifficulty (Difficulty difficulty)
void SetRaidDifficulty (Difficulty difficulty, bool send=true)
bool InCombatToInstance (uint32 instanceId)
void ResetInstances (InstanceResetMethod method, bool isRaid, Player *SendMsgTo)
void SendTargetIconList (WorldSession *session) const
void SendUpdateTo (Player *player)
void SendUpdate ()
void UpdatePlayerOutOfRange (Player *pPlayer)
void UpdatePlayerOnlineStatus (Player *player, bool online=true)
void UpdateOfflineLeader (time_t time, uint32 delay)
void BroadcastPacket (WorldPacket const &packet, bool ignorePlayersInBGRaid, int group=-1, ObjectGuid ignore=ObjectGuid()) const
void BroadcastPacketInMap (WorldObject const *who, WorldPacket const &packet, int group=-1, ObjectGuid ignore=ObjectGuid()) const
void BroadcastPacketInRange (WorldObject const *who, WorldPacket const &packet, bool ignorePlayersInBGRaid, int group=-1, ObjectGuid ignore=ObjectGuid()) const
void BroadcastReadyCheck (WorldPacket const &packet) const
void OfflineReadyCheck ()
void RewardGroupAtKill (Unit *pVictim, Player *player_tap)
Provide rewards to group members at unit kill.
bool SetPlayerMap (ObjectGuid guid, uint32 mapid)
void SetLootMethod (LootMethod method)
void SetMasterLooterGuid (ObjectGuid guid)
void SetLootThreshold (ItemQualities threshold)
void SetNextLooterGuid (ObjectGuid const &guid)
LootMethod GetLootMethod () const
ItemQualities GetLootThreshold () const
ObjectGuid const & GetMasterLooterGuid () const
ObjectGuid const & GetCurrentLooterGuid () const
void LinkMember (GroupReference *pRef)
void DelinkMember (GroupReference *) const
InstanceGroupBind * BindToInstance (DungeonPersistentState *state, bool permanent, bool load=false)
void UnbindInstance (uint32 mapid, uint8 difficulty, bool unload=false)
InstanceGroupBind * GetBoundInstance (uint32 mapid)
InstanceGroupBind * GetBoundInstance (Map *aMap, Difficulty difficulty)
BoundInstancesMap & GetBoundInstances (Difficulty difficulty)
LFGData & GetLfgData ()
Protected Types
typedef MemberSlotList::iterator member_witerator
typedef std::set< Player * > InvitesList
Protected Member Functions
bool _addMember (ObjectGuid guid, const char *name, bool isAssistant=false)
bool _addMember (ObjectGuid guid, const char *name, bool isAssistant, uint8 group)
bool _removeMember (ObjectGuid guid)
void _chooseLeader (bool offline=false)
void _setLeader (ObjectGuid guid)
void _updateLeaderFlag (bool remove=false) const
void _updateMembersOnRosterChanged (Player *changed)
bool _setMembersGroup (ObjectGuid guid, uint8 group)
bool _setAssistantFlag (ObjectGuid guid, const bool &state)
bool _setMainTank (ObjectGuid guid)
bool _setMainAssistant (ObjectGuid guid)
void _homebindIfInstance (Player *player) const
void _initRaidSubGroupsCounter ()
member_citerator _getMemberCSlot (ObjectGuid guid) const
member_witerator _getMemberWSlot (ObjectGuid guid)
void SubGroupCounterIncrease (uint8 subgroup)
void SubGroupCounterDecrease (uint8 subgroup)
uint32 GetMaxSkillValueForGroup (SkillType skill)
GroupFlagMask GetFlags (MemberSlot const &slot) const
Protected Attributes
uint32 m_Id
MemberSlotList m_memberSlots
GroupRefManager m_memberMgr
InvitesList m_invitees
ObjectGuid m_leaderGuid
std::string m_leaderName
time_t m_leaderLastOnline
ObjectGuid m_mainTankGuid
ObjectGuid m_mainAssistantGuid
GroupType m_groupFlags
Difficulty m_dungeonDifficulty
Difficulty m_raidDifficulty
BattleGround * m_bgGroup
Battlefield * m_bfGroup
ObjectGuid m_targetIcons [TARGET_ICON_COUNT]
LootMethod m_lootMethod
ItemQualities m_lootThreshold
ObjectGuid m_masterLooterGuid
ObjectGuid m_currentLooterGuid
BoundInstancesMap m_boundInstances [MAX_DIFFICULTY]
uint8 * m_subGroupsCounts
LFGData m_lfgData
Detailed Description
request member stats checken
todo: uninvite people that not accepted invite
Definition at line 122 of file Group.h.
Member Typedef Documentation
BoundInstancesMap
typedef std::unordered_map< uint32 , InstanceGroupBind > Group::BoundInstancesMap
Definition at line 136 of file Group.h.
InvitesList
typedef std::set<Player*> Group::InvitesList protected
Definition at line 139 of file Group.h.
member_citerator
typedef MemberSlotList::const_iterator Group::member_citerator
Definition at line 134 of file Group.h.
member_witerator
typedef MemberSlotList::iterator Group::member_witerator protected
Definition at line 138 of file Group.h.
MemberSlotList
typedef std::list<MemberSlot> Group::MemberSlotList
Definition at line 133 of file Group.h.
Constructor & Destructor Documentation
Group()
Group::Group ()
Definition at line 70 of file Group.cpp.
~Group()
Group::~Group ()
Definition at line 77 of file Group.cpp.
References ALLIANCE, DEBUG_LOG, BattleGround::GetBgRaid(), HORDE, m_bgGroup, m_boundInstances, m_subGroupsCounts, BattleGround::SetBgRaid(), and sLog.
Member Function Documentation
_addMember() [1/2]
bool Group::_addMember (ObjectGuid guid, const char * name, bool isAssistant, uint8 group) protected
Definition at line 871 of file Group.cpp.
References Group::MemberSlot::assistant, CharacterDatabase, GetBoundInstance(), ObjectGuid::GetCounter(), Player::GetGroup(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), Player::GetTeleportDest(), Group::MemberSlot::group, Group::MemberSlot::guid, IsBattleGroup(), Player::IsBeingTeleported(), IsFull(), Object::IsInWorld(), IsRaidGroup(), Group::MemberSlot::lastMap, m_Id, Player::m_InstanceValid, m_memberSlots, m_targetIcons, WorldLocation::mapid, Group::MemberSlot::name, Database::PExecute(), Player::SetBattleRaid(), Player::SetGroup(), Player::SetGroupInvite(), Player::SetOriginalGroup(), sObjectMgr, and SubGroupCounterIncrease().
_addMember() [2/2]
bool Group::_addMember (ObjectGuid guid, const char * name, bool isAssistant = false) protected
Definition at line 848 of file Group.cpp.
References m_subGroupsCounts, MAX_GROUP_SIZE, and MAX_RAID_SUBGROUPS.
Referenced by AddMember().
_chooseLeader()
void Group::_chooseLeader (bool offline = false) protected
Definition at line 974 of file Group.cpp.
References _setLeader(), ChangeLeader(), Player::GetGroup(), GetMembersCount(), GetMembersMinCount(), Player::GetSession(), ObjectGuid::IsEmpty(), IsRaidGroup(), m_leaderGuid, m_memberSlots, and sObjectMgr.
Referenced by _removeMember(), and UpdateOfflineLeader().
_getMemberCSlot()
member_citerator Group::_getMemberCSlot (ObjectGuid guid) const inline protected
Definition at line 329 of file Group.h.
References m_memberSlots.
Referenced by _setLeader(), _setMainTank(), ChangeLeader(), GetMemberGroup(), IsAssistant(), IsMember(), and SendUpdateTo().
_getMemberWSlot()
member_witerator Group::_getMemberWSlot (ObjectGuid guid) inline protected
Definition at line 338 of file Group.h.
References m_memberSlots.
Referenced by _removeMember(), _setAssistantFlag(), _setMainAssistant(), _setMembersGroup(), and SetPlayerMap().
_homebindIfInstance()
void Group::_homebindIfInstance (Player * player) const protected
Definition at line 1606 of file Group.cpp.
References Player::GetBoundInstance(), Map::GetDifficulty(), Map::GetId(), WorldObject::GetMap(), Map::IsDungeon(), Player::IsGameMaster(), Player::m_InstanceValid, and InstancePlayerBind::perm.
Referenced by Disband(), and RemoveMember().
_initRaidSubGroupsCounter()
void Group::_initRaidSubGroupsCounter () inline protected
Definition at line 317 of file Group.h.
References m_memberSlots, m_subGroupsCounts, and MAX_RAID_SUBGROUPS.
Referenced by ConvertToRaid(), Create(), and LoadGroupFromDB().
_removeMember()
bool Group::_removeMember (ObjectGuid guid) protected
Definition at line 935 of file Group.cpp.
References _chooseLeader(), _getMemberWSlot(), _updateLeaderFlag(), CharacterDatabase, ObjectGuid::GetCounter(), Player::GetOriginalGroup(), IsBattleGroup(), m_leaderGuid, m_memberSlots, Database::PExecute(), Player::RemoveFromBattleGroundRaid(), Player::SetGroup(), Player::SetOriginalGroup(), sObjectMgr, and SubGroupCounterDecrease().
Referenced by RemoveMember().
_setAssistantFlag()
bool Group::_setAssistantFlag (ObjectGuid guid, const bool & state) protected
Definition at line 1156 of file Group.cpp.
References _getMemberWSlot(), CharacterDatabase, ObjectGuid::GetCounter(), IsBattleGroup(), m_memberSlots, and Database::PExecute().
Referenced by SetAssistant().
_setLeader()
void Group::_setLeader (ObjectGuid guid) protected
Definition at line 1019 of file Group.cpp.
References _getMemberCSlot(), _updateLeaderFlag(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Player::ConvertInstancesToGroup(), ObjectGuid::GetCounter(), IsBattleGroup(), m_boundInstances, m_Id, m_leaderGuid, m_leaderLastOnline, m_leaderName, m_memberSlots, Database::PExecute(), and sObjectMgr.
Referenced by _chooseLeader(), and ChangeLeader().
_setMainAssistant()
bool Group::_setMainAssistant (ObjectGuid guid) protected
Definition at line 1191 of file Group.cpp.
References _getMemberWSlot(), _setMainTank(), CharacterDatabase, ObjectGuid::GetCounter(), IsBattleGroup(), m_Id, m_mainAssistantGuid, m_mainTankGuid, m_memberSlots, and Database::PExecute().
Referenced by _setMainTank(), and SetMainAssistant().
_setMainTank()
bool Group::_setMainTank (ObjectGuid guid) protected
Definition at line 1168 of file Group.cpp.
References _getMemberCSlot(), _setMainAssistant(), CharacterDatabase, ObjectGuid::GetCounter(), IsBattleGroup(), m_Id, m_mainAssistantGuid, m_mainTankGuid, m_memberSlots, and Database::PExecute().
Referenced by _setMainAssistant(), and SetMainTank().
_setMembersGroup()
bool Group::_setMembersGroup (ObjectGuid guid, uint8 group) protected
Definition at line 1140 of file Group.cpp.
References _getMemberWSlot(), CharacterDatabase, ObjectGuid::GetCounter(), IsBattleGroup(), m_memberSlots, Database::PExecute(), and SubGroupCounterIncrease().
Referenced by ChangeMembersGroup().
_updateLeaderFlag()
void Group::_updateLeaderFlag (bool remove = false) const protected
Definition at line 1083 of file Group.cpp.
References m_leaderGuid, and sObjectMgr.
Referenced by _removeMember(), _setLeader(), AddLeaderInvite(), Create(), and Disband().
_updateMembersOnRosterChanged()
void Group::_updateMembersOnRosterChanged (Player * changed) protected
Definition at line 1089 of file Group.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GROUP, CONFIG_UINT32_FOGOFWAR_HEALTH, CONTROLLED_CHARM, CONTROLLED_GUARDIANS, CONTROLLED_MINIPET, CONTROLLED_PET, CONTROLLED_TOTEMS, CORPSE_FIELD_BYTES_1, GetFirstMember(), Player::HasAtClient(), Object::IsInWorld(), GroupReference::next(), sWorld, TYPEID_PLAYER, UNIT_FIELD_FACTIONTEMPLATE, UNIT_FIELD_HEALTH, and UNIT_FIELD_MAXHEALTH.
Referenced by AddMember(), and RemoveMember().
AddInvite()
bool Group::AddInvite (Player * player)
Definition at line 254 of file Group.cpp.
References Player::GetGroup(), Player::GetGroupInvite(), Player::GetOriginalGroup(), IsBattleGroup(), m_invitees, RemoveInvite(), and Player::SetGroupInvite().
Referenced by AddLeaderInvite(), and WorldSession::HandleGroupInviteOpcode().
AddLeaderInvite()
bool Group::AddLeaderInvite (Player * player)
Definition at line 273 of file Group.cpp.
References _updateLeaderFlag(), AddInvite(), WorldObject::GetName(), Object::GetObjectGuid(), m_leaderGuid, and m_leaderName.
Referenced by WorldSession::HandleGroupInviteOpcode().
AddMember()
bool Group::AddMember (ObjectGuid guid, const char * name)
Definition at line 320 of file Group.cpp.
References _addMember(), _updateMembersOnRosterChanged(), UpdateData::BuildPacket(), GetDungeonDifficulty(), GetFirstMember(), GetRaidDifficulty(), GROUP_UPDATE_FULL, UpdateData::HasData(), UpdateMask::HasData(), INSTANCE_RESET_GROUP_JOIN, IsBattleGroup(), IsLeader(), IsRaidGroup(), LEVELREQUIREMENT_HEROIC, GroupReference::next(), SendUpdate(), UpdateMask::SetCount(), sObjectMgr, UF_FLAG_GROUP_ONLY, and UpdatePlayerOutOfRange().
Referenced by LfgProposal::AcceptProposal(), Battlefield::CanAddPlayerToRaid(), Create(), and WorldSession::HandleGroupAcceptOpcode().
BindToInstance()
InstanceGroupBind * Group::BindToInstance (DungeonPersistentState * state, bool permanent, bool load = false)
Definition at line 1559 of file Group.cpp.
References DungeonPersistentState::AddGroup(), CharacterDatabase, DEBUG_LOG, MapPersistentState::GetDifficulty(), GetId(), MapPersistentState::GetInstanceId(), GetLeaderGuid(), MapPersistentState::GetMapId(), IsBattleGroup(), m_boundInstances, InstanceGroupBind::perm, Database::PExecute(), DungeonPersistentState::RemoveGroup(), and InstanceGroupBind::state.
Referenced by DungeonMap::Add(), Player::ConvertInstancesToGroup(), ChatHandler::HandleGonameCommand(), ObjectMgr::LoadGroups(), and DungeonMap::PermBindAllPlayers().
BroadcastPacket()
void Group::BroadcastPacket (WorldPacket const & packet, bool ignorePlayersInBGRaid, int group = -1, ObjectGuid ignore = ObjectGuid()) const
Definition at line 777 of file Group.cpp.
References GetFirstMember(), Player::GetGroup(), Object::GetObjectGuid(), Player::GetSession(), GroupReference::next(), and WorldSession::SendPacket().
Referenced by ChangeLeader(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleMinimapPingOpcode(), WorldSession::HandleRaidReadyCheckFinishedOpcode(), WorldSession::HandleRaidReadyCheckOpcode(), WorldSession::HandleRandomRollOpcode(), LFGMgr::JoinLfg(), LFGMgr::LeaveLfg(), RemoveMember(), Player::SendNewItem(), and SetTargetIcon().
BroadcastPacketInMap()
void Group::BroadcastPacketInMap (WorldObject const * who, WorldPacket const & packet, int group = -1, ObjectGuid ignore = ObjectGuid()) const
Definition at line 790 of file Group.cpp.
References GetFirstMember(), Object::GetObjectGuid(), Player::GetSession(), WorldObject::IsInMap(), GroupReference::next(), and WorldSession::SendPacket().
Referenced by WorldSession::HandleChangePlayerDifficulty().
BroadcastPacketInRange()
void Group::BroadcastPacketInRange (WorldObject const * who, WorldPacket const & packet, bool ignorePlayersInBGRaid, int group = -1, ObjectGuid ignore = ObjectGuid()) const
Definition at line 806 of file Group.cpp.
References GetFirstMember(), Player::GetGroup(), Object::GetObjectGuid(), Player::GetSession(), Player::IsAtGroupRewardDistance(), GroupReference::next(), and WorldSession::SendPacket().
Referenced by Unit::Kill().
BroadcastReadyCheck()
void Group::BroadcastReadyCheck (WorldPacket const & packet) const
Definition at line 822 of file Group.cpp.
References GetFirstMember(), Object::GetObjectGuid(), Player::GetSession(), IsAssistant(), IsLeader(), GroupReference::next(), and WorldSession::SendPacket().
Referenced by WorldSession::HandleRaidReadyCheckOpcode(), and OfflineReadyCheck().
CanJoinBattleGroundQueue()
GroupJoinBattlegroundResult Group::CanJoinBattleGroundQueue (BattleGround const * bgOrTemplate, BattleGroundQueueTypeId bgQueueTypeId, uint32 MinPlayerCount, uint32 MaxPlayerCount, bool isRated, uint32 arenaSlot)
Definition at line 1293 of file Group.cpp.
References ARENA_TYPE_NONE, BATTLEGROUND_AA, BATTLEGROUND_RB, BattleGroundMgr::BgQueueTypeId(), Player::CanJoinToBattleground(), ERR_ARENA_TEAM_PARTY_SIZE, ERR_BATTLEGROUND_JOIN_FAILED, ERR_BATTLEGROUND_JOIN_RANGE_INDEX, ERR_BATTLEGROUND_JOIN_TIMED_OUT, ERR_BATTLEGROUND_NONE, ERR_BATTLEGROUND_TOO_MANY_QUEUES, ERR_GROUP_JOIN_BATTLEGROUND_DESERTERS, ERR_GROUP_JOIN_BATTLEGROUND_FAIL, ERR_IN_NON_RANDOM_BG, ERR_IN_RANDOM_BG, Player::GetArenaTeamId(), GetBattlegroundBracketByLevel(), GetFirstMember(), Unit::GetLevel(), BattleGround::GetMapId(), GetMembersCount(), Reference< TO, FROM >::getSource(), Player::GetTeam(), BattleGround::GetTypeId(), Player::HasFreeBattleGroundQueueId(), Player::InArena(), Player::InBattleGroundQueue(), Player::InBattleGroundQueueForBattleGroundQueueType(), BattleGround::IsArena(), PvPDifficultyEntry::mapId, BattlemasterListEntry::maxGroupSize, GroupReference::next(), and sBattlemasterListStore.
Referenced by WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
ChangeLeader()
void Group::ChangeLeader (ObjectGuid guid)
Definition at line 484 of file Group.cpp.
References _getMemberCSlot(), _setLeader(), BroadcastPacket(), m_memberSlots, SendUpdate(), and SMSG_GROUP_SET_LEADER.
Referenced by _chooseLeader(), WorldSession::HandleGroupSetLeaderOpcode(), and PlayerbotMgr::OnBotLogin().
ChangeMembersGroup() [1/2]
void Group::ChangeMembersGroup (ObjectGuid guid, uint8 group)
Definition at line 1225 of file Group.cpp.
References _setMembersGroup(), GetMemberGroup(), IsRaidGroup(), SendUpdate(), sObjectMgr, and SubGroupCounterDecrease().
Referenced by WorldSession::HandleGroupChangeSubGroupOpcode(), and WorldSession::HandleGroupSwapSubGroupOpcode().
ChangeMembersGroup() [2/2]
void Group::ChangeMembersGroup (Player * player, uint8 group)
Definition at line 1250 of file Group.cpp.
References _setMembersGroup(), Player::GetGroup(), Player::GetGroupRef(), Object::GetObjectGuid(), Player::GetOriginalGroupRef(), Player::GetOriginalSubGroup(), Player::GetSubGroup(), IsRaidGroup(), SendUpdate(), GroupReference::setSubGroup(), and SubGroupCounterDecrease().
ConvertToLFG()
void Group::ConvertToLFG ()
Definition at line 229 of file Group.cpp.
References CharacterDatabase, GROUP_FLAG_LFG, GROUP_FLAG_LFG_RESTRICTED, IsBattleGroup(), m_groupFlags, m_Id, m_lootMethod, NEED_BEFORE_GREED, Database::PExecute(), and SendUpdate().
ConvertToRaid()
void Group::ConvertToRaid ()
Definition at line 238 of file Group.cpp.
References _initRaidSubGroupsCounter(), CharacterDatabase, GROUP_FLAG_RAID, IsBattleGroup(), m_groupFlags, m_Id, m_memberSlots, Database::PExecute(), SendUpdate(), and sObjectMgr.
Referenced by WorldSession::HandleGroupRaidConvertOpcode().
Create()
bool Group::Create (ObjectGuid guid, const char * name)
Definition at line 101 of file Group.cpp.
References _initRaidSubGroupsCounter(), _updateLeaderFlag(), AddMember(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Player::ConvertInstancesToGroup(), DUNGEON_DIFFICULTY_NORMAL, ObjectGuid::GetCounter(), Player::GetDungeonDifficulty(), Player::GetRaidDifficulty(), GROUP_FLAG_NORMAL, GROUP_FLAG_RAID, GROUP_FLAGS_BGRAID, GROUP_LOOT, IsBattleGroup(), ITEM_QUALITY_UNCOMMON, m_currentLooterGuid, m_dungeonDifficulty, m_groupFlags, m_Id, m_leaderGuid, m_leaderLastOnline, m_leaderName, m_lootMethod, m_lootThreshold, m_mainAssistantGuid, m_mainTankGuid, m_masterLooterGuid, m_raidDifficulty, m_targetIcons, Database::PExecute(), RAID_DIFFICULTY_10MAN_NORMAL, sObjectMgr, and UI64FMTD.
Referenced by Battlefield::CanAddPlayerToRaid(), and WorldSession::HandleGroupAcceptOpcode().
DelinkMember()
void Group::DelinkMember (GroupReference *) const inline
Definition at line 291 of file Group.h.
Referenced by GroupReference::sourceObjectDestroyLink(), and GroupReference::targetObjectDestroyLink().
Disband()
void Group::Disband (bool hideDestroy = false)
Definition at line 498 of file Group.cpp.
References _homebindIfInstance(), _updateLeaderFlag(), Database::BeginTransaction(), CharacterDatabase, ObjectGuid::Clear(), Database::CommitTransaction(), Player::GetGroup(), Player::GetOriginalGroup(), Player::GetSession(), WorldPacket::Initialize(), INSTANCE_RESET_GROUP_DISBAND, IsBattleGroup(), IsRaidGroup(), m_Id, m_leaderGuid, m_leaderName, m_memberSlots, Database::PExecute(), RemoveAllInvites(), Player::RemoveFromBattleGroundRaid(), ResetInstances(), WorldSession::SendPacket(), Player::SetGroup(), Player::SetOriginalGroup(), SMSG_GROUP_DESTROYED, SMSG_GROUP_LIST, sObjectMgr, and Player::UpdateForQuestWorldObjects().
Referenced by WorldSession::HandleGroupDisbandOpcode(), ObjectMgr::LoadGroups(), RemoveMember(), and Player::UninviteFromGroup().
GetBoundInstance() [1/2]
InstanceGroupBind * Group::GetBoundInstance (Map * aMap, Difficulty difficulty)
Definition at line 1546 of file Group.cpp.
References Map::GetId(), GetMapDifficultyData(), and m_boundInstances.
GetBoundInstance() [2/2]
InstanceGroupBind * Group::GetBoundInstance (uint32 mapid)
Definition at line 1527 of file Group.cpp.
References DUNGEON_DIFFICULTY_NORMAL, GetDifficulty(), GetMapDifficultyData(), MapPersistentState::GetSaveDifficulty(), MapEntry::IsRaid(), m_boundInstances, and sMapStore.
Referenced by _addMember(), DungeonMap::Add(), and ChatHandler::HandleGonameCommand().
GetBoundInstances()
BoundInstancesMap& Group::GetBoundInstances (Difficulty difficulty) inline
Definition at line 297 of file Group.h.
References m_boundInstances.
GetCurrentLooterGuid()
ObjectGuid const& Group::GetCurrentLooterGuid () const inline
Definition at line 288 of file Group.h.
References m_currentLooterGuid.
Referenced by Loot::SetGroupLootRight().
GetDataForXPAtKill()
void Group::GetDataForXPAtKill (Unit const * victim, uint32 & count, uint32 & sum_level, Player *& member_with_max_level, Player *& not_gray_member_with_max_level, Player * additional = nullptr)
Definition at line 604 of file Group.cpp.
References GetDataForXPAtKill_helper(), GetFirstMember(), Unit::IsAlive(), Player::IsAtGroupRewardDistance(), and GroupReference::next().
Referenced by RewardGroupAtKill().
GetDifficulty()
Difficulty Group::GetDifficulty (bool isRaid) const inline
Definition at line 255 of file Group.h.
References m_dungeonDifficulty, and m_raidDifficulty.
Referenced by MapManager::CreateInstance(), GetBoundInstance(), WorldSession::HandleMoveWorldportAckOpcode(), and ResetInstances().
GetDungeonDifficulty()
Difficulty Group::GetDungeonDifficulty () const inline
Definition at line 256 of file Group.h.
References m_dungeonDifficulty.
Referenced by AddMember().
GetFirstMember() [1/2]
GroupReference* Group::GetFirstMember () inline
Definition at line 200 of file Group.h.
References GroupRefManager::getFirst(), and m_memberMgr.
Referenced by _updateMembersOnRosterChanged(), BattleGroundQueue::AddGroup(), AddMember(), BroadcastPacket(), BroadcastPacketInMap(), BroadcastPacketInRange(), BroadcastReadyCheck(), CanJoinBattleGroundQueue(), Spell::FillRaidOrPartyTargets(), LFGMgr::FinishDungeon(), GetDataForXPAtKill(), Creature::GetLootRecipient(), GameObject::GetLootRecipient(), GetMaxSkillValueForGroup(), Player::GetNextRaidMemberWithLowestLifePercentage(), Unit::GetNextRandomRaidMember(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleGroupgoCommand(), WorldSession::HandleLfgPartyLockInfoRequestOpcode(), ChatHandler::HandleTeleGroupCommand(), InCombatToInstance(), PlayerbotAI::IsInCombat(), LFGMgr::JoinLfg(), RemoveMember(), RewardGroupAtKill(), SetDungeonDifficulty(), SetRaidDifficulty(), Spell::SetTargetMap(), LFGMgr::TeleportPlayer(), AreaAura::Update(), PetAI::UpdateAllies(), PlayerbotAI::UpdateAttackerInfo(), and UpdatePlayerOutOfRange().
GetFirstMember() [2/2]
GroupReference const* Group::GetFirstMember () const inline
Definition at line 201 of file Group.h.
References GroupRefManager::getFirst(), and m_memberMgr.
GetFlags()
GroupFlagMask Group::GetFlags (MemberSlot const & slot) const inline protected
Definition at line 361 of file Group.h.
References Group::MemberSlot::assistant, GROUP_ASSISTANT, GROUP_MAIN_ASSISTANT, GROUP_MAIN_TANK, Group::MemberSlot::guid, m_mainAssistantGuid, and m_mainTankGuid.
Referenced by SendUpdateTo().
GetGuidStr()
std::string Group::GetGuidStr () const inline
Definition at line 161 of file Group.h.
References GetObjectGuid(), and ObjectGuid::GetString().
Referenced by Battlefield::CanAddPlayerToRaid().
GetId()
uint32 Group::GetId () const inline
Definition at line 159 of file Group.h.
References m_Id.
Referenced by Player::_LoadBoundInstances(), DungeonMap::Add(), ObjectMgr::AddGroup(), BindToInstance(), GetObjectGuid(), ObjectMgr::LoadGroups(), ObjectMgr::RemoveGroup(), and AreaAura::Update().
GetInvited() [1/2]
Player * Group::GetInvited (const std::string & name) const
Definition at line 310 of file Group.cpp.
References m_invitees.
GetInvited() [2/2]
Player * Group::GetInvited (ObjectGuid guid) const
Definition at line 301 of file Group.cpp.
References m_invitees.
Referenced by WorldSession::HandleGroupUninviteGuidOpcode(), and WorldSession::HandleGroupUninviteOpcode().
GetInviteesCount()
uint32 Group::GetInviteesCount () const inline
Definition at line 204 of file Group.h.
References m_invitees.
Referenced by Player::UninviteFromGroup().
GetLeaderGuid()
ObjectGuid const& Group::GetLeaderGuid () const inline
Definition at line 167 of file Group.h.
References m_leaderGuid.
Referenced by BindToInstance(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupDeclineOpcode(), WorldSession::HandleGroupDisbandOpcode(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleNamegoCommand(), IsLeader(), DungeonMap::PermBindAllPlayers(), UnbindInstance(), and Player::UpdateGroupLeaderFlag().
GetLeaderName()
const char* Group::GetLeaderName () const inline
Definition at line 168 of file Group.h.
References m_leaderName.
Referenced by WorldSession::HandleGroupAcceptOpcode(), and WorldSession::HandleGroupUninviteOpcode().
GetLfgData()
LFGData& Group::GetLfgData () inline
Definition at line 299 of file Group.h.
References m_lfgData.
Referenced by LFGMgr::FinishDungeon(), WorldSession::HandleLfgSetRolesOpcode(), LFGMgr::JoinLfg(), LFGMgr::LeaveLfg(), and LFGMgr::TeleportPlayer().
GetLootMethod()
LootMethod Group::GetLootMethod () const inline
Definition at line 285 of file Group.h.
References m_lootMethod.
Referenced by Loot::SetGroupLootRight().
GetLootThreshold()
ItemQualities Group::GetLootThreshold () const inline
Definition at line 286 of file Group.h.
References m_lootThreshold.
Referenced by Loot::SetGroupLootRight().
GetMainAssistantGuid()
ObjectGuid Group::GetMainAssistantGuid () const inline
Definition at line 227 of file Group.h.
References m_mainAssistantGuid.
Referenced by WorldSession::HandlePartyAssignmentOpcode().
GetMainTankGuid()
ObjectGuid Group::GetMainTankGuid () const inline
Definition at line 226 of file Group.h.
References m_mainTankGuid.
Referenced by WorldSession::HandlePartyAssignmentOpcode().
GetMasterLooterGuid()
ObjectGuid const& Group::GetMasterLooterGuid () const inline
Definition at line 287 of file Group.h.
References m_masterLooterGuid.
Referenced by Loot::SetGroupLootRight().
GetMaxSkillValueForGroup()
uint32 Group::GetMaxSkillValueForGroup (SkillType skill) protected
Definition at line 1275 of file Group.cpp.
References GetFirstMember(), Player::GetSkillValue(), and GroupReference::next().
GetMemberGroup()
uint8 Group::GetMemberGroup (ObjectGuid guid) const inline
Definition at line 206 of file Group.h.
References _getMemberCSlot(), m_memberSlots, and MAX_RAID_SUBGROUPS.
Referenced by Battlefield::CanAddPlayerToRaid(), ChangeMembersGroup(), WorldSession::HandleMessagechatOpcode(), and Unit::Kill().
GetMemberGuid()
ObjectGuid Group::GetMemberGuid (const std::string & name) inline
Definition at line 173 of file Group.h.
References m_memberSlots.
Referenced by WorldSession::HandleGroupUninviteOpcode().
GetMembersCount()
uint32 Group::GetMembersCount () const inline
Definition at line 202 of file Group.h.
References m_memberSlots.
Referenced by _chooseLeader(), CanJoinBattleGroundQueue(), Unit::GetNextRandomRaidMember(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), WorldSession::HandleGroupRaidConvertOpcode(), IsCreated(), LFGMgr::JoinLfg(), RemoveInvite(), RemoveMember(), SendUpdateTo(), Player::UninviteFromGroup(), and PetAI::UpdateAllies().
GetMemberSlots()
MemberSlotList const& Group::GetMemberSlots () const inline
Definition at line 199 of file Group.h.
References m_memberSlots.
Referenced by PlayerbotAI::_HandleCommandPull(), PlayerbotAI::_HandleCommandQuest(), PlayerbotClassAI::Buff(), PlayerbotPaladinAI::CheckAuras(), PlayerbotAI::ClearGroupCombatOrder(), PlayerbotClassAI::GetDispelTarget(), PlayerbotAI::GetGroupHealer(), PlayerbotAI::GetGroupTank(), PlayerbotClassAI::GetHealTarget(), PlayerbotClassAI::GetResurrectionTarget(), PlayerbotAI::GroupHoTOnTank(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleGroupSwapSubGroupOpcode(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::NeedGroupBuff(), Loot::Release(), PlayerbotAI::SetGroupCombatOrder(), PlayerbotAI::SetGroupIgnoreUpdateTime(), and Loot::SetGroupLootRight().
GetMembersMinCount()
uint32 Group::GetMembersMinCount () const inline
Definition at line 203 of file Group.h.
References IsBattleGroup().
Referenced by _chooseLeader(), WorldSession::HandleGroupRaidConvertOpcode(), RemoveMember(), and Player::UninviteFromGroup().
GetObjectGuid()
ObjectGuid Group::GetObjectGuid () const inline
Definition at line 160 of file Group.h.
References GetId(), and HIGHGUID_GROUP.
Referenced by LFGMgr::FinishDungeon(), GetGuidStr(), WorldSession::HandleLfgSetRolesOpcode(), LFGMgr::JoinLfg(), LFGMgr::LeaveLfg(), WorldSession::LogoutPlayer(), and SendUpdateTo().
GetRaidDifficulty()
Difficulty Group::GetRaidDifficulty () const inline
Definition at line 257 of file Group.h.
References m_raidDifficulty.
Referenced by AddMember().
HasFreeSlotSubGroup()
bool Group::HasFreeSlotSubGroup (uint8 subgroup) const inline
Definition at line 192 of file Group.h.
References m_subGroupsCounts, and MAX_GROUP_SIZE.
Referenced by WorldSession::HandleGroupChangeSubGroupOpcode().
InCombatToInstance()
bool Group::InCombatToInstance (uint32 instanceId)
Definition at line 1398 of file Group.cpp.
References Unit::getAttackers(), GetFirstMember(), WorldObject::GetInstanceId(), and GroupReference::next().
IsAssistant()
bool Group::IsAssistant (ObjectGuid guid) const inline
Definition at line 181 of file Group.h.
References _getMemberCSlot(), and m_memberSlots.
Referenced by BroadcastReadyCheck(), Player::CanUninviteFromGroup(), WorldSession::HandleGroupChangeSubGroupOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleRaidReadyCheckFinishedOpcode(), WorldSession::HandleRaidReadyCheckOpcode(), and WorldSession::HandleRaidTargetUpdateOpcode().
IsBattleGroup()
bool Group::IsBattleGroup () const inline
Definition at line 165 of file Group.h.
References m_bfGroup, and m_bgGroup.
Referenced by _addMember(), _removeMember(), _setAssistantFlag(), _setLeader(), _setMainAssistant(), _setMainTank(), _setMembersGroup(), AddInvite(), AddMember(), BindToInstance(), ConvertToLFG(), ConvertToRaid(), Create(), Disband(), GetMembersMinCount(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleMessagechatOpcode(), ResetInstances(), SendUpdateTo(), SetDungeonDifficulty(), SetRaidDifficulty(), and UpdateOfflineLeader().
IsCreated()
bool Group::IsCreated () const inline
Definition at line 166 of file Group.h.
References GetMembersCount().
Referenced by WorldSession::HandleGroupAcceptOpcode(), WorldSession::HandleGroupInviteOpcode(), and Player::UninviteFromGroup().
IsFull()
bool Group::IsFull () const inline
Definition at line 162 of file Group.h.
References GROUP_FLAG_NORMAL, m_groupFlags, m_memberSlots, MAX_GROUP_SIZE, and MAX_RAID_SIZE.
Referenced by _addMember(), WorldSession::HandleGroupAcceptOpcode(), and WorldSession::HandleGroupInviteOpcode().
IsLeader()
bool Group::IsLeader (ObjectGuid guid) const inline
Definition at line 172 of file Group.h.
References GetLeaderGuid().
Referenced by AddMember(), BroadcastReadyCheck(), Player::CanUninviteFromGroup(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleGonameCommand(), WorldSession::HandleGroupAssistantLeaderOpcode(), WorldSession::HandleGroupChangeSubGroupOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupRaidConvertOpcode(), WorldSession::HandleGroupSetLeaderOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleLootMethodOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandlePartyAssignmentOpcode(), WorldSession::HandleRaidReadyCheckFinishedOpcode(), WorldSession::HandleRaidReadyCheckOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), PlayerbotMgr::OnBotLogin(), and UpdatePlayerOnlineStatus().
IsLFGGroup()
bool Group::IsLFGGroup () const inline
Definition at line 164 of file Group.h.
References GROUP_FLAG_LFG, and m_groupFlags.
Referenced by LFGMgr::JoinLfg(), and LFGMgr::TeleportPlayer().
IsMember()
bool Group::IsMember (ObjectGuid guid) const inline
Definition at line 171 of file Group.h.
References _getMemberCSlot(), and m_memberSlots.
Referenced by Object::BuildValuesUpdate(), Battlefield::CanAddPlayerToRaid(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGroupUninviteGuidOpcode(), PlayerbotMgr::OnBotLogin(), Spell::SetTargetMap(), and UpdatePlayerOnlineStatus().
IsRaidGroup()
bool Group::IsRaidGroup () const inline
Definition at line 163 of file Group.h.
References GROUP_FLAG_RAID, and m_groupFlags.
Referenced by _addMember(), _chooseLeader(), AddMember(), ChangeMembersGroup(), Disband(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupSwapSubGroupOpcode(), WorldSession::HandleMessagechatOpcode(), WorldSession::HandleRaidTargetUpdateOpcode(), WorldSession::LogoutPlayer(), RemoveMember(), RewardGroupAtKill(), SetAssistant(), SetMainAssistant(), SetMainTank(), and PetAI::UpdateAllies().
LinkMember()
void Group::LinkMember (GroupReference * pRef) inline
Definition at line 290 of file Group.h.
References LinkedListHead::insertFirst(), and m_memberMgr.
Referenced by GroupReference::targetObjectBuildLink().
LoadGroupFromDB()
bool Group::LoadGroupFromDB (Field * fields)
Definition at line 160 of file Group.cpp.
References _initRaidSubGroupsCounter(), DUNGEON_DIFFICULTY_NORMAL, Field::GetUInt32(), Field::GetUInt8(), GROUP_FLAG_RAID, HIGHGUID_PLAYER, m_currentLooterGuid, m_dungeonDifficulty, m_groupFlags, m_Id, m_leaderGuid, m_leaderLastOnline, m_leaderName, m_lootMethod, m_lootThreshold, m_mainAssistantGuid, m_mainTankGuid, m_masterLooterGuid, m_raidDifficulty, m_targetIcons, MAX_DUNGEON_DIFFICULTY, MAX_RAID_DIFFICULTY, RAID_DIFFICULTY_10MAN_NORMAL, sObjectMgr, and TARGET_ICON_COUNT.
Referenced by ObjectMgr::LoadGroups().
LoadMemberFromDB()
bool Group::LoadMemberFromDB (uint32 guidLow, uint8 subgroup, bool assistant)
Definition at line 202 of file Group.cpp.
References Group::MemberSlot::assistant, ObjectGuid::GetString(), Group::MemberSlot::group, Group::MemberSlot::guid, HIGHGUID_PLAYER, Group::MemberSlot::lastMap, m_memberSlots, Group::MemberSlot::name, sLog, sObjectMgr, and SubGroupCounterIncrease().
Referenced by ObjectMgr::LoadGroups().
OfflineReadyCheck()
void Group::OfflineReadyCheck ()
Definition at line 833 of file Group.cpp.
References BroadcastReadyCheck(), Player::GetSession(), m_memberSlots, MSG_RAID_READY_CHECK_CONFIRM, and sObjectMgr.
Referenced by WorldSession::HandleRaidReadyCheckOpcode().
RemoveAllInvites()
void Group::RemoveAllInvites ()
Definition at line 293 of file Group.cpp.
References m_invitees.
Referenced by Disband(), WorldSession::HandleGroupInviteOpcode(), and Player::UninviteFromGroup().
RemoveInvite()
uint32 Group::RemoveInvite (Player * player)
Definition at line 285 of file Group.cpp.
References GetMembersCount(), m_invitees, and Player::SetGroupInvite().
Referenced by AddInvite(), WorldSession::HandleGroupAcceptOpcode(), and Player::UninviteFromGroup().
RemoveMember()
uint32 Group::RemoveMember (ObjectGuid guid, uint8 method)
Definition at line 406 of file Group.cpp.
References _homebindIfInstance(), _removeMember(), _updateMembersOnRosterChanged(), botConfig, BroadcastPacket(), Disband(), Config::GetBoolDefault(), GetFirstMember(), Player::GetGroup(), GetMembersCount(), GetMembersMinCount(), Player::GetSession(), WorldPacket::Initialize(), IsRaidGroup(), m_leaderName, m_memberSlots, GroupReference::next(), Unit::RemoveAllGroupBuffsFromCaster(), WorldSession::SendPacket(), SendUpdate(), SMSG_GROUP_LIST, SMSG_GROUP_SET_LEADER, SMSG_GROUP_UNINVITE, sObjectMgr, and Player::UpdateForQuestWorldObjects().
Referenced by PlayerbotMgr::HandleMasterIncomingPacket(), PlayerbotMgr::RemoveAllBotsFromGroup(), and Player::RemoveFromGroup().
ResetInstances()
void Group::ResetInstances (InstanceResetMethod method, bool isRaid, Player * SendMsgTo)
Definition at line 1421 of file Group.cpp.
References DungeonPersistentState::CanReset(), CharacterDatabase, DungeonPersistentState::DeleteFromDB(), DUNGEON_DIFFICULTY_HEROIC, ObjectAccessor::FindPlayer(), GetDifficulty(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMapId(), Player::GetTeleportDest(), INSTANCE_RESET_ALL, INSTANCE_RESET_CHANGE_DIFFICULTY, INSTANCE_RESET_GROUP_DISBAND, IsBattleGroup(), Player::IsBeingTeleported(), MapEntry::IsDungeon(), MapEntry::IsRaid(), m_boundInstances, m_memberSlots, MAP_RAID, MapEntry::map_type, WorldLocation::mapid, Database::PExecute(), DungeonPersistentState::RemoveGroup(), Player::SendResetInstanceFailed(), Player::SendResetInstanceSuccess(), sMapMgr, and sMapStore.
Referenced by Disband().
RewardGroupAtKill()
void Group::RewardGroupAtKill (Unit * pVictim, Player * player_tap)
Provide rewards to group members at unit kill.
Parameters
pVictim Killed unit
player_tap Player who tap unit if online, it can be group member or can be not if leaved after tap but before kill target
Rewards received by group members and player_tap
not get Xp in PvP or no not gray players in group
skip in check PvP case (for speed, not used)
Definition at line 1679 of file Group.cpp.
References MaNGOS::XP::Gain(), GetDataForXPAtKill(), GetFirstMember(), WorldObject::GetMapId(), Object::GetTypeId(), Object::HasFlag(), Player::IsAtGroupRewardDistance(), IsRaidGroup(), GroupReference::next(), RewardGroupAtKill_helper(), sMapStore, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and MaNGOS::XP::xp_in_group_rate().
Referenced by Unit::Kill().
SameSubGroup()
bool Group::SameSubGroup (Player const * member1, Player const * member2) const
Definition at line 1215 of file Group.cpp.
References Player::GetGroup(), and Player::GetSubGroup().
Referenced by PlayerbotClassAI::GetHealTarget(), Unit::IsInGroup(), Player::IsInGroup(), AreaAura::Update(), and PetAI::UpdateAllies().
SendTargetIconList()
void Group::SendTargetIconList (WorldSession * session) const
Definition at line 633 of file Group.cpp.
References m_targetIcons, MSG_RAID_TARGET_UPDATE, WorldSession::SendPacket(), and TARGET_ICON_COUNT.
Referenced by WorldSession::HandleRaidTargetUpdateOpcode().
SendUpdate()
void Group::SendUpdate ()
Definition at line 712 of file Group.cpp.
References m_memberSlots, SendUpdateTo(), and sObjectMgr.
Referenced by AddMember(), ChangeLeader(), ChangeMembersGroup(), ConvertToLFG(), ConvertToRaid(), WorldSession::HandleLootMethodOpcode(), RemoveMember(), SetAssistant(), SetMainAssistant(), SetMainTank(), and UpdatePlayerOnlineStatus().
SendUpdateTo()
void Group::SendUpdateTo (Player * player)
Definition at line 653 of file Group.cpp.
References _getMemberCSlot(), Map::GetEntry(), GetFlags(), Player::GetGroup(), GetGroupMemberStatus(), WorldObject::GetMap(), GetMembersCount(), Object::GetObjectGuid(), GetObjectGuid(), Player::GetSession(), GROUP_FLAG_LFG, IsBattleGroup(), MapEntry::IsDynamicDifficultyMap(), Map::IsHeroic(), Object::IsInWorld(), m_dungeonDifficulty, m_groupFlags, m_leaderGuid, m_lootMethod, m_lootThreshold, m_masterLooterGuid, m_memberSlots, m_raidDifficulty, MASTER_LOOT, WorldSession::SendPacket(), SMSG_GROUP_LIST, and sObjectMgr.
Referenced by WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), and SendUpdate().
SetAssistant()
void Group::SetAssistant (ObjectGuid guid, bool state) inline
Definition at line 229 of file Group.h.
References _setAssistantFlag(), IsRaidGroup(), and SendUpdate().
Referenced by WorldSession::HandleGroupAssistantLeaderOpcode().
SetBattlefieldGroup()
void Group::SetBattlefieldGroup (Battlefield * bf) inline
Definition at line 220 of file Group.h.
References m_bfGroup.
Referenced by Battlefield::CanAddPlayerToRaid().
SetBattlegroundGroup()
void Group::SetBattlegroundGroup (BattleGround * bg) inline
Definition at line 219 of file Group.h.
References m_bgGroup.
Referenced by BattleGround::SetBgRaid().
SetDungeonDifficulty()
void Group::SetDungeonDifficulty (Difficulty difficulty)
Definition at line 1363 of file Group.cpp.
References CharacterDatabase, GetFirstMember(), Unit::GetLevel(), Player::GetSession(), IsBattleGroup(), LEVELREQUIREMENT_HEROIC, m_dungeonDifficulty, m_Id, GroupReference::next(), Database::PExecute(), Player::SendDungeonDifficulty(), and Player::SetDungeonDifficulty().
SetLootMethod()
void Group::SetLootMethod (LootMethod method) inline
Definition at line 281 of file Group.h.
References m_lootMethod.
Referenced by WorldSession::HandleLootMethodOpcode().
SetLootThreshold()
void Group::SetLootThreshold (ItemQualities threshold) inline
Definition at line 283 of file Group.h.
References m_lootThreshold.
Referenced by WorldSession::HandleLootMethodOpcode().
SetMainAssistant()
void Group::SetMainAssistant (ObjectGuid guid) inline
Definition at line 244 of file Group.h.
References _setMainAssistant(), IsRaidGroup(), and SendUpdate().
Referenced by WorldSession::HandlePartyAssignmentOpcode().
SetMainTank()
void Group::SetMainTank (ObjectGuid guid) inline
Definition at line 236 of file Group.h.
References _setMainTank(), IsRaidGroup(), and SendUpdate().
Referenced by WorldSession::HandlePartyAssignmentOpcode().
SetMasterLooterGuid()
void Group::SetMasterLooterGuid (ObjectGuid guid) inline
Definition at line 282 of file Group.h.
References m_masterLooterGuid.
Referenced by WorldSession::HandleLootMethodOpcode().
SetNextLooterGuid()
void Group::SetNextLooterGuid (ObjectGuid const & guid) inline
Definition at line 284 of file Group.h.
References m_currentLooterGuid.
Referenced by Loot::SetGroupLootRight().
SetPlayerMap()
bool Group::SetPlayerMap (ObjectGuid guid, uint32 mapid)
Definition at line 1409 of file Group.cpp.
References _getMemberWSlot(), DEBUG_LOG, and m_memberSlots.
SetRaidDifficulty()
void Group::SetRaidDifficulty (Difficulty difficulty, bool send = true)
Definition at line 1379 of file Group.cpp.
References CharacterDatabase, GetFirstMember(), Unit::GetLevel(), Player::GetSession(), IsBattleGroup(), LEVELREQUIREMENT_HEROIC, m_Id, m_raidDifficulty, GroupReference::next(), Database::PExecute(), and Player::SendRaidDifficulty().
Referenced by WorldSession::HandleChangePlayerDifficulty().
SetTargetIcon()
void Group::SetTargetIcon (uint8 id, ObjectGuid whoGuid, ObjectGuid targetGuid)
Definition at line 567 of file Group.cpp.
References BroadcastPacket(), m_targetIcons, MSG_RAID_TARGET_UPDATE, and TARGET_ICON_COUNT.
Referenced by WorldSession::HandleRaidTargetUpdateOpcode().
SubGroupCounterDecrease()
void Group::SubGroupCounterDecrease (uint8 subgroup) inline protected
Definition at line 353 of file Group.h.
References m_subGroupsCounts.
Referenced by _removeMember(), and ChangeMembersGroup().
SubGroupCounterIncrease()
void Group::SubGroupCounterIncrease (uint8 subgroup) inline protected
Definition at line 347 of file Group.h.
References m_subGroupsCounts.
Referenced by _addMember(), _setMembersGroup(), and LoadMemberFromDB().
UnbindInstance()
void Group::UnbindInstance (uint32 mapid, uint8 difficulty, bool unload = false)
Definition at line 1593 of file Group.cpp.
References CharacterDatabase, GetLeaderGuid(), m_boundInstances, and Database::PExecute().
Referenced by MapPersistentStateManager::_ResetSave(), and DungeonPersistentState::UnbindThisState().
UpdateOfflineLeader()
void Group::UpdateOfflineLeader (time_t time, uint32 delay)
Definition at line 753 of file Group.cpp.
References _chooseLeader(), IsBattleGroup(), m_leaderGuid, m_leaderLastOnline, and sObjectMgr.
UpdatePlayerOnlineStatus()
void Group::UpdatePlayerOnlineStatus (Player * player, bool online = true)
Definition at line 735 of file Group.cpp.
References Object::GetObjectGuid(), GROUP_UPDATE_FULL, IsLeader(), IsMember(), m_leaderLastOnline, SendUpdate(), Player::SetGroupUpdateFlag(), and UpdatePlayerOutOfRange().
Referenced by WorldSession::HandlePlayerLogin().
UpdatePlayerOutOfRange()
void Group::UpdatePlayerOutOfRange (Player * pPlayer)
Definition at line 718 of file Group.cpp.
References WorldSession::BuildPartyMemberStatsChangedPacket(), GetFirstMember(), Player::GetGroupUpdateFlag(), GROUP_UPDATE_FLAG_NONE, Player::HasAtClient(), Object::IsInWorld(), and GroupReference::next().
Referenced by AddMember(), and UpdatePlayerOnlineStatus().
Field Documentation
m_bfGroup
Battlefield* Group::m_bfGroup protected
Definition at line 385 of file Group.h.
Referenced by IsBattleGroup(), and SetBattlefieldGroup().
m_bgGroup
BattleGround* Group::m_bgGroup protected
Definition at line 384 of file Group.h.
Referenced by IsBattleGroup(), SetBattlegroundGroup(), and ~Group().
m_boundInstances
BoundInstancesMap Group::m_boundInstances[MAX_DIFFICULTY] protected
Definition at line 391 of file Group.h.
Referenced by _setLeader(), BindToInstance(), GetBoundInstance(), GetBoundInstances(), ResetInstances(), UnbindInstance(), and ~Group().
m_currentLooterGuid
ObjectGuid Group::m_currentLooterGuid protected
Definition at line 390 of file Group.h.
Referenced by Create(), GetCurrentLooterGuid(), LoadGroupFromDB(), and SetNextLooterGuid().
m_dungeonDifficulty
Difficulty Group::m_dungeonDifficulty protected
Definition at line 382 of file Group.h.
Referenced by Create(), GetDifficulty(), GetDungeonDifficulty(), LoadGroupFromDB(), SendUpdateTo(), and SetDungeonDifficulty().
m_groupFlags
GroupType Group::m_groupFlags protected
Definition at line 381 of file Group.h.
Referenced by ConvertToLFG(), ConvertToRaid(), Create(), IsFull(), IsLFGGroup(), IsRaidGroup(), LoadGroupFromDB(), and SendUpdateTo().
m_Id
uint32 Group::m_Id protected
Definition at line 372 of file Group.h.
Referenced by _addMember(), _setLeader(), _setMainAssistant(), _setMainTank(), ConvertToLFG(), ConvertToRaid(), Create(), Disband(), GetId(), LoadGroupFromDB(), SetDungeonDifficulty(), and SetRaidDifficulty().
m_invitees
InvitesList Group::m_invitees protected
Definition at line 375 of file Group.h.
Referenced by AddInvite(), GetInvited(), GetInviteesCount(), RemoveAllInvites(), and RemoveInvite().
m_leaderGuid
ObjectGuid Group::m_leaderGuid protected
Definition at line 376 of file Group.h.
Referenced by _chooseLeader(), _removeMember(), _setLeader(), _updateLeaderFlag(), AddLeaderInvite(), Create(), Disband(), GetLeaderGuid(), LoadGroupFromDB(), SendUpdateTo(), and UpdateOfflineLeader().
m_leaderLastOnline
time_t Group::m_leaderLastOnline protected
Definition at line 378 of file Group.h.
Referenced by _setLeader(), Create(), LoadGroupFromDB(), UpdateOfflineLeader(), and UpdatePlayerOnlineStatus().
m_leaderName
std::string Group::m_leaderName protected
Definition at line 377 of file Group.h.
Referenced by _setLeader(), AddLeaderInvite(), Create(), Disband(), GetLeaderName(), LoadGroupFromDB(), and RemoveMember().
m_lfgData
LFGData Group::m_lfgData protected
Definition at line 394 of file Group.h.
Referenced by GetLfgData().
m_lootMethod
LootMethod Group::m_lootMethod protected
Definition at line 387 of file Group.h.
Referenced by ConvertToLFG(), Create(), GetLootMethod(), LoadGroupFromDB(), SendUpdateTo(), and SetLootMethod().
m_lootThreshold
ItemQualities Group::m_lootThreshold protected
Definition at line 388 of file Group.h.
Referenced by Create(), GetLootThreshold(), LoadGroupFromDB(), SendUpdateTo(), and SetLootThreshold().
m_mainAssistantGuid
ObjectGuid Group::m_mainAssistantGuid protected
Definition at line 380 of file Group.h.
Referenced by _setMainAssistant(), _setMainTank(), Create(), GetFlags(), GetMainAssistantGuid(), and LoadGroupFromDB().
m_mainTankGuid
ObjectGuid Group::m_mainTankGuid protected
Definition at line 379 of file Group.h.
Referenced by _setMainAssistant(), _setMainTank(), Create(), GetFlags(), GetMainTankGuid(), and LoadGroupFromDB().
m_masterLooterGuid
ObjectGuid Group::m_masterLooterGuid protected
Definition at line 389 of file Group.h.
Referenced by Create(), GetMasterLooterGuid(), LoadGroupFromDB(), SendUpdateTo(), and SetMasterLooterGuid().
m_memberMgr
GroupRefManager Group::m_memberMgr protected
Definition at line 374 of file Group.h.
Referenced by GetFirstMember(), and LinkMember().
m_memberSlots
MemberSlotList Group::m_memberSlots protected
Definition at line 373 of file Group.h.
Referenced by _addMember(), _chooseLeader(), _getMemberCSlot(), _getMemberWSlot(), _initRaidSubGroupsCounter(), _removeMember(), _setAssistantFlag(), _setLeader(), _setMainAssistant(), _setMainTank(), _setMembersGroup(), ChangeLeader(), ConvertToRaid(), Disband(), GetMemberGroup(), GetMemberGuid(), GetMembersCount(), GetMemberSlots(), IsAssistant(), IsFull(), IsMember(), LoadMemberFromDB(), OfflineReadyCheck(), RemoveMember(), ResetInstances(), SendUpdate(), SendUpdateTo(), and SetPlayerMap().
m_raidDifficulty
Difficulty Group::m_raidDifficulty protected
Definition at line 383 of file Group.h.
Referenced by Create(), GetDifficulty(), GetRaidDifficulty(), LoadGroupFromDB(), SendUpdateTo(), and SetRaidDifficulty().
m_subGroupsCounts
uint8* Group::m_subGroupsCounts protected
Definition at line 392 of file Group.h.
Referenced by _addMember(), _initRaidSubGroupsCounter(), HasFreeSlotSubGroup(), SubGroupCounterDecrease(), SubGroupCounterIncrease(), and ~Group().
m_targetIcons
ObjectGuid Group::m_targetIcons[TARGET_ICON_COUNT] protected
Definition at line 386 of file Group.h.
Referenced by _addMember(), Create(), LoadGroupFromDB(), SendTargetIconList(), and SetTargetIcon().
The documentation for this class was generated from the following files:
Group.h
Group.cpp