CMaNGOS_WoTLK: ByteBuffer Class Reference
ByteBuffer Class Reference
#include <ByteBuffer.h>
Data Structures
struct Reserve
struct Resize
Public Member Functions
ByteBuffer (size_t reservedSize=s_defaultSize)
virtual ~ByteBuffer ()=default
ByteBuffer (const ByteBuffer &)=default
ByteBuffer (ByteBuffer &&byteBuffer) noexcept
ByteBuffer (size_t size, Reserve)
ByteBuffer (size_t size, Resize)
ByteBuffer & operator= (const ByteBuffer &)=default
ByteBuffer & operator= (ByteBuffer &&byteBuffer) noexcept
void clear ()
template<typename T >
void put (size_t pos, T value)
ByteBuffer & operator<< (uint8 value)
ByteBuffer & operator<< (uint16 value)
ByteBuffer & operator<< (uint32 value)
ByteBuffer & operator<< (uint64 value)
ByteBuffer & operator<< (int8 value)
ByteBuffer & operator<< (int16 value)
ByteBuffer & operator<< (int32 value)
ByteBuffer & operator<< (int64 value)
ByteBuffer & operator<< (float value)
ByteBuffer & operator<< (double value)
ByteBuffer & operator<< (const std::string &value)
ByteBuffer & operator<< (const char *str)
ByteBuffer & operator>> (bool &value)
ByteBuffer & operator>> (uint8 &value)
ByteBuffer & operator>> (uint16 &value)
ByteBuffer & operator>> (uint32 &value)
ByteBuffer & operator>> (uint64 &value)
ByteBuffer & operator>> (int8 &value)
ByteBuffer & operator>> (int16 &value)
ByteBuffer & operator>> (int32 &value)
ByteBuffer & operator>> (int64 &value)
ByteBuffer & operator>> (float &value)
ByteBuffer & operator>> (double &value)
ByteBuffer & operator>> (std::string &value)
template<class T >
ByteBuffer & operator>> (Unused< T > const &)
uint8 operator[] (size_t pos) const
size_t rpos () const
size_t rpos (size_t rpos_)
size_t wpos () const
size_t wpos (size_t wpos_)
template<typename T >
void read_skip ()
void read_skip (size_t skip)
template<typename T >
T read ()
template<typename T >
T read (size_t pos) const
void read (uint8 *dest, size_t len)
void read (std::string &value, bool utf8)
uint64 readPackGUID ()
const uint8 * contents () const
size_t size () const
bool empty () const
void resize (size_t newsize)
void reserve (size_t ressize)
void append (const std::string &str)
void append (const char *src, size_t cnt)
template<class T >
void append (const T *src, size_t cnt)
void append (const uint8 *src, size_t cnt)
void append (const std::vector< uint8 > &buffer)
void append (const ByteBuffer &buffer)
void appendPackXYZ (float x, float y, float z)
void appendPackGUID (uint64 guid)
void put (size_t pos, const uint8 *src, size_t cnt)
void print_storage () const
void textlike () const
void hexlike () const
template<>
void read_skip ()
template<>
void read_skip ()
Private Member Functions
template<typename T >
void append (T value)
Private Attributes
size_t _rpos
size_t _wpos
std::vector< uint8 > _storage
Static Private Attributes
static constexpr size_t s_defaultSize = 0x1000
Detailed Description
Definition at line 49 of file ByteBuffer.h.
Constructor & Destructor Documentation
ByteBuffer() [1/5]
ByteBuffer::ByteBuffer (size_t reservedSize = s_defaultSize) inline explicit
Definition at line 53 of file ByteBuffer.h.
References _storage.
~ByteBuffer()
virtual ByteBuffer::~ByteBuffer () virtual default
ByteBuffer() [2/5]
ByteBuffer::ByteBuffer (const ByteBuffer &) default
ByteBuffer() [3/5]
ByteBuffer::ByteBuffer (ByteBuffer && byteBuffer) inline noexcept
Definition at line 62 of file ByteBuffer.h.
ByteBuffer() [4/5]
ByteBuffer::ByteBuffer (size_t size, Reserve) inline
Definition at line 73 of file ByteBuffer.h.
References _storage, and size().
ByteBuffer() [5/5]
ByteBuffer::ByteBuffer (size_t size, Resize) inline
Definition at line 78 of file ByteBuffer.h.
References _storage, and size().
Member Function Documentation
append() [1/7]
void ByteBuffer::append (const ByteBuffer & buffer) inline
Definition at line 414 of file ByteBuffer.h.
References append(), contents(), and wpos().
append() [2/7]
void ByteBuffer::append (const char * src, size_t cnt) inline
Definition at line 386 of file ByteBuffer.h.
References append().
append() [3/7]
void ByteBuffer::append (const std::string & str) inline
Definition at line 381 of file ByteBuffer.h.
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), Pet::_LoadSpellCooldowns(), append(), appendPackGUID(), WardenWin::BuildFileHashInit(), WardenWin::BuildLuaInit(), UpdateData::BuildPacket(), WardenWin::BuildTimingInit(), Object::BuildValuesUpdate(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleGameObjectQueryOpcode(), WorldSession::HandleRequestAccountData(), WardenWin::InitializeClient(), WardenMac::LoadScriptedScans(), Player::LockOutSpells(), WorldSocket::Open(), MaNGOS::EmoteChatBuilder::operator()(), operator<<(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), Warden::RequestChallenge(), Warden::RequestScans(), Warden::SendModuleToClient(), Warden::SendPacket(), WorldSession::SendRedirectClient(), Warden::Warden(), Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), and Movement::PacketBuilder::WriteCreate().
append() [4/7]
void ByteBuffer::append (const std::vector< uint8 > & buffer) inline
Definition at line 409 of file ByteBuffer.h.
References append().
append() [5/7]
template<class T > void ByteBuffer::append (const T * src, size_t cnt) inline
Definition at line 391 of file ByteBuffer.h.
References append().
append() [6/7]
void ByteBuffer::append (const uint8 * src, size_t cnt) inline
Definition at line 396 of file ByteBuffer.h.
References _storage, _wpos, MANGOS_ASSERT, and size().
append() [7/7]
template<typename T > void ByteBuffer::append (T value) inline private
Definition at line 463 of file ByteBuffer.h.
References append(), and EndianConvert().
appendPackGUID()
void ByteBuffer::appendPackGUID (uint64 guid) inline
Definition at line 430 of file ByteBuffer.h.
References append(), and size().
Referenced by AchievementMgr::BuildAllDataPacket(), Object::BuildMovementUpdate(), PlayerbotAI::HandleBotOutgoingPacket(), SpellLog::Initialize(), PlayerbotMgr::OnBotLogin(), PackedGuid::PackedGuid(), CalendarMgr::SendCalendarEventInviteRemove(), AchievementMgr::SendCriteriaUpdate(), Player::SendEquipmentSetList(), PackedGuid::Set(), and Player::SetEquipmentSet().
appendPackXYZ()
void ByteBuffer::appendPackXYZ (float x, float y, float z) inline
Definition at line 421 of file ByteBuffer.h.
Referenced by Movement::WriteLinearPath().
clear()
void ByteBuffer::clear () inline
Definition at line 99 of file ByteBuffer.h.
References _rpos, _storage, and _wpos.
Referenced by PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleGuildMOTDOpcode(), WorldPacket::Initialize(), Channel::Invite(), Channel::Join(), Channel::Leave(), operator>>(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), WardenMac::Update(), WardenWin::Update(), and Player::Whisper().
contents()
const uint8* ByteBuffer::contents () const inline
Definition at line 363 of file ByteBuffer.h.
References _storage.
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleReconnectProof(), append(), WardenWin::BuildFileHashInit(), WardenWin::BuildLuaInit(), UpdateData::BuildPacket(), WardenWin::BuildTimingInit(), Warden::HandleChallengeResponse(), Warden::HandlePacket(), WorldSession::HandleRequestAccountData(), WorldSession::HandleUpdateAccountData(), HexToBytes(), PacketLog::LogPacket(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), NullSessionAnticheat::ReadAddonInfo(), Warden::SendPacket(), and WorldSocket::SendPacket().
empty()
bool ByteBuffer::empty () const inline
Definition at line 366 of file ByteBuffer.h.
References _storage.
Referenced by UpdateData::BuildPacket(), WorldSession::HandleGuildMOTDOpcode(), WorldSession::HandleRaidReadyCheckOpcode(), PacketLog::LogPacket(), WorldStateExpressionMgr::Meets(), WorldSocket::SendPacket(), WardenMac::Update(), and WardenWin::Update().
hexlike()
void ByteBuffer::hexlike () const
Definition at line 62 of file ByteBuffer.cpp.
References LOG_LVL_DEBUG, size(), and sLog.
Referenced by WorldSession::HandleCalendarEventStatus(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleChannelVoiceOnOpcode(), ChatHandler::HandleDebugSendOpcodeCommand(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleEjectPassenger(), WorldSession::HandleEquipmentSetUseOpcode(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveNotActiveMoverOpcode(), WorldSession::HandlePageTextQueryOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleRequestVehicleSwitchSeat(), WorldSession::HandleRideVehicleInteract(), WorldSession::HandleSetActiveMoverOpcode(), WorldSession::HandleSetActiveVoiceChannel(), WorldSession::HandleVoiceSessionEnableOpcode(), and WorldSession::ProcessByteBufferException().
operator<<() [1/12]
ByteBuffer& ByteBuffer::operator<< (const char * str) inline
Definition at line 180 of file ByteBuffer.h.
References append().
operator<<() [2/12]
ByteBuffer& ByteBuffer::operator<< (const std::string & value) inline
Definition at line 173 of file ByteBuffer.h.
References append().
operator<<() [3/12]
ByteBuffer& ByteBuffer::operator<< (double value) inline
Definition at line 167 of file ByteBuffer.h.
operator<<() [4/12]
ByteBuffer& ByteBuffer::operator<< (float value) inline
Definition at line 161 of file ByteBuffer.h.
operator<<() [5/12]
ByteBuffer& ByteBuffer::operator<< (int16 value) inline
Definition at line 142 of file ByteBuffer.h.
operator<<() [6/12]
ByteBuffer& ByteBuffer::operator<< (int32 value) inline
Definition at line 148 of file ByteBuffer.h.
operator<<() [7/12]
ByteBuffer& ByteBuffer::operator<< (int64 value) inline
Definition at line 154 of file ByteBuffer.h.
operator<<() [8/12]
ByteBuffer& ByteBuffer::operator<< (int8 value) inline
Definition at line 136 of file ByteBuffer.h.
operator<<() [9/12]
ByteBuffer& ByteBuffer::operator<< (uint16 value) inline
Definition at line 117 of file ByteBuffer.h.
operator<<() [10/12]
ByteBuffer& ByteBuffer::operator<< (uint32 value) inline
Definition at line 123 of file ByteBuffer.h.
operator<<() [11/12]
ByteBuffer& ByteBuffer::operator<< (uint64 value) inline
Definition at line 129 of file ByteBuffer.h.
operator<<() [12/12]
ByteBuffer& ByteBuffer::operator<< (uint8 value) inline
Definition at line 111 of file ByteBuffer.h.
operator=() [1/2]
ByteBuffer& ByteBuffer::operator= (ByteBuffer && byteBuffer) inline noexcept
Definition at line 85 of file ByteBuffer.h.
References _rpos, _storage, and _wpos.
operator=() [2/2]
ByteBuffer& ByteBuffer::operator= (const ByteBuffer &) default
operator>>() [1/13]
ByteBuffer& ByteBuffer::operator>> (bool & value) inline
Definition at line 187 of file ByteBuffer.h.
operator>>() [2/13]
ByteBuffer& ByteBuffer::operator>> (double & value) inline
Definition at line 248 of file ByteBuffer.h.
operator>>() [3/13]
ByteBuffer& ByteBuffer::operator>> (float & value) inline
Definition at line 242 of file ByteBuffer.h.
operator>>() [4/13]
ByteBuffer& ByteBuffer::operator>> (int16 & value) inline
Definition at line 224 of file ByteBuffer.h.
operator>>() [5/13]
ByteBuffer& ByteBuffer::operator>> (int32 & value) inline
Definition at line 230 of file ByteBuffer.h.
operator>>() [6/13]
ByteBuffer& ByteBuffer::operator>> (int64 & value) inline
Definition at line 236 of file ByteBuffer.h.
operator>>() [7/13]
ByteBuffer& ByteBuffer::operator>> (int8 & value) inline
Definition at line 218 of file ByteBuffer.h.
operator>>() [8/13]
ByteBuffer& ByteBuffer::operator>> (std::string & value) inline
Definition at line 254 of file ByteBuffer.h.
References read().
operator>>() [9/13]
ByteBuffer& ByteBuffer::operator>> (uint16 & value) inline
Definition at line 199 of file ByteBuffer.h.
operator>>() [10/13]
ByteBuffer& ByteBuffer::operator>> (uint32 & value) inline
Definition at line 205 of file ByteBuffer.h.
operator>>() [11/13]
ByteBuffer& ByteBuffer::operator>> (uint64 & value) inline
Definition at line 211 of file ByteBuffer.h.
operator>>() [12/13]
ByteBuffer& ByteBuffer::operator>> (uint8 & value) inline
Definition at line 193 of file ByteBuffer.h.
operator>>() [13/13]
template<class T > ByteBuffer& ByteBuffer::operator>> (Unused< T > const &) inline
Definition at line 261 of file ByteBuffer.h.
operator[]()
uint8 ByteBuffer::operator[] (size_t pos) const inline
Definition at line 267 of file ByteBuffer.h.
print_storage()
void ByteBuffer::print_storage () const
Definition at line 28 of file ByteBuffer.cpp.
References LOG_LVL_DEBUG, size(), and sLog.
put() [1/2]
void ByteBuffer::put (size_t pos, const uint8 * src, size_t cnt) inline
Definition at line 450 of file ByteBuffer.h.
References _storage, and size().
put() [2/2]
template<typename T > void ByteBuffer::put (size_t pos, T value) inline
Definition at line 105 of file ByteBuffer.h.
References EndianConvert().
Referenced by Guild::AppendDisplayGuildBankSlot(), BattleGroundMgr::BuildBattleGroundListPacket(), Player::BuildEnchantmentsInfoData(), UpdateData::BuildPacket(), Player::BuildPetTalentsInfoData(), Player::BuildPlayerTalentsInfoData(), Unit::CharmCooldownInitialize(), Guild::DisplayGuildBankContentUpdate(), SpellLog::FinalizePrevious(), Loot::GetLootContentFor(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionListItems(), WorldSession::HandleAuctionListOwnerItems(), WorldSession::HandleAuctionListPendingSales(), WorldSession::HandleCharEnum(), WorldSession::HandleGetMailList(), WorldSession::HandleQueryNextMailTime(), WorldSession::HandleQueryQuestsCompletedOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleWhoOpcode(), Guild::MassInviteToEvent(), Player::PetSpellInitialize(), AchievementMgr::SendAchievementEarned(), Channel::SendChannelListResponse(), Spell::SendChannelStart(), Player::SendEquipmentSetList(), Player::SendInitialSpells(), Player::SendInitWorldStates(), WorldSession::SendListInventory(), PlayerMenu::SendQuestGiverQuestList(), Player::SendQuestGiverStatusMultiple(), Player::SendRaidInfo(), WorldSession::SendStablePet(), GroupLootRoll::SendStartRoll(), ReputationMgr::SendState(), SpellLog::SendToSet(), WorldSession::SendTrainerList(), Player::SendUnlearnSpells(), and Spell::WriteSpellGoTargets().
read() [1/4]
template<typename T > T ByteBuffer::read () inline
Definition at line 298 of file ByteBuffer.h.
References _rpos.
Referenced by EvalRelOp(), EvalSingleValue(), EvalValue(), WorldSocket::HandleAuthSession(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleMessagechatOpcode(), WorldStateExpressionMgr::Meets(), operator>>(), operator>>(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), and WardenWin::ValidateEndScene().
read() [2/4]
template<typename T > T ByteBuffer::read (size_t pos) const inline
Definition at line 305 of file ByteBuffer.h.
References _storage, EndianConvert(), and size().
read() [3/4]
void ByteBuffer::read (std::string & value, bool utf8) inline
Definition at line 328 of file ByteBuffer.h.
References _rpos, rpos(), and size().
read() [4/4]
void ByteBuffer::read (uint8 * dest, size_t len) inline
Definition at line 320 of file ByteBuffer.h.
References _rpos, _storage, and size().
read_skip() [1/4]
template<typename T > void ByteBuffer::read_skip () inline
Definition at line 289 of file ByteBuffer.h.
References read_skip().
Referenced by WorldSession::HandleAcceptTradeOpcode(), WorldSocket::HandleAuthSession(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleCancelCastOpcode(), WorldSession::HandleCancelChanneling(), WorldSession::HandleGMSurveySubmitOpcode(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketUpdateTextOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupUninviteGuidOpcode(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleItemNameQueryOpcode(), WorldSession::HandleLeaveBattlefieldOpcode(), WorldSession::HandleMailDelete(), WorldSession::HandleMailReturnToSender(), WorldSession::HandlePageTextQueryOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandleRepopRequestOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSetActiveVoiceChannel(), WorldSession::HandleVoiceSessionEnableOpcode(), and read_skip().
read_skip() [2/4]
template<> void ByteBuffer::read_skip () inline
Definition at line 555 of file ByteBuffer.h.
read_skip() [3/4]
template<> void ByteBuffer::read_skip () inline
Definition at line 562 of file ByteBuffer.h.
read_skip() [4/4]
void ByteBuffer::read_skip (size_t skip) inline
Definition at line 291 of file ByteBuffer.h.
References _rpos, and size().
readPackGUID()
uint64 ByteBuffer::readPackGUID () inline
Definition at line 344 of file ByteBuffer.h.
Referenced by operator>>().
reserve()
void ByteBuffer::reserve (size_t ressize) inline
Definition at line 375 of file ByteBuffer.h.
References _storage, and size().
Referenced by WorldPacket::Initialize().
resize()
void ByteBuffer::resize (size_t newsize) inline
Definition at line 368 of file ByteBuffer.h.
References _rpos, _storage, _wpos, and size().
Referenced by UpdateData::BuildPacket(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleLfgJoinOpcode(), WorldSession::HandleRequestAccountData(), WorldSession::HandleUpdateAccountData(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), and NullSessionAnticheat::ReadAddonInfo().
rpos() [1/2]
size_t ByteBuffer::rpos () const inline
Definition at line 272 of file ByteBuffer.h.
References _rpos.
Referenced by WorldSession::ExecuteOpcode(), WorldSession::HandleActivateTaxiExpressOpcode(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleCastSpellOpcode(), Warden::HandleChallengeResponse(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleGuildRankOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMoveNotActiveMoverOpcode(), Warden::HandlePacket(), WorldSession::HandleQuestPOIQueryOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUseItemOpcode(), WorldSession::LogUnprocessedTail(), WorldStateExpressionMgr::Meets(), SpellCastTargets::read(), read(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), and NullSessionAnticheat::ReadAddonInfo().
rpos() [2/2]
size_t ByteBuffer::rpos (size_t rpos_) inline
Definition at line 274 of file ByteBuffer.h.
References _rpos.
size()
size_t ByteBuffer::size () const inline
Definition at line 365 of file ByteBuffer.h.
References _storage.
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleReconnectProof(), Pet::_LoadSpellCooldowns(), UpdateData::AddUpdateBlock(), append(), appendPackGUID(), ByteBuffer(), WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleGMSurveySubmitOpcode(), WorldSession::HandleGMTicketCreateOpcode(), WorldSession::HandleGMTicketUpdateTextOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleOpenItemOpcode(), Warden::HandlePacket(), WorldSession::HandlePetSetAction(), WorldSession::HandleTogglePvP(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUseItemOpcode(), hexlike(), HexToBytes(), PacketLog::LogPacket(), WorldStateExpressionMgr::Meets(), operator<<(), Log::outWorldPacketDump(), print_storage(), put(), SpellCastTargets::read(), read(), read_skip(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), NullSessionAnticheat::ReadAddonInfo(), reserve(), resize(), CalendarMgr::SendCalendarEvent(), WorldSession::SendExpectedSpamRecords(), WorldSession::SendMotd(), WorldSocket::SendPacket(), WorldSession::SendPacket(), PackedGuid::size(), WorldSession::SizeError(), and textlike().
textlike()
void ByteBuffer::textlike () const
Definition at line 45 of file ByteBuffer.cpp.
References LOG_LVL_DEBUG, size(), and sLog.
wpos() [1/2]
size_t ByteBuffer::wpos () const inline
Definition at line 280 of file ByteBuffer.h.
References _wpos.
Referenced by append(), Guild::AppendDisplayGuildBankSlot(), BattleGroundMgr::BuildBattleGroundListPacket(), Player::BuildEnchantmentsInfoData(), WardenWin::BuildFileHashInit(), WardenWin::BuildLuaInit(), UpdateData::BuildPacket(), Player::BuildPetTalentsInfoData(), Player::BuildPlayerTalentsInfoData(), WardenWin::BuildTimingInit(), Unit::CharmCooldownInitialize(), Guild::DisplayGuildBankContentUpdate(), WorldSession::ExecuteOpcode(), Loot::GetLootContentFor(), WorldSession::HandleActivateTaxiExpressOpcode(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleCastSpellOpcode(), Warden::HandleChallengeResponse(), WorldSession::HandleGetMailList(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleGuildRankOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMoveNotActiveMoverOpcode(), Warden::HandlePacket(), WorldSession::HandleQuestPOIQueryOpcode(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleUpdateAccountData(), WorldSession::HandleUseItemOpcode(), SpellLog::Initialize(), WardenWin::InitializeClient(), WorldSession::LogUnprocessedTail(), Player::PetSpellInitialize(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), Warden::RequestScans(), AchievementMgr::SendAchievementEarned(), Channel::SendChannelListResponse(), Spell::SendChannelStart(), Player::SendEquipmentSetList(), Player::SendInitialSpells(), Player::SendInitWorldStates(), WorldSession::SendListInventory(), Warden::SendPacket(), WorldSession::SendPacket(), PlayerMenu::SendQuestGiverQuestList(), Player::SendRaidInfo(), WorldSession::SendStablePet(), GroupLootRoll::SendStartRoll(), ReputationMgr::SendState(), WorldSession::SendTrainerList(), Player::SendUnlearnSpells(), PackedGuid::Set(), SpellLog::SetCurrentEffect(), and Spell::WriteSpellGoTargets().
wpos() [2/2]
size_t ByteBuffer::wpos (size_t wpos_) inline
Definition at line 282 of file ByteBuffer.h.
References _wpos.
Field Documentation
_rpos
size_t ByteBuffer::_rpos private
Definition at line 469 of file ByteBuffer.h.
Referenced by clear(), operator=(), read(), read_skip(), resize(), and rpos().
_storage
std::vector<uint8> ByteBuffer::_storage private
Definition at line 470 of file ByteBuffer.h.
Referenced by append(), ByteBuffer(), clear(), contents(), empty(), operator=(), put(), read(), reserve(), resize(), and size().
_wpos
size_t ByteBuffer::_wpos private
Definition at line 469 of file ByteBuffer.h.
Referenced by append(), clear(), operator=(), resize(), and wpos().
s_defaultSize
constexpr size_t ByteBuffer::s_defaultSize = 0x1000 static constexpr private
Definition at line 472 of file ByteBuffer.h.
The documentation for this class was generated from the following files:
ByteBuffer.h
ByteBuffer.cpp