CMaNGOS_WoTLK: MotionMaster Class Reference
MotionMaster Class Reference
#include <MotionMaster.h>
Public Types
typedef Impl::container_type::const_iterator const_iterator
Public Member Functions
MotionMaster (Unit *unit)
~MotionMaster ()
void Initialize ()
MovementGenerator const * GetCurrent () const
const_iterator begin () const
const_iterator end () const
void UpdateMotion (uint32 diff)
void Clear (bool reset=true, bool all=false)
void MovementExpired (bool reset=true)
void MoveIdle ()
void MoveRandomAroundPoint (float x, float y, float z, float radius, float verticalZ=0.0f, uint32 timer=0)
void MoveTargetedHome (bool runHome=true)
void MoveFollow (Unit *target, float dist, float angle, bool asMain=false, bool alwaysBoost=false)
void MoveInFormation (FormationSlotDataSPtr &sData, bool asMain=false)
void MoveStay (float x, float y, float z, float o=0, bool asMain=false)
void MoveChase (Unit *target, float dist=0.0f, float angle=0.0f, bool moveFurther=false, bool walk=false, bool combat=true, bool delayed=false)
void DistanceYourself (float dist)
void MoveConfused ()
void MoveFleeing (Unit *enemy, uint32 time=0)
void MovePoint (uint32 id, Position const &position, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, float speed=0.f, bool generatePath=true, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void MovePoint (uint32 id, float x, float y, float z, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, bool generatePath=true)
void MovePointTOL (uint32 id, float x, float y, float z, bool takeOff, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE)
void MovePath (std::vector< G3D::Vector3 > &path, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, bool flying=false)
void MovePath (std::vector< G3D::Vector3 > &path, float o, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, bool flying=false)
void MovePath (int32 pathId=0, WaypointPathOrigin wpOrigin=PATH_NO_PATH, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, bool flying=false, float speed=0.f, bool cyclic=false, ObjectGuid guid=ObjectGuid())
void MoveRetreat (float x, float y, float z, float o, uint32 delay)
void MoveWaypoint (uint32 pathId=0, uint32 source=0, uint32 initialDelay=0, uint32 overwriteEntry=0, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, ObjectGuid guid=ObjectGuid())
void MoveLinearWP (uint32 pathId=0, uint32 source=0, uint32 initialDelay=0, uint32 overwriteEntry=0, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, ObjectGuid guid=ObjectGuid())
void MoveTaxi ()
void MoveDistract (uint32 timer)
void MoveCharge (float x, float y, float z, float speed, uint32 id=EVENT_CHARGE)
void MoveCharge (Unit &target, float speed, uint32 id=EVENT_CHARGE)
bool MoveFall (ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void MoveKnockback (float x, float y, float z, float horizontalSpeed, float maxHeight, uint32 id=EVENT_JUMP)
void MoveJump (float x, float y, float z, float horizontalSpeed, float maxHeight, uint32 id=EVENT_JUMP)
void MoveJumpFacingVerticalSpeed (Position pos, float horizontalSpeed, float verticalSpeed, uint32 id=EVENT_JUMP, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void MoveJumpFacing (Position pos, float horizontalSpeed, float maxHeight, uint32 id=EVENT_JUMP, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void MovePathAndJumpVerticalSpeed (uint32 pathId, float horizontalSpeed, float verticalSpeed, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, ObjectGuid guid=ObjectGuid())
void MovePathAndJump (uint32 pathId, float horizontalSpeed, float maxHeight, ForcedMovement forcedMovement=FORCED_MOVEMENT_NONE, ObjectGuid guid=ObjectGuid())
MovementGeneratorType GetCurrentMovementGeneratorType () const
void propagateSpeedChange ()
bool SetNextWaypoint (uint32 pointId)
uint32 getLastReachedWaypoint () const
void GetWaypointPathInformation (std::ostringstream &oss) const
bool GetDestination (float &x, float &y, float &z) const
void SetDefaultPathId (uint32 pathId)
uint32 GetPathId () const
void InterruptPanic ()
void PauseWaypoints (uint32 time)
void UnpauseWaypoints ()
void UnMarkFollowMovegens ()
Private Types
typedef std::stack< MovementGenerator * > Impl
typedef std::vector< MovementGenerator * > ExpireList
Private Member Functions
void Mutate (MovementGenerator *m)
void DirectClean (bool reset, bool all)
void DelayedClean (bool reset, bool all)
void DirectExpire (bool reset)
void DelayedExpire (bool reset)
Private Attributes
Unit * m_owner
ExpireList * m_expList
uint8 m_cleanFlag
uint32 m_defaultPathId
uint32 m_currentPathId
Detailed Description
Definition at line 96 of file MotionMaster.h.
Member Typedef Documentation
const_iterator
typedef Impl::container_type::const_iterator MotionMaster::const_iterator
Definition at line 115 of file MotionMaster.h.
ExpireList
typedef std::vector<MovementGenerator*> MotionMaster::ExpireList private
Definition at line 100 of file MotionMaster.h.
Impl
typedef std::stack<MovementGenerator*> MotionMaster::Impl private
Definition at line 99 of file MotionMaster.h.
Constructor & Destructor Documentation
MotionMaster()
MotionMaster::MotionMaster (Unit * unit) inline explicit
Definition at line 104 of file MotionMaster.h.
~MotionMaster()
MotionMaster::~MotionMaster ()
Definition at line 103 of file MotionMaster.cpp.
References isStatic().
Member Function Documentation
begin()
const_iterator MotionMaster::begin () const inline
Definition at line 116 of file MotionMaster.h.
Referenced by ChatHandler::HandleMovegensCommand().
Clear()
void MotionMaster::Clear (bool reset = true, bool all = false) inline
Definition at line 120 of file MotionMaster.h.
References DelayedClean(), DirectClean(), m_cleanFlag, and MMCF_UPDATE.
Referenced by VehicleInfo::ApplySeatMods(), boss_sindragosaAI::AttackStart(), npc_klinfranAI::BeginEvent(), npc_solenorAI::BeginEvent(), npc_artoriusAI::BeginEvent(), PlayerbotAI::CastSpell(), npc_theramore_spar_controller::CombatantSeparate(), npc_brann_hosAI::CompleteTribunalEvent(), Map::CreatureRespawnRelocation(), npc_rethhedronAI::DamageTaken(), boss_black_knightAI::DamageTaken(), trial_companion_commonAI::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), boss_feral_defenderAI::DamageTaken(), mob_vrykul_skeletonAI::DamageTaken(), npc_anubarak_trial_frostsphereAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), boss_aerial_unitAI::DamageTaken(), npc_scrap_reaverAI::Die(), boss_ymironAI::DoChannelSpiritYmiron(), PlayerbotAI::DoCombatMovement(), CreatureAI::DoFakeDeath(), PlayerbotAI::DoLoot(), boss_brundirAI::DoMoveToTarget(), boss_head_of_horsemanAI::DoRejoinHead(), boss_lady_deathwhisperAI::DoStartSecondPhase(), trial_companion_commonAI::DoUseNearbyMountIfCan(), EffectAuraDummy_npc_scourged_flamespitter(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_volkhan_anvil(), npc_manaforge_spawnAI::EnterEvadeMode(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyCreature(), npc_commanderAI::FinishedWaypointMovement(), npc_razorthorn_ravager_pet::HandleAnimations(), PlayerbotAI::HandleBotOutgoingPacket(), npc_scrap_reaverAI::HandleKill(), boss_scarlet_commander_mograineAI::HandleLayOnHandsTimer(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePetActionHelper(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_high_inquisitor_whitemaneAI::HandleResurrection(), Initialize(), npc_grark_lorkrubAI::JustDidDialogueStep(), npc_brann_hosAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), boss_thekalBaseAI::JustPreventedDeath(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_illidan_stormrageAI::JustPreventedDeath(), essence_base_AI::JustPreventedDeath(), mob_mature_netherwing_drakeAI::JustReachedHome(), mob_bt_battle_fighterAI::JustReachedHome(), npc_zulian_prowlerAI::JustRespawned(), boss_kiljaedenAI::JustSummoned(), boss_terokkAI::JustSummoned(), MoveFollow(), MoveInFormation(), npc_theramore_spar_controller::MoveIntoPosition(), mob_ashtongue_sorcererAI::MovementInform(), npc_shade_of_the_horsemanAI::MovementInform(), boss_nightbaneAI::MovementInform(), boss_felmystAI::MovementInform(), boss_nalorakkAI::MovementInform(), boss_sir_zeliekAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), boss_broggokAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_ethereal_frostworgAI::MovementInform(), npc_akama_illidanAI::MovementInform(), npc_amanishi_hatcherAI::MovementInform(), boss_blood_queen_lanathelAI::MovementInform(), boss_hadronoxAI::MovementInform(), boss_icehowlAI::MovementInform(), dummy_dragonAI::MovementInform(), npc_colonel_julesAI::MovementInform(), npc_anchorite_baradaAI::MovementInform(), npc_vimgol_AI::MovementInform(), MoveStay(), MoveTargetedHome(), spell_strangulating_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), instance_pit_of_saron::OnCreatureDeath(), instance_pit_of_saron::OnCreatureEnterCombat(), npc_hungry_nether_rayAI::OwnerKilledUnit(), npc_anubarak_trial_spikeAI::PermafrostHit(), boss_mr_smiteAI::PhaseEquipStart(), npc_brann_hosAI::PrepareTribunalEvent(), CreatureEventAI::ProcessAction(), twin_jormungars_commonAI::ReceiveAIEvent(), npc_skyguard_aether_techAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), npc_anubarak_trial_spikeAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), boss_malygosAI::ReceiveAIEvent(), npc_decaying_ghoulAI::ReceiveAIEvent(), mob_soaring_eagleAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), VehicleInfo::RemoveSeatMods(), npc_snakesAI::Reset(), ScriptedPetAI::ResetPetCombat(), Unit::SetDeathState(), FollowerAI::SetFollowComplete(), FollowerAI::SetFollowPaused(), mob_arugal_voidwalkerAI::SetLeader(), boss_leviathan_mk2AI::SpellHit(), boss_zuljinAI::SpellHit(), boss_drakkari_colossusAI::SpellHit(), boss_aerial_unitAI::SpellHit(), boss_brutallusAI::SpellHitTarget(), npc_escortAI::Start(), npc_adyen_the_lightwardenAI::StartEvent(), FollowerAI::StartFollow(), boss_alarAI::StartPhaseTransition(), npc_brann_hosAI::StartSjonnirEvent(), npc_brann_hosAI::StartTribunalEvent(), npc_spring_rabbitAI::StartWhatRabbitsDo(), PlayerbotMgr::Stay(), npc_eris_havenfireAI::SummonedMovementInform(), boss_terokkAI::SummonedMovementInform(), boss_lady_vashjAI::SummonedMovementInform(), boss_the_lurker_belowAI::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), npc_theramore_spar_controller::SwitchMembers(), Unit::TakePossessOf(), Unit::Uncharm(), instance_stratholme::Update(), npc_kyle_the_frenziedAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), npc_oil_stained_wolfAI::UpdateAI(), boss_icehowlAI::UpdateAI(), npc_firecrackers_bunnyAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_savianaAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_morokkAI::UpdateEscortAI(), PlayerbotAI::UseItem(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_adyen_the_lightwardenAI::WaypointReached(), npc_taelan_fordringAI::WaypointReached(), npc_tirion_fordringAI::WaypointReached(), npc_cork_gizeltonAI::WaypointReached(), and npc_prospector_anvilwardAI::WaypointReached().
DelayedClean()
void MotionMaster::DelayedClean (bool reset, bool all) private
Definition at line 181 of file MotionMaster.cpp.
References MovementGenerator::Finalize(), isStatic(), m_cleanFlag, m_expList, m_owner, and MMCF_RESET.
Referenced by Clear().
DelayedExpire()
void MotionMaster::DelayedExpire (bool reset) private
Definition at line 244 of file MotionMaster.cpp.
References MovementGenerator::Finalize(), isStatic(), m_cleanFlag, m_expList, m_owner, and MMCF_RESET.
Referenced by MovementExpired().
DirectClean()
void MotionMaster::DirectClean (bool reset, bool all) private
Definition at line 162 of file MotionMaster.cpp.
References MovementGenerator::Finalize(), isStatic(), m_owner, and MANGOS_ASSERT.
Referenced by Clear().
DirectExpire()
void MotionMaster::DirectExpire (bool reset) private
Definition at line 205 of file MotionMaster.cpp.
References EFFECT_MOTION_TYPE, MovementGenerator::Finalize(), MovementGenerator::GetMovementGeneratorType(), Initialize(), isStatic(), and m_owner.
Referenced by MovementExpired().
DistanceYourself()
void MotionMaster::DistanceYourself (float dist)
Definition at line 341 of file MotionMaster.cpp.
References CHASE_MOTION_TYPE, GetCurrentMovementGeneratorType(), and m_owner.
Referenced by UnitAI::DistanceYourself().
end()
const_iterator MotionMaster::end () const inline
Definition at line 117 of file MotionMaster.h.
Referenced by ChatHandler::HandleMovegensCommand(), propagateSpeedChange(), and UnMarkFollowMovegens().
GetCurrent()
MovementGenerator const* MotionMaster::GetCurrent () const inline
Definition at line 109 of file MotionMaster.h.
Referenced by CreatureEventAI::CheckEvent(), UnitAI::ExecuteActions(), UnitConditionMgr::getConditionValue(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), and ChatHandler::HandleWpShowCommand().
GetCurrentMovementGeneratorType()
MovementGeneratorType MotionMaster::GetCurrentMovementGeneratorType () const
Definition at line 767 of file MotionMaster.cpp.
References IDLE_MOTION_TYPE.
Referenced by mob_arugal_voidwalkerAI::CheckGroupStatus(), DistanceYourself(), EffectDummyCreature_boss_ionar(), EffectDummyCreature_npc_aged_dying_ancient_kodo(), FollowerAI::EnterEvadeMode(), ScriptAction::ExecuteDbscriptCommand(), UnitAI::HandleMovementOnAttackStart(), ChatHandler::HandleNpcUnFollowCommand(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), mob_bt_battle_fighterAI::JustReachedHome(), MoveChase(), MoveLinearWP(), MoveTaxi(), MoveWaypoint(), npc_sunblade_protectorAI::npc_sunblade_protectorAI(), DawnbladeAttack::OnCheckTarget(), spell_align_disk_aggro::OnEffectExecute(), PauseWaypoints(), CreatureEventAI::ProcessAction(), npc_klinfranAI::Reset(), npc_solenorAI::Reset(), npc_artoriusAI::Reset(), UnitAI::SetCombatMovement(), instance_stratholme::SetData(), FollowerAI::SetFollowComplete(), UnitAI::SetFollowMovement(), FollowerAI::SetFollowPaused(), npc_kyle_the_frenziedAI::SpellHit(), FollowerAI::StartFollow(), UnpauseWaypoints(), instance_stratholme::Update(), PetAI::UpdateAI(), PlayerbotAI::UpdateAI(), boss_ionarAI::UpdateAI(), and mob_mature_netherwing_drakeAI::UpdateAI().
GetDestination()
bool MotionMaster::GetDestination (float & x, float & y, float & z) const
Definition at line 787 of file MotionMaster.cpp.
References Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::Finalized(), m_owner, and Unit::movespline.
Referenced by ChatHandler::HandleMovegensCommand(), and MaNGOS::NearUsedPosDo::operator()().
getLastReachedWaypoint()
uint32 MotionMaster::getLastReachedWaypoint () const
Definition at line 757 of file MotionMaster.cpp.
References WAYPOINT_MOTION_TYPE.
Referenced by FormationData::ClearMoveGen(), npc_arthasAI::GetAIInformation(), FormationData::OnDeath(), and instance_halls_of_reflection::OnPlayerEnter().
GetPathId()
uint32 MotionMaster::GetPathId () const inline
Definition at line 177 of file MotionMaster.h.
References m_currentPathId.
Referenced by FormationData::ClearMoveGen(), ChatHandler::HandleDebugWaypoint(), ChatHandler::HandleWpExportCommand(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), npc_shade_of_the_horsemanAI::MovementInform(), npc_core_of_entropiusAI::MovementInform(), npc_harkorAI::MovementInform(), npc_tanzarAI::MovementInform(), npc_ashliAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_akama_illidanAI::MovementInform(), npc_amanishi_hatcherAI::MovementInform(), npc_rethhedronAI::MovementInform(), FormationData::OnDeath(), boss_terokkAI::SummonedMovementInform(), boss_lady_vashjAI::SummonedMovementInform(), boss_illidan_stormrageAI::SummonedMovementInform(), npc_shade_of_the_horsemanAI::UpdateAI(), and npc_spawned_oronok_tornheartAI::WaypointMotionType().
GetWaypointPathInformation()
void MotionMaster::GetWaypointPathInformation (std::ostringstream & oss) const
Definition at line 775 of file MotionMaster.cpp.
References WaypointMovementGenerator< Creature >::GetPathInformation(), and WAYPOINT_MOTION_TYPE.
Referenced by npc_escortAI::GetAIInformation().
Initialize()
void MotionMaster::Initialize ()
Definition at line 59 of file MotionMaster.cpp.
References Clear(), Object::GetDbGuid(), Object::GetEntry(), Object::GetGUIDHigh(), Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), Unit::hasUnitState(), Object::IsCreature(), LINEAR_WP_MOTION_TYPE, m_currentPathId, m_defaultPathId, m_owner, PATH_FROM_WAYPOINT_PATH, PATH_NO_PATH, FactorySelector::selectMovementGenerator(), si_idleMovement, Unit::StopMoving(), UNIT_STAT_POSSESSED, and WAYPOINT_MOTION_TYPE.
Referenced by Creature::AIM_Initialize(), FormationData::ClearMoveGen(), Map::CreatureRespawnRelocation(), DirectExpire(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), WorldSession::HandlePlayerLogin(), ChatHandler::HandleWpModifyCommand(), PlayerbotAI::MovementClear(), FormationData::Remove(), VehicleInfo::RemoveSeatMods(), npc_klinfranAI::Reset(), npc_solenorAI::Reset(), npc_artoriusAI::Reset(), Creature::SetDeathState(), Unit::Uncharm(), and UpdateMotion().
InterruptPanic()
void MotionMaster::InterruptPanic ()
Definition at line 674 of file MotionMaster.cpp.
References MovementExpired(), and TIMED_FLEEING_MOTION_TYPE.
Referenced by UnitAI::CheckForHelp().
MoveCharge() [1/2]
void MotionMaster::MoveCharge (float x, float y, float z, float speed, uint32 id = EVENT_CHARGE)
Definition at line 546 of file MotionMaster.cpp.
References Unit::hasUnitState(), m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), and UNIT_STAT_NO_FREE_MOVE.
Referenced by Spell::EffectCharge(), Spell::EffectChargeDest(), and ZombieChowSearch::OnPeriodicTrigger().
MoveCharge() [2/2]
void MotionMaster::MoveCharge (Unit & target, float speed, uint32 id = EVENT_CHARGE)
Definition at line 559 of file MotionMaster.cpp.
References WorldObject::GetAngle(), Unit::GetCombatReach(), WorldObject::GetFirstCollisionPosition(), Unit::hasUnitState(), m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), UNIT_STAT_NO_FREE_MOVE, Position::x, Position::y, and Position::z.
MoveChase()
void MotionMaster::MoveChase (Unit * target, float dist = 0.0f, float angle = 0.0f, bool moveFurther = false, bool walk = false, bool combat = true, bool delayed = false)
Definition at line 320 of file MotionMaster.cpp.
References CHASE_MOTION_TYPE, DEBUG_FILTER_LOG, GetCurrentMovementGeneratorType(), Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by ScriptedPetAI::AttackStart(), boss_ionarAI::AttackStart(), boss_ymironAI::DoChannelSpiritYmiron(), PlayerbotAI::DoCombatMovement(), boss_lady_vashjAI::DoInformGeneratorStopped(), UnitAI::DoStartMovement(), ScriptedAI::DoStartMovement(), boss_lady_deathwhisperAI::DoStartSecondPhase(), EffectDummyCreature_npc_volkhan_anvil(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), UnitAI::HandleMovementOnAttackStart(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_scarlet_commander_mograineAI::HandleRevivedTimer(), npc_corrupted_soul_fragmentAI::JustRespawned(), boss_kologarnAI::JustSummoned(), boss_grandmaster_vorpilAI::JustSummoned(), boss_archimondeAI::JustSummoned(), boss_xevozzAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_blood_queen_lanathelAI::MovementInform(), boss_sindragosaAI::MovementInform(), npc_rimefang_iccAI::MovementInform(), boss_jedogaAI::MovementInform(), boss_savianaAI::MovementInform(), boss_brundirAI::MovementInform(), boss_icehowlAI::MovementInform(), npc_vimgol_AI::MovementInform(), spell_dark_transformation_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_tag_troll::OnEffectExecute(), spell_align_disk_aggro::OnEffectExecute(), CreatureEventAI::ProcessAction(), twin_jormungars_commonAI::ReceiveAIEvent(), npc_anubarak_trial_spikeAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), npc_power_sparkAI::ReceiveAIEvent(), npc_power_sparkAI::Reset(), npc_planar_anomalyAI::Reset(), boss_zuljinAI::SpellHit(), boss_drakkari_colossusAI::SpellHit(), boss_kelthuzadAI::StartPhase2(), PlayerbotAI::UpdateAI(), npc_rookery_hatcherAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_ionarAI::UpdateAI(), npc_ingvar_throw_dummyAI::UpdateAI(), boss_lajAI::UpdateAI(), and boss_grand_astromancer_capernianAI::UpdateAI().
MoveConfused()
void MotionMaster::MoveConfused ()
Definition at line 313 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by Unit::SetConfused(), Unit::SetFleeing(), Unit::TakePossessOf(), and Unit::Uncharm().
MoveDistract()
void MotionMaster::MoveDistract (uint32 timer)
Definition at line 539 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by UnitAI::DetectOrAttack(), and Spell::EffectDistract().
MoveFall()
bool MotionMaster::MoveFall (ObjectGuid guid = ObjectGuid(), uint32 relayId = 0)
Definition at line 577 of file MotionMaster.cpp.
References DEBUG_LOG, EVENT_FALL, Map::GetHeight(), Map::GetId(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), INVALID_HEIGHT, m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), and Movement::MoveSplineInit::SetFall().
Referenced by npc_anubarak_trial_frostsphereAI::DamageTaken(), ScriptAction::ExecuteDbscriptCommand(), boss_brutallusAI::JustDidDialogueStep(), spell_strangulating_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), ATangledSkeinEncasingWebsEffect::OnEffectExecute(), Unit::SetDeathState(), boss_brutallusAI::SpellHitTarget(), and boss_brutallusAI::SummonedMovementInform().
MoveFleeing()
void MotionMaster::MoveFleeing (Unit * enemy, uint32 time = 0)
Definition at line 455 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by EffectDummyCreature_spell_dummy_npc(), Unit::SetConfused(), Unit::SetFleeing(), Unit::TakePossessOf(), and Unit::Uncharm().
MoveFollow()
void MotionMaster::MoveFollow (Unit * target, float dist, float angle, bool asMain = false, bool alwaysBoost = false)
Definition at line 351 of file MotionMaster.cpp.
References Clear(), DEBUG_FILTER_LOG, Object::GetGuidStr(), Object::HasFlag(), Unit::hasUnitState(), Object::IsPlayer(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and UNIT_STAT_LOST_CONTROL.
Referenced by GuardianAI::CombatStop(), PlayerbotRogueAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVP(), npc_mistress_nagmaraAI::DoPotionOfLoveIfCan(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectDummyCreature_npc_aged_dying_ancient_kodo(), EffectDummyCreature_spell_dummy_npc(), PlayerAI::EnterEvadeMode(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), npc_razorthorn_ravager_pet::HandleAnimations(), Aura::HandleAuraDummy(), PlayerbotAI::HandleBotOutgoingPacket(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleNpcFollowCommand(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), PlayerAI::JustGotCharmed(), npc_spawned_oronok_tornheartAI::JustRespawned(), boss_ambassador_flamelashAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_ogronAI::JustSummoned(), boss_taldaram_iccAI::JustSummoned(), npc_storm_tempered_keeperAI::JustSummoned(), boss_terokkAI::JustSummoned(), boss_mekgineer_steamriggerAI::JustSummoned(), PlayerbotAI::MovementReset(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), spell_water_globule_missile::OnEffectExecute(), SummonCrusaderLeCraft::OnSummon(), SummonCrusaderLamoof::OnSummon(), SummonCrusaderJosephine::OnSummon(), npc_infantryAI::ReceiveAIEvent(), mob_soaring_eagleAI::ReceiveAIEvent(), npc_mojoAI::ReceiveEmote(), CreatureAI::RequestFollow(), npc_simone_the_inconspicuousAI::Reset(), npc_arcane_beamAI::Reset(), npc_mojoAI::Reset(), ScriptedPetAI::ResetPetCombat(), mob_arugal_voidwalkerAI::SetFollower(), CreatureLinkingHolder::SetFollowing(), FollowerAI::SetFollowPaused(), npc_evergrove_druidAI::SpellHit(), npc_rabid_bearAI::SpellHit(), FollowerAI::StartFollow(), npc_adyen_the_lightwardenAI::SummonedJustReachedHome(), Unit::TriggerHomeEvents(), PetAI::UpdateAI(), FollowerAI::UpdateAI(), ScriptedPetAI::UpdateAI(), npc_scrap_reaverAI::UpdateAI(), npc_mojoAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), npc_volatile_ooze_iccAI::UpdateAI(), npc_gas_cloud_iccAI::UpdateAI(), npc_living_flareAI::UpdateAI(), and npc_rocknotAI::WaypointReached().
MoveIdle()
void MotionMaster::MoveIdle ()
Definition at line 275 of file MotionMaster.cpp.
References isStatic(), and si_idleMovement.
Referenced by npc_amanishi_scoutAI::Aggro(), boss_alarAI::Aggro(), VehicleInfo::ApplySeatMods(), npc_klinfranAI::BeginEvent(), npc_solenorAI::BeginEvent(), npc_simone_the_inconspicuousAI::BeginEvent(), npc_artoriusAI::BeginEvent(), PlayerbotAI::CastSpell(), boss_black_knightAI::DamageTaken(), trial_companion_commonAI::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), boss_feral_defenderAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), npc_iron_constructAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), npc_scrap_reaverAI::Die(), boss_drakkari_colossusAI::DoEmergeElemental(), CreatureAI::DoFakeDeath(), PlayerbotAI::DoLoot(), instance_stratholme::DoMoveBackDefenders(), npc_mistress_nagmaraAI::DoPotionOfLoveIfCan(), boss_head_of_horsemanAI::DoRejoinHead(), ScriptedAI::DoStartNoMovement(), boss_kalecgosAI::DoStartOutro(), EffectDummyCreature_npc_aged_dying_ancient_kodo(), EffectDummyCreature_npc_oil_stained_wolf(), npc_isillienAI::EnterEvadeMode(), npc_grand_admiral_westwindAI::EnterEvadeMode(), npc_magister_aledisAI::EnterEvadeMode(), boss_jeklikAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyCreature(), npc_commanderAI::FinishedWaypointMovement(), npc_razorthorn_ravager_pet::HandleAnimations(), PlayerbotAI::HandleBotOutgoingPacket(), npc_scrap_reaverAI::HandleKill(), UnitAI::HandleMovementOnAttackStart(), boss_illidan_stormrageAI::HandlePhaseTransition(), npc_grark_lorkrubAI::JustDidDialogueStep(), boss_thekalBaseAI::JustPreventedDeath(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), boss_illidan_stormrageAI::JustPreventedDeath(), npc_laughing_skullAI::JustReachedHome(), npc_maghar_escortAI::JustReachedHome(), boss_brundirAI::JustSummoned(), npc_rabid_bearAI::MoveInLineOfSight(), npc_firecrackers_bunnyAI::MoveInLineOfSight(), npc_ball_of_flameAI::MoveInLineOfSight(), npc_evergrove_druidAI::MoveInLineOfSight(), mob_ashtongue_sorcererAI::MovementInform(), npc_shattered_hands_zealotAI::MovementInform(), guard_hallows_end_helperAI::MovementInform(), boss_nightbaneAI::MovementInform(), boss_felmystAI::MovementInform(), boss_nalorakkAI::MovementInform(), npc_harkorAI::MovementInform(), npc_tanzarAI::MovementInform(), npc_ashliAI::MovementInform(), boss_sir_zeliekAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), boss_broggokAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_corrupted_furbolgAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_nefarianAI::MovementInform(), npc_amanishi_hatcherAI::MovementInform(), npc_lazy_peonAI::MovementInform(), npc_spring_rabbitAI::MovementInform(), npc_rimefang_iccAI::MovementInform(), npc_spinestalker_iccAI::MovementInform(), npc_rookery_hatcherAI::MovementInform(), npc_felhound_trackerAI::MovementInform(), boss_hadronoxAI::MovementInform(), boss_malygosAI::MovementInform(), npc_decaying_ghoulAI::MovementInform(), npc_apexis_flayerAI::MovementInform(), npc_krunAI::MovementInform(), KoiKoiDeath::OnEffectExecute(), npc_anubarak_trial_spikeAI::PermafrostHit(), CreatureEventAI::ProcessAction(), twin_jormungars_commonAI::ReceiveAIEvent(), boss_malygosAI::ReceiveAIEvent(), npc_power_sparkAI::ReceiveAIEvent(), npc_domesticated_felboarAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_dragonmaw_racerAI::Reset(), ScriptedPetAI::ResetPetCombat(), Unit::SetDeathState(), FollowerAI::SetFollowComplete(), FollowerAI::SetFollowPaused(), npc_aged_dying_ancient_kodoAI::SpellHit(), npc_forest_frogAI::SpellHit(), npc_kyle_the_frenziedAI::SpellHit(), boss_brutallusAI::SpellHitTarget(), FollowerAI::StartFollow(), boss_alarAI::StartPhaseTransition(), npc_manaforge_control_consoleAI::SummonedMovementInform(), npc_daphne_stilwellAI::SummonedMovementInform(), npc_shattered_hand_legionnaire::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), Unit::TakePossessOf(), Unit::Uncharm(), instance_stratholme::Update(), npc_krazAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_xt_002AI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), npc_soulgrinderAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), boss_lajAI::UpdateAI(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_adyen_the_lightwardenAI::WaypointReached(), npc_taelan_fordringAI::WaypointReached(), npc_tirion_fordringAI::WaypointReached(), npc_rocknotAI::WaypointReached(), and npc_prospector_anvilwardAI::WaypointReached().
MoveInFormation()
void MotionMaster::MoveInFormation (FormationSlotDataSPtr & sData, bool asMain = false)
Definition at line 370 of file MotionMaster.cpp.
References Clear(), DEBUG_FILTER_LOG, Object::GetGuidStr(), Unit::hasUnitState(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), and UNIT_STAT_LOST_CONTROL.
MoveJump()
void MotionMaster::MoveJump (float x, float y, float z, float horizontalSpeed, float maxHeight, uint32 id = EVENT_JUMP)
Definition at line 611 of file MotionMaster.cpp.
References m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), Movement::MoveSplineInit::SetParabolic(), and Movement::MoveSplineInit::SetVelocity().
Referenced by boss_forgemaster_garfrostAI::ExecuteAction(), boss_thorimAI::JustDidDialogueStep(), instance_azjol_nerub::OnCreatureRespawn(), npc_scarlet_ghoulAI::ReceiveAIEvent(), and boss_icehowlAI::UpdateAI().
MoveJumpFacing()
void MotionMaster::MoveJumpFacing (Position pos, float horizontalSpeed, float maxHeight, uint32 id = EVENT_JUMP, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0)
Definition at line 627 of file MotionMaster.cpp.
References m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), Position::o, Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetParabolic(), Movement::MoveSplineInit::SetVelocity(), Position::x, Position::y, and Position::z.
Referenced by MoveJumpFacingVerticalSpeed().
MoveJumpFacingVerticalSpeed()
void MotionMaster::MoveJumpFacingVerticalSpeed (Position pos, float horizontalSpeed, float verticalSpeed, uint32 id = EVENT_JUMP, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0)
Definition at line 620 of file MotionMaster.cpp.
References Movement::computeFallElevation(), Movement::gravity, and MoveJumpFacing().
Referenced by Spell::EffectJump(), and ScriptAction::ExecuteDbscriptCommand().
MoveKnockback()
void MotionMaster::MoveKnockback (float x, float y, float z, float horizontalSpeed, float maxHeight, uint32 id = EVENT_JUMP)
Definition at line 601 of file MotionMaster.cpp.
References m_owner, Movement::MoveSplineInit::MoveTo(), Mutate(), Movement::MoveSplineInit::SetOrientationFixed(), Movement::MoveSplineInit::SetParabolic(), and Movement::MoveSplineInit::SetVelocity().
Referenced by Unit::KnockBackWithAngle().
MoveLinearWP()
void MotionMaster::MoveLinearWP (uint32 pathId = 0, uint32 source = 0, uint32 initialDelay = 0, uint32 overwriteEntry = 0, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, ObjectGuid guid = ObjectGuid())
Definition at line 494 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, GetCurrentMovementGeneratorType(), Object::GetGuidStr(), Object::GetTypeId(), WaypointMovementGenerator< Creature >::InitializeWaypointPath(), LINEAR_WP_MOTION_TYPE, LOG_FILTER_AI_AND_MOVEGENSS, m_currentPathId, m_owner, Mutate(), WaypointMovementGenerator< Creature >::SetForcedMovement(), WaypointMovementGenerator< Creature >::SetGuid(), sLog, and TYPEID_UNIT.
Referenced by ScriptAction::ExecuteDbscriptCommand(), and CreatureEventAI::ProcessAction().
MovementExpired()
void MotionMaster::MovementExpired (bool reset = true) inline
Definition at line 127 of file MotionMaster.h.
References DelayedExpire(), DirectExpire(), m_cleanFlag, and MMCF_UPDATE.
Referenced by Spell::EffectDummy(), EffectDummyCreature_boss_ionar(), Spell::EffectScriptEffect(), npc_disciple_of_naralexAI::EnterEvadeMode(), ChatHandler::HandleNpcUnFollowCommand(), InterruptPanic(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), Mutate(), Unit::SetConfused(), instance_stratholme::SetData(), Unit::SetFleeing(), npc_kyle_the_frenziedAI::SpellHit(), Player::TaxiFlightInterrupt(), UnMarkFollowMovegens(), PetAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), and UpdateMotion().
MovePath() [1/3]
void MotionMaster::MovePath (int32 pathId = 0, WaypointPathOrigin wpOrigin = PATH_NO_PATH, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, bool flying = false, float speed = 0.f, bool cyclic = false, ObjectGuid guid = ObjectGuid())
Definition at line 443 of file MotionMaster.cpp.
References m_currentPathId, m_owner, and Mutate().
MovePath() [2/3]
void MotionMaster::MovePath (std::vector< G3D::Vector3 > & path, float o, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, bool flying = false)
Definition at line 427 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
MovePath() [3/3]
void MotionMaster::MovePath (std::vector< G3D::Vector3 > & path, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, bool flying = false)
Definition at line 422 of file MotionMaster.cpp.
Referenced by boss_nightbaneAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), boss_headless_horsemanAI::JustRespawned(), boss_felmystAI::JustRespawned(), boss_kiljaedenAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), npc_shade_of_the_horsemanAI::MovementInform(), boss_felmystAI::MovementInform(), OpenPortalFromShattrath::OnApply(), CreatureEventAI::ProcessAction(), QuestAccept_npc_dragonmaw_racer(), npc_kalecgosAI::Reset(), boss_nightbaneAI::StartIntro(), boss_ayamissAI::StartLanding(), npc_shade_of_the_horsemanAI::StartLanding(), boss_lady_vashjAI::SummonedMovementInform(), and npc_shade_of_the_horsemanAI::UpdateAI().
MovePathAndJump()
void MotionMaster::MovePathAndJump (uint32 pathId, float horizontalSpeed, float maxHeight, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, ObjectGuid guid = ObjectGuid())
Definition at line 645 of file MotionMaster.cpp.
References Mutate().
Referenced by MovePathAndJumpVerticalSpeed().
MovePathAndJumpVerticalSpeed()
void MotionMaster::MovePathAndJumpVerticalSpeed (uint32 pathId, float horizontalSpeed, float verticalSpeed, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, ObjectGuid guid = ObjectGuid())
Definition at line 638 of file MotionMaster.cpp.
References Movement::computeFallElevation(), Movement::gravity, and MovePathAndJump().
Referenced by ScriptAction::ExecuteDbscriptCommand().
MovePoint() [1/2]
void MotionMaster::MovePoint (uint32 id, float x, float y, float z, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, bool generatePath = true)
Definition at line 411 of file MotionMaster.cpp.
References MovePoint().
MovePoint() [2/2]
void MotionMaster::MovePoint (uint32 id, Position const & position, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, float speed = 0.f, bool generatePath = true, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0)
Definition at line 406 of file MotionMaster.cpp.
References Mutate(), Position::o, Position::x, Position::y, and Position::z.
Referenced by PlayerbotAI::_HandleCommandFind(), npc_amanishi_scoutAI::Aggro(), boss_jeklikAI::Aggro(), boss_lady_blaumeuxAI::Aggro(), boss_rivendare_naxxAI::Aggro(), boss_thane_korthazzAI::Aggro(), boss_sir_zeliekAI::Aggro(), boss_alarAI::Aggro(), boss_felmystAI::Aggro(), boss_sindragosaAI::AttackStart(), npc_rimefang_iccAI::AttackStart(), npc_spinestalker_iccAI::AttackStart(), boss_taldaramAI::boss_taldaramAI(), boss_sartharionAI::CallDragon(), npc_living_flareAI::CheckPortalDist(), npc_theramore_spar_controller::CombatantSeparate(), npc_private_hendelAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), boss_aerial_unitAI::DamageTaken(), npc_shadowlord_deathwailAI::DoBeginDescent(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), npc_cenarion_sparrowhawkAI::DoFindNearbyStones(), npc_felhound_trackerAI::DoFindNewCrystal(), npc_rookery_hatcherAI::DoFindNewEgg(), npc_snufflenose_gopherAI::DoFindNewTubber(), boss_alarAI::DoFlameQuills(), PlayerbotAI::DoLoot(), instance_stratholme::DoMoveBackDefenders(), boss_vazruden_heraldAI::DoMoveToCenter(), boss_vazruden_heraldAI::DoMoveToCombat(), npc_fel_guard_houndAI::DoMoveToCorpse(), npc_general_andorovAI::DoMoveToEventLocation(), boss_brundirAI::DoMoveToTarget(), boss_alarAI::DoPlatformMove(), boss_midnightAI::DoPrepareMount(), boss_selin_fireheartAI::DoSelectNearestCrystal(), boss_vazruden_heraldAI::DoSplit(), npc_akamaAI::DoStartEvent(), boss_algalonAI::DoStartIntroEvent(), npc_Shattered_Hand_Scout::DoStartRunning(), trial_companion_commonAI::DoUseNearbyMountIfCan(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), EffectAuraDummy_npc_scourged_flamespitter(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_oil_stained_wolf(), Spell::EffectScriptEffect(), FollowerAI::EnterEvadeMode(), npc_tirion_fordringAI::EnterEvadeMode(), npc_general_andorovAI::EnterEvadeMode(), npc_living_mojoAI::EnterEvadeMode(), npc_rimefang_iccAI::EnterEvadeMode(), npc_spinestalker_iccAI::EnterEvadeMode(), npc_manaforge_spawnAI::EnterEvadeMode(), npc_spawned_oronok_tornheartAI::EnterEvadeMode(), npc_millhouse_manastormAI::EnterEvadeMode(), boss_dalliahAI::EnterEvadeMode(), boss_soccothratesAI::EnterEvadeMode(), npc_sunblade_scoutAI::ExecuteAction(), boss_alarAI::ExecuteAction(), npc_highlord_darion_mograineAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_warlord_kalithreshAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), ScriptAction::ExecuteDbscriptCommand(), boss_zuljinAI::ExecutePhaseTransition(), boss_sartharionAI::FetchDragons(), PlayerbotAI::findNearbyCreature(), npc_shadow_demonAI::FindNewTarget(), PlayerbotClassAI::FleeFromPointIfCan(), world_map_kalimdor::GhostOPlasmEventStep(), npc_lazy_peonAI::GoLumberPile(), GossipSelect_npc_barrett_ramsey(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_spawned_oronok_tornheart(), ChildTbcAI::HandleAerisLanding(), npc_razorthorn_ravager_pet::HandleAnimations(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), Aura::HandleAuraDummy(), boss_felmystAI::HandleBreath(), ChildTbcAI::HandleCallOfTheFarseer(), ChatHandler::HandleComeToMeCommand(), boss_kalecgosAI::HandleExit(), boss_felmystAI::HandleFelmystSpawnDelay(), ChildTbcAI::HandleHchuuAndTheMushroomPeople(), boss_felmystAI::HandleLiftoff(), npc_general_andorovAI::HandleMove(), ChildTbcAI::HandleNowWhenIGrowUp(), boss_majordomoAI::HandleOutro(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_felmystAI::HandlePreBreath(), ChildTbcAI::HandleSeatOfTheNaaru(), boss_felmystAI::HandleSideMove(), ChildTbcAI::HandleTripToTheDarkPortal(), ChildTbcAI::HandleVisitTheThroneOfTheElements(), instance_blackrock_spire::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), npc_smolderwing::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_queen_lanathel_introAI::JustDidDialogueStep(), boss_malygosAI::JustDidDialogueStep(), npc_millhouse_manastormAI::JustDidDialogueStep(), boss_soccothratesAI::JustDidDialogueStep(), essence_base_AI::JustPreventedDeath(), boss_sindragosaAI::JustReachedHome(), npc_zulian_prowlerAI::JustRespawned(), npc_grimstoneAI::JustSummoned(), npc_eris_havenfireAI::JustSummoned(), boss_thermapluggAI::JustSummoned(), npc_blastmaster_emi_shortfuseAI::JustSummoned(), npc_00x09hlAI::JustSummoned(), npc_rinjiAI::JustSummoned(), npc_image_of_medivhAI::JustSummoned(), npc_deathstalker_faerleiaAI::JustSummoned(), npc_arthasAI::JustSummoned(), npc_time_riftAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_ogronAI::JustSummoned(), boss_onyxiaAI::JustSummoned(), npc_twiggy_flatheadAI::JustSummoned(), npc_beast_combat_stalkerAI::JustSummoned(), npc_crystal_channel_targetAI::JustSummoned(), npc_emilyAI::JustSummoned(), boss_valanar_iccAI::JustSummoned(), boss_lord_marrowgarAI::JustSummoned(), npc_putricides_trapAI::JustSummoned(), boss_algalonAI::JustSummoned(), boss_mimironAI::JustSummoned(), boss_heart_deconstructorAI::JustSummoned(), boss_ingvarAI::JustSummoned(), npc_prison_event_controllerAI::JustSummoned(), npc_shaheenAI::JustSummoned(), npc_fhwoorAI::JustSummoned(), npc_squire_roweAI::JustSummoned(), boss_eranikusAI::JustSummoned(), boss_viscidusAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), npc_doom_blossomAI::JustSummoned(), boss_doomwalkerAI::JustSummoned(), npc_totem_of_spiritsAI::JustSummoned(), instance_trial_of_the_champion::MoveChampionToHome(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_jennyAI::MoveInLineOfSight(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_theramore_spar_controller::MoveIntoPosition(), npc_shattered_hands_zealotAI::MovementInform(), boss_nightbaneAI::MovementInform(), boss_felmystAI::MovementInform(), boss_vazruden_heraldAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), npc_akama_illidanAI::MovementInform(), npc_concentrated_bulletAI::MovementInform(), boss_blood_queen_lanathelAI::MovementInform(), boss_sindragosaAI::MovementInform(), npc_rimefang_iccAI::MovementInform(), npc_spinestalker_iccAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_general_andorovAI::MovementInform(), npc_krunAI::MovementInform(), MovePoint(), npc_apexis_flayerAI::MoveToCrystal(), npc_ethereal_frostworgAI::MoveToNewPoint(), npc_deadsoul_orb::MoveToNextTrigger(), NetherCharge::MoveToRandomPoint(), spell_lingering_fumes_targetting::OnAfterHit(), spell_grip_of_agony_aura::OnApply(), instance_pit_of_saron::OnCreatureDeath(), instance_pit_of_saron::OnCreatureEnterCombat(), instance_dark_portal::OnCreatureEvade(), instance_violet_hold::OnCreatureEvade(), spell_slave_trigger_closest::OnEffectExecute(), spell_out_cold::OnEffectExecute(), GluthDecimate::OnEffectExecute(), SummonGargoyle::OnSummon(), npc_hungry_nether_rayAI::OwnerKilledUnit(), boss_mr_smiteAI::PhaseEquipStart(), ProcessEventId_event_go_focusing_iris(), boss_illidan_stormrageAI::ReceiveAIEvent(), npc_spirit_prisoner_of_bladespire::ReceiveAIEvent(), boss_silithidRoyaltyAI::ReceiveAIEvent(), boss_malygosAI::ReceiveAIEvent(), npc_decaying_ghoulAI::ReceiveAIEvent(), npc_domesticated_felboarAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_concentrated_bulletAI::Reset(), npc_floating_spiritAI::Reset(), world_map_outland::ScriptAction(), instance_stratholme::SetData(), boss_onyxiaAI::SpellHit(), boss_shade_of_akamaAI::SpellHit(), npc_forest_frogAI::SpellHit(), boss_tethyrAI::SpellHit(), boss_aerial_unitAI::SpellHit(), npc_injured_patientAI::SpellHit(), boss_alarAI::StartPhaseTransition(), npc_spring_rabbitAI::StartWhatRabbitsDo(), boss_jedogaAI::SummonedCreatureJustDied(), npc_manaforge_control_consoleAI::SummonedMovementInform(), npc_image_of_medivhAI::SummonedMovementInform(), npc_thrall_old_hillsbradAI::SummonedMovementInform(), npc_anachronos_the_ancientAI::SummonedMovementInform(), npc_daphne_stilwellAI::SummonedMovementInform(), npc_air_force_botsAI::SummonGuard(), npc_theramore_spar_controller::SwitchMembers(), instance_stratholme::Update(), instance_sethekk_halls::Update(), npc_forest_frogAI::UpdateAI(), boss_eranikusAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), npc_eye_of_acherusAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), npc_lazy_peonAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), boss_jedogaAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), boss_icehowlAI::UpdateAI(), npc_firecrackers_bunnyAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), npc_rimefang_iccAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), dummy_dragonAI::UpdateAI(), boss_savianaAI::UpdateAI(), boss_volkhanAI::UpdateAI(), npc_dark_matterAI::UpdateAI(), boss_brundirAI::UpdateAI(), npc_hodir_fury_reticleAI::UpdateAI(), boss_aerial_unitAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), boss_ymironAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_vimgol_AI::UpdateAI(), npc_bird_spiritAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), npc_kernobeeAI::UpdateFollowerAI(), npc_toogaAI::UpdateFollowerAI(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_tirion_fordringAI::WaypointReached(), and npc_rocknotAI::WaypointReached().
MovePointTOL()
void MotionMaster::MovePointTOL (uint32 id, float x, float y, float z, bool takeOff, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE)
Definition at line 416 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by boss_nightbaneAI::DoMoveToClosestTrigger(), boss_razorscaleAI::ReceiveAIEvent(), boss_onyxiaAI::UpdateAI(), and boss_razorscaleAI::UpdateAI().
MoveRandomAroundPoint()
void MotionMaster::MoveRandomAroundPoint (float x, float y, float z, float radius, float verticalZ = 0.0f, uint32 timer = 0)
Definition at line 281 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), Object::GetTypeId(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), sLog, and TYPEID_PLAYER.
Referenced by boss_razorscaleAI::boss_razorscaleAI(), npc_apexis_flayerAI::CrystalStrike(), ScriptAction::ExecuteDbscriptCommand(), boss_razorscaleAI::JustReachedHome(), boss_algalonAI::JustSummoned(), npc_colonel_julesAI::JustSummoned(), boss_highlord_kruulAI::JustSummoned(), boss_ossirianAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), npc_shade_of_the_horsemanAI::MovementInform(), npc_magrami_spectre::MovementInform(), spell_strangulating_aura::OnApply(), CreatureEventAI::ProcessAction(), boss_head_of_horsemanAI::ReceiveAIEvent(), npc_anubarak_trial_frostsphereAI::Reset(), npc_snakesAI::Reset(), npc_death_rayAI::UpdateAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), and npc_magwinAI::WaypointReached().
MoveRetreat()
void MotionMaster::MoveRetreat (float x, float y, float z, float o, uint32 delay)
Definition at line 449 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, and Mutate().
Referenced by CreatureAI::DoRetreat().
MoveStay()
void MotionMaster::MoveStay (float x, float y, float z, float o = 0, bool asMain = false)
Definition at line 391 of file MotionMaster.cpp.
References Clear(), DEBUG_FILTER_LOG, Object::GetGuidStr(), Unit::hasUnitState(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), and UNIT_STAT_LOST_CONTROL.
Referenced by PetAI::UpdateAI().
MoveTargetedHome()
void MotionMaster::MoveTargetedHome (bool runHome = true)
Definition at line 297 of file MotionMaster.cpp.
References Clear(), DEBUG_FILTER_LOG, Object::GetGuidStr(), Object::GetTypeId(), Unit::hasUnitState(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), sLog, TYPEID_UNIT, and UNIT_STAT_LOST_CONTROL.
Referenced by UnitAI::EnterEvadeMode(), FollowerAI::EnterEvadeMode(), hyjalAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), npc_grand_admiral_westwindAI::EnterEvadeMode(), boss_freyaAI::EnterEvadeMode(), boss_hodirAI::EnterEvadeMode(), boss_thorimAI::EnterEvadeMode(), npc_spawned_oronok_tornheartAI::EnterEvadeMode(), npc_dirty_larryAI::NextStep(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_evergrove_druidAI::ReceiveAIEvent(), and boss_majordomoAI::SummonedCreatureJustDied().
MoveTaxi()
void MotionMaster::MoveTaxi ()
Definition at line 520 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, GetCurrentMovementGeneratorType(), Object::GetGuidStr(), Object::GetTypeId(), LOG_FILTER_AI_AND_MOVEGENSS, m_owner, Mutate(), sLog, TAXI_MOTION_TYPE, and TYPEID_UNIT.
Referenced by Player::ActivateTaxiPathTo(), and Player::TaxiFlightResume().
MoveWaypoint()
void MotionMaster::MoveWaypoint (uint32 pathId = 0, uint32 source = 0, uint32 initialDelay = 0, uint32 overwriteEntry = 0, ForcedMovement forcedMovement = FORCED_MOVEMENT_NONE, ObjectGuid guid = ObjectGuid())
Definition at line 468 of file MotionMaster.cpp.
References DEBUG_FILTER_LOG, GetCurrentMovementGeneratorType(), Object::GetGuidStr(), Object::GetTypeId(), WaypointMovementGenerator< Creature >::InitializeWaypointPath(), LOG_FILTER_AI_AND_MOVEGENSS, m_currentPathId, m_owner, Mutate(), WaypointMovementGenerator< Creature >::SetForcedMovement(), WaypointMovementGenerator< Creature >::SetGuid(), sLog, TYPEID_UNIT, and WAYPOINT_MOTION_TYPE.
Referenced by npc_brann_hosAI::CompleteTribunalEvent(), npc_rethhedronAI::DamageTaken(), npc_private_hendelAI::DamageTaken(), instance_violet_hold::DoReleaseBoss(), instance_scholomance::DoRespawnEntranceRoom(), npc_akama_illidanAI::DoResumeEvent(), instance_culling_of_stratholme::DoSpawnArthasIfNeeded(), npc_highlord_darion_mograineAI::DoStartConclusion(), npc_magister_aledisAI::EnterEvadeMode(), ScriptAction::ExecuteDbscriptCommand(), GossipSelect_npc_brann_ulduar(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_sinclari(), GossipSelect_npc_tobias_seecher(), ChatHandler::HandleDebugWaypoint(), ChildTbcAI::HandleTripToTheDarkPortal(), npc_flame_tsunamiAI::HandleTsunamiDamage(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_brann_hosAI::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), mob_bt_battle_fighterAI::JustReachedHome(), npc_highlord_darion_mograineAI::JustSummoned(), npc_time_riftAI::JustSummoned(), npc_prison_event_controllerAI::JustSummoned(), npc_credit_marker_they_must_burnAI::JustSummoned(), boss_janalaiAI::JustSummoned(), npc_keeper_remulosAI::JustSummoned(), boss_terokkAI::JustSummoned(), npc_aether_tech_vendorAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), boss_malygosAI::MovementInform(), instance_pinnacle::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_pit_of_saron::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), npc_brann_hosAI::PrepareTribunalEvent(), CreatureEventAI::ProcessAction(), boss_ambassador_hellmawAI::ReceiveAIEvent(), npc_skyguard_aether_techAI::ReceiveAIEvent(), npc_akama_illidanAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), mob_soaring_eagleAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), hyjalAI::ReceiveAIEvent(), world_map_outland::ScriptAction(), instance_zulaman::SendNextBearWave(), mob_arugal_voidwalkerAI::SetLeader(), npc_escortAI::Start(), npc_amanishi_lookoutAI::StartEvent(), npc_harkorAI::StartEvent(), npc_tanzarAI::StartEvent(), npc_krazAI::StartEvent(), npc_ashliAI::StartEvent(), npc_adyen_the_lightwardenAI::StartEvent(), boss_nefarianAI::StartLanding(), npc_brann_hosAI::StartSjonnirEvent(), npc_brann_hosAI::StartTribunalEvent(), npc_keeper_remulosAI::SummonedJustReachedHome(), boss_terokkAI::SummonedMovementInform(), npc_lazy_peonAI::UpdateAI(), npc_graufAI::UpdateAI(), boss_ambassador_hellmawAI::UpdateAI(), and npc_cork_gizeltonAI::WaypointReached().
Mutate()
void MotionMaster::Mutate (MovementGenerator * m) private
Definition at line 650 of file MotionMaster.cpp.
References DISTRACT_MOTION_TYPE, EFFECT_MOTION_TYPE, HOME_MOTION_TYPE, MovementGenerator::Initialize(), m_owner, and MovementExpired().
Referenced by MoveCharge(), MoveChase(), MoveConfused(), MoveDistract(), MoveFall(), MoveFleeing(), MoveFollow(), MoveInFormation(), MoveJump(), MoveJumpFacing(), MoveKnockback(), MoveLinearWP(), MovePath(), MovePathAndJump(), MovePoint(), MovePointTOL(), MoveRandomAroundPoint(), MoveRetreat(), MoveStay(), MoveTargetedHome(), MoveTaxi(), and MoveWaypoint().
PauseWaypoints()
void MotionMaster::PauseWaypoints (uint32 time)
Definition at line 681 of file MotionMaster.cpp.
References addUnitState(), GetCurrentMovementGeneratorType(), Object::IsCreature(), m_owner, PATH_MOTION_TYPE, Unit::StopMoving(), UNIT_STAT_WAYPOINT_PAUSED, and WAYPOINT_MOTION_TYPE.
Referenced by WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleQuestgiverHelloOpcode(), boss_lich_king_horAI::MoveInLineOfSight(), CreatureEventAI::ProcessAction(), WorldSession::SendListInventory(), npc_escortAI::SetEscortPaused(), and boss_malygosAI::UpdateAI().
propagateSpeedChange()
void MotionMaster::propagateSpeedChange ()
Definition at line 738 of file MotionMaster.cpp.
References end().
Referenced by Unit::propagateSpeedChange().
SetDefaultPathId()
void MotionMaster::SetDefaultPathId (uint32 pathId) inline
Definition at line 176 of file MotionMaster.h.
References m_defaultPathId.
Referenced by WorldObject::SummonCreature().
SetNextWaypoint()
bool MotionMaster::SetNextWaypoint (uint32 pointId)
Definition at line 747 of file MotionMaster.cpp.
References WAYPOINT_MOTION_TYPE.
Referenced by npc_colonel_julesAI::GoHome(), mob_bt_battle_fighterAI::JustReachedHome(), npc_colonel_julesAI::MovementInform(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_escortAI::SetCurrentWaypoint(), npc_ranshallaAI::UpdateEscortAI(), and npc_cork_gizeltonAI::WaypointReached().
UnMarkFollowMovegens()
void MotionMaster::UnMarkFollowMovegens ()
Definition at line 724 of file MotionMaster.cpp.
References end(), FOLLOW_MOTION_TYPE, and MovementExpired().
Referenced by Unit::Uncharm().
UnpauseWaypoints()
void MotionMaster::UnpauseWaypoints ()
Definition at line 704 of file MotionMaster.cpp.
References GetCurrentMovementGeneratorType(), Object::IsCreature(), m_owner, PATH_MOTION_TYPE, UNIT_STAT_WAYPOINT_PAUSED, and WAYPOINT_MOTION_TYPE.
Referenced by CreatureEventAI::ProcessAction(), npc_escortAI::SetEscortPaused(), and boss_malygosAI::UpdateAI().
UpdateMotion()
void MotionMaster::UpdateMotion (uint32 diff)
Definition at line 115 of file MotionMaster.cpp.
References Object::GetEntry(), Object::GetGUIDHigh(), Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), Unit::hasUnitState(), Initialize(), isStatic(), m_cleanFlag, m_expList, m_owner, MANGOS_ASSERT, MMCF_RESET, MMCF_UPDATE, MovementExpired(), and UNIT_STAT_CAN_NOT_MOVE.
Referenced by Unit::Update().
Field Documentation
m_cleanFlag
uint8 MotionMaster::m_cleanFlag private
Definition at line 197 of file MotionMaster.h.
Referenced by Clear(), DelayedClean(), DelayedExpire(), MovementExpired(), and UpdateMotion().
m_currentPathId
uint32 MotionMaster::m_currentPathId private
Definition at line 200 of file MotionMaster.h.
Referenced by GetPathId(), Initialize(), MoveLinearWP(), MovePath(), and MoveWaypoint().
m_defaultPathId
uint32 MotionMaster::m_defaultPathId private
Definition at line 199 of file MotionMaster.h.
Referenced by Initialize(), and SetDefaultPathId().
m_expList
ExpireList* MotionMaster::m_expList private
Definition at line 196 of file MotionMaster.h.
Referenced by DelayedClean(), DelayedExpire(), and UpdateMotion().
m_owner
Unit* MotionMaster::m_owner private
Definition at line 195 of file MotionMaster.h.
Referenced by DelayedClean(), DelayedExpire(), DirectClean(), DirectExpire(), DistanceYourself(), GetDestination(), Initialize(), MoveCharge(), MoveChase(), MoveConfused(), MoveDistract(), MoveFall(), MoveFleeing(), MoveFollow(), MoveInFormation(), MoveJump(), MoveJumpFacing(), MoveKnockback(), MoveLinearWP(), MovePath(), MovePointTOL(), MoveRandomAroundPoint(), MoveRetreat(), MoveStay(), MoveTargetedHome(), MoveTaxi(), MoveWaypoint(), Mutate(), PauseWaypoints(), UnpauseWaypoints(), and UpdateMotion().
The documentation for this class was generated from the following files:
MotionMaster.h
MotionMaster.cpp