CMaNGOS_WoTLK: MMAP::MMapManager Class Reference
MMAP::MMapManager Class Reference
#include <MoveMap.h>
Public Member Functions
MMapManager ()
~MMapManager ()
bool loadMap (uint32 mapId, uint32 instanceId, int32 x, int32 y, uint32 number)
bool loadMapData (uint32 mapId, uint32 instanceId)
void loadAllGameObjectModels (std::vector< uint32 > const &displayIds)
bool loadGameObject (uint32 displayId)
bool unloadMap (uint32 mapId, uint32 instanceId, int32 x, int32 y)
bool unloadMap (uint32 mapId)
bool unloadMapInstance (uint32 mapId, uint32 instanceId)
bool IsMMapTileLoaded (uint32 mapId, uint32 instanceId, uint32 x, uint32 y) const
dtNavMeshQuery const * GetNavMeshQuery (uint32 mapId, uint32 instanceId)
dtNavMeshQuery const * GetModelNavMeshQuery (uint32 displayId)
dtNavMesh const * GetNavMesh (uint32 mapId, uint32 instanceId)
dtNavMesh const * GetGONavMesh (uint32 displayId)
uint32 getLoadedTilesCount () const
uint32 getLoadedMapsCount () const
void ChangeTile (uint32 mapId, uint32 instanceId, uint32 tileX, uint32 tileY, uint32 tileNumber)
Private Member Functions
uint32 packTileID (int32 x, int32 y) const
uint64 packInstanceId (uint32 mapId, uint32 instanceId) const
Private Attributes
std::unordered_map< uint64, std::unique_ptr< MMapData > > m_loadedMMaps
uint32 m_loadedTiles
std::unordered_map< uint32, std::unique_ptr< MMapGOData > > m_loadedModels
std::mutex m_modelsMutex
Detailed Description
Definition at line 91 of file MoveMap.h.
Constructor & Destructor Documentation
MMapManager()
MMAP::MMapManager::MMapManager () inline
Definition at line 94 of file MoveMap.h.
~MMapManager()
MMAP::MMapManager::~MMapManager ()
Definition at line 119 of file MoveMap.cpp.
Member Function Documentation
ChangeTile()
void MMAP::MMapManager::ChangeTile (uint32 mapId, uint32 instanceId, uint32 tileX, uint32 tileY, uint32 tileNumber)
Definition at line 125 of file MoveMap.cpp.
References loadMap(), and unloadMap().
Referenced by Map::ChangeGOPathfinding(), and Map::SetNavTile().
GetGONavMesh()
dtNavMesh const * MMAP::MMapManager::GetGONavMesh (uint32 displayId)
Definition at line 478 of file MoveMap.cpp.
References m_loadedModels.
getLoadedMapsCount()
uint32 MMAP::MMapManager::getLoadedMapsCount () const inline
Definition at line 113 of file MoveMap.h.
References m_loadedMMaps.
Referenced by ChatHandler::HandleMmapStatsCommand().
getLoadedTilesCount()
uint32 MMAP::MMapManager::getLoadedTilesCount () const inline
Definition at line 112 of file MoveMap.h.
References m_loadedTiles.
Referenced by ChatHandler::HandleMmapStatsCommand().
GetModelNavMeshQuery()
dtNavMeshQuery const * MMAP::MMapManager::GetModelNavMeshQuery (uint32 displayId)
Definition at line 513 of file MoveMap.cpp.
References DETAIL_LOG, m_loadedModels, m_modelsMutex, MANGOS_ASSERT, and sLog.
Referenced by PathFinder::SetCurrentNavMesh().
GetNavMesh()
dtNavMesh const * MMAP::MMapManager::GetNavMesh (uint32 mapId, uint32 instanceId)
Definition at line 469 of file MoveMap.cpp.
References m_loadedMMaps, and packInstanceId().
Referenced by ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), and ChatHandler::HandleMmapStatsCommand().
GetNavMeshQuery()
dtNavMeshQuery const * MMAP::MMapManager::GetNavMeshQuery (uint32 mapId, uint32 instanceId)
Definition at line 486 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, LOG_FILTER_MAP_LOADING, m_loadedMMaps, MANGOS_ASSERT, packInstanceId(), and sLog.
Referenced by ChatHandler::HandleMmapLoadedTilesCommand(), ChatHandler::HandleMmapLocCommand(), PathFinder::PathFinder(), and PathFinder::SetCurrentNavMesh().
IsMMapTileLoaded()
bool MMAP::MMapManager::IsMMapTileLoaded (uint32 mapId, uint32 instanceId, uint32 x, uint32 y) const
Definition at line 185 of file MoveMap.cpp.
References m_loadedMMaps, packInstanceId(), and packTileID().
loadAllGameObjectModels()
void MMAP::MMapManager::loadAllGameObjectModels (std::vector< uint32 > const & displayIds)
Definition at line 285 of file MoveMap.cpp.
References loadGameObject().
Referenced by World::SetInitialWorldSettings().
loadGameObject()
bool MMAP::MMapManager::loadGameObject (uint32 displayId)
Definition at line 291 of file MoveMap.cpp.
References DEBUG_LOG, DETAIL_LOG, m_loadedModels, MANGOS_ASSERT, MMAP_MAGIC, MMAP_VERSION, MmapTileHeader::mmapMagic, MmapTileHeader::mmapVersion, MmapTileHeader::size, sLog, and sWorld.
Referenced by loadAllGameObjectModels().
loadMap()
bool MMAP::MMapManager::loadMap (uint32 mapId, uint32 instanceId, int32 x, int32 y, uint32 number)
Definition at line 202 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, loadMapData(), LOG_FILTER_MAP_LOADING, m_loadedMMaps, m_loadedTiles, MANGOS_ASSERT, MMAP_MAGIC, MMAP_VERSION, MmapTileHeader::mmapMagic, MmapTileHeader::mmapVersion, packInstanceId(), packTileID(), MmapTileHeader::size, sLog, and sWorld.
Referenced by ChangeTile(), and Map::LoadMapAndVMap().
loadMapData()
bool MMAP::MMapManager::loadMapData (uint32 mapId, uint32 instanceId)
Definition at line 131 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, MMAP::MMapFactory::IsPathfindingEnabled(), LOG_FILTER_MAP_LOADING, m_loadedMMaps, MANGOS_ASSERT, packInstanceId(), sLog, and sWorld.
Referenced by Map::Initialize(), and loadMap().
packInstanceId()
uint64 MMAP::MMapManager::packInstanceId (uint32 mapId, uint32 instanceId) const private
Definition at line 180 of file MoveMap.cpp.
Referenced by GetNavMesh(), GetNavMeshQuery(), IsMMapTileLoaded(), loadMap(), loadMapData(), unloadMap(), and unloadMapInstance().
packTileID()
uint32 MMAP::MMapManager::packTileID (int32 x, int32 y) const private
Definition at line 175 of file MoveMap.cpp.
Referenced by IsMMapTileLoaded(), loadMap(), and unloadMap().
unloadMap() [1/2]
bool MMAP::MMapManager::unloadMap (uint32 mapId)
Definition at line 402 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, LOG_FILTER_MAP_LOADING, m_loadedMMaps, m_loadedTiles, and sLog.
unloadMap() [2/2]
bool MMAP::MMapManager::unloadMap (uint32 mapId, uint32 instanceId, int32 x, int32 y)
Definition at line 357 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, LOG_FILTER_MAP_LOADING, m_loadedMMaps, m_loadedTiles, MANGOS_ASSERT, packInstanceId(), packTileID(), and sLog.
Referenced by ChangeTile(), and TerrainInfo::~TerrainInfo().
unloadMapInstance()
bool MMAP::MMapManager::unloadMapInstance (uint32 mapId, uint32 instanceId)
Definition at line 442 of file MoveMap.cpp.
References DEBUG_FILTER_LOG, LOG_FILTER_MAP_LOADING, m_loadedMMaps, and packInstanceId().
Referenced by Map::~Map().
Field Documentation
m_loadedMMaps
std::unordered_map<uint64, std::unique_ptr<MMapData> > MMAP::MMapManager::m_loadedMMaps private
Definition at line 120 of file MoveMap.h.
Referenced by getLoadedMapsCount(), GetNavMesh(), GetNavMeshQuery(), IsMMapTileLoaded(), loadMap(), loadMapData(), unloadMap(), and unloadMapInstance().
m_loadedModels
std::unordered_map<uint32, std::unique_ptr<MMapGOData> > MMAP::MMapManager::m_loadedModels private
Definition at line 123 of file MoveMap.h.
Referenced by GetGONavMesh(), GetModelNavMeshQuery(), and loadGameObject().
m_loadedTiles
uint32 MMAP::MMapManager::m_loadedTiles private
Definition at line 121 of file MoveMap.h.
Referenced by getLoadedTilesCount(), loadMap(), and unloadMap().
m_modelsMutex
std::mutex MMAP::MMapManager::m_modelsMutex private
Definition at line 124 of file MoveMap.h.
Referenced by GetModelNavMeshQuery().
The documentation for this class was generated from the following files:
MoveMap.h
MoveMap.cpp