CMaNGOS_WoTLK: Loot Class Reference
Loot Class Reference
#include <LootMgr.h>
Public Member Functions
Loot (Player *player, Creature *creature, LootType type)
Loot (Player *player, GameObject *gameObject, LootType type, bool lootSnapshot=false)
Loot (Player *player, Corpse *corpse, LootType type)
Loot (Player *player, Item *item, LootType type)
Loot (Player *player, uint32 id, LootType type)
Loot (Unit *unit, Item *item)
Loot (LootType type)
~Loot ()
void AddItem (LootStoreItem const &item)
void AddItem (uint32 itemid, uint32 count, uint32 randomSuffix, int32 randomPropertyId, Player *player=nullptr, bool notify=false)
bool AutoStore (Player *player, bool broadcast=false, uint32 bag=NULL_BAG, uint32 slot=NULL_SLOT)
bool CanLoot (Player const *player)
void ShowContentTo (Player *plr)
void Update ()
bool IsChanged () const
void Release (Player *player)
void GetLootItemsListFor (Player *player, LootItemList &lootList)
void SetGoldAmount (uint32 _gold)
void SendGold (Player *player)
void SendReleaseFor (Player *plr)
bool IsItemAlreadyIn (uint32 itemId) const
void PrintLootList (ChatHandler &chat, WorldSession *session) const
bool HasLoot () const
uint32 GetGoldAmount () const
LootType GetLootType () const
LootItem * GetLootItemInSlot (uint32 itemSlot)
GroupLootRoll * GetRollForSlot (uint32 itemSlot)
InventoryResult SendItem (Player *target, uint32 itemSlot)
InventoryResult SendItem (Player *target, LootItem *lootItem, bool sendError=true)
WorldObject const * GetLootTarget () const
ObjectGuid const & GetLootGuid () const
ObjectGuid const & GetMasterLootGuid () const
GuidSet const & GetOwnerSet () const
TimePoint const & GetCreateTime () const
Private Member Functions
Loot ()
void Clear ()
bool IsLootedFor (Player const *player) const
bool IsLootedForAll () const
void SendReleaseFor (ObjectGuid const &guid)
void SendReleaseForAll ()
void SendAllowedLooter ()
void NotifyMoneyRemoved ()
void NotifyItemRemoved (uint32 lootIndex)
void NotifyItemRemoved (Player *player, uint32 lootIndex) const
void NotifyItemChanged (LootItem *item)
void GroupCheck ()
void SetGroupLootRight (Player *player)
void GenerateMoneyLoot (uint32 minAmount, uint32 maxAmount)
bool FillLoot (uint32 loot_id, LootStore const &store, Player *lootOwner, bool personal, bool noEmptyError=false)
void ForceLootAnimationClientUpdate () const
void SetPlayerIsLooting (Player *player)
void SetPlayerIsNotLooting (Player *player)
void GetLootContentFor (Player *player, ByteBuffer &buffer)
uint32 GetLootStatusFor (Player const *player) const
bool IsLootOpenedBy (ObjectGuid const &playerGuid) const
Private Attributes
WorldObject * m_lootTarget
Item * m_itemTarget
ObjectGuid m_guidTarget
LootItemList m_lootItems
uint32 m_gold
uint32 m_maxSlot
LootType m_lootType
ClientLootType m_clientLootType
LootMethod m_lootMethod
ItemQualities m_threshold
ObjectGuid m_masterOwnerGuid
ObjectGuid m_currentLooterGuid
GuidSet m_ownerSet
uint32 m_maxEnchantSkill
bool m_haveItemOverThreshold
bool m_isChecked
bool m_isChest
bool m_isChanged
bool m_isFakeLoot
GroupLootRollMap m_roll
GuidSet m_playersLooting
GuidSet m_playersOpened
TimePoint m_createTime
Friends
struct LootItem
class GroupLootRoll
class LootMgr
Detailed Description
Definition at line 287 of file LootMgr.h.
Constructor & Destructor Documentation
Loot() [1/8]
Loot::Loot (Player * player, Creature * creature, LootType type)
Definition at line 1737 of file LootMgr.cpp.
References CLIENT_LOOT_CORPSE, CLIENT_LOOT_PICKPOCKETING, CONFIG_BOOL_CORPSE_EMPTY_LOOT_SHOW, CONFIG_FLOAT_RATE_DROP_MONEY, CREATURE_LOOT_STATUS_LOOTED, FillLoot(), ForceLootAnimationClientUpdate(), GenerateMoneyLoot(), Creature::GetCreatureInfo(), Object::GetGuidStr(), Unit::GetLevel(), Object::GetObjectGuid(), IsLootedForAll(), LOOT_CORPSE, LOOT_PICKPOCKETING, LOOT_SKINNING, CreatureInfo::LootId, LootTemplates_Creature, LootTemplates_Pickpocketing, LootTemplates_Skinning, m_clientLootType, m_gold, m_guidTarget, m_isFakeLoot, m_lootMethod, m_lootTarget, m_ownerSet, CreatureInfo::MaxLootGold, CreatureInfo::MinLootGold, NOT_GROUP_TYPE_LOOT, CreatureInfo::PickpocketLootId, Object::SetFlag(), SetGroupLootRight(), Creature::SetLootStatus(), CreatureInfo::SkinningLootId, sLog, sWorld, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, and urand().
Loot() [2/8]
Loot::Loot (Player * player, GameObject * gameObject, LootType type, bool lootSnapshot = false)
Definition at line 1836 of file LootMgr.cpp.
References CLIENT_LOOT_FISHING, CLIENT_LOOT_PICKPOCKETING, FillLoot(), GAMEOBJECT_TYPE_CHEST, GenerateMoneyLoot(), Object::GetEntry(), GameObject::GetGOInfo(), GameObjectInfo::GetLootId(), GameObject::GetLootState(), Object::GetObjectGuid(), GameObject::GetOwnerGuid(), WorldObject::GetZoneAndAreaId(), GO_ACTIVATED, GO_READY, GameObject::IsAtInteractDistance(), GameObject::IsSpawned(), LOOT_FISHING, LOOT_FISHING_FAIL, LOOT_FISHINGHOLE, LootTemplates_Fishing, LootTemplates_Gameobject, m_clientLootType, m_guidTarget, m_isChest, m_lootMethod, m_lootTarget, m_lootType, m_ownerSet, GameObjectInfo::MaxMoneyLoot, GameObjectInfo::MinMoneyLoot, NOT_GROUP_TYPE_LOOT, SetGroupLootRight(), GameObject::SetLootState(), sLog, and GameObjectInfo::type.
Loot() [3/8]
Loot::Loot (Player * player, Corpse * corpse, LootType type)
Definition at line 1927 of file LootMgr.cpp.
References CLIENT_LOOT_CORPSE, CONFIG_FLOAT_RATE_DROP_MONEY, CORPSE_BONES, FillLoot(), Player::GetBattleGround(), Unit::GetLevel(), Object::GetObjectGuid(), Corpse::GetOwnerGuid(), BattleGround::GetPlayerSkinRefLootId(), Corpse::GetType(), LOOT_INSIGNIA, Corpse::lootForBody, LootTemplates_Reference, m_clientLootType, m_gold, m_guidTarget, m_lootMethod, m_lootTarget, m_ownerSet, MANGOS_ASSERT, NOT_GROUP_TYPE_LOOT, sLog, sObjectAccessor, sWorld, and urand().
Loot() [4/8]
Loot::Loot (Player * player, Item * item, LootType type)
Definition at line 1976 of file LootMgr.cpp.
References CLIENT_LOOT_PICKPOCKETING, ItemPrototype::DisenchantID, FillLoot(), GenerateMoneyLoot(), Object::GetEntry(), Object::GetObjectGuid(), Item::GetProto(), ITEM_LOOT_CHANGED, ITEM_LOOT_TEMPORARY, LOOT_DISENCHANTING, LOOT_MILLING, LOOT_PROSPECTING, LootTemplates_Disenchant, LootTemplates_Item, LootTemplates_Milling, LootTemplates_Prospecting, m_clientLootType, m_guidTarget, m_itemTarget, m_lootMethod, m_ownerSet, ItemPrototype::MaxMoneyLoot, ItemPrototype::MinMoneyLoot, NOT_GROUP_TYPE_LOOT, Item::SetLootState(), and sLog.
Loot() [5/8]
Loot::Loot (Player * player, uint32 id, LootType type)
Definition at line 2032 of file LootMgr.cpp.
References CLIENT_LOOT_PICKPOCKETING, FillLoot(), Object::GetObjectGuid(), LOOT_DISENCHANTING, LOOT_MAIL, LOOT_SKINNING, LOOT_SPELL, LootTemplates_Disenchant, LootTemplates_Mail, LootTemplates_Skinning, LootTemplates_Spell, m_clientLootType, m_ownerSet, and sLog.
Loot() [6/8]
Loot::Loot (Unit * unit, Item * item)
Definition at line 2023 of file LootMgr.cpp.
References Object::GetObjectGuid(), m_guidTarget, and m_ownerSet.
Loot() [7/8]
Loot::Loot (LootType type)
Definition at line 2062 of file LootMgr.cpp.
~Loot()
Loot::~Loot ()
Definition at line 2278 of file LootMgr.cpp.
References m_lootItems, and SendReleaseForAll().
Loot() [8/8]
Loot::Loot () inline private
Definition at line 333 of file LootMgr.h.
Member Function Documentation
AddItem() [1/2]
void Loot::AddItem (LootStoreItem const & item)
Definition at line 961 of file LootMgr.cpp.
References LootItem::isUnderThreshold, LootItem, m_haveItemOverThreshold, m_lootItems, m_maxSlot, m_threshold, and MAX_NR_LOOT_ITEMS.
Referenced by GroupLootRoll::Finish(), Item::LoadLootFromDB(), LootTemplate::LootGroup::Process(), and LootTemplate::Process().
AddItem() [2/2]
void Loot::AddItem (uint32 itemid, uint32 count, uint32 randomSuffix, int32 randomPropertyId, Player * player = nullptr, bool notify = false)
Definition at line 975 of file LootMgr.cpp.
References LootItem::allowedGuid, Object::GetObjectGuid(), LootItem, m_lootItems, m_maxSlot, m_ownerSet, MAX_NR_LOOT_ITEMS, and NotifyItemChanged().
AutoStore()
bool Loot::AutoStore (Player * player, bool broadcast = false, uint32 bag = NULL_BAG, uint32 slot = NULL_SLOT)
Definition at line 2186 of file LootMgr.cpp.
References LootItem::allowedGuid, Player::CanStoreNewItem(), LootItem::count, EQUIP_ERR_OK, LootItem::freeForAll, Object::GetObjectGuid(), LootItem::IsAllowed(), LootItem::itemId, m_isChanged, m_lootItems, NULL_BAG, NULL_SLOT, LootItem::randomPropertyId, Player::SendEquipError(), Player::SendNewItem(), and Player::StoreNewItem().
Referenced by Spell::EffectCreateItem2(), Spell::EffectCreateRandomItem(), GroupLootRoll::Finish(), PlayerbotAI::PickPocket(), Release(), and Aura::TriggerSpell().
CanLoot()
bool Loot::CanLoot (Player const * player)
Definition at line 1122 of file LootMgr.cpp.
References FREE_FOR_ALL, GetLootStatusFor(), Object::GetObjectGuid(), LOOT_FISHINGHOLE, LOOT_STATUS_CONTAIN_FFA, LOOT_STATUS_CONTAIN_GOLD, LOOT_STATUS_CONTAIN_RELEASED_ITEMS, m_currentLooterGuid, m_haveItemOverThreshold, m_lootMethod, m_lootType, m_masterOwnerGuid, m_ownerSet, MASTER_LOOT, NOT_GROUP_TYPE_LOOT, and ROUND_ROBIN.
Referenced by Object::BuildValuesUpdate(), PlayerbotAI::DoLoot(), PlayerbotAI::findNearbyCorpse(), and ShowContentTo().
Clear()
void Loot::Clear () private
Definition at line 2285 of file LootMgr.cpp.
References ObjectGuid::Clear(), m_currentLooterGuid, m_gold, m_haveItemOverThreshold, m_isChecked, m_lootItems, m_masterOwnerGuid, m_maxEnchantSkill, m_maxSlot, m_ownerSet, m_playersLooting, and m_roll.
Referenced by Release().
FillLoot()
bool Loot::FillLoot (uint32 loot_id, LootStore const & store, Player * lootOwner, bool personal, bool noEmptyError = false) private
Definition at line 996 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), LootStore::GetLootFor(), GetLootTarget(), LootStore::GetName(), Object::GetObjectGuid(), GROUP_LOOT, LootStore::IsRatesAllowed(), LOOTITEM_TYPE_QUEST, m_currentLooterGuid, m_isChest, m_lootItems, m_lootMethod, m_masterOwnerGuid, m_ownerSet, m_threshold, MASTER_LOOT, MAX_NR_LOOT_ITEMS, NEED_BEFORE_GREED, LootTemplate::Process(), and sLog.
Referenced by Loot(), and Release().
ForceLootAnimationClientUpdate()
void Loot::ForceLootAnimationClientUpdate () const private
Definition at line 2237 of file LootMgr.cpp.
References Object::ForceValuesUpdateAtIndex(), Object::GetTypeId(), m_lootTarget, TYPEID_GAMEOBJECT, TYPEID_UNIT, and UNIT_DYNAMIC_FLAGS.
Referenced by Loot(), Release(), SendGold(), and SendItem().
GenerateMoneyLoot()
void Loot::GenerateMoneyLoot (uint32 minAmount, uint32 maxAmount) private
Definition at line 1234 of file LootMgr.cpp.
References CONFIG_FLOAT_RATE_DROP_MONEY, m_gold, sWorld, and urand().
Referenced by Loot().
GetCreateTime()
TimePoint const& Loot::GetCreateTime () const inline
Definition at line 330 of file LootMgr.h.
References m_createTime.
GetGoldAmount()
uint32 Loot::GetGoldAmount () const inline
Definition at line 320 of file LootMgr.h.
References m_gold.
Referenced by PlayerbotAI::PickPocket(), and Item::SaveToDB().
GetLootContentFor()
void Loot::GetLootContentFor (Player * player, ByteBuffer & buffer) private
Definition at line 2409 of file LootMgr.cpp.
References Object::GetGuidStr(), LootItem::GetSlotTypeForSharedLoot(), LootItem::itemId, LootItem::lootSlot, m_gold, m_lootItems, MAX_LOOT_SLOT_TYPE, ByteBuffer::put(), sLog, and ByteBuffer::wpos().
Referenced by ShowContentTo().
GetLootGuid()
ObjectGuid const& Loot::GetLootGuid () const inline
Definition at line 327 of file LootMgr.h.
References m_guidTarget.
Referenced by WorldSession::HandleAutostoreLootItemOpcode(), SendAllowedLooter(), GroupLootRoll::SendAllPassed(), GroupLootRoll::SendLootRollWon(), GroupLootRoll::SendRoll(), and GroupLootRoll::SendStartRoll().
GetLootItemInSlot()
LootItem * Loot::GetLootItemInSlot (uint32 itemSlot)
Definition at line 2255 of file LootMgr.cpp.
References m_lootItems.
Referenced by WorldSession::HandleAutostoreLootItemOpcode(), WorldSession::HandleLootMasterGiveOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), SendItem(), and GroupLootRoll::TryToStart().
GetLootItemsListFor()
void Loot::GetLootItemsListFor (Player * player, LootItemList & lootList)
Definition at line 2266 of file LootMgr.cpp.
References LootItem::IsAllowed(), and m_lootItems.
Referenced by Spell::EffectCreateItem2(), Spell::EffectCreateRandomItem(), GroupLootRoll::Finish(), MailDraft::prepareItems(), Mail::prepareTemplateItems(), and Item::SaveToDB().
GetLootStatusFor()
uint32 Loot::GetLootStatusFor (Player const * player) const private
Definition at line 1075 of file LootMgr.cpp.
References LOOT_STATUS_CONTAIN_FFA, LOOT_STATUS_CONTAIN_GOLD, LOOT_STATUS_CONTAIN_RELEASED_ITEMS, LOOT_STATUS_FAKE_LOOT, LOOT_STATUS_NOT_FULLY_LOOTED, m_gold, m_isFakeLoot, m_lootItems, m_playersOpened, and MAX_LOOT_SLOT_TYPE.
Referenced by CanLoot(), and IsLootedFor().
GetLootTarget()
WorldObject const* Loot::GetLootTarget () const inline
Definition at line 326 of file LootMgr.h.
References m_lootTarget.
Referenced by FillLoot(), LootItem::IsAllowed(), LootTemplate::PlayerOrGroupFulfilsCondition(), and GroupLootRoll::SendStartRoll().
GetLootType()
LootType Loot::GetLootType () const inline
Definition at line 321 of file LootMgr.h.
References m_lootType.
Referenced by Spell::EffectDisEnchant(), Spell::EffectPickPocket(), Spell::EffectSkinning(), Spell::EffectSkinPlayerCorpse(), PlayerbotAI::PickPocket(), and Player::RemovedInsignia().
GetMasterLootGuid()
ObjectGuid const& Loot::GetMasterLootGuid () const inline
Definition at line 328 of file LootMgr.h.
References m_masterOwnerGuid.
Referenced by WorldSession::HandleLootMasterGiveOpcode().
GetOwnerSet()
GuidSet const& Loot::GetOwnerSet () const inline
Definition at line 329 of file LootMgr.h.
References m_ownerSet.
Referenced by LootTemplate::PlayerOrGroupFulfilsCondition().
GetRollForSlot()
GroupLootRoll * Loot::GetRollForSlot (uint32 itemSlot)
Definition at line 948 of file LootMgr.cpp.
References m_roll.
Referenced by LootMgr::PlayerVote().
GroupCheck()
void Loot::GroupCheck () private
Definition at line 1574 of file LootMgr.cpp.
References Player::GetSession(), m_isChecked, m_lootItems, m_lootMethod, m_masterOwnerGuid, m_ownerSet, m_roll, MASTER_LOOT, WorldSession::SendPacket(), SMSG_LOOT_MASTER_LIST, and sObjectAccessor.
Referenced by ShowContentTo().
HasLoot()
bool Loot::HasLoot () const
IsChanged()
bool Loot::IsChanged () const inline
Definition at line 311 of file LootMgr.h.
References m_isChanged.
Referenced by GameObject::Update().
IsItemAlreadyIn()
bool Loot::IsItemAlreadyIn (uint32 itemId) const
Definition at line 2362 of file LootMgr.cpp.
References m_lootItems.
Referenced by LootTemplate::LootGroup::Roll().
IsLootedFor()
bool Loot::IsLootedFor (Player const * player) const private
Definition at line 1103 of file LootMgr.cpp.
References GetLootStatusFor().
Referenced by IsLootedForAll(), Release(), SendGold(), and SendItem().
IsLootedForAll()
bool Loot::IsLootedForAll () const private
Definition at line 1108 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), IsLootedFor(), and m_ownerSet.
Referenced by Loot(), Release(), and SendItem().
IsLootOpenedBy()
bool Loot::IsLootOpenedBy (ObjectGuid const & playerGuid) const inline private
Definition at line 356 of file LootMgr.h.
References m_playersOpened.
NotifyItemChanged()
void Loot::NotifyItemChanged (LootItem * item) private
Definition at line 1190 of file LootMgr.cpp.
References LootItem::count, LootItem::displayID, ObjectAccessor::FindPlayer(), Player::GetSession(), LootItem::itemId, LootItem::lootSlot, m_guidTarget, m_playersLooting, LootItem::randomPropertyId, LootItem::randomSuffix, WorldSession::SendPacket(), and SMSG_LOOT_UPDATE.
Referenced by AddItem(), and GroupLootRoll::Finish().
NotifyItemRemoved() [1/2]
void Loot::NotifyItemRemoved (Player * player, uint32 lootIndex) const private
Definition at line 1182 of file LootMgr.cpp.
References Player::GetSession(), WorldSession::SendPacket(), and SMSG_LOOT_REMOVED.
NotifyItemRemoved() [2/2]
void Loot::NotifyItemRemoved (uint32 lootIndex) private
Definition at line 1165 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), Player::GetSession(), and m_playersLooting.
Referenced by GroupLootRoll::Finish(), and SendItem().
NotifyMoneyRemoved()
void Loot::NotifyMoneyRemoved () private
Definition at line 1215 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), Player::GetSession(), m_playersLooting, WorldSession::SendPacket(), and SMSG_LOOT_CLEAR_MONEY.
Referenced by SendGold().
PrintLootList()
void Loot::PrintLootList (ChatHandler & chat, WorldSession * session) const
Definition at line 2373 of file LootMgr.cpp.
References WorldSession::GetSessionDbLocaleIndex(), LANG_ITEM_LIST_CHAT, SQLStorage::LookupEntry(), m_gold, m_lootItems, ItemPrototype::Name1, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), sItemStorage, and sObjectMgr.
Referenced by ChatHandler::HandleNpcShowLootCommand().
Release()
void Loot::Release (Player * player)
Definition at line 1295 of file LootMgr.cpp.
References GameObject::AddUse(), AutoStore(), GameObjectInfo::chest, Clear(), CONFIG_FLOAT_RATE_MINING_AMOUNT, CONFIG_FLOAT_RATE_MINING_NEXT, CORPSE_DYNFLAG_LOOTABLE, CORPSE_FIELD_DYNAMIC_FLAGS, CREATURE_LOOT_STATUS_LOOTED, CREATURE_LOOT_STATUS_PICKPOCKETED, CREATURE_LOOT_STATUS_SKIN_AVAILABLE, CREATURE_LOOT_STATUS_SKINNED, Player::DestroyItem(), Player::DestroyItemCount(), FillLoot(), GameObjectInfo::fishinghole, ForceLootAnimationClientUpdate(), FREE_FOR_ALL, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, Item::GetBagSlot(), Item::GetCount(), GameObject::GetGOInfo(), GameObject::GetGoType(), Player::GetGroup(), ObjectGuid::GetHigh(), GameObjectInfo::GetLootId(), Group::GetMemberSlots(), Object::GetObjectGuid(), Player::GetSkillValue(), Item::GetSlot(), GameObject::GetUseCount(), GO_JUST_DEACTIVATED, GO_READY, HIGHGUID_CORPSE, HIGHGUID_GAMEOBJECT, HIGHGUID_ITEM, HIGHGUID_UNIT, HIGHGUID_VEHICLE, INTERACTION_DISTANCE, IsLootedFor(), IsLootedForAll(), WorldObject::IsWithinDistInMap(), ITEM_LOOT_REMOVED, LOOT_CORPSE, LOOT_DISENCHANTING, LOOT_MILLING, LOOT_PICKPOCKETING, LOOT_PROSPECTING, LOOT_SKINNING, LootTemplates_Gameobject, m_currentLooterGuid, m_guidTarget, m_isFakeLoot, m_itemTarget, m_lootItems, m_lootMethod, m_lootTarget, m_lootType, m_ownerSet, Object::RemoveFlag(), roll_chance_f(), SendReleaseForAll(), Item::SetLootState(), GameObject::SetLootState(), Creature::SetLootStatus(), SetPlayerIsNotLooting(), LockEntry::Skill, SKILL_MINING, sLockStore, sWorld, urand(), and GameObject::UseDoorOrButton().
Referenced by PlayerbotAI::PickPocket(), and SendGold().
SendAllowedLooter()
void Loot::SendAllowedLooter () private
Definition at line 2070 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), FREE_FOR_ALL, GetLootGuid(), m_currentLooterGuid, m_lootMethod, m_masterOwnerGuid, m_ownerSet, MASTER_LOOT, NOT_GROUP_TYPE_LOOT, SMSG_LOOT_LIST, and ObjectGuid::WriteAsPacked().
Referenced by SendItem(), and SetGroupLootRight().
SendGold()
void Loot::SendGold (Player * player)
Definition at line 2309 of file LootMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY, ForceLootAnimationClientUpdate(), Player::GetAchievementMgr(), Player::GetItemByGuid(), Player::GetSession(), ObjectGuid::IsItem(), IsLootedFor(), ITEM_LOOT_CHANGED, m_gold, m_guidTarget, m_lootMethod, m_ownerSet, Player::ModifyMoney(), NOT_GROUP_TYPE_LOOT, NotifyMoneyRemoved(), Release(), WorldSession::SendPacket(), SMSG_LOOT_MONEY_NOTIFY, sObjectMgr, and AchievementMgr::UpdateAchievementCriteria().
Referenced by WorldSession::HandleLootMoneyOpcode(), and PlayerbotAI::PickPocket().
SendItem() [1/2]
InventoryResult Loot::SendItem (Player * target, LootItem * lootItem, bool sendError = true)
Definition at line 2096 of file LootMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, LootItem::allowedGuid, Player::CanStoreNewItem(), GameObjectInfo::chest, LootItem::count, EQUIP_ERR_CANT_DO_RIGHT_NOW, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, EQUIP_ERR_OUT_OF_RANGE, ForceLootAnimationClientUpdate(), LootItem::freeForAll, Player::GetAchievementMgr(), GameObject::GetGOInfo(), Object::GetObjectGuid(), Player::GetSession(), GO_JUST_DEACTIVATED, LootItem::isBlocked, IsLootedFor(), IsLootedForAll(), LootItem::isReleased, LootItem::itemId, LootItem::lootSlot, m_currentLooterGuid, m_isChanged, m_isChest, m_lootTarget, m_lootType, NotifyItemRemoved(), NULL_BAG, NULL_SLOT, LootItem::randomPropertyId, SendAllowedLooter(), Player::SendEquipError(), Player::SendNewItem(), SendReleaseFor(), SendReleaseForAll(), GameObject::SetLootState(), sLog, Player::StoreNewItem(), and AchievementMgr::UpdateAchievementCriteria().
SendItem() [2/2]
InventoryResult Loot::SendItem (Player * target, uint32 itemSlot)
Definition at line 2090 of file LootMgr.cpp.
References GetLootItemInSlot().
Referenced by GroupLootRoll::Finish(), WorldSession::HandleAutostoreLootItemOpcode(), and WorldSession::HandleLootMasterGiveOpcode().
SendReleaseFor() [1/2]
void Loot::SendReleaseFor (ObjectGuid const & guid) private
Definition at line 1247 of file LootMgr.cpp.
References Player::GetSession(), SendReleaseFor(), and sObjectAccessor.
SendReleaseFor() [2/2]
void Loot::SendReleaseFor (Player * plr)
Definition at line 1255 of file LootMgr.cpp.
References Player::GetSession(), m_guidTarget, WorldSession::SendPacket(), SetPlayerIsNotLooting(), and SMSG_LOOT_RELEASE_RESPONSE.
Referenced by WorldSession::HandleAutostoreLootItemOpcode(), SendItem(), SendReleaseFor(), SendReleaseForAll(), and ShowContentTo().
SendReleaseForAll()
void Loot::SendReleaseForAll () private
Definition at line 1264 of file LootMgr.cpp.
References m_playersLooting, and SendReleaseFor().
Referenced by Release(), SendItem(), and ~Loot().
SetGoldAmount()
void Loot::SetGoldAmount (uint32 _gold)
Definition at line 2303 of file LootMgr.cpp.
References LOOT_SKINNING, m_gold, and m_lootType.
Referenced by Item::LoadLootFromDB().
SetGroupLootRight()
void Loot::SetGroupLootRight (Player * player) private
Definition at line 1638 of file LootMgr.cpp.
References ObjectAccessor::FindPlayer(), FREE_FOR_ALL, Group::GetCurrentLooterGuid(), Player::GetGroup(), Group::GetLootMethod(), Group::GetLootThreshold(), Group::GetMasterLooterGuid(), Group::GetMemberSlots(), Object::GetObjectGuid(), Player::GetSkillValue(), GROUP_LOOT, IsEligibleForLoot(), m_currentLooterGuid, m_isChecked, m_isChest, m_lootMethod, m_lootTarget, m_masterOwnerGuid, m_maxEnchantSkill, m_ownerSet, m_threshold, MASTER_LOOT, NOT_GROUP_TYPE_LOOT, SendAllowedLooter(), Group::SetNextLooterGuid(), and SKILL_ENCHANTING.
Referenced by Loot(), and ShowContentTo().
SetPlayerIsLooting()
void Loot::SetPlayerIsLooting (Player * player) private
Definition at line 1271 of file LootMgr.cpp.
References Object::GetObjectGuid(), ObjectGuid::IsGameObject(), LOOT_CORPSE, m_guidTarget, m_isChest, m_lootTarget, m_lootType, m_playersLooting, Object::SetFlag(), Player::SetLootGuid(), UNIT_FIELD_FLAGS, and UNIT_FLAG_LOOTING.
Referenced by ShowContentTo().
SetPlayerIsNotLooting()
void Loot::SetPlayerIsNotLooting (Player * player) private
Definition at line 1283 of file LootMgr.cpp.
References Object::GetObjectGuid(), ObjectGuid::IsGameObject(), LOOT_CORPSE, m_guidTarget, m_isChest, m_lootTarget, m_lootType, m_playersLooting, Object::RemoveFlag(), Player::SetLootGuid(), UNIT_FIELD_FLAGS, and UNIT_FLAG_LOOTING.
Referenced by Release(), and SendReleaseFor().
ShowContentTo()
void Loot::ShowContentTo (Player * plr)
Definition at line 1532 of file LootMgr.cpp.
References CanLoot(), Object::GetGuidStr(), GetLootContentFor(), Object::GetObjectGuid(), GroupCheck(), WorldObject::InspectingLoot(), LOOT_ERROR_LOCKED, m_clientLootType, m_guidTarget, m_isChecked, m_isChest, m_lootItems, m_lootMethod, m_lootTarget, m_ownerSet, m_playersOpened, NOT_GROUP_TYPE_LOOT, Player::SendDirectMessage(), Player::SendLootError(), SendReleaseFor(), SetGroupLootRight(), SetPlayerIsLooting(), sLog, and SMSG_LOOT_RESPONSE.
Referenced by Spell::EffectDisEnchant(), Spell::EffectMilling(), Spell::EffectPickPocket(), Spell::EffectProspecting(), Spell::EffectSkinning(), Spell::EffectSkinPlayerCorpse(), WorldSession::HandleOpenItemOpcode(), Player::RemovedInsignia(), Spell::SendLoot(), and GameObject::Use().
Update()
void Loot::Update ()
Definition at line 2222 of file LootMgr.cpp.
References m_isChanged, and m_roll.
Referenced by Creature::Update(), and GameObject::Update().
Friends And Related Function Documentation
GroupLootRoll
friend class GroupLootRoll friend
Definition at line 291 of file LootMgr.h.
LootItem
friend struct LootItem friend
Definition at line 290 of file LootMgr.h.
Referenced by AddItem().
LootMgr
friend class LootMgr friend
Definition at line 292 of file LootMgr.h.
Field Documentation
m_clientLootType
ClientLootType Loot::m_clientLootType private
Definition at line 367 of file LootMgr.h.
Referenced by Loot(), and ShowContentTo().
m_createTime
TimePoint Loot::m_createTime private
Definition at line 382 of file LootMgr.h.
Referenced by GetCreateTime().
m_currentLooterGuid
ObjectGuid Loot::m_currentLooterGuid private
Definition at line 371 of file LootMgr.h.
Referenced by CanLoot(), Clear(), FillLoot(), LootItem::GetSlotTypeForSharedLoot(), Release(), SendAllowedLooter(), SendItem(), and SetGroupLootRight().
m_gold
uint32 Loot::m_gold private
Definition at line 364 of file LootMgr.h.
Referenced by Clear(), GenerateMoneyLoot(), GetGoldAmount(), GetLootContentFor(), GetLootStatusFor(), Loot(), PrintLootList(), SendGold(), and SetGoldAmount().
m_guidTarget
ObjectGuid Loot::m_guidTarget private
Definition at line 361 of file LootMgr.h.
Referenced by GetLootGuid(), Loot(), NotifyItemChanged(), Release(), SendGold(), SendReleaseFor(), SetPlayerIsLooting(), SetPlayerIsNotLooting(), and ShowContentTo().
m_haveItemOverThreshold
bool Loot::m_haveItemOverThreshold private
Definition at line 374 of file LootMgr.h.
Referenced by AddItem(), CanLoot(), and Clear().
m_isChanged
bool Loot::m_isChanged private
Definition at line 377 of file LootMgr.h.
Referenced by AutoStore(), IsChanged(), SendItem(), and Update().
m_isChecked
bool Loot::m_isChecked private
Definition at line 375 of file LootMgr.h.
Referenced by Clear(), GroupCheck(), SetGroupLootRight(), and ShowContentTo().
m_isChest
bool Loot::m_isChest private
Definition at line 376 of file LootMgr.h.
Referenced by FillLoot(), LootItem::GetSlotTypeForSharedLoot(), LootItem::IsAllowed(), Loot(), SendItem(), SetGroupLootRight(), SetPlayerIsLooting(), SetPlayerIsNotLooting(), and ShowContentTo().
m_isFakeLoot
bool Loot::m_isFakeLoot private
Definition at line 378 of file LootMgr.h.
Referenced by GetLootStatusFor(), Loot(), and Release().
m_itemTarget
Item* Loot::m_itemTarget private
Definition at line 360 of file LootMgr.h.
Referenced by Loot(), and Release().
m_lootItems
LootItemList Loot::m_lootItems private
Definition at line 363 of file LootMgr.h.
Referenced by AddItem(), AutoStore(), Clear(), FillLoot(), GetLootContentFor(), GetLootItemInSlot(), GetLootItemsListFor(), GetLootStatusFor(), GroupCheck(), IsItemAlreadyIn(), PrintLootList(), Release(), ShowContentTo(), GroupLootRoll::TryToStart(), and ~Loot().
m_lootMethod
LootMethod Loot::m_lootMethod private
Definition at line 368 of file LootMgr.h.
Referenced by CanLoot(), FillLoot(), LootItem::GetSlotTypeForSharedLoot(), GroupCheck(), Loot(), Release(), SendAllowedLooter(), SendGold(), GroupLootRoll::SendStartRoll(), SetGroupLootRight(), and ShowContentTo().
m_lootTarget
WorldObject* Loot::m_lootTarget private
Definition at line 359 of file LootMgr.h.
Referenced by ForceLootAnimationClientUpdate(), GetLootTarget(), Loot(), Release(), SendItem(), SetGroupLootRight(), SetPlayerIsLooting(), SetPlayerIsNotLooting(), and ShowContentTo().
m_lootType
LootType Loot::m_lootType private
Definition at line 366 of file LootMgr.h.
Referenced by CanLoot(), GetLootType(), LootItem::GetSlotTypeForSharedLoot(), Loot(), Release(), SendItem(), SetGoldAmount(), SetPlayerIsLooting(), and SetPlayerIsNotLooting().
m_masterOwnerGuid
ObjectGuid Loot::m_masterOwnerGuid private
Definition at line 370 of file LootMgr.h.
Referenced by CanLoot(), Clear(), FillLoot(), GetMasterLootGuid(), LootItem::GetSlotTypeForSharedLoot(), GroupCheck(), SendAllowedLooter(), and SetGroupLootRight().
m_maxEnchantSkill
uint32 Loot::m_maxEnchantSkill private
Definition at line 373 of file LootMgr.h.
Referenced by Clear(), SetGroupLootRight(), and GroupLootRoll::TryToStart().
m_maxSlot
uint32 Loot::m_maxSlot private
Definition at line 365 of file LootMgr.h.
Referenced by AddItem(), and Clear().
m_ownerSet
GuidSet Loot::m_ownerSet private
Definition at line 372 of file LootMgr.h.
Referenced by AddItem(), CanLoot(), Clear(), FillLoot(), GetOwnerSet(), GroupCheck(), IsLootedForAll(), Loot(), Release(), SendAllowedLooter(), SendGold(), SetGroupLootRight(), ShowContentTo(), and GroupLootRoll::TryToStart().
m_playersLooting
GuidSet Loot::m_playersLooting private
Definition at line 380 of file LootMgr.h.
Referenced by Clear(), NotifyItemChanged(), NotifyItemRemoved(), NotifyMoneyRemoved(), SendReleaseForAll(), SetPlayerIsLooting(), and SetPlayerIsNotLooting().
m_playersOpened
GuidSet Loot::m_playersOpened private
Definition at line 381 of file LootMgr.h.
Referenced by GetLootStatusFor(), IsLootOpenedBy(), and ShowContentTo().
m_roll
GroupLootRollMap Loot::m_roll private
Definition at line 379 of file LootMgr.h.
Referenced by Clear(), GetRollForSlot(), GroupCheck(), and Update().
m_threshold
ItemQualities Loot::m_threshold private
Definition at line 369 of file LootMgr.h.
Referenced by AddItem(), FillLoot(), and SetGroupLootRight().
The documentation for this class was generated from the following files:
LootMgr.h
LootMgr.cpp