CMaNGOS_WoTLK: TypeMapContainer< OBJECT_TYPES > Class Template Reference
TypeMapContainer< OBJECT_TYPES > Class Template Reference
#include <TypeContainer.h>
Public Member Functions
template<class SPECIFIC_TYPE >
size_t Count () const
template<class SPECIFIC_TYPE >
bool insert (SPECIFIC_TYPE *obj)
inserts a specific object into the container
template<class SPECIFIC_TYPE >
bool remove (SPECIFIC_TYPE *obj)
Removes the object from the container, and returns the removed object.
ContainerMapList< OBJECT_TYPES > & GetElements ()
const ContainerMapList< OBJECT_TYPES > & GetElements () const
Private Attributes
ContainerMapList< OBJECT_TYPES > i_elements
Detailed Description
template<class OBJECT_TYPES>
class TypeMapContainer< OBJECT_TYPES >
Definition at line 216 of file TypeContainer.h.
Member Function Documentation
Count()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > size_t TypeMapContainer< OBJECT_TYPES >::Count () const inline
Definition at line 221 of file TypeContainer.h.
References MaNGOS::Count(), and TypeMapContainer< OBJECT_TYPES >::i_elements.
GetElements() [1/2]
template<class OBJECT_TYPES > ContainerMapList<OBJECT_TYPES>& TypeMapContainer< OBJECT_TYPES >::GetElements () inline
Definition at line 239 of file TypeContainer.h.
References TypeMapContainer< OBJECT_TYPES >::i_elements.
Referenced by VisitorHelper().
GetElements() [2/2]
template<class OBJECT_TYPES > const ContainerMapList<OBJECT_TYPES>& TypeMapContainer< OBJECT_TYPES >::GetElements () const inline
Definition at line 240 of file TypeContainer.h.
References TypeMapContainer< OBJECT_TYPES >::i_elements.
insert()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > bool TypeMapContainer< OBJECT_TYPES >::insert (SPECIFIC_TYPE * obj) inline
inserts a specific object into the container
Definition at line 225 of file TypeContainer.h.
References TypeMapContainer< OBJECT_TYPES >::i_elements, and MaNGOS::Insert().
remove()
template<class OBJECT_TYPES > template<class SPECIFIC_TYPE > bool TypeMapContainer< OBJECT_TYPES >::remove (SPECIFIC_TYPE * obj) inline
Removes the object from the container, and returns the removed object.
Definition at line 233 of file TypeContainer.h.
References TypeMapContainer< OBJECT_TYPES >::i_elements, and MaNGOS::Remove().
Field Documentation
i_elements
template<class OBJECT_TYPES > ContainerMapList<OBJECT_TYPES> TypeMapContainer< OBJECT_TYPES >::i_elements private
Definition at line 244 of file TypeContainer.h.
Referenced by TypeMapContainer< OBJECT_TYPES >::Count(), TypeMapContainer< OBJECT_TYPES >::GetElements(), TypeMapContainer< OBJECT_TYPES >::insert(), and TypeMapContainer< OBJECT_TYPES >::remove().
The documentation for this class was generated from the following file:
TypeContainer.h