CMaNGOS_WoTLK: TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > Class Template Reference
TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE > Class Template Reference
#include <TypeContainer.h>
Public Member Functions
template<class SPECIFIC_TYPE >
bool insert (KEY_TYPE handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
bool erase (KEY_TYPE handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * find (KEY_TYPE hdl, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
std::unordered_map< KEY_TYPE, SPECIFIC_TYPE * >::iterator begin ()
template<class SPECIFIC_TYPE >
std::unordered_map< KEY_TYPE, SPECIFIC_TYPE * >::iterator end ()
Static Private Member Functions
template<class SPECIFIC_TYPE >
static bool insert (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > &elements, KEY_TYPE handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
static bool insert (ContainerUnorderedMap< TypeNull, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
static bool insert (ContainerUnorderedMap< T, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class H , class T >
static bool insert (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &elements, KEY_TYPE handle, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
static SPECIFIC_TYPE * find (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > &elements, KEY_TYPE hdl, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
static SPECIFIC_TYPE * find (ContainerUnorderedMap< TypeNull, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
static SPECIFIC_TYPE * find (ContainerUnorderedMap< T, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class H , class T >
static SPECIFIC_TYPE * find (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &elements, KEY_TYPE hdl, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
static bool erase (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > &elements, KEY_TYPE handle, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
static bool erase (ContainerUnorderedMap< TypeNull, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
static bool erase (ContainerUnorderedMap< T, KEY_TYPE > &, KEY_TYPE, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class H , class T >
static bool erase (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > &elements, KEY_TYPE handle, SPECIFIC_TYPE *)
Private Attributes
ContainerUnorderedMap< OBJECT_TYPES, KEY_TYPE > i_elements
Detailed Description
template<class OBJECT_TYPES, class KEY_TYPE = OBJECT_HANDLE>
class TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >
Definition at line 53 of file TypeContainer.h.
Member Function Documentation
begin()
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > std::unordered_map<KEY_TYPE, SPECIFIC_TYPE*>::iterator TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::begin () inline
Definition at line 76 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements.
end()
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > std::unordered_map<KEY_TYPE, SPECIFIC_TYPE*>::iterator TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::end () inline
Definition at line 82 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements.
erase() [1/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > & elements, KEY_TYPE handle, SPECIFIC_TYPE *) inline static private
Definition at line 156 of file TypeContainer.h.
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
erase() [2/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class T > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase (ContainerUnorderedMap< T, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 170 of file TypeContainer.h.
erase() [3/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class H , class T > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & elements, KEY_TYPE handle, SPECIFIC_TYPE *) inline static private
Definition at line 176 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase().
erase() [4/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase (ContainerUnorderedMap< TypeNull, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 164 of file TypeContainer.h.
erase() [5/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase (KEY_TYPE handle, SPECIFIC_TYPE *) inline
Definition at line 64 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements.
Referenced by TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), and Pet::RemoveFromWorld().
find() [1/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > & elements, KEY_TYPE hdl, SPECIFIC_TYPE *) inline static private
Definition at line 127 of file TypeContainer.h.
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
find() [2/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class T > static SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find (ContainerUnorderedMap< T, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 142 of file TypeContainer.h.
find() [3/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class H , class T > static SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & elements, KEY_TYPE hdl, SPECIFIC_TYPE *) inline static private
Definition at line 148 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find().
find() [4/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find (ContainerUnorderedMap< TypeNull, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 136 of file TypeContainer.h.
find() [5/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > SPECIFIC_TYPE* TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find (KEY_TYPE hdl, SPECIFIC_TYPE *) inline
Definition at line 70 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements.
Referenced by TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), Map::GetCreature(), Map::GetDynamicObject(), Map::GetGameObject(), and Map::GetPet().
insert() [1/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert (ContainerUnorderedMap< SPECIFIC_TYPE, KEY_TYPE > & elements, KEY_TYPE handle, SPECIFIC_TYPE * obj) inline static private
Definition at line 94 of file TypeContainer.h.
References ContainerUnorderedMap< OBJECT, KEY_TYPE >::_element.
insert() [2/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class T > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert (ContainerUnorderedMap< T, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 113 of file TypeContainer.h.
insert() [3/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE , class H , class T > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert (ContainerUnorderedMap< TypeList< H, T >, KEY_TYPE > & elements, KEY_TYPE handle, SPECIFIC_TYPE * obj) inline static private
Definition at line 119 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert().
insert() [4/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > static bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert (ContainerUnorderedMap< TypeNull, KEY_TYPE > & , KEY_TYPE , SPECIFIC_TYPE *) inline static private
Definition at line 107 of file TypeContainer.h.
insert() [5/5]
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> template<class SPECIFIC_TYPE > bool TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert (KEY_TYPE handle, SPECIFIC_TYPE * obj) inline
Definition at line 58 of file TypeContainer.h.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements.
Referenced by Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), Pet::AddToWorld(), and TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert().
Field Documentation
i_elements
template<class OBJECT_TYPES , class KEY_TYPE = OBJECT_HANDLE> ContainerUnorderedMap<OBJECT_TYPES, KEY_TYPE> TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::i_elements private
Definition at line 89 of file TypeContainer.h.
Referenced by TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::begin(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::end(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), and TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert().
The documentation for this class was generated from the following file:
TypeContainer.h