CMaNGOS_WoTLK: FormationMovementGenerator Class Reference
FormationMovementGenerator Class Reference
#include <TargetedMovementGenerator.h>
Public Member Functions
FormationMovementGenerator (FormationSlotDataSPtr &sData, bool main)
~FormationMovementGenerator ()
MovementGeneratorType GetMovementGeneratorType () const override
bool Update (Unit &, const uint32 &) override
void Interrupt (Unit &owner) override
bool GetResetPosition (Unit &, float &x, float &y, float &z, float &o) const
Public Member Functions inherited from FollowMovementGenerator
FollowMovementGenerator (Unit &target, float offset, float angle, bool main, bool possess, bool alwaysBoost=false)
~FollowMovementGenerator ()
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Reset (Unit &owner) override
virtual bool EnableWalking () const
bool _lostTarget (Unit &owner) const
void _reachTarget (Unit &owner)
void HandleMovementFailure (Unit &owner) override
virtual bool IsRemovedOnExpire () const override
void MarkMovegen ()
Public Member Functions inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
bool Update (Unit &, const uint32 &)
virtual bool IsReachable () const override
Unit * GetCurrentTarget () const override
float GetOffset () const
float GetAngle () const
virtual void UnitSpeedChanged () override
virtual bool RemoveOnInvalid () const
Public Member Functions inherited from MovementGeneratorMedium< T, D >
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Initialize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Finalize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Interrupt (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Reset (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool Update (U &u, const uint32 &time_diff)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
bool IsActive (Unit &u)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit &target)
void stopFollowing ()
void SetNewTarget (Unit &target)
Protected Member Functions
void HandleTargetedMovement (Unit &owner, const uint32 &time_diff) override
void HandleFinalizedMovement (Unit &owner) override
Protected Member Functions inherited from FollowMovementGenerator
float GetDynamicTargetDistance (Unit &owner, bool forRangeCheck) const override
bool _hasUnitStateNotMove (Unit &owner) override
void _clearUnitStateMove (Unit &owner) override
void _addUnitStateMove (Unit &owner) override
virtual float GetSpeed (Unit &owner) const
virtual bool IsBoostAllowed (Unit &owner) const
virtual bool IsUnstuckAllowed (Unit &owner) const
virtual bool Move (Unit &owner, float x, float y, float z)
virtual bool _getOrientation (Unit &owner, float &o) const
virtual bool _getLocation (Unit &owner, float &x, float &y, float &z, bool movingNow) const
virtual void _setOrientation (Unit &owner)
virtual uint32 _getPollRateMultiplier (Unit &owner, bool targetMovingNow, bool targetMovedBefore=true) const
virtual uint32 _getPollRate (Unit &owner, bool movingNow, bool movingBefore=true) const
Protected Member Functions inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
TargetedMovementGeneratorMedium (Unit &target, float offset, float angle)
~TargetedMovementGeneratorMedium ()
virtual bool RequiresNewPosition (Unit &owner, Position pos) const
virtual bool ShouldFaceTarget () const
Private Member Functions
virtual void _setLocation (Unit &owner, bool catchup) override
float BuildPath (Unit &owner, PointsArray &path)
bool HandleMasterDistanceCheck (Unit &owner, const uint32 &time_diff)
Private Attributes
FormationSlotDataSPtr m_slot
float m_lastAngle
bool m_headingToMaster
float m_tpDistance
float m_moveToMasterDistance
Position m_resetPoint
Additional Inherited Members
Static Protected Member Functions inherited from FollowMovementGenerator
static uint32 _getPollRateBase ()
static uint32 _getPollRateMax ()
Protected Attributes inherited from FollowMovementGenerator
bool m_main
bool m_possess
bool m_boost
bool m_targetMoving
bool m_targetFaced
Protected Attributes inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
ShortTimeTracker i_recheckDistance
float i_offset
float i_angle
G3D::Vector3 i_lastTargetPos
bool i_speedChanged
bool i_targetReached
bool i_faceTarget
PathFinder * i_path
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
Definition at line 247 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
FormationMovementGenerator()
FormationMovementGenerator::FormationMovementGenerator (FormationSlotDataSPtr & sData, bool main)
Definition at line 1144 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_path, m_moveToMasterDistance, and m_tpDistance.
~FormationMovementGenerator()
FormationMovementGenerator::~FormationMovementGenerator ()
Definition at line 1155 of file TargetedMovementGenerator.cpp.
Member Function Documentation
_setLocation()
void FormationMovementGenerator::_setLocation (Unit & owner, bool catchup) override private virtual
Reimplemented from FollowMovementGenerator.
Definition at line 1446 of file TargetedMovementGenerator.cpp.
References FollowMovementGenerator::_addUnitStateMove(), BuildPath(), FollowMovementGenerator::EnableWalking(), FORMATION_FOLLOWERS_CHECK_OVERRIDE, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_recheckDistance, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_targetReached, Movement::MoveSplineInit::Launch(), FollowMovementGenerator::m_targetFaced, Movement::MoveSplineInit::MovebyPath(), ShortTimeTracker::Reset(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetVelocity(), and Movement::MoveSplineInit::SetWalk().
Referenced by HandleTargetedMovement().
BuildPath()
float FormationMovementGenerator::BuildPath (Unit & owner, PointsArray & path) private
Definition at line 1197 of file TargetedMovementGenerator.cpp.
References PathFinder::calculate(), Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::Finalized(), PathFinder::getPath(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetSpeed(), Unit::HasHoverAura(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_path, TargetedMovementGeneratorBase::i_target, Unit::IsFlying(), Unit::IsInWater(), m_lastAngle, M_PI_F, m_slot, MOVE_WALK, WorldObject::MovePositionToFirstCollision(), Unit::movespline, SPAWN_GROUP_FORMATION_TYPE_RANDOM, Unit::UpdateAllowedPositionZ(), Position::x, Position::y, and Position::z.
Referenced by _setLocation().
GetMovementGeneratorType()
MovementGeneratorType FormationMovementGenerator::GetMovementGeneratorType () const inline override virtual
Reimplemented from FollowMovementGenerator.
Definition at line 253 of file TargetedMovementGenerator.h.
References FORMATION_MOTION_TYPE.
GetResetPosition()
bool FormationMovementGenerator::GetResetPosition (Unit & , float & x, float & y, float & z, float & o) const virtual
Reimplemented from FollowMovementGenerator.
Definition at line 1184 of file TargetedMovementGenerator.cpp.
References Position::IsEmpty(), m_resetPoint, Position::o, Position::x, Position::y, and Position::z.
HandleFinalizedMovement()
void FormationMovementGenerator::HandleFinalizedMovement (Unit & owner) override protected virtual
Reimplemented from FollowMovementGenerator.
Definition at line 1434 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorBase::i_target, and TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_targetReached.
HandleMasterDistanceCheck()
bool FormationMovementGenerator::HandleMasterDistanceCheck (Unit & owner, const uint32 & time_diff) private
Definition at line 1338 of file TargetedMovementGenerator.cpp.
References FollowMovementGenerator::_addUnitStateMove(), WorldObject::GetDistance(), WorldObject::GetPosition(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_recheckDistance, Movement::MoveSplineInit::Launch(), m_headingToMaster, m_moveToMasterDistance, m_slot, m_tpDistance, Movement::MoveSplineInit::MoveTo(), Unit::NearTeleportTo(), Position::o, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetWalk(), ShortTimeTracker::Update(), Position::x, Position::y, and Position::z.
Referenced by HandleTargetedMovement().
HandleTargetedMovement()
void FormationMovementGenerator::HandleTargetedMovement (Unit & owner, const uint32 & time_diff) override protected virtual
Reimplemented from FollowMovementGenerator.
Definition at line 1383 of file TargetedMovementGenerator.cpp.
References _setLocation(), Movement::MoveSpline::Finalized(), HandleMasterDistanceCheck(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_recheckDistance, TargetedMovementGeneratorBase::i_target, m_slot, FollowMovementGenerator::m_targetFaced, FollowMovementGenerator::m_targetMoving, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, movementFlagsMask, Unit::movespline, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), and ShortTimeTracker::Update().
Interrupt()
void FormationMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from FollowMovementGenerator.
Definition at line 1173 of file TargetedMovementGenerator.cpp.
References WorldObject::GetPosition(), WorldObject::GetTransport(), Unit::hasUnitState(), FollowMovementGenerator::Interrupt(), m_resetPoint, and UNIT_STAT_FOLLOW_MOVE.
Update()
bool FormationMovementGenerator::Update (Unit & unit, const uint32 & diff) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 1160 of file TargetedMovementGenerator.cpp.
References Reference< TO, FROM >::getTarget(), TargetedMovementGeneratorBase::i_target, Reference< TO, FROM >::isValid(), m_slot, TargetedMovementGeneratorBase::SetNewTarget(), and TargetedMovementGeneratorMedium< T, D >::Update().
Field Documentation
m_headingToMaster
bool FormationMovementGenerator::m_headingToMaster private
Definition at line 273 of file TargetedMovementGenerator.h.
Referenced by HandleMasterDistanceCheck().
m_lastAngle
float FormationMovementGenerator::m_lastAngle private
Definition at line 270 of file TargetedMovementGenerator.h.
Referenced by BuildPath().
m_moveToMasterDistance
float FormationMovementGenerator::m_moveToMasterDistance private
Definition at line 279 of file TargetedMovementGenerator.h.
Referenced by FormationMovementGenerator(), and HandleMasterDistanceCheck().
m_resetPoint
Position FormationMovementGenerator::m_resetPoint private
Definition at line 282 of file TargetedMovementGenerator.h.
Referenced by GetResetPosition(), and Interrupt().
m_slot
FormationSlotDataSPtr FormationMovementGenerator::m_slot private
Definition at line 267 of file TargetedMovementGenerator.h.
Referenced by BuildPath(), HandleMasterDistanceCheck(), HandleTargetedMovement(), and Update().
m_tpDistance
float FormationMovementGenerator::m_tpDistance private
Definition at line 276 of file TargetedMovementGenerator.h.
Referenced by FormationMovementGenerator(), and HandleMasterDistanceCheck().
The documentation for this class was generated from the following files:
TargetedMovementGenerator.h
TargetedMovementGenerator.cpp