CMaNGOS_WoTLK: UpdateMask Class Reference
UpdateMask Class Reference
#include <UpdateMask.h>
Public Member Functions
UpdateMask ()
UpdateMask (const UpdateMask &mask)
~UpdateMask ()
void SetBit (uint32 index)
void UnsetBit (uint32 index)
bool GetBit (uint32 index) const
uint32 GetBlockCount () const
uint32 GetLength () const
uint32 GetCount () const
uint8 * GetMask () const
bool HasData () const
void SetCount (uint32 valuesCount)
void Clear ()
UpdateMask & operator= (const UpdateMask &mask)
void operator&= (const UpdateMask &mask)
void operator|= (const UpdateMask &mask)
UpdateMask operator& (const UpdateMask &mask) const
UpdateMask operator| (const UpdateMask &mask) const
Private Attributes
bool mHasData
uint32 mCount
uint32 mBlocks
uint32 * mUpdateMask
Detailed Description
Definition at line 24 of file UpdateMask.h.
Constructor & Destructor Documentation
UpdateMask() [1/2]
UpdateMask::UpdateMask () inline
Definition at line 27 of file UpdateMask.h.
UpdateMask() [2/2]
UpdateMask::UpdateMask (const UpdateMask & mask) inline
Definition at line 28 of file UpdateMask.h.
~UpdateMask()
UpdateMask::~UpdateMask () inline
Definition at line 30 of file UpdateMask.h.
References mUpdateMask.
Member Function Documentation
Clear()
void UpdateMask::Clear () inline
Definition at line 68 of file UpdateMask.h.
References mBlocks, mHasData, and mUpdateMask.
GetBit()
bool UpdateMask::GetBit (uint32 index) const inline
Definition at line 46 of file UpdateMask.h.
References mUpdateMask.
Referenced by Object::BuildValuesUpdate().
GetBlockCount()
uint32 UpdateMask::GetBlockCount () const inline
Definition at line 51 of file UpdateMask.h.
References mBlocks.
Referenced by Object::BuildValuesUpdate().
GetCount()
uint32 UpdateMask::GetCount () const inline
Definition at line 53 of file UpdateMask.h.
References mCount.
Referenced by Object::BuildValuesUpdate().
GetLength()
uint32 UpdateMask::GetLength () const inline
Definition at line 52 of file UpdateMask.h.
References mBlocks.
Referenced by Object::BuildValuesUpdate().
GetMask()
uint8* UpdateMask::GetMask () const inline
Definition at line 54 of file UpdateMask.h.
References mUpdateMask.
Referenced by Object::BuildValuesUpdate().
HasData()
bool UpdateMask::HasData () const inline
Definition at line 55 of file UpdateMask.h.
References mHasData.
Referenced by Group::AddMember(), Object::BuildValuesUpdateBlockForPlayer(), Object::BuildValuesUpdateBlockForPlayerWithFlags(), Aura::HandleAuraControlVehicle(), and Aura::HandleModCharm().
operator&()
UpdateMask UpdateMask::operator& (const UpdateMask & mask) const inline
Definition at line 97 of file UpdateMask.h.
References MANGOS_ASSERT, and mCount.
operator&=()
void UpdateMask::operator&= (const UpdateMask & mask) inline
Definition at line 83 of file UpdateMask.h.
References MANGOS_ASSERT, mBlocks, mCount, and mUpdateMask.
operator=()
UpdateMask& UpdateMask::operator= (const UpdateMask & mask) inline
Definition at line 75 of file UpdateMask.h.
References mBlocks, mCount, mUpdateMask, and SetCount().
operator|()
UpdateMask UpdateMask::operator| (const UpdateMask & mask) const inline
Definition at line 107 of file UpdateMask.h.
References MANGOS_ASSERT, and mCount.
operator|=()
void UpdateMask::operator|= (const UpdateMask & mask) inline
Definition at line 90 of file UpdateMask.h.
References MANGOS_ASSERT, mBlocks, mCount, and mUpdateMask.
SetBit()
void UpdateMask::SetBit (uint32 index) inline
Definition at line 35 of file UpdateMask.h.
References mHasData, and mUpdateMask.
Referenced by Object::_SetCreateBits(), Object::_SetUpdateBits(), Object::BuildValuesUpdate(), and Object::MarkUpdateFieldsWithFlagForUpdate().
SetCount()
void UpdateMask::SetCount (uint32 valuesCount) inline
Definition at line 57 of file UpdateMask.h.
References mBlocks, mCount, and mUpdateMask.
Referenced by Group::AddMember(), Object::BuildCreateUpdateBlockForPlayer(), Object::BuildForcedValuesUpdateBlockForPlayer(), Object::BuildValuesUpdateBlockForPlayer(), Object::BuildValuesUpdateBlockForPlayerWithFlags(), Aura::HandleAuraControlVehicle(), Aura::HandleModCharm(), and operator=().
UnsetBit()
void UpdateMask::UnsetBit (uint32 index) inline
Definition at line 41 of file UpdateMask.h.
References mUpdateMask.
Field Documentation
mBlocks
uint32 UpdateMask::mBlocks private
Definition at line 120 of file UpdateMask.h.
Referenced by Clear(), GetBlockCount(), GetLength(), operator&=(), operator=(), operator|=(), and SetCount().
mCount
uint32 UpdateMask::mCount private
Definition at line 119 of file UpdateMask.h.
Referenced by GetCount(), operator&(), operator&=(), operator=(), operator|(), operator|=(), and SetCount().
mHasData
bool UpdateMask::mHasData private
Definition at line 118 of file UpdateMask.h.
Referenced by Clear(), HasData(), and SetBit().
mUpdateMask
uint32* UpdateMask::mUpdateMask private
Definition at line 121 of file UpdateMask.h.
Referenced by Clear(), GetBit(), GetMask(), operator&=(), operator=(), operator|=(), SetBit(), SetCount(), UnsetBit(), and ~UpdateMask().
The documentation for this class was generated from the following file:
UpdateMask.h