CMaNGOS_WoTLK: instance_temple_of_ahnqiraj Class Reference
instance_temple_of_ahnqiraj Class Reference
#include <temple_of_ahnqiraj.h>
Public Member Functions
instance_temple_of_ahnqiraj (Map *pMap)
~instance_temple_of_ahnqiraj ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void DoHandleTempleAreaTrigger (uint32 triggerId, Player *player)
const char * Save () const override
void Load (const char *chrIn) override
void Update (uint32 uiDiff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void JustDidDialogueStep (int32 entry) override
Will be called when a dialogue step was done.
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint8 m_uiBugTrioDeathCount
uint32 m_uiCthunWhisperTimer
uint32 m_uiSkeramProphecyTimer
GuidVector m_bugTrioSpawns
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 94 of file temple_of_ahnqiraj.h.
Constructor & Destructor Documentation
instance_temple_of_ahnqiraj()
instance_temple_of_ahnqiraj::instance_temple_of_ahnqiraj (Map * pMap)
Definition at line 40 of file temple_of_ahnqiraj.cpp.
References Initialize().
~instance_temple_of_ahnqiraj()
instance_temple_of_ahnqiraj::~instance_temple_of_ahnqiraj () inline
Definition at line 98 of file temple_of_ahnqiraj.h.
Member Function Documentation
DoHandleTempleAreaTrigger()
void instance_temple_of_ahnqiraj::DoHandleTempleAreaTrigger (uint32 triggerId, Player * player)
Definition at line 96 of file temple_of_ahnqiraj.cpp.
References AREATRIGGER_SARTURA, AREATRIGGER_TWIN_EMPERORS, EMOTE_EYE_INTRO, FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, NOT_STARTED, NPC_MASTERS_EYE, NPC_SARTURA, SetData(), DialogueHelper::StartNextDialogueText(), TYPE_SARTURA, and TYPE_TWINS_INTRO.
GetData()
uint32 instance_temple_of_ahnqiraj::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 384 of file temple_of_ahnqiraj.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by DoHandleTempleAreaTrigger(), boss_veknilashAI::MoveInLineOfSight(), boss_veklorAI::MoveInLineOfSight(), OnCreatureCreate(), SetData(), and Update().
Initialize()
void instance_temple_of_ahnqiraj::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 49 of file temple_of_ahnqiraj.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_temple_of_ahnqiraj().
IsEncounterInProgress()
bool instance_temple_of_ahnqiraj::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 56 of file temple_of_ahnqiraj.cpp.
References IN_PROGRESS, and m_auiEncounter.
JustDidDialogueStep()
void instance_temple_of_ahnqiraj::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 67 of file temple_of_ahnqiraj.cpp.
References DONE, EMOTE_EYE_INTRO, ScriptedInstance::GetSingleCreatureFromStorage(), NPC_MASTERS_EYE, NPC_VEKLOR, NPC_VEKNILASH, SAY_EMPERORS_INTRO_6, SetData(), STAND_EMPERORS_INTRO, TYPE_TWINS_INTRO, and UNIT_STAND_STATE_STAND.
Load()
void instance_temple_of_ahnqiraj::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 360 of file temple_of_ahnqiraj.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_temple_of_ahnqiraj::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 133 of file temple_of_ahnqiraj.cpp.
References Creature::AI(), Unit::CastSpell(), DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), IN_PROGRESS, Unit::IsAlive(), m_bugTrioSpawns, ScriptedInstance::m_npcEntryGuidStore, NPC_CLAW_TENTACLE, NPC_CTHUN, NPC_EYE_OF_CTHUN, NPC_EYE_TENTACLE, NPC_GIANT_CLAW_TENTACLE, NPC_GIANT_EYE_TENTACLE, NPC_KRI, NPC_MASTERS_EYE, NPC_OURO_SPAWNER, NPC_POISON_CLOUD, NPC_SARTURA, NPC_SKERAM, NPC_VEKLOR, NPC_VEKNILASH, NPC_VEM, NPC_VISCIDUS, NPC_YAUJ, Creature::Respawn(), UnitAI::SetCombatMovement(), Unit::SetStandState(), SPELL_SUMMON_GIANT_PORTAL, SPELL_SUMMON_PORTAL, TRIGGERED_OLD_TRIGGERED, TYPE_CTHUN, TYPE_SKERAM, TYPE_TWINS_INTRO, and UNIT_STAND_STATE_KNEEL.
OnCreatureDeath()
void instance_temple_of_ahnqiraj::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 116 of file temple_of_ahnqiraj.cpp.
References GetClosestCreatureWithEntry(), Object::GetEntry(), NPC_CLAW_TENTACLE, NPC_EYE_TENTACLE, NPC_GIANT_CLAW_TENTACLE, NPC_GIANT_EYE_TENTACLE, NPC_GIANT_TENTACLE_PORTAL, and NPC_TENTACLE_PORTAL.
OnCreatureRespawn()
void instance_temple_of_ahnqiraj::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 210 of file temple_of_ahnqiraj.cpp.
References Creature::AI(), Object::GetEntry(), NPC_EXIT_TRIGGER, NPC_QIRAJI_SCARAB, NPC_QIRAJI_SCORPION, UnitAI::SetCombatMovement(), Creature::SetCorpseDelay(), and Creature::SetInCombatWithZone().
OnObjectCreate()
void instance_temple_of_ahnqiraj::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 184 of file temple_of_ahnqiraj.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_SANDWORM_BASE, GO_SKERAM_GATE, GO_STATE_ACTIVE, GO_TWINS_ENTER_DOOR, GO_TWINS_EXIT_DOOR, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), TYPE_HUHURAN, TYPE_SKERAM, and TYPE_TWINS.
Save()
const char* instance_temple_of_ahnqiraj::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 114 of file temple_of_ahnqiraj.h.
References m_strInstData.
SetData()
void instance_temple_of_ahnqiraj::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 226 of file temple_of_ahnqiraj.cpp.
References AI_EVENT_CUSTOM_A, DONE, ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_JUST_DEACTIVATED, GO_SANDWORM_BASE, GO_SKERAM_GATE, GO_TWINS_ENTER_DOOR, GO_TWINS_EXIT_DOOR, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bugTrioSpawns, m_strInstData, m_uiBugTrioDeathCount, NPC_CTHUN, NPC_EYE_OF_CTHUN, NPC_KRI, NPC_OURO_SPAWNER, NPC_VEM, NPC_YAUJ, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, TYPE_BUG_TRIO, TYPE_CTHUN, TYPE_FANKRISS, TYPE_HUHURAN, TYPE_OURO, TYPE_SARTURA, TYPE_SKERAM, TYPE_TWINS, TYPE_TWINS_INTRO, and TYPE_VISCIDUS.
Referenced by boss_twin_emperorsAI::Aggro(), DoHandleTempleAreaTrigger(), JustDidDialogueStep(), boss_twin_emperorsAI::JustDied(), and boss_twin_emperorsAI::JustReachedHome().
Update()
void instance_temple_of_ahnqiraj::Update (uint32 uiDiff) override virtual
Reimplemented from InstanceData.
Definition at line 392 of file temple_of_ahnqiraj.cpp.
References DialogueHelper::DialogueUpdate(), DONE, DoScriptText(), GetData(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, m_uiCthunWhisperTimer, m_uiSkeramProphecyTimer, MINUTE, NOT_STARTED, NPC_CTHUN, SAY_CTHUN_WHISPER_1, SAY_CTHUN_WHISPER_2, SAY_CTHUN_WHISPER_3, SAY_CTHUN_WHISPER_4, SAY_CTHUN_WHISPER_5, SAY_CTHUN_WHISPER_6, SAY_CTHUN_WHISPER_7, SAY_CTHUN_WHISPER_8, sound_skeram_prophecy, TYPE_CTHUN, TYPE_SKERAM, and urand().
Field Documentation
m_auiEncounter
uint32 instance_temple_of_ahnqiraj::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 120 of file temple_of_ahnqiraj.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), and SetData().
m_bugTrioSpawns
GuidVector instance_temple_of_ahnqiraj::m_bugTrioSpawns private
Definition at line 127 of file temple_of_ahnqiraj.h.
Referenced by OnCreatureCreate(), and SetData().
m_strInstData
std::string instance_temple_of_ahnqiraj::m_strInstData private
Definition at line 121 of file temple_of_ahnqiraj.h.
Referenced by Save(), and SetData().
m_uiBugTrioDeathCount
uint8 instance_temple_of_ahnqiraj::m_uiBugTrioDeathCount private
Definition at line 123 of file temple_of_ahnqiraj.h.
Referenced by SetData().
m_uiCthunWhisperTimer
uint32 instance_temple_of_ahnqiraj::m_uiCthunWhisperTimer private
Definition at line 124 of file temple_of_ahnqiraj.h.
Referenced by Update().
m_uiSkeramProphecyTimer
uint32 instance_temple_of_ahnqiraj::m_uiSkeramProphecyTimer private
Definition at line 125 of file temple_of_ahnqiraj.h.
Referenced by Update().
The documentation for this class was generated from the following files:
temple_of_ahnqiraj.h
temple_of_ahnqiraj.cpp