CMaNGOS_WoTLK: WorldPacket Class Reference
WorldPacket Class Reference
#include <WorldPacket.h>
Public Member Functions
WorldPacket ()
WorldPacket (Opcodes opcode, size_t res=200)
WorldPacket (const WorldPacket &packet)
WorldPacket (const WorldPacket &packet, std::chrono::steady_clock::time_point receivedTime)
void Initialize (Opcodes opcode, size_t newres=200)
Opcodes GetOpcode () const
void SetOpcode (Opcodes opcode)
const char * GetOpcodeName () const
std::chrono::steady_clock::time_point GetReceivedTime () const
void SetReceivedTime (std::chrono::steady_clock::time_point receivedTime)
Public Member Functions inherited from ByteBuffer
ByteBuffer (size_t reservedSize=s_defaultSize)
virtual ~ByteBuffer ()=default
ByteBuffer (const ByteBuffer &)=default
ByteBuffer (ByteBuffer &&byteBuffer) noexcept
ByteBuffer (size_t size, Reserve)
ByteBuffer (size_t size, Resize)
ByteBuffer & operator= (const ByteBuffer &)=default
ByteBuffer & operator= (ByteBuffer &&byteBuffer) noexcept
void clear ()
template<typename T >
void put (size_t pos, T value)
ByteBuffer & operator<< (uint8 value)
ByteBuffer & operator<< (uint16 value)
ByteBuffer & operator<< (uint32 value)
ByteBuffer & operator<< (uint64 value)
ByteBuffer & operator<< (int8 value)
ByteBuffer & operator<< (int16 value)
ByteBuffer & operator<< (int32 value)
ByteBuffer & operator<< (int64 value)
ByteBuffer & operator<< (float value)
ByteBuffer & operator<< (double value)
ByteBuffer & operator<< (const std::string &value)
ByteBuffer & operator<< (const char *str)
ByteBuffer & operator>> (bool &value)
ByteBuffer & operator>> (uint8 &value)
ByteBuffer & operator>> (uint16 &value)
ByteBuffer & operator>> (uint32 &value)
ByteBuffer & operator>> (uint64 &value)
ByteBuffer & operator>> (int8 &value)
ByteBuffer & operator>> (int16 &value)
ByteBuffer & operator>> (int32 &value)
ByteBuffer & operator>> (int64 &value)
ByteBuffer & operator>> (float &value)
ByteBuffer & operator>> (double &value)
ByteBuffer & operator>> (std::string &value)
template<class T >
ByteBuffer & operator>> (Unused< T > const &)
uint8 operator[] (size_t pos) const
size_t rpos () const
size_t rpos (size_t rpos_)
size_t wpos () const
size_t wpos (size_t wpos_)
template<typename T >
void read_skip ()
void read_skip (size_t skip)
template<typename T >
T read ()
template<typename T >
T read (size_t pos) const
void read (uint8 *dest, size_t len)
void read (std::string &value, bool utf8)
uint64 readPackGUID ()
const uint8 * contents () const
size_t size () const
bool empty () const
void resize (size_t newsize)
void reserve (size_t ressize)
void append (const std::string &str)
void append (const char *src, size_t cnt)
template<class T >
void append (const T *src, size_t cnt)
void append (const uint8 *src, size_t cnt)
void append (const std::vector< uint8 > &buffer)
void append (const ByteBuffer &buffer)
void appendPackXYZ (float x, float y, float z)
void appendPackGUID (uint64 guid)
void put (size_t pos, const uint8 *src, size_t cnt)
void print_storage () const
void textlike () const
void hexlike () const
template<>
void read_skip ()
template<>
void read_skip ()
Protected Attributes
Opcodes m_opcode
std::chrono::steady_clock::time_point m_receivedTime
Detailed Description
Definition at line 29 of file WorldPacket.h.
Constructor & Destructor Documentation
WorldPacket() [1/4]
WorldPacket::WorldPacket () inline
Definition at line 33 of file WorldPacket.h.
WorldPacket() [2/4]
WorldPacket::WorldPacket (Opcodes opcode, size_t res = 200) inline explicit
Definition at line 36 of file WorldPacket.h.
WorldPacket() [3/4]
WorldPacket::WorldPacket (const WorldPacket & packet) inline
Definition at line 38 of file WorldPacket.h.
WorldPacket() [4/4]
WorldPacket::WorldPacket (const WorldPacket & packet, std::chrono::steady_clock::time_point receivedTime) inline
Definition at line 41 of file WorldPacket.h.
Member Function Documentation
GetOpcode()
Opcodes WorldPacket::GetOpcode () const inline
Definition at line 53 of file WorldPacket.h.
References m_opcode.
Referenced by WorldSession::Handle_Deprecated(), WorldSession::Handle_EarlyProccess(), WorldSession::Handle_NULL(), WorldSession::Handle_ServerSide(), NamreebAnticheat::Movement::HandleAnticheatTests(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleChannelAnnouncementsOpcode(), WorldSession::HandleChannelBanOpcode(), WorldSession::HandleChannelDisplayListQueryOpcode(), WorldSession::HandleChannelInviteOpcode(), WorldSession::HandleChannelKickOpcode(), WorldSession::HandleChannelListOpcode(), WorldSession::HandleChannelModerateOpcode(), WorldSession::HandleChannelModeratorOpcode(), WorldSession::HandleChannelMuteOpcode(), WorldSession::HandleChannelOwnerOpcode(), WorldSession::HandleChannelPasswordOpcode(), WorldSession::HandleChannelSetOwnerOpcode(), WorldSession::HandleChannelUnbanOpcode(), WorldSession::HandleChannelUnmoderatorOpcode(), WorldSession::HandleChannelUnmuteOpcode(), ChatHandler::HandleDebugSendOpcodeCommand(), WorldSession::HandleForceSpeedChangeAckOpcodes(), WorldSession::HandleGetChannelMemberCountOpcode(), WorldSession::HandleJoinChannelOpcode(), WorldSession::HandleLeaveChannelOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), PlayerbotMgr::HandleMasterOutgoingPacket(), WorldSession::HandleMoveFlagChangeOpcode(), WorldSession::HandleMoveKnockBackAck(), WorldSession::HandleMovementOpcodes(), WorldSession::HandleMoveRootAck(), WorldSession::HandleMoveTeleportAckOpcode(), WorldSession::HandleRequestVehicleNextSeat(), WorldSession::HandleSetAllowLowLevelRaidOpcode(), WorldSession::HandleSetChannelWatchOpcode(), NamreebAnticheat::Movement::HandleSpeedChangeAck(), PacketLog::LogPacket(), WorldSession::LogUnexpectedOpcode(), WorldSession::LogUnprocessedTail(), NullSessionAnticheat::Movement(), NamreebAnticheat::SessionAnticheat::Movement(), MapSessionFilter::Process(), WorldSessionFilter::Process(), WorldSession::ProcessByteBufferException(), WorldSession::ProcessMovementInfo(), Unit::SendMoveRoot(), WorldSocket::SendPacket(), Unit::SendTeleportPacket(), Unit::SetCanFly(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetSpeedRate(), Unit::SetWaterWalk(), and WorldSession::SizeError().
GetOpcodeName()
const char* WorldPacket::GetOpcodeName () const inline
Definition at line 55 of file WorldPacket.h.
References LookupOpcodeName(), and m_opcode.
Referenced by WorldSession::Handle_Deprecated(), WorldSession::Handle_EarlyProccess(), WorldSession::Handle_NULL(), WorldSession::Handle_ServerSide(), WorldSession::HandleChannelAnnouncementsOpcode(), WorldSession::HandleChannelBanOpcode(), WorldSession::HandleChannelDisplayListQueryOpcode(), WorldSession::HandleChannelInviteOpcode(), WorldSession::HandleChannelKickOpcode(), WorldSession::HandleChannelListOpcode(), WorldSession::HandleChannelModerateOpcode(), WorldSession::HandleChannelModeratorOpcode(), WorldSession::HandleChannelMuteOpcode(), WorldSession::HandleChannelOwnerOpcode(), WorldSession::HandleChannelPasswordOpcode(), WorldSession::HandleChannelSetOwnerOpcode(), WorldSession::HandleChannelUnbanOpcode(), WorldSession::HandleChannelUnmoderatorOpcode(), WorldSession::HandleChannelUnmuteOpcode(), ChatHandler::HandleDebugSendOpcodeCommand(), WorldSession::HandleForceSpeedChangeAckOpcodes(), WorldSession::HandleGetChannelMemberCountOpcode(), WorldSession::HandleJoinChannelOpcode(), WorldSession::HandleLeaveChannelOpcode(), WorldSession::HandleMoveFlagChangeOpcode(), WorldSession::HandleMoveRootAck(), WorldSession::HandleSetChannelWatchOpcode(), WorldSession::LogUnexpectedOpcode(), WorldSession::LogUnprocessedTail(), WorldSocket::SendPacket(), and WorldSession::SizeError().
GetReceivedTime()
std::chrono::steady_clock::time_point WorldPacket::GetReceivedTime () const inline
Definition at line 57 of file WorldPacket.h.
References m_receivedTime.
Referenced by WorldSession::HandleTimeSyncResp().
Initialize()
void WorldPacket::Initialize (Opcodes opcode, size_t newres = 200) inline
Definition at line 46 of file WorldPacket.h.
References ByteBuffer::clear(), m_opcode, and ByteBuffer::reserve().
Referenced by PlayerbotAI::_HandleCommandSkill(), Unit::AddComboPoints(), VehicleInfo::Board(), BattleGroundMgr::BuildBattleGroundListPacket(), BattleGroundMgr::BuildBattleGroundStatusPacket(), ChatHandler::BuildChatPacket(), BattleGroundMgr::BuildGroupJoinedBattlegroundPacket(), WorldSession::BuildPartyMemberStatsChangedPacket(), BattleGroundMgr::BuildPlayerJoinedBattleGroundPacket(), BattleGroundMgr::BuildPlayerLeftBattleGroundPacket(), BattleGroundMgr::BuildPlaySoundPacket(), BattleGroundMgr::BuildPvpLogDataPacket(), BattleGroundMgr::BuildUpdateWorldStatePacket(), Group::Disband(), Player::DuelComplete(), Spell::EffectBind(), Spell::EffectTeachTaxiNode(), WorldSocket::HandleAuthSession(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePlayerLogin(), WorldSession::HandlePlayerReconnect(), WorldSession::HandleReadItemOpcode(), WorldSession::HandleTrainerBuySpellOpcode(), SpellLog::Initialize(), Channel::JoinNotify(), SocialMgr::MakeFriendStatusPacket(), Channel::MakeNotifyPacket(), MaNGOS::EmoteChatBuilder::operator()(), NamreebAnticheat::SessionAnticheat::ReadAddonInfo(), Group::RemoveMember(), Spell::SendChannelStart(), ReputationMgr::SendForceReactions(), Player::SendInitialPacketsBeforeAddToMap(), Spell::SendInterrupted(), Player::SendSavedInstances(), and Unit::SendTeleportPacket().
SetOpcode()
void WorldPacket::SetOpcode (Opcodes opcode) inline
Definition at line 54 of file WorldPacket.h.
References m_opcode.
Referenced by UpdateData::BuildPacket(), WorldSession::HandleClientCastFlags(), WorldSession::HandleUpdateMissileTrajectory(), Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
SetReceivedTime()
void WorldPacket::SetReceivedTime (std::chrono::steady_clock::time_point receivedTime) inline
Definition at line 58 of file WorldPacket.h.
References m_receivedTime.
Field Documentation
m_opcode
Opcodes WorldPacket::m_opcode protected
Definition at line 61 of file WorldPacket.h.
Referenced by GetOpcode(), GetOpcodeName(), Initialize(), and SetOpcode().
m_receivedTime
std::chrono::steady_clock::time_point WorldPacket::m_receivedTime protected
Definition at line 62 of file WorldPacket.h.
Referenced by GetReceivedTime(), and SetReceivedTime().
The documentation for this class was generated from the following file:
WorldPacket.h