CMaNGOS_WoTLK: SpellMgr Class Reference
SpellMgr Class Reference
#include <SpellMgr.h>
Public Types
enum SpellFaction { SPELL_NEUTRAL = 0 , SPELL_HELPFUL = 1 , SPELL_HARMFUL = 2 }
Public Member Functions
SpellMgr ()
~SpellMgr ()
SpellElixirMap const & GetSpellElixirMap () const
uint32 GetSpellElixirMask (uint32 spellid) const
SpellSpecific GetSpellElixirSpecific (uint32 spellid) const
SpellSpecific GetSpellFoodSpecific (const SpellEntry *entry) const
SpellThreatEntry const * GetSpellThreatEntry (uint32 spellid) const
float GetSpellThreatMultiplier (SpellEntry const *spellInfo) const
SpellProcEventEntry const * GetSpellProcEvent (uint32 spellId) const
float GetItemEnchantProcChance (uint32 spellid) const
SpellBonusEntry const * GetSpellBonusData (uint32 spellId) const
SpellTargetPosition const * GetSpellTargetPosition (uint32 spell_id) const
SpellChainNode const * GetSpellChainNode (uint32 spell_id) const
uint32 GetFirstSpellInChain (uint32 spell_id) const
uint32 GetPrevSpellInChain (uint32 spell_id) const
uint32 GetNextSpellInChain (uint32 spell_id) const
SpellChainMapNext const & GetSpellChainNext () const
template<typename Worker >
void doForHighRanks (uint32 spellid, Worker &worker)
uint8 GetSpellRank (uint32 spell_id) const
bool IsSpellHigherRankOfSpell (uint32 spellId1, uint32 spellId2) const
bool IsSpellAnotherRankOfSpell (uint32 spellId1, uint32 spellId2) const
bool IsSingleTargetSpell (SpellEntry const *entry) const
bool IsSingleTargetSpells (SpellEntry const *entry1, SpellEntry const *entry2) const
bool IsSpellStackableWithSpell (const SpellEntry *entry1, const SpellEntry *entry2) const
bool IsSpellStackableWithSpellForDifferentCasters (const SpellEntry *entry1, const SpellEntry *entry2) const
uint32 GetSpellBookSuccessorSpellId (uint32 spellId)
bool IsSpellCanAffectSpell (SpellEntry const *spellInfo_1, SpellEntry const *spellInfo_2) const
SpellEntry const * SelectAuraRankForLevel (SpellEntry const *spellInfo, uint32 level) const
SpellLearnSkillNode const * GetSpellLearnSkill (uint32 spell_id) const
bool IsSpellLearnSpell (uint32 spell_id) const
SpellLearnSpellMapBounds GetSpellLearnSpellMapBounds (uint32 spell_id) const
bool IsSpellLearnToSpell (uint32 parent, uint32 child) const
bool IsPrimaryProfessionFirstRankSpell (uint32 spellId) const
uint32 GetProfessionSpellMinLevel (uint32 spellId) const
bool IsSkillBonusSpell (uint32 spellId) const
SkillLineAbilityMapBounds GetSkillLineAbilityMapBoundsBySpellId (uint32 spellId) const
SkillLineAbilityMapBounds GetSkillLineAbilityMapBoundsBySkillId (uint32 skillId) const
SkillRaceClassInfoMapBounds GetSkillRaceClassInfoMapBounds (uint32 skill_id) const
PetAura const * GetPetAura (uint32 spell_id, SpellEffectIndex eff)
PetLevelupSpellSet const * GetPetLevelupSpellList (uint32 petFamily) const
PetDefaultSpellsEntry const * GetPetDefaultSpellsEntry (int32 id) const
SpellCastResult GetSpellAllowedInLocationError (SpellEntry const *spellInfo, uint32 map_id, uint32 zone_id, uint32 area_id, Player const *player=nullptr) const
SpellAreaMapBounds GetSpellAreaMapBounds (uint32 spell_id) const
SpellAreaForAuraMapBounds GetSpellAreaForAuraMapBounds (uint32 spell_id) const
SpellAreaForAreaMapBounds GetSpellAreaForAreaMapBounds (uint32 area_id) const
void CheckUsedSpells (char const *table) const
void LoadSpellChains ()
void LoadSpellLearnSkills ()
void LoadSpellLearnSpells ()
void LoadSpellScriptTarget ()
void LoadSpellElixirs ()
void LoadSpellProcEvents ()
void LoadSpellProcItemEnchant ()
void LoadSpellBonuses ()
void LoadSpellTargetPositions ()
void LoadSpellThreats ()
void LoadSkillLineAbilityMaps ()
void LoadSkillRaceClassInfoMap ()
void LoadSpellPetAuras ()
void LoadPetLevelupSpellMap ()
void LoadPetDefaultSpells ()
void LoadSpellAreas ()
Static Public Member Functions
static bool IsSpellTargetHarmfulAtClient (uint32 target)
static bool IsSpellTargetHelpfulAtClient (uint32 target)
static bool IsSpellEffectHarmfulAtClient (const SpellEntry &entry, SpellEffectIndex effIndex)
static bool IsSpellEffectHelpfulAtClient (const SpellEntry &entry, SpellEffectIndex effIndex)
static SpellFaction GetSpellFactionAtClient (const SpellEntry &entry, SpellEffectIndexMask mask=EFFECT_MASK_ALL)
static bool IsSpellProcEventCanTriggeredBy (SpellProcEventEntry const *spellProcEvent, uint32 EventProcFlag, SpellEntry const *spellInfo, uint32 procFlags, uint32 procExtra)
static bool IsProfessionOrRidingSpell (uint32 spellId)
static bool IsProfessionSpell (uint32 spellId)
static bool IsPrimaryProfessionSpell (uint32 spellId)
static bool IsSpellValid (SpellEntry const *spellInfo, Player *pl=nullptr, bool msg=true)
Some checks for spells, to prevent adding deprecated/broken spells for trainers, spell book, etc.
static SpellMgr & Instance ()
Private Member Functions
bool LoadPetDefaultSpells_helper (CreatureInfo const *cInfo, PetDefaultSpellsEntry &petDefSpells)
Private Attributes
SpellChainMap mSpellChains
SpellChainMapNext mSpellChainsNext
SpellLearnSkillMap mSpellLearnSkills
SpellLearnSpellMap mSpellLearnSpells
SpellTargetPositionMap mSpellTargetPositions
SpellElixirMap mSpellElixirs
SpellThreatMap mSpellThreatMap
SpellProcEventMap mSpellProcEventMap
SpellProcItemEnchantMap mSpellProcItemEnchantMap
SpellBonusMap mSpellBonusMap
SkillLineAbilityMap mSkillLineAbilityMapBySpellId
SkillLineAbilityMap mSkillLineAbilityMapBySkillId
SkillRaceClassInfoMap mSkillRaceClassInfoMap
SpellPetAuraMap mSpellPetAuraMap
PetLevelupSpellMap mPetLevelupSpellMap
PetDefaultSpellsMap mPetDefaultSpellsMap
SpellAreaMap mSpellAreaMap
SpellAreaForAuraMap mSpellAreaForAuraMap
SpellAreaForAreaMap mSpellAreaForAreaMap
Friends
struct DoSpellBonuses
struct DoSpellProcEvent
struct DoSpellProcItemEnchant
Detailed Description
Definition at line 2739 of file SpellMgr.h.
Member Enumeration Documentation
SpellFaction
enum SpellMgr::SpellFaction
Enumerator
SPELL_NEUTRAL
SPELL_HELPFUL
SPELL_HARMFUL
Definition at line 2929 of file SpellMgr.h.
Constructor & Destructor Documentation
SpellMgr()
SpellMgr::SpellMgr ()
Definition at line 45 of file SpellMgr.cpp.
~SpellMgr()
SpellMgr::~SpellMgr ()
Definition at line 49 of file SpellMgr.cpp.
Member Function Documentation
CheckUsedSpells()
void SpellMgr::CheckUsedSpells (char const * table) const
Definition at line 3044 of file SpellMgr.cpp.
References SpellEntry::Category, SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, QueryResult::Fetch(), Field::GetCppString(), Field::GetInt32(), SQLStorageBase::GetMaxEntry(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt64(), SpellEntry::IsFitToFamilyMask(), IsSpellHaveAura(), IsSpellHaveEffect(), SQLStorage::LookupEntry(), MAX_SPELL_EFFECTS, QueryResult::NextRow(), Database::PQuery(), sLog, SPELLFAMILY_PET, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellEntry::SpellVisual, sSpellCategoryStore, sSpellTemplate, BarGoLink::step(), TOTAL_AURAS, UI64FMTD, and WorldDatabase.
doForHighRanks()
template<typename Worker > void SpellMgr::doForHighRanks (uint32 spellid, Worker & worker) inline
Definition at line 3070 of file SpellMgr.h.
References GetSpellChainNext().
Referenced by SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), LoadSpellBonuses(), and LoadSpellProcItemEnchant().
GetFirstSpellInChain()
uint32 SpellMgr::GetFirstSpellInChain (uint32 spell_id) const inline
Definition at line 3032 of file SpellMgr.h.
References GetSpellChainNode().
Referenced by IsSpellAnotherRankOfSpell(), LoadSpellBonuses(), LoadSpellProcItemEnchant(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
GetItemEnchantProcChance()
float SpellMgr::GetItemEnchantProcChance (uint32 spellid) const inline
Definition at line 2991 of file SpellMgr.h.
References mSpellProcItemEnchantMap.
GetNextSpellInChain()
uint32 SpellMgr::GetNextSpellInChain (uint32 spell_id) const inline
Definition at line 3048 of file SpellMgr.h.
References GetSpellChainNext(), GetSpellChainNode(), SpellChainNode::prev, and SpellChainNode::req.
GetPetAura()
PetAura const* SpellMgr::GetPetAura (uint32 spell_id, SpellEffectIndex eff) inline
Definition at line 3266 of file SpellMgr.h.
References mSpellPetAuraMap.
GetPetDefaultSpellsEntry()
PetDefaultSpellsEntry const* SpellMgr::GetPetDefaultSpellsEntry (int32 id) const inline
Definition at line 3283 of file SpellMgr.h.
References mPetDefaultSpellsMap.
GetPetLevelupSpellList()
PetLevelupSpellSet const* SpellMgr::GetPetLevelupSpellList (uint32 petFamily) const inline
Definition at line 3274 of file SpellMgr.h.
References mPetLevelupSpellMap.
Referenced by LoadPetDefaultSpells_helper().
GetPrevSpellInChain()
uint32 SpellMgr::GetPrevSpellInChain (uint32 spell_id) const inline
Definition at line 3040 of file SpellMgr.h.
References GetSpellChainNode().
Referenced by SelectAuraRankForLevel().
GetProfessionSpellMinLevel()
uint32 SpellMgr::GetProfessionSpellMinLevel (uint32 spellId) const
Definition at line 1467 of file SpellMgr.cpp.
References GetSkillLineAbilityMapBoundsBySpellId(), GetSpellRank(), SKILL_FISHING, SKILL_HERBALISM, SKILL_MINING, and SKILL_SKINNING.
GetSkillLineAbilityMapBoundsBySkillId()
SkillLineAbilityMapBounds SpellMgr::GetSkillLineAbilityMapBoundsBySkillId (uint32 skillId) const inline
Definition at line 3256 of file SpellMgr.h.
References mSkillLineAbilityMapBySkillId.
GetSkillLineAbilityMapBoundsBySpellId()
SkillLineAbilityMapBounds SpellMgr::GetSkillLineAbilityMapBoundsBySpellId (uint32 spellId) const inline
Definition at line 3251 of file SpellMgr.h.
References mSkillLineAbilityMapBySpellId.
Referenced by GetProfessionSpellMinLevel(), GetSpellBookSuccessorSpellId(), and IsSkillBonusSpell().
GetSkillRaceClassInfoMapBounds()
SkillRaceClassInfoMapBounds SpellMgr::GetSkillRaceClassInfoMapBounds (uint32 skill_id) const inline
Definition at line 3261 of file SpellMgr.h.
References mSkillRaceClassInfoMap.
GetSpellAllowedInLocationError()
SpellCastResult SpellMgr::GetSpellAllowedInLocationError (SpellEntry const * spellInfo, uint32 map_id, uint32 zone_id, uint32 area_id, Player const * player = nullptr) const
Definition at line 2869 of file SpellMgr.cpp.
References MapEntry::addon, SpellEntry::AreaGroupId, AreaGroupEntry::AreaId, Player::GetBattleGround(), GetSpellAreaMapBounds(), GetSpellRecoveryTime(), BattleGround::GetStatus(), GetVirtualMapForMapAndZone(), SpellEntry::HasAttribute(), SpellEntry::Id, IN_MILLISECONDS, Player::InArena(), Player::InBattleGround(), BattleGround::IsArena(), MapEntry::IsBattleGround(), MapEntry::IsContinent(), Player::IsGameMaster(), MapEntry::IsRaid(), SQLStorage::LookupEntry(), MINUTE, AreaGroupEntry::nextGroup, sAreaGroupStore, sMapStore, SPELL_ATTR_EX3_ONLY_BATTLEGROUNDS, SPELL_ATTR_EX4_IGNORE_DEFAULT_ARENA_RESTRICTIONS, SPELL_ATTR_EX4_NOT_IN_ARENA, SPELL_ATTR_EX4_ONLY_FLYING_AREAS, SPELL_ATTR_EX6_NOT_IN_RAID_INSTANCES, SPELL_CAST_OK, SPELL_FAILED_INCORRECT_AREA, SPELL_FAILED_NOT_IN_ARENA, SPELL_FAILED_NOT_IN_RAID_INSTANCE, SPELL_FAILED_ONLY_BATTLEGROUNDS, SPELL_FAILED_ONLY_IN_ARENA, SPELL_FAILED_REQUIRES_AREA, and STATUS_WAIT_JOIN.
GetSpellAreaForAreaMapBounds()
SpellAreaForAreaMapBounds SpellMgr::GetSpellAreaForAreaMapBounds (uint32 area_id) const inline
Definition at line 3303 of file SpellMgr.h.
References mSpellAreaForAreaMap.
GetSpellAreaForAuraMapBounds()
SpellAreaForAuraMapBounds SpellMgr::GetSpellAreaForAuraMapBounds (uint32 spell_id) const inline
Definition at line 3298 of file SpellMgr.h.
References mSpellAreaForAuraMap.
Referenced by LoadSpellAreas().
GetSpellAreaMapBounds()
SpellAreaMapBounds SpellMgr::GetSpellAreaMapBounds (uint32 spell_id) const inline
Definition at line 3293 of file SpellMgr.h.
References mSpellAreaMap.
Referenced by GetSpellAllowedInLocationError(), and LoadSpellAreas().
GetSpellBonusData()
SpellBonusEntry const* SpellMgr::GetSpellBonusData (uint32 spellId) const inline
Definition at line 3003 of file SpellMgr.h.
References mSpellBonusMap.
GetSpellBookSuccessorSpellId()
uint32 SpellMgr::GetSpellBookSuccessorSpellId (uint32 spellId) inline
Definition at line 3193 of file SpellMgr.h.
References GetSkillLineAbilityMapBoundsBySpellId().
GetSpellChainNext()
SpellChainMapNext const& SpellMgr::GetSpellChainNext () const inline
Definition at line 3067 of file SpellMgr.h.
References mSpellChainsNext.
Referenced by doForHighRanks(), and GetNextSpellInChain().
GetSpellChainNode()
SpellChainNode const* SpellMgr::GetSpellChainNode (uint32 spell_id) const inline
Definition at line 3023 of file SpellMgr.h.
References mSpellChains.
Referenced by GetFirstSpellInChain(), GetNextSpellInChain(), GetPrevSpellInChain(), and GetSpellRank().
GetSpellElixirMap()
SpellElixirMap const& SpellMgr::GetSpellElixirMap () const inline
Definition at line 2753 of file SpellMgr.h.
References mSpellElixirs.
GetSpellElixirMask()
uint32 SpellMgr::GetSpellElixirMask (uint32 spellid) const inline
Definition at line 2755 of file SpellMgr.h.
References mSpellElixirs.
Referenced by GetSpellElixirSpecific().
GetSpellElixirSpecific()
SpellSpecific SpellMgr::GetSpellElixirSpecific (uint32 spellid) const inline
Definition at line 2764 of file SpellMgr.h.
References ELIXIR_BATTLE_MASK, ELIXIR_FLASK_MASK, ELIXIR_GUARDIAN_MASK, ELIXIR_WELL_FED, GetSpellElixirMask(), SPELL_BATTLE_ELIXIR, SPELL_FLASK_ELIXIR, SPELL_GUARDIAN_ELIXIR, SPELL_NORMAL, and SPELL_WELL_FED.
GetSpellFactionAtClient()
static SpellFaction SpellMgr::GetSpellFactionAtClient (const SpellEntry & entry, SpellEffectIndexMask mask = EFFECT_MASK_ALL) inline static
Definition at line 2937 of file SpellMgr.h.
References SpellEntry::Effect, IsSpellEffectHarmfulAtClient(), IsSpellEffectHelpfulAtClient(), MAX_EFFECT_INDEX, SPELL_HARMFUL, SPELL_HELPFUL, SPELL_NEUTRAL, TARGET_FLAG_UNIT_ALLY, TARGET_FLAG_UNIT_ENEMY, and SpellEntry::Targets.
GetSpellFoodSpecific()
SpellSpecific SpellMgr::GetSpellFoodSpecific (const SpellEntry * entry) const inline
Definition at line 2778 of file SpellMgr.h.
References AURA_INTERRUPT_FLAG_STANDING_CANCELS, SpellEntry::AuraInterruptFlags, SpellEntry::EffectApplyAuraName, SpellEntry::HasAttribute(), SpellEntry::Id, MAX_EFFECT_INDEX, SPELL_ATTR_EX2_RETAIN_ITEM_CAST, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_REGEN, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_MANA, SPELL_DRINK, SPELL_FOOD, SPELL_FOOD_AND_DRINK, SPELL_NORMAL, SPELL_WELL_FED, SPELLFAMILY_GENERIC, and SpellEntry::SpellFamilyName.
GetSpellLearnSkill()
SpellLearnSkillNode const* SpellMgr::GetSpellLearnSkill (uint32 spell_id) const inline
Definition at line 3213 of file SpellMgr.h.
References mSpellLearnSkills.
GetSpellLearnSpellMapBounds()
SpellLearnSpellMapBounds SpellMgr::GetSpellLearnSpellMapBounds (uint32 spell_id) const inline
Definition at line 3226 of file SpellMgr.h.
References mSpellLearnSpells.
Referenced by IsSpellLearnToSpell(), and LoadSpellLearnSpells().
GetSpellProcEvent()
SpellProcEventEntry const* SpellMgr::GetSpellProcEvent (uint32 spellId) const inline
Definition at line 2982 of file SpellMgr.h.
References mSpellProcEventMap.
GetSpellRank()
uint8 SpellMgr::GetSpellRank (uint32 spell_id) const inline
Definition at line 3082 of file SpellMgr.h.
References GetSpellChainNode().
Referenced by GetProfessionSpellMinLevel(), IsPrimaryProfessionFirstRankSpell(), IsSpellHigherRankOfSpell(), and SelectAuraRankForLevel().
GetSpellTargetPosition()
SpellTargetPosition const* SpellMgr::GetSpellTargetPosition (uint32 spell_id) const inline
Definition at line 3014 of file SpellMgr.h.
References mSpellTargetPositions.
GetSpellThreatEntry()
SpellThreatEntry const* SpellMgr::GetSpellThreatEntry (uint32 spellid) const inline
Definition at line 2961 of file SpellMgr.h.
References mSpellThreatMap.
Referenced by GetSpellThreatMultiplier().
GetSpellThreatMultiplier()
float SpellMgr::GetSpellThreatMultiplier (SpellEntry const * spellInfo) const inline
Definition at line 2970 of file SpellMgr.h.
References GetSpellThreatEntry(), and SpellEntry::Id.
Instance()
SpellMgr & SpellMgr::Instance () static
Definition at line 53 of file SpellMgr.cpp.
IsPrimaryProfessionFirstRankSpell()
bool SpellMgr::IsPrimaryProfessionFirstRankSpell (uint32 spellId) const
Definition at line 1503 of file SpellMgr.cpp.
References GetSpellRank(), and IsPrimaryProfessionSpell().
IsPrimaryProfessionSpell()
bool SpellMgr::IsPrimaryProfessionSpell (uint32 spellId) static
Definition at line 1453 of file SpellMgr.cpp.
References SpellEntry::Effect, EFFECT_INDEX_1, SpellEntry::EffectMiscValue, IsPrimaryProfessionSkill(), SQLStorage::LookupEntry(), SPELL_EFFECT_SKILL, and sSpellTemplate.
Referenced by IsPrimaryProfessionFirstRankSpell().
IsProfessionOrRidingSpell()
bool SpellMgr::IsProfessionOrRidingSpell (uint32 spellId) static
Definition at line 1425 of file SpellMgr.cpp.
References SpellEntry::Effect, EFFECT_INDEX_1, SpellEntry::EffectMiscValue, IsProfessionOrRidingSkill(), SQLStorage::LookupEntry(), SPELL_EFFECT_SKILL, and sSpellTemplate.
IsProfessionSpell()
bool SpellMgr::IsProfessionSpell (uint32 spellId) static
Definition at line 1439 of file SpellMgr.cpp.
References SpellEntry::Effect, EFFECT_INDEX_1, SpellEntry::EffectMiscValue, IsProfessionSkill(), SQLStorage::LookupEntry(), SPELL_EFFECT_SKILL, and sSpellTemplate.
Referenced by Player::GetTrainerSpellState(), and ObjectMgr::LoadTrainers().
IsSingleTargetSpell()
bool SpellMgr::IsSingleTargetSpell (SpellEntry const * entry) const inline
Definition at line 3116 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, and SPELL_ATTR_EX5_LIMIT_N.
Referenced by IsSingleTargetSpells().
IsSingleTargetSpells()
bool SpellMgr::IsSingleTargetSpells (SpellEntry const * entry1, SpellEntry const * entry2) const inline
Definition at line 3130 of file SpellMgr.h.
References ClassFamilyMask::Empty(), SpellEntry::Id, SpellEntry::IsFitToFamily(), IsSingleTargetSpell(), IsSpellAnotherRankOfSpell(), SPELLFAMILY_GENERIC, SpellEntry::SpellFamilyFlags, and SpellEntry::SpellFamilyName.
IsSkillBonusSpell()
bool SpellMgr::IsSkillBonusSpell (uint32 spellId) const
Definition at line 1508 of file SpellMgr.cpp.
References ABILITY_LEARNED_ON_GET_PROFESSION_SKILL, GetSkillLineAbilityMapBoundsBySpellId(), SkillLineAbilityEntry::learnOnGetSkill, and SkillLineAbilityEntry::req_skill_value.
IsSpellAnotherRankOfSpell()
bool SpellMgr::IsSpellAnotherRankOfSpell (uint32 spellId1, uint32 spellId2) const inline
Definition at line 3111 of file SpellMgr.h.
References GetFirstSpellInChain().
Referenced by IsSingleTargetSpells(), and IsSpellStackableWithSpellForDifferentCasters().
IsSpellCanAffectSpell()
bool SpellMgr::IsSpellCanAffectSpell (SpellEntry const * spellInfo_1, SpellEntry const * spellInfo_2) const
Definition at line 1414 of file SpellMgr.cpp.
References SpellEntry::GetEffectSpellClassMask(), SpellEntry::IsFitToFamilyMask(), and MAX_EFFECT_INDEX.
IsSpellEffectHarmfulAtClient()
static bool SpellMgr::IsSpellEffectHarmfulAtClient (const SpellEntry & entry, SpellEffectIndex effIndex) inline static
Definition at line 2905 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, and IsSpellTargetHarmfulAtClient().
Referenced by GetSpellFactionAtClient().
IsSpellEffectHelpfulAtClient()
static bool SpellMgr::IsSpellEffectHelpfulAtClient (const SpellEntry & entry, SpellEffectIndex effIndex) inline static
Definition at line 2911 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, IsSpellTargetHelpfulAtClient(), SPELL_AURA_DUMMY, and TARGET_UNIT_CASTER.
Referenced by GetSpellFactionAtClient().
IsSpellHigherRankOfSpell()
bool SpellMgr::IsSpellHigherRankOfSpell (uint32 spellId1, uint32 spellId2) const inline
Definition at line 3090 of file SpellMgr.h.
References GetSpellRank(), and mSpellChains.
IsSpellLearnSpell()
bool SpellMgr::IsSpellLearnSpell (uint32 spell_id) const inline
Definition at line 3221 of file SpellMgr.h.
References mSpellLearnSpells.
IsSpellLearnToSpell()
bool SpellMgr::IsSpellLearnToSpell (uint32 parent, uint32 child) const inline
Definition at line 3231 of file SpellMgr.h.
References GetSpellLearnSpellMapBounds().
IsSpellProcEventCanTriggeredBy()
bool SpellMgr::IsSpellProcEventCanTriggeredBy (SpellProcEventEntry const * spellProcEvent, uint32 EventProcFlag, SpellEntry const * spellInfo, uint32 procFlags, uint32 procExtra) static
Definition at line 1158 of file SpellMgr.cpp.
References PROC_EX_CAST_END, PROC_EX_CRITICAL_HIT, PROC_EX_EX_TRIGGER_ALWAYS, PROC_EX_INTERNAL_HOT, PROC_EX_NONE, PROC_EX_NORMAL_HIT, PROC_EX_PERIODIC_POSITIVE, PROC_FLAG_DEAL_HARMFUL_ABILITY, PROC_FLAG_DEAL_HARMFUL_PERIODIC, PROC_FLAG_DEAL_HARMFUL_SPELL, PROC_FLAG_DEAL_HELPFUL_ABILITY, PROC_FLAG_DEAL_HELPFUL_SPELL, PROC_FLAG_DEATH, PROC_FLAG_HEARTBEAT, PROC_FLAG_KILL, PROC_FLAG_ON_TRAP_ACTIVATION, PROC_FLAG_TAKE_HARMFUL_ABILITY, PROC_FLAG_TAKE_HARMFUL_PERIODIC, PROC_FLAG_TAKE_HARMFUL_SPELL, PROC_FLAG_TAKE_HELPFUL_ABILITY, PROC_FLAG_TAKE_HELPFUL_SPELL, SpellProcEventEntry::procEx, SpellEntry::SchoolMask, SpellProcEventEntry::schoolMask, SPELL_SCHOOL_MASK_NORMAL, SpellEntry::SpellFamilyName, and SpellProcEventEntry::spellFamilyName.
Referenced by Unit::IsTriggeredAtSpellProcEvent().
IsSpellStackableWithSpell()
bool SpellMgr::IsSpellStackableWithSpell (const SpellEntry * entry1, const SpellEntry * entry2) const inline
Definition at line 3153 of file SpellMgr.h.
References SpellEntry::HasAttribute(), IsStackableSpell(), SPELL_ATTR_EX_AURA_UNIQUE, SPELL_ATTR_NO_AURA_CANCEL, and SPELL_ATTR_PASSIVE.
Referenced by IsSpellStackableWithSpellForDifferentCasters().
IsSpellStackableWithSpellForDifferentCasters()
bool SpellMgr::IsSpellStackableWithSpellForDifferentCasters (const SpellEntry * entry1, const SpellEntry * entry2) const inline
Definition at line 3172 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, IsSpellAnotherRankOfSpell(), IsSpellStackableWithSpell(), SPELL_ATTR_EX3_DOT_STACKING_RULE, and SPELL_ATTR_EX5_AURA_UNIQUE_PER_CASTER.
IsSpellTargetHarmfulAtClient()
static bool SpellMgr::IsSpellTargetHarmfulAtClient (uint32 target) inline static
Definition at line 2854 of file SpellMgr.h.
References TARGET_CORPSE_ENEMY_NEAR_CASTER, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_24, TARGET_ENUM_UNITS_ENEMY_IN_CONE_54, TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_UNIT_ENEMY, and TARGET_UNIT_ENEMY_NEAR_CASTER.
Referenced by IsSpellEffectHarmfulAtClient().
IsSpellTargetHelpfulAtClient()
static bool SpellMgr::IsSpellTargetHelpfulAtClient (uint32 target) inline static
Definition at line 2874 of file SpellMgr.h.
References TARGET_ENUM_UNITS_FRIEND_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_FRIEND_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_FRIEND_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_FRIEND_IN_CONE, TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_PLAYER_RAID_NYI, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_MASTER, TARGET_UNIT_CASTER_PET, TARGET_UNIT_FRIEND, TARGET_UNIT_FRIEND_CHAIN_HEAL, TARGET_UNIT_FRIEND_NEAR_CASTER, TARGET_UNIT_NEAR_CASTER, TARGET_UNIT_PARTY, TARGET_UNIT_RAID, TARGET_UNIT_RAID_AND_CLASS, and TARGET_UNIT_RAID_NEAR_CASTER.
Referenced by IsSpellEffectHelpfulAtClient().
IsSpellValid()
bool SpellMgr::IsSpellValid (SpellEntry const * spellInfo, Player * pl = nullptr, bool msg = true) static
Some checks for spells, to prevent adding deprecated/broken spells for trainers, spell book, etc.
Definition at line 2563 of file SpellMgr.cpp.
References SpellEntry::Effect, SpellEntry::EffectItemType, SpellEntry::EffectTriggerSpell, ObjectMgr::GetItemPrototype(), SpellEntry::Id, IsLootCraftingSpell(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, ChatHandler::PSendSysMessage(), SpellEntry::Reagent, sLog, SPELL_EFFECT_CREATE_ITEM, SPELL_EFFECT_CREATE_ITEM_2, SPELL_EFFECT_LEARN_SPELL, SPELL_EFFECT_NONE, and sSpellTemplate.
Referenced by Player::addSpell(), ChatHandler::HandleCastCommand(), ChatHandler::HandleCastDistCommand(), ChatHandler::HandleCastSelfCommand(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLearnAllGMCommand(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleLearnSkillRecipesHelper(), ObjectMgr::LoadQuests(), and ObjectMgr::LoadTrainers().
LoadPetDefaultSpells()
void SpellMgr::LoadPetDefaultSpells ()
Definition at line 2484 of file SpellMgr.cpp.
References CREATURE_MAX_SPELLS, SpellEntry::Effect, SpellEntry::EffectMiscValue, CreatureInfo::Entry, SQLStorageBase::GetMaxEntry(), LoadPetDefaultSpells_helper(), SQLStorage::LookupEntry(), MANGOS_ASSERT, MAX_CREATURE_SPELL_DATA_SLOT, MAX_EFFECT_INDEX, mPetDefaultSpellsMap, CreatureInfo::PetSpellDataId, sCreatureSpellDataStore, sCreatureStorage, sLog, sObjectMgr, SPELL_EFFECT_SUMMON, SPELL_EFFECT_SUMMON_PET, CreatureSpellDataEntry::spellId, PetDefaultSpellsEntry::spellid, CreatureInfo::SpellList, and sSpellTemplate.
LoadPetDefaultSpells_helper()
bool SpellMgr::LoadPetDefaultSpells_helper (CreatureInfo const * cInfo, PetDefaultSpellsEntry & petDefSpells) private
Definition at line 2436 of file SpellMgr.cpp.
References CreatureInfo::Family, GetPetLevelupSpellList(), and PetDefaultSpellsEntry::spellid.
Referenced by LoadPetDefaultSpells().
LoadPetLevelupSpellMap()
void SpellMgr::LoadPetLevelupSpellMap ()
Definition at line 2395 of file SpellMgr.cpp.
References ABILITY_LEARNED_ON_GET_RACE_OR_CLASS_SKILL, CreatureFamilyEntry::ID, SpellEntry::Id, SkillLineAbilityEntry::learnOnGetSkill, SQLStorage::LookupEntry(), mPetLevelupSpellMap, sCreatureFamilyStore, SkillLineAbilityEntry::skillId, CreatureFamilyEntry::skillLine, sLog, SkillLineAbilityEntry::spellId, SpellEntry::spellLevel, sSkillLineAbilityStore, and sSpellTemplate.
LoadSkillLineAbilityMaps()
void SpellMgr::LoadSkillLineAbilityMaps ()
Definition at line 2993 of file SpellMgr.cpp.
References mSkillLineAbilityMapBySkillId, mSkillLineAbilityMapBySpellId, sLog, sSkillLineAbilityStore, and BarGoLink::step().
LoadSkillRaceClassInfoMap()
void SpellMgr::LoadSkillRaceClassInfoMap ()
Definition at line 3017 of file SpellMgr.cpp.
References mSkillRaceClassInfoMap, SkillRaceClassInfoEntry::skillId, sLog, sSkillLineStore, sSkillRaceClassInfoStore, and BarGoLink::step().
LoadSpellAreas()
void SpellMgr::LoadSpellAreas ()
Definition at line 2654 of file SpellMgr.cpp.
References SpellArea::areaId, SpellArea::auraSpell, SpellArea::autocast, SpellArea::conditionId, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, QueryResult::Fetch(), SpellArea::gender, GENDER_FEMALE, GENDER_MALE, GENDER_NONE, GetAreaEntryByAreaID(), Field::GetBool(), Field::GetInt32(), QueryResult::GetRowCount(), GetSpellAreaForAuraMapBounds(), GetSpellAreaMapBounds(), Field::GetUInt16(), Field::GetUInt32(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellAreaForAreaMap, mSpellAreaForAuraMap, mSpellAreaMap, QueryResult::NextRow(), Database::Query(), SpellArea::questEnd, SpellArea::questStart, SpellArea::questStartCanActive, SpellArea::raceMask, RACEMASK_ALL_PLAYABLE, sConditionStorage, sLog, sObjectMgr, SPELL_AURA_DUMMY, SPELL_AURA_GHOST, SPELL_AURA_PHASE, SpellArea::spellId, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
LoadSpellBonuses()
void SpellMgr::LoadSpellBonuses ()
Definition at line 1001 of file SpellMgr.cpp.
References SpellBonusEntry::ap_bonus, SpellBonusEntry::ap_dot_bonus, CalculateDefaultCoefficient(), SpellBonusEntry::direct_damage, doForHighRanks(), DOT, SpellBonusEntry::dot_damage, SpellEntry::Effect, SpellEntry::EffectApplyAuraName, QueryResult::Fetch(), GetFirstSpellInChain(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellBonusMap, QueryResult::NextRow(), Database::Query(), SCALE_SPELLPOWER_HEALING, sLog, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_MANA, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_POWER_BURN_MANA, SPELL_AURA_SCHOOL_ABSORB, SPELL_DIRECT_DAMAGE, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
LoadSpellChains()
void SpellMgr::LoadSpellChains ()
Definition at line 1643 of file SpellMgr.cpp.
References QueryResult::Fetch(), SpellChainNode::first, QueryResult::GetRowCount(), GetTalentSpellPos(), Field::GetUInt32(), Field::GetUInt8(), LoadSpellChains_AbilityHelper(), SQLStorage::LookupEntry(), MANGOS_ASSERT, MAX_TALENT_RANK, mSkillLineAbilityMapBySpellId, mSpellChains, mSpellChainsNext, QueryResult::NextRow(), SpellChainNode::prev, Database::Query(), SpellChainNode::rank, TalentEntry::RankID, SpellChainNode::req, SKILL_INTERNAL, sLog, sSpellTemplate, sTalentStore, BarGoLink::step(), and WorldDatabase.
LoadSpellElixirs()
void SpellMgr::LoadSpellElixirs ()
Definition at line 1255 of file SpellMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), SQLStorage::LookupEntry(), mSpellElixirs, QueryResult::NextRow(), Database::Query(), sLog, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
LoadSpellLearnSkills()
void SpellMgr::LoadSpellLearnSkills ()
Definition at line 2012 of file SpellMgr.cpp.
References SpellEntry::CalculateSimpleValue(), SpellEntry::Effect, SpellLearnSkillNode::effect, SpellEntry::EffectMiscValue, SQLStorageBase::GetMaxEntry(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellLearnSkills, SpellLearnSkillNode::skill, sLog, SPELL_EFFECT_SKILL, sSpellTemplate, SpellLearnSkillNode::step, and BarGoLink::step().
LoadSpellLearnSpells()
void SpellMgr::LoadSpellLearnSpells ()
Definition at line 2050 of file SpellMgr.cpp.
References SpellLearnSpellNode::active, SpellLearnSpellNode::autoLearned, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, QueryResult::Fetch(), Field::GetBool(), SQLStorageBase::GetMaxEntry(), QueryResult::GetRowCount(), GetSpellLearnSpellMapBounds(), GetTalentSpellCost(), Field::GetUInt32(), IsPassiveSpell(), IsSpellHaveEffect(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellLearnSpells, QueryResult::NextRow(), Database::Query(), sLog, SpellLearnSpellNode::spell, SPELL_EFFECT_LEARN_SPELL, SPELL_EFFECT_SKILL_STEP, sSpellTemplate, BarGoLink::step(), TARGET_UNIT_CASTER_PET, and WorldDatabase.
LoadSpellPetAuras()
void SpellMgr::LoadSpellPetAuras ()
Definition at line 2316 of file SpellMgr.cpp.
References SpellEntry::CalculateSimpleValue(), SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellPetAuraMap, QueryResult::NextRow(), Database::Query(), sLog, SPELL_AURA_DUMMY, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_DUMMY, sSpellTemplate, BarGoLink::step(), TARGET_UNIT_CASTER_PET, and WorldDatabase.
LoadSpellProcEvents()
void SpellMgr::LoadSpellProcEvents ()
Definition at line 832 of file SpellMgr.cpp.
References SpellProcEventEntry::cooldown, SpellProcEventEntry::customChance, SpellRankHelper< EntryType, WorkerType, StorageType >::customRank, QueryResult::Fetch(), SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_EFFECT_INDEX, mSpellProcEventMap, QueryResult::NextRow(), SpellProcEventEntry::ppmRate, SpellProcEventEntry::procEx, SpellProcEventEntry::procFlags, Database::Query(), SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank(), SpellProcEventEntry::schoolMask, sLog, SpellProcEventEntry::spellFamilyMask, SpellProcEventEntry::spellFamilyName, BarGoLink::step(), SpellRankHelper< EntryType, WorkerType, StorageType >::worker, and WorldDatabase.
LoadSpellProcItemEnchant()
void SpellMgr::LoadSpellProcItemEnchant ()
Definition at line 896 of file SpellMgr.cpp.
References doForHighRanks(), QueryResult::Fetch(), GetFirstSpellInChain(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), mSpellProcItemEnchantMap, QueryResult::NextRow(), Database::Query(), sLog, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
LoadSpellScriptTarget()
void SpellMgr::LoadSpellScriptTarget ()
Definition at line 2161 of file SpellMgr.cpp.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SQLMultiStorage::EraseEntry(), SQLMultiStorage::SQLMSIteratorBounds< T >::first, SQLMultiStorage::getBounds(), SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), SpellEntry::Id, SQLMultiStorage::Load(), LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), SQLHashStorage::LookupEntry(), MAX_EFFECT_INDEX, MAX_SPELL_TARGET_TYPE, sCreatureStorage, SQLMultiStorage::SQLMSIteratorBounds< T >::second, sGOStorage, sLog, sObjectMgr, SPELL_TARGET_TYPE_CREATURE_GUID, SPELL_TARGET_TYPE_GAMEOBJECT, SPELL_TARGET_TYPE_GAMEOBJECT_GUID, SPELL_TARGET_TYPE_STRING_ID, sScriptMgr, sSpellScriptTargetStorage, sSpellTemplate, TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_54, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_SCRIPT_IN_CONE_110, TARGET_ENUM_UNITS_SCRIPT_IN_CONE_60, TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, TARGET_LOCATION_SCRIPT_NEAR_CASTER, TARGET_UNIT_CASTER, and TARGET_UNIT_SCRIPT_NEAR_CASTER.
LoadSpellTargetPositions()
void SpellMgr::LoadSpellTargetPositions ()
Definition at line 572 of file SpellMgr.cpp.
References SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, mSpellTargetPositions, QueryResult::NextRow(), Database::Query(), sLog, sMapStore, sSpellTemplate, BarGoLink::step(), TARGET_LOCATION_DATABASE, SpellTargetPosition::target_mapId, SpellTargetPosition::target_Orientation, SpellTargetPosition::target_X, SpellTargetPosition::target_Y, SpellTargetPosition::target_Z, and WorldDatabase.
LoadSpellThreats()
void SpellMgr::LoadSpellThreats ()
Definition at line 1370 of file SpellMgr.cpp.
References SpellThreatEntry::ap_bonus, QueryResult::Fetch(), SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), mSpellThreatMap, SpellThreatEntry::multiplier, QueryResult::NextRow(), Database::Query(), SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank(), sLog, BarGoLink::step(), SpellThreatEntry::threat, SpellRankHelper< EntryType, WorkerType, StorageType >::worker, and WorldDatabase.
SelectAuraRankForLevel()
SpellEntry const * SpellMgr::SelectAuraRankForLevel (SpellEntry const * spellInfo, uint32 level) const
Definition at line 1525 of file SpellMgr.cpp.
References CONFIG_BOOL_AUTO_DOWNRANK, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, GetPrevSpellInChain(), GetSpellRank(), SpellEntry::Id, IsAreaEffectPositiveTarget(), IsExplicitPositiveTarget(), IsPassiveSpell(), IsPositiveEffect(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_EFFECT_APPLY_AURA, SpellEntry::spellLevel, sSpellTemplate, and sWorld.
Friends And Related Function Documentation
DoSpellBonuses
friend struct DoSpellBonuses friend
Definition at line 2741 of file SpellMgr.h.
DoSpellProcEvent
friend struct DoSpellProcEvent friend
Definition at line 2742 of file SpellMgr.h.
DoSpellProcItemEnchant
friend struct DoSpellProcItemEnchant friend
Definition at line 2743 of file SpellMgr.h.
Field Documentation
mPetDefaultSpellsMap
PetDefaultSpellsMap SpellMgr::mPetDefaultSpellsMap private
Definition at line 3350 of file SpellMgr.h.
Referenced by GetPetDefaultSpellsEntry(), and LoadPetDefaultSpells().
mPetLevelupSpellMap
PetLevelupSpellMap SpellMgr::mPetLevelupSpellMap private
Definition at line 3349 of file SpellMgr.h.
Referenced by GetPetLevelupSpellList(), and LoadPetLevelupSpellMap().
mSkillLineAbilityMapBySkillId
SkillLineAbilityMap SpellMgr::mSkillLineAbilityMapBySkillId private
Definition at line 3346 of file SpellMgr.h.
Referenced by GetSkillLineAbilityMapBoundsBySkillId(), and LoadSkillLineAbilityMaps().
mSkillLineAbilityMapBySpellId
SkillLineAbilityMap SpellMgr::mSkillLineAbilityMapBySpellId private
Definition at line 3345 of file SpellMgr.h.
Referenced by GetSkillLineAbilityMapBoundsBySpellId(), LoadSkillLineAbilityMaps(), and LoadSpellChains().
mSkillRaceClassInfoMap
SkillRaceClassInfoMap SpellMgr::mSkillRaceClassInfoMap private
Definition at line 3347 of file SpellMgr.h.
Referenced by GetSkillRaceClassInfoMapBounds(), and LoadSkillRaceClassInfoMap().
mSpellAreaForAreaMap
SpellAreaForAreaMap SpellMgr::mSpellAreaForAreaMap private
Definition at line 3353 of file SpellMgr.h.
Referenced by GetSpellAreaForAreaMapBounds(), and LoadSpellAreas().
mSpellAreaForAuraMap
SpellAreaForAuraMap SpellMgr::mSpellAreaForAuraMap private
Definition at line 3352 of file SpellMgr.h.
Referenced by GetSpellAreaForAuraMapBounds(), and LoadSpellAreas().
mSpellAreaMap
SpellAreaMap SpellMgr::mSpellAreaMap private
Definition at line 3351 of file SpellMgr.h.
Referenced by GetSpellAreaMapBounds(), and LoadSpellAreas().
mSpellBonusMap
SpellBonusMap SpellMgr::mSpellBonusMap private
Definition at line 3344 of file SpellMgr.h.
Referenced by GetSpellBonusData(), and LoadSpellBonuses().
mSpellChains
SpellChainMap SpellMgr::mSpellChains private
Definition at line 3335 of file SpellMgr.h.
Referenced by GetSpellChainNode(), IsSpellHigherRankOfSpell(), and LoadSpellChains().
mSpellChainsNext
SpellChainMapNext SpellMgr::mSpellChainsNext private
Definition at line 3336 of file SpellMgr.h.
Referenced by GetSpellChainNext(), and LoadSpellChains().
mSpellElixirs
SpellElixirMap SpellMgr::mSpellElixirs private
Definition at line 3340 of file SpellMgr.h.
Referenced by GetSpellElixirMap(), GetSpellElixirMask(), and LoadSpellElixirs().
mSpellLearnSkills
SpellLearnSkillMap SpellMgr::mSpellLearnSkills private
Definition at line 3337 of file SpellMgr.h.
Referenced by GetSpellLearnSkill(), and LoadSpellLearnSkills().
mSpellLearnSpells
SpellLearnSpellMap SpellMgr::mSpellLearnSpells private
Definition at line 3338 of file SpellMgr.h.
Referenced by GetSpellLearnSpellMapBounds(), IsSpellLearnSpell(), and LoadSpellLearnSpells().
mSpellPetAuraMap
SpellPetAuraMap SpellMgr::mSpellPetAuraMap private
Definition at line 3348 of file SpellMgr.h.
Referenced by GetPetAura(), and LoadSpellPetAuras().
mSpellProcEventMap
SpellProcEventMap SpellMgr::mSpellProcEventMap private
Definition at line 3342 of file SpellMgr.h.
Referenced by GetSpellProcEvent(), and LoadSpellProcEvents().
mSpellProcItemEnchantMap
SpellProcItemEnchantMap SpellMgr::mSpellProcItemEnchantMap private
Definition at line 3343 of file SpellMgr.h.
Referenced by GetItemEnchantProcChance(), and LoadSpellProcItemEnchant().
mSpellTargetPositions
SpellTargetPositionMap SpellMgr::mSpellTargetPositions private
Definition at line 3339 of file SpellMgr.h.
Referenced by GetSpellTargetPosition(), and LoadSpellTargetPositions().
mSpellThreatMap
SpellThreatMap SpellMgr::mSpellThreatMap private
Definition at line 3341 of file SpellMgr.h.
Referenced by GetSpellThreatEntry(), and LoadSpellThreats().
The documentation for this class was generated from the following files:
SpellMgr.h
SpellMgr.cpp