CMaNGOS_WoTLK: CombatManager Class Reference
CombatManager Class Reference
#include <CombatManager.h>
Public Member Functions
CombatManager (Unit *owner)
void Update (const uint32 diff)
bool IsInEvadeMode () const
bool IsEvadingHome () const
bool IsEvadeRegen () const
void StartEvadeTimer ()
void StopEvade ()
EvadeState GetEvadeState () const
void SetEvadeState (EvadeState state)
void OnCombatStart ()
uint32 GetCombatTimer () const
void TriggerCombatTimer (Unit *target)
void TriggerCombatTimer (bool pvp)
void TriggerCombatTimer (uint32 timer)
void StopCombatTimer ()
bool IsLeashingDisabled ()
void SetLeashingDisable (bool apply)
void SetLeashingCheck (std::function< bool(Unit *, float x, float y, float z)> check)
Private Attributes
Unit * m_owner
uint32 m_evadeTimer
EvadeState m_evadeState
uint32 m_combatTick
uint32 m_combatTimer
Position m_lastRefreshPos
bool m_leashingDisabled
std::function< bool(Unit *, float x, float y, float z)> m_leashingCheck
Detailed Description
Definition at line 35 of file CombatManager.h.
Constructor & Destructor Documentation
CombatManager()
CombatManager::CombatManager (Unit * owner)
Definition at line 27 of file CombatManager.cpp.
Member Function Documentation
GetCombatTimer()
uint32 CombatManager::GetCombatTimer () const inline
Definition at line 53 of file CombatManager.h.
References m_combatTimer.
Referenced by ChatHandler::HandleCombatListCommand(), and ChatHandler::HandleNpcInfoCommand().
GetEvadeState()
EvadeState CombatManager::GetEvadeState () const inline
Definition at line 48 of file CombatManager.h.
References m_evadeState.
IsEvadeRegen()
bool CombatManager::IsEvadeRegen () const inline
Definition at line 45 of file CombatManager.h.
References m_evadeState, and m_evadeTimer.
IsEvadingHome()
bool CombatManager::IsEvadingHome () const inline
Definition at line 44 of file CombatManager.h.
References EVADE_HOME, and m_evadeState.
Referenced by PetAI::AttackStart(), boss_akilzonAI::boss_akilzonAI(), boss_kalecgos_humanoidAI::boss_kalecgos_humanoidAI(), boss_zuljinAI::boss_zuljinAI(), Unit::CanAttackOnSight(), Unit::CanEnterCombat(), UnitAI::DetectOrAttack(), boss_kelidan_the_breakerAI::DoSetupAdds(), priestess_commonAI::ExecuteActions(), WorldSession::HandlePetActionHelper(), instance_sunwell_plateau::Initialize(), npc_enslaved_soulAI::npc_enslaved_soulAI(), and PetAI::UpdateAI().
IsInEvadeMode()
bool CombatManager::IsInEvadeMode () const inline
Definition at line 43 of file CombatManager.h.
References m_evadeState, and m_evadeTimer.
Referenced by Unit::Attack(), CreatureEventAI::CheckEvent(), CreatureVisitCreatureWorker(), Unit::DealDamageMods(), Unit::DealMeleeDamage(), Unit::DealSpellDamage(), ChatHandler::HandleNpcInfoCommand(), mob_shadowmoon_channelerAI::HandleSetup(), boss_anubarak_trialAI::MoveInLineOfSight(), PlayerVisitCreatureWorker(), PlayerVisitPlayerWorker(), npc_xiri::ReceiveAIEvent(), Unit::RollMeleeOutcomeAgainst(), Unit::SpellHitResult(), UnitVisitObjectsNotifierWorker(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
IsLeashingDisabled()
bool CombatManager::IsLeashingDisabled () inline
Definition at line 58 of file CombatManager.h.
References m_leashingDisabled.
Referenced by ChatHandler::HandleNpcInfoCommand().
OnCombatStart()
void CombatManager::OnCombatStart ()
Definition at line 179 of file CombatManager.cpp.
References COMBAT_MANAGER_TICK, and m_combatTick.
Referenced by Unit::SetInCombatState().
SetEvadeState()
void CombatManager::SetEvadeState (EvadeState state)
Definition at line 161 of file CombatManager.cpp.
References Unit::AI(), Unit::CallForAllControlledUnits(), CONTROLLED_CHARM, CONTROLLED_GUARDIANS, CONTROLLED_PET, CONTROLLED_TOTEMS, EVADE_HOME, EVADE_NONE, Unit::HasCharmer(), m_evadeState, m_evadeTimer, m_owner, ORDER_EVADE, ORDER_NONE, and UnitAI::SetAIOrder().
Referenced by HomeMovementGenerator< Creature >::Finalize(), HomeMovementGenerator< Creature >::Initialize(), SetEvadeHelper::operator()(), StopEvade(), and Unit::Uncharm().
SetLeashingCheck()
void CombatManager::SetLeashingCheck (std::function< bool(Unit *, float x, float y, float z)> check) inline
Definition at line 60 of file CombatManager.h.
References m_leashingCheck.
Referenced by boss_akilzonAI::boss_akilzonAI(), boss_attumenAI::boss_attumenAI(), boss_baroness_anastariAI::boss_baroness_anastariAI(), boss_black_stalkerAI::boss_black_stalkerAI(), boss_broodlordAI::boss_broodlordAI(), boss_curatorAI::boss_curatorAI(), boss_fathomguard_caribdisAI::boss_fathomguard_caribdisAI(), boss_fathomguard_sharkkisAI::boss_fathomguard_sharkkisAI(), boss_fathomguard_tidalvessAI::boss_fathomguard_tidalvessAI(), boss_fathomlord_karathressAI::boss_fathomlord_karathressAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_felmystAI::boss_felmystAI(), boss_gurtogg_bloodboilAI::boss_gurtogg_bloodboilAI(), boss_halazziAI::boss_halazziAI(), boss_heiganAI::boss_heiganAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_illidari_councilAI::boss_illidari_councilAI(), boss_janalaiAI::boss_janalaiAI(), boss_kalecgosAI::boss_kalecgosAI(), boss_kelidan_the_breakerAI::boss_kelidan_the_breakerAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_leotheras_the_blindAI::boss_leotheras_the_blindAI(), boss_maiden_of_virtueAI::boss_maiden_of_virtueAI(), boss_malacrassAI::boss_malacrassAI(), boss_midnightAI::boss_midnightAI(), boss_moamAI::boss_moamAI(), boss_moroesAI::boss_moroesAI(), boss_morogrim_tidewalkerAI::boss_morogrim_tidewalkerAI(), boss_najentusAI::boss_najentusAI(), boss_nalorakkAI::boss_nalorakkAI(), boss_nethermancer_sepethreaAI::boss_nethermancer_sepethreaAI(), boss_netherspiteAI::boss_netherspiteAI(), boss_razorgoreAI::boss_razorgoreAI(), boss_razuviousAI::boss_razuviousAI(), boss_sacrolashAI::boss_sacrolashAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_selin_fireheartAI::boss_selin_fireheartAI(), boss_silithidRoyaltyAI::boss_silithidRoyaltyAI(), boss_sindragosaAI::boss_sindragosaAI(), boss_teron_gorefiendAI::boss_teron_gorefiendAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), boss_vazrudenAI::boss_vazrudenAI(), boss_vexallusAI::boss_vexallusAI(), boss_viscidusAI::boss_viscidusAI(), boss_void_reaverAI::boss_void_reaverAI(), boss_warchief_kargath_bladefistAI::boss_warchief_kargath_bladefistAI(), boss_warlord_kalithreshAI::boss_warlord_kalithreshAI(), boss_zuljinAI::boss_zuljinAI(), essence_base_AI::essence_base_AI(), mob_shadowmoon_channelerAI::mob_shadowmoon_channelerAI(), instance_sunwell_plateau::OnCreatureCreate(), and world_map_outland::OnCreatureRespawn().
SetLeashingDisable()
void CombatManager::SetLeashingDisable (bool apply) inline
Definition at line 59 of file CombatManager.h.
References ByteConverter::apply(), and m_leashingDisabled.
Referenced by mob_shadowmoon_soulstealerAI::Aggro(), boss_pathaleon_the_calculatorAI::boss_pathaleon_the_calculatorAI(), boss_terokkAI::boss_terokkAI(), mob_shadowmoon_soulstealerAI::EnterEvadeMode(), mob_shadowmoon_soulstealerAI::JustRespawned(), boss_broggokAI::JustSummoned(), npc_adyen_the_lightwardenAI::npc_adyen_the_lightwardenAI(), npc_doomguard_punisherAI::npc_doomguard_punisherAI(), npc_dreadmawAI::npc_dreadmawAI(), npc_eye_of_shartuulAI::npc_eye_of_shartuulAI(), npc_kaylaan_the_lostAI::npc_kaylaan_the_lostAI(), npc_laughing_skullAI::npc_laughing_skullAI(), npc_netherspite_portalAI::npc_netherspite_portalAI(), npc_reliquary_combat_triggerAI::npc_reliquary_combat_triggerAI(), npc_rethhedronAI::npc_rethhedronAI(), npc_shartuulAI::npc_shartuulAI(), npc_shivan_assassinAI::npc_shivan_assassinAI(), instance_black_temple::OnCreatureCreate(), world_map_outland::OnCreatureCreate(), instance_mechanar::OnCreatureCreate(), boss_magtheridonAI::Reset(), and npc_fel_cannon::SpellHit().
StartEvadeTimer()
void CombatManager::StartEvadeTimer () inline
Definition at line 46 of file CombatManager.h.
References m_evadeTimer.
Referenced by Unit::SelectHostileTarget().
StopCombatTimer()
void CombatManager::StopCombatTimer () inline
Definition at line 57 of file CombatManager.h.
References m_combatTimer.
Referenced by Unit::CombatStop(), PetAI::EnterEvadeMode(), Unit::TakeCharmOf(), and Unit::TakePossessOf().
StopEvade()
void CombatManager::StopEvade ()
Definition at line 144 of file CombatManager.cpp.
References EVADE_NONE, m_evadeTimer, and SetEvadeState().
Referenced by Unit::SelectHostileTarget(), and Unit::SetDeathState().
TriggerCombatTimer() [1/3]
void CombatManager::TriggerCombatTimer (bool pvp)
Definition at line 190 of file CombatManager.cpp.
References WorldObject::GetPosition(), Unit::GetPursuit(), m_combatTimer, m_lastRefreshPos, and m_owner.
TriggerCombatTimer() [2/3]
void CombatManager::TriggerCombatTimer (uint32 timer)
Definition at line 196 of file CombatManager.cpp.
References WorldObject::GetPosition(), m_combatTimer, m_lastRefreshPos, and m_owner.
TriggerCombatTimer() [3/3]
void CombatManager::TriggerCombatTimer (Unit * target)
Definition at line 184 of file CombatManager.cpp.
References Unit::CanHaveThreatList(), Unit::GetCombatManager(), Object::HasFlag(), m_owner, TriggerCombatTimer(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by Spell::cast(), Unit::CasterHitTargetWithSpell(), CreatureLinkingHolder::DoCreatureLinkingEvent(), Unit::EngageInCombatWith(), Unit::EngageInCombatWithAggressor(), Unit::HandleDamageDealt(), CreatureLinkingHolder::ProcessSlave(), Unit::SetInCombatState(), HostileRefManager::threatAssist(), TriggerCombatTimer(), and CreatureGroup::TriggerLinkingEvent().
Update()
void CombatManager::Update (const uint32 diff)
Definition at line 47 of file CombatManager.cpp.
References Unit::AI(), COMBAT_MANAGER_TICK, CONFIG_FLOAT_LEASH_RADIUS, ThreatManager::DeleteOutOfRangeReferences(), Unit::EvadeTimerExpired(), Creature::GetCombatStartPosition(), Creature::GetCreatureInfo(), WorldObject::GetDistance2d(), Unit::getHostileRefManager(), WorldObject::GetMap(), Unit::GetMaster(), WorldObject::GetPosition(), Position::GetPositionX(), Position::GetPositionY(), UnitAI::GetReactState(), LinkedListHead::getSize(), Unit::getThreatManager(), Unit::GetVictim(), Unit::HandleExitCombat(), Unit::HasCharmer(), Object::HasFlag(), Unit::HasMaster(), Unit::IsAlive(), Object::IsCreature(), Unit::IsCrowdControlled(), Map::IsDungeon(), Unit::IsImmobilizedState(), Unit::IsInCombat(), Object::IsPlayer(), Unit::IsPlayerControlled(), CreatureInfo::Leash, m_combatTick, m_combatTimer, m_evadeTimer, m_lastRefreshPos, m_leashingCheck, m_leashingDisabled, m_owner, REACT_PASSIVE, sWorld, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by Unit::Update().
Field Documentation
m_combatTick
uint32 CombatManager::m_combatTick private
Definition at line 67 of file CombatManager.h.
Referenced by OnCombatStart(), and Update().
m_combatTimer
uint32 CombatManager::m_combatTimer private
Definition at line 70 of file CombatManager.h.
Referenced by GetCombatTimer(), StopCombatTimer(), TriggerCombatTimer(), and Update().
m_evadeState
EvadeState CombatManager::m_evadeState private
Definition at line 66 of file CombatManager.h.
Referenced by GetEvadeState(), IsEvadeRegen(), IsEvadingHome(), IsInEvadeMode(), and SetEvadeState().
m_evadeTimer
uint32 CombatManager::m_evadeTimer private
Definition at line 65 of file CombatManager.h.
Referenced by IsEvadeRegen(), IsInEvadeMode(), SetEvadeState(), StartEvadeTimer(), StopEvade(), and Update().
m_lastRefreshPos
Position CombatManager::m_lastRefreshPos private
Definition at line 71 of file CombatManager.h.
Referenced by TriggerCombatTimer(), and Update().
m_leashingCheck
std::function<bool(Unit*, float x, float y, float z)> CombatManager::m_leashingCheck private
Definition at line 73 of file CombatManager.h.
Referenced by SetLeashingCheck(), and Update().
m_leashingDisabled
bool CombatManager::m_leashingDisabled private
Definition at line 72 of file CombatManager.h.
Referenced by IsLeashingDisabled(), SetLeashingDisable(), and Update().
m_owner
Unit* CombatManager::m_owner private
Definition at line 62 of file CombatManager.h.
Referenced by SetEvadeState(), TriggerCombatTimer(), and Update().
The documentation for this class was generated from the following files:
CombatManager.h
CombatManager.cpp