CMaNGOS_WoTLK: instance_scholomance Class Reference
instance_scholomance Class Reference
#include <scholomance.h>
Public Member Functions
instance_scholomance (Map *pMap)
~instance_scholomance ()
void Initialize () override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature)
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnPlayerEnter (Player *pPlayer) override
void HandlePortalEvent (uint32 uiEventId, uint32 uiData)
void HandleDawnGambitEvent ()
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void Update (const uint32 diff) override
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoSpawnGandlingIfCan (bool bByPlayerEnter)
void DoRespawnEntranceRoom (Player *pSummoner)
Private Attributes
uint32 m_uiGambitTransformTimer
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiGandlingEvent
GandlingEventMap m_mGandlingData
bool m_bIsRoomReset
GuidSet m_sEntranceRoomGuids
GuidSet m_sViewingRoomGuids
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 133 of file scholomance.h.
Constructor & Destructor Documentation
instance_scholomance()
instance_scholomance::instance_scholomance (Map * pMap)
Definition at line 28 of file instance_scholomance.cpp.
References Initialize().
~instance_scholomance()
instance_scholomance::~instance_scholomance () inline
Definition at line 137 of file scholomance.h.
Member Function Documentation
DoRespawnEntranceRoom()
void instance_scholomance::DoRespawnEntranceRoom (Player * pSummoner) private
Definition at line 105 of file instance_scholomance.cpp.
References aEntranceRoomSpawnLocs, debug_log(), Map::GetCreature(), Unit::GetMotionMaster(), GetRandomGenerator(), InstanceData::instance, m_bIsRoomReset, SpawnLocation::m_fO, SpawnLocation::m_fX, SpawnLocation::m_fY, SpawnLocation::m_fZ, m_sEntranceRoomGuids, MAX_GROUPS, MAX_NPC_PER_GROUP, MotionMaster::MoveWaypoint(), NPC_DISEASED_GHOUL, NPC_NECROFIEND, NPC_REANIMATED_CORPSE, NPC_RISEN_ABERRATION, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and urand().
Referenced by OnPlayerEnter(), and SetData().
DoSpawnGandlingIfCan()
void instance_scholomance::DoSpawnGandlingIfCan (bool bByPlayerEnter) private
Definition at line 232 of file instance_scholomance.cpp.
References aGandlingSpawnLocs, DONE, DoScriptText(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), HOLIDAY_FEAST_OF_WINTER_VEIL, IsHolidayActive(), m_auiEncounter, SpawnLocation::m_fO, SpawnLocation::m_fX, SpawnLocation::m_fY, SpawnLocation::m_fZ, NPC_DARKMASTER_GANDLING, SAY_GANDLING_SPAWN, SPELL_XMAS_GANDLING, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, TYPE_ALEXEI_BAROV, TYPE_GANDLING, TYPE_ILLUCIA_BAROV, TYPE_MALICIA, TYPE_POLKELT, TYPE_RAVENIAN, and TYPE_THEOLEN.
Referenced by OnPlayerEnter(), and SetData().
GetData()
uint32 instance_scholomance::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 293 of file instance_scholomance.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnCreatureCreate(), and OnPlayerEnter().
HandleDawnGambitEvent()
void instance_scholomance::HandleDawnGambitEvent ()
Definition at line 438 of file instance_scholomance.cpp.
References DoScriptText(), FACTION_SCOURGE, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, InstanceData::instance, m_sViewingRoomGuids, m_uiGambitTransformTimer, NPC_MARDUK_BLACKPOOL, NPC_VECTUS, SPELL_STUDENT_TRANSFORM, TEMPFACTION_RESTORE_RESPAWN, TRIGGERED_NONE, UNIT_STAND_STATE_STAND, and YELL_VECTUS_GAMBIT.
Referenced by Update().
HandlePortalEvent()
void instance_scholomance::HandlePortalEvent (uint32 uiEventId, uint32 uiData)
Definition at line 262 of file instance_scholomance.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), FAIL, IN_PROGRESS, m_mGandlingData, m_uiGandlingEvent, and SPECIAL.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), and OnCreatureEvade().
Initialize()
void instance_scholomance::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 36 of file instance_scholomance.cpp.
References aGandlingEvents, m_auiEncounter, and m_mGandlingData.
Referenced by instance_scholomance().
Load()
void instance_scholomance::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 301 of file instance_scholomance.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_scholomance::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 53 of file instance_scholomance.cpp.
References aEntranceRoom, DONE, GetData(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), BoxVolume::m_fCenterZ, BoxVolume::m_fCornerX, BoxVolume::m_fCornerY, m_mGandlingData, ScriptedInstance::m_npcEntryGuidStore, m_sEntranceRoomGuids, m_sViewingRoomGuids, m_uiGandlingEvent, BoxVolume::m_uiLength, BoxVolume::m_uiWidth, NPC_DARKMASTER_GANDLING, NPC_DISEASED_GHOUL, NPC_MARDUK_BLACKPOOL, NPC_REANIMATED_CORPSE, NPC_RISEN_ABERRATION, NPC_RISEN_GUARDIAN, NPC_SCHOLOMANCE_STUDENT, NPC_VECTUS, and TYPE_RATTLEGORE.
OnCreatureDeath()
void instance_scholomance::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 388 of file instance_scholomance.cpp.
References DONE, Object::GetEntry(), Object::GetGUIDLow(), HandlePortalEvent(), m_mGandlingData, NPC_ALEXEI_BAROV, NPC_DARKMASTER_GANDLING, NPC_ILLUCIA_BAROV, NPC_INSTRUCTOR_MALICIA, NPC_KIRTONOS, NPC_LOREKEEPER_POLKELT, NPC_RAS_FROSTWHISPER, NPC_RATTLEGORE, NPC_RAVENIAN, NPC_RISEN_GUARDIAN, NPC_THEOLEN_KRASTINOV, SetData(), TYPE_ALEXEI_BAROV, TYPE_GANDLING, TYPE_ILLUCIA_BAROV, TYPE_KIRTONOS, TYPE_MALICIA, TYPE_POLKELT, TYPE_RAS_FROSTWHISPER, TYPE_RATTLEGORE, TYPE_RAVENIAN, and TYPE_THEOLEN.
OnCreatureEnterCombat()
void instance_scholomance::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 322 of file instance_scholomance.cpp.
References Object::GetEntry(), Object::GetGUIDLow(), HandlePortalEvent(), IN_PROGRESS, m_mGandlingData, NPC_ALEXEI_BAROV, NPC_DARKMASTER_GANDLING, NPC_ILLUCIA_BAROV, NPC_INSTRUCTOR_MALICIA, NPC_KIRTONOS, NPC_LOREKEEPER_POLKELT, NPC_RAS_FROSTWHISPER, NPC_RATTLEGORE, NPC_RAVENIAN, NPC_RISEN_GUARDIAN, NPC_THEOLEN_KRASTINOV, SetData(), TYPE_ALEXEI_BAROV, TYPE_GANDLING, TYPE_ILLUCIA_BAROV, TYPE_KIRTONOS, TYPE_MALICIA, TYPE_POLKELT, TYPE_RAS_FROSTWHISPER, TYPE_RATTLEGORE, TYPE_RAVENIAN, and TYPE_THEOLEN.
OnCreatureEvade()
void instance_scholomance::OnCreatureEvade (Creature * pCreature) virtual
Reimplemented from InstanceData.
Definition at line 355 of file instance_scholomance.cpp.
References FAIL, Object::GetEntry(), Object::GetGUIDLow(), HandlePortalEvent(), m_mGandlingData, NPC_ALEXEI_BAROV, NPC_DARKMASTER_GANDLING, NPC_ILLUCIA_BAROV, NPC_INSTRUCTOR_MALICIA, NPC_KIRTONOS, NPC_LOREKEEPER_POLKELT, NPC_RAS_FROSTWHISPER, NPC_RATTLEGORE, NPC_RAVENIAN, NPC_RISEN_GUARDIAN, NPC_THEOLEN_KRASTINOV, SetData(), TYPE_ALEXEI_BAROV, TYPE_GANDLING, TYPE_ILLUCIA_BAROV, TYPE_KIRTONOS, TYPE_MALICIA, TYPE_POLKELT, TYPE_RAS_FROSTWHISPER, TYPE_RATTLEGORE, TYPE_RAVENIAN, and TYPE_THEOLEN.
OnObjectCreate()
void instance_scholomance::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 82 of file instance_scholomance.cpp.
References DONE, EVENT_ID_BAROV, EVENT_ID_ILLUCIA, EVENT_ID_MALICIA, EVENT_ID_POLKELT, EVENT_ID_RAVENIAN, EVENT_ID_THEOLEN, Object::GetEntry(), Object::GetObjectGuid(), GO_GATE_BAROV, GO_GATE_GANDLING, GO_GATE_ILLUCIA, GO_GATE_KIRTONOS, GO_GATE_MALICIA, GO_GATE_POLKELT, GO_GATE_RAS, GO_GATE_RAVENIAN, GO_GATE_THEOLEN, GO_STATE_ACTIVE, GO_VIEWING_ROOM_DOOR, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_mGandlingData, GameObject::SetGoState(), and TYPE_RATTLEGORE.
OnPlayerEnter()
void instance_scholomance::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 44 of file instance_scholomance.cpp.
References DONE, DoRespawnEntranceRoom(), DoSpawnGandlingIfCan(), GetData(), and TYPE_RATTLEGORE.
Save()
const char* instance_scholomance::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 157 of file scholomance.h.
References m_strInstData.
SetData()
void instance_scholomance::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 158 of file instance_scholomance.cpp.
References DONE, DoRespawnEntranceRoom(), DoSpawnGandlingIfCan(), ScriptedInstance::DoUseDoorOrButton(), EVENT_ID_BAROV, EVENT_ID_ILLUCIA, EVENT_ID_MALICIA, EVENT_ID_POLKELT, EVENT_ID_RAVENIAN, EVENT_ID_THEOLEN, FAIL, ScriptedInstance::GetPlayerInMap(), GO_GATE_GANDLING, GO_GATE_KIRTONOS, GO_GATE_RAS, IN_PROGRESS, m_auiEncounter, m_mGandlingData, m_strInstData, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_ALEXEI_BAROV, TYPE_GANDLING, TYPE_ILLUCIA_BAROV, TYPE_KIRTONOS, TYPE_MALICIA, TYPE_POLKELT, TYPE_RAS_FROSTWHISPER, TYPE_RATTLEGORE, TYPE_RAVENIAN, and TYPE_THEOLEN.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), and OnCreatureEvade().
Update()
void instance_scholomance::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 427 of file instance_scholomance.cpp.
References HandleDawnGambitEvent(), and m_uiGambitTransformTimer.
Field Documentation
m_auiEncounter
uint32 instance_scholomance::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 165 of file scholomance.h.
Referenced by DoSpawnGandlingIfCan(), GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_bIsRoomReset
bool instance_scholomance::m_bIsRoomReset private
Definition at line 171 of file scholomance.h.
Referenced by DoRespawnEntranceRoom().
m_mGandlingData
GandlingEventMap instance_scholomance::m_mGandlingData private
Definition at line 169 of file scholomance.h.
Referenced by HandlePortalEvent(), Initialize(), OnCreatureCreate(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), OnObjectCreate(), and SetData().
m_sEntranceRoomGuids
GuidSet instance_scholomance::m_sEntranceRoomGuids private
Definition at line 172 of file scholomance.h.
Referenced by DoRespawnEntranceRoom(), and OnCreatureCreate().
m_strInstData
std::string instance_scholomance::m_strInstData private
Definition at line 166 of file scholomance.h.
Referenced by Save(), and SetData().
m_sViewingRoomGuids
GuidSet instance_scholomance::m_sViewingRoomGuids private
Definition at line 173 of file scholomance.h.
Referenced by HandleDawnGambitEvent(), and OnCreatureCreate().
m_uiGambitTransformTimer
uint32 instance_scholomance::m_uiGambitTransformTimer private
Definition at line 164 of file scholomance.h.
Referenced by HandleDawnGambitEvent(), and Update().
m_uiGandlingEvent
uint32 instance_scholomance::m_uiGandlingEvent private
Definition at line 168 of file scholomance.h.
Referenced by HandlePortalEvent(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
scholomance.h
instance_scholomance.cpp