CMaNGOS_WoTLK: PlayerbotClassAI Class Reference
PlayerbotClassAI Class Reference
#include <PlayerbotClassAI.h>
Public Member Functions
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual CombatManeuverReturns DoFirstCombatManeuver (Unit *)
virtual CombatManeuverReturns DoNextCombatManeuver (Unit *)
virtual bool CanPull ()
virtual bool Pull ()
virtual uint32 Neutralize (uint8 creatureType)
virtual void DoNonCombatActions ()
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
Protected Member Functions
virtual CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *)
virtual CombatManeuverReturns DoNextCombatManeuverPVE (Unit *)
virtual CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *)
virtual CombatManeuverReturns DoNextCombatManeuverPVP (Unit *)
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
virtual CombatManeuverReturns DispelPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Protected Attributes
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 61 of file PlayerbotClassAI.h.
Constructor & Destructor Documentation
PlayerbotClassAI()
PlayerbotClassAI::PlayerbotClassAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 27 of file PlayerbotClassAI.cpp.
References ClearWait(), m_MinHealthPercentDPS, m_MinHealthPercentHealer, m_MinHealthPercentMaster, and m_MinHealthPercentTank.
~PlayerbotClassAI()
PlayerbotClassAI::~PlayerbotClassAI () virtual
Definition at line 38 of file PlayerbotClassAI.cpp.
Member Function Documentation
Buff()
CombatManeuverReturns PlayerbotClassAI::Buff (bool(*)(PlayerbotAI *, uint32, Unit *) BuffHelper, uint32 spellId, uint32 type = JOB_ALL, bool mustBeOOC = true) protected
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
params:BuffHelper boolean function that will be called back if buffing criteria are met params:spellId uint32 the spell ID of the spell buff params:type uint32, optional: default: JOB_ALL, the JOB_TYPE that target must have to be eligible for buffing Please note that job_type JOB_MANAONLY is a cumulative restriction. JOB_TANK | JOB_HEAL means both; JOB_TANK | JOB_MANAONLY means tanks with powertype MANA (paladins, druids) params: mustBeOOC boolean, optional: default: false, will return RETURN_NO_ACTION_OK if set to true and bot is in combat If false is returned, the bot is expected to perform a buff check for the single target version of the group buff.
Definition at line 133 of file PlayerbotClassAI.cpp.
References CLASS_DRUID, Unit::getClass(), Player::GetGroup(), Group::GetMemberSlots(), Unit::GetPowerType(), GetTargetJob(), Unit::IsAlive(), Unit::IsInCombat(), JOB_MANAONLY, m_ai, m_bot, m_master, POWER_MANA, RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, and sObjectMgr.
Referenced by PlayerbotDruidAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), and PlayerbotPriestAI::DoNonCombatActions().
CanPull()
virtual bool PlayerbotClassAI::CanPull () inline virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotPaladinAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 70 of file PlayerbotClassAI.h.
CastHoTOnTank()
bool PlayerbotClassAI::CastHoTOnTank ()
Definition at line 90 of file PlayerbotClassAI.cpp.
References DEBUG_LOG.
CastSpellNoRanged()
CombatManeuverReturns PlayerbotClassAI::CastSpellNoRanged (uint32 nextAction, Unit * pTarget) protected
Definition at line 717 of file PlayerbotClassAI.cpp.
References PlayerbotAI::CastSpell(), m_ai, RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, and SPELL_CAST_OK.
Referenced by PlayerbotDruidAI::CastSpell().
CastSpellWand()
CombatManeuverReturns PlayerbotClassAI::CastSpellWand (uint32 nextAction, Unit * pTarget, uint32 SHOOT) protected
Definition at line 728 of file PlayerbotClassAI.cpp.
References PlayerbotAI::CastSpell(), PlayerbotAI::COMBAT_RANGED, Unit::FindCurrentSpellBySpellId(), PlayerbotAI::GetCombatStyle(), Player::GetWeaponForAttack(), Unit::InterruptNonMeleeSpells(), m_ai, m_bot, RANGED_ATTACK, RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_UNKNOWN, and SPELL_CAST_OK.
Referenced by PlayerbotMageAI::CastSpell(), PlayerbotPriestAI::CastSpell(), and PlayerbotWarlockAI::CastSpell().
ClearWait()
void PlayerbotClassAI::ClearWait () inline
Definition at line 84 of file PlayerbotClassAI.h.
References m_WaitUntil.
Referenced by PlayerbotClassAI(), and PlayerbotAI::UpdateAI().
DispelPlayer()
CombatManeuverReturns PlayerbotClassAI::DispelPlayer (Player * target) protected virtual
Reimplemented in PlayerbotShamanAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotDruidAI, and PlayerbotMageAI.
Definition at line 112 of file PlayerbotClassAI.cpp.
References Unit::IsAlive(), RETURN_NO_ACTION_INVALIDTARGET, and RETURN_NO_ACTION_OK.
Referenced by PlayerbotMageAI::DispelPlayer(), PlayerbotDruidAI::DispelPlayer(), PlayerbotPaladinAI::DispelPlayer(), PlayerbotPriestAI::DispelPlayer(), and PlayerbotShamanAI::DispelPlayer().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotClassAI::DoFirstCombatManeuver (Unit *) virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 40 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotClassAI::DoFirstCombatManeuverPVE (Unit *) protected virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 43 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotClassAI::DoFirstCombatManeuverPVP (Unit *) protected virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 45 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotClassAI::DoNextCombatManeuver (Unit *) virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 41 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotClassAI::DoNextCombatManeuverPVE (Unit *) protected virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 44 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotClassAI::DoNextCombatManeuverPVP (Unit *) protected virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 46 of file PlayerbotClassAI.cpp.
References RETURN_NO_ACTION_OK.
DoNonCombatActions()
void PlayerbotClassAI::DoNonCombatActions () virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotWarlockAI, PlayerbotShamanAI, PlayerbotRogueAI, PlayerbotPriestAI, PlayerbotPaladinAI, PlayerbotMageAI, PlayerbotHunterAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 48 of file PlayerbotClassAI.cpp.
References DEBUG_LOG.
Referenced by PlayerbotAI::UpdateAI().
EatDrinkBandage()
bool PlayerbotClassAI::EatDrinkBandage (bool bMana = true, unsigned char foodPercent = 50, unsigned char drinkPercent = 50, unsigned char bandagePercent = 70)
Definition at line 53 of file PlayerbotClassAI.cpp.
References PlayerbotAI::FindBandage(), PlayerbotAI::FindDrink(), PlayerbotAI::FindFood(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetManaPercent(), Unit::HasAura(), m_ai, m_bot, RECENTLY_BANDAGED, PlayerbotAI::TellMaster(), and PlayerbotAI::UseItem().
Referenced by PlayerbotDeathKnightAI::DoNonCombatActions(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), and PlayerbotWarriorAI::DoNonCombatActions().
FindTargetAndHeal()
bool PlayerbotClassAI::FindTargetAndHeal () protected
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
Returns false else. Find a target based on healing orders (no orders = no healing), then try to heal it using own class HealPlayer() method
Definition at line 218 of file PlayerbotClassAI.cpp.
References PlayerbotAI::GetClassAI(), PlayerbotAI::GetCombatOrder(), GetHealTarget(), HealPlayer(), Unit::IsAlive(), PlayerbotAI::IsHealer(), PlayerbotAI::IsMainHealer(), JOB_ALL, JOB_ALL_NO_MT, JOB_MAIN_TANK, m_ai, m_bot, PlayerbotAI::ORDERS_NOT_MAIN_HEAL, and RETURN_CONTINUE.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverHeal(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), and PlayerbotShamanAI::DoNextCombatManeuverPVE().
FleeFromAoEIfCan()
bool PlayerbotClassAI::FleeFromAoEIfCan (uint32 spellId, Unit * pTarget) protected
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
params: spellId uint32 the spell ID of the hostile AoE the bot is supposed to move from. It is used to find the radius of the AoE spell params: pTarget Unit* the creature or gameobject the bot will use to define one of the prefered direction in which to flee
return true if bot has found a proper destination, false if none was found
Definition at line 399 of file PlayerbotClassAI.cpp.
References EFFECT_INDEX_0, SpellEntry::EffectRadiusIndex, FleeFromPointIfCan(), WorldObject::GetPosition(), GetSpellRadius(), SQLStorage::LookupEntry(), m_bot, sSpellRadiusStore, and sSpellTemplate.
FleeFromNpcWithAuraIfCan()
bool PlayerbotClassAI::FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit * pTarget) protected
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
params: goEntry uint32 the ID of the hostile trap the bot is supposed to move from. It is used to find the radius of the trap params: spellId uint32 the spell ID of the aura the creature is supposed to have (directly or from triggered spell). It is used to find the radius of the aura params: pTarget Unit* the creature or gameobject the bot will use to define one of the prefered direction in which to flee
return true if bot has found a proper destination, false if none was found
Definition at line 459 of file PlayerbotClassAI.cpp.
References EFFECT_INDEX_0, SpellEntry::EffectRadiusIndex, FleeFromPointIfCan(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellRadius(), SQLStorage::LookupEntry(), m_bot, M_PI_F, sSpellRadiusStore, sSpellTemplate, and Cell::VisitGridObjects().
FleeFromPointIfCan()
bool PlayerbotClassAI::FleeFromPointIfCan (uint32 radius, Unit * pTarget, float x0, float y0, float z0, float forcedAngle = 0.0f) protected
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
params: radius uint32 the minimal radius (distance) used by the bot to look for a destination from the provided position params: pTarget Unit* the creature or gameobject the bot will use to define one of the prefered direction in which to flee params: x0, y0, z0 float the coordinates of the origin point used to calculate the destination point params: forcedAngle float (optional) when iterating to find a proper point in world to move the bot to, this angle will be prioritly used over other angles if it is provided
return true if bot has found a proper destination, false if none was found
Definition at line 499 of file PlayerbotClassAI.cpp.
References frand(), WorldObject::GetAngle(), WorldObject::GetDistance(), Map::GetHeightInRange(), Map::GetHitPosition(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetPhaseMask(), PlayerbotAI::InterruptCurrentCastingSpell(), m_ai, m_bot, M_PI_F, MotionMaster::MovePoint(), and PlayerbotAI::SetIgnoreUpdateTime().
Referenced by FleeFromAoEIfCan(), FleeFromNpcWithAuraIfCan(), and FleeFromTrapGOIfCan().
FleeFromTrapGOIfCan()
bool PlayerbotClassAI::FleeFromTrapGOIfCan (uint32 goEntry, Unit * pTarget) protected
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
params: goEntry uint32 the ID of the hostile trap the bot is supposed to move from. It is used to find the radius of the trap params: pTarget Unit* the creature or gameobject the bot will use to define one of the prefered direction in which to flee
return true if bot has found a proper destination, false if none was found
Definition at line 424 of file PlayerbotClassAI.cpp.
References FleeFromPointIfCan(), GAMEOBJECT_TYPE_TRAP, WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SQLHashStorage::LookupEntry(), m_bot, sGOStorage, GameObjectInfo::trap, GameObjectInfo::type, and Cell::VisitGridObjects().
GetBotJob()
JOB_TYPE PlayerbotClassAI::GetBotJob (Player * target)
Definition at line 655 of file PlayerbotClassAI.cpp.
References JOB_DPS, JOB_HEAL, JOB_MAIN_HEAL, JOB_MAIN_TANK, and JOB_TANK.
Referenced by GetTargetJob().
GetDispelTarget()
Player * PlayerbotClassAI::GetDispelTarget (DispelType dispelType, JOB_TYPE type = JOB_ALL, bool bMustBeOOC = false) protected
GetDispelTarget() return Unit* Returns unit to be dispelled.
First checks Main Tank(s), next 'critical' Healer(s), next regular Tank(s) next Master (if different from:), next DPS.
return NULL If NULL is returned, no healing is required. At all.
Will need extensive re-write for co-operation amongst multiple healers. As it stands, multiple healers would all pick the same 'ideal' healing target.
Definition at line 576 of file PlayerbotClassAI.cpp.
References SpellEntry::Dispel, DISPEL_MAGIC, GetDispellMask(), Player::GetGroup(), Group::GetMemberSlots(), Unit::GetSpellAuraHolderMap(), SpellAuraHolder::GetSpellProto(), GetTargetJob(), Unit::IsAlive(), Unit::IsInCombat(), SpellAuraHolder::IsPositive(), m_bot, and sObjectMgr.
Referenced by PlayerbotDruidAI::DispelPlayer(), PlayerbotPaladinAI::DispelPlayer(), PlayerbotPriestAI::DispelPlayer(), PlayerbotShamanAI::DispelPlayer(), PlayerbotMageAI::DoNextCombatManeuverPVE(), and PlayerbotMageAI::DoNonCombatActions().
GetHealTarget()
Player * PlayerbotClassAI::GetHealTarget (JOB_TYPE type = JOB_ALL, bool onlyPickFromSameGroup = false) protected
GetHealTarget() return Unit* Returns unit to be healed.
First checks Main Tank(s), next 'critical' Healer(s), next regular Tank(s) next Master (if different from:), next DPS. If none of the healths are low enough (or multiple valid targets) against these checks, the lowest health is healed. Having a target returned does not guarantee it's worth healing, merely that the target does not have 100% health.
return NULL If NULL is returned, no healing is required. At all.
Will need extensive re-write for co-operation amongst multiple healers. As it stands, multiple healers would all pick the same 'ideal' healing target.
Definition at line 254 of file PlayerbotClassAI.cpp.
References Player::GetGroup(), Unit::GetHealth(), Unit::GetHealthPercent(), Unit::GetMaxHealth(), Group::GetMemberSlots(), GetTargetJob(), Unit::IsAlive(), JOB_HEAL, JOB_MAIN_HEAL, JOB_MAIN_TANK, JOB_MASTER, JOB_TANK, m_bot, m_master, m_MinHealthPercentDPS, m_MinHealthPercentHealer, m_MinHealthPercentMaster, m_MinHealthPercentTank, Group::SameSubGroup(), and sObjectMgr.
Referenced by PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVP(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), and FindTargetAndHeal().
GetResurrectionTarget()
Player * PlayerbotClassAI::GetResurrectionTarget (JOB_TYPE type = JOB_ALL, bool bMustBeOOC = true) protected
Definition at line 621 of file PlayerbotClassAI.cpp.
References Player::GetGroup(), Group::GetMemberSlots(), GetTargetJob(), Unit::IsAlive(), Unit::IsInCombat(), m_bot, m_master, and sObjectMgr.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverHeal(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), and PlayerbotShamanAI::DoNonCombatActions().
GetTargetJob()
JOB_TYPE PlayerbotClassAI::GetTargetJob (Player * target)
Definition at line 668 of file PlayerbotClassAI.cpp.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, DEATHKNIGHT_SPEC_FROST, DRUID_SPEC_FERAL, DRUID_SPEC_RESTORATION, GetBotJob(), Unit::getClass(), JOB_DPS, JOB_HEAL, JOB_MASTER, JOB_TANK, m_master, PALADIN_SPEC_HOLY, PALADIN_SPEC_PROTECTION, PRIEST_SPEC_HOLY, SHAMAN_SPEC_RESTORATION, and WARRIOR_SPEC_PROTECTION.
Referenced by Buff(), PlayerbotPaladinAI::CheckAuras(), GetDispelTarget(), GetHealTarget(), GetResurrectionTarget(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), and PlayerbotShamanAI::HealPlayer().
GetWaitUntil()
time_t PlayerbotClassAI::GetWaitUntil () inline
Definition at line 82 of file PlayerbotClassAI.h.
References m_WaitUntil.
HealPlayer()
CombatManeuverReturns PlayerbotClassAI::HealPlayer (Player * target) protected virtual
Reimplemented in PlayerbotShamanAI, PlayerbotPriestAI, PlayerbotPaladinAI, and PlayerbotDruidAI.
Definition at line 96 of file PlayerbotClassAI.cpp.
References Unit::IsAlive(), RETURN_NO_ACTION_INVALIDTARGET, and RETURN_NO_ACTION_OK.
Referenced by FindTargetAndHeal(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), and PlayerbotShamanAI::HealPlayer().
NeedGroupBuff()
bool PlayerbotClassAI::NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId) protected
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
params:groupBuffSpellId uint32 the spell ID of the group buff like Arcane Brillance params:singleBuffSpellId uint32 the spell ID of the single target buff equivalent of the group buff like Arcane Intellect for group buff Arcane Brillance If false is returned, the bot is expected to perform a buff check for the single target version of the group buff.
Definition at line 185 of file PlayerbotClassAI.cpp.
References EFFECT_INDEX_0, Player::GetGroup(), Group::GetMemberSlots(), Unit::GetPet(), Unit::HasAura(), Unit::HasAuraType(), Unit::IsAlive(), m_bot, sObjectMgr, and SPELL_AURA_MOD_UNATTACKABLE.
Referenced by PlayerbotDruidAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), and PlayerbotPriestAI::DoNonCombatActions().
Neutralize()
virtual uint32 PlayerbotClassAI::Neutralize (uint8 creatureType) inline virtual
Reimplemented in PlayerbotPriestAI, and PlayerbotDruidAI.
Definition at line 72 of file PlayerbotClassAI.h.
Pull()
virtual bool PlayerbotClassAI::Pull () inline virtual
Reimplemented in PlayerbotWarriorAI, PlayerbotPaladinAI, PlayerbotDruidAI, and PlayerbotDeathKnightAI.
Definition at line 71 of file PlayerbotClassAI.h.
ResurrectPlayer()
CombatManeuverReturns PlayerbotClassAI::ResurrectPlayer (Player * target) protected virtual
Reimplemented in PlayerbotShamanAI, PlayerbotPriestAI, PlayerbotPaladinAI, and PlayerbotDruidAI.
Definition at line 104 of file PlayerbotClassAI.cpp.
References Unit::IsAlive(), RETURN_NO_ACTION_INVALIDTARGET, and RETURN_NO_ACTION_OK.
Referenced by PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), and PlayerbotShamanAI::ResurrectPlayer().
SetWait()
void PlayerbotClassAI::SetWait (uint8 t) inline
Definition at line 83 of file PlayerbotClassAI.h.
References PlayerbotAI::CurrentTime(), m_ai, and m_WaitUntil.
Field Documentation
m_ai
PlayerbotAI& PlayerbotClassAI::m_ai protected
Definition at line 120 of file PlayerbotClassAI.h.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::_DoNextPVECombatManeuverHeal(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), Buff(), PlayerbotDruidAI::CastHoTOnTank(), PlayerbotPaladinAI::CastHoTOnTank(), PlayerbotPriestAI::CastHoTOnTank(), PlayerbotShamanAI::CastHoTOnTank(), CastSpellNoRanged(), CastSpellWand(), PlayerbotPaladinAI::CheckAuras(), PlayerbotWarlockAI::CheckDemon(), PlayerbotDruidAI::CheckForms(), PlayerbotPaladinAI::CheckSeals(), PlayerbotShamanAI::CheckShields(), PlayerbotWarriorAI::CheckShouts(), PlayerbotPaladinAI::DispelPlayer(), PlayerbotShamanAI::DispelPlayer(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVP(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), PlayerbotDeathKnightAI::DoNextCombatManeuver(), PlayerbotDruidAI::DoNextCombatManeuver(), PlayerbotHunterAI::DoNextCombatManeuver(), PlayerbotMageAI::DoNextCombatManeuver(), PlayerbotPaladinAI::DoNextCombatManeuver(), PlayerbotPriestAI::DoNextCombatManeuver(), PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotShamanAI::DoNextCombatManeuver(), PlayerbotWarlockAI::DoNextCombatManeuver(), PlayerbotWarriorAI::DoNextCombatManeuver(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotRogueAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVP(), PlayerbotDruidAI::DoNextCombatManeuverPVP(), PlayerbotHunterAI::DoNextCombatManeuverPVP(), PlayerbotMageAI::DoNextCombatManeuverPVP(), PlayerbotPaladinAI::DoNextCombatManeuverPVP(), PlayerbotPriestAI::DoNextCombatManeuverPVP(), PlayerbotShamanAI::DoNextCombatManeuverPVP(), PlayerbotWarlockAI::DoNextCombatManeuverPVP(), PlayerbotWarriorAI::DoNextCombatManeuverPVP(), PlayerbotDeathKnightAI::DoNonCombatActions(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), PlayerbotShamanAI::DropTotems(), EatDrinkBandage(), FindTargetAndHeal(), FleeFromPointIfCan(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), PlayerbotDruidAI::Neutralize(), PlayerbotPriestAI::Neutralize(), PlayerbotDeathKnightAI::PlayerbotDeathKnightAI(), PlayerbotDruidAI::PlayerbotDruidAI(), PlayerbotHunterAI::PlayerbotHunterAI(), PlayerbotMageAI::PlayerbotMageAI(), PlayerbotPaladinAI::PlayerbotPaladinAI(), PlayerbotPriestAI::PlayerbotPriestAI(), PlayerbotRogueAI::PlayerbotRogueAI(), PlayerbotShamanAI::PlayerbotShamanAI(), PlayerbotWarlockAI::PlayerbotWarlockAI(), PlayerbotWarriorAI::PlayerbotWarriorAI(), PlayerbotDeathKnightAI::Pull(), PlayerbotPaladinAI::Pull(), PlayerbotWarriorAI::Pull(), PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), PlayerbotShamanAI::ResurrectPlayer(), SetWait(), and PlayerbotShamanAI::UseCooldowns().
m_bot
Player& PlayerbotClassAI::m_bot protected
Definition at line 119 of file PlayerbotClassAI.h.
Referenced by PlayerbotDruidAI::_DoNextPVECombatManeuverBear(), PlayerbotDruidAI::_DoNextPVECombatManeuverCat(), PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS(), Buff(), PlayerbotDeathKnightAI::CanPull(), PlayerbotPaladinAI::CanPull(), PlayerbotWarriorAI::CanPull(), CastSpellWand(), PlayerbotPaladinAI::CheckAuras(), PlayerbotWarlockAI::CheckDemon(), PlayerbotDruidAI::CheckForms(), PlayerbotMageAI::CheckFrostCooldowns(), PlayerbotPaladinAI::CheckSeals(), PlayerbotShamanAI::CheckShields(), PlayerbotWarriorAI::CheckShouts(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuverPVE(), PlayerbotWarriorAI::DoFirstCombatManeuverPVE(), PlayerbotRogueAI::DoFirstCombatManeuverPVP(), PlayerbotWarriorAI::DoFirstCombatManeuverPVP(), PlayerbotRogueAI::DoNextCombatManeuver(), PlayerbotDeathKnightAI::DoNextCombatManeuverPVE(), PlayerbotDruidAI::DoNextCombatManeuverPVE(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotPaladinAI::DoNextCombatManeuverPVE(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVE(), PlayerbotWarlockAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), PlayerbotShamanAI::DoNextCombatManeuverPVP(), PlayerbotDeathKnightAI::DoNonCombatActions(), PlayerbotDruidAI::DoNonCombatActions(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotMageAI::DoNonCombatActions(), PlayerbotPaladinAI::DoNonCombatActions(), PlayerbotPriestAI::DoNonCombatActions(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), PlayerbotShamanAI::DropTotems(), EatDrinkBandage(), FindTargetAndHeal(), FleeFromAoEIfCan(), FleeFromNpcWithAuraIfCan(), FleeFromPointIfCan(), FleeFromTrapGOIfCan(), GetDispelTarget(), GetHealTarget(), GetResurrectionTarget(), PlayerbotDruidAI::HealPlayer(), PlayerbotPaladinAI::HealPlayer(), PlayerbotPriestAI::HealPlayer(), PlayerbotShamanAI::HealPlayer(), NeedGroupBuff(), PlayerbotWarriorAI::Pull(), PlayerbotDruidAI::ResurrectPlayer(), PlayerbotPaladinAI::ResurrectPlayer(), PlayerbotPriestAI::ResurrectPlayer(), PlayerbotShamanAI::ResurrectPlayer(), and PlayerbotShamanAI::UseCooldowns().
m_master
Player& PlayerbotClassAI::m_master protected
Definition at line 118 of file PlayerbotClassAI.h.
Referenced by Buff(), PlayerbotShamanAI::CheckShields(), PlayerbotPriestAI::DoNextCombatManeuverPVE(), PlayerbotDeathKnightAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotWarriorAI::DoNonCombatActions(), GetHealTarget(), GetResurrectionTarget(), GetTargetJob(), and PlayerbotShamanAI::UseCooldowns().
m_MinHealthPercentDPS
uint8 PlayerbotClassAI::m_MinHealthPercentDPS protected
Definition at line 113 of file PlayerbotClassAI.h.
Referenced by GetHealTarget(), and PlayerbotClassAI().
m_MinHealthPercentHealer
uint8 PlayerbotClassAI::m_MinHealthPercentHealer protected
Definition at line 112 of file PlayerbotClassAI.h.
Referenced by GetHealTarget(), and PlayerbotClassAI().
m_MinHealthPercentMaster
uint8 PlayerbotClassAI::m_MinHealthPercentMaster protected
Definition at line 114 of file PlayerbotClassAI.h.
Referenced by GetHealTarget(), and PlayerbotClassAI().
m_MinHealthPercentTank
uint8 PlayerbotClassAI::m_MinHealthPercentTank protected
Definition at line 111 of file PlayerbotClassAI.h.
Referenced by GetHealTarget(), and PlayerbotClassAI().
m_WaitUntil
time_t PlayerbotClassAI::m_WaitUntil protected
Definition at line 116 of file PlayerbotClassAI.h.
Referenced by ClearWait(), PlayerbotDeathKnightAI::DoFirstCombatManeuver(), PlayerbotDruidAI::DoFirstCombatManeuver(), PlayerbotHunterAI::DoFirstCombatManeuver(), PlayerbotMageAI::DoFirstCombatManeuver(), PlayerbotPaladinAI::DoFirstCombatManeuver(), PlayerbotPriestAI::DoFirstCombatManeuver(), PlayerbotRogueAI::DoFirstCombatManeuver(), PlayerbotShamanAI::DoFirstCombatManeuver(), PlayerbotWarlockAI::DoFirstCombatManeuver(), PlayerbotWarriorAI::DoFirstCombatManeuver(), GetWaitUntil(), and SetWait().
RECENTLY_BANDAGED
uint32 PlayerbotClassAI::RECENTLY_BANDAGED protected
Definition at line 123 of file PlayerbotClassAI.h.
Referenced by EatDrinkBandage(), PlayerbotDeathKnightAI::PlayerbotDeathKnightAI(), PlayerbotDruidAI::PlayerbotDruidAI(), PlayerbotHunterAI::PlayerbotHunterAI(), PlayerbotMageAI::PlayerbotMageAI(), PlayerbotPaladinAI::PlayerbotPaladinAI(), PlayerbotPriestAI::PlayerbotPriestAI(), PlayerbotRogueAI::PlayerbotRogueAI(), PlayerbotShamanAI::PlayerbotShamanAI(), PlayerbotWarlockAI::PlayerbotWarlockAI(), and PlayerbotWarriorAI::PlayerbotWarriorAI().
The documentation for this class was generated from the following files:
PlayerbotClassAI.h
PlayerbotClassAI.cpp