CMaNGOS_WoTLK: DatabaseMysql Class Reference
DatabaseMysql Class Reference
#include <DatabaseMysql.h>
Public Member Functions
DatabaseMysql ()
~DatabaseMysql ()
void ThreadStart () override
void ThreadEnd () override
Public Member Functions inherited from Database
virtual ~Database ()
virtual bool Initialize (const char *infoString, int nConns=1)
virtual void InitDelayThread ()
virtual void HaltDelayThread ()
QueryResult * Query (const char *sql)
Synchronous DB queries.
QueryNamedResult * QueryNamed (const char *sql)
QueryResult * PQuery (const char *format,...) ATTR_PRINTF(2
QueryResult QueryNamedResult * PQueryNamed (const char *format,...) ATTR_PRINTF(2
QueryResult QueryNamedResult bool DirectExecute (const char *sql) const
bool DirectPExecute (const char *format,...) ATTR_PRINTF(2
template<class Class >
bool bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *), const char *sql)
Async queries and query holders, implemented in DatabaseImpl.h.
template<class Class , typename ParamType1 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *sql)
template<class Class , typename ParamType1 , typename ParamType2 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *sql)
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *sql)
template<typename ParamType1 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *sql)
template<typename ParamType1 , typename ParamType2 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *sql)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *sql)
template<class Class >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *), const char *format,...) ATTR_PRINTF(4
template<class Class , typename ParamType1 >
bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...) ATTR_PRINTF(5
template<class Class , typename ParamType1 , typename ParamType2 >
bool bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...) ATTR_PRINTF(6
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool bool bool bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...) ATTR_PRINTF(7
template<typename ParamType1 >
bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...) ATTR_PRINTF(4
template<typename ParamType1 , typename ParamType2 >
bool bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...) ATTR_PRINTF(5
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool bool bool bool bool bool bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...) ATTR_PRINTF(6
template<class Class >
bool bool bool bool bool bool bool bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *), SqlQueryHolder *holder)
template<class Class , typename ParamType1 >
bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *, ParamType1), SqlQueryHolder *holder, ParamType1 param1)
bool Execute (const char *sql)
bool PExecute (const char *format,...) ATTR_PRINTF(2
bool bool PExecuteLog (const char *format,...) ATTR_PRINTF(2
bool bool bool BeginTransaction ()
bool CommitTransaction ()
bool RollbackTransaction ()
bool CommitTransactionDirect ()
SqlStatement CreateStatement (SqlStatementID &index, const char *fmt)
std::string GetStmtString (const int stmtId) const
operator bool () const
void escape_string (std::string &str)
void ProcessResultQueue ()
bool CheckRequiredField (char const *table_name, char const *required_name)
uint32 GetPingIntervall () const
void Ping ()
void AllowAsyncTransactions ()
template<class Class >
bool AsyncQuery (Class *object, void(Class::*method)(QueryResult *), const char *sql)
template<class Class , typename ParamType1 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...)
template<class Class , typename ParamType1 , typename ParamType2 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...)
template<class Class , typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncPQuery (Class *object, void(Class::*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...)
template<typename ParamType1 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1), ParamType1 param1, const char *format,...)
template<typename ParamType1 , typename ParamType2 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2), ParamType1 param1, ParamType2 param2, const char *format,...)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool AsyncPQuery (void(*method)(QueryResult *, ParamType1, ParamType2, ParamType3), ParamType1 param1, ParamType2 param2, ParamType3 param3, const char *format,...)
template<class Class >
bool DelayQueryHolder (Class *object, void(Class::*method)(QueryResult *, SqlQueryHolder *), SqlQueryHolder *holder)
Protected Member Functions
virtual SqlConnection * CreateConnection () override
Protected Member Functions inherited from Database
Database ()
void StopServer ()
virtual SqlDelayThread * CreateDelayThread ()
SqlConnection * getQueryConnection ()
SqlConnection * getAsyncConnection () const
bool ExecuteStmt (const SqlStatementID &id, SqlStmtParameters *params)
bool DirectExecuteStmt (const SqlStatementID &id, SqlStmtParameters *params)
Static Private Attributes
static size_t db_count = 0
Friends
class MaNGOS::OperatorNew< DatabaseMysql >
Additional Inherited Members
Protected Types inherited from Database
typedef std::vector< SqlConnection * > SqlConnectionContainer
typedef std::mutex LOCK_TYPE
typedef std::lock_guard< LOCK_TYPE > LOCK_GUARD
typedef std::unordered_map< std::string, int > PreparedStmtRegistry
Protected Attributes inherited from Database
boost::thread_specific_ptr< SqlTransaction > m_currentTransaction
DB connections.
int m_nQueryConnPoolSize
std::atomic_long m_nQueryCounter
SqlConnectionContainer m_pQueryConnections
SqlConnection * m_pAsyncConn
SqlResultQueue * m_pResultQueue
Transaction queues from diff. threads.
SqlDelayThread * m_threadBody
Pointer to delay sql executer (owned by m_delayThread)
MaNGOS::Thread * m_delayThread
Pointer to executer thread.
std::atomic< bool > m_allowAsyncTransactions
flag which specifies if async transactions are enabled
LOCK_TYPE m_stmtGuard
PreparedStmtRegistry m_stmtRegistry
int m_iStmtIndex
Detailed Description
Definition at line 92 of file DatabaseMysql.h.
Constructor & Destructor Documentation
DatabaseMysql()
DatabaseMysql::DatabaseMysql ()
Definition at line 40 of file DatabaseMysql.cpp.
References db_count, sLog, and Log::WaitBeforeContinueIfNeed().
~DatabaseMysql()
DatabaseMysql::~DatabaseMysql ()
Definition at line 57 of file DatabaseMysql.cpp.
References db_count, and Database::StopServer().
Member Function Documentation
CreateConnection()
SqlConnection * DatabaseMysql::CreateConnection () override protected virtual
Implements Database.
Definition at line 66 of file DatabaseMysql.cpp.
ThreadEnd()
void DatabaseMysql::ThreadEnd () override virtual
Reimplemented from Database.
Definition at line 35 of file DatabaseMysql.cpp.
Referenced by CliRunnable::run(), and WorldRunnable::run().
ThreadStart()
void DatabaseMysql::ThreadStart () override virtual
Reimplemented from Database.
Definition at line 30 of file DatabaseMysql.cpp.
Referenced by CliRunnable::run(), and WorldRunnable::run().
Friends And Related Function Documentation
MaNGOS::OperatorNew< DatabaseMysql >
friend class MaNGOS::OperatorNew< DatabaseMysql > friend
Definition at line 89 of file DatabaseMysql.h.
Field Documentation
db_count
size_t DatabaseMysql::db_count = 0 static private
Definition at line 109 of file DatabaseMysql.h.
Referenced by DatabaseMysql(), and ~DatabaseMysql().
The documentation for this class was generated from the following files:
DatabaseMysql.h
DatabaseMysql.cpp