CMaNGOS_WoTLK: AuctionHouseObject Class Reference
AuctionHouseObject Class Reference
#include <AuctionHouseMgr.h>
Public Types
typedef std::map< uint32, AuctionEntry * > AuctionEntryMap
typedef std::pair< AuctionEntryMap::const_iterator, AuctionEntryMap::const_iterator > AuctionEntryMapBounds
Public Member Functions
AuctionHouseObject ()
~AuctionHouseObject ()
uint32 GetCount () const
AuctionEntryMap const & GetAuctions () const
AuctionEntryMapBounds GetAuctionsBounds () const
void AddAuction (AuctionEntry *ah)
AuctionEntry * GetAuction (uint32 id) const
bool RemoveAuction (uint32 id)
void Update ()
void BuildListBidderItems (WorldPacket &data, Player *player, uint32 listfrom, uint32 &count, uint32 &totalcount)
void BuildListOwnerItems (WorldPacket &data, Player *player, uint32 listfrom, uint32 &count, uint32 &totalcount)
void BuildListPendingSales (WorldPacket &data, Player *player, uint32 &count)
AuctionEntry * AddAuction (AuctionHouseEntry const *auctionHouseEntry, Item *newItem, uint32 etime, uint32 bid, uint32 buyout=0, uint32 deposit=0, Player *pl=nullptr)
Private Attributes
AuctionEntryMap AuctionsMap
Detailed Description
Definition at line 91 of file AuctionHouseMgr.h.
Member Typedef Documentation
AuctionEntryMap
typedef std::map<uint32, AuctionEntry*> AuctionHouseObject::AuctionEntryMap
Definition at line 101 of file AuctionHouseMgr.h.
AuctionEntryMapBounds
typedef std::pair<AuctionEntryMap::const_iterator, AuctionEntryMap::const_iterator> AuctionHouseObject::AuctionEntryMapBounds
Definition at line 102 of file AuctionHouseMgr.h.
Constructor & Destructor Documentation
AuctionHouseObject()
AuctionHouseObject::AuctionHouseObject () inline
Definition at line 94 of file AuctionHouseMgr.h.
~AuctionHouseObject()
AuctionHouseObject::~AuctionHouseObject () inline
Definition at line 95 of file AuctionHouseMgr.h.
References AuctionsMap.
Member Function Documentation
AddAuction() [1/2]
void AuctionHouseObject::AddAuction (AuctionEntry * ah) inline
Definition at line 109 of file AuctionHouseMgr.h.
References AuctionsMap, AuctionEntry::Id, and MANGOS_ASSERT.
Referenced by AddAuction(), ChatHandler::HandleAuctionItemCommand(), WorldSession::HandleAuctionSellItem(), AuctionHouseMgr::LoadAuctions(), and AuctionHouseBot::Update().
AddAuction() [2/2]
AuctionEntry * AuctionHouseObject::AddAuction (AuctionHouseEntry const * auctionHouseEntry, Item * newItem, uint32 etime, uint32 bid, uint32 buyout = 0, uint32 deposit = 0, Player * pl = nullptr)
Definition at line 911 of file AuctionHouseMgr.cpp.
References AddAuction(), AuctionEntry::auctionHouseEntry, Database::BeginTransaction(), AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CharacterDatabase, Database::CommitTransaction(), CONFIG_FLOAT_RATE_AUCTION_TIME, AuctionEntry::deposit, AuctionEntry::expireTime, Item::GetCount(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUIDLow(), Item::GetItemRandomPropertyId(), WorldObject::GetName(), Object::GetObjectGuid(), AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemGuidLow, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, AuctionEntry::moneyDeliveryTime, AuctionEntry::owner, AuctionEntry::ownerName, sAuctionMgr, Player::SaveInventoryAndGoldToDB(), Item::SaveToDB(), AuctionEntry::SaveToDB(), sObjectMgr, AuctionEntry::startbid, sWorld, and Utf8toWStr().
BuildListBidderItems()
void AuctionHouseObject::BuildListBidderItems (WorldPacket & data, Player * player, uint32 listfrom, uint32 & count, uint32 & totalcount)
Definition at line 606 of file AuctionHouseMgr.cpp.
References AuctionsMap, AuctionEntry::bidder, AuctionEntry::BuildAuctionInfo(), Object::GetGUIDLow(), and AuctionEntry::moneyDeliveryTime.
Referenced by WorldSession::HandleAuctionListBidderItems().
BuildListOwnerItems()
void AuctionHouseObject::BuildListOwnerItems (WorldPacket & data, Player * player, uint32 listfrom, uint32 & count, uint32 & totalcount)
Definition at line 626 of file AuctionHouseMgr.cpp.
References AuctionsMap, AuctionEntry::BuildAuctionInfo(), Object::GetGUIDLow(), AuctionEntry::moneyDeliveryTime, and AuctionEntry::owner.
Referenced by WorldSession::HandleAuctionListOwnerItems().
BuildListPendingSales()
void AuctionHouseObject::BuildListPendingSales (WorldPacket & data, Player * player, uint32 & count)
Definition at line 883 of file AuctionHouseMgr.cpp.
References AUCTION_SUCCESSFUL, AuctionsMap, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, DAY, AuctionEntry::deposit, AuctionEntry::GetAuctionCut(), Object::GetGUIDLow(), AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, AuctionEntry::moneyDeliveryTime, and AuctionEntry::owner.
GetAuction()
AuctionEntry* AuctionHouseObject::GetAuction (uint32 id) const inline
Definition at line 115 of file AuctionHouseMgr.h.
References AuctionsMap.
Referenced by WorldSession::HandleAuctionListBidderItems(), WorldSession::HandleAuctionPlaceBid(), and WorldSession::HandleAuctionRemoveItem().
GetAuctions()
AuctionEntryMap const& AuctionHouseObject::GetAuctions () const inline
Definition at line 106 of file AuctionHouseMgr.h.
References AuctionsMap.
Referenced by WorldSession::HandleAuctionListItems().
GetAuctionsBounds()
AuctionEntryMapBounds AuctionHouseObject::GetAuctionsBounds () const inline
Definition at line 107 of file AuctionHouseMgr.h.
References AuctionsMap.
Referenced by AuctionHouseBot::Update().
GetCount()
uint32 AuctionHouseObject::GetCount () const inline
Definition at line 104 of file AuctionHouseMgr.h.
References AuctionsMap.
RemoveAuction()
bool AuctionHouseObject::RemoveAuction (uint32 id) inline
Definition at line 121 of file AuctionHouseMgr.h.
References AuctionsMap.
Referenced by WorldSession::HandleAuctionRemoveItem().
Update()
void AuctionHouseObject::Update ()
Handle expired auctions
perform the transaction if there was bidder
cancel the auction if there was no bidder and clear the auction
Definition at line 563 of file AuctionHouseMgr.cpp.
References AuctionsMap, MANGOS_ASSERT, sAuctionMgr, and sWorld.
Field Documentation
AuctionsMap
AuctionEntryMap AuctionHouseObject::AuctionsMap private
Definition at line 134 of file AuctionHouseMgr.h.
Referenced by AddAuction(), BuildListBidderItems(), BuildListOwnerItems(), BuildListPendingSales(), GetAuction(), GetAuctions(), GetAuctionsBounds(), GetCount(), RemoveAuction(), Update(), and ~AuctionHouseObject().
The documentation for this class was generated from the following files:
AuctionHouseMgr.h
AuctionHouseMgr.cpp