CMaNGOS_WoTLK: WaypointManager Class Reference
WaypointManager Class Reference
#include <WaypointManager.h>
Public Member Functions
WaypointManager ()
~WaypointManager ()
void Load ()
WaypointPath * GetDefaultPath (uint32 entry, uint32 lowGuid, WaypointPathOrigin *wpOrigin=nullptr)
WaypointPath * GetPathFromOrigin (uint32 entry, uint32 lowGuid, int32 pathId, WaypointPathOrigin wpOrigin)
void DeletePath (uint32 id)
void SetExternalWPTable (char const *tableName)
Set external source table.
std::string GetExternalWPTable () const
bool AddExternalNode (uint32 entry, int32 pathId, uint32 pointId, float x, float y, float z, float o, uint32 waittime, uint32 scriptId)
Add Nodes from external sources.
WaypointNode const * AddNode (uint32 entry, uint32 dbGuid, uint32 pathId, uint32 &pointId, WaypointPathOrigin wpDest, float x, float y, float z, float orientation)
Add a node as position pointId. If pointId == 0 then as last point.
void DeleteNode (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin)
void SetNodePosition (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, float x, float y, float z)
void SetNodeWaittime (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, uint32 waittime)
void SetNodeOrientation (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, float orientation)
bool SetNodeScriptId (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, uint32 scriptId)
return true if a valid scriptId is provided
Static Public Member Functions
static std::string GetOriginString (WaypointPathOrigin origin)
Private Types
typedef std::unordered_map< uint32, WaypointPath > WaypointPathMap
Private Member Functions
WaypointPath * GetPath (uint32 id)
WaypointPath * GetPathTemplate (uint32 entry)
WaypointPath * GetPathMovementTemplate (uint32 entry)
WaypointPathMap * getMapForPathType (WaypointPathOrigin origin)
Private Attributes
WaypointPathMap m_pathMap
WaypointPathMap m_pathTemplateMap
WaypointPathMap m_externalPathTemplateMap
WaypointPathMap m_pathMovementTemplateMap
std::string m_externalTable
Detailed Description
Definition at line 48 of file WaypointManager.h.
Member Typedef Documentation
WaypointPathMap
typedef std::unordered_map<uint32 , WaypointPath> WaypointManager::WaypointPathMap private
Definition at line 179 of file WaypointManager.h.
Constructor & Destructor Documentation
WaypointManager()
WaypointManager::WaypointManager () inline
Definition at line 51 of file WaypointManager.h.
~WaypointManager()
WaypointManager::~WaypointManager () inline
Definition at line 52 of file WaypointManager.h.
Member Function Documentation
AddExternalNode()
bool WaypointManager::AddExternalNode (uint32 entry, int32 pathId, uint32 pointId, float x, float y, float z, float o, uint32 waittime, uint32 scriptId)
Add Nodes from external sources.
Insert a node into the storage for external access.
Definition at line 512 of file WaypointManager.cpp.
References MaNGOS::IsValidMapCoord(), m_externalPathTemplateMap, and sLog.
AddNode()
WaypointNode const * WaypointManager::AddNode (uint32 entry, uint32 dbGuid, uint32 pathId, uint32 & pointId, WaypointPathOrigin wpDest, float x, float y, float z, float orientation)
Add a node as position pointId. If pointId == 0 then as last point.
Insert at a certain point, if pointId == 0 insert last. In this case pointId will be changed to the id to which the node was added
Definition at line 531 of file WaypointManager.cpp.
References getMapForPathType(), PATH_FROM_ENTRY, PATH_FROM_GUID, Database::PExecuteLog(), waypointKeyColumn, waypointOriginTables, and WorldDatabase.
DeleteNode()
void WaypointManager::DeleteNode (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin)
Definition at line 590 of file WaypointManager.cpp.
References GetPathFromOrigin(), PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, Database::PExecuteLog(), waypointKeyColumn, waypointOriginTables, and WorldDatabase.
DeletePath()
void WaypointManager::DeletePath (uint32 id)
Definition at line 617 of file WaypointManager.cpp.
References m_pathMap, Database::PExecuteLog(), and WorldDatabase.
GetDefaultPath()
WaypointPath* WaypointManager::GetDefaultPath (uint32 entry, uint32 lowGuid, WaypointPathOrigin * wpOrigin = nullptr) inline
Definition at line 67 of file WaypointManager.h.
References GetPath(), GetPathMovementTemplate(), GetPathTemplate(), PATH_FROM_ENTRY, PATH_FROM_GUID, and PATH_FROM_WAYPOINT_PATH.
GetExternalWPTable()
std::string WaypointManager::GetExternalWPTable () const inline
Definition at line 132 of file WaypointManager.h.
References m_externalTable.
getMapForPathType()
WaypointPathMap* WaypointManager::getMapForPathType (WaypointPathOrigin origin) inline private
Definition at line 181 of file WaypointManager.h.
References m_externalPathTemplateMap, m_pathMap, m_pathMovementTemplateMap, m_pathTemplateMap, PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, and PATH_NO_PATH.
Referenced by AddNode().
GetOriginString()
static std::string WaypointManager::GetOriginString (WaypointPathOrigin origin) inline static
Definition at line 148 of file WaypointManager.h.
References PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, and PATH_NO_PATH.
Referenced by WaypointMovementGenerator< Creature >::GetPathInformation(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), and ChatHandler::HandleWpShowCommand().
GetPath()
WaypointPath* WaypointManager::GetPath (uint32 id) inline private
Definition at line 161 of file WaypointManager.h.
References m_pathMap.
Referenced by GetDefaultPath().
GetPathFromOrigin()
WaypointPath* WaypointManager::GetPathFromOrigin (uint32 entry, uint32 lowGuid, int32 pathId, WaypointPathOrigin wpOrigin) inline
Definition at line 93 of file WaypointManager.h.
References m_externalPathTemplateMap, m_pathMap, m_pathMovementTemplateMap, m_pathTemplateMap, PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, and PATH_NO_PATH.
Referenced by DeleteNode(), SetNodeOrientation(), SetNodePosition(), SetNodeScriptId(), and SetNodeWaittime().
GetPathMovementTemplate()
WaypointPath* WaypointManager::GetPathMovementTemplate (uint32 entry) inline private
Definition at line 173 of file WaypointManager.h.
References m_pathMovementTemplateMap.
Referenced by GetDefaultPath().
GetPathTemplate()
WaypointPath* WaypointManager::GetPathTemplate (uint32 entry) inline private
Definition at line 167 of file WaypointManager.h.
References m_pathTemplateMap.
Referenced by GetDefaultPath().
Load()
void WaypointManager::Load ()
Definition at line 158 of file WaypointManager.cpp.
References CheckDbscript(), WaypointNode::delay, ERROR_DB_STRICT_LOG, QueryResult::Fetch(), ObjectMgr::GetCreatureTemplate(), Field::GetFloat(), Field::GetUInt32(), CreatureData::id, MaNGOS::IsValidMapCoord(), LINEAR_WP_MOTION_TYPE, m_pathMap, m_pathMovementTemplateMap, m_pathTemplateMap, CreatureInfo::MovementType, CreatureData::movementType, MaNGOS::NormalizeMapCoord(), WaypointNode::orientation, Database::PExecute(), Database::PQuery(), Database::Query(), WaypointNode::script_id, SCRIPT_TYPE_CREATURE_MOVEMENT, sLog, sObjectMgr, sScriptMgr, BarGoLink::step(), sTerrainMgr, WAYPOINT_MOTION_TYPE, WorldDatabase, WaypointNode::x, WaypointNode::y, and WaypointNode::z.
SetExternalWPTable()
void WaypointManager::SetExternalWPTable (char const * tableName) inline
Set external source table.
Definition at line 131 of file WaypointManager.h.
References m_externalTable.
SetNodeOrientation()
void WaypointManager::SetNodeOrientation (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, float orientation)
Definition at line 691 of file WaypointManager.cpp.
References GetPathFromOrigin(), PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, Database::PExecuteLog(), waypointKeyColumn, waypointOriginTables, and WorldDatabase.
SetNodePosition()
void WaypointManager::SetNodePosition (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, float x, float y, float z)
Definition at line 629 of file WaypointManager.cpp.
References GetPathFromOrigin(), PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, Database::PExecuteLog(), waypointKeyColumn, waypointOriginTables, and WorldDatabase.
SetNodeScriptId()
bool WaypointManager::SetNodeScriptId (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, uint32 scriptId)
return true if a valid scriptId is provided
Definition at line 721 of file WaypointManager.cpp.
References GetPathFromOrigin(), PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, Database::PExecuteLog(), SCRIPT_TYPE_CREATURE_MOVEMENT, sScriptMgr, waypointKeyColumn, waypointOriginTables, and WorldDatabase.
SetNodeWaittime()
void WaypointManager::SetNodeWaittime (uint32 entry, uint32 dbGuid, uint32 point, uint32 pathId, WaypointPathOrigin wpOrigin, uint32 waittime)
Definition at line 662 of file WaypointManager.cpp.
References GetPathFromOrigin(), PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_FROM_GUID, PATH_FROM_WAYPOINT_PATH, Database::PExecuteLog(), waypointKeyColumn, waypointOriginTables, and WorldDatabase.
Field Documentation
m_externalPathTemplateMap
WaypointPathMap WaypointManager::m_externalPathTemplateMap private
Definition at line 196 of file WaypointManager.h.
Referenced by AddExternalNode(), getMapForPathType(), and GetPathFromOrigin().
m_externalTable
std::string WaypointManager::m_externalTable private
Definition at line 199 of file WaypointManager.h.
Referenced by GetExternalWPTable(), and SetExternalWPTable().
m_pathMap
WaypointPathMap WaypointManager::m_pathMap private
Definition at line 194 of file WaypointManager.h.
Referenced by DeletePath(), getMapForPathType(), GetPath(), GetPathFromOrigin(), and Load().
m_pathMovementTemplateMap
WaypointPathMap WaypointManager::m_pathMovementTemplateMap private
Definition at line 197 of file WaypointManager.h.
Referenced by getMapForPathType(), GetPathFromOrigin(), GetPathMovementTemplate(), and Load().
m_pathTemplateMap
WaypointPathMap WaypointManager::m_pathTemplateMap private
Definition at line 195 of file WaypointManager.h.
Referenced by getMapForPathType(), GetPathFromOrigin(), GetPathTemplate(), and Load().
The documentation for this class was generated from the following files:
WaypointManager.h
WaypointManager.cpp