CMaNGOS_WoTLK: BigNumber Class Reference
BigNumber Class Reference
#include <BigNumber.h>
Public Member Functions
BigNumber ()
BigNumber (const BigNumber &bn)
BigNumber (uint32)
~BigNumber ()
void SetDword (uint32)
void SetQword (uint64)
void SetBinary (const uint8 *bytes, int len)
int SetHexStr (const char *str)
void SetRand (int numbits)
BigNumber & operator= (const BigNumber &bn)
BigNumber & operator+= (const BigNumber &bn)
BigNumber operator+ (const BigNumber &bn)
BigNumber & operator-= (const BigNumber &bn)
BigNumber operator- (const BigNumber &bn)
BigNumber & operator*= (const BigNumber &bn)
BigNumber operator* (const BigNumber &bn)
BigNumber & operator/= (const BigNumber &bn)
BigNumber operator/ (const BigNumber &bn)
BigNumber & operator%= (const BigNumber &bn)
BigNumber operator% (const BigNumber &bn)
bool isZero () const
BigNumber ModExp (const BigNumber &bn1, const BigNumber &bn2)
BigNumber Exp (const BigNumber &)
int GetNumBytes (void) const
struct bignum_st * BN ()
uint32 AsDword () const
std::vector< uint8 > AsByteArray (int minSize=0, bool reverse=true) const
const char * AsHexStr () const
const char * AsDecStr () const
Private Attributes
struct bignum_st * _bn
uint8 * _array
Detailed Description
Definition at line 27 of file BigNumber.h.
Constructor & Destructor Documentation
BigNumber() [1/3]
BigNumber::BigNumber ()
Definition at line 23 of file BigNumber.cpp.
References _array, and _bn.
BigNumber() [2/3]
BigNumber::BigNumber (const BigNumber & bn)
Definition at line 29 of file BigNumber.cpp.
References _array, and _bn.
BigNumber() [3/3]
BigNumber::BigNumber (uint32 val)
Definition at line 35 of file BigNumber.cpp.
References _array, and _bn.
~BigNumber()
BigNumber::~BigNumber ()
Definition at line 42 of file BigNumber.cpp.
References _array, and _bn.
Member Function Documentation
AsByteArray()
std::vector< uint8 > BigNumber::AsByteArray (int minSize = 0, bool reverse = true) const
Definition at line 160 of file BigNumber.cpp.
References _bn, and GetNumBytes().
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleReconnectChallenge(), SRP6::CalculateVerifier(), HMACSHA1::ComputeHash(), SRP6::HashSessionKey(), WorldSocket::Open(), SRP6::Proof(), HMACSHA1::UpdateBigNumber(), CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), and Warden::Warden().
AsDecStr()
const char * BigNumber::AsDecStr () const
Definition at line 186 of file BigNumber.cpp.
References _bn.
AsDword()
uint32 BigNumber::AsDword () const
Definition at line 150 of file BigNumber.cpp.
References _bn.
AsHexStr()
const char * BigNumber::AsHexStr () const
Definition at line 181 of file BigNumber.cpp.
References _bn.
Referenced by AuthSocket::_HandleLogonProof(), SRP6::CalculateVerifier(), AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), AccountMgr::CreateAccount(), WorldSocket::HandleAuthSession(), and SRP6::ProofVerifier().
BN()
struct bignum_st* BigNumber::BN () inline
Definition at line 82 of file BigNumber.h.
References _bn.
Exp()
BigNumber BigNumber::Exp (const BigNumber & bn)
Definition at line 123 of file BigNumber.cpp.
References _bn.
GetNumBytes()
int BigNumber::GetNumBytes (void) const
Definition at line 145 of file BigNumber.cpp.
References _bn.
Referenced by AuthSocket::_HandleReconnectProof(), AsByteArray(), SRP6::CalculateHostPublicEphemeral(), SRP6::CalculateVerifier(), HMACSHA1::ComputeHash(), and HMACSHA1::UpdateBigNumber().
isZero()
bool BigNumber::isZero () const
Definition at line 155 of file BigNumber.cpp.
References _bn.
Referenced by SRP6::CalculateSessionKey(), SRP6::CalculateVerifier(), SRP6::SetSalt(), and SRP6::SetVerifier().
ModExp()
BigNumber BigNumber::ModExp (const BigNumber & bn1, const BigNumber & bn2)
Definition at line 134 of file BigNumber.cpp.
References _bn.
Referenced by SRP6::CalculateHostPublicEphemeral(), SRP6::CalculateSessionKey(), and SRP6::CalculateVerifier().
operator%()
BigNumber BigNumber::operator% (const BigNumber & bn) inline
Definition at line 69 of file BigNumber.h.
operator%=()
BigNumber & BigNumber::operator%= (const BigNumber & bn)
Definition at line 114 of file BigNumber.cpp.
References _bn.
operator*()
BigNumber BigNumber::operator* (const BigNumber & bn) inline
Definition at line 57 of file BigNumber.h.
operator*=()
BigNumber & BigNumber::operator*= (const BigNumber & bn)
Definition at line 96 of file BigNumber.cpp.
References _bn.
operator+()
BigNumber BigNumber::operator+ (const BigNumber & bn) inline
Definition at line 45 of file BigNumber.h.
operator+=()
BigNumber & BigNumber::operator+= (const BigNumber & bn)
Definition at line 84 of file BigNumber.cpp.
References _bn.
operator-()
BigNumber BigNumber::operator- (const BigNumber & bn) inline
Definition at line 51 of file BigNumber.h.
operator-=()
BigNumber & BigNumber::operator-= (const BigNumber & bn)
Definition at line 90 of file BigNumber.cpp.
References _bn.
operator/()
BigNumber BigNumber::operator/ (const BigNumber & bn) inline
Definition at line 63 of file BigNumber.h.
operator/=()
BigNumber & BigNumber::operator/= (const BigNumber & bn)
Definition at line 105 of file BigNumber.cpp.
References _bn.
operator=()
BigNumber & BigNumber::operator= (const BigNumber & bn)
Definition at line 78 of file BigNumber.cpp.
References _bn.
SetBinary()
void BigNumber::SetBinary (const uint8 * bytes, int len)
Definition at line 60 of file BigNumber.cpp.
References _bn.
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), SRP6::CalculateSessionKey(), SRP6::CalculateVerifier(), and SRP6::HashSessionKey().
SetDword()
void BigNumber::SetDword (uint32 val)
Definition at line 48 of file BigNumber.cpp.
References _bn.
Referenced by WorldSocket::HandleAuthSession(), and SRP6::SRP6().
SetHexStr()
int BigNumber::SetHexStr (const char * str)
Definition at line 68 of file BigNumber.cpp.
References _bn.
Referenced by AuthSocket::_HandleLogonChallenge(), SRP6::CalculateVerifier(), WorldSocket::HandleAuthSession(), SRP6::SetSalt(), SRP6::SetStrongSessionKey(), SRP6::SetVerifier(), and SRP6::SRP6().
SetQword()
void BigNumber::SetQword (uint64 val)
Definition at line 53 of file BigNumber.cpp.
References _bn.
SetRand()
void BigNumber::SetRand (int numbits)
Definition at line 73 of file BigNumber.cpp.
References _bn.
Referenced by AuthSocket::_HandleReconnectChallenge(), SRP6::CalculateHostPublicEphemeral(), SRP6::CalculateVerifier(), and WorldSocket::Open().
Field Documentation
_array
uint8* BigNumber::_array private
Definition at line 92 of file BigNumber.h.
Referenced by BigNumber(), and ~BigNumber().
_bn
struct bignum_st* BigNumber::_bn private
Definition at line 91 of file BigNumber.h.
Referenced by AsByteArray(), AsDecStr(), AsDword(), AsHexStr(), BigNumber(), BN(), Exp(), GetNumBytes(), isZero(), ModExp(), operator%=(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), SetBinary(), SetDword(), SetHexStr(), SetQword(), SetRand(), and ~BigNumber().
The documentation for this class was generated from the following files:
BigNumber.h
BigNumber.cpp