CMaNGOS_WoTLK: GridInfo Class Reference
GridInfo Class Reference
NGrid is nothing more than a wrapper of the Grid with an NxN cells.
#include <NGrid.h>
Public Member Functions
GridInfo ()
GridInfo (time_t expiry, bool unload=true)
const TimeTracker & getTimeTracker () const
bool getUnloadLock () const
void setUnloadExplicitLock (bool on)
void incUnloadActiveLock ()
void decUnloadActiveLock ()
void setTimer (const TimeTracker &pTimer)
void ResetTimeTracker (time_t interval)
void UpdateTimeTracker (time_t diff)
Private Attributes
TimeTracker i_timer
uint16 i_unloadActiveLockCount: 16
bool i_unloadExplicitLock: 1
Detailed Description
NGrid is nothing more than a wrapper of the Grid with an NxN cells.
Definition at line 31 of file NGrid.h.
Constructor & Destructor Documentation
GridInfo() [1/2]
GridInfo::GridInfo () inline
Definition at line 35 of file NGrid.h.
GridInfo() [2/2]
GridInfo::GridInfo (time_t expiry, bool unload = true) inline
Definition at line 40 of file NGrid.h.
Member Function Documentation
decUnloadActiveLock()
void GridInfo::decUnloadActiveLock () inline
Definition at line 54 of file NGrid.h.
References i_unloadActiveLockCount.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::decUnloadActiveLock().
getTimeTracker()
const TimeTracker& GridInfo::getTimeTracker () const inline
Definition at line 45 of file NGrid.h.
References i_timer.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getTimeTracker(), ActiveState::Update(), and RemovalState::Update().
getUnloadLock()
bool GridInfo::getUnloadLock () const inline
Definition at line 47 of file NGrid.h.
References i_unloadActiveLockCount, and i_unloadExplicitLock.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getUnloadLock(), and RemovalState::Update().
incUnloadActiveLock()
void GridInfo::incUnloadActiveLock () inline
Definition at line 53 of file NGrid.h.
References i_unloadActiveLockCount.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::incUnloadActiveLock().
ResetTimeTracker()
void GridInfo::ResetTimeTracker (time_t interval) inline
Definition at line 57 of file NGrid.h.
References i_timer, and TimeTracker::Reset().
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ResetTimeTracker().
setTimer()
void GridInfo::setTimer (const TimeTracker & pTimer) inline
Definition at line 56 of file NGrid.h.
References i_timer.
setUnloadExplicitLock()
void GridInfo::setUnloadExplicitLock (bool on) inline
Definition at line 52 of file NGrid.h.
References i_unloadExplicitLock.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::setUnloadExplicitLock().
UpdateTimeTracker()
void GridInfo::UpdateTimeTracker (time_t diff) inline
Definition at line 58 of file NGrid.h.
References i_timer, and TimeTracker::Update().
Referenced by ActiveState::Update(), RemovalState::Update(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::UpdateTimeTracker().
Field Documentation
i_timer
TimeTracker GridInfo::i_timer private
Definition at line 62 of file NGrid.h.
Referenced by getTimeTracker(), ResetTimeTracker(), setTimer(), and UpdateTimeTracker().
i_unloadActiveLockCount
uint16 GridInfo::i_unloadActiveLockCount private
Definition at line 63 of file NGrid.h.
Referenced by decUnloadActiveLock(), getUnloadLock(), and incUnloadActiveLock().
i_unloadExplicitLock
bool GridInfo::i_unloadExplicitLock private
Definition at line 64 of file NGrid.h.
Referenced by getUnloadLock(), and setUnloadExplicitLock().
The documentation for this class was generated from the following file:
NGrid.h