CMaNGOS_WoTLK: MaNGOS::FriendlyEligibleDispelInRangeCheck Class Reference
MaNGOS::FriendlyEligibleDispelInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
FriendlyEligibleDispelInRangeCheck (Unit const *obj, float range, uint32 dispelMask, uint32 mechanicMask, bool self)
Unit const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 m_dispelMask
uint32 m_mechanicMask
bool m_self
Detailed Description
Definition at line 1044 of file GridNotifiers.h.
Constructor & Destructor Documentation
FriendlyEligibleDispelInRangeCheck()
MaNGOS::FriendlyEligibleDispelInRangeCheck::FriendlyEligibleDispelInRangeCheck (Unit const * obj, float range, uint32 dispelMask, uint32 mechanicMask, bool self) inline
Definition at line 1047 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
Unit const& MaNGOS::FriendlyEligibleDispelInRangeCheck::GetFocusObject () const inline
Definition at line 1049 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::FriendlyEligibleDispelInRangeCheck::operator() (Unit * u) inline
Definition at line 1050 of file GridNotifiers.h.
References Unit::CanAssist(), Unit::GetMaxNegativeAuraModifier(), Unit::HasMechanicMaskOrDispelMaskAura(), i_obj, i_range, Unit::IsAlive(), Unit::IsCrowdControlled(), Unit::isFrozen(), Unit::IsImmobilizedState(), Unit::IsInCombat(), WorldObject::IsWithinDistInMap(), m_dispelMask, m_mechanicMask, m_self, and SPELL_AURA_MOD_DECREASE_SPEED.
Field Documentation
i_obj
Unit const* MaNGOS::FriendlyEligibleDispelInRangeCheck::i_obj private
Definition at line 1067 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::FriendlyEligibleDispelInRangeCheck::i_range private
Definition at line 1068 of file GridNotifiers.h.
Referenced by operator()().
m_dispelMask
uint32 MaNGOS::FriendlyEligibleDispelInRangeCheck::m_dispelMask private
Definition at line 1069 of file GridNotifiers.h.
Referenced by operator()().
m_mechanicMask
uint32 MaNGOS::FriendlyEligibleDispelInRangeCheck::m_mechanicMask private
Definition at line 1070 of file GridNotifiers.h.
Referenced by operator()().
m_self
bool MaNGOS::FriendlyEligibleDispelInRangeCheck::m_self private
Definition at line 1071 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h