CMaNGOS_WoTLK: instance_ahnkahet Class Reference
instance_ahnkahet Class Reference
#include <ahnkahet.h>
Public Member Functions
instance_ahnkahet (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetData64 (uint32 uiType, uint64 uiGuid) override
ObjectGuid SelectRandomGuardianEggGuid ()
ObjectGuid SelectRandomSwarmerEggGuid ()
ObjectGuid SelectJedogaSacrificeControllerGuid () const
void GetJedogaControllersList (GuidList &lList) const
void GetJedogaEventControllersList (GuidList &lList) const
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void HandleInsanityClear ()
void HandleInsanitySwitch (Player *pPlayer)
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_bRespectElders
bool m_bVolunteerWork
uint8 m_uiDevicesActivated
uint8 m_uiInitiatesKilled
uint8 m_uiTwistedVisageCount
ObjectGuid m_jedogaSacrificeController
GuidList m_GuardianEggList
GuidList m_SwarmerEggList
GuidList m_lJedogaControllersGuidList
GuidList m_lJedogaEventControllersGuidList
GuidList m_lInsanityPlayersGuidList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 66 of file ahnkahet.h.
Constructor & Destructor Documentation
instance_ahnkahet()
instance_ahnkahet::instance_ahnkahet (Map * pMap)
Definition at line 29 of file ahnkahet.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_ahnkahet::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 375 of file ahnkahet.cpp.
References ACHIEV_CRIT_RESPECT_ELDERS, ACHIEV_CRIT_VOLUNTEER_WORK, m_bRespectElders, and m_bVolunteerWork.
GetData()
uint32 instance_ahnkahet::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 411 of file ahnkahet.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by boss_taldaramAI::boss_taldaramAI().
GetJedogaControllersList()
void instance_ahnkahet::GetJedogaControllersList (GuidList & lList) const inline
Definition at line 88 of file ahnkahet.h.
References m_lJedogaControllersGuidList.
Referenced by boss_taldaramAI::UpdateAI().
GetJedogaEventControllersList()
void instance_ahnkahet::GetJedogaEventControllersList (GuidList & lList) const inline
Definition at line 89 of file ahnkahet.h.
References m_lJedogaEventControllersGuidList.
Referenced by boss_jedogaAI::UpdateAI().
HandleInsanityClear()
void instance_ahnkahet::HandleInsanityClear () private
Definition at line 322 of file ahnkahet.cpp.
References Map::GetPlayer(), InstanceData::instance, m_lInsanityPlayersGuidList, and SPELL_AURA_PHASE.
Referenced by OnCreatureDeath(), and OnCreatureEvade().
HandleInsanitySwitch()
void instance_ahnkahet::HandleInsanitySwitch (Player * pPlayer) private
Definition at line 331 of file ahnkahet.cpp.
References Unit::GetAurasByType(), Map::GetPlayer(), InstanceData::instance, m_lInsanityPlayersGuidList, SPELL_AURA_PHASE, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by OnCreatureDeath().
Initialize()
void instance_ahnkahet::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 39 of file ahnkahet.cpp.
References m_auiEncounter.
Referenced by instance_ahnkahet().
Load()
void instance_ahnkahet::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 389 of file ahnkahet.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_ahnkahet::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 44 of file ahnkahet.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), m_GuardianEggList, m_jedogaSacrificeController, m_lJedogaControllersGuidList, m_lJedogaEventControllersGuidList, ScriptedInstance::m_npcEntryGuidStore, m_SwarmerEggList, m_uiTwistedVisageCount, NPC_AHNKAHAR_GUARDIAN_EGG, NPC_AHNKAHAR_SWARM_EGG, NPC_ELDER_NADOX, NPC_HERALD_VOLAZJ, NPC_JEDOGA_CONTROLLER, NPC_JEDOGA_SHADOWSEEKER, NPC_TALDARAM, NPC_TWISTED_VISAGE_1, NPC_TWISTED_VISAGE_2, NPC_TWISTED_VISAGE_3, NPC_TWISTED_VISAGE_4, and NPC_TWISTED_VISAGE_5.
OnCreatureDeath()
void instance_ahnkahet::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 195 of file ahnkahet.cpp.
References aJedogaLandingLoc, Unit::CastSpell(), Map::GetCreature(), Object::GetEntry(), Map::GetPlayer(), ScriptedInstance::GetSingleCreatureFromStorage(), WorldObject::GetSpawnerGuid(), HandleInsanityClear(), HandleInsanitySwitch(), IN_PROGRESS, InstanceData::instance, Creature::IsTemporarySummon(), m_lJedogaEventControllersGuidList, m_uiInitiatesKilled, m_uiTwistedVisageCount, MAX_INITIATES, NPC_HERALD_VOLAZJ, NPC_JEDOGA_SHADOWSEEKER, NPC_TWILIGHT_INITIATE, NPC_TWISTED_VISAGE_1, NPC_TWISTED_VISAGE_2, NPC_TWISTED_VISAGE_3, NPC_TWISTED_VISAGE_4, NPC_TWISTED_VISAGE_5, SetData(), SPELL_INSANITY_CLEAR, SPELL_INSANITY_SWITCH, SPELL_TWISTED_VISAGE_DEATH, TRIGGERED_OLD_TRIGGERED, and TYPE_VOLAZJ.
OnCreatureEvade()
void instance_ahnkahet::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 258 of file ahnkahet.cpp.
References Creature::ForcedDespawn(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), HandleInsanityClear(), IN_PROGRESS, m_uiTwistedVisageCount, NPC_HERALD_VOLAZJ, NPC_TWISTED_VISAGE_1, NPC_TWISTED_VISAGE_2, NPC_TWISTED_VISAGE_3, NPC_TWISTED_VISAGE_4, NPC_TWISTED_VISAGE_5, SetData(), SPELL_INSANITY_CLEAR, TRIGGERED_OLD_TRIGGERED, and TYPE_VOLAZJ.
OnObjectCreate()
void instance_ahnkahet::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 82 of file ahnkahet.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ANCIENT_DEVICE_L, GO_ANCIENT_DEVICE_R, GO_DOOR_TALDARAM, GO_FLAG_NO_INTERACT, GO_STATE_ACTIVE, GO_VORTEX, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), SPECIAL, TYPE_NADOX, and TYPE_TALDARAM.
Save()
const char* instance_ahnkahet::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 93 of file ahnkahet.h.
References m_strInstData.
SelectJedogaSacrificeControllerGuid()
ObjectGuid instance_ahnkahet::SelectJedogaSacrificeControllerGuid () const inline
Definition at line 86 of file ahnkahet.h.
References m_jedogaSacrificeController.
Referenced by boss_jedogaAI::MovementInform(), and boss_jedogaAI::SummonedCreatureJustDied().
SelectRandomGuardianEggGuid()
ObjectGuid instance_ahnkahet::SelectRandomGuardianEggGuid ()
Definition at line 300 of file ahnkahet.cpp.
References m_GuardianEggList, and urand().
Referenced by boss_nadoxAI::UpdateAI().
SelectRandomSwarmerEggGuid()
ObjectGuid instance_ahnkahet::SelectRandomSwarmerEggGuid ()
Definition at line 311 of file ahnkahet.cpp.
References m_SwarmerEggList, and urand().
Referenced by boss_nadoxAI::UpdateAI().
SetData()
void instance_ahnkahet::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 107 of file ahnkahet.cpp.
References ACHIEV_START_VOLAZJ_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, aTaldaramLandingLoc, debug_log(), DONE, ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_ANCIENT_DEVICE_L, GO_ANCIENT_DEVICE_R, GO_DOOR_TALDARAM, GO_FLAG_NO_INTERACT, GO_VORTEX, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bRespectElders, m_bVolunteerWork, m_lInsanityPlayersGuidList, m_lJedogaControllersGuidList, m_strInstData, m_uiDevicesActivated, m_uiTwistedVisageCount, NPC_TALDARAM, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), script_error_log(), SPECIAL, TYPE_AMANITAR, TYPE_JEDOGA, TYPE_NADOX, TYPE_TALDARAM, and TYPE_VOLAZJ.
Referenced by boss_jedogaAI::Aggro(), boss_nadoxAI::Aggro(), boss_taldaramAI::Aggro(), boss_jedogaAI::JustDied(), boss_nadoxAI::JustDied(), boss_taldaramAI::JustDied(), boss_jedogaAI::JustReachedHome(), boss_nadoxAI::JustReachedHome(), boss_taldaramAI::JustReachedHome(), OnCreatureDeath(), and OnCreatureEvade().
SetData64()
void instance_ahnkahet::SetData64 (uint32 uiType, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 290 of file ahnkahet.cpp.
References DATA_INSANITY_PLAYER, Map::GetPlayer(), InstanceData::instance, and m_lInsanityPlayersGuidList.
Field Documentation
m_auiEncounter
uint32 instance_ahnkahet::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 100 of file ahnkahet.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_bRespectElders
bool instance_ahnkahet::m_bRespectElders private
Definition at line 103 of file ahnkahet.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_bVolunteerWork
bool instance_ahnkahet::m_bVolunteerWork private
Definition at line 104 of file ahnkahet.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_GuardianEggList
GuidList instance_ahnkahet::m_GuardianEggList private
Definition at line 112 of file ahnkahet.h.
Referenced by OnCreatureCreate(), and SelectRandomGuardianEggGuid().
m_jedogaSacrificeController
ObjectGuid instance_ahnkahet::m_jedogaSacrificeController private
Definition at line 110 of file ahnkahet.h.
Referenced by OnCreatureCreate(), and SelectJedogaSacrificeControllerGuid().
m_lInsanityPlayersGuidList
GuidList instance_ahnkahet::m_lInsanityPlayersGuidList private
Definition at line 116 of file ahnkahet.h.
Referenced by HandleInsanityClear(), HandleInsanitySwitch(), SetData(), and SetData64().
m_lJedogaControllersGuidList
GuidList instance_ahnkahet::m_lJedogaControllersGuidList private
Definition at line 114 of file ahnkahet.h.
Referenced by GetJedogaControllersList(), OnCreatureCreate(), and SetData().
m_lJedogaEventControllersGuidList
GuidList instance_ahnkahet::m_lJedogaEventControllersGuidList private
Definition at line 115 of file ahnkahet.h.
Referenced by GetJedogaEventControllersList(), OnCreatureCreate(), and OnCreatureDeath().
m_strInstData
std::string instance_ahnkahet::m_strInstData private
Definition at line 101 of file ahnkahet.h.
Referenced by Save(), and SetData().
m_SwarmerEggList
GuidList instance_ahnkahet::m_SwarmerEggList private
Definition at line 113 of file ahnkahet.h.
Referenced by OnCreatureCreate(), and SelectRandomSwarmerEggGuid().
m_uiDevicesActivated
uint8 instance_ahnkahet::m_uiDevicesActivated private
Definition at line 106 of file ahnkahet.h.
Referenced by SetData().
m_uiInitiatesKilled
uint8 instance_ahnkahet::m_uiInitiatesKilled private
Definition at line 107 of file ahnkahet.h.
Referenced by OnCreatureDeath().
m_uiTwistedVisageCount
uint8 instance_ahnkahet::m_uiTwistedVisageCount private
Definition at line 108 of file ahnkahet.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), OnCreatureEvade(), and SetData().
The documentation for this class was generated from the following files:
ahnkahet.h
ahnkahet.cpp