CMaNGOS_WoTLK: Movement::MoveSplineInit Class Reference
Movement::MoveSplineInit Class Reference
#include <MoveSplineInit.h>
Public Member Functions
MoveSplineInit (Unit &m)
int32 Launch ()
void Stop (bool forceSend=false)
void SetParabolic (float amplitude, uint32 parabolicStartIdx)
void SetAnimation (AnimType anim)
void SetFacing (float angle)
void SetFacing (Vector3 const &spot)
void SetFacing (const WorldObject *target)
void MovebyPath (const PointsArray &controls, int32 path_offset=0)
void MoveTo (const Vector3 &dest, bool generatePath=false, bool forceDestination=false)
void MoveTo (float x, float y, float z, bool generatePath=false, bool forceDestination=false)
void SetFirstPointId (int32 pointId)
void SetSmooth ()
void SetFly ()
void SetWalk (bool enable)
void SetCyclic ()
void SetFall ()
void SetOrientationInversed ()
void SetOrientationFixed (bool enable)
void SetVelocity (float vel)
void SetBoardVehicle ()
void SetExitVehicle ()
PointsArray & Path ()
void SetCombatSlowed (float slowed)
bool CheckBounds () const
Protected Attributes
MoveSplineInitArgs args
Unit & unit
Detailed Description
Definition at line 42 of file MoveSplineInit.h.
Constructor & Destructor Documentation
MoveSplineInit()
Movement::MoveSplineInit::MoveSplineInit (Unit & m) explicit
Definition at line 217 of file MoveSplineInit.cpp.
References args, Movement::MoveSplineInitArgs::flags, Movement::MoveSplineFlag::flying, MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, MOVEFLAG_CAN_FLY, MOVEFLAG_FLYING, MOVEFLAG_HOVER, MOVEFLAG_LEVITATING, MOVEFLAG_WALK_MODE, unit, and Movement::MoveSplineFlag::walkmode.
Member Function Documentation
CheckBounds()
bool Movement::MoveSplineInit::CheckBounds () const inline
Definition at line 132 of file MoveSplineInit.h.
References Movement::MoveSplineInitArgs::_checkPathBounds(), and args.
Referenced by FixedPathMovementGenerator::Move(), and PathJumpGenerator::Move().
Launch()
int32 Movement::MoveSplineInit::Launch ()
Definition at line 31 of file MoveSplineInit.cpp.
References TempSpawnSettings::activeObject, MovementInfo::AddMovementFlag(), args, GenericTransport::CalculatePassengerOffset(), CMDEBUGFLAG_WP_PATH, Movement::MoveSpline::ComputePosition(), Movement::MoveSplineFlag::cyclic, TempSpawnSettings::despawnTime, Movement::MoveSpline::Duration(), Movement::MoveSplineFlag::enter_cycle, TempSpawnSettings::entry, Movement::MoveSpline::Finalized(), Movement::MoveSplineInitArgs::flags, Object::GetEntry(), TransportInfo::GetLocalPosition(), WorldObject::GetMap(), MovementInfo::GetMovementFlags(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetSpeed(), MovementInfo::GetSpeedType(), WorldObject::GetTransport(), TransportInfo::GetTransportGuid(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Movement::MoveSplineFlag::hasFlag(), WorldObject::HaveDebugFlag(), IN_MILLISECONDS, Movement::MoveSpline::Initialize(), Movement::MoveSplineInitArgs::initialOrientation, Unit::IsImmobilizedState(), WorldObject::m_movementInfo, MOVEFLAG_FLYING, MOVEFLAG_FORWARD, MOVEFLAG_ROOT, MOVEFLAG_SPLINE_ENABLED, MOVEFLAG_SWIMMING, MOVEFLAG_WALK_MODE, Unit::movespline, MoveTo(), TempSpawnSettings::ori, Movement::Location::orientation, Movement::MoveSplineInitArgs::path, WorldObject::SendMessageToAllWhoSeeMe(), MovementInfo::SetMovementFlags(), WorldPacket::SetOpcode(), sLog, Movement::MoveSplineInitArgs::slowed, SMSG_MONSTER_MOVE, SMSG_MONSTER_MOVE_TRANSPORT, TempSpawnSettings::spawnDataEntry, TempSpawnSettings::spawner, TempSpawnSettings::spawnType, Movement::splineCounter, Movement::MoveSplineInitArgs::splineId, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, TempSpawnSettings::tempSpawnMovegen, unit, Movement::MoveSplineInitArgs::Validate(), Movement::MoveSplineInitArgs::velocity, VISUAL_WAYPOINT, Movement::MoveSplineFlag::walkmode, TempSpawnSettings::waypointId, ObjectGuid::WriteAsPacked(), Movement::PacketBuilder::WriteMonsterMove(), TempSpawnSettings::x, TempSpawnSettings::y, and TempSpawnSettings::z.
Referenced by AbstractRandomMovementGenerator::_setLocation(), FormationMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), VehicleInfo::Board(), ChaseMovementGenerator::DispatchSplineToPosition(), FormationMovementGenerator::HandleMasterDistanceCheck(), ChatHandler::HandleMmapPathCommand(), AbstractWrapperMovementGenerator::Initialize(), Unit::MonsterMoveWithSpeed(), FollowMovementGenerator::Move(), TaxiMovementGenerator::Move(), PointMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), PointTOLMovementGenerator::Move(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Unit::SetFacingTo(), Unit::SetFacingToObject(), VehicleInfo::SwitchSeat(), VehicleInfo::UnBoard(), and AbstractWrapperMovementGenerator::Update().
MovebyPath()
void Movement::MoveSplineInit::MovebyPath (const PointsArray & controls, int32 path_offset = 0) inline
Definition at line 150 of file MoveSplineInit.h.
References args, Movement::MoveSplineInitArgs::path, and Movement::MoveSplineInitArgs::path_Idx_offset.
Referenced by AbstractRandomMovementGenerator::_setLocation(), FormationMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), ChaseMovementGenerator::DispatchSplineToPosition(), ChatHandler::HandleMmapPathCommand(), FollowMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), MoveTo(), and WaypointMovementGenerator< Creature >::SendNextWayPointPath().
MoveTo() [1/2]
void Movement::MoveSplineInit::MoveTo (const Vector3 & dest, bool generatePath = false, bool forceDestination = false) inline
Definition at line 162 of file MoveSplineInit.h.
References args, PathFinder::calculate(), PathFinder::getPath(), MovebyPath(), Movement::MoveSplineInitArgs::path, Movement::MoveSplineInitArgs::path_Idx_offset, and unit.
Referenced by VehicleInfo::Board(), FormationMovementGenerator::HandleMasterDistanceCheck(), Launch(), Unit::MonsterMoveWithSpeed(), PointMovementGenerator::Move(), PointTOLMovementGenerator::Move(), MotionMaster::MoveCharge(), MotionMaster::MoveFall(), MotionMaster::MoveJump(), MotionMaster::MoveJumpFacing(), MotionMaster::MoveKnockback(), MoveTo(), Stop(), VehicleInfo::SwitchSeat(), and VehicleInfo::UnBoard().
MoveTo() [2/2]
void Movement::MoveSplineInit::MoveTo (float x, float y, float z, bool generatePath = false, bool forceDestination = false) inline
Definition at line 156 of file MoveSplineInit.h.
References MoveTo().
Path()
PointsArray& Movement::MoveSplineInit::Path () inline
Definition at line 129 of file MoveSplineInit.h.
References args, and Movement::MoveSplineInitArgs::path.
Referenced by TaxiMovementGenerator::Move(), FixedPathMovementGenerator::Move(), and PathJumpGenerator::Move().
SetAnimation()
void Movement::MoveSplineInit::SetAnimation (AnimType anim) inline
Definition at line 185 of file MoveSplineInit.h.
References Movement::MoveSplineInitArgs::animation_start_Idx, args, Movement::MoveSplineFlag::EnableAnimation(), and Movement::MoveSplineInitArgs::flags.
Referenced by PointTOLMovementGenerator::Move().
SetBoardVehicle()
void Movement::MoveSplineInit::SetBoardVehicle () inline
Definition at line 147 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableBoardVehicle(), and Movement::MoveSplineInitArgs::flags.
Referenced by VehicleInfo::Board().
SetCombatSlowed()
void Movement::MoveSplineInit::SetCombatSlowed (float slowed) inline
Definition at line 131 of file MoveSplineInit.h.
References args, and Movement::MoveSplineInitArgs::slowed.
Referenced by AbstractRandomMovementGenerator::_setLocation(), and ChaseMovementGenerator::DispatchSplineToPosition().
SetCyclic()
void Movement::MoveSplineInit::SetCyclic () inline
Definition at line 142 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::cyclic, and Movement::MoveSplineInitArgs::flags.
Referenced by FixedPathMovementGenerator::Move().
SetExitVehicle()
void Movement::MoveSplineInit::SetExitVehicle () inline
Definition at line 148 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableExitVehicle(), and Movement::MoveSplineInitArgs::flags.
Referenced by VehicleInfo::UnBoard().
SetFacing() [1/3]
void Movement::MoveSplineInit::SetFacing (const WorldObject * target)
Definition at line 224 of file MoveSplineInit.cpp.
References args, Movement::MoveSplineFlag::EnableFacingTarget(), Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, Object::GetObjectGuid(), ObjectGuid::GetRawValue(), and Movement::FacingInfo::target.
SetFacing() [2/3]
void Movement::MoveSplineInit::SetFacing (float angle)
Definition at line 230 of file MoveSplineInit.cpp.
References Movement::FacingInfo::angle, args, Movement::MoveSplineFlag::EnableFacingAngle(), Movement::MoveSplineInitArgs::facing, and Movement::MoveSplineInitArgs::flags.
Referenced by FormationMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), VehicleInfo::Board(), ChaseMovementGenerator::DispatchSplineToPosition(), FormationMovementGenerator::HandleMasterDistanceCheck(), PointMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), PointTOLMovementGenerator::Move(), MotionMaster::MoveCharge(), MotionMaster::MoveJumpFacing(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), Unit::SetFacingTo(), Unit::SetFacingToObject(), and VehicleInfo::UnBoard().
SetFacing() [3/3]
void Movement::MoveSplineInit::SetFacing (Vector3 const & spot) inline
Definition at line 191 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableFacingPoint(), Movement::FacingInfo::f, Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, Movement::FacingInfo::x, Movement::FacingInfo::y, and Movement::FacingInfo::z.
SetFall()
void Movement::MoveSplineInit::SetFall () inline
Definition at line 143 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableFalling(), and Movement::MoveSplineInitArgs::flags.
Referenced by MotionMaster::MoveFall().
SetFirstPointId()
void Movement::MoveSplineInit::SetFirstPointId (int32 pointId) inline
Definition at line 89 of file MoveSplineInit.h.
References args, and Movement::MoveSplineInitArgs::path_Idx_offset.
Referenced by TaxiMovementGenerator::Move(), FixedPathMovementGenerator::Move(), and PathJumpGenerator::Move().
SetFly()
void Movement::MoveSplineInit::SetFly () inline
Definition at line 139 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableFlying(), and Movement::MoveSplineInitArgs::flags.
Referenced by TaxiMovementGenerator::Move(), PointMovementGenerator::Move(), FixedPathMovementGenerator::Move(), and PointTOLMovementGenerator::Move().
SetOrientationFixed()
void Movement::MoveSplineInit::SetOrientationFixed (bool enable) inline
Definition at line 146 of file MoveSplineInit.h.
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::orientationFixed.
Referenced by MotionMaster::MoveKnockback().
SetOrientationInversed()
void Movement::MoveSplineInit::SetOrientationInversed () inline
Definition at line 145 of file MoveSplineInit.h.
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::orientationInversed.
SetParabolic()
void Movement::MoveSplineInit::SetParabolic (float amplitude, uint32 parabolicStartIdx) inline
Definition at line 178 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableParabolic(), Movement::MoveSplineInitArgs::flags, Movement::MoveSplineInitArgs::parabolic_amplitude, and Movement::MoveSplineInitArgs::parabolic_start_Idx.
Referenced by PathJumpGenerator::Move(), MotionMaster::MoveJump(), MotionMaster::MoveJumpFacing(), and MotionMaster::MoveKnockback().
SetSmooth()
void Movement::MoveSplineInit::SetSmooth () inline
Definition at line 141 of file MoveSplineInit.h.
References args, Movement::MoveSplineFlag::EnableCatmullRom(), and Movement::MoveSplineInitArgs::flags.
SetVelocity()
void Movement::MoveSplineInit::SetVelocity (float vel) inline
Definition at line 144 of file MoveSplineInit.h.
References args, and Movement::MoveSplineInitArgs::velocity.
Referenced by FormationMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), Unit::MonsterMoveWithSpeed(), FollowMovementGenerator::Move(), TaxiMovementGenerator::Move(), PointMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), PointTOLMovementGenerator::Move(), MotionMaster::MoveCharge(), MotionMaster::MoveJump(), MotionMaster::MoveJumpFacing(), and MotionMaster::MoveKnockback().
SetWalk()
void Movement::MoveSplineInit::SetWalk (bool enable) inline
Definition at line 140 of file MoveSplineInit.h.
References args, Movement::MoveSplineInitArgs::flags, and Movement::MoveSplineFlag::walkmode.
Referenced by AbstractRandomMovementGenerator::_setLocation(), FormationMovementGenerator::_setLocation(), HomeMovementGenerator< Creature >::_setTargetLocation(), ChaseMovementGenerator::DispatchSplineToPosition(), FormationMovementGenerator::HandleMasterDistanceCheck(), ChatHandler::HandleMmapPathCommand(), FollowMovementGenerator::Move(), PointMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), PointTOLMovementGenerator::Move(), MotionMaster::MoveCharge(), and WaypointMovementGenerator< Creature >::SendNextWayPointPath().
Stop()
void Movement::MoveSplineInit::Stop (bool forceSend = false)
Definition at line 152 of file MoveSplineInit.cpp.
References args, GenericTransport::CalculatePassengerOffset(), Movement::MoveSpline::ComputePosition(), Movement::MoveSplineFlag::Done, Movement::MoveSpline::Finalized(), Movement::MoveSplineInitArgs::flags, Movement::MoveSpline::GetId(), TransportInfo::GetLocalPosition(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTransport(), TransportInfo::GetTransportGuid(), WorldObject::GetTransportInfo(), TransportInfo::GetTransportSeat(), Movement::MoveSpline::Initialize(), WorldObject::m_movementInfo, Movement::MonsterMoveStop, MOVEFLAG_FORWARD, MOVEFLAG_SPLINE_ENABLED, Unit::movespline, MoveTo(), Movement::Location::orientation, Movement::MoveSplineInitArgs::path, MovementInfo::RemoveMovementFlag(), WorldObject::SendMessageToAllWhoSeeMe(), WorldPacket::SetOpcode(), SMSG_MONSTER_MOVE, SMSG_MONSTER_MOVE_TRANSPORT, Movement::splineCounter, Movement::MoveSplineInitArgs::splineId, unit, and ObjectGuid::WriteAsPacked().
Referenced by WaypointMovementGenerator< Creature >::OnArrived(), Unit::StopMoving(), and WaypointMovementGenerator< Creature >::Update().
Field Documentation
args
MoveSplineInitArgs Movement::MoveSplineInit::args protected
Definition at line 135 of file MoveSplineInit.h.
Referenced by CheckBounds(), Launch(), MovebyPath(), MoveSplineInit(), MoveTo(), Path(), SetAnimation(), SetBoardVehicle(), SetCombatSlowed(), SetCyclic(), SetExitVehicle(), SetFacing(), SetFall(), SetFirstPointId(), SetFly(), SetOrientationFixed(), SetOrientationInversed(), SetParabolic(), SetSmooth(), SetVelocity(), SetWalk(), and Stop().
unit
Unit& Movement::MoveSplineInit::unit protected
Definition at line 136 of file MoveSplineInit.h.
Referenced by Launch(), MoveSplineInit(), MoveTo(), and Stop().
The documentation for this class was generated from the following files:
MoveSplineInit.h
MoveSplineInit.cpp