CMaNGOS_WoTLK: instance_eye_of_eternity Class Reference
instance_eye_of_eternity Class Reference
#include <eye_of_eternity.h>
Public Member Functions
instance_eye_of_eternity (Map *pMap)
~instance_eye_of_eternity ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual uint32 GetData (uint32) const
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Attributes
uint32 m_uiEncounter
uint32 m_uiMalygosResetTimer
uint32 m_uiMalygosCompleteTimer
GuidList m_lDiskRidersGuids
GuidList m_lSecondPhaseCreaturesGuids
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Detailed Description
Definition at line 39 of file eye_of_eternity.h.
Constructor & Destructor Documentation
instance_eye_of_eternity()
instance_eye_of_eternity::instance_eye_of_eternity (Map * pMap)
Definition at line 28 of file eye_of_eternity.cpp.
References Initialize().
~instance_eye_of_eternity()
instance_eye_of_eternity::~instance_eye_of_eternity () inline
Definition at line 43 of file eye_of_eternity.h.
Member Function Documentation
Initialize()
void instance_eye_of_eternity::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 35 of file eye_of_eternity.cpp.
References m_uiEncounter, and NOT_STARTED.
Referenced by instance_eye_of_eternity().
IsEncounterInProgress()
bool instance_eye_of_eternity::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 40 of file eye_of_eternity.cpp.
References IN_PROGRESS, and m_uiEncounter.
OnCreatureCreate()
void instance_eye_of_eternity::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file eye_of_eternity.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lDiskRidersGuids, m_lSecondPhaseCreaturesGuids, ScriptedInstance::m_npcEntryGuidStore, NPC_ALEXSTRASZA, NPC_ALEXSTRASZA_INVIS, NPC_ARCANE_OVERLOAD, NPC_HOVER_DISK_LORD, NPC_HOVER_DISK_SCION, NPC_LARGE_TRIGGER, NPC_MALYGOS, NPC_NEXUS_LORD, and NPC_SCION_OF_ETERNITY.
OnCreatureDeath()
void instance_eye_of_eternity::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 143 of file eye_of_eternity.cpp.
References AI_EVENT_CUSTOM_A, Creature::ForcedDespawn(), Map::GetCreature(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), InstanceData::instance, TransportInfo::IsOnVehicle(), m_lDiskRidersGuids, m_lSecondPhaseCreaturesGuids, NPC_MALYGOS, NPC_NEXUS_LORD, NPC_SCION_OF_ETERNITY, and SPELL_AURA_CONTROL_VEHICLE.
OnCreatureRespawn()
void instance_eye_of_eternity::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 84 of file eye_of_eternity.cpp.
References Creature::AI(), Object::GetEntry(), NPC_SURGE_OF_POWER, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_eye_of_eternity::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 67 of file eye_of_eternity.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_ALEXSTRASZAS_GIFT, GO_ALEXSTRASZAS_GIFT_H, GO_EXIT_PORTAL, GO_FOCUSING_IRIS, GO_FOCUSING_IRIS_H, GO_HEART_OF_MAGIC, GO_HEART_OF_MAGIC_H, GO_PLATFORM, and ScriptedInstance::m_goEntryGuidStore.
SetData()
void instance_eye_of_eternity::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 96 of file eye_of_eternity.cpp.
References ACHIEV_START_MALYGOS_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, Map::ChangeGOPathfinding(), DAY, DONE, ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::DoStartTimedAchievement(), FAIL, Map::GetDifficulty(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_EXIT_PORTAL, GO_FOCUSING_IRIS, GO_FOCUSING_IRIS_H, GO_HEART_OF_MAGIC, GO_HEART_OF_MAGIC_H, GO_PLATFORM, GO_STATE_READY, HOUR, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_uiEncounter, m_uiMalygosCompleteTimer, m_uiMalygosResetTimer, NPC_MALYGOS, RAID_DIFFICULTY_10MAN_NORMAL, and TYPE_MALYGOS.
Referenced by boss_malygosAI::Aggro(), boss_malygosAI::JustDied(), and boss_malygosAI::JustReachedHome().
Update()
void instance_eye_of_eternity::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 179 of file eye_of_eternity.cpp.
References ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_ALEXSTRASZAS_GIFT, GO_ALEXSTRASZAS_GIFT_H, GO_EXIT_PORTAL, HOUR, InstanceData::instance, Map::IsRegularDifficulty(), m_uiMalygosCompleteTimer, m_uiMalygosResetTimer, and NPC_MALYGOS.
Field Documentation
m_lDiskRidersGuids
GuidList instance_eye_of_eternity::m_lDiskRidersGuids protected
Definition at line 65 of file eye_of_eternity.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_lSecondPhaseCreaturesGuids
GuidList instance_eye_of_eternity::m_lSecondPhaseCreaturesGuids protected
Definition at line 66 of file eye_of_eternity.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_uiEncounter
uint32 instance_eye_of_eternity::m_uiEncounter protected
Definition at line 60 of file eye_of_eternity.h.
Referenced by Initialize(), IsEncounterInProgress(), and SetData().
m_uiMalygosCompleteTimer
uint32 instance_eye_of_eternity::m_uiMalygosCompleteTimer protected
Definition at line 63 of file eye_of_eternity.h.
Referenced by SetData(), and Update().
m_uiMalygosResetTimer
uint32 instance_eye_of_eternity::m_uiMalygosResetTimer protected
Definition at line 62 of file eye_of_eternity.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
eye_of_eternity.h
eye_of_eternity.cpp