CMaNGOS_WoTLK: instance_blackrock_spire Class Reference
instance_blackrock_spire Class Reference
#include <blackrock_spire.h>
Public Member Functions
instance_blackrock_spire (Map *pMap)
~instance_blackrock_spire ()
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void DoUseEmberseerRunes (bool bReset=false)
void DoProcessEmberseerEvent ()
void DoSortRoomEventMobs ()
void GetIncarceratorGUIDList (GuidList &lList) const
void StartflamewreathEventIfCan ()
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Data Fields
bool m_bBeastIntroDone
bool m_bBeastOutOfLair
Data Fields inherited from InstanceData
Map * instance
Private Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoSendNextStadiumWave ()
void DoSendNextFlamewreathWave ()
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiFlamewreathEventTimer
uint32 m_uiFlamewreathWaveCount
uint32 m_uiStadiumEventTimer
uint8 m_uiStadiumWaves
uint8 m_uiStadiumMobsAlive
ObjectGuid m_aRoomRuneGuid [MAX_ROOMS]
GuidList m_alRoomEventMobGUIDSorted [MAX_ROOMS]
GuidList m_lRoomEventMobGUIDList
GuidList m_lIncarceratorGUIDList
GuidList m_lEmberseerRunesGUIDList
GuidList m_lStadiumSpectatorsGUIDList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 139 of file blackrock_spire.h.
Constructor & Destructor Documentation
instance_blackrock_spire()
instance_blackrock_spire::instance_blackrock_spire (Map * pMap)
Definition at line 99 of file instance_blackrock_spire.cpp.
References Initialize().
~instance_blackrock_spire()
instance_blackrock_spire::~instance_blackrock_spire () inline
Definition at line 143 of file blackrock_spire.h.
Member Function Documentation
DoProcessEmberseerEvent()
void instance_blackrock_spire::DoProcessEmberseerEvent ()
Definition at line 480 of file instance_blackrock_spire.cpp.
References DONE, DoScriptText(), EMOTE_BEGIN, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, InstanceData::instance, m_lIncarceratorGUIDList, NPC_BLACKHAND_INCARCERATOR, NPC_PYROGUARD_EMBERSEER, script_error_log(), SPELL_EMBERSEER_GROWING, TRIGGERED_OLD_TRIGGERED, TYPE_EMBERSEER, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
DoSendNextFlamewreathWave()
void instance_blackrock_spire::DoSendNextFlamewreathWave () private
Definition at line 648 of file instance_blackrock_spire.cpp.
References DoScriptText(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_FATHER_FLAME, HOUR, IN_MILLISECONDS, m_uiFlamewreathEventTimer, m_uiFlamewreathWaveCount, NPC_ROOKERY_GUARDIAN, NPC_ROOKERY_HATCHER, NPC_SOLAKAR_FLAMEWREATH, rookeryEventSpawnPos, SAY_ROOKERY_EVENT_START, SetData(), SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TYPE_FLAMEWREATH, and urand().
Referenced by Update().
DoSendNextStadiumWave()
void instance_blackrock_spire::DoSendNextStadiumWave () private
Definition at line 588 of file instance_blackrock_spire.cpp.
References aStadiumEventNpcs, aStadiumLocs, ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_GYTH_COMBAT_DOOR, m_uiStadiumEventTimer, m_uiStadiumMobsAlive, m_uiStadiumWaves, MAX_STADIUM_MOBS_PER_WAVE, MAX_STADIUM_WAVES, NPC_GYTH, NPC_LORD_VICTOR_NEFARIUS, SAY_NEFARIUS_LOSE1, DialogueHelper::StartNextDialogueText(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, Position::x, Position::y, and Position::z.
Referenced by OnCreatureDeath(), and Update().
DoSortRoomEventMobs()
void instance_blackrock_spire::DoSortRoomEventMobs ()
Definition at line 325 of file instance_blackrock_spire.cpp.
References Map::GetCreature(), GetData(), WorldObject::GetDistance(), Map::GetGameObject(), IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), m_alRoomEventMobGUIDSorted, m_aRoomRuneGuid, m_lRoomEventMobGUIDList, MAX_ROOMS, NOT_STARTED, SetData(), and TYPE_ROOM_EVENT.
DoUseEmberseerRunes()
void instance_blackrock_spire::DoUseEmberseerRunes (bool bReset = false)
Definition at line 517 of file instance_blackrock_spire.cpp.
References ScriptedInstance::DoUseDoorOrButton(), Map::GetGameObject(), InstanceData::instance, and m_lEmberseerRunesGUIDList.
Referenced by boss_pyroguard_emberseerAI::DoHandleEmberseerGrowing(), and SetData().
GetData()
uint32 instance_blackrock_spire::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 317 of file instance_blackrock_spire.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by DoProcessEmberseerEvent(), DoSortRoomEventMobs(), and OnObjectCreate().
GetIncarceratorGUIDList()
void instance_blackrock_spire::GetIncarceratorGUIDList (GuidList & lList) const inline
Definition at line 165 of file blackrock_spire.h.
References m_lIncarceratorGUIDList.
Referenced by boss_pyroguard_emberseerAI::UpdateAI().
Initialize()
void instance_blackrock_spire::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 111 of file instance_blackrock_spire.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_aRoomRuneGuid, and m_auiEncounter.
Referenced by instance_blackrock_spire().
JustDidDialogueStep()
void instance_blackrock_spire::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 534 of file instance_blackrock_spire.cpp.
References Creature::AI(), aSpectatorsSpawnLocs, aSpectatorsTargetLocs, aStadiumLocs, aStadiumSpectators, DONE, Unit::GetMotionMaster(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_lStadiumSpectatorsGUIDList, m_uiStadiumEventTimer, MotionMaster::MovePoint(), NPC_BLACKHAND_HANDLER, NPC_LORD_VICTOR_NEFARIUS, NPC_REND_BLACKHAND, REACT_DEFENSIVE, SAY_NEFARIUS_VICTORY, SAY_NEFARIUS_WARCHIEF, SetData(), Unit::SetFacingTo(), UnitAI::SetReactState(), Creature::SetWalk(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_STADIUM.
Load()
void instance_blackrock_spire::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 295 of file instance_blackrock_spire.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_blackrock_spire::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 167 of file instance_blackrock_spire.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lIncarceratorGUIDList, m_lRoomEventMobGUIDList, ScriptedInstance::m_npcEntryGuidStore, NPC_BLACKHAND_INCARCERATOR, NPC_BLACKHAND_SUMMONER, NPC_BLACKHAND_VETERAN, NPC_GYTH, NPC_LORD_VICTOR_NEFARIUS, NPC_PYROGUARD_EMBERSEER, NPC_REND_BLACKHAND, NPC_SCARSHIELD_INFILTRATOR, NPC_SOLAKAR_FLAMEWREATH, and NPC_THE_BEAST.
OnCreatureDeath()
void instance_blackrock_spire::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 346 of file instance_blackrock_spire.cpp.
References ObjectGuid::Clear(), DONE, DoScriptText(), DoSendNextStadiumWave(), ScriptedInstance::DoUseDoorOrButton(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DRAKKISATH_DOOR_1, GO_DRAKKISATH_DOOR_2, IN_PROGRESS, Creature::IsTemporarySummon(), m_alRoomEventMobGUIDSorted, m_aRoomRuneGuid, m_auiEncounter, m_uiStadiumMobsAlive, MAX_ROOMS, NPC_BLACKHAND_HANDLER, NPC_BLACKHAND_SUMMONER, NPC_BLACKHAND_VETERAN, NPC_CHROMATIC_DRAGON, NPC_CHROMATIC_WHELP, NPC_DRAKKISATH, NPC_GYTH, NPC_LORD_VICTOR_NEFARIUS, NPC_REND_BLACKHAND, NPC_SOLAKAR_FLAMEWREATH, SAY_NEFARIUS_TAUNT1, SAY_NEFARIUS_TAUNT2, SAY_NEFARIUS_TAUNT3, SAY_NEFARIUS_TAUNT4, SAY_NEFARIUS_TAUNT5, SAY_NEFARIUS_TAUNT6, SAY_NEFARIUS_TAUNT7, SAY_NEFARIUS_TAUNT8, SAY_NEFARIUS_VICTORY, SAY_REND_TAUNT1, SAY_REND_TAUNT2, SAY_REND_TAUNT3, SAY_REND_TAUNT4, SetData(), DialogueHelper::StartNextDialogueText(), TYPE_DRAKKISATH, TYPE_FLAMEWREATH, TYPE_ROOM_EVENT, and urand().
OnCreatureDespawn()
void instance_blackrock_spire::OnCreatureDespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 474 of file instance_blackrock_spire.cpp.
References Unit::CastSpell(), Object::GetEntry(), NPC_THE_BEAST, SPELL_FINKLE_IS_EINHORN, and TRIGGERED_OLD_TRIGGERED.
OnCreatureEnterCombat()
void instance_blackrock_spire::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 463 of file instance_blackrock_spire.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_BLACKHAND_INCARCERATOR, SetData(), and TYPE_EMBERSEER.
OnCreatureEvade()
void instance_blackrock_spire::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 435 of file instance_blackrock_spire.cpp.
References FAIL, Creature::ForcedDespawn(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), Creature::IsTemporarySummon(), NPC_BLACKHAND_HANDLER, NPC_BLACKHAND_INCARCERATOR, NPC_CHROMATIC_DRAGON, NPC_CHROMATIC_WHELP, NPC_GYTH, NPC_PYROGUARD_EMBERSEER, NPC_REND_BLACKHAND, NPC_ROOKERY_GUARDIAN, NPC_ROOKERY_HATCHER, NPC_SOLAKAR_FLAMEWREATH, SetData(), TYPE_FLAMEWREATH, and TYPE_STADIUM.
OnObjectCreate()
void instance_blackrock_spire::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 118 of file instance_blackrock_spire.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), GO_DOORS, GO_DRAKKISATH_DOOR_1, GO_DRAKKISATH_DOOR_2, GO_EMBERSEER_IN, GO_EMBERSEER_OUT, GO_EMBERSEER_RUNE_1, GO_EMBERSEER_RUNE_2, GO_EMBERSEER_RUNE_3, GO_EMBERSEER_RUNE_4, GO_EMBERSEER_RUNE_5, GO_EMBERSEER_RUNE_6, GO_EMBERSEER_RUNE_7, GO_FATHER_FLAME, GO_GYTH_COMBAT_DOOR, GO_GYTH_ENTRY_DOOR, GO_GYTH_EXIT_DOOR, GO_ROOM_1_RUNE, GO_ROOM_2_RUNE, GO_ROOM_3_RUNE, GO_ROOM_4_RUNE, GO_ROOM_5_RUNE, GO_ROOM_6_RUNE, GO_ROOM_7_RUNE, GO_STATE_ACTIVE, m_aRoomRuneGuid, ScriptedInstance::m_goEntryGuidStore, m_lEmberseerRunesGUIDList, GameObject::SetGoState(), TYPE_EMBERSEER, TYPE_ROOM_EVENT, and TYPE_STADIUM.
Save()
const char* instance_blackrock_spire::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 158 of file blackrock_spire.h.
References m_strInstData.
SetData()
void instance_blackrock_spire::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 187 of file instance_blackrock_spire.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), DoUseEmberseerRunes(), FAIL, Creature::ForcedDespawn(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DOORS, GO_EMBERSEER_IN, GO_EMBERSEER_OUT, GO_GYTH_ENTRY_DOOR, GO_GYTH_EXIT_DOOR, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_lIncarceratorGUIDList, m_lStadiumSpectatorsGUIDList, m_strInstData, m_uiFlamewreathEventTimer, m_uiFlamewreathWaveCount, m_uiStadiumEventTimer, m_uiStadiumMobsAlive, m_uiStadiumWaves, NPC_GYTH, NPC_LORD_VICTOR_NEFARIUS, NPC_REND_BLACKHAND, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_NEFARIUS_INTRO_1, DialogueHelper::StartNextDialogueText(), TYPE_DRAKKISATH, TYPE_EMBERSEER, TYPE_FLAMEWREATH, TYPE_ROOM_EVENT, TYPE_STADIUM, TYPE_VALTHALAK, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Referenced by boss_pyroguard_emberseerAI::DoHandleEmberseerGrowing(), DoSendNextFlamewreathWave(), DoSortRoomEventMobs(), JustDidDialogueStep(), boss_pyroguard_emberseerAI::JustDied(), boss_pyroguard_emberseerAI::JustReachedHome(), OnCreatureDeath(), OnCreatureEnterCombat(), and OnCreatureEvade().
StartflamewreathEventIfCan()
void instance_blackrock_spire::StartflamewreathEventIfCan ()
Definition at line 713 of file instance_blackrock_spire.cpp.
References DONE, ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_auiEncounter, m_uiFlamewreathEventTimer, m_uiFlamewreathWaveCount, NPC_SOLAKAR_FLAMEWREATH, TYPE_DRAKKISATH, and TYPE_FLAMEWREATH.
Update()
void instance_blackrock_spire::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 692 of file instance_blackrock_spire.cpp.
References DialogueHelper::DialogueUpdate(), DoSendNextFlamewreathWave(), DoSendNextStadiumWave(), m_uiFlamewreathEventTimer, and m_uiStadiumEventTimer.
Field Documentation
m_alRoomEventMobGUIDSorted
GuidList instance_blackrock_spire::m_alRoomEventMobGUIDSorted[MAX_ROOMS] private
Definition at line 189 of file blackrock_spire.h.
Referenced by DoSortRoomEventMobs(), and OnCreatureDeath().
m_aRoomRuneGuid
ObjectGuid instance_blackrock_spire::m_aRoomRuneGuid[MAX_ROOMS] private
Definition at line 188 of file blackrock_spire.h.
Referenced by DoSortRoomEventMobs(), Initialize(), OnCreatureDeath(), and OnObjectCreate().
m_auiEncounter
uint32 instance_blackrock_spire::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 179 of file blackrock_spire.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureDeath(), SetData(), and StartflamewreathEventIfCan().
m_bBeastIntroDone
bool instance_blackrock_spire::m_bBeastIntroDone
Definition at line 171 of file blackrock_spire.h.
m_bBeastOutOfLair
bool instance_blackrock_spire::m_bBeastOutOfLair
Definition at line 172 of file blackrock_spire.h.
m_lEmberseerRunesGUIDList
GuidList instance_blackrock_spire::m_lEmberseerRunesGUIDList private
Definition at line 192 of file blackrock_spire.h.
Referenced by DoUseEmberseerRunes(), and OnObjectCreate().
m_lIncarceratorGUIDList
GuidList instance_blackrock_spire::m_lIncarceratorGUIDList private
Definition at line 191 of file blackrock_spire.h.
Referenced by DoProcessEmberseerEvent(), GetIncarceratorGUIDList(), OnCreatureCreate(), and SetData().
m_lRoomEventMobGUIDList
GuidList instance_blackrock_spire::m_lRoomEventMobGUIDList private
Definition at line 190 of file blackrock_spire.h.
Referenced by DoSortRoomEventMobs(), and OnCreatureCreate().
m_lStadiumSpectatorsGUIDList
GuidList instance_blackrock_spire::m_lStadiumSpectatorsGUIDList private
Definition at line 193 of file blackrock_spire.h.
Referenced by JustDidDialogueStep(), and SetData().
m_strInstData
std::string instance_blackrock_spire::m_strInstData private
Definition at line 180 of file blackrock_spire.h.
Referenced by Save(), and SetData().
m_uiFlamewreathEventTimer
uint32 instance_blackrock_spire::m_uiFlamewreathEventTimer private
Definition at line 182 of file blackrock_spire.h.
Referenced by DoSendNextFlamewreathWave(), SetData(), StartflamewreathEventIfCan(), and Update().
m_uiFlamewreathWaveCount
uint32 instance_blackrock_spire::m_uiFlamewreathWaveCount private
Definition at line 183 of file blackrock_spire.h.
Referenced by DoSendNextFlamewreathWave(), SetData(), and StartflamewreathEventIfCan().
m_uiStadiumEventTimer
uint32 instance_blackrock_spire::m_uiStadiumEventTimer private
Definition at line 184 of file blackrock_spire.h.
Referenced by DoSendNextStadiumWave(), JustDidDialogueStep(), SetData(), and Update().
m_uiStadiumMobsAlive
uint8 instance_blackrock_spire::m_uiStadiumMobsAlive private
Definition at line 186 of file blackrock_spire.h.
Referenced by DoSendNextStadiumWave(), OnCreatureDeath(), and SetData().
m_uiStadiumWaves
uint8 instance_blackrock_spire::m_uiStadiumWaves private
Definition at line 185 of file blackrock_spire.h.
Referenced by DoSendNextStadiumWave(), and SetData().
The documentation for this class was generated from the following files:
blackrock_spire.h
instance_blackrock_spire.cpp