CMaNGOS_WoTLK: MaNGOS::NearestAssistCreatureInCreatureRangeCheck Class Reference
MaNGOS::NearestAssistCreatureInCreatureRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestAssistCreatureInCreatureRangeCheck (Creature *obj, Unit *enemy, float range)
WorldObject const & GetFocusObject () const
bool operator() (Creature *u)
float GetLastRange () const
NearestAssistCreatureInCreatureRangeCheck (NearestAssistCreatureInCreatureRangeCheck const &)
Private Attributes
Creature *const i_obj
Unit *const i_enemy
float i_range
Detailed Description
Definition at line 1379 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestAssistCreatureInCreatureRangeCheck() [1/2]
MaNGOS::NearestAssistCreatureInCreatureRangeCheck::NearestAssistCreatureInCreatureRangeCheck (Creature * obj, Unit * enemy, float range) inline
Definition at line 1382 of file GridNotifiers.h.
NearestAssistCreatureInCreatureRangeCheck() [2/2]
MaNGOS::NearestAssistCreatureInCreatureRangeCheck::NearestAssistCreatureInCreatureRangeCheck (NearestAssistCreatureInCreatureRangeCheck const &)
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::NearestAssistCreatureInCreatureRangeCheck::GetFocusObject () const inline
Definition at line 1384 of file GridNotifiers.h.
References i_obj.
GetLastRange()
float MaNGOS::NearestAssistCreatureInCreatureRangeCheck::GetLastRange () const inline
Definition at line 1402 of file GridNotifiers.h.
References i_range.
operator()()
bool MaNGOS::NearestAssistCreatureInCreatureRangeCheck::operator() (Creature * u) inline
Definition at line 1385 of file GridNotifiers.h.
References Unit::CanAssist(), Unit::CanAttack(), WorldObject::GetDistance(), i_enemy, i_obj, i_range, Unit::IsDead(), Unit::IsInCombat(), WorldObject::IsWithinDistInMap(), and WorldObject::IsWithinLOSInMap().
Field Documentation
i_enemy
Unit* const MaNGOS::NearestAssistCreatureInCreatureRangeCheck::i_enemy private
Definition at line 1409 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Creature* const MaNGOS::NearestAssistCreatureInCreatureRangeCheck::i_obj private
Definition at line 1408 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::NearestAssistCreatureInCreatureRangeCheck::i_range private
Definition at line 1410 of file GridNotifiers.h.
Referenced by GetLastRange(), and operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h