CMaNGOS_WoTLK: VMAP::VMapManager2 Class Reference
VMAP::VMapManager2 Class Reference
#include <VMapManager2.h>
Public Member Functions
G3D::Vector3 convertPositionToInternalRep (float x, float y, float z) const
VMapManager2 ()
~VMapManager2 ()
VMAPLoadResult loadMap (const char *pBasePath, unsigned int pMapId, int x, int y) override
bool IsTileLoaded (uint32 mapId, uint32 x, uint32 y) const override
void unloadMap (unsigned int pMapId, int x, int y) override
void unloadMap (unsigned int pMapId) override
bool isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, bool ignoreM2Model) override
bool getObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float pModifyDist) override
fill the hit pos and return true, if an object was hit
float getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist) override
get height or INVALID_HEIGHT if no height available
bool processCommand (char *) override
send debug commands
bool getAreaInfo (unsigned int pMapId, float x, float y, float &z, uint32 &flags, int32 &adtId, int32 &rootId, int32 &groupId) const override
Query world model area info.
bool GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float &level, float &floor, uint32 &type) const override
WorldModel * acquireModelInstance (const std::string &basepath, const std::string &filename)
void releaseModelInstance (const std::string &filename)
std::string getDirFileName (unsigned int pMapId, int, int) const override
bool existsMap (const char *pBasePath, unsigned int pMapId, int x, int y) override
Public Member Functions inherited from VMAP::IVMapManager
IVMapManager ()
virtual ~IVMapManager (void)
void setEnableLineOfSightCalc (bool pVal)
Enable/disable LOS calculation It is enabled by default.
void setEnableHeightCalc (bool pVal)
Enable/disable model height calculation It is enabled by default.
bool isLineOfSightCalcEnabled () const
bool isHeightCalcEnabled () const
bool isMapLoadingEnabled () const
Static Public Member Functions
static std::string getMapFileName (unsigned int pMapId)
Protected Member Functions
bool _loadMap (uint32 pMapId, const std::string &basePath, uint32 tileX, uint32 tileY)
Protected Attributes
ModelFileMap iLoadedModelFiles
InstanceTreeMap iInstanceMapTrees
Private Attributes
std::mutex m_vmStaticMapMutex
std::mutex m_vmModelMutex
Detailed Description
Definition at line 66 of file VMapManager2.h.
Constructor & Destructor Documentation
VMapManager2()
VMAP::VMapManager2::VMapManager2 ()
Definition at line 34 of file VMapManager2.cpp.
~VMapManager2()
VMAP::VMapManager2::~VMapManager2 (void)
Definition at line 40 of file VMapManager2.cpp.
References iInstanceMapTrees, and iLoadedModelFiles.
Member Function Documentation
_loadMap()
bool VMAP::VMapManager2::_loadMap (uint32 pMapId, const std::string & basePath, uint32 tileX, uint32 tileY) protected
Definition at line 102 of file VMapManager2.cpp.
References getMapFileName(), iInstanceMapTrees, VMAP::StaticMapTree::InitMap(), and m_vmStaticMapMutex.
Referenced by loadMap().
acquireModelInstance()
WorldModel * VMAP::VMapManager2::acquireModelInstance (const std::string & basepath, const std::string & filename)
Definition at line 265 of file VMapManager2.cpp.
References DEBUG_FILTER_LOG, ERROR_LOG, iLoadedModelFiles, LOG_FILTER_MAP_LOADING, m_vmModelMutex, and VMAP::WorldModel::readFile().
Referenced by VMAP::StaticMapTree::InitMap(), and VMAP::StaticMapTree::LoadMapTile().
convertPositionToInternalRep()
Vector3 VMAP::VMapManager2::convertPositionToInternalRep (float x, float y, float z) const
Definition at line 54 of file VMapManager2.cpp.
Referenced by getAreaInfo(), getHeight(), GetLiquidLevel(), getObjectHitPos(), and isInLineOfSight().
existsMap()
bool VMAP::VMapManager2::existsMap (const char * pBasePath, unsigned int pMapId, int x, int y) override virtual
Implements VMAP::IVMapManager.
Definition at line 305 of file VMapManager2.cpp.
References VMAP::StaticMapTree::CanLoadMap().
getAreaInfo()
bool VMAP::VMapManager2::getAreaInfo (unsigned int pMapId, float x, float y, float & z, uint32 & flags, int32 & adtId, int32 & rootId, int32 & groupId) const override virtual
Query world model area info.
Parameters
z gets adjusted to the ground height for which this are info is valid
Implements VMAP::IVMapManager.
Definition at line 229 of file VMapManager2.cpp.
References convertPositionToInternalRep(), and iInstanceMapTrees.
getDirFileName()
std::string VMAP::VMapManager2::getDirFileName (unsigned int pMapId, int , int) const inline override virtual
Implements VMAP::IVMapManager.
Definition at line 110 of file VMapManager2.h.
References getMapFileName().
getHeight()
float VMAP::VMapManager2::getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist) override virtual
get height or INVALID_HEIGHT if no height available
Implements VMAP::IVMapManager.
Definition at line 208 of file VMapManager2.cpp.
References convertPositionToInternalRep(), iInstanceMapTrees, VMAP::IVMapManager::isHeightCalcEnabled(), and VMAP_INVALID_HEIGHT_VALUE.
GetLiquidLevel()
bool VMAP::VMapManager2::GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float & level, float & floor, uint32 & type) const override virtual
Implements VMAP::IVMapManager.
Definition at line 243 of file VMapManager2.cpp.
References convertPositionToInternalRep(), VMAP::ModelInstance::GetLiquidLevel(), VMAP::GroupModel::GetLiquidType(), VMAP::LocationInfo::ground_Z, VMAP::LocationInfo::hitInstance, VMAP::LocationInfo::hitModel, and iInstanceMapTrees.
getMapFileName()
std::string VMAP::VMapManager2::getMapFileName (unsigned int pMapId) static
Definition at line 66 of file VMapManager2.cpp.
References MAP_FILENAME_EXTENSION2.
Referenced by _loadMap(), VMAP::StaticMapTree::CanLoadMap(), and getDirFileName().
getObjectHitPos()
bool VMAP::VMapManager2::getObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float pModifyDist) override virtual
fill the hit pos and return true, if an object was hit
get the hit position and return true if we hit something otherwise the result pos will be the dest pos
Implements VMAP::IVMapManager.
Definition at line 179 of file VMapManager2.cpp.
References convertPositionToInternalRep(), iInstanceMapTrees, and VMAP::IVMapManager::isLineOfSightCalcEnabled().
isInLineOfSight()
bool VMAP::VMapManager2::isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, bool ignoreM2Model) override virtual
Implements VMAP::IVMapManager.
Definition at line 158 of file VMapManager2.cpp.
References convertPositionToInternalRep(), iInstanceMapTrees, and VMAP::IVMapManager::isLineOfSightCalcEnabled().
IsTileLoaded()
bool VMAP::VMapManager2::IsTileLoaded (uint32 mapId, uint32 x, uint32 y) const override virtual
Implements VMAP::IVMapManager.
Definition at line 91 of file VMapManager2.cpp.
References iInstanceMapTrees.
loadMap()
VMAPLoadResult VMAP::VMapManager2::loadMap (const char * pBasePath, unsigned int pMapId, int x, int y) override virtual
Implements VMAP::IVMapManager.
Definition at line 76 of file VMapManager2.cpp.
References _loadMap(), VMAP::IVMapManager::isMapLoadingEnabled(), VMAP::VMAP_LOAD_RESULT_ERROR, VMAP::VMAP_LOAD_RESULT_IGNORED, and VMAP::VMAP_LOAD_RESULT_OK.
processCommand()
bool VMAP::VMapManager2::processCommand (char * pCommand) inline override virtual
send debug commands
Implements VMAP::IVMapManager.
Definition at line 101 of file VMapManager2.h.
releaseModelInstance()
void VMAP::VMapManager2::releaseModelInstance (const std::string & filename)
Definition at line 288 of file VMapManager2.cpp.
References DEBUG_FILTER_LOG, ERROR_LOG, iLoadedModelFiles, and LOG_FILTER_MAP_LOADING.
Referenced by VMAP::StaticMapTree::UnloadMap(), and VMAP::StaticMapTree::UnloadMapTile().
unloadMap() [1/2]
void VMAP::VMapManager2::unloadMap (unsigned int pMapId) override virtual
Implements VMAP::IVMapManager.
Definition at line 126 of file VMapManager2.cpp.
References iInstanceMapTrees.
unloadMap() [2/2]
void VMAP::VMapManager2::unloadMap (unsigned int pMapId, int x, int y) override virtual
Implements VMAP::IVMapManager.
Definition at line 142 of file VMapManager2.cpp.
References iInstanceMapTrees.
Field Documentation
iInstanceMapTrees
InstanceTreeMap VMAP::VMapManager2::iInstanceMapTrees protected
Definition at line 75 of file VMapManager2.h.
Referenced by _loadMap(), getAreaInfo(), getHeight(), GetLiquidLevel(), getObjectHitPos(), isInLineOfSight(), IsTileLoaded(), unloadMap(), and ~VMapManager2().
iLoadedModelFiles
ModelFileMap VMAP::VMapManager2::iLoadedModelFiles protected
Definition at line 74 of file VMapManager2.h.
Referenced by acquireModelInstance(), releaseModelInstance(), and ~VMapManager2().
m_vmModelMutex
std::mutex VMAP::VMapManager2::m_vmModelMutex private
Definition at line 70 of file VMapManager2.h.
Referenced by acquireModelInstance().
m_vmStaticMapMutex
std::mutex VMAP::VMapManager2::m_vmStaticMapMutex private
Definition at line 69 of file VMapManager2.h.
Referenced by _loadMap().
The documentation for this class was generated from the following files:
VMapManager2.h
VMapManager2.cpp