CMaNGOS_WoTLK: NamreebAnticheat::AntispamMgr Class Reference
NamreebAnticheat::AntispamMgr Class Reference
#include <antispammgr.hpp>
Public Member Functions
AntispamMgr ()
~AntispamMgr ()
void LoadFromDB ()
std::string NormalizeString (const std::string &string, uint32 mask) const
void BlacklistAdd (const std::string &string)
uint32 CheckBlacklist (const std::string &string, std::string &log) const
void ScheduleAnalysis (std::shared_ptr< Antispam > session)
void CacheSession (std::shared_ptr< Antispam > session)
std::shared_ptr< Antispam > GetSession (uint32 accountId)
std::shared_ptr< Antispam > CheckCache (uint32 accountId)
bool IsSilenced (uint32 accountId) const
bool IsSilenced (const WorldSession *session) const
void Silence (uint32 accountId) const
void Unsilence (uint32 accountId) const
Private Member Functions
std::string NormalizeStringInternal (const std::string &string, uint32 mask) const
void WorkerLoop ()
Private Attributes
std::mutex _mutex
bool _shutdownRequested
std::vector< std::pair< std::string, std::string > > _blacklist
std::vector< std::pair< std::string, std::string > > _asciiReplace
std::vector< std::pair< std::wstring, std::wstring > > _unicodeReplace
std::unordered_set< std::shared_ptr< Antispam > > _workQueue
std::unordered_map< uint32, std::pair< uint32, std::shared_ptr< Antispam > > > _temporaryCache
std::thread _worker
Detailed Description
Definition at line 28 of file antispammgr.hpp.
Constructor & Destructor Documentation
AntispamMgr()
NamreebAnticheat::AntispamMgr::AntispamMgr ()
Definition at line 140 of file antispammgr.cpp.
~AntispamMgr()
NamreebAnticheat::AntispamMgr::~AntispamMgr ()
Definition at line 142 of file antispammgr.cpp.
References _shutdownRequested, and _worker.
Member Function Documentation
BlacklistAdd()
void NamreebAnticheat::AntispamMgr::BlacklistAdd (const std::string & string)
Definition at line 275 of file antispammgr.cpp.
References _blacklist, _mutex, SqlStatement::addString(), Database::BeginTransaction(), Database::CommitTransaction(), Database::CreateStatement(), LoginDatabase, NormalizeStringInternal(), and sAnticheatConfig.
CacheSession()
void NamreebAnticheat::AntispamMgr::CacheSession (std::shared_ptr< Antispam > session)
Definition at line 359 of file antispammgr.cpp.
References _mutex, _temporaryCache, and WorldTimer::getMSTime().
CheckBlacklist()
uint32 NamreebAnticheat::AntispamMgr::CheckBlacklist (const std::string & string, std::string & log) const
Definition at line 308 of file antispammgr.cpp.
References _blacklist, _mutex, NormalizeStringInternal(), and sAnticheatConfig.
CheckCache()
std::shared_ptr< Antispam > NamreebAnticheat::AntispamMgr::CheckCache (uint32 accountId)
Definition at line 381 of file antispammgr.cpp.
References _mutex, and _temporaryCache.
GetSession()
std::shared_ptr< Antispam > NamreebAnticheat::AntispamMgr::GetSession (uint32 accountId)
Definition at line 365 of file antispammgr.cpp.
References _mutex, and _temporaryCache.
IsSilenced() [1/2]
bool NamreebAnticheat::AntispamMgr::IsSilenced (const WorldSession * session) const
Definition at line 402 of file antispammgr.cpp.
References ACCOUNT_FLAG_SILENCED, and WorldSession::GetAccountFlags().
IsSilenced() [2/2]
bool NamreebAnticheat::AntispamMgr::IsSilenced (uint32 accountId) const
Definition at line 393 of file antispammgr.cpp.
References ACCOUNT_FLAG_SILENCED, sAccountMgr, and sWorld.
LoadFromDB()
void NamreebAnticheat::AntispamMgr::LoadFromDB ()
Definition at line 199 of file antispammgr.cpp.
References _asciiReplace, _blacklist, _mutex, _unicodeReplace, LoginDatabase, NormalizeStringInternal(), Database::Query(), sAnticheatConfig, and sLog.
NormalizeString()
std::string NamreebAnticheat::AntispamMgr::NormalizeString (const std::string & string, uint32 mask) const
Definition at line 57 of file antispammgr.cpp.
References _mutex, and NormalizeStringInternal().
NormalizeStringInternal()
std::string NamreebAnticheat::AntispamMgr::NormalizeStringInternal (const std::string & string, uint32 mask) const private
Definition at line 63 of file antispammgr.cpp.
References _asciiReplace, _unicodeReplace, isBasicLatinCharacter(), isBasicLatinString(), isNumeric(), NF_CUT_COLOR, NF_CUT_CTRL, NF_CUT_NUMBERS, NF_CUT_PUNCT, NF_CUT_SPACE, NF_REMOVE_NON_LATIN, NF_REMOVE_REPEATS, NF_REPLACE_UNICODE, NF_REPLACE_WORDS, Utf8toWStr(), and wstrToUpper().
Referenced by BlacklistAdd(), CheckBlacklist(), LoadFromDB(), and NormalizeString().
ScheduleAnalysis()
void NamreebAnticheat::AntispamMgr::ScheduleAnalysis (std::shared_ptr< Antispam > session)
Definition at line 353 of file antispammgr.cpp.
References _mutex, and _workQueue.
Silence()
void NamreebAnticheat::AntispamMgr::Silence (uint32 accountId) const
Definition at line 408 of file antispammgr.cpp.
References ACCOUNT_FLAG_SILENCED, Database::BeginTransaction(), Database::CommitTransaction(), LoginDatabase, Database::PExecute(), and sWorld.
Unsilence()
void NamreebAnticheat::AntispamMgr::Unsilence (uint32 accountId) const
Definition at line 422 of file antispammgr.cpp.
References ACCOUNT_FLAG_SILENCED, Database::BeginTransaction(), Database::CommitTransaction(), LoginDatabase, Database::PExecute(), and sWorld.
WorkerLoop()
void NamreebAnticheat::AntispamMgr::WorkerLoop () private
Definition at line 148 of file antispammgr.cpp.
References _mutex, _shutdownRequested, _temporaryCache, _workQueue, WorldTimer::getMSTime(), IN_MILLISECONDS, and sAnticheatConfig.
Field Documentation
_asciiReplace
std::vector<std::pair<std::string, std::string> > NamreebAnticheat::AntispamMgr::_asciiReplace private
Definition at line 43 of file antispammgr.hpp.
Referenced by LoadFromDB(), and NormalizeStringInternal().
_blacklist
std::vector<std::pair<std::string, std::string> > NamreebAnticheat::AntispamMgr::_blacklist private
Definition at line 38 of file antispammgr.hpp.
Referenced by BlacklistAdd(), CheckBlacklist(), and LoadFromDB().
_mutex
std::mutex NamreebAnticheat::AntispamMgr::_mutex mutable private
Definition at line 33 of file antispammgr.hpp.
Referenced by BlacklistAdd(), CacheSession(), CheckBlacklist(), CheckCache(), GetSession(), LoadFromDB(), NormalizeString(), ScheduleAnalysis(), and WorkerLoop().
_shutdownRequested
bool NamreebAnticheat::AntispamMgr::_shutdownRequested private
Definition at line 35 of file antispammgr.hpp.
Referenced by WorkerLoop(), and ~AntispamMgr().
_temporaryCache
std::unordered_map<uint32, std::pair<uint32, std::shared_ptr<Antispam> > > NamreebAnticheat::AntispamMgr::_temporaryCache private
Definition at line 50 of file antispammgr.hpp.
Referenced by CacheSession(), CheckCache(), GetSession(), and WorkerLoop().
_unicodeReplace
std::vector<std::pair<std::wstring, std::wstring> > NamreebAnticheat::AntispamMgr::_unicodeReplace private
Definition at line 44 of file antispammgr.hpp.
Referenced by LoadFromDB(), and NormalizeStringInternal().
_worker
std::thread NamreebAnticheat::AntispamMgr::_worker private
Definition at line 53 of file antispammgr.hpp.
Referenced by ~AntispamMgr().
_workQueue
std::unordered_set<std::shared_ptr<Antispam> > NamreebAnticheat::AntispamMgr::_workQueue private
Definition at line 47 of file antispammgr.hpp.
Referenced by ScheduleAnalysis(), and WorkerLoop().
The documentation for this class was generated from the following files:
antispammgr.hpp
antispammgr.cpp