CMaNGOS_WoTLK: CreatureEventAIMgr Class Reference
CreatureEventAIMgr Class Reference
#include <CreatureEventAIMgr.h>
Public Member Functions
CreatureEventAIMgr ()
~CreatureEventAIMgr ()
void LoadCreatureEventAI_Summons (bool check_entry_use)
void LoadCreatureEventAI_Scripts ()
std::shared_ptr< CreatureEventAI_Event_Map > const & GetCreatureEventEntryAIMap () const
std::shared_ptr< CreatureEventAI_Event_Map > const & GetCreatureEventGuidAIMap () const
CreatureEventAI_Summon_Map const & GetCreatureEventAISummonMap () const
std::shared_ptr< CreatureEventAI_EventComputedData_Map > const & GetEAIComputedDataMap () const
Private Member Functions
void CheckUnusedAISummons ()
Private Attributes
std::shared_ptr< CreatureEventAI_Event_Map > m_CreatureEventAIEventEntryMap
std::shared_ptr< CreatureEventAI_Event_Map > m_CreatureEventAIEventGuidMap
CreatureEventAI_Summon_Map m_CreatureEventAI_Summon_Map
std::shared_ptr< CreatureEventAI_EventComputedData_Map > m_creatureEventAIComputedDataMap
Detailed Description
Definition at line 25 of file CreatureEventAIMgr.h.
Constructor & Destructor Documentation
CreatureEventAIMgr()
CreatureEventAIMgr::CreatureEventAIMgr () inline
Definition at line 28 of file CreatureEventAIMgr.h.
~CreatureEventAIMgr()
CreatureEventAIMgr::~CreatureEventAIMgr () inline
Definition at line 29 of file CreatureEventAIMgr.h.
Member Function Documentation
CheckUnusedAISummons()
void CreatureEventAIMgr::CheckUnusedAISummons () private
Definition at line 90 of file CreatureEventAIMgr.cpp.
References ACTION_T_SUMMON_ID, m_CreatureEventAI_Summon_Map, m_CreatureEventAIEventEntryMap, m_CreatureEventAIEventGuidMap, and sLog.
Referenced by LoadCreatureEventAI_Scripts(), and LoadCreatureEventAI_Summons().
GetCreatureEventAISummonMap()
CreatureEventAI_Summon_Map const& CreatureEventAIMgr::GetCreatureEventAISummonMap () const inline
Definition at line 36 of file CreatureEventAIMgr.h.
References m_CreatureEventAI_Summon_Map.
GetCreatureEventEntryAIMap()
std::shared_ptr<CreatureEventAI_Event_Map> const& CreatureEventAIMgr::GetCreatureEventEntryAIMap () const inline
Definition at line 34 of file CreatureEventAIMgr.h.
References m_CreatureEventAIEventEntryMap.
GetCreatureEventGuidAIMap()
std::shared_ptr<CreatureEventAI_Event_Map> const& CreatureEventAIMgr::GetCreatureEventGuidAIMap () const inline
Definition at line 35 of file CreatureEventAIMgr.h.
References m_CreatureEventAIEventGuidMap.
GetEAIComputedDataMap()
std::shared_ptr<CreatureEventAI_EventComputedData_Map> const& CreatureEventAIMgr::GetEAIComputedDataMap () const inline
Definition at line 37 of file CreatureEventAIMgr.h.
References m_creatureEventAIComputedDataMap.
LoadCreatureEventAI_Scripts()
void CreatureEventAIMgr::LoadCreatureEventAI_Scripts ()
Definition at line 205 of file CreatureEventAIMgr.cpp.
References CreatureEventAI_Event::action, ACTION_T_ATTACK_START, ACTION_T_AUTO_ATTACK, ACTION_T_CALL_FOR_HELP, ACTION_T_CAST, ACTION_T_CAST_EVENT, ACTION_T_CAST_EVENT_ALL, ACTION_T_CHANCED_TEXT, ACTION_T_CHANGE_MOVEMENT, ACTION_T_COMBAT_MOVEMENT, ACTION_T_DESPAWN_GUARDIANS, ACTION_T_DIE, ACTION_T_EMOTE, ACTION_T_END, ACTION_T_EVADE, ACTION_T_FLEE_FOR_ASSIST, ACTION_T_FORCE_DESPAWN, ACTION_T_INC_PHASE, ACTION_T_INTERRUPT_SPELL, ACTION_T_KILLED_MONSTER, ACTION_T_MORPH_TO_ENTRY_OR_MODEL, ACTION_T_MOUNT_TO_ENTRY_OR_MODEL, ACTION_T_NONE, ACTION_T_PAUSE_WAYPOINTS, ACTION_T_QUEST_EVENT, ACTION_T_QUEST_EVENT_ALL, ACTION_T_RANDOM_EMOTE, ACTION_T_RANDOM_PHASE, ACTION_T_RANDOM_PHASE_RANGE, ACTION_T_RANDOM_SAY, ACTION_T_RANDOM_SOUND, ACTION_T_RANDOM_TEXTEMOTE, ACTION_T_RANDOM_YELL, ACTION_T_RANGED_MOVEMENT, ACTION_T_REMOVE_UNIT_FLAG, ACTION_T_REMOVEAURASFROMSPELL, ACTION_T_SET_DEATH_PREVENTION, ACTION_T_SET_DESPAWN_AGGREGATION, ACTION_T_SET_FACING, ACTION_T_SET_FACTION, ACTION_T_SET_FOLLOW_MOVEMENT, ACTION_T_SET_IMMOBILIZED_STATE, ACTION_T_SET_IMMUNITY_SET, ACTION_T_SET_INST_DATA, ACTION_T_SET_INST_DATA64, ACTION_T_SET_PHASE, ACTION_T_SET_RANGED_MODE, ACTION_T_SET_REACT_STATE, ACTION_T_SET_SHEATH, ACTION_T_SET_SPELL_SET, ACTION_T_SET_STAND_STATE, ACTION_T_SET_THROW_MASK, ACTION_T_SET_UNIT_FIELD, ACTION_T_SET_UNIT_FLAG, ACTION_T_SET_WALK, ACTION_T_SOUND, ACTION_T_SPAWN, ACTION_T_START_RELAY_SCRIPT, ACTION_T_SUMMON_ID, ACTION_T_TEXT, ACTION_T_TEXT_NEW, ACTION_T_THREAT_ALL_PCT, ACTION_T_THREAT_SINGLE, ACTION_T_THROW_AI_EVENT, ACTION_T_UPDATE_TEMPLATE, ACTION_T_ZONE_COMBAT_PULSE, CreatureEventAI_Action::attackStart, CreatureEventAI_Event::buffed, CreatureEventAI_Action::cast, CreatureEventAI_Action::cast_event, CreatureEventAI_Action::cast_event_all, CAST_FORCE_TARGET_SELF, CAST_TRIGGERED, CreatureEventAI_Action::chanced_text, CHANGE_MOVEMENT_MAX, CreatureEventAI_Action::changeMovement, CheckUnusedAISummons(), CONFIG_FLOAT_CREATURE_FAMILY_ASSISTANCE_RADIUS, MaNGOS::Count(), CreatureEventAI_Event::creature_guid, CreatureEventAI_Event::creature_id, CURRENT_MAX_SPELL, CreatureEventAI_Event::death, CreatureEventAI_Action::deathPrevention, CreatureEventAI_Action::despawnGuardians, EFLAG_COMBAT_ACTION, EFLAG_DIFFICULTY_ALL, EFLAG_REPEATABLE, CreatureEventAI_Action::emote, CreatureEventAI_Event::event_chance, CreatureEventAI_Event::event_flags, CreatureEventAI_Event::event_id, CreatureEventAI_Event::event_inverse_phase_mask, EVENT_T_AGGRO, EVENT_T_AURA, EVENT_T_DEATH, EVENT_T_DEATH_PREVENTED, EVENT_T_END, EVENT_T_ENERGY, EVENT_T_EVADE, EVENT_T_FACING_TARGET, EVENT_T_FRIENDLY_HP, EVENT_T_FRIENDLY_IS_CC, EVENT_T_FRIENDLY_MISSING_BUFF, EVENT_T_HP, EVENT_T_KILL, EVENT_T_MANA, EVENT_T_MISSING_AURA, EVENT_T_OOC_LOS, EVENT_T_QUEST_ACCEPT, EVENT_T_QUEST_COMPLETE, EVENT_T_RANGE, EVENT_T_REACHED_HOME, EVENT_T_RECEIVE_AI_EVENT, EVENT_T_RECEIVE_EMOTE, EVENT_T_SELECT_ATTACKING_TARGET, EVENT_T_SPAWNED, EVENT_T_SPELL_CAST, EVENT_T_SPELLHIT, EVENT_T_SPELLHIT_TARGET, EVENT_T_SUMMONED_JUST_DESPAWN, EVENT_T_SUMMONED_JUST_DIED, EVENT_T_SUMMONED_UNIT, EVENT_T_TARGET_AURA, EVENT_T_TARGET_CASTING, EVENT_T_TARGET_HP, EVENT_T_TARGET_MANA, EVENT_T_TARGET_MISSING_AURA, EVENT_T_TARGET_NOT_REACHABLE, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, EVENT_T_TIMER_OOC, CreatureEventAI_Event::event_type, CreatureEventAI_Event::facingTarget, CreatureEventAI_Event::friendly_buff, CreatureEventAI_Event::friendly_hp, CreatureEventAI_Event::friendly_is_cc, CreatureEventAI_EventComputedData::friendlyHp, GetAreaEntryByAreaID(), Field::GetInt32(), SQLStorageBase::GetMaxEntry(), Field::GetUInt32(), Field::GetUInt8(), SpellEntry::HasAttribute(), CreatureEventAI_Action::immunitySet, CreatureEventAI_Action::interruptSpell, IsOnlySelfTargeting(), IsSpellHaveEffect(), IsValidTargetType(), CreatureEventAI_Event::kill, CreatureEventAI_Action::killed_monster, LOG_FILTER_EVENT_AI_DEV, SQLStorage::LookupEntry(), m_CreatureEventAI_Summon_Map, m_creatureEventAIComputedDataMap, m_CreatureEventAIEventEntryMap, m_CreatureEventAIEventGuidMap, MAX_ACTIONS, MAX_DB_MOTION_TYPE, MAX_PHASE, MAX_SHEATH_STATE, MAX_UNIT_STAND_STATE, MAXIMAL_AI_EVENT_EVENTAI, CreatureEventAI_Action::morph, CreatureEventAI_Action::mount, OBJECT_END, CreatureEventAI_Event::ooc_los, CreatureEventAI_Event::percent_range, Database::Query(), CreatureEventAI_Event::quest, CreatureEventAI_Action::quest_event, CreatureEventAI_Action::quest_event_all, QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT, CreatureEventAI_Action::random_emote, CreatureEventAI_Action::random_phase, CreatureEventAI_Action::random_phase_range, CreatureEventAI_Action::random_sound, CreatureEventAI_Event::range, CreatureEventAI_Action::rangedMode, SpellEntry::rangeIndex, CreatureEventAI_Action::raw, CreatureEventAI_Event::raw, REACT_AGGRESSIVE, CreatureEventAI_Event::receive_emote, CreatureEventAI_Event::receiveAIEvent, CreatureEventAI_Action::relayScript, CreatureEventAI_Action::remove_aura, RUN_CHASE, RUN_DEFAULT, SpellEntry::SchoolMask, sConditionStorage, sCreatureDisplayInfoStore, sCreatureStorage, SCRIPT_TYPE_RELAY, CreatureEventAI_Event::selectTarget, sEmotesStore, sEmotesTextStore, CreatureEventAI_Action::set_faction, CreatureEventAI_Action::set_inc_phase, CreatureEventAI_Action::set_inst_data, CreatureEventAI_Action::set_inst_data64, CreatureEventAI_Action::set_phase, CreatureEventAI_Action::set_sheath, CreatureEventAI_Action::set_unit_field, CreatureEventAI_Action::setFacing, CreatureEventAI_Action::setReactState, CreatureEventAI_Action::setStandState, CreatureEventAI_Action::setThrowMask, sFactionTemplateStore, SHEATH_STATE_UNARMED, SIZE_OF_GRIDS, sLog, sMapStore, sObjectMgr, CreatureEventAI_Action::sound, CreatureEventAI_Event::spawned, SPAWNED_EVENT_ALWAY, SPAWNED_EVENT_MAP, SPAWNED_EVENT_ZONE, SPELL_ATTR_EX3_ONLY_ON_PLAYER, SPELL_ATTR_EX_EXCLUDE_CASTER, SPELL_EFFECT_CREATE_RANDOM_ITEM, SPELL_EFFECT_DUMMY, SPELL_EFFECT_KILL_CREDIT_GROUP, SPELL_EFFECT_KILL_CREDIT_PERSONAL, SPELL_EFFECT_QUEST_COMPLETE, CreatureEventAI_Event::spell_hit, CreatureEventAI_Event::spell_hit_target, SPELL_RANGE_IDX_SELF_ONLY, CreatureEventAI_Event::spellCast, CreatureEventAI_Action::spellSet, sScriptMgr, sSoundEntriesStore, sSpellTemplate, BarGoLink::step(), CreatureEventAI_Action::summon, CreatureEventAI_Action::summon_id, CreatureEventAI_Event::summoned, sWorld, CreatureEventAI_Event::target_casting, TARGET_T_ACTION_INVOKER, TARGET_T_ACTION_INVOKER_OWNER, TARGET_T_EVENT_SPECIFIC, TARGET_T_HOSTILE, TARGET_T_HOSTILE_RANDOM, TARGET_T_HOSTILE_RANDOM_NOT_TOP, TARGET_T_NEAREST_AOE_TARGET, TARGET_T_NONE, TARGET_T_SELF, SpellEntry::Targets, CreatureEventAI_Action::text, CreatureEventAI_Action::textNew, CreatureEventAI_Action::threat_all_pct, CreatureEventAI_Action::threat_single, CreatureEventAI_Action::throwEvent, CreatureEventAI_Event::timer, CreatureEventAI_Action::type, TYPE_MAX, UNIT_END, CreatureEventAI_Action::unit_flag, CreatureEventAI_Action::update_template, WALK_CHASE, WALK_DEFAULT, CreatureEventAI_Action::walkSetting, and WorldDatabase.
LoadCreatureEventAI_Summons()
void CreatureEventAIMgr::LoadCreatureEventAI_Summons (bool check_entry_use)
Definition at line 35 of file CreatureEventAIMgr.cpp.
References CheckUnusedAISummons(), MaNGOS::Count(), QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), CreatureEventAI_Summon::id, MaNGOS::IsValidMapCoord(), m_CreatureEventAI_Summon_Map, QueryResult::NextRow(), CreatureEventAI_Summon::orientation, CreatureEventAI_Summon::position_x, CreatureEventAI_Summon::position_y, CreatureEventAI_Summon::position_z, Database::Query(), sLog, CreatureEventAI_Summon::SpawnTimeSecs, BarGoLink::step(), and WorldDatabase.
Field Documentation
m_CreatureEventAI_Summon_Map
CreatureEventAI_Summon_Map CreatureEventAIMgr::m_CreatureEventAI_Summon_Map private
Definition at line 44 of file CreatureEventAIMgr.h.
Referenced by CheckUnusedAISummons(), GetCreatureEventAISummonMap(), LoadCreatureEventAI_Scripts(), and LoadCreatureEventAI_Summons().
m_creatureEventAIComputedDataMap
std::shared_ptr<CreatureEventAI_EventComputedData_Map> CreatureEventAIMgr::m_creatureEventAIComputedDataMap private
Definition at line 45 of file CreatureEventAIMgr.h.
Referenced by GetEAIComputedDataMap(), and LoadCreatureEventAI_Scripts().
m_CreatureEventAIEventEntryMap
std::shared_ptr<CreatureEventAI_Event_Map> CreatureEventAIMgr::m_CreatureEventAIEventEntryMap private
Definition at line 42 of file CreatureEventAIMgr.h.
Referenced by CheckUnusedAISummons(), GetCreatureEventEntryAIMap(), and LoadCreatureEventAI_Scripts().
m_CreatureEventAIEventGuidMap
std::shared_ptr<CreatureEventAI_Event_Map> CreatureEventAIMgr::m_CreatureEventAIEventGuidMap private
Definition at line 43 of file CreatureEventAIMgr.h.
Referenced by CheckUnusedAISummons(), GetCreatureEventGuidAIMap(), and LoadCreatureEventAI_Scripts().
The documentation for this class was generated from the following files:
CreatureEventAIMgr.h
CreatureEventAIMgr.cpp