CMaNGOS_WoTLK: Log Class Reference
Log Class Reference
#include <Log.h>
Public Member Functions
void Initialize ()
void InitColors (const std::string &str)
void outCommand (uint32 account, const char *str,...) ATTR_PRINTF(3
void void outString ()
void outString (const char *str,...) ATTR_PRINTF(2
void void outError (const char *err,...) ATTR_PRINTF(2
void void void outBasic (const char *str,...) ATTR_PRINTF(2
void void void void outDetail (const char *str,...) ATTR_PRINTF(2
void void void void void outDebug (const char *str,...) ATTR_PRINTF(2
void void void void void void outErrorDb ()
void outErrorDb (const char *err,...) ATTR_PRINTF(2
void void outChar (const char *str,...) ATTR_PRINTF(2
void void void outErrorEventAI ()
void outErrorEventAI (const char *err,...) ATTR_PRINTF(2
void void outErrorScriptLib ()
void outErrorScriptLib (const char *err,...) ATTR_PRINTF(2
void void outWorldPacketDump (const char *socket, uint32 opcode, char const *opcodeName, ByteBuffer const &packet, bool incoming)
void outCharDump (const char *str, uint32 account_id, uint32 guid, const char *name)
void outRALog (const char *str,...) ATTR_PRINTF(2
void void outCustomLog (const char *str,...) ATTR_PRINTF(2
void void uint32 GetLogLevel () const
void SetLogLevel (char *level)
void SetLogFileLevel (char *level)
void SetColor (bool stdout_stream, Color color)
void ResetColor (bool stdout_stream)
void outTime () const
bool HasLogFilter (uint32 filter) const
void SetLogFilter (LogFilters filter, bool on)
bool HasLogLevelOrHigher (LogLevel loglvl) const
bool IsOutCharDump () const
bool IsIncludeTime () const
std::string GetTraceLog ()
void setScriptLibraryErrorFile (char const *fname, char const *libName)
void traceLog ()
Static Public Member Functions
static void outTimestamp (FILE *file)
static std::string GetTimestampStr ()
static void WaitBeforeContinueIfNeed ()
Static Public Member Functions inherited from MaNGOS::Singleton< Log, MaNGOS::ClassLevelLockable< Log, std::mutex > >
static Log & Instance ()
Private Member Functions
Log ()
~Log ()
FILE * openLogFile (char const *configFileName, char const *configTimeStampFlag, char const *mode)
FILE * openGmlogPerAccount (uint32 account)
Private Attributes
FILE * raLogfile
FILE * logfile
FILE * gmLogfile
FILE * charLogfile
FILE * dberLogfile
FILE * eventAiErLogfile
FILE * scriptErrLogFile
FILE * worldLogfile
FILE * customLogFile
std::mutex m_worldLogMtx
std::mutex m_traceLogMtx
LogLevel m_logLevel
LogLevel m_logFileLevel
bool m_colored
bool m_includeTime
Color m_colors [4]
uint32 m_logFilter
std::string m_logsDir
std::string m_logsTimestamp
bool m_charLog_Dump
bool m_gmlog_per_account
std::string m_gmlog_filename_format
char const * m_scriptLibName
Friends
class MaNGOS::OperatorNew< Log >
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Singleton< Log, MaNGOS::ClassLevelLockable< Log, std::mutex > >
Singleton ()
Detailed Description
Definition at line 96 of file Log.h.
Constructor & Destructor Documentation
Log()
Log::Log () private
Definition at line 71 of file Log.cpp.
References Initialize().
~Log()
Log::~Log () inline private
Definition at line 101 of file Log.h.
References charLogfile, customLogFile, dberLogfile, eventAiErLogfile, gmLogfile, logfile, raLogfile, scriptErrLogFile, and worldLogfile.
Member Function Documentation
GetLogLevel()
void void uint32 Log::GetLogLevel () const inline
Definition at line 175 of file Log.h.
References m_logLevel.
GetTimestampStr()
std::string Log::GetTimestampStr () static
Definition at line 346 of file Log.cpp.
Referenced by Initialize().
GetTraceLog()
std::string Log::GetTraceLog ()
Definition at line 1124 of file Log.cpp.
References m_traceLogMtx.
Referenced by traceLog().
HasLogFilter()
bool Log::HasLogFilter (uint32 filter) const inline
Definition at line 183 of file Log.h.
References m_logFilter.
HasLogLevelOrHigher()
bool Log::HasLogLevelOrHigher (LogLevel loglvl) const inline
Definition at line 185 of file Log.h.
References logfile, m_logFileLevel, and m_logLevel.
InitColors()
void Log::InitColors (const std::string & str)
Definition at line 78 of file Log.cpp.
References Color_count, LogType_count, m_colored, and m_colors.
Referenced by Initialize().
Initialize()
void Log::Initialize ()
Common log files data
Open specific log files
Definition at line 221 of file Log.cpp.
References charLogfile, LogFilterData::configName, customLogFile, dberLogfile, LogFilterData::defaultState, eventAiErLogfile, GetTimestampStr(), gmLogfile, InitColors(), LOG_FILTER_COUNT, logfile, logFilterData, m_charLog_Dump, m_gmlog_filename_format, m_gmlog_per_account, m_includeTime, m_logFileLevel, m_logFilter, m_logLevel, m_logsDir, m_logsTimestamp, openLogFile(), raLogfile, sConfig, scriptErrLogFile, and worldLogfile.
Referenced by Log().
IsIncludeTime()
bool Log::IsIncludeTime () const inline
Definition at line 187 of file Log.h.
References m_includeTime.
IsOutCharDump()
bool Log::IsOutCharDump () const inline
Definition at line 186 of file Log.h.
References m_charLog_Dump.
openGmlogPerAccount()
FILE * Log::openGmlogPerAccount (uint32 account) private
Definition at line 310 of file Log.cpp.
References m_gmlog_filename_format, and MANGOS_PATH_MAX.
Referenced by outCommand().
openLogFile()
FILE * Log::openLogFile (char const * configFileName, char const * configTimeStampFlag, char const * mode) private
Definition at line 292 of file Log.cpp.
References m_logsDir, m_logsTimestamp, and sConfig.
Referenced by Initialize().
outBasic()
void Log::outBasic (const char * str, ...)
Definition at line 614 of file Log.cpp.
References LOG_LVL_BASIC, LogDetails, logfile, m_colored, m_colors, m_includeTime, m_logFileLevel, m_logLevel, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outChar()
void Log::outChar (const char * str, ...)
Definition at line 798 of file Log.cpp.
References charLogfile, m_worldLogMtx, and outTimestamp().
outCharDump()
void Log::outCharDump (const char * str, uint32 account_id, uint32 guid, const char * name)
Definition at line 925 of file Log.cpp.
References charLogfile, and m_worldLogMtx.
outCommand()
void Log::outCommand (uint32 account, const char * str, ...)
Definition at line 735 of file Log.cpp.
References gmLogfile, LOG_LVL_DETAIL, LogDetails, logfile, m_colored, m_colors, m_gmlog_per_account, m_includeTime, m_logFileLevel, m_logLevel, m_worldLogMtx, openGmlogPerAccount(), outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outCustomLog()
void Log::outCustomLog (const char * str, ...)
Definition at line 956 of file Log.cpp.
References customLogFile, m_worldLogMtx, and outTimestamp().
outDebug()
void Log::outDebug (const char * str, ...)
Definition at line 694 of file Log.cpp.
References LOG_LVL_DEBUG, LogDebug, logfile, m_colored, m_colors, m_includeTime, m_logFileLevel, m_logLevel, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outDetail()
void Log::outDetail (const char * str, ...)
Definition at line 653 of file Log.cpp.
References LOG_LVL_DETAIL, LogDetails, logfile, m_colored, m_colors, m_includeTime, m_logFileLevel, m_logLevel, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outError()
void Log::outError (const char * err, ...)
Definition at line 418 of file Log.cpp.
References LogError, logfile, m_colored, m_colors, m_includeTime, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outErrorDb() [1/2]
void Log::outErrorDb ()
Definition at line 457 of file Log.cpp.
References dberLogfile, logfile, m_includeTime, m_worldLogMtx, outTime(), and outTimestamp().
outErrorDb() [2/2]
void Log::outErrorDb (const char * err, ...)
Definition at line 483 of file Log.cpp.
References dberLogfile, LogError, logfile, m_colored, m_colors, m_includeTime, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outErrorEventAI() [1/2]
void Log::outErrorEventAI ()
Definition at line 536 of file Log.cpp.
References eventAiErLogfile, logfile, m_includeTime, m_worldLogMtx, outTime(), and outTimestamp().
outErrorEventAI() [2/2]
void Log::outErrorEventAI (const char * err, ...)
Definition at line 562 of file Log.cpp.
References eventAiErLogfile, LogError, logfile, m_colored, m_colors, m_includeTime, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outErrorScriptLib() [1/2]
void Log::outErrorScriptLib ()
Definition at line 816 of file Log.cpp.
References logfile, m_includeTime, m_scriptLibName, m_worldLogMtx, outTime(), outTimestamp(), and scriptErrLogFile.
outErrorScriptLib() [2/2]
void Log::outErrorScriptLib (const char * err, ...)
Definition at line 844 of file Log.cpp.
References LogError, logfile, m_colored, m_colors, m_includeTime, m_scriptLibName, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), scriptErrLogFile, SetColor(), and vutf8printf().
outRALog()
void Log::outRALog (const char * str, ...)
Definition at line 936 of file Log.cpp.
References m_worldLogMtx, outTimestamp(), and raLogfile.
outString() [1/2]
void Log::outString ()
Definition at line 363 of file Log.cpp.
References logfile, m_includeTime, m_worldLogMtx, outTime(), and outTimestamp().
outString() [2/2]
void Log::outString (const char * str, ...)
Definition at line 379 of file Log.cpp.
References logfile, LogNormal, m_colored, m_colors, m_includeTime, m_worldLogMtx, outTime(), outTimestamp(), ResetColor(), SetColor(), and vutf8printf().
outTime()
void Log::outTime () const
Definition at line 333 of file Log.cpp.
Referenced by outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
outTimestamp()
void Log::outTimestamp (FILE * file) static
Definition at line 320 of file Log.cpp.
Referenced by outBasic(), outChar(), outCommand(), outCustomLog(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), outRALog(), outString(), and outWorldPacketDump().
outWorldPacketDump()
void Log::outWorldPacketDump (const char * socket, uint32 opcode, char const * opcodeName, ByteBuffer const & packet, bool incoming)
Definition at line 899 of file Log.cpp.
References m_worldLogMtx, outTimestamp(), ByteBuffer::size(), and worldLogfile.
ResetColor()
void Log::ResetColor (bool stdout_stream)
Definition at line 183 of file Log.cpp.
Referenced by outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
SetColor()
void Log::SetColor (bool stdout_stream, Color color)
Definition at line 107 of file Log.cpp.
References Color_count, and YELLOW.
Referenced by outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
SetLogFileLevel()
void Log::SetLogFileLevel (char * level)
Definition at line 207 of file Log.cpp.
References LOG_LVL_DEBUG, LOG_LVL_MINIMAL, and m_logFileLevel.
SetLogFilter()
void Log::SetLogFilter (LogFilters filter, bool on) inline
Definition at line 184 of file Log.h.
References m_logFilter.
SetLogLevel()
void Log::SetLogLevel (char * level)
Definition at line 193 of file Log.cpp.
References LOG_LVL_DEBUG, LOG_LVL_MINIMAL, and m_logLevel.
setScriptLibraryErrorFile()
void Log::setScriptLibraryErrorFile (char const * fname, char const * libName)
Definition at line 999 of file Log.cpp.
References m_logsDir, m_scriptLibName, and scriptErrLogFile.
traceLog()
void Log::traceLog ()
Definition at line 1111 of file Log.cpp.
References customLogFile, GetTraceLog(), and m_worldLogMtx.
WaitBeforeContinueIfNeed()
void Log::WaitBeforeContinueIfNeed () static
Definition at line 976 of file Log.cpp.
References sConfig, and BarGoLink::step().
Referenced by DatabaseMysql::DatabaseMysql(), World::DetectDBCLang(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), World::LoadConfigSettings(), LoadDBCStores(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPlayerInfo(), main(), Master::Run(), and World::SetInitialWorldSettings().
Friends And Related Function Documentation
MaNGOS::OperatorNew< Log >
friend class MaNGOS::OperatorNew< Log > friend
Definition at line 70 of file Log.h.
Field Documentation
charLogfile
FILE* Log::charLogfile private
Definition at line 204 of file Log.h.
Referenced by Initialize(), outChar(), outCharDump(), and ~Log().
customLogFile
FILE* Log::customLogFile private
Definition at line 209 of file Log.h.
Referenced by Initialize(), outCustomLog(), traceLog(), and ~Log().
dberLogfile
FILE* Log::dberLogfile private
Definition at line 205 of file Log.h.
Referenced by Initialize(), outErrorDb(), and ~Log().
eventAiErLogfile
FILE* Log::eventAiErLogfile private
Definition at line 206 of file Log.h.
Referenced by Initialize(), outErrorEventAI(), and ~Log().
gmLogfile
FILE* Log::gmLogfile private
Definition at line 203 of file Log.h.
Referenced by Initialize(), outCommand(), and ~Log().
logfile
FILE* Log::logfile private
Definition at line 202 of file Log.h.
Referenced by HasLogLevelOrHigher(), Initialize(), outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), outString(), and ~Log().
m_charLog_Dump
bool Log::m_charLog_Dump private
Definition at line 227 of file Log.h.
Referenced by Initialize(), and IsOutCharDump().
m_colored
bool Log::m_colored private
Definition at line 217 of file Log.h.
Referenced by InitColors(), outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
m_colors
Color Log::m_colors[4] private
Definition at line 219 of file Log.h.
Referenced by InitColors(), outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
m_gmlog_filename_format
std::string Log::m_gmlog_filename_format private
Definition at line 231 of file Log.h.
Referenced by Initialize(), and openGmlogPerAccount().
m_gmlog_per_account
bool Log::m_gmlog_per_account private
Definition at line 230 of file Log.h.
Referenced by Initialize(), and outCommand().
m_includeTime
bool Log::m_includeTime private
Definition at line 218 of file Log.h.
Referenced by Initialize(), IsIncludeTime(), outBasic(), outCommand(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), and outString().
m_logFileLevel
LogLevel Log::m_logFileLevel private
Definition at line 216 of file Log.h.
Referenced by HasLogLevelOrHigher(), Initialize(), outBasic(), outCommand(), outDebug(), outDetail(), and SetLogFileLevel().
m_logFilter
uint32 Log::m_logFilter private
Definition at line 220 of file Log.h.
Referenced by HasLogFilter(), Initialize(), and SetLogFilter().
m_logLevel
LogLevel Log::m_logLevel private
Definition at line 215 of file Log.h.
Referenced by GetLogLevel(), HasLogLevelOrHigher(), Initialize(), outBasic(), outCommand(), outDebug(), outDetail(), and SetLogLevel().
m_logsDir
std::string Log::m_logsDir private
Definition at line 223 of file Log.h.
Referenced by Initialize(), openLogFile(), and setScriptLibraryErrorFile().
m_logsTimestamp
std::string Log::m_logsTimestamp private
Definition at line 224 of file Log.h.
Referenced by Initialize(), and openLogFile().
m_scriptLibName
char const* Log::m_scriptLibName private
Definition at line 233 of file Log.h.
Referenced by outErrorScriptLib(), and setScriptLibraryErrorFile().
m_traceLogMtx
std::mutex Log::m_traceLogMtx private
Definition at line 212 of file Log.h.
Referenced by GetTraceLog().
m_worldLogMtx
std::mutex Log::m_worldLogMtx private
Definition at line 211 of file Log.h.
Referenced by outBasic(), outChar(), outCharDump(), outCommand(), outCustomLog(), outDebug(), outDetail(), outError(), outErrorDb(), outErrorEventAI(), outErrorScriptLib(), outRALog(), outString(), outWorldPacketDump(), and traceLog().
raLogfile
FILE* Log::raLogfile private
Definition at line 201 of file Log.h.
Referenced by Initialize(), outRALog(), and ~Log().
scriptErrLogFile
FILE* Log::scriptErrLogFile private
Definition at line 207 of file Log.h.
Referenced by Initialize(), outErrorScriptLib(), setScriptLibraryErrorFile(), and ~Log().
worldLogfile
FILE* Log::worldLogfile private
Definition at line 208 of file Log.h.
Referenced by Initialize(), outWorldPacketDump(), and ~Log().
The documentation for this class was generated from the following files:
Log.h
Log.cpp