CMaNGOS_WoTLK: NamreebAnticheat::Antispam Class Reference
NamreebAnticheat::Antispam Class Reference
#include <antispam.hpp>
Public Member Functions
Antispam (uint32 account)
uint32 GetBlacklistCount () const
uint32 GetAccount () const
std::string GetInfo () const
void AutoReply (const std::string &msg)
void Whisper (const std::string &msg, const ObjectGuid &to)
void Say (const std::string &msg)
void Yell (const std::string &msg)
void Channel (const std::string &msg)
void Mail (const std::string &subject, const std::string &body, const ObjectGuid &to)
void ChannelInvite (const std::string &channelName, const ObjectGuid &to)
void PartyInvite (const ObjectGuid &to)
void Analyze ()
Private Member Functions
uint32 Total () const
float Rate () const
void Notify (const char *format,...)
void Silence (const char *format,...)
void NewMessage (const std::string &msg)
float GetDistanceTraveled () const
uint32 RepetitionScore () const
Private Attributes
const uint32 _account
const uint32 _creationTime
std::mutex _mutex
uint32 _whisperCount
uint32 _sayCount
uint32 _yellCount
uint32 _channelCount
uint32 _mailCount
uint32 _channelInviteCount
uint32 _partyInviteCount
std::unordered_set< ObjectGuid > _whisperTargets
std::unordered_set< ObjectGuid > _mailTargets
std::unordered_set< ObjectGuid > _channelInviteTargets
std::unordered_set< ObjectGuid > _partyInviteTargets
std::vector< std::string > _pendingMessages
nam::cyclic< std::string, 10 > _recentMessages
std::vector< std::pair< uint32, std::string > > _uniqueMessages
nam::priority< std::string, uint32, 5 > _topBlacklistedMessages
uint32 _blacklistCount
uint32 _lastNotification
Detailed Description
Definition at line 35 of file antispam.hpp.
Constructor & Destructor Documentation
Antispam()
NamreebAnticheat::Antispam::Antispam (uint32 account)
Definition at line 210 of file antispam.cpp.
Member Function Documentation
Analyze()
void NamreebAnticheat::Antispam::Analyze ()
Definition at line 412 of file antispam.cpp.
References _account, _blacklistCount, _channelInviteCount, _channelInviteTargets, _creationTime, _mailCount, _mailTargets, _mutex, _partyInviteCount, _partyInviteTargets, _pendingMessages, _recentMessages, _topBlacklistedMessages, _uniqueMessages, _whisperCount, _whisperTargets, nam::damerau_levenshtein_distance(), WorldTimer::getMSTime(), IN_MILLISECONDS, nam::priority< T, P, N >::insert(), MINUTE, Notify(), nam::cyclic< T, N >::push_back(), Rate(), RepetitionScore(), sAnticheatConfig, sAntispamMgr, Silence(), and Total().
AutoReply()
void NamreebAnticheat::Antispam::AutoReply (const std::string & msg)
Definition at line 269 of file antispam.cpp.
References _mutex, and NewMessage().
Channel()
void NamreebAnticheat::Antispam::Channel (const std::string & msg)
Definition at line 301 of file antispam.cpp.
References _channelCount, _mutex, and NewMessage().
ChannelInvite()
void NamreebAnticheat::Antispam::ChannelInvite (const std::string & channelName, const ObjectGuid & to)
Definition at line 321 of file antispam.cpp.
References _channelInviteCount, _channelInviteTargets, _mutex, and NewMessage().
GetAccount()
uint32 NamreebAnticheat::Antispam::GetAccount () const inline
Definition at line 100 of file antispam.hpp.
References _account.
GetBlacklistCount()
uint32 NamreebAnticheat::Antispam::GetBlacklistCount () const inline
Definition at line 99 of file antispam.hpp.
References _blacklistCount.
GetDistanceTraveled()
float NamreebAnticheat::Antispam::GetDistanceTraveled () const private
Definition at line 346 of file antispam.cpp.
References _account, NamreebAnticheat::SessionAnticheat::GetDistanceTraveled(), WorldTimer::getMSTime(), IN_MILLISECONDS, sAnticheatConfig, and sWorld.
Referenced by GetInfo(), and RepetitionScore().
GetInfo()
std::string NamreebAnticheat::Antispam::GetInfo () const
Definition at line 214 of file antispam.cpp.
References _account, _blacklistCount, _channelCount, _channelInviteCount, _channelInviteTargets, _creationTime, _mailCount, _mailTargets, _mutex, _partyInviteCount, _partyInviteTargets, _sayCount, _uniqueMessages, _whisperCount, _whisperTargets, _yellCount, nam::damerau_levenshtein_distance(), GetDistanceTraveled(), WorldTimer::getMSTime(), IN_MILLISECONDS, MINUTE, Rate(), RepetitionScore(), sAntispamMgr, sWorld, and Total().
Mail()
void NamreebAnticheat::Antispam::Mail (const std::string & subject, const std::string & body, const ObjectGuid & to)
Definition at line 310 of file antispam.cpp.
References _mailCount, _mailTargets, _mutex, and NewMessage().
NewMessage()
void NamreebAnticheat::Antispam::NewMessage (const std::string & msg) private
Definition at line 339 of file antispam.cpp.
References _pendingMessages, and sAntispamMgr.
Referenced by AutoReply(), Channel(), ChannelInvite(), Mail(), Say(), Whisper(), and Yell().
Notify()
void NamreebAnticheat::Antispam::Notify (const char * format, ...) private
Definition at line 64 of file antispam.cpp.
References _account, _lastNotification, _recentMessages, _topBlacklistedMessages, ACCOUNT_FLAG_SHOW_ANTISPAM, SqlStatement::addUInt32(), Database::BeginTransaction(), Database::CommitTransaction(), Database::CreateStatement(), WorldTimer::getMSTime(), IN_MILLISECONDS, LANG_GM_ANNOUNCE_COLOR, LogsDatabase, MINUTE, realmID, sAnticheatConfig, sAntispamMgr, and sWorld.
Referenced by Analyze().
PartyInvite()
void NamreebAnticheat::Antispam::PartyInvite (const ObjectGuid & to)
Definition at line 331 of file antispam.cpp.
References _mutex, _partyInviteCount, and _partyInviteTargets.
Rate()
float NamreebAnticheat::Antispam::Rate () const private
Definition at line 52 of file antispam.cpp.
References _creationTime, WorldTimer::getMSTime(), IN_MILLISECONDS, MINUTE, sAnticheatConfig, and Total().
Referenced by Analyze(), and GetInfo().
RepetitionScore()
uint32 NamreebAnticheat::Antispam::RepetitionScore () const private
Definition at line 372 of file antispam.cpp.
References _creationTime, _uniqueMessages, GetDistanceTraveled(), WorldTimer::getMSTime(), IN_MILLISECONDS, and sAnticheatConfig.
Referenced by Analyze(), and GetInfo().
Say()
void NamreebAnticheat::Antispam::Say (const std::string & msg)
Definition at line 285 of file antispam.cpp.
References _mutex, _sayCount, and NewMessage().
Silence()
void NamreebAnticheat::Antispam::Silence (const char * format, ...) private
Definition at line 137 of file antispam.cpp.
References _account, _recentMessages, _topBlacklistedMessages, ACCOUNT_FLAG_SHOW_ANTISPAM, SqlStatement::addUInt32(), Database::BeginTransaction(), Database::CommitTransaction(), Database::CreateStatement(), LANG_GM_ANNOUNCE_COLOR, LogsDatabase, realmID, sAnticheatConfig, sAntispamMgr, and sWorld.
Referenced by Analyze().
Total()
uint32 NamreebAnticheat::Antispam::Total () const inline private
Definition at line 76 of file antispam.hpp.
References _channelCount, _channelInviteCount, _mailCount, _sayCount, _whisperCount, and _yellCount.
Referenced by Analyze(), GetInfo(), and Rate().
Whisper()
void NamreebAnticheat::Antispam::Whisper (const std::string & msg, const ObjectGuid & to)
Definition at line 276 of file antispam.cpp.
References _mutex, _whisperCount, _whisperTargets, and NewMessage().
Yell()
void NamreebAnticheat::Antispam::Yell (const std::string & msg)
Definition at line 293 of file antispam.cpp.
References _mutex, _yellCount, and NewMessage().
Field Documentation
_account
const uint32 NamreebAnticheat::Antispam::_account private
Definition at line 38 of file antispam.hpp.
Referenced by Analyze(), GetAccount(), GetDistanceTraveled(), GetInfo(), Notify(), and Silence().
_blacklistCount
uint32 NamreebAnticheat::Antispam::_blacklistCount private
Definition at line 70 of file antispam.hpp.
Referenced by Analyze(), GetBlacklistCount(), and GetInfo().
_channelCount
uint32 NamreebAnticheat::Antispam::_channelCount private
Definition at line 46 of file antispam.hpp.
Referenced by Channel(), GetInfo(), and Total().
_channelInviteCount
uint32 NamreebAnticheat::Antispam::_channelInviteCount private
Definition at line 48 of file antispam.hpp.
Referenced by Analyze(), ChannelInvite(), GetInfo(), and Total().
_channelInviteTargets
std::unordered_set<ObjectGuid> NamreebAnticheat::Antispam::_channelInviteTargets private
Definition at line 53 of file antispam.hpp.
Referenced by Analyze(), ChannelInvite(), and GetInfo().
_creationTime
const uint32 NamreebAnticheat::Antispam::_creationTime private
Definition at line 39 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), Rate(), and RepetitionScore().
_lastNotification
uint32 NamreebAnticheat::Antispam::_lastNotification private
Definition at line 73 of file antispam.hpp.
Referenced by Notify().
_mailCount
uint32 NamreebAnticheat::Antispam::_mailCount private
Definition at line 47 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), Mail(), and Total().
_mailTargets
std::unordered_set<ObjectGuid> NamreebAnticheat::Antispam::_mailTargets private
Definition at line 52 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), and Mail().
_mutex
std::mutex NamreebAnticheat::Antispam::_mutex mutable private
Definition at line 41 of file antispam.hpp.
Referenced by Analyze(), AutoReply(), Channel(), ChannelInvite(), GetInfo(), Mail(), PartyInvite(), Say(), Whisper(), and Yell().
_partyInviteCount
uint32 NamreebAnticheat::Antispam::_partyInviteCount private
Definition at line 49 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), and PartyInvite().
_partyInviteTargets
std::unordered_set<ObjectGuid> NamreebAnticheat::Antispam::_partyInviteTargets private
Definition at line 54 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), and PartyInvite().
_pendingMessages
std::vector<std::string> NamreebAnticheat::Antispam::_pendingMessages private
Definition at line 57 of file antispam.hpp.
Referenced by Analyze(), and NewMessage().
_recentMessages
nam::cyclic<std::string, 10> NamreebAnticheat::Antispam::_recentMessages private
Definition at line 60 of file antispam.hpp.
Referenced by Analyze(), Notify(), and Silence().
_sayCount
uint32 NamreebAnticheat::Antispam::_sayCount private
Definition at line 44 of file antispam.hpp.
Referenced by GetInfo(), Say(), and Total().
_topBlacklistedMessages
nam::priority<std::string, uint32, 5> NamreebAnticheat::Antispam::_topBlacklistedMessages private
Definition at line 67 of file antispam.hpp.
Referenced by Analyze(), Notify(), and Silence().
_uniqueMessages
std::vector<std::pair<uint32, std::string> > NamreebAnticheat::Antispam::_uniqueMessages private
Definition at line 63 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), and RepetitionScore().
_whisperCount
uint32 NamreebAnticheat::Antispam::_whisperCount private
Definition at line 43 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), Total(), and Whisper().
_whisperTargets
std::unordered_set<ObjectGuid> NamreebAnticheat::Antispam::_whisperTargets private
Definition at line 51 of file antispam.hpp.
Referenced by Analyze(), GetInfo(), and Whisper().
_yellCount
uint32 NamreebAnticheat::Antispam::_yellCount private
Definition at line 45 of file antispam.hpp.
Referenced by GetInfo(), Total(), and Yell().
The documentation for this class was generated from the following files:
antispam.hpp
antispam.cpp