CMaNGOS_WoTLK: instance_halls_of_reflection Class Reference
instance_halls_of_reflection Class Reference
#include <halls_of_reflection.h>
Public Member Functions
instance_halls_of_reflection (Map *pMap)
~instance_halls_of_reflection ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDespawn (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnPlayerEnter (Player *pPlayer) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
uint32 GetPlayerTeam () const
const char * Save () const override
void Load (const char *chrIn) override
void GetDungeonTrapsGUIDList (GuidList &lList) const
void GetReflectionsGUIDList (GuidList &lList) const
void Update (uint32 uiDiff)
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoCleanupFrostmourneEvent ()
void DoSendNextSpiritWave ()
void DoSetupEscapeEvent (Player *pPlayer)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiTeam
uint32 m_uiEventTimer
uint32 m_uiActivateTimer
uint32 m_uiEscapeResetTimer
uint32 m_uiShipUpdateTimer
uint32 m_uiSummonDelayTimer
uint8 m_uiEventStage
GuidList m_lRisenSpiritsGuids
GuidList m_lActiveSpiritsGuids
GuidList m_lDungeonTrapsGuids
GuidList m_lSpiritReflectionsGuids
GuidList m_lGunshipStairsAllyGuids
GuidList m_lGunshipStairsHordeGuids
GuidList m_lIceWallGuids
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Detailed Description
Definition at line 119 of file halls_of_reflection.h.
Constructor & Destructor Documentation
instance_halls_of_reflection()
instance_halls_of_reflection::instance_halls_of_reflection (Map * pMap)
Definition at line 62 of file halls_of_reflection.cpp.
References Initialize().
~instance_halls_of_reflection()
instance_halls_of_reflection::~instance_halls_of_reflection () inline
Definition at line 123 of file halls_of_reflection.h.
Member Function Documentation
DoCleanupFrostmourneEvent()
void instance_halls_of_reflection::DoCleanupFrostmourneEvent () protected
Definition at line 505 of file halls_of_reflection.cpp.
References DONE, ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_ICECROWN_DOOR_ENTRANCE, InstanceData::instance, m_lActiveSpiritsGuids, m_lRisenSpiritsGuids, m_uiEventTimer, NPC_FALRIC, NPC_MARWYN, TYPE_FALRIC, and WORLD_STATE_SPIRIT_WAVES.
Referenced by SetData().
DoSendNextSpiritWave()
void instance_halls_of_reflection::DoSendNextSpiritWave () protected
Definition at line 428 of file halls_of_reflection.cpp.
References ScriptedInstance::DoUpdateWorldState(), Map::GetCreature(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_lActiveSpiritsGuids, m_lRisenSpiritsGuids, m_uiActivateTimer, m_uiEventStage, m_uiEventTimer, NPC_FALRIC, NPC_MARWYN, script_error_log(), SPELL_SPIRIT_ACTIVATE_VISUAL, TRIGGERED_NONE, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_UNINTERACTIBLE, urand(), WORLD_STATE_SPIRIT_WAVES, and WORLD_STATE_SPIRIT_WAVES_COUNT.
Referenced by Update().
DoSetupEscapeEvent()
void instance_halls_of_reflection::DoSetupEscapeEvent (Player * pPlayer) protected
Definition at line 539 of file halls_of_reflection.cpp.
References aEventKingLocations, HORDE, m_uiTeam, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by OnPlayerEnter(), SetData(), and Update().
ExecuteChatCommand()
void instance_halls_of_reflection::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 677 of file halls_of_reflection.cpp.
References ChatHandler::ExtractLiteralArg(), Map::GetTransport(), GO_STATE_ACTIVE, GO_TRANSPORT_OGRIMS_HAMMER, GO_TRANSPORT_SKYBREAKER, HIGHGUID_MO_TRANSPORT, and InstanceData::instance.
GetData()
uint32 instance_halls_of_reflection::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 332 of file halls_of_reflection.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_queldelar_start(), AreaTrigger_at_wrath_lich_king(), DoCleanupFrostmourneEvent(), and OnPlayerEnter().
GetDungeonTrapsGUIDList()
void instance_halls_of_reflection::GetDungeonTrapsGUIDList (GuidList & lList) const inline
Definition at line 145 of file halls_of_reflection.h.
References m_lDungeonTrapsGuids.
Referenced by AreaTrigger_at_frostworn_general().
GetPlayerTeam()
uint32 instance_halls_of_reflection::GetPlayerTeam () const inline
Definition at line 140 of file halls_of_reflection.h.
References m_uiTeam.
Referenced by boss_lich_king_horAI::MovementInform(), boss_lich_king_horAI::ReceiveAIEvent(), and boss_lich_king_horAI::SummonedCreatureJustDied().
GetReflectionsGUIDList()
void instance_halls_of_reflection::GetReflectionsGUIDList (GuidList & lList) const inline
Definition at line 146 of file halls_of_reflection.h.
References m_lSpiritReflectionsGuids.
Referenced by EffectDummyCreature_spell_summon_reflections().
Initialize()
void instance_halls_of_reflection::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 74 of file halls_of_reflection.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_halls_of_reflection().
JustDidDialogueStep()
void instance_halls_of_reflection::JustDidDialogueStep (int32) override protected virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 398 of file halls_of_reflection.cpp.
References afUtherSpawnLoc, ALLIANCE, ScriptedInstance::GetSingleCreatureFromStorage(), m_uiTeam, NPC_FROSTMOURNE_ALTAR_BUNNY, NPC_JAINA_PART2, NPC_LICH_KING, NPC_SYLVANAS_PART2, NPC_UTHER, SAY_ALLY_INTRO_2, SPELL_DARK_BINDING, SPELL_FINDING_JAINA_CREDIT, SPELL_FINDING_SYLVANAS_CREDIT, SPELL_ICE_PRISON, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Load()
void instance_halls_of_reflection::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 309 of file halls_of_reflection.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_halls_of_reflection::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 122 of file halls_of_reflection.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), m_auiEncounter, m_lDungeonTrapsGuids, m_lRisenSpiritsGuids, m_lSpiritReflectionsGuids, ScriptedInstance::m_npcEntryGuidStore, NPC_DUNGEON_TRAP_STALKER, NPC_FALRIC, NPC_FROSTMOURNE_ALTAR_BUNNY, NPC_FROSTSWORN_GENERAL, NPC_GHOSTLY_PRIEST, NPC_JAINA_PART1, NPC_JAINA_PART2, NPC_LICH_KING, NPC_MARWYN, NPC_PHANTOM_MAGE, NPC_SHADOWY_MERCENARY, NPC_SPECTRAL_FOOTMAN, NPC_SPIRITUAL_REFLECTION_1, NPC_SPIRITUAL_REFLECTION_2, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, NPC_TORTURED_RIFLEMAN, NPC_UTHER, SetData(), SPECIAL, TYPE_FALRIC, and TYPE_MARWYN.
OnCreatureDeath()
void instance_halls_of_reflection::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 340 of file halls_of_reflection.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), m_lActiveSpiritsGuids, m_uiEventTimer, NPC_FALRIC, NPC_FROSTSWORN_GENERAL, NPC_GHOSTLY_PRIEST, NPC_MARWYN, NPC_PHANTOM_MAGE, NPC_QUEL_DELAR, NPC_SHADOWY_MERCENARY, NPC_SPECTRAL_FOOTMAN, NPC_TORTURED_RIFLEMAN, SetData(), TYPE_FALRIC, TYPE_FROSTWORN_GENERAL, TYPE_MARWYN, and TYPE_QUEL_DELAR.
OnCreatureDespawn()
void instance_halls_of_reflection::OnCreatureDespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 383 of file halls_of_reflection.cpp.
References DONE, Object::GetEntry(), NPC_LICH_KING_INTRO, SetData(), and TYPE_FROSTMOURNE_INTRO.
OnCreatureEnterCombat()
void instance_halls_of_reflection::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 389 of file halls_of_reflection.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_FALRIC, NPC_MARWYN, SetData(), TYPE_FALRIC, and TYPE_MARWYN.
OnCreatureEvade()
void instance_halls_of_reflection::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 360 of file halls_of_reflection.cpp.
References FAIL, Object::GetEntry(), Unit::HasAuraType(), m_uiEventStage, NPC_FALRIC, NPC_FROSTSWORN_GENERAL, NPC_GHOSTLY_PRIEST, NPC_MARWYN, NPC_PHANTOM_MAGE, NPC_SHADOWY_MERCENARY, NPC_SPECTRAL_FOOTMAN, NPC_TORTURED_RIFLEMAN, SetData(), SPELL_AURA_MOD_INVISIBILITY, TYPE_FALRIC, TYPE_FROSTWORN_GENERAL, and TYPE_MARWYN.
OnObjectCreate()
void instance_halls_of_reflection::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 165 of file halls_of_reflection.cpp.
References GameObject::Delete(), DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_CAPTAIN_CHEST_ALLIANCE, GO_CAPTAIN_CHEST_ALLIANCE_H, GO_CAPTAIN_CHEST_HORDE, GO_CAPTAIN_CHEST_HORDE_H, GO_FROSTMOURNE, GO_FROSTMOURNE_ALTAR, GO_GUNSHIP_STAIRS_A, GO_GUNSHIP_STAIRS_H, GO_ICE_WALL, GO_ICECROWN_DOOR_ENTRANCE, GO_ICECROWN_DOOR_LK_ENTRANCE, GO_ICECROWN_DOOR_LK_EXIT, GO_IMPENETRABLE_DOOR, GO_STATE_ACTIVE, GO_TRANSPORT_OGRIMS_HAMMER, GO_TRANSPORT_SKYBREAKER, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_lGunshipStairsAllyGuids, m_lGunshipStairsHordeGuids, m_lIceWallGuids, GameObject::SetGoState(), TYPE_FROSTMOURNE_INTRO, and TYPE_MARWYN.
OnPlayerEnter()
void instance_halls_of_reflection::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 80 of file halls_of_reflection.cpp.
References afGeneralSpawnLoc, ALLIANCE, DONE, DoSetupEscapeEvent(), GetData(), MotionMaster::getLastReachedWaypoint(), Unit::GetMotionMaster(), Player::GetQuestStatus(), ScriptedInstance::GetSingleCreatureFromStorage(), Player::GetTeam(), Unit::HasAura(), HORDE, m_uiSummonDelayTimer, m_uiTeam, NOT_STARTED, NPC_FROSTMOURNE_ALTAR_BUNNY, NPC_FROSTSWORN_GENERAL, NPC_LICH_KING, NPC_SYLVANAS_PART1, NPC_SYLVANAS_PART2, NPC_UTHER, QUEST_ID_HALLS_REFLECTION_ALLY, QUEST_ID_HALLS_REFLECTION_HORDE, QUEST_STATUS_INCOMPLETE, SetData(), DialogueHelper::SetDialogueSide(), SPECIAL, SPELL_QUELDELAR_COMPULSION, SPELL_START_HALLS_REFLECTION, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_FROSTMOURNE_INTRO, TYPE_FROSTWORN_GENERAL, TYPE_MARWYN, and TYPE_QUEL_DELAR.
Save()
const char* instance_halls_of_reflection::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 142 of file halls_of_reflection.h.
References m_strInstData.
SetData()
void instance_halls_of_reflection::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 204 of file halls_of_reflection.cpp.
References afGeneralSpawnLoc, ALLIANCE, DoCleanupFrostmourneEvent(), DONE, DoSetupEscapeEvent(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), FAIL, ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetTransport(), GO_ICECROWN_DOOR_ENTRANCE, GO_IMPENETRABLE_DOOR, GO_STATE_ACTIVE, GO_TRANSPORT_OGRIMS_HAMMER, GO_TRANSPORT_SKYBREAKER, HIGHGUID_MO_TRANSPORT, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_strInstData, m_uiEscapeResetTimer, m_uiEventStage, m_uiEventTimer, m_uiShipUpdateTimer, m_uiTeam, NPC_FROSTMOURNE_ALTAR_BUNNY, NPC_FROSTSWORN_GENERAL, NPC_JAINA_PART2, NPC_SYLVANAS_PART2, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_ALLY_INTRO_1, SPECIAL, DialogueHelper::StartNextDialogueText(), TEMPSPAWN_DEAD_DESPAWN, TYPE_FALRIC, TYPE_FROSTMOURNE_INTRO, TYPE_FROSTWORN_GENERAL, TYPE_LICH_KING, TYPE_MARWYN, TYPE_QUEL_DELAR, and WORLD_STATE_SPIRIT_WAVES.
Referenced by AreaTrigger_at_frostworn_general(), AreaTrigger_at_queldelar_start(), AreaTrigger_at_wrath_lich_king(), boss_lich_king_horAI::MoveInLineOfSight(), boss_lich_king_horAI::MovementInform(), OnCreatureCreate(), OnCreatureDeath(), OnCreatureDespawn(), OnCreatureEnterCombat(), OnCreatureEvade(), and OnPlayerEnter().
Update()
void instance_halls_of_reflection::Update (uint32 uiDiff) virtual
Reimplemented from InstanceData.
Definition at line 550 of file halls_of_reflection.cpp.
References aEventBeginLocations, ALLIANCE, DialogueHelper::DialogueUpdate(), ScriptedInstance::DoRespawnGameObject(), DoSendNextSpiritWave(), DoSetupEscapeEvent(), ScriptedInstance::DoToggleGameObjectFlags(), Map::GetCreature(), Map::GetGameObject(), ScriptedInstance::GetPlayerInMap(), Map::GetTransport(), GO_CAPTAIN_CHEST_ALLIANCE, GO_CAPTAIN_CHEST_ALLIANCE_H, GO_CAPTAIN_CHEST_HORDE, GO_CAPTAIN_CHEST_HORDE_H, GO_FLAG_NO_INTERACT, GO_STATE_ACTIVE, GO_TRANSPORT_OGRIMS_HAMMER, GO_TRANSPORT_SKYBREAKER, HIGHGUID_MO_TRANSPORT, HORDE, InstanceData::instance, Map::IsRegularDifficulty(), m_lActiveSpiritsGuids, m_lGunshipStairsAllyGuids, m_lGunshipStairsHordeGuids, m_lIceWallGuids, m_uiActivateTimer, m_uiEscapeResetTimer, m_uiEventStage, m_uiEventTimer, m_uiShipUpdateTimer, m_uiSummonDelayTimer, m_uiTeam, MINUTE, script_error_log(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Field Documentation
m_auiEncounter
uint32 instance_halls_of_reflection::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 158 of file halls_of_reflection.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), and SetData().
m_lActiveSpiritsGuids
GuidList instance_halls_of_reflection::m_lActiveSpiritsGuids protected
Definition at line 170 of file halls_of_reflection.h.
Referenced by DoCleanupFrostmourneEvent(), DoSendNextSpiritWave(), OnCreatureDeath(), and Update().
m_lDungeonTrapsGuids
GuidList instance_halls_of_reflection::m_lDungeonTrapsGuids protected
Definition at line 171 of file halls_of_reflection.h.
Referenced by GetDungeonTrapsGUIDList(), and OnCreatureCreate().
m_lGunshipStairsAllyGuids
GuidList instance_halls_of_reflection::m_lGunshipStairsAllyGuids protected
Definition at line 173 of file halls_of_reflection.h.
Referenced by OnObjectCreate(), and Update().
m_lGunshipStairsHordeGuids
GuidList instance_halls_of_reflection::m_lGunshipStairsHordeGuids protected
Definition at line 174 of file halls_of_reflection.h.
Referenced by OnObjectCreate(), and Update().
m_lIceWallGuids
GuidList instance_halls_of_reflection::m_lIceWallGuids protected
Definition at line 175 of file halls_of_reflection.h.
Referenced by OnObjectCreate(), and Update().
m_lRisenSpiritsGuids
GuidList instance_halls_of_reflection::m_lRisenSpiritsGuids protected
Definition at line 169 of file halls_of_reflection.h.
Referenced by DoCleanupFrostmourneEvent(), DoSendNextSpiritWave(), and OnCreatureCreate().
m_lSpiritReflectionsGuids
GuidList instance_halls_of_reflection::m_lSpiritReflectionsGuids protected
Definition at line 172 of file halls_of_reflection.h.
Referenced by GetReflectionsGUIDList(), and OnCreatureCreate().
m_strInstData
std::string instance_halls_of_reflection::m_strInstData protected
Definition at line 159 of file halls_of_reflection.h.
Referenced by Save(), and SetData().
m_uiActivateTimer
uint32 instance_halls_of_reflection::m_uiActivateTimer protected
Definition at line 163 of file halls_of_reflection.h.
Referenced by DoSendNextSpiritWave(), and Update().
m_uiEscapeResetTimer
uint32 instance_halls_of_reflection::m_uiEscapeResetTimer protected
Definition at line 164 of file halls_of_reflection.h.
Referenced by SetData(), and Update().
m_uiEventStage
uint8 instance_halls_of_reflection::m_uiEventStage protected
Definition at line 167 of file halls_of_reflection.h.
Referenced by DoSendNextSpiritWave(), OnCreatureEvade(), SetData(), and Update().
m_uiEventTimer
uint32 instance_halls_of_reflection::m_uiEventTimer protected
Definition at line 162 of file halls_of_reflection.h.
Referenced by DoCleanupFrostmourneEvent(), DoSendNextSpiritWave(), OnCreatureDeath(), SetData(), and Update().
m_uiShipUpdateTimer
uint32 instance_halls_of_reflection::m_uiShipUpdateTimer protected
Definition at line 165 of file halls_of_reflection.h.
Referenced by SetData(), and Update().
m_uiSummonDelayTimer
uint32 instance_halls_of_reflection::m_uiSummonDelayTimer protected
Definition at line 166 of file halls_of_reflection.h.
Referenced by OnPlayerEnter(), and Update().
m_uiTeam
uint32 instance_halls_of_reflection::m_uiTeam protected
Definition at line 161 of file halls_of_reflection.h.
Referenced by DoSetupEscapeEvent(), GetPlayerTeam(), JustDidDialogueStep(), OnPlayerEnter(), SetData(), and Update().
The documentation for this class was generated from the following files:
halls_of_reflection.h
halls_of_reflection.cpp