CMaNGOS_WoTLK: MapManager Class Reference
MapManager Class Reference
#include <MapManager.h>
Public Types
typedef std::map< MapID, Map * > MapMapType
typedef std::map< uint32, std::vector< const TransportTemplate * > > TransportMap
Public Member Functions
void CreateContinents ()
Map * CreateMap (uint32, const WorldObject *obj)
Map * CreateBgMap (uint32 mapid, BattleGround *bg)
Map * FindMap (uint32 mapid, uint32 instanceId=0) const
void UpdateGridState (grid_state_t state, Map &map, NGridType &ngrid, GridInfo &ginfo, const uint32 &x, const uint32 &y, const uint32 &t_diff)
void DeleteInstance (uint32 mapid, uint32 instanceId)
void Initialize ()
void Update (uint32)
void SetGridCleanUpDelay (uint32 t)
void SetMapUpdateInterval (uint32 t)
void UnloadAll ()
void RemoveAllObjectsInRemoveList ()
void LoadTransports ()
void InitializeVisibilityDistanceInfo ()
uint32 GetNumInstances ()
uint32 GetNumPlayersInInstances ()
const MapMapType & Maps () const
template<typename Do >
void DoForAllMaps (Do &_do)
template<typename Do >
void DoForAllMapsWithMapId (uint32 mapId, Do &_do)
template<typename Check >
WorldObject * SearchOnAllLoadedMap (Check &check)
void DoForAllMaps (const std::function< void(Map *)> &worker)
void DoForAllMapsWithMapId (uint32 mapId, std::function< void(Map *)> worker)
Static Public Member Functions
static bool ExistMapAndVMap (uint32 mapid, float x, float y)
static bool IsValidMAP (uint32 mapid)
static bool IsValidMapCoord (uint32 mapid, float x, float y)
static bool IsValidMapCoord (uint32 mapid, float x, float y, float z)
static bool IsValidMapCoord (uint32 mapid, float x, float y, float z, float o)
static bool IsValidMapCoord (WorldLocation const &loc)
static float NormalizeOrientation (float o)
Static Public Member Functions inherited from MaNGOS::Singleton< MapManager, MaNGOS::ClassLevelLockable< MapManager, std::recursive_mutex > >
static MapManager & Instance ()
Data Fields
TransportMap m_transportsByMap
TransportMap m_transportsByEntry
Private Types
typedef std::recursive_mutex LOCK_TYPE
typedef std::lock_guard< LOCK_TYPE > LOCK_TYPE_GUARD
typedef MaNGOS::ClassLevelLockable< MapManager, std::recursive_mutex >::Lock Guard
Private Member Functions
MapManager ()
~MapManager ()
MapManager (const MapManager &)
MapManager & operator= (const MapManager &)
void InitStateMachine ()
void DeleteStateMachine ()
Map * CreateInstance (uint32 id, Player *player)
DungeonMap * CreateDungeonMap (uint32 id, uint32 InstanceId, Difficulty difficulty, DungeonPersistentState *save, Team ownerTeam)
BattleGroundMap * CreateBattleGroundMap (uint32 id, uint32 InstanceId, BattleGround *bg)
Private Attributes
GridState * si_GridStates [MAX_GRID_STATE]
int i_GridStateErrorCount
std::mutex m_lock
uint32 i_gridCleanUpDelay
MapMapType i_maps
IntervalTimer i_timer
MapUpdater m_updater
Friends
class MaNGOS::OperatorNew< MapManager >
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Singleton< MapManager, MaNGOS::ClassLevelLockable< MapManager, std::recursive_mutex > >
Singleton ()
Detailed Description
Definition at line 55 of file MapManager.h.
Member Typedef Documentation
Guard
typedef MaNGOS::ClassLevelLockable<MapManager, std::recursive_mutex>::Lock MapManager::Guard private
Definition at line 61 of file MapManager.h.
LOCK_TYPE
typedef std::recursive_mutex MapManager::LOCK_TYPE private
Definition at line 59 of file MapManager.h.
LOCK_TYPE_GUARD
typedef std::lock_guard<LOCK_TYPE> MapManager::LOCK_TYPE_GUARD private
Definition at line 60 of file MapManager.h.
MapMapType
typedef std::map<MapID, Map* > MapManager::MapMapType
Definition at line 64 of file MapManager.h.
TransportMap
typedef std::map<uint32, std::vector<const TransportTemplate*> > MapManager::TransportMap
Definition at line 140 of file MapManager.h.
Constructor & Destructor Documentation
MapManager() [1/2]
MapManager::MapManager () private
Definition at line 36 of file MapManager.cpp.
References CONFIG_UINT32_INTERVAL_MAPUPDATE, i_timer, IntervalTimer::SetInterval(), and sWorld.
~MapManager()
MapManager::~MapManager () private
Definition at line 42 of file MapManager.cpp.
References DeleteStateMachine(), and i_maps.
MapManager() [2/2]
MapManager::MapManager (const MapManager &) private
Member Function Documentation
CreateBattleGroundMap()
BattleGroundMap * MapManager::CreateBattleGroundMap (uint32 id, uint32 InstanceId, BattleGround * bg) private
Definition at line 379 of file MapManager.cpp.
References DEBUG_LOG, PvPDifficultyEntry::difficulty, GetBattlegroundBracketByLevel(), BattleGround::GetMapId(), BattleGround::GetMinLevel(), BattleGround::GetTypeId(), i_gridCleanUpDelay, i_maps, BattleGroundMap::Initialize(), Map::IsBattleGroundOrArena(), MANGOS_ASSERT, REGULAR_DIFFICULTY, BattleGroundMap::SetBG(), and BattleGround::SetBgMap().
Referenced by CreateBgMap().
CreateBgMap()
Map * MapManager::CreateBgMap (uint32 mapid, BattleGround * bg)
Definition at line 148 of file MapManager.cpp.
References CreateBattleGroundMap(), sObjectMgr, and sTerrainMgr.
CreateContinents()
void MapManager::CreateContinents ()
Definition at line 91 of file MapManager.cpp.
References i_gridCleanUpDelay, i_maps, and Map::Initialize().
Referenced by Initialize().
CreateDungeonMap()
DungeonMap * MapManager::CreateDungeonMap (uint32 id, uint32 InstanceId, Difficulty difficulty, DungeonPersistentState * save, Team ownerTeam) private
Definition at line 347 of file MapManager.cpp.
References DEBUG_LOG, DUNGEON_DIFFICULTY_NORMAL, ObjectMgr::GetInstanceTemplate(), GetMapDifficultyData(), i_gridCleanUpDelay, Map::Initialize(), MANGOS_ASSERT, DungeonMap::SetInstanceTeam(), sLog, and sMapStore.
Referenced by CreateInstance().
CreateInstance()
Map * MapManager::CreateInstance (uint32 id, Player * player) private
Definition at line 298 of file MapManager.cpp.
References Map::ChangeMapDifficulty(), CreateDungeonMap(), FindMap(), Player::GetBattleGroundId(), Player::GetBoundInstanceSaveForSelfOrGroup(), Map::GetDifficulty(), Player::GetDifficulty(), Group::GetDifficulty(), Player::GetGroup(), Player::GetTeam(), i_maps, MapEntry::IsBattleGroundOrArena(), MapEntry::IsDynamicDifficultyMap(), MapEntry::IsRaid(), MANGOS_ASSERT, sMapStore, and sObjectMgr.
Referenced by CreateMap().
CreateMap()
Map * MapManager::CreateMap (uint32 id, const WorldObject * obj)
Parameters
id - MapId of the to be created map.
obj WorldObject for which the map is to be created. Must be player for Instancable maps.
Definition at line 110 of file MapManager.cpp.
References ALLIANCE, CreateInstance(), FindMap(), Object::GetTypeId(), i_gridCleanUpDelay, i_maps, Map::Initialize(), MapEntry::Instanceable(), Object::IsPlayer(), m_lock, MANGOS_ASSERT, sMapStore, and TYPEID_PLAYER.
DeleteInstance()
void MapManager::DeleteInstance (uint32 mapid, uint32 instanceId)
Definition at line 174 of file MapManager.cpp.
References i_maps, Map::Instanceable(), and Map::UnloadAll().
DeleteStateMachine()
void MapManager::DeleteStateMachine () private
Definition at line 68 of file MapManager.cpp.
References GRID_STATE_ACTIVE, GRID_STATE_IDLE, GRID_STATE_INVALID, GRID_STATE_REMOVAL, and si_GridStates.
Referenced by ~MapManager().
DoForAllMaps() [1/2]
void MapManager::DoForAllMaps (const std::function< void(Map *)> & worker)
Definition at line 409 of file MapManager.cpp.
References i_maps.
DoForAllMaps() [2/2]
template<typename Do > void MapManager::DoForAllMaps (Do & _do) inline
Definition at line 152 of file MapManager.h.
References i_maps.
DoForAllMapsWithMapId() [1/2]
template<typename Do > void MapManager::DoForAllMapsWithMapId (uint32 mapId, Do & _do) inline
Definition at line 194 of file MapManager.h.
References i_maps.
DoForAllMapsWithMapId() [2/2]
void MapManager::DoForAllMapsWithMapId (uint32 mapId, std::function< void(Map *)> worker)
Definition at line 401 of file MapManager.cpp.
References i_maps.
ExistMapAndVMap()
bool MapManager::ExistMapAndVMap (uint32 mapid, float x, float y) static
Definition at line 235 of file MapManager.cpp.
References MaNGOS::ComputeGridPair(), GridMap::ExistMap(), GridMap::ExistVMap(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by World::SetInitialWorldSettings().
FindMap()
Map * MapManager::FindMap (uint32 mapid, uint32 instanceId = 0) const
Definition at line 156 of file MapManager.cpp.
References i_maps.
Referenced by CreateInstance(), and CreateMap().
GetNumInstances()
uint32 MapManager::GetNumInstances ()
Definition at line 269 of file MapManager.cpp.
References i_maps, Map::IsDungeon(), and m_lock.
GetNumPlayersInInstances()
uint32 MapManager::GetNumPlayersInInstances ()
Definition at line 283 of file MapManager.cpp.
References Map::GetPlayers(), LinkedListHead::getSize(), i_maps, Map::IsDungeon(), and m_lock.
Initialize()
void MapManager::Initialize ()
Definition at line 50 of file MapManager.cpp.
References MapUpdater::activate(), CONFIG_UINT32_NUM_MAP_THREADS, CreateContinents(), InitStateMachine(), m_updater, and sWorld.
InitializeVisibilityDistanceInfo()
void MapManager::InitializeVisibilityDistanceInfo ()
Definition at line 85 of file MapManager.cpp.
References i_maps.
InitStateMachine()
void MapManager::InitStateMachine () private
Definition at line 60 of file MapManager.cpp.
References GRID_STATE_ACTIVE, GRID_STATE_IDLE, GRID_STATE_INVALID, GRID_STATE_REMOVAL, and si_GridStates.
Referenced by Initialize().
IsValidMAP()
bool MapManager::IsValidMAP (uint32 mapid) static
Definition at line 245 of file MapManager.cpp.
References ObjectMgr::GetInstanceTemplate(), MapEntry::IsDungeon(), and sMapStore.
Referenced by IsValidMapCoord().
IsValidMapCoord() [1/4]
static bool MapManager::IsValidMapCoord (uint32 mapid, float x, float y) inline static
Definition at line 101 of file MapManager.h.
References IsValidMAP(), and MaNGOS::IsValidMapCoord().
Referenced by Player::_LoadHomeBind(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGoHelper(), ChatHandler::HandleGoXYZCommand(), WorldSession::HandleMoveWorldportAckOpcode(), IsValidMapCoord(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadPlayerInfo(), and Player::TeleportTo().
IsValidMapCoord() [2/4]
static bool MapManager::IsValidMapCoord (uint32 mapid, float x, float y, float z) inline static
Definition at line 106 of file MapManager.h.
References IsValidMAP(), and MaNGOS::IsValidMapCoord().
IsValidMapCoord() [3/4]
static bool MapManager::IsValidMapCoord (uint32 mapid, float x, float y, float z, float o) inline static
Definition at line 111 of file MapManager.h.
References IsValidMAP(), and MaNGOS::IsValidMapCoord().
IsValidMapCoord() [4/4]
static bool MapManager::IsValidMapCoord (WorldLocation const & loc) inline static
Definition at line 116 of file MapManager.h.
References WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, IsValidMapCoord(), WorldLocation::mapid, and WorldLocation::orientation.
LoadTransports()
void MapManager::LoadTransports ()
Definition at line 39 of file Transports.cpp.
References QueryResult::Fetch(), GAMEOBJECT_TYPE_MO_TRANSPORT, Field::GetCppString(), ObjectMgr::GetGameObjectInfo(), QueryResult::GetRowCount(), Field::GetUInt32(), TransportTemplate::keyFrames, m_transportsByEntry, m_transportsByMap, MapEntry::MapID, QueryResult::NextRow(), TransportTemplate::pathTime, Database::Query(), sLog, sMapStore, BarGoLink::step(), sTransportMgr, GameObjectInfo::type, and WorldDatabase.
Maps()
const MapMapType& MapManager::Maps () const inline
Definition at line 150 of file MapManager.h.
References i_maps.
NormalizeOrientation()
static float MapManager::NormalizeOrientation (float o) inline static
Definition at line 122 of file MapManager.h.
References M_PI_F.
Referenced by ChaseMovementGenerator::Backpedal(), VehicleInfo::CalculateBoardingPositionOf(), GenericTransport::CalculatePassengerOffset(), GenericTransport::CalculatePassengerOrientation(), GenericTransport::CalculatePassengerPosition(), ChaseMovementGenerator::FanOut(), TransportMgr::GenerateWaypoints(), MovementInfo::GetOrientationInMotion(), WorldObject::HasInArcAt(), spell_wailing_souls_aura::OnPeriodicDummy(), PeriodicRotate::OnPeriodicTrigger(), SpoutTurning::OnPeriodicTrigger(), npc_frostbiteAI::SpellHit(), Aura::TriggerSpell(), TransportBase::Update(), npc_doomfire_targetingAI::UpdateAI(), and TransportBase::UpdateGlobalPositions().
operator=()
MapManager& MapManager::operator= (const MapManager &) private
RemoveAllObjectsInRemoveList()
void MapManager::RemoveAllObjectsInRemoveList ()
Definition at line 229 of file MapManager.cpp.
References i_maps.
SearchOnAllLoadedMap()
template<typename Check > WorldObject * MapManager::SearchOnAllLoadedMap (Check & check) inline
Definition at line 203 of file MapManager.h.
References i_maps.
SetGridCleanUpDelay()
void MapManager::SetGridCleanUpDelay (uint32 t) inline
Definition at line 79 of file MapManager.h.
References i_gridCleanUpDelay, and MIN_GRID_DELAY.
SetMapUpdateInterval()
void MapManager::SetMapUpdateInterval (uint32 t) inline
Definition at line 87 of file MapManager.h.
References i_timer, MIN_MAP_UPDATE_DELAY, IntervalTimer::Reset(), and IntervalTimer::SetInterval().
UnloadAll()
void MapManager::UnloadAll ()
Definition at line 252 of file MapManager.cpp.
References MapUpdater::activated(), MapUpdater::deactivate(), i_maps, MaNGOS::Singleton< TerrainManager, MaNGOS::ClassLevelLockable< TerrainManager, std::mutex > >::Instance(), m_updater, and TerrainManager::UnloadAll().
Update()
void MapManager::Update (uint32 diff)
Definition at line 192 of file MapManager.cpp.
References MapUpdater::activated(), Map::CanUnload(), IntervalTimer::GetCurrent(), i_maps, i_timer, m_updater, IntervalTimer::Passed(), MapUpdater::schedule_update(), IntervalTimer::SetCurrent(), Map::UnloadAll(), IntervalTimer::Update(), and MapUpdater::wait().
UpdateGridState()
void MapManager::UpdateGridState (grid_state_t state, Map & map, NGridType & ngrid, GridInfo & ginfo, const uint32 & x, const uint32 & y, const uint32 & t_diff)
Definition at line 76 of file MapManager.cpp.
References si_GridStates, and GridState::Update().
Friends And Related Function Documentation
MaNGOS::OperatorNew< MapManager >
friend class MaNGOS::OperatorNew< MapManager > friend
Definition at line 52 of file MapManager.h.
Field Documentation
i_gridCleanUpDelay
uint32 MapManager::i_gridCleanUpDelay private
Definition at line 186 of file MapManager.h.
Referenced by CreateBattleGroundMap(), CreateContinents(), CreateDungeonMap(), CreateMap(), and SetGridCleanUpDelay().
i_GridStateErrorCount
int MapManager::i_GridStateErrorCount private
Definition at line 168 of file MapManager.h.
i_maps
MapMapType MapManager::i_maps private
Definition at line 187 of file MapManager.h.
Referenced by CreateBattleGroundMap(), CreateContinents(), CreateInstance(), CreateMap(), DeleteInstance(), DoForAllMaps(), DoForAllMapsWithMapId(), FindMap(), GetNumInstances(), GetNumPlayersInInstances(), InitializeVisibilityDistanceInfo(), Maps(), RemoveAllObjectsInRemoveList(), SearchOnAllLoadedMap(), UnloadAll(), Update(), and ~MapManager().
i_timer
IntervalTimer MapManager::i_timer private
Definition at line 188 of file MapManager.h.
Referenced by MapManager(), SetMapUpdateInterval(), and Update().
m_lock
std::mutex MapManager::m_lock private
Definition at line 185 of file MapManager.h.
Referenced by CreateMap(), GetNumInstances(), and GetNumPlayersInInstances().
m_transportsByEntry
TransportMap MapManager::m_transportsByEntry
Definition at line 142 of file MapManager.h.
Referenced by LoadTransports().
m_transportsByMap
TransportMap MapManager::m_transportsByMap
Definition at line 141 of file MapManager.h.
Referenced by LoadTransports().
m_updater
MapUpdater MapManager::m_updater private
Definition at line 190 of file MapManager.h.
Referenced by Initialize(), UnloadAll(), and Update().
si_GridStates
GridState* MapManager::si_GridStates[MAX_GRID_STATE] private
Definition at line 167 of file MapManager.h.
Referenced by DeleteStateMachine(), InitStateMachine(), and UpdateGridState().
The documentation for this class was generated from the following files:
MapManager.h
Transports.cpp
MapManager.cpp