CMaNGOS_WoTLK: CreatureGroup Class Reference
CreatureGroup Class Reference
#include <SpawnGroup.h>
Public Member Functions
CreatureGroup (SpawnGroupEntry const &entry, Map &map)
void RemoveObject (WorldObject *wo) override
void TriggerLinkingEvent (uint32 event, Unit *target)
void SetFormationData (FormationEntrySPtr fEntry)
FormationData * GetFormationData ()
FormationEntrySPtr GetFormationEntry () const
virtual void Update () override
virtual CreatureGroup * GetCreatureGroup () override
Map & GetMap ()
void MoveHome ()
void Despawn (uint32 timeMSToDespawn=0, uint32 forcedDespawnTime=0) override
void Despawn (uint32 timeMSToDespawn, bool onlyAlive, uint32 forcedDespawnTime)
bool IsOutOfCombat ()
bool IsEvading ()
Public Member Functions inherited from SpawnGroup
SpawnGroup (SpawnGroupEntry const &entry, Map &map, uint32 typeId)
virtual ~SpawnGroup ()
virtual void AddObject (uint32 dbGuid, uint32 entry)
uint32 GetGuidEntry (uint32 dbGuid) const
uint32 GetEligibleEntry (std::map< uint32, uint32 > &existingEntries, std::map< uint32, uint32 > &minEntries)
virtual void Spawn (bool force)
std::string to_string () const
uint32 GetObjectTypeId () const
void SetEnabled (bool enabled)
SpawnGroupEntry const & GetGroupEntry () const
uint32 GetGroupId () const
bool IsWorldstateConditionSatisfied () const
void RespawnIfInVicinity (Position pos, float range)
Private Member Functions
void ClearRespawnTimes ()
Private Attributes
FormationDataSPtr m_formationData
Additional Inherited Members
Protected Attributes inherited from SpawnGroup
SpawnGroupEntry const & m_entry
Map & m_map
std::map< uint32, uint32 > m_objects
std::map< uint32, uint32 > m_chosenEntries
std::map< uint32, bool > m_chosenSpawns
uint32 m_objectTypeId
bool m_enabled
Detailed Description
Definition at line 73 of file SpawnGroup.h.
Constructor & Destructor Documentation
CreatureGroup()
CreatureGroup::CreatureGroup (SpawnGroupEntry const & entry, Map & map)
Definition at line 393 of file SpawnGroup.cpp.
References SpawnGroupEntry::formationEntry, and m_formationData.
Member Function Documentation
ClearRespawnTimes()
void CreatureGroup::ClearRespawnTimes () private
Definition at line 566 of file SpawnGroup.cpp.
References SpawnGroupEntry::DbGuids, SpawnGroup::GetObjectTypeId(), Map::GetPersistentState(), SpawnGroup::m_entry, SpawnGroup::m_map, and MapPersistentState::SaveObjectRespawnTime().
Referenced by TriggerLinkingEvent().
Despawn() [1/2]
void CreatureGroup::Despawn (uint32 timeMSToDespawn, bool onlyAlive, uint32 forcedDespawnTime)
Definition at line 509 of file SpawnGroup.cpp.
References Map::GetCreature(), SpawnGroup::GetObjectTypeId(), Map::GetPersistentState(), SpawnGroup::m_map, SpawnGroup::m_objects, MapPersistentState::RemoveCreatureFromGrid(), MapPersistentState::SaveObjectRespawnTime(), and sObjectMgr.
Despawn() [2/2]
void CreatureGroup::Despawn (uint32 timeMSToDespawn = 0, uint32 forcedDespawnTime = 0) inline override virtual
Implements SpawnGroup.
Definition at line 92 of file SpawnGroup.h.
References Despawn().
Referenced by Despawn(), and npc_cork_gizeltonAI::MakeQuestFailAndClean().
GetCreatureGroup()
virtual CreatureGroup* CreatureGroup::GetCreatureGroup () inline override virtual
Reimplemented from SpawnGroup.
Definition at line 86 of file SpawnGroup.h.
Referenced by ScriptAction::ExecuteDbscriptCommand().
GetFormationData()
FormationData* CreatureGroup::GetFormationData () inline
Definition at line 81 of file SpawnGroup.h.
References m_formationData.
Referenced by Creature::CleanupsBeforeDelete(), Creature::ClearCreatureGroup(), ScriptAction::ExecuteDbscriptCommand(), FormationSlotData::GetFormationData(), Creature::LoadFromDB(), RemoveObject(), and TriggerLinkingEvent().
GetFormationEntry()
FormationEntrySPtr CreatureGroup::GetFormationEntry () const inline
Definition at line 82 of file SpawnGroup.h.
References SpawnGroupEntry::formationEntry, and SpawnGroup::m_entry.
Referenced by ChatHandler::HandleWpShowCommand().
GetMap()
Map& CreatureGroup::GetMap () inline
Definition at line 88 of file SpawnGroup.h.
References SpawnGroup::m_map.
Referenced by FormationData::Reset().
IsEvading()
bool CreatureGroup::IsEvading ()
Definition at line 550 of file SpawnGroup.cpp.
References Map::GetCreature(), SpawnGroup::m_map, and SpawnGroup::m_objects.
Referenced by TriggerLinkingEvent().
IsOutOfCombat()
bool CreatureGroup::IsOutOfCombat ()
Definition at line 534 of file SpawnGroup.cpp.
References Map::GetCreature(), SpawnGroup::m_map, and SpawnGroup::m_objects.
Referenced by FormationData::OnDeath(), and npc_cork_gizeltonAI::UpdateEscortAI().
MoveHome()
void CreatureGroup::MoveHome ()
Definition at line 496 of file SpawnGroup.cpp.
References FORCED_MOVEMENT_RUN, Map::GetCreature(), Creature::GetRespawnPosition(), SpawnGroup::m_map, and SpawnGroup::m_objects.
Referenced by ScriptAction::ExecuteDbscriptCommand().
RemoveObject()
void CreatureGroup::RemoveObject (WorldObject * wo) override virtual
Reimplemented from SpawnGroup.
Definition at line 401 of file SpawnGroup.cpp.
References Object::GetDbGuid(), GetFormationData(), WorldObject::GetInstanceData(), Map::GetPersistentState(), SpawnGroup::m_map, SpawnGroup::m_objects, InstanceData::OnCreatureGroupDespawn(), MapPersistentState::RemoveCreatureFromGrid(), SpawnGroup::RemoveObject(), FormationData::ResetLastWP(), and sObjectMgr.
Referenced by Creature::ClearCreatureGroup().
SetFormationData()
void CreatureGroup::SetFormationData (FormationEntrySPtr fEntry)
Definition at line 475 of file SpawnGroup.cpp.
References m_formationData.
Referenced by ScriptAction::ExecuteDbscriptCommand().
TriggerLinkingEvent()
void CreatureGroup::TriggerLinkingEvent (uint32 event, Unit * target)
Definition at line 414 of file SpawnGroup.cpp.
References Unit::AddThreat(), ClearRespawnTimes(), CREATURE_GROUP_AGGRO_TOGETHER, CREATURE_GROUP_EVADE_TOGETHER, CREATURE_GROUP_EVENT_AGGRO, CREATURE_GROUP_EVENT_EVADE, CREATURE_GROUP_EVENT_HOME, CREATURE_GROUP_EVENT_MEMBER_DIED, CREATURE_GROUP_EVENT_RESPAWN, CREATURE_GROUP_RESPAWN_TOGETHER, SpawnGroupEntry::Flags, Unit::GetCombatManager(), Map::GetCreature(), GetFormationData(), SpawnManager::GetSpawnGroup(), Map::GetSpawnManager(), IsEvading(), SpawnGroupEntry::LinkedGroups, SpawnGroup::m_entry, SpawnGroup::m_map, SpawnGroup::m_objects, Unit::SetInCombatWith(), CombatManager::TriggerCombatTimer(), and TriggerLinkingEvent().
Referenced by Creature::LoadFromDB(), TriggerLinkingEvent(), and Creature::Update().
Update()
void CreatureGroup::Update () override virtual
Reimplemented from SpawnGroup.
Definition at line 489 of file SpawnGroup.cpp.
References m_formationData, and SpawnGroup::Update().
Field Documentation
m_formationData
FormationDataSPtr CreatureGroup::m_formationData private
Definition at line 100 of file SpawnGroup.h.
Referenced by CreatureGroup(), GetFormationData(), SetFormationData(), and Update().
The documentation for this class was generated from the following files:
SpawnGroup.h
SpawnGroup.cpp