CMaNGOS_WoTLK: FollowMovementGenerator Class Reference
FollowMovementGenerator Class Reference
#include <TargetedMovementGenerator.h>
Public Member Functions
FollowMovementGenerator (Unit &target, float offset, float angle, bool main, bool possess, bool alwaysBoost=false)
~FollowMovementGenerator ()
MovementGeneratorType GetMovementGeneratorType () const override
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
virtual void Interrupt (Unit &owner) override
void Reset (Unit &owner) override
bool GetResetPosition (Unit &owner, float &x, float &y, float &z, float &o) const override
virtual bool EnableWalking () const
bool _lostTarget (Unit &owner) const
void _reachTarget (Unit &owner)
void HandleMovementFailure (Unit &owner) override
virtual bool IsRemovedOnExpire () const override
void MarkMovegen ()
Public Member Functions inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
bool Update (Unit &, const uint32 &)
virtual bool IsReachable () const override
Unit * GetCurrentTarget () const override
float GetOffset () const
float GetAngle () const
virtual void UnitSpeedChanged () override
virtual bool RemoveOnInvalid () const
Public Member Functions inherited from MovementGeneratorMedium< T, D >
bool Update (Unit &u, const uint32 &time_diff) override
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Initialize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Finalize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Interrupt (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Reset (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool Update (U &u, const uint32 &time_diff)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
bool IsActive (Unit &u)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit &target)
void stopFollowing ()
void SetNewTarget (Unit &target)
Protected Member Functions
float GetDynamicTargetDistance (Unit &owner, bool forRangeCheck) const override
void HandleTargetedMovement (Unit &owner, const uint32 &time_diff) override
void HandleFinalizedMovement (Unit &owner) override
bool _hasUnitStateNotMove (Unit &owner) override
void _clearUnitStateMove (Unit &owner) override
void _addUnitStateMove (Unit &owner) override
virtual float GetSpeed (Unit &owner) const
virtual bool IsBoostAllowed (Unit &owner) const
virtual bool IsUnstuckAllowed (Unit &owner) const
virtual bool Move (Unit &owner, float x, float y, float z)
virtual bool _getOrientation (Unit &owner, float &o) const
virtual bool _getLocation (Unit &owner, float &x, float &y, float &z, bool movingNow) const
virtual void _setOrientation (Unit &owner)
virtual void _setLocation (Unit &owner, bool movingNow)
virtual uint32 _getPollRateMultiplier (Unit &owner, bool targetMovingNow, bool targetMovedBefore=true) const
virtual uint32 _getPollRate (Unit &owner, bool movingNow, bool movingBefore=true) const
Protected Member Functions inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
TargetedMovementGeneratorMedium (Unit &target, float offset, float angle)
~TargetedMovementGeneratorMedium ()
virtual bool RequiresNewPosition (Unit &owner, Position pos) const
virtual bool ShouldFaceTarget () const
Static Protected Member Functions
static uint32 _getPollRateBase ()
static uint32 _getPollRateMax ()
Protected Attributes
bool m_main
bool m_possess
bool m_boost
bool m_targetMoving
bool m_targetFaced
Protected Attributes inherited from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >
ShortTimeTracker i_recheckDistance
float i_offset
float i_angle
G3D::Vector3 i_lastTargetPos
bool i_speedChanged
bool i_targetReached
bool i_faceTarget
PathFinder * i_path
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
Definition at line 178 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
FollowMovementGenerator()
FollowMovementGenerator::FollowMovementGenerator (Unit & target, float offset, float angle, bool main, bool possess, bool alwaysBoost = false) inline
Definition at line 181 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_faceTarget.
~FollowMovementGenerator()
FollowMovementGenerator::~FollowMovementGenerator () inline
Definition at line 187 of file TargetedMovementGenerator.h.
Member Function Documentation
_addUnitStateMove()
void FollowMovementGenerator::_addUnitStateMove (Unit & owner) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 703 of file TargetedMovementGenerator.cpp.
References Unit::addUnitState(), and UNIT_STAT_FOLLOW_MOVE.
Referenced by FormationMovementGenerator::_setLocation(), FormationMovementGenerator::HandleMasterDistanceCheck(), and Move().
_clearUnitStateMove()
void FollowMovementGenerator::_clearUnitStateMove (Unit & owner) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 702 of file TargetedMovementGenerator.cpp.
References Unit::clearUnitState(), and UNIT_STAT_FOLLOW_MOVE.
Referenced by HandleMovementFailure(), and Interrupt().
_getLocation()
bool FollowMovementGenerator::_getLocation (Unit & owner, float & x, float & y, float & z, bool movingNow) const protected virtual
Definition at line 942 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::GetAngle(), Unit::GetCollisionHeight(), GetDynamicTargetDistance(), Unit::GetObjectBoundingRadius(), WorldObject::GetPosition(), TargetedMovementGeneratorBase::i_target, and Reference< TO, FROM >::isValid().
Referenced by _setLocation(), GetResetPosition(), and Move().
_getOrientation()
bool FollowMovementGenerator::_getOrientation (Unit & owner, float & o) const protected virtual
Definition at line 933 of file TargetedMovementGenerator.cpp.
References WorldObject::GetAngle(), Reference< TO, FROM >::getTarget(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_faceTarget, TargetedMovementGeneratorBase::i_target, and Reference< TO, FROM >::isValid().
Referenced by _setOrientation(), GetResetPosition(), and Move().
_getPollRate()
uint32 FollowMovementGenerator::_getPollRate (Unit & owner, bool movingNow, bool movingBefore = true) const protected virtual
Definition at line 1030 of file TargetedMovementGenerator.cpp.
References _getPollRateBase(), _getPollRateMax(), _getPollRateMultiplier(), and Unit::GetSpeedRateInMotion().
Referenced by HandleTargetedMovement().
_getPollRateBase()
static uint32 FollowMovementGenerator::_getPollRateBase () inline static protected
Definition at line 231 of file TargetedMovementGenerator.h.
Referenced by _getPollRate().
_getPollRateMax()
static uint32 FollowMovementGenerator::_getPollRateMax () inline static protected
Definition at line 232 of file TargetedMovementGenerator.h.
Referenced by _getPollRate().
_getPollRateMultiplier()
uint32 FollowMovementGenerator::_getPollRateMultiplier (Unit & owner, bool targetMovingNow, bool targetMovedBefore = true) const protected virtual
Definition at line 1024 of file TargetedMovementGenerator.cpp.
References Object::HasFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by _getPollRate().
_hasUnitStateNotMove()
bool FollowMovementGenerator::_hasUnitStateNotMove (Unit & owner) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 701 of file TargetedMovementGenerator.cpp.
References Unit::hasUnitState(), UNIT_STAT_NO_FOLLOW_MOVEMENT, and UNIT_STAT_NOT_MOVE.
Referenced by _setLocation().
_lostTarget()
bool FollowMovementGenerator::_lostTarget (Unit & owner) const
Definition at line 705 of file TargetedMovementGenerator.cpp.
_reachTarget()
void FollowMovementGenerator::_reachTarget (Unit & owner)
Definition at line 710 of file TargetedMovementGenerator.cpp.
Referenced by HandleFinalizedMovement().
_setLocation()
void FollowMovementGenerator::_setLocation (Unit & owner, bool movingNow) protected virtual
Reimplemented in FormationMovementGenerator.
Definition at line 1007 of file TargetedMovementGenerator.cpp.
References _getLocation(), _hasUnitStateNotMove(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_targetReached, Reference< TO, FROM >::isValid(), m_targetFaced, and Move().
Referenced by HandleTargetedMovement().
_setOrientation()
void FollowMovementGenerator::_setOrientation (Unit & owner) protected virtual
Definition at line 994 of file TargetedMovementGenerator.cpp.
References _getOrientation(), m_targetFaced, Unit::SetFacingTo(), and WorldObject::SetOrientation().
Referenced by HandleTargetedMovement().
EnableWalking()
bool FollowMovementGenerator::EnableWalking () const virtual
Definition at line 714 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorBase::i_target, and Reference< TO, FROM >::isValid().
Referenced by FormationMovementGenerator::_setLocation(), and Move().
Finalize()
void FollowMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 812 of file TargetedMovementGenerator.cpp.
References Unit::AI(), Unit::clearUnitState(), TargetedMovementGeneratorBase::i_target, Reference< TO, FROM >::isValid(), UnitAI::RelinquishFollow(), UNIT_STAT_FOLLOW, and UNIT_STAT_FOLLOW_MOVE.
GetDynamicTargetDistance()
float FollowMovementGenerator::GetDynamicTargetDistance (Unit & owner, bool forRangeCheck) const override protected virtual
Reimplemented from TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 1050 of file TargetedMovementGenerator.cpp.
References FOLLOW_DIST_GAP_FOR_DIST_FACTOR, FOLLOW_DIST_RECALCULATE_FACTOR, FOLLOW_RECALCULATE_FACTOR, FOLLOW_RECALCULATE_RANGE, Unit::GetObjectBoundingRadius(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::GetOffset(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_offset, TargetedMovementGeneratorBase::i_target, and RANDOM_MOTION_TYPE.
Referenced by _getLocation().
GetMovementGeneratorType()
MovementGeneratorType FollowMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Reimplemented in FormationMovementGenerator.
Definition at line 189 of file TargetedMovementGenerator.h.
References FOLLOW_MOTION_TYPE.
GetResetPosition()
bool FollowMovementGenerator::GetResetPosition (Unit & owner, float & x, float & y, float & z, float & o) const override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Reimplemented in FormationMovementGenerator.
Definition at line 830 of file TargetedMovementGenerator.cpp.
References _getLocation(), _getOrientation(), WorldObject::GetAngle(), WorldObject::GetTransport(), and m_targetMoving.
GetSpeed()
float FollowMovementGenerator::GetSpeed (Unit & owner) const protected virtual
Definition at line 725 of file TargetedMovementGenerator.cpp.
References DIST_CALC_NONE, WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetSpeed(), Object::HasFlag(), TargetedMovementGeneratorBase::i_target, IsBoostAllowed(), Unit::IsInCombat(), Reference< TO, FROM >::isValid(), m_boost, MOVE_RUN, MOVE_WALK, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by Move().
HandleFinalizedMovement()
void FollowMovementGenerator::HandleFinalizedMovement (Unit & owner) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Reimplemented in FormationMovementGenerator.
Definition at line 1138 of file TargetedMovementGenerator.cpp.
References _reachTarget(), and TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_targetReached.
HandleMovementFailure()
void FollowMovementGenerator::HandleMovementFailure (Unit & owner) override virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 1133 of file TargetedMovementGenerator.cpp.
References _clearUnitStateMove().
HandleTargetedMovement()
void FollowMovementGenerator::HandleTargetedMovement (Unit & owner, const uint32 & time_diff) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Reimplemented in FormationMovementGenerator.
Definition at line 1067 of file TargetedMovementGenerator.cpp.
References _getPollRate(), _setLocation(), _setOrientation(), WorldObject::GetPosition(), WorldObject::GetTransport(), MovementInfo::HasMovementFlag(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_faceTarget, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_recheckDistance, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_targetReached, Unit::IsNoMountedFollow(), WorldObject::m_movementInfo, m_targetFaced, m_targetMoving, MOVEFLAG_BACKWARD, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, MOVEFLAG_MASK_MOVING_FORWARD, MOVEFLAG_PITCH_DOWN, MOVEFLAG_PITCH_UP, ShortTimeTracker::Passed(), RANDOM_MOTION_TYPE, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::RequiresNewPosition(), ShortTimeTracker::Reset(), UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and ShortTimeTracker::Update().
Initialize()
void FollowMovementGenerator::Initialize (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 798 of file TargetedMovementGenerator.cpp.
References Unit::addUnitState(), WorldObject::GetMap(), TargetedMovementGeneratorBase::i_target, Reference< TO, FROM >::isValid(), sLog, and UNIT_STAT_FOLLOW.
Referenced by Reset().
Interrupt()
void FollowMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Reimplemented in FormationMovementGenerator.
Definition at line 819 of file TargetedMovementGenerator.cpp.
References _clearUnitStateMove(), and Unit::InterruptMoving().
Referenced by FormationMovementGenerator::Interrupt().
IsBoostAllowed()
bool FollowMovementGenerator::IsBoostAllowed (Unit & owner) const protected virtual
Definition at line 754 of file TargetedMovementGenerator.cpp.
References WorldObject::GetMapId(), Unit::GetMasterGuid(), WorldObject::GetPosition(), WorldObject::GetTransport(), TargetedMovementGeneratorBase::i_target, Unit::IsInCombat(), Reference< TO, FROM >::isValid(), m_boost, MOVEFLAG_BACKWARD, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::RequiresNewPosition(), and sMapStore.
Referenced by GetSpeed().
IsRemovedOnExpire()
virtual bool FollowMovementGenerator::IsRemovedOnExpire () const inline override virtual
Reimplemented from MovementGenerator.
Definition at line 205 of file TargetedMovementGenerator.h.
References m_main.
IsUnstuckAllowed()
bool FollowMovementGenerator::IsUnstuckAllowed (Unit & owner) const protected virtual
Definition at line 781 of file TargetedMovementGenerator.cpp.
References Unit::GetMasterGuid(), WorldObject::GetPosition(), WorldObject::GetTransport(), TargetedMovementGeneratorBase::i_target, Reference< TO, FROM >::isValid(), MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, MOVEFLAG_FLYING, and TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::RequiresNewPosition().
Referenced by Move().
MarkMovegen()
void FollowMovementGenerator::MarkMovegen ()
Definition at line 719 of file TargetedMovementGenerator.cpp.
References m_main, and m_possess.
Move()
bool FollowMovementGenerator::Move (Unit & owner, float x, float y, float z) protected virtual
Definition at line 845 of file TargetedMovementGenerator.cpp.
References _addUnitStateMove(), _getLocation(), _getOrientation(), PathFinder::calculate(), GenericTransport::CalculatePassengerPosition(), Map::CreatureRelocation(), EnableWalking(), Movement::MoveSpline::Finalized(), Unit::GetCollisionHeight(), WorldObject::GetMap(), PathFinder::getPath(), PathFinder::getPathType(), WorldObject::GetPhaseMask(), GetSpeed(), WorldObject::GetTransport(), Object::GetTypeId(), TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >::i_path, TargetedMovementGeneratorBase::i_target, Map::IsInLineOfSight(), IsUnstuckAllowed(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), Unit::movespline, Unit::NearTeleportTo(), PATHFIND_NOPATH, PATHFIND_SHORTCUT, Unit::SendHeartBeat(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and Unit::UpdateSplinePosition().
Referenced by _setLocation().
Reset()
void FollowMovementGenerator::Reset (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 825 of file TargetedMovementGenerator.cpp.
References Initialize().
Field Documentation
m_boost
bool FollowMovementGenerator::m_boost protected
Definition at line 238 of file TargetedMovementGenerator.h.
Referenced by GetSpeed(), and IsBoostAllowed().
m_main
bool FollowMovementGenerator::m_main protected
Definition at line 236 of file TargetedMovementGenerator.h.
Referenced by IsRemovedOnExpire(), and MarkMovegen().
m_possess
bool FollowMovementGenerator::m_possess protected
Definition at line 237 of file TargetedMovementGenerator.h.
Referenced by MarkMovegen().
m_targetFaced
bool FollowMovementGenerator::m_targetFaced protected
Definition at line 241 of file TargetedMovementGenerator.h.
Referenced by FormationMovementGenerator::_setLocation(), _setLocation(), _setOrientation(), HandleTargetedMovement(), and FormationMovementGenerator::HandleTargetedMovement().
m_targetMoving
bool FollowMovementGenerator::m_targetMoving protected
Definition at line 240 of file TargetedMovementGenerator.h.
Referenced by GetResetPosition(), HandleTargetedMovement(), and FormationMovementGenerator::HandleTargetedMovement().
The documentation for this class was generated from the following files:
TargetedMovementGenerator.h
TargetedMovementGenerator.cpp