CMaNGOS_WoTLK: instance_blackrock_depths Class Reference
instance_blackrock_depths Class Reference
#include <blackrock_depths.h>
Public Member Functions
instance_blackrock_depths (Map *pMap)
~instance_blackrock_depths ()
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void SetArenaCenterCoords (float fX, float fY, float fZ)
void GetArenaCenterCoords (float &fX, float &fY, float &fZ) const
void GetArenaCrowdGuid (GuidSet &sCrowdSet) const
void SetBarDoorIsOpen ()
void GetBarDoorIsOpen (bool &bIsOpen) const
void HandleBarPatrons (uint8 uiEventType)
void HandleBarPatrol (uint8 uiStep)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoCallNextDwarf ()
bool CanReplacePrincess () const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_bIsBarDoorOpen
uint32 m_uiBarAleCount
uint32 m_uiPatronEmoteTimer
uint8 m_uiBrokenKegs
uint32 m_uiPatrolTimer
uint8 m_uiStolenAles
uint32 m_uiDagranTimer
uint8 m_uiCofferDoorsOpened
uint8 m_uiDwarfRound
uint32 m_uiDwarfFightTimer
float m_fArenaCenterX
float m_fArenaCenterY
float m_fArenaCenterZ
GuidSet m_sVaultNpcGuids
GuidSet m_sArenaCrowdNpcGuids
GuidSet m_sBarPatronNpcGuids
GuidSet m_sBarPatrolGuids
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 223 of file blackrock_depths.h.
Constructor & Destructor Documentation
instance_blackrock_depths()
instance_blackrock_depths::instance_blackrock_depths (Map * pMap)
Definition at line 28 of file instance_blackrock_depths.cpp.
References Initialize().
~instance_blackrock_depths()
instance_blackrock_depths::~instance_blackrock_depths () inline
Definition at line 227 of file blackrock_depths.h.
Member Function Documentation
CanReplacePrincess()
bool instance_blackrock_depths::CanReplacePrincess () const private
Definition at line 609 of file instance_blackrock_depths.cpp.
References ALLIANCE, Map::GetPlayers(), HORDE, InstanceData::instance, LinkedListHead::isEmpty(), QUEST_FATE_KINGDOM, and QUEST_ROYAL_RESCUE.
Referenced by OnCreatureCreate().
DoCallNextDwarf()
void instance_blackrock_depths::DoCallNextDwarf () private
Definition at line 594 of file instance_blackrock_depths.cpp.
References aTombDwarfes, FACTION_DWARF_HOSTILE, ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiDwarfFightTimer, m_uiDwarfRound, TEMPFACTION_RESTORE_REACH_HOME, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by OnCreatureDeath(), SetData(), and Update().
GetArenaCenterCoords()
void instance_blackrock_depths::GetArenaCenterCoords (float & fX, float & fY, float & fZ) const inline
Definition at line 250 of file blackrock_depths.h.
References m_fArenaCenterX, m_fArenaCenterY, and m_fArenaCenterZ.
Referenced by npc_grimstoneAI::JustSummoned().
GetArenaCrowdGuid()
void instance_blackrock_depths::GetArenaCrowdGuid (GuidSet & sCrowdSet) const inline
Definition at line 252 of file blackrock_depths.h.
References m_sArenaCrowdNpcGuids.
Referenced by npc_grimstoneAI::UpdateEscortAI().
GetBarDoorIsOpen()
void instance_blackrock_depths::GetBarDoorIsOpen (bool & bIsOpen) const inline
Definition at line 256 of file blackrock_depths.h.
References m_bIsBarDoorOpen.
Referenced by npc_rocknotAI::UpdateEscortAI(), and npc_rocknotAI::WaypointReached().
GetData()
uint32 instance_blackrock_depths::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 414 of file instance_blackrock_depths.cpp.
References IN_PROGRESS, m_auiEncounter, m_uiBarAleCount, SPECIAL, TYPE_BAR, TYPE_BRIDGE, TYPE_FLAMELASH, TYPE_HURLEY, TYPE_IRON_HALL, TYPE_LYCEUM, TYPE_NAGMARA, TYPE_PLUGGER, TYPE_QUEST_JAIL_BREAK, TYPE_RING_OF_LAW, TYPE_ROCKNOT, TYPE_TOMB_OF_SEVEN, and TYPE_VAULT.
Referenced by EffectDummyCreature_spell_banner_of_provocation(), HandleBarPatrol(), HandleBarPatrons(), OnCreatureDeath(), OnCreatureEvade(), OnObjectCreate(), Update(), npc_grimstoneAI::UpdateEscortAI(), npc_rocknotAI::UpdateEscortAI(), npc_marshal_windsorAI::UpdateEscortAI(), npc_phalanxAI::WaypointReached(), and npc_rocknotAI::WaypointReached().
HandleBarPatrol()
void instance_blackrock_depths::HandleBarPatrol (uint8 uiStep)
Definition at line 703 of file instance_blackrock_depths.cpp.
References aBarPatrolId, aBarPatrolPositions, DONE, DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_BAR_DOOR, InstanceData::instance, m_bIsBarDoorOpen, m_sBarPatrolGuids, m_uiPatrolTimer, NPC_FIREGUARD_DESTROYER, NPC_PLUGGER_SPAZZRING, SetBarDoorIsOpen(), SetData(), SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_BAR, YELL_PATROL_1, and YELL_PATROL_2.
Referenced by SetData(), and Update().
HandleBarPatrons()
void instance_blackrock_depths::HandleBarPatrons (uint8 uiEventType)
Definition at line 629 of file instance_blackrock_depths.cpp.
References aPatronsEmotes, DONE, DoScriptText(), EMOTE_ONESHOT_NONE, FACTION_DARK_IRON, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_BAR_KEG_SHOT, InstanceData::instance, m_sBarPatronNpcGuids, NPC_MISTRESS_NAGMARA, NPC_PRIVATE_ROCKNOT, PATRON_EMOTE, PATRON_HOSTILE, PATRON_PISSED, SAY_PISSED_PATRON_1, SAY_PISSED_PATRON_2, SAY_PISSED_PATRON_3, SAY_ROCKNOT_DESPAWN, SPELL_NAGMARA_VANISH, TEMPFACTION_RESTORE_RESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_PLUGGER, UNIT_STAND_STATE_STAND, and urand().
Referenced by boss_plugger_spazzringAI::JustDied(), SetData(), and Update().
Initialize()
void instance_blackrock_depths::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 47 of file instance_blackrock_depths.cpp.
References m_auiEncounter.
Referenced by instance_blackrock_depths().
Load()
void instance_blackrock_depths::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 453 of file instance_blackrock_depths.cpp.
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, and TYPE_IRON_HALL.
OnCreatureCreate()
void instance_blackrock_depths::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 58 of file instance_blackrock_depths.cpp.
References aArenaCrowdVolume, aVaultPositions, CanReplacePrincess(), Unit::CastSpell(), DONE, FACTION_ARENA_NEUTRAL, FACTION_DARK_IRON, Creature::ForcedDespawn(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), WorldObject::IsWithinDist2d(), m_auiEncounter, ArenaCylinder::m_fCenterX, ArenaCylinder::m_fCenterY, ArenaCylinder::m_fCenterZ, ScriptedInstance::m_npcEntryGuidStore, m_sArenaCrowdNpcGuids, m_sBarPatronNpcGuids, m_sVaultNpcGuids, ArenaCylinder::m_uiHeight, ArenaCylinder::m_uiRadius, NPC_ANGERREL, NPC_ANVILRAGE_MEDIC, NPC_ANVILRAGE_OFFICER, NPC_ANVILRAGE_SOLDIER, NPC_ARENA_SPECTATOR, NPC_COREN_DIREBREW, NPC_CREST, NPC_DOOMREL, NPC_DOPEREL, NPC_DUGHAL, NPC_EMPEROR, NPC_GLOOMREL, NPC_GRIM_PATRON, NPC_GUZZLING_PATRON, NPC_HAMMERED_PATRON, NPC_HATEREL, NPC_JAZ, NPC_LOREGRAIN, NPC_MAGMUS, NPC_MISTRESS_NAGMARA, NPC_PHALANX, NPC_PLUGGER_SPAZZRING, NPC_PRIESTESS, NPC_PRINCESS, NPC_PRIVATE_ROCKNOT, NPC_RIBBLY_SCREWSPIGGOT, NPC_SEETHREL, NPC_SHADOWFORGE_CITIZEN, NPC_SHADOWFORGE_PEASANT, NPC_SHADOWFORGE_SENATOR, NPC_SHILL, NPC_TOBIAS, NPC_VILEREL, NPC_WARBRINGER_CONST, NPC_WATCHER_DOOMGRIP, Creature::SetFactionTemporary(), Unit::SetStandState(), SPELL_STONED, TEMPFACTION_RESTORE_RESPAWN, TRIGGERED_OLD_TRIGGERED, UNIT_STAND_STATE_STAND, and Creature::UpdateEntry().
OnCreatureDeath()
void instance_blackrock_depths::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 514 of file instance_blackrock_depths.cpp.
References aTombDwarfes, DoCallNextDwarf(), DONE, DoScriptText(), GetData(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_sVaultNpcGuids, m_uiDagranTimer, m_uiDwarfRound, NPC_ANGERREL, NPC_CREST, NPC_DOOMREL, NPC_DOPEREL, NPC_EMPEROR, NPC_GLOOMREL, NPC_HATEREL, NPC_HURLEY_BLACKBREATH, NPC_JAZ, NPC_MAGMUS, NPC_OGRABISI, NPC_RIBBLY_SCREWSPIGGOT, NPC_SEETHREL, NPC_SHADOWFORGE_SENATOR, NPC_SHILL, NPC_VILEREL, NPC_WARBRINGER_CONST, NPC_WATCHER_DOOMGRIP, SetData(), SPECIAL, TYPE_BAR, TYPE_HURLEY, TYPE_IRON_HALL, TYPE_PLUGGER, TYPE_QUEST_JAIL_BREAK, TYPE_TOMB_OF_SEVEN, TYPE_VAULT, urand(), YELL_SENATOR_1, YELL_SENATOR_2, YELL_SENATOR_3, and YELL_SENATOR_4.
OnCreatureEnterCombat()
void instance_blackrock_depths::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 476 of file instance_blackrock_depths.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_MAGMUS, SetData(), and TYPE_IRON_HALL.
OnCreatureEvade()
void instance_blackrock_depths::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 482 of file instance_blackrock_depths.cpp.
References aArenaNPCs, FAIL, GetData(), Object::GetEntry(), IN_PROGRESS, NPC_ANGERREL, NPC_DOOMREL, NPC_DOPEREL, NPC_GLOOMREL, NPC_HATEREL, NPC_MAGMUS, NPC_SEETHREL, NPC_VILEREL, SetData(), SPECIAL, TYPE_IRON_HALL, TYPE_RING_OF_LAW, and TYPE_TOMB_OF_SEVEN.
OnCreatureRespawn()
void instance_blackrock_depths::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 192 of file instance_blackrock_depths.cpp.
References Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_COREN_DIREBREW, and NPC_DIREBREW_MINION.
OnObjectCreate()
void instance_blackrock_depths::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 134 of file instance_blackrock_depths.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), GetData(), Object::GetEntry(), Object::GetObjectGuid(), GO_ARENA_1, GO_ARENA_2, GO_ARENA_3, GO_ARENA_4, GO_ARENA_SPOILS, GO_BAR_DOOR, GO_BAR_KEG_SHOT, GO_BAR_KEG_TRAP, GO_CHEST_SEVEN, GO_DWARFRUNE_A01, GO_DWARFRUNE_B01, GO_DWARFRUNE_C01, GO_DWARFRUNE_D01, GO_DWARFRUNE_E01, GO_DWARFRUNE_F01, GO_DWARFRUNE_G01, GO_GOLEM_ROOM_N, GO_GOLEM_ROOM_S, GO_JAIL_DOOR_SUPPLY, GO_JAIL_SUPPLY_CRATE, GO_LYCEUM, GO_SECRET_DOOR, GO_SECRET_SAFE, GO_SHADOW_DUMMY, GO_SHADOW_GIANT_DOOR, GO_SHADOW_LOCK, GO_SHADOW_MECHANISM, GO_SPECTRAL_CHALICE, GO_STATE_ACTIVE_ALTERNATIVE, GO_THRONE_ROOM, GO_TOMB_ENTER, GO_TOMB_EXIT, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, SetBarDoorIsOpen(), GameObject::SetGoState(), and TYPE_ROCKNOT.
OnPlayerEnter()
void instance_blackrock_depths::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 52 of file instance_blackrock_depths.cpp.
References LFGData::GetDungeon(), Player::GetLfgData(), Map::GetVariableManager(), InstanceData::instance, SEASONAL_COREN_DIREBREW, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_COREN_DIREBREW_DUNGEON.
Save()
const char* instance_blackrock_depths::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 243 of file blackrock_depths.h.
References m_strInstData.
SetArenaCenterCoords()
void instance_blackrock_depths::SetArenaCenterCoords (float fX, float fY, float fZ) inline
Definition at line 249 of file blackrock_depths.h.
References m_fArenaCenterX, m_fArenaCenterY, and m_fArenaCenterZ.
SetBarDoorIsOpen()
void instance_blackrock_depths::SetBarDoorIsOpen () inline
Definition at line 255 of file blackrock_depths.h.
References m_bIsBarDoorOpen.
Referenced by HandleBarPatrol(), OnObjectCreate(), SetData(), and npc_rocknotAI::WaypointReached().
SetData()
void instance_blackrock_depths::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 199 of file instance_blackrock_depths.cpp.
References aHurleyPositions, aTombDwarfes, aVaultPositions, DoCallNextDwarf(), DONE, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FACTION_ARENA_NEUTRAL, FAIL, Map::GetCreature(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_ARENA_SPOILS, GO_CHEST_SEVEN, GO_DWARFRUNE_A01, GO_FLAG_NO_INTERACT, GO_GOLEM_ROOM_N, GO_GOLEM_ROOM_S, GO_SECRET_DOOR, GO_SECRET_SAFE, GO_THRONE_ROOM, GO_TOMB_ENTER, GO_TOMB_EXIT, HandleBarPatrol(), HandleBarPatrons(), HOUR, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_sArenaCrowdNpcGuids, m_strInstData, m_sVaultNpcGuids, m_uiBarAleCount, m_uiBrokenKegs, m_uiCofferDoorsOpened, m_uiDwarfFightTimer, m_uiDwarfRound, m_uiStolenAles, MAX_CRONIES, MAX_DWARF_RUNES, MAX_RELIC_DOORS, NPC_BLACKBREATH_CRONY, NPC_HURLEY_BLACKBREATH, NPC_MAGMUS, NPC_PLUGGER_SPAZZRING, NPC_WATCHER_DOOMGRIP, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, PATRON_PISSED, Unit::RemoveAurasDueToSpell(), InstanceData::SaveToDB(), SetBarDoorIsOpen(), SPECIAL, SPELL_STONED, WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, TEMPSPAWN_DEAD_DESPAWN, TYPE_BAR, TYPE_BRIDGE, TYPE_FLAMELASH, TYPE_HURLEY, TYPE_IRON_HALL, TYPE_LYCEUM, TYPE_NAGMARA, TYPE_PLUGGER, TYPE_QUEST_JAIL_BREAK, TYPE_RING_OF_LAW, TYPE_ROCKNOT, TYPE_TOMB_OF_SEVEN, TYPE_VAULT, and YELL_MAGMUS_INTRO.
Referenced by EffectDummyCreature_spell_banner_of_provocation(), HandleBarPatrol(), boss_plugger_spazzringAI::JustDied(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), npc_mistress_nagmaraAI::UpdateAI(), npc_phalanxAI::UpdateEscortAI(), npc_rocknotAI::UpdateEscortAI(), npc_marshal_windsorAI::UpdateEscortAI(), npc_grimstoneAI::WaypointReached(), npc_phalanxAI::WaypointReached(), and npc_marshal_windsorAI::WaypointReached().
Update()
void instance_blackrock_depths::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 772 of file instance_blackrock_depths.cpp.
References DoCallNextDwarf(), GetData(), HandleBarPatrol(), HandleBarPatrons(), IN_PROGRESS, m_uiDagranTimer, m_uiDwarfFightTimer, m_uiDwarfRound, m_uiPatrolTimer, m_uiPatronEmoteTimer, MAX_DWARFS, PATRON_EMOTE, SPECIAL, and TYPE_BAR.
Field Documentation
m_auiEncounter
uint32 instance_blackrock_depths::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 264 of file blackrock_depths.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), and SetData().
m_bIsBarDoorOpen
bool instance_blackrock_depths::m_bIsBarDoorOpen private
Definition at line 268 of file blackrock_depths.h.
Referenced by GetBarDoorIsOpen(), HandleBarPatrol(), and SetBarDoorIsOpen().
m_fArenaCenterX
float instance_blackrock_depths::m_fArenaCenterX private
Definition at line 281 of file blackrock_depths.h.
Referenced by GetArenaCenterCoords(), and SetArenaCenterCoords().
m_fArenaCenterY
float instance_blackrock_depths::m_fArenaCenterY private
Definition at line 281 of file blackrock_depths.h.
Referenced by GetArenaCenterCoords(), and SetArenaCenterCoords().
m_fArenaCenterZ
float instance_blackrock_depths::m_fArenaCenterZ private
Definition at line 281 of file blackrock_depths.h.
Referenced by GetArenaCenterCoords(), and SetArenaCenterCoords().
m_sArenaCrowdNpcGuids
GuidSet instance_blackrock_depths::m_sArenaCrowdNpcGuids private
Definition at line 284 of file blackrock_depths.h.
Referenced by GetArenaCrowdGuid(), OnCreatureCreate(), and SetData().
m_sBarPatrolGuids
GuidSet instance_blackrock_depths::m_sBarPatrolGuids private
Definition at line 286 of file blackrock_depths.h.
Referenced by HandleBarPatrol().
m_sBarPatronNpcGuids
GuidSet instance_blackrock_depths::m_sBarPatronNpcGuids private
Definition at line 285 of file blackrock_depths.h.
Referenced by HandleBarPatrons(), and OnCreatureCreate().
m_strInstData
std::string instance_blackrock_depths::m_strInstData private
Definition at line 265 of file blackrock_depths.h.
Referenced by Save(), and SetData().
m_sVaultNpcGuids
GuidSet instance_blackrock_depths::m_sVaultNpcGuids private
Definition at line 283 of file blackrock_depths.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and SetData().
m_uiBarAleCount
uint32 instance_blackrock_depths::m_uiBarAleCount private
Definition at line 269 of file blackrock_depths.h.
Referenced by GetData(), and SetData().
m_uiBrokenKegs
uint8 instance_blackrock_depths::m_uiBrokenKegs private
Definition at line 271 of file blackrock_depths.h.
Referenced by SetData().
m_uiCofferDoorsOpened
uint8 instance_blackrock_depths::m_uiCofferDoorsOpened private
Definition at line 276 of file blackrock_depths.h.
Referenced by SetData().
m_uiDagranTimer
uint32 instance_blackrock_depths::m_uiDagranTimer private
Definition at line 274 of file blackrock_depths.h.
Referenced by OnCreatureDeath(), and Update().
m_uiDwarfFightTimer
uint32 instance_blackrock_depths::m_uiDwarfFightTimer private
Definition at line 279 of file blackrock_depths.h.
Referenced by DoCallNextDwarf(), SetData(), and Update().
m_uiDwarfRound
uint8 instance_blackrock_depths::m_uiDwarfRound private
Definition at line 278 of file blackrock_depths.h.
Referenced by DoCallNextDwarf(), OnCreatureDeath(), SetData(), and Update().
m_uiPatrolTimer
uint32 instance_blackrock_depths::m_uiPatrolTimer private
Definition at line 272 of file blackrock_depths.h.
Referenced by HandleBarPatrol(), and Update().
m_uiPatronEmoteTimer
uint32 instance_blackrock_depths::m_uiPatronEmoteTimer private
Definition at line 270 of file blackrock_depths.h.
Referenced by Update().
m_uiStolenAles
uint8 instance_blackrock_depths::m_uiStolenAles private
Definition at line 273 of file blackrock_depths.h.
Referenced by SetData().
The documentation for this class was generated from the following files:
blackrock_depths.h
instance_blackrock_depths.cpp