CMaNGOS_WoTLK: CombatConditionMgr Class Reference
CombatConditionMgr Class Reference
#include <CombatCondition.h>
Public Member Functions
CombatConditionMgr (UnitConditionMgr &unitConditionMgr, WorldStateExpressionMgr &worldStateExpressionMgr)
std::shared_ptr< std::map< int32, CombatConditionEntry > > Load ()
bool Meets (Unit const *self, int32 Id, float range)
std::shared_ptr< std::map< int32, CombatConditionEntry > > Get ()
Private Attributes
std::shared_ptr< std::map< int32, CombatConditionEntry > > m_combatConditions
UnitConditionMgr & m_unitConditionMgr
WorldStateExpressionMgr & m_worldStateExpressionMgr
Detailed Description
Definition at line 46 of file CombatCondition.h.
Constructor & Destructor Documentation
CombatConditionMgr()
CombatConditionMgr::CombatConditionMgr (UnitConditionMgr & unitConditionMgr, WorldStateExpressionMgr & worldStateExpressionMgr)
Definition at line 28 of file CombatCondition.cpp.
Member Function Documentation
Get()
std::shared_ptr<std::map<int32, CombatConditionEntry> > CombatConditionMgr::Get () inline
Definition at line 56 of file CombatCondition.h.
References m_combatConditions.
Load()
std::shared_ptr< std::map< int32, CombatConditionEntry > > CombatConditionMgr::Load ()
Definition at line 33 of file CombatCondition.cpp.
References MaNGOS::Count(), CombatConditionEntry::EnemyConditionCount, CombatConditionEntry::EnemyConditionId, CombatConditionEntry::EnemyConditionLogic, CombatConditionEntry::EnemyConditionOp, UnitConditionMgr::Exists(), WorldStateExpressionMgr::Exists(), CombatConditionEntry::FriendConditionCount, CombatConditionEntry::FriendConditionId, CombatConditionEntry::FriendConditionLogic, CombatConditionEntry::FriendConditionOp, Field::GetUInt32(), CombatConditionEntry::Id, m_combatConditions, m_unitConditionMgr, m_worldStateExpressionMgr, MAX, Database::Query(), CombatConditionEntry::SelfConditionId, sLog, BarGoLink::step(), CombatConditionEntry::TargetConditionId, WorldDatabase, and CombatConditionEntry::WorldStateConditionId.
Meets()
bool CombatConditionMgr::Meets (Unit const * self, int32 Id, float range)
Definition at line 129 of file CombatCondition.cpp.
References AND, ConditionEntry::CheckOp(), CombatConditionEntry::EnemyConditionCount, CombatConditionEntry::EnemyConditionId, CombatConditionEntry::EnemyConditionLogic, CombatConditionEntry::EnemyConditionOp, CombatConditionEntry::FriendConditionCount, CombatConditionEntry::FriendConditionId, CombatConditionEntry::FriendConditionLogic, CombatConditionEntry::FriendConditionOp, m_unitConditionMgr, m_worldStateExpressionMgr, WorldStateExpressionMgr::Meets(), UnitConditionMgr::Meets(), NONE, OR, CombatConditionEntry::SelfConditionId, CombatConditionEntry::TargetConditionId, Cell::VisitGridObjects(), CombatConditionEntry::WorldStateConditionId, and XOR.
Field Documentation
m_combatConditions
std::shared_ptr<std::map<int32, CombatConditionEntry> > CombatConditionMgr::m_combatConditions private
Definition at line 58 of file CombatCondition.h.
Referenced by Get(), and Load().
m_unitConditionMgr
UnitConditionMgr& CombatConditionMgr::m_unitConditionMgr private
Definition at line 59 of file CombatCondition.h.
Referenced by Load(), and Meets().
m_worldStateExpressionMgr
WorldStateExpressionMgr& CombatConditionMgr::m_worldStateExpressionMgr private
Definition at line 60 of file CombatCondition.h.
Referenced by Load(), and Meets().
The documentation for this class was generated from the following files:
CombatCondition.h
CombatCondition.cpp