CMaNGOS_WoTLK: BattleGroundQueue::SelectionPool Class Reference
BattleGroundQueue::SelectionPool Class Reference
Public Member Functions
SelectionPool ()
void Init ()
bool AddGroup (GroupQueueInfo *ginfo, uint32 desiredCount, uint32 bgInstanceId)
Function that adds group to selection pool.
bool KickGroup (uint32 size)
Function that removes group infr from pool selection.
uint32 GetPlayerCount () const
Data Fields
GroupsQueueType selectedGroups
Private Attributes
uint32 playerCount
Detailed Description
Definition at line 119 of file BattleGroundMgr.h.
Constructor & Destructor Documentation
SelectionPool()
BattleGroundQueue::SelectionPool::SelectionPool () inline
Definition at line 122 of file BattleGroundMgr.h.
Member Function Documentation
AddGroup()
bool BattleGroundQueue::SelectionPool::AddGroup (GroupQueueInfo * queueInfo, uint32 desiredCount, uint32 bgInstanceId)
Function that adds group to selection pool.
returns true if we can invite more players, or when we added group to selection pool
returns false when selection pool is full
Parameters
group queue info
desired count
Definition at line 144 of file BattleGroundMgr.cpp.
References GroupQueueInfo::desiredInstanceId, GroupQueueInfo::isInvitedToBgInstanceGuid, and GroupQueueInfo::players.
Referenced by BattleGroundQueue::CheckNormalMatch(), BattleGroundQueue::CheckPremadeMatch(), BattleGroundQueue::CheckSkirmishForSameFaction(), BattleGroundQueue::FillPlayersToBg(), and BattleGroundQueue::Update().
GetPlayerCount()
uint32 BattleGroundQueue::SelectionPool::GetPlayerCount () const inline
Definition at line 126 of file BattleGroundMgr.h.
References playerCount.
Referenced by BattleGroundQueue::CheckNormalMatch(), and BattleGroundQueue::Update().
Init()
void BattleGroundQueue::SelectionPool::Init ()
Definition at line 90 of file BattleGroundMgr.cpp.
References playerCount, and selectedGroups.
Referenced by BattleGroundQueue::CheckSkirmishForSameFaction(), and BattleGroundQueue::Update().
KickGroup()
bool BattleGroundQueue::SelectionPool::KickGroup (uint32 size)
Function that removes group infr from pool selection.
returns true when we need to try to add new group to selection pool
returns false when selection pool is ok or when we kicked smaller group than we need to kick
sometimes it can be called on empty selection pool
Parameters
size
Definition at line 104 of file BattleGroundMgr.cpp.
References GroupQueueInfo::players.
Referenced by BattleGroundQueue::FillPlayersToBg().
Field Documentation
playerCount
uint32 BattleGroundQueue::SelectionPool::playerCount private
Definition at line 129 of file BattleGroundMgr.h.
Referenced by GetPlayerCount(), and Init().
selectedGroups
GroupsQueueType BattleGroundQueue::SelectionPool::selectedGroups
Definition at line 127 of file BattleGroundMgr.h.
Referenced by BattleGroundQueue::CheckSkirmishForSameFaction(), Init(), and BattleGroundQueue::Update().
The documentation for this class was generated from the following files:
BattleGroundMgr.h
BattleGroundMgr.cpp