CMaNGOS_WoTLK: RetreatMovementGenerator Class Reference
RetreatMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
RetreatMovementGenerator (float x, float y, float z, float o, uint32 delay)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
void Reset (Unit &unit) override
bool Update (Unit &unit, const uint32 &diff) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from PointMovementGenerator
PointMovementGenerator (uint32 id, float x, float y, float z, float o, bool generatePath, uint32 forcedMovement, float speed=0.f, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
PointMovementGenerator (uint32 id, float x, float y, float z, bool generatePath, uint32 forcedMovement, float speed=0.f)
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
void MovementInform (Unit &) override
Protected Member Functions inherited from PointMovementGenerator
virtual void Move (Unit &unit)
Private Attributes
ShortTimeTracker m_delayTimer
bool m_arrived
Additional Inherited Members
Protected Attributes inherited from PointMovementGenerator
float m_x
float m_y
float m_z
float m_o
float m_speed
bool m_generatePath
uint32 m_forcedMovement
Detailed Description
Definition at line 59 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
RetreatMovementGenerator()
RetreatMovementGenerator::RetreatMovementGenerator (float x, float y, float z, float o, uint32 delay) inline
Definition at line 62 of file PointMovementGenerator.h.
Member Function Documentation
Finalize()
void RetreatMovementGenerator::Finalize (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 145 of file PointMovementGenerator.cpp.
References Unit::AI(), Unit::clearUnitState(), PointMovementGenerator::Finalize(), and UNIT_STAT_RETREATING.
GetMovementGeneratorType()
MovementGeneratorType RetreatMovementGenerator::GetMovementGeneratorType () const inline override virtual
Reimplemented from PointMovementGenerator.
Definition at line 71 of file PointMovementGenerator.h.
References RETREAT_MOTION_TYPE.
Initialize()
void RetreatMovementGenerator::Initialize (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 130 of file PointMovementGenerator.cpp.
References Unit::addUnitState(), Unit::AI(), PointMovementGenerator::Initialize(), Unit::IsClientControlled(), m_arrived, Unit::SetTarget(), and UNIT_STAT_RETREATING.
Interrupt()
void RetreatMovementGenerator::Interrupt (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 155 of file PointMovementGenerator.cpp.
References Unit::AI(), and PointMovementGenerator::Interrupt().
MovementInform()
void RetreatMovementGenerator::MovementInform (Unit &) inline override protected virtual
Reimplemented from PointMovementGenerator.
Definition at line 74 of file PointMovementGenerator.h.
Reset()
void RetreatMovementGenerator::Reset (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 163 of file PointMovementGenerator.cpp.
References m_arrived, and PointMovementGenerator::Reset().
Update()
bool RetreatMovementGenerator::Update (Unit & unit, const uint32 & diff) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 169 of file PointMovementGenerator.cpp.
References Unit::AI(), m_arrived, m_delayTimer, ShortTimeTracker::Passed(), ShortTimeTracker::Update(), and PointMovementGenerator::Update().
Field Documentation
m_arrived
bool RetreatMovementGenerator::m_arrived private
Definition at line 78 of file PointMovementGenerator.h.
Referenced by Initialize(), Reset(), and Update().
m_delayTimer
ShortTimeTracker RetreatMovementGenerator::m_delayTimer private
Definition at line 77 of file PointMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
PointMovementGenerator.h
PointMovementGenerator.cpp