CMaNGOS_WoTLK: SqlPlainPreparedStatement Class Reference
SqlPlainPreparedStatement Class Reference
#include <SqlPreparedStatement.h>
Public Member Functions
SqlPlainPreparedStatement (const std::string &fmt, SqlConnection &conn)
~SqlPlainPreparedStatement ()
virtual bool prepare () override
virtual void bind (const SqlStmtParameters &holder) override
virtual bool execute () override
Public Member Functions inherited from SqlPreparedStatement
virtual ~SqlPreparedStatement ()
bool isPrepared () const
bool isQuery () const
uint32 params () const
uint32 columns () const
Protected Member Functions
void DataToString (const SqlStmtFieldData &data, std::ostringstream &fmt) const
Protected Member Functions inherited from SqlPreparedStatement
SqlPreparedStatement (const std::string &fmt, SqlConnection &conn)
Protected Attributes
std::string m_szPlainRequest
Protected Attributes inherited from SqlPreparedStatement
uint32 m_nParams
uint32 m_nColumns
bool m_bIsQuery
bool m_bPrepared
std::string m_szFmt
SqlConnection & m_pConn
Detailed Description
Definition at line 333 of file SqlPreparedStatement.h.
Constructor & Destructor Documentation
SqlPlainPreparedStatement()
SqlPlainPreparedStatement::SqlPlainPreparedStatement (const std::string & fmt, SqlConnection & conn)
Definition at line 87 of file SqlPreparedStatement.cpp.
References SqlPreparedStatement::m_bIsQuery, SqlPreparedStatement::m_bPrepared, SqlPreparedStatement::m_nParams, and SqlPreparedStatement::m_szFmt.
~SqlPlainPreparedStatement()
SqlPlainPreparedStatement::~SqlPlainPreparedStatement () inline
Definition at line 337 of file SqlPreparedStatement.h.
Member Function Documentation
bind()
void SqlPlainPreparedStatement::bind (const SqlStmtParameters & holder) override virtual
Implements SqlPreparedStatement.
Definition at line 94 of file SqlPreparedStatement.cpp.
References SqlStmtParameters::boundParams(), DataToString(), SqlPreparedStatement::m_nParams, SqlPreparedStatement::m_szFmt, m_szPlainRequest, MANGOS_ASSERT, and SqlStmtParameters::params().
DataToString()
void SqlPlainPreparedStatement::DataToString (const SqlStmtFieldData & data, std::ostringstream & fmt) const protected
Definition at line 136 of file SqlPreparedStatement.cpp.
References SqlConnection::DB(), Database::escape_string(), FIELD_BOOL, FIELD_DOUBLE, FIELD_FLOAT, FIELD_I16, FIELD_I32, FIELD_I64, FIELD_I8, FIELD_NONE, FIELD_STRING, FIELD_UI16, FIELD_UI32, FIELD_UI64, FIELD_UI8, SqlPreparedStatement::m_pConn, SqlStmtFieldData::toBool(), SqlStmtFieldData::toDouble(), SqlStmtFieldData::toFloat(), SqlStmtFieldData::toInt16(), SqlStmtFieldData::toInt32(), SqlStmtFieldData::toInt64(), SqlStmtFieldData::toInt8(), SqlStmtFieldData::toStr(), SqlStmtFieldData::toUint16(), SqlStmtFieldData::toUint32(), SqlStmtFieldData::toUint64(), SqlStmtFieldData::toUint8(), and SqlStmtFieldData::type().
Referenced by bind().
execute()
bool SqlPlainPreparedStatement::execute () override virtual
Implements SqlPreparedStatement.
Definition at line 128 of file SqlPreparedStatement.cpp.
References SqlConnection::Execute(), SqlPreparedStatement::m_pConn, and m_szPlainRequest.
prepare()
virtual bool SqlPlainPreparedStatement::prepare () inline override virtual
Implements SqlPreparedStatement.
Definition at line 340 of file SqlPreparedStatement.h.
Field Documentation
m_szPlainRequest
std::string SqlPlainPreparedStatement::m_szPlainRequest protected
Definition at line 350 of file SqlPreparedStatement.h.
Referenced by bind(), and execute().
The documentation for this class was generated from the following files:
SqlPreparedStatement.h
SqlPreparedStatement.cpp