CMaNGOS_WoTLK: VMAP::IVMapManager Class Reference
VMAP::IVMapManager Class Reference abstract
#include <IVMapManager.h>
Public Member Functions
IVMapManager ()
virtual ~IVMapManager (void)
virtual VMAPLoadResult loadMap (const char *pBasePath, unsigned int pMapId, int x, int y)=0
virtual bool existsMap (const char *pBasePath, unsigned int pMapId, int x, int y)=0
virtual void unloadMap (unsigned int pMapId, int x, int y)=0
virtual void unloadMap (unsigned int pMapId)=0
virtual bool isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, bool ignoreM2Model)=0
virtual float getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist)=0
virtual bool getObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float pModifyDist)=0
test if we hit an object.
virtual bool processCommand (char *pCommand)=0
send debug commands
void setEnableLineOfSightCalc (bool pVal)
Enable/disable LOS calculation It is enabled by default.
void setEnableHeightCalc (bool pVal)
Enable/disable model height calculation It is enabled by default.
bool isLineOfSightCalcEnabled () const
bool isHeightCalcEnabled () const
bool isMapLoadingEnabled () const
virtual std::string getDirFileName (unsigned int pMapId, int x, int y) const =0
virtual bool IsTileLoaded (uint32 mapId, uint32 x, uint32 y) const =0
virtual bool getAreaInfo (unsigned int pMapId, float x, float y, float &z, uint32 &flags, int32 &adtId, int32 &rootId, int32 &groupId) const =0
Query world model area info.
virtual bool GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float &level, float &floor, uint32 &type) const =0
Private Attributes
bool iEnableLineOfSightCalc
bool iEnableHeightCalc
Detailed Description
Definition at line 44 of file IVMapManager.h.
Constructor & Destructor Documentation
IVMapManager()
VMAP::IVMapManager::IVMapManager () inline
Definition at line 51 of file IVMapManager.h.
~IVMapManager()
virtual VMAP::IVMapManager::~IVMapManager (void) inline virtual
Definition at line 53 of file IVMapManager.h.
Member Function Documentation
existsMap()
virtual bool VMAP::IVMapManager::existsMap (const char * pBasePath, unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapManager2.
getAreaInfo()
virtual bool VMAP::IVMapManager::getAreaInfo (unsigned int pMapId, float x, float y, float & z, uint32 & flags, int32 & adtId, int32 & rootId, int32 & groupId) const pure virtual
Query world model area info.
Parameters
z gets adjusted to the ground height for which this are info is valid
Implemented in VMAP::VMapManager2.
Referenced by TerrainInfo::GetAreaInfo().
getDirFileName()
virtual std::string VMAP::IVMapManager::getDirFileName (unsigned int pMapId, int x, int y) const pure virtual
Implemented in VMAP::VMapManager2.
getHeight()
virtual float VMAP::IVMapManager::getHeight (unsigned int pMapId, float x, float y, float z, float maxSearchDist) pure virtual
Implemented in VMAP::VMapManager2.
Referenced by Map::GetHeightInRange(), and TerrainInfo::GetHeightStatic().
GetLiquidLevel()
virtual bool VMAP::IVMapManager::GetLiquidLevel (uint32 pMapId, float x, float y, float z, uint8 ReqLiquidType, float & level, float & floor, uint32 & type) const pure virtual
Implemented in VMAP::VMapManager2.
Referenced by TerrainInfo::getLiquidStatus().
getObjectHitPos()
virtual bool VMAP::IVMapManager::getObjectHitPos (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float pModifyDist) pure virtual
test if we hit an object.
return true if we hit one. rx,ry,rz will hold the hit position or the dest position, if no intersection was found return a position, that is pReduceDist closer to the origin
Implemented in VMAP::VMapManager2.
Referenced by Map::GetHitPosition().
isHeightCalcEnabled()
bool VMAP::IVMapManager::isHeightCalcEnabled () const inline
Definition at line 86 of file IVMapManager.h.
References iEnableHeightCalc.
Referenced by TerrainInfo::CanCheckLiquidLevel(), VMAP::VMapManager2::getHeight(), and TerrainInfo::GetHeightStatic().
isInLineOfSight()
virtual bool VMAP::IVMapManager::isInLineOfSight (unsigned int pMapId, float x1, float y1, float z1, float x2, float y2, float z2, bool ignoreM2Model) pure virtual
Implemented in VMAP::VMapManager2.
Referenced by Map::IsInLineOfSight().
isLineOfSightCalcEnabled()
bool VMAP::IVMapManager::isLineOfSightCalcEnabled () const inline
Definition at line 85 of file IVMapManager.h.
References iEnableLineOfSightCalc.
Referenced by Spell::CheckCast(), Map::GetHeightInRange(), VMAP::VMapManager2::getObjectHitPos(), and VMAP::VMapManager2::isInLineOfSight().
isMapLoadingEnabled()
bool VMAP::IVMapManager::isMapLoadingEnabled () const inline
Definition at line 87 of file IVMapManager.h.
References iEnableHeightCalc, and iEnableLineOfSightCalc.
Referenced by VMAP::VMapManager2::loadMap().
IsTileLoaded()
virtual bool VMAP::IVMapManager::IsTileLoaded (uint32 mapId, uint32 x, uint32 y) const pure virtual
Implemented in VMAP::VMapManager2.
Referenced by TerrainInfo::LoadMapAndVMap().
loadMap()
virtual VMAPLoadResult VMAP::IVMapManager::loadMap (const char * pBasePath, unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapManager2.
Referenced by TerrainInfo::LoadMapAndVMap().
processCommand()
virtual bool VMAP::IVMapManager::processCommand (char * pCommand) pure virtual
send debug commands
Implemented in VMAP::VMapManager2.
setEnableHeightCalc()
void VMAP::IVMapManager::setEnableHeightCalc (bool pVal) inline
Enable/disable model height calculation It is enabled by default.
If it is enabled in mid game the maps have to loaded manualy
Definition at line 83 of file IVMapManager.h.
References iEnableHeightCalc.
Referenced by World::LoadConfigSettings().
setEnableLineOfSightCalc()
void VMAP::IVMapManager::setEnableLineOfSightCalc (bool pVal) inline
Enable/disable LOS calculation It is enabled by default.
If it is enabled in mid game the maps have to loaded manualy
Definition at line 78 of file IVMapManager.h.
References iEnableLineOfSightCalc.
Referenced by World::LoadConfigSettings().
unloadMap() [1/2]
virtual void VMAP::IVMapManager::unloadMap (unsigned int pMapId) pure virtual
Implemented in VMAP::VMapManager2.
unloadMap() [2/2]
virtual void VMAP::IVMapManager::unloadMap (unsigned int pMapId, int x, int y) pure virtual
Implemented in VMAP::VMapManager2.
Referenced by TerrainInfo::CleanUpGrids(), and TerrainInfo::~TerrainInfo().
Field Documentation
iEnableHeightCalc
bool VMAP::IVMapManager::iEnableHeightCalc private
Definition at line 48 of file IVMapManager.h.
Referenced by isHeightCalcEnabled(), isMapLoadingEnabled(), and setEnableHeightCalc().
iEnableLineOfSightCalc
bool VMAP::IVMapManager::iEnableLineOfSightCalc private
Definition at line 47 of file IVMapManager.h.
Referenced by isLineOfSightCalcEnabled(), isMapLoadingEnabled(), and setEnableLineOfSightCalc().
The documentation for this class was generated from the following file:
IVMapManager.h