CMaNGOS_WoTLK: SpellLog Class Reference
SpellLog Class Reference
#include <Spell.h>
Public Member Functions
SpellLog (Spell *spell)
SpellLog ()=delete
SpellLog (const SpellLog &)=delete
void Initialize ()
template<typename... Args>
void AddLog (uint32 spellEffect, Args... args)
void SendToSet ()
Private Member Functions
void FinalizePrevious ()
void SetCurrentEffect (uint32 effect)
template<typename T >
void AddLogData (T const &data)
template<typename T , typename... Args>
void AddLogData (T const &data, Args const &... args)
Private Attributes
Spell * m_spell
WorldPacket m_spellLogData
size_t m_spellLogDataEffectsCounterPos
uint32 m_spellLogDataEffectsCounter
size_t m_spellLogDataTargetsCounterPos
uint32 m_spellLogDataTargetsCounter
uint32 m_currentEffect
Detailed Description
Definition at line 269 of file Spell.h.
Constructor & Destructor Documentation
SpellLog() [1/3]
SpellLog::SpellLog (Spell * spell) inline
Definition at line 272 of file Spell.h.
SpellLog() [2/3]
SpellLog::SpellLog () delete
SpellLog() [3/3]
SpellLog::SpellLog (const SpellLog &) delete
Member Function Documentation
AddLog()
template<typename... Args> void SpellLog::AddLog (uint32 spellEffect, Args... args) inline
Definition at line 282 of file Spell.h.
References AddLogData(), m_spellLogDataEffectsCounter, and SetCurrentEffect().
Referenced by Spell::DoSummonTotem(), Spell::EffectAddExtraAttacks(), Spell::EffectCreateItem(), Spell::EffectCreateItem2(), Spell::EffectCreateRandomItem(), Spell::EffectDismissPet(), Spell::EffectDuel(), Spell::EffectFeedPet(), Spell::EffectInterruptCast(), Spell::EffectOpenLock(), Spell::EffectPowerBurn(), Spell::EffectPowerDrain(), Spell::EffectResurrect(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), and Spell::EffectTransmitted().
AddLogData() [1/2]
template<typename T > void SpellLog::AddLogData (T const & data) inline private
Definition at line 301 of file Spell.h.
References m_spellLogData.
Referenced by AddLog(), and AddLogData().
AddLogData() [2/2]
template<typename T , typename... Args> void SpellLog::AddLogData (T const & data, Args const &... args) inline private
Definition at line 304 of file Spell.h.
References AddLogData().
FinalizePrevious()
void SpellLog::FinalizePrevious () private
Definition at line 374 of file Spell.cpp.
References m_currentEffect, m_spellLogData, m_spellLogDataTargetsCounter, m_spellLogDataTargetsCounterPos, MAX_SPELL_EFFECTS, and ByteBuffer::put().
Referenced by SendToSet(), and SetCurrentEffect().
Initialize()
void SpellLog::Initialize ()
Definition at line 363 of file Spell.cpp.
References ByteBuffer::appendPackGUID(), Object::GetObjectGuid(), ObjectGuid::GetRawValue(), Spell::GetTrueCaster(), SpellEntry::Id, WorldPacket::Initialize(), m_spell, Spell::m_spellInfo, m_spellLogData, m_spellLogDataEffectsCounter, m_spellLogDataEffectsCounterPos, SMSG_SPELLLOGEXECUTE, and ByteBuffer::wpos().
Referenced by SendToSet(), and Spell::Spell().
SendToSet()
void SpellLog::SendToSet ()
Definition at line 402 of file Spell.cpp.
References FinalizePrevious(), Spell::GetTrueCaster(), Initialize(), m_spell, m_spellLogData, m_spellLogDataEffectsCounter, m_spellLogDataEffectsCounterPos, ByteBuffer::put(), and WorldObject::SendMessageToSet().
Referenced by Spell::_handle_finish_phase(), Spell::EffectDismissPet(), and Spell::EffectFeedPet().
SetCurrentEffect()
void SpellLog::SetCurrentEffect (uint32 effect) private
Definition at line 384 of file Spell.cpp.
References FinalizePrevious(), m_currentEffect, m_spellLogData, m_spellLogDataTargetsCounter, m_spellLogDataTargetsCounterPos, and ByteBuffer::wpos().
Referenced by AddLog().
Field Documentation
m_currentEffect
uint32 SpellLog::m_currentEffect private
Definition at line 316 of file Spell.h.
Referenced by FinalizePrevious(), and SetCurrentEffect().
m_spell
Spell* SpellLog::m_spell private
Definition at line 310 of file Spell.h.
Referenced by Initialize(), and SendToSet().
m_spellLogData
WorldPacket SpellLog::m_spellLogData private
Definition at line 311 of file Spell.h.
Referenced by AddLogData(), FinalizePrevious(), Initialize(), SendToSet(), and SetCurrentEffect().
m_spellLogDataEffectsCounter
uint32 SpellLog::m_spellLogDataEffectsCounter private
Definition at line 313 of file Spell.h.
Referenced by AddLog(), Initialize(), and SendToSet().
m_spellLogDataEffectsCounterPos
size_t SpellLog::m_spellLogDataEffectsCounterPos private
Definition at line 312 of file Spell.h.
Referenced by Initialize(), and SendToSet().
m_spellLogDataTargetsCounter
uint32 SpellLog::m_spellLogDataTargetsCounter private
Definition at line 315 of file Spell.h.
Referenced by FinalizePrevious(), and SetCurrentEffect().
m_spellLogDataTargetsCounterPos
size_t SpellLog::m_spellLogDataTargetsCounterPos private
Definition at line 314 of file Spell.h.
Referenced by FinalizePrevious(), and SetCurrentEffect().
The documentation for this class was generated from the following files:
Spell.h
Spell.cpp