CMaNGOS_WoTLK: MySQLConnection Class Reference
MySQLConnection Class Reference
#include <DatabaseMysql.h>
Public Member Functions
MySQLConnection (Database &db)
~MySQLConnection ()
bool Initialize (const char *infoString) override
Initializes Mysql and connects to a server.
QueryResult * Query (const char *sql) override
QueryNamedResult * QueryNamed (const char *sql) override
bool Execute (const char *sql) override
unsigned long escape_string (char *to, const char *from, unsigned long length)
bool BeginTransaction () override
bool CommitTransaction () override
bool RollbackTransaction () override
Public Member Functions inherited from SqlConnection
virtual ~SqlConnection ()
bool ExecuteStmt (int nIndex, const SqlStmtParameters &id)
Database & DB () const
Protected Member Functions
SqlPreparedStatement * CreateStatement (const std::string &fmt) override
Protected Member Functions inherited from SqlConnection
SqlConnection (Database &db)
SqlPreparedStatement * GetStmt (uint32 nIndex)
void FreePreparedStatements ()
Private Member Functions
bool _TransactionCmd (const char *sql)
bool _Query (const char *sql, MYSQL_RES **pResult, MYSQL_FIELD **pFields, uint64 *pRowCount, uint32 *pFieldCount)
Private Attributes
MYSQL * mMysql
Additional Inherited Members
Protected Attributes inherited from SqlConnection
Database & m_db
Detailed Description
Definition at line 62 of file DatabaseMysql.h.
Constructor & Destructor Documentation
MySQLConnection()
MySQLConnection::MySQLConnection (Database & db) inline
Definition at line 65 of file DatabaseMysql.h.
~MySQLConnection()
MySQLConnection::~MySQLConnection ()
Definition at line 71 of file DatabaseMysql.cpp.
References SqlConnection::FreePreparedStatements(), and mMysql.
Member Function Documentation
_Query()
bool MySQLConnection::_Query (const char * sql, MYSQL_RES ** pResult, MYSQL_FIELD ** pFields, uint64 * pRowCount, uint32 * pFieldCount) private
Definition at line 175 of file DatabaseMysql.cpp.
References DEBUG_FILTER_LOG, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), LOG_FILTER_SQL_TEXT, mMysql, and sLog.
Referenced by Query(), and QueryNamed().
_TransactionCmd()
bool MySQLConnection::_TransactionCmd (const char * sql) private
Definition at line 264 of file DatabaseMysql.cpp.
References DEBUG_FILTER_LOG, LOG_FILTER_SQL_TEXT, mMysql, and sLog.
Referenced by BeginTransaction(), CommitTransaction(), and RollbackTransaction().
BeginTransaction()
bool MySQLConnection::BeginTransaction () override virtual
Reimplemented from SqlConnection.
Definition at line 276 of file DatabaseMysql.cpp.
References _TransactionCmd().
CommitTransaction()
bool MySQLConnection::CommitTransaction () override virtual
Reimplemented from SqlConnection.
Definition at line 281 of file DatabaseMysql.cpp.
References _TransactionCmd().
CreateStatement()
SqlPreparedStatement * MySQLConnection::CreateStatement (const std::string & fmt) override protected virtual
Reimplemented from SqlConnection.
Definition at line 300 of file DatabaseMysql.cpp.
References mMysql.
escape_string()
unsigned long MySQLConnection::escape_string (char * to, const char * from, unsigned long length) virtual
Reimplemented from SqlConnection.
Definition at line 291 of file DatabaseMysql.cpp.
References mMysql.
Execute()
bool MySQLConnection::Execute (const char * sql) override virtual
Implements SqlConnection.
Definition at line 243 of file DatabaseMysql.cpp.
References DEBUG_FILTER_LOG, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), LOG_FILTER_SQL_TEXT, mMysql, and sLog.
Referenced by Initialize().
Initialize()
bool MySQLConnection::Initialize (const char * infoString) override virtual
Initializes Mysql and connects to a server.
infoString should be formated like hostname;username;password;database.
Implements SqlConnection.
Definition at line 77 of file DatabaseMysql.cpp.
References DETAIL_LOG, Execute(), mMysql, sLog, and StrSplit().
Query()
QueryResult * MySQLConnection::Query (const char * sql) override virtual
Implements SqlConnection.
Definition at line 207 of file DatabaseMysql.cpp.
References _Query(), and QueryResultMysql::NextRow().
QueryNamed()
QueryNamedResult * MySQLConnection::QueryNamed (const char * sql) override virtual
Implements SqlConnection.
Definition at line 223 of file DatabaseMysql.cpp.
References _Query(), and QueryResultMysql::NextRow().
RollbackTransaction()
bool MySQLConnection::RollbackTransaction () override virtual
Reimplemented from SqlConnection.
Definition at line 286 of file DatabaseMysql.cpp.
References _TransactionCmd().
Field Documentation
mMysql
MYSQL* MySQLConnection::mMysql private
Definition at line 89 of file DatabaseMysql.h.
Referenced by _Query(), _TransactionCmd(), CreateStatement(), escape_string(), Execute(), Initialize(), and ~MySQLConnection().
The documentation for this class was generated from the following files:
DatabaseMysql.h
DatabaseMysql.cpp