CMaNGOS_WoTLK: MaNGOS::MonsterChatBuilder Class Reference
MaNGOS::MonsterChatBuilder Class Reference
Public Member Functions
MonsterChatBuilder (WorldObject const &obj, ChatMsg msgtype, std::vector< std::string > content, Language language, Unit const *target)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
WorldObject const & i_object
ChatMsg i_msgtype
std::vector< std::string > i_content
Language i_language
Unit const * i_target
Detailed Description
Definition at line 1962 of file Object.cpp.
Constructor & Destructor Documentation
MonsterChatBuilder()
MaNGOS::MonsterChatBuilder::MonsterChatBuilder (WorldObject const & obj, ChatMsg msgtype, std::vector< std::string > content, Language language, Unit const * target) inline
Definition at line 1965 of file Object.cpp.
Member Function Documentation
operator()()
void MaNGOS::MonsterChatBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 1967 of file Object.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, WorldObject::GetNameForLocaleIdx(), Object::GetObjectGuid(), i_content, i_language, i_msgtype, i_object, and i_target.
Field Documentation
i_content
std::vector<std::string> MaNGOS::MonsterChatBuilder::i_content private
Definition at line 1982 of file Object.cpp.
Referenced by operator()().
i_language
Language MaNGOS::MonsterChatBuilder::i_language private
Definition at line 1983 of file Object.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::MonsterChatBuilder::i_msgtype private
Definition at line 1981 of file Object.cpp.
Referenced by operator()().
i_object
WorldObject const& MaNGOS::MonsterChatBuilder::i_object private
Definition at line 1980 of file Object.cpp.
Referenced by operator()().
i_target
Unit const* MaNGOS::MonsterChatBuilder::i_target private
Definition at line 1984 of file Object.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
Object.cpp