CMaNGOS_WoTLK: instance_pinnacle Class Reference
instance_pinnacle Class Reference
#include <utgarde_pinnacle.h>
Public Member Functions
instance_pinnacle (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
ObjectGuid GetRandomBrazier () const
void SetGortokEventStarter (ObjectGuid playerGuid)
ObjectGuid GetGortokEventStarter () const
ObjectGuid GetSkadiMobsTrigger () const
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
bool m_abAchievCriteria [MAX_SPECIAL_ACHIEV_CRITS]
std::string m_strInstData
uint32 m_uiGortokOrbTimer
uint8 m_uiGortokOrbPhase
uint32 m_uiGauntletCheckTimer
uint32 m_uiSkadiResetTimer
ObjectGuid m_gortokEventTriggerGuid
ObjectGuid m_gortokEventStarterGuid
ObjectGuid m_skadiMobsTriggerGuid
GuidList m_lskadiGauntletMobsList
GuidVector m_vbrazierVector
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 82 of file utgarde_pinnacle.h.
Constructor & Destructor Documentation
instance_pinnacle()
instance_pinnacle::instance_pinnacle (Map * pMap)
Definition at line 60 of file utgarde_pinnacle.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_pinnacle::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 352 of file utgarde_pinnacle.cpp.
References ACHIEV_CRIT_GIRL_LOVES_SKADI, ACHIEV_CRIT_INCREDIBLE_HULK, ACHIEV_CRIT_KINGS_BANE, m_abAchievCriteria, TYPE_ACHIEV_INCREDIBLE_HULK, TYPE_ACHIEV_KINGS_BANE, and TYPE_ACHIEV_LOVE_SKADI.
GetData()
uint32 instance_pinnacle::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 316 of file utgarde_pinnacle.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnPlayerEnter().
GetGortokEventStarter()
ObjectGuid instance_pinnacle::GetGortokEventStarter () const inline
Definition at line 112 of file utgarde_pinnacle.h.
References m_gortokEventStarterGuid.
GetRandomBrazier()
ObjectGuid instance_pinnacle::GetRandomBrazier () const inline
Definition at line 103 of file utgarde_pinnacle.h.
References m_vbrazierVector, and urand().
GetSkadiMobsTrigger()
ObjectGuid instance_pinnacle::GetSkadiMobsTrigger () const inline
Definition at line 113 of file utgarde_pinnacle.h.
References m_skadiMobsTriggerGuid.
Referenced by boss_skadiAI::DoPrepareForGauntlet().
Initialize()
void instance_pinnacle::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 69 of file utgarde_pinnacle.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_abAchievCriteria, and m_auiEncounter.
Referenced by instance_pinnacle().
JustDidDialogueStep()
void instance_pinnacle::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 368 of file utgarde_pinnacle.cpp.
References aArthasSpawnPos, aSvalaSpawnPos, ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_ARTHAS_IMAGE, NPC_SVALA, NPC_SVALA_SORROWGRAVE, SAY_INTRO_5, SPELL_TRANSFORMING, SPELL_TRANSFORMING_CHANNEL, SPELL_TRANSFORMING_FLOATING, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_DESPAWN, TRIGGERED_NONE, UNIT_BYTE1_FLAG_FLY_ANIM, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, and UNIT_FLAG_UNINTERACTIBLE.
Load()
void instance_pinnacle::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 324 of file utgarde_pinnacle.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_pinnacle::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 99 of file utgarde_pinnacle.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), m_gortokEventTriggerGuid, m_lskadiGauntletMobsList, ScriptedInstance::m_npcEntryGuidStore, m_skadiMobsTriggerGuid, m_vbrazierVector, NPC_ARTHAS_IMAGE, NPC_BJORN, NPC_FLAME_BRAZIER, NPC_FURBOLG, NPC_GRAUF, NPC_HALDOR, NPC_JORMUNGAR, NPC_RANULF, NPC_RHINO, NPC_SKADI, NPC_SVALA, NPC_SVALA_SORROWGRAVE, NPC_TORGYN, NPC_WORGEN, NPC_WORLD_TRIGGER, NPC_WORLD_TRIGGER_LARGE, NPC_YMIRJAR_HARPOONER, NPC_YMIRJAR_WARRIOR, and NPC_YMIRJAR_WITCH_DOCTOR.
OnCreatureDeath()
void instance_pinnacle::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 446 of file utgarde_pinnacle.cpp.
References DONE, Object::GetEntry(), m_uiGortokOrbTimer, NPC_FURBOLG, NPC_GORTOK, NPC_JORMUNGAR, NPC_RHINO, NPC_WORGEN, SetData(), and TYPE_GORTOK.
OnCreatureEvade()
void instance_pinnacle::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 424 of file utgarde_pinnacle.cpp.
References FAIL, Object::GetEntry(), NPC_FURBOLG, NPC_GORTOK, NPC_JORMUNGAR, NPC_RHINO, NPC_WORGEN, NPC_YMIRJAR_HARPOONER, NPC_YMIRJAR_WARRIOR, NPC_YMIRJAR_WITCH_DOCTOR, SetData(), Object::SetFlag(), TYPE_GORTOK, TYPE_SKADI, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, and UNIT_FLAG_UNINTERACTIBLE.
OnCreatureRespawn()
void instance_pinnacle::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 136 of file utgarde_pinnacle.cpp.
References Creature::AI(), Object::GetEntry(), ObjectGuid::GetEntry(), Unit::GetMotionMaster(), WorldObject::GetSpawnerGuid(), Creature::IsTemporarySummon(), MotionMaster::MoveWaypoint(), NPC_FLAME_BREATH_TRIGGER, NPC_RITUAL_TARGET, NPC_SPIRIT_FOUNT, NPC_WORLD_TRIGGER, NPC_YMIRJAR_HARPOONER, NPC_YMIRJAR_WARRIOR, NPC_YMIRJAR_WITCH_DOCTOR, REACT_PASSIVE, Unit::SetCanEnterCombat(), UnitAI::SetReactState(), and Creature::SetWalk().
OnObjectCreate()
void instance_pinnacle::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 162 of file utgarde_pinnacle.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_DOOR_SKADI, GO_DOOR_YMIRON, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), TYPE_SKADI, and TYPE_YMIRON.
OnPlayerEnter()
void instance_pinnacle::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 79 of file utgarde_pinnacle.cpp.
References aSvalaSpawnPos, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_SVALA, NPC_SVALA_SORROWGRAVE, SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_SVALA, UNIT_BYTE1_FLAG_FLY_ANIM, UNIT_FIELD_BYTES_1, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Save()
const char* instance_pinnacle::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 115 of file utgarde_pinnacle.h.
References m_strInstData.
SetData()
void instance_pinnacle::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 180 of file utgarde_pinnacle.cpp.
References ACHIEV_START_SKADI_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, aGortokMiniBosses, aOrbPositions, DONE, ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DOOR_SKADI, GO_DOOR_YMIRON, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_gortokEventTriggerGuid, m_lskadiGauntletMobsList, m_skadiMobsTriggerGuid, m_strInstData, m_uiGauntletCheckTimer, m_uiGortokOrbPhase, m_uiGortokOrbTimer, m_uiSkadiResetTimer, NOT_STARTED, NPC_ARTHAS_IMAGE, NPC_GRAUF, NPC_SKADI, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), script_error_log(), SetSpecialAchievementCriteria(), SPECIAL, SPELL_GAUNTLET_PERIODIC, SPELL_ORB_VISUAL, DialogueHelper::StartNextDialogueText(), TRIGGERED_OLD_TRIGGERED, TYPE_ACHIEV_INCREDIBLE_HULK, TYPE_ACHIEV_KINGS_BANE, TYPE_ACHIEV_LOVE_SKADI, TYPE_GORTOK, TYPE_SKADI, TYPE_SVALA, TYPE_YMIRON, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by boss_skadiAI::Aggro(), boss_ymironAI::Aggro(), boss_skadiAI::JustDied(), boss_svalaAI::JustDied(), boss_ymironAI::JustDied(), boss_skadiAI::JustReachedHome(), boss_svalaAI::JustReachedHome(), boss_ymironAI::JustReachedHome(), OnCreatureDeath(), and OnCreatureEvade().
SetGortokEventStarter()
void instance_pinnacle::SetGortokEventStarter (ObjectGuid playerGuid) inline
Definition at line 111 of file utgarde_pinnacle.h.
References m_gortokEventStarterGuid.
SetSpecialAchievementCriteria()
void instance_pinnacle::SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
Definition at line 346 of file utgarde_pinnacle.cpp.
References m_abAchievCriteria, and MAX_SPECIAL_ACHIEV_CRITS.
Referenced by boss_svalaAI::KilledUnit(), npc_graufAI::MovementInform(), and SetData().
Update()
void instance_pinnacle::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 462 of file utgarde_pinnacle.cpp.
References aOrbPositions, DialogueHelper::DialogueUpdate(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Map::IsRegularDifficulty(), m_gortokEventTriggerGuid, m_uiGauntletCheckTimer, m_uiGortokOrbPhase, m_uiGortokOrbTimer, m_uiSkadiResetTimer, NPC_GRAUF, NPC_SKADI, NPC_WORLD_TRIGGER_LARGE, SPELL_AWAKEN_GORTOK, SPELL_AWAKEN_SUBBOSS, SPELL_GAUNTLET_RESET_CHECK, and TRIGGERED_NONE.
Field Documentation
m_abAchievCriteria
bool instance_pinnacle::m_abAchievCriteria[MAX_SPECIAL_ACHIEV_CRITS] private
Definition at line 124 of file utgarde_pinnacle.h.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetSpecialAchievementCriteria().
m_auiEncounter
uint32 instance_pinnacle::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 123 of file utgarde_pinnacle.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_gortokEventStarterGuid
ObjectGuid instance_pinnacle::m_gortokEventStarterGuid private
Definition at line 134 of file utgarde_pinnacle.h.
Referenced by GetGortokEventStarter(), and SetGortokEventStarter().
m_gortokEventTriggerGuid
ObjectGuid instance_pinnacle::m_gortokEventTriggerGuid private
Definition at line 133 of file utgarde_pinnacle.h.
Referenced by OnCreatureCreate(), SetData(), and Update().
m_lskadiGauntletMobsList
GuidList instance_pinnacle::m_lskadiGauntletMobsList private
Definition at line 137 of file utgarde_pinnacle.h.
Referenced by OnCreatureCreate(), and SetData().
m_skadiMobsTriggerGuid
ObjectGuid instance_pinnacle::m_skadiMobsTriggerGuid private
Definition at line 135 of file utgarde_pinnacle.h.
Referenced by GetSkadiMobsTrigger(), OnCreatureCreate(), and SetData().
m_strInstData
std::string instance_pinnacle::m_strInstData private
Definition at line 125 of file utgarde_pinnacle.h.
Referenced by Save(), and SetData().
m_uiGauntletCheckTimer
uint32 instance_pinnacle::m_uiGauntletCheckTimer private
Definition at line 130 of file utgarde_pinnacle.h.
Referenced by SetData(), and Update().
m_uiGortokOrbPhase
uint8 instance_pinnacle::m_uiGortokOrbPhase private
Definition at line 128 of file utgarde_pinnacle.h.
Referenced by SetData(), and Update().
m_uiGortokOrbTimer
uint32 instance_pinnacle::m_uiGortokOrbTimer private
Definition at line 127 of file utgarde_pinnacle.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_uiSkadiResetTimer
uint32 instance_pinnacle::m_uiSkadiResetTimer private
Definition at line 131 of file utgarde_pinnacle.h.
Referenced by SetData(), and Update().
m_vbrazierVector
GuidVector instance_pinnacle::m_vbrazierVector private
Definition at line 138 of file utgarde_pinnacle.h.
Referenced by GetRandomBrazier(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
utgarde_pinnacle.h
utgarde_pinnacle.cpp