CMaNGOS_WoTLK: instance_arcatraz Class Reference
instance_arcatraz Class Reference
#include <arcatraz.h>
Public Member Functions
instance_arcatraz (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiResetDelayTimer
uint32 m_uiEntranceEventTimer
uint8 m_uiKilledWarders
uint8 m_uiKilledDefenders
GuidList m_lSkyrissEventMobsGuidList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 82 of file arcatraz.h.
Constructor & Destructor Documentation
instance_arcatraz()
instance_arcatraz::instance_arcatraz (Map * pMap)
Definition at line 92 of file arcatraz.cpp.
References Initialize().
Member Function Documentation
GetData()
uint32 instance_arcatraz::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 330 of file arcatraz.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnPlayerEnter(), and SetData().
Initialize()
void instance_arcatraz::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 101 of file arcatraz.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_arcatraz().
JustDidDialogueStep()
void instance_arcatraz::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 361 of file arcatraz.cpp.
References aSummonPosition, Unit::CastSpell(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_SEAL_SPHERE, IN_PROGRESS, Unit::InterruptNonMeleeSpells(), SpawnLocation::m_fO, SpawnLocation::m_fX, SpawnLocation::m_fY, SpawnLocation::m_fZ, NPC_AKKIRIS, NPC_BL_DRAKONAAR, NPC_BLAZING_TRICKSTER, NPC_MELLICHAR, NPC_MILLHOUSE, NPC_PHASE_HUNTER, NPC_PRISON_APHPA_POD, NPC_PRISON_BETA_POD, NPC_PRISON_BOSS_POD, NPC_PRISON_DELTA_POD, NPC_PRISON_GAMMA_POD, NPC_SKYRISS, NPC_SULFURON, NPC_TW_DRAKONAAR, SAY_SKYRISS_AGGRO, SetData(), Unit::SetFacingToObject(), SPELL_MIND_REND, SPELL_QUIET_SUICIDE, SPELL_SIMPLE_TELEPORT, SPELL_TARGET_ALPHA, SPELL_TARGET_BETA, SPELL_TARGET_DELTA, SPELL_TARGET_GAMMA, SPELL_TARGET_OMEGA, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, TYPE_WARDEN_1, TYPE_WARDEN_2, TYPE_WARDEN_3, TYPE_WARDEN_4, TYPE_WARDEN_5, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, urand(), YELL_MELLICAR_WELCOME, YELL_MELLICHAR_RELEASE1, YELL_MELLICHAR_RELEASE2, YELL_MELLICHAR_RELEASE4, and YELL_MELLICHAR_RELEASE5.
Load()
void instance_arcatraz::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 338 of file arcatraz.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_arcatraz::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 142 of file arcatraz.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lSkyrissEventMobsGuidList, ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_AKKIRIS, NPC_BL_DRAKONAAR, NPC_BLAZING_TRICKSTER, NPC_DALLIAH, NPC_MELLICHAR, NPC_MILLHOUSE, NPC_PHASE_HUNTER, NPC_PRISON_APHPA_POD, NPC_PRISON_BETA_POD, NPC_PRISON_BOSS_POD, NPC_PRISON_DELTA_POD, NPC_PRISON_GAMMA_POD, NPC_SKYRISS, NPC_SOCCOTHRATES, NPC_SULFURON, NPC_TW_DRAKONAAR, and NPC_WRATH_SCRYER_FELFIRE.
OnCreatureDeath()
void instance_arcatraz::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 443 of file arcatraz.cpp.
References DONE, Creature::ForcedDespawn(), Object::GetEntry(), m_uiEntranceEventTimer, m_uiKilledDefenders, m_uiKilledWarders, MAX_DEFENDERS, MAX_WARDERS, NPC_ARCATRAZ_DEFENDER, NPC_ARCATRAZ_WARDER, NPC_PROTEAN_HORROR, NPC_PROTEAN_NIGHTMARE, SetData(), and TYPE_ENTRANCE.
OnObjectCreate()
void instance_arcatraz::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 117 of file arcatraz.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_CORE_SECURITY_FIELD_ALPHA, GO_CORE_SECURITY_FIELD_BETA, GO_POD_ALPHA, GO_POD_BETA, GO_POD_DELTA, GO_POD_GAMMA, GO_POD_OMEGA, GO_SEAL_SPHERE, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, and GameObject::SetGoState().
OnPlayerEnter()
void instance_arcatraz::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 107 of file arcatraz.cpp.
References DONE, GetData(), IN_PROGRESS, m_uiEntranceEventTimer, SetData(), and TYPE_ENTRANCE.
Save()
const char* instance_arcatraz::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 97 of file arcatraz.h.
References m_strInstData.
SetData()
void instance_arcatraz::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 174 of file arcatraz.cpp.
References Player::AreaExploredOrEventHappens(), DONE, DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetData(), Map::GetPlayers(), Player::GetQuestStatus(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_CORE_SECURITY_FIELD_ALPHA, GO_CORE_SECURITY_FIELD_BETA, GO_POD_ALPHA, GO_POD_BETA, GO_POD_DELTA, GO_POD_GAMMA, GO_POD_OMEGA, GO_SEAL_SPHERE, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, m_lSkyrissEventMobsGuidList, m_strInstData, m_uiResetDelayTimer, NOT_STARTED, NPC_MELLICHAR, NPC_MILLHOUSE, NPC_WRATH_SCRYER_FELFIRE, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, QUEST_STATUS_INCOMPLETE, QUEST_TRIAL_OF_THE_NAARU_TENACITY, InstanceData::SaveToDB(), SAY_MILLHOUSE_COMPLETE, DialogueHelper::StartNextDialogueText(), TYPE_DALLIAH, TYPE_ENTRANCE, TYPE_HARBINGERSKYRISS, TYPE_SOCCOTHRATES, TYPE_WARDEN_1, TYPE_WARDEN_2, TYPE_WARDEN_3, TYPE_WARDEN_4, TYPE_WARDEN_5, TYPE_ZEREKETH, YELL_MELLICHAR_INTRO1, YELL_MELLICHAR_RELEASE2, YELL_MELLICHAR_RELEASE3, YELL_MELLICHAR_RELEASE4, and YELL_MELLICHAR_RELEASE5.
Referenced by JustDidDialogueStep(), OnCreatureDeath(), and OnPlayerEnter().
Update()
void instance_arcatraz::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 468 of file arcatraz.cpp.
References aEntranceSpawnLoc, DialogueHelper::DialogueUpdate(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiEntranceEventTimer, m_uiKilledDefenders, m_uiKilledWarders, m_uiResetDelayTimer, MAX_DEFENDERS, MAX_WARDERS, NPC_MELLICHAR, NPC_PROTEAN_HORROR, NPC_PROTEAN_NIGHTMARE, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, and urand().
Field Documentation
m_auiEncounter
uint32 instance_arcatraz::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 105 of file arcatraz.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_lSkyrissEventMobsGuidList
GuidList instance_arcatraz::m_lSkyrissEventMobsGuidList private
Definition at line 113 of file arcatraz.h.
Referenced by OnCreatureCreate(), and SetData().
m_strInstData
std::string instance_arcatraz::m_strInstData private
Definition at line 106 of file arcatraz.h.
Referenced by Save(), and SetData().
m_uiEntranceEventTimer
uint32 instance_arcatraz::m_uiEntranceEventTimer private
Definition at line 109 of file arcatraz.h.
Referenced by OnCreatureDeath(), OnPlayerEnter(), and Update().
m_uiKilledDefenders
uint8 instance_arcatraz::m_uiKilledDefenders private
Definition at line 111 of file arcatraz.h.
Referenced by OnCreatureDeath(), and Update().
m_uiKilledWarders
uint8 instance_arcatraz::m_uiKilledWarders private
Definition at line 110 of file arcatraz.h.
Referenced by OnCreatureDeath(), and Update().
m_uiResetDelayTimer
uint32 instance_arcatraz::m_uiResetDelayTimer private
Definition at line 108 of file arcatraz.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
arcatraz.h
arcatraz.cpp