CMaNGOS_WoTLK: WorldSocket Class Reference
WorldSocket Class Reference
User to World Communication
WorldSocket.
#include <WorldSocket.h>
Data Structures
struct ClientPktHeader
Public Member Functions
WorldSocket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
void SendPacket (const WorldPacket &pct, bool immediate=false)
void FinalizeSession ()
virtual bool Open () override
BigNumber & GetSessionKey ()
Return the session key.
std::deque< uint32 > GetOutOpcodeHistory ()
std::deque< uint32 > GetIncOpcodeHistory ()
bool IsLoggingPackets () const
void SetPacketLogging (bool state)
Public Member Functions inherited from MaNGOS::Socket
Socket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
virtual ~Socket ()=default
void Close ()
bool IsClosed () const
virtual bool Deletable () const
bool Read (char *buffer, int length)
void ReadSkip (int length)
void Write (const char *buffer, int length)
void Write (const char *header, int headerSize, const char *content, int contentSize)
boost::asio::ip::tcp::socket & GetAsioSocket ()
const std::string & GetRemoteEndpoint () const
const std::string & GetRemoteAddress () const
template<typename T >
std::shared_ptr< T > shared ()
boost::asio::ip::address GetRemoteIpAddress () const
uint16 GetRemotePort () const
Data Fields
std::map< uint32, TimePoint > m_lastPacket
Static Public Attributes
static std::vector< uint32 > m_packetCooldowns = InitOpcodeCooldowns()
Private Member Functions
virtual bool ProcessIncomingData () override
process one incoming packet.
bool HandleAuthSession (WorldPacket &recvPacket)
Called by ProcessIncoming() on CMSG_AUTH_SESSION.
bool HandlePing (WorldPacket &recvPacket)
Called by ProcessIncoming() on CMSG_PING.
Private Attributes
std::chrono::system_clock::time_point m_lastPingTime
Time in which the last ping was received.
uint32 m_overSpeedPings
Keep track of over-speed pings ,to prevent ping flood.
ClientPktHeader m_existingHeader
bool m_useExistingHeader
AuthCrypt m_crypt
Class used for managing encryption of the headers.
WorldSession * m_session
Session to which received packets are routed.
const uint32 m_seed
BigNumber m_s
std::mutex m_worldSocketMutex
std::deque< uint32 > m_opcodeHistoryOut
std::deque< uint32 > m_opcodeHistoryInc
bool m_loggingPackets
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Socket
const uint8 * InPeak () const
int ReadLengthRemaining () const
void ForceFlushOut ()
Protected Attributes inherited from MaNGOS::Socket
const std::string m_address
const std::string m_remoteEndpoint
boost::asio::ip::address m_remoteAddress
uint16 m_remotePort
Detailed Description
WorldSocket.
This class is responsible for the communication with remote clients. Most methods return -1 on failure. The class uses reference counting.
For output the class uses one buffer (64K usually) and a queue where it stores packet if there is no place on the queue. The reason this is done, is because the server does really a lot of small-size writes to it, and it doesn't scale well to allocate memory for every. When something is written to the output buffer the socket is not immediately activated for output (again for the same reason), there is 10ms celling (thats why there is Update() override method). This concept is similar to TCP_CORK, but TCP_CORK uses 200ms celling. As result overhead generated by sending packets from "producer" threads is minimal, and doing a lot of writes with small size is tolerated.
The calls to Update () method are managed by WorldSocketMgr and ReactorRunnable.
For input ,the class uses one 1024 bytes buffer on stack to which it does recv() calls. And then received data is distributed where its needed. 1024 matches pretty well the traffic generated by client for now.
The input/output do speculative reads/writes (AKA it tries to read all data available in the kernel buffer or tries to write everything available in userspace buffer), which is ok for using with Level and Edge Triggered IO notification.
Definition at line 77 of file WorldSocket.h.
Constructor & Destructor Documentation
WorldSocket()
WorldSocket::WorldSocket (boost::asio::io_service & service, std::function< void(Socket *)> closeHandler)
Definition at line 115 of file WorldSocket.cpp.
Member Function Documentation
FinalizeSession()
void WorldSocket::FinalizeSession () inline
Definition at line 137 of file WorldSocket.h.
References m_session.
GetIncOpcodeHistory()
std::deque< uint32 > WorldSocket::GetIncOpcodeHistory ()
Definition at line 109 of file WorldSocket.cpp.
References m_opcodeHistoryInc, and m_worldSocketMutex.
GetOutOpcodeHistory()
std::deque< uint32 > WorldSocket::GetOutOpcodeHistory ()
Definition at line 103 of file WorldSocket.cpp.
References m_opcodeHistoryOut, and m_worldSocketMutex.
GetSessionKey()
BigNumber& WorldSocket::GetSessionKey () inline
Return the session key.
Definition at line 142 of file WorldSocket.h.
References m_s.
HandleAuthSession()
bool WorldSocket::HandleAuthSession (WorldPacket & recvPacket) private
Called by ProcessIncoming() on CMSG_AUTH_SESSION.
Re-check ip locking (same check as in realmd).
Definition at line 317 of file WorldSocket.cpp.
References Messager< T >::AddMessage(), BigNumber::AsHexStr(), WorldSession::AssignAnticheat(), AUTH_BANNED, AUTH_FAILED, AUTH_UNAVAILABLE, AUTH_UNKNOWN_ACCOUNT, AUTH_VERSION_MISMATCH, BASIC_LOG, CLIENT_OS_MAC, CLIENT_OS_WIN, CLIENT_PLATFORM_PPC, CLIENT_PLATFORM_X86, CONFIG_UINT32_EXPANSION, Database::CreateStatement(), DEBUG_LOG, Database::escape_string(), QueryResult::Fetch(), CryptoHash< Algorithm, DigestSize >::Finalize(), WorldSession::GetAnticheat(), CryptoHash< Algorithm, DigestSize >::GetDigest(), GetLocaleByName(), WorldSession::GetMessager(), MaNGOS::Socket::GetRemoteAddress(), WorldSession::GetState(), Field::GetString(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), AuthCrypt::Init(), WorldPacket::Initialize(), WorldSession::InitializeAnticheat(), IsAcceptableClientBuild(), MaNGOS::Socket::IsClosed(), WorldSession::LoadGlobalAccountData(), WorldSession::LoadTutorialsData(), LOGIN_TYPE_MANGOSD, LoginDatabase, m_crypt, m_s, m_seed, m_session, SqlStatement::PExecute(), Database::PQuery(), ByteBuffer::read(), ByteBuffer::read_skip(), SessionAnticheatInterface::ReadAddonInfo(), WorldSession::RequestNewSocket(), sAnticheatLib, SEC_ADMINISTRATOR, SEC_GAMEMASTER, SEC_PLAYER, WorldSession::SendAuthOk(), SendPacket(), WorldSession::SetDelayedAnticheat(), BigNumber::SetDword(), WorldSession::SetGameBuild(), BigNumber::SetHexStr(), WorldSession::SetOS(), WorldSession::SetPlatform(), sLog, SMSG_AUTH_RESPONSE, sWorld, sWorldState, CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), CryptoHash< Algorithm, DigestSize >::UpdateData(), and WORLD_SESSION_STATE_CHAR_SELECTION.
Referenced by ProcessIncomingData().
HandlePing()
bool WorldSocket::HandlePing (WorldPacket & recvPacket) private
Called by ProcessIncoming() on CMSG_PING.
Definition at line 647 of file WorldSocket.cpp.
References CONFIG_UINT32_MAX_OVERSPEED_PINGS, MaNGOS::Socket::GetRemoteAddress(), WorldSession::GetSecurity(), m_lastPingTime, m_overSpeedPings, m_session, WorldSession::ResetClientTimeDelay(), SEC_PLAYER, SendPacket(), WorldSession::SetLatency(), sLog, SMSG_PONG, and sWorld.
Referenced by ProcessIncomingData().
IsLoggingPackets()
bool WorldSocket::IsLoggingPackets () const inline
Definition at line 150 of file WorldSocket.h.
References m_loggingPackets.
Referenced by ProcessIncomingData(), and SendPacket().
Open()
bool WorldSocket::Open () override virtual
Reimplemented from MaNGOS::Socket.
Definition at line 150 of file WorldSocket.cpp.
References ByteBuffer::append(), BigNumber::AsByteArray(), m_seed, SendPacket(), BigNumber::SetRand(), and SMSG_AUTH_CHALLENGE.
ProcessIncomingData()
bool WorldSocket::ProcessIncomingData () override private virtual
process one incoming packet.
Implements MaNGOS::Socket.
Definition at line 173 of file WorldSocket.cpp.
References CLIENT_TO_SERVER, WorldSocket::ClientPktHeader::cmd, CMSG_AUTH_SESSION, CMSG_KEEP_ALIVE, CMSG_PING, CMSG_TIME_SYNC_RESP, CONFIG_BOOL_KICK_PLAYER_ON_BAD_PACKET, DEBUG_LOG, AuthCrypt::DecryptRecv(), DETAIL_LOG, EndianConvert(), EndianConvertReverse(), WorldSession::GetAccountId(), MaNGOS::Socket::GetRemoteAddress(), MaNGOS::Socket::GetRemoteEndpoint(), MaNGOS::Socket::GetRemoteIpAddress(), MaNGOS::Socket::GetRemotePort(), HandleAuthSession(), HandlePing(), MaNGOS::Socket::InPeak(), MaNGOS::Socket::IsClosed(), IsLoggingPackets(), LOG_LVL_DEBUG, m_crypt, m_existingHeader, m_lastPacket, m_opcodeHistoryInc, m_packetCooldowns, m_session, m_useExistingHeader, NUM_MSG_TYPES, WorldSession::QueuePacket(), MaNGOS::Socket::Read(), MaNGOS::Socket::ReadLengthRemaining(), MaNGOS::Socket::ReadSkip(), WorldSocket::ClientPktHeader::size, SIZEFMTD, sLog, sPacketLog, and sWorld.
SendPacket()
void WorldSocket::SendPacket (const WorldPacket & pct, bool immediate = false)
Definition at line 120 of file WorldSocket.cpp.
References ByteBuffer::contents(), ByteBuffer::empty(), AuthCrypt::EncryptSend(), MaNGOS::Socket::ForceFlushOut(), ServerPktHeader::getHeaderLength(), WorldPacket::GetOpcode(), WorldPacket::GetOpcodeName(), MaNGOS::Socket::GetRemoteEndpoint(), MaNGOS::Socket::GetRemoteIpAddress(), MaNGOS::Socket::GetRemotePort(), ServerPktHeader::header, MaNGOS::Socket::IsClosed(), IsLoggingPackets(), m_crypt, m_opcodeHistoryOut, m_worldSocketMutex, SERVER_TO_CLIENT, ByteBuffer::size(), sLog, sPacketLog, and MaNGOS::Socket::Write().
Referenced by HandleAuthSession(), HandlePing(), and Open().
SetPacketLogging()
void WorldSocket::SetPacketLogging (bool state) inline
Definition at line 151 of file WorldSocket.h.
References m_loggingPackets.
Field Documentation
m_crypt
AuthCrypt WorldSocket::m_crypt private
Class used for managing encryption of the headers.
Definition at line 106 of file WorldSocket.h.
Referenced by HandleAuthSession(), ProcessIncomingData(), and SendPacket().
m_existingHeader
ClientPktHeader WorldSocket::m_existingHeader private
Definition at line 102 of file WorldSocket.h.
Referenced by ProcessIncomingData().
m_lastPacket
std::map<uint32, TimePoint> WorldSocket::m_lastPacket
Definition at line 148 of file WorldSocket.h.
Referenced by ProcessIncomingData().
m_lastPingTime
std::chrono::system_clock::time_point WorldSocket::m_lastPingTime private
Time in which the last ping was received.
Definition at line 97 of file WorldSocket.h.
Referenced by HandlePing().
m_loggingPackets
bool WorldSocket::m_loggingPackets private
Definition at line 129 of file WorldSocket.h.
Referenced by IsLoggingPackets(), and SetPacketLogging().
m_opcodeHistoryInc
std::deque<uint32> WorldSocket::m_opcodeHistoryInc private
Definition at line 127 of file WorldSocket.h.
Referenced by GetIncOpcodeHistory(), and ProcessIncomingData().
m_opcodeHistoryOut
std::deque<uint32> WorldSocket::m_opcodeHistoryOut private
Definition at line 126 of file WorldSocket.h.
Referenced by GetOutOpcodeHistory(), and SendPacket().
m_overSpeedPings
uint32 WorldSocket::m_overSpeedPings private
Keep track of over-speed pings ,to prevent ping flood.
Definition at line 100 of file WorldSocket.h.
Referenced by HandlePing().
m_packetCooldowns
std::vector< uint32 > WorldSocket::m_packetCooldowns = InitOpcodeCooldowns() static
Definition at line 147 of file WorldSocket.h.
Referenced by ProcessIncomingData().
m_s
BigNumber WorldSocket::m_s private
Definition at line 113 of file WorldSocket.h.
Referenced by GetSessionKey(), and HandleAuthSession().
m_seed
const uint32 WorldSocket::m_seed private
Definition at line 111 of file WorldSocket.h.
Referenced by HandleAuthSession(), and Open().
m_session
WorldSession* WorldSocket::m_session private
Session to which received packets are routed.
Definition at line 109 of file WorldSocket.h.
Referenced by FinalizeSession(), HandleAuthSession(), HandlePing(), and ProcessIncomingData().
m_useExistingHeader
bool WorldSocket::m_useExistingHeader private
Definition at line 103 of file WorldSocket.h.
Referenced by ProcessIncomingData().
m_worldSocketMutex
std::mutex WorldSocket::m_worldSocketMutex private
Definition at line 124 of file WorldSocket.h.
Referenced by GetIncOpcodeHistory(), GetOutOpcodeHistory(), and SendPacket().
The documentation for this class was generated from the following files:
WorldSocket.h
WorldSocket.cpp