CMaNGOS_WoTLK: QuestMenu Class Reference
QuestMenu Class Reference
#include <GossipDef.h>
Public Member Functions
QuestMenu ()
~QuestMenu ()
void AddMenuItem (uint32 QuestId, uint8 Icon)
void ClearMenu ()
uint8 MenuItemCount () const
bool Empty () const
bool HasItem (uint32 questid)
QuestMenuItem const & GetItem (uint16 Id)
Protected Attributes
QuestMenuItemList m_qItems
Detailed Description
Definition at line 236 of file GossipDef.h.
Constructor & Destructor Documentation
QuestMenu()
QuestMenu::QuestMenu ()
Definition at line 254 of file GossipDef.cpp.
References m_qItems.
~QuestMenu()
QuestMenu::~QuestMenu ()
Definition at line 259 of file GossipDef.cpp.
References ClearMenu().
Member Function Documentation
AddMenuItem()
void QuestMenu::AddMenuItem (uint32 QuestId, uint8 Icon)
Definition at line 264 of file GossipDef.cpp.
References GOSSIP_MAX_MENU_ITEMS, QuestMenuItem::m_qIcon, QuestMenuItem::m_qId, m_qItems, MANGOS_ASSERT, and sObjectMgr.
Referenced by Player::PrepareQuestMenu().
ClearMenu()
void QuestMenu::ClearMenu ()
Definition at line 288 of file GossipDef.cpp.
References m_qItems.
Referenced by PlayerMenu::ClearMenus(), Player::PrepareQuestMenu(), and ~QuestMenu().
Empty()
bool QuestMenu::Empty () const inline
Definition at line 250 of file GossipDef.h.
References m_qItems.
Referenced by PlayerMenu::Empty(), Player::SendPreparedGossip(), and Player::SendPreparedQuest().
GetItem()
QuestMenuItem const& QuestMenu::GetItem (uint16 Id) inline
Definition at line 257 of file GossipDef.h.
References m_qItems.
Referenced by PlayerbotAI::CastSpell(), PlayerbotAI::HandleCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), PlayerbotAI::ListQuests(), PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), PlayerMenu::SendQuestGiverQuestList(), and PlayerbotAI::TurnInQuests().
HasItem()
bool QuestMenu::HasItem (uint32 questid)
Definition at line 280 of file GossipDef.cpp.
References m_qItems.
MenuItemCount()
uint8 QuestMenu::MenuItemCount () const inline
Definition at line 245 of file GossipDef.h.
References m_qItems.
Referenced by PlayerbotAI::CastSpell(), PlayerbotAI::HandleCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), PlayerbotAI::ListQuests(), PlayerMenu::SendGossipMenu(), Player::SendPreparedQuest(), PlayerMenu::SendQuestGiverQuestList(), and PlayerbotAI::TurnInQuests().
Field Documentation
m_qItems
QuestMenuItemList QuestMenu::m_qItems protected
Definition at line 263 of file GossipDef.h.
Referenced by AddMenuItem(), ClearMenu(), Empty(), GetItem(), HasItem(), MenuItemCount(), and QuestMenu().
The documentation for this class was generated from the following files:
GossipDef.h
GossipDef.cpp