CMaNGOS_WoTLK: Config Class Reference
Config Class Reference
#include <Config.h>
Public Member Functions
bool SetSource (const std::string &file)
bool Reload ()
bool IsSet (const std::string &name) const
const std::string GetStringDefault (const std::string &name, const std::string &def="") const
bool GetBoolDefault (const std::string &name, bool def) const
int32 GetIntDefault (const std::string &name, int32 def) const
float GetFloatDefault (const std::string &name, float def) const
const std::string & GetFilename () const
Data Fields
std::mutex m_configLock
Private Attributes
std::string m_filename
std::unordered_map< std::string, std::string > m_entries
Detailed Description
Definition at line 30 of file Config.h.
Member Function Documentation
GetBoolDefault()
bool Config::GetBoolDefault (const std::string & name, bool def) const
Definition at line 92 of file Config.cpp.
References GetStringDefault().
Referenced by PlayerbotMgr::HandleMasterIncomingPacket(), AuctionHouseBot::Initialize(), PlayerbotMgr::PlayerbotMgr(), Player::PrepareGossipMenu(), Group::RemoveMember(), and NamreebAnticheat::AnticheatConfig::setConfig().
GetFilename()
const std::string& Config::GetFilename () const inline
Definition at line 47 of file Config.h.
References m_filename.
GetFloatDefault()
float Config::GetFloatDefault (const std::string & name, float def) const
Definition at line 109 of file Config.cpp.
References GetStringDefault().
Referenced by PlayerbotMgr::PlayerbotMgr(), and NamreebAnticheat::AnticheatConfig::setConfig().
GetIntDefault()
int32 Config::GetIntDefault (const std::string & name, int32 def) const
Definition at line 102 of file Config.cpp.
References GetStringDefault().
Referenced by AuctionHouseBot::GetMinMaxConfig(), NamreebAnticheat::AnticheatConfig::loadConfigSettings(), Player::OnGossipSelect(), PlayerbotMgr::PlayerbotMgr(), Player::PrepareGossipMenu(), NamreebAnticheat::AnticheatConfig::setConfig(), and PlayerbotMgr::SetInitialWorldSettings().
GetStringDefault()
const std::string Config::GetStringDefault (const std::string & name, const std::string & def = "") const
Definition at line 83 of file Config.cpp.
References m_entries.
Referenced by GetBoolDefault(), GetFloatDefault(), GetIntDefault(), NamreebAnticheat::AnticheatConfig::loadConfigSettings(), AuctionHouseBot::ParseItemValueConfig(), AuctionHouseBot::ParseLootConfig(), and Player::PrepareGossipMenu().
IsSet()
bool Config::IsSet (const std::string & name) const
Definition at line 77 of file Config.cpp.
References m_entries.
Reload()
bool Config::Reload ()
Definition at line 38 of file Config.cpp.
References m_configLock, m_entries, and m_filename.
Referenced by SetSource().
SetSource()
bool Config::SetSource (const std::string & file)
Definition at line 31 of file Config.cpp.
References m_filename, and Reload().
Referenced by AuctionHouseBot::Initialize(), and PlayerbotMgr::SetInitialWorldSettings().
Field Documentation
m_configLock
std::mutex Config::m_configLock
Definition at line 48 of file Config.h.
Referenced by Reload().
m_entries
std::unordered_map<std::string, std::string> Config::m_entries private
Definition at line 34 of file Config.h.
Referenced by GetStringDefault(), IsSet(), and Reload().
m_filename
std::string Config::m_filename private
Definition at line 33 of file Config.h.
Referenced by GetFilename(), Reload(), and SetSource().
The documentation for this class was generated from the following files:
Config.h
Config.cpp