CMaNGOS_WoTLK: PlayerbotShamanAI Class Reference
PlayerbotShamanAI Class Reference
#include <PlayerbotShamanAI.h>
Public Member Functions
PlayerbotShamanAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotShamanAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
void DoNonCombatActions () override
bool CastHoTOnTank ()
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns HealPlayer (Player *target) override
CombatManeuverReturns ResurrectPlayer (Player *target) override
CombatManeuverReturns DispelPlayer (Player *target=nullptr)
void DropTotems ()
void CheckShields ()
void UseCooldowns ()
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Private Attributes
uint32 ROCKBITER_WEAPON
uint32 STONESKIN_TOTEM
uint32 LIGHTNING_SHIELD
uint32 FLAMETONGUE_WEAPON
uint32 STRENGTH_OF_EARTH_TOTEM
uint32 FOCUSED
uint32 FROSTBRAND_WEAPON
uint32 FROST_RESISTANCE_TOTEM
uint32 FLAMETONGUE_TOTEM
uint32 FIRE_RESISTANCE_TOTEM
uint32 WINDFURY_WEAPON
uint32 GROUNDING_TOTEM
uint32 NATURE_RESISTANCE_TOTEM
uint32 WIND_FURY_TOTEM
uint32 STORMSTRIKE
uint32 LAVA_LASH
uint32 SHAMANISTIC_RAGE
uint32 WRATH_OF_AIR_TOTEM
uint32 EARTH_ELEMENTAL_TOTEM
uint32 BLOODLUST
uint32 HEROISM
uint32 FERAL_SPIRIT
uint32 MAELSTROM_WEAPON
uint32 HEALING_WAVE
uint32 LESSER_HEALING_WAVE
uint32 ANCESTRAL_SPIRIT
uint32 TREMOR_TOTEM
uint32 HEALING_STREAM_TOTEM
uint32 MANA_SPRING_TOTEM
uint32 CHAIN_HEAL
uint32 MANA_TIDE_TOTEM
uint32 EARTH_SHIELD
uint32 WATER_SHIELD
uint32 EARTHLIVING_WEAPON
uint32 RIPTIDE
uint32 CURE_TOXINS
uint32 CLEANSE_SPIRIT
uint32 NATURES_SWIFTNESS_SHAMAN
uint32 TIDAL_FORCE
uint32 LIGHTNING_BOLT
uint32 EARTH_SHOCK
uint32 STONECLAW_TOTEM
uint32 FLAME_SHOCK
uint32 SEARING_TOTEM
uint32 PURGE
uint32 FIRE_NOVA_TOTEM
uint32 WIND_SHOCK
uint32 FROST_SHOCK
uint32 MAGMA_TOTEM
uint32 CHAIN_LIGHTNING
uint32 TOTEM_OF_WRATH
uint32 FIRE_ELEMENTAL_TOTEM
uint32 LAVA_BURST
uint32 EARTHBIND_TOTEM
uint32 HEX
uint32 ELEMENTAL_MASTERY
uint32 THUNDERSTORM
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 STRENGTH_OF_EARTH_EFFECT
uint32 FLAMETONGUE_EFFECT
uint32 MAGMA_TOTEM_EFFECT
uint32 STONECLAW_EFFECT
uint32 FIRE_RESISTANCE_EFFECT
uint32 FROST_RESISTANCE_EFFECT
uint32 GROUDNING_EFFECT
uint32 NATURE_RESISTANCE_EFFECT
uint32 STONESKIN_EFFECT
uint32 WINDFURY_EFFECT
uint32 WRATH_OF_AIR_EFFECT
uint32 CLEANSING_TOTEM_EFFECT
uint32 HEALING_STREAM_EFFECT
uint32 MANA_SPRING_EFFECT
uint32 TREMOR_TOTEM_EFFECT
uint32 TOTEM_OF_WRATH_EFFECT
uint32 EARTHBIND_EFFECT
uint32 IMPROVED_ICY_TALONS
uint32 HORN_OF_WINTER
uint32 SpellSequence
uint32 LastSpellEnhancement
uint32 LastSpellRestoration
uint32 LastSpellElemental
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 131 of file PlayerbotShamanAI.h.
Constructor & Destructor Documentation
PlayerbotShamanAI()
PlayerbotShamanAI::PlayerbotShamanAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 25 of file PlayerbotShamanAI.cpp.
References ANCESTRAL_SPIRIT, ANCESTRAL_SPIRIT_1, BERSERKING, BERSERKING_ALL, BLOOD_FURY, BLOOD_FURY_SHAMAN, BLOODLUST, BLOODLUST_1, CHAIN_HEAL, CHAIN_HEAL_1, CHAIN_LIGHTNING, CHAIN_LIGHTNING_1, CLEANSE_SPIRIT, CLEANSE_SPIRIT_1, CLEANSING_TOTEM_EFFECT, CLEANSING_TOTEM_EFFECT_1, CURE_TOXINS, CURE_TOXINS_1, EARTH_ELEMENTAL_TOTEM, EARTH_ELEMENTAL_TOTEM_1, EARTH_SHIELD, EARTH_SHIELD_1, EARTH_SHOCK, EARTH_SHOCK_1, EARTHBIND_EFFECT, EARTHBIND_EFFECT_1, EARTHBIND_TOTEM, EARTHBIND_TOTEM_1, EARTHLIVING_WEAPON, EARTHLIVING_WEAPON_1, ELEMENTAL_MASTERY, ELEMENTAL_MASTERY_1, FERAL_SPIRIT, FERAL_SPIRIT_1, FIRE_ELEMENTAL_TOTEM, FIRE_ELEMENTAL_TOTEM_1, FIRE_NOVA_TOTEM, FIRE_RESISTANCE_EFFECT, FIRE_RESISTANCE_EFFECT_1, FIRE_RESISTANCE_TOTEM, FIRE_RESISTANCE_TOTEM_1, FLAME_SHOCK, FLAME_SHOCK_1, FLAMETONGUE_EFFECT, FLAMETONGUE_EFFECT_1, FLAMETONGUE_TOTEM, FLAMETONGUE_TOTEM_1, FLAMETONGUE_WEAPON, FLAMETONGUE_WEAPON_1, FOCUSED, FROST_RESISTANCE_EFFECT, FROST_RESISTANCE_EFFECT_1, FROST_RESISTANCE_TOTEM, FROST_RESISTANCE_TOTEM_1, FROST_SHOCK, FROST_SHOCK_1, FROSTBRAND_WEAPON, FROSTBRAND_WEAPON_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_SHAMAN, GROUDNING_EFFECT, GROUDNING_EFFECT_1, GROUNDING_TOTEM, GROUNDING_TOTEM_1, HEALING_STREAM_EFFECT, HEALING_STREAM_EFFECT_1, HEALING_STREAM_TOTEM, HEALING_STREAM_TOTEM_1, HEALING_WAVE, HEALING_WAVE_1, HEROISM, HEROISM_1, HEX, HEX_1, HORN_OF_WINTER, HORN_OF_WINTER_1, IMPROVED_ICY_TALONS, IMPROVED_ICY_TALONS_1, PlayerbotAI::initSpell(), LAVA_BURST, LAVA_BURST_1, LAVA_LASH, LAVA_LASH_1, LESSER_HEALING_WAVE, LESSER_HEALING_WAVE_1, LIGHTNING_BOLT, LIGHTNING_BOLT_1, LIGHTNING_SHIELD, LIGHTNING_SHIELD_1, PlayerbotClassAI::m_ai, MAELSTROM_WEAPON, MAELSTROM_WEAPON_1, MAGMA_TOTEM, MAGMA_TOTEM_1, MAGMA_TOTEM_EFFECT, MAGMA_TOTEM_EFFECT_1, MANA_SPRING_EFFECT, MANA_SPRING_EFFECT_1, MANA_SPRING_TOTEM, MANA_SPRING_TOTEM_1, MANA_TIDE_TOTEM, MANA_TIDE_TOTEM_1, NATURE_RESISTANCE_EFFECT, NATURE_RESISTANCE_EFFECT_1, NATURE_RESISTANCE_TOTEM, NATURE_RESISTANCE_TOTEM_1, NATURES_SWIFTNESS_SHAMAN, NATURES_SWIFTNESS_SHAMAN_1, PURGE, PURGE_1, PlayerbotClassAI::RECENTLY_BANDAGED, RIPTIDE, RIPTIDE_1, ROCKBITER_WEAPON, ROCKBITER_WEAPON_1, SEARING_TOTEM, SEARING_TOTEM_1, SHAMANISTIC_RAGE, SHAMANISTIC_RAGE_1, STONECLAW_EFFECT, STONECLAW_EFFECT_1, STONECLAW_TOTEM, STONECLAW_TOTEM_1, STONESKIN_EFFECT, STONESKIN_EFFECT_1, STONESKIN_TOTEM, STONESKIN_TOTEM_1, STORMSTRIKE, STORMSTRIKE_1, STRENGTH_OF_EARTH_EFFECT, STRENGTH_OF_EARTH_EFFECT_1, STRENGTH_OF_EARTH_TOTEM, STRENGTH_OF_EARTH_TOTEM_1, THUNDERSTORM, THUNDERSTORM_1, TIDAL_FORCE, TIDAL_FORCE_1, TOTEM_OF_WRATH, TOTEM_OF_WRATH_1, TOTEM_OF_WRATH_EFFECT, TOTEM_OF_WRATH_EFFECT_1, TREMOR_TOTEM, TREMOR_TOTEM_1, TREMOR_TOTEM_EFFECT, TREMOR_TOTEM_EFFECT_1, WAR_STOMP, WAR_STOMP_ALL, WATER_SHIELD, WATER_SHIELD_1, WIND_FURY_TOTEM, WIND_SHOCK, WINDFURY_EFFECT, WINDFURY_EFFECT_1, WINDFURY_TOTEM_1, WINDFURY_WEAPON, WINDFURY_WEAPON_1, WRATH_OF_AIR_EFFECT, WRATH_OF_AIR_EFFECT_1, WRATH_OF_AIR_TOTEM, and WRATH_OF_AIR_TOTEM_1.
~PlayerbotShamanAI()
PlayerbotShamanAI::~PlayerbotShamanAI () virtual
Definition at line 122 of file PlayerbotShamanAI.cpp.
Member Function Documentation
CastHoTOnTank()
bool PlayerbotShamanAI::CastHoTOnTank ()
Definition at line 554 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::IsHealer(), and PlayerbotClassAI::m_ai.
CheckShields()
void PlayerbotShamanAI::CheckShields () private
Definition at line 442 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), EARTH_SHIELD, EFFECT_INDEX_0, Unit::HasAura(), LIGHTNING_SHIELD, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_master, SHAMAN_SPEC_ELEMENTAL, SHAMAN_SPEC_ENHANCEMENT, SHAMAN_SPEC_RESTORATION, and WATER_SHIELD.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and DoNonCombatActions().
DispelPlayer()
CombatManeuverReturns PlayerbotShamanAI::DispelPlayer (Player * target = nullptr) private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 325 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), CLEANSE_SPIRIT, CURE_TOXINS, DISPEL_CURSE, DISPEL_DISEASE, DISPEL_POISON, PlayerbotClassAI::DispelPlayer(), PlayerbotClassAI::GetDispelTarget(), PlayerbotClassAI::m_ai, RETURN_CONTINUE, RETURN_NO_ACTION_OK, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotShamanAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 124 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotClassAI::GetHealTarget(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), HealPlayer(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_HEAL, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotShamanAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 166 of file PlayerbotShamanAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotShamanAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 171 of file PlayerbotShamanAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotShamanAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 176 of file PlayerbotShamanAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotShamanAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 193 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), CheckShields(), PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, DispelPlayer(), DropTotems(), EARTH_SHOCK, PlayerbotClassAI::FindTargetAndHeal(), FLAME_SHOCK, PlayerbotAI::GetCombatStyle(), Unit::HasAura(), PlayerbotAI::HasDispelOrder(), PlayerbotAI::IsHealer(), WorldObject::IsSpellReady(), LAVA_BURST, LAVA_LASH, LIGHTNING_BOLT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MAELSTROM_WEAPON, RETURN_CONTINUE, RETURN_NO_ACTION_OK, PlayerbotAI::SetCombatStyle(), SHAMAN_SPEC_ELEMENTAL, SHAMAN_SPEC_ENHANCEMENT, SHAMAN_SPEC_RESTORATION, SPELL_CAST_OK, STORMSTRIKE, and UseCooldowns().
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotShamanAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 255 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), CheckShields(), DoNextCombatManeuverPVE(), DropTotems(), PlayerbotClassAI::GetHealTarget(), PlayerbotAI::GetScenarioType(), HealPlayer(), LIGHTNING_BOLT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, RETURN_CONTINUE, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVP_DUEL, SPELL_CAST_OK, and UseCooldowns().
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotShamanAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 492 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), CheckShields(), DispelPlayer(), EARTHLIVING_WEAPON, PlayerbotClassAI::EatDrinkBandage(), EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, FLAMETONGUE_WEAPON, Item::GetEnchantmentId(), PlayerbotClassAI::GetHealTarget(), Player::GetItemByPos(), PlayerbotClassAI::GetResurrectionTarget(), PlayerbotAI::HasDispelOrder(), HealPlayer(), Unit::IsAlive(), PlayerbotAI::IsHealer(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, ResurrectPlayer(), RETURN_CONTINUE, SHAMAN_SPEC_ELEMENTAL, SHAMAN_SPEC_ENHANCEMENT, SHAMAN_SPEC_RESTORATION, TEMP_ENCHANTMENT_SLOT, and WINDFURY_WEAPON.
DropTotems()
void PlayerbotShamanAI::DropTotems () private
Definition at line 364 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), FIRE_RESISTANCE_TOTEM, FLAMETONGUE_TOTEM, FROST_RESISTANCE_TOTEM, PlayerbotAI::GetCombatOrder(), WorldObject::GetDistance(), Unit::GetTotem(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MANA_SPRING_TOTEM, NATURE_RESISTANCE_TOTEM, PlayerbotAI::ORDERS_RESIST_FIRE, PlayerbotAI::ORDERS_RESIST_FROST, PlayerbotAI::ORDERS_RESIST_NATURE, SHAMAN_SPEC_ELEMENTAL, SHAMAN_SPEC_ENHANCEMENT, SPELL_CAST_OK, STRENGTH_OF_EARTH_TOTEM, TOTEM_OF_WRATH, TOTEM_SLOT_AIR, TOTEM_SLOT_EARTH, TOTEM_SLOT_FIRE, TOTEM_SLOT_WATER, WIND_FURY_TOTEM, and WRATH_OF_AIR_TOTEM.
Referenced by DoNextCombatManeuverPVE(), and DoNextCombatManeuverPVP().
HealPlayer()
CombatManeuverReturns PlayerbotShamanAI::HealPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 270 of file PlayerbotShamanAI.cpp.
References PlayerbotAI::CastSpell(), CHAIN_HEAL, EFFECT_INDEX_0, Unit::GetHealthPercent(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), PlayerbotClassAI::GetTargetJob(), Unit::HasAura(), HEALING_WAVE, PlayerbotClassAI::HealPlayer(), PlayerbotAI::In_Reach(), JOB_MAIN_TANK, JOB_TANK, LESSER_HEALING_WAVE, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), PlayerbotAI::MOVEMENT_STAY, RETURN_CONTINUE, RETURN_NO_ACTION_OK, RETURN_NO_ACTION_UNKNOWN, RIPTIDE, and SPELL_CAST_OK.
Referenced by DoFirstCombatManeuver(), DoNextCombatManeuverPVP(), and DoNonCombatActions().
ResurrectPlayer()
CombatManeuverReturns PlayerbotShamanAI::ResurrectPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 306 of file PlayerbotShamanAI.cpp.
References ANCESTRAL_SPIRIT, PlayerbotAI::CastSpell(), WorldObject::GetName(), PlayerbotAI::In_Reach(), PlayerbotAI::IsInCombat(), LANG_UNIVERSAL, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::ResurrectPlayer(), RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, Player::Say(), and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
UseCooldowns()
void PlayerbotShamanAI::UseCooldowns () private
Definition at line 454 of file PlayerbotShamanAI.cpp.
References BLOODLUST, PlayerbotAI::CastSpell(), EFFECT_INDEX_0, ELEMENTAL_MASTERY, FERAL_SPIRIT, PlayerbotAI::GetManaPercent(), Unit::HasAura(), HEROISM, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_master, MANA_TIDE_TOTEM, NATURES_SWIFTNESS_SHAMAN, SHAMAN_SPEC_ELEMENTAL, SHAMAN_SPEC_ENHANCEMENT, SHAMAN_SPEC_RESTORATION, SHAMANISTIC_RAGE, SPELL_CAST_OK, THUNDERSTORM, and TIDAL_FORCE.
Referenced by DoNextCombatManeuverPVE(), and DoNextCombatManeuverPVP().
Field Documentation
ANCESTRAL_SPIRIT
uint32 PlayerbotShamanAI::ANCESTRAL_SPIRIT private
Definition at line 192 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and ResurrectPlayer().
ARCANE_TORRENT
uint32 PlayerbotShamanAI::ARCANE_TORRENT private
Definition at line 228 of file PlayerbotShamanAI.h.
BERSERKING
uint32 PlayerbotShamanAI::BERSERKING private
Definition at line 236 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
BLOOD_FURY
uint32 PlayerbotShamanAI::BLOOD_FURY private
Definition at line 234 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
BLOODLUST
uint32 PlayerbotShamanAI::BLOODLUST private
Definition at line 184 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
CHAIN_HEAL
uint32 PlayerbotShamanAI::CHAIN_HEAL private
Definition at line 196 of file PlayerbotShamanAI.h.
Referenced by HealPlayer(), and PlayerbotShamanAI().
CHAIN_LIGHTNING
uint32 PlayerbotShamanAI::CHAIN_LIGHTNING private
Definition at line 218 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
CLEANSE_SPIRIT
uint32 PlayerbotShamanAI::CLEANSE_SPIRIT private
Definition at line 203 of file PlayerbotShamanAI.h.
Referenced by DispelPlayer(), and PlayerbotShamanAI().
CLEANSING_TOTEM_EFFECT
uint32 PlayerbotShamanAI::CLEANSING_TOTEM_EFFECT private
Definition at line 251 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
CURE_TOXINS
uint32 PlayerbotShamanAI::CURE_TOXINS private
Definition at line 202 of file PlayerbotShamanAI.h.
Referenced by DispelPlayer(), and PlayerbotShamanAI().
EARTH_ELEMENTAL_TOTEM
uint32 PlayerbotShamanAI::EARTH_ELEMENTAL_TOTEM private
Definition at line 183 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
EARTH_SHIELD
uint32 PlayerbotShamanAI::EARTH_SHIELD private
Definition at line 198 of file PlayerbotShamanAI.h.
Referenced by CheckShields(), and PlayerbotShamanAI().
EARTH_SHOCK
uint32 PlayerbotShamanAI::EARTH_SHOCK private
Definition at line 209 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
EARTHBIND_EFFECT
uint32 PlayerbotShamanAI::EARTHBIND_EFFECT private
Definition at line 256 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
EARTHBIND_TOTEM
uint32 PlayerbotShamanAI::EARTHBIND_TOTEM private
Definition at line 222 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
EARTHLIVING_WEAPON
uint32 PlayerbotShamanAI::EARTHLIVING_WEAPON private
Definition at line 200 of file PlayerbotShamanAI.h.
Referenced by DoNonCombatActions(), and PlayerbotShamanAI().
ELEMENTAL_MASTERY
uint32 PlayerbotShamanAI::ELEMENTAL_MASTERY private
Definition at line 224 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
ESCAPE_ARTIST
uint32 PlayerbotShamanAI::ESCAPE_ARTIST private
Definition at line 231 of file PlayerbotShamanAI.h.
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotShamanAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 232 of file PlayerbotShamanAI.h.
FERAL_SPIRIT
uint32 PlayerbotShamanAI::FERAL_SPIRIT private
Definition at line 186 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
FIRE_ELEMENTAL_TOTEM
uint32 PlayerbotShamanAI::FIRE_ELEMENTAL_TOTEM private
Definition at line 220 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FIRE_NOVA_TOTEM
uint32 PlayerbotShamanAI::FIRE_NOVA_TOTEM private
Definition at line 214 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FIRE_RESISTANCE_EFFECT
uint32 PlayerbotShamanAI::FIRE_RESISTANCE_EFFECT private
Definition at line 244 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FIRE_RESISTANCE_TOTEM
uint32 PlayerbotShamanAI::FIRE_RESISTANCE_TOTEM private
Definition at line 174 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
FLAME_SHOCK
uint32 PlayerbotShamanAI::FLAME_SHOCK private
Definition at line 211 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
FLAMETONGUE_EFFECT
uint32 PlayerbotShamanAI::FLAMETONGUE_EFFECT private
Definition at line 241 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FLAMETONGUE_TOTEM
uint32 PlayerbotShamanAI::FLAMETONGUE_TOTEM private
Definition at line 173 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
FLAMETONGUE_WEAPON
uint32 PlayerbotShamanAI::FLAMETONGUE_WEAPON private
Definition at line 168 of file PlayerbotShamanAI.h.
Referenced by DoNonCombatActions(), and PlayerbotShamanAI().
FOCUSED
uint32 PlayerbotShamanAI::FOCUSED private
Definition at line 170 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FROST_RESISTANCE_EFFECT
uint32 PlayerbotShamanAI::FROST_RESISTANCE_EFFECT private
Definition at line 245 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FROST_RESISTANCE_TOTEM
uint32 PlayerbotShamanAI::FROST_RESISTANCE_TOTEM private
Definition at line 172 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
FROST_SHOCK
uint32 PlayerbotShamanAI::FROST_SHOCK private
Definition at line 216 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
FROSTBRAND_WEAPON
uint32 PlayerbotShamanAI::FROSTBRAND_WEAPON private
Definition at line 171 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotShamanAI::GIFT_OF_THE_NAARU private
Definition at line 229 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
GROUDNING_EFFECT
uint32 PlayerbotShamanAI::GROUDNING_EFFECT private
Definition at line 246 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
GROUNDING_TOTEM
uint32 PlayerbotShamanAI::GROUNDING_TOTEM private
Definition at line 176 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
HEALING_STREAM_EFFECT
uint32 PlayerbotShamanAI::HEALING_STREAM_EFFECT private
Definition at line 252 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
HEALING_STREAM_TOTEM
uint32 PlayerbotShamanAI::HEALING_STREAM_TOTEM private
Definition at line 194 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
HEALING_WAVE
uint32 PlayerbotShamanAI::HEALING_WAVE private
Definition at line 190 of file PlayerbotShamanAI.h.
Referenced by HealPlayer(), and PlayerbotShamanAI().
HEROISM
uint32 PlayerbotShamanAI::HEROISM private
Definition at line 185 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
HEX
uint32 PlayerbotShamanAI::HEX private
Definition at line 223 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
HORN_OF_WINTER
uint32 PlayerbotShamanAI::HORN_OF_WINTER private
Definition at line 260 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
IMPROVED_ICY_TALONS
uint32 PlayerbotShamanAI::IMPROVED_ICY_TALONS private
Definition at line 259 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
LastSpellElemental
uint32 PlayerbotShamanAI::LastSpellElemental private
Definition at line 262 of file PlayerbotShamanAI.h.
LastSpellEnhancement
uint32 PlayerbotShamanAI::LastSpellEnhancement private
Definition at line 262 of file PlayerbotShamanAI.h.
LastSpellRestoration
uint32 PlayerbotShamanAI::LastSpellRestoration private
Definition at line 262 of file PlayerbotShamanAI.h.
LAVA_BURST
uint32 PlayerbotShamanAI::LAVA_BURST private
Definition at line 221 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
LAVA_LASH
uint32 PlayerbotShamanAI::LAVA_LASH private
Definition at line 180 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
LESSER_HEALING_WAVE
uint32 PlayerbotShamanAI::LESSER_HEALING_WAVE private
Definition at line 191 of file PlayerbotShamanAI.h.
Referenced by HealPlayer(), and PlayerbotShamanAI().
LIGHTNING_BOLT
uint32 PlayerbotShamanAI::LIGHTNING_BOLT private
Definition at line 208 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotShamanAI().
LIGHTNING_SHIELD
uint32 PlayerbotShamanAI::LIGHTNING_SHIELD private
Definition at line 167 of file PlayerbotShamanAI.h.
Referenced by CheckShields(), and PlayerbotShamanAI().
MAELSTROM_WEAPON
uint32 PlayerbotShamanAI::MAELSTROM_WEAPON private
Definition at line 187 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
MAGMA_TOTEM
uint32 PlayerbotShamanAI::MAGMA_TOTEM private
Definition at line 217 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
MAGMA_TOTEM_EFFECT
uint32 PlayerbotShamanAI::MAGMA_TOTEM_EFFECT private
Definition at line 242 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
MANA_SPRING_EFFECT
uint32 PlayerbotShamanAI::MANA_SPRING_EFFECT private
Definition at line 253 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
MANA_SPRING_TOTEM
uint32 PlayerbotShamanAI::MANA_SPRING_TOTEM private
Definition at line 195 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
MANA_TIDE_TOTEM
uint32 PlayerbotShamanAI::MANA_TIDE_TOTEM private
Definition at line 197 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
NATURE_RESISTANCE_EFFECT
uint32 PlayerbotShamanAI::NATURE_RESISTANCE_EFFECT private
Definition at line 247 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
NATURE_RESISTANCE_TOTEM
uint32 PlayerbotShamanAI::NATURE_RESISTANCE_TOTEM private
Definition at line 177 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
NATURES_SWIFTNESS_SHAMAN
uint32 PlayerbotShamanAI::NATURES_SWIFTNESS_SHAMAN private
Definition at line 204 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
PURGE
uint32 PlayerbotShamanAI::PURGE private
Definition at line 213 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
RIPTIDE
uint32 PlayerbotShamanAI::RIPTIDE private
Definition at line 201 of file PlayerbotShamanAI.h.
Referenced by HealPlayer(), and PlayerbotShamanAI().
ROCKBITER_WEAPON
uint32 PlayerbotShamanAI::ROCKBITER_WEAPON private
Definition at line 165 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
SEARING_TOTEM
uint32 PlayerbotShamanAI::SEARING_TOTEM private
Definition at line 212 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
SHADOWMELD
uint32 PlayerbotShamanAI::SHADOWMELD private
Definition at line 233 of file PlayerbotShamanAI.h.
SHAMANISTIC_RAGE
uint32 PlayerbotShamanAI::SHAMANISTIC_RAGE private
Definition at line 181 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
SpellSequence
uint32 PlayerbotShamanAI::SpellSequence private
Definition at line 262 of file PlayerbotShamanAI.h.
STONECLAW_EFFECT
uint32 PlayerbotShamanAI::STONECLAW_EFFECT private
Definition at line 243 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
STONECLAW_TOTEM
uint32 PlayerbotShamanAI::STONECLAW_TOTEM private
Definition at line 210 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
STONEFORM
uint32 PlayerbotShamanAI::STONEFORM private
Definition at line 230 of file PlayerbotShamanAI.h.
STONESKIN_EFFECT
uint32 PlayerbotShamanAI::STONESKIN_EFFECT private
Definition at line 248 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
STONESKIN_TOTEM
uint32 PlayerbotShamanAI::STONESKIN_TOTEM private
Definition at line 166 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
STORMSTRIKE
uint32 PlayerbotShamanAI::STORMSTRIKE private
Definition at line 179 of file PlayerbotShamanAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotShamanAI().
STRENGTH_OF_EARTH_EFFECT
uint32 PlayerbotShamanAI::STRENGTH_OF_EARTH_EFFECT private
Definition at line 240 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
STRENGTH_OF_EARTH_TOTEM
uint32 PlayerbotShamanAI::STRENGTH_OF_EARTH_TOTEM private
Definition at line 169 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
THUNDERSTORM
uint32 PlayerbotShamanAI::THUNDERSTORM private
Definition at line 225 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
TIDAL_FORCE
uint32 PlayerbotShamanAI::TIDAL_FORCE private
Definition at line 205 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI(), and UseCooldowns().
TOTEM_OF_WRATH
uint32 PlayerbotShamanAI::TOTEM_OF_WRATH private
Definition at line 219 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
TOTEM_OF_WRATH_EFFECT
uint32 PlayerbotShamanAI::TOTEM_OF_WRATH_EFFECT private
Definition at line 255 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
TREMOR_TOTEM
uint32 PlayerbotShamanAI::TREMOR_TOTEM private
Definition at line 193 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
TREMOR_TOTEM_EFFECT
uint32 PlayerbotShamanAI::TREMOR_TOTEM_EFFECT private
Definition at line 254 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
WAR_STOMP
uint32 PlayerbotShamanAI::WAR_STOMP private
Definition at line 235 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
WATER_SHIELD
uint32 PlayerbotShamanAI::WATER_SHIELD private
Definition at line 199 of file PlayerbotShamanAI.h.
Referenced by CheckShields(), and PlayerbotShamanAI().
WILL_OF_THE_FORSAKEN
uint32 PlayerbotShamanAI::WILL_OF_THE_FORSAKEN private
Definition at line 237 of file PlayerbotShamanAI.h.
WIND_FURY_TOTEM
uint32 PlayerbotShamanAI::WIND_FURY_TOTEM private
Definition at line 178 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
WIND_SHOCK
uint32 PlayerbotShamanAI::WIND_SHOCK private
Definition at line 215 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
WINDFURY_EFFECT
uint32 PlayerbotShamanAI::WINDFURY_EFFECT private
Definition at line 249 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
WINDFURY_WEAPON
uint32 PlayerbotShamanAI::WINDFURY_WEAPON private
Definition at line 175 of file PlayerbotShamanAI.h.
Referenced by DoNonCombatActions(), and PlayerbotShamanAI().
WRATH_OF_AIR_EFFECT
uint32 PlayerbotShamanAI::WRATH_OF_AIR_EFFECT private
Definition at line 250 of file PlayerbotShamanAI.h.
Referenced by PlayerbotShamanAI().
WRATH_OF_AIR_TOTEM
uint32 PlayerbotShamanAI::WRATH_OF_AIR_TOTEM private
Definition at line 182 of file PlayerbotShamanAI.h.
Referenced by DropTotems(), and PlayerbotShamanAI().
The documentation for this class was generated from the following files:
PlayerbotShamanAI.h
PlayerbotShamanAI.cpp