CMaNGOS_WoTLK: SpellScriptMgr Class Reference
SpellScriptMgr Class Reference
#include <SpellScript.h>
Static Public Member Functions
static SpellScript * GetSpellScript (uint32 spellId)
static AuraScript * GetAuraScript (uint32 spellId)
static void SetSpellScript (std::string scriptName, SpellScript *script)
static void SetAuraScript (std::string scriptName, AuraScript *script)
static void LoadScripts ()
Static Private Member Functions
static SpellScript * GetSpellScript (std::string scriptName)
static AuraScript * GetAuraScript (std::string scriptName)
static void SetSpellScript (uint32 spellId, SpellScript *script)
static void SetAuraScript (uint32 spellId, AuraScript *script)
Static Private Attributes
static std::map< uint32, SpellScript * > m_spellScriptMap {}
static std::map< uint32, AuraScript * > m_auraScriptMap {}
static std::map< std::string, std::unique_ptr< SpellScript > > m_spellScriptStringMap {}
static std::map< std::string, std::unique_ptr< AuraScript > > m_auraScriptStringMap {}
Detailed Description
Definition at line 140 of file SpellScript.h.
Member Function Documentation
GetAuraScript() [1/2]
AuraScript * SpellScriptMgr::GetAuraScript (std::string scriptName) static private
Definition at line 120 of file SpellScript.cpp.
References m_auraScriptStringMap.
GetAuraScript() [2/2]
AuraScript * SpellScriptMgr::GetAuraScript (uint32 spellId) static
Definition at line 36 of file SpellScript.cpp.
References m_auraScriptMap.
Referenced by DynamicObject::Create(), and LoadScripts().
GetSpellScript() [1/2]
SpellScript * SpellScriptMgr::GetSpellScript (std::string scriptName) static private
Definition at line 112 of file SpellScript.cpp.
References m_spellScriptStringMap.
GetSpellScript() [2/2]
SpellScript * SpellScriptMgr::GetSpellScript (uint32 spellId) static
Definition at line 28 of file SpellScript.cpp.
References m_spellScriptMap.
Referenced by LoadScripts().
LoadScripts()
void SpellScriptMgr::LoadScripts () static
Definition at line 66 of file SpellScript.cpp.
References GetAuraScript(), Field::GetCppString(), GetSpellScript(), Field::GetUInt32(), LoadDeathKnightScripts(), LoadDruidScripts(), LoadHunterScripts(), LoadMageScripts(), LoadPaladinScripts(), LoadPriestScripts(), LoadRogueScripts(), LoadScalingScripts(), LoadShamanScripts(), LoadWarlockScripts(), LoadWarriorScripts(), SQLStorage::LookupEntry(), Database::Query(), SetAuraScript(), SetSpellScript(), sLog, sSpellTemplate, and WorldDatabase.
Referenced by World::SetInitialWorldSettings().
SetAuraScript() [1/2]
void SpellScriptMgr::SetAuraScript (std::string scriptName, AuraScript * script) static
Definition at line 49 of file SpellScript.cpp.
References m_auraScriptStringMap.
Referenced by LoadScripts(), and RegisterSpellScript().
SetAuraScript() [2/2]
void SpellScriptMgr::SetAuraScript (uint32 spellId, AuraScript * script) static private
Definition at line 133 of file SpellScript.cpp.
References m_auraScriptMap.
SetSpellScript() [1/2]
void SpellScriptMgr::SetSpellScript (std::string scriptName, SpellScript * script) static
Definition at line 44 of file SpellScript.cpp.
References m_spellScriptStringMap.
Referenced by LoadScripts(), and RegisterSpellScript().
SetSpellScript() [2/2]
void SpellScriptMgr::SetSpellScript (uint32 spellId, SpellScript * script) static private
Definition at line 128 of file SpellScript.cpp.
References m_spellScriptMap.
Field Documentation
m_auraScriptMap
std::map< uint32, AuraScript * > SpellScriptMgr::m_auraScriptMap {} static private
Definition at line 158 of file SpellScript.h.
Referenced by GetAuraScript(), and SetAuraScript().
m_auraScriptStringMap
std::map< std::string, std::unique_ptr< AuraScript > > SpellScriptMgr::m_auraScriptStringMap {} static private
Definition at line 160 of file SpellScript.h.
Referenced by GetAuraScript(), and SetAuraScript().
m_spellScriptMap
std::map< uint32, SpellScript * > SpellScriptMgr::m_spellScriptMap {} static private
Definition at line 157 of file SpellScript.h.
Referenced by GetSpellScript(), and SetSpellScript().
m_spellScriptStringMap
std::map< std::string, std::unique_ptr< SpellScript > > SpellScriptMgr::m_spellScriptStringMap {} static private
Definition at line 159 of file SpellScript.h.
Referenced by GetSpellScript(), and SetSpellScript().
The documentation for this class was generated from the following files:
SpellScript.h
SpellScript.cpp