CMaNGOS_WoTLK: BattleGroundAV Class Reference
BattleGroundAV Class Reference
#include <BattleGroundAV.h>
Public Member Functions
BattleGroundAV ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *player) override
Method that is called when adding a player to the battleground.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
Team GetPrematureWinner () override
Function that returns the premature winner.
void HandleCreatureCreate (Creature *) override
void HandleGameObjectCreate (GameObject *) override
bool HandleAreaTrigger (Player *source, uint32 trigger) override
void HandlePlayerClickedOnFlag (Player *source, GameObject *target_obj) override
void HandleKillPlayer (Player *player, Player *killer) override
Method that handles killing players.
void HandleKillUnit (Creature *creature, Player *killer) override
bool CheckAchievementCriteriaMeet (uint32 criteriaId, Player const *source, Unit const *target, uint32 miscvalue1) override
bool IsConditionFulfilled (Player const *source, uint32 conditionId, WorldObject const *conditionSource, uint32 conditionSourceType) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandlePlayerDroppedFlag (Player *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Private Member Functions
void UpdateScore (PvpTeamIndex teamIdx, int32 points)
void HandleQuestComplete (uint32 questid, Player *player)
bool CanPlayerDoMineQuest (uint32 gameobjectEntry, Team team)
void ProcessPlayerAssaultsPoint (Player *player, AVNodeIds node)
void ProcessPlayerDefendsPoint (Player *player, AVNodeIds node)
void ProcessPlayerDestroyedPoint (AVNodeIds node)
void InitializeNode (AVNodeIds node)
void AssaultNode (AVNodeIds node, PvpTeamIndex teamIdx)
void DestroyNode (AVNodeIds node)
void DefendNode (AVNodeIds node, PvpTeamIndex teamIdx)
void PopulateNode (AVNodeIds node)
will spawn and despawn creatures around a node more a wrapper around spawnevent cause graveyards are special
int32 GetNodeMessageId (AVNodeIds node) const
void ChangeMineOwner (AVMineIds mineId, PvpTeamIndex newOwnerTeamIdx)
uint8 GetWorldStateType (uint8 state, PvpTeamIndex teamIdx) const
void UpdateNodeWorldState (AVNodeIds node, uint32 newState)
void DoSendYellToTeam (PvpTeamIndex teamIdx, int32 textId, uint8 nodeId, bool useNode=true, int32 mineLangId=0)
Private Attributes
uint32 m_teamQuestStatus [PVP_TEAM_COUNT][9]
AVNodeInfo m_nodes [BG_AV_MAX_NODES]
PvpTeamIndex m_mineOwner [BG_AV_MAX_MINES]
uint32 m_mineTimer [BG_AV_MAX_MINES]
uint32 m_mineReclaimTimer [BG_AV_MAX_MINES]
uint32 m_mineYellTimer
uint8 m_homeTowersControlled [PVP_TEAM_COUNT]
uint8 m_enemyTowersDestroyed [PVP_TEAM_COUNT]
bool m_wasInformedNearLose [PVP_TEAM_COUNT]
bool m_spiritHealersSet
uint32 m_honorMapComplete
uint32 m_repTowerDestruction
uint32 m_repCaptain
uint32 m_repBoss
uint32 m_repOwnedGrave
uint32 m_repOwnedMine
uint32 m_repSurviveCaptain
uint32 m_repSurviveTower
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 620 of file BattleGroundAV.h.
Constructor & Destructor Documentation
BattleGroundAV()
BattleGroundAV::BattleGroundAV ()
Definition at line 30 of file BattleGroundAV.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_AV_HAS_BEGUN, LANG_BG_AV_START_HALF_MINUTE, LANG_BG_AV_START_ONE_MINUTE, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundAV::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 362 of file BattleGroundAV.cpp.
References BattleGround::AddPlayer(), avGraveyardData, avNodeDefaults, BG_AV_MAX_GRAVEYARDS, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, Object::GetObjectGuid(), AlteracNodeData::initialOwner, m_nodes, BattleGround::m_playerScores, m_spiritHealersSet, AlteracSummonData::o, AVNodeInfo::spiritHealerGuid, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_NEUTRAL, TEMPSPAWN_DEAD_DESPAWN, AlteracSummonData::x, AlteracSummonData::y, and AlteracSummonData::z.
AssaultNode()
void BattleGroundAV::AssaultNode (AVNodeIds node, PvpTeamIndex teamIdx) private
Definition at line 809 of file BattleGroundAV.cpp.
References BG_AV_CAPTIME, BG_AV_SNOWFALL_FIRSTCAP, m_nodes, MANGOS_ASSERT, AVNodeInfo::owner, POINT_ASSAULTED, AVNodeInfo::prevOwner, AVNodeInfo::prevState, AVNodeInfo::state, TEAM_INDEX_NEUTRAL, and AVNodeInfo::timer.
Referenced by ProcessPlayerAssaultsPoint().
CanPlayerDoMineQuest()
bool BattleGroundAV::CanPlayerDoMineQuest (uint32 gameobjectEntry, Team team) private
Definition at line 608 of file BattleGroundAV.cpp.
References BG_AV_COLDTOOTH_MINE_ID, BG_AV_GO_COLDTOOTH_SUPPLIES, BG_AV_GO_IRONDEEP_SUPPLIES, BG_AV_IRONDEEP_MINE_ID, GetTeamIndexByTeamId(), and m_mineOwner.
ChangeMineOwner()
void BattleGroundAV::ChangeMineOwner (AVMineIds mineId, PvpTeamIndex newOwnerTeamIdx) private
Definition at line 568 of file BattleGroundAV.cpp.
References avMineWorldStates, BG_AV_IRONDEEP_MINE_ID, BG_AV_MINE_BOSSES, BG_AV_MINE_EVENT, BG_AV_MINE_RECLAIM_TIMER, BG_AV_MINE_TICK_TIMER, BG_AV_NPC_PVP_MINE_CREDIT, BG_AV_SOUND_ALLIANCE_GOOD, BG_AV_SOUND_HORDE_GOOD, DEBUG_LOG, DoSendYellToTeam(), BattleGround::GetBgMap(), Player::GetTeam(), GetTeamIdByTeamIndex(), Map::GetVariableManager(), Player::KilledMonsterCredit(), LANG_BG_AV_MINE_NORTH, LANG_BG_AV_MINE_SOUTH, LANG_BG_AV_MINE_TAKEN, m_mineOwner, m_mineReclaimTimer, m_mineTimer, BattleGround::m_players, BattleGround::PlaySoundToAll(), WorldStateVariableManager::SetVariable(), sObjectMgr, BattleGround::SpawnEvent(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_NEUTRAL, WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
Referenced by HandleKillUnit(), and Update().
CheckAchievementCriteriaMeet()
bool BattleGroundAV::CheckAchievementCriteriaMeet (uint32 criteriaId, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 993 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_ACHIEV_CRIT_ALL_COUNTS_A1, BG_AV_ACHIEV_CRIT_ALL_COUNTS_A2, BG_AV_ACHIEV_CRIT_ALL_COUNTS_H1, BG_AV_ACHIEV_CRIT_ALL_COUNTS_H2, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF1, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF10, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF2, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF3, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF4, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF5, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF6, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF7, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF8, BG_AV_ACHIEV_CRIT_FROSTWOLF_PERF9, BG_AV_ACHIEV_CRIT_SICKLY_GAZELLE, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF1, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF10, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF2, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF3, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF4, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF5, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF6, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF7, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF8, BG_AV_ACHIEV_CRIT_STORMPIKE_PERF9, BG_AV_AREA_ID_FIELD_OF_STRIFE, BG_AV_COLDTOOTH_MINE_ID, BG_AV_IRONDEEP_MINE_ID, BG_AV_MAX_TOWERS_PER_TEAM, WorldObject::GetAreaId(), Player::GetTeam(), Object::GetTypeId(), HORDE, Unit::IsMounted(), m_enemyTowersDestroyed, m_homeTowersControlled, m_mineOwner, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and TYPEID_PLAYER.
DefendNode()
void BattleGroundAV::DefendNode (AVNodeIds node, PvpTeamIndex teamIdx) private
Definition at line 864 of file BattleGroundAV.cpp.
References m_nodes, MANGOS_ASSERT, AVNodeInfo::owner, POINT_CONTROLLED, AVNodeInfo::prevOwner, AVNodeInfo::prevState, AVNodeInfo::state, and AVNodeInfo::timer.
Referenced by ProcessPlayerDefendsPoint().
DestroyNode()
void BattleGroundAV::DestroyNode (AVNodeIds node) private
Definition at line 824 of file BattleGroundAV.cpp.
References m_nodes, MANGOS_ASSERT, AVNodeInfo::owner, POINT_ASSAULTED, POINT_CONTROLLED, AVNodeInfo::prevOwner, AVNodeInfo::prevState, AVNodeInfo::state, AVNodeInfo::timer, and AVNodeInfo::totalOwner.
Referenced by ProcessPlayerDestroyedPoint().
DoSendYellToTeam()
void BattleGroundAV::DoSendYellToTeam (PvpTeamIndex teamIdx, int32 textId, uint8 nodeId, bool useNode = true, int32 mineLangId = 0) private
Definition at line 960 of file BattleGroundAV.cpp.
References BG_AV_NPC_FROSTWOLF_HERALD, BG_AV_NPC_STORMPIKE_HERALD, GetNodeMessageId(), BattleGround::GetSingleCreatureFromStorage(), LANG_BG_ALLY, LANG_BG_HORDE, LANG_UNIVERSAL, BattleGround::SendYell2ToAll(), BattleGround::SendYellToAll(), and TEAM_INDEX_ALLIANCE.
Referenced by ChangeMineOwner(), HandleKillUnit(), ProcessPlayerAssaultsPoint(), ProcessPlayerDefendsPoint(), and ProcessPlayerDestroyedPoint().
EndBattleGround()
void BattleGroundAV::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 390 of file BattleGroundAV.cpp.
References ALLIANCE, avTeamCaptains, avTeamFactions, BG_AV_KILL_SURVIVING_CAPTAIN, BG_AV_KILL_SURVIVING_TOWER, BG_AV_MAX_NODES, BG_AV_NPC_HERALD, CHAT_MSG_MONSTER_YELL, DEBUG_LOG, BattleGround::EndBattleGround(), BattleGround::GetBonusHonorFromKill(), BattleGround::GetSingleCreatureFromStorage(), GetTeamIdByTeamIndex(), HORDE, Unit::IsAlive(), m_homeTowersControlled, m_honorMapComplete, m_mineOwner, m_nodes, m_repOwnedGrave, m_repOwnedMine, m_repSurviveCaptain, m_repSurviveTower, AVNodeInfo::owner, POINT_CONTROLLED, PVP_TEAM_COUNT, BattleGround::RewardHonorToTeam(), BattleGround::RewardReputationToTeam(), BattleGround::SendBcdToAll(), TEAM_INDEX_NEUTRAL, YELL_ALLIANCE_WINS, YELL_FROSTWOLF_DEAD, YELL_HORDE_WINS, and YELL_STORMPIKE_DEAD.
Referenced by HandleKillUnit(), and UpdateScore().
GetNodeMessageId()
int32 BattleGroundAV::GetNodeMessageId (AVNodeIds node) const private
Definition at line 785 of file BattleGroundAV.cpp.
References BG_AV_NODE_DUNBALDAR_NORTH, BG_AV_NODE_DUNBALDAR_SOUTH, BG_AV_NODE_FROSTWOLF_EAST, BG_AV_NODE_FROSTWOLF_WEST, BG_AV_NODE_GY_DUN_BALDAR, BG_AV_NODE_GY_FROSTWOLF, BG_AV_NODE_GY_FROSTWOLF_KEEP, BG_AV_NODE_GY_ICEBLOOD, BG_AV_NODE_GY_SNOWFALL, BG_AV_NODE_GY_STONEHEARTH, BG_AV_NODE_GY_STORMPIKE, BG_AV_NODE_ICEBLOOD_TOWER, BG_AV_NODE_ICEWING_BUNKER, BG_AV_NODE_STONEHEART_BUNKER, BG_AV_NODE_TOWER_POINT, LANG_BG_AV_NODE_GRAVE_FROST, LANG_BG_AV_NODE_GRAVE_FROST_HUT, LANG_BG_AV_NODE_GRAVE_ICE, LANG_BG_AV_NODE_GRAVE_SNOW, LANG_BG_AV_NODE_GRAVE_STONE, LANG_BG_AV_NODE_GRAVE_STORM_AID, LANG_BG_AV_NODE_GRAVE_STORMPIKE, LANG_BG_AV_NODE_TOWER_DUN_N, LANG_BG_AV_NODE_TOWER_DUN_S, LANG_BG_AV_NODE_TOWER_FROST_E, LANG_BG_AV_NODE_TOWER_FROST_W, LANG_BG_AV_NODE_TOWER_ICE, LANG_BG_AV_NODE_TOWER_ICEWING, LANG_BG_AV_NODE_TOWER_POINT, and LANG_BG_AV_NODE_TOWER_STONE.
Referenced by DoSendYellToTeam().
GetPrematureWinner()
Team BattleGroundAV::GetPrematureWinner () override virtual
Function that returns the premature winner.
Reimplemented from BattleGround.
Definition at line 979 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_STATE_SCORE_A, BG_AV_STATE_SCORE_H, BattleGround::GetBgMap(), BattleGround::GetPrematureWinner(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), and HORDE.
GetWorldStateType()
uint8 BattleGroundAV::GetWorldStateType (uint8 state, PvpTeamIndex teamIdx) const inline private
Definition at line 675 of file BattleGroundAV.h.
References BG_AV_MAX_STATES.
HandleAreaTrigger()
bool BattleGroundAV::HandleAreaTrigger (Player * source, uint32 trigger) override virtual
Reimplemented from BattleGround.
Definition at line 460 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_AT_ENTRANCE_ALLIANCE1, BG_AV_AT_ENTRANCE_ALLIANCE2, BG_AV_AT_ENTRANCE_HORDE, Player::GetSession(), Player::GetTeam(), HORDE, LANG_BATTLEGROUND_ONLY_ALLIANCE_USE, LANG_BATTLEGROUND_ONLY_HORDE_USE, Player::LeaveBattleground(), and WorldSession::SendNotification().
HandleCreatureCreate()
void BattleGroundAV::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from BattleGround.
Definition at line 118 of file BattleGroundAV.cpp.
References BG_AV_NPC_CAPTAIN_GALVANGAR, BG_AV_NPC_CAPTAIN_STONEHEARTH, BG_AV_NPC_EAST_WARMASTER, BG_AV_NPC_FROSTWOLF_HERALD, BG_AV_NPC_HERALD, BG_AV_NPC_ICEBLOOD_WARMASTER, BG_AV_NPC_ICEWING_MARSHAL, BG_AV_NPC_MORLOCH, BG_AV_NPC_NORTH_MARSHAL, BG_AV_NPC_SOUTH_MARSHAL, BG_AV_NPC_STONEHEARTH_MARSHAL, BG_AV_NPC_STORMPIKE_HERALD, BG_AV_NPC_TASKMASTER_SNIVVLE, BG_AV_NPC_TOWERPOINT_WARMASTER, BG_AV_NPC_WEST_WARMASTER, Object::GetEntry(), Object::GetObjectGuid(), and BattleGround::m_npcEntryGuidStore.
HandleGameObjectCreate()
void BattleGroundAV::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 142 of file BattleGroundAV.cpp.
References BG_AV_GO_COLDTOOTH_SUPPLIES, BG_AV_GO_FROSTWOLF_BANNER, BG_AV_GO_IRONDEEP_SUPPLIES, BG_AV_GO_STORMPIKE_BANNER, Object::GetEntry(), Object::GetObjectGuid(), and BattleGround::m_goEntryGuidStore.
HandleKillPlayer()
void BattleGroundAV::HandleKillPlayer (Player * player, Player * killer) override virtual
Method that handles killing players.
also handles generic logic for arena updates
Parameters
victim player
killer player
Reimplemented from BattleGround.
Definition at line 38 of file BattleGroundAV.cpp.
References BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), BattleGround::HandleKillPlayer(), STATUS_IN_PROGRESS, and UpdateScore().
HandleKillUnit()
void BattleGroundAV::HandleKillUnit (Creature * creature, Player * killer) override virtual
Reimplemented from BattleGround.
Definition at line 48 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_COLDTOOTH_MINE_ID, BG_AV_FACTION_ID_FROSTWOLF, BG_AV_FACTION_ID_STORMPIKE, BG_AV_IRONDEEP_MINE_ID, BG_AV_KILL_BOSS, BG_AV_KILL_CAPTAIN, BG_AV_NODE_CAPTAIN_DEAD_A, BG_AV_NODE_CAPTAIN_DEAD_H, BG_AV_NPC_AGGI_RUMBLESTOMP, BG_AV_NPC_CAPTAIN_GALVANGAR, BG_AV_NPC_CAPTAIN_STONEHEARTH, BG_AV_NPC_DREKTHAR, BG_AV_NPC_KEETAR, BG_AV_NPC_MASHA_SWIFTCUT, BG_AV_NPC_MORLOCH, BG_AV_NPC_TASKMASTER_SNIVVLE, BG_AV_NPC_UMI_THORSON, BG_AV_NPC_VANNDAR_STORMPIKE, BG_AV_RES_CAPTAIN, BG_AV_SPELL_COMPLETE_AV_QUEST, BattleGround::CastSpellOnTeam(), ChangeMineOwner(), DEBUG_LOG, DoSendYellToTeam(), EndBattleGround(), BattleGround::GetBonusHonorFromKill(), Object::GetEntry(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), HORDE, LANG_BG_AV_A_GENERAL_DEAD, LANG_BG_AV_H_GENERAL_DEAD, m_repBoss, m_repCaptain, BattleGround::RewardHonorToTeam(), BattleGround::RewardReputationToTeam(), BattleGround::SpawnEvent(), STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and UpdateScore().
HandlePlayerClickedOnFlag()
void BattleGroundAV::HandlePlayerClickedOnFlag (Player * source, GameObject * target_obj) override virtual
Reimplemented from BattleGround.
Definition at line 646 of file BattleGroundAV.cpp.
References BG_AV_MAX_NODES, BG_AV_MAX_STATES, DEBUG_LOG, Object::GetDbGuid(), Object::GetEntry(), BattleGround::GetStatus(), Player::GetTeam(), POINT_ASSAULTED, POINT_CONTROLLED, ProcessPlayerAssaultsPoint(), ProcessPlayerDefendsPoint(), sBattleGroundMgr, and STATUS_IN_PROGRESS.
HandleQuestComplete()
void BattleGroundAV::HandleQuestComplete (uint32 questid, Player * player) private
Definition at line 156 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_FACTION_ID_FROSTWOLF, BG_AV_FACTION_ID_STORMPIKE, BG_AV_NODE_GY_DUN_BALDAR, BG_AV_NODE_GY_FROSTWOLF_KEEP, BG_AV_QUEST_ARMOR_SCRAPS_A, BG_AV_QUEST_ARMOR_SCRAPS_A_REPEAT, BG_AV_QUEST_ARMOR_SCRAPS_H, BG_AV_QUEST_ARMOR_SCRAPS_H_REPEAT, BG_AV_QUEST_COLDTOOTH_SUPPLIES_A, BG_AV_QUEST_COLDTOOTH_SUPPLIES_H, BG_AV_QUEST_CRYSTAL_CLUSTER, BG_AV_QUEST_EMPTY_STABLES_A, BG_AV_QUEST_EMPTY_STABLES_H, BG_AV_QUEST_GALLON_OF_BLOOD, BG_AV_QUEST_GUSES_FLEET, BG_AV_QUEST_ICHMANS_FLEET, BG_AV_QUEST_IRONDEEP_SUPPLIES_A, BG_AV_QUEST_IRONDEEP_SUPPLIES_H, BG_AV_QUEST_IVUS_FOREST_LORD, BG_AV_QUEST_JEZTORS_FLEET, BG_AV_QUEST_LOKHOLAR_ICE_LORD, BG_AV_QUEST_MULVERICKS_FLEET, BG_AV_QUEST_RAM_HIDE, BG_AV_QUEST_RAM_RIDING, BG_AV_QUEST_SLIDORES_FLEET, BG_AV_QUEST_VIPORES_FLEET, DEBUG_LOG, BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), m_nodes, m_teamQuestStatus, POINT_CONTROLLED, PopulateNode(), BattleGround::RewardReputationToTeam(), and STATUS_IN_PROGRESS.
InitializeNode()
void BattleGroundAV::InitializeNode (AVNodeIds node) private
Definition at line 836 of file BattleGroundAV.cpp.
References avNodeDefaults, BG_AV_MAX_GRAVETYPES, BG_AV_MAX_NODES, BG_AV_MAX_STATES, BG_AV_ZONE_MAIN, AlteracNodeData::defaultWorldState, BattleGround::GetBgMap(), Map::GetGraveyardManager(), GetTeamIdByTeamIndex(), Map::GetVariableManager(), AlteracNodeData::graveyardId, AVNodeInfo::graveyardId, AlteracNodeData::initialOwner, BattleGround::m_activeEvents, m_nodes, AVNodeInfo::owner, POINT_CONTROLLED, AVNodeInfo::prevOwner, AVNodeInfo::prevState, GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), AVNodeInfo::state, TEAM_INDEX_NEUTRAL, TEAM_INVALID, AVNodeInfo::timer, AVNodeInfo::totalOwner, WORLD_STATE_ADD, and AVNodeInfo::worldState.
Referenced by Reset().
IsConditionFulfilled()
bool BattleGroundAV::IsConditionFulfilled (Player const * source, uint32 conditionId, WorldObject const * conditionSource, uint32 conditionSourceType) override virtual
Reimplemented from BattleGround.
Definition at line 1032 of file BattleGroundAV.cpp.
PopulateNode()
void BattleGroundAV::PopulateNode (AVNodeIds node) private
will spawn and despawn creatures around a node more a wrapper around spawnevent cause graveyards are special
Definition at line 620 of file BattleGroundAV.cpp.
References BG_AV_MAX_GRAVETYPES, BG_AV_MAX_NODES, BG_AV_MAX_STATES, AVNodeInfo::graveyardId, m_nodes, m_teamQuestStatus, AVNodeInfo::owner, POINT_CONTROLLED, BattleGround::SpawnEvent(), and TEAM_INDEX_NEUTRAL.
Referenced by HandleQuestComplete(), ProcessPlayerAssaultsPoint(), ProcessPlayerDefendsPoint(), and ProcessPlayerDestroyedPoint().
ProcessPlayerAssaultsPoint()
void BattleGroundAV::ProcessPlayerAssaultsPoint (Player * player, AVNodeIds node) private
Definition at line 725 of file BattleGroundAV.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, AI_EVENT_CUSTOM_A, AssaultNode(), avNodeDefaults, avNodeWorldStates, BG_AV_NPC_PVP_GRAVEYARD_CREDIT, BG_AV_NPC_PVP_TOWER_CREDIT, BG_AV_SOUND_ALLIANCE_ASSAULTS, BG_AV_SOUND_HORDE_ASSAULTS, BG_AV_ZONE_MAIN, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, DEBUG_LOG, DoSendYellToTeam(), BattleGround::GetBgMap(), GetClosestCreatureWithEntry(), Map::GetGraveyardManager(), Player::GetTeam(), GetTeamIndexByTeamId(), AVNodeInfo::graveyardId, LANG_BG_AV_GRAVE_ASSAULTED, LANG_BG_AV_TOWER_ASSAULTED, m_nodes, BattleGround::PlaySoundToAll(), PopulateNode(), Player::RewardPlayerAndGroupAtEventCredit(), SCORE_GRAVEYARDS_ASSAULTED, SCORE_TOWERS_ASSAULTED, GraveyardManager::SetGraveYardLinkTeam(), TEAM_INDEX_ALLIANCE, TEAM_INVALID, Player::UpdateAchievementCriteria(), UpdateNodeWorldState(), UpdatePlayerScore(), AlteracNodeStates::worldStateAllyGrey, and AlteracNodeStates::worldStateHordeGrey.
Referenced by HandlePlayerClickedOnFlag(), and ProcessPlayerDefendsPoint().
ProcessPlayerDefendsPoint()
void BattleGroundAV::ProcessPlayerDefendsPoint (Player * player, AVNodeIds node) private
Definition at line 672 of file BattleGroundAV.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, avNodeWorldStates, BG_AV_NODE_GY_SNOWFALL, BG_AV_SOUND_ALLIANCE_GOOD, BG_AV_SOUND_BOTH_TOWER_DEFEND, BG_AV_SOUND_HORDE_GOOD, DEBUG_LOG, DefendNode(), DoSendYellToTeam(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), AVNodeInfo::graveyardId, LANG_BG_AV_GRAVE_DEFENDED, LANG_BG_AV_TOWER_DEFENDED, m_nodes, BattleGround::PlaySoundToAll(), POINT_ASSAULTED, PopulateNode(), ProcessPlayerAssaultsPoint(), SCORE_GRAVEYARDS_DEFENDED, SCORE_TOWERS_DEFENDED, sLog, STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, TEAM_INDEX_NEUTRAL, Player::UpdateAchievementCriteria(), UpdateNodeWorldState(), UpdatePlayerScore(), AlteracNodeStates::worldStateAlly, and AlteracNodeStates::worldStateHorde.
Referenced by HandlePlayerClickedOnFlag().
ProcessPlayerDestroyedPoint()
void BattleGroundAV::ProcessPlayerDestroyedPoint (AVNodeIds node) private
Definition at line 514 of file BattleGroundAV.cpp.
References ALLIANCE, avGraveyardData, avNodeDefaults, BG_AV_FACTION_ID_STORMPIKE, BG_AV_KILL_TOWER, BG_AV_MARSHAL_A_SOUTH, BG_AV_NODE_DUNBALDAR_SOUTH, BG_AV_NPC_FROSTWOLF_HERALD, BG_AV_NPC_STORMPIKE_HERALD, BG_AV_RES_TOWER, BG_AV_ZONE_MAIN, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, DEBUG_LOG, DestroyNode(), DoSendYellToTeam(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), Map::GetGraveyardManager(), BattleGround::GetOtherTeamIndex(), BattleGround::GetSingleCreatureFromStorage(), GetTeamIdByTeamIndex(), AVNodeInfo::graveyardId, LANG_BG_AV_GRAVE_TAKEN, LANG_BG_AV_TOWER_TAKEN, m_enemyTowersDestroyed, m_homeTowersControlled, m_nodes, m_repTowerDestruction, AlteracSummonData::o, PopulateNode(), BattleGround::RewardHonorToTeam(), BattleGround::RewardReputationToTeam(), GraveyardManager::SetGraveYardLinkTeam(), sLog, BattleGround::SpawnEvent(), AVNodeInfo::spiritHealerGuid, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEMPSPAWN_DEAD_DESPAWN, UpdateNodeWorldState(), UpdateScore(), AlteracSummonData::x, AlteracSummonData::y, and AlteracSummonData::z.
Referenced by Update().
Reset()
void BattleGroundAV::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 877 of file BattleGroundAV.cpp.
References ALLIANCE, avMineWorldStates, avNodeWorldStates, BG_AV_BOSS_A, BG_AV_BOSS_H, BG_AV_CAPTAIN_A, BG_AV_CAPTAIN_H, BG_AV_GRAVE_MAIN_ALLIANCE, BG_AV_GRAVE_MAIN_HORDE, BG_AV_HERALD, BG_AV_KILL_MAP_COMPLETE, BG_AV_KILL_MAP_COMPLETE_HOLIDAY, BG_AV_MARSHAL_A_SOUTH, BG_AV_MAX_MINES, BG_AV_MAX_NODES, BG_AV_MAX_TOWERS_PER_TEAM, BG_AV_MINE_BOSSES, BG_AV_MINE_EVENT, BG_AV_MINE_TICK_TIMER, BG_AV_MINE_YELL, BG_AV_NODE_DUNBALDAR_SOUTH, BG_AV_REP_BOSS, BG_AV_REP_BOSS_HOLIDAY, BG_AV_REP_CAPTAIN, BG_AV_REP_CAPTAIN_HOLIDAY, BG_AV_REP_OWNED_GRAVE, BG_AV_REP_OWNED_GRAVE_HOLIDAY, BG_AV_REP_OWNED_MINE, BG_AV_REP_OWNED_MINE_HOLIDAY, BG_AV_REP_SURVIVING_CAPTAIN, BG_AV_REP_SURVIVING_CAPTAIN_HOLIDAY, BG_AV_REP_SURVIVING_TOWER, BG_AV_REP_SURVIVING_TOWER_HOLIDAY, BG_AV_REP_TOWER, BG_AV_REP_TOWER_HOLIDAY, BG_AV_SCORE_INITIAL_POINTS, BG_AV_STATE_SCORE_A, BG_AV_STATE_SCORE_H, BG_AV_STATE_SCORE_SHOW_A, BG_AV_STATE_SCORE_SHOW_H, BG_AV_TEAMS_COUNT, BG_AV_ZONE_MAIN, BattleGround::GetBgMap(), Map::GetGraveyardManager(), BattleGround::GetTypeId(), Map::GetVariableManager(), HORDE, InitializeNode(), BattleGroundMgr::IsBgWeekend(), BattleGround::m_activeEvents, m_enemyTowersDestroyed, m_homeTowersControlled, m_honorMapComplete, m_mineOwner, m_mineTimer, m_mineYellTimer, m_repBoss, m_repCaptain, m_repOwnedGrave, m_repOwnedMine, m_repSurviveCaptain, m_repSurviveTower, m_repTowerDestruction, m_spiritHealersSet, m_teamQuestStatus, m_wasInformedNearLose, PVP_TEAM_COUNT, BattleGround::Reset(), GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), TEAM_INDEX_NEUTRAL, and WORLD_STATE_ADD.
StartingEventOpenDoors()
void BattleGroundAV::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 351 of file BattleGroundAV.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, BG_AV_STATE_SCORE_SHOW_A, BG_AV_STATE_SCORE_SHOW_H, BG_AV_TIMED_ACHIEV_ALTERAC_BLITZ, BG_EVENT_DOOR, BattleGround::GetBgMap(), Map::GetVariableManager(), BattleGround::OpenDoorEvent(), WorldStateVariableManager::SetVariable(), BattleGround::StartTimedAchievement(), and WORLD_STATE_ADD.
Update()
void BattleGroundAV::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 297 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_MAX_MINES, BG_AV_MAX_NODES, BG_AV_MINE_TICK_TIMER, BG_AV_NPC_MORLOCH, BG_AV_NPC_TASKMASTER_SNIVVLE, ChangeMineOwner(), CHAT_MSG_MONSTER_YELL, BattleGround::GetSingleCreatureFromStorage(), BattleGround::GetStatus(), HORDE, m_mineOwner, m_mineReclaimTimer, m_mineTimer, m_mineYellTimer, m_nodes, POINT_ASSAULTED, ProcessPlayerDestroyedPoint(), BattleGround::SendBcdToTeam(), STATUS_IN_PROGRESS, TEAM_INDEX_NEUTRAL, AVNodeInfo::timer, BattleGround::Update(), UpdateScore(), YELL_MORLOCH_MINE, and YELL_SNIVVLE_MINE.
UpdateNodeWorldState()
void BattleGroundAV::UpdateNodeWorldState (AVNodeIds node, uint32 newState) private
Definition at line 777 of file BattleGroundAV.cpp.
References BattleGround::GetBgMap(), Map::GetVariableManager(), m_nodes, WorldStateVariableManager::SetVariable(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, and AVNodeInfo::worldState.
Referenced by ProcessPlayerAssaultsPoint(), ProcessPlayerDefendsPoint(), and ProcessPlayerDestroyedPoint().
UpdatePlayerScore()
void BattleGroundAV::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 484 of file BattleGroundAV.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_GRAVEYARDS_ASSAULTED, SCORE_GRAVEYARDS_DEFENDED, SCORE_SECONDARY_OBJECTIVES, SCORE_TOWERS_ASSAULTED, SCORE_TOWERS_DEFENDED, and BattleGround::UpdatePlayerScore().
Referenced by ProcessPlayerAssaultsPoint(), and ProcessPlayerDefendsPoint().
UpdateScore()
void BattleGroundAV::UpdateScore (PvpTeamIndex teamIdx, int32 points) private
Definition at line 270 of file BattleGroundAV.cpp.
References ALLIANCE, BG_AV_SCORE_NEAR_LOSE, BG_AV_SOUND_NEAR_LOSE, BG_AV_STATE_SCORE_A, BG_AV_STATE_SCORE_H, CHAT_MSG_BG_SYSTEM_NEUTRAL, EndBattleGround(), BattleGround::GetBgMap(), Map::GetVariableManager(), HORDE, LANG_BG_AV_A_NEAR_LOSE, LANG_BG_AV_H_NEAR_LOSE, m_wasInformedNearLose, BattleGround::PlaySoundToAll(), BattleGround::SendMessageToAll(), WorldStateVariableManager::SetVariable(), TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by HandleKillPlayer(), HandleKillUnit(), ProcessPlayerDestroyedPoint(), and Update().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 622 of file BattleGroundAV.h.
Field Documentation
m_enemyTowersDestroyed
uint8 BattleGroundAV::m_enemyTowersDestroyed[PVP_TEAM_COUNT] private
Definition at line 692 of file BattleGroundAV.h.
Referenced by CheckAchievementCriteriaMeet(), ProcessPlayerDestroyedPoint(), and Reset().
m_homeTowersControlled
uint8 BattleGroundAV::m_homeTowersControlled[PVP_TEAM_COUNT] private
Definition at line 691 of file BattleGroundAV.h.
Referenced by CheckAchievementCriteriaMeet(), EndBattleGround(), ProcessPlayerDestroyedPoint(), and Reset().
m_honorMapComplete
uint32 BattleGroundAV::m_honorMapComplete private
Definition at line 697 of file BattleGroundAV.h.
Referenced by EndBattleGround(), and Reset().
m_mineOwner
PvpTeamIndex BattleGroundAV::m_mineOwner[BG_AV_MAX_MINES] private
Definition at line 686 of file BattleGroundAV.h.
Referenced by CanPlayerDoMineQuest(), ChangeMineOwner(), CheckAchievementCriteriaMeet(), EndBattleGround(), Reset(), and Update().
m_mineReclaimTimer
uint32 BattleGroundAV::m_mineReclaimTimer[BG_AV_MAX_MINES] private
Definition at line 688 of file BattleGroundAV.h.
Referenced by ChangeMineOwner(), and Update().
m_mineTimer
uint32 BattleGroundAV::m_mineTimer[BG_AV_MAX_MINES] private
Definition at line 687 of file BattleGroundAV.h.
Referenced by ChangeMineOwner(), Reset(), and Update().
m_mineYellTimer
uint32 BattleGroundAV::m_mineYellTimer private
Definition at line 689 of file BattleGroundAV.h.
Referenced by Reset(), and Update().
m_nodes
AVNodeInfo BattleGroundAV::m_nodes[BG_AV_MAX_NODES] private
Definition at line 683 of file BattleGroundAV.h.
Referenced by AddPlayer(), AssaultNode(), DefendNode(), DestroyNode(), EndBattleGround(), HandleQuestComplete(), InitializeNode(), PopulateNode(), ProcessPlayerAssaultsPoint(), ProcessPlayerDefendsPoint(), ProcessPlayerDestroyedPoint(), Update(), and UpdateNodeWorldState().
m_repBoss
uint32 BattleGroundAV::m_repBoss private
Definition at line 700 of file BattleGroundAV.h.
Referenced by HandleKillUnit(), and Reset().
m_repCaptain
uint32 BattleGroundAV::m_repCaptain private
Definition at line 699 of file BattleGroundAV.h.
Referenced by HandleKillUnit(), and Reset().
m_repOwnedGrave
uint32 BattleGroundAV::m_repOwnedGrave private
Definition at line 701 of file BattleGroundAV.h.
Referenced by EndBattleGround(), and Reset().
m_repOwnedMine
uint32 BattleGroundAV::m_repOwnedMine private
Definition at line 702 of file BattleGroundAV.h.
Referenced by EndBattleGround(), and Reset().
m_repSurviveCaptain
uint32 BattleGroundAV::m_repSurviveCaptain private
Definition at line 703 of file BattleGroundAV.h.
Referenced by EndBattleGround(), and Reset().
m_repSurviveTower
uint32 BattleGroundAV::m_repSurviveTower private
Definition at line 704 of file BattleGroundAV.h.
Referenced by EndBattleGround(), and Reset().
m_repTowerDestruction
uint32 BattleGroundAV::m_repTowerDestruction private
Definition at line 698 of file BattleGroundAV.h.
Referenced by ProcessPlayerDestroyedPoint(), and Reset().
m_spiritHealersSet
bool BattleGroundAV::m_spiritHealersSet private
Definition at line 695 of file BattleGroundAV.h.
Referenced by AddPlayer(), and Reset().
m_teamQuestStatus
uint32 BattleGroundAV::m_teamQuestStatus[PVP_TEAM_COUNT][9] private
Definition at line 681 of file BattleGroundAV.h.
Referenced by HandleQuestComplete(), PopulateNode(), and Reset().
m_wasInformedNearLose
bool BattleGroundAV::m_wasInformedNearLose[PVP_TEAM_COUNT] private
Definition at line 694 of file BattleGroundAV.h.
Referenced by Reset(), and UpdateScore().
The documentation for this class was generated from the following files:
BattleGroundAV.h
BattleGroundAV.cpp