CMaNGOS_WoTLK: MaNGOS::NearUsedPosDo Class Reference
MaNGOS::NearUsedPosDo Class Reference
Public Member Functions
NearUsedPosDo (WorldObject const &obj, WorldObject const *searcher, float absAngle, ObjectPosSelector &selector)
void operator() (Corpse *) const
void operator() (DynamicObject *) const
void operator() (Creature *c) const
template<class T >
void operator() (T *u) const
void add (WorldObject *u, float x, float y) const
Private Attributes
WorldObject const & i_object
WorldObject const * i_searcher
float i_absAngle
ObjectPosSelector & i_selector
Detailed Description
Definition at line 2370 of file Object.cpp.
Constructor & Destructor Documentation
NearUsedPosDo()
MaNGOS::NearUsedPosDo::NearUsedPosDo (WorldObject const & obj, WorldObject const * searcher, float absAngle, ObjectPosSelector & selector) inline
Definition at line 2373 of file Object.cpp.
Member Function Documentation
add()
void MaNGOS::NearUsedPosDo::add (WorldObject * u, float x, float y) const inline
Definition at line 2410 of file Object.cpp.
References ObjectPosSelector::AddUsedArea(), WorldObject::GetAngle(), WorldObject::GetObjectBoundingRadius(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), i_absAngle, i_object, i_selector, M_PI_F, ObjectPosSelector::m_searcherDist, ObjectPosSelector::m_searchPosFor, and OCCUPY_POS_DEPTH_FACTOR.
Referenced by operator()().
operator()() [1/4]
void MaNGOS::NearUsedPosDo::operator() (Corpse *) const inline
Definition at line 2376 of file Object.cpp.
operator()() [2/4]
void MaNGOS::NearUsedPosDo::operator() (Creature * c) const inline
Definition at line 2379 of file Object.cpp.
References add(), MotionMaster::GetDestination(), Unit::GetMotionMaster(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), i_object, i_searcher, and Unit::IsStopped().
operator()() [3/4]
void MaNGOS::NearUsedPosDo::operator() (DynamicObject *) const inline
Definition at line 2377 of file Object.cpp.
operator()() [4/4]
template<class T > void MaNGOS::NearUsedPosDo::operator() (T * u) const inline
Definition at line 2397 of file Object.cpp.
References add(), i_object, and i_searcher.
Field Documentation
i_absAngle
float MaNGOS::NearUsedPosDo::i_absAngle private
Definition at line 2440 of file Object.cpp.
Referenced by add().
i_object
WorldObject const& MaNGOS::NearUsedPosDo::i_object private
Definition at line 2438 of file Object.cpp.
Referenced by add(), and operator()().
i_searcher
WorldObject const* MaNGOS::NearUsedPosDo::i_searcher private
Definition at line 2439 of file Object.cpp.
Referenced by operator()().
i_selector
ObjectPosSelector& MaNGOS::NearUsedPosDo::i_selector private
Definition at line 2441 of file Object.cpp.
Referenced by add().
The documentation for this class was generated from the following file:
Object.cpp