CMaNGOS_WoTLK: MaNGOS::AnyAoETargetUnitInObjectRangeCheck Class Reference
MaNGOS::AnyAoETargetUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyAoETargetUnitInObjectRangeCheck (WorldObject const *obj, SpellEntry const *spellInfo, float range, bool ignorePhase=false)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
SpellEntry const * i_spellInfo
float i_range
bool i_targetForPlayer
bool i_ignorePhase
Detailed Description
Definition at line 1300 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyAoETargetUnitInObjectRangeCheck()
MaNGOS::AnyAoETargetUnitInObjectRangeCheck::AnyAoETargetUnitInObjectRangeCheck (WorldObject const * obj, SpellEntry const * spellInfo, float range, bool ignorePhase = false) inline
Definition at line 1303 of file GridNotifiers.h.
References i_obj, i_targetForPlayer, and WorldObject::IsControlledByPlayer().
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AnyAoETargetUnitInObjectRangeCheck::GetFocusObject () const inline
Definition at line 1308 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnyAoETargetUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 1309 of file GridNotifiers.h.
References WorldObject::CanAttackSpell(), Object::GetTypeId(), i_ignorePhase, i_obj, i_range, i_spellInfo, WorldObject::IsWithinDistInMap(), and TYPEID_UNIT.
Field Documentation
i_ignorePhase
bool MaNGOS::AnyAoETargetUnitInObjectRangeCheck::i_ignorePhase private
Definition at line 1323 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* MaNGOS::AnyAoETargetUnitInObjectRangeCheck::i_obj private
Definition at line 1319 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck(), GetFocusObject(), and operator()().
i_range
float MaNGOS::AnyAoETargetUnitInObjectRangeCheck::i_range private
Definition at line 1321 of file GridNotifiers.h.
Referenced by operator()().
i_spellInfo
SpellEntry const* MaNGOS::AnyAoETargetUnitInObjectRangeCheck::i_spellInfo private
Definition at line 1320 of file GridNotifiers.h.
Referenced by operator()().
i_targetForPlayer
bool MaNGOS::AnyAoETargetUnitInObjectRangeCheck::i_targetForPlayer private
Definition at line 1322 of file GridNotifiers.h.
Referenced by AnyAoETargetUnitInObjectRangeCheck().
The documentation for this class was generated from the following file:
GridNotifiers.h