CMaNGOS_WoTLK: SessionAnticheatInterface Class Reference
SessionAnticheatInterface Class Reference abstract
#include <Anticheat.hpp>
Public Member Functions
virtual ~SessionAnticheatInterface ()=default
virtual void Update (uint32 diff)=0
virtual bool IsSilenced () const =0
virtual void SendCharEnum (WorldPacket &&packet)=0
virtual void NewPlayer ()=0
virtual void LeaveWorld ()=0
virtual void Disconnect ()=0
virtual bool ReadAddonInfo (WorldPacket *, WorldPacket &)=0
virtual void SendPlayerInfo (ChatHandler *) const =0
virtual void RecordCheat (uint32 actionMask, const char *detector, const char *format,...)=0
virtual bool Movement (MovementInfo &mi, const WorldPacket &)=0
virtual void TimeSkipped (const ObjectGuid &mover, uint32 ms)=0
virtual bool ExtrapolateMovement (MovementInfo const &mi, uint32 diffMs, Position &pos)=0
virtual bool SpeedChangeAck (MovementInfo &mi, const WorldPacket &packet, float newSpeed)=0
virtual bool IsInKnockBack () const =0
virtual void KnockBack (float speedxy, float speedz, float cos, float sin)=0
virtual void OnExplore (const AreaTableEntry *p)=0
virtual void Teleport (const Position &pos)=0
virtual void OrderSent (uint16 opcode, uint32 counter)=0
virtual void OrderAck (uint16 opcode, uint32 counter)=0
virtual void WardenPacket (WorldPacket &packet)=0
virtual void AutoReply (const std::string &msg)=0
virtual void Whisper (const std::string &msg, const ObjectGuid &to)=0
virtual void Say (const std::string &msg)=0
virtual void Yell (const std::string &msg)=0
virtual void Channel (const std::string &msg)=0
virtual void Mail (const std::string &subject, const std::string &body, const ObjectGuid &to)=0
virtual void ChannelInvite (const std::string &channelName, const ObjectGuid &to)=0
virtual void PartyInvite (const ObjectGuid &to)=0
Detailed Description
Definition at line 62 of file Anticheat.hpp.
Constructor & Destructor Documentation
~SessionAnticheatInterface()
virtual SessionAnticheatInterface::~SessionAnticheatInterface () virtual default
Member Function Documentation
AutoReply()
virtual void SessionAnticheatInterface::AutoReply (const std::string & msg) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Channel()
virtual void SessionAnticheatInterface::Channel (const std::string & msg) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
ChannelInvite()
virtual void SessionAnticheatInterface::ChannelInvite (const std::string & channelName, const ObjectGuid & to) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by Channel::Invite().
Disconnect()
virtual void SessionAnticheatInterface::Disconnect () pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
ExtrapolateMovement()
virtual bool SessionAnticheatInterface::ExtrapolateMovement (MovementInfo const & mi, uint32 diffMs, Position & pos) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
IsInKnockBack()
virtual bool SessionAnticheatInterface::IsInKnockBack () const pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
IsSilenced()
virtual bool SessionAnticheatInterface::IsSilenced () const pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by Channel::Invite(), Player::Say(), Channel::Say(), Player::TextEmote(), Player::Whisper(), and Player::Yell().
KnockBack()
virtual void SessionAnticheatInterface::KnockBack (float speedxy, float speedz, float cos, float sin) pure virtual
Implemented in NullSessionAnticheat, and NamreebAnticheat::SessionAnticheat.
LeaveWorld()
virtual void SessionAnticheatInterface::LeaveWorld () pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by Player::RemoveFromWorld().
Mail()
virtual void SessionAnticheatInterface::Mail (const std::string & subject, const std::string & body, const ObjectGuid & to) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Movement()
virtual bool SessionAnticheatInterface::Movement (MovementInfo & mi, const WorldPacket &) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
NewPlayer()
virtual void SessionAnticheatInterface::NewPlayer () pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
OnExplore()
virtual void SessionAnticheatInterface::OnExplore (const AreaTableEntry * p) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by Player::CheckAreaExploreAndOutdoor().
OrderAck()
virtual void SessionAnticheatInterface::OrderAck (uint16 opcode, uint32 counter) pure virtual
Implemented in NullSessionAnticheat, and NamreebAnticheat::SessionAnticheat.
OrderSent()
virtual void SessionAnticheatInterface::OrderSent (uint16 opcode, uint32 counter) pure virtual
Implemented in NullSessionAnticheat, and NamreebAnticheat::SessionAnticheat.
Referenced by Unit::SendMoveRoot(), Unit::SendTeleportPacket(), and Unit::SetSpeedRate().
PartyInvite()
virtual void SessionAnticheatInterface::PartyInvite (const ObjectGuid & to) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by WorldSession::HandleGroupInviteOpcode().
ReadAddonInfo()
virtual bool SessionAnticheatInterface::ReadAddonInfo (WorldPacket * , WorldPacket &) pure virtual
Implemented in NullSessionAnticheat, and NamreebAnticheat::SessionAnticheat.
Referenced by WorldSocket::HandleAuthSession().
RecordCheat()
virtual void SessionAnticheatInterface::RecordCheat (uint32 actionMask, const char * detector, const char * format, ...) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Say()
virtual void SessionAnticheatInterface::Say (const std::string & msg) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
SendCharEnum()
virtual void SessionAnticheatInterface::SendCharEnum (WorldPacket && packet) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
SendPlayerInfo()
virtual void SessionAnticheatInterface::SendPlayerInfo (ChatHandler *) const pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Referenced by ChatHandler::HandlePInfoCommand().
SpeedChangeAck()
virtual bool SessionAnticheatInterface::SpeedChangeAck (MovementInfo & mi, const WorldPacket & packet, float newSpeed) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Teleport()
virtual void SessionAnticheatInterface::Teleport (const Position & pos) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
TimeSkipped()
virtual void SessionAnticheatInterface::TimeSkipped (const ObjectGuid & mover, uint32 ms) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Update()
virtual void SessionAnticheatInterface::Update (uint32 diff) pure virtual
Implemented in NullSessionAnticheat, and NamreebAnticheat::SessionAnticheat.
WardenPacket()
virtual void SessionAnticheatInterface::WardenPacket (WorldPacket & packet) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Whisper()
virtual void SessionAnticheatInterface::Whisper (const std::string & msg, const ObjectGuid & to) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
Yell()
virtual void SessionAnticheatInterface::Yell (const std::string & msg) pure virtual
Implemented in NamreebAnticheat::SessionAnticheat, and NullSessionAnticheat.
The documentation for this class was generated from the following file:
Anticheat.hpp