CMaNGOS_WoTLK: PanicMovementGenerator Class Reference
PanicMovementGenerator Class Reference
#include <RandomMovementGenerator.h>
Public Member Functions
PanicMovementGenerator (Unit const &source, uint32 time)
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
bool Update (Unit &owner, const uint32 &diff) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from FleeingMovementGenerator
FleeingMovementGenerator (Unit const &source)
virtual int32 _setLocation (Unit &owner) override
Public Member Functions inherited from AbstractRandomMovementGenerator
AbstractRandomMovementGenerator (uint32 stateActive, uint32 stateMotion, uint32 delayMin, uint32 delayMax, uint32 movesMax=1)
void Reset (Unit &owner) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Private Attributes
ShortTimeTracker m_fleeingTimer
Additional Inherited Members
Protected Attributes inherited from AbstractRandomMovementGenerator
float i_x
float i_y
float i_z
float i_radius
float i_verticalZ
float i_pathLength
bool i_walk
std::unique_ptr< PathFinder > m_pathFinder
ShortTimeTracker i_nextMoveTimer
uint32 i_nextMoveCount
uint32 i_nextMoveCountMax
uint32 i_nextMoveDelayMin
uint32 i_nextMoveDelayMax
uint32 i_stateActive
uint32 i_stateMotion
Detailed Description
Definition at line 108 of file RandomMovementGenerator.h.
Constructor & Destructor Documentation
PanicMovementGenerator()
PanicMovementGenerator::PanicMovementGenerator (Unit const & source, uint32 time) inline
Definition at line 111 of file RandomMovementGenerator.h.
Member Function Documentation
Finalize()
void PanicMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 239 of file RandomMovementGenerator.cpp.
References Unit::AI(), Unit::clearUnitState(), AbstractRandomMovementGenerator::Finalize(), Object::RemoveFlag(), UnitAI::TimedFleeingEnded(), UNIT_FIELD_FLAGS, UNIT_FLAG_FLEEING, and UNIT_STAT_PANIC.
GetMovementGeneratorType()
MovementGeneratorType PanicMovementGenerator::GetMovementGeneratorType () const inline override virtual
Reimplemented from FleeingMovementGenerator.
Definition at line 118 of file RandomMovementGenerator.h.
References TIMED_FLEEING_MOTION_TYPE.
Initialize()
void PanicMovementGenerator::Initialize (Unit & owner) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 232 of file RandomMovementGenerator.cpp.
References Unit::addUnitState(), AbstractRandomMovementGenerator::Initialize(), and UNIT_STAT_PANIC.
Interrupt()
void PanicMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 252 of file RandomMovementGenerator.cpp.
References Unit::AI(), AbstractRandomMovementGenerator::Interrupt(), and UnitAI::TimedFleeingEnded().
Update()
bool PanicMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 260 of file RandomMovementGenerator.cpp.
References m_fleeingTimer, ShortTimeTracker::Passed(), ShortTimeTracker::Update(), and AbstractRandomMovementGenerator::Update().
Field Documentation
m_fleeingTimer
ShortTimeTracker PanicMovementGenerator::m_fleeingTimer private
Definition at line 121 of file RandomMovementGenerator.h.
Referenced by Update().
The documentation for this class was generated from the following files:
RandomMovementGenerator.h
RandomMovementGenerator.cpp