CMaNGOS_WoTLK: SQLMultiStorage Class Reference
SQLMultiStorage Class Reference
#include <SQLStorage.h>
Data Structures
class SQLMSIteratorBounds
class SQLMultiSIterator
Public Member Functions
SQLMultiStorage (const char *fmt, const char *_entry_field, const char *sqlname)
SQLMultiStorage (const char *src_fmt, const char *dst_fmt, const char *_entry_field, const char *sqlname)
~SQLMultiStorage ()
template<typename T >
SQLMSIteratorBounds< T > getBounds (uint32 key) const
void Load ()
void EraseEntry (uint32 id)
Public Member Functions inherited from SQLStorageBase
char const * GetTableName () const
char const * EntryFieldName () const
FieldFormat GetDstFormat (uint32 idx) const
const char * GetDstFormat () const
FieldFormat GetSrcFormat (uint32 idx) const
const char * GetSrcFormat () const
uint32 GetMaxEntry () const
uint32 GetRecordCount () const
template<typename T >
SQLSIterator< T > getDataBegin () const
template<typename T >
SQLSIterator< T > getDataEnd () const
Protected Member Functions
void prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override
void JustCreatedRecord (uint32 recordId, char *record) override
void Free () override
Protected Member Functions inherited from SQLStorageBase
SQLStorageBase ()
virtual ~SQLStorageBase ()
void Initialize (const char *tableName, const char *entry_field, const char *src_format, const char *dst_format)
uint32 GetDstFieldCount () const
uint32 GetSrcFieldCount () const
uint32 GetRecordSize () const
Private Types
typedef std::multimap< uint32, char * > RecordMultiMap
Private Attributes
RecordMultiMap m_indexMultiMap
Friends
template<class DerivedLoader , class StorageClass >
class SQLStorageLoaderBase
template<typename T >
class SQLMultiSIterator
template<typename T >
class SQLMSIteratorBounds
Detailed Description
Definition at line 175 of file SQLStorage.h.
Member Typedef Documentation
RecordMultiMap
typedef std::multimap<uint32 , char* > SQLMultiStorage::RecordMultiMap private
Definition at line 182 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLMultiStorage() [1/2]
SQLMultiStorage::SQLMultiStorage (const char * fmt, const char * _entry_field, const char * sqlname)
Definition at line 232 of file SQLStorage.cpp.
References SQLStorageBase::Initialize().
SQLMultiStorage() [2/2]
SQLMultiStorage::SQLMultiStorage (const char * src_fmt, const char * dst_fmt, const char * _entry_field, const char * sqlname)
Definition at line 237 of file SQLStorage.cpp.
References SQLStorageBase::Initialize().
~SQLMultiStorage()
SQLMultiStorage::~SQLMultiStorage () inline
Definition at line 188 of file SQLStorage.h.
References Free().
Member Function Documentation
EraseEntry()
void SQLMultiStorage::EraseEntry (uint32 id)
Definition at line 227 of file SQLStorage.cpp.
References m_indexMultiMap.
Referenced by SpellMgr::LoadSpellScriptTarget(), and ObjectMgr::LoadVehicleAccessory().
Free()
void SQLMultiStorage::Free () override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 213 of file SQLStorage.cpp.
References SQLStorageBase::Free(), and m_indexMultiMap.
Referenced by prepareToLoad(), and ~SQLMultiStorage().
getBounds()
template<typename T > SQLMSIteratorBounds<T> SQLMultiStorage::getBounds (uint32 key) const inline
Definition at line 228 of file SQLStorage.h.
References m_indexMultiMap.
Referenced by Spell::CheckScriptTargeting(), VehicleInfo::Initialize(), SpellTargetMgr::Initialize(), ObjectMgr::LoadItemRequiredTarget(), SpellMgr::LoadSpellScriptTarget(), Spell::SetTargetMap(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
JustCreatedRecord()
void SQLMultiStorage::JustCreatedRecord (uint32 recordId, char * record) inline override protected virtual
Implements SQLStorageBase.
Definition at line 236 of file SQLStorage.h.
References m_indexMultiMap.
Load()
void SQLMultiStorage::Load ()
Definition at line 207 of file SQLStorage.cpp.
References SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load().
Referenced by SpellMgr::LoadSpellScriptTarget(), and ObjectMgr::LoadVehicleAccessory().
prepareToLoad()
void SQLMultiStorage::prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 219 of file SQLStorage.cpp.
References Free(), and SQLStorageBase::prepareToLoad().
Friends And Related Function Documentation
SQLMSIteratorBounds
template<typename T > friend class SQLMSIteratorBounds friend
Definition at line 179 of file SQLStorage.h.
SQLMultiSIterator
template<typename T > friend class SQLMultiSIterator friend
Definition at line 178 of file SQLStorage.h.
SQLStorageLoaderBase
template<class DerivedLoader , class StorageClass > friend class SQLStorageLoaderBase friend
Definition at line 177 of file SQLStorage.h.
Field Documentation
m_indexMultiMap
RecordMultiMap SQLMultiStorage::m_indexMultiMap private
Definition at line 244 of file SQLStorage.h.
Referenced by EraseEntry(), Free(), getBounds(), and JustCreatedRecord().
The documentation for this class was generated from the following files:
SQLStorage.h
SQLStorage.cpp