CMaNGOS_WoTLK: instance_zulfarrak Class Reference
instance_zulfarrak Class Reference
#include <zulfarrak.h>
Public Member Functions
instance_zulfarrak (Map *pMap)
~instance_zulfarrak ()
void Initialize () override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature)
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void GetShallowGravesGuidList (GuidList &lList) const
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidList m_lShallowGravesGuidList
GuidList m_lPyramidTrollsGuidList
uint32 m_uiPyramidEventTimer
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Detailed Description
Definition at line 47 of file zulfarrak.h.
Constructor & Destructor Documentation
instance_zulfarrak()
instance_zulfarrak::instance_zulfarrak (Map * pMap)
Definition at line 27 of file instance_zulfarrak.cpp.
References Initialize().
~instance_zulfarrak()
instance_zulfarrak::~instance_zulfarrak () inline
Definition at line 51 of file zulfarrak.h.
Member Function Documentation
GetData()
uint32 instance_zulfarrak::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 140 of file instance_zulfarrak.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by AreaTrigger_at_zulfarrak(), OnObjectCreate(), and SetData().
GetShallowGravesGuidList()
void instance_zulfarrak::GetShallowGravesGuidList (GuidList & lList) const inline
Definition at line 65 of file zulfarrak.h.
References m_lShallowGravesGuidList.
Referenced by boss_zumrahAI::SelectNearbyShallowGrave().
Initialize()
void instance_zulfarrak::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 33 of file instance_zulfarrak.cpp.
References m_auiEncounter.
Referenced by instance_zulfarrak().
Load()
void instance_zulfarrak::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 116 of file instance_zulfarrak.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_zulfarrak::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 38 of file instance_zulfarrak.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lPyramidTrollsGuidList, ScriptedInstance::m_npcEntryGuidStore, NPC_ANTUSUL, NPC_SANDFURY_ACOLYTE, NPC_SANDFURY_CRETIN, NPC_SANDFURY_DRUDGE, NPC_SANDFURY_SLAVE, NPC_SANDFURY_ZEALOT, and NPC_SERGEANT_BLY.
OnCreatureDeath()
void instance_zulfarrak::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 178 of file instance_zulfarrak.cpp.
References DONE, Object::GetEntry(), NPC_ANTUSUL, NPC_CHIEF_SANDSCALP, NPC_GAHZRILLA, NPC_NEKRUM, NPC_SEZZZIZ, NPC_THEKA, NPC_VELRATHA, NPC_ZUMRAH, SetData(), TYPE_ANTUSUL, TYPE_CHIEF_SANDSCALP, TYPE_GAHZRILLA, TYPE_NEKRUM, TYPE_SEZZZIZ, TYPE_THEKA, TYPE_VELRATHA, and TYPE_ZUMRAH.
OnCreatureEnterCombat()
void instance_zulfarrak::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 148 of file instance_zulfarrak.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_ANTUSUL, NPC_CHIEF_SANDSCALP, NPC_GAHZRILLA, NPC_NEKRUM, NPC_SEZZZIZ, NPC_THEKA, NPC_VELRATHA, NPC_ZUMRAH, SetData(), TYPE_ANTUSUL, TYPE_CHIEF_SANDSCALP, TYPE_GAHZRILLA, TYPE_NEKRUM, TYPE_SEZZZIZ, TYPE_THEKA, TYPE_VELRATHA, and TYPE_ZUMRAH.
OnCreatureEvade()
void instance_zulfarrak::OnCreatureEvade (Creature * pCreature) virtual
Reimplemented from InstanceData.
Definition at line 163 of file instance_zulfarrak.cpp.
References FAIL, Object::GetEntry(), NPC_ANTUSUL, NPC_CHIEF_SANDSCALP, NPC_GAHZRILLA, NPC_NEKRUM, NPC_SEZZZIZ, NPC_THEKA, NPC_VELRATHA, NPC_ZUMRAH, SetData(), TYPE_ANTUSUL, TYPE_CHIEF_SANDSCALP, TYPE_GAHZRILLA, TYPE_NEKRUM, TYPE_SEZZZIZ, TYPE_THEKA, TYPE_VELRATHA, and TYPE_ZUMRAH.
OnObjectCreate()
void instance_zulfarrak::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 56 of file instance_zulfarrak.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), GO_END_DOOR, GO_SHALLOW_GRAVE, GO_STATE_ACTIVE, m_lShallowGravesGuidList, GameObject::SetGoState(), and TYPE_PYRAMID_EVENT.
Save()
const char* instance_zulfarrak::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 67 of file zulfarrak.h.
References m_strInstData.
SetData()
void instance_zulfarrak::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 67 of file instance_zulfarrak.cpp.
References DONE, GetData(), IN_PROGRESS, m_auiEncounter, m_strInstData, m_uiPyramidEventTimer, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_ANTUSUL, TYPE_CHIEF_SANDSCALP, TYPE_GAHZRILLA, TYPE_NEKRUM, TYPE_PYRAMID_EVENT, TYPE_SEZZZIZ, TYPE_THEKA, TYPE_VELRATHA, and TYPE_ZUMRAH.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), and OnCreatureEvade().
Update()
void instance_zulfarrak::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 193 of file instance_zulfarrak.cpp.
References Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_lPyramidTrollsGuidList, m_uiPyramidEventTimer, NPC_SERGEANT_BLY, and urand().
Field Documentation
m_auiEncounter
uint32 instance_zulfarrak::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 73 of file zulfarrak.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_lPyramidTrollsGuidList
GuidList instance_zulfarrak::m_lPyramidTrollsGuidList protected
Definition at line 77 of file zulfarrak.h.
Referenced by OnCreatureCreate(), and Update().
m_lShallowGravesGuidList
GuidList instance_zulfarrak::m_lShallowGravesGuidList protected
Definition at line 76 of file zulfarrak.h.
Referenced by GetShallowGravesGuidList(), and OnObjectCreate().
m_strInstData
std::string instance_zulfarrak::m_strInstData protected
Definition at line 74 of file zulfarrak.h.
Referenced by Save(), and SetData().
m_uiPyramidEventTimer
uint32 instance_zulfarrak::m_uiPyramidEventTimer protected
Definition at line 79 of file zulfarrak.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
zulfarrak.h
instance_zulfarrak.cpp