CMaNGOS_WoTLK: BgQueueInviteEvent Class Reference
BgQueueInviteEvent Class Reference
#include <BattleGroundMgr.h>
Public Member Functions
BgQueueInviteEvent (ObjectGuid playerGuid, uint32 bgInstanceGuid, BattleGroundTypeId bgTypeId, ArenaType arenaType, uint32 removeTime)
virtual ~BgQueueInviteEvent ()
virtual bool Execute (uint64 e_time, uint32 p_time) override
Function that executes battleground queue invite event.
virtual void Abort (uint64 e_time) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
Private Attributes
ObjectGuid m_playerGuid
uint32 m_bgInstanceGuid
BattleGroundTypeId m_bgTypeId
ArenaType m_arenaType
uint32 m_removeTime
Additional Inherited Members
Data Fields inherited from BasicEvent
bool to_Abort
uint64 m_addTime
uint64 m_execTime
Detailed Description
Definition at line 146 of file BattleGroundMgr.h.
Constructor & Destructor Documentation
BgQueueInviteEvent()
BgQueueInviteEvent::BgQueueInviteEvent (ObjectGuid playerGuid, uint32 bgInstanceGuid, BattleGroundTypeId bgTypeId, ArenaType arenaType, uint32 removeTime) inline
Definition at line 149 of file BattleGroundMgr.h.
~BgQueueInviteEvent()
virtual BgQueueInviteEvent::~BgQueueInviteEvent () inline virtual
Definition at line 153 of file BattleGroundMgr.h.
Member Function Documentation
Abort()
void BgQueueInviteEvent::Abort (uint64 e_time) override virtual
Reimplemented from BasicEvent.
Definition at line 1204 of file BattleGroundMgr.cpp.
Execute()
bool BgQueueInviteEvent::Execute (uint64 e_time, uint32 p_time) override virtual
Function that executes battleground queue invite event.
Reimplemented from BasicEvent.
Definition at line 1172 of file BattleGroundMgr.cpp.
References BattleGroundMgr::BgQueueTypeId(), BattleGround::GetArenaType(), Player::GetBattleGroundQueueIndex(), Player::GetSession(), BattleGround::GetTypeId(), INVITATION_REMIND_TIME, INVITE_ACCEPT_WAIT_TIME, BattleGroundQueue::IsPlayerInvited(), PLAYER_MAX_BATTLEGROUND_QUEUES, sBattleGroundMgr, WorldSession::SendPacket(), sObjectMgr, STATUS_WAIT_JOIN, sWorld, and TEAM_NONE.
Field Documentation
m_arenaType
ArenaType BgQueueInviteEvent::m_arenaType private
Definition at line 162 of file BattleGroundMgr.h.
m_bgInstanceGuid
uint32 BgQueueInviteEvent::m_bgInstanceGuid private
Definition at line 160 of file BattleGroundMgr.h.
m_bgTypeId
BattleGroundTypeId BgQueueInviteEvent::m_bgTypeId private
Definition at line 161 of file BattleGroundMgr.h.
m_playerGuid
ObjectGuid BgQueueInviteEvent::m_playerGuid private
Definition at line 159 of file BattleGroundMgr.h.
m_removeTime
uint32 BgQueueInviteEvent::m_removeTime private
Definition at line 163 of file BattleGroundMgr.h.
The documentation for this class was generated from the following files:
BattleGroundMgr.h
BattleGroundMgr.cpp