CMaNGOS_WoTLK: MovementInfo Class Reference
MovementInfo Class Reference
#include <Object.h>
Data Structures
struct JumpInfo
Public Member Functions
MovementInfo ()
void Read (ByteBuffer &data)
void Write (ByteBuffer &data) const
void AddMovementFlag (MovementFlags f)
void RemoveMovementFlag (MovementFlags f)
bool HasMovementFlag (MovementFlags f) const
MovementFlags GetMovementFlags () const
void SetMovementFlags (MovementFlags f)
MovementFlags2 GetMovementFlags2 () const
void AddMovementFlags2 (MovementFlags2 f)
UnitMoveType GetSpeedType () const
float GetOrientationInMotion (float o) const
Position const & GetPos () const
void SetTransportPos (Position const &pos)
void SetTransportData (ObjectGuid guid, float x, float y, float z, float o, uint32 time, int8 seat)
void UpdateTransportData (Position pos)
void ClearTransportData ()
ObjectGuid const & GetTransportGuid () const
Position const & GetTransportPos () const
int8 GetTransportSeat () const
uint32 GetTransportTime () const
uint32 GetFallTime () const
void ChangeOrientation (float o)
void ChangePosition (float x, float y, float z, float o)
JumpInfo const & GetJumpInfo () const
Static Public Member Functions
static UnitMoveType GetSpeedType (MovementFlags f)
static float GetOrientationInMotion (MovementFlags flags, float orientation)
Data Fields
uint32 moveFlags
uint16 moveFlags2
uint32 ctime
uint32 stime
Position pos
ObjectGuid t_guid
Position t_pos
uint32 t_time
int8 t_seat
uint32 t_time2
float s_pitch
uint32 fallTime
JumpInfo jump
float u_unk1
Detailed Description
Definition at line 832 of file Object.h.
Constructor & Destructor Documentation
MovementInfo()
MovementInfo::MovementInfo () inline
Definition at line 835 of file Object.h.
Member Function Documentation
AddMovementFlag()
void MovementInfo::AddMovementFlag (MovementFlags f) inline
Definition at line 843 of file Object.h.
References moveFlags.
Referenced by GenericTransport::AddPassenger(), VehicleInfo::Board(), Object::BuildMovementUpdate(), PlayerbotAI::HandleBotOutgoingPacket(), Creature::InitEntry(), Movement::MoveSplineInit::Launch(), Unit::SendMoveRoot(), Unit::SetCanFly(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetSwim(), Creature::SetWalk(), Unit::SetWaterWalk(), Player::TeleportTo(), and PlayerbotAI::UpdateAI().
AddMovementFlags2()
void MovementInfo::AddMovementFlags2 (MovementFlags2 f) inline
Definition at line 849 of file Object.h.
References moveFlags2.
Referenced by VehicleInfo::Initialize().
ChangeOrientation()
void MovementInfo::ChangeOrientation (float o) inline
Definition at line 898 of file Object.h.
References Position::o, and pos.
Referenced by WorldObject::SetOrientation().
ChangePosition()
void MovementInfo::ChangePosition (float x, float y, float z, float o) inline
Definition at line 899 of file Object.h.
References Position::o, pos, Position::x, Position::y, and Position::z.
Referenced by WorldObject::Relocate(), and Unit::SendTeleportPacket().
ClearTransportData()
void MovementInfo::ClearTransportData () inline
Definition at line 883 of file Object.h.
References Position::o, t_guid, t_pos, t_seat, t_time, Position::x, Position::y, and Position::z.
Referenced by WorldSession::HandleMoverRelocation(), Player::LoadFromDB(), Player::TeleportTo(), and VehicleInfo::UnBoard().
GetFallTime()
uint32 MovementInfo::GetFallTime () const inline
Definition at line 897 of file Object.h.
References fallTime.
Referenced by Player::HandleFall(), and Player::UpdateFallInformationIfNeed().
GetJumpInfo()
JumpInfo const& MovementInfo::GetJumpInfo () const inline
Definition at line 909 of file Object.h.
References jump.
GetMovementFlags()
MovementFlags MovementInfo::GetMovementFlags () const inline
Definition at line 846 of file Object.h.
References moveFlags.
Referenced by WaypointMovementGenerator< Creature >::BuildIntPath(), Object::BuildMovementUpdate(), NamreebAnticheat::Movement::CheckTeleport(), ChatHandler::HandleDebugMoveflags(), Movement::MoveSplineInit::Launch(), and WorldSession::ProcessMovementInfo().
GetMovementFlags2()
MovementFlags2 MovementInfo::GetMovementFlags2 () const inline
Definition at line 848 of file Object.h.
References moveFlags2.
GetOrientationInMotion() [1/2]
float MovementInfo::GetOrientationInMotion (float o) const inline
Definition at line 866 of file Object.h.
References GetOrientationInMotion(), and moveFlags.
Referenced by GetOrientationInMotion().
GetOrientationInMotion() [2/2]
float MovementInfo::GetOrientationInMotion (MovementFlags flags, float orientation) static
Definition at line 238 of file Unit.cpp.
References M_PI_F, MOVEFLAG_BACKWARD, MOVEFLAG_FORWARD, MOVEFLAG_STRAFE_LEFT, MOVEFLAG_STRAFE_RIGHT, and MapManager::NormalizeOrientation().
GetPos()
Position const& MovementInfo::GetPos () const inline
Definition at line 870 of file Object.h.
References pos.
Referenced by Player::HandleFall(), WorldSession::HandleMoverRelocation(), NamreebAnticheat::Movement::IsTeleportAllowed(), Player::UpdateFallInformationIfNeed(), and WorldSession::VerifyMovementInfo().
GetSpeedType() [1/2]
UnitMoveType MovementInfo::GetSpeedType () const inline
Definition at line 852 of file Object.h.
References GetSpeedType(), and moveFlags.
Referenced by WaypointMovementGenerator< Creature >::BuildIntPath(), Unit::GetSpeedInMotion(), Unit::GetSpeedRateInMotion(), GetSpeedType(), and Movement::MoveSplineInit::Launch().
GetSpeedType() [2/2]
static UnitMoveType MovementInfo::GetSpeedType (MovementFlags f) inline static
Definition at line 853 of file Object.h.
References MOVE_FLIGHT, MOVE_FLIGHT_BACK, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_WALK, MOVEFLAG_BACKWARD, MOVEFLAG_FLYING, MOVEFLAG_SWIMMING, and MOVEFLAG_WALK_MODE.
GetTransportGuid()
ObjectGuid const& MovementInfo::GetTransportGuid () const inline
Definition at line 893 of file Object.h.
References t_guid.
Referenced by Unit::FindRootVehicle(), WorldSession::HandleMoverRelocation(), and NamreebAnticheat::SessionAnticheat::Movement().
GetTransportPos()
Position const& MovementInfo::GetTransportPos () const inline
Definition at line 894 of file Object.h.
References t_pos.
Referenced by WorldObject::GetPosition(), WorldObject::GetTransOffsetO(), WorldObject::GetTransOffsetX(), WorldObject::GetTransOffsetY(), WorldObject::GetTransOffsetZ(), WorldSession::HandlePlayerLogin(), Player::LoadFromDB(), Player::SaveToDB(), Player::TeleportTo(), Transport::TeleportTransport(), and WorldSession::VerifyMovementInfo().
GetTransportSeat()
int8 MovementInfo::GetTransportSeat () const inline
Definition at line 895 of file Object.h.
References t_seat.
Referenced by WorldObject::GetTransSeat().
GetTransportTime()
uint32 MovementInfo::GetTransportTime () const inline
Definition at line 896 of file Object.h.
References t_time.
Referenced by WorldObject::GetTransTime().
HasMovementFlag()
bool MovementInfo::HasMovementFlag (MovementFlags f) const inline
Definition at line 845 of file Object.h.
References moveFlags.
Referenced by Creature::CanFly(), Player::CanFly(), WorldSession::HandleMoveRootAck(), FollowMovementGenerator::HandleTargetedMovement(), Player::HasMovementFlag(), Unit::IsFalling(), Unit::IsFlying(), Creature::IsFlying(), Unit::IsLevitating(), Unit::IsMoving(), Unit::IsMovingForward(), Unit::IsMovingIgnoreFlying(), Player::isMovingOrTurning(), Unit::IsRooted(), Creature::IsSwimming(), Player::IsSwimming(), Unit::IsWalking(), NamreebAnticheat::SessionAnticheat::Movement(), Movement::MoveSplineInit::MoveSplineInit(), Read(), Unit::SetStunnedByLogout(), Spell::SetTargetMap(), Creature::SetWalk(), Spell::update(), Creature::UpdateEntry(), Player::UpdateFallInformationIfNeed(), WorldSession::VerifyMovementInfo(), and Write().
Read()
void MovementInfo::Read (ByteBuffer & data)
Definition at line 140 of file Unit.cpp.
References MovementInfo::JumpInfo::cosAngle, ctime, fallTime, HasMovementFlag(), jump, MOVEFLAG2_ALLOW_PITCHING, MOVEFLAG2_INTERP_MOVEMENT, MOVEFLAG_FALLING, MOVEFLAG_FLYING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_SPLINE_ELEVATION, MOVEFLAG_SWIMMING, moveFlags, moveFlags2, Position::o, pos, ObjectGuid::ReadAsPacked(), s_pitch, MovementInfo::JumpInfo::sinAngle, MovementInfo::JumpInfo::start, MovementInfo::JumpInfo::startClientTime, stime, sWorld, t_guid, t_pos, t_seat, t_time, t_time2, u_unk1, Position::x, MovementInfo::JumpInfo::xyspeed, Position::y, Position::z, and MovementInfo::JumpInfo::zspeed.
Referenced by operator>>().
RemoveMovementFlag()
void MovementInfo::RemoveMovementFlag (MovementFlags f) inline
Definition at line 844 of file Object.h.
References moveFlags.
Referenced by Object::BuildMovementUpdate(), NamreebAnticheat::Movement::CheckTeleport(), Unit::DisableSpline(), PlayerbotAI::HandleBotOutgoingPacket(), Intervene::OnCast(), Unit::SendMoveRoot(), Unit::SetCanFly(), Unit::SetFeatherFall(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetSwim(), Creature::SetWalk(), Unit::SetWaterWalk(), Movement::MoveSplineInit::Stop(), VehicleInfo::UnBoard(), and PlayerbotAI::UpdateAI().
SetMovementFlags()
void MovementInfo::SetMovementFlags (MovementFlags f) inline
Definition at line 847 of file Object.h.
References moveFlags.
Referenced by Movement::MoveSplineInit::Launch(), and Player::TeleportTo().
SetTransportData()
void MovementInfo::SetTransportData (ObjectGuid guid, float x, float y, float z, float o, uint32 time, int8 seat) inline
Definition at line 872 of file Object.h.
References Position::o, t_guid, t_pos, t_seat, t_time, Position::x, Position::y, and Position::z.
Referenced by GenericTransport::AddPetToTransport(), VehicleInfo::Board(), Player::LoadFromDB(), GenericTransport::RemovePassenger(), and Unit::SendTeleportPacket().
SetTransportPos()
void MovementInfo::SetTransportPos (Position const & pos) inline
Definition at line 871 of file Object.h.
References pos, and t_pos.
Referenced by Creature::LoadFromDB(), and GameObject::LoadFromDB().
UpdateTransportData()
void MovementInfo::UpdateTransportData (Position pos) inline
Definition at line 882 of file Object.h.
References pos, and t_pos.
Referenced by Unit::UpdateSplinePosition().
Write()
void MovementInfo::Write (ByteBuffer & data) const
Definition at line 193 of file Unit.cpp.
References MovementInfo::JumpInfo::cosAngle, fallTime, HasMovementFlag(), ObjectGuid::IsVehicle(), jump, MOVEFLAG2_ALLOW_PITCHING, MOVEFLAG2_INTERP_MOVEMENT, MOVEFLAG_FALLING, MOVEFLAG_FLYING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_SPLINE_ELEVATION, MOVEFLAG_SWIMMING, moveFlags, moveFlags2, Position::o, pos, s_pitch, MovementInfo::JumpInfo::sinAngle, stime, t_guid, t_pos, t_seat, t_time, t_time2, u_unk1, ObjectGuid::WriteAsPacked(), Position::x, MovementInfo::JumpInfo::xyspeed, Position::y, Position::z, and MovementInfo::JumpInfo::zspeed.
Referenced by WorldSession::HandleMovementOpcodes(), operator<<(), and Unit::SendTeleportPacket().
Field Documentation
ctime
uint32 MovementInfo::ctime
Definition at line 914 of file Object.h.
Referenced by NamreebAnticheat::Movement::ExtrapolateMovement(), NamreebAnticheat::Movement::GetMaxAllowedDist(), NamreebAnticheat::Movement::HandleAnticheatTests(), WorldSession::HandleMoveTimeSkippedOpcode(), NamreebAnticheat::Movement::KnockBack(), Read(), and WorldSession::SynchronizeMovement().
fallTime
uint32 MovementInfo::fallTime
Definition at line 926 of file Object.h.
Referenced by NamreebAnticheat::Movement::CheckFallReset(), GetFallTime(), NamreebAnticheat::Movement::HandleAnticheatTests(), Read(), and Write().
jump
JumpInfo MovementInfo::jump
Definition at line 928 of file Object.h.
Referenced by NamreebAnticheat::Movement::CheckFallReset(), NamreebAnticheat::Movement::ExtrapolateMovement(), GetJumpInfo(), NamreebAnticheat::Movement::GetMaxAllowedDist(), NamreebAnticheat::Movement::HandleAnticheatTests(), WorldSession::HandleMoveKnockBackAck(), NamreebAnticheat::Movement::KnockBack(), Read(), and Write().
moveFlags
uint32 MovementInfo::moveFlags
Definition at line 912 of file Object.h.
Referenced by AddMovementFlag(), NamreebAnticheat::Movement::ExtrapolateMovement(), NamreebAnticheat::Movement::GetMaxAllowedDist(), GetMovementFlags(), GetOrientationInMotion(), GetSpeedType(), Unit::GetXYFlagBasedSpeed(), NamreebAnticheat::Movement::HandleAnticheatTests(), ChatHandler::HandleNpcInfoCommand(), HasMovementFlag(), NamreebAnticheat::Movement::KnockBack(), Read(), RemoveMovementFlag(), SetMovementFlags(), and Write().
moveFlags2
uint16 MovementInfo::moveFlags2
Definition at line 913 of file Object.h.
Referenced by AddMovementFlags2(), GetMovementFlags2(), Read(), and Write().
pos
Position MovementInfo::pos
Definition at line 916 of file Object.h.
Referenced by GenericTransport::AddPetToTransport(), ChangeOrientation(), ChangePosition(), NamreebAnticheat::Movement::CheckTeleport(), NamreebAnticheat::Movement::ExtrapolateMovement(), GetPos(), NamreebAnticheat::Movement::HandleAnticheatTests(), NamreebAnticheat::Movement::IsTeleportAllowed(), Read(), GenericTransport::RemovePassenger(), SetTransportPos(), UpdateTransportData(), and Write().
s_pitch
float MovementInfo::s_pitch
Definition at line 924 of file Object.h.
Referenced by NamreebAnticheat::Movement::ExtrapolateMovement(), Read(), and Write().
stime
uint32 MovementInfo::stime
Definition at line 915 of file Object.h.
Referenced by NamreebAnticheat::Movement::HandleAnticheatTests(), WorldSession::HandleMoveTimeSkippedOpcode(), NamreebAnticheat::Movement::KnockBack(), Read(), Unit::SendMoveRoot(), WorldSession::SynchronizeMovement(), and Write().
t_guid
ObjectGuid MovementInfo::t_guid
Definition at line 918 of file Object.h.
Referenced by GenericTransport::AddPassenger(), ClearTransportData(), WorldObject::GetPosition(), GetTransportGuid(), Read(), SetTransportData(), Player::TeleportTo(), GenericTransport::UpdatePassengerPosition(), and Write().
t_pos
Position MovementInfo::t_pos
Definition at line 919 of file Object.h.
Referenced by GenericTransport::AddPassenger(), GenericTransport::AddPetToTransport(), ClearTransportData(), WorldObject::GetPosition(), GetTransportPos(), WorldSession::HandleMoveWorldportAckOpcode(), Read(), SetTransportData(), SetTransportPos(), WorldObject::SummonCreature(), UpdateTransportData(), and Write().
t_seat
int8 MovementInfo::t_seat
Definition at line 921 of file Object.h.
Referenced by ClearTransportData(), GetTransportSeat(), Read(), SetTransportData(), and Write().
t_time
uint32 MovementInfo::t_time
Definition at line 920 of file Object.h.
Referenced by GenericTransport::AddPassenger(), ClearTransportData(), GetTransportTime(), Read(), SetTransportData(), Player::TeleportTo(), GenericTransport::UpdatePassengerPosition(), and Write().
t_time2
uint32 MovementInfo::t_time2
Definition at line 922 of file Object.h.
Referenced by Read(), and Write().
u_unk1
float MovementInfo::u_unk1
Definition at line 930 of file Object.h.
Referenced by Read(), and Write().
The documentation for this class was generated from the following files:
Object.h
Unit.cpp