CMaNGOS_WoTLK: MaNGOS::NearestGameObjectFishingHoleCheck Class Reference
MaNGOS::NearestGameObjectFishingHoleCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
NearestGameObjectFishingHoleCheck (WorldObject const &obj, float range)
WorldObject const & GetFocusObject () const
bool operator() (GameObject *go)
float GetLastRange () const
Private Member Functions
NearestGameObjectFishingHoleCheck (NearestGameObjectFishingHoleCheck const &)
Private Attributes
WorldObject const & i_obj
float i_range
Detailed Description
Definition at line 721 of file GridNotifiers.h.
Constructor & Destructor Documentation
NearestGameObjectFishingHoleCheck() [1/2]
MaNGOS::NearestGameObjectFishingHoleCheck::NearestGameObjectFishingHoleCheck (WorldObject const & obj, float range) inline
Definition at line 724 of file GridNotifiers.h.
NearestGameObjectFishingHoleCheck() [2/2]
MaNGOS::NearestGameObjectFishingHoleCheck::NearestGameObjectFishingHoleCheck (NearestGameObjectFishingHoleCheck const &) private
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::NearestGameObjectFishingHoleCheck::GetFocusObject () const inline
Definition at line 725 of file GridNotifiers.h.
References i_obj.
GetLastRange()
float MaNGOS::NearestGameObjectFishingHoleCheck::GetLastRange () const inline
Definition at line 735 of file GridNotifiers.h.
References i_range.
operator()()
bool MaNGOS::NearestGameObjectFishingHoleCheck::operator() (GameObject * go) inline
Definition at line 726 of file GridNotifiers.h.
References DIST_CALC_COMBAT_REACH, GameObjectInfo::fishinghole, GAMEOBJECT_TYPE_FISHINGHOLE, WorldObject::GetDistance(), GameObject::GetGOInfo(), i_obj, i_range, GameObject::IsSpawned(), WorldObject::IsWithinDistInMap(), and GameObjectInfo::type.
Field Documentation
i_obj
WorldObject const& MaNGOS::NearestGameObjectFishingHoleCheck::i_obj private
Definition at line 737 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::NearestGameObjectFishingHoleCheck::i_range private
Definition at line 738 of file GridNotifiers.h.
Referenced by GetLastRange(), and operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h