CMaNGOS_WoTLK: instance_sunken_temple Class Reference
instance_sunken_temple Class Reference
#include <sunken_temple.h>
Public Member Functions
instance_sunken_temple (Map *pMap)
~instance_sunken_temple ()
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature)
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void Update (const uint32 diff) override
bool ProcessStatueEvent (uint32 uiEventId)
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoSpawnAtalarionIfCan ()
void DoUpdateFlamesFlags (bool bRestore)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint8 m_uiProtectorsRemaining
uint8 m_uiStatueCounter
uint8 m_uiFlameCounter
uint32 m_uiAvatarSummonTimer
uint32 m_uiSupressorTimer
uint32 m_suppressionTimer
bool m_bIsFirstHakkarWave
bool m_bCanSummonBloodkeeper
GuidList m_luiFlameGUIDs
GuidList m_luiBigLightGUIDs
GuidVector m_evilCircleGuidList
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 113 of file sunken_temple.h.
Constructor & Destructor Documentation
instance_sunken_temple()
instance_sunken_temple::instance_sunken_temple (Map * pMap)
Definition at line 27 of file sunken_temple.cpp.
References Initialize().
~instance_sunken_temple()
instance_sunken_temple::~instance_sunken_temple () inline
Definition at line 117 of file sunken_temple.h.
Member Function Documentation
DoSpawnAtalarionIfCan()
void instance_sunken_temple::DoSpawnAtalarionIfCan () protected
Definition at line 307 of file sunken_temple.cpp.
References aSunkenTempleLocation, ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_IDOL_OF_HAKKAR, m_luiBigLightGUIDs, MINUTE, NPC_ATALARION, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by SetData().
DoUpdateFlamesFlags()
void instance_sunken_temple::DoUpdateFlamesFlags (bool bRestore) protected
Definition at line 354 of file sunken_temple.cpp.
References ScriptedInstance::DoToggleGameObjectFlags(), GO_FLAG_NO_INTERACT, and m_luiFlameGUIDs.
Referenced by SetData().
GetData()
uint32 instance_sunken_temple::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 383 of file sunken_temple.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by GOUse_go_eternal_flame(), and OnCreatureCreate().
Initialize()
void instance_sunken_temple::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 40 of file sunken_temple.cpp.
References m_auiEncounter.
Referenced by instance_sunken_temple().
Load()
void instance_sunken_temple::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 360 of file sunken_temple.cpp.
References DONE, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_sunken_temple::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 77 of file sunken_temple.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, m_uiProtectorsRemaining, NPC_ATALARION, NPC_GASHER, NPC_HUKKU, NPC_JAMMALAN, NPC_LORO, NPC_MIJAN, NPC_OGOM, NPC_SHADE_OF_ERANIKUS, NPC_ZOLO, NPC_ZULLOR, Object::RemoveFlag(), TYPE_JAMMALAN, TYPE_PROTECTORS, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnCreatureDeath()
void instance_sunken_temple::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 127 of file sunken_temple.cpp.
References DONE, Object::GetEntry(), m_bCanSummonBloodkeeper, NPC_ATALARION, NPC_AVATAR_OF_HAKKAR, NPC_GASHER, NPC_HUKKU, NPC_JAMMALAN, NPC_LORO, NPC_MIJAN, NPC_SUPPRESSOR, NPC_ZOLO, NPC_ZULLOR, SetData(), TYPE_ATALARION, TYPE_AVATAR, TYPE_JAMMALAN, and TYPE_PROTECTORS.
OnCreatureEvade()
void instance_sunken_temple::OnCreatureEvade (Creature * pCreature) virtual
Reimplemented from InstanceData.
Definition at line 107 of file sunken_temple.cpp.
References FAIL, Object::GetEntry(), NPC_AVATAR_OF_HAKKAR, NPC_BLOODKEEPER, NPC_HAKKARI_MINION, NPC_JAMMALAN, NPC_OGOM, NPC_SHADE_OF_ERANIKUS, NPC_SUPPRESSOR, Object::RemoveFlag(), SetData(), TYPE_AVATAR, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnObjectCreate()
void instance_sunken_temple::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file sunken_temple.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_ATALAI_LIGHT_BIG, GO_ETERNAL_FLAME_1, GO_ETERNAL_FLAME_2, GO_ETERNAL_FLAME_3, GO_ETERNAL_FLAME_4, GO_EVIL_CIRCLE, GO_HAKKAR_DOOR_1, GO_HAKKAR_DOOR_2, GO_IDOL_OF_HAKKAR, GO_JAMMALAN_BARRIER, GO_STATE_ACTIVE, m_auiEncounter, m_evilCircleGuidList, ScriptedInstance::m_goEntryGuidStore, m_luiBigLightGUIDs, m_luiFlameGUIDs, GameObject::SetGoState(), and TYPE_PROTECTORS.
ProcessStatueEvent()
bool instance_sunken_temple::ProcessStatueEvent (uint32 uiEventId)
Definition at line 327 of file sunken_temple.cpp.
References m_aAtalaiStatueEvents, m_uiStatueCounter, MAX_STATUES, SetData(), SPECIAL, and TYPE_ATALARION.
Save()
const char* instance_sunken_temple::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 134 of file sunken_temple.h.
References m_strInstData.
SetData()
void instance_sunken_temple::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 151 of file sunken_temple.cpp.
References aSunkenTempleLocation, Unit::CastSpell(), DAY, DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), ScriptedInstance::DoRespawnGameObject(), DoScriptText(), DoSpawnAtalarionIfCan(), DoUpdateFlamesFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetGameObject(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_HAKKAR_DOOR_1, GO_HAKKAR_DOOR_2, GO_JAMMALAN_BARRIER, GO_JUST_DEACTIVATED, Unit::HasAura(), IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bIsFirstHakkarWave, m_evilCircleGuidList, SummonLocations::m_fO, SummonLocations::m_fX, SummonLocations::m_fY, SummonLocations::m_fZ, ScriptedInstance::m_npcEntryGuidStore, m_strInstData, m_suppressionTimer, m_uiAvatarSummonTimer, m_uiFlameCounter, m_uiProtectorsRemaining, m_uiSupressorTimer, MAX_FLAMES, MINUTE, NPC_JAMMALAN, NPC_OGOM, NPC_SHADE_OF_ERANIKUS, NPC_SHADE_OF_HAKKAR, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_AVATAR_BRAZIER_1, SAY_AVATAR_BRAZIER_2, SAY_AVATAR_BRAZIER_3, SAY_AVATAR_BRAZIER_4, SAY_JAMMALAN_INTRO, SPECIAL, SPELL_SUMMON_AVATAR, SPELL_SUPPRESSION, WorldObject::SummonCreature(), TEMPSPAWN_MANUAL_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_ATALARION, TYPE_AVATAR, TYPE_JAMMALAN, TYPE_MALFURION, TYPE_PROTECTORS, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, and urand().
Referenced by GOUse_go_eternal_flame(), OnCreatureDeath(), OnCreatureEvade(), ProcessStatueEvent(), and Update().
Update()
void instance_sunken_temple::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 391 of file sunken_temple.cpp.
References aHakkariDoorLocations, DoScriptText(), FAIL, Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bCanSummonBloodkeeper, m_bIsFirstHakkarWave, m_evilCircleGuidList, SummonLocations::m_fX, SummonLocations::m_fY, SummonLocations::m_fZ, m_suppressionTimer, m_uiAvatarSummonTimer, m_uiSupressorTimer, NPC_BLOODKEEPER, NPC_HAKKARI_MINION, NPC_SHADE_OF_HAKKAR, NPC_SUPPRESSOR, roll_chance_i(), SAY_AVATAR_DESPAWN, SAY_SUPPRESSOR_1, SAY_SUPPRESSOR_2, SAY_SUPPRESSOR_3, SAY_SUPPRESSOR_4, SetData(), SPELL_SUPPRESSION, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_AVATAR, and urand().
Field Documentation
m_auiEncounter
uint32 instance_sunken_temple::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 141 of file sunken_temple.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), SetData(), and Update().
m_bCanSummonBloodkeeper
bool instance_sunken_temple::m_bCanSummonBloodkeeper protected
Definition at line 151 of file sunken_temple.h.
Referenced by OnCreatureDeath(), and Update().
m_bIsFirstHakkarWave
bool instance_sunken_temple::m_bIsFirstHakkarWave protected
Definition at line 150 of file sunken_temple.h.
Referenced by SetData(), and Update().
m_evilCircleGuidList
GuidVector instance_sunken_temple::m_evilCircleGuidList protected
Definition at line 155 of file sunken_temple.h.
Referenced by OnObjectCreate(), SetData(), and Update().
m_luiBigLightGUIDs
GuidList instance_sunken_temple::m_luiBigLightGUIDs protected
Definition at line 154 of file sunken_temple.h.
Referenced by DoSpawnAtalarionIfCan(), and OnObjectCreate().
m_luiFlameGUIDs
GuidList instance_sunken_temple::m_luiFlameGUIDs protected
Definition at line 153 of file sunken_temple.h.
Referenced by DoUpdateFlamesFlags(), and OnObjectCreate().
m_strInstData
std::string instance_sunken_temple::m_strInstData protected
Definition at line 142 of file sunken_temple.h.
Referenced by Save(), and SetData().
m_suppressionTimer
uint32 instance_sunken_temple::m_suppressionTimer protected
Definition at line 149 of file sunken_temple.h.
Referenced by SetData(), and Update().
m_uiAvatarSummonTimer
uint32 instance_sunken_temple::m_uiAvatarSummonTimer protected
Definition at line 147 of file sunken_temple.h.
Referenced by SetData(), and Update().
m_uiFlameCounter
uint8 instance_sunken_temple::m_uiFlameCounter protected
Definition at line 146 of file sunken_temple.h.
Referenced by SetData().
m_uiProtectorsRemaining
uint8 instance_sunken_temple::m_uiProtectorsRemaining protected
Definition at line 144 of file sunken_temple.h.
Referenced by OnCreatureCreate(), and SetData().
m_uiStatueCounter
uint8 instance_sunken_temple::m_uiStatueCounter protected
Definition at line 145 of file sunken_temple.h.
Referenced by ProcessStatueEvent().
m_uiSupressorTimer
uint32 instance_sunken_temple::m_uiSupressorTimer protected
Definition at line 148 of file sunken_temple.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
sunken_temple.h
sunken_temple.cpp