CMaNGOS_WoTLK: ObjectGuidGenerator< high > Class Template Reference
ObjectGuidGenerator< high > Class Template Reference
#include <ObjectGuid.h>
Public Member Functions
ObjectGuidGenerator (uint32 start=1)
void Set (uint32 val)
uint32 Generate ()
uint32 GetNextAfterMaxUsed () const
Private Attributes
std::atomic< uint32 > m_nextGuid
Detailed Description
template<HighGuid high>
class ObjectGuidGenerator< high >
Definition at line 237 of file ObjectGuid.h.
Constructor & Destructor Documentation
ObjectGuidGenerator()
template<HighGuid high> ObjectGuidGenerator< high >::ObjectGuidGenerator (uint32 start = 1) inline explicit
Definition at line 240 of file ObjectGuid.h.
Member Function Documentation
Generate()
template<HighGuid high> uint32 ObjectGuidGenerator< high >::Generate
Definition at line 67 of file ObjectGuid.cpp.
References ERROR_EXIT_CODE, ObjectGuid::GetMaxCounter(), ObjectGuid::GetTypeName(), sLog, and World::StopNow().
Referenced by ObjectMgr::GenerateCorpseLowGuid(), ObjectMgr::GenerateGroupLowGuid(), ObjectMgr::GenerateInstanceLowGuid(), ObjectMgr::GenerateItemLowGuid(), Map::GenerateLocalLowGuid(), ObjectMgr::GeneratePlayerLowGuid(), ObjectMgr::GenerateStaticCreatureLowGuid(), and ObjectMgr::GenerateStaticGameObjectLowGuid().
GetNextAfterMaxUsed()
template<HighGuid high> uint32 ObjectGuidGenerator< high >::GetNextAfterMaxUsed () const inline
Definition at line 247 of file ObjectGuid.h.
References ObjectGuidGenerator< high >::m_nextGuid.
Referenced by ObjectMgr::GenerateStaticCreatureLowGuid(), ObjectMgr::GenerateStaticGameObjectLowGuid(), and ObjectMgr::SetHighestGuids().
Set()
template<HighGuid high> void ObjectGuidGenerator< high >::Set (uint32 val) inline
Definition at line 243 of file ObjectGuid.h.
References ObjectGuidGenerator< high >::m_nextGuid.
Referenced by Map::Initialize(), and ObjectMgr::SetHighestGuids().
Field Documentation
m_nextGuid
template<HighGuid high> std::atomic<uint32> ObjectGuidGenerator< high >::m_nextGuid private
Definition at line 250 of file ObjectGuid.h.
Referenced by ObjectGuidGenerator< high >::GetNextAfterMaxUsed(), and ObjectGuidGenerator< high >::Set().
The documentation for this class was generated from the following files:
ObjectGuid.h
ObjectGuid.cpp