CMaNGOS_WoTLK: instance_serpentshrine_cavern Class Reference
instance_serpentshrine_cavern Class Reference
#include <serpent_shrine.h>
Public Member Functions
instance_serpentshrine_cavern (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnPlayerResurrect (Player *player) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetData64 (uint32 uiType, uint64 uiGuid) override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
void GetBeamHelpersGUIDList (GuidList &lList) const
void GetTinyTriggerGUIDList (GuidList &lList) const
const char * Save () const override
void Load (const char *chrIn) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void SpawnFishCorpses ()
void EngageBridgeConsole (GameObject *_console=nullptr)
void EngageBossConsole (uint32 uiType, GameObject *console)
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiSpellBinderCount
GuidList m_lFishCorpsesGUIDList
GuidList m_lSpellBindersGUIDList
GuidList m_lBeamHelpersGUIDList
GuidList m_tinyTriggerGUIDList
GuidSet m_sPlatformMobsGUIDSet
GuidSet m_sPlatformMobsAliveGUIDSet
GuidVector m_vashjBridgeParts
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 70 of file serpent_shrine.h.
Constructor & Destructor Documentation
instance_serpentshrine_cavern()
instance_serpentshrine_cavern::instance_serpentshrine_cavern (Map * pMap)
Definition at line 36 of file serpent_shrine.cpp.
References Initialize().
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_serpentshrine_cavern::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 269 of file serpent_shrine.cpp.
References DONE, GetData(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_LURKER, INSTANCE_CONDITION_ID_SCALDING_WATER, m_sPlatformMobsAliveGUIDSet, script_error_log(), and TYPE_THELURKER_EVENT.
EngageBossConsole()
void instance_serpentshrine_cavern::EngageBossConsole (uint32 uiType, GameObject * console) private
Definition at line 350 of file serpent_shrine.cpp.
References DONE, EncounterTypeFromGOEntry(), GAMEOBJECT_FLAGS, Object::GetEntry(), Map::GetGameObject(), GO_CONSOLE_HYDROSS, GO_CONSOLE_KARATHRESS, GO_CONSOLE_LEOTHERAS, GO_CONSOLE_LURKER, GO_CONSOLE_MOROGRIM, GO_FLAG_NO_INTERACT, GO_STATE_ACTIVE, InstanceData::instance, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), SPECIAL, TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
Referenced by OnObjectCreate(), and SetData().
EngageBridgeConsole()
void instance_serpentshrine_cavern::EngageBridgeConsole (GameObject * _console = nullptr) private
Definition at line 323 of file serpent_shrine.cpp.
References GAMEOBJECT_FLAGS, Map::GetGameObject(), GO_CONSOLE_VASHJ, GO_FLAG_NO_INTERACT, InstanceData::instance, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, SPECIAL, TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
Referenced by OnObjectCreate(), and SetData().
ExecuteChatCommand()
void instance_serpentshrine_cavern::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 428 of file serpent_shrine.cpp.
References ChatHandler::ExtractLiteralArg(), IN_PROGRESS, SetData(), and TYPE_THELURKER_EVENT.
GetBeamHelpersGUIDList()
void instance_serpentshrine_cavern::GetBeamHelpersGUIDList (GuidList & lList) const inline
Definition at line 92 of file serpent_shrine.h.
References m_lBeamHelpersGUIDList.
Referenced by boss_hydross_the_unstableAI::DoHandleBeamHelpers().
GetData()
uint32 instance_serpentshrine_cavern::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 250 of file serpent_shrine.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by CheckConditionCriteriaMeet().
GetTinyTriggerGUIDList()
void instance_serpentshrine_cavern::GetTinyTriggerGUIDList (GuidList & lList) const inline
Definition at line 93 of file serpent_shrine.h.
References m_tinyTriggerGUIDList.
Referenced by boss_lady_vashjAI::MovementInform().
Initialize()
void instance_serpentshrine_cavern::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 42 of file serpent_shrine.cpp.
References m_auiEncounter.
Referenced by instance_serpentshrine_cavern().
IsEncounterInProgress()
bool instance_serpentshrine_cavern::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 47 of file serpent_shrine.cpp.
References IN_PROGRESS, m_auiEncounter, and TYPE_COMBAT_MAX.
Load()
void instance_serpentshrine_cavern::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 224 of file serpent_shrine.cpp.
References DONE, IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SpawnFishCorpses(), TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LADYVASHJ_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
OnCreatureCreate()
void instance_serpentshrine_cavern::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 58 of file serpent_shrine.cpp.
References Creature::ForcedDespawn(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), m_lBeamHelpersGUIDList, m_lFishCorpsesGUIDList, m_lSpellBindersGUIDList, ScriptedInstance::m_npcEntryGuidStore, m_sPlatformMobsGUIDSet, m_tinyTriggerGUIDList, NPC_CARIBDIS, NPC_COILFANG_FRENZY_CORPSE, NPC_COILFANG_PRIESTESS, NPC_COILFANG_SHATTERER, NPC_GREYHEART_SPELLBINDER, NPC_GREYHEART_TECHNICIAN, NPC_HYDROSS_BEAM_HELPER, NPC_KARATHRESS, NPC_LADYVASHJ, NPC_LEOTHERAS, NPC_SEER_OLUM, NPC_SHARKKIS, NPC_TIDALVESS, NPC_TINY_TRIGGER, NPC_VASHJIR_HONOR_GUARD, NPC_WORLD_TRIGGER, Object::SetUInt32Value(), UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
OnCreatureDeath()
void instance_serpentshrine_cavern::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 291 of file serpent_shrine.cpp.
References AI_EVENT_CUSTOM_A, Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_sPlatformMobsAliveGUIDSet, m_sPlatformMobsGUIDSet, m_uiSpellBinderCount, MAX_SPELLBINDERS, NPC_COILFANG_PRIESTESS, NPC_COILFANG_SHATTERER, NPC_GREYHEART_SPELLBINDER, NPC_GREYHEART_TECHNICIAN, NPC_LEOTHERAS, NPC_VASHJIR_HONOR_GUARD, and SpawnFishCorpses().
OnCreatureEnterCombat()
void instance_serpentshrine_cavern::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 284 of file serpent_shrine.cpp.
References Object::GetEntry(), Unit::InterruptNonMeleeSpells(), and NPC_GREYHEART_SPELLBINDER.
OnObjectCreate()
void instance_serpentshrine_cavern::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 98 of file serpent_shrine.cpp.
References EngageBossConsole(), EngageBridgeConsole(), Object::GetEntry(), Object::GetObjectGuid(), GO_BRIDGE_PART_1, GO_BRIDGE_PART_2, GO_BRIDGE_PART_3, GO_CONSOLE_HYDROSS, GO_CONSOLE_KARATHRESS, GO_CONSOLE_LEOTHERAS, GO_CONSOLE_LURKER, GO_CONSOLE_MOROGRIM, GO_CONSOLE_VASHJ, GO_SHIELD_GENERATOR_1, GO_SHIELD_GENERATOR_2, GO_SHIELD_GENERATOR_3, GO_SHIELD_GENERATOR_4, GO_STRANGE_POOL, and ScriptedInstance::m_goEntryGuidStore.
OnPlayerResurrect()
void instance_serpentshrine_cavern::OnPlayerResurrect (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 127 of file serpent_shrine.cpp.
References AI_EVENT_CUSTOM_B, ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_auiEncounter, NPC_LEOTHERAS, and TYPE_LEOTHERAS_EVENT.
Save()
const char* instance_serpentshrine_cavern::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 95 of file serpent_shrine.h.
References m_strInstData.
SetData()
void instance_serpentshrine_cavern::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 136 of file serpent_shrine.cpp.
References DONE, ScriptedInstance::DoToggleGameObjectFlags(), EngageBossConsole(), EngageBridgeConsole(), FAIL, Map::GetCreature(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_FLAG_NO_INTERACT, GO_SHIELD_GENERATOR_1, GO_SHIELD_GENERATOR_2, GO_SHIELD_GENERATOR_3, GO_SHIELD_GENERATOR_4, GO_STRANGE_POOL, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_lSpellBindersGUIDList, m_strInstData, m_tinyTriggerGUIDList, m_uiSpellBinderCount, NPC_LADYVASHJ, NPC_WORLD_TRIGGER, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, SPELL_LURKER_SPAWN_TRIGGER, TRIGGERED_OLD_TRIGGERED, TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LADYVASHJ_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_LEOTHERAS_EVENT_DEMONS, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
Referenced by boss_hydross_the_unstableAI::Aggro(), boss_lady_vashjAI::Aggro(), boss_lady_vashjAI::EnterEvadeMode(), ExecuteChatCommand(), boss_hydross_the_unstableAI::JustDied(), boss_lady_vashjAI::JustDied(), and boss_hydross_the_unstableAI::JustReachedHome().
SetData64()
void instance_serpentshrine_cavern::SetData64 (uint32 uiType, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 258 of file serpent_shrine.cpp.
References DATA_WATERSTATE_EVENT, m_sPlatformMobsAliveGUIDSet, and m_sPlatformMobsGUIDSet.
ShowChatCommands()
void instance_serpentshrine_cavern::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 423 of file serpent_shrine.cpp.
References ChatHandler::SendSysMessage().
SpawnFishCorpses()
void instance_serpentshrine_cavern::SpawnFishCorpses () private
Definition at line 314 of file serpent_shrine.cpp.
References Map::GetCreature(), InstanceData::instance, and m_lFishCorpsesGUIDList.
Referenced by Load(), and OnCreatureDeath().
Field Documentation
m_auiEncounter
uint32 instance_serpentshrine_cavern::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 106 of file serpent_shrine.h.
Referenced by EngageBossConsole(), EngageBridgeConsole(), GetData(), Initialize(), IsEncounterInProgress(), Load(), OnPlayerResurrect(), and SetData().
m_lBeamHelpersGUIDList
GuidList instance_serpentshrine_cavern::m_lBeamHelpersGUIDList private
Definition at line 113 of file serpent_shrine.h.
Referenced by GetBeamHelpersGUIDList(), and OnCreatureCreate().
m_lFishCorpsesGUIDList
GuidList instance_serpentshrine_cavern::m_lFishCorpsesGUIDList private
Definition at line 111 of file serpent_shrine.h.
Referenced by OnCreatureCreate(), and SpawnFishCorpses().
m_lSpellBindersGUIDList
GuidList instance_serpentshrine_cavern::m_lSpellBindersGUIDList private
Definition at line 112 of file serpent_shrine.h.
Referenced by OnCreatureCreate(), and SetData().
m_sPlatformMobsAliveGUIDSet
GuidSet instance_serpentshrine_cavern::m_sPlatformMobsAliveGUIDSet private
Definition at line 116 of file serpent_shrine.h.
Referenced by CheckConditionCriteriaMeet(), OnCreatureDeath(), and SetData64().
m_sPlatformMobsGUIDSet
GuidSet instance_serpentshrine_cavern::m_sPlatformMobsGUIDSet private
Definition at line 115 of file serpent_shrine.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and SetData64().
m_strInstData
std::string instance_serpentshrine_cavern::m_strInstData private
Definition at line 107 of file serpent_shrine.h.
Referenced by Save(), and SetData().
m_tinyTriggerGUIDList
GuidList instance_serpentshrine_cavern::m_tinyTriggerGUIDList private
Definition at line 114 of file serpent_shrine.h.
Referenced by GetTinyTriggerGUIDList(), OnCreatureCreate(), and SetData().
m_uiSpellBinderCount
uint32 instance_serpentshrine_cavern::m_uiSpellBinderCount private
Definition at line 109 of file serpent_shrine.h.
Referenced by OnCreatureDeath(), and SetData().
m_vashjBridgeParts
GuidVector instance_serpentshrine_cavern::m_vashjBridgeParts private
Definition at line 117 of file serpent_shrine.h.
The documentation for this class was generated from the following files:
serpent_shrine.h
serpent_shrine.cpp