CMaNGOS_WoTLK: PathFinder Class Reference
PathFinder Class Reference
#include <PathFinder.h>
Public Member Functions
PathFinder (Unit const *owner, bool ignoreNormalization=false)
~PathFinder ()
bool calculate (float destX, float destY, float destZ, bool forceDest=false, bool straightLine=false)
bool calculate (Vector3 const &start, Vector3 const &dest, bool forceDest=false, bool straightLine=false)
void ComputePathToRandomPoint (Vector3 const &startPoint, float maxRange)
void setUseStrightPath (bool useStraightPath)
void setPathLengthLimit (float distance)
Vector3 getStartPosition () const
Vector3 getEndPosition () const
Vector3 getActualEndPosition () const
PointsArray & getPath ()
PathType getPathType () const
Private Member Functions
void setStartPosition (const Vector3 &point)
void setEndPosition (const Vector3 &point)
void setActualEndPosition (const Vector3 &point)
void NormalizePath ()
void SetCurrentNavMesh ()
void clear ()
bool inRange (const Vector3 &p1, const Vector3 &p2, float r, float h) const
float dist3DSqr (const Vector3 &p1, const Vector3 &p2) const
bool inRangeYZX (const float *v1, const float *v2, float r, float h) const
dtPolyRef getPathPolyByPosition (const dtPolyRef *polyPath, uint32 polyPathSize, const float *point, float *distance=nullptr) const
dtPolyRef getPolyByLocation (const float *point, float *distance)
bool HaveTile (const Vector3 &p) const
void BuildPolyPath (const Vector3 &startPos, const Vector3 &endPos)
void BuildPointPath (const float *startPoint, const float *endPoint)
void BuildShortcut ()
NavTerrainFlag getNavTerrain (float x, float y, float z) const
void createFilter ()
void updateFilter ()
uint32 fixupCorridor (dtPolyRef *path, uint32 npath, uint32 maxPath, const dtPolyRef *visited, uint32 nvisited)
bool getSteerTarget (const float *startPos, const float *endPos, float minTargetDist, const dtPolyRef *path, uint32 pathSize, float *steerPos, unsigned char &steerPosFlag, dtPolyRef &steerPosRef) const
dtStatus findSmoothPath (const float *startPos, const float *endPos, const dtPolyRef *polyPath, uint32 polyPathSize, float *smoothPath, int *smoothPathSize, uint32 maxSmoothPathSize)
Private Attributes
PointsArray m_pathPoints
PathType m_type
bool m_useStraightPath
bool m_forceDestination
bool m_straightLine
uint32 m_pointPathLimit
std::vector< float > m_cachedPoints
std::vector< dtPolyRef > m_pathPolyRefs
uint32 m_polyLength
std::vector< dtPolyRef > m_smoothPathPolyRefs
Vector3 m_startPosition
Vector3 m_endPosition
Vector3 m_actualEndPosition
const Unit *const m_sourceUnit
const dtNavMesh * m_navMesh
const dtNavMeshQuery * m_navMeshQuery
const dtNavMeshQuery * m_defaultNavMeshQuery
uint32 m_defaultMapId
bool m_ignoreNormalization
dtQueryFilter m_filter
Detailed Description
Definition at line 67 of file PathFinder.h.
Constructor & Destructor Documentation
PathFinder()
PathFinder::PathFinder (Unit const * owner, bool ignoreNormalization = false)
Definition at line 35 of file PathFinder.cpp.
References createFilter(), MMAP::MMapFactory::createOrGetMMapManager(), DEBUG_FILTER_LOG, Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), MMAP::MMapManager::GetNavMeshQuery(), MMAP::MMapFactory::IsPathfindingEnabled(), LOG_FILTER_PATHFINDING, m_defaultNavMeshQuery, and m_sourceUnit.
~PathFinder()
PathFinder::~PathFinder ()
Definition at line 53 of file PathFinder.cpp.
References DEBUG_FILTER_LOG, Object::GetGUIDLow(), LOG_FILTER_PATHFINDING, and m_sourceUnit.
Member Function Documentation
BuildPointPath()
void PathFinder::BuildPointPath (const float * startPoint, const float * endPoint) private
Definition at line 550 of file PathFinder.cpp.
References BuildShortcut(), CONFIG_BOOL_PATH_FIND_OPTIMIZE, DEBUG_FILTER_LOG, dist3DSqr(), findSmoothPath(), getActualEndPosition(), getEndPosition(), getPolyByLocation(), getStartPosition(), inRange(), INVALID_POLYREF, LINE_FAULT, LOG_FILTER_PATHFINDING, m_cachedPoints, m_forceDestination, m_navMeshQuery, m_pathPoints, m_pathPolyRefs, m_pointPathLimit, m_polyLength, m_straightLine, m_type, m_useStraightPath, PATHFIND_NOPATH, PATHFIND_NORMAL, PATHFIND_NOT_USING_PATH, PATHFIND_SHORT, setActualEndPosition(), SKIP_POINT_LIMIT, SMOOTH_PATH_STEP_SIZE, sWorld, and VERTEX_SIZE.
Referenced by BuildPolyPath().
BuildPolyPath()
void PathFinder::BuildPolyPath (const Vector3 & startPos, const Vector3 & endPos) private
Definition at line 204 of file PathFinder.cpp.
References BuildPointPath(), BuildShortcut(), Unit::CanFly(), Unit::CanSwim(), clear(), DEBUG_FILTER_LOG, Unit::GetCollisionWidth(), Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), getPolyByLocation(), WorldObject::GetTerrain(), Object::GetTypeId(), INVALID_POLYREF, Map::IsDungeon(), TerrainInfo::IsSwimmable(), TerrainInfo::IsUnderWater(), LOG_FILTER_PATHFINDING, m_filter, m_navMeshQuery, m_pathPolyRefs, m_pointPathLimit, m_polyLength, m_sourceUnit, m_straightLine, m_type, MAX_POINT_PATH_LENGTH, PATHFIND_INCOMPLETE, PATHFIND_NOPATH, PATHFIND_NORMAL, PATHFIND_NOT_USING_PATH, setActualEndPosition(), setEndPosition(), sLog, TYPEID_PLAYER, and VERTEX_SIZE.
Referenced by calculate(), and ComputePathToRandomPoint().
BuildShortcut()
void PathFinder::BuildShortcut () private
Definition at line 758 of file PathFinder.cpp.
References clear(), DEBUG_FILTER_LOG, getActualEndPosition(), getStartPosition(), LOG_FILTER_PATHFINDING, m_pathPoints, m_type, NormalizePath(), and PATHFIND_SHORTCUT.
Referenced by BuildPointPath(), BuildPolyPath(), calculate(), and ComputePathToRandomPoint().
calculate() [1/2]
bool PathFinder::calculate (float destX, float destY, float destZ, bool forceDest = false, bool straightLine = false)
Definition at line 78 of file PathFinder.cpp.
References WorldObject::GetPosition(), WorldObject::GetTransport(), and m_sourceUnit.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), WaypointMovementGenerator< Creature >::BuildIntPath(), FormationMovementGenerator::BuildPath(), Spell::CheckCast(), CheckPathToTarget(), ChaseMovementGenerator::DispatchSplineToPosition(), ChatHandler::HandleMmapPathCommand(), ChatHandler::HandleMmapTestArea(), FollowMovementGenerator::Move(), WorldObject::MovePositionToFirstCollision(), and Movement::MoveSplineInit::MoveTo().
calculate() [2/2]
bool PathFinder::calculate (Vector3 const & start, Vector3 const & dest, bool forceDest = false, bool straightLine = false)
Definition at line 88 of file PathFinder.cpp.
References BuildPolyPath(), BuildShortcut(), DEBUG_FILTER_LOG, Object::GetEntry(), Object::GetGUIDHigh(), Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), Unit::hasUnitState(), HaveTile(), MaNGOS::IsValidMapCoord(), LOG_FILTER_PATHFINDING, m_forceDestination, m_navMesh, m_navMeshQuery, m_sourceUnit, m_straightLine, m_type, PATHFIND_NORMAL, PATHFIND_NOT_USING_PATH, SetCurrentNavMesh(), setEndPosition(), setStartPosition(), UNIT_STAT_IGNORE_PATHFINDING, and updateFilter().
clear()
void PathFinder::clear () inline private
Definition at line 129 of file PathFinder.h.
References m_pathPoints, and m_polyLength.
Referenced by BuildPolyPath(), BuildShortcut(), and ComputePathToRandomPoint().
ComputePathToRandomPoint()
void PathFinder::ComputePathToRandomPoint (Vector3 const & startPoint, float maxRange)
Definition at line 1066 of file PathFinder.cpp.
References BuildPolyPath(), BuildShortcut(), Unit::CanSwim(), clear(), Unit::GetCollisionHeight(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), getPolyByLocation(), WorldObject::GetPosition(), WorldObject::GetTransport(), Unit::hasUnitState(), HaveTile(), INVALID_POLYREF, Map::IsInLineOfSight(), Unit::IsInWater(), m_forceDestination, m_navMesh, m_navMeshQuery, M_PI_F, m_sourceUnit, m_straightLine, m_type, PATHFIND_NOPATH, PATHFIND_NORMAL, PATHFIND_SHORTCUT, rand_norm_f(), SetCurrentNavMesh(), setEndPosition(), setStartPosition(), UNIT_STAT_IGNORE_PATHFINDING, and updateFilter().
createFilter()
void PathFinder::createFilter () private
Definition at line 776 of file PathFinder.cpp.
References Creature::CanSwim(), Creature::CanWalk(), Object::GetTypeId(), m_filter, m_sourceUnit, NAV_GROUND, NAV_MAGMA_SLIME, NAV_WATER, TYPEID_PLAYER, TYPEID_UNIT, and updateFilter().
Referenced by PathFinder().
dist3DSqr()
float PathFinder::dist3DSqr (const Vector3 & p1, const Vector3 & p2) const private
Definition at line 1155 of file PathFinder.cpp.
Referenced by BuildPointPath().
findSmoothPath()
dtStatus PathFinder::findSmoothPath (const float * startPos, const float * endPos, const dtPolyRef * polyPath, uint32 polyPathSize, float * smoothPath, int * smoothPathSize, uint32 maxSmoothPathSize) private
Definition at line 941 of file PathFinder.cpp.
References fixupCorridor(), getSteerTarget(), inRangeYZX(), INVALID_POLYREF, m_filter, m_navMesh, m_navMeshQuery, m_pointPathLimit, m_smoothPathPolyRefs, SMOOTH_PATH_SLOP, SMOOTH_PATH_STEP_SIZE, and VERTEX_SIZE.
Referenced by BuildPointPath().
fixupCorridor()
uint32 PathFinder::fixupCorridor (dtPolyRef * path, uint32 npath, uint32 maxPath, const dtPolyRef * visited, uint32 nvisited) private
Definition at line 856 of file PathFinder.cpp.
Referenced by findSmoothPath().
getActualEndPosition()
Vector3 PathFinder::getActualEndPosition () const inline
Definition at line 88 of file PathFinder.h.
References m_actualEndPosition.
Referenced by BuildPointPath(), BuildShortcut(), and ChatHandler::HandleMmapPathCommand().
getEndPosition()
Vector3 PathFinder::getEndPosition () const inline
Definition at line 87 of file PathFinder.h.
References m_endPosition.
Referenced by BuildPointPath(), ChatHandler::HandleMmapPathCommand(), and ChaseMovementGenerator::HandleTargetedMovement().
getNavTerrain()
NavTerrainFlag PathFinder::getNavTerrain (float x, float y, float z) const private
Definition at line 818 of file PathFinder.cpp.
References TerrainInfo::getLiquidStatus(), WorldObject::GetTerrain(), LIQUID_MAP_NO_WATER, m_sourceUnit, MAP_ALL_LIQUIDS, MAP_LIQUID_TYPE_MAGMA, MAP_LIQUID_TYPE_OCEAN, MAP_LIQUID_TYPE_SLIME, MAP_LIQUID_TYPE_WATER, NAV_GROUND, NAV_MAGMA_SLIME, NAV_WATER, and GridMapLiquidData::type_flags.
Referenced by updateFilter().
getPath()
PointsArray& PathFinder::getPath () inline
Definition at line 90 of file PathFinder.h.
References m_pathPoints.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), WaypointMovementGenerator< Creature >::BuildIntPath(), FormationMovementGenerator::BuildPath(), CheckPathToTarget(), ChaseMovementGenerator::DispatchSplineToPosition(), ChaseMovementGenerator::GetPrintout(), ChatHandler::HandleMmapPathCommand(), FollowMovementGenerator::Move(), WorldObject::MovePositionToFirstCollision(), and Movement::MoveSplineInit::MoveTo().
getPathPolyByPosition()
dtPolyRef PathFinder::getPathPolyByPosition (const dtPolyRef * polyPath, uint32 polyPathSize, const float * point, float * distance = nullptr) const private
Definition at line 136 of file PathFinder.cpp.
References INVALID_POLYREF, m_navMeshQuery, and VERTEX_SIZE.
Referenced by getPolyByLocation().
getPathType()
PathType PathFinder::getPathType () const inline
Definition at line 91 of file PathFinder.h.
References m_type.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), Spell::CheckCast(), CheckPathToTarget(), ChaseMovementGenerator::DispatchSplineToPosition(), ChatHandler::HandleMmapPathCommand(), FollowMovementGenerator::Move(), and WorldObject::MovePositionToFirstCollision().
getPolyByLocation()
dtPolyRef PathFinder::getPolyByLocation (const float * point, float * distance) private
Definition at line 167 of file PathFinder.cpp.
References FarPolySearchBound, getPathPolyByPosition(), INVALID_POLYREF, m_filter, m_navMeshQuery, m_pathPolyRefs, m_polyLength, NearPolySearchBound, and VERTEX_SIZE.
Referenced by BuildPointPath(), BuildPolyPath(), and ComputePathToRandomPoint().
getStartPosition()
Vector3 PathFinder::getStartPosition () const inline
Definition at line 86 of file PathFinder.h.
References m_startPosition.
Referenced by BuildPointPath(), BuildShortcut(), and ChatHandler::HandleMmapPathCommand().
getSteerTarget()
bool PathFinder::getSteerTarget (const float * startPos, const float * endPos, float minTargetDist, const dtPolyRef * path, uint32 pathSize, float * steerPos, unsigned char & steerPosFlag, dtPolyRef & steerPosRef) const private
Definition at line 904 of file PathFinder.cpp.
References inRangeYZX(), m_navMeshQuery, and VERTEX_SIZE.
Referenced by findSmoothPath().
HaveTile()
bool PathFinder::HaveTile (const Vector3 & p) const private
Workaround For some reason, often the tx and ty variables wont get a valid value Use this check to prevent getting negative tile coords and crashing on getTileAt
Definition at line 837 of file PathFinder.cpp.
References WorldObject::GetTransport(), m_navMesh, m_sourceUnit, and VERTEX_SIZE.
Referenced by calculate(), and ComputePathToRandomPoint().
inRange()
bool PathFinder::inRange (const Vector3 & p1, const Vector3 & p2, float r, float h) const private
Definition at line 1149 of file PathFinder.cpp.
Referenced by BuildPointPath().
inRangeYZX()
bool PathFinder::inRangeYZX (const float * v1, const float * v2, float r, float h) const private
Definition at line 1141 of file PathFinder.cpp.
Referenced by findSmoothPath(), and getSteerTarget().
NormalizePath()
void PathFinder::NormalizePath () private
Definition at line 741 of file PathFinder.cpp.
References GenericTransport::CalculatePassengerOffset(), GenericTransport::CalculatePassengerPosition(), CONFIG_BOOL_PATH_FIND_NORMALIZE_Z, WorldObject::GetTransport(), m_ignoreNormalization, m_pathPoints, m_sourceUnit, sWorld, and Unit::UpdateAllowedPositionZ().
Referenced by BuildShortcut().
setActualEndPosition()
void PathFinder::setActualEndPosition (const Vector3 & point) inline private
Definition at line 125 of file PathFinder.h.
References m_actualEndPosition.
Referenced by BuildPointPath(), and BuildPolyPath().
SetCurrentNavMesh()
void PathFinder::SetCurrentNavMesh () private
Definition at line 58 of file PathFinder.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), MMAP::MMapManager::GetModelNavMeshQuery(), MMAP::MMapManager::GetNavMeshQuery(), WorldObject::GetTransport(), MMAP::MMapFactory::IsPathfindingEnabled(), m_defaultMapId, m_defaultNavMeshQuery, m_navMesh, m_navMeshQuery, and m_sourceUnit.
Referenced by calculate(), and ComputePathToRandomPoint().
setEndPosition()
void PathFinder::setEndPosition (const Vector3 & point) inline private
Definition at line 124 of file PathFinder.h.
References m_actualEndPosition, and m_endPosition.
Referenced by BuildPolyPath(), calculate(), and ComputePathToRandomPoint().
setPathLengthLimit()
void PathFinder::setPathLengthLimit (float distance) inline
Definition at line 83 of file PathFinder.h.
References m_pointPathLimit, MAX_POINT_PATH_LENGTH, and SMOOTH_PATH_STEP_SIZE.
Referenced by Spell::CheckCast().
setStartPosition()
void PathFinder::setStartPosition (const Vector3 & point) inline private
Definition at line 123 of file PathFinder.h.
References m_startPosition.
Referenced by calculate(), and ComputePathToRandomPoint().
setUseStrightPath()
void PathFinder::setUseStrightPath (bool useStraightPath) inline
Definition at line 82 of file PathFinder.h.
References m_useStraightPath.
Referenced by ChatHandler::HandleMmapPathCommand().
updateFilter()
void PathFinder::updateFilter () private
Definition at line 803 of file PathFinder.cpp.
References getNavTerrain(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::IsInWater(), Unit::IsUnderwater(), m_filter, and m_sourceUnit.
Referenced by calculate(), ComputePathToRandomPoint(), and createFilter().
Field Documentation
m_actualEndPosition
Vector3 PathFinder::m_actualEndPosition private
Definition at line 110 of file PathFinder.h.
Referenced by getActualEndPosition(), setActualEndPosition(), and setEndPosition().
m_cachedPoints
std::vector<float> PathFinder::m_cachedPoints private
Definition at line 102 of file PathFinder.h.
Referenced by BuildPointPath().
m_defaultMapId
uint32 PathFinder::m_defaultMapId private
Definition at line 117 of file PathFinder.h.
Referenced by SetCurrentNavMesh().
m_defaultNavMeshQuery
const dtNavMeshQuery* PathFinder::m_defaultNavMeshQuery private
Definition at line 116 of file PathFinder.h.
Referenced by PathFinder(), and SetCurrentNavMesh().
m_endPosition
Vector3 PathFinder::m_endPosition private
Definition at line 109 of file PathFinder.h.
Referenced by getEndPosition(), and setEndPosition().
m_filter
dtQueryFilter PathFinder::m_filter private
Definition at line 121 of file PathFinder.h.
Referenced by BuildPolyPath(), createFilter(), findSmoothPath(), getPolyByLocation(), and updateFilter().
m_forceDestination
bool PathFinder::m_forceDestination private
Definition at line 99 of file PathFinder.h.
Referenced by BuildPointPath(), calculate(), and ComputePathToRandomPoint().
m_ignoreNormalization
bool PathFinder::m_ignoreNormalization private
Definition at line 119 of file PathFinder.h.
Referenced by NormalizePath().
m_navMesh
const dtNavMesh* PathFinder::m_navMesh private
Definition at line 113 of file PathFinder.h.
Referenced by calculate(), ComputePathToRandomPoint(), findSmoothPath(), HaveTile(), and SetCurrentNavMesh().
m_navMeshQuery
const dtNavMeshQuery* PathFinder::m_navMeshQuery private
Definition at line 114 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), calculate(), ComputePathToRandomPoint(), findSmoothPath(), getPathPolyByPosition(), getPolyByLocation(), getSteerTarget(), and SetCurrentNavMesh().
m_pathPoints
PointsArray PathFinder::m_pathPoints private
Definition at line 95 of file PathFinder.h.
Referenced by BuildPointPath(), BuildShortcut(), clear(), getPath(), and NormalizePath().
m_pathPolyRefs
std::vector<dtPolyRef> PathFinder::m_pathPolyRefs private
Definition at line 104 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), and getPolyByLocation().
m_pointPathLimit
uint32 PathFinder::m_pointPathLimit private
Definition at line 101 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), findSmoothPath(), and setPathLengthLimit().
m_polyLength
uint32 PathFinder::m_polyLength private
Definition at line 105 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), clear(), and getPolyByLocation().
m_smoothPathPolyRefs
std::vector<dtPolyRef> PathFinder::m_smoothPathPolyRefs private
Definition at line 106 of file PathFinder.h.
Referenced by findSmoothPath().
m_sourceUnit
const Unit* const PathFinder::m_sourceUnit private
Definition at line 112 of file PathFinder.h.
Referenced by BuildPolyPath(), calculate(), ComputePathToRandomPoint(), createFilter(), getNavTerrain(), HaveTile(), NormalizePath(), PathFinder(), SetCurrentNavMesh(), updateFilter(), and ~PathFinder().
m_startPosition
Vector3 PathFinder::m_startPosition private
Definition at line 108 of file PathFinder.h.
Referenced by getStartPosition(), and setStartPosition().
m_straightLine
bool PathFinder::m_straightLine private
Definition at line 100 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), calculate(), and ComputePathToRandomPoint().
m_type
PathType PathFinder::m_type private
Definition at line 96 of file PathFinder.h.
Referenced by BuildPointPath(), BuildPolyPath(), BuildShortcut(), calculate(), ComputePathToRandomPoint(), and getPathType().
m_useStraightPath
bool PathFinder::m_useStraightPath private
Definition at line 98 of file PathFinder.h.
Referenced by BuildPointPath(), and setUseStrightPath().
The documentation for this class was generated from the following files:
PathFinder.h
PathFinder.cpp