CMaNGOS_WoTLK: WintergraspPlayer Class Reference
WintergraspPlayer Class Reference
#include <BattlefieldWG.h>
Public Member Functions
WintergraspPlayer ()
void SetPlayerRank (WintergraspRank rank)
WintergraspRank GetPlayerRank () const
void IncreaseKillCount ()
uint32 GetKillCount ()
Public Member Functions inherited from BattlefieldPlayer
BattlefieldPlayer ()
Protected Attributes
uint32 killCount
WintergraspRank playerRank
Additional Inherited Members
Data Fields inherited from BattlefieldPlayer
time_t removeTime
uint32 removeDelay
Detailed Description
Definition at line 653 of file BattlefieldWG.h.
Constructor & Destructor Documentation
WintergraspPlayer()
WintergraspPlayer::WintergraspPlayer () inline
Definition at line 656 of file BattlefieldWG.h.
Member Function Documentation
GetKillCount()
uint32 WintergraspPlayer::GetKillCount () inline
Definition at line 663 of file BattlefieldWG.h.
References killCount.
Referenced by BattlefieldWG::UpdatePlayerScore().
GetPlayerRank()
WintergraspRank WintergraspPlayer::GetPlayerRank () const inline
Definition at line 659 of file BattlefieldWG.h.
References playerRank.
Referenced by BattlefieldWG::UpdatePlayerScore().
IncreaseKillCount()
void WintergraspPlayer::IncreaseKillCount () inline
Definition at line 662 of file BattlefieldWG.h.
References killCount.
Referenced by BattlefieldWG::HandlePlayerKillInsideArea().
SetPlayerRank()
void WintergraspPlayer::SetPlayerRank (WintergraspRank rank) inline
Definition at line 658 of file BattlefieldWG.h.
References playerRank.
Referenced by BattlefieldWG::UpdatePlayerScore().
Field Documentation
killCount
uint32 WintergraspPlayer::killCount protected
Definition at line 666 of file BattlefieldWG.h.
Referenced by GetKillCount(), and IncreaseKillCount().
playerRank
WintergraspRank WintergraspPlayer::playerRank protected
Definition at line 667 of file BattlefieldWG.h.
Referenced by GetPlayerRank(), and SetPlayerRank().
The documentation for this class was generated from the following file:
BattlefieldWG.h