CMaNGOS_WoTLK: NamreebAnticheat::Movement Class Reference
NamreebAnticheat::Movement Class Reference
#include <movement.hpp>
Data Structures
struct Ack
struct MovementHistory
struct Order
struct TimeSkip
struct WorldChange
Public Member Functions
Movement (Player *me)
float TotalDistanceTraveled () const
bool IsInKnockBack () const
void KnockBack (float speedxy, float speedz, float cos, float sin)
bool HandleAnticheatTests (MovementInfo &movementInfo, WorldSession *session, const WorldPacket &packet)
bool HandleSpeedChangeAck (MovementInfo &movementInfo, WorldSession *session, const WorldPacket &packet, float newSpeed)
void HandleEnterWorld ()
void HandleLeaveWorld ()
void TimeSkipped (const ObjectGuid &mover, uint32 ms)
void HandleTeleport (const Position &pos)
void VerifyMovementFlags (uint32 flags, uint32 &removeFlags, bool strict) const
void OrderSent (uint16 opcode, uint32 counter)
void OrderAck (uint16 opcode, uint32 counter)
void CheckExpiredOrders (uint32 latency)
bool ExtrapolateMovement (MovementInfo const &mi, uint32 diffMs, Position &pos) const
bool GetMaxAllowedDist (MovementInfo const &mi, uint32 diffMs, float &dxy, float &dz) const
void OnExplore (AreaTableEntry const *p)
void OnTransport (Player *plMover, ObjectGuid transportGuid)
bool CheckTeleport (uint16 opcode, MovementInfo &movementInfo)
void SendOrderInfo (ChatHandler *handler) const
size_t PendingOrderCount () const
size_t DumpOrders (std::string &out) const
size_t DumpAcks (std::string &out) const
size_t DumpTimeSkips (std::string &out) const
size_t DumpWorldChanges (std::string &out) const
size_t DumpMovement (std::string &out) const
Data Fields
float clientSpeeds [MAX_MOVE_TYPE]
float overSpeedDistanceTick
float overSpeedDistanceTotal
Private Member Functions
MovementInfo & GetLastMovementInfo () const
float GetXYFlagBasedClientSpeed (uint32 moveFlags) const
bool IsTeleportAllowed (MovementInfo const &movementInfo, float &distance)
bool CheckFallReset (MovementInfo const &movementInfo) const
Private Attributes
SessionAnticheat *const _anticheat
Player *const _me
float _totalDistanceTraveled
bool _wasMovingOther
bool _justTeleported
std::deque< PendingOrder > _orders
uint32 _serverInitTime
uint32 _clientInitTime
float _jumpInitialSpeed
bool _inKnockBack
nam::cyclic< Order, 15 > _orderHistory
nam::cyclic< Ack, 15 > _ackHistory
nam::cyclic< TimeSkip, 15 > _timeSkipHistory
nam::cyclic< WorldChange, 15 > _worldChangeHistory
nam::cyclic< MovementHistory, 45 > _moveHistory
Detailed Description
Definition at line 35 of file movement.hpp.
Constructor & Destructor Documentation
Movement()
NamreebAnticheat::Movement::Movement (Player * me) explicit
Definition at line 99 of file movement.cpp.
References _anticheat, clientSpeeds, and MANGOS_ASSERT.
Member Function Documentation
CheckExpiredOrders()
void NamreebAnticheat::Movement::CheckExpiredOrders (uint32 latency)
Definition at line 291 of file movement.cpp.
References _orders, and WorldTimer::getMSTime().
CheckFallReset()
bool NamreebAnticheat::Movement::CheckFallReset (MovementInfo const & movementInfo) const private
Definition at line 972 of file movement.cpp.
References NamreebAnticheat::CONFIG_BOOL_AC_MOVEMENT_CHEAT_BAD_FALL_RESET_ENABLED, MovementInfo::fallTime, GetLastMovementInfo(), MovementInfo::jump, MOVEFLAG_FALLINGFAR, sAnticheatConfig, and MovementInfo::JumpInfo::zspeed.
Referenced by HandleAnticheatTests().
CheckTeleport()
bool NamreebAnticheat::Movement::CheckTeleport (uint16 opcode, MovementInfo & movementInfo)
Definition at line 986 of file movement.cpp.
References _anticheat, _me, NamreebAnticheat::CHEAT_TYPE_FORBIDDEN, NamreebAnticheat::CHEAT_TYPE_TELEPORT, NamreebAnticheat::CHEAT_TYPE_TELEPORT_FAR, GetAreaEntryByAreaID(), MovementInfo::GetMovementFlags(), Player::GetMover(), WorldSession::GetSecurity(), Player::GetSession(), WorldObject::GetTerrain(), Object::GetTypeId(), TerrainInfo::GetZoneAndAreaId(), IsTeleportAllowed(), LookupOpcodeName(), MOVEFLAG_ONTRANSPORT, MapEntry::name, MovementInfo::pos, NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), MovementInfo::RemoveMovementFlag(), sAnticheatConfig, Player::SavePositionInDB(), SEC_PLAYER, sLog, sMapStore, TYPEID_PLAYER, VerifyMovementFlags(), Position::x, Position::y, and Position::z.
DumpAcks()
size_t NamreebAnticheat::Movement::DumpAcks (std::string & out) const
Definition at line 1117 of file movement.cpp.
References _ackHistory, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), and LookupOpcodeName().
DumpMovement()
size_t NamreebAnticheat::Movement::DumpMovement (std::string & out) const
Definition at line 1174 of file movement.cpp.
References _moveHistory, WorldTimer::getMSTime(), LookupOpcodeName(), and MOVEFLAG_FALLING.
Referenced by HandleAnticheatTests().
DumpOrders()
size_t NamreebAnticheat::Movement::DumpOrders (std::string & out) const
Definition at line 1097 of file movement.cpp.
References _orderHistory, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), and LookupOpcodeName().
DumpTimeSkips()
size_t NamreebAnticheat::Movement::DumpTimeSkips (std::string & out) const
Definition at line 1137 of file movement.cpp.
References _timeSkipHistory, WorldTimer::getMSTime(), and WorldTimer::getMSTimeDiff().
DumpWorldChanges()
size_t NamreebAnticheat::Movement::DumpWorldChanges (std::string & out) const
Definition at line 1157 of file movement.cpp.
References _worldChangeHistory.
ExtrapolateMovement()
bool NamreebAnticheat::Movement::ExtrapolateMovement (MovementInfo const & mi, uint32 diffMs, Position & pos) const
Definition at line 737 of file movement.cpp.
References _jumpInitialSpeed, _me, clientSpeeds, Movement::computeFallElevation(), MovementInfo::JumpInfo::cosAngle, MovementInfo::ctime, Movement::MoveSpline::Finalized(), Map::GetHeight(), WorldObject::GetMap(), WorldTimer::getMSTimeDiff(), WorldObject::GetPhaseMask(), Map::IsInLineOfSight(), MaNGOS::IsValidMapCoord(), MovementInfo::jump, M_PI, M_PI_F, MOVE_TURN_RATE, MOVEFLAG_BACKWARD, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, MOVEFLAG_FORWARD, MOVEFLAG_MASK_MOVING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_PITCH_DOWN, MOVEFLAG_PITCH_UP, MOVEFLAG_SAFE_FALL, MOVEFLAG_STRAFE_LEFT, MOVEFLAG_STRAFE_RIGHT, MOVEFLAG_SWIMMING, MOVEFLAG_TURN_LEFT, MOVEFLAG_TURN_RIGHT, MOVEFLAG_WATERWALKING, MovementInfo::moveFlags, Unit::movespline, Position::o, MovementInfo::pos, MovementInfo::s_pitch, MovementInfo::JumpInfo::sinAngle, MovementInfo::JumpInfo::start, MovementInfo::JumpInfo::startClientTime, Position::x, MovementInfo::JumpInfo::xyspeed, Position::y, and Position::z.
Referenced by HandleAnticheatTests().
GetLastMovementInfo()
MovementInfo & NamreebAnticheat::Movement::GetLastMovementInfo () const private
Definition at line 703 of file movement.cpp.
References _me, and WorldObject::m_movementInfo.
Referenced by CheckFallReset(), HandleAnticheatTests(), and KnockBack().
GetMaxAllowedDist()
bool NamreebAnticheat::Movement::GetMaxAllowedDist (MovementInfo const & mi, uint32 diffMs, float & dxy, float & dz) const
Definition at line 856 of file movement.cpp.
References _me, clientSpeeds, MovementInfo::ctime, Movement::MoveSpline::Finalized(), MovementInfo::jump, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, MOVEFLAG_MASK_MOVING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_SAFE_FALL, MovementInfo::moveFlags, Unit::movespline, Movement::terminalVelocity, and MovementInfo::JumpInfo::xyspeed.
Referenced by HandleAnticheatTests().
GetXYFlagBasedClientSpeed()
float NamreebAnticheat::Movement::GetXYFlagBasedClientSpeed (uint32 moveFlags) const private
Definition at line 708 of file movement.cpp.
References clientSpeeds, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_WALK, MOVEFLAG_BACKWARD, MOVEFLAG_MASK_XY, MOVEFLAG_SWIMMING, and MOVEFLAG_WALK_MODE.
Referenced by HandleAnticheatTests().
HandleAnticheatTests()
bool NamreebAnticheat::Movement::HandleAnticheatTests (MovementInfo & movementInfo, WorldSession * session, const WorldPacket & packet)
Definition at line 313 of file movement.cpp.
References _anticheat, _clientInitTime, _inKnockBack, _jumpInitialSpeed, _justTeleported, _me, _moveHistory, _serverInitTime, _totalDistanceTraveled, _wasMovingOther, ALLIANCE, NamreebAnticheat::CHEAT_TYPE_BAD_FALL_RESET, NamreebAnticheat::CHEAT_TYPE_FLY_HACK, NamreebAnticheat::CHEAT_TYPE_FORBIDDEN, NamreebAnticheat::CHEAT_TYPE_JUMP_SPEED_CHANGE, NamreebAnticheat::CHEAT_TYPE_MULTIJUMP, NamreebAnticheat::CHEAT_TYPE_NULL_CLIENT_TIME, NamreebAnticheat::CHEAT_TYPE_NUM_DESYNC, NamreebAnticheat::CHEAT_TYPE_OVERSPEED_JUMP, NamreebAnticheat::CHEAT_TYPE_OVERSPEED_Z, NamreebAnticheat::CHEAT_TYPE_SKIPPED_HEARTBEATS, NamreebAnticheat::CHEAT_TYPE_TELE_TO_TRANSPORT, NamreebAnticheat::CHEAT_TYPE_TIME_BACK, CheckFallReset(), clientSpeeds, CMSG_MOVE_FALL_RESET, CMSG_MOVE_FEATHER_FALL_ACK, CMSG_MOVE_KNOCK_BACK_ACK, MovementInfo::JumpInfo::cosAngle, MovementInfo::ctime, DumpMovement(), ExtrapolateMovement(), MovementInfo::fallTime, Movement::MoveSpline::Finalized(), GetAnticheatLib(), Player::GetBattleGround(), GetLastMovementInfo(), WorldObject::GetMapId(), GetMaxAllowedDist(), NamreebAnticheat::SessionAnticheat::GetMovementDebugString(), WorldTimer::getMSTimeDiff(), WorldPacket::GetOpcode(), Player::GetTeam(), GetXYFlagBasedClientSpeed(), Unit::GetXYFlagBasedSpeed(), HORDE, IN_MILLISECONDS, NamreebAnticheat::SessionAnticheat::IsBanTimerActive(), IsInKnockBack(), NamreebAnticheat::SessionAnticheat::IsKickTimerActive(), Player::IsSelfMover(), Unit::IsTaxiFlying(), MovementInfo::jump, LookupOpcodeName(), MANGOS_ASSERT, MINUTE, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, MOVEFLAG_MASK_MOVING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_SWIMMING, MOVEFLAG_WATERWALKING, MovementInfo::moveFlags, Unit::movespline, MSG_MOVE_FALL_LAND, MSG_MOVE_JUMP, MSG_MOVE_STOP, MSG_MOVE_STOP_SWIM, overSpeedDistanceTick, overSpeedDistanceTotal, MovementInfo::pos, NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), sAnticheatConfig, MovementInfo::JumpInfo::sinAngle, sLog, MovementInfo::JumpInfo::startClientTime, STATUS_WAIT_JOIN, MovementInfo::stime, Position::x, MovementInfo::JumpInfo::xyspeed, Position::y, Position::z, and MovementInfo::JumpInfo::zspeed.
Referenced by HandleSpeedChangeAck().
HandleEnterWorld()
void NamreebAnticheat::Movement::HandleEnterWorld ()
Definition at line 678 of file movement.cpp.
References _me, _worldChangeHistory, clientSpeeds, WorldTimer::getMSTime(), Unit::GetSpeed(), and MAX_MOVE_TYPE.
HandleLeaveWorld()
void NamreebAnticheat::Movement::HandleLeaveWorld ()
Definition at line 686 of file movement.cpp.
References _clientInitTime, _serverInitTime, _worldChangeHistory, and WorldTimer::getMSTime().
HandleSpeedChangeAck()
bool NamreebAnticheat::Movement::HandleSpeedChangeAck (MovementInfo & movementInfo, WorldSession * session, const WorldPacket & packet, float newSpeed)
Definition at line 630 of file movement.cpp.
References _me, clientSpeeds, CMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_FLIGHT_SPEED_CHANGE_ACK, CMSG_FORCE_RUN_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_RUN_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_BACK_SPEED_CHANGE_ACK, CMSG_FORCE_SWIM_SPEED_CHANGE_ACK, CMSG_FORCE_TURN_RATE_CHANGE_ACK, CMSG_FORCE_WALK_SPEED_CHANGE_ACK, DETAIL_LOG, WorldObject::GetName(), WorldPacket::GetOpcode(), Unit::GetSpeed(), Unit::GetSpeedRate(), WorldObject::GetTransport(), HandleAnticheatTests(), MAX_MOVE_TYPE, MOVE_FLIGHT, MOVE_FLIGHT_BACK, MOVE_RUN, MOVE_RUN_BACK, MOVE_SWIM, MOVE_SWIM_BACK, MOVE_TURN_RATE, MOVE_WALK, and Unit::SetSpeedRate().
HandleTeleport()
void NamreebAnticheat::Movement::HandleTeleport (const Position & pos)
Definition at line 908 of file movement.cpp.
References _justTeleported.
IsInKnockBack()
bool NamreebAnticheat::Movement::IsInKnockBack () const inline
Definition at line 118 of file movement.hpp.
References _inKnockBack.
Referenced by HandleAnticheatTests().
IsTeleportAllowed()
bool NamreebAnticheat::Movement::IsTeleportAllowed (MovementInfo const & movementInfo, float & distance) private
Definition at line 925 of file movement.cpp.
References _me, WorldObject::GetAreaId(), MovementInfo::GetPos(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTerrain(), TerrainInfo::GetZoneAndAreaId(), WorldObject::GetZoneId(), Player::IsBeingTeleported(), Player::IsLaunched(), MovementInfo::pos, Position::x, Position::y, and Position::z.
Referenced by CheckTeleport().
KnockBack()
void NamreebAnticheat::Movement::KnockBack (float speedxy, float speedz, float cos, float sin)
Definition at line 110 of file movement.cpp.
References _inKnockBack, _jumpInitialSpeed, _me, MovementInfo::JumpInfo::cosAngle, MovementInfo::ctime, GetLastMovementInfo(), WorldTimer::getMSTime(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), MovementInfo::jump, MOVEFLAG_MASK_MOVING_OR_TURN, MovementInfo::moveFlags, MovementInfo::JumpInfo::sinAngle, MovementInfo::JumpInfo::start, MovementInfo::JumpInfo::startClientTime, MovementInfo::stime, Position::x, MovementInfo::JumpInfo::xyspeed, Position::y, Position::z, and MovementInfo::JumpInfo::zspeed.
OnExplore()
void NamreebAnticheat::Movement::OnExplore (AreaTableEntry const * p)
Definition at line 899 of file movement.cpp.
References _anticheat, _me, AreaTableEntry::area_level, NamreebAnticheat::CHEAT_TYPE_EXPLORE, NamreebAnticheat::CHEAT_TYPE_EXPLORE_HIGH_LEVEL, Unit::GetLevel(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), and sAnticheatConfig.
OnTransport()
void NamreebAnticheat::Movement::OnTransport (Player * plMover, ObjectGuid transportGuid)
Definition at line 913 of file movement.cpp.
References _anticheat, NamreebAnticheat::CHEAT_TYPE_FAKE_TRANSPORT, Map::GetGameObject(), WorldObject::GetMap(), WorldObject::GetMapId(), GameObject::IsTransport(), WorldObject::IsWithinDist(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), and sAnticheatConfig.
OrderAck()
void NamreebAnticheat::Movement::OrderAck (uint16 opcode, uint32 counter)
Definition at line 245 of file movement.cpp.
References _ackHistory, _anticheat, _me, _orders, NamreebAnticheat::CHEAT_TYPE_BAD_ORDER_ACK, WorldTimer::getMSTime(), WorldObject::GetName(), LookupOpcodeName(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), sAnticheatConfig, and sLog.
OrderSent()
void NamreebAnticheat::Movement::OrderSent (uint16 opcode, uint32 counter)
Definition at line 236 of file movement.cpp.
References _me, _orderHistory, _orders, WorldTimer::getMSTime(), WorldObject::GetName(), LookupOpcodeName(), and sLog.
PendingOrderCount()
size_t NamreebAnticheat::Movement::PendingOrderCount () const inline
Definition at line 146 of file movement.hpp.
References _orders.
SendOrderInfo()
void NamreebAnticheat::Movement::SendOrderInfo (ChatHandler * handler) const
Definition at line 1072 of file movement.cpp.
References _anticheat, _orders, NamreebAnticheat::SessionAnticheat::GetMovementDebugString(), WorldTimer::getMSTime(), LookupOpcodeName(), and ChatHandler::PSendSysMessage().
TimeSkipped()
void NamreebAnticheat::Movement::TimeSkipped (const ObjectGuid & mover, uint32 ms)
Definition at line 693 of file movement.cpp.
References _clientInitTime, _me, _timeSkipHistory, Object::GetGUIDLow(), WorldTimer::getMSTime(), WorldObject::GetName(), ObjectGuid::GetRawValue(), and sLog.
TotalDistanceTraveled()
float NamreebAnticheat::Movement::TotalDistanceTraveled () const inline
Definition at line 116 of file movement.hpp.
References _totalDistanceTraveled.
VerifyMovementFlags()
void NamreebAnticheat::Movement::VerifyMovementFlags (uint32 flags, uint32 & removeFlags, bool strict) const
Definition at line 125 of file movement.cpp.
References _anticheat, _me, _orders, NamreebAnticheat::CHEAT_TYPE_FLY_HACK, NamreebAnticheat::CHEAT_TYPE_ROOT_MOVE, NamreebAnticheat::CHEAT_TYPE_SLOW_FALL, NamreebAnticheat::CHEAT_TYPE_WATER_WALK, Movement::MoveSpline::Finalized(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), Unit::HasAuraType(), Unit::hasUnitState(), MOVEFLAG_CAN_FLY, MOVEFLAG_FALLINGFAR, MOVEFLAG_FLYING, MOVEFLAG_HOVER, MOVEFLAG_LEVITATING, MOVEFLAG_ONTRANSPORT, MOVEFLAG_ROOT, MOVEFLAG_SAFE_FALL, MOVEFLAG_SWIMMING, MOVEFLAG_WALK_MODE, MOVEFLAG_WATERWALKING, Unit::movespline, NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), sAnticheatConfig, SEC_PLAYER, SMSG_FORCE_MOVE_ROOT, SMSG_MOVE_LAND_WALK, SMSG_MOVE_NORMAL_FALL, SPELL_AURA_FEATHER_FALL, SPELL_AURA_GHOST, SPELL_AURA_WATER_WALK, UNIT_STAT_ROOT, and UNIT_STAT_STUNNED.
Referenced by CheckTeleport().
Field Documentation
_ackHistory
nam::cyclic<Ack, 15> NamreebAnticheat::Movement::_ackHistory private
Definition at line 72 of file movement.hpp.
Referenced by DumpAcks(), and OrderAck().
_anticheat
SessionAnticheat* const NamreebAnticheat::Movement::_anticheat private
Definition at line 38 of file movement.hpp.
Referenced by CheckTeleport(), HandleAnticheatTests(), Movement(), OnExplore(), OnTransport(), OrderAck(), SendOrderInfo(), and VerifyMovementFlags().
_clientInitTime
uint32 NamreebAnticheat::Movement::_clientInitTime private
Definition at line 55 of file movement.hpp.
Referenced by HandleAnticheatTests(), HandleLeaveWorld(), and TimeSkipped().
_inKnockBack
bool NamreebAnticheat::Movement::_inKnockBack private
Definition at line 58 of file movement.hpp.
Referenced by HandleAnticheatTests(), IsInKnockBack(), and KnockBack().
_jumpInitialSpeed
float NamreebAnticheat::Movement::_jumpInitialSpeed private
Definition at line 57 of file movement.hpp.
Referenced by ExtrapolateMovement(), HandleAnticheatTests(), and KnockBack().
_justTeleported
bool NamreebAnticheat::Movement::_justTeleported private
Definition at line 47 of file movement.hpp.
Referenced by HandleAnticheatTests(), and HandleTeleport().
_me
Player* const NamreebAnticheat::Movement::_me private
Definition at line 39 of file movement.hpp.
Referenced by CheckTeleport(), ExtrapolateMovement(), GetLastMovementInfo(), GetMaxAllowedDist(), HandleAnticheatTests(), HandleEnterWorld(), HandleSpeedChangeAck(), IsTeleportAllowed(), KnockBack(), OnExplore(), OrderAck(), OrderSent(), TimeSkipped(), and VerifyMovementFlags().
_moveHistory
nam::cyclic<MovementHistory, 45> NamreebAnticheat::Movement::_moveHistory private
Definition at line 94 of file movement.hpp.
Referenced by DumpMovement(), and HandleAnticheatTests().
_orderHistory
nam::cyclic<Order, 15> NamreebAnticheat::Movement::_orderHistory private
Definition at line 65 of file movement.hpp.
Referenced by DumpOrders(), and OrderSent().
_orders
std::deque<PendingOrder> NamreebAnticheat::Movement::_orders private
Definition at line 50 of file movement.hpp.
Referenced by CheckExpiredOrders(), OrderAck(), OrderSent(), PendingOrderCount(), SendOrderInfo(), and VerifyMovementFlags().
_serverInitTime
uint32 NamreebAnticheat::Movement::_serverInitTime private
Definition at line 54 of file movement.hpp.
Referenced by HandleAnticheatTests(), and HandleLeaveWorld().
_timeSkipHistory
nam::cyclic<TimeSkip, 15> NamreebAnticheat::Movement::_timeSkipHistory private
Definition at line 80 of file movement.hpp.
Referenced by DumpTimeSkips(), and TimeSkipped().
_totalDistanceTraveled
float NamreebAnticheat::Movement::_totalDistanceTraveled private
Definition at line 41 of file movement.hpp.
Referenced by HandleAnticheatTests(), and TotalDistanceTraveled().
_wasMovingOther
bool NamreebAnticheat::Movement::_wasMovingOther private
Definition at line 44 of file movement.hpp.
Referenced by HandleAnticheatTests().
_worldChangeHistory
nam::cyclic<WorldChange, 15> NamreebAnticheat::Movement::_worldChangeHistory private
Definition at line 87 of file movement.hpp.
Referenced by DumpWorldChanges(), HandleEnterWorld(), and HandleLeaveWorld().
clientSpeeds
float NamreebAnticheat::Movement::clientSpeeds[MAX_MOVE_TYPE]
Definition at line 106 of file movement.hpp.
Referenced by ExtrapolateMovement(), GetMaxAllowedDist(), GetXYFlagBasedClientSpeed(), HandleAnticheatTests(), HandleEnterWorld(), HandleSpeedChangeAck(), and Movement().
overSpeedDistanceTick
float NamreebAnticheat::Movement::overSpeedDistanceTick
Definition at line 109 of file movement.hpp.
Referenced by HandleAnticheatTests().
overSpeedDistanceTotal
float NamreebAnticheat::Movement::overSpeedDistanceTotal
Definition at line 112 of file movement.hpp.
Referenced by HandleAnticheatTests().
The documentation for this class was generated from the following files:
movement.hpp
movement.cpp