CMaNGOS_WoTLK: nam::priority< T, P, N > Class Template Reference
nam::priority< T, P, N > Class Template Reference
#include <priority.hpp>
Public Types
using value_type = T
using reference = T &
using const_reference = const T &
using iterator = PriorityIterator< priority, false >
using const_iterator = PriorityIterator< priority, true >
Public Member Functions
priority ()
template<class... Args>
void emplace (P prio, Args &&... args) noexcept
void insert (P prio, const_reference elem) noexcept
void clear () noexcept
std::size_t size () const noexcept
bool empty () const noexcept
reference operator[] (std::size_t n)
const_reference operator[] (std::size_t n) const
iterator begin () noexcept
const_iterator begin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
Private Member Functions
std::size_t find_idx (P prio) const noexcept
void shift (std::size_t idx) noexcept
Private Attributes
std::size_t _curr
std::array< std::pair< P, T >, N > _raw
Detailed Description
template<typename T, typename P, std::size_t N>
class nam::priority< T, P, N >
Definition at line 86 of file priority.hpp.
Member Typedef Documentation
const_iterator
template<typename T , typename P , std::size_t N> using nam::priority< T, P, N >::const_iterator = PriorityIterator<priority, true>
Definition at line 113 of file priority.hpp.
const_reference
template<typename T , typename P , std::size_t N> using nam::priority< T, P, N >::const_reference = const T&
Definition at line 111 of file priority.hpp.
iterator
template<typename T , typename P , std::size_t N> using nam::priority< T, P, N >::iterator = PriorityIterator<priority, false>
Definition at line 112 of file priority.hpp.
reference
template<typename T , typename P , std::size_t N> using nam::priority< T, P, N >::reference = T&
Definition at line 110 of file priority.hpp.
value_type
template<typename T , typename P , std::size_t N> using nam::priority< T, P, N >::value_type = T
Definition at line 109 of file priority.hpp.
Constructor & Destructor Documentation
priority()
template<typename T , typename P , std::size_t N> nam::priority< T, P, N >::priority () inline
Definition at line 115 of file priority.hpp.
Member Function Documentation
begin() [1/2]
template<typename T , typename P , std::size_t N> const_iterator nam::priority< T, P, N >::begin () const inline noexcept
Definition at line 160 of file priority.hpp.
begin() [2/2]
template<typename T , typename P , std::size_t N> iterator nam::priority< T, P, N >::begin () inline noexcept
Definition at line 155 of file priority.hpp.
clear()
template<typename T , typename P , std::size_t N> void nam::priority< T, P, N >::clear () inline noexcept
Definition at line 137 of file priority.hpp.
References nam::priority< T, P, N >::_curr.
emplace()
template<typename T , typename P , std::size_t N> template<class... Args> void nam::priority< T, P, N >::emplace (P prio, Args &&... args) inline noexcept
Definition at line 118 of file priority.hpp.
References nam::priority< T, P, N >::_curr, nam::priority< T, P, N >::_raw, nam::priority< T, P, N >::find_idx(), and nam::priority< T, P, N >::shift().
Referenced by nam::priority< T, P, N >::insert().
empty()
template<typename T , typename P , std::size_t N> bool nam::priority< T, P, N >::empty () const inline noexcept
Definition at line 143 of file priority.hpp.
References nam::priority< T, P, N >::_curr.
end() [1/2]
template<typename T , typename P , std::size_t N> const_iterator nam::priority< T, P, N >::end () const inline noexcept
Definition at line 170 of file priority.hpp.
References nam::priority< T, P, N >::_curr.
end() [2/2]
template<typename T , typename P , std::size_t N> iterator nam::priority< T, P, N >::end () inline noexcept
Definition at line 165 of file priority.hpp.
References nam::priority< T, P, N >::_curr.
find_idx()
template<typename T , typename P , std::size_t N> std::size_t nam::priority< T, P, N >::find_idx (P prio) const inline private noexcept
Definition at line 92 of file priority.hpp.
References nam::priority< T, P, N >::_curr, and nam::priority< T, P, N >::_raw.
Referenced by nam::priority< T, P, N >::emplace().
insert()
template<typename T , typename P , std::size_t N> void nam::priority< T, P, N >::insert (P prio, const_reference elem) inline noexcept
Definition at line 132 of file priority.hpp.
References nam::priority< T, P, N >::emplace().
Referenced by NamreebAnticheat::Antispam::Analyze().
operator[]() [1/2]
template<typename T , typename P , std::size_t N> reference nam::priority< T, P, N >::operator[] (std::size_t n) inline
Definition at line 145 of file priority.hpp.
References nam::priority< T, P, N >::_raw.
operator[]() [2/2]
template<typename T , typename P , std::size_t N> const_reference nam::priority< T, P, N >::operator[] (std::size_t n) const inline
Definition at line 150 of file priority.hpp.
References nam::priority< T, P, N >::_raw.
shift()
template<typename T , typename P , std::size_t N> void nam::priority< T, P, N >::shift (std::size_t idx) inline private noexcept
Definition at line 102 of file priority.hpp.
References nam::priority< T, P, N >::_raw.
Referenced by nam::priority< T, P, N >::emplace().
size()
template<typename T , typename P , std::size_t N> std::size_t nam::priority< T, P, N >::size () const inline noexcept
Definition at line 142 of file priority.hpp.
References nam::priority< T, P, N >::_curr.
Field Documentation
_curr
template<typename T , typename P , std::size_t N> std::size_t nam::priority< T, P, N >::_curr private
Definition at line 89 of file priority.hpp.
Referenced by nam::priority< T, P, N >::clear(), nam::priority< T, P, N >::emplace(), nam::priority< T, P, N >::empty(), nam::priority< T, P, N >::end(), nam::priority< T, P, N >::find_idx(), and nam::priority< T, P, N >::size().
_raw
template<typename T , typename P , std::size_t N> std::array<std::pair<P, T>, N> nam::priority< T, P, N >::_raw private
Definition at line 90 of file priority.hpp.
Referenced by nam::priority< T, P, N >::emplace(), nam::priority< T, P, N >::find_idx(), nam::priority< T, P, N >::operator[](), and nam::priority< T, P, N >::shift().
The documentation for this class was generated from the following file:
priority.hpp