CMaNGOS_WoTLK: StayMovementGenerator Class Reference
StayMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
StayMovementGenerator (float x, float y, float z, float o=0)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
bool Update (Unit &unit, const uint32 &diff) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from PointMovementGenerator
PointMovementGenerator (uint32 id, float x, float y, float z, float o, bool generatePath, uint32 forcedMovement, float speed=0.f, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
PointMovementGenerator (uint32 id, float x, float y, float z, bool generatePath, uint32 forcedMovement, float speed=0.f)
void Reset (Unit &unit) override
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
void MovementInform (Unit &) override
Protected Member Functions inherited from PointMovementGenerator
virtual void Move (Unit &unit)
Private Attributes
bool m_arrived
Additional Inherited Members
Protected Attributes inherited from PointMovementGenerator
float m_x
float m_y
float m_z
float m_o
float m_speed
bool m_generatePath
uint32 m_forcedMovement
Detailed Description
Definition at line 81 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
StayMovementGenerator()
StayMovementGenerator::StayMovementGenerator (float x, float y, float z, float o = 0) inline
Definition at line 84 of file PointMovementGenerator.h.
Member Function Documentation
Finalize()
void StayMovementGenerator::Finalize (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 194 of file PointMovementGenerator.cpp.
References Unit::clearUnitState(), PointMovementGenerator::Finalize(), and UNIT_STAT_STAY.
GetMovementGeneratorType()
MovementGeneratorType StayMovementGenerator::GetMovementGeneratorType () const inline override virtual
Reimplemented from PointMovementGenerator.
Definition at line 92 of file PointMovementGenerator.h.
References STAY_MOTION_TYPE.
Initialize()
void StayMovementGenerator::Initialize (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 188 of file PointMovementGenerator.cpp.
References Unit::addUnitState(), PointMovementGenerator::Initialize(), and UNIT_STAT_STAY.
Interrupt()
void StayMovementGenerator::Interrupt (Unit & unit) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 200 of file PointMovementGenerator.cpp.
References PointMovementGenerator::Interrupt(), and m_arrived.
MovementInform()
void StayMovementGenerator::MovementInform (Unit &) inline override protected virtual
Reimplemented from PointMovementGenerator.
Definition at line 95 of file PointMovementGenerator.h.
Update()
bool StayMovementGenerator::Update (Unit & unit, const uint32 & diff) override virtual
Reimplemented from PointMovementGenerator.
Definition at line 206 of file PointMovementGenerator.cpp.
References Unit::clearUnitState(), m_arrived, UNIT_STAT_ROAMING_MOVE, and PointMovementGenerator::Update().
Field Documentation
m_arrived
bool StayMovementGenerator::m_arrived private
Definition at line 98 of file PointMovementGenerator.h.
Referenced by Interrupt(), and Update().
The documentation for this class was generated from the following files:
PointMovementGenerator.h
PointMovementGenerator.cpp