CMaNGOS_WoTLK: BattleGroundMap Class Reference
BattleGroundMap Class Reference
#include <Map.h>
Public Member Functions
BattleGroundMap (uint32 id, time_t, uint32 InstanceId, uint8 spawnMode)
~BattleGroundMap ()
virtual void Initialize (bool) override
void Update (const uint32 &) override
bool Add (Player *) override
void Remove (Player *, bool) override
bool CanEnter (Player *player) override
void SetUnload ()
void UnloadAll (bool pForce) override
virtual void InitVisibilityDistance () override
BattleGround * GetBG () const
void SetBG (BattleGround *bg)
BattleGroundPersistentState * GetPersistanceState () const
Public Member Functions inherited from Map
virtual ~Map ()
bool CanUnload (uint32 diff)
template<class T >
void Add (T *)
template<class T >
void Remove (T *, bool)
void VisitNearbyCellsOf (WorldObject *obj, TypeContainerVisitor< MaNGOS::ObjectUpdater, GridTypeMapContainer > &gridVisitor, TypeContainerVisitor< MaNGOS::ObjectUpdater, WorldTypeMapContainer > &worldVisitor)
void MessageBroadcast (Player const *, WorldPacket const &, bool to_self)
void MessageBroadcast (WorldObject const *, WorldPacket const &)
void MessageDistBroadcast (Player const *, WorldPacket const &, float dist, bool to_self, bool own_team_only=false)
void MessageDistBroadcast (WorldObject const *, WorldPacket const &, float dist)
void MessageMapBroadcast (WorldObject const *obj, WorldPacket const &msg)
void MessageMapBroadcastZone (WorldObject const *obj, WorldPacket const &msg, uint32 zoneId)
void MessageMapBroadcastArea (WorldObject const *obj, WorldPacket const &msg, uint32 areaId)
void ExecuteDistWorker (WorldObject const *obj, float dist, std::function< void(Player *)> const &worker)
void ExecuteMapWorker (std::function< void(Player *)> const &worker)
void ExecuteMapWorkerZone (uint32 zoneId, std::function< void(Player *)> const &worker)
void ExecuteMapWorkerArea (uint32 areaId, std::function< void(Player *)> const &worker)
float GetVisibilityDistance () const
void PlayerRelocation (Player *, float x, float y, float z, float orientation)
void CreatureRelocation (Creature *creature, float x, float y, float z, float ang)
void GameObjectRelocation (GameObject *go, float x, float y, float z, float orientation, bool respawnRelocationOnFail=true)
void DynamicObjectRelocation (DynamicObject *dynObj, float x, float y, float z, float orientation)
template<class T , class CONTAINER >
void Visit (const Cell &cell, TypeContainerVisitor< T, CONTAINER > &visitor)
bool IsRemovalGrid (float x, float y) const
bool IsLoaded (float x, float y) const
bool GetUnloadLock (const GridPair &p) const
void SetUnloadLock (const GridPair &p, bool on)
void ForceLoadGrid (float x, float y)
bool UnloadGrid (const uint32 &x, const uint32 &y, bool pForce)
void ResetGridExpiry (NGridType &grid, float factor=1) const
time_t GetGridExpiry (void) const
uint32 GetId (void) const
virtual void RemoveAllObjectsInRemoveList ()
bool CreatureRespawnRelocation (Creature *c)
uint32 GetInstanceId () const
const char * GetMapName () const
uint8 GetSpawnMode () const
Difficulty GetDifficulty () const
bool IsRegularDifficulty () const
uint32 GetMaxPlayers () const
uint32 GetMaxResetDelay () const
MapDifficultyEntry const * GetMapDifficulty () const
void ChangeMapDifficulty (Difficulty difficulty)
void SetNewDifficultyCooldown (TimePoint const &newCooldown)
TimePoint const & GetNewDifficultyCooldown () const
MapEntry const * GetEntry () const
bool Instanceable () const
bool IsDungeon () const
bool IsRaid () const
bool IsNonRaidDungeon () const
bool IsRaidOrHeroicDungeon () const
bool IsHeroic () const
bool IsBattleGround () const
bool IsBattleArena () const
bool IsBattleGroundOrArena () const
bool IsContinent () const
bool IsMountAllowed () const
bool IsDynguidForced () const
MapPersistentState * GetPersistentState () const
void AddObjectToRemoveList (WorldObject *obj)
void UpdateObjectVisibility (WorldObject *obj, Cell cell, const CellPair &cellpair)
void resetMarkedCells ()
bool isCellMarked (uint32 pCellId) const
void markCell (uint32 pCellId)
bool HavePlayers () const
uint32 GetPlayersCountExceptGMs () const
bool ActiveObjectsNearGrid (uint32 x, uint32 y) const
void SendToPlayers (WorldPacket const &data) const
Send a Packet to all players on a map.
bool SendToPlayersInZone (WorldPacket const &data, uint32 zoneId) const
Send a Packet to all players in a zone. Return false if no player found.
PlayerList const & GetPlayers () const
bool ScriptsStart (ScriptMapType scriptType, uint32 id, Object *source, Object *target, ScriptExecutionParam execParams=SCRIPT_EXEC_PARAM_NONE)
Put scripts in the execution queue.
void ScriptCommandStart (ScriptInfo const &script, uint32 delay, Object *source, Object *target)
void AddToActive (WorldObject *obj)
void RemoveFromActive (WorldObject *obj)
void AddToOnEventNotified (WorldObject *obj)
void RemoveFromOnEventNotified (WorldObject *obj)
void OnEventHappened (uint16 event_id, bool activate, bool resume)
Player * GetPlayer (ObjectGuid guid)
Function return player that in world at CURRENT map.
Creature * GetCreature (ObjectGuid guid)
Function return creature (non-pet and then most summoned by spell creatures) that in world at CURRENT map.
Creature * GetCreatureByEntry (uint32 entry)
Pet * GetPet (ObjectGuid guid)
Function return pet that in world at CURRENT map.
Creature * GetAnyTypeCreature (ObjectGuid guid)
Function return non-player unit object that in world at CURRENT map, so creature, or pet, or vehicle.
GameObject * GetGameObject (ObjectGuid guid)
Function return gameobject that in world at CURRENT map.
DynamicObject * GetDynamicObject (ObjectGuid guid)
Function return dynamic object that in world at CURRENT map.
Corpse * GetCorpse (ObjectGuid guid) const
Function return corpse that at CURRENT map.
Unit * GetUnit (ObjectGuid guid)
Function return unit in world at CURRENT map.
WorldObject * GetWorldObject (ObjectGuid guid)
Function return world object in world at CURRENT map, so any except transports.
Creature * GetCreature (uint32 dbguid) const
GameObject * GetGameObject (uint32 dbguid) const
std::vector< WorldObject * > const * GetWorldObjects (std::string stringId) const
std::vector< Creature * > const * GetCreatures (std::string stringId) const
std::vector< GameObject * > const * GetGameObjects (std::string stringId) const
std::vector< WorldObject * > const * GetWorldObjects (uint32 stringId) const
std::vector< Creature * > const * GetCreatures (uint32 stringId) const
std::vector< GameObject * > const * GetGameObjects (uint32 stringId) const
void AddDbGuidObject (WorldObject *obj)
void RemoveDbGuidObject (WorldObject *obj)
void AddStringIdObject (uint32 stringId, WorldObject *obj)
void RemoveStringIdObject (uint32 stringId, WorldObject *obj)
MapStoredObjectTypesContainer & GetObjectsStore ()
std::map< uint32, uint32 > & GetTempCreatures ()
std::map< uint32, uint32 > & GetTempPets ()
void AddUpdateObject (Object *obj)
void RemoveUpdateObject (Object *obj)
uint32 GenerateLocalLowGuid (HighGuid guidhigh)
const TerrainInfo * GetTerrain () const
void CreateInstanceData (bool load)
InstanceData * GetInstanceData () const
uint32 GetScriptId () const
void MonsterYellToMap (ObjectGuid guid, int32 textId, ChatMsg chatMsg, Language language, Unit const *target) const
Function simulates yell of creature.
void MonsterYellToMap (CreatureInfo const *cinfo, int32 textId, ChatMsg chatMsg, Language language, Unit const *target, uint32 senderLowGuid=0) const
Function simulates yell of creature.
void PlayDirectSoundToMap (uint32 soundId, uint32 zoneId=0) const
Function to play sound to all players in map.
float GetHeight (uint32 phasemask, float x, float y, float z, bool swim=false) const
bool GetHeightInRange (uint32 phasemask, float x, float y, float &z, float maxSearchDist=4.0f) const
bool IsInLineOfSight (float srcX, float srcY, float srcZ, float destX, float destY, float destZ, uint32 phasemask, bool ignoreM2Model) const
Function to check if a point is in line of sight from an other point.
bool GetHitPosition (float srcX, float srcY, float srcZ, float &destX, float &destY, float &destZ, uint32 phasemask, float modifyDist) const
get the hit position and return true if we hit something (in this case the dest position will hold the hit-position) otherwise the result pos will be the dest pos
void InsertGameObjectModel (const GameObjectModel &mdl)
void RemoveGameObjectModel (const GameObjectModel &mdl)
bool ContainsGameObjectModel (const GameObjectModel &mdl) const
CreatureLinkingHolder * GetCreatureLinkingHolder ()
void TeleportAllPlayersTo (TeleportLocation loc)
WeatherSystem * GetWeatherSystem () const
void SetWeather (uint32 zoneId, WeatherType type, float grade, bool permanently)
Set the weather in a zone on this map.
bool GetReachableRandomPosition (Unit *unit, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetReachableRandomPointOnGround (uint32 phaseMask, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetRandomPointInTheAir (uint32 phaseMask, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetRandomPointUnderWater (uint32 phaseMask, float &x, float &y, float &z, float radius, GridMapLiquidData &liquid_status, bool randomRange=true) const
uint32 SpawnedCountForEntry (uint32 entry)
void AddToSpawnCount (const ObjectGuid &guid)
void RemoveFromSpawnCount (const ObjectGuid &guid)
uint32 GetCurrentMSTime () const
TimePoint GetCurrentClockTime () const
uint32 GetCurrentDiff () const
time_t GetCurrentTime_t () const
tm GetCurrentTime_tm () const
void SetZoneMusic (uint32 zoneId, uint32 areaId, uint32 musicId)
Function to set the zone music info.
void SetZoneWeather (uint32 zoneId, uint32 areaId, uint32 weatherId, float weatherGrade)
Function to set the zone weather info.
void SetZoneOverrideLight (uint32 zoneId, uint32 areaId, uint32 lightId, uint32 fadeInTime)
Function to set the zone light override info.
void SendZoneDynamicInfo (Player *player, bool zoneUpdated, bool areaUpdated) const
Function to set the zone dynamic info.
void CreatePlayerOnClient (Player *player)
uint32 GetLoadedGridsCount ()
Messager< Map > & GetMessager ()
GenericTransport * GetTransport (ObjectGuid guid)
TransportSet const & GetTransports ()
GraveyardManager & GetGraveyardManager ()
void AddTransport (Transport *transport)
void RemoveTransport (Transport *transport)
bool CanSpawn (TypeID typeId, uint32 dbGuid)
SpawnManager & GetSpawnManager ()
MapDataContainer & GetMapDataContainer ()
MapDataContainer const & GetMapDataContainer () const
WorldStateVariableManager & GetVariableManager ()
WorldStateVariableManager const & GetVariableManager () const
void ChangeGOPathfinding (uint32 entry, uint32 displayId, bool apply)
void SetNavTile (uint32 tileX, uint32 tileY, uint32 tileNumber)
void AwardLFGRewards (uint32 dungeonId)
template<>
void AddToGrid (GameObject *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Player *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Corpse *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Creature *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Player *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Corpse *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Creature *obj, NGridType *grid, Cell const &cell)
Public Member Functions inherited from GridRefManager< NGridType >
GridReference< NGridType > * getFirst ()
GridReference< NGridType > * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefManager< TO, FROM >
RefManager ()
virtual ~RefManager ()
Reference< TO, FROM > * getFirst ()
Reference< TO, FROM > const * getFirst () const
Reference< TO, FROM > * getLast ()
Reference< TO, FROM > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
const_iterator begin () const
const_iterator end () const
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Member Functions
MapPersistentState * GetPersistentState () const
Private Attributes
BattleGround * m_bg
Additional Inherited Members
Public Types inherited from Map
enum ScriptExecutionParam { SCRIPT_EXEC_PARAM_NONE = 0x00 , SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE = 0x01 , SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET = 0x02 , SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE_TARGET = 0x03 }
typedef MapRefManager PlayerList
typedef TypeUnorderedMapContainer< AllMapStoredObjectTypes, ObjectGuid > MapStoredObjectTypesContainer
typedef std::set< Transport * > TransportSet
Public Types inherited from GridRefManager< NGridType >
typedef LinkedListHead::Iterator< GridReference< NGridType > > iterator
Public Types inherited from RefManager< TO, FROM >
typedef LinkedListHead::Iterator< Reference< TO, FROM > > iterator
typedef LinkedListHead::Iterator< Reference< TO, FROM > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Static Public Member Functions inherited from Map
static void DeleteFromWorld (Player *pl)
Data Fields inherited from Map
std::set< ObjectGuid > m_objRemoveList
Protected Types inherited from Map
typedef WorldObjectSet ActiveNonPlayers
Protected Member Functions inherited from Map
Map (uint32 id, time_t, uint32 InstanceId, uint8 SpawnMode)
Protected Attributes inherited from Map
MapEntry const * i_mapEntry
uint8 i_spawnMode
uint32 i_id
uint32 i_InstanceId
uint32 m_unloadTimer
float m_VisibleDistance
MapPersistentState * m_persistentState
MapRefManager m_mapRefManager
MapRefManager::iterator m_mapRefIter
ActiveNonPlayers m_activeNonPlayers
ActiveNonPlayers::iterator m_activeNonPlayersIter
MapStoredObjectTypesContainer m_objectsStore
std::map< uint32, uint32 > m_tempCreatures
std::map< uint32, uint32 > m_tempPets
std::map< std::pair< HighGuid, uint32 >, std::vector< WorldObject * > > m_dbGuidObjects
WorldObjectSet m_onEventNotifiedObjects
WorldObjectSet::iterator m_onEventNotifiedIter
Messager< Map > m_messager
GraveyardManager m_graveyardManager
Detailed Description
Definition at line 605 of file Map.h.
Constructor & Destructor Documentation
BattleGroundMap()
BattleGroundMap::BattleGroundMap (uint32 id, time_t expiry, uint32 InstanceId, uint8 spawnMode)
Definition at line 2005 of file Map.cpp.
~BattleGroundMap()
BattleGroundMap::~BattleGroundMap ()
Definition at line 2010 of file Map.cpp.
Member Function Documentation
Add()
bool BattleGroundMap::Add (Player * player) override virtual
Reimplemented from Map.
Definition at line 2049 of file Map.cpp.
References Map::Add(), CanEnter(), and Player::m_InstanceValid.
CanEnter()
bool BattleGroundMap::CanEnter (Player * player) override virtual
Reimplemented from Map.
Definition at line 2037 of file Map.cpp.
References Map::CanEnter(), Player::GetBattleGroundId(), and Map::GetInstanceId().
Referenced by Add().
GetBG()
BattleGround* BattleGroundMap::GetBG () const inline
Definition at line 622 of file Map.h.
References m_bg.
Referenced by StartEvents_Event(), and Update().
GetPersistanceState()
BattleGroundPersistentState * BattleGroundMap::GetPersistanceState () const
Definition at line 2026 of file Map.cpp.
References Map::GetPersistentState().
GetPersistentState()
MapPersistentState* Map::GetPersistentState inline private
Definition at line 240 of file Map.h.
Initialize()
void BattleGroundMap::Initialize (bool) override virtual
Reimplemented from Map.
Definition at line 2014 of file Map.cpp.
References Map::Initialize().
Referenced by MapManager::CreateBattleGroundMap().
InitVisibilityDistance()
void BattleGroundMap::InitVisibilityDistance () override virtual
Reimplemented from Map.
Definition at line 2031 of file Map.cpp.
References World::GetMaxVisibleDistanceInBGArenas(), and Map::m_VisibleDistance.
Remove()
void BattleGroundMap::Remove (Player * player, bool remove) override virtual
Reimplemented from Map.
Definition at line 2060 of file Map.cpp.
References DETAIL_FILTER_LOG, Map::GetInstanceId(), Map::GetMapName(), WorldObject::GetName(), LOG_FILTER_PLAYER_MOVES, and Map::Remove().
SetBG()
void BattleGroundMap::SetBG (BattleGround * bg) inline
Definition at line 623 of file Map.h.
References m_bg.
Referenced by MapManager::CreateBattleGroundMap().
SetUnload()
void BattleGroundMap::SetUnload ()
Definition at line 2066 of file Map.cpp.
References Map::m_unloadTimer, and MIN_UNLOAD_DELAY.
Referenced by BattleGround::~BattleGround().
UnloadAll()
void BattleGroundMap::UnloadAll (bool pForce) override virtual
Reimplemented from Map.
Definition at line 2071 of file Map.cpp.
References TELEPORT_LOCATION_BG_ENTRY_POINT, Map::TeleportAllPlayersTo(), and Map::UnloadAll().
Update()
void BattleGroundMap::Update (const uint32 & diff) override virtual
Reimplemented from Map.
Definition at line 2019 of file Map.cpp.
References GetBG(), Map::Update(), and BattleGround::Update().
Field Documentation
m_bg
BattleGround* BattleGroundMap::m_bg private
Definition at line 629 of file Map.h.
Referenced by GetBG(), and SetBG().
The documentation for this class was generated from the following files:
Map.h
Map.cpp