CMaNGOS_WoTLK: ChaseMovementGenerator Class Reference
ChaseMovementGenerator Class Reference
#include <TargetedMovementGenerator.h>
Public Member Functions
ChaseMovementGenerator (Unit &target, float offset, float angle, bool moveFurther=true, bool walk=false, bool combat=true)
~ChaseMovementGenerator ()
MovementGeneratorType GetMovementGeneratorType () const override
void Initialize (Unit &) override
void Finalize (Unit &) override
void Interrupt (Unit &) override
void Reset (Unit &) override
void SetOffsetAndAngle (float offset, float angle, bool moveFurther)
void DistanceYourself (Unit &owner, float distance)
void FanOut (Unit &owner)
bool EnableWalking () const
bool _lostTarget (Unit &u) const
bool RemoveOnInvalid () const override
void _reachTarget (Unit &)
bool GetResetPosition (Unit &, float &, float &, float &, float &) const override
void HandleMovementFailure (Unit &owner) override
ChaseMovementMode GetCurrentMode () const
virtual bool IsReachable () const override
virtual bool IsRemovedOnExpire () const override
std::pair< std::string, std::string > GetPrintout () const
void AddDelay ()
Public Member Functions inherited from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >
bool Update (Unit &, const uint32 &)
Unit * GetCurrentTarget () const override
float GetOffset () const
float GetAngle () const
virtual void UnitSpeedChanged () override
Public Member Functions inherited from MovementGeneratorMedium< T, D >
bool Update (Unit &u, const uint32 &time_diff) override
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Initialize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Finalize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Interrupt (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Reset (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool Update (U &u, const uint32 &time_diff)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
bool IsActive (Unit &u)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit &target)
void stopFollowing ()
void SetNewTarget (Unit &target)
Protected Member Functions
float GetDynamicTargetDistance (Unit &owner, bool forRangeCheck) const override
void HandleTargetedMovement (Unit &owner, const uint32 &time_diff) override
void HandleFinalizedMovement (Unit &owner) override
bool RequiresNewPosition (Unit &owner, Position pos) const override
bool _hasUnitStateNotMove (Unit &u) override
void _clearUnitStateMove (Unit &u) override
void _addUnitStateMove (Unit &u) override
Protected Member Functions inherited from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >
TargetedMovementGeneratorMedium (Unit &target, float offset, float angle)
~TargetedMovementGeneratorMedium ()
virtual bool RequiresNewPosition (Unit &owner, Position pos) const
virtual bool ShouldFaceTarget () const
Private Member Functions
virtual bool _getLocation (Unit &owner, float &x, float &y, float &z) const
virtual void _setLocation (Unit &owner)
bool IsReachablePositionToTarget (Unit &owner, float x, float y, float z, Unit &target)
bool DispatchSplineToPosition (Unit &owner, float x, float y, float z, bool walk, bool cutPath, bool target=false, bool checkReachable=false)
void CutPath (Unit &owner, PointsArray &path)
void Backpedal (Unit &owner)
Private Attributes
bool m_moveFurther
bool m_walk
bool m_combat
bool m_reachable
bool m_fanningEnabled
uint32 m_closenessAndFanningTimer
bool m_closenessExpired
ChaseMovementMode m_currentMode
GuidVector m_spawns
Additional Inherited Members
Protected Attributes inherited from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >
ShortTimeTracker i_recheckDistance
float i_offset
float i_angle
G3D::Vector3 i_lastTargetPos
bool i_speedChanged
bool i_targetReached
bool i_faceTarget
PathFinder * i_path
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
Definition at line 108 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
ChaseMovementGenerator()
ChaseMovementGenerator::ChaseMovementGenerator (Unit & target, float offset, float angle, bool moveFurther = true, bool walk = false, bool combat = true) inline
Definition at line 113 of file TargetedMovementGenerator.h.
~ChaseMovementGenerator()
ChaseMovementGenerator::~ChaseMovementGenerator () inline
Definition at line 116 of file TargetedMovementGenerator.h.
Member Function Documentation
_addUnitStateMove()
void ChaseMovementGenerator::_addUnitStateMove (Unit & u) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 119 of file TargetedMovementGenerator.cpp.
References Unit::addUnitState(), and UNIT_STAT_CHASE_MOVE.
Referenced by DispatchSplineToPosition().
_clearUnitStateMove()
void ChaseMovementGenerator::_clearUnitStateMove (Unit & u) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 118 of file TargetedMovementGenerator.cpp.
References Unit::clearUnitState(), and UNIT_STAT_CHASE_MOVE.
Referenced by HandleFinalizedMovement(), and HandleMovementFailure().
_getLocation()
bool ChaseMovementGenerator::_getLocation (Unit & owner, float & x, float & y, float & z) const private virtual
Definition at line 629 of file TargetedMovementGenerator.cpp.
References GetDynamicTargetDistance(), Unit::GetObjectBoundingRadius(), WorldObject::GetPosition(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_angle, TargetedMovementGeneratorBase::i_target, and Reference< TO, FROM >::isValid().
Referenced by _setLocation(), and HandleTargetedMovement().
_hasUnitStateNotMove()
bool ChaseMovementGenerator::_hasUnitStateNotMove (Unit & u) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 117 of file TargetedMovementGenerator.cpp.
References Unit::hasUnitState(), UNIT_STAT_NO_COMBAT_MOVEMENT, and UNIT_STAT_NOT_MOVE.
Referenced by _setLocation().
_lostTarget()
bool ChaseMovementGenerator::_lostTarget (Unit & u) const
Definition at line 121 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::GetCurrentTarget(), Unit::GetVictim(), and m_combat.
_reachTarget()
void ChaseMovementGenerator::_reachTarget (Unit &)
Definition at line 126 of file TargetedMovementGenerator.cpp.
Referenced by HandleFinalizedMovement().
_setLocation()
void ChaseMovementGenerator::_setLocation (Unit & owner) private virtual
Definition at line 649 of file TargetedMovementGenerator.cpp.
References _getLocation(), _hasUnitStateNotMove(), DispatchSplineToPosition(), EnableWalking(), WorldObject::GetPosition(), WorldObject::GetTransport(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, Reference< TO, FROM >::isValid(), RequiresNewPosition(), Position::x, Position::y, and Position::z.
Referenced by Initialize().
AddDelay()
void ChaseMovementGenerator::AddDelay ()
Definition at line 198 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_recheckDistance, and ShortTimeTracker::Reset().
Backpedal()
void ChaseMovementGenerator::Backpedal (Unit & owner) private
Definition at line 391 of file TargetedMovementGenerator.cpp.
References Unit::AI(), CHASE_CLOSENESS_TIMER, CHASE_MODE_BACKPEDAL, DispatchSplineToPosition(), DIST_CALC_NONE, FanOut(), UnitAI::GetCombatScriptStatus(), Unit::GetObjectBoundingRadius(), WorldObject::GetOrientation(), WorldObject::GetPosition(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, m_closenessAndFanningTimer, m_closenessExpired, m_currentMode, M_PI_F, and MapManager::NormalizeOrientation().
Referenced by HandleTargetedMovement().
CutPath()
void ChaseMovementGenerator::CutPath (Unit & owner, PointsArray & path) private
Definition at line 579 of file TargetedMovementGenerator.cpp.
References CHASE_DEFAULT_RANGE_FACTOR, CHASE_MOVE_CLOSER_FACTOR, DIST_CALC_NONE, Unit::GetCollisionHeight(), WorldObject::GetMap(), WorldObject::GetPhaseMask(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, TargetedMovementGeneratorBase::i_target, IGNORE_M2, and Map::IsInLineOfSight().
Referenced by DispatchSplineToPosition().
DispatchSplineToPosition()
bool ChaseMovementGenerator::DispatchSplineToPosition (Unit & owner, float x, float y, float z, bool walk, bool cutPath, bool target = false, bool checkReachable = false) private
Definition at line 472 of file TargetedMovementGenerator.cpp.
References _addUnitStateMove(), PathFinder::calculate(), CONFIG_BOOL_PATH_FIND_NORMALIZE_Z, CutPath(), Movement::MoveSpline::Finalized(), Map::GetCreature(), Unit::GetHealthPercent(), WorldObject::GetMap(), PathFinder::getPath(), PathFinder::getPathType(), WorldObject::GetPosition(), WorldObject::GetPositionZ(), Reference< TO, FROM >::getTarget(), WorldObject::GetTransport(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_path, TargetedMovementGeneratorBase::i_target, Unit::IsDebuggingMovement(), Unit::IsInWater(), IsReachablePositionToTarget(), Unit::IsSlowedInCombat(), WorldObject::IsWithinDist3d(), WorldObject::IsWithinLOS(), Movement::MoveSplineInit::Launch(), m_reachable, m_spawns, Movement::MoveSplineInit::MovebyPath(), Unit::movespline, Position::o, PATHFIND_INCOMPLETE, PATHFIND_NOPATH, Movement::MoveSplineInit::SetCombatSlowed(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetWalk(), sLog, WorldObject::SummonCreature(), sWorld, TEMPSPAWN_TIMED_DESPAWN, Unit::UpdateSplinePosition(), VISIBILITY_ON, Position::x, Position::y, and Position::z.
Referenced by _setLocation(), Backpedal(), DistanceYourself(), FanOut(), and HandleTargetedMovement().
DistanceYourself()
void ChaseMovementGenerator::DistanceYourself (Unit & owner, float distance)
Definition at line 378 of file TargetedMovementGenerator.cpp.
References Unit::AI(), CHASE_MODE_DISTANCING, DispatchSplineToPosition(), UnitAI::DistancingStarted(), Unit::GetObjectBoundingRadius(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, and m_currentMode.
EnableWalking()
bool ChaseMovementGenerator::EnableWalking () const inline
Definition at line 128 of file TargetedMovementGenerator.h.
References m_walk.
Referenced by _setLocation(), and HandleTargetedMovement().
FanOut()
void ChaseMovementGenerator::FanOut (Unit & owner)
Definition at line 427 of file TargetedMovementGenerator.cpp.
References CHASE_MODE_FANNING, DispatchSplineToPosition(), DIST_CALC_NONE, fanAngleMax, fanAngleMin, fanningRadius, frand(), Unit::GetObjectBoundingRadius(), WorldObject::GetOrientation(), Unit::GetVictim(), Object::HasFlag(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, irand(), WorldObject::IsBoarded(), Unit::IsMoving(), m_closenessAndFanningTimer, m_currentMode, m_fanningEnabled, M_PI_F, MapManager::NormalizeOrientation(), UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, and Cell::VisitAllObjects().
Referenced by Backpedal().
Finalize()
void ChaseMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 146 of file TargetedMovementGenerator.cpp.
References Unit::AI(), CHASE_MODE_DISTANCING, Unit::clearUnitState(), UnitAI::DistancingEnded(), m_currentMode, UNIT_STAT_CHASE, and UNIT_STAT_CHASE_MOVE.
GetCurrentMode()
ChaseMovementMode ChaseMovementGenerator::GetCurrentMode () const inline
Definition at line 135 of file TargetedMovementGenerator.h.
References m_currentMode.
Referenced by ChatHandler::HandleMovegensCommand().
GetDynamicTargetDistance()
float ChaseMovementGenerator::GetDynamicTargetDistance (Unit & owner, bool forRangeCheck) const override protected virtual
Reimplemented from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 203 of file TargetedMovementGenerator.cpp.
References CHASE_DEFAULT_RANGE_FACTOR, CHASE_RECHASE_RANGE_FACTOR, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, TargetedMovementGeneratorBase::i_target, and m_moveFurther.
Referenced by _getLocation(), and RequiresNewPosition().
GetMovementGeneratorType()
MovementGeneratorType ChaseMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Definition at line 118 of file TargetedMovementGenerator.h.
References CHASE_MOTION_TYPE.
GetPrintout()
std::pair< std::string, std::string > ChaseMovementGenerator::GetPrintout () const
Definition at line 178 of file TargetedMovementGenerator.cpp.
References PathFinder::getPath(), and TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_path.
Referenced by ChatHandler::HandlePrintMovement().
GetResetPosition()
bool ChaseMovementGenerator::GetResetPosition (Unit & , float & , float & , float & , float &) const inline override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 132 of file TargetedMovementGenerator.h.
HandleFinalizedMovement()
void ChaseMovementGenerator::HandleFinalizedMovement (Unit & owner) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 351 of file TargetedMovementGenerator.cpp.
References _clearUnitStateMove(), _reachTarget(), Unit::AI(), CHASE_CLOSENESS_TIMER, CHASE_MODE_BACKPEDAL, CHASE_MODE_DISTANCING, CHASE_MODE_FANNING, CHASE_MODE_NORMAL, UnitAI::DistancingEnded(), Reference< TO, FROM >::getTarget(), WorldObject::GetTransport(), WorldObject::HasInArc(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, m_closenessAndFanningTimer, m_currentMode, m_reachable, and Unit::SetInFront().
HandleMovementFailure()
void ChaseMovementGenerator::HandleMovementFailure (Unit & owner) override virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 343 of file TargetedMovementGenerator.cpp.
References _clearUnitStateMove(), Unit::AI(), CHASE_MODE_DISTANCING, CHASE_MODE_NORMAL, UnitAI::DistancingEnded(), and m_currentMode.
HandleTargetedMovement()
void ChaseMovementGenerator::HandleTargetedMovement (Unit & owner, const uint32 & time_diff) override protected virtual
Implements TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 222 of file TargetedMovementGenerator.cpp.
References _getLocation(), Backpedal(), CHASE_MODE_DISTANCING, CHASE_MODE_NORMAL, DispatchSplineToPosition(), DIST_CALC_NONE, EnableWalking(), Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::Finalized(), WorldObject::GetDistance(), PathFinder::getEndPosition(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTransport(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_path, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_recheckDistance, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_speedChanged, TargetedMovementGeneratorBase::i_target, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, Unit::InterruptMoving(), Unit::IsClientControlled(), IsReachablePositionToTarget(), m_closenessAndFanningTimer, m_closenessExpired, m_currentMode, m_reachable, Unit::movespline, ShortTimeTracker::Passed(), RequiresNewPosition(), ShortTimeTracker::Reset(), Unit::StopMoving(), TYPEID_PLAYER, ShortTimeTracker::Update(), Position::x, Position::y, and Position::z.
Initialize()
void ChaseMovementGenerator::Initialize (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 131 of file TargetedMovementGenerator.cpp.
References _setLocation(), Unit::addUnitState(), WorldObject::GetMap(), Object::GetTypeId(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_lastTargetPos, TargetedMovementGeneratorBase::i_target, Reference< TO, FROM >::isValid(), m_fanningEnabled, sLog, TYPEID_UNIT, and UNIT_STAT_CHASE.
Referenced by Reset().
Interrupt()
void ChaseMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 153 of file TargetedMovementGenerator.cpp.
References Unit::AI(), CHASE_MODE_DISTANCING, Unit::clearUnitState(), Unit::InterruptMoving(), m_currentMode, and UNIT_STAT_CHASE_MOVE.
IsReachable()
bool ChaseMovementGenerator::IsReachable () const override virtual
Reimplemented from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 602 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_targetReached, and m_reachable.
IsReachablePositionToTarget()
bool ChaseMovementGenerator::IsReachablePositionToTarget (Unit & owner, float x, float y, float z, Unit & target) private
Definition at line 670 of file TargetedMovementGenerator.cpp.
References Unit::CanFly(), CREATURE_Z_ATTACK_RANGE_MELEE, DIST_CALC_COMBAT_REACH, Unit::GetCombatReach(), WorldObject::GetCombinedCombatReach(), WorldObject::GetDistance(), WorldObject::GetPosition(), WorldObject::GetTransport(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, TargetedMovementGeneratorBase::i_target, Unit::IsFalling(), Position::x, Position::y, and Position::z.
Referenced by DispatchSplineToPosition(), and HandleTargetedMovement().
IsRemovedOnExpire()
virtual bool ChaseMovementGenerator::IsRemovedOnExpire () const inline override virtual
Reimplemented from MovementGenerator.
Definition at line 138 of file TargetedMovementGenerator.h.
RemoveOnInvalid()
bool ChaseMovementGenerator::RemoveOnInvalid () const inline override virtual
Reimplemented from TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >.
Definition at line 130 of file TargetedMovementGenerator.h.
RequiresNewPosition()
bool ChaseMovementGenerator::RequiresNewPosition (Unit & owner, Position pos) const override protected
Definition at line 607 of file TargetedMovementGenerator.cpp.
References DIST_CALC_NONE, GetDynamicTargetDistance(), WorldObject::GetTransport(), TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, TargetedMovementGeneratorBase::i_target, IGNORE_M2, m_moveFurther, Position::x, Position::y, and Position::z.
Referenced by _setLocation(), and HandleTargetedMovement().
Reset()
void ChaseMovementGenerator::Reset (Unit & owner) override virtual
Reimplemented from MovementGeneratorMedium< T, D >.
Definition at line 161 of file TargetedMovementGenerator.cpp.
References Initialize().
SetOffsetAndAngle()
void ChaseMovementGenerator::SetOffsetAndAngle (float offset, float angle, bool moveFurther)
Definition at line 166 of file TargetedMovementGenerator.cpp.
References TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_angle, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >::i_offset, and m_moveFurther.
Field Documentation
m_closenessAndFanningTimer
uint32 ChaseMovementGenerator::m_closenessAndFanningTimer private
Definition at line 170 of file TargetedMovementGenerator.h.
Referenced by Backpedal(), FanOut(), HandleFinalizedMovement(), and HandleTargetedMovement().
m_closenessExpired
bool ChaseMovementGenerator::m_closenessExpired private
Definition at line 171 of file TargetedMovementGenerator.h.
Referenced by Backpedal(), and HandleTargetedMovement().
m_combat
bool ChaseMovementGenerator::m_combat private
Definition at line 166 of file TargetedMovementGenerator.h.
Referenced by _lostTarget().
m_currentMode
ChaseMovementMode ChaseMovementGenerator::m_currentMode private
Definition at line 173 of file TargetedMovementGenerator.h.
Referenced by Backpedal(), DistanceYourself(), FanOut(), Finalize(), GetCurrentMode(), HandleFinalizedMovement(), HandleMovementFailure(), HandleTargetedMovement(), and Interrupt().
m_fanningEnabled
bool ChaseMovementGenerator::m_fanningEnabled private
Definition at line 168 of file TargetedMovementGenerator.h.
Referenced by FanOut(), and Initialize().
m_moveFurther
bool ChaseMovementGenerator::m_moveFurther private
Definition at line 164 of file TargetedMovementGenerator.h.
Referenced by GetDynamicTargetDistance(), RequiresNewPosition(), and SetOffsetAndAngle().
m_reachable
bool ChaseMovementGenerator::m_reachable private
Definition at line 167 of file TargetedMovementGenerator.h.
Referenced by DispatchSplineToPosition(), HandleFinalizedMovement(), HandleTargetedMovement(), and IsReachable().
m_spawns
GuidVector ChaseMovementGenerator::m_spawns private
Definition at line 175 of file TargetedMovementGenerator.h.
Referenced by DispatchSplineToPosition().
m_walk
bool ChaseMovementGenerator::m_walk private
Definition at line 165 of file TargetedMovementGenerator.h.
Referenced by EnableWalking().
The documentation for this class was generated from the following files:
TargetedMovementGenerator.h
TargetedMovementGenerator.cpp