CMaNGOS_WoTLK: QueryResult Class Reference
QueryResult Class Reference abstract
#include <QueryResult.h>
Public Member Functions
QueryResult (uint64 rowCount, uint32 fieldCount)
virtual ~QueryResult ()
virtual bool NextRow ()=0
Field * Fetch () const
const Field & operator[] (int index) const
uint32 GetFieldCount () const
uint64 GetRowCount () const
Protected Attributes
Field * mCurrentRow
uint32 mFieldCount
uint64 mRowCount
Detailed Description
Definition at line 26 of file QueryResult.h.
Constructor & Destructor Documentation
QueryResult()
QueryResult::QueryResult (uint64 rowCount, uint32 fieldCount) inline
Definition at line 29 of file QueryResult.h.
~QueryResult()
virtual QueryResult::~QueryResult () inline virtual
Definition at line 32 of file QueryResult.h.
Member Function Documentation
Fetch()
Field* QueryResult::Fetch () const inline
Definition at line 36 of file QueryResult.h.
References mCurrentRow.
Referenced by MapPersistentStateManager::_DelHelper(), PlayerbotAI::_HandleCommandSurvey(), AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleReconnectChallenge(), Player::_LoadActions(), Player::_LoadArenaTeamInfo(), Player::_LoadAuras(), Pet::_LoadAuras(), Player::_LoadBGData(), Player::_LoadBoundInstances(), Player::_LoadCreatedInstanceTimers(), Player::_LoadDailyQuestStatus(), Player::_LoadDeclinedNames(), Player::_LoadEquipmentSets(), Player::_LoadGlyphs(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItemLoot(), Player::_LoadMailedItems(), Player::_LoadMails(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Player::_LoadSkills(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::_LoadSpells(), Player::_LoadTalents(), Player::_LoadWeeklyQuestStatus(), World::_UpdateRealmCharCount(), Guild::AddMember(), World::BanAccount(), PlayerbotAI::BotDataRestore(), Player::BuildEnumData(), AccountMgr::CheckPassword(), CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), PlayerbotAI::CombatOrderRestore(), CreateDumpString(), BattleGroundMgr::CreateInitialBattleGrounds(), Map::CreateInstanceData(), Player::Customize(), AccountMgr::DeleteAccount(), Player::DeleteFromDB(), Pet::DeleteFromDB(), Player::DeleteOldCharacters(), BattleGround::EndBattleGround(), QueryNamedResult::Fetch(), AccountMgr::GetCharactersCount(), ChatHandler::getCommandTable(), ChatHandler::GetDeletedCharacterInfoList(), Player::GetGuildIdFromDB(), Player::GetLevelFromDB(), Player::GetRankFromDB(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), PlayerbotAI::GetTalentSpecsAmount(), Player::GetZoneIdFromDB(), ChatHandler::HandleAddItemCommand(), WorldSocket::HandleAuthSession(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleBanListIPCommand(), WorldSession::HandleCalendarEventInvite(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharDeleteOpcode(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGMListFullCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleLinkAddCommand(), ChatHandler::HandleLinkCheckCommand(), ChatHandler::HandleListItemCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionDeclineOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), ChatHandler::HandlePInfoCommand(), WorldSession::HandlePlayerLogin(), MassMailerQueryHandler::HandleQueryCallback(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), WorldSession::HandleWhoisOpcode(), ChatHandler::HandleWpAddCommand(), AuctionHouseBot::Initialize(), CreatureLinkingMgr::IsLinkingEntryValid(), Player::LeaveAllArenaTeams(), PlayerbotAI::ListAuctions(), WaypointManager::Load(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeam::LoadArenaTeamFromDB(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), Guild::LoadBankRightsFromDB(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnEntry(), ScriptMgr::LoadDbScriptRandomTemplates(), World::LoadDBVersion(), World::LoadEventGroupChosen(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), CreatureLinkingMgr::LoadFromDB(), PoolManager::LoadFromDB(), Player::LoadFromDB(), AchievementMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), Guild::LoadGuildFromDB(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMangosStrings(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), Pet::LoadPetFromDB(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), Guild::LoadRanksFromDB(), AuthSocket::LoadRealmlist(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), DungeonResetScheduler::LoadResetTimes(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), World::LoadSpamRecords(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), MapManager::LoadTransports(), WorldSession::LoadTutorialsData(), ObjectMgr::LoadVendors(), SystemMgr::LoadVersion(), WeatherMgr::LoadWeatherZoneChances(), ChatHandler::LookupPlayerSearchCommand(), Player::OnGossipSelect(), QueryNamedResult::operator[](), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), PlayerbotAI::RemoveAuction(), Player::RemovePetitionsAndSigns(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), BattleGroundMgr::RewardArenaSeason(), WorldSession::SendNameQueryResponseFromDBCallBack(), WorldSession::SendPetitionQueryOpcode(), WorldSession::SendStablePet(), PlayerbotAI::SetQuestNeedItems(), ChatHandler::ShowAccountListHelper(), ChatHandler::ShowPlayerListHelper(), StoreGUID(), PlayerbotAI::TalentSpecDBContainsError(), Pet::TryLoadFromDB(), and RealmList::UpdateRealms().
GetFieldCount()
uint32 QueryResult::GetFieldCount () const inline
Definition at line 40 of file QueryResult.h.
References mFieldCount.
Referenced by CreateDumpString(), QueryNamedResult::GetFieldCount(), ChatHandler::HandleBanListHelper(), and SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load().
GetRowCount()
uint64 QueryResult::GetRowCount () const inline
Definition at line 41 of file QueryResult.h.
References mRowCount.
Referenced by CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), BattleGroundMgr::CreateInitialBattleGrounds(), Player::DeleteOldCharacters(), ChatHandler::GetDeletedCharacterInfoList(), QueryNamedResult::GetRowCount(), ChatHandler::HandleListItemCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandleTurnInPetitionOpcode(), CreatureLinkingMgr::IsLinkingEntryValid(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnEntry(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), CreatureLinkingMgr::LoadFromDB(), PoolManager::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), GuildMgr::LoadGuilds(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMangosStrings(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), ScriptDevAIMgr::LoadScriptNames(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), MapManager::LoadTransports(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherZoneChances(), ChatHandler::LookupPlayerSearchCommand(), ObjectMgr::ReturnOrDeleteOldMails(), and PlayerbotAI::TalentSpecDBContainsError().
NextRow()
virtual bool QueryResult::NextRow () pure virtual
Implemented in QueryResultPostgre, and QueryResultMysql.
Referenced by MapPersistentStateManager::_DelHelper(), PlayerbotAI::_HandleCommandSurvey(), Player::_LoadActions(), Player::_LoadArenaTeamInfo(), Player::_LoadAuras(), Pet::_LoadAuras(), Player::_LoadBoundInstances(), Player::_LoadCreatedInstanceTimers(), Player::_LoadDailyQuestStatus(), Player::_LoadEquipmentSets(), Player::_LoadGlyphs(), Player::_LoadInventory(), Player::_LoadItemLoot(), Player::_LoadMailedItems(), Player::_LoadMails(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Player::_LoadSkills(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::_LoadSpells(), Player::_LoadTalents(), Player::_LoadWeeklyQuestStatus(), World::BanAccount(), CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), BattleGroundMgr::CreateInitialBattleGrounds(), AccountMgr::DeleteAccount(), Player::DeleteFromDB(), Player::DeleteOldCharacters(), PlayerDumpWriter::DumpTableContent(), ChatHandler::getCommandTable(), ChatHandler::GetDeletedCharacterInfoList(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleBanListIPCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharEnum(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGMListFullCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleListItemCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionShowSignOpcode(), MassMailerQueryHandler::HandleQueryCallback(), WorldSession::HandleStablePet(), WorldSession::HandleTurnInPetitionOpcode(), AuctionHouseBot::Initialize(), Player::LeaveAllArenaTeams(), PlayerbotAI::ListAuctions(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), Guild::LoadBankRightsFromDB(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnEntry(), ScriptMgr::LoadDbScriptRandomTemplates(), World::LoadEventGroupChosen(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), CreatureLinkingMgr::LoadFromDB(), PoolManager::LoadFromDB(), AchievementMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), GuildMgr::LoadGuilds(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMangosStrings(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), Guild::LoadRanksFromDB(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), DungeonResetScheduler::LoadResetTimes(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), ScriptDevAIMgr::LoadScriptNames(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), World::LoadSpamRecords(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), MapManager::LoadTransports(), WorldSession::LoadTutorialsData(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherZoneChances(), ChatHandler::LookupPlayerSearchCommand(), QueryNamedResult::NextRow(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), Player::RemovePetitionsAndSigns(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), WorldSession::SendStablePet(), PlayerbotAI::SetQuestNeedItems(), ChatHandler::ShowAccountListHelper(), ChatHandler::ShowPlayerListHelper(), PlayerbotAI::TalentSpecDBContainsError(), and RealmList::UpdateRealms().
operator[]()
const Field& QueryResult::operator[] (int index) const inline
Definition at line 38 of file QueryResult.h.
References mCurrentRow.
Field Documentation
mCurrentRow
Field* QueryResult::mCurrentRow protected
Definition at line 44 of file QueryResult.h.
Referenced by QueryResultMysql::ConvertNativeType(), Fetch(), QueryResultMysql::NextRow(), operator[](), and QueryResultMysql::QueryResultMysql().
mFieldCount
uint32 QueryResult::mFieldCount protected
Definition at line 45 of file QueryResult.h.
Referenced by GetFieldCount(), QueryResultMysql::NextRow(), and QueryResultMysql::QueryResultMysql().
mRowCount
uint64 QueryResult::mRowCount protected
Definition at line 46 of file QueryResult.h.
Referenced by GetRowCount().
The documentation for this class was generated from the following file:
QueryResult.h