CMaNGOS_WoTLK: Movement::SplineBase Class Reference
Movement::SplineBase Class Reference
#include <spline.h>
Public Types
enum EvaluationMode {
ModeLinear , ModeCatmullrom , ModeBezier3_Unused , UninitializedMode ,
ModesEnd
}
typedef int index_type
typedef std::vector< Vector3 > ControlArray
Public Member Functions
SplineBase ()
void evaluate_percent (index_type Idx, float u, Vector3 &c) const
Caclulates the position for given segment Idx, and percent of segment length t.
void evaluate_derivative (index_type Idx, float u, Vector3 &hermite) const
Caclulates derivation in index Idx, and percent of segment length t.
index_type first () const
Bounds for spline indexes.
index_type last () const
bool empty () const
EvaluationMode mode () const
bool isCyclic () const
const ControlArray & getPoints () const
index_type getPointCount () const
const Vector3 & getPoint (index_type i) const
void init_spline (const Vector3 *controls, index_type count, EvaluationMode m)
Initializes spline.
void init_cyclic_spline (const Vector3 *controls, index_type count, EvaluationMode m, index_type cyclic_point)
template<class Init >
void init_spline (Init &initializer)
As i can see there are a lot of ways how spline can be initialized would be no harm to have some custom initializers.
void clear ()
float SegLength (index_type i) const
Calculates distance between [i; i+1] points, assumes that index i is in bounds.
std::string ToString () const
Protected Types
enum { STEPS_PER_SEGMENT = 3 }
typedef void(SplineBase::* EvaluationMethtod) (index_type, float, Vector3 &) const
typedef float(SplineBase::* SegLenghtMethtod) (index_type) const
typedef void(SplineBase::* InitMethtod) (const Vector3 *, index_type, bool, index_type)
Protected Member Functions
void EvaluateLinear (index_type, float, Vector3 &) const
void EvaluateCatmullRom (index_type, float, Vector3 &) const
void EvaluateBezier3 (index_type, float, Vector3 &) const
void EvaluateDerivativeLinear (index_type, float, Vector3 &) const
void EvaluateDerivativeCatmullRom (index_type, float, Vector3 &) const
void EvaluateDerivativeBezier3 (index_type, float, Vector3 &) const
float SegLengthLinear (index_type) const
float SegLengthCatmullRom (index_type) const
float SegLengthBezier3 (index_type) const
void InitLinear (const Vector3 *, index_type, bool, index_type)
void InitCatmullRom (const Vector3 *, index_type, bool, index_type)
void InitBezier3 (const Vector3 *, index_type, bool, index_type)
void UninitializedSpline () const
Protected Attributes
ControlArray points
index_type index_lo
index_type index_hi
uint8 m_mode
bool cyclic
Static Protected Attributes
static EvaluationMethtod evaluators [ModesEnd]
static EvaluationMethtod derivative_evaluators [ModesEnd]
static SegLenghtMethtod seglengths [ModesEnd]
static InitMethtod initializers [ModesEnd]
Detailed Description
Definition at line 27 of file spline.h.
Member Typedef Documentation
ControlArray
typedef std::vector<Vector3> Movement::SplineBase::ControlArray
Definition at line 31 of file spline.h.
EvaluationMethtod
typedef void(SplineBase::* Movement::SplineBase::EvaluationMethtod) (index_type, float, Vector3 &) const protected
Definition at line 65 of file spline.h.
index_type
typedef int Movement::SplineBase::index_type
Definition at line 30 of file spline.h.
InitMethtod
typedef void(SplineBase::* Movement::SplineBase::InitMethtod) (const Vector3 *, index_type, bool, index_type) protected
Definition at line 82 of file spline.h.
SegLenghtMethtod
typedef float(SplineBase::* Movement::SplineBase::SegLenghtMethtod) (index_type) const protected
Definition at line 76 of file spline.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
STEPS_PER_SEGMENT
Definition at line 51 of file spline.h.
EvaluationMode
enum Movement::SplineBase::EvaluationMode
Enumerator
ModeLinear
ModeCatmullrom
ModeBezier3_Unused
UninitializedMode
ModesEnd
Definition at line 33 of file spline.h.
Constructor & Destructor Documentation
SplineBase()
Movement::SplineBase::SplineBase () inline explicit
Definition at line 89 of file spline.h.
Member Function Documentation
clear()
void Movement::SplineBase::clear ()
Definition at line 286 of file spline.cpp.
References index_hi, index_lo, and points.
Referenced by Movement::Spline< length_type >::clear().
empty()
bool Movement::SplineBase::empty () const inline
Definition at line 107 of file spline.h.
References index_hi, and index_lo.
Referenced by Movement::MoveSpline::Initialized().
evaluate_derivative()
void Movement::SplineBase::evaluate_derivative (index_type Idx, float u, Vector3 & hermite) const inline
Caclulates derivation in index Idx, and percent of segment length t.
Parameters
Idx - spline segment index, should be in range [first, last)
t - percent of spline segment length, assumes that t in range [0, 1]
Definition at line 101 of file spline.h.
References m_mode.
Referenced by Movement::Spline< length_type >::evaluate_derivative().
evaluate_percent()
void Movement::SplineBase::evaluate_percent (index_type Idx, float u, Vector3 & c) const inline
Caclulates the position for given segment Idx, and percent of segment length t.
Parameters
t - percent of segment length, assumes that t in range [0, 1]
Idx - spline segment index, should be in range [first, last)
Definition at line 95 of file spline.h.
References m_mode.
Referenced by Movement::Spline< length_type >::evaluate_percent().
EvaluateBezier3()
void Movement::SplineBase::EvaluateBezier3 (index_type index, float t, Vector3 & result) const protected
Definition at line 128 of file spline.cpp.
References Movement::C_Evaluate(), index_hi, index_lo, MANGOS_ASSERT, points, and Movement::s_Bezier3Coeffs().
EvaluateCatmullRom()
void Movement::SplineBase::EvaluateCatmullRom (index_type index, float t, Vector3 & result) const protected
Definition at line 122 of file spline.cpp.
References Movement::C_Evaluate(), index_hi, index_lo, MANGOS_ASSERT, points, and Movement::s_catmullRomCoeffs().
EvaluateDerivativeBezier3()
void Movement::SplineBase::EvaluateDerivativeBezier3 (index_type index, float t, Vector3 & result) const protected
Definition at line 147 of file spline.cpp.
References Movement::C_Evaluate_Derivative(), index_hi, index_lo, MANGOS_ASSERT, points, and Movement::s_Bezier3Coeffs().
EvaluateDerivativeCatmullRom()
void Movement::SplineBase::EvaluateDerivativeCatmullRom (index_type index, float t, Vector3 & result) const protected
Definition at line 141 of file spline.cpp.
References Movement::C_Evaluate_Derivative(), index_hi, index_lo, MANGOS_ASSERT, points, and Movement::s_catmullRomCoeffs().
EvaluateDerivativeLinear()
void Movement::SplineBase::EvaluateDerivativeLinear (index_type index, float , Vector3 & result) const protected
Definition at line 135 of file spline.cpp.
References index_hi, index_lo, MANGOS_ASSERT, and points.
EvaluateLinear()
void Movement::SplineBase::EvaluateLinear (index_type index, float u, Vector3 & result) const protected
Definition at line 116 of file spline.cpp.
References index_hi, index_lo, MANGOS_ASSERT, and points.
first()
index_type Movement::SplineBase::first () const inline
Bounds for spline indexes.
All indexes should be in range [first, last).
Definition at line 104 of file spline.h.
References index_lo.
Referenced by Movement::MoveSpline::_updateState(), Movement::MoveSpline::computeFallElevation(), Movement::MoveSpline::currentPathIdx(), Movement::MoveSpline::init_spline(), Movement::Spline< length_type >::length(), and Movement::PacketBuilder::WriteCommonMonsterMovePart().
getPoint()
const Vector3& Movement::SplineBase::getPoint (index_type i) const inline
Definition at line 113 of file spline.h.
References points.
Referenced by Movement::MoveSpline::computeFallElevation(), Movement::MoveSpline::CurrentDestination(), Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::init_spline(), Movement::FallInitializer::operator()(), Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::WriteLinearPath().
getPointCount()
index_type Movement::SplineBase::getPointCount () const inline
Definition at line 112 of file spline.h.
References points.
Referenced by Movement::MoveSpline::_updateState(), Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), and Movement::WriteLinearPath().
getPoints()
const ControlArray& Movement::SplineBase::getPoints () const inline
Definition at line 111 of file spline.h.
References points.
Referenced by Movement::MoveSpline::_updateState(), and Movement::MoveSpline::getPath().
init_cyclic_spline()
void Movement::SplineBase::init_cyclic_spline (const Vector3 * controls, index_type count, EvaluationMode m, index_type cyclic_point)
Definition at line 212 of file spline.cpp.
References cyclic, initializers, and m_mode.
Referenced by Movement::Spline< length_type >::init_cyclic_spline().
init_spline() [1/2]
void Movement::SplineBase::init_spline (const Vector3 * controls, index_type count, EvaluationMode m)
Initializes spline.
Don't call other methods while spline not initialized.
Definition at line 204 of file spline.cpp.
References cyclic, initializers, and m_mode.
Referenced by Movement::Spline< length_type >::init_spline().
init_spline() [2/2]
template<class Init > void Movement::SplineBase::init_spline (Init & initializer) inline
As i can see there are a lot of ways how spline can be initialized would be no harm to have some custom initializers.
Definition at line 121 of file spline.h.
References cyclic, index_hi, index_lo, m_mode, and points.
InitBezier3()
void Movement::SplineBase::InitBezier3 (const Vector3 * controls, index_type count, bool , index_type) protected
Definition at line 273 of file spline.cpp.
References index_hi, index_lo, and points.
InitCatmullRom()
void Movement::SplineBase::InitCatmullRom (const Vector3 * controls, index_type count, bool isCyclic, index_type cyclic_point) protected
Definition at line 240 of file spline.cpp.
References index_hi, index_lo, isCyclic(), and points.
InitLinear()
void Movement::SplineBase::InitLinear (const Vector3 * controls, index_type count, bool isCyclic, index_type cyclic_point) protected
Definition at line 220 of file spline.cpp.
References index_hi, index_lo, isCyclic(), MANGOS_ASSERT, and points.
isCyclic()
bool Movement::SplineBase::isCyclic () const inline
Definition at line 109 of file spline.h.
References cyclic.
Referenced by Movement::MoveSpline::_updateState(), Movement::MoveSpline::init_spline(), InitCatmullRom(), and InitLinear().
last()
index_type Movement::SplineBase::last () const inline
Definition at line 105 of file spline.h.
References index_hi.
Referenced by Movement::MoveSpline::_Finalize(), Movement::MoveSpline::_updateState(), Movement::MoveSpline::currentPathIdx(), Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::init_spline(), and Movement::Spline< length_type >::length().
mode()
EvaluationMode Movement::SplineBase::mode () const inline
Definition at line 108 of file spline.h.
References m_mode.
Referenced by ToString(), and Movement::PacketBuilder::WriteCreate().
SegLength()
float Movement::SplineBase::SegLength (index_type i) const inline
Calculates distance between [i; i+1] points, assumes that index i is in bounds.
Definition at line 129 of file spline.h.
References m_mode.
Referenced by Movement::CommonInitializer::operator()().
SegLengthBezier3()
float Movement::SplineBase::SegLengthBezier3 (index_type index) const protected
Definition at line 180 of file spline.cpp.
References Movement::C_Evaluate(), index_hi, index_lo, MANGOS_ASSERT, points, Movement::s_Bezier3Coeffs(), and STEPS_PER_SEGMENT.
SegLengthCatmullRom()
float Movement::SplineBase::SegLengthCatmullRom (index_type index) const protected
Definition at line 160 of file spline.cpp.
References Movement::C_Evaluate(), index_hi, index_lo, MANGOS_ASSERT, points, Movement::s_catmullRomCoeffs(), and STEPS_PER_SEGMENT.
SegLengthLinear()
float Movement::SplineBase::SegLengthLinear (index_type index) const protected
Definition at line 154 of file spline.cpp.
References index_hi, index_lo, MANGOS_ASSERT, and points.
ToString()
std::string Movement::SplineBase::ToString () const
Definition at line 293 of file spline.cpp.
References mode(), ModesEnd, and points.
Referenced by Movement::MoveSpline::ToString().
UninitializedSpline()
void Movement::SplineBase::UninitializedSpline () const inline protected
Definition at line 85 of file spline.h.
References MANGOS_ASSERT.
Field Documentation
cyclic
bool Movement::SplineBase::cyclic protected
Definition at line 49 of file spline.h.
Referenced by init_cyclic_spline(), init_spline(), Movement::Spline< length_type >::init_spline_custom(), and isCyclic().
derivative_evaluators
SplineBase::EvaluationMethtod Movement::SplineBase::derivative_evaluators static protected
Initial value:
=
    {
        &SplineBase::EvaluateDerivativeLinear,
        &SplineBase::EvaluateDerivativeCatmullRom,
        &SplineBase::EvaluateDerivativeBezier3,
        (EvaluationMethtod)& SplineBase::UninitializedSpline,
    }
Definition at line 71 of file spline.h.
evaluators
SplineBase::EvaluationMethtod Movement::SplineBase::evaluators static protected
Initial value:
=
    {
        &SplineBase::EvaluateLinear,
        &SplineBase::EvaluateCatmullRom,
        &SplineBase::EvaluateBezier3,
        (EvaluationMethtod)& SplineBase::UninitializedSpline,
    }
Definition at line 66 of file spline.h.
index_hi
index_type Movement::SplineBase::index_hi protected
Definition at line 46 of file spline.h.
Referenced by clear(), empty(), EvaluateBezier3(), EvaluateCatmullRom(), EvaluateDerivativeBezier3(), EvaluateDerivativeCatmullRom(), EvaluateDerivativeLinear(), EvaluateLinear(), init_spline(), Movement::Spline< length_type >::init_spline_custom(), InitBezier3(), InitCatmullRom(), Movement::Spline< length_type >::initLengths(), InitLinear(), last(), Movement::Spline< length_type >::length(), SegLengthBezier3(), SegLengthCatmullRom(), and SegLengthLinear().
index_lo
index_type Movement::SplineBase::index_lo protected
Definition at line 45 of file spline.h.
Referenced by clear(), empty(), EvaluateBezier3(), EvaluateCatmullRom(), EvaluateDerivativeBezier3(), EvaluateDerivativeCatmullRom(), EvaluateDerivativeLinear(), EvaluateLinear(), first(), init_spline(), Movement::Spline< length_type >::init_spline_custom(), InitBezier3(), InitCatmullRom(), Movement::Spline< length_type >::initLengths(), InitLinear(), SegLengthBezier3(), SegLengthCatmullRom(), and SegLengthLinear().
initializers
SplineBase::InitMethtod Movement::SplineBase::initializers static protected
Initial value:
=
    {
        &SplineBase::InitCatmullRom,
        &SplineBase::InitCatmullRom,
        &SplineBase::InitBezier3,
        (InitMethtod)& SplineBase::UninitializedSpline,
    }
Definition at line 83 of file spline.h.
Referenced by init_cyclic_spline(), and init_spline().
m_mode
uint8 Movement::SplineBase::m_mode protected
Definition at line 48 of file spline.h.
Referenced by evaluate_derivative(), evaluate_percent(), init_cyclic_spline(), init_spline(), Movement::Spline< length_type >::init_spline_custom(), mode(), and SegLength().
points
ControlArray Movement::SplineBase::points protected
Definition at line 43 of file spline.h.
Referenced by clear(), EvaluateBezier3(), EvaluateCatmullRom(), EvaluateDerivativeBezier3(), EvaluateDerivativeCatmullRom(), EvaluateDerivativeLinear(), EvaluateLinear(), getPoint(), getPointCount(), getPoints(), init_spline(), Movement::Spline< length_type >::init_spline_custom(), InitBezier3(), InitCatmullRom(), InitLinear(), SegLengthBezier3(), SegLengthCatmullRom(), SegLengthLinear(), and ToString().
seglengths
SplineBase::SegLenghtMethtod Movement::SplineBase::seglengths static protected
Initial value:
=
    {
        &SplineBase::SegLengthLinear,
        &SplineBase::SegLengthCatmullRom,
        &SplineBase::SegLengthBezier3,
        (SegLenghtMethtod)& SplineBase::UninitializedSpline,
    }
Definition at line 77 of file spline.h.
The documentation for this class was generated from the following files:
spline.h
spline.cpp