CMaNGOS_WoTLK: UnitConditionMgr Class Reference
UnitConditionMgr Class Reference
#include <UnitCondition.h>
Public Member Functions
std::shared_ptr< std::map< int32, UnitConditionEntry > > Load ()
bool Meets (Unit const *source, Unit const *target, int32 Id)
bool Exists (int32 Id)
std::shared_ptr< std::map< int32, UnitConditionEntry > > Get ()
Private Member Functions
bool meets (Unit const *source, Unit const *target, UnitCondition conditionType, uint32 operation, int32 value)
int32 getConditionValue (Unit const *source, Unit const *target, UnitCondition conditionType, int32 value)
Private Attributes
std::shared_ptr< std::map< int32, UnitConditionEntry > > m_unitConditions
Detailed Description
Definition at line 134 of file UnitCondition.h.
Member Function Documentation
Exists()
bool UnitConditionMgr::Exists (int32 Id)
Definition at line 104 of file UnitCondition.cpp.
References m_unitConditions.
Referenced by CombatConditionMgr::Load().
Get()
std::shared_ptr<std::map<int32, UnitConditionEntry> > UnitConditionMgr::Get () inline
Definition at line 143 of file UnitCondition.h.
References m_unitConditions.
getConditionValue()
int32 UnitConditionMgr::getConditionValue (Unit const * source, Unit const * target, UnitCondition conditionType, int32 value) private
Definition at line 115 of file UnitCondition.cpp.
References AURA_INTERRUPT_FLAG_DAMAGE, BASE_ATTACK, CAN_ASSIST, CAN_ATTACK, Unit::CanAssist(), Unit::CanAttack(), Unit::CanReachWithMeleeAttack(), CLASS, COMBO_POINTS, CREATURE_ID, CREATURE_TYPE, CURRENT_GENERIC_SPELL, DAMAGE_ARCANE, DAMAGE_FIRE, DAMAGE_FROST, DAMAGE_HOLY, DAMAGE_MAGIC, DAMAGE_NATURE, DAMAGE_PHYSICAL, DAMAGE_SHADOW, DAMAGE_TOTAL, SpellEntry::Dispel, DIST_CALC_NONE, ENERGY_PERCENT, Unit::getAttackers(), Unit::getClass(), Unit::GetComboPoints(), Unit::GetCreatureType(), MotionMaster::GetCurrent(), Unit::GetCurrentSpell(), WorldObject::GetDistance(), Object::GetEntry(), Unit::GetHealth(), Unit::GetHealthPercent(), Unit::GetLevel(), Unit::GetMasterGuid(), Unit::GetMiniPet(), Unit::GetMotionMaster(), Object::GetObjectGuid(), Unit::GetPowerPercent(), Unit::getRace(), SpellAuraHolder::GetSpellProto(), Unit::GetTarget(), ThreatManager::getThreatList(), Unit::getThreatManager(), Unit::GetTotem(), HAS_AURA, HAS_CRITTER, HAS_HARMFUL_AURA_CANCELLED_BY_DAMAGE, HAS_HARMFUL_AURA_DISPEL_TYPE, HAS_HARMFUL_AURA_EFFECT, HAS_HARMFUL_AURA_MECHANIC, HAS_HARMFUL_AURA_SCHOOL, HAS_HARMFUL_AURA_SPELL, HAS_HARMFUL_AURA_WITH_PERIODIC_DAMAGE, HAS_HELPFUL_AURA_DISPEL_TYPE, HAS_HELPFUL_AURA_MECHANIC, HAS_HELPFUL_AURA_SPELL, HAS_PET, HAS_TOTEM_IN_SLOT_1, HAS_TOTEM_IN_SLOT_2, HAS_TOTEM_IN_SLOT_3, HAS_TOTEM_IN_SLOT_4, HAS_TOTEM_IN_SLOT_5, HAS_WEAPON, Unit::HasAnyPet(), Unit::HasAura(), Unit::HasAuraHolder(), Unit::HasAuraType(), SpellAuraHolder::HasMechanic(), Unit::HasNegativeAuraWithInterruptFlag(), Unit::HasSpell(), WorldObject::HasStringId(), Unit::hasWeapon(), HEALTH, HEALTH_PERCENT, IN_COMBAT, IN_MELEE_RANGE, IS_ATTACKING_ME, IS_CASTING, IS_CASTING_SPELL, IS_CHANNELING, IS_CHANNELING_SPELL, IS_DYING, IS_ENEMY, IS_IMMUNE_TO_AREA_OF_EFFECT, IS_INTERRUPTIBLE, IS_MASTER, IS_MELEE_ATTACKING, IS_MOVING, IS_MY_PET, IS_PLAYER, IS_PLAYER_CONTROLLED_NPC, IS_RANGED_ATTACKING, IS_SELF, IS_SPEC_HEALER, IS_SPEC_MELEE, IS_SPEC_RANGED, IS_SPEC_TANK, IS_TARGET, Unit::IsAOEImmune(), Object::IsCreature(), Unit::IsEnemy(), Unit::IsInCombat(), Unit::IsInterruptible(), Unit::IsMoving(), Object::IsPlayer(), Unit::IsPlayerControlled(), SpellAuraHolder::IsPositive(), Aura::IsPositive(), MovementGenerator::IsReachable(), LABEL, LEVEL, MANA_PERCENT, NONE, NUMBER_OF_ATTACKERS, NUMBER_OF_ENEMIES, NUMBER_OF_FRIENDS, NUMBER_OF_MELEE_ATTACKERS, NUMBER_OF_RANGED_ATTACKERS, OFF_ATTACK, PATH_FAIL_COUNT, POWER_ENERGY, POWER_MANA, POWER_RAGE, PURSUIT_TIME, RACE, RAGE_PERCENT, RANGE, SpellEntry::SchoolMask, SPELL_AURA_PERIODIC_DAMAGE, SPELL_KNOWN, STRING_ID, THREAT_ARCANE, THREAT_FIRE, THREAT_FROST, THREAT_HOLY, THREAT_MAGIC, THREAT_NATURE, THREAT_PHYSICAL, THREAT_SHADOW, THREAT_TOTAL, TOTAL_AURAS, TOTEM_SLOT_AIR, TOTEM_SLOT_EARTH, TOTEM_SLOT_FIRE, TOTEM_SLOT_WATER, and UNUSED.
Referenced by meets().
Load()
std::shared_ptr< std::map< int32, UnitConditionEntry > > UnitConditionMgr::Load ()
Definition at line 29 of file UnitCondition.cpp.
References MaNGOS::Count(), Field::GetInt32(), Field::GetUInt32(), UnitConditionEntry::Id, m_unitConditions, MAX, UnitConditionEntry::Operation, Database::Query(), sLog, BarGoLink::step(), UnitConditionEntry::Value, UnitConditionEntry::Variable, and WorldDatabase.
Meets()
bool UnitConditionMgr::Meets (Unit const * source, Unit const * target, int32 Id)
Definition at line 81 of file UnitCondition.cpp.
References UnitConditionEntry::Flags, WorldObject::GetMap(), Map::GetMapDataContainer(), MapDataContainer::GetUnitConditions(), meets(), UnitConditionEntry::Operation, UNIT_CONDITION_FLAG_OR, UnitConditionEntry::Value, and UnitConditionEntry::Variable.
Referenced by CombatConditionMgr::Meets().
meets()
bool UnitConditionMgr::meets (Unit const * source, Unit const * target, UnitCondition conditionType, uint32 operation, int32 value) private
Definition at line 109 of file UnitCondition.cpp.
References ConditionEntry::CheckOp(), and getConditionValue().
Referenced by Meets().
Field Documentation
m_unitConditions
std::shared_ptr<std::map<int32, UnitConditionEntry> > UnitConditionMgr::m_unitConditions private
Definition at line 148 of file UnitCondition.h.
Referenced by Exists(), Get(), and Load().
The documentation for this class was generated from the following files:
UnitCondition.h
UnitCondition.cpp