CMaNGOS_WoTLK: PlayerbotWarriorAI Class Reference
PlayerbotWarriorAI Class Reference
#include <PlayerbotWarriorAI.h>
Public Member Functions
PlayerbotWarriorAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotWarriorAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
bool CanPull () override
bool Pull () override
void DoNonCombatActions () override
void CheckShouts ()
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
virtual CombatManeuverReturns DispelPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Private Attributes
uint32 BATTLE_STANCE
uint32 CHARGE
uint32 HEROIC_STRIKE
uint32 REND
uint32 THUNDER_CLAP
uint32 HAMSTRING
uint32 MOCKING_BLOW
uint32 RETALIATION
uint32 SWEEPING_STRIKES
uint32 MORTAL_STRIKE
uint32 BLADESTORM
uint32 HEROIC_THROW
uint32 SHATTERING_THROW
uint32 TASTE_FOR_BLOOD
uint32 SUDDEN_DEATH
uint32 DEFENSIVE_STANCE
uint32 BLOODRAGE
uint32 SUNDER_ARMOR
uint32 TAUNT
uint32 SHIELD_BASH
uint32 REVENGE
uint32 SHIELD_BLOCK
uint32 DISARM
uint32 SHIELD_WALL
uint32 SHIELD_SLAM
uint32 VIGILANCE
uint32 DEVASTATE
uint32 SHOCKWAVE
uint32 CONCUSSION_BLOW
uint32 SPELL_REFLECTION
uint32 LAST_STAND
uint32 BERSERKER_STANCE
uint32 BATTLE_SHOUT
uint32 DEMORALIZING_SHOUT
uint32 OVERPOWER
uint32 CLEAVE
uint32 INTIMIDATING_SHOUT
uint32 EXECUTE
uint32 CHALLENGING_SHOUT
uint32 SLAM
uint32 INTERCEPT
uint32 DEATH_WISH
uint32 BERSERKER_RAGE
uint32 WHIRLWIND
uint32 PUMMEL
uint32 BLOODTHIRST
uint32 RECKLESSNESS
uint32 RAMPAGE
uint32 HEROIC_FURY
uint32 COMMANDING_SHOUT
uint32 ENRAGED_REGENERATION
uint32 PIERCING_HOWL
uint32 SLAM_PROC
uint32 BLOODSURGE
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 AUTO_SHOT
uint32 SpellSequence
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 96 of file PlayerbotWarriorAI.h.
Constructor & Destructor Documentation
PlayerbotWarriorAI()
PlayerbotWarriorAI::PlayerbotWarriorAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotWarriorAI.cpp.
References AUTO_SHOT, AUTO_SHOT_2, BATTLE_SHOUT, BATTLE_SHOUT_1, BATTLE_STANCE, BATTLE_STANCE_1, BERSERKER_RAGE, BERSERKER_RAGE_1, BERSERKER_STANCE, BERSERKER_STANCE_1, BERSERKING, BERSERKING_ALL, BLADESTORM, BLADESTORM_1, BLOOD_FURY, BLOOD_FURY_MELEE_CLASSES, BLOODRAGE, BLOODRAGE_1, BLOODSURGE, BLOODSURGE_1, BLOODTHIRST, BLOODTHIRST_1, CHALLENGING_SHOUT, CHALLENGING_SHOUT_1, CHARGE, CHARGE_1, CLEAVE, CLEAVE_1, COMMANDING_SHOUT, COMMANDING_SHOUT_1, CONCUSSION_BLOW, CONCUSSION_BLOW_1, DEATH_WISH, DEATH_WISH_1, DEFENSIVE_STANCE, DEFENSIVE_STANCE_1, DEMORALIZING_SHOUT, DEMORALIZING_SHOUT_1, DEVASTATE, DEVASTATE_1, DISARM, DISARM_1, ENRAGED_REGENERATION, ENRAGED_REGENERATION_1, ESCAPE_ARTIST, ESCAPE_ARTIST_ALL, EVERY_MAN_FOR_HIMSELF, EVERY_MAN_FOR_HIMSELF_ALL, EXECUTE, EXECUTE_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_WARRIOR, HAMSTRING, HAMSTRING_1, HEROIC_FURY, HEROIC_FURY_1, HEROIC_STRIKE, HEROIC_STRIKE_1, HEROIC_THROW, HEROIC_THROW_1, PlayerbotAI::initSpell(), INTERCEPT, INTERCEPT_1, INTIMIDATING_SHOUT, INTIMIDATING_SHOUT_1, LAST_STAND, LAST_STAND_1, PlayerbotClassAI::m_ai, MOCKING_BLOW, MOCKING_BLOW_1, MORTAL_STRIKE, MORTAL_STRIKE_1, OVERPOWER, OVERPOWER_1, PIERCING_HOWL, PIERCING_HOWL_1, PUMMEL, PUMMEL_1, RAMPAGE, PlayerbotClassAI::RECENTLY_BANDAGED, RECKLESSNESS, RECKLESSNESS_1, REND, REND_1, RETALIATION, RETALIATION_1, REVENGE, REVENGE_1, SHADOWMELD, SHADOWMELD_ALL, SHATTERING_THROW, SHATTERING_THROW_1, SHIELD_BASH, SHIELD_BASH_1, SHIELD_BLOCK, SHIELD_BLOCK_1, SHIELD_SLAM, SHIELD_SLAM_1, SHIELD_WALL, SHIELD_WALL_1, SHOCKWAVE, SHOCKWAVE_1, SLAM, SLAM_1, SLAM_PROC, SLAM_PROC_1, SPELL_REFLECTION, SPELL_REFLECTION_1, STONEFORM, STONEFORM_ALL, SUDDEN_DEATH, SUDDEN_DEATH_1, SUNDER_ARMOR, SUNDER_ARMOR_1, SWEEPING_STRIKES, SWEEPING_STRIKES_1, TASTE_FOR_BLOOD, TASTE_FOR_BLOOD_1, TAUNT, TAUNT_1, THUNDER_CLAP, THUNDER_CLAP_1, VIGILANCE, VIGILANCE_1, WAR_STOMP, WAR_STOMP_ALL, WHIRLWIND, WHIRLWIND_1, WILL_OF_THE_FORSAKEN, and WILL_OF_THE_FORSAKEN_ALL.
~PlayerbotWarriorAI()
PlayerbotWarriorAI::~PlayerbotWarriorAI () virtual
Definition at line 98 of file PlayerbotWarriorAI.cpp.
Member Function Documentation
CanPull()
bool PlayerbotWarriorAI::CanPull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 491 of file PlayerbotWarriorAI.cpp.
References Object::GetUInt32Value(), PlayerbotClassAI::m_bot, and PLAYER_AMMO_ID.
CheckShouts()
void PlayerbotWarriorAI::CheckShouts ()
Definition at line 448 of file PlayerbotWarriorAI.cpp.
References BATTLE_SHOUT, PlayerbotAI::CastSpell(), COMMANDING_SHOUT, EFFECT_INDEX_0, Unit::HasAura(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, SPELL_CAST_OK, and WARRIOR_SPEC_PROTECTION.
Referenced by DoNextCombatManeuverPVE().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotWarriorAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 100 of file PlayerbotWarriorAI.cpp.
References PlayerbotAI::Attack(), ATTACK_DISTANCE, PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DIST_CALC_COMBAT_REACH_WITH_MELEE, DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCurrentTarget(), WorldObject::GetDistance(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_TANK, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, PlayerbotAI::SCENARIO_PVP_OPENWORLD, and PlayerbotAI::SetGroupIgnoreUpdateTime().
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotWarriorAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 159 of file PlayerbotWarriorAI.cpp.
References BATTLE_STANCE, BERSERKER_STANCE, BLOODRAGE, PlayerbotAI::CastSpell(), CHARGE, DEFENSIVE_STANCE, DIST_CALC_COMBAT_REACH_WITH_MELEE, EFFECT_INDEX_0, PlayerbotAI::GetCombatOrder(), WorldObject::GetContactPoint(), WorldObject::GetDistance(), PlayerbotAI::GetRageAmount(), Unit::HasAura(), INTERCEPT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_TANK, WorldObject::Relocate(), RETURN_CONTINUE, RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, SPELL_CAST_OK, and TAUNT.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotWarriorAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 217 of file PlayerbotWarriorAI.cpp.
References BATTLE_STANCE, BERSERKER_STANCE, BLOODRAGE, PlayerbotAI::CastSpell(), CHARGE, DEFENSIVE_STANCE, DIST_CALC_COMBAT_REACH_WITH_MELEE, EFFECT_INDEX_0, PlayerbotAI::GetCombatOrder(), WorldObject::GetContactPoint(), WorldObject::GetDistance(), PlayerbotAI::GetRageAmount(), Unit::HasAura(), INTERCEPT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_TANK, WorldObject::Relocate(), RETURN_CONTINUE, RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, SPELL_CAST_OK, and TAUNT.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotWarriorAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 274 of file PlayerbotWarriorAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotWarriorAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 291 of file PlayerbotWarriorAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, BERSERKER_RAGE, BLADESTORM, BLOODRAGE, BLOODSURGE, BLOODTHIRST, PlayerbotAI::CastSpell(), CheckShouts(), CONCUSSION_BLOW, DEMORALIZING_SHOUT, EFFECT_INDEX_0, EXECUTE, PlayerbotAI::FindAttacker(), PlayerbotAI::GetCombatOrder(), Unit::GetHealthPercent(), PlayerbotAI::GetRageAmount(), Unit::HasAura(), HEROIC_STRIKE, WorldObject::IsSpellReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MORTAL_STRIKE, PlayerbotAI::ORDERS_TANK, OVERPOWER, REND, RETURN_CONTINUE, RETURN_NO_ACTION_OK, PlayerbotAI::SetIgnoreUpdateTime(), SHATTERING_THROW, SHIELD_SLAM, SHOCKWAVE, SLAM, SPELL_CAST_OK, SUDDEN_DEATH, TASTE_FOR_BLOOD, TAUNT, THUNDER_CLAP, WARRIOR_SPEC_ARMS, WARRIOR_SPEC_FURY, WARRIOR_SPEC_PROTECTION, and WHIRLWIND.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotWarriorAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 439 of file PlayerbotWarriorAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), HEROIC_STRIKE, PlayerbotClassAI::m_ai, RETURN_CONTINUE, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotWarriorAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 462 of file PlayerbotWarriorAI.cpp.
References BATTLE_STANCE, BERSERKER_STANCE, PlayerbotAI::CastSpell(), DEFENSIVE_STANCE, PlayerbotClassAI::EatDrinkBandage(), EFFECT_INDEX_0, PlayerbotAI::GetHealthPercent(), Unit::getRace(), GIFT_OF_THE_NAARU, Unit::HasAura(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_master, RACE_DRAENEI, SPELL_CAST_OK, PlayerbotAI::TellMaster(), VIGILANCE, WARRIOR_SPEC_ARMS, WARRIOR_SPEC_FURY, and WARRIOR_SPEC_PROTECTION.
Pull()
bool PlayerbotWarriorAI::Pull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 497 of file PlayerbotWarriorAI.cpp.
References PlayerbotAI::Attack(), ATTACK_DISTANCE, AUTO_SHOT, Unit::CastSpell(), DIST_CALC_COMBAT_REACH_WITH_MELEE, PlayerbotAI::GetCurrentSpellId(), PlayerbotAI::GetCurrentTarget(), WorldObject::GetDistance(), PlayerbotAI::In_Range(), WorldObject::IsWithinLOSInMap(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::TellMaster(), and TRIGGERED_OLD_TRIGGERED.
Field Documentation
ARCANE_TORRENT
uint32 PlayerbotWarriorAI::ARCANE_TORRENT private
Definition at line 181 of file PlayerbotWarriorAI.h.
AUTO_SHOT
uint32 PlayerbotWarriorAI::AUTO_SHOT private
Definition at line 193 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI(), and Pull().
BATTLE_SHOUT
uint32 PlayerbotWarriorAI::BATTLE_SHOUT private
Definition at line 157 of file PlayerbotWarriorAI.h.
Referenced by CheckShouts(), and PlayerbotWarriorAI().
BATTLE_STANCE
uint32 PlayerbotWarriorAI::BATTLE_STANCE private
Definition at line 121 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNonCombatActions(), and PlayerbotWarriorAI().
BERSERKER_RAGE
uint32 PlayerbotWarriorAI::BERSERKER_RAGE private
Definition at line 167 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
BERSERKER_STANCE
uint32 PlayerbotWarriorAI::BERSERKER_STANCE private
Definition at line 156 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNonCombatActions(), and PlayerbotWarriorAI().
BERSERKING
uint32 PlayerbotWarriorAI::BERSERKING private
Definition at line 189 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
BLADESTORM
uint32 PlayerbotWarriorAI::BLADESTORM private
Definition at line 131 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
BLOOD_FURY
uint32 PlayerbotWarriorAI::BLOOD_FURY private
Definition at line 187 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
BLOODRAGE
uint32 PlayerbotWarriorAI::BLOODRAGE private
Definition at line 139 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
BLOODSURGE
uint32 PlayerbotWarriorAI::BLOODSURGE private
Definition at line 178 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
BLOODTHIRST
uint32 PlayerbotWarriorAI::BLOODTHIRST private
Definition at line 170 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
CHALLENGING_SHOUT
uint32 PlayerbotWarriorAI::CHALLENGING_SHOUT private
Definition at line 163 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
CHARGE
uint32 PlayerbotWarriorAI::CHARGE private
Definition at line 122 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), and PlayerbotWarriorAI().
CLEAVE
uint32 PlayerbotWarriorAI::CLEAVE private
Definition at line 160 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
COMMANDING_SHOUT
uint32 PlayerbotWarriorAI::COMMANDING_SHOUT private
Definition at line 174 of file PlayerbotWarriorAI.h.
Referenced by CheckShouts(), and PlayerbotWarriorAI().
CONCUSSION_BLOW
uint32 PlayerbotWarriorAI::CONCUSSION_BLOW private
Definition at line 151 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
DEATH_WISH
uint32 PlayerbotWarriorAI::DEATH_WISH private
Definition at line 166 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
DEFENSIVE_STANCE
uint32 PlayerbotWarriorAI::DEFENSIVE_STANCE private
Definition at line 138 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNonCombatActions(), and PlayerbotWarriorAI().
DEMORALIZING_SHOUT
uint32 PlayerbotWarriorAI::DEMORALIZING_SHOUT private
Definition at line 158 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
DEVASTATE
uint32 PlayerbotWarriorAI::DEVASTATE private
Definition at line 149 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
DISARM
uint32 PlayerbotWarriorAI::DISARM private
Definition at line 145 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
ENRAGED_REGENERATION
uint32 PlayerbotWarriorAI::ENRAGED_REGENERATION private
Definition at line 175 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
ESCAPE_ARTIST
uint32 PlayerbotWarriorAI::ESCAPE_ARTIST private
Definition at line 184 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotWarriorAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 185 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
EXECUTE
uint32 PlayerbotWarriorAI::EXECUTE private
Definition at line 162 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotWarriorAI::GIFT_OF_THE_NAARU private
Definition at line 182 of file PlayerbotWarriorAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarriorAI().
HAMSTRING
uint32 PlayerbotWarriorAI::HAMSTRING private
Definition at line 126 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
HEROIC_FURY
uint32 PlayerbotWarriorAI::HEROIC_FURY private
Definition at line 173 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
HEROIC_STRIKE
uint32 PlayerbotWarriorAI::HEROIC_STRIKE private
Definition at line 123 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotWarriorAI().
HEROIC_THROW
uint32 PlayerbotWarriorAI::HEROIC_THROW private
Definition at line 132 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
INTERCEPT
uint32 PlayerbotWarriorAI::INTERCEPT private
Definition at line 165 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), and PlayerbotWarriorAI().
INTIMIDATING_SHOUT
uint32 PlayerbotWarriorAI::INTIMIDATING_SHOUT private
Definition at line 161 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
LAST_STAND
uint32 PlayerbotWarriorAI::LAST_STAND private
Definition at line 153 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
MOCKING_BLOW
uint32 PlayerbotWarriorAI::MOCKING_BLOW private
Definition at line 127 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
MORTAL_STRIKE
uint32 PlayerbotWarriorAI::MORTAL_STRIKE private
Definition at line 130 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
OVERPOWER
uint32 PlayerbotWarriorAI::OVERPOWER private
Definition at line 159 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
PIERCING_HOWL
uint32 PlayerbotWarriorAI::PIERCING_HOWL private
Definition at line 176 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
PUMMEL
uint32 PlayerbotWarriorAI::PUMMEL private
Definition at line 169 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
RAMPAGE
uint32 PlayerbotWarriorAI::RAMPAGE private
Definition at line 172 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
RECKLESSNESS
uint32 PlayerbotWarriorAI::RECKLESSNESS private
Definition at line 171 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
REND
uint32 PlayerbotWarriorAI::REND private
Definition at line 124 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
RETALIATION
uint32 PlayerbotWarriorAI::RETALIATION private
Definition at line 128 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
REVENGE
uint32 PlayerbotWarriorAI::REVENGE private
Definition at line 143 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SHADOWMELD
uint32 PlayerbotWarriorAI::SHADOWMELD private
Definition at line 186 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SHATTERING_THROW
uint32 PlayerbotWarriorAI::SHATTERING_THROW private
Definition at line 133 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
SHIELD_BASH
uint32 PlayerbotWarriorAI::SHIELD_BASH private
Definition at line 142 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SHIELD_BLOCK
uint32 PlayerbotWarriorAI::SHIELD_BLOCK private
Definition at line 144 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SHIELD_SLAM
uint32 PlayerbotWarriorAI::SHIELD_SLAM private
Definition at line 147 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
SHIELD_WALL
uint32 PlayerbotWarriorAI::SHIELD_WALL private
Definition at line 146 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SHOCKWAVE
uint32 PlayerbotWarriorAI::SHOCKWAVE private
Definition at line 150 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
SLAM
uint32 PlayerbotWarriorAI::SLAM private
Definition at line 164 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
SLAM_PROC
uint32 PlayerbotWarriorAI::SLAM_PROC private
Definition at line 177 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SPELL_REFLECTION
uint32 PlayerbotWarriorAI::SPELL_REFLECTION private
Definition at line 152 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SpellSequence
uint32 PlayerbotWarriorAI::SpellSequence private
Definition at line 195 of file PlayerbotWarriorAI.h.
STONEFORM
uint32 PlayerbotWarriorAI::STONEFORM private
Definition at line 183 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SUDDEN_DEATH
uint32 PlayerbotWarriorAI::SUDDEN_DEATH private
Definition at line 135 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
SUNDER_ARMOR
uint32 PlayerbotWarriorAI::SUNDER_ARMOR private
Definition at line 140 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
SWEEPING_STRIKES
uint32 PlayerbotWarriorAI::SWEEPING_STRIKES private
Definition at line 129 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
TASTE_FOR_BLOOD
uint32 PlayerbotWarriorAI::TASTE_FOR_BLOOD private
Definition at line 134 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
TAUNT
uint32 PlayerbotWarriorAI::TAUNT private
Definition at line 141 of file PlayerbotWarriorAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
THUNDER_CLAP
uint32 PlayerbotWarriorAI::THUNDER_CLAP private
Definition at line 125 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
VIGILANCE
uint32 PlayerbotWarriorAI::VIGILANCE private
Definition at line 148 of file PlayerbotWarriorAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarriorAI().
WAR_STOMP
uint32 PlayerbotWarriorAI::WAR_STOMP private
Definition at line 188 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
WHIRLWIND
uint32 PlayerbotWarriorAI::WHIRLWIND private
Definition at line 168 of file PlayerbotWarriorAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarriorAI().
WILL_OF_THE_FORSAKEN
uint32 PlayerbotWarriorAI::WILL_OF_THE_FORSAKEN private
Definition at line 190 of file PlayerbotWarriorAI.h.
Referenced by PlayerbotWarriorAI().
The documentation for this class was generated from the following files:
PlayerbotWarriorAI.h
PlayerbotWarriorAI.cpp