CMaNGOS_WoTLK: Path< PathElem, PathNode > Class Template Reference
Path< PathElem, PathNode > Class Template Reference
#include <Path.h>
Public Member Functions
size_t size () const
bool empty () const
void resize (unsigned int sz)
void crop (unsigned int start, unsigned int end)
void clear ()
float GetTotalLength (uint32 start, uint32 end) const
float GetTotalLength () const
float GetPassedLength (uint32 curnode, float x, float y, float z) const
void push_back (const PathElem &node)
void pop_back ()
auto & front () const
auto & back () const
PathNode & operator[] (size_t idx)
PathNode const & operator[] (size_t idx) const
void set (size_t idx, PathElem elem)
auto begin () const
auto end () const
auto rbegin () const
auto rend () const
bool operator!= (Path< PathElem, PathNode > const &other) const
Protected Attributes
std::deque< PathElem > i_nodes
Detailed Description
template<typename PathElem, typename PathNode = PathElem>
class Path< PathElem, PathNode >
Definition at line 34 of file Path.h.
Member Function Documentation
back()
template<typename PathElem , typename PathNode = PathElem> auto& Path< PathElem, PathNode >::back () const inline
Definition at line 94 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by Taxi::Tracker::AddRoute(), and TransportMgr::GenerateWaypoints().
begin()
template<typename PathElem , typename PathNode = PathElem> auto Path< PathElem, PathNode >::begin () const inline
Definition at line 101 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by TransportAnimation::GetPrevAnimNode(), Taxi::Tracker::Prepare(), and Taxi::Tracker::Trim().
clear()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::clear () inline
Definition at line 55 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
crop()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::crop (unsigned int start, unsigned int end) inline
Definition at line 40 of file Path.h.
References Path< PathElem, PathNode >::end(), and Path< PathElem, PathNode >::i_nodes.
empty()
template<typename PathElem , typename PathNode = PathElem> bool Path< PathElem, PathNode >::empty () const inline
Definition at line 38 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
end()
template<typename PathElem , typename PathNode = PathElem> auto Path< PathElem, PathNode >::end () const inline
Definition at line 102 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by Path< PathElem, PathNode >::crop(), TransportAnimation::GetNextAnimNode(), TransportAnimation::GetPrevAnimNode(), Path< PathElem, PathNode >::GetTotalLength(), Taxi::Tracker::Prepare(), and Taxi::Tracker::Trim().
front()
template<typename PathElem , typename PathNode = PathElem> auto& Path< PathElem, PathNode >::front () const inline
Definition at line 93 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by Taxi::Tracker::AddRoute().
GetPassedLength()
template<typename PathElem , typename PathNode = PathElem> float Path< PathElem, PathNode >::GetPassedLength (uint32 curnode, float x, float y, float z) const inline
Definition at line 74 of file Path.h.
References Path< PathElem, PathNode >::GetTotalLength(), Path< PathElem, PathNode >::i_nodes, PathNode::x, PathNode::y, and PathNode::z.
GetTotalLength() [1/2]
template<typename PathElem , typename PathNode = PathElem> float Path< PathElem, PathNode >::GetTotalLength () const inline
Definition at line 72 of file Path.h.
References Path< PathElem, PathNode >::GetTotalLength(), and Path< PathElem, PathNode >::size().
Referenced by Path< PathElem, PathNode >::GetPassedLength(), and Path< PathElem, PathNode >::GetTotalLength().
GetTotalLength() [2/2]
template<typename PathElem , typename PathNode = PathElem> float Path< PathElem, PathNode >::GetTotalLength (uint32 start, uint32 end) const inline
Definition at line 57 of file Path.h.
References Path< PathElem, PathNode >::end(), Path< PathElem, PathNode >::i_nodes, PathNode::x, PathNode::y, and PathNode::z.
operator!=()
template<typename PathElem , typename PathNode = PathElem> bool Path< PathElem, PathNode >::operator!= (Path< PathElem, PathNode > const & other) const inline
Definition at line 106 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
operator[]() [1/2]
template<typename PathElem , typename PathNode = PathElem> PathNode& Path< PathElem, PathNode >::operator[] (size_t idx) inline
Definition at line 96 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
operator[]() [2/2]
template<typename PathElem , typename PathNode = PathElem> PathNode const& Path< PathElem, PathNode >::operator[] (size_t idx) const inline
Definition at line 97 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
pop_back()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::pop_back () inline
Definition at line 91 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
push_back()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::push_back (const PathElem & node) inline
Definition at line 90 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
rbegin()
template<typename PathElem , typename PathNode = PathElem> auto Path< PathElem, PathNode >::rbegin () const inline
Definition at line 103 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by Taxi::Tracker::Trim().
rend()
template<typename PathElem , typename PathNode = PathElem> auto Path< PathElem, PathNode >::rend () const inline
Definition at line 104 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by Taxi::Tracker::Trim().
resize()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::resize (unsigned int sz) inline
Definition at line 39 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
set()
template<typename PathElem , typename PathNode = PathElem> void Path< PathElem, PathNode >::set (size_t idx, PathElem elem) inline
Definition at line 99 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
size()
template<typename PathElem , typename PathNode = PathElem> size_t Path< PathElem, PathNode >::size () const inline
Definition at line 37 of file Path.h.
References Path< PathElem, PathNode >::i_nodes.
Referenced by TransportMgr::GenerateWaypoints(), Path< PathElem, PathNode >::GetTotalLength(), and ObjectMgr::LoadTaxiShortcuts().
Field Documentation
i_nodes
template<typename PathElem , typename PathNode = PathElem> std::deque<PathElem> Path< PathElem, PathNode >::i_nodes protected
Definition at line 109 of file Path.h.
Referenced by Path< PathElem, PathNode >::back(), Path< PathElem, PathNode >::begin(), Path< PathElem, PathNode >::clear(), Path< PathElem, PathNode >::crop(), Path< PathElem, PathNode >::empty(), Path< PathElem, PathNode >::end(), Path< PathElem, PathNode >::front(), Path< PathElem, PathNode >::GetPassedLength(), Path< PathElem, PathNode >::GetTotalLength(), Path< PathElem, PathNode >::operator!=(), Path< PathElem, PathNode >::operator[](), Path< PathElem, PathNode >::pop_back(), Path< PathElem, PathNode >::push_back(), Path< PathElem, PathNode >::rbegin(), Path< PathElem, PathNode >::rend(), Path< PathElem, PathNode >::resize(), Path< PathElem, PathNode >::set(), and Path< PathElem, PathNode >::size().
The documentation for this class was generated from the following file:
Path.h