CMaNGOS_WoTLK: Map Class Reference
Map Class Reference
#include <Map.h>
Data Structures
struct StringIdMapStorage
Public Types
enum ScriptExecutionParam { SCRIPT_EXEC_PARAM_NONE = 0x00 , SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE = 0x01 , SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET = 0x02 , SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE_TARGET = 0x03 }
typedef MapRefManager PlayerList
typedef TypeUnorderedMapContainer< AllMapStoredObjectTypes, ObjectGuid > MapStoredObjectTypesContainer
typedef std::set< Transport * > TransportSet
Public Types inherited from GridRefManager< NGridType >
typedef LinkedListHead::Iterator< GridReference< NGridType > > iterator
Public Types inherited from RefManager< TO, FROM >
typedef LinkedListHead::Iterator< Reference< TO, FROM > > iterator
typedef LinkedListHead::Iterator< Reference< TO, FROM > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
virtual ~Map ()
bool CanUnload (uint32 diff)
virtual void Initialize (bool loadInstanceData=true)
virtual bool Add (Player *)
virtual void Remove (Player *, bool)
template<class T >
void Add (T *)
template<class T >
void Remove (T *, bool)
void VisitNearbyCellsOf (WorldObject *obj, TypeContainerVisitor< MaNGOS::ObjectUpdater, GridTypeMapContainer > &gridVisitor, TypeContainerVisitor< MaNGOS::ObjectUpdater, WorldTypeMapContainer > &worldVisitor)
virtual void Update (const uint32 &)
void MessageBroadcast (Player const *, WorldPacket const &, bool to_self)
void MessageBroadcast (WorldObject const *, WorldPacket const &)
void MessageDistBroadcast (Player const *, WorldPacket const &, float dist, bool to_self, bool own_team_only=false)
void MessageDistBroadcast (WorldObject const *, WorldPacket const &, float dist)
void MessageMapBroadcast (WorldObject const *obj, WorldPacket const &msg)
void MessageMapBroadcastZone (WorldObject const *obj, WorldPacket const &msg, uint32 zoneId)
void MessageMapBroadcastArea (WorldObject const *obj, WorldPacket const &msg, uint32 areaId)
void ExecuteDistWorker (WorldObject const *obj, float dist, std::function< void(Player *)> const &worker)
void ExecuteMapWorker (std::function< void(Player *)> const &worker)
void ExecuteMapWorkerZone (uint32 zoneId, std::function< void(Player *)> const &worker)
void ExecuteMapWorkerArea (uint32 areaId, std::function< void(Player *)> const &worker)
float GetVisibilityDistance () const
virtual void InitVisibilityDistance ()
void PlayerRelocation (Player *, float x, float y, float z, float orientation)
void CreatureRelocation (Creature *creature, float x, float y, float z, float ang)
void GameObjectRelocation (GameObject *go, float x, float y, float z, float orientation, bool respawnRelocationOnFail=true)
void DynamicObjectRelocation (DynamicObject *dynObj, float x, float y, float z, float orientation)
template<class T , class CONTAINER >
void Visit (const Cell &cell, TypeContainerVisitor< T, CONTAINER > &visitor)
bool IsRemovalGrid (float x, float y) const
bool IsLoaded (float x, float y) const
bool GetUnloadLock (const GridPair &p) const
void SetUnloadLock (const GridPair &p, bool on)
void ForceLoadGrid (float x, float y)
bool UnloadGrid (const uint32 &x, const uint32 &y, bool pForce)
virtual void UnloadAll (bool pForce)
void ResetGridExpiry (NGridType &grid, float factor=1) const
time_t GetGridExpiry (void) const
uint32 GetId (void) const
virtual void RemoveAllObjectsInRemoveList ()
bool CreatureRespawnRelocation (Creature *c)
uint32 GetInstanceId () const
virtual bool CanEnter (Player *player)
const char * GetMapName () const
uint8 GetSpawnMode () const
Difficulty GetDifficulty () const
bool IsRegularDifficulty () const
uint32 GetMaxPlayers () const
uint32 GetMaxResetDelay () const
MapDifficultyEntry const * GetMapDifficulty () const
void ChangeMapDifficulty (Difficulty difficulty)
void SetNewDifficultyCooldown (TimePoint const &newCooldown)
TimePoint const & GetNewDifficultyCooldown () const
MapEntry const * GetEntry () const
bool Instanceable () const
bool IsDungeon () const
bool IsRaid () const
bool IsNonRaidDungeon () const
bool IsRaidOrHeroicDungeon () const
bool IsHeroic () const
bool IsBattleGround () const
bool IsBattleArena () const
bool IsBattleGroundOrArena () const
bool IsContinent () const
bool IsMountAllowed () const
bool IsDynguidForced () const
MapPersistentState * GetPersistentState () const
void AddObjectToRemoveList (WorldObject *obj)
void UpdateObjectVisibility (WorldObject *obj, Cell cell, const CellPair &cellpair)
void resetMarkedCells ()
bool isCellMarked (uint32 pCellId) const
void markCell (uint32 pCellId)
bool HavePlayers () const
uint32 GetPlayersCountExceptGMs () const
bool ActiveObjectsNearGrid (uint32 x, uint32 y) const
void SendToPlayers (WorldPacket const &data) const
Send a Packet to all players on a map.
bool SendToPlayersInZone (WorldPacket const &data, uint32 zoneId) const
Send a Packet to all players in a zone. Return false if no player found.
PlayerList const & GetPlayers () const
bool ScriptsStart (ScriptMapType scriptType, uint32 id, Object *source, Object *target, ScriptExecutionParam execParams=SCRIPT_EXEC_PARAM_NONE)
Put scripts in the execution queue.
void ScriptCommandStart (ScriptInfo const &script, uint32 delay, Object *source, Object *target)
void AddToActive (WorldObject *obj)
void RemoveFromActive (WorldObject *obj)
void AddToOnEventNotified (WorldObject *obj)
void RemoveFromOnEventNotified (WorldObject *obj)
void OnEventHappened (uint16 event_id, bool activate, bool resume)
Player * GetPlayer (ObjectGuid guid)
Function return player that in world at CURRENT map.
Creature * GetCreature (ObjectGuid guid)
Function return creature (non-pet and then most summoned by spell creatures) that in world at CURRENT map.
Creature * GetCreatureByEntry (uint32 entry)
Pet * GetPet (ObjectGuid guid)
Function return pet that in world at CURRENT map.
Creature * GetAnyTypeCreature (ObjectGuid guid)
Function return non-player unit object that in world at CURRENT map, so creature, or pet, or vehicle.
GameObject * GetGameObject (ObjectGuid guid)
Function return gameobject that in world at CURRENT map.
DynamicObject * GetDynamicObject (ObjectGuid guid)
Function return dynamic object that in world at CURRENT map.
Corpse * GetCorpse (ObjectGuid guid) const
Function return corpse that at CURRENT map.
Unit * GetUnit (ObjectGuid guid)
Function return unit in world at CURRENT map.
WorldObject * GetWorldObject (ObjectGuid guid)
Function return world object in world at CURRENT map, so any except transports.
Creature * GetCreature (uint32 dbguid) const
GameObject * GetGameObject (uint32 dbguid) const
std::vector< WorldObject * > const * GetWorldObjects (std::string stringId) const
std::vector< Creature * > const * GetCreatures (std::string stringId) const
std::vector< GameObject * > const * GetGameObjects (std::string stringId) const
std::vector< WorldObject * > const * GetWorldObjects (uint32 stringId) const
std::vector< Creature * > const * GetCreatures (uint32 stringId) const
std::vector< GameObject * > const * GetGameObjects (uint32 stringId) const
void AddDbGuidObject (WorldObject *obj)
void RemoveDbGuidObject (WorldObject *obj)
void AddStringIdObject (uint32 stringId, WorldObject *obj)
void RemoveStringIdObject (uint32 stringId, WorldObject *obj)
MapStoredObjectTypesContainer & GetObjectsStore ()
std::map< uint32, uint32 > & GetTempCreatures ()
std::map< uint32, uint32 > & GetTempPets ()
void AddUpdateObject (Object *obj)
void RemoveUpdateObject (Object *obj)
uint32 GenerateLocalLowGuid (HighGuid guidhigh)
const TerrainInfo * GetTerrain () const
void CreateInstanceData (bool load)
InstanceData * GetInstanceData () const
uint32 GetScriptId () const
void MonsterYellToMap (ObjectGuid guid, int32 textId, ChatMsg chatMsg, Language language, Unit const *target) const
Function simulates yell of creature.
void MonsterYellToMap (CreatureInfo const *cinfo, int32 textId, ChatMsg chatMsg, Language language, Unit const *target, uint32 senderLowGuid=0) const
Function simulates yell of creature.
void PlayDirectSoundToMap (uint32 soundId, uint32 zoneId=0) const
Function to play sound to all players in map.
float GetHeight (uint32 phasemask, float x, float y, float z, bool swim=false) const
bool GetHeightInRange (uint32 phasemask, float x, float y, float &z, float maxSearchDist=4.0f) const
bool IsInLineOfSight (float srcX, float srcY, float srcZ, float destX, float destY, float destZ, uint32 phasemask, bool ignoreM2Model) const
Function to check if a point is in line of sight from an other point.
bool GetHitPosition (float srcX, float srcY, float srcZ, float &destX, float &destY, float &destZ, uint32 phasemask, float modifyDist) const
get the hit position and return true if we hit something (in this case the dest position will hold the hit-position) otherwise the result pos will be the dest pos
void InsertGameObjectModel (const GameObjectModel &mdl)
void RemoveGameObjectModel (const GameObjectModel &mdl)
bool ContainsGameObjectModel (const GameObjectModel &mdl) const
CreatureLinkingHolder * GetCreatureLinkingHolder ()
void TeleportAllPlayersTo (TeleportLocation loc)
WeatherSystem * GetWeatherSystem () const
void SetWeather (uint32 zoneId, WeatherType type, float grade, bool permanently)
Set the weather in a zone on this map.
bool GetReachableRandomPosition (Unit *unit, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetReachableRandomPointOnGround (uint32 phaseMask, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetRandomPointInTheAir (uint32 phaseMask, float &x, float &y, float &z, float radius, bool randomRange=true) const
bool GetRandomPointUnderWater (uint32 phaseMask, float &x, float &y, float &z, float radius, GridMapLiquidData &liquid_status, bool randomRange=true) const
uint32 SpawnedCountForEntry (uint32 entry)
void AddToSpawnCount (const ObjectGuid &guid)
void RemoveFromSpawnCount (const ObjectGuid &guid)
uint32 GetCurrentMSTime () const
TimePoint GetCurrentClockTime () const
uint32 GetCurrentDiff () const
time_t GetCurrentTime_t () const
tm GetCurrentTime_tm () const
void SetZoneMusic (uint32 zoneId, uint32 areaId, uint32 musicId)
Function to set the zone music info.
void SetZoneWeather (uint32 zoneId, uint32 areaId, uint32 weatherId, float weatherGrade)
Function to set the zone weather info.
void SetZoneOverrideLight (uint32 zoneId, uint32 areaId, uint32 lightId, uint32 fadeInTime)
Function to set the zone light override info.
void SendZoneDynamicInfo (Player *player, bool zoneUpdated, bool areaUpdated) const
Function to set the zone dynamic info.
void CreatePlayerOnClient (Player *player)
uint32 GetLoadedGridsCount ()
Messager< Map > & GetMessager ()
GenericTransport * GetTransport (ObjectGuid guid)
TransportSet const & GetTransports ()
GraveyardManager & GetGraveyardManager ()
void AddTransport (Transport *transport)
void RemoveTransport (Transport *transport)
bool CanSpawn (TypeID typeId, uint32 dbGuid)
SpawnManager & GetSpawnManager ()
MapDataContainer & GetMapDataContainer ()
MapDataContainer const & GetMapDataContainer () const
WorldStateVariableManager & GetVariableManager ()
WorldStateVariableManager const & GetVariableManager () const
void ChangeGOPathfinding (uint32 entry, uint32 displayId, bool apply)
void SetNavTile (uint32 tileX, uint32 tileY, uint32 tileNumber)
void AwardLFGRewards (uint32 dungeonId)
template<>
void AddToGrid (GameObject *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Player *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Corpse *obj, NGridType *grid, Cell const &cell)
template<>
void AddToGrid (Creature *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Player *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Corpse *obj, NGridType *grid, Cell const &cell)
template<>
void RemoveFromGrid (Creature *obj, NGridType *grid, Cell const &cell)
Public Member Functions inherited from GridRefManager< NGridType >
GridReference< NGridType > * getFirst ()
GridReference< NGridType > * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefManager< TO, FROM >
RefManager ()
virtual ~RefManager ()
Reference< TO, FROM > * getFirst ()
Reference< TO, FROM > const * getFirst () const
Reference< TO, FROM > * getLast ()
Reference< TO, FROM > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
const_iterator begin () const
const_iterator end () const
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Static Public Member Functions
static void DeleteFromWorld (Player *pl)
Data Fields
std::set< ObjectGuid > m_objRemoveList
Protected Types
typedef WorldObjectSet ActiveNonPlayers
Protected Member Functions
Map (uint32 id, time_t, uint32 InstanceId, uint8 SpawnMode)
Protected Attributes
MapEntry const * i_mapEntry
uint8 i_spawnMode
uint32 i_id
uint32 i_InstanceId
uint32 m_unloadTimer
float m_VisibleDistance
MapPersistentState * m_persistentState
MapRefManager m_mapRefManager
MapRefManager::iterator m_mapRefIter
ActiveNonPlayers m_activeNonPlayers
ActiveNonPlayers::iterator m_activeNonPlayersIter
MapStoredObjectTypesContainer m_objectsStore
std::map< uint32, uint32 > m_tempCreatures
std::map< uint32, uint32 > m_tempPets
std::map< std::pair< HighGuid, uint32 >, std::vector< WorldObject * > > m_dbGuidObjects
WorldObjectSet m_onEventNotifiedObjects
WorldObjectSet::iterator m_onEventNotifiedIter
Messager< Map > m_messager
GraveyardManager m_graveyardManager
Private Types
typedef std::multimap< TimePoint, ScriptAction > ScriptScheduleMap
Private Member Functions
void LoadMapAndVMap (int gx, int gy)
void SetTimer (uint32 t)
void SendInitSelf (Player *player) const
void SendInitTransports (Player *player) const
void SendRemoveTransports (Player *player) const
void LoadTransports ()
bool CreatureCellRelocation (Creature *c, const Cell &new_cell)
bool loaded (const GridPair &) const
void EnsureGridCreated (const GridPair &)
bool EnsureGridLoaded (Cell const &)
void EnsureGridLoadedAtEnter (Cell const &, Player *player=nullptr)
void buildNGridLinkage (NGridType *pNGridType)
NGridType * getNGrid (uint32 x, uint32 y) const
bool isGridObjectDataLoaded (uint32 x, uint32 y) const
void setGridObjectDataLoaded (bool pLoaded, uint32 x, uint32 y)
void setNGrid (NGridType *grid, uint32 x, uint32 y)
void ScriptsProcess ()
Process queued scripts.
void SendObjectUpdates ()
template<class T >
void AddToGrid (T *, NGridType *, Cell const &)
template<class T >
void RemoveFromGrid (T *, NGridType *, Cell const &)
Private Attributes
std::set< Object * > i_objectsToClientUpdate
time_t i_gridExpiry
time_t m_curTime
tm m_curTimeTm
NGridType * i_grids [MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS]
TerrainInfo *const m_TerrainData
bool m_bLoadedGrids [MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS]
std::bitset< TOTAL_NUMBER_OF_CELLS_PER_MAP *TOTAL_NUMBER_OF_CELLS_PER_MAP > marked_cells
WorldObjectSet i_objectsToRemove
ScriptScheduleMap m_scriptSchedule
InstanceData * i_data
uint32 i_script_id
ObjectGuidGenerator< HIGHGUID_UNIT > m_CreatureGuids
ObjectGuidGenerator< HIGHGUID_GAMEOBJECT > m_GameObjectGuids
ObjectGuidGenerator< HIGHGUID_TRANSPORT > m_transportGuids
ObjectGuidGenerator< HIGHGUID_DYNAMICOBJECT > m_DynObjectGuids
ObjectGuidGenerator< HIGHGUID_PET > m_PetGuids
ObjectGuidGenerator< HIGHGUID_VEHICLE > m_VehicleGuids
CreatureLinkingHolder m_creatureLinkingHolder
DynamicMapTree m_dyn_tree
WeatherSystem * m_weatherSystem
TransportSet m_transports
TransportSet::iterator m_transportsIterator
std::unordered_map< uint32, std::set< ObjectGuid > > m_spawnedCount
SpawnManager m_spawnManager
std::unordered_map< uint32, StringIdMapStorage > m_objectsPerStringId
MapDataContainer m_dataContainer
std::shared_ptr< CreatureSpellListContainer > m_spellListContainer
WorldStateVariableManager m_variableManager
ZoneDynamicInfoMap m_zoneDynamicInfo
ZoneDynamicInfoMap m_areaDynamicInfo
uint32 m_defaultLight
TimePoint m_dynamicDifficultyCooldown
std::map< std::pair< uint32, uint32 >, uint32 > m_tileNumberPerTile
Friends
class MapReference
class ObjectGridLoader
class ObjectWorldLoader
Detailed Description
Definition at line 117 of file Map.h.
Member Typedef Documentation
ActiveNonPlayers
typedef WorldObjectSet Map::ActiveNonPlayers protected
Definition at line 474 of file Map.h.
MapStoredObjectTypesContainer
typedef TypeUnorderedMapContainer<AllMapStoredObjectTypes, ObjectGuid> Map::MapStoredObjectTypesContainer
Definition at line 309 of file Map.h.
PlayerList
typedef MapRefManager Map::PlayerList
Definition at line 259 of file Map.h.
ScriptScheduleMap
typedef std::multimap<TimePoint, ScriptAction> Map::ScriptScheduleMap private
Definition at line 503 of file Map.h.
TransportSet
typedef std::set<Transport*> Map::TransportSet
Definition at line 392 of file Map.h.
Member Enumeration Documentation
ScriptExecutionParam
enum Map::ScriptExecutionParam
Enumerator
SCRIPT_EXEC_PARAM_NONE
SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE
SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET
SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE_TARGET
Definition at line 263 of file Map.h.
Constructor & Destructor Documentation
Map()
Map::Map (uint32 id, time_t expiry, uint32 InstanceId, uint8 SpawnMode) protected
Definition at line 216 of file Map.cpp.
References m_weatherSystem.
~Map()
Map::~Map () virtual
Definition at line 53 of file Map.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), GetInstanceId(), TerrainInfo::GetMapId(), i_data, m_persistentState, m_TerrainData, m_transports, m_weatherSystem, Referencable< Countable >::Release(), MapPersistentState::SetUsedByMapState(), sTerrainMgr, UnloadAll(), and MMAP::MMapManager::unloadMapInstance().
Member Function Documentation
ActiveObjectsNearGrid()
bool Map::ActiveObjectsNearGrid (uint32 x, uint32 y) const
Definition at line 1492 of file Map.cpp.
References MaNGOS::ComputeCellPair(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), GetVisibilityDistance(), m_activeNonPlayers, m_mapRefManager, MANGOS_ASSERT, MAX_NUMBER_OF_CELLS, MAX_NUMBER_OF_GRIDS, SIZE_OF_GRID_CELL, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by UnloadGrid(), and ActiveState::Update().
Add() [1/2]
bool Map::Add (Player * player) virtual
Reimplemented in BattleGroundMap, and DungeonMap.
Definition at line 483 of file Map.cpp.
References Player::AddToWorld(), Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), EnsureGridLoadedAtEnter(), ViewPoint::Event_AddedToWorld(), Player::GetMapRef(), getNGrid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetViewPoint(), Cell::GridX(), Cell::GridY(), i_data, IsRaid(), Reference< TO, FROM >::link(), InstanceData::OnPlayerEnter(), Unit::RemoveAllGroupBuffsFromCaster(), SendInitSelf(), SendInitTransports(), WorldObject::SetMap(), and UpdateObjectVisibility().
Referenced by DungeonMap::Add(), BattleGroundMap::Add(), Player::BuildPlayerRepop(), BattleGround::ChangeBgCreatureSpawnState(), ObjectAccessor::ConvertCorpseForPlayer(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::EffectAddFarsight(), Spell::EffectCreateTamedPet(), Spell::EffectDuel(), Spell::EffectPersistentAA(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), Spell::EffectTransmitted(), ChatHandler::HandleGameObjectMoveCommand(), WorldSession::HandlePlayerLogin(), Creature::LoadFromDB(), GameObject::LoadFromDB(), Pet::LoadPetFromDB(), GameObject::Refresh(), TemporarySpawn::Summon(), Totem::Summon(), GameObject::SummonLinkedTrapIfAny(), Unit::TakePossessOf(), Creature::Update(), and GameObject::Update().
Add() [2/2]
template<class T > void Map::Add (T * obj)
Definition at line 513 of file Map.cpp.
References AddToActive(), AddToGrid(), Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), DEBUG_FILTER_LOG, EnsureGridCreated(), EnsureGridLoadedAtEnter(), getNGrid(), Cell::GridX(), Cell::GridY(), LOG_FILTER_CREATURE_MOVES, MANGOS_ASSERT, sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, UpdateObjectVisibility(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
AddDbGuidObject()
void Map::AddDbGuidObject (WorldObject * obj)
Definition at line 2420 of file Map.cpp.
References Object::GetDbGuid(), WorldObject::GetParentHigh(), and m_dbGuidObjects.
Referenced by Creature::AddToWorld(), and GameObject::AddToWorld().
AddObjectToRemoveList()
void Map::AddObjectToRemoveList (WorldObject * obj)
Definition at line 1413 of file Map.cpp.
References WorldObject::CleanupsBeforeDelete(), GetId(), WorldObject::GetInstanceId(), GetInstanceId(), WorldObject::GetMapId(), i_objectsToRemove, and MANGOS_ASSERT.
Referenced by WorldObject::AddObjectToRemoveList().
AddStringIdObject()
void Map::AddStringIdObject (uint32 stringId, WorldObject * obj)
Definition at line 2431 of file Map.cpp.
References Object::IsCreature(), Object::IsGameObject(), and m_objectsPerStringId.
Referenced by WorldObject::AddToWorld(), and WorldObject::SetStringId().
AddToActive()
void Map::AddToActive (WorldObject * obj)
Definition at line 1530 of file Map.cpp.
References MaNGOS::ComputeCellPair(), MaNGOS::ComputeGridPair(), EnsureGridLoaded(), Object::GetEntry(), Object::GetGUIDLow(), getNGrid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Creature::GetRespawnCoord(), Object::GetTypeId(), Creature::HasStaticDBSpawnData(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::incUnloadActiveLock(), Creature::IsPet(), m_activeNonPlayers, sLog, TYPEID_UNIT, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Add(), LoadHelper(), WorldObject::SetActiveObjectState(), and Camera::SetView().
AddToGrid() [1/5]
template<> void Map::AddToGrid (Corpse * obj, NGridType * grid, Cell const & cell)
Definition at line 296 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), CORPSE_BONES, and Corpse::GetType().
AddToGrid() [2/5]
template<> void Map::AddToGrid (Creature * obj, NGridType * grid, Cell const & cell)
Definition at line 311 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), Creature::IsPet(), and WorldObject::SetCurrentCell().
AddToGrid() [3/5]
template<> void Map::AddToGrid (GameObject * obj, NGridType * grid, Cell const & cell)
Definition at line 283 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), and WorldObject::SetCurrentCell().
AddToGrid() [4/5]
template<> void Map::AddToGrid (Player * obj, NGridType * grid, Cell const & cell)
Definition at line 290 of file Map.cpp.
References Cell::CellX(), and Cell::CellY().
AddToGrid() [5/5]
template<class T > void Map::AddToGrid (T * obj, NGridType * grid, Cell const & cell) private
Definition at line 277 of file Map.cpp.
References Cell::CellX(), and Cell::CellY().
Referenced by Add(), CreatureCellRelocation(), DynamicObjectRelocation(), EnsureGridLoadedAtEnter(), GameObjectRelocation(), and PlayerRelocation().
AddToOnEventNotified()
void Map::AddToOnEventNotified (WorldObject * obj)
Definition at line 1593 of file Map.cpp.
References m_onEventNotifiedObjects.
Referenced by WorldObject::AddToWorld(), and WorldObject::SetNotifyOnEventState().
AddToSpawnCount()
void Map::AddToSpawnCount (const ObjectGuid & guid)
Definition at line 2898 of file Map.cpp.
References ObjectGuid::GetEntry(), and m_spawnedCount.
Referenced by Creature::AddToWorld().
AddTransport()
void Map::AddTransport (Transport * transport)
Definition at line 123 of file Map.cpp.
References m_transports.
Referenced by Transport::LoadTransport(), and Transport::TeleportTransport().
AddUpdateObject()
void Map::AddUpdateObject (Object * obj) inline
Definition at line 314 of file Map.h.
References i_objectsToClientUpdate.
Referenced by WorldObject::AddToClientUpdateList().
AwardLFGRewards()
void Map::AwardLFGRewards (uint32 dungeonId)
Definition at line 162 of file Map.cpp.
References GetPlayers(), and sLFGMgr.
Referenced by boss_headless_horsemanAI::JustDied(), boss_ahuneAI::JustDied(), instance_shadowfang_keep::SetData(), and DungeonPersistentState::UpdateEncounterState().
buildNGridLinkage()
void Map::buildNGridLinkage (NGridType * pNGridType) inline private
Definition at line 444 of file Map.h.
References NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::link().
Referenced by EnsureGridCreated().
CanEnter()
bool Map::CanEnter (Player * player) virtual
Reimplemented in BattleGroundMap.
Definition at line 2078 of file Map.cpp.
References Player::GetMapRef(), and Reference< TO, FROM >::getTarget().
Referenced by DungeonMap::Add(), BattleGroundMap::CanEnter(), and Player::TeleportTo().
CanSpawn()
bool Map::CanSpawn (TypeID typeId, uint32 dbGuid)
Definition at line 141 of file Map.cpp.
References CreatureLinkingHolder::CanSpawn(), GetCreatureLinkingHolder(), GetDifficulty(), sObjectMgr, GameObjectData::spawnMask, TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by WorldObject::SpawnCreature(), and WorldObject::SpawnGameObject().
CanUnload()
bool Map::CanUnload (uint32 diff) inline
Definition at line 130 of file Map.h.
References m_unloadTimer.
Referenced by MapManager::Update().
ChangeGOPathfinding()
void Map::ChangeGOPathfinding (uint32 entry, uint32 displayId, bool apply)
Definition at line 181 of file Map.cpp.
References ByteConverter::apply(), MMAP::MMapManager::ChangeTile(), MMAP::MMapFactory::createOrGetMMapManager(), GetId(), GetInstanceId(), GameObjectModel::GetTileDataForGoDisplayId(), GameObjectModel::GetTilesForGOEntry(), and m_tileNumberPerTile.
Referenced by boss_malygosAI::JustDidDialogueStep(), boss_kologarnAI::JustDied(), ColiseumFloor::JustSpawned(), ColiseumFloor::OnGoStateChange(), instance_ulduar::OnPlayerEnter(), and instance_eye_of_eternity::SetData().
ChangeMapDifficulty()
void Map::ChangeMapDifficulty (Difficulty difficulty)
Definition at line 1243 of file Map.cpp.
References GetCurrentClockTime(), Object::GetDbGuid(), Object::GetEntry(), GetObjectsStore(), i_spawnMode, Unit::IsClientControlled(), SetNewDifficultyCooldown(), sObjectMgr, and Creature::UpdateEntry().
Referenced by MapManager::CreateInstance(), and WorldSession::HandleChangePlayerDifficulty().
ContainsGameObjectModel()
bool Map::ContainsGameObjectModel (const GameObjectModel & mdl) const
Definition at line 2682 of file Map.cpp.
References DynamicMapTree::contains(), and m_dyn_tree.
CreateInstanceData()
void Map::CreateInstanceData (bool load)
Definition at line 1611 of file Map.cpp.
References CharacterDatabase, DEBUG_LOG, QueryResult::Fetch(), GetId(), ObjectMgr::GetInstanceTemplate(), Field::GetString(), ObjectMgr::GetWorldTemplate(), i_data, i_InstanceId, i_script_id, InstanceData::Initialize(), Instanceable(), InstanceData::Load(), Database::PExecute(), Database::PQuery(), and sScriptDevAIMgr.
Referenced by Initialize().
CreatePlayerOnClient()
void Map::CreatePlayerOnClient (Player * player)
Definition at line 469 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), ViewPoint::Event_AddedToWorld(), getNGrid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetViewPoint(), Cell::GridX(), Cell::GridY(), SendInitSelf(), SendInitTransports(), and UpdateObjectVisibility().
Referenced by WorldSession::HandlePlayerReconnect().
CreatureCellRelocation()
bool Map::CreatureCellRelocation (Creature * c, const Cell & new_cell) private
Definition at line 1127 of file Map.cpp.
References AddToGrid(), Cell::CellX(), Cell::CellY(), DEBUG_FILTER_LOG, Cell::DiffGrid(), EnsureGridLoadedAtEnter(), ViewPoint::Event_GridChanged(), WorldObject::GetCurrentCell(), Object::GetEntry(), Object::GetGUIDLow(), getNGrid(), WorldObject::GetViewPoint(), Cell::gridPair(), Cell::GridX(), Cell::GridY(), WorldObject::isActiveObject(), loaded(), LOG_FILTER_CREATURE_MOVES, and RemoveFromGrid().
Referenced by CreatureRelocation(), and CreatureRespawnRelocation().
CreatureRelocation()
void Map::CreatureRelocation (Creature * creature, float x, float y, float z, float ang)
Definition at line 1040 of file Map.cpp.
References MaNGOS::ComputeCellPair(), CreatureCellRelocation(), CreatureRespawnRelocation(), DEBUG_FILTER_LOG, Object::GetEntry(), Object::GetGUIDLow(), LOG_FILTER_CREATURE_MOVES, Unit::OnRelocated(), and WorldObject::Relocate().
Referenced by WorldSession::HandleMoverRelocation(), ChatHandler::HandleNpcMoveCommand(), npc_brann_hosAI::JustRespawned(), FollowMovementGenerator::Move(), Unit::NearTeleportTo(), Creature::RemoveCorpse(), TransportBase::UpdateGlobalPositionOf(), GenericTransport::UpdatePassengerPosition(), and Unit::UpdateSplinePosition().
CreatureRespawnRelocation()
bool Map::CreatureRespawnRelocation (Creature * c)
Definition at line 1152 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), MotionMaster::Clear(), Unit::CombatStopWithPets(), MaNGOS::ComputeCellPair(), CreatureCellRelocation(), DEBUG_FILTER_LOG, WorldObject::GetCurrentCell(), Object::GetEntry(), Object::GetGUIDLow(), Unit::GetMotionMaster(), Creature::GetRespawnCoord(), Cell::GridX(), Cell::GridY(), MotionMaster::Initialize(), LOG_FILTER_CREATURE_MOVES, Unit::OnRelocated(), and WorldObject::Relocate().
Referenced by CreatureRelocation(), and ObjectGridRespawnMover::Visit().
DeleteFromWorld()
void Map::DeleteFromWorld (Player * pl) static
Definition at line 369 of file Map.cpp.
References sObjectAccessor.
Referenced by WorldSession::LogoutPlayer(), and Remove().
DynamicObjectRelocation()
void Map::DynamicObjectRelocation (DynamicObject * dynObj, float x, float y, float z, float orientation)
Definition at line 1093 of file Map.cpp.
References AddToGrid(), Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), DEBUG_FILTER_LOG, Cell::DiffCell(), Cell::DiffGrid(), EnsureGridLoadedAtEnter(), ViewPoint::Event_GridChanged(), WorldObject::GetCurrentCell(), Object::GetEntry(), Object::GetGUIDLow(), getNGrid(), WorldObject::GetViewPoint(), Cell::gridPair(), Cell::GridX(), Cell::GridY(), WorldObject::isActiveObject(), loaded(), LOG_FILTER_CREATURE_MOVES, WorldObject::Relocate(), RemoveFromGrid(), and WorldObject::UpdateObjectVisibility().
Referenced by GenericTransport::UpdatePassengerPosition().
EnsureGridCreated()
void Map::EnsureGridCreated (const GridPair & p) private
Definition at line 375 of file Map.cpp.
References buildNGridLinkage(), CONFIG_BOOL_GRID_UNLOAD, getNGrid(), GRID_STATE_IDLE, i_gridExpiry, LoadMapAndVMap(), m_bLoadedGrids, MAX_NUMBER_OF_GRIDS, NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::SetGridState(), setNGrid(), sWorld, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Add(), and EnsureGridLoaded().
EnsureGridLoaded()
bool Map::EnsureGridLoaded (Cell const & cell) private
Definition at line 423 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), EnsureGridCreated(), getNGrid(), Cell::GridX(), Cell::GridY(), isGridObjectDataLoaded(), ObjectGridLoader::LoadN(), MANGOS_ASSERT, setGridObjectDataLoaded(), and sObjectAccessor.
Referenced by AddToActive(), EnsureGridLoadedAtEnter(), and Visit().
EnsureGridLoadedAtEnter()
void Map::EnsureGridLoadedAtEnter (Cell const & cell, Player * player = nullptr) private
Definition at line 396 of file Map.cpp.
References AddToGrid(), Cell::CellX(), Cell::CellY(), DEBUG_FILTER_LOG, EnsureGridLoaded(), WorldObject::GetName(), getNGrid(), GRID_STATE_ACTIVE, Cell::GridX(), Cell::GridY(), i_id, LOG_FILTER_PLAYER_MOVES, ResetGridExpiry(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::SetGridState().
Referenced by Add(), CreatureCellRelocation(), DynamicObjectRelocation(), ForceLoadGrid(), GameObjectRelocation(), and PlayerRelocation().
ExecuteDistWorker()
void Map::ExecuteDistWorker (WorldObject const * obj, float dist, std::function< void(Player *)> const & worker)
Definition at line 658 of file Map.cpp.
References MaNGOS::ComputeCellPair(), Cell::data, Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetTypeId(), loaded(), Cell::Part, Cell::SetNoCreate(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Cell::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by go_screaming_hall_door::UpdateAI(), go_brewfest_music::UpdateAI(), and go_midsummer_music::UpdateAI().
ExecuteMapWorker()
void Map::ExecuteMapWorker (std::function< void(Player *)> const & worker)
Definition at line 679 of file Map.cpp.
References GetPlayers().
ExecuteMapWorkerArea()
void Map::ExecuteMapWorkerArea (uint32 areaId, std::function< void(Player *)> const & worker)
Definition at line 694 of file Map.cpp.
References GetPlayers().
ExecuteMapWorkerZone()
void Map::ExecuteMapWorkerZone (uint32 zoneId, std::function< void(Player *)> const & worker)
Definition at line 686 of file Map.cpp.
References GetPlayers().
Referenced by WorldObject::MonsterText(), and SendBgNeutralToPlayer().
ForceLoadGrid()
void Map::ForceLoadGrid (float x, float y)
Definition at line 458 of file Map.cpp.
References MaNGOS::ComputeCellPair(), EnsureGridLoadedAtEnter(), getNGrid(), Cell::GridX(), Cell::GridY(), IsLoaded(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::setUnloadExplicitLock().
Referenced by CinematicMgr::BeginCinematic(), and ObjectMgr::LoadActiveEntities().
GameObjectRelocation()
void Map::GameObjectRelocation (GameObject * go, float x, float y, float z, float orientation, bool respawnRelocationOnFail = true)
Definition at line 1060 of file Map.cpp.
References AddToGrid(), Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), DEBUG_FILTER_LOG, Cell::DiffCell(), Cell::DiffGrid(), EnsureGridLoadedAtEnter(), ViewPoint::Event_GridChanged(), WorldObject::GetCurrentCell(), Object::GetEntry(), Object::GetGUIDLow(), getNGrid(), WorldObject::GetViewPoint(), Cell::gridPair(), Cell::GridX(), Cell::GridY(), WorldObject::isActiveObject(), loaded(), LOG_FILTER_CREATURE_MOVES, WorldObject::Relocate(), RemoveFromGrid(), GameObject::UpdateModelPosition(), and WorldObject::UpdateObjectVisibility().
Referenced by ElevatorTransport::Update(), and GenericTransport::UpdatePassengerPosition().
GenerateLocalLowGuid()
uint32 Map::GenerateLocalLowGuid (HighGuid guidhigh)
Definition at line 2451 of file Map.cpp.
References ObjectGuidGenerator< high >::Generate(), HIGHGUID_DYNAMICOBJECT, HIGHGUID_GAMEOBJECT, HIGHGUID_PET, HIGHGUID_TRANSPORT, HIGHGUID_UNIT, HIGHGUID_VEHICLE, m_CreatureGuids, m_DynObjectGuids, m_GameObjectGuids, m_PetGuids, m_VehicleGuids, and MANGOS_ASSERT.
Referenced by Pet::CreateBaseAtCreature(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::DoSummonTotem(), Spell::EffectAddFarsight(), Spell::EffectCreateTamedPet(), Spell::EffectDuel(), Spell::EffectPersistentAA(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonPet(), Spell::EffectTransmitted(), Creature::LoadFromDB(), GameObject::LoadFromDB(), Pet::LoadPetFromDB(), WorldObject::SummonCreature(), GameObject::SummonLinkedTrapIfAny(), and Unit::TakePossessOf().
GetAnyTypeCreature()
Creature * Map::GetAnyTypeCreature (ObjectGuid guid)
Function return non-player unit object that in world at CURRENT map, so creature, or pet, or vehicle.
Parameters
guid must be non-player unit guid (HIGHGUID_PET HIGHGUID_UNIT HIGHGUID_VEHICLE)
Definition at line 2252 of file Map.cpp.
References GetCreature(), ObjectGuid::GetHigh(), GetPet(), HIGHGUID_PET, HIGHGUID_UNIT, and HIGHGUID_VEHICLE.
Referenced by npc_thrallAI::CanUseFeralSpiritsAgain(), npc_building_triggerAI::DamageTaken(), UnitAI::DespawnGuids(), ScriptedInstance::DespawnGuids(), AiDelayEventAround::Execute(), HomeMovementGenerator< Creature >::Finalize(), Player::GetNPCIfCanInteractWith(), npc_spring_rabbitAI::GetPartnerAI(), ChatHandler::getSelectedCreature(), GetUnit(), ObjectAccessor::GetUnit(), WorldSession::HandleGetMirrorimageData(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandleSpellClick(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), AbstractWrapperMovementGenerator::Inform(), WaypointMovementGenerator< Creature >::InformAI(), boss_terestianAI::JustReachedHome(), AbstractPathMovementGenerator::MovementInform(), WorldSession::SendPetNameQuery(), Player::SendQuestGiverStatusMultiple(), npc_spring_rabbitAI::UpdateAI(), and Player::UpdateForQuestWorldObjects().
GetCorpse()
Corpse * Map::GetCorpse (ObjectGuid guid) const
Function return corpse that at CURRENT map.
Note: corpse can be NOT IN WORLD, so can't be used corpse->GetMap() without pre-check corpse->isInWorld()
Parameters
guid must be corpse guid (HIGHGUID_CORPSE)
Definition at line 2241 of file Map.cpp.
References ObjectAccessor::GetCorpseInMap(), GetId(), WorldObject::GetInstanceId(), and GetInstanceId().
Referenced by Spell::CheckCast(), Spell::CheckTarget(), Corpse::DeleteBonesFromWorld(), LootMgr::GetLoot(), GetWorldObject(), and RemoveAllObjectsInRemoveList().
GetCreature() [1/2]
Creature * Map::GetCreature (ObjectGuid guid)
Function return creature (non-pet and then most summoned by spell creatures) that in world at CURRENT map.
Parameters
guid must be creature or vehicle guid (HIGHGUID_UNIT HIGHGUID_VEHICLE)
Definition at line 2219 of file Map.cpp.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), and m_objectsStore.
Referenced by PlayerbotAI::_HandleCommandGet(), PlayerbotAI::_HandleCommandSkill(), boss_algalonAI::ActivateRandomConstellation(), boss_kelidan_the_breakerAI::AddJustAggroed(), boss_malchezaarAI::Aggro(), npc_amanishi_scoutAI::Aggro(), boss_sjonnirAI::Aggro(), boss_warbringer_omroggAI::Aggro(), boss_soccothratesAI::Aggro(), npc_precious_the_devourerAI::Aggro(), npc_simone_seductressAI::Aggro(), AreaTrigger_at_frostworn_general(), boss_anetheronAI::boss_anetheronAI(), boss_anzuAI::boss_anzuAI(), boss_jeklikAI::boss_jeklikAI(), boss_terokkAI::boss_terokkAI(), boss_veras_darkshadowAI::boss_veras_darkshadowAI(), boss_ionarAI::CallBackSparks(), CreatureLinkingHolder::CanSpawn(), BattleGround::ChangeBgCreatureSpawnState(), PlayerbotAI::CheckBotCast(), mob_arugal_voidwalkerAI::CheckGroupStatus(), Spell::CheckScriptTargeting(), BattlefieldWG::CleanupBattlefield(), instance_blackwing_lair::CleanupNefarianStage(), mob_phoenix_tkAI::CorpseRemoved(), boss_ahuneAI::DamageTaken(), npc_frozen_coreAI::DamageTaken(), npc_dirty_larryAI::DamageTaken(), boss_black_knightAI::DamageTaken(), boss_hodirAI::DamageTaken(), boss_saraAI::DamageTaken(), npc_simone_seductressAI::DemonDespawn(), CreatureGroup::Despawn(), instance_wailing_caverns::DespawnAll(), instance_mount_hyjal::DespawnBase(), world_map_outland::DespawnBashir(), boss_anzuAI::DespawnBirdHelpers(), npc_commanderAI::DespawnDefenders(), npc_commanderAI::DespawnDragonmaw(), npc_adyen_the_lightwardenAI::DespawnEvent(), boss_volkhanAI::DespawnGolems(), boss_kelthuzadAI::DespawnIntroCreatures(), boss_mechano_lord_capacitusAI::DespawnNetherCharges(), instance_mount_hyjal::DespawnOverrun(), boss_netherspiteAI::DespawnPortals(), boss_ionarAI::DespawnSpark(), npc_colonel_julesAI::DespawnSummons(), OutdoorPvPGH::DespawnVendors(), OutdoorPvPNA::DespawnVendors(), npc_scrap_reaverAI::Die(), ChaseMovementGenerator::DispatchSplineToPosition(), instance_gundrak::DoAltarVisualEffect(), npc_eris_havenfireAI::DoAttackArchersTarget(), instance_shattered_halls::DoBeginArcherAttack(), boss_ymironAI::DoChannelSpiritYmiron(), instance_zulaman::DoChestEvent(), instance_trial_of_the_champion::DoCleanupArenaOnWipe(), instance_trial_of_the_crusader::DoCleanupCrusaders(), instance_halls_of_reflection::DoCleanupFrostmourneEvent(), world_map_ebon_hold::DoClearBattleScene(), instance_violet_hold::DoClearBossMobs(), CreatureLinkingHolder::DoCreatureLinkingEvent(), world_map_ebon_hold::DoDefeatUndeadArmy(), boss_warchief_kargath_bladefistAI::DoDespawnAdds(), boss_jeklikAI::DoDespawnBombRiders(), boss_anubarak_trialAI::DoDespawnPursuingSpikes(), npc_keeper_remulosAI::DoDespawnSummoned(), boss_eranikusAI::DoDespawnSummoned(), boss_kaelthasAI::DoDespawnSummons(), npc_eris_havenfireAI::DoDespawnSummons(), instance_karazhan::DoFailChessEvent(), instance_karazhan::DoFinishChessEvent(), boss_hydross_the_unstableAI::DoHandleBeamHelpers(), instance_draktharon_keep::DoHandleCrystal(), npc_general_andorovAI::DoInitializeFollowers(), instance_stratholme::DoMoveBackDefenders(), instance_karazhan::DoMoveChessPieceToSides(), boss_razorscaleAI::DoMoveEngineersToHarpoon(), boss_nightbaneAI::DoMoveToClosestTrigger(), npc_general_andorovAI::DoMoveToEventLocation(), instance_blood_furnace::DoNextBroggokEventPhase(), npc_flame_of_azzinothAI::DoPickChargeTarget(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), instance_karazhan::DoPrepareChessEvent(), boss_skadiAI::DoPrepareForGauntlet(), instance_blackrock_spire::DoProcessEmberseerEvent(), boss_anubarak_trialAI::DoRefreshSpheres(), instance_violet_hold::DoReleaseBoss(), world_map_ebon_hold::DoResetBattleScene(), instance_uldaman::DoResetKeeperEvent(), instance_scholomance::DoRespawnEntranceRoom(), boss_halazziAI::DoReuniteSpirits(), boss_lady_deathwhisperAI::DoSelectRandomCultist(), instance_trial_of_the_champion::DoSendChampionsToExit(), instance_trial_of_the_champion::DoSendNextArenaWave(), instance_ruins_of_ahnqiraj::DoSendNextArmyWave(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_trial_of_the_champion::DoSetChamptionsInCombat(), instance_trial_of_the_crusader::DoSetCrusadersInCombat(), boss_taldaramAI::DoSetSpheresInMotion(), boss_kelidan_the_breakerAI::DoSetupAdds(), instance_culling_of_stratholme::DoSetupEntranceSoldiers(), instance_blood_furnace::DoSortBroggokOrcs(), instance_sunwell_plateau::DoSortFlightTriggers(), instance_draktharon_keep::DoSortNovosDummies(), instance_blackrock_spire::DoSortRoomEventMobs(), boss_lady_deathwhisperAI::DoSortSummoningStalkers(), instance_stratholme::DoSortZiggurats(), boss_thorimAI::DoSpawnArenaDwarf(), npc_drijyaAI::DoSpawnCreature(), instance_violet_hold::DoSpawnIntroMob(), boss_ossirianAI::DoSpawnNextCrystal(), npc_meteor_strike_initialAI::DoStartFlameStrikes(), npc_valentine_boss_managerAI::DoStartValentineEvent(), boss_lady_deathwhisperAI::DoSummonCultistWave(), boss_trollgoreAI::DoSummonDrakkariInvaders(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), boss_headless_horsemanAI::DoTossHead(), npc_anubisath_sentinelAI::DoTransferAbility(), npc_anachronos_the_ancientAI::DoUnsummonArmy(), instance_culling_of_stratholme::DoUpdateZombieResidents(), boss_warbringer_omroggAI::DoYellForThreat(), instance_sunwell_plateau::DropFog(), EffectDummyCreature_spell_summon_reflections(), EffectScriptEffectCreature_npc_putricide(), boss_anzuAI::EnableBirdHelpers(), npc_adyen_the_lightwardenAI::EndEvent(), FormationMap::EngageInBlackTempleAssault(), boss_nightbaneAI::EnterEvadeMode(), npc_tirion_fordringAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), npc_anubisath_sentinelAI::EnterEvadeMode(), npc_precious_the_devourerAI::EnterEvadeMode(), npc_beast_combat_stalkerAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), boss_vazruden_heraldAI::EnterEvadeMode(), npc_manaforge_spawnAI::EnterEvadeMode(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_sladranAI::ExecuteAction(), boss_zarithrianAI::ExecuteAction(), boss_sjonnirAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), npc_adyen_the_lightwardenAI::ExecuteTimer(), npc_apprentice_mirvedaAI::FailEvent(), npc_twiggy_flatheadAI::FailEvent(), npc_adyen_the_lightwardenAI::FailEvent(), instance_shattered_halls::FailGauntlet(), instance_sunwell_plateau::FailKiljaeden(), instance_sethekk_halls::FinishAnzuIntro(), world_map_outland::FinishPhase(), npc_raging_flamesAI::FixateRandomTarget(), npc_regthar_deathgateAI::ForceDespawn(), boss_gormokAI::GetActiveSnobold(), WorldState::GetActiveZones(), GetAnyTypeCreature(), BattlefieldWG::GetBattlefieldReady(), instance_uldaman::GetClosestDwarfNotInCombat(), boss_thorimAI::GetClosestLowerBunny(), instance_culling_of_stratholme::GetCratesBunnyOrderedList(), LootMgr::GetLoot(), npc_chess_piece_genericAI::GetMovementSquare(), instance_draktharon_keep::GetNextCrystalTarget(), Player::GetObjectByTypeMask(), ScriptAction::GetScriptCommandObject(), ScriptAction::GetScriptProcessTargets(), ScriptedInstance::GetSingleCreatureFromStorage(), BattleGround::GetSingleCreatureFromStorage(), npc_squire_roweAI::GetSpeakerByEntry(), npc_taelan_fordringAI::GetSpeakerByEntry(), npc_keeper_remulosAI::GetSpeakerByEntry(), npc_grark_lorkrubAI::GetSpeakerByEntry(), npc_anachronos_the_ancientAI::GetSpeakerByEntry(), npc_ranshallaAI::GetSpeakerByEntry(), npc_shaheenAI::GetSpeakerByEntry(), npc_anchorite_baradaAI::GetSpeakerByEntry(), npc_spawned_oronok_tornheartAI::GetSpeakerByEntry(), instance_draktharon_keep::GetSummonDummy(), npc_air_force_botsAI::GetSummonedGuard(), npc_chess_piece_genericAI::GetTargetByType(), Unit::GetTotem(), GetValidNPCsOfList(), GetWorldObject(), world_map_kalimdor::GhostOPlasmEventStep(), WorldState::HandleActiveZone(), mob_torlothAI::HandleAnimation(), WorldSession::HandleAreaSpiritHealerQueryOpcode(), WorldSession::HandleAreaSpiritHealerQueueOpcode(), npc_doomguard_punisherAI::HandleAttackDelay(), npc_shivan_assassinAI::HandleAttackDelay(), npc_eye_of_shartuulAI::HandleAttackDelay(), npc_dreadmawAI::HandleAttackDelay(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), Aura::HandleAuraDummy(), instance_blackrock_depths::HandleBarPatrol(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirEnemyAttack(), WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleBattlemasterJoinArena(), PlayerbotAI::HandleBotOutgoingPacket(), boss_felmystAI::HandleBreath(), boss_lady_vashjAI::HandleCoilfangElite(), boss_lady_vashjAI::HandleCoilfangStrider(), instance_scholomance::HandleDawnGambitEvent(), ChatHandler::HandleDebugDbscriptGuided(), ChatHandler::HandleDebugDbscriptSourced(), ChatHandler::HandleDebugDbscriptTargeted(), BattlefieldWG::HandleDestructibleBuildingEvent(), boss_ahuneAI::HandleEmerge(), boss_lady_vashjAI::HandleEnchantedElemental(), boss_vaelastraszAI::HandleIntro(), ChatHandler::HandleNpcDeleteCommand(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcWhisperCommand(), boss_gothikAI::HandleOpenGates(), boss_majordomoAI::HandleOutro(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_felmystAI::HandlePreBreath(), mob_phoenix_tkAI::HandleRebirth(), mob_shadowmoon_channelerAI::HandleSetup(), world_map_outland::HandleShartuulAddAttack(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulEventReset(), world_map_outland::HandleShartuulSpawnSequence(), boss_muruAI::HandleSpawnAttack(), boss_high_astromancer_solarianAI::HandleSplitAgents(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_lady_vashjAI::HandleTaintedElemental(), ChildTbcAI::HandleTripToTheDarkPortal(), ChatHandler::HandleWpShowCommand(), instance_sunwell_plateau::ImpYell(), instance_trial_of_the_champion::InformChampionReachHome(), npc_anubisath_sentinelAI::InitSentinelsNear(), instance_trial_of_the_champion::IsArenaChallengeComplete(), CreatureGroup::IsEvading(), CreatureGroup::IsOutOfCombat(), go_fel_cannonball_stack_trap::JustDespawned(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), npc_squire_roweAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), npc_grark_lorkrubAI::JustDidDialogueStep(), npc_barnesAI::JustDidDialogueStep(), npc_kiljaeden_controllerAI::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), npc_blastmaster_emi_shortfuseAI::JustDied(), npc_chess_piece_genericAI::JustDied(), boss_headless_horsemanAI::JustDied(), boss_anetheronAI::JustDied(), npc_thrall_old_hillsbradAI::JustDied(), npc_simone_seductressAI::JustDied(), boss_gormokAI::JustDied(), dummy_dragonAI::JustDied(), boss_sjonnirAI::JustDied(), npc_flash_freezeAI::JustDied(), boss_ymironAI::JustDied(), boss_supremusAI::JustDied(), npc_soulgrinderAI::JustDied(), boss_warbringer_omroggAI::JustDied(), npc_anchorite_baradaAI::JustDied(), npc_vindicator_sedaiAI::JustDied(), npc_salhadaarAI::JustDied(), npc_scrapped_fel_reaverAI::JustDied(), mob_torlothAI::JustDied(), PallidHorrorAI::JustDied(), npc_keeper_remulosAI::JustDied(), boss_terokkAI::JustDied(), npc_00x09hlAI::JustDied(), npc_oox22feAI::JustDied(), npc_oox17tnAI::JustDied(), Unit::JustKilledCreature(), boss_thermapluggAI::JustReachedHome(), boss_curatorAI::JustReachedHome(), boss_headless_horsemanAI::JustReachedHome(), npc_simone_seductressAI::JustReachedHome(), boss_sjonnirAI::JustReachedHome(), boss_algalonAI::JustReachedHome(), boss_warbringer_omroggAI::JustReachedHome(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_emilyAI::JustSummoned(), npc_storm_tempered_keeperAI::JustSummoned(), npc_warp_gate::JustSummoned(), boss_entropiusAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_archimondeAI::JustSummoned(), boss_terokkAI::JustSummoned(), boss_warbringer_omroggAI::KilledUnit(), Creature::LoadFromDB(), instance_trial_of_the_champion::MoveChampionToHome(), CreatureGroup::MoveHome(), boss_lich_king_horAI::MoveInLineOfSight(), npc_bashir_flesh_fiendAI::MovementInform(), npc_scarlet_ghoulAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_concentrated_bulletAI::MovementInform(), boss_ymironAI::MovementInform(), boss_jedogaAI::MovementInform(), npc_hodir_fury_reticleAI::MovementInform(), npc_decaying_ghoulAI::MovementInform(), npc_cenarion_sparrowhawkAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), boss_lady_vashjAI::MovementInform(), npc_anchorite_baradaAI::MovementInform(), npc_vindicator_sedaiAI::MovementInform(), PointMovementGenerator::MovementInform(), npc_dirty_larryAI::NextStep(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), Sacrifice::OnApply(), world_map_outland::OnCreatureCreate(), instance_underbog::OnCreatureDeath(), instance_ahnkahet::OnCreatureDeath(), instance_eye_of_eternity::OnCreatureDeath(), instance_shadow_labyrinth::OnCreatureDeath(), instance_gundrak::OnCreatureEnterCombat(), instance_zulaman::OnCreatureEvade(), instance_azjol_nerub::OnCreatureRespawn(), TriggerKTAdd::OnEffectExecute(), SummonZombieChow::OnPeriodicTrigger(), instance_blood_furnace::OnPlayerEnter(), instance_halls_of_stone::OnPlayerEnter(), PallidHorrorAI::OnRemoveFromWorld(), AddCreatureToRemoveListInMapsWorker::operator()(), GameEventUpdateCreatureDataInMapsWorker::operator()(), npc_doctorAI::PatientSaved(), PlayerbotAI::PickPocket(), instance_forge_of_souls::ProcessEventNpcs(), instance_halls_of_stone::ProcessFaceSpell(), instance_halls_of_stone::ProcessFaceSummon(), instance_dire_maul::ProcessForceFieldOpening(), CreatureLinkingHolder::ProcessSlaveGuidList(), world_map_outland::ProgressShartuul(), boss_illidan_stormrageAI::ReceiveAIEvent(), npc_amanishi_scoutAI::ReceiveAIEvent(), boss_professor_putricideAI::ReceiveAIEvent(), npc_creature_generatorAI::ReceiveAIEvent(), mob_phoenix_tkAI::ReceiveAIEvent(), npc_chess_piece_genericAI::ReceiveAIEvent(), boss_razorscaleAI::ReceiveAIEvent(), boss_general_vezaxAI::ReceiveAIEvent(), mob_soaring_eagleAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), npc_dawnblade_blood_knight::ReceiveAIEvent(), npc_bt_battle_sensor::ReinforceAldorScryerFrontline(), FormationData::Reset(), npc_kelerun_bloodmournAI::Reset(), boss_aranAI::Reset(), boss_anetheronAI::Reset(), npc_concentrated_bulletAI::Reset(), boss_exarch_maladaarAI::Reset(), npc_warp_gate::Reset(), npc_salhadaarAI::Reset(), npc_doctorAI::Reset(), npc_manaforge_control_consoleAI::ResetControlConsoleAndDespawn(), instance_violet_hold::ResetEvent(), instance_sunwell_plateau::ResetGauntlet(), instance_violet_hold::ResetGuards(), instance_azjol_nerub::ResetHadronoxTriggers(), instance_violet_hold::ResetIntroPortals(), instance_black_temple::RespawnChannelers(), ScriptedInstance::RespawnDbGuids(), boss_ossirianAI::RespawnFirstCrystal(), instance_mount_hyjal::RetreatBase(), world_map_outland::ScriptAction(), instance_zulgurub::SelectRandomPantherTrigger(), boss_thorimAI::SelectRandomUpperBunny(), BattleGroundSA::SendBattlegroundWarning(), npc_bt_battle_sensor::SendIllidariAttack(), BattleGround::SendMessageToAll(), instance_zulaman::SendNextBearWave(), WorldSession::SendTaxiStatus(), BattlefieldWG::SendWintergraspWarning(), OutdoorPvPZM::SetBeaconArtKit(), instance_stratholme::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), instance_blackrock_depths::SetData(), instance_blackrock_spire::SetData(), instance_blackwing_lair::SetData(), instance_magisters_terrace::SetData(), world_map_ebon_hold::SetData(), instance_scarlet_monastery::SetData(), instance_sunwell_plateau::SetData(), instance_zulaman::SetData(), instance_old_hillsbrad::SetData(), instance_onyxias_lair::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_ahnkahet::SetData(), instance_trial_of_the_champion::SetData(), instance_draktharon_keep::SetData(), instance_gundrak::SetData(), instance_forge_of_souls::SetData(), instance_pit_of_saron::SetData(), instance_icecrown_citadel::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_pinnacle::SetData(), instance_serpentshrine_cavern::SetData(), instance_steam_vault::SetData(), instance_magtheridons_lair::SetData(), instance_arcatraz::SetData(), instance_blackwing_lair::SetData64(), mob_arugal_voidwalkerAI::SetFollower(), BattleGroundSA::SetupGraveyards(), boss_volkhanAI::ShatterGolems(), instance_dire_maul::SortPylonGuards(), instance_mount_hyjal::SpawnBase(), npc_soulgrinderAI::SpawnCreature(), instance_serpentshrine_cavern::SpawnFishCorpses(), instance_sunwell_plateau::SpawnGauntlet(), instance_mount_hyjal::SpawnInfernal(), boss_ahuneAI::SpellHit(), npc_warp_gate::SpellHit(), npc_injured_patientAI::SpellHit(), instance_magisters_terrace::StartCrystalVisual(), npc_dawnblade_blood_knight::StartDuel(), npc_adyen_the_lightwardenAI::StartEvent(), instance_sunwell_plateau::StartImps(), instance_sunwell_plateau::StartMiniEvent(), boss_majordomoAI::StartSummonEvent(), npc_dawnblade_blood_knight::StopDuel(), instance_sunwell_plateau::StopImps(), npc_soulgrinderAI::SummonedCreatureDespawn(), boss_jedogaAI::SummonedCreatureJustDied(), npc_emilyAI::SummonedCreatureJustDied(), boss_varosAI::SummonedCreatureJustDied(), boss_kologarnAI::SummonedCreatureJustDied(), npc_soulgrinderAI::SummonedCreatureJustDied(), boss_akilzonAI::SummonedCreatureJustDied(), npc_emilyAI::SummonedMovementInform(), npc_xiri::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), boss_kelthuzadAI::SummonIntroCreatures(), WorldState::SummonMouth(), WorldState::SummonPallid(), boss_gurtogg_bloodboilAI::SwitchPhase(), instance_stratholme::ThazudinAcolyteJustDied(), SpawnGroup::to_string(), CreatureGroup::TriggerLinkingEvent(), CreatureLinkingHolder::TryFollowMaster(), npc_commander_dawnforgeAI::TurnToEachOther(), npc_commander_dawnforgeAI::TurnToPathaleonsImage(), OutdoorPvPEP::UnsummonFlightMaster(), boss_majordomoAI::UnsummonMajordomoAdds(), OutdoorPvPEP::UnsummonSoldiers(), instance_blackwing_lair::Update(), instance_deadmines::Update(), instance_karazhan::Update(), instance_shadowfang_keep::Update(), instance_stratholme::Update(), instance_sunwell_plateau::Update(), instance_uldaman::Update(), instance_dire_maul::Update(), instance_zulfarrak::Update(), instance_azjol_nerub::Update(), instance_trial_of_the_champion::Update(), instance_halls_of_stone::Update(), instance_pinnacle::Update(), instance_halls_of_reflection::Update(), instance_pit_of_saron::Update(), instance_ulduar::Update(), boss_eranikusAI::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), boss_pyroguard_emberseerAI::UpdateAI(), npc_kelerun_bloodmournAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_tethyrAI::UpdateAI(), npc_twiggy_flatheadAI::UpdateAI(), npc_precious_the_devourerAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), boss_jedogaAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_sinkhole_kill_creditAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), boss_icehowlAI::UpdateAI(), npc_king_ymironAI::UpdateAI(), boss_sartharionAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_freyaAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), boss_heart_deconstructorAI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), boss_ymironAI::UpdateAI(), boss_murmurAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), npc_bird_spiritAI::UpdateAI(), npc_warp_gate::UpdateAI(), npc_soulgrinderAI::UpdateAI(), npc_supplicantAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), npc_commander_dawnforgeAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), npc_doctorAI::UpdateAI(), npc_injured_patientAI::UpdateAI(), npc_warlock_mount_ritualAI::UpdateAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_harrison_jones_zaAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_harrison_jonesAI::UpdateEscortAI(), npc_runic_colossusAI::UpdateRunicSmash(), BattlefieldWG::UpdateTenacities(), npc_scrap_reaverAI::UpdateTimers(), npc_ranger_lilathaAI::WaypointReached(), npc_tirion_fordringAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), and npc_drijyaAI::WaypointReached().
GetCreature() [2/2]
Creature * Map::GetCreature (uint32 dbguid) const
Definition at line 2349 of file Map.cpp.
References HIGHGUID_UNIT, and m_dbGuidObjects.
GetCreatureByEntry()
Creature* Map::GetCreatureByEntry (uint32 entry)
GetCreatureLinkingHolder()
CreatureLinkingHolder* Map::GetCreatureLinkingHolder () inline
Definition at line 350 of file Map.h.
References m_creatureLinkingHolder.
Referenced by CanSpawn(), Creature::Create(), Unit::JustKilledCreature(), Creature::LoadFromDB(), Creature::RemoveCorpse(), WorldObject::SummonCreature(), Unit::TakePossessOf(), Unit::TriggerAggroLinkingEvent(), Unit::TriggerEvadeEvents(), Unit::TriggerHomeEvents(), and Creature::Update().
GetCreatures() [1/2]
std::vector< Creature * > const * Map::GetCreatures (std::string stringId) const
Definition at line 2383 of file Map.cpp.
References GetMapDataContainer().
Referenced by Spell::CheckScriptTargeting(), and OCWAuchindounSummonAdventurer::OnSummon().
GetCreatures() [2/2]
std::vector< Creature * > const * Map::GetCreatures (uint32 stringId) const
Definition at line 2402 of file Map.cpp.
References m_objectsPerStringId.
GetCurrentClockTime()
TimePoint Map::GetCurrentClockTime () const
Definition at line 86 of file Map.cpp.
References World::GetCurrentClockTime().
Referenced by Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Pet::_SaveSpellCooldowns(), SpawnManager::AddCreature(), SpawnManager::AddGameObject(), boss_alythessAI::Aggro(), boss_sacrolashAI::Aggro(), AreaTrigger_at_beggar(), Creature::CanRestockPickpocketLoot(), ChangeMapDifficulty(), Unit::CharmCooldownInitialize(), DynamicObject::Create(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), WorldObject::GetGCD(), SpawnManager::GetRespawnList(), WorldSession::HandleChangePlayerDifficulty(), WorldObject::HasGCD(), Creature::InspectingLoot(), Creature::IsCorpseExpired(), world_map_northrend::IsDalaranCooldownForPlayer(), TemporarySpawn::IsExpired(), BattleGroundWS::IsFlagHeldFor45Seconds(), WorldObject::IsSpellOnPermanentCooldown(), WorldObject::IsSpellReady(), LFGMgr::JoinLfg(), Player::LockOutSpells(), instance_sunwell_plateau::OnCreatureDeath(), WorldObject::PrintCooldownList(), Unit::ProcDamageAndSpellFor(), BattleGroundWS::ProcessFlagPickUpFromBase(), Creature::ReduceCorpseDecayTimer(), Pet::ResetCorpseRespawn(), instance_sunwell_plateau::ResetGauntlet(), SpawnManager::RespawnCreature(), SpawnManager::RespawnGameObject(), ScriptCommandStart(), ScriptsProcess(), ScriptsStart(), Player::SendInitialSpells(), world_map_northrend::SetDalaranCooldownTime(), instance_icecrown_citadel::SetData(), Creature::SetDeathState(), TemporarySpawn::SetDeathState(), TemporarySpawn::SetSummonProperties(), npc_regthar_deathgateAI::SpawnCreature(), Creature::StartPickpocketRestockTimer(), npc_regthar_deathgateAI::SummonedCreatureJustDied(), SpawnManager::Update(), and TemporarySpawn::Update().
GetCurrentDiff()
uint32 Map::GetCurrentDiff () const
Definition at line 91 of file Map.cpp.
References World::GetCurrentDiff().
Referenced by Player::AddGCD().
GetCurrentMSTime()
uint32 Map::GetCurrentMSTime () const
Definition at line 81 of file Map.cpp.
References World::GetCurrentMSTime().
Referenced by Object::BuildMovementUpdate(), Spell::cast(), WorldSession::HandlePetActionHelper(), Spell::SendSpellGo(), GenericTransport::SetGoState(), Spell::Spell(), SpellAuraHolder::SpellAuraHolder(), ElevatorTransport::Update(), Transport::Update(), and Spell::update().
GetCurrentTime_t()
time_t Map::GetCurrentTime_t () const
Definition at line 96 of file Map.cpp.
References m_curTime.
GetCurrentTime_tm()
tm Map::GetCurrentTime_tm () const
Definition at line 101 of file Map.cpp.
References m_curTimeTm.
GetDifficulty()
Difficulty Map::GetDifficulty () const inline
Definition at line 216 of file Map.h.
References GetSpawnMode().
Referenced by Group::_homebindIfInstance(), DungeonMap::Add(), CanSpawn(), CreatureLinkingHolder::CanSpawn(), Spell::CheckCast(), MapManager::CreateInstance(), Spell::EffectDummy(), Player::GetAreaTriggerLockStatus(), GetMapDifficulty(), Aura::HandleAuraDummy(), WorldSession::HandleChangePlayerDifficulty(), CreatureEventAI::InitAI(), Initialize(), WorldStateVariableManager::Initialize(), instance_trial_of_the_crusader::Is25ManDifficulty(), instance_icecrown_citadel::Is25ManDifficulty(), instance_ruby_sanctum::Is25ManDifficulty(), instance_trial_of_the_crusader::IsHeroicDifficulty(), instance_icecrown_citadel::IsHeroicDifficulty(), instance_ruby_sanctum::IsHeroicDifficulty(), IsRaidOrHeroicDungeon(), IsRegularDifficulty(), npc_beast_combat_stalkerAI::JustSummoned(), ConflagrationTargeting::OnInit(), SummonZombieChow::OnPeriodicTrigger(), DungeonMap::PermBindAllPlayers(), npc_beast_combat_stalkerAI::Reset(), Player::SendInitialPacketsBeforeAddToMap(), instance_eye_of_eternity::SetData(), SpawnGroup::Spawn(), Spell::Spell(), and Aura::TriggerSpell().
GetDynamicObject()
DynamicObject * Map::GetDynamicObject (ObjectGuid guid)
Function return dynamic object that in world at CURRENT map.
Parameters
guid must be dynamic object guid (HIGHGUID_DYNAMICOBJECT)
Definition at line 2280 of file Map.cpp.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), and m_objectsStore.
Referenced by Spell::GetAffectiveCasterObject(), Spell::GetCastingObject(), Unit::GetDynObject(), Player::GetObjectByTypeMask(), GetWorldObject(), and Unit::RemoveDynObject().
GetEntry()
MapEntry const* Map::GetEntry () const inline
Definition at line 225 of file Map.h.
References i_mapEntry.
Referenced by WorldSession::HandleChangePlayerDifficulty(), WorldSession::HandleSetRaidDifficultyOpcode(), and Group::SendUpdateTo().
GetGameObject() [1/2]
GameObject * Map::GetGameObject (ObjectGuid guid)
Function return gameobject that in world at CURRENT map.
Parameters
guid must be gameobject guid (HIGHGUID_GAMEOBJECT)
Definition at line 2270 of file Map.cpp.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), and m_objectsStore.
Referenced by PlayerbotAI::_HandleCommandFind(), PlayerbotAI::_HandleCommandSurvey(), PlayerbotAI::_HandleCommandUse(), instance_halls_of_stone::ActivateFace(), Unit::AddWildGameObject(), boss_ouroAI::Burrow(), PlayerbotAI::CastSpell(), BattleGround::ChangeBgObjectSpawnState(), PlayerbotAI::CheckBotCast(), Player::CheckDuelDistance(), Spell::CheckScriptTargeting(), instance_blackwing_lair::CleanupNefarianStage(), GameObjectGroup::Despawn(), UnitAI::DespawnGuids(), ScriptedInstance::DespawnGuids(), instance_black_temple::DespawnImpalingSpines(), WorldState::DespawnWarEffortGuids(), Spell::DoAllEffectOnTarget(), world_map_kalimdor::DoDespawnElementalRifts(), boss_razorscaleAI::DoMoveEngineersToHarpoon(), BattleGround::DoorClose(), BattleGround::DoorOpen(), ScriptedInstance::DoRespawnGameObject(), instance_blood_furnace::DoSortBroggokOrcs(), instance_draktharon_keep::DoSortNovosDummies(), instance_blackrock_spire::DoSortRoomEventMobs(), instance_stratholme::DoSortZiggurats(), ScriptedInstance::DoToggleGameObjectFlags(), instance_naxxramas::DoTriggerHeiganTraps(), ScriptedInstance::DoUseDoorOrButton(), instance_blackrock_spire::DoUseEmberseerRunes(), npc_demolitionist_legosoAI::DoUseExplosiveTraps(), Spell::EffectSummonObject(), instance_serpentshrine_cavern::EngageBossConsole(), instance_serpentshrine_cavern::EngageBridgeConsole(), boss_ouroAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::extractGOinfo(), instance_shattered_halls::FailGauntlet(), Spell::GetAffectiveCasterObject(), BattlefieldWG::GetBattlefieldReady(), Spell::GetCastingObject(), Unit::GetGameObject(), ChatHandler::GetGameObjectWithGuid(), GameObject::GetLinkedTrap(), LootMgr::GetLoot(), Player::GetNextQuest(), Player::GetObjectByTypeMask(), ScriptAction::GetScriptCommandObject(), ScriptAction::GetScriptProcessTargets(), BattleGround::GetSingleGameObjectFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GameObject::GetSpawner(), GetTransport(), GetWorldObject(), world_map_kalimdor::GhostOPlasmEventStep(), npc_razorthorn_ravager_pet::HandleAnimations(), PlayerbotAI::HandleBotOutgoingPacket(), BattlefieldWG::HandleDestructibleBuildingEvent(), BattleGroundSA::HandleEvent(), WorldSession::HandleGameobjectReportUse(), ChatHandler::HandleGameObjectRespawnCommand(), ChatHandler::HandleGameObjectTargetCommand(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleLootOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), OutdoorPvPHP::HandlePlayerKillInsideArea(), OutdoorPvPZM::HandlePlayerKillInsideArea(), world_map_outland::HandleShartuulEventReset(), BattleGround::HandleTriggerBuff(), npc_ranshallaAI::JustDidDialogueStep(), boss_ouroAI::JustReachedHome(), boss_yorAI::JustRespawned(), npc_ethereum_prisoner_dungeonAI::JustRespawned(), npc_ethereum_prisonerAI::JustRespawned(), GameObject::LoadFromDB(), OutdoorPvPNA::LockHalaa(), OutdoorPvPGH::LockLighthouse(), OutdoorPvPTF::LockTowers(), BattlefieldWG::LockWorkshops(), npc_nesingwary_trapperAI::MoveInLineOfSight(), npc_snufflenose_gopherAI::MovementInform(), npc_nesingwary_trapperAI::MovementInform(), instance_blood_furnace::OnPlayerEnter(), NamreebAnticheat::Movement::OnTransport(), AddGameObjectToRemoveListInMapsWorker::operator()(), Player::PrepareQuestMenu(), instance_dire_maul::ProcessDreadsteedRitualStart(), world_map_outland::ProgressShartuul(), npc_ice_spear_bunnyAI::ReceiveAIEvent(), instance_halls_of_stone::ResetFace(), OutdoorPvPTF::ResetTowers(), OutdoorPvP::RespawnGO(), npc_drijyaAI::RespawnGo(), boss_zumrahAI::SelectNearbyShallowGrave(), Spell::SendChannelStart(), Player::SendQuestGiverStatusMultiple(), OutdoorPvP::SetBannerVisual(), instance_zulgurub::SetData(), instance_gnomeregan::SetData(), instance_sunken_temple::SetData(), instance_dire_maul::SetData(), instance_ruins_of_ahnqiraj::SetData(), instance_pit_of_saron::SetData(), instance_ruby_sanctum::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_magtheridons_lair::SetData(), instance_blackwing_lair::SetData64(), instance_halls_of_stone::SortFaces(), instance_dire_maul::SortPylonGuards(), npc_warp_gate::SpellHit(), boss_kurinnaxxAI::TriggerTrap(), OutdoorPvPNA::UnlockHalaa(), OutdoorPvPGH::UnlockLighthouse(), instance_blackwing_lair::Update(), world_map_ebon_hold::Update(), instance_sunken_temple::Update(), instance_dire_maul::Update(), instance_blood_furnace::Update(), instance_shattered_halls::Update(), GameObjectAura::Update(), Spell::update(), instance_halls_of_reflection::Update(), SpellCastTargets::Update(), boss_thermapluggAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), npc_nature_bombAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), instance_violet_hold::UpdateCellForBoss(), npc_maxx_a_million_escortAI::UpdateEscortAI(), Spell::UpdateOriginalCasterPointer(), npc_ranger_lilathaAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_ranshallaAI::WaypointReached(), npc_galen_goodwardAI::WaypointStart(), and npc_stinky_ignatzAI::WaypointStart().
GetGameObject() [2/2]
GameObject * Map::GetGameObject (uint32 dbguid) const
Definition at line 2366 of file Map.cpp.
References HIGHGUID_GAMEOBJECT, and m_dbGuidObjects.
GetGameObjects() [1/2]
std::vector< GameObject * > const * Map::GetGameObjects (std::string stringId) const
Definition at line 2388 of file Map.cpp.
References GetMapDataContainer().
Referenced by Spell::CheckScriptTargeting().
GetGameObjects() [2/2]
std::vector< GameObject * > const * Map::GetGameObjects (uint32 stringId) const
Definition at line 2411 of file Map.cpp.
References m_objectsPerStringId.
GetGraveyardManager()
GraveyardManager& Map::GetGraveyardManager () inline
Definition at line 396 of file Map.h.
References m_graveyardManager.
Referenced by BattleGroundIC::DoApplyObjectiveBenefits(), BattleGroundIC::DoResetObjective(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleNearGraveCommand(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundAV::InitializeNode(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundAB::ProcessNodeCapture(), BattleGroundAV::ProcessPlayerAssaultsPoint(), BattleGroundAV::ProcessPlayerDestroyedPoint(), Player::RepopAtGraveyard(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundWS::Reset(), WorldSession::SendSpiritResurrect(), Player::SetBattleGroundEntryPoint(), OutdoorPvP::SetGraveYardLinkTeam(), BattleGroundSA::SetupBattleground(), BattleGroundAB::StartingEventOpenDoors(), BattleGroundEY::StartingEventOpenDoors(), and BattleGroundWS::StartingEventOpenDoors().
GetGridExpiry()
time_t Map::GetGridExpiry (void) const inline
Definition at line 197 of file Map.h.
References i_gridExpiry.
GetHeight()
float Map::GetHeight (uint32 phasemask, float x, float y, float z, bool swim = false) const
Definition at line 2663 of file Map.cpp.
References DEFAULT_HEIGHT_SEARCH, DEFAULT_WATER_SEARCH, DynamicMapTree::getHeight(), TerrainInfo::GetHeightStatic(), m_dyn_tree, and m_TerrainData.
Referenced by Unit::AdjustZForCollision(), EffectAuraDummy_npc_scourged_flamespitter(), NamreebAnticheat::Movement::ExtrapolateMovement(), GetRandomPointInTheAir(), GetRandomPointUnderWater(), ChatHandler::HandleGoHelper(), ChatHandler::HandleGPSCommand(), Unit::IsAboveGround(), MotionMaster::MoveFall(), SummonVoidSentinelSummoner::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), boss_onyxiaAI::UpdateAI(), boss_brundirAI::UpdateAI(), WorldObject::UpdateAllowedPositionZ(), Unit::UpdateAllowedPositionZ(), and WorldObject::UpdateGroundPositionZ().
GetHeightInRange()
bool Map::GetHeightInRange (uint32 phasemask, float x, float y, float & z, float maxSearchDist = 4.0f) const
Definition at line 2608 of file Map.cpp.
References VMAP::VMapFactory::createOrGetVMapManager(), DynamicMapTree::getHeight(), VMAP::IVMapManager::getHeight(), i_id, INVALID_HEIGHT_VALUE, VMAP::IVMapManager::isLineOfSightCalcEnabled(), m_dyn_tree, m_TerrainData, and VMAP_INVALID_HEIGHT_VALUE.
Referenced by PlayerbotClassAI::FleeFromPointIfCan(), GetReachableRandomPointOnGround(), world_map_kalimdor::GhostOPlasmEventStep(), and Spell::SetTargetMap().
GetHitPosition()
bool Map::GetHitPosition (float srcX, float srcY, float srcZ, float & destX, float & destY, float & destZ, uint32 phasemask, float modifyDist) const
get the hit position and return true if we hit something (in this case the dest position will hold the hit-position) otherwise the result pos will be the dest pos
Definition at line 2583 of file Map.cpp.
References VMAP::VMapFactory::createOrGetVMapManager(), GetId(), DynamicMapTree::getObjectHitPos(), VMAP::IVMapManager::getObjectHitPos(), and m_dyn_tree.
Referenced by Spell::EffectSummonType(), PlayerbotClassAI::FleeFromPointIfCan(), GetReachableRandomPointOnGround(), Unit::KnockBackWithAngle(), WorldObject::MovePositionToFirstCollision(), and Spell::SetTargetMap().
GetId()
uint32 Map::GetId (void) const inline
Definition at line 198 of file Map.h.
References i_id.
Referenced by Group::_homebindIfInstance(), DungeonMap::Add(), AddObjectToRemoveList(), BrewfestEvent::BrewfestEvent(), ChangeGOPathfinding(), InstanceData::CheckAchievementCriteriaMeet(), InstanceData::CheckConditionCriteriaMeet(), GameObject::Create(), CreateInstanceData(), DoOrSimulateScriptTextForMap(), ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), ConditionEntry::Evaluate(), Group::GetBoundInstance(), GetCorpse(), GetHitPosition(), GetMapDifficulty(), ScriptAction::GetScriptProcessTargets(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleListAreaTriggerCommand(), ChatHandler::HandleNpcAddCommand(), SpawnManager::Initialize(), Initialize(), WorldStateVariableManager::Initialize(), IsDynguidForced(), IsInLineOfSight(), IsMountAllowed(), ObjectMgr::LoadActiveEntities(), Player::LoadFromDB(), LoadMapAndVMap(), ObjectGridLoader::LoadN(), Transport::LoadTransport(), LoadTransports(), ConditionEntry::Meets(), MotionMaster::MoveFall(), DungeonMap::PermBindAllPlayers(), DungeonMap::Reset(), InstanceData::SaveToDB(), DungeonMap::SendResetWarnings(), Creature::SetInCombatWithZone(), WorldObject::SetMap(), SetNavTile(), DungeonMap::SetResetSchedule(), DialogueHelper::StartNextDialogueText(), IdleState::Update(), RemovalState::Update(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
GetInstanceData()
InstanceData* Map::GetInstanceData () const inline
Definition at line 331 of file Map.h.
References i_data.
Referenced by AreaTrigger_at_ghazan_surface(), AreaTrigger_at_naturalist_bite(), AreaTrigger_at_teron_gorefiend(), boss_festergutAI::boss_festergutAI(), boss_tethyrAI::boss_tethyrAI(), CreatureLinkingHolder::CanSpawn(), Creature::Create(), GameObject::Create(), boss_tethyrAI::DoEncounterCleanup(), ConditionEntry::Evaluate(), Player::GetAreaTriggerLockStatus(), WorldObject::GetInstanceData(), GossipHello_npc_adyen_the_lightwarden(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleInstanceSaveDataCommand(), ChatHandler::HandleSD2HelpCommand(), ChatHandler::HandleSD2ScriptCommand(), boss_tethyrAI::KilledUnit(), npc_skyguard_aether_techAI::MovementInform(), npc_skyguard_rangerAI::MovementInform(), npc_Shattered_Hand_Scout::MovementInform(), NecropolisHealthAI::NecropolisHealthAI(), NecroticShard::NecroticShard(), HodirsProtectiveGaze::OnAbsorb(), SnakeWrap::OnApply(), PossessDemonShartuul::OnEffectExecute(), SmashShield::OnEffectExecute(), GameEventMgr::OnEventHappened(), go_ai_larva_spewer::OnLootStateChange(), go_ai_suppression::OnLootStateChange(), ProcessEventIdRazorgorePossess(), ProcessEventTransports(), QuestAccept_npc_major_mills(), npc_adyen_the_lightwardenAI::StartEvent(), go_infernaling_summoner_portal_hound::UpdateAI(), and go_infernaling_summoner::UpdateAI().
GetInstanceId()
uint32 Map::GetInstanceId () const inline
Definition at line 207 of file Map.h.
References i_InstanceId.
Referenced by DungeonMap::Add(), ObjectAccessor::AddCorpsesToGrid(), AddObjectToRemoveList(), BattleGroundMap::CanEnter(), ChangeGOPathfinding(), GetCorpse(), BattleGround::GetInstanceId(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleNamegoCommand(), Initialize(), LoadHelper(), LoadMapAndVMap(), DungeonMap::Remove(), BattleGroundMap::Remove(), InstanceData::SaveToDB(), WorldObject::SetMap(), SetNavTile(), DungeonMap::SetResetSchedule(), and ~Map().
GetLoadedGridsCount()
uint32 Map::GetLoadedGridsCount ()
Definition at line 448 of file Map.cpp.
References GRID_STATE_ACTIVE, i_grids, and MAX_NUMBER_OF_GRIDS.
Referenced by ChatHandler::HandleGridsLoadedCount().
GetMapDataContainer() [1/2]
MapDataContainer& Map::GetMapDataContainer () inline
Definition at line 405 of file Map.h.
References m_dataContainer.
Referenced by WorldObject::AddStringId(), CreatureEventAI::CheckEvent(), GetCreatures(), GetGameObjects(), ScriptAction::GetScriptProcessTargets(), GetWorldObjects(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleReloadCreatureSpellLists(), ChatHandler::HandleReloadEventAIScriptsCommand(), ChatHandler::HandleRespawnCommand(), CreatureEventAI::InitAI(), SpawnManager::Initialize(), Creature::LoadFromDB(), GameObject::LoadFromDB(), ScriptMgr::LoadScriptMap(), ScriptMgr::LoadStringIds(), WorldStateExpressionMgr::Meets(), UnitConditionMgr::Meets(), MaNGOS::RespawnDo::operator()(), WorldObject::RemoveStringId(), ScriptsStart(), and Creature::SetSpellList().
GetMapDataContainer() [2/2]
MapDataContainer const& Map::GetMapDataContainer () const inline
Definition at line 406 of file Map.h.
References m_dataContainer.
GetMapDifficulty()
MapDifficultyEntry const * Map::GetMapDifficulty () const
Definition at line 1238 of file Map.cpp.
References GetDifficulty(), GetId(), and GetMapDifficultyData().
Referenced by GetMaxPlayers(), and GetMaxResetDelay().
GetMapName()
const char * Map::GetMapName () const
Definition at line 1284 of file Map.cpp.
References i_mapEntry, MapEntry::name, and sWorld.
Referenced by DungeonMap::Add(), Unit::GetChannelObject(), Unit::GetCharm(), Unit::GetCharmer(), Unit::GetCreator(), Unit::GetSpawner(), Unit::GetTarget(), ChatHandler::HandleListAreaTriggerCommand(), DungeonMap::Remove(), and BattleGroundMap::Remove().
GetMaxPlayers()
uint32 Map::GetMaxPlayers () const
Definition at line 1264 of file Map.cpp.
References GetMapDifficulty(), GetMapDifficultyData(), i_id, IsRegularDifficulty(), MapDifficultyEntry::maxPlayers, and REGULAR_DIFFICULTY.
Referenced by AchievementMgr::UpdateAchievementCriteria().
GetMaxResetDelay()
uint32 Map::GetMaxResetDelay () const
Definition at line 1279 of file Map.cpp.
References GetMapDifficulty(), and DungeonResetScheduler::GetMaxResetTimeFor().
GetMessager()
Messager<Map>& Map::GetMessager () inline
Definition at line 390 of file Map.h.
References m_messager.
Referenced by OutdoorPvP::BuffTeam(), WorldState::HandleActiveZone(), WorldSession::HandleMoveWorldportAckOpcode(), ChatHandler::HandleReloadCreatureSpellLists(), ChatHandler::HandleReloadEventAIScriptsCommand(), ScriptMgr::LoadScriptMap(), ScriptMgr::LoadStringIds(), WorldState::OnDisable(), OutdoorPvP::SetGraveYardLinkTeam(), WorldState::StartSunsReachPhase(), WorldState::SummonMouth(), WorldState::SummonPallid(), Transport::TeleportTransport(), and Update().
GetNewDifficultyCooldown()
TimePoint const& Map::GetNewDifficultyCooldown () const inline
Definition at line 223 of file Map.h.
References m_dynamicDifficultyCooldown.
Referenced by WorldSession::HandleChangePlayerDifficulty().
getNGrid()
NGridType* Map::getNGrid (uint32 x, uint32 y) const inline private
Definition at line 446 of file Map.h.
References i_grids, MANGOS_ASSERT, and MAX_NUMBER_OF_GRIDS.
Referenced by Add(), AddToActive(), CreatePlayerOnClient(), CreatureCellRelocation(), DynamicObjectRelocation(), EnsureGridCreated(), EnsureGridLoaded(), EnsureGridLoadedAtEnter(), ForceLoadGrid(), GameObjectRelocation(), GetUnloadLock(), isGridObjectDataLoaded(), IsRemovalGrid(), loaded(), PlayerRelocation(), Remove(), RemoveFromActive(), setGridObjectDataLoaded(), SetUnloadLock(), UnloadGrid(), Visit(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
GetObjectsStore()
MapStoredObjectTypesContainer& Map::GetObjectsStore () inline
Definition at line 310 of file Map.h.
References m_objectsStore.
Referenced by Creature::AddToWorld(), DynamicObject::AddToWorld(), GameObject::AddToWorld(), Pet::AddToWorld(), ChangeMapDifficulty(), BattleGround::EndBattleGround(), Creature::RemoveFromWorld(), DynamicObject::RemoveFromWorld(), GameObject::RemoveFromWorld(), and Pet::RemoveFromWorld().
GetPersistentState()
MapPersistentState* Map::GetPersistentState () const inline
Definition at line 240 of file Map.h.
References m_persistentState.
Referenced by Player::BindToInstance(), CreatureGroup::ClearRespawnTimes(), GameObject::Delete(), CreatureGroup::Despawn(), GameObjectGroup::Despawn(), WorldMap::GetPersistanceState(), DungeonMap::GetPersistanceState(), BattleGroundMap::GetPersistanceState(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), ChatHandler::HandleRespawnCommand(), CreatureLinkingHolder::IsRespawnReady(), Creature::LoadFromDB(), GameObject::LoadFromDB(), MaNGOS::RespawnDo::operator()(), FindCreatureData::operator()(), FindGOData::operator()(), SpawnGroup::RemoveObject(), CreatureGroup::RemoveObject(), GameObjectGroup::RemoveObject(), Creature::Respawn(), GameObject::Respawn(), SpawnManager::RespawnAll(), SpawnManager::RespawnCreature(), SpawnManager::RespawnGameObject(), SpawnGroup::RespawnIfInVicinity(), Creature::SaveRespawnTime(), GameObject::SaveRespawnTime(), SpawnGroup::Spawn(), Creature::Update(), GameObject::Update(), and ObjectGridLoader::Visit().
GetPet()
Pet * Map::GetPet (ObjectGuid guid)
Function return pet that in world at CURRENT map.
Parameters
guid must be pet guid (HIGHGUID_PET)
Definition at line 2229 of file Map.cpp.
References TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::find(), and m_objectsStore.
Referenced by Unit::_GetPet(), Spell::CheckCast(), GetAnyTypeCreature(), Unit::GetMiniPet(), Player::GetObjectByTypeMask(), ScriptAction::GetScriptCommandObject(), GetWorldObject(), WorldSession::HandlePetRename(), and Spell::SetTargetMap().
GetPlayer()
Player * Map::GetPlayer (ObjectGuid guid)
Function return player that in world at CURRENT map.
Note: This is function preferred if you sure that need player only placed at specific map This is not true for some spell cast targeting and most packet handlers
Parameters
guid must be player guid (HIGHGUID_PLAYER)
Definition at line 2208 of file Map.cpp.
References ObjectAccessor::FindPlayer(), and WorldObject::GetMap().
Referenced by mob_shadowmoon_soulstealerAI::Aggro(), npc_dragonmaw_racerAI::AttackPlayer(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), boss_black_stalkerAI::boss_black_stalkerAI(), boss_coren_direbrewAI::boss_coren_direbrewAI(), boss_yorAI::boss_yorAI(), WorldState::BuffAdalsSongOfBattle(), WorldState::BuffMagtheridonTeam(), npc_simon_game_bunnyAI::BuffPlayers(), OutdoorPvP::BuffTeam(), npc_lord_illidan_stormrageAI::CheckEventFail(), npc_dirty_larryAI::DamageTaken(), npc_death_knight_initiateAI::DamageTaken(), npc_grand_admiral_westwindAI::DamageTaken(), WorldState::DispelAdalsSongOfBattle(), WorldState::DispelMagtheridonTeam(), npc_eris_havenfireAI::DoBalanceEventEnd(), npc_simon_game_bunnyAI::DoCleanupGame(), npc_simon_game_bunnyAI::DoCompleteLevel(), instance_sunwell_plateau::DoEjectSpectralPlayers(), npc_manaforge_control_consoleAI::DoFailEvent(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), npc_eris_havenfireAI::DoHandlePhaseEnd(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), Spell::EffectBreakPlayerTargeting(), Spell::EffectDummy(), EffectDummyCreature_spell_summon_reflections(), npc_adyen_the_lightwardenAI::EndEvent(), boss_cthunAI::EnterEvadeMode(), npc_apprentice_mirvedaAI::FailEvent(), npc_adyen_the_lightwardenAI::FailEvent(), npc_commanderAI::FailEvent(), npc_dragonmaw_racerAI::FailRace(), npc_dragonmaw_racerAI::FinishRace(), world_map_outland::GetCurrentPlayer(), npc_a_special_surpriseAI::GetDialogueTarget(), npc_death_knight_initiateAI::GetDialogueTarget(), FollowerAI::GetLeaderForFollower(), go_manticron_cubeAI::GetManticronCubeLastUser(), npc_escortAI::GetPlayerForEscort(), npc_adyen_the_lightwardenAI::GetPlayerTarget(), ScriptAction::GetScriptCommandObject(), GetUnit(), GetWorldObject(), WorldSession::HandleAcceptLevelGrant(), mob_torlothAI::HandleAnimation(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), WorldSession::HandleGrantLevel(), instance_ahnkahet::HandleInsanityClear(), instance_ahnkahet::HandleInsanitySwitch(), boss_lady_vashjAI::HandleIntroText(), boss_omor_the_unscarredAI::HandlePullBack(), WorldSession::HandleRideVehicleInteract(), WorldState::HandleSunsReachSubPhaseTransition(), npc_shadowlord_deathwailAI::IsPlayerOrGroupInRangeAndActiveInEvent(), npc_death_knight_initiateAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_valentine_boss_managerAI::JustDidDialogueStep(), npc_lich_king_villageAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_deathstalker_faerleiaAI::JustDied(), npc_web_wrapAI::JustDied(), npc_constrictor_tentacleAI::JustDied(), npc_shadow_demonAI::JustDied(), npc_soulgrinderAI::JustDied(), npc_anchorite_baradaAI::JustDied(), mob_torlothAI::JustDied(), go_imp_in_a_ball::JustSpawned(), npc_eris_havenfireAI::JustSummoned(), boss_volazjAI::JustSummoned(), boss_exarch_maladaarAI::JustSummoned(), npc_lord_illidan_stormrageAI::JustSummoned(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_shadow_demonAI::MovementInform(), npc_grand_admiral_westwindAI::MovementInform(), npc_dragonmaw_racer_skyshatterAI::MovementInform(), npc_dirty_larryAI::NextStep(), npc_commanderAI::npc_commanderAI(), npc_ethereum_prisoner_dungeonAI::npc_ethereum_prisoner_dungeonAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_mage_mirror_imageAI::npc_mage_mirror_imageAI(), FaceRandomTarget::OnCast(), instance_ahnkahet::OnCreatureDeath(), instance_azjol_nerub::OnCreatureRespawn(), SapphironAchievementCheck::OnEffectExecute(), HurtfulStrikePrimer::OnEffectExecute(), npc_doctorAI::PatientDied(), LootTemplate::PlayerOrGroupFulfilsCondition(), CreatureEventAI::ProcessAction(), Player::QueueOrAddResurrectRequest(), npc_major_mills::ReceiveAIEvent(), npc_jennyAI::ReceiveAIEvent(), npc_ghoul_feeding_bunnyAI::ReceiveAIEvent(), npc_arcane_beamAI::Reset(), ScourgeMinion::ScourgeMinion(), npc_twiggy_flatheadAI::SetChallengerReady(), instance_ahnkahet::SetData64(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), npc_private_hendelAI::SpellHit(), npc_deathstalker_faerleiaAI::SummonedCreatureJustDied(), npc_apprentice_mirvedaAI::SummonedCreatureJustDied(), npc_eris_havenfireAI::SummonedCreatureJustDied(), boss_terestianAI::SummonedCreatureJustDied(), npc_image_of_medivhAI::SummonedMovementInform(), npc_twiggy_flatheadAI::SummonedMovementInform(), npc_simone_the_inconspicuousAI::Transform(), npc_commander_dawnforgeAI::TurnToEachOther(), npc_commander_dawnforgeAI::TurnToPathaleonsImage(), instance_uldaman::Update(), npc_forest_frogAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), go_aura_generator_000AI::UpdateAI(), npc_kelerun_bloodmournAI::UpdateAI(), npc_infused_crystalAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), npc_dashel_stonefistAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_calvin_montagueAI::UpdateAI(), boss_archaedasAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), npc_twiggy_flatheadAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), npc_web_wrapAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), npc_commander_dawnforgeAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), guard_shattrath_aldorAI::UpdateAI(), guard_shattrath_scryerAI::UpdateAI(), npc_doctorAI::UpdateAI(), npc_redemption_targetAI::UpdateAI(), npc_mage_mirror_imageAI::UpdateAI(), npc_power_blue_flightAI::UpdateAI(), npc_garments_of_questsAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), UpdateObjectVisibility(), npc_adyen_the_lightwardenAI::WaypointReached(), and npc_commanderAI::WinEvent().
GetPlayers()
PlayerList const& Map::GetPlayers () const inline
Definition at line 260 of file Map.h.
References m_mapRefManager.
Referenced by boss_skeramAI::Aggro(), boss_najentusAI::Aggro(), AreaTrigger_at_frostworn_general(), AwardLFGRewards(), ScriptedInstance::BanPlayersIfNoGm(), WorldStateVariableManager::BroadcastVariable(), instance_blackrock_depths::CanReplacePrincess(), go_aura_generator::ChangeState(), instance_zulaman::ChangeWeather(), go_aura_generator::CheckAndApplyAura(), npc_spirit_guideAI::CorpseRemoved(), boss_icehowlAI::DoApplySurgeOfAdrenaline(), instance_shattered_halls::DoCastGroupDebuff(), npc_grimstoneAI::DoChallengeQuestCredit(), instance_culling_of_stratholme::DoChromieWhisper(), npc_thrall_old_hillsbradAI::DoHandleQuestCredit(), boss_skadiAI::DoPrepareForGauntlet(), boss_moroesAI::DoRemoveGarroteAura(), npc_highlord_darion_mograineAI::DoSendQuestCredit(), ScriptedInstance::DoStartTimedAchievement(), world_map_ebon_hold::DoUpdateBattleWeatherData(), world_map_ebon_hold::DoUpdateBattleWorldState(), world_map_ebon_hold::DoUpdateBattleZoneLightData(), ScriptedInstance::DoUpdateWorldState(), boss_felmystAI::EnterEvadeMode(), ConditionEntry::Evaluate(), ExecuteMapWorker(), ExecuteMapWorkerArea(), ExecuteMapWorkerZone(), MapManager::GetNumPlayersInInstances(), ScriptedInstance::GetPlayerInMap(), boss_gothikAI::HandleOpenGates(), boss_gothikAI::HasPlayersInLeftSide(), npc_graufAI::JustDied(), boss_alarAI::JustDied(), npc_guardian_of_yoggAI::JustReachedHome(), MessageMapBroadcast(), MessageMapBroadcastArea(), MessageMapBroadcastZone(), MonsterYellToMap(), PlayDirectSoundToMap(), Remove(), dummy_dragonAI::RemoveDebuff(), instance_stratholme::SetData(), instance_pinnacle::SetData(), instance_shattered_halls::SetData(), instance_arcatraz::SetData(), Creature::SetInCombatWithZone(), SetZoneMusic(), SetZoneOverrideLight(), SetZoneWeather(), instance_dark_portal::StartPostEvent(), instance_stratholme::Update(), instance_sunwell_plateau::Update(), instance_slave_pens::Update(), instance_mechanar::Update(), boss_bigbadwolfAI::UpdateAI(), npc_putricides_trapAI::UpdateAI(), Transport::UpdateForMap(), and instance_old_hillsbrad::UpdateLodgeQuestCredit().
GetPlayersCountExceptGMs()
uint32 Map::GetPlayersCountExceptGMs () const
Definition at line 1463 of file Map.cpp.
References m_mapRefManager.
Referenced by AchievementCriteriaRequirement::Meets(), and instance_dire_maul::Update().
GetRandomPointInTheAir()
bool Map::GetRandomPointInTheAir (uint32 phaseMask, float & x, float & y, float & z, float radius, bool randomRange = true) const
Definition at line 2724 of file Map.cpp.
References GetHeight(), INVALID_HEIGHT, M_PI_F, and rand_norm_f().
Referenced by GetReachableRandomPosition().
GetRandomPointUnderWater()
bool Map::GetRandomPointUnderWater (uint32 phaseMask, float & x, float & y, float & z, float radius, GridMapLiquidData & liquid_status, bool randomRange = true) const
Definition at line 2688 of file Map.cpp.
References GetHeight(), INVALID_HEIGHT, GridMapLiquidData::level, M_PI_F, and rand_norm_f().
Referenced by GetReachableRandomPosition().
GetReachableRandomPointOnGround()
bool Map::GetReachableRandomPointOnGround (uint32 phaseMask, float & x, float & y, float & z, float radius, bool randomRange = true) const
Definition at line 2751 of file Map.cpp.
References GetHeightInRange(), GetHitPosition(), M_PI_F, and rand_norm_f().
Referenced by GetReachableRandomPosition(), and world_map_kalimdor::GhostOPlasmEventStep().
GetReachableRandomPosition()
bool Map::GetReachableRandomPosition (Unit * unit, float & x, float & y, float & z, float radius, bool randomRange = true) const
Definition at line 2798 of file Map.cpp.
References TerrainInfo::getLiquidStatus(), WorldObject::GetPhaseMask(), GetRandomPointInTheAir(), GetRandomPointUnderWater(), GetReachableRandomPointOnGround(), Object::GetTypeId(), LIQUID_MAP_IN_WATER, LIQUID_MAP_UNDER_WATER, m_TerrainData, MAP_ALL_LIQUIDS, sLog, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by Spell::EffectScriptEffect(), and ChatHandler::HandleMmapTestHeight().
GetScriptId()
uint32 Map::GetScriptId () const inline
Definition at line 332 of file Map.h.
References i_script_id.
Referenced by ScriptDevAIMgr::CreateInstanceData().
GetSpawnManager()
SpawnManager& Map::GetSpawnManager () inline
Definition at line 403 of file Map.h.
References m_spawnManager.
Referenced by BattleGround::ChangeBgCreatureSpawnState(), BattleGround::ChangeBgObjectSpawnState(), CreatureLinkingHolder::DoCreatureLinkingEvent(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleDebugRespawnDynguid(), ChatHandler::HandleDebugSpawnsList(), ChatHandler::HandleRespawnCommand(), Creature::LoadFromDB(), GameObject::LoadFromDB(), MaNGOS::RespawnDo::operator()(), CreatureLinkingHolder::ProcessSlaveGuidList(), ScriptedInstance::RespawnDbGuids(), instance_sunwell_plateau::SetData(), Creature::SetDeathState(), PoolGroup< T >::Spawn1Object(), CreatureGroup::TriggerLinkingEvent(), and GameObject::Update().
GetSpawnMode()
uint8 Map::GetSpawnMode () const inline
Definition at line 215 of file Map.h.
References i_spawnMode.
Referenced by GetDifficulty(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleNpcAddCommand(), CreatureEventAI::InitAI(), AchievementCriteriaRequirement::Meets(), DungeonMap::SetResetSchedule(), and ObjectGridLoader::Visit().
GetTempCreatures()
std::map<uint32, uint32>& Map::GetTempCreatures () inline
Definition at line 311 of file Map.h.
References m_tempCreatures.
Referenced by Creature::AddToWorld(), ChatHandler::HandleShowTemporarySpawnList(), and Creature::RemoveFromWorld().
GetTempPets()
std::map<uint32, uint32>& Map::GetTempPets () inline
Definition at line 312 of file Map.h.
References m_tempPets.
Referenced by Creature::AddToWorld(), ChatHandler::HandleShowTemporarySpawnList(), and Creature::RemoveFromWorld().
GetTerrain()
const TerrainInfo* Map::GetTerrain () const inline
Definition at line 328 of file Map.h.
References m_TerrainData.
Referenced by WorldObject::GetTerrain(), Spell::SetTargetMap(), PlayerbotAI::UpdateAI(), Unit::UpdateAllowedPositionZ(), and Player::UpdateTerainEnvironmentFlags().
GetTransport()
GenericTransport * Map::GetTransport (ObjectGuid guid)
Definition at line 106 of file Map.cpp.
References ObjectGuid::GetEntry(), GetGameObject(), and m_transports.
Referenced by instance_halls_of_reflection::ExecuteChatCommand(), instance_icecrown_citadel::ExecuteChatCommand(), ScriptAction::GetScriptCommandObject(), WorldSession::HandleMoverRelocation(), WorldSession::HandleMoveTeleportAckOpcode(), WorldSession::HandleMoveWorldportAckOpcode(), instance_icecrown_citadel::JustDidDialogueStep(), Player::LoadFromDB(), SpellCastTargets::read(), instance_halls_of_reflection::SetData(), instance_icecrown_citadel::SetData(), Player::TeleportTo(), instance_halls_of_reflection::Update(), and SpellCastTargets::Update().
GetTransports()
TransportSet const& Map::GetTransports () inline
Definition at line 394 of file Map.h.
References m_transports.
Referenced by ChatHandler::HandleDebugTransports().
GetUnit()
Unit * Map::GetUnit (ObjectGuid guid)
Function return unit in world at CURRENT map.
Note: in case player guid not always expected need player at current map only. For example in spell casting can be expected any in world player targeting in some cases
Parameters
guid must be unit guid (HIGHGUID_PLAYER HIGHGUID_PET HIGHGUID_UNIT HIGHGUID_VEHICLE)
Definition at line 2293 of file Map.cpp.
References GetAnyTypeCreature(), GetPlayer(), and ObjectGuid::IsPlayer().
Referenced by Unit::_UpdateAutoRepeatSpell(), ThreatManager::addThreat(), boss_renatakiAI::boss_renatakiAI(), Spell::CheckCast(), npc_theramore_spar_controller::CheckCombatantHP(), npc_theramore_spar_controller::CombatantSalute(), npc_theramore_spar_controller::CombatantSeparate(), DynamicObject::Delay(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_flame_of_azzinothAI::DoPickChargeTarget(), boss_grandmaster_vorpilAI::DoTeleportToPlatform(), Spell::EffectDummy(), Spell::EffectJump(), Spell::EffectScriptEffect(), AiDelayEventAround::Execute(), boss_rimefang_posAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), SpellAuraHolder::GetCaster(), Unit::GetCharm(), Unit::GetCharmer(), Unit::GetCreator(), Spell::GetPrefilledUnitTargetOrUnitTarget(), boss_thorimAI::GetRandomArenaPlayer(), boss_sacrolashAI::GetRandomTargetAtDist(), GameObject::GetSpawner(), Unit::GetSpawner(), Unit::GetTarget(), HostileRefManager::GetThreatRedirectionTarget(), WorldSession::HandleAttackSwingOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleEjectPassenger(), WorldSession::HandleLootOpcode(), Aura::HandlePeriodicTriggerSpell(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), WorldSession::HandlePetStopAttack(), WorldSession::HandleRequestVehicleSwitchSeat(), WorldSession::HandleTextEmoteOpcode(), mob_stolen_soulAI::JustDied(), npc_warden_mellicharAI::JustDied(), npc_inner_demonAI::JustDied(), Unit::JustKilledCreature(), boss_head_of_horsemanAI::JustPreventedDeath(), npc_zulian_prowlerAI::JustRespawned(), boss_uromAI::JustSummoned(), boss_kologarnAI::JustSummoned(), npc_warden_mellicharAI::JustSummoned(), boss_ayamissAI::JustSummoned(), npc_theramore_spar_controller::MoveIntoPosition(), spell_awaken_subboss_aura::OnApply(), spell_awaken_gortok::OnEffectExecute(), SupremusHatefulStrikePrimer::OnEffectExecute(), TribalDeath::OnEffectExecute(), KillingSpree::OnPeriodicDummy(), spell_explosive_barrage_aura::OnPeriodicTrigger(), PallidHorrorAI::PallidHorrorAI(), CreatureAI::RelinquishFollow(), Unit::RemoveNotOwnTrackedTargetAuras(), npc_evergrove_druidAI::ReturnToSpawn(), npc_mimiron_flamesAI::SelectClosestSpreadTarget(), Unit::SetFleeing(), npc_theramore_spar_controller::StartSparring(), npc_theramore_spar_controller::SwitchMembers(), Aura::TriggerSpell(), SpellAuraHolder::UnregisterAndCleanupTrackedAuras(), PetAI::UpdateAI(), TotemAI::UpdateAI(), DreadsteedQuestObjects::UpdateAI(), boss_malygosAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_sifAI::UpdateAI(), npc_bird_spiritAI::UpdateAI(), npc_danath_trollbaneAI::UpdateAI(), npc_nazgrelAI::UpdateAI(), npc_flash_freezeAI::UpdateAI(), and npc_spawned_oronok_tornheartAI::WaypointMotionType().
GetUnloadLock()
bool Map::GetUnloadLock (const GridPair & p) const inline
Definition at line 186 of file Map.h.
References getNGrid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getUnloadLock(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
GetVariableManager() [1/2]
WorldStateVariableManager& Map::GetVariableManager () inline
Definition at line 407 of file Map.h.
References m_variableManager.
Referenced by BattleGround::AddPlayer(), BattleGroundEY::AddPoints(), BattleGroundAV::ChangeMineOwner(), BattleGroundWS::CheckAchievementCriteriaMeet(), BattleGroundEY::CheckVictory(), instance_mount_hyjal::DespawnWaveSpawns(), BattleGroundIC::DoCaptureObjective(), BattleGroundAB::DoUpdateNodeWorldstate(), EvalSingleValue(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), instance_mount_hyjal::FailEvent(), BattleGroundWS::GetFlagState(), BattleGroundAB::GetPrematureWinner(), BattleGroundAV::GetPrematureWinner(), BattleGroundEY::GetPrematureWinner(), BattleGroundWS::GetPrematureWinner(), BattleGroundIC::GetReinforcements(), BattleGroundIC::HandleEvent(), BattleGroundSA::HandleEvent(), BattleGround::HandleKillPlayer(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), boss_sartharionAI::HandleResetWorldstate(), ChatHandler::HandleVariablePrint(), instance_uldaman::Initialize(), instance_zulaman::Initialize(), instance_mount_hyjal::Initialize(), world_map_kalimdor::Initialize(), world_map_outland::Initialize(), BattleGroundAV::InitializeNode(), instance_mount_hyjal::OnCreatureCreate(), instance_mount_hyjal::OnCreatureDeath(), instance_uldaman::OnCreatureGroupDespawn(), instance_blackrock_depths::OnPlayerEnter(), instance_scarlet_monastery::OnPlayerEnter(), instance_shadowfang_keep::OnPlayerEnter(), instance_slave_pens::OnPlayerEnter(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAB::ProcessNodeCapture(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGround::RemovePlayer(), BattleGround::Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundSA::Reset(), BattleGroundWS::Reset(), BattleGroundWS::RespawnFlagAtBase(), instance_mount_hyjal::RetreatBase(), boss_sartharionAI::SendFlameTsunami(), Player::SendInitWorldStates(), world_map_outland::SetData(), world_map_kalimdor::SetData(), instance_zulaman::SetData(), instance_mount_hyjal::SetData(), BattleGroundSA::SetDefender(), BattleGroundEY::SetFlagState(), BattleGroundIC::SetReinforcements(), BattleGroundEY::SetTowerOwner(), BattleGroundSA::SetupBattleground(), instance_zulaman::SpawnMalacrass(), instance_mount_hyjal::SpawnWave(), BattleGroundAV::StartingEventOpenDoors(), BattleGroundSA::StartingEventOpenDoors(), BattleGroundAB::Update(), BattleGroundSA::Update(), BattleGroundWS::Update(), BattleGroundAV::UpdateNodeWorldState(), BattleGroundAV::UpdateScore(), and BattleGroundSA::UpdateTimerWorldState().
GetVariableManager() [2/2]
WorldStateVariableManager const& Map::GetVariableManager () const inline
Definition at line 408 of file Map.h.
References m_variableManager.
GetVisibilityDistance()
float Map::GetVisibilityDistance () const inline
Definition at line 163 of file Map.h.
References m_VisibleDistance.
Referenced by ActiveObjectsNearGrid(), Spell::CheckCast(), VisibilityData::GetVisibilityDistance(), Update(), and VisitNearbyCellsOf().
GetWeatherSystem()
WeatherSystem* Map::GetWeatherSystem () const inline
Definition at line 356 of file Map.h.
References m_weatherSystem.
Referenced by Player::UpdateZone().
GetWorldObject()
WorldObject * Map::GetWorldObject (ObjectGuid guid)
Function return world object in world at CURRENT map, so any except transports.
Definition at line 2304 of file Map.cpp.
References GetCorpse(), GetCreature(), GetDynamicObject(), GetGameObject(), ObjectGuid::GetHigh(), GetPet(), GetPlayer(), HIGHGUID_CORPSE, HIGHGUID_DYNAMICOBJECT, HIGHGUID_GAMEOBJECT, HIGHGUID_MO_TRANSPORT, HIGHGUID_PET, HIGHGUID_PLAYER, HIGHGUID_TRANSPORT, HIGHGUID_UNIT, HIGHGUID_VEHICLE, and Object::IsInWorld().
Referenced by Spell::AddUnitTarget(), PlayerbotAI::CombatOrderRestore(), PlayerbotAI::DoLoot(), PlayerbotAI::findNearbyCreature(), Unit::GetChannelObject(), WorldSession::HandleFarSightOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePlayerReconnect(), AbstractWrapperMovementGenerator::Inform(), PointMovementGenerator::MovementInform(), MaNGOS::VisibleNotifier::Notify(), WaypointMovementGenerator< Creature >::OnArrived(), and Update().
GetWorldObjects() [1/2]
std::vector< WorldObject * > const * Map::GetWorldObjects (std::string stringId) const
Definition at line 2378 of file Map.cpp.
References GetMapDataContainer().
Referenced by ScriptAction::GetScriptProcessTargets().
GetWorldObjects() [2/2]
std::vector< WorldObject * > const * Map::GetWorldObjects (uint32 stringId) const
Definition at line 2393 of file Map.cpp.
References m_objectsPerStringId.
HavePlayers()
bool Map::HavePlayers () const inline
Definition at line 250 of file Map.h.
References LinkedListHead::isEmpty(), and m_mapRefManager.
Referenced by DungeonMap::Reset(), DungeonMap::SetResetSchedule(), and TeleportAllPlayersTo().
Initialize()
void Map::Initialize (bool loadInstanceData = true) virtual
Reimplemented in BattleGroundMap.
Definition at line 228 of file Map.cpp.
References Referencable< Countable >::AddRef(), CreateInstanceData(), MMAP::MMapFactory::createOrGetMMapManager(), MapPersistentState::GetCompletedEncountersMask(), GetDifficulty(), GetId(), GetInstanceId(), i_mapEntry, GraveyardManager::Init(), SpawnManager::Initialize(), WorldStateVariableManager::Initialize(), MapPersistentState::InitPools(), InitVisibilityDistance(), IsDungeon(), MMAP::MMapManager::loadMapData(), LoadTransports(), m_bLoadedGrids, m_CreatureGuids, m_GameObjectGuids, m_graveyardManager, m_persistentState, m_spawnManager, m_TerrainData, m_variableManager, MAX_NUMBER_OF_GRIDS, ObjectGuidGenerator< high >::Set(), setNGrid(), MapPersistentState::SetUsedByMapState(), sMapPersistentStateMgr, and sObjectMgr.
Referenced by MapManager::CreateContinents(), MapManager::CreateDungeonMap(), MapManager::CreateMap(), and BattleGroundMap::Initialize().
InitVisibilityDistance()
void Map::InitVisibilityDistance () virtual
Reimplemented in BattleGroundMap, and DungeonMap.
Definition at line 269 of file Map.cpp.
References World::GetMaxVisibleDistanceOnContinents(), and m_VisibleDistance.
Referenced by Initialize().
InsertGameObjectModel()
void Map::InsertGameObjectModel (const GameObjectModel & mdl)
Definition at line 2672 of file Map.cpp.
References DynamicMapTree::insert(), and m_dyn_tree.
Referenced by GameObject::AddModelToMap(), GameObject::AddToWorld(), GameObject::UpdateModel(), and GameObject::UpdateModelPosition().
Instanceable()
bool Map::Instanceable () const inline
Definition at line 226 of file Map.h.
References i_mapEntry, and MapEntry::Instanceable().
Referenced by ObjectAccessor::AddCorpsesToGrid(), CreateInstanceData(), MapManager::DeleteInstance(), ConditionEntry::Evaluate(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleNamegoCommand(), Aura::HandlePreventResurrection(), InstanceData::SaveToDB(), World::SendDefenseMessage(), World::SendDefenseMessageBroadcastText(), and World::SendZoneUnderAttackMessage().
IsBattleArena()
bool Map::IsBattleArena () const inline
Definition at line 233 of file Map.h.
References i_mapEntry, and MapEntry::IsBattleArena().
Referenced by Pet::LoadPetFromDB(), Drink::OnApply(), Replenishment::OnCheckTarget(), and Drink::OnPeriodicDummy().
IsBattleGround()
bool Map::IsBattleGround () const inline
Definition at line 232 of file Map.h.
References i_mapEntry, and MapEntry::IsBattleGround().
Referenced by npc_spirit_guideAI::CorpseRemoved(), Spell::EffectTeleportGraveyard(), Spell::EffectWMODamage(), FlagClickBg::OnCheckCast(), spell_repair_cannon::OnEffectExecute(), spell_end_of_round::OnEffectExecute(), and GameObject::Use().
IsBattleGroundOrArena()
bool Map::IsBattleGroundOrArena () const inline
Definition at line 234 of file Map.h.
References i_mapEntry, and MapEntry::IsBattleGroundOrArena().
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), GameObject::Create(), MapManager::CreateBattleGroundMap(), Player::CreateCorpse(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleGroupgoCommand(), ChatHandler::HandleNamegoCommand(), LoadHelper(), MaNGOS::RespawnDo::operator()(), InstanceData::SaveToDB(), StartEvents_Event(), Update(), and Player::Update().
isCellMarked()
bool Map::isCellMarked (uint32 pCellId) const inline
Definition at line 247 of file Map.h.
References marked_cells.
Referenced by Update(), and VisitNearbyCellsOf().
IsContinent()
bool Map::IsContinent () const inline
Definition at line 235 of file Map.h.
References i_mapEntry, and MapEntry::IsContinent().
Referenced by ChatHandler::HandleListAreaTriggerCommand(), WorldState::HandlePlayerEnterZone(), and WorldState::HandlePlayerLeaveZone().
IsDungeon()
bool Map::IsDungeon () const inline
Definition at line 227 of file Map.h.
References i_mapEntry, and MapEntry::IsDungeon().
Referenced by Group::_homebindIfInstance(), HomeMovementGenerator< Creature >::_setTargetLocation(), Player::BeforeVisibilityDestroy(), PathFinder::BuildPolyPath(), Spell::CheckScriptTargeting(), UnitAI::DetectOrAttack(), boss_moroesAI::DoRemoveGarroteAura(), Spell::EffectDummy(), Spell::EffectStuck(), ConditionEntry::Evaluate(), Spell::finish(), Player::GetAreaTriggerLockStatus(), Creature::GetCreatureConditionalSpawnEntry(), MapManager::GetNumInstances(), MapManager::GetNumPlayersInInstances(), Aura::HandleAuraDummy(), WorldSession::HandleChangePlayerDifficulty(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleNamegoCommand(), WorldSession::HandleSetDungeonDifficultyOpcode(), WorldSession::HandleSetRaidDifficultyOpcode(), WorldSession::HandleSpellClick(), Unit::HasAuraOfDifficulty(), CreatureEventAI::InitAI(), Initialize(), IsMountAllowed(), Unit::JustKilledCreature(), UnitAI::MoveInLineOfSight(), npc_malfurionAI::npc_malfurionAI(), Unit::RemoveAurasDueToSpell(), dummy_dragonAI::RemoveDebuff(), SpawnGroup::RemoveObject(), Player::SetBattleGroundEntryPoint(), Creature::SetInCombatWithZone(), SpawnGroup::Spawn(), Spell::Spell(), LFGMgr::TeleportPlayer(), CombatManager::Update(), AchievementMgr::UpdateAchievementCriteria(), and npc_malfurionAI::UpdateAI().
IsDynguidForced()
bool Map::IsDynguidForced () const
Definition at line 2871 of file Map.cpp.
References GetId().
Referenced by Creature::LoadFromDB(), and GameObject::LoadFromDB().
isGridObjectDataLoaded()
bool Map::isGridObjectDataLoaded (uint32 x, uint32 y) const inline private
Definition at line 453 of file Map.h.
References getNGrid(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::isGridObjectDataLoaded().
Referenced by EnsureGridLoaded(), and loaded().
IsHeroic()
bool Map::IsHeroic () const inline
Definition at line 231 of file Map.h.
References DUNGEON_DIFFICULTY_HEROIC, i_spawnMode, IsRaid(), and RAID_DIFFICULTY_10MAN_HEROIC.
Referenced by npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), and Group::SendUpdateTo().
IsInLineOfSight()
bool Map::IsInLineOfSight (float srcX, float srcY, float srcZ, float destX, float destY, float destZ, uint32 phasemask, bool ignoreM2Model) const
Function to check if a point is in line of sight from an other point.
Definition at line 2573 of file Map.cpp.
References VMAP::VMapFactory::createOrGetVMapManager(), GetId(), DynamicMapTree::isInLineOfSight(), VMAP::IVMapManager::isInLineOfSight(), and m_dyn_tree.
Referenced by CheckPathToTarget(), PathFinder::ComputePathToRandomPoint(), ChaseMovementGenerator::CutPath(), NamreebAnticheat::Movement::ExtrapolateMovement(), WorldObject::IsWithinLOS(), WorldObject::IsWithinLOSForMe(), and FollowMovementGenerator::Move().
IsLoaded()
bool Map::IsLoaded (float x, float y) const inline
Definition at line 180 of file Map.h.
References MaNGOS::ComputeGridPair(), and loaded().
Referenced by ForceLoadGrid(), SpawnCreatureInMapsWorker::operator()(), SpawnGameObjectInMapsWorker::operator()(), SpawnGroup::Spawn(), PoolGroup< T >::Spawn1Object(), and Transport::Update().
IsMountAllowed()
bool Map::IsMountAllowed () const
Definition at line 2860 of file Map.cpp.
References GetId(), ObjectMgr::GetInstanceTemplate(), and IsDungeon().
Referenced by Spell::CheckCast().
IsNonRaidDungeon()
bool Map::IsNonRaidDungeon () const inline
Definition at line 229 of file Map.h.
References i_mapEntry, and MapEntry::IsNonRaidDungeon().
Referenced by MaNGOS::XP::Gain(), and Player::RewardReputation().
IsRaid()
bool Map::IsRaid () const inline
Definition at line 228 of file Map.h.
References i_mapEntry, and MapEntry::IsRaid().
Referenced by Add(), ChatHandler::HandleGonameCommand(), WorldSession::HandlePlayerLogin(), IsHeroic(), IsRaidOrHeroicDungeon(), Remove(), DungeonMap::SendResetWarnings(), Spell::Spell(), and AchievementMgr::UpdateAchievementCriteria().
IsRaidOrHeroicDungeon()
bool Map::IsRaidOrHeroicDungeon () const inline
Definition at line 230 of file Map.h.
References DUNGEON_DIFFICULTY_NORMAL, GetDifficulty(), and IsRaid().
Referenced by Unit::JustKilledCreature(), and DungeonMap::SetResetSchedule().
IsRegularDifficulty()
bool Map::IsRegularDifficulty () const inline
Definition at line 217 of file Map.h.
References GetDifficulty(), and REGULAR_DIFFICULTY.
Referenced by AreaTrigger_at_shattered_halls(), argent_champion_commonAI::argent_champion_commonAI(), boss_aeonusAI::boss_aeonusAI(), boss_aerial_unitAI::boss_aerial_unitAI(), boss_algalonAI::boss_algalonAI(), boss_ambassador_hellmawAI::boss_ambassador_hellmawAI(), boss_anomalusAI::boss_anomalusAI(), boss_anubarakAI::boss_anubarakAI(), boss_auriayaAI::boss_auriayaAI(), boss_bjarngrimAI::boss_bjarngrimAI(), boss_brundirAI::boss_brundirAI(), boss_chrono_lord_dejaAI::boss_chrono_lord_dejaAI(), boss_dalliahAI::boss_dalliahAI(), boss_darkweaver_sythAI::boss_darkweaver_sythAI(), boss_devourer_of_soulsAI::boss_devourer_of_soulsAI(), boss_eregosAI::boss_eregosAI(), boss_feral_defenderAI::boss_feral_defenderAI(), boss_flame_leviathanAI::boss_flame_leviathanAI(), boss_freyaAI::boss_freyaAI(), boss_general_vezaxAI::boss_general_vezaxAI(), boss_grand_warlock_nethekurseAI::boss_grand_warlock_nethekurseAI(), boss_grandmaster_vorpilAI::boss_grandmaster_vorpilAI(), boss_hadronoxAI::boss_hadronoxAI(), boss_harbinger_skyrissAI::boss_harbinger_skyrissAI(), boss_hodirAI::boss_hodirAI(), boss_ichoronAI::boss_ichoronAI(), boss_ignisAI::boss_ignisAI(), boss_ingvarAI::boss_ingvarAI(), boss_ionarAI::boss_ionarAI(), boss_jedogaAI::boss_jedogaAI(), boss_kelesethAI::boss_kelesethAI(), boss_keristraszaAI::boss_keristraszaAI(), boss_kologarnAI::boss_kologarnAI(), boss_krikthirAI::boss_krikthirAI(), boss_leviathan_mk2AI::boss_leviathan_mk2AI(), boss_lokenAI::boss_lokenAI(), boss_malygosAI::boss_malygosAI(), boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI(), boss_molgeimAI::boss_molgeimAI(), boss_murmurAI::boss_murmurAI(), boss_nadoxAI::boss_nadoxAI(), boss_nethermancer_sepethreaAI::boss_nethermancer_sepethreaAI(), boss_novosAI::boss_novosAI(), boss_onyxiaAI::boss_onyxiaAI(), boss_ormorokAI::boss_ormorokAI(), boss_pandemoniusAI::boss_pandemoniusAI(), boss_pathaleon_the_calculatorAI::boss_pathaleon_the_calculatorAI(), boss_razorscaleAI::boss_razorscaleAI(), boss_saraAI::boss_saraAI(), boss_sartharionAI::boss_sartharionAI(), boss_sifAI::boss_sifAI(), boss_sjonnirAI::boss_sjonnirAI(), boss_skadiAI::boss_skadiAI(), boss_soccothratesAI::boss_soccothratesAI(), boss_steelbreakerAI::boss_steelbreakerAI(), boss_svalaAI::boss_svalaAI(), boss_taldaramAI::boss_taldaramAI(), boss_telestraAI::boss_telestraAI(), boss_tharonjaAI::boss_tharonjaAI(), boss_thespiaAI::boss_thespiaAI(), boss_thorimAI::boss_thorimAI(), boss_thorngrinAI::boss_thorngrinAI(), boss_trollgoreAI::boss_trollgoreAI(), boss_uromAI::boss_uromAI(), boss_varosAI::boss_varosAI(), boss_volazjAI::boss_volazjAI(), boss_volkhanAI::boss_volkhanAI(), boss_vx001AI::boss_vx001AI(), boss_warbringer_omroggAI::boss_warbringer_omroggAI(), boss_warchief_kargath_bladefistAI::boss_warchief_kargath_bladefistAI(), boss_warp_splinterAI::boss_warp_splinterAI(), boss_xevozzAI::boss_xevozzAI(), boss_xt_002AI::boss_xt_002AI(), boss_ymironAI::boss_ymironAI(), boss_yogg_saronAI::boss_yogg_saronAI(), instance_ulduar::DoCallLeviathanHelp(), instance_shattered_halls::DoInitialGets(), instance_ulduar::DoSpawnHodirNpcs(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), dummy_dragonAI::dummy_dragonAI(), Spell::EffectDummy(), Spell::EffectScriptEffect(), GetMaxPlayers(), boss_ahuneAI::JustDied(), mob_dragonflayer_forge_masterAI::mob_dragonflayer_forge_masterAI(), mob_molten_golemAI::mob_molten_golemAI(), mob_steamrigger_mechanicAI::mob_steamrigger_mechanicAI(), mob_stormforged_lieutenantAI::mob_stormforged_lieutenantAI(), mob_vrykul_skeletonAI::mob_vrykul_skeletonAI(), npc_annhyldeAI::npc_annhyldeAI(), npc_arcatraz_defenderAI::npc_arcatraz_defenderAI(), npc_arthasAI::npc_arthasAI(), npc_constrictor_tentacleAI::npc_constrictor_tentacleAI(), npc_dark_matterAI::npc_dark_matterAI(), npc_eonars_giftAI::npc_eonars_giftAI(), npc_ethereal_sphereAI::npc_ethereal_sphereAI(), npc_guardian_of_yoggAI::npc_guardian_of_yoggAI(), npc_immortal_guardianAI::npc_immortal_guardianAI(), npc_impale_targetAI::npc_impale_targetAI(), npc_iron_constructAI::npc_iron_constructAI(), npc_iron_rootsAI::npc_iron_rootsAI(), npc_living_constellationAI::npc_living_constellationAI(), npc_nature_bombAI::npc_nature_bombAI(), npc_raging_flamesAI::npc_raging_flamesAI(), npc_runic_colossusAI::npc_runic_colossusAI(), npc_time_riftAI::npc_time_riftAI(), npc_voice_yogg_saronAI::npc_voice_yogg_saronAI(), npc_void_travelerAI::npc_void_travelerAI(), SnakeWrap::OnApply(), WidowsEmbrace::OnApply(), spell_intense_cold_aura::OnApply(), spell_create_spirit_fount_beam_aura::OnApply(), HatefulStrikePrimer::OnCheckTarget(), VazrudenLiquidFire::OnEffectExecute(), SapphironBlizzardInit::OnEffectExecute(), spell_vortex::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), instance_gundrak::OnObjectCreate(), GripOfSladran::OnPeriodicDummy(), spell_permafrost_aura::OnPeriodicDummy(), SummonSkeletonsNoth::OnPeriodicTrigger(), instance_ulduar::OnPlayerEnter(), instance_shattered_halls::OnPlayerEnter(), Aura::PeriodicDummyTick(), ProcessEventId_event_boss_hodir(), instance_halls_of_stone::ProcessFaceSpell(), instance_halls_of_stone::ProcessFaceSummon(), instance_culling_of_stratholme::SetData(), instance_trial_of_the_champion::SetData(), instance_gundrak::SetData(), instance_naxxramas::SetData(), instance_eye_of_eternity::SetData(), instance_oculus::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_ramparts::SetData(), instance_arcatraz::SetData(), instance_mechanar::SetData(), three_nature_alliesAI::three_nature_alliesAI(), trial_companion_commonAI::trial_companion_commonAI(), instance_eye_of_eternity::Update(), instance_pinnacle::Update(), instance_blood_furnace::Update(), and instance_halls_of_reflection::Update().
IsRemovalGrid()
bool Map::IsRemovalGrid (float x, float y) const inline
Definition at line 174 of file Map.h.
References MaNGOS::ComputeGridPair(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridState(), getNGrid(), GRID_STATE_REMOVAL, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by ObjectAccessor::ConvertCorpseForPlayer().
loaded()
bool Map::loaded (const GridPair & p) const private
Definition at line 702 of file Map.cpp.
References getNGrid(), isGridObjectDataLoaded(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by CreatureCellRelocation(), DynamicObjectRelocation(), ExecuteDistWorker(), GameObjectRelocation(), IsLoaded(), MessageBroadcast(), MessageDistBroadcast(), Remove(), and Visit().
LoadMapAndVMap()
void Map::LoadMapAndVMap (int gx, int gy) private
Definition at line 204 of file Map.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), GetId(), GetInstanceId(), TerrainInfo::Load(), MMAP::MMapManager::loadMap(), m_bLoadedGrids, and m_TerrainData.
Referenced by EnsureGridCreated().
LoadTransports()
void Map::LoadTransports () private
Definition at line 1391 of file Map.cpp.
References GetId(), GameObject::IsSpawnedByDefault(), Transport::LoadTransport(), sMapMgr, and TEAM_NONE.
Referenced by Initialize().
markCell()
void Map::markCell (uint32 pCellId) inline
Definition at line 248 of file Map.h.
References marked_cells.
Referenced by Update(), and VisitNearbyCellsOf().
MessageBroadcast() [1/2]
void Map::MessageBroadcast (Player const * player, WorldPacket const & msg, bool to_self)
Definition at line 549 of file Map.cpp.
References MaNGOS::ComputeCellPair(), Cell::data, Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), loaded(), Cell::Part, Cell::SetNoCreate(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Cell::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by WorldObject::SendMessageToSet(), and Player::SendMessageToSet().
MessageBroadcast() [2/2]
void Map::MessageBroadcast (WorldObject const * obj, WorldPacket const & msg)
Definition at line 570 of file Map.cpp.
References MaNGOS::ComputeCellPair(), Cell::data, Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetTypeId(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), loaded(), Cell::Part, Cell::SetNoCreate(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Cell::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
MessageDistBroadcast() [1/2]
void Map::MessageDistBroadcast (Player const * player, WorldPacket const & msg, float dist, bool to_self, bool own_team_only = false)
Definition at line 593 of file Map.cpp.
References MaNGOS::ComputeCellPair(), Cell::data, Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), loaded(), Cell::Part, Cell::SetNoCreate(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Cell::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by WorldObject::SendMessageToSetInRange(), and Player::SendMessageToSetInRange().
MessageDistBroadcast() [2/2]
void Map::MessageDistBroadcast (WorldObject const * obj, WorldPacket const & msg, float dist)
Definition at line 614 of file Map.cpp.
References MaNGOS::ComputeCellPair(), Cell::data, Object::GetGUIDLow(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetTypeId(), loaded(), Cell::Part, Cell::SetNoCreate(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Cell::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
MessageMapBroadcast()
void Map::MessageMapBroadcast (WorldObject const * obj, WorldPacket const & msg)
Definition at line 635 of file Map.cpp.
References GetPlayers().
Referenced by WorldObject::HandlePlayPacketSettings().
MessageMapBroadcastArea()
void Map::MessageMapBroadcastArea (WorldObject const * obj, WorldPacket const & msg, uint32 areaId)
Definition at line 650 of file Map.cpp.
References GetPlayers().
Referenced by WorldObject::HandlePlayPacketSettings().
MessageMapBroadcastZone()
void Map::MessageMapBroadcastZone (WorldObject const * obj, WorldPacket const & msg, uint32 zoneId)
Definition at line 642 of file Map.cpp.
References GetPlayers().
Referenced by WorldObject::HandlePlayPacketSettings().
MonsterYellToMap() [1/2]
void Map::MonsterYellToMap (CreatureInfo const * cinfo, int32 textId, ChatMsg chatMsg, Language language, Unit const * target, uint32 senderLowGuid = 0) const
Function simulates yell of creature.
Parameters
cinfo must be entry of Creature of whom to Simulate the yell
textId Id of the simulated text
language language of the text
target,can be nullptr
senderLowGuid provide way proper show yell for near spawned creature with known lowguid, 0 accepted by client else if this not important
Definition at line 2543 of file Map.cpp.
References GetPlayers().
MonsterYellToMap() [2/2]
void Map::MonsterYellToMap (ObjectGuid guid, int32 textId, ChatMsg chatMsg, Language language, Unit const * target) const
Function simulates yell of creature.
Parameters
guid must be creature guid of whom to Simulate the yell, non-creature guids not supported at this moment
textId Id of the simulated text
language language of the text
target,can be nullptr
Definition at line 2514 of file Map.cpp.
References ObjectGuid::GetCounter(), ObjectMgr::GetCreatureTemplate(), ObjectGuid::GetEntry(), ObjectGuid::GetString(), ObjectGuid::IsAnyTypeCreature(), and sLog.
Referenced by DoOrSimulateScriptTextForMap().
OnEventHappened()
void Map::OnEventHappened (uint16 event_id, bool activate, bool resume)
Definition at line 2883 of file Map.cpp.
References i_data, m_onEventNotifiedIter, m_onEventNotifiedObjects, and InstanceData::OnEventHappened().
Referenced by GameEventMgr::OnEventHappened().
PlayDirectSoundToMap()
void Map::PlayDirectSoundToMap (uint32 soundId, uint32 zoneId = 0) const
Function to play sound to all players in map.
Parameters
soundId Played Sound
zoneId Id of the Zone to which the sound should be restricted
Definition at line 2559 of file Map.cpp.
References GetPlayers(), and SMSG_PLAY_SOUND.
Referenced by DoOrSimulateScriptTextForMap(), ScriptAction::ExecuteDbscriptCommand(), and go_ai_bell::OnEventHappened().
PlayerRelocation()
void Map::PlayerRelocation (Player * player, float x, float y, float z, float orientation)
Definition at line 1002 of file Map.cpp.
References AddToGrid(), Cell::CellX(), Cell::CellY(), MaNGOS::ComputeCellPair(), DEBUG_FILTER_LOG, Cell::DiffCell(), Cell::DiffGrid(), EnsureGridLoadedAtEnter(), ViewPoint::Event_GridChanged(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridState(), WorldObject::GetName(), getNGrid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetViewPoint(), GRID_STATE_ACTIVE, Cell::GridX(), Cell::GridY(), LOG_FILTER_PLAYER_MOVES, MANGOS_ASSERT, Unit::OnRelocated(), WorldObject::Relocate(), RemoveFromGrid(), ResetGridExpiry(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::SetGridState().
Referenced by Player::SetPosition(), TransportBase::UpdateGlobalPositionOf(), and GenericTransport::UpdatePassengerPosition().
Remove() [1/2]
void Map::Remove (Player * player, bool remove) virtual
Reimplemented in BattleGroundMap, and DungeonMap.
Definition at line 903 of file Map.cpp.
References Player::CleanupsBeforeDelete(), MaNGOS::ComputeCellPair(), Cell::data, DEBUG_FILTER_LOG, DeleteFromWorld(), Player::GetMapRef(), WorldObject::GetName(), getNGrid(), Object::GetObjectGuid(), GetPlayers(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Cell::GridX(), Cell::GridY(), i_data, IsRaid(), LOG_FILTER_PLAYER_MOVES, m_mapRefIter, MANGOS_ASSERT, MapReference::nocheck_prev(), InstanceData::OnPlayerLeave(), Cell::Part, RemoveFromGrid(), Player::RemoveFromWorld(), Player::ResetMap(), SendRemoveTransports(), sLog, TOTAL_NUMBER_OF_CELLS_PER_MAP, Reference< TO, FROM >::unlink(), UpdateObjectVisibility(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), ChatHandler::HandleGameObjectMoveCommand(), WorldSession::LogoutPlayer(), DungeonMap::Remove(), BattleGroundMap::Remove(), RemoveAllObjectsInRemoveList(), and Player::TeleportTo().
Remove() [2/2]
template<class T > void Map::Remove (T * obj, bool remove)
Definition at line 960 of file Map.cpp.
References MaNGOS::ComputeCellPair(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, Cell::data, DEBUG_FILTER_LOG, getNGrid(), Cell::GridX(), Cell::GridY(), loaded(), LOG_FILTER_CREATURE_MOVES, m_objRemoveList, MANGOS_ASSERT, Cell::Part, RemoveFromActive(), RemoveFromGrid(), sLog, sWorld, TOTAL_NUMBER_OF_CELLS_PER_MAP, UpdateObjectVisibility(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
RemoveAllObjectsInRemoveList()
void Map::RemoveAllObjectsInRemoveList () virtual
Definition at line 1423 of file Map.cpp.
References GetCorpse(), Object::GetGUIDLow(), Object::GetObjectGuid(), Object::GetTypeId(), i_objectsToRemove, Remove(), sLog, TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by UnloadGrid().
RemoveDbGuidObject()
void Map::RemoveDbGuidObject (WorldObject * obj)
Definition at line 2425 of file Map.cpp.
References Object::GetDbGuid(), WorldObject::GetParentHigh(), and m_dbGuidObjects.
Referenced by Creature::RemoveFromWorld(), and GameObject::RemoveFromWorld().
RemoveFromActive()
void Map::RemoveFromActive (WorldObject * obj)
Definition at line 1558 of file Map.cpp.
References MaNGOS::ComputeGridPair(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::decUnloadActiveLock(), Object::GetEntry(), Object::GetGUIDLow(), getNGrid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Creature::GetRespawnCoord(), Object::GetTypeId(), Creature::HasStaticDBSpawnData(), Creature::IsPet(), m_activeNonPlayers, m_activeNonPlayersIter, sLog, TYPEID_UNIT, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Remove(), WorldObject::SetActiveObjectState(), and Camera::SetView().
RemoveFromGrid() [1/4]
template<> void Map::RemoveFromGrid (Corpse * obj, NGridType * grid, Cell const & cell)
Definition at line 340 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), CORPSE_BONES, and Corpse::GetType().
RemoveFromGrid() [2/4]
template<> void Map::RemoveFromGrid (Creature * obj, NGridType * grid, Cell const & cell)
Definition at line 355 of file Map.cpp.
References Cell::CellX(), Cell::CellY(), and Creature::IsPet().
RemoveFromGrid() [3/4]
template<> void Map::RemoveFromGrid (Player * obj, NGridType * grid, Cell const & cell)
Definition at line 334 of file Map.cpp.
References Cell::CellX(), and Cell::CellY().
RemoveFromGrid() [4/4]
template<class T > void Map::RemoveFromGrid (T * obj, NGridType * grid, Cell const & cell) private
Definition at line 328 of file Map.cpp.
References Cell::CellX(), and Cell::CellY().
Referenced by CreatureCellRelocation(), DynamicObjectRelocation(), GameObjectRelocation(), PlayerRelocation(), and Remove().
RemoveFromOnEventNotified()
void Map::RemoveFromOnEventNotified (WorldObject * obj)
Definition at line 1598 of file Map.cpp.
References m_onEventNotifiedIter, and m_onEventNotifiedObjects.
Referenced by WorldObject::RemoveFromWorld(), and WorldObject::SetNotifyOnEventState().
RemoveFromSpawnCount()
void Map::RemoveFromSpawnCount (const ObjectGuid & guid)
Definition at line 2903 of file Map.cpp.
References ObjectGuid::GetEntry(), and m_spawnedCount.
Referenced by Creature::RemoveFromWorld().
RemoveGameObjectModel()
void Map::RemoveGameObjectModel (const GameObjectModel & mdl)
Definition at line 2677 of file Map.cpp.
References m_dyn_tree, and DynamicMapTree::remove().
Referenced by GameObject::RemoveFromWorld(), GameObject::RemoveModelFromMap(), GameObject::UpdateModel(), and GameObject::UpdateModelPosition().
RemoveStringIdObject()
void Map::RemoveStringIdObject (uint32 stringId, WorldObject * obj)
Definition at line 2441 of file Map.cpp.
References Object::IsCreature(), Object::IsGameObject(), and m_objectsPerStringId.
Referenced by WorldObject::RemoveFromWorld(), and WorldObject::SetStringId().
RemoveTransport()
void Map::RemoveTransport (Transport * transport)
Definition at line 128 of file Map.cpp.
References m_transports, and m_transportsIterator.
Referenced by Transport::TeleportTransport().
RemoveUpdateObject()
void Map::RemoveUpdateObject (Object * obj) inline
Definition at line 319 of file Map.h.
References i_objectsToClientUpdate.
Referenced by WorldObject::RemoveFromClientUpdateList().
ResetGridExpiry()
void Map::ResetGridExpiry (NGridType & grid, float factor = 1) const inline
Definition at line 192 of file Map.h.
References i_gridExpiry, and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ResetTimeTracker().
Referenced by EnsureGridLoadedAtEnter(), PlayerRelocation(), ActiveState::Update(), IdleState::Update(), and RemovalState::Update().
resetMarkedCells()
void Map::resetMarkedCells () inline
Definition at line 246 of file Map.h.
References marked_cells.
Referenced by Update().
ScriptCommandStart()
void Map::ScriptCommandStart (ScriptInfo const & script, uint32 delay, Object * source, Object * target)
Definition at line 2146 of file Map.cpp.
References GetCurrentClockTime(), Object::GetObjectGuid(), ScriptAction::HandleScriptStep(), Object::isType(), m_scriptSchedule, SCRIPT_TYPE_INTERNAL, and TYPEMASK_ITEM.
ScriptsProcess()
void Map::ScriptsProcess () private
Process queued scripts.
Process overdue queued scripts
Definition at line 2166 of file Map.cpp.
References GetCurrentClockTime(), and m_scriptSchedule.
Referenced by Update().
ScriptsStart()
bool Map::ScriptsStart (ScriptMapType scriptType, uint32 id, Object * source, Object * target, ScriptExecutionParam execParams = SCRIPT_EXEC_PARAM_NONE)
Put scripts in the execution queue.
Find the script map
Schedule script execution for all scripts in the script map
Definition at line 2087 of file Map.cpp.
References DETAIL_FILTER_LOG, GetCurrentClockTime(), GetMapDataContainer(), Object::GetObjectGuid(), MapDataContainer::GetScriptMap(), ObjectGuid::GetString(), ScriptAction::HandleScriptStep(), Object::isType(), LOG_FILTER_DB_SCRIPT, m_scriptSchedule, MANGOS_ASSERT, SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE, SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET, and TYPEMASK_ITEM.
Referenced by Player::AddQuest(), npc_warlock_mount_ritualAI::DoSummonPack(), Spell::EffectDummy(), Spell::EffectScriptEffect(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), ScriptAction::ExecuteDbscriptCommand(), Player::GetGossipTextId(), ChatHandler::HandleDebugDbscript(), ChatHandler::HandleDebugDbscriptGuided(), ChatHandler::HandleDebugDbscriptSourced(), ChatHandler::HandleDebugDbscriptTargeted(), AbstractWrapperMovementGenerator::Inform(), Unit::JustKilledCreature(), npc_shattered_sun_fighterAI::JustRespawned(), Creature::LoadFromDB(), npc_evergrove_druidAI::MoveInLineOfSight(), AbstractPathMovementGenerator::MovementInform(), PointMovementGenerator::MovementInform(), StormcrowAmulet::OnApply(), WaypointMovementGenerator< Creature >::OnArrived(), Player::OnGossipSelect(), MammothTrapBoreanAI::OnLootStateChange(), CreatureEventAI::ProcessAction(), QuestAccept_npc_major_mills(), QuestRewarded_into_the_soulgrinder(), QuestRewarded_npc_adal(), Creature::ResetEntry(), npc_evergrove_druidAI::ReturnToSpawn(), Player::RewardQuest(), npc_xiri::RunAkamaRPEvent(), npc_dorius_stonetenderAI::SpellHit(), boss_scarlet_commander_mograineAI::SpellHit(), StartEvents_Event(), world_map_outland::StartManaSlaveEvent(), WorldObject::SummonCreature(), UnitAI::UpdateSpellLists(), GameObject::Use(), and npc_wounded_blood_elfAI::WaypointReached().
SendInitSelf()
void Map::SendInitSelf (Player * player) const private
Definition at line 1300 of file Map.cpp.
References Player::AddAtClient(), Player::BuildCreateUpdateBlockForPlayer(), UpdateData::BuildPacket(), DETAIL_LOG, Object::GetGUIDLow(), UpdateData::GetPacketCount(), Player::GetSession(), WorldObject::GetTransport(), Player::HasAtClient(), and WorldSession::SendPacket().
Referenced by Add(), and CreatePlayerOnClient().
SendInitTransports()
void Map::SendInitTransports (Player * player) const private
Definition at line 1339 of file Map.cpp.
References Player::AddAtClient(), UpdateData::BuildPacket(), WorldObject::GetMapId(), UpdateData::GetPacketCount(), Player::GetSession(), WorldObject::GetTransport(), i_id, m_transports, and WorldSession::SendPacket().
Referenced by Add(), and CreatePlayerOnClient().
SendObjectUpdates()
void Map::SendObjectUpdates () private
Definition at line 2328 of file Map.cpp.
References Object::BuildUpdateData(), and i_objectsToClientUpdate.
Referenced by Update().
SendRemoveTransports()
void Map::SendRemoveTransports (Player * player) const private
Definition at line 1365 of file Map.cpp.
References UpdateData::BuildPacket(), WorldObject::GetMapId(), UpdateData::GetPacketCount(), Player::GetSession(), WorldObject::GetTransport(), i_id, m_transports, Player::RemoveAtClient(), and WorldSession::SendPacket().
Referenced by Remove().
SendToPlayers()
void Map::SendToPlayers (WorldPacket const & data) const
Send a Packet to all players on a map.
Definition at line 1472 of file Map.cpp.
References m_mapRefManager.
Referenced by InstanceData::SendEncounterFrame().
SendToPlayersInZone()
bool Map::SendToPlayersInZone (WorldPacket const & data, uint32 zoneId) const
Send a Packet to all players in a zone. Return false if no player found.
Definition at line 1478 of file Map.cpp.
References m_mapRefManager.
Referenced by Weather::SendWeatherForPlayersInZone().
SendZoneDynamicInfo()
void Map::SendZoneDynamicInfo (Player * player, bool zoneUpdated, bool areaUpdated) const
Function to set the zone dynamic info.
Definition at line 2911 of file Map.cpp.
References Player::GetSession(), WorldObject::GetZoneAndAreaId(), m_areaDynamicInfo, m_defaultLight, m_zoneDynamicInfo, WorldSession::SendPacket(), SMSG_OVERRIDE_LIGHT, SMSG_PLAY_MUSIC, and SMSG_WEATHER.
Referenced by Player::UpdateZone().
setGridObjectDataLoaded()
void Map::setGridObjectDataLoaded (bool pLoaded, uint32 x, uint32 y) inline private
Definition at line 454 of file Map.h.
References getNGrid(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::setGridObjectDataLoaded().
Referenced by EnsureGridLoaded().
SetNavTile()
void Map::SetNavTile (uint32 tileX, uint32 tileY, uint32 tileNumber)
Definition at line 156 of file Map.cpp.
References MMAP::MMapManager::ChangeTile(), MMAP::MMapFactory::createOrGetMMapManager(), GetId(), and GetInstanceId().
SetNewDifficultyCooldown()
void Map::SetNewDifficultyCooldown (TimePoint const & newCooldown)
Definition at line 1258 of file Map.cpp.
References m_dynamicDifficultyCooldown.
Referenced by ChangeMapDifficulty(), and instance_icecrown_citadel::SetData().
setNGrid()
void Map::setNGrid (NGridType * grid, uint32 x, uint32 y) inline private
Definition at line 1403 of file Map.cpp.
References i_grids, MANGOS_ASSERT, MAX_NUMBER_OF_GRIDS, and sLog.
Referenced by EnsureGridCreated(), Initialize(), and UnloadGrid().
SetTimer()
void Map::SetTimer (uint32 t) inline private
Definition at line 429 of file Map.h.
References i_gridExpiry, and MIN_GRID_DELAY.
SetUnloadLock()
void Map::SetUnloadLock (const GridPair & p, bool on) inline
Definition at line 187 of file Map.h.
References getNGrid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::setUnloadExplicitLock(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
SetWeather()
void Map::SetWeather (uint32 zoneId, WeatherType type, float grade, bool permanently)
Set the weather in a zone on this map.
Parameters
zoneId set the weather for which zone
type What weather to set
grade how strong the weather should be
permanently set the weather permanently?
Definition at line 1695 of file Map.cpp.
References WeatherSystem::FindOrCreateWeather(), m_weatherSystem, and Weather::SetWeather().
Referenced by boss_ossirianAI::Aggro(), ChatHandler::HandleChangeWeatherCommand(), and MouthAI::ReceiveAIEvent().
SetZoneMusic()
void Map::SetZoneMusic (uint32 zoneId, uint32 areaId, uint32 musicId)
Function to set the zone music info.
Parameters
zoneId Id of the Zone
musicId for the zone
Definition at line 2964 of file Map.cpp.
References GetPlayers(), LinkedListHead::isEmpty(), m_areaDynamicInfo, m_zoneDynamicInfo, and SMSG_PLAY_MUSIC.
SetZoneOverrideLight()
void Map::SetZoneOverrideLight (uint32 zoneId, uint32 areaId, uint32 lightId, uint32 fadeInTime)
Function to set the zone light override info.
Parameters
zoneId Id of the Zone
lightId to use as override
fadeInTime for the lightId override
Definition at line 3054 of file Map.cpp.
References GetPlayers(), LinkedListHead::isEmpty(), ZoneDynamicInfo::lightFadeInTime, m_areaDynamicInfo, m_defaultLight, m_zoneDynamicInfo, ZoneDynamicInfo::overrideLightId, and SMSG_OVERRIDE_LIGHT.
Referenced by boss_malygosAI::JustDidDialogueStep(), boss_malygosAI::JustReachedHome(), and boss_malygosAI::Reset().
SetZoneWeather()
void Map::SetZoneWeather (uint32 zoneId, uint32 areaId, uint32 weatherId, float weatherGrade)
Function to set the zone weather info.
Parameters
zoneId Id of the Zone
weatherId for the zone
weatherGrade for the given weatherId
Definition at line 3006 of file Map.cpp.
References GetPlayers(), LinkedListHead::isEmpty(), m_areaDynamicInfo, m_zoneDynamicInfo, SMSG_WEATHER, ZoneDynamicInfo::weatherGrade, and ZoneDynamicInfo::weatherId.
Referenced by world_map_kalimdor::SetData(), and WorldState::StartSunsReachPhase().
SpawnedCountForEntry()
uint32 Map::SpawnedCountForEntry (uint32 entry)
Definition at line 2893 of file Map.cpp.
References m_spawnedCount.
Referenced by AreaTrigger_at_socrethar_seat(), Spell::OnCheckCast(), ProcessEventId_event_summon_terokk(), and go_infernaling_summoner::UpdateAI().
TeleportAllPlayersTo()
void Map::TeleportAllPlayersTo (TeleportLocation loc)
Definition at line 1669 of file Map.cpp.
References MapRefManager::getFirst(), Reference< TO, FROM >::getSource(), HavePlayers(), m_mapRefManager, TELEPORT_LOCATION_BG_ENTRY_POINT, and TELEPORT_LOCATION_HOMEBIND.
Referenced by DungeonMap::UnloadAll(), and BattleGroundMap::UnloadAll().
UnloadAll()
void Map::UnloadAll (bool pForce) virtual
Reimplemented in BattleGroundMap, and DungeonMap.
Definition at line 1228 of file Map.cpp.
References GridRefManager< OBJECT >::end(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getX(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getY(), and UnloadGrid().
Referenced by MapManager::DeleteInstance(), DungeonMap::UnloadAll(), BattleGroundMap::UnloadAll(), MapManager::Update(), and ~Map().
UnloadGrid()
bool Map::UnloadGrid (const uint32 & x, const uint32 & y, bool pForce)
Definition at line 1176 of file Map.cpp.
References ActiveObjectsNearGrid(), DEBUG_FILTER_LOG, getNGrid(), i_id, LOG_FILTER_MAP_LOADING, m_bLoadedGrids, m_TerrainData, MANGOS_ASSERT, MAX_NUMBER_OF_GRIDS, ObjectGridUnloader::MoveToRespawnN(), RemoveAllObjectsInRemoveList(), setNGrid(), ObjectGridStoper::StopN(), TerrainInfo::Unload(), and ObjectGridUnloader::UnloadN().
Referenced by UnloadAll(), and RemovalState::Update().
Update()
void Map::Update (const uint32 & t_diff) virtual
update active cells around players and active objects
update players at tick
Process necessary scripts
Reimplemented in BattleGroundMap, and DungeonMap.
Definition at line 734 of file Map.cpp.
References MapRefManager::begin(), Cell::CalculateCellArea(), GridRefManager< OBJECT >::end(), MapRefManager::end(), Messager< T >::Execute(), Player::GetFarSightGuid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::GetGridState(), GetMessager(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Player::GetSession(), Reference< TO, FROM >::getSource(), GetVisibilityDistance(), GetWorldObject(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getX(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::getY(), CellArea::high_bound, i_data, i_id, i_InstanceId, IsBattleGroundOrArena(), isCellMarked(), Object::IsInWorld(), WorldObject::IsPositionValid(), CellArea::low_bound, m_activeNonPlayers, m_activeNonPlayersIter, m_curTime, m_curTimeTm, m_dyn_tree, m_mapRefIter, m_mapRefManager, m_scriptSchedule, m_spawnManager, m_transports, m_transportsIterator, m_weatherSystem, MANGOS_ASSERT, markCell(), MAX_GRID_STATE, resetMarkedCells(), ScriptsProcess(), SendObjectUpdates(), Cell::SetNoCreate(), sMapMgr, TOTAL_NUMBER_OF_CELLS_PER_MAP, SpawnManager::Update(), Player::Update(), Transport::Update(), InstanceData::Update(), DynamicMapTree::update(), WorldSession::UpdateMap(), WeatherSystem::UpdateWeathers(), Visit(), VisitNearbyCellsOf(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by MapUpdateWorker::execute(), DungeonMap::Update(), and BattleGroundMap::Update().
UpdateObjectVisibility()
void Map::UpdateObjectVisibility (WorldObject * obj, Cell cell, const CellPair & cellpair)
Definition at line 1289 of file Map.cpp.
References GetPlayer(), MaNGOS::VisibleChangesNotifier::GetUnvisitedGuids(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), Cell::SetNoCreate(), and Cell::Visit().
Referenced by Add(), CreatePlayerOnClient(), Remove(), and WorldObject::UpdateObjectVisibility().
Visit()
template<class T , class CONTAINER > void Map::Visit (const Cell & cell, TypeContainerVisitor< T, CONTAINER > & visitor) inline
Definition at line 634 of file Map.h.
References Cell::CellX(), Cell::CellY(), EnsureGridLoaded(), getNGrid(), Cell::GridX(), Cell::GridY(), loaded(), Cell::NoCreate(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
Referenced by GridCrawler::execute(), Update(), Cell::Visit(), Cell::VisitCircle(), and VisitNearbyCellsOf().
VisitNearbyCellsOf()
void Map::VisitNearbyCellsOf (WorldObject * obj, TypeContainerVisitor< MaNGOS::ObjectUpdater, GridTypeMapContainer > & gridVisitor, TypeContainerVisitor< MaNGOS::ObjectUpdater, WorldTypeMapContainer > & worldVisitor)
Definition at line 709 of file Map.cpp.
References Cell::CalculateCellArea(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), GetVisibilityDistance(), CellArea::high_bound, isCellMarked(), Object::IsInWorld(), CellArea::low_bound, markCell(), Cell::SetNoCreate(), TOTAL_NUMBER_OF_CELLS_PER_MAP, Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Update().
Friends And Related Function Documentation
MapReference
friend class MapReference friend
Definition at line 119 of file Map.h.
ObjectGridLoader
friend class ObjectGridLoader friend
Definition at line 120 of file Map.h.
ObjectWorldLoader
friend class ObjectWorldLoader friend
Definition at line 121 of file Map.h.
Field Documentation
i_data
InstanceData* Map::i_data private
Definition at line 506 of file Map.h.
Referenced by Add(), CreateInstanceData(), GetInstanceData(), OnEventHappened(), Remove(), Update(), and ~Map().
i_gridExpiry
time_t Map::i_gridExpiry private
Definition at line 489 of file Map.h.
Referenced by EnsureGridCreated(), GetGridExpiry(), ResetGridExpiry(), and SetTimer().
i_grids
NGridType* Map::i_grids[MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS] private
Definition at line 493 of file Map.h.
Referenced by GetLoadedGridsCount(), getNGrid(), and setNGrid().
i_id
uint32 Map::i_id protected
Definition at line 465 of file Map.h.
Referenced by EnsureGridLoadedAtEnter(), GetHeightInRange(), GetId(), GetMaxPlayers(), SendInitTransports(), SendRemoveTransports(), UnloadGrid(), and Update().
i_InstanceId
uint32 Map::i_InstanceId protected
Definition at line 466 of file Map.h.
Referenced by CreateInstanceData(), GetInstanceId(), and Update().
i_mapEntry
MapEntry const* Map::i_mapEntry protected
Definition at line 463 of file Map.h.
Referenced by DungeonMap::Add(), DungeonMap::DungeonMap(), GetEntry(), GetMapName(), Initialize(), Instanceable(), IsBattleArena(), IsBattleGround(), IsBattleGroundOrArena(), IsContinent(), IsDungeon(), IsNonRaidDungeon(), and IsRaid().
i_objectsToClientUpdate
std::set<Object*> Map::i_objectsToClientUpdate private
Definition at line 460 of file Map.h.
Referenced by AddUpdateObject(), RemoveUpdateObject(), and SendObjectUpdates().
i_objectsToRemove
WorldObjectSet Map::i_objectsToRemove private
Definition at line 501 of file Map.h.
Referenced by AddObjectToRemoveList(), and RemoveAllObjectsInRemoveList().
i_script_id
uint32 Map::i_script_id private
Definition at line 507 of file Map.h.
Referenced by CreateInstanceData(), and GetScriptId().
i_spawnMode
uint8 Map::i_spawnMode protected
Definition at line 464 of file Map.h.
Referenced by ChangeMapDifficulty(), GetSpawnMode(), and IsHeroic().
m_activeNonPlayers
ActiveNonPlayers Map::m_activeNonPlayers protected
Definition at line 475 of file Map.h.
Referenced by ActiveObjectsNearGrid(), AddToActive(), RemoveFromActive(), and Update().
m_activeNonPlayersIter
ActiveNonPlayers::iterator Map::m_activeNonPlayersIter protected
Definition at line 476 of file Map.h.
Referenced by RemoveFromActive(), and Update().
m_areaDynamicInfo
ZoneDynamicInfoMap Map::m_areaDynamicInfo private
Definition at line 556 of file Map.h.
Referenced by SendZoneDynamicInfo(), SetZoneMusic(), SetZoneOverrideLight(), and SetZoneWeather().
m_bLoadedGrids
bool Map::m_bLoadedGrids[MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS] private
Definition at line 497 of file Map.h.
Referenced by EnsureGridCreated(), Initialize(), LoadMapAndVMap(), and UnloadGrid().
m_CreatureGuids
ObjectGuidGenerator<HIGHGUID_UNIT> Map::m_CreatureGuids private
Definition at line 510 of file Map.h.
Referenced by GenerateLocalLowGuid(), and Initialize().
m_creatureLinkingHolder
CreatureLinkingHolder Map::m_creatureLinkingHolder private
Definition at line 524 of file Map.h.
Referenced by GetCreatureLinkingHolder().
m_curTime
time_t Map::m_curTime private
Definition at line 490 of file Map.h.
Referenced by GetCurrentTime_t(), and Update().
m_curTimeTm
tm Map::m_curTimeTm private
Definition at line 491 of file Map.h.
Referenced by GetCurrentTime_tm(), and Update().
m_dataContainer
MapDataContainer Map::m_dataContainer private
Definition at line 550 of file Map.h.
Referenced by GetMapDataContainer().
m_dbGuidObjects
std::map<std::pair<HighGuid, uint32>, std::vector<WorldObject*> > Map::m_dbGuidObjects protected
Definition at line 480 of file Map.h.
Referenced by AddDbGuidObject(), GetCreature(), GetGameObject(), and RemoveDbGuidObject().
m_defaultLight
uint32 Map::m_defaultLight private
Definition at line 557 of file Map.h.
Referenced by SendZoneDynamicInfo(), and SetZoneOverrideLight().
m_dyn_tree
DynamicMapTree Map::m_dyn_tree private
Definition at line 527 of file Map.h.
Referenced by ContainsGameObjectModel(), GetHeight(), GetHeightInRange(), GetHitPosition(), InsertGameObjectModel(), IsInLineOfSight(), RemoveGameObjectModel(), and Update().
m_dynamicDifficultyCooldown
TimePoint Map::m_dynamicDifficultyCooldown private
Definition at line 559 of file Map.h.
Referenced by GetNewDifficultyCooldown(), and SetNewDifficultyCooldown().
m_DynObjectGuids
ObjectGuidGenerator<HIGHGUID_DYNAMICOBJECT> Map::m_DynObjectGuids private
Definition at line 513 of file Map.h.
Referenced by GenerateLocalLowGuid().
m_GameObjectGuids
ObjectGuidGenerator<HIGHGUID_GAMEOBJECT> Map::m_GameObjectGuids private
Definition at line 511 of file Map.h.
Referenced by GenerateLocalLowGuid(), and Initialize().
m_graveyardManager
GraveyardManager Map::m_graveyardManager protected
Definition at line 487 of file Map.h.
Referenced by GetGraveyardManager(), and Initialize().
m_mapRefIter
MapRefManager::iterator Map::m_mapRefIter protected
Definition at line 472 of file Map.h.
Referenced by Remove(), and Update().
m_mapRefManager
MapRefManager Map::m_mapRefManager protected
Definition at line 471 of file Map.h.
Referenced by ActiveObjectsNearGrid(), GetPlayers(), GetPlayersCountExceptGMs(), HavePlayers(), DungeonMap::PermBindAllPlayers(), DungeonMap::Remove(), DungeonMap::Reset(), DungeonMap::SendResetWarnings(), SendToPlayers(), SendToPlayersInZone(), MapReference::sourceObjectDestroyLink(), MapReference::targetObjectBuildLink(), MapReference::targetObjectDestroyLink(), TeleportAllPlayersTo(), and Update().
m_messager
Messager<Map> Map::m_messager protected
Definition at line 485 of file Map.h.
Referenced by GetMessager().
m_objectsPerStringId
std::unordered_map<uint32, StringIdMapStorage> Map::m_objectsPerStringId private
Definition at line 548 of file Map.h.
Referenced by AddStringIdObject(), GetCreatures(), GetGameObjects(), GetWorldObjects(), and RemoveStringIdObject().
m_objectsStore
MapStoredObjectTypesContainer Map::m_objectsStore protected
Definition at line 477 of file Map.h.
Referenced by GetCreature(), GetDynamicObject(), GetGameObject(), GetObjectsStore(), and GetPet().
m_objRemoveList
std::set<ObjectGuid> Map::m_objRemoveList
Definition at line 411 of file Map.h.
Referenced by MaNGOS::VisibleNotifier::Notify(), and Remove().
m_onEventNotifiedIter
WorldObjectSet::iterator Map::m_onEventNotifiedIter protected
Definition at line 483 of file Map.h.
Referenced by OnEventHappened(), and RemoveFromOnEventNotified().
m_onEventNotifiedObjects
WorldObjectSet Map::m_onEventNotifiedObjects protected
Definition at line 482 of file Map.h.
Referenced by AddToOnEventNotified(), OnEventHappened(), and RemoveFromOnEventNotified().
m_persistentState
MapPersistentState* Map::m_persistentState protected
Definition at line 469 of file Map.h.
Referenced by GetPersistentState(), Initialize(), and ~Map().
m_PetGuids
ObjectGuidGenerator<HIGHGUID_PET> Map::m_PetGuids private
Definition at line 514 of file Map.h.
Referenced by GenerateLocalLowGuid().
m_scriptSchedule
ScriptScheduleMap Map::m_scriptSchedule private
Definition at line 504 of file Map.h.
Referenced by ScriptCommandStart(), ScriptsProcess(), ScriptsStart(), and Update().
m_spawnedCount
std::unordered_map<uint32, std::set<ObjectGuid> > Map::m_spawnedCount private
Definition at line 536 of file Map.h.
Referenced by AddToSpawnCount(), RemoveFromSpawnCount(), and SpawnedCountForEntry().
m_spawnManager
SpawnManager Map::m_spawnManager private
Definition at line 539 of file Map.h.
Referenced by GetSpawnManager(), Initialize(), and Update().
m_spellListContainer
std::shared_ptr<CreatureSpellListContainer> Map::m_spellListContainer private
Definition at line 551 of file Map.h.
m_tempCreatures
std::map<uint32, uint32> Map::m_tempCreatures protected
Definition at line 478 of file Map.h.
Referenced by GetTempCreatures().
m_tempPets
std::map<uint32, uint32> Map::m_tempPets protected
Definition at line 479 of file Map.h.
Referenced by GetTempPets().
m_TerrainData
TerrainInfo* const Map::m_TerrainData private
Definition at line 496 of file Map.h.
Referenced by GetHeight(), GetHeightInRange(), GetReachableRandomPosition(), GetTerrain(), Initialize(), LoadMapAndVMap(), UnloadGrid(), and ~Map().
m_tileNumberPerTile
std::map<std::pair<uint32, uint32>, uint32> Map::m_tileNumberPerTile private
Definition at line 561 of file Map.h.
Referenced by ChangeGOPathfinding().
m_transportGuids
ObjectGuidGenerator<HIGHGUID_TRANSPORT> Map::m_transportGuids private
Definition at line 512 of file Map.h.
m_transports
TransportSet Map::m_transports private
Definition at line 533 of file Map.h.
Referenced by AddTransport(), GetTransport(), GetTransports(), RemoveTransport(), SendInitTransports(), SendRemoveTransports(), Update(), and ~Map().
m_transportsIterator
TransportSet::iterator Map::m_transportsIterator private
Definition at line 534 of file Map.h.
Referenced by RemoveTransport(), and Update().
m_unloadTimer
uint32 Map::m_unloadTimer protected
Definition at line 467 of file Map.h.
Referenced by DungeonMap::Add(), CanUnload(), DungeonMap::DungeonMap(), DungeonMap::Remove(), DungeonMap::Reset(), and BattleGroundMap::SetUnload().
m_variableManager
WorldStateVariableManager Map::m_variableManager private
Definition at line 553 of file Map.h.
Referenced by GetVariableManager(), and Initialize().
m_VehicleGuids
ObjectGuidGenerator<HIGHGUID_VEHICLE> Map::m_VehicleGuids private
Definition at line 515 of file Map.h.
Referenced by GenerateLocalLowGuid().
m_VisibleDistance
float Map::m_VisibleDistance protected
Definition at line 468 of file Map.h.
Referenced by GetVisibilityDistance(), InitVisibilityDistance(), DungeonMap::InitVisibilityDistance(), and BattleGroundMap::InitVisibilityDistance().
m_weatherSystem
WeatherSystem* Map::m_weatherSystem private
Definition at line 530 of file Map.h.
Referenced by GetWeatherSystem(), Map(), SetWeather(), Update(), and ~Map().
m_zoneDynamicInfo
ZoneDynamicInfoMap Map::m_zoneDynamicInfo private
Definition at line 555 of file Map.h.
Referenced by SendZoneDynamicInfo(), SetZoneMusic(), SetZoneOverrideLight(), and SetZoneWeather().
marked_cells
std::bitset<TOTAL_NUMBER_OF_CELLS_PER_MAP* TOTAL_NUMBER_OF_CELLS_PER_MAP> Map::marked_cells private
Definition at line 499 of file Map.h.
Referenced by isCellMarked(), markCell(), and resetMarkedCells().
The documentation for this class was generated from the following files:
Map.h
Map.cpp