CMaNGOS_WoTLK: CliRunnable Class Reference
CliRunnable Class Reference
Mangos Daemon
Command Line Interface handling thread.
#include <CliRunnable.h>
Public Member Functions
void run () override
Thread start
Public Member Functions inherited from MaNGOS::Runnable
virtual ~Runnable ()
void incReference ()
void decReference ()
Detailed Description
Command Line Interface handling thread.
Definition at line 30 of file CliRunnable.h.
Member Function Documentation
run()
void CliRunnable::run (void) override virtual
Thread start
Init new SQL thread for the world database (one connection call enough)
Display the list of available CLI functions then beep
As long as the World is running (no World::m_stopEvent), get the command line and handle it
End the database thread
Implements MaNGOS::Runnable.
Definition at line 609 of file CliRunnable.cpp.
References commandFinished(), consoleToUtf8(), World::IsStopped(), sConfig, SEC_CONSOLE, SHUTDOWN_EXIT_CODE, sLog, World::StopNow(), sWorld, DatabaseMysql::ThreadEnd(), DatabaseMysql::ThreadStart(), utf8print(), and WorldDatabase.
The documentation for this class was generated from the following files:
CliRunnable.h
CliRunnable.cpp