CMaNGOS_WoTLK: AreaAura Class Reference
AreaAura Class Reference
#include <SpellAuras.h>
Public Member Functions
AreaAura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster=nullptr, Item *castItem=nullptr, uint32 originalRankSpellId=0)
virtual ~AreaAura ()
Public Member Functions inherited from Aura
void HandleNULL (bool, bool)
void HandleUnused (bool, bool)
void HandleNoImmediateEffect (bool, bool)
void HandleBindSight (bool apply, bool Real)
void HandleModPossess (bool apply, bool Real)
void HandlePeriodicDamage (bool apply, bool Real)
void HandleAuraDummy (bool apply, bool Real)
void HandleAuraPeriodicDummy (bool apply, bool Real)
void HandleModConfuse (bool apply, bool Real)
void HandleModCharm (bool apply, bool Real)
void HandleModFear (bool apply, bool Real)
void HandlePeriodicHeal (bool apply, bool Real)
void HandleModAttackSpeed (bool apply, bool Real)
void HandleModMeleeRangedSpeedPct (bool apply, bool Real)
void HandleModCombatSpeedPct (bool apply, bool Real)
void HandleModThreat (bool apply, bool Real)
void HandleModTaunt (bool Apply, bool Real)
void HandleFeignDeath (bool apply, bool Real)
void HandleAuraModDisarm (bool apply, bool Real)
void HandleAuraModStalked (bool apply, bool Real)
void HandleAuraWaterWalk (bool apply, bool Real)
void HandleAuraFeatherFall (bool apply, bool Real)
void HandleAuraHover (bool apply, bool Real)
void HandleAddModifier (bool apply, bool Real)
void HandleAuraModStun (bool apply, bool Real)
void HandleModDamageDone (bool apply, bool Real)
void HandleAuraDamageShield (bool apply, bool real)
void HandleAuraUntrackable (bool apply, bool Real)
void HandleAuraEmpathy (bool apply, bool Real)
void HandleModOffhandDamagePercent (bool apply, bool Real)
void HandleAuraModRangedAttackPower (bool apply, bool Real)
void HandleAuraModIncreaseEnergyPercent (bool apply, bool Real)
void HandleAuraModIncreaseHealthPercent (bool apply, bool Real)
void HandleAuraModRegenInterrupt (bool apply, bool Real)
void HandleModMeleeSpeedPct (bool apply, bool Real)
void HandlePeriodicTriggerSpell (bool apply, bool Real)
void HandlePeriodicTriggerSpellWithValue (bool apply, bool Real)
void HandlePeriodicEnergize (bool apply, bool Real)
void HandleAuraModResistanceExclusive (bool apply, bool Real)
void HandleAuraSafeFall (bool Apply, bool Real)
void HandleAuraModPetTalentsPoints (bool Apply, bool Real)
void HandleModStealth (bool apply, bool Real)
void HandleModStealthDetect (bool apply, bool real)
void HandleInvisibility (bool apply, bool Real)
void HandleInvisibilityDetect (bool apply, bool Real)
void HandleAuraModTotalHealthPercentRegen (bool apply, bool Real)
void HandleAuraModTotalManaPercentRegen (bool apply, bool Real)
void HandleAuraModResistance (bool apply, bool Real)
void HandleAuraModRoot (bool apply, bool Real)
void HandleAuraModSilence (bool apply, bool Real)
void HandleAuraModStat (bool apply, bool Real)
void HandleDetectAmore (bool apply, bool Real)
void HandleAuraFakeInebriation (bool apply, bool Real)
void HandleAuraModIncreaseSpeed (bool Apply, bool Real)
void HandleAuraModIncreaseMountedSpeed (bool apply, bool Real)
void HandleAuraModIncreaseFlightSpeed (bool apply, bool Real)
void HandleAuraModDecreaseSpeed (bool apply, bool Real)
void HandleAuraModUseNormalSpeed (bool Apply, bool Real)
void HandleAuraModIncreaseHealth (bool apply, bool Real)
void HandleAuraModIncreaseEnergy (bool apply, bool Real)
void HandleAuraModShapeshift (bool apply, bool Real)
void HandleAuraModEffectImmunity (bool apply, bool Real)
void HandleAuraModStateImmunity (bool apply, bool Real)
void HandleAuraModSchoolImmunity (bool apply, bool Real)
void HandleAuraModDmgImmunity (bool apply, bool Real)
void HandleAuraModDispelImmunity (bool apply, bool Real)
void HandleAuraProcTriggerSpell (bool apply, bool Real)
void HandleAuraTrackCreatures (bool apply, bool Real)
void HandleAuraTrackResources (bool apply, bool Real)
void HandleAuraModParryPercent (bool apply, bool Real)
void HandleAuraModDodgePercent (bool apply, bool Real)
void HandleAuraModBlockPercent (bool apply, bool Real)
void HandleAuraModCritPercent (bool apply, bool Real)
void HandlePeriodicLeech (bool apply, bool Real)
void HandleModHitChance (bool apply, bool Real)
void HandleModSpellHitChance (bool apply, bool Real)
void HandleAuraModScale (bool apply, bool Real)
void HandlePeriodicManaLeech (bool apply, bool Real)
void HandlePeriodicHealthFunnel (bool apply, bool Real)
void HandleModCastingSpeed (bool apply, bool Real)
void HandleAuraMounted (bool apply, bool Real)
void HandleWaterBreathing (bool apply, bool real)
void HandleModStealthLevel (bool apply, bool real)
void HandleModWaterBreathing (bool apply, bool Real)
void HandleModBaseResistance (bool apply, bool Real)
void HandleModRegen (bool apply, bool Real)
void HandleModPowerRegen (bool apply, bool Real)
void HandleModPowerRegenPCT (bool Apply, bool Real)
void HandleModHealingPCT (bool apply, bool real)
void HandleChannelDeathItem (bool apply, bool Real)
void HandleDamagePercentTaken (bool apply, bool Real)
void HandlePeriodicDamagePCT (bool apply, bool Real)
void HandleAuraModAttackPower (bool apply, bool Real)
void HandleAuraTransform (bool apply, bool Real)
void HandleModSpellCritChance (bool apply, bool Real)
void HandleAuraModIncreaseSwimSpeed (bool Apply, bool Real)
void HandleModPowerCostPCT (bool apply, bool Real)
void HandleModPowerCost (bool apply, bool Real)
void HandleFarSight (bool apply, bool Real)
void HandleModPossessPet (bool apply, bool Real)
void HandleModMechanicImmunity (bool apply, bool Real)
void HandleModMechanicImmunityMask (bool apply, bool Real)
void HandleAuraModSkill (bool apply, bool Real)
void HandleModDamagePercentDone (bool apply, bool Real)
void HandleModPercentStat (bool apply, bool Real)
void HandleModResistancePercent (bool apply, bool Real)
void HandleAuraModBaseResistancePercent (bool apply, bool Real)
void HandleAuraTrackStealthed (bool apply, bool Real)
void HandleForceReaction (bool apply, bool Real)
void HandleAuraModRangedHaste (bool apply, bool Real)
void HandleRangedAmmoHaste (bool apply, bool Real)
void HandleModHealingDone (bool Apply, bool Real)
void HandleModTotalPercentStat (bool apply, bool Real)
void HandleAuraModTotalThreat (bool apply, bool Real)
void HandleModUnattackable (bool Apply, bool Real)
void HandleAuraModPacify (bool apply, bool Real)
void HandleAuraGhost (bool apply, bool Real)
void HandleAuraAllowFlight (bool apply, bool Real)
void HandleModRating (bool apply, bool Real)
void HandleModRatingFromStat (bool apply, bool Real)
void HandleModTargetResistance (bool apply, bool Real)
void HandleAuraModAttackPowerPercent (bool apply, bool Real)
void HandleAuraModRangedAttackPowerPercent (bool apply, bool Real)
void HandleAuraModRangedAttackPowerOfStatPercent (bool apply, bool Real)
void HandleAuraModAttackPowerOfStatPercent (bool apply, bool Real)
void HandleAuraModAttackPowerOfArmor (bool apply, bool Real)
void HandleSpiritOfRedemption (bool apply, bool Real)
void HandleAoECharm (bool apply, bool Real)
void HandleModManaRegen (bool apply, bool Real)
void HandleComprehendLanguage (bool apply, bool Real)
void HandleShieldBlockValue (bool apply, bool Real)
void HandleModSpellCritChanceShool (bool apply, bool Real)
void HandleAuraRetainComboPoints (bool apply, bool Real)
void HandleModSpellDamagePercentFromStat (bool apply, bool Real)
void HandleModSpellHealingPercentFromStat (bool apply, bool Real)
void HandleAuraModDispelResist (bool apply, bool Real)
void HandleAuraControlVehicle (bool apply, bool Real)
Such auras are applied from a caster(=player) to a vehicle.
void HandleModSpellDamagePercentFromAttackPower (bool apply, bool Real)
void HandleModSpellHealingPercentFromAttackPower (bool apply, bool Real)
void HandleAuraModPacifyAndSilence (bool apply, bool Real)
void HandleAuraModIncreaseMaxHealth (bool apply, bool Real)
void HandleAuraModExpertise (bool apply, bool Real)
void HandleForceMoveForward (bool apply, bool Real)
void HandleAuraModResistenceOfStatPercent (bool apply, bool Real)
void HandleAuraPowerBurn (bool apply, bool Real)
void HandleSchoolAbsorb (bool apply, bool Real)
void HandlePreventFleeing (bool apply, bool Real)
void HandleManaShield (bool apply, bool Real)
void HandleArenaPreparation (bool apply, bool Real)
void HandleAuraMirrorImage (bool apply, bool Real)
void HandleAuraConvertRune (bool apply, bool Real)
void HandleAuraIncreaseBaseHealthPercent (bool apply, bool Real)
void HandleNoReagentUseAura (bool Apply, bool Real)
void HandlePhase (bool apply, bool Real)
void HandleModTargetArmorPct (bool Apply, bool Real)
void HandleAuraModAllCritChance (bool apply, bool Real)
void HandleAuraOpenStable (bool apply, bool Real)
void HandleAuraAddMechanicAbilities (bool apply, bool Real)
void HandleAuraStopNaturalManaRegen (bool apply, bool Real)
void HandleAuraSetVehicleId (bool apply, bool Real)
void HandleMirrorName (bool apply, bool Real)
void HandlePreventResurrection (bool apply, bool Real)
void HandleFactionOverride (bool apply, bool Real)
void HandlePrayerOfMending (bool apply, bool Real)
void HandleTriggerLinkedAura (bool apply, bool Real)
void HandleAuraDetaunt (bool Apply, bool Real)
void HandleOverrideClassScript (bool apply, bool real)
void HandleAuraAllowOnlyAbility (bool apply, bool real)
virtual ~Aura ()
void SetModifier (AuraType type, int32 amount, uint32 periodicTime, int32 miscValue)
Modifier * GetModifier ()
Modifier const * GetModifier () const
int32 GetMiscValue () const
int32 GetMiscBValue () const
SpellEntry const * GetSpellProto () const
uint32 GetId () const
ObjectGuid const & GetCastItemGuid () const
ObjectGuid const & GetCasterGuid () const
Unit * GetCaster () const
Unit * GetTarget () const
SpellEffectIndex GetEffIndex () const
int32 GetBasePoints () const
int32 GetAmount () const
void SetAmount (int32 amount)
int32 GetAuraMaxDuration () const
int32 GetAuraDuration () const
time_t GetAuraApplyTime () const
uint32 GetAuraTicks () const
uint32 GetAuraMaxTicks () const
uint32 GetStackAmount () const
void SetLoadedState (int32 damage, uint32 periodicTime)
bool IsPositive () const
bool IsPersistent () const
bool IsAreaAura () const
bool IsPeriodic () const
bool IsSaveToDbAura () const
void ApplyModifier (bool apply, bool Real=false)
void UpdateAuraScaling ()
void UpdateAura (uint32 diff)
void SetRemoveMode (AuraRemoveMode mode)
AuraRemoveMode GetRemoveMode ()
virtual Unit * GetTriggerTarget () const
void HandleShapeshiftBoosts (bool apply)
void TriggerSpell ()
void TriggerSpellWithValue ()
ClassFamilyMask const & GetAuraSpellClassMask () const
bool isAffectedOnSpell (SpellEntry const *spell) const
bool CanProcFrom (SpellEntry const *spell, uint32 procFlag, uint32 EventProcEx, uint32 procEx, bool active, bool useClassMask) const
SpellAuraHolder * GetHolder ()
SpellAuraHolder const * GetHolder () const
bool IsLastAuraOnHolder ()
bool HasMechanic (uint32 mechanic) const
SpellModifier * GetSpellModifier ()
void UseMagnet ()
bool IsMagnetUsed () const
AuraScript * GetAuraScript () const
void SetScriptValue (uint64 value)
uint64 GetScriptValue ()
void SetScriptStorage (ScriptStorage *storage)
ScriptStorage * GetScriptStorage ()
void OnAuraInit ()
int32 OnAuraValueCalculate (Unit *caster, int32 currentValue)
void OnDamageCalculate (Unit *victim, int32 &advertisedBenefit, float &totalMod)
void OnApply (bool apply)
void OnAfterApply (bool apply)
bool OnCheckProc (ProcExecutionData &data)
SpellAuraProcResult OnProc (ProcExecutionData &data)
void OnAbsorb (int32 &currentAbsorb, int32 &remainingDamage, uint32 &reflectedSpellId, int32 &reflectDamage, bool &preventedDeath, bool &dropCharge)
void OnManaAbsorb (int32 &currentAbsorb)
void OnAuraDeathPrevention (int32 &remainingDamage)
void OnPeriodicTrigger (PeriodicTriggerData &data)
void OnPeriodicDummy ()
void OnPeriodicTickEnd ()
void OnPeriodicCalculateAmount (uint32 &amount)
void OnHeartbeat ()
uint32 GetAuraScriptCustomizationValue ()
void ForcePeriodicity (uint32 periodicTime)
Protected Member Functions
void Update (uint32 diff) override
Protected Member Functions inherited from Aura
Aura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster=nullptr, Item *castItem=nullptr)
void PeriodicTick ()
void PeriodicDummyTick ()
bool IsCritFromAbilityAura (Unit *caster, uint32 &damage) const
void ReapplyAffectedPassiveAuras ()
void PickTargetsForSpellTrigger (Unit *&triggerCaster, Unit *&triggerTarget, WorldObject *&triggerTargetObject, SpellEntry const *spellInfo)
void CastTriggeredSpell (PeriodicTriggerData &data)
Private Attributes
float m_radius
AreaAuraType m_areaAuraType
uint32 m_originalRankSpellId
Additional Inherited Members
Static Public Member Functions inherited from Aura
static uint32 CalculateAuraEffectValue (Unit *caster, Unit *target, SpellEntry const *spellProto, SpellEffectIndex effIdx, uint32 value)
Protected Attributes inherited from Aura
Modifier m_modifier
SpellModifier * m_spellmod
time_t m_applyTime
int32 m_currentBasePoints
int32 m_periodicTimer
uint32 m_periodicTick
AuraRemoveMode m_removeMode: 8
SpellEffectIndex m_effIndex: 8
bool m_positive: 1
bool m_isPeriodic: 1
bool m_isAreaAura: 1
bool m_isPersistent: 1
bool m_magnetUsed: 1
SpellAuraHolder *const m_spellAuraHolder
uint64 m_scriptValue
ScriptStorage * m_storage
Detailed Description
Definition at line 613 of file SpellAuras.h.
Constructor & Destructor Documentation
AreaAura()
AreaAura::AreaAura (SpellEntry const * spellproto, SpellEffectIndex eff, int32 const * currentDamage, int32 const * currentBasePoints, SpellAuraHolder * holder, Unit * target, Unit * caster = nullptr, Item * castItem = nullptr, uint32 originalRankSpellId = 0)
Definition at line 459 of file SpellAuras.cpp.
References AREA_AURA_ENEMY, AREA_AURA_FRIEND, AREA_AURA_OWNER, AREA_AURA_PARTY, AREA_AURA_PET, AREA_AURA_RAID, SpellEntry::Effect, SpellEntry::EffectRadiusIndex, WorldObject::GetSpellModOwner(), GetSpellRadius(), Object::GetTypeId(), SpellEntry::Id, m_areaAuraType, Modifier::m_auraname, Aura::m_effIndex, Aura::m_isAreaAura, Aura::m_modifier, m_radius, MANGOS_ASSERT, sLog, SPELL_AURA_NONE, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AREA_AURA_OWNER, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_PET, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELLMOD_RADIUS, sSpellRadiusStore, and TYPEID_UNIT.
Referenced by Update().
~AreaAura()
AreaAura::~AreaAura () virtual
Definition at line 510 of file SpellAuras.cpp.
Member Function Documentation
Update()
void AreaAura::Update (uint32 diff) override protected virtual
Reimplemented from Aura.
Definition at line 567 of file SpellAuras.cpp.
References SpellAuraHolder::AddAura(), ByteConverter::apply(), Aura::ApplyModifier(), AREA_AURA_ENEMY, AREA_AURA_FRIEND, AREA_AURA_OWNER, AREA_AURA_PARTY, AREA_AURA_PET, AREA_AURA_RAID, AreaAura(), SpellEntry::CalculateSimpleValue(), WorldObject::CalculateSpellEffectValue(), Unit::CanAssistSpell(), CreateSpellAuraHolder(), Aura::GetAuraDuration(), Unit::GetBeneficiaryPlayer(), Aura::GetCaster(), Aura::GetCasterGuid(), Aura::GetEffIndex(), Group::GetFirstMember(), Player::GetGroup(), Group::GetId(), Aura::GetId(), Unit::GetMaster(), Unit::GetMasterGuid(), Aura::GetModifier(), Object::GetObjectGuid(), Unit::GetPet(), Aura::GetSpellProto(), Aura::GetTarget(), Object::GetTypeId(), SpellEntry::HasAttribute(), Unit::HasAura(), Unit::hasUnitState(), SpellEntry::Id, Unit::IsAlive(), Unit::IsPlayerControlled(), IsStackableSpell(), WorldObject::IsWithinDistInMap(), m_areaAuraType, Modifier::m_auraname, Modifier::m_baseAmount, Aura::m_currentBasePoints, Aura::m_effIndex, Aura::m_modifier, m_originalRankSpellId, m_radius, GroupReference::next(), Unit::RemoveSingleAuraFromSpellAuraHolder(), Group::SameSubGroup(), SpellAuraHolder::SetAuraDuration(), SpellAuraHolder::SetState(), SPELL_ATTR_EX3_ONLY_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER_CONTROLLED_NPC, SPELL_ATTR_EX6_IGNORE_PHASE_SHIFT, SPELL_AURA_NONE, SPELLAURAHOLDER_STATE_READY, sSpellMgr, TYPEID_PLAYER, UNIT_STAT_ISOLATED, Aura::Update(), Cell::VisitAllObjects(), and Cell::VisitGridObjects().
Field Documentation
m_areaAuraType
AreaAuraType AreaAura::m_areaAuraType private
Definition at line 622 of file SpellAuras.h.
Referenced by AreaAura(), and Update().
m_originalRankSpellId
uint32 AreaAura::m_originalRankSpellId private
Definition at line 623 of file SpellAuras.h.
Referenced by Update().
m_radius
float AreaAura::m_radius private
Definition at line 621 of file SpellAuras.h.
Referenced by AreaAura(), and Update().
The documentation for this class was generated from the following files:
SpellAuras.h
SpellAuras.cpp