CMaNGOS_WoTLK: PlayerSocial Class Reference
PlayerSocial Class Reference
#include <SocialMgr.h>
Public Member Functions
PlayerSocial ()
~PlayerSocial ()
bool AddToSocialList (ObjectGuid friend_guid, bool ignore)
void RemoveFromSocialList (ObjectGuid friend_guid, bool ignore)
void SetFriendNote (ObjectGuid friend_guid, std::string note)
void SendSocialList ()
bool HasFriend (ObjectGuid friend_guid)
bool HasIgnore (ObjectGuid ignore_guid)
void SetPlayerGuid (ObjectGuid guid)
uint32 GetNumberOfSocialsWithFlag (SocialFlag flag)
Private Attributes
PlayerSocialMap m_playerSocialMap
uint32 m_playerLowGuid
Friends
class SocialMgr
Detailed Description
Definition at line 112 of file SocialMgr.h.
Constructor & Destructor Documentation
PlayerSocial()
PlayerSocial::PlayerSocial ()
Definition at line 31 of file SocialMgr.cpp.
~PlayerSocial()
PlayerSocial::~PlayerSocial ()
Definition at line 35 of file SocialMgr.cpp.
References m_playerSocialMap.
Member Function Documentation
AddToSocialList()
bool PlayerSocial::AddToSocialList (ObjectGuid friend_guid, bool ignore)
Definition at line 51 of file SocialMgr.cpp.
References CharacterDatabase, FriendInfo::Flags, ObjectGuid::GetCounter(), GetNumberOfSocialsWithFlag(), m_playerLowGuid, m_playerSocialMap, Database::PExecute(), SOCIAL_FLAG_FRIEND, SOCIAL_FLAG_IGNORED, SOCIALMGR_FRIEND_LIMIT, and SOCIALMGR_IGNORE_LIMIT.
Referenced by WorldSession::HandleAddFriendOpcodeCallBack(), and WorldSession::HandleAddIgnoreOpcodeCallBack().
GetNumberOfSocialsWithFlag()
uint32 PlayerSocial::GetNumberOfSocialsWithFlag (SocialFlag flag)
Definition at line 40 of file SocialMgr.cpp.
References m_playerSocialMap.
Referenced by AddToSocialList().
HasFriend()
bool PlayerSocial::HasFriend (ObjectGuid friend_guid)
Definition at line 157 of file SocialMgr.cpp.
References ObjectGuid::GetCounter(), m_playerSocialMap, and SOCIAL_FLAG_FRIEND.
Referenced by WorldSession::HandleAddFriendOpcodeCallBack().
HasIgnore()
bool PlayerSocial::HasIgnore (ObjectGuid ignore_guid)
Definition at line 165 of file SocialMgr.cpp.
References ObjectGuid::GetCounter(), m_playerSocialMap, and SOCIAL_FLAG_IGNORED.
Referenced by Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), Spell::EffectDuel(), WorldSession::HandleAddIgnoreOpcodeCallBack(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleInitiateTradeOpcode(), and Channel::Invite().
RemoveFromSocialList()
void PlayerSocial::RemoveFromSocialList (ObjectGuid friend_guid, bool ignore)
Definition at line 85 of file SocialMgr.cpp.
References CharacterDatabase, ObjectGuid::GetCounter(), m_playerLowGuid, m_playerSocialMap, Database::PExecute(), SOCIAL_FLAG_FRIEND, and SOCIAL_FLAG_IGNORED.
Referenced by WorldSession::HandleDelFriendOpcode(), and WorldSession::HandleDelIgnoreOpcode().
SendSocialList()
void PlayerSocial::SendSocialList ()
Definition at line 121 of file SocialMgr.cpp.
References FriendInfo::Area, FriendInfo::Class, DEBUG_LOG, FriendInfo::Flags, Player::GetSession(), HIGHGUID_PLAYER, FriendInfo::Level, m_playerLowGuid, m_playerSocialMap, FriendInfo::Note, WorldSession::SendPacket(), SMSG_CONTACT_LIST, sObjectMgr, SOCIAL_FLAG_FRIEND, sSocialMgr, and FriendInfo::Status.
Referenced by WorldSession::HandleContactListOpcode(), WorldSession::HandlePlayerReconnect(), and Player::SendInitialPacketsBeforeAddToMap().
SetFriendNote()
void PlayerSocial::SetFriendNote (ObjectGuid friend_guid, std::string note)
Definition at line 107 of file SocialMgr.cpp.
References CharacterDatabase, Database::escape_string(), ObjectGuid::GetCounter(), m_playerLowGuid, m_playerSocialMap, Database::PExecute(), and utf8truncate().
Referenced by WorldSession::HandleAddFriendOpcodeCallBack(), and WorldSession::HandleSetContactNotesOpcode().
SetPlayerGuid()
void PlayerSocial::SetPlayerGuid (ObjectGuid guid) inline
Definition at line 127 of file SocialMgr.h.
References ObjectGuid::GetCounter(), and m_playerLowGuid.
Referenced by SocialMgr::LoadFromDB().
Friends And Related Function Documentation
SocialMgr
friend class SocialMgr friend
Definition at line 114 of file SocialMgr.h.
Field Documentation
m_playerLowGuid
uint32 PlayerSocial::m_playerLowGuid private
Definition at line 131 of file SocialMgr.h.
Referenced by AddToSocialList(), RemoveFromSocialList(), SendSocialList(), SetFriendNote(), and SetPlayerGuid().
m_playerSocialMap
PlayerSocialMap PlayerSocial::m_playerSocialMap private
Definition at line 130 of file SocialMgr.h.
Referenced by AddToSocialList(), SocialMgr::GetFriendInfo(), GetNumberOfSocialsWithFlag(), HasFriend(), HasIgnore(), SocialMgr::LoadFromDB(), RemoveFromSocialList(), SendSocialList(), SetFriendNote(), and ~PlayerSocial().
The documentation for this class was generated from the following files:
SocialMgr.h
SocialMgr.cpp