CMaNGOS_WoTLK: BattleGroundRL Class Reference
BattleGroundRL Class Reference
#include <BattleGroundRL.h>
Public Member Functions
BattleGroundRL ()
virtual void StartingEventOpenDoors () override
bool HandlePlayerUnderMap (Player *) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void Update (uint32 diff)
Update method.
virtual void Reset ()
Method that is called when no players remains in battleground.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
virtual void EndBattleGround (Team)
Method that ends battleground.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
virtual void UpdatePlayerScore (Player *, uint32, uint32)
Method that updates player score.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual bool HandleAreaTrigger (Player *, uint32)
virtual void HandleKillPlayer (Player *, Player *)
Method that handles killing players.
virtual void HandleKillUnit (Creature *, Player *)
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectCreate (GameObject *)
virtual void HandlePlayerDroppedFlag (Player *)
virtual void HandlePlayerClickedOnFlag (Player *, GameObject *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
virtual void AddPlayer (Player *)
Method that is called when adding a player to the battleground.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual Team GetPrematureWinner ()
Function that returns the premature winner.
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 23 of file BattleGroundRL.h.
Constructor & Destructor Documentation
BattleGroundRL()
BattleGroundRL::BattleGroundRL ()
Definition at line 26 of file BattleGroundRL.cpp.
References BG_START_DELAY_15S, BG_START_DELAY_1M, BG_START_DELAY_30S, BG_START_DELAY_NONE, BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_ARENA_FIFTEEN_SECONDS, LANG_ARENA_HAS_BEGUN, LANG_ARENA_ONE_MINUTE, LANG_ARENA_THIRTY_SECONDS, BattleGround::m_startDelayTimes, and BattleGround::m_startMessageIds.
Member Function Documentation
HandlePlayerUnderMap()
bool BattleGroundRL::HandlePlayerUnderMap (Player * player) override virtual
Reimplemented from BattleGround.
Definition at line 46 of file BattleGroundRL.cpp.
References BattleGround::GetMapId(), WorldObject::GetOrientation(), and Player::TeleportTo().
StartingEventOpenDoors()
void BattleGroundRL::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 41 of file BattleGroundRL.cpp.
References BG_EVENT_DOOR, and BattleGround::OpenDoorEvent().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 25 of file BattleGroundRL.h.
The documentation for this class was generated from the following files:
BattleGroundRL.h
BattleGroundRL.cpp