CMaNGOS_WoTLK: instance_icecrown_citadel Class Reference
instance_icecrown_citadel Class Reference
#include <icecrown_citadel.h>
Public Member Functions
instance_icecrown_citadel (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *pCreature) override
void OnObjectSpawn (GameObject *pGo) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
uint32 GetPlayerTeam () const
const char * Save () const override
void Load (const char *strIn) override
void DoHandleCitadelAreaTrigger (uint32 uiTriggerId, Player *pPlayer)
bool IsHeroicDifficulty () const
bool Is25ManDifficulty () const
void GetDeathwhisperStalkersList (GuidList &lList) const
void GetRotfaceStalkersList (GuidList &lList) const
ObjectGuid GetScientistStalkerGuid (bool bLeft)
void DoPreparePutricideDoor ()
void SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget=nullptr, uint32 uiMiscvalue1=0) const override
bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const override
void Update (const uint32 diff) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void ProcessEventNpcs (Player *pPlayer)
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
std::string m_strInstData
uint32 m_auiEncounter [MAX_ENCOUNTER]
bool m_abAchievCriteria [MAX_SPECIAL_ACHIEV_CRITS]
uint32 m_uiTeam
uint32 m_uiPutricideValveTimer
bool m_bHasMarrowgarIntroYelled
bool m_bHasDeathwhisperIntroYelled
bool m_bHasRimefangLanded
bool m_bHasSpinestalkerLanded
ObjectGuid m_leftScientistStalkerGuid
ObjectGuid m_rightScientistStalkerGuid
GuidList m_lDeathwhisperStalkersGuids
GuidList m_lDeathwhisperCultistsGuids
GuidList m_lRotfaceUpperStalkersGuids
GuidList m_lFactionTeleporterGuids [PVP_TEAM_COUNT]
GuidSet m_sDarkfallenCreaturesLowerGuids
GuidSet m_sDarkfallenCreaturesLeftGuids
GuidSet m_sDarkfallenCreaturesRightGuids
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 325 of file icecrown_citadel.h.
Constructor & Destructor Documentation
instance_icecrown_citadel()
instance_icecrown_citadel::instance_icecrown_citadel (Map * pMap)
Definition at line 120 of file icecrown_citadel.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_icecrown_citadel::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget = nullptr, uint32 uiMiscvalue1 = 0) const override virtual
Reimplemented from InstanceData.
Definition at line 993 of file icecrown_citadel.cpp.
References ACHIEV_CRIT_BONED_10H, ACHIEV_CRIT_BONED_10N, ACHIEV_CRIT_BONED_25H, ACHIEV_CRIT_BONED_25N, ACHIEV_CRIT_DANCES_WITH_OOZES_10H, ACHIEV_CRIT_DANCES_WITH_OOZES_10N, ACHIEV_CRIT_DANCES_WITH_OOZES_25H, ACHIEV_CRIT_DANCES_WITH_OOZES_25N, ACHIEV_CRIT_MADE_A_MESS_10H, ACHIEV_CRIT_MADE_A_MESS_10N, ACHIEV_CRIT_MADE_A_MESS_25H, ACHIEV_CRIT_MADE_A_MESS_25N, ACHIEV_CRIT_NAUSEA_10H, ACHIEV_CRIT_NAUSEA_10N, ACHIEV_CRIT_NAUSEA_25H, ACHIEV_CRIT_NAUSEA_25N, m_abAchievCriteria, TYPE_ACHIEV_BONED, TYPE_ACHIEV_DANCES_OOZES, TYPE_ACHIEV_MADE_A_MESS, and TYPE_ACHIEV_NAUSEA.
CheckConditionCriteriaMeet()
bool instance_icecrown_citadel::CheckConditionCriteriaMeet (Player const * source, uint32 instance_condition_id, WorldObject const * conditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 1022 of file icecrown_citadel.cpp.
References DONE, GetData(), INSTANCE_CONDITION_ID_INNER_SPIRE_TELEPORT, and TYPE_DEATHBRINGER_SAURFANG.
DoHandleCitadelAreaTrigger()
void instance_icecrown_citadel::DoHandleCitadelAreaTrigger (uint32 uiTriggerId, Player * pPlayer)
Definition at line 151 of file icecrown_citadel.cpp.
References AT_DEATHWHISPER_INTRO, AT_MARROWGAR_INTRO, AT_SINDRAGOSA_PLATFORM, DoScriptText(), ScriptedInstance::GetSingleCreatureFromStorage(), m_bHasDeathwhisperIntroYelled, m_bHasMarrowgarIntroYelled, m_bHasRimefangLanded, m_bHasSpinestalkerLanded, NPC_LORD_MARROWGAR, NPC_RIMEFANG, NPC_SINDRAGOSA, NPC_SPINESTALKER, SAY_DEATHWHISPER_SPEECH_1, SAY_MARROWGAR_INTRO, and DialogueHelper::StartNextDialogueText().
DoPreparePutricideDoor()
void instance_icecrown_citadel::DoPreparePutricideDoor () inline
Definition at line 361 of file icecrown_citadel.h.
References m_uiPutricideValveTimer.
ExecuteChatCommand()
void instance_icecrown_citadel::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 1108 of file icecrown_citadel.cpp.
References ChatHandler::ExtractLiteralArg(), GAMEOBJECT_FLAGS, ScriptedInstance::GetSingleGameObjectFromStorage(), Map::GetTransport(), GO_ARTHAS_PLATFORM, GO_ARTHAS_PRECIPICE, GO_DEATHWHISPER_ELEVATOR, GO_FLAG_DAMAGED, GO_FLAG_NODESPAWN, GO_FROSTY_EDGE, GO_FROSTY_WIND, GO_ORGRIMS_HAMMER_A, GO_ORGRIMS_HAMMER_H, GO_SNOW_EDGE, GO_STATE_ACTIVE, GO_STATE_READY, GO_THE_SKYBREAKER_A, GO_THE_SKYBREAKER_H, GO_ZEPPELIN_HORDE, HIGHGUID_MO_TRANSPORT, InstanceData::instance, Transport::LoadTransport(), and sTransportMgr.
GetData()
uint32 instance_icecrown_citadel::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 979 of file icecrown_citadel.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by boss_festergutAI::Aggro(), boss_rotfaceAI::Aggro(), AreaTrigger_at_frozen_throne_tele(), AreaTrigger_at_putricides_trap(), AreaTrigger_at_rampart_skull(), CheckConditionCriteriaMeet(), GossipHello_go_icc_teleporter(), OnCreatureDeath(), boss_professor_putricideAI::Reset(), SetData(), npc_putricides_trapAI::SummonedCreatureJustDied(), boss_festergutAI::UpdateAI(), and npc_putricides_trapAI::UpdateAI().
GetDeathwhisperStalkersList()
void instance_icecrown_citadel::GetDeathwhisperStalkersList (GuidList & lList) const inline
Definition at line 356 of file icecrown_citadel.h.
References m_lDeathwhisperStalkersGuids.
Referenced by boss_lady_deathwhisperAI::Aggro().
GetPlayerTeam()
uint32 instance_icecrown_citadel::GetPlayerTeam () const inline
Definition at line 345 of file icecrown_citadel.h.
References m_uiTeam.
Referenced by AreaTrigger_at_rampart_skull().
GetRotfaceStalkersList()
void instance_icecrown_citadel::GetRotfaceStalkersList (GuidList & lList) const inline
Definition at line 357 of file icecrown_citadel.h.
References m_lRotfaceUpperStalkersGuids.
Referenced by EffectScriptEffectCreature_npc_putricide().
GetScientistStalkerGuid()
ObjectGuid instance_icecrown_citadel::GetScientistStalkerGuid (bool bLeft) inline
Definition at line 358 of file icecrown_citadel.h.
References m_leftScientistStalkerGuid, and m_rightScientistStalkerGuid.
Referenced by boss_professor_putricideAI::ReceiveAIEvent().
Initialize()
void instance_icecrown_citadel::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 131 of file icecrown_citadel.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_abAchievCriteria, and m_auiEncounter.
Referenced by instance_icecrown_citadel().
Is25ManDifficulty()
bool instance_icecrown_citadel::Is25ManDifficulty () const inline
Definition at line 354 of file icecrown_citadel.h.
References Map::GetDifficulty(), InstanceData::instance, RAID_DIFFICULTY_25MAN_HEROIC, and RAID_DIFFICULTY_25MAN_NORMAL.
Referenced by boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_lady_deathwhisperAI::DoSummonCultistWave(), npc_rimefang_iccAI::npc_rimefang_iccAI(), SetData(), and boss_festergutAI::UpdateAI().
IsEncounterInProgress()
bool instance_icecrown_citadel::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 140 of file icecrown_citadel.cpp.
References IN_PROGRESS, and m_auiEncounter.
IsHeroicDifficulty()
bool instance_icecrown_citadel::IsHeroicDifficulty () const inline
Definition at line 353 of file icecrown_citadel.h.
References Map::GetDifficulty(), InstanceData::instance, RAID_DIFFICULTY_10MAN_HEROIC, and RAID_DIFFICULTY_25MAN_HEROIC.
Referenced by boss_blood_queen_lanathelAI::Aggro(), boss_festergutAI::Aggro(), boss_rotfaceAI::Aggro(), boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_lord_marrowgarAI::boss_lord_marrowgarAI(), boss_professor_putricideAI::MovementInform(), boss_blood_queen_lanathelAI::UpdateAI(), boss_festergutAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_rotfaceAI::UpdateAI(), and boss_the_lich_king_iccAI::UpdateAI().
JustDidDialogueStep()
void instance_icecrown_citadel::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 946 of file icecrown_citadel.cpp.
References Map::GetTransport(), GO_ORGRIMS_HAMMER_A, GO_STATE_ACTIVE, GO_THE_SKYBREAKER_H, HIGHGUID_MO_TRANSPORT, IN_PROGRESS, Infinite, InstanceData::instance, Transport::LoadTransport(), SAY_GUNSHIP_START_ALLY_3, SAY_GUNSHIP_START_ALLY_5, SAY_GUNSHIP_START_HORDE_3, SAY_GUNSHIP_START_HORDE_4, SetData(), sTransportMgr, and TYPE_GUNSHIP_BATTLE.
Load()
void instance_icecrown_citadel::Load (const char * strIn) override virtual
Reimplemented from InstanceData.
Definition at line 1033 of file icecrown_citadel.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_icecrown_citadel::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 206 of file icecrown_citadel.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_lDeathwhisperCultistsGuids, m_lDeathwhisperStalkersGuids, m_leftScientistStalkerGuid, m_lRotfaceUpperStalkersGuids, ScriptedInstance::m_npcEntryGuidStore, m_rightScientistStalkerGuid, m_sDarkfallenCreaturesLeftGuids, m_sDarkfallenCreaturesLowerGuids, m_sDarkfallenCreaturesRightGuids, NPC_BLOOD_ORB_CONTROL, NPC_CULT_ADHERENT, NPC_CULT_FANATIC, NPC_DARFALLEN_NOBLE, NPC_DARKFALLEN_ADVISOR, NPC_DARKFALLEN_ARCHMAGE, NPC_DARKFALLEN_BLOOD_KNIGHT, NPC_DEATHBRINGER_SAURFANG, NPC_DEATHWHISPER_SPAWN_STALKER, NPC_FESTERGUT, NPC_GAS_STALKER, NPC_GUNSHIP_MURADIN, NPC_GUNSHIP_SAURFANG, NPC_KELESETH, NPC_LADY_DEATHWHISPER, NPC_LANATHEL_INTRO, NPC_LICH_KING, NPC_LORD_MARROWGAR, NPC_MAD_SCIENTIST_STALKER, NPC_OOZE_TENTACLE_STALKER, NPC_ORGRIMS_HAMMER, NPC_PROFESSOR_PUTRICIDE, NPC_PUDDLE_STALKER, NPC_PUTRICIDES_TRAP, NPC_REANIMATED_ADHERENT, NPC_REANIMATED_FANATIC, NPC_RIMEFANG, NPC_ROTFACE, NPC_SINDRAGOSA, NPC_SKYBREAKER, NPC_SLIMY_TENTACLE_STALKER, NPC_SPINESTALKER, NPC_SPIRE_FROSTWYRM, NPC_TALDARAM, NPC_TIRION_FORDRING, NPC_VALANAR, NPC_VALITHRIA, and NPC_VALITHRIA_COMBAT_TRIGGER.
OnCreatureDeath()
void instance_icecrown_citadel::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 484 of file icecrown_citadel.cpp.
References ALLIANCE, DONE, DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), FAIL, GetClosestGameObjectWithEntry(), GetData(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_EMPOWERING_BLOOD_ORB, GO_FLAG_NO_INTERACT, HORDE, m_lDeathwhisperCultistsGuids, m_sDarkfallenCreaturesLeftGuids, m_sDarkfallenCreaturesLowerGuids, m_sDarkfallenCreaturesRightGuids, m_uiTeam, NPC_CULT_ADHERENT, NPC_CULT_FANATIC, NPC_DARFALLEN_NOBLE, NPC_DARKFALLEN_ADVISOR, NPC_DARKFALLEN_ARCHMAGE, NPC_DARKFALLEN_BLOOD_KNIGHT, NPC_DEFORMED_FANATIC, NPC_EMPOWERED_ADHERENT, NPC_FESTERGUT, NPC_ORGRIMS_HAMMER, NPC_PRECIOUS, NPC_REANIMATED_ADHERENT, NPC_REANIMATED_FANATIC, NPC_ROTFACE, NPC_SKYBREAKER, NPC_SPIRE_FROSTWYRM, NPC_STINKY, SAY_PRECIOUS_DIES, SAY_STINKY_DIES, SetData(), TYPE_BLOOD_WING_ENTRANCE, TYPE_GUNSHIP_BATTLE, and TYPE_SPIRE_FROSTWYRM.
OnCreatureEnterCombat()
void instance_icecrown_citadel::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 471 of file icecrown_citadel.cpp.
References Object::GetEntry(), NPC_DARFALLEN_NOBLE, NPC_DARKFALLEN_ADVISOR, NPC_DARKFALLEN_ARCHMAGE, and NPC_DARKFALLEN_BLOOD_KNIGHT.
OnCreatureRespawn()
void instance_icecrown_citadel::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 278 of file icecrown_citadel.cpp.
References Creature::AI(), Object::GetEntry(), NPC_COLDFLAME, NPC_DEATHWHISPER_SPAWN_STALKER, NPC_FROST_FREEZE_TRAP, NPC_ORGRIMS_HAMMER, NPC_SKYBREAKER, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_icecrown_citadel::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 294 of file icecrown_citadel.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ALLIANCE_TELEPORTER, GO_ARTHAS_PLATFORM, GO_ARTHAS_PRECIPICE, GO_BLOODPRINCE_DOOR, GO_BLOODWING_SIGIL, GO_COUNCIL_DOOR_1, GO_COUNCIL_DOOR_2, GO_CRIMSON_HALL_DOOR, GO_DEATHWHISPER_ELEVATOR, GO_DREAMWALKER_CACHE, GO_DREAMWALKER_CACHE_10_H, GO_DREAMWALKER_CACHE_25, GO_DREAMWALKER_CACHE_25_H, GO_DRINK_ME, GO_FLAG_NO_INTERACT, GO_FROSTWING_SIGIL, GO_FROSTY_EDGE, GO_FROSTY_WIND, GO_GREEN_DRAGON_ENTRANCE, GO_GREEN_DRAGON_EXIT, GO_GREEN_PLAGUE, GO_GREEN_TUBE, GO_GREEN_VALVE, GO_GUNSHIP_ARMORY_A, GO_GUNSHIP_ARMORY_A_10H, GO_GUNSHIP_ARMORY_A_25, GO_GUNSHIP_ARMORY_A_25H, GO_GUNSHIP_ARMORY_H, GO_GUNSHIP_ARMORY_H_10H, GO_GUNSHIP_ARMORY_H_25, GO_GUNSHIP_ARMORY_H_25H, GO_HORDE_TELEPORTER, GO_ICECROWN_GRATE, GO_ICESHARD_1, GO_ICESHARD_2, GO_ICESHARD_3, GO_ICESHARD_4, GO_ICEWALL_1, GO_ICEWALL_2, GO_MARROWGAR_DOOR, GO_ORANGE_PLAGUE, GO_ORANGE_TUBE, GO_ORANGE_VALVE, GO_ORATORY_DOOR, GO_PLAGUE_SIGIL, GO_SAURFANG_CACHE, GO_SAURFANG_CACHE_10_H, GO_SAURFANG_CACHE_25, GO_SAURFANG_CACHE_25_H, GO_SAURFANG_DOOR, GO_SCIENTIST_DOOR, GO_SCIENTIST_DOOR_COLLISION, GO_SCIENTIST_DOOR_GREEN, GO_SCIENTIST_DOOR_ORANGE, GO_SINDRAGOSA_ENTRANCE, GO_SINDRAGOSA_SHORTCUT_ENTRANCE, GO_SINDRAGOSA_SHORTCUT_EXIT, GO_SNOW_EDGE, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, GO_TRANSPORTER_DEATHBRINGER, GO_TRANSPORTER_FROZEN_THRONE, GO_TRANSPORTER_LIGHTS_HAMMER, GO_TRANSPORTER_ORATORY_DAMNED, GO_TRANSPORTER_RAMPART_SKULLS, GO_TRANSPORTER_SINDRAGOSA, GO_TRANSPORTER_UPPER_SPIRE, GO_VALITHRIA_DOOR_1, GO_VALITHRIA_DOOR_2, GO_VALITHRIA_DOOR_3, GO_VALITHRIA_DOOR_4, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_lFactionTeleporterGuids, Object::RemoveFlag(), GameObject::SetGoState(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TYPE_BLOOD_PRINCE_COUNCIL, TYPE_BLOOD_WING_ENTRANCE, TYPE_DEATHBRINGER_SAURFANG, TYPE_FESTERGUT, TYPE_FROST_WING_ENTRANCE, TYPE_GUNSHIP_BATTLE, TYPE_LADY_DEATHWHISPER, TYPE_MARROWGAR, TYPE_PLAGUE_WING_ENTRANCE, TYPE_PROFESSOR_PUTRICIDE, TYPE_QUEEN_LANATHEL, TYPE_ROTFACE, TYPE_SINDRAGOSA, and TYPE_VALITHRIA.
OnObjectSpawn()
void instance_icecrown_citadel::OnObjectSpawn (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 460 of file icecrown_citadel.cpp.
References DONE, Object::GetEntry(), GO_DEATHWHISPER_ELEVATOR, GO_STATE_READY, m_auiEncounter, GameObject::SetGoState(), and TYPE_LADY_DEATHWHISPER.
OnPlayerEnter()
void instance_icecrown_citadel::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 196 of file icecrown_citadel.cpp.
References Player::GetTeam(), m_uiTeam, and ProcessEventNpcs().
ProcessEventNpcs()
void instance_icecrown_citadel::ProcessEventNpcs (Player * pPlayer) private
Definition at line 1080 of file icecrown_citadel.cpp.
References aSaurfangLocations, ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::DoUseDoorOrButton(), GetTeamIndexByTeamId(), HORDE, HOUR, IN_MILLISECONDS, m_lFactionTeleporterGuids, m_uiTeam, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by OnPlayerEnter().
Save()
const char* instance_icecrown_citadel::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 347 of file icecrown_citadel.h.
References m_strInstData.
SetData()
void instance_icecrown_citadel::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 562 of file icecrown_citadel.cpp.
References ALLIANCE, DONE, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), ENCOUNTER_FRAME_DISENGAGE, ENCOUNTER_FRAME_ENGAGE, FAIL, Map::GetCreature(), Map::GetCurrentClockTime(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), Map::GetTransport(), GO_BLOODPRINCE_DOOR, GO_BLOODWING_SIGIL, GO_COUNCIL_DOOR_1, GO_COUNCIL_DOOR_2, GO_CRIMSON_HALL_DOOR, GO_DEATHWHISPER_ELEVATOR, GO_DREAMWALKER_CACHE, GO_DRINK_ME, GO_FLAG_NO_INTERACT, GO_FROSTWING_SIGIL, GO_GREEN_DRAGON_ENTRANCE, GO_GREEN_DRAGON_EXIT, GO_GREEN_PLAGUE, GO_GREEN_VALVE, GO_GUNSHIP_ARMORY_A, GO_GUNSHIP_ARMORY_H, GO_ICECROWN_GRATE, GO_ICEWALL_1, GO_ICEWALL_2, GO_MARROWGAR_DOOR, GO_ORANGE_PLAGUE, GO_ORANGE_VALVE, GO_ORATORY_DOOR, GO_ORGRIMS_HAMMER_A, GO_ORGRIMS_HAMMER_H, GO_PLAGUE_SIGIL, GO_SAURFANG_CACHE, GO_SAURFANG_DOOR, GO_SCIENTIST_DOOR, GO_SCIENTIST_DOOR_COLLISION, GO_SCIENTIST_DOOR_GREEN, GO_SCIENTIST_DOOR_ORANGE, GO_SINDRAGOSA_ENTRANCE, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, GO_THE_SKYBREAKER_A, GO_THE_SKYBREAKER_H, GO_TRANSPORTER_DEATHBRINGER, GO_TRANSPORTER_FROZEN_THRONE, GO_TRANSPORTER_LIGHTS_HAMMER, GO_TRANSPORTER_ORATORY_DAMNED, GO_TRANSPORTER_RAMPART_SKULLS, GO_VALITHRIA_DOOR_1, GO_VALITHRIA_DOOR_2, GO_VALITHRIA_DOOR_3, GO_VALITHRIA_DOOR_4, GO_ZEPPELIN_HORDE, HIGHGUID_MO_TRANSPORT, HORDE, IN_PROGRESS, InstanceData::instance, Is25ManDifficulty(), Transport::LoadTransport(), m_auiEncounter, m_lDeathwhisperCultistsGuids, m_strInstData, m_uiTeam, MINUTE, MUSIC_ID_GUNSHIP, NPC_GUNSHIP_MURADIN, NPC_GUNSHIP_SAURFANG, NPC_KELESETH, NPC_LADY_DEATHWHISPER, NPC_ORGRIMS_HAMMER, NPC_SKYBREAKER, NPC_TALDARAM, NPC_VALANAR, NPC_VALITHRIA, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_GUNSHIP_ALLY_WIN, SAY_GUNSHIP_HORDE_WIN, SAY_GUNSHIP_START_ALLY_1, SAY_GUNSHIP_START_HORDE_1, script_error_log(), InstanceData::SendEncounterFrame(), Map::SetNewDifficultyCooldown(), SetSpecialAchievementCriteria(), SPECIAL, SPELL_AWARD_REPUTATION, SPELL_CHECK_FOR_PLAYERS, SPELL_FULL_HOUSE_ACHIEV_CHECK, SPELL_GUNSHIP_ACHIEVEMENT, SPELL_TELEPORT_PLAYERS_VICTORY, DialogueHelper::StartNextDialogueText(), sTransportMgr, TRIGGERED_OLD_TRIGGERED, TYPE_ACHIEV_BONED, TYPE_ACHIEV_DANCES_OOZES, TYPE_ACHIEV_MADE_A_MESS, TYPE_ACHIEV_NAUSEA, TYPE_BLOOD_PRINCE_COUNCIL, TYPE_BLOOD_WING_ENTRANCE, TYPE_DEATHBRINGER_SAURFANG, TYPE_FESTERGUT, TYPE_FROST_WING_ENTRANCE, TYPE_GUNSHIP_BATTLE, TYPE_LADY_DEATHWHISPER, TYPE_LICH_KING, TYPE_MARROWGAR, TYPE_PLAGUE_WING_ENTRANCE, TYPE_PROFESSOR_PUTRICIDE, TYPE_QUEEN_LANATHEL, TYPE_ROTFACE, TYPE_SINDRAGOSA, TYPE_SPIRE_FROSTWYRM, and TYPE_VALITHRIA.
Referenced by boss_blood_queen_lanathelAI::Aggro(), boss_deathbringer_saurfangAI::Aggro(), boss_festergutAI::Aggro(), boss_lady_deathwhisperAI::Aggro(), boss_lord_marrowgarAI::Aggro(), boss_professor_putricideAI::Aggro(), boss_rotfaceAI::Aggro(), boss_the_lich_king_iccAI::Aggro(), AreaTrigger_at_putricides_trap(), boss_deathbringer_saurfangAI::DamageTaken(), JustDidDialogueStep(), boss_blood_queen_lanathelAI::JustDied(), boss_festergutAI::JustDied(), boss_lady_deathwhisperAI::JustDied(), boss_lord_marrowgarAI::JustDied(), boss_professor_putricideAI::JustDied(), boss_rotfaceAI::JustDied(), boss_sindragosaAI::JustDied(), boss_the_lich_king_iccAI::JustDied(), boss_valithria_dreamwalkerAI::JustDied(), boss_blood_queen_lanathelAI::JustReachedHome(), boss_deathbringer_saurfangAI::JustReachedHome(), boss_festergutAI::JustReachedHome(), boss_lady_deathwhisperAI::JustReachedHome(), boss_lord_marrowgarAI::JustReachedHome(), boss_professor_putricideAI::JustReachedHome(), boss_rotfaceAI::JustReachedHome(), boss_sindragosaAI::JustReachedHome(), boss_the_lich_king_iccAI::JustReachedHome(), boss_valithria_dreamwalkerAI::JustReachedHome(), boss_sindragosaAI::MovementInform(), OnCreatureDeath(), npc_putricides_trapAI::SummonedCreatureJustDied(), and npc_putricides_trapAI::UpdateAI().
SetSpecialAchievementCriteria()
void instance_icecrown_citadel::SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
Definition at line 987 of file icecrown_citadel.cpp.
References m_abAchievCriteria, and MAX_SPECIAL_ACHIEV_CRITS.
Referenced by EffectScriptEffectCreature_spell_eat_ooze(), boss_deathbringer_saurfangAI::ExecuteAction(), mob_big_oozeAI::ReceiveAIEvent(), SetData(), and npc_bone_spikeAI::UpdateAI().
ShowChatCommands()
void instance_icecrown_citadel::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 1103 of file icecrown_citadel.cpp.
References ChatHandler::SendSysMessage().
Update()
void instance_icecrown_citadel::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 1058 of file icecrown_citadel.cpp.
References DialogueHelper::DialogueUpdate(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_SCIENTIST_DOOR_COLLISION, GO_SCIENTIST_DOOR_GREEN, GO_SCIENTIST_DOOR_ORANGE, GO_STATE_ACTIVE_ALTERNATIVE, and m_uiPutricideValveTimer.
Field Documentation
m_abAchievCriteria
bool instance_icecrown_citadel::m_abAchievCriteria[MAX_SPECIAL_ACHIEV_CRITS] private
Definition at line 380 of file icecrown_citadel.h.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetSpecialAchievementCriteria().
m_auiEncounter
uint32 instance_icecrown_citadel::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 379 of file icecrown_citadel.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), OnObjectSpawn(), and SetData().
m_bHasDeathwhisperIntroYelled
bool instance_icecrown_citadel::m_bHasDeathwhisperIntroYelled private
Definition at line 386 of file icecrown_citadel.h.
Referenced by DoHandleCitadelAreaTrigger().
m_bHasMarrowgarIntroYelled
bool instance_icecrown_citadel::m_bHasMarrowgarIntroYelled private
Definition at line 385 of file icecrown_citadel.h.
Referenced by DoHandleCitadelAreaTrigger().
m_bHasRimefangLanded
bool instance_icecrown_citadel::m_bHasRimefangLanded private
Definition at line 387 of file icecrown_citadel.h.
Referenced by DoHandleCitadelAreaTrigger().
m_bHasSpinestalkerLanded
bool instance_icecrown_citadel::m_bHasSpinestalkerLanded private
Definition at line 388 of file icecrown_citadel.h.
Referenced by DoHandleCitadelAreaTrigger().
m_lDeathwhisperCultistsGuids
GuidList instance_icecrown_citadel::m_lDeathwhisperCultistsGuids private
Definition at line 394 of file icecrown_citadel.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and SetData().
m_lDeathwhisperStalkersGuids
GuidList instance_icecrown_citadel::m_lDeathwhisperStalkersGuids private
Definition at line 393 of file icecrown_citadel.h.
Referenced by GetDeathwhisperStalkersList(), and OnCreatureCreate().
m_leftScientistStalkerGuid
ObjectGuid instance_icecrown_citadel::m_leftScientistStalkerGuid private
Definition at line 390 of file icecrown_citadel.h.
Referenced by GetScientistStalkerGuid(), and OnCreatureCreate().
m_lFactionTeleporterGuids
GuidList instance_icecrown_citadel::m_lFactionTeleporterGuids[PVP_TEAM_COUNT] private
Definition at line 396 of file icecrown_citadel.h.
Referenced by OnObjectCreate(), and ProcessEventNpcs().
m_lRotfaceUpperStalkersGuids
GuidList instance_icecrown_citadel::m_lRotfaceUpperStalkersGuids private
Definition at line 395 of file icecrown_citadel.h.
Referenced by GetRotfaceStalkersList(), and OnCreatureCreate().
m_rightScientistStalkerGuid
ObjectGuid instance_icecrown_citadel::m_rightScientistStalkerGuid private
Definition at line 391 of file icecrown_citadel.h.
Referenced by GetScientistStalkerGuid(), and OnCreatureCreate().
m_sDarkfallenCreaturesLeftGuids
GuidSet instance_icecrown_citadel::m_sDarkfallenCreaturesLeftGuids private
Definition at line 398 of file icecrown_citadel.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_sDarkfallenCreaturesLowerGuids
GuidSet instance_icecrown_citadel::m_sDarkfallenCreaturesLowerGuids private
Definition at line 397 of file icecrown_citadel.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_sDarkfallenCreaturesRightGuids
GuidSet instance_icecrown_citadel::m_sDarkfallenCreaturesRightGuids private
Definition at line 399 of file icecrown_citadel.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_strInstData
std::string instance_icecrown_citadel::m_strInstData private
Definition at line 378 of file icecrown_citadel.h.
Referenced by Save(), and SetData().
m_uiPutricideValveTimer
uint32 instance_icecrown_citadel::m_uiPutricideValveTimer private
Definition at line 383 of file icecrown_citadel.h.
Referenced by DoPreparePutricideDoor(), and Update().
m_uiTeam
uint32 instance_icecrown_citadel::m_uiTeam private
Definition at line 382 of file icecrown_citadel.h.
Referenced by GetPlayerTeam(), OnCreatureDeath(), OnPlayerEnter(), ProcessEventNpcs(), and SetData().
The documentation for this class was generated from the following files:
icecrown_citadel.h
icecrown_citadel.cpp