CMaNGOS_WoTLK: instance_underbog Class Reference
instance_underbog Class Reference
#include <underbog.h>
Public Member Functions
instance_underbog (Map *map)
void Initialize ()
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void OnCreatureCreate (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectCreate (GameObject *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
bool m_bGhazanSurfaced
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 23 of file underbog.h.
Constructor & Destructor Documentation
instance_underbog()
instance_underbog::instance_underbog (Map * map)
Definition at line 27 of file underbog.cpp.
References Initialize().
Member Function Documentation
GetData()
uint32 instance_underbog::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 43 of file underbog.cpp.
References DATA_GHAZAN_SURFACE, and m_bGhazanSurfaced.
Initialize()
void instance_underbog::Initialize () virtual
Reimplemented from InstanceData.
Definition at line 32 of file underbog.cpp.
Referenced by instance_underbog().
OnCreatureCreate()
void instance_underbog::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 51 of file underbog.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_BLACK_STALKER, NPC_CLAW, NPC_GHAZAN, NPC_SWAMPLORD_MUSELEK, and NPC_UNDERBOG_FRENZY.
OnCreatureDeath()
void instance_underbog::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 67 of file underbog.cpp.
References Unit::CastSpell(), Map::GetCreature(), Object::GetEntry(), InstanceData::instance, ScriptedInstance::m_npcEntryGuidCollection, NPC_GHAZAN, NPC_UNDERBOG_FRENZY, Object::SetFlag(), SPELL_PERMANENT_FEIGH_DEATH, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, and UNIT_FLAG_UNINTERACTIBLE.
SetData()
void instance_underbog::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 37 of file underbog.cpp.
References DATA_GHAZAN_SURFACE, and m_bGhazanSurfaced.
Field Documentation
m_bGhazanSurfaced
bool instance_underbog::m_bGhazanSurfaced private
Definition at line 36 of file underbog.h.
Referenced by GetData(), and SetData().
The documentation for this class was generated from the following files:
underbog.h
underbog.cpp