CMaNGOS_WoTLK: ThreatManager Class Reference
ThreatManager Class Reference
#include <ThreatManager.h>
Public Member Functions
ThreatManager (Unit *owner)
~ThreatManager ()
void clearReferences ()
void addThreat (Unit *victim, float threat, bool crit, SpellSchoolMask schoolMask, SpellEntry const *threatSpell, bool assist)
void addThreat (Unit *victim, float threat)
void addThreatDirectly (Unit *victim, float threat)
void modifyThreatPercent (Unit *victim, int32 threatPercent)
void modifyAllThreatPercent (int32 threatPercent)
float getThreat (Unit *victim, bool alsoSearchOfflineList=false)
float GetHighestThreat ()
bool HasThreat (Unit *victim, bool alsoSearchOfflineList=false)
bool isThreatListEmpty () const
void processThreatEvent (ThreatRefStatusChangeEvent &threatRefStatusChangeEvent)
void UpdateForClient (uint32 diff)
HostileReference * getCurrentVictim () const
Unit * getOwner () const
Unit * getHostileTarget ()
void TauntUpdate ()
void FixateTarget (Unit *victim)
void setCurrentVictim (HostileReference *hostileReference)
void setCurrentVictimByTarget (Unit *target)
void setDirty (bool dirty)
ThreatList const & getThreatList () const
void DeleteOutOfRangeReferences ()
void SetTargetSuppressed (Unit *target)
void ClearSuppressed (HostileReference *except)
Private Member Functions
void UpdateContainers ()
Private Attributes
HostileReference * iCurrentVictim
Unit * iOwner
ShortTimeTracker iUpdateTimer
bool iUpdateNeed
ThreatContainer iThreatContainer
ThreatContainer iThreatOfflineContainer
Friends
class HostileReference
Detailed Description
Definition at line 192 of file ThreatManager.h.
Constructor & Destructor Documentation
ThreatManager()
ThreatManager::ThreatManager (Unit * owner) explicit
Definition at line 451 of file ThreatManager.cpp.
~ThreatManager()
ThreatManager::~ThreatManager () inline
Definition at line 199 of file ThreatManager.h.
References clearReferences().
Member Function Documentation
addThreat() [1/2]
void ThreatManager::addThreat (Unit * victim, float threat) inline
Definition at line 204 of file ThreatManager.h.
References addThreat(), and SPELL_SCHOOL_MASK_NONE.
Referenced by addThreat().
addThreat() [2/2]
void ThreatManager::addThreat (Unit * victim, float threat, bool crit, SpellSchoolMask schoolMask, SpellEntry const * threatSpell, bool assist)
Definition at line 469 of file ThreatManager.cpp.
References addThreatDirectly(), ThreatCalcHelper::CalcThreat(), Unit::getHostileRefManager(), WorldObject::GetMap(), getOwner(), HostileRefManager::GetThreatRedirectionData(), Object::GetTypeId(), Map::GetUnit(), iOwner, Unit::IsAlive(), Player::IsGameMaster(), and TYPEID_PLAYER.
Referenced by Unit::AddThreat(), addThreatDirectly(), AQWhirlwind::OnEffectExecute(), CreatureEventAI::ProcessAction(), and HostileRefManager::threatAssist().
addThreatDirectly()
void ThreatManager::addThreatDirectly (Unit * victim, float threat)
Definition at line 518 of file ThreatManager.cpp.
References ThreatContainer::addReference(), HostileReference::addThreat(), ThreatContainer::addThreat(), addThreat(), Unit::CanJoinInAttacking(), Unit::GetMaster(), getOwner(), HostileReference, Unit::IsAlive(), Player::IsGameMaster(), Unit::IsOfflineTarget(), Object::IsPlayer(), Unit::IsPropagatingThreatToOwner(), iThreatContainer, iThreatOfflineContainer, iUpdateNeed, HostileReference::setOnlineOfflineState(), and Unit::TriggerAggroLinkingEvent().
Referenced by addThreat(), and Spell::EffectTaunt().
clearReferences()
void ThreatManager::clearReferences ()
Definition at line 458 of file ThreatManager.cpp.
References ThreatContainer::clearReferences(), iCurrentVictim, iThreatContainer, iThreatOfflineContainer, iUpdateNeed, iUpdateTimer, ShortTimeTracker::Reset(), and THREAT_UPDATE_INTERVAL.
Referenced by Unit::DeleteThreatList(), Unit::Uncharm(), and ~ThreatManager().
ClearSuppressed()
void ThreatManager::ClearSuppressed (HostileReference * except)
Definition at line 745 of file ThreatManager.cpp.
References getOwner(), ThreatContainer::getThreatList(), iThreatContainer, STATE_NORMAL, and STATE_SUPPRESSED.
Referenced by processThreatEvent().
DeleteOutOfRangeReferences()
void ThreatManager::DeleteOutOfRangeReferences ()
Definition at line 752 of file ThreatManager.cpp.
References DIST_CALC_COMBAT_REACH, getOwner(), ThreatContainer::getThreatList(), iThreatContainer, and iThreatOfflineContainer.
Referenced by CombatManager::Update().
FixateTarget()
void ThreatManager::FixateTarget (Unit * victim)
Definition at line 634 of file ThreatManager.cpp.
References ThreatContainer::getReferenceByTarget(), HostileReference::GetTauntState(), ThreatContainer::getThreatList(), iThreatContainer, HostileReference::SetTauntState(), STATE_FIXATED, STATE_NONE, and TauntUpdate().
Referenced by Unit::FixateTarget().
getCurrentVictim()
HostileReference* ThreatManager::getCurrentVictim () const inline
Definition at line 223 of file ThreatManager.h.
References iCurrentVictim.
Referenced by getHostileTarget(), MagneticPullThaddius::OnHit(), and processThreatEvent().
GetHighestThreat()
float ThreatManager::GetHighestThreat ()
Definition at line 589 of file ThreatManager.cpp.
References ThreatContainer::getThreatList(), iThreatContainer, and iThreatOfflineContainer.
Referenced by Spell::EffectTaunt().
getHostileTarget()
Unit * ThreatManager::getHostileTarget ()
Definition at line 565 of file ThreatManager.cpp.
References getCurrentVictim(), getOwner(), Reference< TO, FROM >::getTarget(), iThreatContainer, ThreatContainer::selectNextVictim(), setCurrentVictim(), and UpdateContainers().
Referenced by boss_vx001AI::SelectCustomHostileTarget(), Unit::SelectHostileTarget(), and boss_devourer_of_soulsAI::UpdateAI().
getOwner()
Unit* ThreatManager::getOwner () const inline
Definition at line 225 of file ThreatManager.h.
References iOwner.
Referenced by addThreat(), addThreatDirectly(), ClearSuppressed(), DeleteOutOfRangeReferences(), HostileRefManager::deleteReference(), HostileRefManager::deleteReferencesForFaction(), getHostileTarget(), HostileReference::getSourceUnit(), HostileRefManager::HandleSuppressed(), HostileRefManager::setOnlineOfflineState(), HostileRefManager::threatAssist(), PlayerbotAI::UpdateAttackersForTarget(), and UpdateContainers().
getThreat()
float ThreatManager::getThreat (Unit * victim, bool alsoSearchOfflineList = false)
Definition at line 575 of file ThreatManager.cpp.
References ThreatContainer::getReferenceByTarget(), HostileReference::getThreat(), iThreatContainer, and iThreatOfflineContainer.
Referenced by Spell::EffectDummy(), Spell::EffectTaunt(), ChatHandler::HandleNpcThreatCommand(), HurtfulStrikePrimer::OnEffectExecute(), processThreatEvent(), boss_mandokirAI::ReceiveAIEvent(), boss_kiggler_the_crazedAI::SpellHitTarget(), Aura::TriggerSpell(), and PlayerbotAI::UpdateAttackersForTarget().
getThreatList()
ThreatList const& ThreatManager::getThreatList () const inline
Definition at line 238 of file ThreatManager.h.
References ThreatContainer::getThreatList(), and iThreatContainer.
Referenced by UnitAI::AttackSpecificEnemy(), boss_baroness_anastariAI::boss_baroness_anastariAI(), UnitAI::ChooseTarget(), boss_hodirAI::DamageTaken(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_flame_of_azzinothAI::DoPickChargeTarget(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), priestess_commonAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_black_stalkerAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), boss_kaelthasAI::ExecuteActions(), Creature::FillGuidsListFromThreatList(), UnitConditionMgr::getConditionValue(), boss_thorimAI::GetRandomArenaPlayer(), boss_sacrolashAI::GetRandomTargetAtDist(), ChatHandler::HandleNpcThreatCommand(), SpectralBlast::OnCheckTarget(), HatefulStrikePrimer::OnCheckTarget(), Spell::OnCheckTarget(), FaceHighestThreat::OnEffectExecute(), spell_explosive_barrage_aura::OnPeriodicTrigger(), CreatureEventAI::ProcessAction(), CharmInfo::ProcessUnattackableTargets(), Unit::RemoveUnattackableTargets(), Unit::SelectAttackingTarget(), Unit::SelectAttackingTargets(), npc_mimiron_flamesAI::SelectClosestSpreadTarget(), boss_razorscaleAI::SelectCustomHostileTarget(), Unit::SendHighestThreatUpdate(), Unit::SendThreatUpdate(), Unit::TakeCharmOf(), Aura::TriggerSpell(), npc_klinfranAI::UpdateAI(), npc_solenorAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), npc_artoriusAI::UpdateAI(), boss_malygosAI::UpdateAI(), npc_the_cleanerAI::UpdateAI(), and PlayerbotAI::UpdateAttackerInfo().
HasThreat()
bool ThreatManager::HasThreat (Unit * victim, bool alsoSearchOfflineList = false)
Definition at line 601 of file ThreatManager.cpp.
References ThreatContainer::getReferenceByTarget(), iThreatContainer, and iThreatOfflineContainer.
Referenced by Player::BeforeVisibilityDestroy(), IsEligibleForLoot(), and InheritMastersThreatList::OnEffectExecute().
isThreatListEmpty()
bool ThreatManager::isThreatListEmpty () const inline
Definition at line 217 of file ThreatManager.h.
References ThreatContainer::empty(), and iThreatContainer.
Referenced by UnitAI::DoResetThreat(), Spell::EffectSummonType(), AQWhirlwind::OnEffectExecute(), boss_vx001AI::SelectCustomHostileTarget(), Unit::SelectHostileTarget(), boss_devourer_of_soulsAI::UpdateAI(), and UpdateForClient().
modifyAllThreatPercent()
void ThreatManager::modifyAllThreatPercent (int32 threatPercent)
Definition at line 552 of file ThreatManager.cpp.
References iThreatContainer, iUpdateNeed, and ThreatContainer::modifyAllThreatPercent().
Referenced by UnitAI::DoResetThreat(), BlinkArcaneAnomaly::OnEffectExecute(), AQWhirlwind::OnEffectExecute(), and CreatureEventAI::ProcessAction().
modifyThreatPercent()
void ThreatManager::modifyThreatPercent (Unit * victim, int32 threatPercent)
Definition at line 546 of file ThreatManager.cpp.
References iThreatContainer, iUpdateNeed, and ThreatContainer::modifyThreatPercent().
Referenced by Spell::EffectDummy(), Spell::EffectModifyThreatPercent(), Spell::EffectScriptEffect(), mob_bt_battle_fighterAI::ExecuteShadowlordActions(), Unit::HandleProcTriggerSpellAuraProc(), HateToHalf::OnEffectExecute(), HateToZero::OnEffectExecute(), SpectralBlast::OnEffectExecute(), CreatureEventAI::ProcessAction(), npc_bonechewer_brawler::ReceiveAIEvent(), Unit::SelectHostileTarget(), boss_kiggler_the_crazedAI::SpellHitTarget(), boss_ouroAI::SpellHitTarget(), boss_ebonrocAI::SpellHitTarget(), boss_firemawAI::SpellHitTarget(), boss_flamegorAI::SpellHitTarget(), boss_ragnarosAI::SpellHitTarget(), boss_gurtogg_bloodboilAI::SwitchPhase(), Aura::TriggerSpell(), npc_bonechewer_combatant::UpdateAI(), and boss_nethermancer_sepethreaAI::UpdateAI().
processThreatEvent()
void ThreatManager::processThreatEvent (ThreatRefStatusChangeEvent & threatRefStatusChangeEvent)
Definition at line 672 of file ThreatManager.cpp.
References ThreatContainer::addReference(), ClearSuppressed(), getCurrentVictim(), ThreatRefStatusChangeEvent::getFValue(), ThreatRefStatusChangeEvent::getReference(), HostileReference::getThreat(), getThreat(), UnitBaseEvent::getType(), iOwner, HostileReference::isOnline(), iThreatContainer, iThreatOfflineContainer, iUpdateNeed, ThreatContainer::remove(), Unit::SendThreatRemove(), setCurrentVictim(), setDirty(), ThreatRefStatusChangeEvent::setThreatManager(), UEV_THREAT_REF_ONLINE_STATUS, UEV_THREAT_REF_REMOVE_FROM_LIST, UEV_THREAT_REF_SUPPRESSED_STATUS, and UEV_THREAT_REF_THREAT_CHANGE.
Referenced by HostileReference::fireStatusChanged().
setCurrentVictim()
void ThreatManager::setCurrentVictim (HostileReference * hostileReference)
Definition at line 647 of file ThreatManager.cpp.
References iCurrentVictim, iOwner, iUpdateNeed, and Unit::SendHighestThreatUpdate().
Referenced by getHostileTarget(), processThreatEvent(), and setCurrentVictimByTarget().
setCurrentVictimByTarget()
void ThreatManager::setCurrentVictimByTarget (Unit * target)
Definition at line 660 of file ThreatManager.cpp.
References ThreatContainer::getReferenceByTarget(), Reference< TO, FROM >::getTarget(), iCurrentVictim, iThreatContainer, and setCurrentVictim().
Referenced by Unit::Attack(), and Spell::EffectTaunt().
setDirty()
void ThreatManager::setDirty (bool dirty) inline
Definition at line 235 of file ThreatManager.h.
References iThreatContainer, and ThreatContainer::setDirty().
Referenced by processThreatEvent(), and TauntUpdate().
SetTargetSuppressed()
void ThreatManager::SetTargetSuppressed (Unit * target)
Definition at line 768 of file ThreatManager.cpp.
References ThreatContainer::getReferenceByTarget(), iThreatContainer, and STATE_SUPPRESSED.
Referenced by Unit::EvadeTimerExpired().
TauntUpdate()
void ThreatManager::TauntUpdate ()
Definition at line 611 of file ThreatManager.cpp.
References Unit::GetAurasByType(), ThreatContainer::getThreatList(), iOwner, iThreatContainer, setDirty(), SPELL_AURA_DETAUNT, SPELL_AURA_MOD_TAUNT, STATE_DETAUNTED, STATE_FIXATED, STATE_NONE, and STATE_TAUNTED.
Referenced by FixateTarget(), and Unit::TauntUpdate().
UpdateContainers()
void ThreatManager::UpdateContainers () private
Definition at line 560 of file ThreatManager.cpp.
References getOwner(), iThreatContainer, and ThreatContainer::update().
Referenced by getHostileTarget().
UpdateForClient()
void ThreatManager::UpdateForClient (uint32 diff)
Definition at line 730 of file ThreatManager.cpp.
References iOwner, isThreatListEmpty(), iUpdateNeed, iUpdateTimer, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), Unit::SendThreatUpdate(), THREAT_UPDATE_INTERVAL, and ShortTimeTracker::Update().
Referenced by Unit::Update().
Friends And Related Function Documentation
HostileReference
friend class HostileReference friend
Definition at line 195 of file ThreatManager.h.
Referenced by addThreatDirectly().
Field Documentation
iCurrentVictim
HostileReference* ThreatManager::iCurrentVictim private
Definition at line 248 of file ThreatManager.h.
Referenced by clearReferences(), getCurrentVictim(), setCurrentVictim(), and setCurrentVictimByTarget().
iOwner
Unit* ThreatManager::iOwner private
Definition at line 249 of file ThreatManager.h.
Referenced by addThreat(), getOwner(), processThreatEvent(), setCurrentVictim(), TauntUpdate(), and UpdateForClient().
iThreatContainer
ThreatContainer ThreatManager::iThreatContainer private
Definition at line 252 of file ThreatManager.h.
Referenced by addThreatDirectly(), clearReferences(), ClearSuppressed(), DeleteOutOfRangeReferences(), FixateTarget(), GetHighestThreat(), getHostileTarget(), getThreat(), getThreatList(), HasThreat(), isThreatListEmpty(), modifyAllThreatPercent(), modifyThreatPercent(), processThreatEvent(), setCurrentVictimByTarget(), setDirty(), SetTargetSuppressed(), TauntUpdate(), and UpdateContainers().
iThreatOfflineContainer
ThreatContainer ThreatManager::iThreatOfflineContainer private
Definition at line 253 of file ThreatManager.h.
Referenced by addThreatDirectly(), clearReferences(), DeleteOutOfRangeReferences(), GetHighestThreat(), getThreat(), HasThreat(), and processThreatEvent().
iUpdateNeed
bool ThreatManager::iUpdateNeed private
Definition at line 251 of file ThreatManager.h.
Referenced by addThreatDirectly(), clearReferences(), modifyAllThreatPercent(), modifyThreatPercent(), processThreatEvent(), setCurrentVictim(), and UpdateForClient().
iUpdateTimer
ShortTimeTracker ThreatManager::iUpdateTimer private
Definition at line 250 of file ThreatManager.h.
Referenced by clearReferences(), and UpdateForClient().
The documentation for this class was generated from the following files:
ThreatManager.h
ThreatManager.cpp