CMaNGOS_WoTLK: BattlefieldWG Class Reference
BattlefieldWG Class Reference
#include <BattlefieldWG.h>
Public Member Functions
BattlefieldWG ()
void Reset ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
Function that adds a player to the players of the affected battlefield zones.
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected battlefield zones.
void HandlePlayerEnterArea (Player *player, uint32 areaId, bool isMainZone) override
void HandlePlayerLeaveArea (Player *player, uint32 areaId, bool isMainZone) override
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleCreatureCreate (Creature *creature) override
void HandleCreatureDeath (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
bool HandleGameObjectUse (Player *player, GameObject *go) override
void HandlePlayerKillInsideArea (Player *player, Unit *victim) override
void Update (uint32 diff) override
Battlefield update function.
void SendBattlefieldTimerUpdate () override
void StartBattle (Team defender) override
Function that starts battlefield battle.
void EndBattle (Team winner) override
Function that ends battlefield battle.
void RewardPlayersOnBattleEnd (Team winner) override
void OnBattlefieldPlayersUpdate () override
void UpdatePlayerBattleResponse (Player *player) override
void UpdatePlayerExitRequest (Player *player) override
void UpdatePlayerGroupDisband (Player *player) override
bool IsConditionFulfilled (Player const *source, uint32 conditionId, WorldObject const *conditionSource, uint32 conditionSourceType) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target, uint32 miscvalue1) override
Public Member Functions inherited from Battlefield
Battlefield ()
void HandleQueueInviteResponse (Player *, bool)
Function that handles player invite response.
void HandleWarInviteResponse (Player *, bool)
Function that handles player teleport response.
void HandleExitRequest (Player *)
Function that handles player queue exit request.
void HandlePlayerAFK (Player *)
Function that handles the AFK status.
void HandlePlayerLoggedIn (Player *)
Function that handles the player which just logged in.
Team GetDefender () const
Team GetAttacker () const
void RemovePlayerFromRaid (ObjectGuid playerGuid)
Function that removes a player from a raid group.
void HandleBattlefieldGroupDisband (Player *player)
Function that handles the disband of the group.
bool HasPlayer (ObjectGuid playerGuid)
Function that checks if the battlefield has the player.
bool CanDeleteBattlefieldGroup (Group *group)
Function that checks if a battlefield group can be deleted.
BattlefieldStatus GetBattlefieldStatus () const
void SetTimer (uint32 value)
uint32 GetTimer () const
uint32 GetBattleDuration () const
uint32 GetStartInviteDelay () const
uint32 GetCooldownDuration () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetBattlefieldId () const
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleGameObjectRemove (GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
Private Member Functions
void InitPlayerBattlefieldData (Player *player) override
Function that initializes the player data.
void KickBattlefieldPlayer (Player *player) override
void SetupPlayerPosition (Player *player) override
bool HandleCapturePointEvent (uint32 eventId, GameObject *go)
bool HandleDestructibleBuildingEvent (uint32 eventId, GameObject *go, Unit *invoker)
void LockWorkshops (bool lock, const WorldObject *objRef, WintergraspFactory *workshop)
void GetBattlefieldReady (const WorldObject *objRef)
void CleanupBattlefield (const WorldObject *objRef, Team winner)
void SendUpdateGeneralWorldStates ()
void SendWintergraspWarning (int32 messageId, const WorldObject *objRef, uint32 soundId=0)
Player * GetPlayerInZone ()
void UpdatePlayerScore (Player *player)
void UpdateTenacities (const WorldObject *objRef)
WintergraspRank GetPlayerRank (Player *player)
void SendPromotionWhisper (Player *player, int32 textEntry)
Private Attributes
bool m_sentPrebattleWarning
uint32 m_destroyedTowers [PVP_TEAM_COUNT]
uint32 m_workshopCount [PVP_TEAM_COUNT]
ObjectGuid m_relicGuid [PVP_TEAM_COUNT]
ObjectGuid m_zoneLeaderGuid [PVP_TEAM_COUNT]
ObjectGuid m_fortressDoorGuid
ObjectGuid m_fortressDoorWallGuid
std::vector< BattlefieldBuilding * > m_keepBuildings
std::vector< BattlefieldBuilding * > m_defenseTowers
std::vector< BattlefieldBuilding * > m_offenseTowers
std::vector< WintergraspFactory * > m_defenseWorkshops
std::vector< WintergraspFactory * > m_capturableWorkshops
GuidList m_defenseCannonsGuids
GuidList m_attackCannonsGuids
GuidList m_stalkersGuids
GuidList m_detectionUnitsGuids
GuidList m_trashMobsGuids
GuidList m_vendorGuids [PVP_TEAM_COUNT]
GuidList m_activeVehiclesGuids [PVP_TEAM_COUNT]
GuidList m_towerBannersGuids [PVP_TEAM_COUNT]
Additional Inherited Members
Protected Member Functions inherited from Battlefield
void InvitePlayerToQueue (Player *)
Function that handles player invite to queue.
void InitPlayersBeforeBattle ()
Function that initializes all players before the battle starts.
void UpdateBattlefieldPlayers ()
Function that refresh all battlefield players.
void SendZoneWarning (WorldObject *, int32, uint32 soundId=0)
Function that sends a zone wide warning to all players.
void QuestCreditTeam (uint32, Team, WorldObject *)
Function that rewards the given team players.
bool CanAddPlayerToRaid (Player *)
Function that checks if the player can be added to a raid group.
bool IsTeamFull (PvpTeamIndex)
Function that checks if a team is already full.
Group * GetFreeRaid (PvpTeamIndex)
Function that returns a non full group for a specified team index.
Group * GetGroupFor (ObjectGuid)
Function that returns the group of a specified player.
uint32 GetPlayerCountByTeam (PvpTeamIndex)
Function that returns the number of players depending on the team.
Protected Member Functions inherited from OutdoorPvP
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from Battlefield
BattlefieldPlayerDataMap m_activePlayers
std::set< Group * > m_battlefieldRaids [PVP_TEAM_COUNT]
std::set< ObjectGuid > m_queuedPlayers [PVP_TEAM_COUNT]
std::map< ObjectGuid, time_t > m_invitedPlayers [PVP_TEAM_COUNT]
uint32 m_battleFieldId
uint32 m_zoneId
uint32 m_queueUpdateTimer
uint32 m_playersUpdateTimer
BattlefieldStatus m_status
Team m_zoneOwner
uint32 m_timer
uint32 m_battleDuration
uint32 m_startInviteDelay
uint32 m_cooldownDuration
uint32 m_maxPlayersPerTeam
time_t m_startTime
bool m_playersInvited
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 670 of file BattlefieldWG.h.
Constructor & Destructor Documentation
BattlefieldWG()
BattlefieldWG::BattlefieldWG ()
Definition at line 28 of file BattlefieldWG.cpp.
References BATTLEFIELD_WG, Battlefield::m_battleFieldId, Battlefield::m_zoneId, Battlefield::m_zoneOwner, Reset(), TEAM_NONE, and ZONE_ID_WINTERGRASP.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool BattlefieldWG::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from OutdoorPvP.
Definition at line 1460 of file BattlefieldWG.cpp.
References ACHIEV_CRIT_VEH_SLAUGHTER_CANNON, ACHIEV_CRIT_VEH_SLAUGHTER_CATAPULT, ACHIEV_CRIT_VEH_SLAUGHTER_DEMOLISHER, ACHIEV_CRIT_VEH_SLAUGHTER_SIEGE_A, ACHIEV_CRIT_VEH_SLAUGHTER_SIEGE_H, ACHIEV_CRIT_WG_NO_CHANCE, ACHIEV_CRIT_WG_WITHIN_GRASP, Object::GetEntry(), Battlefield::GetTimer(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), IN_MILLISECONDS, WorldObject::IsBoarded(), Unit::IsMounted(), MINUTE, NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H, and NPC_WINTERGRASP_TOWER_CANNON.
CleanupBattlefield()
void BattlefieldWG::CleanupBattlefield (const WorldObject * objRef, Team winner) private
Definition at line 992 of file BattlefieldWG.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), Map::GetCreature(), Battlefield::GetDefender(), WorldObject::GetMap(), GetTeamIndexByTeamId(), GRAVEYARD_ID_FORTRESS_INDOOR, HORDE, IN_MILLISECONDS, LANG_OPVP_WG_ALLIANCE_CAPTURED, LANG_OPVP_WG_ALLIANCE_DEFENDED, LANG_OPVP_WG_HORDE_CAPTURED, LANG_OPVP_WG_HORDE_DEFENDED, LockWorkshops(), m_activeVehiclesGuids, m_attackCannonsGuids, m_capturableWorkshops, m_defenseCannonsGuids, m_defenseTowers, m_keepBuildings, m_offenseTowers, m_trashMobsGuids, m_vendorGuids, MAX_WG_OFFENSE_TOWERS, MINUTE, PVP_TEAM_COUNT, SendUpdateGeneralWorldStates(), OutdoorPvP::SendUpdateWorldState(), SendWintergraspWarning(), OutdoorPvP::SetGraveYardLinkTeam(), SOUND_ID_WG_ALLIANCE_WINS, SOUND_ID_WG_HORDE_WINS, SPELL_TOWER_CONTROL, wgTeamControlAuras, and ZONE_ID_WINTERGRASP.
Referenced by EndBattle().
EndBattle()
void BattlefieldWG::EndBattle (Team winner) override virtual
Function that ends battlefield battle.
Parameters
winner team
reference object
Reimplemented from Battlefield.
Definition at line 824 of file BattlefieldWG.cpp.
References CleanupBattlefield(), Battlefield::EndBattle(), GetPlayerInZone(), and m_sentPrebattleWarning.
Referenced by GetBattlefieldReady(), HandleGameObjectUse(), and Update().
FillInitialWorldStates()
void BattlefieldWG::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 155 of file BattlefieldWG.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, FillInitialWorldState(), Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), HORDE, m_activeVehiclesGuids, m_capturableWorkshops, m_defenseTowers, m_defenseWorkshops, m_keepBuildings, m_offenseTowers, Battlefield::m_timer, m_workshopCount, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_WG_ALLIANCE_DEFENDER, WORLD_STATE_WG_HORDE_DEFENDER, WORLD_STATE_WG_MAX_VEHICLE_A, WORLD_STATE_WG_MAX_VEHICLE_H, WORLD_STATE_WG_SHOW_BATTLE, WORLD_STATE_WG_SHOW_COOLDOWN, WORLD_STATE_WG_TIME_TO_END, WORLD_STATE_WG_TIME_TO_NEXT_BATTLE, WORLD_STATE_WG_VEHICLE_A, and WORLD_STATE_WG_VEHICLE_H.
GetBattlefieldReady()
void BattlefieldWG::GetBattlefieldReady (const WorldObject * objRef) private
Definition at line 840 of file BattlefieldWG.cpp.
References ALLIANCE, BF_GO_STATE_ALLIANCE_INTACT, BF_GO_STATE_HORDE_INTACT, OutdoorPvP::BuffTeam(), DEBUG_LOG, EndBattle(), GAMEOBJECT_FLAGS, Battlefield::GetAttacker(), Map::GetCreature(), Battlefield::GetDefender(), Map::GetGameObject(), WorldObject::GetMap(), GetTeamIndexByTeamId(), GO_FLAG_NO_INTERACT, GO_WORKSHOP_BROKEN_TEMPLE, GO_WORKSHOP_SUNKEN_RING, GRAVEYARD_ID_FORTRESS_INDOOR, HORDE, LANG_OPVP_WG_BATTLE_BEGIN, LockWorkshops(), m_attackCannonsGuids, Battlefield::m_battleDuration, m_capturableWorkshops, m_defenseCannonsGuids, m_defenseTowers, m_defenseWorkshops, m_destroyedTowers, m_fortressDoorGuid, m_fortressDoorWallGuid, m_keepBuildings, m_offenseTowers, m_relicGuid, m_towerBannersGuids, m_trashMobsGuids, m_workshopCount, PVP_TEAM_COUNT, SendUpdateGeneralWorldStates(), OutdoorPvP::SendUpdateWorldState(), SendWintergraspWarning(), OutdoorPvP::SetGraveYardLinkTeam(), sLog, SPELL_TOWER_CONTROL, TEAM_INVALID, TEAM_NONE, wgTeamControlAuras, wgTeamFactions, and ZONE_ID_WINTERGRASP.
Referenced by HandlePlayerEnterZone(), and StartBattle().
GetPlayerInZone()
Player * BattlefieldWG::GetPlayerInZone () private
Definition at line 1391 of file BattlefieldWG.cpp.
References OutdoorPvP::m_zonePlayers, and sObjectMgr.
Referenced by EndBattle(), OnBattlefieldPlayersUpdate(), StartBattle(), and Update().
GetPlayerRank()
WintergraspRank BattlefieldWG::GetPlayerRank (Player * player) private
Definition at line 1289 of file BattlefieldWG.cpp.
References Object::GetObjectGuid(), Battlefield::m_activePlayers, and WG_RANK_NONE.
HandleCapturePointEvent()
bool BattlefieldWG::HandleCapturePointEvent (uint32 eventId, GameObject * go) private
Definition at line 573 of file BattlefieldWG.cpp.
References DEBUG_LOG, Battlefield::GetAttacker(), Battlefield::GetDefender(), Object::GetEntry(), GetTeamIndexByTeamId(), GO_WORKSHOP_BROKEN_TEMPLE, GO_WORKSHOP_SUNKEN_RING, m_capturableWorkshops, OutdoorPvP::SendUpdateWorldState(), SendWintergraspWarning(), OutdoorPvP::SetBannerVisual(), OutdoorPvP::SetGraveYardLinkTeam(), WintergraspCapturePointEventData::team, wgCapturePointEventData, and ZONE_ID_WINTERGRASP.
Referenced by HandleEvent().
HandleCreatureCreate()
void BattlefieldWG::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 286 of file BattlefieldWG.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, Unit::CastSpell(), Creature::ForcedDespawn(), Battlefield::GetAttacker(), Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetSpawnerGuid(), GetTeamIndexByTeamId(), Creature::IsTemporarySummon(), m_activeVehiclesGuids, m_attackCannonsGuids, m_defenseCannonsGuids, m_detectionUnitsGuids, m_stalkersGuids, m_trashMobsGuids, m_vendorGuids, m_zoneLeaderGuid, NPC_ALLIANCE_BRIGADIER_GENERAL, NPC_ANCHORITE_TESSA, NPC_BOWYER_RANDOLPH, NPC_CHAMPION_ROSSLAI, NPC_CHILLED_EARTH_ELEMENTAL, NPC_COMMANDER_DARDOSH, NPC_COMMANDER_ZANNETH, NPC_GLACIAL_SPIRIT, NPC_HOODOO_MASTER_FUJIN, NPC_HORDE_WARBRINGER, NPC_INVISIBLE_STALKER, NPC_KNIGHT_DAMERON, NPC_LEUTENANT_MURP, NPC_LIVING_LASHER, NPC_MARSHAL_MAGRUDER, NPC_MORGAN_DAY, NPC_PRIMALIST_MULFORT, NPC_RAGING_FLAME, NPC_SENIOR_DEMOLITIONIST_LEGOSO, NPC_SIEGE_MASTER_STOUTHANDLE, NPC_SIEGESMITH_STRONGHOOF, NPC_SORCERESS_KAYLANA, NPC_STONE_GUARD_MUKAR, NPC_TACTICAL_OFFICER_AHBRAMIS, NPC_TACTICAL_OFFICER_KILRATH, NPC_TRAVIS_DAY, NPC_VIERON_BLAZEFEATHER, NPC_WANDERING_SHADOW, NPC_WHISPERING_WIND, NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_DETECTION_UNIT, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H, NPC_WINTERGRASP_TOWER_CANNON, OutdoorPvP::SendUpdateWorldState(), Unit::setFaction(), SPELL_ALLIANCE_FLAG, SPELL_HORDE_FLAG, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_NONE, TRIGGERED_OLD_TRIGGERED, wgTeamFactions, WORLD_STATE_WG_VEHICLE_A, and WORLD_STATE_WG_VEHICLE_H.
HandleCreatureDeath()
void BattlefieldWG::HandleCreatureDeath (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 379 of file BattlefieldWG.cpp.
References ALLIANCE, Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPlayer(), WorldObject::GetSpawnerGuid(), GetTeamIndexByTeamId(), Creature::IsTemporarySummon(), m_activeVehiclesGuids, NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H, OutdoorPvP::SendUpdateWorldState(), WORLD_STATE_WG_VEHICLE_A, and WORLD_STATE_WG_VEHICLE_H.
HandleDestructibleBuildingEvent()
bool BattlefieldWG::HandleDestructibleBuildingEvent (uint32 eventId, GameObject * go, Unit * invoker) private
Definition at line 618 of file BattlefieldWG.cpp.
References AI_EVENT_CUSTOM_EVENTAI_A, AI_EVENT_CUSTOM_EVENTAI_B, AI_EVENT_CUSTOM_EVENTAI_C, ALLIANCE, BF_GO_STATE_ALLIANCE_DAMAGED, BF_GO_STATE_ALLIANCE_DESTROYED, BF_GO_STATE_ALLIANCE_INTACT, BF_GO_STATE_HORDE_DAMAGED, BF_GO_STATE_HORDE_DESTROYED, BF_GO_STATE_HORDE_INTACT, OutdoorPvP::BuffTeam(), Unit::CastSpell(), DEBUG_LOG, EVENT_KEEP_DOOR_DESTROY, GAMEOBJECT_FLAGS, Battlefield::GetAttacker(), Map::GetCreature(), Battlefield::GetDefender(), Object::GetEntry(), Map::GetGameObject(), WorldObject::GetMap(), GetTeamIndexByTeamId(), Battlefield::GetTimer(), GO_FLAG_NO_INTERACT, GO_WG_FORTRESS_DOOR, IN_MILLISECONDS, m_defenseTowers, m_destroyedTowers, m_fortressDoorGuid, m_fortressDoorWallGuid, m_keepBuildings, m_offenseTowers, m_relicGuid, m_zoneLeaderGuid, MAX_WG_OFFENSE_TOWERS, MINUTE, NPC_QUEST_CREDIT_KILL_SOUTHERN_TOWER, Battlefield::QuestCreditTeam(), OutdoorPvP::SendUpdateWorldState(), SendWintergraspWarning(), GameObject::SetFaction(), Battlefield::SetTimer(), SPELL_ACHIEV_LEAN_TOWER_DEFENSE, SPELL_ACHIEV_LEAN_TOWER_OFFENSE, SPELL_TOWER_CONTROL, TRIGGERED_OLD_TRIGGERED, wgFortressData, wgFortressTowersData, wgOffenseData, and wgTeamFactions.
Referenced by HandleEvent().
HandleEvent()
bool BattlefieldWG::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 521 of file BattlefieldWG.cpp.
References BF_STATUS_COOLDOWN, GAMEOBJECT_TYPE_CAPTURE_POINT, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), GameObject::GetGoType(), HandleCapturePointEvent(), HandleDestructibleBuildingEvent(), Object::IsGameObject(), Object::IsUnit(), sLog, and TEAM_NONE.
HandleGameObjectCreate()
void BattlefieldWG::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 403 of file BattlefieldWG.cpp.
References BF_STATUS_COOLDOWN, CAPTURE_ARTKIT_NEUTRAL, GAMEOBJECT_TYPE_CAPTURE_POINT, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, Battlefield::GetAttacker(), Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Object::GetEntry(), GameObject::GetGoType(), Object::GetObjectGuid(), GetTeamIndexByTeamId(), GO_JUST_DEACTIVATED, GO_TITAN_RELIC_ALLIANCE, GO_TITAN_RELIC_HORDE, GO_WG_FORTRESS_COLLISION_DOOR, GO_WG_FORTRESS_COLLISION_WALL, GO_WINTERGRASP_BANNER_DEFENSE_ALLIANCE, GO_WINTERGRASP_BANNER_DEFENSE_HORDE, GO_WINTERGRASP_BANNER_OFFENSE_ALLIANCE, GO_WINTERGRASP_BANNER_OFFENSE_HORDE, OutdoorPvP::HandleGameObjectCreate(), m_capturableWorkshops, m_defenseTowers, m_fortressDoorGuid, m_fortressDoorWallGuid, m_keepBuildings, m_offenseTowers, m_relicGuid, m_towerBannersGuids, GameObject::SetFaction(), GameObject::SetGoArtKit(), GameObject::SetLootState(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_NONE, wgCapturePointArtKits, and wgTeamFactions.
HandleGameObjectUse()
bool BattlefieldWG::HandleGameObjectUse (Player * player, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 550 of file BattlefieldWG.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, EndBattle(), GAMEOBJECT_FLAGS, Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Object::GetEntry(), GO_FLAG_NO_INTERACT, GO_TITAN_RELIC_ALLIANCE, GO_TITAN_RELIC_HORDE, HORDE, Object::SetFlag(), sLog, and TEAM_NONE.
HandlePlayerEnterArea()
void BattlefieldWG::HandlePlayerEnterArea (Player * player, uint32 areaId, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 252 of file BattlefieldWG.cpp.
References AREA_ID_EASTPARK_WORKSHOP, AREA_ID_THE_BROKEN_TEMPLE, AREA_ID_THE_SUNKEN_RING, and AREA_ID_WESTPARK_WORKSHOP.
HandlePlayerEnterZone()
void BattlefieldWG::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Function that adds a player to the players of the affected battlefield zones.
Parameters
player to add
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from Battlefield.
Definition at line 196 of file BattlefieldWG.cpp.
References BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, Unit::CastSpell(), Battlefield::GetAttacker(), GetBattlefieldReady(), Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Player::GetTeam(), GetTeamIndexByTeamId(), Battlefield::HandlePlayerEnterZone(), m_destroyedTowers, OutdoorPvP::m_zonePlayers, MAX_WG_OFFENSE_TOWERS, Unit::RemoveAurasDueToSpell(), SPELL_CORPORAL, SPELL_ESSENCE_WINTERGRASP_ZONE, SPELL_LIEUTENANT, SPELL_RECRUIT, SPELL_TOWER_CONTROL, TEAM_NONE, TRIGGERED_OLD_TRIGGERED, UpdatePlayerScore(), and wgTeamControlAuras.
HandlePlayerKillInsideArea()
void BattlefieldWG::HandlePlayerKillInsideArea (Player * player, Unit * victim) override virtual
Reimplemented from OutdoorPvP.
Definition at line 1116 of file BattlefieldWG.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Object::GetEntry(), Object::GetObjectGuid(), Player::GetTeam(), Object::GetTypeId(), WintergraspPlayer::IncreaseKillCount(), Player::KilledMonsterCredit(), Battlefield::m_activePlayers, NPC_QUEST_CREDIT_KILL_ALLIANCE, NPC_QUEST_CREDIT_KILL_HORDE, NPC_QUEST_CREDIT_KILL_VEHICLE, NPC_VALLIANCE_EXPEDITION_CHAMPION, NPC_VALLIANCE_EXPEDITION_GUARD, NPC_WARSONG_CHAMPION, NPC_WARSONG_GUARD, NPC_WINTERGRASP_CATAPULT, NPC_WINTERGRASP_DEMOLISHER, NPC_WINTERGRASP_SIEGE_ENGINE_A, NPC_WINTERGRASP_SIEGE_ENGINE_H, NPC_WINTERGRASP_TOWER_CANNON, TYPEID_PLAYER, TYPEID_UNIT, and UpdatePlayerScore().
HandlePlayerLeaveArea()
void BattlefieldWG::HandlePlayerLeaveArea (Player * player, uint32 areaId, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 271 of file BattlefieldWG.cpp.
References AREA_ID_EASTPARK_WORKSHOP, AREA_ID_THE_BROKEN_TEMPLE, AREA_ID_THE_SUNKEN_RING, and AREA_ID_WESTPARK_WORKSHOP.
HandlePlayerLeaveZone()
void BattlefieldWG::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected battlefield zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from Battlefield.
Definition at line 234 of file BattlefieldWG.cpp.
References Battlefield::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), SPELL_ALLIANCE_CONTROL_PHASE, SPELL_CORPORAL, SPELL_ESSENCE_WINTERGRASP_ZONE, SPELL_HORDE_CONTROL_PHASE, SPELL_LIEUTENANT, SPELL_RECRUIT, and SPELL_TOWER_CONTROL.
InitPlayerBattlefieldData()
void BattlefieldWG::InitPlayerBattlefieldData (Player * player) override private virtual
Function that initializes the player data.
Parameters
player to load
Reimplemented from Battlefield.
Definition at line 1268 of file BattlefieldWG.cpp.
References BF_STATUS_IN_PROGRESS, Battlefield::GetBattlefieldStatus(), Object::GetObjectGuid(), Battlefield::m_activePlayers, and UpdatePlayerScore().
IsConditionFulfilled()
bool BattlefieldWG::IsConditionFulfilled (Player const * source, uint32 conditionId, WorldObject const * conditionSource, uint32 conditionSourceType) override virtual
Reimplemented from OutdoorPvP.
Definition at line 1432 of file BattlefieldWG.cpp.
References BF_STATUS_IN_PROGRESS, Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), Player::GetTeam(), m_activeVehiclesGuids, m_capturableWorkshops, m_workshopCount, OPVP_COND_WG_ALLOW_TELE_BROKEN_TEMPLE, OPVP_COND_WG_ALLOW_TELE_EASTPARK, OPVP_COND_WG_ALLOW_TELE_SUNKEN_RING, OPVP_COND_WG_ALLOW_TELE_WESTPARK, OPVP_COND_WG_BATTLEFIELD_IN_PROGRESS, OPVP_COND_WG_FORTRESS_ACCESS_ALLOWED, OPVP_COND_WG_MAX_ALLIANCE_VEHICLES, OPVP_COND_WG_MAX_HORDE_VEHICLES, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
KickBattlefieldPlayer()
void BattlefieldWG::KickBattlefieldPlayer (Player * player) override private virtual
Reimplemented from Battlefield.
Definition at line 1282 of file BattlefieldWG.cpp.
References Unit::CastSpell(), SPELL_TELEPORT_DALARAN, and TRIGGERED_OLD_TRIGGERED.
LockWorkshops()
void BattlefieldWG::LockWorkshops (bool lock, const WorldObject * objRef, WintergraspFactory * workshop) private
Definition at line 774 of file BattlefieldWG.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, WintergraspFactory::GetCapturePointEntry(), WintergraspFactory::GetCapturePointGuid(), Map::GetGameObject(), WorldObject::GetMap(), WintergraspFactory::GetOwner(), GetTeamIndexByTeamId(), GO_JUST_DEACTIVATED, OutdoorPvP::SetBannerVisual(), sOutdoorPvPMgr, wgCapturePointAnims, and wgCapturePointArtKits.
Referenced by CleanupBattlefield(), and GetBattlefieldReady().
OnBattlefieldPlayersUpdate()
void BattlefieldWG::OnBattlefieldPlayersUpdate () override virtual
Reimplemented from Battlefield.
Definition at line 1261 of file BattlefieldWG.cpp.
References GetPlayerInZone(), and UpdateTenacities().
Reset()
void BattlefieldWG::Reset () virtual
Reimplemented from Battlefield.
Definition at line 37 of file BattlefieldWG.cpp.
References ALLIANCE, BF_GO_STATE_ALLIANCE_INTACT, BF_GO_STATE_HORDE_INTACT, BF_GO_STATE_NEUTRAL_INTACT, BF_STATUS_COOLDOWN, countof, DEBUG_LOG, Battlefield::GetAttacker(), Battlefield::GetDefender(), GO_WORKSHOP_BROKEN_TEMPLE, GO_WORKSHOP_SUNKEN_RING, m_capturableWorkshops, Battlefield::m_cooldownDuration, m_defenseTowers, m_defenseWorkshops, m_destroyedTowers, m_keepBuildings, m_offenseTowers, Battlefield::m_playersInvited, m_sentPrebattleWarning, Battlefield::m_startTime, Battlefield::m_status, m_workshopCount, PVP_TEAM_COUNT, WintergraspFactory::SetAreaId(), WintergraspFactory::SetCapturePointEntry(), WintergraspFactory::SetConditionId(), BattlefieldBuilding::SetGoState(), WintergraspFactory::SetGraveyardId(), OutdoorPvP::SetGraveYardLinkTeam(), WintergraspFactory::SetOwner(), Battlefield::SetTimer(), BattlefieldBuilding::SetWorldState(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_INVALID, TEAM_NONE, wgCapturePointData, wgFortressData, wgFortressTowersData, wgFortressWorkshopsData, wgOffenseData, and ZONE_ID_WINTERGRASP.
Referenced by BattlefieldWG().
RewardPlayersOnBattleEnd()
void BattlefieldWG::RewardPlayersOnBattleEnd (Team winner) override virtual
Reimplemented from Battlefield.
Definition at line 1234 of file BattlefieldWG.cpp.
References ALLIANCE, Player::AreaExploredOrEventHappens(), Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::m_zonePlayers, QUEST_ID_VICTORY_IN_WINTERGRASP_A, QUEST_ID_VICTORY_IN_WINTERGRASP_H, Unit::RemoveAurasDueToSpell(), sObjectMgr, SPELL_CORPORAL, SPELL_LIEUTENANT, SPELL_RECRUIT, SPELL_WINTERGRASP_DEFEAT, SPELL_WINTERGRASP_VICTORY, and TRIGGERED_OLD_TRIGGERED.
SendBattlefieldTimerUpdate()
void BattlefieldWG::SendBattlefieldTimerUpdate () override virtual
Reimplemented from Battlefield.
Definition at line 1423 of file BattlefieldWG.cpp.
References BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, Battlefield::GetBattlefieldStatus(), Battlefield::m_timer, OutdoorPvP::SendUpdateWorldState(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_WG_SHOW_BATTLE, WORLD_STATE_WG_SHOW_COOLDOWN, WORLD_STATE_WG_TIME_TO_END, and WORLD_STATE_WG_TIME_TO_NEXT_BATTLE.
SendPromotionWhisper()
void BattlefieldWG::SendPromotionWhisper (Player * player, int32 textEntry) private
Definition at line 1226 of file BattlefieldWG.cpp.
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), WorldObject::MonsterWhisper(), and sObjectMgr.
Referenced by UpdatePlayerScore().
SendRemoveWorldStates()
void BattlefieldWG::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 191 of file BattlefieldWG.cpp.
References Player::SendUpdateWorldState(), WORLD_STATE_REMOVE, and WORLD_STATE_WG_SHOW_BATTLE.
SendUpdateGeneralWorldStates()
void BattlefieldWG::SendUpdateGeneralWorldStates () private
Definition at line 1096 of file BattlefieldWG.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), HORDE, m_activeVehiclesGuids, Battlefield::m_timer, m_workshopCount, OutdoorPvP::SendUpdateWorldState(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_WG_ALLIANCE_DEFENDER, WORLD_STATE_WG_HORDE_DEFENDER, WORLD_STATE_WG_MAX_VEHICLE_A, WORLD_STATE_WG_MAX_VEHICLE_H, WORLD_STATE_WG_SHOW_BATTLE, WORLD_STATE_WG_SHOW_COOLDOWN, WORLD_STATE_WG_TIME_TO_END, WORLD_STATE_WG_TIME_TO_NEXT_BATTLE, WORLD_STATE_WG_VEHICLE_A, and WORLD_STATE_WG_VEHICLE_H.
Referenced by CleanupBattlefield(), and GetBattlefieldReady().
SendWintergraspWarning()
void BattlefieldWG::SendWintergraspWarning (int32 messageId, const WorldObject * objRef, uint32 soundId = 0) private
Definition at line 1380 of file BattlefieldWG.cpp.
References Map::GetCreature(), WorldObject::GetMap(), m_stalkersGuids, and Battlefield::SendZoneWarning().
Referenced by CleanupBattlefield(), GetBattlefieldReady(), HandleCapturePointEvent(), HandleDestructibleBuildingEvent(), and Update().
SetupPlayerPosition()
void BattlefieldWG::SetupPlayerPosition (Player * player) override private virtual
Reimplemented from Battlefield.
Definition at line 1276 of file BattlefieldWG.cpp.
References Unit::CastSpell(), Battlefield::GetDefender(), Player::GetTeam(), SPELL_TELEPORT_BRIDGE, SPELL_TELEPORT_DALARAN_TO_WG, and TRIGGERED_OLD_TRIGGERED.
StartBattle()
void BattlefieldWG::StartBattle (Team defender) override virtual
Function that starts battlefield battle.
Parameters
defender team
Reimplemented from Battlefield.
Definition at line 805 of file BattlefieldWG.cpp.
References ALLIANCE, DEBUG_LOG, GetBattlefieldReady(), Battlefield::GetDefender(), GetPlayerInZone(), HORDE, Battlefield::StartBattle(), TEAM_NONE, and urand().
Update()
void BattlefieldWG::Update (uint32 diff) override virtual
Battlefield update function.
Reimplemented from Battlefield.
Definition at line 1406 of file BattlefieldWG.cpp.
References BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, EndBattle(), Battlefield::GetBattlefieldStatus(), Battlefield::GetDefender(), GetPlayerInZone(), IN_MILLISECONDS, LANG_OPVP_WG_ABOUT_TO_BEGIN, m_sentPrebattleWarning, Battlefield::m_timer, MINUTE, SendWintergraspWarning(), and Battlefield::Update().
UpdatePlayerBattleResponse()
void BattlefieldWG::UpdatePlayerBattleResponse (Player * player) override virtual
Reimplemented from Battlefield.
Definition at line 1298 of file BattlefieldWG.cpp.
References UpdatePlayerScore(), and UpdateTenacities().
UpdatePlayerExitRequest()
void BattlefieldWG::UpdatePlayerExitRequest (Player * player) override virtual
Reimplemented from Battlefield.
Definition at line 1304 of file BattlefieldWG.cpp.
References UpdateTenacities().
UpdatePlayerGroupDisband()
void BattlefieldWG::UpdatePlayerGroupDisband (Player * player) override virtual
Reimplemented from Battlefield.
Definition at line 1309 of file BattlefieldWG.cpp.
References UpdateTenacities().
UpdatePlayerScore()
void BattlefieldWG::UpdatePlayerScore (Player * player) private
Definition at line 1170 of file BattlefieldWG.cpp.
References Unit::CastSpell(), WintergraspPlayer::GetKillCount(), Object::GetObjectGuid(), WintergraspPlayer::GetPlayerRank(), Unit::HasAura(), LANG_OPVP_WG_REACHED_RANK_1, LANG_OPVP_WG_REACHED_RANK_2, Battlefield::m_activePlayers, MAX_WG_CORPORAL_KILLS, MAX_WG_LIEUTENANT_KILLS, Unit::RemoveAurasDueToSpell(), SendPromotionWhisper(), WintergraspPlayer::SetPlayerRank(), SPELL_CORPORAL, SPELL_LIEUTENANT, SPELL_RECRUIT, TRIGGERED_OLD_TRIGGERED, WG_RANK_CORPORAL, WG_RANK_LIEUTENANT, and WG_RANK_RECRUIT.
Referenced by HandlePlayerEnterZone(), HandlePlayerKillInsideArea(), InitPlayerBattlefieldData(), and UpdatePlayerBattleResponse().
UpdateTenacities()
void BattlefieldWG::UpdateTenacities (const WorldObject * objRef) private
Definition at line 1315 of file BattlefieldWG.cpp.
References ALLIANCE, Unit::CastSpell(), Map::GetCreature(), WorldObject::GetMap(), Battlefield::GetPlayerCountByTeam(), Player::GetTeam(), HORDE, m_activeVehiclesGuids, OutdoorPvP::m_zonePlayers, PVP_TEAM_COUNT, Unit::RemoveAurasDueToSpell(), sObjectMgr, SPELL_GREAT_HONOR, SPELL_GREATER_HONOR, SPELL_GREATEST_HONOR, SPELL_HONORABLE, SPELL_LOKNARASH, SPELL_LOKREGAR, SPELL_LOKTAR, SPELL_LOKTAR_OGAR, SPELL_TENACITY, SPELL_TENACITY_VEHICLE, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and TRIGGERED_OLD_TRIGGERED.
Referenced by OnBattlefieldPlayersUpdate(), UpdatePlayerBattleResponse(), UpdatePlayerExitRequest(), and UpdatePlayerGroupDisband().
Field Documentation
m_activeVehiclesGuids
GuidList BattlefieldWG::m_activeVehiclesGuids[PVP_TEAM_COUNT] private
Definition at line 797 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), FillInitialWorldStates(), HandleCreatureCreate(), HandleCreatureDeath(), IsConditionFulfilled(), SendUpdateGeneralWorldStates(), and UpdateTenacities().
m_attackCannonsGuids
GuidList BattlefieldWG::m_attackCannonsGuids private
Definition at line 791 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), GetBattlefieldReady(), and HandleCreatureCreate().
m_capturableWorkshops
std::vector<WintergraspFactory*> BattlefieldWG::m_capturableWorkshops private
Definition at line 787 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), FillInitialWorldStates(), GetBattlefieldReady(), HandleCapturePointEvent(), HandleGameObjectCreate(), IsConditionFulfilled(), and Reset().
m_defenseCannonsGuids
GuidList BattlefieldWG::m_defenseCannonsGuids private
Definition at line 790 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), GetBattlefieldReady(), and HandleCreatureCreate().
m_defenseTowers
std::vector<BattlefieldBuilding*> BattlefieldWG::m_defenseTowers private
Definition at line 783 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), FillInitialWorldStates(), GetBattlefieldReady(), HandleDestructibleBuildingEvent(), HandleGameObjectCreate(), and Reset().
m_defenseWorkshops
std::vector<WintergraspFactory*> BattlefieldWG::m_defenseWorkshops private
Definition at line 786 of file BattlefieldWG.h.
Referenced by FillInitialWorldStates(), GetBattlefieldReady(), and Reset().
m_destroyedTowers
uint32 BattlefieldWG::m_destroyedTowers[PVP_TEAM_COUNT] private
Definition at line 771 of file BattlefieldWG.h.
Referenced by GetBattlefieldReady(), HandleDestructibleBuildingEvent(), HandlePlayerEnterZone(), and Reset().
m_detectionUnitsGuids
GuidList BattlefieldWG::m_detectionUnitsGuids private
Definition at line 793 of file BattlefieldWG.h.
Referenced by HandleCreatureCreate().
m_fortressDoorGuid
ObjectGuid BattlefieldWG::m_fortressDoorGuid private
Definition at line 778 of file BattlefieldWG.h.
Referenced by GetBattlefieldReady(), HandleDestructibleBuildingEvent(), and HandleGameObjectCreate().
m_fortressDoorWallGuid
ObjectGuid BattlefieldWG::m_fortressDoorWallGuid private
Definition at line 779 of file BattlefieldWG.h.
Referenced by GetBattlefieldReady(), HandleDestructibleBuildingEvent(), and HandleGameObjectCreate().
m_keepBuildings
std::vector<BattlefieldBuilding*> BattlefieldWG::m_keepBuildings private
Definition at line 782 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), FillInitialWorldStates(), GetBattlefieldReady(), HandleDestructibleBuildingEvent(), HandleGameObjectCreate(), and Reset().
m_offenseTowers
std::vector<BattlefieldBuilding*> BattlefieldWG::m_offenseTowers private
Definition at line 784 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), FillInitialWorldStates(), GetBattlefieldReady(), HandleDestructibleBuildingEvent(), HandleGameObjectCreate(), and Reset().
m_relicGuid
ObjectGuid BattlefieldWG::m_relicGuid[PVP_TEAM_COUNT] private
Definition at line 775 of file BattlefieldWG.h.
Referenced by GetBattlefieldReady(), HandleDestructibleBuildingEvent(), and HandleGameObjectCreate().
m_sentPrebattleWarning
bool BattlefieldWG::m_sentPrebattleWarning private
Definition at line 768 of file BattlefieldWG.h.
Referenced by EndBattle(), Reset(), and Update().
m_stalkersGuids
GuidList BattlefieldWG::m_stalkersGuids private
Definition at line 792 of file BattlefieldWG.h.
Referenced by HandleCreatureCreate(), and SendWintergraspWarning().
m_towerBannersGuids
GuidList BattlefieldWG::m_towerBannersGuids[PVP_TEAM_COUNT] private
Definition at line 798 of file BattlefieldWG.h.
Referenced by GetBattlefieldReady(), and HandleGameObjectCreate().
m_trashMobsGuids
GuidList BattlefieldWG::m_trashMobsGuids private
Definition at line 794 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), GetBattlefieldReady(), and HandleCreatureCreate().
m_vendorGuids
GuidList BattlefieldWG::m_vendorGuids[PVP_TEAM_COUNT] private
Definition at line 796 of file BattlefieldWG.h.
Referenced by CleanupBattlefield(), and HandleCreatureCreate().
m_workshopCount
uint32 BattlefieldWG::m_workshopCount[PVP_TEAM_COUNT] private
Definition at line 772 of file BattlefieldWG.h.
Referenced by FillInitialWorldStates(), GetBattlefieldReady(), IsConditionFulfilled(), Reset(), and SendUpdateGeneralWorldStates().
m_zoneLeaderGuid
ObjectGuid BattlefieldWG::m_zoneLeaderGuid[PVP_TEAM_COUNT] private
Definition at line 776 of file BattlefieldWG.h.
Referenced by HandleCreatureCreate(), and HandleDestructibleBuildingEvent().
The documentation for this class was generated from the following files:
BattlefieldWG.h
BattlefieldWG.cpp