CMaNGOS_WoTLK: metric::measurement Class Reference
metric::measurement Class Reference
#include <Metric.h>
Public Member Functions
measurement (std::string name, std::function< bool()> condition=[] { return true;})
measurement (std::string name, std::string key, boost::any value, std::function< bool()> condition=[] { return true;})
measurement (std::string name, std::string key, boost::any value, std::map< std::string, std::string > tags, std::function< bool()> condition=[] { return true;})
measurement (std::string name, std::map< std::string, std::string > tags, std::function< bool()> condition=[] { return true;})
virtual ~measurement ()
void add_tag (std::string key, std::string value)
void add_field (std::string key, boost::any value)
const boost::any get_field (std::string key)
Protected Member Functions
void set_condition (std::function< bool()> condition)
Private Attributes
std::string m_name
std::map< std::string, std::string > m_tags
std::map< std::string, boost::any > m_fields
std::chrono::system_clock::time_point m_timestamp
std::function< bool()> m_condition
Detailed Description
Definition at line 45 of file Metric.h.
Constructor & Destructor Documentation
measurement() [1/4]
metric::measurement::measurement (std::string name, std::function< bool()> condition = [] { return true; })
Definition at line 26 of file Metric.cpp.
measurement() [2/4]
metric::measurement::measurement (std::string name, std::string key, boost::any value, std::function< bool()> condition = [] { return true; })
Definition at line 31 of file Metric.cpp.
References add_field().
measurement() [3/4]
metric::measurement::measurement (std::string name, std::string key, boost::any value, std::map< std::string, std::string > tags, std::function< bool()> condition = [] { return true; })
Definition at line 37 of file Metric.cpp.
References add_field().
measurement() [4/4]
metric::measurement::measurement (std::string name, std::map< std::string, std::string > tags, std::function< bool()> condition = [] { return true; })
Definition at line 43 of file Metric.cpp.
~measurement()
metric::measurement::~measurement () virtual
Definition at line 48 of file Metric.cpp.
Member Function Documentation
add_field()
void metric::measurement::add_field (std::string key, boost::any value)
Definition at line 59 of file Metric.cpp.
Referenced by measurement(), World::Update(), and metric::duration< precision >::~duration().
add_tag()
void metric::measurement::add_tag (std::string key, std::string value)
Definition at line 54 of file Metric.cpp.
get_field()
const boost::any metric::measurement::get_field (std::string key)
Definition at line 64 of file Metric.cpp.
Referenced by metric::duration< precision >::duration().
set_condition()
void metric::measurement::set_condition (std::function< bool()> condition) protected
Definition at line 72 of file Metric.cpp.
Referenced by metric::duration< precision >::duration().
Field Documentation
m_condition
std::function<bool()> metric::measurement::m_condition private
Definition at line 66 of file Metric.h.
m_fields
std::map<std::string, boost::any> metric::measurement::m_fields private
Definition at line 64 of file Metric.h.
m_name
std::string metric::measurement::m_name private
Definition at line 62 of file Metric.h.
m_tags
std::map<std::string, std::string> metric::measurement::m_tags private
Definition at line 63 of file Metric.h.
m_timestamp
std::chrono::system_clock::time_point metric::measurement::m_timestamp private
Definition at line 65 of file Metric.h.
The documentation for this class was generated from the following files:
Metric.h
Metric.cpp