CMaNGOS_WoTLK: MaNGOS::BattleGroundMessageBuilder Class Reference
MaNGOS::BattleGroundMessageBuilder Class Reference
Public Member Functions
BattleGroundMessageBuilder (ChatMsg msgtype, Language language, int32 textId, Creature const *source, va_list *args=nullptr)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
ChatMsg i_msgtype
Language i_language
int32 i_textId
Creature const * i_source
va_list * i_args
Detailed Description
Definition at line 104 of file BattleGround.cpp.
Constructor & Destructor Documentation
BattleGroundMessageBuilder()
MaNGOS::BattleGroundMessageBuilder::BattleGroundMessageBuilder (ChatMsg msgtype, Language language, int32 textId, Creature const * source, va_list * args = nullptr) inline
Definition at line 107 of file BattleGround.cpp.
Member Function Documentation
operator()()
void MaNGOS::BattleGroundMessageBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 109 of file BattleGround.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, WorldObject::GetName(), Object::GetObjectGuid(), i_args, i_language, i_msgtype, i_source, i_textId, and sObjectMgr.
Field Documentation
i_args
va_list* MaNGOS::BattleGroundMessageBuilder::i_args private
Definition at line 133 of file BattleGround.cpp.
Referenced by operator()().
i_language
Language MaNGOS::BattleGroundMessageBuilder::i_language private
Definition at line 130 of file BattleGround.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::BattleGroundMessageBuilder::i_msgtype private
Definition at line 129 of file BattleGround.cpp.
Referenced by operator()().
i_source
Creature const* MaNGOS::BattleGroundMessageBuilder::i_source private
Definition at line 132 of file BattleGround.cpp.
Referenced by operator()().
i_textId
int32 MaNGOS::BattleGroundMessageBuilder::i_textId private
Definition at line 131 of file BattleGround.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
BattleGround.cpp