CMaNGOS_WoTLK: CombatActions Class Reference
CombatActions Class Reference abstract
#include <TimerAI.h>
Public Member Functions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ExecuteActions ()=0
virtual void ResetAllTimers () override
virtual void GetAIInformation (ChatHandler &reader) override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Private Attributes
std::map< uint32, Timer > m_combatActions
std::vector< bool > m_actionReadyStatus
std::map< uint32, bool > m_timerlessActionSettings
std::map< uint32, uint32 > m_spellAction
Additional Inherited Members
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Detailed Description
Definition at line 116 of file TimerAI.h.
Constructor & Destructor Documentation
CombatActions()
CombatActions::CombatActions (uint32 maxCombatActions) inline
Definition at line 119 of file TimerAI.h.
Member Function Documentation
AddCombatAction() [1/5]
void CombatActions::AddCombatAction (uint32 id, bool disabled)
Definition at line 190 of file TimerAI.cpp.
References m_actionReadyStatus, m_combatActions, and TIMER_COMBAT_COMBAT.
Referenced by boss_ahuneAI::boss_ahuneAI(), boss_akilzonAI::boss_akilzonAI(), boss_alarAI::boss_alarAI(), boss_alythessAI::boss_alythessAI(), boss_anetheronAI::boss_anetheronAI(), boss_anomalusAI::boss_anomalusAI(), boss_anzuAI::boss_anzuAI(), boss_apothecary_hummelAI::boss_apothecary_hummelAI(), boss_aranAI::boss_aranAI(), boss_archimondeAI::boss_archimondeAI(), boss_arlokkAI::boss_arlokkAI(), boss_arugalAI::boss_arugalAI(), boss_attumenAI::boss_attumenAI(), boss_ayamissAI::boss_ayamissAI(), boss_azgalorAI::boss_azgalorAI(), boss_azuregosAI::boss_azuregosAI(), boss_baltharusAI::boss_baltharusAI(), boss_baron_geddonAI::boss_baron_geddonAI(), boss_black_stalkerAI::boss_black_stalkerAI(), boss_blackheart_the_inciterAI::boss_blackheart_the_inciterAI(), boss_blindeye_the_seerAI::boss_blindeye_the_seerAI(), boss_broggokAI::boss_broggokAI(), boss_bronjahmAI::boss_bronjahmAI(), boss_broodlordAI::boss_broodlordAI(), boss_brutallusAI::boss_brutallusAI(), boss_buruAI::boss_buruAI(), boss_chromaggusAI::boss_chromaggusAI(), boss_coren_direbrewAI::boss_coren_direbrewAI(), boss_cthunAI::boss_cthunAI(), boss_curatorAI::boss_curatorAI(), boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI(), boss_dorotheeAI::boss_dorotheeAI(), boss_ebonrocAI::boss_ebonrocAI(), boss_entropiusAI::boss_entropiusAI(), boss_eregosAI::boss_eregosAI(), boss_essence_of_angerAI::boss_essence_of_angerAI(), boss_essence_of_desireAI::boss_essence_of_desireAI(), boss_essence_of_sufferingAI::boss_essence_of_sufferingAI(), boss_eye_of_cthunAI::boss_eye_of_cthunAI(), boss_fankrissAI::boss_fankrissAI(), boss_fathomguard_sharkkisAI::boss_fathomguard_sharkkisAI(), boss_fathomguard_tidalvessAI::boss_fathomguard_tidalvessAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_felmystAI::boss_felmystAI(), boss_firemawAI::boss_firemawAI(), boss_flamegorAI::boss_flamegorAI(), boss_forgemaster_garfrostAI::boss_forgemaster_garfrostAI(), boss_galdarahAI::boss_galdarahAI(), boss_garrAI::boss_garrAI(), boss_gathios_the_shattererAI::boss_gathios_the_shattererAI(), boss_gehennasAI::boss_gehennasAI(), boss_golemaggAI::boss_golemaggAI(), boss_gothikAI::boss_gothikAI(), boss_grobbulusAI::boss_grobbulusAI(), boss_gruulAI::boss_gruulAI(), boss_gurtogg_bloodboilAI::boss_gurtogg_bloodboilAI(), boss_hadronoxAI::boss_hadronoxAI(), boss_halazziAI::boss_halazziAI(), boss_heiganAI::boss_heiganAI(), boss_high_astromancer_solarianAI::boss_high_astromancer_solarianAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_high_king_maulgarAI::boss_high_king_maulgarAI(), boss_high_nethermancer_zerevorAI::boss_high_nethermancer_zerevorAI(), boss_highlord_kruulAI::boss_highlord_kruulAI(), boss_huhuranAI::boss_huhuranAI(), boss_hungarfenAI::boss_hungarfenAI(), boss_ichoronAI::boss_ichoronAI(), boss_ickAI::boss_ickAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_ingvarAI::boss_ingvarAI(), boss_janalaiAI::boss_janalaiAI(), boss_kalecgos_humanoidAI::boss_kalecgos_humanoidAI(), boss_kalecgosAI::boss_kalecgosAI(), boss_kazrogalAI::boss_kazrogalAI(), boss_kazzakAI::boss_kazzakAI(), boss_kelesethAI::boss_kelesethAI(), boss_kelidan_the_breakerAI::boss_kelidan_the_breakerAI(), boss_keristraszaAI::boss_keristraszaAI(), boss_kiggler_the_crazedAI::boss_kiggler_the_crazedAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_kriAI::boss_kriAI(), boss_krickAI::boss_krickAI(), boss_krikthirAI::boss_krikthirAI(), boss_krosh_firehandAI::boss_krosh_firehandAI(), boss_kurinnaxxAI::boss_kurinnaxxAI(), boss_lady_blaumeuxAI::boss_lady_blaumeuxAI(), boss_lady_deathwhisperAI::boss_lady_deathwhisperAI(), boss_lady_malandeAI::boss_lady_malandeAI(), boss_lady_vashjAI::boss_lady_vashjAI(), boss_leotheras_the_blindAI::boss_leotheras_the_blindAI(), boss_loathebAI::boss_loathebAI(), boss_lucifronAI::boss_lucifronAI(), boss_magmadarAI::boss_magmadarAI(), boss_magtheridonAI::boss_magtheridonAI(), boss_maiden_of_virtueAI::boss_maiden_of_virtueAI(), boss_maievAI::boss_maievAI(), boss_majordomoAI::boss_majordomoAI(), boss_malacrassAI::boss_malacrassAI(), boss_malchezaarAI::boss_malchezaarAI(), boss_marliAI::boss_marliAI(), boss_midnightAI::boss_midnightAI(), boss_moamAI::boss_moamAI(), boss_moorabiAI::boss_moorabiAI(), boss_moroesAI::boss_moroesAI(), boss_morogrim_tidewalkerAI::boss_morogrim_tidewalkerAI(), boss_muruAI::boss_muruAI(), boss_najentusAI::boss_najentusAI(), boss_nalorakkAI::boss_nalorakkAI(), boss_nefarianAI::boss_nefarianAI(), boss_netherspiteAI::boss_netherspiteAI(), boss_nexusprince_shaffarAI::boss_nexusprince_shaffarAI(), boss_nightbaneAI::boss_nightbaneAI(), boss_nothAI::boss_nothAI(), boss_olm_the_summonerAI::boss_olm_the_summonerAI(), boss_omor_the_unscarredAI::boss_omor_the_unscarredAI(), boss_ormorokAI::boss_ormorokAI(), boss_ossirianAI::boss_ossirianAI(), boss_ouroAI::boss_ouroAI(), boss_patchwerkAI::boss_patchwerkAI(), boss_priestess_delrissaAI::boss_priestess_delrissaAI(), boss_rage_winterchillAI::boss_rage_winterchillAI(), boss_ragnarosAI::boss_ragnarosAI(), boss_razorgoreAI::boss_razorgoreAI(), boss_rimefang_posAI::boss_rimefang_posAI(), boss_rivendare_naxxAI::boss_rivendare_naxxAI(), boss_sacrolashAI::boss_sacrolashAI(), boss_sapphironAI::boss_sapphironAI(), boss_sarturaAI::boss_sarturaAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_scarlet_commander_mograineAI::boss_scarlet_commander_mograineAI(), boss_selin_fireheartAI::boss_selin_fireheartAI(), boss_shahrazAI::boss_shahrazAI(), boss_shazzrahAI::boss_shazzrahAI(), boss_shirrakAI::boss_shirrakAI(), boss_sir_zeliekAI::boss_sir_zeliekAI(), boss_sjonnirAI::boss_sjonnirAI(), boss_skadiAI::boss_skadiAI(), boss_skeramAI::boss_skeramAI(), boss_sladranAI::boss_sladranAI(), boss_spirit_lynxAI::boss_spirit_lynxAI(), boss_sulfuronAI::boss_sulfuronAI(), boss_supremusAI::boss_supremusAI(), boss_svalaAI::boss_svalaAI(), boss_swamplord_muselekAI::boss_swamplord_muselekAI(), boss_talon_king_ikissAI::boss_talon_king_ikissAI(), boss_telestraAI::boss_telestraAI(), boss_temporusAI::boss_temporusAI(), boss_terestianAI::boss_terestianAI(), boss_terokkAI::boss_terokkAI(), boss_teron_gorefiendAI::boss_teron_gorefiendAI(), boss_thaddiusAI::boss_thaddiusAI(), boss_thane_korthazzAI::boss_thane_korthazzAI(), boss_the_lurker_belowAI::boss_the_lurker_belowAI(), boss_the_makerAI::boss_the_makerAI(), boss_twin_emperorsAI::boss_twin_emperorsAI(), boss_tyrannusAI::boss_tyrannusAI(), boss_vaelastraszAI::boss_vaelastraszAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), boss_vazrudenAI::boss_vazrudenAI(), boss_veklorAI::boss_veklorAI(), boss_veknilashAI::boss_veknilashAI(), boss_vemAI::boss_vemAI(), boss_veras_darkshadowAI::boss_veras_darkshadowAI(), boss_vexallusAI::boss_vexallusAI(), boss_victor_nefariusAI::boss_victor_nefariusAI(), boss_viscidusAI::boss_viscidusAI(), boss_void_reaverAI::boss_void_reaverAI(), boss_warlord_kalithreshAI::boss_warlord_kalithreshAI(), boss_watchkeeper_gargolmarAI::boss_watchkeeper_gargolmarAI(), boss_xevozzAI::boss_xevozzAI(), boss_yaujAI::boss_yaujAI(), boss_yorAI::boss_yorAI(), boss_zarithrianAI::boss_zarithrianAI(), boss_zuljinAI::boss_zuljinAI(), hyjalAI::hyjalAI(), mob_arugal_voidwalkerAI::mob_arugal_voidwalkerAI(), mob_bt_battle_fighterAI::mob_bt_battle_fighterAI(), mob_core_ragerAI::mob_core_ragerAI(), mob_dragonflayer_forge_masterAI::mob_dragonflayer_forge_masterAI(), mob_flamewaker_priestAI::mob_flamewaker_priestAI(), mob_hellfire_channelerAI::mob_hellfire_channelerAI(), mob_ohganAI::mob_ohganAI(), mob_shadowmoon_channelerAI::mob_shadowmoon_channelerAI(), mob_solarium_priestAI::mob_solarium_priestAI(), mob_torlothAI::mob_torlothAI(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_akamaAI::npc_akamaAI(), npc_anubisath_defenderAI::npc_anubisath_defenderAI(), npc_apexis_flayerAI::npc_apexis_flayerAI(), npc_apokoAI::npc_apokoAI(), npc_bashir_flesh_fiendAI::npc_bashir_flesh_fiendAI(), npc_bonechewer_brawler::npc_bonechewer_brawler(), npc_bonechewer_combatant::npc_bonechewer_combatant(), npc_burster_wormAI::npc_burster_wormAI(), npc_commanderAI::npc_commanderAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_dawnblade_blood_knight::npc_dawnblade_blood_knight(), npc_death_knight_initiateAI::npc_death_knight_initiateAI(), npc_doomguard_punisherAI::npc_doomguard_punisherAI(), npc_dreadmawAI::npc_dreadmawAI(), npc_ellrys_duskhallowAI::npc_ellrys_duskhallowAI(), npc_eramas_brightblazeAI::npc_eramas_brightblazeAI(), npc_eye_of_shartuulAI::npc_eye_of_shartuulAI(), npc_flame_of_azzinothAI::npc_flame_of_azzinothAI(), npc_garaxxasAI::npc_garaxxasAI(), npc_general_andorovAI::npc_general_andorovAI(), npc_giant_claw_tentacleAI::npc_giant_claw_tentacleAI(), npc_grand_collectorAI::npc_grand_collectorAI(), npc_highlord_darion_mograineAI::npc_highlord_darion_mograineAI(), npc_jaina_proudmooreAI::npc_jaina_proudmooreAI(), npc_kagani_nightstrikeAI::npc_kagani_nightstrikeAI(), npc_kaldorei_eliteAI::npc_kaldorei_eliteAI(), npc_living_mojoAI::npc_living_mojoAI(), npc_magister_aledisAI::npc_magister_aledisAI(), npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), npc_nether_rayAI::npc_nether_rayAI(), npc_razorthorn_ravager::npc_razorthorn_ravager(), npc_shaman_earth_elementalAI::npc_shaman_earth_elementalAI(), npc_shaman_fire_elementalAI::npc_shaman_fire_elementalAI(), npc_shartuulAI::npc_shartuulAI(), npc_shivan_assassinAI::npc_shivan_assassinAI(), npc_skyguard_rangerAI::npc_skyguard_rangerAI(), npc_sunblade_protectorAI::npc_sunblade_protectorAI(), npc_sunblade_scoutAI::npc_sunblade_scoutAI(), npc_thrallAI::npc_thrallAI(), npc_tyrande_whisperwindAI::npc_tyrande_whisperwindAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), npc_warlord_salarisAI::npc_warlord_salarisAI(), npc_yazzaiAI::npc_yazzaiAI(), npc_zelfanAI::npc_zelfanAI(), priestess_commonAI::priestess_commonAI(), npc_sinister_reflectionAI::ReceiveAIEvent(), npc_shattered_hand_legionnaire::Reset(), and ScourgeMinion::ScourgeMinion().
AddCombatAction() [2/5]
void CombatActions::AddCombatAction (uint32 id, std::chrono::milliseconds timer) inline
Definition at line 126 of file TimerAI.h.
AddCombatAction() [3/5]
void CombatActions::AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax) inline
Definition at line 132 of file TimerAI.h.
AddCombatAction() [4/5]
void CombatActions::AddCombatAction (uint32 id, uint32 timer)
Definition at line 196 of file TimerAI.cpp.
References m_actionReadyStatus, m_combatActions, and TIMER_COMBAT_COMBAT.
AddCombatAction() [5/5]
void CombatActions::AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
Definition at line 202 of file TimerAI.cpp.
References m_actionReadyStatus, m_combatActions, and TIMER_COMBAT_COMBAT.
AddTimerlessCombatAction()
void CombatActions::AddTimerlessCombatAction (uint32 id, bool byDefault)
Definition at line 208 of file TimerAI.cpp.
References m_actionReadyStatus, and m_timerlessActionSettings.
Referenced by boss_alarAI::boss_alarAI(), boss_anomalusAI::boss_anomalusAI(), boss_aranAI::boss_aranAI(), boss_archimondeAI::boss_archimondeAI(), boss_attumenAI::boss_attumenAI(), boss_ayamissAI::boss_ayamissAI(), boss_azuregosAI::boss_azuregosAI(), boss_baltharusAI::boss_baltharusAI(), boss_baron_geddonAI::boss_baron_geddonAI(), boss_bronjahmAI::boss_bronjahmAI(), boss_buruAI::boss_buruAI(), boss_chromaggusAI::boss_chromaggusAI(), boss_coren_direbrewAI::boss_coren_direbrewAI(), boss_curatorAI::boss_curatorAI(), boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI(), boss_drakkari_colossusAI::boss_drakkari_colossusAI(), boss_drakkari_elementalAI::boss_drakkari_elementalAI(), boss_eregosAI::boss_eregosAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_forgemaster_garfrostAI::boss_forgemaster_garfrostAI(), boss_golemaggAI::boss_golemaggAI(), boss_gothikAI::boss_gothikAI(), boss_gruulAI::boss_gruulAI(), boss_hakkarAI::boss_hakkarAI(), boss_halazziAI::boss_halazziAI(), boss_high_astromancer_solarianAI::boss_high_astromancer_solarianAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_high_king_maulgarAI::boss_high_king_maulgarAI(), boss_huhuranAI::boss_huhuranAI(), boss_hungarfenAI::boss_hungarfenAI(), boss_ichoronAI::boss_ichoronAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_janalaiAI::boss_janalaiAI(), boss_jeklikAI::boss_jeklikAI(), boss_kalecgos_humanoidAI::boss_kalecgos_humanoidAI(), boss_kalecgosAI::boss_kalecgosAI(), boss_kelidan_the_breakerAI::boss_kelidan_the_breakerAI(), boss_kelthuzadAI::boss_kelthuzadAI(), boss_keristraszaAI::boss_keristraszaAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_krikthirAI::boss_krikthirAI(), boss_kurinnaxxAI::boss_kurinnaxxAI(), boss_lady_vashjAI::boss_lady_vashjAI(), boss_leotheras_the_blindAI::boss_leotheras_the_blindAI(), boss_maexxnaAI::boss_maexxnaAI(), boss_magtheridonAI::boss_magtheridonAI(), boss_malacrassAI::boss_malacrassAI(), boss_malchezaarAI::boss_malchezaarAI(), boss_midnightAI::boss_midnightAI(), boss_moroesAI::boss_moroesAI(), boss_morogrim_tidewalkerAI::boss_morogrim_tidewalkerAI(), boss_muruAI::boss_muruAI(), boss_nefarianAI::boss_nefarianAI(), boss_nightbaneAI::boss_nightbaneAI(), boss_omor_the_unscarredAI::boss_omor_the_unscarredAI(), boss_ormorokAI::boss_ormorokAI(), boss_ouroAI::boss_ouroAI(), boss_patchwerkAI::boss_patchwerkAI(), boss_sarturaAI::boss_sarturaAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_shahrazAI::boss_shahrazAI(), boss_sjonnirAI::boss_sjonnirAI(), boss_skeramAI::boss_skeramAI(), boss_sladranAI::boss_sladranAI(), boss_spirit_lynxAI::boss_spirit_lynxAI(), boss_svalaAI::boss_svalaAI(), boss_swamplord_muselekAI::boss_swamplord_muselekAI(), boss_talon_king_ikissAI::boss_talon_king_ikissAI(), boss_telestraAI::boss_telestraAI(), boss_terokkAI::boss_terokkAI(), boss_thekalAI::boss_thekalAI(), boss_vaelastraszAI::boss_vaelastraszAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), boss_vazrudenAI::boss_vazrudenAI(), boss_venoxisAI::boss_venoxisAI(), boss_vexallusAI::boss_vexallusAI(), boss_watchkeeper_gargolmarAI::boss_watchkeeper_gargolmarAI(), boss_zuljinAI::boss_zuljinAI(), hyjalAI::hyjalAI(), mob_core_ragerAI::mob_core_ragerAI(), npc_akamaAI::npc_akamaAI(), npc_anubisath_defenderAI::npc_anubisath_defenderAI(), npc_anubisath_sentinelAI::npc_anubisath_sentinelAI(), npc_bonechewer_brawler::npc_bonechewer_brawler(), npc_bonechewer_combatant::npc_bonechewer_combatant(), npc_burster_wormAI::npc_burster_wormAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_dawnblade_blood_knight::npc_dawnblade_blood_knight(), npc_doomguard_punisherAI::npc_doomguard_punisherAI(), npc_gurubashi_bat_riderAI::npc_gurubashi_bat_riderAI(), npc_jaina_proudmooreAI::npc_jaina_proudmooreAI(), npc_magister_aledisAI::npc_magister_aledisAI(), npc_sunblade_scoutAI::npc_sunblade_scoutAI(), and priestess_companion_commonAI::priestess_companion_commonAI().
DelayCombatAction() [1/2]
void CombatActions::DelayCombatAction (uint32 index, std::chrono::milliseconds timer) inline
Definition at line 183 of file TimerAI.h.
DelayCombatAction() [2/2]
void CombatActions::DelayCombatAction (uint32 index, uint32 timer) inline
Definition at line 173 of file TimerAI.h.
Referenced by boss_aranAI::ExecuteAction().
DelayTimer() [1/2]
virtual void CombatActions::DelayTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented from TimerManager.
Definition at line 151 of file TimerAI.h.
DelayTimer() [2/2]
void CombatActions::DelayTimer (uint32 index, uint32 timer) override virtual
Reimplemented from TimerManager.
Definition at line 247 of file TimerAI.cpp.
References TimerManager::DelayTimer(), and m_combatActions.
DisableCombatAction()
void CombatActions::DisableCombatAction (uint32 index)
Definition at line 268 of file TimerAI.cpp.
References DisableTimer(), m_timerlessActionSettings, and SetActionReadyStatus().
Referenced by boss_ouroAI::Burrow(), boss_ingvarAI::DamageTaken(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_drakkari_elementalAI::DoPrepareSecondEmerge(), boss_lady_deathwhisperAI::DoStartSecondPhase(), npc_flame_of_azzinothAI::Enrage(), boss_thekalAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_netherspiteAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_dorotheeAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), boss_scarlet_commander_mograineAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), boss_muruAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_malacrassAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_hakkarAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), npc_gurubashi_bat_riderAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_venoxisAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), npc_corrupted_furbolgAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), boss_cthunAI::ExecuteAction(), npc_giant_claw_tentacleAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_twin_emperorsAI::ExecuteAction(), npc_anubisath_sentinelAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_krikthirAI::ExecuteAction(), boss_drakkari_elementalAI::ExecuteAction(), boss_drakkari_colossusAI::ExecuteAction(), npc_living_mojoAI::ExecuteAction(), boss_galdarahAI::ExecuteAction(), boss_sladranAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_rimefang_posAI::ExecuteAction(), boss_deathbringer_saurfangAI::ExecuteAction(), boss_lady_deathwhisperAI::ExecuteAction(), boss_gothikAI::ExecuteAction(), boss_grobbulusAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_kelthuzadAI::ExecuteAction(), boss_loathebAI::ExecuteAction(), boss_maexxnaAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_patchwerkAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_baltharusAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), boss_kelesethAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_xevozzAI::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_flame_of_azzinothAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_gathios_the_shattererAI::ExecuteAction(), boss_fathomguard_sharkkisAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), npc_bonechewer_combatant::HandleEventStart(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_vazruden_heraldAI::HandlePhaseChange(), boss_nightbaneAI::HandlePhaseTransition(), boss_ragnarosAI::HandlePhaseTransition(), boss_halazziAI::HandlePhaseTransition(), boss_zuljinAI::HandlePhaseTransition(), boss_alarAI::HandlePhaseTransition(), boss_brutallusAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), boss_apothecary_hummelAI::JustPreventedDeath(), npc_highlord_darion_mograineAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_illidan_stormrageAI::PreparePhaseTimers(), boss_maievAI::ReceiveAIEvent(), npc_bonechewer_brawler::ReceiveAIEvent(), boss_ichoronAI::ReceiveAIEvent(), boss_moorabiAI::SpellHitTarget(), boss_gurtogg_bloodboilAI::SwitchPhase(), and boss_netherspiteAI::SwitchPhases().
DisableTimer()
void CombatActions::DisableTimer (uint32 index) override virtual
Reimplemented from TimerManager.
Definition at line 226 of file TimerAI.cpp.
References TimerManager::DisableTimer(), and m_combatActions.
Referenced by boss_thaddiusAddsAI::boss_thaddiusAddsAI(), npc_theramore_spar_controller::CheckCombatantHP(), DisableCombatAction(), mob_illidari_councilAI::DoEndEvent(), boss_lady_vashjAI::DoInformGeneratorStopped(), npc_daphne_stilwellAI::DoSendWave(), boss_supremusAI::ExecuteAction(), boss_felblood_kaelthasAI::HandleOutro(), npc_shadowfang_prisonerAI::HandleSpeech(), boss_brutallusAI::JustDidDialogueStep(), boss_lady_vashjAI::JustDied(), npc_ethereal_sphereAI::MoveInLineOfSight(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), mob_zealot_lorkhanAI::PreventRevive(), mob_zealot_zathAI::PreventRevive(), npc_shivan_assassinAI::ReceiveAIEvent(), hyjalAI::ReceiveAIEvent(), boss_anzuAI::Reset(), boss_reliquary_of_soulsAI::Reset(), mob_illidari_councilAI::Reset(), and npc_commanderAI::ResetEvent().
ExecuteActions()
virtual void CombatActions::ExecuteActions () pure virtual
Implemented in npc_vindicator_sedaiAI, npc_apexis_flayerAI, npc_grand_collectorAI, npc_bashir_flesh_fiendAI, npc_skyguard_rangerAI, boss_anzuAI, npc_ethereum_prisoner_dungeonAI, boss_yorAI, priestess_commonAI, boss_highlord_kruulAI, boss_kaelthasAI, mob_bt_battle_fighterAI, npc_kaylaan_the_lostAI, boss_warlord_kalithreshAI, boss_kazzakAI, and UnitAI.
GetActionReadyStatus()
bool CombatActions::GetActionReadyStatus (uint32 index) inline
Definition at line 189 of file TimerAI.h.
Referenced by boss_vazruden_heraldAI::DoMoveToCombat(), boss_malchezaarAI::ExecuteAction(), UnitAI::ExecuteActions(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), priestess_commonAI::ExecuteActions(), boss_yorAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), npc_skyguard_rangerAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_grand_collectorAI::ExecuteActions(), npc_apexis_flayerAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteAssassinActions(), mob_bt_battle_fighterAI::ExecuteCaalenActions(), mob_bt_battle_fighterAI::ExecuteMagisterActions(), mob_bt_battle_fighterAI::ExecuteRavagerActions(), mob_bt_battle_fighterAI::ExecuteShadowlordActions(), mob_bt_battle_fighterAI::ExecuteSuccubusActions(), mob_bt_battle_fighterAI::ExecuteVindicatorActions(), boss_curatorAI::GetSubsequentActionTimer(), boss_vazrudenAI::JustDied(), boss_midnightAI::KilledUnit(), and boss_illidan_stormrageAI::ReceiveAIEvent().
GetAIInformation()
void CombatActions::GetAIInformation (ChatHandler & reader) override virtual
Reimplemented from TimerManager.
Reimplemented in boss_kaelthasAI, npc_commanderAI, npc_simon_game_bunnyAI, boss_illidan_stormrageAI, npc_anubisath_sentinelAI, npc_arthasAI, boss_kiljaedenAI, boss_brutallusAI, mob_arugal_voidwalkerAI, npc_highlord_darion_mograineAI, boss_thermapluggAI, Scripted_NoMovementAI, ScriptedAI, npc_escortAI, CreatureEventAI, and UnitAI.
Definition at line 275 of file TimerAI.cpp.
References Timer::disabled, Timer::id, m_combatActions, ChatHandler::PSendSysMessage(), and Timer::timer.
Referenced by npc_commanderAI::GetAIInformation().
GetCombatActionCount()
size_t CombatActions::GetCombatActionCount () inline
Definition at line 197 of file TimerAI.h.
Referenced by UnitAI::ExecuteActions(), and priestess_commonAI::ExecuteActions().
ReduceTimer() [1/2]
virtual void CombatActions::ReduceTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented from TimerManager.
Definition at line 146 of file TimerAI.h.
ReduceTimer() [2/2]
void CombatActions::ReduceTimer (uint32 index, uint32 timer) override virtual
Reimplemented from TimerManager.
Definition at line 238 of file TimerAI.cpp.
References m_combatActions, and TimerManager::ReduceTimer().
Referenced by boss_reliquary_of_soulsAI::DoNotifySouldDead(), and boss_ragnarosAI::SummonedCreatureJustDied().
ResetAllTimers()
void CombatActions::ResetAllTimers () override virtual
Reimplemented from TimerManager.
Definition at line 175 of file TimerAI.cpp.
References m_actionReadyStatus, m_combatActions, m_timerlessActionSettings, and TimerManager::ResetAllTimers().
Referenced by CreatureAI::Reset(), and mob_water_globuleAI::Reset().
ResetCombatAction() [1/2]
void CombatActions::ResetCombatAction (uint32 index, std::chrono::milliseconds timer) inline
Definition at line 168 of file TimerAI.h.
ResetCombatAction() [2/2]
void CombatActions::ResetCombatAction (uint32 index, uint32 timer) inline
Definition at line 163 of file TimerAI.h.
Referenced by npc_anubisath_defenderAI::Aggro(), boss_sapphironAI::Aggro(), boss_swamplord_muselekAI::DistancingEnded(), boss_buruAI::DoAttackNewTarget(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_alarAI::DoPlatformMove(), boss_anomalusAI::DoResumeCombat(), boss_cthunAI::DoSpawnTentacles(), boss_lady_deathwhisperAI::DoStartSecondPhase(), boss_ichoronAI::EndSplitPhase(), boss_high_inquisitor_whitemaneAI::EnterCombat(), boss_baron_geddonAI::ExecuteAction(), npc_sunblade_scoutAI::ExecuteAction(), npc_sunblade_protectorAI::ExecuteAction(), mob_ohganAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_watchkeeper_gargolmarAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_broodlordAI::ExecuteAction(), boss_chromaggusAI::ExecuteAction(), boss_ebonrocAI::ExecuteAction(), boss_firemawAI::ExecuteAction(), boss_flamegorAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_razorgoreAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_victor_nefariusAI::ExecuteAction(), npc_dawnblade_blood_knight::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_maiden_of_virtueAI::ExecuteAction(), boss_midnightAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_netherspiteAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_dorotheeAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), priestess_commonAI::ExecuteAction(), boss_priestess_delrissaAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), npc_ellrys_duskhallowAI::ExecuteAction(), npc_eramas_brightblazeAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), npc_warlord_salarisAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), npc_apokoAI::ExecuteAction(), npc_zelfanAI::ExecuteAction(), boss_selin_fireheartAI::ExecuteAction(), boss_vexallusAI::ExecuteAction(), boss_garrAI::ExecuteAction(), boss_gehennasAI::ExecuteAction(), boss_golemaggAI::ExecuteAction(), mob_core_ragerAI::ExecuteAction(), boss_lucifronAI::ExecuteAction(), boss_magmadarAI::ExecuteAction(), boss_majordomoAI::ExecuteAction(), boss_ragnarosAI::ExecuteAction(), boss_shazzrahAI::ExecuteAction(), boss_sulfuronAI::ExecuteAction(), mob_flamewaker_priestAI::ExecuteAction(), npc_death_knight_initiateAI::ExecuteAction(), npc_highlord_darion_mograineAI::ExecuteAction(), boss_scarlet_commander_mograineAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_apothecary_hummelAI::ExecuteAction(), mob_arugal_voidwalkerAI::ExecuteAction(), boss_arugalAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kalecgos_humanoidAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), npc_sinister_reflectionAI::ExecuteAction(), boss_entropiusAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_spirit_lynxAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_malacrassAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_zuljinAI::ExecuteAction(), boss_arlokkAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), boss_anetheronAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_azgalorAI::ExecuteAction(), boss_kazrogalAI::ExecuteAction(), boss_rage_winterchillAI::ExecuteAction(), hyjalAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), npc_thrallAI::ExecuteAction(), npc_tyrande_whisperwindAI::ExecuteAction(), npc_corrupted_furbolgAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_moamAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), npc_general_andorovAI::ExecuteAction(), npc_kaldorei_eliteAI::ExecuteAction(), boss_kriAI::ExecuteAction(), boss_vemAI::ExecuteAction(), boss_yaujAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_cthunAI::ExecuteAction(), npc_giant_claw_tentacleAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_twin_emperorsAI::ExecuteAction(), boss_veknilashAI::ExecuteAction(), boss_veklorAI::ExecuteAction(), boss_viscidusAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_hadronoxAI::ExecuteAction(), boss_krikthirAI::ExecuteAction(), npc_nerubian_burrowerAI::ExecuteAction(), npc_living_mojoAI::ExecuteAction(), boss_moorabiAI::ExecuteAction(), boss_sladranAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_ickAI::ExecuteAction(), boss_krickAI::ExecuteAction(), boss_tyrannusAI::ExecuteAction(), boss_rimefang_posAI::ExecuteAction(), boss_deathbringer_saurfangAI::ExecuteAction(), boss_lady_deathwhisperAI::ExecuteAction(), boss_lady_blaumeuxAI::ExecuteAction(), boss_rivendare_naxxAI::ExecuteAction(), boss_thane_korthazzAI::ExecuteAction(), boss_sir_zeliekAI::ExecuteAction(), boss_gothikAI::ExecuteAction(), boss_grobbulusAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_loathebAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_thaddiusAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_keristraszaAI::ExecuteAction(), boss_ormorokAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_eregosAI::ExecuteAction(), boss_baltharusAI::ExecuteAction(), boss_zarithrianAI::ExecuteAction(), boss_sjonnirAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), boss_kelesethAI::ExecuteAction(), mob_dragonflayer_forge_masterAI::ExecuteAction(), boss_skadiAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_ichoronAI::ExecuteAction(), boss_xevozzAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_nexusprince_shaffarAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), npc_bonechewer_combatant::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_akama_illidanAI::ExecuteAction(), boss_maievAI::ExecuteAction(), npc_flame_of_azzinothAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_essence_of_sufferingAI::ExecuteAction(), boss_essence_of_desireAI::ExecuteAction(), boss_essence_of_angerAI::ExecuteAction(), npc_akamaAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_gathios_the_shattererAI::ExecuteAction(), boss_high_nethermancer_zerevorAI::ExecuteAction(), boss_lady_malandeAI::ExecuteAction(), boss_veras_darkshadowAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_fathomguard_sharkkisAI::ExecuteAction(), boss_fathomguard_tidalvessAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_black_stalkerAI::ExecuteAction(), boss_hungarfenAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_olm_the_summonerAI::ExecuteAction(), boss_kiggler_the_crazedAI::ExecuteAction(), boss_blindeye_the_seerAI::ExecuteAction(), boss_krosh_firehandAI::ExecuteAction(), boss_broggokAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), mob_shadowmoon_channelerAI::ExecuteAction(), boss_the_makerAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_vazrudenAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), mob_hellfire_channelerAI::ExecuteAction(), npc_shattered_hand_legionnaire::ExecuteAction(), npc_magister_aledisAI::ExecuteAction(), npc_razorthorn_ravager::ExecuteAction(), mob_torlothAI::ExecuteAction(), npc_commanderAI::ExecuteAction(), npc_doomguard_punisherAI::ExecuteAction(), npc_eye_of_shartuulAI::ExecuteAction(), npc_dreadmawAI::ExecuteAction(), npc_shartuulAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), mob_solarium_priestAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), npc_shaman_fire_elementalAI::ExecuteAction(), npc_shaman_earth_elementalAI::ExecuteAction(), boss_kiljaedenAI::HandleAttackDelay(), boss_nefarianAI::HandleAttackStart(), boss_ahuneAI::HandleEmerge(), boss_eye_of_cthunAI::HandleEndDarkGlare(), boss_gothikAI::HandleGroundPhase(), boss_heiganAI::HandleGroundPhase(), boss_skeramAI::HandleInitImages(), boss_telestraAI::HandlePersonalityMerge(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_vazruden_heraldAI::HandlePhaseChange(), boss_nightbaneAI::HandlePhaseTransition(), boss_ragnarosAI::HandlePhaseTransition(), boss_halazziAI::HandlePhaseTransition(), boss_zuljinAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_alarAI::HandlePhaseTransition(), boss_high_inquisitor_whitemaneAI::HandleResurrectionCombat(), boss_scarlet_commander_mograineAI::HandleRevivedTimer(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_the_lurker_belowAI::HandleSpoutEnd(), boss_the_lurker_belowAI::HandleSubmergeActions(), boss_felmystAI::HandleTransitionDelay(), boss_kiljaedenAI::JustDidDialogueStep(), npc_highlord_darion_mograineAI::JustSummoned(), boss_forgemaster_garfrostAI::MovementInform(), npc_akama_illidanAI::MovementInform(), IceBolt::OnEffectExecute(), boss_temporusAI::OnSpellCooldownAdded(), npc_nether_rayAI::OnSpellCooldownAdded(), boss_felmystAI::OnSpellCooldownAdded(), boss_anetheronAI::OnSpellCooldownAdded(), boss_archimondeAI::OnSpellCooldownAdded(), boss_teron_gorefiendAI::OnSpellCooldownAdded(), boss_essence_of_desireAI::OnSpellInterrupt(), boss_illidan_stormrageAI::PreparePhaseTimers(), boss_maievAI::ReceiveAIEvent(), boss_kiljaedenAI::ReceiveAIEvent(), boss_muruAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), boss_selin_fireheartAI::ReceiveAIEvent(), npc_bonechewer_brawler::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), boss_galdarahAI::ReceiveAIEvent(), boss_rimefang_posAI::ReceiveAIEvent(), ScourgeMinion::ScourgeMinion(), boss_ossirianAI::SpellHit(), boss_marliAI::SpellHitTarget(), boss_bronjahmAI::SpellHitTarget(), boss_malacrassAI::SpellHitTarget(), boss_xevozzAI::SummonedCreatureDespawn(), boss_fathomguard_sharkkisAI::SummonedCreatureJustDied(), boss_nightbaneAI::SummonedCreatureJustDied(), boss_gurtogg_bloodboilAI::SwitchPhase(), boss_netherspiteAI::SwitchPhases(), and npc_bonechewer_combatant::UpdateAI().
ResetIfNotStarted() [1/2]
virtual void CombatActions::ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented from TimerManager.
Definition at line 156 of file TimerAI.h.
ResetIfNotStarted() [2/2]
void CombatActions::ResetIfNotStarted (uint32 index, uint32 timer) override virtual
Reimplemented from TimerManager.
Definition at line 256 of file TimerAI.cpp.
References m_combatActions, and TimerManager::ResetIfNotStarted().
Referenced by boss_lady_vashjAI::SummonedCreatureDespawn().
ResetTimer() [1/2]
virtual void CombatActions::ResetTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented from TimerManager.
Definition at line 140 of file TimerAI.h.
ResetTimer() [2/2]
void CombatActions::ResetTimer (uint32 index, uint32 timer) override virtual
Reimplemented from TimerManager.
Definition at line 214 of file TimerAI.cpp.
References m_combatActions, and TimerManager::ResetTimer().
Referenced by mob_water_globuleAI::AcquireNewTarget(), boss_kelidan_the_breakerAI::AddJustReachedHome(), boss_kalecgos_humanoidAI::Aggro(), boss_akilzonAI::Aggro(), boss_zuljinAI::Aggro(), boss_gothikAI::Aggro(), npc_burster_wormAI::Aggro(), boss_anubrekhanAI::Aggro(), boss_gluthAI::Aggro(), BossAI::Aggro(), boss_heiganAI::Aggro(), boss_vaelastraszAI::BeginIntro(), boss_vaelastraszAI::BeginSpeech(), boss_gothikAI::boss_gothikAI(), boss_moorabiAI::boss_moorabiAI(), boss_reliquary_of_soulsAI::boss_reliquary_of_soulsAI(), boss_supremusAI::boss_supremusAI(), npc_theramore_spar_controller::CheckCombatantHP(), mob_arugal_voidwalkerAI::CheckGroupStatus(), npc_theramore_spar_controller::CombatantIntro(), npc_theramore_spar_controller::CombatantSalute(), npc_theramore_spar_controller::CombatantSeparate(), boss_deathbringer_saurfangAI::DamageTaken(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_drakkari_colossusAI::DoPrepareColossus(), npc_daphne_stilwellAI::DoSendWave(), mob_phoenix_tkAI::DoSetFakeDeath(), boss_kelidan_the_breakerAI::DoSetupAdds(), mob_illidari_councilAI::DoStartEvent(), npc_lady_sylvanas_windrunnerAI::DoStartLamentEvent(), boss_kalecgosAI::DoStartOutro(), boss_skeramAI::DoTeleport(), npc_enslaved_soulAI::EnterEvadeMode(), hyjalAI::EventStarted(), boss_talon_king_ikissAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_muruAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_moamAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), npc_nerubian_burrowerAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_kelthuzadAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), boss_yorAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), npc_skyguard_rangerAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_grand_collectorAI::ExecuteActions(), npc_apexis_flayerAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteAssassinActions(), mob_bt_battle_fighterAI::ExecuteCaalenActions(), mob_bt_battle_fighterAI::ExecuteMagisterActions(), mob_bt_battle_fighterAI::ExecuteRavagerActions(), mob_bt_battle_fighterAI::ExecuteShadowlordActions(), PlayerAI::ExecuteSpells(), mob_bt_battle_fighterAI::ExecuteSuccubusActions(), mob_bt_battle_fighterAI::ExecuteVindicatorActions(), npc_singularityAI::FindTarget(), DarkFiendAI::FindTarget(), npc_commanderAI::FinishedWaypointMovement(), npc_commander_hobbAI::FinishedWaypointMovement(), npc_commander_arcusAI::FinishedWaypointMovement(), ChildTbcAI::HandleAerisLanding(), mob_torlothAI::HandleAnimation(), npc_razorthorn_ravager_pet::HandleAnimations(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), ChildTbcAI::HandleCallOfTheFarseer(), npc_burster_wormAI::HandleChaseSequence(), boss_lady_vashjAI::HandleCoilfangElite(), boss_lady_vashjAI::HandleCoilfangStrider(), CombatAI::HandleDelayedInstantAnimation(), boss_felmystAI::HandleDemonicVapor(), boss_alarAI::HandleDiveBomb(), boss_aranAI::HandleDrinking(), mob_phoenix_tkAI::HandleEmberBlast(), boss_lady_vashjAI::HandleEnchantedElemental(), boss_ragnarosAI::HandleEnterCombat(), npc_grand_collectorAI::HandleEvent(), boss_kalecgosAI::HandleExit(), boss_felmystAI::HandleFelmystSpawnDelay(), npc_shartuulAI::HandleFightSequence(), boss_felblood_kaelthasAI::HandleGravityLapse(), boss_heiganAI::HandleGroundPhase(), ChildTbcAI::HandleHchuuAndTheMushroomPeople(), boss_vaelastraszAI::HandleIntro(), boss_felblood_kaelthasAI::HandleIntro(), boss_lady_vashjAI::HandleIntroText(), boss_scarlet_commander_mograineAI::HandleLayOnHandsTimer(), boss_brutallusAI::HandleMadrigosaFrostbolt(), ChildTbcAI::HandleNowWhenIGrowUp(), npc_shivan_assassinAI::HandleOocAnim(), boss_felblood_kaelthasAI::HandleOutro(), boss_majordomoAI::HandleOutro(), npc_akama_illidanAI::HandleOutro(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_magtheridonAI::HandlePhaseTransition(), boss_buruAI::HandlePhaseTwo(), npc_ethereal_sphereAI::HandlePlayerSummon(), boss_alarAI::HandleRebirth(), boss_high_inquisitor_whitemaneAI::HandleResurrection(), ChildTbcAI::HandleSeatOfTheNaaru(), mob_shadowmoon_channelerAI::HandleSetup(), npc_singularityAI::HandleSpawn(), boss_vaelastraszAI::HandleSpeech(), npc_shadowfang_prisonerAI::HandleSpeech(), boss_high_astromancer_solarianAI::HandleSplitAgents(), boss_high_astromancer_solarianAI::HandleSplitPhaseDelay(), boss_lady_vashjAI::HandleSporebat(), npc_khadgars_servantAI::HandleStart(), boss_the_lurker_belowAI::HandleSubmergeActions(), TorchTossingTargetBunnyControllerAI::HandleTargetChange(), npc_caribdis_cyclone::HandleTargetPick(), boss_heiganAI::HandleTaunt(), ChildTbcAI::HandleTimeToVisitTheCaverns(), npc_kalecgosAI::HandleTransform(), boss_felmystAI::HandleTransition(), ChildTbcAI::HandleTripToTheDarkPortal(), ChildTbcAI::HandleVisitTheThroneOfTheElements(), boss_cthunAI::HandleWeaken(), npc_theramore_spar_controller::HandleWin(), hyjalAI::hyjalAI(), boss_brutallusAI::JustDidDialogueStep(), npc_dawnblade_blood_knight::JustReachedHome(), boss_majordomoAI::JustReachedHome(), boss_leotheras_the_blindAI::JustReachedHome(), boss_kelidan_the_breakerAI::JustReachedHome(), boss_nefarianAI::JustRespawned(), npc_dawnblade_blood_knight::JustRespawned(), boss_felmystAI::JustRespawned(), npc_general_andorovAI::JustRespawned(), npc_ouro_moundAI::JustRespawned(), boss_anzuAI::JustRespawned(), npc_disruptor_towerAI::JustRespawned(), npc_fire_nova_totemAI::JustRespawned(), boss_brutallusAI::JustSummoned(), boss_kiljaedenAI::JustSummoned(), boss_anetheronAI::JustSummoned(), boss_veras_darkshadowAI::JustSummoned(), boss_kurinnaxxAI::JustSummoned(), CombatAI::KilledUnit(), mob_illidari_councilAI::mob_illidari_councilAI(), MouthAI::MouthAI(), npc_theramore_spar_controller::MoveIntoPosition(), npc_bashir_flesh_fiendAI::MovementInform(), boss_silithidRoyaltyAI::MovementInform(), boss_nightbaneAI::MovementInform(), boss_felmystAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), boss_alarAI::MovementInform(), npc_doom_blossomAI::MovementInform(), NetherCharge::MovementInform(), npc_razorthorn_ravager_pet::MovementInform(), npc_corrupted_furbolgAI::MovementInform(), boss_illidan_stormrageAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_nefarianAI::MovementInform(), boss_high_inquisitor_whitemaneAI::MovementInform(), npc_krunAI::MovementInform(), NecroticShard::NecroticShard(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_doom_blossomAI::npc_doom_blossomAI(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_krunAI::npc_krunAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), HodirsProtectiveGaze::OnAbsorb(), boss_thekalAI::OnFakeingDeath(), mob_zealot_lorkhanAI::OnFakeingDeath(), mob_zealot_zathAI::OnFakeingDeath(), boss_thekalAI::OnRevive(), boss_omor_the_unscarredAI::OnSpellCooldownAdded(), CombatAI::OnTaunt(), PallidHorrorAI::PallidHorrorAI(), npc_ouro_moundAI::PickNewTarget(), boss_telestraAI::ReceiveAIEvent(), boss_aranAI::ReceiveAIEvent(), boss_alythessAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), boss_muruAI::ReceiveAIEvent(), boss_janalaiAI::ReceiveAIEvent(), boss_arlokkAI::ReceiveAIEvent(), npc_general_andorovAI::ReceiveAIEvent(), boss_cthunAI::ReceiveAIEvent(), npc_akama_illidanAI::ReceiveAIEvent(), npc_creature_generatorAI::ReceiveAIEvent(), boss_supremusAI::ReceiveAIEvent(), npc_shattered_hand_legionnaire::ReceiveAIEvent(), npc_cultist_engineer::ReceiveAIEvent(), npc_doomguard_punisherAI::ReceiveAIEvent(), npc_shivan_assassinAI::ReceiveAIEvent(), npc_eye_of_shartuulAI::ReceiveAIEvent(), npc_dreadmawAI::ReceiveAIEvent(), boss_lady_vashjAI::ReceiveAIEvent(), mob_shadowmoon_channelerAI::ReceiveAIEvent(), boss_skadiAI::ReceiveAIEvent(), npc_akamaAI::ReceiveAIEvent(), boss_kazzakAI::Reset(), boss_yorAI::Reset(), boss_anzuAI::Reset(), npc_skyguard_rangerAI::Reset(), npc_bashir_flesh_fiendAI::Reset(), npc_grand_collectorAI::Reset(), npc_apexis_flayerAI::Reset(), boss_warlord_kalithreshAI::Reset(), mob_bt_battle_fighterAI::Reset(), boss_highlord_kruulAI::Reset(), npc_corrupted_furbolgAI::SeekPurification(), boss_sartharionAI::SendFlameTsunami(), boss_viscidusAI::SetPhase(), boss_zuljinAI::SpellHit(), boss_najentusAI::SpellHit(), boss_maievAI::SpellHit(), boss_scarlet_commander_mograineAI::SpellHit(), boss_ragnarosAI::SpellHitTarget(), ChildTbcAI::StartAerisLandingScript(), ChildTbcAI::StartAuchindounScript(), ChildTbcAI::StartCoTScript(), ChildTbcAI::StartDarkPortalScript(), boss_twin_emperorsAI::StartDelayedAttack(), boss_reliquary_of_soulsAI::StartEvent(), npc_commanderAI::StartEvent(), boss_yorAI::StartEvent(), npc_ethereum_prisoner_dungeonAI::StartEvent(), npc_ethereum_prisonerAI::StartEvent(), ChildTbcAI::StartFarseerScript(), ChildTbcAI::StartLvl70ETCScript(), ChildTbcAI::StartSeatScript(), npc_theramore_spar_controller::StartSparring(), ChildTbcAI::StartSporeggarScript(), boss_majordomoAI::StartSummonEvent(), ChildTbcAI::StartThroneScript(), boss_terestianAI::SummonedCreatureJustDied(), boss_lady_vashjAI::SummonedCreatureJustDied(), boss_reliquary_of_soulsAI::SummonedMovementInform(), npc_theramore_spar_controller::SwitchMembers(), UnitAI::UpdateAI(), UnitAI::UpdateSpellLists(), npc_shadowfang_prisonerAI::WaypointReached(), npc_daphne_stilwellAI::WaypointReached(), and npc_commanderAI::WinEvent().
SetActionReadyStatus()
void CombatActions::SetActionReadyStatus (uint32 index, bool state) inline
Definition at line 188 of file TimerAI.h.
Referenced by boss_thekalAI::boss_thekalAI(), boss_archimondeAI::CheckLeash(), DisableCombatAction(), boss_swamplord_muselekAI::DistancingEnded(), boss_illidan_stormrageAI::DoInformFlameKilled(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_vazruden_heraldAI::DoMoveToCombat(), boss_midnightAI::DoPrepareMount(), boss_baron_geddonAI::ExecuteAction(), npc_sunblade_scoutAI::ExecuteAction(), boss_watchkeeper_gargolmarAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_chromaggusAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_midnightAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), priestess_companion_commonAI::ExecuteAction(), boss_vexallusAI::ExecuteAction(), boss_golemaggAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kalecgos_humanoidAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_malacrassAI::ExecuteAction(), boss_zuljinAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), hyjalAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_buruAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_keristraszaAI::ExecuteAction(), boss_ormorokAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_ichoronAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), npc_bonechewer_combatant::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), npc_akamaAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_hungarfenAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), npc_doomguard_punisherAI::ExecuteAction(), npc_shivan_assassinAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), boss_yorAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), npc_skyguard_rangerAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_grand_collectorAI::ExecuteActions(), npc_apexis_flayerAI::ExecuteActions(), mob_bt_battle_fighterAI::ExecuteAssassinActions(), mob_bt_battle_fighterAI::ExecuteCaalenActions(), mob_bt_battle_fighterAI::ExecuteMagisterActions(), mob_bt_battle_fighterAI::ExecuteRavagerActions(), mob_bt_battle_fighterAI::ExecuteShadowlordActions(), mob_bt_battle_fighterAI::ExecuteSuccubusActions(), mob_bt_battle_fighterAI::ExecuteVindicatorActions(), boss_halazziAI::HandlePhaseTransition(), boss_scarlet_commander_mograineAI::HandleRevivedTimer(), boss_muruAI::JustPreventedDeath(), npc_doomguard_punisherAI::JustPreventedDeath(), npc_shivan_assassinAI::JustPreventedDeath(), boss_alarAI::JustPreventedDeath(), npc_dawnblade_blood_knight::JustRespawned(), boss_janalaiAI::JustSummoned(), boss_vazrudenAI::MakeNazanLand(), boss_zuljinAI::MovementInform(), boss_felblood_kaelthasAI::ReceiveAIEvent(), boss_kazzakAI::Reset(), boss_yorAI::Reset(), boss_anzuAI::Reset(), npc_skyguard_rangerAI::Reset(), npc_bashir_flesh_fiendAI::Reset(), npc_grand_collectorAI::Reset(), npc_apexis_flayerAI::Reset(), boss_warlord_kalithreshAI::Reset(), mob_bt_battle_fighterAI::Reset(), boss_highlord_kruulAI::Reset(), and boss_buruAI::ScheduleNewTarget().
UpdateTimers()
void CombatActions::UpdateTimers (const uint32 diff, bool combat) override virtual
Reimplemented from TimerManager.
Definition at line 164 of file TimerAI.cpp.
References Timer::functor, m_combatActions, Timer::UpdateTimer(), and TimerManager::UpdateTimers().
Referenced by npc_skyguard_rangerAI::UpdateAI(), PetAI::UpdateAI(), boss_kazzakAI::UpdateAI(), boss_archimondeAI::UpdateAI(), boss_yorAI::UpdateAI(), npc_ethereum_prisoner_dungeonAI::UpdateAI(), boss_anzuAI::UpdateAI(), npc_bashir_flesh_fiendAI::UpdateAI(), npc_grand_collectorAI::UpdateAI(), npc_akamaAI::UpdateAI(), npc_apexis_flayerAI::UpdateAI(), boss_warlord_kalithreshAI::UpdateAI(), npc_commanderAI::UpdateAI(), boss_highlord_kruulAI::UpdateAI(), boss_sartharionAI::UpdateAI(), mob_bt_battle_fighterAI::UpdateAI(), UnitAI::UpdateAI(), npc_daphne_stilwellAI::UpdateEscortAI(), and npc_khadgars_servantAI::UpdateEscortAI().
Field Documentation
m_actionReadyStatus
std::vector<bool> CombatActions::m_actionReadyStatus private
Definition at line 201 of file TimerAI.h.
Referenced by AddCombatAction(), AddTimerlessCombatAction(), and ResetAllTimers().
m_combatActions
std::map<uint32, Timer> CombatActions::m_combatActions private
Definition at line 200 of file TimerAI.h.
Referenced by AddCombatAction(), DelayTimer(), DisableTimer(), GetAIInformation(), ReduceTimer(), ResetAllTimers(), ResetIfNotStarted(), ResetTimer(), and UpdateTimers().
m_spellAction
std::map<uint32, uint32> CombatActions::m_spellAction private
Definition at line 203 of file TimerAI.h.
m_timerlessActionSettings
std::map<uint32, bool> CombatActions::m_timerlessActionSettings private
Definition at line 202 of file TimerAI.h.
Referenced by AddTimerlessCombatAction(), DisableCombatAction(), and ResetAllTimers().
The documentation for this class was generated from the following files:
TimerAI.h
TimerAI.cpp