CMaNGOS_WoTLK: AuthCrypt Class Reference
AuthCrypt Class Reference
#include <AuthCrypt.h>
Public Member Functions
AuthCrypt ()
void Init (BigNumber *K)
void DecryptRecv (uint8 *, size_t)
void EncryptSend (uint8 *, size_t)
Private Attributes
SARC4 _clientDecrypt
SARC4 _serverEncrypt
bool _initialized
Detailed Description
Definition at line 27 of file AuthCrypt.h.
Constructor & Destructor Documentation
AuthCrypt()
AuthCrypt::AuthCrypt ()
Definition at line 25 of file AuthCrypt.cpp.
Member Function Documentation
DecryptRecv()
void AuthCrypt::DecryptRecv (uint8 * data, size_t len)
Definition at line 59 of file AuthCrypt.cpp.
References _clientDecrypt, _initialized, and SARC4::UpdateData().
Referenced by WorldSocket::ProcessIncomingData().
EncryptSend()
void AuthCrypt::EncryptSend (uint8 * data, size_t len)
Definition at line 67 of file AuthCrypt.cpp.
References _initialized, _serverEncrypt, and SARC4::UpdateData().
Referenced by WorldSocket::SendPacket().
Init()
void AuthCrypt::Init (BigNumber * K)
Definition at line 27 of file AuthCrypt.cpp.
References _clientDecrypt, _initialized, _serverEncrypt, HMACSHA1::ComputeHash(), SARC4::Init(), SEED_KEY_SIZE, and SARC4::UpdateData().
Referenced by WorldSocket::HandleAuthSession().
Field Documentation
_clientDecrypt
SARC4 AuthCrypt::_clientDecrypt private
Definition at line 37 of file AuthCrypt.h.
Referenced by DecryptRecv(), and Init().
_initialized
bool AuthCrypt::_initialized private
Definition at line 39 of file AuthCrypt.h.
Referenced by DecryptRecv(), EncryptSend(), and Init().
_serverEncrypt
SARC4 AuthCrypt::_serverEncrypt private
Definition at line 38 of file AuthCrypt.h.
Referenced by EncryptSend(), and Init().
The documentation for this class was generated from the following files:
AuthCrypt.h
AuthCrypt.cpp