CMaNGOS_WoTLK: ScriptDevAIMgr Class Reference
ScriptDevAIMgr Class Reference
#include <ScriptDevAIMgr.h>
Public Member Functions
ScriptDevAIMgr ()
~ScriptDevAIMgr ()
void Initialize ()
void LoadScriptNames ()
void CheckScriptNames ()
void LoadAreaTriggerScripts ()
void LoadEventIdScripts ()
bool OnGossipHello (Player *pPlayer, Creature *pCreature)
bool OnGossipHello (Player *pPlayer, GameObject *pGo)
bool OnGossipSelect (Player *pPlayer, Creature *pCreature, uint32 uiSender, uint32 uiAction, const char *code)
bool OnGossipSelect (Player *pPlayer, GameObject *pGo, uint32 uiSender, uint32 uiAction, const char *code)
bool OnQuestAccept (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
bool OnQuestAccept (Player *pPlayer, GameObject *pGo, Quest const *pQuest)
bool OnQuestAccept (Player *pPlayer, Item *pItem, Quest const *pQuest)
bool OnQuestRewarded (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
bool OnQuestRewarded (Player *pPlayer, GameObject *pGo, Quest const *pQuest)
uint32 GetDialogStatus (const Player *pPlayer, const Creature *pCreature) const
uint32 GetDialogStatus (const Player *pPlayer, const GameObject *pGo) const
bool OnGameObjectUse (Player *pPlayer, GameObject *pGo)
std::function< bool(Unit *)> * OnTrapSearch (GameObject *go)
bool OnItemUse (Player *pPlayer, Item *pItem, SpellCastTargets const &targets)
bool OnItemLoot (Player *pPlayer, Item *pItem, bool apply)
bool OnAreaTrigger (Player *pPlayer, AreaTriggerEntry const *atEntry)
bool OnProcessEvent (uint32 uiEventId, Object *pSource, Object *pTarget, bool bIsStart)
bool OnEffectDummy (Unit *pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature *pTarget, ObjectGuid originalCasterGuid)
bool OnEffectDummy (Unit *pCaster, uint32 spellId, SpellEffectIndex effIndex, GameObject *pTarget, ObjectGuid originalCasterGuid)
bool OnEffectDummy (Unit *pCaster, uint32 spellId, SpellEffectIndex effIndex, Item *pTarget, ObjectGuid originalCasterGuid)
bool OnEffectScriptEffect (Unit *pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature *pTarget, ObjectGuid originalCasterGuid)
bool OnAuraDummy (Aura const *pAura, bool bApply)
bool OnNpcSpellClick (Player *pPlayer, Creature *pClickedCreature, uint32 spellId)
void AddScript (uint32 id, Script *script)
Script * GetScript (uint32 id) const
const char * GetScriptName (uint32 id) const
uint32 GetScriptId (const char *name) const
uint32 GetScriptIdsCount () const
UnitAI * GetCreatureAI (Creature *pCreature) const
GameObjectAI * GetGameObjectAI (GameObject *gameobject) const
InstanceData * CreateInstanceData (Map *pMap)
uint32 GetAreaTriggerScriptId (uint32 triggerId) const
uint32 GetEventIdScriptId (uint32 eventId) const
Private Types
typedef std::vector< Script * > SDScriptVec
typedef std::vector< std::string > ScriptNameMap
typedef std::unordered_map< uint32, uint32 > AreaTriggerScriptMap
typedef std::unordered_map< uint32, uint32 > EventIdScriptMap
Private Attributes
int m_scriptCount
SDScriptVec m_scripts
AreaTriggerScriptMap m_AreaTriggerScripts
EventIdScriptMap m_EventIdScripts
ScriptNameMap m_scriptNames
Detailed Description
Definition at line 133 of file ScriptDevAIMgr.h.
Member Typedef Documentation
AreaTriggerScriptMap
typedef std::unordered_map<uint32, uint32> ScriptDevAIMgr::AreaTriggerScriptMap private
Definition at line 185 of file ScriptDevAIMgr.h.
EventIdScriptMap
typedef std::unordered_map<uint32, uint32> ScriptDevAIMgr::EventIdScriptMap private
Definition at line 186 of file ScriptDevAIMgr.h.
ScriptNameMap
typedef std::vector<std::string> ScriptDevAIMgr::ScriptNameMap private
Definition at line 184 of file ScriptDevAIMgr.h.
SDScriptVec
typedef std::vector<Script*> ScriptDevAIMgr::SDScriptVec private
Definition at line 183 of file ScriptDevAIMgr.h.
Constructor & Destructor Documentation
ScriptDevAIMgr()
ScriptDevAIMgr::ScriptDevAIMgr () inline
Definition at line 136 of file ScriptDevAIMgr.h.
~ScriptDevAIMgr()
ScriptDevAIMgr::~ScriptDevAIMgr ()
Definition at line 472 of file ScriptDevAIMgr.cpp.
References m_scriptCount, m_scripts, and setScriptLibraryErrorFile().
Member Function Documentation
AddScript()
void ScriptDevAIMgr::AddScript (uint32 id, Script * script)
Definition at line 485 of file ScriptDevAIMgr.cpp.
References m_scriptCount, and m_scripts.
CheckScriptNames()
void ScriptDevAIMgr::CheckScriptNames ()
Definition at line 579 of file ScriptDevAIMgr.cpp.
References GetScriptIdsCount(), GetScriptName(), m_scriptCount, m_scripts, outstring_log(), and script_error_log().
CreateInstanceData()
InstanceData * ScriptDevAIMgr::CreateInstanceData (Map * pMap)
Definition at line 462 of file ScriptDevAIMgr.cpp.
References Script::GetInstanceData, GetScript(), and Map::GetScriptId().
GetAreaTriggerScriptId()
uint32 ScriptDevAIMgr::GetAreaTriggerScriptId (uint32 triggerId) const
Definition at line 696 of file ScriptDevAIMgr.cpp.
References m_AreaTriggerScripts.
Referenced by OnAreaTrigger().
GetCreatureAI()
UnitAI * ScriptDevAIMgr::GetCreatureAI (Creature * pCreature) const
Definition at line 362 of file ScriptDevAIMgr.cpp.
References Script::GetAI, GetScript(), and Creature::GetScriptId().
GetDialogStatus() [1/2]
uint32 ScriptDevAIMgr::GetDialogStatus (const Player * pPlayer, const Creature * pCreature) const
Definition at line 237 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), DIALOG_STATUS_UNDEFINED, Player::GetPlayerMenu(), GetScript(), Creature::GetScriptId(), and Script::pDialogStatusNPC.
GetDialogStatus() [2/2]
uint32 ScriptDevAIMgr::GetDialogStatus (const Player * pPlayer, const GameObject * pGo) const
Definition at line 249 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), DIALOG_STATUS_UNDEFINED, GameObject::GetGOInfo(), Player::GetPlayerMenu(), GetScript(), Script::pDialogStatusGO, and GameObjectInfo::ScriptId.
GetEventIdScriptId()
uint32 ScriptDevAIMgr::GetEventIdScriptId (uint32 eventId) const
Definition at line 705 of file ScriptDevAIMgr.cpp.
References m_EventIdScripts.
Referenced by OnProcessEvent().
GetGameObjectAI()
GameObjectAI * ScriptDevAIMgr::GetGameObjectAI (GameObject * gameobject) const
Definition at line 372 of file ScriptDevAIMgr.cpp.
References Script::GetGameObjectAI, GetScript(), and GameObject::GetScriptId().
GetScript()
Script * ScriptDevAIMgr::GetScript (uint32 id) const
Definition at line 494 of file ScriptDevAIMgr.cpp.
References m_scripts.
Referenced by CreateInstanceData(), GetCreatureAI(), GetDialogStatus(), GetGameObjectAI(), OnAreaTrigger(), OnAuraDummy(), OnEffectDummy(), OnEffectScriptEffect(), OnGameObjectUse(), OnGossipHello(), OnGossipSelect(), OnItemLoot(), OnItemUse(), OnProcessEvent(), OnQuestAccept(), OnQuestRewarded(), and OnTrapSearch().
GetScriptId()
uint32 ScriptDevAIMgr::GetScriptId (const char * name) const
Definition at line 590 of file ScriptDevAIMgr.cpp.
References m_scriptNames.
Referenced by LoadAreaTriggerScripts(), and LoadEventIdScripts().
GetScriptIdsCount()
uint32 ScriptDevAIMgr::GetScriptIdsCount () const inline
Definition at line 173 of file ScriptDevAIMgr.h.
References m_scriptNames.
Referenced by CheckScriptNames(), and Initialize().
GetScriptName()
const char* ScriptDevAIMgr::GetScriptName (uint32 id) const inline
Definition at line 171 of file ScriptDevAIMgr.h.
References m_scriptNames.
Referenced by CheckScriptNames().
Initialize()
void ScriptDevAIMgr::Initialize ()
Definition at line 501 of file ScriptDevAIMgr.cpp.
References AddScripts(), FillSpellSummary(), GetScriptIdsCount(), LoadDatabase(), m_scripts, outstring_log(), and BarGoLink::step().
LoadAreaTriggerScripts()
void ScriptDevAIMgr::LoadAreaTriggerScripts ()
Definition at line 605 of file ScriptDevAIMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), GetScriptId(), Field::GetString(), Field::GetUInt32(), m_AreaTriggerScripts, QueryResult::NextRow(), Database::Query(), sAreaTriggerStore, sLog, BarGoLink::step(), and WorldDatabase.
LoadEventIdScripts()
void ScriptDevAIMgr::LoadEventIdScripts ()
Definition at line 650 of file ScriptDevAIMgr.cpp.
References ScriptMgr::CollectPossibleEventIds(), QueryResult::Fetch(), QueryResult::GetRowCount(), GetScriptId(), Field::GetString(), Field::GetUInt32(), m_EventIdScripts, QueryResult::NextRow(), Database::Query(), sLog, SPELL_EFFECT_SEND_EVENT, BarGoLink::step(), and WorldDatabase.
LoadScriptNames()
void ScriptDevAIMgr::LoadScriptNames ()
Definition at line 534 of file ScriptDevAIMgr.cpp.
References QueryResult::GetRowCount(), m_scriptNames, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
OnAreaTrigger()
bool ScriptDevAIMgr::OnAreaTrigger (Player * pPlayer, AreaTriggerEntry const * atEntry)
Definition at line 341 of file ScriptDevAIMgr.cpp.
References GetAreaTriggerScriptId(), GetScript(), AreaTriggerEntry::id, and Script::pAreaTrigger.
OnAuraDummy()
bool ScriptDevAIMgr::OnAuraDummy (Aura const * pAura, bool bApply)
Definition at line 442 of file ScriptDevAIMgr.cpp.
References GetScript(), Aura::GetTarget(), and Script::pEffectAuraDummy.
OnEffectDummy() [1/3]
bool ScriptDevAIMgr::OnEffectDummy (Unit * pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature * pTarget, ObjectGuid originalCasterGuid)
Definition at line 402 of file ScriptDevAIMgr.cpp.
References GetScript(), Creature::GetScriptId(), and Script::pEffectDummyNPC.
OnEffectDummy() [2/3]
bool ScriptDevAIMgr::OnEffectDummy (Unit * pCaster, uint32 spellId, SpellEffectIndex effIndex, GameObject * pTarget, ObjectGuid originalCasterGuid)
Definition at line 412 of file ScriptDevAIMgr.cpp.
References GameObject::GetGOInfo(), GetScript(), Script::pEffectDummyGO, and GameObjectInfo::ScriptId.
OnEffectDummy() [3/3]
bool ScriptDevAIMgr::OnEffectDummy (Unit * pCaster, uint32 spellId, SpellEffectIndex effIndex, Item * pTarget, ObjectGuid originalCasterGuid)
Definition at line 422 of file ScriptDevAIMgr.cpp.
References Item::GetProto(), GetScript(), Script::pEffectDummyItem, and ItemPrototype::ScriptId.
OnEffectScriptEffect()
bool ScriptDevAIMgr::OnEffectScriptEffect (Unit * pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature * pTarget, ObjectGuid originalCasterGuid)
Definition at line 432 of file ScriptDevAIMgr.cpp.
References GetScript(), Creature::GetScriptId(), and Script::pEffectScriptEffectNPC.
OnGameObjectUse()
bool ScriptDevAIMgr::OnGameObjectUse (Player * pPlayer, GameObject * pGo)
Definition at line 297 of file ScriptDevAIMgr.cpp.
References GameObject::GetGOInfo(), GetScript(), Script::pGOUse, and GameObjectInfo::ScriptId.
OnGossipHello() [1/2]
bool ScriptDevAIMgr::OnGossipHello (Player * pPlayer, Creature * pCreature)
Definition at line 163 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), Player::GetPlayerMenu(), GetScript(), Creature::GetScriptId(), and Script::pGossipHello.
OnGossipHello() [2/2]
bool ScriptDevAIMgr::OnGossipHello (Player * pPlayer, GameObject * pGo)
Definition at line 175 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), GameObject::GetGOInfo(), Player::GetPlayerMenu(), GetScript(), Script::pGossipHelloGO, and GameObjectInfo::ScriptId.
OnGossipSelect() [1/2]
bool ScriptDevAIMgr::OnGossipSelect (Player * pPlayer, Creature * pCreature, uint32 uiSender, uint32 uiAction, const char * code)
Definition at line 187 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), debug_log(), Player::GetPlayerMenu(), GetScript(), Creature::GetScriptId(), Script::pGossipSelect, and Script::pGossipSelectWithCode.
OnGossipSelect() [2/2]
bool ScriptDevAIMgr::OnGossipSelect (Player * pPlayer, GameObject * pGo, uint32 uiSender, uint32 uiAction, const char * code)
Definition at line 212 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), debug_log(), GameObject::GetGOInfo(), Player::GetPlayerMenu(), GetScript(), Script::pGossipSelectGO, Script::pGossipSelectGOWithCode, and GameObjectInfo::ScriptId.
OnItemLoot()
bool ScriptDevAIMgr::OnItemLoot (Player * pPlayer, Item * pItem, bool apply)
Definition at line 392 of file ScriptDevAIMgr.cpp.
References ByteConverter::apply(), Item::GetProto(), GetScript(), Script::pItemLoot, and ItemPrototype::ScriptId.
OnItemUse()
bool ScriptDevAIMgr::OnItemUse (Player * pPlayer, Item * pItem, SpellCastTargets const & targets)
Definition at line 382 of file ScriptDevAIMgr.cpp.
References Item::GetProto(), GetScript(), Script::pItemUse, and ItemPrototype::ScriptId.
OnNpcSpellClick()
bool ScriptDevAIMgr::OnNpcSpellClick (Player * pPlayer, Creature * pClickedCreature, uint32 spellId)
Definition at line 452 of file ScriptDevAIMgr.cpp.
References Creature::GetScriptId(), m_scripts, and Script::pNpcSpellClick.
OnProcessEvent()
bool ScriptDevAIMgr::OnProcessEvent (uint32 uiEventId, Object * pSource, Object * pTarget, bool bIsStart)
Definition at line 351 of file ScriptDevAIMgr.cpp.
References GetEventIdScriptId(), GetScript(), and Script::pProcessEventId.
OnQuestAccept() [1/3]
bool ScriptDevAIMgr::OnQuestAccept (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
Definition at line 261 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), Player::GetPlayerMenu(), GetScript(), Creature::GetScriptId(), and Script::pQuestAcceptNPC.
OnQuestAccept() [2/3]
bool ScriptDevAIMgr::OnQuestAccept (Player * pPlayer, GameObject * pGo, Quest const * pQuest)
Definition at line 273 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), GameObject::GetGOInfo(), Player::GetPlayerMenu(), GetScript(), Script::pQuestAcceptGO, and GameObjectInfo::ScriptId.
OnQuestAccept() [3/3]
bool ScriptDevAIMgr::OnQuestAccept (Player * pPlayer, Item * pItem, Quest const * pQuest)
Definition at line 285 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), Player::GetPlayerMenu(), Item::GetProto(), GetScript(), Script::pQuestAcceptItem, and ItemPrototype::ScriptId.
OnQuestRewarded() [1/2]
bool ScriptDevAIMgr::OnQuestRewarded (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
Definition at line 317 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), Player::GetPlayerMenu(), GetScript(), Creature::GetScriptId(), and Script::pQuestRewardedNPC.
OnQuestRewarded() [2/2]
bool ScriptDevAIMgr::OnQuestRewarded (Player * pPlayer, GameObject * pGo, Quest const * pQuest)
Definition at line 329 of file ScriptDevAIMgr.cpp.
References PlayerMenu::ClearMenus(), GameObject::GetGOInfo(), Player::GetPlayerMenu(), GetScript(), Script::pQuestRewardedGO, and GameObjectInfo::ScriptId.
OnTrapSearch()
std::function< bool(Unit *)> * ScriptDevAIMgr::OnTrapSearch (GameObject * go)
Definition at line 307 of file ScriptDevAIMgr.cpp.
References GameObject::GetGOInfo(), GetScript(), Script::pTrapSearching, and GameObjectInfo::ScriptId.
Field Documentation
m_AreaTriggerScripts
AreaTriggerScriptMap ScriptDevAIMgr::m_AreaTriggerScripts private
Definition at line 191 of file ScriptDevAIMgr.h.
Referenced by GetAreaTriggerScriptId(), and LoadAreaTriggerScripts().
m_EventIdScripts
EventIdScriptMap ScriptDevAIMgr::m_EventIdScripts private
Definition at line 192 of file ScriptDevAIMgr.h.
Referenced by GetEventIdScriptId(), and LoadEventIdScripts().
m_scriptCount
int ScriptDevAIMgr::m_scriptCount private
Definition at line 188 of file ScriptDevAIMgr.h.
Referenced by AddScript(), CheckScriptNames(), and ~ScriptDevAIMgr().
m_scriptNames
ScriptNameMap ScriptDevAIMgr::m_scriptNames private
Definition at line 194 of file ScriptDevAIMgr.h.
Referenced by GetScriptId(), GetScriptIdsCount(), GetScriptName(), and LoadScriptNames().
m_scripts
SDScriptVec ScriptDevAIMgr::m_scripts private
Definition at line 189 of file ScriptDevAIMgr.h.
Referenced by AddScript(), CheckScriptNames(), GetScript(), Initialize(), OnNpcSpellClick(), and ~ScriptDevAIMgr().
The documentation for this class was generated from the following files:
ScriptDevAIMgr.h
ScriptDevAIMgr.cpp