CMaNGOS_WoTLK: LFGData Class Reference
LFGData Class Reference
#include <LFG.h>
Public Member Functions
LFGData ()
LfgState GetState () const
void SetState (LfgState state)
uint32 GetDungeon () const
void SetDungeon (uint32 dungeon)
std::string GetComment () const
void SetComment (std::string comment)
LfgDungeonSet & GetListedDungeonSet ()
void SetPlayerRoles (uint8 roles)
uint8 GetPlayerRoles () const
void SetCountAtJoin (uint8 count)
uint8 GetCountAtJoin () const
Private Attributes
LfgState m_state
uint32 m_dungeon
std::string m_comment
LfgDungeonSet m_listedDungeonSet
std::vector< uint8 > m_roles
uint8 m_countAtJoin
Detailed Description
Definition at line 31 of file LFG.h.
Constructor & Destructor Documentation
LFGData()
LFGData::LFGData ()
Definition at line 25 of file LFG.cpp.
Member Function Documentation
GetComment()
std::string LFGData::GetComment () const inline
Definition at line 39 of file LFG.h.
References m_comment.
GetCountAtJoin()
uint8 LFGData::GetCountAtJoin () const inline
Definition at line 46 of file LFG.h.
References m_countAtJoin.
Referenced by LFGMgr::FinishDungeon().
GetDungeon()
uint32 LFGData::GetDungeon () const inline
Definition at line 37 of file LFG.h.
References m_dungeon.
Referenced by LFGMgr::FinishDungeon(), LFGMgr::JoinLfg(), instance_blackrock_depths::OnPlayerEnter(), instance_scarlet_monastery::OnPlayerEnter(), instance_shadowfang_keep::OnPlayerEnter(), instance_slave_pens::OnPlayerEnter(), and LFGMgr::TeleportPlayer().
GetListedDungeonSet()
LfgDungeonSet& LFGData::GetListedDungeonSet () inline
Definition at line 41 of file LFG.h.
References m_listedDungeonSet.
Referenced by LFGMgr::JoinLfg(), and LFGMgr::LeaveLfg().
GetPlayerRoles()
uint8 LFGData::GetPlayerRoles () const inline
Definition at line 44 of file LFG.h.
References m_roles, and ROLE_INDEX_PLAYER.
GetState()
LfgState LFGData::GetState () const inline
Definition at line 35 of file LFG.h.
References m_state.
Referenced by LFGMgr::FinishDungeon(), WorldSession::HandleLfgSetCommentOpcode(), WorldSession::HandleLfgSetRolesOpcode(), LFGMgr::JoinLfg(), LFGMgr::LeaveLfg(), and WorldSession::LogoutPlayer().
SetComment()
void LFGData::SetComment (std::string comment) inline
Definition at line 40 of file LFG.h.
References m_comment.
Referenced by WorldSession::HandleLfgSetCommentOpcode(), and LFGMgr::JoinLfg().
SetCountAtJoin()
void LFGData::SetCountAtJoin (uint8 count) inline
Definition at line 45 of file LFG.h.
References m_countAtJoin.
SetDungeon()
void LFGData::SetDungeon (uint32 dungeon) inline
Definition at line 38 of file LFG.h.
References m_dungeon.
SetPlayerRoles()
void LFGData::SetPlayerRoles (uint8 roles) inline
Definition at line 43 of file LFG.h.
References m_roles, and ROLE_INDEX_PLAYER.
Referenced by LFGMgr::JoinLfg().
SetState()
void LFGData::SetState (LfgState state) inline
Definition at line 36 of file LFG.h.
References m_state.
Referenced by LFGMgr::FinishDungeon(), LFGMgr::JoinLfg(), and LFGMgr::LeaveLfg().
Field Documentation
m_comment
std::string LFGData::m_comment private
Definition at line 50 of file LFG.h.
Referenced by GetComment(), and SetComment().
m_countAtJoin
uint8 LFGData::m_countAtJoin private
Definition at line 53 of file LFG.h.
Referenced by GetCountAtJoin(), and SetCountAtJoin().
m_dungeon
uint32 LFGData::m_dungeon private
Definition at line 49 of file LFG.h.
Referenced by GetDungeon(), and SetDungeon().
m_listedDungeonSet
LfgDungeonSet LFGData::m_listedDungeonSet private
Definition at line 51 of file LFG.h.
Referenced by GetListedDungeonSet().
m_roles
std::vector<uint8> LFGData::m_roles private
Definition at line 52 of file LFG.h.
Referenced by GetPlayerRoles(), and SetPlayerRoles().
m_state
LfgState LFGData::m_state private
Definition at line 48 of file LFG.h.
Referenced by GetState(), and SetState().
The documentation for this class was generated from the following files:
LFG.h
LFG.cpp