CMaNGOS_WoTLK: PlayerbotWarlockAI Class Reference
PlayerbotWarlockAI Class Reference
#include <PlayerbotWarlockAI.h>
Public Member Functions
PlayerbotWarlockAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotWarlockAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
void DoNonCombatActions () override
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns CastSpell (uint32 nextAction, Unit *pTarget=nullptr)
void CheckDemon ()
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
virtual CombatManeuverReturns DispelPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Private Attributes
uint32 CURSE_OF_WEAKNESS
uint32 CURSE_OF_AGONY
uint32 CURSE_OF_EXHAUSTION
uint32 CURSE_OF_TONGUES
uint32 CURSE_OF_THE_ELEMENTS
uint32 CURSE_OF_DOOM
uint32 SHOOT
uint32 CORRUPTION
uint32 DRAIN_SOUL
uint32 DRAIN_LIFE
uint32 DRAIN_MANA
uint32 LIFE_TAP
uint32 UNSTABLE_AFFLICTION
uint32 HAUNT
uint32 SEED_OF_CORRUPTION
uint32 DARK_PACT
uint32 HOWL_OF_TERROR
uint32 FEAR
uint32 SHADOW_BOLT
uint32 IMMOLATE
uint32 INCINERATE
uint32 SEARING_PAIN
uint32 CONFLAGRATE
uint32 SOUL_FIRE
uint32 SHADOWFURY
uint32 CHAOS_BOLT
uint32 SHADOWFLAME
uint32 HELLFIRE
uint32 RAIN_OF_FIRE
uint32 SHADOWBURN
uint32 DEMON_SKIN
uint32 DEMON_ARMOR
uint32 DEMONIC_EMPOWERMENT
uint32 SHADOW_WARD
uint32 FEL_ARMOR
uint32 SOULSHATTER
uint32 SOUL_LINK
uint32 SOUL_LINK_AURA
uint32 HEALTH_FUNNEL
uint32 DETECT_INVISIBILITY
uint32 CREATE_FIRESTONE
uint32 CREATE_SOULSTONE
uint32 CREATE_HEALTHSTONE
uint32 CREATE_SPELLSTONE
uint32 SUMMON_IMP
uint32 SUMMON_VOIDWALKER
uint32 SUMMON_SUCCUBUS
uint32 SUMMON_FELHUNTER
uint32 SUMMON_FELGUARD
uint32 BLOOD_PACT
uint32 FIREBOLT
uint32 FIRE_SHIELD
uint32 ANGUISH
uint32 CLEAVE
uint32 INTERCEPT
uint32 DEVOUR_MAGIC
uint32 FEL_INTELLIGENCE
uint32 SHADOW_BITE
uint32 SPELL_LOCK
uint32 LASH_OF_PAIN
uint32 SEDUCTION
uint32 SOOTHING_KISS
uint32 CONSUME_SHADOWS
uint32 SACRIFICE
uint32 SUFFERING
uint32 TORMENT
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 m_lastDemon
uint32 m_demonOfChoice
bool m_isTempImp
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 157 of file PlayerbotWarlockAI.h.
Constructor & Destructor Documentation
PlayerbotWarlockAI()
PlayerbotWarlockAI::PlayerbotWarlockAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 22 of file PlayerbotWarlockAI.cpp.
References ARCANE_TORRENT, ARCANE_TORRENT_MANA_CLASSES, BLOOD_FURY, BLOOD_FURY_WARLOCK, BLOOD_PACT, CHAOS_BOLT, CHAOS_BOLT_1, CONFLAGRATE, CONFLAGRATE_1, CONSUME_SHADOWS, CORRUPTION, CORRUPTION_1, CREATE_FIRESTONE, CREATE_FIRESTONE_1, CREATE_HEALTHSTONE, CREATE_HEALTHSTONE_1, CREATE_SOULSTONE, CREATE_SOULSTONE_1, CREATE_SPELLSTONE, CREATE_SPELLSTONE_1, CURSE_OF_AGONY, CURSE_OF_AGONY_1, CURSE_OF_DOOM, CURSE_OF_DOOM_1, CURSE_OF_EXHAUSTION, CURSE_OF_EXHAUSTION_1, CURSE_OF_THE_ELEMENTS, CURSE_OF_THE_ELEMENTS_1, CURSE_OF_TONGUES, CURSE_OF_TONGUES_1, CURSE_OF_WEAKNESS, CURSE_OF_WEAKNESS_1, DARK_PACT, DARK_PACT_1, DEMON_ARMOR, DEMON_ARMOR_1, DEMON_IMP, DEMON_SKIN, DEMON_SKIN_1, DEMONIC_EMPOWERMENT, DEMONIC_EMPOWERMENT_1, DETECT_INVISIBILITY, DETECT_INVISIBILITY_1, DRAIN_LIFE, DRAIN_LIFE_1, DRAIN_MANA, DRAIN_MANA_1, DRAIN_SOUL, DRAIN_SOUL_1, ESCAPE_ARTIST, ESCAPE_ARTIST_ALL, EVERY_MAN_FOR_HIMSELF, EVERY_MAN_FOR_HIMSELF_ALL, FEAR, FEAR_1, FEL_ARMOR, FEL_ARMOR_1, FEL_INTELLIGENCE, HAUNT, HAUNT_1, HEALTH_FUNNEL, HEALTH_FUNNEL_1, HELLFIRE, HELLFIRE_1, HOWL_OF_TERROR, HOWL_OF_TERROR_1, IMMOLATE, IMMOLATE_1, INCINERATE, INCINERATE_1, PlayerbotAI::initSpell(), LIFE_TAP, LIFE_TAP_1, PlayerbotClassAI::m_ai, m_demonOfChoice, m_isTempImp, m_lastDemon, RAIN_OF_FIRE, RAIN_OF_FIRE_1, PlayerbotClassAI::RECENTLY_BANDAGED, SEARING_PAIN, SEARING_PAIN_1, SEED_OF_CORRUPTION, SEED_OF_CORRUPTION_1, SHADOW_BOLT, SHADOW_BOLT_1, SHADOW_WARD, SHADOW_WARD_1, SHADOWBURN, SHADOWBURN_1, SHADOWFLAME, SHADOWFLAME_1, SHADOWFURY, SHADOWFURY_1, SHOOT, SHOOT_3, SOUL_FIRE, SOUL_FIRE_1, SOUL_LINK, SOUL_LINK_1, SOUL_LINK_AURA, SOULSHATTER, SOULSHATTER_1, SUMMON_FELGUARD, SUMMON_FELGUARD_1, SUMMON_FELHUNTER, SUMMON_FELHUNTER_1, SUMMON_IMP, SUMMON_IMP_1, SUMMON_SUCCUBUS, SUMMON_SUCCUBUS_1, SUMMON_VOIDWALKER, SUMMON_VOIDWALKER_1, UNSTABLE_AFFLICTION, UNSTABLE_AFFLICTION_1, WILL_OF_THE_FORSAKEN, and WILL_OF_THE_FORSAKEN_ALL.
~PlayerbotWarlockAI()
PlayerbotWarlockAI::~PlayerbotWarlockAI () virtual
Definition at line 98 of file PlayerbotWarlockAI.cpp.
Member Function Documentation
CastSpell()
CombatManeuverReturns PlayerbotWarlockAI::CastSpell (uint32 nextAction, Unit * pTarget = nullptr) inline private
Definition at line 179 of file PlayerbotWarlockAI.h.
References PlayerbotClassAI::CastSpellWand(), and SHOOT.
Referenced by DoNextCombatManeuverPVE().
CheckDemon()
void PlayerbotWarlockAI::CheckDemon () private
Definition at line 310 of file PlayerbotWarlockAI.cpp.
References PlayerbotAI::CastSpell(), DEMON_FELGUARD, DEMON_FELHUNTER, DEMON_IMP, DEMON_SUCCUBUS, Object::GetEntry(), Player::GetItemCount(), Unit::GetPet(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, m_demonOfChoice, m_isTempImp, SOUL_SHARD, SPELL_CAST_OK, SUMMON_FELGUARD, SUMMON_FELHUNTER, SUMMON_IMP, SUMMON_SUCCUBUS, WARLOCK_SPEC_AFFLICTION, WARLOCK_SPEC_DEMONOLOGY, and WARLOCK_SPEC_DESTRUCTION.
Referenced by DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotWarlockAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 100 of file PlayerbotWarlockAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotWarlockAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 142 of file PlayerbotWarlockAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotWarlockAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 147 of file PlayerbotWarlockAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotWarlockAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 152 of file PlayerbotWarlockAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, RETURN_NO_ACTION_ERROR, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotWarlockAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 172 of file PlayerbotWarlockAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, Unit::CanReachWithMeleeAttack(), PlayerbotAI::CastPetSpell(), CastSpell(), CHAOS_BOLT, PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, CONFLAGRATE, CORRUPTION, CURSE_OF_AGONY, DEMON_VOIDWALKER, DEMONIC_EMPOWERMENT, DRAIN_SOUL, PlayerbotAI::FindAttacker(), PlayerbotAI::FindConsumable(), PlayerbotAI::GetCombatStyle(), Object::GetEntry(), PlayerbotAI::GetFreeBagSpace(), Unit::GetHealth(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), Player::GetItemCount(), Unit::GetMaxHealth(), Unit::GetPet(), Player::GetWeaponForAttack(), Unit::HasAura(), HAUNT, HEALTHSTONE_DISPLAYID, IMMOLATE, PlayerbotAI::In_Reach(), INCINERATE, PlayerbotAI::IsImmuneToSchool(), PlayerbotAI::IsNeutralized(), WorldObject::IsSpellReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, RANGED_ATTACK, RETURN_CONTINUE, RETURN_NO_ACTION_OK, SACRIFICE, PlayerbotAI::SetCombatStyle(), PlayerbotAI::SetIgnoreUpdateTime(), SHADOW_BOLT, SHOOT, SOUL_SHARD, SOULSHATTER, SPELL_SCHOOL_MASK_FIRE, SPELL_SCHOOL_MASK_SHADOW, UNSTABLE_AFFLICTION, PlayerbotAI::UseItem(), WARLOCK_SPEC_AFFLICTION, WARLOCK_SPEC_DEMONOLOGY, and WARLOCK_SPEC_DESTRUCTION.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotWarlockAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 300 of file PlayerbotWarlockAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), FEAR, PlayerbotAI::In_Reach(), PlayerbotClassAI::m_ai, RETURN_CONTINUE, SHADOW_BOLT, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotWarlockAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 366 of file PlayerbotWarlockAI.cpp.
References ANGUISH, ANGUISH_ICON, BLOOD_PACT, BLOOD_PACT_ICON, PlayerbotAI::CanStore(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), CheckDemon(), CLEAVE, CLEAVE_ICON, CONSUME_SHADOWS, CONSUME_SHADOWS_ICON, CREATE_FIRESTONE, CREATE_HEALTHSTONE, CREATE_SOULSTONE, CREATE_SPELLSTONE, DARK_PACT, DEMON_ARMOR, DEMON_FELGUARD, DEMON_FELHUNTER, DEMON_IMP, DEMON_SKIN, DEMON_SUCCUBUS, DEMON_VOIDWALKER, Player::DestroyItemCount(), DEVOUR_MAGIC, DEVOUR_MAGIC_ICON, PlayerbotClassAI::EatDrinkBandage(), EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, FEL_ARMOR, FEL_INTELLIGENCE, FEL_INTELLIGENCE_ICON, PlayerbotAI::FindConsumable(), FIRE_SHIELD, FIRE_SHIELD_ICON, FIREBOLT, FIREBOLT_ICON, FIRESTONE, FIRESTONE_DISPLAYID, Item::GetEnchantmentId(), Object::GetEntry(), PlayerbotAI::GetFreeBagSpace(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), Player::GetItemByPos(), Player::GetItemCount(), PlayerbotAI::GetManaPercent(), Unit::GetMaxPower(), Unit::GetPet(), Unit::GetPower(), Item::GetProto(), GREATER_FIRESTONE, GREATER_SPELLSTONE, Unit::HasAura(), HEALTHSTONE_DISPLAYID, PlayerbotAI::initPetSpell(), INTERCEPT, INTERCEPT_ICON, INVENTORY_SLOT_BAG_0, WorldObject::IsSpellReady(), LASH_OF_PAIN, LASH_OF_PAIN_ICON, LESSER_FIRESTONE, LIFE_TAP, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, m_lastDemon, PlayerbotClassAI::m_master, MAJOR_FIRESTONE, MAJOR_SPELLSTONE, MAX_SHARD_COUNT, POWER_MANA, SACRIFICE, SACRIFICE_ICON, SEDUCTION, SEDUCTION_ICON, PlayerbotAI::SelfBuff(), SHADOW_BITE, SHADOW_BITE_ICON, SOOTHING_KISS, SOOTHING_KISS_ICON, SOUL_LINK, SOUL_LINK_AURA, SOUL_SHARD, SOULSTONE_DISPLAYID, SPELL_CAST_OK, SPELL_LOCK, SPELL_LOCK_ICON, _Spell::SpellId, ItemPrototype::Spells, SPELLSTONE, SPELLSTONE_DISPLAYID, SUFFERING, SUFFERING_ICON, TEMP_ENCHANTMENT_SLOT, TORMENT, TORMENT_ICON, and PlayerbotAI::UseItem().
Field Documentation
ANGUISH
uint32 PlayerbotWarlockAI::ANGUISH private
Definition at line 247 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
ARCANE_TORRENT
uint32 PlayerbotWarlockAI::ARCANE_TORRENT private
Definition at line 263 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
BERSERKING
uint32 PlayerbotWarlockAI::BERSERKING private
Definition at line 271 of file PlayerbotWarlockAI.h.
BLOOD_FURY
uint32 PlayerbotWarlockAI::BLOOD_FURY private
Definition at line 269 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
BLOOD_PACT
uint32 PlayerbotWarlockAI::BLOOD_PACT private
Definition at line 244 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CHAOS_BOLT
uint32 PlayerbotWarlockAI::CHAOS_BOLT private
Definition at line 214 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
CLEAVE
uint32 PlayerbotWarlockAI::CLEAVE private
Definition at line 248 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
CONFLAGRATE
uint32 PlayerbotWarlockAI::CONFLAGRATE private
Definition at line 211 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
CONSUME_SHADOWS
uint32 PlayerbotWarlockAI::CONSUME_SHADOWS private
Definition at line 257 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CORRUPTION
uint32 PlayerbotWarlockAI::CORRUPTION private
Definition at line 194 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
CREATE_FIRESTONE
uint32 PlayerbotWarlockAI::CREATE_FIRESTONE private
Definition at line 231 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CREATE_HEALTHSTONE
uint32 PlayerbotWarlockAI::CREATE_HEALTHSTONE private
Definition at line 233 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CREATE_SOULSTONE
uint32 PlayerbotWarlockAI::CREATE_SOULSTONE private
Definition at line 232 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CREATE_SPELLSTONE
uint32 PlayerbotWarlockAI::CREATE_SPELLSTONE private
Definition at line 234 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
CURSE_OF_AGONY
uint32 PlayerbotWarlockAI::CURSE_OF_AGONY private
Definition at line 185 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
CURSE_OF_DOOM
uint32 PlayerbotWarlockAI::CURSE_OF_DOOM private
Definition at line 189 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
CURSE_OF_EXHAUSTION
uint32 PlayerbotWarlockAI::CURSE_OF_EXHAUSTION private
Definition at line 186 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
CURSE_OF_THE_ELEMENTS
uint32 PlayerbotWarlockAI::CURSE_OF_THE_ELEMENTS private
Definition at line 188 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
CURSE_OF_TONGUES
uint32 PlayerbotWarlockAI::CURSE_OF_TONGUES private
Definition at line 187 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
CURSE_OF_WEAKNESS
uint32 PlayerbotWarlockAI::CURSE_OF_WEAKNESS private
Definition at line 184 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
DARK_PACT
uint32 PlayerbotWarlockAI::DARK_PACT private
Definition at line 202 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
DEMON_ARMOR
uint32 PlayerbotWarlockAI::DEMON_ARMOR private
Definition at line 222 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
DEMON_SKIN
uint32 PlayerbotWarlockAI::DEMON_SKIN private
Definition at line 221 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
DEMONIC_EMPOWERMENT
uint32 PlayerbotWarlockAI::DEMONIC_EMPOWERMENT private
Definition at line 223 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
DETECT_INVISIBILITY
uint32 PlayerbotWarlockAI::DETECT_INVISIBILITY private
Definition at line 230 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
DEVOUR_MAGIC
uint32 PlayerbotWarlockAI::DEVOUR_MAGIC private
Definition at line 250 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
DRAIN_LIFE
uint32 PlayerbotWarlockAI::DRAIN_LIFE private
Definition at line 196 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
DRAIN_MANA
uint32 PlayerbotWarlockAI::DRAIN_MANA private
Definition at line 197 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
DRAIN_SOUL
uint32 PlayerbotWarlockAI::DRAIN_SOUL private
Definition at line 195 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
ESCAPE_ARTIST
uint32 PlayerbotWarlockAI::ESCAPE_ARTIST private
Definition at line 266 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotWarlockAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 267 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
FEAR
uint32 PlayerbotWarlockAI::FEAR private
Definition at line 204 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVP(), and PlayerbotWarlockAI().
FEL_ARMOR
uint32 PlayerbotWarlockAI::FEL_ARMOR private
Definition at line 225 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
FEL_INTELLIGENCE
uint32 PlayerbotWarlockAI::FEL_INTELLIGENCE private
Definition at line 251 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
FIRE_SHIELD
uint32 PlayerbotWarlockAI::FIRE_SHIELD private
Definition at line 246 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
FIREBOLT
uint32 PlayerbotWarlockAI::FIREBOLT private
Definition at line 245 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
GIFT_OF_THE_NAARU
uint32 PlayerbotWarlockAI::GIFT_OF_THE_NAARU private
Definition at line 264 of file PlayerbotWarlockAI.h.
HAUNT
uint32 PlayerbotWarlockAI::HAUNT private
Definition at line 200 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
HEALTH_FUNNEL
uint32 PlayerbotWarlockAI::HEALTH_FUNNEL private
Definition at line 229 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
HELLFIRE
uint32 PlayerbotWarlockAI::HELLFIRE private
Definition at line 216 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
HOWL_OF_TERROR
uint32 PlayerbotWarlockAI::HOWL_OF_TERROR private
Definition at line 203 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
IMMOLATE
uint32 PlayerbotWarlockAI::IMMOLATE private
Definition at line 208 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
INCINERATE
uint32 PlayerbotWarlockAI::INCINERATE private
Definition at line 209 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
INTERCEPT
uint32 PlayerbotWarlockAI::INTERCEPT private
Definition at line 249 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
LASH_OF_PAIN
uint32 PlayerbotWarlockAI::LASH_OF_PAIN private
Definition at line 254 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
LIFE_TAP
uint32 PlayerbotWarlockAI::LIFE_TAP private
Definition at line 198 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
m_demonOfChoice
uint32 PlayerbotWarlockAI::m_demonOfChoice private
Definition at line 275 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
m_isTempImp
bool PlayerbotWarlockAI::m_isTempImp private
Definition at line 276 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
m_lastDemon
uint32 PlayerbotWarlockAI::m_lastDemon private
Definition at line 274 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
RAIN_OF_FIRE
uint32 PlayerbotWarlockAI::RAIN_OF_FIRE private
Definition at line 217 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SACRIFICE
uint32 PlayerbotWarlockAI::SACRIFICE private
Definition at line 258 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
SEARING_PAIN
uint32 PlayerbotWarlockAI::SEARING_PAIN private
Definition at line 210 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SEDUCTION
uint32 PlayerbotWarlockAI::SEDUCTION private
Definition at line 255 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
SEED_OF_CORRUPTION
uint32 PlayerbotWarlockAI::SEED_OF_CORRUPTION private
Definition at line 201 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SHADOW_BITE
uint32 PlayerbotWarlockAI::SHADOW_BITE private
Definition at line 252 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
SHADOW_BOLT
uint32 PlayerbotWarlockAI::SHADOW_BOLT private
Definition at line 207 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotWarlockAI().
SHADOW_WARD
uint32 PlayerbotWarlockAI::SHADOW_WARD private
Definition at line 224 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SHADOWBURN
uint32 PlayerbotWarlockAI::SHADOWBURN private
Definition at line 218 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SHADOWFLAME
uint32 PlayerbotWarlockAI::SHADOWFLAME private
Definition at line 215 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SHADOWFURY
uint32 PlayerbotWarlockAI::SHADOWFURY private
Definition at line 213 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SHADOWMELD
uint32 PlayerbotWarlockAI::SHADOWMELD private
Definition at line 268 of file PlayerbotWarlockAI.h.
SHOOT
uint32 PlayerbotWarlockAI::SHOOT private
Definition at line 191 of file PlayerbotWarlockAI.h.
Referenced by CastSpell(), DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
SOOTHING_KISS
uint32 PlayerbotWarlockAI::SOOTHING_KISS private
Definition at line 256 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
SOUL_FIRE
uint32 PlayerbotWarlockAI::SOUL_FIRE private
Definition at line 212 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
SOUL_LINK
uint32 PlayerbotWarlockAI::SOUL_LINK private
Definition at line 227 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
SOUL_LINK_AURA
uint32 PlayerbotWarlockAI::SOUL_LINK_AURA private
Definition at line 228 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions(), and PlayerbotWarlockAI().
SOULSHATTER
uint32 PlayerbotWarlockAI::SOULSHATTER private
Definition at line 226 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
SPELL_LOCK
uint32 PlayerbotWarlockAI::SPELL_LOCK private
Definition at line 253 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
STONEFORM
uint32 PlayerbotWarlockAI::STONEFORM private
Definition at line 265 of file PlayerbotWarlockAI.h.
SUFFERING
uint32 PlayerbotWarlockAI::SUFFERING private
Definition at line 259 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
SUMMON_FELGUARD
uint32 PlayerbotWarlockAI::SUMMON_FELGUARD private
Definition at line 241 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
SUMMON_FELHUNTER
uint32 PlayerbotWarlockAI::SUMMON_FELHUNTER private
Definition at line 240 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
SUMMON_IMP
uint32 PlayerbotWarlockAI::SUMMON_IMP private
Definition at line 237 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
SUMMON_SUCCUBUS
uint32 PlayerbotWarlockAI::SUMMON_SUCCUBUS private
Definition at line 239 of file PlayerbotWarlockAI.h.
Referenced by CheckDemon(), and PlayerbotWarlockAI().
SUMMON_VOIDWALKER
uint32 PlayerbotWarlockAI::SUMMON_VOIDWALKER private
Definition at line 238 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
TORMENT
uint32 PlayerbotWarlockAI::TORMENT private
Definition at line 260 of file PlayerbotWarlockAI.h.
Referenced by DoNonCombatActions().
UNSTABLE_AFFLICTION
uint32 PlayerbotWarlockAI::UNSTABLE_AFFLICTION private
Definition at line 199 of file PlayerbotWarlockAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotWarlockAI().
WAR_STOMP
uint32 PlayerbotWarlockAI::WAR_STOMP private
Definition at line 270 of file PlayerbotWarlockAI.h.
WILL_OF_THE_FORSAKEN
uint32 PlayerbotWarlockAI::WILL_OF_THE_FORSAKEN private
Definition at line 272 of file PlayerbotWarlockAI.h.
Referenced by PlayerbotWarlockAI().
The documentation for this class was generated from the following files:
PlayerbotWarlockAI.h
PlayerbotWarlockAI.cpp