CMaNGOS_WoTLK: ViewPoint Class Reference
ViewPoint Class Reference
Object-observer, notifies farsight object state to cameras that attached to it.
#include <Camera.h>
Public Member Functions
ViewPoint ()
~ViewPoint ()
bool hasViewers () const
void Event_AddedToWorld (GridType *grid)
void Event_RemovedFromWorld ()
void Event_GridChanged (GridType *grid)
void Event_ViewPointVisibilityChanged ()
void Call_UpdateVisibilityForOwner ()
Private Types
typedef std::list< Camera * > CameraList
Private Member Functions
void Attach (Camera *c)
void Detach (Camera *c)
void CameraCall (void(Camera::*handler)())
Private Attributes
CameraList m_cameras
GridType * m_grid
Friends
class Camera
Detailed Description
Object-observer, notifies farsight object state to cameras that attached to it.
Definition at line 80 of file Camera.h.
Member Typedef Documentation
CameraList
typedef std::list<Camera*> ViewPoint::CameraList private
Definition at line 84 of file Camera.h.
Constructor & Destructor Documentation
ViewPoint()
ViewPoint::ViewPoint () inline
Definition at line 106 of file Camera.h.
~ViewPoint()
ViewPoint::~ViewPoint ()
Definition at line 155 of file Camera.cpp.
References m_cameras, and sLog.
Member Function Documentation
Attach()
void ViewPoint::Attach (Camera * c) inline private
Definition at line 89 of file Camera.h.
References m_cameras.
Referenced by Camera::Camera(), and Camera::SetView().
Call_UpdateVisibilityForOwner()
void ViewPoint::Call_UpdateVisibilityForOwner () inline
Definition at line 135 of file Camera.h.
References CameraCall(), and Camera::UpdateVisibilityForOwner().
Referenced by Unit::OnRelocated(), WorldObject::UpdateVisibilityAndView(), and Unit::UpdateVisibilityAndView().
CameraCall()
void ViewPoint::CameraCall (void(Camera::*)() handler) inline private
Definition at line 92 of file Camera.h.
References m_cameras.
Referenced by Call_UpdateVisibilityForOwner(), Event_AddedToWorld(), Event_GridChanged(), Event_RemovedFromWorld(), and Event_ViewPointVisibilityChanged().
Detach()
void ViewPoint::Detach (Camera * c) inline private
Definition at line 90 of file Camera.h.
References m_cameras.
Referenced by Camera::SetView(), and Camera::~Camera().
Event_AddedToWorld()
void ViewPoint::Event_AddedToWorld (GridType * grid) inline
Definition at line 112 of file Camera.h.
References CameraCall(), Camera::Event_AddedToWorld(), and m_grid.
Referenced by Map::Add(), and Map::CreatePlayerOnClient().
Event_GridChanged()
void ViewPoint::Event_GridChanged (GridType * grid) inline
Definition at line 124 of file Camera.h.
References CameraCall(), Camera::Event_Moved(), and m_grid.
Referenced by Map::CreatureCellRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), and Map::PlayerRelocation().
Event_RemovedFromWorld()
void ViewPoint::Event_RemovedFromWorld () inline
Definition at line 118 of file Camera.h.
References CameraCall(), Camera::Event_RemovedFromWorld(), and m_grid.
Referenced by DynamicObject::RemoveFromWorld(), and Unit::RemoveFromWorld().
Event_ViewPointVisibilityChanged()
void ViewPoint::Event_ViewPointVisibilityChanged () inline
Definition at line 130 of file Camera.h.
References CameraCall(), and Camera::Event_ViewPointVisibilityChanged().
Referenced by WorldObject::UpdateVisibilityAndView(), and Unit::UpdateVisibilityAndView().
hasViewers()
bool ViewPoint::hasViewers () const inline
Definition at line 109 of file Camera.h.
References m_cameras.
Referenced by WorldObject::isActiveObject().
Friends And Related Function Documentation
Camera
friend class Camera friend
Definition at line 82 of file Camera.h.
Field Documentation
m_cameras
CameraList ViewPoint::m_cameras private
Definition at line 86 of file Camera.h.
Referenced by Attach(), CameraCall(), Detach(), hasViewers(), and ~ViewPoint().
m_grid
GridType* ViewPoint::m_grid private
Definition at line 87 of file Camera.h.
Referenced by Camera::Event_AddedToWorld(), Event_AddedToWorld(), Event_GridChanged(), Camera::Event_Moved(), Event_RemovedFromWorld(), and Camera::UpdateForCurrentViewPoint().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp