CMaNGOS_WoTLK: instance_steam_vault Class Reference
instance_steam_vault Class Reference
#include <steam_vault.h>
Public Member Functions
instance_steam_vault (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidList m_lNagaDistillerGuidList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 26 of file steam_vault.h.
Constructor & Destructor Documentation
instance_steam_vault()
instance_steam_vault::instance_steam_vault (Map * pMap)
Definition at line 48 of file steam_vault.cpp.
References Initialize().
Member Function Documentation
GetData()
uint32 instance_steam_vault::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 160 of file steam_vault.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by SetData().
Initialize()
void instance_steam_vault::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 53 of file steam_vault.cpp.
References m_auiEncounter.
Referenced by instance_steam_vault().
Load()
void instance_steam_vault::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 168 of file steam_vault.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_steam_vault::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 58 of file steam_vault.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lNagaDistillerGuidList, ScriptedInstance::m_npcEntryGuidStore, NPC_KALITHRESH, NPC_NAGA_DISTILLER, and NPC_STEAMRIGGER.
OnCreatureDeath()
void instance_steam_vault::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 94 of file steam_vault.cpp.
References Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_KALITHRESH, and NPC_NAGA_DISTILLER.
OnObjectCreate()
void instance_steam_vault::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 72 of file steam_vault.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ACCESS_PANEL_HYDRO, GO_ACCESS_PANEL_MEK, GO_FLAG_NO_INTERACT, GO_MAIN_CHAMBERS_DOOR, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), SPECIAL, TYPE_HYDROMANCER_THESPIA, and TYPE_MEKGINEER_STEAMRIGGER.
Save()
const char* instance_steam_vault::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 41 of file steam_vault.h.
References m_strInstData.
SetData()
void instance_steam_vault::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 104 of file steam_vault.cpp.
References DONE, ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), GetData(), GO_ACCESS_PANEL_HYDRO, GO_ACCESS_PANEL_MEK, GO_FLAG_NO_INTERACT, GO_MAIN_CHAMBERS_DOOR, InstanceData::instance, m_auiEncounter, m_lNagaDistillerGuidList, m_strInstData, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, TYPE_HYDROMANCER_THESPIA, TYPE_MEKGINEER_STEAMRIGGER, TYPE_WARLORD_KALITHRESH, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by boss_warlord_kalithreshAI::Aggro(), boss_warlord_kalithreshAI::JustDied(), and boss_warlord_kalithreshAI::JustReachedHome().
Field Documentation
m_auiEncounter
uint32 instance_steam_vault::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 45 of file steam_vault.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_lNagaDistillerGuidList
GuidList instance_steam_vault::m_lNagaDistillerGuidList private
Definition at line 48 of file steam_vault.h.
Referenced by OnCreatureCreate(), and SetData().
m_strInstData
std::string instance_steam_vault::m_strInstData private
Definition at line 46 of file steam_vault.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
steam_vault.h
steam_vault.cpp