CMaNGOS_WoTLK: AuthSocket Class Reference
AuthSocket Class Reference
Realm Daemon
#include <AuthSocket.h>
Public Member Functions
AuthSocket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
Constructor - set the N and g values for SRP6.
bool Open () override
void SendProof (Sha1Hash sha)
void LoadRealmlist (ByteBuffer &pkt, uint32 acctid, uint8 accountSecurityLevel=0)
int32 generateToken (char const *b32key)
uint8 getEligibleRealmCount (uint8 accountSecurityLevel)
bool VerifyVersion (uint8 const *a, int32 aLength, uint8 const *versionProof, bool isReconnect)
bool _HandleLogonChallenge ()
Logon Challenge command handler.
bool _HandleLogonProof ()
Logon Proof command handler.
bool _HandleReconnectChallenge ()
Reconnect Challenge command handler.
bool _HandleReconnectProof ()
Reconnect Proof command handler.
bool _HandleRealmList ()
Realm List command handler
bool _HandleXferResume ()
Resume patch transfer.
bool _HandleXferCancel ()
Cancel patch transfer.
bool _HandleXferAccept ()
Accept patch transfer.
Public Member Functions inherited from MaNGOS::Socket
Socket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
virtual ~Socket ()=default
void Close ()
bool IsClosed () const
virtual bool Deletable () const
bool Read (char *buffer, int length)
void ReadSkip (int length)
void Write (const char *buffer, int length)
void Write (const char *header, int headerSize, const char *content, int contentSize)
boost::asio::ip::tcp::socket & GetAsioSocket ()
const std::string & GetRemoteEndpoint () const
const std::string & GetRemoteAddress () const
template<typename T >
std::shared_ptr< T > shared ()
boost::asio::ip::address GetRemoteIpAddress () const
uint16 GetRemotePort () const
Static Public Attributes
static const int s_BYTE_SIZE = 32
Private Types
enum eStatus {
STATUS_CHALLENGE , STATUS_LOGON_PROOF , STATUS_RECON_PROOF , STATUS_PATCH ,
STATUS_AUTHED , STATUS_CLOSED
}
Private Member Functions
virtual bool ProcessIncomingData () override
Read the packet from the client.
Private Attributes
SRP6 srp
BigNumber _reconnectProof
eStatus _status
std::string _login
std::string _safelogin
std::string _token
std::string m_os
std::string m_platform
std::string m_locale
std::string _safelocale
uint16 _build
AccountTypes _accountSecurityLevel
boost::asio::deadline_timer m_timeoutTimer
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Socket
const uint8 * InPeak () const
int ReadLengthRemaining () const
void ForceFlushOut ()
Protected Attributes inherited from MaNGOS::Socket
const std::string m_address
const std::string m_remoteEndpoint
boost::asio::ip::address m_remoteAddress
uint16 m_remotePort
Detailed Description
Definition at line 40 of file AuthSocket.h.
Member Enumeration Documentation
eStatus
enum AuthSocket::eStatus private
Enumerator
STATUS_CHALLENGE
STATUS_LOGON_PROOF
STATUS_RECON_PROOF
STATUS_PATCH
STATUS_AUTHED
STATUS_CLOSED
Definition at line 68 of file AuthSocket.h.
Constructor & Destructor Documentation
AuthSocket()
AuthSocket::AuthSocket (boost::asio::io_service & service, std::function< void(Socket *)> closeHandler)
Constructor - set the N and g values for SRP6.
Definition at line 181 of file AuthSocket.cpp.
Member Function Documentation
_HandleLogonChallenge()
bool AuthSocket::_HandleLogonChallenge ()
Logon Challenge command handler.
Read the first 4 bytes (header) to get the length of the remaining of the packet
Session is closed unless overriden
Read the remaining of the packet
Normalize account name
Verify that this IP is not in the ip_banned table
Get the account details from the account table
If the IP is 'locked', check that the player comes indeed from the correct IP address
If the account is banned, reject the logon attempt
Fill the response packet with the result
All good, await client's proof
Definition at line 308 of file AuthSocket.cpp.
References _accountSecurityLevel, _build, _login, _safelocale, _safelogin, _status, _token, ByteBuffer::append(), BigNumber::AsByteArray(), AUTH_LOGON_FAILED_BANNED, AUTH_LOGON_FAILED_FAIL_NOACCESS, AUTH_LOGON_FAILED_SUSPENDED, AUTH_LOGON_FAILED_UNKNOWN_ACCOUNT, AUTH_LOGON_SUCCESS, BASIC_LOG, AUTH_LOGON_CHALLENGE_C::build, SRP6::CalculateHostPublicEphemeral(), CMD_AUTH_LOGON_CHALLENGE, ByteBuffer::contents(), AUTH_LOGON_CHALLENGE_C::country, DEBUG_LOG, EndianConvert(), Database::escape_string(), QueryResult::Fetch(), AUTH_LOGON_CHALLENGE_C::gamename, Field::GetCppString(), SRP6::GetGeneratorModulo(), SRP6::GetHostPublicEphemeral(), SRP6::GetPrime(), Field::GetString(), Field::GetUInt8(), AUTH_LOGON_CHALLENGE_C::I, AUTH_LOGON_CHALLENGE_C::I_len, AUTH_LOGON_CHALLENGE_C::ip, LoginDatabase, MaNGOS::Socket::m_address, m_locale, m_os, m_platform, AUTH_LOGON_CHALLENGE_C::os, AUTH_LOGON_CHALLENGE_C::platform, Database::PQuery(), MaNGOS::Socket::Read(), MaNGOS::Socket::ReadLengthRemaining(), SEC_ADMINISTRATOR, SECURITY_FLAG_AUTHENTICATOR, SECURITY_FLAG_PIN, SECURITY_FLAG_UNK, BigNumber::SetHexStr(), SRP6::SetSalt(), SRP6::SetVerifier(), AUTH_LOGON_CHALLENGE_C::size, ByteBuffer::size(), srp, STATUS_CLOSED, STATUS_LOGON_PROOF, AUTH_LOGON_CHALLENGE_C::timezone_bias, VersionChallenge, and MaNGOS::Socket::Write().
Referenced by ProcessIncomingData().
_HandleLogonProof()
bool AuthSocket::_HandleLogonProof ()
Logon Proof command handler.
Read the packet
Session is closed unless overriden
If the client has no valid version
Continue the SRP6 calculation based on data received from the client
Check if SRP6 results match (password is correct), else send an error
Update the sessionkey, current ip and login time and reset number of failed logins in the account table for this account
Finish SRP6 and send the final result to the client
Set _status to authed!
Definition at line 515 of file AuthSocket.cpp.
References _build, _login, _safelocale, _safelogin, _status, _token, BigNumber::AsHexStr(), AUTH_LOGON_FAILED_UNKNOWN_ACCOUNT, AUTH_LOGON_FAILED_VERSION_INVALID, BASIC_LOG, SRP6::CalculateProof(), SRP6::CalculateSessionKey(), CMD_AUTH_LOGON_CHALLENGE, CMD_AUTH_LOGON_PROOF, ByteBuffer::contents(), DEBUG_LOG, Database::escape_string(), SRP6::Finalize(), FindBuildInfo(), generateToken(), SRP6::GetStrongSessionKey(), Field::GetUInt32(), SRP6::HashSessionKey(), LOGIN_TYPE_REALMD, LoginDatabase, MaNGOS::Socket::m_address, m_os, m_platform, Database::PExecute(), Database::PQuery(), SRP6::Proof(), MaNGOS::Socket::Read(), sConfig, SECURITY_FLAG_AUTHENTICATOR, SendProof(), ByteBuffer::size(), srp, STATUS_AUTHED, STATUS_CLOSED, VerifyVersion(), and MaNGOS::Socket::Write().
Referenced by ProcessIncomingData().
_HandleRealmList()
bool AuthSocket::_HandleRealmList ()
Realm List command handler
Get the user id (else close the connection)
Update realm list if need
Circle through realms in the RealmList and construct the return packet (including # of user characters in each realm)
Definition at line 795 of file AuthSocket.cpp.
References _login, _safelogin, ByteBuffer::append(), MaNGOS::Socket::Close(), CMD_REALM_LIST, ByteBuffer::contents(), DEBUG_LOG, LoadRealmlist(), LoginDatabase, Database::PQuery(), MaNGOS::Socket::ReadLengthRemaining(), MaNGOS::Socket::ReadSkip(), ByteBuffer::size(), sLog, sRealmList, RealmList::UpdateIfNeed(), and MaNGOS::Socket::Write().
Referenced by ProcessIncomingData().
_HandleReconnectChallenge()
bool AuthSocket::_HandleReconnectChallenge ()
Reconnect Challenge command handler.
Read the first 4 bytes (header) to get the length of the remaining of the packet
Session is closed unless overriden
Read the remaining of the packet
All good, await client's proof
Sending response
Definition at line 672 of file AuthSocket.cpp.
References _build, _login, _reconnectProof, _safelogin, _status, ByteBuffer::append(), BigNumber::AsByteArray(), AUTH_LOGON_CHALLENGE_C::build, MaNGOS::Socket::Close(), CMD_AUTH_RECONNECT_CHALLENGE, ByteBuffer::contents(), DEBUG_LOG, EndianConvert(), Database::escape_string(), QueryResult::Fetch(), AUTH_LOGON_CHALLENGE_C::I, AUTH_LOGON_CHALLENGE_C::I_len, LoginDatabase, Database::PQuery(), MaNGOS::Socket::Read(), MaNGOS::Socket::ReadLengthRemaining(), BigNumber::SetRand(), SRP6::SetStrongSessionKey(), AUTH_LOGON_CHALLENGE_C::size, ByteBuffer::size(), sLog, srp, STATUS_CLOSED, STATUS_RECON_PROOF, VersionChallenge, and MaNGOS::Socket::Write().
Referenced by ProcessIncomingData().
_HandleReconnectProof()
bool AuthSocket::_HandleReconnectProof ()
Reconnect Proof command handler.
Read the packet
Session is closed unless overriden
Sending response
Set _status to authed!
Definition at line 743 of file AuthSocket.cpp.
References _login, _reconnectProof, _status, AUTH_LOGON_FAILED_VERSION_INVALID, AUTH_LOGON_SUCCESS, MaNGOS::Socket::Close(), CMD_AUTH_RECONNECT_PROOF, ByteBuffer::contents(), DEBUG_LOG, CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength(), BigNumber::GetNumBytes(), SRP6::GetStrongSessionKey(), CryptoHash< Algorithm, DigestSize >::Initialize(), AUTH_RECONNECT_PROOF_C::R1, AUTH_RECONNECT_PROOF_C::R2, AUTH_RECONNECT_PROOF_C::R3, MaNGOS::Socket::Read(), BigNumber::SetBinary(), ByteBuffer::size(), sLog, srp, STATUS_AUTHED, STATUS_CLOSED, CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), CryptoHash< Algorithm, DigestSize >::UpdateData(), VerifyVersion(), and MaNGOS::Socket::Write().
Referenced by ProcessIncomingData().
_HandleXferAccept()
bool AuthSocket::_HandleXferAccept ()
Accept patch transfer.
Definition at line 1006 of file AuthSocket.cpp.
References DEBUG_LOG, and MaNGOS::Socket::ReadSkip().
Referenced by ProcessIncomingData().
_HandleXferCancel()
bool AuthSocket::_HandleXferCancel ()
Cancel patch transfer.
Definition at line 995 of file AuthSocket.cpp.
References MaNGOS::Socket::Close(), DEBUG_LOG, and MaNGOS::Socket::ReadSkip().
Referenced by ProcessIncomingData().
_HandleXferResume()
bool AuthSocket::_HandleXferResume ()
Resume patch transfer.
Definition at line 982 of file AuthSocket.cpp.
References DEBUG_LOG, MaNGOS::Socket::ReadLengthRemaining(), and MaNGOS::Socket::ReadSkip().
Referenced by ProcessIncomingData().
generateToken()
int32 AuthSocket::generateToken (char const * b32key)
Definition at line 1015 of file AuthSocket.cpp.
References base32_decode(), and HMAC_RES_SIZE.
Referenced by _HandleLogonProof().
getEligibleRealmCount()
uint8 AuthSocket::getEligibleRealmCount (uint8 accountSecurityLevel)
Definition at line 971 of file AuthSocket.cpp.
References sRealmList.
Referenced by LoadRealmlist().
LoadRealmlist()
void AuthSocket::LoadRealmlist (ByteBuffer & pkt, uint32 acctid, uint8 accountSecurityLevel = 0)
Definition at line 834 of file AuthSocket.cpp.
References _accountSecurityLevel, _build, RealmBuildInfo::bugfix_version, QueryResult::Fetch(), FindBuildInfo(), getEligibleRealmCount(), Field::GetUInt8(), LoginDatabase, RealmBuildInfo::major_version, RealmBuildInfo::minor_version, Database::PQuery(), REALM_FLAG_OFFLINE, REALM_FLAG_SPECIFYBUILD, and sRealmList.
Referenced by _HandleRealmList().
Open()
bool AuthSocket::Open () override virtual
Reimplemented from MaNGOS::Socket.
Definition at line 186 of file AuthSocket.cpp.
References MaNGOS::Socket::Close(), MaNGOS::Socket::IsClosed(), and m_timeoutTimer.
ProcessIncomingData()
bool AuthSocket::ProcessIncomingData () override private virtual
Read the packet from the client.
Circle through known commands and call the correct command handler
Implements MaNGOS::Socket.
Definition at line 204 of file AuthSocket.cpp.
References _HandleLogonChallenge(), _HandleLogonProof(), _HandleRealmList(), _HandleReconnectChallenge(), _HandleReconnectProof(), _HandleXferAccept(), _HandleXferCancel(), _HandleXferResume(), _status, CMD_AUTH_LOGON_CHALLENGE, CMD_AUTH_LOGON_PROOF, CMD_AUTH_RECONNECT_CHALLENGE, CMD_AUTH_RECONNECT_PROOF, CMD_REALM_LIST, CMD_XFER_ACCEPT, CMD_XFER_CANCEL, CMD_XFER_RESUME, DEBUG_LOG, MaNGOS::Socket::InPeak(), m_timeoutTimer, MaNGOS::Socket::ReadLengthRemaining(), STATUS_AUTHED, STATUS_CHALLENGE, STATUS_LOGON_PROOF, STATUS_PATCH, and STATUS_RECON_PROOF.
SendProof()
void AuthSocket::SendProof (Sha1Hash sha)
Definition at line 268 of file AuthSocket.cpp.
References _build, ACCOUNT_FLAG_PROPASS, CMD_AUTH_LOGON_PROOF, CryptoHash< Algorithm, DigestSize >::GetDigest(), and MaNGOS::Socket::Write().
Referenced by _HandleLogonProof().
VerifyVersion()
bool AuthSocket::VerifyVersion (uint8 const * a, int32 aLength, uint8 const * versionProof, bool isReconnect)
Definition at line 1040 of file AuthSocket.cpp.
References _build, CryptoHash< Algorithm, DigestSize >::Finalize(), FindBuildInfo(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< Algorithm, DigestSize >::GetLength(), m_os, RealmBuildInfo::MacHash, sConfig, CryptoHash< Algorithm, DigestSize >::UpdateData(), and RealmBuildInfo::WindowsHash.
Referenced by _HandleLogonProof(), and _HandleReconnectProof().
Field Documentation
_accountSecurityLevel
AccountTypes AuthSocket::_accountSecurityLevel private
Definition at line 91 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), and LoadRealmlist().
_build
uint16 AuthSocket::_build private
Definition at line 90 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), _HandleReconnectChallenge(), LoadRealmlist(), SendProof(), and VerifyVersion().
_login
std::string AuthSocket::_login private
Definition at line 83 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), _HandleRealmList(), _HandleReconnectChallenge(), and _HandleReconnectProof().
_reconnectProof
BigNumber AuthSocket::_reconnectProof private
Definition at line 79 of file AuthSocket.h.
Referenced by _HandleReconnectChallenge(), and _HandleReconnectProof().
_safelocale
std::string AuthSocket::_safelocale private
Definition at line 89 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), and _HandleLogonProof().
_safelogin
std::string AuthSocket::_safelogin private
Definition at line 84 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), _HandleRealmList(), and _HandleReconnectChallenge().
_status
eStatus AuthSocket::_status private
Definition at line 81 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), _HandleReconnectChallenge(), _HandleReconnectProof(), and ProcessIncomingData().
_token
std::string AuthSocket::_token private
Definition at line 85 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), and _HandleLogonProof().
m_locale
std::string AuthSocket::m_locale private
Definition at line 88 of file AuthSocket.h.
Referenced by _HandleLogonChallenge().
m_os
std::string AuthSocket::m_os private
Definition at line 86 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), and VerifyVersion().
m_platform
std::string AuthSocket::m_platform private
Definition at line 87 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), and _HandleLogonProof().
m_timeoutTimer
boost::asio::deadline_timer AuthSocket::m_timeoutTimer private
Definition at line 93 of file AuthSocket.h.
Referenced by Open(), and ProcessIncomingData().
s_BYTE_SIZE
const int AuthSocket::s_BYTE_SIZE = 32 static
Definition at line 43 of file AuthSocket.h.
srp
SRP6 AuthSocket::srp private
Definition at line 78 of file AuthSocket.h.
Referenced by _HandleLogonChallenge(), _HandleLogonProof(), _HandleReconnectChallenge(), and _HandleReconnectProof().
The documentation for this class was generated from the following files:
AuthSocket.h
AuthSocket.cpp