CMaNGOS_WoTLK: PointTOLMovementGenerator Class Reference
PointTOLMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
PointTOLMovementGenerator (uint32 id, float x, float y, float z, bool takeOff, uint32 forcedMovement, float speed=0)
Public Member Functions inherited from PointMovementGenerator
PointMovementGenerator (uint32 id, float x, float y, float z, float o, bool generatePath, uint32 forcedMovement, float speed=0.f, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
PointMovementGenerator (uint32 id, float x, float y, float z, bool generatePath, uint32 forcedMovement, float speed=0.f)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
void Reset (Unit &unit) override
bool Update (Unit &unit, const uint32 &) override
void UnitSpeedChanged () override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
void Move (Unit &unit) override
Protected Member Functions inherited from PointMovementGenerator
virtual void MovementInform (Unit &unit)
Private Attributes
bool m_takeOff
Additional Inherited Members
Protected Attributes inherited from PointMovementGenerator
float m_x
float m_y
float m_z
float m_o
float m_speed
bool m_generatePath
uint32 m_forcedMovement
Detailed Description
Definition at line 101 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
PointTOLMovementGenerator()
PointTOLMovementGenerator::PointTOLMovementGenerator (uint32 id, float x, float y, float z, bool takeOff, uint32 forcedMovement, float speed = 0) inline
Definition at line 104 of file PointMovementGenerator.h.
Member Function Documentation
Move()
void PointTOLMovementGenerator::Move (Unit & unit) override protected virtual
Reimplemented from PointMovementGenerator.
Definition at line 216 of file PointMovementGenerator.cpp.
References Movement::FlyToGround, FORCED_MOVEMENT_WALK, Unit::hasUnitState(), Movement::MoveSplineInit::Launch(), PointMovementGenerator::m_forcedMovement, PointMovementGenerator::m_o, PointMovementGenerator::m_speed, m_takeOff, PointMovementGenerator::m_x, PointMovementGenerator::m_y, PointMovementGenerator::m_z, Movement::MoveSplineInit::MoveTo(), Movement::MoveSplineInit::SetAnimation(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetFly(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), Movement::ToGround, and UNIT_STAT_RUNNING.
Field Documentation
m_takeOff
bool PointTOLMovementGenerator::m_takeOff private
Definition at line 111 of file PointMovementGenerator.h.
Referenced by Move().
The documentation for this class was generated from the following files:
PointMovementGenerator.h
PointMovementGenerator.cpp