CMaNGOS_WoTLK: AchievementMgr Class Reference
AchievementMgr Class Reference
#include <AchievementMgr.h>
Public Types
enum ProgressType { PROGRESS_SET , PROGRESS_ACCUMULATE , PROGRESS_HIGHEST }
Public Member Functions
AchievementMgr (Player *player)
~AchievementMgr ()
void Reset ()
void LoadFromDB (QueryResult *achievementResult, QueryResult *criteriaResult)
void SaveToDB ()
void ResetAchievementCriteria (AchievementCriteriaTypes type, uint32 miscvalue1=0, uint32 miscvalue2=0)
void StartTimedAchievementCriteria (AchievementCriteriaTypes type, uint32 timedRequirementId, time_t startTime=0)
this function will be called whenever the user might have done a timed-criteria relevant action, or by scripting side?
void DoFailedTimedAchievementCriterias ()
this function will be called whenever there could be a timed achievement criteria failed because of ellapsed time
void UpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscvalue1=0, uint32 miscvalue2=0, Unit *unit=nullptr, uint32 time=0)
this function will be called whenever the user might have done a criteria relevant action
void CheckAllAchievementCriteria ()
called at player login.
void SendAllAchievementData ()
void SendRespondInspectAchievements (Player *player)
Player * GetPlayer () const
CompletedAchievementData const * GetCompleteData (uint32 achievement_id) const
bool HasAchievement (uint32 achievement_id) const
CompletedAchievementMap const & GetCompletedAchievements () const
bool IsCompletedCriteria (AchievementCriteriaEntry const *achievementCriteria, AchievementEntry const *achievement) const
CriteriaProgress * GetCriteriaProgress (AchievementCriteriaEntry const *entry)
uint32 GetCriteriaProgressCounter (AchievementCriteriaEntry const *entry) const
void SetCriteriaProgress (AchievementCriteriaEntry const *criteria, AchievementEntry const *achievement, uint32 changeValue, ProgressType ptype)
Static Public Member Functions
static void DeleteFromDB (ObjectGuid guid)
static uint32 GetCriteriaProgressMaxCounter (AchievementCriteriaEntry const *achievementCriteria, AchievementEntry const *achievement)
Private Member Functions
void SendAchievementEarned (AchievementEntry const *achievement) const
void SendCriteriaUpdate (uint32 id, CriteriaProgress const *progress) const
void CompletedCriteriaFor (AchievementEntry const *achievement)
void CompletedAchievement (AchievementEntry const *achievement)
void IncompletedAchievement (AchievementEntry const *achievement)
bool IsCompletedAchievement (AchievementEntry const *entry)
void BuildAllDataPacket (WorldPacket &data)
used by both SMSG_ALL_ACHIEVEMENT_DATA and SMSG_RESPOND_INSPECT_ACHIEVEMENT
Private Attributes
Player * m_player
CriteriaProgressMap m_criteriaProgress
CompletedAchievementMap m_completedAchievements
AchievementCriteriaFailTimeMap m_criteriaFailTimes
Detailed Description
Definition at line 275 of file AchievementMgr.h.
Member Enumeration Documentation
ProgressType
enum AchievementMgr::ProgressType
Enumerator
PROGRESS_SET
PROGRESS_ACCUMULATE
PROGRESS_HIGHEST
Definition at line 310 of file AchievementMgr.h.
Constructor & Destructor Documentation
AchievementMgr()
AchievementMgr::AchievementMgr (Player * player)
Definition at line 444 of file AchievementMgr.cpp.
References m_player.
~AchievementMgr()
AchievementMgr::~AchievementMgr ()
Definition at line 449 of file AchievementMgr.cpp.
Member Function Documentation
BuildAllDataPacket()
void AchievementMgr::BuildAllDataPacket (WorldPacket & data) private
used by both SMSG_ALL_ACHIEVEMENT_DATA and SMSG_RESPOND_INSPECT_ACHIEVEMENT
Definition at line 2431 of file AchievementMgr.cpp.
References ByteBuffer::appendPackGUID(), Object::GetPackGUID(), GetPlayer(), m_completedAchievements, m_criteriaProgress, and secsToTimeBitFields().
Referenced by SendAllAchievementData(), and SendRespondInspectAchievements().
CheckAllAchievementCriteria()
void AchievementMgr::CheckAllAchievementCriteria ()
called at player login.
The player might have fulfilled some achievements when the achievement system wasn't working yet
Definition at line 779 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_TOTAL, and UpdateAchievementCriteria().
Referenced by Player::LoadFromDB(), and Reset().
CompletedAchievement()
void AchievementMgr::CompletedAchievement (AchievementEntry const * achievement) private
Definition at line 2306 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_REALM_FIRST_KILL, MailDraft::AddItem(), CompletedAchievementData::changed, Item::CreateItem(), CompletedAchievementData::date, DETAIL_LOG, AchievementEntry::flags, GetPlayer(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), HORDE, AchievementEntry::ID, AchievementReward::itemId, m_completedAchievements, MAIL_CREATURE, sAchievementMgr, Item::SaveToDB(), sCharTitlesStore, SendAchievementEarned(), AchievementReward::sender, MailDraft::SendMailTo(), Player::SetTitle(), AchievementReward::subject, AchievementReward::text, AchievementReward::titleId, and UpdateAchievementCriteria().
Referenced by CompletedCriteriaFor(), and SetCriteriaProgress().
CompletedCriteriaFor()
void AchievementMgr::CompletedCriteriaFor (AchievementEntry const * achievement) private
Definition at line 2121 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_COUNTER, CompletedAchievement(), AchievementEntry::flags, AchievementEntry::ID, IsCompletedAchievement(), and m_completedAchievements.
Referenced by SetCriteriaProgress().
DeleteFromDB()
void AchievementMgr::DeleteFromDB (ObjectGuid guid) static
Definition at line 563 of file AchievementMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), ObjectGuid::GetCounter(), and Database::PExecute().
Referenced by ChatHandler::HandleResetAchievementsCommand(), and Reset().
DoFailedTimedAchievementCriterias()
void AchievementMgr::DoFailedTimedAchievementCriterias ()
this function will be called whenever there could be a timed achievement criteria failed because of ellapsed time
Definition at line 867 of file AchievementMgr.cpp.
References DETAIL_FILTER_LOG, AchievementCriteriaEntry::ID, IsCompletedCriteria(), LOG_FILTER_ACHIEVEMENT_UPDATES, m_criteriaFailTimes, m_criteriaProgress, MANGOS_ASSERT, AchievementCriteriaEntry::referredAchievement, sAchievementCriteriaStore, sAchievementStore, SendCriteriaUpdate(), and CriteriaProgress::timedCriteriaFailed.
Referenced by Player::Update().
GetCompletedAchievements()
CompletedAchievementMap const& AchievementMgr::GetCompletedAchievements () const inline
Definition at line 302 of file AchievementMgr.h.
References m_completedAchievements.
Referenced by ChatHandler::HandleCharacterAchievementsCommand().
GetCompleteData()
CompletedAchievementData const* AchievementMgr::GetCompleteData (uint32 achievement_id) const inline
Definition at line 295 of file AchievementMgr.h.
References m_completedAchievements.
Referenced by ChatHandler::HandleAchievementAddCommand(), ChatHandler::HandleAchievementCommand(), ChatHandler::HandleAchievementRemoveCommand(), ChatHandler::HandleLookupAchievementCommand(), and HasAchievement().
GetCriteriaProgress()
CriteriaProgress * AchievementMgr::GetCriteriaProgress (AchievementCriteriaEntry const * entry)
Definition at line 1891 of file AchievementMgr.cpp.
References AchievementCriteriaEntry::ID, and m_criteriaProgress.
Referenced by UpdateAchievementCriteria().
GetCriteriaProgressCounter()
uint32 AchievementMgr::GetCriteriaProgressCounter (AchievementCriteriaEntry const * entry) const
Definition at line 1897 of file AchievementMgr.cpp.
References AchievementCriteriaEntry::ID, and m_criteriaProgress.
Referenced by ChatHandler::HandleAchievementCriteriaAddCommand(), ChatHandler::HandleAchievementCriteriaRemoveCommand(), and ChatHandler::ShowAchievementCriteriaListHelper().
GetCriteriaProgressMaxCounter()
uint32 AchievementMgr::GetCriteriaProgressMaxCounter (AchievementCriteriaEntry const * achievementCriteria, AchievementEntry const * achievement) static
Definition at line 1903 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE, ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_DEATH, ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP, ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON, ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN, ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER, ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS, ACHIEVEMENT_CRITERIA_TYPE_HK_RACE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL, ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM, ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED, ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, ACHIEVEMENT_FLAG_COUNTER, AchievementCriteriaEntry::be_spell_target, AchievementCriteriaEntry::buy_bank_slot, AchievementCriteriaEntry::capture_bg_objective, AchievementCriteriaEntry::cast_spell, AchievementCriteriaEntry::complete_daily_quest, AchievementCriteriaEntry::complete_quest_count, AchievementCriteriaEntry::complete_quests_in_zone, AchievementCriteriaEntry::do_emote, AchievementCriteriaEntry::equip_epic_item, AchievementCriteriaEntry::equip_item, AchievementCriteriaEntry::fall_without_dying, AchievementCriteriaEntry::fish_in_gameobject, AchievementEntry::flags, AchievementCriteriaEntry::gain_exalted_reputation, AchievementCriteriaEntry::gain_reputation, AchievementCriteriaEntry::healing_done, AchievementCriteriaEntry::highest_personal_rating, AchievementCriteriaEntry::hk_class, AchievementCriteriaEntry::hk_race, AchievementCriteriaEntry::honorable_kill, AchievementCriteriaEntry::honorable_kill_at_area, AchievementCriteriaEntry::honorable_kill_battleground, AchievementCriteriaEntry::kill_creature, AchievementCriteriaEntry::learn_skill_level, AchievementCriteriaEntry::learn_skill_line, AchievementCriteriaEntry::learn_skillline_spell, AchievementCriteriaEntry::loot_item, AchievementCriteriaEntry::loot_money, AchievementCriteriaEntry::loot_type, AchievementCriteriaEntry::own_item, AchievementCriteriaEntry::quest_reward_money, AchievementCriteriaEntry::raw, AchievementCriteriaEntry::reach_level, AchievementCriteriaEntry::reach_skill_level, AchievementCriteriaEntry::requiredType, AchievementCriteriaEntry::roll_greed_on_loot, AchievementCriteriaEntry::special_pvp_kill, AchievementCriteriaEntry::use_gameobject, AchievementCriteriaEntry::use_item, AchievementCriteriaEntry::visit_barber, AchievementCriteriaEntry::win_bg, AchievementCriteriaEntry::win_duel, and AchievementCriteriaEntry::win_rated_arena.
Referenced by ChatHandler::HandleAchievementAddCommand(), ChatHandler::HandleAchievementCriteriaAddCommand(), ChatHandler::HandleAchievementCriteriaRemoveCommand(), IsCompletedCriteria(), LoadFromDB(), SetCriteriaProgress(), and ChatHandler::ShowAchievementCriteriaListHelper().
GetPlayer()
Player* AchievementMgr::GetPlayer () const inline
Definition at line 293 of file AchievementMgr.h.
References m_player.
Referenced by BuildAllDataPacket(), CompletedAchievement(), IncompletedAchievement(), SaveToDB(), SendAchievementEarned(), SendAllAchievementData(), SendCriteriaUpdate(), SendRespondInspectAchievements(), StartTimedAchievementCriteria(), and UpdateAchievementCriteria().
HasAchievement()
bool AchievementMgr::HasAchievement (uint32 achievement_id) const inline
Definition at line 301 of file AchievementMgr.h.
References GetCompleteData().
Referenced by LFGMgr::GetLockedDungeons(), and SetCriteriaProgress().
IncompletedAchievement()
void AchievementMgr::IncompletedAchievement (AchievementEntry const * achievement) private
Definition at line 2374 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_COUNTER, CharacterDatabase, DETAIL_LOG, AchievementEntry::flags, GetPlayer(), HORDE, AchievementEntry::ID, m_completedAchievements, m_player, Database::PExecute(), sAchievementMgr, sCharTitlesStore, Player::SendDirectMessage(), Player::SetTitle(), SMSG_ACHIEVEMENT_DELETED, and AchievementReward::titleId.
Referenced by SetCriteriaProgress().
IsCompletedAchievement()
bool AchievementMgr::IsCompletedAchievement (AchievementEntry const * entry) private
Definition at line 2135 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_SUMM, AchievementEntry::count, CriteriaProgress::counter, AchievementEntry::flags, AchievementEntry::ID, IsCompletedCriteria(), m_criteriaProgress, AchievementEntry::refAchievement, and sAchievementMgr.
Referenced by CompletedCriteriaFor(), ResetAchievementCriteria(), and SetCriteriaProgress().
IsCompletedCriteria()
bool AchievementMgr::IsCompletedCriteria (AchievementCriteriaEntry const * achievementCriteria, AchievementEntry const * achievement) const
Definition at line 2097 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_COUNTER, ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, ACHIEVEMENT_FLAG_REQ_COUNT, CriteriaProgress::counter, AchievementEntry::flags, GetCriteriaProgressMaxCounter(), AchievementCriteriaEntry::ID, m_criteriaProgress, and sAchievementMgr.
Referenced by DoFailedTimedAchievementCriterias(), ChatHandler::HandleAchievementAddCommand(), ChatHandler::HandleAchievementCriteriaAddCommand(), IsCompletedAchievement(), LoadFromDB(), ResetAchievementCriteria(), SetCriteriaProgress(), ChatHandler::ShowAchievementCriteriaListHelper(), StartTimedAchievementCriteria(), and UpdateAchievementCriteria().
LoadFromDB()
void AchievementMgr::LoadFromDB (QueryResult * achievementResult, QueryResult * criteriaResult)
Definition at line 629 of file AchievementMgr.cpp.
References CriteriaProgress::changed, CompletedAchievementData::changed, CharacterDatabase, CriteriaProgress::counter, CriteriaProgress::date, CompletedAchievementData::date, QueryResult::Fetch(), GetCriteriaProgressMaxCounter(), Field::GetUInt32(), AchievementCriteriaEntry::ID, IsCompletedCriteria(), m_completedAchievements, m_criteriaFailTimes, m_criteriaProgress, QueryResult::NextRow(), Database::PExecute(), AchievementCriteriaEntry::referredAchievement, sAchievementCriteriaStore, sAchievementStore, sLog, CriteriaProgress::timedCriteriaFailed, and AchievementCriteriaEntry::timeLimit.
Referenced by Player::LoadFromDB().
Reset()
void AchievementMgr::Reset ()
Definition at line 453 of file AchievementMgr.cpp.
References CheckAllAchievementCriteria(), DeleteFromDB(), Object::GetObjectGuid(), m_completedAchievements, m_criteriaProgress, m_player, Player::SendDirectMessage(), SMSG_ACHIEVEMENT_DELETED, and SMSG_CRITERIA_DELETED.
Referenced by ChatHandler::HandleResetAchievementsCommand().
ResetAchievementCriteria()
void AchievementMgr::ResetAchievementCriteria (AchievementCriteriaTypes type, uint32 miscvalue1 = 0, uint32 miscvalue2 = 0)
Definition at line 477 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_FLAG_FAIL_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, CONFIG_BOOL_GM_ALLOW_ACHIEVEMENT_GAINS, DETAIL_FILTER_LOG, WorldSession::GetSecurity(), Player::GetSession(), IsCompletedAchievement(), IsCompletedCriteria(), LOG_FILTER_ACHIEVEMENT_UPDATES, m_player, PROGRESS_SET, sAchievementMgr, sAchievementStore, SEC_PLAYER, SetCriteriaProgress(), and sWorld.
Referenced by BattleGround::AddPlayer(), BattleGround::EndBattleGround(), and BattleGround::HandleKillPlayer().
SaveToDB()
void AchievementMgr::SaveToDB ()
mark as saved in db
mark as updated in db
Definition at line 572 of file AchievementMgr.cpp.
References CharacterDatabase, Database::CreateStatement(), GetPlayer(), m_completedAchievements, m_criteriaProgress, SqlStatement::PExecute(), sAchievementCriteriaStore, and AchievementCriteriaEntry::timeLimit.
Referenced by Player::SaveToDB().
SendAchievementEarned()
void AchievementMgr::SendAchievementEarned (AchievementEntry const * achievement) const private
Definition at line 711 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_REALM_FIRST_KILL, ACHIEVEMENT_FLAG_REALM_FIRST_REACH, ALLIANCE, CHAT_MSG_ACHIEVEMENT, CHAT_MSG_GUILD_ACHIEVEMENT, CONFIG_FLOAT_LISTEN_RANGE_SAY, DEBUG_FILTER_LOG, AchievementEntry::flags, WorldObject::GetName(), Object::GetObjectGuid(), Object::GetPackGUID(), GetPlayer(), Player::GetTeam(), HORDE, AchievementEntry::ID, Object::IsInWorld(), LANG_ACHIEVEMENT_EARNED, LOG_FILTER_ACHIEVEMENT_UPDATES, ByteBuffer::put(), secsToTimeBitFields(), Player::SendMessageToSetInRange(), sGuildMgr, SMSG_ACHIEVEMENT_EARNED, SMSG_SERVER_FIRST_ACHIEVEMENT, sWorld, Cell::VisitWorldObjects(), and ByteBuffer::wpos().
Referenced by CompletedAchievement().
SendAllAchievementData()
void AchievementMgr::SendAllAchievementData ()
Definition at line 2411 of file AchievementMgr.cpp.
References BuildAllDataPacket(), GetPlayer(), Player::GetSession(), m_completedAchievements, WorldSession::SendPacket(), and SMSG_ALL_ACHIEVEMENT_DATA.
Referenced by Player::SendInitialPacketsBeforeAddToMap().
SendCriteriaUpdate()
void AchievementMgr::SendCriteriaUpdate (uint32 id, CriteriaProgress const * progress) const private
Definition at line 759 of file AchievementMgr.cpp.
References ByteBuffer::appendPackGUID(), CriteriaProgress::counter, CriteriaProgress::date, Object::GetPackGUID(), GetPlayer(), secsToTimeBitFields(), Player::SendDirectMessage(), SMSG_CRITERIA_UPDATE, and CriteriaProgress::timedCriteriaFailed.
Referenced by DoFailedTimedAchievementCriterias(), SetCriteriaProgress(), and StartTimedAchievementCriteria().
SendRespondInspectAchievements()
void AchievementMgr::SendRespondInspectAchievements (Player * player)
Definition at line 2419 of file AchievementMgr.cpp.
References BuildAllDataPacket(), Object::GetPackGUID(), GetPlayer(), Player::GetSession(), m_completedAchievements, WorldSession::SendPacket(), and SMSG_RESPOND_INSPECT_ACHIEVEMENTS.
Referenced by WorldSession::HandleQueryInspectAchievementsOpcode().
SetCriteriaProgress()
void AchievementMgr::SetCriteriaProgress (AchievementCriteriaEntry const * criteria, AchievementEntry const * achievement, uint32 changeValue, ProgressType ptype)
Definition at line 2191 of file AchievementMgr.cpp.
References ACHIEVEMENT_FLAG_SUMM, CriteriaProgress::changed, CompletedAchievement(), CompletedCriteriaFor(), CriteriaProgress::counter, CriteriaProgress::date, DETAIL_FILTER_LOG, AchievementEntry::flags, GetCriteriaProgressMaxCounter(), Object::GetGUIDLow(), HasAchievement(), AchievementEntry::ID, AchievementCriteriaEntry::ID, IncompletedAchievement(), IsCompletedAchievement(), IsCompletedCriteria(), AchievementCriteriaEntry::IsExplicitlyStartedTimedCriteria(), LOG_FILTER_ACHIEVEMENT_UPDATES, m_criteriaFailTimes, m_criteriaProgress, m_player, PROGRESS_ACCUMULATE, PROGRESS_HIGHEST, PROGRESS_SET, sAchievementMgr, SendCriteriaUpdate(), Player::SendDirectMessage(), SMSG_CRITERIA_DELETED, CriteriaProgress::timedCriteriaFailed, and AchievementCriteriaEntry::timeLimit.
Referenced by ChatHandler::HandleAchievementAddCommand(), ChatHandler::HandleAchievementCriteriaAddCommand(), ChatHandler::HandleAchievementCriteriaRemoveCommand(), ChatHandler::HandleAchievementRemoveCommand(), ResetAchievementCriteria(), and UpdateAchievementCriteria().
StartTimedAchievementCriteria()
void AchievementMgr::StartTimedAchievementCriteria (AchievementCriteriaTypes type, uint32 timedRequirementId, time_t startTime = 0)
this function will be called whenever the user might have done a timed-criteria relevant action, or by scripting side?
Definition at line 806 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_FACTION_FLAG_ALLIANCE, ACHIEVEMENT_FACTION_FLAG_HORDE, ALLIANCE, CriteriaProgress::changed, CONFIG_BOOL_GM_ALLOW_ACHIEVEMENT_GAINS, CriteriaProgress::counter, CriteriaProgress::date, DETAIL_FILTER_LOG, AchievementEntry::factionFlag, GetPlayer(), WorldSession::GetSecurity(), Player::GetSession(), HORDE, IsCompletedCriteria(), LOG_FILTER_ACHIEVEMENT_UPDATES, m_criteriaFailTimes, m_criteriaProgress, m_player, sAchievementMgr, sAchievementStore, SEC_PLAYER, SendCriteriaUpdate(), sWorld, and CriteriaProgress::timedCriteriaFailed.
Referenced by WorldSession::HandleQuestgiverAcceptQuestOpcode(), BattleGroundWS::ProcessFlagPickUpFromBase(), and Player::StartTimedAchievementCriteria().
UpdateAchievementCriteria()
void AchievementMgr::UpdateAchievementCriteria (AchievementCriteriaTypes type, uint32 miscvalue1 = 0, uint32 miscvalue2 = 0, Unit * unit = nullptr, uint32 time = 0)
this function will be called whenever the user might have done a criteria relevant action
Definition at line 911 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_CONDITION_MAP, ACHIEVEMENT_CRITERIA_CONDITION_NO_GROUP, ACHIEVEMENT_CRITERIA_CONDITION_NO_LOOSE, ACHIEVEMENT_CRITERIA_TYPE_ACCEPTED_SUMMONINGS, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_BUY_BANK_SLOT, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_ACHIEVEMENT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_BATTLEGROUND, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_DAILY_QUEST_DAILY, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST_COUNT, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUESTS_IN_ZONE, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_RAID, ACHIEVEMENT_CRITERIA_TYPE_CREATE_AUCTION, ACHIEVEMENT_CRITERIA_TYPE_DAMAGE_DONE, ACHIEVEMENT_CRITERIA_TYPE_DEATH, ACHIEVEMENT_CRITERIA_TYPE_DEATH_AT_MAP, ACHIEVEMENT_CRITERIA_TYPE_DEATH_IN_DUNGEON, ACHIEVEMENT_CRITERIA_TYPE_DEATHS_FROM, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EARN_ACHIEVEMENT_POINTS, ACHIEVEMENT_CRITERIA_TYPE_EARN_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_ITEM, ACHIEVEMENT_CRITERIA_TYPE_EXPLORE_AREA, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_FLIGHT_PATHS_TAKEN, ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_AT_BARBER, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_MAIL, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TALENTS, ACHIEVEMENT_CRITERIA_TYPE_GOLD_SPENT_FOR_TRAVELLING, ACHIEVEMENT_CRITERIA_TYPE_HEALING_DONE, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_ARMOR, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_BID, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_GOLD_VALUE_OWNED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEAL_CASTED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALING_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HEALTH, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_DEALT, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_HIT_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_PERSONAL_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_POWER, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_RATING, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_SPELLPOWER, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_STAT, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_TEAM_RATING, ACHIEVEMENT_CRITERIA_TYPE_HK_CLASS, ACHIEVEMENT_CRITERIA_TYPE_HK_RACE, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL_AT_AREA, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILLED_BY_PLAYER, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILL_LINE, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SKILLLINE_SPELLS, ACHIEVEMENT_CRITERIA_TYPE_LEARN_SPELL, ACHIEVEMENT_CRITERIA_TYPE_LOOT_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_ITEM, ACHIEVEMENT_CRITERIA_TYPE_LOOT_MONEY, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOSE_DUEL, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_QUEST_REWARD, ACHIEVEMENT_CRITERIA_TYPE_MONEY_FROM_VENDORS, ACHIEVEMENT_CRITERIA_TYPE_NUMBER_OF_TALENT_RESETS, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_OWN_ITEM, ACHIEVEMENT_CRITERIA_TYPE_OWN_RANK, ACHIEVEMENT_CRITERIA_TYPE_PLAY_ARENA, ACHIEVEMENT_CRITERIA_TYPE_QUEST_ABANDONED, ACHIEVEMENT_CRITERIA_TYPE_REACH_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_REACH_SKILL_LEVEL, ACHIEVEMENT_CRITERIA_TYPE_RECEIVE_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED_ON_LOOT, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_TOTAL_DAMAGE_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_TOTAL_HEALING_RECEIVED, ACHIEVEMENT_CRITERIA_TYPE_USE_GAMEOBJECT, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS, ACHIEVEMENT_CRITERIA_TYPE_VISIT_BARBER_SHOP, ACHIEVEMENT_CRITERIA_TYPE_WIN_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, ACHIEVEMENT_FACTION_FLAG_ALLIANCE, ACHIEVEMENT_FACTION_FLAG_HORDE, achievIdByArenaSlot, achievIdByClass, achievIdByRace, achievIdForDungeon, ALLIANCE, WorldMapOverlayEntry::areatableID, CONFIG_BOOL_GM_ALLOW_ACHIEVEMENT_GAINS, CriteriaProgress::date, DAY, DETAIL_FILTER_LOG, DUNGEON_DIFFICULTY_NORMAL, AchievementEntry::factionFlag, GetAreaFlagByAreaID(), BattleGround::GetArenaType(), Player::GetBankBagSlotCount(), Player::GetBattleGround(), GetCriteriaProgress(), ReputationMgr::GetExaltedFactionCount(), ReputationMgr::GetHonoredFactionCount(), Player::GetItemCount(), ObjectMgr::GetItemPrototype(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetMapId(), Map::GetMaxPlayers(), Player::GetMoney(), GetPlayer(), Player::getQuestStatusMap(), ReputationMgr::GetReputation(), Player::GetReputationMgr(), ReputationMgr::GetReveredFactionCount(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetSkillMaxPure(), Player::GetSkillValueBase(), ArenaTeam::GetSlotByType(), Player::GetSpellMap(), Object::GetTypeId(), Object::GetUInt32Value(), ReputationMgr::GetVisibleFactionCount(), Quest::GetZoneOrSort(), HORDE, AchievementEntry::ID, BattleGround::IsArena(), IsCompletedCriteria(), Map::IsDungeon(), Object::IsInWorld(), Map::IsRaid(), ITEM_QUALITY_EPIC, ItemPrototype::ItemLevel, LOG_FILTER_ACHIEVEMENT_UPDATES, m_completedAchievements, m_player, MAX_ARENA_SLOT, MAX_CLASSES, MAX_RACES, AchievementCriteriaRequirementSet::Meets(), PLAYER_EXPLORED_ZONES_1, PLAYER_FIELD_LIFETIME_HONORABLE_KILLS, PROGRESS_ACCUMULATE, PROGRESS_HIGHEST, PROGRESS_SET, ItemPrototype::Quality, sAchievementMgr, sAchievementStore, SEC_PLAYER, SetCriteriaProgress(), sMapMgr, sObjectMgr, sSpellMgr, sWorld, sWorldMapOverlayStore, and TYPEID_PLAYER.
Referenced by Player::addSpell(), CheckAllAchievementCriteria(), Player::CheckAreaExploreAndOutdoor(), CompletedAchievement(), Spell::DoSpellHitOnUnit(), Player::DuelComplete(), BattleGround::EndBattleGround(), Player::EnvironmentalDamage(), Player::EquipItem(), Player::EquipNewItem(), GroupLootRoll::Finish(), Player::GiveLevel(), WorldSession::HandleAlterAppearanceOpcode(), WorldSession::HandleAuctionPlaceBid(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleBuybackItem(), WorldSession::HandleBuyBankSlotOpcode(), Player::HandleFall(), WorldSession::HandleGameobjectReportUse(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandlePlayerLogin(), WorldSession::HandleQuestLogRemoveQuest(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleTextEmoteOpcode(), Unit::Kill(), Player::KilledMonster(), Player::KilledMonsterCredit(), Player::MoveItemToInventory(), LootMgr::PlayerVote(), GroupLootRoll::PlayerVote(), Player::QuickEquipItem(), Player::resetTalents(), Player::RewardQuest(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), Loot::SendGold(), Loot::SendItem(), Player::SetDeathState(), ReputationMgr::SetOneFactionReputation(), Player::SetSkill(), Player::StoreItem(), Player::StoreNewItem(), Player::SummonIfPossible(), Player::UpdateAchievementCriteria(), Player::UpdateSkill(), and Player::UpdateSkillPro().
Field Documentation
m_completedAchievements
CompletedAchievementMap AchievementMgr::m_completedAchievements private
Definition at line 324 of file AchievementMgr.h.
Referenced by BuildAllDataPacket(), CompletedAchievement(), CompletedCriteriaFor(), GetCompletedAchievements(), GetCompleteData(), IncompletedAchievement(), LoadFromDB(), Reset(), SaveToDB(), SendAllAchievementData(), SendRespondInspectAchievements(), and UpdateAchievementCriteria().
m_criteriaFailTimes
AchievementCriteriaFailTimeMap AchievementMgr::m_criteriaFailTimes private
Definition at line 325 of file AchievementMgr.h.
Referenced by DoFailedTimedAchievementCriterias(), LoadFromDB(), SetCriteriaProgress(), and StartTimedAchievementCriteria().
m_criteriaProgress
CriteriaProgressMap AchievementMgr::m_criteriaProgress private
Definition at line 323 of file AchievementMgr.h.
Referenced by BuildAllDataPacket(), DoFailedTimedAchievementCriterias(), GetCriteriaProgress(), GetCriteriaProgressCounter(), IsCompletedAchievement(), IsCompletedCriteria(), LoadFromDB(), Reset(), SaveToDB(), SetCriteriaProgress(), and StartTimedAchievementCriteria().
m_player
Player* AchievementMgr::m_player private
Definition at line 322 of file AchievementMgr.h.
Referenced by AchievementMgr(), GetPlayer(), IncompletedAchievement(), Reset(), ResetAchievementCriteria(), SetCriteriaProgress(), StartTimedAchievementCriteria(), and UpdateAchievementCriteria().
The documentation for this class was generated from the following files:
AchievementMgr.h
AchievementMgr.cpp