CMaNGOS_WoTLK: instance_magtheridons_lair Class Reference
instance_magtheridons_lair Class Reference
#include <magtheridons_lair.h>
Public Member Functions
instance_magtheridons_lair (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
GuidList m_lChannelerGuidList
GuidList m_lColumnGuidList
GuidList m_lCubeGuidList
uint32 m_uiRandYellTimer
uint32 m_uiCageBreakTimer
uint8 m_uiCageBreakStage
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 35 of file magtheridons_lair.h.
Constructor & Destructor Documentation
instance_magtheridons_lair()
instance_magtheridons_lair::instance_magtheridons_lair (Map * pMap)
Definition at line 28 of file magtheridons_lair.cpp.
References Initialize().
Member Function Documentation
GetData()
uint32 instance_magtheridons_lair::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 199 of file magtheridons_lair.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Initialize()
void instance_magtheridons_lair::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 36 of file magtheridons_lair.cpp.
References m_auiEncounter.
Referenced by instance_magtheridons_lair().
IsEncounterInProgress()
bool instance_magtheridons_lair::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 41 of file magtheridons_lair.cpp.
References IN_PROGRESS, and m_auiEncounter.
OnCreatureCreate()
void instance_magtheridons_lair::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 52 of file magtheridons_lair.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lChannelerGuidList, ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_BURNING_ABYSSAL, NPC_CHANNELER, and NPC_MAGTHERIDON.
OnObjectCreate()
void instance_magtheridons_lair::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 68 of file magtheridons_lair.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_DOODAD_HF_MAG_DOOR01, GO_DOODAD_HF_RAID_FX01, GO_MAGTHERIDON_COLUMN_000, GO_MAGTHERIDON_COLUMN_001, GO_MAGTHERIDON_COLUMN_002, GO_MAGTHERIDON_COLUMN_003, GO_MAGTHERIDON_COLUMN_004, GO_MAGTHERIDON_COLUMN_005, GO_MANTICRON_CUBE, ScriptedInstance::m_goEntryGuidStore, m_lColumnGuidList, and m_lCubeGuidList.
SetData()
void instance_magtheridons_lair::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 90 of file magtheridons_lair.cpp.
References AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, ScriptedInstance::DespawnGuids(), DONE, ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_DOODAD_HF_MAG_DOOR01, GO_FLAG_NO_INTERACT, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_lChannelerGuidList, m_lColumnGuidList, m_lCubeGuidList, m_uiCageBreakStage, m_uiCageBreakTimer, MINUTE, NOT_STARTED, NPC_BURNING_ABYSSAL, NPC_MAGTHERIDON, SPECIAL, TYPE_CHANNELER_EVENT, and TYPE_MAGTHERIDON_EVENT.
Referenced by Update().
Update()
void instance_magtheridons_lair::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 207 of file magtheridons_lair.cpp.
References aRandomTaunt, DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), EMOTE_NEARLY_FREE, ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, m_auiEncounter, m_uiCageBreakStage, m_uiCageBreakTimer, m_uiRandYellTimer, MINUTE, NPC_MAGTHERIDON, SetData(), TYPE_CHANNELER_EVENT, TYPE_MAGTHERIDON_EVENT, and urand().
Field Documentation
m_auiEncounter
uint32 instance_magtheridons_lair::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 53 of file magtheridons_lair.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), SetData(), and Update().
m_lChannelerGuidList
GuidList instance_magtheridons_lair::m_lChannelerGuidList private
Definition at line 55 of file magtheridons_lair.h.
Referenced by OnCreatureCreate(), and SetData().
m_lColumnGuidList
GuidList instance_magtheridons_lair::m_lColumnGuidList private
Definition at line 56 of file magtheridons_lair.h.
Referenced by OnObjectCreate(), and SetData().
m_lCubeGuidList
GuidList instance_magtheridons_lair::m_lCubeGuidList private
Definition at line 57 of file magtheridons_lair.h.
Referenced by OnObjectCreate(), and SetData().
m_uiCageBreakStage
uint8 instance_magtheridons_lair::m_uiCageBreakStage private
Definition at line 61 of file magtheridons_lair.h.
Referenced by SetData(), and Update().
m_uiCageBreakTimer
uint32 instance_magtheridons_lair::m_uiCageBreakTimer private
Definition at line 60 of file magtheridons_lair.h.
Referenced by SetData(), and Update().
m_uiRandYellTimer
uint32 instance_magtheridons_lair::m_uiRandYellTimer private
Definition at line 59 of file magtheridons_lair.h.
Referenced by Update().
The documentation for this class was generated from the following files:
magtheridons_lair.h
magtheridons_lair.cpp