CMaNGOS_WoTLK: SQLStorageBase Class Reference
SQLStorageBase Class Reference abstract
#include <SQLStorage.h>
Data Structures
class SQLSIterator
Public Member Functions
char const * GetTableName () const
char const * EntryFieldName () const
FieldFormat GetDstFormat (uint32 idx) const
const char * GetDstFormat () const
FieldFormat GetSrcFormat (uint32 idx) const
const char * GetSrcFormat () const
uint32 GetMaxEntry () const
uint32 GetRecordCount () const
template<typename T >
SQLSIterator< T > getDataBegin () const
template<typename T >
SQLSIterator< T > getDataEnd () const
Protected Member Functions
SQLStorageBase ()
virtual ~SQLStorageBase ()
void Initialize (const char *tableName, const char *entry_field, const char *src_format, const char *dst_format)
uint32 GetDstFieldCount () const
uint32 GetSrcFieldCount () const
uint32 GetRecordSize () const
virtual void prepareToLoad (uint32 maxEntry, uint32 recordCount, uint32 recordSize)
virtual void JustCreatedRecord (uint32 recordId, char *record)=0
virtual void Free ()
Private Member Functions
char * createRecord (uint32 recordId)
Private Attributes
const char * m_tableName
const char * m_entry_field
const char * m_src_format
const char * m_dst_format
uint32 m_dstFieldCount
uint32 m_srcFieldCount
uint32 m_recordCount
uint32 m_maxEntry
uint32 m_recordSize
char * m_data
Friends
template<class DerivedLoader , class StorageClass >
class SQLStorageLoaderBase
Detailed Description
Definition at line 26 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLStorageBase()
SQLStorageBase::SQLStorageBase () protected
Definition at line 23 of file SQLStorage.cpp.
~SQLStorageBase()
virtual SQLStorageBase::~SQLStorageBase () inline protected virtual
Definition at line 69 of file SQLStorage.h.
References Free().
Member Function Documentation
createRecord()
char * SQLStorageBase::createRecord (uint32 recordId) private
Definition at line 47 of file SQLStorage.cpp.
References JustCreatedRecord(), m_data, m_recordCount, and m_recordSize.
EntryFieldName()
char const* SQLStorageBase::EntryFieldName () const inline
Definition at line 32 of file SQLStorage.h.
References m_entry_field.
Free()
void SQLStorageBase::Free () protected virtual
Reimplemented in SQLMultiStorage, SQLHashStorage, and SQLStorage.
Definition at line 69 of file SQLStorage.cpp.
References FT_64BITINT, FT_BYTE, FT_FLOAT, FT_IND, FT_INT, FT_LOGIC, FT_NA, FT_NA_BYTE, FT_NA_FLOAT, FT_NA_POINTER, FT_SORT, FT_STRING, m_data, m_dst_format, m_dstFieldCount, m_recordCount, and m_recordSize.
Referenced by SQLStorage::Free(), SQLHashStorage::Free(), SQLMultiStorage::Free(), and ~SQLStorageBase().
getDataBegin()
template<typename T > SQLSIterator<T> SQLStorageBase::getDataBegin () const inline
Definition at line 63 of file SQLStorage.h.
References m_data, and m_recordSize.
Referenced by ScriptMgr::CollectPossibleEventIds(), ChatHandler::HandleLookupObjectCommand(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), LoadLootTemplates_Gameobject(), SpellMgr::LoadSpellScriptTarget(), ObjectMgr::LoadSpellTemplate(), and ObjectMgr::LoadVehicleAccessory().
getDataEnd()
template<typename T > SQLSIterator<T> SQLStorageBase::getDataEnd () const inline
Definition at line 65 of file SQLStorage.h.
References m_data, m_recordCount, and m_recordSize.
Referenced by ScriptMgr::CollectPossibleEventIds(), ChatHandler::HandleLookupObjectCommand(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), LoadLootTemplates_Gameobject(), SpellMgr::LoadSpellScriptTarget(), ObjectMgr::LoadSpellTemplate(), and ObjectMgr::LoadVehicleAccessory().
GetDstFieldCount()
uint32 SQLStorageBase::GetDstFieldCount () const inline protected
Definition at line 73 of file SQLStorage.h.
References m_dstFieldCount.
GetDstFormat() [1/2]
const char* SQLStorageBase::GetDstFormat () const inline
Definition at line 35 of file SQLStorage.h.
References m_dst_format.
GetDstFormat() [2/2]
FieldFormat SQLStorageBase::GetDstFormat (uint32 idx) const inline
Definition at line 34 of file SQLStorage.h.
References m_dst_format.
GetMaxEntry()
uint32 SQLStorageBase::GetMaxEntry () const inline
Definition at line 39 of file SQLStorage.h.
References m_maxEntry.
Referenced by ObjectMgr::CheckSpellCones(), SpellMgr::CheckUsedSpells(), ScriptMgr::CollectPossibleEventIds(), FillSpellSummary(), ChatHandler::HandleAddItemSetCommand(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleQuestAddCommand(), SpellTargetMgr::Initialize(), ObjectMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureConditionalSpawn(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplates(), LoadDBCStores(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemPrototypes(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Item(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Skinning(), LoadLootTemplates_Spell(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadPetDefaultSpells(), ScriptMgr::LoadScripts(), LoadSkillDiscoveryTable(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellScriptTarget(), ObjectMgr::LoadSpellTemplate(), ObjectMgr::LoadTrainerTemplates(), TransportMgr::LoadTransportTemplates(), ObjectMgr::LoadVendorTemplates(), ObjectMgr::LoadWorldTemplate(), and SQLStorage::LookupEntry().
GetRecordCount()
uint32 SQLStorageBase::GetRecordCount () const inline
Definition at line 40 of file SQLStorage.h.
References m_recordCount.
Referenced by ObjectMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureConditionalSpawn(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadPageTexts(), SpellMgr::LoadSpellScriptTarget(), ObjectMgr::LoadSpellTemplate(), ObjectMgr::LoadVehicleAccessory(), World::LoadWorldSafeLocs(), and ObjectMgr::LoadWorldTemplate().
GetRecordSize()
uint32 SQLStorageBase::GetRecordSize () const inline protected
Definition at line 75 of file SQLStorage.h.
References m_recordSize.
GetSrcFieldCount()
uint32 SQLStorageBase::GetSrcFieldCount () const inline protected
Definition at line 74 of file SQLStorage.h.
References m_srcFieldCount.
GetSrcFormat() [1/2]
const char* SQLStorageBase::GetSrcFormat () const inline
Definition at line 37 of file SQLStorage.h.
References m_src_format.
GetSrcFormat() [2/2]
FieldFormat SQLStorageBase::GetSrcFormat (uint32 idx) const inline
Definition at line 36 of file SQLStorage.h.
References m_src_format.
GetTableName()
char const* SQLStorageBase::GetTableName () const inline
Definition at line 31 of file SQLStorage.h.
References m_tableName.
Referenced by ObjectMgr::LoadCreatureAddons().
Initialize()
void SQLStorageBase::Initialize (const char * tableName, const char * entry_field, const char * src_format, const char * dst_format) protected
Definition at line 36 of file SQLStorage.cpp.
References m_dst_format, m_dstFieldCount, m_entry_field, m_src_format, m_srcFieldCount, and m_tableName.
Referenced by SQLHashStorage::SQLHashStorage(), SQLMultiStorage::SQLMultiStorage(), and SQLStorage::SQLStorage().
JustCreatedRecord()
virtual void SQLStorageBase::JustCreatedRecord (uint32 recordId, char * record) protected pure virtual
Implemented in SQLMultiStorage, SQLHashStorage, and SQLStorage.
Referenced by createRecord().
prepareToLoad()
void SQLStorageBase::prepareToLoad (uint32 maxEntry, uint32 recordCount, uint32 recordSize) protected virtual
Reimplemented in SQLMultiStorage, SQLHashStorage, and SQLStorage.
Definition at line 56 of file SQLStorage.cpp.
References m_data, m_maxEntry, m_recordCount, and m_recordSize.
Referenced by SQLStorage::prepareToLoad(), SQLHashStorage::prepareToLoad(), and SQLMultiStorage::prepareToLoad().
Friends And Related Function Documentation
SQLStorageLoaderBase
template<class DerivedLoader , class StorageClass > friend class SQLStorageLoaderBase friend
Definition at line 28 of file SQLStorage.h.
Field Documentation
m_data
char* SQLStorageBase::m_data private
Definition at line 98 of file SQLStorage.h.
Referenced by createRecord(), Free(), getDataBegin(), getDataEnd(), and prepareToLoad().
m_dst_format
const char* SQLStorageBase::m_dst_format private
Definition at line 88 of file SQLStorage.h.
Referenced by Free(), GetDstFormat(), and Initialize().
m_dstFieldCount
uint32 SQLStorageBase::m_dstFieldCount private
Definition at line 91 of file SQLStorage.h.
Referenced by Free(), GetDstFieldCount(), and Initialize().
m_entry_field
const char* SQLStorageBase::m_entry_field private
Definition at line 86 of file SQLStorage.h.
Referenced by EntryFieldName(), and Initialize().
m_maxEntry
uint32 SQLStorageBase::m_maxEntry private
Definition at line 94 of file SQLStorage.h.
Referenced by GetMaxEntry(), and prepareToLoad().
m_recordCount
uint32 SQLStorageBase::m_recordCount private
Definition at line 93 of file SQLStorage.h.
Referenced by createRecord(), Free(), getDataEnd(), GetRecordCount(), and prepareToLoad().
m_recordSize
uint32 SQLStorageBase::m_recordSize private
Definition at line 95 of file SQLStorage.h.
Referenced by createRecord(), Free(), getDataBegin(), getDataEnd(), GetRecordSize(), and prepareToLoad().
m_src_format
const char* SQLStorageBase::m_src_format private
Definition at line 87 of file SQLStorage.h.
Referenced by GetSrcFormat(), and Initialize().
m_srcFieldCount
uint32 SQLStorageBase::m_srcFieldCount private
Definition at line 92 of file SQLStorage.h.
Referenced by GetSrcFieldCount(), and Initialize().
m_tableName
const char* SQLStorageBase::m_tableName private
Definition at line 85 of file SQLStorage.h.
Referenced by GetTableName(), and Initialize().
The documentation for this class was generated from the following files:
SQLStorage.h
SQLStorage.cpp