CMaNGOS_WoTLK: instance_azjol_nerub Class Reference
instance_azjol_nerub Class Reference
#include <azjol-nerub.h>
Public Member Functions
instance_azjol_nerub (Map *pMap)
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
ObjectGuid GetVenomancerTrigger () const
ObjectGuid GetDarterTrigger () const
void SetHadronoxDeniedAchievCriteria (bool bIsMet)
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoSendWatcherOrKrikthir ()
void ResetHadronoxTriggers ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
ObjectGuid m_playerGuid
ObjectGuid m_playerTriggerGuid [MAX_GAUNTLET_SPELLS]
ObjectGuid m_leftTargetTriggerGuid
ObjectGuid m_rightTargetTriggerGuid
GuidList m_lSpiderTriggersGuids
GuidList m_lCrusherGuids
ObjectGuid m_darterSummonTarget
ObjectGuid m_guardianSummonTarget
ObjectGuid m_venomancerSummonTarget
ObjectGuid m_anubSummonTarget
uint32 m_uiWatcherTimer
uint32 m_uiPeriodicAuraTimer
uint32 m_uiPeriodicAuraStage
uint32 m_uiSpiderSummonTimer
bool m_bWatchHimDie
bool m_bHadronoxDenied
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 117 of file azjol-nerub.h.
Constructor & Destructor Documentation
instance_azjol_nerub()
instance_azjol_nerub::instance_azjol_nerub (Map * pMap)
Definition at line 27 of file azjol-nerub.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_azjol_nerub::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 341 of file azjol-nerub.cpp.
References ACHIEV_CRITERIA_DENIED, ACHIEV_CRITERIA_WATCH_DIE, m_bHadronoxDenied, and m_bWatchHimDie.
DoSendWatcherOrKrikthir()
void instance_azjol_nerub::DoSendWatcherOrKrikthir () private
Definition at line 356 of file azjol-nerub.cpp.
References Creature::AI(), UnitAI::AttackStart(), aWatchers, DoScriptText(), Map::GetPlayer(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_playerGuid, NPC_KRIKTHIR, SAY_SEND_GROUP_1, SAY_SEND_GROUP_2, SAY_SEND_GROUP_3, and urand().
Referenced by Update().
GetDarterTrigger()
ObjectGuid instance_azjol_nerub::GetDarterTrigger () const inline
Definition at line 138 of file azjol-nerub.h.
References m_darterSummonTarget.
Referenced by boss_anubarakAI::UpdateAI().
GetData()
uint32 instance_azjol_nerub::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 333 of file azjol-nerub.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnCreatureEnterCombat().
GetVenomancerTrigger()
ObjectGuid instance_azjol_nerub::GetVenomancerTrigger () const inline
Definition at line 137 of file azjol-nerub.h.
References m_venomancerSummonTarget.
Referenced by boss_anubarakAI::UpdateAI().
Initialize()
void instance_azjol_nerub::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 38 of file azjol-nerub.cpp.
References m_auiEncounter.
Referenced by instance_azjol_nerub().
Load()
void instance_azjol_nerub::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 311 of file azjol-nerub.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_azjol_nerub::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 62 of file azjol-nerub.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_anubSummonTarget, m_darterSummonTarget, m_guardianSummonTarget, m_lCrusherGuids, m_leftTargetTriggerGuid, m_lSpiderTriggersGuids, ScriptedInstance::m_npcEntryGuidStore, m_rightTargetTriggerGuid, m_venomancerSummonTarget, NPC_ANUBAR_CRUSHER, NPC_ANUBARAK, NPC_GASHRA, NPC_HADRONOX, NPC_KRIKTHIR, NPC_NARJIL, NPC_SILTHIK, NPC_WORLD_TRIGGER, and NPC_WORLD_TRIGGER_LARGE.
OnCreatureDeath()
void instance_azjol_nerub::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 167 of file azjol-nerub.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_auiEncounter, m_bWatchHimDie, m_lCrusherGuids, m_uiWatcherTimer, NOT_STARTED, NPC_ANUBAR_CRUSHER, NPC_GASHRA, NPC_HADRONOX, NPC_NARJIL, NPC_SILTHIK, REACT_PASSIVE, and TYPE_KRIKTHIR.
OnCreatureEnterCombat()
void instance_azjol_nerub::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 198 of file azjol-nerub.cpp.
References DoScriptText(), EMOTE_MOVE_TUNNEL, AzjolNerubSummonData::entry, gauntletSummonData, Unit::GetBeneficiaryPlayer(), GetData(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::GetVictim(), IN_PROGRESS, Creature::IsTemporarySummon(), m_playerGuid, m_playerTriggerGuid, m_uiSpiderSummonTimer, MAX_GAUNTLET_SPAWNS, MAX_GAUNTLET_SPELLS, NPC_ANUBAR_CRUSHER, NPC_GASHRA, NPC_HADRONOX, NPC_NARJIL, NPC_SILTHIK, AzjolNerubSummonData::o, SAY_CRUSHER_AGGRO, SetData(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, triggerSummonData, TYPE_HADRONOX, AzjolNerubSummonData::x, AzjolNerubSummonData::y, and AzjolNerubSummonData::z.
OnCreatureEvade()
void instance_azjol_nerub::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 248 of file azjol-nerub.cpp.
References ObjectGuid::Clear(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), m_playerGuid, NPC_ANUBAR_ASSASSIN, NPC_ANUBAR_DARTER, NPC_ANUBAR_GUARDIAN, NPC_ANUBAR_VENOMANCER, NPC_ANUBARAK, NPC_GASHRA, NPC_NARJIL, and NPC_SILTHIK.
OnCreatureRespawn()
void instance_azjol_nerub::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 106 of file azjol-nerub.cpp.
References Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), Map::GetCreature(), Object::GetEntry(), Unit::GetMotionMaster(), Map::GetPlayer(), ScriptedInstance::GetPlayerInMap(), WorldObject::GetPositionX(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::GetSpeed(), InstanceData::instance, m_anubSummonTarget, m_playerGuid, MOVE_RUN, MotionMaster::MoveJump(), MotionMaster::MoveWaypoint(), NPC_ANUBAR_ASSASSIN, NPC_ANUBAR_CHAMPION_1, NPC_ANUBAR_CHAMPION_2, NPC_ANUBAR_CHAMPION_3, NPC_ANUBAR_CRYPT_FIEND_1, NPC_ANUBAR_CRYPT_FIEND_2, NPC_ANUBAR_CRYPT_FIEND_3, NPC_ANUBAR_DARTER, NPC_ANUBAR_GUARDIAN, NPC_ANUBAR_NECROMANCER_1, NPC_ANUBAR_NECROMANCER_2, NPC_ANUBAR_NECROMANCER_3, NPC_ANUBAR_VENOMANCER, NPC_HADRONOX, NPC_IMPALE_TARGET, NPC_WORLD_TRIGGER, NPC_WORLD_TRIGGER_LARGE, REACT_PASSIVE, Unit::SetCanEnterCombat(), Unit::SetLevitate(), UnitAI::SetReactState(), Creature::SetWalk(), SPELL_CHECK_RESET, and TRIGGERED_OLD_TRIGGERED.
OnObjectCreate()
void instance_azjol_nerub::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 43 of file azjol-nerub.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_DOOR_ANUBARAK_1, GO_DOOR_ANUBARAK_2, GO_DOOR_ANUBARAK_3, GO_DOOR_KRIKTHIR, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), and TYPE_KRIKTHIR.
ResetHadronoxTriggers()
void instance_azjol_nerub::ResetHadronoxTriggers () private
Definition at line 397 of file azjol-nerub.cpp.
References Map::GetCreature(), InstanceData::instance, m_lSpiderTriggersGuids, m_playerTriggerGuid, m_uiSpiderSummonTimer, MAX_GAUNTLET_SPELLS, SPELL_SUMMON_CHAMPION_S, SPELL_SUMMON_CRYPT_FIEND_S, and SPELL_SUMMON_NECROMANCER_S.
Referenced by SetData().
Save()
const char* instance_azjol_nerub::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 142 of file azjol-nerub.h.
References m_strInstData.
SetData()
void instance_azjol_nerub::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 267 of file azjol-nerub.cpp.
References ACHIEV_START_ANUB_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DONE, ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoUseDoorOrButton(), GO_DOOR_ANUBARAK_1, GO_DOOR_ANUBARAK_2, GO_DOOR_ANUBARAK_3, GO_DOOR_KRIKTHIR, IN_PROGRESS, m_auiEncounter, m_strInstData, m_uiPeriodicAuraStage, m_uiPeriodicAuraTimer, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, ResetHadronoxTriggers(), InstanceData::SaveToDB(), SPECIAL, TYPE_ANUBARAK, TYPE_HADRONOX, and TYPE_KRIKTHIR.
Referenced by boss_anubarakAI::Aggro(), boss_anubarakAI::JustDied(), boss_hadronoxAI::JustDied(), boss_krikthirAI::JustDied(), boss_anubarakAI::JustReachedHome(), boss_hadronoxAI::MovementInform(), and OnCreatureEnterCombat().
SetHadronoxDeniedAchievCriteria()
void instance_azjol_nerub::SetHadronoxDeniedAchievCriteria (bool bIsMet) inline
Definition at line 140 of file azjol-nerub.h.
References m_bHadronoxDenied.
Referenced by boss_hadronoxAI::MovementInform().
Update()
void instance_azjol_nerub::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 419 of file azjol-nerub.cpp.
References aPlayerSummonSpells, aSpiderSummonSpells, DoSendWatcherOrKrikthir(), Map::GetCreature(), InstanceData::instance, m_lSpiderTriggersGuids, m_playerTriggerGuid, m_uiPeriodicAuraStage, m_uiPeriodicAuraTimer, m_uiSpiderSummonTimer, m_uiWatcherTimer, MAX_GAUNTLET_SPELLS, and TRIGGERED_OLD_TRIGGERED.
Field Documentation
m_anubSummonTarget
ObjectGuid instance_azjol_nerub::m_anubSummonTarget private
Definition at line 167 of file azjol-nerub.h.
Referenced by OnCreatureCreate(), and OnCreatureRespawn().
m_auiEncounter
uint32 instance_azjol_nerub::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 151 of file azjol-nerub.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureDeath(), OnObjectCreate(), and SetData().
m_bHadronoxDenied
bool instance_azjol_nerub::m_bHadronoxDenied private
Definition at line 175 of file azjol-nerub.h.
Referenced by CheckAchievementCriteriaMeet(), and SetHadronoxDeniedAchievCriteria().
m_bWatchHimDie
bool instance_azjol_nerub::m_bWatchHimDie private
Definition at line 174 of file azjol-nerub.h.
Referenced by CheckAchievementCriteriaMeet(), and OnCreatureDeath().
m_darterSummonTarget
ObjectGuid instance_azjol_nerub::m_darterSummonTarget private
Definition at line 164 of file azjol-nerub.h.
Referenced by GetDarterTrigger(), and OnCreatureCreate().
m_guardianSummonTarget
ObjectGuid instance_azjol_nerub::m_guardianSummonTarget private
Definition at line 165 of file azjol-nerub.h.
Referenced by OnCreatureCreate().
m_lCrusherGuids
GuidList instance_azjol_nerub::m_lCrusherGuids private
Definition at line 161 of file azjol-nerub.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_leftTargetTriggerGuid
ObjectGuid instance_azjol_nerub::m_leftTargetTriggerGuid private
Definition at line 158 of file azjol-nerub.h.
Referenced by OnCreatureCreate().
m_lSpiderTriggersGuids
GuidList instance_azjol_nerub::m_lSpiderTriggersGuids private
Definition at line 160 of file azjol-nerub.h.
Referenced by OnCreatureCreate(), ResetHadronoxTriggers(), and Update().
m_playerGuid
ObjectGuid instance_azjol_nerub::m_playerGuid private
Definition at line 154 of file azjol-nerub.h.
Referenced by DoSendWatcherOrKrikthir(), OnCreatureEnterCombat(), OnCreatureEvade(), and OnCreatureRespawn().
m_playerTriggerGuid
ObjectGuid instance_azjol_nerub::m_playerTriggerGuid[MAX_GAUNTLET_SPELLS] private
Definition at line 157 of file azjol-nerub.h.
Referenced by OnCreatureEnterCombat(), ResetHadronoxTriggers(), and Update().
m_rightTargetTriggerGuid
ObjectGuid instance_azjol_nerub::m_rightTargetTriggerGuid private
Definition at line 159 of file azjol-nerub.h.
Referenced by OnCreatureCreate().
m_strInstData
std::string instance_azjol_nerub::m_strInstData private
Definition at line 152 of file azjol-nerub.h.
Referenced by Save(), and SetData().
m_uiPeriodicAuraStage
uint32 instance_azjol_nerub::m_uiPeriodicAuraStage private
Definition at line 171 of file azjol-nerub.h.
Referenced by SetData(), and Update().
m_uiPeriodicAuraTimer
uint32 instance_azjol_nerub::m_uiPeriodicAuraTimer private
Definition at line 170 of file azjol-nerub.h.
Referenced by SetData(), and Update().
m_uiSpiderSummonTimer
uint32 instance_azjol_nerub::m_uiSpiderSummonTimer private
Definition at line 172 of file azjol-nerub.h.
Referenced by OnCreatureEnterCombat(), ResetHadronoxTriggers(), and Update().
m_uiWatcherTimer
uint32 instance_azjol_nerub::m_uiWatcherTimer private
Definition at line 169 of file azjol-nerub.h.
Referenced by OnCreatureDeath(), and Update().
m_venomancerSummonTarget
ObjectGuid instance_azjol_nerub::m_venomancerSummonTarget private
Definition at line 166 of file azjol-nerub.h.
Referenced by GetVenomancerTrigger(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
azjol-nerub.h
azjol-nerub.cpp