CMaNGOS_WoTLK: CooldownContainer Class Reference
CooldownContainer Class Reference
#include <Object.h>
Public Types
typedef std::map< uint32, CooldownDataUPTR > spellIdMap
typedef spellIdMap::const_iterator ConstIterator
typedef spellIdMap::iterator Iterator
typedef std::map< uint32, ConstIterator > categoryMap
Public Member Functions
void Update (TimePoint const &now)
bool AddCooldown (TimePoint clockNow, uint32 spellId, uint32 duration, uint32 spellCategory=0, uint32 categoryDuration=0, uint32 itemId=0, bool onHold=false)
void RemoveBySpellId (uint32 spellId)
void RemoveByCategory (uint32 category)
Iterator erase (ConstIterator spellCDItr)
ConstIterator FindBySpellId (uint32 id) const
ConstIterator FindByCategory (uint32 category) const
void clear ()
ConstIterator begin () const
ConstIterator end () const
bool IsEmpty () const
size_t size () const
Private Attributes
spellIdMap m_spellIdMap
categoryMap m_categoryMap
Detailed Description
Definition at line 217 of file Object.h.
Member Typedef Documentation
categoryMap
typedef std::map<uint32, ConstIterator> CooldownContainer::categoryMap
Definition at line 223 of file Object.h.
ConstIterator
typedef spellIdMap::const_iterator CooldownContainer::ConstIterator
Definition at line 221 of file Object.h.
Iterator
typedef spellIdMap::iterator CooldownContainer::Iterator
Definition at line 222 of file Object.h.
spellIdMap
typedef std::map<uint32, CooldownDataUPTR> CooldownContainer::spellIdMap
Definition at line 220 of file Object.h.
Member Function Documentation
AddCooldown()
bool CooldownContainer::AddCooldown (TimePoint clockNow, uint32 spellId, uint32 duration, uint32 spellCategory = 0, uint32 categoryDuration = 0, uint32 itemId = 0, bool onHold = false) inline
Definition at line 245 of file Object.h.
References FindByCategory(), m_categoryMap, m_spellIdMap, and RemoveBySpellId().
Referenced by Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), WorldObject::AddCooldown(), Creature::AddCooldown(), and Player::AddCooldown().
begin()
ConstIterator CooldownContainer::begin () const inline
Definition at line 320 of file Object.h.
References m_spellIdMap.
Referenced by Player::ModifyCooldown(), Player::RemoveAllCooldowns(), and Player::RemoveSomeCooldown().
clear()
void CooldownContainer::clear () inline
Definition at line 318 of file Object.h.
References m_categoryMap, and m_spellIdMap.
Referenced by WorldObject::RemoveAllCooldowns().
end()
ConstIterator CooldownContainer::end () const inline
Definition at line 321 of file Object.h.
References m_spellIdMap.
Referenced by Player::AddCooldown(), FindByCategory(), WorldObject::GetExpireTime(), WorldObject::HasGCDOrCooldownWithinMargin(), WorldObject::IsSpellOnPermanentCooldown(), WorldObject::IsSpellReady(), Player::ModifyCooldown(), Player::RemoveAllCooldowns(), Player::RemoveSomeCooldown(), and Player::RemoveSpellCategoryCooldown().
erase()
Iterator CooldownContainer::erase (ConstIterator spellCDItr) inline
Definition at line 298 of file Object.h.
References m_categoryMap, and m_spellIdMap.
Referenced by Player::AddCooldown(), Player::ModifyCooldown(), Player::RemoveAllCooldowns(), Player::RemoveSomeCooldown(), Player::RemoveSpellCategoryCooldown(), and Update().
FindByCategory()
ConstIterator CooldownContainer::FindByCategory (uint32 category) const inline
Definition at line 312 of file Object.h.
References end(), and m_categoryMap.
Referenced by Player::AddCooldown(), AddCooldown(), WorldObject::HasGCDOrCooldownWithinMargin(), WorldObject::IsSpellReady(), and Player::RemoveSpellCategoryCooldown().
FindBySpellId()
ConstIterator CooldownContainer::FindBySpellId (uint32 id) const inline
Definition at line 310 of file Object.h.
References m_spellIdMap.
Referenced by Player::AddCooldown(), WorldObject::GetExpireTime(), WorldObject::HasGCDOrCooldownWithinMargin(), WorldObject::IsSpellOnPermanentCooldown(), and WorldObject::IsSpellReady().
IsEmpty()
bool CooldownContainer::IsEmpty () const inline
Definition at line 322 of file Object.h.
References m_spellIdMap.
RemoveByCategory()
void CooldownContainer::RemoveByCategory (uint32 category) inline
Definition at line 288 of file Object.h.
References m_categoryMap.
Referenced by WorldObject::RemoveSpellCategoryCooldown().
RemoveBySpellId()
void CooldownContainer::RemoveBySpellId (uint32 spellId) inline
Definition at line 272 of file Object.h.
References m_categoryMap, and m_spellIdMap.
Referenced by AddCooldown(), WorldObject::RemoveSpellCooldown(), and Player::RemoveSpellCooldown().
size()
size_t CooldownContainer::size () const inline
Definition at line 323 of file Object.h.
References m_spellIdMap.
Referenced by Player::SendInitialSpells().
Update()
void CooldownContainer::Update (TimePoint const & now) inline
Definition at line 225 of file Object.h.
References erase(), m_categoryMap, and m_spellIdMap.
Referenced by WorldObject::UpdateCooldowns().
Field Documentation
m_categoryMap
categoryMap CooldownContainer::m_categoryMap private
Definition at line 327 of file Object.h.
Referenced by AddCooldown(), clear(), erase(), FindByCategory(), RemoveByCategory(), RemoveBySpellId(), and Update().
m_spellIdMap
spellIdMap CooldownContainer::m_spellIdMap private
Definition at line 326 of file Object.h.
Referenced by AddCooldown(), begin(), clear(), end(), erase(), FindBySpellId(), IsEmpty(), RemoveBySpellId(), size(), and Update().
The documentation for this class was generated from the following file:
Object.h