CMaNGOS_WoTLK: ScriptMgr Class Reference
ScriptMgr Class Reference
#include <ScriptMgr.h>
Public Types
typedef std::pair< int32, uint32 > ScriptTemplatePair
typedef std::vector< ScriptTemplatePair > ScriptTemplateVector
Public Member Functions
ScriptMgr ()
~ScriptMgr ()
void LoadScriptMap (ScriptMapType scriptType, bool reload=false)
void LoadStringIds (bool reload=false)
void LoadDbScriptStrings ()
void LoadDbScriptRandomTemplates ()
void CheckRandomStringTemplates (std::set< int32 > &ids)
void CheckRandomRelayTemplates ()
bool CheckScriptStringTemplateId (uint32 id) const
bool CheckScriptRelayTemplateId (uint32 id) const
void GetScriptStringTemplate (uint32 id, ScriptTemplateVector &stringTemplate)
void GetScriptRelayTemplate (uint32 id, ScriptTemplateVector &stringTemplate)
int32 GetRandomScriptTemplateId (uint32 id, uint8 templateType)
int32 GetRandomScriptStringFromTemplate (uint32 id)
int32 GetRandomRelayDbscriptFromTemplate (uint32 id)
std::shared_ptr< ScriptMapMapName > GetScriptMap (ScriptMapType scriptMapType)
bool ExistsStringId (uint32 stringId)
std::shared_ptr< StringIdMap > GetStringIdMap ()
std::shared_ptr< StringIdMapByString > GetStringIdByStringMap ()
Static Public Member Functions
static bool CanSpellEffectStartDBScript (SpellEntry const *spellinfo, SpellEffectIndex effIdx)
static void CollectPossibleEventIds (std::set< uint32 > &eventIds)
Private Types
enum RandomTemplates { STRING_TEMPLATE = 0 , RELAY_TEMPLATE = 1 , MAX_TYPE }
typedef std::vector< std::string > ScriptNameMap
typedef std::unordered_map< uint32, uint32 > AreaTriggerScriptMap
typedef std::unordered_map< uint32, uint32 > EventIdScriptMap
typedef std::unordered_map< uint32, ScriptTemplateVector > ScriptTemplateMap
Private Member Functions
void LoadScripts (ScriptMapType scriptType)
void CheckScriptTexts (ScriptMapType scriptType)
Private Attributes
AreaTriggerScriptMap m_AreaTriggerScripts
EventIdScriptMap m_EventIdScripts
ScriptTemplateMap m_scriptTemplates [MAX_TYPE]
ScriptTemplateMap m_scriptTemplatesEquallyChanced [MAX_TYPE]
ScriptTemplateMap m_scriptTemplatesExplicitlyChanced [MAX_TYPE]
ScriptNameMap m_scriptNames
std::shared_ptr< ScriptMapMapName > m_scriptMaps [SCRIPT_TYPE_MAX]
std::shared_ptr< StringIdMap > m_stringIds
std::shared_ptr< StringIdMapByString > m_stringIdsByString
Detailed Description
Definition at line 653 of file ScriptMgr.h.
Member Typedef Documentation
AreaTriggerScriptMap
typedef std::unordered_map<uint32, uint32> ScriptMgr::AreaTriggerScriptMap private
Definition at line 699 of file ScriptMgr.h.
EventIdScriptMap
typedef std::unordered_map<uint32, uint32> ScriptMgr::EventIdScriptMap private
Definition at line 700 of file ScriptMgr.h.
ScriptNameMap
typedef std::vector<std::string> ScriptMgr::ScriptNameMap private
Definition at line 698 of file ScriptMgr.h.
ScriptTemplateMap
typedef std::unordered_map<uint32, ScriptTemplateVector> ScriptMgr::ScriptTemplateMap private
Definition at line 701 of file ScriptMgr.h.
ScriptTemplatePair
typedef std::pair<int32, uint32> ScriptMgr::ScriptTemplatePair
Definition at line 677 of file ScriptMgr.h.
ScriptTemplateVector
typedef std::vector<ScriptTemplatePair> ScriptMgr::ScriptTemplateVector
Definition at line 678 of file ScriptMgr.h.
Member Enumeration Documentation
RandomTemplates
enum ScriptMgr::RandomTemplates private
Enumerator
STRING_TEMPLATE
RELAY_TEMPLATE
MAX_TYPE
Definition at line 655 of file ScriptMgr.h.
Constructor & Destructor Documentation
ScriptMgr()
ScriptMgr::ScriptMgr ()
Definition at line 58 of file ScriptMgr.cpp.
~ScriptMgr()
ScriptMgr::~ScriptMgr () inline
Definition at line 664 of file ScriptMgr.h.
Member Function Documentation
CanSpellEffectStartDBScript()
bool ScriptMgr::CanSpellEffectStartDBScript (SpellEntry const * spellinfo, SpellEffectIndex effIdx) static
Definition at line 87 of file ScriptMgr.cpp.
References GetSpellStartDBScriptPriority(), and MAX_EFFECT_INDEX.
Referenced by Spell::EffectDummy(), Spell::EffectScriptEffect(), and Spell::EffectTriggerSpell().
CheckRandomRelayTemplates()
void ScriptMgr::CheckRandomRelayTemplates ()
Definition at line 1236 of file ScriptMgr.cpp.
References GetScriptMap(), m_scriptTemplates, RELAY_TEMPLATE, SCRIPT_TYPE_RELAY, and sLog.
Referenced by LoadScriptMap().
CheckRandomStringTemplates()
void ScriptMgr::CheckRandomStringTemplates (std::set< int32 > & ids)
Definition at line 1228 of file ScriptMgr.cpp.
References m_scriptTemplates, and STRING_TEMPLATE.
CheckScriptRelayTemplateId()
bool ScriptMgr::CheckScriptRelayTemplateId (uint32 id) const inline
Definition at line 676 of file ScriptMgr.h.
References m_scriptTemplates, and RELAY_TEMPLATE.
CheckScriptStringTemplateId()
bool ScriptMgr::CheckScriptStringTemplateId (uint32 id) const inline
Definition at line 675 of file ScriptMgr.h.
References m_scriptTemplates, and STRING_TEMPLATE.
CheckScriptTexts()
void ScriptMgr::CheckScriptTexts (ScriptMapType scriptType) private
Definition at line 1245 of file ScriptMgr.cpp.
References GetScriptMap(), m_scriptTemplates, SCRIPT_COMMAND_TALK, sLog, sObjectMgr, and STRING_TEMPLATE.
Referenced by LoadDbScriptStrings().
CollectPossibleEventIds()
void ScriptMgr::CollectPossibleEventIds (std::set< uint32 > & eventIds) static
Definition at line 3296 of file ScriptMgr.cpp.
References TaxiPathNodeEntry::arrivalEventID, TaxiPathNodeEntry::departureEventID, SpellEntry::Effect, SpellEntry::EffectMiscValue, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CAPTURE_POINT, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_GOOBER, SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetMaxEntry(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, sGOStorage, SPELL_EFFECT_SEND_EVENT, sSpellTemplate, and sTaxiPathNodesByPath.
Referenced by ScriptDevAIMgr::LoadEventIdScripts(), and LoadScriptMap().
ExistsStringId()
bool ScriptMgr::ExistsStringId (uint32 stringId)
Definition at line 3413 of file ScriptMgr.cpp.
References m_stringIds.
Referenced by LoadScripts().
GetRandomRelayDbscriptFromTemplate()
int32 ScriptMgr::GetRandomRelayDbscriptFromTemplate (uint32 id)
Definition at line 3287 of file ScriptMgr.cpp.
References GetRandomScriptTemplateId(), and RELAY_TEMPLATE.
GetRandomScriptStringFromTemplate()
int32 ScriptMgr::GetRandomScriptStringFromTemplate (uint32 id)
Definition at line 3282 of file ScriptMgr.cpp.
References GetRandomScriptTemplateId(), and STRING_TEMPLATE.
GetRandomScriptTemplateId()
int32 ScriptMgr::GetRandomScriptTemplateId (uint32 id, uint8 templateType)
Definition at line 3255 of file ScriptMgr.cpp.
References m_scriptTemplates, m_scriptTemplatesEquallyChanced, m_scriptTemplatesExplicitlyChanced, rand_chance(), and urand().
Referenced by GetRandomRelayDbscriptFromTemplate(), and GetRandomScriptStringFromTemplate().
GetScriptMap()
std::shared_ptr< ScriptMapMapName > ScriptMgr::GetScriptMap (ScriptMapType scriptMapType)
Definition at line 3367 of file ScriptMgr.cpp.
References m_scriptMaps.
Referenced by CheckRandomRelayTemplates(), CheckScriptTexts(), LoadScriptMap(), and LoadScripts().
GetScriptRelayTemplate()
void ScriptMgr::GetScriptRelayTemplate (uint32 id, ScriptTemplateVector & stringTemplate) inline
Definition at line 680 of file ScriptMgr.h.
References m_scriptTemplates, and RELAY_TEMPLATE.
GetScriptStringTemplate()
void ScriptMgr::GetScriptStringTemplate (uint32 id, ScriptTemplateVector & stringTemplate) inline
Definition at line 679 of file ScriptMgr.h.
References m_scriptTemplates, and STRING_TEMPLATE.
GetStringIdByStringMap()
std::shared_ptr<StringIdMapByString> ScriptMgr::GetStringIdByStringMap () inline
Definition at line 693 of file ScriptMgr.h.
References m_stringIdsByString.
GetStringIdMap()
std::shared_ptr<StringIdMap> ScriptMgr::GetStringIdMap () inline
Definition at line 692 of file ScriptMgr.h.
References m_stringIds.
LoadDbScriptRandomTemplates()
void ScriptMgr::LoadDbScriptRandomTemplates ()
Definition at line 1197 of file ScriptMgr.cpp.
References QueryResult::Fetch(), Field::GetInt32(), Field::GetUInt32(), m_scriptTemplates, m_scriptTemplatesEquallyChanced, m_scriptTemplatesExplicitlyChanced, MAX_TYPE, QueryResult::NextRow(), Database::Query(), sLog, and WorldDatabase.
LoadDbScriptStrings()
void ScriptMgr::LoadDbScriptStrings ()
Definition at line 1183 of file ScriptMgr.cpp.
References CheckScriptTexts(), SCRIPT_TYPE_CREATURE_DEATH, SCRIPT_TYPE_CREATURE_MOVEMENT, SCRIPT_TYPE_EVENT, SCRIPT_TYPE_GAMEOBJECT, SCRIPT_TYPE_GAMEOBJECT_TEMPLATE, SCRIPT_TYPE_GOSSIP, SCRIPT_TYPE_QUEST_END, SCRIPT_TYPE_QUEST_START, SCRIPT_TYPE_RELAY, and SCRIPT_TYPE_SPELL.
LoadScriptMap()
void ScriptMgr::LoadScriptMap (ScriptMapType scriptType, bool reload = false)
Definition at line 971 of file ScriptMgr.cpp.
References CheckRandomRelayTemplates(), CollectPossibleEventIds(), Map::GetMapDataContainer(), Map::GetMessager(), GetScriptMap(), GetSpellStartDBScriptPriority(), LoadScripts(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, SCRIPT_COMMAND_START_RELAY_SCRIPT, SCRIPT_TYPE_CREATURE_DEATH, SCRIPT_TYPE_CREATURE_MOVEMENT, SCRIPT_TYPE_EVENT, SCRIPT_TYPE_GAMEOBJECT, SCRIPT_TYPE_GAMEOBJECT_TEMPLATE, SCRIPT_TYPE_GOSSIP, SCRIPT_TYPE_QUEST_END, SCRIPT_TYPE_QUEST_START, SCRIPT_TYPE_RELAY, SCRIPT_TYPE_SPELL, sLog, sMapMgr, sObjectMgr, SPELL_EFFECT_SEND_EVENT, and sSpellTemplate.
LoadScripts()
void ScriptMgr::LoadScripts (ScriptMapType scriptType) private
Definition at line 107 of file ScriptMgr.cpp.
References ScriptInfo::buddyEntry, ScriptInfo::castSpell, ScriptInfo::command, ScriptInfo::condition_id, ScriptInfo::createItem, CURRENT_MAX_SPELL, ScriptInfo::data_flags, DEFAULT_VISIBILITY_DISTANCE, ScriptInfo::delay, EFFECT_MOTION_TYPE, ScriptInfo::emote, ExistsStringId(), ScriptInfo::faction, FALL_MOTION_TYPE, FORCED_MOVEMENT_FLIGHT, ScriptInfo::formationData, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, ObjectMgr::GetCreatureTemplate(), Field::GetFloat(), ObjectMgr::GetGameObjectInfo(), ScriptInfo::GetGOGuid(), Field::GetInt32(), ObjectMgr::GetItemPrototype(), SQLStorageBase::GetMaxEntry(), GetScriptMap(), Field::GetUInt32(), ScriptInfo::goLockState, ScriptInfo::HasAdditionalScriptFlag(), Quest::HasSpecialFlag(), ScriptInfo::id, GameObjectInfo::id, GameObjectData::id, INTERACTION_DISTANCE, ScriptInfo::interruptSpell, ScriptInfo::IsCreatureBuddy(), MaNGOS::IsValidMapCoord(), ScriptInfo::killCredit, LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), m_scriptMaps, MAX_DB_MOTION_TYPE, MAX_EFFECT_INDEX, MAX_SCRIPT_FLAG_VALID, MAX_TEXT_ID, MAX_UNIT_STAND_STATE, ScriptInfo::morph, ScriptInfo::mount, ScriptInfo::moveDynamic, ScriptInfo::movement, ScriptInfo::npcFlag, ScriptInfo::o, ScriptInfo::playMovie, ScriptInfo::playSound, Database::PQuery(), QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT, ScriptInfo::questExplored, ScriptInfo::raw, ScriptInfo::rawFloat, ScriptInfo::relayScript, ScriptInfo::removeAura, sConditionStorage, sCreatureDisplayInfoStore, sCreatureStorage, SCRIPT_COMMAND_ACTIVATE_OBJECT, SCRIPT_COMMAND_ATTACK_START, SCRIPT_COMMAND_CAST_CUSTOM_SPELL, SCRIPT_COMMAND_CAST_SPELL, SCRIPT_COMMAND_CLOSE_DOOR, SCRIPT_COMMAND_CREATE_ITEM, SCRIPT_COMMAND_DESPAWN_GO, SCRIPT_COMMAND_DESPAWN_SELF, SCRIPT_COMMAND_EMOTE, SCRIPT_COMMAND_FIELD_SET, SCRIPT_COMMAND_FLAG_REMOVE, SCRIPT_COMMAND_FLAG_SET, SCRIPT_COMMAND_GO_LOCK_STATE, SCRIPT_COMMAND_INTERRUPT_SPELL, SCRIPT_COMMAND_KILL_CREDIT, SCRIPT_COMMAND_MODIFY_NPC_FLAGS, SCRIPT_COMMAND_MODIFY_UNIT_FLAGS, SCRIPT_COMMAND_MORPH_TO_ENTRY_OR_MODEL, SCRIPT_COMMAND_MOUNT_TO_ENTRY_OR_MODEL, SCRIPT_COMMAND_MOVE_DYNAMIC, SCRIPT_COMMAND_MOVE_TO, SCRIPT_COMMAND_MOVEMENT, SCRIPT_COMMAND_OPEN_DOOR, SCRIPT_COMMAND_PAUSE_WAYPOINTS, SCRIPT_COMMAND_PLAY_MOVIE, SCRIPT_COMMAND_PLAY_SOUND, SCRIPT_COMMAND_QUEST_EXPLORED, SCRIPT_COMMAND_REMOVE_AURA, SCRIPT_COMMAND_RESET_GO, SCRIPT_COMMAND_RESPAWN, SCRIPT_COMMAND_RESPAWN_GAMEOBJECT, SCRIPT_COMMAND_SEND_AI_EVENT, SCRIPT_COMMAND_SEND_MAIL, SCRIPT_COMMAND_SEND_TAXI_PATH, SCRIPT_COMMAND_SET_ACTIVEOBJECT, SCRIPT_COMMAND_SET_DATA_64, SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS, SCRIPT_COMMAND_SET_FACING, SCRIPT_COMMAND_SET_FACTION, SCRIPT_COMMAND_SET_GOSSIP_MENU, SCRIPT_COMMAND_SET_HOVER, SCRIPT_COMMAND_SET_RUN, SCRIPT_COMMAND_SET_SHEATHE, SCRIPT_COMMAND_SET_STRING_ID, SCRIPT_COMMAND_SET_WORLDSTATE, SCRIPT_COMMAND_SPAWN_GROUP, SCRIPT_COMMAND_STAND_STATE, SCRIPT_COMMAND_START_RELAY_SCRIPT, SCRIPT_COMMAND_TALK, SCRIPT_COMMAND_TELEPORT_TO, SCRIPT_COMMAND_TEMP_SPAWN_CREATURE, SCRIPT_COMMAND_TERMINATE_COND, SCRIPT_COMMAND_TERMINATE_SCRIPT, SCRIPT_COMMAND_UPDATE_TEMPLATE, SCRIPT_COMMAND_XP_USER, SCRIPT_COMMAND_ZONE_PULSE, SCRIPT_FLAG_BUDDY_AS_TARGET, SCRIPT_FLAG_BUDDY_BY_GO, SCRIPT_FLAG_BUDDY_BY_GUID, SCRIPT_FLAG_BUDDY_BY_POOL, SCRIPT_FLAG_BUDDY_BY_SPAWN_GROUP, SCRIPT_FLAG_BUDDY_BY_STRING_ID, SCRIPT_FLAG_COMMAND_ADDITIONAL, SCRIPT_TYPE_RELAY, scriptTableNames, ScriptInfo::searchRadiusOrGuid, sEmotesStore, ScriptInfo::sendMail, ScriptInfo::sendTaxiPath, ScriptInfo::setSheathe, sFactionTemplateStore, SHEATH_STATE_RANGED, sLog, sMailTemplateStore, sMapStore, sMovieStore, sObjectMgr, SPAWN_GROUP_FORMATION_TYPE_COUNT, ScriptInfo::speed, SPELL_EFFECT_SEND_TAXI, sPoolMgr, sScriptMgr, sSoundEntriesStore, sSpellTemplate, ScriptInfo::standState, sTaxiPathStore, BarGoLink::step(), ScriptInfo::stringId, ScriptInfo::summonCreature, ScriptInfo::talk, ScriptInfo::teleportTo, ScriptInfo::terminateCond, ScriptInfo::terminateScript, ScriptInfo::textId, GameObjectInfo::type, ScriptInfo::unitFlag, ScriptInfo::updateTemplate, WorldDatabase, ScriptInfo::x, ScriptInfo::y, and ScriptInfo::z.
Referenced by LoadScriptMap().
LoadStringIds()
void ScriptMgr::LoadStringIds (bool reload = false)
Definition at line 1131 of file ScriptMgr.cpp.
References Field::GetCppString(), Field::GetInt32(), Map::GetMapDataContainer(), Map::GetMessager(), StringId::Id, m_stringIds, m_stringIdsByString, StringId::Name, Database::Query(), sLog, sMapMgr, BarGoLink::step(), and WorldDatabase.
Field Documentation
m_AreaTriggerScripts
AreaTriggerScriptMap ScriptMgr::m_AreaTriggerScripts private
Definition at line 703 of file ScriptMgr.h.
m_EventIdScripts
EventIdScriptMap ScriptMgr::m_EventIdScripts private
Definition at line 704 of file ScriptMgr.h.
m_scriptMaps
std::shared_ptr<ScriptMapMapName> ScriptMgr::m_scriptMaps[SCRIPT_TYPE_MAX] private
Definition at line 711 of file ScriptMgr.h.
Referenced by GetScriptMap(), and LoadScripts().
m_scriptNames
ScriptNameMap ScriptMgr::m_scriptNames private
Definition at line 709 of file ScriptMgr.h.
m_scriptTemplates
ScriptTemplateMap ScriptMgr::m_scriptTemplates[MAX_TYPE] private
Definition at line 706 of file ScriptMgr.h.
Referenced by CheckRandomRelayTemplates(), CheckRandomStringTemplates(), CheckScriptRelayTemplateId(), CheckScriptStringTemplateId(), CheckScriptTexts(), GetRandomScriptTemplateId(), GetScriptRelayTemplate(), GetScriptStringTemplate(), and LoadDbScriptRandomTemplates().
m_scriptTemplatesEquallyChanced
ScriptTemplateMap ScriptMgr::m_scriptTemplatesEquallyChanced[MAX_TYPE] private
Definition at line 707 of file ScriptMgr.h.
Referenced by GetRandomScriptTemplateId(), and LoadDbScriptRandomTemplates().
m_scriptTemplatesExplicitlyChanced
ScriptTemplateMap ScriptMgr::m_scriptTemplatesExplicitlyChanced[MAX_TYPE] private
Definition at line 708 of file ScriptMgr.h.
Referenced by GetRandomScriptTemplateId(), and LoadDbScriptRandomTemplates().
m_stringIds
std::shared_ptr<StringIdMap> ScriptMgr::m_stringIds private
Definition at line 714 of file ScriptMgr.h.
Referenced by ExistsStringId(), GetStringIdMap(), and LoadStringIds().
m_stringIdsByString
std::shared_ptr<StringIdMapByString> ScriptMgr::m_stringIdsByString private
Definition at line 715 of file ScriptMgr.h.
Referenced by GetStringIdByStringMap(), and LoadStringIds().
The documentation for this class was generated from the following files:
ScriptMgr.h
ScriptMgr.cpp