CMaNGOS_WoTLK: GameEventMgr Class Reference
GameEventMgr Class Reference
#include <GameEventMgr.h>
Public Types
typedef std::set< uint16 > ActiveEvents
typedef std::vector< GameEventData > GameEventDataMap
Public Member Functions
GameEventMgr ()
~GameEventMgr ()
ActiveEvents const & GetActiveEventList () const
GameEventDataMap const & GetEventMap () const
bool CheckOneGameEvent (uint16 entry, time_t currenttime) const
uint32 NextCheck (uint16 entry) const
void LoadFromDB ()
void Initialize (MapPersistentState *state)
uint32 Update (ActiveEvents const *activeAtShutdown=nullptr)
bool IsValidEvent (uint16 event_id) const
bool IsActiveEvent (uint16 event_id) const
bool IsActiveHoliday (HolidayIds id) const
uint32 Initialize ()
void StartEvent (uint16 event_id, bool overwrite=false, bool resume=false)
void StopEvent (uint16 event_id, bool overwrite=false)
template<typename T >
int16 GetGameEventId (uint32 guid_or_poolid)
std::unordered_map< uint32, std::vector< uint32 > > const & GetEventGroups () const
GameEventCreatureData const * GetCreatureUpdateDataForActiveEvent (uint32 dbGuid) const
void WeeklyEventTimerRecalculation ()
template<>
int16 GetGameEventId (uint32 guid_or_poolid)
template<>
int16 GetGameEventId (uint32 guid_or_poolid)
template<>
int16 GetGameEventId (uint32 guid_or_poolid)
Protected Types
typedef std::list< uint32 > GuidList
typedef std::list< uint16 > IdList
typedef std::vector< GuidList > GameEventGuidMap
typedef std::vector< IdList > GameEventIdMap
typedef std::list< GameEventCreatureDataPair > GameEventCreatureDataList
typedef std::vector< GameEventCreatureDataList > GameEventCreatureDataMap
typedef std::multimap< uint32, uint32 > GameEventCreatureDataPerGuidMap
typedef std::pair< GameEventCreatureDataPerGuidMap::const_iterator, GameEventCreatureDataPerGuidMap::const_iterator > GameEventCreatureDataPerGuidBounds
typedef std::list< uint32 > QuestList
typedef std::vector< QuestList > GameEventQuestMap
typedef std::list< GameEventMail > MailList
typedef std::vector< MailList > GameEventMailMap
Protected Attributes
GameEventQuestMap m_gameEventQuests
GameEventCreatureDataMap m_gameEventCreatureData
GameEventCreatureDataPerGuidMap m_gameEventCreatureDataPerGuid
GameEventMailMap m_gameEventMails
GameEventGuidMap m_gameEventCreatureGuids
GameEventGuidMap m_gameEventGameobjectGuids
GameEventIdMap m_gameEventSpawnPoolIds
GameEventDataMap m_gameEvents
ActiveEvents m_activeEvents
bool m_isGameEventsInit
std::unordered_map< uint32, std::vector< uint32 > > m_gameEventGroups
Private Member Functions
void ApplyNewEvent (uint16 event_id, bool resume)
void UnApplyEvent (uint16 event_id)
void GameEventSpawn (int16 event_id)
void GameEventUnspawn (int16 event_id)
void UpdateCreatureData (int16 event_id, bool activate)
void UpdateEventQuests (uint16 event_id, bool Activate)
void UpdateWorldStates (uint16 event_id, bool Activate)
void SendEventMails (int16 event_id)
void OnEventHappened (uint16 event_id, bool activate, bool resume)
void ComputeEventStartAndEndTime (GameEventData &data, time_t today)
Detailed Description
Definition at line 93 of file GameEventMgr.h.
Member Typedef Documentation
ActiveEvents
typedef std::set<uint16> GameEventMgr::ActiveEvents
Definition at line 98 of file GameEventMgr.h.
GameEventCreatureDataList
typedef std::list<GameEventCreatureDataPair> GameEventMgr::GameEventCreatureDataList protected
Definition at line 137 of file GameEventMgr.h.
GameEventCreatureDataMap
typedef std::vector<GameEventCreatureDataList> GameEventMgr::GameEventCreatureDataMap protected
Definition at line 138 of file GameEventMgr.h.
GameEventCreatureDataPerGuidBounds
typedef std::pair<GameEventCreatureDataPerGuidMap::const_iterator, GameEventCreatureDataPerGuidMap::const_iterator> GameEventMgr::GameEventCreatureDataPerGuidBounds protected
Definition at line 140 of file GameEventMgr.h.
GameEventCreatureDataPerGuidMap
typedef std::multimap<uint32, uint32> GameEventMgr::GameEventCreatureDataPerGuidMap protected
Definition at line 139 of file GameEventMgr.h.
GameEventDataMap
typedef std::vector<GameEventData> GameEventMgr::GameEventDataMap
Definition at line 99 of file GameEventMgr.h.
GameEventGuidMap
typedef std::vector<GuidList> GameEventMgr::GameEventGuidMap protected
Definition at line 135 of file GameEventMgr.h.
GameEventIdMap
typedef std::vector<IdList> GameEventMgr::GameEventIdMap protected
Definition at line 136 of file GameEventMgr.h.
GameEventMailMap
typedef std::vector<MailList> GameEventMgr::GameEventMailMap protected
Definition at line 151 of file GameEventMgr.h.
GameEventQuestMap
typedef std::vector<QuestList> GameEventMgr::GameEventQuestMap protected
Definition at line 143 of file GameEventMgr.h.
GuidList
typedef std::list<uint32> GameEventMgr::GuidList protected
Definition at line 133 of file GameEventMgr.h.
IdList
typedef std::list<uint16> GameEventMgr::IdList protected
Definition at line 134 of file GameEventMgr.h.
MailList
typedef std::list<GameEventMail> GameEventMgr::MailList protected
Definition at line 150 of file GameEventMgr.h.
QuestList
typedef std::list<uint32> GameEventMgr::QuestList protected
Definition at line 142 of file GameEventMgr.h.
Constructor & Destructor Documentation
GameEventMgr()
GameEventMgr::GameEventMgr ()
Definition at line 1179 of file GameEventMgr.cpp.
References m_isGameEventsInit.
~GameEventMgr()
GameEventMgr::~GameEventMgr () inline
Definition at line 97 of file GameEventMgr.h.
Member Function Documentation
ApplyNewEvent()
void GameEventMgr::ApplyNewEvent (uint16 event_id, bool resume) private
Definition at line 835 of file GameEventMgr.cpp.
References CharacterDatabase, CONFIG_BOOL_EVENT_ANNOUNCE, GameEventSpawn(), GameEventUnspawn(), LANG_EVENTMESSAGE, m_activeEvents, m_gameEvents, OnEventHappened(), Database::PExecute(), RESTART_EXIT_CODE, SendEventMails(), SHUTDOWN_MASK_RESTART, sLog, sWorld, UpdateCreatureData(), UpdateEventQuests(), and UpdateWorldStates().
Referenced by StartEvent().
CheckOneGameEvent()
bool GameEventMgr::CheckOneGameEvent (uint16 entry, time_t currenttime) const
Definition at line 36 of file GameEventMgr.cpp.
References m_gameEvents, and MINUTE.
Referenced by Update().
ComputeEventStartAndEndTime()
void GameEventMgr::ComputeEventStartAndEndTime (GameEventData & data, time_t today) private
Definition at line 1258 of file GameEventMgr.cpp.
References GameEventData::end, GAME_EVENT_SCHEDULE_DMF_1, GAME_EVENT_SCHEDULE_DMF_2, GAME_EVENT_SCHEDULE_DMF_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_3, GAME_EVENT_SCHEDULE_EASTER, GAME_EVENT_SCHEDULE_LUNAR_NEW_YEAR, GAME_EVENT_SCHEDULE_YEARLY, gaussEaster(), Moon::nextphase(), GameEventData::scheduleType, and GameEventData::start.
Referenced by LoadFromDB(), and WeeklyEventTimerRecalculation().
GameEventSpawn()
void GameEventMgr::GameEventSpawn (int16 event_id) private
Definition at line 869 of file GameEventMgr.cpp.
References m_gameEventCreatureGuids, m_gameEventGameobjectGuids, m_gameEvents, m_gameEventSpawnPoolIds, SIZEFMTD, sLog, sObjectMgr, Creature::SpawnInMaps(), GameObject::SpawnInMaps(), and sPoolMgr.
Referenced by ApplyNewEvent(), UnApplyEvent(), and Update().
GameEventUnspawn()
void GameEventMgr::GameEventUnspawn (int16 event_id) private
Definition at line 946 of file GameEventMgr.cpp.
References Creature::AddToRemoveListInMaps(), GameObject::AddToRemoveListInMaps(), m_gameEventCreatureGuids, m_gameEventGameobjectGuids, m_gameEvents, m_gameEventSpawnPoolIds, SIZEFMTD, sLog, sObjectMgr, and sPoolMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
GetActiveEventList()
ActiveEvents const& GameEventMgr::GetActiveEventList () const inline
Definition at line 100 of file GameEventMgr.h.
References m_activeEvents.
GetCreatureUpdateDataForActiveEvent()
GameEventCreatureData const * GameEventMgr::GetCreatureUpdateDataForActiveEvent (uint32 dbGuid) const
Definition at line 1025 of file GameEventMgr.cpp.
References IsActiveEvent(), m_gameEventCreatureData, and m_gameEventCreatureDataPerGuid.
GetEventGroups()
std::unordered_map<uint32, std::vector<uint32> > const& GameEventMgr::GetEventGroups () const inline
Definition at line 116 of file GameEventMgr.h.
References m_gameEventGroups.
GetEventMap()
GameEventDataMap const& GameEventMgr::GetEventMap () const inline
Definition at line 101 of file GameEventMgr.h.
References m_gameEvents.
GetGameEventId() [1/4]
template<> int16 GameEventMgr::GetGameEventId (uint32 guid_or_poolid)
Definition at line 1148 of file GameEventMgr.cpp.
References m_gameEventCreatureGuids, and m_gameEvents.
GetGameEventId() [2/4]
template<> int16 GameEventMgr::GetGameEventId (uint32 guid_or_poolid)
Definition at line 1159 of file GameEventMgr.cpp.
References m_gameEventGameobjectGuids, and m_gameEvents.
GetGameEventId() [3/4]
template<> int16 GameEventMgr::GetGameEventId (uint32 guid_or_poolid)
Definition at line 1170 of file GameEventMgr.cpp.
References m_gameEventSpawnPoolIds.
GetGameEventId() [4/4]
template<typename T > int16 GameEventMgr::GetGameEventId (uint32 guid_or_poolid)
Initialize() [1/2]
uint32 GameEventMgr::Initialize ()
Definition at line 732 of file GameEventMgr.cpp.
References BASIC_LOG, CharacterDatabase, Database::Execute(), Field::GetUInt16(), m_activeEvents, m_isGameEventsInit, Database::Query(), and Update().
Initialize() [2/2]
void GameEventMgr::Initialize (MapPersistentState * state)
Definition at line 758 of file GameEventMgr.cpp.
References m_activeEvents, m_gameEventSpawnPoolIds, and sPoolMgr.
IsActiveEvent()
bool GameEventMgr::IsActiveEvent (uint16 event_id) const inline
Definition at line 108 of file GameEventMgr.h.
References m_activeEvents.
Referenced by GetCreatureUpdateDataForActiveEvent(), and Update().
IsActiveHoliday()
bool GameEventMgr::IsActiveHoliday (HolidayIds id) const
Definition at line 1184 of file GameEventMgr.cpp.
References HOLIDAY_NONE, m_activeEvents, and m_gameEvents.
IsValidEvent()
bool GameEventMgr::IsValidEvent (uint16 event_id) const inline
Definition at line 107 of file GameEventMgr.h.
References m_gameEvents.
Referenced by LoadFromDB().
LoadFromDB()
void GameEventMgr::LoadFromDB ()
Definition at line 89 of file GameEventMgr.cpp.
References ComputeEventStartAndEndTime(), GameEventData::description, GameEventData::end, GameEventCreatureData::entry_id, GameEventCreatureData::equipment_id, GameEventData::eventGroup, FAR_FUTURE, GAME_EVENT_SCHEDULE_DATE, GAME_EVENT_SCHEDULE_DMF_1, GAME_EVENT_SCHEDULE_DMF_2, GAME_EVENT_SCHEDULE_DMF_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_3, GAME_EVENT_SCHEDULE_EASTER, GAME_EVENT_SCHEDULE_LUNAR_NEW_YEAR, GAME_EVENT_SCHEDULE_SERVERSIDE, GAME_EVENT_SCHEDULE_YEARLY, Field::GetCppString(), ObjectMgr::GetCreatureTemplate(), Field::GetInt16(), Field::GetTime(), Field::GetUInt16(), Field::GetUInt32(), HOLIDAY_CHILDRENS_WEEK, HOLIDAY_DARKMOON_FAIRE_ELWYNN, HOLIDAY_DARKMOON_FAIRE_SHATTRATH, HOLIDAY_DARKMOON_FAIRE_THUNDER, HOLIDAY_HARVEST_FESTIVAL, GameEventData::holiday_id, HOLIDAY_LOVE_IS_IN_THE_AIR, HOLIDAY_LUNAR_FESTIVAL, HOLIDAY_NOBLEGARDEN, HOLIDAY_NONE, HOLIDAY_PILGRIMS_BOUNTY, IsValidEvent(), GameEventData::length, GameEventData::linkedTo, SQLStorage::LookupEntry(), m_gameEventCreatureData, m_gameEventCreatureDataPerGuid, m_gameEventCreatureGuids, m_gameEventGameobjectGuids, m_gameEventGroups, m_gameEventMails, m_gameEventQuests, m_gameEvents, m_gameEventSpawnPoolIds, GameEventMail::mailTemplateId, GameEventCreatureData::modelid, GameEventData::occurence, Database::Query(), GameEventMail::questId, GameEventMail::raceMask, RACEMASK_ALL_PLAYABLE, GameEventData::scheduleType, GameEventMail::senderEntry, sHolidaysStore, sLog, sMailTemplateStore, sObjectMgr, GameEventCreatureData::spell_id_end, GameEventCreatureData::spell_id_start, sPoolMgr, sSpellTemplate, GameEventData::start, BarGoLink::step(), and WorldDatabase.
NextCheck()
uint32 GameEventMgr::NextCheck (uint16 entry) const
Definition at line 42 of file GameEventMgr.cpp.
References m_gameEvents, max_ge_check_delay, and MINUTE.
Referenced by Update().
OnEventHappened()
void GameEventMgr::OnEventHappened (uint16 event_id, bool activate, bool resume) private
Definition at line 1201 of file GameEventMgr.cpp.
References Map::GetInstanceData(), Map::OnEventHappened(), and sMapMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
SendEventMails()
void GameEventMgr::SendEventMails (int16 event_id) private
Definition at line 1121 of file GameEventMgr.cpp.
References m_gameEventMails, m_gameEvents, MAIL_CREATURE, and sMassMailMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
StartEvent()
void GameEventMgr::StartEvent (uint16 event_id, bool overwrite = false, bool resume = false)
Definition at line 67 of file GameEventMgr.cpp.
References ApplyNewEvent(), and m_gameEvents.
Referenced by Update().
StopEvent()
void GameEventMgr::StopEvent (uint16 event_id, bool overwrite = false)
Definition at line 78 of file GameEventMgr.cpp.
References m_gameEvents, MINUTE, and UnApplyEvent().
Referenced by Update().
UnApplyEvent()
void GameEventMgr::UnApplyEvent (uint16 event_id) private
Definition at line 814 of file GameEventMgr.cpp.
References CharacterDatabase, GameEventSpawn(), GameEventUnspawn(), m_activeEvents, m_gameEvents, OnEventHappened(), Database::PExecute(), SendEventMails(), sLog, UpdateCreatureData(), UpdateEventQuests(), and UpdateWorldStates().
Referenced by StopEvent().
Update()
uint32 GameEventMgr::Update (ActiveEvents const * activeAtShutdown = nullptr)
Definition at line 768 of file GameEventMgr.cpp.
References BASIC_LOG, CheckOneGameEvent(), GAME_EVENT_SCHEDULE_SERVERSIDE, GameEventSpawn(), IN_MILLISECONDS, IsActiveEvent(), m_gameEvents, m_isGameEventsInit, max_ge_check_delay, NextCheck(), StartEvent(), StopEvent(), and UpdateWorldStates().
Referenced by Initialize().
UpdateCreatureData()
void GameEventMgr::UpdateCreatureData (int16 event_id, bool activate) private
Definition at line 1072 of file GameEventMgr.cpp.
References CreatureData::GetObjectGuid(), m_gameEventCreatureData, CreatureData::mapid, sMapMgr, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateEventQuests()
void GameEventMgr::UpdateEventQuests (uint16 event_id, bool Activate) private
Definition at line 1087 of file GameEventMgr.cpp.
References m_gameEventQuests, and sObjectMgr.
Referenced by ApplyNewEvent(), and UnApplyEvent().
UpdateWorldStates()
void GameEventMgr::UpdateWorldStates (uint16 event_id, bool Activate) private
Definition at line 1102 of file GameEventMgr.cpp.
References BATTLEGROUND_TYPE_NONE, HOLIDAY_NONE, BattlemasterListEntry::HolidayWorldStateId, m_gameEvents, sBattleGroundMgr, sBattlemasterListStore, sWorld, and BattleGroundMgr::WeekendHolidayIdToBgType().
Referenced by ApplyNewEvent(), UnApplyEvent(), and Update().
WeeklyEventTimerRecalculation()
void GameEventMgr::WeeklyEventTimerRecalculation ()
Definition at line 1382 of file GameEventMgr.cpp.
References ComputeEventStartAndEndTime(), GAME_EVENT_SCHEDULE_DMF_1, GAME_EVENT_SCHEDULE_DMF_2, GAME_EVENT_SCHEDULE_DMF_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_1_3, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_1, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_2, GAME_EVENT_SCHEDULE_DMF_BUILDING_STAGE_2_3, GAME_EVENT_SCHEDULE_EASTER, GAME_EVENT_SCHEDULE_LUNAR_NEW_YEAR, GAME_EVENT_SCHEDULE_YEARLY, and m_gameEvents.
Field Documentation
m_activeEvents
ActiveEvents GameEventMgr::m_activeEvents protected
Definition at line 158 of file GameEventMgr.h.
Referenced by ApplyNewEvent(), GetActiveEventList(), Initialize(), IsActiveEvent(), IsActiveHoliday(), and UnApplyEvent().
m_gameEventCreatureData
GameEventCreatureDataMap GameEventMgr::m_gameEventCreatureData protected
Definition at line 147 of file GameEventMgr.h.
Referenced by GetCreatureUpdateDataForActiveEvent(), LoadFromDB(), and UpdateCreatureData().
m_gameEventCreatureDataPerGuid
GameEventCreatureDataPerGuidMap GameEventMgr::m_gameEventCreatureDataPerGuid protected
Definition at line 148 of file GameEventMgr.h.
Referenced by GetCreatureUpdateDataForActiveEvent(), and LoadFromDB().
m_gameEventCreatureGuids
GameEventGuidMap GameEventMgr::m_gameEventCreatureGuids protected
Definition at line 154 of file GameEventMgr.h.
Referenced by GameEventSpawn(), GameEventUnspawn(), GetGameEventId(), and LoadFromDB().
m_gameEventGameobjectGuids
GameEventGuidMap GameEventMgr::m_gameEventGameobjectGuids protected
Definition at line 155 of file GameEventMgr.h.
Referenced by GameEventSpawn(), GameEventUnspawn(), GetGameEventId(), and LoadFromDB().
m_gameEventGroups
std::unordered_map<uint32, std::vector<uint32> > GameEventMgr::m_gameEventGroups protected
Definition at line 161 of file GameEventMgr.h.
Referenced by GetEventGroups(), and LoadFromDB().
m_gameEventMails
GameEventMailMap GameEventMgr::m_gameEventMails protected
Definition at line 152 of file GameEventMgr.h.
Referenced by LoadFromDB(), and SendEventMails().
m_gameEventQuests
GameEventQuestMap GameEventMgr::m_gameEventQuests protected
Definition at line 145 of file GameEventMgr.h.
Referenced by LoadFromDB(), and UpdateEventQuests().
m_gameEvents
GameEventDataMap GameEventMgr::m_gameEvents protected
Definition at line 157 of file GameEventMgr.h.
Referenced by ApplyNewEvent(), CheckOneGameEvent(), GameEventSpawn(), GameEventUnspawn(), GetEventMap(), GetGameEventId(), IsActiveHoliday(), IsValidEvent(), LoadFromDB(), NextCheck(), SendEventMails(), StartEvent(), StopEvent(), UnApplyEvent(), Update(), UpdateWorldStates(), and WeeklyEventTimerRecalculation().
m_gameEventSpawnPoolIds
GameEventIdMap GameEventMgr::m_gameEventSpawnPoolIds protected
Definition at line 156 of file GameEventMgr.h.
Referenced by GameEventSpawn(), GameEventUnspawn(), GetGameEventId(), Initialize(), and LoadFromDB().
m_isGameEventsInit
bool GameEventMgr::m_isGameEventsInit protected
Definition at line 159 of file GameEventMgr.h.
Referenced by GameEventMgr(), Initialize(), and Update().
The documentation for this class was generated from the following files:
GameEventMgr.h
GameEventMgr.cpp