CMaNGOS_WoTLK: DungeonResetScheduler Class Reference
DungeonResetScheduler Class Reference
#include <MapPersistentStateMgr.h>
Public Member Functions
DungeonResetScheduler (MapPersistentStateManager &mgr)
void LoadResetTimes ()
time_t GetResetTimeFor (uint32 mapid, Difficulty d) const
void SetResetTimeFor (uint32 mapid, Difficulty d, time_t t)
void ScheduleReset (bool add, time_t time, DungeonResetEvent event)
void Update ()
void ResetAllRaid ()
Static Public Member Functions
static uint32 GetMaxResetTimeFor (MapDifficultyEntry const *mapDiff)
static time_t CalculateNextResetTime (MapDifficultyEntry const *mapDiff, time_t prevResetTime)
Private Types
typedef std::unordered_map< uint32, time_t > ResetTimeByMapDifficultyMap
typedef std::multimap< time_t, DungeonResetEvent > ResetTimeQueue
Private Attributes
MapPersistentStateManager & m_InstanceSaves
ResetTimeByMapDifficultyMap m_resetTimeByMapDifficulty
ResetTimeQueue m_resetTimeQueue
Detailed Description
Definition at line 299 of file MapPersistentStateMgr.h.
Member Typedef Documentation
ResetTimeByMapDifficultyMap
typedef std::unordered_map<uint32 , time_t > DungeonResetScheduler::ResetTimeByMapDifficultyMap private
Definition at line 329 of file MapPersistentStateMgr.h.
ResetTimeQueue
typedef std::multimap< time_t , DungeonResetEvent > DungeonResetScheduler::ResetTimeQueue private
Definition at line 332 of file MapPersistentStateMgr.h.
Constructor & Destructor Documentation
DungeonResetScheduler()
DungeonResetScheduler::DungeonResetScheduler (MapPersistentStateManager & mgr) inline explicit
Definition at line 302 of file MapPersistentStateMgr.h.
Member Function Documentation
CalculateNextResetTime()
time_t DungeonResetScheduler::CalculateNextResetTime (MapDifficultyEntry const * mapDiff, time_t prevResetTime) static
Definition at line 373 of file MapPersistentStateMgr.cpp.
References CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR, DAY, GetMaxResetTimeFor(), HOUR, MINUTE, and sWorld.
Referenced by MapPersistentStateManager::_ResetOrWarnAll(), and Update().
GetMaxResetTimeFor()
uint32 DungeonResetScheduler::GetMaxResetTimeFor (MapDifficultyEntry const * mapDiff) static
Definition at line 360 of file MapPersistentStateMgr.cpp.
References CONFIG_FLOAT_RATE_INSTANCE_RESET_TIME, DAY, MapDifficultyEntry::resetTime, and sWorld.
Referenced by CalculateNextResetTime(), Map::GetMaxResetDelay(), and LoadResetTimes().
GetResetTimeFor()
time_t DungeonResetScheduler::GetResetTimeFor (uint32 mapid, Difficulty d) const inline
Definition at line 306 of file MapPersistentStateMgr.h.
References m_resetTimeByMapDifficulty, and MAKE_PAIR32.
Referenced by MapPersistentStateManager::AddPersistentState(), LoadResetTimes(), and Update().
LoadResetTimes()
void DungeonResetScheduler::LoadResetTimes ()
Definition at line 380 of file MapPersistentStateMgr.cpp.
References MapPersistentStateManager::_CleanupExpiredInstancesAtTime(), CharacterDatabase, CONFIG_UINT32_ARENA_FIRST_RESET_DAY, CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR, CONFIG_UINT32_QUEST_DAILY_RESET_HOUR, DAY, Database::DirectPExecute(), QueryResult::Fetch(), GetMapDifficultyData(), GetMaxResetTimeFor(), GetResetTimeFor(), Field::GetUInt32(), Field::GetUInt64(), HOUR, MapEntry::IsDungeon(), m_InstanceSaves, MAKE_PAIR32, QueryResult::NextRow(), PAIR32_HIPART, PAIR32_LOPART, Database::Query(), RESET_EVENT_INFORM_1, RESET_EVENT_INFORM_LAST, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, MapDifficultyEntry::resetTime, ScheduleReset(), SetResetTimeFor(), sLog, sMapDifficultyMap, sMapPersistentStateMgr, sMapStore, sWorld, and UI64FMTD.
Referenced by MapPersistentStateManager::CleanupInstances().
ResetAllRaid()
void DungeonResetScheduler::ResetAllRaid ()
Definition at line 628 of file MapPersistentStateMgr.cpp.
References m_resetTimeQueue, RESET_EVENT_FORCED_INFORM_1, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, SetResetTimeFor(), and DungeonResetEvent::type.
ScheduleReset()
void DungeonResetScheduler::ScheduleReset (bool add, time_t time, DungeonResetEvent event)
Definition at line 542 of file MapPersistentStateMgr.cpp.
References DungeonResetEvent::instanceId, m_resetTimeQueue, DungeonResetEvent::mapid, sLog, and DungeonResetEvent::type.
Referenced by MapPersistentStateManager::AddPersistentState(), LoadResetTimes(), and Update().
SetResetTimeFor()
void DungeonResetScheduler::SetResetTimeFor (uint32 mapid, Difficulty d, time_t t) inline
Definition at line 315 of file MapPersistentStateMgr.h.
References m_resetTimeByMapDifficulty, and MAKE_PAIR32.
Referenced by LoadResetTimes(), ResetAllRaid(), and Update().
Update()
void DungeonResetScheduler::Update ()
Definition at line 577 of file MapPersistentStateMgr.cpp.
References MapPersistentStateManager::_ResetInstance(), MapPersistentStateManager::_ResetOrWarnAll(), CalculateNextResetTime(), CharacterDatabase, Database::DirectPExecute(), GetMapDifficultyData(), GetResetTimeFor(), m_InstanceSaves, m_resetTimeQueue, MANGOS_ASSERT, RESET_EVENT_FORCED_INFORM_LAST, RESET_EVENT_INFORM_1, RESET_EVENT_INFORM_LAST, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, ScheduleReset(), SetResetTimeFor(), and UI64FMTD.
Referenced by MapPersistentStateManager::Update().
Field Documentation
m_InstanceSaves
MapPersistentStateManager& DungeonResetScheduler::m_InstanceSaves private
Definition at line 326 of file MapPersistentStateMgr.h.
Referenced by LoadResetTimes(), and Update().
m_resetTimeByMapDifficulty
ResetTimeByMapDifficultyMap DungeonResetScheduler::m_resetTimeByMapDifficulty private
Definition at line 330 of file MapPersistentStateMgr.h.
Referenced by GetResetTimeFor(), and SetResetTimeFor().
m_resetTimeQueue
ResetTimeQueue DungeonResetScheduler::m_resetTimeQueue private
Definition at line 333 of file MapPersistentStateMgr.h.
Referenced by ResetAllRaid(), ScheduleReset(), and Update().
The documentation for this class was generated from the following files:
MapPersistentStateMgr.h
MapPersistentStateMgr.cpp