CMaNGOS_WoTLK: LootMgr Class Reference
LootMgr Class Reference
#include <LootMgr.h>
Public Member Functions
void PlayerVote (Player *player, ObjectGuid const &lootTargetGuid, uint32 itemSlot, RollVote vote)
Loot * GetLoot (Player *player, ObjectGuid const &targetGuid=ObjectGuid()) const
void CheckDropStats (ChatHandler &chat, uint32 amountOfCheck, uint32 lootId, std::string lootStore) const
bool ExistsRefLootTemplate (uint32 refLootId) const
Detailed Description
Definition at line 430 of file LootMgr.h.
Member Function Documentation
CheckDropStats()
void LootMgr::CheckDropStats (ChatHandler & chat, uint32 amountOfCheck, uint32 lootId, std::string lootStore) const
Definition at line 3200 of file LootMgr.cpp.
References LootStore::GetLootFor(), LootStore::GetName(), LootStore::IsRatesAllowed(), LANG_ITEM_LIST_CHAT, SQLStorage::LookupEntry(), LOOT_DEBUG, LootTemplates_Creature, LootTemplates_Disenchant, LootTemplates_Fishing, LootTemplates_Gameobject, LootTemplates_Item, LootTemplates_Mail, LootTemplates_Milling, LootTemplates_Pickpocketing, LootTemplates_Prospecting, LootTemplates_Skinning, LootTemplates_Spell, ItemPrototype::Name1, LootTemplate::Process(), ChatHandler::PSendSysMessage(), sItemStorage, sLog, and sObjectMgr.
ExistsRefLootTemplate()
bool LootMgr::ExistsRefLootTemplate (uint32 refLootId) const
Definition at line 3279 of file LootMgr.cpp.
References LootStore::HaveLootFor(), and LootTemplates_Reference.
GetLoot()
Loot * LootMgr::GetLoot (Player * player, ObjectGuid const & targetGuid = ObjectGuid()) const
Definition at line 3137 of file LootMgr.cpp.
References Map::GetCorpse(), Map::GetCreature(), Map::GetGameObject(), ObjectGuid::GetHigh(), Player::GetItemByGuid(), Player::GetLootGuid(), WorldObject::GetMap(), Player::GetSelectionGuid(), Item::HasGeneratedLoot(), HIGHGUID_CORPSE, HIGHGUID_GAMEOBJECT, HIGHGUID_ITEM, HIGHGUID_UNIT, HIGHGUID_VEHICLE, ObjectGuid::IsEmpty(), and Object::m_loot.
PlayerVote()
void LootMgr::PlayerVote (Player * player, ObjectGuid const & lootTargetGuid, uint32 itemSlot, RollVote vote)
Definition at line 3101 of file LootMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, Player::GetAchievementMgr(), Loot::GetRollForSlot(), GroupLootRoll::PlayerVote(), ROLL_DISENCHANT, ROLL_GREED, ROLL_NEED, sLog, and AchievementMgr::UpdateAchievementCriteria().
The documentation for this class was generated from the following files:
LootMgr.h
LootMgr.cpp