CMaNGOS_WoTLK: instance_shadow_labyrinth Class Reference
instance_shadow_labyrinth Class Reference
#include <shadow_labyrinth.h>
Public Member Functions
instance_shadow_labyrinth (Map *pMap)
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetData64 (uint32 uiType, uint64 uiGuid) override
const char * Save () const override
void Load (const char *chrIn) override
bool IsHellmawUnbanished () const
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidSet m_sRitualistsAliveGUIDSet
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 39 of file shadow_labyrinth.h.
Constructor & Destructor Documentation
instance_shadow_labyrinth()
instance_shadow_labyrinth::instance_shadow_labyrinth (Map * pMap)
Definition at line 35 of file shadow_labyrinth.cpp.
References Initialize().
Member Function Documentation
GetData()
uint32 instance_shadow_labyrinth::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 116 of file shadow_labyrinth.cpp.
References m_auiEncounter, TYPE_HELLMAW, TYPE_INCITER, TYPE_MURMUR, and TYPE_VORPIL.
Referenced by SetData64().
Initialize()
void instance_shadow_labyrinth::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 40 of file shadow_labyrinth.cpp.
References m_auiEncounter.
Referenced by instance_shadow_labyrinth().
IsHellmawUnbanished()
bool instance_shadow_labyrinth::IsHellmawUnbanished () const inline
Definition at line 59 of file shadow_labyrinth.h.
References m_sRitualistsAliveGUIDSet.
Referenced by boss_ambassador_hellmawAI::UpdateAI().
Load()
void instance_shadow_labyrinth::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 166 of file shadow_labyrinth.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_shadow_labyrinth::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 60 of file shadow_labyrinth.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_BLACKHEART_THE_INCITER, NPC_CABAL_SPELLBINDER, NPC_CABAL_SUMMONER, NPC_CONTAINMENT_BEAM, NPC_HELLMAW, NPC_MURMUR, and NPC_VORPIL.
OnCreatureDeath()
void instance_shadow_labyrinth::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 142 of file shadow_labyrinth.cpp.
References AI_EVENT_CUSTOM_A, Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_sRitualistsAliveGUIDSet, NPC_CABAL_RITUALIST, NPC_CONTAINMENT_BEAM, and NPC_HELLMAW.
OnObjectCreate()
void instance_shadow_labyrinth::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file shadow_labyrinth.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_REFECTORY_DOOR, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), and TYPE_HELLMAW.
Save()
const char* instance_shadow_labyrinth::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 56 of file shadow_labyrinth.h.
References m_strInstData.
SetData()
void instance_shadow_labyrinth::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 78 of file shadow_labyrinth.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), GO_REFECTORY_DOOR, m_auiEncounter, m_strInstData, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_HELLMAW, TYPE_INCITER, TYPE_MURMUR, and TYPE_VORPIL.
Referenced by boss_ambassador_hellmawAI::Aggro(), boss_ambassador_hellmawAI::JustDied(), and boss_ambassador_hellmawAI::JustReachedHome().
SetData64()
void instance_shadow_labyrinth::SetData64 (uint32 uiType, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 130 of file shadow_labyrinth.cpp.
References DATA_CABAL_RITUALIST, DONE, GetData(), m_sRitualistsAliveGUIDSet, and TYPE_HELLMAW.
Field Documentation
m_auiEncounter
uint32 instance_shadow_labyrinth::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 62 of file shadow_labyrinth.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_sRitualistsAliveGUIDSet
GuidSet instance_shadow_labyrinth::m_sRitualistsAliveGUIDSet private
Definition at line 65 of file shadow_labyrinth.h.
Referenced by IsHellmawUnbanished(), OnCreatureDeath(), and SetData64().
m_strInstData
std::string instance_shadow_labyrinth::m_strInstData private
Definition at line 63 of file shadow_labyrinth.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
shadow_labyrinth.h
shadow_labyrinth.cpp