CMaNGOS_WoTLK: CalendarEvent Class Reference
CalendarEvent Class Reference
#include <Calendar.h>
Public Member Functions
CalendarEvent (uint64 eventId, uint64 creatorGUID, uint32 guildId, CalendarEventType type, int32 dungeonId, time_t eventTime, uint32 flags, time_t unknownTime, std::string title, std::string description)
CalendarEvent ()
~CalendarEvent ()
bool IsGuildEvent () const
bool IsGuildAnnouncement () const
bool AddInvite (CalendarInvite *invite)
CalendarInviteMap const * GetInviteMap () const
CalendarInvite * GetInviteById (uint64 inviteId)
CalendarInvite * GetInviteByGuid (ObjectGuid const &guid)
bool RemoveInviteById (uint64 inviteId, Player *remover)
void RemoveInviteByGuid (ObjectGuid const &playerGuid)
void RemoveAllInvite (ObjectGuid const &removerGuid)
Data Fields
uint64 EventId
ObjectGuid CreatorGuid
uint32 GuildId
CalendarEventType Type
CalendarRepeatType Repeatable
int32 DungeonId
time_t EventTime
uint32 Flags
time_t UnknownTime
std::string Title
std::string Description
Private Member Functions
void RemoveInviteByItr (CalendarInviteMap::iterator inviteItr)
void RemoveAllInvite ()
Private Attributes
CalendarInviteMap m_Invitee
Detailed Description
Definition at line 139 of file Calendar.h.
Constructor & Destructor Documentation
CalendarEvent() [1/2]
CalendarEvent::CalendarEvent (uint64 eventId, uint64 creatorGUID, uint32 guildId, CalendarEventType type, int32 dungeonId, time_t eventTime, uint32 flags, time_t unknownTime, std::string title, std::string description) inline
Definition at line 142 of file Calendar.h.
CalendarEvent() [2/2]
CalendarEvent::CalendarEvent () inline
Definition at line 148 of file Calendar.h.
~CalendarEvent()
CalendarEvent::~CalendarEvent ()
Definition at line 31 of file Calendar.cpp.
References RemoveAllInvite().
Member Function Documentation
AddInvite()
bool CalendarEvent::AddInvite (CalendarInvite * invite)
Definition at line 37 of file Calendar.cpp.
References CalendarInvite::InviteId, and m_Invitee.
Referenced by CalendarMgr::AddInvite().
GetInviteByGuid()
CalendarInvite * CalendarEvent::GetInviteByGuid (ObjectGuid const & guid)
Definition at line 53 of file Calendar.cpp.
References m_Invitee.
Referenced by CalendarMgr::AddInvite(), and RemoveInviteById().
GetInviteById()
CalendarInvite * CalendarEvent::GetInviteById (uint64 inviteId)
Definition at line 45 of file Calendar.cpp.
References m_Invitee.
GetInviteMap()
CalendarInviteMap const* CalendarEvent::GetInviteMap () const inline
Definition at line 159 of file Calendar.h.
References m_Invitee.
Referenced by CalendarMgr::CanAddInviteTo(), and CalendarMgr::GetPlayerInvitesList().
IsGuildAnnouncement()
bool CalendarEvent::IsGuildAnnouncement () const inline
Definition at line 155 of file Calendar.h.
References CALENDAR_FLAG_GUILD_ANNOUNCEMENT, and Flags.
Referenced by CalendarMgr::AddInvite(), CalendarMgr::CopyEvent(), WorldSession::HandleCalendarAddEvent(), and CalendarMgr::SendPacketToAllEventRelatives().
IsGuildEvent()
bool CalendarEvent::IsGuildEvent () const inline
Definition at line 154 of file Calendar.h.
References CALENDAR_FLAG_GUILD_EVENT, and Flags.
Referenced by CalendarMgr::AddInvite(), RemoveInviteByItr(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendPacketToAllEventRelatives().
RemoveAllInvite() [1/2]
void CalendarEvent::RemoveAllInvite () private
Definition at line 142 of file Calendar.cpp.
References m_Invitee, and RemoveInviteByItr().
Referenced by ~CalendarEvent().
RemoveAllInvite() [2/2]
void CalendarEvent::RemoveAllInvite (ObjectGuid const & removerGuid)
Definition at line 150 of file Calendar.cpp.
References m_Invitee, MAIL_CHECK_MASK_COPIED, RemoveInviteByItr(), secsToTimeBitFields(), MailDraft::SendMailTo(), and Title.
RemoveInviteByGuid()
void CalendarEvent::RemoveInviteByGuid (ObjectGuid const & playerGuid)
Definition at line 83 of file Calendar.cpp.
References m_Invitee, and RemoveInviteByItr().
Referenced by CalendarMgr::RemovePlayerCalendar().
RemoveInviteById()
bool CalendarEvent::RemoveInviteById (uint64 inviteId, Player * remover)
Definition at line 97 of file Calendar.cpp.
References CALENDAR_ERROR_DELETE_CREATOR_FAILED, CALENDAR_ERROR_NO_INVITE, CALENDAR_ERROR_NOT_INVITED, CALENDAR_ERROR_PERMISSIONS, CALENDAR_RANK_MODERATOR, CALENDAR_RANK_OWNER, CreatorGuid, GetInviteByGuid(), Object::GetObjectGuid(), CalendarInvite::InviteeGuid, m_Invitee, CalendarInvite::Rank, RemoveInviteByItr(), and sCalendarMgr.
Referenced by CalendarMgr::RemoveInvite().
RemoveInviteByItr()
void CalendarEvent::RemoveInviteByItr (CalendarInviteMap::iterator inviteItr) private
Definition at line 67 of file Calendar.cpp.
References CALENDAR_STATUS_REMOVED, CharacterDatabase, Flags, IsGuildEvent(), m_Invitee, MANGOS_ASSERT, Database::PExecute(), sCalendarMgr, sObjectMgr, and UI64FMTD.
Referenced by RemoveAllInvite(), RemoveInviteByGuid(), and RemoveInviteById().
Field Documentation
CreatorGuid
ObjectGuid CalendarEvent::CreatorGuid
Definition at line 169 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::AddInvite(), CalendarMgr::LoadCalendarsFromDB(), RemoveInviteById(), and CalendarMgr::SendCalendarEvent().
Description
std::string CalendarEvent::Description
Definition at line 178 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), and CalendarMgr::SendCalendarEventUpdateAlert().
DungeonId
int32 CalendarEvent::DungeonId
Definition at line 173 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), and CalendarMgr::SendCalendarEventUpdateAlert().
EventId
uint64 CalendarEvent::EventId
Definition at line 168 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::AddInvite(), CalendarMgr::LoadCalendarsFromDB(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventRemovedAlert(), and CalendarMgr::SendCalendarEventUpdateAlert().
EventTime
time_t CalendarEvent::EventTime
Definition at line 174 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), CalendarMgr::SendCalendarEventRemovedAlert(), and CalendarMgr::SendCalendarEventUpdateAlert().
Flags
uint32 CalendarEvent::Flags
Definition at line 175 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), IsGuildAnnouncement(), IsGuildEvent(), CalendarMgr::LoadCalendarsFromDB(), RemoveInviteByItr(), CalendarMgr::SendCalendarEvent(), CalendarMgr::SendCalendarEventInviteRemoveAlert(), and CalendarMgr::SendCalendarEventUpdateAlert().
GuildId
uint32 CalendarEvent::GuildId
Definition at line 170 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendPacketToAllEventRelatives().
m_Invitee
CalendarInviteMap CalendarEvent::m_Invitee private
Definition at line 184 of file Calendar.h.
Referenced by AddInvite(), GetInviteByGuid(), GetInviteById(), GetInviteMap(), RemoveAllInvite(), RemoveInviteByGuid(), RemoveInviteById(), and RemoveInviteByItr().
Repeatable
CalendarRepeatType CalendarEvent::Repeatable
Definition at line 172 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendCalendarEventUpdateAlert().
Title
std::string CalendarEvent::Title
Definition at line 177 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), RemoveAllInvite(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendCalendarEventUpdateAlert().
Type
CalendarEventType CalendarEvent::Type
Definition at line 171 of file Calendar.h.
Referenced by CalendarMgr::AddEvent(), CalendarMgr::LoadCalendarsFromDB(), CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendCalendarEventUpdateAlert().
UnknownTime
time_t CalendarEvent::UnknownTime
Definition at line 176 of file Calendar.h.
Referenced by CalendarMgr::SendCalendarEvent(), and CalendarMgr::SendCalendarEventUpdateAlert().
The documentation for this class was generated from the following files:
Calendar.h
Calendar.cpp