CMaNGOS_WoTLK: AuctionHouseMgr Class Reference
AuctionHouseMgr Class Reference
#include <AuctionHouseMgr.h>
Public Types
typedef std::unordered_map< uint32, Item * > ItemMap
Public Member Functions
AuctionHouseMgr ()
~AuctionHouseMgr ()
AuctionHouseObject * GetAuctionsMap (AuctionHouseType houseType)
AuctionHouseObject * GetAuctionsMap (AuctionHouseEntry const *house)
Item * GetAItem (uint32 id)
void SendAuctionWonMail (AuctionEntry *auction)
void SendAuctionExpiredMail (AuctionEntry *auction)
void LoadAuctionItems ()
void LoadAuctions ()
void AddAItem (Item *it)
bool RemoveAItem (uint32 id)
void Update ()
Static Public Member Functions
static void SendAuctionSuccessfulMail (AuctionEntry *auction)
static uint32 GetAuctionDeposit (AuctionHouseEntry const *entry, uint32 time, Item *pItem)
static uint32 GetAuctionHouseTeam (AuctionHouseEntry const *house)
static AuctionHouseEntry const * GetAuctionHouseEntry (Unit *unit)
Private Attributes
AuctionHouseObject mAuctions [MAX_AUCTION_HOUSE_TYPE]
ItemMap mAitems
Detailed Description
Definition at line 158 of file AuctionHouseMgr.h.
Member Typedef Documentation
ItemMap
typedef std::unordered_map<uint32, Item*> AuctionHouseMgr::ItemMap
Definition at line 164 of file AuctionHouseMgr.h.
Constructor & Destructor Documentation
AuctionHouseMgr()
AuctionHouseMgr::AuctionHouseMgr ()
Definition at line 41 of file AuctionHouseMgr.cpp.
~AuctionHouseMgr()
AuctionHouseMgr::~AuctionHouseMgr ()
Definition at line 45 of file AuctionHouseMgr.cpp.
References mAitems.
Member Function Documentation
AddAItem()
void AuctionHouseMgr::AddAItem (Item * it)
Definition at line 461 of file AuctionHouseMgr.cpp.
References Object::GetGUIDLow(), mAitems, and MANGOS_ASSERT.
Referenced by LoadAuctionItems().
GetAItem()
Item* AuctionHouseMgr::GetAItem (uint32 id) inline
Definition at line 169 of file AuctionHouseMgr.h.
References mAitems.
Referenced by LoadAuctions(), SendAuctionExpiredMail(), and SendAuctionWonMail().
GetAuctionDeposit()
uint32 AuctionHouseMgr::GetAuctionDeposit (AuctionHouseEntry const * entry, uint32 time, Item * pItem) static
Definition at line 65 of file AuctionHouseMgr.cpp.
References CONFIG_FLOAT_RATE_AUCTION_DEPOSIT, CONFIG_UINT32_AUCTION_DEPOSIT_MIN, AuctionHouseEntry::depositPercent, Item::GetCount(), Item::GetProto(), MIN_AUCTION_TIME, ItemPrototype::SellPrice, and sWorld.
Referenced by WorldSession::HandleAuctionSellItem().
GetAuctionHouseEntry()
AuctionHouseEntry const * AuctionHouseMgr::GetAuctionHouseEntry (Unit * unit) static
Definition at line 502 of file AuctionHouseMgr.cpp.
References ALLIANCE, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_AUCTION, FACTION_GROUP_MASK_ALLIANCE, FACTION_GROUP_MASK_HORDE, FactionTemplateEntry::factionGroupMask, Player::GetAuctionAccessMode(), Unit::GetFaction(), Object::GetTypeId(), HORDE, sAuctionHouseStore, sFactionTemplateStore, sWorld, and TYPEID_UNIT.
Referenced by WorldSession::GetCheckedAuctionHouseForAuctioneer(), and WorldSession::SendAuctionHello().
GetAuctionHouseTeam()
uint32 AuctionHouseMgr::GetAuctionHouseTeam (AuctionHouseEntry const * house) static
Definition at line 485 of file AuctionHouseMgr.cpp.
References ALLIANCE, HORDE, and AuctionHouseEntry::houseId.
Referenced by GetAuctionsMap().
GetAuctionsMap() [1/2]
AuctionHouseObject * AuctionHouseMgr::GetAuctionsMap (AuctionHouseEntry const * house)
Definition at line 51 of file AuctionHouseMgr.cpp.
References ALLIANCE, AUCTION_HOUSE_ALLIANCE, AUCTION_HOUSE_HORDE, AUCTION_HOUSE_NEUTRAL, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_AUCTION, GetAuctionHouseTeam(), HORDE, mAuctions, and sWorld.
GetAuctionsMap() [2/2]
AuctionHouseObject* AuctionHouseMgr::GetAuctionsMap (AuctionHouseType houseType) inline
Definition at line 166 of file AuctionHouseMgr.h.
References mAuctions.
Referenced by LoadAuctions().
LoadAuctionItems()
void AuctionHouseMgr::LoadAuctionItems ()
Definition at line 264 of file AuctionHouseMgr.cpp.
References AddAItem(), CharacterDatabase, QueryResult::Fetch(), ObjectMgr::GetItemPrototype(), QueryResult::GetRowCount(), Field::GetUInt32(), Item::LoadFromDB(), NewItemOrBag(), QueryResult::NextRow(), Database::Query(), sLog, and BarGoLink::step().
LoadAuctions()
void AuctionHouseMgr::LoadAuctions ()
Definition at line 315 of file AuctionHouseMgr.cpp.
References AuctionHouseObject::AddAuction(), MailDraft::AddItem(), AUCTION_CANCELED, AuctionEntry::auctionHouseEntry, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CharacterDatabase, AuctionEntry::DeleteFromDB(), AuctionEntry::deposit, AuctionEntry::expireTime, QueryResult::Fetch(), GetAItem(), GetAuctionsMap(), Item::GetCount(), Object::GetEntry(), Item::GetItemRandomPropertyId(), Field::GetUInt32(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemGuidLow, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, LANG_UNKNOWN, MAIL_CHECK_MASK_COPIED, AuctionEntry::moneyDeliveryTime, QueryResult::NextRow(), AuctionEntry::owner, AuctionEntry::ownerName, Database::PExecute(), Database::Query(), RemoveAItem(), sAuctionHouseStore, MailDraft::SendMailTo(), sLog, sObjectMgr, AuctionEntry::startbid, BarGoLink::step(), and Utf8toWStr().
RemoveAItem()
bool AuctionHouseMgr::RemoveAItem (uint32 id)
Definition at line 468 of file AuctionHouseMgr.cpp.
References mAitems.
Referenced by LoadAuctions(), SendAuctionExpiredMail(), and SendAuctionWonMail().
SendAuctionExpiredMail()
void AuctionHouseMgr::SendAuctionExpiredMail (AuctionEntry * auction)
Definition at line 220 of file AuctionHouseMgr.cpp.
References MailDraft::AddItem(), AUCTION_EXPIRED, CharacterDatabase, GetAItem(), Player::GetSession(), HIGHGUID_PLAYER, AuctionEntry::Id, AuctionEntry::itemCount, AuctionEntry::itemGuidLow, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, Database::PExecute(), RemoveAItem(), WorldSession::SendAuctionOwnerNotification(), MailDraft::SendMailTo(), sLog, and sObjectMgr.
SendAuctionSuccessfulMail()
void AuctionHouseMgr::SendAuctionSuccessfulMail (AuctionEntry * auction) static
Definition at line 179 of file AuctionHouseMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_GOLD_EARNED_BY_AUCTIONS, ACHIEVEMENT_CRITERIA_TYPE_HIGHEST_AUCTION_SOLD, AUCTION_SUCCESSFUL, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, DEBUG_LOG, AuctionEntry::deposit, Player::GetAchievementMgr(), AuctionEntry::GetAuctionCut(), HIGHGUID_PLAYER, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, MailDraft::SendMailTo(), MailDraft::SetMoney(), sObjectMgr, and AchievementMgr::UpdateAchievementCriteria().
SendAuctionWonMail()
void AuctionHouseMgr::SendAuctionWonMail (AuctionEntry * auction)
Definition at line 80 of file AuctionHouseMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_WON_AUCTIONS, MailDraft::AddItem(), AUCTION_WON, AuctionEntry::bid, AuctionEntry::bidder, AuctionEntry::buyout, CharacterDatabase, CONFIG_BOOL_GM_LOG_TRADE, DEBUG_LOG, WorldSession::GetAccountId(), Player::GetAchievementMgr(), GetAItem(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), HIGHGUID_PLAYER, AuctionEntry::itemCount, AuctionEntry::itemGuidLow, AuctionEntry::itemRandomPropertyId, AuctionEntry::itemTemplate, LANG_UNKNOWN, MAIL_CHECK_MASK_COPIED, AuctionEntry::owner, Database::PExecute(), RemoveAItem(), sAccountMgr, SEC_PLAYER, WorldSession::SendAuctionBidderNotification(), WorldSession::SendAuctionOwnerNotification(), MailDraft::SendMailTo(), sLog, sObjectMgr, sWorld, and AchievementMgr::UpdateAchievementCriteria().
Update()
void AuctionHouseMgr::Update ()
Definition at line 479 of file AuctionHouseMgr.cpp.
References mAuctions.
Field Documentation
mAitems
ItemMap AuctionHouseMgr::mAitems private
Definition at line 201 of file AuctionHouseMgr.h.
Referenced by AddAItem(), GetAItem(), RemoveAItem(), and ~AuctionHouseMgr().
mAuctions
AuctionHouseObject AuctionHouseMgr::mAuctions[MAX_AUCTION_HOUSE_TYPE] private
Definition at line 199 of file AuctionHouseMgr.h.
Referenced by GetAuctionsMap(), and Update().
The documentation for this class was generated from the following files:
AuctionHouseMgr.h
AuctionHouseMgr.cpp