CMaNGOS_WoTLK: QueryResultMysql Class Reference
QueryResultMysql Class Reference
#include <QueryResultMysql.h>
Public Member Functions
QueryResultMysql (MYSQL_RES *result, MYSQL_FIELD *fields, uint64 rowCount, uint32 fieldCount)
~QueryResultMysql ()
bool NextRow () override
Public Member Functions inherited from QueryResult
QueryResult (uint64 rowCount, uint32 fieldCount)
virtual ~QueryResult ()
Field * Fetch () const
const Field & operator[] (int index) const
uint32 GetFieldCount () const
uint64 GetRowCount () const
Private Member Functions
enum Field::DataTypes ConvertNativeType (enum_field_types mysqlType) const
void EndQuery ()
Private Attributes
MYSQL_RES * mResult
Additional Inherited Members
Protected Attributes inherited from QueryResult
Field * mCurrentRow
uint32 mFieldCount
uint64 mRowCount
Detailed Description
Definition at line 32 of file QueryResultMysql.h.
Constructor & Destructor Documentation
QueryResultMysql()
QueryResultMysql::QueryResultMysql (MYSQL_RES * result, MYSQL_FIELD * fields, uint64 rowCount, uint32 fieldCount)
Definition at line 24 of file QueryResultMysql.cpp.
References ConvertNativeType(), MANGOS_ASSERT, QueryResult::mCurrentRow, and QueryResult::mFieldCount.
~QueryResultMysql()
QueryResultMysql::~QueryResultMysql ()
Definition at line 34 of file QueryResultMysql.cpp.
References EndQuery().
Member Function Documentation
ConvertNativeType()
enum Field::DataTypes QueryResultMysql::ConvertNativeType (enum_field_types mysqlType) const private
Definition at line 57 of file QueryResultMysql.cpp.
References QueryResult::mCurrentRow, and mResult.
Referenced by QueryResultMysql().
EndQuery()
void QueryResultMysql::EndQuery () private
Definition at line 57 of file QueryResultMysql.cpp.
Referenced by NextRow(), and ~QueryResultMysql().
NextRow()
bool QueryResultMysql::NextRow () override virtual
Implements QueryResult.
Definition at line 39 of file QueryResultMysql.cpp.
References EndQuery(), QueryResult::mCurrentRow, QueryResult::mFieldCount, and mResult.
Referenced by MySQLConnection::Query(), and MySQLConnection::QueryNamed().
Field Documentation
mResult
MYSQL_RES* QueryResultMysql::mResult private
Definition at line 45 of file QueryResultMysql.h.
Referenced by ConvertNativeType(), and NextRow().
The documentation for this class was generated from the following files:
QueryResultMysql.h
QueryResultMysql.cpp