CMaNGOS_WoTLK: instance_scarlet_monastery Class Reference
instance_scarlet_monastery Class Reference
#include <scarlet_monastery.h>
Public Member Functions
instance_scarlet_monastery (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void OnObjectSpawn (GameObject *go) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiData) const override
bool DoHandleAreaTrigger (AreaTriggerEntry const *areaTrigger)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
GuidSet m_sAshbringerFriendlyGuids
uint32 m_auiEncounter [MAX_ENCOUNTER]
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 43 of file scarlet_monastery.h.
Constructor & Destructor Documentation
instance_scarlet_monastery()
instance_scarlet_monastery::instance_scarlet_monastery (Map * pMap)
Definition at line 29 of file instance_scarlet_monastery.cpp.
References Initialize().
Member Function Documentation
DoHandleAreaTrigger()
bool instance_scarlet_monastery::DoHandleAreaTrigger (AreaTriggerEntry const * areaTrigger)
Definition at line 184 of file instance_scarlet_monastery.cpp.
References AREATRIGGER_CATHEDRAL_ENTRANCE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), GetData(), AreaTriggerEntry::id, IN_PROGRESS, NOT_STARTED, NPC_MOGRAINE, SAY_ASHBRINGER_ENTRANCE, SetData(), and TYPE_ASHBRINGER_EVENT.
GetData()
uint32 instance_scarlet_monastery::GetData (uint32 uiData) const override virtual
Reimplemented from InstanceData.
Definition at line 169 of file instance_scarlet_monastery.cpp.
References m_auiEncounter, TYPE_ASHBRINGER_EVENT, and TYPE_MOGRAINE_AND_WHITE_EVENT.
Referenced by DoHandleAreaTrigger(), boss_high_inquisitor_whitemaneAI::EnterCombat(), boss_scarlet_commander_mograineAI::EnterEvadeMode(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), boss_scarlet_commander_mograineAI::HandleLayOnHandsTimer(), OnCreatureRespawn(), OnObjectSpawn(), and boss_scarlet_commander_mograineAI::SpellHit().
Initialize()
void instance_scarlet_monastery::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 34 of file instance_scarlet_monastery.cpp.
References m_auiEncounter.
Referenced by instance_scarlet_monastery().
OnCreatureCreate()
void instance_scarlet_monastery::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file instance_scarlet_monastery.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, m_sAshbringerFriendlyGuids, NPC_ABBOT, NPC_CENTURION, NPC_CHAMPION, NPC_CHAPLAIN, NPC_DEFENDER, NPC_FAIRBANKS, NPC_HEADLESS_HORSEMAN_EARTHQUAKE_BUNNY, NPC_MOGRAINE, NPC_MONK, NPC_MYRMIDON, NPC_SORCERER, NPC_VORREL, NPC_WHITEMANE, and NPC_WIZARD.
OnCreatureDeath()
void instance_scarlet_monastery::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 75 of file instance_scarlet_monastery.cpp.
References DoScriptText(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_INTERROGATOR_VISHAS, NPC_VORREL, and SAY_TRIGGER_VORREL.
OnCreatureRespawn()
void instance_scarlet_monastery::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 93 of file instance_scarlet_monastery.cpp.
References GetData(), Unit::GetFaction(), Object::GetObjectGuid(), IN_PROGRESS, Unit::IsAlive(), Unit::IsInCombat(), m_sAshbringerFriendlyGuids, Unit::setFaction(), and TYPE_ASHBRINGER_EVENT.
OnObjectCreate()
void instance_scarlet_monastery::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 85 of file instance_scarlet_monastery.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_CHAPEL_DOOR, GO_WHITEMANE_DOOR, and ScriptedInstance::m_goEntryGuidStore.
OnObjectSpawn()
void instance_scarlet_monastery::OnObjectSpawn (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 101 of file instance_scarlet_monastery.cpp.
References ScriptedInstance::DoUseDoorOrButton(), GetData(), Object::GetEntry(), GO_CHAPEL_DOOR, IN_PROGRESS, and TYPE_ASHBRINGER_EVENT.
OnPlayerEnter()
void instance_scarlet_monastery::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 39 of file instance_scarlet_monastery.cpp.
References LFGData::GetDungeon(), Player::GetLfgData(), Map::GetVariableManager(), InstanceData::instance, SEASONAL_HEADLESS_HORSEMAN, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_HEADLESS_HORSEMAN_DUNGEON.
SetData()
void instance_scarlet_monastery::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 108 of file instance_scarlet_monastery.cpp.
References ScriptedInstance::DoUseDoorOrButton(), FAIL, Creature::ForcedDespawn(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CHAPEL_DOOR, GO_WHITEMANE_DOOR, IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), Unit::IsInCombat(), m_auiEncounter, m_sAshbringerFriendlyGuids, NOT_STARTED, NPC_MOGRAINE, NPC_WHITEMANE, Creature::SetRespawnDelay(), TYPE_ASHBRINGER_EVENT, and TYPE_MOGRAINE_AND_WHITE_EVENT.
Referenced by DoHandleAreaTrigger(), boss_scarlet_commander_mograineAI::EnterEvadeMode(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), and boss_scarlet_commander_mograineAI::SpellHit().
Field Documentation
m_auiEncounter
uint32 instance_scarlet_monastery::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 65 of file scarlet_monastery.h.
Referenced by GetData(), Initialize(), and SetData().
m_sAshbringerFriendlyGuids
GuidSet instance_scarlet_monastery::m_sAshbringerFriendlyGuids private
Definition at line 64 of file scarlet_monastery.h.
Referenced by OnCreatureCreate(), OnCreatureRespawn(), and SetData().
The documentation for this class was generated from the following files:
scarlet_monastery.h
instance_scarlet_monastery.cpp