CMaNGOS_WoTLK: SqlTransaction Class Reference
SqlTransaction Class Reference
#include <SqlOperations.h>
Public Member Functions
SqlTransaction ()
~SqlTransaction ()
void DelayExecute (SqlOperation *sql)
bool Execute (SqlConnection *conn) override
Public Member Functions inherited from SqlOperation
virtual void OnRemove ()
virtual ~SqlOperation ()
Private Attributes
std::vector< SqlOperation * > m_queue
Detailed Description
Definition at line 57 of file SqlOperations.h.
Constructor & Destructor Documentation
SqlTransaction()
SqlTransaction::SqlTransaction () inline
Definition at line 63 of file SqlOperations.h.
~SqlTransaction()
SqlTransaction::~SqlTransaction ()
Definition at line 37 of file SqlOperations.cpp.
References m_queue.
Member Function Documentation
DelayExecute()
void SqlTransaction::DelayExecute (SqlOperation * sql) inline
Definition at line 66 of file SqlOperations.h.
References m_queue.
Execute()
bool SqlTransaction::Execute (SqlConnection * conn) override virtual
Implements SqlOperation.
Definition at line 46 of file SqlOperations.cpp.
References SqlConnection::BeginTransaction(), SqlConnection::CommitTransaction(), SqlOperation::Execute(), LOCK_DB_CONN, m_queue, and SqlConnection::RollbackTransaction().
Field Documentation
m_queue
std::vector<SqlOperation* > SqlTransaction::m_queue private
Definition at line 60 of file SqlOperations.h.
Referenced by DelayExecute(), Execute(), and ~SqlTransaction().
The documentation for this class was generated from the following files:
SqlOperations.h
SqlOperations.cpp