CMaNGOS_WoTLK: GridMap Class Reference
GridMap Class Reference
#include <GridMap.h>
Public Member Functions
GridMap ()
~GridMap ()
bool loadData (char const *filename)
void unloadData ()
bool IsFullyLoaded () const
void SetFullyLoaded ()
uint16 getArea (float x, float y) const
float getHeight (float x, float y) const
float getLiquidLevel (float x, float y) const
uint8 getTerrainType (float x, float y) const
GridMapLiquidStatus getLiquidStatus (float x, float y, float z, uint8 ReqLiquidType, GridMapLiquidData *data=nullptr, float collisionHeight=2.03128f)
Static Public Member Functions
static bool ExistMap (uint32 mapid, int gx, int gy)
static bool ExistVMap (uint32 mapid, int gx, int gy)
Private Types
typedef float(GridMap::* pGetHeightPtr) (float x, float y) const
Private Member Functions
bool loadAreaData (FILE *in, uint32 offset, uint32 size)
bool loadHeightData (FILE *in, uint32 offset, uint32 size)
bool loadGridMapLiquidData (FILE *in, uint32 offset, uint32 size)
bool loadHolesData (FILE *in, uint32 offset, uint32 size)
bool isHole (int row, int col) const
float getHeightFromFloat (float x, float y) const
float getHeightFromUint16 (float x, float y) const
float getHeightFromUint8 (float x, float y) const
float getHeightFromFlat (float x, float y) const
Private Attributes
uint32 m_flags
uint16 m_gridArea
uint16 * m_area_map
float m_gridHeight
float m_gridIntHeightMultiplier
union {
float * m_V9
uint16 * m_uint16_V9
uint8 * m_uint8_V9
};
union {
float * m_V8
uint16 * m_uint16_V8
uint8 * m_uint8_V8
};
uint16 m_liquidGlobalEntry
uint8 m_liquidGlobalFlags
uint8 m_liquid_offX
uint8 m_liquid_offY
uint8 m_liquid_width
uint8 m_liquid_height
float m_liquidLevel
uint16 * m_liquidEntry
uint8 * m_liquidFlags
float * m_liquid_map
uint16 * m_holes
bool m_fullyLoaded
pGetHeightPtr m_gridGetHeight
Detailed Description
Definition at line 45 of file GridMap.h.
Member Typedef Documentation
pGetHeightPtr
typedef float(GridMap::* GridMap::pGetHeightPtr) (float x, float y) const private
Definition at line 94 of file GridMap.h.
Constructor & Destructor Documentation
GridMap()
GridMap::GridMap ()
Definition at line 43 of file GridMap.cpp.
References getHeightFromFlat(), INVALID_HEIGHT_VALUE, m_area_map, m_flags, m_fullyLoaded, m_gridArea, m_gridGetHeight, m_gridHeight, m_holes, m_liquid_height, m_liquid_map, m_liquid_offX, m_liquid_offY, m_liquid_width, m_liquidEntry, m_liquidFlags, m_liquidGlobalEntry, m_liquidGlobalFlags, m_liquidLevel, m_V8, and m_V9.
~GridMap()
GridMap::~GridMap ()
Definition at line 75 of file GridMap.cpp.
References unloadData().
Member Function Documentation
ExistMap()
bool GridMap::ExistMap (uint32 mapid, int gx, int gy) static
Definition at line 660 of file GridMap.cpp.
References GridMapFileHeader::buildMagic, IsAcceptableClientBuild(), MAP_MAGIC, MAP_VERSION_MAGIC, GridMapFileHeader::mapMagic, sLog, sWorld, and GridMapFileHeader::versionMagic.
Referenced by MapManager::ExistMapAndVMap(), and ChatHandler::HandleGPSCommand().
ExistVMap()
bool GridMap::ExistVMap (uint32 mapid, int gx, int gy) static
Definition at line 692 of file GridMap.cpp.
References VMAP::VMapFactory::createOrGetVMapManager(), sLog, and sWorld.
Referenced by MapManager::ExistMapAndVMap(), and ChatHandler::HandleGPSCommand().
getArea()
uint16 GridMap::getArea (float x, float y) const
Definition at line 277 of file GridMap.cpp.
References m_area_map, m_gridArea, and SIZE_OF_GRIDS.
Referenced by getLiquidStatus().
getHeight()
float GridMap::getHeight (float x, float y) const inline
Definition at line 115 of file GridMap.h.
Referenced by getLiquidStatus().
getHeightFromFlat()
float GridMap::getHeightFromFlat (float x, float y) const private
Definition at line 289 of file GridMap.cpp.
References m_gridHeight.
Referenced by GridMap(), loadHeightData(), and unloadData().
getHeightFromFloat()
float GridMap::getHeightFromFloat (float x, float y) const private
Definition at line 309 of file GridMap.cpp.
References INVALID_HEIGHT_VALUE, isHole(), m_holes, m_V8, m_V9, MAP_RESOLUTION, and SIZE_OF_GRIDS.
Referenced by loadHeightData().
getHeightFromUint16()
float GridMap::getHeightFromUint16 (float x, float y) const private
Definition at line 462 of file GridMap.cpp.
References m_gridHeight, m_gridIntHeightMultiplier, m_uint16_V8, m_uint16_V9, MAP_RESOLUTION, and SIZE_OF_GRIDS.
Referenced by loadHeightData().
getHeightFromUint8()
float GridMap::getHeightFromUint8 (float x, float y) const private
Definition at line 394 of file GridMap.cpp.
References m_gridHeight, m_gridIntHeightMultiplier, m_uint8_V8, m_uint8_V9, MAP_RESOLUTION, and SIZE_OF_GRIDS.
Referenced by loadHeightData().
getLiquidLevel()
float GridMap::getLiquidLevel (float x, float y) const
Definition at line 530 of file GridMap.cpp.
References INVALID_HEIGHT_VALUE, m_liquid_height, m_liquid_map, m_liquid_offX, m_liquid_offY, m_liquid_width, m_liquidLevel, MAP_RESOLUTION, and SIZE_OF_GRIDS.
getLiquidStatus()
GridMapLiquidStatus GridMap::getLiquidStatus (float x, float y, float z, uint8 ReqLiquidType, GridMapLiquidData * data = nullptr, float collisionHeight = 2.03128f)
Definition at line 563 of file GridMap.cpp.
References GridMapLiquidData::depth_level, GridMapLiquidData::entry, getArea(), GetAreaEntryByAreaID(), getHeight(), GridMapLiquidData::level, LIQUID_MAP_ABOVE_WATER, LIQUID_MAP_IN_WATER, LIQUID_MAP_NO_WATER, LIQUID_MAP_UNDER_WATER, LIQUID_MAP_WATER_WALK, m_liquid_height, m_liquid_map, m_liquid_offX, m_liquid_offY, m_liquid_width, m_liquidEntry, m_liquidFlags, m_liquidGlobalEntry, m_liquidGlobalFlags, m_liquidLevel, MAP_LIQUID_TYPE_DEEP_WATER, MAP_RESOLUTION, sAreaStore, SIZE_OF_GRIDS, sLiquidTypeStore, and GridMapLiquidData::type_flags.
getTerrainType()
uint8 GridMap::getTerrainType (float x, float y) const
Definition at line 550 of file GridMap.cpp.
References m_liquidFlags, m_liquidGlobalFlags, and SIZE_OF_GRIDS.
IsFullyLoaded()
bool GridMap::IsFullyLoaded () const inline
Definition at line 108 of file GridMap.h.
References m_fullyLoaded.
Referenced by TerrainInfo::GetGrid().
isHole()
bool GridMap::isHole (int row, int col) const private
Definition at line 294 of file GridMap.cpp.
References holetab_h, holetab_v, and m_holes.
Referenced by getHeightFromFloat().
loadAreaData()
bool GridMap::loadAreaData (FILE * in, uint32 offset, uint32 size) private
Definition at line 160 of file GridMap.cpp.
References GridMapAreaHeader::flags, GridMapAreaHeader::fourcc, GridMapAreaHeader::gridArea, m_area_map, m_gridArea, MAP_AREA_MAGIC, and MAP_AREA_NO_AREA.
Referenced by loadData().
loadData()
bool GridMap::loadData (char const * filename)
Definition at line 80 of file GridMap.cpp.
References GridMapFileHeader::areaMapOffset, GridMapFileHeader::areaMapSize, GridMapFileHeader::buildMagic, DEBUG_FILTER_LOG, GridMapFileHeader::heightMapOffset, GridMapFileHeader::heightMapSize, GridMapFileHeader::holesOffset, GridMapFileHeader::holesSize, IsAcceptableClientBuild(), GridMapFileHeader::liquidMapOffset, GridMapFileHeader::liquidMapSize, loadAreaData(), loadGridMapLiquidData(), loadHeightData(), loadHolesData(), LOG_FILTER_MAP_LOADING, MAP_MAGIC, MAP_VERSION_MAGIC, GridMapFileHeader::mapMagic, sLog, unloadData(), and GridMapFileHeader::versionMagic.
Referenced by TerrainInfo::LoadMapAndVMap().
loadGridMapLiquidData()
bool GridMap::loadGridMapLiquidData (FILE * in, uint32 offset, uint32 size) private
Definition at line 238 of file GridMap.cpp.
References GridMapLiquidHeader::flags, GridMapLiquidHeader::fourcc, GridMapLiquidHeader::height, GridMapLiquidHeader::liquidFlags, GridMapLiquidHeader::liquidLevel, GridMapLiquidHeader::liquidType, m_liquid_height, m_liquid_map, m_liquid_offX, m_liquid_offY, m_liquid_width, m_liquidEntry, m_liquidFlags, m_liquidGlobalEntry, m_liquidGlobalFlags, m_liquidLevel, MAP_LIQUID_MAGIC, MAP_LIQUID_NO_HEIGHT, MAP_LIQUID_NO_TYPE, GridMapLiquidHeader::offsetX, GridMapLiquidHeader::offsetY, and GridMapLiquidHeader::width.
Referenced by loadData().
loadHeightData()
bool GridMap::loadHeightData (FILE * in, uint32 offset, uint32 size) private
Definition at line 181 of file GridMap.cpp.
References GridMapHeightHeader::flags, GridMapHeightHeader::fourcc, getHeightFromFlat(), getHeightFromFloat(), getHeightFromUint16(), getHeightFromUint8(), GridMapHeightHeader::gridHeight, GridMapHeightHeader::gridMaxHeight, m_gridGetHeight, m_gridHeight, m_gridIntHeightMultiplier, m_uint16_V8, m_uint16_V9, m_uint8_V8, m_uint8_V9, m_V8, m_V9, MAP_HEIGHT_AS_INT16, MAP_HEIGHT_AS_INT8, MAP_HEIGHT_MAGIC, and MAP_HEIGHT_NO_HEIGHT.
Referenced by loadData().
loadHolesData()
bool GridMap::loadHolesData (FILE * in, uint32 offset, uint32 size) private
Definition at line 230 of file GridMap.cpp.
References m_holes.
Referenced by loadData().
SetFullyLoaded()
void GridMap::SetFullyLoaded () inline
Definition at line 109 of file GridMap.h.
References m_fullyLoaded.
Referenced by TerrainInfo::LoadMapAndVMap().
unloadData()
void GridMap::unloadData ()
Definition at line 147 of file GridMap.cpp.
References getHeightFromFlat(), m_area_map, m_gridGetHeight, m_holes, m_liquid_map, m_liquidEntry, m_liquidFlags, m_V8, and m_V9.
Referenced by TerrainInfo::CleanUpGrids(), loadData(), and ~GridMap().
Field Documentation
union { ... }
union { ... }
m_area_map
uint16* GridMap::m_area_map private
Definition at line 52 of file GridMap.h.
Referenced by getArea(), GridMap(), loadAreaData(), and unloadData().
m_flags
uint32 GridMap::m_flags private
Definition at line 48 of file GridMap.h.
Referenced by GridMap().
m_fullyLoaded
bool GridMap::m_fullyLoaded private
Definition at line 85 of file GridMap.h.
Referenced by GridMap(), IsFullyLoaded(), and SetFullyLoaded().
m_gridArea
uint16 GridMap::m_gridArea private
Definition at line 51 of file GridMap.h.
Referenced by getArea(), GridMap(), and loadAreaData().
m_gridGetHeight
pGetHeightPtr GridMap::m_gridGetHeight private
Definition at line 95 of file GridMap.h.
Referenced by GridMap(), loadHeightData(), and unloadData().
m_gridHeight
float GridMap::m_gridHeight private
Definition at line 55 of file GridMap.h.
Referenced by getHeightFromFlat(), getHeightFromUint16(), getHeightFromUint8(), GridMap(), and loadHeightData().
m_gridIntHeightMultiplier
float GridMap::m_gridIntHeightMultiplier private
Definition at line 56 of file GridMap.h.
Referenced by getHeightFromUint16(), getHeightFromUint8(), and loadHeightData().
m_holes
uint16* GridMap::m_holes private
Definition at line 82 of file GridMap.h.
Referenced by getHeightFromFloat(), GridMap(), isHole(), loadHolesData(), and unloadData().
m_liquid_height
uint8 GridMap::m_liquid_height private
Definition at line 76 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_liquid_map
float* GridMap::m_liquid_map private
Definition at line 80 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), loadGridMapLiquidData(), and unloadData().
m_liquid_offX
uint8 GridMap::m_liquid_offX private
Definition at line 73 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_liquid_offY
uint8 GridMap::m_liquid_offY private
Definition at line 74 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_liquid_width
uint8 GridMap::m_liquid_width private
Definition at line 75 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_liquidEntry
uint16* GridMap::m_liquidEntry private
Definition at line 78 of file GridMap.h.
Referenced by getLiquidStatus(), GridMap(), loadGridMapLiquidData(), and unloadData().
m_liquidFlags
uint8* GridMap::m_liquidFlags private
Definition at line 79 of file GridMap.h.
Referenced by getLiquidStatus(), getTerrainType(), GridMap(), loadGridMapLiquidData(), and unloadData().
m_liquidGlobalEntry
uint16 GridMap::m_liquidGlobalEntry private
Definition at line 71 of file GridMap.h.
Referenced by getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_liquidGlobalFlags
uint8 GridMap::m_liquidGlobalFlags private
Definition at line 72 of file GridMap.h.
Referenced by getLiquidStatus(), getTerrainType(), GridMap(), and loadGridMapLiquidData().
m_liquidLevel
float GridMap::m_liquidLevel private
Definition at line 77 of file GridMap.h.
Referenced by getLiquidLevel(), getLiquidStatus(), GridMap(), and loadGridMapLiquidData().
m_uint16_V8
uint16* GridMap::m_uint16_V8
Definition at line 66 of file GridMap.h.
Referenced by getHeightFromUint16(), and loadHeightData().
m_uint16_V9
uint16* GridMap::m_uint16_V9
Definition at line 60 of file GridMap.h.
Referenced by getHeightFromUint16(), and loadHeightData().
m_uint8_V8
uint8* GridMap::m_uint8_V8
Definition at line 67 of file GridMap.h.
Referenced by getHeightFromUint8(), and loadHeightData().
m_uint8_V9
uint8* GridMap::m_uint8_V9
Definition at line 61 of file GridMap.h.
Referenced by getHeightFromUint8(), and loadHeightData().
m_V8
float* GridMap::m_V8
Definition at line 65 of file GridMap.h.
Referenced by getHeightFromFloat(), GridMap(), loadHeightData(), and unloadData().
m_V9
float* GridMap::m_V9
Definition at line 59 of file GridMap.h.
Referenced by getHeightFromFloat(), GridMap(), loadHeightData(), and unloadData().
The documentation for this class was generated from the following files:
GridMap.h
GridMap.cpp