CMaNGOS_WoTLK: AuctionHouseBot Class Reference
AuctionHouseBot Class Reference
#include <AuctionHouseBot.h>
Public Member Functions
AuctionHouseBot ()
~AuctionHouseBot ()
void Initialize ()
void SetConfigFileName (const std::string &filename)
void Update ()
bool ReloadAllConfig ()
void Rebuild (bool all)
void PrepareStatusInfos (AuctionHouseBotStatusInfo &statusInfo) const
void SetItemData (uint32 item, AuctionHouseBotItemData &itemData, bool reset=false)
AuctionHouseBotItemData GetItemData (uint32 item)
Private Member Functions
uint32 GetMinMaxConfig (const char *config, uint32 minValue, uint32 maxValue, uint32 defaultValue)
void ParseLootConfig (char const *fieldname, std::vector< int32 > &lootConfig)
void FillUintVectorFromQuery (char const *query, std::vector< uint32 > &lootTemplates)
void ParseItemValueConfig (char const *fieldname, std::vector< uint32 > &itemValues)
void AddLootToItemMap (LootStore *store, std::vector< int32 > &lootConfig, std::vector< uint32 > &lootTemplates, std::unordered_map< uint32, uint32 > &itemMap)
uint32 CalculateBuyoutPrice (ItemPrototype const *prototype)
uint32 ValueWithVariance (uint32 itemValue)
Private Attributes
std::string m_configFileName
Config m_ahBotCfg
uint32 m_houseAction
uint32 m_chanceSell
uint32 m_chanceBuy
std::vector< int32 > m_creatureLootNormalConfig
std::vector< int32 > m_creatureLootRareConfig
std::vector< int32 > m_creatureLootEliteConfig
std::vector< int32 > m_creatureLootRareEliteConfig
std::vector< int32 > m_creatureLootWorldBossConfig
std::vector< int32 > m_disenchantLootConfig
std::vector< int32 > m_fishingLootConfig
std::vector< int32 > m_gameobjectLootConfig
std::vector< int32 > m_skinningLootConfig
std::vector< int32 > m_professionItemsConfig
std::vector< std::vector< uint32 > > m_itemValue = std::vector<std::vector<uint32>>(MAX_ITEM_QUALITY, std::vector<uint32>(MAX_ITEM_CLASS))
bool m_vendorValue
uint32 m_valueVariance
uint32 m_auctionBidMin
uint32 m_auctionBidMax
uint32 m_auctionTimeMin
uint32 m_auctionTimeMax
uint32 m_buyValue
std::vector< uint32 > m_creatureLootNormalTemplates
std::vector< uint32 > m_creatureLootRareTemplates
std::vector< uint32 > m_creatureLootEliteTemplates
std::vector< uint32 > m_creatureLootRareEliteTemplates
std::vector< uint32 > m_creatureLootWorldBossTemplates
std::vector< uint32 > m_disenchantLootTemplates
std::vector< uint32 > m_fishingLootTemplates
std::vector< uint32 > m_gameobjectLootTemplates
std::vector< uint32 > m_skinningLootTemplates
std::vector< uint32 > m_professionItems
std::unordered_set< uint32 > m_vendorItems
std::unordered_map< uint32, AuctionHouseBotItemData > m_itemData
Detailed Description
Definition at line 45 of file AuctionHouseBot.h.
Constructor & Destructor Documentation
AuctionHouseBot()
AuctionHouseBot::AuctionHouseBot ()
Definition at line 33 of file AuctionHouseBot.cpp.
~AuctionHouseBot()
AuctionHouseBot::~AuctionHouseBot ()
Definition at line 37 of file AuctionHouseBot.cpp.
Member Function Documentation
AddLootToItemMap()
void AuctionHouseBot::AddLootToItemMap (LootStore * store, std::vector< int32 > & lootConfig, std::vector< uint32 > & lootTemplates, std::unordered_map< uint32, uint32 > & itemMap) private
Definition at line 463 of file AuctionHouseBot.cpp.
References LootItem::count, LootStore::GetLootFor(), LootStore::IsRatesAllowed(), LootItem::itemId, LOOT_DEBUG, LootTemplate::Process(), and urand().
Referenced by Update().
CalculateBuyoutPrice()
uint32 AuctionHouseBot::CalculateBuyoutPrice (ItemPrototype const * prototype) private
Definition at line 486 of file AuctionHouseBot.cpp.
References ItemPrototype::BuyPrice, ItemPrototype::Class, ITEM_QUALITY_NORMAL, ItemPrototype::ItemId, m_itemValue, m_vendorItems, m_vendorValue, ItemPrototype::Quality, and ItemPrototype::SellPrice.
Referenced by GetItemData(), and Update().
FillUintVectorFromQuery()
void AuctionHouseBot::FillUintVectorFromQuery (char const * query, std::vector< uint32 > & lootTemplates) private
Definition at line 433 of file AuctionHouseBot.cpp.
References Field::GetUInt32(), Database::PQuery(), BarGoLink::step(), and WorldDatabase.
Referenced by Initialize().
GetItemData()
AuctionHouseBotItemData AuctionHouseBot::GetItemData (uint32 item)
Definition at line 370 of file AuctionHouseBot.cpp.
References CalculateBuyoutPrice(), ObjectMgr::GetItemPrototype(), m_itemData, and AuctionHouseBotItemData::Value.
GetMinMaxConfig()
uint32 AuctionHouseBot::GetMinMaxConfig (const char * config, uint32 minValue, uint32 maxValue, uint32 defaultValue) private
Definition at line 383 of file AuctionHouseBot.cpp.
References Config::GetIntDefault(), m_ahBotCfg, and sLog.
Referenced by Initialize().
Initialize()
void AuctionHouseBot::Initialize ()
Definition at line 41 of file AuctionHouseBot.cpp.
References AuctionHouseBotItemData::AddChance, CharacterDatabase, QueryResult::Fetch(), FillUintVectorFromQuery(), Config::GetBoolDefault(), GetMinMaxConfig(), Field::GetUInt32(), ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_NORMAL, ITEM_QUALITY_POOR, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, m_ahBotCfg, m_auctionBidMax, m_auctionBidMin, m_auctionTimeMax, m_auctionTimeMin, m_buyValue, m_chanceBuy, m_chanceSell, m_configFileName, m_creatureLootEliteConfig, m_creatureLootEliteTemplates, m_creatureLootNormalConfig, m_creatureLootNormalTemplates, m_creatureLootRareConfig, m_creatureLootRareEliteConfig, m_creatureLootRareEliteTemplates, m_creatureLootRareTemplates, m_creatureLootWorldBossConfig, m_creatureLootWorldBossTemplates, m_disenchantLootConfig, m_disenchantLootTemplates, m_fishingLootConfig, m_fishingLootTemplates, m_gameobjectLootConfig, m_gameobjectLootTemplates, m_itemData, m_itemValue, m_professionItems, m_professionItemsConfig, m_skinningLootConfig, m_skinningLootTemplates, m_valueVariance, m_vendorItems, m_vendorValue, AuctionHouseBotItemData::MaxAmount, AuctionHouseBotItemData::MinAmount, QueryResult::NextRow(), ParseItemValueConfig(), ParseLootConfig(), Database::PQuery(), Config::SetSource(), sLog, and AuctionHouseBotItemData::Value.
Referenced by ReloadAllConfig().
ParseItemValueConfig()
void AuctionHouseBot::ParseItemValueConfig (char const * fieldname, std::vector< uint32 > & itemValues) private
Definition at line 452 of file AuctionHouseBot.cpp.
References Config::GetStringDefault(), and m_ahBotCfg.
Referenced by Initialize().
ParseLootConfig()
void AuctionHouseBot::ParseLootConfig (char const * fieldname, std::vector< int32 > & lootConfig) private
Definition at line 398 of file AuctionHouseBot.cpp.
References Config::GetStringDefault(), m_ahBotCfg, and sLog.
Referenced by Initialize().
PrepareStatusInfos()
void AuctionHouseBot::PrepareStatusInfos (AuctionHouseBotStatusInfo & statusInfo) const
Definition at line 304 of file AuctionHouseBot.cpp.
References AuctionEntry::itemGuidLow, MAX_AUCTION_HOUSE_TYPE, MAX_ITEM_QUALITY, AuctionEntry::owner, ItemPrototype::Quality, and sAuctionMgr.
Rebuild()
void AuctionHouseBot::Rebuild (bool all)
Definition at line 277 of file AuctionHouseBot.cpp.
References AuctionEntry::bid, AuctionEntry::expireTime, m_auctionTimeMax, m_auctionTimeMin, m_houseAction, MAX_AUCTION_HOUSE_TYPE, AuctionEntry::owner, sAuctionMgr, sLog, sWorld, and Update().
ReloadAllConfig()
bool AuctionHouseBot::ReloadAllConfig ()
Definition at line 271 of file AuctionHouseBot.cpp.
References Initialize().
SetConfigFileName()
void AuctionHouseBot::SetConfigFileName (const std::string & filename) inline
Definition at line 52 of file AuctionHouseBot.h.
References m_configFileName.
SetItemData()
void AuctionHouseBot::SetItemData (uint32 item, AuctionHouseBotItemData & itemData, bool reset = false)
Definition at line 333 of file AuctionHouseBot.cpp.
References AuctionHouseBotItemData::AddChance, SqlStatement::addUInt32(), CharacterDatabase, Database::CreateStatement(), SqlStatement::Execute(), ObjectMgr::GetItemPrototype(), ItemPrototype::GetMaxStackSize(), m_itemData, AuctionHouseBotItemData::MaxAmount, AuctionHouseBotItemData::MinAmount, SqlStatement::PExecute(), and AuctionHouseBotItemData::Value.
Update()
void AuctionHouseBot::Update ()
Definition at line 155 of file AuctionHouseBot.cpp.
References AuctionHouseObject::AddAuction(), AddLootToItemMap(), AUCTION_HOUSE_ALLIANCE, AUCTION_HOUSE_HORDE, AuctionEntry::bid, BIND_QUEST_ITEM, BIND_WHEN_PICKED_UP, ItemPrototype::Bonding, AuctionEntry::buyout, CalculateBuyoutPrice(), ItemPrototype::Class, Item::CreateItem(), ItemPrototype::Flags, AuctionEntry::GetAuctionOutBid(), AuctionHouseObject::GetAuctionsBounds(), Item::GetCount(), ObjectMgr::GetItemPrototype(), ItemPrototype::GetMaxStackSize(), Item::GetProto(), HOUR, ITEM_FLAG_HAS_LOOT, AuctionEntry::itemGuidLow, ItemPrototype::ItemId, LootTemplates_Creature, LootTemplates_Disenchant, LootTemplates_Fishing, LootTemplates_Gameobject, LootTemplates_Skinning, m_auctionBidMax, m_auctionBidMin, m_auctionTimeMax, m_auctionTimeMin, m_chanceBuy, m_chanceSell, m_creatureLootEliteConfig, m_creatureLootEliteTemplates, m_creatureLootNormalConfig, m_creatureLootNormalTemplates, m_creatureLootRareConfig, m_creatureLootRareEliteConfig, m_creatureLootRareEliteTemplates, m_creatureLootRareTemplates, m_creatureLootWorldBossConfig, m_creatureLootWorldBossTemplates, m_disenchantLootConfig, m_disenchantLootTemplates, m_fishingLootConfig, m_fishingLootTemplates, m_gameobjectLootConfig, m_gameobjectLootTemplates, m_houseAction, m_itemData, m_itemValue, m_professionItems, m_professionItemsConfig, m_skinningLootConfig, m_skinningLootTemplates, MAX_AUCTION_HOUSE_TYPE, AuctionEntry::owner, ItemPrototype::Quality, sAuctionHouseStore, sAuctionMgr, AuctionEntry::startbid, AuctionEntry::UpdateBid(), urand(), and ValueWithVariance().
Referenced by Rebuild().
ValueWithVariance()
uint32 AuctionHouseBot::ValueWithVariance (uint32 itemValue) inline private
Definition at line 69 of file AuctionHouseBot.h.
References m_valueVariance, and urand().
Referenced by Update().
Field Documentation
m_ahBotCfg
Config AuctionHouseBot::m_ahBotCfg private
Definition at line 72 of file AuctionHouseBot.h.
Referenced by GetMinMaxConfig(), Initialize(), ParseItemValueConfig(), and ParseLootConfig().
m_auctionBidMax
uint32 AuctionHouseBot::m_auctionBidMax private
Definition at line 94 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_auctionBidMin
uint32 AuctionHouseBot::m_auctionBidMin private
Definition at line 93 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_auctionTimeMax
uint32 AuctionHouseBot::m_auctionTimeMax private
Definition at line 96 of file AuctionHouseBot.h.
Referenced by Initialize(), Rebuild(), and Update().
m_auctionTimeMin
uint32 AuctionHouseBot::m_auctionTimeMin private
Definition at line 95 of file AuctionHouseBot.h.
Referenced by Initialize(), Rebuild(), and Update().
m_buyValue
uint32 AuctionHouseBot::m_buyValue private
Definition at line 97 of file AuctionHouseBot.h.
Referenced by Initialize().
m_chanceBuy
uint32 AuctionHouseBot::m_chanceBuy private
Definition at line 77 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_chanceSell
uint32 AuctionHouseBot::m_chanceSell private
Definition at line 76 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_configFileName
std::string AuctionHouseBot::m_configFileName private
Definition at line 71 of file AuctionHouseBot.h.
Referenced by Initialize(), and SetConfigFileName().
m_creatureLootEliteConfig
std::vector<int32> AuctionHouseBot::m_creatureLootEliteConfig private
Definition at line 81 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootEliteTemplates
std::vector<uint32> AuctionHouseBot::m_creatureLootEliteTemplates private
Definition at line 101 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootNormalConfig
std::vector<int32> AuctionHouseBot::m_creatureLootNormalConfig private
Definition at line 79 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootNormalTemplates
std::vector<uint32> AuctionHouseBot::m_creatureLootNormalTemplates private
Definition at line 99 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootRareConfig
std::vector<int32> AuctionHouseBot::m_creatureLootRareConfig private
Definition at line 80 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootRareEliteConfig
std::vector<int32> AuctionHouseBot::m_creatureLootRareEliteConfig private
Definition at line 82 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootRareEliteTemplates
std::vector<uint32> AuctionHouseBot::m_creatureLootRareEliteTemplates private
Definition at line 102 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootRareTemplates
std::vector<uint32> AuctionHouseBot::m_creatureLootRareTemplates private
Definition at line 100 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootWorldBossConfig
std::vector<int32> AuctionHouseBot::m_creatureLootWorldBossConfig private
Definition at line 83 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_creatureLootWorldBossTemplates
std::vector<uint32> AuctionHouseBot::m_creatureLootWorldBossTemplates private
Definition at line 103 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_disenchantLootConfig
std::vector<int32> AuctionHouseBot::m_disenchantLootConfig private
Definition at line 84 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_disenchantLootTemplates
std::vector<uint32> AuctionHouseBot::m_disenchantLootTemplates private
Definition at line 104 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_fishingLootConfig
std::vector<int32> AuctionHouseBot::m_fishingLootConfig private
Definition at line 85 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_fishingLootTemplates
std::vector<uint32> AuctionHouseBot::m_fishingLootTemplates private
Definition at line 105 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_gameobjectLootConfig
std::vector<int32> AuctionHouseBot::m_gameobjectLootConfig private
Definition at line 86 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_gameobjectLootTemplates
std::vector<uint32> AuctionHouseBot::m_gameobjectLootTemplates private
Definition at line 106 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_houseAction
uint32 AuctionHouseBot::m_houseAction private
Definition at line 74 of file AuctionHouseBot.h.
Referenced by Rebuild(), and Update().
m_itemData
std::unordered_map<uint32, AuctionHouseBotItemData> AuctionHouseBot::m_itemData private
Definition at line 112 of file AuctionHouseBot.h.
Referenced by GetItemData(), Initialize(), SetItemData(), and Update().
m_itemValue
std::vector<std::vector<uint32> > AuctionHouseBot::m_itemValue = std::vector<std::vector<uint32>>(MAX_ITEM_QUALITY, std::vector<uint32>(MAX_ITEM_CLASS)) private
Definition at line 90 of file AuctionHouseBot.h.
Referenced by CalculateBuyoutPrice(), Initialize(), and Update().
m_professionItems
std::vector<uint32> AuctionHouseBot::m_professionItems private
Definition at line 108 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_professionItemsConfig
std::vector<int32> AuctionHouseBot::m_professionItemsConfig private
Definition at line 88 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_skinningLootConfig
std::vector<int32> AuctionHouseBot::m_skinningLootConfig private
Definition at line 87 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_skinningLootTemplates
std::vector<uint32> AuctionHouseBot::m_skinningLootTemplates private
Definition at line 107 of file AuctionHouseBot.h.
Referenced by Initialize(), and Update().
m_valueVariance
uint32 AuctionHouseBot::m_valueVariance private
Definition at line 92 of file AuctionHouseBot.h.
Referenced by Initialize(), and ValueWithVariance().
m_vendorItems
std::unordered_set<uint32> AuctionHouseBot::m_vendorItems private
Definition at line 110 of file AuctionHouseBot.h.
Referenced by CalculateBuyoutPrice(), and Initialize().
m_vendorValue
bool AuctionHouseBot::m_vendorValue private
Definition at line 91 of file AuctionHouseBot.h.
Referenced by CalculateBuyoutPrice(), and Initialize().
The documentation for this class was generated from the following files:
AuctionHouseBot.h
AuctionHouseBot.cpp