CMaNGOS_WoTLK: instance_zulgurub Class Reference
instance_zulgurub Class Reference
#include <zulgurub.h>
Public Member Functions
instance_zulgurub (Map *map)
~instance_zulgurub ()
void Initialize () override
void OnCreatureCreate (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
const char * Save () const override
void Load (const char *chrIn) override
void DoYellAtTriggerIfCan (uint32 triggerId)
Creature * SelectRandomPantherTrigger (bool bIsLeft)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void RemoveHakkarPowerStack ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidList m_lRightPantherTriggerGUIDList
GuidList m_lLeftPantherTriggerGUIDList
GuidList m_lSpiderEggGUIDList
GuidList m_lProwlerGUIDList
bool m_bHasIntroYelled
bool m_bHasAltarYelled
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 48 of file zulgurub.h.
Constructor & Destructor Documentation
instance_zulgurub()
instance_zulgurub::instance_zulgurub (Map * map)
Definition at line 27 of file zulgurub.cpp.
References Initialize().
~instance_zulgurub()
instance_zulgurub::~instance_zulgurub () inline
Definition at line 52 of file zulgurub.h.
Member Function Documentation
DoYellAtTriggerIfCan()
void instance_zulgurub::DoYellAtTriggerIfCan (uint32 triggerId)
Definition at line 39 of file zulgurub.cpp.
References AREATRIGGER_ALTAR, AREATRIGGER_ENTER, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), m_bHasAltarYelled, m_bHasIntroYelled, NPC_HAKKAR, SAY_HAKKAR_PROTECT, and SAY_MINION_DESTROY.
GetData()
uint32 instance_zulgurub::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 205 of file zulgurub.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Initialize()
void instance_zulgurub::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 34 of file zulgurub.cpp.
References m_auiEncounter.
Referenced by instance_zulgurub().
Load()
void instance_zulgurub::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 182 of file zulgurub.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_zulgurub::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 53 of file zulgurub.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionY(), m_lLeftPantherTriggerGUIDList, m_lRightPantherTriggerGUIDList, ScriptedInstance::m_npcEntryGuidStore, NPC_BLOODLORD_MANDOKIR, NPC_HAKKAR, NPC_JINDO, NPC_LORKHAN, NPC_MARLI, NPC_PANTHER_TRIGGER, NPC_THEKAL, and NPC_ZATH.
OnObjectCreate()
void instance_zulgurub::OnObjectCreate (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 75 of file zulgurub.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_FORCEFIELD, GO_GONG_OF_BETHEKK, GO_SPIDER_EGG, ScriptedInstance::m_goEntryGuidStore, and m_lSpiderEggGUIDList.
RemoveHakkarPowerStack()
void instance_zulgurub::RemoveHakkarPowerStack () protected
Definition at line 171 of file zulgurub.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), NPC_HAKKAR, SPELL_HAKKAR_POWER_DOWN, and TRIGGERED_NONE.
Referenced by SetData().
Save()
const char* instance_zulgurub::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 63 of file zulgurub.h.
References m_strInstData.
SelectRandomPantherTrigger()
Creature * instance_zulgurub::SelectRandomPantherTrigger (bool bIsLeft)
Definition at line 213 of file zulgurub.cpp.
References Map::GetCreature(), InstanceData::instance, m_lLeftPantherTriggerGUIDList, m_lRightPantherTriggerGUIDList, and urand().
Referenced by boss_arlokkAI::Aggro().
SetData()
void instance_zulgurub::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 90 of file zulgurub.cpp.
References aMandokirDownstairsPos, DAY, DONE, ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_FORCEFIELD, GO_GONG_OF_BETHEKK, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_lSpiderEggGUIDList, m_strInstData, NPC_BLOODLORD_MANDOKIR, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, RemoveHakkarPowerStack(), InstanceData::SaveToDB(), SPECIAL, TYPE_ARLOKK, TYPE_JEKLIK, TYPE_LORKHAN, TYPE_MARLI, TYPE_OHGAN, TYPE_THEKAL, TYPE_VENOXIS, and TYPE_ZATH.
Referenced by boss_arlokkAI::JustDied(), and boss_arlokkAI::JustReachedHome().
Field Documentation
m_auiEncounter
uint32 instance_zulgurub::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 73 of file zulgurub.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_bHasAltarYelled
bool instance_zulgurub::m_bHasAltarYelled protected
Definition at line 82 of file zulgurub.h.
Referenced by DoYellAtTriggerIfCan().
m_bHasIntroYelled
bool instance_zulgurub::m_bHasIntroYelled protected
Definition at line 81 of file zulgurub.h.
Referenced by DoYellAtTriggerIfCan().
m_lLeftPantherTriggerGUIDList
GuidList instance_zulgurub::m_lLeftPantherTriggerGUIDList protected
Definition at line 77 of file zulgurub.h.
Referenced by OnCreatureCreate(), and SelectRandomPantherTrigger().
m_lProwlerGUIDList
GuidList instance_zulgurub::m_lProwlerGUIDList protected
Definition at line 79 of file zulgurub.h.
m_lRightPantherTriggerGUIDList
GuidList instance_zulgurub::m_lRightPantherTriggerGUIDList protected
Definition at line 76 of file zulgurub.h.
Referenced by OnCreatureCreate(), and SelectRandomPantherTrigger().
m_lSpiderEggGUIDList
GuidList instance_zulgurub::m_lSpiderEggGUIDList protected
Definition at line 78 of file zulgurub.h.
Referenced by OnObjectCreate(), and SetData().
m_strInstData
std::string instance_zulgurub::m_strInstData protected
Definition at line 74 of file zulgurub.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
zulgurub.h
zulgurub.cpp