CMaNGOS_WoTLK: RASocket Class Reference
RASocket Class Reference
Mangos Daemon
Remote Administration socket.
#include <RASocket.h>
Public Member Functions
RASocket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
RASocket constructor.
virtual ~RASocket ()
RASocket destructor.
virtual bool Open () override
Accept an incoming connection.
Public Member Functions inherited from MaNGOS::Socket
Socket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
virtual ~Socket ()=default
void Close ()
bool IsClosed () const
virtual bool Deletable () const
bool Read (char *buffer, int length)
void ReadSkip (int length)
void Write (const char *buffer, int length)
void Write (const char *header, int headerSize, const char *content, int contentSize)
boost::asio::ip::tcp::socket & GetAsioSocket ()
const std::string & GetRemoteEndpoint () const
const std::string & GetRemoteAddress () const
template<typename T >
std::shared_ptr< T > shared ()
boost::asio::ip::address GetRemoteIpAddress () const
uint16 GetRemotePort () const
Private Types
enum AuthLevel { None , HaveUsername , Authenticated }
Private Member Functions
virtual bool ProcessIncomingData () override
Read data from the network.
bool HandleInput ()
void Send (const std::string &message)
Private Attributes
const bool m_secure
bool m_restricted
std::string m_input
AuthLevel m_authLevel
AccountTypes m_accountLevel
uint32 m_accountId
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Socket
const uint8 * InPeak () const
int ReadLengthRemaining () const
void ForceFlushOut ()
Protected Attributes inherited from MaNGOS::Socket
const std::string m_address
const std::string m_remoteEndpoint
boost::asio::ip::address m_remoteAddress
uint16 m_remotePort
Detailed Description
Remote Administration socket.
Definition at line 35 of file RASocket.h.
Member Enumeration Documentation
AuthLevel
enum RASocket::AuthLevel private
Enumerator
None
HaveUsername
Authenticated
Definition at line 38 of file RASocket.h.
Constructor & Destructor Documentation
RASocket()
RASocket::RASocket (boost::asio::io_service & service, std::function< void(Socket *)> closeHandler)
RASocket constructor.
Definition at line 40 of file RASocket.cpp.
References m_restricted, sConfig, and sLog.
~RASocket()
RASocket::~RASocket () virtual
RASocket destructor.
Definition at line 54 of file RASocket.cpp.
References sLog.
Member Function Documentation
HandleInput()
bool RASocket::HandleInput () private
If the input is '<username>'
If the user is not found, deny access
if gmlevel is too low, deny access
allow by remotely connected admin use console level commands dependent from config setting
Else deny access
Definition at line 106 of file RASocket.cpp.
References LANG_RA_PASS, LANG_RA_USER, m_accountId, m_accountLevel, m_authLevel, m_input, m_restricted, m_secure, None, sAccountMgr, sConfig, SEC_ADMINISTRATOR, SEC_CONSOLE, Send(), sLog, sObjectMgr, and sWorld.
Referenced by ProcessIncomingData().
Open()
bool RASocket::Open () override virtual
Accept an incoming connection.
print Motd
Reimplemented from MaNGOS::Socket.
Definition at line 60 of file RASocket.cpp.
References LANG_RA_USER, MaNGOS::Socket::m_address, Send(), sLog, sObjectMgr, and sWorld.
ProcessIncomingData()
bool RASocket::ProcessIncomingData () override private virtual
Read data from the network.
Implements MaNGOS::Socket.
Definition at line 76 of file RASocket.cpp.
References DEBUG_LOG, HandleInput(), m_input, MaNGOS::Socket::Read(), and MaNGOS::Socket::ReadLengthRemaining().
Send()
void RASocket::Send (const std::string & message) private
Definition at line 211 of file RASocket.cpp.
References MaNGOS::Socket::Write().
Referenced by HandleInput(), and Open().
Field Documentation
m_accountId
uint32 RASocket::m_accountId private
Definition at line 52 of file RASocket.h.
Referenced by HandleInput().
m_accountLevel
AccountTypes RASocket::m_accountLevel private
Definition at line 51 of file RASocket.h.
Referenced by HandleInput().
m_authLevel
AuthLevel RASocket::m_authLevel private
Definition at line 50 of file RASocket.h.
Referenced by HandleInput().
m_input
std::string RASocket::m_input private
Definition at line 48 of file RASocket.h.
Referenced by HandleInput(), and ProcessIncomingData().
m_restricted
bool RASocket::m_restricted private
Definition at line 46 of file RASocket.h.
Referenced by HandleInput(), and RASocket().
m_secure
const bool RASocket::m_secure private
Definition at line 45 of file RASocket.h.
Referenced by HandleInput().
The documentation for this class was generated from the following files:
RASocket.h
RASocket.cpp