CMaNGOS_WoTLK: Movement::MoveSplineFlag Class Reference
Movement::MoveSplineFlag Class Reference
#include <MoveSplineFlag.h>
Public Types
enum eFlags {
None = 0x00000000 , Done = 0x00000100 , Falling = 0x00000200 , No_Spline = 0x00000400 ,
Parabolic = 0x00000800 , Walkmode = 0x00001000 , Flying = 0x00002000 , OrientationFixed = 0x00004000 ,
Final_Point = 0x00008000 , Final_Target = 0x00010000 , Final_Angle = 0x00020000 , Catmullrom = 0x00040000 ,
Cyclic = 0x00080000 , Enter_Cycle = 0x00100000 , Animation = 0x00200000 , Frozen = 0x00400000 ,
BoardVehicle = 0x00800000 , ExitVehicle = 0x01000000 , Unknown7 = 0x02000000 , Unknown8 = 0x04000000 ,
OrientationInversed = 0x08000000 , Unknown10 = 0x10000000 , Unknown11 = 0x20000000 , Unknown12 = 0x40000000 ,
Unknown13 = 0x80000000 , Mask_Final_Facing = Final_Point | Final_Target | Final_Angle , Mask_Animations = 0xFF , Mask_No_Monster_Move = Mask_Final_Facing | Mask_Animations | Done ,
Mask_CatmullRom = Flying | Catmullrom , Mask_Unused = No_Spline | Enter_Cycle | Frozen | Unknown7 | Unknown8 | Unknown10 | Unknown11 | Unknown12 | Unknown13
}
Public Member Functions
uint32 & raw ()
const uint32 & raw () const
MoveSplineFlag ()
MoveSplineFlag (uint32 f)
MoveSplineFlag (const MoveSplineFlag &f)
bool isSmooth () const
bool isLinear () const
bool isFacing () const
uint8 getAnimationId () const
bool hasAllFlags (uint32 f) const
bool hasFlag (uint32 f) const
uint32 operator& (uint32 f) const
uint32 operator| (uint32 f) const
std::string ToString () const
void operator&= (uint32 f)
void operator|= (uint32 f)
void EnableAnimation (uint8 anim)
void EnableParabolic ()
void EnableFalling ()
void EnableFlying ()
void EnableCatmullRom ()
void EnableFacingPoint ()
void EnableFacingAngle ()
void EnableFacingTarget ()
void EnableBoardVehicle ()
void EnableExitVehicle ()
Data Fields
uint8 animId: 8
bool done: 1
bool falling: 1
bool no_spline: 1
bool parabolic: 1
bool walkmode: 1
bool flying: 1
bool orientationFixed: 1
bool final_point: 1
bool final_target: 1
bool final_angle: 1
bool catmullrom: 1
bool cyclic: 1
bool enter_cycle: 1
bool animation: 1
bool frozen: 1
bool boardVehicle: 1
bool exitVehicle: 1
bool unknown7: 1
bool unknown8: 1
bool orientationInversed: 1
bool unknown10: 1
bool unknown11: 1
bool unknown12: 1
bool unknown13: 1
Detailed Description
Definition at line 31 of file MoveSplineFlag.h.
Member Enumeration Documentation
eFlags
enum Movement::MoveSplineFlag::eFlags
Enumerator
None
Done
Falling
No_Spline
Parabolic
Walkmode
Flying
OrientationFixed
Final_Point
Final_Target
Final_Angle
Catmullrom
Cyclic
Enter_Cycle
Animation
Frozen
BoardVehicle
ExitVehicle
Unknown7
Unknown8
OrientationInversed
Unknown10
Unknown11
Unknown12
Unknown13
Mask_Final_Facing
Mask_Animations
Mask_No_Monster_Move
Mask_CatmullRom
Mask_Unused
Definition at line 34 of file MoveSplineFlag.h.
Constructor & Destructor Documentation
MoveSplineFlag() [1/3]
Movement::MoveSplineFlag::MoveSplineFlag () inline
Definition at line 78 of file MoveSplineFlag.h.
References raw().
MoveSplineFlag() [2/3]
Movement::MoveSplineFlag::MoveSplineFlag (uint32 f) inline
Definition at line 79 of file MoveSplineFlag.h.
References raw().
MoveSplineFlag() [3/3]
Movement::MoveSplineFlag::MoveSplineFlag (const MoveSplineFlag & f) inline
Definition at line 80 of file MoveSplineFlag.h.
References raw().
Member Function Documentation
EnableAnimation()
void Movement::MoveSplineFlag::EnableAnimation (uint8 anim) inline
Definition at line 100 of file MoveSplineFlag.h.
References Animation, Falling, Mask_Animations, Parabolic, and raw().
Referenced by Movement::MoveSplineInit::SetAnimation().
EnableBoardVehicle()
void Movement::MoveSplineFlag::EnableBoardVehicle () inline
Definition at line 108 of file MoveSplineFlag.h.
References BoardVehicle, Catmullrom, ExitVehicle, and raw().
Referenced by Movement::MoveSplineInit::SetBoardVehicle().
EnableCatmullRom()
void Movement::MoveSplineFlag::EnableCatmullRom () inline
Definition at line 104 of file MoveSplineFlag.h.
References Catmullrom, Flying, and raw().
Referenced by Movement::MoveSplineInit::SetSmooth().
EnableExitVehicle()
void Movement::MoveSplineFlag::EnableExitVehicle () inline
Definition at line 109 of file MoveSplineFlag.h.
References BoardVehicle, ExitVehicle, and raw().
Referenced by Movement::MoveSplineInit::SetExitVehicle().
EnableFacingAngle()
void Movement::MoveSplineFlag::EnableFacingAngle () inline
Definition at line 106 of file MoveSplineFlag.h.
References Final_Angle, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
EnableFacingPoint()
void Movement::MoveSplineFlag::EnableFacingPoint () inline
Definition at line 105 of file MoveSplineFlag.h.
References Final_Point, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
EnableFacingTarget()
void Movement::MoveSplineFlag::EnableFacingTarget () inline
Definition at line 107 of file MoveSplineFlag.h.
References Final_Target, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
EnableFalling()
void Movement::MoveSplineFlag::EnableFalling () inline
Definition at line 102 of file MoveSplineFlag.h.
References Animation, Falling, Mask_Animations, Parabolic, and raw().
Referenced by Movement::MoveSplineInit::SetFall().
EnableFlying()
void Movement::MoveSplineFlag::EnableFlying () inline
Definition at line 103 of file MoveSplineFlag.h.
References Catmullrom, Flying, and raw().
Referenced by Movement::MoveSplineInit::SetFly().
EnableParabolic()
void Movement::MoveSplineFlag::EnableParabolic () inline
Definition at line 101 of file MoveSplineFlag.h.
References Animation, Falling, Mask_Animations, Parabolic, and raw().
Referenced by Movement::MoveSplineInit::SetParabolic().
getAnimationId()
uint8 Movement::MoveSplineFlag::getAnimationId () const inline
Definition at line 88 of file MoveSplineFlag.h.
References animId.
Referenced by Movement::PacketBuilder::WriteCommonMonsterMovePart().
hasAllFlags()
bool Movement::MoveSplineFlag::hasAllFlags (uint32 f) const inline
Definition at line 89 of file MoveSplineFlag.h.
References raw().
hasFlag()
bool Movement::MoveSplineFlag::hasFlag (uint32 f) const inline
Definition at line 90 of file MoveSplineFlag.h.
References raw().
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::MoveSplineInit::Launch().
isFacing()
bool Movement::MoveSplineFlag::isFacing () const inline
Definition at line 86 of file MoveSplineFlag.h.
References Mask_Final_Facing, and raw().
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::MoveSpline::isFacing().
isLinear()
bool Movement::MoveSplineFlag::isLinear () const inline
Definition at line 85 of file MoveSplineFlag.h.
References isSmooth().
isSmooth()
bool Movement::MoveSplineFlag::isSmooth () const inline
Definition at line 84 of file MoveSplineFlag.h.
References Mask_CatmullRom, and raw().
Referenced by Movement::MoveSpline::init_spline(), and isLinear().
operator&()
uint32 Movement::MoveSplineFlag::operator& (uint32 f) const inline
Definition at line 91 of file MoveSplineFlag.h.
References raw().
operator&=()
void Movement::MoveSplineFlag::operator&= (uint32 f) inline
Definition at line 97 of file MoveSplineFlag.h.
References raw().
operator|()
uint32 Movement::MoveSplineFlag::operator| (uint32 f) const inline
Definition at line 92 of file MoveSplineFlag.h.
References raw().
operator|=()
void Movement::MoveSplineFlag::operator|= (uint32 f) inline
Definition at line 98 of file MoveSplineFlag.h.
References raw().
raw() [1/2]
uint32& Movement::MoveSplineFlag::raw () inline
Definition at line 75 of file MoveSplineFlag.h.
Referenced by EnableAnimation(), EnableBoardVehicle(), EnableCatmullRom(), EnableExitVehicle(), EnableFacingAngle(), EnableFacingPoint(), EnableFacingTarget(), EnableFalling(), EnableFlying(), EnableParabolic(), hasAllFlags(), hasFlag(), isFacing(), isSmooth(), MoveSplineFlag(), operator&(), operator&=(), operator|(), operator|=(), ToString(), and Movement::PacketBuilder::WriteCreate().
raw() [2/2]
const uint32& Movement::MoveSplineFlag::raw () const inline
Definition at line 76 of file MoveSplineFlag.h.
ToString()
std::string Movement::MoveSplineFlag::ToString () const
Definition at line 201 of file util.cpp.
References Movement::g_SplineFlag_names, Movement::print_flags(), and raw().
Referenced by Movement::MoveSpline::ToString().
Field Documentation
animation
bool Movement::MoveSplineFlag::animation
Definition at line 125 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::PacketBuilder::WriteCommonMonsterMovePart().
animId
uint8 Movement::MoveSplineFlag::animId
Definition at line 111 of file MoveSplineFlag.h.
Referenced by getAnimationId().
boardVehicle
bool Movement::MoveSplineFlag::boardVehicle
Definition at line 127 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::IsBoarding().
catmullrom
bool Movement::MoveSplineFlag::catmullrom
Definition at line 122 of file MoveSplineFlag.h.
cyclic
bool Movement::MoveSplineFlag::cyclic
Definition at line 123 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::init_spline(), Movement::MoveSpline::isCyclic(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::SetCyclic(), and Movement::PacketBuilder::WriteMonsterMove().
done
bool Movement::MoveSplineFlag::done
Definition at line 112 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::_Finalize(), Movement::MoveSpline::_Interrupt(), Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::Finalized(), Movement::MoveSpline::Initialize(), and Movement::MoveSpline::MoveSpline().
enter_cycle
bool Movement::MoveSplineFlag::enter_cycle
Definition at line 124 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::_updateState(), Movement::MoveSpline::init_spline(), and Movement::MoveSplineInit::Launch().
exitVehicle
bool Movement::MoveSplineFlag::exitVehicle
Definition at line 128 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::IsBoarding().
falling
bool Movement::MoveSplineFlag::falling
Definition at line 113 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::MoveSpline::init_spline().
final_angle
bool Movement::MoveSplineFlag::final_angle
Definition at line 121 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::isFacingAngle(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
final_point
bool Movement::MoveSplineFlag::final_point
Definition at line 119 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::isFacingPoint(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
final_target
bool Movement::MoveSplineFlag::final_target
Definition at line 120 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::isFacingTarget(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
flying
bool Movement::MoveSplineFlag::flying
Definition at line 117 of file MoveSplineFlag.h.
Referenced by Movement::MoveSplineInit::MoveSplineInit().
frozen
bool Movement::MoveSplineFlag::frozen
Definition at line 126 of file MoveSplineFlag.h.
no_spline
bool Movement::MoveSplineFlag::no_spline
Definition at line 114 of file MoveSplineFlag.h.
orientationFixed
bool Movement::MoveSplineFlag::orientationFixed
Definition at line 118 of file MoveSplineFlag.h.
Referenced by Movement::MoveSplineInit::SetOrientationFixed().
orientationInversed
bool Movement::MoveSplineFlag::orientationInversed
Definition at line 131 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::MoveSplineInit::SetOrientationInversed().
parabolic
bool Movement::MoveSplineFlag::parabolic
Definition at line 115 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::Initialize(), and Movement::PacketBuilder::WriteCommonMonsterMovePart().
unknown10
bool Movement::MoveSplineFlag::unknown10
Definition at line 132 of file MoveSplineFlag.h.
unknown11
bool Movement::MoveSplineFlag::unknown11
Definition at line 133 of file MoveSplineFlag.h.
unknown12
bool Movement::MoveSplineFlag::unknown12
Definition at line 134 of file MoveSplineFlag.h.
unknown13
bool Movement::MoveSplineFlag::unknown13
Definition at line 135 of file MoveSplineFlag.h.
unknown7
bool Movement::MoveSplineFlag::unknown7
Definition at line 129 of file MoveSplineFlag.h.
unknown8
bool Movement::MoveSplineFlag::unknown8
Definition at line 130 of file MoveSplineFlag.h.
walkmode
bool Movement::MoveSplineFlag::walkmode
Definition at line 116 of file MoveSplineFlag.h.
Referenced by Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MoveSplineInit(), and Movement::MoveSplineInit::SetWalk().
The documentation for this class was generated from the following files:
MoveSplineFlag.h
util.cpp