CMaNGOS_WoTLK: LootStore Class Reference
LootStore Class Reference
#include <LootMgr.h>
Public Member Functions
LootStore (char const *name, char const *entryName, bool ratesAllowed)
virtual ~LootStore ()
void Verify () const
void LoadAndCollectLootIds (LootIdSet &ids_set)
void LoadAndCheckReferenceNames ()
void CheckLootRefs (LootIdSet *ref_set=nullptr) const
void ReportUnusedIds (LootIdSet const &ids_set) const
void ReportNotExistedId (uint32 id) const
bool HaveLootFor (uint32 loot_id) const
bool HaveQuestLootFor (uint32 loot_id) const
bool HaveQuestLootForPlayer (uint32 loot_id, Player *player) const
LootTemplate const * GetLootFor (uint32 loot_id) const
char const * GetName () const
char const * GetEntryName () const
bool IsRatesAllowed () const
Protected Member Functions
void LoadLootTable ()
void Clear ()
Private Attributes
LootTemplateMap m_LootTemplates
char const * m_name
char const * m_entryName
bool m_ratesAllowed
Detailed Description
Definition at line 223 of file LootMgr.h.
Constructor & Destructor Documentation
LootStore()
LootStore::LootStore (char const * name, char const * entryName, bool ratesAllowed) inline explicit
Definition at line 226 of file LootMgr.h.
~LootStore()
virtual LootStore::~LootStore () inline virtual
Definition at line 228 of file LootMgr.h.
References Clear().
Member Function Documentation
CheckLootRefs()
void LootStore::CheckLootRefs (LootIdSet * ref_set = nullptr) const
Definition at line 261 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesCreatureCommand(), ChatHandler::HandleReloadLootTemplatesDisenchantCommand(), ChatHandler::HandleReloadLootTemplatesFishingCommand(), ChatHandler::HandleReloadLootTemplatesGameobjectCommand(), ChatHandler::HandleReloadLootTemplatesItemCommand(), ChatHandler::HandleReloadLootTemplatesMailCommand(), ChatHandler::HandleReloadLootTemplatesMillingCommand(), ChatHandler::HandleReloadLootTemplatesPickpocketingCommand(), ChatHandler::HandleReloadLootTemplatesProspectingCommand(), ChatHandler::HandleReloadLootTemplatesSkinningCommand(), and ChatHandler::HandleReloadLootTemplatesSpellCommand().
Clear()
void LootStore::Clear () protected
Definition at line 82 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by LoadLootTable(), and ~LootStore().
GetEntryName()
char const* LootStore::GetEntryName () const inline
Definition at line 245 of file LootMgr.h.
References m_entryName.
Referenced by ReportNotExistedId(), and ReportUnusedIds().
GetLootFor()
LootTemplate const * LootStore::GetLootFor (uint32 loot_id) const
Definition at line 209 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by AuctionHouseBot::AddLootToItemMap(), LootMgr::CheckDropStats(), LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), Loot::FillLoot(), and LootTemplate::Process().
GetName()
char const* LootStore::GetName () const inline
Definition at line 244 of file LootMgr.h.
References m_name.
Referenced by LootMgr::CheckDropStats(), Loot::FillLoot(), LootStoreItem::IsValid(), LoadLootTable(), ReportNotExistedId(), ReportUnusedIds(), and LootTemplate::LootGroup::Verify().
HaveLootFor()
bool LootStore::HaveLootFor (uint32 loot_id) const inline
Definition at line 238 of file LootMgr.h.
References m_LootTemplates.
Referenced by Spell::CheckItems(), and LootMgr::ExistsRefLootTemplate().
HaveQuestLootFor()
bool LootStore::HaveQuestLootFor (uint32 loot_id) const
Definition at line 189 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by ObjectMgr::LoadGameObjectForQuests().
HaveQuestLootForPlayer()
bool LootStore::HaveQuestLootForPlayer (uint32 loot_id, Player * player) const
Definition at line 199 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by GameObject::ActivateToQuest().
IsRatesAllowed()
bool LootStore::IsRatesAllowed () const inline
Definition at line 246 of file LootMgr.h.
References m_ratesAllowed.
Referenced by AuctionHouseBot::AddLootToItemMap(), LootMgr::CheckDropStats(), and Loot::FillLoot().
LoadAndCheckReferenceNames()
void LootStore::LoadAndCheckReferenceNames ()
Definition at line 227 of file LootMgr.cpp.
References Field::GetCppString(), Field::GetUInt32(), m_LootTemplates, Database::Query(), sLog, and WorldDatabase.
Referenced by LoadLootTemplates_Reference().
LoadAndCollectLootIds()
void LootStore::LoadAndCollectLootIds (LootIdSet & ids_set)
Definition at line 219 of file LootMgr.cpp.
References LoadLootTable(), and m_LootTemplates.
Referenced by LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Reference(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
LoadLootTable()
void LootStore::LoadLootTable () protected
Definition at line 99 of file LootMgr.cpp.
References ConditionEntry::CanBeUsedWithoutPlayer(), Clear(), QueryResult::Fetch(), Field::GetFloat(), Field::GetInt32(), GetName(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), LootStoreItem::IsValid(), SQLStorage::LookupEntry(), m_LootTemplates, QueryResult::NextRow(), Database::PQuery(), sConditionStorage, SIZEFMTD, sLog, BarGoLink::step(), Verify(), and WorldDatabase.
Referenced by LoadAndCollectLootIds().
ReportNotExistedId()
void LootStore::ReportNotExistedId (uint32 id) const
Definition at line 278 of file LootMgr.cpp.
References GetEntryName(), GetName(), and sLog.
Referenced by LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
ReportUnusedIds()
void LootStore::ReportUnusedIds (LootIdSet const & ids_set) const
Definition at line 267 of file LootMgr.cpp.
References GetEntryName(), GetName(), and sLog.
Referenced by CheckLootTemplates_Reference(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Fishing(), LoadLootTemplates_Gameobject(), LoadLootTemplates_Item(), LoadLootTemplates_Mail(), LoadLootTemplates_Milling(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Skinning(), and LoadLootTemplates_Spell().
Verify()
void LootStore::Verify () const
Definition at line 91 of file LootMgr.cpp.
References m_LootTemplates.
Referenced by LoadLootTable().
Field Documentation
m_entryName
char const* LootStore::m_entryName private
Definition at line 253 of file LootMgr.h.
Referenced by GetEntryName().
m_LootTemplates
LootTemplateMap LootStore::m_LootTemplates private
Definition at line 251 of file LootMgr.h.
Referenced by CheckLootRefs(), Clear(), GetLootFor(), HaveLootFor(), HaveQuestLootFor(), HaveQuestLootForPlayer(), LoadAndCheckReferenceNames(), LoadAndCollectLootIds(), LoadLootTable(), and Verify().
m_name
char const* LootStore::m_name private
Definition at line 252 of file LootMgr.h.
Referenced by GetName().
m_ratesAllowed
bool LootStore::m_ratesAllowed private
Definition at line 254 of file LootMgr.h.
Referenced by IsRatesAllowed().
The documentation for this class was generated from the following files:
LootMgr.h
LootMgr.cpp