CMaNGOS_WoTLK: PlayerbotRogueAI Class Reference
PlayerbotRogueAI Class Reference
#include <PlayerbotRogueAI.h>
Public Member Functions
PlayerbotRogueAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotRogueAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
void DoNonCombatActions () override
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
virtual CombatManeuverReturns DispelPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Private Attributes
uint32 SINISTER_STRIKE
uint32 BACKSTAB
uint32 GOUGE
uint32 EVASION
uint32 SPRINT
uint32 KICK
uint32 FEINT
uint32 SHIV
uint32 FAN_OF_KNIVES
uint32 SHADOWSTEP
uint32 STEALTH
uint32 VANISH
uint32 HEMORRHAGE
uint32 BLIND
uint32 SHADOW_DANCE
uint32 PICK_POCKET
uint32 CLOAK_OF_SHADOWS
uint32 TRICK_TRADE
uint32 CRIPPLING_POISON
uint32 DEADLY_POISON
uint32 MIND_NUMBING_POISON
uint32 GHOSTLY_STRIKE
uint32 DISTRACT
uint32 PREPARATION
uint32 PREMEDITATION
uint32 EVISCERATE
uint32 SLICE_DICE
uint32 GARROTE
uint32 EXPOSE_ARMOR
uint32 AMBUSH
uint32 RUPTURE
uint32 DISMANTLE
uint32 CHEAP_SHOT
uint32 KIDNEY_SHOT
uint32 MUTILATE
uint32 ENVENOM
uint32 DEADLY_THROW
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 SpellSequence
uint32 LastSpellCombat
uint32 LastSpellSubtlety
uint32 LastSpellAssassination
uint32 Aura
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 87 of file PlayerbotRogueAI.h.
Constructor & Destructor Documentation
PlayerbotRogueAI()
PlayerbotRogueAI::PlayerbotRogueAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotRogueAI.cpp.
References AMBUSH, AMBUSH_1, ARCANE_TORRENT, ARCANE_TORRENT_ROGUE, BACKSTAB, BACKSTAB_1, BERSERKING, BERSERKING_ALL, BLIND, BLIND_1, BLOOD_FURY, BLOOD_FURY_MELEE_CLASSES, CHEAP_SHOT, CHEAP_SHOT_1, CLOAK_OF_SHADOWS, CLOAK_OF_SHADOWS_1, DISMANTLE, DISMANTLE_1, DISTRACT, DISTRACT_1, ESCAPE_ARTIST, ESCAPE_ARTIST_ALL, EVASION, EVASION_1, EVERY_MAN_FOR_HIMSELF, EVERY_MAN_FOR_HIMSELF_ALL, EVISCERATE, EVISCERATE_1, EXPOSE_ARMOR, EXPOSE_ARMOR_1, FAN_OF_KNIVES, FAN_OF_KNIVES_1, FEINT, FEINT_1, GARROTE, GARROTE_1, GHOSTLY_STRIKE, GHOSTLY_STRIKE_1, GOUGE, GOUGE_1, HEMORRHAGE, HEMORRHAGE_1, PlayerbotAI::initSpell(), KICK, KICK_1, KIDNEY_SHOT, KIDNEY_SHOT_1, PlayerbotClassAI::m_ai, MUTILATE, MUTILATE_1, PICK_POCKET, PICK_POCKET_1, PREMEDITATION, PREMEDITATION_1, PREPARATION, PREPARATION_1, PlayerbotClassAI::RECENTLY_BANDAGED, RUPTURE, RUPTURE_1, SHADOW_DANCE, SHADOW_DANCE_1, SHADOWMELD, SHADOWMELD_ALL, SHADOWSTEP, SHADOWSTEP_1, SINISTER_STRIKE, SINISTER_STRIKE_1, SLICE_AND_DICE_1, SLICE_DICE, SPRINT, SPRINT_1, STEALTH, STEALTH_1, STONEFORM, STONEFORM_ALL, VANISH, VANISH_1, WILL_OF_THE_FORSAKEN, and WILL_OF_THE_FORSAKEN_ALL.
~PlayerbotRogueAI()
PlayerbotRogueAI::~PlayerbotRogueAI () virtual
Definition at line 70 of file PlayerbotRogueAI.cpp.
Member Function Documentation
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotRogueAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 72 of file PlayerbotRogueAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotRogueAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 114 of file PlayerbotRogueAI.cpp.
References Unit::addUnitState(), PlayerbotAI::CastSpell(), EFFECT_INDEX_0, Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::HasAura(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_OK, SPELL_CAST_OK, STEALTH, and UNIT_STAT_CHASE.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotRogueAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 132 of file PlayerbotRogueAI.cpp.
References Unit::addUnitState(), PlayerbotAI::CastSpell(), EFFECT_INDEX_0, Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::HasAura(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), RETURN_FINISHED_FIRST_MOVES, RETURN_NO_ACTION_OK, SPELL_CAST_OK, STEALTH, and UNIT_STAT_CHASE.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotRogueAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 169 of file PlayerbotRogueAI.cpp.
References AMBUSH, ARCANE_TORRENT, AURA_STATE_DEADLY_POISON, BACKSTAB, BERSERKING, BLIND, BLOOD_FURY, Unit::CanReachWithMeleeAttack(), PlayerbotAI::CastSpell(), CHEAP_SHOT, CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, CLOAK_OF_SHADOWS, CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD, DISMANTLE, EFFECT_INDEX_0, ESCAPE_ARTIST, EVASION, EVERY_MAN_FOR_HIMSELF, EVISCERATE, EXPOSE_ARMOR, FEINT, GARROTE, Unit::getClass(), Unit::GetComboPoints(), Creature::GetCreatureInfo(), Unit::GetCreatureTypeMask(), PlayerbotAI::GetEnergyAmount(), PlayerbotAI::GetGroupTank(), PlayerbotAI::GetHealthPercent(), Unit::getRace(), Unit::GetVictim(), GHOSTLY_STRIKE, GOUGE, Unit::HasAura(), Unit::HasAuraState(), Unit::HasAuraType(), Object::HasFlag(), Unit::hasUnitState(), HEMORRHAGE, PlayerbotAI::IsElite(), WorldObject::isInBackInMap(), Unit::IsNonMeleeSpellCasted(), KICK, KIDNEY_SHOT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MUTILATE, PICK_POCKET, PlayerbotAI::PickPocket(), PREMEDITATION, PREPARATION, RACE_BLOODELF, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TROLL, RACE_UNDEAD, Unit::RemoveSpellsCausingAura(), RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, RogueCombat, RogueSpellPreventing, RogueStealth, RogueThreat, RUPTURE, SHADOW_DANCE, SHADOWMELD, SHADOWSTEP, SINISTER_STRIKE, SLICE_DICE, SPELL_AURA_MOD_CHARM, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_STEALTH, SPELL_AURA_PERIODIC_DAMAGE, SPELL_CAST_OK, SpellSequence, STEALTH, STONEFORM, PlayerbotAI::TellMaster(), UNIT_FIELD_FLAGS, UNIT_FLAG_DISARMED, UNIT_STAT_ROOT, UNIT_STAT_STUNNED, CreatureInfo::UnitClass, VANISH, and WILL_OF_THE_FORSAKEN.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotRogueAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 149 of file PlayerbotRogueAI.cpp.
References DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, RETURN_NO_ACTION_ERROR, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
Referenced by DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotRogueAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 363 of file PlayerbotRogueAI.cpp.
References DoNextCombatManeuverPVE().
Referenced by DoNextCombatManeuverPVE().
DoNonCombatActions()
void PlayerbotRogueAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 371 of file PlayerbotRogueAI.cpp.
References DEADLY_POISON_DISPLAYID, PlayerbotClassAI::EatDrinkBandage(), EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, PlayerbotAI::FindConsumable(), Item::GetEnchantmentId(), Player::GetItemByPos(), Unit::HasAura(), INSTANT_POISON_DISPLAYID, INVENTORY_SLOT_BAG_0, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, Unit::RemoveSpellsCausingAura(), PlayerbotAI::SetIgnoreUpdateTime(), SPELL_AURA_MOD_STEALTH, STEALTH, TEMP_ENCHANTMENT_SLOT, PlayerbotAI::UseItem(), and WOUND_POISON_DISPLAYID.
Field Documentation
AMBUSH
uint32 PlayerbotRogueAI::AMBUSH private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
ARCANE_TORRENT
uint32 PlayerbotRogueAI::ARCANE_TORRENT private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
Aura
uint32 PlayerbotRogueAI::Aura private
Definition at line 118 of file PlayerbotRogueAI.h.
BACKSTAB
uint32 PlayerbotRogueAI::BACKSTAB private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
BERSERKING
uint32 PlayerbotRogueAI::BERSERKING private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
BLIND
uint32 PlayerbotRogueAI::BLIND private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
BLOOD_FURY
uint32 PlayerbotRogueAI::BLOOD_FURY private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
CHEAP_SHOT
uint32 PlayerbotRogueAI::CHEAP_SHOT private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
CLOAK_OF_SHADOWS
uint32 PlayerbotRogueAI::CLOAK_OF_SHADOWS private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
CRIPPLING_POISON
uint32 PlayerbotRogueAI::CRIPPLING_POISON private
Definition at line 110 of file PlayerbotRogueAI.h.
DEADLY_POISON
uint32 PlayerbotRogueAI::DEADLY_POISON private
Definition at line 110 of file PlayerbotRogueAI.h.
DEADLY_THROW
uint32 PlayerbotRogueAI::DEADLY_THROW private
Definition at line 113 of file PlayerbotRogueAI.h.
DISMANTLE
uint32 PlayerbotRogueAI::DISMANTLE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
DISTRACT
uint32 PlayerbotRogueAI::DISTRACT private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by PlayerbotRogueAI().
ENVENOM
uint32 PlayerbotRogueAI::ENVENOM private
Definition at line 113 of file PlayerbotRogueAI.h.
ESCAPE_ARTIST
uint32 PlayerbotRogueAI::ESCAPE_ARTIST private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
EVASION
uint32 PlayerbotRogueAI::EVASION private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotRogueAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
EVISCERATE
uint32 PlayerbotRogueAI::EVISCERATE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
EXPOSE_ARMOR
uint32 PlayerbotRogueAI::EXPOSE_ARMOR private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
FAN_OF_KNIVES
uint32 PlayerbotRogueAI::FAN_OF_KNIVES private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by PlayerbotRogueAI().
FEINT
uint32 PlayerbotRogueAI::FEINT private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
GARROTE
uint32 PlayerbotRogueAI::GARROTE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
GHOSTLY_STRIKE
uint32 PlayerbotRogueAI::GHOSTLY_STRIKE private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotRogueAI::GIFT_OF_THE_NAARU private
Definition at line 116 of file PlayerbotRogueAI.h.
GOUGE
uint32 PlayerbotRogueAI::GOUGE private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
HEMORRHAGE
uint32 PlayerbotRogueAI::HEMORRHAGE private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
KICK
uint32 PlayerbotRogueAI::KICK private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
KIDNEY_SHOT
uint32 PlayerbotRogueAI::KIDNEY_SHOT private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
LastSpellAssassination
uint32 PlayerbotRogueAI::LastSpellAssassination private
Definition at line 118 of file PlayerbotRogueAI.h.
LastSpellCombat
uint32 PlayerbotRogueAI::LastSpellCombat private
Definition at line 118 of file PlayerbotRogueAI.h.
LastSpellSubtlety
uint32 PlayerbotRogueAI::LastSpellSubtlety private
Definition at line 118 of file PlayerbotRogueAI.h.
MIND_NUMBING_POISON
uint32 PlayerbotRogueAI::MIND_NUMBING_POISON private
Definition at line 110 of file PlayerbotRogueAI.h.
MUTILATE
uint32 PlayerbotRogueAI::MUTILATE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
PICK_POCKET
uint32 PlayerbotRogueAI::PICK_POCKET private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
PREMEDITATION
uint32 PlayerbotRogueAI::PREMEDITATION private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
PREPARATION
uint32 PlayerbotRogueAI::PREPARATION private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
RUPTURE
uint32 PlayerbotRogueAI::RUPTURE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SHADOW_DANCE
uint32 PlayerbotRogueAI::SHADOW_DANCE private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SHADOWMELD
uint32 PlayerbotRogueAI::SHADOWMELD private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SHADOWSTEP
uint32 PlayerbotRogueAI::SHADOWSTEP private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SHIV
uint32 PlayerbotRogueAI::SHIV private
Definition at line 107 of file PlayerbotRogueAI.h.
SINISTER_STRIKE
uint32 PlayerbotRogueAI::SINISTER_STRIKE private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SLICE_DICE
uint32 PlayerbotRogueAI::SLICE_DICE private
Definition at line 113 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
SpellSequence
uint32 PlayerbotRogueAI::SpellSequence private
Definition at line 118 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver().
SPRINT
uint32 PlayerbotRogueAI::SPRINT private
Definition at line 107 of file PlayerbotRogueAI.h.
Referenced by PlayerbotRogueAI().
STEALTH
uint32 PlayerbotRogueAI::STEALTH private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), DoNextCombatManeuver(), DoNonCombatActions(), and PlayerbotRogueAI().
STONEFORM
uint32 PlayerbotRogueAI::STONEFORM private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
TRICK_TRADE
uint32 PlayerbotRogueAI::TRICK_TRADE private
Definition at line 110 of file PlayerbotRogueAI.h.
VANISH
uint32 PlayerbotRogueAI::VANISH private
Definition at line 110 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
WAR_STOMP
uint32 PlayerbotRogueAI::WAR_STOMP private
Definition at line 116 of file PlayerbotRogueAI.h.
WILL_OF_THE_FORSAKEN
uint32 PlayerbotRogueAI::WILL_OF_THE_FORSAKEN private
Definition at line 116 of file PlayerbotRogueAI.h.
Referenced by DoNextCombatManeuver(), and PlayerbotRogueAI().
The documentation for this class was generated from the following files:
PlayerbotRogueAI.h
PlayerbotRogueAI.cpp