CMaNGOS_WoTLK: EffectMovementGenerator Class Reference
EffectMovementGenerator Class Reference
#include <WrapperMovementGenerator.h>
Public Member Functions
EffectMovementGenerator (Movement::MoveSplineInit &spline, uint32 id=0, bool delayed=false, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
bool Update (Unit &owner, const uint32 &diff) override
void UnitSpeedChanged () override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from AbstractWrapperMovementGenerator
AbstractWrapperMovementGenerator (Movement::MoveSplineInit &spline, uint32 id=0, bool delayed=false, bool resident=true, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void Reset (Unit &owner) override
void Inform (Unit &owner)
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Additional Inherited Members
Protected Attributes inherited from AbstractWrapperMovementGenerator
Movement::MoveSplineInit i_spline
uint32 i_id
bool i_delayed
bool i_resident
bool i_dispatched
bool i_informed
bool i_useTimer
bool i_timerSet
ShortTimeTracker m_delayTimer
ObjectGuid m_guid
uint32 m_relayId
Detailed Description
Definition at line 52 of file WrapperMovementGenerator.h.
Constructor & Destructor Documentation
EffectMovementGenerator()
EffectMovementGenerator::EffectMovementGenerator (Movement::MoveSplineInit & spline, uint32 id = 0, bool delayed = false, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0) inline
Definition at line 55 of file WrapperMovementGenerator.h.
Member Function Documentation
Finalize()
void EffectMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from AbstractWrapperMovementGenerator.
Definition at line 159 of file WrapperMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractWrapperMovementGenerator::Finalize(), UNIT_STAT_PROPELLED, UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
GetMovementGeneratorType()
MovementGeneratorType EffectMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements AbstractWrapperMovementGenerator.
Reimplemented in FallMovementGenerator.
Definition at line 65 of file WrapperMovementGenerator.h.
References EFFECT_MOTION_TYPE.
Initialize()
void EffectMovementGenerator::Initialize (Unit & owner) override virtual
Reimplemented from AbstractWrapperMovementGenerator.
Definition at line 149 of file WrapperMovementGenerator.cpp.
References Unit::addUnitState(), AbstractWrapperMovementGenerator::i_delayed, AbstractWrapperMovementGenerator::i_dispatched, AbstractWrapperMovementGenerator::Initialize(), UNIT_STAT_PROPELLED, UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Interrupt()
void EffectMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from AbstractWrapperMovementGenerator.
Definition at line 165 of file WrapperMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractWrapperMovementGenerator::Interrupt(), and UNIT_STAT_ROAMING_MOVE.
UnitSpeedChanged()
void EffectMovementGenerator::UnitSpeedChanged () inline override virtual
Implements AbstractWrapperMovementGenerator.
Definition at line 63 of file WrapperMovementGenerator.h.
Update()
bool EffectMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Reimplemented from AbstractWrapperMovementGenerator.
Definition at line 171 of file WrapperMovementGenerator.cpp.
References Unit::addUnitState(), AbstractWrapperMovementGenerator::i_delayed, AbstractWrapperMovementGenerator::i_dispatched, UNIT_STAT_ROAMING_MOVE, and AbstractWrapperMovementGenerator::Update().
The documentation for this class was generated from the following files:
WrapperMovementGenerator.h
WrapperMovementGenerator.cpp