CMaNGOS_WoTLK: MaNGOS::thread_local_ptr< T > Class Template Reference
MaNGOS::thread_local_ptr< T > Class Template Reference
#include <TSS.h>
Public Member Functions
thread_local_ptr ()
thread_local_ptr (Generate generator)
thread_local_ptr (Generate generator, Cleanup cleanup)
T * get_value ()
T * get ()
T * operator-> ()
boost::detail::sp_dereference< T >::type operator* () const
Private Types
typedef std::function< T *()> Generate
typedef std::function< void(T *)> Cleanup
Private Attributes
Generate m_generator
Detailed Description
template<typename T>
class MaNGOS::thread_local_ptr< T >
Definition at line 30 of file TSS.h.
Member Typedef Documentation
Cleanup
template<typename T > typedef std::function<void(T*)> MaNGOS::thread_local_ptr< T >::Cleanup private
Definition at line 34 of file TSS.h.
Generate
template<typename T > typedef std::function<T* ()> MaNGOS::thread_local_ptr< T >::Generate private
Definition at line 33 of file TSS.h.
Constructor & Destructor Documentation
thread_local_ptr() [1/3]
template<typename T > MaNGOS::thread_local_ptr< T >::thread_local_ptr () inline
Definition at line 39 of file TSS.h.
thread_local_ptr() [2/3]
template<typename T > MaNGOS::thread_local_ptr< T >::thread_local_ptr (Generate generator) inline
Definition at line 40 of file TSS.h.
thread_local_ptr() [3/3]
template<typename T > MaNGOS::thread_local_ptr< T >::thread_local_ptr (Generate generator, Cleanup cleanup) inline
Definition at line 41 of file TSS.h.
Member Function Documentation
get()
template<typename T > T* MaNGOS::thread_local_ptr< T >::get () inline
Definition at line 46 of file TSS.h.
References MaNGOS::thread_local_ptr< T >::get_value(), and MaNGOS::thread_local_ptr< T >::m_generator.
Referenced by MaNGOS::thread_local_ptr< T >::operator*(), and MaNGOS::thread_local_ptr< T >::operator->().
get_value()
template<typename T > T* MaNGOS::thread_local_ptr< T >::get_value () inline
Definition at line 44 of file TSS.h.
Referenced by MaNGOS::thread_local_ptr< T >::get().
operator*()
template<typename T > boost::detail::sp_dereference< T >::type MaNGOS::thread_local_ptr< T >::operator* () const inline
Definition at line 62 of file TSS.h.
References MaNGOS::thread_local_ptr< T >::get().
operator->()
template<typename T > T* MaNGOS::thread_local_ptr< T >::operator-> () inline
Definition at line 57 of file TSS.h.
References MaNGOS::thread_local_ptr< T >::get().
Field Documentation
m_generator
template<typename T > Generate MaNGOS::thread_local_ptr< T >::m_generator private
Definition at line 36 of file TSS.h.
Referenced by MaNGOS::thread_local_ptr< T >::get().
The documentation for this class was generated from the following file:
TSS.h