CMaNGOS_WoTLK: GossipMenu Class Reference
GossipMenu Class Reference
#include <GossipDef.h>
Public Member Functions
GossipMenu (WorldSession *session)
~GossipMenu ()
void AddMenuItem (uint8 Icon, const std::string &Message, bool Coded=false)
void AddMenuItem (uint8 Icon, const std::string &Message, uint32 dtSender, uint32 dtAction, const std::string &BoxMessage, uint32 BoxMoney, bool Coded=false)
void AddMenuItem (uint8 Icon, char const *Message, bool Coded=false)
void AddMenuItem (uint8 Icon, char const *Message, uint32 dtSender, uint32 dtAction, char const *BoxMessage, uint32 BoxMoney, bool Coded=false)
void AddMenuItem (uint8 Icon, int32 itemText, uint32 dtSender, uint32 dtAction, int32 boxText, uint32 BoxMoney, bool Coded=false)
void SetMenuId (uint32 menu_id)
uint32 GetMenuId () const
void SetDiscoveredNode ()
bool IsJustDiscoveredNode () const
void AddGossipMenuItemData (int32 action_menu, uint32 action_poi, uint32 action_script)
unsigned int MenuItemCount () const
bool Empty () const
GossipMenuItem const & GetItem (unsigned int Id)
bool IsItemsDataEmpty () const
GossipMenuItemData const * GetItemData (unsigned int indexId)
uint32 MenuItemSender (unsigned int ItemId)
uint32 MenuItemAction (unsigned int ItemId)
bool MenuItemCoded (unsigned int ItemId)
void ClearMenu ()
WorldSession * GetMenuSession () const
Protected Attributes
GossipMenuItemList m_gItems
GossipMenuItemDataList m_gItemsData
uint32 m_gMenuId
bool m_discoveredNode
Private Attributes
WorldSession * m_session
Detailed Description
Definition at line 166 of file GossipDef.h.
Constructor & Destructor Documentation
GossipMenu()
GossipMenu::GossipMenu (WorldSession * session) explicit
Definition at line 27 of file GossipDef.cpp.
References m_discoveredNode, m_gItems, and m_gMenuId.
~GossipMenu()
GossipMenu::~GossipMenu ()
Definition at line 34 of file GossipDef.cpp.
References ClearMenu().
Member Function Documentation
AddGossipMenuItemData()
void GossipMenu::AddGossipMenuItemData (int32 action_menu, uint32 action_poi, uint32 action_script)
Definition at line 56 of file GossipDef.cpp.
References GossipMenuItemData::m_gAction_menu, GossipMenuItemData::m_gAction_poi, GossipMenuItemData::m_gAction_script, and m_gItemsData.
AddMenuItem() [1/5]
void GossipMenu::AddMenuItem (uint8 Icon, char const * Message, bool Coded = false)
Definition at line 72 of file GossipDef.cpp.
References AddMenuItem().
AddMenuItem() [2/5]
void GossipMenu::AddMenuItem (uint8 Icon, char const * Message, uint32 dtSender, uint32 dtAction, char const * BoxMessage, uint32 BoxMoney, bool Coded = false)
Definition at line 77 of file GossipDef.cpp.
References AddMenuItem().
AddMenuItem() [3/5]
void GossipMenu::AddMenuItem (uint8 Icon, const std::string & Message, bool Coded = false)
Definition at line 67 of file GossipDef.cpp.
Referenced by AddMenuItem().
AddMenuItem() [4/5]
void GossipMenu::AddMenuItem (uint8 Icon, const std::string & Message, uint32 dtSender, uint32 dtAction, const std::string & BoxMessage, uint32 BoxMoney, bool Coded = false)
Definition at line 39 of file GossipDef.cpp.
References GOSSIP_MAX_MENU_ITEMS, GossipMenuItem::m_gBoxMessage, GossipMenuItem::m_gBoxMoney, GossipMenuItem::m_gCoded, GossipMenuItem::m_gIcon, m_gItems, GossipMenuItem::m_gMessage, GossipMenuItem::m_gOptionId, GossipMenuItem::m_gSender, and MANGOS_ASSERT.
AddMenuItem() [5/5]
void GossipMenu::AddMenuItem (uint8 Icon, int32 itemText, uint32 dtSender, uint32 dtAction, int32 boxText, uint32 BoxMoney, bool Coded = false)
Definition at line 82 of file GossipDef.cpp.
References AddMenuItem(), WorldSession::GetSessionDbLocaleIndex(), m_session, and sObjectMgr.
ClearMenu()
void GossipMenu::ClearMenu ()
Definition at line 116 of file GossipDef.cpp.
References m_discoveredNode, m_gItems, m_gItemsData, and m_gMenuId.
Referenced by PlayerMenu::ClearMenus(), and ~GossipMenu().
Empty()
bool GossipMenu::Empty () const inline
Definition at line 195 of file GossipDef.h.
References m_gItems.
Referenced by PlayerMenu::Empty().
GetItem()
GossipMenuItem const& GossipMenu::GetItem (unsigned int Id) inline
Definition at line 200 of file GossipDef.h.
References m_gItems.
Referenced by Player::OnGossipSelect(), and PlayerMenu::SendGossipMenu().
GetItemData()
GossipMenuItemData const* GossipMenu::GetItemData (unsigned int indexId) inline
Definition at line 207 of file GossipDef.h.
References m_gItemsData, and sLog.
Referenced by Player::OnGossipSelect().
GetMenuId()
uint32 GossipMenu::GetMenuId () const inline
Definition at line 182 of file GossipDef.h.
References m_gMenuId.
Referenced by Player::OnGossipSelect(), PlayerMenu::SendGossipMenu(), and Player::SendPreparedGossip().
GetMenuSession()
WorldSession* GossipMenu::GetMenuSession () const inline
Definition at line 223 of file GossipDef.h.
References m_session.
Referenced by PlayerMenu::GetMenuSession().
IsItemsDataEmpty()
bool GossipMenu::IsItemsDataEmpty () const inline
Definition at line 205 of file GossipDef.h.
References m_gItemsData.
IsJustDiscoveredNode()
bool GossipMenu::IsJustDiscoveredNode () const inline
Definition at line 186 of file GossipDef.h.
References m_discoveredNode.
Referenced by Player::SendPreparedGossip().
MenuItemAction()
uint32 GossipMenu::MenuItemAction (unsigned int ItemId)
Definition at line 100 of file GossipDef.cpp.
References m_gItems.
Referenced by PlayerMenu::GossipOptionAction().
MenuItemCoded()
bool GossipMenu::MenuItemCoded (unsigned int ItemId)
Definition at line 108 of file GossipDef.cpp.
References m_gItems.
Referenced by PlayerMenu::GossipOptionCoded().
MenuItemCount()
unsigned int GossipMenu::MenuItemCount () const inline
Definition at line 190 of file GossipDef.h.
References m_gItems.
Referenced by Player::OnGossipSelect(), and PlayerMenu::SendGossipMenu().
MenuItemSender()
uint32 GossipMenu::MenuItemSender (unsigned int ItemId)
Definition at line 92 of file GossipDef.cpp.
References m_gItems.
Referenced by PlayerMenu::GossipOptionSender().
SetDiscoveredNode()
void GossipMenu::SetDiscoveredNode () inline
Definition at line 185 of file GossipDef.h.
References m_discoveredNode.
SetMenuId()
void GossipMenu::SetMenuId (uint32 menu_id) inline
Definition at line 181 of file GossipDef.h.
References m_gMenuId.
Field Documentation
m_discoveredNode
bool GossipMenu::m_discoveredNode protected
Definition at line 230 of file GossipDef.h.
Referenced by ClearMenu(), GossipMenu(), IsJustDiscoveredNode(), and SetDiscoveredNode().
m_gItems
GossipMenuItemList GossipMenu::m_gItems protected
Definition at line 226 of file GossipDef.h.
Referenced by AddMenuItem(), ClearMenu(), Empty(), GetItem(), GossipMenu(), MenuItemAction(), MenuItemCoded(), MenuItemCount(), and MenuItemSender().
m_gItemsData
GossipMenuItemDataList GossipMenu::m_gItemsData protected
Definition at line 227 of file GossipDef.h.
Referenced by AddGossipMenuItemData(), ClearMenu(), GetItemData(), and IsItemsDataEmpty().
m_gMenuId
uint32 GossipMenu::m_gMenuId protected
Definition at line 229 of file GossipDef.h.
Referenced by ClearMenu(), GetMenuId(), GossipMenu(), and SetMenuId().
m_session
WorldSession* GossipMenu::m_session private
Definition at line 233 of file GossipDef.h.
Referenced by AddMenuItem(), and GetMenuSession().
The documentation for this class was generated from the following files:
GossipDef.h
GossipDef.cpp