CMaNGOS_WoTLK: instance_blood_furnace Class Reference
instance_blood_furnace Class Reference
#include <blood_furnace.h>
Public Member Functions
instance_blood_furnace (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void OnCreatureDeath (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
void Update (const uint32 diff) override
void Load (const char *chrIn) override
const char * Save () const override
void GetKelidanAddList (GuidList &lList)
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoSortBroggokOrcs ()
void DoNextBroggokEventPhase ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
BroggokEventInfo m_aBroggokEvent [MAX_ORC_WAVES]
uint32 m_uiBroggokEventTimer
uint32 m_uiBroggokEventPhase
uint32 m_uiRandYellTimer
uint32 m_crackTimer
GameObject * m_lLeverGO
GuidList m_cracks
GuidList m_luiNascentOrcGuids
GuidList m_lChannelersGuids
bool m_firstPlayer
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 72 of file blood_furnace.h.
Constructor & Destructor Documentation
instance_blood_furnace()
instance_blood_furnace::instance_blood_furnace (Map * pMap)
Definition at line 27 of file blood_furnace.cpp.
References Initialize().
Member Function Documentation
DoNextBroggokEventPhase()
void instance_blood_furnace::DoNextBroggokEventPhase () private
Definition at line 257 of file blood_furnace.cpp.
References ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DOOR_BROGGOK_REAR, IN_MILLISECONDS, InstanceData::instance, m_aBroggokEvent, BroggokEventInfo::m_bIsCellOpened, m_uiBroggokEventPhase, m_uiBroggokEventTimer, MAX_ORC_WAVES, NPC_BROGGOK, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by OnCreatureDeath(), SetData(), and Update().
DoSortBroggokOrcs()
void instance_blood_furnace::DoSortBroggokOrcs () private
Definition at line 444 of file blood_furnace.cpp.
References Map::GetCreature(), Map::GetGameObject(), Position::GetPositionZ(), InstanceData::instance, m_aBroggokEvent, m_luiNascentOrcGuids, Position::x, Position::y, and Position::z.
Referenced by SetData().
ExecuteChatCommand()
void instance_blood_furnace::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 426 of file blood_furnace.cpp.
References ChatHandler::ExtractLiteralArg(), FAIL, GetData(), IN_PROGRESS, m_uiBroggokEventPhase, ChatHandler::PSendSysMessage(), SetData(), and TYPE_BROGGOK_EVENT.
GetData()
uint32 instance_blood_furnace::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 393 of file blood_furnace.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by ExecuteChatCommand().
GetKelidanAddList()
void instance_blood_furnace::GetKelidanAddList (GuidList & lList) inline
Definition at line 95 of file blood_furnace.h.
References m_lChannelersGuids.
Referenced by boss_kelidan_the_breakerAI::DoSetupAdds().
Initialize()
void instance_blood_furnace::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 37 of file blood_furnace.cpp.
References m_auiEncounter.
Referenced by instance_blood_furnace().
Load()
void instance_blood_furnace::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 401 of file blood_furnace.cpp.
References FAIL, IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_blood_furnace::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 42 of file blood_furnace.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lChannelersGuids, m_luiNascentOrcGuids, ScriptedInstance::m_npcEntryGuidStore, NPC_BROGGOK, NPC_FEL_ORC_NEOPHYTE, NPC_IN_COMBAT_TRIGGER, NPC_KELIDAN_THE_BREAKER, NPC_MAGTHERIDON, NPC_NASCENT_FEL_ORC, NPC_SHADOWMOON_CHANNELER, Object::SetFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
OnCreatureDeath()
void instance_blood_furnace::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 314 of file blood_furnace.cpp.
References DoNextBroggokEventPhase(), Object::GetEntry(), Object::GetObjectGuid(), IN_PROGRESS, m_aBroggokEvent, m_auiEncounter, BroggokEventInfo::m_sSortedOrcGuids, m_uiBroggokEventPhase, BroggokEventInfo::m_uiKilledOrcCount, MAX_ORC_WAVES, NPC_FEL_ORC_NEOPHYTE, NPC_NASCENT_FEL_ORC, and TYPE_BROGGOK_EVENT.
OnCreatureEvade()
void instance_blood_furnace::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 296 of file blood_furnace.cpp.
References FAIL, Object::GetEntry(), Object::GetObjectGuid(), m_aBroggokEvent, m_auiEncounter, BroggokEventInfo::m_sSortedOrcGuids, m_uiBroggokEventPhase, MAX_ORC_WAVES, NPC_BROGGOK, NPC_FEL_ORC_NEOPHYTE, NPC_NASCENT_FEL_ORC, SetData(), and TYPE_BROGGOK_EVENT.
OnObjectCreate()
void instance_blood_furnace::OnObjectCreate (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 63 of file blood_furnace.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_CRACK_1, GO_CRACK_2, GO_CRACK_3, GO_CRACK_4, GO_CRACK_5, GO_CRACK_6, GO_CRACK_7, GO_DOOR_BROGGOK_FRONT, GO_DOOR_BROGGOK_REAR, GO_DOOR_FINAL_EXIT, GO_DOOR_KELIDAN_EXIT, GO_DOOR_MAKER_FRONT, GO_DOOR_MAKER_REAR, GO_PRISON_CELL_BROGGOK_1, GO_PRISON_CELL_BROGGOK_2, GO_PRISON_CELL_BROGGOK_3, GO_PRISON_CELL_BROGGOK_4, GO_PRISON_CELL_DOOR_LEVER, GO_STATE_ACTIVE, IN_PROGRESS, m_aBroggokEvent, m_auiEncounter, BroggokEventInfo::m_cellGuid, m_cracks, ScriptedInstance::m_goEntryGuidStore, m_lLeverGO, GameObject::Respawn(), GameObject::SetGoState(), GameObject::SetRespawnTime(), TYPE_BROGGOK_EVENT, TYPE_KELIDAN_EVENT, and TYPE_THE_MAKER_EVENT.
OnPlayerEnter()
void instance_blood_furnace::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 230 of file blood_furnace.cpp.
References Map::GetCreature(), Map::GetGameObject(), InstanceData::instance, m_aBroggokEvent, BroggokEventInfo::m_cellGuid, m_firstPlayer, m_luiNascentOrcGuids, MAX_ORC_WAVES, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_UNINTERACTIBLE.
Save()
const char* instance_blood_furnace::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 93 of file blood_furnace.h.
References m_strInstData.
SetData()
void instance_blood_furnace::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 120 of file blood_furnace.cpp.
References DONE, DoNextBroggokEventPhase(), DoScriptText(), DoSortBroggokOrcs(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DOOR_BROGGOK_FRONT, GO_DOOR_FINAL_EXIT, GO_DOOR_KELIDAN_EXIT, GO_DOOR_MAKER_FRONT, GO_DOOR_MAKER_REAR, IN_PROGRESS, InstanceData::instance, m_aBroggokEvent, m_auiEncounter, m_lLeverGO, m_strInstData, m_uiBroggokEventPhase, MAX_ORC_WAVES, NPC_BROGGOK, NPC_IN_COMBAT_TRIGGER, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, GameObject::Respawn(), InstanceData::SaveToDB(), SAY_BROGGOK_INTRO, script_error_log(), GameObject::SetRespawnTime(), SPELL_COMBAT_TRIGGER, TRIGGERED_OLD_TRIGGERED, TYPE_BROGGOK_EVENT, TYPE_KELIDAN_EVENT, TYPE_THE_MAKER_EVENT, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by ExecuteChatCommand(), boss_kelidan_the_breakerAI::JustDied(), boss_kelidan_the_breakerAI::JustReachedHome(), OnCreatureEvade(), and Update().
ShowChatCommands()
void instance_blood_furnace::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 421 of file blood_furnace.cpp.
References ChatHandler::SendSysMessage().
Update()
void instance_blood_furnace::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 344 of file blood_furnace.cpp.
References aRandomTaunt, DoNextBroggokEventPhase(), DoScriptText(), FAIL, Map::GetGameObject(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_STATE_READY, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, m_cracks, m_crackTimer, m_uiBroggokEventPhase, m_uiBroggokEventTimer, m_uiRandYellTimer, MAX_ORC_WAVES, NPC_MAGTHERIDON, SetData(), TYPE_BROGGOK_EVENT, and urand().
Field Documentation
m_aBroggokEvent
BroggokEventInfo instance_blood_furnace::m_aBroggokEvent[MAX_ORC_WAVES] private
Definition at line 107 of file blood_furnace.h.
Referenced by DoNextBroggokEventPhase(), DoSortBroggokOrcs(), OnCreatureDeath(), OnCreatureEvade(), OnObjectCreate(), OnPlayerEnter(), and SetData().
m_auiEncounter
uint32 instance_blood_furnace::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 104 of file blood_furnace.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureDeath(), OnCreatureEvade(), OnObjectCreate(), SetData(), and Update().
m_cracks
GuidList instance_blood_furnace::m_cracks private
Definition at line 116 of file blood_furnace.h.
Referenced by OnObjectCreate(), and Update().
m_crackTimer
uint32 instance_blood_furnace::m_crackTimer private
Definition at line 112 of file blood_furnace.h.
Referenced by Update().
m_firstPlayer
bool instance_blood_furnace::m_firstPlayer private
Definition at line 120 of file blood_furnace.h.
Referenced by OnPlayerEnter().
m_lChannelersGuids
GuidList instance_blood_furnace::m_lChannelersGuids private
Definition at line 118 of file blood_furnace.h.
Referenced by GetKelidanAddList(), and OnCreatureCreate().
m_lLeverGO
GameObject* instance_blood_furnace::m_lLeverGO private
Definition at line 114 of file blood_furnace.h.
Referenced by OnObjectCreate(), and SetData().
m_luiNascentOrcGuids
GuidList instance_blood_furnace::m_luiNascentOrcGuids private
Definition at line 117 of file blood_furnace.h.
Referenced by DoSortBroggokOrcs(), OnCreatureCreate(), and OnPlayerEnter().
m_strInstData
std::string instance_blood_furnace::m_strInstData private
Definition at line 105 of file blood_furnace.h.
Referenced by Save(), and SetData().
m_uiBroggokEventPhase
uint32 instance_blood_furnace::m_uiBroggokEventPhase private
Definition at line 110 of file blood_furnace.h.
Referenced by DoNextBroggokEventPhase(), ExecuteChatCommand(), OnCreatureDeath(), OnCreatureEvade(), SetData(), and Update().
m_uiBroggokEventTimer
uint32 instance_blood_furnace::m_uiBroggokEventTimer private
Definition at line 109 of file blood_furnace.h.
Referenced by DoNextBroggokEventPhase(), and Update().
m_uiRandYellTimer
uint32 instance_blood_furnace::m_uiRandYellTimer private
Definition at line 111 of file blood_furnace.h.
Referenced by Update().
The documentation for this class was generated from the following files:
blood_furnace.h
blood_furnace.cpp