CMaNGOS_WoTLK: MaNGOS::LocalizedPacketDo< Builder > Class Template Reference
MaNGOS::LocalizedPacketDo< Builder > Class Template Reference
#include <GridNotifiers.h>
Public Member Functions
LocalizedPacketDo (Builder &builder)
void operator() (Player *p)
Private Attributes
Builder & i_builder
std::vector< std::unique_ptr< WorldPacket > > i_data_cache
Detailed Description
template<class Builder>
class MaNGOS::LocalizedPacketDo< Builder >
Definition at line 1575 of file GridNotifiers.h.
Constructor & Destructor Documentation
LocalizedPacketDo()
template<class Builder > MaNGOS::LocalizedPacketDo< Builder >::LocalizedPacketDo (Builder & builder) inline explicit
Definition at line 1578 of file GridNotifiers.h.
Member Function Documentation
operator()()
template<class Builder > void MaNGOS::LocalizedPacketDo< Builder >::operator() (Player * p)
Definition at line 681 of file GridNotifiersImpl.h.
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Player::SendDirectMessage().
Field Documentation
i_builder
template<class Builder > Builder& MaNGOS::LocalizedPacketDo< Builder >::i_builder private
Definition at line 1583 of file GridNotifiers.h.
i_data_cache
template<class Builder > std::vector<std::unique_ptr<WorldPacket> > MaNGOS::LocalizedPacketDo< Builder >::i_data_cache private
Definition at line 1584 of file GridNotifiers.h.
The documentation for this class was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h