CMaNGOS_WoTLK: BattleGroundWS Class Reference
BattleGroundWS Class Reference
#include <BattleGroundWS.h>
Public Member Functions
BattleGroundWS ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *player) override
Method that is called when adding a player to the battleground.
void RemovePlayer (Player *player, ObjectGuid guid) override
Method that handles generic logic when removing a player.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
Team GetPrematureWinner () override
Function that returns the premature winner.
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
bool HandleAreaTrigger (Player *source, uint32 trigger) override
void HandleGameObjectCreate (GameObject *go) override
void HandleKillPlayer (Player *player, Player *killer) override
Method that handles killing players.
void HandlePlayerClickedOnFlag (Player *source, GameObject *go) override
void HandlePlayerDroppedFlag (Player *source) override
ObjectGuid const & GetFlagCarrierGuid (uint8 teamIdx) const
bool IsFlagHeldFor45Seconds (Team flagHolderTeam)
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target, uint32 miscvalue1) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual void HandleKillUnit (Creature *, Player *)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Private Member Functions
void SetFlagCarrier (uint8 teamIdx, ObjectGuid guid)
void ClearFlagCarrier (uint8 teamIdx)
bool IsFlagPickedUp (uint8 teamIdx) const
void ClearDroppedFlagGuid (Team team)
ObjectGuid const & GetDroppedFlagGuid (Team team) const
void RespawnFlagAtBase (Team team, bool wasCaptured)
void RespawnDroppedFlag (Team team)
int32 GetFlagState (Team team)
void ProcessFlagPickUpFromBase (Player *player, Team attackerTeam)
void ProcessDroppedFlagActions (Player *player, GameObject *target)
uint32 GetRemainingTimeInMinutes () const
void ProcessPlayerFlagScoreEvent (Player *source)
Private Attributes
ObjectGuid m_droppedFlagGuid [PVP_TEAM_COUNT]
ObjectGuid m_flagCarrier [PVP_TEAM_COUNT]
bool m_flagOnRespawn [PVP_TEAM_COUNT]
TimePoint m_flagPickupFromBaseTime [PVP_TEAM_COUNT]
uint32 m_flagsTimer [PVP_TEAM_COUNT]
uint32 m_flagsDropTimer [PVP_TEAM_COUNT]
uint32 m_flagCarrierDebuffTimer
bool m_focusedAssaultActive
bool m_brutalAssaultActive
uint32 m_reputationCapture
uint32 m_honorWinKills
uint32 m_honorEndKills
uint32 m_endTimer
Team m_lastCapturedFlagTeam
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 212 of file BattleGroundWS.h.
Constructor & Destructor Documentation
BattleGroundWS()
BattleGroundWS::BattleGroundWS ()
Definition at line 28 of file BattleGroundWS.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_WS_HAS_BEGUN, LANG_BG_WS_START_HALF_MINUTE, LANG_BG_WS_START_ONE_MINUTE, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundWS::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 149 of file BattleGroundWS.cpp.
References BattleGround::AddPlayer(), Object::GetObjectGuid(), and BattleGround::m_playerScores.
CheckAchievementCriteriaMeet()
bool BattleGroundWS::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 700 of file BattleGroundWS.cpp.
References ALLIANCE, BG_WS_FLAG_STATE_ON_BASE, BG_WS_SPELL_SILVERWING_FLAG, BG_WS_SPELL_WARSONG_FLAG, WorldObject::GetAreaId(), BattleGround::GetBgMap(), Player::GetTeam(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), BattleGround::GetWinner(), Unit::HasAura(), HORDE, TEAM_INDEX_ALLIANCE, WINNER_ALLIANCE, WINNER_HORDE, WS_ACHIEV_IRONMAN, WS_ACHIEV_SAVE_THE_DAY_1, WS_ACHIEV_SAVE_THE_DAY_2, and wsFlagPickedUp.
ClearDroppedFlagGuid()
void BattleGroundWS::ClearDroppedFlagGuid (Team team) inline private
Definition at line 255 of file BattleGroundWS.h.
References ObjectGuid::Clear(), GetTeamIndexByTeamId(), and m_droppedFlagGuid.
Referenced by RespawnDroppedFlag().
ClearFlagCarrier()
void BattleGroundWS::ClearFlagCarrier (uint8 teamIdx) inline private
Definition at line 251 of file BattleGroundWS.h.
References ObjectGuid::Clear(), and m_flagCarrier.
Referenced by HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), and RemovePlayer().
EndBattleGround()
void BattleGroundWS::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 641 of file BattleGroundWS.cpp.
References ALLIANCE, BattleGround::EndBattleGround(), BattleGround::GetBonusHonorFromKill(), HORDE, m_honorEndKills, m_honorWinKills, and BattleGround::RewardHonorToTeam().
Referenced by ProcessPlayerFlagScoreEvent(), and Update().
GetDroppedFlagGuid()
ObjectGuid const& BattleGroundWS::GetDroppedFlagGuid (Team team) const inline private
Definition at line 256 of file BattleGroundWS.h.
References GetTeamIndexByTeamId(), and m_droppedFlagGuid.
Referenced by RespawnDroppedFlag().
GetFlagCarrierGuid()
ObjectGuid const& BattleGroundWS::GetFlagCarrierGuid (uint8 teamIdx) const inline
Definition at line 240 of file BattleGroundWS.h.
References m_flagCarrier.
Referenced by HandleAreaTrigger(), HandlePlayerDroppedFlag(), and Update().
GetFlagState()
int32 BattleGroundWS::GetFlagState (Team team) private
Definition at line 217 of file BattleGroundWS.cpp.
References BattleGround::GetBgMap(), GetTeamIndexByTeamId(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), and wsFlagPickedUp.
GetPrematureWinner()
Team BattleGroundWS::GetPrematureWinner () override virtual
Function that returns the premature winner.
Reimplemented from BattleGround.
Definition at line 683 of file BattleGroundWS.cpp.
References ALLIANCE, BG_WS_STATE_CAPTURES_ALLIANCE, BG_WS_STATE_CAPTURES_HORDE, BattleGround::GetBgMap(), BattleGround::GetPrematureWinner(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), HORDE, and m_lastCapturedFlagTeam.
Referenced by Update().
GetRemainingTimeInMinutes()
uint32 BattleGroundWS::GetRemainingTimeInMinutes () const inline private
Definition at line 266 of file BattleGroundWS.h.
References IN_MILLISECONDS, m_endTimer, and MINUTE.
Referenced by Reset(), and Update().
HandleAreaTrigger()
bool BattleGroundWS::HandleAreaTrigger (Player * source, uint32 trigger) override virtual
Reimplemented from BattleGround.
Definition at line 485 of file BattleGroundWS.cpp.
References BattleGround::GetBgMap(), GetFlagCarrierGuid(), Object::GetObjectGuid(), BattleGround::GetStatus(), ProcessPlayerFlagScoreEvent(), STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, WS_AT_SILVERWING_ROOM, WS_AT_WARSONG_ROOM, and wsFlagPickedUp.
HandleEvent()
bool BattleGroundWS::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from BattleGround.
Definition at line 527 of file BattleGroundWS.cpp.
References GAMEOBJECT_TYPE_FLAGDROP, Object::GetEntry(), GameObject::GetGoType(), BattleGround::GetOtherTeamIndex(), Player::GetTeam(), GetTeamIndexByTeamId(), GO_JUST_DEACTIVATED, HandlePlayerClickedOnFlag(), Object::IsGameObject(), Object::IsPlayer(), ProcessDroppedFlagActions(), GameObject::SetLootState(), WS_EVENT_ALLIANCE_FLAG_DROPPED_PICKUP, WS_EVENT_ALLIANCE_FLAG_PICKUP, WS_EVENT_HORDE_FLAG_DROPPED_PICKUP, WS_EVENT_HORDE_FLAG_PICKUP, and wsDroppedFlagId.
HandleGameObjectCreate()
void BattleGroundWS::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 512 of file BattleGroundWS.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_WS_SILVERWING_FLAG_DROP, GO_WS_WARSONG_FLAG_DROP, m_droppedFlagGuid, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
HandleKillPlayer()
void BattleGroundWS::HandleKillPlayer (Player * player, Player * killer) override virtual
Method that handles killing players.
also handles generic logic for arena updates
Parameters
victim player
killer player
Reimplemented from BattleGround.
Definition at line 653 of file BattleGroundWS.cpp.
References BattleGround::GetStatus(), BattleGround::HandleKillPlayer(), HandlePlayerDroppedFlag(), and STATUS_IN_PROGRESS.
HandlePlayerClickedOnFlag()
void BattleGroundWS::HandlePlayerClickedOnFlag (Player * source, GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 434 of file BattleGroundWS.cpp.
References Object::GetEntry(), BattleGround::GetStatus(), Player::GetTeam(), GO_WS_SILVERWING_FLAG, GO_WS_WARSONG_FLAG, ProcessFlagPickUpFromBase(), and STATUS_IN_PROGRESS.
Referenced by HandleEvent().
HandlePlayerDroppedFlag()
void BattleGroundWS::HandlePlayerDroppedFlag (Player * source) override virtual
Reimplemented from BattleGround.
Definition at line 295 of file BattleGroundWS.cpp.
References BG_WS_FLAG_ACTION_DROPPED, BG_WS_FLAG_ACTION_PICKEDUP, BG_WS_FLAG_DROP_TIME, BG_WS_FLAG_ICON_INVISIBLE, BG_WS_FLAG_STATE_ON_GROUND, BG_WS_SPELL_BRUTAL_ASSAULT, BG_WS_SPELL_FOCUSED_ASSAULT, Unit::CastSpell(), ClearFlagCarrier(), DEBUG_LOG, BattleGround::GetBgMap(), GetFlagCarrierGuid(), Object::GetObjectGuid(), BattleGround::GetOtherTeamIndex(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), Map::GetVariableManager(), IsFlagPickedUp(), m_flagsDropTimer, Unit::RemoveAurasDueToSpell(), BattleGround::SendMessageToAll(), WorldStateVariableManager::SetVariable(), SPELL_RECENTLY_DROPPED_FLAG, STATUS_IN_PROGRESS, TRIGGERED_OLD_TRIGGERED, wsFlagHUDPickedUp, wsFlagPickedUp, and wsgFlagData.
Referenced by HandleKillPlayer(), and RemovePlayer().
IsFlagHeldFor45Seconds()
bool BattleGroundWS::IsFlagHeldFor45Seconds (Team flagHolderTeam)
Definition at line 332 of file BattleGroundWS.cpp.
References BattleGround::GetBgMap(), Map::GetCurrentClockTime(), BattleGround::GetOtherTeamIndex(), GetTeamIndexByTeamId(), and m_flagPickupFromBaseTime.
Referenced by WorldSession::HandleBattleGroundPlayerPositionsOpcode().
IsFlagPickedUp()
bool BattleGroundWS::IsFlagPickedUp (uint8 teamIdx) const inline private
Definition at line 252 of file BattleGroundWS.h.
References ObjectGuid::IsEmpty(), and m_flagCarrier.
Referenced by HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), RemovePlayer(), and Update().
ProcessDroppedFlagActions()
void BattleGroundWS::ProcessDroppedFlagActions (Player * player, GameObject * target) private
Definition at line 372 of file BattleGroundWS.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, BG_WS_FLAG_ACTION_NONE, BG_WS_FLAG_ACTION_PICKEDUP, BG_WS_FLAG_ACTION_RETURNED, BG_WS_FLAG_ICON_INVISIBLE, BG_WS_FLAG_ICON_VISIBLE, BG_WS_FLAG_STATE_ON_BASE, BG_WS_FLAG_STATE_ON_GROUND, BG_WS_FLAG_STATE_ON_PLAYER, BG_WS_SPELL_BRUTAL_ASSAULT, BG_WS_SPELL_FOCUSED_ASSAULT, Unit::CastSpell(), DEBUG_LOG, BattleGround::GetBgMap(), Object::GetEntry(), Object::GetObjectGuid(), BattleGround::GetOtherTeamIndex(), Player::GetTeam(), GetTeamIndexByTeamId(), Map::GetVariableManager(), m_brutalAssaultActive, m_focusedAssaultActive, BattleGround::PlaySoundToAll(), Unit::RemoveAurasWithInterruptFlags(), RespawnFlagAtBase(), SCORE_FLAG_RETURNS, BattleGround::SendMessageToAll(), SetFlagCarrier(), WorldStateVariableManager::SetVariable(), BattleGround::SpawnEvent(), TRIGGERED_OLD_TRIGGERED, Player::UpdateAchievementCriteria(), UpdatePlayerScore(), wsDroppedFlagId, wsFlagHUDPickedUp, wsFlagPickedUp, and wsgFlagData.
Referenced by HandleEvent().
ProcessFlagPickUpFromBase()
void BattleGroundWS::ProcessFlagPickUpFromBase (Player * player, Team attackerTeam) private
Definition at line 340 of file BattleGroundWS.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ALLIANCE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, BG_WS_FLAG_ACTION_PICKEDUP, BG_WS_FLAG_ICON_VISIBLE, BG_WS_FLAG_STATE_ON_BASE, BG_WS_FLAG_STATE_ON_PLAYER, BG_WS_SPELL_BRUTAL_ASSAULT, BG_WS_SPELL_FOCUSED_ASSAULT, Unit::CastSpell(), DEBUG_LOG, Player::GetAchievementMgr(), BattleGround::GetBgMap(), Map::GetCurrentClockTime(), Object::GetObjectGuid(), BattleGround::GetOtherTeamIndex(), Player::GetTeam(), GetTeamIndexByTeamId(), Map::GetVariableManager(), m_brutalAssaultActive, m_flagOnRespawn, m_flagPickupFromBaseTime, m_focusedAssaultActive, BattleGround::PlaySoundToAll(), Unit::RemoveAurasWithInterruptFlags(), BattleGround::SendMessageToAll(), SetFlagCarrier(), WorldStateVariableManager::SetVariable(), BattleGround::SpawnEvent(), AchievementMgr::StartTimedAchievementCriteria(), TRIGGERED_OLD_TRIGGERED, WS_TIMED_ACHIEV_QUICK_CAP_A, WS_TIMED_ACHIEV_QUICK_CAP_H, wsFlagHUDPickedUp, wsFlagPickedUp, and wsgFlagData.
Referenced by HandlePlayerClickedOnFlag().
ProcessPlayerFlagScoreEvent()
void BattleGroundWS::ProcessPlayerFlagScoreEvent (Player * source) private
Definition at line 224 of file BattleGroundWS.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ALLIANCE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, BG_WS_FLAG_ACTION_CAPTURED, BG_WS_FLAG_ACTION_PICKEDUP, BG_WS_FLAG_ICON_INVISIBLE, BG_WS_FLAG_RESPAWN_TIME, BG_WS_FLAG_STATE_ON_BASE, BG_WS_MAX_TEAM_SCORE, BG_WS_SPELL_BRUTAL_ASSAULT, BG_WS_SPELL_FOCUSED_ASSAULT, BG_WS_STATE_CAPTURES_ALLIANCE, BG_WS_STATE_CAPTURES_HORDE, BG_WS_STATE_FLAG_ALLIANCE, BG_WS_STATE_FLAG_HORDE, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_ALLIANCE, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_HORDE, ClearFlagCarrier(), DEBUG_LOG, EndBattleGround(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), BattleGround::GetOtherTeamIndex(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIdByTeamIndex(), GetTeamIndexByTeamId(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), IsFlagPickedUp(), m_flagOnRespawn, m_flagsTimer, m_reputationCapture, BattleGround::PlaySoundToAll(), Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasWithInterruptFlags(), BattleGround::RewardHonorToTeam(), BattleGround::RewardReputationToTeam(), SCORE_FLAG_CAPTURES, BattleGround::SendMessageToAll(), WorldStateVariableManager::SetVariable(), BattleGround::SpawnEvent(), STATUS_IN_PROGRESS, TEAM_NONE, Player::UpdateAchievementCriteria(), UpdatePlayerScore(), WS_EVENT_FLAG_A, WS_EVENT_FLAG_H, wsFlagHUDPickedUp, wsFlagPickedUp, and wsgFlagData.
Referenced by HandleAreaTrigger().
RemovePlayer()
void BattleGroundWS::RemovePlayer (Player * , ObjectGuid) override virtual
Method that handles generic logic when removing a player.
used mainly for arena logic
Parameters
player
guid
Reimplemented from BattleGround.
Definition at line 450 of file BattleGroundWS.cpp.
References ALLIANCE, ClearFlagCarrier(), BattleGround::GetOtherTeamIndex(), Player::GetTeam(), GetTeamIndexByTeamId(), HandlePlayerDroppedFlag(), HORDE, IsFlagPickedUp(), m_flagCarrier, RespawnFlagAtBase(), sLog, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Reset()
void BattleGroundWS::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 582 of file BattleGroundWS.cpp.
References ALLIANCE, BG_EVENT_NONE, BG_WS_BRUTAL_ASSAULT_TIME, BG_WS_FLAG_ICON_INVISIBLE, BG_WS_MAX_TEAM_SCORE, BG_WS_NORMAL_FLAG_CAPTURE_REPUTATION, BG_WS_NORMAL_MAP_COMPLETE_KILLS, BG_WS_NORMAL_WIN_KILLS, BG_WS_STATE_CAPTURES_ALLIANCE, BG_WS_STATE_CAPTURES_HORDE, BG_WS_STATE_CAPTURES_MAX, BG_WS_STATE_FLAG_ALLIANCE, BG_WS_STATE_FLAG_HORDE, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_ALLIANCE, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_HORDE, BG_WS_STATE_TIME_ENABLED, BG_WS_STATE_TIME_REMAINING, BG_WS_TIME_LIMIT, BG_WS_WEEKEND_FLAG_CAPTURE_REPUTATION, BG_WS_WEEKEND_MAP_COMPLETE_KILLS, BG_WS_WEEKEND_WIN_KILLS, BG_WS_ZONE_ID_MAIN, ObjectGuid::Clear(), BattleGround::GetBgMap(), Map::GetGraveyardManager(), GetRemainingTimeInMinutes(), BattleGround::GetTypeId(), Map::GetVariableManager(), HORDE, BattleGroundMgr::IsBgWeekend(), BattleGround::m_activeEvents, m_brutalAssaultActive, m_droppedFlagGuid, m_endTimer, m_flagCarrier, m_flagCarrierDebuffTimer, m_flagOnRespawn, m_flagsDropTimer, m_flagsTimer, m_focusedAssaultActive, m_honorEndKills, m_honorWinKills, m_lastCapturedFlagTeam, m_reputationCapture, PVP_TEAM_COUNT, BattleGround::Reset(), GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), TEAM_INVALID, TEAM_NONE, WORLD_STATE_ADD, WS_EVENT_FLAG_A, WS_EVENT_FLAG_H, WS_EVENT_SPIRITGUIDES_SPAWN, WS_GRAVEYARD_FLAGROOM_ALLIANCE, WS_GRAVEYARD_FLAGROOM_HORDE, WS_GRAVEYARD_MAIN_ALLIANCE, and WS_GRAVEYARD_MAIN_HORDE.
RespawnDroppedFlag()
void BattleGroundWS::RespawnDroppedFlag (Team team) private
Definition at line 194 of file BattleGroundWS.cpp.
References BG_WS_FLAG_ACTION_RESPAWN, ClearDroppedFlagGuid(), DEBUG_LOG, BattleGround::GetBgMap(), GetDroppedFlagGuid(), BattleGround::GetStatus(), GetTeamIndexByTeamId(), GO_JUST_DEACTIVATED, BattleGround::PlaySoundToAll(), RespawnFlagAtBase(), BattleGround::SendMessageToAll(), STATUS_IN_PROGRESS, and wsgFlagData.
Referenced by Update().
RespawnFlagAtBase()
void BattleGroundWS::RespawnFlagAtBase (Team team, bool wasCaptured) private
Definition at line 160 of file BattleGroundWS.cpp.
References BG_WS_BRUTAL_ASSAULT_TIME, BG_WS_FLAG_STATE_ON_BASE, BG_WS_SOUND_FLAGS_RESPAWNED, CHAT_MSG_BG_SYSTEM_NEUTRAL, DEBUG_LOG, BattleGround::GetBgMap(), BattleGround::GetOtherTeamIndex(), GetTeamIndexByTeamId(), Map::GetVariableManager(), LANG_BG_WS_F_PLACED, m_brutalAssaultActive, m_flagCarrierDebuffTimer, m_flagOnRespawn, m_focusedAssaultActive, BattleGround::PlaySoundToAll(), BattleGround::SendMessageToAll(), WorldStateVariableManager::SetVariable(), BattleGround::SpawnEvent(), WS_EVENT_FLAG_A, WS_EVENT_FLAG_H, and wsFlagPickedUp.
Referenced by ProcessDroppedFlagActions(), RemovePlayer(), RespawnDroppedFlag(), and Update().
SetFlagCarrier()
void BattleGroundWS::SetFlagCarrier (uint8 teamIdx, ObjectGuid guid) inline private
Definition at line 250 of file BattleGroundWS.h.
References m_flagCarrier.
Referenced by ProcessDroppedFlagActions(), and ProcessFlagPickUpFromBase().
StartingEventOpenDoors()
void BattleGroundWS::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 129 of file BattleGroundWS.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ALLIANCE, BG_EVENT_DOOR, BG_WS_ZONE_ID_MAIN, BattleGround::GetBgMap(), Map::GetGraveyardManager(), HORDE, BattleGround::OpenDoorEvent(), GraveyardManager::SetGraveYardLinkTeam(), BattleGround::SpawnEvent(), BattleGround::StartTimedAchievement(), TEAM_INVALID, WS_EVENT_FLAG_A, WS_EVENT_FLAG_H, WS_EVENT_SPIRITGUIDES_SPAWN, WS_GRAVEYARD_FLAGROOM_ALLIANCE, WS_GRAVEYARD_FLAGROOM_HORDE, WS_GRAVEYARD_MAIN_ALLIANCE, WS_GRAVEYARD_MAIN_HORDE, and WS_TIMED_ACHIEV_WARSONG_EXP.
Update()
void BattleGroundWS::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 37 of file BattleGroundWS.cpp.
References BG_WS_FLAG_STATE_ON_BASE, BG_WS_FLAG_STATE_ON_GROUND, BG_WS_FOCUSED_ASSAULT_TIME, BG_WS_SPELL_BRUTAL_ASSAULT, BG_WS_SPELL_FOCUSED_ASSAULT, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_ALLIANCE, BG_WS_STATE_FLAG_PICKED_UP_FLAG_STATE_HORDE, BG_WS_STATE_TIME_REMAINING, EndBattleGround(), BattleGround::GetBgMap(), GetFlagCarrierGuid(), GetPrematureWinner(), GetRemainingTimeInMinutes(), BattleGround::GetStatus(), GetTeamIdByTeamIndex(), Map::GetVariableManager(), IsFlagPickedUp(), m_brutalAssaultActive, m_endTimer, m_flagCarrierDebuffTimer, m_flagOnRespawn, m_flagsDropTimer, m_flagsTimer, m_focusedAssaultActive, PVP_TEAM_COUNT, RespawnDroppedFlag(), RespawnFlagAtBase(), WorldStateVariableManager::SetVariable(), STATUS_IN_PROGRESS, TRIGGERED_OLD_TRIGGERED, BattleGround::Update(), and wsFlagPickedUp.
UpdatePlayerScore()
void BattleGroundWS::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 663 of file BattleGroundWS.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_FLAG_CAPTURES, SCORE_FLAG_RETURNS, and BattleGround::UpdatePlayerScore().
Referenced by ProcessDroppedFlagActions(), and ProcessPlayerFlagScoreEvent().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 214 of file BattleGroundWS.h.
Field Documentation
m_brutalAssaultActive
bool BattleGroundWS::m_brutalAssaultActive private
Definition at line 280 of file BattleGroundWS.h.
Referenced by ProcessDroppedFlagActions(), ProcessFlagPickUpFromBase(), Reset(), RespawnFlagAtBase(), and Update().
m_droppedFlagGuid
ObjectGuid BattleGroundWS::m_droppedFlagGuid[PVP_TEAM_COUNT] private
Definition at line 271 of file BattleGroundWS.h.
Referenced by ClearDroppedFlagGuid(), GetDroppedFlagGuid(), HandleGameObjectCreate(), and Reset().
m_endTimer
uint32 BattleGroundWS::m_endTimer private
Definition at line 285 of file BattleGroundWS.h.
Referenced by GetRemainingTimeInMinutes(), Reset(), and Update().
m_flagCarrier
ObjectGuid BattleGroundWS::m_flagCarrier[PVP_TEAM_COUNT] private
Definition at line 272 of file BattleGroundWS.h.
Referenced by ClearFlagCarrier(), GetFlagCarrierGuid(), IsFlagPickedUp(), RemovePlayer(), Reset(), and SetFlagCarrier().
m_flagCarrierDebuffTimer
uint32 BattleGroundWS::m_flagCarrierDebuffTimer private
Definition at line 278 of file BattleGroundWS.h.
Referenced by Reset(), RespawnFlagAtBase(), and Update().
m_flagOnRespawn
bool BattleGroundWS::m_flagOnRespawn[PVP_TEAM_COUNT] private
Definition at line 274 of file BattleGroundWS.h.
Referenced by ProcessFlagPickUpFromBase(), ProcessPlayerFlagScoreEvent(), Reset(), RespawnFlagAtBase(), and Update().
m_flagPickupFromBaseTime
TimePoint BattleGroundWS::m_flagPickupFromBaseTime[PVP_TEAM_COUNT] private
Definition at line 275 of file BattleGroundWS.h.
Referenced by IsFlagHeldFor45Seconds(), and ProcessFlagPickUpFromBase().
m_flagsDropTimer
uint32 BattleGroundWS::m_flagsDropTimer[PVP_TEAM_COUNT] private
Definition at line 277 of file BattleGroundWS.h.
Referenced by HandlePlayerDroppedFlag(), Reset(), and Update().
m_flagsTimer
uint32 BattleGroundWS::m_flagsTimer[PVP_TEAM_COUNT] private
Definition at line 276 of file BattleGroundWS.h.
Referenced by ProcessPlayerFlagScoreEvent(), Reset(), and Update().
m_focusedAssaultActive
bool BattleGroundWS::m_focusedAssaultActive private
Definition at line 279 of file BattleGroundWS.h.
Referenced by ProcessDroppedFlagActions(), ProcessFlagPickUpFromBase(), Reset(), RespawnFlagAtBase(), and Update().
m_honorEndKills
uint32 BattleGroundWS::m_honorEndKills private
Definition at line 284 of file BattleGroundWS.h.
Referenced by EndBattleGround(), and Reset().
m_honorWinKills
uint32 BattleGroundWS::m_honorWinKills private
Definition at line 283 of file BattleGroundWS.h.
Referenced by EndBattleGround(), and Reset().
m_lastCapturedFlagTeam
Team BattleGroundWS::m_lastCapturedFlagTeam private
Definition at line 286 of file BattleGroundWS.h.
Referenced by GetPrematureWinner(), and Reset().
m_reputationCapture
uint32 BattleGroundWS::m_reputationCapture private
Definition at line 282 of file BattleGroundWS.h.
Referenced by ProcessPlayerFlagScoreEvent(), and Reset().
The documentation for this class was generated from the following files:
BattleGroundWS.h
BattleGroundWS.cpp