CMaNGOS_WoTLK: instance_black_temple Class Reference
instance_black_temple Class Reference
#include <black_temple.h>
Public Member Functions
instance_black_temple (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *player) override
void OnPlayerResurrect (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void OnCreatureEvade (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
GuidVector const & GetChannelersGuidList () const
GuidVector const & GetGeneratorGuidVector () const
GuidVector & GetShadowyConstructGuidVector ()
void GetGlaiveTargetGuidVector (GuidVector &vector) const
GuidVector & GetIllidanSpawns ()
GuidVector & GetIllidanTriggersLower ()
GuidVector & GetIllidanTriggersUpper ()
GuidVector & GetEnslavedSouls ()
void DespawnImpalingSpines ()
void RespawnChannelers ()
const char * Save () const override
void Load (const char *chrIn) override
void DoTeleportAkamaIfCan ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoOpenPreMotherDoor ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidVector m_channelersGuidVector
GuidVector m_creatureGeneratorGuidVector
GuidVector m_vGlaiveTargetGuidVector
GuidVector m_ashtongue
GuidVector m_impalingSpines
GuidVector m_shadowyConstructs
GuidVector m_soulFragments
GuidVector m_enslavedSouls
bool m_akamaIllidanSequence
GuidVector m_illidanSpawns
GuidVector m_illidanTriggersLower
GuidVector m_illidanTriggersUpper
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 102 of file black_temple.h.
Constructor & Destructor Documentation
instance_black_temple()
instance_black_temple::instance_black_temple (Map * map)
Definition at line 39 of file black_temple.cpp.
References Initialize().
Member Function Documentation
DespawnImpalingSpines()
void instance_black_temple::DespawnImpalingSpines ()
Definition at line 458 of file black_temple.cpp.
References Map::GetGameObject(), InstanceData::instance, and m_impalingSpines.
Referenced by boss_najentusAI::Reset().
DoOpenPreMotherDoor()
void instance_black_temple::DoOpenPreMotherDoor () private
Definition at line 435 of file black_temple.cpp.
References DONE, DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), EMOTE_OPEN_MOTHER_DOOR, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_PRE_SHAHRAZ_DOOR, NPC_BLACK_TEMPLE_TRIGGER, TYPE_BLOODBOIL, TYPE_GOREFIEND, TYPE_RELIQUIARY, and TYPE_SHADE.
Referenced by SetData().
DoTeleportAkamaIfCan()
void instance_black_temple::DoTeleportAkamaIfCan ()
Definition at line 445 of file black_temple.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, DONE, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), m_akamaIllidanSequence, NPC_AKAMA, UnitAI::SendAIEvent(), TYPE_COUNCIL, and TYPE_ILLIDAN.
Referenced by npc_akama_illidanAI::JustRespawned(), OnPlayerEnter(), and SetData().
GetChannelersGuidList()
GuidVector const& instance_black_temple::GetChannelersGuidList () const inline
Definition at line 122 of file black_temple.h.
References m_channelersGuidVector.
Referenced by npc_akamaAI::JustDidDialogueStep(), and npc_akamaAI::ReceiveAIEvent().
GetData()
uint32 instance_black_temple::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 427 of file black_temple.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by boss_illidan_stormrageAI::CorpseRemoved(), npc_akama_illidanAI::CorpseRemoved(), npc_akamaAI::CorpseRemoved(), boss_shade_of_akamaAI::CorpseRemoved(), DoOpenPreMotherDoor(), DoTeleportAkamaIfCan(), boss_illidan_stormrageAI::JustDied(), boss_shade_of_akamaAI::JustDied(), boss_reliquary_of_soulsAI::MoveInLineOfSight(), OnCreatureDeath(), OnCreatureRespawn(), OnPlayerResurrect(), and SetData().
GetEnslavedSouls()
GuidVector& instance_black_temple::GetEnslavedSouls () inline
Definition at line 129 of file black_temple.h.
References m_enslavedSouls.
Referenced by boss_reliquary_of_soulsAI::boss_reliquary_of_soulsAI(), and boss_reliquary_of_soulsAI::Reset().
GetGeneratorGuidVector()
GuidVector const& instance_black_temple::GetGeneratorGuidVector () const inline
Definition at line 123 of file black_temple.h.
References m_creatureGeneratorGuidVector.
Referenced by npc_akamaAI::JustDidDialogueStep(), and npc_akamaAI::ReceiveAIEvent().
GetGlaiveTargetGuidVector()
void instance_black_temple::GetGlaiveTargetGuidVector (GuidVector & vector) const inline
Definition at line 125 of file black_temple.h.
References m_vGlaiveTargetGuidVector.
Referenced by boss_illidan_stormrageAI::HandlePhaseTransition().
GetIllidanSpawns()
GuidVector& instance_black_temple::GetIllidanSpawns () inline
Definition at line 126 of file black_temple.h.
References m_illidanSpawns.
Referenced by boss_illidan_stormrageAI::ReceiveAIEvent().
GetIllidanTriggersLower()
GuidVector& instance_black_temple::GetIllidanTriggersLower () inline
Definition at line 127 of file black_temple.h.
References m_illidanTriggersLower.
Referenced by boss_illidan_stormrageAI::HandlePhaseTransition().
GetIllidanTriggersUpper()
GuidVector& instance_black_temple::GetIllidanTriggersUpper () inline
Definition at line 128 of file black_temple.h.
References m_illidanTriggersUpper.
GetShadowyConstructGuidVector()
GuidVector& instance_black_temple::GetShadowyConstructGuidVector () inline
Definition at line 124 of file black_temple.h.
References m_shadowyConstructs.
Referenced by boss_teron_gorefiendAI::DespawnSummons().
Initialize()
void instance_black_temple::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 44 of file black_temple.cpp.
References m_auiEncounter.
Referenced by instance_black_temple().
IsEncounterInProgress()
bool instance_black_temple::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 61 of file black_temple.cpp.
References IN_PROGRESS, and m_auiEncounter.
Load()
void instance_black_temple::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 474 of file black_temple.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_black_temple::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 72 of file black_temple.cpp.
References AI_EVENT_CUSTOM_B, DONE, FACTION_ASHTONGUE_FRIENDLY, Unit::GetCombatManager(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), Creature::IsTemporarySummon(), m_ashtongue, m_auiEncounter, m_channelersGuidVector, m_creatureGeneratorGuidVector, m_enslavedSouls, m_illidanSpawns, m_illidanTriggersLower, m_illidanTriggersUpper, ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, m_shadowyConstructs, m_soulFragments, m_vGlaiveTargetGuidVector, NPC_AKAMA, NPC_AKAMA_SHADE, NPC_ANGERED_SOUL_FRAGMENT, NPC_ASH_CHANNELER, NPC_ASHTONGUE_BATTLELORD, NPC_ASHTONGUE_FERAL_SPIRIT, NPC_ASHTONGUE_MYSTIC, NPC_ASHTONGUE_PRIMALIST, NPC_ASHTONGUE_STALKER, NPC_ASHTONGUE_STORMCALLER, NPC_BLACK_TEMPLE_TRIGGER, NPC_BLADE_OF_AZZINOTH, NPC_BLAZE, NPC_CAGE_TRAP_DISTURB_TRIGGER, NPC_COUNCIL_VOICE, NPC_CREATURE_GENERATOR, NPC_DEMON_FIRE, NPC_ENSLAVED_SOUL, NPC_FLAME_CRASH, NPC_FLAME_OF_AZZINOTH, NPC_GATHIOS, NPC_GLAIVE_TARGET, NPC_HUNGERING_SOUL_FRAGMENT, NPC_ILLIDAN_DOOR_TRIGGER, NPC_ILLIDAN_STORMRAGE, NPC_ILLIDAN_TARGET, NPC_ILLIDARI_COUNCIL, NPC_ILLIDARI_ELITE, NPC_LADY_MALANDE, NPC_MAIEV_SHADOWSONG, NPC_PARASITIC_SHADOWFIEND, NPC_RELIQUARY_COMBAT_TRIGGER, NPC_RELIQUARY_OF_SOULS, NPC_SHADE_OF_AKAMA, NPC_SHADOW_DEMON, NPC_SHADOWY_CONSTRUCT, NPC_SKY_STALKER, NPC_SPIRIT_OF_OLUM, NPC_SPIRIT_OF_UDALO, NPC_STORM_FURY, NPC_SUFFERING_SOUL_FRAGMENT, NPC_TERON_GOREFIEND, NPC_VENGEFUL_SPIRIT, NPC_VERAS, NPC_WIND_REAVER, NPC_WORLD_TRIGGER, NPC_ZEREVOR, Unit::setFaction(), Object::SetFlag(), CombatManager::SetLeashingDisable(), TYPE_SHADE, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
OnCreatureDeath()
void instance_black_temple::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 262 of file black_temple.cpp.
References DAY, DONE, GetData(), Object::GetEntry(), NPC_ANGERED_SOUL_FRAGMENT, NPC_HUNGERING_SOUL_FRAGMENT, NPC_SUFFERING_SOUL_FRAGMENT, Creature::SaveRespawnTime(), Creature::SetRespawnDelay(), and TYPE_RELIQUIARY.
OnCreatureEvade()
void instance_black_temple::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 248 of file black_temple.cpp.
References AI_EVENT_CUSTOM_A, Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_RELIQUARY_COMBAT_TRIGGER, and NPC_RELIQUARY_OF_SOULS.
OnCreatureRespawn()
void instance_black_temple::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 176 of file black_temple.cpp.
References DAY, DONE, FACTION_ASHTONGUE_FRIENDLY, Creature::ForcedDespawn(), GetData(), Object::GetEntry(), m_auiEncounter, NPC_ANGERED_SOUL_FRAGMENT, NPC_ASHTONGUE_BATTLELORD, NPC_ASHTONGUE_FERAL_SPIRIT, NPC_ASHTONGUE_MYSTIC, NPC_ASHTONGUE_PRIMALIST, NPC_ASHTONGUE_STALKER, NPC_ASHTONGUE_STORMCALLER, NPC_HUNGERING_SOUL_FRAGMENT, NPC_RELIQUARY_OF_SOULS, NPC_STORM_FURY, NPC_SUFFERING_SOUL_FRAGMENT, Unit::setFaction(), Creature::SetRespawnDelay(), and TYPE_SHADE.
OnObjectCreate()
void instance_black_temple::OnObjectCreate (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 202 of file black_temple.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_COUNCIL_DOOR, GO_GOREFIEND_DOOR, GO_GURTOGG_DOOR, GO_ILLIDAN_DOOR_L, GO_ILLIDAN_DOOR_R, GO_ILLIDAN_GATE, GO_IMPALING_SPINE, GO_NAJENTUS_GATE, GO_POST_SHAHRAZ_DOOR, GO_PRE_COUNCIL_DOOR, GO_PRE_SHAHRAZ_DOOR, GO_SHADE_OF_AKAMA, GO_STATE_ACTIVE, GO_SUPREMUS_DOORS, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_impalingSpines, GameObject::SetGoState(), TYPE_BLOODBOIL, TYPE_GOREFIEND, TYPE_ILLIDAN, TYPE_NAJENTUS, TYPE_RELIQUIARY, TYPE_SHADE, TYPE_SHAHRAZ, and TYPE_SUPREMUS.
OnPlayerEnter()
void instance_black_temple::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 49 of file black_temple.cpp.
References DoTeleportAkamaIfCan().
OnPlayerResurrect()
void instance_black_temple::OnPlayerResurrect (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 54 of file black_temple.cpp.
References GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, NPC_RELIQUARY_COMBAT_TRIGGER, and TYPE_RELIQUIARY.
RespawnChannelers()
void instance_black_temple::RespawnChannelers ()
Definition at line 467 of file black_temple.cpp.
References Map::GetCreature(), InstanceData::instance, and m_channelersGuidVector.
Referenced by boss_shade_of_akamaAI::JustRespawned().
Save()
const char* instance_black_temple::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 134 of file black_temple.h.
References m_strInstData.
SetData()
void instance_black_temple::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 278 of file black_temple.cpp.
References AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, ScriptedInstance::BanPlayersIfNoGm(), DAY, DONE, DoOpenPreMotherDoor(), DoScriptText(), DoTeleportAkamaIfCan(), ScriptedInstance::DoUseDoorOrButton(), EMOTE_OPEN_NAJENTUS_DOOR, FACTION_ASHTONGUE_FRIENDLY, FAIL, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_COUNCIL_DOOR, GO_GOREFIEND_DOOR, GO_GURTOGG_DOOR, GO_ILLIDAN_DOOR_L, GO_ILLIDAN_DOOR_R, GO_NAJENTUS_GATE, GO_POST_SHAHRAZ_DOOR, GO_SHADE_OF_AKAMA, GO_SUPREMUS_DOORS, IN_PROGRESS, InstanceData::instance, m_ashtongue, m_auiEncounter, m_channelersGuidVector, m_creatureGeneratorGuidVector, m_soulFragments, m_strInstData, NPC_BLACK_TEMPLE_TRIGGER, NPC_ILLIDAN_STORMRAGE, NPC_RELIQUARY_COMBAT_TRIGGER, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), script_error_log(), TYPE_BLOODBOIL, TYPE_COUNCIL, TYPE_GOREFIEND, TYPE_ILLIDAN, TYPE_NAJENTUS, TYPE_RELIQUIARY, TYPE_SHADE, TYPE_SHAHRAZ, and TYPE_SUPREMUS.
Referenced by boss_illidan_stormrageAI::Aggro(), boss_shahrazAI::Aggro(), boss_teron_gorefiendAI::Aggro(), boss_najentusAI::Aggro(), npc_akamaAI::DamageTaken(), npc_akamaAI::DoStartEvent(), boss_teron_gorefiendAI::EnterEvadeMode(), boss_illidan_stormrageAI::JustDied(), boss_shahrazAI::JustDied(), boss_shade_of_akamaAI::JustDied(), boss_teron_gorefiendAI::JustDied(), boss_najentusAI::JustDied(), boss_illidan_stormrageAI::JustReachedHome(), boss_shahrazAI::JustReachedHome(), boss_najentusAI::JustReachedHome(), boss_reliquary_of_soulsAI::ReceiveAIEvent(), boss_reliquary_of_soulsAI::StartEvent(), and boss_reliquary_of_soulsAI::SummonedCreatureJustDied().
Field Documentation
m_akamaIllidanSequence
bool instance_black_temple::m_akamaIllidanSequence private
Definition at line 152 of file black_temple.h.
Referenced by DoTeleportAkamaIfCan().
m_ashtongue
GuidVector instance_black_temple::m_ashtongue private
Definition at line 147 of file black_temple.h.
Referenced by OnCreatureCreate(), and SetData().
m_auiEncounter
uint32 instance_black_temple::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 141 of file black_temple.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnCreatureCreate(), OnCreatureRespawn(), OnObjectCreate(), and SetData().
m_channelersGuidVector
GuidVector instance_black_temple::m_channelersGuidVector private
Definition at line 144 of file black_temple.h.
Referenced by GetChannelersGuidList(), OnCreatureCreate(), RespawnChannelers(), and SetData().
m_creatureGeneratorGuidVector
GuidVector instance_black_temple::m_creatureGeneratorGuidVector private
Definition at line 145 of file black_temple.h.
Referenced by GetGeneratorGuidVector(), OnCreatureCreate(), and SetData().
m_enslavedSouls
GuidVector instance_black_temple::m_enslavedSouls private
Definition at line 151 of file black_temple.h.
Referenced by GetEnslavedSouls(), and OnCreatureCreate().
m_illidanSpawns
GuidVector instance_black_temple::m_illidanSpawns private
Definition at line 154 of file black_temple.h.
Referenced by GetIllidanSpawns(), and OnCreatureCreate().
m_illidanTriggersLower
GuidVector instance_black_temple::m_illidanTriggersLower private
Definition at line 155 of file black_temple.h.
Referenced by GetIllidanTriggersLower(), and OnCreatureCreate().
m_illidanTriggersUpper
GuidVector instance_black_temple::m_illidanTriggersUpper private
Definition at line 156 of file black_temple.h.
Referenced by GetIllidanTriggersUpper(), and OnCreatureCreate().
m_impalingSpines
GuidVector instance_black_temple::m_impalingSpines private
Definition at line 148 of file black_temple.h.
Referenced by DespawnImpalingSpines(), and OnObjectCreate().
m_shadowyConstructs
GuidVector instance_black_temple::m_shadowyConstructs private
Definition at line 149 of file black_temple.h.
Referenced by GetShadowyConstructGuidVector(), and OnCreatureCreate().
m_soulFragments
GuidVector instance_black_temple::m_soulFragments private
Definition at line 150 of file black_temple.h.
Referenced by OnCreatureCreate(), and SetData().
m_strInstData
std::string instance_black_temple::m_strInstData private
Definition at line 142 of file black_temple.h.
Referenced by Save(), and SetData().
m_vGlaiveTargetGuidVector
GuidVector instance_black_temple::m_vGlaiveTargetGuidVector private
Definition at line 146 of file black_temple.h.
Referenced by GetGlaiveTargetGuidVector(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
black_temple.h
black_temple.cpp