CMaNGOS_WoTLK: RealmList Class Reference
RealmList Class Reference
Realm Daemon
Storage object for the list of realms on the server.
#include <RealmList.h>
Public Types
typedef std::map< std::string, Realm > RealmMap
Public Member Functions
RealmList ()
~RealmList ()
void Initialize (uint32 updateInterval)
Load the realm list from the database.
void UpdateIfNeed ()
RealmMap::const_iterator begin () const
RealmMap::const_iterator end () const
uint32 size () const
Static Public Member Functions
static RealmList & Instance ()
Private Member Functions
void UpdateRealms (bool init)
void UpdateRealm (uint32 ID, const std::string &name, const std::string &address, uint32 port, uint8 icon, RealmFlags realmflags, uint8 timezone, AccountTypes allowedSecurityLevel, float popu, const std::string &builds)
Private Attributes
RealmMap m_realms
Internal map of realms.
uint32 m_UpdateInterval
time_t m_NextUpdateTime
Detailed Description
Storage object for the list of realms on the server.
Definition at line 59 of file RealmList.h.
Member Typedef Documentation
RealmMap
typedef std::map<std::string, Realm> RealmList::RealmMap
Definition at line 62 of file RealmList.h.
Constructor & Destructor Documentation
RealmList()
RealmList::RealmList ()
Definition at line 84 of file RealmList.cpp.
~RealmList()
RealmList::~RealmList () inline
Definition at line 67 of file RealmList.h.
Member Function Documentation
begin()
RealmMap::const_iterator RealmList::begin () const inline
Definition at line 73 of file RealmList.h.
References m_realms.
end()
RealmMap::const_iterator RealmList::end () const inline
Definition at line 74 of file RealmList.h.
References m_realms.
Initialize()
void RealmList::Initialize (uint32 updateInterval)
Load the realm list from the database.
Get the content of the realmlist table in the database
Definition at line 95 of file RealmList.cpp.
References m_UpdateInterval, and UpdateRealms().
Referenced by main().
Instance()
static RealmList& RealmList::Instance () static
size()
uint32 RealmList::size () const inline
Definition at line 75 of file RealmList.h.
References m_realms.
Referenced by main().
UpdateIfNeed()
void RealmList::UpdateIfNeed ()
Definition at line 142 of file RealmList.cpp.
References m_NextUpdateTime, m_realms, m_UpdateInterval, and UpdateRealms().
Referenced by AuthSocket::_HandleRealmList().
UpdateRealm()
void RealmList::UpdateRealm (uint32 ID, const std::string & name, const std::string & address, uint32 port, uint8 icon, RealmFlags realmflags, uint8 timezone, AccountTypes allowedSecurityLevel, float popu, const std::string & builds) private
Create new if not exist or update existed
Append port to IP address.
Definition at line 103 of file RealmList.cpp.
References Realm::address, Realm::allowedSecurityLevel, RealmBuildInfo::bugfix_version, RealmBuildInfo::build, FindBuildInfo(), RealmBuildInfo::hotfix_version, Realm::icon, Realm::m_ID, m_realms, RealmBuildInfo::major_version, RealmBuildInfo::minor_version, Realm::populationLevel, Realm::realmBuildInfo, Realm::realmbuilds, Realm::realmflags, StrSplit(), and Realm::timezone.
Referenced by UpdateRealms().
UpdateRealms()
void RealmList::UpdateRealms (bool init) private
Circle through results and add them to the realm map
Definition at line 157 of file RealmList.cpp.
References DETAIL_LOG, QueryResult::Fetch(), Field::GetCppString(), Field::GetUInt32(), Field::GetUInt8(), LoginDatabase, QueryResult::NextRow(), Database::Query(), REALM_FLAG_NEW_PLAYERS, REALM_FLAG_OFFLINE, REALM_FLAG_RECOMMENDED, REALM_FLAG_SPECIFYBUILD, SEC_ADMINISTRATOR, sLog, and UpdateRealm().
Referenced by Initialize(), and UpdateIfNeed().
Field Documentation
m_NextUpdateTime
time_t RealmList::m_NextUpdateTime private
Definition at line 82 of file RealmList.h.
Referenced by UpdateIfNeed().
m_realms
RealmMap RealmList::m_realms private
Internal map of realms.
Definition at line 80 of file RealmList.h.
Referenced by begin(), end(), size(), UpdateIfNeed(), and UpdateRealm().
m_UpdateInterval
uint32 RealmList::m_UpdateInterval private
Definition at line 81 of file RealmList.h.
Referenced by Initialize(), and UpdateIfNeed().
The documentation for this class was generated from the following files:
RealmList.h
RealmList.cpp