CMaNGOS_WoTLK: MirrorTimer Class Reference
MirrorTimer Class Reference
#include <Player.h>
Public Types
enum Type {
FATIGUE = 0 , BREATH = 1 , FEIGNDEATH = 2 , NUM_CLIENT_TIMERS ,
ENVIRONMENTAL = NUM_CLIENT_TIMERS , NUM_TIMERS
}
enum Status { UNCHANGED = 0 , FULL_UPDATE = 1 , STATUS_UPDATE = 2 }
Public Member Functions
MirrorTimer (Type type)
bool IsActive () const
bool IsRegenerating () const
bool IsFrozen () const
Type GetType () const
uint32 GetRemaining () const
uint32 GetDuration () const
int32 GetScale () const
uint32 GetSpellId () const
Status FetchStatus ()
void Stop ()
void Start (uint32 interval, uint32 spellId=0)
void Start (uint32 current, uint32 max, uint32 spellId)
void SetRemaining (uint32 duration)
void SetDuration (uint32 duration)
void SetFrozen (bool state)
void SetScale (int32 scale)
bool Update (uint32 diff)
Private Attributes
Type m_type
int32 m_scale
uint32 m_spellId
ShortIntervalTimer m_tracker
ShortIntervalTimer m_pulse
Status m_status
bool m_active
bool m_frozen
Detailed Description
Definition at line 478 of file Player.h.
Member Enumeration Documentation
Status
enum MirrorTimer::Status
Enumerator
UNCHANGED
FULL_UPDATE
STATUS_UPDATE
Definition at line 494 of file Player.h.
Type
enum MirrorTimer::Type
Enumerator
FATIGUE
BREATH
FEIGNDEATH
NUM_CLIENT_TIMERS
ENVIRONMENTAL
NUM_TIMERS
Definition at line 481 of file Player.h.
Constructor & Destructor Documentation
MirrorTimer()
MirrorTimer::MirrorTimer (Type type) inline
Definition at line 501 of file Player.h.
Member Function Documentation
FetchStatus()
MirrorTimer::Status MirrorTimer::FetchStatus () inline
Definition at line 150 of file Player.cpp.
References m_status, and UNCHANGED.
GetDuration()
uint32 MirrorTimer::GetDuration () const inline
Definition at line 509 of file Player.h.
References ShortIntervalTimer::GetInterval(), and m_tracker.
Referenced by Player::GetMirrorTimerMaxDuration(), SetDuration(), and SetRemaining().
GetRemaining()
uint32 MirrorTimer::GetRemaining () const inline
Definition at line 508 of file Player.h.
References ShortIntervalTimer::GetCurrent(), ShortIntervalTimer::GetInterval(), and m_tracker.
Referenced by SetRemaining().
GetScale()
int32 MirrorTimer::GetScale () const inline
Definition at line 510 of file Player.h.
References m_scale.
GetSpellId()
uint32 MirrorTimer::GetSpellId () const inline
Definition at line 511 of file Player.h.
References m_spellId.
GetType()
Type MirrorTimer::GetType () const inline
Definition at line 507 of file Player.h.
References m_type.
IsActive()
bool MirrorTimer::IsActive () const inline
Definition at line 503 of file Player.h.
References m_active.
Referenced by Player::IsMirrorTimerActive(), SetDuration(), SetFrozen(), SetRemaining(), SetScale(), and Update().
IsFrozen()
bool MirrorTimer::IsFrozen () const inline
Definition at line 505 of file Player.h.
References IsRegenerating(), and m_frozen.
Referenced by SetFrozen(), and Update().
IsRegenerating()
bool MirrorTimer::IsRegenerating () const inline
Definition at line 504 of file Player.h.
References m_scale.
Referenced by IsFrozen().
SetDuration()
void MirrorTimer::SetDuration (uint32 duration) inline
Definition at line 206 of file Player.cpp.
References FULL_UPDATE, GetDuration(), IsActive(), m_status, m_tracker, ShortIntervalTimer::SetInterval(), and Stop().
Referenced by Player::SetWaterBreathingIntervalMultiplier().
SetFrozen()
void MirrorTimer::SetFrozen (bool state) inline
Definition at line 217 of file Player.cpp.
References IsActive(), IsFrozen(), m_frozen, m_status, and STATUS_UPDATE.
Referenced by SetScale(), and Start().
SetRemaining()
void MirrorTimer::SetRemaining (uint32 duration) inline
Definition at line 195 of file Player.cpp.
References FULL_UPDATE, GetDuration(), GetRemaining(), IsActive(), m_status, m_tracker, ShortIntervalTimer::SetCurrent(), and Stop().
Referenced by Player::UpdateMirrorTimers().
SetScale()
void MirrorTimer::SetScale (int32 scale) inline
Definition at line 225 of file Player.cpp.
References FULL_UPDATE, IsActive(), m_scale, m_status, and SetFrozen().
Referenced by Player::SetEnvironmentFlags(), and Player::SetWaterBreathingIntervalMultiplier().
Start() [1/2]
void MirrorTimer::Start (uint32 current, uint32 max, uint32 spellId) inline
Definition at line 184 of file Player.cpp.
References m_active, m_tracker, ShortIntervalTimer::SetCurrent(), SetFrozen(), and Start().
Start() [2/2]
void MirrorTimer::Start (uint32 interval, uint32 spellId = 0) inline
Definition at line 168 of file Player.cpp.
References FULL_UPDATE, IN_MILLISECONDS, m_active, m_pulse, m_scale, m_spellId, m_status, m_tracker, ShortIntervalTimer::SetCurrent(), ShortIntervalTimer::SetInterval(), and Stop().
Referenced by Start(), and Player::UpdateMirrorTimers().
Stop()
void MirrorTimer::Stop () inline
Definition at line 157 of file Player.cpp.
References m_active, m_pulse, m_status, m_tracker, ShortIntervalTimer::SetCurrent(), and STATUS_UPDATE.
Referenced by SetDuration(), SetRemaining(), Start(), Update(), and Player::UpdateMirrorTimers().
Update()
bool MirrorTimer::Update (uint32 diff)
Definition at line 236 of file Player.cpp.
References ShortIntervalTimer::GetCurrent(), ShortIntervalTimer::GetInterval(), IsActive(), IsFrozen(), m_pulse, m_scale, m_tracker, ShortIntervalTimer::Passed(), ShortIntervalTimer::Reset(), ShortIntervalTimer::SetCurrent(), Stop(), and ShortIntervalTimer::Update().
Field Documentation
m_active
bool MirrorTimer::m_active private
Definition at line 539 of file Player.h.
Referenced by IsActive(), Start(), and Stop().
m_frozen
bool MirrorTimer::m_frozen private
Definition at line 540 of file Player.h.
Referenced by IsFrozen(), and SetFrozen().
m_pulse
ShortIntervalTimer MirrorTimer::m_pulse private
Definition at line 535 of file Player.h.
Referenced by Start(), Stop(), and Update().
m_scale
int32 MirrorTimer::m_scale private
Definition at line 531 of file Player.h.
Referenced by GetScale(), IsRegenerating(), SetScale(), Start(), and Update().
m_spellId
uint32 MirrorTimer::m_spellId private
Definition at line 532 of file Player.h.
Referenced by GetSpellId(), and Start().
m_status
Status MirrorTimer::m_status private
Definition at line 537 of file Player.h.
Referenced by FetchStatus(), SetDuration(), SetFrozen(), SetRemaining(), SetScale(), Start(), and Stop().
m_tracker
ShortIntervalTimer MirrorTimer::m_tracker private
Definition at line 534 of file Player.h.
Referenced by GetDuration(), GetRemaining(), SetDuration(), SetRemaining(), Start(), Stop(), and Update().
m_type
Type MirrorTimer::m_type private
Definition at line 530 of file Player.h.
Referenced by GetType().
The documentation for this class was generated from the following files:
Player.h
Player.cpp