CMaNGOS_WoTLK: FactoryHolder< T, Key > Class Template Reference
FactoryHolder< T, Key > Class Template Reference abstract
FactoryHolder holds a factory object of a specific type.
#include <FactoryHolder.h>
Public Types
typedef ObjectRegistry< FactoryHolder< T, Key >, Key > FactoryHolderRegistry
typedef MaNGOS::Singleton< FactoryHolderRegistry > FactoryHolderRepository
Public Member Functions
FactoryHolder (Key k)
virtual ~FactoryHolder ()
Key key () const
void RegisterSelf (void)
void DeregisterSelf (void)
virtual T * Create (void *data=nullptr) const =0
Abstract Factory create method.
Private Attributes
Key i_key
Detailed Description
template<class T, class Key = std::string>
class FactoryHolder< T, Key >
FactoryHolder holds a factory object of a specific type.
Definition at line 30 of file FactoryHolder.h.
Member Typedef Documentation
FactoryHolderRegistry
template<class T , class Key = std::string> typedef ObjectRegistry<FactoryHolder<T, Key >, Key > FactoryHolder< T, Key >::FactoryHolderRegistry
Definition at line 33 of file FactoryHolder.h.
FactoryHolderRepository
template<class T , class Key = std::string> typedef MaNGOS::Singleton<FactoryHolderRegistry > FactoryHolder< T, Key >::FactoryHolderRepository
Definition at line 34 of file FactoryHolder.h.
Constructor & Destructor Documentation
FactoryHolder()
template<class T , class Key = std::string> FactoryHolder< T, Key >::FactoryHolder (Key k) inline
Definition at line 36 of file FactoryHolder.h.
~FactoryHolder()
template<class T , class Key = std::string> virtual FactoryHolder< T, Key >::~FactoryHolder () inline virtual
Definition at line 37 of file FactoryHolder.h.
Member Function Documentation
Create()
template<class T , class Key = std::string> virtual T* FactoryHolder< T, Key >::Create (void * data = nullptr) const pure virtual
Abstract Factory create method.
Implemented in MovementGeneratorFactory< REAL_MOVEMENT >, and CreatureAIFactory< REAL_AI >.
Referenced by FactorySelector::GetSpecificAI(), FactorySelector::selectAI(), and FactorySelector::selectMovementGenerator().
DeregisterSelf()
template<class T , class Key = std::string> void FactoryHolder< T, Key >::DeregisterSelf (void) inline
Definition at line 41 of file FactoryHolder.h.
References MaNGOS::Singleton< T, ThreadingModel, CreatePolicy, LifeTimePolicy >::Instance().
key()
template<class T , class Key = std::string> Key FactoryHolder< T, Key >::key () const inline
Definition at line 38 of file FactoryHolder.h.
References FactoryHolder< T, Key >::i_key.
Referenced by FactorySelector::selectAI().
RegisterSelf()
template<class T , class Key = std::string> void FactoryHolder< T, Key >::RegisterSelf (void) inline
Definition at line 40 of file FactoryHolder.h.
References FactoryHolder< T, Key >::i_key, and MaNGOS::Singleton< T, ThreadingModel, CreatePolicy, LifeTimePolicy >::Instance().
Field Documentation
i_key
template<class T , class Key = std::string> Key FactoryHolder< T, Key >::i_key private
Definition at line 46 of file FactoryHolder.h.
Referenced by FactoryHolder< T, Key >::key(), and FactoryHolder< T, Key >::RegisterSelf().
The documentation for this class was generated from the following file:
FactoryHolder.h