CMaNGOS_WoTLK: Battlefield Class Reference
Battlefield Class Reference
#include <Battlefield.h>
Public Member Functions
Battlefield ()
virtual void HandlePlayerEnterZone (Player *, bool) override
Function that adds a player to the players of the affected battlefield zones.
virtual void HandlePlayerLeaveZone (Player *, bool) override
Function that removes a player from the players of the affected battlefield zones.
void HandleQueueInviteResponse (Player *, bool)
Function that handles player invite response.
void HandleWarInviteResponse (Player *, bool)
Function that handles player teleport response.
void HandleExitRequest (Player *)
Function that handles player queue exit request.
void HandlePlayerAFK (Player *)
Function that handles the AFK status.
void HandlePlayerLoggedIn (Player *)
Function that handles the player which just logged in.
virtual void StartBattle (Team)
Function that starts battlefield battle.
virtual void EndBattle (Team)
Function that ends battlefield battle.
virtual void Update (uint32) override
Battlefield update function.
virtual void SendBattlefieldTimerUpdate ()
Team GetDefender () const
Team GetAttacker () const
void RemovePlayerFromRaid (ObjectGuid playerGuid)
Function that removes a player from a raid group.
void HandleBattlefieldGroupDisband (Player *player)
Function that handles the disband of the group.
bool HasPlayer (ObjectGuid playerGuid)
Function that checks if the battlefield has the player.
bool CanDeleteBattlefieldGroup (Group *group)
Function that checks if a battlefield group can be deleted.
BattlefieldStatus GetBattlefieldStatus () const
void SetTimer (uint32 value)
uint32 GetTimer () const
uint32 GetBattleDuration () const
uint32 GetStartInviteDelay () const
uint32 GetCooldownDuration () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetBattlefieldId () const
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectCreate (GameObject *)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleGameObjectUse (Player *, GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Protected Member Functions
virtual void Reset ()
virtual void InitPlayerBattlefieldData (Player *)
Function that initializes the player data.
virtual void OnBattlefieldPlayersUpdate ()
virtual void UpdatePlayerBattleResponse (Player *)
virtual void UpdatePlayerExitRequest (Player *)
virtual void UpdatePlayerGroupDisband (Player *)
virtual void RewardPlayersOnBattleEnd (Team)
virtual void SetupPlayerPosition (Player *)
virtual void KickBattlefieldPlayer (Player *)
void InvitePlayerToQueue (Player *)
Function that handles player invite to queue.
void InitPlayersBeforeBattle ()
Function that initializes all players before the battle starts.
void UpdateBattlefieldPlayers ()
Function that refresh all battlefield players.
void SendZoneWarning (WorldObject *, int32, uint32 soundId=0)
Function that sends a zone wide warning to all players.
void QuestCreditTeam (uint32, Team, WorldObject *)
Function that rewards the given team players.
bool CanAddPlayerToRaid (Player *)
Function that checks if the player can be added to a raid group.
bool IsTeamFull (PvpTeamIndex)
Function that checks if a team is already full.
Group * GetFreeRaid (PvpTeamIndex)
Function that returns a non full group for a specified team index.
Group * GetGroupFor (ObjectGuid)
Function that returns the group of a specified player.
uint32 GetPlayerCountByTeam (PvpTeamIndex)
Function that returns the number of players depending on the team.
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes
BattlefieldPlayerDataMap m_activePlayers
std::set< Group * > m_battlefieldRaids [PVP_TEAM_COUNT]
std::set< ObjectGuid > m_queuedPlayers [PVP_TEAM_COUNT]
std::map< ObjectGuid, time_t > m_invitedPlayers [PVP_TEAM_COUNT]
uint32 m_battleFieldId
uint32 m_zoneId
uint32 m_queueUpdateTimer
uint32 m_playersUpdateTimer
BattlefieldStatus m_status
Team m_zoneOwner
uint32 m_timer
uint32 m_battleDuration
uint32 m_startInviteDelay
uint32 m_cooldownDuration
uint32 m_maxPlayersPerTeam
time_t m_startTime
bool m_playersInvited
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 141 of file Battlefield.h.
Constructor & Destructor Documentation
Battlefield()
Battlefield::Battlefield ()
Definition at line 31 of file Battlefield.cpp.
References CONFIG_UINT32_BATTLEFIELD_BATTLE_DURATION, CONFIG_UINT32_BATTLEFIELD_COOLDOWN_DURATION, CONFIG_UINT32_BATTLEFIELD_MAX_PLAYERS_PER_TEAM, IN_MILLISECONDS, m_battleDuration, m_cooldownDuration, OutdoorPvP::m_isBattlefield, m_maxPlayersPerTeam, m_startInviteDelay, MINUTE, and sWorld.
Member Function Documentation
CanAddPlayerToRaid()
bool Battlefield::CanAddPlayerToRaid (Player * player) protected
Function that checks if the player can be added to a raid group.
Parameters
player to be added to raid
Definition at line 477 of file Battlefield.cpp.
References Group::AddMember(), Group::Create(), DEBUG_LOG, GetFreeRaid(), Player::GetGroup(), Object::GetGuidStr(), Group::GetGuidStr(), Group::GetMemberGroup(), WorldObject::GetName(), Object::GetObjectGuid(), Player::GetTeam(), GetTeamIndexByTeamId(), Object::IsInWorld(), Group::IsMember(), IsTeamFull(), m_battlefieldRaids, Group::SetBattlefieldGroup(), Player::SetBattleRaid(), and sLog.
Referenced by HandleWarInviteResponse().
CanDeleteBattlefieldGroup()
bool Battlefield::CanDeleteBattlefieldGroup (Group * group)
Function that checks if a battlefield group can be deleted.
Parameters
group to be deleted
Definition at line 584 of file Battlefield.cpp.
References m_battlefieldRaids.
EndBattle()
void Battlefield::EndBattle (Team winner) virtual
Function that ends battlefield battle.
Parameters
winner team
reference object
Reimplemented in BattlefieldWG.
Definition at line 287 of file Battlefield.cpp.
References ALLIANCE, BF_STATUS_COOLDOWN, DEBUG_LOG, m_battlefieldRaids, m_cooldownDuration, m_playersInvited, m_status, m_timer, m_zoneOwner, RewardPlayersOnBattleEnd(), sLog, and TEAM_NONE.
Referenced by BattlefieldWG::EndBattle(), and Update().
GetAttacker()
Team Battlefield::GetAttacker () const inline
Definition at line 172 of file Battlefield.h.
References ALLIANCE, HORDE, m_zoneOwner, and TEAM_NONE.
Referenced by BattlefieldWG::GetBattlefieldReady(), BattlefieldWG::HandleCapturePointEvent(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleDestructibleBuildingEvent(), BattlefieldWG::HandleGameObjectCreate(), BattlefieldWG::HandlePlayerEnterZone(), and BattlefieldWG::Reset().
GetBattleDuration()
uint32 Battlefield::GetBattleDuration () const inline
Definition at line 188 of file Battlefield.h.
References m_battleDuration.
GetBattlefieldId()
uint32 Battlefield::GetBattlefieldId () const inline
Definition at line 194 of file Battlefield.h.
References m_battleFieldId.
GetBattlefieldStatus()
BattlefieldStatus Battlefield::GetBattlefieldStatus () const inline
Definition at line 181 of file Battlefield.h.
References m_status.
Referenced by BattlefieldWG::FillInitialWorldStates(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleEvent(), BattlefieldWG::HandleGameObjectCreate(), BattlefieldWG::HandleGameObjectUse(), HandlePlayerAFK(), HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerKillInsideArea(), HandleQueueInviteResponse(), HandleWarInviteResponse(), BattlefieldWG::InitPlayerBattlefieldData(), BattlefieldWG::IsConditionFulfilled(), spell_teleport_lake_wintergrasp::OnEffectExecute(), BattlefieldWG::SendBattlefieldTimerUpdate(), BattlefieldWG::SendUpdateGeneralWorldStates(), BattlefieldWG::Update(), Update(), npc_spirit_guide_wintergraspAI::UpdateAI(), and go_vehicle_teleporter::UpdateAI().
GetCooldownDuration()
uint32 Battlefield::GetCooldownDuration () const inline
Definition at line 190 of file Battlefield.h.
References m_cooldownDuration.
GetDefender()
Team Battlefield::GetDefender () const inline
Definition at line 171 of file Battlefield.h.
References m_zoneOwner.
Referenced by BattlefieldWG::CleanupBattlefield(), BattlefieldWG::FillInitialWorldStates(), BattlefieldWG::GetBattlefieldReady(), BattlefieldWG::HandleCapturePointEvent(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleDestructibleBuildingEvent(), BattlefieldWG::HandleEvent(), BattlefieldWG::HandleGameObjectCreate(), BattlefieldWG::HandleGameObjectUse(), BattlefieldWG::HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerKillInsideArea(), BattlefieldWG::IsConditionFulfilled(), spell_teleport_lake_wintergrasp::OnEffectExecute(), BattlefieldWG::Reset(), BattlefieldWG::SendUpdateGeneralWorldStates(), BattlefieldWG::SetupPlayerPosition(), BattlefieldWG::StartBattle(), BattlefieldWG::Update(), and go_vehicle_teleporter::UpdateAI().
GetFreeRaid()
Group * Battlefield::GetFreeRaid (PvpTeamIndex teamIdx) protected
Function that returns a non full group for a specified team index.
Parameters
team index
Definition at line 442 of file Battlefield.cpp.
References m_battlefieldRaids.
Referenced by CanAddPlayerToRaid().
GetGroupFor()
Group * Battlefield::GetGroupFor (ObjectGuid playerGuid) protected
Function that returns the group of a specified player.
Parameters
player guid
Definition at line 458 of file Battlefield.cpp.
References m_battlefieldRaids.
Referenced by HandlePlayerLoggedIn(), HasPlayer(), and RemovePlayerFromRaid().
GetMaxPlayersPerTeam()
uint32 Battlefield::GetMaxPlayersPerTeam () const inline
Definition at line 191 of file Battlefield.h.
References m_maxPlayersPerTeam.
GetPlayerCountByTeam()
uint32 Battlefield::GetPlayerCountByTeam (PvpTeamIndex teamIdx) protected
Function that returns the number of players depending on the team.
Parameters
team index
Definition at line 560 of file Battlefield.cpp.
References m_battlefieldRaids.
Referenced by IsTeamFull(), and BattlefieldWG::UpdateTenacities().
GetStartInviteDelay()
uint32 Battlefield::GetStartInviteDelay () const inline
Definition at line 189 of file Battlefield.h.
References m_startInviteDelay.
Referenced by spell_teleport_lake_wintergrasp::OnEffectExecute().
GetTimer()
uint32 Battlefield::GetTimer () const inline
Definition at line 185 of file Battlefield.h.
References m_timer.
Referenced by BattlefieldWG::CheckAchievementCriteriaMeet(), BattlefieldWG::HandleDestructibleBuildingEvent(), and spell_teleport_lake_wintergrasp::OnEffectExecute().
HandleBattlefieldGroupDisband()
void Battlefield::HandleBattlefieldGroupDisband (Player * player)
Function that handles the disband of the group.
Parameters
player that is affected by the group disband
Definition at line 606 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_UNACCEPTED_REMOVE_DELAY, Object::GetObjectGuid(), Player::GetSession(), m_activePlayers, m_battleFieldId, WorldSession::SendBattlefieldLeaveMessage(), and UpdatePlayerGroupDisband().
HandleExitRequest()
void Battlefield::HandleExitRequest (Player * player)
Function that handles player queue exit request.
Parameters
player to exit queue
Definition at line 743 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_UNACCEPTED_REMOVE_DELAY, Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), GetTeamIndexByTeamId(), HasPlayer(), m_activePlayers, m_battleFieldId, m_queuedPlayers, RemovePlayerFromRaid(), WorldSession::SendBattlefieldLeaveMessage(), and UpdatePlayerExitRequest().
HandlePlayerAFK()
void Battlefield::HandlePlayerAFK (Player * player)
Function that handles the AFK status.
Parameters
player to be punished
Definition at line 119 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_STATUS_IN_PROGRESS, GetBattlefieldStatus(), Object::GetObjectGuid(), Player::GetSession(), HasPlayer(), KickBattlefieldPlayer(), m_battleFieldId, RemovePlayerFromRaid(), and WorldSession::SendBattlefieldLeaveMessage().
HandlePlayerEnterZone()
void Battlefield::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Function that adds a player to the players of the affected battlefield zones.
Parameters
player to add
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Reimplemented in BattlefieldWG.
Definition at line 50 of file Battlefield.cpp.
References BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, BF_TIME_TO_ACCEPT, GetBattlefieldStatus(), Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), GetTeamIndexByTeamId(), OutdoorPvP::HandlePlayerEnterZone(), HasPlayer(), InitPlayerBattlefieldData(), InvitePlayerToQueue(), m_activePlayers, m_battleFieldId, m_invitedPlayers, m_startInviteDelay, m_startTime, m_timer, m_zoneId, WorldSession::SendBattlefieldWarInvite(), and SetupPlayerPosition().
Referenced by BattlefieldWG::HandlePlayerEnterZone().
HandlePlayerLeaveZone()
void Battlefield::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected battlefield zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Reimplemented in BattlefieldWG.
Definition at line 85 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_UNACCEPTED_REMOVE_DELAY, Object::GetObjectGuid(), Player::GetSession(), OutdoorPvP::HandlePlayerLeaveZone(), HasPlayer(), m_activePlayers, m_battleFieldId, and WorldSession::SendBattlefieldLeaveMessage().
Referenced by BattlefieldWG::HandlePlayerLeaveZone().
HandlePlayerLoggedIn()
void Battlefield::HandlePlayerLoggedIn (Player * player)
Function that handles the player which just logged in.
Parameters
player
Definition at line 134 of file Battlefield.cpp.
References GetGroupFor(), Object::GetObjectGuid(), and Player::SetBattleRaid().
HandleQueueInviteResponse()
void Battlefield::HandleQueueInviteResponse (Player * player, bool accepted)
Function that handles player invite response.
Parameters
player that responded
whether the player has accepted or not
Definition at line 654 of file Battlefield.cpp.
References BF_STATUS_IN_PROGRESS, BF_TIME_TO_ACCEPT, GetBattlefieldStatus(), Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), GetTeamIndexByTeamId(), HasPlayer(), IsTeamFull(), m_battleFieldId, m_invitedPlayers, m_queuedPlayers, m_zoneId, WorldSession::SendBattlefieldQueueResponse(), and WorldSession::SendBattlefieldWarInvite().
HandleWarInviteResponse()
void Battlefield::HandleWarInviteResponse (Player * player, bool accepted)
Function that handles player teleport response.
Parameters
player that responded
whether the player has accepted or not
Definition at line 689 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_STATUS_IN_PROGRESS, BF_UNACCEPTED_REMOVE_DELAY, CanAddPlayerToRaid(), DEBUG_LOG, GetBattlefieldStatus(), Object::GetGuidStr(), Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), GetTeamIndexByTeamId(), WorldObject::GetZoneId(), HasPlayer(), InitPlayerBattlefieldData(), m_activePlayers, m_battleFieldId, m_invitedPlayers, m_zoneId, WorldSession::SendBattlefieldEnteredResponse(), WorldSession::SendBattlefieldLeaveMessage(), and UpdatePlayerBattleResponse().
HasPlayer()
bool Battlefield::HasPlayer (ObjectGuid playerGuid)
Function that checks if the battlefield has the player.
Parameters
player guid to be removed
Definition at line 550 of file Battlefield.cpp.
References GetGroupFor().
Referenced by HandleExitRequest(), HandlePlayerAFK(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HandleQueueInviteResponse(), HandleWarInviteResponse(), InvitePlayerToQueue(), QuestCreditTeam(), and UpdateBattlefieldPlayers().
InitPlayerBattlefieldData()
void Battlefield::InitPlayerBattlefieldData (Player * player) protected virtual
Function that initializes the player data.
Parameters
player to load
Reimplemented in BattlefieldWG.
Definition at line 109 of file Battlefield.cpp.
References Object::GetObjectGuid(), and m_activePlayers.
Referenced by HandlePlayerEnterZone(), HandleWarInviteResponse(), and InitPlayersBeforeBattle().
InitPlayersBeforeBattle()
void Battlefield::InitPlayersBeforeBattle () protected
Function that initializes all players before the battle starts.
Definition at line 146 of file Battlefield.cpp.
References InitPlayerBattlefieldData(), m_activePlayers, OutdoorPvP::m_zonePlayers, and sObjectMgr.
Referenced by StartBattle().
InvitePlayerToQueue()
void Battlefield::InvitePlayerToQueue (Player * player) protected
Function that handles player invite to queue.
Parameters
player to be invited
Definition at line 629 of file Battlefield.cpp.
References Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), GetTeamIndexByTeamId(), HasPlayer(), IsTeamFull(), m_battleFieldId, m_invitedPlayers, m_queuedPlayers, m_zoneId, WorldSession::SendBattlefieldQueueInvite(), and WorldSession::SendBattlefieldQueueResponse().
Referenced by HandlePlayerEnterZone(), and Update().
IsTeamFull()
bool Battlefield::IsTeamFull (PvpTeamIndex teamIdx) protected
Function that checks if a team is already full.
Parameters
team index
Definition at line 574 of file Battlefield.cpp.
References GetPlayerCountByTeam(), m_invitedPlayers, m_maxPlayersPerTeam, and m_queuedPlayers.
Referenced by CanAddPlayerToRaid(), HandleQueueInviteResponse(), and InvitePlayerToQueue().
KickBattlefieldPlayer()
virtual void Battlefield::KickBattlefieldPlayer (Player *) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 222 of file Battlefield.h.
Referenced by HandlePlayerAFK(), and UpdateBattlefieldPlayers().
OnBattlefieldPlayersUpdate()
virtual void Battlefield::OnBattlefieldPlayersUpdate () inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 204 of file Battlefield.h.
Referenced by UpdateBattlefieldPlayers().
QuestCreditTeam()
void Battlefield::QuestCreditTeam (uint32 credit, Team team, WorldObject * source) protected
Function that rewards the given team players.
Parameters
kill credit
team
source object
Definition at line 414 of file Battlefield.cpp.
References Player::GetTeam(), HasPlayer(), Player::IsAtGroupRewardDistance(), Player::KilledMonsterCredit(), OutdoorPvP::m_zonePlayers, and sObjectMgr.
Referenced by BattlefieldWG::HandleDestructibleBuildingEvent().
RemovePlayerFromRaid()
void Battlefield::RemovePlayerFromRaid (ObjectGuid playerGuid)
Function that removes a player from a raid group.
Parameters
player guid to be removed
Definition at line 536 of file Battlefield.cpp.
References GetGroupFor().
Referenced by HandleExitRequest(), HandlePlayerAFK(), and UpdateBattlefieldPlayers().
Reset()
virtual void Battlefield::Reset () inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 198 of file Battlefield.h.
RewardPlayersOnBattleEnd()
virtual void Battlefield::RewardPlayersOnBattleEnd (Team) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 216 of file Battlefield.h.
Referenced by EndBattle().
SendBattlefieldTimerUpdate()
virtual void Battlefield::SendBattlefieldTimerUpdate () inline virtual
Reimplemented in BattlefieldWG.
Definition at line 168 of file Battlefield.h.
Referenced by Update().
SendZoneWarning()
void Battlefield::SendZoneWarning (WorldObject * source, int32 textEntry, uint32 soundId = 0) protected
Function that sends a zone wide warning to all players.
Parameters
source object
text entry
sound id
Definition at line 787 of file Battlefield.cpp.
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), WorldObject::GetZoneId(), m_zoneId, OutdoorPvP::m_zonePlayers, WorldObject::MonsterTextEmote(), PLAY_TARGET, WorldObject::PlayDirectSound(), and sObjectMgr.
Referenced by BattlefieldWG::SendWintergraspWarning().
SetTimer()
void Battlefield::SetTimer (uint32 value) inline
Definition at line 184 of file Battlefield.h.
References m_timer.
Referenced by BattlefieldWG::HandleDestructibleBuildingEvent(), and BattlefieldWG::Reset().
SetupPlayerPosition()
virtual void Battlefield::SetupPlayerPosition (Player *) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 219 of file Battlefield.h.
Referenced by HandlePlayerEnterZone().
StartBattle()
void Battlefield::StartBattle (Team defender) virtual
Function that starts battlefield battle.
Parameters
defender team
Reimplemented in BattlefieldWG.
Definition at line 205 of file Battlefield.cpp.
References ALLIANCE, BATTLEFIELD_LEAVE_REASON_EXITED, BF_STATUS_IN_PROGRESS, BF_TIME_TO_ACCEPT, BF_UNACCEPTED_REMOVE_DELAY, DEBUG_LOG, Player::GetSession(), InitPlayersBeforeBattle(), m_activePlayers, m_battleDuration, m_battleFieldId, m_battlefieldRaids, m_invitedPlayers, m_queuedPlayers, m_startTime, m_status, m_timer, m_zoneId, m_zoneOwner, OutdoorPvP::m_zonePlayers, PVP_TEAM_COUNT, WorldSession::SendBattlefieldLeaveMessage(), WorldSession::SendBattlefieldWarInvite(), OutdoorPvP::SendRemoveWorldStates(), and sObjectMgr.
Referenced by BattlefieldWG::StartBattle(), and Update().
Update()
void Battlefield::Update (uint32 diff) override virtual
Battlefield update function.
Reimplemented from OutdoorPvP.
Reimplemented in BattlefieldWG.
Definition at line 322 of file Battlefield.cpp.
References BATTLEFIELD_LEAVE_REASON_EXITED, BF_STATUS_COOLDOWN, BF_STATUS_IN_PROGRESS, EndBattle(), GetBattlefieldStatus(), InvitePlayerToQueue(), m_battleFieldId, m_invitedPlayers, m_playersInvited, m_playersUpdateTimer, m_queuedPlayers, m_queueUpdateTimer, m_startInviteDelay, m_status, m_timer, m_zoneOwner, OutdoorPvP::m_zonePlayers, SendBattlefieldTimerUpdate(), sObjectMgr, StartBattle(), and UpdateBattlefieldPlayers().
Referenced by BattlefieldWG::Update().
UpdateBattlefieldPlayers()
void Battlefield::UpdateBattlefieldPlayers () protected
Function that refresh all battlefield players.
Definition at line 169 of file Battlefield.cpp.
References HasPlayer(), KickBattlefieldPlayer(), m_activePlayers, OnBattlefieldPlayersUpdate(), RemovePlayerFromRaid(), and sObjectMgr.
Referenced by Update().
UpdatePlayerBattleResponse()
virtual void Battlefield::UpdatePlayerBattleResponse (Player *) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 207 of file Battlefield.h.
Referenced by HandleWarInviteResponse().
UpdatePlayerExitRequest()
virtual void Battlefield::UpdatePlayerExitRequest (Player *) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 210 of file Battlefield.h.
Referenced by HandleExitRequest().
UpdatePlayerGroupDisband()
virtual void Battlefield::UpdatePlayerGroupDisband (Player *) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 213 of file Battlefield.h.
Referenced by HandleBattlefieldGroupDisband().
Field Documentation
m_activePlayers
BattlefieldPlayerDataMap Battlefield::m_activePlayers protected
Definition at line 247 of file Battlefield.h.
Referenced by BattlefieldWG::GetPlayerRank(), HandleBattlefieldGroupDisband(), HandleExitRequest(), HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerKillInsideArea(), HandlePlayerLeaveZone(), HandleWarInviteResponse(), InitPlayerBattlefieldData(), BattlefieldWG::InitPlayerBattlefieldData(), InitPlayersBeforeBattle(), StartBattle(), UpdateBattlefieldPlayers(), and BattlefieldWG::UpdatePlayerScore().
m_battleDuration
uint32 Battlefield::m_battleDuration protected
Definition at line 262 of file Battlefield.h.
Referenced by Battlefield(), GetBattleDuration(), BattlefieldWG::GetBattlefieldReady(), and StartBattle().
m_battleFieldId
uint32 Battlefield::m_battleFieldId protected
Definition at line 253 of file Battlefield.h.
Referenced by BattlefieldWG::BattlefieldWG(), GetBattlefieldId(), HandleBattlefieldGroupDisband(), HandleExitRequest(), HandlePlayerAFK(), HandlePlayerEnterZone(), HandlePlayerLeaveZone(), HandleQueueInviteResponse(), HandleWarInviteResponse(), InvitePlayerToQueue(), StartBattle(), and Update().
m_battlefieldRaids
std::set<Group*> Battlefield::m_battlefieldRaids[PVP_TEAM_COUNT] protected
Definition at line 249 of file Battlefield.h.
Referenced by CanAddPlayerToRaid(), CanDeleteBattlefieldGroup(), EndBattle(), GetFreeRaid(), GetGroupFor(), GetPlayerCountByTeam(), and StartBattle().
m_cooldownDuration
uint32 Battlefield::m_cooldownDuration protected
Definition at line 264 of file Battlefield.h.
Referenced by Battlefield(), EndBattle(), GetCooldownDuration(), and BattlefieldWG::Reset().
m_invitedPlayers
std::map<ObjectGuid, time_t> Battlefield::m_invitedPlayers[PVP_TEAM_COUNT] protected
Definition at line 251 of file Battlefield.h.
Referenced by HandlePlayerEnterZone(), HandleQueueInviteResponse(), HandleWarInviteResponse(), InvitePlayerToQueue(), IsTeamFull(), StartBattle(), and Update().
m_maxPlayersPerTeam
uint32 Battlefield::m_maxPlayersPerTeam protected
Definition at line 265 of file Battlefield.h.
Referenced by Battlefield(), GetMaxPlayersPerTeam(), and IsTeamFull().
m_playersInvited
bool Battlefield::m_playersInvited protected
Definition at line 269 of file Battlefield.h.
Referenced by EndBattle(), BattlefieldWG::Reset(), and Update().
m_playersUpdateTimer
uint32 Battlefield::m_playersUpdateTimer protected
Definition at line 256 of file Battlefield.h.
Referenced by Update().
m_queuedPlayers
std::set<ObjectGuid> Battlefield::m_queuedPlayers[PVP_TEAM_COUNT] protected
Definition at line 250 of file Battlefield.h.
Referenced by HandleExitRequest(), HandleQueueInviteResponse(), InvitePlayerToQueue(), IsTeamFull(), StartBattle(), and Update().
m_queueUpdateTimer
uint32 Battlefield::m_queueUpdateTimer protected
Definition at line 255 of file Battlefield.h.
Referenced by Update().
m_startInviteDelay
uint32 Battlefield::m_startInviteDelay protected
Definition at line 263 of file Battlefield.h.
Referenced by Battlefield(), GetStartInviteDelay(), HandlePlayerEnterZone(), and Update().
m_startTime
time_t Battlefield::m_startTime protected
Definition at line 267 of file Battlefield.h.
Referenced by HandlePlayerEnterZone(), BattlefieldWG::Reset(), and StartBattle().
m_status
BattlefieldStatus Battlefield::m_status protected
Definition at line 258 of file Battlefield.h.
Referenced by EndBattle(), GetBattlefieldStatus(), BattlefieldWG::Reset(), StartBattle(), and Update().
m_timer
uint32 Battlefield::m_timer protected
Definition at line 260 of file Battlefield.h.
Referenced by EndBattle(), BattlefieldWG::FillInitialWorldStates(), GetTimer(), HandlePlayerEnterZone(), BattlefieldWG::SendBattlefieldTimerUpdate(), BattlefieldWG::SendUpdateGeneralWorldStates(), SetTimer(), StartBattle(), BattlefieldWG::Update(), and Update().
m_zoneId
uint32 Battlefield::m_zoneId protected
Definition at line 254 of file Battlefield.h.
Referenced by BattlefieldWG::BattlefieldWG(), HandlePlayerEnterZone(), HandleQueueInviteResponse(), HandleWarInviteResponse(), InvitePlayerToQueue(), SendZoneWarning(), and StartBattle().
m_zoneOwner
Team Battlefield::m_zoneOwner protected
Definition at line 259 of file Battlefield.h.
Referenced by BattlefieldWG::BattlefieldWG(), EndBattle(), GetAttacker(), GetDefender(), StartBattle(), and Update().
The documentation for this class was generated from the following files:
Battlefield.h
Battlefield.cpp