CMaNGOS_WoTLK: SqlConnection Class Reference
SqlConnection Class Reference abstract
#include <Database.h>
Data Structures
class Lock
Public Member Functions
virtual ~SqlConnection ()
virtual bool Initialize (const char *infoString)=0
virtual QueryResult * Query (const char *sql)=0
virtual QueryNamedResult * QueryNamed (const char *sql)=0
virtual bool Execute (const char *sql)=0
virtual unsigned long escape_string (char *to, const char *from, unsigned long length)
virtual bool BeginTransaction ()
virtual bool CommitTransaction ()
virtual bool RollbackTransaction ()
bool ExecuteStmt (int nIndex, const SqlStmtParameters &id)
Database & DB () const
Protected Member Functions
SqlConnection (Database &db)
virtual SqlPreparedStatement * CreateStatement (const std::string &fmt)
SqlPreparedStatement * GetStmt (uint32 nIndex)
void FreePreparedStatements ()
Protected Attributes
Database & m_db
Private Types
typedef std::vector< SqlPreparedStatement * > StmtHolder
Private Attributes
std::recursive_mutex m_mutex
StmtHolder m_holder
Detailed Description
Definition at line 41 of file Database.h.
Member Typedef Documentation
StmtHolder
typedef std::vector<SqlPreparedStatement* > SqlConnection::StmtHolder private
Definition at line 98 of file Database.h.
Constructor & Destructor Documentation
~SqlConnection()
virtual SqlConnection::~SqlConnection () inline virtual
Definition at line 44 of file Database.h.
SqlConnection()
SqlConnection::SqlConnection (Database & db) inline protected
Definition at line 84 of file Database.h.
Member Function Documentation
BeginTransaction()
virtual bool SqlConnection::BeginTransaction () inline virtual
Reimplemented in PostgreSQLConnection, and MySQLConnection.
Definition at line 59 of file Database.h.
Referenced by SqlTransaction::Execute().
CommitTransaction()
virtual bool SqlConnection::CommitTransaction () inline virtual
Reimplemented in PostgreSQLConnection, and MySQLConnection.
Definition at line 60 of file Database.h.
Referenced by SqlTransaction::Execute().
CreateStatement()
SqlPreparedStatement * SqlConnection::CreateStatement (const std::string & fmt) protected virtual
Reimplemented in MySQLConnection.
Definition at line 33 of file Database.cpp.
Referenced by GetStmt().
DB()
Database& SqlConnection::DB () const inline
Definition at line 81 of file Database.h.
References m_db.
Referenced by SqlPlainPreparedStatement::DataToString().
escape_string()
virtual unsigned long SqlConnection::escape_string (char * to, const char * from, unsigned long length) inline virtual
Reimplemented in PostgreSQLConnection, and MySQLConnection.
Definition at line 56 of file Database.h.
Execute()
virtual bool SqlConnection::Execute (const char * sql) pure virtual
Implemented in PostgreSQLConnection, and MySQLConnection.
Referenced by Database::DirectExecute(), SqlPlainPreparedStatement::execute(), and SqlPlainRequest::Execute().
ExecuteStmt()
bool SqlConnection::ExecuteStmt (int nIndex, const SqlStmtParameters & id)
Definition at line 81 of file Database.cpp.
References SqlPreparedStatement::bind(), SqlPreparedStatement::execute(), and GetStmt().
Referenced by Database::DirectExecuteStmt(), and SqlPreparedRequest::Execute().
FreePreparedStatements()
void SqlConnection::FreePreparedStatements () protected
Definition at line 38 of file Database.cpp.
References m_holder.
Referenced by MySQLConnection::~MySQLConnection().
GetStmt()
SqlPreparedStatement * SqlConnection::GetStmt (uint32 nIndex) protected
Definition at line 49 of file Database.cpp.
References CreateStatement(), Database::GetStmtString(), m_db, m_holder, MANGOS_ASSERT, and SqlPreparedStatement::prepare().
Referenced by ExecuteStmt().
Initialize()
virtual bool SqlConnection::Initialize (const char * infoString) pure virtual
Implemented in PostgreSQLConnection, and MySQLConnection.
Referenced by Database::Initialize().
Query()
virtual QueryResult* SqlConnection::Query (const char * sql) pure virtual
Implemented in PostgreSQLConnection, and MySQLConnection.
Referenced by SqlQuery::Execute(), SqlQueryHolderEx::Execute(), Database::Ping(), and Database::Query().
QueryNamed()
virtual QueryNamedResult* SqlConnection::QueryNamed (const char * sql) pure virtual
Implemented in PostgreSQLConnection, and MySQLConnection.
Referenced by Database::QueryNamed().
RollbackTransaction()
virtual bool SqlConnection::RollbackTransaction () inline virtual
Reimplemented in PostgreSQLConnection, and MySQLConnection.
Definition at line 62 of file Database.h.
Referenced by SqlTransaction::Execute().
Field Documentation
m_db
Database& SqlConnection::m_db protected
Definition at line 90 of file Database.h.
Referenced by DB(), and GetStmt().
m_holder
StmtHolder SqlConnection::m_holder private
Definition at line 99 of file Database.h.
Referenced by FreePreparedStatements(), and GetStmt().
m_mutex
std::recursive_mutex SqlConnection::m_mutex private
Definition at line 96 of file Database.h.
Referenced by SqlConnection::Lock::Lock(), and SqlConnection::Lock::~Lock().
The documentation for this class was generated from the following files:
Database.h
Database.cpp