CMaNGOS_WoTLK: MapRefManager Class Reference
MapRefManager Class Reference
#include <MapRefManager.h>
Public Types
typedef LinkedListHead::Iterator< MapReference > iterator
typedef LinkedListHead::Iterator< MapReference const > const_iterator
Public Types inherited from RefManager< Map, Player >
typedef LinkedListHead::Iterator< Reference< Map, Player > > iterator
typedef LinkedListHead::Iterator< Reference< Map, Player > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
MapReference * getFirst ()
MapReference const * getFirst () const
MapReference * getLast ()
MapReference const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
const_iterator begin () const
const_iterator end () const
Public Member Functions inherited from RefManager< Map, Player >
RefManager ()
virtual ~RefManager ()
Reference< Map, Player > * getFirst ()
Reference< Map, Player > const * getFirst () const
Reference< Map, Player > * getLast ()
Reference< Map, Player > const * getLast () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
Definition at line 26 of file MapRefManager.h.
Member Typedef Documentation
const_iterator
typedef LinkedListHead::Iterator< MapReference const > MapRefManager::const_iterator
Definition at line 30 of file MapRefManager.h.
iterator
typedef LinkedListHead::Iterator< MapReference > MapRefManager::iterator
Definition at line 29 of file MapRefManager.h.
Member Function Documentation
begin() [1/2]
iterator MapRefManager::begin () inline
Definition at line 37 of file MapRefManager.h.
References getFirst().
Referenced by instance_dark_portal::StartPostEvent(), Map::Update(), and boss_bigbadwolfAI::UpdateAI().
begin() [2/2]
const_iterator MapRefManager::begin () const inline
Definition at line 41 of file MapRefManager.h.
References getFirst().
end() [1/2]
iterator MapRefManager::end () inline
Definition at line 38 of file MapRefManager.h.
Referenced by instance_dark_portal::StartPostEvent(), Map::Update(), and boss_bigbadwolfAI::UpdateAI().
end() [2/2]
const_iterator MapRefManager::end () const inline
Definition at line 42 of file MapRefManager.h.
getFirst() [1/2]
MapReference* MapRefManager::getFirst () inline
Definition at line 32 of file MapRefManager.h.
References RefManager< TO, FROM >::getFirst().
Referenced by begin(), and Map::TeleportAllPlayersTo().
getFirst() [2/2]
MapReference const* MapRefManager::getFirst () const inline
Definition at line 33 of file MapRefManager.h.
References RefManager< TO, FROM >::getFirst().
getLast() [1/2]
MapReference* MapRefManager::getLast () inline
Definition at line 34 of file MapRefManager.h.
References RefManager< TO, FROM >::getLast().
Referenced by rbegin().
getLast() [2/2]
MapReference const* MapRefManager::getLast () const inline
Definition at line 35 of file MapRefManager.h.
References RefManager< TO, FROM >::getLast().
rbegin()
iterator MapRefManager::rbegin () inline
Definition at line 39 of file MapRefManager.h.
References getLast().
rend()
iterator MapRefManager::rend () inline
Definition at line 40 of file MapRefManager.h.
The documentation for this class was generated from the following file:
MapRefManager.h