CMaNGOS_WoTLK: world_map_ebon_hold Class Reference
world_map_ebon_hold Class Reference
#include <world_map_ebon_hold.h>
Public Member Functions
world_map_ebon_hold (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void Update (const uint32 diff) override
bool CanAndToggleGothikYell ()
void DoUpdateBattleWorldState (uint32 uiStateId, uint32 uiStateData)
void DoUpdateBattleWeatherData (uint32 weatherId, uint32 weatherGrade)
void DoUpdateBattleZoneLightData (uint32 lightId, uint32 fadeInTime)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoSpawnUndeadWave ()
void DoEnableHolyTraps ()
void DoDefeatUndeadArmy ()
void DoResetBattleScene ()
void DoClearBattleScene ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_uiGothikYellTimer
uint32 m_uiBattleEncounter
uint32 m_uiBattleProgressTimer
uint32 m_uiTrapUsageTimer
uint32 m_uiDefendersDead
uint32 m_uiAttackersDead
uint32 m_uiAbominationsDead
GuidList m_lFleshBehemothGuids
GuidList m_lUndeadArmyGuids
GuidList m_lLightDefendersGuids
GuidList m_lLightTrapsGuids
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 227 of file world_map_ebon_hold.h.
Constructor & Destructor Documentation
world_map_ebon_hold()
world_map_ebon_hold::world_map_ebon_hold (Map * pMap)
Definition at line 27 of file world_map_ebon_hold.cpp.
References Initialize().
Member Function Documentation
CanAndToggleGothikYell()
bool world_map_ebon_hold::CanAndToggleGothikYell ()
Definition at line 502 of file world_map_ebon_hold.cpp.
References m_uiGothikYellTimer.
Referenced by npc_scarlet_ghoulAI::ReceiveAIEvent().
DoClearBattleScene()
void world_map_ebon_hold::DoClearBattleScene () protected
Definition at line 295 of file world_map_ebon_hold.cpp.
References aLightChampions, aScourgeChampions, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_lLightDefendersGuids, and NPC_HIGHLORD_TIRION_FORDRING.
Referenced by Update().
DoDefeatUndeadArmy()
void world_map_ebon_hold::DoDefeatUndeadArmy () protected
Definition at line 332 of file world_map_ebon_hold.cpp.
References Map::GetCreature(), InstanceData::instance, m_lFleshBehemothGuids, and m_lUndeadArmyGuids.
Referenced by SetData().
DoEnableHolyTraps()
void world_map_ebon_hold::DoEnableHolyTraps () protected
Definition at line 347 of file world_map_ebon_hold.cpp.
References ScriptedInstance::DoRespawnGameObject(), and m_lLightTrapsGuids.
Referenced by SetData().
DoResetBattleScene()
void world_map_ebon_hold::DoResetBattleScene () protected
Definition at line 318 of file world_map_ebon_hold.cpp.
References aScourgeChampions, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, and m_lFleshBehemothGuids.
Referenced by SetData(), and Update().
DoSpawnUndeadWave()
void world_map_ebon_hold::DoSpawnUndeadWave () protected
Definition at line 354 of file world_map_ebon_hold.cpp.
References aAbominationLocations, WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_LIGHT_OF_DAWN, sSpawnLocation::m_fO, sSpawnLocation::m_fX, sSpawnLocation::m_fY, sSpawnLocation::m_fZ, m_uiAttackersDead, sSpawnLocation::m_uiEntry, MAX_ABOMINATIONS, MAX_UNDEAD_WARRIORS, NPC_VOLATILE_GHOUL, NPC_WARRIOR_OF_THE_FROZEN_WASTES, roll_chance_i(), script_error_log(), Creature::SetWalk(), WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_DESPAWN.
Referenced by OnCreatureDeath(), and Update().
DoUpdateBattleWeatherData()
void world_map_ebon_hold::DoUpdateBattleWeatherData (uint32 weatherId, uint32 weatherGrade)
Definition at line 273 of file world_map_ebon_hold.cpp.
References Map::GetPlayers(), InstanceData::instance, and SPELL_CHAPTER_IV.
Referenced by npc_highlord_darion_mograineAI::JustDidDialogueStep().
DoUpdateBattleWorldState()
void world_map_ebon_hold::DoUpdateBattleWorldState (uint32 uiStateId, uint32 uiStateData)
Definition at line 262 of file world_map_ebon_hold.cpp.
References Map::GetPlayers(), InstanceData::instance, and SPELL_CHAPTER_IV.
Referenced by OnCreatureDeath(), SetData(), and Update().
DoUpdateBattleZoneLightData()
void world_map_ebon_hold::DoUpdateBattleZoneLightData (uint32 lightId, uint32 fadeInTime)
Definition at line 284 of file world_map_ebon_hold.cpp.
References Map::GetPlayers(), InstanceData::instance, and SPELL_CHAPTER_IV.
Referenced by npc_highlord_darion_mograineAI::JustDidDialogueStep().
GetData()
uint32 world_map_ebon_hold::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 253 of file world_map_ebon_hold.cpp.
References m_uiBattleEncounter, and TYPE_BATTLE.
Referenced by npc_highlord_darion_mograineAI::GetAIInformation(), npc_highlord_darion_mograineAI::MovementInform(), OnCreatureDeath(), and Update().
Initialize()
void world_map_ebon_hold::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 39 of file world_map_ebon_hold.cpp.
Referenced by world_map_ebon_hold().
OnCreatureCreate()
void world_map_ebon_hold::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 41 of file world_map_ebon_hold.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), Creature::IsTemporarySummon(), m_lFleshBehemothGuids, m_lLightDefendersGuids, m_lUndeadArmyGuids, ScriptedInstance::m_npcEntryGuidStore, NPC_COMMANDER_ELIGOR_DAWNBRINGER, NPC_DARION_MOGRAINE, NPC_DEFENDER_OF_THE_LIGHT, NPC_DUKE_NICHOLAS_ZVERENHOFF, NPC_FLESH_BEHEMOTH, NPC_HIGHLORD_ALEXANDROS_MOGRAINE, NPC_HIGHLORD_DARION_MOGRAINE, NPC_HIGHLORD_TIRION_FORDRING, NPC_KOLTIRA_DEATHWEAVER, NPC_KORFAX_CHAMPION_OF_THE_LIGHT, NPC_LEONID_BARTHALOMEW_THE_REVERED, NPC_LORD_MAXWELL_TYROSUS, NPC_ORBAZ_BLOODBANE, NPC_RAMPAGING_ABOMINATION, NPC_RAYNE, NPC_RIMBLAT_EARTHSHATTER, NPC_THASSARIAN, NPC_THE_LICH_KING, NPC_VOLATILE_GHOUL, and NPC_WARRIOR_OF_THE_FROZEN_WASTES.
OnCreatureDeath()
void world_map_ebon_hold::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 93 of file world_map_ebon_hold.cpp.
References aAbominationLocations, BATTLE_STATE_IN_PROGRESS, BATTLE_STATE_LOST, DoSpawnUndeadWave(), DoUpdateBattleWorldState(), GetData(), Object::GetEntry(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), sSpawnLocation::m_fO, sSpawnLocation::m_fX, sSpawnLocation::m_fY, sSpawnLocation::m_fZ, m_uiAbominationsDead, m_uiAttackersDead, m_uiDefendersDead, sSpawnLocation::m_uiEntry, MAX_ABOMINATIONS, MAX_FORCES_LIGHT, MAX_FORCES_SCOURGE, MAX_UNDEAD_WARRIORS, NPC_COMMANDER_ELIGOR_DAWNBRINGER, NPC_DEFENDER_OF_THE_LIGHT, NPC_DUKE_NICHOLAS_ZVERENHOFF, NPC_FLESH_BEHEMOTH, NPC_KORFAX_CHAMPION_OF_THE_LIGHT, NPC_LEONID_BARTHALOMEW_THE_REVERED, NPC_LORD_MAXWELL_TYROSUS, NPC_RAMPAGING_ABOMINATION, NPC_RAYNE, NPC_RIMBLAT_EARTHSHATTER, NPC_VOLATILE_GHOUL, NPC_WARRIOR_OF_THE_FROZEN_WASTES, Creature::SetCorpseDelay(), WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, TYPE_BATTLE, WORLD_STATE_FORCES_LIGHT, and WORLD_STATE_FORCES_SCOURGE.
OnCreatureRespawn()
void world_map_ebon_hold::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 80 of file world_map_ebon_hold.cpp.
References Object::GetEntry(), Creature::IsTemporarySummon(), NPC_RAMPAGING_ABOMINATION, NPC_VOLATILE_GHOUL, NPC_WARRIOR_OF_THE_FROZEN_WASTES, and Creature::SetWalk().
OnObjectCreate()
void world_map_ebon_hold::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 171 of file world_map_ebon_hold.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_HOLY_LIGHTNING_1, GO_HOLY_LIGHTNING_2, GO_LIGHT_OF_DAWN, ScriptedInstance::m_goEntryGuidStore, and m_lLightTrapsGuids.
SetData()
void world_map_ebon_hold::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 185 of file world_map_ebon_hold.cpp.
References BATTLE_STATE_DIALOGUE, BATTLE_STATE_IN_PROGRESS, BATTLE_STATE_LOST, BATTLE_STATE_NOT_STARTED, BATTLE_STATE_PREPARE, BATTLE_STATE_RESET, BATTLE_STATE_WAIT_QUEST, DoDefeatUndeadArmy(), DoEnableHolyTraps(), DoResetBattleScene(), DoUpdateBattleWorldState(), Map::GetCreature(), InstanceData::instance, m_lLightDefendersGuids, m_uiAttackersDead, m_uiBattleEncounter, m_uiBattleProgressTimer, m_uiDefendersDead, m_uiTrapUsageTimer, MAX_BATTLE_INTRO_TIMER, MAX_FORCES_LIGHT, MAX_FORCES_SCOURGE, TIMER_BATTLE_PREPARE, TIMER_BATTLE_PROGRESS, TIMER_BATTLE_QUEST_WAIT, TIMER_BATTLE_RESET_DELAY, TYPE_BATTLE, WORLD_STATE_BATTLE_BEGIN, WORLD_STATE_BATTLE_TIMER_SHOW, WORLD_STATE_BATTLE_TIMER_TIME, WORLD_STATE_FORCES_LIGHT, WORLD_STATE_FORCES_SCOURGE, and WORLD_STATE_FORCES_SHOW.
Referenced by npc_highlord_darion_mograineAI::DoStartConclusion(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), and Update().
Update()
void world_map_ebon_hold::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 386 of file world_map_ebon_hold.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_B, AI_EVENT_CUSTOM_C, BATTLE_STATE_IN_PROGRESS, BATTLE_STATE_LOST, BATTLE_STATE_NOT_STARTED, BATTLE_STATE_PREPARE, BATTLE_STATE_RESET, BATTLE_STATE_WAIT_QUEST, DoClearBattleScene(), DoResetBattleScene(), DoSpawnUndeadWave(), DoUpdateBattleWorldState(), GetData(), Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, InstanceData::instance, m_lLightTrapsGuids, m_uiBattleProgressTimer, m_uiGothikYellTimer, m_uiTrapUsageTimer, MINUTE, NPC_HIGHLORD_DARION_MOGRAINE, NPC_HIGHLORD_TIRION_FORDRING, script_error_log(), UnitAI::SendAIEvent(), SetData(), TYPE_BATTLE, urand(), and WORLD_STATE_BATTLE_TIMER_TIME.
Field Documentation
m_lFleshBehemothGuids
GuidList world_map_ebon_hold::m_lFleshBehemothGuids protected
Definition at line 266 of file world_map_ebon_hold.h.
Referenced by DoDefeatUndeadArmy(), DoResetBattleScene(), and OnCreatureCreate().
m_lLightDefendersGuids
GuidList world_map_ebon_hold::m_lLightDefendersGuids protected
Definition at line 268 of file world_map_ebon_hold.h.
Referenced by DoClearBattleScene(), OnCreatureCreate(), and SetData().
m_lLightTrapsGuids
GuidList world_map_ebon_hold::m_lLightTrapsGuids protected
Definition at line 269 of file world_map_ebon_hold.h.
Referenced by DoEnableHolyTraps(), OnObjectCreate(), and Update().
m_lUndeadArmyGuids
GuidList world_map_ebon_hold::m_lUndeadArmyGuids protected
Definition at line 267 of file world_map_ebon_hold.h.
Referenced by DoDefeatUndeadArmy(), and OnCreatureCreate().
m_uiAbominationsDead
uint32 world_map_ebon_hold::m_uiAbominationsDead protected
Definition at line 264 of file world_map_ebon_hold.h.
Referenced by OnCreatureDeath().
m_uiAttackersDead
uint32 world_map_ebon_hold::m_uiAttackersDead protected
Definition at line 263 of file world_map_ebon_hold.h.
Referenced by DoSpawnUndeadWave(), OnCreatureDeath(), and SetData().
m_uiBattleEncounter
uint32 world_map_ebon_hold::m_uiBattleEncounter protected
Definition at line 258 of file world_map_ebon_hold.h.
Referenced by GetData(), and SetData().
m_uiBattleProgressTimer
uint32 world_map_ebon_hold::m_uiBattleProgressTimer protected
Definition at line 259 of file world_map_ebon_hold.h.
Referenced by SetData(), and Update().
m_uiDefendersDead
uint32 world_map_ebon_hold::m_uiDefendersDead protected
Definition at line 262 of file world_map_ebon_hold.h.
Referenced by OnCreatureDeath(), and SetData().
m_uiGothikYellTimer
uint32 world_map_ebon_hold::m_uiGothikYellTimer protected
Definition at line 257 of file world_map_ebon_hold.h.
Referenced by CanAndToggleGothikYell(), and Update().
m_uiTrapUsageTimer
uint32 world_map_ebon_hold::m_uiTrapUsageTimer protected
Definition at line 260 of file world_map_ebon_hold.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
world_map_ebon_hold.h
world_map_ebon_hold.cpp