CMaNGOS_WoTLK: GraveyardManager Class Reference
GraveyardManager Class Reference
#include <GraveyardManager.h>
Public Member Functions
void Init (Map *map)
WorldSafeLocsEntry const * GetClosestGraveYard (float x, float y, float z, uint32 mapId, Team team) const
bool AddGraveYardLink (uint32 id, uint32 locId, uint32 linkKind, Team team, bool inDB=true)
void SetGraveYardLinkTeam (uint32 id, uint32 linkKey, Team team)
GraveYardData const * FindGraveYardData (uint32 id, uint32 zoneId)
GraveYardMap & GetGraveyardMap ()
Static Public Member Functions
static GraveYardData const * FindGraveYardData (GraveYardMap const &map, uint32 id, uint32 zoneId)
static uint32 GraveyardLinkKey (uint32 locId, uint32 linkKind)
Private Member Functions
WorldSafeLocsEntry const * GetClosestGraveyardHelper (GraveYardMapBounds bounds, float x, float y, float z, uint32 mapId, Team team) const
Private Attributes
GraveYardMap m_graveyardMap
Detailed Description
Definition at line 48 of file GraveyardManager.h.
Member Function Documentation
AddGraveYardLink()
bool GraveyardManager::AddGraveYardLink (uint32 id, uint32 locId, uint32 linkKind, Team team, bool inDB = true)
Adds a given graveyard link to the currently active graveyard links. Optionally add it into the database too.
Parameters
id The id of a graveyard. This is an index to the graveyard in sWorldSafeLocsStore which holds data from WorldSafeLocs.dbc
locId The id of a location. This is either an area id or a map id based on the value of linkKind
linkKind The kind of the graveyard link to be added. Kind is either GRAVEYARD_MAPLINK or GRAVEYARD_AREALINK
team The team that is allowed to use this graveyard link. Can be TEAM_BOTH_ALLOWED, HORDE or ALLIANCE.
inDB True if the given graveyard link needs to be added to the database. False otherwise.
Returns
Whether or not the link was added (False only if the link was already added added).
Definition at line 226 of file GraveyardManager.cpp.
References FindGraveYardData(), GraveyardLinkKey(), m_graveyardMap, Database::PExecuteLog(), GraveYardData::safeLocId, GraveYardData::team, and WorldDatabase.
Referenced by ChatHandler::HandleLinkGraveCommand(), and SetGraveYardLinkTeam().
FindGraveYardData() [1/2]
GraveYardData const * GraveyardManager::FindGraveYardData (GraveYardMap const & map, uint32 id, uint32 locKey) static
Return the Graveyard link data for a given graveyard and location combination.
Parameters
id The id of a graveyard. This is an index to the graveyard in sWorldSafeLocsStore which holds data from WorldSafeLocs.dbc
locKey A location key as returned by ObjectMgr::GraveyardLinkKey
Definition at line 177 of file GraveyardManager.cpp.
FindGraveYardData() [2/2]
GraveYardData const * GraveyardManager::FindGraveYardData (uint32 id, uint32 zoneId)
Definition at line 273 of file GraveyardManager.cpp.
References m_graveyardMap.
Referenced by AddGraveYardLink(), ChatHandler::HandleNearGraveCommand(), and World::LoadGraveyardZones().
GetClosestGraveYard()
WorldSafeLocsEntry const * GraveyardManager::GetClosestGraveYard (float x, float y, float z, uint32 mapId, Team team) const
Definition at line 134 of file GraveyardManager.cpp.
References GetClosestGraveyardHelper(), GRAVEYARD_AREALINK, GRAVEYARD_MAPLINK, GraveyardLinkKey(), m_graveyardMap, sLog, and sTerrainMgr.
Referenced by ChatHandler::HandleNearGraveCommand(), Player::RepopAtGraveyard(), WorldSession::SendSpiritResurrect(), and Player::SetBattleGroundEntryPoint().
GetClosestGraveyardHelper()
WorldSafeLocsEntry const * GraveyardManager::GetClosestGraveyardHelper (GraveYardMapBounds bounds, float x, float y, float z, uint32 mapId, Team team) const private
Definition at line 27 of file GraveyardManager.cpp.
References MapEntry::ghost_entrance_map, MapEntry::ghost_entrance_x, MapEntry::ghost_entrance_y, SQLStorage::LookupEntry(), WorldSafeLocsEntry::map_id, GraveYardData::safeLocId, sMapStore, sWorldSafeLocsStore, GraveYardData::team, TEAM_BOTH_ALLOWED, WorldSafeLocsEntry::x, WorldSafeLocsEntry::y, and WorldSafeLocsEntry::z.
Referenced by GetClosestGraveYard().
GetGraveyardMap()
GraveYardMap& GraveyardManager::GetGraveyardMap () inline
Definition at line 62 of file GraveyardManager.h.
References m_graveyardMap.
Referenced by World::LoadGraveyardZones().
GraveyardLinkKey()
uint32 GraveyardManager::GraveyardLinkKey (uint32 locationId, uint32 linkKind) static
Turn a location id and a link kind into a location key that indexes the graveyard link map.
Parameters
locationId The id of an area or a map.
linkKind The kind of id, either GRAVEYARD_MAPLINK or GRAVEYARD_AREALINK
Returns
The location key composed of the given data.
Definition at line 199 of file GraveyardManager.cpp.
Referenced by AddGraveYardLink(), GetClosestGraveYard(), and World::LoadGraveyardZones().
Init()
void GraveyardManager::Init (Map * map)
Definition at line 127 of file GraveyardManager.cpp.
References m_graveyardMap, and sWorld.
Referenced by Map::Initialize().
SetGraveYardLinkTeam()
void GraveyardManager::SetGraveYardLinkTeam (uint32 id, uint32 linkKey, Team team)
Definition at line 245 of file GraveyardManager.cpp.
References AddGraveYardLink(), m_graveyardMap, GraveYardData::safeLocId, sLog, GraveYardData::team, and TEAM_INVALID.
Referenced by BattleGroundIC::DoApplyObjectiveBenefits(), BattleGroundIC::DoResetObjective(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundAV::InitializeNode(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundAB::ProcessNodeCapture(), BattleGroundAV::ProcessPlayerAssaultsPoint(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundWS::Reset(), BattleGroundSA::SetupBattleground(), BattleGroundAB::StartingEventOpenDoors(), BattleGroundEY::StartingEventOpenDoors(), and BattleGroundWS::StartingEventOpenDoors().
Field Documentation
m_graveyardMap
GraveYardMap GraveyardManager::m_graveyardMap private
Definition at line 66 of file GraveyardManager.h.
Referenced by AddGraveYardLink(), FindGraveYardData(), GetClosestGraveYard(), GetGraveyardMap(), Init(), and SetGraveYardLinkTeam().
The documentation for this class was generated from the following files:
GraveyardManager.h
GraveyardManager.cpp