CMaNGOS_WoTLK: MaNGOS::Thread Class Reference
MaNGOS::Thread Class Reference
#include <Threading.h>
Public Member Functions
Thread ()
Thread (Runnable *instance)
~Thread ()
bool wait ()
void destroy ()
void setPriority (Priority priority)
Static Public Member Functions
static void Sleep (unsigned long msecs)
static std::thread::id currentId ()
Private Member Functions
Thread (const Thread &)
Thread & operator= (const Thread &)
Static Private Member Functions
static void ThreadTask (void *param)
Private Attributes
Runnable *const m_task
std::thread::id m_iThreadId
std::thread m_ThreadImp
Detailed Description
Definition at line 54 of file Threading.h.
Constructor & Destructor Documentation
Thread() [1/3]
Thread::Thread ()
Definition at line 27 of file Threading.cpp.
Thread() [2/3]
Thread::Thread (Runnable * instance) explicit
Definition at line 31 of file Threading.cpp.
References MaNGOS::Runnable::incReference(), m_iThreadId, m_task, and m_ThreadImp.
~Thread()
Thread::~Thread ()
Definition at line 40 of file Threading.cpp.
References MaNGOS::Runnable::decReference(), and m_task.
Thread() [3/3]
MaNGOS::Thread::Thread (const Thread &) private
Member Function Documentation
currentId()
std::thread::id Thread::currentId () static
Definition at line 87 of file Threading.cpp.
destroy()
void Thread::destroy ()
Definition at line 70 of file Threading.cpp.
References m_iThreadId, m_task, and m_ThreadImp.
Referenced by Master::Run().
operator=()
Thread& MaNGOS::Thread::operator= (const Thread &) private
setPriority()
void Thread::setPriority (Priority priority)
Definition at line 92 of file Threading.cpp.
References m_ThreadImp, MANGOS_ASSERT, MaNGOS::Priority_High, MaNGOS::Priority_Highest, MaNGOS::Priority_Idle, MaNGOS::Priority_Low, MaNGOS::Priority_Lowest, MaNGOS::Priority_Normal, and MaNGOS::Priority_Realtime.
Referenced by Master::Run().
Sleep()
void Thread::Sleep (unsigned long msecs) static
Definition at line 134 of file Threading.cpp.
Referenced by SqlDelayThread::run(), WorldRunnable::run(), and FreezeDetectorRunnable::run().
ThreadTask()
void Thread::ThreadTask (void * param) static private
Definition at line 81 of file Threading.cpp.
References MaNGOS::Runnable::run().
wait()
bool Thread::wait ()
Definition at line 49 of file Threading.cpp.
References m_iThreadId, m_task, and m_ThreadImp.
Referenced by Database::HaltDelayThread(), and Master::Run().
Field Documentation
m_iThreadId
std::thread::id MaNGOS::Thread::m_iThreadId private
Definition at line 76 of file Threading.h.
Referenced by destroy(), Thread(), and wait().
m_task
Runnable* const MaNGOS::Thread::m_task private
Definition at line 75 of file Threading.h.
Referenced by destroy(), Thread(), wait(), and ~Thread().
m_ThreadImp
std::thread MaNGOS::Thread::m_ThreadImp private
Definition at line 77 of file Threading.h.
Referenced by destroy(), setPriority(), Thread(), and wait().
The documentation for this class was generated from the following files:
Threading.h
Threading.cpp