CMaNGOS_WoTLK: LFGMgr Class Reference
LFGMgr Class Reference
#include <LFGMgr.h>
Public Member Functions
void LoadRewards ()
void LoadLFGDungeons (bool reload=false)
bool IsSeasonActive (uint32 dungeonId) const
uint32 GetLFGDungeonEntry (uint32 id)
LfgReward const * GetRandomDungeonReward (uint32 dungeon, uint8 level)
LfgDungeonSet GetRandomAndSeasonalDungeons (uint8 level, uint8 expansion) const
LfgLockMap const GetLockedDungeons (Player *player)
Get locked dungeons.
LfgDungeonSet const & GetDungeonsByRandom (uint32 randomdungeon)
LfgType GetDungeonType (uint32 dungeonId)
void JoinLfg (Player *player, uint8 roles, LfgDungeonSet &dungeons, std::string &comment)
void LeaveLfg (Player *player)
void TeleportPlayer (Player *player, bool out, bool fromOpcode)
Teleports the player in or out the dungeon.
LFGDungeonData const * GetLFGDungeon (uint32 id)
void FinishDungeon (Group *group, uint32 dungeonId, Map const *currMap)
Static Public Member Functions
static uint32 FilterClassRoles (uint32 roles, uint32 classMask)
static bool CheckGroupRoles (LfgPlayerInfoMap &groles)
Private Member Functions
void GetCompatibleDungeons (LfgDungeonSet &dungeons, GuidSet const &players, LfgLockPartyMap &lockMap, LfgInstanceSaveMap &savedMap, bool isContinue)
Given a list of dungeons remove the dungeons players have restrictions.
Private Attributes
std::unordered_map< uint32, LFGDungeonData > m_lfgDungeons
std::multimap< uint32, LfgReward > m_lfgRewards
std::map< uint32, LfgDungeonSet > m_cachedDungeonMapsPerGroup
Detailed Description
Definition at line 83 of file LFGMgr.h.
Member Function Documentation
CheckGroupRoles()
bool LFGMgr::CheckGroupRoles (LfgPlayerInfoMap & groles) static
Definition at line 876 of file LFGMgr.cpp.
References LFG_DPS_NEEDED, LFG_HEALERS_NEEDED, LFG_TANKS_NEEDED, PLAYER_ROLE_DAMAGE, PLAYER_ROLE_HEALER, PLAYER_ROLE_LEADER, PLAYER_ROLE_NONE, and PLAYER_ROLE_TANK.
Referenced by LFGQueueData::UpdateRoleCheck().
FilterClassRoles()
uint32 LFGMgr::FilterClassRoles (uint32 roles, uint32 classMask) static
Definition at line 866 of file LFGMgr.cpp.
References HEALER, PLAYER_ROLE_ANY, PLAYER_ROLE_HEALER, PLAYER_ROLE_TANK, and TANK.
Referenced by JoinLfg().
FinishDungeon()
void LFGMgr::FinishDungeon (Group * group, uint32 dungeonId, Map const * currMap)
Definition at line 257 of file LFGMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_USE_LFD_TO_GROUP_WITH_PLAYERS, Player::CanRewardQuest(), LFGDungeonData::difficulty, DUNGEON_DIFFICULTY_HEROIC, LFGDungeonData::Entry(), LfgReward::firstQuest, LFGData::GetCountAtJoin(), LFGData::GetDungeon(), Group::GetFirstMember(), Unit::GetLevel(), Player::GetLfgData(), Group::GetLfgData(), GetLFGDungeon(), WorldObject::GetMap(), WorldObject::GetMapId(), Object::GetObjectGuid(), Group::GetObjectGuid(), GetRandomDungeonReward(), Player::GetSession(), LFGData::GetState(), ObjectGuid::GetString(), LFG_SPELL_DUNGEON_COOLDOWN, LFG_STATE_FINISHED_DUNGEON, LFG_TYPE_RANDOM_DUNGEON, LFGDungeonData::map, GroupReference::next(), LfgReward::otherQuest, Unit::RemoveAurasDueToSpell(), Player::RewardQuest(), LFGDungeonData::seasonal, WorldSession::SendLfgPlayerReward(), LFGData::SetState(), sLog, sObjectMgr, LFGDungeonData::type, and Player::UpdateAchievementCriteria().
GetCompatibleDungeons()
void LFGMgr::GetCompatibleDungeons (LfgDungeonSet & dungeons, GuidSet const & players, LfgLockPartyMap & lockMap, LfgInstanceSaveMap & savedMap, bool isContinue) private
Given a list of dungeons remove the dungeons players have restrictions.
Parameters
[in,out] dungeons Dungeons to check restrictions
[in] players Set of players to check their dungeon restrictions
[out] lockMap Map of players Lock status info of given dungeons (Empty if dungeons is not empty)
Definition at line 363 of file LFGMgr.cpp.
References LFGDungeonData::difficulty, ObjectAccessor::FindPlayer(), Player::GetBoundInstance(), GetLFGDungeon(), GetLockedDungeons(), LFG_LOCKSTATUS_RAID_LOCKED, MANGOS_ASSERT, and LFGDungeonData::map.
Referenced by JoinLfg().
GetDungeonsByRandom()
LfgDungeonSet const & LFGMgr::GetDungeonsByRandom (uint32 randomdungeon)
Definition at line 520 of file LFGMgr.cpp.
References GetLFGDungeon(), LFGDungeonData::group, and m_cachedDungeonMapsPerGroup.
Referenced by GetLockedDungeons(), and JoinLfg().
GetDungeonType()
LfgType LFGMgr::GetDungeonType (uint32 dungeonId)
Definition at line 527 of file LFGMgr.cpp.
References GetLFGDungeon(), LFG_TYPE_NONE, and LFGDungeonData::type.
Referenced by JoinLfg().
GetLFGDungeon()
LFGDungeonData const * LFGMgr::GetLFGDungeon (uint32 id)
Definition at line 247 of file LFGMgr.cpp.
References m_lfgDungeons.
Referenced by FinishDungeon(), GetCompatibleDungeons(), GetDungeonsByRandom(), GetDungeonType(), GetLFGDungeonEntry(), GetLockedDungeons(), and TeleportPlayer().
GetLFGDungeonEntry()
uint32 LFGMgr::GetLFGDungeonEntry (uint32 id)
Definition at line 415 of file LFGMgr.cpp.
References GetLFGDungeon().
Referenced by LoadRewards().
GetLockedDungeons()
LfgLockMap const LFGMgr::GetLockedDungeons (Player * player)
Get locked dungeons.
Definition at line 452 of file LFGMgr.cpp.
References ALLIANCE, LFGDungeonData::CheckMaxLevel(), LFGDungeonData::CheckMinLevel(), LFGDungeonData::difficulty, DUNGEON_DIFFICULTY_NORMAL, LFGDungeonData::Entry(), LFGDungeonData::expansion, Player::GetAchievementMgr(), Player::GetAverageItemLevel(), Player::GetBoundInstance(), GetDungeonsByRandom(), WorldSession::GetExpansion(), Unit::GetLevel(), GetLFGDungeon(), Player::GetQuestRewardStatus(), Player::GetSession(), Player::GetTeam(), LFGDungeonData::group, AchievementMgr::HasAchievement(), Player::HasItemCount(), HORDE, LFGDungeonData::id, IsSeasonActive(), LFG_LOCKSTATUS_INSUFFICIENT_EXPANSION, LFG_LOCKSTATUS_MISSING_ACHIEVEMENT, LFG_LOCKSTATUS_MISSING_ITEM, LFG_LOCKSTATUS_NOT_IN_SEASON, LFG_LOCKSTATUS_QUEST_NOT_COMPLETED, LFG_LOCKSTATUS_RAID_LOCKED, LFG_LOCKSTATUS_TOO_HIGH_LEVEL, LFG_LOCKSTATUS_TOO_LOW_GEAR_SCORE, LFG_LOCKSTATUS_TOO_LOW_LEVEL, LFGDungeonData::map, LFGDungeonData::seasonal, and sObjectMgr.
Referenced by GetCompatibleDungeons().
GetRandomAndSeasonalDungeons()
LfgDungeonSet LFGMgr::GetRandomAndSeasonalDungeons (uint8 level, uint8 expansion) const
Definition at line 439 of file LFGMgr.cpp.
References IsSeasonActive(), LFG_TYPE_RANDOM_DUNGEON, and m_lfgDungeons.
GetRandomDungeonReward()
LfgReward const * LFGMgr::GetRandomDungeonReward (uint32 dungeon, uint8 level)
Definition at line 424 of file LFGMgr.cpp.
References m_lfgRewards.
Referenced by FinishDungeon().
IsSeasonActive()
bool LFGMgr::IsSeasonActive (uint32 dungeonId) const
Definition at line 231 of file LFGMgr.cpp.
References HOLIDAY_BREWFEST, HOLIDAY_FIRE_FESTIVAL, HOLIDAY_HALLOWS_END, HOLIDAY_LOVE_IS_IN_THE_AIR, SEASONAL_AHUNE, SEASONAL_COREN_DIREBREW, SEASONAL_CROWN_CHEMICAL_CO, SEASONAL_HEADLESS_HORSEMAN, and sGameEventMgr.
Referenced by GetLockedDungeons(), and GetRandomAndSeasonalDungeons().
JoinLfg()
void LFGMgr::JoinLfg (Player * player, uint8 roles, LfgDungeonSet & dungeons, std::string & comment)
Definition at line 536 of file LFGMgr.cpp.
References LFGQueue::AddToQueue(), Group::BroadcastPacket(), WorldSession::BuildLfgJoinResult(), WorldSession::BuildLfgUpdate(), ConcatenateDungeons(), DEBUG_LOG, FilterClassRoles(), Unit::getClass(), Unit::getClassMask(), GetCompatibleDungeons(), Map::GetCurrentClockTime(), LFGData::GetDungeon(), GetDungeonsByRandom(), GetDungeonType(), Group::GetFirstMember(), Player::GetGroup(), Unit::GetLevel(), Player::GetLfgData(), Group::GetLfgData(), LFGData::GetListedDungeonSet(), WorldObject::GetMap(), Group::GetMembersCount(), Object::GetObjectGuid(), Group::GetObjectGuid(), Unit::getRace(), World::GetRaidBrowser(), Player::GetSession(), LFGData::GetState(), ObjectGuid::GetString(), Player::GetTeam(), Unit::HasAura(), Player::InArena(), Player::InBattleGround(), Player::InBattleGroundQueue(), Group::IsLFGGroup(), LFG_JOIN_DESERTER, LFG_JOIN_DISCONNECTED, LFG_JOIN_DUNGEON_INVALID, LFG_JOIN_MIXED_RAID_DUNGEON, LFG_JOIN_NOT_MEET_REQS, LFG_JOIN_OK, LFG_JOIN_PARTY_DESERTER, LFG_JOIN_PARTY_NOT_MEET_REQS, LFG_JOIN_PARTY_RANDOM_COOLDOWN, LFG_JOIN_RANDOM_COOLDOWN, LFG_JOIN_TOO_MUCH_MEMBERS, LFG_JOIN_USING_BG_SYSTEM, LFG_ROLECHECK_DEFAULT, LFG_ROLECHECK_INITIALITING, LFG_SPELL_DUNGEON_COOLDOWN, LFG_SPELL_DUNGEON_DESERTER, LFG_STATE_FINISHED_DUNGEON, LFG_STATE_QUEUED, LFG_STATE_RAIDBROWSER, LFG_STATE_ROLECHECK, LFG_TYPE_DUNGEON, LFG_TYPE_HEROIC_DUNGEON, LFG_TYPE_RAID, LFG_TYPE_RANDOM_DUNGEON, LFG_UPDATETYPE_JOIN_QUEUE, LfgJoinResultData::lockmap, LFGQueueData::m_cancelTime, LFGQueueData::m_dungeons, LFGQueueData::m_groupGuids, LFGQueueData::m_joinTime, LFGQueueData::m_leaderGuid, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, LFGQueueData::m_raid, LFGQueueData::m_randomDungeonId, LFGQueueData::m_roleCheckState, LFGQueueData::m_savedMap, LFGQueueData::m_state, LFGQueueData::m_team, MAX_GROUP_SIZE, GroupReference::next(), PLAYER_ROLE_DAMAGE, PLAYER_ROLE_HEALER, PLAYER_ROLE_TANK, LFGQueue::RemoveFromQueue(), LfgJoinResultData::result, WorldSession::SendPacket(), LFGData::SetComment(), LFGData::SetPlayerRoles(), LFGData::SetState(), and sWorld.
LeaveLfg()
void LFGMgr::LeaveLfg (Player * player)
Definition at line 795 of file LFGMgr.cpp.
References Group::BroadcastPacket(), WorldSession::BuildLfgUpdate(), Player::GetGroup(), Player::GetLfgData(), Group::GetLfgData(), LFGData::GetListedDungeonSet(), Object::GetObjectGuid(), Group::GetObjectGuid(), Player::GetSession(), LFGData::GetState(), LFG_STATE_NONE, LFG_STATE_RAIDBROWSER, LFG_UPDATETYPE_REMOVED_FROM_QUEUE, WorldSession::SendPacket(), LFGData::SetState(), and sWorld.
LoadLFGDungeons()
void LFGMgr::LoadLFGDungeons (bool reload = false)
Definition at line 146 of file LFGMgr.cpp.
References Field::GetFloat(), Field::GetUInt32(), LFGDungeonData::group, LFGDungeonData::id, LFGDungeonEntry::ID, LFG_TYPE_DUNGEON, LFG_TYPE_HEROIC_DUNGEON, LFG_TYPE_RAID, LFG_TYPE_RANDOM_DUNGEON, m_cachedDungeonMapsPerGroup, m_lfgDungeons, LFGDungeonData::map, LFGDungeonData::name, LFGDungeonData::o, Database::Query(), sLFGDungeonStore, sLog, sObjectMgr, BarGoLink::step(), AreaTrigger::target_mapId, AreaTrigger::target_Orientation, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, LFGDungeonData::type, LFGDungeonEntry::TypeID, WorldDatabase, LFGDungeonData::x, LFGDungeonData::y, and LFGDungeonData::z.
LoadRewards()
void LFGMgr::LoadRewards ()
Definition at line 83 of file LFGMgr.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, LfgReward::firstQuest, GetLFGDungeonEntry(), Field::GetUInt32(), Field::GetUInt8(), m_lfgRewards, LfgReward::maxLevel, LfgReward::otherQuest, Database::Query(), sLog, sObjectMgr, BarGoLink::step(), sWorld, and WorldDatabase.
TeleportPlayer()
void LFGMgr::TeleportPlayer (Player * player, bool out, bool fromOpcode)
Teleports the player in or out the dungeon.
Parameters
[in] player Player to teleport
[in] out Teleport out (true) or in (false)
[in] fromOpcode Function called from opcode handlers? (Default false)
Definition at line 946 of file LFGMgr.cpp.
References MirrorTimer::FATIGUE, Unit::GetCharm(), LFGData::GetDungeon(), Group::GetFirstMember(), Player::GetGroup(), Group::GetLfgData(), GetLFGDungeon(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetSession(), Unit::GetVehicleInfo(), Unit::HasAura(), Unit::hasUnitState(), Unit::IsAlive(), Map::IsDungeon(), Unit::IsFalling(), Group::IsLFGGroup(), Player::IsMirrorTimerActive(), LFG_TELEPORTERROR_CHARMING, LFG_TELEPORTERROR_FALLING, LFG_TELEPORTERROR_FATIGUE, LFG_TELEPORTERROR_IN_VEHICLE, LFG_TELEPORTERROR_INVALID_LOCATION, LFG_TELEPORTERROR_OK, LFG_TELEPORTERROR_PLAYER_DEAD, LFGDungeonData::map, GroupReference::next(), LFGDungeonData::o, WorldSession::SendLfgTeleportError(), Player::SetBattleGroundEntryPoint(), sLog, Player::TaxiFlightInterrupt(), Player::TeleportTo(), Player::TeleportToBGEntryPoint(), UNIT_STAT_PROPELLED, LFGDungeonData::x, LFGDungeonData::y, and LFGDungeonData::z.
Field Documentation
m_cachedDungeonMapsPerGroup
std::map<uint32, LfgDungeonSet> LFGMgr::m_cachedDungeonMapsPerGroup private
Definition at line 123 of file LFGMgr.h.
Referenced by GetDungeonsByRandom(), and LoadLFGDungeons().
m_lfgDungeons
std::unordered_map<uint32, LFGDungeonData> LFGMgr::m_lfgDungeons private
Definition at line 121 of file LFGMgr.h.
Referenced by GetLFGDungeon(), GetRandomAndSeasonalDungeons(), and LoadLFGDungeons().
m_lfgRewards
std::multimap<uint32, LfgReward> LFGMgr::m_lfgRewards private
Definition at line 122 of file LFGMgr.h.
Referenced by GetRandomDungeonReward(), and LoadRewards().
The documentation for this class was generated from the following files:
LFGMgr.h
LFGMgr.cpp