CMaNGOS_WoTLK: MovementGenerator Class Reference
MovementGenerator Class Reference abstract
#include <MovementGenerator.h>
Public Member Functions
virtual ~MovementGenerator ()
virtual void Initialize (Unit &)=0
virtual void Finalize (Unit &)=0
virtual void Interrupt (Unit &)=0
virtual void Reset (Unit &)=0
virtual bool Update (Unit &, const uint32 &time_diff)=0
virtual MovementGeneratorType GetMovementGeneratorType () const =0
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Detailed Description
Definition at line 32 of file MovementGenerator.h.
Constructor & Destructor Documentation
~MovementGenerator()
MovementGenerator::~MovementGenerator () virtual
Definition at line 22 of file MovementGenerator.cpp.
Member Function Documentation
Finalize()
virtual void MovementGenerator::Finalize (Unit &) pure virtual
Implemented in StayMovementGenerator, RetreatMovementGenerator, PointMovementGenerator, PathJumpGenerator, TaxiMovementGenerator, FixedPathMovementGenerator, MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, EffectMovementGenerator, AbstractWrapperMovementGenerator, FollowMovementGenerator, PanicMovementGenerator, WanderMovementGenerator, AbstractRandomMovementGenerator, AbstractPathMovementGenerator, DistractMovementGenerator, ChaseMovementGenerator, and IdleMovementGenerator.
Referenced by MotionMaster::DelayedClean(), MotionMaster::DelayedExpire(), MotionMaster::DirectClean(), and MotionMaster::DirectExpire().
GetCurrentTarget()
virtual Unit* MovementGenerator::GetCurrentTarget () const inline virtual
Reimplemented in TargetedMovementGeneratorMedium< T, D >, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >, and TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 50 of file MovementGenerator.h.
GetMovementGeneratorType()
virtual MovementGeneratorType MovementGenerator::GetMovementGeneratorType () const pure virtual
Implemented in AbstractWrapperMovementGenerator, FallMovementGenerator, EffectMovementGenerator, FormationMovementGenerator, FollowMovementGenerator, ChaseMovementGenerator, PanicMovementGenerator, FleeingMovementGenerator, TimedWanderMovementGenerator, WanderMovementGenerator, ConfusedMovementGenerator, StayMovementGenerator, RetreatMovementGenerator, PointMovementGenerator, PathJumpGenerator, TaxiMovementGenerator, FixedPathMovementGenerator, DistractMovementGenerator, IdleMovementGenerator, HomeMovementGenerator< Creature >, and WaypointMovementGenerator< Creature >.
Referenced by MotionMaster::DirectExpire(), and AbstractPathMovementGenerator::MovementInform().
GetResetPosition()
virtual bool MovementGenerator::GetResetPosition (Unit & , float & , float & , float & , float &) const inline virtual
Reimplemented in MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, FollowMovementGenerator, FormationMovementGenerator, and ChaseMovementGenerator.
Definition at line 55 of file MovementGenerator.h.
Initialize()
virtual void MovementGenerator::Initialize (Unit &) pure virtual
Implemented in StayMovementGenerator, RetreatMovementGenerator, PointMovementGenerator, PathJumpGenerator, TaxiMovementGenerator, FixedPathMovementGenerator, MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, EffectMovementGenerator, AbstractWrapperMovementGenerator, FollowMovementGenerator, PanicMovementGenerator, AbstractRandomMovementGenerator, AbstractPathMovementGenerator, DistractMovementGenerator, ChaseMovementGenerator, and IdleMovementGenerator.
Referenced by MotionMaster::Mutate().
Interrupt()
virtual void MovementGenerator::Interrupt (Unit &) pure virtual
Implemented in StayMovementGenerator, RetreatMovementGenerator, PointMovementGenerator, PathJumpGenerator, TaxiMovementGenerator, FixedPathMovementGenerator, MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, EffectMovementGenerator, AbstractWrapperMovementGenerator, FormationMovementGenerator, FollowMovementGenerator, PanicMovementGenerator, WanderMovementGenerator, AbstractRandomMovementGenerator, AbstractPathMovementGenerator, ChaseMovementGenerator, and IdleMovementGenerator.
IsActive()
bool MovementGenerator::IsActive (Unit & u)
Definition at line 26 of file MovementGenerator.cpp.
References Unit::GetMotionMaster().
IsReachable()
virtual bool MovementGenerator::IsReachable () const inline virtual
Reimplemented in ChaseMovementGenerator, TargetedMovementGeneratorMedium< T, D >, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >, and TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >.
Definition at line 58 of file MovementGenerator.h.
Referenced by CreatureEventAI::CheckEvent(), UnitAI::ExecuteActions(), and UnitConditionMgr::getConditionValue().
IsRemovedOnExpire()
virtual bool MovementGenerator::IsRemovedOnExpire () const inline virtual
Reimplemented in FollowMovementGenerator, and ChaseMovementGenerator.
Definition at line 60 of file MovementGenerator.h.
Reset()
virtual void MovementGenerator::Reset (Unit &) pure virtual
Implemented in RetreatMovementGenerator, PointMovementGenerator, PathJumpGenerator, FixedPathMovementGenerator, MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, AbstractWrapperMovementGenerator, FollowMovementGenerator, AbstractRandomMovementGenerator, AbstractPathMovementGenerator, DistractMovementGenerator, ChaseMovementGenerator, and IdleMovementGenerator.
UnitSpeedChanged()
virtual void MovementGenerator::UnitSpeedChanged () inline virtual
Reimplemented in AbstractWrapperMovementGenerator, EffectMovementGenerator, WaypointMovementGenerator< Creature >, TargetedMovementGeneratorMedium< T, D >, TargetedMovementGeneratorMedium< Unit, ChaseMovementGenerator >, TargetedMovementGeneratorMedium< Unit, FollowMovementGenerator >, PointMovementGenerator, and AbstractPathMovementGenerator.
Definition at line 52 of file MovementGenerator.h.
Update()
virtual bool MovementGenerator::Update (Unit & , const uint32 & time_diff) pure virtual
Implemented in StayMovementGenerator, RetreatMovementGenerator, TaxiMovementGenerator, PointMovementGenerator, MovementGeneratorMedium< T, D >, MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >, MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >, EffectMovementGenerator, PanicMovementGenerator, TimedWanderMovementGenerator, AbstractRandomMovementGenerator, DistractMovementGenerator, AbstractWrapperMovementGenerator, AbstractPathMovementGenerator, FormationMovementGenerator, and IdleMovementGenerator.
The documentation for this class was generated from the following files:
MovementGenerator.h
MovementGenerator.cpp