CMaNGOS_WoTLK: PoolGroup< T > Class Template Reference
PoolGroup< T > Class Template Reference
#include <PoolManager.h>
Public Member Functions
PoolGroup ()
void SetPoolId (uint32 pool_id)
~PoolGroup ()
bool isEmpty () const
void AddEntry (PoolObject &poolitem, uint32 maxentries)
bool CheckPool () const
void CheckEventLinkAndReport (int16 event_id, std::map< uint32, int16 > const &creature2event, std::map< uint32, int16 > const &go2event) const
PoolObject * RollOne (SpawnedPoolData &spawns, uint32 triggerFrom, MapPersistentState &mapState)
void DespawnObject (MapPersistentState &mapState, uint32 guid=0)
void Despawn1Object (MapPersistentState &mapState, uint32 guid)
void SpawnObject (MapPersistentState &mapState, uint32 limit, uint32 triggerFrom, bool instantly)
void SetExcludeObject (uint32 guid, bool state)
void Spawn1Object (MapPersistentState &mapState, PoolObject *obj, bool instantly)
void ReSpawn1Object (MapPersistentState &mapState, PoolObject *obj)
void RemoveOneRelation (uint16 child_pool_id)
PoolObjectList const & GetExplicitlyChanced () const
PoolObjectList const & GetEqualChanced () const
size_t size () const
void Despawn1Object (MapPersistentState &mapState, uint32 guid)
void Despawn1Object (MapPersistentState &mapState, uint32 guid)
void Despawn1Object (MapPersistentState &mapState, uint32 child_pool_id)
void RemoveOneRelation (uint16 child_pool_id)
void Spawn1Object (MapPersistentState &mapState, PoolObject *obj, bool instantly)
void Spawn1Object (MapPersistentState &mapState, PoolObject *obj, bool instantly)
void Spawn1Object (MapPersistentState &mapState, PoolObject *obj, bool instantly)
void ReSpawn1Object (MapPersistentState &mapState, PoolObject *obj)
void ReSpawn1Object (MapPersistentState &mapState, PoolObject *obj)
void ReSpawn1Object (MapPersistentState &, PoolObject *)
Private Member Functions
bool CanSpawn (PoolObject *object, MapPersistentState &mapState)
bool CanSpawn (PoolObject *object, MapPersistentState &mapState)
bool CanSpawn (PoolObject *object, MapPersistentState &mapState)
bool CanSpawn (PoolObject *object, MapPersistentState &mapState)
Private Attributes
uint32 poolId
PoolObjectList ExplicitlyChanced
PoolObjectList EqualChanced
Detailed Description
template<class T>
class PoolGroup< T >
Definition at line 99 of file PoolManager.h.
Constructor & Destructor Documentation
PoolGroup()
template<class T > PoolGroup< T >::PoolGroup () inline explicit
Definition at line 102 of file PoolManager.h.
~PoolGroup()
template<class T > PoolGroup< T >::~PoolGroup () inline
Definition at line 104 of file PoolManager.h.
Member Function Documentation
AddEntry()
template<class T > void PoolGroup< T >::AddEntry (PoolObject & poolitem, uint32 maxentries)
Definition at line 139 of file PoolManager.cpp.
References PoolObject::chance.
Referenced by PoolManager::LoadFromDB().
CanSpawn() [1/4]
bool PoolGroup< Creature >::CanSpawn (PoolObject * object, MapPersistentState & mapState) private
Definition at line 369 of file PoolManager.cpp.
References MapPersistentState::GetMap(), PoolObject::guid, and TYPEID_UNIT.
CanSpawn() [2/4]
bool PoolGroup< GameObject >::CanSpawn (PoolObject * object, MapPersistentState & mapState) private
Definition at line 377 of file PoolManager.cpp.
References MapPersistentState::GetMap(), PoolObject::guid, and TYPEID_GAMEOBJECT.
CanSpawn() [3/4]
bool PoolGroup< Pool >::CanSpawn (PoolObject * object, MapPersistentState & mapState) private
Definition at line 385 of file PoolManager.cpp.
CanSpawn() [4/4]
template<class T > bool PoolGroup< T >::CanSpawn (PoolObject * object, MapPersistentState & mapState) private
CheckEventLinkAndReport()
template<class T > void PoolGroup< T >::CheckEventLinkAndReport (int16 event_id, std::map< uint32, int16 > const & creature2event, std::map< uint32, int16 > const & go2event) const
Definition at line 164 of file PoolManager.cpp.
CheckPool()
template<class T > bool PoolGroup< T >::CheckPool
Definition at line 149 of file PoolManager.cpp.
Despawn1Object() [1/4]
void PoolGroup< Pool >::Despawn1Object (MapPersistentState & mapState, uint32 child_pool_id)
Definition at line 341 of file PoolManager.cpp.
References sPoolMgr.
Despawn1Object() [2/4]
void PoolGroup< Creature >::Despawn1Object (MapPersistentState & mapState, uint32 guid)
Definition at line 305 of file PoolManager.cpp.
References MapPersistentState::GetMapId(), sMapPersistentStateMgr, and sObjectMgr.
Despawn1Object() [3/4]
void PoolGroup< GameObject >::Despawn1Object (MapPersistentState & mapState, uint32 guid)
Definition at line 323 of file PoolManager.cpp.
References MapPersistentState::GetMapId(), sMapPersistentStateMgr, and sObjectMgr.
Despawn1Object() [4/4]
template<class T > void PoolGroup< T >::Despawn1Object (MapPersistentState & mapState, uint32 guid)
DespawnObject()
template<class T > void PoolGroup< T >::DespawnObject (MapPersistentState & mapState, uint32 guid = 0)
Definition at line 272 of file PoolManager.cpp.
References MapPersistentState::GetSpawnedPoolData(), SpawnedPoolData::IsSpawnedObject(), and SpawnedPoolData::RemoveSpawn().
GetEqualChanced()
template<class T > PoolObjectList const& PoolGroup< T >::GetEqualChanced () const inline
Definition at line 120 of file PoolManager.h.
References PoolGroup< T >::EqualChanced.
Referenced by ScriptAction::ExecuteDbscriptCommand(), ScriptAction::GetScriptProcessTargets(), and ChatHandler::HandlePoolInfoCommand().
GetExplicitlyChanced()
template<class T > PoolObjectList const& PoolGroup< T >::GetExplicitlyChanced () const inline
Definition at line 119 of file PoolManager.h.
References PoolGroup< T >::ExplicitlyChanced.
Referenced by ScriptAction::ExecuteDbscriptCommand(), ScriptAction::GetScriptProcessTargets(), and ChatHandler::HandlePoolInfoCommand().
isEmpty()
template<class T > bool PoolGroup< T >::isEmpty () const inline
Definition at line 105 of file PoolManager.h.
References PoolGroup< T >::EqualChanced, and PoolGroup< T >::ExplicitlyChanced.
RemoveOneRelation() [1/2]
void PoolGroup< Pool >::RemoveOneRelation (uint16 child_pool_id)
Definition at line 348 of file PoolManager.cpp.
RemoveOneRelation() [2/2]
template<class T > void PoolGroup< T >::RemoveOneRelation (uint16 child_pool_id)
ReSpawn1Object() [1/4]
void PoolGroup< Pool >::ReSpawn1Object (MapPersistentState & , PoolObject *)
Definition at line 558 of file PoolManager.cpp.
ReSpawn1Object() [2/4]
void PoolGroup< Creature >::ReSpawn1Object (MapPersistentState & mapState, PoolObject * obj)
Definition at line 530 of file PoolManager.cpp.
References MapPersistentState::GetMapId(), PoolObject::guid, sMapPersistentStateMgr, and sObjectMgr.
ReSpawn1Object() [3/4]
void PoolGroup< GameObject >::ReSpawn1Object (MapPersistentState & mapState, PoolObject * obj)
Definition at line 544 of file PoolManager.cpp.
References MapPersistentState::GetMapId(), PoolObject::guid, sMapPersistentStateMgr, and sObjectMgr.
ReSpawn1Object() [4/4]
template<class T > void PoolGroup< T >::ReSpawn1Object (MapPersistentState & mapState, PoolObject * obj)
RollOne()
template<class T > PoolObject * PoolGroup< T >::RollOne (SpawnedPoolData & spawns, uint32 triggerFrom, MapPersistentState & mapState)
Definition at line 196 of file PoolManager.cpp.
References GetRandomGenerator(), SpawnedPoolData::IsSpawnedObject(), and rand_chance().
SetExcludeObject()
template<class T > void PoolGroup< T >::SetExcludeObject (uint32 guid, bool state)
Definition at line 174 of file PoolManager.cpp.
SetPoolId()
template<class T > void PoolGroup< T >::SetPoolId (uint32 pool_id) inline
Definition at line 103 of file PoolManager.h.
References PoolGroup< T >::poolId.
Referenced by PoolManager::LoadFromDB().
size()
template<class T > size_t PoolGroup< T >::size () const inline
Definition at line 122 of file PoolManager.h.
References PoolGroup< T >::EqualChanced, and PoolGroup< T >::ExplicitlyChanced.
Spawn1Object() [1/4]
void PoolGroup< Creature >::Spawn1Object (MapPersistentState & mapState, PoolObject * obj, bool instantly)
Definition at line 442 of file PoolManager.cpp.
References MapPersistentState::AddCreatureToGrid(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, MapPersistentState::GetMap(), Creature::GetRespawnDelay(), PoolObject::guid, Map::IsLoaded(), Creature::IsWorldBoss(), Creature::LoadFromDB(), MapPersistentState::SaveCreatureRespawnTime(), Creature::SaveRespawnTime(), Creature::SetRespawnDelay(), Creature::SetRespawnTime(), sObjectMgr, and sWorld.
Spawn1Object() [2/4]
void PoolGroup< GameObject >::Spawn1Object (MapPersistentState & mapState, PoolObject * obj, bool instantly)
Definition at line 475 of file PoolManager.cpp.
References MapPersistentState::AddGameobjectToGrid(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, GameObject::CreateGameObject(), GameObjectInfo::ExtraFlags, GAMEOBJECT_EXTRA_FLAG_DYNGUID, ObjectMgr::GetGameObjectInfo(), MapPersistentState::GetMap(), GameObjectData::GetRandomRespawnTime(), Map::GetSpawnManager(), PoolObject::guid, GameObjectData::id, Map::IsLoaded(), GameObject::LoadFromDB(), MANGOS_ASSERT, SpawnManager::RespawnGameObject(), MapPersistentState::SaveGORespawnTime(), GameObject::SaveRespawnTime(), GameObject::SetRespawnTime(), sObjectMgr, and sWorld.
Spawn1Object() [3/4]
void PoolGroup< Pool >::Spawn1Object (MapPersistentState & mapState, PoolObject * obj, bool instantly)
Definition at line 523 of file PoolManager.cpp.
References PoolObject::guid, and sPoolMgr.
Spawn1Object() [4/4]
template<class T > void PoolGroup< T >::Spawn1Object (MapPersistentState & mapState, PoolObject * obj, bool instantly)
SpawnObject()
template<class T > void PoolGroup< T >::SpawnObject (MapPersistentState & mapState, uint32 limit, uint32 triggerFrom, bool instantly)
Definition at line 391 of file PoolManager.cpp.
References SpawnedPoolData::AddSpawn(), SpawnedPoolData::GetSpawnedObjects(), MapPersistentState::GetSpawnedPoolData(), PoolObject::guid, SpawnedPoolData::IsSpawnedObject(), and MANGOS_ASSERT.
Field Documentation
EqualChanced
template<class T > PoolObjectList PoolGroup< T >::EqualChanced private
Definition at line 128 of file PoolManager.h.
Referenced by PoolGroup< T >::GetEqualChanced(), PoolGroup< T >::isEmpty(), and PoolGroup< T >::size().
ExplicitlyChanced
template<class T > PoolObjectList PoolGroup< T >::ExplicitlyChanced private
Definition at line 127 of file PoolManager.h.
Referenced by PoolGroup< T >::GetExplicitlyChanced(), PoolGroup< T >::isEmpty(), and PoolGroup< T >::size().
poolId
template<class T > uint32 PoolGroup< T >::poolId private
Definition at line 126 of file PoolManager.h.
Referenced by PoolGroup< T >::SetPoolId().
The documentation for this class was generated from the following files:
PoolManager.h
PoolManager.cpp