CMaNGOS_WoTLK: TerrainManager Class Reference
TerrainManager Class Reference
#include <GridMap.h>
Public Member Functions
TerrainInfo * LoadTerrain (const uint32 mapId)
void UnloadTerrain (const uint32 mapId)
void Update (const uint32 diff)
void UnloadAll ()
uint16 GetAreaFlag (uint32 mapid, float x, float y, float z) const
uint32 GetAreaId (uint32 mapid, float x, float y, float z) const
uint32 GetZoneId (uint32 mapid, float x, float y, float z) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid, uint32 mapid, float x, float y, float z) const
Static Public Member Functions
static uint32 GetAreaIdByAreaFlag (uint16 areaflag, uint32 map_id)
static uint32 GetZoneIdByAreaFlag (uint16 areaflag, uint32 map_id)
static void GetZoneAndAreaIdByAreaFlag (uint32 &zoneid, uint32 &areaid, uint16 areaflag, uint32 map_id)
Static Public Member Functions inherited from MaNGOS::Singleton< TerrainManager, MaNGOS::ClassLevelLockable< TerrainManager, std::mutex > >
static TerrainManager & Instance ()
Private Types
typedef std::unordered_map< uint32, TerrainInfo * > TerrainDataMap
typedef MaNGOS::ClassLevelLockable< TerrainManager, std::mutex >::Lock Guard
Private Member Functions
TerrainManager ()
~TerrainManager ()
TerrainManager (const TerrainManager &)
TerrainManager & operator= (const TerrainManager &)
Private Attributes
TerrainDataMap i_TerrainMap
Friends
class MaNGOS::OperatorNew< TerrainManager >
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Singleton< TerrainManager, MaNGOS::ClassLevelLockable< TerrainManager, std::mutex > >
Singleton ()
Detailed Description
Definition at line 213 of file GridMap.h.
Member Typedef Documentation
Guard
typedef MaNGOS::ClassLevelLockable<TerrainManager, std::mutex>::Lock TerrainManager::Guard private
Definition at line 254 of file GridMap.h.
TerrainDataMap
typedef std::unordered_map<uint32, TerrainInfo*> TerrainManager::TerrainDataMap private
Definition at line 215 of file GridMap.h.
Constructor & Destructor Documentation
TerrainManager() [1/2]
TerrainManager::TerrainManager () private
Definition at line 1417 of file GridMap.cpp.
~TerrainManager()
TerrainManager::~TerrainManager () private
Definition at line 1421 of file GridMap.cpp.
References i_TerrainMap.
TerrainManager() [2/2]
TerrainManager::TerrainManager (const TerrainManager &) private
Member Function Documentation
GetAreaFlag()
uint16 TerrainManager::GetAreaFlag (uint32 mapid, float x, float y, float z) const inline
Definition at line 225 of file GridMap.h.
References TerrainInfo::GetAreaFlag(), and LoadTerrain().
Referenced by GetAreaId(), GetZoneAndAreaId(), and GetZoneId().
GetAreaId()
uint32 TerrainManager::GetAreaId (uint32 mapid, float x, float y, float z) const inline
Definition at line 230 of file GridMap.h.
References GetAreaFlag(), and GetAreaIdByAreaFlag().
GetAreaIdByAreaFlag()
uint32 TerrainManager::GetAreaIdByAreaFlag (uint16 areaflag, uint32 map_id) static
Definition at line 1476 of file GridMap.cpp.
References GetAreaEntryByAreaFlagAndMap(), and AreaTableEntry::ID.
Referenced by TerrainInfo::GetAreaId(), and GetAreaId().
GetZoneAndAreaId()
void TerrainManager::GetZoneAndAreaId (uint32 & zoneid, uint32 & areaid, uint32 mapid, float x, float y, float z) const inline
Definition at line 238 of file GridMap.h.
References GetAreaFlag(), and GetZoneAndAreaIdByAreaFlag().
GetZoneAndAreaIdByAreaFlag()
void TerrainManager::GetZoneAndAreaIdByAreaFlag (uint32 & zoneid, uint32 & areaid, uint16 areaflag, uint32 map_id) static
Definition at line 1494 of file GridMap.cpp.
References GetAreaEntryByAreaFlagAndMap(), AreaTableEntry::ID, and AreaTableEntry::zone.
Referenced by TerrainInfo::GetZoneAndAreaId(), and GetZoneAndAreaId().
GetZoneId()
uint32 TerrainManager::GetZoneId (uint32 mapid, float x, float y, float z) const inline
Definition at line 234 of file GridMap.h.
References GetAreaFlag(), and GetZoneIdByAreaFlag().
GetZoneIdByAreaFlag()
uint32 TerrainManager::GetZoneIdByAreaFlag (uint16 areaflag, uint32 map_id) static
Definition at line 1485 of file GridMap.cpp.
References GetAreaEntryByAreaFlagAndMap(), AreaTableEntry::ID, and AreaTableEntry::zone.
Referenced by TerrainInfo::GetZoneId(), and GetZoneId().
LoadTerrain()
TerrainInfo * TerrainManager::LoadTerrain (const uint32 mapId)
Definition at line 1427 of file GridMap.cpp.
References i_TerrainMap.
Referenced by GetAreaFlag().
operator=()
TerrainManager& TerrainManager::operator= (const TerrainManager &) private
UnloadAll()
void TerrainManager::UnloadAll ()
Definition at line 1468 of file GridMap.cpp.
References i_TerrainMap.
Referenced by MapManager::UnloadAll().
UnloadTerrain()
void TerrainManager::UnloadTerrain (const uint32 mapId)
Definition at line 1441 of file GridMap.cpp.
References CONFIG_BOOL_GRID_UNLOAD, i_TerrainMap, Referencable< Countable >::IsReferenced(), and sWorld.
Update()
void TerrainManager::Update (const uint32 diff)
Definition at line 1461 of file GridMap.cpp.
References i_TerrainMap.
Friends And Related Function Documentation
MaNGOS::OperatorNew< TerrainManager >
friend class MaNGOS::OperatorNew< TerrainManager > friend
Definition at line 215 of file GridMap.h.
Field Documentation
i_TerrainMap
TerrainDataMap TerrainManager::i_TerrainMap private
Definition at line 255 of file GridMap.h.
Referenced by LoadTerrain(), UnloadAll(), UnloadTerrain(), Update(), and ~TerrainManager().
The documentation for this class was generated from the following files:
GridMap.h
GridMap.cpp