CMaNGOS_WoTLK: MaNGOS::GameObjectFocusCheck Class Reference
MaNGOS::GameObjectFocusCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
GameObjectFocusCheck (WorldObject const *unit, uint32 focusId)
WorldObject const & GetFocusObject () const
bool operator() (GameObject *go) const
Private Attributes
WorldObject const * i_object
uint32 i_focusId
Detailed Description
Definition at line 694 of file GridNotifiers.h.
Constructor & Destructor Documentation
GameObjectFocusCheck()
MaNGOS::GameObjectFocusCheck::GameObjectFocusCheck (WorldObject const * unit, uint32 focusId) inline
Definition at line 697 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::GameObjectFocusCheck::GetFocusObject () const inline
Definition at line 698 of file GridNotifiers.h.
References i_object.
operator()()
bool MaNGOS::GameObjectFocusCheck::operator() (GameObject * go) const inline
Definition at line 699 of file GridNotifiers.h.
References GAMEOBJECT_TYPE_SPELL_FOCUS, GameObject::GetGOInfo(), i_focusId, i_object, GameObject::IsSpawned(), WorldObject::IsWithinDistInMap(), GameObjectInfo::spellFocus, and GameObjectInfo::type.
Field Documentation
i_focusId
uint32 MaNGOS::GameObjectFocusCheck::i_focusId private
Definition at line 717 of file GridNotifiers.h.
Referenced by operator()().
i_object
WorldObject const* MaNGOS::GameObjectFocusCheck::i_object private
Definition at line 716 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h