CMaNGOS_WoTLK: instance_dark_portal Class Reference
instance_dark_portal Class Reference
#include <dark_portal.h>
Public Member Functions
instance_dark_portal (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature)
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void DoHandleAreaTrigger (uint32 uiTriggerId)
uint32 GetCurrentRiftId () const
void Update (const uint32 diff) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
bool IsBossTimeRift () const
void UpdateWorldState (bool bEnable=true)
void DoSpawnNextPortal ()
void DoResetEvent ()
void StartPostEvent ()
void ExecutePostEventStep ()
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiWorldState
uint32 m_uiWorldStateRiftCount
uint32 m_uiWorldStateShieldCount
uint32 m_uiSummonedCrystalCount
bool m_bHasIntroYelled
uint32 m_uiMedivhYellCount
uint32 m_uiNextPortalTimer
uint32 m_uiSummonCrystalTimer
uint32 m_uiSummonBeamStalkerTimer
uint8 m_uiCurrentRiftId
uint32 m_uiPostEventTimer
uint8 m_uiPostEventStep
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 121 of file dark_portal.h.
Constructor & Destructor Documentation
instance_dark_portal()
instance_dark_portal::instance_dark_portal (Map * pMap)
Definition at line 27 of file dark_portal.cpp.
References Initialize().
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_dark_portal::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override private virtual
Reimplemented from InstanceData.
Definition at line 553 of file dark_portal.cpp.
References GetData(), Object::GetGuidStr(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, INSTANCE_CONDITION_ID_SAAT_BEACON, NPC_MEDIVH, script_error_log(), and TYPE_MEDIVH.
DoHandleAreaTrigger()
void instance_dark_portal::DoHandleAreaTrigger (uint32 uiTriggerId)
Definition at line 78 of file dark_portal.cpp.
References AREATRIGGER_ENTER, AREATRIGGER_MEDIVH, DoScriptText(), FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_bHasIntroYelled, NOT_STARTED, NPC_SAAT, SAY_SAAT_WELCOME, SetData(), and TYPE_MEDIVH.
DoResetEvent()
void instance_dark_portal::DoResetEvent () private
Definition at line 49 of file dark_portal.cpp.
References m_uiCurrentRiftId, m_uiMedivhYellCount, m_uiNextPortalTimer, m_uiSummonBeamStalkerTimer, m_uiSummonCrystalTimer, m_uiSummonedCrystalCount, m_uiWorldStateRiftCount, m_uiWorldStateShieldCount, and UpdateWorldState().
Referenced by SetData().
DoSpawnNextPortal()
void instance_dark_portal::DoSpawnNextPortal () private
Definition at line 353 of file dark_portal.cpp.
References afPortalLocation, debug_log(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiCurrentRiftId, NPC_MEDIVH, NPC_TIME_RIFT, TEMPSPAWN_CORPSE_DESPAWN, and urand().
Referenced by ExecuteChatCommand(), and Update().
ExecuteChatCommand()
void instance_dark_portal::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 604 of file dark_portal.cpp.
References DoSpawnNextPortal(), ScriptedInstance::DoUpdateWorldState(), ChatHandler::ExtractLiteralArg(), ChatHandler::ExtractUInt32(), m_uiWorldStateRiftCount, ChatHandler::PSendSysMessage(), and WORLD_STATE_OPENING_THE_DARK_PORTAL_RIFT_STATE.
ExecutePostEventStep()
void instance_dark_portal::ExecutePostEventStep () private
Definition at line 398 of file dark_portal.cpp.
References ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_DARK_PORTAL, m_uiPostEventStep, m_uiPostEventTimer, NPC_COUNCIL_ENFORCER, NPC_MEDIVH, POST_EVENT_1_MEDIVH_YELL, POST_EVENT_2_MEDIVH_NPCFLAGS, POST_EVENT_3_SUMMON_ORCS_1, POST_EVENT_4_SUMMON_ORCS_2, POST_EVENT_5_SUMMON_ORCS_3, POST_EVENT_6_SUMMON_ORCS_4, SAY_MEDIVH_WIN, TEMPSPAWN_DEAD_DESPAWN, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and WEEK.
Referenced by Update().
GetCurrentRiftId()
uint32 instance_dark_portal::GetCurrentRiftId () const inline
Definition at line 144 of file dark_portal.h.
References m_uiWorldStateRiftCount.
Referenced by npc_time_riftAI::npc_time_riftAI(), and npc_time_riftAI::SummonedCreatureJustDied().
GetData()
uint32 instance_dark_portal::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 240 of file dark_portal.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by CheckConditionCriteriaMeet(), DoHandleAreaTrigger(), npc_time_riftAI::DoSummon(), and Update().
Initialize()
void instance_dark_portal::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 44 of file dark_portal.cpp.
References m_auiEncounter.
Referenced by instance_dark_portal().
IsBossTimeRift()
bool instance_dark_portal::IsBossTimeRift () const inline private
Definition at line 152 of file dark_portal.h.
References m_uiWorldStateRiftCount.
Referenced by SetData().
Load()
void instance_dark_portal::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 248 of file dark_portal.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_dark_portal::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 98 of file dark_portal.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, NPC_DARK_PORTAL_DUMMY, NPC_MEDIVH, and NPC_SAAT.
OnCreatureDeath()
void instance_dark_portal::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 335 of file dark_portal.cpp.
References DONE, Object::GetEntry(), NPC_AEONUS, NPC_CHRONO_LORD, NPC_CHRONO_LORD_DEJA, NPC_TEMPORUS, NPC_TIMEREAVER, SetData(), TYPE_AEONUS, TYPE_CHRONO_LORD, and TYPE_TEMPORUS.
OnCreatureEnterCombat()
void instance_dark_portal::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 271 of file dark_portal.cpp.
References Object::GetEntry(), IN_PROGRESS, Unit::InterruptNonMeleeSpells(), NPC_AEONUS, NPC_ASSASSIN, NPC_ASSASSIN_2, NPC_CHRONO_LORD, NPC_CHRONO_LORD_DEJA, NPC_CHRONOMANCER, NPC_CHRONOMANCER_2, NPC_EXECUTIONER, NPC_EXECUTIONER_2, NPC_TEMPORUS, NPC_TIMEREAVER, NPC_VANQUISHER, NPC_VANQUISHER_2, NPC_WHELP, SetData(), TYPE_AEONUS, TYPE_CHRONO_LORD, and TYPE_TEMPORUS.
OnCreatureEvade()
void instance_dark_portal::OnCreatureEvade (Creature * pCreature) virtual
Reimplemented from InstanceData.
Definition at line 300 of file dark_portal.cpp.
References FAIL, Object::GetEntry(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), MotionMaster::MovePoint(), NPC_AEONUS, NPC_ASSASSIN, NPC_ASSASSIN_2, NPC_CHRONO_LORD, NPC_CHRONO_LORD_DEJA, NPC_CHRONOMANCER, NPC_CHRONOMANCER_2, NPC_EXECUTIONER, NPC_EXECUTIONER_2, NPC_MEDIVH, NPC_TEMPORUS, NPC_TIMEREAVER, NPC_VANQUISHER, NPC_VANQUISHER_2, NPC_WHELP, SetData(), TYPE_AEONUS, TYPE_CHRONO_LORD, and TYPE_TEMPORUS.
OnObjectCreate()
void instance_dark_portal::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 110 of file dark_portal.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_DARK_PORTAL, and ScriptedInstance::m_goEntryGuidStore.
OnPlayerEnter()
void instance_dark_portal::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 73 of file dark_portal.cpp.
References IN_PROGRESS, m_auiEncounter, TYPE_MEDIVH, and UpdateWorldState().
Save()
const char* instance_dark_portal::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 139 of file dark_portal.h.
References m_strInstData.
SetData()
void instance_dark_portal::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 120 of file dark_portal.cpp.
References DONE, DoResetEvent(), DoScriptText(), ScriptedInstance::DoUpdateWorldState(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, IsBossTimeRift(), m_auiEncounter, m_strInstData, m_uiMedivhYellCount, m_uiNextPortalTimer, m_uiSummonBeamStalkerTimer, m_uiSummonCrystalTimer, m_uiWorldStateRiftCount, m_uiWorldStateShieldCount, MINUTE, NPC_DARK_PORTAL_DUMMY, NPC_MEDIVH, NPC_SAAT, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_MEDIVH_ENTER, SPECIAL, SPELL_CRYSTAL_SHATTER, StartPostEvent(), TRIGGERED_OLD_TRIGGERED, TYPE_AEONUS, TYPE_CHRONO_LORD, TYPE_MEDIVH, TYPE_SHIELD, TYPE_TEMPORUS, TYPE_TIME_RIFT, uiMedivhWeakYell, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, UpdateWorldState(), and WORLD_STATE_OPENING_THE_DARK_PORTAL_SHIELD_STATE.
Referenced by DoHandleAreaTrigger(), npc_time_riftAI::DoSummon(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), and npc_time_riftAI::SummonedCreatureJustDied().
ShowChatCommands()
void instance_dark_portal::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 599 of file dark_portal.cpp.
References ChatHandler::SendSysMessage().
StartPostEvent()
void instance_dark_portal::StartPostEvent () private
Definition at line 372 of file dark_portal.cpp.
References MapRefManager::begin(), MapRefManager::end(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, LinkedListHead::isEmpty(), m_uiPostEventStep, m_uiPostEventTimer, NPC_MEDIVH, POST_EVENT_1_MEDIVH_YELL, QUEST_MASTER_TOUCH, QUEST_OPENING_PORTAL, and QUEST_STATUS_INCOMPLETE.
Referenced by SetData().
Update()
void instance_dark_portal::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 490 of file dark_portal.cpp.
References DONE, DoSpawnNextPortal(), ScriptedInstance::DoUpdateWorldState(), ExecutePostEventStep(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_uiNextPortalTimer, m_uiPostEventTimer, m_uiSummonBeamStalkerTimer, m_uiSummonCrystalTimer, m_uiSummonedCrystalCount, m_uiWorldStateRiftCount, MAX_CRYSTALS, NPC_DARK_PORTAL_DUMMY, SPELL_PORTAL_BEAM, SPELL_PORTAL_CRYSTAL, TRIGGERED_OLD_TRIGGERED, TYPE_MEDIVH, urand(), and WORLD_STATE_OPENING_THE_DARK_PORTAL_RIFT_STATE.
UpdateWorldState()
void instance_dark_portal::UpdateWorldState (bool bEnable = true) private
Definition at line 64 of file dark_portal.cpp.
References ScriptedInstance::DoUpdateWorldState(), m_uiWorldState, m_uiWorldStateRiftCount, m_uiWorldStateShieldCount, WORLD_STATE_OPENING_THE_DARK_PORTAL_IS_ACTIVE, WORLD_STATE_OPENING_THE_DARK_PORTAL_RIFT_STATE, and WORLD_STATE_OPENING_THE_DARK_PORTAL_SHIELD_STATE.
Referenced by DoResetEvent(), OnPlayerEnter(), and SetData().
Field Documentation
m_auiEncounter
uint32 instance_dark_portal::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 160 of file dark_portal.h.
Referenced by GetData(), Initialize(), Load(), OnPlayerEnter(), and SetData().
m_bHasIntroYelled
bool instance_dark_portal::m_bHasIntroYelled private
Definition at line 168 of file dark_portal.h.
Referenced by DoHandleAreaTrigger().
m_strInstData
std::string instance_dark_portal::m_strInstData private
Definition at line 161 of file dark_portal.h.
Referenced by Save(), and SetData().
m_uiCurrentRiftId
uint8 instance_dark_portal::m_uiCurrentRiftId private
Definition at line 174 of file dark_portal.h.
Referenced by DoResetEvent(), and DoSpawnNextPortal().
m_uiMedivhYellCount
uint32 instance_dark_portal::m_uiMedivhYellCount private
Definition at line 169 of file dark_portal.h.
Referenced by DoResetEvent(), and SetData().
m_uiNextPortalTimer
uint32 instance_dark_portal::m_uiNextPortalTimer private
Definition at line 171 of file dark_portal.h.
Referenced by DoResetEvent(), SetData(), and Update().
m_uiPostEventStep
uint8 instance_dark_portal::m_uiPostEventStep private
Definition at line 177 of file dark_portal.h.
Referenced by ExecutePostEventStep(), and StartPostEvent().
m_uiPostEventTimer
uint32 instance_dark_portal::m_uiPostEventTimer private
Definition at line 176 of file dark_portal.h.
Referenced by ExecutePostEventStep(), StartPostEvent(), and Update().
m_uiSummonBeamStalkerTimer
uint32 instance_dark_portal::m_uiSummonBeamStalkerTimer private
Definition at line 173 of file dark_portal.h.
Referenced by DoResetEvent(), SetData(), and Update().
m_uiSummonCrystalTimer
uint32 instance_dark_portal::m_uiSummonCrystalTimer private
Definition at line 172 of file dark_portal.h.
Referenced by DoResetEvent(), SetData(), and Update().
m_uiSummonedCrystalCount
uint32 instance_dark_portal::m_uiSummonedCrystalCount private
Definition at line 166 of file dark_portal.h.
Referenced by DoResetEvent(), and Update().
m_uiWorldState
uint32 instance_dark_portal::m_uiWorldState private
Definition at line 163 of file dark_portal.h.
Referenced by UpdateWorldState().
m_uiWorldStateRiftCount
uint32 instance_dark_portal::m_uiWorldStateRiftCount private
Definition at line 164 of file dark_portal.h.
Referenced by DoResetEvent(), ExecuteChatCommand(), GetCurrentRiftId(), IsBossTimeRift(), SetData(), Update(), and UpdateWorldState().
m_uiWorldStateShieldCount
uint32 instance_dark_portal::m_uiWorldStateShieldCount private
Definition at line 165 of file dark_portal.h.
Referenced by DoResetEvent(), SetData(), and UpdateWorldState().
The documentation for this class was generated from the following files:
dark_portal.h
dark_portal.cpp