CMaNGOS_WoTLK: LfgRaidBrowser Class Reference
LfgRaidBrowser Class Reference
#include <LFGQueue.h>
Public Member Functions
WorldPacket BuildSearchResults (uint32 dungeonId, uint32 team)
void AddListener (uint32 dungeonId, uint32 team, ObjectGuid guid)
void RemoveListener (uint32 dungeonId, uint32 team, ObjectGuid guid)
void AddListed (LFGQueueData const &data)
void RemoveListed (ObjectGuid guid)
void SetPlayerRoles (ObjectGuid group, ObjectGuid player, uint8 roles)
void UpdateComment (ObjectGuid guid, std::string comment)
void Update (World *world)
Private Member Functions
void ProcessDungeons (LfgDungeonSet const &dungeons, uint32 team, ObjectGuid guid)
Private Attributes
std::map< ObjectGuid, LFGQueueData > m_listed
std::map< std::pair< uint32, uint32 >, ListedContainer > m_listedPerDungeon
std::map< std::pair< uint32, uint32 >, bool > m_changed
std::map< std::pair< uint32, uint32 >, std::vector< ObjectGuid > > m_listeners
Detailed Description
Definition at line 165 of file LFGQueue.h.
Member Function Documentation
AddListed()
void LfgRaidBrowser::AddListed (LFGQueueData const & data)
Definition at line 762 of file LFGQueue.cpp.
References LFG_STATE_RAIDBROWSER, LFGQueueData::m_dungeons, LFGQueueData::m_leaderGuid, m_listed, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, LFGQueueData::m_state, LFGQueueData::m_team, ProcessDungeons(), and LFGQueueData::UpdateRoleCheck().
AddListener()
void LfgRaidBrowser::AddListener (uint32 dungeonId, uint32 team, ObjectGuid guid)
Definition at line 745 of file LFGQueue.cpp.
References BuildSearchResults(), ObjectAccessor::FindPlayer(), m_changed, and m_listeners.
BuildSearchResults()
WorldPacket LfgRaidBrowser::BuildSearchResults (uint32 dungeonId, uint32 team)
Definition at line 601 of file LFGQueue.cpp.
References ObjectGuid::IsGroup(), LFG_TYPE_RAID, LFGQueuePlayer::m_class, LFGQueueData::m_comment, ListedContainer::m_groups, LFGQueueData::m_leaderGuid, LFGQueuePlayer::m_level, m_listed, m_listedPerDungeon, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, ListedContainer::m_players, ListedContainer::m_playerToGroup, LFGQueuePlayer::m_race, LFGQueuePlayer::m_roles, LFGQueueData::m_roles, LFGQueueData::m_savedMap, RAID_BROWSER_FLAG_AREAID, RAID_BROWSER_FLAG_COMMENT, RAID_BROWSER_FLAG_GROUP_GUID, RAID_BROWSER_FLAG_GROUP_LEADER, RAID_BROWSER_FLAG_PLAYER_STATS, RAID_BROWSER_FLAG_ROLES, RAID_BROWSER_FLAG_SAVE, RAID_BROWSER_FLAG_STATUS, and SMSG_LFG_SEARCH_RESULTS.
Referenced by AddListener(), and Update().
ProcessDungeons()
void LfgRaidBrowser::ProcessDungeons (LfgDungeonSet const & dungeons, uint32 team, ObjectGuid guid) private
Definition at line 855 of file LFGQueue.cpp.
References ObjectGuid::IsPlayer(), m_changed, ListedContainer::m_groups, m_listed, m_listedPerDungeon, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, ListedContainer::m_players, and ListedContainer::m_playerToGroup.
Referenced by AddListed(), and Update().
RemoveListed()
void LfgRaidBrowser::RemoveListed (ObjectGuid guid)
Definition at line 772 of file LFGQueue.cpp.
References ObjectGuid::IsPlayer(), m_changed, LFGQueueData::m_dungeons, ListedContainer::m_groups, m_listed, m_listedPerDungeon, LFGQueueData::m_playerInfoPerGuid, ListedContainer::m_players, ListedContainer::m_playerToGroup, and LFGQueueData::m_team.
RemoveListener()
void LfgRaidBrowser::RemoveListener (uint32 dungeonId, uint32 team, ObjectGuid guid)
Definition at line 756 of file LFGQueue.cpp.
References m_listeners.
SetPlayerRoles()
void LfgRaidBrowser::SetPlayerRoles (ObjectGuid group, ObjectGuid player, uint8 roles)
Definition at line 801 of file LFGQueue.cpp.
References m_listed.
Update()
void LfgRaidBrowser::Update (World * world)
Definition at line 819 of file LFGQueue.cpp.
References BuildSearchResults(), ObjectAccessor::FindPlayer(), Player::GetSession(), LFG_ROLECHECK_DEFAULT, LFG_ROLECHECK_FINISHED, LFG_STATE_RAIDBROWSER, m_changed, LFGQueueData::m_dungeons, m_listed, m_listeners, LFGQueueData::m_ownerGuid, LFGQueueData::m_roleCheckState, LFGQueueData::m_state, LFGQueueData::m_team, ProcessDungeons(), and WorldSession::SendPacket().
Referenced by World::Update().
UpdateComment()
void LfgRaidBrowser::UpdateComment (ObjectGuid guid, std::string comment)
Definition at line 808 of file LFGQueue.cpp.
References m_changed, and m_listed.
Field Documentation
m_changed
std::map<std::pair<uint32, uint32>, bool> LfgRaidBrowser::m_changed private
Definition at line 184 of file LFGQueue.h.
Referenced by AddListener(), ProcessDungeons(), RemoveListed(), Update(), and UpdateComment().
m_listed
std::map<ObjectGuid, LFGQueueData> LfgRaidBrowser::m_listed private
Definition at line 182 of file LFGQueue.h.
Referenced by AddListed(), BuildSearchResults(), ProcessDungeons(), RemoveListed(), SetPlayerRoles(), Update(), and UpdateComment().
m_listedPerDungeon
std::map<std::pair<uint32, uint32>, ListedContainer> LfgRaidBrowser::m_listedPerDungeon private
Definition at line 183 of file LFGQueue.h.
Referenced by BuildSearchResults(), ProcessDungeons(), and RemoveListed().
m_listeners
std::map<std::pair<uint32, uint32>, std::vector<ObjectGuid> > LfgRaidBrowser::m_listeners private
Definition at line 185 of file LFGQueue.h.
Referenced by AddListener(), RemoveListener(), and Update().
The documentation for this class was generated from the following files:
LFGQueue.h
LFGQueue.cpp