CMaNGOS_WoTLK: PlayerMenu Class Reference
PlayerMenu Class Reference
#include <GossipDef.h>
Public Member Functions
PlayerMenu (WorldSession *session)
~PlayerMenu ()
GossipMenu & GetGossipMenu ()
QuestMenu & GetQuestMenu ()
WorldSession * GetMenuSession () const
bool Empty () const
void ClearMenus ()
uint32 GossipOptionSender (unsigned int Selection)
uint32 GossipOptionAction (unsigned int Selection)
bool GossipOptionCoded (unsigned int Selection)
void SendGossipMenu (uint32 TitleTextId, ObjectGuid objectGuid)
void CloseGossip () const
void SendPointOfInterest (float X, float Y, uint32 Icon, uint32 Flags, uint32 Data, const char *locName) const
void SendPointOfInterest (uint32 poi_id) const
void SendQuestGiverStatus (uint8 questStatus, ObjectGuid npcGUID) const
void SendQuestGiverQuestList (QEmote eEmote, const std::string &Title, ObjectGuid npcGUID)
void SendQuestGiverQuestDetails (Quest const *pQuest, ObjectGuid guid, bool ActivateAccept) const
void SendQuestGiverOfferReward (Quest const *pQuest, ObjectGuid npcGUID, bool EnableNext) const
void SendQuestGiverRequestItems (Quest const *pQuest, ObjectGuid npcGUID, bool Completable, bool CloseOnCancel) const
Private Attributes
GossipMenu mGossipMenu
QuestMenu mQuestMenu
Detailed Description
Definition at line 266 of file GossipDef.h.
Constructor & Destructor Documentation
PlayerMenu()
PlayerMenu::PlayerMenu (WorldSession * session) explicit
Definition at line 124 of file GossipDef.cpp.
~PlayerMenu()
PlayerMenu::~PlayerMenu ()
Definition at line 128 of file GossipDef.cpp.
References ClearMenus().
Member Function Documentation
ClearMenus()
void PlayerMenu::ClearMenus ()
Definition at line 133 of file GossipDef.cpp.
References GossipMenu::ClearMenu(), QuestMenu::ClearMenu(), mGossipMenu, and mQuestMenu.
Referenced by Creature::CanInteractWithBattleMaster(), ScriptDevAIMgr::GetDialogStatus(), Creature::IsTrainerOf(), ScriptDevAIMgr::OnGossipHello(), ScriptDevAIMgr::OnGossipSelect(), ScriptDevAIMgr::OnQuestAccept(), ScriptDevAIMgr::OnQuestRewarded(), and ~PlayerMenu().
CloseGossip()
void PlayerMenu::CloseGossip () const
Definition at line 198 of file GossipDef.cpp.
References GetMenuSession(), WorldSession::SendPacket(), and SMSG_GOSSIP_COMPLETE.
Referenced by WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestgiverCancel(), WorldSession::HandleQuestgiverQueryQuestOpcode(), Player::OnGossipSelect(), and WorldSession::SendBindPoint().
Empty()
bool PlayerMenu::Empty () const inline
Definition at line 281 of file GossipDef.h.
References GossipMenu::Empty(), QuestMenu::Empty(), mGossipMenu, and mQuestMenu.
GetGossipMenu()
GossipMenu& PlayerMenu::GetGossipMenu () inline
Definition at line 276 of file GossipDef.h.
References mGossipMenu.
GetMenuSession()
WorldSession* PlayerMenu::GetMenuSession () const inline
Definition at line 279 of file GossipDef.h.
References GossipMenu::GetMenuSession(), and mGossipMenu.
Referenced by CloseGossip(), SendGossipMenu(), SendPointOfInterest(), SendQuestGiverOfferReward(), SendQuestGiverQuestDetails(), SendQuestGiverQuestList(), SendQuestGiverRequestItems(), and SendQuestGiverStatus().
GetQuestMenu()
QuestMenu& PlayerMenu::GetQuestMenu () inline
Definition at line 277 of file GossipDef.h.
References mQuestMenu.
Referenced by PlayerbotAI::CastSpell(), PlayerbotAI::HandleCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), PlayerbotAI::ListQuests(), and PlayerbotAI::TurnInQuests().
GossipOptionAction()
uint32 PlayerMenu::GossipOptionAction (unsigned int Selection)
Definition at line 144 of file GossipDef.cpp.
References GossipMenu::MenuItemAction(), and mGossipMenu.
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
GossipOptionCoded()
bool PlayerMenu::GossipOptionCoded (unsigned int Selection)
Definition at line 149 of file GossipDef.cpp.
References GossipMenu::MenuItemCoded(), and mGossipMenu.
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
GossipOptionSender()
uint32 PlayerMenu::GossipOptionSender (unsigned int Selection)
Definition at line 139 of file GossipDef.cpp.
References GossipMenu::MenuItemSender(), and mGossipMenu.
Referenced by WorldSession::HandleGossipSelectOptionOpcode().
SendGossipMenu()
void PlayerMenu::SendGossipMenu (uint32 TitleTextId, ObjectGuid objectGuid)
Definition at line 154 of file GossipDef.cpp.
References DEBUG_LOG, QuestMenu::GetItem(), GossipMenu::GetItem(), GossipMenu::GetMenuId(), GetMenuSession(), Quest::GetQuestFlags(), Quest::GetQuestLevel(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), Quest::GetTitle(), Quest::IsAutoComplete(), Quest::IsDailyOrWeekly(), Quest::IsMonthly(), Quest::IsRepeatable(), GossipMenuItem::m_gBoxMessage, GossipMenuItem::m_gBoxMoney, GossipMenuItem::m_gCoded, GossipMenuItem::m_gIcon, GossipMenuItem::m_gMessage, QuestMenuItem::m_qIcon, QuestMenuItem::m_qId, GossipMenu::MenuItemCount(), QuestMenu::MenuItemCount(), mGossipMenu, mQuestMenu, WorldSession::SendPacket(), SMSG_GOSSIP_MESSAGE, and sObjectMgr.
Referenced by Creature::CanInteractWithBattleMaster(), GossipHello_example_gossip_codebox(), and Creature::IsTrainerOf().
SendPointOfInterest() [1/2]
void PlayerMenu::SendPointOfInterest (float X, float Y, uint32 Icon, uint32 Flags, uint32 Data, const char * locName) const
Definition at line 207 of file GossipDef.cpp.
References GetMenuSession(), WorldSession::SendPacket(), and SMSG_GOSSIP_POI.
Referenced by ChatHandler::HandleDebugSendPoiCommand().
SendPointOfInterest() [2/2]
void PlayerMenu::SendPointOfInterest (uint32 poi_id) const
Definition at line 221 of file GossipDef.cpp.
References PointOfInterest::data, PointOfInterest::flags, GetMenuSession(), WorldSession::GetSessionDbLocaleIndex(), PointOfInterest::icon, PointOfInterest::icon_name, WorldSession::SendPacket(), sLog, SMSG_GOSSIP_POI, sObjectMgr, PointOfInterest::x, and PointOfInterest::y.
SendQuestGiverOfferReward()
void PlayerMenu::SendQuestGiverOfferReward (Quest const * pQuest, ObjectGuid npcGUID, bool EnableNext) const
Definition at line 464 of file GossipDef.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, ItemPrototype::DisplayInfoID, Quest::GetBonusTalents(), Quest::GetCharTitleId(), ObjectMgr::GetItemPrototype(), GetMenuSession(), Quest::GetOfferRewardText(), Quest::GetQuestFlags(), Quest::GetQuestId(), Quest::GetRewChoiceItemsCount(), Quest::GetRewHonorAddition(), Quest::GetRewHonorMultiplier(), Quest::GetRewItemsCount(), Quest::GetRewMoneyMaxLevel(), Quest::GetRewOrReqMoney(), Quest::GetRewSpell(), Quest::GetRewSpellCast(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), Quest::GetSuggestedPlayers(), Quest::GetTitle(), Quest::GetXPReward(), MaNGOS::Honor::hk_honor_at_level(), Quest::OfferRewardEmote, Quest::OfferRewardEmoteDelay, QUEST_REPUTATIONS_COUNT, Quest::RewChoiceItemCount, Quest::RewChoiceItemId, Quest::RewItemCount, Quest::RewItemId, Quest::RewRepFaction, Quest::RewRepValueId, WorldSession::SendPacket(), SMSG_QUESTGIVER_OFFER_REWARD, sObjectMgr, and sWorld.
Referenced by WorldSession::HandleQuestgiverChooseRewardOpcode(), WorldSession::HandleQuestgiverCompleteQuest(), WorldSession::HandleQuestgiverRequestRewardOpcode(), and SendQuestGiverRequestItems().
SendQuestGiverQuestDetails()
void PlayerMenu::SendQuestGiverQuestDetails (Quest const * pQuest, ObjectGuid guid, bool ActivateAccept) const
Definition at line 339 of file GossipDef.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, DEBUG_LOG, Quest::DetailsEmote, Quest::DetailsEmoteDelay, ItemPrototype::DisplayInfoID, Quest::GetBonusTalents(), Quest::GetCharTitleId(), Quest::GetDetails(), Quest::GetDetailsEmoteCount(), ObjectMgr::GetItemPrototype(), GetMenuSession(), Quest::GetObjectives(), Quest::GetQuestFlags(), Quest::GetQuestId(), Quest::GetRewChoiceItemsCount(), Quest::GetRewHonorAddition(), Quest::GetRewHonorMultiplier(), Quest::GetRewItemsCount(), Quest::GetRewMoneyMaxLevel(), Quest::GetRewOrReqMoney(), Quest::GetRewSpell(), Quest::GetRewSpellCast(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), Quest::GetSuggestedPlayers(), Quest::GetTitle(), Quest::GetXPReward(), Quest::HasQuestFlag(), QUEST_FLAGS_HIDDEN_REWARDS, QUEST_REPUTATIONS_COUNT, Quest::RewChoiceItemCount, Quest::RewChoiceItemId, Quest::RewItemCount, Quest::RewItemId, Quest::RewRepFaction, Quest::RewRepValueId, WorldSession::SendPacket(), SMSG_QUESTGIVER_QUEST_DETAILS, sObjectMgr, and sWorld.
Referenced by Spell::EffectQuestOffer(), WorldSession::HandlePushQuestToParty(), WorldSession::HandleQuestgiverChooseRewardOpcode(), and WorldSession::HandleQuestgiverQueryQuestOpcode().
SendQuestGiverQuestList()
void PlayerMenu::SendQuestGiverQuestList (QEmote eEmote, const std::string & Title, ObjectGuid npcGUID)
Definition at line 293 of file GossipDef.cpp.
References QEmote::_Delay, QEmote::_Emote, DEBUG_LOG, QuestMenu::GetItem(), GetMenuSession(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), QuestMenuItem::m_qIcon, QuestMenuItem::m_qId, QuestMenu::MenuItemCount(), mQuestMenu, ByteBuffer::put(), WorldSession::SendPacket(), SMSG_QUESTGIVER_QUEST_LIST, sObjectMgr, and ByteBuffer::wpos().
SendQuestGiverRequestItems()
void PlayerMenu::SendQuestGiverRequestItems (Quest const * pQuest, ObjectGuid npcGUID, bool Completable, bool CloseOnCancel) const
Definition at line 571 of file GossipDef.cpp.
References DEBUG_LOG, ItemPrototype::DisplayInfoID, Quest::GetCompleteEmote(), Quest::GetCompleteEmoteDelay(), Quest::GetIncompleteEmote(), Quest::GetIncompleteEmoteDelay(), ObjectMgr::GetItemPrototype(), GetMenuSession(), Quest::GetQuestFlags(), Quest::GetQuestId(), Quest::GetReqItemsCount(), Quest::GetRequestItemsText(), Quest::GetRewOrReqMoney(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), Quest::GetSuggestedPlayers(), Quest::GetTitle(), QUEST_ITEM_OBJECTIVES_COUNT, Quest::ReqItemCount, Quest::ReqItemId, WorldSession::SendPacket(), SendQuestGiverOfferReward(), SMSG_QUESTGIVER_REQUEST_ITEMS, and sObjectMgr.
Referenced by WorldSession::HandleQuestgiverCompleteQuest().
SendQuestGiverStatus()
void PlayerMenu::SendQuestGiverStatus (uint8 questStatus, ObjectGuid npcGUID) const
Definition at line 329 of file GossipDef.cpp.
References DEBUG_LOG, GetMenuSession(), ObjectGuid::GetString(), WorldSession::SendPacket(), and SMSG_QUESTGIVER_STATUS.
Referenced by WorldSession::HandleQuestgiverStatusQueryOpcode().
Field Documentation
mGossipMenu
GossipMenu PlayerMenu::mGossipMenu private
Definition at line 269 of file GossipDef.h.
Referenced by ClearMenus(), Empty(), GetGossipMenu(), GetMenuSession(), GossipOptionAction(), GossipOptionCoded(), GossipOptionSender(), and SendGossipMenu().
mQuestMenu
QuestMenu PlayerMenu::mQuestMenu private
Definition at line 270 of file GossipDef.h.
Referenced by ClearMenus(), Empty(), GetQuestMenu(), SendGossipMenu(), and SendQuestGiverQuestList().
The documentation for this class was generated from the following files:
GossipDef.h
GossipDef.cpp