CMaNGOS_WoTLK: instance_pit_of_saron Class Reference
instance_pit_of_saron Class Reference
#include <pit_of_saron.h>
Public Member Functions
instance_pit_of_saron (Map *pMap)
~instance_pit_of_saron ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
uint32 GetPlayerTeam () const
void SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (uint32 uiDiff)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoStartIntroEvent ()
void DoStartAmbushEvent ()
void DoStartTyrannusEvent ()
void DoSpawnTyrannusUndead ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_abAchievCriteria [MAX_SPECIAL_ACHIEV_CRITS]
uint8 m_uiAmbushAggroCount
uint32 m_uiTeam
uint32 m_uiSummonDelayTimer
uint32 m_uiIciclesTimer
uint32 m_uiEyeLichKingTimer
uint32 m_uiSummonUndeadTimer
GuidList m_lTunnelStalkersGuidList
GuidList m_lAmbushNpcsGuidList
GuidList m_lSaroniteRockGuidList
GuidList m_lEndingCreaturesGuidList
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Detailed Description
Definition at line 193 of file pit_of_saron.h.
Constructor & Destructor Documentation
instance_pit_of_saron()
instance_pit_of_saron::instance_pit_of_saron (Map * pMap)
Definition at line 55 of file pit_of_saron.cpp.
References Initialize().
~instance_pit_of_saron()
instance_pit_of_saron::~instance_pit_of_saron () inline
Definition at line 197 of file pit_of_saron.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_pit_of_saron::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 359 of file pit_of_saron.cpp.
References ACHIEV_CRIT_DOESNT_GO_ELEVEN, ACHIEV_CRIT_DONT_LOOK_UP, m_abAchievCriteria, TYPE_ACHIEV_DOESNT_GO_ELEVEN, and TYPE_ACHIEV_DONT_LOOK_UP.
DoSpawnTyrannusUndead()
void instance_pit_of_saron::DoSpawnTyrannusUndead () protected
Definition at line 469 of file pit_of_saron.cpp.
References afTyrannusSummonPos, WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_FALLEN_WARRIOR_EPILOG, NPC_TYRANNUS, NPC_WRATHBONE_REAVER, NPC_WRATHBONE_SORCERER, script_error_log(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and urand().
Referenced by Update().
DoStartAmbushEvent()
void instance_pit_of_saron::DoStartAmbushEvent () protected
Definition at line 418 of file pit_of_saron.cpp.
References aEventFirstAmbushLocations, DoScriptText(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_TYRANNUS_INTRO, SAY_TYRANNUS_AMBUSH_1, script_error_log(), WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by SetData().
DoStartIntroEvent()
void instance_pit_of_saron::DoStartIntroEvent () protected
Definition at line 396 of file pit_of_saron.cpp.
References aEventBeginLocations, ScriptedInstance::GetSingleCreatureFromStorage(), HORDE, m_uiTeam, NPC_TYRANNUS_INTRO, script_error_log(), WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by Update().
DoStartTyrannusEvent()
void instance_pit_of_saron::DoStartTyrannusEvent () protected
Definition at line 442 of file pit_of_saron.cpp.
References aEventTunnelEndLocations, ScriptedInstance::GetSingleCreatureFromStorage(), HORDE, m_lEndingCreaturesGuidList, m_uiTeam, NPC_TYRANNUS, SAY_PREFIGHT_1, script_error_log(), DialogueHelper::StartNextDialogueText(), WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by SetData().
GetData()
uint32 instance_pit_of_saron::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 278 of file pit_of_saron.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by AreaTrigger_at_pit_of_saron(), boss_rimefang_posAI::MoveInLineOfSight(), and OnPlayerEnter().
GetPlayerTeam()
uint32 instance_pit_of_saron::GetPlayerTeam () const inline
Definition at line 212 of file pit_of_saron.h.
References m_uiTeam.
Referenced by boss_ickAI::JustDied(), boss_forgemaster_garfrostAI::JustDied(), boss_tyrannusAI::JustDied(), and SetData().
Initialize()
void instance_pit_of_saron::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 66 of file pit_of_saron.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_abAchievCriteria, and m_auiEncounter.
Referenced by instance_pit_of_saron().
JustDidDialogueStep()
void instance_pit_of_saron::JustDidDialogueStep (int32) override protected virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 373 of file pit_of_saron.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), NPC_RIMEFANG, NPC_TYRANNUS, SPELL_EJECT_ALL_PASSENGERS, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Load()
void instance_pit_of_saron::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 256 of file pit_of_saron.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_pit_of_saron::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 95 of file pit_of_saron.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_lAmbushNpcsGuidList, m_lTunnelStalkersGuidList, ScriptedInstance::m_npcEntryGuidStore, NPC_COLDWRAITH, NPC_ELANDRA, NPC_EYE_LICH_KING, NPC_FALLEN_WARRIOR, NPC_GARFROST, NPC_ICK, NPC_IRONSKULL_PART1, NPC_JAINA_PART1, NPC_KILARA, NPC_KORELN, NPC_KRICK, NPC_LORALEN, NPC_RIMEFANG, NPC_STALKER, NPC_SYLVANAS_PART1, NPC_TYRANNUS, NPC_TYRANNUS_INTRO, NPC_VICTUS_PART1, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FLAMEBEARER, and NPC_YMIRJAR_WRATHBRINGER.
OnCreatureDeath()
void instance_pit_of_saron::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 318 of file pit_of_saron.cpp.
References afTyrannusMovePos, MotionMaster::Clear(), DoScriptText(), Object::GetEntry(), Unit::GetMotionMaster(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), Creature::IsTemporarySummon(), m_lAmbushNpcsGuidList, m_uiIciclesTimer, MotionMaster::MovePoint(), NPC_COLDWRAITH, NPC_FALLEN_WARRIOR, NPC_TYRANNUS_INTRO, NPC_YMIRJAR_DEATHBRINGER, NPC_YMIRJAR_FLAMEBEARER, NPC_YMIRJAR_WRATHBRINGER, SAY_GAUNTLET, SetSpecialAchievementCriteria(), Creature::SetWalk(), TYPE_ACHIEV_DONT_LOOK_UP, and urand().
OnCreatureEnterCombat()
void instance_pit_of_saron::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 286 of file pit_of_saron.cpp.
References aEventSecondAmbushLocations, afTyrannusMovePos, MotionMaster::Clear(), DoScriptText(), Object::GetEntry(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiAmbushAggroCount, MotionMaster::MovePoint(), NPC_TYRANNUS_INTRO, NPC_YMIRJAR_DEATHBRINGER, SAY_TYRANNUS_AMBUSH_2, Creature::SetWalk(), WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
OnCreatureRespawn()
void instance_pit_of_saron::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 135 of file pit_of_saron.cpp.
References Creature::AI(), Object::GetEntry(), Unit::GetMotionMaster(), Creature::IsTemporarySummon(), MotionMaster::MoveWaypoint(), NPC_FROSTBLADE, NPC_TYRANNUS_INTRO, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_pit_of_saron::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 152 of file pit_of_saron.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_ICEWALL, GO_SARONITE_ROCK, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_lSaroniteRockGuidList, GameObject::SetGoState(), TYPE_GARFROST, and TYPE_KRICK.
OnPlayerEnter()
void instance_pit_of_saron::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 75 of file pit_of_saron.cpp.
References afTyrannusMovePos, DONE, GetData(), Player::GetTeam(), m_uiEyeLichKingTimer, m_uiSummonDelayTimer, m_uiTeam, NOT_STARTED, NPC_TYRANNUS_INTRO, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_AMBUSH, TYPE_GARFROST, and TYPE_KRICK.
Save()
const char* instance_pit_of_saron::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 217 of file pit_of_saron.h.
References m_strInstData.
SetData()
void instance_pit_of_saron::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 170 of file pit_of_saron.cpp.
References DONE, DoStartAmbushEvent(), DoStartTyrannusEvent(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), Map::GetGameObject(), GetPlayerTeam(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_ICEWALL, GO_JUST_DEACTIVATED, HORDE, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_lEndingCreaturesGuidList, m_lSaroniteRockGuidList, m_strInstData, m_uiEyeLichKingTimer, m_uiIciclesTimer, m_uiSummonUndeadTimer, NPC_JAINA_PART1, NPC_SYLVANAS_PART1, NPC_TYRANNUS, NPC_TYRANNUS_INTRO, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SetSpecialAchievementCriteria(), SPECIAL, SPELL_ACHIEVEMENT_CHECK, TRIGGERED_OLD_TRIGGERED, TYPE_ACHIEV_DOESNT_GO_ELEVEN, TYPE_AMBUSH, TYPE_GARFROST, TYPE_KRICK, and TYPE_TYRANNUS.
Referenced by boss_forgemaster_garfrostAI::Aggro(), boss_ickAI::Aggro(), boss_tyrannusAI::Aggro(), AreaTrigger_at_pit_of_saron(), boss_ickAI::JustDied(), boss_forgemaster_garfrostAI::JustDied(), boss_tyrannusAI::JustDied(), boss_forgemaster_garfrostAI::JustReachedHome(), boss_ickAI::JustReachedHome(), boss_tyrannusAI::JustReachedHome(), and boss_rimefang_posAI::MoveInLineOfSight().
SetSpecialAchievementCriteria()
void instance_pit_of_saron::SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
Definition at line 353 of file pit_of_saron.cpp.
References m_abAchievCriteria, and MAX_SPECIAL_ACHIEV_CRITS.
Referenced by OnCreatureDeath(), SetData(), and npc_collapsing_icicleAI::SpellHitTarget().
Update()
void instance_pit_of_saron::Update (uint32 uiDiff) virtual
Reimplemented from InstanceData.
Definition at line 509 of file pit_of_saron.cpp.
References DialogueHelper::DialogueUpdate(), DoSpawnTyrannusUndead(), DoStartIntroEvent(), Map::GetCreature(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_lTunnelStalkersGuidList, m_uiEyeLichKingTimer, m_uiIciclesTimer, m_uiSummonDelayTimer, m_uiSummonUndeadTimer, NPC_EYE_LICH_KING, roll_chance_i(), script_error_log(), SPELL_ICICLE_SUMMON, TRIGGERED_OLD_TRIGGERED, and urand().
Field Documentation
m_abAchievCriteria
bool instance_pit_of_saron::m_abAchievCriteria[MAX_SPECIAL_ACHIEV_CRITS] protected
Definition at line 233 of file pit_of_saron.h.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetSpecialAchievementCriteria().
m_auiEncounter
uint32 instance_pit_of_saron::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 230 of file pit_of_saron.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_lAmbushNpcsGuidList
GuidList instance_pit_of_saron::m_lAmbushNpcsGuidList protected
Definition at line 243 of file pit_of_saron.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_lEndingCreaturesGuidList
GuidList instance_pit_of_saron::m_lEndingCreaturesGuidList protected
Definition at line 245 of file pit_of_saron.h.
Referenced by DoStartTyrannusEvent(), and SetData().
m_lSaroniteRockGuidList
GuidList instance_pit_of_saron::m_lSaroniteRockGuidList protected
Definition at line 244 of file pit_of_saron.h.
Referenced by OnObjectCreate(), and SetData().
m_lTunnelStalkersGuidList
GuidList instance_pit_of_saron::m_lTunnelStalkersGuidList protected
Definition at line 242 of file pit_of_saron.h.
Referenced by OnCreatureCreate(), and Update().
m_strInstData
std::string instance_pit_of_saron::m_strInstData protected
Definition at line 231 of file pit_of_saron.h.
Referenced by Save(), and SetData().
m_uiAmbushAggroCount
uint8 instance_pit_of_saron::m_uiAmbushAggroCount protected
Definition at line 235 of file pit_of_saron.h.
Referenced by OnCreatureEnterCombat().
m_uiEyeLichKingTimer
uint32 instance_pit_of_saron::m_uiEyeLichKingTimer protected
Definition at line 239 of file pit_of_saron.h.
Referenced by OnPlayerEnter(), SetData(), and Update().
m_uiIciclesTimer
uint32 instance_pit_of_saron::m_uiIciclesTimer protected
Definition at line 238 of file pit_of_saron.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_uiSummonDelayTimer
uint32 instance_pit_of_saron::m_uiSummonDelayTimer protected
Definition at line 237 of file pit_of_saron.h.
Referenced by OnPlayerEnter(), and Update().
m_uiSummonUndeadTimer
uint32 instance_pit_of_saron::m_uiSummonUndeadTimer protected
Definition at line 240 of file pit_of_saron.h.
Referenced by SetData(), and Update().
m_uiTeam
uint32 instance_pit_of_saron::m_uiTeam protected
Definition at line 236 of file pit_of_saron.h.
Referenced by DoStartIntroEvent(), DoStartTyrannusEvent(), GetPlayerTeam(), and OnPlayerEnter().
The documentation for this class was generated from the following files:
pit_of_saron.h
pit_of_saron.cpp