CMaNGOS_WoTLK: TargetedMovementGeneratorMedium< T, D > Class Template Reference
TargetedMovementGeneratorMedium< T, D > Class Template Reference abstract
#include <TargetedMovementGenerator.h>
Public Member Functions
bool Update (T &, const uint32 &)
virtual bool IsReachable () const override
Unit * GetCurrentTarget () const override
float GetOffset () const
float GetAngle () const
virtual void UnitSpeedChanged () override
virtual bool RemoveOnInvalid () const
Public Member Functions inherited from MovementGeneratorMedium< T, D >
void Initialize (Unit &u) override
void Finalize (Unit &u) override
void Interrupt (Unit &u) override
void Reset (Unit &u) override
bool Update (Unit &u, const uint32 &time_diff) override
bool GetResetPosition (Unit &u, float &x, float &y, float &z, float &o) const override
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Initialize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Finalize (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Interrupt (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
void Reset (U &u)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool Update (U &u, const uint32 &time_diff)
template<class U = T, typename std::enable_if< false==std::is_same< U, Unit >::value, U >::type * = nullptr>
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual MovementGeneratorType GetMovementGeneratorType () const =0
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Public Member Functions inherited from TargetedMovementGeneratorBase
TargetedMovementGeneratorBase (Unit &target)
void stopFollowing ()
void SetNewTarget (Unit &target)
Protected Member Functions
TargetedMovementGeneratorMedium (Unit &target, float offset, float angle)
~TargetedMovementGeneratorMedium ()
virtual bool RequiresNewPosition (T &owner, Position pos) const
virtual float GetDynamicTargetDistance (T &, bool) const
virtual bool ShouldFaceTarget () const
virtual void HandleTargetedMovement (T &owner, const uint32 &time_diff)=0
virtual void HandleFinalizedMovement (T &owner)=0
virtual void HandleMovementFailure (T &owner)=0
virtual bool _hasUnitStateNotMove (Unit &owner)=0
virtual void _clearUnitStateMove (Unit &owner)=0
virtual void _addUnitStateMove (Unit &owner)=0
Protected Attributes
ShortTimeTracker i_recheckDistance
float i_offset
float i_angle
G3D::Vector3 i_lastTargetPos
bool i_speedChanged: 1
bool i_targetReached: 1
bool i_faceTarget: 1
PathFinder * i_path
Protected Attributes inherited from TargetedMovementGeneratorBase
FollowerReference i_target
Detailed Description
template<class T, typename D>
class TargetedMovementGeneratorMedium< T, D >
Definition at line 41 of file TargetedMovementGenerator.h.
Constructor & Destructor Documentation
TargetedMovementGeneratorMedium()
template<class T , typename D > TargetedMovementGeneratorMedium< T, D >::TargetedMovementGeneratorMedium (Unit & target, float offset, float angle) inline protected
Definition at line 45 of file TargetedMovementGenerator.h.
~TargetedMovementGeneratorMedium()
template<class T , typename D > TargetedMovementGeneratorMedium< T, D >::~TargetedMovementGeneratorMedium () inline protected
Definition at line 53 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_path.
Member Function Documentation
_addUnitStateMove()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::_addUnitStateMove (Unit & owner) protected pure virtual
Implemented in ChaseMovementGenerator, and FollowMovementGenerator.
_clearUnitStateMove()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::_clearUnitStateMove (Unit & owner) protected pure virtual
Implemented in ChaseMovementGenerator, and FollowMovementGenerator.
_hasUnitStateNotMove()
template<class T , typename D > virtual bool TargetedMovementGeneratorMedium< T, D >::_hasUnitStateNotMove (Unit & owner) protected pure virtual
Implemented in ChaseMovementGenerator, and FollowMovementGenerator.
GetAngle()
template<class T , typename D > float TargetedMovementGeneratorMedium< T, D >::GetAngle () const inline
Definition at line 62 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_angle.
Referenced by ChatHandler::HandleMovegensCommand().
GetCurrentTarget()
template<class T , typename D > Unit* TargetedMovementGeneratorMedium< T, D >::GetCurrentTarget () const inline override virtual
Reimplemented from MovementGenerator.
Definition at line 60 of file TargetedMovementGenerator.h.
References Reference< TO, FROM >::getTarget(), and TargetedMovementGeneratorBase::i_target.
Referenced by ChatHandler::HandleMovegensCommand(), and ChatHandler::HandleNpcUnFollowCommand().
GetDynamicTargetDistance()
template<class T , typename D > virtual float TargetedMovementGeneratorMedium< T, D >::GetDynamicTargetDistance (T & , bool) const inline protected virtual
Reimplemented in FollowMovementGenerator, and ChaseMovementGenerator.
Definition at line 70 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_offset.
GetOffset()
template<class T , typename D > float TargetedMovementGeneratorMedium< T, D >::GetOffset () const inline
Definition at line 61 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_offset.
Referenced by ChatHandler::HandleMovegensCommand().
HandleFinalizedMovement()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::HandleFinalizedMovement (T & owner) protected pure virtual
Implemented in FormationMovementGenerator, FollowMovementGenerator, and ChaseMovementGenerator.
HandleMovementFailure()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::HandleMovementFailure (T & owner) protected pure virtual
Implemented in FollowMovementGenerator, and ChaseMovementGenerator.
HandleTargetedMovement()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::HandleTargetedMovement (T & owner, const uint32 & time_diff) protected pure virtual
Implemented in FormationMovementGenerator, FollowMovementGenerator, and ChaseMovementGenerator.
IsReachable()
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::IsReachable override virtual
Reimplemented from MovementGenerator.
Reimplemented in ChaseMovementGenerator.
Definition at line 103 of file TargetedMovementGenerator.cpp.
References PATHFIND_NORMAL.
RemoveOnInvalid()
template<class T , typename D > virtual bool TargetedMovementGeneratorMedium< T, D >::RemoveOnInvalid () const inline virtual
Reimplemented in ChaseMovementGenerator.
Definition at line 66 of file TargetedMovementGenerator.h.
RequiresNewPosition()
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::RequiresNewPosition (T & owner, Position pos) const protected virtual
Definition at line 109 of file TargetedMovementGenerator.cpp.
References DIST_CALC_NONE, Position::x, Position::y, and Position::z.
ShouldFaceTarget()
template<class T , typename D > virtual bool TargetedMovementGeneratorMedium< T, D >::ShouldFaceTarget () const inline protected virtual
Definition at line 71 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_faceTarget.
UnitSpeedChanged()
template<class T , typename D > virtual void TargetedMovementGeneratorMedium< T, D >::UnitSpeedChanged () inline override virtual
Reimplemented from MovementGenerator.
Definition at line 64 of file TargetedMovementGenerator.h.
References TargetedMovementGeneratorMedium< T, D >::i_speedChanged.
Update()
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::Update (T & owner, const uint32 & time_diff)
Definition at line 46 of file TargetedMovementGenerator.cpp.
References sLog.
Referenced by FormationMovementGenerator::Update().
Field Documentation
i_angle
template<class T , typename D > float TargetedMovementGeneratorMedium< T, D >::i_angle protected
Definition at line 82 of file TargetedMovementGenerator.h.
Referenced by TargetedMovementGeneratorMedium< T, D >::GetAngle().
i_faceTarget
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::i_faceTarget protected
Definition at line 86 of file TargetedMovementGenerator.h.
Referenced by TargetedMovementGeneratorMedium< T, D >::ShouldFaceTarget().
i_lastTargetPos
template<class T , typename D > G3D::Vector3 TargetedMovementGeneratorMedium< T, D >::i_lastTargetPos protected
Definition at line 83 of file TargetedMovementGenerator.h.
i_offset
template<class T , typename D > float TargetedMovementGeneratorMedium< T, D >::i_offset protected
Definition at line 81 of file TargetedMovementGenerator.h.
Referenced by TargetedMovementGeneratorMedium< T, D >::GetDynamicTargetDistance(), and TargetedMovementGeneratorMedium< T, D >::GetOffset().
i_path
template<class T , typename D > PathFinder* TargetedMovementGeneratorMedium< T, D >::i_path protected
Definition at line 88 of file TargetedMovementGenerator.h.
Referenced by TargetedMovementGeneratorMedium< T, D >::~TargetedMovementGeneratorMedium().
i_recheckDistance
template<class T , typename D > ShortTimeTracker TargetedMovementGeneratorMedium< T, D >::i_recheckDistance protected
Definition at line 80 of file TargetedMovementGenerator.h.
i_speedChanged
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::i_speedChanged protected
Definition at line 84 of file TargetedMovementGenerator.h.
Referenced by TargetedMovementGeneratorMedium< T, D >::UnitSpeedChanged().
i_targetReached
template<class T , typename D > bool TargetedMovementGeneratorMedium< T, D >::i_targetReached protected
Definition at line 85 of file TargetedMovementGenerator.h.
The documentation for this class was generated from the following files:
TargetedMovementGenerator.h
TargetedMovementGenerator.cpp