CMaNGOS_WoTLK: instance_obsidian_sanctum Class Reference
instance_obsidian_sanctum Class Reference
#include <obsidian_sanctum.h>
Public Member Functions
instance_obsidian_sanctum (Map *pMap)
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
ObjectGuid SelectRandomFireCycloneGuid ()
bool IsActivePortal ()
void SetPortalStatus (uint8 uiType, bool bStatus)
bool GetPortaStatus (uint8 uiType)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectCreate (GameObject *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
bool m_bPortalActive [MAX_TWILIGHT_DRAGONS]
uint8 m_uiAliveDragons
std::set< uint32 > m_sVolcanoBlowFailPlayers
GuidList m_lFireCycloneGuidList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 63 of file obsidian_sanctum.h.
Constructor & Destructor Documentation
instance_obsidian_sanctum()
instance_obsidian_sanctum::instance_obsidian_sanctum (Map * pMap)
Definition at line 31 of file obsidian_sanctum.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_obsidian_sanctum::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 106 of file obsidian_sanctum.cpp.
References ACHIEV_CRIT_VOLCANO_BLOW_H, ACHIEV_CRIT_VOLCANO_BLOW_N, ACHIEV_DRAGONS_ALIVE_1_H, ACHIEV_DRAGONS_ALIVE_1_N, ACHIEV_DRAGONS_ALIVE_2_H, ACHIEV_DRAGONS_ALIVE_2_N, ACHIEV_DRAGONS_ALIVE_3_H, ACHIEV_DRAGONS_ALIVE_3_N, Object::GetGUIDLow(), m_sVolcanoBlowFailPlayers, and m_uiAliveDragons.
CheckConditionCriteriaMeet()
bool instance_obsidian_sanctum::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 128 of file obsidian_sanctum.cpp.
References Object::GetGuidStr(), INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, INSTANCE_CONDITION_ID_HARD_MODE_3, m_uiAliveDragons, and script_error_log().
GetData()
uint32 instance_obsidian_sanctum::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 87 of file obsidian_sanctum.cpp.
References m_auiEncounter, and TYPE_SARTHARION_EVENT.
Referenced by dummy_dragonAI::DoEjectTwilightPlayersIfCan(), dummy_dragonAI::DoOpenPortal(), mob_tenebronAI::JustDied(), mob_shadronAI::JustDied(), mob_vesperonAI::JustDied(), dummy_dragonAI::MovementInform(), mob_shadronAI::SummonedCreatureJustDied(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), and mob_vesperonAI::UpdateDragonAI().
GetPortaStatus()
bool instance_obsidian_sanctum::GetPortaStatus (uint8 uiType) inline
Definition at line 89 of file obsidian_sanctum.h.
References m_bPortalActive.
Initialize()
void instance_obsidian_sanctum::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 37 of file obsidian_sanctum.cpp.
References m_auiEncounter, and m_bPortalActive.
Referenced by instance_obsidian_sanctum().
IsActivePortal()
bool instance_obsidian_sanctum::IsActivePortal () inline
Definition at line 77 of file obsidian_sanctum.h.
References m_bPortalActive.
Referenced by dummy_dragonAI::DoEjectTwilightPlayersIfCan(), and dummy_dragonAI::UpdateAI().
OnCreatureCreate()
void instance_obsidian_sanctum::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file obsidian_sanctum.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lFireCycloneGuidList, ScriptedInstance::m_npcEntryGuidStore, NPC_FIRE_CYCLONE, NPC_SARTHARION, NPC_SHADRON, NPC_TENEBRON, NPC_TENEBRON_EGG_CONTROLLER, NPC_VESPERON, NPC_VESPERON_CONTROLLER, NPC_VESPERON_CONTROLLER_DEBUFF_CLEAR, and WorldObject::SetActiveObjectState().
SelectRandomFireCycloneGuid()
ObjectGuid instance_obsidian_sanctum::SelectRandomFireCycloneGuid ()
Definition at line 95 of file obsidian_sanctum.cpp.
References m_lFireCycloneGuidList, and urand().
Referenced by boss_sartharionAI::UpdateAI().
SetData()
void instance_obsidian_sanctum::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 67 of file obsidian_sanctum.cpp.
References IN_PROGRESS, m_auiEncounter, m_sVolcanoBlowFailPlayers, m_uiAliveDragons, TYPE_ALIVE_DRAGONS, TYPE_SARTHARION_EVENT, and TYPE_VOLCANO_BLOW_FAILED.
Referenced by boss_sartharionAI::Aggro(), boss_sartharionAI::FetchDragons(), boss_sartharionAI::JustDied(), and boss_sartharionAI::JustReachedHome().
SetPortalStatus()
void instance_obsidian_sanctum::SetPortalStatus (uint8 uiType, bool bStatus) inline
Definition at line 88 of file obsidian_sanctum.h.
References m_bPortalActive.
Referenced by dummy_dragonAI::DoOpenPortal(), dummy_dragonAI::JustReachedHome(), mob_tenebronAI::ReceiveAIEvent(), mob_shadronAI::SummonedCreatureJustDied(), and mob_vesperonAI::SummonedCreatureJustDied().
Field Documentation
m_auiEncounter
uint32 instance_obsidian_sanctum::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 95 of file obsidian_sanctum.h.
Referenced by GetData(), Initialize(), and SetData().
m_bPortalActive
bool instance_obsidian_sanctum::m_bPortalActive[MAX_TWILIGHT_DRAGONS] private
Definition at line 96 of file obsidian_sanctum.h.
Referenced by GetPortaStatus(), Initialize(), IsActivePortal(), and SetPortalStatus().
m_lFireCycloneGuidList
GuidList instance_obsidian_sanctum::m_lFireCycloneGuidList private
Definition at line 102 of file obsidian_sanctum.h.
Referenced by OnCreatureCreate(), and SelectRandomFireCycloneGuid().
m_sVolcanoBlowFailPlayers
std::set<uint32> instance_obsidian_sanctum::m_sVolcanoBlowFailPlayers private
Definition at line 100 of file obsidian_sanctum.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_uiAliveDragons
uint8 instance_obsidian_sanctum::m_uiAliveDragons private
Definition at line 98 of file obsidian_sanctum.h.
Referenced by CheckAchievementCriteriaMeet(), CheckConditionCriteriaMeet(), and SetData().
The documentation for this class was generated from the following files:
obsidian_sanctum.h
obsidian_sanctum.cpp