CMaNGOS_WoTLK: instance_karazhan Class Reference
instance_karazhan Class Reference
#include <karazhan.h>
Public Member Functions
instance_karazhan (Map *pMap)
~instance_karazhan ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void SetData64 (uint32 uiData, uint64 uiGuid) override
void DoPrepareOperaStage (Creature *pOrganizer)
uint32 GetPlayerTeam () const
bool IsFriendlyGameReady () const
void DoMoveChessPieceToSides (uint32 uiSpellId, uint32 uiFaction, bool bGameEnd=false)
void DoFailChessEvent ()
void DoFinishChessEvent ()
void GetChessPiecesByFaction (GuidList &lList, uint32 uiFaction)
GuidVector & GetAranTeleportNPCs ()
void GetNightbaneTriggers (GuidList &lList, bool bGround)
void Load (const char *chrIn) override
const char * Save () const override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Data Fields
GuidVector m_vInfernalRelays
Data Fields inherited from InstanceData
Map * instance
Private Member Functions
void DoPrepareChessEvent ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiOperaEvent
uint32 m_uiOzDeathCount
uint32 m_uiTeam
uint32 m_uiChessResetTimer
uint32 m_uiChessEndingTimer
uint32 m_uiVictoryControllerTimer
uint32 m_uiVictoryToolTimers [8]
uint8 m_uiAllianceStalkerCount
uint8 m_uiHordeStalkerCount
bool m_bFriendlyGame
bool m_bBasementBossReady
bool m_uiVictoryTimersPhase [8]
ObjectGuid m_HordeStatusGuid
ObjectGuid m_AllianceStatusGuid
GuidList m_lOperaTreeGuidList
GuidList m_lOperaHayGuidList
GuidList m_lNightbaneGroundTriggers
GuidList m_lNightbaneAirTriggers
GuidSet m_sBasementMobsSet
GuidList m_lChessHordeStalkerList
GuidList m_lChessAllianceStalkerList
GuidList m_lChessPiecesAlliance
GuidList m_lChessPiecesHorde
GuidVector m_vHordeStalkers
GuidVector m_vAllianceStalkers
GuidVector m_vVictoryDummyTools
GuidVector m_vChessSquares
GuidVector m_aranTeleportNPCs
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 203 of file karazhan.h.
Constructor & Destructor Documentation
instance_karazhan()
instance_karazhan::instance_karazhan (Map * pMap)
Definition at line 41 of file karazhan.cpp.
References Initialize().
~instance_karazhan()
instance_karazhan::~instance_karazhan () inline
Definition at line 207 of file karazhan.h.
Member Function Documentation
DoFailChessEvent()
void instance_karazhan::DoFailChessEvent ()
Definition at line 592 of file karazhan.cpp.
References AI_EVENT_CUSTOM_A, Unit::GetCharmer(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_CHESSBOARD, InstanceData::instance, m_lChessPiecesAlliance, m_lChessPiecesHorde, m_uiChessResetTimer, m_vChessSquares, NPC_ECHO_MEDIVH, SPELL_CLEAR_BOARD, SPELL_GAME_OVER, and TRIGGERED_OLD_TRIGGERED.
Referenced by SetData().
DoFinishChessEvent()
void instance_karazhan::DoFinishChessEvent ()
Definition at line 641 of file karazhan.cpp.
References AI_EVENT_CUSTOM_A, DAY, ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), Unit::GetCharmer(), Map::GetCreature(), GetData(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_CHESSBOARD, GO_DUST_COVERED_CHEST, GO_FLAG_NO_INTERACT, GO_GAMESMANS_HALL_EXIT_DOOR, InstanceData::instance, m_bFriendlyGame, m_lChessPiecesAlliance, m_lChessPiecesHorde, m_uiChessEndingTimer, m_uiChessResetTimer, m_vChessSquares, NPC_ECHO_MEDIVH, SPECIAL, SPELL_CLEAR_BOARD, SPELL_FORCE_KILL_BUNNY, SPELL_GAME_OVER, TRIGGERED_OLD_TRIGGERED, and TYPE_CHESS.
Referenced by SetData().
DoMoveChessPieceToSides()
void instance_karazhan::DoMoveChessPieceToSides (uint32 uiSpellId, uint32 uiFaction, bool bGameEnd = false)
Definition at line 555 of file karazhan.cpp.
References Unit::CastSpell(), EMOTE_STATE_APPLAUD, FACTION_ID_CHESS_ALLIANCE, Map::GetCreature(), InstanceData::instance, m_AllianceStatusGuid, m_HordeStatusGuid, m_uiAllianceStalkerCount, m_uiHordeStalkerCount, m_vAllianceStalkers, m_vHordeStalkers, and TRIGGERED_OLD_TRIGGERED.
Referenced by npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), npc_human_conjurerAI::JustDied(), npc_orc_warlockAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), npc_water_elementalAI::JustDied(), npc_summoned_daemonAI::JustDied(), npc_human_chargerAI::JustDied(), npc_orc_wolfAI::JustDied(), npc_human_clericAI::JustDied(), and npc_orc_necrolyteAI::JustDied().
DoPrepareChessEvent()
void instance_karazhan::DoPrepareChessEvent () private
Definition at line 461 of file karazhan.cpp.
References AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, GetClosestCreatureWithEntry(), Map::GetCreature(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_CHESSBOARD, InstanceData::instance, m_AllianceStatusGuid, m_HordeStatusGuid, m_lChessAllianceStalkerList, m_lChessHordeStalkerList, m_lChessPiecesAlliance, m_lChessPiecesHorde, m_uiAllianceStalkerCount, m_uiHordeStalkerCount, m_vAllianceStalkers, m_vHordeStalkers, NPC_SQUARE_BLACK, NPC_SQUARE_WHITE, and script_error_log().
Referenced by SetData().
DoPrepareOperaStage()
void instance_karazhan::DoPrepareOperaStage (Creature * pOrganizer)
Definition at line 704 of file karazhan.cpp.
References aOperaLocJul, aOperaLocOz, aOperaLocWolf, debug_log(), ScriptedInstance::DoRespawnGameObject(), OperaSpawns::fO, OperaSpawns::fX, OperaSpawns::fY, OperaSpawns::fZ, GetData(), GO_HOOD_BACKDROP, GO_HOOD_HOUSE, GO_OZ_BACKDROP, GO_RAJ_BACKDROP, GO_RAJ_BALCONY, GO_RAJ_MOON, HOUR, IN_PROGRESS, m_lOperaHayGuidList, m_lOperaTreeGuidList, OPERA_EVENT_RED_RIDING_HOOD, OPERA_EVENT_ROMULO_AND_JUL, OPERA_EVENT_WIZARD_OZ, SetData(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_OPERA, TYPE_OPERA_PERFORMANCE, and OperaSpawns::uiEntry.
Referenced by npc_barnesAI::WaypointReached().
GetAranTeleportNPCs()
GuidVector& instance_karazhan::GetAranTeleportNPCs () inline
Definition at line 234 of file karazhan.h.
References m_aranTeleportNPCs.
Referenced by boss_aranAI::ExecuteAction(), and boss_aranAI::Reset().
GetChessPiecesByFaction()
void instance_karazhan::GetChessPiecesByFaction (GuidList & lList, uint32 uiFaction) inline
Definition at line 232 of file karazhan.h.
References FACTION_ID_CHESS_ALLIANCE, m_lChessPiecesAlliance, and m_lChessPiecesHorde.
Referenced by npc_chess_piece_genericAI::GetMovementSquare(), and npc_chess_piece_genericAI::GetTargetByType().
GetData()
uint32 instance_karazhan::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 332 of file karazhan.cpp.
References m_auiEncounter, m_uiOperaEvent, MAX_ENCOUNTER, and TYPE_OPERA_PERFORMANCE.
Referenced by boss_nightbaneAI::CorpseRemoved(), DoFinishChessEvent(), DoPrepareOperaStage(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), OnCreatureRespawn(), OnPlayerEnter(), npc_chess_piece_genericAI::Reset(), Update(), npc_echo_of_medivhAI::UpdateAI(), npc_chess_piece_genericAI::UpdateAI(), and npc_barnesAI::WaypointReached().
GetNightbaneTriggers()
void instance_karazhan::GetNightbaneTriggers (GuidList & lList, bool bGround) inline
Definition at line 236 of file karazhan.h.
References m_lNightbaneAirTriggers, and m_lNightbaneGroundTriggers.
Referenced by boss_nightbaneAI::DoMoveToClosestTrigger().
GetPlayerTeam()
uint32 instance_karazhan::GetPlayerTeam () const inline
Definition at line 227 of file karazhan.h.
References m_uiTeam.
Referenced by npc_king_llaneAI::DamageTaken(), npc_warchief_blackhandAI::DamageTaken(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), npc_human_conjurerAI::JustDied(), npc_orc_warlockAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), npc_water_elementalAI::JustDied(), npc_summoned_daemonAI::JustDied(), npc_human_chargerAI::JustDied(), npc_orc_wolfAI::JustDied(), npc_human_clericAI::JustDied(), npc_orc_necrolyteAI::JustDied(), npc_chess_piece_genericAI::Reset(), and npc_echo_of_medivhAI::UpdateAI().
Initialize()
void instance_karazhan::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 55 of file karazhan.cpp.
References m_auiEncounter.
Referenced by instance_karazhan().
IsEncounterInProgress()
bool instance_karazhan::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 60 of file karazhan.cpp.
References IN_PROGRESS, and m_auiEncounter.
IsFriendlyGameReady()
bool instance_karazhan::IsFriendlyGameReady () const inline
Definition at line 228 of file karazhan.h.
References m_bFriendlyGame.
Load()
void instance_karazhan::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 357 of file karazhan.cpp.
References DONE, IN_PROGRESS, m_auiEncounter, m_bFriendlyGame, m_uiOperaEvent, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_karazhan::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 84 of file karazhan.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_AllianceStatusGuid, m_aranTeleportNPCs, m_HordeStatusGuid, m_lChessAllianceStalkerList, m_lChessHordeStalkerList, m_lChessPiecesAlliance, m_lChessPiecesHorde, m_lNightbaneAirTriggers, m_lNightbaneGroundTriggers, ScriptedInstance::m_npcEntryGuidStore, m_vChessSquares, m_vInfernalRelays, m_vVictoryDummyTools, NPC_ATTUMEN, NPC_BARNES, NPC_BARON_RAFE_DREUGER, NPC_BARONESS_DOROTHEA_MILLSTIPE, NPC_CHESS_STATUS_BAR, NPC_CHESS_VICTORY_CONTROLLER, NPC_CONJURED_WATER_ELEMENTAL, NPC_ECHO_MEDIVH, NPC_HUMAN_CHARGER, NPC_HUMAN_CLERIC, NPC_HUMAN_CONJURER, NPC_HUMAN_FOOTMAN, NPC_IMAGE_OF_ARCANAGOS, NPC_IMAGE_OF_MEDIVH, NPC_INFERNAL_RELAY, NPC_INVISIBLE_STALKER, NPC_JULIANNE, NPC_KING_LLANE, NPC_LADY_CATRIONA_VON_INDI, NPC_LADY_KEIRA_BERRYBUCK, NPC_LORD_CRISPIN_FERENCE, NPC_LORD_ROBIN_DARIS, NPC_MIDNIGHT, NPC_MOROES, NPC_NETHERSPITE, NPC_NIGHTBANE, NPC_NIGHTBANE_HELPER, NPC_ORC_GRUNT, NPC_ORC_NECROLYTE, NPC_ORC_WARLOCK, NPC_ORC_WOLF, NPC_ROMULO, NPC_SQUARE_BLACK, NPC_SQUARE_WHITE, NPC_SUMMONED_DAEMON, NPC_TELEPORT_E, NPC_TELEPORT_N, NPC_TELEPORT_NE, NPC_TELEPORT_NW, NPC_TELEPORT_S, NPC_TELEPORT_SE, NPC_TELEPORT_SW, NPC_TELEPORT_W, NPC_VICTORY_DUMMY_TOOL, and NPC_WARCHIEF_BLACKHAND.
OnCreatureDeath()
void instance_karazhan::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 406 of file karazhan.cpp.
References aBasementEnum, afChroneSpawnLoc, DoScriptText(), BasementSpawns::fO, BasementSpawns::fX, BasementSpawns::fY, BasementSpawns::fZ, Object::GetEntry(), Object::GetObjectGuid(), Unit::GetVictim(), HOUR, IN_MILLISECONDS, m_bBasementBossReady, m_sBasementMobsSet, m_uiOzDeathCount, MAX_OZ_OPERA_MOBS, NPC_COLDMIST_STALKER, NPC_COLDMIST_WIDOW, NPC_CRONE, NPC_DOROTHEE, NPC_DREADBEAST, NPC_GREATER_SHADOWBAT, NPC_PHASE_HOUND, NPC_ROAR, NPC_SHADOWBAT, NPC_SHADOWBEAST, NPC_STRAWMAN, NPC_TINHEAD, NPC_VAMPIRIC_SHADOWBAT, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, BasementSpawns::uiEntry, and urand().
OnCreatureEvade()
void instance_karazhan::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 387 of file karazhan.cpp.
References Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_BARON_RAFE_DREUGER, NPC_BARONESS_DOROTHEA_MILLSTIPE, NPC_LADY_CATRIONA_VON_INDI, NPC_LADY_KEIRA_BERRYBUCK, NPC_LORD_CRISPIN_FERENCE, NPC_LORD_ROBIN_DARIS, and NPC_MOROES.
OnCreatureRespawn()
void instance_karazhan::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 215 of file karazhan.cpp.
References Creature::AI(), Creature::ForcedDespawn(), GetData(), Object::GetEntry(), IN_PROGRESS, NPC_BLIZZARD, NPC_INFERNAL, REACT_PASSIVE, UnitAI::SetReactState(), and TYPE_MALCHEZZAR.
OnObjectCreate()
void instance_karazhan::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 165 of file karazhan.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_BLACKENED_URN, GO_CHESSBOARD, GO_DUST_COVERED_CHEST, GO_FLAG_LOCKED, GO_GAMESMANS_HALL_DOOR, GO_GAMESMANS_HALL_EXIT_DOOR, GO_HOOD_BACKDROP, GO_HOOD_HOUSE, GO_HOOD_TREE, GO_MASSIVE_DOOR, GO_MASTERS_TERRACE_DOOR_1, GO_MASTERS_TERRACE_DOOR_2, GO_NETHERSPACE_DOOR, GO_OZ_BACKDROP, GO_OZ_HAY, GO_PRIVATE_LIBRARY_DOOR, GO_RAJ_BACKDROP, GO_RAJ_BALCONY, GO_RAJ_MOON, GO_SERVANTS_ACCESS_DOOR, GO_SIDE_ENTRANCE_DOOR, GO_STAGE_CURTAIN, GO_STAGE_DOOR_LEFT, GO_STAGE_DOOR_RIGHT, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_lOperaHayGuidList, m_lOperaTreeGuidList, Object::RemoveFlag(), and GameObject::SetGoState().
OnPlayerEnter()
void instance_karazhan::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 71 of file karazhan.cpp.
References GetData(), Player::GetTeam(), m_uiTeam, OPERA_EVENT_ROMULO_AND_JUL, OPERA_EVENT_WIZARD_OZ, SetData(), TYPE_OPERA_PERFORMANCE, and urand().
Save()
const char* instance_karazhan::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 239 of file karazhan.h.
References m_strInstData.
SetData()
void instance_karazhan::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 230 of file karazhan.cpp.
References DoFailChessEvent(), DoFinishChessEvent(), DONE, DoPrepareChessEvent(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), GO_FLAG_LOCKED, GO_MASSIVE_DOOR, GO_MASTERS_TERRACE_DOOR_1, GO_MASTERS_TERRACE_DOOR_2, GO_NETHERSPACE_DOOR, GO_PRIVATE_LIBRARY_DOOR, GO_SERVANTS_ACCESS_DOOR, GO_SIDE_ENTRANCE_DOOR, GO_STAGE_CURTAIN, GO_STAGE_DOOR_LEFT, GO_STAGE_DOOR_RIGHT, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_strInstData, m_uiOperaEvent, m_uiOzDeathCount, NPC_MIDNIGHT, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, TYPE_ARAN, TYPE_ATTUMEN, TYPE_CHESS, TYPE_CURATOR, TYPE_MAIDEN, TYPE_MALCHEZZAR, TYPE_MOROES, TYPE_NETHERSPITE, TYPE_NIGHTBANE, TYPE_OPERA, TYPE_OPERA_PERFORMANCE, and TYPE_TERESTIAN.
Referenced by boss_midnightAI::Aggro(), boss_aranAI::Aggro(), DoPrepareOperaStage(), boss_nightbaneAI::EnterEvadeMode(), boss_attumenAI::JustDied(), boss_nightbaneAI::JustDied(), boss_aranAI::JustDied(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), boss_midnightAI::JustReachedHome(), boss_attumenAI::JustReachedHome(), boss_aranAI::JustReachedHome(), OnPlayerEnter(), and Update().
SetData64()
void instance_karazhan::SetData64 (uint32 uiData, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 343 of file karazhan.cpp.
References DATA_BASEMENT_EVENT, m_bBasementBossReady, m_sBasementMobsSet, and MIN_BASEMENT_MOBS.
Update()
void instance_karazhan::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 739 of file karazhan.cpp.
References DONE, EMOTE_STATE_NONE, FAIL, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_bFriendlyGame, m_lChessAllianceStalkerList, m_lChessHordeStalkerList, m_lChessPiecesAlliance, m_lChessPiecesHorde, m_uiChessEndingTimer, m_uiChessResetTimer, m_uiVictoryControllerTimer, m_uiVictoryTimersPhase, m_uiVictoryToolTimers, m_vChessSquares, m_vVictoryDummyTools, NOT_STARTED, NPC_CHESS_VICTORY_CONTROLLER, SetData(), SPELL_BOARD_VISUAL, SPELL_VICTORY_VISUAL, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPE_CHESS, and urand().
Field Documentation
m_AllianceStatusGuid
ObjectGuid instance_karazhan::m_AllianceStatusGuid private
Definition at line 267 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), DoPrepareChessEvent(), and OnCreatureCreate().
m_aranTeleportNPCs
GuidVector instance_karazhan::m_aranTeleportNPCs private
Definition at line 283 of file karazhan.h.
Referenced by GetAranTeleportNPCs(), and OnCreatureCreate().
m_auiEncounter
uint32 instance_karazhan::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 248 of file karazhan.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), and SetData().
m_bBasementBossReady
bool instance_karazhan::m_bBasementBossReady private
Definition at line 263 of file karazhan.h.
Referenced by OnCreatureDeath(), and SetData64().
m_bFriendlyGame
bool instance_karazhan::m_bFriendlyGame private
Definition at line 262 of file karazhan.h.
Referenced by DoFinishChessEvent(), IsFriendlyGameReady(), Load(), and Update().
m_HordeStatusGuid
ObjectGuid instance_karazhan::m_HordeStatusGuid private
Definition at line 266 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), DoPrepareChessEvent(), and OnCreatureCreate().
m_lChessAllianceStalkerList
GuidList instance_karazhan::m_lChessAllianceStalkerList private
Definition at line 276 of file karazhan.h.
Referenced by DoPrepareChessEvent(), OnCreatureCreate(), and Update().
m_lChessHordeStalkerList
GuidList instance_karazhan::m_lChessHordeStalkerList private
Definition at line 275 of file karazhan.h.
Referenced by DoPrepareChessEvent(), OnCreatureCreate(), and Update().
m_lChessPiecesAlliance
GuidList instance_karazhan::m_lChessPiecesAlliance private
Definition at line 277 of file karazhan.h.
Referenced by DoFailChessEvent(), DoFinishChessEvent(), DoPrepareChessEvent(), GetChessPiecesByFaction(), OnCreatureCreate(), and Update().
m_lChessPiecesHorde
GuidList instance_karazhan::m_lChessPiecesHorde private
Definition at line 278 of file karazhan.h.
Referenced by DoFailChessEvent(), DoFinishChessEvent(), DoPrepareChessEvent(), GetChessPiecesByFaction(), OnCreatureCreate(), and Update().
m_lNightbaneAirTriggers
GuidList instance_karazhan::m_lNightbaneAirTriggers private
Definition at line 272 of file karazhan.h.
Referenced by GetNightbaneTriggers(), and OnCreatureCreate().
m_lNightbaneGroundTriggers
GuidList instance_karazhan::m_lNightbaneGroundTriggers private
Definition at line 271 of file karazhan.h.
Referenced by GetNightbaneTriggers(), and OnCreatureCreate().
m_lOperaHayGuidList
GuidList instance_karazhan::m_lOperaHayGuidList private
Definition at line 270 of file karazhan.h.
Referenced by DoPrepareOperaStage(), and OnObjectCreate().
m_lOperaTreeGuidList
GuidList instance_karazhan::m_lOperaTreeGuidList private
Definition at line 269 of file karazhan.h.
Referenced by DoPrepareOperaStage(), and OnObjectCreate().
m_sBasementMobsSet
GuidSet instance_karazhan::m_sBasementMobsSet private
Definition at line 273 of file karazhan.h.
Referenced by OnCreatureDeath(), and SetData64().
m_strInstData
std::string instance_karazhan::m_strInstData private
Definition at line 249 of file karazhan.h.
Referenced by Save(), and SetData().
m_uiAllianceStalkerCount
uint8 instance_karazhan::m_uiAllianceStalkerCount private
Definition at line 259 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), and DoPrepareChessEvent().
m_uiChessEndingTimer
uint32 instance_karazhan::m_uiChessEndingTimer private
Definition at line 255 of file karazhan.h.
Referenced by DoFinishChessEvent(), and Update().
m_uiChessResetTimer
uint32 instance_karazhan::m_uiChessResetTimer private
Definition at line 254 of file karazhan.h.
Referenced by DoFailChessEvent(), DoFinishChessEvent(), and Update().
m_uiHordeStalkerCount
uint8 instance_karazhan::m_uiHordeStalkerCount private
Definition at line 260 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), and DoPrepareChessEvent().
m_uiOperaEvent
uint32 instance_karazhan::m_uiOperaEvent private
Definition at line 251 of file karazhan.h.
Referenced by GetData(), Load(), and SetData().
m_uiOzDeathCount
uint32 instance_karazhan::m_uiOzDeathCount private
Definition at line 252 of file karazhan.h.
Referenced by OnCreatureDeath(), and SetData().
m_uiTeam
uint32 instance_karazhan::m_uiTeam private
Definition at line 253 of file karazhan.h.
Referenced by GetPlayerTeam(), and OnPlayerEnter().
m_uiVictoryControllerTimer
uint32 instance_karazhan::m_uiVictoryControllerTimer private
Definition at line 256 of file karazhan.h.
Referenced by Update().
m_uiVictoryTimersPhase
bool instance_karazhan::m_uiVictoryTimersPhase[8] private
Definition at line 264 of file karazhan.h.
Referenced by Update().
m_uiVictoryToolTimers
uint32 instance_karazhan::m_uiVictoryToolTimers[8] private
Definition at line 257 of file karazhan.h.
Referenced by Update().
m_vAllianceStalkers
GuidVector instance_karazhan::m_vAllianceStalkers private
Definition at line 280 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), and DoPrepareChessEvent().
m_vChessSquares
GuidVector instance_karazhan::m_vChessSquares private
Definition at line 282 of file karazhan.h.
Referenced by DoFailChessEvent(), DoFinishChessEvent(), OnCreatureCreate(), and Update().
m_vHordeStalkers
GuidVector instance_karazhan::m_vHordeStalkers private
Definition at line 279 of file karazhan.h.
Referenced by DoMoveChessPieceToSides(), and DoPrepareChessEvent().
m_vInfernalRelays
GuidVector instance_karazhan::m_vInfernalRelays
Definition at line 243 of file karazhan.h.
Referenced by OnCreatureCreate().
m_vVictoryDummyTools
GuidVector instance_karazhan::m_vVictoryDummyTools private
Definition at line 281 of file karazhan.h.
Referenced by OnCreatureCreate(), and Update().
The documentation for this class was generated from the following files:
karazhan.h
karazhan.cpp