CMaNGOS_WoTLK: instance_shattered_halls Class Reference
instance_shattered_halls Class Reference
#include <shattered_halls.h>
Public Member Functions
instance_shattered_halls (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void OnCreatureEnterCombat (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
void GauntletReset ()
void DoInitialGets ()
void DoSummonInitialWave ()
void DoSummonSHZealot ()
void DoBeginArcherAttack (bool leftOrRight)
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoCastGroupDebuff (uint32 uiSpellId)
void FailGauntlet ()
void StopGauntlet ()
void EndGauntlet ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiExecutionTimer
uint32 m_uiTeam
uint8 m_uiExecutionStage
uint8 m_uiPrisonersLeft
std::vector< ObjectGuid > m_vGauntletPermanentGuids
std::vector< ObjectGuid > m_vGauntletTemporaryGuids
std::vector< ObjectGuid > m_vGauntletBossGuids
std::vector< std::pair< ObjectGuid, uint32 > > m_vBlazeTimers
bool m_bInitialWavesSpawned
bool m_bPorungDoneYelling
bool m_bZealotOneOrTwo
bool m_gauntletStopped
Creature * m_porung
GuidList m_lSHArchers
uint8 m_uiNumInitialWaves
uint8 m_uiPorungYellNumber
uint32 m_uiInitialWaves_Delay
uint32 m_uiWaveTimer
uint32 m_uiPorungYellDelay
uint32 m_uiShootFlamingArrowTimer_1
uint32 m_uiShootFlamingArrowTimer_2
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 90 of file shattered_halls.h.
Constructor & Destructor Documentation
instance_shattered_halls()
instance_shattered_halls::instance_shattered_halls (Map * pMap)
Definition at line 30 of file shattered_halls.cpp.
References Initialize().
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_shattered_halls::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 277 of file shattered_halls.cpp.
References Object::GetGuidStr(), INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, INSTANCE_CONDITION_ID_HARD_MODE_3, INSTANCE_CONDITION_ID_NORMAL_MODE, m_uiPrisonersLeft, and script_error_log().
DoBeginArcherAttack()
void instance_shattered_halls::DoBeginArcherAttack (bool leftOrRight)
Definition at line 384 of file shattered_halls.cpp.
References Unit::CastSpell(), Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), InstanceData::instance, NPC_SHATTERED_HAND_ARCHER, SHOOT_FLAME_ARROW, and TRIGGERED_NONE.
Referenced by Update().
DoCastGroupDebuff()
void instance_shattered_halls::DoCastGroupDebuff (uint32 uiSpellId) private
Definition at line 611 of file shattered_halls.cpp.
References Unit::CastSpell(), Map::GetPlayers(), Unit::HasAura(), InstanceData::instance, and TRIGGERED_OLD_TRIGGERED.
Referenced by SetData(), and Update().
DoInitialGets()
void instance_shattered_halls::DoInitialGets ()
Definition at line 356 of file shattered_halls.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Map::IsRegularDifficulty(), m_porung, NPC_BLOOD_GUARD, and NPC_PORUNG.
Referenced by SetData().
DoSummonInitialWave()
void instance_shattered_halls::DoSummonInitialWave ()
Definition at line 361 of file shattered_halls.cpp.
References EMOTE_STATE_READY1H, firstWaveWaypoints, InstanceData::instance, m_uiNumInitialWaves, NPC_SHATTERED_HAND_ZEALOT, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, and zealotSpawnCoords.
Referenced by Update().
DoSummonSHZealot()
void instance_shattered_halls::DoSummonSHZealot ()
Definition at line 375 of file shattered_halls.cpp.
References EMOTE_STATE_READY1H, InstanceData::instance, NPC_SHATTERED_HAND_ZEALOT, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, zealotSpawnCoords, and zealotWaypoints.
Referenced by Update().
EndGauntlet()
void instance_shattered_halls::EndGauntlet () private
Definition at line 605 of file shattered_halls.cpp.
References m_vGauntletTemporaryGuids.
Referenced by FailGauntlet(), and SetData().
FailGauntlet()
void instance_shattered_halls::FailGauntlet () private
Definition at line 577 of file shattered_halls.cpp.
References EndGauntlet(), GauntletReset(), Map::GetCreature(), Map::GetGameObject(), InstanceData::instance, m_vBlazeTimers, m_vGauntletBossGuids, m_vGauntletPermanentGuids, and m_vGauntletTemporaryGuids.
Referenced by SetData().
GauntletReset()
void instance_shattered_halls::GauntletReset ()
Definition at line 340 of file shattered_halls.cpp.
References ARCHER_SHOOT_DELAY, m_bInitialWavesSpawned, m_bPorungDoneYelling, m_bZealotOneOrTwo, m_lSHArchers, m_porung, m_uiInitialWaves_Delay, m_uiNumInitialWaves, m_uiPorungYellDelay, m_uiPorungYellNumber, m_uiShootFlamingArrowTimer_1, m_uiShootFlamingArrowTimer_2, m_uiWaveTimer, and WAVE_TIMER.
Referenced by FailGauntlet(), and Initialize().
GetData()
uint32 instance_shattered_halls::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 246 of file shattered_halls.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by AreaTrigger_at_shattered_halls().
Initialize()
void instance_shattered_halls::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 40 of file shattered_halls.cpp.
References GauntletReset(), and m_auiEncounter.
Referenced by instance_shattered_halls().
Load()
void instance_shattered_halls::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 224 of file shattered_halls.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_shattered_halls::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 82 of file shattered_halls.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), Creature::IsTemporarySummon(), ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, m_vGauntletBossGuids, m_vGauntletPermanentGuids, m_vGauntletTemporaryGuids, NPC_BLOOD_GUARD, NPC_EXECUTIONER, NPC_KARGATH_BLADEFIST, NPC_NETHEKURSE, NPC_OFFICER_ALLIANCE, NPC_OFFICER_HORDE, NPC_PORUNG, NPC_SCOUT, NPC_SHATTERED_HAND_ARCHER, NPC_SHATTERED_HAND_ZEALOT, NPC_SOLDIER_ALLIANCE_2, NPC_SOLDIER_ALLIANCE_3, NPC_SOLDIER_HORDE_2, and NPC_SOLDIER_HORDE_3.
OnCreatureDeath()
void instance_shattered_halls::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 254 of file shattered_halls.cpp.
References DONE, Object::GetEntry(), NPC_EXECUTIONER, SetData(), and TYPE_EXECUTION.
OnCreatureEnterCombat()
void instance_shattered_halls::OnCreatureEnterCombat (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 260 of file shattered_halls.cpp.
References Object::GetEntry(), NPC_EXECUTIONER, SetData(), SPECIAL, and TYPE_EXECUTION.
OnCreatureEvade()
void instance_shattered_halls::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 268 of file shattered_halls.cpp.
References FAIL, Object::GetEntry(), IN_PROGRESS, NPC_EXECUTIONER, NPC_SHATTERED_HAND_ZEALOT, SetData(), TYPE_EXECUTION, and TYPE_GAUNTLET.
OnCreatureRespawn()
void instance_shattered_halls::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 115 of file shattered_halls.cpp.
References Object::GetEntry(), Creature::GetRespawnDelay(), NPC_FLAME_ARROW, Unit::SetCanEnterCombat(), and Creature::SetNoRewards().
OnObjectCreate()
void instance_shattered_halls::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 60 of file shattered_halls.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_BLAZE, GO_NETHEKURSE_DOOR, GO_NETHEKURSE_ENTER_DOOR, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_vBlazeTimers, GameObject::SetGoState(), and TYPE_NETHEKURSE.
OnPlayerEnter()
void instance_shattered_halls::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 46 of file shattered_halls.cpp.
References ALLIANCE, aSoldiersLocs, Player::GetTeam(), InstanceData::instance, Map::IsRegularDifficulty(), m_uiTeam, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Save()
const char* instance_shattered_halls::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 110 of file shattered_halls.h.
References m_strInstData.
SetData()
void instance_shattered_halls::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 123 of file shattered_halls.cpp.
References afExecutionerLoc, ALLIANCE, aSoldiersLocs, DoCastGroupDebuff(), DoInitialGets(), DONE, ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::DoUseOpenableObject(), EndGauntlet(), FAIL, FailGauntlet(), ScriptedInstance::GetPlayerInMap(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_NETHEKURSE_DOOR, GO_NETHEKURSE_ENTER_DOOR, IN_PROGRESS, InstanceData::instance, m_auiEncounter, SpawnLocation::m_fO, SpawnLocation::m_fX, SpawnLocation::m_fY, SpawnLocation::m_fZ, m_strInstData, SpawnLocation::m_uiAllianceEntry, m_uiExecutionStage, SpawnLocation::m_uiHordeEntry, m_uiTeam, NPC_EXECUTIONER, NPC_OFFICER_ALLIANCE, NPC_OFFICER_HORDE, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, SPELL_KARGATH_EXECUTIONER_1, StopGauntlet(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_BLADEFIST, TYPE_EXECUTION, TYPE_GAUNTLET, TYPE_NETHEKURSE, TYPE_OMROGG, UNIT_FIELD_FLAGS, UNIT_FLAG_SPAWNING, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by AreaTrigger_at_shattered_halls(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), and Update().
StopGauntlet()
void instance_shattered_halls::StopGauntlet () private
Definition at line 600 of file shattered_halls.cpp.
References m_gauntletStopped.
Referenced by SetData().
Update()
void instance_shattered_halls::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 415 of file shattered_halls.cpp.
References ALLIANCE, ARCHER_SHOOT_DELAY, DELAY_350_MILLI, DoBeginArcherAttack(), DoCastGroupDebuff(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), DoSummonInitialWave(), DoSummonSHZealot(), FAIL, Map::GetGameObject(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bInitialWavesSpawned, m_bPorungDoneYelling, m_bZealotOneOrTwo, m_gauntletStopped, m_porung, m_uiExecutionStage, m_uiExecutionTimer, m_uiInitialWaves_Delay, m_uiNumInitialWaves, m_uiPorungYellDelay, m_uiPorungYellNumber, m_uiPrisonersLeft, m_uiShootFlamingArrowTimer_1, m_uiShootFlamingArrowTimer_2, m_uiTeam, m_uiWaveTimer, m_vBlazeTimers, MINUTE, NPC_KARGATH_BLADEFIST, NPC_OFFICER_ALLIANCE, NPC_OFFICER_HORDE, NPC_SOLDIER_ALLIANCE_2, NPC_SOLDIER_ALLIANCE_3, NPC_SOLDIER_HORDE_2, NPC_SOLDIER_HORDE_3, PORUNG_AIM_YELL, PORUNG_FIRE_YELL, PORUNG_FORM_RANKS_YELL, PORUNG_READY_YELL, PORUNG_YELL_DELAY_1, PORUNG_YELL_DELAY_2, SAY_KARGATH_EXECUTE_ALLY, SAY_KARGATH_EXECUTE_HORDE, SetData(), SPELL_FLAMES, SPELL_KARGATH_EXECUTIONER_2, SPELL_KARGATH_EXECUTIONER_3, TRIGGERED_NONE, TYPE_EXECUTION, TYPE_GAUNTLET, urand(), and WAVE_TIMER.
Field Documentation
m_auiEncounter
uint32 instance_shattered_halls::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 133 of file shattered_halls.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), SetData(), and Update().
m_bInitialWavesSpawned
bool instance_shattered_halls::m_bInitialWavesSpawned private
Definition at line 147 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_bPorungDoneYelling
bool instance_shattered_halls::m_bPorungDoneYelling private
Definition at line 148 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_bZealotOneOrTwo
bool instance_shattered_halls::m_bZealotOneOrTwo private
Definition at line 149 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_gauntletStopped
bool instance_shattered_halls::m_gauntletStopped private
Definition at line 150 of file shattered_halls.h.
Referenced by StopGauntlet(), and Update().
m_lSHArchers
GuidList instance_shattered_halls::m_lSHArchers private
Definition at line 153 of file shattered_halls.h.
Referenced by GauntletReset().
m_porung
Creature* instance_shattered_halls::m_porung private
Definition at line 152 of file shattered_halls.h.
Referenced by DoInitialGets(), GauntletReset(), and Update().
m_strInstData
std::string instance_shattered_halls::m_strInstData private
Definition at line 134 of file shattered_halls.h.
Referenced by Save(), and SetData().
m_uiExecutionStage
uint8 instance_shattered_halls::m_uiExecutionStage private
Definition at line 138 of file shattered_halls.h.
Referenced by SetData(), and Update().
m_uiExecutionTimer
uint32 instance_shattered_halls::m_uiExecutionTimer private
Definition at line 136 of file shattered_halls.h.
Referenced by Update().
m_uiInitialWaves_Delay
uint32 instance_shattered_halls::m_uiInitialWaves_Delay private
Definition at line 157 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_uiNumInitialWaves
uint8 instance_shattered_halls::m_uiNumInitialWaves private
Definition at line 155 of file shattered_halls.h.
Referenced by DoSummonInitialWave(), GauntletReset(), and Update().
m_uiPorungYellDelay
uint32 instance_shattered_halls::m_uiPorungYellDelay private
Definition at line 159 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_uiPorungYellNumber
uint8 instance_shattered_halls::m_uiPorungYellNumber private
Definition at line 156 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_uiPrisonersLeft
uint8 instance_shattered_halls::m_uiPrisonersLeft private
Definition at line 139 of file shattered_halls.h.
Referenced by CheckConditionCriteriaMeet(), and Update().
m_uiShootFlamingArrowTimer_1
uint32 instance_shattered_halls::m_uiShootFlamingArrowTimer_1 private
Definition at line 160 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_uiShootFlamingArrowTimer_2
uint32 instance_shattered_halls::m_uiShootFlamingArrowTimer_2 private
Definition at line 161 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_uiTeam
uint32 instance_shattered_halls::m_uiTeam private
Definition at line 137 of file shattered_halls.h.
Referenced by OnPlayerEnter(), SetData(), and Update().
m_uiWaveTimer
uint32 instance_shattered_halls::m_uiWaveTimer private
Definition at line 158 of file shattered_halls.h.
Referenced by GauntletReset(), and Update().
m_vBlazeTimers
std::vector<std::pair<ObjectGuid, uint32> > instance_shattered_halls::m_vBlazeTimers private
Definition at line 145 of file shattered_halls.h.
Referenced by FailGauntlet(), OnObjectCreate(), and Update().
m_vGauntletBossGuids
std::vector<ObjectGuid> instance_shattered_halls::m_vGauntletBossGuids private
Definition at line 143 of file shattered_halls.h.
Referenced by FailGauntlet(), and OnCreatureCreate().
m_vGauntletPermanentGuids
std::vector<ObjectGuid> instance_shattered_halls::m_vGauntletPermanentGuids private
Definition at line 141 of file shattered_halls.h.
Referenced by FailGauntlet(), and OnCreatureCreate().
m_vGauntletTemporaryGuids
std::vector<ObjectGuid> instance_shattered_halls::m_vGauntletTemporaryGuids private
Definition at line 142 of file shattered_halls.h.
Referenced by EndGauntlet(), FailGauntlet(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
shattered_halls.h
shattered_halls.cpp