CMaNGOS_WoTLK: Movement::Spline< length_type > Class Template Reference
Movement::Spline< length_type > Class Template Reference
#include <spline.h>
Public Types
typedef length_type LengthType
typedef std::vector< length_type > LengthArray
Public Types inherited from Movement::SplineBase
enum EvaluationMode {
ModeLinear , ModeCatmullrom , ModeBezier3_Unused , UninitializedMode ,
ModesEnd
}
typedef int index_type
typedef std::vector< Vector3 > ControlArray
Public Member Functions
Spline ()
void evaluate_percent (float t, Vector3 &c) const
Calculates the position for given t.
void evaluate_derivative (float t, Vector3 &hermite) const
Calculates derivation for given t.
void evaluate_percent (index_type Idx, float u, Vector3 &c) const
Calculates the position for given segment Idx, and percent of segment length t.
void evaluate_derivative (index_type Idx, float u, Vector3 &c) const
Caclulates derivation for index Idx, and percent of segment length t.
index_type computeIndexInBounds (float t) const
void computeIndex (float t, index_type &out_idx, float &out_u) const
void init_spline (const Vector3 *controls, index_type count, EvaluationMode m)
Initializes spline.
void init_cyclic_spline (const Vector3 *controls, index_type count, EvaluationMode m, index_type cyclic_point)
template<class Init >
void init_spline_custom (Init &initializer)
As i can see there are a lot of ways how spline can be initialized would be no harm to have some custom initializers.
void initLengths ()
Initializes lengths with SplineBase::SegLength method.
template<class T >
void initLengths (T &cacher)
Initializes lengths in some custom way Note that value returned by cacher must be greater or equal to previous value.
length_type length () const
Returns length of the whole spline.
length_type length (index_type first, index_type last) const
Returns length between given nodes.
length_type length (index_type Idx) const
void set_length (index_type i, length_type length)
void clear ()
Public Member Functions inherited from Movement::SplineBase
SplineBase ()
void evaluate_percent (index_type Idx, float u, Vector3 &c) const
Caclulates the position for given segment Idx, and percent of segment length t.
void evaluate_derivative (index_type Idx, float u, Vector3 &hermite) const
Caclulates derivation in index Idx, and percent of segment length t.
index_type first () const
Bounds for spline indexes.
index_type last () const
bool empty () const
EvaluationMode mode () const
bool isCyclic () const
const ControlArray & getPoints () const
index_type getPointCount () const
const Vector3 & getPoint (index_type i) const
void init_spline (const Vector3 *controls, index_type count, EvaluationMode m)
Initializes spline.
void init_cyclic_spline (const Vector3 *controls, index_type count, EvaluationMode m, index_type cyclic_point)
template<class Init >
void init_spline (Init &initializer)
As i can see there are a lot of ways how spline can be initialized would be no harm to have some custom initializers.
void clear ()
float SegLength (index_type i) const
Calculates distance between [i; i+1] points, assumes that index i is in bounds.
std::string ToString () const
Protected Member Functions
index_type computeIndexInBounds (length_type length) const
Protected Member Functions inherited from Movement::SplineBase
void EvaluateLinear (index_type, float, Vector3 &) const
void EvaluateCatmullRom (index_type, float, Vector3 &) const
void EvaluateBezier3 (index_type, float, Vector3 &) const
void EvaluateDerivativeLinear (index_type, float, Vector3 &) const
void EvaluateDerivativeCatmullRom (index_type, float, Vector3 &) const
void EvaluateDerivativeBezier3 (index_type, float, Vector3 &) const
float SegLengthLinear (index_type) const
float SegLengthCatmullRom (index_type) const
float SegLengthBezier3 (index_type) const
void InitLinear (const Vector3 *, index_type, bool, index_type)
void InitCatmullRom (const Vector3 *, index_type, bool, index_type)
void InitBezier3 (const Vector3 *, index_type, bool, index_type)
void UninitializedSpline () const
Protected Attributes
LengthArray lengths
Protected Attributes inherited from Movement::SplineBase
ControlArray points
index_type index_lo
index_type index_hi
uint8 m_mode
bool cyclic
Additional Inherited Members
Protected Types inherited from Movement::SplineBase
enum { STEPS_PER_SEGMENT = 3 }
typedef void(SplineBase::* EvaluationMethtod) (index_type, float, Vector3 &) const
typedef float(SplineBase::* SegLenghtMethtod) (index_type) const
typedef void(SplineBase::* InitMethtod) (const Vector3 *, index_type, bool, index_type)
Static Protected Attributes inherited from Movement::SplineBase
static EvaluationMethtod evaluators [ModesEnd]
static EvaluationMethtod derivative_evaluators [ModesEnd]
static SegLenghtMethtod seglengths [ModesEnd]
static InitMethtod initializers [ModesEnd]
Detailed Description
template<typename length_type>
class Movement::Spline< length_type >
Definition at line 135 of file spline.h.
Member Typedef Documentation
LengthArray
template<typename length_type > typedef std::vector<length_type> Movement::Spline< length_type >::LengthArray
Definition at line 139 of file spline.h.
LengthType
template<typename length_type > typedef length_type Movement::Spline< length_type >::LengthType
Definition at line 138 of file spline.h.
Constructor & Destructor Documentation
Spline()
template<typename length_type > Movement::Spline< length_type >::Spline () inline explicit
Definition at line 147 of file spline.h.
Referenced by TransportMgr::GenerateWaypoints().
Member Function Documentation
clear()
template<typename length_type > void Movement::Spline< length_type >::clear
Definition at line 94 of file spline.impl.h.
References Movement::SplineBase::clear().
Referenced by Movement::MoveSpline::Initialize().
computeIndex()
template<typename length_type > void Movement::Spline< length_type >::computeIndex (float t, index_type & out_idx, float & out_u) const
Definition at line 67 of file spline.impl.h.
References MANGOS_ASSERT.
computeIndexInBounds() [1/2]
template<typename length_type > SplineBase::index_type Movement::Spline< length_type >::computeIndexInBounds (float t) const
Definition at line 76 of file spline.impl.h.
References MANGOS_ASSERT.
computeIndexInBounds() [2/2]
template<typename length_type > SplineBase::index_type Movement::Spline< length_type >::computeIndexInBounds (length_type length) const protected
Definition at line 40 of file spline.impl.h.
evaluate_derivative() [1/2]
template<typename length_type > void Movement::Spline< length_type >::evaluate_derivative (float t, Vector3 & hermite) const
Calculates derivation for given t.
Parameters
t - percent of spline's length, assumes that t in range [0, 1].
Definition at line 32 of file spline.impl.h.
Referenced by Movement::MoveSpline::ComputePosition(), and TransportMgr::GenerateWaypoints().
evaluate_derivative() [2/2]
template<typename length_type > void Movement::Spline< length_type >::evaluate_derivative (index_type Idx, float u, Vector3 & c) const inline
Caclulates derivation for index Idx, and percent of segment length t.
Parameters
Idx - spline segment index, should be in range [first, last)
t - percent of spline segment length, assumes that t in range [0, 1].
Definition at line 165 of file spline.h.
References Movement::SplineBase::evaluate_derivative().
evaluate_percent() [1/2]
template<typename length_type > void Movement::Spline< length_type >::evaluate_percent (float t, Vector3 & c) const
Calculates the position for given t.
Parameters
t - percent of spline's length, assumes that t in range [0, 1].
Definition at line 24 of file spline.impl.h.
Referenced by Movement::MoveSpline::ComputePosition().
evaluate_percent() [2/2]
template<typename length_type > void Movement::Spline< length_type >::evaluate_percent (index_type Idx, float u, Vector3 & c) const inline
Calculates the position for given segment Idx, and percent of segment length t.
Parameters
t = partial_segment_length / whole_segment_length
Idx - spline segment index, should be in range [first, last).
Definition at line 160 of file spline.h.
References Movement::SplineBase::evaluate_percent().
init_cyclic_spline()
template<typename length_type > void Movement::Spline< length_type >::init_cyclic_spline (const Vector3 * controls, index_type count, EvaluationMode m, index_type cyclic_point) inline
Definition at line 173 of file spline.h.
References Movement::SplineBase::init_cyclic_spline().
Referenced by Movement::MoveSpline::init_spline().
init_spline()
template<typename length_type > void Movement::Spline< length_type >::init_spline (const Vector3 * controls, index_type count, EvaluationMode m) inline
Initializes spline.
Don't call other methods while spline not initialized.
Definition at line 172 of file spline.h.
References Movement::SplineBase::init_spline().
Referenced by TransportMgr::GenerateWaypoints(), and Movement::MoveSpline::init_spline().
init_spline_custom()
template<typename length_type > template<class Init > void Movement::Spline< length_type >::init_spline_custom (Init & initializer) inline
As i can see there are a lot of ways how spline can be initialized would be no harm to have some custom initializers.
Definition at line 177 of file spline.h.
References Movement::SplineBase::cyclic, Movement::SplineBase::index_hi, Movement::SplineBase::index_lo, Movement::SplineBase::m_mode, and Movement::SplineBase::points.
Referenced by TransportMgr::GenerateWaypoints().
initLengths() [1/2]
template<typename length_type > void Movement::Spline< length_type >::initLengths
Initializes lengths with SplineBase::SegLength method.
Definition at line 82 of file spline.impl.h.
Referenced by TransportMgr::GenerateWaypoints(), and Movement::MoveSpline::init_spline().
initLengths() [2/2]
template<typename length_type > template<class T > void Movement::Spline< length_type >::initLengths (T & cacher) inline
Initializes lengths in some custom way Note that value returned by cacher must be greater or equal to previous value.
Definition at line 187 of file spline.h.
References Movement::SplineBase::index_hi, Movement::SplineBase::index_lo, Movement::Spline< length_type >::lengths, and MANGOS_ASSERT.
length() [1/3]
template<typename length_type > length_type Movement::Spline< length_type >::length () const inline
Returns length of the whole spline.
Definition at line 207 of file spline.h.
References Movement::SplineBase::index_hi, and Movement::Spline< length_type >::lengths.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::ComputeTimeToIndex(), Movement::MoveSpline::Duration(), Movement::MoveSpline::DurationAtPointIdx(), TransportMgr::GenerateWaypoints(), Movement::MoveSpline::init_spline(), Movement::MoveSpline::next_timestamp(), and Movement::Spline< length_type >::set_length().
length() [2/3]
template<typename length_type > length_type Movement::Spline< length_type >::length (index_type first, index_type last) const inline
Returns length between given nodes.
Definition at line 209 of file spline.h.
References Movement::SplineBase::first(), Movement::SplineBase::last(), and Movement::Spline< length_type >::lengths.
length() [3/3]
template<typename length_type > length_type Movement::Spline< length_type >::length (index_type Idx) const inline
Definition at line 210 of file spline.h.
References Movement::Spline< length_type >::lengths.
set_length()
template<typename length_type > void Movement::Spline< length_type >::set_length (index_type i, length_type length) inline
Definition at line 212 of file spline.h.
References Movement::Spline< length_type >::length(), and Movement::Spline< length_type >::lengths.
Referenced by Movement::MoveSpline::init_spline().
Field Documentation
lengths
template<typename length_type > LengthArray Movement::Spline< length_type >::lengths protected
Definition at line 142 of file spline.h.
Referenced by Movement::Spline< length_type >::initLengths(), Movement::Spline< length_type >::length(), and Movement::Spline< length_type >::set_length().
The documentation for this class was generated from the following files:
spline.h
spline.impl.h