CMaNGOS_WoTLK: TransportInfo Class Reference
TransportInfo Class Reference
to provide abstract support for transported entities
A class to provide basic information for each transported passenger.
#include <TransportSystem.h>
Public Member Functions
TransportInfo (WorldObject *owner, TransportBase *transport, float lx, float ly, float lz, float lo, uint8 seat)
void SetLocalPosition (float lx, float ly, float lz, float lo)
void SetTransportSeat (uint8 seat)
WorldObject * GetTransport () const
ObjectGuid GetTransportGuid () const
bool IsOnVehicle () const
bool HasOnBoard (WorldObject const *passenger) const
uint8 GetTransportSeat () const
float GetLocalOrientation () const
float GetLocalPositionX () const
float GetLocalPositionY () const
float GetLocalPositionZ () const
void GetLocalPosition (float &lx, float &ly, float &lz, float &lo) const
void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const
void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const
Private Attributes
WorldObject * m_owner
Passenger.
TransportBase * m_transport
Transporter.
Position m_localPosition
uint8 m_seat
Detailed Description
A class to provide basic information for each transported passenger.
This includes
local positions
Accessors to get the transporter
Definition at line 96 of file TransportSystem.h.
Member Function Documentation
CalculatePassengerOffset()
void TransportInfo::CalculatePassengerOffset (float & x, float & y, float & z, float * o = nullptr) const inline
Definition at line 133 of file TransportSystem.h.
References TransportBase::CalculatePassengerOffset(), and m_transport.
CalculatePassengerPosition()
void TransportInfo::CalculatePassengerPosition (float & x, float & y, float & z, float * o = nullptr) const inline
Definition at line 129 of file TransportSystem.h.
References TransportBase::CalculatePassengerPosition(), and m_transport.
GetLocalOrientation()
float TransportInfo::GetLocalOrientation () const inline
Definition at line 117 of file TransportSystem.h.
References m_localPosition, and Position::o.
GetLocalPosition()
void TransportInfo::GetLocalPosition (float & lx, float & ly, float & lz, float & lo) const inline
Definition at line 121 of file TransportSystem.h.
References m_localPosition, Position::o, Position::x, Position::y, and Position::z.
Referenced by Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
GetLocalPositionX()
float TransportInfo::GetLocalPositionX () const inline
Definition at line 118 of file TransportSystem.h.
References m_localPosition, and Position::x.
GetLocalPositionY()
float TransportInfo::GetLocalPositionY () const inline
Definition at line 119 of file TransportSystem.h.
References m_localPosition, and Position::y.
GetLocalPositionZ()
float TransportInfo::GetLocalPositionZ () const inline
Definition at line 120 of file TransportSystem.h.
References m_localPosition, and Position::z.
GetTransport()
WorldObject* TransportInfo::GetTransport () const inline
Definition at line 106 of file TransportSystem.h.
References TransportBase::GetOwner(), and m_transport.
Referenced by trial_companion_commonAI::AttackStart(), WorldSession::BuildPartyMemberStatsChangedPacket(), VehicleInfo::CanBoard(), BattlefieldWG::CheckAchievementCriteriaMeet(), BattleGroundSA::CheckAchievementCriteriaMeet(), BattleGroundIC::CheckAchievementCriteriaMeet(), Spell::CheckTarget(), Spell::CheckVehicle(), trial_companion_commonAI::DamageTaken(), Aura::HandleAuraDummy(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleRequestVehicleNextSeat(), WorldSession::HandleRequestVehicleSwitchSeat(), TransportBase::HasOnBoard(), instance_eye_of_eternity::OnCreatureDeath(), Unit::SetDeathState(), Spell::SetTargetMap(), Unit::TriggerHomeEvents(), and trial_companion_commonAI::UpdateAI().
GetTransportGuid()
ObjectGuid TransportInfo::GetTransportGuid () const inline
Definition at line 107 of file TransportSystem.h.
References Object::GetObjectGuid(), TransportBase::GetOwner(), and m_transport.
Referenced by Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
GetTransportSeat()
uint8 TransportInfo::GetTransportSeat () const inline
Definition at line 116 of file TransportSystem.h.
References m_seat.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket(), WorldSession::HandleEjectPassenger(), WorldSession::HandleRequestPartyMemberStatsOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleRequestVehicleNextSeat(), Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
HasOnBoard()
bool TransportInfo::HasOnBoard (WorldObject const * passenger) const inline
Definition at line 113 of file TransportSystem.h.
References TransportBase::HasOnBoard(), and m_transport.
Referenced by Spell::CheckCast().
IsOnVehicle()
bool TransportInfo::IsOnVehicle () const inline
Definition at line 110 of file TransportSystem.h.
References TransportBase::GetOwner(), Object::GetTypeId(), m_transport, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by trial_companion_commonAI::AttackStart(), Spell::CheckCast(), Aura::HandleAuraDummy(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleDismissControlledVehicle(), WorldSession::HandleGameObjectUseOpcode(), WorldSession::HandleRequestVehicleExit(), WorldSession::HandleRequestVehicleNextSeat(), WorldSession::HandleRequestVehicleSwitchSeat(), instance_eye_of_eternity::OnCreatureDeath(), Spell::SetTargetMap(), and trial_companion_commonAI::UpdateAI().
SetTransportSeat()
void TransportInfo::SetTransportSeat (uint8 seat) inline
Definition at line 103 of file TransportSystem.h.
References m_seat.
Field Documentation
m_localPosition
Position TransportInfo::m_localPosition private
Definition at line 141 of file TransportSystem.h.
Referenced by GetLocalOrientation(), GetLocalPosition(), GetLocalPositionX(), GetLocalPositionY(), GetLocalPositionZ(), and SetLocalPosition().
m_owner
WorldObject* TransportInfo::m_owner private
Passenger.
Definition at line 139 of file TransportSystem.h.
Referenced by SetLocalPosition().
m_seat
uint8 TransportInfo::m_seat private
Definition at line 142 of file TransportSystem.h.
Referenced by GetTransportSeat(), and SetTransportSeat().
m_transport
TransportBase* TransportInfo::m_transport private
Transporter.
Definition at line 140 of file TransportSystem.h.
Referenced by CalculatePassengerOffset(), CalculatePassengerPosition(), GetTransport(), GetTransportGuid(), HasOnBoard(), IsOnVehicle(), SetLocalPosition(), and TransportInfo().
The documentation for this class was generated from the following files:
TransportSystem.h
TransportSystem.cpp