CMaNGOS_WoTLK: ThreatCalcHelper Class Reference
ThreatCalcHelper Class Reference
#include <ThreatManager.h>
Static Public Member Functions
static float CalcThreat (Unit *hatedUnit, Unit *hatingUnit, float threat, bool crit, SpellSchoolMask schoolMask, SpellEntry const *threatSpell, bool assist)
Detailed Description
Definition at line 41 of file ThreatManager.h.
Member Function Documentation
CalcThreat()
float ThreatCalcHelper::CalcThreat (Unit * hatedUnit, Unit * hatingUnit, float threat, bool crit, SpellSchoolMask schoolMask, SpellEntry const * threatSpell, bool assist) static
Definition at line 34 of file ThreatManager.cpp.
References Unit::ApplyTotalThreatModifier(), SpellEntry::EffectApplyAuraName, SpellEntry::EffectBasePoints, Unit::GetNoThreatState(), WorldObject::GetSpellModOwner(), Unit::GetTotalAuraMultiplierByMiscMask(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, Unit::IsSupportThreatOnly(), MAX_EFFECT_INDEX, SPELL_ATTR_EX_NO_THREAT, SPELL_AURA_MOD_CRITICAL_THREAT, SPELL_AURA_MOD_TOTAL_THREAT, SPELLMOD_THREAT, and TYPEID_PLAYER.
Referenced by ThreatManager::addThreat().
The documentation for this class was generated from the following files:
ThreatManager.h
ThreatManager.cpp