CMaNGOS_WoTLK: VMAP::WorldModel Class Reference
VMAP::WorldModel Class Reference
#include <WorldModel.h>
Public Member Functions
WorldModel ()
void setGroupModels (std::vector< GroupModel > &models)
pass group models to WorldModel and create BIH. Passed vector is swapped with old geometry!
void setRootWmoID (uint32 id)
bool IntersectRay (const G3D::Ray &ray, float &distance, bool stopAtFirstHit, bool ignoreM2Model=false) const
bool IntersectPoint (const G3D::Vector3 &p, const G3D::Vector3 &down, float &dist, AreaInfo &info) const
bool GetLocationInfo (const G3D::Vector3 &p, const G3D::Vector3 &down, float &dist, GroupLocationInfo &info) const
bool writeFile (const std::string &filename)
bool readFile (const std::string &filename)
void setModelFlags (uint32 newFlags)
uint32 getModelFlags () const
Protected Attributes
uint32 RootWMOID
std::vector< GroupModel > groupModels
BIH groupTree
uint32 modelFlags
Detailed Description
Holds a model (converted M2 or WMO) in its original coordinate space
Definition at line 113 of file WorldModel.h.
Constructor & Destructor Documentation
WorldModel()
VMAP::WorldModel::WorldModel () inline
Definition at line 116 of file WorldModel.h.
Member Function Documentation
GetLocationInfo()
bool VMAP::WorldModel::GetLocationInfo (const G3D::Vector3 & p, const G3D::Vector3 & down, float & dist, GroupLocationInfo & info) const
Definition at line 521 of file WorldModel.cpp.
References groupModels, groupTree, VMAP::WModelAreaCallback::hit, VMAP::GroupLocationInfo::hitModel, BIH::intersectPoint(), VMAP::GroupLocationInfo::rootId, RootWMOID, and VMAP::WModelAreaCallback::zDist.
Referenced by VMAP::ModelInstance::GetLocationInfo().
getModelFlags()
uint32 VMAP::WorldModel::getModelFlags () const inline
Definition at line 127 of file WorldModel.h.
References modelFlags.
IntersectPoint()
bool VMAP::WorldModel::IntersectPoint (const G3D::Vector3 & p, const G3D::Vector3 & down, float & dist, AreaInfo & info) const
Definition at line 502 of file WorldModel.cpp.
References VMAP::AreaInfo::flags, VMAP::AreaInfo::groupId, groupModels, groupTree, VMAP::WModelAreaCallback::hit, BIH::intersectPoint(), VMAP::AreaInfo::result, VMAP::AreaInfo::rootId, RootWMOID, and VMAP::WModelAreaCallback::zDist.
Referenced by VMAP::ModelInstance::intersectPoint().
IntersectRay()
bool VMAP::WorldModel::IntersectRay (const G3D::Ray & ray, float & distance, bool stopAtFirstHit, bool ignoreM2Model = false) const
Definition at line 448 of file WorldModel.cpp.
References groupModels, groupTree, VMAP::WModelRayCallBack::hit, BIH::intersectRay(), VMAP::MOD_M2, and modelFlags.
Referenced by VMAP::ModelInstance::intersectRay(), and GameObjectModel::intersectRay().
readFile()
bool VMAP::WorldModel::readFile (const std::string & filename)
Definition at line 571 of file WorldModel.cpp.
References groupModels, groupTree, VMAP::readChunk(), BIH::readFromFile(), RootWMOID, and VMAP::VMAP_MAGIC.
Referenced by VMAP::VMapManager2::acquireModelInstance().
setGroupModels()
void VMAP::WorldModel::setGroupModels (std::vector< GroupModel > & models)
pass group models to WorldModel and create BIH. Passed vector is swapped with old geometry!
Definition at line 429 of file WorldModel.cpp.
References BIH::build(), groupModels, and groupTree.
Referenced by VMAP::TileAssembler::convertRawFile().
setModelFlags()
void VMAP::WorldModel::setModelFlags (uint32 newFlags) inline
Definition at line 126 of file WorldModel.h.
References modelFlags.
Referenced by GameObjectModel::initialize(), VMAP::StaticMapTree::InitMap(), and VMAP::StaticMapTree::LoadMapTile().
setRootWmoID()
void VMAP::WorldModel::setRootWmoID (uint32 id) inline
Definition at line 120 of file WorldModel.h.
References RootWMOID.
Referenced by VMAP::TileAssembler::convertRawFile().
writeFile()
bool VMAP::WorldModel::writeFile (const std::string & filename)
Definition at line 538 of file WorldModel.cpp.
References groupModels, groupTree, RootWMOID, VMAP::VMAP_MAGIC, and BIH::writeToFile().
Referenced by VMAP::TileAssembler::convertRawFile().
Field Documentation
groupModels
std::vector<GroupModel> VMAP::WorldModel::groupModels protected
Definition at line 130 of file WorldModel.h.
Referenced by GetLocationInfo(), IntersectPoint(), IntersectRay(), readFile(), setGroupModels(), and writeFile().
groupTree
BIH VMAP::WorldModel::groupTree protected
Definition at line 131 of file WorldModel.h.
Referenced by GetLocationInfo(), IntersectPoint(), IntersectRay(), readFile(), setGroupModels(), and writeFile().
modelFlags
uint32 VMAP::WorldModel::modelFlags protected
Definition at line 132 of file WorldModel.h.
Referenced by getModelFlags(), IntersectRay(), and setModelFlags().
RootWMOID
uint32 VMAP::WorldModel::RootWMOID protected
Definition at line 129 of file WorldModel.h.
Referenced by GetLocationInfo(), IntersectPoint(), readFile(), setRootWmoID(), and writeFile().
The documentation for this class was generated from the following files:
WorldModel.h
WorldModel.cpp