CMaNGOS_WoTLK: WardenWin Class Reference
WardenWin Class Reference final
#include <WardenWin.hpp>
Public Member Functions
WardenWin (WorldSession *session, const BigNumber &K, SessionAnticheatInterface *anticheat)
void Update (uint32 diff)
virtual void SetCharEnumPacket (WorldPacket &&packet)
virtual void SendPlayerInfo (ChatHandler *handler, bool includeFingerprint) const
Public Member Functions inherited from Warden
virtual ~Warden ()=default
void HandlePacket (WorldPacket &recvData)
const WardenModule * GetModule () const
uint8 GetXor () const
Static Public Member Functions
static void LoadScriptedScans ()
Static Public Member Functions inherited from Warden
static void LoadScriptedScans ()
Private Member Functions
void ValidateEndScene (const std::vector< uint8 > &code)
virtual uint32 GetScanFlags () const
virtual void InitializeClient ()
void BuildLuaInit (const std::string &module, bool fastcall, uint32 offset, ByteBuffer &out) const
void BuildFileHashInit (const std::string &module, bool asyncparam, uint32 openOffset, uint32 sizeOffset, uint32 readOffset, uint32 closeOffset, ByteBuffer &out) const
void BuildTimingInit (const std::string &module, uint32 offset, bool set, ByteBuffer &out) const
Private Attributes
uint32 _wardenAddress
WIN_SYSTEM_INFO _sysInfo
bool _sysInfoSaved
bool _proxifierFound
std::string _hypervisors
WorldPacket _charEnum
uint32 _lastClientTime
uint32 _lastHardwareActionTime
uint32 _lastTimeCheckServer
bool _endSceneFound
uint32 _endSceneAddress
Additional Inherited Members
Static Public Attributes inherited from Warden
static constexpr size_t MaxRequest = 256
static constexpr size_t MaxReply = 256
Protected Member Functions inherited from Warden
Warden (WorldSession *session, const WardenModule *module, const BigNumber &K, SessionAnticheatInterface *anticheat)
std::vector< std::shared_ptr< const Scan > > SelectScans (ScanFlags flags) const
void BeginScanClock ()
void EnqueueScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void RequestScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void SendPacket (const ByteBuffer &buff)
Static Protected Member Functions inherited from Warden
static uint32 BuildChecksum (const uint8 *data, size_t size)
Protected Attributes inherited from Warden
NamreebAnticheat::SessionAnticheat *const _anticheat
WorldSession *const _session
const WardenModule *const _module
uint8 _xor
bool _initialized
std::vector< std::shared_ptr< const Scan > > _pendingScans
std::vector< std::shared_ptr< const Scan > > _enqueuedScans
Static Protected Attributes inherited from Warden
static constexpr size_t KeyLength = 16
Detailed Description
Definition at line 44 of file WardenWin.hpp.
Constructor & Destructor Documentation
WardenWin()
WardenWin::WardenWin (WorldSession * session, const BigNumber & K, SessionAnticheatInterface * anticheat)
Definition at line 590 of file wardenwin.cpp.
References _sysInfo.
Member Function Documentation
BuildFileHashInit()
void WardenWin::BuildFileHashInit (const std::string & module, bool asyncparam, uint32 openOffset, uint32 sizeOffset, uint32 readOffset, uint32 closeOffset, ByteBuffer & out) const private
Definition at line 535 of file wardenwin.cpp.
References ByteBuffer::append(), Warden::BuildChecksum(), ByteBuffer::contents(), WARDEN_SMSG_MODULE_INITIALIZE, and ByteBuffer::wpos().
Referenced by InitializeClient().
BuildLuaInit()
void WardenWin::BuildLuaInit (const std::string & module, bool fastcall, uint32 offset, ByteBuffer & out) const private
Definition at line 509 of file wardenwin.cpp.
References ByteBuffer::append(), Warden::BuildChecksum(), ByteBuffer::contents(), WARDEN_SMSG_MODULE_INITIALIZE, and ByteBuffer::wpos().
Referenced by InitializeClient().
BuildTimingInit()
void WardenWin::BuildTimingInit (const std::string & module, uint32 offset, bool set, ByteBuffer & out) const private
Definition at line 565 of file wardenwin.cpp.
References ByteBuffer::append(), Warden::BuildChecksum(), ByteBuffer::contents(), WARDEN_SMSG_MODULE_INITIALIZE, and ByteBuffer::wpos().
Referenced by InitializeClient().
GetScanFlags()
uint32 WardenWin::GetScanFlags () const private virtual
Implements Warden.
Definition at line 655 of file wardenwin.cpp.
References Warden::_session, AdvancedScan, WorldSession::GetAccountId(), WorldSession::GetAccountMaxLevel(), WorldSession::GetGameBuild(), WorldSession::KickPlayer(), None, sAnticheatConfig, sLog, and WinBuild12340.
InitializeClient()
void WardenWin::InitializeClient () private virtual
Implements Warden.
Definition at line 674 of file wardenwin.cpp.
References Warden::_initialized, ByteBuffer::append(), BuildFileHashInit(), BuildLuaInit(), BuildTimingInit(), Warden::SendPacket(), and ByteBuffer::wpos().
LoadScriptedScans()
void WardenWin::LoadScriptedScans () static
Definition at line 376 of file wardenwin.cpp.
References _sysInfo, _wardenAddress, WIN_SYSTEM_INFO::dwOemId, InitialLogin, None, READ_MEMORY, sLog, sWardenScanMgr, and WinAllBuild.
Referenced by Warden::LoadScriptedScans().
SendPlayerInfo()
void WardenWin::SendPlayerInfo (ChatHandler * handler, bool includeFingerprint) const virtual
Implements Warden.
Definition at line 757 of file wardenwin.cpp.
References _endSceneAddress, _endSceneFound, _hypervisors, _lastClientTime, _lastHardwareActionTime, _lastTimeCheckServer, _proxifierFound, _sysInfo, WIN_SYSTEM_INFO::dwActiveProcessorMask, WIN_SYSTEM_INFO::dwNumberOfProcessors, WIN_SYSTEM_INFO::dwPageSize, WIN_SYSTEM_INFO::dwProcessorType, WorldTimer::getMSTime(), WIN_SYSTEM_INFO::lpMaximumApplicationAddress, ChatHandler::PSendSysMessage(), ChatHandler::SendSysMessage(), WIN_SYSTEM_INFO::wProcessorArchitecture, and WIN_SYSTEM_INFO::wProcessorRevision.
SetCharEnumPacket()
void WardenWin::SetCharEnumPacket (WorldPacket && packet) virtual
Implements Warden.
Definition at line 748 of file wardenwin.cpp.
References _charEnum, Warden::_session, _sysInfoSaved, and WorldSession::SendPacket().
Update()
void WardenWin::Update (uint32 diff) virtual
Reimplemented from Warden.
Definition at line 699 of file wardenwin.cpp.
References Warden::_anticheat, _charEnum, Warden::_initialized, Warden::_session, _sysInfo, _sysInfoSaved, SqlStatement::addUInt32(), Database::BeginTransaction(), NamreebAnticheat::SessionAnticheat::CleanupFingerprintHistory(), ByteBuffer::clear(), Database::CommitTransaction(), Database::CreateStatement(), WIN_SYSTEM_INFO::dwActiveProcessorMask, WIN_SYSTEM_INFO::dwNumberOfProcessors, WIN_SYSTEM_INFO::dwPageSize, WIN_SYSTEM_INFO::dwProcessorType, ByteBuffer::empty(), WorldSession::GetAccountId(), NamreebAnticheat::SessionAnticheat::GetFingerprint(), WorldSession::GetRemoteAddress(), LoginDatabase, WIN_SYSTEM_INFO::lpMaximumApplicationAddress, realmID, WorldSession::SendPacket(), Warden::Update(), WIN_SYSTEM_INFO::wProcessorArchitecture, and WIN_SYSTEM_INFO::wProcessorRevision.
ValidateEndScene()
void WardenWin::ValidateEndScene (const std::vector< uint8 > & code) private
Definition at line 599 of file wardenwin.cpp.
References _endSceneAddress, Warden::_session, Warden::EnqueueScans(), WorldSession::GetAccountId(), WorldSession::GetRemoteAddress(), None, ByteBuffer::read(), sAnticheatConfig, and sLog.
Field Documentation
_charEnum
WorldPacket WardenWin::_charEnum private
Definition at line 58 of file WardenWin.hpp.
Referenced by SetCharEnumPacket(), and Update().
_endSceneAddress
uint32 WardenWin::_endSceneAddress private
Definition at line 65 of file WardenWin.hpp.
Referenced by SendPlayerInfo(), and ValidateEndScene().
_endSceneFound
bool WardenWin::_endSceneFound private
Definition at line 64 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_hypervisors
std::string WardenWin::_hypervisors private
Definition at line 56 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_lastClientTime
uint32 WardenWin::_lastClientTime private
Definition at line 60 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_lastHardwareActionTime
uint32 WardenWin::_lastHardwareActionTime private
Definition at line 61 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_lastTimeCheckServer
uint32 WardenWin::_lastTimeCheckServer private
Definition at line 62 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_proxifierFound
bool WardenWin::_proxifierFound private
Definition at line 54 of file WardenWin.hpp.
Referenced by SendPlayerInfo().
_sysInfo
WIN_SYSTEM_INFO WardenWin::_sysInfo private
Definition at line 51 of file WardenWin.hpp.
Referenced by LoadScriptedScans(), SendPlayerInfo(), Update(), and WardenWin().
_sysInfoSaved
bool WardenWin::_sysInfoSaved private
Definition at line 53 of file WardenWin.hpp.
Referenced by SetCharEnumPacket(), and Update().
_wardenAddress
uint32 WardenWin::_wardenAddress private
Definition at line 49 of file WardenWin.hpp.
Referenced by LoadScriptedScans().
The documentation for this class was generated from the following files:
WardenWin.hpp
wardenwin.cpp