CMaNGOS_WoTLK: instance_zulaman Class Reference
instance_zulaman Class Reference
#include <zulaman.h>
Public Member Functions
instance_zulaman (Map *map)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
bool IsBearPhaseInProgress () const
void SetBearEventProgress (bool bIsInProgress)
void SendNextBearWave (Unit *pTarget)
bool IsAkilzonGauntletSpawning () const
bool IsAkilzonGauntletInProgress () const
bool CheckConditionCriteriaMeet (Player const *player, uint32 instanceConditionId, WorldObject const *conditionSource, uint32 conditionSourceType) const override
void Update (const uint32 diff) override
void ChangeWeather (bool rain)
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
void StartSpiritTimer ()
std::vector< uint32 > & GetMalacrassAddsEntryList ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Data Fields
GuidSet sDrumTriggerGuidSet
GuidSet sHutTriggerGuidSet
GuidSet sGongGuardianGuidSet
ObjectGuid m_GongGuardianAttackerGuid
Data Fields inherited from InstanceData
Map * instance
Private Member Functions
uint8 GetKilledPreBosses ()
void DoTimeRunSay (RunEventSteps uiData)
void DoChestEvent (BossToChestIndex uiIndex)
void SpawnMalacrass ()
Private Attributes
std::string m_strInstData
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 m_auiRandVendor [MAX_VENDOR]
TimeEventNpcInfo m_aEventNpcInfo [MAX_CHESTS]
bool m_startCheck
uint32 m_uiEventTimer
NalorakkTrashInfo m_nalorakkEvent [MAX_BEAR_WAVES]
uint8 m_uiBearEventPhase
bool m_isBearPhaseInProgress
GuidSet sAkilzonTrashGuidSet
uint32 m_spiritFadeTimer
std::vector< uint32 > m_malacrassAddsEntryList
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 203 of file zulaman.h.
Constructor & Destructor Documentation
instance_zulaman()
instance_zulaman::instance_zulaman (Map * map)
Definition at line 28 of file zulaman.cpp.
References Initialize().
Member Function Documentation
ChangeWeather()
void instance_zulaman::ChangeWeather (bool rain)
Definition at line 784 of file zulaman.cpp.
References Map::GetPlayers(), Player::GetSession(), InstanceData::instance, WorldSession::SendPacket(), and SMSG_WEATHER.
Referenced by boss_akilzonAI::ExecuteAction(), and boss_akilzonAI::ReceiveAIEvent().
CheckConditionCriteriaMeet()
bool instance_zulaman::CheckConditionCriteriaMeet (Player const * player, uint32 instanceConditionId, WorldObject const * conditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 609 of file zulaman.cpp.
References Object::GetEntry(), Object::GetGuidStr(), GO_ASHLIS_BAG, GO_HARKORS_SATCHEL, GO_KRAZS_PACKAGE, GO_TANZARS_TRUNK, INDEX_AKILZON, INDEX_HALAZZI, INDEX_JANALAI, INDEX_NALORAKK, INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, INSTANCE_CONDITION_ID_HARD_MODE_3, INSTANCE_CONDITION_ID_HARD_MODE_4, INSTANCE_CONDITION_ID_NORMAL_MODE, m_aEventNpcInfo, NPC_ASHLI, NPC_HARKOR, NPC_KRAZ, NPC_TANZAR, script_error_log(), and TimeEventNpcInfo::uiSavePosition.
DoChestEvent()
void instance_zulaman::DoChestEvent (BossToChestIndex uiIndex) private
Definition at line 687 of file zulaman.cpp.
References AI_EVENT_CUSTOM_A, DoTimeRunSay(), GAMEOBJECT_FLAGS, Map::GetCreature(), GetKilledPreBosses(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ASHLIS_BAG, GO_FLAG_NO_INTERACT, GO_HARKORS_SATCHEL, GO_KRAZS_PACKAGE, InstanceData::instance, m_aEventNpcInfo, NPC_ASHLI, NPC_HARKOR, NPC_KRAZ, NPC_TANZAR, TimeEventNpcInfo::npGuid, RUN_PROGRESS, and TimeEventNpcInfo::uiSavePosition.
Referenced by SetData().
DoTimeRunSay()
void instance_zulaman::DoTimeRunSay (RunEventSteps uiData) private
Definition at line 659 of file zulaman.cpp.
References ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), GetKilledPreBosses(), NPC_MALACRASS, RUN_DONE, RUN_FAIL, RUN_FAIL_SOON, RUN_PROGRESS, RUN_START, SAY_INST_BEGIN, SAY_INST_COMPLETE, SAY_INST_PROGRESS_1, SAY_INST_PROGRESS_2, SAY_INST_PROGRESS_3, SAY_INST_SACRIF1, SAY_INST_SACRIF2, SAY_INST_WARN_1, SAY_INST_WARN_2, SAY_INST_WARN_3, SAY_INST_WARN_4, and urand().
Referenced by DoChestEvent(), SetData(), and Update().
ExecuteChatCommand()
void instance_zulaman::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 803 of file zulaman.cpp.
References ScriptedInstance::DoUseDoorOrButton(), ChatHandler::ExtractLiteralArg(), GO_HEXLORD_ENTRANCE, SetData(), SpawnMalacrass(), SPECIAL, and TYPE_EVENT_RUN.
GetData()
uint32 instance_zulaman::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 557 of file zulaman.cpp.
References m_auiEncounter, m_auiRandVendor, TYPE_AKILZON, TYPE_ASHLI, TYPE_EVENT_RUN, TYPE_HALAZZI, TYPE_HARKOR, TYPE_JANALAI, TYPE_KRAZ, TYPE_MALACRASS, TYPE_NALORAKK, TYPE_RAND_VENDOR_1, TYPE_RAND_VENDOR_2, TYPE_RUN_EVENT_TIME, TYPE_TANZAR, and TYPE_ZULJIN.
Referenced by boss_malacrassAI::CorpseRemoved(), Load(), OnPlayerEnter(), npc_harrison_jones_zaAI::SetHoldState(), npc_harkorAI::StartEvent(), npc_tanzarAI::StartEvent(), npc_krazAI::StartEvent(), and npc_ashliAI::StartEvent().
GetKilledPreBosses()
uint8 instance_zulaman::GetKilledPreBosses () private
Definition at line 654 of file zulaman.cpp.
References DONE, m_auiEncounter, TYPE_AKILZON, TYPE_HALAZZI, TYPE_JANALAI, and TYPE_NALORAKK.
Referenced by DoChestEvent(), DoTimeRunSay(), OnObjectCreate(), OnPlayerEnter(), and SetData().
GetMalacrassAddsEntryList()
std::vector<uint32>& instance_zulaman::GetMalacrassAddsEntryList () inline
Definition at line 248 of file zulaman.h.
References m_malacrassAddsEntryList.
Referenced by boss_malacrassAI::DoInitializeAdds(), and boss_malacrassAI::ReceiveAIEvent().
Initialize()
void instance_zulaman::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 38 of file zulaman.cpp.
References Map::GetVariableManager(), InstanceData::instance, m_auiEncounter, m_auiRandVendor, WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), WORLD_STATE_CUSTOM_SPAWN_MALACRASS, WORLD_STATE_ZUL_AMAN_EVENT_RUN_IS_ACTIVE, and WORLD_STATE_ZUL_AMAN_TIME_COUNTER.
Referenced by instance_zulaman().
IsAkilzonGauntletInProgress()
bool instance_zulaman::IsAkilzonGauntletInProgress () const inline
Definition at line 229 of file zulaman.h.
References m_auiEncounter, NOT_STARTED, and TYPE_AKILZON_GAUNTLET.
Referenced by npc_amanishi_tempestAI::Aggro(), npc_amanishi_lookoutAI::MoveInLineOfSight(), npc_eagle_trash_aggro_triggerAI::MoveInLineOfSight(), and npc_amanishi_lookoutAI::ReceiveAIEvent().
IsAkilzonGauntletSpawning()
bool instance_zulaman::IsAkilzonGauntletSpawning () const inline
Definition at line 228 of file zulaman.h.
References IN_PROGRESS, m_auiEncounter, and TYPE_AKILZON_GAUNTLET.
Referenced by npc_amanishi_tempestAI::UpdateAI().
IsBearPhaseInProgress()
bool instance_zulaman::IsBearPhaseInProgress () const inline
Definition at line 224 of file zulaman.h.
References m_isBearPhaseInProgress.
Referenced by boss_nalorakkAI::MoveInLineOfSight().
IsEncounterInProgress()
bool instance_zulaman::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 47 of file zulaman.cpp.
References IN_PROGRESS, m_auiEncounter, and TYPE_RUN_EVENT_TIME.
Load()
void instance_zulaman::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 526 of file zulaman.cpp.
References DONE, FAIL, GetData(), IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SetData(), TYPE_AKILZON, TYPE_AKILZON_GAUNTLET, TYPE_EVENT_RUN, and TYPE_RUN_EVENT_TIME.
OnCreatureCreate()
void instance_zulaman::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 70 of file zulaman.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionZ(), INDEX_AKILZON, INDEX_HALAZZI, INDEX_JANALAI, INDEX_NALORAKK, m_aEventNpcInfo, m_GongGuardianAttackerGuid, m_nalorakkEvent, ScriptedInstance::m_npcEntryGuidStore, NalorakkTrashInfo::nalorakkTrashSet, NPC_AKILZON, NPC_ALYSON, NPC_AMANISHI_GUARDIAN, NPC_ASHLI, NPC_AXETHROWER, NPC_BEAR_SPIRIT, NPC_DARKHEART, NPC_DRAGONHAWK_EGG, NPC_DRAGONHAWK_SPIRIT, NPC_EAGLE_SPIRIT, NPC_FENSTALKER, NPC_GAZAKROTH, NPC_HALAZZI, NPC_HARKOR, NPC_HARRISON, NPC_JANALAI, NPC_KORAGG, NPC_KRAZ, NPC_LOOKOUT, NPC_LYNX_SPIRIT, NPC_MALACRASS, NPC_MEDICINE_MAN, NPC_NALORAKK, NPC_PROTECTOR, NPC_RADAAN, NPC_SLITHER, NPC_TANZAR, NPC_TEMPEST, NPC_THURG, NPC_TRIBES_MAN, NPC_WARBRINGER, NPC_WIND_WALKER, NPC_WORLD_TRIGGER, NPC_ZULJIN, TimeEventNpcInfo::npGuid, sAkilzonTrashGuidSet, sDrumTriggerGuidSet, Creature::SetCorpseDelay(), Object::SetFlag(), Unit::SetImmuneToPlayer(), sGongGuardianGuidSet, sHutTriggerGuidSet, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnCreatureDeath()
void instance_zulaman::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 161 of file zulaman.cpp.
References aBearEventInfo, DoScriptText(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_nalorakkEvent, m_uiBearEventPhase, MAX_BEAR_WAVES, NalorakkTrashInfo::nalorakkTrashSet, NPC_AXETHROWER, NPC_MEDICINE_MAN, NPC_NALORAKK, NPC_TRIBES_MAN, NPC_WARBRINGER, SAY_RUN_BACK, NalorakkTrashInfo::trashKilledCount, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnCreatureEvade()
void instance_zulaman::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 194 of file zulaman.cpp.
References Creature::ForcedDespawn(), Map::GetCreature(), Object::GetEntry(), Object::GetObjectGuid(), InstanceData::instance, Unit::IsAlive(), m_isBearPhaseInProgress, m_nalorakkEvent, m_uiBearEventPhase, NOT_STARTED, NPC_AXETHROWER, NPC_MEDICINE_MAN, NPC_PROTECTOR, NPC_REINFORCEMENT, NPC_TEMPEST, NPC_TRIBES_MAN, NPC_WARBRINGER, NPC_WIND_WALKER, Creature::Respawn(), sAkilzonTrashGuidSet, SetData(), Object::SetFlag(), NalorakkTrashInfo::trashKilledCount, TYPE_AKILZON_GAUNTLET, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnCreatureRespawn()
void instance_zulaman::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 243 of file zulaman.cpp.
References Creature::AI(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_HATCHLING, NPC_JANALAI, NPC_REINFORCEMENT, NPC_WORLD_TRIGGER_NOT_IMMUNE_PC, REACT_PASSIVE, Unit::SetCanEnterCombat(), UnitAI::SetCombatMovement(), Creature::SetInCombatWithZone(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_zulaman::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 262 of file zulaman.cpp.
References DONE, FAIL, GAMEOBJECT_FLAGS, Object::GetEntry(), GetKilledPreBosses(), Object::GetObjectGuid(), GO_ALTAR_TORCH_BEAR_GOD, GO_ALTAR_TORCH_DRAGONHAWK_GOD, GO_ALTAR_TORCH_EAGLE_GOD, GO_ALTAR_TORCH_LYNX_GOD, GO_AMANI_DRUM, GO_ASHLIS_BAG, GO_ASHLIS_CAGE, GO_DWARF_HAMMER, GO_DWARF_LOOT_BOX, GO_FIRE_DOOR, GO_FLAG_LOCKED, GO_HARKORS_BREW_KEG, GO_HARKORS_CAGE, GO_HARKORS_SATCHEL, GO_HEXLORD_ENTRANCE, GO_KRAZS_CAGE, GO_KRAZS_CHEST, GO_KRAZS_PACKAGE, GO_LYNX_TEMPLE_ENTRANCE, GO_LYNX_TEMPLE_EXIT, GO_MASSIVE_GATE, GO_STATE_ACTIVE, GO_STRANGE_GONG, GO_TANZARS_CAGE, GO_TANZARS_TRUNK, GO_WIND_DOOR, GO_WOODEN_DOOR, IN_PROGRESS, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), TYPE_AKILZON, TYPE_EVENT_RUN, TYPE_HALAZZI, TYPE_JANALAI, TYPE_MALACRASS, and TYPE_NALORAKK.
OnPlayerEnter()
void instance_zulaman::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 59 of file zulaman.cpp.
References DONE, GetData(), GetKilledPreBosses(), m_startCheck, SpawnMalacrass(), and TYPE_MALACRASS.
Save()
const char* instance_zulaman::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 221 of file zulaman.h.
References m_strInstData.
SendNextBearWave()
void instance_zulaman::SendNextBearWave (Unit * pTarget)
Definition at line 581 of file zulaman.cpp.
References DIST_CALC_COMBAT_REACH, Map::GetCreature(), WorldObject::GetDistance(), Object::GetGUIDLow(), Unit::GetMotionMaster(), InstanceData::instance, Unit::IsAlive(), m_isBearPhaseInProgress, m_nalorakkEvent, m_uiBearEventPhase, MotionMaster::MoveWaypoint(), Object::RemoveFlag(), Creature::SetWalk(), sWaypointMgr, NalorakkTrashInfo::trashKilledCount, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Referenced by boss_nalorakkAI::MoveInLineOfSight().
SetBearEventProgress()
void instance_zulaman::SetBearEventProgress (bool bIsInProgress) inline
Definition at line 225 of file zulaman.h.
References m_isBearPhaseInProgress.
Referenced by boss_nalorakkAI::MovementInform().
SetData()
void instance_zulaman::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 339 of file zulaman.cpp.
References AI_EVENT_CUSTOM_A, debug_log(), DoChestEvent(), DONE, DoTimeRunSay(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::DoUseOpenableObject(), EMOTE_ONESHOT_NONE, FAIL, GAMEOBJECT_FLAGS, Map::GetCreature(), GetKilledPreBosses(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), Map::GetVariableManager(), GO_ALTAR_TORCH_BEAR_GOD, GO_ALTAR_TORCH_DRAGONHAWK_GOD, GO_ALTAR_TORCH_EAGLE_GOD, GO_ALTAR_TORCH_LYNX_GOD, GO_FIRE_DOOR, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_HEXLORD_ENTRANCE, GO_LYNX_TEMPLE_ENTRANCE, GO_LYNX_TEMPLE_EXIT, GO_MASSIVE_GATE, GO_STRANGE_GONG, GO_WIND_DOOR, GO_WOODEN_DOOR, IN_PROGRESS, INDEX_AKILZON, INDEX_HALAZZI, INDEX_JANALAI, INDEX_NALORAKK, InstanceData::instance, m_aEventNpcInfo, m_auiEncounter, m_auiRandVendor, m_strInstData, NPC_HARRISON, NPC_MALACRASS, TimeEventNpcInfo::npGuid, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, RUN_DONE, RUN_FAIL, RUN_START, InstanceData::SaveToDB(), script_error_log(), WorldStateVariableManager::SetVariable(), SpawnMalacrass(), SPECIAL, TYPE_AKILZON, TYPE_AKILZON_GAUNTLET, TYPE_ASHLI, TYPE_EVENT_RUN, TYPE_HALAZZI, TYPE_HARKOR, TYPE_JANALAI, TYPE_KRAZ, TYPE_MALACRASS, TYPE_NALORAKK, TYPE_RAND_VENDOR_1, TYPE_RAND_VENDOR_2, TYPE_RUN_EVENT_TIME, TYPE_TANZAR, TYPE_ZULJIN, WORLD_STATE_ZUL_AMAN_EVENT_RUN_IS_ACTIVE, and WORLD_STATE_ZUL_AMAN_TIME_COUNTER.
Referenced by boss_akilzonAI::Aggro(), boss_malacrassAI::Aggro(), boss_nalorakkAI::Aggro(), boss_zuljinAI::Aggro(), npc_amanishi_tempestAI::Aggro(), boss_zuljinAI::EnterEvadeMode(), ExecuteChatCommand(), boss_akilzonAI::JustDied(), boss_malacrassAI::JustDied(), boss_nalorakkAI::JustDied(), boss_zuljinAI::JustDied(), boss_akilzonAI::JustReachedHome(), boss_malacrassAI::JustReachedHome(), boss_nalorakkAI::JustReachedHome(), Load(), OnCreatureEvade(), npc_ashliAI::SpellHitTarget(), npc_amanishi_lookoutAI::StartEvent(), Update(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_krazAI::UpdateAI(), and npc_harrison_jones_zaAI::WaypointReached().
ShowChatCommands()
void instance_zulaman::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 798 of file zulaman.cpp.
References ChatHandler::SendSysMessage().
SpawnMalacrass()
void instance_zulaman::SpawnMalacrass () private
Definition at line 734 of file zulaman.cpp.
References Map::GetVariableManager(), InstanceData::instance, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_SPAWN_MALACRASS.
Referenced by ExecuteChatCommand(), OnPlayerEnter(), and SetData().
StartSpiritTimer()
void instance_zulaman::StartSpiritTimer ()
Definition at line 739 of file zulaman.cpp.
References m_spiritFadeTimer.
Referenced by boss_zuljinAI::SpellHitTarget().
Update()
void instance_zulaman::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 744 of file zulaman.cpp.
References debug_log(), DoTimeRunSay(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, m_auiEncounter, m_spiritFadeTimer, m_uiEventTimer, MINUTE, NPC_BEAR_SPIRIT, NPC_DRAGONHAWK_SPIRIT, NPC_EAGLE_SPIRIT, NPC_LYNX_SPIRIT, RUN_FAIL_SOON, SetData(), SPELL_RETURN_TO_SPIRIT_REALM, TRIGGERED_NONE, TYPE_EVENT_RUN, and TYPE_RUN_EVENT_TIME.
Field Documentation
m_aEventNpcInfo
TimeEventNpcInfo instance_zulaman::m_aEventNpcInfo[MAX_CHESTS] private
Definition at line 258 of file zulaman.h.
Referenced by CheckConditionCriteriaMeet(), DoChestEvent(), OnCreatureCreate(), and SetData().
m_auiEncounter
uint32 instance_zulaman::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 256 of file zulaman.h.
Referenced by GetData(), GetKilledPreBosses(), Initialize(), IsAkilzonGauntletInProgress(), IsAkilzonGauntletSpawning(), IsEncounterInProgress(), Load(), OnObjectCreate(), SetData(), and Update().
m_auiRandVendor
uint32 instance_zulaman::m_auiRandVendor[MAX_VENDOR] private
Definition at line 257 of file zulaman.h.
Referenced by GetData(), Initialize(), and SetData().
m_GongGuardianAttackerGuid
ObjectGuid instance_zulaman::m_GongGuardianAttackerGuid
Definition at line 239 of file zulaman.h.
Referenced by OnCreatureCreate(), npc_harrison_jones_zaAI::UpdateEscortAI(), and npc_harrison_jones_zaAI::WaypointReached().
m_isBearPhaseInProgress
bool instance_zulaman::m_isBearPhaseInProgress private
Definition at line 265 of file zulaman.h.
Referenced by IsBearPhaseInProgress(), OnCreatureEvade(), SendNextBearWave(), and SetBearEventProgress().
m_malacrassAddsEntryList
std::vector<uint32> instance_zulaman::m_malacrassAddsEntryList private
Definition at line 271 of file zulaman.h.
Referenced by GetMalacrassAddsEntryList().
m_nalorakkEvent
NalorakkTrashInfo instance_zulaman::m_nalorakkEvent[MAX_BEAR_WAVES] private
Definition at line 263 of file zulaman.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), OnCreatureEvade(), and SendNextBearWave().
m_spiritFadeTimer
uint32 instance_zulaman::m_spiritFadeTimer private
Definition at line 269 of file zulaman.h.
Referenced by StartSpiritTimer(), and Update().
m_startCheck
bool instance_zulaman::m_startCheck private
Definition at line 260 of file zulaman.h.
Referenced by OnPlayerEnter().
m_strInstData
std::string instance_zulaman::m_strInstData private
Definition at line 255 of file zulaman.h.
Referenced by Save(), and SetData().
m_uiBearEventPhase
uint8 instance_zulaman::m_uiBearEventPhase private
Definition at line 264 of file zulaman.h.
Referenced by OnCreatureDeath(), OnCreatureEvade(), and SendNextBearWave().
m_uiEventTimer
uint32 instance_zulaman::m_uiEventTimer private
Definition at line 261 of file zulaman.h.
Referenced by Update().
sAkilzonTrashGuidSet
GuidSet instance_zulaman::sAkilzonTrashGuidSet private
Definition at line 267 of file zulaman.h.
Referenced by OnCreatureCreate(), and OnCreatureEvade().
sDrumTriggerGuidSet
GuidSet instance_zulaman::sDrumTriggerGuidSet
Definition at line 235 of file zulaman.h.
Referenced by npc_amanishi_scoutAI::Aggro(), and OnCreatureCreate().
sGongGuardianGuidSet
GuidSet instance_zulaman::sGongGuardianGuidSet
Definition at line 238 of file zulaman.h.
Referenced by OnCreatureCreate(), npc_harrison_jones_zaAI::UpdateEscortAI(), and npc_harrison_jones_zaAI::WaypointReached().
sHutTriggerGuidSet
GuidSet instance_zulaman::sHutTriggerGuidSet
Definition at line 236 of file zulaman.h.
Referenced by OnCreatureCreate(), and npc_amanishi_scoutAI::ReceiveAIEvent().
The documentation for this class was generated from the following files:
zulaman.h
zulaman.cpp