CMaNGOS_WoTLK: BattleGroundQueue Class Reference
BattleGroundQueue Class Reference
#include <BattleGroundMgr.h>
Data Structures
class SelectionPool
Public Member Functions
BattleGroundQueue ()
~BattleGroundQueue ()
void Update (BattleGroundTypeId, BattleGroundBracketId, ArenaType arenaType=ARENA_TYPE_NONE, bool isRated=false, uint32 arenaRating=0)
Method that is called when group is inserted, or player / group is removed from BG Queue - there is only one player's status changed, so we don't use while(true) cycles to invite whole queue.
void FillPlayersToBg (BattleGround *, BattleGroundBracketId)
Method that invites players to an already running battleground.
bool CheckPremadeMatch (BattleGroundBracketId, uint32, uint32)
Method that checks if (premade vs premade) battlegrouns is possible.
bool CheckNormalMatch (BattleGround *, BattleGroundBracketId, uint32, uint32)
Method that tries to create battleground or arena with minPlayersPerTeam against maxPlayersPerTeam.
bool CheckSkirmishForSameFaction (BattleGroundBracketId, uint32)
Method that will check if we can invite players to same faction skirmish match.
GroupQueueInfo * AddGroup (Player *, Group *, BattleGroundTypeId, PvPDifficultyEntry const *, ArenaType, bool, bool, uint32, uint32, uint32 arenaTeamId=0)
Function that adds group or player (grp == nullptr) to battleground queue with the given leader and specifications.
void RemovePlayer (ObjectGuid, bool)
Method that removes player from queue and from group info, if group info is empty then remove it too.
bool IsPlayerInvited (ObjectGuid, const uint32, const uint32)
Function that returns true when player is in queue and is invited to bgInstanceGuid.
bool GetPlayerGroupInfoData (ObjectGuid, GroupQueueInfo *)
Function that returns player group info data.
void PlayerInvitedToBgUpdateAverageWaitTime (GroupQueueInfo *, BattleGroundBracketId)
Method that updates average update wait time.
uint32 GetAverageQueueWaitTime (GroupQueueInfo *, BattleGroundBracketId)
Function that returns averate queue wait time.
Private Types
typedef std::map< ObjectGuid, PlayerQueueInfo > QueuedPlayersMap
typedef std::list< GroupQueueInfo * > GroupsQueueType
Private Member Functions
bool InviteGroupToBg (GroupQueueInfo *, BattleGround *, Team)
Function that invites group to battleground.
Private Attributes
std::recursive_mutex m_lock
QueuedPlayersMap m_queuedPlayers
GroupsQueueType m_queuedGroups [MAX_BATTLEGROUND_BRACKETS][BG_QUEUE_GROUP_TYPES_COUNT]
SelectionPool m_selectionPools [PVP_TEAM_COUNT]
uint32 m_waitTimes [PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS][COUNT_OF_PLAYERS_TO_AVERAGE_WAIT_TIME]
uint32 m_waitTimeLastPlayer [PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS]
uint32 m_sumOfWaitTimes [PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS]
Detailed Description
Definition at line 78 of file BattleGroundMgr.h.
Member Typedef Documentation
GroupsQueueType
typedef std::list<GroupQueueInfo*> BattleGroundQueue::GroupsQueueType private
Definition at line 105 of file BattleGroundMgr.h.
QueuedPlayersMap
typedef std::map<ObjectGuid, PlayerQueueInfo> BattleGroundQueue::QueuedPlayersMap private
Definition at line 101 of file BattleGroundMgr.h.
Constructor & Destructor Documentation
BattleGroundQueue()
BattleGroundQueue::BattleGroundQueue ()
Definition at line 55 of file BattleGroundMgr.cpp.
References COUNT_OF_PLAYERS_TO_AVERAGE_WAIT_TIME, m_sumOfWaitTimes, m_waitTimeLastPlayer, m_waitTimes, MAX_BATTLEGROUND_BRACKETS, and PVP_TEAM_COUNT.
~BattleGroundQueue()
BattleGroundQueue::~BattleGroundQueue ()
Definition at line 70 of file BattleGroundMgr.cpp.
References BG_QUEUE_GROUP_TYPES_COUNT, m_queuedGroups, and m_queuedPlayers.
Member Function Documentation
AddGroup()
GroupQueueInfo * BattleGroundQueue::AddGroup (Player * leader, Group * group, BattleGroundTypeId bgTypeId, PvPDifficultyEntry const * bracketEntry, ArenaType arenaType, bool isRated, bool isPremade, uint32 instanceId, uint32 arenaRating, uint32 arenaTeamId = 0)
Function that adds group or player (grp == nullptr) to battleground queue with the given leader and specifications.
Parameters
leader player
group
battleground type id
bracket entry
arena type
isRated
isPremade
arena rating
arena team id
Definition at line 178 of file BattleGroundMgr.cpp.
References ARENA_TYPE_NONE, GroupQueueInfo::arenaTeamId, GroupQueueInfo::arenaTeamRating, GroupQueueInfo::arenaType, BG_QUEUE_NORMAL_ALLIANCE, BG_QUEUE_NORMAL_HORDE, GroupQueueInfo::bgTypeId, CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_JOIN, CONFIG_UINT32_BATTLEGROUND_QUEUE_ANNOUNCER_JOIN, DEBUG_LOG, GroupQueueInfo::desiredInstanceId, PvPDifficultyEntry::GetBracketId(), Group::GetFirstMember(), WorldTimer::getMSTime(), Object::GetObjectGuid(), Player::GetTeam(), PlayerQueueInfo::groupInfo, GroupQueueInfo::groupTeam, HORDE, GroupQueueInfo::isInvitedToBgInstanceGuid, GroupQueueInfo::isRated, GroupQueueInfo::joinTime, LANG_ARENA_QUEUE_ANNOUNCE_WORLD_JOIN, LANG_BG_QUEUE_ANNOUNCE_SELF, LANG_BG_QUEUE_ANNOUNCE_WORLD, PlayerQueueInfo::lastOnlineTime, m_queuedGroups, m_queuedPlayers, PvPDifficultyEntry::maxLevel, PvPDifficultyEntry::minLevel, GroupReference::next(), GroupQueueInfo::opponentsTeamRating, GroupQueueInfo::players, ChatHandler::PSendSysMessage(), PVP_TEAM_COUNT, GroupQueueInfo::removeInviteTime, sBattleGroundMgr, and sWorld.
Referenced by CheckNormalMatch(), WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
CheckNormalMatch()
bool BattleGroundQueue::CheckNormalMatch (BattleGround * bgTemplate, BattleGroundBracketId bracketId, uint32 minPlayers, uint32 maxPlayers)
Method that tries to create battleground or arena with minPlayersPerTeam against maxPlayersPerTeam.
Parameters
battleground
bracket id
min players
max players
Definition at line 743 of file BattleGroundMgr.cpp.
References BattleGroundQueue::SelectionPool::AddGroup(), AddGroup(), BG_QUEUE_NORMAL_ALLIANCE, CONFIG_UINT32_BATTLEGROUND_INVITATION_TYPE, BattleGroundQueue::SelectionPool::GetPlayerCount(), BattleGround::IsBattleGround(), m_queuedGroups, m_selectionPools, PVP_TEAM_COUNT, sBattleGroundMgr, sWorld, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by Update().
CheckPremadeMatch()
bool BattleGroundQueue::CheckPremadeMatch (BattleGroundBracketId bracketId, uint32 minPlayersPerTeam, uint32 maxPlayersPerTeam)
Method that checks if (premade vs premade) battlegrouns is possible.
then after 30 mins (default) in queue it moves premade group to normal queue
it tries to invite as much players as it can - to maxPlayersPerTeam, because premade groups have more than minPlayersPerTeam players
Parameters
bracket id
min players per team
max players per team
Definition at line 675 of file BattleGroundMgr.cpp.
References BattleGroundQueue::SelectionPool::AddGroup(), BG_QUEUE_NORMAL_ALLIANCE, BG_QUEUE_PREMADE_ALLIANCE, BG_QUEUE_PREMADE_HORDE, CONFIG_UINT32_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH, WorldTimer::getMSTime(), m_queuedGroups, m_selectionPools, PVP_TEAM_COUNT, sWorld, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by Update().
CheckSkirmishForSameFaction()
bool BattleGroundQueue::CheckSkirmishForSameFaction (BattleGroundBracketId bracketId, uint32 minPlayersPerTeam)
Method that will check if we can invite players to same faction skirmish match.
Parameters
bracket id
min players
Definition at line 795 of file BattleGroundMgr.cpp.
References BattleGroundQueue::SelectionPool::AddGroup(), ALLIANCE, BG_QUEUE_NORMAL_ALLIANCE, HORDE, BattleGroundQueue::SelectionPool::Init(), m_queuedGroups, m_selectionPools, BattleGroundQueue::SelectionPool::selectedGroups, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by Update().
FillPlayersToBg()
void BattleGroundQueue::FillPlayersToBg (BattleGround * bg, BattleGroundBracketId bracketId)
Method that invites players to an already running battleground.
invitation is based on config file
large groups are disadvantageous, because they will be kicked first if invitation type = 1
Parameters
battleground
bracket id
Definition at line 589 of file BattleGroundMgr.cpp.
References BattleGroundQueue::SelectionPool::AddGroup(), ALLIANCE, BG_QUEUE_NORMAL_ALLIANCE, BG_QUEUE_NORMAL_HORDE, CONFIG_UINT32_BATTLEGROUND_INVITATION_TYPE, BattleGround::GetClientInstanceId(), BattleGround::GetFreeSlotsForTeam(), HORDE, BattleGroundQueue::SelectionPool::KickGroup(), m_queuedGroups, m_selectionPools, sWorld, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by Update().
GetAverageQueueWaitTime()
uint32 BattleGroundQueue::GetAverageQueueWaitTime (GroupQueueInfo * queueInfo, BattleGroundBracketId bracketId)
Function that returns averate queue wait time.
Parameters
group queue info
bracket id
Definition at line 324 of file BattleGroundMgr.cpp.
References ARENA_TYPE_NONE, GroupQueueInfo::arenaType, COUNT_OF_PLAYERS_TO_AVERAGE_WAIT_TIME, GroupQueueInfo::groupTeam, HORDE, GroupQueueInfo::isRated, m_sumOfWaitTimes, m_waitTimes, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
GetPlayerGroupInfoData()
bool BattleGroundQueue::GetPlayerGroupInfoData (ObjectGuid guid, GroupQueueInfo * queueInfo)
Function that returns player group info data.
returns true when the player is found in queue
Parameters
player guid
group queue info
Definition at line 499 of file BattleGroundMgr.cpp.
References m_queuedPlayers.
Referenced by WorldSession::HandleBattlefieldPortOpcode(), and WorldSession::HandleBattlefieldStatusOpcode().
InviteGroupToBg()
bool BattleGroundQueue::InviteGroupToBg (GroupQueueInfo * queueInfo, BattleGround * bg, Team team) private
Function that invites group to battleground.
Parameters
group queue info
battleground
team
Definition at line 517 of file BattleGroundMgr.cpp.
References EventProcessor::AddEvent(), ALLIANCE, GroupQueueInfo::arenaTeamId, GroupQueueInfo::arenaType, BattleGroundMgr::BgQueueTypeId(), EventProcessor::CalculateTime(), DEBUG_LOG, BattleGround::GetArenaType(), Player::GetBattleGroundQueueIndex(), BattleGround::GetBracketId(), Object::GetGuidStr(), BattleGround::GetInstanceId(), WorldTimer::getMSTime(), Object::GetObjectGuid(), Player::GetSession(), BattleGround::GetTypeId(), GroupQueueInfo::groupTeam, HORDE, BattleGround::IncreaseInvitedCount(), INVITATION_REMIND_TIME, INVITE_ACCEPT_WAIT_TIME, BattleGround::IsArena(), GroupQueueInfo::isInvitedToBgInstanceGuid, BattleGround::IsRated(), WorldObject::m_events, PlayerInvitedToBgUpdateAverageWaitTime(), GroupQueueInfo::players, GroupQueueInfo::removeInviteTime, sBattleGroundMgr, WorldSession::SendPacket(), BattleGround::SetArenaTeamIdForTeam(), Player::SetInviteForBattleGroundQueueType(), sObjectMgr, STATUS_WAIT_JOIN, and TEAM_NONE.
Referenced by Update().
IsPlayerInvited()
bool BattleGroundQueue::IsPlayerInvited (ObjectGuid playerGuid, const uint32 bgInstanceGuid, const uint32 removeTime)
Function that returns true when player is in queue and is invited to bgInstanceGuid.
Parameters
player guid
battleground instance guid
remove time
Definition at line 483 of file BattleGroundMgr.cpp.
References m_queuedPlayers.
Referenced by BgQueueInviteEvent::Execute(), and BgQueueRemoveEvent::Execute().
PlayerInvitedToBgUpdateAverageWaitTime()
void BattleGroundQueue::PlayerInvitedToBgUpdateAverageWaitTime (GroupQueueInfo * queueInfo, BattleGroundBracketId bracketId)
Method that updates average update wait time.
Parameters
group queue info
bracket id
Definition at line 285 of file BattleGroundMgr.cpp.
References ARENA_TYPE_NONE, GroupQueueInfo::arenaType, COUNT_OF_PLAYERS_TO_AVERAGE_WAIT_TIME, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), GroupQueueInfo::groupTeam, HORDE, GroupQueueInfo::isRated, GroupQueueInfo::joinTime, m_sumOfWaitTimes, m_waitTimeLastPlayer, m_waitTimes, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by InviteGroupToBg().
RemovePlayer()
void BattleGroundQueue::RemovePlayer (ObjectGuid guid, bool decreaseInvitedCount)
Method that removes player from queue and from group info, if group info is empty then remove it too.
Parameters
guid
decrease invite count
Definition at line 352 of file BattleGroundMgr.cpp.
References ARENA_TYPE_NONE, GroupQueueInfo::arenaTeamId, GroupQueueInfo::arenaTeamRating, GroupQueueInfo::arenaType, BG_QUEUE_GROUP_TYPES_COUNT, BG_QUEUE_NORMAL_ALLIANCE, BattleGroundMgr::BgQueueTypeId(), GroupQueueInfo::bgTypeId, CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_EXIT, DEBUG_LOG, BattleGround::DecreaseInvitedCount(), ObjectGuid::GetString(), GetTeamIndexByTeamId(), GroupQueueInfo::groupTeam, GroupQueueInfo::isInvitedToBgInstanceGuid, GroupQueueInfo::isRated, LANG_ARENA_QUEUE_ANNOUNCE_WORLD_EXIT, m_queuedGroups, m_queuedPlayers, MAX_BATTLEGROUND_BRACKETS, ArenaTeam::MemberLost(), ArenaTeam::OfflineMemberLost(), GroupQueueInfo::opponentsTeamRating, GroupQueueInfo::players, ArenaTeam::SaveToDB(), sBattleGroundMgr, sLog, sObjectMgr, STATUS_NONE, sWorld, and TEAM_NONE.
Referenced by WorldSession::HandleBattlefieldPortOpcode().
Update()
void BattleGroundQueue::Update (BattleGroundTypeId bgTypeId, BattleGroundBracketId bracketId, ArenaType arenaType = ARENA_TYPE_NONE, bool isRated = false, uint32 arenaRating = 0)
Method that is called when group is inserted, or player / group is removed from BG Queue - there is only one player's status changed, so we don't use while(true) cycles to invite whole queue.
it must be called after fully adding the members of a group to ensure group joining
should be called from BattleGround::RemovePlayer function in some cases
Parameters
bg type id
bracket id
arena type
isRated
arenaRating
Definition at line 872 of file BattleGroundMgr.cpp.
References BattleGroundQueue::SelectionPool::AddGroup(), ALLIANCE, ARENA_TYPE_NONE, GroupQueueInfo::arenaTeamRating, BG_QUEUE_NORMAL_ALLIANCE, BG_QUEUE_NORMAL_HORDE, BG_QUEUE_PREMADE_ALLIANCE, BG_QUEUE_PREMADE_HORDE, CheckNormalMatch(), CheckPremadeMatch(), CheckSkirmishForSameFaction(), DEBUG_LOG, FillPlayersToBg(), GetBattlegroundBracketById(), BattleGround::GetMapId(), BattleGround::GetMaxPlayersPerTeam(), BattleGround::GetMinPlayersPerTeam(), WorldTimer::getMSTime(), BattleGroundQueue::SelectionPool::GetPlayerCount(), BattleGround::HasFreeSlots(), HORDE, BattleGroundQueue::SelectionPool::Init(), InviteGroupToBg(), BattleGround::IsArena(), BattleGround::IsBattleGround(), GroupQueueInfo::joinTime, m_queuedGroups, m_selectionPools, PVP_TEAM_COUNT, BattleGround::RemoveFromBgFreeSlotQueue(), sBattleGroundMgr, BattleGroundQueue::SelectionPool::selectedGroups, sLog, BattleGround::StartBattleGround(), STATUS_WAIT_LEAVE, STATUS_WAIT_QUEUE, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by BattleGroundMgr::Update().
Field Documentation
m_lock
std::recursive_mutex BattleGroundQueue::m_lock private
Definition at line 99 of file BattleGroundMgr.h.
m_queuedGroups
GroupsQueueType BattleGroundQueue::m_queuedGroups[MAX_BATTLEGROUND_BRACKETS][BG_QUEUE_GROUP_TYPES_COUNT] private
Definition at line 116 of file BattleGroundMgr.h.
Referenced by AddGroup(), CheckNormalMatch(), CheckPremadeMatch(), CheckSkirmishForSameFaction(), FillPlayersToBg(), RemovePlayer(), Update(), and ~BattleGroundQueue().
m_queuedPlayers
QueuedPlayersMap BattleGroundQueue::m_queuedPlayers private
Definition at line 102 of file BattleGroundMgr.h.
Referenced by AddGroup(), GetPlayerGroupInfoData(), IsPlayerInvited(), RemovePlayer(), and ~BattleGroundQueue().
m_selectionPools
SelectionPool BattleGroundQueue::m_selectionPools[PVP_TEAM_COUNT] private
Definition at line 133 of file BattleGroundMgr.h.
Referenced by CheckNormalMatch(), CheckPremadeMatch(), CheckSkirmishForSameFaction(), FillPlayersToBg(), and Update().
m_sumOfWaitTimes
uint32 BattleGroundQueue::m_sumOfWaitTimes[PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS] private
Definition at line 139 of file BattleGroundMgr.h.
Referenced by BattleGroundQueue(), GetAverageQueueWaitTime(), and PlayerInvitedToBgUpdateAverageWaitTime().
m_waitTimeLastPlayer
uint32 BattleGroundQueue::m_waitTimeLastPlayer[PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS] private
Definition at line 138 of file BattleGroundMgr.h.
Referenced by BattleGroundQueue(), and PlayerInvitedToBgUpdateAverageWaitTime().
m_waitTimes
uint32 BattleGroundQueue::m_waitTimes[PVP_TEAM_COUNT][MAX_BATTLEGROUND_BRACKETS][COUNT_OF_PLAYERS_TO_AVERAGE_WAIT_TIME] private
Definition at line 137 of file BattleGroundMgr.h.
Referenced by BattleGroundQueue(), GetAverageQueueWaitTime(), and PlayerInvitedToBgUpdateAverageWaitTime().
The documentation for this class was generated from the following files:
BattleGroundMgr.h
BattleGroundMgr.cpp