CMaNGOS_WoTLK: QueryNamedResult Class Reference
QueryNamedResult Class Reference
#include <QueryResult.h>
Public Member Functions
QueryNamedResult (QueryResult *query, QueryFieldNames const &names)
~QueryNamedResult ()
bool NextRow () const
Field * Fetch () const
uint32 GetFieldCount () const
uint64 GetRowCount () const
Field const & operator[] (int index) const
Field const & operator[] (const std::string &name) const
QueryFieldNames const & GetFieldNames () const
uint32 GetField_idx (const std::string &name) const
Protected Attributes
QueryResult * mQuery
QueryFieldNames mFieldNames
Detailed Description
Definition at line 51 of file QueryResult.h.
Constructor & Destructor Documentation
QueryNamedResult()
QueryNamedResult::QueryNamedResult (QueryResult * query, QueryFieldNames const & names) inline explicit
Definition at line 54 of file QueryResult.h.
~QueryNamedResult()
QueryNamedResult::~QueryNamedResult () inline
Definition at line 55 of file QueryResult.h.
References mQuery.
Member Function Documentation
Fetch()
Field* QueryNamedResult::Fetch () const inline
Definition at line 59 of file QueryResult.h.
References QueryResult::Fetch(), and mQuery.
GetField_idx()
uint32 QueryNamedResult::GetField_idx (const std::string & name) const inline
Definition at line 68 of file QueryResult.h.
References MANGOS_ASSERT, and mFieldNames.
Referenced by operator[]().
GetFieldCount()
uint32 QueryNamedResult::GetFieldCount () const inline
Definition at line 60 of file QueryResult.h.
References QueryResult::GetFieldCount(), and mQuery.
GetFieldNames()
QueryFieldNames const& QueryNamedResult::GetFieldNames () const inline
Definition at line 66 of file QueryResult.h.
References mFieldNames.
Referenced by Database::CheckRequiredField(), and PlayerDumpWriter::GetDump().
GetRowCount()
uint64 QueryNamedResult::GetRowCount () const inline
Definition at line 61 of file QueryResult.h.
References QueryResult::GetRowCount(), and mQuery.
NextRow()
bool QueryNamedResult::NextRow () const inline
Definition at line 58 of file QueryResult.h.
References mQuery, and QueryResult::NextRow().
operator[]() [1/2]
Field const& QueryNamedResult::operator[] (const std::string & name) const inline
Definition at line 65 of file QueryResult.h.
References QueryResult::Fetch(), GetField_idx(), and mQuery.
operator[]() [2/2]
Field const& QueryNamedResult::operator[] (int index) const inline
Definition at line 62 of file QueryResult.h.
References mQuery.
Field Documentation
mFieldNames
QueryFieldNames QueryNamedResult::mFieldNames protected
Definition at line 81 of file QueryResult.h.
Referenced by GetField_idx(), and GetFieldNames().
mQuery
QueryResult* QueryNamedResult::mQuery protected
Definition at line 80 of file QueryResult.h.
Referenced by Fetch(), GetFieldCount(), GetRowCount(), NextRow(), operator[](), and ~QueryNamedResult().
The documentation for this class was generated from the following file:
QueryResult.h