CMaNGOS_WoTLK: instance_uldaman Class Reference
instance_uldaman Class Reference
#include <uldaman.h>
Public Member Functions
instance_uldaman (Map *pMap)
~instance_uldaman ()
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureGroupDespawn (CreatureGroup *pGroup, Creature *pCreature) override
void Update (const uint32 diff) override
void SetData (uint32 uiType, uint32 uiData) override
void SetData64 (uint32 uiData, uint64 uiGuid) override
uint32 GetData (uint32 uiType) const override
uint64 GetData64 (uint32 uiData) const override
void StartEvent (uint32 uiEventId, Player *pPlayer)
Creature * GetClosestDwarfNotInCombat (Creature *pSearcher)
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnEventHappened (uint16, bool, bool)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoResetKeeperEvent ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
ObjectGuid m_playerGuid
uint32 m_uiKeeperCooldown
uint32 m_uiStoneKeepersFallen
GuidList m_lWardens
GuidList m_lKeepers
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 37 of file uldaman.h.
Constructor & Destructor Documentation
instance_uldaman()
instance_uldaman::instance_uldaman (Map * pMap)
Definition at line 28 of file instance_uldaman.cpp.
References Initialize().
~instance_uldaman()
instance_uldaman::~instance_uldaman () inline
Definition at line 41 of file uldaman.h.
Member Function Documentation
DoResetKeeperEvent()
void instance_uldaman::DoResetKeeperEvent () protected
Definition at line 207 of file instance_uldaman.cpp.
References Map::GetCreature(), InstanceData::instance, m_lKeepers, NPC_STONE_KEEPER, and script_error_log().
Referenced by SetData().
GetClosestDwarfNotInCombat()
Creature * instance_uldaman::GetClosestDwarfNotInCombat (Creature * pSearcher)
Definition at line 226 of file instance_uldaman.cpp.
References Map::GetCreature(), Unit::GetVictim(), InstanceData::instance, Unit::IsAlive(), and m_lWardens.
Referenced by boss_archaedasAI::UpdateAI().
GetData()
uint32 instance_uldaman::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 169 of file instance_uldaman.cpp.
References m_auiEncounter, TYPE_ALTAR_EVENT, and TYPE_ARCHAEDAS.
Referenced by OnObjectCreate(), StartEvent(), Update(), and boss_archaedasAI::UpdateAI().
GetData64()
uint64 instance_uldaman::GetData64 (uint32 uiData) const override virtual
Reimplemented from InstanceData.
Definition at line 181 of file instance_uldaman.cpp.
References DATA_EVENT_STARTER, ObjectGuid::GetRawValue(), and m_playerGuid.
Initialize()
void instance_uldaman::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 35 of file instance_uldaman.cpp.
References Map::GetVariableManager(), InstanceData::instance, m_auiEncounter, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_SPAWN_ANNORA.
Referenced by instance_uldaman().
Load()
void instance_uldaman::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 136 of file instance_uldaman.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_uldaman::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 62 of file instance_uldaman.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_lKeepers, m_lWardens, ScriptedInstance::m_npcEntryGuidStore, NPC_ARCHAEDAS, NPC_CUSTODIAN, NPC_HALLSHAPER, and NPC_STONE_KEEPER.
OnCreatureDeath()
void instance_uldaman::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 252 of file instance_uldaman.cpp.
References DONE, Object::GetEntry(), m_lKeepers, m_uiKeeperCooldown, m_uiStoneKeepersFallen, NPC_STONE_KEEPER, SetData(), and TYPE_ALTAR_EVENT.
OnCreatureEvade()
void instance_uldaman::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 245 of file instance_uldaman.cpp.
References Object::GetEntry(), NOT_STARTED, NPC_STONE_KEEPER, SetData(), and TYPE_ALTAR_EVENT.
OnCreatureGroupDespawn()
void instance_uldaman::OnCreatureGroupDespawn (CreatureGroup * pGroup, Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 82 of file instance_uldaman.cpp.
References SpawnGroup::GetGroupId(), Map::GetVariableManager(), InstanceData::instance, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_SPAWN_ANNORA.
OnObjectCreate()
void instance_uldaman::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 41 of file instance_uldaman.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), GO_ANCIENT_TREASURE, GO_ANCIENT_VAULT, GO_STATE_ACTIVE, GO_TEMPLE_DOOR_LOWER, GO_TEMPLE_DOOR_UPPER, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), TYPE_ALTAR_EVENT, and TYPE_ARCHAEDAS.
Save()
const char* instance_uldaman::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 64 of file uldaman.h.
References m_strInstData.
SetData()
void instance_uldaman::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 88 of file instance_uldaman.cpp.
References DONE, DoResetKeeperEvent(), ScriptedInstance::DoRespawnGameObject(), ScriptedInstance::DoUseDoorOrButton(), GO_ANCIENT_TREASURE, GO_ANCIENT_VAULT, GO_TEMPLE_DOOR_LOWER, GO_TEMPLE_DOOR_UPPER, HOUR, IN_PROGRESS, m_auiEncounter, m_strInstData, m_uiKeeperCooldown, m_uiStoneKeepersFallen, NOT_STARTED, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_ALTAR_EVENT, and TYPE_ARCHAEDAS.
Referenced by boss_archaedasAI::Aggro(), boss_archaedasAI::JustDied(), boss_archaedasAI::JustReachedHome(), OnCreatureDeath(), OnCreatureEvade(), StartEvent(), and Update().
SetData64()
void instance_uldaman::SetData64 (uint32 uiData, uint64 uiGuid) override virtual
Reimplemented from InstanceData.
Definition at line 158 of file instance_uldaman.cpp.
References DATA_EVENT_STARTER, and m_playerGuid.
StartEvent()
void instance_uldaman::StartEvent (uint32 uiEventId, Player * pPlayer)
Definition at line 191 of file instance_uldaman.cpp.
References EVENT_ID_ALTAR_ARCHAEDAS, EVENT_ID_ALTAR_KEEPER, FAIL, GetData(), Object::GetObjectGuid(), IN_PROGRESS, m_playerGuid, NOT_STARTED, SetData(), SPECIAL, TYPE_ALTAR_EVENT, and TYPE_ARCHAEDAS.
Update()
void instance_uldaman::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 265 of file instance_uldaman.cpp.
References Creature::AI(), UnitAI::AttackStart(), Map::GetCreature(), GetData(), WorldObject::GetMap(), Map::GetPlayer(), ScriptedInstance::GetPlayerInMap(), Unit::GetVictim(), IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), WorldObject::IsWithinDistInMap(), m_lKeepers, m_playerGuid, m_uiKeeperCooldown, NOT_STARTED, Unit::RemoveAurasDueToSpell(), SetData(), SPELL_STONED, and TYPE_ALTAR_EVENT.
Field Documentation
m_auiEncounter
uint32 instance_uldaman::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 70 of file uldaman.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_lKeepers
GuidList instance_uldaman::m_lKeepers protected
Definition at line 79 of file uldaman.h.
Referenced by DoResetKeeperEvent(), OnCreatureCreate(), OnCreatureDeath(), and Update().
m_lWardens
GuidList instance_uldaman::m_lWardens protected
Definition at line 78 of file uldaman.h.
Referenced by GetClosestDwarfNotInCombat(), and OnCreatureCreate().
m_playerGuid
ObjectGuid instance_uldaman::m_playerGuid protected
Definition at line 73 of file uldaman.h.
Referenced by GetData64(), SetData64(), StartEvent(), and Update().
m_strInstData
std::string instance_uldaman::m_strInstData protected
Definition at line 71 of file uldaman.h.
Referenced by Save(), and SetData().
m_uiKeeperCooldown
uint32 instance_uldaman::m_uiKeeperCooldown protected
Definition at line 75 of file uldaman.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_uiStoneKeepersFallen
uint32 instance_uldaman::m_uiStoneKeepersFallen protected
Definition at line 76 of file uldaman.h.
Referenced by OnCreatureDeath(), and SetData().
The documentation for this class was generated from the following files:
uldaman.h
instance_uldaman.cpp