CMaNGOS_WoTLK: SpawnGroup Class Reference
SpawnGroup Class Reference abstract
#include <SpawnGroup.h>
Public Member Functions
SpawnGroup (SpawnGroupEntry const &entry, Map &map, uint32 typeId)
virtual ~SpawnGroup ()
virtual void AddObject (uint32 dbGuid, uint32 entry)
virtual void RemoveObject (WorldObject *wo)
uint32 GetGuidEntry (uint32 dbGuid) const
virtual void Update ()
uint32 GetEligibleEntry (std::map< uint32, uint32 > &existingEntries, std::map< uint32, uint32 > &minEntries)
virtual void Spawn (bool force)
virtual void Despawn (uint32 timeMSToDespawn=0, uint32 forcedDespawnTime=0)=0
std::string to_string () const
uint32 GetObjectTypeId () const
void SetEnabled (bool enabled)
SpawnGroupEntry const & GetGroupEntry () const
uint32 GetGroupId () const
virtual CreatureGroup * GetCreatureGroup ()
bool IsWorldstateConditionSatisfied () const
void RespawnIfInVicinity (Position pos, float range)
Protected Attributes
SpawnGroupEntry const & m_entry
Map & m_map
std::map< uint32, uint32 > m_objects
std::map< uint32, uint32 > m_chosenEntries
std::map< uint32, bool > m_chosenSpawns
uint32 m_objectTypeId
bool m_enabled
Detailed Description
Definition at line 39 of file SpawnGroup.h.
Constructor & Destructor Documentation
SpawnGroup()
SpawnGroup::SpawnGroup (SpawnGroupEntry const & entry, Map & map, uint32 typeId)
Definition at line 65 of file SpawnGroup.cpp.
~SpawnGroup()
virtual SpawnGroup::~SpawnGroup () inline virtual
Definition at line 43 of file SpawnGroup.h.
Member Function Documentation
AddObject()
void SpawnGroup::AddObject (uint32 dbGuid, uint32 entry) virtual
Definition at line 69 of file SpawnGroup.cpp.
References m_objects.
Referenced by Creature::SetCreatureGroup(), GameObject::SetGameObjectGroup(), and Spawn().
Despawn()
virtual void SpawnGroup::Despawn (uint32 timeMSToDespawn = 0, uint32 forcedDespawnTime = 0) pure virtual
Implemented in GameObjectGroup, and CreatureGroup.
Referenced by Spawn().
GetCreatureGroup()
virtual CreatureGroup* SpawnGroup::GetCreatureGroup () inline virtual
Reimplemented in CreatureGroup.
Definition at line 57 of file SpawnGroup.h.
GetEligibleEntry()
uint32 SpawnGroup::GetEligibleEntry (std::map< uint32, uint32 > & existingEntries, std::map< uint32, uint32 > & minEntries)
Definition at line 106 of file SpawnGroup.cpp.
References SpawnGroupEntry::EquallyChanced, SpawnGroupEntry::ExplicitlyChanced, GetRandomGenerator(), m_entry, SpawnGroupEntry::RandomEntries, and urand().
Referenced by Spawn().
GetGroupEntry()
SpawnGroupEntry const& SpawnGroup::GetGroupEntry () const inline
Definition at line 54 of file SpawnGroup.h.
References m_entry.
Referenced by FormationData::FormationData(), FormationData::GetDefaultSlotId(), FormationData::SetFormationSlot(), and FormationData::~FormationData().
GetGroupId()
uint32 SpawnGroup::GetGroupId () const inline
Definition at line 55 of file SpawnGroup.h.
References SpawnGroupEntry::Id, and m_entry.
Referenced by FormationData::Add(), ScriptAction::ExecuteDbscriptCommand(), FormationData::FreeSlot(), instance_uldaman::OnCreatureGroupDespawn(), FormationData::Remove(), and FormationData::TrySetNewMaster().
GetGuidEntry()
uint32 SpawnGroup::GetGuidEntry (uint32 dbGuid) const
Definition at line 93 of file SpawnGroup.cpp.
References m_objects.
Referenced by Creature::LoadFromDB(), and GameObject::LoadFromDB().
GetObjectTypeId()
uint32 SpawnGroup::GetObjectTypeId () const inline
Definition at line 52 of file SpawnGroup.h.
References m_objectTypeId.
Referenced by CreatureGroup::ClearRespawnTimes(), CreatureGroup::Despawn(), GameObjectGroup::Despawn(), RemoveObject(), RespawnIfInVicinity(), and Spawn().
IsWorldstateConditionSatisfied()
bool SpawnGroup::IsWorldstateConditionSatisfied () const
Definition at line 327 of file SpawnGroup.cpp.
References CONDITION_FROM_WORLDSTATE, IsConditionSatisfied(), m_entry, m_map, sObjectMgr, SpawnGroupEntry::WorldStateCondition, and SpawnGroupEntry::WorldStateExpression.
Referenced by RespawnIfInVicinity(), and Spawn().
RemoveObject()
void SpawnGroup::RemoveObject (WorldObject * wo) virtual
Reimplemented in GameObjectGroup, and CreatureGroup.
Definition at line 74 of file SpawnGroup.cpp.
References SpawnGroupEntry::DbGuids, Object::GetDbGuid(), MapPersistentState::GetObjectRespawnTime(), GetObjectTypeId(), Map::GetPersistentState(), SpawnGroupEntry::HasChancedSpawns, Map::IsDungeon(), m_chosenSpawns, m_entry, m_map, m_objects, and MapPersistentState::SaveObjectRespawnTime().
Referenced by CreatureGroup::RemoveObject(), and GameObjectGroup::RemoveObject().
RespawnIfInVicinity()
void SpawnGroup::RespawnIfInVicinity (Position pos, float range)
Definition at line 341 of file SpawnGroup.cpp.
References SpawnGroupEntry::DbGuids, Position::GetDistance(), GetObjectTypeId(), Map::GetPersistentState(), IsWorldstateConditionSatisfied(), m_entry, m_map, MapPersistentState::SaveObjectRespawnTime(), sObjectMgr, TYPEID_UNIT, and Position::z.
SetEnabled()
void SpawnGroup::SetEnabled (bool enabled) inline
Definition at line 53 of file SpawnGroup.h.
References m_enabled.
Spawn()
void SpawnGroup::Spawn (bool force) virtual
Definition at line 150 of file SpawnGroup.cpp.
References SpawnGroupEntry::Active, MapPersistentState::AddCreatureToGrid(), MapPersistentState::AddGameobjectToGrid(), AddObject(), SpawnGroupEntry::DbGuids, Despawn(), SpawnGroupEntry::Flags, Map::GetDifficulty(), GetEligibleEntry(), MapPersistentState::GetObjectRespawnTime(), GetObjectTypeId(), Map::GetPersistentState(), GetRandomGenerator(), SpawnGroupEntry::HasChancedSpawns, Map::IsDungeon(), Map::IsLoaded(), IsWorldstateConditionSatisfied(), m_chosenEntries, m_chosenSpawns, m_enabled, m_entry, m_map, m_objects, SpawnGroupEntry::MaxCount, SpawnGroupEntry::RandomEntries, roll_chance_i(), MapPersistentState::SaveObjectRespawnTime(), sObjectMgr, SPAWN_GROUP_DESPAWN_ON_COND_FAIL, WorldObject::SpawnCreature(), WorldObject::SpawnGameObject(), and TYPEID_UNIT.
Referenced by instance_ramparts::DoFailVazruden(), and Update().
to_string()
std::string SpawnGroup::to_string () const
Definition at line 376 of file SpawnGroup.cpp.
References Map::GetCreature(), Object::GetGuidStr(), m_map, and m_objects.
Update()
void SpawnGroup::Update () virtual
Reimplemented in CreatureGroup.
Definition at line 101 of file SpawnGroup.cpp.
References Spawn().
Referenced by CreatureGroup::Update().
Field Documentation
m_chosenEntries
std::map<uint32, uint32> SpawnGroup::m_chosenEntries protected
Definition at line 67 of file SpawnGroup.h.
Referenced by Spawn().
m_chosenSpawns
std::map<uint32, bool> SpawnGroup::m_chosenSpawns protected
Definition at line 68 of file SpawnGroup.h.
Referenced by RemoveObject(), and Spawn().
m_enabled
bool SpawnGroup::m_enabled protected
Definition at line 70 of file SpawnGroup.h.
Referenced by SetEnabled(), and Spawn().
m_entry
SpawnGroupEntry const& SpawnGroup::m_entry protected
Definition at line 64 of file SpawnGroup.h.
Referenced by CreatureGroup::ClearRespawnTimes(), GetEligibleEntry(), CreatureGroup::GetFormationEntry(), GetGroupEntry(), GetGroupId(), IsWorldstateConditionSatisfied(), RemoveObject(), RespawnIfInVicinity(), Spawn(), and CreatureGroup::TriggerLinkingEvent().
m_map
Map& SpawnGroup::m_map protected
Definition at line 65 of file SpawnGroup.h.
Referenced by CreatureGroup::ClearRespawnTimes(), CreatureGroup::Despawn(), GameObjectGroup::Despawn(), CreatureGroup::GetMap(), CreatureGroup::IsEvading(), CreatureGroup::IsOutOfCombat(), IsWorldstateConditionSatisfied(), CreatureGroup::MoveHome(), RemoveObject(), CreatureGroup::RemoveObject(), GameObjectGroup::RemoveObject(), RespawnIfInVicinity(), Spawn(), to_string(), and CreatureGroup::TriggerLinkingEvent().
m_objects
std::map<uint32, uint32> SpawnGroup::m_objects protected
Definition at line 66 of file SpawnGroup.h.
Referenced by AddObject(), CreatureGroup::Despawn(), GameObjectGroup::Despawn(), GetGuidEntry(), CreatureGroup::IsEvading(), CreatureGroup::IsOutOfCombat(), CreatureGroup::MoveHome(), RemoveObject(), CreatureGroup::RemoveObject(), Spawn(), to_string(), and CreatureGroup::TriggerLinkingEvent().
m_objectTypeId
uint32 SpawnGroup::m_objectTypeId protected
Definition at line 69 of file SpawnGroup.h.
Referenced by GetObjectTypeId().
The documentation for this class was generated from the following files:
SpawnGroup.h
SpawnGroup.cpp