CMaNGOS_WoTLK: OutdoorPvP Class Reference
OutdoorPvP Class Reference
#include <OutdoorPvP.h>
Public Member Functions
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectCreate (GameObject *)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleGameObjectUse (Player *, GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Protected Member Functions
virtual void HandlePlayerEnterZone (Player *, bool)
virtual void HandlePlayerLeaveZone (Player *, bool)
Function that removes a player from the players of the affected outdoor pvp zones.
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Friends
class OutdoorPvPMgr
Detailed Description
Definition at line 46 of file OutdoorPvP.h.
Constructor & Destructor Documentation
OutdoorPvP()
OutdoorPvP::OutdoorPvP () inline
Definition at line 51 of file OutdoorPvP.h.
~OutdoorPvP()
virtual OutdoorPvP::~OutdoorPvP () inline virtual
Definition at line 52 of file OutdoorPvP.h.
Member Function Documentation
BuffTeam()
void OutdoorPvP::BuffTeam (Team team, uint32 spellId, bool remove = false, const uint32 areaId = 0)
Definition at line 143 of file OutdoorPvP.cpp.
References Messager< T >::AddMessage(), Unit::CastSpell(), WorldObject::GetAreaId(), WorldObject::GetMap(), Map::GetMessager(), Object::GetObjectGuid(), Map::GetPlayer(), Player::GetTeam(), m_zonePlayers, Unit::RemoveAuraHolderFromStack(), sObjectMgr, and TRIGGERED_OLD_TRIGGERED.
Referenced by BattlefieldWG::CleanupBattlefield(), BattlefieldWG::GetBattlefieldReady(), OutdoorPvPSI::HandleAreaTrigger(), BattlefieldWG::HandleDestructibleBuildingEvent(), OutdoorPvPZM::HandleGameObjectUse(), OutdoorPvPTF::LockZone(), OutdoorPvPNA::ProcessCaptureEvent(), OutdoorPvPEP::ProcessCaptureEvent(), OutdoorPvPHP::ProcessCaptureEvent(), and OutdoorPvPTF::UnlockZone().
CheckAchievementCriteriaMeet()
virtual bool OutdoorPvP::CheckAchievementCriteriaMeet (uint32 , Player const * , Unit const * , uint32) inline virtual
Reimplemented in BattlefieldWG.
Definition at line 110 of file OutdoorPvP.h.
FillInitialWorldStates()
virtual void OutdoorPvP::FillInitialWorldStates (WorldPacket & , uint32 &) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPEP, and BattlefieldWG.
Definition at line 55 of file OutdoorPvP.h.
GetBannerArtKit()
uint32 OutdoorPvP::GetBannerArtKit (Team team, uint32 artKitAlliance = CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde = CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral = CAPTURE_ARTKIT_NEUTRAL) const protected
Definition at line 176 of file OutdoorPvP.cpp.
References ALLIANCE, and HORDE.
Referenced by OutdoorPvPGH::HandleGameObjectCreate(), OutdoorPvPHP::HandleGameObjectCreate(), OutdoorPvPNA::HandleGameObjectCreate(), OutdoorPvPTF::HandleGameObjectCreate(), and OutdoorPvPEP::InitBanner().
HandleAreaTrigger()
virtual bool OutdoorPvP::HandleAreaTrigger (Player * , uint32) inline virtual
Reimplemented in OutdoorPvPSI.
Definition at line 77 of file OutdoorPvP.h.
HandleConditionStateChange()
virtual void OutdoorPvP::HandleConditionStateChange (uint32 , bool) inline virtual
Reimplemented in OutdoorPvPZM.
Definition at line 105 of file OutdoorPvP.h.
HandleCreatureCreate()
virtual void OutdoorPvP::HandleCreatureCreate (Creature *) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPNA, OutdoorPvPGH, OutdoorPvPEP, and BattlefieldWG.
Definition at line 64 of file OutdoorPvP.h.
HandleCreatureDeath()
virtual void OutdoorPvP::HandleCreatureDeath (Creature *) inline virtual
Reimplemented in OutdoorPvPNA, OutdoorPvPGH, and BattlefieldWG.
Definition at line 71 of file OutdoorPvP.h.
HandleDropFlag()
virtual bool OutdoorPvP::HandleDropFlag (Player * , uint32) inline virtual
Reimplemented in OutdoorPvPSI.
Definition at line 80 of file OutdoorPvP.h.
HandleEvent()
virtual bool OutdoorPvP::HandleEvent (uint32 , Object * , Object *) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPGH, OutdoorPvPEP, and BattlefieldWG.
Definition at line 58 of file OutdoorPvP.h.
Referenced by StartEvents_Event().
HandleGameObjectCreate()
void OutdoorPvP::HandleGameObjectCreate (GameObject * go) virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPGH, OutdoorPvPEP, and BattlefieldWG.
Definition at line 80 of file OutdoorPvP.cpp.
References GameObjectInfo::capturePoint, GAMEOBJECT_TYPE_CAPTURE_POINT, Object::GetEntry(), GameObject::GetGOInfo(), GameObject::SetCapturePointSlider(), sOutdoorPvPMgr, and GameObjectInfo::type.
Referenced by BattlefieldWG::HandleGameObjectCreate(), OutdoorPvPEP::HandleGameObjectCreate(), OutdoorPvPGH::HandleGameObjectCreate(), OutdoorPvPHP::HandleGameObjectCreate(), OutdoorPvPNA::HandleGameObjectCreate(), OutdoorPvPTF::HandleGameObjectCreate(), and OutdoorPvPZM::HandleGameObjectCreate().
HandleGameObjectRemove()
void OutdoorPvP::HandleGameObjectRemove (GameObject * go) virtual
Definition at line 94 of file OutdoorPvP.cpp.
References GAMEOBJECT_TYPE_CAPTURE_POINT, GameObject::GetCapturePointSliderValue(), Object::GetEntry(), GameObject::GetGOInfo(), GameObject::GetLootState(), GO_ACTIVATED, sOutdoorPvPMgr, and GameObjectInfo::type.
HandleGameObjectUse()
virtual bool OutdoorPvP::HandleGameObjectUse (Player * , GameObject *) inline virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPEP, and BattlefieldWG.
Definition at line 74 of file OutdoorPvP.h.
HandleObjectiveComplete()
virtual void OutdoorPvP::HandleObjectiveComplete (uint32 , const PlayerList & , Team) inline virtual
Reimplemented in OutdoorPvPTF, OutdoorPvPNA, OutdoorPvPHP, and OutdoorPvPEP.
Definition at line 61 of file OutdoorPvP.h.
HandlePlayerEnterArea()
virtual void OutdoorPvP::HandlePlayerEnterArea (Player * , uint32 , bool) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 117 of file OutdoorPvP.h.
HandlePlayerEnterZone()
void OutdoorPvP::HandlePlayerEnterZone (Player * player, bool isMainZone) protected virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPEP, BattlefieldWG, and Battlefield.
Definition at line 38 of file OutdoorPvP.cpp.
References Object::GetObjectGuid(), and m_zonePlayers.
Referenced by Battlefield::HandlePlayerEnterZone(), OutdoorPvPEP::HandlePlayerEnterZone(), OutdoorPvPHP::HandlePlayerEnterZone(), OutdoorPvPNA::HandlePlayerEnterZone(), OutdoorPvPSI::HandlePlayerEnterZone(), OutdoorPvPTF::HandlePlayerEnterZone(), and OutdoorPvPZM::HandlePlayerEnterZone().
HandlePlayerKill()
void OutdoorPvP::HandlePlayerKill (Player * killer, Unit * victim)
Function that handles kills in the main outdoor pvp zones.
Parameters
player who killed another unit
victim who was killed
Definition at line 110 of file OutdoorPvP.cpp.
References Player::CanUseCapturePoint(), Player::GetGroup(), HandlePlayerKillInsideArea(), Player::IsAtGroupRewardDistance(), Unit::IsTrivialForTarget(), and GroupReference::next().
HandlePlayerKillInsideArea()
virtual void OutdoorPvP::HandlePlayerKillInsideArea (Player * , Unit *) inline protected virtual
Reimplemented in BattlefieldWG, OutdoorPvPZM, OutdoorPvPNA, and OutdoorPvPHP.
Definition at line 124 of file OutdoorPvP.h.
Referenced by HandlePlayerKill().
HandlePlayerLeaveArea()
virtual void OutdoorPvP::HandlePlayerLeaveArea (Player * , uint32 , bool) inline protected virtual
Reimplemented in BattlefieldWG.
Definition at line 118 of file OutdoorPvP.h.
HandlePlayerLeaveZone()
void OutdoorPvP::HandlePlayerLeaveZone (Player * player, bool isMainZone) protected virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPSI, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPEP, BattlefieldWG, and Battlefield.
Definition at line 49 of file OutdoorPvP.cpp.
References WorldObject::GetName(), Object::GetObjectGuid(), Player::GetSession(), m_zonePlayers, WorldSession::PlayerLogout(), SendRemoveWorldStates(), and sLog.
Referenced by Battlefield::HandlePlayerLeaveZone(), OutdoorPvPEP::HandlePlayerLeaveZone(), OutdoorPvPHP::HandlePlayerLeaveZone(), OutdoorPvPNA::HandlePlayerLeaveZone(), OutdoorPvPSI::HandlePlayerLeaveZone(), OutdoorPvPTF::HandlePlayerLeaveZone(), and OutdoorPvPZM::HandlePlayerLeaveZone().
IsBattlefield()
bool OutdoorPvP::IsBattlefield () const inline
Definition at line 99 of file OutdoorPvP.h.
References m_isBattlefield.
Referenced by Player::CreateCorpse(), spell_teleport_lake_wintergrasp::OnEffectExecute(), Player::RemovedInsignia(), npc_spirit_guide_wintergraspAI::UpdateAI(), go_vehicle_teleporter::UpdateAI(), and Player::UpdateArea().
IsConditionFulfilled()
virtual bool OutdoorPvP::IsConditionFulfilled (Player const * , uint32 , WorldObject const * , uint32) inline virtual
Reimplemented in OutdoorPvPZM, and BattlefieldWG.
Definition at line 102 of file OutdoorPvP.h.
RespawnGO()
void OutdoorPvP::RespawnGO (const WorldObject * objRef, ObjectGuid goGuid, bool respawn) protected
Definition at line 202 of file OutdoorPvP.cpp.
References DAY, Map::GetGameObject(), and WorldObject::GetMap().
Referenced by OutdoorPvPNA::HandleFactionObjects(), OutdoorPvPNA::HandleGameObjectUse(), OutdoorPvPZM::HandleGameObjectUse(), and OutdoorPvPEP::ProcessCaptureEvent().
SendRemoveWorldStates()
virtual void OutdoorPvP::SendRemoveWorldStates (Player *) inline protected virtual
Reimplemented in OutdoorPvPZM, OutdoorPvPTF, OutdoorPvPNA, OutdoorPvPHP, OutdoorPvPEP, and BattlefieldWG.
Definition at line 121 of file OutdoorPvP.h.
Referenced by HandlePlayerLeaveZone(), and Battlefield::StartBattle().
SendUpdateWorldState()
void OutdoorPvP::SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
Parameters
world state to update
new world state value
Definition at line 67 of file OutdoorPvP.cpp.
References m_zonePlayers, and sObjectMgr.
Referenced by BattlefieldWG::CleanupBattlefield(), BattlefieldWG::GetBattlefieldReady(), OutdoorPvPSI::HandleAreaTrigger(), BattlefieldWG::HandleCapturePointEvent(), BattlefieldWG::HandleCreatureCreate(), OutdoorPvPNA::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), OutdoorPvPNA::HandleCreatureDeath(), BattlefieldWG::HandleDestructibleBuildingEvent(), OutdoorPvPZM::HandleGameObjectUse(), OutdoorPvPTF::LockZone(), OutdoorPvPNA::ProcessCaptureEvent(), OutdoorPvPEP::ProcessCaptureEvent(), OutdoorPvPTF::ProcessCaptureEvent(), OutdoorPvPZM::ProcessCaptureEvent(), OutdoorPvPHP::ProcessCaptureEvent(), BattlefieldWG::SendBattlefieldTimerUpdate(), BattlefieldWG::SendUpdateGeneralWorldStates(), OutdoorPvPTF::UnlockZone(), OutdoorPvPZM::UpdateScoutState(), OutdoorPvPTF::UpdateTimerWorldState(), OutdoorPvPNA::UpdateWorldState(), and OutdoorPvPNA::UpdateWyvernsWorldState().
SetBannerVisual() [1/2]
void OutdoorPvP::SetBannerVisual (const WorldObject * objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
Definition at line 189 of file OutdoorPvP.cpp.
References Map::GetGameObject(), and WorldObject::GetMap().
Referenced by BattlefieldWG::HandleCapturePointEvent(), OutdoorPvPGH::HandleEvent(), OutdoorPvPNA::HandleEvent(), BattlefieldWG::LockWorkshops(), OutdoorPvPEP::ProcessCaptureEvent(), OutdoorPvPTF::ProcessCaptureEvent(), OutdoorPvPHP::ProcessCaptureEvent(), and OutdoorPvPTF::ResetTowers().
SetBannerVisual() [2/2]
void OutdoorPvP::SetBannerVisual (GameObject * go, uint32 artKit, uint32 animId)
Definition at line 195 of file OutdoorPvP.cpp.
References Object::GetObjectGuid(), GameObject::Refresh(), WorldObject::SendGameObjectCustomAnim(), and GameObject::SetGoArtKit().
SetGraveYardLinkTeam()
void OutdoorPvP::SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
Parameters
player to add
whether zone is main outdoor pvp zone or a affected zone
Definition at line 32 of file OutdoorPvP.cpp.
References Map::GetGraveyardManager(), World::GetGraveyardManager(), Map::GetMessager(), sMapMgr, and sWorld.
Referenced by BattlefieldWG::CleanupBattlefield(), BattlefieldWG::GetBattlefieldReady(), BattlefieldWG::HandleCapturePointEvent(), OutdoorPvPZM::HandleGameObjectUse(), OutdoorPvPEP::OutdoorPvPEP(), OutdoorPvPNA::OutdoorPvPNA(), OutdoorPvPZM::OutdoorPvPZM(), OutdoorPvPNA::ProcessCaptureEvent(), OutdoorPvPEP::ProcessCaptureEvent(), and BattlefieldWG::Reset().
Update()
virtual void OutdoorPvP::Update (uint32) inline virtual
Reimplemented in Battlefield, OutdoorPvPTF, OutdoorPvPNA, and BattlefieldWG.
Definition at line 83 of file OutdoorPvP.h.
Friends And Related Function Documentation
OutdoorPvPMgr
friend class OutdoorPvPMgr friend
Definition at line 48 of file OutdoorPvP.h.
Field Documentation
m_isBattlefield
bool OutdoorPvP::m_isBattlefield protected
Definition at line 135 of file OutdoorPvP.h.
Referenced by Battlefield::Battlefield(), and IsBattlefield().
m_zonePlayers
GuidZoneMap OutdoorPvP::m_zonePlayers protected
Definition at line 133 of file OutdoorPvP.h.
Referenced by BuffTeam(), BattlefieldWG::GetPlayerInZone(), HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerEnterZone(), HandlePlayerLeaveZone(), Battlefield::InitPlayersBeforeBattle(), Battlefield::QuestCreditTeam(), OutdoorPvPNA::RespawnSoldier(), BattlefieldWG::RewardPlayersOnBattleEnd(), SendUpdateWorldState(), Battlefield::SendZoneWarning(), Battlefield::StartBattle(), OutdoorPvPTF::UnlockZone(), Battlefield::Update(), and BattlefieldWG::UpdateTenacities().
The documentation for this class was generated from the following files:
OutdoorPvP.h
OutdoorPvP.cpp