CMaNGOS_WoTLK: ScriptedInstance Class Reference
ScriptedInstance Class Reference
#include <sc_instance.h>
Public Types
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Public Member Functions
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Initialize ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectCreate (GameObject *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureCreate (Creature *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual uint32 GetData (uint32) const
virtual void SetData (uint32, uint32)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 27 of file sc_instance.h.
Member Typedef Documentation
EntryGuidCollection
typedef std::unordered_map<uint32, GuidVector> ScriptedInstance::EntryGuidCollection
Definition at line 31 of file sc_instance.h.
EntryGuidMap
typedef std::map<uint32, ObjectGuid> ScriptedInstance::EntryGuidMap
Definition at line 30 of file sc_instance.h.
Constructor & Destructor Documentation
ScriptedInstance()
ScriptedInstance::ScriptedInstance (Map * map) inline
Definition at line 33 of file sc_instance.h.
~ScriptedInstance()
ScriptedInstance::~ScriptedInstance () inline
Definition at line 34 of file sc_instance.h.
Member Function Documentation
BanPlayersIfNoGm()
void ScriptedInstance::BanPlayersIfNoGm (const std::string & reason)
Definition at line 157 of file sc_instance.cpp.
References Player::BanPlayer(), Map::GetPlayers(), WorldSession::GetSecurity(), Player::GetSession(), InstanceData::instance, and SEC_GAMEMASTER.
Referenced by instance_black_temple::SetData(), and instance_sunwell_plateau::SetData().
DespawnGuids()
void ScriptedInstance::DespawnGuids (GuidVector & spawns) protected
Definition at line 185 of file sc_instance.cpp.
References Map::GetAnyTypeCreature(), Map::GetGameObject(), GO_JUST_DEACTIVATED, and InstanceData::instance.
Referenced by instance_mount_hyjal::DespawnWaveSpawns(), instance_sunwell_plateau::ResetGauntlet(), world_map_outland::SetData(), instance_sunwell_plateau::SetData(), instance_naxxramas::SetData(), and instance_magtheridons_lair::SetData().
DoOrSimulateScriptTextForThisInstance()
void ScriptedInstance::DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry) inline
Definition at line 62 of file sc_instance.h.
References DoOrSimulateScriptTextForMap(), GetSingleCreatureFromStorage(), and InstanceData::instance.
Referenced by instance_scarlet_monastery::DoHandleAreaTrigger(), DialogueHelper::DoNextDialogueStep(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), instance_naxxramas::DoTaunt(), instance_zulaman::DoTimeRunSay(), instance_zulgurub::DoYellAtTriggerIfCan(), instance_ulduar::JustDidDialogueStep(), instance_naxxramas::OnCreatureDeath(), instance_stratholme::SetData(), instance_sunken_temple::SetData(), instance_culling_of_stratholme::SetData(), instance_stratholme::StartSlaughterSquare(), instance_stratholme::ThazudinAcolyteJustDied(), instance_blackwing_lair::Update(), instance_stratholme::Update(), instance_sunwell_plateau::Update(), instance_culling_of_stratholme::Update(), instance_magtheridons_lair::Update(), and instance_shattered_halls::Update().
DoRespawnGameObject() [1/2]
void ScriptedInstance::DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn = MINUTE)
Function that respawns a despawned GameObject with given time.
Parameters
guid The ObjectGuid of the GO that will be respawned
uiTimeToDespawn (in seconds) Despawn the GO after this time, default is a minute
Definition at line 56 of file sc_instance.cpp.
References Map::GetGameObject(), and InstanceData::instance.
Referenced by world_map_ebon_hold::DoEnableHolyTraps(), instance_karazhan::DoFinishChessEvent(), instance_trial_of_the_crusader::DoHandleEventEpilogue(), instance_karazhan::DoPrepareOperaStage(), DoRespawnGameObject(), instance_sunken_temple::DoSpawnAtalarionIfCan(), npc_warlock_mount_ritualAI::DoSummonPack(), instance_dark_portal::ExecutePostEventStep(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), instance_deadmines::OnPlayerEnter(), instance_wailing_caverns::OnPlayerEnter(), instance_dire_maul::ProcessDreadsteedRitualStart(), instance_icecrown_citadel::ProcessEventNpcs(), npc_halion_controllerAI::ReceiveAIEvent(), instance_mount_hyjal::RetreatBase(), instance_blackrock_depths::SetData(), instance_gnomeregan::SetData(), instance_molten_core::SetData(), instance_sunken_temple::SetData(), instance_uldaman::SetData(), instance_culling_of_stratholme::SetData(), instance_old_hillsbrad::SetData(), instance_dire_maul::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_eye_of_eternity::SetData(), instance_oculus::SetData(), instance_ulduar::SetData(), instance_ramparts::SetData(), instance_mount_hyjal::SpawnOres(), npc_brain_yogg_saronAI::SummonedCreatureJustDied(), instance_eye_of_eternity::Update(), and instance_halls_of_reflection::Update().
DoRespawnGameObject() [2/2]
void ScriptedInstance::DoRespawnGameObject (uint32 entry, uint32 timeToDespawn = MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
Definition at line 110 of file sc_instance.cpp.
References debug_log(), DoRespawnGameObject(), Map::GetId(), InstanceData::instance, and m_goEntryGuidStore.
DoStartTimedAchievement()
void ScriptedInstance::DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Parameters
criteriaType The Type that is required to complete the criteria, see enum AchievementCriteriaTypes in MaNGOS
uiTimedCriteriaMiscId The ID that identifies how the criteria is started
Definition at line 273 of file sc_instance.cpp.
References debug_log(), Map::GetPlayers(), InstanceData::instance, and LinkedListHead::isEmpty().
Referenced by boss_volazjAI::Aggro(), boss_lich_king_horAI::ReceiveAIEvent(), instance_onyxias_lair::SetData(), instance_ahnkahet::SetData(), instance_azjol_nerub::SetData(), instance_trial_of_the_crusader::SetData(), instance_naxxramas::SetData(), instance_eye_of_eternity::SetData(), instance_oculus::SetData(), instance_halls_of_lightning::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), and instance_pinnacle::SetData().
DoToggleGameObjectFlags() [1/2]
void ScriptedInstance::DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
Parameters
guid The ObjectGuid of the GO that will be respawned
uiGOflags Which GO-flags to toggle
bApply should the GO-flags be applied or removed?
Definition at line 95 of file sc_instance.cpp.
References ByteConverter::apply(), GAMEOBJECT_FLAGS, Map::GetGameObject(), and InstanceData::instance.
Referenced by boss_kiljaedenAI::DoActivateDragonOrb(), instance_karazhan::DoFinishChessEvent(), DoToggleGameObjectFlags(), instance_sunken_temple::DoUpdateFlamesFlags(), instance_blackwing_lair::OnCreatureDeath(), instance_icecrown_citadel::OnCreatureDeath(), instance_dire_maul::OnPlayerEnter(), instance_blackrock_depths::SetData(), instance_blackwing_lair::SetData(), instance_karazhan::SetData(), instance_magisters_terrace::SetData(), instance_culling_of_stratholme::SetData(), instance_ahnkahet::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_nexus::SetData(), instance_oculus::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_sethekk_halls::SetData(), instance_serpentshrine_cavern::SetData(), instance_steam_vault::SetData(), instance_ramparts::SetData(), instance_magtheridons_lair::SetData(), instance_blackwing_lair::SetData64(), instance_halls_of_reflection::Update(), instance_ulduar::Update(), instance_violet_hold::UpdateCrystals(), and npc_harrison_jones_zaAI::WaypointReached().
DoToggleGameObjectFlags() [2/2]
void ScriptedInstance::DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
Definition at line 78 of file sc_instance.cpp.
References ByteConverter::apply(), debug_log(), DoToggleGameObjectFlags(), Map::GetId(), InstanceData::instance, and m_goEntryGuidStore.
DoUpdateWorldState()
void ScriptedInstance::DoUpdateWorldState (uint32 stateId, uint32 stateData) virtual
Helper function to update a world state for all players in the map.
Parameters
uiStateId The WorldState that will be set for all players in the map
uiStateData The Value to which the State will be set to
Definition at line 126 of file sc_instance.cpp.
References debug_log(), Map::GetPlayers(), InstanceData::instance, and LinkedListHead::isEmpty().
Referenced by boss_algalonAI::Aggro(), instance_halls_of_reflection::DoCleanupFrostmourneEvent(), instance_halls_of_reflection::DoSendNextSpiritWave(), npc_halion_controllerAI::DoUpdateCorporeality(), instance_dark_portal::ExecuteChatCommand(), instance_oculus::OnCreatureDeath(), instance_old_hillsbrad::OnCreatureEnterCombat(), npc_halion_controllerAI::ReceiveAIEvent(), instance_culling_of_stratholme::SetData(), instance_dark_portal::SetData(), instance_old_hillsbrad::SetData(), instance_trial_of_the_crusader::SetData(), instance_halls_of_reflection::SetData(), instance_oculus::SetData(), instance_ruby_sanctum::SetData(), instance_ulduar::SetData(), instance_violet_hold::SetData(), instance_oculus::SetData64(), instance_culling_of_stratholme::Update(), instance_dark_portal::Update(), instance_violet_hold::Update(), instance_dark_portal::UpdateWorldState(), and instance_violet_hold::UpdateWorldState().
DoUseDoorOrButton() [1/2]
void ScriptedInstance::DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime = 0, bool useAlternativeState = false)
Function that uses a door or a button.
Parameters
guid The ObjectGuid of the Door/ Button that will be used
uiWithRestoreTime (in seconds) if == 0 autoCloseTime will be used (if not 0 by default in *_template)
bUseAlternativeState Use to alternative state
Definition at line 14 of file sc_instance.cpp.
References GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_TRAPDOOR, Map::GetGameObject(), GO_ACTIVATED, GO_READY, InstanceData::instance, and script_error_log().
Referenced by instance_halls_of_stone::ActivateFace(), boss_akilzonAI::boss_akilzonAI(), boss_kalecgos_humanoidAI::boss_kalecgos_humanoidAI(), boss_zuljinAI::boss_zuljinAI(), instance_gnomeregan::DoActivateBombFace(), instance_halls_of_reflection::DoCleanupFrostmourneEvent(), instance_gnomeregan::DoDeactivateBombFace(), instance_karazhan::DoFinishChessEvent(), instance_stratholme::DoGateTrap(), instance_draktharon_keep::DoHandleCrystal(), instance_ruby_sanctum::DoHandleZarithrianDoor(), instance_blood_furnace::DoNextBroggokEventPhase(), instance_ulduar::DoOpenMadnessDoorIfCan(), instance_trial_of_the_crusader::DoOpenMainGate(), instance_black_temple::DoOpenPreMotherDoor(), instance_stratholme::DoOpenSlaughterhouseDoor(), instance_blackrock_spire::DoSendNextStadiumWave(), DoUseDoorOrButton(), instance_blackrock_spire::DoUseEmberseerRunes(), instance_zulaman::ExecuteChatCommand(), instance_blackrock_depths::HandleBarPatrol(), boss_kelthuzadAI::HandleLichKingAnswer(), instance_scholomance::HandlePortalEvent(), npc_arthasAI::JustDidDialogueStep(), instance_trial_of_the_champion::JustDidDialogueStep(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_brann_hosAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), instance_ulduar::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), instance_arcatraz::JustDidDialogueStep(), npc_blastmaster_emi_shortfuseAI::JustDied(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_brann_hosAI::MovementInform(), instance_trial_of_the_crusader::OnCreatureCreate(), instance_blackrock_spire::OnCreatureDeath(), instance_ulduar::OnCreatureDeath(), instance_blackrock_depths::OnObjectCreate(), instance_scarlet_monastery::OnObjectSpawn(), instance_icecrown_citadel::ProcessEventNpcs(), instance_dire_maul::ProcessForceFieldOpening(), instance_shadowfang_keep::SetData(), instance_stratholme::SetData(), instance_zulgurub::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), instance_blackrock_depths::SetData(), instance_blackrock_spire::SetData(), instance_blackwing_lair::SetData(), instance_deadmines::SetData(), instance_karazhan::SetData(), instance_magisters_terrace::SetData(), instance_molten_core::SetData(), instance_scarlet_monastery::SetData(), instance_scholomance::SetData(), instance_sunken_temple::SetData(), instance_sunwell_plateau::SetData(), instance_uldaman::SetData(), instance_zulaman::SetData(), instance_blackfathom_deeps::SetData(), instance_culling_of_stratholme::SetData(), instance_dire_maul::SetData(), instance_razorfen_kraul::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_ahnkahet::SetData(), instance_azjol_nerub::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_draktharon_keep::SetData(), instance_gundrak::SetData(), instance_halls_of_reflection::SetData(), instance_pit_of_saron::SetData(), instance_icecrown_citadel::SetData(), instance_naxxramas::SetData(), instance_oculus::SetData(), instance_ruby_sanctum::SetData(), instance_halls_of_lightning::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_utgarde_keep::SetData(), instance_pinnacle::SetData(), instance_violet_hold::SetData(), instance_sethekk_halls::SetData(), instance_shadow_labyrinth::SetData(), instance_steam_vault::SetData(), instance_gruuls_lair::SetData(), instance_magtheridons_lair::SetData(), instance_shattered_halls::SetData(), instance_arcatraz::SetData(), instance_the_eye::SetData(), instance_mechanar::SetData(), instance_violet_hold::StartEvent(), instance_stratholme::StartSlaughterSquare(), npc_brain_yogg_saronAI::SummonedCreatureJustDied(), instance_deadmines::Update(), instance_stratholme::Update(), instance_trial_of_the_champion::Update(), instance_trial_of_the_crusader::Update(), instance_gundrak::Update(), instance_icecrown_citadel::Update(), instance_ruby_sanctum::Update(), instance_ulduar::Update(), boss_kaelthasAI::UpdateAI(), instance_violet_hold::UpdateCellForBoss(), npc_grimstoneAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_rocknotAI::WaypointReached(), npc_marshal_windsorAI::WaypointReached(), npc_barnesAI::WaypointReached(), and npc_blastmaster_emi_shortfuseAI::WaypointStart().
DoUseDoorOrButton() [2/2]
void ScriptedInstance::DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime = 0, bool useAlternativeState = false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
Definition at line 34 of file sc_instance.cpp.
References debug_log(), DoUseDoorOrButton(), Map::GetId(), InstanceData::instance, and m_goEntryGuidStore.
DoUseOpenableObject()
void ScriptedInstance::DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime = 0, bool useAlternativeState = false)
Definition at line 44 of file sc_instance.cpp.
References GetSingleGameObjectFromStorage().
Referenced by instance_sunwell_plateau::Initialize(), instance_the_eye::OpenDoors(), BossAI::OpenEntrances(), BossAI::OpenExits(), instance_stratholme::SetData(), instance_sunwell_plateau::SetData(), instance_zulaman::SetData(), instance_naxxramas::SetData(), instance_shattered_halls::SetData(), and instance_gundrak::Update().
GetCreatureGuidVectorFromStorage()
void ScriptedInstance::GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector & entryGuidVector, bool skipDebugLog = false) const
Definition at line 253 of file sc_instance.cpp.
References m_npcEntryGuidCollection.
Referenced by boss_soccothratesAI::Aggro(), instance_shattered_halls::DoBeginArcherAttack(), npc_flame_of_azzinothAI::DoPickChargeTarget(), boss_ossirianAI::DoSpawnNextCrystal(), instance_sunwell_plateau::DropFog(), instance_sunwell_plateau::FailKiljaeden(), instance_sethekk_halls::FinishAnzuIntro(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulEventReset(), boss_kaelthasAI::MovementInform(), npc_vimgol_middle_bunnyAI::npc_vimgol_middle_bunnyAI(), npc_vimgol_visual_bunnyAI::npc_vimgol_visual_bunnyAI(), instance_shadow_labyrinth::OnCreatureDeath(), npc_vimgol_middle_bunnyAI::playersInsideCircles(), boss_murmurAI::ReceiveAIEvent(), boss_ossirianAI::RespawnFirstCrystal(), world_map_outland::ScriptAction(), world_map_outland::SetData(), instance_sunwell_plateau::SetData(), instance_magtheridons_lair::SetData(), and instance_arcatraz::SetData().
GetGameObjectGuidVectorFromStorage()
void ScriptedInstance::GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector & entryGuidVector, bool skipDebugLog = false) const
Definition at line 260 of file sc_instance.cpp.
References m_goEntryGuidCollection.
Referenced by npc_drijyaAI::npc_drijyaAI(), and instance_ruins_of_ahnqiraj::SetData().
GetPlayerInMap()
Player * ScriptedInstance::GetPlayerInMap (bool bOnlyAlive = false, bool bCanBeGamemaster = true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
Definition at line 143 of file sc_instance.cpp.
References Map::GetPlayers(), Object::HasFlag(), InstanceData::instance, Unit::IsAlive(), Unit::IsFeigningDeathSuccessfully(), Player::IsGameMaster(), UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and UNIT_FLAG_UNTARGETABLE.
Referenced by boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_felmystAI::boss_felmystAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_moamAI::boss_moamAI(), boss_netherspiteAI::boss_netherspiteAI(), boss_razorgoreAI::boss_razorgoreAI(), boss_sathrovarrAI::boss_sathrovarrAI(), boss_vexallusAI::boss_vexallusAI(), boss_skeramAI::ClearMark(), instance_blackrock_depths::DoCallNextDwarf(), instance_zulaman::DoChestEvent(), instance_karazhan::DoFinishChessEvent(), instance_trial_of_the_crusader::DoHandleEventEpilogue(), instance_stratholme::DoScarletBastionDefense(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_ruins_of_ahnqiraj::DoSpawnAndorovIfCan(), instance_sunken_temple::DoSpawnAtalarionIfCan(), instance_mechanar::DoSpawnBridgeWave(), boss_mimironAI::DoSpawnFlamesInitial(), instance_scholomance::DoSpawnGandlingIfCan(), instance_molten_core::DoSpawnMajordomoIfCan(), instance_oculus::DoSpawnNextBossIfCan(), instance_trial_of_the_crusader::DoSummonRamsey(), boss_heiganAI::EnterEvadeMode(), instance_halls_of_stone::ExecuteChatCommand(), instance_trial_of_the_crusader::JustDidDialogueStep(), instance_pinnacle::JustDidDialogueStep(), boss_sjonnirAI::JustDied(), boss_lich_king_horAI::JustSummoned(), instance_azjol_nerub::OnCreatureRespawn(), instance_molten_core::SetData(), instance_scholomance::SetData(), instance_sunken_temple::SetData(), instance_culling_of_stratholme::SetData(), instance_old_hillsbrad::SetData(), instance_forge_of_souls::SetData(), instance_halls_of_reflection::SetData(), instance_ulduar::SetData(), instance_serpentshrine_cavern::SetData(), instance_ramparts::SetData(), instance_shattered_halls::SetData(), instance_mechanar::SetData(), instance_mount_hyjal::SpawnArchimonde(), instance_ulduar::SpawnFriendlyKeeper(), instance_ulduar::SpawnKeeperHelper(), boss_kelthuzadAI::SpellHit(), instance_stratholme::Update(), instance_uldaman::Update(), instance_culling_of_stratholme::Update(), instance_mount_hyjal::Update(), instance_naxxramas::Update(), instance_blood_furnace::Update(), instance_shattered_halls::Update(), instance_arcatraz::Update(), instance_halls_of_reflection::Update(), instance_pit_of_saron::Update(), instance_temple_of_ahnqiraj::Update(), npc_tanzarAI::UpdateAI(), and npc_grandmotherAI::UpdateAI().
GetSingleCreatureFromStorage()
Creature * ScriptedInstance::GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog = false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
Definition at line 240 of file sc_instance.cpp.
References Map::GetCreature(), Map::GetId(), InstanceData::instance, m_npcEntryGuidStore, and script_error_log().
Referenced by boss_kalecgosAI::Aggro(), boss_gormokAI::Aggro(), boss_festergutAI::Aggro(), boss_rotfaceAI::Aggro(), boss_halion_realAI::Aggro(), boss_illidari_councilAI::Aggro(), mob_fel_orc_convertAI::Aggro(), boss_ickAI::Aggro(), boss_tyrannusAI::Aggro(), mob_shadowmoon_channelerAI::Aggro(), AreaTrigger_at_bartolo_ginsetti(), AreaTrigger_at_brewfest_barker(), AreaTrigger_at_ghazan_surface(), AreaTrigger_at_murkdeep(), AreaTrigger_at_naturalist_bite(), AreaTrigger_at_naxxramas(), AreaTrigger_at_putricides_trap(), AreaTrigger_at_queldelar_start(), AreaTrigger_at_rampart_skull(), AreaTrigger_at_teron_gorefiend(), AreaTrigger_at_zulfarrak(), npc_shadow_imageAI::AttackRandomTarget(), boss_sartharionAI::CallDragon(), boss_thekalAI::CanPreventAddsResurrect(), world_map_outland::CheckConditionCriteriaMeet(), instance_dark_portal::CheckConditionCriteriaMeet(), instance_blackwing_lair::CleanupNefarianStage(), instance_violet_hold::CreateBossSpawnByEntry(), npc_akamaAI::DamageTaken(), advisor_base_ai::DamageTaken(), boss_twin_emperorsAI::DamageTaken(), boss_thorimAI::DamageTaken(), npc_king_llaneAI::DamageTaken(), npc_warchief_blackhandAI::DamageTaken(), boss_halion_realAI::DamageTaken(), boss_halion_twilightAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), boss_leviathan_mk2AI::DamageTaken(), boss_vx001AI::DamageTaken(), boss_aerial_unitAI::DamageTaken(), instance_mount_hyjal::DespawnBase(), boss_skadiAI::DoBoardGrauf(), instance_ulduar::DoCallLeviathanHelp(), instance_blackrock_depths::DoCallNextDwarf(), boss_fjolaAI::DoCastSpecialAbility(), instance_culling_of_stratholme::DoChromieWhisper(), instance_trial_of_the_champion::DoCleanupArenaOnWipe(), instance_trial_of_the_crusader::DoCleanupCrusaders(), instance_halls_of_reflection::DoCleanupFrostmourneEvent(), world_map_ebon_hold::DoClearBattleScene(), boss_freyaAI::DoDrainElders(), mob_illidari_councilAI::DoEndEvent(), instance_culling_of_stratholme::DoEventAtTriggerIfCan(), instance_karazhan::DoFailChessEvent(), instance_ramparts::DoFailVazruden(), instance_karazhan::DoFinishChessEvent(), boss_mimironAI::DoFlyToNextRandomSeat(), instance_dark_portal::DoHandleAreaTrigger(), npc_graufAI::DoHandleBreathYell(), instance_icecrown_citadel::DoHandleCitadelAreaTrigger(), boss_halion_twilightAI::DoHandleShadowOrbEvent(), instance_temple_of_ahnqiraj::DoHandleTempleAreaTrigger(), instance_ruby_sanctum::DoHandleZarithrianDoor(), instance_shattered_halls::DoInitialGets(), boss_saraAI::DoInitialiseKeepers(), boss_malacrassAI::DoInitializeAdds(), boss_priestess_delrissaAI::DoInitializeCompanions(), instance_blood_furnace::DoNextBroggokEventPhase(), DialogueHelper::DoNextDialogueStep(), instance_black_temple::DoOpenPreMotherDoor(), DoOrSimulateScriptTextForThisInstance(), npc_mistress_nagmaraAI::DoPotionOfLoveIfCan(), instance_trial_of_the_champion::DoPrepareChampions(), instance_blackrock_spire::DoProcessEmberseerEvent(), instance_violet_hold::DoReleaseBoss(), world_map_ebon_hold::DoResetBattleScene(), boss_ymironAI::DoResetSpirits(), boss_gathios_the_shattererAI::DoSelectCouncilMember(), instance_trial_of_the_champion::DoSendNextArenaWave(), instance_ruins_of_ahnqiraj::DoSendNextArmyWave(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_blackrock_spire::DoSendNextStadiumWave(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), instance_trial_of_the_crusader::DoSetCrusadersInCombat(), instance_ruins_of_ahnqiraj::DoSortArmyWaves(), instance_draktharon_keep::DoSortNovosDummies(), instance_stratholme::DoSortZiggurats(), instance_ruins_of_ahnqiraj::DoSpawnAndorovIfCan(), instance_culling_of_stratholme::DoSpawnArthasIfNeeded(), instance_sunken_temple::DoSpawnAtalarionIfCan(), instance_culling_of_stratholme::DoSpawnChromieIfNeeded(), instance_culling_of_stratholme::DoSpawnCorruptorIfNeeded(), boss_mimironAI::DoSpawnFlamesInitial(), instance_scholomance::DoSpawnGandlingIfCan(), boss_moroesAI::DoSpawnGuests(), instance_molten_core::DoSpawnMajordomoIfCan(), instance_blackfathom_deeps::DoSpawnMobs(), instance_oculus::DoSpawnNextBossIfCan(), instance_dark_portal::DoSpawnNextPortal(), instance_culling_of_stratholme::DoSpawnNextScourgeWave(), boss_flame_leviathanAI::DoSpawnThorimHammer(), instance_pit_of_saron::DoSpawnTyrannusUndead(), instance_shadowfang_keep::DoSpeech(), instance_pit_of_saron::DoStartAmbushEvent(), npc_highlord_darion_mograineAI::DoStartConclusion(), mob_illidari_councilAI::DoStartEvent(), instance_pit_of_saron::DoStartIntroEvent(), boss_kalecgosAI::DoStartOutro(), instance_pit_of_saron::DoStartTyrannusEvent(), npc_valentine_boss_managerAI::DoStartValentineEvent(), npc_teleportation_portalAI::DoSummon(), instance_trial_of_the_champion::DoSummonHeraldIfNeeded(), npc_beast_combat_stalkerAI::DoSummonNextBeast(), boss_skeramAI::DoTeleport(), instance_black_temple::DoTeleportAkamaIfCan(), npc_halion_controllerAI::DoUpdateCorporeality(), EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectDummyCreature_npc_vault_warder(), EffectDummyCreature_spell_guard_slip_kik(), EffectScriptEffectCreature_spell_inhale_blight(), boss_midnightAI::EnterEvadeMode(), boss_attumenAI::EnterEvadeMode(), priestess_companion_commonAI::EnterEvadeMode(), boss_sathrovarrAI::EnterEvadeMode(), boss_zuljinAI::EnterEvadeMode(), boss_thekalAI::EnterEvadeMode(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_living_mojoAI::EnterEvadeMode(), essence_base_AI::EnterEvadeMode(), boss_essence_of_angerAI::EnterEvadeMode(), npc_enslaved_soulAI::EnterEvadeMode(), boss_fathomguard_sharkkisAI::EnterEvadeMode(), boss_fathomguard_tidalvessAI::EnterEvadeMode(), boss_fathomguard_caribdisAI::EnterEvadeMode(), boss_vazrudenAI::EnterEvadeMode(), boss_attumenAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), boss_apothecary_hummelAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_spirit_lynxAI::ExecuteAction(), boss_ickAI::ExecuteAction(), boss_tyrannusAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), instance_sunwell_plateau::ExecuteChatCommand(), instance_mount_hyjal::ExecuteChatCommand(), boss_zuljinAI::ExecutePhaseTransition(), instance_dark_portal::ExecutePostEventStep(), instance_mount_hyjal::FailEvent(), instance_sunwell_plateau::FailKiljaeden(), boss_sartharionAI::FetchDragons(), boss_freyaAI::FetchElders(), boss_flame_leviathanAI::FetchTowers(), instance_sethekk_halls::FinishAnzuIntro(), world_map_outland::FinishPhase(), boss_brutallusAI::GetAIInformation(), world_map_outland::GetCurrentDemon(), boss_thaddiusAddsAI::GetOtherAdd(), boss_thorimAI::GetRandomArenaPlayer(), world_map_outland::GetShartuulManager(), GossipSelect_npc_taretha(), GOUse_go_big_red_button(), GOUse_go_infernaling_summoner_portal_hound(), GOUse_go_sapphiron_birth(), GOUse_go_wooden_door(), instance_blackrock_depths::HandleBarPatrol(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirEnemyAttack(), world_map_outland::HandleBashirOutro(), instance_scholomance::HandleDawnGambitEvent(), npc_grand_collectorAI::HandleEvent(), boss_kiljaedenAI::HandleKalecYell(), BrewfestEvent::HandleKegTappingEvent(), boss_scarlet_commander_mograineAI::HandleLayOnHandsTimer(), boss_kelthuzadAI::HandleLichKingAnswer(), boss_brutallusAI::HandleMadrigosaFrostbolt(), boss_brutallusAI::HandleMadrigosaSpawnMove(), npc_shivan_assassinAI::HandleOocAnim(), npc_akama_illidanAI::HandleOutro(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulEventReset(), world_map_outland::HandleShartuulSpawnSequence(), boss_felmystAI::HandleSideMove(), instance_old_hillsbrad::HandleThrallRelocation(), boss_twin_emperorsAI::HealedBy(), instance_trial_of_the_champion::InformChampionReachHome(), instance_sunwell_plateau::Initialize(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), instance_shadowfang_keep::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), instance_temple_of_ahnqiraj::JustDidDialogueStep(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_maievAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), instance_blackrock_spire::JustDidDialogueStep(), npc_image_of_medivhAI::JustDidDialogueStep(), npc_valentine_boss_managerAI::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), npc_kiljaeden_controllerAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), instance_sunwell_plateau::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDidDialogueStep(), npc_tarethaAI::JustDidDialogueStep(), instance_trial_of_the_champion::JustDidDialogueStep(), instance_trial_of_the_crusader::JustDidDialogueStep(), instance_halls_of_reflection::JustDidDialogueStep(), instance_pit_of_saron::JustDidDialogueStep(), npc_queen_lanathel_introAI::JustDidDialogueStep(), boss_malygosAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), boss_thorimAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), npc_brain_yogg_saronAI::JustDidDialogueStep(), instance_ulduar::JustDidDialogueStep(), instance_pinnacle::JustDidDialogueStep(), npc_akama_illidanAI::JustDidDialogueStep(), instance_arcatraz::JustDidDialogueStep(), boss_soccothratesAI::JustDidDialogueStep(), boss_plugger_spazzringAI::JustDied(), boss_emperor_dagran_thaurissanAI::JustDied(), boss_thekalAI::JustDied(), boss_eye_of_cthunAI::JustDied(), boss_drakkari_elementalAI::JustDied(), npc_living_mojoAI::JustDied(), boss_ickAI::JustDied(), npc_blood_orb_controlAI::JustDied(), boss_festergutAI::JustDied(), boss_rotfaceAI::JustDied(), npc_rimefang_iccAI::JustDied(), npc_spinestalker_iccAI::JustDied(), boss_thaddiusAI::JustDied(), boss_flame_leviathanAI::JustDied(), npc_saronite_vaporAI::JustDied(), npc_flash_freezeAI::JustDied(), boss_heart_deconstructorAI::JustDied(), npc_graufAI::JustDied(), npc_enslaved_soulAI::JustDied(), boss_shade_of_akamaAI::JustDied(), mob_ashtongue_channelerAI::JustDied(), mob_ashtongue_sorcererAI::JustDied(), boss_swamplord_muselekAI::JustDied(), Council_Base_AI::JustDied(), npc_warden_mellicharAI::JustDied(), npc_general_andorovAI::JustDied(), boss_forgemaster_garfrostAI::JustDied(), boss_tyrannusAI::JustDied(), mob_shadowmoon_channelerAI::JustDied(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), npc_human_conjurerAI::JustDied(), npc_orc_warlockAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), npc_water_elementalAI::JustDied(), npc_summoned_daemonAI::JustDied(), npc_human_chargerAI::JustDied(), npc_orc_wolfAI::JustDied(), npc_human_clericAI::JustDied(), npc_orc_necrolyteAI::JustDied(), boss_silver_hand_bossesAI::JustDied(), mob_fel_orc_convertAI::JustDied(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), boss_alythessAI::JustPreventedDeath(), boss_sacrolashAI::JustPreventedDeath(), boss_sathrovarrAI::JustPreventedDeath(), npc_akama_illidanAI::JustPreventedDeath(), boss_illidan_stormrageAI::JustPreventedDeath(), essence_base_AI::JustPreventedDeath(), boss_moira_bronzebeardAI::JustReachedHome(), npc_garaxxasAI::JustReachedHome(), boss_drakkari_elementalAI::JustReachedHome(), boss_festergutAI::JustReachedHome(), boss_professor_putricideAI::JustReachedHome(), boss_rotfaceAI::JustReachedHome(), boss_thaddiusAI::JustReachedHome(), boss_freyaAI::JustReachedHome(), boss_leviathan_mk2AI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), npc_graufAI::JustReachedHome(), boss_illidari_councilAI::JustReachedHome(), boss_swamplord_muselekAI::JustReachedHome(), mob_shadowmoon_channelerAI::JustReachedHome(), advisor_base_ai::JustReachedHome(), boss_kaelthasAI::JustRespawned(), boss_headless_horsemanAI::JustRespawned(), boss_felmystAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_corrupted_soul_fragmentAI::JustRespawned(), dummy_blackheart_the_inciterAI::JustRespawned(), npc_time_riftAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), boss_onyxiaAI::JustSummoned(), mob_ahnkahar_eggAI::JustSummoned(), npc_crystal_channel_targetAI::JustSummoned(), boss_festergutAI::JustSummoned(), boss_rotfaceAI::JustSummoned(), npc_rubble_stalkerAI::JustSummoned(), boss_heart_deconstructorAI::JustSummoned(), boss_attumenAI::JustSummoned(), npc_buru_eggAI::JustSummoned(), npc_grand_collectorAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_midnightAI::KilledUnit(), trial_crusader_commonAI::KilledUnit(), boss_leviathan_mk2AI::KilledUnit(), boss_vx001AI::KilledUnit(), boss_aerial_unitAI::KilledUnit(), boss_ickAI::KilledUnit(), priestess_companion_commonAI::KilledUnit(), boss_spirit_lynxAI::KilledUnit(), boss_mandokirAI::KilledUnit(), boss_vazrudenAI::MakeNazanLand(), instance_trial_of_the_champion::MoveChampionToHome(), boss_saraAI::MoveInLineOfSight(), npc_eagle_trash_aggro_triggerAI::MoveInLineOfSight(), npc_reliquary_LOS_aggro_triggerAI::MoveInLineOfSight(), boss_midnightAI::MovementInform(), npc_core_of_entropiusAI::MovementInform(), boss_zuljinAI::MovementInform(), npc_akamaAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_shade_of_akamaAI::MovementInform(), npc_living_mojoAI::MovementInform(), boss_high_inquisitor_whitemaneAI::MovementInform(), npc_champion_mountAI::MovementInform(), boss_thorimAI::MovementInform(), boss_jaraxxusAI::MovementInform(), boss_onyxiaAI::MovementInform(), npc_queen_lanathel_introAI::MovementInform(), boss_malygosAI::MovementInform(), boss_leviathan_mk2AI::MovementInform(), boss_lich_king_horAI::MovementInform(), mob_spark_of_ionarAI::MovementInform(), npc_saronite_vaporAI::MovementInform(), npc_enslaved_soulAI::npc_enslaved_soulAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), npc_shadow_constructAI::npc_shadow_constructAI(), HodirsProtectiveGaze::OnAbsorb(), instance_black_temple::OnCreatureCreate(), instance_shadowfang_keep::OnCreatureDeath(), instance_zulaman::OnCreatureDeath(), world_map_outland::OnCreatureDeath(), instance_blackrock_depths::OnCreatureDeath(), instance_blackrock_spire::OnCreatureDeath(), instance_blackwing_lair::OnCreatureDeath(), instance_scarlet_monastery::OnCreatureDeath(), instance_sunwell_plateau::OnCreatureDeath(), instance_mount_hyjal::OnCreatureDeath(), instance_ahnkahet::OnCreatureDeath(), instance_azjol_nerub::OnCreatureDeath(), instance_trial_of_the_champion::OnCreatureDeath(), instance_gundrak::OnCreatureDeath(), instance_pit_of_saron::OnCreatureDeath(), instance_icecrown_citadel::OnCreatureDeath(), instance_naxxramas::OnCreatureDeath(), instance_eye_of_eternity::OnCreatureDeath(), instance_oculus::OnCreatureDeath(), instance_ulduar::OnCreatureDeath(), instance_utgarde_keep::OnCreatureDeath(), instance_shadow_labyrinth::OnCreatureDeath(), instance_serpentshrine_cavern::OnCreatureDeath(), instance_steam_vault::OnCreatureDeath(), world_map_outland::OnCreatureDespawn(), instance_trial_of_the_champion::OnCreatureDespawn(), instance_azjol_nerub::OnCreatureEnterCombat(), instance_pit_of_saron::OnCreatureEnterCombat(), instance_karazhan::OnCreatureEvade(), instance_black_temple::OnCreatureEvade(), instance_dark_portal::OnCreatureEvade(), instance_draktharon_keep::OnCreatureEvade(), instance_blackrock_spire::OnCreatureEvade(), instance_ahnkahet::OnCreatureEvade(), instance_azjol_nerub::OnCreatureEvade(), instance_trial_of_the_crusader::OnCreatureEvade(), instance_blackrock_depths::OnCreatureRespawn(), instance_blackwing_lair::OnCreatureRespawn(), instance_shadowfang_keep::OnCreatureRespawn(), instance_zulaman::OnCreatureRespawn(), instance_ruins_of_ahnqiraj::OnCreatureRespawn(), instance_naxxramas::OnCreatureRespawn(), instance_nexus::OnCreatureRespawn(), instance_ulduar::OnCreatureRespawn(), instance_utgarde_keep::OnCreatureRespawn(), instance_the_eye::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), spell_conjure_flame_sphere::OnEffectExecute(), spell_launch_harpoon::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), instance_onyxias_lair::OnObjectCreate(), spell_crystal_spike_aura::OnPeriodicDummy(), instance_sunwell_plateau::OnPlayerEnter(), instance_mount_hyjal::OnPlayerEnter(), instance_old_hillsbrad::OnPlayerEnter(), instance_halls_of_reflection::OnPlayerEnter(), instance_naxxramas::OnPlayerEnter(), instance_ruby_sanctum::OnPlayerEnter(), instance_halls_of_stone::OnPlayerEnter(), instance_ulduar::OnPlayerEnter(), instance_pinnacle::OnPlayerEnter(), instance_mechanar::OnPlayerEnter(), instance_black_temple::OnPlayerResurrect(), instance_serpentshrine_cavern::OnPlayerResurrect(), npc_feather_vortexAI::PickNewTarget(), ProcessEventId_CharmDegrader(), ProcessEventId_CharmShivan(), ProcessEventId_event_boss_hodir(), ProcessEventId_event_spell_summon_nightbane(), ProcessEventId_WildhammerMessage(), ProcessEventIdRazorgorePossess(), ProcessEventTransports(), instance_halls_of_stone::ProcessFaceSpell(), instance_dire_maul::ProcessForceFieldOpening(), world_map_outland::ProgressShartuul(), boss_malacrassAI::ReceiveAIEvent(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_yogg_saronAI::ReceiveAIEvent(), boss_kalecgosAI::ReceiveAIEvent(), boss_razorscaleAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), mob_big_oozeAI::ReceiveAIEvent(), npc_halion_controllerAI::ReceiveAIEvent(), instance_zulgurub::RemoveHakkarPowerStack(), npc_rocknotAI::Reset(), npc_power_sparkAI::Reset(), npc_arcane_beamAI::Reset(), instance_violet_hold::ResetEvent(), instance_mount_hyjal::RetreatBase(), world_map_outland::ScriptAction(), npc_mimiron_flamesAI::SelectClosestSpreadTarget(), instance_shadowfang_keep::SetData(), instance_stratholme::SetData(), instance_zulgurub::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), world_map_outland::SetData(), instance_blackrock_depths::SetData(), instance_blackrock_spire::SetData(), instance_blackwing_lair::SetData(), instance_gnomeregan::SetData(), instance_karazhan::SetData(), instance_scarlet_monastery::SetData(), instance_sunken_temple::SetData(), instance_sunwell_plateau::SetData(), instance_zulaman::SetData(), instance_culling_of_stratholme::SetData(), instance_dark_portal::SetData(), instance_mount_hyjal::SetData(), instance_old_hillsbrad::SetData(), instance_dire_maul::SetData(), instance_ruins_of_ahnqiraj::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_wailing_caverns::SetData(), instance_ahnkahet::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_halls_of_reflection::SetData(), instance_pit_of_saron::SetData(), instance_icecrown_citadel::SetData(), instance_eye_of_eternity::SetData(), instance_nexus::SetData(), instance_ruby_sanctum::SetData(), instance_ulduar::SetData(), instance_pinnacle::SetData(), instance_violet_hold::SetData(), instance_serpentshrine_cavern::SetData(), instance_ramparts::SetData(), instance_magtheridons_lair::SetData(), instance_shattered_halls::SetData(), instance_arcatraz::SetData(), instance_the_eye::SetData(), instance_blackwing_lair::SetData64(), instance_mount_hyjal::SpawnArchimonde(), instance_mount_hyjal::SpawnBase(), world_map_outland::SpawnBoss(), instance_mount_hyjal::SpawnInvasionWave(), instance_sunwell_plateau::SpawnMuru(), instance_violet_hold::SpawnPortal(), world_map_outland::SpawnRandomBashirMob(), world_map_outland::SpawnTowerDefenders(), instance_sunwell_plateau::SpawnTwins(), instance_mount_hyjal::SpawnWave(), boss_thorimAI::SpellHit(), boss_veklorAI::SpellHit(), npc_voice_yogg_saronAI::SpellHitTarget(), npc_netherspite_portalAI::SpellHitTarget(), boss_swamplord_muselekAI::SpellHitTarget(), BrewfestEvent::StartDarkIronAttackEvent(), instance_blackrock_spire::StartflamewreathEventIfCan(), instance_dark_portal::StartPostEvent(), world_map_outland::StartTransitionPhase(), npc_thrall_old_hillsbradAI::SummonedCreatureJustDied(), npc_beast_combat_stalkerAI::SummonedCreatureJustDied(), boss_lich_king_horAI::SummonedCreatureJustDied(), mob_shadronAI::SummonedCreatureJustDied(), boss_freyaAI::SummonedCreatureJustDied(), npc_blade_of_azzinothAI::SummonedCreatureJustDied(), npc_time_riftAI::SummonedMovementInform(), trial_companion_commonAI::SummonedMovementInform(), npc_crystal_channel_targetAI::SummonedMovementInform(), npc_akamaAI::SummonedMovementInform(), npc_creature_generatorAI::SummonedMovementInform(), boss_reliquary_of_soulsAI::SummonedMovementInform(), instance_blackwing_lair::Update(), instance_deadmines::Update(), instance_karazhan::Update(), world_map_ebon_hold::Update(), instance_shadowfang_keep::Update(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_sunwell_plateau::Update(), instance_zulaman::Update(), instance_culling_of_stratholme::Update(), instance_dark_portal::Update(), instance_zulfarrak::Update(), instance_trial_of_the_champion::Update(), instance_eye_of_eternity::Update(), instance_ruby_sanctum::Update(), instance_pinnacle::Update(), instance_violet_hold::Update(), instance_sethekk_halls::Update(), instance_slave_pens::Update(), instance_blood_furnace::Update(), instance_magtheridons_lair::Update(), instance_shattered_halls::Update(), instance_arcatraz::Update(), instance_mechanar::Update(), world_map_kalimdor::Update(), instance_pit_of_saron::Update(), instance_ulduar::Update(), instance_temple_of_ahnqiraj::Update(), mob_arcane_sphereAI::UpdateAI(), go_screaming_hall_door::UpdateAI(), mob_blood_elf_council_voice_triggerAI::UpdateAI(), boss_moira_bronzebeardAI::UpdateAI(), boss_gythAI::UpdateAI(), npc_blackwing_orbAI::UpdateAI(), npc_netherspite_portalAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_romuloAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_impale_targetAI::UpdateAI(), npc_beast_combat_stalkerAI::UpdateAI(), boss_fjolaAI::UpdateAI(), blood_prince_council_baseAI::UpdateAI(), boss_festergutAI::UpdateAI(), mob_frost_bombAI::UpdateAI(), npc_tenebron_egg_controllerAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), npc_halion_controllerAI::UpdateAI(), mob_stormforged_lieutenantAI::UpdateAI(), boss_volkhanAI::UpdateAI(), npc_hodir_fury_reticleAI::UpdateAI(), boss_kologarnAI::UpdateAI(), boss_mimironAI::UpdateAI(), boss_leviathan_mk2AI::UpdateAI(), npc_bot_triggerAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_xt_002AI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), npc_brain_yogg_saronAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mob_vrykul_skeletonAI::UpdateAI(), boss_ymironAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_fathomguard_caribdisAI::UpdateAI(), boss_dalliahAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), npc_rocknotAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_reginald_windsorAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_tarethaAI::WaypointReached(), and npc_marshal_windsorAI::WaypointReached().
GetSingleGameObjectFromStorage()
GameObject * ScriptedInstance::GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog = false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Definition at line 226 of file sc_instance.cpp.
References Map::GetGameObject(), Map::GetId(), InstanceData::instance, m_goEntryGuidStore, and script_error_log().
Referenced by world_map_outland::DespawnCrystalforgeGuardians(), boss_kiljaedenAI::DoActivateDragonOrb(), instance_gundrak::DoAltarVisualEffect(), instance_zulaman::DoChestEvent(), instance_karazhan::DoFailChessEvent(), instance_karazhan::DoFinishChessEvent(), npc_rocknotAI::DoGo(), instance_karazhan::DoPrepareChessEvent(), instance_blackrock_spire::DoSendNextFlamewreathWave(), world_map_ebon_hold::DoSpawnUndeadWave(), boss_ambassador_flamelashAI::DoSummonSpirit(), DoUseOpenableObject(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), instance_icecrown_citadel::ExecuteChatCommand(), world_map_outland::ExecuteChatCommand(), instance_sunwell_plateau::FailKiljaeden(), instance_sethekk_halls::FinishAnzuIntro(), GOUse_go_activate_tram(), instance_blackrock_depths::HandleBarPatrons(), instance_trial_of_the_crusader::HandleDestroyFloor(), boss_majordomoAI::HandleOutro(), instance_naxxramas::IsInRightSideGothArea(), instance_shadowfang_keep::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), boss_malygosAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), boss_nightbaneAI::JustRespawned(), npc_blastmaster_emi_shortfuseAI::JustSummoned(), boss_majordomoAI::JustSummoned(), boss_lady_vashjAI::MovementInform(), instance_mount_hyjal::OnCreatureDeath(), instance_razorfen_downs::OnCreatureDeath(), boss_mr_smiteAI::PhaseEquipStart(), instance_dire_maul::ProcessDreadsteedRitualStart(), ProcessEventId_event_boss_hodir(), npc_halion_controllerAI::ReceiveAIEvent(), instance_zulgurub::SetData(), instance_maraudon::SetData(), world_map_kalimdor::SetData(), instance_gnomeregan::SetData(), instance_molten_core::SetData(), instance_zulaman::SetData(), instance_dire_maul::SetData(), instance_temple_of_ahnqiraj::SetData(), instance_gundrak::SetData(), instance_icecrown_citadel::SetData(), instance_eye_of_eternity::SetData(), instance_ruby_sanctum::SetData(), instance_halls_of_lightning::SetData(), instance_halls_of_stone::SetData(), instance_ulduar::SetData(), instance_sethekk_halls::SetData(), instance_serpentshrine_cavern::SetData(), instance_ramparts::SetData(), instance_magtheridons_lair::SetData(), instance_arcatraz::SetData(), instance_the_eye::SetData(), instance_mechanar::SetData(), mob_dragonflayer_forge_masterAI::SetMyForge(), instance_sethekk_halls::StartAnzuIntro(), npc_harkorAI::StartEvent(), npc_tanzarAI::StartEvent(), npc_krazAI::StartEvent(), npc_ashliAI::StartEvent(), world_map_outland::StartManaSlaveEvent(), instance_deadmines::Update(), instance_stratholme::Update(), instance_maraudon::Update(), instance_gundrak::Update(), instance_icecrown_citadel::Update(), instance_naxxramas::Update(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_krazAI::UpdateAI(), npc_warlock_mount_ritualAI::UpdateAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_shadowfang_prisonerAI::WaypointReached(), and npc_blastmaster_emi_shortfuseAI::WaypointReached().
RespawnDbGuids()
void ScriptedInstance::RespawnDbGuids (std::vector< uint32 > & spawns, uint32 respawnDelay) protected
Definition at line 206 of file sc_instance.cpp.
References Map::GetCreature(), Map::GetSpawnManager(), InstanceData::instance, and SpawnManager::RespawnCreature().
Referenced by instance_sunwell_plateau::FailKiljaeden().
Field Documentation
m_goEntryGuidCollection
EntryGuidCollection ScriptedInstance::m_goEntryGuidCollection protected
Definition at line 81 of file sc_instance.h.
Referenced by GetGameObjectGuidVectorFromStorage(), instance_ruins_of_ahnqiraj::OnObjectCreate(), world_map_outland::OnObjectCreate(), and world_map_kalimdor::OnObjectCreate().
m_goEntryGuidStore
EntryGuidMap ScriptedInstance::m_goEntryGuidStore protected
Definition at line 78 of file sc_instance.h.
Referenced by DoRespawnGameObject(), DoToggleGameObjectFlags(), DoUseDoorOrButton(), instance_serpentshrine_cavern::EngageBossConsole(), instance_serpentshrine_cavern::EngageBridgeConsole(), GetSingleGameObjectFromStorage(), instance_shadowfang_keep::OnObjectCreate(), instance_stratholme::OnObjectCreate(), instance_zulgurub::OnObjectCreate(), instance_maraudon::OnObjectCreate(), instance_black_temple::OnObjectCreate(), instance_blood_furnace::OnObjectCreate(), world_map_outland::OnObjectCreate(), instance_blackrock_depths::OnObjectCreate(), instance_blackrock_spire::OnObjectCreate(), instance_blackwing_lair::OnObjectCreate(), instance_deadmines::OnObjectCreate(), instance_gnomeregan::OnObjectCreate(), instance_karazhan::OnObjectCreate(), instance_magisters_terrace::OnObjectCreate(), instance_molten_core::OnObjectCreate(), world_map_ebon_hold::OnObjectCreate(), instance_scarlet_monastery::OnObjectCreate(), instance_scholomance::OnObjectCreate(), instance_sunken_temple::OnObjectCreate(), instance_sunwell_plateau::OnObjectCreate(), instance_uldaman::OnObjectCreate(), instance_zulaman::OnObjectCreate(), instance_blackfathom_deeps::OnObjectCreate(), instance_culling_of_stratholme::OnObjectCreate(), instance_dark_portal::OnObjectCreate(), instance_mount_hyjal::OnObjectCreate(), instance_old_hillsbrad::OnObjectCreate(), instance_dire_maul::OnObjectCreate(), instance_razorfen_downs::OnObjectCreate(), instance_razorfen_kraul::OnObjectCreate(), instance_temple_of_ahnqiraj::OnObjectCreate(), instance_wailing_caverns::OnObjectCreate(), world_map_kalimdor::OnObjectCreate(), instance_ahnkahet::OnObjectCreate(), instance_azjol_nerub::OnObjectCreate(), instance_trial_of_the_champion::OnObjectCreate(), instance_trial_of_the_crusader::OnObjectCreate(), instance_gundrak::OnObjectCreate(), instance_halls_of_reflection::OnObjectCreate(), instance_pit_of_saron::OnObjectCreate(), instance_icecrown_citadel::OnObjectCreate(), instance_naxxramas::OnObjectCreate(), instance_eye_of_eternity::OnObjectCreate(), instance_nexus::OnObjectCreate(), instance_oculus::OnObjectCreate(), instance_ruby_sanctum::OnObjectCreate(), instance_halls_of_lightning::OnObjectCreate(), instance_halls_of_stone::OnObjectCreate(), instance_ulduar::OnObjectCreate(), instance_utgarde_keep::OnObjectCreate(), instance_pinnacle::OnObjectCreate(), instance_violet_hold::OnObjectCreate(), instance_sethekk_halls::OnObjectCreate(), instance_shadow_labyrinth::OnObjectCreate(), instance_serpentshrine_cavern::OnObjectCreate(), instance_steam_vault::OnObjectCreate(), instance_gruuls_lair::OnObjectCreate(), instance_ramparts::OnObjectCreate(), instance_magtheridons_lair::OnObjectCreate(), instance_shattered_halls::OnObjectCreate(), instance_arcatraz::OnObjectCreate(), instance_the_eye::OnObjectCreate(), instance_mechanar::OnObjectCreate(), and instance_dire_maul::Update().
m_npcEntryGuidCollection
EntryGuidCollection ScriptedInstance::m_npcEntryGuidCollection protected
Definition at line 80 of file sc_instance.h.
Referenced by GetCreatureGuidVectorFromStorage(), instance_black_temple::OnCreatureCreate(), instance_underbog::OnCreatureCreate(), instance_shattered_halls::OnCreatureCreate(), world_map_outland::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), instance_ruins_of_ahnqiraj::OnCreatureCreate(), world_map_kalimdor::OnCreatureCreate(), instance_sethekk_halls::OnCreatureCreate(), instance_shadow_labyrinth::OnCreatureCreate(), instance_magtheridons_lair::OnCreatureCreate(), instance_arcatraz::OnCreatureCreate(), instance_the_eye::OnCreatureCreate(), instance_underbog::OnCreatureDeath(), and world_map_kalimdor::OnCreatureDeath().
m_npcEntryGuidStore
EntryGuidMap ScriptedInstance::m_npcEntryGuidStore protected
Definition at line 79 of file sc_instance.h.
Referenced by instance_stratholme::DoSortZiggurats(), GetSingleCreatureFromStorage(), instance_shadowfang_keep::OnCreatureCreate(), instance_stratholme::OnCreatureCreate(), instance_zulaman::OnCreatureCreate(), instance_zulgurub::OnCreatureCreate(), instance_temple_of_ahnqiraj::OnCreatureCreate(), world_map_northrend::OnCreatureCreate(), instance_black_temple::OnCreatureCreate(), instance_slave_pens::OnCreatureCreate(), instance_underbog::OnCreatureCreate(), instance_blood_furnace::OnCreatureCreate(), instance_shattered_halls::OnCreatureCreate(), world_map_outland::OnCreatureCreate(), instance_blackrock_depths::OnCreatureCreate(), instance_blackrock_spire::OnCreatureCreate(), instance_blackwing_lair::OnCreatureCreate(), instance_deadmines::OnCreatureCreate(), instance_gnomeregan::OnCreatureCreate(), instance_karazhan::OnCreatureCreate(), instance_magisters_terrace::OnCreatureCreate(), instance_molten_core::OnCreatureCreate(), world_map_ebon_hold::OnCreatureCreate(), instance_scarlet_monastery::OnCreatureCreate(), instance_scholomance::OnCreatureCreate(), instance_sunken_temple::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), instance_uldaman::OnCreatureCreate(), instance_blackfathom_deeps::OnCreatureCreate(), instance_culling_of_stratholme::OnCreatureCreate(), instance_dark_portal::OnCreatureCreate(), instance_mount_hyjal::OnCreatureCreate(), instance_old_hillsbrad::OnCreatureCreate(), instance_dire_maul::OnCreatureCreate(), instance_onyxias_lair::OnCreatureCreate(), instance_ruins_of_ahnqiraj::OnCreatureCreate(), instance_wailing_caverns::OnCreatureCreate(), world_map_kalimdor::OnCreatureCreate(), instance_zulfarrak::OnCreatureCreate(), instance_ahnkahet::OnCreatureCreate(), instance_azjol_nerub::OnCreatureCreate(), instance_trial_of_the_champion::OnCreatureCreate(), instance_trial_of_the_crusader::OnCreatureCreate(), instance_draktharon_keep::OnCreatureCreate(), instance_gundrak::OnCreatureCreate(), instance_forge_of_souls::OnCreatureCreate(), instance_halls_of_reflection::OnCreatureCreate(), instance_pit_of_saron::OnCreatureCreate(), instance_icecrown_citadel::OnCreatureCreate(), instance_naxxramas::OnCreatureCreate(), instance_eye_of_eternity::OnCreatureCreate(), instance_nexus::OnCreatureCreate(), instance_oculus::OnCreatureCreate(), instance_obsidian_sanctum::OnCreatureCreate(), instance_ruby_sanctum::OnCreatureCreate(), instance_halls_of_lightning::OnCreatureCreate(), instance_halls_of_stone::OnCreatureCreate(), instance_ulduar::OnCreatureCreate(), instance_utgarde_keep::OnCreatureCreate(), instance_pinnacle::OnCreatureCreate(), instance_violet_hold::OnCreatureCreate(), instance_sethekk_halls::OnCreatureCreate(), instance_shadow_labyrinth::OnCreatureCreate(), instance_serpentshrine_cavern::OnCreatureCreate(), instance_steam_vault::OnCreatureCreate(), instance_gruuls_lair::OnCreatureCreate(), instance_ramparts::OnCreatureCreate(), instance_magtheridons_lair::OnCreatureCreate(), instance_arcatraz::OnCreatureCreate(), instance_the_eye::OnCreatureCreate(), instance_mechanar::OnCreatureCreate(), instance_sunken_temple::SetData(), and instance_dire_maul::Update().
The documentation for this class was generated from the following files:
sc_instance.h
sc_instance.cpp