CMaNGOS_WoTLK: PlayerbotMgr Class Reference
PlayerbotMgr Class Reference
#include <PlayerbotMgr.h>
Public Member Functions
PlayerbotMgr (Player *const master)
virtual ~PlayerbotMgr ()
void RemoveBots ()
void UpdateAI (const uint32 p_time)
void HandleMasterIncomingPacket (const WorldPacket &packet)
void HandleMasterOutgoingPacket (const WorldPacket &packet)
void LoginPlayerBot (ObjectGuid guid)
void LogoutPlayerBot (ObjectGuid guid)
Player * GetPlayerBot (ObjectGuid guid) const
Player * GetMaster () const
PlayerBotMap::const_iterator GetPlayerBotsBegin () const
PlayerBotMap::const_iterator GetPlayerBotsEnd () const
void LogoutAllBots (bool fullRemove=false)
void RemoveAllBotsFromGroup ()
void OnBotLogin (Player *const bot)
void Stay ()
Static Public Member Functions
static void SetInitialWorldSettings ()
Data Fields
uint32 m_confRestrictBotLevel
uint32 m_confDisableBotsInRealm
uint32 m_confMaxNumBots
bool m_confDisableBots
bool m_confDebugWhisper
float m_confFollowDistance [2]
uint32 gConfigSellLevelDiff
bool m_confCollectCombat
bool m_confCollectQuest
bool m_confCollectProfession
bool m_confCollectLoot
bool m_confCollectSkin
bool m_confCollectObjects
uint32 m_confCollectDistance
uint32 m_confCollectDistanceMax
Private Attributes
Player *const m_master
PlayerBotMap m_playerBots
GuidSet m_botToRemove
Detailed Description
Definition at line 33 of file PlayerbotMgr.h.
Constructor & Destructor Documentation
PlayerbotMgr()
PlayerbotMgr::PlayerbotMgr (Player *const master)
Definition at line 54 of file PlayerbotMgr.cpp.
References botConfig, gConfigSellLevelDiff, Config::GetBoolDefault(), Config::GetFloatDefault(), Config::GetIntDefault(), m_confCollectCombat, m_confCollectDistance, m_confCollectDistanceMax, m_confCollectLoot, m_confCollectObjects, m_confCollectProfession, m_confCollectQuest, m_confCollectSkin, m_confDebugWhisper, m_confFollowDistance, m_confMaxNumBots, and sLog.
~PlayerbotMgr()
PlayerbotMgr::~PlayerbotMgr () virtual
Definition at line 82 of file PlayerbotMgr.cpp.
References LogoutAllBots().
Member Function Documentation
GetMaster()
Player* PlayerbotMgr::GetMaster () const inline
Definition at line 61 of file PlayerbotMgr.h.
References m_master.
Referenced by PlayerbotAI::GetMaster(), HandleMasterIncomingPacket(), and HandleMasterOutgoingPacket().
GetPlayerBot()
Player * PlayerbotMgr::GetPlayerBot (ObjectGuid guid) const
Definition at line 920 of file PlayerbotMgr.cpp.
References m_playerBots.
Referenced by HandleMasterIncomingPacket(), and RemoveBots().
GetPlayerBotsBegin()
PlayerBotMap::const_iterator PlayerbotMgr::GetPlayerBotsBegin () const inline
Definition at line 63 of file PlayerbotMgr.h.
References m_playerBots.
Referenced by HandleMasterIncomingPacket(), HandleMasterOutgoingPacket(), OnBotLogin(), RemoveAllBotsFromGroup(), and Stay().
GetPlayerBotsEnd()
PlayerBotMap::const_iterator PlayerbotMgr::GetPlayerBotsEnd () const inline
Definition at line 64 of file PlayerbotMgr.h.
References m_playerBots.
Referenced by HandleMasterIncomingPacket(), HandleMasterOutgoingPacket(), OnBotLogin(), RemoveAllBotsFromGroup(), and Stay().
HandleMasterIncomingPacket()
void PlayerbotMgr::HandleMasterIncomingPacket (const WorldPacket & packet)
Definition at line 89 of file PlayerbotMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_ROLL_GREED, ACHIEVEMENT_CRITERIA_TYPE_ROLL_NEED, Player::AddQuest(), Unit::Attack(), botConfig, Player::CanAddQuest(), Unit::CanAttack(), Player::CanTakeQuest(), Player::CanUseItem(), CharacterDatabase, MotionMaster::Clear(), CMSG_ACTIVATETAXI, CMSG_ACTIVATETAXIEXPRESS, CMSG_AREATRIGGER, CMSG_GAMEOBJ_REPORT_USE, CMSG_GAMEOBJ_USE, CMSG_GOSSIP_HELLO, CMSG_INSPECT, CMSG_LIST_INVENTORY, CMSG_LOGOUT_REQUEST, CMSG_LOOT_ROLL, CMSG_OFFER_PETITION, CMSG_QUESTGIVER_ACCEPT_QUEST, CMSG_QUESTGIVER_COMPLETE_QUEST, CMSG_QUESTGIVER_HELLO, CMSG_SPIRIT_HEALER_ACTIVATE, CMSG_TEXT_EMOTE, DEBUG_LOG, EQUIP_ERR_OK, ObjectAccessor::FindPlayer(), GAMEOBJECT_TYPE_QUESTGIVER, Player::GetAchievementMgr(), Config::GetBoolDefault(), ObjectGuid::GetCounter(), Creature::GetCreatureInfo(), Map::GetGameObject(), GameObject::GetGoType(), Player::GetGroup(), Object::GetGUIDLow(), QuestMenu::GetItem(), Loot::GetLootItemInSlot(), WorldObject::GetMap(), GetMaster(), Unit::GetMotionMaster(), WorldObject::GetName(), Player::GetNPCIfCanInteractWith(), Player::GetObjectByTypeMask(), Object::GetObjectGuid(), WorldPacket::GetOpcode(), WorldObject::GetOrientation(), GetPlayerBot(), GetPlayerBotsBegin(), GetPlayerBotsEnd(), Player::GetPlayerMenu(), PlayerMenu::GetQuestMenu(), Player::GetQuestStatus(), Player::GetSelectionGuid(), Player::GetSession(), ObjectGuid::GetString(), Object::GetUInt32Value(), ObjectAccessor::GetUnit(), Map::GetWorldObject(), GOSSIP_OPTION_AUCTIONEER, GOSSIP_OPTION_BANKER, GOSSIP_OPTION_INNKEEPER, GOSSIP_OPTION_QUESTGIVER, GOSSIP_OPTION_STABLEPET, GOSSIP_OPTION_TAXIVENDOR, GOSSIP_OPTION_VENDOR, CreatureInfo::GossipMenuId, WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), Player::HasSkill(), WorldPacket::Initialize(), INTERACTION_DISTANCE, Player::IsBeingTeleported(), WorldObject::IsInMap(), Object::IsInWorld(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), LootItem::itemId, LootItem::itemProto, LogoutAllBots(), m_master, m_playerBots, QuestMenuItem::m_qId, QuestMenu::MenuItemCount(), MotionMaster::MoveFollow(), PlayerbotAI::MOVEMENT_FOLLOW, PlayerbotAI::MOVEMENT_STAY, PETITION_SIGN_OK, Database::PExecute(), Database::PQuery(), Player::PrepareQuestMenu(), ChatHandler::PSendSysMessage(), QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_STATUS_COMPLETE, Group::RemoveMember(), Quest::ReqCreatureOrGOCount, Quest::ReqItemCount, ROLL_DISENCHANT, ROLL_GREED, ROLL_NEED, ROLL_NOT_EMITED_YET, ByteBuffer::rpos(), Player::SatisfyQuestLog(), Player::SatisfyQuestStatus(), WorldSession::SendLearnNewTaxiNode(), WorldSession::SendPacket(), SKILL_ENCHANTING, sLog, sLootMgr, SMSG_PETITION_SIGN_RESULTS, sObjectMgr, TEXTEMOTE_BOW, TEXTEMOTE_DRINK, TEXTEMOTE_EAT, TEXTEMOTE_POINT, TEXTEMOTE_STAND, TEXTEMOTE_WAVE, TYPEMASK_CREATURE_OR_GAMEOBJECT, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, and AchievementMgr::UpdateAchievementCriteria().
HandleMasterOutgoingPacket()
void PlayerbotMgr::HandleMasterOutgoingPacket (const WorldPacket & packet)
Definition at line 755 of file PlayerbotMgr.cpp.
References Unit::CastSpell(), SpellEntry::EffectApplyAuraName, SpellEntry::EffectBasePoints, Unit::GetAurasByType(), GetMaster(), WorldPacket::GetOpcode(), GetPlayerBotsBegin(), GetPlayerBotsEnd(), Player::GetSession(), Player::GetSpellMap(), WorldSession::HandleCancelMountAuraOpcode(), Unit::IsMounted(), IsPassiveSpell(), SQLStorage::LookupEntry(), MSG_MOVE_HEARTBEAT, PLAYERSPELL_REMOVED, ObjectGuid::ReadAsPacked(), SMSG_AURA_UPDATE_ALL, SMSG_COMPRESSED_UPDATE_OBJECT, SMSG_CREATURE_QUERY_RESPONSE, SMSG_DESTROY_OBJECT, SMSG_FORCE_RUN_SPEED_CHANGE, SMSG_GAMEOBJECT_QUERY_RESPONSE, SMSG_MONSTER_MOVE, SMSG_NAME_QUERY_RESPONSE, SMSG_QUERY_TIME_RESPONSE, SMSG_STANDSTATE_UPDATE, SMSG_UPDATE_OBJECT, SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED, SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED, SPELL_AURA_MOUNTED, SPELL_CAST_OK, sSpellTemplate, and TRIGGERED_NONE.
LoginPlayerBot()
void PlayerbotMgr::LoginPlayerBot (ObjectGuid guid)
LogoutAllBots()
void PlayerbotMgr::LogoutAllBots (bool fullRemove = false)
Definition at line 895 of file PlayerbotMgr.cpp.
References m_botToRemove, m_playerBots, and RemoveBots().
Referenced by HandleMasterIncomingPacket(), and ~PlayerbotMgr().
LogoutPlayerBot()
void PlayerbotMgr::LogoutPlayerBot (ObjectGuid guid)
Definition at line 914 of file PlayerbotMgr.cpp.
References m_botToRemove.
OnBotLogin()
void PlayerbotMgr::OnBotLogin (Player *const bot)
Definition at line 926 of file PlayerbotMgr.cpp.
References ByteBuffer::appendPackGUID(), Group::ChangeLeader(), CMSG_SET_ACTIVE_MOVER, Player::GetGroup(), Player::GetMover(), Object::GetObjectGuid(), GetPlayerBotsBegin(), GetPlayerBotsEnd(), Player::GetSession(), Group::IsLeader(), Group::IsMember(), m_confDebugWhisper, m_master, WorldObject::m_movementInfo, m_playerBots, MSG_MOVE_FALL_LAND, WorldSession::QueuePacket(), and Player::RemoveFromGroup().
RemoveAllBotsFromGroup()
void PlayerbotMgr::RemoveAllBotsFromGroup ()
Definition at line 968 of file PlayerbotMgr.cpp.
References Player::GetGroup(), Object::GetObjectGuid(), GetPlayerBotsBegin(), GetPlayerBotsEnd(), Player::IsInGroup(), m_master, and Group::RemoveMember().
RemoveBots()
void PlayerbotMgr::RemoveBots ()
Definition at line 878 of file PlayerbotMgr.cpp.
References GetPlayerBot(), Player::GetSession(), WorldSession::LogoutPlayer(), m_botToRemove, and m_playerBots.
Referenced by LogoutAllBots().
SetInitialWorldSettings()
void PlayerbotMgr::SetInitialWorldSettings () static
Definition at line 41 of file PlayerbotMgr.cpp.
References botConfig, Config::GetIntDefault(), Config::SetSource(), and sLog.
Referenced by World::SetInitialWorldSettings().
Stay()
void PlayerbotMgr::Stay ()
Definition at line 904 of file PlayerbotMgr.cpp.
References MotionMaster::Clear(), Unit::GetMotionMaster(), GetPlayerBotsBegin(), and GetPlayerBotsEnd().
UpdateAI()
void PlayerbotMgr::UpdateAI (const uint32 p_time)
Definition at line 87 of file PlayerbotMgr.cpp.
Field Documentation
gConfigSellLevelDiff
uint32 PlayerbotMgr::gConfigSellLevelDiff
Definition at line 79 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::_doSellItem(), PlayerbotAI::DropGarbage(), and PlayerbotMgr().
m_botToRemove
GuidSet PlayerbotMgr::m_botToRemove private
Definition at line 92 of file PlayerbotMgr.h.
Referenced by LogoutAllBots(), LogoutPlayerBot(), and RemoveBots().
m_confCollectCombat
bool PlayerbotMgr::m_confCollectCombat
Definition at line 80 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectDistance
uint32 PlayerbotMgr::m_confCollectDistance
Definition at line 86 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::findNearbyCorpse(), PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectDistanceMax
uint32 PlayerbotMgr::m_confCollectDistanceMax
Definition at line 87 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::_HandleCommandCollect(), PlayerbotAI::DoLoot(), and PlayerbotMgr().
m_confCollectLoot
bool PlayerbotMgr::m_confCollectLoot
Definition at line 83 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectObjects
bool PlayerbotMgr::m_confCollectObjects
Definition at line 85 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectProfession
bool PlayerbotMgr::m_confCollectProfession
Definition at line 82 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectQuest
bool PlayerbotMgr::m_confCollectQuest
Definition at line 81 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confCollectSkin
bool PlayerbotMgr::m_confCollectSkin
Definition at line 84 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::PlayerbotAI(), and PlayerbotMgr().
m_confDebugWhisper
bool PlayerbotMgr::m_confDebugWhisper
Definition at line 77 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::GetCombatTarget(), OnBotLogin(), PlayerbotAI::PickPocket(), PlayerbotMgr(), and PlayerbotAI::SendOrders().
m_confDisableBots
bool PlayerbotMgr::m_confDisableBots
Definition at line 76 of file PlayerbotMgr.h.
m_confDisableBotsInRealm
uint32 PlayerbotMgr::m_confDisableBotsInRealm
Definition at line 74 of file PlayerbotMgr.h.
m_confFollowDistance
float PlayerbotMgr::m_confFollowDistance[2]
Definition at line 78 of file PlayerbotMgr.h.
Referenced by PlayerbotAI::MovementReset(), and PlayerbotMgr().
m_confMaxNumBots
uint32 PlayerbotMgr::m_confMaxNumBots
Definition at line 75 of file PlayerbotMgr.h.
Referenced by PlayerbotMgr().
m_confRestrictBotLevel
uint32 PlayerbotMgr::m_confRestrictBotLevel
Definition at line 73 of file PlayerbotMgr.h.
m_master
Player* const PlayerbotMgr::m_master private
Definition at line 90 of file PlayerbotMgr.h.
Referenced by GetMaster(), HandleMasterIncomingPacket(), OnBotLogin(), and RemoveAllBotsFromGroup().
m_playerBots
PlayerBotMap PlayerbotMgr::m_playerBots private
Definition at line 91 of file PlayerbotMgr.h.
Referenced by GetPlayerBot(), GetPlayerBotsBegin(), GetPlayerBotsEnd(), HandleMasterIncomingPacket(), LogoutAllBots(), OnBotLogin(), and RemoveBots().
The documentation for this class was generated from the following files:
PlayerbotMgr.h
PlayerbotMgr.cpp