CMaNGOS_WoTLK: LFGQueue Class Reference
LFGQueue Class Reference
#include <LFGQueue.h>
Public Member Functions
void AddToQueue (LFGQueueData const &data)
void RemoveFromQueue (ObjectGuid owner)
void SetPlayerRoles (ObjectGuid group, ObjectGuid player, uint8 roles)
void UpdateProposal (ObjectGuid playerGuid, uint32 proposalId, bool accept)
void RemoveProposal (uint32 proposalId)
void OnPlayerLogout (ObjectGuid guid, ObjectGuid groupGuid)
LFGQueueData & GetQueueData (ObjectGuid owner)
void Update ()
std::string GetDebugPrintout ()
Messager< LFGQueue > & GetMessager ()
void ToggleTesting ()
bool IsTestingEnabled () const
void SetPartyMemberCountAtJoin (ObjectGuid guid, uint32 count)
uint32 GetPartyMemberCountAtJoin (ObjectGuid guid) const
void UpdateWaitTimeDps (int32 time, uint32 dungeonId)
void UpdateWaitTimeHealer (int32 time, uint32 dungeonId)
void UpdateWaitTimeTank (int32 time, uint32 dungeonId)
void UpdateWaitTimeAvg (int32 time, uint32 dungeonId)
Private Attributes
std::map< ObjectGuid, LFGQueueData > m_queueData
std::vector< LFGQueueData * > m_sortedQueue
Messager< LFGQueue > m_messager
bool m_testing = false
std::map< uint32, LfgProposal > m_proposals
std::vector< uint32 > m_proposalsForRemoval
std::map< ObjectGuid, uint32 > m_numberOfPartyMembersAtJoin
Detailed Description
Definition at line 114 of file LFGQueue.h.
Member Function Documentation
AddToQueue()
void LFGQueue::AddToQueue (LFGQueueData const & data)
Definition at line 23 of file LFGQueue.cpp.
References LFG_ROLECHECK_INITIALITING, LFGQueueData::m_leaderGuid, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, m_queueData, LFGQueueData::m_roleCheckState, and LFGQueueData::UpdateRoleCheck().
Referenced by LFGMgr::JoinLfg().
GetDebugPrintout()
std::string LFGQueue::GetDebugPrintout ()
Definition at line 171 of file LFGQueue.cpp.
GetMessager()
Messager<LFGQueue>& LFGQueue::GetMessager () inline
Definition at line 131 of file LFGQueue.h.
References m_messager.
Referenced by Update().
GetPartyMemberCountAtJoin()
uint32 LFGQueue::GetPartyMemberCountAtJoin (ObjectGuid guid) const
Definition at line 176 of file LFGQueue.cpp.
References m_numberOfPartyMembersAtJoin.
Referenced by LfgProposal::AcceptProposal().
GetQueueData()
LFGQueueData& LFGQueue::GetQueueData (ObjectGuid owner) inline
Definition at line 125 of file LFGQueue.h.
References m_queueData.
Referenced by LfgProposal::AcceptProposal(), and LfgProposal::FailProposal().
IsTestingEnabled()
bool LFGQueue::IsTestingEnabled () const inline
Definition at line 134 of file LFGQueue.h.
References m_testing.
Referenced by Update().
OnPlayerLogout()
void LFGQueue::OnPlayerLogout (ObjectGuid guid, ObjectGuid groupGuid)
Definition at line 76 of file LFGQueue.cpp.
References World::BroadcastPersonalized(), WorldSession::BuildLfgUpdate(), LFGQueueData::GetState(), ObjectGuid::IsGroup(), LFG_ROLECHECK_INITIALITING, LFG_STATE_QUEUED, LFG_UPDATETYPE_GROUP_MEMBER_OFFLINE, LFGQueueData::m_playerInfoPerGuid, m_queueData, LFGQueueData::m_roleCheckState, sWorld, and LFGQueueData::UpdateRoleCheck().
RemoveFromQueue()
void LFGQueue::RemoveFromQueue (ObjectGuid owner)
Definition at line 31 of file LFGQueue.cpp.
References m_queueData.
Referenced by LfgProposal::AcceptProposal(), and LFGMgr::JoinLfg().
RemoveProposal()
void LFGQueue::RemoveProposal (uint32 proposalId)
Definition at line 71 of file LFGQueue.cpp.
References m_proposalsForRemoval.
Referenced by LfgProposal::AcceptProposal(), and LfgProposal::FailProposal().
SetPartyMemberCountAtJoin()
void LFGQueue::SetPartyMemberCountAtJoin (ObjectGuid guid, uint32 count) inline
Definition at line 136 of file LFGQueue.h.
References m_numberOfPartyMembersAtJoin.
Referenced by LfgProposal::AcceptProposal().
SetPlayerRoles()
void LFGQueue::SetPlayerRoles (ObjectGuid group, ObjectGuid player, uint8 roles)
Definition at line 36 of file LFGQueue.cpp.
References LFG_STATE_FAILED, and m_queueData.
Referenced by WorldSession::HandleLfgSetRolesOpcode().
ToggleTesting()
void LFGQueue::ToggleTesting () inline
Definition at line 133 of file LFGQueue.h.
References m_testing.
Update()
void LFGQueue::Update ()
Definition at line 102 of file LFGQueue.cpp.
References Messager< T >::Execute(), GetMessager(), LFGQueueData::GetState(), LfgProposal::id, World::IsStopped(), IsTestingEnabled(), LFG_ROLECHECK_INITIALITING, LFG_STATE_FAILED, LFG_STATE_QUEUED, LFGQueueData::m_cancelTime, LFGQueueData::m_playerInfoPerGuid, m_proposals, m_proposalsForRemoval, m_queueData, LFGQueueData::m_roleCheckState, LFGQueueData::PopQueue(), sWorld, LfgProposal::UpdateProposal(), and LFGQueueData::UpdateRoleCheck().
Referenced by World::StartLFGQueueThread().
UpdateProposal()
void LFGQueue::UpdateProposal (ObjectGuid playerGuid, uint32 proposalId, bool accept)
Definition at line 47 of file LFGQueue.cpp.
References World::BroadcastPersonalized(), WorldSession::BuildLfgUpdateProposal(), LFGQueueData::m_playerInfoPerGuid, m_proposals, m_queueData, LFGQueueData::m_randomDungeonId, LfgProposal::queues, sWorld, and LfgProposal::UpdatePlayerProposal().
Referenced by WorldSession::HandleLfgProposalResultOpcode().
UpdateWaitTimeAvg()
void LFGQueue::UpdateWaitTimeAvg (int32 time, uint32 dungeonId)
Definition at line 200 of file LFGQueue.cpp.
Referenced by LfgProposal::AcceptProposal().
UpdateWaitTimeDps()
void LFGQueue::UpdateWaitTimeDps (int32 time, uint32 dungeonId)
Definition at line 185 of file LFGQueue.cpp.
Referenced by LfgProposal::AcceptProposal().
UpdateWaitTimeHealer()
void LFGQueue::UpdateWaitTimeHealer (int32 time, uint32 dungeonId)
Definition at line 190 of file LFGQueue.cpp.
Referenced by LfgProposal::AcceptProposal().
UpdateWaitTimeTank()
void LFGQueue::UpdateWaitTimeTank (int32 time, uint32 dungeonId)
Definition at line 195 of file LFGQueue.cpp.
Referenced by LfgProposal::AcceptProposal().
Field Documentation
m_messager
Messager<LFGQueue> LFGQueue::m_messager private
Definition at line 148 of file LFGQueue.h.
Referenced by GetMessager().
m_numberOfPartyMembersAtJoin
std::map<ObjectGuid, uint32> LFGQueue::m_numberOfPartyMembersAtJoin private
Definition at line 155 of file LFGQueue.h.
Referenced by GetPartyMemberCountAtJoin(), and SetPartyMemberCountAtJoin().
m_proposals
std::map<uint32, LfgProposal> LFGQueue::m_proposals private
Definition at line 152 of file LFGQueue.h.
Referenced by Update(), and UpdateProposal().
m_proposalsForRemoval
std::vector<uint32> LFGQueue::m_proposalsForRemoval private
Definition at line 153 of file LFGQueue.h.
Referenced by RemoveProposal(), and Update().
m_queueData
std::map<ObjectGuid, LFGQueueData> LFGQueue::m_queueData private
Definition at line 145 of file LFGQueue.h.
Referenced by AddToQueue(), GetQueueData(), OnPlayerLogout(), RemoveFromQueue(), SetPlayerRoles(), Update(), and UpdateProposal().
m_sortedQueue
std::vector<LFGQueueData*> LFGQueue::m_sortedQueue private
Definition at line 146 of file LFGQueue.h.
m_testing
bool LFGQueue::m_testing = false private
Definition at line 150 of file LFGQueue.h.
Referenced by IsTestingEnabled(), and ToggleTesting().
The documentation for this class was generated from the following files:
LFGQueue.h
LFGQueue.cpp