CMaNGOS_WoTLK: Movement::counter< T, limit > Class Template Reference
Movement::counter< T, limit > Class Template Reference
#include <typedefs.h>
Public Member Functions
counter ()
void Increase ()
T NewId ()
T getCurrent () const
Private Member Functions
void init ()
Private Attributes
T m_counter
Detailed Description
template<class T, T limit>
class Movement::counter< T, limit >
Definition at line 48 of file typedefs.h.
Constructor & Destructor Documentation
counter()
template<class T , T limit> Movement::counter< T, limit >::counter () inline
Definition at line 51 of file typedefs.h.
References Movement::counter< T, limit >::init().
Member Function Documentation
getCurrent()
template<class T , T limit> T Movement::counter< T, limit >::getCurrent () const inline
Definition at line 62 of file typedefs.h.
References Movement::counter< T, limit >::m_counter.
Increase()
template<class T , T limit> void Movement::counter< T, limit >::Increase () inline
Definition at line 53 of file typedefs.h.
References Movement::counter< T, limit >::init(), and Movement::counter< T, limit >::m_counter.
Referenced by Movement::counter< T, limit >::NewId().
init()
template<class T , T limit> void Movement::counter< T, limit >::init () inline private
Definition at line 65 of file typedefs.h.
References Movement::counter< T, limit >::m_counter.
Referenced by Movement::counter< T, limit >::counter(), and Movement::counter< T, limit >::Increase().
NewId()
template<class T , T limit> T Movement::counter< T, limit >::NewId () inline
Definition at line 61 of file typedefs.h.
References Movement::counter< T, limit >::Increase(), and Movement::counter< T, limit >::m_counter.
Field Documentation
m_counter
template<class T , T limit> T Movement::counter< T, limit >::m_counter private
Definition at line 66 of file typedefs.h.
Referenced by Movement::counter< T, limit >::getCurrent(), Movement::counter< T, limit >::Increase(), Movement::counter< T, limit >::init(), and Movement::counter< T, limit >::NewId().
The documentation for this class was generated from the following file:
typedefs.h