CMaNGOS_WoTLK: SystemMgr Class Reference
SystemMgr Class Reference
#include <system.h>
Public Types
typedef std::map< uint32, std::map< int32, PathInformation > > EntryPathInfo
Public Member Functions
SystemMgr ()
~SystemMgr ()
void LoadVersion ()
void LoadScriptTexts ()
void LoadScriptTextsCustom ()
void LoadScriptGossipTexts ()
void LoadScriptWaypoints ()
Static Public Member Functions
static SystemMgr & Instance ()
Detailed Description
Definition at line 28 of file system.h.
Member Typedef Documentation
EntryPathInfo
typedef std::map< uint32 , std::map < int32 , PathInformation > > SystemMgr::EntryPathInfo
Definition at line 36 of file system.h.
Constructor & Destructor Documentation
SystemMgr()
SystemMgr::SystemMgr ()
Definition at line 14 of file system.cpp.
~SystemMgr()
SystemMgr::~SystemMgr () inline
Definition at line 32 of file system.h.
Member Function Documentation
Instance()
SystemMgr & SystemMgr::Instance () static
Definition at line 18 of file system.cpp.
LoadScriptGossipTexts()
void SystemMgr::LoadScriptGossipTexts ()
Definition at line 58 of file system.cpp.
References LoadMangosStrings(), outstring_log(), TEXT_SOURCE_GOSSIP_END, TEXT_SOURCE_GOSSIP_START, and WorldDatabase.
LoadScriptTexts()
void SystemMgr::LoadScriptTexts ()
Definition at line 46 of file system.cpp.
References LoadMangosStrings(), outstring_log(), TEXT_SOURCE_TEXT_END, TEXT_SOURCE_TEXT_START, and WorldDatabase.
LoadScriptTextsCustom()
void SystemMgr::LoadScriptTextsCustom ()
Definition at line 52 of file system.cpp.
References LoadMangosStrings(), outstring_log(), TEXT_SOURCE_CUSTOM_END, TEXT_SOURCE_CUSTOM_START, and WorldDatabase.
LoadScriptWaypoints()
void SystemMgr::LoadScriptWaypoints ()
Definition at line 64 of file system.cpp.
References error_db_log(), GetCreatureTemplateStore(), Field::GetFloat(), Field::GetUInt32(), outstring_log(), Database::PQuery(), BarGoLink::step(), sWaypointMgr, UI64FMTD, and WorldDatabase.
LoadVersion()
void SystemMgr::LoadVersion ()
Definition at line 24 of file system.cpp.
References QueryResult::Fetch(), Field::GetCppString(), outstring_log(), Database::PQuery(), script_error_log(), strSD2Version, and WorldDatabase.
The documentation for this class was generated from the following files:
system.h
system.cpp