CMaNGOS_WoTLK: MaNGOS::BattleGround2ChatBuilder Class Reference
MaNGOS::BattleGround2ChatBuilder Class Reference
Public Member Functions
BattleGround2ChatBuilder (ChatMsg msgtype, int32 textId, Player const *source, int32 arg1, int32 arg2)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
ChatMsg i_msgtype
int32 i_textId
Player const * i_source
int32 i_arg1
int32 i_arg2
Detailed Description
Definition at line 152 of file BattleGround.cpp.
Constructor & Destructor Documentation
BattleGround2ChatBuilder()
MaNGOS::BattleGround2ChatBuilder::BattleGround2ChatBuilder (ChatMsg msgtype, int32 textId, Player const * source, int32 arg1, int32 arg2) inline
Definition at line 155 of file BattleGround.cpp.
Member Function Documentation
operator()()
void MaNGOS::BattleGround2ChatBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 157 of file BattleGround.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, WorldObject::GetName(), Object::GetObjectGuid(), i_arg1, i_arg2, i_msgtype, i_source, i_textId, LANG_UNIVERSAL, and sObjectMgr.
Field Documentation
i_arg1
int32 MaNGOS::BattleGround2ChatBuilder::i_arg1 private
Definition at line 179 of file BattleGround.cpp.
Referenced by operator()().
i_arg2
int32 MaNGOS::BattleGround2ChatBuilder::i_arg2 private
Definition at line 180 of file BattleGround.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::BattleGround2ChatBuilder::i_msgtype private
Definition at line 176 of file BattleGround.cpp.
Referenced by operator()().
i_source
Player const* MaNGOS::BattleGround2ChatBuilder::i_source private
Definition at line 178 of file BattleGround.cpp.
Referenced by operator()().
i_textId
int32 MaNGOS::BattleGround2ChatBuilder::i_textId private
Definition at line 177 of file BattleGround.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
BattleGround.cpp