CMaNGOS_WoTLK: ConditionEntry Class Reference
ConditionEntry Class Reference
#include <Conditions.h>
Public Member Functions
ConditionEntry ()
ConditionEntry (uint32 _entry, int16 _condition, uint32 _value1, uint32 _value2, uint32 _value3, uint32 _value4, uint8 _flags)
bool IsValid () const
bool Meets (WorldObject const *target, Map const *map, WorldObject const *source, ConditionSource conditionSourceType) const
Static Public Member Functions
static bool CanBeUsedWithoutPlayer (uint32 entry)
static bool CheckOp (ConditionOperation op, int32 value, int32 operand)
Private Member Functions
void DisableCondition ()
bool CheckParamRequirements (WorldObject const *target, Map const *map, WorldObject const *source) const
bool Evaluate (WorldObject const *target, Map const *map, WorldObject const *source, ConditionSource conditionSourceType) const
Private Attributes
uint32 m_entry
ConditionType m_condition
uint32 m_value1
uint32 m_value2
uint32 m_value3
uint32 m_value4
uint8 m_flags
Detailed Description
Definition at line 153 of file Conditions.h.
Constructor & Destructor Documentation
ConditionEntry() [1/2]
ConditionEntry::ConditionEntry () inline
Definition at line 157 of file Conditions.h.
ConditionEntry() [2/2]
ConditionEntry::ConditionEntry (uint32 _entry, int16 _condition, uint32 _value1, uint32 _value2, uint32 _value3, uint32 _value4, uint8 _flags) inline
Definition at line 159 of file Conditions.h.
Member Function Documentation
CanBeUsedWithoutPlayer()
bool ConditionEntry::CanBeUsedWithoutPlayer (uint32 entry) static
Definition at line 1040 of file Conditions.cpp.
References CONDITION_AND, CONDITION_NOT, CONDITION_OR, CONDITION_REQ_TARGET_PLAYER, ConditionTargets, SQLStorage::LookupEntry(), m_condition, m_value1, m_value2, and sConditionStorage.
Referenced by LootStore::LoadLootTable().
CheckOp()
bool ConditionEntry::CheckOp (ConditionOperation op, int32 value, int32 operand) static
Definition at line 131 of file Conditions.cpp.
References EQUAL_TO, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN, LESS_THAN_OR_EQUAL_TO, and NOT_EQUAL_TO.
Referenced by EvalRelOp(), Evaluate(), CombatConditionMgr::Meets(), and UnitConditionMgr::meets().
CheckParamRequirements()
bool ConditionEntry::CheckParamRequirements (WorldObject const * target, Map const * map, WorldObject const * source) const private
Definition at line 537 of file Conditions.cpp.
References CONDITION_REQ_ANY_WORLDOBJECT, CONDITION_REQ_BOTH_GAMEOBJECTS, CONDITION_REQ_BOTH_PLAYERS, CONDITION_REQ_BOTH_UNITS, CONDITION_REQ_BOTH_WORLDOBJECTS, CONDITION_REQ_MAP_OR_WORLDOBJECT, CONDITION_REQ_NONE, CONDITION_REQ_SOURCE_CREATURE, CONDITION_REQ_SOURCE_GAMEOBJECT, CONDITION_REQ_SOURCE_PLAYER, CONDITION_REQ_SOURCE_UNIT, CONDITION_REQ_SOURCE_WORLDOBJECT, CONDITION_REQ_TARGET_CREATURE, CONDITION_REQ_TARGET_GAMEOBJECT, CONDITION_REQ_TARGET_PLAYER, CONDITION_REQ_TARGET_PLAYER_OR_CORPSE, CONDITION_REQ_TARGET_UNIT, CONDITION_REQ_TARGET_UNIT_OR_CORPSE, CONDITION_REQ_TARGET_WORLDOBJECT, ConditionTargets, Object::IsCorpse(), Object::IsCreature(), Object::IsGameObject(), Object::IsPlayer(), Object::IsUnit(), and m_condition.
Referenced by Meets().
DisableCondition()
void ConditionEntry::DisableCondition () inline private
Definition at line 171 of file Conditions.h.
References CONDITION_FLAG_REVERSE_RESULT, CONDITION_NONE, m_condition, and m_flags.
Evaluate()
bool ConditionEntry::Evaluate (WorldObject const * target, Map const * map, WorldObject const * source, ConditionSource conditionSourceType) const inline private
Definition at line 147 of file Conditions.cpp.
References CheckOp(), SkillLineAbilityEntry::classmask, CONDITION_ACHIEVEMENT, CONDITION_ACHIEVEMENT_REALM, CONDITION_ACTIVE_GAME_EVENT, CONDITION_ACTIVE_HOLIDAY, CONDITION_AD_COMMISSION_AURA, CONDITION_AND, CONDITION_AREA_FLAG, CONDITION_AREAID, CONDITION_AURA, CONDITION_COMPLETED_ENCOUNTER, CONDITION_CREATURE_IN_RANGE, CONDITION_DEAD_OR_AWAY, CONDITION_FROM_REFERING_LOOT, CONDITION_GENDER, CONDITION_INSTANCE_SCRIPT, CONDITION_ITEM, CONDITION_ITEM_EQUIPPED, CONDITION_ITEM_WITH_BANK, CONDITION_LAST_WAYPOINT, CONDITION_LEARNABLE_ABILITY, CONDITION_LEVEL, CONDITION_NONE, CONDITION_NOT, CONDITION_OR, CONDITION_PVP_RANK, CONDITION_PVP_SCRIPT, CONDITION_QUEST_NONE, CONDITION_QUESTAVAILABLE, CONDITION_QUESTREWARDED, CONDITION_QUESTTAKEN, CONDITION_RACE_CLASS, CONDITION_REPUTATION_RANK_MAX, CONDITION_REPUTATION_RANK_MIN, CONDITION_SKILL, CONDITION_SKILL_BELOW, CONDITION_SPAWN_COUNT, CONDITION_SPELL, CONDITION_TEAM, CONDITION_WORLD_SCRIPT, CONDITION_WORLDSTATE, CONDITION_XP_USER, conditionSourceToStr, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_AUCTION, DungeonEncounterEntry::encounterIndex, GetAreaEntryByAreaID(), WorldObject::GetAreaId(), Player::GetBattleGround(), Unit::getClassMask(), Object::GetGuidStr(), Map::GetId(), Map::GetInstanceData(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetMapId(), Map::GetPlayers(), Player::GetQuestRewardStatus(), Unit::getRaceMask(), Player::GetRank(), ReputationMgr::GetRank(), Player::GetReputationMgr(), Player::GetSkillValue(), Player::GetSkillValueBase(), Object::GetTypeId(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), WorldObject::GetZoneAndAreaId(), WorldObject::GetZoneId(), Object::HasFlag(), Player::HasItemCount(), Player::HasSkill(), Player::HasSpell(), Player::InBattleGround(), Map::Instanceable(), Unit::IsAlive(), Player::IsCurrentQuest(), Map::IsDungeon(), Player::IsGameMaster(), Object::IsPlayer(), WorldObject::IsWithinDistInMap(), SQLStorage::LookupEntry(), m_condition, m_entry, m_value1, m_value2, m_value3, m_value4, DungeonEncounterEntry::mapId, Meets(), SkillLineAbilityEntry::min_value, GroupReference::next(), PLAYER_FLAGS, PLAYER_FLAGS_XP_USER_DISABLED, SkillLineAbilityEntry::racemask, sAchievementMgr, sAchievementStore, sConditionStorage, sDungeonEncounterStore, sFactionStore, sGameEventMgr, SkillLineAbilityEntry::skillId, sLog, sObjectMgr, sOutdoorPvPMgr, SPELL_ATTR_ALLOW_WHILE_MOUNTED, SPELL_ATTR_IS_ABILITY, sSpellMgr, sWorld, sWorldState, TYPEID_PLAYER, TYPEID_UNIT, and Cell::VisitGridObjects().
Referenced by Meets().
IsValid()
bool ConditionEntry::IsValid () const
Definition at line 621 of file Conditions.cpp.
References ALLIANCE, CLASSMASK_ALL_PLAYABLE, CONDITION_ACHIEVEMENT, CONDITION_ACHIEVEMENT_REALM, CONDITION_ACTIVE_GAME_EVENT, CONDITION_ACTIVE_HOLIDAY, CONDITION_AD_COMMISSION_AURA, CONDITION_AND, CONDITION_AREA_FLAG, CONDITION_AREAID, CONDITION_AURA, CONDITION_COMPLETED_ENCOUNTER, CONDITION_CREATURE_IN_RANGE, CONDITION_DEAD_OR_AWAY, CONDITION_GENDER, CONDITION_INSTANCE_SCRIPT, CONDITION_ITEM, CONDITION_ITEM_EQUIPPED, CONDITION_ITEM_WITH_BANK, CONDITION_LAST_WAYPOINT, CONDITION_LEARNABLE_ABILITY, CONDITION_LEVEL, CONDITION_NONE, CONDITION_NOT, CONDITION_OR, CONDITION_PVP_SCRIPT, CONDITION_QUEST_NONE, CONDITION_QUESTAVAILABLE, CONDITION_QUESTREWARDED, CONDITION_QUESTTAKEN, CONDITION_RACE_CLASS, CONDITION_REPUTATION_RANK_MAX, CONDITION_REPUTATION_RANK_MIN, CONDITION_SKILL, CONDITION_SKILL_BELOW, CONDITION_SPAWN_COUNT, CONDITION_SPELL, CONDITION_TEAM, CONDITION_WORLD_SCRIPT, CONDITION_WORLDSTATE, CONDITION_XP_USER, CONFIG_UINT32_MAX_PLAYER_LEVEL, GetAreaEntryByAreaID(), ObjectMgr::GetItemPrototype(), HORDE, SQLStorage::LookupEntry(), m_condition, m_entry, m_value1, m_value2, m_value3, m_value4, DungeonEncounterEntry::mapId, MAX, MAX_EFFECT_INDEX, MAX_GENDER, MAX_REPUTATION_RANK, MIN_REPUTATION_RANK, RACEMASK_ALL_PLAYABLE, sAchievementStore, sConditionStorage, sCreatureStorage, sDungeonEncounterStore, sFactionStore, sGameEventMgr, sLog, sObjectMgr, sSkillLineStore, sSpellMgr, sSpellTemplate, and sWorld.
Referenced by ObjectMgr::LoadConditions().
Meets()
bool ConditionEntry::Meets (WorldObject const * target, Map const * map, WorldObject const * source, ConditionSource conditionSourceType) const
Definition at line 108 of file Conditions.cpp.
References CheckParamRequirements(), CONDITION_FLAG_REVERSE_RESULT, CONDITION_FLAG_SWAP_TARGETS, conditionSourceToStr, DEBUG_LOG, Evaluate(), Object::GetGuidStr(), Map::GetId(), m_condition, m_entry, m_flags, and sLog.
Referenced by Evaluate().
Field Documentation
m_condition
ConditionType ConditionEntry::m_condition private
Definition at line 175 of file Conditions.h.
Referenced by CanBeUsedWithoutPlayer(), CheckParamRequirements(), DisableCondition(), Evaluate(), IsValid(), and Meets().
m_entry
uint32 ConditionEntry::m_entry private
Definition at line 174 of file Conditions.h.
Referenced by Evaluate(), IsValid(), and Meets().
m_flags
uint8 ConditionEntry::m_flags private
Definition at line 180 of file Conditions.h.
Referenced by DisableCondition(), and Meets().
m_value1
uint32 ConditionEntry::m_value1 private
Definition at line 176 of file Conditions.h.
Referenced by CanBeUsedWithoutPlayer(), Evaluate(), and IsValid().
m_value2
uint32 ConditionEntry::m_value2 private
Definition at line 177 of file Conditions.h.
Referenced by CanBeUsedWithoutPlayer(), Evaluate(), and IsValid().
m_value3
uint32 ConditionEntry::m_value3 private
Definition at line 178 of file Conditions.h.
Referenced by Evaluate(), and IsValid().
m_value4
uint32 ConditionEntry::m_value4 private
Definition at line 179 of file Conditions.h.
Referenced by Evaluate(), and IsValid().
The documentation for this class was generated from the following files:
Conditions.h
Conditions.cpp