CMaNGOS_WoTLK: Camera Class Reference
Camera Class Reference
Camera - object-receiver. Receives broadcast packets from nearby worldobjects, object visibility changes and sends them to client.
#include <Camera.h>
Public Member Functions
Camera (Player *pl)
~Camera ()
WorldObject * GetBody () const
Player * GetOwner () const
void SetView (WorldObject *obj, bool update_far_sight_field=true)
void ResetView (bool update_far_sight_field=true)
template<class T >
void UpdateVisibilityOf (T *target, UpdateData &data, WorldObjectSet &vis)
void UpdateVisibilityOf (WorldObject *target) const
void ReceivePacket (WorldPacket const &data) const
void UpdateVisibilityForOwner ()
void UpdateVisibilityForOwner (bool addToWorld)
GridReference< Camera > & GetGridRef ()
bool isActiveObject () const
Private Member Functions
void Event_AddedToWorld ()
void Event_RemovedFromWorld ()
void Event_Moved ()
void Event_ViewPointVisibilityChanged ()
void UpdateForCurrentViewPoint ()
Private Attributes
Player & m_owner
WorldObject * m_source
GridReference< Camera > m_gridRef
Friends
class ViewPoint
Detailed Description
Camera - object-receiver. Receives broadcast packets from nearby worldobjects, object visibility changes and sends them to client.
Definition at line 31 of file Camera.h.
Constructor & Destructor Documentation
Camera()
Camera::Camera (Player * pl) explicit
Definition at line 26 of file Camera.cpp.
References ViewPoint::Attach(), WorldObject::GetViewPoint(), and m_source.
~Camera()
Camera::~Camera ()
Definition at line 31 of file Camera.cpp.
References ViewPoint::Detach(), WorldObject::GetViewPoint(), m_owner, m_source, and MANGOS_ASSERT.
Member Function Documentation
Event_AddedToWorld()
void Camera::Event_AddedToWorld () private
Definition at line 103 of file Camera.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), WorldObject::GetViewPoint(), ViewPoint::m_grid, m_source, MANGOS_ASSERT, and UpdateVisibilityForOwner().
Referenced by ViewPoint::Event_AddedToWorld().
Event_Moved()
void Camera::Event_Moved () private
Definition at line 123 of file Camera.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), WorldObject::GetViewPoint(), ViewPoint::m_grid, m_gridRef, m_source, and Reference< TO, FROM >::unlink().
Referenced by ViewPoint::Event_GridChanged().
Event_RemovedFromWorld()
void Camera::Event_RemovedFromWorld () private
Definition at line 112 of file Camera.cpp.
References m_gridRef, m_owner, m_source, ResetView(), and Reference< TO, FROM >::unlink().
Referenced by ViewPoint::Event_RemovedFromWorld().
Event_ViewPointVisibilityChanged()
void Camera::Event_ViewPointVisibilityChanged () private
Definition at line 92 of file Camera.cpp.
References Player::HasAtClient(), m_owner, m_source, and ResetView().
Referenced by ViewPoint::Event_ViewPointVisibilityChanged().
GetBody()
WorldObject* Camera::GetBody () const inline
Definition at line 39 of file Camera.h.
References m_source.
Referenced by CinematicMgr::EndCinematic(), ChatHandler::HandleDebugIsVisibleCommand(), Player::HandleStealthedUnitsDetection(), MaNGOS::CameraDistWorker< Do >::Visit(), and MaNGOS::CameraDistLambdaWorker::Visit().
GetGridRef()
GridReference<Camera>& Camera::GetGridRef () inline
Definition at line 73 of file Camera.h.
References m_gridRef.
GetOwner()
Player* Camera::GetOwner () const inline
Definition at line 40 of file Camera.h.
References m_owner.
Referenced by MaNGOS::VisibleNotifier::Notify(), MaNGOS::CameraDistWorker< Do >::Visit(), and MaNGOS::CameraDistLambdaWorker::Visit().
isActiveObject()
bool Camera::isActiveObject () const inline
Definition at line 74 of file Camera.h.
ReceivePacket()
void Camera::ReceivePacket (WorldPacket const & data) const
Definition at line 40 of file Camera.cpp.
References m_owner, and Player::SendDirectMessage().
ResetView()
void Camera::ResetView (bool update_far_sight_field = true)
Definition at line 98 of file Camera.cpp.
References m_owner, and SetView().
Referenced by CinematicMgr::EndCinematic(), Event_RemovedFromWorld(), Event_ViewPointVisibilityChanged(), Aura::HandleBindSight(), Aura::HandleFarSight(), WorldSession::HandleFarSightOpcode(), Player::RemoveFromWorld(), VehicleInfo::RemoveSeatMods(), and Unit::Uncharm().
SetView()
void Camera::SetView (WorldObject * obj, bool update_far_sight_field = true)
Definition at line 55 of file Camera.cpp.
References Map::AddToActive(), ViewPoint::Attach(), ViewPoint::Detach(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetViewPoint(), WorldObject::isActiveObject(), WorldObject::IsInMap(), Object::isType(), m_owner, m_source, MANGOS_ASSERT, PLAYER_FARSIGHT, Map::RemoveFromActive(), Object::SetGuidValue(), sLog, TYPEMASK_DYNAMICOBJECT, TYPEMASK_UNIT, and UpdateForCurrentViewPoint().
Referenced by VehicleInfo::ApplySeatMods(), CinematicMgr::BeginCinematic(), Aura::HandleBindSight(), Aura::HandleFarSight(), WorldSession::HandleFarSightOpcode(), ChatHandler::HandleSetViewCommand(), ResetView(), and Unit::TakePossessOf().
UpdateForCurrentViewPoint()
void Camera::UpdateForCurrentViewPoint () private
Definition at line 45 of file Camera.cpp.
References WorldObject::GetViewPoint(), ViewPoint::m_grid, m_gridRef, m_source, Reference< TO, FROM >::unlink(), and UpdateVisibilityForOwner().
Referenced by SetView().
UpdateVisibilityForOwner() [1/2]
void Camera::UpdateVisibilityForOwner () inline
Definition at line 57 of file Camera.h.
References UpdateVisibilityForOwner().
Referenced by ViewPoint::Call_UpdateVisibilityForOwner(), Event_AddedToWorld(), Player::ResurrectPlayer(), WorldSession::SendSpiritResurrect(), Player::SetGameMaster(), UpdateForCurrentViewPoint(), and UpdateVisibilityForOwner().
UpdateVisibilityForOwner() [2/2]
void Camera::UpdateVisibilityForOwner (bool addToWorld)
Definition at line 146 of file Camera.cpp.
References WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), m_source, MAX_VISIBILITY_DISTANCE, MaNGOS::VisibleNotifier::Notify(), and Cell::VisitAllObjects().
UpdateVisibilityOf() [1/2]
template<class T > void Camera::UpdateVisibilityOf (T * target, UpdateData & data, WorldObjectSet & vis)
Definition at line 135 of file Camera.cpp.
References m_owner, m_source, and Player::UpdateVisibilityOf().
Referenced by MaNGOS::VisibleNotifier::Visit().
UpdateVisibilityOf() [2/2]
void Camera::UpdateVisibilityOf (WorldObject * target) const
Definition at line 129 of file Camera.cpp.
References m_owner, m_source, and Player::UpdateVisibilityOf().
Friends And Related Function Documentation
ViewPoint
friend class ViewPoint friend
Definition at line 33 of file Camera.h.
Field Documentation
m_gridRef
GridReference<Camera> Camera::m_gridRef private
Definition at line 76 of file Camera.h.
Referenced by Event_Moved(), Event_RemovedFromWorld(), GetGridRef(), and UpdateForCurrentViewPoint().
m_owner
Player& Camera::m_owner private
Definition at line 67 of file Camera.h.
Referenced by Event_RemovedFromWorld(), Event_ViewPointVisibilityChanged(), GetOwner(), ReceivePacket(), ResetView(), SetView(), UpdateVisibilityOf(), and ~Camera().
m_source
WorldObject* Camera::m_source private
Definition at line 68 of file Camera.h.
Referenced by Camera(), Event_AddedToWorld(), Event_Moved(), Event_RemovedFromWorld(), Event_ViewPointVisibilityChanged(), GetBody(), SetView(), UpdateForCurrentViewPoint(), UpdateVisibilityForOwner(), UpdateVisibilityOf(), and ~Camera().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp