CMaNGOS_WoTLK: ReputationMgr Class Reference
ReputationMgr Class Reference
#include <ReputationMgr.h>
Public Member Functions
ReputationMgr (Player *owner)
~ReputationMgr ()
void SaveToDB ()
void LoadFromDB (QueryResult *result)
uint8 GetVisibleFactionCount () const
uint8 GetHonoredFactionCount () const
uint8 GetReveredFactionCount () const
uint8 GetExaltedFactionCount () const
FactionStateList const & GetStateList () const
FactionState const * GetState (FactionEntry const *factionEntry) const
FactionState const * GetState (RepListID id) const
int32 GetReputation (uint32 faction_id) const
int32 GetReputation (FactionEntry const *factionEntry) const
int32 GetBaseReputation (FactionEntry const *factionEntry) const
bool IsAtWar (uint32 faction_id) const
bool IsAtWar (FactionEntry const *factionEntry) const
ReputationRank GetRank (FactionEntry const *factionEntry) const
ReputationRank GetBaseRank (FactionEntry const *factionEntry) const
ReputationRank const * GetForcedRankIfAny (FactionTemplateEntry const *factionTemplateEntry) const
void SetReputation (FactionEntry const *factionEntry, int32 standing)
void ModifyReputation (FactionEntry const *factionEntry, int32 standing)
void SetVisible (FactionTemplateEntry const *factionTemplateEntry)
void SetVisible (FactionEntry const *factionEntry)
void SetAtWar (RepListID repListID, bool on)
void SetInactive (RepListID repListID, bool on)
void ApplyForceReaction (uint32 faction_id, ReputationRank rank, bool apply)
void SendInitialReputations ()
void SendForceReactions ()
void SendState (FactionState const *faction, bool anyRankIncreased)
Static Public Member Functions
static ReputationRank ReputationToRank (int32 standing)
Static Public Attributes
static const int32 PointsInRank [MAX_REPUTATION_RANK] = {36000, 3000, 3000, 3000, 6000, 12000, 21000, 1000}
static const int32 Reputation_Cap = 42999
static const int32 Reputation_Bottom = -42000
Private Member Functions
void Initialize ()
uint32 GetDefaultStateFlags (const FactionEntry *factionEntry) const
void SetReputation (FactionEntry const *factionEntry, int32 standing, bool incremental)
bool SetOneFactionReputation (FactionEntry const *factionEntry, int32 standing, bool incremental)
void SetVisible (FactionState *faction)
void SetAtWar (FactionState *faction, bool atWar)
void SetInactive (FactionState *faction, bool inactive)
void SendVisible (FactionState const *faction) const
void UpdateRankCounters (ReputationRank old_rank, ReputationRank new_rank)
Private Attributes
Player * m_player
FactionStateList m_factions
ForcedReactions m_forcedReactions
uint8 m_visibleFactionCount: 8
uint8 m_honoredFactionCount: 8
uint8 m_reveredFactionCount: 8
uint8 m_exaltedFactionCount: 8
Detailed Description
Definition at line 58 of file ReputationMgr.h.
Constructor & Destructor Documentation
ReputationMgr()
ReputationMgr::ReputationMgr (Player * owner) inline explicit
Definition at line 61 of file ReputationMgr.h.
~ReputationMgr()
ReputationMgr::~ReputationMgr () inline
Definition at line 63 of file ReputationMgr.h.
Member Function Documentation
ApplyForceReaction()
void ReputationMgr::ApplyForceReaction (uint32 faction_id, ReputationRank rank, bool apply)
Definition at line 132 of file ReputationMgr.cpp.
References ByteConverter::apply(), and m_forcedReactions.
Referenced by Aura::HandleForceReaction(), and InsidiousWhisper::OnApply().
GetBaseRank()
ReputationRank ReputationMgr::GetBaseRank (FactionEntry const * factionEntry) const
Definition at line 117 of file ReputationMgr.cpp.
References GetBaseReputation(), and ReputationToRank().
Referenced by Initialize().
GetBaseReputation()
int32 ReputationMgr::GetBaseReputation (FactionEntry const * factionEntry) const
Definition at line 74 of file ReputationMgr.cpp.
References FactionEntry::BaseRepValue, Unit::getClassMask(), FactionEntry::GetIndexFitTo(), Unit::getRaceMask(), and m_player.
Referenced by Spell::EffectDummy(), GetBaseRank(), GetReputation(), LoadFromDB(), and SetOneFactionReputation().
GetDefaultStateFlags()
uint32 ReputationMgr::GetDefaultStateFlags (const FactionEntry * factionEntry) const private
Definition at line 140 of file ReputationMgr.cpp.
References Unit::getClassMask(), FactionEntry::GetIndexFitTo(), Unit::getRaceMask(), m_player, and FactionEntry::ReputationFlags.
Referenced by Initialize().
GetExaltedFactionCount()
uint8 ReputationMgr::GetExaltedFactionCount () const inline
Definition at line 77 of file ReputationMgr.h.
References m_exaltedFactionCount.
Referenced by AchievementMgr::UpdateAchievementCriteria().
GetForcedRankIfAny()
ReputationRank const * ReputationMgr::GetForcedRankIfAny (FactionTemplateEntry const * factionTemplateEntry) const
Definition at line 123 of file ReputationMgr.cpp.
References FactionTemplateEntry::faction, and m_forcedReactions.
Referenced by Unit::GetReactionTo().
GetHonoredFactionCount()
uint8 ReputationMgr::GetHonoredFactionCount () const inline
Definition at line 75 of file ReputationMgr.h.
References m_honoredFactionCount.
Referenced by AchievementMgr::UpdateAchievementCriteria().
GetRank()
ReputationRank ReputationMgr::GetRank (FactionEntry const * factionEntry) const
Definition at line 111 of file ReputationMgr.cpp.
References GetReputation(), and ReputationToRank().
Referenced by ConditionEntry::Evaluate(), GetFactionReaction(), Player::GetReputationRank(), LoadFromDB(), Player::ReputationChanged(), Player::RewardReputation(), SetReputation(), and ChatHandler::ShowFactionListHelper().
GetReputation() [1/2]
int32 ReputationMgr::GetReputation (FactionEntry const * factionEntry) const
Definition at line 63 of file ReputationMgr.cpp.
References GetBaseReputation(), and GetState().
GetReputation() [2/2]
int32 ReputationMgr::GetReputation (uint32 faction_id) const
Definition at line 50 of file ReputationMgr.cpp.
References WorldObject::GetName(), m_player, sFactionStore, and sLog.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::CalculateReputationGain(), Player::CanCompleteQuest(), GetRank(), ChatHandler::HandleModifyRepCommand(), ChatHandler::HandleQuestCompleteCommand(), Player::ReputationChanged(), ChatHandler::ShowFactionListHelper(), and AchievementMgr::UpdateAchievementCriteria().
GetReveredFactionCount()
uint8 ReputationMgr::GetReveredFactionCount () const inline
Definition at line 76 of file ReputationMgr.h.
References m_reveredFactionCount.
Referenced by AchievementMgr::UpdateAchievementCriteria().
GetState() [1/2]
FactionState const * ReputationMgr::GetState (FactionEntry const * factionEntry) const
Definition at line 39 of file ReputationMgr.cpp.
References FactionEntry::HasReputation(), and FactionEntry::reputationListID.
Referenced by GetReputation(), ChatHandler::HandleLookupFactionCommand(), and IsAtWar().
GetState() [2/2]
FactionState const * ReputationMgr::GetState (RepListID id) const
Definition at line 44 of file ReputationMgr.cpp.
References m_factions.
GetStateList()
FactionStateList const& ReputationMgr::GetStateList () const inline
Definition at line 79 of file ReputationMgr.h.
References m_factions.
Referenced by ChatHandler::HandleCharacterReputationCommand().
GetVisibleFactionCount()
uint8 ReputationMgr::GetVisibleFactionCount () const inline
Definition at line 74 of file ReputationMgr.h.
References m_visibleFactionCount.
Referenced by AchievementMgr::UpdateAchievementCriteria().
Initialize()
void ReputationMgr::Initialize () private
Definition at line 246 of file ReputationMgr.cpp.
References FACTION_FLAG_VISIBLE, FactionState::Flags, GetBaseRank(), GetDefaultStateFlags(), FactionEntry::HasReputation(), FactionState::ID, FactionEntry::ID, m_exaltedFactionCount, m_factions, m_honoredFactionCount, m_reveredFactionCount, m_visibleFactionCount, FactionState::needSave, FactionState::needSend, REP_HOSTILE, FactionState::ReputationListID, FactionEntry::reputationListID, sFactionStore, FactionState::Standing, and UpdateRankCounters().
Referenced by LoadFromDB().
IsAtWar() [1/2]
bool ReputationMgr::IsAtWar (FactionEntry const * factionEntry) const
Definition at line 100 of file ReputationMgr.cpp.
References FACTION_FLAG_AT_WAR, and GetState().
IsAtWar() [2/2]
bool ReputationMgr::IsAtWar (uint32 faction_id) const
Definition at line 87 of file ReputationMgr.cpp.
References WorldObject::GetName(), m_player, sFactionStore, and sLog.
Referenced by Unit::GetReactionTo().
LoadFromDB()
void ReputationMgr::LoadFromDB (QueryResult * result)
Definition at line 520 of file ReputationMgr.cpp.
References FACTION_FLAG_AT_WAR, FACTION_FLAG_INACTIVE, FACTION_FLAG_VISIBLE, QueryResult::Fetch(), FactionState::Flags, GetBaseReputation(), GetRank(), Field::GetUInt32(), FactionEntry::HasReputation(), FactionEntry::ID, Initialize(), m_factions, m_forcedReactions, FactionState::needSave, FactionState::needSend, QueryResult::NextRow(), REP_HOSTILE, FactionEntry::reputationListID, ReputationToRank(), SetAtWar(), SetInactive(), SetVisible(), sFactionStore, FactionState::Standing, and UpdateRankCounters().
Referenced by Player::LoadFromDB().
ModifyReputation()
void ReputationMgr::ModifyReputation (FactionEntry const * factionEntry, int32 standing) inline
Definition at line 101 of file ReputationMgr.h.
References SetReputation().
Referenced by Spell::EffectReputation(), OutdoorPvPSI::HandleAreaTrigger(), Player::RewardReputation(), and BattleGround::RewardReputationToTeam().
ReputationToRank()
ReputationRank ReputationMgr::ReputationToRank (int32 standing) static
Definition at line 27 of file ReputationMgr.cpp.
References MAX_REPUTATION_RANK, MIN_REPUTATION_RANK, PointsInRank, and Reputation_Cap.
Referenced by GetBaseRank(), GetRank(), LoadFromDB(), SetAtWar(), and SetOneFactionReputation().
SaveToDB()
void ReputationMgr::SaveToDB ()
Definition at line 588 of file ReputationMgr.cpp.
References CharacterDatabase, Database::CreateStatement(), FactionState::Flags, Object::GetGUIDLow(), FactionState::ID, m_factions, m_player, FactionState::needSave, SqlStatement::PExecute(), and FactionState::Standing.
Referenced by Player::SaveToDB().
SendForceReactions()
void ReputationMgr::SendForceReactions ()
Definition at line 153 of file ReputationMgr.cpp.
References WorldPacket::Initialize(), m_forcedReactions, m_player, Player::SendDirectMessage(), and SMSG_SET_FORCED_REACTIONS.
Referenced by Aura::HandleForceReaction(), and InsidiousWhisper::OnApply().
SendInitialReputations()
void ReputationMgr::SendInitialReputations ()
Definition at line 200 of file ReputationMgr.cpp.
References m_factions, m_player, Player::SendDirectMessage(), and SMSG_INITIALIZE_FACTIONS.
Referenced by Player::SendInitialPacketsBeforeAddToMap().
SendState()
void ReputationMgr::SendState (FactionState const * faction, bool anyRankIncreased)
Definition at line 166 of file ReputationMgr.cpp.
References m_factions, m_player, FactionState::needSend, ByteBuffer::put(), FactionState::ReputationListID, Player::SendDirectMessage(), SMSG_SET_FACTION_STANDING, FactionState::Standing, and ByteBuffer::wpos().
Referenced by SetReputation().
SendVisible()
void ReputationMgr::SendVisible (FactionState const * faction) const private
Definition at line 235 of file ReputationMgr.cpp.
References Player::GetSession(), m_player, WorldSession::PlayerLoading(), FactionState::ReputationListID, Player::SendDirectMessage(), and SMSG_SET_FACTION_VISIBLE.
Referenced by SetVisible().
SetAtWar() [1/2]
void ReputationMgr::SetAtWar (FactionState * faction, bool atWar) private
Definition at line 467 of file ReputationMgr.cpp.
References FACTION_FLAG_AT_WAR, FACTION_FLAG_PEACE_FORCED, FactionState::Flags, FactionState::needSave, FactionState::needSend, REP_HATED, ReputationToRank(), and FactionState::Standing.
SetAtWar() [2/2]
void ReputationMgr::SetAtWar (RepListID repListID, bool on)
Definition at line 454 of file ReputationMgr.cpp.
References FACTION_FLAG_HIDDEN, FACTION_FLAG_INVISIBLE_FORCED, and m_factions.
Referenced by WorldSession::HandleSetFactionAtWarOpcode(), LoadFromDB(), and SetOneFactionReputation().
SetInactive() [1/2]
void ReputationMgr::SetInactive (FactionState * faction, bool inactive) private
Definition at line 498 of file ReputationMgr.cpp.
References FACTION_FLAG_HIDDEN, FACTION_FLAG_INACTIVE, FACTION_FLAG_INVISIBLE_FORCED, FACTION_FLAG_VISIBLE, FactionState::Flags, FactionState::needSave, and FactionState::needSend.
SetInactive() [2/2]
void ReputationMgr::SetInactive (RepListID repListID, bool on)
Definition at line 489 of file ReputationMgr.cpp.
References m_factions.
Referenced by WorldSession::HandleSetFactionInactiveOpcode(), and LoadFromDB().
SetOneFactionReputation()
bool ReputationMgr::SetOneFactionReputation (FactionEntry const * factionEntry, int32 standing, bool incremental) private
Definition at line 355 of file ReputationMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_GAIN_EXALTED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_HONORED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_GAIN_REVERED_REPUTATION, ACHIEVEMENT_CRITERIA_TYPE_KNOWN_FACTIONS, Player::GetAchievementMgr(), GetBaseReputation(), FactionEntry::ID, m_factions, m_player, FactionState::needSave, FactionState::needSend, REP_HOSTILE, REP_NEUTRAL, REP_UNFRIENDLY, Reputation_Bottom, Reputation_Cap, Player::ReputationChanged(), FactionEntry::reputationListID, ReputationToRank(), SetAtWar(), SetVisible(), FactionState::Standing, AchievementMgr::UpdateAchievementCriteria(), and UpdateRankCounters().
Referenced by SetReputation().
SetReputation() [1/2]
void ReputationMgr::SetReputation (FactionEntry const * factionEntry, int32 standing) inline
Definition at line 97 of file ReputationMgr.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), Spell::EffectDummy(), ChatHandler::HandleModifyRepCommand(), ChatHandler::HandleQuestCompleteCommand(), and ModifyReputation().
SetReputation() [2/2]
void ReputationMgr::SetReputation (FactionEntry const * factionEntry, int32 standing, bool incremental) private
Definition at line 278 of file ReputationMgr.cpp.
References FACTION_FLAG_TEAM_REPUTATION, GetFactionTeamList(), GetRank(), Player::GetReputationRank(), FactionEntry::ID, m_factions, m_player, MAX_SPILLOVER_FACTIONS, FactionEntry::reputationListID, SendState(), SetOneFactionReputation(), sFactionStore, sObjectMgr, FactionEntry::spilloverRateOut, and FactionEntry::team.
SetVisible() [1/3]
void ReputationMgr::SetVisible (FactionEntry const * factionEntry)
Definition at line 420 of file ReputationMgr.cpp.
References FactionEntry::HasReputation(), m_factions, FactionEntry::reputationListID, and SetVisible().
SetVisible() [2/3]
void ReputationMgr::SetVisible (FactionState * faction) private
Definition at line 432 of file ReputationMgr.cpp.
References FACTION_FLAG_HIDDEN, FACTION_FLAG_INVISIBLE_FORCED, FACTION_FLAG_VISIBLE, FactionState::Flags, m_visibleFactionCount, FactionState::needSave, FactionState::needSend, and SendVisible().
SetVisible() [3/3]
void ReputationMgr::SetVisible (FactionTemplateEntry const * factionTemplateEntry)
Definition at line 411 of file ReputationMgr.cpp.
References FactionTemplateEntry::faction, and sFactionStore.
Referenced by Player::AddQuest(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleSetTargetOpcode(), LoadFromDB(), SetOneFactionReputation(), and SetVisible().
UpdateRankCounters()
void ReputationMgr::UpdateRankCounters (ReputationRank old_rank, ReputationRank new_rank) private
Definition at line 608 of file ReputationMgr.cpp.
References m_exaltedFactionCount, m_honoredFactionCount, m_reveredFactionCount, REP_EXALTED, REP_HONORED, and REP_REVERED.
Referenced by Initialize(), LoadFromDB(), and SetOneFactionReputation().
Field Documentation
m_exaltedFactionCount
uint8 ReputationMgr::m_exaltedFactionCount private
Definition at line 135 of file ReputationMgr.h.
Referenced by GetExaltedFactionCount(), Initialize(), and UpdateRankCounters().
m_factions
FactionStateList ReputationMgr::m_factions private
Definition at line 130 of file ReputationMgr.h.
Referenced by GetState(), GetStateList(), Initialize(), LoadFromDB(), SaveToDB(), SendInitialReputations(), SendState(), SetAtWar(), SetInactive(), SetOneFactionReputation(), SetReputation(), and SetVisible().
m_forcedReactions
ForcedReactions ReputationMgr::m_forcedReactions private
Definition at line 131 of file ReputationMgr.h.
Referenced by ApplyForceReaction(), GetForcedRankIfAny(), LoadFromDB(), and SendForceReactions().
m_honoredFactionCount
uint8 ReputationMgr::m_honoredFactionCount private
Definition at line 133 of file ReputationMgr.h.
Referenced by GetHonoredFactionCount(), Initialize(), and UpdateRankCounters().
m_player
Player* ReputationMgr::m_player private
Definition at line 129 of file ReputationMgr.h.
Referenced by GetBaseReputation(), GetDefaultStateFlags(), GetReputation(), IsAtWar(), SaveToDB(), SendForceReactions(), SendInitialReputations(), SendState(), SendVisible(), SetOneFactionReputation(), and SetReputation().
m_reveredFactionCount
uint8 ReputationMgr::m_reveredFactionCount private
Definition at line 134 of file ReputationMgr.h.
Referenced by GetReveredFactionCount(), Initialize(), and UpdateRankCounters().
m_visibleFactionCount
uint8 ReputationMgr::m_visibleFactionCount private
Definition at line 132 of file ReputationMgr.h.
Referenced by GetVisibleFactionCount(), Initialize(), and SetVisible().
PointsInRank
const int32 ReputationMgr::PointsInRank = {36000, 3000, 3000, 3000, 6000, 12000, 21000, 1000} static
Definition at line 68 of file ReputationMgr.h.
Referenced by ChatHandler::HandleModifyRepCommand(), and ReputationToRank().
Reputation_Bottom
const int32 ReputationMgr::Reputation_Bottom = -42000 static
Definition at line 70 of file ReputationMgr.h.
Referenced by SetOneFactionReputation().
Reputation_Cap
const int32 ReputationMgr::Reputation_Cap = 42999 static
Definition at line 69 of file ReputationMgr.h.
Referenced by ObjectMgr::LoadQuests(), ReputationToRank(), and SetOneFactionReputation().
The documentation for this class was generated from the following files:
ReputationMgr.h
ReputationMgr.cpp