CMaNGOS_WoTLK: MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck Class Reference
MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyUnfriendlyVisibleUnitInObjectRangeCheck (WorldObject const *obj, Unit const *funit, float range)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
Unit const * i_funit
float i_range
Detailed Description
Definition at line 1126 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyUnfriendlyVisibleUnitInObjectRangeCheck()
MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::AnyUnfriendlyVisibleUnitInObjectRangeCheck (WorldObject const * obj, Unit const * funit, float range) inline
Definition at line 1129 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::GetFocusObject () const inline
Definition at line 1131 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 1132 of file GridNotifiers.h.
References WorldObject::CanAssistSpell(), i_funit, i_obj, i_range, Unit::IsAlive(), Unit::IsVisibleForOrDetect(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_funit
Unit const* MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::i_funit private
Definition at line 1141 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::i_obj private
Definition at line 1140 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AnyUnfriendlyVisibleUnitInObjectRangeCheck::i_range private
Definition at line 1142 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h