CMaNGOS_WoTLK: WorldTimer Class Reference
WorldTimer Class Reference
#include <Timer.h>
Static Public Member Functions
static uint32 getMSTime ()
static uint32 getMSTimeDiff (const uint32 &oldMSTime, std::chrono::steady_clock::time_point newTime)
static uint32 getMSTimeDiff (const uint32 &oldMSTime, const uint32 &newMSTime)
static uint32 tickTime ()
static uint32 tickPrevTime ()
static uint32 tick ()
Static Private Attributes
static uint32 m_iTime = 0
static uint32 m_iPrevTime = 0
Detailed Description
Definition at line 34 of file Timer.h.
Member Function Documentation
getMSTime()
uint32 WorldTimer::getMSTime () static
Definition at line 60 of file Util.cpp.
References GetApplicationStartTime().
Referenced by MySQLConnection::_Query(), BattleGroundQueue::AddGroup(), NamreebAnticheat::Antispam::Analyze(), Unit::ApplyDiminishingAura(), Warden::BeginScanClock(), Warden::BeginTimeoutClock(), NamreebAnticheat::AntispamMgr::CacheSession(), NamreebAnticheat::Movement::CheckExpiredOrders(), BattleGroundQueue::CheckPremadeMatch(), NamreebAnticheat::Movement::DumpAcks(), NamreebAnticheat::Movement::DumpMovement(), NamreebAnticheat::Movement::DumpOrders(), NamreebAnticheat::Movement::DumpTimeSkips(), NamreebAnticheat::AnticheatLib::EnableExtrapolationDebug(), NamreebAnticheat::SessionAnticheat::EnterWorld(), MySQLConnection::Execute(), Unit::GetDiminishing(), NamreebAnticheat::Antispam::GetDistanceTraveled(), NamreebAnticheat::Antispam::GetInfo(), WorldSession::HandleBattlefieldStatusOpcode(), NamreebAnticheat::Movement::HandleEnterWorld(), NamreebAnticheat::Movement::HandleLeaveWorld(), ChatHandler::HandleMmapTestArea(), ChatHandler::HandleMmapTestHeight(), WorldSession::HandlePlayerLogin(), PacketLog::Initialize(), BattleGroundQueue::InviteGroupToBg(), NamreebAnticheat::Movement::KnockBack(), LoadM2Cameras(), PacketLog::LogPacket(), NamreebAnticheat::Antispam::Notify(), NamreebAnticheat::AnticheatLib::OfferExtrapolationData(), NamreebAnticheat::Movement::OrderAck(), NamreebAnticheat::Movement::OrderSent(), BattleGroundQueue::PlayerInvitedToBgUpdateAverageWaitTime(), NamreebAnticheat::Antispam::Rate(), NamreebAnticheat::Antispam::RepetitionScore(), WorldRunnable::run(), FreezeDetectorRunnable::run(), NamreebAnticheat::Movement::SendOrderInfo(), WardenWin::SendPlayerInfo(), WorldSession::SendTimeSync(), World::SetInitialWorldSettings(), tick(), NamreebAnticheat::Movement::TimeSkipped(), BattleGroundQueue::Update(), Player::Update(), Warden::Update(), WorldSession::Update(), World::Update(), and NamreebAnticheat::AntispamMgr::WorkerLoop().
getMSTimeDiff() [1/2]
static uint32 WorldTimer::getMSTimeDiff (const uint32 & oldMSTime, const uint32 & newMSTime) inline static
Definition at line 50 of file Timer.h.
getMSTimeDiff() [2/2]
static uint32 WorldTimer::getMSTimeDiff (const uint32 & oldMSTime, std::chrono::steady_clock::time_point newTime) inline static
Definition at line 41 of file Timer.h.
References GetApplicationStartTime().
Referenced by MySQLConnection::_Query(), NamreebAnticheat::Movement::DumpAcks(), NamreebAnticheat::Movement::DumpOrders(), NamreebAnticheat::Movement::DumpTimeSkips(), MySQLConnection::Execute(), NamreebAnticheat::Movement::ExtrapolateMovement(), Unit::GetDiminishing(), NamreebAnticheat::Movement::HandleAnticheatTests(), WorldSession::HandleBattlefieldStatusOpcode(), ChatHandler::HandleMmapTestArea(), ChatHandler::HandleMmapTestHeight(), WorldSession::HandleTimeSyncResp(), LoadM2Cameras(), BattleGroundQueue::PlayerInvitedToBgUpdateAverageWaitTime(), FreezeDetectorRunnable::run(), World::SetInitialWorldSettings(), tick(), WorldUpdateCounter::timeElapsed(), Player::Update(), and WorldSession::Update().
tick()
uint32 WorldTimer::tick () static
Definition at line 48 of file Util.cpp.
References getMSTime(), getMSTimeDiff(), m_iPrevTime, and m_iTime.
Referenced by WorldRunnable::run().
tickPrevTime()
uint32 WorldTimer::tickPrevTime () static
Definition at line 46 of file Util.cpp.
References m_iPrevTime.
Referenced by WorldUpdateCounter::timeElapsed().
tickTime()
uint32 WorldTimer::tickTime () static
Definition at line 45 of file Util.cpp.
References m_iTime.
Referenced by WorldUpdateCounter::Reset(), WorldRunnable::run(), and WorldUpdateCounter::timeElapsed().
Field Documentation
m_iPrevTime
uint32 WorldTimer::m_iPrevTime = 0 static private
Definition at line 74 of file Timer.h.
Referenced by tick(), and tickPrevTime().
m_iTime
uint32 WorldTimer::m_iTime = 0 static private
Definition at line 73 of file Timer.h.
Referenced by tick(), and tickTime().
The documentation for this class was generated from the following files:
Timer.h
Util.cpp