CMaNGOS_WoTLK: CryptoHash< Algorithm, DigestSize > Class Template Reference
CryptoHash< Algorithm, DigestSize > Class Template Reference
#include <CryptoHash.h>
Public Member Functions
CryptoHash ()
CryptoHash (CryptoHash const &other)
CryptoHash (CryptoHash &&other)
CryptoHash & operator= (CryptoHash other)
~CryptoHash ()
void swap (CryptoHash &other)
void UpdateBigNumbers (BigNumber *bn0,...)
int UpdateData (const uint8 *data, int len)
int UpdateData (const std::vector< uint8 > &data)
int UpdateData (const std::string &str)
int Initialize ()
int Finalize ()
uint8 * GetDigest ()
Static Public Member Functions
constexpr static size_t GetLength ()
Private Attributes
EVP_MD_CTX * m_ctx
std::array< uint8, DigestSize > m_digest
Friends
void swap (CryptoHash &left, CryptoHash &right)
Detailed Description
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize>
class CryptoHash< Algorithm, DigestSize >
Definition at line 41 of file CryptoHash.h.
Constructor & Destructor Documentation
CryptoHash() [1/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> CryptoHash< Algorithm, DigestSize >::CryptoHash () inline
Definition at line 44 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx.
CryptoHash() [2/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> CryptoHash< Algorithm, DigestSize >::CryptoHash (CryptoHash< Algorithm, DigestSize > const & other) inline
Definition at line 48 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx, and CryptoHash< Algorithm, DigestSize >::m_digest.
CryptoHash() [3/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> CryptoHash< Algorithm, DigestSize >::CryptoHash (CryptoHash< Algorithm, DigestSize > && other) inline
Definition at line 53 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::swap().
~CryptoHash()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> CryptoHash< Algorithm, DigestSize >::~CryptoHash () inline
Definition at line 62 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx.
Member Function Documentation
Finalize()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> int CryptoHash< Algorithm, DigestSize >::Finalize () inline
Definition at line 95 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx, and CryptoHash< Algorithm, DigestSize >::m_digest.
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), SRP6::CalculateSessionKey(), AccountMgr::CalculateShaPassHash(), SRP6::CalculateVerifier(), SHA1Randx::FillUp(), SRP6::Finalize(), WorldSocket::HandleAuthSession(), SRP6::HashSessionKey(), SHA1Randx::SHA1Randx(), AuthSocket::VerifyVersion(), WardenMac::WardenMac(), and WardenModule::WardenModule().
GetDigest()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> uint8* CryptoHash< Algorithm, DigestSize >::GetDigest () inline
Definition at line 97 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_digest.
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), SRP6::CalculateSessionKey(), AccountMgr::CalculateShaPassHash(), SRP6::CalculateVerifier(), SHA1Randx::FillUp(), WorldSocket::HandleAuthSession(), SRP6::HashSessionKey(), AuthSocket::SendProof(), SHA1Randx::SHA1Randx(), AuthSocket::VerifyVersion(), WardenMac::WardenMac(), and WardenModule::WardenModule().
GetLength()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> constexpr static size_t CryptoHash< Algorithm, DigestSize >::GetLength () inline static constexpr
Definition at line 98 of file CryptoHash.h.
Referenced by WardenMac::LoadScriptedScans(), AuthSocket::VerifyVersion(), WardenMac::WardenMac(), and WardenModule::WardenModule().
Initialize()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> int CryptoHash< Algorithm, DigestSize >::Initialize () inline
Definition at line 94 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx.
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), AccountMgr::CalculateShaPassHash(), SHA1Randx::FillUp(), SRP6::Finalize(), SRP6::HashSessionKey(), and SHA1Randx::SHA1Randx().
operator=()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> CryptoHash& CryptoHash< Algorithm, DigestSize >::operator= (CryptoHash< Algorithm, DigestSize > other) inline
Definition at line 57 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::swap().
swap()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> void CryptoHash< Algorithm, DigestSize >::swap (CryptoHash< Algorithm, DigestSize > & other) inline
Definition at line 67 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx, and CryptoHash< Algorithm, DigestSize >::m_digest.
Referenced by CryptoHash< Algorithm, DigestSize >::CryptoHash(), and CryptoHash< Algorithm, DigestSize >::operator=().
UpdateBigNumbers()
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> void CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers (BigNumber * bn0, ...) inline
Definition at line 77 of file CryptoHash.h.
References BigNumber::AsByteArray(), and CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), SRP6::CalculateSessionKey(), SRP6::Finalize(), and WorldSocket::HandleAuthSession().
UpdateData() [1/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> int CryptoHash< Algorithm, DigestSize >::UpdateData (const std::string & str) inline
Definition at line 92 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by CryptoHash< Algorithm, DigestSize >::UpdateData().
UpdateData() [2/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> int CryptoHash< Algorithm, DigestSize >::UpdateData (const std::vector< uint8 > & data) inline
Definition at line 91 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by CryptoHash< Algorithm, DigestSize >::UpdateData().
UpdateData() [3/3]
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> int CryptoHash< Algorithm, DigestSize >::UpdateData (const uint8 * data, int len) inline
Definition at line 90 of file CryptoHash.h.
References CryptoHash< Algorithm, DigestSize >::m_ctx.
Referenced by AuthSocket::_HandleReconnectProof(), SRP6::CalculateProof(), AccountMgr::CalculateShaPassHash(), SRP6::CalculateVerifier(), SHA1Randx::FillUp(), WorldSocket::HandleAuthSession(), SRP6::HashSessionKey(), SHA1Randx::SHA1Randx(), CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), AuthSocket::VerifyVersion(), WardenMac::WardenMac(), and WardenModule::WardenModule().
Friends And Related Function Documentation
swap
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> void swap (CryptoHash< Algorithm, DigestSize > & left, CryptoHash< Algorithm, DigestSize > & right) friend
Definition at line 72 of file CryptoHash.h.
Field Documentation
m_ctx
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> EVP_MD_CTX* CryptoHash< Algorithm, DigestSize >::m_ctx private
Definition at line 101 of file CryptoHash.h.
Referenced by CryptoHash< Algorithm, DigestSize >::CryptoHash(), CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::Initialize(), CryptoHash< Algorithm, DigestSize >::swap(), CryptoHash< Algorithm, DigestSize >::UpdateData(), and CryptoHash< Algorithm, DigestSize >::~CryptoHash().
m_digest
template<CryptoHashImpl::Algorithm Algorithm, size_t DigestSize> std::array<uint8, DigestSize> CryptoHash< Algorithm, DigestSize >::m_digest private
Definition at line 102 of file CryptoHash.h.
Referenced by CryptoHash< Algorithm, DigestSize >::CryptoHash(), CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), and CryptoHash< Algorithm, DigestSize >::swap().
The documentation for this class was generated from the following file:
CryptoHash.h