CMaNGOS_WoTLK: WorldStateVariableManager Class Reference
WorldStateVariableManager Class Reference
#include <WorldStateVariableManager.h>
Public Member Functions
WorldStateVariableManager (Map *map)
void Initialize (uint32 completedEncounterMask)
int32 GetVariable (int32 Id) const
WorldStateVariable const * GetVariableData (int32 Id) const
void SetVariable (int32 Id, int32 value)
void SetVariableData (int32 Id, bool send, uint32 zoneId, uint32 areaId)
void AddVariableExecutor (int32 Id, std::function< void()> &executor)
void FillInitialWorldStates (ByteBuffer &data, uint32 &count, uint32 zoneId, uint32 areaId)
void BroadcastVariable (int32 Id) const
std::string GetVariableList () const
void SetEncounterVariable (uint32 encounterId, bool state)
Private Attributes
std::map< int32, WorldStateVariable > m_variables
Map * m_owner
Detailed Description
Definition at line 42 of file WorldStateVariableManager.h.
Constructor & Destructor Documentation
WorldStateVariableManager()
WorldStateVariableManager::WorldStateVariableManager (Map * map)
Definition at line 26 of file WorldStateVariableManager.cpp.
Member Function Documentation
AddVariableExecutor()
void WorldStateVariableManager::AddVariableExecutor (int32 Id, std::function< void()> & executor)
Definition at line 81 of file WorldStateVariableManager.cpp.
References m_variables.
BroadcastVariable()
void WorldStateVariableManager::BroadcastVariable (int32 Id) const
Definition at line 101 of file WorldStateVariableManager.cpp.
References WorldStateVariable::areaId, Map::GetPlayers(), GetVariableData(), m_owner, MANGOS_ASSERT, WorldStateVariable::value, and WorldStateVariable::zoneId.
Referenced by SetVariable().
FillInitialWorldStates()
void WorldStateVariableManager::FillInitialWorldStates (ByteBuffer & data, uint32 & count, uint32 zoneId, uint32 areaId)
Definition at line 86 of file WorldStateVariableManager.cpp.
References m_variables.
Referenced by Player::SendInitWorldStates().
GetVariable()
int32 WorldStateVariableManager::GetVariable (int32 Id) const
Definition at line 46 of file WorldStateVariableManager.cpp.
References m_variables.
Referenced by BattleGroundWS::CheckAchievementCriteriaMeet(), BattleGroundEY::CheckVictory(), EvalSingleValue(), ConditionEntry::Evaluate(), BattleGroundWS::GetFlagState(), BattleGroundAB::GetPrematureWinner(), BattleGroundAV::GetPrematureWinner(), BattleGroundEY::GetPrematureWinner(), BattleGroundWS::GetPrematureWinner(), BattleGroundIC::GetReinforcements(), BattleGroundAB::HandlePlayerClickedOnFlag(), instance_mount_hyjal::OnCreatureCreate(), instance_mount_hyjal::OnCreatureDeath(), BattleGroundAB::ProcessNodeCapture(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), world_map_kalimdor::SetData(), instance_mount_hyjal::SpawnWave(), and BattleGroundAB::Update().
GetVariableData()
WorldStateVariable const * WorldStateVariableManager::GetVariableData (int32 Id) const
Definition at line 54 of file WorldStateVariableManager.cpp.
References m_variables.
Referenced by BroadcastVariable().
GetVariableList()
std::string WorldStateVariableManager::GetVariableList () const
Definition at line 125 of file WorldStateVariableManager.cpp.
References m_variables, WorldStateName::Name, and sObjectMgr.
Referenced by ChatHandler::HandleVariablePrint().
Initialize()
void WorldStateVariableManager::Initialize (uint32 completedEncounterMask)
Definition at line 30 of file WorldStateVariableManager.cpp.
References DungeonEncounterEntry::CompleteWorldStateID, DungeonEncounterEntry::Difficulty, DungeonEncounterEntry::encounterIndex, Map::GetDifficulty(), Map::GetId(), DungeonEncounterEntry::Id, m_owner, SetEncounterVariable(), SetVariable(), and sObjectMgr.
Referenced by Map::Initialize().
SetEncounterVariable()
void WorldStateVariableManager::SetEncounterVariable (uint32 encounterId, bool state)
Definition at line 136 of file WorldStateVariableManager.cpp.
References SetVariable().
Referenced by Initialize().
SetVariable()
void WorldStateVariableManager::SetVariable (int32 Id, int32 value)
Definition at line 62 of file WorldStateVariableManager.cpp.
References BroadcastVariable(), and m_variables.
Referenced by BattleGround::AddPlayer(), BattleGroundEY::AddPoints(), BattleGroundAV::ChangeMineOwner(), instance_mount_hyjal::DespawnWaveSpawns(), BattleGroundIC::DoCaptureObjective(), BattleGroundAB::DoUpdateNodeWorldstate(), ScriptAction::ExecuteDbscriptCommand(), instance_mount_hyjal::FailEvent(), BattleGroundIC::HandleEvent(), BattleGroundSA::HandleEvent(), BattleGround::HandleKillPlayer(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), boss_sartharionAI::HandleResetWorldstate(), instance_uldaman::Initialize(), instance_zulaman::Initialize(), world_map_outland::Initialize(), Initialize(), BattleGroundAV::InitializeNode(), instance_mount_hyjal::OnCreatureDeath(), instance_uldaman::OnCreatureGroupDespawn(), instance_blackrock_depths::OnPlayerEnter(), instance_scarlet_monastery::OnPlayerEnter(), instance_shadowfang_keep::OnPlayerEnter(), instance_slave_pens::OnPlayerEnter(), BattleGroundEY::ProcessCaptureEvent(), BattleGroundWS::ProcessDroppedFlagActions(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAB::ProcessNodeCapture(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGround::RemovePlayer(), BattleGround::Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundWS::Reset(), BattleGroundWS::RespawnFlagAtBase(), instance_mount_hyjal::RetreatBase(), boss_sartharionAI::SendFlameTsunami(), world_map_outland::SetData(), world_map_kalimdor::SetData(), instance_zulaman::SetData(), instance_mount_hyjal::SetData(), BattleGroundSA::SetDefender(), SetEncounterVariable(), BattleGroundEY::SetFlagState(), BattleGroundIC::SetReinforcements(), BattleGroundEY::SetTowerOwner(), BattleGroundSA::SetupBattleground(), instance_zulaman::SpawnMalacrass(), instance_mount_hyjal::SpawnWave(), BattleGroundAV::StartingEventOpenDoors(), BattleGroundSA::StartingEventOpenDoors(), BattleGroundAB::Update(), BattleGroundSA::Update(), BattleGroundWS::Update(), BattleGroundAV::UpdateNodeWorldState(), BattleGroundAV::UpdateScore(), and BattleGroundSA::UpdateTimerWorldState().
SetVariableData()
void WorldStateVariableManager::SetVariableData (int32 Id, bool send, uint32 zoneId, uint32 areaId)
Definition at line 73 of file WorldStateVariableManager.cpp.
References m_variables.
Referenced by instance_zulaman::Initialize(), instance_mount_hyjal::Initialize(), world_map_kalimdor::Initialize(), world_map_outland::Initialize(), BattleGround::Reset(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), BattleGroundIC::Reset(), BattleGroundSA::Reset(), and BattleGroundWS::Reset().
Field Documentation
m_owner
Map* WorldStateVariableManager::m_owner private
Definition at line 64 of file WorldStateVariableManager.h.
Referenced by BroadcastVariable(), and Initialize().
m_variables
std::map<int32, WorldStateVariable> WorldStateVariableManager::m_variables private
Definition at line 63 of file WorldStateVariableManager.h.
Referenced by AddVariableExecutor(), FillInitialWorldStates(), GetVariable(), GetVariableData(), GetVariableList(), SetVariable(), and SetVariableData().
The documentation for this class was generated from the following files:
WorldStateVariableManager.h
WorldStateVariableManager.cpp