CMaNGOS_WoTLK: WardenMac Class Reference
WardenMac Class Reference final
#include <WardenMac.hpp>
Public Member Functions
WardenMac (WorldSession *session, const BigNumber &K, SessionAnticheatInterface *anticheat)
void Update (uint32 diff)
virtual void SetCharEnumPacket (WorldPacket &&packet)
virtual void SendPlayerInfo (ChatHandler *, bool) const
Public Member Functions inherited from Warden
virtual ~Warden ()=default
void HandlePacket (WorldPacket &recvData)
const WardenModule * GetModule () const
uint8 GetXor () const
Static Public Member Functions
static void LoadScriptedScans ()
Static Public Member Functions inherited from Warden
static void LoadScriptedScans ()
Private Member Functions
virtual uint32 GetScanFlags () const
virtual void InitializeClient ()
Private Attributes
bool _fingerprintSaved
std::string _hashString
uint8 _hashSHA [SHA_DIGEST_LENGTH]
uint8 _hashMD5 [MD5_DIGEST_LENGTH]
WorldPacket _charEnum
Additional Inherited Members
Static Public Attributes inherited from Warden
static constexpr size_t MaxRequest = 256
static constexpr size_t MaxReply = 256
Protected Member Functions inherited from Warden
Warden (WorldSession *session, const WardenModule *module, const BigNumber &K, SessionAnticheatInterface *anticheat)
std::vector< std::shared_ptr< const Scan > > SelectScans (ScanFlags flags) const
void BeginScanClock ()
void EnqueueScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void RequestScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void SendPacket (const ByteBuffer &buff)
Static Protected Member Functions inherited from Warden
static uint32 BuildChecksum (const uint8 *data, size_t size)
Protected Attributes inherited from Warden
NamreebAnticheat::SessionAnticheat *const _anticheat
WorldSession *const _session
const WardenModule *const _module
uint8 _xor
bool _initialized
std::vector< std::shared_ptr< const Scan > > _pendingScans
std::vector< std::shared_ptr< const Scan > > _enqueuedScans
Static Protected Attributes inherited from Warden
static constexpr size_t KeyLength = 16
Detailed Description
Definition at line 23 of file WardenMac.hpp.
Constructor & Destructor Documentation
WardenMac()
WardenMac::WardenMac (WorldSession * session, const BigNumber & K, SessionAnticheatInterface * anticheat)
Definition at line 53 of file wardenmac.cpp.
References _hashMD5, _hashSHA, _hashString, Warden::_module, Warden::_session, Warden::BeginScanClock(), CryptoHash< Algorithm, DigestSize >::Finalize(), WorldSession::GetAccountName(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< Algorithm, DigestSize >::GetLength(), InitializeClient(), InitialLogin, Warden::RequestScans(), Warden::SelectScans(), and CryptoHash< Algorithm, DigestSize >::UpdateData().
Member Function Documentation
GetScanFlags()
uint32 WardenMac::GetScanFlags () const private virtual
Implements Warden.
Definition at line 139 of file wardenmac.cpp.
References Warden::_session, AdvancedScan, WorldSession::GetAccountMaxLevel(), MacAllBuild, and sAnticheatConfig.
InitializeClient()
void WardenMac::InitializeClient () private virtual
Implements Warden.
Definition at line 149 of file wardenmac.cpp.
References Warden::_initialized.
Referenced by WardenMac().
LoadScriptedScans()
void WardenMac::LoadScriptedScans () static
Definition at line 23 of file wardenmac.cpp.
References ByteBuffer::append(), CryptoHash< Algorithm, DigestSize >::GetLength(), CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength(), MANGOS_ASSERT, and sWardenScanMgr.
Referenced by Warden::LoadScriptedScans().
SendPlayerInfo()
virtual void WardenMac::SendPlayerInfo (ChatHandler * , bool) const inline virtual
Implements Warden.
Definition at line 48 of file WardenMac.hpp.
SetCharEnumPacket()
void WardenMac::SetCharEnumPacket (WorldPacket && packet) virtual
Implements Warden.
Definition at line 130 of file wardenmac.cpp.
References _charEnum, Warden::_initialized, Warden::_session, and WorldSession::SendPacket().
Update()
void WardenMac::Update (uint32 diff) virtual
Reimplemented from Warden.
Definition at line 94 of file wardenmac.cpp.
References _charEnum, _fingerprintSaved, Warden::_initialized, Warden::_session, ByteBuffer::clear(), ByteBuffer::empty(), WorldSession::SendPacket(), and Warden::Update().
Field Documentation
_charEnum
WorldPacket WardenMac::_charEnum private
Definition at line 32 of file WardenMac.hpp.
Referenced by SetCharEnumPacket(), and Update().
_fingerprintSaved
bool WardenMac::_fingerprintSaved private
Definition at line 26 of file WardenMac.hpp.
Referenced by Update().
_hashMD5
uint8 WardenMac::_hashMD5[MD5_DIGEST_LENGTH] private
Definition at line 30 of file WardenMac.hpp.
Referenced by WardenMac().
_hashSHA
uint8 WardenMac::_hashSHA[SHA_DIGEST_LENGTH] private
Definition at line 29 of file WardenMac.hpp.
Referenced by WardenMac().
_hashString
std::string WardenMac::_hashString private
Definition at line 28 of file WardenMac.hpp.
Referenced by WardenMac().
The documentation for this class was generated from the following files:
WardenMac.hpp
wardenmac.cpp