CMaNGOS_WoTLK: MapPersistentStateManager Class Reference
MapPersistentStateManager Class Reference
#include <MapPersistentStateMgr.h>
Public Member Functions
MapPersistentStateManager ()
~MapPersistentStateManager ()
void InitWorldMaps ()
void LoadCreatureRespawnTimes ()
void LoadGameobjectRespawnTimes ()
MapPersistentState * AddPersistentState (MapEntry const *mapEntry, uint32 instanceId, Difficulty difficulty, time_t resetTime, bool canReset, bool load=false, uint32 completedEncountersMask=0)
MapPersistentState * GetPersistentState (uint32 mapId, uint32 instanceId)
void RemovePersistentState (uint32 mapId, uint32 instanceId)
template<typename Do >
void DoForAllStatesWithMapId (uint32 mapId, Do &_do)
void CleanupInstances ()
void PackInstances () const
DungeonResetScheduler & GetScheduler ()
void GetStatistics (uint32 &numStates, uint32 &numBoundPlayers, uint32 &numBoundGroups)
void Update ()
time_t GetSubsequentResetTime (uint32 mapid, Difficulty difficulty, time_t resetTime) const
Static Public Member Functions
static void DeleteInstanceFromDB (uint32 instanceid)
Static Public Member Functions inherited from MaNGOS::Singleton< MapPersistentStateManager, MaNGOS::ClassLevelLockable< MapPersistentStateManager, std::mutex > >
static MapPersistentStateManager & Instance ()
Private Types
typedef std::unordered_map< uint32, MapPersistentState * > PersistentStateMap
Private Member Functions
void _ResetOrWarnAll (uint32 mapid, Difficulty difficulty, bool warn, uint32 timeLeft)
void _ResetInstance (uint32 mapid, uint32 instanceId)
void _CleanupExpiredInstancesAtTime (time_t t)
void _ResetSave (PersistentStateMap &holder, PersistentStateMap::iterator &itr)
void _DelHelper (DatabaseType &db, const char *fields, const char *table, const char *queryTail,...) const
Private Attributes
bool lock_instLists
PersistentStateMap m_instanceSaveByInstanceId
PersistentStateMap m_instanceSaveByMapId
DungeonResetScheduler m_Scheduler
Friends
class DungeonResetScheduler
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Singleton< MapPersistentStateManager, MaNGOS::ClassLevelLockable< MapPersistentStateManager, std::mutex > >
Singleton ()
Detailed Description
Definition at line 336 of file MapPersistentStateMgr.h.
Member Typedef Documentation
PersistentStateMap
typedef std::unordered_map<uint32 , MapPersistentState*> MapPersistentStateManager::PersistentStateMap private
Definition at line 376 of file MapPersistentStateMgr.h.
Constructor & Destructor Documentation
MapPersistentStateManager()
MapPersistentStateManager::MapPersistentStateManager ()
Definition at line 656 of file MapPersistentStateMgr.cpp.
~MapPersistentStateManager()
MapPersistentStateManager::~MapPersistentStateManager ()
Definition at line 660 of file MapPersistentStateMgr.cpp.
References lock_instLists, m_instanceSaveByInstanceId, and m_instanceSaveByMapId.
Member Function Documentation
_CleanupExpiredInstancesAtTime()
void MapPersistentStateManager::_CleanupExpiredInstancesAtTime (time_t t) private
Definition at line 1058 of file MapPersistentStateMgr.cpp.
References _DelHelper(), CharacterDatabase, and UI64FMTD.
Referenced by DungeonResetScheduler::LoadResetTimes().
_DelHelper()
void MapPersistentStateManager::_DelHelper (DatabaseType & db, const char * fields, const char * table, const char * queryTail, ...) const private
Definition at line 773 of file MapPersistentStateMgr.cpp.
References Database::escape_string(), QueryResult::Fetch(), Field::GetCppString(), MANGOS_ASSERT, MAX_QUERY_LEN, QueryResult::NextRow(), Database::PExecute(), Database::PQuery(), and StrSplit().
Referenced by _CleanupExpiredInstancesAtTime(), and CleanupInstances().
_ResetInstance()
void MapPersistentStateManager::_ResetInstance (uint32 mapid, uint32 instanceId) private
Definition at line 939 of file MapPersistentStateMgr.cpp.
References _ResetSave(), DEBUG_LOG, DeleteInstanceFromDB(), INSTANCE_RESET_RESPAWN_DELAY, m_instanceSaveByInstanceId, and MANGOS_ASSERT.
Referenced by DungeonResetScheduler::Update().
_ResetOrWarnAll()
void MapPersistentStateManager::_ResetOrWarnAll (uint32 mapid, Difficulty difficulty, bool warn, uint32 timeLeft) private
Definition at line 984 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), DungeonResetScheduler::CalculateNextResetTime(), CharacterDatabase, Database::CommitTransaction(), GetMapDifficultyData(), MapEntry::IsDungeon(), m_instanceSaveByInstanceId, Database::PExecute(), MapDifficultyEntry::resetTime, sLog, sMapMgr, sMapStore, and UI64FMTD.
Referenced by DungeonResetScheduler::Update().
_ResetSave()
void MapPersistentStateManager::_ResetSave (PersistentStateMap & holder, PersistentStateMap::iterator & itr) private
Definition at line 888 of file MapPersistentStateMgr.cpp.
References EXTEND_STATE_EXPIRED, EXTEND_STATE_EXTENDED, EXTEND_STATE_NORMAL, DungeonPersistentState::GetGroupList(), DungeonPersistentState::GetPlayerList(), lock_instLists, MANGOS_ASSERT, and Group::UnbindInstance().
Referenced by _ResetInstance(), and RemovePersistentState().
AddPersistentState()
MapPersistentState * MapPersistentStateManager::AddPersistentState (MapEntry const * mapEntry, uint32 instanceId, Difficulty difficulty, time_t resetTime, bool canReset, bool load = false, uint32 completedEncountersMask = 0)
Definition at line 675 of file MapPersistentStateMgr.cpp.
References DEBUG_LOG, DUNGEON_DIFFICULTY_NORMAL, GetPersistentState(), DungeonResetScheduler::GetResetTimeFor(), MapPersistentState::GetSaveDifficulty(), MapEntry::IsBattleGroundOrArena(), MapEntry::IsDungeon(), m_instanceSaveByInstanceId, m_instanceSaveByMapId, m_Scheduler, MAP_RAID, MapEntry::map_type, MapEntry::MapID, NORMAL_INSTANCE_RESET_TIME, RESET_EVENT_NORMAL_DUNGEON, DungeonPersistentState::SaveToDB(), DungeonResetScheduler::ScheduleReset(), and UI64FMTD.
Referenced by InitWorldMaps(), LoadCreatureRespawnTimes(), and LoadGameobjectRespawnTimes().
CleanupInstances()
void MapPersistentStateManager::CleanupInstances ()
Definition at line 804 of file MapPersistentStateMgr.cpp.
References _DelHelper(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Database::Execute(), DungeonResetScheduler::LoadResetTimes(), m_Scheduler, sLog, and BarGoLink::step().
DeleteInstanceFromDB()
void MapPersistentStateManager::DeleteInstanceFromDB (uint32 instanceid) static
Definition at line 733 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), and Database::PExecute().
Referenced by _ResetInstance(), and DungeonPersistentState::DeleteFromDB().
DoForAllStatesWithMapId()
template<typename Do > void MapPersistentStateManager::DoForAllStatesWithMapId (uint32 mapId, Do & _do) inline
Definition at line 397 of file MapPersistentStateMgr.h.
References GetPersistentState(), MapEntry::Instanceable(), m_instanceSaveByInstanceId, and sMapStore.
GetPersistentState()
MapPersistentState * MapPersistentStateManager::GetPersistentState (uint32 mapId, uint32 instanceId)
Definition at line 722 of file MapPersistentStateMgr.cpp.
References m_instanceSaveByInstanceId, and m_instanceSaveByMapId.
Referenced by AddPersistentState(), and DoForAllStatesWithMapId().
GetScheduler()
DungeonResetScheduler& MapPersistentStateManager::GetScheduler () inline
Definition at line 366 of file MapPersistentStateMgr.h.
References m_Scheduler.
GetStatistics()
void MapPersistentStateManager::GetStatistics (uint32 & numStates, uint32 & numBoundPlayers, uint32 & numBoundGroups)
Definition at line 1040 of file MapPersistentStateMgr.cpp.
References m_instanceSaveByInstanceId.
GetSubsequentResetTime()
time_t MapPersistentStateManager::GetSubsequentResetTime (uint32 mapid, Difficulty difficulty, time_t resetTime) const
Definition at line 1215 of file MapPersistentStateMgr.cpp.
References CONFIG_FLOAT_RATE_INSTANCE_RESET_TIME, CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR, DAY, GetLocalHourTimestamp(), GetMapDifficultyData(), MINUTE, MapDifficultyEntry::resetTime, sLog, and sWorld.
InitWorldMaps()
void MapPersistentStateManager::InitWorldMaps ()
Definition at line 1063 of file MapPersistentStateMgr.cpp.
References AddPersistentState(), REGULAR_DIFFICULTY, and sMapStore.
LoadCreatureRespawnTimes()
void MapPersistentStateManager::LoadCreatureRespawnTimes ()
Definition at line 1072 of file MapPersistentStateMgr.cpp.
References AddPersistentState(), CharacterDatabase, Database::DirectExecute(), QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt64(), Field::GetUInt8(), MapEntry::Instanceable(), MapEntry::IsDungeon(), MapEntry::IsRaid(), CreatureData::mapid, MAX_DUNGEON_DIFFICULTY, MAX_RAID_DIFFICULTY, QueryResult::NextRow(), Database::Query(), REGULAR_DIFFICULTY, MapPersistentState::SetCreatureRespawnTime(), sLog, sMapStore, sObjectMgr, and BarGoLink::step().
LoadGameobjectRespawnTimes()
void MapPersistentStateManager::LoadGameobjectRespawnTimes ()
Definition at line 1143 of file MapPersistentStateMgr.cpp.
References AddPersistentState(), CharacterDatabase, Database::DirectExecute(), QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt64(), Field::GetUInt8(), MapEntry::Instanceable(), MapEntry::IsDungeon(), MapEntry::IsRaid(), GameObjectData::mapid, MAX_DUNGEON_DIFFICULTY, MAX_RAID_DIFFICULTY, QueryResult::NextRow(), Database::Query(), REGULAR_DIFFICULTY, MapPersistentState::SetGORespawnTime(), sLog, sMapStore, sObjectMgr, and BarGoLink::step().
PackInstances()
void MapPersistentStateManager::PackInstances () const
Definition at line 836 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), QueryResult::Fetch(), QueryResult::NextRow(), Database::PExecute(), Database::Query(), sLog, and BarGoLink::step().
RemovePersistentState()
void MapPersistentStateManager::RemovePersistentState (uint32 mapId, uint32 instanceId)
Definition at line 747 of file MapPersistentStateMgr.cpp.
References _ResetSave(), CharacterDatabase, lock_instLists, m_instanceSaveByInstanceId, m_instanceSaveByMapId, Database::PExecute(), and UI64FMTD.
Update()
void MapPersistentStateManager::Update () inline
Definition at line 372 of file MapPersistentStateMgr.h.
References m_Scheduler, and DungeonResetScheduler::Update().
Friends And Related Function Documentation
DungeonResetScheduler
friend class DungeonResetScheduler friend
Definition at line 338 of file MapPersistentStateMgr.h.
Field Documentation
lock_instLists
bool MapPersistentStateManager::lock_instLists private
Definition at line 387 of file MapPersistentStateMgr.h.
Referenced by _ResetSave(), RemovePersistentState(), and ~MapPersistentStateManager().
m_instanceSaveByInstanceId
PersistentStateMap MapPersistentStateManager::m_instanceSaveByInstanceId private
Definition at line 389 of file MapPersistentStateMgr.h.
Referenced by _ResetInstance(), _ResetOrWarnAll(), AddPersistentState(), DoForAllStatesWithMapId(), GetPersistentState(), GetStatistics(), RemovePersistentState(), and ~MapPersistentStateManager().
m_instanceSaveByMapId
PersistentStateMap MapPersistentStateManager::m_instanceSaveByMapId private
Definition at line 391 of file MapPersistentStateMgr.h.
Referenced by AddPersistentState(), GetPersistentState(), RemovePersistentState(), and ~MapPersistentStateManager().
m_Scheduler
DungeonResetScheduler MapPersistentStateManager::m_Scheduler private
Definition at line 393 of file MapPersistentStateMgr.h.
Referenced by AddPersistentState(), CleanupInstances(), GetScheduler(), and Update().
The documentation for this class was generated from the following files:
MapPersistentStateMgr.h
MapPersistentStateMgr.cpp