CMaNGOS_WoTLK: SHA1Randx Class Reference
SHA1Randx Class Reference
#include <WardenKeyGeneration.h>
Public Member Functions
SHA1Randx (const uint8 *buff, size_t size)
void Generate (uint8 *buf, size_t sz)
Private Member Functions
void FillUp ()
Private Attributes
Sha1Hash sh
size_t taken
uint8 o0 [20]
uint8 o1 [20]
uint8 o2 [20]
Detailed Description
Definition at line 14 of file WardenKeyGeneration.h.
Constructor & Destructor Documentation
SHA1Randx()
SHA1Randx::SHA1Randx (const uint8 * buff, size_t size) inline
Definition at line 17 of file WardenKeyGeneration.h.
References FillUp(), CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< Algorithm, DigestSize >::Initialize(), o0, o1, o2, sh, taken, and CryptoHash< Algorithm, DigestSize >::UpdateData().
Member Function Documentation
FillUp()
void SHA1Randx::FillUp () inline private
Definition at line 51 of file WardenKeyGeneration.h.
References CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< Algorithm, DigestSize >::Initialize(), o0, o1, o2, sh, taken, and CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by Generate(), and SHA1Randx().
Generate()
void SHA1Randx::Generate (uint8 * buf, size_t sz) inline
Definition at line 38 of file WardenKeyGeneration.h.
References FillUp(), o0, and taken.
Referenced by Warden::Warden().
Field Documentation
o0
uint8 SHA1Randx::o0[20] private
Definition at line 66 of file WardenKeyGeneration.h.
Referenced by FillUp(), Generate(), and SHA1Randx().
o1
uint8 SHA1Randx::o1[20] private
Definition at line 66 of file WardenKeyGeneration.h.
Referenced by FillUp(), and SHA1Randx().
o2
uint8 SHA1Randx::o2[20] private
Definition at line 66 of file WardenKeyGeneration.h.
Referenced by FillUp(), and SHA1Randx().
sh
Sha1Hash SHA1Randx::sh private
Definition at line 64 of file WardenKeyGeneration.h.
Referenced by FillUp(), and SHA1Randx().
taken
size_t SHA1Randx::taken private
Definition at line 65 of file WardenKeyGeneration.h.
Referenced by FillUp(), Generate(), and SHA1Randx().
The documentation for this class was generated from the following file:
WardenKeyGeneration.h