CMaNGOS_WoTLK: PlayerbotHunterAI Class Reference
PlayerbotHunterAI Class Reference
#include <PlayerbotHunterAI.h>
Public Member Functions
PlayerbotHunterAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotHunterAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
void DoNonCombatActions () override
Static Public Member Functions
static bool HasPet (Player *bot)
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
bool IsTargetEnraged (Unit *pTarget)
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
virtual CombatManeuverReturns DispelPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Private Attributes
bool m_petSummonFailed
bool m_rangedCombat
bool m_has_ammo
uint32 PET_SUMMON
uint32 PET_DISMISS
uint32 PET_REVIVE
uint32 PET_MEND
uint32 PET_FEED
uint32 BAD_ATTITUDE
uint32 SONIC_BLAST
uint32 NETHER_SHOCK
uint32 DEMORALIZING_SCREECH
uint32 INTIMIDATION
uint32 AUTO_SHOT
uint32 HUNTERS_MARK
uint32 ARCANE_SHOT
uint32 CONCUSSIVE_SHOT
uint32 DISTRACTING_SHOT
uint32 MULTI_SHOT
uint32 EXPLOSIVE_SHOT
uint32 SERPENT_STING
uint32 SCORPID_STING
uint32 VIPER_STING
uint32 WYVERN_STING
uint32 AIMED_SHOT
uint32 STEADY_SHOT
uint32 CHIMERA_SHOT
uint32 VOLLEY
uint32 BLACK_ARROW
uint32 KILL_SHOT
uint32 RAPTOR_STRIKE
uint32 WING_CLIP
uint32 MONGOOSE_BITE
uint32 DISENGAGE
uint32 DETERRENCE
uint32 BEAR_TRAP
uint32 FREEZING_TRAP
uint32 IMMOLATION_TRAP
uint32 FROST_TRAP
uint32 EXPLOSIVE_TRAP
uint32 ARCANE_TRAP
uint32 SNAKE_TRAP
uint32 ASPECT_OF_THE_HAWK
uint32 ASPECT_OF_THE_MONKEY
uint32 RAPID_FIRE
uint32 TRUESHOT_AURA
uint32 MISDIRECTION
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 105 of file PlayerbotHunterAI.h.
Constructor & Destructor Documentation
PlayerbotHunterAI()
PlayerbotHunterAI::PlayerbotHunterAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 24 of file PlayerbotHunterAI.cpp.
References AIMED_SHOT, AIMED_SHOT_1, ARCANE_SHOT, ARCANE_SHOT_1, ARCANE_TORRENT, ARCANE_TORRENT_MANA_CLASSES, ARCANE_TRAP, ASPECT_OF_THE_HAWK, ASPECT_OF_THE_HAWK_1, ASPECT_OF_THE_MONKEY, ASPECT_OF_THE_MONKEY_1, AUTO_SHOT, AUTO_SHOT_1, BAD_ATTITUDE, BEAR_TRAP, BERSERKING, BERSERKING_ALL, BLACK_ARROW, BLACK_ARROW_1, BLOOD_FURY, BLOOD_FURY_MELEE_CLASSES, CALL_PET_1, CHIMERA_SHOT, CHIMERA_SHOT_1, CONCUSSIVE_SHOT, CONCUSSIVE_SHOT_1, DEMORALIZING_SCREECH, DETERRENCE, DETERRENCE_1, DISENGAGE, DISENGAGE_1, DISMISS_PET_1, DISTRACTING_SHOT, DISTRACTING_SHOT_1, EXPLOSIVE_SHOT, EXPLOSIVE_SHOT_1, EXPLOSIVE_TRAP, EXPLOSIVE_TRAP_1, FREEZING_TRAP, FREEZING_TRAP_1, FROST_TRAP, FROST_TRAP_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_HUNTER, HUNTERS_MARK, HUNTERS_MARK_1, IMMOLATION_TRAP, IMMOLATION_TRAP_1, PlayerbotAI::initSpell(), INTIMIDATION, INTIMIDATION_1, KILL_SHOT, KILL_SHOT_1, PlayerbotClassAI::m_ai, m_petSummonFailed, m_rangedCombat, MEND_PET_1, MISDIRECTION, MISDIRECTION_1, MONGOOSE_BITE, MONGOOSE_BITE_1, MULTI_SHOT, MULTISHOT_1, NETHER_SHOCK, PET_DISMISS, PET_FEED, PET_MEND, PET_REVIVE, PET_SUMMON, RAPID_FIRE, RAPID_FIRE_1, RAPTOR_STRIKE, RAPTOR_STRIKE_1, PlayerbotClassAI::RECENTLY_BANDAGED, REVIVE_PET_1, SCORPID_STING, SCORPID_STING_1, SERPENT_STING, SERPENT_STING_1, SHADOWMELD, SHADOWMELD_ALL, SNAKE_TRAP, SNAKE_TRAP_1, SONIC_BLAST, STEADY_SHOT, STEADY_SHOT_1, STONEFORM, STONEFORM_ALL, TRUESHOT_AURA, TRUESHOT_AURA_1, VIPER_STING, VIPER_STING_1, VOLLEY, VOLLEY_1, WAR_STOMP, WAR_STOMP_ALL, WING_CLIP, WING_CLIP_1, WYVERN_STING, and WYVERN_STING_1.
~PlayerbotHunterAI()
PlayerbotHunterAI::~PlayerbotHunterAI () virtual
Definition at line 98 of file PlayerbotHunterAI.cpp.
Member Function Documentation
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotHunterAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 100 of file PlayerbotHunterAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::FindAmmo(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetScenarioType(), Object::GetUInt32Value(), PlayerbotAI::GroupTankHoldsAggro(), Player::HasItemCount(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, m_has_ammo, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, PLAYER_AMMO_ID, RANGED_ATTACK, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, PlayerbotAI::SCENARIO_PVP_OPENWORLD, and Unit::setAttackTimer().
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotHunterAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 148 of file PlayerbotHunterAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotHunterAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 153 of file PlayerbotHunterAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotHunterAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 158 of file PlayerbotHunterAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotHunterAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 175 of file PlayerbotHunterAI.cpp.
References AIMED_SHOT, ARCANE_SHOT, ARCANE_TORRENT, ARCANE_TRAP, ASPECT_OF_THE_HAWK, ASPECT_OF_THE_MONKEY, AURA_STATE_DEADLY_POISON, AUTO_SHOT, BEAR_TRAP, BERSERKING, BLACK_ARROW, BLOOD_FURY, Unit::CanReachWithMeleeAttack(), PlayerbotAI::CastSpell(), Unit::CastSpell(), PlayerbotAI::CheckBotCast(), CHIMERA_SHOT, PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, CONCUSSIVE_SHOT, DETERRENCE, EFFECT_INDEX_0, EXPLOSIVE_SHOT, EXPLOSIVE_TRAP, FROST_TRAP, PlayerbotAI::GetAttackerCount(), PlayerbotAI::GetCombatStyle(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetManaPercent(), Unit::GetPet(), Unit::GetPower(), Unit::getRace(), Object::GetUInt32Value(), Unit::GetVictim(), GIFT_OF_THE_NAARU, Unit::HasAura(), Unit::HasAuraState(), HUNTERS_MARK, IMMOLATION_TRAP, PlayerbotAI::Impulse(), PlayerbotAI::In_Reach(), Unit::InterruptNonMeleeSpells(), INTIMIDATION, Unit::IsAlive(), Unit::isAttackReady(), KILL_SHOT, SQLStorage::LookupEntry(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, m_has_ammo, m_rangedCombat, MISDIRECTION, MONGOOSE_BITE, MULTI_SHOT, PET_MEND, PLAYER_AMMO_ID, POWER_MANA, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RANGED_ATTACK, RAPID_FIRE, RAPTOR_STRIKE, RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, SCORPID_STING, SERPENT_STING, Unit::setAttackTimer(), PlayerbotAI::SetCombatStyle(), SHADOWMELD, SPELL_CAST_OK, sSpellTemplate, STEADY_SHOT, STONEFORM, PlayerbotAI::TellMaster(), TRIGGERED_OLD_TRIGGERED, VIPER_STING, VOLLEY, WAR_STOMP, WING_CLIP, and WYVERN_STING.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotHunterAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 318 of file PlayerbotHunterAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), PlayerbotClassAI::m_ai, RAPTOR_STRIKE, RETURN_CONTINUE, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotHunterAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 342 of file PlayerbotHunterAI.cpp.
References ASPECT_OF_THE_HAWK, Unit::CastCustomSpell(), PlayerbotAI::CastSpell(), Unit::CastSpell(), PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, Player::DestroyItemCount(), PlayerbotClassAI::EatDrinkBandage(), EFFECT_INDEX_0, Bag::GetBagSize(), PlayerbotAI::GetCombatStyle(), Pet::GetCurrentFoodBenefitLevel(), Pet::GetHappinessState(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), Player::GetItemByPos(), Unit::GetPet(), Unit::GetPetGuid(), Item::GetProto(), Unit::getRace(), GIFT_OF_THE_NAARU, HAPPY, Unit::HasAura(), Pet::HaveInDiet(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, INVENTORY_SLOT_BAG_START, INVENTORY_SLOT_ITEM_END, INVENTORY_SLOT_ITEM_START, Unit::IsAlive(), ItemPrototype::ItemLevel, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, m_petSummonFailed, m_rangedCombat, PET_FEED, PET_MEND, PET_REVIVE, PET_SUMMON, RACE_DRAENEI, PlayerbotAI::SetCombatStyle(), PlayerbotAI::SetIgnoreUpdateTime(), SPELL_CAST_OK, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_NO_PET, SPELL_FAILED_NO_POWER, PlayerbotAI::TellMaster(), TRIGGERED_OLD_TRIGGERED, and TRUESHOT_AURA.
HasPet()
static bool PlayerbotHunterAI::HasPet (Player * bot) static
IsTargetEnraged()
bool PlayerbotHunterAI::IsTargetEnraged (Unit * pTarget) private
Definition at line 326 of file PlayerbotHunterAI.cpp.
References SpellEntry::Dispel, DISPEL_ENRAGE, GetDispellMask(), Unit::GetSpellAuraHolderMap(), and SpellAuraHolder::GetSpellProto().
Field Documentation
AIMED_SHOT
uint32 PlayerbotHunterAI::AIMED_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
ARCANE_SHOT
uint32 PlayerbotHunterAI::ARCANE_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
ARCANE_TORRENT
uint32 PlayerbotHunterAI::ARCANE_TORRENT private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
ARCANE_TRAP
uint32 PlayerbotHunterAI::ARCANE_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
ASPECT_OF_THE_HAWK
uint32 PlayerbotHunterAI::ASPECT_OF_THE_HAWK private
Definition at line 138 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotHunterAI().
ASPECT_OF_THE_MONKEY
uint32 PlayerbotHunterAI::ASPECT_OF_THE_MONKEY private
Definition at line 138 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
AUTO_SHOT
uint32 PlayerbotHunterAI::AUTO_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
BAD_ATTITUDE
uint32 PlayerbotHunterAI::BAD_ATTITUDE private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
BEAR_TRAP
uint32 PlayerbotHunterAI::BEAR_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
BERSERKING
uint32 PlayerbotHunterAI::BERSERKING private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
BLACK_ARROW
uint32 PlayerbotHunterAI::BLACK_ARROW private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
BLOOD_FURY
uint32 PlayerbotHunterAI::BLOOD_FURY private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
CHIMERA_SHOT
uint32 PlayerbotHunterAI::CHIMERA_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
CONCUSSIVE_SHOT
uint32 PlayerbotHunterAI::CONCUSSIVE_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
DEMORALIZING_SCREECH
uint32 PlayerbotHunterAI::DEMORALIZING_SCREECH private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
DETERRENCE
uint32 PlayerbotHunterAI::DETERRENCE private
Definition at line 136 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
DISENGAGE
uint32 PlayerbotHunterAI::DISENGAGE private
Definition at line 136 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
DISTRACTING_SHOT
uint32 PlayerbotHunterAI::DISTRACTING_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
ESCAPE_ARTIST
uint32 PlayerbotHunterAI::ESCAPE_ARTIST private
Definition at line 141 of file PlayerbotHunterAI.h.
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotHunterAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 141 of file PlayerbotHunterAI.h.
EXPLOSIVE_SHOT
uint32 PlayerbotHunterAI::EXPLOSIVE_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
EXPLOSIVE_TRAP
uint32 PlayerbotHunterAI::EXPLOSIVE_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
FREEZING_TRAP
uint32 PlayerbotHunterAI::FREEZING_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
FROST_TRAP
uint32 PlayerbotHunterAI::FROST_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotHunterAI::GIFT_OF_THE_NAARU private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotHunterAI().
HUNTERS_MARK
uint32 PlayerbotHunterAI::HUNTERS_MARK private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
IMMOLATION_TRAP
uint32 PlayerbotHunterAI::IMMOLATION_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
INTIMIDATION
uint32 PlayerbotHunterAI::INTIMIDATION private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
KILL_SHOT
uint32 PlayerbotHunterAI::KILL_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
m_has_ammo
bool PlayerbotHunterAI::m_has_ammo private
Definition at line 132 of file PlayerbotHunterAI.h.
Referenced by DoFirstCombatManeuver(), and DoNextCombatManeuverPVE().
m_petSummonFailed
bool PlayerbotHunterAI::m_petSummonFailed private
Definition at line 130 of file PlayerbotHunterAI.h.
Referenced by DoNonCombatActions(), and PlayerbotHunterAI().
m_rangedCombat
bool PlayerbotHunterAI::m_rangedCombat private
Definition at line 131 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotHunterAI().
MISDIRECTION
uint32 PlayerbotHunterAI::MISDIRECTION private
Definition at line 138 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
MONGOOSE_BITE
uint32 PlayerbotHunterAI::MONGOOSE_BITE private
Definition at line 136 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
MULTI_SHOT
uint32 PlayerbotHunterAI::MULTI_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
NETHER_SHOCK
uint32 PlayerbotHunterAI::NETHER_SHOCK private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
PET_DISMISS
uint32 PlayerbotHunterAI::PET_DISMISS private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
PET_FEED
uint32 PlayerbotHunterAI::PET_FEED private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by DoNonCombatActions(), and PlayerbotHunterAI().
PET_MEND
uint32 PlayerbotHunterAI::PET_MEND private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotHunterAI().
PET_REVIVE
uint32 PlayerbotHunterAI::PET_REVIVE private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by DoNonCombatActions(), and PlayerbotHunterAI().
PET_SUMMON
uint32 PlayerbotHunterAI::PET_SUMMON private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by DoNonCombatActions(), and PlayerbotHunterAI().
RAPID_FIRE
uint32 PlayerbotHunterAI::RAPID_FIRE private
Definition at line 138 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
RAPTOR_STRIKE
uint32 PlayerbotHunterAI::RAPTOR_STRIKE private
Definition at line 136 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotHunterAI().
SCORPID_STING
uint32 PlayerbotHunterAI::SCORPID_STING private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
SERPENT_STING
uint32 PlayerbotHunterAI::SERPENT_STING private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
SHADOWMELD
uint32 PlayerbotHunterAI::SHADOWMELD private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
SNAKE_TRAP
uint32 PlayerbotHunterAI::SNAKE_TRAP private
Definition at line 137 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
SONIC_BLAST
uint32 PlayerbotHunterAI::SONIC_BLAST private
Definition at line 134 of file PlayerbotHunterAI.h.
Referenced by PlayerbotHunterAI().
STEADY_SHOT
uint32 PlayerbotHunterAI::STEADY_SHOT private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
STONEFORM
uint32 PlayerbotHunterAI::STONEFORM private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
TRUESHOT_AURA
uint32 PlayerbotHunterAI::TRUESHOT_AURA private
Definition at line 138 of file PlayerbotHunterAI.h.
Referenced by DoNonCombatActions(), and PlayerbotHunterAI().
VIPER_STING
uint32 PlayerbotHunterAI::VIPER_STING private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
VOLLEY
uint32 PlayerbotHunterAI::VOLLEY private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
WAR_STOMP
uint32 PlayerbotHunterAI::WAR_STOMP private
Definition at line 141 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
WILL_OF_THE_FORSAKEN
uint32 PlayerbotHunterAI::WILL_OF_THE_FORSAKEN private
Definition at line 141 of file PlayerbotHunterAI.h.
WING_CLIP
uint32 PlayerbotHunterAI::WING_CLIP private
Definition at line 136 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
WYVERN_STING
uint32 PlayerbotHunterAI::WYVERN_STING private
Definition at line 135 of file PlayerbotHunterAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotHunterAI().
The documentation for this class was generated from the following files:
PlayerbotHunterAI.h
PlayerbotHunterAI.cpp