CMaNGOS_WoTLK: MaNGOS::TauntFlagObjectCheck Class Reference
MaNGOS::TauntFlagObjectCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
TauntFlagObjectCheck (Unit const *fobj, float range)
WorldObject const & GetFocusObject () const
bool operator() (Player *u)
bool operator() (Corpse *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Private Attributes
Unit const * i_fobj
float i_range
Detailed Description
Definition at line 661 of file GridNotifiers.h.
Constructor & Destructor Documentation
TauntFlagObjectCheck()
MaNGOS::TauntFlagObjectCheck::TauntFlagObjectCheck (Unit const * fobj, float range) inline
Definition at line 664 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::TauntFlagObjectCheck::GetFocusObject () const inline
Definition at line 665 of file GridNotifiers.h.
References i_fobj.
operator()() [1/3]
bool TauntFlagObjectCheck::operator() (Corpse * u)
Definition at line 253 of file GridNotifiers.cpp.
References Unit::CanAssist(), CORPSE_BONES, ObjectAccessor::FindPlayer(), Corpse::GetOwnerGuid(), Corpse::GetType(), i_fobj, i_range, and WorldObject::IsWithinDistInMap().
operator()() [2/3]
template<class NOT_INTERESTED > bool MaNGOS::TauntFlagObjectCheck::operator() (NOT_INTERESTED *) inline
Definition at line 674 of file GridNotifiers.h.
operator()() [3/3]
bool MaNGOS::TauntFlagObjectCheck::operator() (Player * u) inline
Definition at line 666 of file GridNotifiers.h.
References Unit::CanAssist(), i_fobj, i_range, Unit::IsAlive(), Unit::IsTaxiFlying(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_fobj
Unit const* MaNGOS::TauntFlagObjectCheck::i_fobj private
Definition at line 676 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::TauntFlagObjectCheck::i_range private
Definition at line 677 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp