CMaNGOS_WoTLK: GMTicketMgr Class Reference
GMTicketMgr Class Reference
#include <GMTicketMgr.h>
Public Types
enum CommandResult : uint8 {
COMMAND_RESULT_SUCCESS = 0 , COMMAND_RESULT_TICKET_NOT_FOUND = 1 , COMMAND_RESULT_PLAYER_OFFLINE = 2 , COMMAND_RESULT_ACCESS_DENIED = 3 ,
COMMAND_RESULT_TICKET_NOT_ASSIGNED = 4 , COMMAND_RESULT_TICKET_UNSEEN = 5
}
Public Member Functions
GMTicketMgr ()
~GMTicketMgr ()=default
void LoadGMTickets ()
void PrintTicketList (WorldSession *session, std::ostringstream &output, size_t max, const GMTicketCategoryEntry *category=nullptr, bool online=false) const
void OnPlayerOnlineState (Player &player, bool online) const
void ShowMOTD (Player &gm) const
std::pair< bool, bool > HookGMTicketWhisper (Player *sender, const std::string &recepient, Player *character, const std::string &msg, bool addon)
bool HookGMTicketWhoQuery (const std::string &query, Player *gm) const
GMTicket * GetTicketById (uint32 id, GMTicketState state=GMTICKET_STATE_OPEN) const
GMTicket * GetTicketByPlayer (ObjectGuid playerGuid, GMTicketState state=GMTICKET_STATE_OPEN, ObjectGuid assigneeGuid=ObjectGuid()) const
bool Add (GMTicket *ticket, bool loading=false)
bool Recycle (GMTicket *ticket)
void Survey (GMTicket *ticket, const GMSurveyResult *result=nullptr)
CommandResult Abandon (GMTicket *ticket)
CommandResult Discard (GMTicket *ticket, const std::string &reason, WorldSession *session=nullptr)
CommandResult Escalate (GMTicket *ticket, WorldSession *session, uint8 level)
CommandResult Comment (GMTicket *ticket, WorldSession *session, const std::string &text)
CommandResult Read (GMTicket *ticket)
CommandResult Resolve (GMTicket *ticket, const std::string &commentary, WorldSession *session=nullptr)
CommandResult Sort (GMTicket *ticket, const GMTicketCategoryEntry &category, WorldSession *session=nullptr)
CommandResult Update (GMTicket *ticket, const std::string &text)
CommandResult Whisper (GMTicket *ticket, const std::string &message, WorldSession *session=nullptr)
float GetOldestTicketAgeDays () const
float GetOldestTicketAgeLastUpdateDays (time_t now) const
bool GetSystemStatus () const
bool SetSystemStatus (bool status)
uint32 GenerateTicketId ()
Static Public Member Functions
static void Save (const GMTicket *ticket)
static void Save (const GMSurveyResult *survey)
static void Print (GMTicket const &ticket, WorldSession *session, time_t now=time(nullptr))
static const std::string PrintMailResponse (GMTicket const &ticket, bool resolved)
static const char * PrintTicketCategory (GMTicket const &ticket, LocaleConstant locale=DEFAULT_LOCALE)
static const char * PrintTicketChatAlert (GMTicketMgrChatAlert alert, LocaleConstant locale=DEFAULT_LOCALE)
static const char * PrintTicketStatus (GMTicket const &ticket, LocaleConstant locale=DEFAULT_LOCALE)
static const char * PrintTicketStatusColorSequence (GMTicket const &ticket)
static const std::string PrintTicketSummaryLine (GMTicket const &ticket, LocaleConstant locale=DEFAULT_LOCALE)
static bool TicketChatIncoming (GMTicket *ticket, Player *player, WorldSession *gm, const std::string &message, bool addon=false)
static bool TicketChatOutgoing (GMTicket *ticket, WorldSession *gm, Player *player, const std::string &message, bool addon=false)
static bool TicketChatAlert (const GMTicket *ticket, GMTicketMgrChatAlert alert)
static float GetDaysPassed (time_t now, time_t since)
static float GetTicketAgeDays (time_t now, time_t created)
Private Member Functions
std::pair< GMTicket *, std::string > GetTicketByIdTag (const std::string &tag, GMTicketState state=GMTICKET_STATE_OPEN, ObjectGuid assigneeGuid=ObjectGuid()) const
bool Remove (GMTicket &ticket)
void RemoveAll ()
CommandResult Close (GMTicket *ticket, const std::string &commentary, bool resolved, WorldSession *session=nullptr)
void UpdateTicketQueueStats (GMTicket &closed, time_t when)
void UpdateTicketQueueTimers (GMTicket *except=nullptr) const
float GetAverageResolutionDays () const
size_t GetTicketCount () const
Static Private Member Functions
static CommandResult CanComment (const GMTicket *ticket, WorldSession *who)
static CommandResult CanClose (const GMTicket *ticket, bool resolve, WorldSession *who)
static CommandResult CanSort (const GMTicket *ticket, WorldSession *who)
static CommandResult CanWhisper (const GMTicket *ticket, WorldSession *who)
Private Attributes
GMTicketSystemStatus m_status
GMTicketMap m_tickets
GMTicketList m_list
uint32 m_lastTicketId = 0
uint32 m_currentTicketCountOpen = 0
uint32 m_currentTicketCountClosed = 0
float m_statsAverageResolutionDays = 0
float m_statsCurrentTotalResolutionDays = 0
float m_statsOldestTicketAgeDays = -1
time_t m_statsOldestTicketAgeLastUpdate = 0
Detailed Description
Definition at line 214 of file GMTicketMgr.h.
Member Enumeration Documentation
CommandResult
enum GMTicketMgr::CommandResult : uint8
Enumerator
COMMAND_RESULT_SUCCESS
COMMAND_RESULT_TICKET_NOT_FOUND
COMMAND_RESULT_PLAYER_OFFLINE
COMMAND_RESULT_ACCESS_DENIED
COMMAND_RESULT_TICKET_NOT_ASSIGNED
COMMAND_RESULT_TICKET_UNSEEN
Definition at line 217 of file GMTicketMgr.h.
Constructor & Destructor Documentation
GMTicketMgr()
GMTicketMgr::GMTicketMgr ()
Definition at line 323 of file GMTicketMgr.cpp.
References CONFIG_BOOL_GM_TICKETS_QUEUE_STATUS, m_status, and sWorld.
~GMTicketMgr()
GMTicketMgr::~GMTicketMgr () default
Member Function Documentation
Abandon()
GMTicketMgr::CommandResult GMTicketMgr::Abandon (GMTicket * ticket)
Definition at line 957 of file GMTicketMgr.cpp.
References COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_FOUND, GMTicket::GetIdTag(), GMTICKET_STATE_ABANDONED, GMTICKETMGR_CHAT_ABANDONED, GMTicket::IsOpen(), LANG_TICKET_BROADCAST_ABANDONED, m_currentTicketCountOpen, Save(), GMTicket::SetState(), sWorld, and TicketChatAlert().
Add()
bool GMTicketMgr::Add (GMTicket * ticket, bool loading = false)
Definition at line 897 of file GMTicketMgr.cpp.
References GMTicket::GetAuthorName(), GMTicket::GetId(), GMTicket::GetIdTag(), GMTicket::IsOpen(), LANG_TICKET_BROADCAST_NEW, m_currentTicketCountOpen, m_list, m_tickets, Save(), and sWorld.
Referenced by LoadGMTickets().
CanClose()
GMTicketMgr::CommandResult GMTicketMgr::CanClose (const GMTicket * ticket, bool resolve, WorldSession * who) inline static private
Definition at line 1196 of file GMTicketMgr.cpp.
References COMMAND_RESULT_ACCESS_DENIED, COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_ASSIGNED, COMMAND_RESULT_TICKET_NOT_FOUND, COMMAND_RESULT_TICKET_UNSEEN, GMTicket::GetAuthorName(), GMTicket::GetLevel(), WorldSession::GetPlayerName(), WorldSession::GetSecurity(), GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), GMTicket::IsOpen(), and GMTicket::IsSeen().
Referenced by Close(), and Print().
CanComment()
GMTicketMgr::CommandResult GMTicketMgr::CanComment (const GMTicket * ticket, WorldSession * who) inline static private
Definition at line 1184 of file GMTicketMgr.cpp.
References COMMAND_RESULT_ACCESS_DENIED, COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_FOUND, COMMAND_RESULT_TICKET_UNSEEN, GMTicket::IsOpen(), and GMTicket::IsSeen().
Referenced by Comment(), and Print().
CanSort()
GMTicketMgr::CommandResult GMTicketMgr::CanSort (const GMTicket * ticket, WorldSession * who) inline static private
Definition at line 1217 of file GMTicketMgr.cpp.
References COMMAND_RESULT_ACCESS_DENIED, COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_ASSIGNED, COMMAND_RESULT_TICKET_NOT_FOUND, COMMAND_RESULT_TICKET_UNSEEN, GMTicket::GetLevel(), WorldSession::GetPlayerName(), WorldSession::GetSecurity(), GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), GMTicket::IsOpen(), and GMTicket::IsSeen().
Referenced by Print(), and Sort().
CanWhisper()
GMTicketMgr::CommandResult GMTicketMgr::CanWhisper (const GMTicket * ticket, WorldSession * who) inline static private
Definition at line 1233 of file GMTicketMgr.cpp.
References COMMAND_RESULT_ACCESS_DENIED, COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_ASSIGNED, COMMAND_RESULT_TICKET_NOT_FOUND, COMMAND_RESULT_TICKET_UNSEEN, GMTicket::GetLevel(), WorldSession::GetPlayerName(), WorldSession::GetSecurity(), GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), GMTicket::IsOpen(), and GMTicket::IsSeen().
Referenced by HookGMTicketWhisper(), Print(), and Whisper().
Close()
GMTicketMgr::CommandResult GMTicketMgr::Close (GMTicket * ticket, const std::string & commentary, bool resolved, WorldSession * session = nullptr) private
Definition at line 1280 of file GMTicketMgr.cpp.
References CanClose(), COMMAND_RESULT_SUCCESS, GMTicket::GetAssigneeGuid(), GMTicket::GetAssigneeName(), GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), ObjectGuid::GetCounter(), GMTicket::GetIdTag(), GMTicket::GetLocale(), GetLocaleByName(), WorldSession::GetPlayerName(), WorldSession::GetSecurity(), Player::GetSession(), GMTICKET_STATE_CLOSED, GMTICKET_STATUS_CLOSED, GMTICKET_STATUS_SURVEY, GMTicket::IsSurveyed(), LANG_TICKET_BROADCAST_CLOSED, LANG_TICKET_CLOSED_LETTER_TITLE, m_currentTicketCountClosed, m_currentTicketCountOpen, MAIL_NORMAL, MAIL_STATIONERY_GM, PrintMailResponse(), Remove(), Save(), WorldSession::SendGMTicketResult(), MailDraft::SendMailTo(), GMTicket::SetAssignee(), GMTicket::SetConclusion(), GMTicket::SetState(), SMSG_GM_TICKET_STATUS_UPDATE, sObjectMgr, sTicketMgr, sWorld, and UpdateTicketQueueStats().
Referenced by Discard(), and Resolve().
Comment()
GMTicketMgr::CommandResult GMTicketMgr::Comment (GMTicket * ticket, WorldSession * session, const std::string & text)
Definition at line 1026 of file GMTicketMgr.cpp.
References GMTicket::AddNote(), CanComment(), COMMAND_RESULT_SUCCESS, GMTicket::GetIdTag(), WorldSession::GetPlayerName(), LANG_TICKET_BROADCAST_COMMENTARY, Save(), StrSplit(), sWorld, and TimeToTimestampStr().
Discard()
CommandResult GMTicketMgr::Discard (GMTicket * ticket, const std::string & reason, WorldSession * session = nullptr) inline
Definition at line 265 of file GMTicketMgr.h.
References Close().
Escalate()
GMTicketMgr::CommandResult GMTicketMgr::Escalate (GMTicket * ticket, WorldSession * session, uint8 level)
Definition at line 976 of file GMTicketMgr.cpp.
References clamp(), COMMAND_RESULT_ACCESS_DENIED, COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_ASSIGNED, COMMAND_RESULT_TICKET_NOT_FOUND, COMMAND_RESULT_TICKET_UNSEEN, GMTicket::Compare(), GMTicket::GetAssigneeGuid(), GMTicket::GetAuthorGuid(), GMTicket::GetIdTag(), GMTicket::GetLevel(), WorldSession::GetPlayerName(), WorldSession::GetSecurity(), GMTICKET_STATUS_UPDATED, GMTICKETMGR_CHAT_ESCALATED, GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), GMTicket::IsEscalated(), GMTicket::IsOpen(), GMTicket::IsSeen(), LANG_TICKET_BROADCAST_ESCALATION, m_list, Save(), SEC_ADMINISTRATOR, GMTicket::SetAssignee(), SMSG_GM_TICKET_STATUS_UPDATE, sObjectMgr, sWorld, and TicketChatAlert().
GenerateTicketId()
uint32 GMTicketMgr::GenerateTicketId () inline
Definition at line 283 of file GMTicketMgr.h.
References m_lastTicketId.
GetAverageResolutionDays()
float GMTicketMgr::GetAverageResolutionDays () const inline private
Definition at line 301 of file GMTicketMgr.h.
References m_statsAverageResolutionDays.
Referenced by ShowMOTD().
GetDaysPassed()
static float GMTicketMgr::GetDaysPassed (time_t now, time_t since) inline static
Definition at line 274 of file GMTicketMgr.h.
References DAY.
Referenced by GetOldestTicketAgeLastUpdateDays(), GetTicketAgeDays(), and UpdateTicketQueueStats().
GetOldestTicketAgeDays()
float GMTicketMgr::GetOldestTicketAgeDays () const inline
Definition at line 277 of file GMTicketMgr.h.
References m_statsOldestTicketAgeDays.
GetOldestTicketAgeLastUpdateDays()
float GMTicketMgr::GetOldestTicketAgeLastUpdateDays (time_t now) const
Definition at line 1340 of file GMTicketMgr.cpp.
References GetDaysPassed(), and m_statsOldestTicketAgeLastUpdate.
GetSystemStatus()
bool GMTicketMgr::GetSystemStatus () const inline
Definition at line 280 of file GMTicketMgr.h.
References m_status.
Referenced by ShowMOTD().
GetTicketAgeDays()
static float GMTicketMgr::GetTicketAgeDays (time_t now, time_t created) inline static
Definition at line 276 of file GMTicketMgr.h.
References GetDaysPassed().
Referenced by UpdateTicketQueueStats().
GetTicketById()
GMTicket * GMTicketMgr::GetTicketById (uint32 id, GMTicketState state = GMTICKET_STATE_OPEN) const
Definition at line 847 of file GMTicketMgr.cpp.
References m_tickets.
Referenced by GetTicketByIdTag().
GetTicketByIdTag()
std::pair< GMTicket *, std::string > GMTicketMgr::GetTicketByIdTag (const std::string & tag, GMTicketState state = GMTICKET_STATE_OPEN, ObjectGuid assigneeGuid = ObjectGuid()) const private
Definition at line 873 of file GMTicketMgr.cpp.
References GetTicketById(), and ObjectGuid::IsPlayer().
Referenced by HookGMTicketWhisper(), and HookGMTicketWhoQuery().
GetTicketByPlayer()
GMTicket * GMTicketMgr::GetTicketByPlayer (ObjectGuid playerGuid, GMTicketState state = GMTICKET_STATE_OPEN, ObjectGuid assigneeGuid = ObjectGuid()) const
Definition at line 856 of file GMTicketMgr.cpp.
References GMTicket::GetAuthorGuid(), GMTicket::GetState(), GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), ObjectGuid::IsPlayer(), and m_tickets.
Referenced by HookGMTicketWhisper(), and OnPlayerOnlineState().
GetTicketCount()
size_t GMTicketMgr::GetTicketCount () const inline private
Definition at line 302 of file GMTicketMgr.h.
References m_tickets.
Referenced by LoadGMTickets().
HookGMTicketWhisper()
std::pair< bool, bool > GMTicketMgr::HookGMTicketWhisper (Player * sender, const std::string & recepient, Player * character, const std::string & msg, bool addon)
Definition at line 767 of file GMTicketMgr.cpp.
References CanWhisper(), COMMAND_RESULT_SUCCESS, GMTicket::GetAuthorName(), GMTicket::GetId(), Object::GetObjectGuid(), Player::GetSession(), GetTicketByIdTag(), GetTicketByPlayer(), GMTICKET_STATE_OPEN, Player::isAcceptTickets(), ChatHandler::ParseCommands(), sObjectMgr, TicketChatIncoming(), and TicketChatOutgoing().
HookGMTicketWhoQuery()
bool GMTicketMgr::HookGMTicketWhoQuery (const std::string & query, Player * gm) const
Definition at line 823 of file GMTicketMgr.cpp.
References Player::GetSession(), GetTicketByIdTag(), GMTICKET_STATE_OPEN, Player::isAcceptTickets(), Print(), and SMSG_WHO.
LoadGMTickets()
void GMTicketMgr::LoadGMTickets ()
Definition at line 328 of file GMTicketMgr.cpp.
References Add(), CharacterDatabase, GMTicket::Compare(), GetTicketCount(), m_lastTicketId, m_list, Database::Query(), RemoveAll(), SIZEFMTD, sLog, and BarGoLink::step().
OnPlayerOnlineState()
void GMTicketMgr::OnPlayerOnlineState (Player & player, bool online) const
Definition at line 688 of file GMTicketMgr.cpp.
References Object::GetObjectGuid(), Player::GetSession(), GetTicketByPlayer(), GMTICKET_STATE_CLOSED, GMTICKETMGR_CHAT_OFFLINE, GMTICKETMGR_CHAT_ONLINE, SEC_GAMEMASTER, sTicketMgr, and TicketChatAlert().
Print()
void GMTicketMgr::Print (GMTicket const & ticket, WorldSession * session, time_t now = time(nullptr)) static
Definition at line 372 of file GMTicketMgr.cpp.
References CanClose(), CanComment(), CanSort(), CanWhisper(), COMMAND_RESULT_SUCCESS, GMTicket::GetAnsweredAt(), GMTicket::GetAssigneeGuid(), GMTicket::GetAssigneeName(), GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), GMTicket::GetCategory(), GMTicket::GetClosedAt(), GMTicket::GetConclusion(), ObjectGuid::GetCounter(), GMTicket::GetCreatedAt(), GMTicket::GetId(), GMTicket::GetLastSeenAt(), GMTicket::GetLevel(), GMTicket::GetLocale(), GMTicket::GetMapId(), GMTicket::GetNotes(), GMTicket::GetPositionX(), GMTicket::GetPositionY(), GMTicket::GetPositionZ(), WorldSession::GetSessionDbcLocale(), GMTicket::GetText(), GMTicket::GetUpdatedAt(), GMTicket::IsOpen(), LANG_OFFLINE, LANG_TICKET_DETAILS_ACTION_DISCARD, LANG_TICKET_DETAILS_ACTION_NOTE, LANG_TICKET_DETAILS_ACTION_RESOLVE, LANG_TICKET_DETAILS_ACTION_SORT, LANG_TICKET_DETAILS_ACTION_WHISPER, LANG_TICKET_DETAILS_LINE_ACTIONS, LANG_TICKET_DETAILS_LINE_ANSWERED, LANG_TICKET_DETAILS_LINE_ASSIGNED, LANG_TICKET_DETAILS_LINE_AUTHOR, LANG_TICKET_DETAILS_LINE_CLOSED, LANG_TICKET_DETAILS_LINE_CONCLUSION, LANG_TICKET_DETAILS_LINE_GM_NOTES, LANG_TICKET_DETAILS_LINE_LOCATION, LANG_TICKET_DETAILS_LINE_QUOTE, LANG_TICKET_DETAILS_LINE_QUOTE_GM, LANG_TICKET_DETAILS_LINE_SEEN, LANG_TICKET_DETAILS_LINE_SUBMITTED, LANG_TICKET_DETAILS_LINE_SUMMARY, LANG_TICKET_DETAILS_LINE_TEXT, LANG_TICKET_DETAILS_LINE_UPDATED, LANG_TICKETS_PRINT_SPACER, PrintTicketCategory(), PrintTicketStatus(), ChatHandler::PSendSysMessage(), secsToTimeString(), ChatHandler::SendSysMessage(), sObjectMgr, StrSplit(), and TimeToTimestampStr().
Referenced by ChatHandler::HandleTicketReadCommand(), and HookGMTicketWhoQuery().
PrintMailResponse()
const std::string GMTicketMgr::PrintMailResponse (GMTicket const & ticket, bool resolved) inline static
Definition at line 433 of file GMTicketMgr.cpp.
References GMTicket::GetAssigneeName(), GMTicket::GetConclusion(), GMTicket::GetLocale(), GetLocaleByName(), LANG_TICKET_CLOSED_LETTER_DISCARDED, LANG_TICKET_CLOSED_LETTER_FOOTNOTE, LANG_TICKET_CLOSED_LETTER_RESOLVED, and sObjectMgr.
Referenced by Close().
PrintTicketCategory()
const char * GMTicketMgr::PrintTicketCategory (GMTicket const & ticket, LocaleConstant locale = DEFAULT_LOCALE) inline static
Definition at line 456 of file GMTicketMgr.cpp.
References GMTicket::GetCategory(), LANG_UNKNOWN, sGMTicketCategoryStore, sObjectMgr, and sWorld.
Referenced by Print(), PrintTicketSummaryLine(), and Sort().
PrintTicketChatAlert()
const char * GMTicketMgr::PrintTicketChatAlert (GMTicketMgrChatAlert alert, LocaleConstant locale = DEFAULT_LOCALE) inline static
Definition at line 469 of file GMTicketMgr.cpp.
References GMTICKETMGR_CHAT_ABANDONED, GMTICKETMGR_CHAT_ESCALATED, GMTICKETMGR_CHAT_OFFLINE, GMTICKETMGR_CHAT_ONLINE, GMTICKETMGR_CHAT_UPDATED, LANG_TICKET_ASSIGNEE_ALERT_ABANDONED, LANG_TICKET_ASSIGNEE_ALERT_ESCALATED, LANG_TICKET_ASSIGNEE_ALERT_OFFLINE, LANG_TICKET_ASSIGNEE_ALERT_ONLINE, LANG_TICKET_ASSIGNEE_ALERT_UPDATED, and sObjectMgr.
Referenced by TicketChatAlert().
PrintTicketList()
void GMTicketMgr::PrintTicketList (WorldSession * session, std::ostringstream & output, size_t max, const GMTicketCategoryEntry * category = nullptr, bool online = false) const
Definition at line 552 of file GMTicketMgr.cpp.
References WorldSession::GetMangosString(), WorldSession::GetSessionDbcLocale(), GMTicketCategoryEntry::ID, LANG_COMMAND_TICKETS_LISTING_FOOTER, LANG_TICKETS_PRINT_SPACER, m_list, PrintTicketSummaryLine(), and sObjectMgr.
PrintTicketStatus()
const char * GMTicketMgr::PrintTicketStatus (GMTicket const & ticket, LocaleConstant locale = DEFAULT_LOCALE) inline static
Definition at line 485 of file GMTicketMgr.cpp.
References GMTicket::GetState(), GMTicket::GetStatus(), GMTICKET_ASSIGNEDTOGM_STATUS_ASSIGNED, GMTICKET_ASSIGNEDTOGM_STATUS_ESCALATED, GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, GMTICKET_STATE_ABANDONED, GMTICKET_STATE_CLOSED, GMTICKET_STATE_OPEN, GMTicket::IsSeen(), LANG_TICKET_STATUS_BRIEF_ABANDONED, LANG_TICKET_STATUS_BRIEF_ASSIGNED, LANG_TICKET_STATUS_BRIEF_CLOSED, LANG_TICKET_STATUS_BRIEF_ESCALATED, LANG_TICKET_STATUS_BRIEF_OPEN, LANG_TICKET_STATUS_BRIEF_UNSEEN, LANG_UNKNOWN, and sObjectMgr.
Referenced by Print(), and PrintTicketSummaryLine().
PrintTicketStatusColorSequence()
const char * GMTicketMgr::PrintTicketStatusColorSequence (GMTicket const & ticket) inline static
Definition at line 511 of file GMTicketMgr.cpp.
References GMTicket::GetState(), GMTicket::GetStatus(), GMTICKET_ASSIGNEDTOGM_STATUS_ASSIGNED, GMTICKET_ASSIGNEDTOGM_STATUS_ESCALATED, GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, GMTICKET_STATE_ABANDONED, GMTICKET_STATE_CLOSED, GMTICKET_STATE_OPEN, and GMTicket::IsSeen().
Referenced by PrintTicketSummaryLine().
PrintTicketSummaryLine()
const std::string GMTicketMgr::PrintTicketSummaryLine (GMTicket const & ticket, LocaleConstant locale = DEFAULT_LOCALE) inline static
Definition at line 533 of file GMTicketMgr.cpp.
References GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), GMTicket::GetCategory(), GMTicket::GetId(), GMTicket::GetLevel(), GMTicket::GetLocale(), LANG_OFFLINE, PrintTicketCategory(), PrintTicketStatus(), PrintTicketStatusColorSequence(), and sObjectMgr.
Referenced by PrintTicketList().
Read()
GMTicketMgr::CommandResult GMTicketMgr::Read (GMTicket * ticket)
Definition at line 1049 of file GMTicketMgr.cpp.
References COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_FOUND, GMTicket::Compare(), GMTicket::GetAuthorGuid(), GMTICKET_STATUS_UPDATED, GMTicket::IsOpen(), GMTicket::IsSeen(), m_list, Save(), GMTicket::SetSeen(), SMSG_GM_TICKET_STATUS_UPDATE, and sObjectMgr.
Recycle()
bool GMTicketMgr::Recycle (GMTicket * ticket)
Definition at line 921 of file GMTicketMgr.cpp.
References GMTicket::Compare(), GMTicket::GetAuthorName(), GMTicket::GetId(), GMTicket::GetIdTag(), GMTicket::GetState(), GMTICKET_STATE_ABANDONED, GMTICKET_STATE_OPEN, LANG_TICKET_BROADCAST_NEW, m_currentTicketCountOpen, m_list, m_tickets, Save(), GMTicket::SetState(), and sWorld.
Remove()
bool GMTicketMgr::Remove (GMTicket & ticket) private
Definition at line 1249 of file GMTicketMgr.cpp.
References GMTicket::GetId(), GMTicket::IsOpen(), m_currentTicketCountOpen, m_list, and m_tickets.
Referenced by Close(), and Survey().
RemoveAll()
void GMTicketMgr::RemoveAll () private
Definition at line 1269 of file GMTicketMgr.cpp.
References m_currentTicketCountOpen, m_list, and m_tickets.
Referenced by LoadGMTickets().
Resolve()
CommandResult GMTicketMgr::Resolve (GMTicket * ticket, const std::string & commentary, WorldSession * session = nullptr) inline
Definition at line 269 of file GMTicketMgr.h.
References Close().
Save() [1/2]
void GMTicketMgr::Save (const GMSurveyResult * survey) static
Definition at line 298 of file GMTicketMgr.cpp.
References CharacterDatabase, GMSurveyResult::GetAnswers(), GMSurveyResult::GetAnswersCount(), GMSurveyResult::GetComment(), GMSurveyResult::GetSurveyId(), GMSurveyResult::GetTicketId(), GMSurveyResult::HasComment(), and Database::PExecute().
Save() [2/2]
void GMTicketMgr::Save (const GMTicket * ticket) static
Definition at line 154 of file GMTicketMgr.cpp.
References CharacterDatabase, Database::CreateStatement(), SqlStatement::Execute(), GMTicket::GetId(), Database::PExecute(), and GMTicket::Save().
Referenced by Abandon(), Add(), Close(), Comment(), Escalate(), Read(), Recycle(), Sort(), Survey(), Update(), and Whisper().
SetSystemStatus()
bool GMTicketMgr::SetSystemStatus (bool status)
Definition at line 1158 of file GMTicketMgr.cpp.
References GMTicket::GetAuthorGuid(), GMTICKET_STATUS_UPDATED, GMTicket::IsOpen(), m_status, m_tickets, SMSG_GM_TICKET_STATUS_UPDATE, SMSG_GMTICKET_SYSTEMSTATUS, sObjectMgr, and sWorld.
ShowMOTD()
void GMTicketMgr::ShowMOTD (Player & gm) const
Definition at line 706 of file GMTicketMgr.cpp.
References DAY, GetAverageResolutionDays(), ChatHandler::GetMangosString(), Object::GetObjectGuid(), Player::GetSession(), GetSystemStatus(), GMTICKETMGR_CHAT_ONLINE, Player::isAcceptTickets(), LANG_OFF, LANG_ON, LANG_TICKET_MOTD_SYSTEM_ASSIGNED, LANG_TICKET_MOTD_SYSTEM_STATS_CLOSED, LANG_TICKET_MOTD_SYSTEM_STATS_OPEN, LANG_TICKET_MOTD_SYSTEM_STATUS, LANG_TICKETS_NOTIFICATIONS, m_currentTicketCountClosed, m_currentTicketCountOpen, m_list, ChatHandler::PSendSysMessage(), secsToTimeString(), sObjectMgr, strToUpper(), and TicketChatAlert().
Sort()
GMTicketMgr::CommandResult GMTicketMgr::Sort (GMTicket * ticket, const GMTicketCategoryEntry & category, WorldSession * session = nullptr)
Definition at line 1074 of file GMTicketMgr.cpp.
References CanSort(), COMMAND_RESULT_SUCCESS, GMTicket::GetAuthorGuid(), GMTicket::GetCategory(), GMTicket::GetIdTag(), WorldSession::GetPlayerName(), GMTICKET_STATUS_UPDATED, GMTicketCategoryEntry::ID, LANG_TICKET_BROADCAST_CATEGORY, PrintTicketCategory(), Save(), GMTicket::SetCategory(), SMSG_GM_TICKET_STATUS_UPDATE, sObjectMgr, and sWorld.
Survey()
void GMTicketMgr::Survey (GMTicket * ticket, const GMSurveyResult * result = nullptr)
Definition at line 942 of file GMTicketMgr.cpp.
References GMTicket::GetIdTag(), GMTicket::IsOpen(), GMTicket::IsSurveyed(), LANG_TICKET_BROADCAST_SURVEY, Remove(), Save(), and sWorld.
TicketChatAlert()
bool GMTicketMgr::TicketChatAlert (const GMTicket * ticket, GMTicketMgrChatAlert alert) static
Definition at line 667 of file GMTicketMgr.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_WHISPER, CHAT_TAG_NONE, GMTicket::GetAssigneeGuid(), GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), GMTicket::GetIdTag(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), GMTICKETMGR_CHAT_OFFLINE, Player::isAcceptTickets(), GMTicket::IsAssigned(), GMTicket::IsAssignedTo(), LANG_UNIVERSAL, PrintTicketChatAlert(), WorldSession::SendPacket(), and sObjectMgr.
Referenced by Abandon(), Escalate(), OnPlayerOnlineState(), ShowMOTD(), and Update().
TicketChatIncoming()
bool GMTicketMgr::TicketChatIncoming (GMTicket * ticket, Player * player, WorldSession * gm, const std::string & message, bool addon = false) static
Definition at line 579 of file GMTicketMgr.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_AFK, CHAT_MSG_DND, CHAT_MSG_WHISPER, CHAT_MSG_WHISPER_INFORM, CHAT_TAG_GM, ByteBuffer::clear(), GMTicket::GetAssigneeGuid(), GMTicket::GetAssigneeName(), GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), Player::GetChatTag(), GMTicket::GetIdTag(), WorldSession::GetPlayer(), Player::GetSession(), Object::IsInWorld(), LANG_ADDON, LANG_UNIVERSAL, WorldSession::SendPacket(), and GMTicket::UpdateStatsChat().
Referenced by HookGMTicketWhisper().
TicketChatOutgoing()
bool GMTicketMgr::TicketChatOutgoing (GMTicket * ticket, WorldSession * gm, Player * player, const std::string & message, bool addon = false) static
Definition at line 624 of file GMTicketMgr.cpp.
References Player::autoReplyMsg, ChatHandler::BuildChatPacket(), CHAT_MSG_AFK, CHAT_MSG_DND, CHAT_MSG_WHISPER, CHAT_MSG_WHISPER_INFORM, CHAT_TAG_GM, CHAT_TAG_NONE, ByteBuffer::clear(), GMTicket::GetAssigneeGuid(), GMTicket::GetAssigneeName(), GMTicket::GetAuthorGuid(), GMTicket::GetAuthorName(), Player::GetChatTag(), GMTicket::GetIdTag(), WorldSession::GetPlayer(), Player::GetSession(), Player::isAFK(), Player::isDND(), Object::IsInWorld(), LANG_ADDON, LANG_UNIVERSAL, WorldSession::SendPacket(), and GMTicket::UpdateStatsChat().
Referenced by HookGMTicketWhisper(), and Whisper().
Update()
GMTicketMgr::CommandResult GMTicketMgr::Update (GMTicket * ticket, const std::string & text)
Definition at line 1096 of file GMTicketMgr.cpp.
References COMMAND_RESULT_SUCCESS, COMMAND_RESULT_TICKET_NOT_FOUND, GMTicket::Compare(), GMTicket::GetAuthorGuid(), GMTicket::GetIdTag(), GMTicket::GetText(), GMTICKET_STATUS_UPDATED, GMTICKETMGR_CHAT_UPDATED, GMTicket::IsEscalated(), GMTicket::IsOpen(), LANG_TICKET_BROADCAST_DEESCALATION, m_list, Save(), GMTicket::SetUpdated(), SMSG_GM_TICKET_STATUS_UPDATE, sObjectMgr, sWorld, and TicketChatAlert().
UpdateTicketQueueStats()
void GMTicketMgr::UpdateTicketQueueStats (GMTicket & closed, time_t when) private
Definition at line 1345 of file GMTicketMgr.cpp.
References GMTicket::GetCreatedAt(), GetDaysPassed(), GetTicketAgeDays(), m_currentTicketCountClosed, m_list, m_statsAverageResolutionDays, m_statsCurrentTotalResolutionDays, m_statsOldestTicketAgeDays, m_statsOldestTicketAgeLastUpdate, MANGOS_ASSERT, and UpdateTicketQueueTimers().
Referenced by Close().
UpdateTicketQueueTimers()
void GMTicketMgr::UpdateTicketQueueTimers (GMTicket * except = nullptr) const inline private
Definition at line 1366 of file GMTicketMgr.cpp.
References GMTicket::GetAuthorGuid(), GMTICKET_STATUS_UPDATED, GMTicket::IsEscalated(), GMTicket::IsOpen(), GMTicket::IsSeen(), m_tickets, SMSG_GM_TICKET_STATUS_UPDATE, and sObjectMgr.
Referenced by UpdateTicketQueueStats().
Whisper()
GMTicketMgr::CommandResult GMTicketMgr::Whisper (GMTicket * ticket, const std::string & message, WorldSession * session = nullptr)
Definition at line 1123 of file GMTicketMgr.cpp.
References CanWhisper(), COMMAND_RESULT_PLAYER_OFFLINE, COMMAND_RESULT_SUCCESS, GMTicket::GetAssigneeName(), GMTicket::GetAuthorGuid(), GMTicket::GetIdTag(), Object::GetObjectGuid(), WorldSession::GetPlayer(), WorldSession::GetSecurity(), Player::GetSession(), GMTICKET_STATUS_UPDATED, GMTicket::IsAssigned(), LANG_TICKET_BROADCAST_ASSIGNMENT, Save(), WorldSession::SendGMTicketResult(), GMTicket::SetAnswered(), GMTicket::SetAssignee(), SMSG_GM_TICKET_STATUS_UPDATE, sObjectMgr, sWorld, and TicketChatOutgoing().
Field Documentation
m_currentTicketCountClosed
uint32 GMTicketMgr::m_currentTicketCountClosed = 0 private
Definition at line 312 of file GMTicketMgr.h.
Referenced by Close(), ShowMOTD(), and UpdateTicketQueueStats().
m_currentTicketCountOpen
uint32 GMTicketMgr::m_currentTicketCountOpen = 0 private
Definition at line 311 of file GMTicketMgr.h.
Referenced by Abandon(), Add(), Close(), Recycle(), Remove(), RemoveAll(), and ShowMOTD().
m_lastTicketId
uint32 GMTicketMgr::m_lastTicketId = 0 private
Definition at line 310 of file GMTicketMgr.h.
Referenced by GenerateTicketId(), and LoadGMTickets().
m_list
GMTicketList GMTicketMgr::m_list private
Definition at line 308 of file GMTicketMgr.h.
Referenced by Add(), Escalate(), LoadGMTickets(), PrintTicketList(), Read(), Recycle(), Remove(), RemoveAll(), ShowMOTD(), Update(), and UpdateTicketQueueStats().
m_statsAverageResolutionDays
float GMTicketMgr::m_statsAverageResolutionDays = 0 private
Definition at line 315 of file GMTicketMgr.h.
Referenced by GetAverageResolutionDays(), and UpdateTicketQueueStats().
m_statsCurrentTotalResolutionDays
float GMTicketMgr::m_statsCurrentTotalResolutionDays = 0 private
Definition at line 316 of file GMTicketMgr.h.
Referenced by UpdateTicketQueueStats().
m_statsOldestTicketAgeDays
float GMTicketMgr::m_statsOldestTicketAgeDays = -1 private
Definition at line 318 of file GMTicketMgr.h.
Referenced by GetOldestTicketAgeDays(), and UpdateTicketQueueStats().
m_statsOldestTicketAgeLastUpdate
time_t GMTicketMgr::m_statsOldestTicketAgeLastUpdate = 0 private
Definition at line 319 of file GMTicketMgr.h.
Referenced by GetOldestTicketAgeLastUpdateDays(), and UpdateTicketQueueStats().
m_status
GMTicketSystemStatus GMTicketMgr::m_status private
Definition at line 305 of file GMTicketMgr.h.
Referenced by GetSystemStatus(), GMTicketMgr(), and SetSystemStatus().
m_tickets
GMTicketMap GMTicketMgr::m_tickets private
Definition at line 307 of file GMTicketMgr.h.
Referenced by Add(), GetTicketById(), GetTicketByPlayer(), GetTicketCount(), Recycle(), Remove(), RemoveAll(), SetSystemStatus(), and UpdateTicketQueueTimers().
The documentation for this class was generated from the following files:
GMTicketMgr.h
GMTicketMgr.cpp