CMaNGOS_WoTLK: ObjectMgr Class Reference
ObjectMgr Class Reference
#include <ObjectMgr.h>
Public Types
typedef std::unordered_map< uint32, Item * > ItemMap
typedef std::unordered_map< uint32, Group * > GroupMap
typedef std::unordered_map< uint32, ArenaTeam * > ArenaTeamMap
typedef std::unordered_map< uint32, Quest * > QuestMap
typedef std::unordered_map< uint32, AreaTrigger > AreaTriggerMap
typedef std::unordered_map< uint32, RepRewardRate > RepRewardRateMap
typedef std::unordered_map< uint32, ReputationOnKillEntry > RepOnKillMap
typedef std::unordered_map< uint32, RepSpilloverTemplate > RepSpilloverTemplateMap
typedef std::unordered_map< uint32, PointOfInterest > PointOfInterestMap
typedef std::string NpcTextArray[MAX_GOSSIP_TEXT_OPTIONS]
Public Member Functions
ObjectMgr ()
~ObjectMgr ()
std::unordered_map< uint32, std::vector< uint32 > > const & GetCreatureSpawnEntry () const
std::vector< uint32 > LoadGameobjectInfo ()
void PackGroupIds ()
Group * GetGroupById (uint32 id) const
void AddGroup (Group *group)
void RemoveGroup (Group *group)
GroupMap::iterator GetGroupMapBegin ()
GroupMap::iterator GetGroupMapEnd ()
ArenaTeam * GetArenaTeamById (uint32 arenateamid) const
ArenaTeam * GetArenaTeamByName (const std::string &arenateamname) const
ArenaTeam * GetArenaTeamByCaptain (ObjectGuid guid) const
void AddArenaTeam (ArenaTeam *arenaTeam)
void RemoveArenaTeam (uint32 Id)
ArenaTeamMap::iterator GetArenaTeamMapBegin ()
ArenaTeamMap::iterator GetArenaTeamMapEnd ()
CreatureModelInfo const * GetCreatureModelRandomGender (uint32 display_id) const
uint32 GetCreatureModelAlternativeModel (uint32 modelId) const
PetLevelInfo const * GetPetLevelInfo (uint32 creature_id, uint32 level) const
PlayerClassInfo const * GetPlayerClassInfo (uint32 class_) const
void GetPlayerClassLevelInfo (uint32 class_, uint32 level, PlayerClassLevelInfo *info) const
PlayerInfo const * GetPlayerInfo (uint32 race, uint32 class_) const
void GetPlayerLevelInfo (uint32 race, uint32 class_, uint32 level, PlayerLevelInfo *info) const
ObjectGuid GetPlayerGuidByName (std::string name) const
int32 GetPlayerMapIdByGUID (ObjectGuid const &guid) const
bool GetPlayerNameByGUID (ObjectGuid guid, std::string &name) const
Team GetPlayerTeamByGUID (ObjectGuid guid) const
uint32 GetPlayerAccountIdByGUID (ObjectGuid guid) const
uint32 GetPlayerAccountIdByPlayerName (const std::string &name) const
bool AddTaxiShortcut (const TaxiPathEntry *path, uint32 lengthTakeoff, uint32 lengthLanding)
bool GetTaxiShortcut (uint32 pathid, TaxiShortcutData &data)
void LoadTaxiShortcuts ()
uint32 GetNearestTaxiNode (float x, float y, float z, uint32 mapid, Team team) const
void GetTaxiPath (uint32 source, uint32 destination, uint32 &path, uint32 &cost) const
uint32 GetTaxiMountDisplayId (uint32 id, Team team) const
Quest const * GetQuestTemplate (uint32 quest_id) const
QuestMap const & GetQuestTemplates () const
uint32 GetQuestForAreaTrigger (uint32 Trigger_ID) const
bool IsTavernAreaTrigger (uint32 Trigger_ID) const
bool IsGameObjectForQuests (uint32 entry) const
GossipText const * GetGossipText (uint32 Text_ID) const
QuestgiverGreeting const * GetQuestgiverGreetingData (uint32 entry, uint32 type) const
TrainerGreeting const * GetTrainerGreetingData (uint32 entry) const
AreaTrigger const * GetAreaTrigger (uint32 trigger) const
AccessRequirement const * GetAccessRequirement (uint32 mapid, Difficulty difficulty) const
std::vector< uint32 > const * GetAllRandomEntries (std::unordered_map< uint32, std::vector< uint32 >> const &map, uint32 dbguid) const
uint32 GetRandomEntry (std::unordered_map< uint32, std::vector< uint32 >> const &map, uint32 dbguid) const
uint32 GetRandomGameObjectEntry (uint32 dbguid) const
std::vector< uint32 > const * GetAllRandomGameObjectEntries (uint32 dbguid) const
uint32 GetRandomCreatureEntry (uint32 dbguid) const
std::vector< uint32 > const * GetAllRandomCreatureEntries (uint32 dbguid) const
AreaTrigger const * GetGoBackTrigger (uint32 map_id) const
AreaTrigger const * GetMapEntranceTrigger (uint32 Map) const
Searches for the areatrigger which teleports players to the given map TODO: Requirements should be propably Map bound not Areatrigger bound.
RepRewardRate const * GetRepRewardRate (uint32 factionId) const
ReputationOnKillEntry const * GetReputationOnKillEntry (uint32 id) const
RepSpilloverTemplate const * GetRepSpilloverTemplate (uint32 factionId) const
PointOfInterest const * GetPointOfInterest (uint32 id) const
QuestPOIVector const * GetQuestPOIVector (uint32 questId)
void LoadArenaTeams ()
void LoadGroups ()
void LoadQuests ()
void LoadQuestRelations ()
void LoadGameobjectQuestRelations ()
void LoadGameobjectInvolvedRelations ()
void LoadCreatureQuestRelations ()
void LoadCreatureInvolvedRelations ()
bool LoadMangosStrings (DatabaseType &db, char const *table, int32 min_value, int32 max_value, bool extra_content)
bool LoadMangosStrings ()
void LoadCreatureLocales ()
void LoadCreatureTemplates ()
void LoadCreatures ()
void LoadCreatureAddons ()
void LoadCreatureClassLvlStats ()
void LoadCreatureConditionalSpawn ()
void LoadCreatureSpawnDataTemplates ()
void LoadCreatureSpawnEntry ()
void LoadCreatureModelInfo ()
void LoadCreatureModelRace ()
void LoadEquipmentTemplates ()
void LoadGameObjectLocales ()
void LoadGameObjects ()
void LoadGameObjectSpawnEntry ()
void LoadGameObjectTemplateAddons ()
void LoadItemPrototypes ()
void LoadItemConverts ()
void LoadItemExpireConverts ()
void LoadItemRequiredTarget ()
void LoadItemLocales ()
void LoadQuestLocales ()
void LoadGossipTextLocales ()
void LoadQuestgiverGreeting ()
void LoadQuestgiverGreetingLocales ()
void LoadTrainerGreetings ()
void LoadTrainerGreetingLocales ()
void LoadPageTextLocales ()
void LoadGossipMenuItemsLocales ()
void LoadPointOfInterestLocales ()
void LoadInstanceEncounters ()
void LoadInstanceTemplate ()
void LoadWorldTemplate ()
void LoadWorldStateNames ()
void LoadConditions ()
void LoadMailLevelRewards ()
void LoadGossipText ()
void LoadAreaTriggerTeleports ()
void LoadAccessRequirements ()
void LoadQuestAreaTriggers ()
void LoadTavernAreaTriggers ()
void LoadGameObjectForQuests ()
void LoadPageTexts ()
void LoadPlayerInfo ()
void LoadPetLevelInfo ()
void LoadExplorationBaseXP ()
void LoadPetNames ()
void LoadPetNumber ()
void LoadCorpses ()
void LoadFishingBaseSkillLevel ()
void LoadReputationRewardRate ()
void LoadReputationOnKill ()
void LoadReputationSpilloverTemplate ()
void LoadPointsOfInterest ()
void LoadQuestPOI ()
void LoadNPCSpellClickSpells ()
void LoadSpellTemplate ()
void CheckSpellCones ()
void LoadCreatureTemplateSpells (std::shared_ptr< CreatureSpellListContainer > container)
void LoadCreatureCooldowns ()
void LoadCreatureImmunities ()
std::shared_ptr< CreatureSpellListContainer > LoadCreatureSpellLists ()
void LoadSpawnGroups ()
void LoadGameTele ()
void LoadNpcGossips ()
void LoadGossipMenus ()
void LoadDungeonEncounters ()
void LoadAreaGroups ()
void LoadSQLDBCs ()
void LoadVendorTemplates ()
void LoadVendors ()
void LoadTrainerTemplates ()
void LoadTrainers ()
void LoadBroadcastText ()
void LoadBroadcastTextLocales ()
std::tuple< std::shared_ptr< std::map< int32, UnitConditionEntry > >, std::shared_ptr< std::map< int32, WorldStateExpressionEntry > >, std::shared_ptr< std::map< int32, CombatConditionEntry > > > LoadConditionsAndExpressions ()
std::shared_ptr< std::map< int32, UnitConditionEntry > > GetUnitConditions ()
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > GetWorldStateExpressions ()
std::shared_ptr< std::map< int32, CombatConditionEntry > > GetCombatConditions ()
void LoadActiveEntities (Map *_map)
void LoadVehicleAccessory ()
void LoadVehicleSeatParameters ()
std::string GeneratePetName (uint32 entry)
uint32 GetBaseXP (uint32 level) const
uint32 GetXPForLevel (uint32 level) const
uint32 GetXPForPetLevel (uint32 level) const
uint32 GetMaxLevelForExpansion (uint32 expansion) const
int32 GetFishingBaseSkillLevel (uint32 entry) const
void ReturnOrDeleteOldMails (bool serverUp)
void SetHighestGuids ()
uint32 GetFirstTemporaryCreatureLowGuid () const
uint32 GetFirstTemporaryGameObjectLowGuid () const
uint32 GenerateStaticCreatureLowGuid ()
uint32 GenerateStaticGameObjectLowGuid ()
uint32 GeneratePlayerLowGuid ()
uint32 GenerateItemLowGuid ()
uint32 GenerateCorpseLowGuid ()
uint32 GenerateInstanceLowGuid ()
uint32 GenerateGroupLowGuid ()
uint32 GenerateArenaTeamId ()
uint32 GenerateAuctionID ()
uint64 GenerateEquipmentSetGuid ()
uint32 GenerateGuildId ()
uint32 GenerateMailID ()
uint32 GeneratePetNumber ()
MailLevelReward const * GetMailLevelReward (uint32 level, uint32 raceMask)
CreatureDataPair const * GetCreatureDataPair (uint32 guid) const
CreatureData const * GetCreatureData (uint32 guid) const
CreatureSpawnTemplate const * GetCreatureSpawnTemplate (uint32 entry) const
CreatureData * GetCreatureData (uint32 guid)
CreatureData & NewOrExistCreatureData (uint32 guid)
void DeleteCreatureData (uint32 guid)
template<typename Worker >
void DoCreatureData (Worker &worker) const
CreatureLocale const * GetCreatureLocale (uint32 entry) const
void GetCreatureLocaleStrings (uint32 entry, int32 loc_idx, char const **namePtr, char const **subnamePtr=nullptr) const
GameObjectLocale const * GetGameObjectLocale (uint32 entry) const
ItemLocale const * GetItemLocale (uint32 entry) const
void GetItemLocaleStrings (uint32 entry, int32 loc_idx, std::string *namePtr, std::string *descriptionPtr=nullptr) const
QuestLocale const * GetQuestLocale (uint32 entry) const
void GetQuestLocaleStrings (uint32 entry, int32 loc_idx, std::string *titlePtr) const
NpcTextLocale const * GetNpcTextLocale (uint32 entry) const
BroadcastText const * GetBroadcastText (uint32 entry) const
void GetNpcTextLocaleStringsAll (uint32 entry, int32 loc_idx, NpcTextArray *text0_Ptr, NpcTextArray *text1_Ptr) const
void GetNpcTextLocaleStrings0 (uint32 entry, int32 loc_idx, std::string *text0_0_Ptr, std::string *text1_0_Ptr) const
void GetQuestgiverGreetingLocales (uint32 entry, uint32 type, int32 loc_idx, std::string *titlePtr) const
QuestgiverGreetingLocale const * GetQuestgiverGreetingLocale (uint32 entry, uint32 type) const
void GetTrainerGreetingLocales (uint32 entry, int32 loc_idx, std::string *titlePtr) const
TrainerGreetingLocale const * GetTrainerGreetingLocale (uint32 entry) const
PageTextLocale const * GetPageTextLocale (uint32 entry) const
GossipMenuItemsLocale const * GetGossipMenuItemsLocale (uint32 entry) const
PointOfInterestLocale const * GetPointOfInterestLocale (uint32 poi_id) const
GameObjectDataPair const * GetGODataPair (uint32 guid) const
GameObjectData const * GetGOData (uint32 guid) const
GameObjectTemplateAddon const * GetGOTemplateAddon (uint32 entry) const
GameObjectData & NewGOData (uint32 guid)
void DeleteGOData (uint32 guid)
template<typename Worker >
void DoGOData (Worker &worker) const
MangosStringLocale const * GetMangosStringLocale (int32 entry) const
uint32 GetLoadedStringsCount (int32 minEntry) const
const char * GetMangosString (int32 entry, int locale_idx) const
const char * GetMangosStringForDbcLocale (int32 entry) const
int GetDbc2StorageLocaleIndex () const
void SetDbc2StorageLocaleIndex (LocaleConstant loc)
int GetStorageLocaleIndexFor (LocaleConstant loc)
int GetOrNewStorageLocaleIndexFor (LocaleConstant loc)
CellObjectGuids const & GetCellObjectGuids (uint16 mapid, uint8 spawnMode, uint32 cell_id)
void AddCreatureToGrid (uint32 guid, CreatureData const *data)
void RemoveCreatureFromGrid (uint32 guid, CreatureData const *data)
void AddGameobjectToGrid (uint32 guid, GameObjectData const *data)
void RemoveGameobjectFromGrid (uint32 guid, GameObjectData const *data)
void AddCorpseCellData (uint32 mapid, uint32 cellid, uint32 player_guid, uint32 instance)
void DeleteCorpseCellData (uint32 mapid, uint32 cellid, uint32 player_guid)
void LoadReservedPlayersNames ()
bool IsReservedName (const std::string &name) const
bool IsConditionSatisfied (uint32 conditionId, WorldObject const *target, Map const *map, WorldObject const *source, ConditionSource conditionSourceType) const
bool IsWorldStateExpressionSatisfied (int32 expressionId, Map const *map)
bool IsUnitConditionSatisfied (int32 conditionId, Unit const *source, Unit const *target)
bool IsCombatConditionSatisfied (int32 expressionId, Unit const *source, float range)
GameTele const * GetGameTele (uint32 id) const
GameTele const * GetGameTele (const std::string &name) const
GameTeleMap const & GetGameTeleMap () const
bool AddGameTele (GameTele &tele)
bool DeleteGameTele (const std::string &name)
uint32 GetNpcGossip (uint32 entry) const
TrainerSpellData const * GetNpcTrainerSpells (uint32 entry) const
TrainerSpellData const * GetNpcTrainerTemplateSpells (uint32 entry) const
VendorItemData const * GetNpcVendorItemList (uint32 entry) const
VendorItemData const * GetNpcVendorTemplateItemList (uint32 entry) const
void AddVendorItem (uint32 entry, uint32 item, uint32 maxcount, uint32 incrtime, uint32 extendedcost)
bool RemoveVendorItem (uint32 entry, uint32 item)
bool IsVendorItemValid (bool isTemplate, char const *tableName, uint32 vendor_entry, uint32 item_id, uint32 maxcount, uint32 incrtime, uint32 ExtendedCost, uint16 conditionId, Player *pl=nullptr) const
SpellClickInfoMapBounds GetSpellClickInfoMapBounds (uint32 creature_id) const
uint32 GetItemConvert (uint32 itemEntry, uint32 raceMask) const
uint32 GetItemExpireConvert (uint32 itemEntry) const
ItemRequiredTargetMapBounds GetItemRequiredTargetMapBounds (uint32 uiItemEntry) const
DungeonEncounterMapBounds GetDungeonEncounterBounds (uint32 creditEntry) const
DungeonEncounterMapBounds GetDungeonEncounterBoundsByMap (uint32 mapId) const
bool IsEncounter (uint32 creditEntry, uint32 mapId) const
bool IsExistingGossipMenuId (uint32 menuId)
GossipMenusMapBounds GetGossipMenusMapBounds (uint32 uiMenuId) const
GossipMenuItemsMapBounds GetGossipMenuItemsMapBounds (uint32 uiMenuId) const
ExclusiveQuestGroupsMapBounds GetExclusiveQuestGroupsMapBounds (int32 groupId) const
QuestRelationsMapBounds GetCreatureQuestRelationsMapBounds (uint32 entry) const
QuestRelationsMapBounds GetCreatureQuestInvolvedRelationsMapBounds (uint32 entry) const
QuestRelationsMapBounds GetGOQuestRelationsMapBounds (uint32 entry) const
QuestRelationsMapBounds GetGOQuestInvolvedRelationsMapBounds (uint32 entry) const
QuestRelationsMap & GetCreatureQuestRelationsMap ()
std::pair< uint32, uint32 > GetCreatureCooldownRange (uint32 entry, uint32 spellId) const
bool GetCreatureCooldown (uint32 entry, uint32 spellId, uint32 cooldown) const
void AddCreatureCooldown (uint32 entry, uint32 spellId, uint32 min, uint32 max)
uint32 GetModelForRace (uint32 sourceModelId, uint32 racemask)
CreatureClassLvlStats const * GetCreatureClassLvlStats (uint32 level, uint32 unitClass, int32 expansion) const
: Data returned is used to compute health, mana, armor, damage of creatures.
CreatureImmunityVector const * GetCreatureImmunitySet (uint32 entry, uint32 setId) const
CreatureSpellList * GetCreatureSpellList (uint32 Id) const
std::shared_ptr< CreatureSpellListContainer > GetCreatureSpellListContainer ()
std::shared_ptr< SpawnGroupEntryContainer > GetSpawnGroupContainer ()
bool HasWorldStateName (int32 Id) const
WorldStateName * GetWorldStateName (int32 Id)
std::vector< std::pair< TypeID, uint32 > > const & GetDbGuidsForTransport (uint32 mapId) const
VehicleSeatParameters const * GetVehicleSeatParameters (uint32 seatEntry) const
Static Public Member Functions
static GameObjectInfo const * GetGameObjectInfo (uint32 id)
Wrapper for sGOStorage.LookupEntry.
static Player * GetPlayer (const char *name)
Wrapper for ObjectAccessor::FindPlayerByName.
static Player * GetPlayer (ObjectGuid guid, bool inWorld=true)
Wrapper for ObjectAccessor::FindPlayer.
static CreatureInfo const * GetCreatureTemplate (uint32 id)
Wrapper for sCreatureStorage.LookupEntry.
static CreatureModelInfo const * GetCreatureModelInfo (uint32 modelid)
Wrapper for sCreatureModelStorage.LookupEntry.
static EquipmentInfo const * GetEquipmentInfo (uint32 entry)
Wrapper for sEquipmentStorage.LookupEntry.
static CreatureDataAddon const * GetCreatureAddon (uint32 lowguid)
Wrapper for sCreatureDataAddonStorage.LookupEntry.
static CreatureDataAddon const * GetCreatureTemplateAddon (uint32 entry)
Wrapper for sCreatureInfoAddonStorage.LookupEntry.
static ItemPrototype const * GetItemPrototype (uint32 id)
Wrapper for sItemStorage.LookupEntry.
static InstanceTemplate const * GetInstanceTemplate (uint32 map)
Wrapper for sInstanceTemplate.LookupEntry.
static WorldTemplate const * GetWorldTemplate (uint32 map)
Wrapper for sWorldTemplate.LookupEntry.
static CreatureConditionalSpawn const * GetCreatureConditionalSpawn (uint32 lowguid)
Wrapper for sCreatureConditionalSpawnStore.LookupEntry.
static bool CheckPublicMessageLanguage (const std::string &message)
static uint8 CheckPlayerName (const std::string &name, bool create=false)
static PetNameInvalidReason CheckPetName (const std::string &name)
static bool IsValidCharterName (const std::string &name)
static bool CheckDeclinedNames (const std::wstring &mainpart, DeclinedName const &names)
Protected Types
typedef std::unordered_map< uint32, GossipText > GossipTextMap
typedef std::unordered_map< uint32, uint32 > QuestAreaTriggerMap
typedef std::set< uint32 > TavernAreaTriggerSet
typedef std::set< uint32 > GameObjectForQuestSet
typedef std::multimap< uint32, CreatureModelRace > CreatureModelRaceMap
typedef std::pair< CreatureModelRaceMap::const_iterator, CreatureModelRaceMap::const_iterator > CreatureModelRaceMapBounds
typedef std::set< std::wstring > ReservedNamesMap
typedef std::vector< LocaleConstant > LocalForIndex
Protected Attributes
uint8 m_Dbc2StorageLocaleIndex
IdGenerator< uint32 > m_ArenaTeamIds
IdGenerator< uint32 > m_AuctionIds
IdGenerator< uint64 > m_EquipmentSetIds
IdGenerator< uint32 > m_GuildIds
IdGenerator< uint32 > m_MailIds
IdGenerator< uint32 > m_PetNumbers
uint32 m_FirstTemporaryCreatureGuid
uint32 m_FirstTemporaryGameObjectGuid
ObjectGuidGenerator< HIGHGUID_UNIT > m_StaticCreatureGuids
ObjectGuidGenerator< HIGHGUID_GAMEOBJECT > m_StaticGameObjectGuids
ObjectGuidGenerator< HIGHGUID_PLAYER > m_CharGuids
ObjectGuidGenerator< HIGHGUID_ITEM > m_ItemGuids
ObjectGuidGenerator< HIGHGUID_CORPSE > m_CorpseGuids
ObjectGuidGenerator< HIGHGUID_INSTANCE > m_InstanceGuids
ObjectGuidGenerator< HIGHGUID_GROUP > m_GroupGuids
QuestMap mQuestTemplates
GroupMap mGroupMap
ArenaTeamMap mArenaTeamMap
QuestAreaTriggerMap mQuestAreaTriggerMap
TavernAreaTriggerSet mTavernAreaTriggerSet
GameObjectForQuestSet mGameObjectForQuestSet
GossipTextMap mGossipText
AreaTriggerMap mAreaTriggers
RepRewardRateMap m_RepRewardRateMap
RepOnKillMap mRepOnKill
RepSpilloverTemplateMap m_RepSpilloverTemplateMap
GossipMenusMap m_mGossipMenusMap
GossipMenuItemsMap m_mGossipMenuItemsMap
std::unordered_map< uint32, std::vector< uint32 > > m_creatureSpawnEntryMap
std::unordered_map< uint32, std::vector< uint32 > > m_gameobjectSpawnEntryMap
std::unordered_map< uint32, GameObjectTemplateAddon > m_gameobjectAddonTemplates
PointOfInterestMap mPointsOfInterest
QuestPOIMap mQuestPOIMap
ReservedNamesMap m_ReservedNames
TaxiShortcutMap m_TaxiShortcutMap
GameTeleMap m_GameTeleMap
SpellClickInfoMap mSpellClickInfoMap
ItemConvertMap m_ItemConvert
ItemConvertMap m_ItemExpireConvert
ItemRequiredTargetMap m_ItemRequiredTarget
LocalForIndex m_LocalForIndex
ExclusiveQuestGroupsMap m_ExclusiveQuestGroups
QuestRelationsMap m_CreatureQuestRelations
QuestRelationsMap m_CreatureQuestInvolvedRelations
QuestRelationsMap m_GOQuestRelations
QuestRelationsMap m_GOQuestInvolvedRelations
Private Types
typedef std::map< uint32, PetLevelInfo * > PetLevelInfoMap
typedef std::vector< uint32 > PlayerXPperLevel
typedef std::map< uint32, uint32 > BaseXPMap
typedef std::map< uint32, int32 > FishingBaseSkillMap
typedef std::map< uint32, std::vector< std::string > > HalfNameMap
typedef std::multimap< uint32, uint32 > ActiveObjectGuidsOnMap
Private Member Functions
void LoadCreatureAddons (SQLStorage &creatureaddons, char const *entryName, char const *comment)
void ConvertCreatureAddonAuras (CreatureDataAddon *addon, char const *table, char const *guidEntryStr)
void LoadQuestRelationsHelper (QuestRelationsMap &map, char const *table)
void LoadVendors (char const *tableName, bool isTemplates)
void LoadTrainers (char const *tableName, bool isTemplates)
void LoadGossipMenu (std::set< uint32 > &gossipScriptSet)
void LoadGossipMenuItems (std::set< uint32 > &gossipScriptSet)
void BuildPlayerLevelInfo (uint8 race, uint8 _class, uint8 level, PlayerLevelInfo *info) const
Private Attributes
MailLevelRewardMap m_mailLevelRewardMap
PetLevelInfoMap petInfo
PlayerClassInfo playerClassInfo [MAX_CLASSES]
PlayerInfo playerInfo [MAX_RACES][MAX_CLASSES]
PlayerXPperLevel mPlayerXPperLevel
BaseXPMap mBaseXPTable
FishingBaseSkillMap mFishingBaseForArea
HalfNameMap PetHalfName0
HalfNameMap PetHalfName1
CreatureClassLvlStats m_creatureClassLvlStats [DEFAULT_MAX_CREATURE_LEVEL+1][MAX_CREATURE_CLASS][MAX_EXPANSION+1]
MapObjectGuids mMapObjectGuids
ActiveObjectGuidsOnMap m_activeCreatures
ActiveObjectGuidsOnMap m_activeGameObjects
CreatureSpawnTemplateMap m_creatureSpawnTemplateMap
CreatureDataMap mCreatureDataMap
CreatureLocaleMap mCreatureLocaleMap
std::unordered_map< uint32, std::unordered_map< uint32, std::pair< uint32, uint32 > > > m_creatureCooldownMap
GameObjectDataMap mGameObjectDataMap
GameObjectLocaleMap mGameObjectLocaleMap
ItemLocaleMap mItemLocaleMap
QuestLocaleMap mQuestLocaleMap
NpcTextLocaleMap mNpcTextLocaleMap
PageTextLocaleMap mPageTextLocaleMap
MangosStringLocaleMap mMangosStringLocaleMap
std::map< int32, uint32 > m_loadedStringCount
GossipMenuItemsLocaleMap mGossipMenuItemsLocaleMap
PointOfInterestLocaleMap mPointOfInterestLocaleMap
DungeonEncounterMap m_DungeonEncounters
DungeonEncounterMap m_DungeonEncountersByMap
QuestgiverGreetingMap m_questgiverGreetingMap [QUESTGIVER_TYPE_MAX]
QuestgiverGreetingLocaleMap m_questgiverGreetingLocaleMap [QUESTGIVER_TYPE_MAX]
TrainerGreetingMap m_trainerGreetingMap
TrainerGreetingLocaleMap m_trainerGreetingLocaleMap
CreatureModelRaceMap m_mCreatureModelRaceMap
CacheNpcTextIdMap m_mCacheNpcTextIdMap
CacheVendorItemMap m_mCacheVendorTemplateItemMap
CacheVendorItemMap m_mCacheVendorItemMap
CacheTrainerSpellMap m_mCacheTrainerTemplateSpellMap
CacheTrainerSpellMap m_mCacheTrainerSpellMap
BroadcastTextMap m_broadcastTextMap
CreatureImmunityContainer m_creatureImmunities
std::shared_ptr< CreatureSpellListContainer > m_spellListContainer
std::shared_ptr< SpawnGroupEntryContainer > m_spawnGroupContainer
std::map< int32, WorldStateName > m_worldStateNames
std::unique_ptr< UnitConditionMgr > m_unitConditionMgr
std::unique_ptr< WorldStateExpressionMgr > m_worldStateExpressionMgr
std::unique_ptr< CombatConditionMgr > m_combatConditionMgr
std::unordered_map< uint32, AccessRequirement > m_accessRequirements
std::map< uint32, uint32 > m_transportMaps
std::map< uint32, std::vector< std::pair< TypeID, uint32 > > > m_guidsForMap
std::map< uint32, VehicleSeatParameters > m_seatParameters
Friends
class PlayerDumpReader
Detailed Description
Definition at line 505 of file ObjectMgr.h.
Member Typedef Documentation
ActiveObjectGuidsOnMap
typedef std::multimap<uint32 , uint32 > ObjectMgr::ActiveObjectGuidsOnMap private
Definition at line 1403 of file ObjectMgr.h.
AreaTriggerMap
typedef std::unordered_map<uint32, AreaTrigger> ObjectMgr::AreaTriggerMap
Definition at line 521 of file ObjectMgr.h.
ArenaTeamMap
typedef std::unordered_map<uint32, ArenaTeam*> ObjectMgr::ArenaTeamMap
Definition at line 517 of file ObjectMgr.h.
BaseXPMap
typedef std::map<uint32, uint32> ObjectMgr::BaseXPMap private
Definition at line 1393 of file ObjectMgr.h.
CreatureModelRaceMap
typedef std::multimap<uint32, CreatureModelRace> ObjectMgr::CreatureModelRaceMap protected
Definition at line 1318 of file ObjectMgr.h.
CreatureModelRaceMapBounds
typedef std::pair<CreatureModelRaceMap::const_iterator, CreatureModelRaceMap::const_iterator> ObjectMgr::CreatureModelRaceMapBounds protected
Definition at line 1319 of file ObjectMgr.h.
FishingBaseSkillMap
typedef std::map<uint32, int32> ObjectMgr::FishingBaseSkillMap private
Definition at line 1396 of file ObjectMgr.h.
GameObjectForQuestSet
typedef std::set<uint32> ObjectMgr::GameObjectForQuestSet protected
Definition at line 1316 of file ObjectMgr.h.
GossipTextMap
typedef std::unordered_map<uint32, GossipText> ObjectMgr::GossipTextMap protected
Definition at line 1313 of file ObjectMgr.h.
GroupMap
typedef std::unordered_map<uint32, Group*> ObjectMgr::GroupMap
Definition at line 515 of file ObjectMgr.h.
HalfNameMap
typedef std::map<uint32, std::vector<std::string> > ObjectMgr::HalfNameMap private
Definition at line 1399 of file ObjectMgr.h.
ItemMap
typedef std::unordered_map<uint32, Item*> ObjectMgr::ItemMap
Definition at line 513 of file ObjectMgr.h.
LocalForIndex
typedef std::vector<LocaleConstant> ObjectMgr::LocalForIndex protected
Definition at line 1359 of file ObjectMgr.h.
NpcTextArray
typedef std::string ObjectMgr::NpcTextArray[MAX_GOSSIP_TEXT_OPTIONS]
Definition at line 959 of file ObjectMgr.h.
PetLevelInfoMap
typedef std::map<uint32, PetLevelInfo*> ObjectMgr::PetLevelInfoMap private
Definition at line 1381 of file ObjectMgr.h.
PlayerXPperLevel
typedef std::vector<uint32> ObjectMgr::PlayerXPperLevel private
Definition at line 1390 of file ObjectMgr.h.
PointOfInterestMap
typedef std::unordered_map<uint32, PointOfInterest> ObjectMgr::PointOfInterestMap
Definition at line 527 of file ObjectMgr.h.
QuestAreaTriggerMap
typedef std::unordered_map<uint32, uint32> ObjectMgr::QuestAreaTriggerMap protected
Definition at line 1314 of file ObjectMgr.h.
QuestMap
typedef std::unordered_map<uint32, Quest*> ObjectMgr::QuestMap
Definition at line 519 of file ObjectMgr.h.
RepOnKillMap
typedef std::unordered_map<uint32, ReputationOnKillEntry> ObjectMgr::RepOnKillMap
Definition at line 524 of file ObjectMgr.h.
RepRewardRateMap
typedef std::unordered_map<uint32, RepRewardRate > ObjectMgr::RepRewardRateMap
Definition at line 523 of file ObjectMgr.h.
RepSpilloverTemplateMap
typedef std::unordered_map<uint32, RepSpilloverTemplate> ObjectMgr::RepSpilloverTemplateMap
Definition at line 525 of file ObjectMgr.h.
ReservedNamesMap
typedef std::set<std::wstring> ObjectMgr::ReservedNamesMap protected
Definition at line 1346 of file ObjectMgr.h.
TavernAreaTriggerSet
typedef std::set<uint32> ObjectMgr::TavernAreaTriggerSet protected
Definition at line 1315 of file ObjectMgr.h.
Constructor & Destructor Documentation
ObjectMgr()
ObjectMgr::ObjectMgr ()
Definition at line 155 of file ObjectMgr.cpp.
~ObjectMgr()
ObjectMgr::~ObjectMgr ()
Definition at line 171 of file ObjectMgr.cpp.
References m_mCacheTrainerSpellMap, m_mCacheVendorItemMap, m_mCacheVendorTemplateItemMap, mArenaTeamMap, MAX_CLASSES, mGroupMap, mQuestTemplates, petInfo, playerClassInfo, and playerInfo.
Member Function Documentation
AddArenaTeam()
void ObjectMgr::AddArenaTeam (ArenaTeam * arenaTeam)
Definition at line 10362 of file ObjectMgr.cpp.
References ArenaTeam::GetId(), and mArenaTeamMap.
Referenced by LoadArenaTeams().
AddCorpseCellData()
void ObjectMgr::AddCorpseCellData (uint32 mapid, uint32 cellid, uint32 player_guid, uint32 instance)
Definition at line 8593 of file ObjectMgr.cpp.
References CellObjectGuids::corpses, MAKE_PAIR32, and mMapObjectGuids.
AddCreatureCooldown()
void ObjectMgr::AddCreatureCooldown (uint32 entry, uint32 spellId, uint32 min, uint32 max)
Definition at line 10586 of file ObjectMgr.cpp.
References m_creatureCooldownMap.
AddCreatureToGrid()
void ObjectMgr::AddCreatureToGrid (uint32 guid, CreatureData const * data)
Definition at line 2246 of file ObjectMgr.cpp.
References MaNGOS::ComputeCellPair(), MAKE_PAIR32, CreatureData::mapid, mMapObjectGuids, CreatureData::posX, CreatureData::posY, CreatureData::spawnMask, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by LoadCreatures().
AddGameobjectToGrid()
void ObjectMgr::AddGameobjectToGrid (uint32 guid, GameObjectData const * data)
Definition at line 2609 of file ObjectMgr.cpp.
References MaNGOS::ComputeCellPair(), MAKE_PAIR32, GameObjectData::mapid, mMapObjectGuids, GameObjectData::posX, GameObjectData::posY, GameObjectData::spawnMask, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by LoadGameObjects().
AddGameTele()
bool ObjectMgr::AddGameTele (GameTele & tele)
Definition at line 9449 of file ObjectMgr.cpp.
References Database::escape_string(), m_GameTeleMap, GameTele::mapId, GameTele::name, GameTele::orientation, Database::PExecuteLog(), GameTele::position_x, GameTele::position_y, GameTele::position_z, Utf8toWStr(), GameTele::wnameLow, WorldDatabase, and wstrToLower().
AddGroup()
void ObjectMgr::AddGroup (Group * group)
Definition at line 10352 of file ObjectMgr.cpp.
References Group::GetId(), and mGroupMap.
Referenced by LoadGroups().
AddTaxiShortcut()
bool ObjectMgr::AddTaxiShortcut (const TaxiPathEntry * path, uint32 lengthTakeoff, uint32 lengthLanding)
Definition at line 6654 of file ObjectMgr.cpp.
References TaxiPathEntry::ID, TaxiShortcutData::lengthLanding, TaxiShortcutData::lengthTakeoff, and m_TaxiShortcutMap.
Referenced by LoadTaxiShortcuts().
AddVendorItem()
void ObjectMgr::AddVendorItem (uint32 entry, uint32 item, uint32 maxcount, uint32 incrtime, uint32 extendedcost)
Definition at line 10217 of file ObjectMgr.cpp.
References VendorItemData::AddItem(), m_mCacheVendorItemMap, Database::PExecuteLog(), and WorldDatabase.
BuildPlayerLevelInfo()
void ObjectMgr::BuildPlayerLevelInfo (uint8 race, uint8 _class, uint8 level, PlayerLevelInfo * info) const private
Definition at line 4458 of file ObjectMgr.cpp.
References CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, CONFIG_UINT32_MAX_PLAYER_LEVEL, PlayerInfo::levelInfo, playerInfo, STAT_AGILITY, STAT_INTELLECT, STAT_SPIRIT, STAT_STAMINA, STAT_STRENGTH, PlayerLevelInfo::stats, and sWorld.
Referenced by GetPlayerLevelInfo().
CheckDeclinedNames()
bool ObjectMgr::CheckDeclinedNames (const std::wstring & mainpart, DeclinedName const & names) static
Definition at line 9316 of file ObjectMgr.cpp.
References GetMainPartOfName(), MAX_DECLINED_NAME_CASES, DeclinedName::name, and Utf8toWStr().
Referenced by WorldSession::HandlePetRename(), and WorldSession::HandleSetPlayerDeclinedNamesOpcode().
CheckPetName()
PetNameInvalidReason ObjectMgr::CheckPetName (const std::string & name) static
Definition at line 8913 of file ObjectMgr.cpp.
References CONFIG_UINT32_MIN_PET_NAME, CONFIG_UINT32_STRICT_PET_NAMES, isValidString(), MAX_PET_NAME, PET_NAME_INVALID, PET_NAME_MIXED_LANGUAGES, PET_NAME_SUCCESS, PET_NAME_TOO_LONG, PET_NAME_TOO_SHORT, sWorld, and Utf8toWStr().
Referenced by WorldSession::HandlePetRename().
CheckPlayerName()
uint8 ObjectMgr::CheckPlayerName (const std::string & name, bool create = false) static
Definition at line 8875 of file ObjectMgr.cpp.
References CHAR_NAME_INVALID_CHARACTER, CHAR_NAME_MIXED_LANGUAGES, CHAR_NAME_SUCCESS, CHAR_NAME_TOO_LONG, CHAR_NAME_TOO_SHORT, CONFIG_UINT32_MIN_PLAYER_NAME, CONFIG_UINT32_STRICT_PLAYER_NAMES, isValidString(), MAX_PLAYER_NAME, sWorld, and Utf8toWStr().
Referenced by WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharRenameOpcode(), ChatHandler::HandlePDumpLoadCommand(), PlayerDumpReader::LoadDump(), and Player::LoadFromDB().
CheckPublicMessageLanguage()
bool ObjectMgr::CheckPublicMessageLanguage (const std::string & message) static
Definition at line 8835 of file ObjectMgr.cpp.
References GetRealmLanguageType(), isCyrillicCharacter(), isEastAsianCharacter(), isExtendedLatinCharacter(), LT_ANY, LT_CYRILLIC, LT_EAST_ASIA, LT_EXTENDEN_LATIN, and Utf8toWStr().
CheckSpellCones()
void ObjectMgr::CheckSpellCones ()
Definition at line 8395 of file ObjectMgr.cpp.
References SpellCone::coneAngle, SQLStorageBase::GetMaxEntry(), SQLStorage::LookupEntry(), sLog, sSpellCones, sSpellMgr, and sSpellTemplate.
ConvertCreatureAddonAuras()
void ObjectMgr::ConvertCreatureAddonAuras (CreatureDataAddon * addon, char const * table, char const * guidEntryStr) private
Definition at line 766 of file ObjectMgr.cpp.
References CreatureDataAddon::auras, SpellEntry::CastingTimeIndex, CreatureDataAddon::guidOrEntry, IsOnlySelfTargeting(), IsSpellAppliesAura(), IsSpellHaveAura(), IsSpellHaveEffect(), LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), sLog, SPELL_AURA_CONTROL_VEHICLE, SPELL_EFFECT_DUMMY, SPELL_EFFECT_SCRIPT_EFFECT, SPELL_EFFECT_TRIGGER_SPELL, sSpellCastTimesStore, and sSpellTemplate.
Referenced by LoadCreatureAddons().
DeleteCorpseCellData()
void ObjectMgr::DeleteCorpseCellData (uint32 mapid, uint32 cellid, uint32 player_guid)
Definition at line 8600 of file ObjectMgr.cpp.
References CellObjectGuids::corpses, MAKE_PAIR32, and mMapObjectGuids.
DeleteCreatureData()
void ObjectMgr::DeleteCreatureData (uint32 guid)
Definition at line 8564 of file ObjectMgr.cpp.
References GetCreatureData(), mCreatureDataMap, and RemoveCreatureFromGrid().
DeleteGameTele()
bool ObjectMgr::DeleteGameTele (const std::string & name)
Definition at line 9476 of file ObjectMgr.cpp.
References m_GameTeleMap, Database::PExecuteLog(), Utf8toWStr(), WorldDatabase, and wstrToLower().
DeleteGOData()
void ObjectMgr::DeleteGOData (uint32 guid)
Definition at line 8583 of file ObjectMgr.cpp.
References GetGOData(), mGameObjectDataMap, and RemoveGameobjectFromGrid().
DoCreatureData()
template<typename Worker > void ObjectMgr::DoCreatureData (Worker & worker) const inline
Definition at line 904 of file ObjectMgr.h.
References mCreatureDataMap.
DoGOData()
template<typename Worker > void ObjectMgr::DoGOData (Worker & worker) const inline
Definition at line 1021 of file ObjectMgr.h.
References mGameObjectDataMap.
GenerateArenaTeamId()
uint32 ObjectMgr::GenerateArenaTeamId () inline
Definition at line 852 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_ArenaTeamIds.
GenerateAuctionID()
uint32 ObjectMgr::GenerateAuctionID () inline
Definition at line 853 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_AuctionIds.
GenerateCorpseLowGuid()
uint32 ObjectMgr::GenerateCorpseLowGuid () inline
Definition at line 848 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), and m_CorpseGuids.
GenerateEquipmentSetGuid()
uint64 ObjectMgr::GenerateEquipmentSetGuid () inline
Definition at line 854 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_EquipmentSetIds.
GenerateGroupLowGuid()
uint32 ObjectMgr::GenerateGroupLowGuid () inline
Definition at line 850 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), and m_GroupGuids.
GenerateGuildId()
uint32 ObjectMgr::GenerateGuildId () inline
Definition at line 855 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_GuildIds.
GenerateInstanceLowGuid()
uint32 ObjectMgr::GenerateInstanceLowGuid () inline
Definition at line 849 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), and m_InstanceGuids.
GenerateItemLowGuid()
uint32 ObjectMgr::GenerateItemLowGuid () inline
Definition at line 847 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), and m_ItemGuids.
GenerateMailID()
uint32 ObjectMgr::GenerateMailID () inline
Definition at line 857 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_MailIds.
GeneratePetName()
std::string ObjectMgr::GeneratePetName (uint32 entry)
Definition at line 7786 of file ObjectMgr.cpp.
References CreatureInfo::Family, GetCreatureTemplate(), GetPetName(), CreatureInfo::Name, PetHalfName0, PetHalfName1, sWorld, and urand().
GeneratePetNumber()
uint32 ObjectMgr::GeneratePetNumber () inline
Definition at line 858 of file ObjectMgr.h.
References IdGenerator< T >::Generate(), and m_PetNumbers.
GeneratePlayerLowGuid()
uint32 ObjectMgr::GeneratePlayerLowGuid () inline
Definition at line 846 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), and m_CharGuids.
GenerateStaticCreatureLowGuid()
uint32 ObjectMgr::GenerateStaticCreatureLowGuid () inline
Definition at line 843 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), ObjectGuidGenerator< high >::GetNextAfterMaxUsed(), m_FirstTemporaryCreatureGuid, and m_StaticCreatureGuids.
GenerateStaticGameObjectLowGuid()
uint32 ObjectMgr::GenerateStaticGameObjectLowGuid () inline
Definition at line 844 of file ObjectMgr.h.
References ObjectGuidGenerator< high >::Generate(), ObjectGuidGenerator< high >::GetNextAfterMaxUsed(), m_FirstTemporaryGameObjectGuid, and m_StaticGameObjectGuids.
GetAccessRequirement()
AccessRequirement const * ObjectMgr::GetAccessRequirement (uint32 mapid, Difficulty difficulty) const
Definition at line 6333 of file ObjectMgr.cpp.
References m_accessRequirements, and MAKE_PAIR32.
GetAllRandomCreatureEntries()
std::vector<uint32> const* ObjectMgr::GetAllRandomCreatureEntries (uint32 dbguid) const inline
Definition at line 642 of file ObjectMgr.h.
References GetAllRandomEntries(), and m_creatureSpawnEntryMap.
Referenced by LoadSpawnGroups().
GetAllRandomEntries()
std::vector<uint32> const* ObjectMgr::GetAllRandomEntries (std::unordered_map< uint32, std::vector< uint32 >> const & map, uint32 dbguid) const inline
Definition at line 623 of file ObjectMgr.h.
Referenced by GetAllRandomCreatureEntries(), GetAllRandomGameObjectEntries(), and GetRandomEntry().
GetAllRandomGameObjectEntries()
std::vector<uint32> const* ObjectMgr::GetAllRandomGameObjectEntries (uint32 dbguid) const inline
Definition at line 639 of file ObjectMgr.h.
References GetAllRandomEntries(), and m_gameobjectSpawnEntryMap.
Referenced by LoadSpawnGroups().
GetAreaTrigger()
AreaTrigger const* ObjectMgr::GetAreaTrigger (uint32 trigger) const inline
Definition at line 613 of file ObjectMgr.h.
References mAreaTriggers.
GetArenaTeamByCaptain()
ArenaTeam * ObjectMgr::GetArenaTeamByCaptain (ObjectGuid guid) const
Definition at line 231 of file ObjectMgr.cpp.
References mArenaTeamMap.
GetArenaTeamById()
ArenaTeam * ObjectMgr::GetArenaTeamById (uint32 arenateamid) const
Definition at line 213 of file ObjectMgr.cpp.
References mArenaTeamMap.
GetArenaTeamByName()
ArenaTeam * ObjectMgr::GetArenaTeamByName (const std::string & arenateamname) const
Definition at line 222 of file ObjectMgr.cpp.
References mArenaTeamMap.
GetArenaTeamMapBegin()
ArenaTeamMap::iterator ObjectMgr::GetArenaTeamMapBegin () inline
Definition at line 545 of file ObjectMgr.h.
References mArenaTeamMap.
GetArenaTeamMapEnd()
ArenaTeamMap::iterator ObjectMgr::GetArenaTeamMapEnd () inline
Definition at line 546 of file ObjectMgr.h.
References mArenaTeamMap.
GetBaseXP()
uint32 ObjectMgr::GetBaseXP (uint32 level) const
Definition at line 7708 of file ObjectMgr.cpp.
References mBaseXPTable.
GetBroadcastText()
BroadcastText const* ObjectMgr::GetBroadcastText (uint32 entry) const inline
Definition at line 952 of file ObjectMgr.h.
References m_broadcastTextMap.
Referenced by LoadMangosStrings().
GetCellObjectGuids()
CellObjectGuids const& ObjectMgr::GetCellObjectGuids (uint16 mapid, uint8 spawnMode, uint32 cell_id) inline
Definition at line 1052 of file ObjectMgr.h.
References MAKE_PAIR32, and mMapObjectGuids.
GetCombatConditions()
std::shared_ptr< std::map< int32, CombatConditionEntry > > ObjectMgr::GetCombatConditions ()
Definition at line 8559 of file ObjectMgr.cpp.
References m_combatConditionMgr.
GetCreatureAddon()
CreatureDataAddon const * ObjectMgr::GetCreatureAddon (uint32 lowguid) static
Wrapper for sCreatureDataAddonStorage.LookupEntry.
Definition at line 4542 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureDataAddonStorage.
Referenced by Creature::GetCreatureAddon().
GetCreatureClassLvlStats()
CreatureClassLvlStats const * ObjectMgr::GetCreatureClassLvlStats (uint32 level, uint32 unitClass, int32 expansion) const
: Data returned is used to compute health, mana, armor, damage of creatures.
May be nullptr.
Parameters
uint32 level creature level
uint32 unitClass creature class, related to CLASSMASK_ALL_CREATURES
uint32 expansion creature expansion (we could have creature exp = 0 for wotlk as well as exp = 1 or exp = 2)
Returns
: CreatureClassLvlStats const* or nullptr
Description: GetCreatureClassLvlStats give fast access to creature stats data. FullName: ObjectMgr::GetCreatureClassLvlStats Access: public Qualifier: const
Definition at line 987 of file ObjectMgr.cpp.
References CreatureClassLvlStats::BaseDamage, CreatureClassLvlStats::BaseHealth, classToIndex, and m_creatureClassLvlStats.
GetCreatureConditionalSpawn()
CreatureConditionalSpawn const * ObjectMgr::GetCreatureConditionalSpawn (uint32 lowguid) static
Wrapper for sCreatureConditionalSpawnStore.LookupEntry.
Definition at line 4547 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureConditionalSpawnStore.
Referenced by Creature::GetCreatureConditionalSpawnEntry(), and LoadCreatures().
GetCreatureCooldown()
bool ObjectMgr::GetCreatureCooldown (uint32 entry, uint32 spellId, uint32 cooldown) const inline
Definition at line 1240 of file ObjectMgr.h.
References m_creatureCooldownMap, and urand().
GetCreatureCooldownRange()
std::pair<uint32, uint32> ObjectMgr::GetCreatureCooldownRange (uint32 entry, uint32 spellId) const inline
Definition at line 1226 of file ObjectMgr.h.
References m_creatureCooldownMap.
Referenced by LoadCreatureTemplateSpells().
GetCreatureData() [1/2]
CreatureData* ObjectMgr::GetCreatureData (uint32 guid) inline
Definition at line 892 of file ObjectMgr.h.
References mCreatureDataMap.
GetCreatureData() [2/2]
CreatureData const* ObjectMgr::GetCreatureData (uint32 guid) const inline
Definition at line 880 of file ObjectMgr.h.
References GetCreatureDataPair().
Referenced by DeleteCreatureData(), LoadNpcGossips(), and LoadSpawnGroups().
GetCreatureDataPair()
CreatureDataPair const* ObjectMgr::GetCreatureDataPair (uint32 guid) const inline
Definition at line 873 of file ObjectMgr.h.
References mCreatureDataMap.
Referenced by GetCreatureData().
GetCreatureImmunitySet()
CreatureImmunityVector const * ObjectMgr::GetCreatureImmunitySet (uint32 entry, uint32 setId) const
Definition at line 1014 of file ObjectMgr.cpp.
References m_creatureImmunities.
GetCreatureLocale()
CreatureLocale const* ObjectMgr::GetCreatureLocale (uint32 entry) const inline
Definition at line 911 of file ObjectMgr.h.
References mCreatureLocaleMap.
Referenced by GetCreatureLocaleStrings().
GetCreatureLocaleStrings()
void ObjectMgr::GetCreatureLocaleStrings (uint32 entry, int32 loc_idx, char const ** namePtr, char const ** subnamePtr = nullptr) const
Definition at line 10372 of file ObjectMgr.cpp.
References GetCreatureLocale().
GetCreatureModelAlternativeModel()
uint32 ObjectMgr::GetCreatureModelAlternativeModel (uint32 modelId) const
Definition at line 1613 of file ObjectMgr.cpp.
References GetCreatureModelInfo().
GetCreatureModelInfo()
CreatureModelInfo const * ObjectMgr::GetCreatureModelInfo (uint32 modelid) static
Wrapper for sCreatureModelStorage.LookupEntry.
Definition at line 4540 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureModelStorage.
Referenced by GetCreatureModelAlternativeModel(), GetCreatureModelRandomGender(), and LoadCreatureModelInfo().
GetCreatureModelRandomGender()
CreatureModelInfo const * ObjectMgr::GetCreatureModelRandomGender (uint32 display_id) const
Definition at line 1621 of file ObjectMgr.cpp.
References GetCreatureModelInfo(), CreatureModelInfo::modelid, CreatureModelInfo::modelid_other_gender, sLog, and urand().
Referenced by GetTaxiMountDisplayId().
GetCreatureQuestInvolvedRelationsMapBounds()
QuestRelationsMapBounds ObjectMgr::GetCreatureQuestInvolvedRelationsMapBounds (uint32 entry) const inline
Definition at line 1209 of file ObjectMgr.h.
References m_CreatureQuestInvolvedRelations.
GetCreatureQuestRelationsMap()
QuestRelationsMap& ObjectMgr::GetCreatureQuestRelationsMap () inline
Definition at line 1224 of file ObjectMgr.h.
References m_CreatureQuestRelations.
GetCreatureQuestRelationsMapBounds()
QuestRelationsMapBounds ObjectMgr::GetCreatureQuestRelationsMapBounds (uint32 entry) const inline
Definition at line 1204 of file ObjectMgr.h.
References m_CreatureQuestRelations.
GetCreatureSpawnEntry()
std::unordered_map<uint32, std::vector<uint32> > const& ObjectMgr::GetCreatureSpawnEntry () const inline
Definition at line 529 of file ObjectMgr.h.
References m_creatureSpawnEntryMap.
GetCreatureSpawnTemplate()
CreatureSpawnTemplate const* ObjectMgr::GetCreatureSpawnTemplate (uint32 entry) const inline
Definition at line 886 of file ObjectMgr.h.
References m_creatureSpawnTemplateMap.
Referenced by LoadCreatures().
GetCreatureSpellList()
CreatureSpellList * ObjectMgr::GetCreatureSpellList (uint32 Id) const
Definition at line 1028 of file ObjectMgr.cpp.
References m_spellListContainer.
GetCreatureSpellListContainer()
std::shared_ptr<CreatureSpellListContainer> ObjectMgr::GetCreatureSpellListContainer () inline
Definition at line 1272 of file ObjectMgr.h.
References m_spellListContainer.
GetCreatureTemplate()
CreatureInfo const * ObjectMgr::GetCreatureTemplate (uint32 id) static
Wrapper for sCreatureStorage.LookupEntry.
Definition at line 4539 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureStorage.
Referenced by PlayerbotAI::_HandleCommandQuest(), Creature::ChooseDisplayId(), CreatureLinkingHolder::DoCreatureLinkingEvent(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::DoSummonTotem(), Spell::DoSummonVehicle(), Spell::DoSummonWild(), Spell::EffectCreateTamedPet(), Spell::EffectScriptEffect(), Spell::EffectSummonPet(), Spell::EffectSummonType(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::ExtractLocationFromLink(), GeneratePetName(), Creature::GetAIName(), GetModelForRace(), CreatureData::GetObjectGuid(), Creature::GetScriptId(), GetTaxiMountDisplayId(), Aura::HandleAuraEmpathy(), Aura::HandleAuraMounted(), Aura::HandleAuraTransform(), WorldSession::HandleCreatureQueryOpcode(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleNpcAddCommand(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolSpawnsCommand(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleStableSwapPet(), WorldSession::HandleUnstablePet(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), Creature::InitEntry(), CreatureLinkingMgr::IsLinkingEntryValid(), AchievementCriteriaRequirement::IsValid(), IsVendorItemValid(), Unit::JustKilledCreature(), WaypointManager::Load(), LoadCreatureConditionalSpawn(), LoadCreatureInvolvedRelations(), LoadCreatureLocales(), LoadCreatureQuestRelations(), LoadCreatures(), LoadCreatureSpawnEntry(), GameEventMgr::LoadFromDB(), Creature::LoadFromDB(), LoadMailLevelRewards(), LoadNPCSpellClickSpells(), Pet::LoadPetFromDB(), LoadReputationOnKill(), AchievementGlobalMgr::LoadRewards(), ScriptMgr::LoadScripts(), LoadSpawnGroups(), LoadTrainers(), Map::MonsterYellToMap(), CreatureEventAI::ProcessAction(), PlayerbotAI::SendQuestNeedList(), WorldObject::SummonCreature(), Unit::TakePossessOf(), CreatureLinkingHolder::TryFollowMaster(), and Pet::TryLoadFromDB().
GetCreatureTemplateAddon()
CreatureDataAddon const * ObjectMgr::GetCreatureTemplateAddon (uint32 entry) static
Wrapper for sCreatureInfoAddonStorage.LookupEntry.
Definition at line 4543 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureInfoAddonStorage.
Referenced by Creature::GetCreatureAddon().
GetDbc2StorageLocaleIndex()
int ObjectMgr::GetDbc2StorageLocaleIndex () const inline
Definition at line 1045 of file ObjectMgr.h.
References m_Dbc2StorageLocaleIndex.
GetDbGuidsForTransport()
std::vector< std::pair< TypeID, uint32 > > const & ObjectMgr::GetDbGuidsForTransport (uint32 mapId) const
Definition at line 1000 of file ObjectMgr.cpp.
References m_guidsForMap.
GetDungeonEncounterBounds()
DungeonEncounterMapBounds ObjectMgr::GetDungeonEncounterBounds (uint32 creditEntry) const inline
Definition at line 1172 of file ObjectMgr.h.
References m_DungeonEncounters.
Referenced by IsEncounter().
GetDungeonEncounterBoundsByMap()
DungeonEncounterMapBounds ObjectMgr::GetDungeonEncounterBoundsByMap (uint32 mapId) const inline
Definition at line 1177 of file ObjectMgr.h.
References m_DungeonEncountersByMap.
GetEquipmentInfo()
EquipmentInfo const * ObjectMgr::GetEquipmentInfo (uint32 entry) static
Wrapper for sEquipmentStorage.LookupEntry.
Definition at line 4541 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sEquipmentStorage.
GetExclusiveQuestGroupsMapBounds()
ExclusiveQuestGroupsMapBounds ObjectMgr::GetExclusiveQuestGroupsMapBounds (int32 groupId) const inline
Definition at line 1199 of file ObjectMgr.h.
References m_ExclusiveQuestGroups.
GetFirstTemporaryCreatureLowGuid()
uint32 ObjectMgr::GetFirstTemporaryCreatureLowGuid () const inline
Definition at line 839 of file ObjectMgr.h.
References m_FirstTemporaryCreatureGuid.
GetFirstTemporaryGameObjectLowGuid()
uint32 ObjectMgr::GetFirstTemporaryGameObjectLowGuid () const inline
Definition at line 840 of file ObjectMgr.h.
References m_FirstTemporaryGameObjectGuid.
GetFishingBaseSkillLevel()
int32 ObjectMgr::GetFishingBaseSkillLevel (uint32 entry) const inline
Definition at line 828 of file ObjectMgr.h.
References mFishingBaseForArea.
GetGameObjectInfo()
GameObjectInfo const * ObjectMgr::GetGameObjectInfo (uint32 id) static
Wrapper for sGOStorage.LookupEntry.
Definition at line 4536 of file ObjectMgr.cpp.
References SQLHashStorage::LookupEntry(), and sGOStorage.
Referenced by PlayerbotAI::_HandleCommandCollect(), GameObject::Create(), Transport::Create(), GameObject::CreateGameObject(), Spell::EffectTransmitted(), ChatHandler::ExtractLocationFromLink(), PlayerbotAI::findNearbyGO(), GameObject::GetScriptId(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), WorldSession::HandleGameObjectQueryOpcode(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleListObjectCommand(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolSpawnsCommand(), GameObject::LoadFromDB(), LoadGameobjectInvolvedRelations(), LoadGameObjectLocales(), LoadGameobjectQuestRelations(), LoadGameObjects(), LoadGameObjectSpawnEntry(), ScriptMgr::LoadScripts(), LoadSpawnGroups(), MapManager::LoadTransports(), PlayerbotAI::SendQuestNeedList(), PlayerbotAI::SetQuestNeedItems(), and PoolGroup< T >::Spawn1Object().
GetGameObjectLocale()
GameObjectLocale const* ObjectMgr::GetGameObjectLocale (uint32 entry) const inline
Definition at line 920 of file ObjectMgr.h.
References mGameObjectLocaleMap.
GetGameTele() [1/2]
GameTele const * ObjectMgr::GetGameTele (const std::string & name) const
Definition at line 9426 of file ObjectMgr.cpp.
References m_GameTeleMap, Utf8toWStr(), GameTele::wnameLow, and wstrToLower().
GetGameTele() [2/2]
GameTele const* ObjectMgr::GetGameTele (uint32 id) const inline
Definition at line 1085 of file ObjectMgr.h.
References m_GameTeleMap.
GetGameTeleMap()
GameTeleMap const& ObjectMgr::GetGameTeleMap () const inline
Definition at line 1093 of file ObjectMgr.h.
References m_GameTeleMap.
GetGoBackTrigger()
AreaTrigger const * ObjectMgr::GetGoBackTrigger (uint32 map_id) const
Definition at line 7084 of file ObjectMgr.cpp.
References MapEntry::ghost_entrance_map, AreaTrigger::IsLessOrEqualThan(), mAreaTriggers, sAreaTriggerStore, and sMapStore.
GetGOData()
GameObjectData const* ObjectMgr::GetGOData (uint32 guid) const inline
Definition at line 1009 of file ObjectMgr.h.
References GetGODataPair().
Referenced by DeleteGOData(), and LoadSpawnGroups().
GetGODataPair()
GameObjectDataPair const* ObjectMgr::GetGODataPair (uint32 guid) const inline
Definition at line 1002 of file ObjectMgr.h.
References mGameObjectDataMap.
Referenced by GetGOData().
GetGOQuestInvolvedRelationsMapBounds()
QuestRelationsMapBounds ObjectMgr::GetGOQuestInvolvedRelationsMapBounds (uint32 entry) const inline
Definition at line 1219 of file ObjectMgr.h.
References m_GOQuestInvolvedRelations.
GetGOQuestRelationsMapBounds()
QuestRelationsMapBounds ObjectMgr::GetGOQuestRelationsMapBounds (uint32 entry) const inline
Definition at line 1214 of file ObjectMgr.h.
References m_GOQuestRelations.
GetGossipMenuItemsLocale()
GossipMenuItemsLocale const* ObjectMgr::GetGossipMenuItemsLocale (uint32 entry) const inline
Definition at line 988 of file ObjectMgr.h.
References mGossipMenuItemsLocaleMap.
GetGossipMenuItemsMapBounds()
GossipMenuItemsMapBounds ObjectMgr::GetGossipMenuItemsMapBounds (uint32 uiMenuId) const inline
Definition at line 1194 of file ObjectMgr.h.
References m_mGossipMenuItemsMap.
Referenced by LoadGossipMenuItemsLocales().
GetGossipMenusMapBounds()
GossipMenusMapBounds ObjectMgr::GetGossipMenusMapBounds (uint32 uiMenuId) const inline
Definition at line 1189 of file ObjectMgr.h.
References m_mGossipMenusMap.
GetGossipText()
GossipText const * ObjectMgr::GetGossipText (uint32 Text_ID) const
Definition at line 5965 of file ObjectMgr.cpp.
References mGossipText.
Referenced by LoadGossipMenu(), LoadGossipTextLocales(), and LoadNpcGossips().
GetGOTemplateAddon()
GameObjectTemplateAddon const * ObjectMgr::GetGOTemplateAddon (uint32 entry) const
Definition at line 8574 of file ObjectMgr.cpp.
References m_gameobjectAddonTemplates.
GetGroupById()
Group * ObjectMgr::GetGroupById (uint32 id) const
Definition at line 204 of file ObjectMgr.cpp.
References mGroupMap.
Referenced by LoadGroups().
GetGroupMapBegin()
GroupMap::iterator ObjectMgr::GetGroupMapBegin () inline
Definition at line 537 of file ObjectMgr.h.
References mGroupMap.
GetGroupMapEnd()
GroupMap::iterator ObjectMgr::GetGroupMapEnd () inline
Definition at line 538 of file ObjectMgr.h.
References mGroupMap.
GetInstanceTemplate()
InstanceTemplate const * ObjectMgr::GetInstanceTemplate (uint32 map) static
Wrapper for sInstanceTemplate.LookupEntry.
Definition at line 4545 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sInstanceTemplate.
Referenced by Player::CheckAndRevivePlayerOnDungeonEnter(), Spell::CheckCast(), MapManager::CreateDungeonMap(), Map::CreateInstanceData(), DungeonPersistentState::GetTemplate(), WorldSession::HandleMoveWorldportAckOpcode(), Map::IsMountAllowed(), MapManager::IsValidMAP(), LoadInstanceTemplate(), and Player::RewardReputation().
GetItemConvert()
uint32 ObjectMgr::GetItemConvert (uint32 itemEntry, uint32 raceMask) const inline
Definition at line 1151 of file ObjectMgr.h.
References ItemPrototype::AllowableRace, GetItemPrototype(), and m_ItemConvert.
GetItemExpireConvert()
uint32 ObjectMgr::GetItemExpireConvert (uint32 itemEntry) const inline
Definition at line 1161 of file ObjectMgr.h.
References m_ItemExpireConvert.
GetItemLocale()
ItemLocale const* ObjectMgr::GetItemLocale (uint32 entry) const inline
Definition at line 927 of file ObjectMgr.h.
References mItemLocaleMap.
Referenced by GetItemLocaleStrings().
GetItemLocaleStrings()
void ObjectMgr::GetItemLocaleStrings (uint32 entry, int32 loc_idx, std::string * namePtr, std::string * descriptionPtr = nullptr) const
Definition at line 10387 of file ObjectMgr.cpp.
References GetItemLocale().
GetItemPrototype()
ItemPrototype const * ObjectMgr::GetItemPrototype (uint32 id) static
Wrapper for sItemStorage.LookupEntry.
Definition at line 4544 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sItemStorage.
Referenced by Player::_ApplyAmmoBonuses(), Player::_CanStoreItem(), Player::_CanTakeMoreSimilarItems(), Player::_LoadInventory(), Player::_LoadMailedItems(), Player::_LoadSpellCooldowns(), PlayerbotAI::AuctionResult(), Player::BuildEnumData(), PlayerbotAI::Buy(), Player::BuyItemFromVendorSlot(), Player::CanEquipUniqueItem(), Player::CanUseAmmo(), ChatHandler::CheckEscapeSequences(), Spell::CheckItems(), AuctionEntry::CompareAuctionEntry(), Player::Create(), Item::Create(), Bag::Create(), Item::CreateItem(), Player::DeleteFromDB(), Spell::DoCreateItem(), Spell::EffectRestoreItemCharges(), GenerateEnchSuffixFactor(), Item::GetGemCountWithLimitCategory(), GetItemConvert(), AuctionHouseBot::GetItemData(), Item::GetProto(), Creature::GetVendorItemCurrentCount(), ChatHandler::HandleAddItemCommand(), ChatHandler::HandleAuctionItemCommand(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleItemNameQueryOpcode(), WorldSession::HandleItemQuerySingleOpcode(), ChatHandler::HandleListItemCommand(), ChatHandler::HandleNpcAddVendorItemCommand(), ChatHandler::HandleNpcDelVendorItemCommand(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandleQuestLogRemoveQuest(), ChatHandler::HandleSendItemsHelper(), WorldSession::HandleSocketOpcode(), Player::HasItemOrGemWithIdEquipped(), Player::HasQuestForItem(), Player::IsActionButtonDataValid(), PlayerbotAI::IsItemUseful(), SpellMgr::IsSpellValid(), ConditionEntry::IsValid(), LootStoreItem::IsValid(), IsVendorItemValid(), LoadAccessRequirements(), LoadAreaTriggerTeleports(), AuctionHouseMgr::LoadAuctionItems(), Corpse::LoadFromDB(), Guild::LoadGuildBankFromDB(), LoadItemLocales(), LoadItemPrototypes(), Item::LoadLootFromDB(), LoadPlayerInfo(), AchievementGlobalMgr::LoadRewards(), ScriptMgr::LoadScripts(), LootItem::LootItem(), operator<<(), Player::RewardQuest(), LootStoreItem::Roll(), Player::SendEquipError(), WorldSession::SendListInventory(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), BattleGround::SendRewardMarkByMail(), AuctionHouseBot::SetItemData(), AuctionHouseBot::Update(), AchievementMgr::UpdateAchievementCriteria(), Player::UpdatePotionCooldown(), Creature::UpdateVendorItemCurrentCount(), and Spell::WriteAmmoToPacket().
GetItemRequiredTargetMapBounds()
ItemRequiredTargetMapBounds ObjectMgr::GetItemRequiredTargetMapBounds (uint32 uiItemEntry) const inline
Definition at line 1167 of file ObjectMgr.h.
References m_ItemRequiredTarget.
GetLoadedStringsCount()
uint32 ObjectMgr::GetLoadedStringsCount (int32 minEntry) const inline
Definition at line 1034 of file ObjectMgr.h.
References m_loadedStringCount.
GetMailLevelReward()
MailLevelReward const* ObjectMgr::GetMailLevelReward (uint32 level, uint32 raceMask) inline
Definition at line 860 of file ObjectMgr.h.
References m_mailLevelRewardMap.
GetMangosString()
const char * ObjectMgr::GetMangosString (int32 entry, int locale_idx) const
Definition at line 9232 of file ObjectMgr.cpp.
References _DoStringError(), and GetMangosStringLocale().
Referenced by GetMangosStringForDbcLocale().
GetMangosStringForDbcLocale()
const char* ObjectMgr::GetMangosStringForDbcLocale (int32 entry) const inline
Definition at line 1043 of file ObjectMgr.h.
References GetMangosString(), and m_Dbc2StorageLocaleIndex.
GetMangosStringLocale()
MangosStringLocale const* ObjectMgr::GetMangosStringLocale (int32 entry) const inline
Definition at line 1028 of file ObjectMgr.h.
References mMangosStringLocaleMap.
Referenced by GetMangosString().
GetMapEntranceTrigger()
AreaTrigger const * ObjectMgr::GetMapEntranceTrigger (uint32 Map) const
Searches for the areatrigger which teleports players to the given map TODO: Requirements should be propably Map bound not Areatrigger bound.
Definition at line 7129 of file ObjectMgr.cpp.
References MapEntry::Instanceable(), AreaTrigger::IsLessOrEqualThan(), mAreaTriggers, and sMapStore.
GetMaxLevelForExpansion()
uint32 ObjectMgr::GetMaxLevelForExpansion (uint32 expansion) const
Definition at line 7721 of file ObjectMgr.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, EXPANSION_TBC, EXPANSION_WOTLK, and sWorld.
GetModelForRace()
uint32 ObjectMgr::GetModelForRace (uint32 sourceModelId, uint32 racemask)
Definition at line 1641 of file ObjectMgr.cpp.
References Creature::ChooseDisplayId(), GetCreatureTemplate(), and m_mCreatureModelRaceMap.
GetNearestTaxiNode()
uint32 ObjectMgr::GetNearestTaxiNode (float x, float y, float z, uint32 mapid, Team team) const
Definition at line 6747 of file ObjectMgr.cpp.
References ALLIANCE, TaxiNodesEntry::map_id, TaxiNodesEntry::MountCreatureID, sTaxiNodesMask, sTaxiNodesStore, TaxiNodesEntry::x, TaxiNodesEntry::y, and TaxiNodesEntry::z.
GetNpcGossip()
uint32 ObjectMgr::GetNpcGossip (uint32 entry) const inline
Definition at line 1097 of file ObjectMgr.h.
References m_mCacheNpcTextIdMap.
GetNpcTextLocale()
NpcTextLocale const* ObjectMgr::GetNpcTextLocale (uint32 entry) const inline
Definition at line 945 of file ObjectMgr.h.
References mNpcTextLocaleMap.
Referenced by GetNpcTextLocaleStrings0(), and GetNpcTextLocaleStringsAll().
GetNpcTextLocaleStrings0()
void ObjectMgr::GetNpcTextLocaleStrings0 (uint32 entry, int32 loc_idx, std::string * text0_0_Ptr, std::string * text1_0_Ptr) const
Definition at line 10433 of file ObjectMgr.cpp.
References GetNpcTextLocale().
GetNpcTextLocaleStringsAll()
void ObjectMgr::GetNpcTextLocaleStringsAll (uint32 entry, int32 loc_idx, ObjectMgr::NpcTextArray * text0_Ptr, ObjectMgr::NpcTextArray * text1_Ptr) const
Definition at line 10414 of file ObjectMgr.cpp.
References GetNpcTextLocale(), and MAX_GOSSIP_TEXT_OPTIONS.
GetNpcTrainerSpells()
TrainerSpellData const* ObjectMgr::GetNpcTrainerSpells (uint32 entry) const inline
Definition at line 1106 of file ObjectMgr.h.
References m_mCacheTrainerSpellMap.
GetNpcTrainerTemplateSpells()
TrainerSpellData const* ObjectMgr::GetNpcTrainerTemplateSpells (uint32 entry) const inline
Definition at line 1115 of file ObjectMgr.h.
References m_mCacheTrainerTemplateSpellMap.
Referenced by LoadTrainers().
GetNpcVendorItemList()
VendorItemData const* ObjectMgr::GetNpcVendorItemList (uint32 entry) const inline
Definition at line 1124 of file ObjectMgr.h.
References m_mCacheVendorItemMap.
Referenced by IsVendorItemValid().
GetNpcVendorTemplateItemList()
VendorItemData const* ObjectMgr::GetNpcVendorTemplateItemList (uint32 entry) const inline
Definition at line 1133 of file ObjectMgr.h.
References m_mCacheVendorTemplateItemMap.
Referenced by IsVendorItemValid().
GetOrNewStorageLocaleIndexFor()
int ObjectMgr::GetOrNewStorageLocaleIndexFor (LocaleConstant loc)
Definition at line 8945 of file ObjectMgr.cpp.
References DEFAULT_LOCALE, and m_LocalForIndex.
Referenced by LoadBroadcastTextLocales(), LoadCreatureLocales(), LoadGameObjectLocales(), LoadGossipMenuItemsLocales(), LoadGossipTextLocales(), LoadItemLocales(), LoadMangosStrings(), LoadPageTextLocales(), LoadPointOfInterestLocales(), LoadQuestgiverGreetingLocales(), LoadQuestLocales(), and LoadTrainerGreetingLocales().
GetPageTextLocale()
PageTextLocale const* ObjectMgr::GetPageTextLocale (uint32 entry) const inline
Definition at line 981 of file ObjectMgr.h.
References mPageTextLocaleMap.
GetPetLevelInfo()
PetLevelInfo const * ObjectMgr::GetPetLevelInfo (uint32 creature_id, uint32 level) const
Definition at line 3740 of file ObjectMgr.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, petInfo, and sWorld.
GetPlayer() [1/2]
Player * ObjectMgr::GetPlayer (const char * name) static
Wrapper for ObjectAccessor::FindPlayerByName.
Definition at line 4537 of file ObjectMgr.cpp.
References ObjectAccessor::FindPlayerByName().
Referenced by GetPlayerAccountIdByGUID(), GetPlayerMapIdByGUID(), GetPlayerNameByGUID(), GetPlayerTeamByGUID(), and ReturnOrDeleteOldMails().
GetPlayer() [2/2]
Player * ObjectMgr::GetPlayer (ObjectGuid guid, bool inWorld = true) static
Wrapper for ObjectAccessor::FindPlayer.
Definition at line 4538 of file ObjectMgr.cpp.
References ObjectAccessor::FindPlayer().
GetPlayerAccountIdByGUID()
uint32 ObjectMgr::GetPlayerAccountIdByGUID (ObjectGuid guid) const
Definition at line 2722 of file ObjectMgr.cpp.
References CharacterDatabase, ObjectGuid::GetCounter(), GetPlayer(), ObjectGuid::IsPlayer(), and Database::PQuery().
GetPlayerAccountIdByPlayerName()
uint32 ObjectMgr::GetPlayerAccountIdByPlayerName (const std::string & name) const
Definition at line 2744 of file ObjectMgr.cpp.
References CharacterDatabase, and Database::PQuery().
GetPlayerClassInfo()
PlayerClassInfo const* ObjectMgr::GetPlayerClassInfo (uint32 class_) const inline
Definition at line 553 of file ObjectMgr.h.
References MAX_CLASSES, and playerClassInfo.
GetPlayerClassLevelInfo()
void ObjectMgr::GetPlayerClassLevelInfo (uint32 class_, uint32 level, PlayerClassLevelInfo * info) const
Definition at line 4430 of file ObjectMgr.cpp.
References CONFIG_UINT32_MAX_PLAYER_LEVEL, PlayerClassInfo::levelInfo, MAX_CLASSES, playerClassInfo, and sWorld.
GetPlayerGuidByName()
ObjectGuid ObjectMgr::GetPlayerGuidByName (std::string name) const
Definition at line 2661 of file ObjectMgr.cpp.
References CharacterDatabase, Database::escape_string(), HIGHGUID_PLAYER, and Database::PQuery().
GetPlayerInfo()
PlayerInfo const* ObjectMgr::GetPlayerInfo (uint32 race, uint32 class_) const inline
Definition at line 560 of file ObjectMgr.h.
References PlayerInfo::displayId_f, PlayerInfo::displayId_m, MAX_CLASSES, MAX_RACES, and playerInfo.
GetPlayerLevelInfo()
void ObjectMgr::GetPlayerLevelInfo (uint32 race, uint32 class_, uint32 level, PlayerLevelInfo * info) const
Definition at line 4443 of file ObjectMgr.cpp.
References BuildPlayerLevelInfo(), CONFIG_UINT32_MAX_PLAYER_LEVEL, PlayerInfo::displayId_f, PlayerInfo::displayId_m, PlayerInfo::levelInfo, MAX_CLASSES, MAX_RACES, playerInfo, and sWorld.
GetPlayerMapIdByGUID()
int32 ObjectMgr::GetPlayerMapIdByGUID (ObjectGuid const & guid) const
Definition at line 2642 of file ObjectMgr.cpp.
References CharacterDatabase, ObjectGuid::GetCounter(), GetPlayer(), and Database::PQuery().
GetPlayerNameByGUID()
bool ObjectMgr::GetPlayerNameByGUID (ObjectGuid guid, std::string & name) const
Definition at line 2679 of file ObjectMgr.cpp.
References CharacterDatabase, ObjectGuid::GetCounter(), GetPlayer(), and Database::PQuery().
GetPlayerTeamByGUID()
Team ObjectMgr::GetPlayerTeamByGUID (ObjectGuid guid) const
Definition at line 2702 of file ObjectMgr.cpp.
References CharacterDatabase, ObjectGuid::GetCounter(), GetPlayer(), Database::PQuery(), TEAM_NONE, and Player::TeamForRace().
GetPointOfInterest()
PointOfInterest const* ObjectMgr::GetPointOfInterest (uint32 id) const inline
Definition at line 673 of file ObjectMgr.h.
References mPointsOfInterest.
Referenced by LoadGossipMenuItems(), and LoadPointOfInterestLocales().
GetPointOfInterestLocale()
PointOfInterestLocale const* ObjectMgr::GetPointOfInterestLocale (uint32 poi_id) const inline
Definition at line 995 of file ObjectMgr.h.
References mPointOfInterestLocaleMap.
GetQuestForAreaTrigger()
uint32 ObjectMgr::GetQuestForAreaTrigger (uint32 Trigger_ID) const inline
Definition at line 591 of file ObjectMgr.h.
References mQuestAreaTriggerMap.
GetQuestgiverGreetingData()
QuestgiverGreeting const * ObjectMgr::GetQuestgiverGreetingData (uint32 entry, uint32 type) const
Definition at line 6174 of file ObjectMgr.cpp.
References m_questgiverGreetingMap.
GetQuestgiverGreetingLocale()
QuestgiverGreetingLocale const* ObjectMgr::GetQuestgiverGreetingLocale (uint32 entry, uint32 type) const inline
Definition at line 965 of file ObjectMgr.h.
References m_questgiverGreetingLocaleMap.
Referenced by GetQuestgiverGreetingLocales().
GetQuestgiverGreetingLocales()
void ObjectMgr::GetQuestgiverGreetingLocales (uint32 entry, uint32 type, int32 loc_idx, std::string * titlePtr) const
Definition at line 10450 of file ObjectMgr.cpp.
References GetQuestgiverGreetingLocale().
GetQuestLocale()
QuestLocale const* ObjectMgr::GetQuestLocale (uint32 entry) const inline
Definition at line 936 of file ObjectMgr.h.
References mQuestLocaleMap.
Referenced by GetQuestLocaleStrings().
GetQuestLocaleStrings()
void ObjectMgr::GetQuestLocaleStrings (uint32 entry, int32 loc_idx, std::string * titlePtr) const
Definition at line 10402 of file ObjectMgr.cpp.
References GetQuestLocale().
GetQuestPOIVector()
QuestPOIVector const* ObjectMgr::GetQuestPOIVector (uint32 questId) inline
Definition at line 681 of file ObjectMgr.h.
References mQuestPOIMap.
GetQuestTemplate()
Quest const* ObjectMgr::GetQuestTemplate (uint32 quest_id) const inline
Definition at line 584 of file ObjectMgr.h.
References mQuestTemplates.
Referenced by LoadAccessRequirements(), LoadQuestAreaTriggers(), and LoadQuestLocales().
GetQuestTemplates()
QuestMap const& ObjectMgr::GetQuestTemplates () const inline
Definition at line 589 of file ObjectMgr.h.
References mQuestTemplates.
GetRandomCreatureEntry()
uint32 ObjectMgr::GetRandomCreatureEntry (uint32 dbguid) const inline
Definition at line 641 of file ObjectMgr.h.
References GetRandomEntry(), and m_creatureSpawnEntryMap.
Referenced by LoadCreatures().
GetRandomEntry()
uint32 ObjectMgr::GetRandomEntry (std::unordered_map< uint32, std::vector< uint32 >> const & map, uint32 dbguid) const inline
Definition at line 631 of file ObjectMgr.h.
References GetAllRandomEntries(), and irand().
Referenced by GetRandomCreatureEntry(), and GetRandomGameObjectEntry().
GetRandomGameObjectEntry()
uint32 ObjectMgr::GetRandomGameObjectEntry (uint32 dbguid) const inline
Definition at line 638 of file ObjectMgr.h.
References GetRandomEntry(), and m_gameobjectSpawnEntryMap.
Referenced by LoadGameObjects().
GetRepRewardRate()
RepRewardRate const* ObjectMgr::GetRepRewardRate (uint32 factionId) const inline
Definition at line 647 of file ObjectMgr.h.
References m_RepRewardRateMap.
GetRepSpilloverTemplate()
RepSpilloverTemplate const* ObjectMgr::GetRepSpilloverTemplate (uint32 factionId) const inline
Definition at line 664 of file ObjectMgr.h.
References m_RepSpilloverTemplateMap.
GetReputationOnKillEntry()
ReputationOnKillEntry const* ObjectMgr::GetReputationOnKillEntry (uint32 id) const inline
Definition at line 656 of file ObjectMgr.h.
References mRepOnKill.
GetSpawnGroupContainer()
std::shared_ptr<SpawnGroupEntryContainer> ObjectMgr::GetSpawnGroupContainer () inline
Definition at line 1273 of file ObjectMgr.h.
References m_spawnGroupContainer.
GetSpellClickInfoMapBounds()
SpellClickInfoMapBounds ObjectMgr::GetSpellClickInfoMapBounds (uint32 creature_id) const inline
Definition at line 1146 of file ObjectMgr.h.
References mSpellClickInfoMap.
GetStorageLocaleIndexFor()
int ObjectMgr::GetStorageLocaleIndexFor (LocaleConstant loc)
Definition at line 8933 of file ObjectMgr.cpp.
References DEFAULT_LOCALE, and m_LocalForIndex.
Referenced by SetDbc2StorageLocaleIndex().
GetTaxiMountDisplayId()
uint32 ObjectMgr::GetTaxiMountDisplayId (uint32 id, Team team) const
Definition at line 6810 of file ObjectMgr.cpp.
References ALLIANCE, Creature::ChooseDisplayId(), GetCreatureModelRandomGender(), GetCreatureTemplate(), HORDE, CreatureModelInfo::modelid, TaxiNodesEntry::MountCreatureID, and sTaxiNodesStore.
GetTaxiPath()
void ObjectMgr::GetTaxiPath (uint32 source, uint32 destination, uint32 & path, uint32 & cost) const
Definition at line 6786 of file ObjectMgr.cpp.
References sTaxiPathSetBySource.
GetTaxiShortcut()
bool ObjectMgr::GetTaxiShortcut (uint32 pathid, TaxiShortcutData & data)
Definition at line 6672 of file ObjectMgr.cpp.
References m_TaxiShortcutMap.
GetTrainerGreetingData()
TrainerGreeting const * ObjectMgr::GetTrainerGreetingData (uint32 entry) const
Definition at line 6326 of file ObjectMgr.cpp.
References m_trainerGreetingMap.
GetTrainerGreetingLocale()
TrainerGreetingLocale const* ObjectMgr::GetTrainerGreetingLocale (uint32 entry) const inline
Definition at line 974 of file ObjectMgr.h.
References m_trainerGreetingLocaleMap.
Referenced by GetTrainerGreetingLocales().
GetTrainerGreetingLocales()
void ObjectMgr::GetTrainerGreetingLocales (uint32 entry, int32 loc_idx, std::string * titlePtr) const
Definition at line 10463 of file ObjectMgr.cpp.
References GetTrainerGreetingLocale().
GetUnitConditions()
std::shared_ptr< std::map< int32, UnitConditionEntry > > ObjectMgr::GetUnitConditions ()
Definition at line 8549 of file ObjectMgr.cpp.
References m_unitConditionMgr.
GetVehicleSeatParameters()
VehicleSeatParameters const * ObjectMgr::GetVehicleSeatParameters (uint32 seatEntry) const
Definition at line 1005 of file ObjectMgr.cpp.
References m_seatParameters.
GetWorldStateExpressions()
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > ObjectMgr::GetWorldStateExpressions ()
Definition at line 8554 of file ObjectMgr.cpp.
References m_worldStateExpressionMgr.
GetWorldStateName()
WorldStateName * ObjectMgr::GetWorldStateName (int32 Id)
Definition at line 1042 of file ObjectMgr.cpp.
References m_worldStateNames.
GetWorldTemplate()
WorldTemplate const * ObjectMgr::GetWorldTemplate (uint32 map) static
Wrapper for sWorldTemplate.LookupEntry.
Definition at line 4546 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sWorldTemplate.
Referenced by Map::CreateInstanceData(), and LoadWorldTemplate().
GetXPForLevel()
uint32 ObjectMgr::GetXPForLevel (uint32 level) const
Definition at line 7714 of file ObjectMgr.cpp.
References mPlayerXPperLevel.
Referenced by GetXPForPetLevel().
GetXPForPetLevel()
uint32 ObjectMgr::GetXPForPetLevel (uint32 level) const inline
Definition at line 825 of file ObjectMgr.h.
References GetXPForLevel().
HasWorldStateName()
bool ObjectMgr::HasWorldStateName (int32 Id) const
Definition at line 1037 of file ObjectMgr.cpp.
References m_worldStateNames.
IsCombatConditionSatisfied()
bool ObjectMgr::IsCombatConditionSatisfied (int32 expressionId, Unit const * source, float range)
Definition at line 9311 of file ObjectMgr.cpp.
References m_combatConditionMgr.
IsConditionSatisfied()
bool ObjectMgr::IsConditionSatisfied (uint32 conditionId, WorldObject const * target, Map const * map, WorldObject const * source, ConditionSource conditionSourceType) const
Definition at line 9293 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sConditionStorage.
IsEncounter()
bool ObjectMgr::IsEncounter (uint32 creditEntry, uint32 mapId) const
Definition at line 8958 of file ObjectMgr.cpp.
References ENCOUNTER_CREDIT_KILL_CREATURE, and GetDungeonEncounterBounds().
IsExistingGossipMenuId()
bool ObjectMgr::IsExistingGossipMenuId (uint32 menuId) inline
Definition at line 1185 of file ObjectMgr.h.
References m_mGossipMenusMap.
IsGameObjectForQuests()
bool ObjectMgr::IsGameObjectForQuests (uint32 entry) const inline
Definition at line 603 of file ObjectMgr.h.
References mGameObjectForQuestSet.
IsReservedName()
bool ObjectMgr::IsReservedName (const std::string & name) const
Definition at line 8751 of file ObjectMgr.cpp.
References m_ReservedNames, Utf8toWStr(), and wstrToLower().
IsTavernAreaTrigger()
bool ObjectMgr::IsTavernAreaTrigger (uint32 Trigger_ID) const inline
Definition at line 598 of file ObjectMgr.h.
References mTavernAreaTriggerSet.
IsUnitConditionSatisfied()
bool ObjectMgr::IsUnitConditionSatisfied (int32 conditionId, Unit const * source, Unit const * target)
Definition at line 9306 of file ObjectMgr.cpp.
References m_unitConditionMgr.
IsValidCharterName()
bool ObjectMgr::IsValidCharterName (const std::string & name) static
Definition at line 8895 of file ObjectMgr.cpp.
References CONFIG_UINT32_MIN_CHARTER_NAME, CONFIG_UINT32_STRICT_CHARTER_NAMES, isValidString(), MAX_CHARTER_NAME, sWorld, and Utf8toWStr().
Referenced by WorldSession::HandlePetitionBuyOpcode(), and WorldSession::HandlePetitionRenameOpcode().
IsVendorItemValid()
bool ObjectMgr::IsVendorItemValid (bool isTemplate, char const * tableName, uint32 vendor_entry, uint32 item_id, uint32 maxcount, uint32 incrtime, uint32 ExtendedCost, uint16 conditionId, Player * pl = nullptr) const
Definition at line 10238 of file ObjectMgr.cpp.
References VendorItemData::FindItemCostPair(), GetCreatureTemplate(), VendorItemData::GetItemCount(), GetItemPrototype(), GetNpcVendorItemList(), GetNpcVendorTemplateItemList(), LANG_COMMAND_ADDVENDORITEMITEMS, LANG_COMMAND_VENDORSELECTION, LANG_EXTENDED_COST_NOT_EXIST, LANG_ITEM_ALREADY_IN_LIST, LANG_ITEM_NOT_FOUND, SQLStorage::LookupEntry(), ChatHandler::PSendSysMessage(), sConditionStorage, ChatHandler::SendSysMessage(), sItemExtendedCostStore, sLog, and CreatureInfo::VendorTemplateId.
Referenced by LoadVendors().
IsWorldStateExpressionSatisfied()
bool ObjectMgr::IsWorldStateExpressionSatisfied (int32 expressionId, Map const * map)
Definition at line 9301 of file ObjectMgr.cpp.
References m_worldStateExpressionMgr.
LoadAccessRequirements()
void ObjectMgr::LoadAccessRequirements ()
Definition at line 6989 of file ObjectMgr.cpp.
References AccessRequirement::achievement, GetItemPrototype(), GetQuestTemplate(), Field::GetString(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), AccessRequirement::item, AccessRequirement::item2, AccessRequirement::item_level, AccessRequirement::levelMax, AccessRequirement::levelMin, m_accessRequirements, MAKE_PAIR32, Database::Query(), AccessRequirement::quest_A, AccessRequirement::quest_H, AccessRequirement::questFailedText, sAchievementMgr, sLog, BarGoLink::step(), and WorldDatabase.
LoadActiveEntities()
void ObjectMgr::LoadActiveEntities (Map * _map)
Parameters
_map Map* of the map for which to load active entities. If nullptr active entities on continents are loaded
Definition at line 9856 of file ObjectMgr.cpp.
References Map::ForceLoadGrid(), Map::GetId(), m_activeCreatures, m_activeGameObjects, mCreatureDataMap, mGameObjectDataMap, CreatureData::posX, GameObjectData::posX, CreatureData::posY, GameObjectData::posY, and sWorld.
LoadAreaGroups()
void ObjectMgr::LoadAreaGroups ()
Definition at line 8427 of file ObjectMgr.cpp.
References SQLStorage::Load(), sAreaGroupStore, and sLog.
Referenced by LoadSQLDBCs().
LoadAreaTriggerTeleports()
void ObjectMgr::LoadAreaTriggerTeleports ()
Definition at line 6847 of file ObjectMgr.cpp.
References AreaTrigger::conditionId, QueryResult::Fetch(), Field::GetFloat(), GetItemPrototype(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), AreaTrigger::heroicKey, AreaTrigger::heroicKey2, SQLStorage::LookupEntry(), mAreaTriggers, mQuestTemplates, QueryResult::NextRow(), Database::Query(), AreaTrigger::requiredItem, AreaTrigger::requiredItem2, AreaTrigger::requiredLevel, AreaTrigger::requiredQuest, AreaTrigger::requiredQuestHeroic, sAreaTriggerStore, sConditionStorage, sLog, sMapStore, BarGoLink::step(), AreaTrigger::target_mapId, AreaTrigger::target_Orientation, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, and WorldDatabase.
LoadArenaTeams()
void ObjectMgr::LoadArenaTeams ()
Definition at line 4552 of file ObjectMgr.cpp.
References AddArenaTeam(), CharacterDatabase, ArenaTeam::Disband(), QueryResult::GetRowCount(), ArenaTeam::LoadArenaTeamFromDB(), ArenaTeam::LoadMembersFromDB(), QueryResult::NextRow(), Database::Query(), sLog, and BarGoLink::step().
LoadBroadcastText()
void ObjectMgr::LoadBroadcastText ()
Definition at line 8440 of file ObjectMgr.cpp.
References BroadcastText::chatTypeId, DEFAULT_LOCALE, BroadcastText::emoteDelays, BroadcastText::emoteIds, BroadcastText::femaleText, Field::GetCppString(), Field::GetUInt32(), BroadcastText::languageId, m_broadcastTextMap, BroadcastText::maleText, Database::Query(), sLog, BroadcastText::soundId1, BarGoLink::step(), and WorldDatabase.
LoadBroadcastTextLocales()
void ObjectMgr::LoadBroadcastTextLocales ()
Definition at line 8488 of file ObjectMgr.cpp.
References BroadcastText::femaleText, Field::GetCppString(), GetLocaleByName(), GetOrNewStorageLocaleIndexFor(), Field::GetUInt32(), m_broadcastTextMap, BroadcastText::maleText, Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadConditions()
void ObjectMgr::LoadConditions ()
Definition at line 5930 of file ObjectMgr.cpp.
References SQLStorage::EraseEntry(), SQLStorageBase::GetMaxEntry(), Quest::GetQuestId(), SQLStorageBase::GetRecordCount(), ConditionEntry::IsValid(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), SQLStorage::LookupEntry(), mQuestTemplates, Quest::RequiredCondition, sConditionStorage, and sLog.
LoadConditionsAndExpressions()
std::tuple< std::shared_ptr< std::map< int32, UnitConditionEntry > >, std::shared_ptr< std::map< int32, WorldStateExpressionEntry > >, std::shared_ptr< std::map< int32, CombatConditionEntry > > > ObjectMgr::LoadConditionsAndExpressions ()
Definition at line 8541 of file ObjectMgr.cpp.
References m_combatConditionMgr, m_unitConditionMgr, and m_worldStateExpressionMgr.
LoadCorpses()
void ObjectMgr::LoadCorpses ()
Definition at line 7803 of file ObjectMgr.cpp.
References CharacterDatabase, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), Corpse::LoadFromDB(), QueryResult::NextRow(), Database::Query(), sLog, sObjectAccessor, and BarGoLink::step().
LoadCreatureAddons() [1/2]
void ObjectMgr::LoadCreatureAddons ()
Definition at line 890 of file ObjectMgr.cpp.
References SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetTableName(), SQLStorage::LookupEntry(), mCreatureDataMap, sCreatureDataAddonStorage, sCreatureInfoAddonStorage, sCreatureStorage, and sLog.
LoadCreatureAddons() [2/2]
void ObjectMgr::LoadCreatureAddons (SQLStorage & creatureaddons, char const * entryName, char const * comment) private
Definition at line 855 of file ObjectMgr.cpp.
References ConvertCreatureAddonAuras(), CreatureDataAddon::emote, SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), SQLStorageBase::GetTableName(), CreatureDataAddon::guidOrEntry, SQLStorage::Load(), SQLStorage::LookupEntry(), CreatureDataAddon::mount, sCreatureDisplayInfoStore, sEmotesStore, CreatureDataAddon::sheath_state, SHEATH_STATE_RANGED, and sLog.
LoadCreatureClassLvlStats()
void ObjectMgr::LoadCreatureClassLvlStats ()
Definition at line 909 of file ObjectMgr.cpp.
References CreatureClassLvlStats::BaseArmor, CreatureClassLvlStats::BaseDamage, CreatureClassLvlStats::BaseHealth, CreatureClassLvlStats::BaseMana, CreatureClassLvlStats::BaseMeleeAttackPower, CreatureClassLvlStats::BaseRangedAttackPower, CLASSMASK_ALL_CREATURES, classToIndex, DEFAULT_MAX_CREATURE_LEVEL, QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), m_creatureClassLvlStats, MAX_EXPANSION, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadCreatureConditionalSpawn()
void ObjectMgr::LoadCreatureConditionalSpawn ()
Definition at line 1893 of file ObjectMgr.cpp.
References CreatureConditionalSpawn::EntryAlliance, CreatureConditionalSpawn::EntryHorde, GetCreatureTemplate(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), CreatureConditionalSpawn::Guid, SQLStorage::Load(), SQLStorage::LookupEntry(), sCreatureConditionalSpawnStore, and sLog.
LoadCreatureCooldowns()
void ObjectMgr::LoadCreatureCooldowns ()
Definition at line 10546 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_creatureCooldownMap, QueryResult::NextRow(), Database::Query(), sCreatureStorage, sLog, sSpellTemplate, and WorldDatabase.
LoadCreatureImmunities()
void ObjectMgr::LoadCreatureImmunities ()
Definition at line 1051 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_creatureImmunities, MAX_SPELL_IMMUNITY, QueryResult::NextRow(), Database::Query(), sCreatureStorage, sLog, and WorldDatabase.
LoadCreatureInvolvedRelations()
void ObjectMgr::LoadCreatureInvolvedRelations ()
Definition at line 8694 of file ObjectMgr.cpp.
References GetCreatureTemplate(), LoadQuestRelationsHelper(), m_CreatureQuestInvolvedRelations, and sLog.
Referenced by LoadQuestRelations().
LoadCreatureLocales()
void ObjectMgr::LoadCreatureLocales ()
Definition at line 240 of file ObjectMgr.cpp.
References ERROR_DB_STRICT_LOG, QueryResult::Fetch(), GetCreatureTemplate(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_LOCALE, mCreatureLocaleMap, CreatureLocale::Name, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), CreatureLocale::SubName, and WorldDatabase.
LoadCreatureModelInfo()
void ObjectMgr::LoadCreatureModelInfo ()
Definition at line 1666 of file ObjectMgr.cpp.
References CreatureModelInfo::bounding_radius, CreatureModelInfo::combat_reach, DEFAULT_WORLD_OBJECT_SIZE, CreatureModelInfo::gender, GENDER_FEMALE, GENDER_MALE, GetCreatureModelInfo(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), SQLStorage::Load(), SQLStorage::LookupEntry(), MAX_GENDER, ChrRacesEntry::model_f, ChrRacesEntry::model_m, CreatureModelInfo::modelid, CreatureModelInfo::modelid_alternative, CreatureModelInfo::modelid_other_gender, RACEMASK_ALL_PLAYABLE, sChrRacesStore, sCreatureDisplayInfoStore, sCreatureModelStorage, and sLog.
LoadCreatureModelRace()
void ObjectMgr::LoadCreatureModelRace ()
Definition at line 1776 of file ObjectMgr.cpp.
References CreatureModelRace::creature_entry, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_mCreatureModelRaceMap, CreatureModelRace::modelid, CreatureModelRace::modelid_racial, QueryResult::NextRow(), Database::Query(), CreatureModelRace::racemask, RACEMASK_ALL_PLAYABLE, sCreatureDisplayInfoStore, sCreatureModelStorage, sCreatureStorage, sLog, BarGoLink::step(), and WorldDatabase.
LoadCreatureQuestRelations()
void ObjectMgr::LoadCreatureQuestRelations ()
Definition at line 8682 of file ObjectMgr.cpp.
References GetCreatureTemplate(), LoadQuestRelationsHelper(), m_CreatureQuestRelations, and sLog.
Referenced by LoadQuestRelations().
LoadCreatures()
void ObjectMgr::LoadCreatures ()
Definition at line 2033 of file ObjectMgr.cpp.
References AddCreatureToGrid(), CreatureInfo::AIName, CONFIG_BOOL_AUTOLOAD_ACTIVE, CREATURE_EXTRA_FLAG_ACTIVE, CreatureInfo::DifficultyEntry, CreatureConditionalSpawn::EntryAlliance, CreatureConditionalSpawn::EntryHorde, CreatureData::EntryPoolId, CreatureInfo::ExtraFlags, QueryResult::Fetch(), CreatureData::gameEvent, GetCreatureConditionalSpawn(), GetCreatureSpawnTemplate(), GetCreatureTemplate(), Field::GetFloat(), Field::GetInt16(), GetMapDifficultyData(), SQLStorageBase::GetMaxEntry(), GetRandomCreatureEntry(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), CreatureData::GuidPoolId, CreatureData::id, IDLE_MOTION_TYPE, MapEntry::IsContinent(), CreatureData::IsNotPartOfPoolOrEvent(), MaNGOS::IsValidMapCoord(), SQLStorage::LookupEntry(), m_activeCreatures, m_guidsForMap, m_transportMaps, CreatureData::mapid, MAX_DIFFICULTY, mCreatureDataMap, CreatureData::movementType, QueryResult::NextRow(), CreatureData::orientation, CreatureData::OriginalZoneId, CreatureData::phaseMask, CreatureData::posX, CreatureData::posY, CreatureData::posZ, Database::Query(), RANDOM_MOTION_TYPE, sCreatureStorage, SIZEFMTD, sLog, sMapStore, CreatureData::spawndist, CreatureData::spawnMask, CreatureData::spawnTemplate, CreatureData::spawntimesecsmax, CreatureData::spawntimesecsmin, BarGoLink::step(), sTerrainMgr, sWorld, TYPEID_UNIT, and WorldDatabase.
LoadCreatureSpawnDataTemplates()
void ObjectMgr::LoadCreatureSpawnDataTemplates ()
Definition at line 1918 of file ObjectMgr.cpp.
References Field::GetCppString(), Field::GetInt32(), Field::GetUInt32(), m_creatureSpawnTemplateMap, Database::Query(), sLog, sScriptMgr, BarGoLink::step(), and WorldDatabase.
LoadCreatureSpawnEntry()
void ObjectMgr::LoadCreatureSpawnEntry ()
Definition at line 1986 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetCreatureTemplate(), QueryResult::GetRowCount(), Field::GetUInt32(), m_creatureSpawnEntryMap, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadCreatureSpellLists()
std::shared_ptr< CreatureSpellListContainer > ObjectMgr::LoadCreatureSpellLists ()
Definition at line 1086 of file ObjectMgr.cpp.
References CreatureSpellListSpell::Availability, CreatureSpellList::ChanceRangedAttack, CreatureSpellList::ChanceSupportAction, CreatureSpellListSpell::CombatCondition, CreatureSpellListTargeting::Comment, CreatureSpellList::Disabled, CreatureSpellListSpell::DisabledForAI, CreatureSpellListSpell::Flags, Field::GetCppString(), Field::GetInt32(), Field::GetUInt32(), SpellEntry::HasAttribute(), CreatureSpellListTargeting::Id, CreatureSpellListSpell::Id, CreatureSpellList::Id, CreatureSpellListSpell::InitialMax, CreatureSpellListSpell::InitialMin, SQLStorage::LookupEntry(), m_spellListContainer, CreatureSpellList::Name, CreatureSpellListTargeting::Param1, CreatureSpellListTargeting::Param2, CreatureSpellListTargeting::Param3, CreatureSpellListSpell::Position, CreatureSpellListSpell::Probability, Database::Query(), CreatureSpellListSpell::RepeatMax, CreatureSpellListSpell::RepeatMin, CreatureSpellListSpell::ScriptId, sLog, SPELL_ATTR_EX_NO_AUTOCAST_AI, SPELL_LIST_TARGETING_MAX, CreatureSpellListSpell::SpellId, sSpellTemplate, CreatureSpellListSpell::Target, CreatureSpellListTargeting::Type, CreatureSpellListTargeting::UnitCondition, and WorldDatabase.
LoadCreatureTemplates()
void ObjectMgr::LoadCreatureTemplates ()
if not set custom creature scale then load scale from CreatureDisplayInfo.dbc
Definition at line 459 of file ObjectMgr.cpp.
References CreatureInfo::DifficultyEntry, SQLStorageBase::GetMaxEntry(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), SQLStorage::LookupEntry(), MAX_DIFFICULTY, and sCreatureStorage.
LoadCreatureTemplateSpells()
void ObjectMgr::LoadCreatureTemplateSpells (std::shared_ptr< CreatureSpellListContainer > container)
Definition at line 10482 of file ObjectMgr.cpp.
References CreatureSpellListSpell::Availability, CREATURE_MAX_SPELLS, CreatureSpellListSpell::DisabledForAI, CreatureSpellListSpell::Flags, GetCreatureCooldownRange(), Field::GetUInt32(), SpellEntry::HasAttribute(), CreatureSpellListSpell::Id, CreatureSpellListSpell::InitialMax, CreatureSpellListSpell::InitialMin, SQLStorage::LookupEntry(), CreatureSpellListSpell::Position, CreatureSpellListSpell::Probability, Database::Query(), CreatureSpellListSpell::RepeatMax, CreatureSpellListSpell::RepeatMin, sCreatureStorage, CreatureSpellListSpell::ScriptId, sLog, SPELL_ATTR_EX_NO_AUTOCAST_AI, CreatureSpellListSpell::SpellId, sSpellTemplate, CreatureSpellListSpell::Target, and WorldDatabase.
LoadDungeonEncounters()
void ObjectMgr::LoadDungeonEncounters ()
Definition at line 8421 of file ObjectMgr.cpp.
References SQLStorage::Load(), sDungeonEncounterStore, and sLog.
Referenced by LoadSQLDBCs().
LoadEquipmentTemplates()
void ObjectMgr::LoadEquipmentTemplates ()
Definition at line 1567 of file ObjectMgr.cpp.
References EquipmentInfo::equipentry, SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), ItemEntry::InventoryType, INVTYPE_2HWEAPON, INVTYPE_HOLDABLE, INVTYPE_RANGED, INVTYPE_RANGEDRIGHT, INVTYPE_RELIC, INVTYPE_SHIELD, INVTYPE_THROWN, INVTYPE_WEAPON, INVTYPE_WEAPONMAINHAND, INVTYPE_WEAPONOFFHAND, SQLStorage::Load(), SQLStorage::LookupEntry(), sEquipmentStorage, sItemStore, and sLog.
LoadExplorationBaseXP()
void ObjectMgr::LoadExplorationBaseXP ()
Definition at line 7674 of file ObjectMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), mBaseXPTable, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadFishingBaseSkillLevel()
void ObjectMgr::LoadFishingBaseSkillLevel ()
Definition at line 9248 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetAreaEntryByAreaID(), Field::GetInt32(), QueryResult::GetRowCount(), Field::GetUInt32(), mFishingBaseForArea, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadGameObjectForQuests()
void ObjectMgr::LoadGameObjectForQuests ()
Definition at line 8972 of file ObjectMgr.cpp.
References GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), LootStore::HaveQuestLootFor(), LootTemplates_Gameobject, m_GOQuestInvolvedRelations, m_GOQuestRelations, mGameObjectForQuestSet, sGOStorage, sLog, and BarGoLink::step().
LoadGameobjectInfo()
std::vector< uint32 > ObjectMgr::LoadGameobjectInfo ()
Definition at line 7478 of file ObjectMgr.cpp.
References GameObjectInfo::areadamage, GameObjectInfo::barberChair, GameObjectInfo::button, GameObjectInfo::camera, GameObjectInfo::capturePoint, GameObjectInfo::chair, CheckAndFixGOCaptureMinTime(), CheckAndFixGOChairHeightId(), CheckGOConsumable(), CheckGOLinkedTrapId(), CheckGOLockId(), CheckGONoDamageImmuneId(), CheckGOSpellId(), GameObjectInfo::chest, DEFAULT_OBJECT_SCALE, GameObjectInfo::displayId, GameObjectInfo::door, ERROR_DB_STRICT_LOG, GameObjectInfo::fishinghole, GameObjectInfo::flagdrop, GameObjectInfo::flagstand, GAMEOBJECT_TYPE_AREADAMAGE, GAMEOBJECT_TYPE_BARBER_CHAIR, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CAPTURE_POINT, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_SPELLCASTER, GAMEOBJECT_TYPE_SUMMONING_RITUAL, GAMEOBJECT_TYPE_TRANSPORT, GAMEOBJECT_TYPE_TRAP, SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetRecordCount(), GameObjectInfo::goober, GameObjectInfo::id, SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), SQLStorage::LookupEntry(), m_guidsForMap, m_transportMaps, GameObjectInfo::moTransport, GameObjectInfo::questgiver, sGOStorage, GameObjectInfo::size, sLog, sPageTextStore, GameObjectInfo::spellcaster, GameObjectInfo::spellFocus, sScriptMgr, sSpellFocusObjectStore, sTaxiPathNodesByPath, GameObjectInfo::StringId, GameObjectInfo::trap, and GameObjectInfo::type.
LoadGameobjectInvolvedRelations()
void ObjectMgr::LoadGameobjectInvolvedRelations ()
Definition at line 8668 of file ObjectMgr.cpp.
References GAMEOBJECT_TYPE_QUESTGIVER, GetGameObjectInfo(), LoadQuestRelationsHelper(), m_GOQuestInvolvedRelations, sLog, and GameObjectInfo::type.
Referenced by LoadQuestRelations().
LoadGameObjectLocales()
void ObjectMgr::LoadGameObjectLocales ()
Definition at line 7319 of file ObjectMgr.cpp.
References GameObjectLocale::CastBarCaption, ERROR_DB_STRICT_LOG, QueryResult::Fetch(), Field::GetCppString(), GetGameObjectInfo(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_LOCALE, mGameObjectLocaleMap, GameObjectLocale::Name, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), and WorldDatabase.
LoadGameobjectQuestRelations()
void ObjectMgr::LoadGameobjectQuestRelations ()
Definition at line 8654 of file ObjectMgr.cpp.
References GAMEOBJECT_TYPE_QUESTGIVER, GetGameObjectInfo(), LoadQuestRelationsHelper(), m_GOQuestRelations, sLog, and GameObjectInfo::type.
Referenced by LoadQuestRelations().
LoadGameObjects()
void ObjectMgr::LoadGameObjects ()
Definition at line 2278 of file ObjectMgr.cpp.
References AddGameobjectToGrid(), GameObjectData::animprogress, CONFIG_BOOL_AUTOLOAD_ACTIVE, GameObjectInfo::displayId, GameObjectData::EntryPoolId, GameObjectInfo::ExtraFlags, GameObjectData::gameEvent, GAMEOBJECT_EXTRA_FLAG_ACTIVE, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_TRAP, Field::GetFloat(), GetGameObjectInfo(), Field::GetInt16(), Field::GetInt32(), GetMapDifficultyData(), GetRandomGameObjectEntry(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), GO_ANIMPROGRESS_DEFAULT, GameObjectData::goState, GameObjectData::GuidPoolId, GameObjectData::id, MapEntry::IsContinent(), GameObjectInfo::IsDespawnAtAction(), GameObjectData::IsNotPartOfPoolOrEvent(), QuaternionData::isUnit(), MaNGOS::IsValidMapCoord(), MapManager::IsValidMapCoord(), m_activeGameObjects, m_guidsForMap, m_transportMaps, GameObjectData::mapid, MAX_DIFFICULTY, MAX_GO_STATE, mGameObjectDataMap, GameObjectData::orientation, GameObjectData::OriginalZoneId, GameObjectData::path_rotation, GameObjectData::phaseMask, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, Database::PQuery(), Database::Query(), GameObjectData::rotation, sGameObjectDisplayInfoStore, SIZEFMTD, sLog, sMapStore, GameObjectData::spawnMask, GameObjectData::spawntimesecsmax, GameObjectData::spawntimesecsmin, sScriptMgr, BarGoLink::step(), sTerrainMgr, GameObjectData::StringId, sWorld, GameObjectInfo::type, TYPEID_GAMEOBJECT, QuaternionData::w, WorldDatabase, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
LoadGameObjectSpawnEntry()
void ObjectMgr::LoadGameObjectSpawnEntry ()
Definition at line 2513 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetGameObjectInfo(), QueryResult::GetRowCount(), Field::GetUInt32(), m_gameobjectSpawnEntryMap, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadGameObjectTemplateAddons()
void ObjectMgr::LoadGameObjectTemplateAddons ()
Definition at line 2560 of file ObjectMgr.cpp.
References GameObjectTemplateAddon::artKits, Field::GetUInt32(), m_gameobjectAddonTemplates, Database::Query(), sGameObjectArtKitStore, sLog, BarGoLink::step(), and WorldDatabase.
LoadGameTele()
void ObjectMgr::LoadGameTele ()
Definition at line 9366 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetCppString(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), MapManager::IsValidMapCoord(), m_GameTeleMap, GameTele::mapId, GameTele::name, QueryResult::NextRow(), GameTele::orientation, GameTele::position_x, GameTele::position_y, GameTele::position_z, Database::Query(), sLog, BarGoLink::step(), Utf8toWStr(), GameTele::wnameLow, WorldDatabase, and wstrToLower().
LoadGossipMenu()
void ObjectMgr::LoadGossipMenu (std::set< uint32 > & gossipScriptSet) private
Definition at line 9935 of file ObjectMgr.cpp.
References GossipMenus::conditionId, CreatureInfo::Entry, GossipMenus::entry, SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), GetGossipText(), SQLStorageBase::GetMaxEntry(), Field::GetUInt16(), Field::GetUInt32(), CreatureInfo::GossipMenuId, LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), m_mGossipMenusMap, Database::Query(), sConditionStorage, sCreatureStorage, GossipMenus::script_id, SCRIPT_TYPE_GOSSIP, sGOStorage, sLog, sScriptMgr, BarGoLink::step(), GossipMenus::text_id, and WorldDatabase.
Referenced by LoadGossipMenus().
LoadGossipMenuItems()
void ObjectMgr::LoadGossipMenuItems (std::set< uint32 > & gossipScriptSet) private
Definition at line 10026 of file ObjectMgr.cpp.
References GossipMenuItems::action_menu_id, GossipMenuItems::action_poi_id, GossipMenuItems::action_script_id, GossipMenuItems::box_broadcast_text, GossipMenuItems::box_coded, GossipMenuItems::box_money, GossipMenuItems::box_text, GossipMenuItems::conditionId, QueryResult::Fetch(), Field::GetCppString(), SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), Field::GetInt32(), SQLStorageBase::GetMaxEntry(), GetPointOfInterest(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), GOSSIP_ICON_CHAT, GOSSIP_ICON_MAX, GOSSIP_OPTION_MAX, GOSSIP_OPTION_NONE, CreatureInfo::GossipMenuId, GossipMenuItems::id, LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), m_mGossipMenuItemsMap, m_mGossipMenusMap, GossipMenuItems::menu_id, QueryResult::NextRow(), GossipMenuItems::npc_option_npcflag, CreatureInfo::NpcFlags, GossipMenuItems::option_broadcast_text, GossipMenuItems::option_icon, GossipMenuItems::option_id, GossipMenuItems::option_text, Database::Query(), sConditionStorage, sCreatureStorage, SCRIPT_TYPE_GOSSIP, sGOStorage, sLog, sScriptMgr, BarGoLink::step(), and WorldDatabase.
Referenced by LoadGossipMenus().
LoadGossipMenuItemsLocales()
void ObjectMgr::LoadGossipMenuItemsLocales ()
Definition at line 307 of file ObjectMgr.cpp.
References GossipMenuItemsLocale::BoxText, ERROR_DB_STRICT_LOG, QueryResult::Fetch(), GetGossipMenuItemsMapBounds(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt16(), MAKE_PAIR32, MAX_LOCALE, mGossipMenuItemsLocaleMap, QueryResult::NextRow(), GossipMenuItemsLocale::OptionText, Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), and WorldDatabase.
LoadGossipMenus()
void ObjectMgr::LoadGossipMenus ()
Definition at line 10199 of file ObjectMgr.cpp.
References LoadGossipMenu(), LoadGossipMenuItems(), SCRIPT_TYPE_GOSSIP, sLog, and sScriptMgr.
LoadGossipText()
void ObjectMgr::LoadGossipText ()
Definition at line 5973 of file ObjectMgr.cpp.
References Field::GetCppString(), Field::GetFloat(), Field::GetUInt32(), MAX_GOSSIP_TEXT_OPTIONS, mGossipText, GossipText::Options, GossipTextOption::Probability, Database::Query(), sLog, sObjectMgr, BarGoLink::step(), GossipTextOption::Text_0, GossipTextOption::Text_1, and WorldDatabase.
LoadGossipTextLocales()
void ObjectMgr::LoadGossipTextLocales ()
Definition at line 6095 of file ObjectMgr.cpp.
References ERROR_DB_STRICT_LOG, QueryResult::Fetch(), GetGossipText(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_LOCALE, mNpcTextLocaleMap, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), NpcTextLocale::Text_0, NpcTextLocale::Text_1, and WorldDatabase.
LoadGroups()
void ObjectMgr::LoadGroups ()
Definition at line 4603 of file ObjectMgr.cpp.
References AddGroup(), Group::BindToInstance(), CharacterDatabase, Group::Disband(), QueryResult::Fetch(), Field::GetBool(), GetGroupById(), Group::GetId(), QueryResult::GetRowCount(), ObjectGuid::GetString(), Field::GetUInt32(), Field::GetUInt8(), HIGHGUID_PLAYER, MapEntry::IsDungeon(), MapEntry::IsRaid(), Group::LoadGroupFromDB(), Group::LoadMemberFromDB(), MAX_DUNGEON_DIFFICULTY, MAX_RAID_DIFFICULTY, mGroupMap, QueryResult::NextRow(), Database::PExecute(), Database::Query(), REGULAR_DIFFICULTY, sLog, sMapPersistentStateMgr, sMapStore, and BarGoLink::step().
LoadInstanceEncounters()
void ObjectMgr::LoadInstanceEncounters ()
Definition at line 5719 of file ObjectMgr.cpp.
References ENCOUNTER_CREDIT_CAST_SPELL, ENCOUNTER_CREDIT_KILL_CREATURE, ENCOUNTER_CREDIT_SCRIPT, DungeonEncounterEntry::encounterName, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), SQLStorage::LookupEntry(), m_DungeonEncounters, m_DungeonEncountersByMap, DungeonEncounterEntry::mapId, QueryResult::NextRow(), Database::Query(), sCreatureStorage, sDungeonEncounterStore, SIZEFMTD, sLog, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
LoadInstanceTemplate()
void ObjectMgr::LoadInstanceTemplate ()
Definition at line 5802 of file ObjectMgr.cpp.
References SQLStorage::EraseEntry(), GetInstanceTemplate(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), MapEntry::Instanceable(), MapEntry::IsContinent(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), InstanceTemplate::map, MapEntry::MapID, InstanceTemplate::parent, sInstanceTemplate, sLog, and sMapStore.
LoadItemConverts()
void ObjectMgr::LoadItemConverts ()
Definition at line 3415 of file ObjectMgr.cpp.
References ItemPrototype::AllowableRace, QueryResult::Fetch(), ItemPrototype::Flags, QueryResult::GetRowCount(), Field::GetUInt32(), ITEM_FLAG_IS_BOUND_TO_ACCOUNT, SQLStorage::LookupEntry(), m_ItemConvert, QueryResult::NextRow(), Database::Query(), ItemPrototype::RequiredReputationFaction, sItemStorage, sLog, BarGoLink::step(), and WorldDatabase.
LoadItemExpireConverts()
void ObjectMgr::LoadItemExpireConverts ()
Definition at line 3478 of file ObjectMgr.cpp.
References ItemPrototype::Duration, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_ItemExpireConvert, QueryResult::NextRow(), Database::Query(), sItemStorage, sLog, BarGoLink::step(), and WorldDatabase.
LoadItemLocales()
void ObjectMgr::LoadItemLocales ()
Definition at line 2757 of file ObjectMgr.cpp.
References ItemLocale::Description, ERROR_DB_STRICT_LOG, QueryResult::Fetch(), GetItemPrototype(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_LOCALE, mItemLocaleMap, ItemLocale::Name, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), and WorldDatabase.
LoadItemPrototypes()
void ObjectMgr::LoadItemPrototypes ()
Definition at line 2834 of file ObjectMgr.cpp.
References ALLIANCE, ItemPrototype::AllowableClass, ItemPrototype::AllowableRace, ItemPrototype::Area, BAG_FAMILY_MASK_CURRENCY_TOKENS, ItemPrototype::BagFamily, ItemPrototype::Bonding, ItemPrototype::BuyCount, ItemPrototype::Class, CLASSMASK_ALL_PLAYABLE, _Socket::Color, ItemPrototype::ContainerSlots, ItemPrototype::Damage, _Damage::DamageType, ItemPrototype::DisenchantID, ItemPrototype::DisplayInfoID, ItemPrototype::Duration, ERROR_DB_STRICT_LOG, ItemPrototype::ExtraFlags, ItemPrototype::Flags, ItemPrototype::Flags2, ItemPrototype::FoodType, ItemPrototype::GemProperties, GetAreaEntryByAreaID(), GetItemEnchantMod(), GetItemPrototype(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), ItemPrototype::HolidayId, HORDE, SpellEntry::Id, ItemPrototype::InventoryType, INVTYPE_BAG, INVTYPE_NON_EQUIP, ITEM_CLASS_ARMOR, ITEM_CLASS_MISC, ITEM_CLASS_WEAPON, ITEM_EXTRA_ALL, ITEM_EXTRA_REAL_TIME_DURATION, ITEM_FLAG2_FACTION_ALLIANCE, ITEM_FLAG2_FACTION_HORDE, ITEM_FLAG_HAS_LOOT, ITEM_FLAG_IS_MILLABLE, ITEM_FLAG_IS_PROSPECTABLE, ITEM_MOD_SPELL_DAMAGE_DONE, ITEM_MOD_SPELL_HEALING_DONE, ITEM_QUALITY_EPIC, ITEM_QUALITY_NORMAL, ITEM_QUALITY_UNCOMMON, ITEM_SPELLTRIGGER_CHANCE_ON_HIT, ITEM_SPELLTRIGGER_LEARN_SPELL_ID, ITEM_SPELLTRIGGER_ON_USE, ItemPrototype::ItemId, CharStartOutfitEntry::ItemId, ItemPrototype::ItemLimitCategory, ItemPrototype::ItemSet, ItemPrototype::ItemStat, _ItemStat::ItemStatType, _ItemStat::ItemStatValue, SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), ItemPrototype::LockID, SQLStorage::LookupEntry(), ItemPrototype::Map, ItemPrototype::Material, MAX_BAG_SIZE, MAX_BIND_TYPE, MAX_INVTYPE, MAX_ITEM_CLASS, MAX_ITEM_MOD, MAX_ITEM_PROTO_DAMAGES, MAX_ITEM_PROTO_SOCKETS, MAX_ITEM_PROTO_SPELLS, MAX_ITEM_PROTO_STATS, MAX_ITEM_QUALITY, MAX_ITEM_SPELLTRIGGER, MAX_PET_DIET, MAX_REPUTATION_RANK, MAX_SHEATHETYPE, MAX_SKILL_TYPE, MAX_SPELL_SCHOOL, ItemPrototype::MaxCount, MaxItemSubclassValues, MIN_REPUTATION_RANK, ItemPrototype::PageText, ItemPrototype::Quality, RACEMASK_ALL_PLAYABLE, ItemPrototype::RandomProperty, ItemPrototype::RandomSuffix, ItemPrototype::RequiredDisenchantSkill, ItemPrototype::RequiredReputationFaction, ItemPrototype::RequiredReputationRank, ItemPrototype::RequiredSkill, ItemPrototype::RequiredSpell, sCharStartOutfitStore, sCurrencyTypesStore, sFactionStore, sGemPropertiesStore, ItemPrototype::Sheath, SHEATHETYPE_NONE, sHolidaysStore, sItemBagFamilyStore, sItemLimitCategoryStore, sItemRandomPropertiesStore, sItemRandomSuffixStore, sItemSetStore, sItemSpellCategoryStore, sItemStorage, sItemStore, sLockStore, sLog, sMapStore, ItemPrototype::Socket, SOCKET_COLOR_ALL, sPageTextStore, SpellEntry::speed, SPELL_ID_GENERIC_LEARN, SPELL_ID_GENERIC_LEARN_PET, _Spell::SpellId, SpellEntry::SpellName, ItemPrototype::Spells, _Spell::SpellTrigger, sSpellTemplate, ItemPrototype::Stackable, ItemPrototype::StatsCount, sTotemCategoryStore, ItemPrototype::SubClass, ItemPrototype::TotemCategory, and ItemPrototype::Unk0.
LoadItemRequiredTarget()
void ObjectMgr::LoadItemRequiredTarget ()
Definition at line 3538 of file ObjectMgr.cpp.
References QueryResult::Fetch(), SQLMultiStorage::SQLMSIteratorBounds< T >::first, SQLMultiStorage::getBounds(), QueryResult::GetRowCount(), Field::GetUInt32(), ITEM_SPELLTRIGGER_ON_USE, SQLStorage::LookupEntry(), m_ItemRequiredTarget, MAX_EFFECT_INDEX, MAX_ITEM_REQ_TARGET_TYPE, QueryResult::NextRow(), Database::Query(), sCreatureStorage, SQLMultiStorage::SQLMSIteratorBounds< T >::second, sItemStorage, sLog, ItemPrototype::Spells, sSpellScriptTargetStorage, sSpellTemplate, BarGoLink::step(), TARGET_UNIT, TARGET_UNIT_ENEMY, and WorldDatabase.
LoadMailLevelRewards()
void ObjectMgr::LoadMailLevelRewards ()
Definition at line 9499 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetCreatureTemplate(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), m_mailLevelRewardMap, MAX_LEVEL, QueryResult::NextRow(), Database::Query(), RACEMASK_ALL_PLAYABLE, sLog, sMailTemplateStore, BarGoLink::step(), and WorldDatabase.
LoadMangosStrings() [1/2]
bool ObjectMgr::LoadMangosStrings () inline
Definition at line 720 of file ObjectMgr.h.
References LoadMangosStrings(), MAX_MANGOS_STRING_ID, MIN_MANGOS_STRING_ID, and WorldDatabase.
Referenced by LoadMangosStrings().
LoadMangosStrings() [2/2]
bool ObjectMgr::LoadMangosStrings (DatabaseType & db, char const * table, int32 min_value, int32 max_value, bool extra_content)
Definition at line 9067 of file ObjectMgr.cpp.
References _DoStringError(), MangosStringLocale::broadcastText, CHAT_TYPE_MAX, CHAT_TYPE_SAY, MangosStringLocale::Content, MangosStringLocale::Emote, EMOTE_ONESHOT_NONE, QueryResult::Fetch(), GetBroadcastText(), Field::GetCppString(), Field::GetInt32(), GetLanguageDescByID(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), LANG_UNIVERSAL, MangosStringLocale::LanguageId, m_loadedStringCount, MAX_LOCALE, MIN_MANGOS_STRING_ID, mMangosStringLocaleMap, QueryResult::NextRow(), Database::PQuery(), sEmotesStore, sLog, MangosStringLocale::SoundId, sSoundEntriesStore, BarGoLink::step(), and MangosStringLocale::Type.
LoadNpcGossips()
void ObjectMgr::LoadNpcGossips ()
Definition at line 9887 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetCreatureData(), GetGossipText(), QueryResult::GetRowCount(), Field::GetUInt32(), m_mCacheNpcTextIdMap, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadNPCSpellClickSpells()
void ObjectMgr::LoadNPCSpellClickSpells ()
Definition at line 8244 of file ObjectMgr.cpp.
References SpellClickInfo::castFlags, SpellClickInfo::conditionId, QueryResult::Fetch(), Field::GetBool(), GetCreatureTemplate(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), SQLStorage::LookupEntry(), mQuestTemplates, mSpellClickInfoMap, QueryResult::NextRow(), Database::Query(), SpellClickInfo::questEnd, SpellClickInfo::questStart, SpellClickInfo::questStartCanActive, sConditionStorage, sLog, SpellClickInfo::spellId, sSpellTemplate, BarGoLink::step(), UNIT_NPC_FLAG_SPELLCLICK, and WorldDatabase.
LoadPageTextLocales()
void ObjectMgr::LoadPageTextLocales ()
Definition at line 5664 of file ObjectMgr.cpp.
References ERROR_DB_STRICT_LOG, QueryResult::Fetch(), Field::GetCppString(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), MAX_LOCALE, mPageTextLocaleMap, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, sPageTextStore, BarGoLink::step(), PageTextLocale::Text, and WorldDatabase.
LoadPageTexts()
void ObjectMgr::LoadPageTexts ()
Definition at line 5622 of file ObjectMgr.cpp.
References SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), SQLStorage::Load(), SQLStorage::LookupEntry(), PageText::Next_Page, sLog, and sPageTextStore.
LoadPetLevelInfo()
void ObjectMgr::LoadPetLevelInfo ()
Definition at line 3639 of file ObjectMgr.cpp.
References PetLevelInfo::armor, CONFIG_UINT32_MAX_PLAYER_LEVEL, DETAIL_LOG, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), PetLevelInfo::health, SQLStorage::LookupEntry(), PetLevelInfo::mana, MAX_STATS, QueryResult::NextRow(), petInfo, Database::Query(), sCreatureStorage, sLog, PetLevelInfo::stats, BarGoLink::step(), STRONG_MAX_LEVEL, sWorld, Log::WaitBeforeContinueIfNeed(), and WorldDatabase.
LoadPetNames()
void ObjectMgr::LoadPetNames ()
Definition at line 7732 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetBool(), QueryResult::GetRowCount(), Field::GetString(), Field::GetUInt32(), QueryResult::NextRow(), PetHalfName0, PetHalfName1, Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadPetNumber()
void ObjectMgr::LoadPetNumber ()
Definition at line 7769 of file ObjectMgr.cpp.
References CharacterDatabase, QueryResult::Fetch(), IdGenerator< T >::GetNextAfterMaxUsed(), m_PetNumbers, Database::Query(), IdGenerator< T >::Set(), sLog, and BarGoLink::step().
LoadPlayerInfo()
void ObjectMgr::LoadPlayerInfo ()
Definition at line 3752 of file ObjectMgr.cpp.
References PlayerInfo::action, PlayerInfo::areaId, PlayerClassLevelInfo::basehealth, PlayerClassLevelInfo::basemana, CLASS_DEATH_KNIGHT, CLASS_WARRIOR, SkillRaceClassInfoEntry::classMask, CLASSMASK_ALL_PLAYABLE, CONFIG_UINT32_EXPANSION, CONFIG_UINT32_MAX_PLAYER_LEVEL, DETAIL_LOG, PlayerInfo::displayId_f, PlayerInfo::displayId_m, EXPANSION_TBC, EXPANSION_WOTLK, QueryResult::Fetch(), Field::GetFloat(), GetItemPrototype(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), Player::IsActionButtonDataValid(), MapManager::IsValidMapCoord(), PlayerInfo::item, PlayerClassInfo::levelInfo, PlayerInfo::levelInfo, SQLStorage::LookupEntry(), PlayerInfo::mapId, MAX_CLASSES, MAX_RACES, MAX_SKILL_STEP, MAX_STATS, SkillTiersEntry::maxSkillValue, ChrRacesEntry::model_f, ChrRacesEntry::model_m, mPlayerXPperLevel, QueryResult::NextRow(), PlayerInfo::orientation, playerClassInfo, playerInfo, PlayerInfo::positionX, PlayerInfo::positionY, PlayerInfo::positionZ, Database::Query(), RACE_BLOODELF, RACE_DRAENEI, RACE_HUMAN, SkillRaceClassInfoEntry::raceMask, RACEMASK_ALL_PLAYABLE, sChrClassesStore, sChrRacesStore, PlayerCreateInfoSkill::SkillId, SkillRaceClassInfoEntry::skillTierId, sLog, sMapStore, PlayerInfo::spell, sSkillLineStore, sSkillTiersStore, sSpellMgr, sSpellTemplate, PlayerLevelInfo::stats, PlayerCreateInfoSkill::Step, BarGoLink::step(), STRONG_MAX_LEVEL, sWorld, Log::WaitBeforeContinueIfNeed(), and WorldDatabase.
LoadPointOfInterestLocales()
void ObjectMgr::LoadPointOfInterestLocales ()
Definition at line 395 of file ObjectMgr.cpp.
References ERROR_DB_STRICT_LOG, QueryResult::Fetch(), Field::GetCppString(), GetOrNewStorageLocaleIndexFor(), GetPointOfInterest(), QueryResult::GetRowCount(), Field::GetUInt32(), PointOfInterestLocale::IconName, MAX_LOCALE, mPointOfInterestLocaleMap, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, BarGoLink::step(), and WorldDatabase.
LoadPointsOfInterest()
void ObjectMgr::LoadPointsOfInterest ()
Definition at line 8113 of file ObjectMgr.cpp.
References PointOfInterest::data, QueryResult::Fetch(), PointOfInterest::flags, Field::GetCppString(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), PointOfInterest::icon, PointOfInterest::icon_name, MaNGOS::IsValidMapCoord(), mPointsOfInterest, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), WorldDatabase, PointOfInterest::x, and PointOfInterest::y.
LoadQuestAreaTriggers()
void ObjectMgr::LoadQuestAreaTriggers ()
Definition at line 6546 of file ObjectMgr.cpp.
References QueryResult::Fetch(), GetQuestTemplate(), QueryResult::GetRowCount(), Field::GetUInt32(), Quest::HasSpecialFlag(), mQuestAreaTriggerMap, QueryResult::NextRow(), Database::Query(), QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT, sAreaTriggerStore, sLog, BarGoLink::step(), and WorldDatabase.
LoadQuestgiverGreeting()
void ObjectMgr::LoadQuestgiverGreeting ()
Definition at line 6181 of file ObjectMgr.cpp.
References QuestgiverGreeting::emoteDelay, QuestgiverGreeting::emoteId, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetString(), Field::GetUInt32(), SQLStorage::LookupEntry(), SQLHashStorage::LookupEntry(), m_questgiverGreetingMap, QueryResult::NextRow(), Database::Query(), QUESTGIVER_CREATURE, QUESTGIVER_GAMEOBJECT, sCreatureStorage, sEmotesStore, sGOStorage, sLog, BarGoLink::step(), QuestgiverGreeting::text, and WorldDatabase.
LoadQuestgiverGreetingLocales()
void ObjectMgr::LoadQuestgiverGreetingLocales ()
Definition at line 6251 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetCppString(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), QuestgiverGreetingLocale::localeText, SQLStorage::LookupEntry(), SQLHashStorage::LookupEntry(), m_questgiverGreetingLocaleMap, MAX_LOCALE, QueryResult::NextRow(), Database::Query(), QUESTGIVER_CREATURE, QUESTGIVER_GAMEOBJECT, sCreatureStorage, sGOStorage, sLog, BarGoLink::step(), and WorldDatabase.
LoadQuestLocales()
void ObjectMgr::LoadQuestLocales ()
Definition at line 5470 of file ObjectMgr.cpp.
References QuestLocale::CompletedText, QuestLocale::Details, QuestLocale::EndText, ERROR_DB_STRICT_LOG, QueryResult::Fetch(), GetOrNewStorageLocaleIndexFor(), GetQuestTemplate(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_LOCALE, mQuestLocaleMap, QueryResult::NextRow(), QuestLocale::Objectives, QuestLocale::ObjectiveText, QuestLocale::OfferRewardText, Database::Query(), QuestLocale::RequestItemsText, sLog, BarGoLink::step(), QuestLocale::Title, and WorldDatabase.
LoadQuestPOI()
void ObjectMgr::LoadQuestPOI ()
Definition at line 8166 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetInt32(), QueryResult::GetRowCount(), Field::GetUInt32(), mQuestPOIMap, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadQuestRelations()
void ObjectMgr::LoadQuestRelations () inline
Definition at line 707 of file ObjectMgr.h.
References LoadCreatureInvolvedRelations(), LoadCreatureQuestRelations(), LoadGameobjectInvolvedRelations(), and LoadGameobjectQuestRelations().
LoadQuestRelationsHelper()
void ObjectMgr::LoadQuestRelationsHelper (QuestRelationsMap & map, char const * table) private
Definition at line 8607 of file ObjectMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), mQuestTemplates, QueryResult::NextRow(), Database::PQuery(), sLog, BarGoLink::step(), and WorldDatabase.
Referenced by LoadCreatureInvolvedRelations(), LoadCreatureQuestRelations(), LoadGameobjectInvolvedRelations(), and LoadGameobjectQuestRelations().
LoadQuests()
void ObjectMgr::LoadQuests ()
Definition at line 4775 of file ObjectMgr.cpp.
References Quest::BreadcrumbForQuestId, Quest::CharTitleId, CLASSMASK_ALL_PLAYABLE, Quest::DependentBreadcrumbQuests, SpellEntry::Effect, SpellEntry::EffectMiscValue, Quest::ExclusiveGroup, QueryResult::Fetch(), GetAreaEntryByAreaID(), Quest::GetBreadcrumbForQuestId(), Quest::GetCharTitleId(), Quest::GetNextQuestId(), Quest::GetPrevQuestId(), Quest::GetQuestId(), Quest::GetQuestMethod(), QueryResult::GetRowCount(), GetTalentSpellCost(), Quest::HasQuestFlag(), Quest::HasSpecialFlag(), SpellEntry::Id, SpellMgr::IsSpellValid(), Quest::LimitTime, SQLStorage::LookupEntry(), SQLHashStorage::LookupEntry(), m_ExclusiveQuestGroups, Quest::m_QuestFlags, Quest::m_SpecialFlags, MAX_EFFECT_INDEX, mQuestTemplates, Quest::NextQuestId, Quest::NextQuestInChain, QueryResult::NextRow(), Quest::PlayersSlain, Quest::PrevQuestId, Quest::prevQuests, Database::Query(), QUEST_FLAGS_AUTO_REWARDED, QUEST_FLAGS_DAILY, QUEST_FLAGS_WEEKLY, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, QUEST_SOURCE_ITEM_IDS_COUNT, QUEST_SPECIAL_FLAG_DB_ALLOWED, QUEST_SPECIAL_FLAG_DELIVER, QUEST_SPECIAL_FLAG_EXPLORATION_OR_EVENT, QUEST_SPECIAL_FLAG_KILL_OR_CAST, QUEST_SPECIAL_FLAG_MONTHLY, QUEST_SPECIAL_FLAG_REPEATABLE, QUEST_SPECIAL_FLAG_SPEAKTO, QUEST_SPECIAL_FLAG_TIMED, QUEST_SPECIAL_FLAGS_PLAYER_KILL, Quest::QuestId, RACEMASK_ALL_PLAYABLE, Quest::RepObjectiveFaction, Quest::RepObjectiveValue, ReputationMgr::Reputation_Cap, Quest::ReqCreatureOrGOCount, Quest::ReqCreatureOrGOId, Quest::ReqItemCount, Quest::ReqItemId, Quest::ReqSourceCount, Quest::ReqSourceId, Quest::ReqSpell, Quest::RequiredClasses, Quest::RequiredMaxRepFaction, Quest::RequiredMaxRepValue, Quest::RequiredMinRepFaction, Quest::RequiredMinRepValue, Quest::RequiredRaces, Quest::RequiredSkill, Quest::RequiredSkillValue, Quest::RewChoiceItemCount, Quest::RewChoiceItemId, Quest::RewItemCount, Quest::RewItemId, Quest::RewMailDelaySecs, Quest::RewMailTemplateId, Quest::RewRepFaction, Quest::RewRepValue, Quest::RewRepValueId, Quest::RewSpell, Quest::RewSpellCast, sCharTitlesStore, sCreatureStorage, Quest::SetSpecialFlag(), sFactionStore, sGOStorage, sItemStorage, SIZEFMTD, sLog, sMailTemplateStore, sObjectMgr, SPELL_EFFECT_QUEST_COMPLETE, SPELL_EFFECT_SEND_EVENT, sQuestSortStore, Quest::SrcItemCount, Quest::SrcItemId, Quest::SrcSpell, sSkillLineStore, sSpellTemplate, BarGoLink::step(), sWorld, WorldDatabase, and Quest::ZoneOrSort.
LoadReputationOnKill()
void ObjectMgr::LoadReputationOnKill ()
Definition at line 7919 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetBool(), GetCreatureTemplate(), Field::GetInt32(), QueryResult::GetRowCount(), Field::GetUInt32(), ReputationOnKillEntry::is_teamaward1, ReputationOnKillEntry::is_teamaward2, mRepOnKill, QueryResult::NextRow(), Database::Query(), ReputationOnKillEntry::repfaction1, ReputationOnKillEntry::repfaction2, ReputationOnKillEntry::reputation_max_cap1, ReputationOnKillEntry::reputation_max_cap2, ReputationOnKillEntry::repvalue1, ReputationOnKillEntry::repvalue2, sFactionStore, sLog, BarGoLink::step(), ReputationOnKillEntry::team_dependent, and WorldDatabase.
LoadReputationRewardRate()
void ObjectMgr::LoadReputationRewardRate ()
Definition at line 7850 of file ObjectMgr.cpp.
References RepRewardRate::creature_rate, QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), m_RepRewardRateMap, QueryResult::NextRow(), Database::Query(), RepRewardRate::quest_rate, sFactionStore, sLog, RepRewardRate::spell_rate, BarGoLink::step(), and WorldDatabase.
LoadReputationSpilloverTemplate()
void ObjectMgr::LoadReputationSpilloverTemplate ()
Definition at line 7996 of file ObjectMgr.cpp.
References RepSpilloverTemplate::faction, RepSpilloverTemplate::faction_rank, RepSpilloverTemplate::faction_rate, QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), m_RepSpilloverTemplateMap, MAX_REPUTATION_RANK, MAX_SPILLOVER_FACTIONS, QueryResult::NextRow(), Database::Query(), FactionEntry::reputationListID, sFactionStore, sLog, BarGoLink::step(), FactionEntry::team, and WorldDatabase.
LoadReservedPlayersNames()
void ObjectMgr::LoadReservedPlayersNames ()
Definition at line 8706 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetCppString(), QueryResult::GetRowCount(), m_ReservedNames, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), Utf8toWStr(), WorldDatabase, and wstrToLower().
LoadSpawnGroups()
void ObjectMgr::LoadSpawnGroups ()
Definition at line 1193 of file ObjectMgr.cpp.
References SpawnGroupEntry::Active, SpawnGroupRandomEntry::Chance, SpawnGroupDbGuids::Chance, CONFIG_BOOL_AUTOLOAD_ACTIVE, CREATURE_EXTRA_FLAG_ACTIVE, SpawnGroupDbGuids::DbGuid, SpawnGroupEntry::DbGuids, SpawnGroupEntry::EnabledByDefault, SpawnGroupRandomEntry::Entry, SpawnGroupEntry::EquallyChanced, SpawnGroupEntry::ExplicitlyChanced, SpawnGroupEntry::Flags, SpawnGroupEntry::formationEntry, GetAllRandomCreatureEntries(), GetAllRandomGameObjectEntries(), Field::GetCppString(), GetCreatureData(), GetCreatureTemplate(), Field::GetFloat(), GetGameObjectInfo(), GetGOData(), Field::GetInt32(), Field::GetUInt32(), SpawnGroupEntry::HasChancedSpawns, CreatureData::id, GameObjectData::id, SpawnGroupRandomEntry::Id, SpawnGroupDbGuids::Id, SpawnGroupEntry::Id, CreatureData::IsNotPartOfPoolOrEvent(), GameObjectData::IsNotPartOfPoolOrEvent(), SQLStorage::LookupEntry(), m_spawnGroupContainer, m_worldStateExpressionMgr, MAX_DB_MOTION_TYPE, SpawnGroupRandomEntry::MaxCount, SpawnGroupEntry::MaxCount, SpawnGroupRandomEntry::MinCount, SpawnGroupEntry::Name, SpawnGroupDbGuids::OwnEntry, Database::Query(), SpawnGroupEntry::RandomEntries, SpawnGroupDbGuids::RandomEntry, RemoveCreatureFromGrid(), RemoveGameobjectFromGrid(), sConditionStorage, sLog, SpawnGroupDbGuids::SlotId, SPAWN_GROUP_CREATURE, SPAWN_GROUP_FORMATION_TYPE_COUNT, SPAWN_GROUP_GAMEOBJECT, CreatureData::spawnMask, GameObjectData::spawnMask, sScriptMgr, SpawnGroupEntry::StringId, sWorld, SpawnGroupEntry::Type, TYPEID_GAMEOBJECT, TYPEID_UNIT, WorldDatabase, SpawnGroupEntry::WorldStateCondition, and SpawnGroupEntry::WorldStateExpression.
LoadSpellTemplate()
void ObjectMgr::LoadSpellTemplate ()
Definition at line 8359 of file ObjectMgr.cpp.
References SQLStorage::EraseEntry(), SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), SQLStorage::Load(), SQLStorage::LookupEntry(), sLog, SpellEntry::SpellFamilyFlags, sSpellCones, and sSpellTemplate.
Referenced by LoadSQLDBCs().
LoadSQLDBCs()
void ObjectMgr::LoadSQLDBCs ()
Definition at line 8433 of file ObjectMgr.cpp.
References LoadAreaGroups(), LoadDungeonEncounters(), and LoadSpellTemplate().
LoadTavernAreaTriggers()
void ObjectMgr::LoadTavernAreaTriggers ()
Definition at line 6609 of file ObjectMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), mTavernAreaTriggerSet, QueryResult::NextRow(), Database::Query(), sAreaTriggerStore, sLog, BarGoLink::step(), and WorldDatabase.
LoadTaxiShortcuts()
void ObjectMgr::LoadTaxiShortcuts ()
Definition at line 6684 of file ObjectMgr.cpp.
References AddTaxiShortcut(), QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), m_TaxiShortcutMap, QueryResult::NextRow(), Database::Query(), Path< PathElem, PathNode >::size(), sLog, sTaxiPathNodesByPath, sTaxiPathStore, BarGoLink::step(), and WorldDatabase.
LoadTrainerGreetingLocales()
void ObjectMgr::LoadTrainerGreetingLocales ()
Definition at line 6382 of file ObjectMgr.cpp.
References QueryResult::Fetch(), Field::GetCppString(), GetOrNewStorageLocaleIndexFor(), QueryResult::GetRowCount(), Field::GetUInt32(), TrainerGreetingLocale::localeText, SQLStorage::LookupEntry(), m_trainerGreetingLocaleMap, MAX_LOCALE, QueryResult::NextRow(), Database::Query(), sCreatureStorage, sLog, BarGoLink::step(), and WorldDatabase.
LoadTrainerGreetings()
void ObjectMgr::LoadTrainerGreetings ()
Definition at line 6341 of file ObjectMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetString(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_trainerGreetingMap, QueryResult::NextRow(), Database::Query(), sCreatureStorage, sLog, BarGoLink::step(), TrainerGreeting::text, and WorldDatabase.
LoadTrainers() [1/2]
void ObjectMgr::LoadTrainers () inline
Definition at line 806 of file ObjectMgr.h.
References LoadTrainers().
Referenced by LoadTrainers(), and LoadTrainerTemplates().
LoadTrainers() [2/2]
void ObjectMgr::LoadTrainers (char const * tableName, bool isTemplates) private
Definition at line 9563 of file ObjectMgr.cpp.
References TrainerSpell::conditionId, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, ERROR_DB_STRICT_LOG, GetCreatureTemplate(), GetNpcTrainerTemplateSpells(), GetTalentSpellCost(), Field::GetUInt16(), Field::GetUInt32(), SpellMgr::IsProfessionSpell(), TrainerSpell::isProvidedReqLevel, SpellMgr::IsSpellValid(), TrainerSpell::learnedSpell, SQLStorage::LookupEntry(), m_mCacheTrainerSpellMap, m_mCacheTrainerTemplateSpellMap, MAX_EFFECT_INDEX, CreatureInfo::NpcFlags, Database::PQuery(), TrainerSpell::reqAbility, TrainerSpell::reqLevel, TrainerSpell::reqSkill, TrainerSpell::reqSkillValue, sConditionStorage, sLog, TrainerSpell::spell, SPELL_EFFECT_LEARN_SPELL, TrainerSpell::spellCost, SpellEntry::spellLevel, TrainerSpellData::spellList, sSpellMgr, sSpellTemplate, BarGoLink::step(), TARGET_NONE, TARGET_UNIT_CASTER, CreatureInfo::TrainerTemplateId, TrainerSpellData::trainerType, UNIT_NPC_FLAG_TRAINER, and WorldDatabase.
LoadTrainerTemplates()
void ObjectMgr::LoadTrainerTemplates ()
Definition at line 9734 of file ObjectMgr.cpp.
References CreatureInfo::Entry, SQLStorageBase::GetMaxEntry(), LoadTrainers(), SQLStorage::LookupEntry(), m_mCacheTrainerTemplateSpellMap, sCreatureStorage, sLog, and CreatureInfo::TrainerTemplateId.
LoadVendors() [1/2]
void ObjectMgr::LoadVendors () inline
Definition at line 804 of file ObjectMgr.h.
References LoadVendors().
Referenced by LoadVendors(), and LoadVendorTemplates().
LoadVendors() [2/2]
void ObjectMgr::LoadVendors (char const * tableName, bool isTemplates) private
Definition at line 9769 of file ObjectMgr.cpp.
References VendorItemData::AddItem(), QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), IsVendorItemValid(), m_mCacheVendorItemMap, m_mCacheVendorTemplateItemMap, QueryResult::NextRow(), Database::PQuery(), sLog, BarGoLink::step(), and WorldDatabase.
LoadVendorTemplates()
void ObjectMgr::LoadVendorTemplates ()
Definition at line 9821 of file ObjectMgr.cpp.
References CreatureInfo::Entry, SQLStorageBase::GetMaxEntry(), LoadVendors(), SQLStorage::LookupEntry(), m_mCacheVendorTemplateItemMap, sCreatureStorage, sLog, and CreatureInfo::VendorTemplateId.
LoadWorldStateNames()
void ObjectMgr::LoadWorldStateNames ()
Definition at line 5892 of file ObjectMgr.cpp.
References Field::GetCppString(), Field::GetInt32(), WorldStateName::Id, m_worldStateNames, WorldStateName::Name, Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadWorldTemplate()
void ObjectMgr::LoadWorldTemplate ()
Definition at line 5862 of file ObjectMgr.cpp.
References SQLStorage::EraseEntry(), SQLStorageBase::GetMaxEntry(), SQLStorageBase::GetRecordCount(), GetWorldTemplate(), MapEntry::Instanceable(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), WorldTemplate::map, sLog, sMapStore, and sWorldTemplate.
NewGOData()
GameObjectData& ObjectMgr::NewGOData (uint32 guid) inline
Definition at line 1017 of file ObjectMgr.h.
References mGameObjectDataMap.
NewOrExistCreatureData()
CreatureData& ObjectMgr::NewOrExistCreatureData (uint32 guid) inline
Definition at line 900 of file ObjectMgr.h.
References mCreatureDataMap.
PackGroupIds()
void ObjectMgr::PackGroupIds ()
Definition at line 7159 of file ObjectMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), QueryResult::Fetch(), Field::GetUInt32(), QueryResult::NextRow(), Database::PExecute(), Database::Query(), sLog, and BarGoLink::step().
RemoveArenaTeam()
void ObjectMgr::RemoveArenaTeam (uint32 Id)
Definition at line 10367 of file ObjectMgr.cpp.
References mArenaTeamMap.
RemoveCreatureFromGrid()
void ObjectMgr::RemoveCreatureFromGrid (uint32 guid, CreatureData const * data)
Definition at line 2262 of file ObjectMgr.cpp.
References MaNGOS::ComputeCellPair(), MAKE_PAIR32, CreatureData::mapid, mMapObjectGuids, CreatureData::posX, CreatureData::posY, CreatureData::spawnMask, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by DeleteCreatureData(), and LoadSpawnGroups().
RemoveGameobjectFromGrid()
void ObjectMgr::RemoveGameobjectFromGrid (uint32 guid, GameObjectData const * data)
Definition at line 2625 of file ObjectMgr.cpp.
References MaNGOS::ComputeCellPair(), MAKE_PAIR32, GameObjectData::mapid, mMapObjectGuids, GameObjectData::posX, GameObjectData::posY, GameObjectData::spawnMask, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by DeleteGOData(), and LoadSpawnGroups().
RemoveGroup()
void ObjectMgr::RemoveGroup (Group * group)
Definition at line 10357 of file ObjectMgr.cpp.
References Group::GetId(), and mGroupMap.
RemoveVendorItem()
bool ObjectMgr::RemoveVendorItem (uint32 entry, uint32 item)
Definition at line 10225 of file ObjectMgr.cpp.
References m_mCacheVendorItemMap, Database::PExecuteLog(), and WorldDatabase.
ReturnOrDeleteOldMails()
void ObjectMgr::ReturnOrDeleteOldMails (bool serverUp)
Parameters
serverUp true if the server is already running, false when the server is started
Definition at line 6438 of file ObjectMgr.cpp.
References Mail::AddItem(), CharacterDatabase, Mail::checked, Mail::COD, DAY, DEBUG_LOG, Mail::deliver_time, Mail::expire_time, QueryResult::Fetch(), Field::GetBool(), ObjectGuid::GetCounter(), Field::GetInt16(), GetPlayer(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), HIGHGUID_PLAYER, Mail::items, MAIL_CHECK_MASK_COD_PAYMENT, MAIL_CHECK_MASK_RETURNED, MAIL_NORMAL, Mail::mailTemplateId, Mail::messageID, Mail::messageType, QueryResult::NextRow(), Database::PExecute(), Database::PQuery(), Mail::receiverGuid, Mail::sender, sLog, BarGoLink::step(), and UI64FMTD.
SetDbc2StorageLocaleIndex()
void ObjectMgr::SetDbc2StorageLocaleIndex (LocaleConstant loc) inline
Definition at line 1046 of file ObjectMgr.h.
References GetStorageLocaleIndexFor(), and m_Dbc2StorageLocaleIndex.
SetHighestGuids()
void ObjectMgr::SetHighestGuids ()
Definition at line 7217 of file ObjectMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CONFIG_UINT32_GUID_RESERVE_SIZE_CREATURE, CONFIG_UINT32_GUID_RESERVE_SIZE_GAMEOBJECT, ObjectGuidGenerator< high >::GetNextAfterMaxUsed(), m_ArenaTeamIds, m_AuctionIds, m_CharGuids, m_CorpseGuids, m_EquipmentSetIds, m_FirstTemporaryCreatureGuid, m_FirstTemporaryGameObjectGuid, m_GroupGuids, m_GuildIds, m_InstanceGuids, m_ItemGuids, m_MailIds, m_StaticCreatureGuids, m_StaticGameObjectGuids, Database::PExecute(), Database::Query(), IdGenerator< T >::Set(), ObjectGuidGenerator< high >::Set(), sWorld, and WorldDatabase.
Friends And Related Function Documentation
PlayerDumpReader
friend class PlayerDumpReader friend
Definition at line 507 of file ObjectMgr.h.
Field Documentation
m_accessRequirements
std::unordered_map<uint32, AccessRequirement> ObjectMgr::m_accessRequirements private
Definition at line 1456 of file ObjectMgr.h.
Referenced by GetAccessRequirement(), and LoadAccessRequirements().
m_activeCreatures
ActiveObjectGuidsOnMap ObjectMgr::m_activeCreatures private
Definition at line 1409 of file ObjectMgr.h.
Referenced by LoadActiveEntities(), and LoadCreatures().
m_activeGameObjects
ActiveObjectGuidsOnMap ObjectMgr::m_activeGameObjects private
Definition at line 1410 of file ObjectMgr.h.
Referenced by LoadActiveEntities(), and LoadGameObjects().
m_ArenaTeamIds
IdGenerator<uint32> ObjectMgr::m_ArenaTeamIds protected
Definition at line 1289 of file ObjectMgr.h.
Referenced by GenerateArenaTeamId(), and SetHighestGuids().
m_AuctionIds
IdGenerator<uint32> ObjectMgr::m_AuctionIds protected
Definition at line 1290 of file ObjectMgr.h.
Referenced by GenerateAuctionID(), and SetHighestGuids().
m_broadcastTextMap
BroadcastTextMap ObjectMgr::m_broadcastTextMap private
Definition at line 1442 of file ObjectMgr.h.
Referenced by GetBroadcastText(), LoadBroadcastText(), and LoadBroadcastTextLocales().
m_CharGuids
ObjectGuidGenerator<HIGHGUID_PLAYER> ObjectMgr::m_CharGuids protected
Definition at line 1305 of file ObjectMgr.h.
Referenced by GeneratePlayerLowGuid(), and SetHighestGuids().
m_combatConditionMgr
std::unique_ptr<CombatConditionMgr> ObjectMgr::m_combatConditionMgr private
Definition at line 1454 of file ObjectMgr.h.
Referenced by GetCombatConditions(), IsCombatConditionSatisfied(), and LoadConditionsAndExpressions().
m_CorpseGuids
ObjectGuidGenerator<HIGHGUID_CORPSE> ObjectMgr::m_CorpseGuids protected
Definition at line 1307 of file ObjectMgr.h.
Referenced by GenerateCorpseLowGuid(), and SetHighestGuids().
m_creatureClassLvlStats
CreatureClassLvlStats ObjectMgr::m_creatureClassLvlStats[DEFAULT_MAX_CREATURE_LEVEL+1][MAX_CREATURE_CLASS][MAX_EXPANSION+1] private
Definition at line 1406 of file ObjectMgr.h.
Referenced by GetCreatureClassLvlStats(), and LoadCreatureClassLvlStats().
m_creatureCooldownMap
std::unordered_map<uint32, std::unordered_map<uint32, std::pair<uint32, uint32> > > ObjectMgr::m_creatureCooldownMap private
Definition at line 1414 of file ObjectMgr.h.
Referenced by AddCreatureCooldown(), GetCreatureCooldown(), GetCreatureCooldownRange(), and LoadCreatureCooldowns().
m_creatureImmunities
CreatureImmunityContainer ObjectMgr::m_creatureImmunities private
Definition at line 1444 of file ObjectMgr.h.
Referenced by GetCreatureImmunitySet(), and LoadCreatureImmunities().
m_CreatureQuestInvolvedRelations
QuestRelationsMap ObjectMgr::m_CreatureQuestInvolvedRelations protected
Definition at line 1365 of file ObjectMgr.h.
Referenced by GetCreatureQuestInvolvedRelationsMapBounds(), and LoadCreatureInvolvedRelations().
m_CreatureQuestRelations
QuestRelationsMap ObjectMgr::m_CreatureQuestRelations protected
Definition at line 1364 of file ObjectMgr.h.
Referenced by GetCreatureQuestRelationsMap(), GetCreatureQuestRelationsMapBounds(), and LoadCreatureQuestRelations().
m_creatureSpawnEntryMap
std::unordered_map<uint32, std::vector<uint32> > ObjectMgr::m_creatureSpawnEntryMap protected
Definition at line 1337 of file ObjectMgr.h.
Referenced by GetAllRandomCreatureEntries(), GetCreatureSpawnEntry(), GetRandomCreatureEntry(), and LoadCreatureSpawnEntry().
m_creatureSpawnTemplateMap
CreatureSpawnTemplateMap ObjectMgr::m_creatureSpawnTemplateMap private
Definition at line 1411 of file ObjectMgr.h.
Referenced by GetCreatureSpawnTemplate(), and LoadCreatureSpawnDataTemplates().
m_Dbc2StorageLocaleIndex
uint8 ObjectMgr::m_Dbc2StorageLocaleIndex protected
Definition at line 1286 of file ObjectMgr.h.
Referenced by GetDbc2StorageLocaleIndex(), GetMangosStringForDbcLocale(), and SetDbc2StorageLocaleIndex().
m_DungeonEncounters
DungeonEncounterMap ObjectMgr::m_DungeonEncounters private
Definition at line 1426 of file ObjectMgr.h.
Referenced by GetDungeonEncounterBounds(), and LoadInstanceEncounters().
m_DungeonEncountersByMap
DungeonEncounterMap ObjectMgr::m_DungeonEncountersByMap private
Definition at line 1427 of file ObjectMgr.h.
Referenced by GetDungeonEncounterBoundsByMap(), and LoadInstanceEncounters().
m_EquipmentSetIds
IdGenerator<uint64> ObjectMgr::m_EquipmentSetIds protected
Definition at line 1291 of file ObjectMgr.h.
Referenced by GenerateEquipmentSetGuid(), and SetHighestGuids().
m_ExclusiveQuestGroups
ExclusiveQuestGroupsMap ObjectMgr::m_ExclusiveQuestGroups protected
Definition at line 1362 of file ObjectMgr.h.
Referenced by GetExclusiveQuestGroupsMapBounds(), and LoadQuests().
m_FirstTemporaryCreatureGuid
uint32 ObjectMgr::m_FirstTemporaryCreatureGuid protected
Definition at line 1297 of file ObjectMgr.h.
Referenced by GenerateStaticCreatureLowGuid(), GetFirstTemporaryCreatureLowGuid(), and SetHighestGuids().
m_FirstTemporaryGameObjectGuid
uint32 ObjectMgr::m_FirstTemporaryGameObjectGuid protected
Definition at line 1298 of file ObjectMgr.h.
Referenced by GenerateStaticGameObjectLowGuid(), GetFirstTemporaryGameObjectLowGuid(), and SetHighestGuids().
m_gameobjectAddonTemplates
std::unordered_map<uint32, GameObjectTemplateAddon> ObjectMgr::m_gameobjectAddonTemplates protected
Definition at line 1339 of file ObjectMgr.h.
Referenced by GetGOTemplateAddon(), and LoadGameObjectTemplateAddons().
m_gameobjectSpawnEntryMap
std::unordered_map<uint32, std::vector<uint32> > ObjectMgr::m_gameobjectSpawnEntryMap protected
Definition at line 1338 of file ObjectMgr.h.
Referenced by GetAllRandomGameObjectEntries(), GetRandomGameObjectEntry(), and LoadGameObjectSpawnEntry().
m_GameTeleMap
GameTeleMap ObjectMgr::m_GameTeleMap protected
Definition at line 1351 of file ObjectMgr.h.
Referenced by AddGameTele(), DeleteGameTele(), GetGameTele(), GetGameTeleMap(), and LoadGameTele().
m_GOQuestInvolvedRelations
QuestRelationsMap ObjectMgr::m_GOQuestInvolvedRelations protected
Definition at line 1367 of file ObjectMgr.h.
Referenced by GetGOQuestInvolvedRelationsMapBounds(), LoadGameObjectForQuests(), and LoadGameobjectInvolvedRelations().
m_GOQuestRelations
QuestRelationsMap ObjectMgr::m_GOQuestRelations protected
Definition at line 1366 of file ObjectMgr.h.
Referenced by GetGOQuestRelationsMapBounds(), LoadGameObjectForQuests(), and LoadGameobjectQuestRelations().
m_GroupGuids
ObjectGuidGenerator<HIGHGUID_GROUP> ObjectMgr::m_GroupGuids protected
Definition at line 1309 of file ObjectMgr.h.
Referenced by GenerateGroupLowGuid(), and SetHighestGuids().
m_guidsForMap
std::map<uint32, std::vector<std::pair<TypeID, uint32> > > ObjectMgr::m_guidsForMap private
Definition at line 1459 of file ObjectMgr.h.
Referenced by GetDbGuidsForTransport(), LoadCreatures(), LoadGameobjectInfo(), and LoadGameObjects().
m_GuildIds
IdGenerator<uint32> ObjectMgr::m_GuildIds protected
Definition at line 1292 of file ObjectMgr.h.
Referenced by GenerateGuildId(), and SetHighestGuids().
m_InstanceGuids
ObjectGuidGenerator<HIGHGUID_INSTANCE> ObjectMgr::m_InstanceGuids protected
Definition at line 1308 of file ObjectMgr.h.
Referenced by GenerateInstanceLowGuid(), and SetHighestGuids().
m_ItemConvert
ItemConvertMap ObjectMgr::m_ItemConvert protected
Definition at line 1355 of file ObjectMgr.h.
Referenced by GetItemConvert(), and LoadItemConverts().
m_ItemExpireConvert
ItemConvertMap ObjectMgr::m_ItemExpireConvert protected
Definition at line 1356 of file ObjectMgr.h.
Referenced by GetItemExpireConvert(), and LoadItemExpireConverts().
m_ItemGuids
ObjectGuidGenerator<HIGHGUID_ITEM> ObjectMgr::m_ItemGuids protected
Definition at line 1306 of file ObjectMgr.h.
Referenced by GenerateItemLowGuid(), and SetHighestGuids().
m_ItemRequiredTarget
ItemRequiredTargetMap ObjectMgr::m_ItemRequiredTarget protected
Definition at line 1357 of file ObjectMgr.h.
Referenced by GetItemRequiredTargetMapBounds(), and LoadItemRequiredTarget().
m_loadedStringCount
std::map<int32 , uint32 > ObjectMgr::m_loadedStringCount private
Definition at line 1422 of file ObjectMgr.h.
Referenced by GetLoadedStringsCount(), and LoadMangosStrings().
m_LocalForIndex
LocalForIndex ObjectMgr::m_LocalForIndex protected
Definition at line 1360 of file ObjectMgr.h.
Referenced by GetOrNewStorageLocaleIndexFor(), and GetStorageLocaleIndexFor().
m_MailIds
IdGenerator<uint32> ObjectMgr::m_MailIds protected
Definition at line 1293 of file ObjectMgr.h.
Referenced by GenerateMailID(), and SetHighestGuids().
m_mailLevelRewardMap
MailLevelRewardMap ObjectMgr::m_mailLevelRewardMap private
Definition at line 1379 of file ObjectMgr.h.
Referenced by GetMailLevelReward(), and LoadMailLevelRewards().
m_mCacheNpcTextIdMap
CacheNpcTextIdMap ObjectMgr::m_mCacheNpcTextIdMap private
Definition at line 1436 of file ObjectMgr.h.
Referenced by GetNpcGossip(), and LoadNpcGossips().
m_mCacheTrainerSpellMap
CacheTrainerSpellMap ObjectMgr::m_mCacheTrainerSpellMap private
Definition at line 1440 of file ObjectMgr.h.
Referenced by GetNpcTrainerSpells(), LoadTrainers(), and ~ObjectMgr().
m_mCacheTrainerTemplateSpellMap
CacheTrainerSpellMap ObjectMgr::m_mCacheTrainerTemplateSpellMap private
Definition at line 1439 of file ObjectMgr.h.
Referenced by GetNpcTrainerTemplateSpells(), LoadTrainers(), and LoadTrainerTemplates().
m_mCacheVendorItemMap
CacheVendorItemMap ObjectMgr::m_mCacheVendorItemMap private
Definition at line 1438 of file ObjectMgr.h.
Referenced by AddVendorItem(), GetNpcVendorItemList(), LoadVendors(), RemoveVendorItem(), and ~ObjectMgr().
m_mCacheVendorTemplateItemMap
CacheVendorItemMap ObjectMgr::m_mCacheVendorTemplateItemMap private
Definition at line 1437 of file ObjectMgr.h.
Referenced by GetNpcVendorTemplateItemList(), LoadVendors(), LoadVendorTemplates(), and ~ObjectMgr().
m_mCreatureModelRaceMap
CreatureModelRaceMap ObjectMgr::m_mCreatureModelRaceMap private
Definition at line 1434 of file ObjectMgr.h.
Referenced by GetModelForRace(), and LoadCreatureModelRace().
m_mGossipMenuItemsMap
GossipMenuItemsMap ObjectMgr::m_mGossipMenuItemsMap protected
Definition at line 1335 of file ObjectMgr.h.
Referenced by GetGossipMenuItemsMapBounds(), and LoadGossipMenuItems().
m_mGossipMenusMap
GossipMenusMap ObjectMgr::m_mGossipMenusMap protected
Definition at line 1334 of file ObjectMgr.h.
Referenced by GetGossipMenusMapBounds(), IsExistingGossipMenuId(), LoadGossipMenu(), and LoadGossipMenuItems().
m_PetNumbers
IdGenerator<uint32> ObjectMgr::m_PetNumbers protected
Definition at line 1294 of file ObjectMgr.h.
Referenced by GeneratePetNumber(), and LoadPetNumber().
m_questgiverGreetingLocaleMap
QuestgiverGreetingLocaleMap ObjectMgr::m_questgiverGreetingLocaleMap[QUESTGIVER_TYPE_MAX] private
Definition at line 1430 of file ObjectMgr.h.
Referenced by GetQuestgiverGreetingLocale(), and LoadQuestgiverGreetingLocales().
m_questgiverGreetingMap
QuestgiverGreetingMap ObjectMgr::m_questgiverGreetingMap[QUESTGIVER_TYPE_MAX] private
Definition at line 1429 of file ObjectMgr.h.
Referenced by GetQuestgiverGreetingData(), and LoadQuestgiverGreeting().
m_RepRewardRateMap
RepRewardRateMap ObjectMgr::m_RepRewardRateMap protected
Definition at line 1330 of file ObjectMgr.h.
Referenced by GetRepRewardRate(), and LoadReputationRewardRate().
m_RepSpilloverTemplateMap
RepSpilloverTemplateMap ObjectMgr::m_RepSpilloverTemplateMap protected
Definition at line 1332 of file ObjectMgr.h.
Referenced by GetRepSpilloverTemplate(), and LoadReputationSpilloverTemplate().
m_ReservedNames
ReservedNamesMap ObjectMgr::m_ReservedNames protected
Definition at line 1347 of file ObjectMgr.h.
Referenced by IsReservedName(), and LoadReservedPlayersNames().
m_seatParameters
std::map<uint32, VehicleSeatParameters> ObjectMgr::m_seatParameters private
Definition at line 1461 of file ObjectMgr.h.
Referenced by GetVehicleSeatParameters(), and LoadVehicleSeatParameters().
m_spawnGroupContainer
std::shared_ptr<SpawnGroupEntryContainer> ObjectMgr::m_spawnGroupContainer private
Definition at line 1448 of file ObjectMgr.h.
Referenced by GetSpawnGroupContainer(), and LoadSpawnGroups().
m_spellListContainer
std::shared_ptr<CreatureSpellListContainer> ObjectMgr::m_spellListContainer private
Definition at line 1446 of file ObjectMgr.h.
Referenced by GetCreatureSpellList(), GetCreatureSpellListContainer(), and LoadCreatureSpellLists().
m_StaticCreatureGuids
ObjectGuidGenerator<HIGHGUID_UNIT> ObjectMgr::m_StaticCreatureGuids protected
Definition at line 1301 of file ObjectMgr.h.
Referenced by GenerateStaticCreatureLowGuid(), and SetHighestGuids().
m_StaticGameObjectGuids
ObjectGuidGenerator<HIGHGUID_GAMEOBJECT> ObjectMgr::m_StaticGameObjectGuids protected
Definition at line 1302 of file ObjectMgr.h.
Referenced by GenerateStaticGameObjectLowGuid(), and SetHighestGuids().
m_TaxiShortcutMap
TaxiShortcutMap ObjectMgr::m_TaxiShortcutMap protected
Definition at line 1349 of file ObjectMgr.h.
Referenced by AddTaxiShortcut(), GetTaxiShortcut(), and LoadTaxiShortcuts().
m_trainerGreetingLocaleMap
TrainerGreetingLocaleMap ObjectMgr::m_trainerGreetingLocaleMap private
Definition at line 1432 of file ObjectMgr.h.
Referenced by GetTrainerGreetingLocale(), and LoadTrainerGreetingLocales().
m_trainerGreetingMap
TrainerGreetingMap ObjectMgr::m_trainerGreetingMap private
Definition at line 1431 of file ObjectMgr.h.
Referenced by GetTrainerGreetingData(), and LoadTrainerGreetings().
m_transportMaps
std::map<uint32, uint32> ObjectMgr::m_transportMaps private
Definition at line 1458 of file ObjectMgr.h.
Referenced by LoadCreatures(), LoadGameobjectInfo(), and LoadGameObjects().
m_unitConditionMgr
std::unique_ptr<UnitConditionMgr> ObjectMgr::m_unitConditionMgr private
Definition at line 1452 of file ObjectMgr.h.
Referenced by GetUnitConditions(), IsUnitConditionSatisfied(), and LoadConditionsAndExpressions().
m_worldStateExpressionMgr
std::unique_ptr<WorldStateExpressionMgr> ObjectMgr::m_worldStateExpressionMgr private
Definition at line 1453 of file ObjectMgr.h.
Referenced by GetWorldStateExpressions(), IsWorldStateExpressionSatisfied(), LoadConditionsAndExpressions(), and LoadSpawnGroups().
m_worldStateNames
std::map<int32, WorldStateName> ObjectMgr::m_worldStateNames private
Definition at line 1450 of file ObjectMgr.h.
Referenced by GetWorldStateName(), HasWorldStateName(), and LoadWorldStateNames().
mAreaTriggers
AreaTriggerMap ObjectMgr::mAreaTriggers protected
Definition at line 1328 of file ObjectMgr.h.
Referenced by GetAreaTrigger(), GetGoBackTrigger(), GetMapEntranceTrigger(), and LoadAreaTriggerTeleports().
mArenaTeamMap
ArenaTeamMap ObjectMgr::mArenaTeamMap protected
Definition at line 1322 of file ObjectMgr.h.
Referenced by AddArenaTeam(), GetArenaTeamByCaptain(), GetArenaTeamById(), GetArenaTeamByName(), GetArenaTeamMapBegin(), GetArenaTeamMapEnd(), RemoveArenaTeam(), and ~ObjectMgr().
mBaseXPTable
BaseXPMap ObjectMgr::mBaseXPTable private
Definition at line 1394 of file ObjectMgr.h.
Referenced by GetBaseXP(), and LoadExplorationBaseXP().
mCreatureDataMap
CreatureDataMap ObjectMgr::mCreatureDataMap private
Definition at line 1412 of file ObjectMgr.h.
Referenced by DeleteCreatureData(), DoCreatureData(), GetCreatureData(), GetCreatureDataPair(), LoadActiveEntities(), LoadCreatureAddons(), LoadCreatures(), and NewOrExistCreatureData().
mCreatureLocaleMap
CreatureLocaleMap ObjectMgr::mCreatureLocaleMap private
Definition at line 1413 of file ObjectMgr.h.
Referenced by GetCreatureLocale(), and LoadCreatureLocales().
mFishingBaseForArea
FishingBaseSkillMap ObjectMgr::mFishingBaseForArea private
Definition at line 1397 of file ObjectMgr.h.
Referenced by GetFishingBaseSkillLevel(), and LoadFishingBaseSkillLevel().
mGameObjectDataMap
GameObjectDataMap ObjectMgr::mGameObjectDataMap private
Definition at line 1415 of file ObjectMgr.h.
Referenced by DeleteGOData(), DoGOData(), GetGODataPair(), LoadActiveEntities(), LoadGameObjects(), and NewGOData().
mGameObjectForQuestSet
GameObjectForQuestSet ObjectMgr::mGameObjectForQuestSet protected
Definition at line 1326 of file ObjectMgr.h.
Referenced by IsGameObjectForQuests(), and LoadGameObjectForQuests().
mGameObjectLocaleMap
GameObjectLocaleMap ObjectMgr::mGameObjectLocaleMap private
Definition at line 1416 of file ObjectMgr.h.
Referenced by GetGameObjectLocale(), and LoadGameObjectLocales().
mGossipMenuItemsLocaleMap
GossipMenuItemsLocaleMap ObjectMgr::mGossipMenuItemsLocaleMap private
Definition at line 1423 of file ObjectMgr.h.
Referenced by GetGossipMenuItemsLocale(), and LoadGossipMenuItemsLocales().
mGossipText
GossipTextMap ObjectMgr::mGossipText protected
Definition at line 1327 of file ObjectMgr.h.
Referenced by GetGossipText(), and LoadGossipText().
mGroupMap
GroupMap ObjectMgr::mGroupMap protected
Definition at line 1321 of file ObjectMgr.h.
Referenced by AddGroup(), GetGroupById(), GetGroupMapBegin(), GetGroupMapEnd(), LoadGroups(), RemoveGroup(), and ~ObjectMgr().
mItemLocaleMap
ItemLocaleMap ObjectMgr::mItemLocaleMap private
Definition at line 1417 of file ObjectMgr.h.
Referenced by GetItemLocale(), and LoadItemLocales().
mMangosStringLocaleMap
MangosStringLocaleMap ObjectMgr::mMangosStringLocaleMap private
Definition at line 1421 of file ObjectMgr.h.
Referenced by GetMangosStringLocale(), and LoadMangosStrings().
mMapObjectGuids
MapObjectGuids ObjectMgr::mMapObjectGuids private
Definition at line 1408 of file ObjectMgr.h.
Referenced by AddCorpseCellData(), AddCreatureToGrid(), AddGameobjectToGrid(), DeleteCorpseCellData(), GetCellObjectGuids(), RemoveCreatureFromGrid(), and RemoveGameobjectFromGrid().
mNpcTextLocaleMap
NpcTextLocaleMap ObjectMgr::mNpcTextLocaleMap private
Definition at line 1419 of file ObjectMgr.h.
Referenced by GetNpcTextLocale(), and LoadGossipTextLocales().
mPageTextLocaleMap
PageTextLocaleMap ObjectMgr::mPageTextLocaleMap private
Definition at line 1420 of file ObjectMgr.h.
Referenced by GetPageTextLocale(), and LoadPageTextLocales().
mPlayerXPperLevel
PlayerXPperLevel ObjectMgr::mPlayerXPperLevel private
Definition at line 1391 of file ObjectMgr.h.
Referenced by GetXPForLevel(), and LoadPlayerInfo().
mPointOfInterestLocaleMap
PointOfInterestLocaleMap ObjectMgr::mPointOfInterestLocaleMap private
Definition at line 1424 of file ObjectMgr.h.
Referenced by GetPointOfInterestLocale(), and LoadPointOfInterestLocales().
mPointsOfInterest
PointOfInterestMap ObjectMgr::mPointsOfInterest protected
Definition at line 1341 of file ObjectMgr.h.
Referenced by GetPointOfInterest(), and LoadPointsOfInterest().
mQuestAreaTriggerMap
QuestAreaTriggerMap ObjectMgr::mQuestAreaTriggerMap protected
Definition at line 1324 of file ObjectMgr.h.
Referenced by GetQuestForAreaTrigger(), and LoadQuestAreaTriggers().
mQuestLocaleMap
QuestLocaleMap ObjectMgr::mQuestLocaleMap private
Definition at line 1418 of file ObjectMgr.h.
Referenced by GetQuestLocale(), and LoadQuestLocales().
mQuestPOIMap
QuestPOIMap ObjectMgr::mQuestPOIMap protected
Definition at line 1343 of file ObjectMgr.h.
Referenced by GetQuestPOIVector(), and LoadQuestPOI().
mQuestTemplates
QuestMap ObjectMgr::mQuestTemplates protected
Definition at line 1311 of file ObjectMgr.h.
Referenced by GetQuestTemplate(), GetQuestTemplates(), LoadAreaTriggerTeleports(), LoadConditions(), LoadNPCSpellClickSpells(), LoadQuestRelationsHelper(), LoadQuests(), and ~ObjectMgr().
mRepOnKill
RepOnKillMap ObjectMgr::mRepOnKill protected
Definition at line 1331 of file ObjectMgr.h.
Referenced by GetReputationOnKillEntry(), and LoadReputationOnKill().
mSpellClickInfoMap
SpellClickInfoMap ObjectMgr::mSpellClickInfoMap protected
Definition at line 1353 of file ObjectMgr.h.
Referenced by GetSpellClickInfoMapBounds(), and LoadNPCSpellClickSpells().
mTavernAreaTriggerSet
TavernAreaTriggerSet ObjectMgr::mTavernAreaTriggerSet protected
Definition at line 1325 of file ObjectMgr.h.
Referenced by IsTavernAreaTrigger(), and LoadTavernAreaTriggers().
PetHalfName0
HalfNameMap ObjectMgr::PetHalfName0 private
Definition at line 1400 of file ObjectMgr.h.
Referenced by GeneratePetName(), and LoadPetNames().
PetHalfName1
HalfNameMap ObjectMgr::PetHalfName1 private
Definition at line 1401 of file ObjectMgr.h.
Referenced by GeneratePetName(), and LoadPetNames().
petInfo
PetLevelInfoMap ObjectMgr::petInfo private
Definition at line 1383 of file ObjectMgr.h.
Referenced by GetPetLevelInfo(), LoadPetLevelInfo(), and ~ObjectMgr().
playerClassInfo
PlayerClassInfo ObjectMgr::playerClassInfo[MAX_CLASSES] private
Definition at line 1385 of file ObjectMgr.h.
Referenced by GetPlayerClassInfo(), GetPlayerClassLevelInfo(), LoadPlayerInfo(), and ~ObjectMgr().
playerInfo
PlayerInfo ObjectMgr::playerInfo[MAX_RACES][MAX_CLASSES] private
Definition at line 1388 of file ObjectMgr.h.
Referenced by BuildPlayerLevelInfo(), GetPlayerInfo(), GetPlayerLevelInfo(), LoadPlayerInfo(), and ~ObjectMgr().
The documentation for this class was generated from the following files:
ObjectMgr.h
Vehicle.cpp
ObjectMgr.cpp