CMaNGOS_WoTLK: PlayerbotDruidAI Class Reference
PlayerbotDruidAI Class Reference
#include <PlayerbotDruidAI.h>
Public Member Functions
PlayerbotDruidAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotDruidAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
bool CanPull () override
bool Pull () override
uint32 Neutralize (uint8 creatureType) override
void DoNonCombatActions () override
bool CastHoTOnTank ()
Private Types
enum CheckForms_ReturnValues {
RETURN_FAIL = 0 , RETURN_FAIL_WAITINGONSELFBUFF , RETURN_OK_NOCHANGE , RETURN_OK_SHIFTING ,
RETURN_OK_CANNOTSHIFT
}
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns CastSpell (uint32 nextAction, Unit *pTarget=nullptr)
CombatManeuverReturns _DoNextPVECombatManeuverBear (Unit *pTarget)
CombatManeuverReturns _DoNextPVECombatManeuverCat (Unit *pTarget)
CombatManeuverReturns _DoNextPVECombatManeuverSpellDPS (Unit *pTarget)
CombatManeuverReturns _DoNextPVECombatManeuverHeal ()
CombatManeuverReturns HealPlayer (Player *target) override
CombatManeuverReturns ResurrectPlayer (Player *target) override
CombatManeuverReturns DispelPlayer (Player *target=nullptr)
uint8 CheckForms ()
CheckForms()
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Static Private Member Functions
static bool BuffHelper (PlayerbotAI *ai, uint32 spellId, Unit *target)
static void GoBuffForm (Player *self)
Private Attributes
uint32 CAT_FORM
uint32 BEAR_FORM
uint32 DIRE_BEAR_FORM
uint32 MOONKIN_FORM
uint32 TREE_OF_LIFE
uint32 TRAVEL_FORM
uint32 CLAW
uint32 COWER
uint32 TIGERS_FURY
uint32 RAKE
uint32 RIP
uint32 FEROCIOUS_BITE
uint32 MAIM
uint32 MANGLE
uint32 MANGLE_CAT
uint32 SAVAGE_ROAR
uint32 BASH
uint32 MAUL
uint32 SWIPE
uint32 DEMORALIZING_ROAR
uint32 CHALLENGING_ROAR
uint32 GROWL
uint32 ENRAGE
uint32 FAERIE_FIRE_FERAL
uint32 MANGLE_BEAR
uint32 LACERATE
uint32 MOONFIRE
uint32 ROOTS
uint32 WRATH
uint32 OMEN_OF_CLARITY
uint32 STARFALL
uint32 STARFIRE
uint32 INSECT_SWARM
uint32 FAERIE_FIRE
uint32 HIBERNATE
uint32 FORCE_OF_NATURE
uint32 HURRICANE
uint32 ECLIPSE_SOLAR
uint32 ECLIPSE_LUNAR
uint32 ECLIPSE
uint32 MARK_OF_THE_WILD
uint32 GIFT_OF_THE_WILD
uint32 THORNS
uint32 INNERVATE
uint32 BARKSKIN
uint32 LIFEBLOOM
uint32 REJUVENATION
uint32 REGROWTH
uint32 NOURISH
uint32 HEALING_TOUCH
uint32 NATURES_SWIFTNESS
uint32 WILD_GROWTH
uint32 SWIFTMEND
uint32 TRANQUILITY
uint32 REVIVE
uint32 REBIRTH
uint32 REMOVE_CURSE
uint32 CURE_POISON
uint32 ABOLISH_POISON
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 SpellSequence
uint32 DruidSpellCombat
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 110 of file PlayerbotDruidAI.h.
Member Enumeration Documentation
CheckForms_ReturnValues
enum PlayerbotDruidAI::CheckForms_ReturnValues private
Enumerator
RETURN_FAIL
RETURN_FAIL_WAITINGONSELFBUFF
RETURN_OK_NOCHANGE
RETURN_OK_SHIFTING
RETURN_OK_CANNOTSHIFT
Definition at line 156 of file PlayerbotDruidAI.h.
Constructor & Destructor Documentation
PlayerbotDruidAI()
PlayerbotDruidAI::PlayerbotDruidAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotDruidAI.cpp.
References ABOLISH_POISON, ABOLISH_POISON_1, BARKSKIN, BARKSKIN_1, BASH, BASH_1, BEAR_FORM, BEAR_FORM_1, CAT_FORM, CAT_FORM_1, CHALLENGING_ROAR, CHALLENGING_ROAR_1, CLAW, CLAW_1, COWER, COWER_1, CURE_POISON, CURE_POISON_1, DEMORALIZING_ROAR, DEMORALIZING_ROAR_1, DIRE_BEAR_FORM, DIRE_BEAR_FORM_1, ECLIPSE, ECLIPSE_1, ECLIPSE_LUNAR, ECLIPSE_LUNAR_1, ECLIPSE_SOLAR, ECLIPSE_SOLAR_1, ENRAGE, ENRAGE_1, ENTANGLING_ROOTS_1, FAERIE_FIRE, FAERIE_FIRE_1, FAERIE_FIRE_FERAL, FAERIE_FIRE_FERAL_1, FEROCIOUS_BITE, FEROCIOUS_BITE_1, FORCE_OF_NATURE, FORCE_OF_NATURE_1, GIFT_OF_THE_WILD, GIFT_OF_THE_WILD_1, GROWL, GROWL_1, HEALING_TOUCH, HEALING_TOUCH_1, HIBERNATE, HIBERNATE_1, HURRICANE, HURRICANE_1, PlayerbotAI::initSpell(), INNERVATE, INNERVATE_1, INSECT_SWARM, INSECT_SWARM_1, LACERATE, LACERATE_1, LIFEBLOOM, LIFEBLOOM_1, PlayerbotClassAI::m_ai, MAIM, MAIM_1, MANGLE, MANGLE_1, MANGLE_BEAR, MANGLE_BEAR_1, MANGLE_CAT, MANGLE_CAT_1, MARK_OF_THE_WILD, MARK_OF_THE_WILD_1, MAUL, MAUL_1, MOONFIRE, MOONFIRE_1, MOONKIN_FORM, MOONKIN_FORM_1, NATURES_SWIFTNESS, NATURES_SWIFTNESS_DRUID_1, NOURISH, NOURISH_1, OMEN_OF_CLARITY, OMEN_OF_CLARITY_1, RAKE, RAKE_1, REBIRTH, REBIRTH_1, PlayerbotClassAI::RECENTLY_BANDAGED, REGROWTH, REGROWTH_1, REJUVENATION, REJUVENATION_1, REMOVE_CURSE, REMOVE_CURSE_DRUID_1, REVIVE, REVIVE_1, RIP, RIP_1, ROOTS, SAVAGE_ROAR, SAVAGE_ROAR_1, SHADOWMELD, SHADOWMELD_ALL, STARFALL, STARFALL_1, STARFIRE, STARFIRE_1, SWIFTMEND, SWIFTMEND_1, SWIPE, SWIPE_BEAR_1, THORNS, THORNS_1, TIGERS_FURY, TIGERS_FURY_1, TRANQUILITY, TRANQUILITY_1, TRAVEL_FORM, TRAVEL_FORM_1, TREE_OF_LIFE, TREE_OF_LIFE_1, WAR_STOMP, WAR_STOMP_ALL, WILD_GROWTH, WILD_GROWTH_1, WRATH, and WRATH_1.
~PlayerbotDruidAI()
PlayerbotDruidAI::~PlayerbotDruidAI () virtual
Definition at line 98 of file PlayerbotDruidAI.cpp.
Member Function Documentation
_DoNextPVECombatManeuverBear()
CombatManeuverReturns PlayerbotDruidAI::_DoNextPVECombatManeuverBear (Unit * pTarget) private
Definition at line 293 of file PlayerbotDruidAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, Unit::Attack(), BEAR_FORM, CastSpell(), DEMORALIZING_ROAR, DIRE_BEAR_FORM, EFFECT_INDEX_0, ENRAGE, FAERIE_FIRE_FERAL, PlayerbotAI::FindAttacker(), WorldObject::GetAngle(), PlayerbotAI::GetAttackerCount(), PlayerbotAI::GetCombatOrder(), Unit::GetVictim(), GROWL, Unit::HasAura(), WorldObject::HasInArc(), PlayerbotAI::In_Reach(), WorldObject::IsSpellReady(), LACERATE, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MANGLE_BEAR, MAUL, PlayerbotAI::ORDERS_TANK, RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_UNKNOWN, Unit::SetFacingTo(), and SWIPE.
Referenced by DoNextCombatManeuverPVE().
_DoNextPVECombatManeuverCat()
CombatManeuverReturns PlayerbotDruidAI::_DoNextPVECombatManeuverCat (Unit * pTarget) private
Definition at line 338 of file PlayerbotDruidAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, Unit::Attack(), CastSpell(), CAT_FORM, CLAW, COWER, EFFECT_INDEX_0, FAERIE_FIRE_FERAL, FEROCIOUS_BITE, PlayerbotAI::FindAttacker(), WorldObject::GetAngle(), Unit::GetComboPoints(), Unit::GetVictim(), Unit::HasAura(), WorldObject::HasInArc(), PlayerbotAI::In_Reach(), WorldObject::IsSpellReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MANGLE_CAT, RAKE, RETURN_CONTINUE, RETURN_NO_ACTION_UNKNOWN, RIP, SAVAGE_ROAR, Unit::SetFacingTo(), and TIGERS_FURY.
Referenced by DoNextCombatManeuverPVE().
_DoNextPVECombatManeuverHeal()
CombatManeuverReturns PlayerbotDruidAI::_DoNextPVECombatManeuverHeal () private
Definition at line 449 of file PlayerbotDruidAI.cpp.
References DispelPlayer(), PlayerbotClassAI::FindTargetAndHeal(), PlayerbotClassAI::GetResurrectionTarget(), PlayerbotAI::HasDispelOrder(), JOB_TANK_MASTER, PlayerbotClassAI::m_ai, ResurrectPlayer(), RETURN_CONTINUE, and RETURN_NO_ACTION_UNKNOWN.
Referenced by DoFirstCombatManeuver(), and DoNextCombatManeuverPVE().
_DoNextPVECombatManeuverSpellDPS()
CombatManeuverReturns PlayerbotDruidAI::_DoNextPVECombatManeuverSpellDPS (Unit * pTarget) private
Definition at line 398 of file PlayerbotDruidAI.cpp.
References Unit::Attack(), Unit::AttackStop(), CastSpell(), PlayerbotAI::COMBAT_MELEE, DispelPlayer(), ECLIPSE_LUNAR, ECLIPSE_SOLAR, EFFECT_INDEX_0, PlayerbotAI::FaceTarget(), FAERIE_FIRE, FORCE_OF_NATURE, WorldObject::GetAngle(), PlayerbotAI::GetCombatStyle(), PlayerbotClassAI::GetResurrectionTarget(), Unit::HasAura(), PlayerbotAI::HasDispelOrder(), WorldObject::HasInArc(), PlayerbotAI::In_Reach(), INSECT_SWARM, JOB_TANK_MASTER, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MOONFIRE, ResurrectPlayer(), RETURN_CONTINUE, RETURN_NO_ACTION_UNKNOWN, Unit::SetFacingTo(), STARFIRE, and WRATH.
Referenced by DoNextCombatManeuverPVE().
BuffHelper()
bool PlayerbotDruidAI::BuffHelper (PlayerbotAI * ai, uint32 spellId, Unit * target) static private
Definition at line 781 of file PlayerbotDruidAI.cpp.
References PlayerbotAI::Buff(), GoBuffForm(), and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
CanPull()
bool PlayerbotDruidAI::CanPull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 811 of file PlayerbotDruidAI.cpp.
References BEAR_FORM, and FAERIE_FIRE_FERAL.
CastHoTOnTank()
bool PlayerbotDruidAI::CastHoTOnTank ()
Definition at line 822 of file PlayerbotDruidAI.cpp.
References CastSpell(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetGroupTank(), PlayerbotClassAI::m_ai, PlayerbotAI::ORDERS_HEAL, REJUVENATION, and RETURN_CONTINUE.
CastSpell()
CombatManeuverReturns PlayerbotDruidAI::CastSpell (uint32 nextAction, Unit * pTarget = nullptr) inline private
Definition at line 135 of file PlayerbotDruidAI.h.
References PlayerbotClassAI::CastSpellNoRanged().
Referenced by _DoNextPVECombatManeuverBear(), _DoNextPVECombatManeuverCat(), _DoNextPVECombatManeuverSpellDPS(), CastHoTOnTank(), CheckForms(), DispelPlayer(), DoNonCombatActions(), HealPlayer(), and Pull().
CheckForms()
uint8 PlayerbotDruidAI::CheckForms () private
CheckForms()
Returns bool - Value indicates success - shape was shifted, already shifted, no need to shift.
Definition at line 603 of file PlayerbotDruidAI.cpp.
References BEAR_FORM, BEAR_FORM_1, CastSpell(), CAT_FORM, CAT_FORM_1, DIRE_BEAR_FORM, DIRE_BEAR_FORM_1, DRUID_SPEC_BALANCE, DRUID_SPEC_FERAL, DRUID_SPEC_RESTORATION, EFFECT_INDEX_0, PlayerbotAI::GetCombatOrder(), Unit::HasAura(), PlayerbotAI::IsHealer(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MOONKIN_FORM, MOONKIN_FORM_1, PlayerbotAI::ORDERS_TANK, Unit::RemoveAurasDueToSpell(), RETURN_FAIL, RETURN_FAIL_WAITINGONSELFBUFF, RETURN_OK_CANNOTSHIFT, RETURN_OK_NOCHANGE, RETURN_OK_SHIFTING, THORNS, and TREE_OF_LIFE.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
DispelPlayer()
CombatManeuverReturns PlayerbotDruidAI::DispelPlayer (Player * target = nullptr) private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 571 of file PlayerbotDruidAI.cpp.
References ABOLISH_POISON, CastSpell(), CURE_POISON, DISPEL_CURSE, DISPEL_POISON, PlayerbotClassAI::DispelPlayer(), PlayerbotClassAI::GetDispelTarget(), REMOVE_CURSE, RETURN_CONTINUE, and RETURN_NO_ACTION_OK.
Referenced by _DoNextPVECombatManeuverHeal(), _DoNextPVECombatManeuverSpellDPS(), and DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotDruidAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 100 of file PlayerbotDruidAI.cpp.
References _DoNextPVECombatManeuverHeal(), PlayerbotAI::Attack(), Unit::CanReachWithMeleeAttack(), PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCurrentTarget(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_HEAL, PlayerbotAI::ORDERS_TANK, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, PlayerbotAI::SCENARIO_PVP_OPENWORLD, and PlayerbotAI::SetGroupIgnoreUpdateTime().
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotDruidAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 163 of file PlayerbotDruidAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotDruidAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 168 of file PlayerbotDruidAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotDruidAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 173 of file PlayerbotDruidAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotDruidAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 191 of file PlayerbotDruidAI.cpp.
References _DoNextPVECombatManeuverBear(), _DoNextPVECombatManeuverCat(), _DoNextPVECombatManeuverHeal(), _DoNextPVECombatManeuverSpellDPS(), PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, BEAR_FORM, Unit::CanReachWithMeleeAttack(), CAT_FORM, CheckForms(), PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, DIRE_BEAR_FORM, DRUID_SPEC_BALANCE, DRUID_SPEC_FERAL, DRUID_SPEC_RESTORATION, PlayerbotAI::FindAttacker(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCombatStyle(), Unit::HasAura(), HealPlayer(), PlayerbotAI::IsHealer(), PlayerbotAI::IsNeutralized(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_HEAL, PlayerbotAI::ORDERS_TANK, RETURN_CONTINUE, RETURN_FAIL, RETURN_NO_ACTION_OK, RETURN_NO_ACTION_UNKNOWN, RETURN_OK_CANNOTSHIFT, RETURN_OK_SHIFTING, PlayerbotAI::SetCombatStyle(), and TREE_OF_LIFE.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotDruidAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 285 of file PlayerbotDruidAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), PlayerbotClassAI::m_ai, MOONFIRE, RETURN_CONTINUE, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotDruidAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 729 of file PlayerbotDruidAI.cpp.
References PlayerbotClassAI::Buff(), BuffHelper(), CastSpell(), CheckForms(), DispelPlayer(), PlayerbotClassAI::EatDrinkBandage(), Player::GetGroup(), PlayerbotClassAI::GetHealTarget(), PlayerbotAI::GetManaPercent(), PlayerbotClassAI::GetResurrectionTarget(), GIFT_OF_THE_WILD, Unit::HasAura(), PlayerbotAI::HasDispelOrder(), PlayerbotAI::HasSpellReagents(), HealPlayer(), PlayerbotAI::In_Reach(), INNERVATE, Unit::IsAlive(), PlayerbotAI::IsHealer(), JOB_ALL, JOB_MAIN_TANK, JOB_TANK, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MARK_OF_THE_WILD, PlayerbotClassAI::NeedGroupBuff(), OMEN_OF_CLARITY, ResurrectPlayer(), RETURN_CONTINUE, and THORNS.
GoBuffForm()
void PlayerbotDruidAI::GoBuffForm (Player * self) static private
Definition at line 794 of file PlayerbotDruidAI.cpp.
References BEAR_FORM_1, CAT_FORM_1, DIRE_BEAR_FORM_1, MOONKIN_FORM_1, and TRAVEL_FORM_1.
Referenced by BuffHelper(), and HealPlayer().
HealPlayer()
CombatManeuverReturns PlayerbotDruidAI::HealPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 466 of file PlayerbotDruidAI.cpp.
References CastSpell(), Unit::GetHealthPercent(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), PlayerbotClassAI::GetTargetJob(), GoBuffForm(), Unit::HasAura(), HEALING_TOUCH, PlayerbotClassAI::HealPlayer(), PlayerbotAI::In_Reach(), WorldObject::IsSpellReady(), JOB_MAIN_TANK, JOB_TANK, LIFEBLOOM, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), PlayerbotAI::MOVEMENT_STAY, NATURES_SWIFTNESS, NOURISH, REGROWTH, REJUVENATION, RETURN_CONTINUE, RETURN_NO_ACTION_OK, RETURN_NO_ACTION_UNKNOWN, SWIFTMEND, TREE_OF_LIFE, and WILD_GROWTH.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
Neutralize()
uint32 PlayerbotDruidAI::Neutralize (uint8 creatureType) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 834 of file PlayerbotDruidAI.cpp.
References CREATURE_TYPE_BEAST, CREATURE_TYPE_DRAGONKIN, HIBERNATE, PlayerbotClassAI::m_ai, and PlayerbotAI::TellMaster().
Pull()
bool PlayerbotDruidAI::Pull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 817 of file PlayerbotDruidAI.cpp.
References BEAR_FORM, CastSpell(), FAERIE_FIRE_FERAL, and RETURN_CONTINUE.
ResurrectPlayer()
CombatManeuverReturns PlayerbotDruidAI::ResurrectPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 541 of file PlayerbotDruidAI.cpp.
References PlayerbotAI::CastSpell(), WorldObject::GetName(), PlayerbotAI::In_Reach(), Unit::IsInCombat(), WorldObject::IsSpellReady(), LANG_UNIVERSAL, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, REBIRTH, PlayerbotClassAI::ResurrectPlayer(), RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, REVIVE, Player::Say(), and SPELL_CAST_OK.
Referenced by _DoNextPVECombatManeuverHeal(), _DoNextPVECombatManeuverSpellDPS(), and DoNonCombatActions().
Field Documentation
ABOLISH_POISON
uint32 PlayerbotDruidAI::ABOLISH_POISON private
Definition at line 234 of file PlayerbotDruidAI.h.
Referenced by DispelPlayer(), and PlayerbotDruidAI().
ARCANE_TORRENT
uint32 PlayerbotDruidAI::ARCANE_TORRENT private
Definition at line 237 of file PlayerbotDruidAI.h.
BARKSKIN
uint32 PlayerbotDruidAI::BARKSKIN private
Definition at line 218 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
BASH
uint32 PlayerbotDruidAI::BASH private
Definition at line 186 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
BEAR_FORM
uint32 PlayerbotDruidAI::BEAR_FORM private
Definition at line 167 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), CanPull(), CheckForms(), DoNextCombatManeuverPVE(), PlayerbotDruidAI(), and Pull().
BERSERKING
uint32 PlayerbotDruidAI::BERSERKING private
Definition at line 245 of file PlayerbotDruidAI.h.
BLOOD_FURY
uint32 PlayerbotDruidAI::BLOOD_FURY private
Definition at line 243 of file PlayerbotDruidAI.h.
CAT_FORM
uint32 PlayerbotDruidAI::CAT_FORM private
Definition at line 166 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), CheckForms(), DoNextCombatManeuverPVE(), and PlayerbotDruidAI().
CHALLENGING_ROAR
uint32 PlayerbotDruidAI::CHALLENGING_ROAR private
Definition at line 190 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
CLAW
uint32 PlayerbotDruidAI::CLAW private
Definition at line 174 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
COWER
uint32 PlayerbotDruidAI::COWER private
Definition at line 175 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
CURE_POISON
uint32 PlayerbotDruidAI::CURE_POISON private
Definition at line 233 of file PlayerbotDruidAI.h.
Referenced by DispelPlayer(), and PlayerbotDruidAI().
DEMORALIZING_ROAR
uint32 PlayerbotDruidAI::DEMORALIZING_ROAR private
Definition at line 189 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
DIRE_BEAR_FORM
uint32 PlayerbotDruidAI::DIRE_BEAR_FORM private
Definition at line 168 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), CheckForms(), DoNextCombatManeuverPVE(), and PlayerbotDruidAI().
DruidSpellCombat
uint32 PlayerbotDruidAI::DruidSpellCombat private
Definition at line 248 of file PlayerbotDruidAI.h.
ECLIPSE
uint32 PlayerbotDruidAI::ECLIPSE private
Definition at line 211 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
ECLIPSE_LUNAR
uint32 PlayerbotDruidAI::ECLIPSE_LUNAR private
Definition at line 210 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
ECLIPSE_SOLAR
uint32 PlayerbotDruidAI::ECLIPSE_SOLAR private
Definition at line 209 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
ENRAGE
uint32 PlayerbotDruidAI::ENRAGE private
Definition at line 192 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
ESCAPE_ARTIST
uint32 PlayerbotDruidAI::ESCAPE_ARTIST private
Definition at line 240 of file PlayerbotDruidAI.h.
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotDruidAI::EVERY_MAN_FOR_HIMSELF private
Definition at line 241 of file PlayerbotDruidAI.h.
FAERIE_FIRE
uint32 PlayerbotDruidAI::FAERIE_FIRE private
Definition at line 205 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
FAERIE_FIRE_FERAL
uint32 PlayerbotDruidAI::FAERIE_FIRE_FERAL private
Definition at line 193 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), _DoNextPVECombatManeuverCat(), CanPull(), PlayerbotDruidAI(), and Pull().
FEROCIOUS_BITE
uint32 PlayerbotDruidAI::FEROCIOUS_BITE private
Definition at line 179 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
FORCE_OF_NATURE
uint32 PlayerbotDruidAI::FORCE_OF_NATURE private
Definition at line 207 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotDruidAI::GIFT_OF_THE_NAARU private
Definition at line 238 of file PlayerbotDruidAI.h.
GIFT_OF_THE_WILD
uint32 PlayerbotDruidAI::GIFT_OF_THE_WILD private
Definition at line 215 of file PlayerbotDruidAI.h.
Referenced by DoNonCombatActions(), and PlayerbotDruidAI().
GROWL
uint32 PlayerbotDruidAI::GROWL private
Definition at line 191 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
HEALING_TOUCH
uint32 PlayerbotDruidAI::HEALING_TOUCH private
Definition at line 225 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
HIBERNATE
uint32 PlayerbotDruidAI::HIBERNATE private
Definition at line 206 of file PlayerbotDruidAI.h.
Referenced by Neutralize(), and PlayerbotDruidAI().
HURRICANE
uint32 PlayerbotDruidAI::HURRICANE private
Definition at line 208 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
INNERVATE
uint32 PlayerbotDruidAI::INNERVATE private
Definition at line 217 of file PlayerbotDruidAI.h.
Referenced by DoNonCombatActions(), and PlayerbotDruidAI().
INSECT_SWARM
uint32 PlayerbotDruidAI::INSECT_SWARM private
Definition at line 204 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
LACERATE
uint32 PlayerbotDruidAI::LACERATE private
Definition at line 195 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
LIFEBLOOM
uint32 PlayerbotDruidAI::LIFEBLOOM private
Definition at line 221 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
MAIM
uint32 PlayerbotDruidAI::MAIM private
Definition at line 180 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
MANGLE
uint32 PlayerbotDruidAI::MANGLE private
Definition at line 181 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
MANGLE_BEAR
uint32 PlayerbotDruidAI::MANGLE_BEAR private
Definition at line 194 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
MANGLE_CAT
uint32 PlayerbotDruidAI::MANGLE_CAT private
Definition at line 182 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
MARK_OF_THE_WILD
uint32 PlayerbotDruidAI::MARK_OF_THE_WILD private
Definition at line 214 of file PlayerbotDruidAI.h.
Referenced by DoNonCombatActions(), and PlayerbotDruidAI().
MAUL
uint32 PlayerbotDruidAI::MAUL private
Definition at line 187 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
MOONFIRE
uint32 PlayerbotDruidAI::MOONFIRE private
Definition at line 198 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), DoNextCombatManeuverPVP(), and PlayerbotDruidAI().
MOONKIN_FORM
uint32 PlayerbotDruidAI::MOONKIN_FORM private
Definition at line 169 of file PlayerbotDruidAI.h.
Referenced by CheckForms(), and PlayerbotDruidAI().
NATURES_SWIFTNESS
uint32 PlayerbotDruidAI::NATURES_SWIFTNESS private
Definition at line 226 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
NOURISH
uint32 PlayerbotDruidAI::NOURISH private
Definition at line 224 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
OMEN_OF_CLARITY
uint32 PlayerbotDruidAI::OMEN_OF_CLARITY private
Definition at line 201 of file PlayerbotDruidAI.h.
Referenced by DoNonCombatActions(), and PlayerbotDruidAI().
RAKE
uint32 PlayerbotDruidAI::RAKE private
Definition at line 177 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
REBIRTH
uint32 PlayerbotDruidAI::REBIRTH private
Definition at line 231 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI(), and ResurrectPlayer().
REGROWTH
uint32 PlayerbotDruidAI::REGROWTH private
Definition at line 223 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
REJUVENATION
uint32 PlayerbotDruidAI::REJUVENATION private
Definition at line 222 of file PlayerbotDruidAI.h.
Referenced by CastHoTOnTank(), HealPlayer(), and PlayerbotDruidAI().
REMOVE_CURSE
uint32 PlayerbotDruidAI::REMOVE_CURSE private
Definition at line 232 of file PlayerbotDruidAI.h.
Referenced by DispelPlayer(), and PlayerbotDruidAI().
REVIVE
uint32 PlayerbotDruidAI::REVIVE private
Definition at line 230 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI(), and ResurrectPlayer().
RIP
uint32 PlayerbotDruidAI::RIP private
Definition at line 178 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
ROOTS
uint32 PlayerbotDruidAI::ROOTS private
Definition at line 199 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
SAVAGE_ROAR
uint32 PlayerbotDruidAI::SAVAGE_ROAR private
Definition at line 183 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
SHADOWMELD
uint32 PlayerbotDruidAI::SHADOWMELD private
Definition at line 242 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
SpellSequence
uint32 PlayerbotDruidAI::SpellSequence private
Definition at line 248 of file PlayerbotDruidAI.h.
STARFALL
uint32 PlayerbotDruidAI::STARFALL private
Definition at line 202 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
STARFIRE
uint32 PlayerbotDruidAI::STARFIRE private
Definition at line 203 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
STONEFORM
uint32 PlayerbotDruidAI::STONEFORM private
Definition at line 239 of file PlayerbotDruidAI.h.
SWIFTMEND
uint32 PlayerbotDruidAI::SWIFTMEND private
Definition at line 228 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
SWIPE
uint32 PlayerbotDruidAI::SWIPE private
Definition at line 188 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverBear(), and PlayerbotDruidAI().
THORNS
uint32 PlayerbotDruidAI::THORNS private
Definition at line 216 of file PlayerbotDruidAI.h.
Referenced by CheckForms(), DoNonCombatActions(), and PlayerbotDruidAI().
TIGERS_FURY
uint32 PlayerbotDruidAI::TIGERS_FURY private
Definition at line 176 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverCat(), and PlayerbotDruidAI().
TRANQUILITY
uint32 PlayerbotDruidAI::TRANQUILITY private
Definition at line 229 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
TRAVEL_FORM
uint32 PlayerbotDruidAI::TRAVEL_FORM private
Definition at line 171 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
TREE_OF_LIFE
uint32 PlayerbotDruidAI::TREE_OF_LIFE private
Definition at line 170 of file PlayerbotDruidAI.h.
Referenced by CheckForms(), DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotDruidAI().
WAR_STOMP
uint32 PlayerbotDruidAI::WAR_STOMP private
Definition at line 244 of file PlayerbotDruidAI.h.
Referenced by PlayerbotDruidAI().
WILD_GROWTH
uint32 PlayerbotDruidAI::WILD_GROWTH private
Definition at line 227 of file PlayerbotDruidAI.h.
Referenced by HealPlayer(), and PlayerbotDruidAI().
WILL_OF_THE_FORSAKEN
uint32 PlayerbotDruidAI::WILL_OF_THE_FORSAKEN private
Definition at line 246 of file PlayerbotDruidAI.h.
WRATH
uint32 PlayerbotDruidAI::WRATH private
Definition at line 200 of file PlayerbotDruidAI.h.
Referenced by _DoNextPVECombatManeuverSpellDPS(), and PlayerbotDruidAI().
The documentation for this class was generated from the following files:
PlayerbotDruidAI.h
PlayerbotDruidAI.cpp