CMaNGOS_WoTLK: MaNGOS::FriendlyEligibleUnitConditionCheck Class Reference
MaNGOS::FriendlyEligibleUnitConditionCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
FriendlyEligibleUnitConditionCheck (Unit const *obj, float range, int32 unitConditionId)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
int32 i_unitConditionId
Detailed Description
Definition at line 1022 of file GridNotifiers.h.
Constructor & Destructor Documentation
FriendlyEligibleUnitConditionCheck()
MaNGOS::FriendlyEligibleUnitConditionCheck::FriendlyEligibleUnitConditionCheck (Unit const * obj, float range, int32 unitConditionId) inline
Definition at line 1025 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::FriendlyEligibleUnitConditionCheck::GetFocusObject () const inline
Definition at line 1026 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::FriendlyEligibleUnitConditionCheck::operator() (Unit * u) inline
Definition at line 1027 of file GridNotifiers.h.
References Unit::CanAssist(), i_obj, i_range, i_unitConditionId, Unit::IsAlive(), Unit::IsUnitConditionSatisfied(), and WorldObject::IsWithinCombatDistInMap().
Field Documentation
i_obj
Unit const* MaNGOS::FriendlyEligibleUnitConditionCheck::i_obj private
Definition at line 1039 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::FriendlyEligibleUnitConditionCheck::i_range private
Definition at line 1040 of file GridNotifiers.h.
Referenced by operator()().
i_unitConditionId
int32 MaNGOS::FriendlyEligibleUnitConditionCheck::i_unitConditionId private
Definition at line 1041 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h