CMaNGOS_WoTLK: TerrainInfo Class Reference
TerrainInfo Class Reference
#include <GridMap.h>
Public Member Functions
TerrainInfo (uint32 mapid)
~TerrainInfo ()
uint32 GetMapId () const
float GetHeightStatic (float x, float y, float z, bool useVmaps=true, float maxSearchDist=DEFAULT_HEIGHT_SEARCH) const
float GetWaterLevel (float x, float y, float z, float *pGround=nullptr) const
float GetWaterOrGroundLevel (float x, float y, float z, float &groundZ, bool swim=false, float minWaterDeep=DEFAULT_COLLISION_HEIGHT) const
Function find higher form water or ground height for current floor.
bool IsInWater (float x, float y, float z, GridMapLiquidData *data=nullptr, float min_depth=2.0f) const
bool IsSwimmable (float x, float y, float z, float radius=1.5f, GridMapLiquidData *data=nullptr) const
bool IsUnderWater (float x, float y, float z, float *waterZ=nullptr) const
bool IsAboveWater (float x, float y, float z, float *pWaterZ=nullptr) const
GridMapLiquidStatus getLiquidStatus (float x, float y, float z, uint8 ReqLiquidType, GridMapLiquidData *data=nullptr, float collisionHeight=2.03128f) const
uint16 GetAreaFlag (float x, float y, float z, bool *isOutdoors=nullptr) const
uint8 GetTerrainType (float x, float y) const
uint32 GetAreaId (float x, float y, float z) const
uint32 GetZoneId (float x, float y, float z) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid, float x, float y, float z) const
bool GetAreaInfo (float x, float y, float z, uint32 &flags, int32 &adtId, int32 &rootId, int32 &groupId) const
AreaNameInfo GetAreaName (float x, float y, float z, uint32 langIndex) const
bool IsOutdoors (float x, float y, float z) const
void CleanUpGrids (const uint32 diff)
bool CanCheckLiquidLevel (float x, float y) const
Public Member Functions inherited from Referencable< std::atomic_long >
Referencable ()
void AddRef ()
bool Release ()
bool IsReferenced () const
Protected Member Functions
GridMap * Load (const uint32 x, const uint32 y, bool mapOnly=false)
void Unload (const uint32 x, const uint32 y)
Private Types
typedef std::mutex LOCK_TYPE
typedef std::lock_guard< LOCK_TYPE > LOCK_GUARD
Private Member Functions
TerrainInfo (const TerrainInfo &)
TerrainInfo & operator= (const TerrainInfo &)
GridMap * GetGrid (const float x, const float y, bool loadOnlyMap=false)
GridMap * LoadMapAndVMap (const uint32 x, const uint32 y, bool mapOnly=false)
int RefGrid (const uint32 &x, const uint32 &y)
int UnrefGrid (const uint32 &x, const uint32 &y)
Private Attributes
const uint32 m_mapId
GridMap * m_GridMaps [MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS]
bool m_GridMapsLoadAttempted [MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS]
int16 m_GridRef [MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS]
ShortIntervalTimer i_timer
VMAP::IVMapManager * m_vmgr
LOCK_TYPE m_mutex
LOCK_TYPE m_refMutex
Friends
class Map
Map is a container which describes a full proto-spline made out of taxi node entries in a sequential order for a single game level.
class ObjectMgr
Detailed Description
Definition at line 139 of file GridMap.h.
Member Typedef Documentation
LOCK_GUARD
typedef std::lock_guard<LOCK_TYPE> TerrainInfo::LOCK_GUARD private
Definition at line 207 of file GridMap.h.
LOCK_TYPE
typedef std::mutex TerrainInfo::LOCK_TYPE private
Definition at line 206 of file GridMap.h.
Constructor & Destructor Documentation
TerrainInfo() [1/2]
TerrainInfo::TerrainInfo (uint32 mapid)
Definition at line 713 of file GridMap.cpp.
References VMAP::VMapFactory::createOrGetVMapManager(), i_timer, m_GridMaps, m_GridMapsLoadAttempted, m_GridRef, m_vmgr, MAX_NUMBER_OF_GRIDS, ShortIntervalTimer::SetCurrent(), ShortIntervalTimer::SetInterval(), and urand().
~TerrainInfo()
TerrainInfo::~TerrainInfo ()
Definition at line 736 of file GridMap.cpp.
References MMAP::MMapFactory::createOrGetMMapManager(), m_GridMaps, m_mapId, m_vmgr, MAX_NUMBER_OF_GRIDS, MMAP::MMapManager::unloadMap(), and VMAP::IVMapManager::unloadMap().
TerrainInfo() [2/2]
TerrainInfo::TerrainInfo (const TerrainInfo &) private
Member Function Documentation
CanCheckLiquidLevel()
bool TerrainInfo::CanCheckLiquidLevel (float x, float y) const
Definition at line 817 of file GridMap.cpp.
References GetGrid(), VMAP::IVMapManager::isHeightCalcEnabled(), and m_vmgr.
Referenced by GetWaterLevel(), GetWaterOrGroundLevel(), IsAboveWater(), IsInWater(), IsSwimmable(), and IsUnderWater().
CleanUpGrids()
void TerrainInfo::CleanUpGrids (const uint32 diff)
Definition at line 783 of file GridMap.cpp.
References i_timer, m_GridMaps, m_GridMapsLoadAttempted, m_GridRef, m_mapId, m_vmgr, MAX_NUMBER_OF_GRIDS, ShortIntervalTimer::Passed(), ShortIntervalTimer::Reset(), GridMap::unloadData(), VMAP::IVMapManager::unloadMap(), and ShortIntervalTimer::Update().
GetAreaFlag()
uint16 TerrainInfo::GetAreaFlag (float x, float y, float z, bool * isOutdoors = nullptr) const
Definition at line 1035 of file GridMap.cpp.
References AreaTableEntry::exploreFlag, GetAreaEntryByAreaID(), GetAreaFlagByMapId(), GetAreaInfo(), GetGrid(), GetMapId(), GetWMOAreaTableEntriesByTripple(), and IsOutdoorWMO().
Referenced by Player::CheckAreaExploreAndOutdoor(), TerrainManager::GetAreaFlag(), GetAreaId(), getLiquidStatus(), GetZoneAndAreaId(), and GetZoneId().
GetAreaId()
uint32 TerrainInfo::GetAreaId (float x, float y, float z) const
Definition at line 1089 of file GridMap.cpp.
References GetAreaFlag(), TerrainManager::GetAreaIdByAreaFlag(), and m_mapId.
Referenced by WorldObject::GetAreaId(), and ChatHandler::HandleListAreaTriggerCommand().
GetAreaInfo()
bool TerrainInfo::GetAreaInfo (float x, float y, float z, uint32 & flags, int32 & adtId, int32 & rootId, int32 & groupId) const
Definition at line 958 of file GridMap.cpp.
References VMAP::IVMapManager::getAreaInfo(), GetGrid(), GetMapId(), and m_vmgr.
Referenced by GetAreaFlag(), GetAreaName(), and IsOutdoors().
GetAreaName()
AreaNameInfo TerrainInfo::GetAreaName (float x, float y, float z, uint32 langIndex) const
Definition at line 980 of file GridMap.cpp.
References AreaTableEntry::area_name, AreaNameInfo::areaName, GetAreaEntryByAreaFlagAndMap(), GetAreaEntryByAreaID(), GetAreaInfo(), GetGrid(), GetWMOAreaTableEntriesByTripple(), m_mapId, and AreaNameInfo::wmoNameOverride.
Referenced by WorldObject::GetAreaName().
GetGrid()
GridMap * TerrainInfo::GetGrid (const float x, const float y, bool loadOnlyMap = false) private
Definition at line 1308 of file GridMap.cpp.
References GridMap::IsFullyLoaded(), LoadMapAndVMap(), m_GridMaps, m_GridMapsLoadAttempted, and SIZE_OF_GRIDS.
Referenced by CanCheckLiquidLevel(), GetAreaFlag(), GetAreaInfo(), GetAreaName(), GetHeightStatic(), getLiquidStatus(), and GetTerrainType().
GetHeightStatic()
float TerrainInfo::GetHeightStatic (float x, float y, float z, bool useVmaps = true, float maxSearchDist = DEFAULT_HEIGHT_SEARCH) const
Definition at line 848 of file GridMap.cpp.
References DEFAULT_HEIGHT_SEARCH, GetGrid(), VMAP::IVMapManager::getHeight(), GetMapId(), INVALID_HEIGHT, VMAP::IVMapManager::isHeightCalcEnabled(), m_vmgr, and VMAP_INVALID_HEIGHT_VALUE.
Referenced by PlayerbotAI::findNearbyGO(), Map::GetHeight(), getLiquidStatus(), GetWaterLevel(), ChatHandler::HandleGPSCommand(), and Creature::LoadFromDB().
getLiquidStatus()
GridMapLiquidStatus TerrainInfo::getLiquidStatus (float x, float y, float z, uint8 ReqLiquidType, GridMapLiquidData * data = nullptr, float collisionHeight = 2.03128f) const
Definition at line 1104 of file GridMap.cpp.
References DEFAULT_WATER_SEARCH, GridMapLiquidData::depth_level, GridMapLiquidData::entry, GetAreaEntryByAreaFlagAndMap(), GetAreaEntryByAreaID(), GetAreaFlag(), GetGrid(), GetHeightStatic(), VMAP::IVMapManager::GetLiquidLevel(), GetMapId(), INVALID_HEIGHT_VALUE, GridMapLiquidData::level, LIQUID_MAP_ABOVE_WATER, LIQUID_MAP_IN_WATER, LIQUID_MAP_NO_WATER, LIQUID_MAP_UNDER_WATER, LIQUID_MAP_WATER_WALK, m_vmgr, sLiquidTypeStore, and GridMapLiquidData::type_flags.
Referenced by PathFinder::getNavTerrain(), Map::GetReachableRandomPosition(), GetWaterLevel(), GetWaterOrGroundLevel(), ChatHandler::HandleGPSCommand(), IsAboveWater(), IsInWater(), IsSwimmable(), IsUnderWater(), and Player::UpdateTerainEnvironmentFlags().
GetMapId()
uint32 TerrainInfo::GetMapId () const inline
Definition at line 145 of file GridMap.h.
References m_mapId.
Referenced by GetAreaFlag(), GetAreaInfo(), GetHeightStatic(), getLiquidStatus(), IsOutdoors(), and Map::~Map().
GetTerrainType()
uint8 TerrainInfo::GetTerrainType (float x, float y) const
Definition at line 1082 of file GridMap.cpp.
References GetGrid().
GetWaterLevel()
float TerrainInfo::GetWaterLevel (float x, float y, float z, float * pGround = nullptr) const
Definition at line 1390 of file GridMap.cpp.
References CanCheckLiquidLevel(), DEFAULT_WATER_SEARCH, GetHeightStatic(), getLiquidStatus(), GridMapLiquidData::level, MAP_ALL_LIQUIDS, and VMAP_INVALID_HEIGHT_VALUE.
Referenced by Aura::HandlePeriodicTriggerSpell(), and Spell::SetTargetMap().
GetWaterOrGroundLevel()
float TerrainInfo::GetWaterOrGroundLevel (float x, float y, float z, float & groundZ, bool swim = false, float minWaterDeep = DEFAULT_COLLISION_HEIGHT) const
Function find higher form water or ground height for current floor.
Parameters
x,y,z Coordinates original point at floor level
groundZ precalculated Z through getHeight
swim z coordinate can be calculated for select above/at or under z coordinate (for fly or swim/walking by bottom) in last cases for in water returned under water height for avoid client set swimming unit as stay at water.
minWaterDeep Default is DEFAULT_COLLISION_HEIGHT. Define minimum height of water to be able to be in water.
Returns
calculated z coordinate
Definition at line 1280 of file GridMap.cpp.
References CanCheckLiquidLevel(), getLiquidStatus(), GridMapLiquidData::level, MAP_ALL_LIQUIDS, and VMAP_INVALID_HEIGHT_VALUE.
Referenced by ChatHandler::HandleGoHelper(), boss_brundirAI::UpdateAI(), and Unit::UpdateAllowedPositionZ().
GetZoneAndAreaId()
void TerrainInfo::GetZoneAndAreaId (uint32 & zoneid, uint32 & areaid, float x, float y, float z) const
Definition at line 1099 of file GridMap.cpp.
References GetAreaFlag(), TerrainManager::GetZoneAndAreaIdByAreaFlag(), and m_mapId.
Referenced by NamreebAnticheat::Movement::CheckTeleport(), WorldObject::GetZoneAndAreaId(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), and NamreebAnticheat::Movement::IsTeleportAllowed().
GetZoneId()
uint32 TerrainInfo::GetZoneId (float x, float y, float z) const
Definition at line 1094 of file GridMap.cpp.
References GetAreaFlag(), TerrainManager::GetZoneIdByAreaFlag(), and m_mapId.
Referenced by WorldObject::GetZoneId().
IsAboveWater()
bool TerrainInfo::IsAboveWater (float x, float y, float z, float * pWaterZ = nullptr) const
Definition at line 1232 of file GridMap.cpp.
References CanCheckLiquidLevel(), getLiquidStatus(), GridMapLiquidData::level, LIQUID_MAP_ABOVE_WATER, MAP_LIQUID_TYPE_OCEAN, and MAP_LIQUID_TYPE_WATER.
Referenced by Spell::EffectTransmitted().
IsInWater()
bool TerrainInfo::IsInWater (float x, float y, float z, GridMapLiquidData * data = nullptr, float min_depth = 2.0f) const
Definition at line 1188 of file GridMap.cpp.
References CanCheckLiquidLevel(), GridMapLiquidData::depth_level, getLiquidStatus(), GridMapLiquidData::level, LIQUID_MAP_ABOVE_WATER, LIQUID_MAP_IN_WATER, LIQUID_MAP_NO_WATER, LIQUID_MAP_UNDER_WATER, LIQUID_MAP_WATER_WALK, and MAP_ALL_LIQUIDS.
Referenced by Unit::IsInWater(), and Spell::SetTargetMap().
IsOutdoors()
bool TerrainInfo::IsOutdoors (float x, float y, float z) const
Definition at line 930 of file GridMap.cpp.
References DEBUG_LOG, GetAreaEntryByAreaID(), GetAreaInfo(), GetMapId(), GetWMOAreaTableEntriesByTripple(), and IsOutdoorWMO().
Referenced by Spell::CheckCast(), ChatHandler::HandleGPSCommand(), and Unit::IsTriggeredAtSpellProcEvent().
IsSwimmable()
bool TerrainInfo::IsSwimmable (float x, float y, float z, float radius = 1.5f, GridMapLiquidData * data = nullptr) const
Definition at line 1216 of file GridMap.cpp.
References CanCheckLiquidLevel(), GridMapLiquidData::depth_level, getLiquidStatus(), GridMapLiquidData::level, and MAP_ALL_LIQUIDS.
Referenced by PathFinder::BuildPolyPath(), Unit::IsInSwimmableWater(), and PlayerbotAI::UpdateAI().
IsUnderWater()
bool TerrainInfo::IsUnderWater (float x, float y, float z, float * waterZ = nullptr) const
Definition at line 1249 of file GridMap.cpp.
References CanCheckLiquidLevel(), getLiquidStatus(), GridMapLiquidData::level, LIQUID_MAP_UNDER_WATER, MAP_LIQUID_TYPE_OCEAN, and MAP_LIQUID_TYPE_WATER.
Referenced by PathFinder::BuildPolyPath(), and Unit::IsUnderwater().
Load()
GridMap * TerrainInfo::Load (const uint32 x, const uint32 y, bool mapOnly = false) protected
Definition at line 746 of file GridMap.cpp.
References LoadMapAndVMap(), m_GridMaps, m_GridMapsLoadAttempted, MANGOS_ASSERT, MAX_NUMBER_OF_GRIDS, and RefGrid().
Referenced by Map::LoadMapAndVMap().
LoadMapAndVMap()
GridMap * TerrainInfo::LoadMapAndVMap (const uint32 x, const uint32 y, bool mapOnly = false) private
Definition at line 1327 of file GridMap.cpp.
References DEBUG_FILTER_LOG, VMAP::IVMapManager::IsTileLoaded(), GridMap::loadData(), VMAP::IVMapManager::loadMap(), LOG_FILTER_MAP_LOADING, m_GridMaps, m_mapId, m_mutex, m_vmgr, MapEntry::name, GridMap::SetFullyLoaded(), sLog, sMapStore, sWorld, VMAP::VMAP_LOAD_RESULT_ERROR, VMAP::VMAP_LOAD_RESULT_IGNORED, and VMAP::VMAP_LOAD_RESULT_OK.
Referenced by GetGrid(), and Load().
operator=()
TerrainInfo& TerrainInfo::operator= (const TerrainInfo &) private
RefGrid()
int TerrainInfo::RefGrid (const uint32 & x, const uint32 & y) private
Definition at line 825 of file GridMap.cpp.
References m_GridRef, m_refMutex, MANGOS_ASSERT, and MAX_NUMBER_OF_GRIDS.
Referenced by Load().
Unload()
void TerrainInfo::Unload (const uint32 x, const uint32 y) protected
Definition at line 766 of file GridMap.cpp.
References m_GridMaps, m_GridMapsLoadAttempted, MANGOS_ASSERT, MAX_NUMBER_OF_GRIDS, and UnrefGrid().
Referenced by Map::UnloadGrid().
UnrefGrid()
int TerrainInfo::UnrefGrid (const uint32 & x, const uint32 & y) private
Definition at line 834 of file GridMap.cpp.
References m_GridRef, m_refMutex, MANGOS_ASSERT, and MAX_NUMBER_OF_GRIDS.
Referenced by Unload().
Friends And Related Function Documentation
Map
friend class Map friend
Map is a container which describes a full proto-spline made out of taxi node entries in a sequential order for a single game level.
Definition at line 179 of file GridMap.h.
ObjectMgr
friend class ObjectMgr friend
Definition at line 180 of file GridMap.h.
Field Documentation
i_timer
ShortIntervalTimer TerrainInfo::i_timer private
Definition at line 202 of file GridMap.h.
Referenced by CleanUpGrids(), and TerrainInfo().
m_GridMaps
GridMap* TerrainInfo::m_GridMaps[MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS] private
Definition at line 197 of file GridMap.h.
Referenced by CleanUpGrids(), GetGrid(), Load(), LoadMapAndVMap(), TerrainInfo(), Unload(), and ~TerrainInfo().
m_GridMapsLoadAttempted
bool TerrainInfo::m_GridMapsLoadAttempted[MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS] private
Definition at line 198 of file GridMap.h.
Referenced by CleanUpGrids(), GetGrid(), Load(), TerrainInfo(), and Unload().
m_GridRef
int16 TerrainInfo::m_GridRef[MAX_NUMBER_OF_GRIDS][MAX_NUMBER_OF_GRIDS] private
Definition at line 199 of file GridMap.h.
Referenced by CleanUpGrids(), RefGrid(), TerrainInfo(), and UnrefGrid().
m_mapId
const uint32 TerrainInfo::m_mapId private
Definition at line 195 of file GridMap.h.
Referenced by CleanUpGrids(), GetAreaId(), GetAreaName(), GetMapId(), GetZoneAndAreaId(), GetZoneId(), LoadMapAndVMap(), and ~TerrainInfo().
m_mutex
LOCK_TYPE TerrainInfo::m_mutex private
Definition at line 208 of file GridMap.h.
Referenced by LoadMapAndVMap().
m_refMutex
LOCK_TYPE TerrainInfo::m_refMutex private
Definition at line 209 of file GridMap.h.
Referenced by RefGrid(), and UnrefGrid().
m_vmgr
VMAP::IVMapManager* TerrainInfo::m_vmgr private
Definition at line 204 of file GridMap.h.
Referenced by CanCheckLiquidLevel(), CleanUpGrids(), GetAreaInfo(), GetHeightStatic(), getLiquidStatus(), LoadMapAndVMap(), TerrainInfo(), and ~TerrainInfo().
The documentation for this class was generated from the following files:
GridMap.h
GridMap.cpp