CMaNGOS_WoTLK: PlayerTaxi Class Reference
PlayerTaxi Class Reference
#include <Player.h>
Public Member Functions
PlayerTaxi ()
~PlayerTaxi ()
void InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint32 level)
void LoadTaxiMask (const char *data)
bool IsTaximaskNodeKnown (uint32 nodeidx) const
bool SetTaximaskNode (uint32 nodeidx)
void AppendTaximaskTo (ByteBuffer &data, bool all)
Private Attributes
TaxiMask m_taximask
Friends
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
Detailed Description
Definition at line 942 of file Player.h.
Constructor & Destructor Documentation
PlayerTaxi()
PlayerTaxi::PlayerTaxi ()
Definition at line 285 of file Player.cpp.
References m_taximask.
~PlayerTaxi()
PlayerTaxi::~PlayerTaxi () inline
Definition at line 946 of file Player.h.
Member Function Documentation
AppendTaximaskTo()
void PlayerTaxi::AppendTaximaskTo (ByteBuffer & data, bool all)
Definition at line 348 of file Player.cpp.
References m_taximask, and sTaxiNodesMask.
Referenced by WorldSession::SendTaxiMenu().
InitTaxiNodesForLevel()
void PlayerTaxi::InitTaxiNodesForLevel (uint32 race, uint32 chrClass, uint32 level)
Definition at line 291 of file Player.cpp.
References ALLIANCE, CLASS_DEATH_KNIGHT, HORDE, m_taximask, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD, SetTaximaskNode(), sOldContinentsNodesMask, TaxiMaskSize, and Player::TeamForRace().
Referenced by Player::InitTaxiNodesForLevel().
IsTaximaskNodeKnown()
bool PlayerTaxi::IsTaximaskNodeKnown (uint32 nodeidx) const inline
Definition at line 951 of file Player.h.
References m_taximask.
Referenced by PlayerbotAI::GetTaxi(), WorldSession::HandleActivateTaxiExpressOpcode(), and WorldSession::HandleActivateTaxiOpcode().
LoadTaxiMask()
void PlayerTaxi::LoadTaxiMask (const char * data)
Definition at line 334 of file Player.cpp.
References m_taximask, sTaxiNodesMask, StrSplit(), and TaxiMaskSize.
Referenced by Player::LoadFromDB().
SetTaximaskNode()
bool PlayerTaxi::SetTaximaskNode (uint32 nodeidx) inline
Definition at line 957 of file Player.h.
References m_taximask.
Referenced by Spell::EffectTeachTaxiNode(), and InitTaxiNodesForLevel().
Friends And Related Function Documentation
operator<<
std::ostringstream& operator<< (std::ostringstream & ss, PlayerTaxi const & taxi) friend
Definition at line 362 of file Player.cpp.
Field Documentation
m_taximask
TaxiMask PlayerTaxi::m_taximask private
Definition at line 973 of file Player.h.
Referenced by AppendTaximaskTo(), InitTaxiNodesForLevel(), IsTaximaskNodeKnown(), LoadTaxiMask(), PlayerTaxi(), and SetTaximaskNode().
The documentation for this class was generated from the following files:
Player.h
Player.cpp