CMaNGOS_WoTLK: GameObject Class Reference
GameObject Class Reference
#include <GameObject.h>
Public Member Functions
GameObject ()
~GameObject ()
void AddToWorld () override
void RemoveFromWorld () override
virtual bool Create (uint32 dbGuid, uint32 guidlow, uint32 name_id, Map *map, uint32 phaseMask, float x, float y, float z, float ang, const QuaternionData &rotation=QuaternionData(), uint8 animprogress=GO_ANIMPROGRESS_DEFAULT, GOState go_state=GO_STATE_READY)
void Update (const uint32 diff) override
void Heartbeat () override
GameObjectInfo const * GetGOInfo () const
GameObjectTemplateAddon const * GetTemplateAddon () const
bool IsTransport () const
bool IsMoTransport () const
bool IsDynTransport () const
bool HasStaticDBSpawnData () const
void SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
void SetLocalRotation (float qx, float qy, float qz, float qw)
void SetTransportPathRotation (const QuaternionData &rotation)
int64 GetPackedLocalRotation () const
QuaternionData GetWorldRotation () const
QuaternionData const GetLocalRotation () const
const char * GetNameForLocaleIdx (int32 loc_idx) const override
void SaveToDB () const
void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask) const
bool LoadFromDB (uint32 dbGuid, Map *map, uint32 newGuid, uint32 forcedEntry, GenericTransport *transport=nullptr)
void DeleteFromDB () const
ObjectGuid const & GetOwnerGuid () const override
void SetOwnerGuid (ObjectGuid guid) override
ObjectGuid const GetSpawnerGuid () const
void SetSpawnerGuid (ObjectGuid guid)
Unit * GetOwner () const
WorldObject * GetSpawner () const
void SetSpellId (uint32 id)
uint32 GetSpellId () const
void ForcedDespawn (uint32 timeMSToDespawn=0)
time_t GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (time_t respawn)
void Respawn ()
bool IsSpawned () const
bool IsSpawnedByDefault () const
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay, bool once=false)
void SetForcedDespawn ()
void Refresh ()
void Delete ()
GameobjectTypes GetGoType () const
void SetGoType (GameobjectTypes type)
GOState GetGoState () const
virtual void SetGoState (GOState state)
uint8 GetGoArtKit () const
void SetGoArtKit (uint8 artkit)
uint8 GetGoAnimProgress () const
void SetGoAnimProgress (uint8 animprogress)
uint32 GetDisplayId () const
void SetDisplayId (uint32 modelId)
void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetFaction () const override
void SetFaction (uint32 faction)
uint32 GetLevel () const override
void Use (Unit *user, SpellEntry const *spellInfo=nullptr)
LootState GetLootState () const
void SetLootState (LootState state, Unit *user=nullptr)
void AddToSkillupList (Player *player)
bool IsInSkillupList (Player *player) const
void ClearSkillupList ()
void ClearAllUsesData ()
void SetActionTarget (ObjectGuid guid)
void AddUniqueUse (Player *player)
void AddUse ()
bool IsInUse () const
void SetInUse (bool use)
uint32 GetUseCount () const
uint32 GetUniqueUseCount () const
void SaveRespawnTime () override
ObjectGuid GetLootRecipientGuid () const
uint32 GetLootGroupRecipientId () const
Player * GetLootRecipient () const
Group * GetGroupLootRecipient () const
bool HasLootRecipient () const
bool IsGroupLootRecipient () const
void SetLootRecipient (Unit *pUnit)
Player * GetOriginalLootRecipient () const
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32 quest_id) const override
bool ActivateToQuest (Player *pTarget) const
void UseDoorOrButton (uint32 time_to_restore=0, bool alternative=false)
void ResetDoorOrButton (Unit *user=nullptr)
void UseOpenableObject (bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
ReputationRank GetReactionTo (Unit const *unit) const override
Get GO to unit reaction.
bool IsEnemy (Unit const *unit) const override
[Serverside] Reaction preset: GO sees a unit as an enemy
bool IsFriend (Unit const *unit) const override
[Serverside] Reaction preset: GO sees a unit as a friend
bool CanAttackSpell (Unit const *target, SpellEntry const *spellInfo=nullptr, bool isAOE=false) const override
[Serverside] Opposition: GameObject can target a target with a harmful spell
bool CanAssistSpell (Unit const *target, SpellEntry const *spellInfo=nullptr) const override
[Serverside] Assistance: GameObject can target a target with a helpful spell
GameObject * SummonLinkedTrapIfAny () const
void TriggerLinkedGameObject (Unit *target) const
GameObject * GetLinkedTrap ()
void SetLinkedTrap (GameObject *linkedTrap)
void DealGameObjectDamage (uint32 damage, uint32 spell, Unit *caster)
void RebuildGameObject (Unit *caster)
void SetDestructibleState (GameObjectDestructibleState state, Unit *attackerOrHealer=nullptr, bool setHealth=false)
GameObjectDestructibleState GetDestructibleState () const
uint32 GetHealth () const
uint32 GetMaxHealth () const
bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const override
bool IsCollisionEnabled () const
GameObject * LookupFishingHoleAround (float range) const
void SetCapturePointSlider (float value, bool isLocked)
float GetCapturePointSliderValue () const
float GetInteractionDistance () const
float GetCollisionHeight () const override
GridReference< GameObject > & GetGridRef ()
uint32 GetScriptId () const
void AIM_Initialize ()
void OnEventHappened (uint16 eventId, bool activate, bool resume) override
GameObjectAI * AI () const
void AddModelToMap ()
void RemoveModelFromMap ()
void UpdateModelPosition ()
bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const override
bool IsAtInteractDistance (Position const &pos, float radius, bool is3D=true) const
bool IsAtInteractDistance (Player const *player, uint32 maxRange=0) const
SpellEntry const * GetSpellForLock (Player const *player) const
float GetStationaryX () const
float GetStationaryY () const
float GetStationaryZ () const
float GetStationaryO () const
std::pair< float, float > GetClosestChairSlotPosition (Unit *user) const
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
void GenerateLootFor (Player *player)
HighGuid GetParentHigh () const override
void SetCooldown (uint32 cooldown)
void SetGameObjectGroup (GameObjectGroup *group)
void ClearGameObjectGroup ()
GameObjectGroup * GetGameObjectGroup () const
Public Member Functions inherited from WorldObject
virtual ~WorldObject ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
virtual float GetCollisionWidth () const
virtual float GetObjectBoundingRadius () const
virtual float GetCombatReach () const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
virtual void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const
virtual void AdjustZForCollision (float, float, float &, float) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void CleanupsBeforeDelete ()
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
virtual ReputationRank GetReactionTo (Corpse const *corpse) const
[Serverside] Get default WorldObject (hierarchy) reaction to a corpse
bool IsControlledByPlayer () const
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
virtual void UpdateVisibilityAndView ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
void SetNotifyOnEventState (bool state)
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
virtual void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration)
void PrintCooldownList (ChatHandler &chat) const
virtual void InspectingLoot ()
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Static Public Member Functions
static GameObject * CreateGameObject (uint32 entry)
static void AddToRemoveListInMaps (uint32 db_guid, GameObjectData const *data)
static void SpawnInMaps (uint32 db_guid, GameObjectData const *data)
Static Public Member Functions inherited from WorldObject
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Data Fields
GameObjectModel * m_model
Data Fields inherited from WorldObject
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Protected Member Functions
void TriggerSummoningRitual ()
void TriggerDelayedAction ()
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes
uint32 m_spellId
time_t m_respawnTime
uint32 m_respawnDelay
bool m_respawnOverriden
bool m_respawnOverrideOnce
bool m_forcedDespawn
LootState m_lootState
bool m_spawnedByDefault
time_t m_cooldownTime
uint32 m_captureTimer
float m_captureSlider
CapturePointState m_captureState
GuidSet m_SkillupSet
uint32 m_useTimes
ObjectGuid m_firstUser
GuidSet m_UniqueUsers
GameObjectInfo const * m_goInfo
GameObjectDisplayInfoEntry const * m_displayInfo
int64 m_packedRotation
QuaternionData m_localRotation
Position m_stationaryPosition
ObjectGuid m_lootRecipientGuid
uint32 m_lootGroupRecipientId
time_t m_rearmTimer
bool m_isInUse
time_t m_reStockTimer
time_t m_despawnTimer
uint32 m_delayedActionTimer
ObjectGuid m_actionTarget
ObjectGuid m_linkedTrap
std::unique_ptr< GameObjectAI > m_AI
ObjectGuid m_spawnerGuid
GameObjectGroup * m_goGroup
Protected Attributes inherited from WorldObject
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Private Member Functions
void SwitchDoorOrButton (bool activate, bool alternative=false)
void TickCapturePoint ()
void UpdateModel ()
void UpdateCollisionState () const
void ForceGameObjectHealth (int32 diff, Unit *caster)
Private Attributes
GridReference< GameObject > m_gridRef
Detailed Description
Definition at line 740 of file GameObject.h.
Constructor & Destructor Documentation
GameObject()
GameObject::GameObject () explicit
Definition at line 66 of file GameObject.cpp.
References GAMEOBJECT_END, GO_READY, m_captureTimer, m_cooldownTime, m_delayedActionTimer, m_despawnTimer, m_forcedDespawn, m_goGroup, m_isInUse, m_lootGroupRecipientId, m_lootState, Object::m_objectType, Object::m_objectTypeId, m_packedRotation, m_rearmTimer, m_respawnDelay, m_respawnOverriden, m_respawnOverrideOnce, m_respawnTime, m_reStockTimer, m_spawnedByDefault, m_spellId, Object::m_updateFlag, m_useTimes, Object::m_valuesCount, TYPEID_GAMEOBJECT, TYPEMASK_GAMEOBJECT, UPDATEFLAG_HAS_POSITION, UPDATEFLAG_HIGHGUID, UPDATEFLAG_POSITION, and UPDATEFLAG_ROTATION.
Referenced by CreateGameObject(), and SummonLinkedTrapIfAny().
~GameObject()
GameObject::~GameObject ()
Definition at line 108 of file GameObject.cpp.
References m_model.
Member Function Documentation
_IsWithinDist()
bool GameObject::_IsWithinDist (WorldObject const * obj, float dist2compare, bool is3D) const override virtual
Reimplemented from WorldObject.
Definition at line 2855 of file GameObject.cpp.
References DIST_CALC_NONE, GAMEOBJECT_TYPE_TRAP, WorldObject::GetCombatReach(), WorldObject::GetDistance(), GetGOInfo(), GetGoType(), WorldObject::GetPosition(), and IsAtInteractDistance().
ActivateToQuest()
bool GameObject::ActivateToQuest (Player * pTarget) const
Definition at line 1215 of file GameObject.cpp.
References Player::CanTakeQuest(), GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, Object::GetEntry(), GetGOInfo(), GetGoType(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), Player::HasQuestForGO(), LootStore::HaveQuestLootForPlayer(), LootTemplates_Gameobject, QUEST_STATUS_COMPLETE, QUEST_STATUS_INCOMPLETE, GameObjectInfo::questId, GameObjectInfo::questID, and sObjectMgr.
AddModelToMap()
void GameObject::AddModelToMap ()
Definition at line 2183 of file GameObject.cpp.
References WorldObject::GetMap(), Map::InsertGameObjectModel(), m_model, and GameObjectModel::Relocate().
AddToRemoveListInMaps()
void GameObject::AddToRemoveListInMaps (uint32 db_guid, GameObjectData const * data) static
Definition at line 2307 of file GameObject.cpp.
References HIGHGUID_GAMEOBJECT, GameObjectData::id, GameObjectData::mapid, and sMapMgr.
Referenced by GameEventMgr::GameEventUnspawn().
AddToSkillupList()
void GameObject::AddToSkillupList (Player * player)
Definition at line 2289 of file GameObject.cpp.
References Object::GetObjectGuid(), and m_SkillupSet.
Referenced by Spell::EffectOpenLock().
AddToWorld()
void GameObject::AddToWorld () override virtual
Register the gameobject for guid lookup
Reimplemented from WorldObject.
Definition at line 121 of file GameObject.cpp.
References Map::AddDbGuidObject(), WorldObject::AddToWorld(), GAMEOBJECT_EXTRA_FLAG_ACTIVE, Object::GetDbGuid(), GetGOInfo(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetObjectsStore(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert(), Map::InsertGameObjectModel(), Object::IsInWorld(), IsSpawned(), m_model, WorldObject::SetActiveObjectState(), SetLinkedTrap(), SummonLinkedTrapIfAny(), and UpdateCollisionState().
AddUniqueUse()
void GameObject::AddUniqueUse (Player * player)
Definition at line 790 of file GameObject.cpp.
References AddUse(), Object::GetObjectGuid(), m_firstUser, and m_UniqueUsers.
Referenced by Spell::EffectTransmitted(), and Use().
AddUse()
void GameObject::AddUse () inline
Definition at line 863 of file GameObject.h.
References m_useTimes.
Referenced by AddUniqueUse(), Loot::Release(), and Use().
AI()
GameObjectAI* GameObject::AI () const inline
Definition at line 928 of file GameObject.h.
References m_AI.
Referenced by AIM_Initialize(), Delete(), GOUse_go_manticron_cube(), Heartbeat(), npc_frequency_scanner::JustSummoned(), BonfireArtkit::OnEffectExecute(), OnEventHappened(), SetGoState(), Update(), ElevatorTransport::Update(), Transport::Update(), and Use().
AIM_Initialize()
void GameObject::AIM_Initialize ()
Definition at line 2823 of file GameObject.cpp.
References AI(), WorldObject::GetInstanceData(), WorldObject::GetMap(), GameObjectAI::JustSpawned(), m_AI, and sScriptDevAIMgr.
Referenced by Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), LoadFromDB(), Refresh(), SummonLinkedTrapIfAny(), and Update().
CanAssistSpell()
bool GameObject::CanAssistSpell (Unit const * target, SpellEntry const * spellInfo = nullptr) const override virtual
[Serverside] Assistance: GameObject can target a target with a helpful spell
Note
Relations API Tier 3
This function is not intented to have client-side counterpart by original design. Some gameobjects can be involved in spell casting, so server needs additional API support. It utilizes owners CanAssistSpell if owner exists
Reimplemented from WorldObject.
Definition at line 1192 of file Relations.cpp.
References GetOwner(), Object::HasFlag(), IsEnemy(), IsFriend(), MANGOS_ASSERT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by MaNGOS::GameObjectTypeInPosRangeCheck::operator()().
CanAttackSpell()
bool GameObject::CanAttackSpell (Unit const * target, SpellEntry const * spellInfo = nullptr, bool isAOE = false) const override virtual
[Serverside] Opposition: GameObject can target a target with a harmful spell
Note
Relations API Tier 3
This function is not intented to have client-side counterpart by original design. Some gameobjects can be involved in spell casting, so server needs additional API support. It utilizes owners CanAttackSpell if owner exists
Reimplemented from WorldObject.
Definition at line 1170 of file Relations.cpp.
References GetOwner(), Object::HasFlag(), IsEnemy(), IsFriend(), MANGOS_ASSERT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by MaNGOS::GameObjectTypeInPosRangeCheck::operator()().
CastSpell() [1/3]
SpellCastResult GameObject::CastSpell (Unit * temporaryCaster, Unit * Victim, SpellEntry const * spellInfo, uint32 triggeredFlags, Item * castItem = nullptr, Aura * triggeredByAura = nullptr, ObjectGuid originalCaster = ObjectGuid(), SpellEntry const * triggeredBy = nullptr)
Definition at line 2978 of file GameObject.cpp.
References DEBUG_FILTER_LOG, Aura::GetCasterGuid(), Spell::GetCastingObject(), Aura::GetEffIndex(), Object::GetEntry(), Object::GetGuidStr(), Aura::GetId(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Aura::GetSpellProto(), SpellEntry::Id, IsChanneledSpell(), LOG_FILTER_SPELL_CAST, Spell::SetCastItem(), SpellCastTargets::setDestination(), Spell::SetFakeCaster(), SpellCastTargets::setSource(), SpellCastTargets::setUnitTarget(), sLog, SPELL_FAILED_ERROR, SPELL_NOT_FOUND, Spell::SpellStart(), TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_SOURCE_LOCATION, and SpellEntry::Targets.
CastSpell() [2/3]
SpellCastResult GameObject::CastSpell (Unit * temporaryCaster, Unit * Victim, uint32 spellId, TriggerCastFlags triggeredFlags, Item * castItem = nullptr, Aura * triggeredByAura = nullptr, ObjectGuid originalCaster = ObjectGuid(), SpellEntry const * triggeredBy = nullptr) inline
Definition at line 951 of file GameObject.h.
References CastSpell().
CastSpell() [3/3]
SpellCastResult GameObject::CastSpell (Unit * temporaryCaster, Unit * Victim, uint32 spellId, uint32 triggeredFlags, Item * castItem = nullptr, Aura * triggeredByAura = nullptr, ObjectGuid originalCaster = ObjectGuid(), SpellEntry const * triggeredBy = nullptr)
Definition at line 2973 of file GameObject.cpp.
References SQLStorage::LookupEntry(), and sSpellTemplate.
Referenced by CastSpell(), Spell::DoSummonWild(), GoCircle::GoCircle(), GossipSelect_go_icc_teleporter(), GossipSelect_go_ulduar_teleporter(), go_bonfire::JustSpawned(), DreadsteedQuestObjects::UpdateAI(), go_ai_suppression::UpdateAI(), go_ai_ectoplasmic_distiller_trap::UpdateAI(), and Use().
ClearAllUsesData()
void GameObject::ClearAllUsesData () inline
Definition at line 853 of file GameObject.h.
References ObjectGuid::Clear(), ClearSkillupList(), m_firstUser, m_UniqueUsers, and m_useTimes.
Referenced by TriggerSummoningRitual(), and Update().
ClearGameObjectGroup()
void GameObject::ClearGameObjectGroup ()
Definition at line 3039 of file GameObject.cpp.
References m_goGroup, and GameObjectGroup::RemoveObject().
Referenced by RemoveFromWorld().
ClearSkillupList()
void GameObject::ClearSkillupList () inline
Definition at line 852 of file GameObject.h.
References m_SkillupSet.
Referenced by ClearAllUsesData().
Create()
bool GameObject::Create (uint32 dbGuid, uint32 guidlow, uint32 name_id, Map * map, uint32 phaseMask, float x, float y, float z, float ang, const QuaternionData & rotation = QuaternionData(), uint8 animprogress = GO_ANIMPROGRESS_DEFAULT, GOState go_state = GO_STATE_READY) virtual
Reimplemented in ElevatorTransport.
Definition at line 184 of file GameObject.cpp.
References Object::_Create(), VisibilityData::AddInvisibilityValue(), VisibilityData::AddStealthStrength(), GameObjectInfo::auraGenerator, GameObjectInfo::displayId, GameObjectInfo::door, GameObjectInfo::faction, GameObjectInfo::flags, ForceGameObjectHealth(), GAMEOBJECT_DYNAMIC, GAMEOBJECT_FACTION, GAMEOBJECT_FLAGS, GAMEOBJECT_LEVEL, GAMEOBJECT_TYPE_AURA_GENERATOR, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_TRANSPORT, GAMEOBJECT_TYPE_TRAP, ObjectMgr::GetGameObjectInfo(), GetGOInfo(), GetGoType(), Map::GetId(), Map::GetInstanceData(), GetMaxHealth(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), WorldObject::GetZoneId(), GO_ACTIVATED, GO_DYNFLAG_LO_ACTIVATE, GO_DYNFLAG_LO_SPARKLE, GO_FLAG_NODESPAWN, GO_FLAG_TRANSPORT, GO_NOT_READY, GO_STATE_ACTIVE, GO_STATE_READY, HIGHGUID_GAMEOBJECT, GameObjectInfo::id, INVISIBILITY_TRAP, Map::IsBattleGroundOrArena(), GameObjectInfo::IsLargeGameObject(), WorldObject::IsPositionValid(), Large, m_goInfo, m_lootState, m_stationaryPosition, Object::m_updateFlag, MANGOS_ASSERT, MAX_GAMEOBJECT_TYPE, WorldObject::Relocate(), SetDisplayId(), Object::SetEntry(), Object::SetFlag(), SetGoAnimProgress(), SetGoArtKit(), SetGoState(), SetGoType(), VisibilityData::SetInvisibilityMask(), SetLocalRotation(), WorldObject::SetMap(), Object::SetObjectScale(), SetPhaseMask(), VisibilityData::SetStealthMask(), WorldObject::SetStringId(), SetTransportPathRotation(), Object::SetUInt32Value(), VisibilityData::SetVisibilityDistanceOverride(), GameObjectInfo::size, sLog, sOutdoorPvPMgr, STEALTH_TRAP, GameObjectInfo::StringId, GameObjectInfo::transport, GameObjectInfo::trap, GameObjectInfo::type, UPDATEFLAG_POSITION, UPDATEFLAG_TRANSPORT, VISIBILITY_DISTANCE_LARGE, QuaternionData::w, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
Referenced by ElevatorTransport::Create(), Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), ChatHandler::HandleGameObjectAddCommand(), LoadFromDB(), and SummonLinkedTrapIfAny().
CreateGameObject()
GameObject * GameObject::CreateGameObject (uint32 entry) static
Definition at line 113 of file GameObject.cpp.
References GameObject(), GAMEOBJECT_TYPE_TRANSPORT, ObjectMgr::GetGameObjectInfo(), and GameObjectInfo::type.
Referenced by ChatHandler::HandleGameObjectAddCommand(), LoadHelper(), SpawnGameObjectInMapsWorker::operator()(), PoolGroup< T >::Spawn1Object(), and WorldObject::SpawnGameObject().
DealGameObjectDamage()
void GameObject::DealGameObjectDamage (uint32 damage, uint32 spell, Unit * caster)
Definition at line 2561 of file GameObject.cpp.
References ForceGameObjectHealth(), GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, Unit::GetBeneficiary(), GetGoType(), Object::GetPackGUID(), SQLStorage::LookupEntry(), MANGOS_ASSERT, WorldObject::SendMessageToSet(), SMSG_DESTRUCTIBLE_BUILDING_DAMAGE, and sSpellTemplate.
Referenced by Spell::EffectWMODamage().
Delete()
void GameObject::Delete ()
Definition at line 800 of file GameObject.cpp.
References WorldObject::AddObjectToRemoveList(), AI(), GAMEOBJECT_FLAGS, Object::GetDbGuid(), GetGOInfo(), GetLinkedTrap(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPersistentState(), GO_JUST_DEACTIVATED, GO_STATE_READY, GameObjectAI::JustDespawned(), WorldObject::SendObjectDeSpawnAnim(), SetGoState(), Object::SetUInt32Value(), and sPoolMgr.
Referenced by ChatHandler::HandleGameObjectDeleteCommand(), instance_halls_of_reflection::OnObjectCreate(), Unit::RemoveGameObject(), and Update().
DeleteFromDB()
void GameObject::DeleteFromDB () const
Definition at line 1008 of file GameObject.cpp.
References DEBUG_LOG, Object::GetDbGuid(), WorldObject::GetMapId(), HasStaticDBSpawnData(), Database::PExecuteLog(), sMapPersistentStateMgr, sObjectMgr, and WorldDatabase.
Referenced by ChatHandler::HandleGameObjectDeleteCommand().
ForcedDespawn()
void GameObject::ForcedDespawn (uint32 timeMSToDespawn = 0)
Definition at line 3068 of file GameObject.cpp.
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Object::GetDbGuid(), GO_JUST_DEACTIVATED, WorldObject::m_events, m_respawnDelay, m_respawnOverriden, SetForcedDespawn(), SetLootState(), SetRespawnDelay(), and sObjectMgr.
Referenced by Spell::EffectActivateObject(), ForcedDespawnDelayGameObjectEvent::Execute(), boss_coren_direbrewAI::JustSummoned(), DemonicCircleSummon::OnApply(), and SummonMoleMachine::OnSummon().
ForceGameObjectHealth()
void GameObject::ForceGameObjectHealth (int32 diff, Unit * caster) private
Definition at line 2588 of file GameObject.cpp.
References DestructibleModelDataEntry::damagedDisplayId, DEBUG_FILTER_LOG, DestructibleModelDataEntry::destroyedDisplayId, GameObjectInfo::destructibleBuilding, GameObjectInfo::displayId, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, Unit::GetBeneficiary(), GetDisplayId(), GetGoType(), Object::GetGuidStr(), WorldObject::GetMap(), GetMaxHealth(), GO_FLAG_DAMAGED, GO_FLAG_DESTROYED, Object::HasFlag(), LOG_FILTER_DAMAGE, m_goInfo, m_useTimes, MANGOS_ASSERT, Object::RemoveFlag(), sDestructibleModelDataStore, SetDisplayId(), Object::SetFlag(), SetGoAnimProgress(), and StartEvents_Event().
Referenced by Create(), DealGameObjectDamage(), RebuildGameObject(), and SetDestructibleState().
GenerateLootFor()
void GameObject::GenerateLootFor (Player * player)
Definition at line 3022 of file GameObject.cpp.
References LOOT_SKINNING, and Object::m_loot.
GetCapturePointSliderValue()
float GameObject::GetCapturePointSliderValue () const inline
Definition at line 918 of file GameObject.h.
References m_captureSlider.
Referenced by OutdoorPvP::HandleGameObjectRemove().
GetClosestChairSlotPosition()
std::pair< float, float > GameObject::GetClosestChairSlotPosition (Unit * user) const
Definition at line 2928 of file GameObject.cpp.
References GameObjectInfo::chair, DEFAULT_VISIBILITY_DISTANCE, DIST_CALC_NONE, WorldObject::GetDistance2d(), GetGOInfo(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), M_PI_F, GameObjectInfo::size, and GameObjectInfo::slots.
Referenced by WorldSession::HandleGameObjectUseOpcode(), and Use().
GetCollisionHeight()
float GameObject::GetCollisionHeight () const inline override virtual
Reimplemented from WorldObject.
Definition at line 921 of file GameObject.h.
GetDestructibleState()
GameObjectDestructibleState GameObject::GetDestructibleState () const
Definition at line 2707 of file GameObject.cpp.
References GAMEOBJECT_FLAGS, GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_INTACT, GO_FLAG_DAMAGED, GO_FLAG_DESTROYED, and Object::HasFlag().
GetDisplayId()
uint32 GameObject::GetDisplayId () const inline
Definition at line 838 of file GameObject.h.
References GAMEOBJECT_DISPLAYID, and Object::GetUInt32Value().
Referenced by GameObjectModel::construct(), ForceGameObjectHealth(), and GameObjectModel::Relocate().
GetFaction()
uint32 GameObject::GetFaction () const inline override virtual
Reimplemented from WorldObject.
Definition at line 841 of file GameObject.h.
References GAMEOBJECT_FACTION, and Object::GetUInt32Value().
GetGameObjectGroup()
GameObjectGroup* GameObject::GetGameObjectGroup () const inline
Definition at line 966 of file GameObject.h.
References m_goGroup.
Referenced by Update().
GetGoAnimProgress()
uint8 GameObject::GetGoAnimProgress () const inline
Definition at line 836 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by Update().
GetGoArtKit()
uint8 GameObject::GetGoArtKit () const inline
Definition at line 834 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
GetGOInfo()
GameObjectInfo const * GameObject::GetGOInfo () const
Definition at line 1048 of file GameObject.cpp.
References m_goInfo.
Referenced by PlayerbotAI::_HandleCommandSurvey(), _IsWithinDist(), ActivateToQuest(), AddToWorld(), go_aura_generator::CheckAndApplyAura(), Create(), ElevatorTransport::Create(), Delete(), PlayerbotAI::DoLoot(), Spell::EffectOpenLock(), GetClosestChairSlotPosition(), ScriptDevAIMgr::GetDialogStatus(), GetSpellForLock(), GetStationaryO(), GetStationaryX(), GetStationaryY(), GetStationaryZ(), GossipHello_go_icc_teleporter(), GossipHello_go_ulduar_teleporter(), ChatHandler::HandleGameObjectActivateCommand(), OutdoorPvP::HandleGameObjectCreate(), ChatHandler::HandleGameObjectMoveCommand(), OutdoorPvP::HandleGameObjectRemove(), ChatHandler::HandleGameObjectTurnCommand(), WorldSession::HandleGameObjectUseOpcode(), IsAtInteractDistance(), IsCollisionEnabled(), IsDynTransport(), IsMoTransport(), IsTransport(), isVisibleForInState(), go_bonfire::JustSpawned(), LoadFromDB(), Loot::Loot(), ScriptDevAIMgr::OnEffectDummy(), ScriptDevAIMgr::OnGameObjectUse(), ScriptDevAIMgr::OnGossipHello(), ScriptDevAIMgr::OnGossipSelect(), ScriptDevAIMgr::OnQuestAccept(), ScriptDevAIMgr::OnQuestRewarded(), ScriptDevAIMgr::OnTrapSearch(), MaNGOS::NearestGameObjectFishingHoleCheck::operator()(), MaNGOS::GameObjectFocusCheck::operator()(), Loot::Release(), RemoveFromWorld(), SaveToDB(), Loot::SendItem(), SetCapturePointSlider(), SetDestructibleState(), GenericTransport::SetGoState(), Transport::SpawnPassengers(), SummonLinkedTrapIfAny(), TickCapturePoint(), TriggerLinkedGameObject(), TriggerSummoningRitual(), Update(), ElevatorTransport::Update(), Transport::Update(), go_ai_suppression::UpdateAI(), go_ai_ectoplasmic_distiller_trap::UpdateAI(), Use(), and UseDoorOrButton().
GetGoState()
GOState GameObject::GetGoState () const inline
Definition at line 832 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by BattleGround::DoorClose(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleGameObjectTargetCommand(), LadyDeathwhisperElevator::HandleStateChange(), IsCollisionEnabled(), SwitchDoorOrButton(), instance_dire_maul::Update(), Update(), instance_violet_hold::UpdateCellForBoss(), and UseOpenableObject().
GetGoType()
GameobjectTypes GameObject::GetGoType () const inline
Definition at line 830 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::GetByteValue().
Referenced by _IsWithinDist(), ActivateToQuest(), PlayerbotAI::CastSpell(), Create(), DealGameObjectDamage(), PlayerbotAI::DoLoot(), Spell::EffectWMOChange(), Spell::EffectWMODamage(), Spell::EffectWMORepair(), ScriptAction::ExecuteDbscriptCommand(), ForceGameObjectHealth(), GetInteractionDistance(), GossipHello_go_large_jack_o_lantern(), GossipHello_go_manaforge(), GOUse_go_harbinger_second_trial(), BattlefieldWG::HandleEvent(), BattleGroundWS::HandleEvent(), BattlefieldWG::HandleGameObjectCreate(), ChatHandler::HandleGameObjectTargetCommand(), WorldSession::HandleGameObjectUseOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), BattleGround::HandleTriggerBuff(), IsAtInteractDistance(), IsCollisionEnabled(), FlagClickBg::OnEffectExecute(), instance_naxxramas::OnObjectCreate(), MaNGOS::GameObjectTypeInPosRangeCheck::operator()(), Player::PrepareGossipMenu(), RebuildGameObject(), Loot::Release(), Spell::SendLoot(), Player::SendQuestGiverStatusMultiple(), SetDestructibleState(), TriggerDelayedAction(), Update(), instance_violet_hold::UpdateCellForBoss(), and Use().
GetGridRef()
GridReference<GameObject>& GameObject::GetGridRef () inline
Definition at line 923 of file GameObject.h.
References m_gridRef.
GetGroupLootRecipient()
Group * GameObject::GetGroupLootRecipient () const
Definition at line 2222 of file GameObject.cpp.
References m_lootGroupRecipientId, and sObjectMgr.
Referenced by GetLootRecipient().
GetHealth()
uint32 GameObject::GetHealth () const inline
Definition at line 908 of file GameObject.h.
References m_useTimes.
Referenced by Spell::EffectWMODamage(), and SetDestructibleState().
GetInteractionDistance()
float GameObject::GetInteractionDistance () const
Definition at line 2716 of file GameObject.cpp.
References CONTACT_DISTANCE, GAMEOBJECT_TYPE_AREADAMAGE, GAMEOBJECT_TYPE_BARBER_CHAIR, GAMEOBJECT_TYPE_BINDER, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GUILD_BANK, GAMEOBJECT_TYPE_MAILBOX, GAMEOBJECT_TYPE_MAP_OBJECT, GAMEOBJECT_TYPE_MINI_GAME, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_TEXT, GetGoType(), and INTERACTION_DISTANCE.
Referenced by IsAtInteractDistance().
GetLevel()
uint32 GameObject::GetLevel () const inline override virtual
Reimplemented from WorldObject.
Definition at line 843 of file GameObject.h.
References GAMEOBJECT_LEVEL, and Object::GetUInt32Value().
GetLinkedTrap()
GameObject * GameObject::GetLinkedTrap ()
Definition at line 2279 of file GameObject.cpp.
References Map::GetGameObject(), WorldObject::GetMap(), and m_linkedTrap.
Referenced by Delete(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), and Update().
GetLocalRotation()
const QuaternionData GameObject::GetLocalRotation () const
Definition at line 3063 of file GameObject.cpp.
References m_localRotation.
Referenced by GetWorldRotation().
GetLootGroupRecipientId()
uint32 GameObject::GetLootGroupRecipientId () const inline
Definition at line 874 of file GameObject.h.
References m_lootGroupRecipientId.
GetLootRecipient()
Player * GameObject::GetLootRecipient () const
Definition at line 2228 of file GameObject.cpp.
References Group::GetFirstMember(), Player::GetGroup(), GetGroupLootRecipient(), GetOriginalLootRecipient(), and GroupReference::next().
GetLootRecipientGuid()
ObjectGuid GameObject::GetLootRecipientGuid () const inline
Definition at line 873 of file GameObject.h.
References m_lootRecipientGuid.
GetLootState()
LootState GameObject::GetLootState () const inline
Definition at line 847 of file GameObject.h.
References m_lootState.
Referenced by Object::BuildValuesUpdate(), BattleGround::ChangeBgObjectSpawnState(), BattleGround::DoorClose(), OutdoorPvP::HandleGameObjectRemove(), ChatHandler::HandleGameObjectTargetCommand(), Loot::Loot(), Spell::OnCheckTarget(), go_ai_larva_spewer::OnLootStateChange(), go_ai_suppression::OnLootStateChange(), DreadsteedQuestObjects::OnLootStateChange(), go_covertopsAI::OnLootStateChange(), KaliriNest::OnLootStateChange(), go_monstrous_kaliri_egg::OnLootStateChange(), go_unadorned_spike::OnLootStateChange(), MammothTrapBoreanAI::OnLootStateChange(), boss_zumrahAI::SelectNearbyShallowGrave(), go_ai_suppression::UpdateAI(), Use(), and UseOpenableObject().
GetMaxHealth()
uint32 GameObject::GetMaxHealth () const inline
Definition at line 909 of file GameObject.h.
References GameObjectInfo::destructibleBuilding, and m_goInfo.
Referenced by Create(), ForceGameObjectHealth(), and SetDestructibleState().
GetNameForLocaleIdx()
const char * GameObject::GetNameForLocaleIdx (int32 loc_idx) const override virtual
Reimplemented from WorldObject.
Definition at line 2052 of file GameObject.cpp.
References Object::GetEntry(), WorldObject::GetName(), GameObjectLocale::Name, and sObjectMgr.
GetOriginalLootRecipient()
Player * GameObject::GetOriginalLootRecipient () const
Definition at line 2217 of file GameObject.cpp.
References ObjectAccessor::FindPlayer(), and m_lootRecipientGuid.
Referenced by GetLootRecipient().
GetOwner()
Unit * GameObject::GetOwner () const
Definition at line 1031 of file GameObject.cpp.
References GetOwnerGuid(), and ObjectAccessor::GetUnit().
Referenced by CanAssistSpell(), CanAttackSpell(), GetReactionTo(), IsEnemy(), IsFriend(), isVisibleForInState(), Unit::SpellHitResult(), TriggerSummoningRitual(), Update(), Spell::UpdateOriginalCasterPointer(), and Use().
GetOwnerGuid()
ObjectGuid const& GameObject::GetOwnerGuid () const inline override virtual
Reimplemented from WorldObject.
Definition at line 781 of file GameObject.h.
References Object::GetGuidValue(), and OBJECT_FIELD_CREATED_BY.
Referenced by Unit::AddGameObject(), Unit::AddWildGameObject(), GetOwner(), ChatHandler::HandleGameObjectDeleteCommand(), Loot::Loot(), RemoveFromWorld(), Unit::RemoveGameObject(), SummonLinkedTrapIfAny(), and Use().
GetPackedLocalRotation()
int64 GameObject::GetPackedLocalRotation () const inline
Definition at line 769 of file GameObject.h.
References m_packedRotation.
GetParentHigh()
HighGuid GameObject::GetParentHigh () const inline override virtual
Reimplemented from WorldObject.
Definition at line 960 of file GameObject.h.
References HIGHGUID_GAMEOBJECT.
GetReactionTo()
ReputationRank GameObject::GetReactionTo (Unit const * unit) const override virtual
Get GO to unit reaction.
Note
Relations API Tier 1
Client-side counterpart: CGGameObject_C::ObjectReaction(const CGGameObject_C *this, const CGUnit_C *unit)
Reimplemented from WorldObject.
Definition at line 299 of file Relations.cpp.
References GAMEOBJECT_FACTION, GetFactionReaction(), GetOwner(), Object::GetUInt32Value(), MANGOS_ASSERT, REP_NEUTRAL, and sFactionTemplateStore.
Referenced by Unit::CanInteract().
GetRespawnDelay()
uint32 GameObject::GetRespawnDelay () const inline
Definition at line 820 of file GameObject.h.
References m_respawnDelay.
Referenced by ChatHandler::HandleGameObjectTargetCommand(), and Update().
GetRespawnTime()
time_t GameObject::GetRespawnTime () const inline
Definition at line 798 of file GameObject.h.
References m_respawnTime.
Referenced by EffectDummyGameObj_spell_dummy_go(), and npc_razorthorn_ravager_pet::HandleAnimations().
GetRespawnTimeEx()
time_t GameObject::GetRespawnTimeEx () const inline
Definition at line 799 of file GameObject.h.
References m_respawnTime.
Referenced by ChatHandler::HandleGameObjectTargetCommand().
GetScriptId()
uint32 GameObject::GetScriptId () const
Definition at line 2818 of file GameObject.cpp.
References Object::GetEntry(), ObjectMgr::GetGameObjectInfo(), and GameObjectInfo::ScriptId.
Referenced by ScriptDevAIMgr::GetGameObjectAI().
GetSpawner()
WorldObject * GameObject::GetSpawner () const
Definition at line 1036 of file GameObject.cpp.
References Map::GetGameObject(), WorldObject::GetMap(), GetSpawnerGuid(), Map::GetUnit(), ObjectGuid::IsGameObject(), and Object::IsInWorld().
Referenced by GOUse_go_omen_cluster(), and FlagClickBg::OnEffectExecute().
GetSpawnerGuid()
ObjectGuid const GameObject::GetSpawnerGuid () const inline virtual
Reimplemented from WorldObject.
Definition at line 783 of file GameObject.h.
References m_spawnerGuid.
Referenced by GetSpawner(), and go_imp_in_a_ball::JustSpawned().
GetSpellForLock()
SpellEntry const * GameObject::GetSpellForLock (Player const * player) const
Definition at line 2892 of file GameObject.cpp.
References WorldObject::CalculateSpellEffectValue(), GetGOInfo(), GameObjectInfo::GetLockId(), Player::GetSpellMap(), LockEntry::Index, LOCK_KEY_SKILL, LOCK_KEY_SPELL, SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, MAX_LOCK_CASE, LockEntry::Skill, sLockStore, SPELL_EFFECT_OPEN_LOCK, sSpellTemplate, and LockEntry::Type.
Referenced by IsAtInteractDistance().
GetSpellId()
uint32 GameObject::GetSpellId () const inline
Definition at line 794 of file GameObject.h.
References m_spellId.
Referenced by Unit::AddGameObject(), Unit::AddWildGameObject(), Unit::RemoveGameObject(), SummonLinkedTrapIfAny(), Update(), and Use().
GetStationaryO()
float GameObject::GetStationaryO () const inline
Definition at line 945 of file GameObject.h.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), WorldObject::GetOrientation(), Position::GetPositionO(), and m_stationaryPosition.
Referenced by Object::BuildMovementUpdate().
GetStationaryX()
float GameObject::GetStationaryX () const inline
Definition at line 942 of file GameObject.h.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionX(), and m_stationaryPosition.
Referenced by Object::BuildMovementUpdate().
GetStationaryY()
float GameObject::GetStationaryY () const inline
Definition at line 943 of file GameObject.h.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionY(), and m_stationaryPosition.
Referenced by Object::BuildMovementUpdate().
GetStationaryZ()
float GameObject::GetStationaryZ () const inline
Definition at line 944 of file GameObject.h.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), Position::GetPositionZ(), and m_stationaryPosition.
Referenced by Object::BuildMovementUpdate().
GetTemplateAddon()
GameObjectTemplateAddon const * GameObject::GetTemplateAddon () const
Definition at line 1053 of file GameObject.cpp.
References Object::GetEntry(), and sObjectMgr.
Referenced by Spell::EffectActivateObject().
GetUniqueUseCount()
uint32 GameObject::GetUniqueUseCount () const inline
Definition at line 868 of file GameObject.h.
References m_UniqueUsers.
Referenced by Use().
GetUseCount()
uint32 GameObject::GetUseCount () const inline
Definition at line 867 of file GameObject.h.
References m_useTimes.
Referenced by Loot::Release(), and Use().
GetWorldRotation()
QuaternionData GameObject::GetWorldRotation () const
Definition at line 3046 of file GameObject.cpp.
References GetLocalRotation(), WorldObject::GetTransport(), QuaternionData::w, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
Referenced by IsAtInteractDistance().
HasInvolvedQuest()
bool GameObject::HasInvolvedQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1072 of file GameObject.cpp.
References Object::GetEntry(), and sObjectMgr.
HasLootRecipient()
bool GameObject::HasLootRecipient () const inline
Definition at line 877 of file GameObject.h.
References ObjectGuid::IsEmpty(), m_lootGroupRecipientId, and m_lootRecipientGuid.
HasQuest()
bool GameObject::HasQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1061 of file GameObject.cpp.
References Object::GetEntry(), and sObjectMgr.
HasStaticDBSpawnData()
bool GameObject::HasStaticDBSpawnData () const
Definition at line 2344 of file GameObject.cpp.
References Object::GetDbGuid(), and sObjectMgr.
Referenced by DeleteFromDB(), and Update().
Heartbeat()
void GameObject::Heartbeat () override virtual
Reimplemented from WorldObject.
Definition at line 771 of file GameObject.cpp.
References AI(), and GameObjectAI::OnHeartbeat().
IsAtInteractDistance() [1/2]
bool GameObject::IsAtInteractDistance (Player const * player, uint32 maxRange = 0) const
Definition at line 2834 of file GameObject.cpp.
References DIST_CALC_NONE, GAMEOBJECT_TYPE_SPELL_FOCUS, WorldObject::GetDistance(), GetGOInfo(), GetGoType(), GetInteractionDistance(), WorldObject::GetPosition(), GetSpellForLock(), GetSpellMaxRange(), IsAtInteractDistance(), SpellEntry::rangeIndex, sGameObjectDisplayInfoStore, and sSpellRangeStore.
IsAtInteractDistance() [2/2]
bool GameObject::IsAtInteractDistance (Position const & pos, float radius, bool is3D = true) const
Definition at line 2868 of file GameObject.cpp.
References DIST_CALC_NONE, WorldObject::GetDistance(), Object::GetObjectScale(), Position::GetPositionX(), WorldObject::GetPositionX(), Position::GetPositionY(), WorldObject::GetPositionY(), Position::GetPositionZ(), WorldObject::GetPositionZ(), GetWorldRotation(), m_displayInfo, QuaternionData::w, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
Referenced by _IsWithinDist(), WorldSession::HandleGameObjectUseOpcode(), IsAtInteractDistance(), Loot::Loot(), and MaNGOS::GameObjectTypeInPosRangeCheck::operator()().
IsCollisionEnabled()
bool GameObject::IsCollisionEnabled () const
Definition at line 1363 of file GameObject.cpp.
References GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_TRAP, GetGOInfo(), GetGoState(), GetGoType(), GO_STATE_READY, and IsSpawned().
Referenced by ChatHandler::HandleGameObjectTargetCommand(), and UpdateCollisionState().
IsDynTransport()
bool GameObject::IsDynTransport () const
Definition at line 1092 of file GameObject.cpp.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_TRANSPORT, GetGOInfo(), GameObjectInfo::transport, and GameObjectInfo::type.
IsEnemy()
bool GameObject::IsEnemy (Unit const * unit) const override virtual
[Serverside] Reaction preset: GO sees a unit as an enemy
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Some gameobjects can be involved in spell casting, so server needs additional API support.
Reimplemented from WorldObject.
Definition at line 920 of file Relations.cpp.
References GAMEOBJECT_FACTION, GetFactionReaction(), GetOwner(), Object::GetUInt32Value(), MANGOS_ASSERT, REP_UNFRIENDLY, and sFactionTemplateStore.
Referenced by CanAssistSpell(), and CanAttackSpell().
IsFriend()
bool GameObject::IsFriend (Unit const * unit) const override virtual
[Serverside] Reaction preset: GO sees a unit as a friend
Note
Relations API Tier 2
This function is not intented to have client-side counterpart by original design. Some gameobjects can be involved in spell casting, so server needs additional API support.
Reimplemented from WorldObject.
Definition at line 944 of file Relations.cpp.
References GAMEOBJECT_FACTION, GetFactionReaction(), GetOwner(), Object::GetUInt32Value(), MANGOS_ASSERT, REP_NEUTRAL, and sFactionTemplateStore.
Referenced by CanAssistSpell(), CanAttackSpell(), and isVisibleForInState().
IsGroupLootRecipient()
bool GameObject::IsGroupLootRecipient () const inline
Definition at line 878 of file GameObject.h.
References m_lootGroupRecipientId.
IsInSkillupList()
bool GameObject::IsInSkillupList (Player * player) const
Definition at line 2284 of file GameObject.cpp.
References Object::GetObjectGuid(), and m_SkillupSet.
Referenced by Spell::EffectOpenLock().
IsInUse()
bool GameObject::IsInUse () const inline
Definition at line 864 of file GameObject.h.
References m_isInUse.
IsMoTransport()
bool GameObject::IsMoTransport () const
Definition at line 1100 of file GameObject.cpp.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GetGOInfo(), and GameObjectInfo::type.
Referenced by isVisibleForInState(), and UpdateVisibilityOf_helper().
IsSpawned()
bool GameObject::IsSpawned () const inline
Definition at line 813 of file GameObject.h.
References m_respawnDelay, m_respawnTime, and m_spawnedByDefault.
Referenced by PlayerbotAI::_HandleCommandSurvey(), AddToWorld(), PlayerbotAI::DoLoot(), dummy_dragonAI::DoOpenPortal(), Spell::EffectDummy(), EffectDummyCreature_npc_shadowmoon_tuber_node(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyGO(), ChatHandler::HandleGameObjectRespawnCommand(), WorldSession::HandleGameObjectUseOpcode(), BattleGround::HandleTriggerBuff(), IsCollisionEnabled(), isVisibleForInState(), Loot::Loot(), MaNGOS::NearestGameObjectFishingHoleCheck::operator()(), MaNGOS::AllGameObjectEntriesListInPosRangeCheck::operator()(), MaNGOS::GameObjectFocusCheck::operator()(), Refresh(), boss_zumrahAI::SelectNearbyShallowGrave(), Update(), go_infernaling_summoner_portal_hound::UpdateAI(), go_ai_lightning::UpdateAI(), go_smoke_beacon::UpdateAI(), go_infernaling_summoner::UpdateAI(), go_elemental_rift::UpdateAI(), and go_ai_fixed_trap::UpdateAI().
IsSpawnedByDefault()
bool GameObject::IsSpawnedByDefault () const inline
Definition at line 819 of file GameObject.h.
References m_spawnedByDefault.
Referenced by BattleGround::ChangeBgObjectSpawnState(), ScriptAction::ExecuteDbscriptCommand(), Map::LoadTransports(), and Update().
IsTransport()
bool GameObject::IsTransport () const
Definition at line 1083 of file GameObject.cpp.
References GAMEOBJECT_TYPE_MO_TRANSPORT, GAMEOBJECT_TYPE_TRANSPORT, GetGOInfo(), and GameObjectInfo::type.
Referenced by spell_split_teleport_boat::OnEffectExecute(), and NamreebAnticheat::Movement::OnTransport().
isVisibleForInState()
bool GameObject::isVisibleForInState (Player const * u, WorldObject const * viewPoint, bool inVisibleList) const override virtual
Implements WorldObject.
Definition at line 1113 of file GameObject.cpp.
References VisibilityData::CanDetectInvisibilityOf(), DIST_CALC_NONE, GAMEOBJECT_TYPE_TRAP, Player::GetBGTeam(), WorldObject::GetDistance(), GetGOInfo(), VisibilityData::GetInvisibilityMask(), WorldObject::GetMap(), GetOwner(), VisibilityData::GetStealthMask(), VisibilityData::GetStealthVisibilityDistance(), WorldObject::GetVisibilityData(), WorldObject::HasInArc(), GameObjectInfo::invisible, IsFriend(), Player::IsGameMaster(), Player::IsInDuelWith(), Player::IsInGroup(), WorldObject::IsInMap(), Object::IsInWorld(), IsMoTransport(), IsSpawned(), WorldObject::IsWithinDistInMap(), GameObjectInfo::stealthed, GameObjectInfo::type, and TYPEID_PLAYER.
LoadFromDB()
bool GameObject::LoadFromDB (uint32 dbGuid, Map * map, uint32 newGuid, uint32 forcedEntry, GenericTransport * transport = nullptr)
Definition at line 887 of file GameObject.cpp.
References Map::Add(), GenericTransport::AddPassenger(), AIM_Initialize(), GameObjectData::animprogress, GenericTransport::CalculatePassengerPosition(), Create(), GameObjectInfo::ExtraFlags, GAMEOBJECT_EXTRA_FLAG_DYNGUID, GAMEOBJECT_FLAGS, Map::GenerateLocalLowGuid(), Object::GetDbGuid(), Map::GetGameObject(), ObjectMgr::GetGameObjectInfo(), GetGOInfo(), MapPersistentState::GetGORespawnTime(), SpawnGroup::GetGuidEntry(), Map::GetMapDataContainer(), Map::GetPersistentState(), GameObjectData::GetRandomRespawnTime(), SpawnManager::GetSpawnGroup(), MapDataContainer::GetSpawnGroupByGuid(), Map::GetSpawnManager(), GO_FLAG_NODESPAWN, GO_STATE_READY, GameObjectData::goState, HIGHGUID_GAMEOBJECT, GameObjectData::id, SpawnGroupEntry::Id, Map::IsDynguidForced(), WorldObject::m_movementInfo, m_respawnDelay, m_respawnTime, m_spawnedByDefault, GameObjectData::orientation, GameObjectData::path_rotation, GameObjectData::phaseMask, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, GameObjectData::rotation, MapPersistentState::SaveGORespawnTime(), Object::SetFlag(), SetGameObjectGroup(), SetGoState(), WorldObject::SetStringId(), SetTransportPathRotation(), MovementInfo::SetTransportPos(), sLog, sObjectMgr, GameObjectData::spawntimesecsmin, SpawnGroupEntry::StringId, and TYPEID_GAMEOBJECT.
Referenced by ChatHandler::HandleGameObjectAddCommand(), SpawnGameObjectInMapsWorker::operator()(), PoolGroup< T >::Spawn1Object(), and WorldObject::SpawnGameObject().
LookupFishingHoleAround()
GameObject * GameObject::LookupFishingHoleAround (float range) const
Definition at line 1352 of file GameObject.cpp.
References Cell::VisitGridObjects().
Referenced by Use().
OnEventHappened()
void GameObject::OnEventHappened (uint16 eventId, bool activate, bool resume) inline override virtual
Reimplemented from WorldObject.
Definition at line 927 of file GameObject.h.
References AI(), and GameObjectAI::OnEventHappened().
RebuildGameObject()
void GameObject::RebuildGameObject (Unit * caster)
Definition at line 2580 of file GameObject.cpp.
References ForceGameObjectHealth(), GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetGoType(), and MANGOS_ASSERT.
Referenced by Spell::EffectWMORepair().
Refresh()
void GameObject::Refresh ()
Definition at line 777 of file GameObject.cpp.
References Map::Add(), AIM_Initialize(), WorldObject::GetMap(), IsSpawned(), m_respawnTime, and m_spawnedByDefault.
Referenced by BattleGround::ChangeBgObjectSpawnState(), dummy_dragonAI::DoOpenPortal(), boss_razorscaleAI::DoRepairHarpoon(), Spell::EffectDummy(), Spell::EffectScriptEffect(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleGameObjectMoveCommand(), OutdoorPvP::SetBannerVisual(), and instance_sethekk_halls::StartAnzuIntro().
RemoveFromWorld()
void GameObject::RemoveFromWorld () override virtual
Remove the gameobject from the accessor
Reimplemented from WorldObject.
Definition at line 150 of file GameObject.cpp.
References ClearGameObjectGroup(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase(), Object::GetDbGuid(), GetGOInfo(), Object::GetGuidStr(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetObjectsStore(), GetOwnerGuid(), ObjectAccessor::GetUnit(), WorldObject::GetZoneId(), Object::IsInWorld(), m_model, m_spellId, Map::RemoveDbGuidObject(), WorldObject::RemoveFromWorld(), Map::RemoveGameObjectModel(), sLog, and sOutdoorPvPMgr.
RemoveModelFromMap()
void GameObject::RemoveModelFromMap ()
Definition at line 2195 of file GameObject.cpp.
References WorldObject::GetMap(), m_model, and Map::RemoveGameObjectModel().
Referenced by Transport::TeleportTransport().
ResetDoorOrButton()
void GameObject::ResetDoorOrButton (Unit * user = nullptr)
Definition at line 1384 of file GameObject.cpp.
References GO_JUST_DEACTIVATED, GO_READY, m_cooldownTime, m_lootState, SetLootState(), and SwitchDoorOrButton().
Referenced by Spell::EffectActivateObject(), ScriptAction::ExecuteDbscriptCommand(), Update(), instance_violet_hold::UpdateCellForBoss(), and UseOpenableObject().
Respawn()
void GameObject::Respawn ()
Definition at line 1206 of file GameObject.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Map::GetPersistentState(), m_respawnTime, m_spawnedByDefault, and MapPersistentState::SaveGORespawnTime().
Referenced by BattleGround::ChangeBgObjectSpawnState(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleGameObjectRespawnCommand(), instance_blood_furnace::OnObjectCreate(), MaNGOS::RespawnDo::operator()(), and instance_blood_furnace::SetData().
SaveRespawnTime()
void GameObject::SaveRespawnTime () override virtual
Reimplemented from WorldObject.
Definition at line 1107 of file GameObject.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Map::GetPersistentState(), m_respawnTime, m_spawnedByDefault, and MapPersistentState::SaveGORespawnTime().
Referenced by PoolGroup< T >::Spawn1Object(), and Update().
SaveToDB() [1/2]
void GameObject::SaveToDB () const
Definition at line 822 of file GameObject.cpp.
References Object::GetDbGuid(), WorldObject::GetMapId(), GameObjectData::phaseMask, sLog, sObjectMgr, and GameObjectData::spawnMask.
Referenced by ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectMoveCommand(), ChatHandler::HandleGameObjectPhaseCommand(), and ChatHandler::HandleGameObjectTurnCommand().
SaveToDB() [2/2]
void GameObject::SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask) const
Definition at line 836 of file GameObject.cpp.
References Database::BeginTransaction(), Database::CommitTransaction(), Object::GetEntry(), GetGOInfo(), Object::GetGUIDLow(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GameObjectData::id, m_localRotation, m_respawnDelay, m_spawnedByDefault, GameObjectData::mapid, GameObjectData::orientation, Database::PExecuteLog(), GameObjectData::phaseMask, GameObjectData::posX, GameObjectData::posY, GameObjectData::posZ, GameObjectData::rotation, sObjectMgr, GameObjectData::spawnMask, GameObjectData::spawntimesecsmax, GameObjectData::spawntimesecsmin, QuaternionData::w, WorldDatabase, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
SetActionTarget()
void GameObject::SetActionTarget (ObjectGuid guid) inline
Definition at line 861 of file GameObject.h.
References m_actionTarget.
Referenced by Spell::EffectTransmitted().
SetCapturePointSlider()
void GameObject::SetCapturePointSlider (float value, bool isLocked)
Definition at line 2349 of file GameObject.cpp.
References CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, CAPTURE_SLIDER_MIDDLE, CAPTURE_STATE_NEUTRAL, CAPTURE_STATE_PROGRESS_ALLIANCE, CAPTURE_STATE_PROGRESS_HORDE, CAPTURE_STATE_WIN_ALLIANCE, CAPTURE_STATE_WIN_HORDE, GameObjectInfo::capturePoint, GetGOInfo(), GO_ACTIVATED, m_captureSlider, m_captureState, and SetLootState().
Referenced by OutdoorPvP::HandleGameObjectCreate(), and BattleGroundEY::HandleGameObjectCreate().
SetCooldown()
void GameObject::SetCooldown (uint32 cooldown)
Definition at line 3028 of file GameObject.cpp.
References m_cooldownTime.
Referenced by instance_sunwell_plateau::OnObjectCreate().
SetDestructibleState()
void GameObject::SetDestructibleState (GameObjectDestructibleState state, Unit * attackerOrHealer = nullptr, bool setHealth = false)
Definition at line 2685 of file GameObject.cpp.
References GameObjectInfo::damagedNumHits, ForceGameObjectHealth(), GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetGOInfo(), GetGoType(), GetHealth(), GetMaxHealth(), GO_DESTRUCTIBLE_DAMAGED, GO_DESTRUCTIBLE_DESTROYED, GO_DESTRUCTIBLE_INTACT, GO_DESTRUCTIBLE_REBUILDING, and MANGOS_ASSERT.
Referenced by Spell::EffectWMOChange().
SetDisplayId()
void GameObject::SetDisplayId (uint32 modelId)
Definition at line 2151 of file GameObject.cpp.
References GAMEOBJECT_DISPLAYID, m_displayInfo, Object::SetUInt32Value(), sGameObjectDisplayInfoStore, and UpdateModel().
Referenced by Create(), Transport::Create(), ForceGameObjectHealth(), and instance_trial_of_the_crusader::OnObjectCreate().
SetFaction()
void GameObject::SetFaction (uint32 faction) inline
Definition at line 842 of file GameObject.h.
References GAMEOBJECT_FACTION, and Object::SetUInt32Value().
Referenced by BattlefieldWG::HandleDestructibleBuildingEvent(), BattleGroundSA::HandleEvent(), and BattlefieldWG::HandleGameObjectCreate().
SetForcedDespawn()
void GameObject::SetForcedDespawn () inline
Definition at line 822 of file GameObject.h.
References m_forcedDespawn.
Referenced by BattleGround::ChangeBgObjectSpawnState(), ForcedDespawn(), ChatHandler::HandleGameObjectForcedDespawnCommand(), KaliriNest::OnLootStateChange(), and go_monstrous_kaliri_egg::OnLootStateChange().
SetGameObjectGroup()
void GameObject::SetGameObjectGroup (GameObjectGroup * group)
Definition at line 3033 of file GameObject.cpp.
References SpawnGroup::AddObject(), Object::GetDbGuid(), Object::GetEntry(), and m_goGroup.
Referenced by LoadFromDB().
SetGoAnimProgress()
void GameObject::SetGoAnimProgress (uint8 animprogress) inline
Definition at line 837 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::SetByteValue().
Referenced by Create(), Transport::Create(), and ForceGameObjectHealth().
SetGoArtKit()
void GameObject::SetGoArtKit (uint8 artkit) inline
Definition at line 835 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::SetByteValue().
Referenced by Create(), Transport::Create(), Spell::EffectActivateObject(), go_bonfire::go_bonfire(), BattlefieldWG::HandleGameObjectCreate(), OutdoorPvPGH::HandleGameObjectCreate(), OutdoorPvPHP::HandleGameObjectCreate(), OutdoorPvPNA::HandleGameObjectCreate(), OutdoorPvPTF::HandleGameObjectCreate(), OutdoorPvPEP::InitBanner(), and OutdoorPvP::SetBannerVisual().
SetGoState()
void GameObject::SetGoState (GOState state) virtual
Reimplemented in ElevatorTransport, and GenericTransport.
Definition at line 2143 of file GameObject.cpp.
References AI(), GAMEOBJECT_BYTES_1, GameObjectAI::OnGoStateChange(), Object::SetByteValue(), and UpdateCollisionState().
Referenced by Create(), Delete(), Spell::EffectTransmitted(), instance_serpentshrine_cavern::EngageBossConsole(), GOUse_go_mausoleum_trigger(), LadyDeathwhisperElevator::HandleStateChange(), LoadFromDB(), instance_shadowfang_keep::OnObjectCreate(), instance_stratholme::OnObjectCreate(), instance_black_temple::OnObjectCreate(), instance_blood_furnace::OnObjectCreate(), instance_blackrock_depths::OnObjectCreate(), instance_blackrock_spire::OnObjectCreate(), instance_blackwing_lair::OnObjectCreate(), instance_deadmines::OnObjectCreate(), instance_karazhan::OnObjectCreate(), instance_magisters_terrace::OnObjectCreate(), instance_scholomance::OnObjectCreate(), instance_sunken_temple::OnObjectCreate(), instance_sunwell_plateau::OnObjectCreate(), instance_uldaman::OnObjectCreate(), instance_zulaman::OnObjectCreate(), instance_blackfathom_deeps::OnObjectCreate(), instance_culling_of_stratholme::OnObjectCreate(), instance_dire_maul::OnObjectCreate(), instance_razorfen_kraul::OnObjectCreate(), instance_temple_of_ahnqiraj::OnObjectCreate(), instance_zulfarrak::OnObjectCreate(), instance_ahnkahet::OnObjectCreate(), instance_azjol_nerub::OnObjectCreate(), instance_trial_of_the_crusader::OnObjectCreate(), instance_gundrak::OnObjectCreate(), instance_halls_of_reflection::OnObjectCreate(), instance_pit_of_saron::OnObjectCreate(), instance_icecrown_citadel::OnObjectCreate(), instance_naxxramas::OnObjectCreate(), instance_oculus::OnObjectCreate(), instance_ruby_sanctum::OnObjectCreate(), instance_halls_of_lightning::OnObjectCreate(), instance_ulduar::OnObjectCreate(), instance_utgarde_keep::OnObjectCreate(), instance_pinnacle::OnObjectCreate(), instance_sethekk_halls::OnObjectCreate(), instance_shadow_labyrinth::OnObjectCreate(), instance_steam_vault::OnObjectCreate(), instance_gruuls_lair::OnObjectCreate(), instance_shattered_halls::OnObjectCreate(), instance_arcatraz::OnObjectCreate(), instance_the_eye::OnObjectCreate(), instance_mechanar::OnObjectCreate(), instance_icecrown_citadel::OnObjectSpawn(), GenericTransport::SetGoState(), SetInUse(), SwitchDoorOrButton(), Update(), Transport::Update(), and Use().
SetGoType()
void GameObject::SetGoType (GameobjectTypes type) inline
Definition at line 831 of file GameObject.h.
References GAMEOBJECT_BYTES_1, and Object::SetByteValue().
Referenced by Create(), and Transport::Create().
SetInUse()
void GameObject::SetInUse (bool use)
Definition at line 2754 of file GameObject.cpp.
References GO_STATE_ACTIVE, GO_STATE_READY, m_isInUse, and SetGoState().
SetLinkedTrap()
void GameObject::SetLinkedTrap (GameObject * linkedTrap) inline
Definition at line 901 of file GameObject.h.
References Object::GetObjectGuid(), and m_linkedTrap.
Referenced by AddToWorld().
SetLocalRotation()
void GameObject::SetLocalRotation (float qx, float qy, float qz, float qw)
Definition at line 2104 of file GameObject.cpp.
References WorldObject::GetOrientation(), m_localRotation, m_packedRotation, QuaternionCompressed::m_raw, QuaternionData::w, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
Referenced by Create(), SetLocalRotationAngles(), and ElevatorTransport::Update().
SetLocalRotationAngles()
void GameObject::SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
Definition at line 2127 of file GameObject.cpp.
References SetLocalRotation().
Referenced by ChatHandler::HandleGameObjectTurnCommand().
SetLootRecipient()
void GameObject::SetLootRecipient (Unit * pUnit)
Definition at line 2254 of file GameObject.cpp.
References ObjectGuid::Clear(), Unit::GetBeneficiaryPlayer(), Player::GetGroup(), Object::GetObjectGuid(), m_lootGroupRecipientId, and m_lootRecipientGuid.
Referenced by Update().
SetLootState()
void GameObject::SetLootState (LootState state, Unit * user = nullptr)
Definition at line 2133 of file GameObject.cpp.
References m_AI, m_lootState, and UpdateCollisionState().
Referenced by BattleGround::ChangeBgObjectSpawnState(), BattleGround::DoorClose(), BattleGround::DoorOpen(), Spell::EffectActivateObject(), Spell::EffectDummy(), EffectDummyCreature_npc_harpoon_fire_state(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectScriptEffect(), ScriptAction::ExecuteDbscriptCommand(), instance_sethekk_halls::FinishAnzuIntro(), ForcedDespawn(), GOUse_go_mysterious_snow_mound(), BattleGroundWS::HandleEvent(), ChatHandler::HandleGameObjectActivateCommand(), BattlefieldWG::HandleGameObjectCreate(), ChatHandler::HandleGameObjectForcedDespawnCommand(), OutdoorPvPSI::HandleGameObjectUse(), BattleGroundEY::HandlePlayerClickedOnFlag(), BattleGround::HandleTriggerBuff(), Loot::Loot(), instance_maraudon::OnObjectCreate(), instance_blackwing_lair::OnObjectCreate(), instance_molten_core::OnObjectCreate(), Loot::Release(), ResetDoorOrButton(), Loot::SendItem(), Spell::SendLoot(), SetCapturePointSlider(), instance_dire_maul::SetData(), instance_sethekk_halls::StartAnzuIntro(), TriggerSummoningRitual(), Update(), go_ai_fixed_trap::UpdateAI(), Use(), and UseDoorOrButton().
SetOwnerGuid()
void GameObject::SetOwnerGuid (ObjectGuid guid) override virtual
Reimplemented from WorldObject.
Definition at line 1025 of file GameObject.cpp.
References m_spawnedByDefault, OBJECT_FIELD_CREATED_BY, and Object::SetGuidValue().
Referenced by Unit::AddGameObject(), Spell::EffectTransmitted(), Unit::RemoveGameObject(), SummonLinkedTrapIfAny(), and Use().
SetPhaseMask()
void GameObject::SetPhaseMask (uint32 newPhaseMask, bool update) virtual
Reimplemented from WorldObject.
Definition at line 2158 of file GameObject.cpp.
References WorldObject::SetPhaseMask(), and UpdateCollisionState().
Referenced by Create(), and ChatHandler::HandleGameObjectPhaseCommand().
SetRespawnDelay()
void GameObject::SetRespawnDelay (uint32 delay, bool once = false) inline
Definition at line 821 of file GameObject.h.
References m_respawnDelay, m_respawnOverriden, and m_respawnOverrideOnce.
Referenced by BattleGround::ChangeBgObjectSpawnState(), ForcedDespawn(), ChatHandler::HandleGameObjectForcedDespawnCommand(), DreadsteedQuestObjects::JustSpawned(), and KaliriNest::OnLootStateChange().
SetRespawnTime()
void GameObject::SetRespawnTime (time_t respawn) inline
Definition at line 807 of file GameObject.h.
References m_respawnDelay, and m_respawnTime.
Referenced by BattleGround::ChangeBgObjectSpawnState(), dummy_dragonAI::DoOpenPortal(), boss_razorscaleAI::DoRepairHarpoon(), Spell::EffectDuel(), Spell::EffectDummy(), Spell::EffectScriptEffect(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), ScriptAction::ExecuteDbscriptCommand(), instance_sethekk_halls::FinishAnzuIntro(), GOUse_go_strange_pool(), ChatHandler::HandleGameObjectAddCommand(), ChatHandler::HandleGameObjectDeleteCommand(), OutdoorPvPEP::HandleGameObjectUse(), OutdoorPvPNA::HandleGameObjectUse(), go_ai_suppression::OnLootStateChange(), instance_blood_furnace::OnObjectCreate(), Unit::RemoveGameObject(), instance_blood_furnace::SetData(), PoolGroup< T >::Spawn1Object(), and instance_sethekk_halls::StartAnzuIntro().
SetSpawnerGuid()
void GameObject::SetSpawnerGuid (ObjectGuid guid) inline
Definition at line 784 of file GameObject.h.
References m_spawnerGuid.
Referenced by Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), and Spell::EffectTransmitted().
SetSpellId()
void GameObject::SetSpellId (uint32 id) inline
Definition at line 789 of file GameObject.h.
References m_spawnedByDefault, and m_spellId.
Referenced by Spell::EffectDuel(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectTransmitted(), and SummonLinkedTrapIfAny().
SetTransportPathRotation()
void GameObject::SetTransportPathRotation (const QuaternionData & rotation)
Definition at line 2119 of file GameObject.cpp.
References GAMEOBJECT_PARENTROTATION, Object::SetFloatValue(), QuaternionData::w, QuaternionData::x, QuaternionData::y, and QuaternionData::z.
Referenced by Create(), and LoadFromDB().
SpawnInMaps()
void GameObject::SpawnInMaps (uint32 db_guid, GameObjectData const * data) static
Definition at line 2338 of file GameObject.cpp.
References GameObjectData::mapid, and sMapMgr.
Referenced by GameEventMgr::GameEventSpawn().
SummonLinkedTrapIfAny()
GameObject * GameObject::SummonLinkedTrapIfAny () const
Definition at line 1290 of file GameObject.cpp.
References Map::Add(), AIM_Initialize(), Create(), GameObject(), GAMEOBJECT_LEVEL, Map::GenerateLocalLowGuid(), GetGOInfo(), GameObjectInfo::GetLinkedGameObjectEntry(), WorldObject::GetMap(), WorldObject::GetOrientation(), GetOwnerGuid(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellId(), Object::GetUInt32Value(), HIGHGUID_GAMEOBJECT, m_respawnDelay, SetOwnerGuid(), SetSpellId(), and Object::SetUInt32Value().
Referenced by AddToWorld().
SwitchDoorOrButton()
void GameObject::SwitchDoorOrButton (bool activate, bool alternative = false) private
Definition at line 1432 of file GameObject.cpp.
References GAMEOBJECT_FLAGS, GetGoState(), GO_FLAG_IN_USE, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, Object::RemoveFlag(), Object::SetFlag(), and SetGoState().
Referenced by ResetDoorOrButton(), and UseDoorOrButton().
TickCapturePoint()
void GameObject::TickCapturePoint () private
Definition at line 2372 of file GameObject.cpp.
References ALLIANCE, GridRefManager< OBJECT >::begin(), CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, CAPTURE_SLIDER_MIDDLE, CAPTURE_STATE_CONTEST_ALLIANCE, CAPTURE_STATE_CONTEST_HORDE, CAPTURE_STATE_NEUTRAL, CAPTURE_STATE_PROGRESS_ALLIANCE, CAPTURE_STATE_PROGRESS_HORDE, CAPTURE_STATE_WIN_ALLIANCE, CAPTURE_STATE_WIN_HORDE, GameObjectInfo::capturePoint, GetGOInfo(), WorldObject::GetMap(), HORDE, m_captureSlider, m_captureState, m_UniqueUsers, WorldObject::SetActiveObjectState(), sOutdoorPvPMgr, StartEvents_Event(), Cell::VisitWorldObjects(), WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
Referenced by Update().
TriggerDelayedAction()
void GameObject::TriggerDelayedAction () protected
Definition at line 2806 of file GameObject.cpp.
References GAMEOBJECT_TYPE_SUMMONING_RITUAL, GetGoType(), and TriggerSummoningRitual().
Referenced by Update().
TriggerLinkedGameObject()
void GameObject::TriggerLinkedGameObject (Unit * target) const
Definition at line 1320 of file GameObject.cpp.
References GAMEOBJECT_TYPE_TRAP, GetGOInfo(), GameObjectInfo::GetLinkedGameObjectEntry(), SQLHashStorage::LookupEntry(), sGOStorage, GameObjectInfo::type, Use(), and Cell::VisitGridObjects().
Referenced by Use().
TriggerSummoningRitual()
void GameObject::TriggerSummoningRitual () protected
Definition at line 2763 of file GameObject.cpp.
References Unit::CastSpell(), ClearAllUsesData(), CURRENT_CHANNELED_SPELL, Unit::FinishSpell(), GetGOInfo(), WorldObject::GetMap(), Object::GetObjectGuid(), GetOwner(), GO_JUST_DEACTIVATED, m_actionTarget, m_firstUser, m_UniqueUsers, SetLootState(), sObjectMgr, GameObjectInfo::summoningRitual, TRIGGERED_INSTANT_CAST, and TRIGGERED_OLD_TRIGGERED.
Referenced by TriggerDelayedAction(), and Use().
Update()
void GameObject::Update (const uint32 diff) override virtual
Reimplemented from WorldObject.
Reimplemented in Transport, and ElevatorTransport.
Definition at line 309 of file GameObject.cpp.
References Map::Add(), SpawnManager::AddGameObject(), WorldObject::AddObjectToRemoveList(), AI(), AIM_Initialize(), GameObjectInfo::charges, GameObjectInfo::chest, ClearAllUsesData(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, CURRENT_CHANNELED_SPELL, Delete(), GameObjectInfo::diameter, Unit::FinishSpell(), FISHING_BOBBER_READY_TIME, Object::ForceValuesUpdateAtIndex(), function, GAMEOBJECT_DYNAMIC, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CAPTURE_POINT, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_TRAP, GameObjectInfo::GetCharges(), Object::GetDbGuid(), EventProcessor::GetEvents(), GetGameObjectGroup(), GetGoAnimProgress(), GetGOInfo(), GetGoState(), GetGoType(), GetLinkedTrap(), GameObjectInfo::GetLockId(), WorldObject::GetMap(), Object::GetObjectGuid(), GetOwner(), Map::GetPersistentState(), GetRespawnDelay(), Map::GetSpawnManager(), GetSpellId(), Object::GetTypeId(), Object::GetUInt32Value(), GO_ACTIVATED, GO_FLAG_IN_USE, GO_FLAG_INTERACT_COND, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_JUST_DEACTIVATED, GO_NOT_READY, GO_READY, GO_STATE_ACTIVE, GO_STATE_ACTIVE_ALTERNATIVE, GO_STATE_READY, Object::HasFlag(), HasStaticDBSpawnData(), Loot::IsChanged(), Unit::IsInCombat(), Object::IsInWorld(), IsSpawned(), IsSpawnedByDefault(), WorldObject::IsUsingNewSpawningSystem(), GameObjectAI::JustDespawned(), m_AI, m_captureTimer, m_cooldownTime, m_delayedActionTimer, m_despawnTimer, WorldObject::m_events, m_forcedDespawn, m_goInfo, Object::m_loot, m_lootState, m_rearmTimer, m_respawnDelay, m_respawnOverriden, m_respawnOverrideOnce, m_respawnTime, m_reStockTimer, m_spawnedByDefault, m_UniqueUsers, m_useTimes, MINUTE, GameObjectInfo::radius, Object::RemoveFlag(), ResetDoorOrButton(), SaveRespawnTime(), Object::SendForcedObjectUpdate(), WorldObject::SendGameObjectCustomAnim(), WorldObject::SendObjectDeSpawnAnim(), SetGoState(), SetLootRecipient(), SetLootState(), Object::SetUInt32Value(), SMSG_FISH_NOT_HOOKED, sObjectMgr, GameObjectInfo::spellId, sPoolMgr, sScriptDevAIMgr, sWorld, sWorldState, TickCapturePoint(), GameObjectInfo::trap, GameObjectInfo::trapCustom, TriggerDelayedAction(), TRIGGERED_NONE, GameObjectInfo::type, TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, Loot::Update(), WorldObject::Update(), EventProcessor::Update(), WorldObject::UpdateObjectVisibility(), Use(), Cell::VisitAllObjects(), WORLD_STATE_REMOVE, and GameObjectInfo::worldState1.
UpdateCollisionState()
void GameObject::UpdateCollisionState () const private
Definition at line 2164 of file GameObject.cpp.
References GameObjectModel::enable(), WorldObject::GetPhaseMask(), IsCollisionEnabled(), Object::IsInWorld(), and m_model.
Referenced by AddToWorld(), SetGoState(), SetLootState(), and SetPhaseMask().
UpdateModel()
void GameObject::UpdateModel () private
Definition at line 2172 of file GameObject.cpp.
References GameObjectModel::construct(), WorldObject::GetMap(), Map::InsertGameObjectModel(), Object::IsInWorld(), m_model, and Map::RemoveGameObjectModel().
Referenced by SetDisplayId().
UpdateModelPosition()
void GameObject::UpdateModelPosition ()
Definition at line 2204 of file GameObject.cpp.
References WorldObject::GetMap(), Map::InsertGameObjectModel(), m_model, GameObjectModel::Relocate(), and Map::RemoveGameObjectModel().
Referenced by Map::GameObjectRelocation(), Transport::TeleportTransport(), and GenericTransport::UpdatePosition().
Use()
void GameObject::Use (Unit * user, SpellEntry const * spellInfo = nullptr)
Definition at line 1445 of file GameObject.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_FISH_IN_GAMEOBJECT, AddUniqueUse(), AddUse(), AI(), GameObjectInfo::barberChair, GameObjectInfo::camera, Player::CanUseBattleGroundObject(), CastSpell(), Unit::CastSpell(), GameObjectInfo::chair, CONFIG_BOOL_SKILL_FAIL_LOOT_FISHING, CONFIG_BOOL_SKILL_FAIL_POSSIBLE_FISHINGPOOL, CONTACT_DISTANCE, CURRENT_CHANNELED_SPELL, DEBUG_FILTER_LOG, DEBUG_LOG, GameObjectInfo::eventId, GameObjectInfo::ExtraFlags, ObjectAccessor::FindPlayer(), Unit::FinishSpell(), GameObjectInfo::flagdrop, GameObjectInfo::flagstand, function, GAMEOBJECT_EXTRA_FLAG_CUSTOM_ANIM_ON_USE, GAMEOBJECT_FLAGS, GAMEOBJECT_TYPE_BARBER_CHAIR, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CAMERA, GAMEOBJECT_TYPE_CHAIR, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_FLAGDROP, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GENERIC, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_MEETINGSTONE, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_SPELLCASTER, GAMEOBJECT_TYPE_SUMMONING_RITUAL, GAMEOBJECT_TYPE_TRAP, GameObjectInfo::GetAutoCloseTime(), Player::GetBattleGround(), GetClosestChairSlotPosition(), GameObjectInfo::GetCooldown(), Unit::GetCurrentSpell(), Object::GetDbGuid(), Object::GetEntry(), GetGOInfo(), GetGoType(), Player::GetGroup(), Object::GetGuidStr(), Unit::GetLevel(), GetLootState(), WorldObject::GetMap(), WorldObject::GetMapId(), Object::GetObjectGuid(), WorldObject::GetOrientation(), GetOwner(), GetOwnerGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetQuestStatus(), Player::GetSelectionGuid(), Player::GetSession(), Player::GetSkillValue(), GetSpellId(), Object::GetTypeId(), GetUniqueUseCount(), GetUseCount(), WorldObject::GetZoneAndAreaId(), GO_ACTIVATED, GO_FLAG_IN_USE, GO_FLAG_LOCKED, GO_JUST_DEACTIVATED, GO_READY, GO_STATE_ACTIVE, GameObjectInfo::goober, GameObjectInfo::id, irand(), Map::IsBattleGround(), Unit::IsInGroup(), Player::IsInGroup(), Object::IsPlayer(), GameObjectInfo::IsUsableMounted(), GameObjectInfo::lockId, LOG_FILTER_AI_AND_MOVEGENSS, SQLStorage::LookupEntry(), LookupFishingHoleAround(), LOOT_FISHING, LOOT_FISHING_FAIL, LOOT_FISHINGHOLE, m_cooldownTime, m_delayedActionTimer, m_firstUser, m_goInfo, Object::m_loot, m_respawnTime, MANGOS_ASSERT, GameObjectInfo::meetingstone, Unit::NearTeleportTo(), GameObjectInfo::noDamageImmune, GameObjectAI::OnUse(), Player::PrepareGossipMenu(), Object::PrintEntryError(), QUEST_STATUS_INCOMPLETE, GameObjectInfo::questgiver, Unit::RemoveGameObject(), Unit::RemoveSpellsCausingAura(), Player::RewardPlayerAndGroupAtCast(), SCRIPT_TYPE_GAMEOBJECT, SCRIPT_TYPE_GAMEOBJECT_TEMPLATE, Map::ScriptsStart(), Player::SendCinematicStart(), WorldObject::SendGameObjectCustomAnim(), WorldSession::SendPacket(), Player::SendPreparedGossip(), Object::SetFlag(), SetGoState(), SetLootState(), SetOwnerGuid(), Unit::SetStandState(), Object::SetUInt32Value(), SpellCastTargets::setUnitTarget(), Loot::ShowContentTo(), SKILL_FISHING, sLog, SMSG_ENABLE_BARBER_SHOP, SMSG_FISH_ESCAPED, SMSG_FISH_NOT_HOOKED, SMSG_GAMEOBJECT_PAGETEXT, sObjectMgr, SPELL_AURA_MOUNTED, SPELL_CAST_OK, GameObjectInfo::spellcaster, Spell::SpellStart(), sScriptDevAIMgr, sSpellTemplate, StartEvents_Event(), GameObjectInfo::summoningRitual, GameObjectInfo::summoningRitualCustom, sWorld, sWorldState, TELE_TO_NOT_LEAVE_COMBAT, TELE_TO_NOT_LEAVE_TRANSPORT, TELE_TO_NOT_UNSUMMON_PET, Player::TeleportTo(), GameObjectInfo::trap, TRIGGERED_CHANNEL_ONLY, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TriggerLinkedGameObject(), TriggerSummoningRitual(), TYPEID_PLAYER, UNIT_STAND_STATE_SIT_LOW_CHAIR, Player::UpdateAchievementCriteria(), Player::UpdateFishingSkill(), Use(), and UseDoorOrButton().
Referenced by Spell::EffectActivateObject(), ScriptAction::ExecuteDbscriptCommand(), WorldSession::HandleGameObjectUseOpcode(), boss_coren_direbrewAI::JustSummoned(), npc_razorscale_spawnerAI::JustSummoned(), SummonMoleMachine::OnSummon(), Spell::SendLoot(), TriggerLinkedGameObject(), Update(), go_screaming_hall_door::UpdateAI(), go_containment::UpdateAI(), go_ai_fixed_trap::UpdateAI(), and Use().
UseDoorOrButton()
void GameObject::UseDoorOrButton (uint32 time_to_restore = 0, bool alternative = false)
Definition at line 1418 of file GameObject.cpp.
References GameObjectInfo::GetAutoCloseTime(), GetGOInfo(), GO_ACTIVATED, GO_READY, m_cooldownTime, m_lootState, SetLootState(), and SwitchDoorOrButton().
Referenced by BattleGround::DoorClose(), BattleGround::DoorOpen(), Spell::EffectActivateObject(), GOUse_go_gundrak_altar(), ChatHandler::HandleGameObjectActivateCommand(), instance_molten_core::OnObjectCreate(), Loot::Release(), Use(), UseOpenableObject(), and npc_galen_goodwardAI::WaypointStart().
UseOpenableObject()
void GameObject::UseOpenableObject (bool open, uint32 withRestoreTime = 0, bool useAlternativeState = false)
Definition at line 1394 of file GameObject.cpp.
References GetGoState(), GetLootState(), GO_READY, GO_STATE_ACTIVE, GO_STATE_READY, ResetDoorOrButton(), and UseDoorOrButton().
Referenced by ScriptAction::ExecuteDbscriptCommand().
Field Documentation
m_actionTarget
ObjectGuid GameObject::m_actionTarget protected
Definition at line 1016 of file GameObject.h.
Referenced by SetActionTarget(), and TriggerSummoningRitual().
m_AI
std::unique_ptr<GameObjectAI> GameObject::m_AI protected
Definition at line 1020 of file GameObject.h.
Referenced by AI(), AIM_Initialize(), SetLootState(), and Update().
m_captureSlider
float GameObject::m_captureSlider protected
Definition at line 981 of file GameObject.h.
Referenced by GetCapturePointSliderValue(), SetCapturePointSlider(), and TickCapturePoint().
m_captureState
CapturePointState GameObject::m_captureState protected
Definition at line 982 of file GameObject.h.
Referenced by SetCapturePointSlider(), and TickCapturePoint().
m_captureTimer
uint32 GameObject::m_captureTimer protected
Definition at line 980 of file GameObject.h.
Referenced by GameObject(), and Update().
m_cooldownTime
time_t GameObject::m_cooldownTime protected
Definition at line 977 of file GameObject.h.
Referenced by GameObject(), ResetDoorOrButton(), SetCooldown(), Update(), Use(), and UseDoorOrButton().
m_delayedActionTimer
uint32 GameObject::m_delayedActionTimer protected
Definition at line 1014 of file GameObject.h.
Referenced by GameObject(), Update(), and Use().
m_despawnTimer
time_t GameObject::m_despawnTimer protected
Definition at line 1009 of file GameObject.h.
Referenced by GameObject(), and Update().
m_displayInfo
GameObjectDisplayInfoEntry const* GameObject::m_displayInfo protected
Definition at line 993 of file GameObject.h.
Referenced by IsAtInteractDistance(), and SetDisplayId().
m_firstUser
ObjectGuid GameObject::m_firstUser protected
Definition at line 989 of file GameObject.h.
Referenced by AddUniqueUse(), ClearAllUsesData(), TriggerSummoningRitual(), and Use().
m_forcedDespawn
bool GameObject::m_forcedDespawn protected
Definition at line 974 of file GameObject.h.
Referenced by GameObject(), SetForcedDespawn(), and Update().
m_goGroup
GameObjectGroup* GameObject::m_goGroup protected
Definition at line 1024 of file GameObject.h.
Referenced by ClearGameObjectGroup(), GameObject(), GetGameObjectGroup(), and SetGameObjectGroup().
m_goInfo
GameObjectInfo const* GameObject::m_goInfo protected
Definition at line 992 of file GameObject.h.
Referenced by Transport::CalculateSegmentPos(), Create(), Transport::Create(), ForceGameObjectHealth(), GetGOInfo(), GetMaxHealth(), Update(), and Use().
m_gridRef
GridReference<GameObject> GameObject::m_gridRef private
Definition at line 1033 of file GameObject.h.
Referenced by GetGridRef().
m_isInUse
bool GameObject::m_isInUse protected
Definition at line 1007 of file GameObject.h.
Referenced by GameObject(), IsInUse(), and SetInUse().
m_linkedTrap
ObjectGuid GameObject::m_linkedTrap protected
Definition at line 1018 of file GameObject.h.
Referenced by GetLinkedTrap(), and SetLinkedTrap().
m_localRotation
QuaternionData GameObject::m_localRotation protected
Definition at line 995 of file GameObject.h.
Referenced by GetLocalRotation(), SaveToDB(), and SetLocalRotation().
m_lootGroupRecipientId
uint32 GameObject::m_lootGroupRecipientId protected
Definition at line 1001 of file GameObject.h.
Referenced by GameObject(), GetGroupLootRecipient(), GetLootGroupRecipientId(), HasLootRecipient(), IsGroupLootRecipient(), and SetLootRecipient().
m_lootRecipientGuid
ObjectGuid GameObject::m_lootRecipientGuid protected
Definition at line 1000 of file GameObject.h.
Referenced by GetLootRecipientGuid(), GetOriginalLootRecipient(), HasLootRecipient(), and SetLootRecipient().
m_lootState
LootState GameObject::m_lootState protected
Definition at line 975 of file GameObject.h.
Referenced by Create(), GameObject(), GetLootState(), ResetDoorOrButton(), SetLootState(), Update(), and UseDoorOrButton().
m_model
GameObjectModel* GameObject::m_model
Definition at line 930 of file GameObject.h.
Referenced by AddModelToMap(), AddToWorld(), RemoveFromWorld(), RemoveModelFromMap(), UpdateCollisionState(), UpdateModel(), UpdateModelPosition(), and ~GameObject().
m_packedRotation
int64 GameObject::m_packedRotation protected
Definition at line 994 of file GameObject.h.
Referenced by GameObject(), GetPackedLocalRotation(), and SetLocalRotation().
m_rearmTimer
time_t GameObject::m_rearmTimer protected
Definition at line 1004 of file GameObject.h.
Referenced by GameObject(), and Update().
m_respawnDelay
uint32 GameObject::m_respawnDelay protected
Definition at line 971 of file GameObject.h.
Referenced by ForcedDespawn(), GameObject(), GetRespawnDelay(), IsSpawned(), LoadFromDB(), SaveToDB(), SetRespawnDelay(), SetRespawnTime(), SummonLinkedTrapIfAny(), and Update().
m_respawnOverriden
bool GameObject::m_respawnOverriden protected
Definition at line 972 of file GameObject.h.
Referenced by ForcedDespawn(), GameObject(), SetRespawnDelay(), and Update().
m_respawnOverrideOnce
bool GameObject::m_respawnOverrideOnce protected
Definition at line 973 of file GameObject.h.
Referenced by GameObject(), SetRespawnDelay(), and Update().
m_respawnTime
time_t GameObject::m_respawnTime protected
Definition at line 970 of file GameObject.h.
Referenced by GameObject(), GetRespawnTime(), GetRespawnTimeEx(), IsSpawned(), LoadFromDB(), Refresh(), Respawn(), SaveRespawnTime(), SetRespawnTime(), Update(), and Use().
m_reStockTimer
time_t GameObject::m_reStockTimer protected
Definition at line 1008 of file GameObject.h.
Referenced by GameObject(), and Update().
m_SkillupSet
GuidSet GameObject::m_SkillupSet protected
Definition at line 984 of file GameObject.h.
Referenced by AddToSkillupList(), ClearSkillupList(), and IsInSkillupList().
m_spawnedByDefault
bool GameObject::m_spawnedByDefault protected
Definition at line 976 of file GameObject.h.
Referenced by GameObject(), IsSpawned(), IsSpawnedByDefault(), LoadFromDB(), Refresh(), Respawn(), SaveRespawnTime(), SaveToDB(), SetOwnerGuid(), SetSpellId(), and Update().
m_spawnerGuid
ObjectGuid GameObject::m_spawnerGuid protected
Definition at line 1022 of file GameObject.h.
Referenced by GetSpawnerGuid(), and SetSpawnerGuid().
m_spellId
uint32 GameObject::m_spellId protected
Definition at line 969 of file GameObject.h.
Referenced by GameObject(), GetSpellId(), RemoveFromWorld(), and SetSpellId().
m_stationaryPosition
Position GameObject::m_stationaryPosition protected
Definition at line 997 of file GameObject.h.
Referenced by Create(), GetStationaryO(), GetStationaryX(), GetStationaryY(), GetStationaryZ(), and ElevatorTransport::Update().
m_UniqueUsers
GuidSet GameObject::m_UniqueUsers protected
Definition at line 990 of file GameObject.h.
Referenced by AddUniqueUse(), ClearAllUsesData(), GetUniqueUseCount(), TickCapturePoint(), TriggerSummoningRitual(), and Update().
m_useTimes
uint32 GameObject::m_useTimes protected
Definition at line 986 of file GameObject.h.
Referenced by AddUse(), ClearAllUsesData(), ForceGameObjectHealth(), GameObject(), GetHealth(), GetUseCount(), and Update().
The documentation for this class was generated from the following files:
GameObject.h
GameObject.cpp
Relations.cpp