CMaNGOS_WoTLK: SQLMultiStorage::SQLMultiSIterator< T > Class Template Reference
SQLMultiStorage::SQLMultiSIterator< T > Class Template Reference
#include <SQLStorage.h>
Public Member Functions
T const * getValue () const
uint32 getKey () const
void operator++ ()
T const * operator* () const
T const * operator-> () const
bool operator!= (const SQLMultiSIterator &r) const
bool operator== (const SQLMultiSIterator &r) const
Private Member Functions
SQLMultiSIterator (RecordMultiMap::const_iterator _itr)
Private Attributes
RecordMultiMap::const_iterator citerator
Friends
class SQLMultiStorage
class SQLMSIteratorBounds< T >
Detailed Description
template<typename T>
class SQLMultiStorage::SQLMultiSIterator< T >
Definition at line 194 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLMultiSIterator()
template<typename T > SQLMultiStorage::SQLMultiSIterator< T >::SQLMultiSIterator (RecordMultiMap::const_iterator _itr) inline private
Definition at line 210 of file SQLStorage.h.
Member Function Documentation
getKey()
template<typename T > uint32 SQLMultiStorage::SQLMultiSIterator< T >::getKey () const inline
Definition at line 201 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::citerator.
getValue()
template<typename T > T const* SQLMultiStorage::SQLMultiSIterator< T >::getValue () const inline
Definition at line 200 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::citerator.
Referenced by SQLMultiStorage::SQLMultiSIterator< T >::operator*(), and SQLMultiStorage::SQLMultiSIterator< T >::operator->().
operator!=()
template<typename T > bool SQLMultiStorage::SQLMultiSIterator< T >::operator!= (const SQLMultiSIterator< T > & r) const inline
Definition at line 206 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::citerator.
operator*()
template<typename T > T const* SQLMultiStorage::SQLMultiSIterator< T >::operator* () const inline
Definition at line 204 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::getValue().
operator++()
template<typename T > void SQLMultiStorage::SQLMultiSIterator< T >::operator++ () inline
Definition at line 203 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::citerator.
operator->()
template<typename T > T const* SQLMultiStorage::SQLMultiSIterator< T >::operator-> () const inline
Definition at line 205 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::getValue().
operator==()
template<typename T > bool SQLMultiStorage::SQLMultiSIterator< T >::operator== (const SQLMultiSIterator< T > & r) const inline
Definition at line 207 of file SQLStorage.h.
References SQLMultiStorage::SQLMultiSIterator< T >::citerator.
Friends And Related Function Documentation
SQLMSIteratorBounds< T >
template<typename T > friend class SQLMSIteratorBounds< T > friend
Definition at line 196 of file SQLStorage.h.
SQLMultiStorage
template<typename T > friend class SQLMultiStorage friend
Definition at line 196 of file SQLStorage.h.
Field Documentation
citerator
template<typename T > RecordMultiMap::const_iterator SQLMultiStorage::SQLMultiSIterator< T >::citerator private
Definition at line 211 of file SQLStorage.h.
Referenced by SQLMultiStorage::SQLMultiSIterator< T >::getKey(), SQLMultiStorage::SQLMultiSIterator< T >::getValue(), SQLMultiStorage::SQLMultiSIterator< T >::operator!=(), SQLMultiStorage::SQLMultiSIterator< T >::operator++(), and SQLMultiStorage::SQLMultiSIterator< T >::operator==().
The documentation for this class was generated from the following file:
SQLStorage.h