CMaNGOS_WoTLK: MySqlPreparedStatement Class Reference
MySqlPreparedStatement Class Reference
#include <DatabaseMysql.h>
Public Member Functions
MySqlPreparedStatement (const std::string &fmt, SqlConnection &conn, MYSQL *mysql)
~MySqlPreparedStatement ()
virtual bool prepare () override
virtual void bind (const SqlStmtParameters &holder) override
virtual bool execute () override
Public Member Functions inherited from SqlPreparedStatement
virtual ~SqlPreparedStatement ()
bool isPrepared () const
bool isQuery () const
uint32 params () const
uint32 columns () const
Protected Member Functions
void addParam (unsigned int nIndex, const SqlStmtFieldData &data)
Protected Member Functions inherited from SqlPreparedStatement
SqlPreparedStatement (const std::string &fmt, SqlConnection &conn)
Static Protected Member Functions
static enum_field_types ToMySQLType (const SqlStmtFieldData &data, bool &bUnsigned)
Private Member Functions
void RemoveBinds ()
Private Attributes
MYSQL * m_pMySQLConn
MYSQL_STMT * m_stmt
MYSQL_BIND * m_pInputArgs
MYSQL_BIND * m_pResult
MYSQL_RES * m_pResultMetadata
Additional Inherited Members
Protected Attributes inherited from SqlPreparedStatement
uint32 m_nParams
uint32 m_nColumns
bool m_bIsQuery
bool m_bPrepared
std::string m_szFmt
SqlConnection & m_pConn
Detailed Description
Definition at line 31 of file DatabaseMysql.h.
Constructor & Destructor Documentation
MySqlPreparedStatement()
MySqlPreparedStatement::MySqlPreparedStatement (const std::string & fmt, SqlConnection & conn, MYSQL * mysql)
Definition at line 306 of file DatabaseMysql.cpp.
~MySqlPreparedStatement()
MySqlPreparedStatement::~MySqlPreparedStatement ()
Definition at line 311 of file DatabaseMysql.cpp.
References RemoveBinds().
Member Function Documentation
addParam()
void MySqlPreparedStatement::addParam (unsigned int nIndex, const SqlStmtFieldData & data) protected
Definition at line 412 of file DatabaseMysql.cpp.
References SqlStmtFieldData::buff(), FIELD_STRING, SqlPreparedStatement::m_nParams, m_pInputArgs, MANGOS_ASSERT, SqlStmtFieldData::size(), ToMySQLType(), and SqlStmtFieldData::type().
Referenced by bind().
bind()
void MySqlPreparedStatement::bind (const SqlStmtParameters & holder) override virtual
Implements SqlPreparedStatement.
Definition at line 375 of file DatabaseMysql.cpp.
References addParam(), SqlStmtParameters::boundParams(), SqlPreparedStatement::isPrepared(), SqlPreparedStatement::m_nParams, m_pInputArgs, m_stmt, MANGOS_ASSERT, SqlStmtParameters::params(), and sLog.
execute()
bool MySqlPreparedStatement::execute () override virtual
Implements SqlPreparedStatement.
Definition at line 449 of file DatabaseMysql.cpp.
References SqlPreparedStatement::isPrepared(), m_stmt, SqlPreparedStatement::m_szFmt, and sLog.
prepare()
bool MySqlPreparedStatement::prepare () override virtual
Implements SqlPreparedStatement.
Definition at line 316 of file DatabaseMysql.cpp.
References SqlPreparedStatement::isPrepared(), SqlPreparedStatement::m_bIsQuery, SqlPreparedStatement::m_bPrepared, SqlPreparedStatement::m_nColumns, SqlPreparedStatement::m_nParams, m_pInputArgs, m_pMySQLConn, m_pResultMetadata, m_stmt, SqlPreparedStatement::m_szFmt, RemoveBinds(), and sLog.
RemoveBinds()
void MySqlPreparedStatement::RemoveBinds () private
Definition at line 430 of file DatabaseMysql.cpp.
References SqlPreparedStatement::m_bPrepared, m_pInputArgs, m_pResult, m_pResultMetadata, and m_stmt.
Referenced by prepare(), and ~MySqlPreparedStatement().
ToMySQLType()
enum_field_types MySqlPreparedStatement::ToMySQLType (const SqlStmtFieldData & data, bool & bUnsigned) static protected
Definition at line 464 of file DatabaseMysql.cpp.
References FIELD_BOOL, FIELD_DOUBLE, FIELD_FLOAT, FIELD_I16, FIELD_I32, FIELD_I64, FIELD_I8, FIELD_NONE, FIELD_STRING, FIELD_UI16, FIELD_UI32, FIELD_UI64, FIELD_UI8, and SqlStmtFieldData::type().
Referenced by addParam().
Field Documentation
m_pInputArgs
MYSQL_BIND* MySqlPreparedStatement::m_pInputArgs private
Definition at line 57 of file DatabaseMysql.h.
Referenced by addParam(), bind(), prepare(), and RemoveBinds().
m_pMySQLConn
MYSQL* MySqlPreparedStatement::m_pMySQLConn private
Definition at line 55 of file DatabaseMysql.h.
Referenced by prepare().
m_pResult
MYSQL_BIND* MySqlPreparedStatement::m_pResult private
Definition at line 58 of file DatabaseMysql.h.
Referenced by RemoveBinds().
m_pResultMetadata
MYSQL_RES* MySqlPreparedStatement::m_pResultMetadata private
Definition at line 59 of file DatabaseMysql.h.
Referenced by prepare(), and RemoveBinds().
m_stmt
MYSQL_STMT* MySqlPreparedStatement::m_stmt private
Definition at line 56 of file DatabaseMysql.h.
Referenced by bind(), execute(), prepare(), and RemoveBinds().
The documentation for this class was generated from the following files:
DatabaseMysql.h
DatabaseMysql.cpp