CMaNGOS_WoTLK: Quest Class Reference
Quest Class Reference
#include <QuestDef.h>
Public Types
typedef std::vector< int32 > PrevQuests
typedef std::vector< uint32 > PrevChainQuests
Public Member Functions
Quest (Field *questRecord)
uint32 GetXPReward (Player *pPlayer) const
uint32 GetQuestFlags () const
bool HasQuestFlag (QuestFlags flag) const
bool HasSpecialFlag (QuestSpecialFlags flag) const
void SetSpecialFlag (QuestSpecialFlags flag)
uint32 GetQuestId () const
uint32 GetQuestMethod () const
int32 GetZoneOrSort () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
int32 GetQuestLevel () const
uint32 GetType () const
uint32 GetRequiredClasses () const
uint32 GetRequiredRaces () const
uint32 GetRequiredSkill () const
uint32 GetRequiredSkillValue () const
uint32 GetRequiredCondition () const
uint32 GetRepObjectiveFaction () const
int32 GetRepObjectiveValue () const
uint32 GetRequiredMinRepFaction () const
int32 GetRequiredMinRepValue () const
uint32 GetRequiredMaxRepFaction () const
int32 GetRequiredMaxRepValue () const
uint32 GetSuggestedPlayers () const
uint32 GetLimitTime () const
int32 GetPrevQuestId () const
int32 GetNextQuestId () const
int32 GetExclusiveGroup () const
uint32 GetBreadcrumbForQuestId () const
uint32 GetNextQuestInChain () const
uint32 GetRewXPId () const
uint32 GetCharTitleId () const
uint32 GetPlayersSlain () const
uint32 GetBonusTalents () const
uint32 GetSrcItemId () const
uint32 GetSrcItemCount () const
uint32 GetSrcSpell () const
std::string GetTitle () const
std::string GetDetails () const
std::string GetObjectives () const
std::string GetOfferRewardText () const
std::string GetRequestItemsText () const
std::string GetEndText () const
std::string GetCompletedText () const
int32 GetRewOrReqMoney () const
uint32 GetRewHonorAddition () const
float GetRewHonorMultiplier () const
uint32 GetRewMoneyMaxLevel () const
uint32 GetRewSpell () const
uint32 GetRewSpellCast () const
uint32 GetRewMailTemplateId () const
uint32 GetRewMailDelaySecs () const
uint32 GetPointMapId () const
float GetPointX () const
float GetPointY () const
uint32 GetPointOpt () const
uint32 GetIncompleteEmote () const
uint32 GetIncompleteEmoteDelay () const
uint32 GetCompleteEmote () const
uint32 GetCompleteEmoteDelay () const
uint32 GetDetailsEmoteCount () const
uint32 GetQuestStartScript () const
uint32 GetQuestCompleteScript () const
bool IsRepeatable () const
bool IsAutoComplete () const
bool IsDaily () const
bool IsWeekly () const
bool IsMonthly () const
bool IsSeasonal () const
bool IsDailyOrWeekly () const
bool IsAutoAccept () const
bool IsAllowedInRaid () const
bool IsRaidQuest (Difficulty difficulty) const
bool IsDungeonFinderQuest () const
void SetQuestActiveState (bool state)
bool IsActive () const
bool CanIncreaseRewardedQuestCounters () const
uint32 CalculateRewardHonor (uint32 level) const
uint32 GetReqItemsCount () const
uint32 GetReqCreatureOrGOcount () const
uint32 GetRewChoiceItemsCount () const
uint32 GetRewItemsCount () const
Data Fields
std::string ObjectiveText [QUEST_OBJECTIVES_COUNT]
uint32 ReqItemId [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 ReqItemCount [QUEST_ITEM_OBJECTIVES_COUNT]
uint32 ReqSourceId [QUEST_SOURCE_ITEM_IDS_COUNT]
uint32 ReqSourceCount [QUEST_SOURCE_ITEM_IDS_COUNT]
int32 ReqCreatureOrGOId [QUEST_OBJECTIVES_COUNT]
uint32 ReqCreatureOrGOCount [QUEST_OBJECTIVES_COUNT]
uint32 ReqSpell [QUEST_OBJECTIVES_COUNT]
uint32 RewChoiceItemId [QUEST_REWARD_CHOICES_COUNT]
uint32 RewChoiceItemCount [QUEST_REWARD_CHOICES_COUNT]
uint32 RewItemId [QUEST_REWARDS_COUNT]
uint32 RewItemCount [QUEST_REWARDS_COUNT]
uint32 RewRepFaction [QUEST_REPUTATIONS_COUNT]
int32 RewRepValueId [QUEST_REPUTATIONS_COUNT]
int32 RewRepValue [QUEST_REPUTATIONS_COUNT]
int32 RewMaxRepValue [QUEST_REPUTATIONS_COUNT]
uint32 DetailsEmote [QUEST_EMOTE_COUNT]
uint32 DetailsEmoteDelay [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmote [QUEST_EMOTE_COUNT]
uint32 OfferRewardEmoteDelay [QUEST_EMOTE_COUNT]
PrevQuests prevQuests
PrevChainQuests prevChainQuests
std::vector< uint32 > DependentBreadcrumbQuests
Protected Attributes
uint32 QuestId
uint32 QuestMethod
int32 ZoneOrSort
uint32 MinLevel
uint32 MaxLevel
int32 QuestLevel
uint32 Type
uint32 RequiredClasses
uint32 RequiredRaces
uint32 RequiredSkill
uint32 RequiredSkillValue
uint32 RequiredCondition
uint32 RepObjectiveFaction
int32 RepObjectiveValue
uint32 RequiredMinRepFaction
int32 RequiredMinRepValue
uint32 RequiredMaxRepFaction
int32 RequiredMaxRepValue
uint32 SuggestedPlayers
uint32 LimitTime
uint32 m_QuestFlags
uint32 m_SpecialFlags
uint32 CharTitleId
uint32 PlayersSlain
uint32 BonusTalents
int32 PrevQuestId
int32 NextQuestId
int32 ExclusiveGroup
uint32 BreadcrumbForQuestId
uint32 NextQuestInChain
uint32 RewXPId
uint32 SrcItemId
uint32 SrcItemCount
uint32 SrcSpell
std::string Title
std::string Details
std::string Objectives
std::string OfferRewardText
std::string RequestItemsText
std::string EndText
std::string CompletedText
uint32 RewHonorAddition
float RewHonorMultiplier
int32 RewOrReqMoney
uint32 RewMoneyMaxLevel
uint32 RewSpell
uint32 RewSpellCast
uint32 RewMailTemplateId
uint32 RewMailDelaySecs
uint32 PointMapId
float PointX
float PointY
uint32 PointOpt
uint32 IncompleteEmote
uint32 IncompleteEmoteDelay
uint32 CompleteEmote
uint32 CompleteEmoteDelay
uint32 QuestStartScript
uint32 QuestCompleteScript
Private Attributes
uint32 m_reqitemscount
uint32 m_reqCreatureOrGOcount
uint32 m_rewchoiceitemscount
uint32 m_rewitemscount
uint32 m_detailsemotecount
bool m_isActive
Friends
class ObjectMgr
Detailed Description
Definition at line 203 of file QuestDef.h.
Member Typedef Documentation
PrevChainQuests
typedef std::vector<uint32> Quest::PrevChainQuests
Definition at line 324 of file QuestDef.h.
PrevQuests
typedef std::vector<int32> Quest::PrevQuests
Definition at line 322 of file QuestDef.h.
Constructor & Destructor Documentation
Quest()
Quest::Quest (Field * questRecord)
Definition at line 25 of file QuestDef.cpp.
References BonusTalents, BreadcrumbForQuestId, CharTitleId, CompletedText, CompleteEmote, CompleteEmoteDelay, Details, DetailsEmote, DetailsEmoteDelay, EndText, ExclusiveGroup, Field::GetCppString(), Field::GetFloat(), Field::GetInt32(), Field::GetUInt16(), Field::GetUInt32(), IncompleteEmote, IncompleteEmoteDelay, LimitTime, m_detailsemotecount, m_isActive, m_QuestFlags, m_reqCreatureOrGOcount, m_reqitemscount, m_rewchoiceitemscount, m_rewitemscount, m_SpecialFlags, MinLevel, NextQuestId, NextQuestInChain, Objectives, ObjectiveText, OfferRewardEmote, OfferRewardEmoteDelay, OfferRewardText, PlayersSlain, PointMapId, PointOpt, PointX, PointY, PrevQuestId, QUEST_EMOTE_COUNT, QUEST_ITEM_OBJECTIVES_COUNT, QUEST_OBJECTIVES_COUNT, QUEST_REPUTATIONS_COUNT, QUEST_REWARD_CHOICES_COUNT, QUEST_REWARDS_COUNT, QUEST_SOURCE_ITEM_IDS_COUNT, QuestCompleteScript, QuestId, QuestLevel, QuestMethod, QuestStartScript, RepObjectiveFaction, RepObjectiveValue, ReqCreatureOrGOCount, ReqCreatureOrGOId, ReqItemCount, ReqItemId, ReqSourceCount, ReqSourceId, ReqSpell, RequestItemsText, RequiredClasses, RequiredCondition, RequiredMaxRepFaction, RequiredMaxRepValue, RequiredMinRepFaction, RequiredMinRepValue, RequiredRaces, RequiredSkill, RequiredSkillValue, RewChoiceItemCount, RewChoiceItemId, RewHonorAddition, RewHonorMultiplier, RewItemCount, RewItemId, RewMailDelaySecs, RewMailTemplateId, RewMaxRepValue, RewMoneyMaxLevel, RewOrReqMoney, RewRepFaction, RewRepValue, RewRepValueId, RewSpell, RewSpellCast, RewXPId, SrcItemCount, SrcItemId, SrcSpell, SuggestedPlayers, Title, Type, and ZoneOrSort.
Member Function Documentation
CalculateRewardHonor()
uint32 Quest::CalculateRewardHonor (uint32 level) const
Definition at line 323 of file QuestDef.cpp.
References GetRewHonorAddition(), GetRewHonorMultiplier(), GT_MAX_LEVEL, sTeamContributionPoints, and TeamContributionPoints::Value.
Referenced by Player::RewardQuest().
CanIncreaseRewardedQuestCounters()
bool Quest::CanIncreaseRewardedQuestCounters () const
Definition at line 316 of file QuestDef.cpp.
References IsDaily(), IsDungeonFinderQuest(), IsMonthly(), IsRepeatable(), IsSeasonal(), and IsWeekly().
Referenced by Player::_LoadQuestStatus(), and Player::RewardQuest().
GetBonusTalents()
uint32 Quest::GetBonusTalents () const inline
Definition at line 244 of file QuestDef.h.
References BonusTalents.
Referenced by Player::_LoadQuestStatus(), WorldSession::HandleQuestQueryOpcode(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and Player::SendQuestReward().
GetBreadcrumbForQuestId()
uint32 Quest::GetBreadcrumbForQuestId () const inline
Definition at line 239 of file QuestDef.h.
References BreadcrumbForQuestId.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestBreadcrumbQuest().
GetCharTitleId()
uint32 Quest::GetCharTitleId () const inline
Definition at line 242 of file QuestDef.h.
References CharTitleId.
Referenced by Player::_LoadQuestStatus(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetCompletedText()
std::string Quest::GetCompletedText () const inline
Definition at line 254 of file QuestDef.h.
References CompletedText.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetCompleteEmote()
uint32 Quest::GetCompleteEmote () const inline
Definition at line 270 of file QuestDef.h.
References CompleteEmote.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetCompleteEmoteDelay()
uint32 Quest::GetCompleteEmoteDelay () const inline
Definition at line 271 of file QuestDef.h.
References CompleteEmoteDelay.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetDetails()
std::string Quest::GetDetails () const inline
Definition at line 249 of file QuestDef.h.
References Details.
Referenced by WorldSession::HandleQuestQueryOpcode(), and PlayerMenu::SendQuestGiverQuestDetails().
GetDetailsEmoteCount()
uint32 Quest::GetDetailsEmoteCount () const inline
Definition at line 272 of file QuestDef.h.
References m_detailsemotecount.
Referenced by PlayerMenu::SendQuestGiverQuestDetails().
GetEndText()
std::string Quest::GetEndText () const inline
Definition at line 253 of file QuestDef.h.
References EndText.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetExclusiveGroup()
int32 Quest::GetExclusiveGroup () const inline
Definition at line 238 of file QuestDef.h.
References ExclusiveGroup.
Referenced by Player::SatisfyQuestExclusiveGroup(), and Player::SatisfyQuestPreviousQuest().
GetIncompleteEmote()
uint32 Quest::GetIncompleteEmote () const inline
Definition at line 268 of file QuestDef.h.
References IncompleteEmote.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetIncompleteEmoteDelay()
uint32 Quest::GetIncompleteEmoteDelay () const inline
Definition at line 269 of file QuestDef.h.
References IncompleteEmoteDelay.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetLimitTime()
uint32 Quest::GetLimitTime () const inline
Definition at line 235 of file QuestDef.h.
References LimitTime.
Referenced by Player::AddQuest().
GetMaxLevel()
uint32 Quest::GetMaxLevel () const inline
Definition at line 220 of file QuestDef.h.
References MaxLevel.
Referenced by Player::CanSeeStartQuest(), and Player::SatisfyQuestLevel().
GetMinLevel()
uint32 Quest::GetMinLevel () const inline
Definition at line 219 of file QuestDef.h.
References MinLevel.
Referenced by Player::CanSeeStartQuest(), and WorldSession::HandleQuestQueryOpcode().
GetNextQuestId()
int32 Quest::GetNextQuestId () const inline
Definition at line 237 of file QuestDef.h.
References NextQuestId.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestPreviousQuest().
GetNextQuestInChain()
uint32 Quest::GetNextQuestInChain () const inline
Definition at line 240 of file QuestDef.h.
References NextQuestInChain.
Referenced by Player::GetNextQuest(), WorldSession::HandleQuestQueryOpcode(), and Player::SatisfyQuestNextChain().
GetObjectives()
std::string Quest::GetObjectives () const inline
Definition at line 250 of file QuestDef.h.
References Objectives.
Referenced by WorldSession::HandleQuestQueryOpcode(), and PlayerMenu::SendQuestGiverQuestDetails().
GetOfferRewardText()
std::string Quest::GetOfferRewardText () const inline
Definition at line 251 of file QuestDef.h.
References OfferRewardText.
Referenced by PlayerMenu::SendQuestGiverOfferReward().
GetPlayersSlain()
uint32 Quest::GetPlayersSlain () const inline
Definition at line 243 of file QuestDef.h.
References PlayersSlain.
Referenced by Player::CanCompleteQuest(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::KilledPlayerCreditForQuest(), and Player::SendQuestUpdateAddPlayer().
GetPointMapId()
uint32 Quest::GetPointMapId () const inline
Definition at line 264 of file QuestDef.h.
References PointMapId.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetPointOpt()
uint32 Quest::GetPointOpt () const inline
Definition at line 267 of file QuestDef.h.
References PointOpt.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetPointX()
float Quest::GetPointX () const inline
Definition at line 265 of file QuestDef.h.
References PointX.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetPointY()
float Quest::GetPointY () const inline
Definition at line 266 of file QuestDef.h.
References PointY.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetPrevQuestId()
int32 Quest::GetPrevQuestId () const inline
Definition at line 236 of file QuestDef.h.
References PrevQuestId.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestPreviousQuest().
GetQuestCompleteScript()
uint32 Quest::GetQuestCompleteScript () const inline
Definition at line 274 of file QuestDef.h.
References QuestCompleteScript.
Referenced by Player::RewardQuest().
GetQuestFlags()
uint32 Quest::GetQuestFlags () const inline
Definition at line 210 of file QuestDef.h.
References m_QuestFlags.
Referenced by Player::CanRewardQuest(), WorldSession::HandleQuestQueryOpcode(), PlayerMenu::SendGossipMenu(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestGiverRequestItems().
GetQuestId()
uint32 Quest::GetQuestId () const inline
Definition at line 216 of file QuestDef.h.
References QuestId.
Referenced by Player::_LoadDailyQuestStatus(), PlayerbotAI::AcceptQuest(), Player::AddQuest(), Player::CanRewardQuest(), ChatHandler::CheckEscapeSequences(), Player::FailQuest(), npc_escortAI::FailQuestForPlayerAndGroup(), npc_escortAI::GetAIInformation(), GOQuestAccept_GO_crystal_prison(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleQuestAddCommand(), WorldSession::HandleQuestQueryOpcode(), FollowerAI::JustDied(), Player::KilledPlayerCreditForQuest(), ObjectMgr::LoadConditions(), ObjectMgr::LoadQuests(), PlayerbotAI::MakeQuestLink(), QuestAccept_boss_vaelastrasz(), QuestAccept_npc_00x09hl(), QuestAccept_npc_akuno(), QuestAccept_npc_ame01(), QuestAccept_npc_anchorite_truuen(), QuestAccept_npc_apothecary_hanes(), QuestAccept_npc_arei(), QuestAccept_npc_bartleby(), QuestAccept_npc_belnistrasz(), QuestAccept_npc_bessy(), QuestAccept_npc_bonker_togglevolt(), QuestAccept_npc_calvin_montague(), QuestAccept_npc_captured_arkonarin(), QuestAccept_npc_captured_vanguard(), QuestAccept_npc_chromie(), QuestAccept_npc_commander(), QuestAccept_npc_cork_gizelton(), QuestAccept_npc_corporal_keeshan(), QuestAccept_npc_dalinda_malem(), QuestAccept_npc_daphne_stilwell(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_deathstalker_erland(), QuestAccept_npc_deathstalker_faerleia(), QuestAccept_npc_defias_traitor(), QuestAccept_npc_demolitionist_legoso(), QuestAccept_npc_doctor(), QuestAccept_npc_dorius_stonetender(), QuestAccept_npc_dragonmaw_racer(), QuestAccept_npc_drijya(), QuestAccept_npc_emily(), QuestAccept_npc_eris_havenfire(), QuestAccept_npc_father_kamaros(), QuestAccept_npc_feero_ironhand(), QuestAccept_npc_fhwoor(), QuestAccept_npc_galen_goodward(), QuestAccept_npc_gilthares(), QuestAccept_npc_grark_lorkrub(), QuestAccept_npc_gurthock(), QuestAccept_npc_harrison_jones(), QuestAccept_npc_helice(), QuestAccept_npc_injured_miner(), QuestAccept_npc_injured_rainspeaker(), QuestAccept_npc_isla_starmane(), QuestAccept_npc_kanati(), QuestAccept_npc_kaya(), QuestAccept_npc_kayra_longmane(), QuestAccept_npc_keeper_remulos(), QuestAccept_npc_kelerun_bloodmourn(), QuestAccept_npc_kerlonian(), QuestAccept_npc_kernobee(), QuestAccept_npc_kindal_moonweaver(), QuestAccept_npc_kinelory(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_letoll(), QuestAccept_npc_lurgglbr(), QuestAccept_npc_magwin(), QuestAccept_npc_major_mills(), QuestAccept_npc_marshal_windsor(), QuestAccept_npc_maxx_a_million(), QuestAccept_npc_melizza_brimbuzzle(), QuestAccept_npc_mikhail(), QuestAccept_npc_miran(), QuestAccept_npc_mist(), QuestAccept_npc_mootoo_the_younger(), QuestAccept_npc_morokk(), QuestAccept_npc_muglash(), QuestAccept_npc_nagrand_captive(), QuestAccept_npc_ogron(), QuestAccept_npc_oox17tn(), QuestAccept_npc_oox22fe(), QuestAccept_npc_orphan_matron(), QuestAccept_npc_paoka_swiftmountain(), QuestAccept_npc_private_hendel(), QuestAccept_npc_professor_phizzlethorpe(), QuestAccept_npc_prospector_remtravel(), QuestAccept_npc_proudhoof(), QuestAccept_npc_ranger_lilatha(), QuestAccept_npc_ranshalla(), QuestAccept_npc_reginald_windsor(), QuestAccept_npc_regthar_deathgate(), QuestAccept_npc_rigger_gizelton(), QuestAccept_npc_ringo(), QuestAccept_npc_rinji(), QuestAccept_npc_ruul_snowhoof(), QuestAccept_npc_shaheen(), QuestAccept_npc_shay_leafrunner(), QuestAccept_npc_skyguard_prisoner(), QuestAccept_npc_skywing(), QuestAccept_npc_squad_leader(), QuestAccept_npc_stinky_ignatz(), QuestAccept_npc_taelan_fordring(), QuestAccept_npc_therylune(), QuestAccept_npc_tooga(), QuestAccept_npc_torek(), QuestAccept_npc_volcor(), QuestAccept_npc_wilda(), QuestAccept_npc_willix_the_importer(), QuestAccept_npc_wizzlecranks_shredder(), QuestAccept_npc_wounded_blood_elf(), QuestAccept_unexpected_results(), QuestAcceptGO_crystalline_tear(), QuestComplete_npc_nazgrel(), QuestComplete_npc_trollbane(), QuestRewarded_boss_apothecary_hummel(), QuestRewarded_into_the_soulgrinder(), QuestRewarded_npc_adal(), QuestRewarded_npc_aurius(), QuestRewarded_npc_coren_direbrew(), QuestRewarded_npc_lady_sylvanas_windrunner(), QuestRewarded_npc_mistress_nagmara(), QuestRewarded_npc_rocknot(), QuestRewarded_npc_taelan_fordring(), QuestRewarded_suns_reach_reclamation(), QuestRewarded_tbc_attunement_titles(), QuestRewarded_war_effort(), Player::RewardQuest(), Player::SatisfyQuestDay(), Player::SatisfyQuestExclusiveGroup(), Player::SatisfyQuestMonth(), Player::SatisfyQuestStatus(), Player::SatisfyQuestWeek(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), Player::SendQuestReward(), Player::SendQuestUpdateAddCreatureOrGo(), Player::SendQuestUpdateAddPlayer(), ChatHandler::ShowQuestListHelper(), and npc_volcorAI::StartEscort().
GetQuestLevel()
int32 Quest::GetQuestLevel () const inline
Definition at line 221 of file QuestDef.h.
References QuestLevel.
Referenced by Player::GetQuestLevelForPlayer(), WorldSession::HandleQuestQueryOpcode(), PlayerbotAI::MakeQuestLink(), PlayerMenu::SendGossipMenu(), and ChatHandler::ShowQuestListHelper().
GetQuestMethod()
uint32 Quest::GetQuestMethod () const inline
Definition at line 217 of file QuestDef.h.
References QuestMethod.
Referenced by WorldSession::HandleQuestQueryOpcode(), and ObjectMgr::LoadQuests().
GetQuestStartScript()
uint32 Quest::GetQuestStartScript () const inline
Definition at line 273 of file QuestDef.h.
References QuestStartScript.
Referenced by Player::AddQuest().
GetRepObjectiveFaction()
uint32 Quest::GetRepObjectiveFaction () const inline
Definition at line 228 of file QuestDef.h.
References RepObjectiveFaction.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::AddQuest(), Player::CanCompleteQuest(), ChatHandler::HandleQuestCompleteCommand(), and WorldSession::HandleQuestQueryOpcode().
GetRepObjectiveValue()
int32 Quest::GetRepObjectiveValue () const inline
Definition at line 229 of file QuestDef.h.
References RepObjectiveValue.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::CanCompleteQuest(), ChatHandler::HandleQuestCompleteCommand(), and WorldSession::HandleQuestQueryOpcode().
GetReqCreatureOrGOcount()
uint32 Quest::GetReqCreatureOrGOcount () const inline
Definition at line 318 of file QuestDef.h.
References m_reqCreatureOrGOcount.
GetReqItemsCount()
uint32 Quest::GetReqItemsCount () const inline
Definition at line 317 of file QuestDef.h.
References m_reqitemscount.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequestItemsText()
std::string Quest::GetRequestItemsText () const inline
Definition at line 252 of file QuestDef.h.
References RequestItemsText.
Referenced by PlayerMenu::SendQuestGiverRequestItems().
GetRequiredClasses()
uint32 Quest::GetRequiredClasses () const inline
Definition at line 223 of file QuestDef.h.
References RequiredClasses.
Referenced by Player::SatisfyQuestClass().
GetRequiredCondition()
uint32 Quest::GetRequiredCondition () const inline
Definition at line 227 of file QuestDef.h.
References RequiredCondition.
Referenced by Player::SatisfyQuestCondition().
GetRequiredMaxRepFaction()
uint32 Quest::GetRequiredMaxRepFaction () const inline
Definition at line 232 of file QuestDef.h.
References RequiredMaxRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMaxRepValue()
int32 Quest::GetRequiredMaxRepValue () const inline
Definition at line 233 of file QuestDef.h.
References RequiredMaxRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepFaction()
uint32 Quest::GetRequiredMinRepFaction () const inline
Definition at line 230 of file QuestDef.h.
References RequiredMinRepFaction.
Referenced by Player::SatisfyQuestReputation().
GetRequiredMinRepValue()
int32 Quest::GetRequiredMinRepValue () const inline
Definition at line 231 of file QuestDef.h.
References RequiredMinRepValue.
Referenced by Player::SatisfyQuestReputation().
GetRequiredRaces()
uint32 Quest::GetRequiredRaces () const inline
Definition at line 224 of file QuestDef.h.
References RequiredRaces.
Referenced by Player::SatisfyQuestRace().
GetRequiredSkill()
uint32 Quest::GetRequiredSkill () const inline
Definition at line 225 of file QuestDef.h.
References RequiredSkill.
Referenced by Player::SatisfyQuestSkill().
GetRequiredSkillValue()
uint32 Quest::GetRequiredSkillValue () const inline
Definition at line 226 of file QuestDef.h.
References RequiredSkillValue.
Referenced by Player::SatisfyQuestSkill().
GetRewChoiceItemsCount()
uint32 Quest::GetRewChoiceItemsCount () const inline
Definition at line 319 of file QuestDef.h.
References m_rewchoiceitemscount.
Referenced by Player::CanRewardQuest(), PlayerbotAI::HandleCommand(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerbotAI::TurnInQuests().
GetRewHonorAddition()
uint32 Quest::GetRewHonorAddition () const inline
Definition at line 256 of file QuestDef.h.
References RewHonorAddition.
Referenced by CalculateRewardHonor(), WorldSession::HandleQuestQueryOpcode(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewHonorMultiplier()
float Quest::GetRewHonorMultiplier () const inline
Definition at line 257 of file QuestDef.h.
References RewHonorMultiplier.
Referenced by CalculateRewardHonor(), WorldSession::HandleQuestQueryOpcode(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewItemsCount()
uint32 Quest::GetRewItemsCount () const inline
Definition at line 320 of file QuestDef.h.
References m_rewitemscount.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewMailDelaySecs()
uint32 Quest::GetRewMailDelaySecs () const inline
Definition at line 263 of file QuestDef.h.
References RewMailDelaySecs.
Referenced by Player::RewardQuest().
GetRewMailTemplateId()
uint32 Quest::GetRewMailTemplateId () const inline
Definition at line 262 of file QuestDef.h.
References RewMailTemplateId.
Referenced by Player::RewardQuest().
GetRewMoneyMaxLevel()
uint32 Quest::GetRewMoneyMaxLevel () const
Definition at line 343 of file QuestDef.cpp.
References HasQuestFlag(), QUEST_FLAGS_NO_MONEY_FROM_XP, and RewMoneyMaxLevel.
Referenced by WorldSession::HandleQuestQueryOpcode(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and Player::SendQuestReward().
GetRewOrReqMoney()
int32 Quest::GetRewOrReqMoney () const
Definition at line 275 of file QuestDef.cpp.
References CONFIG_FLOAT_RATE_DROP_MONEY, RewOrReqMoney, and sWorld.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::CanCompleteQuest(), Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::MoneyChanged(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), and Player::SendQuestReward().
GetRewSpell()
uint32 Quest::GetRewSpell () const inline
Definition at line 260 of file QuestDef.h.
References RewSpell.
Referenced by WorldSession::HandleQuestQueryOpcode(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewSpellCast()
uint32 Quest::GetRewSpellCast () const inline
Definition at line 261 of file QuestDef.h.
References RewSpellCast.
Referenced by WorldSession::HandleQuestQueryOpcode(), Player::learnQuestRewardedSpells(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetRewXPId()
uint32 Quest::GetRewXPId () const inline
Definition at line 241 of file QuestDef.h.
References RewXPId.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetSrcItemCount()
uint32 Quest::GetSrcItemCount () const inline
Definition at line 246 of file QuestDef.h.
References SrcItemCount.
Referenced by Player::CanGiveQuestSourceItemIfNeed(), and Player::TakeQuestSourceItem().
GetSrcItemId()
uint32 Quest::GetSrcItemId () const inline
Definition at line 245 of file QuestDef.h.
References SrcItemId.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::AddQuest(), Player::CanGiveQuestSourceItemIfNeed(), Player::GiveQuestSourceItemIfNeed(), WorldSession::HandleQuestQueryOpcode(), and Player::TakeQuestSourceItem().
GetSrcSpell()
uint32 Quest::GetSrcSpell () const inline
Definition at line 247 of file QuestDef.h.
References SrcSpell.
Referenced by PlayerbotAI::AcceptQuest(), and WorldSession::HandleQuestgiverAcceptQuestOpcode().
GetSuggestedPlayers()
uint32 Quest::GetSuggestedPlayers () const inline
Definition at line 234 of file QuestDef.h.
References SuggestedPlayers.
Referenced by WorldSession::HandleQuestQueryOpcode(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerMenu::SendQuestGiverRequestItems().
GetTitle()
std::string Quest::GetTitle () const inline
Definition at line 248 of file QuestDef.h.
References Title.
Referenced by ChatHandler::CheckEscapeSequences(), ChatHandler::HandleLookupQuestCommand(), WorldSession::HandleQuestQueryOpcode(), PlayerbotAI::MakeQuestLink(), PlayerMenu::SendGossipMenu(), Player::SendQuestConfirmAccept(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), PlayerMenu::SendQuestGiverRequestItems(), ChatHandler::ShowQuestListHelper(), and PlayerbotAI::UseItem().
GetType()
uint32 Quest::GetType () const inline
Definition at line 222 of file QuestDef.h.
References Type.
Referenced by WorldSession::HandleQuestQueryOpcode().
GetXPReward()
uint32 Quest::GetXPReward (Player * pPlayer) const
Definition at line 188 of file QuestDef.cpp.
References Unit::GetLevel(), QuestLevel, RewXPId, and sQuestXPLevelStore.
Referenced by WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
GetZoneOrSort()
int32 Quest::GetZoneOrSort () const inline
Definition at line 218 of file QuestDef.h.
References ZoneOrSort.
Referenced by WorldSession::HandleQuestQueryOpcode(), Player::KilledPlayerCredit(), Player::RewardQuest(), and AchievementMgr::UpdateAchievementCriteria().
HasQuestFlag()
bool Quest::HasQuestFlag (QuestFlags flag) const inline
Definition at line 211 of file QuestDef.h.
References m_QuestFlags.
Referenced by Player::AddQuest(), Player::CanCompleteQuest(), Player::CastedCreatureOrGO(), WorldSession::getDialogStatus(), GetRewMoneyMaxLevel(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), and PlayerMenu::SendQuestGiverQuestDetails().
HasSpecialFlag()
bool Quest::HasSpecialFlag (QuestSpecialFlags flag) const inline
Definition at line 212 of file QuestDef.h.
References m_SpecialFlags.
Referenced by Player::_LoadQuestStatus(), Player::AddQuest(), Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), Player::CastedCreatureOrGO(), Player::FailQuest(), ChatHandler::HandleQuestCompleteCommand(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), Player::KilledMonsterCredit(), Player::KilledPlayerCredit(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuests(), ScriptMgr::LoadScripts(), Player::SatisfyQuestTimed(), and Player::TalkedToCreature().
IsActive()
bool Quest::IsActive () const inline
Definition at line 290 of file QuestDef.h.
References m_isActive.
Referenced by Player::CanSeeStartQuest(), Player::CanTakeQuest(), WorldSession::getDialogStatus(), and Player::PrepareQuestMenu().
IsAllowedInRaid()
bool Quest::IsAllowedInRaid () const
Definition at line 288 of file QuestDef.cpp.
References CONFIG_BOOL_QUEST_IGNORE_RAID, QUEST_TYPE_RAID, QUEST_TYPE_RAID_10, QUEST_TYPE_RAID_25, sWorld, and Type.
Referenced by Player::HasQuestForGO(), Player::HasQuestForItem(), and Player::KilledMonsterCredit().
IsAutoAccept()
bool Quest::IsAutoAccept () const inline
Definition at line 283 of file QuestDef.h.
References m_QuestFlags, and QUEST_FLAGS_AUTO_ACCEPT.
IsAutoComplete()
bool Quest::IsAutoComplete () const inline
Definition at line 277 of file QuestDef.h.
References QuestMethod.
Referenced by Player::_SaveQuestStatus(), Player::CanCompleteQuest(), Player::CanRewardQuest(), WorldSession::getDialogStatus(), Player::PrepareQuestMenu(), PlayerMenu::SendGossipMenu(), and Player::SendPreparedQuest().
IsDaily()
bool Quest::IsDaily () const inline
Definition at line 278 of file QuestDef.h.
References m_QuestFlags, and QUEST_FLAGS_DAILY.
Referenced by CanIncreaseRewardedQuestCounters(), Player::RewardQuest(), and Player::SatisfyQuestDay().
IsDailyOrWeekly()
bool Quest::IsDailyOrWeekly () const inline
Definition at line 282 of file QuestDef.h.
References m_QuestFlags, QUEST_FLAGS_DAILY, and QUEST_FLAGS_WEEKLY.
Referenced by WorldSession::getDialogStatus(), PlayerMenu::SendGossipMenu(), and Player::SendPreparedQuest().
IsDungeonFinderQuest()
bool Quest::IsDungeonFinderQuest () const inline
Definition at line 286 of file QuestDef.h.
References m_SpecialFlags, and QUEST_SPECIAL_FLAG_DUNGEON_FINDER_QUEST.
Referenced by Player::_LoadDailyQuestStatus(), CanIncreaseRewardedQuestCounters(), Player::CanRewardQuest(), Player::RewardQuest(), and Player::SatisfyQuestDay().
IsMonthly()
bool Quest::IsMonthly () const inline
Definition at line 280 of file QuestDef.h.
References m_SpecialFlags, and QUEST_SPECIAL_FLAG_MONTHLY.
Referenced by CanIncreaseRewardedQuestCounters(), Player::RewardQuest(), Player::SatisfyQuestMonth(), and PlayerMenu::SendGossipMenu().
IsRaidQuest()
bool Quest::IsRaidQuest (Difficulty difficulty) const
Definition at line 296 of file QuestDef.cpp.
References m_QuestFlags, QUEST_FLAGS_RAID, QUEST_TYPE_RAID, QUEST_TYPE_RAID_10, QUEST_TYPE_RAID_25, RAID_DIFFICULTY_MASK_25MAN, and Type.
Referenced by Player::KilledPlayerCredit().
IsRepeatable()
bool Quest::IsRepeatable () const inline
Definition at line 276 of file QuestDef.h.
References m_SpecialFlags, and QUEST_SPECIAL_FLAG_REPEATABLE.
Referenced by Player::_LoadQuestStatus(), CanIncreaseRewardedQuestCounters(), WorldSession::getDialogStatus(), Player::GetQuestRewardStatus(), IsSeasonal(), Player::RewardQuest(), PlayerMenu::SendGossipMenu(), and Player::SendPreparedQuest().
IsSeasonal()
bool Quest::IsSeasonal () const
Definition at line 283 of file QuestDef.cpp.
References IsRepeatable(), QUEST_SORT_BREWFEST, QUEST_SORT_LOVE_IS_IN_THE_AIR, QUEST_SORT_LUNAR_FESTIVAL, QUEST_SORT_MIDSUMMER, QUEST_SORT_NOBLEGARDEN, QUEST_SORT_SEASONAL, QUEST_SORT_SPECIAL, and ZoneOrSort.
Referenced by CanIncreaseRewardedQuestCounters().
IsWeekly()
bool Quest::IsWeekly () const inline
Definition at line 279 of file QuestDef.h.
References m_QuestFlags, and QUEST_FLAGS_WEEKLY.
Referenced by CanIncreaseRewardedQuestCounters(), Player::RewardQuest(), and Player::SatisfyQuestWeek().
SetQuestActiveState()
void Quest::SetQuestActiveState (bool state) inline
Definition at line 289 of file QuestDef.h.
References m_isActive.
SetSpecialFlag()
void Quest::SetSpecialFlag (QuestSpecialFlags flag) inline
Definition at line 213 of file QuestDef.h.
References m_SpecialFlags.
Referenced by ObjectMgr::LoadQuests().
Friends And Related Function Documentation
ObjectMgr
friend class ObjectMgr friend
Definition at line 205 of file QuestDef.h.
Field Documentation
BonusTalents
uint32 Quest::BonusTalents protected
Definition at line 364 of file QuestDef.h.
Referenced by GetBonusTalents(), and Quest().
BreadcrumbForQuestId
uint32 Quest::BreadcrumbForQuestId protected
Definition at line 368 of file QuestDef.h.
Referenced by GetBreadcrumbForQuestId(), ObjectMgr::LoadQuests(), and Quest().
CharTitleId
uint32 Quest::CharTitleId protected
Definition at line 362 of file QuestDef.h.
Referenced by GetCharTitleId(), ObjectMgr::LoadQuests(), and Quest().
CompletedText
std::string Quest::CompletedText protected
Definition at line 380 of file QuestDef.h.
Referenced by GetCompletedText(), and Quest().
CompleteEmote
uint32 Quest::CompleteEmote protected
Definition at line 395 of file QuestDef.h.
Referenced by GetCompleteEmote(), and Quest().
CompleteEmoteDelay
uint32 Quest::CompleteEmoteDelay protected
Definition at line 396 of file QuestDef.h.
Referenced by GetCompleteEmoteDelay(), and Quest().
DependentBreadcrumbQuests
std::vector<uint32> Quest::DependentBreadcrumbQuests
Definition at line 326 of file QuestDef.h.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestDependentBreadcrumbQuests().
Details
std::string Quest::Details protected
Definition at line 375 of file QuestDef.h.
Referenced by GetDetails(), and Quest().
DetailsEmote
uint32 Quest::DetailsEmote[QUEST_EMOTE_COUNT]
Definition at line 312 of file QuestDef.h.
Referenced by Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
DetailsEmoteDelay
uint32 Quest::DetailsEmoteDelay[QUEST_EMOTE_COUNT]
Definition at line 313 of file QuestDef.h.
Referenced by Quest(), and PlayerMenu::SendQuestGiverQuestDetails().
EndText
std::string Quest::EndText protected
Definition at line 379 of file QuestDef.h.
Referenced by GetEndText(), and Quest().
ExclusiveGroup
int32 Quest::ExclusiveGroup protected
Definition at line 367 of file QuestDef.h.
Referenced by GetExclusiveGroup(), ObjectMgr::LoadQuests(), and Quest().
IncompleteEmote
uint32 Quest::IncompleteEmote protected
Definition at line 393 of file QuestDef.h.
Referenced by GetIncompleteEmote(), and Quest().
IncompleteEmoteDelay
uint32 Quest::IncompleteEmoteDelay protected
Definition at line 394 of file QuestDef.h.
Referenced by GetIncompleteEmoteDelay(), and Quest().
LimitTime
uint32 Quest::LimitTime protected
Definition at line 359 of file QuestDef.h.
Referenced by GetLimitTime(), ObjectMgr::LoadQuests(), and Quest().
m_detailsemotecount
uint32 Quest::m_detailsemotecount private
Definition at line 334 of file QuestDef.h.
Referenced by GetDetailsEmoteCount(), and Quest().
m_isActive
bool Quest::m_isActive private
Definition at line 336 of file QuestDef.h.
Referenced by IsActive(), Quest(), and SetQuestActiveState().
m_QuestFlags
uint32 Quest::m_QuestFlags protected
Definition at line 360 of file QuestDef.h.
Referenced by GetQuestFlags(), HasQuestFlag(), IsAutoAccept(), IsDaily(), IsDailyOrWeekly(), IsRaidQuest(), IsWeekly(), ObjectMgr::LoadQuests(), and Quest().
m_reqCreatureOrGOcount
uint32 Quest::m_reqCreatureOrGOcount private
Definition at line 331 of file QuestDef.h.
Referenced by GetReqCreatureOrGOcount(), and Quest().
m_reqitemscount
uint32 Quest::m_reqitemscount private
Definition at line 330 of file QuestDef.h.
Referenced by GetReqItemsCount(), and Quest().
m_rewchoiceitemscount
uint32 Quest::m_rewchoiceitemscount private
Definition at line 332 of file QuestDef.h.
Referenced by GetRewChoiceItemsCount(), and Quest().
m_rewitemscount
uint32 Quest::m_rewitemscount private
Definition at line 333 of file QuestDef.h.
Referenced by GetRewItemsCount(), and Quest().
m_SpecialFlags
uint32 Quest::m_SpecialFlags protected
Definition at line 361 of file QuestDef.h.
Referenced by HasSpecialFlag(), IsDungeonFinderQuest(), IsMonthly(), IsRepeatable(), ObjectMgr::LoadQuests(), Quest(), and SetSpecialFlag().
MaxLevel
uint32 Quest::MaxLevel protected
Definition at line 344 of file QuestDef.h.
Referenced by GetMaxLevel().
MinLevel
uint32 Quest::MinLevel protected
Definition at line 343 of file QuestDef.h.
Referenced by GetMinLevel(), and Quest().
NextQuestId
int32 Quest::NextQuestId protected
Definition at line 366 of file QuestDef.h.
Referenced by GetNextQuestId(), ObjectMgr::LoadQuests(), and Quest().
NextQuestInChain
uint32 Quest::NextQuestInChain protected
Definition at line 369 of file QuestDef.h.
Referenced by GetNextQuestInChain(), ObjectMgr::LoadQuests(), and Quest().
Objectives
std::string Quest::Objectives protected
Definition at line 376 of file QuestDef.h.
Referenced by GetObjectives(), and Quest().
ObjectiveText
std::string Quest::ObjectiveText[QUEST_OBJECTIVES_COUNT]
Definition at line 296 of file QuestDef.h.
Referenced by WorldSession::HandleQuestQueryOpcode(), and Quest().
OfferRewardEmote
uint32 Quest::OfferRewardEmote[QUEST_EMOTE_COUNT]
Definition at line 314 of file QuestDef.h.
Referenced by Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardEmoteDelay
uint32 Quest::OfferRewardEmoteDelay[QUEST_EMOTE_COUNT]
Definition at line 315 of file QuestDef.h.
Referenced by Quest(), and PlayerMenu::SendQuestGiverOfferReward().
OfferRewardText
std::string Quest::OfferRewardText protected
Definition at line 377 of file QuestDef.h.
Referenced by GetOfferRewardText(), and Quest().
PlayersSlain
uint32 Quest::PlayersSlain protected
Definition at line 363 of file QuestDef.h.
Referenced by GetPlayersSlain(), ObjectMgr::LoadQuests(), and Quest().
PointMapId
uint32 Quest::PointMapId protected
Definition at line 389 of file QuestDef.h.
Referenced by GetPointMapId(), and Quest().
PointOpt
uint32 Quest::PointOpt protected
Definition at line 392 of file QuestDef.h.
Referenced by GetPointOpt(), and Quest().
PointX
float Quest::PointX protected
Definition at line 390 of file QuestDef.h.
Referenced by GetPointX(), and Quest().
PointY
float Quest::PointY protected
Definition at line 391 of file QuestDef.h.
Referenced by GetPointY(), and Quest().
prevChainQuests
PrevChainQuests Quest::prevChainQuests
Definition at line 325 of file QuestDef.h.
Referenced by Player::SatisfyQuestPrevChain().
PrevQuestId
int32 Quest::PrevQuestId protected
Definition at line 365 of file QuestDef.h.
Referenced by GetPrevQuestId(), ObjectMgr::LoadQuests(), and Quest().
prevQuests
PrevQuests Quest::prevQuests
Definition at line 323 of file QuestDef.h.
Referenced by ObjectMgr::LoadQuests(), and Player::SatisfyQuestPreviousQuest().
QuestCompleteScript
uint32 Quest::QuestCompleteScript protected
Definition at line 398 of file QuestDef.h.
Referenced by GetQuestCompleteScript(), and Quest().
QuestId
uint32 Quest::QuestId protected
Definition at line 340 of file QuestDef.h.
Referenced by GetQuestId(), ObjectMgr::LoadQuests(), and Quest().
QuestLevel
int32 Quest::QuestLevel protected
Definition at line 345 of file QuestDef.h.
Referenced by GetQuestLevel(), GetXPReward(), and Quest().
QuestMethod
uint32 Quest::QuestMethod protected
Definition at line 341 of file QuestDef.h.
Referenced by GetQuestMethod(), IsAutoComplete(), and Quest().
QuestStartScript
uint32 Quest::QuestStartScript protected
Definition at line 397 of file QuestDef.h.
Referenced by GetQuestStartScript(), and Quest().
RepObjectiveFaction
uint32 Quest::RepObjectiveFaction protected
Definition at line 352 of file QuestDef.h.
Referenced by GetRepObjectiveFaction(), ObjectMgr::LoadQuests(), and Quest().
RepObjectiveValue
int32 Quest::RepObjectiveValue protected
Definition at line 353 of file QuestDef.h.
Referenced by GetRepObjectiveValue(), ObjectMgr::LoadQuests(), and Quest().
ReqCreatureOrGOCount
uint32 Quest::ReqCreatureOrGOCount[QUEST_OBJECTIVES_COUNT]
Definition at line 302 of file QuestDef.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), PlayerbotAI::AcceptQuest(), PlayerbotAI::AddQuest(), Player::CanCompleteQuest(), Player::CastedCreatureOrGO(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::HasQuestForGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), Quest(), Player::SendQuestUpdateAddCreatureOrGo(), PlayerbotAI::SetQuestNeedCreatures(), and Player::TalkedToCreature().
ReqCreatureOrGOId
int32 Quest::ReqCreatureOrGOId[QUEST_OBJECTIVES_COUNT]
Definition at line 301 of file QuestDef.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::CanCompleteQuest(), Player::CastedCreatureOrGO(), Player::GetReqKillOrCastCurrentCount(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::HasQuestForGO(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), Quest(), Player::SendQuestUpdateAddCreatureOrGo(), PlayerbotAI::SetQuestNeedCreatures(), and Player::TalkedToCreature().
ReqItemCount
uint32 Quest::ReqItemCount[QUEST_ITEM_OBJECTIVES_COUNT]
Definition at line 298 of file QuestDef.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), PlayerbotAI::AcceptQuest(), PlayerbotAI::AddQuest(), Player::AdjustQuestReqItemCount(), Player::CanCompleteQuest(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::HasQuestForItem(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), QuestRewarded_war_effort(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerbotAI::SetQuestNeedItems().
ReqItemId
uint32 Quest::ReqItemId[QUEST_ITEM_OBJECTIVES_COUNT]
Definition at line 297 of file QuestDef.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::AddQuest(), Player::AdjustQuestReqItemCount(), Player::CanCompleteRepeatableQuest(), Player::CanRewardQuest(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleQuestQueryOpcode(), Player::HasQuestForItem(), Player::ItemAddedQuestCheck(), Player::ItemRemovedQuestCheck(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverRequestItems(), and PlayerbotAI::SetQuestNeedItems().
ReqSourceCount
uint32 Quest::ReqSourceCount[QUEST_SOURCE_ITEM_IDS_COUNT]
Definition at line 300 of file QuestDef.h.
Referenced by Player::HasQuestForItem(), ObjectMgr::LoadQuests(), Quest(), and Player::RewardQuest().
ReqSourceId
uint32 Quest::ReqSourceId[QUEST_SOURCE_ITEM_IDS_COUNT]
Definition at line 299 of file QuestDef.h.
Referenced by WorldSession::HandleQuestQueryOpcode(), Player::HasQuestForItem(), ObjectMgr::LoadQuests(), Quest(), and Player::RewardQuest().
ReqSpell
uint32 Quest::ReqSpell[QUEST_OBJECTIVES_COUNT]
Definition at line 303 of file QuestDef.h.
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::CastedCreatureOrGO(), ChatHandler::HandleQuestCompleteCommand(), Player::KilledMonsterCredit(), ObjectMgr::LoadQuests(), Quest(), and Player::TalkedToCreature().
RequestItemsText
std::string Quest::RequestItemsText protected
Definition at line 378 of file QuestDef.h.
Referenced by GetRequestItemsText(), and Quest().
RequiredClasses
uint32 Quest::RequiredClasses protected
Definition at line 347 of file QuestDef.h.
Referenced by GetRequiredClasses(), ObjectMgr::LoadQuests(), and Quest().
RequiredCondition
uint32 Quest::RequiredCondition protected
Definition at line 351 of file QuestDef.h.
Referenced by GetRequiredCondition(), ObjectMgr::LoadConditions(), and Quest().
RequiredMaxRepFaction
uint32 Quest::RequiredMaxRepFaction protected
Definition at line 356 of file QuestDef.h.
Referenced by GetRequiredMaxRepFaction(), ObjectMgr::LoadQuests(), and Quest().
RequiredMaxRepValue
int32 Quest::RequiredMaxRepValue protected
Definition at line 357 of file QuestDef.h.
Referenced by GetRequiredMaxRepValue(), ObjectMgr::LoadQuests(), and Quest().
RequiredMinRepFaction
uint32 Quest::RequiredMinRepFaction protected
Definition at line 354 of file QuestDef.h.
Referenced by GetRequiredMinRepFaction(), ObjectMgr::LoadQuests(), and Quest().
RequiredMinRepValue
int32 Quest::RequiredMinRepValue protected
Definition at line 355 of file QuestDef.h.
Referenced by GetRequiredMinRepValue(), ObjectMgr::LoadQuests(), and Quest().
RequiredRaces
uint32 Quest::RequiredRaces protected
Definition at line 348 of file QuestDef.h.
Referenced by GetRequiredRaces(), ObjectMgr::LoadQuests(), and Quest().
RequiredSkill
uint32 Quest::RequiredSkill protected
Definition at line 349 of file QuestDef.h.
Referenced by GetRequiredSkill(), ObjectMgr::LoadQuests(), and Quest().
RequiredSkillValue
uint32 Quest::RequiredSkillValue protected
Definition at line 350 of file QuestDef.h.
Referenced by GetRequiredSkillValue(), ObjectMgr::LoadQuests(), and Quest().
RewChoiceItemCount
uint32 Quest::RewChoiceItemCount[QUEST_REWARD_CHOICES_COUNT]
Definition at line 305 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
RewChoiceItemId
uint32 Quest::RewChoiceItemId[QUEST_REWARD_CHOICES_COUNT]
Definition at line 304 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), PlayerbotAI::HandleCommand(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), PlayerMenu::SendQuestGiverOfferReward(), PlayerMenu::SendQuestGiverQuestDetails(), and PlayerbotAI::TurnInQuests().
RewHonorAddition
uint32 Quest::RewHonorAddition protected
Definition at line 381 of file QuestDef.h.
Referenced by GetRewHonorAddition(), and Quest().
RewHonorMultiplier
float Quest::RewHonorMultiplier protected
Definition at line 382 of file QuestDef.h.
Referenced by GetRewHonorMultiplier(), and Quest().
RewItemCount
uint32 Quest::RewItemCount[QUEST_REWARDS_COUNT]
Definition at line 307 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
RewItemId
uint32 Quest::RewItemId[QUEST_REWARDS_COUNT]
Definition at line 306 of file QuestDef.h.
Referenced by Player::CanRewardQuest(), WorldSession::HandleLfgPlayerLockInfoRequestOpcode(), WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardQuest(), WorldSession::SendLfgPlayerReward(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
RewMailDelaySecs
uint32 Quest::RewMailDelaySecs protected
Definition at line 388 of file QuestDef.h.
Referenced by GetRewMailDelaySecs(), ObjectMgr::LoadQuests(), and Quest().
RewMailTemplateId
uint32 Quest::RewMailTemplateId protected
Definition at line 387 of file QuestDef.h.
Referenced by GetRewMailTemplateId(), ObjectMgr::LoadQuests(), and Quest().
RewMaxRepValue
int32 Quest::RewMaxRepValue[QUEST_REPUTATIONS_COUNT]
Definition at line 311 of file QuestDef.h.
Referenced by Quest(), and Player::RewardReputation().
RewMoneyMaxLevel
uint32 Quest::RewMoneyMaxLevel protected
Definition at line 384 of file QuestDef.h.
Referenced by GetRewMoneyMaxLevel(), and Quest().
RewOrReqMoney
int32 Quest::RewOrReqMoney protected
Definition at line 383 of file QuestDef.h.
Referenced by GetRewOrReqMoney(), and Quest().
RewRepFaction
uint32 Quest::RewRepFaction[QUEST_REPUTATIONS_COUNT]
Definition at line 308 of file QuestDef.h.
Referenced by WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
RewRepValue
int32 Quest::RewRepValue[QUEST_REPUTATIONS_COUNT]
Definition at line 310 of file QuestDef.h.
Referenced by ObjectMgr::LoadQuests(), Quest(), and Player::RewardReputation().
RewRepValueId
int32 Quest::RewRepValueId[QUEST_REPUTATIONS_COUNT]
Definition at line 309 of file QuestDef.h.
Referenced by WorldSession::HandleQuestQueryOpcode(), ObjectMgr::LoadQuests(), Quest(), Player::RewardReputation(), PlayerMenu::SendQuestGiverOfferReward(), and PlayerMenu::SendQuestGiverQuestDetails().
RewSpell
uint32 Quest::RewSpell protected
Definition at line 385 of file QuestDef.h.
Referenced by GetRewSpell(), ObjectMgr::LoadQuests(), and Quest().
RewSpellCast
uint32 Quest::RewSpellCast protected
Definition at line 386 of file QuestDef.h.
Referenced by GetRewSpellCast(), ObjectMgr::LoadQuests(), and Quest().
RewXPId
uint32 Quest::RewXPId protected
Definition at line 370 of file QuestDef.h.
Referenced by GetRewXPId(), GetXPReward(), and Quest().
SrcItemCount
uint32 Quest::SrcItemCount protected
Definition at line 372 of file QuestDef.h.
Referenced by GetSrcItemCount(), ObjectMgr::LoadQuests(), and Quest().
SrcItemId
uint32 Quest::SrcItemId protected
Definition at line 371 of file QuestDef.h.
Referenced by GetSrcItemId(), ObjectMgr::LoadQuests(), and Quest().
SrcSpell
uint32 Quest::SrcSpell protected
Definition at line 373 of file QuestDef.h.
Referenced by GetSrcSpell(), ObjectMgr::LoadQuests(), and Quest().
SuggestedPlayers
uint32 Quest::SuggestedPlayers protected
Definition at line 358 of file QuestDef.h.
Referenced by GetSuggestedPlayers(), and Quest().
Title
std::string Quest::Title protected
Definition at line 374 of file QuestDef.h.
Referenced by GetTitle(), and Quest().
Type
uint32 Quest::Type protected
Definition at line 346 of file QuestDef.h.
Referenced by GetType(), IsAllowedInRaid(), IsRaidQuest(), and Quest().
ZoneOrSort
int32 Quest::ZoneOrSort protected
Definition at line 342 of file QuestDef.h.
Referenced by GetZoneOrSort(), IsSeasonal(), ObjectMgr::LoadQuests(), and Quest().
The documentation for this class was generated from the following files:
QuestDef.h
QuestDef.cpp