CMaNGOS_WoTLK: ObjectAccessor Class Reference
ObjectAccessor Class Reference
#include <ObjectAccessor.h>
Public Types
typedef std::unordered_map< ObjectGuid, Corpse * > Player2CorpsesMapType
Public Member Functions
HashMapHolder< Player >::MapType & GetPlayers () const
void SaveAllPlayers () const
void ExecuteOnAllPlayers (std::function< void(Player *)> executor)
Corpse * GetCorpseForPlayerGUID (ObjectGuid guid)
void RemoveCorpse (Corpse *corpse)
void AddCorpse (Corpse *corpse)
void AddCorpsesToGrid (GridPair const &gridpair, GridType &grid, Map *map)
Corpse * ConvertCorpseForPlayer (ObjectGuid player_guid, bool insignia=false)
void RemoveOldCorpses ()
void AddObject (Corpse *object)
void AddObject (Player *player)
void RemoveObject (Corpse *object)
void RemoveObject (Player *player)
Static Public Member Functions
static Unit * GetUnit (WorldObject const &u, ObjectGuid guid)
static Player * FindPlayer (ObjectGuid guid, bool inWorld=true)
static Player * FindPlayerByName (char const *name, bool inWorld=true)
static void KickPlayer (ObjectGuid guid)
static Corpse * GetCorpseInMap (ObjectGuid guid, uint32 mapid)
Static Public Member Functions inherited from MaNGOS::Singleton< ObjectAccessor, MaNGOS::ClassLevelLockable< ObjectAccessor, std::mutex > >
static ObjectAccessor & Instance ()
Private Types
typedef std::mutex LockType
typedef MaNGOS::GeneralLock< LockType > Guard
Private Member Functions
ObjectAccessor ()
~ObjectAccessor ()
ObjectAccessor (const ObjectAccessor &)
ObjectAccessor & operator= (const ObjectAccessor &)
Private Attributes
Player2CorpsesMapType i_player2corpse
LockType i_playerGuard
LockType i_corpseGuard
Friends
class MaNGOS::OperatorNew< ObjectAccessor >
Additional Inherited Members
Protected Member Functions inherited from MaNGOS::Singleton< ObjectAccessor, MaNGOS::ClassLevelLockable< ObjectAccessor, std::mutex > >
Singleton ()
Detailed Description
Definition at line 87 of file ObjectAccessor.h.
Member Typedef Documentation
Guard
typedef MaNGOS::GeneralLock<LockType > ObjectAccessor::Guard private
Definition at line 136 of file ObjectAccessor.h.
LockType
typedef std::mutex ObjectAccessor::LockType private
Definition at line 135 of file ObjectAccessor.h.
Player2CorpsesMapType
typedef std::unordered_map<ObjectGuid, Corpse*> ObjectAccessor::Player2CorpsesMapType
Definition at line 97 of file ObjectAccessor.h.
Constructor & Destructor Documentation
ObjectAccessor() [1/2]
ObjectAccessor::ObjectAccessor () private
Definition at line 66 of file ObjectAccessor.cpp.
~ObjectAccessor()
ObjectAccessor::~ObjectAccessor () private
Definition at line 67 of file ObjectAccessor.cpp.
References i_player2corpse.
ObjectAccessor() [2/2]
ObjectAccessor::ObjectAccessor (const ObjectAccessor &) private
Member Function Documentation
AddCorpse()
void ObjectAccessor::AddCorpse (Corpse * corpse)
Definition at line 192 of file ObjectAccessor.cpp.
References MaNGOS::ComputeCellPair(), CORPSE_BONES, ObjectGuid::GetCounter(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), Corpse::GetOwnerGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Corpse::GetType(), i_corpseGuard, i_player2corpse, MANGOS_ASSERT, sObjectMgr, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
AddCorpsesToGrid()
void ObjectAccessor::AddCorpsesToGrid (GridPair const & gridpair, GridType & grid, Map * map)
Definition at line 208 of file ObjectAccessor.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Map::GetInstanceId(), i_corpseGuard, i_player2corpse, and Map::Instanceable().
AddObject() [1/2]
void ObjectAccessor::AddObject (Corpse * object) inline
Definition at line 126 of file ObjectAccessor.h.
References HashMapHolder< T >::Insert().
AddObject() [2/2]
void ObjectAccessor::AddObject (Player * player)
Definition at line 311 of file ObjectAccessor.cpp.
References PlayerNameMapHolder::Insert(), and HashMapHolder< T >::Insert().
ConvertCorpseForPlayer()
Corpse * ObjectAccessor::ConvertCorpseForPlayer (ObjectGuid player_guid, bool insignia = false)
Definition at line 230 of file ObjectAccessor.cpp.
References Map::Add(), CONFIG_BOOL_DEATH_BONES_BG_OR_ARENA, CONFIG_BOOL_DEATH_BONES_WORLD, CORPSE_END, CORPSE_FIELD_FLAGS, CORPSE_FIELD_ITEM, CORPSE_FLAG_BONES, CORPSE_FLAG_UNK2, Corpse::Create(), DEBUG_LOG, Corpse::DeleteFromDB(), EQUIPMENT_SLOT_END, GetCorpseForPlayerGUID(), Corpse::GetGrid(), Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Object::GetUInt32Value(), Map::IsBattleGroundOrArena(), Map::IsRemovalGrid(), WorldObject::Relocate(), Map::Remove(), RemoveCorpse(), Corpse::SetGrid(), Corpse::SetOwnerGuid(), WorldObject::SetPhaseMask(), Object::SetUInt32Value(), sMapMgr, and sWorld.
Referenced by RemoveOldCorpses().
ExecuteOnAllPlayers()
void ObjectAccessor::ExecuteOnAllPlayers (std::function< void(Player *)> executor)
Definition at line 140 of file ObjectAccessor.cpp.
References sObjectAccessor.
FindPlayer()
Player * ObjectAccessor::FindPlayer (ObjectGuid guid, bool inWorld = true) static
Definition at line 102 of file ObjectAccessor.cpp.
References HashMapHolder< T >::Find(), and Object::IsInWorld().
Referenced by LfgRaidBrowser::AddListener(), Guild::BroadcastPacket(), Guild::BroadcastPacketToRank(), World::BroadcastPersonalized(), SocialMgr::BroadcastToFriendListers(), Guild::BroadcastToGuild(), Guild::BroadcastToOfficers(), BattleGround::BroadcastWorker(), Guild::BroadcastWorker(), Spell::CheckCast(), Guild::DisplayGuildBankContentUpdate(), Loot::FillLoot(), Unit::GetChannelObject(), Unit::GetCharm(), Unit::GetCharmer(), LFGMgr::GetCompatibleDungeons(), Unit::GetCreator(), SocialMgr::GetFriendInfo(), Player::GetObjectByTypeMask(), Creature::GetOriginalLootRecipient(), GameObject::GetOriginalLootRecipient(), Map::GetPlayer(), ObjectMgr::GetPlayer(), Unit::GetSpawner(), Unit::GetTarget(), GetUnit(), WorldSession::HandleAddFriendOpcodeCallBack(), WorldSession::HandleArenaTeamRemoveOpcode(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildDeclineOpcode(), WorldSession::HandleInitiateTradeOpcode(), WorldSession::HandleLootMasterGiveOpcode(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePlayerLoginOpcode(), WorldSession::HandleQuestConfirmAccept(), WorldSession::HandleQuestgiverAcceptQuestOpcode(), WorldSession::HandleQuestPushResult(), WorldSession::HandleRequestPartyMemberStatsOpcode(), Loot::IsLootedForAll(), KickPlayer(), MaNGOS::VisibleNotifier::Notify(), Loot::NotifyItemChanged(), Loot::NotifyItemRemoved(), Loot::NotifyMoneyRemoved(), MaNGOS::CannibalizeObjectCheck::operator()(), MaNGOS::TauntFlagObjectCheck::operator()(), Player::QueueOrAddResurrectRequest(), Group::ResetInstances(), Guild::Roster(), Loot::SendAllowedLooter(), Loot::SetGroupLootRight(), Spell::SetTargetMap(), LfgRaidBrowser::Update(), and GameObject::Use().
FindPlayerByName()
Player * ObjectAccessor::FindPlayerByName (char const * name, bool inWorld = true) static
Definition at line 114 of file ObjectAccessor.cpp.
References PlayerNameMapHolder::Find(), and Object::IsInWorld().
Referenced by ObjectMgr::GetPlayer(), WorldSession::HandleArenaTeamInviteOpcode(), and WorldSession::HandleGuildInviteOpcode().
GetCorpseForPlayerGUID()
Corpse * ObjectAccessor::GetCorpseForPlayerGUID (ObjectGuid guid)
Definition at line 158 of file ObjectAccessor.cpp.
References CORPSE_BONES, i_corpseGuard, i_player2corpse, and MANGOS_ASSERT.
Referenced by ConvertCorpseForPlayer().
GetCorpseInMap()
Corpse * ObjectAccessor::GetCorpseInMap (ObjectGuid guid, uint32 mapid) static
Definition at line 91 of file ObjectAccessor.cpp.
References HashMapHolder< T >::Find(), and WorldObject::GetMapId().
Referenced by Spell::DoAllEffectOnTarget(), Map::GetCorpse(), and SpellCastTargets::Update().
GetPlayers()
HashMapHolder<Player>::MapType& ObjectAccessor::GetPlayers () const inline
Definition at line 108 of file ObjectAccessor.h.
References HashMapHolder< T >::GetContainer().
GetUnit()
Unit * ObjectAccessor::GetUnit (WorldObject const & u, ObjectGuid guid) static
Definition at line 77 of file ObjectAccessor.cpp.
References FindPlayer(), Map::GetAnyTypeCreature(), WorldObject::GetMap(), Object::IsInWorld(), and ObjectGuid::IsPlayer().
Referenced by PlayerbotAI::_HandleCommandAttack(), PlayerbotAI::_HandleCommandNeutralize(), PlayerbotAI::_HandleCommandOrders(), PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandPull(), PlayerbotAI::_HandleCommandSkill(), PlayerbotAI::_HandleCommandUse(), Unit::AddComboPoints(), Spell::cancel(), PlayerbotAI::CastNeutralize(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), Unit::ClearComboPoints(), PlayerbotAI::CombatOrderRestore(), Spell::DelayedChannel(), Spell::DoAllEffectOnTarget(), Unit::FindRootVehicle(), DynamicObject::GetCaster(), Unit::GetControllingPlayer(), Player::GetFirstControlled(), GameObject::GetOwner(), ChatHandler::getSelectedUnit(), Aura::HandleAuraRetainComboPoints(), Unit::HandleDummyAuraProc(), ChatHandler::HandleGameObjectDeleteCommand(), Spell::HandleImmediateEffectExecution(), PlayerbotMgr::HandleMasterIncomingPacket(), WorldSession::HandleOnMissileTrajectoryCollision(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleSetTargetOpcode(), Spell::HandleThreatSpells(), WorldSession::HandleUpdateMissileTrajectory(), AbstractWrapperMovementGenerator::Initialize(), Spell::IsAliveUnitPresentInTargetList(), Spell::ProcReflectProcs(), Spell::ProcSpellAuraTriggers(), GameObject::RemoveFromWorld(), Spell::SendChannelStart(), Player::SendComboPoints(), Spell::update(), SpellCastTargets::Update(), PlayerbotAI::UpdateAI(), HostileReference::updateOnlineStatus(), and Spell::UpdateOriginalCasterPointer().
KickPlayer()
void ObjectAccessor::KickPlayer (ObjectGuid guid) static
Definition at line 148 of file ObjectAccessor.cpp.
References FindPlayer(), and WorldSession::KickPlayer().
Referenced by AccountMgr::DeleteAccount(), and WorldSession::ProcessByteBufferException().
operator=()
ObjectAccessor& ObjectAccessor::operator= (const ObjectAccessor &) private
RemoveCorpse()
void ObjectAccessor::RemoveCorpse (Corpse * corpse)
Definition at line 172 of file ObjectAccessor.cpp.
References MaNGOS::ComputeCellPair(), CORPSE_BONES, ObjectGuid::GetCounter(), WorldObject::GetMapId(), Corpse::GetOwnerGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Corpse::GetType(), i_corpseGuard, i_player2corpse, MANGOS_ASSERT, Corpse::RemoveFromWorld(), sObjectMgr, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by ConvertCorpseForPlayer().
RemoveObject() [1/2]
void ObjectAccessor::RemoveObject (Corpse * object) inline
Definition at line 128 of file ObjectAccessor.h.
References HashMapHolder< T >::Remove().
RemoveObject() [2/2]
void ObjectAccessor::RemoveObject (Player * player)
Definition at line 317 of file ObjectAccessor.cpp.
References PlayerNameMapHolder::Remove(), and HashMapHolder< T >::Remove().
RemoveOldCorpses()
void ObjectAccessor::RemoveOldCorpses ()
Definition at line 295 of file ObjectAccessor.cpp.
References ConvertCorpseForPlayer(), and i_player2corpse.
SaveAllPlayers()
void ObjectAccessor::SaveAllPlayers () const
Definition at line 123 of file ObjectAccessor.cpp.
References sObjectAccessor.
Friends And Related Function Documentation
MaNGOS::OperatorNew< ObjectAccessor >
friend class MaNGOS::OperatorNew< ObjectAccessor > friend
Definition at line 84 of file ObjectAccessor.h.
Field Documentation
i_corpseGuard
LockType ObjectAccessor::i_corpseGuard private
Definition at line 139 of file ObjectAccessor.h.
Referenced by AddCorpse(), AddCorpsesToGrid(), GetCorpseForPlayerGUID(), and RemoveCorpse().
i_player2corpse
Player2CorpsesMapType ObjectAccessor::i_player2corpse private
Definition at line 133 of file ObjectAccessor.h.
Referenced by AddCorpse(), AddCorpsesToGrid(), GetCorpseForPlayerGUID(), RemoveCorpse(), RemoveOldCorpses(), and ~ObjectAccessor().
i_playerGuard
LockType ObjectAccessor::i_playerGuard private
Definition at line 138 of file ObjectAccessor.h.
The documentation for this class was generated from the following files:
ObjectAccessor.h
ObjectAccessor.cpp