CMaNGOS_WoTLK: VisibilityData Class Reference
VisibilityData Class Reference
#include <ObjectVisibility.h>
Public Member Functions
VisibilityData (WorldObject *owner)
bool IsVisibilityOverridden () const
void SetVisibilityDistanceOverride (VisibilityDistanceType type)
float GetVisibilityDistance () const
float GetVisibilityDistanceFor (WorldObject *obj) const
bool CanDetectInvisibilityOf (WorldObject const *u) const
uint32 GetInvisibilityDetectMask () const
void SetInvisibilityDetectMask (uint32 index, bool apply)
uint32 GetInvisibilityMask () const
void SetInvisibilityMask (uint32 index, bool apply)
void SetInvisibilityValue (uint32 index, int32 value)
void AddInvisibilityValue (uint32 index, int32 value)
void AddInvisibilityDetectValue (uint32 index, int32 value)
int32 GetInvisibilityValue (uint32 index) const
int32 GetInvisibilityDetectValue (uint32 index) const
uint32 GetStealthMask () const
void SetStealthMask (uint32 index, bool apply)
void AddStealthStrength (StealthType type, uint32 value)
void AddStealthDetectionStrength (StealthType type, uint32 value)
uint32 GetStealthStrength (StealthType type) const
uint32 GetStealthDetectionStrength (StealthType type) const
float GetStealthVisibilityDistance (Unit const *target, bool alert=false) const
Private Attributes
float m_visibilityDistanceOverride
uint32 m_invisibilityMask
uint32 m_detectInvisibilityMask
int32 m_invisibilityValues [INVISIBILITY_TYPE_MAX]
int32 m_invisibilityDetectValues [INVISIBILITY_TYPE_MAX]
uint32 m_stealthMask
uint32 m_stealthStrength [STEALTH_TYPE_MAX]
uint32 m_stealthDetectStrength [STEALTH_TYPE_MAX]
WorldObject * m_owner
Detailed Description
Definition at line 53 of file ObjectVisibility.h.
Constructor & Destructor Documentation
VisibilityData()
VisibilityData::VisibilityData (WorldObject * owner)
Definition at line 35 of file ObjectVisibility.cpp.
References m_invisibilityDetectValues, m_invisibilityValues, m_stealthDetectStrength, and m_stealthStrength.
Member Function Documentation
AddInvisibilityDetectValue()
void VisibilityData::AddInvisibilityDetectValue (uint32 index, int32 value) inline
Definition at line 72 of file ObjectVisibility.h.
References m_invisibilityDetectValues.
Referenced by Aura::HandleInvisibilityDetect().
AddInvisibilityValue()
void VisibilityData::AddInvisibilityValue (uint32 index, int32 value) inline
Definition at line 71 of file ObjectVisibility.h.
References m_invisibilityValues.
Referenced by GameObject::Create(), go_plague_cauldron::go_plague_cauldron(), go_portal_to_orgrimmar::go_portal_to_orgrimmar(), go_portal_to_undercity::go_portal_to_undercity(), go_scrying_orb::go_scrying_orb(), and Aura::HandleInvisibility().
AddStealthDetectionStrength()
void VisibilityData::AddStealthDetectionStrength (StealthType type, uint32 value) inline
Definition at line 79 of file ObjectVisibility.h.
References m_stealthDetectStrength.
Referenced by Aura::HandleModStealthDetect().
AddStealthStrength()
void VisibilityData::AddStealthStrength (StealthType type, uint32 value) inline
Definition at line 78 of file ObjectVisibility.h.
References m_stealthStrength.
Referenced by GameObject::Create(), Aura::HandleModStealth(), and Aura::HandleModStealthLevel().
CanDetectInvisibilityOf()
bool VisibilityData::CanDetectInvisibilityOf (WorldObject const * u) const
Definition at line 69 of file ObjectVisibility.cpp.
References GetInvisibilityDetectMask(), GetInvisibilityDetectValue(), GetInvisibilityMask(), GetInvisibilityValue(), WorldObject::GetVisibilityData(), and INVISIBILITY_TYPE_MAX.
Referenced by GameObject::isVisibleForInState(), and Unit::IsVisibleForOrDetect().
GetInvisibilityDetectMask()
uint32 VisibilityData::GetInvisibilityDetectMask () const
Definition at line 92 of file ObjectVisibility.cpp.
References Unit::GetControllingPlayer(), WorldObject::GetVisibilityData(), Object::HasFlag(), Object::isType(), m_detectInvisibilityMask, m_owner, TYPEMASK_UNIT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by CanDetectInvisibilityOf().
GetInvisibilityDetectValue()
int32 VisibilityData::GetInvisibilityDetectValue (uint32 index) const
Definition at line 133 of file ObjectVisibility.cpp.
References Unit::GetControllingPlayer(), WorldObject::GetVisibilityData(), Object::HasFlag(), Object::isType(), m_invisibilityDetectValues, m_owner, TYPEMASK_UNIT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by CanDetectInvisibilityOf().
GetInvisibilityMask()
uint32 VisibilityData::GetInvisibilityMask () const
Definition at line 115 of file ObjectVisibility.cpp.
References m_invisibilityMask.
Referenced by CanDetectInvisibilityOf(), Aura::HandleInvisibility(), GameObject::isVisibleForInState(), and Unit::IsVisibleForOrDetect().
GetInvisibilityValue()
int32 VisibilityData::GetInvisibilityValue (uint32 index) const
Definition at line 128 of file ObjectVisibility.cpp.
References m_invisibilityValues.
Referenced by CanDetectInvisibilityOf(), and Aura::HandleInvisibility().
GetStealthDetectionStrength()
uint32 VisibilityData::GetStealthDetectionStrength (StealthType type) const inline
Definition at line 81 of file ObjectVisibility.h.
References m_stealthDetectStrength.
Referenced by GetStealthVisibilityDistance().
GetStealthMask()
uint32 VisibilityData::GetStealthMask () const inline
Definition at line 76 of file ObjectVisibility.h.
References m_stealthMask.
Referenced by GameObject::isVisibleForInState().
GetStealthStrength()
uint32 VisibilityData::GetStealthStrength (StealthType type) const inline
Definition at line 80 of file ObjectVisibility.h.
References m_stealthStrength.
Referenced by GetStealthVisibilityDistance().
GetStealthVisibilityDistance()
float VisibilityData::GetStealthVisibilityDistance (Unit const * target, bool alert = false) const
Definition at line 157 of file ObjectVisibility.cpp.
References Unit::GetCombatReach(), Unit::GetLevelForTarget(), GetStealthDetectionStrength(), GetStealthStrength(), Object::GetTypeId(), WorldObject::GetVisibilityData(), m_owner, MAX_PLAYER_STEALTH_DETECT_RANGE, STEALTH_UNIT, TYPEID_GAMEOBJECT, and TYPEID_PLAYER.
Referenced by UnitAI::CanTriggerStealthAlert(), ChatHandler::HandleGetDistanceCommand(), GameObject::isVisibleForInState(), and Unit::IsVisibleForOrDetect().
GetVisibilityDistance()
float VisibilityData::GetVisibilityDistance () const
Definition at line 53 of file ObjectVisibility.cpp.
References WorldObject::GetMap(), Map::GetVisibilityDistance(), IsVisibilityOverridden(), m_owner, and m_visibilityDistanceOverride.
Referenced by GameObject::Create(), GetVisibilityDistanceFor(), ChatHandler::HandleRespawnCommand(), Map::MessageBroadcast(), Spell::SendSpellGo(), go_brewfest_music::UpdateAI(), go_midsummer_music::UpdateAI(), Map::UpdateObjectVisibility(), Camera::UpdateVisibilityForOwner(), and Map::VisitNearbyCellsOf().
GetVisibilityDistanceFor()
float VisibilityData::GetVisibilityDistanceFor (WorldObject * obj) const
Definition at line 61 of file ObjectVisibility.cpp.
References Object::GetTypeId(), WorldObject::GetVisibilityData(), GetVisibilityDistance(), IsVisibilityOverridden(), m_visibilityDistanceOverride, and TYPEID_PLAYER.
Referenced by Unit::IsVisibleForOrDetect().
IsVisibilityOverridden()
bool VisibilityData::IsVisibilityOverridden () const inline
Definition at line 59 of file ObjectVisibility.h.
References m_visibilityDistanceOverride.
Referenced by GetVisibilityDistance(), and GetVisibilityDistanceFor().
SetInvisibilityDetectMask()
void VisibilityData::SetInvisibilityDetectMask (uint32 index, bool apply)
Definition at line 107 of file ObjectVisibility.cpp.
References ByteConverter::apply(), and m_detectInvisibilityMask.
Referenced by Aura::HandleInvisibilityDetect(), and Player::SetDrunkValue().
SetInvisibilityMask()
void VisibilityData::SetInvisibilityMask (uint32 index, bool apply)
Definition at line 120 of file ObjectVisibility.cpp.
References ByteConverter::apply(), and m_invisibilityMask.
Referenced by GameObject::Create(), go_plague_cauldron::go_plague_cauldron(), go_portal_to_orgrimmar::go_portal_to_orgrimmar(), go_portal_to_undercity::go_portal_to_undercity(), go_scrying_orb::go_scrying_orb(), and Aura::HandleInvisibility().
SetInvisibilityValue()
void VisibilityData::SetInvisibilityValue (uint32 index, int32 value) inline
Definition at line 70 of file ObjectVisibility.h.
References m_invisibilityValues.
Referenced by Player::SetDrunkValue().
SetStealthMask()
void VisibilityData::SetStealthMask (uint32 index, bool apply)
Definition at line 149 of file ObjectVisibility.cpp.
References ByteConverter::apply(), and m_stealthMask.
Referenced by GameObject::Create().
SetVisibilityDistanceOverride()
void VisibilityData::SetVisibilityDistanceOverride (VisibilityDistanceType type)
Definition at line 44 of file ObjectVisibility.cpp.
References AsUnderlyingType(), Object::GetTypeId(), m_owner, m_visibilityDistanceOverride, MANGOS_ASSERT, Max, TYPEID_PLAYER, and VisibilityDistances.
Referenced by GameObject::Create(), Transport::Create(), and CreatureSettings::ResetStaticFlags().
Field Documentation
m_detectInvisibilityMask
uint32 VisibilityData::m_detectInvisibilityMask private
Definition at line 89 of file ObjectVisibility.h.
Referenced by GetInvisibilityDetectMask(), and SetInvisibilityDetectMask().
m_invisibilityDetectValues
int32 VisibilityData::m_invisibilityDetectValues[INVISIBILITY_TYPE_MAX] private
Definition at line 91 of file ObjectVisibility.h.
Referenced by AddInvisibilityDetectValue(), GetInvisibilityDetectValue(), and VisibilityData().
m_invisibilityMask
uint32 VisibilityData::m_invisibilityMask private
Definition at line 88 of file ObjectVisibility.h.
Referenced by GetInvisibilityMask(), and SetInvisibilityMask().
m_invisibilityValues
int32 VisibilityData::m_invisibilityValues[INVISIBILITY_TYPE_MAX] private
Definition at line 90 of file ObjectVisibility.h.
Referenced by AddInvisibilityValue(), GetInvisibilityValue(), SetInvisibilityValue(), and VisibilityData().
m_owner
WorldObject* VisibilityData::m_owner private
Definition at line 97 of file ObjectVisibility.h.
Referenced by GetInvisibilityDetectMask(), GetInvisibilityDetectValue(), GetStealthVisibilityDistance(), GetVisibilityDistance(), and SetVisibilityDistanceOverride().
m_stealthDetectStrength
uint32 VisibilityData::m_stealthDetectStrength[STEALTH_TYPE_MAX] private
Definition at line 95 of file ObjectVisibility.h.
Referenced by AddStealthDetectionStrength(), GetStealthDetectionStrength(), and VisibilityData().
m_stealthMask
uint32 VisibilityData::m_stealthMask private
Definition at line 93 of file ObjectVisibility.h.
Referenced by GetStealthMask(), and SetStealthMask().
m_stealthStrength
uint32 VisibilityData::m_stealthStrength[STEALTH_TYPE_MAX] private
Definition at line 94 of file ObjectVisibility.h.
Referenced by AddStealthStrength(), GetStealthStrength(), and VisibilityData().
m_visibilityDistanceOverride
float VisibilityData::m_visibilityDistanceOverride private
Definition at line 86 of file ObjectVisibility.h.
Referenced by GetVisibilityDistance(), GetVisibilityDistanceFor(), IsVisibilityOverridden(), and SetVisibilityDistanceOverride().
The documentation for this class was generated from the following files:
ObjectVisibility.h
ObjectVisibility.cpp