CMaNGOS_WoTLK: GMSurveyResult Class Reference
GMSurveyResult Class Reference
#include <GMTicketMgr.h>
Public Member Functions
GMSurveyResult (const GMSurveyEntry &entry, uint32 ticketId, const std::map< uint32, uint8 > &answers, const std::string &feedback)
bool HasComment () const
size_t GetAnswersCount () const
uint32 GetTicketId () const
uint32 GetSurveyId () const
std::vector< uint8 > const & GetAnswers () const
std::string const & GetComment () const
Private Attributes
uint32 m_ticketId
uint32 m_surveyId
std::vector< uint8 > m_answers
std::string m_comment
Detailed Description
Definition at line 194 of file GMTicketMgr.h.
Constructor & Destructor Documentation
GMSurveyResult()
GMSurveyResult::GMSurveyResult (const GMSurveyEntry & entry, uint32 ticketId, const std::map< uint32, uint8 > & answers, const std::string & feedback) explicit
Definition at line 281 of file GMTicketMgr.cpp.
References m_answers, MAX_GMSURVEY_QUESTIONS, and GMSurveyEntry::questionID.
Member Function Documentation
GetAnswers()
std::vector<uint8> const& GMSurveyResult::GetAnswers () const inline
Definition at line 204 of file GMTicketMgr.h.
References m_answers.
Referenced by GMTicketMgr::Save().
GetAnswersCount()
size_t GMSurveyResult::GetAnswersCount () const inline
Definition at line 201 of file GMTicketMgr.h.
References m_answers.
Referenced by GMTicketMgr::Save().
GetComment()
std::string const& GMSurveyResult::GetComment () const inline
Definition at line 205 of file GMTicketMgr.h.
References m_comment.
Referenced by GMTicketMgr::Save().
GetSurveyId()
uint32 GMSurveyResult::GetSurveyId () const inline
Definition at line 203 of file GMTicketMgr.h.
References m_surveyId.
Referenced by GMTicketMgr::Save().
GetTicketId()
uint32 GMSurveyResult::GetTicketId () const inline
Definition at line 202 of file GMTicketMgr.h.
References m_ticketId.
Referenced by GMTicketMgr::Save().
HasComment()
bool GMSurveyResult::HasComment () const inline
Definition at line 199 of file GMTicketMgr.h.
References m_comment.
Referenced by GMTicketMgr::Save().
Field Documentation
m_answers
std::vector<uint8> GMSurveyResult::m_answers private
Definition at line 210 of file GMTicketMgr.h.
Referenced by GetAnswers(), GetAnswersCount(), and GMSurveyResult().
m_comment
std::string GMSurveyResult::m_comment private
Definition at line 211 of file GMTicketMgr.h.
Referenced by GetComment(), and HasComment().
m_surveyId
uint32 GMSurveyResult::m_surveyId private
Definition at line 209 of file GMTicketMgr.h.
Referenced by GetSurveyId().
m_ticketId
uint32 GMSurveyResult::m_ticketId private
Definition at line 208 of file GMTicketMgr.h.
Referenced by GetTicketId().
The documentation for this class was generated from the following files:
GMTicketMgr.h
GMTicketMgr.cpp