CMaNGOS_WoTLK: SpellCastTargets Class Reference
SpellCastTargets Class Reference
#include <Spell.h>
Public Member Functions
SpellCastTargets ()
~SpellCastTargets ()
void read (ByteBuffer &data, Unit *caster)
void write (ByteBuffer &data) const
SpellCastTargetsReader ReadForCaster (Unit *caster)
SpellCastTargets & operator= (const SpellCastTargets &target)
void setUnitTarget (Unit *target)
ObjectGuid getUnitTargetGuid () const
Unit * getUnitTarget () const
void setDestination (float x, float y, float z)
void setDestination (Position position)
void setSource (float x, float y, float z)
void getDestination (float &x, float &y, float &z) const
Position getDestination () const
void getDestination (WorldLocation &loc)
void getSource (float &x, float &y, float &z) const
Position getSource () const
float getElevation () const
void setElevation (float elevation)
float getSpeed () const
void setSpeed (float speed)
void setGOTarget (GameObject *target)
ObjectGuid getGOTargetGuid () const
GameObject * getGOTarget () const
void setCorpseTarget (Corpse *corpse)
ObjectGuid getCorpseTargetGuid () const
Corpse * getCorpseTarget () const
void setItemTarget (Item *item)
ObjectGuid getItemTargetGuid () const
Item * getItemTarget () const
uint32 getItemTargetEntry () const
ObjectGuid getDestTransportGuid () const
void setTradeItemTarget (Player *caster)
void updateTradeSlotItem ()
bool IsEmpty () const
void Update (WorldObject *caster)
Data Fields
Position m_srcPos
Position m_srcTransportPos
Position m_destPos
Position m_destTransportPos
std::string m_strTarget
uint32 m_targetMask
uint32 m_mapId
Private Attributes
Unit * m_unitTarget
GameObject * m_GOTarget
Item * m_itemTarget
Corpse * m_CorpseTarget
ObjectGuid m_unitTargetGUID
ObjectGuid m_GOTargetGUID
ObjectGuid m_CorpseTargetGUID
ObjectGuid m_itemTargetGUID
ObjectGuid m_srcTransportGUID
ObjectGuid m_destTransportGUID
uint32 m_itemTargetEntry
float m_elevation
float m_speed
Detailed Description
Definition at line 112 of file Spell.h.
Constructor & Destructor Documentation
SpellCastTargets()
SpellCastTargets::SpellCastTargets ()
Definition at line 117 of file Spell.cpp.
References m_CorpseTarget, m_elevation, m_GOTarget, m_itemTarget, m_itemTargetEntry, m_mapId, m_speed, m_strTarget, m_targetMask, and m_unitTarget.
~SpellCastTargets()
SpellCastTargets::~SpellCastTargets ()
Definition at line 134 of file Spell.cpp.
Member Function Documentation
getCorpseTarget()
Corpse* SpellCastTargets::getCorpseTarget () const inline
Definition at line 181 of file Spell.h.
References m_CorpseTarget.
Referenced by Spell::FillFromTargetFlags(), and Spell::GetMinMaxRange().
getCorpseTargetGuid()
ObjectGuid SpellCastTargets::getCorpseTargetGuid () const inline
Definition at line 180 of file Spell.h.
References m_CorpseTargetGUID.
Referenced by Spell::CheckCast(), Spell::CheckTarget(), and Spell::FillFromTargetFlags().
getDestination() [1/3]
Position SpellCastTargets::getDestination () const inline
Definition at line 164 of file Spell.h.
References m_destPos.
getDestination() [2/3]
void SpellCastTargets::getDestination (float & x, float & y, float & z) const inline
Definition at line 163 of file Spell.h.
References m_destPos, Position::x, Position::y, and Position::z.
Referenced by Spell::CalculateDelayMomentForDst(), Spell::CheckCast(), Spell::CheckTarget(), Spell::EffectChargeDest(), Spell::EffectDummy(), Spell::EffectForceCast(), Spell::EffectJump(), Spell::EffectKnockBackFromPosition(), Spell::EffectLeapForward(), Spell::EffectPullTowards(), Spell::EffectSummonDeadPet(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonType(), Spell::EffectTeleportUnits(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), Spell::EffectTriggerSpell(), JuggleTorchCatch::OnCast(), SummonVoidSentinelSummoner::OnDestTarget(), spell_icy_blast::OnEffectExecute(), ThrowTorch::OnEffectExecute(), BrazierOfDancingFlames::OnSummon(), Spell::SetTargetMap(), and MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer().
getDestination() [3/3]
void SpellCastTargets::getDestination (WorldLocation & loc) inline
Definition at line 165 of file Spell.h.
References WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, m_destPos, Position::x, Position::y, and Position::z.
getDestTransportGuid()
ObjectGuid SpellCastTargets::getDestTransportGuid () const inline
Definition at line 188 of file Spell.h.
References m_destTransportGUID.
Referenced by Spell::SendSpellGo().
getElevation()
float SpellCastTargets::getElevation () const inline
Definition at line 169 of file Spell.h.
References m_elevation.
Referenced by Spell::AddGOTarget(), Spell::AddUnitTarget(), Spell::CalculateDelayMomentForDst(), WorldSession::HandleUpdateMissileTrajectory(), and Spell::SendSpellGo().
getGOTarget()
GameObject* SpellCastTargets::getGOTarget () const inline
Definition at line 177 of file Spell.h.
References m_GOTarget.
Referenced by Spell::CanOpenLock(), Spell::CheckCast(), Spell::CheckRange(), and Spell::SetTargetMap().
getGOTargetGuid()
ObjectGuid SpellCastTargets::getGOTargetGuid () const inline
Definition at line 176 of file Spell.h.
References m_GOTargetGUID.
getItemTarget()
Item* SpellCastTargets::getItemTarget () const inline
Definition at line 185 of file Spell.h.
References m_itemTarget.
Referenced by Spell::CheckCast(), Spell::CheckItems(), Spell::ClearCastItem(), Spell::EffectFeedPet(), Spell::FillFromTargetFlags(), GetSpellCastTime(), Spell::IgnoreItemRequirements(), and Spell::SetTargetMap().
getItemTargetEntry()
uint32 SpellCastTargets::getItemTargetEntry () const inline
Definition at line 186 of file Spell.h.
References m_itemTargetEntry.
Referenced by Spell::CheckItems(), and Spell::TakeReagents().
getItemTargetGuid()
ObjectGuid SpellCastTargets::getItemTargetGuid () const inline
Definition at line 184 of file Spell.h.
References m_itemTargetGUID.
Referenced by Spell::CheckCast(), and Spell::CheckItems().
getSource() [1/2]
Position SpellCastTargets::getSource () const inline
Definition at line 167 of file Spell.h.
References m_srcPos.
getSource() [2/2]
void SpellCastTargets::getSource (float & x, float & y, float & z) const inline
Definition at line 166 of file Spell.h.
References m_srcPos, Position::x, Position::y, and Position::z.
Referenced by Spell::CalculateDelayMomentForDst(), Spell::CheckTarget(), Spell::SetTargetMap(), and MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer().
getSpeed()
float SpellCastTargets::getSpeed () const inline
Definition at line 172 of file Spell.h.
References m_speed.
Referenced by Spell::AddGOTarget(), Spell::AddUnitTarget(), Spell::CalculateDelayMomentForDst(), WorldSession::HandleUpdateMissileTrajectory(), Spell::SendSpellGo(), and Spell::SendSpellStart().
getUnitTarget()
Unit* SpellCastTargets::getUnitTarget () const inline
Definition at line 158 of file Spell.h.
References m_unitTarget.
Referenced by Spell::cast(), Spell::CheckCast(), Spell::CheckItems(), Spell::CheckPetCast(), Spell::CheckRange(), Spell::CheckScriptTargeting(), Spell::CheckTarget(), Spell::DoAllEffectOnTarget(), Spell::DoAllTargetlessEffects(), Spell::DoSpellHitOnUnit(), Spell::EffectHeal(), Spell::EffectJump(), Spell::EffectScriptEffect(), Spell::FillFromTargetFlags(), Spell::FilterTargetMap(), Spell::GetMinMaxRange(), Spell::GetPrefilledUnitTargetOrUnitTarget(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandleUseItemOpcode(), ItemUse_item_gor_dreks_ointment(), BlazeTwins::OnCast(), PlantWarsongBanner::OnCast(), CorrosiveSpit::OnCast(), BurnBody::OnCast(), UseBricksBonesaw::OnCast(), GymersBuddy::OnCast(), Spell::OnCheckCast(), CalmDragonkin::OnCheckCast(), TwistingBlade::OnCheckCast(), TagGreaterFelfireDiemetradon::OnCheckCast(), PrayerOfMending::OnCheckCast(), GammeritaTurtleCamera::OnCheckCast(), SpecificTargetScript::OnCheckCast(), PlantWarsongBanner::OnCheckCast(), CaptureJormungarSpawnSpellScript::OnCheckCast(), ContainerOfRatsSpellScript::OnCheckCast(), LiquidFireOfElune::OnCheckCast(), spell_eagle_eyes::OnCheckCast(), spell_assemble_cage::OnCheckCast(), BurnBody::OnCheckCast(), UseBricksBonesaw::OnCheckCast(), MirrorImageFrostbolt::OnCheckCast(), RetaliationCreature::OnCheckCast(), Misdirection::OnCheckCast(), PowerInfusion::OnCheckCast(), CurseOfDoom::OnCheckCast(), DevourMagic::OnCheckCast(), Spell::OnCheckTarget(), ThousandBladesRenataki::OnEffectExecute(), TagGreaterFelfireDiemetradon::OnHit(), SummonGargoyle::OnSummon(), Shadowfiend::OnSummon(), Spell::Prepare(), Spell::SendCastResult(), Spell::SendChannelStart(), Spell::SetTargetMap(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), and Spell::update().
getUnitTargetGuid()
ObjectGuid SpellCastTargets::getUnitTargetGuid () const inline
Definition at line 157 of file Spell.h.
References m_unitTargetGUID.
Referenced by Spell::cast(), Spell::EffectSchoolDMG(), Spell::FillTargetMap(), DiveBomb::OnAfterHit(), Spell::OnCheckCast(), MentalInterferenceSpellScript::OnCheckCast(), CastNetStormforgedPursuer::OnCheckCast(), ShootRJR::OnCheckCast(), CrusaderParachute::OnCheckCast(), ExorcismFeather::OnCheckCast(), SparrowhawkNet::OnCheckCast(), BanishExile::OnCheckCast(), SeedOfCorruptionDamage::OnCheckTarget(), Spell::update(), and Spell::WriteSpellGoTargets().
IsEmpty()
bool SpellCastTargets::IsEmpty () const inline
Definition at line 201 of file Spell.h.
References m_CorpseTargetGUID, m_GOTargetGUID, m_itemTarget, and m_unitTargetGUID.
operator=()
SpellCastTargets& SpellCastTargets::operator= (const SpellCastTargets & target) inline
Definition at line 123 of file Spell.h.
References m_CorpseTargetGUID, m_destPos, m_destTransportGUID, m_destTransportPos, m_elevation, m_GOTarget, m_GOTargetGUID, m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_mapId, m_speed, m_srcPos, m_srcTransportGUID, m_srcTransportPos, m_strTarget, m_targetMask, m_unitTarget, and m_unitTargetGUID.
read()
void SpellCastTargets::read (ByteBuffer & data, Unit * caster)
Definition at line 251 of file Spell.cpp.
References WorldObject::GetMap(), Map::GetTransport(), Object::GetTypeId(), MaNGOS::IsValidMapCoord(), m_CorpseTargetGUID, m_destPos, m_destTransportGUID, m_destTransportPos, m_GOTargetGUID, m_itemTargetGUID, m_srcPos, m_srcTransportGUID, m_srcTransportPos, m_strTarget, m_targetMask, m_unitTargetGUID, Position::o, ObjectGuid::ReadAsPacked(), ByteBuffer::rpos(), ByteBuffer::size(), TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_LOCKED, TARGET_FLAG_SELF, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_STRING, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_ENEMY, TARGET_FLAG_UNIT_MINIPET, TYPEID_PLAYER, Update(), Position::x, Position::y, and Position::z.
Referenced by operator>>().
ReadForCaster()
SpellCastTargetsReader SpellCastTargets::ReadForCaster (Unit * caster) inline
Definition at line 121 of file Spell.h.
Referenced by WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetCastSpellOpcode(), and WorldSession::HandleUseItemOpcode().
setCorpseTarget()
void SpellCastTargets::setCorpseTarget (Corpse * corpse)
Definition at line 198 of file Spell.cpp.
References Object::GetObjectGuid(), m_CorpseTarget, and m_CorpseTargetGUID.
setDestination() [1/2]
void SpellCastTargets::setDestination (float x, float y, float z)
Definition at line 149 of file Spell.cpp.
References m_destPos, m_targetMask, TARGET_FLAG_DEST_LOCATION, Position::x, Position::y, and Position::z.
Referenced by AreaTrigger_at_area_52(), Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Spell::CheckScriptTargeting(), Spell::EffectForceCast(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), Spell::FillFromTargetFlags(), WorldSession::HandleOnMissileTrajectoryCollision(), WorldSession::HandleUpdateMissileTrajectory(), FlignTorch::OnDestTarget(), and Spell::SetTargetMap().
setDestination() [2/2]
void SpellCastTargets::setDestination (Position position)
Definition at line 157 of file Spell.cpp.
References m_destPos, m_targetMask, and TARGET_FLAG_DEST_LOCATION.
setElevation()
void SpellCastTargets::setElevation (float elevation) inline
Definition at line 170 of file Spell.h.
References m_elevation.
Referenced by WorldSession::HandleClientCastFlags(), and WorldSession::HandleUpdateMissileTrajectory().
setGOTarget()
void SpellCastTargets::setGOTarget (GameObject * target)
Definition at line 171 of file Spell.cpp.
References Object::GetObjectGuid(), m_GOTarget, and m_GOTargetGUID.
Referenced by PlayerbotAI::CheckBotCast(), and Spell::EffectTriggerMissileSpell().
setItemTarget()
void SpellCastTargets::setItemTarget (Item * item)
Definition at line 178 of file Spell.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_targetMask, and TARGET_FLAG_ITEM.
Referenced by PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandProcess(), Spell::ClearCastItem(), Spell::EffectEnchantItemTmp(), and Spell::TakeReagents().
setSource()
void SpellCastTargets::setSource (float x, float y, float z)
Definition at line 163 of file Spell.cpp.
References m_srcPos, m_targetMask, TARGET_FLAG_SOURCE_LOCATION, Position::x, Position::y, and Position::z.
Referenced by Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Spell::FillTargetMap(), WorldSession::HandleUpdateMissileTrajectory(), and Spell::SetTargetMap().
setSpeed()
void SpellCastTargets::setSpeed (float speed) inline
Definition at line 173 of file Spell.h.
References m_speed.
Referenced by WorldSession::HandleClientCastFlags(), and WorldSession::HandleUpdateMissileTrajectory().
setTradeItemTarget()
void SpellCastTargets::setTradeItemTarget (Player * caster)
Definition at line 189 of file Spell.cpp.
References m_itemTargetEntry, m_itemTargetGUID, m_targetMask, TARGET_FLAG_TRADE_ITEM, TRADE_SLOT_NONTRADED, and Update().
Referenced by WorldSession::HandleAcceptTradeOpcode().
setUnitTarget()
void SpellCastTargets::setUnitTarget (Unit * target)
Definition at line 138 of file Spell.cpp.
References Object::GetObjectGuid(), WorldObject::GetPosition(), m_destPos, m_targetMask, m_unitTarget, m_unitTargetGUID, and TARGET_FLAG_UNIT.
Referenced by Unit::_UpdateAutoRepeatSpell(), AreaTrigger_at_area_52(), Unit::CastCustomSpell(), Player::CastItemUseSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), Spell::CheckAndAddMagnetTarget(), PlayerbotAI::CheckBotCast(), Spell::CheckCast(), Spell::CheckPetCast(), Spell::EffectForceCast(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerSpell(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), Spell::ProcSpellAuraTriggers(), PetAI::UpdateAI(), PlayerbotAI::UpdateAI(), and GameObject::Use().
Update()
void SpellCastTargets::Update (WorldObject * caster)
Definition at line 204 of file Spell.cpp.
References ObjectAccessor::GetCorpseInMap(), Object::GetEntry(), Map::GetGameObject(), Player::GetItemByGuid(), WorldObject::GetMap(), WorldObject::GetMapId(), Object::GetObjectGuid(), ObjectGuid::GetRawValue(), Player::GetTradeData(), Map::GetTransport(), Object::GetTypeId(), ObjectAccessor::GetUnit(), m_CorpseTarget, m_CorpseTargetGUID, m_destPos, m_destTransportGUID, m_destTransportPos, m_GOTarget, m_GOTargetGUID, m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_srcPos, m_srcTransportGUID, m_srcTransportPos, m_targetMask, m_unitTarget, m_unitTargetGUID, Position::o, TARGET_FLAG_ITEM, TARGET_FLAG_TRADE_ITEM, TRADE_SLOT_COUNT, TYPEID_PLAYER, Position::x, Position::y, and Position::z.
Referenced by Player::CastQueuedSpell(), WorldSession::HandleUseItemOpcode(), read(), setTradeItemTarget(), and Spell::UpdatePointers().
updateTradeSlotItem()
void SpellCastTargets::updateTradeSlotItem () inline
Definition at line 192 of file Spell.h.
References Object::GetEntry(), Object::GetObjectGuid(), m_itemTarget, m_itemTargetEntry, m_itemTargetGUID, m_targetMask, and TARGET_FLAG_TRADE_ITEM.
Referenced by Spell::cast().
write()
void SpellCastTargets::write (ByteBuffer & data) const
Definition at line 310 of file Spell.cpp.
References Object::GetPackGUID(), m_CorpseTargetGUID, m_destPos, m_destTransportGUID, m_GOTarget, m_itemTarget, m_srcPos, m_srcTransportGUID, m_strTarget, m_targetMask, m_unitTarget, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_STRING, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_MINIPET, ObjectGuid::WriteAsPacked(), Position::x, Position::y, and Position::z.
Referenced by operator<<().
Field Documentation
m_CorpseTarget
Corpse* SpellCastTargets::m_CorpseTarget private
Definition at line 220 of file Spell.h.
Referenced by getCorpseTarget(), setCorpseTarget(), SpellCastTargets(), and Update().
m_CorpseTargetGUID
ObjectGuid SpellCastTargets::m_CorpseTargetGUID private
Definition at line 225 of file Spell.h.
Referenced by getCorpseTargetGuid(), IsEmpty(), operator=(), read(), setCorpseTarget(), Update(), and write().
m_destPos
Position SpellCastTargets::m_destPos
Definition at line 207 of file Spell.h.
Referenced by Spell::CheckRange(), Spell::DoSummonPet(), Spell::EffectAddFarsight(), Spell::EffectDistract(), Spell::EffectPersistentAA(), Spell::EffectSummonDeadPet(), Spell::EffectSummonPet(), Spell::EffectTeleportUnits(), Spell::EffectTriggerMissileSpell(), getDestination(), WorldSession::HandleUpdateMissileTrajectory(), JuggleTorchCatchQuest::OnCast(), ArmageddonAnimation::OnDestTarget(), SummonVoidSentinelSummoner::OnDestTarget(), BlackHoleEffect::OnDestTarget(), TeleportSelf::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), spell_gravity_well_effect::OnDestTarget(), spell_summon_banshee::OnDestTarget(), SummonStefan::OnDestTarget(), EtherealRingSignalFlare::OnDestTarget(), SummonBlossomMoveTarget::OnDestTarget(), CallingRider::OnDestTarget(), NetherVaporSummon::OnDestTarget(), LunarFestivalFireworkSingle::OnDestTarget(), LunarFestivalClusterSmallD::OnDestTarget(), LunarFestivalClusterSmallN::OnDestTarget(), LunarFestivalClusterSmallSE::OnDestTarget(), LunarFestivalClusterSmallSW::OnDestTarget(), LunarFestivalClusterSmallU::OnDestTarget(), LunarFestivalClusterBigD::OnDestTarget(), LunarFestivalClusterBigN::OnDestTarget(), LunarFestivalClusterBigSE::OnDestTarget(), LunarFestivalClusterBigSW::OnDestTarget(), LunarFestivalClusterBigU::OnDestTarget(), SummonRibbonPoleCritter::OnDestTarget(), FlignTorch::OnDestTarget(), BrazierOfDancingFlames::OnDestTarget(), ShatteredSunMarksmanShoot::OnEffectExecute(), FlignTorch::OnEffectExecute(), BucketLands::OnSuccessfulFinish(), operator=(), read(), Spell::SendSpellGo(), setDestination(), Spell::SetTargetMap(), setUnitTarget(), Update(), MaNGOS::SpellNotifierPlayer::Visit(), and write().
m_destTransportGUID
ObjectGuid SpellCastTargets::m_destTransportGUID private
Definition at line 228 of file Spell.h.
Referenced by getDestTransportGuid(), operator=(), read(), Update(), and write().
m_destTransportPos
Position SpellCastTargets::m_destTransportPos
Definition at line 208 of file Spell.h.
Referenced by operator=(), read(), and Update().
m_elevation
float SpellCastTargets::m_elevation private
Definition at line 231 of file Spell.h.
Referenced by getElevation(), operator=(), setElevation(), and SpellCastTargets().
m_GOTarget
GameObject* SpellCastTargets::m_GOTarget private
Definition at line 218 of file Spell.h.
Referenced by getGOTarget(), operator=(), setGOTarget(), SpellCastTargets(), Update(), and write().
m_GOTargetGUID
ObjectGuid SpellCastTargets::m_GOTargetGUID private
Definition at line 224 of file Spell.h.
Referenced by getGOTargetGuid(), IsEmpty(), operator=(), read(), setGOTarget(), and Update().
m_itemTarget
Item* SpellCastTargets::m_itemTarget private
Definition at line 219 of file Spell.h.
Referenced by getItemTarget(), IsEmpty(), operator=(), setItemTarget(), SpellCastTargets(), Update(), updateTradeSlotItem(), and write().
m_itemTargetEntry
uint32 SpellCastTargets::m_itemTargetEntry private
Definition at line 229 of file Spell.h.
Referenced by getItemTargetEntry(), operator=(), setItemTarget(), setTradeItemTarget(), SpellCastTargets(), Update(), and updateTradeSlotItem().
m_itemTargetGUID
ObjectGuid SpellCastTargets::m_itemTargetGUID private
Definition at line 226 of file Spell.h.
Referenced by getItemTargetGuid(), operator=(), read(), setItemTarget(), setTradeItemTarget(), Update(), and updateTradeSlotItem().
m_mapId
uint32 SpellCastTargets::m_mapId
Definition at line 213 of file Spell.h.
Referenced by Spell::EffectTeleportUnits(), operator=(), Spell::SetTargetMap(), and SpellCastTargets().
m_speed
float SpellCastTargets::m_speed private
Definition at line 231 of file Spell.h.
Referenced by getSpeed(), operator=(), setSpeed(), and SpellCastTargets().
m_srcPos
Position SpellCastTargets::m_srcPos
Definition at line 205 of file Spell.h.
Referenced by Spell::CheckRange(), getSource(), WorldSession::HandleUpdateMissileTrajectory(), operator=(), read(), Spell::SendSpellGo(), setSource(), Update(), and write().
m_srcTransportGUID
ObjectGuid SpellCastTargets::m_srcTransportGUID private
Definition at line 227 of file Spell.h.
Referenced by operator=(), read(), Update(), and write().
m_srcTransportPos
Position SpellCastTargets::m_srcTransportPos
Definition at line 206 of file Spell.h.
Referenced by operator=(), read(), and Update().
m_strTarget
std::string SpellCastTargets::m_strTarget
Definition at line 209 of file Spell.h.
Referenced by operator=(), read(), SpellCastTargets(), and write().
m_targetMask
uint32 SpellCastTargets::m_targetMask
Definition at line 211 of file Spell.h.
Referenced by Spell::AddCorpseTarget(), Spell::AddGOTarget(), Spell::AddUnitTarget(), Spell::CalculateDelayMomentForDst(), Unit::CastSpell(), Spell::CheckCast(), Spell::CheckItems(), Spell::CheckPetCast(), Spell::CheckRange(), Spell::DoSummonPet(), Spell::EffectChargeDest(), Spell::EffectDummy(), Spell::EffectForceCast(), Spell::EffectJump(), Spell::EffectKnockBackFromPosition(), Spell::EffectSummonObject(), Spell::EffectSummonObjectWild(), Spell::EffectSummonType(), Spell::EffectTeleportUnits(), Spell::EffectTeleUnitsFaceCaster(), Spell::EffectTransmitted(), Spell::EffectTriggerSpell(), Spell::FillFromTargetFlags(), Spell::FillTargetMap(), WorldSession::HandleOnMissileTrajectoryCollision(), WorldSession::HandleUpdateMissileTrajectory(), operator=(), read(), Spell::SendSpellGo(), Spell::SendSpellStart(), setDestination(), setItemTarget(), setSource(), Spell::SetTargetMap(), setTradeItemTarget(), setUnitTarget(), SpellCastTargets(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), Spell::TakeCastItem(), Update(), updateTradeSlotItem(), and write().
m_unitTarget
Unit* SpellCastTargets::m_unitTarget private
Definition at line 217 of file Spell.h.
Referenced by getUnitTarget(), operator=(), setUnitTarget(), SpellCastTargets(), Update(), and write().
m_unitTargetGUID
ObjectGuid SpellCastTargets::m_unitTargetGUID private
Definition at line 223 of file Spell.h.
Referenced by getUnitTargetGuid(), IsEmpty(), operator=(), read(), setUnitTarget(), and Update().
The documentation for this class was generated from the following files:
Spell.h
Spell.cpp