CMaNGOS_WoTLK: MaNGOS::LocalizedPacketListDo< Builder > Class Template Reference
MaNGOS::LocalizedPacketListDo< Builder > Class Template Reference
#include <GridNotifiers.h>
Public Types
typedef std::vector< std::unique_ptr< WorldPacket > > WorldPacketList
Public Member Functions
LocalizedPacketListDo (Builder &builder)
void operator() (Player *p)
Private Attributes
Builder & i_builder
std::vector< WorldPacketList > i_data_cache
Detailed Description
template<class Builder>
class MaNGOS::LocalizedPacketListDo< Builder >
Definition at line 1589 of file GridNotifiers.h.
Member Typedef Documentation
WorldPacketList
template<class Builder > typedef std::vector<std::unique_ptr<WorldPacket> > MaNGOS::LocalizedPacketListDo< Builder >::WorldPacketList
Definition at line 1592 of file GridNotifiers.h.
Constructor & Destructor Documentation
LocalizedPacketListDo()
template<class Builder > MaNGOS::LocalizedPacketListDo< Builder >::LocalizedPacketListDo (Builder & builder) inline explicit
Definition at line 1593 of file GridNotifiers.h.
Member Function Documentation
operator()()
template<class Builder > void MaNGOS::LocalizedPacketListDo< Builder >::operator() (Player * p)
Definition at line 703 of file GridNotifiersImpl.h.
References Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), and Player::SendDirectMessage().
Field Documentation
i_builder
template<class Builder > Builder& MaNGOS::LocalizedPacketListDo< Builder >::i_builder private
Definition at line 1598 of file GridNotifiers.h.
i_data_cache
template<class Builder > std::vector<WorldPacketList> MaNGOS::LocalizedPacketListDo< Builder >::i_data_cache private
Definition at line 1599 of file GridNotifiers.h.
The documentation for this class was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h