CMaNGOS_WoTLK: SQLStorageLoaderBase< DerivedLoader, StorageClass > Class Template Reference
SQLStorageLoaderBase< DerivedLoader, StorageClass > Class Template Reference
#include <SQLStorage.h>
Public Member Functions
void Load (StorageClass &store, bool error_at_empty=true)
template<class S , class D >
void convert (uint32 field_pos, S src, D &dst)
template<class S >
void convert_to_bool (uint32 field_pos, S src, bool &dst)
template<class S >
void convert_to_str (uint32 field_pos, S src, char *&dst)
template<class D >
void convert_from_str (uint32 field_pos, char const *src, D &dst)
void convert_str_to_bool (uint32 field_pos, char const *src, bool &dst)
void convert_str_to_str (uint32 field_pos, char const *src, char *&dst)
template<class S , class D >
void default_fill (uint32 field_pos, S src, D &dst)
void default_fill_to_str (uint32 field_pos, char const *src, char *&dst)
template<class D >
void convert_from_str (uint32 field_pos, char *src, D &dst)
void convert_str_to_str (uint32 field_pos, char *src, char *&dst)
Private Member Functions
template<class V >
void storeValue (V value, StorageClass &store, char *p, uint32 x, uint32 &offset)
void storeValue (char const *value, StorageClass &store, char *p, uint32 x, uint32 &offset)
void storeValue (char *value, StorageClass &store, char *record, uint32 field_pos, uint32 &offset)
Detailed Description
template<class DerivedLoader, class StorageClass>
class SQLStorageLoaderBase< DerivedLoader, StorageClass >
Definition at line 248 of file SQLStorage.h.
Member Function Documentation
convert()
template<class DerivedLoader , class StorageClass > template<class S , class D > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert (uint32 field_pos, S src, D & dst)
Definition at line 28 of file SQLStorageImpl.h.
convert_from_str() [1/2]
template<class DerivedLoader , class StorageClass > template<class D > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_from_str (uint32 field_pos, char * src, D & dst)
convert_from_str() [2/2]
template<class DerivedLoader , class StorageClass > template<class D > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_from_str (uint32 field_pos, char const * src, D & dst)
Definition at line 67 of file SQLStorageImpl.h.
convert_str_to_bool()
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_str_to_bool (uint32 field_pos, char const * src, bool & dst)
Definition at line 73 of file SQLStorageImpl.h.
convert_str_to_str() [1/2]
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_str_to_str (uint32 field_pos, char * src, char *& dst)
convert_str_to_str() [2/2]
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_str_to_str (uint32 field_pos, char const * src, char *& dst)
Definition at line 42 of file SQLStorageImpl.h.
convert_to_bool()
template<class DerivedLoader , class StorageClass > template<class S > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_to_bool (uint32 field_pos, S src, bool & dst)
Definition at line 35 of file SQLStorageImpl.h.
convert_to_str()
template<class DerivedLoader , class StorageClass > template<class S > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::convert_to_str (uint32 field_pos, S src, char *& dst)
Definition at line 59 of file SQLStorageImpl.h.
default_fill()
template<class DerivedLoader , class StorageClass > template<class S , class D > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::default_fill (uint32 field_pos, S src, D & dst)
Definition at line 80 of file SQLStorageImpl.h.
default_fill_to_str()
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::default_fill_to_str (uint32 field_pos, char const * src, char *& dst)
Definition at line 86 of file SQLStorageImpl.h.
Load()
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load (StorageClass & store, bool error_at_empty = true)
Definition at line 306 of file SQLStorageImpl.h.
References QueryResult::Fetch(), FT_64BITINT, FT_BYTE, FT_FLOAT, FT_IND, FT_INT, FT_LOGIC, FT_NA, FT_NA_BYTE, FT_NA_FLOAT, FT_NA_POINTER, FT_SORT, FT_STRING, QueryResult::GetFieldCount(), Field::GetUInt32(), QueryResult::NextRow(), Database::PQuery(), sLog, BarGoLink::step(), Log::WaitBeforeContinueIfNeed(), and WorldDatabase.
Referenced by SQLHashStorage::Load(), SQLMultiStorage::Load(), SQLStorage::Load(), ObjectMgr::LoadConditions(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemPrototypes(), and ObjectMgr::LoadWorldTemplate().
storeValue() [1/3]
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::storeValue (char * value, StorageClass & store, char * record, uint32 field_pos, uint32 & offset) private
storeValue() [2/3]
template<class DerivedLoader , class StorageClass > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::storeValue (char const * value, StorageClass & store, char * p, uint32 x, uint32 & offset) private
Definition at line 209 of file SQLStorageImpl.h.
References FT_BYTE, FT_FLOAT, FT_INT, FT_LOGIC, FT_NA_POINTER, and FT_STRING.
storeValue() [3/3]
template<class DerivedLoader , class StorageClass > template<class V > void SQLStorageLoaderBase< DerivedLoader, StorageClass >::storeValue (V value, StorageClass & store, char * p, uint32 x, uint32 & offset) private
Definition at line 94 of file SQLStorageImpl.h.
References FT_64BITINT, FT_BYTE, FT_FLOAT, FT_IND, FT_INT, FT_LOGIC, FT_NA, FT_NA_BYTE, FT_NA_FLOAT, FT_SORT, and FT_STRING.
The documentation for this class was generated from the following files:
SQLStorage.h
SQLStorageImpl.h