CMaNGOS_WoTLK: SpellCastArgs Class Reference
SpellCastArgs Class Reference
#include <Spell.h>
Public Member Functions
SpellCastArgs ()
SpellCastArgs & SetTarget (Unit *target)
Unit * GetTarget () const
SpellCastArgs & SetScriptValue (uint64 scriptValue)
bool IsScriptValueSet () const
uint64 GetScriptValue () const
SpellCastArgs & SetBasePoints (int32 *basePoints1, int32 *basePoints2, int32 *basePoints3)
int32 * GetBasePoints (uint32 index)
SpellCastArgs & SetDestination (float x, float y, float z)
SpellCastArgs & SetDestination (Position &position)
bool IsDestinationSet () const
Position GetDestination () const
Private Attributes
Unit * m_target
uint64 m_scriptValue
bool m_scriptValueSet
int32 * m_basePoints [3]
bool m_destinationSet
Position m_destination
Detailed Description
Definition at line 347 of file Spell.h.
Constructor & Destructor Documentation
SpellCastArgs()
SpellCastArgs::SpellCastArgs () inline
Definition at line 350 of file Spell.h.
References m_basePoints.
Member Function Documentation
GetBasePoints()
int32* SpellCastArgs::GetBasePoints (uint32 index) inline
Definition at line 369 of file Spell.h.
References m_basePoints.
Referenced by Unit::CastSpell().
GetDestination()
Position SpellCastArgs::GetDestination () const inline
Definition at line 386 of file Spell.h.
References m_destination.
Referenced by Unit::CastSpell().
GetScriptValue()
uint64 SpellCastArgs::GetScriptValue () const inline
Definition at line 360 of file Spell.h.
References m_scriptValue.
Referenced by Unit::CastSpell().
GetTarget()
Unit* SpellCastArgs::GetTarget () const inline
Definition at line 356 of file Spell.h.
References m_target.
Referenced by Unit::CastSpell().
IsDestinationSet()
bool SpellCastArgs::IsDestinationSet () const inline
Definition at line 385 of file Spell.h.
References m_destinationSet.
Referenced by Unit::CastSpell().
IsScriptValueSet()
bool SpellCastArgs::IsScriptValueSet () const inline
Definition at line 359 of file Spell.h.
References m_scriptValueSet.
Referenced by Unit::CastSpell().
SetBasePoints()
SpellCastArgs& SpellCastArgs::SetBasePoints (int32 * basePoints1, int32 * basePoints2, int32 * basePoints3) inline
Definition at line 362 of file Spell.h.
References m_basePoints.
Referenced by Aura::HandleTriggerLinkedAura(), and MojoFrenzy::OnPeriodicDummy().
SetDestination() [1/2]
SpellCastArgs& SpellCastArgs::SetDestination (float x, float y, float z) inline
Definition at line 371 of file Spell.h.
References m_destination, m_destinationSet, Position::x, Position::y, and Position::z.
SetDestination() [2/2]
SpellCastArgs& SpellCastArgs::SetDestination (Position & position) inline
Definition at line 379 of file Spell.h.
References m_destination, and m_destinationSet.
SetScriptValue()
SpellCastArgs& SpellCastArgs::SetScriptValue (uint64 scriptValue) inline
Definition at line 358 of file Spell.h.
References m_scriptValue, and m_scriptValueSet.
Referenced by PotCheck::OnEffectExecute(), and RandomIngredientAura::OnPeriodicDummy().
SetTarget()
SpellCastArgs& SpellCastArgs::SetTarget (Unit * target) inline
Definition at line 355 of file Spell.h.
References m_target.
Referenced by Aura::HandleTriggerLinkedAura(), PotCheck::OnEffectExecute(), and RandomIngredientAura::OnPeriodicDummy().
Field Documentation
m_basePoints
int32* SpellCastArgs::m_basePoints[3] private
Definition at line 391 of file Spell.h.
Referenced by GetBasePoints(), SetBasePoints(), and SpellCastArgs().
m_destination
Position SpellCastArgs::m_destination private
Definition at line 393 of file Spell.h.
Referenced by GetDestination(), and SetDestination().
m_destinationSet
bool SpellCastArgs::m_destinationSet private
Definition at line 392 of file Spell.h.
Referenced by IsDestinationSet(), and SetDestination().
m_scriptValue
uint64 SpellCastArgs::m_scriptValue private
Definition at line 389 of file Spell.h.
Referenced by GetScriptValue(), and SetScriptValue().
m_scriptValueSet
bool SpellCastArgs::m_scriptValueSet private
Definition at line 390 of file Spell.h.
Referenced by IsScriptValueSet(), and SetScriptValue().
m_target
Unit* SpellCastArgs::m_target private
Definition at line 388 of file Spell.h.
Referenced by GetTarget(), and SetTarget().
The documentation for this class was generated from the following file:
Spell.h