CMaNGOS_WoTLK: ObjectWorldLoader Class Reference
ObjectWorldLoader Class Reference
Public Member Functions
ObjectWorldLoader (ObjectGridLoader &gloader)
void Visit (CorpseMapType &m)
template<class T >
void Visit (GridRefManager< T > &)
Data Fields
uint32 i_corpses
Private Attributes
Cell i_cell
Map * i_map
Detailed Description
Definition at line 78 of file ObjectGridLoader.cpp.
Constructor & Destructor Documentation
ObjectWorldLoader()
ObjectWorldLoader::ObjectWorldLoader (ObjectGridLoader & gloader) inline explicit
Definition at line 81 of file ObjectGridLoader.cpp.
Member Function Documentation
Visit() [1/2]
void ObjectWorldLoader::Visit (CorpseMapType & m)
Definition at line 215 of file ObjectGridLoader.cpp.
References Cell::CellX(), Cell::CellY(), Map::GetId(), Map::getNGrid(), Cell::GridX(), Cell::GridY(), i_cell, i_corpses, i_map, LoadHelper(), MAX_NUMBER_OF_CELLS, sObjectMgr, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Visit() [2/2]
template<class T > void ObjectWorldLoader::Visit (GridRefManager< T > &) inline
Definition at line 87 of file ObjectGridLoader.cpp.
Field Documentation
i_cell
Cell ObjectWorldLoader::i_cell private
Definition at line 90 of file ObjectGridLoader.cpp.
Referenced by Visit().
i_corpses
uint32 ObjectWorldLoader::i_corpses
Definition at line 93 of file ObjectGridLoader.cpp.
Referenced by ObjectGridLoader::Load(), and Visit().
i_map
Map* ObjectWorldLoader::i_map private
Definition at line 91 of file ObjectGridLoader.cpp.
Referenced by Visit().
The documentation for this class was generated from the following file:
ObjectGridLoader.cpp