CMaNGOS_WoTLK: instance_utgarde_keep Class Reference
instance_utgarde_keep Class Reference
#include <utgarde_keep.h>
Public Member Functions
instance_utgarde_keep (Map *pMap)
~instance_utgarde_keep ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_bKelesethAchievFailed
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Detailed Description
Definition at line 42 of file utgarde_keep.h.
Constructor & Destructor Documentation
instance_utgarde_keep()
instance_utgarde_keep::instance_utgarde_keep (Map * pMap)
Definition at line 39 of file utgarde_keep.cpp.
References Initialize().
~instance_utgarde_keep()
instance_utgarde_keep::~instance_utgarde_keep () inline
Definition at line 46 of file utgarde_keep.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_utgarde_keep::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 257 of file utgarde_keep.cpp.
References ACHIEV_CRIT_ON_THE_ROCKS, and m_bKelesethAchievFailed.
GetData()
uint32 instance_utgarde_keep::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 227 of file utgarde_keep.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Initialize()
void instance_utgarde_keep::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 45 of file utgarde_keep.cpp.
References m_auiEncounter.
Referenced by instance_utgarde_keep().
Load()
void instance_utgarde_keep::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 235 of file utgarde_keep.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_utgarde_keep::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 50 of file utgarde_keep.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, NPC_DALRONN, NPC_INGVAR, NPC_KELESETH, and NPC_SKARVALD.
OnCreatureDeath()
void instance_utgarde_keep::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 132 of file utgarde_keep.cpp.
References Unit::CastSpell(), DoScriptText(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), m_bKelesethAchievFailed, NPC_DALRONN, NPC_FROST_TOMB, NPC_SKARVALD, Object::RemoveFlag(), SAY_DAL_DEATH, SAY_DAL_DEATH_REAL, SAY_SKA_DEATH, SAY_SKA_DEATH_REAL, SPELL_SUMMON_DAL_GHOST, SPELL_SUMMON_SKA_GHOST, TRIGGERED_OLD_TRIGGERED, UNIT_DYNAMIC_FLAGS, and UNIT_DYNFLAG_LOOTABLE.
OnCreatureRespawn()
void instance_utgarde_keep::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 63 of file utgarde_keep.cpp.
References Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_DALRONN, NPC_DALRONN_GHOST, NPC_FROST_TOMB, NPC_SKARVALD, NPC_SKARVALD_GHOST, REACT_PASSIVE, Unit::SetCanEnterCombat(), Creature::SetForceAttackingCapability(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_utgarde_keep::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 90 of file utgarde_keep.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_BELLOW_1, GO_BELLOW_2, GO_BELLOW_3, GO_FORGEFIRE_1, GO_FORGEFIRE_2, GO_FORGEFIRE_3, GO_PORTCULLIS_COMBAT, GO_PORTCULLIS_EXIT_1, GO_PORTCULLIS_EXIT_2, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), TYPE_BELLOW_1, TYPE_BELLOW_2, TYPE_BELLOW_3, and TYPE_INGVAR.
Save()
const char* instance_utgarde_keep::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 58 of file utgarde_keep.h.
References m_strInstData.
SetData()
void instance_utgarde_keep::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 178 of file utgarde_keep.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), GO_PORTCULLIS_COMBAT, GO_PORTCULLIS_EXIT_1, GO_PORTCULLIS_EXIT_2, IN_PROGRESS, m_auiEncounter, m_bKelesethAchievFailed, m_strInstData, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_BELLOW_1, TYPE_BELLOW_2, TYPE_BELLOW_3, TYPE_INGVAR, TYPE_KELESETH, and TYPE_SKARVALD_DALRONN.
Referenced by boss_kelesethAI::Aggro(), boss_ingvarAI::Aggro(), boss_ingvarAI::JustDied(), boss_kelesethAI::JustDied(), mob_dragonflayer_forge_masterAI::JustDied(), boss_ingvarAI::JustReachedHome(), and boss_kelesethAI::JustReachedHome().
Field Documentation
m_auiEncounter
uint32 instance_utgarde_keep::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 64 of file utgarde_keep.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_bKelesethAchievFailed
bool instance_utgarde_keep::m_bKelesethAchievFailed protected
Definition at line 67 of file utgarde_keep.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureDeath(), and SetData().
m_strInstData
std::string instance_utgarde_keep::m_strInstData protected
Definition at line 65 of file utgarde_keep.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
utgarde_keep.h
utgarde_keep.cpp