CMaNGOS_WoTLK: TimerManager Class Reference
TimerManager Class Reference
#include <TimerAI.h>
Public Member Functions
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Protected Member Functions
void AddTimer (uint32 id, Timer &&timer)
Private Attributes
std::map< uint32, Timer > m_timers
Detailed Description
Definition at line 63 of file TimerAI.h.
Constructor & Destructor Documentation
TimerManager()
TimerManager::TimerManager () inline
Definition at line 66 of file TimerAI.h.
Member Function Documentation
AddCustomAction() [1/5]
void TimerManager::AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat = TIMER_ALWAYS)
Definition at line 56 of file TimerAI.cpp.
References m_timers.
Referenced by boss_ahuneAI::boss_ahuneAI(), boss_akilzonAI::boss_akilzonAI(), boss_alarAI::boss_alarAI(), boss_alythessAI::boss_alythessAI(), boss_anetheronAI::boss_anetheronAI(), boss_anubrekhanAI::boss_anubrekhanAI(), boss_anzuAI::boss_anzuAI(), boss_aranAI::boss_aranAI(), boss_arlokkAI::boss_arlokkAI(), boss_attumenAI::boss_attumenAI(), boss_black_stalkerAI::boss_black_stalkerAI(), boss_blackheart_the_inciterAI::boss_blackheart_the_inciterAI(), boss_brutallusAI::boss_brutallusAI(), boss_buruAI::boss_buruAI(), boss_coren_direbrewAI::boss_coren_direbrewAI(), boss_cthunAI::boss_cthunAI(), boss_deathbringer_saurfangAI::boss_deathbringer_saurfangAI(), boss_dorotheeAI::boss_dorotheeAI(), boss_drakkari_colossusAI::boss_drakkari_colossusAI(), boss_entropiusAI::boss_entropiusAI(), boss_essence_of_angerAI::boss_essence_of_angerAI(), boss_eye_of_cthunAI::boss_eye_of_cthunAI(), boss_felblood_kaelthasAI::boss_felblood_kaelthasAI(), boss_felmystAI::boss_felmystAI(), boss_gluthAI::boss_gluthAI(), boss_gothikAI::boss_gothikAI(), boss_heiganAI::boss_heiganAI(), boss_high_astromancer_solarianAI::boss_high_astromancer_solarianAI(), boss_high_inquisitor_whitemaneAI::boss_high_inquisitor_whitemaneAI(), boss_illidan_stormrageAI::boss_illidan_stormrageAI(), boss_janalaiAI::boss_janalaiAI(), boss_jeklikAI::boss_jeklikAI(), boss_kalecgos_humanoidAI::boss_kalecgos_humanoidAI(), boss_kalecgosAI::boss_kalecgosAI(), boss_kelidan_the_breakerAI::boss_kelidan_the_breakerAI(), boss_kelthuzadAI::boss_kelthuzadAI(), boss_kiljaedenAI::boss_kiljaedenAI(), boss_kurinnaxxAI::boss_kurinnaxxAI(), boss_lady_vashjAI::boss_lady_vashjAI(), boss_leotheras_the_blindAI::boss_leotheras_the_blindAI(), boss_magtheridonAI::boss_magtheridonAI(), boss_maievAI::boss_maievAI(), boss_majordomoAI::boss_majordomoAI(), boss_moamAI::boss_moamAI(), boss_moorabiAI::boss_moorabiAI(), boss_moroesAI::boss_moroesAI(), boss_muruAI::boss_muruAI(), boss_nefarianAI::boss_nefarianAI(), boss_nightbaneAI::boss_nightbaneAI(), boss_omor_the_unscarredAI::boss_omor_the_unscarredAI(), boss_ouroAI::boss_ouroAI(), boss_ragnarosAI::boss_ragnarosAI(), boss_reliquary_of_soulsAI::boss_reliquary_of_soulsAI(), boss_renatakiAI::boss_renatakiAI(), boss_sacrolashAI::boss_sacrolashAI(), boss_sartharionAI::boss_sartharionAI(), boss_scarlet_commander_mograineAI::boss_scarlet_commander_mograineAI(), boss_silithidRoyaltyAI::boss_silithidRoyaltyAI(), boss_skadiAI::boss_skadiAI(), boss_skeramAI::boss_skeramAI(), boss_supremusAI::boss_supremusAI(), boss_talon_king_ikissAI::boss_talon_king_ikissAI(), boss_telestraAI::boss_telestraAI(), boss_terokkAI::boss_terokkAI(), boss_thaddiusAddsAI::boss_thaddiusAddsAI(), boss_the_lurker_belowAI::boss_the_lurker_belowAI(), boss_thekalAI::boss_thekalAI(), boss_twin_emperorsAI::boss_twin_emperorsAI(), boss_vaelastraszAI::boss_vaelastraszAI(), boss_vazruden_heraldAI::boss_vazruden_heraldAI(), boss_veras_darkshadowAI::boss_veras_darkshadowAI(), boss_viscidusAI::boss_viscidusAI(), boss_yorAI::boss_yorAI(), boss_zuljinAI::boss_zuljinAI(), BossAI::BossAI(), BrewfestEvent::BrewfestEvent(), ChildTbcAI::ChildTbcAI(), CombatAI::CombatAI(), DarkFiendAI::DarkFiendAI(), essence_base_AI::essence_base_AI(), hyjalAI::hyjalAI(), instance_sunwell_plateau::Initialize(), world_map_outland::Initialize(), boss_nothAI::JustSummoned(), LadyDeathwhisperElevator::LadyDeathwhisperElevator(), MinionspawnerAI::MinionspawnerAI(), mob_arugal_voidwalkerAI::mob_arugal_voidwalkerAI(), mob_hellfire_channelerAI::mob_hellfire_channelerAI(), mob_illidari_councilAI::mob_illidari_councilAI(), mob_phoenix_tkAI::mob_phoenix_tkAI(), mob_shadowmoon_channelerAI::mob_shadowmoon_channelerAI(), mob_torlothAI::mob_torlothAI(), mob_water_globuleAI::mob_water_globuleAI(), mob_zealot_lorkhanAI::mob_zealot_lorkhanAI(), mob_zealot_zathAI::mob_zealot_zathAI(), MouthAI::MouthAI(), npc_ethereal_frostworgAI::MovementInform(), NecropolisHealthAI::NecropolisHealthAI(), NecroticShard::NecroticShard(), NetherCharge::NetherCharge(), npc_aether_tech_vendorAI::npc_aether_tech_vendorAI(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_aoe_damage_triggerAI::npc_aoe_damage_triggerAI(), npc_bashir_flesh_fiendAI::npc_bashir_flesh_fiendAI(), npc_bonechewer_combatant::npc_bonechewer_combatant(), npc_burster_wormAI::npc_burster_wormAI(), npc_caribdis_cyclone::npc_caribdis_cyclone(), npc_commander_arcusAI::npc_commander_arcusAI(), npc_commanderAI::npc_commanderAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_creature_generatorAI::npc_creature_generatorAI(), npc_cultist_engineer::npc_cultist_engineer(), npc_daphne_stilwellAI::npc_daphne_stilwellAI(), npc_darknessAI::npc_darknessAI(), npc_dawnblade_blood_knight::npc_dawnblade_blood_knight(), npc_demonic_vaporAI::npc_demonic_vaporAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_doom_blossomAI::npc_doom_blossomAI(), npc_doomguard_punisherAI::npc_doomguard_punisherAI(), npc_dreadmawAI::npc_dreadmawAI(), npc_enslaved_soulAI::npc_enslaved_soulAI(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), npc_ethereal_sphereAI::npc_ethereal_sphereAI(), npc_ethereum_prisoner_dungeonAI::npc_ethereum_prisoner_dungeonAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_eye_of_shartuulAI::npc_eye_of_shartuulAI(), npc_feather_vortexAI::npc_feather_vortexAI(), npc_fire_nova_totemAI::npc_fire_nova_totemAI(), npc_flame_of_azzinothAI::npc_flame_of_azzinothAI(), npc_flame_tsunamiAI::npc_flame_tsunamiAI(), npc_general_andorovAI::npc_general_andorovAI(), npc_grand_collectorAI::npc_grand_collectorAI(), npc_kagani_nightstrikeAI::npc_kagani_nightstrikeAI(), npc_kalecgosAI::npc_kalecgosAI(), npc_khadgars_servantAI::npc_khadgars_servantAI(), npc_krunAI::npc_krunAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_nerubian_burrowerAI::npc_nerubian_burrowerAI(), npc_nether_vaporAI::npc_nether_vaporAI(), npc_ouro_moundAI::npc_ouro_moundAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), npc_razorthorn_ravager_pet::npc_razorthorn_ravager_pet(), npc_shadow_constructAI::npc_shadow_constructAI(), npc_shadowfang_prisonerAI::npc_shadowfang_prisonerAI(), npc_shartuulAI::npc_shartuulAI(), npc_shivan_assassinAI::npc_shivan_assassinAI(), npc_singularityAI::npc_singularityAI(), npc_sinister_reflectionAI::npc_sinister_reflectionAI(), npc_theramore_spar_controller::npc_theramore_spar_controller(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), instance_ulduar::OnCreatureRespawn(), OuroScarab::OuroScarab(), PallidHorrorAI::PallidHorrorAI(), PlayerAI::PlayerAI(), npc_shattered_hand_legionnaire::Reset(), ScourgeMinion::ScourgeMinion(), TorchTossingTargetBunnyControllerAI::TorchTossingTargetBunnyControllerAI(), and UnitAI::UnitAI().
AddCustomAction() [2/5]
void TimerManager::AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat = TIMER_ALWAYS) inline
Definition at line 71 of file TimerAI.h.
AddCustomAction() [3/5]
void TimerManager::AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat = TIMER_ALWAYS) inline
Definition at line 76 of file TimerAI.h.
AddCustomAction() [4/5]
void TimerManager::AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat = TIMER_ALWAYS)
Definition at line 61 of file TimerAI.cpp.
References m_timers.
AddCustomAction() [5/5]
void TimerManager::AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat = TIMER_ALWAYS)
Definition at line 66 of file TimerAI.cpp.
References m_timers.
AddTimer()
void TimerManager::AddTimer (uint32 id, Timer && timer) protected
Definition at line 51 of file TimerAI.cpp.
References m_timers.
DelayTimer() [1/2]
virtual void TimerManager::DelayTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented in CombatActions.
Definition at line 93 of file TimerAI.h.
DelayTimer() [2/2]
void TimerManager::DelayTimer (uint32 index, uint32 timer) virtual
Reimplemented in CombatActions.
Definition at line 104 of file TimerAI.cpp.
References m_timers, and sLog.
Referenced by CombatActions::DelayTimer().
DisableTimer()
void TimerManager::DisableTimer (uint32 index) virtual
Reimplemented in CombatActions.
Definition at line 82 of file TimerAI.cpp.
References m_timers, and sLog.
Referenced by CombatActions::DisableTimer(), world_map_outland::FinishPhase(), and world_map_outland::ProgressShartuul().
GetAIInformation()
void TimerManager::GetAIInformation (ChatHandler & reader) virtual
Reimplemented in boss_kaelthasAI, npc_commanderAI, npc_simon_game_bunnyAI, boss_illidan_stormrageAI, npc_anubisath_sentinelAI, npc_arthasAI, boss_kiljaedenAI, boss_brutallusAI, mob_arugal_voidwalkerAI, npc_highlord_darion_mograineAI, boss_thermapluggAI, Scripted_NoMovementAI, ScriptedAI, CombatActions, npc_escortAI, CreatureEventAI, and UnitAI.
Definition at line 152 of file TimerAI.cpp.
References Timer::disabled, Timer::id, m_timers, ChatHandler::PSendSysMessage(), and Timer::timer.
ReduceTimer() [1/2]
virtual void TimerManager::ReduceTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented in CombatActions.
Definition at line 88 of file TimerAI.h.
ReduceTimer() [2/2]
void TimerManager::ReduceTimer (uint32 index, uint32 timer) virtual
Reimplemented in CombatActions.
Definition at line 93 of file TimerAI.cpp.
References m_timers, and sLog.
Referenced by CombatActions::ReduceTimer().
ResetAllTimers()
void TimerManager::ResetAllTimers () virtual
Reimplemented in CombatActions.
Definition at line 146 of file TimerAI.cpp.
References m_timers.
Referenced by CombatActions::ResetAllTimers().
ResetIfNotStarted() [1/2]
virtual void TimerManager::ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented in CombatActions.
Definition at line 98 of file TimerAI.h.
ResetIfNotStarted() [2/2]
void TimerManager::ResetIfNotStarted (uint32 index, uint32 timer) virtual
Reimplemented in CombatActions.
Definition at line 116 of file TimerAI.cpp.
References m_timers, and sLog.
Referenced by CombatActions::ResetIfNotStarted().
ResetTimer() [1/2]
virtual void TimerManager::ResetTimer (uint32 index, std::chrono::milliseconds timer) inline virtual
Reimplemented in CombatActions.
Definition at line 82 of file TimerAI.h.
ResetTimer() [2/2]
void TimerManager::ResetTimer (uint32 index, uint32 timer) virtual
Reimplemented in CombatActions.
Definition at line 71 of file TimerAI.cpp.
References m_timers, and sLog.
Referenced by world_map_outland::HandleBashirEnemyAttack(), world_map_outland::HandleBashirSpawnEnemy(), BrewfestEvent::HandleKegTappingEvent(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulSpawnSequence(), LadyDeathwhisperElevator::JustReachedStopPoint(), world_map_outland::ProgressShartuul(), CombatActions::ResetTimer(), world_map_outland::ScriptAction(), world_map_outland::SetData(), instance_sunwell_plateau::SetData(), world_map_outland::StartBashirLandingEvent(), world_map_outland::StartBattlePhase(), instance_sunwell_plateau::StartImps(), and world_map_outland::StartPhase().
UpdateTimers() [1/2]
void TimerManager::UpdateTimers (const uint32 diff) virtual
Reimplemented in npc_adyen_the_lightwardenAI, and npc_scrap_reaverAI.
Definition at line 131 of file TimerAI.cpp.
Referenced by BrewfestEvent::Update(), instance_sunwell_plateau::Update(), world_map_outland::Update(), LadyDeathwhisperElevator::UpdateAI(), and CombatActions::UpdateTimers().
UpdateTimers() [2/2]
void TimerManager::UpdateTimers (const uint32 diff, bool combat) virtual
Reimplemented in CombatActions.
Definition at line 136 of file TimerAI.cpp.
References Timer::functor, m_timers, and Timer::UpdateTimer().
Field Documentation
m_timers
std::map<uint32, Timer> TimerManager::m_timers private
Definition at line 113 of file TimerAI.h.
Referenced by AddCustomAction(), AddTimer(), DelayTimer(), DisableTimer(), GetAIInformation(), ReduceTimer(), ResetAllTimers(), ResetIfNotStarted(), ResetTimer(), and UpdateTimers().
The documentation for this class was generated from the following files:
TimerAI.h
TimerAI.cpp