CMaNGOS_WoTLK: instance_draktharon_keep Class Reference
instance_draktharon_keep Class Reference
#include <draktharon_keep.h>
Public Member Functions
instance_draktharon_keep (Map *pMap)
~instance_draktharon_keep ()
void Initialize () override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature)
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void GetTrollgoreOutsideTriggers (GuidVector &vTriggers) const
ObjectGuid GetTrollgoreCornerTrigger () const
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
const char * Save () const override
void Load (const char *chrIn) override
Creature * GetNextCrystalTarget (Creature *pCrystalHandler, uint8 &uiIndex) const
void DoHandleCrystal (uint8 uiIndex)
Creature * GetSummonDummy ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoSortNovosDummies ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiDreadAddsKilled
bool m_bNovosAddGrounded
bool m_bTrollgoreConsume
ObjectGuid m_novosChannelGuid
ObjectGuid m_trollgoreCornerTriggerGuid
NovosCrystalInfo m_aNovosCrystalInfo [MAX_CRYSTALS]
GuidVector m_vSummonDummyGuids
GuidList m_lNovosDummyGuids
GuidVector m_vTriggerGuids
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 61 of file draktharon_keep.h.
Constructor & Destructor Documentation
instance_draktharon_keep()
instance_draktharon_keep::instance_draktharon_keep (Map * pMap)
Definition at line 27 of file instance_draktharon_keep.cpp.
References Initialize().
~instance_draktharon_keep()
instance_draktharon_keep::~instance_draktharon_keep () inline
Definition at line 65 of file draktharon_keep.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_draktharon_keep::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 225 of file instance_draktharon_keep.cpp.
References ACHIEV_CRIT_BETTER_OFF_DREAD, ACHIEV_CRIT_CONSUME_JUNCTION, ACHIEV_CRIT_OH_NOVOS, m_bNovosAddGrounded, m_bTrollgoreConsume, and m_uiDreadAddsKilled.
DoHandleCrystal()
void instance_draktharon_keep::DoHandleCrystal (uint8 uiIndex)
Definition at line 207 of file instance_draktharon_keep.cpp.
References ScriptedInstance::DoUseDoorOrButton(), Map::GetCreature(), InstanceData::instance, m_aNovosCrystalInfo, NovosCrystalInfo::m_bWasUsed, and NovosCrystalInfo::m_channelGuid.
DoSortNovosDummies()
void instance_draktharon_keep::DoSortNovosDummies () protected
Definition at line 102 of file instance_draktharon_keep.cpp.
References Map::GetCreature(), Map::GetGameObject(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), Creature::GetRespawnCoord(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, INTERACTION_DISTANCE, WorldObject::IsWithinDist2d(), WorldObject::IsWithinDistInMap(), m_aNovosCrystalInfo, m_lNovosDummyGuids, m_novosChannelGuid, m_vSummonDummyGuids, and NPC_NOVOS.
Referenced by SetData().
GetData()
uint32 instance_draktharon_keep::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 334 of file instance_draktharon_keep.cpp.
References m_auiEncounter, TYPE_KING_DRED, TYPE_NOVOS, TYPE_THARONJA, and TYPE_TROLLGORE.
Referenced by boss_novosAI::MoveInLineOfSight().
GetNextCrystalTarget()
Creature * instance_draktharon_keep::GetNextCrystalTarget (Creature * pCrystalHandler, uint8 & uiIndex) const
Definition at line 187 of file instance_draktharon_keep.cpp.
References aCrystalHandlerDeathSpells, Map::GetCreature(), WorldObject::GetDistanceOrder(), Unit::HasAura(), InstanceData::instance, m_aNovosCrystalInfo, and MAX_CRYSTALS.
Referenced by boss_novosAI::SummonedCreatureJustDied().
GetSummonDummy()
Creature * instance_draktharon_keep::GetSummonDummy ()
Definition at line 217 of file instance_draktharon_keep.cpp.
References Map::GetCreature(), InstanceData::instance, m_vSummonDummyGuids, and urand().
Referenced by boss_novosAI::UpdateAI().
GetTrollgoreCornerTrigger()
ObjectGuid instance_draktharon_keep::GetTrollgoreCornerTrigger () const inline
Definition at line 80 of file draktharon_keep.h.
References m_trollgoreCornerTriggerGuid.
Referenced by boss_trollgoreAI::DoSummonDrakkariInvaders().
GetTrollgoreOutsideTriggers()
void instance_draktharon_keep::GetTrollgoreOutsideTriggers (GuidVector & vTriggers) const inline
Definition at line 79 of file draktharon_keep.h.
References m_vTriggerGuids.
Referenced by boss_trollgoreAI::Aggro().
Initialize()
void instance_draktharon_keep::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 35 of file instance_draktharon_keep.cpp.
References m_auiEncounter.
Referenced by instance_draktharon_keep().
Load()
void instance_draktharon_keep::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 312 of file instance_draktharon_keep.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_draktharon_keep::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 72 of file instance_draktharon_keep.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), m_lNovosDummyGuids, ScriptedInstance::m_npcEntryGuidStore, m_trollgoreCornerTriggerGuid, m_vTriggerGuids, NPC_CRYSTAL_CHANNEL_TARGET, NPC_NOVOS, and NPC_WORLD_TRIGGER.
OnCreatureDeath()
void instance_draktharon_keep::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 63 of file instance_draktharon_keep.cpp.
References DONE, Object::GetEntry(), IN_PROGRESS, m_auiEncounter, m_uiDreadAddsKilled, NPC_DRAKKARI_GUTRIPPER, NPC_DRAKKARI_SCYTHECLAW, NPC_KING_DRED, SetData(), and TYPE_KING_DRED.
OnCreatureEnterCombat()
void instance_draktharon_keep::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 40 of file instance_draktharon_keep.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_KING_DRED, SetData(), and TYPE_KING_DRED.
OnCreatureEvade()
void instance_draktharon_keep::OnCreatureEvade (Creature * pCreature) virtual
Reimplemented from InstanceData.
Definition at line 46 of file instance_draktharon_keep.cpp.
References FAIL, Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_CRYSTAL_HANDLER, NPC_FETID_TROLL_CORPSE, NPC_HULKING_CORPSE, NPC_KING_DRED, NPC_NOVOS, NPC_RISON_SHADOWCASTER, SetData(), and TYPE_KING_DRED.
OnObjectCreate()
void instance_draktharon_keep::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 91 of file instance_draktharon_keep.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_CRYSTAL_NE, GO_CRYSTAL_NW, GO_CRYSTAL_SE, GO_CRYSTAL_SW, m_aNovosCrystalInfo, and NovosCrystalInfo::m_crystalGuid.
Save()
const char* instance_draktharon_keep::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 84 of file draktharon_keep.h.
References m_strInstData.
SetData()
void instance_draktharon_keep::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 237 of file instance_draktharon_keep.cpp.
References Unit::CastSpell(), DONE, DoSortNovosDummies(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), IN_PROGRESS, InstanceData::instance, Unit::InterruptNonMeleeSpells(), m_aNovosCrystalInfo, m_auiEncounter, m_bNovosAddGrounded, m_bTrollgoreConsume, m_novosChannelGuid, m_strInstData, m_uiDreadAddsKilled, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, SPELL_BEAM_CHANNEL, TRIGGERED_NONE, TYPE_KING_DRED, TYPE_NOVOS, TYPE_THARONJA, and TYPE_TROLLGORE.
Referenced by boss_novosAI::Aggro(), boss_trollgoreAI::Aggro(), boss_novosAI::JustDied(), boss_trollgoreAI::JustDied(), boss_novosAI::JustReachedHome(), boss_trollgoreAI::JustReachedHome(), boss_novosAI::MoveInLineOfSight(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), and boss_trollgoreAI::SpellHit().
Field Documentation
m_aNovosCrystalInfo
NovosCrystalInfo instance_draktharon_keep::m_aNovosCrystalInfo[MAX_CRYSTALS] protected
Definition at line 104 of file draktharon_keep.h.
Referenced by DoHandleCrystal(), DoSortNovosDummies(), GetNextCrystalTarget(), OnObjectCreate(), and SetData().
m_auiEncounter
uint32 instance_draktharon_keep::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 94 of file draktharon_keep.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureDeath(), and SetData().
m_bNovosAddGrounded
bool instance_draktharon_keep::m_bNovosAddGrounded protected
Definition at line 98 of file draktharon_keep.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_bTrollgoreConsume
bool instance_draktharon_keep::m_bTrollgoreConsume protected
Definition at line 99 of file draktharon_keep.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_lNovosDummyGuids
GuidList instance_draktharon_keep::m_lNovosDummyGuids protected
Definition at line 107 of file draktharon_keep.h.
Referenced by DoSortNovosDummies(), and OnCreatureCreate().
m_novosChannelGuid
ObjectGuid instance_draktharon_keep::m_novosChannelGuid protected
Definition at line 101 of file draktharon_keep.h.
Referenced by DoSortNovosDummies(), and SetData().
m_strInstData
std::string instance_draktharon_keep::m_strInstData protected
Definition at line 95 of file draktharon_keep.h.
Referenced by Save(), and SetData().
m_trollgoreCornerTriggerGuid
ObjectGuid instance_draktharon_keep::m_trollgoreCornerTriggerGuid protected
Definition at line 102 of file draktharon_keep.h.
Referenced by GetTrollgoreCornerTrigger(), and OnCreatureCreate().
m_uiDreadAddsKilled
uint32 instance_draktharon_keep::m_uiDreadAddsKilled protected
Definition at line 97 of file draktharon_keep.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureDeath(), and SetData().
m_vSummonDummyGuids
GuidVector instance_draktharon_keep::m_vSummonDummyGuids protected
Definition at line 106 of file draktharon_keep.h.
Referenced by DoSortNovosDummies(), and GetSummonDummy().
m_vTriggerGuids
GuidVector instance_draktharon_keep::m_vTriggerGuids protected
Definition at line 108 of file draktharon_keep.h.
Referenced by GetTrollgoreOutsideTriggers(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
draktharon_keep.h
instance_draktharon_keep.cpp