CMaNGOS_WoTLK: CinematicMgr Class Reference
CinematicMgr Class Reference
#include <CinematicMgr.h>
Public Member Functions
CinematicMgr (Player *playerref)
~CinematicMgr ()
uint32 GetActiveCinematicCamera () const
void SetActiveCinematicCamera (uint32 cinematicCameraId=0)
bool IsOnCinematic () const
void BeginCinematic ()
void EndCinematic ()
bool UpdateCinematicLocation (uint32 diff)
Protected Attributes
uint32 m_cinematicDiff
uint32 m_lastCinematicCheck
uint32 m_activeCinematicCameraId
uint32 m_cinematicLength
FlyByCameraCollection * m_cinematicCamera
Position m_remoteSightPosition
Creature * m_CinematicObject
Private Attributes
Player * player
Friends
class Player
Detailed Description
Definition at line 33 of file CinematicMgr.h.
Constructor & Destructor Documentation
CinematicMgr()
CinematicMgr::CinematicMgr (Player * playerref) explicit
Definition at line 22 of file CinematicMgr.cpp.
References m_activeCinematicCameraId, m_cinematicCamera, m_cinematicDiff, m_cinematicLength, m_CinematicObject, m_lastCinematicCheck, m_remoteSightPosition, and player.
~CinematicMgr()
CinematicMgr::~CinematicMgr ()
Definition at line 34 of file CinematicMgr.cpp.
References EndCinematic(), m_activeCinematicCameraId, and m_cinematicCamera.
Member Function Documentation
BeginCinematic()
void CinematicMgr::BeginCinematic ()
Definition at line 40 of file CinematicMgr.cpp.
References Map::ForceLoadGrid(), Player::GetCamera(), WorldObject::GetMap(), IN_MILLISECONDS, MaNGOS::IsValidMapCoord(), m_activeCinematicCameraId, m_cinematicCamera, m_cinematicDiff, m_cinematicLength, m_CinematicObject, MINUTE, player, WorldObject::SetActiveObjectState(), Camera::SetView(), sFlyByCameraStore, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, VISUAL_WAYPOINT, and Position::x.
EndCinematic()
void CinematicMgr::EndCinematic ()
Definition at line 78 of file CinematicMgr.cpp.
References WorldObject::AddObjectToRemoveList(), Camera::GetBody(), Player::GetCamera(), m_activeCinematicCameraId, m_cinematicCamera, m_cinematicDiff, m_CinematicObject, player, and Camera::ResetView().
Referenced by UpdateCinematicLocation(), and ~CinematicMgr().
GetActiveCinematicCamera()
uint32 CinematicMgr::GetActiveCinematicCamera () const inline
Definition at line 41 of file CinematicMgr.h.
References m_activeCinematicCameraId.
IsOnCinematic()
bool CinematicMgr::IsOnCinematic () const inline
Definition at line 43 of file CinematicMgr.h.
References m_cinematicCamera.
SetActiveCinematicCamera()
void CinematicMgr::SetActiveCinematicCamera (uint32 cinematicCameraId = 0) inline
Definition at line 42 of file CinematicMgr.h.
References m_activeCinematicCameraId.
UpdateCinematicLocation()
bool CinematicMgr::UpdateCinematicLocation (uint32 diff)
Definition at line 96 of file CinematicMgr.cpp.
References CINEMATIC_LOOKAHEAD, EndCinematic(), IN_MILLISECONDS, MaNGOS::IsValidMapCoord(), m_activeCinematicCameraId, m_cinematicCamera, m_cinematicDiff, m_cinematicLength, m_CinematicObject, M_PI, Unit::MonsterMoveWithSpeed(), Position::o, Position::x, Position::y, and Position::z.
Friends And Related Function Documentation
Player
friend class Player friend
Definition at line 35 of file CinematicMgr.h.
Field Documentation
m_activeCinematicCameraId
uint32 CinematicMgr::m_activeCinematicCameraId protected
Definition at line 55 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), EndCinematic(), GetActiveCinematicCamera(), SetActiveCinematicCamera(), UpdateCinematicLocation(), and ~CinematicMgr().
m_cinematicCamera
FlyByCameraCollection* CinematicMgr::m_cinematicCamera protected
Definition at line 57 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), EndCinematic(), IsOnCinematic(), UpdateCinematicLocation(), and ~CinematicMgr().
m_cinematicDiff
uint32 CinematicMgr::m_cinematicDiff protected
Definition at line 53 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), EndCinematic(), and UpdateCinematicLocation().
m_cinematicLength
uint32 CinematicMgr::m_cinematicLength protected
Definition at line 56 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), and UpdateCinematicLocation().
m_CinematicObject
Creature* CinematicMgr::m_CinematicObject protected
Definition at line 59 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), EndCinematic(), and UpdateCinematicLocation().
m_lastCinematicCheck
uint32 CinematicMgr::m_lastCinematicCheck protected
Definition at line 54 of file CinematicMgr.h.
Referenced by CinematicMgr().
m_remoteSightPosition
Position CinematicMgr::m_remoteSightPosition protected
Definition at line 58 of file CinematicMgr.h.
Referenced by CinematicMgr().
player
Player* CinematicMgr::player private
Definition at line 50 of file CinematicMgr.h.
Referenced by BeginCinematic(), CinematicMgr(), EndCinematic(), and Player::IsInDuelWith().
The documentation for this class was generated from the following files:
CinematicMgr.h
CinematicMgr.cpp