CMaNGOS_WoTLK: instance_mount_hyjal Class Reference
instance_mount_hyjal Class Reference
#include <hyjal.h>
Public Member Functions
instance_mount_hyjal (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnPlayerDeath (Player *player) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void StartEvent (HyjalEvents eventId)
void FailEvent ()
GuidVector GetOverrunSpawns (uint32 baseId)
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void SpawnNextWave ()
void SpawnNextInvasionWave ()
void SpawnWave (uint32 index, bool setTimer)
void SpawnWaveInfernals (uint32 index)
void SpawnInvasionInfernals (uint32 index)
void SpawnInfernals (uint32 count)
void SpawnInfernal ()
void SpawnOres (BaseArea index)
void SpawnInvasionWave (uint32 index, bool setTimer)
void SpawnArchimonde ()
void DespawnWaveSpawns ()
void DespawnBase (BaseArea index)
void SpawnBase (BaseArea index, bool spawnLeader)
void RetreatBase (BaseArea index)
void OverrunBase (BaseArea index)
void DespawnOverrun (BaseArea index)
void RestartEvent ()
Private Attributes
uint32 m_encounter [MAX_ENCOUNTER]
std::string m_saveData
GuidVector m_ancientGems [MAX_BASE - 1]
GuidVector m_roaringFlames [MAX_BASE - 1]
GuidVector m_waveSpawns
GuidVector m_baseSpawns [MAX_BASE]
GuidVector m_overrunSpawns [MAX_BASE]
GuidVector m_additionalSpawns
uint32 m_hyjalWaves
uint32 m_invasionWaves
uint32 m_nextWaveTimer
uint32 m_nextInvasionWaveTimer
uint32 m_retreatTimer
uint32 m_infernalsTimer
uint32 m_infernalsCounter
uint32 m_failTimer
bool m_startCheck
GuidVector m_infernalRelays
GuidVector m_infernalTargets
std::vector< uint32 > m_infernalIndices
Static Private Attributes
static std::array< HyjalWave, MAX_WAVES > m_hyjalWavesData = InitHyjalWaves()
static std::array< InvasionWave, MAX_INVASION_WAVES > m_invasionWavesData = InitInvasionWaves()
Friends
class ChatHandler
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 160 of file hyjal.h.
Constructor & Destructor Documentation
instance_mount_hyjal()
instance_mount_hyjal::instance_mount_hyjal (Map * pMap)
Definition at line 36 of file hyjal.cpp.
References Initialize().
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_mount_hyjal::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 1845 of file hyjal.cpp.
References DONE, FAIL, GetData(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_ANETHERON_DONE, INSTANCE_CONDITION_ID_ANETHERON_STARTABLE, INSTANCE_CONDITION_ID_ARCHIMONDE_DONE, INSTANCE_CONDITION_ID_ARCHIMONDE_STARTABLE, INSTANCE_CONDITION_ID_AZGALOR_DONE, INSTANCE_CONDITION_ID_AZGALOR_STARTABLE, INSTANCE_CONDITION_ID_KAZROGAL_STARTABLE, INSTANCE_CONDITION_ID_WAVES_INPROGRESS, INSTANCE_CONDITION_ID_WINTERCHILL_STARTABLE, m_waveSpawns, NOT_STARTED, script_error_log(), TYPE_ANETHERON, TYPE_ARCHIMONDE, TYPE_AZGALOR, TYPE_KAZROGAL, and TYPE_WINTERCHILL.
DespawnBase()
void instance_mount_hyjal::DespawnBase (BaseArea index) private
Definition at line 1515 of file hyjal.cpp.
References BASE_ALLY, BASE_HORDE, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_baseSpawns, NPC_JAINA, and NPC_THRALL.
Referenced by ExecuteChatCommand(), FailEvent(), and SetData().
DespawnOverrun()
void instance_mount_hyjal::DespawnOverrun (BaseArea index) private
Definition at line 1627 of file hyjal.cpp.
References BASE_ELF, Map::GetCreature(), InstanceData::instance, and m_overrunSpawns.
Referenced by ExecuteChatCommand(), and SetData().
DespawnWaveSpawns()
void instance_mount_hyjal::DespawnWaveSpawns () private
Definition at line 1506 of file hyjal.cpp.
References ScriptedInstance::DespawnGuids(), Map::GetVariableManager(), InstanceData::instance, m_additionalSpawns, m_waveSpawns, WorldStateVariableManager::SetVariable(), WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by ExecuteChatCommand(), FailEvent(), and SetData().
ExecuteChatCommand()
void instance_mount_hyjal::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 1734 of file hyjal.cpp.
References DespawnBase(), DespawnOverrun(), DespawnWaveSpawns(), ChatHandler::ExtractLiteralArg(), ChatHandler::ExtractUInt32(), ScriptedInstance::GetSingleCreatureFromStorage(), MAX_BASE, MAX_WAVES, NPC_JAINA, NPC_THRALL, OverrunBase(), ChatHandler::PSendSysMessage(), RetreatBase(), SpawnArchimonde(), SpawnBase(), SpawnInfernals(), and SpawnWave().
FailEvent()
void instance_mount_hyjal::FailEvent ()
Definition at line 1640 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, DespawnBase(), DespawnWaveSpawns(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetVariableManager(), InstanceData::instance, m_failTimer, m_hyjalWaves, m_nextWaveTimer, NPC_JAINA, NPC_THRALL, SetData(), WorldStateVariableManager::SetVariable(), TYPE_ANETHERON, TYPE_AZGALOR, TYPE_KAZROGAL, TYPE_WINTERCHILL, WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by OnCreatureDeath(), SpawnWave(), and Update().
GetData()
uint32 instance_mount_hyjal::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 1148 of file hyjal.cpp.
References m_encounter, TYPE_ANETHERON, TYPE_ARCHIMONDE, TYPE_AZGALOR, TYPE_KAZROGAL, and TYPE_WINTERCHILL.
Referenced by CheckConditionCriteriaMeet(), OnObjectCreate(), OnPlayerDeath(), OnPlayerEnter(), RestartEvent(), and SetData().
GetOverrunSpawns()
GuidVector instance_mount_hyjal::GetOverrunSpawns (uint32 baseId) inline
Definition at line 192 of file hyjal.h.
References m_overrunSpawns.
Initialize()
void instance_mount_hyjal::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 824 of file hyjal.cpp.
References Map::GetVariableManager(), InstanceData::instance, m_encounter, WorldStateVariableManager::SetVariableData(), WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by instance_mount_hyjal().
IsEncounterInProgress()
bool instance_mount_hyjal::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 832 of file hyjal.cpp.
References IN_PROGRESS, m_encounter, and MAX_ENCOUNTER.
Load()
void instance_mount_hyjal::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 1252 of file hyjal.cpp.
References DONE, IN_PROGRESS, m_encounter, m_hyjalWaves, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, TYPE_ANETHERON, TYPE_AZGALOR, TYPE_KAZROGAL, and TYPE_WINTERCHILL.
OnCreatureCreate()
void instance_mount_hyjal::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 893 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, Object::GetEntry(), ObjectGuid::GetEntry(), Object::GetObjectGuid(), WorldObject::GetSpawnerGuid(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), IN_PROGRESS, InstanceData::instance, m_additionalSpawns, m_baseSpawns, m_infernalRelays, m_infernalTargets, ScriptedInstance::m_npcEntryGuidStore, m_waveSpawns, NPC_ABOMI, NPC_ALLIANCE_FOOTMAN, NPC_ALLIANCE_KNIGHT, NPC_ALLIANCE_PEASANT, NPC_ALLIANCE_PRIEST, NPC_ALLIANCE_RIFLEMAN, NPC_ALLIANCE_SORCERESS, NPC_ANETHERON, NPC_ARCHIMONDE, NPC_AZGALOR, NPC_BANSH, NPC_CRYPT, NPC_DIRE_WOLF, NPC_DRUID_OF_THE_CLAW, NPC_DRUID_OF_THE_TALON, NPC_DRYAD, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_GUARDIAN_WATER_ELEMENTAL, NPC_HORDE_GRUNT, NPC_HORDE_HEADHUNTER, NPC_HORDE_HEALING_WARD, NPC_HORDE_PEON, NPC_HORDE_SHAMAN, NPC_HORDE_WITCH_DOCTOR, NPC_HYJAL_DESPAWN_TRIGGER, NPC_INFERNAL, NPC_INFERNAL_RELAY, NPC_INFERNAL_TARGET, NPC_JAINA, NPC_KAZROGAL, NPC_LESSER_DOOMGUARD, NPC_NECRO, NPC_NELF_ANCIENT_OF_LORE, NPC_NELF_ANCIENT_OF_WAR, NPC_NELF_ANCIENT_PROT, NPC_NELF_ARCHER, NPC_NELF_HUNTRESS, NPC_NELF_WISP, NPC_STALK, NPC_TAUREN_WARRIOR, NPC_THRALL, NPC_TOWERING_INFERNAL, NPC_TYRANDE, NPC_WINTERCHILL, SetData(), TYPE_ANETHERON, TYPE_AZGALOR, TYPE_KAZROGAL, TYPE_WINTERCHILL, and WORLD_STATE_MOUNT_HYJAL_ENABLE.
OnCreatureDeath()
void instance_mount_hyjal::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 1068 of file hyjal.cpp.
References AI_EVENT_CUSTOM_D, DONE, FailEvent(), GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), GO_FLAG_LOCKED, GO_HORDE_ENCAMPMENT_PORTAL, GO_NIGHT_ELF_VILLAGE_PORTAL, InstanceData::instance, Creature::IsTemporarySummon(), m_nextWaveTimer, m_waveSpawns, NPC_ABOMI, NPC_ANETHERON, NPC_ARCHIMONDE, NPC_AZGALOR, NPC_BANSH, NPC_CRYPT, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_INFERNAL, NPC_JAINA, NPC_KAZROGAL, NPC_NECRO, NPC_STALK, NPC_THRALL, NPC_WINTERCHILL, SetData(), WorldStateVariableManager::SetVariable(), SpawnNextWave(), TYPE_ANETHERON, TYPE_ARCHIMONDE, TYPE_AZGALOR, TYPE_KAZROGAL, TYPE_WINTERCHILL, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT.
OnCreatureEnterCombat()
void instance_mount_hyjal::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 1060 of file hyjal.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_ARCHIMONDE, SetData(), and TYPE_ARCHIMONDE.
OnCreatureRespawn()
void instance_mount_hyjal::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 1024 of file hyjal.cpp.
References Creature::AI(), Object::GetEntry(), WorldObject::GetSpawnerGuid(), NPC_ABOMI, NPC_ANCIENT_WISP, NPC_BANSH, NPC_CRYPT, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_INFERNAL, NPC_INFERNAL_RELAY, NPC_INFERNAL_TARGET, NPC_LESSER_DOOMGUARD, NPC_NECRO, NPC_STALK, Unit::SetCanEnterCombat(), Creature::SetCorpseDelay(), Creature::SetNoLoot(), Creature::SetNoReputation(), and Creature::SetNoXP().
OnObjectCreate()
void instance_mount_hyjal::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 985 of file hyjal.cpp.
References BASE_ALLY, BASE_HORDE, DONE, GAMEOBJECT_FLAGS, GetData(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), GO_ANCIENT_GEM, GO_FLAG_LOCKED, GO_HORDE_ENCAMPMENT_PORTAL, GO_NIGHT_ELF_VILLAGE_PORTAL, GO_ROARING_FLAME, m_ancientGems, ScriptedInstance::m_goEntryGuidStore, m_roaringFlames, Object::RemoveFlag(), TYPE_ANETHERON, and TYPE_AZGALOR.
OnPlayerDeath()
void instance_mount_hyjal::OnPlayerDeath (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 868 of file hyjal.cpp.
References Unit::CastSpell(), CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, Unit::getClass(), GetData(), IN_PROGRESS, SPELL_SOUL_CHARGE_GREEN_CHARGE, SPELL_SOUL_CHARGE_RED_CHARGE, SPELL_SOUL_CHARGE_YELLOW_CHARGE, TRIGGERED_OLD_TRIGGERED, and TYPE_ARCHIMONDE.
OnPlayerEnter()
void instance_mount_hyjal::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 840 of file hyjal.cpp.
References BASE_ALLY, BASE_HORDE, DONE, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), m_startCheck, NPC_JAINA, NPC_THRALL, SpawnArchimonde(), SpawnBase(), TYPE_ANETHERON, TYPE_ARCHIMONDE, and TYPE_AZGALOR.
OverrunBase()
void instance_mount_hyjal::OverrunBase (BaseArea index) private
Definition at line 1607 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, m_invasionWaves, and SpawnInvasionWave().
Referenced by ExecuteChatCommand(), RetreatBase(), and SetData().
RestartEvent()
void instance_mount_hyjal::RestartEvent () private
Definition at line 1671 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, DONE, GetData(), m_failTimer, SpawnBase(), TYPE_ANETHERON, and TYPE_AZGALOR.
Referenced by Update().
RetreatBase()
void instance_mount_hyjal::RetreatBase (BaseArea index) private
Definition at line 1558 of file hyjal.cpp.
References AI_EVENT_CUSTOM_B, BASE_ALLY, BASE_HORDE, ScriptedInstance::DoRespawnGameObject(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetVariableManager(), InstanceData::instance, m_baseSpawns, m_roaringFlames, NPC_ALLIANCE_KNIGHT, NPC_JAINA, NPC_THRALL, OverrunBase(), REACT_PASSIVE, SetData(), WorldStateVariableManager::SetVariable(), SPECIAL, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, TYPE_WIN, WEEK, WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by ExecuteChatCommand(), and StartEvent().
Save()
const char* instance_mount_hyjal::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 185 of file hyjal.h.
References m_saveData.
SetData()
void instance_mount_hyjal::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 1163 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, debug_log(), DespawnBase(), DespawnOverrun(), DespawnWaveSpawns(), DONE, FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetVariableManager(), IN_PROGRESS, InstanceData::instance, m_encounter, m_nextInvasionWaveTimer, m_saveData, NOT_STARTED, NPC_ARCHIMONDE, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, OverrunBase(), InstanceData::SaveToDB(), WorldStateVariableManager::SetVariable(), SpawnOres(), SPECIAL, TYPE_ANETHERON, TYPE_ARCHIMONDE, TYPE_AZGALOR, TYPE_KAZROGAL, TYPE_WIN, TYPE_WINTERCHILL, WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by FailEvent(), OnCreatureCreate(), OnCreatureDeath(), OnCreatureEnterCombat(), RetreatBase(), and hyjalAI::Win().
ShowChatCommands()
void instance_mount_hyjal::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 1729 of file hyjal.cpp.
References ChatHandler::SendSysMessage().
SpawnArchimonde()
void instance_mount_hyjal::SpawnArchimonde () private
Definition at line 1281 of file hyjal.cpp.
References aArchimondeSpawnLoc, ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_ARCHIMONDE, and TEMPSPAWN_MANUAL_DESPAWN.
Referenced by ExecuteChatCommand(), OnPlayerEnter(), and StartEvent().
SpawnBase()
void instance_mount_hyjal::SpawnBase (BaseArea index, bool spawnLeader = true) private
Definition at line 1535 of file hyjal.cpp.
References BASE_ALLY, BASE_HORDE, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_baseSpawns, NPC_JAINA, and NPC_THRALL.
Referenced by ExecuteChatCommand(), OnPlayerEnter(), RestartEvent(), and StartEvent().
SpawnInfernal()
void instance_mount_hyjal::SpawnInfernal () private
Definition at line 1398 of file hyjal.cpp.
References Map::GetCreature(), InstanceData::instance, m_infernalIndices, m_infernalRelays, m_infernalsCounter, m_infernalsTimer, m_infernalTargets, SPELL_SUMMON_INFERNAL, and TRIGGERED_NONE.
Referenced by SpawnInfernals(), and Update().
SpawnInfernals()
void instance_mount_hyjal::SpawnInfernals (uint32 count) private
Definition at line 1377 of file hyjal.cpp.
References m_infernalIndices, m_infernalRelays, m_infernalsCounter, SpawnInfernal(), and urand().
Referenced by ExecuteChatCommand(), SpawnInvasionInfernals(), and SpawnWaveInfernals().
SpawnInvasionInfernals()
void instance_mount_hyjal::SpawnInvasionInfernals (uint32 index) private
Definition at line 1361 of file hyjal.cpp.
References SpawnInfernals().
Referenced by SpawnInvasionWave().
SpawnInvasionWave()
void instance_mount_hyjal::SpawnInvasionWave (uint32 index, bool setTimer) private
Definition at line 1431 of file hyjal.cpp.
References BASE_ALLY, BASE_ELF, BASE_HORDE, WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetPhaseMask(), GetRandomWavePath(), ScriptedInstance::GetSingleCreatureFromStorage(), IDLE_MOTION_TYPE, m_invasionWavesData, m_nextInvasionWaveTimer, m_overrunSpawns, TempSpawnSettings::movegen, NPC_HYJAL_DESPAWN_TRIGGER, PATH_NONE, Creature::SetCorpseDelay(), Creature::SetRespawnDelay(), SpawnInvasionInfernals(), WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by OverrunBase(), and SpawnNextInvasionWave().
SpawnNextInvasionWave()
void instance_mount_hyjal::SpawnNextInvasionWave () private
Definition at line 1298 of file hyjal.cpp.
References m_invasionWaves, and SpawnInvasionWave().
Referenced by Update().
SpawnNextWave()
void instance_mount_hyjal::SpawnNextWave () private
Definition at line 1292 of file hyjal.cpp.
References m_hyjalWaves, and SpawnWave().
Referenced by OnCreatureDeath(), and Update().
SpawnOres()
void instance_mount_hyjal::SpawnOres (BaseArea index) private
Definition at line 1417 of file hyjal.cpp.
References ScriptedInstance::DoRespawnGameObject(), m_ancientGems, urand(), and WEEK.
Referenced by SetData().
SpawnWave()
void instance_mount_hyjal::SpawnWave (uint32 index, bool setTimer) private
Definition at line 1304 of file hyjal.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_C, FailEvent(), GetInfernalsPerWave(), GetRandomWavePath(), GetRunningPerWaveMobEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), InstanceData::instance, m_hyjalWavesData, m_nextWaveTimer, MAX_CONCURRENT_SPAWNS, NPC_JAINA, NPC_THRALL, Creature::SetNoLoot(), Creature::SetNoReputation(), Creature::SetNoXP(), WorldStateVariableManager::SetVariable(), SpawnWaveInfernals(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, WORLD_STATE_MOUNT_HYJAL_ENABLE, WORLD_STATE_MOUNT_HYJAL_ENEMYCOUNT, and WORLD_STATE_MOUNT_HYJAL_WAVES.
Referenced by ExecuteChatCommand(), SpawnNextWave(), and StartEvent().
SpawnWaveInfernals()
void instance_mount_hyjal::SpawnWaveInfernals (uint32 index) private
Definition at line 1352 of file hyjal.cpp.
References GetInfernalsPerWave(), and SpawnInfernals().
Referenced by SpawnWave().
StartEvent()
void instance_mount_hyjal::StartEvent (HyjalEvents eventId)
Definition at line 1472 of file hyjal.cpp.
References BASE_ALLY, BASE_HORDE, JAINA_FIRST_BOSS, JAINA_SECOND_BOSS, JAINA_WIN, m_hyjalWaves, RetreatBase(), SpawnArchimonde(), SpawnBase(), SpawnWave(), THRALL_FIRST_BOSS, THRALL_SECOND_BOSS, and THRALL_WIN.
Update()
void instance_mount_hyjal::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 1691 of file hyjal.cpp.
References FailEvent(), ScriptedInstance::GetPlayerInMap(), m_failTimer, m_infernalsTimer, m_nextInvasionWaveTimer, m_nextWaveTimer, m_waveSpawns, RestartEvent(), SpawnInfernal(), SpawnNextInvasionWave(), and SpawnNextWave().
Friends And Related Function Documentation
ChatHandler
friend class ChatHandler friend
Definition at line 162 of file hyjal.h.
Field Documentation
m_additionalSpawns
GuidVector instance_mount_hyjal::m_additionalSpawns private
Definition at line 225 of file hyjal.h.
Referenced by DespawnWaveSpawns(), and OnCreatureCreate().
m_ancientGems
GuidVector instance_mount_hyjal::m_ancientGems[MAX_BASE - 1] private
Definition at line 219 of file hyjal.h.
Referenced by OnObjectCreate(), and SpawnOres().
m_baseSpawns
GuidVector instance_mount_hyjal::m_baseSpawns[MAX_BASE] private
Definition at line 222 of file hyjal.h.
Referenced by DespawnBase(), OnCreatureCreate(), RetreatBase(), and SpawnBase().
m_encounter
uint32 instance_mount_hyjal::m_encounter[MAX_ENCOUNTER] private
Definition at line 216 of file hyjal.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), and SetData().
m_failTimer
uint32 instance_mount_hyjal::m_failTimer private
Definition at line 236 of file hyjal.h.
Referenced by FailEvent(), RestartEvent(), and Update().
m_hyjalWaves
uint32 instance_mount_hyjal::m_hyjalWaves private
Definition at line 227 of file hyjal.h.
Referenced by FailEvent(), Load(), SpawnNextWave(), and StartEvent().
m_hyjalWavesData
std::array< HyjalWave, MAX_WAVES > instance_mount_hyjal::m_hyjalWavesData = InitHyjalWaves() static private
Definition at line 240 of file hyjal.h.
Referenced by SpawnWave().
m_infernalIndices
std::vector<uint32> instance_mount_hyjal::m_infernalIndices private
Definition at line 246 of file hyjal.h.
Referenced by SpawnInfernal(), and SpawnInfernals().
m_infernalRelays
GuidVector instance_mount_hyjal::m_infernalRelays private
Definition at line 244 of file hyjal.h.
Referenced by OnCreatureCreate(), SpawnInfernal(), and SpawnInfernals().
m_infernalsCounter
uint32 instance_mount_hyjal::m_infernalsCounter private
Definition at line 234 of file hyjal.h.
Referenced by SpawnInfernal(), and SpawnInfernals().
m_infernalsTimer
uint32 instance_mount_hyjal::m_infernalsTimer private
Definition at line 233 of file hyjal.h.
Referenced by SpawnInfernal(), and Update().
m_infernalTargets
GuidVector instance_mount_hyjal::m_infernalTargets private
Definition at line 245 of file hyjal.h.
Referenced by OnCreatureCreate(), and SpawnInfernal().
m_invasionWaves
uint32 instance_mount_hyjal::m_invasionWaves private
Definition at line 228 of file hyjal.h.
Referenced by OverrunBase(), and SpawnNextInvasionWave().
m_invasionWavesData
std::array< InvasionWave, MAX_INVASION_WAVES > instance_mount_hyjal::m_invasionWavesData = InitInvasionWaves() static private
Definition at line 241 of file hyjal.h.
Referenced by SpawnInvasionWave().
m_nextInvasionWaveTimer
uint32 instance_mount_hyjal::m_nextInvasionWaveTimer private
Definition at line 231 of file hyjal.h.
Referenced by SetData(), SpawnInvasionWave(), and Update().
m_nextWaveTimer
uint32 instance_mount_hyjal::m_nextWaveTimer private
Definition at line 230 of file hyjal.h.
Referenced by FailEvent(), OnCreatureDeath(), SpawnWave(), and Update().
m_overrunSpawns
GuidVector instance_mount_hyjal::m_overrunSpawns[MAX_BASE] private
Definition at line 223 of file hyjal.h.
Referenced by DespawnOverrun(), GetOverrunSpawns(), and SpawnInvasionWave().
m_retreatTimer
uint32 instance_mount_hyjal::m_retreatTimer private
Definition at line 232 of file hyjal.h.
m_roaringFlames
GuidVector instance_mount_hyjal::m_roaringFlames[MAX_BASE - 1] private
Definition at line 220 of file hyjal.h.
Referenced by OnObjectCreate(), and RetreatBase().
m_saveData
std::string instance_mount_hyjal::m_saveData private
Definition at line 217 of file hyjal.h.
Referenced by Save(), and SetData().
m_startCheck
bool instance_mount_hyjal::m_startCheck private
Definition at line 238 of file hyjal.h.
Referenced by OnPlayerEnter().
m_waveSpawns
GuidVector instance_mount_hyjal::m_waveSpawns private
Definition at line 221 of file hyjal.h.
Referenced by CheckConditionCriteriaMeet(), DespawnWaveSpawns(), OnCreatureCreate(), OnCreatureDeath(), and Update().
The documentation for this class was generated from the following files:
hyjal.h
hyjal.cpp