CMaNGOS_WoTLK: MaNGOS::FriendlyMissingBuffInRangeInCombatCheck Class Reference
MaNGOS::FriendlyMissingBuffInRangeInCombatCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
FriendlyMissingBuffInRangeInCombatCheck (Unit const *obj, float range, uint32 spellid)
Unit const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
uint32 i_spell
Detailed Description
Definition at line 1074 of file GridNotifiers.h.
Constructor & Destructor Documentation
FriendlyMissingBuffInRangeInCombatCheck()
MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::FriendlyMissingBuffInRangeInCombatCheck (Unit const * obj, float range, uint32 spellid) inline
Definition at line 1077 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
Unit const& MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::GetFocusObject () const inline
Definition at line 1078 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::operator() (Unit * u) inline
Definition at line 1079 of file GridNotifiers.h.
References Unit::CanAssist(), EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, Unit::HasAura(), i_obj, i_range, i_spell, Unit::IsAlive(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_obj
Unit const* MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::i_obj private
Definition at line 1084 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::i_range private
Definition at line 1085 of file GridNotifiers.h.
Referenced by operator()().
i_spell
uint32 MaNGOS::FriendlyMissingBuffInRangeInCombatCheck::i_spell private
Definition at line 1086 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h