CMaNGOS_WoTLK: SqlStatement Class Reference
SqlStatement Class Reference
#include <SqlPreparedStatement.h>
Public Member Functions
~SqlStatement ()
SqlStatement (const SqlStatement &index)
SqlStatement & operator= (const SqlStatement &index)
int ID () const
uint32 arguments () const
bool Execute ()
bool DirectExecute ()
template<typename ParamType1 >
bool PExecute (ParamType1 param1)
template<typename ParamType1 , typename ParamType2 >
bool PExecute (ParamType1 param1, ParamType2 param2)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 >
bool PExecute (ParamType1 param1, ParamType2 param2, ParamType3 param3)
template<typename ParamType1 , typename ParamType2 , typename ParamType3 , typename ParamType4 >
bool PExecute (ParamType1 param1, ParamType2 param2, ParamType3 param3, ParamType4 param4)
void addBool (bool var)
void addUInt8 (uint8 var)
void addInt8 (int8 var)
void addUInt16 (uint16 var)
void addInt16 (int16 var)
void addUInt32 (uint32 var)
void addInt32 (int32 var)
void addUInt64 (uint64 var)
void addInt64 (int64 var)
void addFloat (float var)
void addDouble (double var)
void addString (const char *var)
void addString (const std::string &var)
void addString (std::ostringstream &ss)
Protected Member Functions
SqlStatement (const SqlStatementID &index, Database &db)
Private Member Functions
SqlStmtParameters * get ()
SqlStmtParameters * detach ()
template<typename ParamType >
void arg (ParamType val)
Private Attributes
SqlStatementID m_index
Database * m_pDB
SqlStmtParameters * m_pParams
Friends
class Database
Detailed Description
Definition at line 191 of file SqlPreparedStatement.h.
Constructor & Destructor Documentation
~SqlStatement()
SqlStatement::~SqlStatement () inline
Definition at line 194 of file SqlPreparedStatement.h.
References m_pParams.
SqlStatement() [1/2]
SqlStatement::SqlStatement (const SqlStatement & index) inline
Definition at line 196 of file SqlPreparedStatement.h.
References m_pParams.
SqlStatement() [2/2]
SqlStatement::SqlStatement (const SqlStatementID & index, Database & db) inline protected
Definition at line 264 of file SqlPreparedStatement.h.
Member Function Documentation
addBool()
void SqlStatement::addBool (bool var) inline
Definition at line 246 of file SqlPreparedStatement.h.
References arg().
addDouble()
void SqlStatement::addDouble (double var) inline
Definition at line 256 of file SqlPreparedStatement.h.
References arg().
addFloat()
void SqlStatement::addFloat (float var) inline
Definition at line 255 of file SqlPreparedStatement.h.
References arg().
Referenced by Player::_SaveBGData(), Player::_SaveStats(), GMTicket::Save(), and Player::SaveToDB().
addInt16()
void SqlStatement::addInt16 (int16 var) inline
Definition at line 250 of file SqlPreparedStatement.h.
References arg().
addInt32()
void SqlStatement::addInt32 (int32 var) inline
Definition at line 252 of file SqlPreparedStatement.h.
References arg().
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveStats(), and Item::SaveToDB().
addInt64()
void SqlStatement::addInt64 (int64 var) inline
Definition at line 254 of file SqlPreparedStatement.h.
References arg().
addInt8()
void SqlStatement::addInt8 (int8 var) inline
Definition at line 248 of file SqlPreparedStatement.h.
References arg().
addString() [1/3]
void SqlStatement::addString (const char * var) inline
Definition at line 257 of file SqlPreparedStatement.h.
References arg().
Referenced by Player::_SaveEquipmentSets(), NamreebAnticheat::AntispamMgr::BlacklistAdd(), GMTicket::Save(), Pet::SavePetToDB(), and Player::SaveToDB().
addString() [2/3]
void SqlStatement::addString (const std::string & var) inline
Definition at line 258 of file SqlPreparedStatement.h.
References arg().
addString() [3/3]
void SqlStatement::addString (std::ostringstream & ss) inline
Definition at line 259 of file SqlPreparedStatement.h.
References arg().
addUInt16()
void SqlStatement::addUInt16 (uint16 var) inline
Definition at line 249 of file SqlPreparedStatement.h.
References arg().
Referenced by Player::SaveToDB().
addUInt32()
void SqlStatement::addUInt32 (uint32 var) inline
Definition at line 251 of file SqlPreparedStatement.h.
References arg().
Referenced by Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveBGData(), Player::_SaveEquipmentSets(), Player::_SaveMail(), Player::_SaveNewInstanceIdTimer(), Player::_SaveQuestStatus(), Player::_SaveSpellCooldowns(), Player::_SaveStats(), BattleGround::EndBattleGround(), Item::LoadFromDB(), NamreebAnticheat::Antispam::Notify(), GMTicket::Save(), Player::SaveItemToInventory(), Pet::SavePetToDB(), Item::SaveToDB(), Player::SaveToDB(), WorldSession::SaveTutorialsData(), AuctionHouseBot::SetItemData(), NamreebAnticheat::Antispam::Silence(), and WardenWin::Update().
addUInt64()
void SqlStatement::addUInt64 (uint64 var) inline
Definition at line 253 of file SqlPreparedStatement.h.
References arg().
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveEquipmentSets(), Player::_SaveMail(), Player::_SaveNewInstanceIdTimer(), Player::_SaveQuestStatus(), Player::_SaveSpellCooldowns(), GMTicket::Save(), Pet::SavePetToDB(), and Player::SaveToDB().
addUInt8()
void SqlStatement::addUInt8 (uint8 var) inline
Definition at line 247 of file SqlPreparedStatement.h.
References arg().
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveQuestStatus(), GMTicket::Save(), Player::SaveItemToInventory(), Item::SaveToDB(), and Player::SaveToDB().
arg()
template<typename ParamType > void SqlStatement::arg (ParamType val) inline private
Definition at line 286 of file SqlPreparedStatement.h.
References SqlStmtParameters::addParam(), and get().
Referenced by addBool(), addDouble(), addFloat(), addInt16(), addInt32(), addInt64(), addInt8(), addString(), addUInt16(), addUInt32(), addUInt64(), addUInt8(), and PExecute().
arguments()
uint32 SqlStatement::arguments () const inline
Definition at line 205 of file SqlPreparedStatement.h.
References SqlStatementID::arguments(), and m_index.
Referenced by DirectExecute(), Execute(), get(), and SqlStmtParameters::reset().
detach()
SqlStmtParameters* SqlStatement::detach () inline private
Definition at line 276 of file SqlPreparedStatement.h.
References m_pParams.
Referenced by DirectExecute(), and Execute().
DirectExecute()
bool SqlStatement::DirectExecute ()
Definition at line 70 of file SqlPreparedStatement.cpp.
References arguments(), SqlStmtParameters::boundParams(), detach(), Database::DirectExecuteStmt(), Database::GetStmtString(), ID(), m_index, m_pDB, MANGOS_ASSERT, and sLog.
Execute()
bool SqlStatement::Execute ()
Definition at line 54 of file SqlPreparedStatement.cpp.
References arguments(), SqlStmtParameters::boundParams(), detach(), Database::ExecuteStmt(), Database::GetStmtString(), ID(), m_index, m_pDB, MANGOS_ASSERT, and sLog.
Referenced by Player::_SaveActions(), Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveBGData(), Player::_SaveEquipmentSets(), Player::_SaveMail(), Player::_SaveNewInstanceIdTimer(), Player::_SaveQuestStatus(), Player::_SaveSpellCooldowns(), Player::_SaveStats(), BattleGround::EndBattleGround(), Item::LoadFromDB(), PExecute(), GMTicketMgr::Save(), Player::SaveItemToInventory(), Pet::SavePetToDB(), Item::SaveToDB(), Player::SaveToDB(), WorldSession::SaveTutorialsData(), and AuctionHouseBot::SetItemData().
get()
SqlStmtParameters* SqlStatement::get () inline private
Definition at line 268 of file SqlPreparedStatement.h.
References arguments(), and m_pParams.
Referenced by arg().
ID()
int SqlStatement::ID () const inline
Definition at line 204 of file SqlPreparedStatement.h.
References SqlStatementID::ID(), and m_index.
Referenced by DirectExecute(), and Execute().
operator=()
SqlStatement & SqlStatement::operator= (const SqlStatement & index)
Definition at line 37 of file SqlPreparedStatement.cpp.
References m_index, m_pDB, and m_pParams.
PExecute() [1/4]
template<typename ParamType1 > bool SqlStatement::PExecute (ParamType1 param1) inline
Definition at line 212 of file SqlPreparedStatement.h.
References arg(), and Execute().
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Player::_SaveBGData(), Player::_SaveDailyQuestStatus(), Player::_SaveEquipmentSets(), Player::_SaveGlyphs(), Player::_SaveInventory(), Player::_SaveMail(), Player::_SaveMonthlyQuestStatus(), Player::_SaveSkills(), Pet::_SaveSpellCooldowns(), Player::_SaveSpellCooldowns(), Pet::_SaveSpells(), Player::_SaveSpells(), Player::_SaveStats(), Player::_SaveTalents(), Player::_SaveWeeklyQuestStatus(), World::AddSession_(), Item::DeleteFromDB(), Corpse::DeleteFromDB(), Pet::DeleteFromDB(), Item::DeleteFromInventoryDB(), Player::DestroyItem(), BattleGround::EndBattleGround(), WorldSocket::HandleAuthSession(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePlayerLogin(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleUnstablePet(), Item::LoadFromDB(), Pet::LoadPetFromDB(), WorldSession::LogoutPlayer(), MapPersistentState::SaveCreatureRespawnTime(), Player::SaveGoldToDB(), MapPersistentState::SaveGORespawnTime(), Player::SaveItemToInventory(), Pet::SavePetToDB(), AchievementMgr::SaveToDB(), Item::SaveToDB(), Player::SaveToDB(), ReputationMgr::SaveToDB(), WorldSession::SetAccountData(), and AuctionHouseBot::SetItemData().
PExecute() [2/4]
template<typename ParamType1 , typename ParamType2 > bool SqlStatement::PExecute (ParamType1 param1, ParamType2 param2) inline
Definition at line 219 of file SqlPreparedStatement.h.
References arg(), and Execute().
PExecute() [3/4]
template<typename ParamType1 , typename ParamType2 , typename ParamType3 > bool SqlStatement::PExecute (ParamType1 param1, ParamType2 param2, ParamType3 param3) inline
Definition at line 227 of file SqlPreparedStatement.h.
References arg(), and Execute().
PExecute() [4/4]
template<typename ParamType1 , typename ParamType2 , typename ParamType3 , typename ParamType4 > bool SqlStatement::PExecute (ParamType1 param1, ParamType2 param2, ParamType3 param3, ParamType4 param4) inline
Definition at line 236 of file SqlPreparedStatement.h.
References arg(), and Execute().
Friends And Related Function Documentation
Database
friend class Database friend
Definition at line 263 of file SqlPreparedStatement.h.
Field Documentation
m_index
SqlStatementID SqlStatement::m_index private
Definition at line 292 of file SqlPreparedStatement.h.
Referenced by arguments(), DirectExecute(), Execute(), ID(), and operator=().
m_pDB
Database* SqlStatement::m_pDB private
Definition at line 293 of file SqlPreparedStatement.h.
Referenced by DirectExecute(), Execute(), and operator=().
m_pParams
SqlStmtParameters* SqlStatement::m_pParams private
Definition at line 294 of file SqlPreparedStatement.h.
Referenced by detach(), get(), operator=(), SqlStatement(), and ~SqlStatement().
The documentation for this class was generated from the following files:
SqlPreparedStatement.h
SqlPreparedStatement.cpp