CMaNGOS_WoTLK: GridRefManager< OBJECT > Class Template Reference
GridRefManager< OBJECT > Class Template Reference
#include <GridRefManager.h>
Public Types
typedef LinkedListHead::Iterator< GridReference< OBJECT > > iterator
Public Types inherited from RefManager< GridRefManager< OBJECT >, OBJECT >
typedef LinkedListHead::Iterator< Reference< GridRefManager< OBJECT >, OBJECT > > iterator
typedef LinkedListHead::Iterator< Reference< GridRefManager< OBJECT >, OBJECT > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
GridReference< OBJECT > * getFirst ()
GridReference< OBJECT > * getLast ()
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
Public Member Functions inherited from RefManager< GridRefManager< OBJECT >, OBJECT >
RefManager ()
virtual ~RefManager ()
Reference< GridRefManager< OBJECT >, OBJECT > * getFirst ()
Reference< GridRefManager< OBJECT >, OBJECT > const * getFirst () const
Reference< GridRefManager< OBJECT >, OBJECT > * getLast ()
Reference< GridRefManager< OBJECT >, OBJECT > const * getLast () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
template<class OBJECT>
class GridRefManager< OBJECT >
Definition at line 27 of file GridRefManager.h.
Member Typedef Documentation
iterator
template<class OBJECT > typedef LinkedListHead::Iterator< GridReference<OBJECT> > GridRefManager< OBJECT >::iterator
Definition at line 31 of file GridRefManager.h.
Member Function Documentation
begin()
template<class OBJECT > iterator GridRefManager< OBJECT >::begin () inline
Definition at line 43 of file GridRefManager.h.
References GridRefManager< OBJECT >::getFirst().
Referenced by GameObject::TickCapturePoint(), MaNGOS::CameraDistWorker< Do >::Visit(), MaNGOS::UnitSearcher< Check >::Visit(), MaNGOS::UnitLastSearcher< Check >::Visit(), MaNGOS::CreatureSearcher< Check >::Visit(), MaNGOS::CreatureLastSearcher< Check >::Visit(), MaNGOS::CreatureListSearcher< Check >::Visit(), MaNGOS::CreatureWorker< Do >::Visit(), ObjectGridRespawnMover::Visit(), MaNGOS::WorldObjectSearcher< Check >::Visit(), MaNGOS::WorldObjectWorker< Do >::Visit(), MaNGOS::GameObjectSearcher< Check >::Visit(), MaNGOS::GameObjectLastSearcher< Check >::Visit(), MaNGOS::GameObjectListSearcher< Check >::Visit(), MaNGOS::VisibleNotifier::Visit(), MaNGOS::SpellNotifierCreatureAndPlayer::Visit(), MaNGOS::WorldObjectListSearcher< Check >::Visit(), MaNGOS::UnitListSearcher< Check >::Visit(), MaNGOS::PlayerSearcher< Check >::Visit(), MaNGOS::PlayerListSearcher< Check >::Visit(), and MaNGOS::PlayerWorker< Do >::Visit().
end()
template<class OBJECT > iterator GridRefManager< OBJECT >::end () inline
Definition at line 44 of file GridRefManager.h.
Referenced by Map::UnloadAll(), Map::Update(), MaNGOS::CameraDistWorker< Do >::Visit(), MaNGOS::UnitSearcher< Check >::Visit(), MaNGOS::UnitLastSearcher< Check >::Visit(), MaNGOS::CreatureSearcher< Check >::Visit(), MaNGOS::CreatureLastSearcher< Check >::Visit(), MaNGOS::CreatureListSearcher< Check >::Visit(), MaNGOS::CreatureWorker< Do >::Visit(), ObjectGridRespawnMover::Visit(), MaNGOS::WorldObjectSearcher< Check >::Visit(), MaNGOS::WorldObjectWorker< Do >::Visit(), MaNGOS::GameObjectSearcher< Check >::Visit(), MaNGOS::GameObjectLastSearcher< Check >::Visit(), MaNGOS::GameObjectListSearcher< Check >::Visit(), MaNGOS::VisibleNotifier::Visit(), MaNGOS::SpellNotifierCreatureAndPlayer::Visit(), MaNGOS::WorldObjectListSearcher< Check >::Visit(), MaNGOS::UnitListSearcher< Check >::Visit(), MaNGOS::PlayerSearcher< Check >::Visit(), MaNGOS::PlayerListSearcher< Check >::Visit(), and MaNGOS::PlayerWorker< Do >::Visit().
getFirst()
template<class OBJECT > GridReference<OBJECT>* GridRefManager< OBJECT >::getFirst () inline
Definition at line 33 of file GridRefManager.h.
Referenced by GridRefManager< OBJECT >::begin(), and ObjectGridUnloader::Visit().
getLast()
template<class OBJECT > GridReference<OBJECT>* GridRefManager< OBJECT >::getLast () inline
Definition at line 38 of file GridRefManager.h.
Referenced by GridRefManager< OBJECT >::rbegin().
rbegin()
template<class OBJECT > iterator GridRefManager< OBJECT >::rbegin () inline
Definition at line 45 of file GridRefManager.h.
References GridRefManager< OBJECT >::getLast().
rend()
template<class OBJECT > iterator GridRefManager< OBJECT >::rend () inline
Definition at line 46 of file GridRefManager.h.
The documentation for this class was generated from the following files:
GridReference.h
GridRefManager.h