CMaNGOS_WoTLK: VehicleInfo Class Reference
VehicleInfo Class Reference
to provide abstract support for transported entities
A class to provide support for each vehicle.
#include <Vehicle.h>
Public Member Functions
VehicleInfo (Unit *owner, VehicleEntry const *vehicleEntry, uint32 overwriteNpcEntry)
Constructor of VehicleInfo.
void Initialize ()
Initializes the accessories.
bool IsInitialized () const
~VehicleInfo ()
VehicleEntry const * GetVehicleEntry () const
VehicleSeatEntry const * GetSeatEntry (uint8 seat) const
Get the Vehicle SeatEntry of a seat by position.
VehicleSeatEntry const * GetSeatForPassenger (Unit const *passenger) const
void Board (Unit *passenger, uint8 seat)
This function will board a passenger onto a vehicle.
void ChangeSeat (Unit *passenger, uint8 currentSeat, bool next)
void SwitchSeat (Unit *passenger, uint8 seat)
This function will switch the seat of a passenger on the same vehicle.
void UnBoard (Unit *passenger, bool changeVehicle)
This function will Unboard a passenger.
bool CanBoard (Unit *passenger) const
This function will check if a passenger can be boarded.
Unit * GetPassenger (uint8 seat) const
void RemoveAccessoriesFromMap ()
Unsummones accessory in case of far-teleport or death.
void TeleportPassengers (uint32 mapId)
void DisableAccessoryInit ()
Public Member Functions inherited from TransportBase
TransportBase (WorldObject *owner)
virtual ~TransportBase ()
void Update (uint32 diff)
void UpdateGlobalPositions ()
void UpdateGlobalPositionOf (WorldObject *passenger, float lx, float ly, float lz, float lo) const
WorldObject * GetOwner () const
void RotateLocalPosition (float lx, float ly, float &rx, float &ry) const
void NormalizeRotatedPosition (float rx, float ry, float &lx, float &ly) const
void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const
void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const
This method transforms supplied global coordinates into local offsets.
bool HasOnBoard (WorldObject const *passenger) const
Private Member Functions
void CalculateBoardingPositionOf (float gx, float gy, float gz, float go, float &lx, float &ly, float &lz, float &lo) const
bool GetUsableSeatFor (Unit *passenger, uint8 &seat, bool reset, bool next) const
This function will get a usable seat for a passenger.
bool IsSeatAvailableFor (Unit *passenger, uint8 seat) const
Returns if a @passenger could board onto @seat - @passenger MUST be provided.
uint8 GetTakenSeatsMask () const
Wrapper to collect all taken seats.
uint8 GetEmptySeatsMask () const
uint8 GetEmptySeats () const
bool IsUsableSeatForPlayer (uint32 seatFlags, uint32 seatFlagsB) const
bool IsUsableSeatForCreature (uint32) const
void ApplySeatMods (Unit *passenger, uint32 seatFlags)
Add control and such modifiers to a passenger if required.
void RemoveSeatMods (Unit *passenger, uint32 seatFlags)
Remove control and such modifiers to a passenger if they were added.
Private Attributes
VehicleEntry const * m_vehicleEntry
VehicleSeatMap m_vehicleSeats
Stores the available seats of the vehicle (filled in constructor)
uint8 m_creatureSeats
Mask that stores which seats are avaiable for creatures.
uint8 m_playerSeats
Mask that stores which seats are avaiable for players.
uint32 m_overwriteNpcEntry
bool m_isInitialized
bool m_disabledAccessoryInit
uint32 m_originalFaction
GuidSet m_accessoryGuids
Stores the summoned accessories of this vehicle.
Additional Inherited Members
Protected Member Functions inherited from TransportBase
void BoardPassenger (WorldObject *passenger, float lx, float ly, float lz, float lo, uint8 seat)
void UnBoardPassenger (WorldObject *passenger)
Protected Attributes inherited from TransportBase
WorldObject * m_owner
The transporting unit.
PassengerMap m_passengers
List of passengers and their transport-information.
Position m_lastPosition
float m_sinO
float m_cosO
uint32 m_updatePositionsTimer
Timer that is used to trigger updates for global coordinate calculations.
Detailed Description
A class to provide support for each vehicle.
This includes
Boarding and unboarding of passengers, including support to switch vehicles
Basic checks if a passenger can board
Definition at line 78 of file Vehicle.h.
Member Function Documentation
DisableAccessoryInit()
void VehicleInfo::DisableAccessoryInit () inline
Definition at line 103 of file Vehicle.h.
References m_disabledAccessoryInit.
Referenced by WorldSession::HandleMoveWorldportAckOpcode().
GetEmptySeats()
uint8 VehicleInfo::GetEmptySeats () const inline private
Definition at line 115 of file Vehicle.h.
References TransportBase::m_passengers, and m_vehicleSeats.
Referenced by CanBoard().
GetEmptySeatsMask()
uint8 VehicleInfo::GetEmptySeatsMask () const inline private
Definition at line 114 of file Vehicle.h.
References GetTakenSeatsMask().
Referenced by CanBoard(), GetUsableSeatFor(), and IsSeatAvailableFor().
GetVehicleEntry()
VehicleEntry const* VehicleInfo::GetVehicleEntry () const inline
Definition at line 87 of file Vehicle.h.
References m_vehicleEntry.
Referenced by CreatureAI::AttackPassengersIfCan(), Aura::HandleAuraMounted(), WorldSession::HandleChangeSeatsOnControlledVehicle(), WorldSession::HandleRequestVehicleSwitchSeat(), Initialize(), and RemoveSeatMods().
IsInitialized()
bool VehicleInfo::IsInitialized () const inline
Definition at line 83 of file Vehicle.h.
References m_isInitialized.
Referenced by Unit::Update().
IsUsableSeatForCreature()
bool VehicleInfo::IsUsableSeatForCreature (uint32) const inline private
Definition at line 118 of file Vehicle.h.
Referenced by VehicleInfo().
Field Documentation
m_accessoryGuids
GuidSet VehicleInfo::m_accessoryGuids private
Stores the summoned accessories of this vehicle.
Definition at line 133 of file Vehicle.h.
Referenced by Initialize(), RemoveAccessoriesFromMap(), and UnBoard().
m_creatureSeats
uint8 VehicleInfo::m_creatureSeats private
Mask that stores which seats are avaiable for creatures.
Definition at line 126 of file Vehicle.h.
Referenced by CanBoard(), GetUsableSeatFor(), IsSeatAvailableFor(), and VehicleInfo().
m_disabledAccessoryInit
bool VehicleInfo::m_disabledAccessoryInit private
Definition at line 131 of file Vehicle.h.
Referenced by DisableAccessoryInit(), and Initialize().
m_isInitialized
bool VehicleInfo::m_isInitialized private
Definition at line 130 of file Vehicle.h.
Referenced by Initialize(), IsInitialized(), and RemoveAccessoriesFromMap().
m_originalFaction
uint32 VehicleInfo::m_originalFaction private
Definition at line 132 of file Vehicle.h.
Referenced by ApplySeatMods(), and RemoveSeatMods().
m_overwriteNpcEntry
uint32 VehicleInfo::m_overwriteNpcEntry private
Definition at line 129 of file Vehicle.h.
Referenced by Initialize().
m_playerSeats
uint8 VehicleInfo::m_playerSeats private
Mask that stores which seats are avaiable for players.
Definition at line 127 of file Vehicle.h.
Referenced by CanBoard(), GetUsableSeatFor(), IsSeatAvailableFor(), and VehicleInfo().
m_vehicleEntry
VehicleEntry const* VehicleInfo::m_vehicleEntry private
Definition at line 124 of file Vehicle.h.
Referenced by ChangeSeat(), GetVehicleEntry(), SwitchSeat(), and UnBoard().
m_vehicleSeats
VehicleSeatMap VehicleInfo::m_vehicleSeats private
Stores the available seats of the vehicle (filled in constructor)
Definition at line 125 of file Vehicle.h.
Referenced by GetEmptySeats(), GetSeatEntry(), and VehicleInfo().
The documentation for this class was generated from the following files:
Vehicle.h
Vehicle.cpp