CMaNGOS_WoTLK: OutdoorPvPHP Class Reference
OutdoorPvPHP Class Reference
#include <OutdoorPvPHP.h>
Public Member Functions
OutdoorPvPHP ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleObjectiveComplete (uint32 eventId, const PlayerList &players, Team team) override
void HandleGameObjectCreate (GameObject *go) override
void HandlePlayerKillInsideArea (Player *player, Unit *) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleGameObjectUse (Player *, GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
bool ProcessCaptureEvent (GameObject *go, uint32 towerId, Team team, uint32 newWorldState, uint32 towerArtKit, uint32 towerAnim)
Private Attributes
Team m_towerOwner [MAX_HP_TOWERS]
uint32 m_towerWorldState [MAX_HP_TOWERS]
uint8 m_towersAlliance
uint8 m_towersHorde
ObjectGuid m_towers [MAX_HP_TOWERS]
ObjectGuid m_banners [MAX_HP_TOWERS]
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 132 of file OutdoorPvPHP.h.
Constructor & Destructor Documentation
OutdoorPvPHP()
OutdoorPvPHP::OutdoorPvPHP ()
Definition at line 27 of file OutdoorPvPHP.cpp.
References m_towerOwner, m_towerWorldState, TEAM_NONE, WORLD_STATE_HP_BROKEN_HILL_NEUTRAL, WORLD_STATE_HP_OVERLOOK_NEUTRAL, and WORLD_STATE_HP_STADIUM_NEUTRAL.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPHP::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 39 of file OutdoorPvPHP.cpp.
References FillInitialWorldState(), m_towersAlliance, m_towersHorde, m_towerWorldState, WORLD_STATE_ADD, WORLD_STATE_HP_TOWER_COUNT_ALLIANCE, WORLD_STATE_HP_TOWER_COUNT_HORDE, WORLD_STATE_HP_TOWER_DISPLAY_A, and WORLD_STATE_HP_TOWER_DISPLAY_H.
HandleEvent()
bool OutdoorPvPHP::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 164 of file OutdoorPvPHP.cpp.
References Object::GetEntry(), hellfireBanners, hellfireTowerEvents, Object::IsGameObject(), m_towerOwner, MAX_HP_TOWERS, ProcessCaptureEvent(), sWorld, and ZONE_ID_HELLFIRE_PENINSULA.
HandleGameObjectCreate()
void OutdoorPvPHP::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 81 of file OutdoorPvPHP.cpp.
References OutdoorPvP::GetBannerArtKit(), Object::GetEntry(), Object::GetObjectGuid(), GO_ARTKIT_BROKEN_HILL_ALLIANCE, GO_ARTKIT_BROKEN_HILL_HORDE, GO_ARTKIT_BROKEN_HILL_NEUTRAL, GO_ARTKIT_OVERLOOK_ALLIANCE, GO_ARTKIT_OVERLOOK_HORDE, GO_ARTKIT_OVERLOOK_NEUTRAL, GO_ARTKIT_STADIUM_ALLIANCE, GO_ARTKIT_STADIUM_HORDE, GO_ARTKIT_STADIUM_NEUTRAL, GO_HELLFIRE_BANNER_BROKEN_HILL, GO_HELLFIRE_BANNER_OVERLOOK, GO_HELLFIRE_BANNER_STADIUM, GO_TOWER_BANNER_BROKEN_HILL, GO_TOWER_BANNER_OVERLOOK, GO_TOWER_BANNER_STADIUM, OutdoorPvP::HandleGameObjectCreate(), m_banners, m_towerOwner, m_towers, and GameObject::SetGoArtKit().
HandleObjectiveComplete()
void OutdoorPvPHP::HandleObjectiveComplete (uint32 eventId, const PlayerList & players, Team team) override virtual
Reimplemented from OutdoorPvP.
Definition at line 114 of file OutdoorPvPHP.cpp.
References EVENT_BROKEN_HILL_PROGRESS_ALLIANCE, EVENT_BROKEN_HILL_PROGRESS_HORDE, EVENT_OVERLOOK_PROGRESS_ALLIANCE, EVENT_OVERLOOK_PROGRESS_HORDE, EVENT_STADIUM_PROGRESS_ALLIANCE, EVENT_STADIUM_PROGRESS_HORDE, HONOR_REWARD_HELLFIRE, NPC_CAPTURE_CREDIT_BROKEN_HILL, NPC_CAPTURE_CREDIT_OVERLOOK, and NPC_CAPTURE_CREDIT_STADIUM.
HandlePlayerEnterZone()
void OutdoorPvPHP::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 59 of file OutdoorPvPHP.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), HORDE, m_towersAlliance, m_towersHorde, MAX_HP_TOWERS, Unit::RemoveAurasDueToSpell(), SPELL_HELLFIRE_SUPERIORITY_ALLIANCE, SPELL_HELLFIRE_SUPERIORITY_HORDE, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerKillInsideArea()
void OutdoorPvPHP::HandlePlayerKillInsideArea (Player * player, Unit * victim) override virtual
Reimplemented from OutdoorPvP.
Definition at line 146 of file OutdoorPvPHP.cpp.
References ALLIANCE, GameObjectInfo::capturePoint, Unit::CastSpell(), Map::GetGameObject(), WorldObject::GetMap(), Player::GetTeam(), WorldObject::IsWithinDistInMap(), m_towers, SPELL_HELLFIRE_TOWER_TOKEN_ALLIANCE, SPELL_HELLFIRE_TOWER_TOKEN_HORDE, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerLeaveZone()
void OutdoorPvPHP::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 73 of file OutdoorPvPHP.cpp.
References ALLIANCE, Player::GetTeam(), OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), SPELL_HELLFIRE_SUPERIORITY_ALLIANCE, and SPELL_HELLFIRE_SUPERIORITY_HORDE.
ProcessCaptureEvent()
bool OutdoorPvPHP::ProcessCaptureEvent (GameObject * go, uint32 towerId, Team team, uint32 newWorldState, uint32 towerArtKit, uint32 towerAnim) private
Definition at line 198 of file OutdoorPvPHP.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), CAPTURE_ANIM_ALLIANCE, CAPTURE_ANIM_HORDE, CAPTURE_ANIM_NEUTRAL, CAPTURE_ARTKIT_ALLIANCE, CAPTURE_ARTKIT_HORDE, CAPTURE_ARTKIT_NEUTRAL, HORDE, m_banners, m_towerOwner, m_towersAlliance, m_towersHorde, m_towerWorldState, MAX_HP_TOWERS, OutdoorPvP::SendUpdateWorldState(), OutdoorPvP::SetBannerVisual(), SPELL_HELLFIRE_SUPERIORITY_ALLIANCE, SPELL_HELLFIRE_SUPERIORITY_HORDE, WORLD_STATE_ADD, WORLD_STATE_HP_TOWER_COUNT_ALLIANCE, WORLD_STATE_HP_TOWER_COUNT_HORDE, and WORLD_STATE_REMOVE.
Referenced by HandleEvent().
SendRemoveWorldStates()
void OutdoorPvPHP::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 50 of file OutdoorPvPHP.cpp.
References m_towerWorldState, Player::SendUpdateWorldState(), WORLD_STATE_HP_TOWER_DISPLAY_A, WORLD_STATE_HP_TOWER_DISPLAY_H, and WORLD_STATE_REMOVE.
Field Documentation
m_banners
ObjectGuid OutdoorPvPHP::m_banners[MAX_HP_TOWERS] private
Definition at line 158 of file OutdoorPvPHP.h.
Referenced by HandleGameObjectCreate(), and ProcessCaptureEvent().
m_towerOwner
Team OutdoorPvPHP::m_towerOwner[MAX_HP_TOWERS] private
Definition at line 152 of file OutdoorPvPHP.h.
Referenced by HandleEvent(), HandleGameObjectCreate(), OutdoorPvPHP(), and ProcessCaptureEvent().
m_towers
ObjectGuid OutdoorPvPHP::m_towers[MAX_HP_TOWERS] private
Definition at line 157 of file OutdoorPvPHP.h.
Referenced by HandleGameObjectCreate(), and HandlePlayerKillInsideArea().
m_towersAlliance
uint8 OutdoorPvPHP::m_towersAlliance private
Definition at line 154 of file OutdoorPvPHP.h.
Referenced by FillInitialWorldStates(), HandlePlayerEnterZone(), and ProcessCaptureEvent().
m_towersHorde
uint8 OutdoorPvPHP::m_towersHorde private
Definition at line 155 of file OutdoorPvPHP.h.
Referenced by FillInitialWorldStates(), HandlePlayerEnterZone(), and ProcessCaptureEvent().
m_towerWorldState
uint32 OutdoorPvPHP::m_towerWorldState[MAX_HP_TOWERS] private
Definition at line 153 of file OutdoorPvPHP.h.
Referenced by FillInitialWorldStates(), OutdoorPvPHP(), ProcessCaptureEvent(), and SendRemoveWorldStates().
The documentation for this class was generated from the following files:
OutdoorPvPHP.h
OutdoorPvPHP.cpp