CMaNGOS_WoTLK: PoolManager Class Reference
PoolManager Class Reference
#include <PoolManager.h>
Public Types
typedef std::vector< PoolTemplateData > PoolTemplateDataMap
Public Member Functions
PoolManager ()
~PoolManager ()
void LoadFromDB ()
void Initialize (MapPersistentState *state)
uint16 GetMaxPoolId () const
template<typename T >
uint16 IsPartOfAPool (uint32 db_guid_or_pool_id) const
template<typename T >
uint16 IsPartOfTopPool (uint32 db_guid_or_pool_id) const
template<typename T >
void SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
bool CheckPool (uint16 pool_id) const
void CheckEventLinkAndReport (uint16 pool_id, int16 event_id, std::map< uint32, int16 > const &creature2event, std::map< uint32, int16 > const &go2event) const
void SpawnPool (MapPersistentState &mapState, uint16 pool_id, bool instantly)
void DespawnPool (MapPersistentState &mapState, uint16 pool_id)
template<typename T >
void UpdatePool (MapPersistentState &mapState, uint16 pool_id, uint32 db_guid_or_pool_id=0)
void SpawnPoolInMaps (uint16 pool_id, bool instantly)
void DespawnPoolInMaps (uint16 pool_id)
void InitSpawnPool (MapPersistentState &mapState, uint16 pool_id)
template<typename T >
void UpdatePoolInMaps (uint16 pool_id, uint32 db_guid_or_pool_id=0)
void RemoveAutoSpawnForPool (uint16 pool_id)
PoolTemplateData const & GetPoolTemplate (uint16 pool_id) const
PoolGroup< Creature > const & GetPoolCreatures (uint16 pool_id) const
PoolGroup< GameObject > const & GetPoolGameObjects (uint16 pool_id) const
PoolGroup< Pool > const & GetPoolPools (uint16 pool_id) const
template<>
void SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
template<>
void SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
template<>
uint16 IsPartOfAPool (uint32 db_guid) const
template<>
uint16 IsPartOfAPool (uint32 db_guid) const
template<>
uint16 IsPartOfAPool (uint32 pool_id) const
Protected Types
typedef std::vector< PoolGroup< Creature > > PoolGroupCreatureMap
typedef std::vector< PoolGroup< GameObject > > PoolGroupGameObjectMap
typedef std::vector< PoolGroup< Pool > > PoolGroupPoolMap
typedef std::pair< uint32, uint16 > SearchPair
typedef std::map< uint32, uint16 > SearchMap
Protected Member Functions
template<typename T >
void SpawnPoolGroup (MapPersistentState &mapState, uint16 pool_id, uint32 db_guid_or_pool_id, bool instantly)
template<>
void SpawnPoolGroup (MapPersistentState &mapState, uint16 pool_id, uint32 db_guid, bool instantly)
template<>
void SpawnPoolGroup (MapPersistentState &mapState, uint16 pool_id, uint32 db_guid, bool instantly)
template<>
void SpawnPoolGroup (MapPersistentState &mapState, uint16 pool_id, uint32 sub_pool_id, bool instantly)
Protected Attributes
uint16 max_pool_id
PoolTemplateDataMap mPoolTemplate
PoolGroupCreatureMap mPoolCreatureGroups
PoolGroupGameObjectMap mPoolGameobjectGroups
PoolGroupPoolMap mPoolPoolGroups
SearchMap mCreatureSearchMap
SearchMap mGameobjectSearchMap
SearchMap mPoolSearchMap
Detailed Description
Definition at line 131 of file PoolManager.h.
Member Typedef Documentation
PoolGroupCreatureMap
typedef std::vector<PoolGroup<Creature> > PoolManager::PoolGroupCreatureMap protected
Definition at line 195 of file PoolManager.h.
PoolGroupGameObjectMap
typedef std::vector<PoolGroup<GameObject> > PoolManager::PoolGroupGameObjectMap protected
Definition at line 196 of file PoolManager.h.
PoolGroupPoolMap
typedef std::vector<PoolGroup<Pool> > PoolManager::PoolGroupPoolMap protected
Definition at line 197 of file PoolManager.h.
PoolTemplateDataMap
typedef std::vector<PoolTemplateData> PoolManager::PoolTemplateDataMap
Definition at line 184 of file PoolManager.h.
SearchMap
typedef std::map<uint32, uint16> PoolManager::SearchMap protected
Definition at line 199 of file PoolManager.h.
SearchPair
typedef std::pair<uint32, uint16> PoolManager::SearchPair protected
Definition at line 198 of file PoolManager.h.
Constructor & Destructor Documentation
PoolManager()
PoolManager::PoolManager ()
Definition at line 565 of file PoolManager.cpp.
~PoolManager()
PoolManager::~PoolManager () inline
Definition at line 135 of file PoolManager.h.
Member Function Documentation
CheckEventLinkAndReport()
void PoolManager::CheckEventLinkAndReport (uint16 pool_id, int16 event_id, std::map< uint32, int16 > const & creature2event, std::map< uint32, int16 > const & go2event) const
Definition at line 1123 of file PoolManager.cpp.
References mPoolCreatureGroups, mPoolGameobjectGroups, and mPoolPoolGroups.
CheckPool()
bool PoolManager::CheckPool (uint16 pool_id) const
Definition at line 1114 of file PoolManager.cpp.
References max_pool_id, mPoolCreatureGroups, mPoolGameobjectGroups, and mPoolPoolGroups.
Referenced by LoadFromDB().
DespawnPool()
void PoolManager::DespawnPool (MapPersistentState & mapState, uint16 pool_id)
Definition at line 1101 of file PoolManager.cpp.
References mPoolCreatureGroups, mPoolGameobjectGroups, and mPoolPoolGroups.
DespawnPoolInMaps()
void PoolManager::DespawnPoolInMaps (uint16 pool_id)
Definition at line 1202 of file PoolManager.cpp.
References PoolTemplateData::mapEntry, MapEntry::MapID, mPoolTemplate, and sMapPersistentStateMgr.
GetMaxPoolId()
uint16 PoolManager::GetMaxPoolId () const inline
Definition at line 140 of file PoolManager.h.
References max_pool_id.
GetPoolCreatures()
PoolGroup<Creature> const& PoolManager::GetPoolCreatures (uint16 pool_id) const inline
Definition at line 186 of file PoolManager.h.
References mPoolCreatureGroups.
GetPoolGameObjects()
PoolGroup<GameObject> const& PoolManager::GetPoolGameObjects (uint16 pool_id) const inline
Definition at line 187 of file PoolManager.h.
References mPoolGameobjectGroups.
GetPoolPools()
PoolGroup<Pool> const& PoolManager::GetPoolPools (uint16 pool_id) const inline
Definition at line 188 of file PoolManager.h.
References mPoolPoolGroups.
GetPoolTemplate()
PoolTemplateData const& PoolManager::GetPoolTemplate (uint16 pool_id) const inline
Definition at line 185 of file PoolManager.h.
References mPoolTemplate.
Initialize()
void PoolManager::Initialize (MapPersistentState * state)
Definition at line 1056 of file PoolManager.cpp.
References InitSpawnPool(), and mPoolTemplate.
InitSpawnPool()
void PoolManager::InitSpawnPool (MapPersistentState & mapState, uint16 pool_id)
Definition at line 1214 of file PoolManager.cpp.
References MapPersistentState::GetMapEntry(), mPoolTemplate, and SpawnPool().
Referenced by Initialize().
IsPartOfAPool() [1/4]
template<> uint16 PoolManager::IsPartOfAPool (uint32 db_guid) const inline
Definition at line 216 of file PoolManager.h.
References mCreatureSearchMap.
IsPartOfAPool() [2/4]
template<> uint16 PoolManager::IsPartOfAPool (uint32 db_guid) const inline
Definition at line 227 of file PoolManager.h.
References mGameobjectSearchMap.
IsPartOfAPool() [3/4]
template<typename T > uint16 PoolManager::IsPartOfAPool (uint32 db_guid_or_pool_id) const
IsPartOfAPool() [4/4]
template<> uint16 PoolManager::IsPartOfAPool (uint32 pool_id) const inline
Definition at line 238 of file PoolManager.h.
References mPoolSearchMap.
IsPartOfTopPool()
template<typename T > uint16 PoolManager::IsPartOfTopPool (uint32 db_guid_or_pool_id) const inline
Definition at line 147 of file PoolManager.h.
LoadFromDB()
void PoolManager::LoadFromDB ()
Definition at line 603 of file PoolManager.cpp.
References PoolGroup< T >::AddEntry(), PoolTemplateData::AutoSpawn, PoolMapChecker::CheckAndRemember(), CheckPool(), PoolTemplateData::description, QueryResult::Fetch(), Field::GetCppString(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), CreatureData::mapid, GameObjectData::mapid, max_pool_id, PoolTemplateData::MaxLimit, mCreatureSearchMap, mGameobjectSearchMap, mPoolCreatureGroups, mPoolGameobjectGroups, mPoolPoolGroups, mPoolSearchMap, mPoolTemplate, QueryResult::NextRow(), Database::Query(), PoolGroup< T >::SetPoolId(), sLog, sObjectMgr, BarGoLink::step(), and WorldDatabase.
RemoveAutoSpawnForPool()
void PoolManager::RemoveAutoSpawnForPool (uint16 pool_id) inline
Definition at line 182 of file PoolManager.h.
References mPoolTemplate.
SetExcludeObject() [1/3]
template<> void PoolManager::SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
Definition at line 1132 of file PoolManager.cpp.
References mPoolCreatureGroups.
SetExcludeObject() [2/3]
template<> void PoolManager::SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
Definition at line 1138 of file PoolManager.cpp.
References mPoolGameobjectGroups.
SetExcludeObject() [3/3]
template<typename T > void PoolManager::SetExcludeObject (uint16 pool_id, uint32 db_guid_or_pool_id, bool state)
SpawnPool()
void PoolManager::SpawnPool (MapPersistentState & mapState, uint16 pool_id, bool instantly)
Parameters
instantly defines if (leaf-)objects are spawned instantly or with fresh respawn timer
Definition at line 1093 of file PoolManager.cpp.
Referenced by InitSpawnPool().
SpawnPoolGroup() [1/4]
template<> void PoolManager::SpawnPoolGroup (MapPersistentState & mapState, uint16 pool_id, uint32 db_guid, bool instantly) protected
Definition at line 1067 of file PoolManager.cpp.
References mPoolCreatureGroups, and mPoolTemplate.
SpawnPoolGroup() [2/4]
template<> void PoolManager::SpawnPoolGroup (MapPersistentState & mapState, uint16 pool_id, uint32 db_guid, bool instantly) protected
Definition at line 1076 of file PoolManager.cpp.
References mPoolGameobjectGroups, and mPoolTemplate.
SpawnPoolGroup() [3/4]
template<typename T > void PoolManager::SpawnPoolGroup (MapPersistentState & mapState, uint16 pool_id, uint32 db_guid_or_pool_id, bool instantly) protected
SpawnPoolGroup() [4/4]
template<> void PoolManager::SpawnPoolGroup (MapPersistentState & mapState, uint16 pool_id, uint32 sub_pool_id, bool instantly) protected
Definition at line 1085 of file PoolManager.cpp.
References mPoolPoolGroups, and mPoolTemplate.
SpawnPoolInMaps()
void PoolManager::SpawnPoolInMaps (uint16 pool_id, bool instantly)
Definition at line 1175 of file PoolManager.cpp.
References PoolTemplateData::mapEntry, MapEntry::MapID, mPoolTemplate, and sMapPersistentStateMgr.
UpdatePool()
template<typename T > template void PoolManager::UpdatePool< Creature > (MapPersistentState & mapState, uint16 pool_id, uint32 db_guid_or_pool_id = 0)
Definition at line 1147 of file PoolManager.cpp.
UpdatePoolInMaps()
template<typename T > template void PoolManager::UpdatePoolInMaps< Creature > (uint16 pool_id, uint32 db_guid_or_pool_id = 0)
Definition at line 1238 of file PoolManager.cpp.
References PoolTemplateData::mapEntry, MapEntry::MapID, mPoolTemplate, and sMapPersistentStateMgr.
Field Documentation
max_pool_id
uint16 PoolManager::max_pool_id protected
Definition at line 193 of file PoolManager.h.
Referenced by CheckPool(), GetMaxPoolId(), and LoadFromDB().
mCreatureSearchMap
SearchMap PoolManager::mCreatureSearchMap protected
Definition at line 207 of file PoolManager.h.
Referenced by IsPartOfAPool(), and LoadFromDB().
mGameobjectSearchMap
SearchMap PoolManager::mGameobjectSearchMap protected
Definition at line 208 of file PoolManager.h.
Referenced by IsPartOfAPool(), and LoadFromDB().
mPoolCreatureGroups
PoolGroupCreatureMap PoolManager::mPoolCreatureGroups protected
Definition at line 202 of file PoolManager.h.
Referenced by CheckEventLinkAndReport(), CheckPool(), DespawnPool(), GetPoolCreatures(), LoadFromDB(), SetExcludeObject(), and SpawnPoolGroup().
mPoolGameobjectGroups
PoolGroupGameObjectMap PoolManager::mPoolGameobjectGroups protected
Definition at line 203 of file PoolManager.h.
Referenced by CheckEventLinkAndReport(), CheckPool(), DespawnPool(), GetPoolGameObjects(), LoadFromDB(), SetExcludeObject(), and SpawnPoolGroup().
mPoolPoolGroups
PoolGroupPoolMap PoolManager::mPoolPoolGroups protected
Definition at line 204 of file PoolManager.h.
Referenced by CheckEventLinkAndReport(), CheckPool(), DespawnPool(), GetPoolPools(), LoadFromDB(), and SpawnPoolGroup().
mPoolSearchMap
SearchMap PoolManager::mPoolSearchMap protected
Definition at line 209 of file PoolManager.h.
Referenced by IsPartOfAPool(), and LoadFromDB().
mPoolTemplate
PoolTemplateDataMap PoolManager::mPoolTemplate protected
Definition at line 201 of file PoolManager.h.
Referenced by DespawnPoolInMaps(), GetPoolTemplate(), Initialize(), InitSpawnPool(), LoadFromDB(), RemoveAutoSpawnForPool(), SpawnPoolGroup(), SpawnPoolInMaps(), and UpdatePoolInMaps().
The documentation for this class was generated from the following files:
PoolManager.h
PoolManager.cpp