CMaNGOS_WoTLK: MailDraft Class Reference
MailDraft Class Reference
The mail system
The class to represent the draft of a mail.
#include <Mail.h>
Public Member Functions
MailDraft ()
Creates a new blank MailDraft object.
MailDraft (uint16 mailTemplateId, bool need_items=true)
Creates a new MailDraft object using mail template id.
MailDraft (std::string subject, std::string body)
Creates a new MailDraft object using subject and content texts.
uint16 GetMailTemplateId () const
Returns the template ID used for this MailDraft.
std::string const & GetSubject () const
Returns the subject of this MailDraft.
std::string const & GetBody () const
Returns the subject of this MailDraft.
uint32 GetMoney () const
Returns the amount of money in this MailDraft.
uint32 GetCOD () const
Returns the Cost of delivery of this MailDraft.
MailDraft & SetSubjectAndBody (const std::string &subject, const std::string &body)
MailDraft & SetMailTemplate (uint16 mailTemplateId, bool need_items=true)
MailDraft & AddItem (Item *item)
Adds an item to the MailDraft.
MailDraft & SetMoney (uint32 money)
Modifies the amount of money in a MailDraft.
MailDraft & SetCOD (uint32 COD)
Modifies the cost of delivery of the MailDraft.
void CloneFrom (MailDraft const &draft)
Clone MailDraft from another MailDraft.
void SendReturnToSender (uint32 sender_acc, ObjectGuid sender_guid, ObjectGuid receiver_guid)
void SendMailTo (MailReceiver const &receiver, MailSender const &sender, MailCheckMask checked=MAIL_CHECK_MASK_NONE, uint32 deliver_delay=0)
Sends a mail.
Private Types
typedef std::map< uint32, Item * > MailItemMap
Holds a Map of GUIDs of items and pointers to the items.
Private Member Functions
MailDraft (MailDraft const &)
MailDraft & operator= (MailDraft const &)
void deleteIncludedItems (bool inDB=false)
Deletes the items included in a MailDraft.
bool prepareItems (Player *receiver)
called from SendMailTo for generate mailTemplateBase items
Private Attributes
uint16 m_mailTemplateId
The ID of the template associated with this MailDraft.
bool m_mailTemplateItemsNeed
Boolean specifying whether items are required or not.
std::string m_subject
The subject of the MailDraft.
std::string m_body
The body of the MailDraft.
MailItemMap m_items
A map of items in this MailDraft.
uint32 m_money
The amount of money in this MailDraft.
uint32 m_COD
The cod amount of this MailDraft.
Detailed Description
The class to represent the draft of a mail.
Definition at line 183 of file Mail.h.
Member Typedef Documentation
MailItemMap
typedef std::map<uint32, Item*> MailDraft::MailItemMap private
Holds a Map of GUIDs of items and pointers to the items.
Definition at line 188 of file Mail.h.
Constructor & Destructor Documentation
MailDraft() [1/4]
MailDraft::MailDraft () inline
Creates a new blank MailDraft object.
Definition at line 195 of file Mail.h.
MailDraft() [2/4]
MailDraft::MailDraft (uint16 mailTemplateId, bool need_items = true) inline explicit
Creates a new MailDraft object using mail template id.
Parameters
mailTemplateId The ID of the Template to be used.
a boolean specifying whether the mail needs items or not.
Definition at line 204 of file Mail.h.
MailDraft() [3/4]
MailDraft::MailDraft (std::string subject, std::string body) inline
Creates a new MailDraft object using subject and content texts.
Parameters
subject The subject of the mail.
itemText The text of the body of the mail.
Definition at line 213 of file Mail.h.
MailDraft() [4/4]
MailDraft::MailDraft (MailDraft const &) private
Member Function Documentation
GetBody()
std::string const& MailDraft::GetBody () const inline
Returns the subject of this MailDraft.
Definition at line 221 of file Mail.h.
References m_body.
Referenced by CloneFrom(), and SendMailTo().
GetCOD()
uint32 MailDraft::GetCOD () const inline
Returns the Cost of delivery of this MailDraft.
Definition at line 225 of file Mail.h.
References m_COD.
Referenced by CloneFrom(), and SendMailTo().
GetMailTemplateId()
uint16 MailDraft::GetMailTemplateId () const inline
Returns the template ID used for this MailDraft.
Definition at line 217 of file Mail.h.
References m_mailTemplateId.
Referenced by CloneFrom(), and SendMailTo().
GetMoney()
uint32 MailDraft::GetMoney () const inline
Returns the amount of money in this MailDraft.
Definition at line 223 of file Mail.h.
References m_money.
Referenced by CloneFrom(), and SendMailTo().
GetSubject()
std::string const& MailDraft::GetSubject () const inline
Returns the subject of this MailDraft.
Definition at line 219 of file Mail.h.
References m_subject.
Referenced by CloneFrom(), and SendMailTo().
operator=()
MailDraft& MailDraft::operator= (MailDraft const &) private
SetCOD()
MailDraft& MailDraft::SetCOD (uint32 COD) inline
Modifies the cost of delivery of the MailDraft.
Parameters
COD the amount to which the cod should be set.
Definition at line 244 of file Mail.h.
References m_COD.
Referenced by WorldSession::HandleSendMail().
SetMailTemplate()
MailDraft& MailDraft::SetMailTemplate (uint16 mailTemplateId, bool need_items = true) inline
Definition at line 230 of file Mail.h.
References m_mailTemplateId, and m_mailTemplateItemsNeed.
Referenced by Player::DeleteFromDB(), and WorldSession::HandleMailReturnToSender().
SetMoney()
MailDraft& MailDraft::SetMoney (uint32 money) inline
Modifies the amount of money in a MailDraft.
Parameters
money The amount of money included in this MailDraft.
Definition at line 238 of file Mail.h.
References m_money.
Referenced by PlayerbotAI::_HandleCommandMail(), Player::DeleteFromDB(), ScriptAction::ExecuteDbscriptCommand(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleSendMail(), ChatHandler::HandleSendMoneyHelper(), WorldSession::SendAuctionCancelledToBidderMail(), WorldSession::SendAuctionOutbiddedMail(), and AuctionHouseMgr::SendAuctionSuccessfulMail().
SetSubjectAndBody()
MailDraft& MailDraft::SetSubjectAndBody (const std::string & subject, const std::string & body) inline
Definition at line 229 of file Mail.h.
References m_body, and m_subject.
Referenced by Player::DeleteFromDB(), WorldSession::HandleMailReturnToSender(), ChatHandler::HandleSendItemsHelper(), ChatHandler::HandleSendMailHelper(), ChatHandler::HandleSendMoneyHelper(), and BattleGroundMgr::RewardArenaSeason().
Field Documentation
m_body
std::string MailDraft::m_body private
The body of the MailDraft.
Definition at line 264 of file Mail.h.
Referenced by CloneFrom(), GetBody(), and SetSubjectAndBody().
m_COD
uint32 MailDraft::m_COD private
The cod amount of this MailDraft.
Definition at line 271 of file Mail.h.
Referenced by CloneFrom(), GetCOD(), SendMailTo(), and SetCOD().
m_items
MailItemMap MailDraft::m_items private
A map of items in this MailDraft.
Keep the items in a map to avoid duplicate guids (which can happen), store only low part of guid
Definition at line 266 of file Mail.h.
Referenced by AddItem(), CloneFrom(), deleteIncludedItems(), prepareItems(), SendMailTo(), and SendReturnToSender().
m_mailTemplateId
uint16 MailDraft::m_mailTemplateId private
The ID of the template associated with this MailDraft.
Definition at line 258 of file Mail.h.
Referenced by CloneFrom(), GetMailTemplateId(), prepareItems(), and SetMailTemplate().
m_mailTemplateItemsNeed
bool MailDraft::m_mailTemplateItemsNeed private
Boolean specifying whether items are required or not.
Definition at line 260 of file Mail.h.
Referenced by CloneFrom(), prepareItems(), and SetMailTemplate().
m_money
uint32 MailDraft::m_money private
The amount of money in this MailDraft.
Definition at line 269 of file Mail.h.
Referenced by CloneFrom(), GetMoney(), SendMailTo(), and SetMoney().
m_subject
std::string MailDraft::m_subject private
The subject of the MailDraft.
Definition at line 262 of file Mail.h.
Referenced by CloneFrom(), GetSubject(), and SetSubjectAndBody().
The documentation for this class was generated from the following files:
Mail.h
Mail.cpp