CMaNGOS_WoTLK: ShortIntervalTimer Class Reference
ShortIntervalTimer Class Reference
#include <Timer.h>
Public Member Functions
ShortIntervalTimer ()
void Update (uint32 diff)
bool Passed () const
void Reset ()
void SetCurrent (uint32 current)
void SetInterval (uint32 interval)
uint32 GetInterval () const
uint32 GetCurrent () const
Private Attributes
uint32 _interval
uint32 _current
Detailed Description
Definition at line 105 of file Timer.h.
Constructor & Destructor Documentation
ShortIntervalTimer()
ShortIntervalTimer::ShortIntervalTimer () inline
Definition at line 108 of file Timer.h.
Member Function Documentation
GetCurrent()
uint32 ShortIntervalTimer::GetCurrent () const inline
Definition at line 125 of file Timer.h.
Referenced by MirrorTimer::GetRemaining(), MirrorTimer::Update(), and OutdoorPvPMgr::Update().
GetInterval()
uint32 ShortIntervalTimer::GetInterval () const inline
Definition at line 124 of file Timer.h.
Referenced by MirrorTimer::GetDuration(), MirrorTimer::GetRemaining(), MirrorTimer::Update(), and Weather::Weather().
Passed()
bool ShortIntervalTimer::Passed () const inline
Definition at line 115 of file Timer.h.
Referenced by TerrainInfo::CleanUpGrids(), MirrorTimer::Update(), OutdoorPvPMgr::Update(), and Weather::Update().
Reset()
void ShortIntervalTimer::Reset () inline
Definition at line 116 of file Timer.h.
Referenced by TerrainInfo::CleanUpGrids(), MirrorTimer::Update(), OutdoorPvPMgr::Update(), and Weather::Update().
SetCurrent()
void ShortIntervalTimer::SetCurrent (uint32 current) inline
Definition at line 122 of file Timer.h.
Referenced by MirrorTimer::SetRemaining(), MirrorTimer::Start(), MirrorTimer::Stop(), TerrainInfo::TerrainInfo(), and MirrorTimer::Update().
SetInterval()
void ShortIntervalTimer::SetInterval (uint32 interval) inline
Definition at line 123 of file Timer.h.
Referenced by OutdoorPvPMgr::OutdoorPvPMgr(), MirrorTimer::SetDuration(), MirrorTimer::Start(), TerrainInfo::TerrainInfo(), and Weather::Weather().
Update()
void ShortIntervalTimer::Update (uint32 diff) inline
Definition at line 110 of file Timer.h.
Referenced by TerrainInfo::CleanUpGrids(), MirrorTimer::Update(), OutdoorPvPMgr::Update(), and Weather::Update().
Field Documentation
_current
uint32 ShortIntervalTimer::_current private
Definition at line 129 of file Timer.h.
_interval
uint32 ShortIntervalTimer::_interval private
Definition at line 128 of file Timer.h.
The documentation for this class was generated from the following file:
Timer.h