CMaNGOS_WoTLK: instance_violet_hold Class Reference
instance_violet_hold Class Reference
#include <violet_hold.h>
Public Types
typedef std::multimap< uint32, ObjectGuid > BossToCellMap
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Public Member Functions
instance_violet_hold (Map *pMap)
~instance_violet_hold ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void DoReleaseBoss (uint32 entry=0)
uint32 GetRandomPortalEliteEntry () const
uint32 GetRandomMobForNormalPortal () const
uint32 GetCurrentPortalNumber () const
BossInformation const * GetBossInformation (uint32 uiEntry=0)
bool IsCurrentPortalForTrash () const
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureRespawn (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
PortalData const * GetPortalData () const
void StartEvent ()
void ResetEvent ()
void ResetVariables ()
void ResetIntroPortals ()
void ResetGuards ()
void UpdateWorldState (bool bEnable=true)
void UpdateCellForBoss (uint32 uiBossEntry, bool bForceClosing=false)
void DoSpawnIntroMob ()
void SetRandomBosses ()
void SpawnPortal ()
void SetPortalId ()
void UpdateCrystals (bool reset)
void DoClearBossMobs (GuidList &list)
bool IsNextPortalForTrash () const
BossSpawn * CreateBossSpawnByEntry (uint32 uiEntry)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiWorldState
uint32 m_uiWorldStateSealCount
uint32 m_uiWorldStatePortalCount
uint8 m_uiPortalId
uint32 m_uiPortalTimer
uint32 m_uiMaxCountPortalLoc
uint32 m_uiSealYellCount
uint32 m_uiIntroSummonTimer
uint32 m_uiEventResetTimer
uint32 m_uiEventStartTimer
uint32 m_uiCyanigosaMoveTimer
bool m_bIsVoidDance
bool m_bIsDefenseless
bool m_bIsDehydratation
BossToCellMap m_mBossToCellMap
GuidVector m_lIntroPortalVector
GuidList m_lGuardsList
GuidList m_lErekemGuardList
GuidList m_lArakkoaGuardList
GuidList m_lVoidSentriesList
GuidList m_lIchorGlobuleList
GuidList m_lEtherealSphereList
GuidList m_lActivationCrystalList
std::vector< uint32 > m_vRandomBossList
std::vector< BossSpawn * > m_vRandomBosses
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 198 of file violet_hold.h.
Member Typedef Documentation
BossToCellMap
typedef std::multimap<uint32, ObjectGuid> instance_violet_hold::BossToCellMap
Definition at line 243 of file violet_hold.h.
Constructor & Destructor Documentation
instance_violet_hold()
instance_violet_hold::instance_violet_hold (Map * pMap)
Definition at line 27 of file violet_hold.cpp.
References Initialize().
~instance_violet_hold()
instance_violet_hold::~instance_violet_hold ()
Definition at line 962 of file violet_hold.cpp.
References m_vRandomBosses.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_violet_hold::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 681 of file violet_hold.cpp.
References ACHIEV_CRIT_DEFENSELES, ACHIEV_CRIT_DEHYDRATATION, ACHIEV_CRIT_VOID_DANCE, m_bIsDefenseless, m_bIsDehydratation, and m_bIsVoidDance.
CreateBossSpawnByEntry()
BossSpawn * instance_violet_hold::CreateBossSpawnByEntry (uint32 uiEntry) protected
Definition at line 559 of file violet_hold.cpp.
References BossSpawn::fO, BossSpawn::fX, BossSpawn::fY, BossSpawn::fZ, ScriptedInstance::GetSingleCreatureFromStorage(), and BossSpawn::uiEntry.
Referenced by SetRandomBosses().
DoClearBossMobs()
void instance_violet_hold::DoClearBossMobs (GuidList & list) protected
Definition at line 654 of file violet_hold.cpp.
References Map::GetCreature(), and InstanceData::instance.
Referenced by OnCreatureDeath(), and OnCreatureEvade().
DoReleaseBoss()
void instance_violet_hold::DoReleaseBoss (uint32 entry = 0)
Definition at line 602 of file violet_hold.cpp.
References DONE, DoScriptText(), GetBossInformation(), Map::GetCreature(), GetData(), Object::GetEntry(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, BossInformation::iSayEntry, m_lArakkoaGuardList, m_lErekemGuardList, MotionMaster::MoveWaypoint(), script_error_log(), TYPE_EREKEM, BossInformation::uiEntry, BossInformation::uiGhostEntry, BossInformation::uiType, and UpdateCellForBoss().
Referenced by ExecuteChatCommand(), and npc_prison_event_controllerAI::ReceiveAIEvent().
DoSpawnIntroMob()
void instance_violet_hold::DoSpawnIntroMob () protected
Definition at line 662 of file violet_hold.cpp.
References aRandomIntroNpcs, fSealAttackLoc, Map::GetCreature(), InstanceData::instance, m_lIntroPortalVector, script_error_log(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and urand().
Referenced by Update().
ExecuteChatCommand()
void instance_violet_hold::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 939 of file violet_hold.cpp.
References DoReleaseBoss(), ChatHandler::ExtractLiteralArg(), m_uiIntroSummonTimer, NPC_EREKEM, NPC_ICHORON, NPC_LAVANTHOR, NPC_MORAGG, NPC_XEVOZZ, and NPC_ZURAMAT.
GetBossInformation()
BossInformation const * instance_violet_hold::GetBossInformation (uint32 uiEntry = 0)
Definition at line 910 of file violet_hold.cpp.
References aBossInformation, GetCurrentPortalNumber(), and m_vRandomBosses.
Referenced by DoReleaseBoss(), npc_prison_event_controllerAI::JustSummoned(), and ResetEvent().
GetCurrentPortalNumber()
uint32 instance_violet_hold::GetCurrentPortalNumber () const inline
Definition at line 214 of file violet_hold.h.
References m_uiWorldStatePortalCount.
Referenced by GetBossInformation(), npc_teleportation_portalAI::Reset(), SetPortalId(), npc_prison_event_controllerAI::SummonedCreatureJustDied(), and npc_teleportation_portalAI::SummonedCreatureJustDied().
GetData()
uint32 instance_violet_hold::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 479 of file violet_hold.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by DoReleaseBoss(), OnCreatureCreate(), OnCreatureDeath(), and OnPlayerEnter().
GetPortalData()
PortalData const* instance_violet_hold::GetPortalData () const inline protected
Definition at line 246 of file violet_hold.h.
References afPortalLocation, and m_uiPortalId.
Referenced by SpawnPortal().
GetRandomMobForNormalPortal()
uint32 instance_violet_hold::GetRandomMobForNormalPortal () const inline
Definition at line 212 of file violet_hold.h.
References aRandomPortalNpcs, and urand().
Referenced by npc_teleportation_portalAI::DoSummon().
GetRandomPortalEliteEntry()
uint32 instance_violet_hold::GetRandomPortalEliteEntry () const inline
Definition at line 211 of file violet_hold.h.
References aRandomPortalElite, and urand().
Referenced by npc_teleportation_portalAI::DoSummon().
Initialize()
void instance_violet_hold::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 49 of file violet_hold.cpp.
References afPortalLocation, countof, m_auiEncounter, and m_uiMaxCountPortalLoc.
Referenced by instance_violet_hold().
IsCurrentPortalForTrash()
bool instance_violet_hold::IsCurrentPortalForTrash () const inline
Definition at line 218 of file violet_hold.h.
References m_uiWorldStatePortalCount, and MAX_MINIBOSSES.
Referenced by npc_teleportation_portalAI::DoSummon(), and SetPortalId().
IsNextPortalForTrash()
bool instance_violet_hold::IsNextPortalForTrash () const inline protected
Definition at line 267 of file violet_hold.h.
References m_uiWorldStatePortalCount, and MAX_MINIBOSSES.
Load()
void instance_violet_hold::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 486 of file violet_hold.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_violet_hold::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 180 of file violet_hold.cpp.
References GetData(), Object::GetEntry(), Object::GetObjectGuid(), IN_PROGRESS, Creature::IsTemporarySummon(), m_bIsDefenseless, m_lArakkoaGuardList, m_lErekemGuardList, m_lEtherealSphereList, m_lGuardsList, m_lIchorGlobuleList, m_lIntroPortalVector, m_lVoidSentriesList, ScriptedInstance::m_npcEntryGuidStore, m_vRandomBossList, NPC_ARAKKOA, NPC_ARAKKOA_GUARD, NPC_CYANIGOSA, NPC_DEFENSE_SYSTEM, NPC_DOOR_SEAL, NPC_EREKEM, NPC_EREKEM_GUARD, NPC_ETHERAL, NPC_ETHEREAL_SPHERE_1, NPC_ETHEREAL_SPHERE_2, NPC_EVENT_CONTROLLER, NPC_HOLD_GUARD, NPC_ICHOR_GLOBULE, NPC_ICHORON, NPC_LAVA_HOUND, NPC_LAVANTHOR, NPC_MORAGG, NPC_PORTAL_INTRO, NPC_SINCLARI, NPC_SINCLARI_ALT, NPC_SWIRLING, NPC_VOID_LORD, NPC_VOID_SENTRY, NPC_WATCHER, NPC_XEVOZZ, NPC_ZURAMAT, and TYPE_MAIN.
OnCreatureDeath()
void instance_violet_hold::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 795 of file violet_hold.cpp.
References DoClearBossMobs(), DONE, GetData(), Object::GetEntry(), IN_PROGRESS, m_bIsVoidDance, m_lEtherealSphereList, m_lIchorGlobuleList, m_lVoidSentriesList, NPC_ARAKKOA, NPC_CYANIGOSA, NPC_EREKEM, NPC_ETHERAL, NPC_ICHORON, NPC_LAVA_HOUND, NPC_LAVANTHOR, NPC_MORAGG, NPC_SWIRLING, NPC_VOID_LORD, NPC_VOID_SENTRY, NPC_WATCHER, NPC_XEVOZZ, NPC_ZURAMAT, SetData(), TYPE_CYANIGOSA, TYPE_EREKEM, TYPE_ICHORON, TYPE_LAVANTHOR, TYPE_MORAGG, TYPE_XEVOZZ, and TYPE_ZURAMAT.
OnCreatureEnterCombat()
void instance_violet_hold::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 697 of file violet_hold.cpp.
References Object::GetEntry(), IN_PROGRESS, Unit::InterruptNonMeleeSpells(), NPC_ARAKKOA, NPC_AZURE_BINDER, NPC_AZURE_CAPTAIN, NPC_AZURE_INVADER, NPC_AZURE_MAGE_SLAYER, NPC_AZURE_RAIDER, NPC_AZURE_SORCEROR, NPC_AZURE_SPELLBREAKER, NPC_AZURE_STALKER, NPC_CYANIGOSA, NPC_EREKEM, NPC_ETHERAL, NPC_ICHORON, NPC_LAVA_HOUND, NPC_LAVANTHOR, NPC_MAGE_HUNTER, NPC_MORAGG, NPC_SWIRLING, NPC_VOID_LORD, NPC_WATCHER, NPC_XEVOZZ, NPC_ZURAMAT, SetData(), TYPE_CYANIGOSA, TYPE_EREKEM, TYPE_ICHORON, TYPE_LAVANTHOR, TYPE_MORAGG, TYPE_XEVOZZ, and TYPE_ZURAMAT.
OnCreatureEvade()
void instance_violet_hold::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 743 of file violet_hold.cpp.
References DoClearBossMobs(), FAIL, fSealAttackLoc, Object::GetEntry(), Unit::GetMotionMaster(), m_lEtherealSphereList, m_lIchorGlobuleList, m_lVoidSentriesList, MotionMaster::MovePoint(), NPC_ARAKKOA, NPC_AZURE_BINDER, NPC_AZURE_CAPTAIN, NPC_AZURE_INVADER, NPC_AZURE_MAGE_SLAYER, NPC_AZURE_RAIDER, NPC_AZURE_SORCEROR, NPC_AZURE_SPELLBREAKER, NPC_AZURE_STALKER, NPC_CYANIGOSA, NPC_EREKEM, NPC_EREKEM_GUARD, NPC_ETHERAL, NPC_ICHORON, NPC_LAVA_HOUND, NPC_LAVANTHOR, NPC_MAGE_HUNTER, NPC_MORAGG, NPC_SWIRLING, NPC_VOID_LORD, NPC_WATCHER, NPC_XEVOZZ, NPC_ZURAMAT, SetData(), Creature::SetWalk(), TYPE_CYANIGOSA, TYPE_EREKEM, TYPE_ICHORON, TYPE_LAVANTHOR, TYPE_MORAGG, TYPE_XEVOZZ, and TYPE_ZURAMAT.
OnCreatureRespawn()
void instance_violet_hold::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 244 of file violet_hold.cpp.
References Creature::AI(), Object::GetEntry(), m_uiCyanigosaMoveTimer, NPC_CYANIGOSA, NPC_VOID_SENTRY_BALL, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_violet_hold::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 259 of file violet_hold.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_CELL_EREKEM, GO_CELL_EREKEM_GUARD_L, GO_CELL_EREKEM_GUARD_R, GO_CELL_ICHORON, GO_CELL_LAVANTHOR, GO_CELL_MORAGG, GO_CELL_XEVOZZ, GO_CELL_ZURAMAT, GO_INTRO_CRYSTAL, GO_PRISON_CRYSTAL, GO_PRISON_SEAL_DOOR, ScriptedInstance::m_goEntryGuidStore, m_lActivationCrystalList, m_mBossToCellMap, NPC_EREKEM, NPC_ICHORON, NPC_LAVANTHOR, NPC_MORAGG, NPC_XEVOZZ, and NPC_ZURAMAT.
OnPlayerEnter()
void instance_violet_hold::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 329 of file violet_hold.cpp.
References GetData(), IN_PROGRESS, m_auiEncounter, m_uiIntroSummonTimer, m_vRandomBosses, NOT_STARTED, ResetEvent(), SetRandomBosses(), TYPE_MAIN, and UpdateWorldState().
ResetEvent()
void instance_violet_hold::ResetEvent () protected
Definition at line 78 of file violet_hold.cpp.
References DONE, FAIL, GetBossInformation(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_auiEncounter, m_lArakkoaGuardList, m_lErekemGuardList, m_vRandomBosses, NOT_STARTED, NPC_ARAKKOA_GUARD, NPC_EVENT_CONTROLLER, NPC_SINCLARI, NPC_SINCLARI_ALT, ResetGuards(), ResetIntroPortals(), ResetVariables(), SetData(), TEMPSPAWN_DEAD_DESPAWN, TYPE_EREKEM, TYPE_MAIN, BossInformation::uiEntry, BossInformation::uiGhostEntry, BossInformation::uiType, UpdateCellForBoss(), UpdateCrystals(), and UpdateWorldState().
Referenced by OnPlayerEnter(), and Update().
ResetGuards()
void instance_violet_hold::ResetGuards () protected
Definition at line 639 of file violet_hold.cpp.
References Map::GetCreature(), InstanceData::instance, and m_lGuardsList.
Referenced by ResetEvent().
ResetIntroPortals()
void instance_violet_hold::ResetIntroPortals () protected
Definition at line 511 of file violet_hold.cpp.
References Map::GetCreature(), InstanceData::instance, and m_lIntroPortalVector.
Referenced by ResetEvent().
ResetVariables()
void instance_violet_hold::ResetVariables () protected
Definition at line 55 of file violet_hold.cpp.
References m_uiIntroSummonTimer, m_uiSealYellCount, m_uiWorldStatePortalCount, and m_uiWorldStateSealCount.
Referenced by ResetEvent().
Save()
const char* instance_violet_hold::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 238 of file violet_hold.h.
References m_strInstData.
SetData()
void instance_violet_hold::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 345 of file violet_hold.cpp.
References aSealWeakYell, debug_log(), DONE, DoScriptText(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), GO_PRISON_SEAL_DOOR, IN_PROGRESS, m_auiEncounter, m_bIsDefenseless, m_bIsDehydratation, m_bIsVoidDance, m_strInstData, m_uiEventResetTimer, m_uiEventStartTimer, m_uiIntroSummonTimer, m_uiPortalTimer, m_uiSealYellCount, m_uiWorldStateSealCount, NOT_STARTED, NPC_EVENT_CONTROLLER, NPC_SINCLARI_ALT, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, StartEvent(), TYPE_CYANIGOSA, TYPE_EREKEM, TYPE_ICHORON, TYPE_LAVANTHOR, TYPE_MAIN, TYPE_MORAGG, TYPE_PORTAL, TYPE_SEAL, TYPE_XEVOZZ, TYPE_ZURAMAT, UpdateWorldState(), and WORLD_STATE_SEAL.
Referenced by npc_teleportation_portalAI::DoSummon(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), boss_ichoronAI::ReceiveAIEvent(), ResetEvent(), npc_prison_event_controllerAI::SummonedCreatureJustDied(), npc_teleportation_portalAI::SummonedCreatureJustDied(), and Update().
SetPortalId()
void instance_violet_hold::SetPortalId () protected
Definition at line 533 of file violet_hold.cpp.
References debug_log(), GetCurrentPortalNumber(), IsCurrentPortalForTrash(), m_uiMaxCountPortalLoc, m_uiPortalId, and urand().
Referenced by Update().
SetRandomBosses()
void instance_violet_hold::SetRandomBosses () protected
Definition at line 571 of file violet_hold.cpp.
References aBossInformation, CreateBossSpawnByEntry(), debug_log(), DONE, GetRandomGenerator(), m_auiEncounter, m_vRandomBosses, m_vRandomBossList, and script_error_log().
Referenced by OnPlayerEnter().
ShowChatCommands()
void instance_violet_hold::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 933 of file violet_hold.cpp.
References ChatHandler::SendSysMessage().
SpawnPortal()
void instance_violet_hold::SpawnPortal () protected
Definition at line 519 of file violet_hold.cpp.
References GetPortalData(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, NPC_PORTAL, NPC_PORTAL_ELITE, NPC_SINCLARI_ALT, PORTAL_TYPE_NORM, and TEMPSPAWN_TIMED_OOC_OR_CORPSE_DESPAWN.
Referenced by Update().
StartEvent()
void instance_violet_hold::StartEvent () protected
Definition at line 64 of file violet_hold.cpp.
References ScriptedInstance::DoUseDoorOrButton(), GO_PRISON_SEAL_DOOR, m_bIsDefenseless, m_uiPortalId, m_uiPortalTimer, UpdateCrystals(), UpdateWorldState(), and urand().
Referenced by SetData().
Update()
void instance_violet_hold::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 836 of file violet_hold.cpp.
References afPortalLocation, DoSpawnIntroMob(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, m_auiEncounter, m_uiCyanigosaMoveTimer, m_uiEventResetTimer, m_uiEventStartTimer, m_uiIntroSummonTimer, m_uiPortalTimer, m_uiWorldStatePortalCount, MOVE_RUN, NPC_CYANIGOSA, ResetEvent(), SetData(), SetPortalId(), SpawnPortal(), TYPE_MAIN, urand(), and WORLD_STATE_PORTALS.
UpdateCellForBoss()
void instance_violet_hold::UpdateCellForBoss (uint32 uiBossEntry, bool bForceClosing = false) protected
Definition at line 299 of file violet_hold.cpp.
References ScriptedInstance::DoUseDoorOrButton(), GAMEOBJECT_TYPE_DOOR, Map::GetGameObject(), GameObject::GetGoState(), GameObject::GetGoType(), GO_STATE_ACTIVE, InstanceData::instance, m_mBossToCellMap, and GameObject::ResetDoorOrButton().
Referenced by DoReleaseBoss(), and ResetEvent().
UpdateCrystals()
void instance_violet_hold::UpdateCrystals (bool reset) protected
Definition at line 647 of file violet_hold.cpp.
References ScriptedInstance::DoToggleGameObjectFlags(), GO_FLAG_NO_INTERACT, and m_lActivationCrystalList.
Referenced by ResetEvent(), and StartEvent().
UpdateWorldState()
void instance_violet_hold::UpdateWorldState (bool bEnable = true) protected
Definition at line 320 of file violet_hold.cpp.
References ScriptedInstance::DoUpdateWorldState(), m_uiWorldState, m_uiWorldStatePortalCount, m_uiWorldStateSealCount, WORLD_STATE_ID, WORLD_STATE_PORTALS, and WORLD_STATE_SEAL.
Referenced by OnPlayerEnter(), ResetEvent(), SetData(), and StartEvent().
Field Documentation
m_auiEncounter
uint32 instance_violet_hold::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 274 of file violet_hold.h.
Referenced by GetData(), Initialize(), Load(), OnPlayerEnter(), ResetEvent(), SetData(), SetRandomBosses(), and Update().
m_bIsDefenseless
bool instance_violet_hold::m_bIsDefenseless protected
Definition at line 292 of file violet_hold.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureCreate(), SetData(), and StartEvent().
m_bIsDehydratation
bool instance_violet_hold::m_bIsDehydratation protected
Definition at line 293 of file violet_hold.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_bIsVoidDance
bool instance_violet_hold::m_bIsVoidDance protected
Definition at line 291 of file violet_hold.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureDeath(), and SetData().
m_lActivationCrystalList
GuidList instance_violet_hold::m_lActivationCrystalList protected
Definition at line 304 of file violet_hold.h.
Referenced by OnObjectCreate(), and UpdateCrystals().
m_lArakkoaGuardList
GuidList instance_violet_hold::m_lArakkoaGuardList protected
Definition at line 300 of file violet_hold.h.
Referenced by DoReleaseBoss(), OnCreatureCreate(), and ResetEvent().
m_lErekemGuardList
GuidList instance_violet_hold::m_lErekemGuardList protected
Definition at line 299 of file violet_hold.h.
Referenced by DoReleaseBoss(), OnCreatureCreate(), and ResetEvent().
m_lEtherealSphereList
GuidList instance_violet_hold::m_lEtherealSphereList protected
Definition at line 303 of file violet_hold.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and OnCreatureEvade().
m_lGuardsList
GuidList instance_violet_hold::m_lGuardsList protected
Definition at line 298 of file violet_hold.h.
Referenced by OnCreatureCreate(), and ResetGuards().
m_lIchorGlobuleList
GuidList instance_violet_hold::m_lIchorGlobuleList protected
Definition at line 302 of file violet_hold.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and OnCreatureEvade().
m_lIntroPortalVector
GuidVector instance_violet_hold::m_lIntroPortalVector protected
Definition at line 297 of file violet_hold.h.
Referenced by DoSpawnIntroMob(), OnCreatureCreate(), and ResetIntroPortals().
m_lVoidSentriesList
GuidList instance_violet_hold::m_lVoidSentriesList protected
Definition at line 301 of file violet_hold.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and OnCreatureEvade().
m_mBossToCellMap
BossToCellMap instance_violet_hold::m_mBossToCellMap protected
Definition at line 295 of file violet_hold.h.
Referenced by OnObjectCreate(), and UpdateCellForBoss().
m_strInstData
std::string instance_violet_hold::m_strInstData protected
Definition at line 275 of file violet_hold.h.
Referenced by Save(), and SetData().
m_uiCyanigosaMoveTimer
uint32 instance_violet_hold::m_uiCyanigosaMoveTimer protected
Definition at line 289 of file violet_hold.h.
Referenced by OnCreatureRespawn(), and Update().
m_uiEventResetTimer
uint32 instance_violet_hold::m_uiEventResetTimer protected
Definition at line 287 of file violet_hold.h.
Referenced by SetData(), and Update().
m_uiEventStartTimer
uint32 instance_violet_hold::m_uiEventStartTimer protected
Definition at line 288 of file violet_hold.h.
Referenced by SetData(), and Update().
m_uiIntroSummonTimer
uint32 instance_violet_hold::m_uiIntroSummonTimer protected
Definition at line 286 of file violet_hold.h.
Referenced by ExecuteChatCommand(), OnPlayerEnter(), ResetVariables(), SetData(), and Update().
m_uiMaxCountPortalLoc
uint32 instance_violet_hold::m_uiMaxCountPortalLoc protected
Definition at line 283 of file violet_hold.h.
Referenced by Initialize(), and SetPortalId().
m_uiPortalId
uint8 instance_violet_hold::m_uiPortalId protected
Definition at line 281 of file violet_hold.h.
Referenced by GetPortalData(), SetPortalId(), and StartEvent().
m_uiPortalTimer
uint32 instance_violet_hold::m_uiPortalTimer protected
Definition at line 282 of file violet_hold.h.
Referenced by SetData(), StartEvent(), and Update().
m_uiSealYellCount
uint32 instance_violet_hold::m_uiSealYellCount protected
Definition at line 285 of file violet_hold.h.
Referenced by ResetVariables(), and SetData().
m_uiWorldState
uint32 instance_violet_hold::m_uiWorldState protected
Definition at line 277 of file violet_hold.h.
Referenced by UpdateWorldState().
m_uiWorldStatePortalCount
uint32 instance_violet_hold::m_uiWorldStatePortalCount protected
Definition at line 279 of file violet_hold.h.
Referenced by GetCurrentPortalNumber(), IsCurrentPortalForTrash(), IsNextPortalForTrash(), ResetVariables(), Update(), and UpdateWorldState().
m_uiWorldStateSealCount
uint32 instance_violet_hold::m_uiWorldStateSealCount protected
Definition at line 278 of file violet_hold.h.
Referenced by ResetVariables(), SetData(), and UpdateWorldState().
m_vRandomBosses
std::vector<BossSpawn*> instance_violet_hold::m_vRandomBosses protected
Definition at line 307 of file violet_hold.h.
Referenced by GetBossInformation(), OnPlayerEnter(), ResetEvent(), SetRandomBosses(), and ~instance_violet_hold().
m_vRandomBossList
std::vector<uint32> instance_violet_hold::m_vRandomBossList protected
Definition at line 305 of file violet_hold.h.
Referenced by OnCreatureCreate(), and SetRandomBosses().
The documentation for this class was generated from the following files:
violet_hold.h
violet_hold.cpp