CMaNGOS_WoTLK: instance_trial_of_the_crusader Class Reference
instance_trial_of_the_crusader Class Reference
#include <trial_of_the_crusader.h>
Public Member Functions
instance_trial_of_the_crusader (Map *pMap)
void Initialize () override
bool IsEncounterInProgress () const override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnPlayerEnter (Player *pPlayer) override
void OnPlayerDeath (Player *pPlayer) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
bool IsHeroicDifficulty () const
bool Is25ManDifficulty () const
uint32 GetPlayerTeam () const
void GetStalkersGUIDVector (GuidVector &vVector) const
const char * Save () const override
void Load (const char *chrIn) override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget=nullptr, uint32 uiMiscvalue1=0) const override
void DoSetCrusadersInCombat (Unit *pTarget)
void DoOpenMainGate (uint32 uiResetTimer)
void Update (const uint32 diff) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void DoSummonRamsey (uint32 uiEntry)
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoHandleEventEpilogue ()
void DoSelectCrusaders ()
void DoCleanupCrusaders ()
void HandleDestroyFloor ()
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
std::vector< uint32 > m_vCrusadersEntries
GuidVector m_vCrusadersGuidsVector
GuidVector m_vStalkersGuidsVector
GuidList m_lSummonedGuidsList
Team m_uiTeam
uint32 m_uiGateResetTimer
uint32 m_uiKilledCrusaders
uint32 m_uiCrusadersAchievTimer
bool m_bCrusadersSummoned
bool m_bCrusadersAchievCheck
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 284 of file trial_of_the_crusader.h.
Constructor & Destructor Documentation
instance_trial_of_the_crusader()
instance_trial_of_the_crusader::instance_trial_of_the_crusader (Map * pMap)
Definition at line 153 of file trial_of_the_crusader.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_trial_of_the_crusader::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget = nullptr, uint32 uiMiscvalue1 = 0) const override virtual
Reimplemented from InstanceData.
Definition at line 541 of file trial_of_the_crusader.cpp.
References ACHIEV_CRIT_PAIN_SPIKE_10_H, ACHIEV_CRIT_PAIN_SPIKE_10_N, ACHIEV_CRIT_PAIN_SPIKE_25_H, ACHIEV_CRIT_PAIN_SPIKE_25_N, ACHIEV_CRIT_TRIBUTE_IMMORTALITY_A, ACHIEV_CRIT_TRIBUTE_IMMORTALITY_H, ACHIEV_CRIT_TRIBUTE_INSANITY_10, ACHIEV_CRIT_TRIBUTE_INSANITY_25, ACHIEV_CRIT_TRIBUTE_MAD_SKILL_10_1, ACHIEV_CRIT_TRIBUTE_MAD_SKILL_10_2, ACHIEV_CRIT_TRIBUTE_MAD_SKILL_25_1, ACHIEV_CRIT_TRIBUTE_MAD_SKILL_25_2, ACHIEV_CRIT_TRIBUTE_SKILL_10_1, ACHIEV_CRIT_TRIBUTE_SKILL_10_2, ACHIEV_CRIT_TRIBUTE_SKILL_10_3, ACHIEV_CRIT_TRIBUTE_SKILL_25_1, ACHIEV_CRIT_TRIBUTE_SKILL_25_2, ACHIEV_CRIT_TRIBUTE_SKILL_25_3, ACHIEV_CRIT_UPPER_BACK_PAIN_10_H, ACHIEV_CRIT_UPPER_BACK_PAIN_10_N, ACHIEV_CRIT_UPPER_BACK_PAIN_25_H, ACHIEV_CRIT_UPPER_BACK_PAIN_25_N, DONE, GetData(), m_lSummonedGuidsList, MIN_ACHIEV_MISTRESSES, MIN_ACHIEV_SNOBOLDS_10, MIN_ACHIEV_SNOBOLDS_25, TYPE_IMMORTALITY_FAILED, and TYPE_WIPE_COUNT.
DoCleanupCrusaders()
void instance_trial_of_the_crusader::DoCleanupCrusaders () private
Definition at line 699 of file trial_of_the_crusader.cpp.
References Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_vCrusadersGuidsVector, NPC_CAT, and NPC_ZHAAGRYM.
Referenced by SetData().
DoHandleEventEpilogue()
void instance_trial_of_the_crusader::DoHandleEventEpilogue () private
Definition at line 602 of file trial_of_the_crusader.cpp.
References aSpawnPositions, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), GetData(), ScriptedInstance::GetPlayerInMap(), GO_PORTAL_DALARAN, GO_TRIBUTE_CHEST_10H_01, GO_TRIBUTE_CHEST_10H_25, GO_TRIBUTE_CHEST_10H_45, GO_TRIBUTE_CHEST_10H_50, GO_TRIBUTE_CHEST_25H_01, GO_TRIBUTE_CHEST_25H_25, GO_TRIBUTE_CHEST_25H_45, GO_TRIBUTE_CHEST_25H_50, Is25ManDifficulty(), IsHeroicDifficulty(), MINUTE, NPC_ARGENT_MAGE, NPC_TIRION_B, SAY_TIRION_EPILOGUE, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, and TYPE_WIPE_COUNT.
Referenced by SetData().
DoOpenMainGate()
void instance_trial_of_the_crusader::DoOpenMainGate (uint32 uiResetTimer)
Definition at line 647 of file trial_of_the_crusader.cpp.
References ScriptedInstance::DoUseDoorOrButton(), GO_MAIN_GATE, and m_uiGateResetTimer.
Referenced by JustDidDialogueStep(), and npc_beast_combat_stalkerAI::JustSummoned().
DoSelectCrusaders()
void instance_trial_of_the_crusader::DoSelectCrusaders () private
Definition at line 654 of file trial_of_the_crusader.cpp.
References aAllyHealerCrusaders, aAllyOtherCrusaders, aAllyReplacementCrusaders, aHordeHealerCrusaders, aHordeOtherCrusaders, aHordeReplacementCrusaders, ALLIANCE, Is25ManDifficulty(), m_uiTeam, m_vCrusadersEntries, MAX_CRUSADERS_HEALERS, MAX_CRUSADERS_OTHER, and urand().
Referenced by OnPlayerEnter().
DoSetCrusadersInCombat()
void instance_trial_of_the_crusader::DoSetCrusadersInCombat (Unit * pTarget)
Definition at line 631 of file trial_of_the_crusader.cpp.
References Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Is25ManDifficulty(), m_vCrusadersGuidsVector, MAX_CRUSADERS_10MAN, MAX_CRUSADERS_25MAN, NPC_CAT, and NPC_ZHAAGRYM.
Referenced by trial_crusader_commonAI::Aggro().
DoSummonRamsey()
void instance_trial_of_the_crusader::DoSummonRamsey (uint32 uiEntry) private
Definition at line 579 of file trial_of_the_crusader.cpp.
References aRamsayPositions, DONE, ScriptedInstance::GetPlayerInMap(), m_auiEncounter, NPC_RAMSEY_1, NPC_RAMSEY_2, NPC_RAMSEY_3, NPC_RAMSEY_4, NPC_RAMSEY_5, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_FACTION_CHAMPIONS, TYPE_JARAXXUS, TYPE_NORTHREND_BEASTS, and TYPE_TWIN_VALKYR.
Referenced by JustDidDialogueStep(), and OnPlayerEnter().
ExecuteChatCommand()
void instance_trial_of_the_crusader::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 940 of file trial_of_the_crusader.cpp.
References ChatHandler::ExtractLiteralArg(), and HandleDestroyFloor().
GetData()
uint32 instance_trial_of_the_crusader::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 439 of file trial_of_the_crusader.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by boss_fjolaAI::Aggro(), trial_crusader_commonAI::Aggro(), CheckAchievementCriteriaMeet(), DoHandleEventEpilogue(), boss_jaraxxusAI::EnterEvadeMode(), boss_fjolaAI::EnterEvadeMode(), boss_fjolaAI::JustDied(), trial_crusader_commonAI::JustReachedHome(), OnPlayerEnter(), and SetData().
GetPlayerTeam()
uint32 instance_trial_of_the_crusader::GetPlayerTeam () const inline
Definition at line 308 of file trial_of_the_crusader.h.
References m_uiTeam.
Referenced by trial_crusader_commonAI::KilledUnit(), and trial_crusader_commonAI::UpdateAI().
GetStalkersGUIDVector()
void instance_trial_of_the_crusader::GetStalkersGUIDVector (GuidVector & vVector) const inline
Definition at line 309 of file trial_of_the_crusader.h.
References m_vStalkersGuidsVector.
Referenced by npc_concentrated_bulletAI::Reset().
HandleDestroyFloor()
void instance_trial_of_the_crusader::HandleDestroyFloor () private
Definition at line 925 of file trial_of_the_crusader.cpp.
References DISPLAYID_DESTROYED_FLOOR, GAMEOBJECT_FLAGS, ScriptedInstance::GetSingleGameObjectFromStorage(), GO_COLISEUM_FLOOR, GO_FLAG_DAMAGED, GO_FLAG_NODESPAWN, and GO_STATE_ACTIVE.
Referenced by ExecuteChatCommand(), and JustDidDialogueStep().
Initialize()
void instance_trial_of_the_crusader::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 164 of file trial_of_the_crusader.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_trial_of_the_crusader().
Is25ManDifficulty()
bool instance_trial_of_the_crusader::Is25ManDifficulty () const inline
Definition at line 306 of file trial_of_the_crusader.h.
References Map::GetDifficulty(), InstanceData::instance, RAID_DIFFICULTY_25MAN_HEROIC, and RAID_DIFFICULTY_25MAN_NORMAL.
Referenced by DoHandleEventEpilogue(), DoSelectCrusaders(), DoSetCrusadersInCombat(), JustDidDialogueStep(), and OnCreatureDeath().
IsEncounterInProgress()
bool instance_trial_of_the_crusader::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 170 of file trial_of_the_crusader.cpp.
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, and TYPE_NORTHREND_BEASTS.
Referenced by OnPlayerDeath().
IsHeroicDifficulty()
bool instance_trial_of_the_crusader::IsHeroicDifficulty () const inline
Definition at line 305 of file trial_of_the_crusader.h.
References Map::GetDifficulty(), InstanceData::instance, RAID_DIFFICULTY_10MAN_HEROIC, and RAID_DIFFICULTY_25MAN_HEROIC.
Referenced by DoHandleEventEpilogue(), OnPlayerEnter(), boss_fjolaAI::Reset(), SetData(), boss_anubarak_trialAI::SpellHit(), boss_anubarak_trialAI::UpdateAI(), trial_crusader_commonAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_fjolaAI::UpdateAI(), and boss_eydisAI::UpdateAI().
JustDidDialogueStep()
void instance_trial_of_the_crusader::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 714 of file trial_of_the_crusader.cpp.
References aAllyCrusadersLoc, aHordeCrusadersLoc, AI_EVENT_CUSTOM_A, ALLIANCE, aMovePositions, aSpawnPositions, DoOpenMainGate(), DoSummonRamsey(), ScriptedInstance::DoUseDoorOrButton(), EVENT_ARTHAS_PORTAL, EVENT_CHAMPIONS_ATTACK, EVENT_DESTROY_FLOOR, EVENT_JARAXXUS_START_ATTACK, EVENT_KILL_FIZZLEBANG, EVENT_OPEN_PORTAL, EVENT_SUMMON_THE_LICHKING, EVENT_SUMMON_TWINS, EVENT_TWINS_ATTACK, CrusadersLocation::fSourceO, CrusadersLocation::fSourceX, CrusadersLocation::fSourceY, CrusadersLocation::fSourceZ, CrusadersLocation::fTargetX, CrusadersLocation::fTargetY, CrusadersLocation::fTargetZ, Map::GetCreature(), ScriptedInstance::GetPlayerInMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_MAIN_GATE, HandleDestroyFloor(), InstanceData::instance, Is25ManDifficulty(), m_bCrusadersSummoned, m_uiTeam, m_vCrusadersEntries, m_vCrusadersGuidsVector, MAX_CRUSADERS_10MAN, MAX_CRUSADERS_25MAN, NPC_BEASTS_COMBAT_STALKER, NPC_EYDIS, NPC_FIZZLEBANG, NPC_FJOLA, NPC_GORMOK, NPC_JARAXXUS, NPC_OPEN_PORTAL_TARGET, NPC_PURPLE_RUNE, NPC_RAMSEY_1, NPC_RAMSEY_2, NPC_RAMSEY_3, NPC_RAMSEY_4, NPC_RAMSEY_5, NPC_SNOBOLD_VASSAL, NPC_THE_LICHKING, NPC_THE_LICHKING_VISUAL, NPC_WORLD_TRIGGER_LARGE, POINT_COMBAT_POSITION, SAY_GARROSH_PVP_A_INTRO_2, SAY_LKING_ANUB_INTRO_1, SAY_TIRION_PVP_INTRO_1, SAY_VARIAN_BEAST_1, SAY_WILFRED_JARAXXUS_INTRO_1, SAY_WILFRED_JARAXXUS_INTRO_2, SAY_WILFRED_JARAXXUS_INTRO_3, script_error_log(), SPELL_ANCHOR_HERE, SPELL_ARTHAS_PORTAL, SPELL_DESTROY_FLOOR_KNOCKUP, SPELL_ENSLAVE_JARAXXUS, SPELL_FEL_LIGHTNING_KILL, SPELL_FROSTNOVA, SPELL_OPEN_PORTAL, SPELL_RIDE_VEHICLE_HARDCODED, SPELL_TWIN_EMPATHY_DARK, SPELL_TWIN_EMPATHY_LIGHT, SPELL_WILFRED_PORTAL, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPE_FACTION_CHAMPIONS, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Load()
void instance_trial_of_the_crusader::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 447 of file trial_of_the_crusader.cpp.
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, and TYPE_NORTHREND_BEASTS.
OnCreatureCreate()
void instance_trial_of_the_crusader::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 181 of file trial_of_the_crusader.cpp.
References ScriptedInstance::DoUseDoorOrButton(), Object::GetEntry(), Object::GetObjectGuid(), GO_MAIN_GATE, m_lSummonedGuidsList, ScriptedInstance::m_npcEntryGuidStore, m_vStalkersGuidsVector, NPC_ACIDMAW, NPC_ANUBARAK, NPC_BEASTS_COMBAT_STALKER, NPC_CAT, NPC_DREADSCALE, NPC_EYDIS, NPC_FIZZLEBANG, NPC_FJOLA, NPC_GARROSH, NPC_JARAXXUS, NPC_MISTRESS_OF_PAIN, NPC_OPEN_PORTAL_TARGET, NPC_SNOBOLD_VASSAL, NPC_THE_LICHKING, NPC_THE_LICHKING_VISUAL, NPC_TIRION_A, NPC_TIRION_B, NPC_VALKYR_STALKER_DARK, NPC_VALKYR_STALKER_LIGHT, NPC_VARIAN, NPC_WORLD_TRIGGER_LARGE, and NPC_ZHAAGRYM.
OnCreatureDeath()
void instance_trial_of_the_crusader::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 468 of file trial_of_the_crusader.cpp.
References Unit::CastSpell(), DONE, Object::GetEntry(), Object::GetObjectGuid(), Is25ManDifficulty(), m_bCrusadersAchievCheck, m_lSummonedGuidsList, m_uiCrusadersAchievTimer, m_uiKilledCrusaders, MAX_CRUSADERS_10MAN, MAX_CRUSADERS_25MAN, NPC_ALLY_DEATH_KNIGHT, NPC_ALLY_DRUID_BALANCE, NPC_ALLY_DRUID_RESTO, NPC_ALLY_HUNTER, NPC_ALLY_MAGE, NPC_ALLY_PALADIN_HOLY, NPC_ALLY_PALADIN_RETRI, NPC_ALLY_PRIEST_DISC, NPC_ALLY_PRIEST_SHADOW, NPC_ALLY_ROGUE, NPC_ALLY_SHAMAN_ENHA, NPC_ALLY_SHAMAN_RESTO, NPC_ALLY_WARLOCK, NPC_ALLY_WARRIOR, NPC_HORDE_DEATH_KNIGHT, NPC_HORDE_DRUID_BALANCE, NPC_HORDE_DRUID_RESTO, NPC_HORDE_HUNTER, NPC_HORDE_MAGE, NPC_HORDE_PALADIN_HOLY, NPC_HORDE_PALADIN_RETRI, NPC_HORDE_PRIEST_DISC, NPC_HORDE_PRIEST_SHADOW, NPC_HORDE_ROGUE, NPC_HORDE_SHAMAN_ENHA, NPC_HORDE_SHAMAN_RESTO, NPC_HORDE_WARLOCK, NPC_HORDE_WARRIOR, NPC_MISTRESS_OF_PAIN, NPC_SNOBOLD_VASSAL, SetData(), SPELL_ENCOUNTER_KILL_CREDIT, SPELL_RESILIENCE_FIX_CREDIT, TRIGGERED_OLD_TRIGGERED, and TYPE_FACTION_CHAMPIONS.
OnCreatureEvade()
void instance_trial_of_the_crusader::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 529 of file trial_of_the_crusader.cpp.
References Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_ANUBARAK, NPC_NERUBIAN_BURROWER, and NPC_SCARAB.
OnCreatureRespawn()
void instance_trial_of_the_crusader::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 220 of file trial_of_the_crusader.cpp.
References Creature::AI(), Object::GetEntry(), NPC_NERUBIAN_BURROW, NPC_VALKYR_STALKER_DARK, NPC_VALKYR_STALKER_LIGHT, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_trial_of_the_crusader::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 234 of file trial_of_the_crusader.cpp.
References DISPLAYID_DESTROYED_FLOOR, DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_COLISEUM_FLOOR, GO_CRUSADERS_CACHE, GO_CRUSADERS_CACHE_10_H, GO_CRUSADERS_CACHE_25, GO_CRUSADERS_CACHE_25_H, GO_FLAG_DAMAGED, GO_FLAG_NODESPAWN, GO_MAIN_GATE, GO_NORTH_GATE, GO_PORTAL_DALARAN, GO_STATE_ACTIVE, GO_TRIBUTE_CHEST_10H_01, GO_TRIBUTE_CHEST_10H_25, GO_TRIBUTE_CHEST_10H_45, GO_TRIBUTE_CHEST_10H_50, GO_TRIBUTE_CHEST_25H_01, GO_TRIBUTE_CHEST_25H_25, GO_TRIBUTE_CHEST_25H_45, GO_TRIBUTE_CHEST_25H_50, GO_WEB_DOOR, GO_WEST_GATE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetDisplayId(), Object::SetFlag(), GameObject::SetGoState(), and TYPE_TWIN_VALKYR.
OnPlayerDeath()
void instance_trial_of_the_crusader::OnPlayerDeath (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 291 of file trial_of_the_crusader.cpp.
References DONE, IsEncounterInProgress(), SetData(), and TYPE_IMMORTALITY_FAILED.
OnPlayerEnter()
void instance_trial_of_the_crusader::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 272 of file trial_of_the_crusader.cpp.
References ALLIANCE, DoSelectCrusaders(), DoSummonRamsey(), GetData(), Player::GetTeam(), IsHeroicDifficulty(), m_uiTeam, MAX_WIPES_ALLOWED, Player::SendUpdateWorldState(), DialogueHelper::SetDialogueSide(), TYPE_WIPE_COUNT, WORLD_STATE_WIPES, and WORLD_STATE_WIPES_COUNT.
Save()
const char* instance_trial_of_the_crusader::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 311 of file trial_of_the_crusader.h.
References m_strInstData.
SetData()
void instance_trial_of_the_crusader::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 297 of file trial_of_the_crusader.cpp.
References ACHIEV_START_VALKYRS_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DoCleanupCrusaders(), DoHandleEventEpilogue(), DONE, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), EVENT_JARAXXUS_RESET_DELAY, EVENT_TWINS_KILLED, FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CRUSADERS_CACHE, GO_NORTH_GATE, GO_WEB_DOOR, GO_WEST_GATE, IN_PROGRESS, IsHeroicDifficulty(), m_auiEncounter, m_bCrusadersAchievCheck, m_bCrusadersSummoned, m_lSummonedGuidsList, m_strInstData, m_uiCrusadersAchievTimer, m_uiKilledCrusaders, MAX_WIPES_ALLOWED, MINUTE, NPC_RAMSEY_2, NPC_RAMSEY_3, NPC_RAMSEY_4, NPC_TIRION_A, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_JARAXXUS_DEATH, SAY_RAID_INTRO_SHORT, SAY_RAID_TRIALS_INTRO, SAY_TIRION_BEAST_SLAY, SAY_TIRION_BEAST_WIPE, SAY_TIRION_PVP_INTRO_1, SAY_TIRION_RAID_INTRO_LONG, SAY_TIRION_TWINS_INTRO, SAY_VARIAN_PVP_A_WIN, script_error_log(), SPECIAL, DialogueHelper::StartNextDialogueText(), TYPE_ANUBARAK, TYPE_FACTION_CHAMPIONS, TYPE_IMMORTALITY_FAILED, TYPE_JARAXXUS, TYPE_NORTHREND_BEASTS, TYPE_TWIN_VALKYR, TYPE_WIPE_COUNT, and WORLD_STATE_WIPES_COUNT.
Referenced by boss_anubarak_trialAI::Aggro(), npc_beast_combat_stalkerAI::Aggro(), boss_fjolaAI::Aggro(), trial_crusader_commonAI::Aggro(), boss_jaraxxusAI::Aggro(), npc_beast_combat_stalkerAI::EnterEvadeMode(), boss_fjolaAI::EnterEvadeMode(), boss_anubarak_trialAI::JustDied(), boss_jaraxxusAI::JustDied(), boss_fjolaAI::JustDied(), boss_anubarak_trialAI::JustReachedHome(), trial_crusader_commonAI::JustReachedHome(), boss_jaraxxusAI::JustReachedHome(), OnCreatureDeath(), OnPlayerDeath(), and npc_beast_combat_stalkerAI::SummonedCreatureJustDied().
ShowChatCommands()
void instance_trial_of_the_crusader::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 935 of file trial_of_the_crusader.cpp.
References ChatHandler::SendSysMessage().
Update()
void instance_trial_of_the_crusader::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 900 of file trial_of_the_crusader.cpp.
References DialogueHelper::DialogueUpdate(), ScriptedInstance::DoUseDoorOrButton(), GO_MAIN_GATE, m_uiCrusadersAchievTimer, and m_uiGateResetTimer.
Field Documentation
m_auiEncounter
uint32 instance_trial_of_the_crusader::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 334 of file trial_of_the_crusader.h.
Referenced by DoSummonRamsey(), GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), and SetData().
m_bCrusadersAchievCheck
bool instance_trial_of_the_crusader::m_bCrusadersAchievCheck private
Definition at line 350 of file trial_of_the_crusader.h.
Referenced by OnCreatureDeath(), and SetData().
m_bCrusadersSummoned
bool instance_trial_of_the_crusader::m_bCrusadersSummoned private
Definition at line 349 of file trial_of_the_crusader.h.
Referenced by JustDidDialogueStep(), and SetData().
m_lSummonedGuidsList
GuidList instance_trial_of_the_crusader::m_lSummonedGuidsList private
Definition at line 341 of file trial_of_the_crusader.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureCreate(), OnCreatureDeath(), and SetData().
m_strInstData
std::string instance_trial_of_the_crusader::m_strInstData private
Definition at line 335 of file trial_of_the_crusader.h.
Referenced by Save(), and SetData().
m_uiCrusadersAchievTimer
uint32 instance_trial_of_the_crusader::m_uiCrusadersAchievTimer private
Definition at line 347 of file trial_of_the_crusader.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_uiGateResetTimer
uint32 instance_trial_of_the_crusader::m_uiGateResetTimer private
Definition at line 345 of file trial_of_the_crusader.h.
Referenced by DoOpenMainGate(), and Update().
m_uiKilledCrusaders
uint32 instance_trial_of_the_crusader::m_uiKilledCrusaders private
Definition at line 346 of file trial_of_the_crusader.h.
Referenced by OnCreatureDeath(), and SetData().
m_uiTeam
Team instance_trial_of_the_crusader::m_uiTeam private
Definition at line 343 of file trial_of_the_crusader.h.
Referenced by DoSelectCrusaders(), GetPlayerTeam(), JustDidDialogueStep(), and OnPlayerEnter().
m_vCrusadersEntries
std::vector<uint32> instance_trial_of_the_crusader::m_vCrusadersEntries private
Definition at line 337 of file trial_of_the_crusader.h.
Referenced by DoSelectCrusaders(), and JustDidDialogueStep().
m_vCrusadersGuidsVector
GuidVector instance_trial_of_the_crusader::m_vCrusadersGuidsVector private
Definition at line 339 of file trial_of_the_crusader.h.
Referenced by DoCleanupCrusaders(), DoSetCrusadersInCombat(), and JustDidDialogueStep().
m_vStalkersGuidsVector
GuidVector instance_trial_of_the_crusader::m_vStalkersGuidsVector private
Definition at line 340 of file trial_of_the_crusader.h.
Referenced by GetStalkersGUIDVector(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
trial_of_the_crusader.h
trial_of_the_crusader.cpp