CMaNGOS_WoTLK: IntervalTimer Class Reference
IntervalTimer Class Reference
#include <Timer.h>
Public Member Functions
IntervalTimer ()
void Update (time_t diff)
bool Passed () const
void Reset ()
void SetCurrent (time_t current)
void SetInterval (time_t interval)
time_t GetInterval () const
time_t GetCurrent () const
Private Attributes
time_t _interval
time_t _current
Detailed Description
Definition at line 77 of file Timer.h.
Constructor & Destructor Documentation
IntervalTimer()
IntervalTimer::IntervalTimer () inline
Definition at line 80 of file Timer.h.
Member Function Documentation
GetCurrent()
time_t IntervalTimer::GetCurrent () const inline
Definition at line 98 of file Timer.h.
Referenced by MapManager::Update().
GetInterval()
time_t IntervalTimer::GetInterval () const inline
Definition at line 97 of file Timer.h.
Passed()
bool IntervalTimer::Passed () const inline
Definition at line 88 of file Timer.h.
Referenced by MapManager::Update().
Reset()
void IntervalTimer::Reset () inline
Definition at line 89 of file Timer.h.
Referenced by World::LoadConfigSettings(), MapManager::SetMapUpdateInterval(), and World::Update().
SetCurrent()
void IntervalTimer::SetCurrent (time_t current) inline
Definition at line 95 of file Timer.h.
Referenced by MapManager::Update().
SetInterval()
void IntervalTimer::SetInterval (time_t interval) inline
Definition at line 96 of file Timer.h.
Referenced by World::LoadConfigSettings(), MapManager::MapManager(), World::SetInitialWorldSettings(), MapManager::SetMapUpdateInterval(), and World::Update().
Update()
void IntervalTimer::Update (time_t diff) inline
Definition at line 82 of file Timer.h.
Referenced by MapManager::Update().
Field Documentation
_current
time_t IntervalTimer::_current private
Definition at line 102 of file Timer.h.
_interval
time_t IntervalTimer::_interval private
Definition at line 101 of file Timer.h.
The documentation for this class was generated from the following file:
Timer.h