CMaNGOS_WoTLK: BattleGroundAB Class Reference
BattleGroundAB Class Reference
#include <BattleGroundAB.h>
Public Member Functions
BattleGroundAB ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *player) override
Method that is called when adding a player to the battleground.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
Team GetPrematureWinner () override
Function that returns the premature winner.
bool HandleAreaTrigger (Player *source, uint32 trigger) override
void HandleGameObjectCreate (GameObject *go) override
void HandlePlayerClickedOnFlag (Player *source, GameObject *go) override
bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target, uint32 miscvalue1) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual void HandleKillPlayer (Player *, Player *)
Method that handles killing players.
virtual void HandleKillUnit (Creature *, Player *)
virtual bool HandleEvent (uint32, Object *, Object *)
virtual void HandleCreatureCreate (Creature *)
virtual void HandlePlayerDroppedFlag (Player *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Private Member Functions
void DoUpdateBanner (uint8 node, ABNodeStatus nodeStatus, bool delay)
void DoUpdateNodeWorldstate (uint8 node, uint32 newState)
bool AreAllNodesControlledByTeam (Team team)
bool IsTeamScores500Disadvantage (Team team)
void ProcessNodeCapture (uint8 node, PvpTeamIndex teamIdx)
int32 GetNodeMessageId (uint8 node) const
Private Attributes
ABNodeStatus m_nodeStatus [BG_AB_MAX_NODES]
ABNodeStatus m_prevNodeStatus [BG_AB_MAX_NODES]
ArathiBannerTimer m_bannerTimers [BG_AB_MAX_NODES]
ObjectGuid m_spiritHealers [BG_AB_MAX_NODES]
ObjectGuid m_honorableDefender [BG_AB_MAX_NODES]
uint32 m_nodeVisualState [BG_AB_MAX_NODES]
uint32 m_nodeTimers [BG_AB_MAX_NODES]
uint32 m_lastTick [PVP_TEAM_COUNT]
uint32 m_honorScoreTicks [PVP_TEAM_COUNT]
uint32 m_reputationScoreTics [PVP_TEAM_COUNT]
bool m_teamScores500Disadvantage [PVP_TEAM_COUNT]
bool m_isInformedNearVictory
uint32 m_honorTicks
uint32 m_reputationTics
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 251 of file BattleGroundAB.h.
Constructor & Destructor Documentation
BattleGroundAB()
BattleGroundAB::BattleGroundAB ()
Definition at line 29 of file BattleGroundAB.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_AB_HAS_BEGUN, LANG_BG_AB_START_HALF_MINUTE, LANG_BG_AB_START_ONE_MINUTE, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundAB::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 178 of file BattleGroundAB.cpp.
References BattleGround::AddPlayer(), Object::GetObjectGuid(), and BattleGround::m_playerScores.
AreAllNodesControlledByTeam()
bool BattleGroundAB::AreAllNodesControlledByTeam (Team team) private
Definition at line 531 of file BattleGroundAB.cpp.
References ALLIANCE, BG_AB_NODE_STATUS_ALLY_OCCUPIED, BG_AB_NODE_STATUS_HORDE_OCCUPIED, HORDE, and m_nodeStatus.
Referenced by CheckAchievementCriteriaMeet().
CheckAchievementCriteriaMeet()
bool BattleGroundAB::CheckAchievementCriteriaMeet (uint32 criteria_id, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 555 of file BattleGroundAB.cpp.
References AB_ACHIEV_HAD_IT_ALL_ALONG, AB_ACHIEV_RESILIET_VICTORY_1, AB_ACHIEV_RESILIET_VICTORY_10, AB_ACHIEV_RESILIET_VICTORY_2, AB_ACHIEV_RESILIET_VICTORY_3, AB_ACHIEV_RESILIET_VICTORY_4, AB_ACHIEV_RESILIET_VICTORY_5, AB_ACHIEV_RESILIET_VICTORY_6, AB_ACHIEV_RESILIET_VICTORY_7, AB_ACHIEV_RESILIET_VICTORY_8, AB_ACHIEV_RESILIET_VICTORY_9, AB_ACHIEV_TERRITORIAL_DOMINANCE, AreAllNodesControlledByTeam(), BG_AB_OP_RESOURCES_ALLY, BG_AB_OP_RESOURCES_HORDE, BattleGround::GetBgMap(), Player::GetTeam(), and IsTeamScores500Disadvantage().
DoUpdateBanner()
void BattleGroundAB::DoUpdateBanner (uint8 node, ABNodeStatus nodeStatus, bool delay) private
Definition at line 224 of file BattleGroundAB.cpp.
References m_bannerTimers, BattleGround::SpawnEvent(), ArathiBannerTimer::status, and ArathiBannerTimer::timer.
Referenced by HandlePlayerClickedOnFlag(), and Update().
DoUpdateNodeWorldstate()
void BattleGroundAB::DoUpdateNodeWorldstate (uint8 node, uint32 newState) private
Definition at line 252 of file BattleGroundAB.cpp.
References BattleGround::GetBgMap(), Map::GetVariableManager(), m_nodeVisualState, WorldStateVariableManager::SetVariable(), WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
Referenced by HandlePlayerClickedOnFlag(), and Update().
EndBattleGround()
void BattleGroundAB::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 498 of file BattleGroundAB.cpp.
References ALLIANCE, BattleGround::EndBattleGround(), BattleGround::GetBonusHonorFromKill(), HORDE, and BattleGround::RewardHonorToTeam().
Referenced by Update().
GetNodeMessageId()
int32 BattleGroundAB::GetNodeMessageId (uint8 node) const private
Definition at line 238 of file BattleGroundAB.cpp.
References BG_AB_NODE_BLACKSMITH, BG_AB_NODE_FARM, BG_AB_NODE_GOLD_MINE, BG_AB_NODE_LUMBER_MILL, BG_AB_NODE_STABLES, LANG_BG_AB_NODE_BLACKSMITH, LANG_BG_AB_NODE_FARM, LANG_BG_AB_NODE_GOLD_MINE, LANG_BG_AB_NODE_LUMBER_MILL, and LANG_BG_AB_NODE_STABLES.
Referenced by HandlePlayerClickedOnFlag(), and Update().
GetPrematureWinner()
Team BattleGroundAB::GetPrematureWinner () override virtual
Function that returns the premature winner.
Reimplemented from BattleGround.
Definition at line 541 of file BattleGroundAB.cpp.
References ALLIANCE, BG_AB_OP_RESOURCES_ALLY, BG_AB_OP_RESOURCES_HORDE, BattleGround::GetBgMap(), BattleGround::GetPrematureWinner(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), and HORDE.
HandleAreaTrigger()
bool BattleGroundAB::HandleAreaTrigger (Player * source, uint32 trigger) override virtual
Reimplemented from BattleGround.
Definition at line 187 of file BattleGroundAB.cpp.
References AB_AT_ALLIANCE_EXIT, AB_AT_HORDE_EXIT, ALLIANCE, Player::GetSession(), Player::GetTeam(), HORDE, LANG_BATTLEGROUND_ONLY_ALLIANCE_USE, LANG_BATTLEGROUND_ONLY_HORDE_USE, Player::LeaveBattleground(), and WorldSession::SendNotification().
HandleGameObjectCreate()
void BattleGroundAB::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 209 of file BattleGroundAB.cpp.
References BG_AB_BANNER_BLACKSMITH, BG_AB_BANNER_FARM, BG_AB_BANNER_LUMBER_MILL, BG_AB_BANNER_MINE, BG_AB_BANNER_STABLE, Object::GetEntry(), Object::GetObjectGuid(), and BattleGround::m_goEntryGuidStore.
HandlePlayerClickedOnFlag()
void BattleGroundAB::HandlePlayerClickedOnFlag (Player * source, GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 297 of file BattleGroundAB.cpp.
References abContestedStates, abGraveyardData, abOccupiedStates, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, BG_AB_FLAG_CAPTURING_TIME, BG_AB_MAX_NODES, BG_AB_NODE_STATUS_ALLY_CONTESTED, BG_AB_NODE_STATUS_HORDE_CONTESTED, BG_AB_NODE_TYPE_CONTESTED, BG_AB_NODE_TYPE_NEUTRAL, BG_AB_NODE_TYPE_OCCUPIED, BG_AB_OP_OCCUPIED_BASES_ALLY, BG_AB_OP_OCCUPIED_BASES_HORDE, BG_AB_SOUND_NODE_ASSAULTED_ALLIANCE, BG_AB_SOUND_NODE_ASSAULTED_HORDE, BG_AB_SOUND_NODE_CLAIMED, BG_AB_ZONE_MAIN, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, DEBUG_LOG, DoUpdateBanner(), DoUpdateNodeWorldstate(), BattleGround::GetBgMap(), Object::GetDbGuid(), Object::GetEntry(), Map::GetGraveyardManager(), GetNodeMessageId(), BattleGround::GetOtherTeamIndex(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), LANG_BG_AB_NODE_ASSAULTED, LANG_BG_AB_NODE_CLAIMED, LANG_BG_AB_NODE_DEFENDED, LANG_BG_ALLY, LANG_BG_HORDE, m_honorableDefender, m_nodeStatus, m_nodeTimers, m_prevNodeStatus, m_spiritHealers, BattleGround::PlaySoundToAll(), ProcessNodeCapture(), Unit::RemoveAurasWithInterruptFlags(), sBattleGroundMgr, SCORE_BASES_ASSAULTED, SCORE_BASES_DEFENDED, BattleGround::SendMessage2ToAll(), GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, TEAM_INVALID, Player::UpdateAchievementCriteria(), and UpdatePlayerScore().
IsTeamScores500Disadvantage()
bool BattleGroundAB::IsTeamScores500Disadvantage (Team team) inline private
Definition at line 284 of file BattleGroundAB.h.
References GetTeamIndexByTeamId(), and m_teamScores500Disadvantage.
Referenced by CheckAchievementCriteriaMeet().
ProcessNodeCapture()
void BattleGroundAB::ProcessNodeCapture (uint8 node, PvpTeamIndex teamIdx) private
Definition at line 261 of file BattleGroundAB.cpp.
References abGraveyardData, abNodeData, BG_AB_OP_OCCUPIED_BASES_ALLY, BG_AB_OP_OCCUPIED_BASES_HORDE, BG_AB_SPELL_QUEST_REWARD_4_BASES, BG_AB_SPELL_QUEST_REWARD_5_BASES, BG_AB_ZONE_MAIN, BG_NPC_HON_DEFENDER_TRIGGER_25_A, BG_NPC_HON_DEFENDER_TRIGGER_25_H, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, BattleGround::CastSpellOnTeam(), DEBUG_LOG, BattleGround::GetBgMap(), Map::GetGraveyardManager(), BattleGround::GetSingleGameObjectFromStorage(), GetTeamIdByTeamIndex(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), m_honorableDefender, m_spiritHealers, BasinSummonData::o, GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), sLog, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEMPSPAWN_DEAD_DESPAWN, BasinSummonData::x, BasinSummonData::y, and BasinSummonData::z.
Referenced by HandlePlayerClickedOnFlag(), and Update().
Reset()
void BattleGroundAB::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 432 of file BattleGroundAB.cpp.
References AB_GRAVEYARD_ALLIANCE, AB_GRAVEYARD_HORDE, abContestedStates, abDefaultStates, abGraveyardData, abOccupiedStates, ALLIANCE, BG_AB_MAX_NODES, BG_AB_MAX_TEAM_SCORE, BG_AB_NODE_STATUS_NEUTRAL, BG_AB_NODE_TYPE_NEUTRAL, BG_AB_NORMAL_HONOR_INTERVAL, BG_AB_NORMAL_REPUTATION_INTERVAL, BG_AB_OP_OCCUPIED_BASES_ALLY, BG_AB_OP_OCCUPIED_BASES_HORDE, BG_AB_OP_RESOURCES_ALLY, BG_AB_OP_RESOURCES_HORDE, BG_AB_OP_RESOURCES_MAX, BG_AB_OP_RESOURCES_WARNING, BG_AB_WARNING_NEAR_VICTORY_SCORE, BG_AB_WEEKEND_HONOR_INTERVAL, BG_AB_WEEKEND_REPUTATION_INTERVAL, BG_AB_ZONE_MAIN, BattleGround::GetBgMap(), Map::GetGraveyardManager(), BattleGround::GetTypeId(), Map::GetVariableManager(), HORDE, BattleGroundMgr::IsBgWeekend(), BattleGround::m_activeEvents, m_bannerTimers, m_honorScoreTicks, m_honorTicks, m_isInformedNearVictory, m_lastTick, m_nodeStatus, m_nodeTimers, m_nodeVisualState, m_prevNodeStatus, m_reputationScoreTics, m_reputationTics, m_teamScores500Disadvantage, PVP_TEAM_COUNT, BattleGround::Reset(), GraveyardManager::SetGraveYardLinkTeam(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), TEAM_INVALID, ArathiBannerTimer::timer, and WORLD_STATE_ADD.
StartingEventOpenDoors()
void BattleGroundAB::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 162 of file BattleGroundAB.cpp.
References AB_GRAVEYARD_ALLIANCE, AB_GRAVEYARD_ALLIANCE_BASE, AB_GRAVEYARD_HORDE, AB_GRAVEYARD_HORDE_BASE, AB_TIMED_ACHIEV_GET_THIS_DONE, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ALLIANCE, BG_AB_ZONE_MAIN, BG_EVENT_DOOR, BattleGround::GetBgMap(), Map::GetGraveyardManager(), HORDE, BattleGround::OpenDoorEvent(), GraveyardManager::SetGraveYardLinkTeam(), BattleGround::StartTimedAchievement(), and TEAM_INVALID.
Update()
void BattleGroundAB::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 37 of file BattleGroundAB.cpp.
References abOccupiedStates, abTickIntervals, abTickPoints, ALLIANCE, BG_AB_MAX_NODES, BG_AB_MAX_TEAM_SCORE, BG_AB_NODE_TYPE_OCCUPIED, BG_AB_OP_RESOURCES_ALLY, BG_AB_OP_RESOURCES_HORDE, BG_AB_SOUND_NEAR_VICTORY_ALLIANCE, BG_AB_SOUND_NEAR_VICTORY_HORDE, BG_AB_SOUND_NODE_CAPTURED_ALLIANCE, BG_AB_SOUND_NODE_CAPTURED_HORDE, BG_AB_WARNING_NEAR_VICTORY_SCORE, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, CHAT_MSG_BG_SYSTEM_NEUTRAL, DoUpdateBanner(), DoUpdateNodeWorldstate(), EndBattleGround(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), GetNodeMessageId(), BattleGround::GetOtherTeamIndex(), BattleGround::GetStatus(), GetTeamIdByTeamIndex(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), HORDE, LANG_BG_AB_A_NEAR_VICTORY, LANG_BG_AB_H_NEAR_VICTORY, LANG_BG_AB_NODE_TAKEN, LANG_BG_ALLY, LANG_BG_HORDE, m_bannerTimers, m_honorScoreTicks, m_honorTicks, m_isInformedNearVictory, m_lastTick, m_nodeStatus, m_nodeTimers, m_prevNodeStatus, m_reputationScoreTics, m_reputationTics, m_teamScores500Disadvantage, BattleGround::PlaySoundToAll(), ProcessNodeCapture(), PVP_TEAM_COUNT, BattleGround::RewardHonorToTeam(), BattleGround::RewardReputationToTeam(), BattleGround::SendMessage2ToAll(), BattleGround::SendMessageToAll(), WorldStateVariableManager::SetVariable(), STATUS_IN_PROGRESS, TEAM_INDEX_ALLIANCE, ArathiBannerTimer::timer, and BattleGround::Update().
UpdatePlayerScore()
void BattleGroundAB::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 510 of file BattleGroundAB.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_BASES_ASSAULTED, SCORE_BASES_DEFENDED, and BattleGround::UpdatePlayerScore().
Referenced by HandlePlayerClickedOnFlag().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 253 of file BattleGroundAB.h.
Field Documentation
m_bannerTimers
ArathiBannerTimer BattleGroundAB::m_bannerTimers[BG_AB_MAX_NODES] private
Definition at line 294 of file BattleGroundAB.h.
Referenced by DoUpdateBanner(), Reset(), and Update().
m_honorableDefender
ObjectGuid BattleGroundAB::m_honorableDefender[BG_AB_MAX_NODES] private
Definition at line 297 of file BattleGroundAB.h.
Referenced by HandlePlayerClickedOnFlag(), and ProcessNodeCapture().
m_honorScoreTicks
uint32 BattleGroundAB::m_honorScoreTicks[PVP_TEAM_COUNT] private
Definition at line 302 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_honorTicks
uint32 BattleGroundAB::m_honorTicks private
Definition at line 307 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_isInformedNearVictory
bool BattleGroundAB::m_isInformedNearVictory private
Definition at line 306 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_lastTick
uint32 BattleGroundAB::m_lastTick[PVP_TEAM_COUNT] private
Definition at line 301 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_nodeStatus
ABNodeStatus BattleGroundAB::m_nodeStatus[BG_AB_MAX_NODES] private
Definition at line 292 of file BattleGroundAB.h.
Referenced by AreAllNodesControlledByTeam(), HandlePlayerClickedOnFlag(), Reset(), and Update().
m_nodeTimers
uint32 BattleGroundAB::m_nodeTimers[BG_AB_MAX_NODES] private
Definition at line 300 of file BattleGroundAB.h.
Referenced by HandlePlayerClickedOnFlag(), Reset(), and Update().
m_nodeVisualState
uint32 BattleGroundAB::m_nodeVisualState[BG_AB_MAX_NODES] private
Definition at line 299 of file BattleGroundAB.h.
Referenced by DoUpdateNodeWorldstate(), and Reset().
m_prevNodeStatus
ABNodeStatus BattleGroundAB::m_prevNodeStatus[BG_AB_MAX_NODES] private
Definition at line 293 of file BattleGroundAB.h.
Referenced by HandlePlayerClickedOnFlag(), Reset(), and Update().
m_reputationScoreTics
uint32 BattleGroundAB::m_reputationScoreTics[PVP_TEAM_COUNT] private
Definition at line 303 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_reputationTics
uint32 BattleGroundAB::m_reputationTics private
Definition at line 308 of file BattleGroundAB.h.
Referenced by Reset(), and Update().
m_spiritHealers
ObjectGuid BattleGroundAB::m_spiritHealers[BG_AB_MAX_NODES] private
Definition at line 296 of file BattleGroundAB.h.
Referenced by HandlePlayerClickedOnFlag(), and ProcessNodeCapture().
m_teamScores500Disadvantage
bool BattleGroundAB::m_teamScores500Disadvantage[PVP_TEAM_COUNT] private
Definition at line 304 of file BattleGroundAB.h.
Referenced by IsTeamScores500Disadvantage(), Reset(), and Update().
The documentation for this class was generated from the following files:
BattleGroundAB.h
BattleGroundAB.cpp