CMaNGOS_WoTLK: ArenaTeam Class Reference
ArenaTeam Class Reference
#include <ArenaTeam.h>
Public Types
typedef std::list< ArenaTeamMember > MemberList
Public Member Functions
ArenaTeam ()
~ArenaTeam ()
bool Create (ObjectGuid captainGuid, ArenaType type, std::string arenaTeamName)
void Disband (WorldSession *session)
uint32 GetId () const
ArenaType GetType () const
uint8 GetSlot () const
ObjectGuid GetCaptainGuid () const
std::string GetName () const
const ArenaTeamStats & GetStats () const
void SetStats (uint32 stat_type, uint32 value)
uint32 GetRating () const
uint32 GetEmblemStyle () const
uint32 GetEmblemColor () const
uint32 GetBorderStyle () const
uint32 GetBorderColor () const
uint32 GetBackgroundColor () const
void SetCaptain (ObjectGuid guid)
bool AddMember (ObjectGuid playerGuid)
void DelMember (ObjectGuid guid)
void SetEmblem (uint32 backgroundColor, uint32 emblemStyle, uint32 emblemColor, uint32 borderStyle, uint32 borderColor)
size_t GetMembersSize () const
size_t GetMaxMembersSize () const
bool Empty () const
MemberList & GetMembers ()
bool HaveMember (ObjectGuid guid) const
ArenaTeamMember * GetMember (ObjectGuid guid)
ArenaTeamMember * GetMember (const std::string &name)
bool IsFighting () const
bool LoadArenaTeamFromDB (QueryResult *arenaTeamDataResult)
bool LoadMembersFromDB (QueryResult *arenaTeamMembersResult)
void SaveToDB ()
void BroadcastPacket (WorldPacket const &packet)
void BroadcastEvent (ArenaTeamEvents event, ObjectGuid guid, char const *str1=nullptr, char const *str2=nullptr, char const *str3=nullptr)
void BroadcastEvent (ArenaTeamEvents event, char const *str1=nullptr, char const *str2=nullptr, char const *str3=nullptr)
void Roster (WorldSession *session)
void Query (WorldSession *session) const
void Stats (WorldSession *session) const
void InspectStats (WorldSession *session, ObjectGuid guid)
uint32 GetPoints (uint32 MemberRating)
float GetChanceAgainst (uint32 own_rating, uint32 enemy_rating) const
int32 WonAgainst (uint32 againstRating)
void MemberWon (Player *plr, uint32 againstRating)
int32 LostAgainst (uint32 againstRating)
void MemberLost (Player *plr, uint32 againstRating)
void OfflineMemberLost (ObjectGuid guid, uint32 againstRating)
void UpdateArenaPointsHelper (std::map< uint32, uint32 > &PlayerPoints)
void NotifyStatsChanged ()
void FinishWeek ()
void FinishGame (int32 mod)
void FinishSeason ()
void SetRatingForAll (uint32 rating)
void MassInviteToEvent (WorldSession *session)
Static Public Member Functions
static uint8 GetSlotByType (ArenaType type)
Protected Attributes
uint32 m_TeamId
ArenaType m_Type
std::string m_Name
ObjectGuid m_CaptainGuid
uint32 m_BackgroundColor
uint32 m_EmblemStyle
uint32 m_EmblemColor
uint32 m_BorderStyle
uint32 m_BorderColor
MemberList m_members
ArenaTeamStats m_stats
Detailed Description
Definition at line 116 of file ArenaTeam.h.
Member Typedef Documentation
MemberList
typedef std::list<ArenaTeamMember> ArenaTeam::MemberList
Definition at line 125 of file ArenaTeam.h.
Constructor & Destructor Documentation
ArenaTeam()
ArenaTeam::ArenaTeam ()
Definition at line 36 of file ArenaTeam.cpp.
References ARENA_TYPE_NONE, CONFIG_INT32_ARENA_STARTRATING, CONFIG_UINT32_ARENA_SEASON_ID, ArenaTeamStats::games_season, ArenaTeamStats::games_week, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_EmblemColor, m_EmblemStyle, m_stats, m_TeamId, m_Type, ArenaTeamStats::rank, ArenaTeamStats::rating, sWorld, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
~ArenaTeam()
ArenaTeam::~ArenaTeam ()
Definition at line 64 of file ArenaTeam.cpp.
Member Function Documentation
AddMember()
bool ArenaTeam::AddMember (ObjectGuid playerGuid)
Definition at line 103 of file ArenaTeam.cpp.
References ARENA_TEAM_MEMBER, ARENA_TEAM_PERSONAL_RATING, CharacterDatabase, ArenaTeamMember::Class, CONFIG_INT32_ARENA_STARTPERSONALRATING, CONFIG_UINT32_ARENA_SEASON_ID, ArenaTeamMember::games_season, ArenaTeamMember::games_week, Player::GetArenaTeamId(), Player::GetArenaTeamIdFromDB(), Unit::getClass(), ObjectGuid::GetCounter(), GetMaxMembersSize(), GetMembersSize(), WorldObject::GetName(), GetSlot(), ObjectGuid::GetString(), GetType(), ArenaTeamMember::guid, m_CaptainGuid, m_members, m_stats, m_TeamId, ArenaTeamMember::name, ArenaTeamMember::personal_rating, Database::PExecute(), Database::PQuery(), ArenaTeamStats::rating, Player::RemovePetitionsAndSigns(), Player::SetArenaTeamIdInvited(), Player::SetArenaTeamInfoField(), Player::SetInArenaTeam(), sLog, sObjectMgr, sWorld, ArenaTeamMember::wins_season, and ArenaTeamMember::wins_week.
Referenced by Create(), WorldSession::HandleArenaTeamAcceptOpcode(), and WorldSession::HandleTurnInPetitionOpcode().
BroadcastEvent() [1/2]
void ArenaTeam::BroadcastEvent (ArenaTeamEvents event, char const * str1 = nullptr, char const * str2 = nullptr, char const * str3 = nullptr) inline
Definition at line 183 of file ArenaTeam.h.
References BroadcastEvent().
BroadcastEvent() [2/2]
void ArenaTeam::BroadcastEvent (ArenaTeamEvents event, ObjectGuid guid, char const * str1 = nullptr, char const * str2 = nullptr, char const * str3 = nullptr)
Definition at line 499 of file ArenaTeam.cpp.
References BroadcastPacket(), DEBUG_LOG, and SMSG_ARENA_TEAM_EVENT.
Referenced by BroadcastEvent(), Disband(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), and WorldSession::HandleArenaTeamRemoveOpcode().
BroadcastPacket()
void ArenaTeam::BroadcastPacket (WorldPacket const & packet)
Definition at line 489 of file ArenaTeam.cpp.
References Player::GetSession(), m_members, WorldSession::SendPacket(), and sObjectMgr.
Referenced by BroadcastEvent().
Create()
bool ArenaTeam::Create (ObjectGuid captainGuid, ArenaType type, std::string arenaTeamName)
Definition at line 68 of file ArenaTeam.cpp.
References AddMember(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), DEBUG_LOG, Database::escape_string(), ArenaTeamStats::games_season, ArenaTeamStats::games_week, ObjectGuid::GetCounter(), ObjectGuid::GetString(), IsArenaTypeValid(), m_BackgroundColor, m_BorderColor, m_BorderStyle, m_CaptainGuid, m_EmblemColor, m_EmblemStyle, m_Name, m_stats, m_TeamId, m_Type, Database::PExecute(), ArenaTeamStats::rank, ArenaTeamStats::rating, sObjectMgr, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Referenced by WorldSession::HandleTurnInPetitionOpcode().
DelMember()
void ArenaTeam::DelMember (ObjectGuid guid)
Definition at line 305 of file ArenaTeam.cpp.
References ARENA_TEAM_END, CharacterDatabase, ERR_ARENA_TEAM_QUIT_S, ObjectGuid::GetCounter(), GetId(), GetName(), GetSlot(), m_members, Database::PExecute(), and sObjectMgr.
Referenced by Disband(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), and LoadMembersFromDB().
Disband()
void ArenaTeam::Disband (WorldSession * session)
Definition at line 327 of file ArenaTeam.cpp.
References Database::BeginTransaction(), BroadcastEvent(), CharacterDatabase, Database::CommitTransaction(), DelMember(), ERR_ARENA_TEAM_DISBANDED_S, GetName(), WorldSession::GetPlayerName(), m_members, m_TeamId, Database::PExecute(), and sObjectMgr.
Referenced by WorldSession::HandleArenaTeamLeaveOpcode(), and ObjectMgr::LoadArenaTeams().
Empty()
bool ArenaTeam::Empty () const inline
Definition at line 151 of file ArenaTeam.h.
References m_members.
Referenced by LoadMembersFromDB().
FinishGame()
void ArenaTeam::FinishGame (int32 mod)
Definition at line 590 of file ArenaTeam.cpp.
References ArenaTeamStats::games_season, ArenaTeamStats::games_week, m_stats, ArenaTeamStats::rank, ArenaTeamStats::rating, and sObjectMgr.
Referenced by LostAgainst(), and WonAgainst().
FinishSeason()
void ArenaTeam::FinishSeason ()
Definition at line 781 of file ArenaTeam.cpp.
References ArenaTeamStats::games_season, ArenaTeamStats::games_week, m_members, m_stats, ArenaTeamStats::rank, ArenaTeamStats::rating, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
FinishWeek()
void ArenaTeam::FinishWeek ()
Definition at line 757 of file ArenaTeam.cpp.
References ArenaTeamStats::games_week, m_members, m_stats, and ArenaTeamStats::wins_week.
GetBackgroundColor()
uint32 ArenaTeam::GetBackgroundColor () const inline
Definition at line 141 of file ArenaTeam.h.
References m_BackgroundColor.
GetBorderColor()
uint32 ArenaTeam::GetBorderColor () const inline
Definition at line 140 of file ArenaTeam.h.
References m_BorderColor.
GetBorderStyle()
uint32 ArenaTeam::GetBorderStyle () const inline
Definition at line 139 of file ArenaTeam.h.
References m_BorderStyle.
GetCaptainGuid()
ObjectGuid ArenaTeam::GetCaptainGuid () const inline
Definition at line 131 of file ArenaTeam.h.
References m_CaptainGuid.
Referenced by Player::_LoadArenaTeamInfo(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), LoadMembersFromDB(), Roster(), and SetCaptain().
GetChanceAgainst()
float ArenaTeam::GetChanceAgainst (uint32 own_rating, uint32 enemy_rating) const
Definition at line 579 of file ArenaTeam.cpp.
References CONFIG_UINT32_ARENA_SEASON_ID, and sWorld.
Referenced by LostAgainst(), MemberLost(), MemberWon(), OfflineMemberLost(), and WonAgainst().
GetEmblemColor()
uint32 ArenaTeam::GetEmblemColor () const inline
Definition at line 138 of file ArenaTeam.h.
References m_EmblemColor.
GetEmblemStyle()
uint32 ArenaTeam::GetEmblemStyle () const inline
Definition at line 137 of file ArenaTeam.h.
References m_EmblemStyle.
GetId()
uint32 ArenaTeam::GetId () const inline
Definition at line 127 of file ArenaTeam.h.
References m_TeamId.
Referenced by ObjectMgr::AddArenaTeam(), DelMember(), WorldSession::HandleArenaTeamInviteOpcode(), InspectStats(), Query(), Roster(), SaveToDB(), SetStats(), and Stats().
GetMaxMembersSize()
size_t ArenaTeam::GetMaxMembersSize () const inline
Definition at line 150 of file ArenaTeam.h.
References GetType().
Referenced by AddMember(), WorldSession::HandleArenaTeamInviteOpcode(), and LoadMembersFromDB().
GetMember() [1/2]
ArenaTeamMember* ArenaTeam::GetMember (const std::string & name) inline
Definition at line 164 of file ArenaTeam.h.
References m_members.
GetMember() [2/2]
ArenaTeamMember* ArenaTeam::GetMember (ObjectGuid guid) inline
Definition at line 155 of file ArenaTeam.h.
References m_members.
Referenced by BattleGround::EndBattleGround(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), WorldSession::HandleBattlemasterJoinArena(), and InspectStats().
GetMembers()
MemberList& ArenaTeam::GetMembers () inline
Definition at line 152 of file ArenaTeam.h.
References m_members.
Referenced by CheckPlayersAndAddToWinners().
GetMembersSize()
size_t ArenaTeam::GetMembersSize () const inline
Definition at line 149 of file ArenaTeam.h.
References m_members.
Referenced by AddMember(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), LoadMembersFromDB(), and Roster().
GetName()
std::string ArenaTeam::GetName () const inline
Definition at line 132 of file ArenaTeam.h.
References m_Name.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), DelMember(), Disband(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamLeaveOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), and Query().
GetPoints()
uint32 ArenaTeam::GetPoints (uint32 MemberRating)
Definition at line 552 of file ArenaTeam.cpp.
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, CONFIG_UINT32_ARENA_SEASON_ID, m_stats, m_Type, ArenaTeamStats::rating, and sWorld.
Referenced by UpdateArenaPointsHelper().
GetRating()
uint32 ArenaTeam::GetRating () const inline
Definition at line 135 of file ArenaTeam.h.
References m_stats, and ArenaTeamStats::rating.
Referenced by WorldSession::HandleBattlemasterJoinArena(), and BattleGround::RemovePlayerAtLeave().
GetSlot()
uint8 ArenaTeam::GetSlot () const inline
Definition at line 129 of file ArenaTeam.h.
References GetSlotByType(), and GetType().
Referenced by Player::_LoadArenaTeamInfo(), AddMember(), DelMember(), WorldSession::HandleArenaTeamAcceptOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), InspectStats(), MemberLost(), MemberWon(), and SetCaptain().
GetSlotByType()
uint8 ArenaTeam::GetSlotByType (ArenaType type) static
Definition at line 529 of file ArenaTeam.cpp.
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, ARENA_TYPE_5v5, and sLog.
Referenced by GetSlot(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandleTurnInPetitionOpcode(), and AchievementMgr::UpdateAchievementCriteria().
GetStats()
const ArenaTeamStats& ArenaTeam::GetStats () const inline
Definition at line 133 of file ArenaTeam.h.
References m_stats.
Referenced by CheckPlayersAndAddToWinners(), BattleGround::EndBattleGround(), and BattleGroundMgr::RewardArenaSeason().
GetType()
ArenaType ArenaTeam::GetType () const inline
Definition at line 128 of file ArenaTeam.h.
References m_Type.
Referenced by Player::_LoadArenaTeamInfo(), AddMember(), GetMaxMembersSize(), GetSlot(), Query(), and Roster().
HaveMember()
bool ArenaTeam::HaveMember (ObjectGuid guid) const
Definition at line 543 of file ArenaTeam.cpp.
References m_members.
InspectStats()
void ArenaTeam::InspectStats (WorldSession * session, ObjectGuid guid)
Definition at line 426 of file ArenaTeam.cpp.
References ArenaTeamMember::games_season, ArenaTeamStats::games_season, GetId(), GetMember(), GetSlot(), m_stats, MSG_INSPECT_ARENA_TEAMS, ArenaTeamMember::personal_rating, ArenaTeamStats::rating, WorldSession::SendPacket(), and ArenaTeamStats::wins_season.
IsFighting()
bool ArenaTeam::IsFighting () const
Definition at line 768 of file ArenaTeam.cpp.
References m_members, and sObjectMgr.
LoadArenaTeamFromDB()
bool ArenaTeam::LoadArenaTeamFromDB (QueryResult * arenaTeamDataResult)
Definition at line 191 of file ArenaTeam.cpp.
References QueryResult::Fetch(), ArenaTeamStats::games_season, ArenaTeamStats::games_week, Field::GetCppString(), Field::GetUInt32(), HIGHGUID_PLAYER, IsArenaTypeValid(), m_BackgroundColor, m_BorderColor, m_BorderStyle, m_CaptainGuid, m_EmblemColor, m_EmblemStyle, m_Name, m_stats, m_TeamId, m_Type, ArenaTeamStats::rank, ArenaTeamStats::rating, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Referenced by ObjectMgr::LoadArenaTeams().
LoadMembersFromDB()
bool ArenaTeam::LoadMembersFromDB (QueryResult * arenaTeamMembersResult)
Definition at line 222 of file ArenaTeam.cpp.
References CharacterDatabase, ArenaTeamMember::Class, DelMember(), Empty(), QueryResult::Fetch(), ArenaTeamMember::games_season, ArenaTeamMember::games_week, GetCaptainGuid(), Field::GetCppString(), GetMaxMembersSize(), GetMembersSize(), ObjectGuid::GetString(), Field::GetUInt32(), Field::GetUInt8(), ArenaTeamMember::guid, HIGHGUID_PLAYER, m_members, m_TeamId, ArenaTeamMember::name, QueryResult::NextRow(), ArenaTeamMember::personal_rating, Database::PExecute(), sLog, ArenaTeamMember::wins_season, and ArenaTeamMember::wins_week.
Referenced by ObjectMgr::LoadArenaTeams().
LostAgainst()
int32 ArenaTeam::LostAgainst (uint32 againstRating)
Definition at line 626 of file ArenaTeam.cpp.
References FinishGame(), GetChanceAgainst(), m_stats, and ArenaTeamStats::rating.
Referenced by BattleGround::EndBattleGround().
MassInviteToEvent()
void ArenaTeam::MassInviteToEvent (WorldSession * session)
Definition at line 807 of file ArenaTeam.cpp.
References Player::GetLevelFromDB(), Object::GetObjectGuid(), WorldSession::GetPlayer(), m_members, WorldSession::SendPacket(), and SMSG_CALENDAR_ARENA_TEAM.
MemberLost()
void ArenaTeam::MemberLost (Player * plr, uint32 againstRating)
Definition at line 641 of file ArenaTeam.cpp.
References ARENA_TEAM_GAMES_SEASON, ARENA_TEAM_GAMES_WEEK, GetChanceAgainst(), Object::GetObjectGuid(), GetSlot(), m_members, and Player::SetArenaTeamInfoField().
Referenced by BattleGround::EndBattleGround(), WorldSession::HandleBattlefieldPortOpcode(), BattleGroundQueue::RemovePlayer(), and BattleGround::RemovePlayerAtLeave().
MemberWon()
void ArenaTeam::MemberWon (Player * plr, uint32 againstRating)
Definition at line 689 of file ArenaTeam.cpp.
References ARENA_TEAM_GAMES_SEASON, ARENA_TEAM_GAMES_WEEK, GetChanceAgainst(), Object::GetObjectGuid(), GetSlot(), m_members, and Player::SetArenaTeamInfoField().
Referenced by BattleGround::EndBattleGround().
NotifyStatsChanged()
void ArenaTeam::NotifyStatsChanged ()
Definition at line 414 of file ArenaTeam.cpp.
References Player::GetSession(), m_members, sObjectMgr, and Stats().
Referenced by BattleGround::EndBattleGround().
OfflineMemberLost()
void ArenaTeam::OfflineMemberLost (ObjectGuid guid, uint32 againstRating)
Definition at line 665 of file ArenaTeam.cpp.
References GetChanceAgainst(), and m_members.
Referenced by BattleGround::EndBattleGround(), BattleGroundQueue::RemovePlayer(), and BattleGround::RemovePlayerAtLeave().
Query()
void ArenaTeam::Query (WorldSession * session) const
Definition at line 386 of file ArenaTeam.cpp.
References DEBUG_LOG, GetId(), GetName(), GetType(), m_BackgroundColor, m_BorderColor, m_BorderStyle, m_EmblemColor, m_EmblemStyle, WorldSession::SendPacket(), and SMSG_ARENA_TEAM_QUERY_RESPONSE.
Roster()
void ArenaTeam::Roster (WorldSession * session)
Definition at line 350 of file ArenaTeam.cpp.
References DEBUG_LOG, GetCaptainGuid(), GetId(), Unit::GetLevel(), GetMembersSize(), GetType(), m_members, WorldSession::SendPacket(), SMSG_ARENA_TEAM_ROSTER, and sObjectMgr.
SaveToDB()
void ArenaTeam::SaveToDB ()
Definition at line 744 of file ArenaTeam.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), ArenaTeamStats::games_season, ArenaTeamStats::games_week, GetId(), m_members, m_stats, m_TeamId, Database::PExecute(), ArenaTeamStats::rank, ArenaTeamStats::rating, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Referenced by BattleGround::EndBattleGround(), ChatHandler::HandleArenaTeamPointSet(), WorldSession::HandleBattlefieldPortOpcode(), and BattleGroundQueue::RemovePlayer().
SetCaptain()
void ArenaTeam::SetCaptain (ObjectGuid guid)
Definition at line 287 of file ArenaTeam.cpp.
References ARENA_TEAM_MEMBER, CharacterDatabase, GetCaptainGuid(), ObjectGuid::GetCounter(), GetSlot(), m_CaptainGuid, m_TeamId, Database::PExecute(), Player::SetArenaTeamInfoField(), and sObjectMgr.
Referenced by WorldSession::HandleArenaTeamLeaderOpcode().
SetEmblem()
void ArenaTeam::SetEmblem (uint32 backgroundColor, uint32 emblemStyle, uint32 emblemColor, uint32 borderStyle, uint32 borderColor)
Definition at line 444 of file ArenaTeam.cpp.
References CharacterDatabase, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_EmblemColor, m_EmblemStyle, m_TeamId, and Database::PExecute().
Referenced by WorldSession::HandleTurnInPetitionOpcode().
SetRatingForAll()
void ArenaTeam::SetRatingForAll (uint32 rating)
Definition at line 799 of file ArenaTeam.cpp.
References m_members, m_stats, and ArenaTeamStats::rating.
Referenced by ChatHandler::HandleArenaTeamPointSet().
SetStats()
void ArenaTeam::SetStats (uint32 stat_type, uint32 value)
Definition at line 455 of file ArenaTeam.cpp.
References CharacterDatabase, DEBUG_LOG, ArenaTeamStats::games_season, ArenaTeamStats::games_week, GetId(), m_stats, Database::PExecute(), ArenaTeamStats::rank, ArenaTeamStats::rating, STAT_TYPE_GAMES_SEASON, STAT_TYPE_GAMES_WEEK, STAT_TYPE_RANK, STAT_TYPE_RATING, STAT_TYPE_WINS_SEASON, STAT_TYPE_WINS_WEEK, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Stats()
void ArenaTeam::Stats (WorldSession * session) const
Definition at line 401 of file ArenaTeam.cpp.
References ArenaTeamStats::games_season, ArenaTeamStats::games_week, GetId(), m_stats, ArenaTeamStats::rank, ArenaTeamStats::rating, WorldSession::SendPacket(), SMSG_ARENA_TEAM_STATS, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Referenced by NotifyStatsChanged().
UpdateArenaPointsHelper()
void ArenaTeam::UpdateArenaPointsHelper (std::map< uint32, uint32 > & PlayerPoints)
Definition at line 715 of file ArenaTeam.cpp.
References ArenaTeamStats::games_week, GetPoints(), m_members, and m_stats.
WonAgainst()
int32 ArenaTeam::WonAgainst (uint32 againstRating)
Definition at line 609 of file ArenaTeam.cpp.
References FinishGame(), GetChanceAgainst(), m_stats, ArenaTeamStats::rating, ArenaTeamStats::wins_season, and ArenaTeamStats::wins_week.
Referenced by BattleGround::EndBattleGround().
Field Documentation
m_BackgroundColor
uint32 ArenaTeam::m_BackgroundColor protected
Definition at line 220 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetBackgroundColor(), LoadArenaTeamFromDB(), Query(), and SetEmblem().
m_BorderColor
uint32 ArenaTeam::m_BorderColor protected
Definition at line 224 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetBorderColor(), LoadArenaTeamFromDB(), Query(), and SetEmblem().
m_BorderStyle
uint32 ArenaTeam::m_BorderStyle protected
Definition at line 223 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetBorderStyle(), LoadArenaTeamFromDB(), Query(), and SetEmblem().
m_CaptainGuid
ObjectGuid ArenaTeam::m_CaptainGuid protected
Definition at line 218 of file ArenaTeam.h.
Referenced by AddMember(), Create(), GetCaptainGuid(), LoadArenaTeamFromDB(), and SetCaptain().
m_EmblemColor
uint32 ArenaTeam::m_EmblemColor protected
Definition at line 222 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetEmblemColor(), LoadArenaTeamFromDB(), Query(), and SetEmblem().
m_EmblemStyle
uint32 ArenaTeam::m_EmblemStyle protected
Definition at line 221 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetEmblemStyle(), LoadArenaTeamFromDB(), Query(), and SetEmblem().
m_members
MemberList ArenaTeam::m_members protected
Definition at line 226 of file ArenaTeam.h.
Referenced by AddMember(), BroadcastPacket(), DelMember(), Disband(), Empty(), FinishSeason(), FinishWeek(), GetMember(), GetMembers(), GetMembersSize(), HaveMember(), IsFighting(), LoadMembersFromDB(), MassInviteToEvent(), MemberLost(), MemberWon(), NotifyStatsChanged(), OfflineMemberLost(), Roster(), SaveToDB(), SetRatingForAll(), and UpdateArenaPointsHelper().
m_Name
std::string ArenaTeam::m_Name protected
Definition at line 217 of file ArenaTeam.h.
Referenced by Create(), GetName(), and LoadArenaTeamFromDB().
m_stats
ArenaTeamStats ArenaTeam::m_stats protected
Definition at line 227 of file ArenaTeam.h.
Referenced by AddMember(), ArenaTeam(), Create(), FinishGame(), FinishSeason(), FinishWeek(), GetPoints(), GetRating(), GetStats(), InspectStats(), LoadArenaTeamFromDB(), LostAgainst(), SaveToDB(), SetRatingForAll(), SetStats(), Stats(), UpdateArenaPointsHelper(), and WonAgainst().
m_TeamId
uint32 ArenaTeam::m_TeamId protected
Definition at line 215 of file ArenaTeam.h.
Referenced by AddMember(), ArenaTeam(), Create(), Disband(), GetId(), LoadArenaTeamFromDB(), LoadMembersFromDB(), SaveToDB(), SetCaptain(), and SetEmblem().
m_Type
ArenaType ArenaTeam::m_Type protected
Definition at line 216 of file ArenaTeam.h.
Referenced by ArenaTeam(), Create(), GetPoints(), GetType(), and LoadArenaTeamFromDB().
The documentation for this class was generated from the following files:
ArenaTeam.h
ArenaTeam.cpp