CMaNGOS_WoTLK: Bag Class Reference
Bag Class Reference
#include <Bag.h>
Public Member Functions
Bag ()
~Bag ()
void AddToWorld () override
void RemoveFromWorld () override
bool Create (uint32 guidlow, uint32 itemid, Player const *owner) override
void StoreItem (uint8 slot, Item *pItem)
void RemoveItem (uint8 slot)
Item * GetItemByPos (uint8 slot) const
Item * GetItemByEntry (uint32 item) const
Item * GetItemByLimitedCategory (uint32 limitedCategory) const
uint32 GetItemCount (uint32 item, Item *skipItem=nullptr) const
uint32 GetItemCountWithLimitCategory (uint32 limitCategory, Item *eItem=nullptr) const
uint8 GetSlotByItemGUID (ObjectGuid guid) const
bool IsEmpty () const
uint32 GetFreeSlots () const
uint32 GetBagSize () const
void SaveToDB () override
bool LoadFromDB (uint32 guidLow, Field *fields, ObjectGuid ownerGuid=ObjectGuid()) override
void DeleteFromDB () override
void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const override
Public Member Functions inherited from Item
Item * CloneItem (uint32 count, Player const *player=nullptr) const
Item ()
ItemPrototype const * GetProto () const
ObjectGuid const & GetOwnerGuid () const
void SetOwnerGuid (ObjectGuid guid)
Player * GetOwner () const
void SetBinding (bool val)
bool IsSoulBound () const
bool IsBoundAccountWide () const
bool IsBindedNotWith (Player const *player) const
bool IsBoundByEnchant () const
bool IsMainHandOnlyEnchant (EnchantmentSlot slot) const
bool CanEnterArenaEnchant (EnchantmentSlot slot) const
void DeleteFromInventoryDB () const
void LoadLootFromDB (Field *fields)
bool IsUnlocked () const
bool IsBag () const
bool IsBroken () const
bool CanBeTraded (bool mail=false) const
void SetInTrade (bool b=true)
bool IsInTrade () const
bool IsFitToSpellRequirements (SpellEntry const *spellInfo) const
bool IsTargetValidForItemUse (Unit *pUnitTarget) const
bool IsLimitedToAnotherMapOrZone (uint32 cur_mapId, uint32 cur_zoneId) const
bool GemsFitSockets () const
uint32 GetCount () const
void SetCount (uint32 value)
uint32 GetMaxStackCount () const
uint8 GetGemCountWithID (uint32 GemID) const
uint8 GetGemCountWithLimitCategory (uint32 limitCategory) const
InventoryResult CanBeMergedPartlyWith (ItemPrototype const *proto) const
uint8 GetSlot () const
Bag * GetContainer () const
uint8 GetBagSlot () const
void SetSlot (uint8 slot)
uint16 GetPos () const
void SetContainer (Bag *container)
bool IsInBag () const
bool IsEquipped () const
uint32 GetSkill () const
uint32 GetSpell () const
int32 GetItemRandomPropertyId () const
uint32 GetItemSuffixFactor () const
void SetItemRandomProperties (int32 randomPropId)
void UpdateItemSuffixFactor ()
void SetEnchantment (EnchantmentSlot slot, uint32 id, uint32 duration, uint32 charges, ObjectGuid caster=ObjectGuid())
void SetEnchantmentDuration (EnchantmentSlot slot, uint32 duration)
void SetEnchantmentCharges (EnchantmentSlot slot, uint32 charges)
void ClearEnchantment (EnchantmentSlot slot)
uint32 GetEnchantmentId (EnchantmentSlot slot) const
uint32 GetEnchantmentDuration (EnchantmentSlot slot) const
uint32 GetEnchantmentCharges (EnchantmentSlot slot) const
std::string const & GetText () const
void SetText (std::string const &text)
void SendUpdateSockets ()
void SendTimeUpdate (Player *owner) const
void UpdateDuration (Player *owner, uint32 diff)
int32 GetSpellCharges (uint8 index=0) const
void SetSpellCharges (uint8 index, int32 value)
bool HasMaxCharges () const
void RestoreCharges ()
void SetLootState (ItemLootUpdateState state)
bool HasGeneratedLoot () const
bool HasTemporaryLoot () const
bool HasSavedLoot () const
ItemUpdateState GetState () const
void SetState (ItemUpdateState state, Player *forplayer=nullptr)
void AddToUpdateQueueOf (Player *player)
void RemoveFromUpdateQueueOf (Player *player)
bool IsInUpdateQueue () const
uint16 GetQueuePos () const
void FSetState (ItemUpdateState state)
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32) const override
bool IsPotion () const
bool IsConjuredConsumable () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &update_players) override
bool IsUsedInSpell () const
void SetUsedInSpell (bool state)
uint32 GetTotalAP () const
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Protected Attributes
Item * m_bagslot [MAX_BAG_SIZE]
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Additional Inherited Members
Static Public Member Functions inherited from Item
static Item * CreateItem (uint32 item, uint32 count, Player const *player=nullptr, uint32 randomPropertyId=0)
static int32 GenerateItemRandomPropertyId (uint32 item_id)
Data Fields inherited from Object
Loot * m_loot
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Detailed Description
Definition at line 34 of file Bag.h.
Constructor & Destructor Documentation
Bag()
Bag::Bag ()
Definition at line 24 of file Bag.cpp.
References CONTAINER_END, m_bagslot, Object::m_objectType, Object::m_objectTypeId, Object::m_valuesCount, MAX_BAG_SIZE, TYPEID_CONTAINER, TYPEMASK_CONTAINER, and TYPEMASK_ITEM.
~Bag()
Bag::~Bag ()
Definition at line 34 of file Bag.cpp.
References m_bagslot.
Member Function Documentation
AddToWorld()
void Bag::AddToWorld () override virtual
Reimplemented from Object.
Definition at line 40 of file Bag.cpp.
References Object::AddToWorld(), GetBagSize(), and m_bagslot.
BuildCreateUpdateBlockForPlayer()
void Bag::BuildCreateUpdateBlockForPlayer (UpdateData * data, Player * target) const override virtual
Reimplemented from Object.
Definition at line 164 of file Bag.cpp.
References Object::BuildCreateUpdateBlockForPlayer(), GetBagSize(), and m_bagslot.
Create()
bool Bag::Create (uint32 guidlow, uint32 itemid, Player const * owner) override virtual
Reimplemented from Item.
Definition at line 58 of file Bag.cpp.
References Object::_Create(), CONTAINER_FIELD_NUM_SLOTS, CONTAINER_FIELD_SLOT_1, ItemPrototype::ContainerSlots, DEFAULT_OBJECT_SCALE, ObjectMgr::GetItemPrototype(), Object::GetObjectGuid(), HIGHGUID_CONTAINER, ITEM_FIELD_CONTAINED, ITEM_FIELD_DURABILITY, ITEM_FIELD_MAXDURABILITY, ITEM_FIELD_OWNER, ITEM_FIELD_STACK_COUNT, m_bagslot, MAX_BAG_SIZE, ItemPrototype::MaxDurability, Object::SetEntry(), Object::SetGuidValue(), Object::SetObjectScale(), and Object::SetUInt32Value().
DeleteFromDB()
void Bag::DeleteFromDB () override virtual
Reimplemented from Item.
Definition at line 119 of file Bag.cpp.
References Item::DeleteFromDB(), and m_bagslot.
GetBagSize()
uint32 Bag::GetBagSize () const inline
Definition at line 58 of file Bag.h.
References CONTAINER_FIELD_NUM_SLOTS, and Object::GetUInt32Value().
Referenced by Player::_CanStoreItem_InBag(), PlayerbotAI::_findItemSlot(), AddToWorld(), PlayerbotAI::AutoUpgradeEquipment(), PlayerbotAI::BankBalance(), BuildCreateUpdateBlockForPlayer(), Player::CanStoreItems(), Player::CanUnequipItems(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotAI::DropGarbage(), PlayerbotAI::FindBandage(), PlayerbotAI::FindConsumable(), PlayerbotAI::FindDrink(), PlayerbotAI::FindFood(), PlayerbotAI::FindItem(), PlayerbotAI::FindItemInBank(), PlayerbotAI::findItemsInInv(), PlayerbotAI::FindMount(), PlayerbotAI::FindPoison(), Player::GetEquipGearScore(), GetFreeSlots(), GetItemByEntry(), GetItemByLimitedCategory(), GetItemByPos(), GetItemCount(), GetItemCountWithLimitCategory(), GetSlotByItemGUID(), PlayerbotAI::HandleBotOutgoingPacket(), ChatHandler::HandleDebugGetItemStateCommand(), IsEmpty(), Player::IsValidPos(), Player::RemoveAllEnchantments(), RemoveFromWorld(), PlayerbotAI::SellGarbage(), PlayerbotAI::SendNotEquipList(), and Player::SwapItem().
GetFreeSlots()
uint32 Bag::GetFreeSlots () const
Definition at line 128 of file Bag.cpp.
References GetBagSize(), and m_bagslot.
Referenced by PlayerbotAI::CanStore(), and PlayerbotAI::GetFreeBagSpace().
GetItemByEntry()
Item * Bag::GetItemByEntry (uint32 item) const
Definition at line 183 of file Bag.cpp.
References GetBagSize(), Object::GetEntry(), and m_bagslot.
GetItemByLimitedCategory()
Item * Bag::GetItemByLimitedCategory (uint32 limitedCategory) const
Definition at line 192 of file Bag.cpp.
References GetBagSize(), Item::GetProto(), ItemPrototype::ItemLimitCategory, and m_bagslot.
GetItemByPos()
Item * Bag::GetItemByPos (uint8 slot) const
Definition at line 244 of file Bag.cpp.
References GetBagSize(), and m_bagslot.
Referenced by Player::GetEquipGearScore(), Player::GetItemByPos(), ChatHandler::HandleDebugGetItemStateCommand(), Player::RemoveAllEnchantments(), and Player::SwapItem().
GetItemCount()
uint32 Bag::GetItemCount (uint32 item, Item * skipItem = nullptr) const
Definition at line 201 of file Bag.cpp.
References _Socket::Color, ItemPrototype::GemProperties, GetBagSize(), Item::GetCount(), Object::GetEntry(), Item::GetGemCountWithID(), Item::GetProto(), m_bagslot, and ItemPrototype::Socket.
Referenced by Player::GetItemCount().
GetItemCountWithLimitCategory()
uint32 Bag::GetItemCountWithLimitCategory (uint32 limitCategory, Item * eItem = nullptr) const
Definition at line 222 of file Bag.cpp.
References GetBagSize(), Item::GetCount(), Item::GetProto(), ItemPrototype::ItemLimitCategory, and m_bagslot.
GetSlotByItemGUID()
uint8 Bag::GetSlotByItemGUID (ObjectGuid guid) const
Definition at line 234 of file Bag.cpp.
References GetBagSize(), Object::GetObjectGuid(), m_bagslot, and NULL_SLOT.
IsEmpty()
bool Bag::IsEmpty () const
Definition at line 174 of file Bag.cpp.
References GetBagSize(), and m_bagslot.
Referenced by Player::CanBankItem().
LoadFromDB()
bool Bag::LoadFromDB (uint32 guidLow, Field * fields, ObjectGuid ownerGuid = ObjectGuid()) override virtual
Reimplemented from Item.
Definition at line 95 of file Bag.cpp.
References CONTAINER_FIELD_NUM_SLOTS, CONTAINER_FIELD_SLOT_1, ItemPrototype::ContainerSlots, Object::GetEntry(), Item::LoadFromDB(), m_bagslot, MAX_BAG_SIZE, Object::SetGuidValue(), Object::SetUInt32Value(), and sObjectMgr.
RemoveFromWorld()
void Bag::RemoveFromWorld () override virtual
Reimplemented from Object.
Definition at line 49 of file Bag.cpp.
References GetBagSize(), m_bagslot, and Object::RemoveFromWorld().
RemoveItem()
void Bag::RemoveItem (uint8 slot)
Definition at line 138 of file Bag.cpp.
References CONTAINER_FIELD_SLOT_1, m_bagslot, MANGOS_ASSERT, MAX_BAG_SIZE, Item::SetContainer(), and Object::SetGuidValue().
Referenced by Player::RemoveItem(), and Player::SwapItem().
SaveToDB()
void Bag::SaveToDB () override virtual
Reimplemented from Item.
Definition at line 90 of file Bag.cpp.
References Item::SaveToDB().
StoreItem()
void Bag::StoreItem (uint8 slot, Item * pItem)
Definition at line 149 of file Bag.cpp.
References CONTAINER_FIELD_SLOT_1, Object::GetObjectGuid(), Item::GetOwnerGuid(), ITEM_FIELD_CONTAINED, ITEM_FIELD_OWNER, m_bagslot, MANGOS_ASSERT, MAX_BAG_SIZE, Item::SetContainer(), Object::SetGuidValue(), and Item::SetSlot().
Referenced by Player::SwapItem().
Field Documentation
m_bagslot
Item* Bag::m_bagslot[MAX_BAG_SIZE] protected
Definition at line 73 of file Bag.h.
Referenced by AddToWorld(), Bag(), BuildCreateUpdateBlockForPlayer(), Create(), DeleteFromDB(), GetFreeSlots(), GetItemByEntry(), GetItemByLimitedCategory(), GetItemByPos(), GetItemCount(), GetItemCountWithLimitCategory(), GetSlotByItemGUID(), IsEmpty(), LoadFromDB(), RemoveFromWorld(), RemoveItem(), StoreItem(), and ~Bag().
The documentation for this class was generated from the following files:
Bag.h
Bag.cpp