CMaNGOS_WoTLK: GuildMgr Class Reference
GuildMgr Class Reference
#include <GuildMgr.h>
Public Member Functions
GuildMgr ()
~GuildMgr ()
void AddGuild (Guild *guild)
void RemoveGuild (uint32 guildId)
Guild * GetGuildById (uint32 guildId) const
Guild * GetGuildByName (std::string const &name) const
Guild * GetGuildByLeader (ObjectGuid const &guid) const
std::string GetGuildNameById (uint32 guildId) const
void LoadGuilds ()
Private Types
typedef std::unordered_map< uint32, Guild * > GuildMap
Private Attributes
GuildMap m_GuildMap
Detailed Description
Definition at line 27 of file GuildMgr.h.
Member Typedef Documentation
GuildMap
typedef std::unordered_map<uint32, Guild*> GuildMgr::GuildMap private
Definition at line 29 of file GuildMgr.h.
Constructor & Destructor Documentation
GuildMgr()
GuildMgr::GuildMgr ()
Definition at line 30 of file GuildMgr.cpp.
~GuildMgr()
GuildMgr::~GuildMgr ()
Definition at line 34 of file GuildMgr.cpp.
References m_GuildMap.
Member Function Documentation
AddGuild()
void GuildMgr::AddGuild (Guild * guild)
Definition at line 40 of file GuildMgr.cpp.
References Guild::GetId(), and m_GuildMap.
Referenced by LoadGuilds().
GetGuildById()
Guild * GuildMgr::GetGuildById (uint32 guildId) const
Definition at line 50 of file GuildMgr.cpp.
References m_GuildMap.
GetGuildByLeader()
Guild * GuildMgr::GetGuildByLeader (ObjectGuid const & guid) const
Definition at line 68 of file GuildMgr.cpp.
References m_GuildMap.
GetGuildByName()
Guild * GuildMgr::GetGuildByName (std::string const & name) const
Definition at line 59 of file GuildMgr.cpp.
References m_GuildMap.
GetGuildNameById()
std::string GuildMgr::GetGuildNameById (uint32 guildId) const
Definition at line 77 of file GuildMgr.cpp.
References m_GuildMap.
LoadGuilds()
void GuildMgr::LoadGuilds ()
Definition at line 86 of file GuildMgr.cpp.
References AddGuild(), CharacterDatabase, Guild::CheckGuildStructure(), CONFIG_UINT32_GUILD_BANK_EVENT_LOG_COUNT, CONFIG_UINT32_GUILD_EVENT_LOG_COUNT, Guild::Disband(), QueryResult::GetRowCount(), Guild::LoadBankRightsFromDB(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), Guild::LoadGuildFromDB(), Guild::LoadMembersFromDB(), Guild::LoadRanksFromDB(), QueryResult::NextRow(), Database::PExecute(), Database::Query(), sLog, BarGoLink::step(), and sWorld.
RemoveGuild()
void GuildMgr::RemoveGuild (uint32 guildId)
Definition at line 45 of file GuildMgr.cpp.
References m_GuildMap.
Field Documentation
m_GuildMap
GuildMap GuildMgr::m_GuildMap private
Definition at line 31 of file GuildMgr.h.
Referenced by AddGuild(), GetGuildById(), GetGuildByLeader(), GetGuildByName(), GetGuildNameById(), RemoveGuild(), and ~GuildMgr().
The documentation for this class was generated from the following files:
GuildMgr.h
GuildMgr.cpp