CMaNGOS_WoTLK: PrioritizeManaUnitWraper Class Reference
PrioritizeManaUnitWraper Class Reference
Public Member Functions
PrioritizeManaUnitWraper (Unit *unit)
Unit * getUnit () const
uint32 getPercent () const
Private Attributes
Unit * i_unit
uint32 i_percent
Detailed Description
Definition at line 55 of file Spell.cpp.
Constructor & Destructor Documentation
PrioritizeManaUnitWraper()
PrioritizeManaUnitWraper::PrioritizeManaUnitWraper (Unit * unit) inline explicit
Definition at line 58 of file Spell.cpp.
References Unit::GetMaxPower(), Unit::GetPower(), i_percent, and POWER_MANA.
Member Function Documentation
getPercent()
uint32 PrioritizeManaUnitWraper::getPercent () const inline
Definition at line 64 of file Spell.cpp.
References i_percent.
Referenced by PrioritizeMana::operator()().
getUnit()
Unit* PrioritizeManaUnitWraper::getUnit () const inline
Definition at line 63 of file Spell.cpp.
References i_unit.
Field Documentation
i_percent
uint32 PrioritizeManaUnitWraper::i_percent private
Definition at line 67 of file Spell.cpp.
Referenced by getPercent(), and PrioritizeManaUnitWraper().
i_unit
Unit* PrioritizeManaUnitWraper::i_unit private
Definition at line 66 of file Spell.cpp.
Referenced by getUnit().
The documentation for this class was generated from the following file:
Spell.cpp