CMaNGOS_WoTLK: GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > Class Template Reference
GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > Class Template Reference
The GridLoader is working in conjuction with the Grid and responsible for loading and unloading object-types (one or more) when objects enters a grid.
#include <GridLoader.h>
Public Member Functions
template<class LOADER >
void Load (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > &grid, LOADER &loader)
Loads the grid.
template<class STOPER >
void Stop (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > &grid, STOPER &stoper)
Stop the grid.
template<class UNLOADER >
void Unload (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > &grid, UNLOADER &unloader)
Unloads the grid.
Detailed Description
template<class ACTIVE_OBJECT, class WORLD_OBJECT_TYPES, class GRID_OBJECT_TYPES>
class GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >
The GridLoader is working in conjuction with the Grid and responsible for loading and unloading object-types (one or more) when objects enters a grid.
Unloading is scheduled and might be canceled if an interested object re-enters. GridLoader does not do the actuall loading and unloading but implements as a template pattern that delicate its loading and unloading for the actualy loader and unloader. GridLoader manages the grid (both local and remote).
Definition at line 43 of file GridLoader.h.
Member Function Documentation
Load()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class LOADER > void GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Load (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > & grid, LOADER & loader) inline
Loads the grid.
Definition at line 50 of file GridLoader.h.
Referenced by ObjectGridLoader::LoadN().
Stop()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class STOPER > void GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Stop (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > & grid, STOPER & stoper) inline
Stop the grid.
Definition at line 58 of file GridLoader.h.
Referenced by ObjectGridStoper::StopN().
Unload()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class UNLOADER > void GridLoader< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Unload (Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > & grid, UNLOADER & unloader) inline
Unloads the grid.
Definition at line 66 of file GridLoader.h.
Referenced by ObjectGridUnloader::UnloadN().
The documentation for this class was generated from the following files:
Grid.h
GridLoader.h