CMaNGOS_WoTLK: AiDelayEventAround Class Reference
AiDelayEventAround Class Reference
Public Member Functions
AiDelayEventAround (AIEventType eventType, ObjectGuid invokerGuid, Unit &owner, CreatureList const &receivers, uint32 miscValue)
bool Execute (uint64, uint32) override
Public Member Functions inherited from BasicEvent
BasicEvent ()
virtual ~BasicEvent ()
virtual bool IsDeletable () const
virtual void Abort (uint64)
Private Member Functions
AiDelayEventAround ()
Private Attributes
AIEventType m_eventType
ObjectGuid m_invokerGuid
Unit & m_owner
uint32 m_miscValue
GuidVector m_receiverGuids
Additional Inherited Members
Data Fields inherited from BasicEvent
bool to_Abort
uint64 m_addTime
uint64 m_execTime
Detailed Description
Definition at line 580 of file UnitAI.cpp.
Constructor & Destructor Documentation
AiDelayEventAround() [1/2]
AiDelayEventAround::AiDelayEventAround (AIEventType eventType, ObjectGuid invokerGuid, Unit & owner, CreatureList const & receivers, uint32 miscValue) inline
Definition at line 583 of file UnitAI.cpp.
References m_receiverGuids.
AiDelayEventAround() [2/2]
AiDelayEventAround::AiDelayEventAround () private
Member Function Documentation
Execute()
bool AiDelayEventAround::Execute (uint64 , uint32) inline override virtual
Reimplemented from BasicEvent.
Definition at line 596 of file UnitAI.cpp.
References Unit::AI(), AI_EVENT_CALL_ASSISTANCE, Map::GetAnyTypeCreature(), WorldObject::GetMap(), Map::GetUnit(), m_eventType, m_invokerGuid, m_miscValue, m_owner, m_receiverGuids, and UnitAI::ReceiveAIEvent().
Field Documentation
m_eventType
AIEventType AiDelayEventAround::m_eventType private
Definition at line 620 of file UnitAI.cpp.
Referenced by Execute().
m_invokerGuid
ObjectGuid AiDelayEventAround::m_invokerGuid private
Definition at line 621 of file UnitAI.cpp.
Referenced by Execute().
m_miscValue
uint32 AiDelayEventAround::m_miscValue private
Definition at line 623 of file UnitAI.cpp.
Referenced by Execute().
m_owner
Unit& AiDelayEventAround::m_owner private
Definition at line 622 of file UnitAI.cpp.
Referenced by Execute().
m_receiverGuids
GuidVector AiDelayEventAround::m_receiverGuids private
Definition at line 625 of file UnitAI.cpp.
Referenced by AiDelayEventAround(), and Execute().
The documentation for this class was generated from the following file:
UnitAI.cpp