CMaNGOS_WoTLK: LootTemplate Class Reference
LootTemplate Class Reference
#include <LootMgr.h>
Data Structures
class LootGroup
Public Member Functions
void AddEntry (LootStoreItem &item)
void Process (Loot &loot, Player const *lootOwner, LootStore const &store, bool rate, uint8 groupId=0) const
bool HasQuestDrop (LootTemplateMap const &store, uint8 groupId=0) const
bool HasQuestDropForPlayer (LootTemplateMap const &store, Player const *player, uint8 groupId=0) const
void Verify (LootStore const &lootstore, uint32 id) const
void CheckLootRefs (LootIdSet *ref_set) const
Static Public Member Functions
static bool PlayerOrGroupFulfilsCondition (const Loot &loot, Player const *lootOwner, uint16 conditionId)
Private Types
typedef std::vector< LootGroup > LootGroups
Private Attributes
LootStoreItemList Entries
LootGroups Groups
Detailed Description
Definition at line 257 of file LootMgr.h.
Member Typedef Documentation
LootGroups
typedef std::vector<LootGroup> LootTemplate::LootGroups private
Definition at line 260 of file LootMgr.h.
Member Function Documentation
AddEntry()
void LootTemplate::AddEntry (LootStoreItem & item)
Definition at line 2637 of file LootMgr.cpp.
References Entries, LootStoreItem::group, Groups, and LootStoreItem::mincountOrRef.
CheckLootRefs()
void LootTemplate::CheckLootRefs (LootIdSet * ref_set) const
Definition at line 2781 of file LootMgr.cpp.
References Entries, LootStore::GetLootFor(), Groups, LootTemplates_Reference, and LootStore::ReportNotExistedId().
HasQuestDrop()
bool LootTemplate::HasQuestDrop (LootTemplateMap const & store, uint8 groupId = 0) const
Definition at line 2691 of file LootMgr.cpp.
References Entries, and Groups.
HasQuestDropForPlayer()
bool LootTemplate::HasQuestDropForPlayer (LootTemplateMap const & store, Player const * player, uint8 groupId = 0) const
Definition at line 2723 of file LootMgr.cpp.
References Entries, Groups, and Player::HasQuestForItem().
PlayerOrGroupFulfilsCondition()
bool LootTemplate::PlayerOrGroupFulfilsCondition (const Loot & loot, Player const * lootOwner, uint16 conditionId) static
Definition at line 2755 of file LootMgr.cpp.
References CONDITION_FROM_REFERING_LOOT, Loot::GetLootTarget(), WorldObject::GetMap(), Loot::GetOwnerSet(), Map::GetPlayer(), Object::IsInWorld(), and sObjectMgr.
Referenced by Process(), and LootTemplate::LootGroup::Roll().
Process()
void LootTemplate::Process (Loot & loot, Player const * lootOwner, LootStore const & store, bool rate, uint8 groupId = 0) const
Definition at line 2650 of file LootMgr.cpp.
References Loot::AddItem(), Entries, LootStore::GetLootFor(), Groups, LootTemplates_Reference, PlayerOrGroupFulfilsCondition(), and Process().
Referenced by AuctionHouseBot::AddLootToItemMap(), LootMgr::CheckDropStats(), Loot::FillLoot(), and Process().
Verify()
void LootTemplate::Verify (LootStore const & lootstore, uint32 id) const
Definition at line 2772 of file LootMgr.cpp.
References Groups.
Field Documentation
Entries
LootStoreItemList LootTemplate::Entries private
Definition at line 279 of file LootMgr.h.
Referenced by AddEntry(), CheckLootRefs(), HasQuestDrop(), HasQuestDropForPlayer(), and Process().
Groups
LootGroups LootTemplate::Groups private
Definition at line 280 of file LootMgr.h.
Referenced by AddEntry(), CheckLootRefs(), HasQuestDrop(), HasQuestDropForPlayer(), Process(), and Verify().
The documentation for this class was generated from the following files:
LootMgr.h
LootMgr.cpp