CMaNGOS_WoTLK: MaNGOS::Runnable Class Reference
MaNGOS::Runnable Class Reference abstract
#include <Threading.h>
Public Member Functions
virtual ~Runnable ()
virtual void run ()=0
void incReference ()
void decReference ()
Private Attributes
std::atomic_long m_refs { 0 }
Detailed Description
Definition at line 27 of file Threading.h.
Constructor & Destructor Documentation
~Runnable()
virtual MaNGOS::Runnable::~Runnable () inline virtual
Definition at line 30 of file Threading.h.
Member Function Documentation
decReference()
void MaNGOS::Runnable::decReference () inline
Definition at line 34 of file Threading.h.
References m_refs.
Referenced by MaNGOS::Thread::~Thread().
incReference()
void MaNGOS::Runnable::incReference () inline
Definition at line 33 of file Threading.h.
References m_refs.
Referenced by MaNGOS::Thread::Thread().
run()
virtual void MaNGOS::Runnable::run () pure virtual
Implemented in FreezeDetectorRunnable, WorldRunnable, CliRunnable, and SqlDelayThread.
Referenced by MaNGOS::Thread::ThreadTask().
Field Documentation
m_refs
std::atomic_long MaNGOS::Runnable::m_refs { 0 } private
Definition at line 40 of file Threading.h.
Referenced by decReference(), and incReference().
The documentation for this class was generated from the following file:
Threading.h