CMaNGOS_WoTLK: Warden Class Reference
Warden Class Reference abstract
#include <warden.hpp>
Public Member Functions
virtual ~Warden ()=default
void HandlePacket (WorldPacket &recvData)
const WardenModule * GetModule () const
uint8 GetXor () const
virtual void Update (uint32 diff)
virtual void SetCharEnumPacket (WorldPacket &&packet)=0
virtual void SendPlayerInfo (ChatHandler *handler, bool includeFingerprint) const =0
Static Public Member Functions
static void LoadScriptedScans ()
Static Public Attributes
static constexpr size_t MaxRequest = 256
static constexpr size_t MaxReply = 256
Protected Member Functions
Warden (WorldSession *session, const WardenModule *module, const BigNumber &K, SessionAnticheatInterface *anticheat)
virtual uint32 GetScanFlags () const =0
std::vector< std::shared_ptr< const Scan > > SelectScans (ScanFlags flags) const
void BeginScanClock ()
void EnqueueScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void RequestScans (std::vector< std::shared_ptr< const Scan >> &&scans)
void SendPacket (const ByteBuffer &buff)
Static Protected Member Functions
static uint32 BuildChecksum (const uint8 *data, size_t size)
Protected Attributes
NamreebAnticheat::SessionAnticheat *const _anticheat
WorldSession *const _session
const WardenModule *const _module
uint8 _xor
bool _initialized
std::vector< std::shared_ptr< const Scan > > _pendingScans
std::vector< std::shared_ptr< const Scan > > _enqueuedScans
Static Protected Attributes
static constexpr size_t KeyLength = 16
Private Member Functions
void EncryptData (uint8 *buffer, size_t size)
void DecryptData (uint8 *buffer, size_t size)
void BeginTimeoutClock ()
void StopTimeoutClock ()
void StopScanClock ()
void SendModuleToClient ()
virtual void InitializeClient ()=0
void RequestChallenge ()
void HandleChallengeResponse (ByteBuffer &buff)
void ReadScanResults (ByteBuffer &buff)
Private Attributes
const ChallengeResponseEntry * _crk
uint32 _timeoutClock
uint32 _scanClock
bool _moduleSendPending
SARC4 _inputCrypto
SARC4 _outputCrypto
Detailed Description
Definition at line 47 of file warden.hpp.
Constructor & Destructor Documentation
Warden()
Warden::Warden (WorldSession * session, const WardenModule * module, const BigNumber & K, SessionAnticheatInterface * anticheat) protected
Definition at line 49 of file warden.cpp.
References _anticheat, _inputCrypto, _module, _outputCrypto, _session, _xor, ByteBuffer::append(), BigNumber::AsByteArray(), BeginTimeoutClock(), WardenModule::binary, CLIENT_PLATFORM_X86, SHA1Randx::Generate(), WorldSession::GetAccountId(), WorldSession::GetPlatform(), WorldSession::GetRemoteAddress(), WardenModule::hash, SARC4::Init(), WardenModule::key, KeyLength, MANGOS_ASSERT, SendPacket(), sLog, and WARDEN_SMSG_MODULE_USE.
~Warden()
virtual Warden::~Warden () virtual default
Member Function Documentation
BeginScanClock()
void Warden::BeginScanClock () protected
Definition at line 333 of file warden.cpp.
References _scanClock, WorldTimer::getMSTime(), and sAnticheatConfig.
Referenced by HandlePacket(), Update(), and WardenMac::WardenMac().
BeginTimeoutClock()
void Warden::BeginTimeoutClock () private
Definition at line 318 of file warden.cpp.
References _timeoutClock, WorldTimer::getMSTime(), and sAnticheatConfig.
Referenced by RequestChallenge(), RequestScans(), SendModuleToClient(), Update(), and Warden().
BuildChecksum()
uint32 Warden::BuildChecksum (const uint8 * data, size_t size) static protected
Definition at line 343 of file warden.cpp.
References CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength().
Referenced by WardenWin::BuildFileHashInit(), WardenWin::BuildLuaInit(), WardenWin::BuildTimingInit(), and HandlePacket().
DecryptData()
void Warden::DecryptData (uint8 * buffer, size_t size) private
Definition at line 308 of file warden.cpp.
References _inputCrypto, and SARC4::UpdateData().
Referenced by HandlePacket().
EncryptData()
void Warden::EncryptData (uint8 * buffer, size_t size) private
Definition at line 313 of file warden.cpp.
References _outputCrypto, and SARC4::UpdateData().
Referenced by SendPacket().
EnqueueScans()
void Warden::EnqueueScans (std::vector< std::shared_ptr< const Scan >> && scans) protected
Definition at line 176 of file warden.cpp.
References _enqueuedScans.
Referenced by WardenWin::ValidateEndScene().
GetModule()
const WardenModule* Warden::GetModule () const inline
Definition at line 130 of file warden.hpp.
References _module.
GetScanFlags()
virtual uint32 Warden::GetScanFlags () const protected pure virtual
Implemented in WardenWin, and WardenMac.
Referenced by SelectScans().
GetXor()
uint8 Warden::GetXor () const inline
Definition at line 131 of file warden.hpp.
References _xor.
HandleChallengeResponse()
void Warden::HandleChallengeResponse (ByteBuffer & buff) private
Definition at line 111 of file warden.cpp.
References _anticheat, _crk, _inputCrypto, _outputCrypto, _session, _xor, NamreebAnticheat::CHEAT_TYPE_WARDEN, ChallengeResponseEntry::clientKey, ByteBuffer::contents(), SARC4::Init(), WorldSession::KickPlayer(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), ChallengeResponseEntry::reply, ByteBuffer::rpos(), ChallengeResponseEntry::serverKey, sLog, StopTimeoutClock(), and ByteBuffer::wpos().
Referenced by HandlePacket().
HandlePacket()
void Warden::HandlePacket (WorldPacket & recvData)
Definition at line 356 of file warden.cpp.
References _anticheat, _crk, _module, _moduleSendPending, _session, BeginScanClock(), BuildChecksum(), NamreebAnticheat::CHEAT_TYPE_WARDEN, CLIENT_OS_WIN, ByteBuffer::contents(), DecryptData(), WorldSession::GetAccountId(), WorldSession::GetOS(), WorldSession::GetRemoteAddress(), HandleChallengeResponse(), InitializeClient(), InitialLogin, WorldSession::KickPlayer(), ReadScanResults(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), RequestChallenge(), RequestScans(), ByteBuffer::rpos(), SelectScans(), SendModuleToClient(), ByteBuffer::size(), sLog, StopTimeoutClock(), WARDEN_CMSG_CHEAT_CHECKS_RESULT, WARDEN_CMSG_HASH_RESULT, WARDEN_CMSG_MEM_CHECKS_RESULT, WARDEN_CMSG_MODULE_FAILED, WARDEN_CMSG_MODULE_MISSING, WARDEN_CMSG_MODULE_OK, and ByteBuffer::wpos().
InitializeClient()
virtual void Warden::InitializeClient () private pure virtual
Implemented in WardenWin, and WardenMac.
Referenced by HandlePacket().
LoadScriptedScans()
void Warden::LoadScriptedScans () static
Definition at line 39 of file warden.cpp.
References WardenMac::LoadScriptedScans(), WardenWin::LoadScriptedScans(), sLog, and sWardenScanMgr.
Referenced by NamreebAnticheat::AnticheatLib::Initialize().
ReadScanResults()
void Warden::ReadScanResults (ByteBuffer & buff) private
Definition at line 269 of file warden.cpp.
References _anticheat, _enqueuedScans, _pendingScans, _session, NamreebAnticheat::CHEAT_TYPE_WARDEN, WorldSession::GetPlayer(), InWorld, Object::IsInWorld(), NamreebAnticheat::SessionAnticheat::RecordCheatInternal(), and RequestScans().
Referenced by HandlePacket().
RequestChallenge()
void Warden::RequestChallenge () private
Definition at line 90 of file warden.cpp.
References _crk, _module, _session, ByteBuffer::append(), BeginTimeoutClock(), WardenModule::crk, WorldSession::GetAccountId(), MANGOS_ASSERT, ChallengeResponseEntry::seed, SendPacket(), sLog, StopTimeoutClock(), urand(), and WARDEN_SMSG_HASH_REQUEST.
Referenced by HandlePacket().
RequestScans()
void Warden::RequestScans (std::vector< std::shared_ptr< const Scan >> && scans) protected
Definition at line 182 of file warden.cpp.
References _enqueuedScans, _pendingScans, _session, _xor, ByteBuffer::append(), BeginTimeoutClock(), CLIENT_OS_WIN, WorldSession::GetOS(), MANGOS_ASSERT, MaxReply, MaxRequest, sAnticheatConfig, SendPacket(), WARDEN_SMSG_CHEAT_CHECKS_REQUEST, and ByteBuffer::wpos().
Referenced by HandlePacket(), ReadScanResults(), Update(), and WardenMac::WardenMac().
SelectScans()
std::vector< std::shared_ptr< const Scan > > Warden::SelectScans (ScanFlags flags) const protected
Definition at line 171 of file warden.cpp.
References GetScanFlags(), and sWardenScanMgr.
Referenced by HandlePacket(), Update(), and WardenMac::WardenMac().
SendModuleToClient()
void Warden::SendModuleToClient () private
Definition at line 143 of file warden.cpp.
References _module, _moduleSendPending, _session, ByteBuffer::append(), BeginTimeoutClock(), WardenModule::binary, WorldSession::GetAccountId(), WorldSession::GetRemoteAddress(), SendPacket(), sLog, StopTimeoutClock(), and WARDEN_SMSG_MODULE_CACHE.
Referenced by HandlePacket().
SendPacket()
void Warden::SendPacket (const ByteBuffer & buff) protected
Definition at line 296 of file warden.cpp.
References _session, ByteBuffer::append(), ByteBuffer::contents(), EncryptData(), WorldSession::SendPacket(), SMSG_WARDEN_DATA, and ByteBuffer::wpos().
Referenced by WardenWin::InitializeClient(), RequestChallenge(), RequestScans(), SendModuleToClient(), and Warden().
SendPlayerInfo()
virtual void Warden::SendPlayerInfo (ChatHandler * handler, bool includeFingerprint) const pure virtual
Implemented in WardenWin, and WardenMac.
SetCharEnumPacket()
virtual void Warden::SetCharEnumPacket (WorldPacket && packet) pure virtual
Implemented in WardenWin, and WardenMac.
StopScanClock()
void Warden::StopScanClock () private
Definition at line 338 of file warden.cpp.
References _scanClock.
Referenced by Update().
StopTimeoutClock()
void Warden::StopTimeoutClock () private
Definition at line 328 of file warden.cpp.
References _timeoutClock.
Referenced by HandleChallengeResponse(), HandlePacket(), RequestChallenge(), and SendModuleToClient().
Update()
void Warden::Update (uint32 diff) virtual
Reimplemented in WardenWin, and WardenMac.
Definition at line 485 of file warden.cpp.
References _enqueuedScans, _pendingScans, _scanClock, _session, _timeoutClock, BeginScanClock(), BeginTimeoutClock(), WorldSession::GetAccountId(), WorldTimer::getMSTime(), WorldSession::GetPlayer(), WorldSession::GetRemoteAddress(), InWorld, Object::IsInWorld(), WorldSession::KickPlayer(), None, RequestScans(), SelectScans(), sLog, and StopScanClock().
Referenced by WardenMac::Update(), and WardenWin::Update().
Field Documentation
_anticheat
NamreebAnticheat::SessionAnticheat* const Warden::_anticheat protected
Definition at line 103 of file warden.hpp.
Referenced by HandleChallengeResponse(), HandlePacket(), ReadScanResults(), WardenWin::Update(), and Warden().
_crk
const ChallengeResponseEntry* Warden::_crk private
Definition at line 50 of file warden.hpp.
Referenced by HandleChallengeResponse(), HandlePacket(), and RequestChallenge().
_enqueuedScans
std::vector<std::shared_ptr<const Scan> > Warden::_enqueuedScans protected
Definition at line 115 of file warden.hpp.
Referenced by EnqueueScans(), ReadScanResults(), RequestScans(), and Update().
_initialized
bool Warden::_initialized protected
Definition at line 112 of file warden.hpp.
Referenced by WardenMac::InitializeClient(), WardenWin::InitializeClient(), WardenMac::SetCharEnumPacket(), WardenMac::Update(), and WardenWin::Update().
_inputCrypto
SARC4 Warden::_inputCrypto private
Definition at line 61 of file warden.hpp.
Referenced by DecryptData(), HandleChallengeResponse(), and Warden().
_module
const WardenModule* const Warden::_module protected
Definition at line 107 of file warden.hpp.
Referenced by GetModule(), HandlePacket(), RequestChallenge(), SendModuleToClient(), Warden(), and WardenMac::WardenMac().
_moduleSendPending
bool Warden::_moduleSendPending private
Definition at line 59 of file warden.hpp.
Referenced by HandlePacket(), and SendModuleToClient().
_outputCrypto
SARC4 Warden::_outputCrypto private
Definition at line 62 of file warden.hpp.
Referenced by EncryptData(), HandleChallengeResponse(), and Warden().
_pendingScans
std::vector<std::shared_ptr<const Scan> > Warden::_pendingScans protected
Definition at line 114 of file warden.hpp.
Referenced by ReadScanResults(), RequestScans(), and Update().
_scanClock
uint32 Warden::_scanClock private
Definition at line 56 of file warden.hpp.
Referenced by BeginScanClock(), StopScanClock(), and Update().
_session
WorldSession* const Warden::_session protected
Definition at line 105 of file warden.hpp.
Referenced by WardenMac::GetScanFlags(), WardenWin::GetScanFlags(), HandleChallengeResponse(), HandlePacket(), ReadScanResults(), RequestChallenge(), RequestScans(), SendModuleToClient(), SendPacket(), WardenMac::SetCharEnumPacket(), WardenWin::SetCharEnumPacket(), Update(), WardenMac::Update(), WardenWin::Update(), WardenWin::ValidateEndScene(), Warden(), and WardenMac::WardenMac().
_timeoutClock
uint32 Warden::_timeoutClock private
Definition at line 53 of file warden.hpp.
Referenced by BeginTimeoutClock(), StopTimeoutClock(), and Update().
_xor
uint8 Warden::_xor protected
Definition at line 109 of file warden.hpp.
Referenced by GetXor(), HandleChallengeResponse(), RequestScans(), and Warden().
KeyLength
constexpr size_t Warden::KeyLength = 16 static constexpr protected
Definition at line 85 of file warden.hpp.
Referenced by Warden().
MaxReply
constexpr size_t Warden::MaxReply = 256 static constexpr
Definition at line 124 of file warden.hpp.
Referenced by WardenScanMgr::GetRandomScans(), and RequestScans().
MaxRequest
constexpr size_t Warden::MaxRequest = 256 static constexpr
Definition at line 121 of file warden.hpp.
Referenced by WardenScanMgr::GetRandomScans(), and RequestScans().
The documentation for this class was generated from the following files:
warden.hpp
warden.cpp