CMaNGOS_WoTLK: MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck Class Reference
MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyUnfriendlyUnitInObjectRangeCheck (WorldObject const *obj, float range)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u) const
Private Attributes
WorldObject const * i_obj
bool i_controlledByPlayer
float i_range
Detailed Description
Definition at line 1104 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyUnfriendlyUnitInObjectRangeCheck()
MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::AnyUnfriendlyUnitInObjectRangeCheck (WorldObject const * obj, float range) inline
Definition at line 1107 of file GridNotifiers.h.
References i_controlledByPlayer, and WorldObject::IsControlledByPlayer().
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::GetFocusObject () const inline
Definition at line 1111 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::operator() (Unit * u) const inline
Definition at line 1112 of file GridNotifiers.h.
References WorldObject::CanAttackSpell(), Object::GetTypeId(), i_obj, i_range, Unit::IsAlive(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), and TYPEID_UNIT.
Field Documentation
i_controlledByPlayer
bool MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::i_controlledByPlayer private
Definition at line 1122 of file GridNotifiers.h.
Referenced by AnyUnfriendlyUnitInObjectRangeCheck().
i_obj
WorldObject const* MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::i_obj private
Definition at line 1121 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AnyUnfriendlyUnitInObjectRangeCheck::i_range private
Definition at line 1123 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h