CMaNGOS_WoTLK: DBCStorage< T > Class Template Reference
DBCStorage< T > Class Template Reference
#include <DBCStore.h>
Public Member Functions
DBCStorage (const char *f)
~DBCStorage ()
T const * LookupEntry (uint32 id) const
uint32 GetNumRows () const
char const * GetFormat () const
uint32 GetFieldCount () const
bool Load (char const *fn)
bool LoadStringsFrom (char const *fn)
void Clear ()
void EraseEntry (uint32 id)
void InsertEntry (T *entry, uint32 id)
Private Types
typedef std::list< char * > StringPoolList
Private Attributes
uint32 nCount
uint32 fieldCount
char const * fmt
T ** indexTable
T * m_dataTable
StringPoolList m_stringPoolList
Detailed Description
template<class T>
class DBCStorage< T >
Definition at line 25 of file DBCStore.h.
Member Typedef Documentation
StringPoolList
template<class T > typedef std::list<char*> DBCStorage< T >::StringPoolList private
Definition at line 27 of file DBCStore.h.
Constructor & Destructor Documentation
DBCStorage()
template<class T > DBCStorage< T >::DBCStorage (const char * f) inline explicit
Definition at line 29 of file DBCStore.h.
~DBCStorage()
template<class T > DBCStorage< T >::~DBCStorage () inline
Definition at line 30 of file DBCStore.h.
References DBCStorage< T >::Clear().
Member Function Documentation
Clear()
template<class T > void DBCStorage< T >::Clear () inline
Definition at line 73 of file DBCStore.h.
References DBCStorage< T >::indexTable, DBCStorage< T >::m_dataTable, DBCStorage< T >::m_stringPoolList, and DBCStorage< T >::nCount.
Referenced by DBCStorage< T >::~DBCStorage().
EraseEntry()
template<class T > void DBCStorage< T >::EraseEntry (uint32 id) inline
Definition at line 91 of file DBCStore.h.
References DBCStorage< T >::indexTable, and DBCStorage< T >::nCount.
GetFieldCount()
template<class T > uint32 DBCStorage< T >::GetFieldCount () const inline
Definition at line 35 of file DBCStore.h.
References DBCStorage< T >::fieldCount.
Referenced by LoadDBC().
GetFormat()
template<class T > char const* DBCStorage< T >::GetFormat () const inline
Definition at line 34 of file DBCStore.h.
References DBCStorage< T >::fmt.
Referenced by LoadDBC().
GetNumRows()
template<class T > uint32 DBCStorage< T >::GetNumRows () const inline
Definition at line 33 of file DBCStore.h.
References DBCStorage< T >::nCount.
InsertEntry()
template<class T > void DBCStorage< T >::InsertEntry (T * entry, uint32 id) inline
Definition at line 92 of file DBCStore.h.
References DBCStorage< T >::indexTable, and DBCStorage< T >::nCount.
Load()
template<class T > bool DBCStorage< T >::Load (char const * fn) inline
Definition at line 37 of file DBCStore.h.
References DBCFileLoader::AutoProduceData(), DBCFileLoader::AutoProduceStrings(), DBCStorage< T >::fieldCount, DBCStorage< T >::fmt, DBCFileLoader::GetCols(), DBCStorage< T >::indexTable, DBCFileLoader::Load(), DBCStorage< T >::m_dataTable, DBCStorage< T >::m_stringPoolList, and DBCStorage< T >::nCount.
Referenced by LoadDBC().
LoadStringsFrom()
template<class T > bool DBCStorage< T >::LoadStringsFrom (char const * fn) inline
Definition at line 56 of file DBCStore.h.
References DBCFileLoader::AutoProduceStrings(), DBCStorage< T >::fmt, DBCStorage< T >::indexTable, DBCFileLoader::Load(), DBCStorage< T >::m_dataTable, and DBCStorage< T >::m_stringPoolList.
Referenced by LoadDBC().
LookupEntry()
template<class T > T const* DBCStorage< T >::LookupEntry (uint32 id) const inline
Definition at line 32 of file DBCStore.h.
References DBCStorage< T >::indexTable, and DBCStorage< T >::nCount.
Field Documentation
fieldCount
template<class T > uint32 DBCStorage< T >::fieldCount private
Definition at line 96 of file DBCStore.h.
Referenced by DBCStorage< T >::GetFieldCount(), and DBCStorage< T >::Load().
fmt
template<class T > char const* DBCStorage< T >::fmt private
Definition at line 97 of file DBCStore.h.
Referenced by DBCStorage< T >::GetFormat(), DBCStorage< T >::Load(), and DBCStorage< T >::LoadStringsFrom().
indexTable
template<class T > T** DBCStorage< T >::indexTable private
Definition at line 98 of file DBCStore.h.
Referenced by DBCStorage< T >::Clear(), DBCStorage< T >::EraseEntry(), DBCStorage< T >::InsertEntry(), DBCStorage< T >::Load(), DBCStorage< T >::LoadStringsFrom(), and DBCStorage< T >::LookupEntry().
m_dataTable
template<class T > T* DBCStorage< T >::m_dataTable private
Definition at line 99 of file DBCStore.h.
Referenced by DBCStorage< T >::Clear(), DBCStorage< T >::Load(), and DBCStorage< T >::LoadStringsFrom().
m_stringPoolList
template<class T > StringPoolList DBCStorage< T >::m_stringPoolList private
Definition at line 100 of file DBCStore.h.
Referenced by DBCStorage< T >::Clear(), DBCStorage< T >::Load(), and DBCStorage< T >::LoadStringsFrom().
nCount
template<class T > uint32 DBCStorage< T >::nCount private
Definition at line 95 of file DBCStore.h.
Referenced by DBCStorage< T >::Clear(), DBCStorage< T >::EraseEntry(), DBCStorage< T >::GetNumRows(), DBCStorage< T >::InsertEntry(), DBCStorage< T >::Load(), and DBCStorage< T >::LookupEntry().
The documentation for this class was generated from the following file:
DBCStore.h