CMaNGOS_WoTLK: DungeonPersistentState Class Reference
DungeonPersistentState Class Reference
#include <MapPersistentStateMgr.h>
Public Types
typedef PlayerList PlayerListType
typedef std::list< Group * > GroupListType
Public Member Functions
DungeonPersistentState (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, bool canReset, uint32 completedEncountersMask)
~DungeonPersistentState ()
InstanceTemplate const * GetTemplate () const
uint8 GetPlayerCount () const
uint8 GetGroupCount () const
void AddPlayer (Player *player)
bool RemovePlayer (Player *player)
void AddGroup (Group *group)
bool RemoveGroup (Group *group)
time_t GetResetTime () const
void SetResetTime (time_t resetTime)
time_t GetResetTimeForDB () const
bool CanReset () const
void SetCanReset (bool canReset)
void UpdateEncounterState (EncounterCreditType type, uint32 creditEntry)
uint32 GetCompletedEncountersMask () const override
void SaveToDB ()
void DeleteFromDB () const
void DeleteRespawnTimes ()
void UnbindThisState ()
PlayerListType & GetPlayerList ()
GroupListType & GetGroupList ()
Public Member Functions inherited from MapPersistentState
virtual ~MapPersistentState ()
uint32 GetInstanceId () const
ObjectGuid GetInstanceGuid () const
uint32 GetMapId () const
MapEntry const * GetMapEntry () const
Difficulty GetDifficulty () const
bool IsUsedByMap () const
Map * GetMap () const
void SetUsedByMapState (Map *map)
time_t GetCreatureRespawnTime (uint32 loguid) const
void SaveCreatureRespawnTime (uint32 loguid, time_t t)
time_t GetGORespawnTime (uint32 loguid) const
void SaveGORespawnTime (uint32 loguid, time_t t)
time_t GetObjectRespawnTime (uint32 typeId, uint32 loguid) const
void SaveObjectRespawnTime (uint32 typeId, uint32 loguid, time_t t)
void InitPools ()
SpawnedPoolData & GetSpawnedPoolData ()
template<typename T >
bool IsSpawnedPoolObject (uint32 db_guid_or_pool_id)
MapCellObjectGuids const & GetCellObjectGuids (uint32 cell_id)
void AddCreatureToGrid (uint32 guid, CreatureData const *data)
void RemoveCreatureFromGrid (uint32 guid, CreatureData const *data)
void AddGameobjectToGrid (uint32 guid, GameObjectData const *data)
void RemoveGameobjectFromGrid (uint32 guid, GameObjectData const *data)
Protected Member Functions
bool CanBeUnload () const override
bool HasBounds () const
Protected Member Functions inherited from MapPersistentState
MapPersistentState (uint16 MapId, uint32 InstanceId, Difficulty difficulty)
bool UnloadIfEmpty ()
void ClearRespawnTimes ()
bool HasRespawnTimes () const
Private Attributes
time_t m_resetTime
bool m_canReset
PlayerListType m_playerList
GroupListType m_groupList
uint32 m_completedEncountersMask
Additional Inherited Members
Static Public Member Functions inherited from MapPersistentState
static Difficulty GetSaveDifficulty (Difficulty difficulty, MapEntry const *entry)
Detailed Description
Definition at line 180 of file MapPersistentStateMgr.h.
Member Typedef Documentation
GroupListType
typedef std::list<Group*> DungeonPersistentState::GroupListType
Definition at line 232 of file MapPersistentStateMgr.h.
PlayerListType
typedef PlayerList DungeonPersistentState::PlayerListType
Definition at line 231 of file MapPersistentStateMgr.h.
Constructor & Destructor Documentation
DungeonPersistentState()
DungeonPersistentState::DungeonPersistentState (uint16 MapId, uint32 InstanceId, Difficulty difficulty, time_t resetTime, bool canReset, uint32 completedEncountersMask)
Definition at line 228 of file MapPersistentStateMgr.cpp.
~DungeonPersistentState()
DungeonPersistentState::~DungeonPersistentState ()
Definition at line 233 of file MapPersistentStateMgr.cpp.
References DEBUG_LOG, MapPersistentState::GetInstanceId(), MapPersistentState::GetMapId(), and UnbindThisState().
Member Function Documentation
AddGroup()
void DungeonPersistentState::AddGroup (Group * group) inline
Definition at line 201 of file MapPersistentStateMgr.h.
References m_groupList.
Referenced by Group::BindToInstance().
AddPlayer()
void DungeonPersistentState::AddPlayer (Player * player) inline
Definition at line 198 of file MapPersistentStateMgr.h.
References m_playerList.
Referenced by Player::BindToInstance().
CanBeUnload()
bool DungeonPersistentState::CanBeUnload () const override protected virtual
Implements MapPersistentState.
Definition at line 253 of file MapPersistentStateMgr.cpp.
References MapPersistentState::CanBeUnload(), HasBounds(), and MapPersistentState::HasRespawnTimes().
CanReset()
bool DungeonPersistentState::CanReset () const inline
Definition at line 213 of file MapPersistentStateMgr.h.
References m_canReset.
Referenced by DungeonMap::Add(), ChatHandler::HandleGonameCommand(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), Player::ResetInstances(), and Group::ResetInstances().
DeleteFromDB()
void DungeonPersistentState::DeleteFromDB () const
Definition at line 290 of file MapPersistentStateMgr.cpp.
References MapPersistentStateManager::DeleteInstanceFromDB(), and MapPersistentState::GetInstanceId().
Referenced by Player::ResetInstances(), and Group::ResetInstances().
DeleteRespawnTimes()
void DungeonPersistentState::DeleteRespawnTimes ()
Definition at line 280 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, MapPersistentState::ClearRespawnTimes(), Database::CommitTransaction(), MapPersistentState::GetInstanceId(), and Database::PExecute().
Referenced by DungeonMap::UnloadAll().
GetCompletedEncountersMask()
uint32 DungeonPersistentState::GetCompletedEncountersMask () const inline override virtual
Reimplemented from MapPersistentState.
Definition at line 220 of file MapPersistentStateMgr.h.
References m_completedEncountersMask.
Referenced by DungeonMap::Add(), and SaveToDB().
GetGroupCount()
uint8 DungeonPersistentState::GetGroupCount () const inline
Definition at line 194 of file MapPersistentStateMgr.h.
References m_groupList.
Referenced by DungeonMap::Add().
GetGroupList()
GroupListType& DungeonPersistentState::GetGroupList () inline
Definition at line 235 of file MapPersistentStateMgr.h.
References m_groupList.
Referenced by MapPersistentStateManager::_ResetSave().
GetPlayerCount()
uint8 DungeonPersistentState::GetPlayerCount () const inline
Definition at line 193 of file MapPersistentStateMgr.h.
References m_playerList.
Referenced by DungeonMap::Add().
GetPlayerList()
PlayerListType& DungeonPersistentState::GetPlayerList () inline
Definition at line 234 of file MapPersistentStateMgr.h.
References m_playerList.
Referenced by MapPersistentStateManager::_ResetSave().
GetResetTime()
time_t DungeonPersistentState::GetResetTime () const inline
Definition at line 206 of file MapPersistentStateMgr.h.
References m_resetTime.
Referenced by GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), CalendarMgr::SendCalendarRaidLockoutAdd(), CalendarMgr::SendCalendarRaidLockoutRemove(), Player::SendRaidInfo(), and DungeonMap::SetResetSchedule().
GetResetTimeForDB()
time_t DungeonPersistentState::GetResetTimeForDB () const
Definition at line 301 of file MapPersistentStateMgr.cpp.
References DUNGEON_DIFFICULTY_HEROIC, MapPersistentState::GetDifficulty(), MapPersistentState::GetMapId(), GetResetTime(), MAP_RAID, MapEntry::map_type, and sMapStore.
Referenced by SaveToDB().
GetTemplate()
InstanceTemplate const * DungeonPersistentState::GetTemplate () const
Definition at line 296 of file MapPersistentStateMgr.cpp.
References ObjectMgr::GetInstanceTemplate(), and MapPersistentState::GetMapId().
HasBounds()
bool DungeonPersistentState::HasBounds () const inline protected
Definition at line 239 of file MapPersistentStateMgr.h.
References m_groupList, and m_playerList.
Referenced by CanBeUnload().
RemoveGroup()
bool DungeonPersistentState::RemoveGroup (Group * group) inline
Definition at line 202 of file MapPersistentStateMgr.h.
References m_groupList, and MapPersistentState::UnloadIfEmpty().
Referenced by Group::BindToInstance(), and Group::ResetInstances().
RemovePlayer()
bool DungeonPersistentState::RemovePlayer (Player * player) inline
Definition at line 199 of file MapPersistentStateMgr.h.
References m_playerList, and MapPersistentState::UnloadIfEmpty().
Referenced by Player::BindToInstance(), and Player::ResetInstances().
SaveToDB()
void DungeonPersistentState::SaveToDB ()
Definition at line 262 of file MapPersistentStateMgr.cpp.
References CharacterDatabase, Database::escape_string(), GetCompletedEncountersMask(), MapPersistentState::GetDifficulty(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMap(), MapPersistentState::GetMapId(), GetResetTimeForDB(), Database::PExecute(), InstanceData::Save(), and UI64FMTD.
Referenced by MapPersistentStateManager::AddPersistentState().
SetCanReset()
void DungeonPersistentState::SetCanReset (bool canReset) inline
Definition at line 214 of file MapPersistentStateMgr.h.
References m_canReset.
Referenced by Player::BindToInstance().
SetResetTime()
void DungeonPersistentState::SetResetTime (time_t resetTime) inline
Definition at line 207 of file MapPersistentStateMgr.h.
References m_resetTime.
Referenced by DungeonMap::SetResetSchedule().
UnbindThisState()
void DungeonPersistentState::UnbindThisState ()
Definition at line 239 of file MapPersistentStateMgr.cpp.
References MapPersistentState::GetDifficulty(), MapPersistentState::GetMapId(), m_groupList, m_playerList, Player::UnbindInstance(), and Group::UnbindInstance().
Referenced by ~DungeonPersistentState().
UpdateEncounterState()
void DungeonPersistentState::UpdateEncounterState (EncounterCreditType type, uint32 creditEntry)
Definition at line 310 of file MapPersistentStateMgr.cpp.
References Map::AwardLFGRewards(), CharacterDatabase, DungeonEncounterEntry::CompleteWorldStateID, DungeonEncounter::creditType, DungeonEncounter::dbcEntry, DEBUG_LOG, DungeonEncounterEntry::Difficulty, DungeonEncounterEntry::encounterIndex, DungeonEncounterEntry::encounterName, MapPersistentState::GetDifficulty(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMap(), MapPersistentState::GetMapId(), DungeonEncounterEntry::Id, DungeonEncounter::lastEncounterDungeon, m_completedEncountersMask, DungeonEncounterEntry::mapId, Database::PExecute(), sObjectMgr, and sWorld.
Field Documentation
m_canReset
bool DungeonPersistentState::m_canReset private
Definition at line 244 of file MapPersistentStateMgr.h.
Referenced by CanReset(), and SetCanReset().
m_completedEncountersMask
uint32 DungeonPersistentState::m_completedEncountersMask private
Definition at line 252 of file MapPersistentStateMgr.h.
Referenced by GetCompletedEncountersMask(), and UpdateEncounterState().
m_groupList
GroupListType DungeonPersistentState::m_groupList private
Definition at line 250 of file MapPersistentStateMgr.h.
Referenced by AddGroup(), GetGroupCount(), GetGroupList(), HasBounds(), RemoveGroup(), and UnbindThisState().
m_playerList
PlayerListType DungeonPersistentState::m_playerList private
Definition at line 249 of file MapPersistentStateMgr.h.
Referenced by AddPlayer(), GetPlayerCount(), GetPlayerList(), HasBounds(), RemovePlayer(), and UnbindThisState().
m_resetTime
time_t DungeonPersistentState::m_resetTime private
Definition at line 243 of file MapPersistentStateMgr.h.
Referenced by GetResetTime(), and SetResetTime().
The documentation for this class was generated from the following files:
MapPersistentStateMgr.h
MapPersistentStateMgr.cpp