CMaNGOS_WoTLK: instance_halls_of_stone Class Reference
instance_halls_of_stone Class Reference
#include <halls_of_stone.h>
Public Member Functions
instance_halls_of_stone (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureRespawn (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
void ActivateFace (uint8 uiFace, bool bAfterEvent)
void ResetFace (uint8 uiFace)
void SetFaceTimer (uint8 uiFace, uint32 uiTimer)
void SetBrannSpankin (bool bIsMet)
ObjectGuid GetBrannSummonedGuid ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void SortFaces ()
void ProcessFaceSpell (uint8 uiFace)
void ProcessFaceSummon (uint8 uiFace)
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
Face m_aFaces [MAX_FACES]
std::string m_strInstData
uint8 m_uiIronSludgeKilled
bool m_bIsBrannSpankin
uint32 m_uiLightningChannelTimer
ObjectGuid m_protectorStalkerGuid
ObjectGuid m_stormcallerStalkerGuid
ObjectGuid m_custodianStalkerGuid
ObjectGuid m_tribunalCasterGuid
ObjectGuid m_brannSummonedGuid
GuidList m_lKaddrakGUIDs
GuidList m_lAbedneumGUIDs
GuidList m_lMarnakGUIDs
GuidList m_lTribunalGUIDs
GuidList m_lWorldtriggerGUIDs
GuidList m_lRuneDwarfGUIDs
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 100 of file halls_of_stone.h.
Constructor & Destructor Documentation
instance_halls_of_stone()
instance_halls_of_stone::instance_halls_of_stone (Map * pMap)
Definition at line 51 of file halls_of_stone.cpp.
References Initialize().
Member Function Documentation
ActivateFace()
void instance_halls_of_stone::ActivateFace (uint8 uiFace, bool bAfterEvent)
Definition at line 467 of file halls_of_stone.cpp.
References ScriptedInstance::DoUseDoorOrButton(), Map::GetGameObject(), InstanceData::instance, m_aFaces, Face::m_goFaceGuid, and MAX_FACES.
Referenced by npc_brann_hosAI::CompleteTribunalEvent(), and npc_brann_hosAI::JustDidDialogueStep().
CheckAchievementCriteriaMeet()
bool instance_halls_of_stone::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 345 of file halls_of_stone.cpp.
References ACHIEV_CRIT_ABUSE_OOZE, ACHIEV_CRIT_BRANN, m_bIsBrannSpankin, m_uiIronSludgeKilled, and MAX_ACHIEV_SLUDGES.
ExecuteChatCommand()
void instance_halls_of_stone::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 671 of file halls_of_stone.cpp.
References DONE, ChatHandler::ExtractLiteralArg(), fBrannDoorLocation, ScriptedInstance::GetPlayerInMap(), NPC_BRANN, SetData(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_TRIBUNAL.
GetBrannSummonedGuid()
ObjectGuid instance_halls_of_stone::GetBrannSummonedGuid () inline
Definition at line 131 of file halls_of_stone.h.
References m_brannSummonedGuid.
Referenced by boss_sjonnirAI::Aggro(), boss_sjonnirAI::ExecuteAction(), boss_sjonnirAI::JustDied(), and boss_sjonnirAI::JustReachedHome().
GetData()
uint32 instance_halls_of_stone::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 337 of file halls_of_stone.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by npc_brann_hosAI::JustRespawned(), OnCreatureDeath(), OnPlayerEnter(), and npc_brann_hosAI::StartTribunalEvent().
Initialize()
void instance_halls_of_stone::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 59 of file halls_of_stone.cpp.
References m_auiEncounter.
Referenced by instance_halls_of_stone().
Load()
void instance_halls_of_stone::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 589 of file halls_of_stone.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_halls_of_stone::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 80 of file halls_of_stone.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_custodianStalkerGuid, m_lAbedneumGUIDs, m_lKaddrakGUIDs, m_lMarnakGUIDs, m_lRuneDwarfGUIDs, m_lTribunalGUIDs, m_lWorldtriggerGUIDs, ScriptedInstance::m_npcEntryGuidStore, m_protectorStalkerGuid, m_stormcallerStalkerGuid, m_tribunalCasterGuid, NPC_ABEDNEUM, NPC_BRANN, NPC_DARK_MATTER, NPC_GOLEM_CUSTODIAN, NPC_KADDRAK, NPC_LIGHTNING_STALKER, NPC_MARNAK, NPC_RUNE_PROTECTOR, NPC_RUNE_STORMCALLER, NPC_SEARING_GAZE_TARGET, NPC_SJONNIR, NPC_TRIBUNAL_OF_AGES, and NPC_WORLDTRIGGER.
OnCreatureDeath()
void instance_halls_of_stone::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 504 of file halls_of_stone.cpp.
References DONE, GetData(), Object::GetEntry(), IN_PROGRESS, m_uiIronSludgeKilled, NPC_IRON_SLUDGE, NPC_KRYSTALLUS, NPC_MAIDEN_GRIEF, SetData(), TYPE_KRYSTALLUS, TYPE_MAIDEN, and TYPE_SJONNIR.
OnCreatureEnterCombat()
void instance_halls_of_stone::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 521 of file halls_of_stone.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_KRYSTALLUS, NPC_MAIDEN_GRIEF, SetData(), TYPE_KRYSTALLUS, and TYPE_MAIDEN.
OnCreatureEvade()
void instance_halls_of_stone::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 534 of file halls_of_stone.cpp.
References FAIL, Object::GetEntry(), NPC_MAIDEN_GRIEF, SetData(), and TYPE_MAIDEN.
OnCreatureRespawn()
void instance_halls_of_stone::OnCreatureRespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 140 of file halls_of_stone.cpp.
References Creature::AI(), Unit::CastSpell(), Object::GetEntry(), Unit::GetMotionMaster(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), Creature::IsTemporarySummon(), m_brannSummonedGuid, MotionMaster::MoveWaypoint(), NPC_ABEDNEUM, NPC_BRANN, NPC_DARK_MATTER, NPC_DARK_MATTER_TARGET, NPC_EARTHEN_DWARF, NPC_IRON_DWARF, NPC_IRON_SLUDGE, NPC_IRON_TROGG, NPC_KADDRAK, NPC_LIGHTNING_STALKER, NPC_MALFORMED_OOZE, NPC_MARNAK, NPC_SEARING_GAZE_TARGET, NPC_TRIBUNAL_OF_AGES, NPC_WORLDTRIGGER, REACT_PASSIVE, Unit::SetCanEnterCombat(), Unit::SetImmuneToNPC(), UnitAI::SetReactState(), Creature::SetWalk(), SPELL_BRANN_STEALTH, and TRIGGERED_NONE.
OnObjectCreate()
void instance_halls_of_stone::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 189 of file halls_of_stone.cpp.
References DONE, FACE_ABEDNEUM, FACE_KADDRAK, FACE_MARNAK, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_DOOR_MAIDEN, GO_DOOR_SJONNIR, GO_DOOR_TO_TRIBUNAL, GO_DOOR_TRIBUNAL, GO_FLAG_NO_INTERACT, GO_SJONNIR_CONSOLE, GO_TRIBUNAL_CHEST, GO_TRIBUNAL_CHEST_H, GO_TRIBUNAL_CONSOLE, GO_TRIBUNAL_FLOOR, GO_TRIBUNAL_HEAD_CENTER, GO_TRIBUNAL_HEAD_LEFT, GO_TRIBUNAL_HEAD_RIGHT, m_aFaces, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Face::m_goFaceGuid, Object::RemoveFlag(), and TYPE_TRIBUNAL.
OnPlayerEnter()
void instance_halls_of_stone::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 64 of file halls_of_stone.cpp.
References DONE, fBrannDoorLocation, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_brannSummonedGuid, NPC_BRANN, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_SJONNIR, and TYPE_TRIBUNAL.
ProcessFaceSpell()
void instance_halls_of_stone::ProcessFaceSpell (uint8 uiFace) private
Definition at line 611 of file halls_of_stone.cpp.
References FACE_ABEDNEUM, FACE_KADDRAK, FACE_MARNAK, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Map::IsRegularDifficulty(), m_aFaces, Face::m_leftEyeGuid, Face::m_rightEyeGuid, Face::m_uiTimer, NPC_DARK_MATTER, SPELL_DARK_MATTER_START, SPELL_GLARE_OF_THE_TRIBUNAL, SPELL_GLARE_OF_THE_TRIBUNAL_H, SPELL_SUMMON_SEARING_GAZE_TARGET, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by Update().
ProcessFaceSummon()
void instance_halls_of_stone::ProcessFaceSummon (uint8 uiFace) private
Definition at line 636 of file halls_of_stone.cpp.
References FACE_ABEDNEUM, FACE_KADDRAK, FACE_MARNAK, Map::GetCreature(), InstanceData::instance, Map::IsRegularDifficulty(), m_aFaces, Face::m_summonerGuid, Face::m_uiSummonTimer, SPELL_SUMMON_CUSTODIAN, SPELL_SUMMON_PROTECTOR, SPELL_SUMMON_STORMCALLER, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by Update().
ResetFace()
void instance_halls_of_stone::ResetFace (uint8 uiFace)
Definition at line 481 of file halls_of_stone.cpp.
References Map::GetGameObject(), InstanceData::instance, m_aFaces, Face::m_goFaceGuid, and MAX_FACES.
Referenced by npc_brann_hosAI::EndTribunalEvent(), and npc_brann_hosAI::JustDidDialogueStep().
Save()
const char* instance_halls_of_stone::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 117 of file halls_of_stone.h.
References m_strInstData.
SetBrannSpankin()
void instance_halls_of_stone::SetBrannSpankin (bool bIsMet) inline
Definition at line 130 of file halls_of_stone.h.
References m_bIsBrannSpankin.
Referenced by ProcessEventId_event_spell_brann_achievement_fail(), and npc_brann_hosAI::StartTribunalEvent().
SetData()
void instance_halls_of_stone::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 222 of file halls_of_stone.cpp.
References ACHIEV_START_MAIDEN_ID, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, DONE, ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), Map::GetGameObject(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_DOOR_SJONNIR, GO_FLAG_NO_INTERACT, GO_SJONNIR_CONSOLE, GO_TRIBUNAL_CHEST, GO_TRIBUNAL_CHEST_H, GO_TRIBUNAL_CONSOLE, GO_TRIBUNAL_FLOOR, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_aFaces, m_auiEncounter, Face::m_leftEyeGuid, m_lRuneDwarfGUIDs, m_strInstData, m_uiIronSludgeKilled, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SortFaces(), SPECIAL, SPELL_ACHIEVEMENT_CHECK, SPELL_KILL_TRIBUNAL_ADD, TRIGGERED_OLD_TRIGGERED, TYPE_KRYSTALLUS, TYPE_MAIDEN, TYPE_SJONNIR, and TYPE_TRIBUNAL.
Referenced by boss_sjonnirAI::Aggro(), npc_brann_hosAI::CompleteTribunalEvent(), npc_brann_hosAI::EndTribunalEvent(), ExecuteChatCommand(), boss_sjonnirAI::JustDied(), npc_brann_hosAI::JustDied(), boss_sjonnirAI::JustReachedHome(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), and npc_brann_hosAI::PrepareTribunalEvent().
SetFaceTimer()
void instance_halls_of_stone::SetFaceTimer (uint8 uiFace, uint32 uiTimer)
Definition at line 490 of file halls_of_stone.cpp.
References m_aFaces, Face::m_bIsActive, Face::m_uiTimer, and MAX_FACES.
Referenced by npc_brann_hosAI::JustDidDialogueStep().
ShowChatCommands()
void instance_halls_of_stone::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 665 of file halls_of_stone.cpp.
References ChatHandler::SendSysMessage().
SortFaces()
void instance_halls_of_stone::SortFaces () private
Definition at line 380 of file halls_of_stone.cpp.
References FACE_ABEDNEUM, FACE_KADDRAK, FACE_MARNAK, Map::GetGameObject(), GetValidNPCsOfList(), InstanceData::instance, m_aFaces, m_custodianStalkerGuid, m_lAbedneumGUIDs, Face::m_leftEyeGuid, m_lKaddrakGUIDs, m_lMarnakGUIDs, m_lTribunalGUIDs, m_lWorldtriggerGUIDs, m_protectorStalkerGuid, Face::m_rightEyeGuid, Face::m_speakerGuid, m_stormcallerStalkerGuid, and Face::m_summonerGuid.
Referenced by SetData().
Update()
void instance_halls_of_stone::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 544 of file halls_of_stone.cpp.
References Map::GetCreature(), IN_PROGRESS, InstanceData::instance, m_aFaces, m_auiEncounter, m_tribunalCasterGuid, m_uiLightningChannelTimer, Face::m_uiSummonTimer, Face::m_uiTimer, MAX_FACES, ProcessFaceSpell(), ProcessFaceSummon(), SPELL_LIGHTNING_CHANNEL_1, SPELL_LIGHTNING_CHANNEL_2, SPELL_LIGHTNING_CHANNEL_3, TRIGGERED_NONE, TYPE_TRIBUNAL, and urand().
Field Documentation
m_aFaces
Face instance_halls_of_stone::m_aFaces[MAX_FACES] private
Definition at line 139 of file halls_of_stone.h.
Referenced by ActivateFace(), OnObjectCreate(), ProcessFaceSpell(), ProcessFaceSummon(), ResetFace(), SetData(), SetFaceTimer(), SortFaces(), and Update().
m_auiEncounter
uint32 instance_halls_of_stone::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 138 of file halls_of_stone.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), SetData(), and Update().
m_bIsBrannSpankin
bool instance_halls_of_stone::m_bIsBrannSpankin private
Definition at line 143 of file halls_of_stone.h.
Referenced by CheckAchievementCriteriaMeet(), and SetBrannSpankin().
m_brannSummonedGuid
ObjectGuid instance_halls_of_stone::m_brannSummonedGuid private
Definition at line 151 of file halls_of_stone.h.
Referenced by GetBrannSummonedGuid(), OnCreatureRespawn(), and OnPlayerEnter().
m_custodianStalkerGuid
ObjectGuid instance_halls_of_stone::m_custodianStalkerGuid private
Definition at line 149 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_lAbedneumGUIDs
GuidList instance_halls_of_stone::m_lAbedneumGUIDs private
Definition at line 154 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_lKaddrakGUIDs
GuidList instance_halls_of_stone::m_lKaddrakGUIDs private
Definition at line 153 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_lMarnakGUIDs
GuidList instance_halls_of_stone::m_lMarnakGUIDs private
Definition at line 155 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_lRuneDwarfGUIDs
GuidList instance_halls_of_stone::m_lRuneDwarfGUIDs private
Definition at line 158 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SetData().
m_lTribunalGUIDs
GuidList instance_halls_of_stone::m_lTribunalGUIDs private
Definition at line 156 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_lWorldtriggerGUIDs
GuidList instance_halls_of_stone::m_lWorldtriggerGUIDs private
Definition at line 157 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_protectorStalkerGuid
ObjectGuid instance_halls_of_stone::m_protectorStalkerGuid private
Definition at line 147 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_stormcallerStalkerGuid
ObjectGuid instance_halls_of_stone::m_stormcallerStalkerGuid private
Definition at line 148 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and SortFaces().
m_strInstData
std::string instance_halls_of_stone::m_strInstData private
Definition at line 140 of file halls_of_stone.h.
Referenced by Save(), and SetData().
m_tribunalCasterGuid
ObjectGuid instance_halls_of_stone::m_tribunalCasterGuid private
Definition at line 150 of file halls_of_stone.h.
Referenced by OnCreatureCreate(), and Update().
m_uiIronSludgeKilled
uint8 instance_halls_of_stone::m_uiIronSludgeKilled private
Definition at line 142 of file halls_of_stone.h.
Referenced by CheckAchievementCriteriaMeet(), OnCreatureDeath(), and SetData().
m_uiLightningChannelTimer
uint32 instance_halls_of_stone::m_uiLightningChannelTimer private
Definition at line 145 of file halls_of_stone.h.
Referenced by Update().
The documentation for this class was generated from the following files:
halls_of_stone.h
halls_of_stone.cpp