CMaNGOS_WoTLK: Field Class Reference
Field Class Reference
#include <Field.h>
Public Types
enum DataTypes {
DB_TYPE_UNKNOWN = 0x00 , DB_TYPE_STRING = 0x01 , DB_TYPE_INTEGER = 0x02 , DB_TYPE_FLOAT = 0x03 ,
DB_TYPE_BOOL = 0x04
}
Public Member Functions
Field ()
Field (const char *value, enum DataTypes type)
~Field ()
enum DataTypes GetType () const
bool IsNULL () const
const char * GetString () const
std::string GetCppString () const
float GetFloat () const
bool GetBool () const
int32 GetInt32 () const
uint8 GetUInt8 () const
uint16 GetUInt16 () const
int16 GetInt16 () const
uint32 GetUInt32 () const
uint64 GetUInt64 () const
time_t GetTime () const
void SetType (enum DataTypes type)
void SetValue (const char *value)
Private Member Functions
Field (Field const &)
Field & operator= (Field const &)
Private Attributes
const char * mValue
enum DataTypes mType
Detailed Description
Definition at line 24 of file Field.h.
Member Enumeration Documentation
DataTypes
enum Field::DataTypes
Enumerator
DB_TYPE_UNKNOWN
DB_TYPE_STRING
DB_TYPE_INTEGER
DB_TYPE_FLOAT
DB_TYPE_BOOL
Definition at line 28 of file Field.h.
Constructor & Destructor Documentation
Field() [1/3]
Field::Field () inline
Definition at line 37 of file Field.h.
Field() [2/3]
Field::Field (const char * value, enum DataTypes type) inline
Definition at line 38 of file Field.h.
~Field()
Field::~Field () inline
Definition at line 40 of file Field.h.
Field() [3/3]
Field::Field (Field const &) private
Member Function Documentation
GetBool()
bool Field::GetBool () const inline
Definition at line 54 of file Field.h.
References mValue.
Referenced by Player::_LoadBoundInstances(), Player::_LoadMails(), PlayerbotAI::BotDataRestore(), Player::DeleteFromDB(), ObjectMgr::LoadGroups(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadReputationOnKill(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellLearnSpells(), and ObjectMgr::ReturnOrDeleteOldMails().
GetCppString()
std::string Field::GetCppString () const inline
Definition at line 49 of file Field.h.
References mValue.
Referenced by MapPersistentStateManager::_DelHelper(), AuthSocket::_HandleLogonChallenge(), Player::_LoadDeclinedNames(), Player::_LoadEquipmentSets(), Player::_LoadMails(), Guild::AddMember(), AccountMgr::CheckPassword(), SpellMgr::CheckUsedSpells(), CreateDumpString(), Player::DeleteFromDB(), ChatHandler::getCommandTable(), ChatHandler::GetDeletedCharacterInfoList(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), GetTime(), HandleAnticheatFingerprintAHistoryCommand(), HandleAnticheatFingerprintHistoryCommand(), ChatHandler::HandleBanListHelper(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), WorldSession::HandleCharDeleteOpcode(), ChatHandler::HandleListItemCommand(), ChatHandler::HandlePInfoCommand(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleWhoisOpcode(), WorldState::Load(), WorldStateExpressionMgr::Load(), GMTicket::Load(), WorldSession::LoadAccountData(), LootStore::LoadAndCheckReferenceNames(), ArenaTeam::LoadArenaTeamFromDB(), ObjectMgr::LoadBroadcastText(), ObjectMgr::LoadBroadcastTextLocales(), CalendarMgr::LoadCalendarsFromDB(), ObjectMgr::LoadCreatureSpawnDataTemplates(), ObjectMgr::LoadCreatureSpellLists(), World::LoadDBVersion(), GameEventMgr::LoadFromDB(), PoolManager::LoadFromDB(), Player::LoadFromDB(), SocialMgr::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipText(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildFromDB(), ObjectMgr::LoadMangosStrings(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), ObjectMgr::LoadPageTextLocales(), Pet::LoadPetFromDB(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), ObjectMgr::LoadQuestgiverGreetingLocales(), Guild::LoadRanksFromDB(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewards(), SpellScriptMgr::LoadScripts(), World::LoadSpamRecords(), ObjectMgr::LoadSpawnGroups(), ScriptMgr::LoadStringIds(), ObjectMgr::LoadTrainerGreetingLocales(), MapManager::LoadTransports(), SystemMgr::LoadVersion(), ObjectMgr::LoadWorldStateNames(), ChatHandler::LookupPlayerSearchCommand(), Quest::Quest(), BattleGroundMgr::RewardArenaSeason(), WorldSession::SendNameQueryResponseFromDBCallBack(), WorldSession::SendPetitionQueryOpcode(), ChatHandler::ShowPlayerListHelper(), StoreGUID(), PlayerbotAI::TalentSpecDBContainsError(), and RealmList::UpdateRealms().
GetFloat()
float Field::GetFloat () const inline
Definition at line 53 of file Field.h.
References mValue.
Referenced by Player::_LoadHomeBind(), Player::BuildEnumData(), BattleGroundMgr::CreateInitialBattleGrounds(), Player::GetZoneIdFromDB(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), WaypointManager::Load(), GMTicket::Load(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadCreatureClassLvlStats(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatures(), PoolManager::LoadFromDB(), Player::LoadFromDB(), Corpse::LoadFromDB(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipText(), LFGMgr::LoadLFGDungeons(), LootStore::LoadLootTable(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ScriptMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadVehicleSeatParameters(), and Quest::Quest().
GetInt16()
int16 Field::GetInt16 () const inline
Definition at line 58 of file Field.h.
References mValue.
Referenced by Player::_LoadMails(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), ObjectMgr::LoadCreatures(), GameEventMgr::LoadFromDB(), ObjectMgr::LoadGameObjects(), and ObjectMgr::ReturnOrDeleteOldMails().
GetInt32()
int32 Field::GetInt32 () const inline
Definition at line 55 of file Field.h.
References mValue.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), Guild::AddMember(), SpellMgr::CheckUsedSpells(), UnitConditionMgr::Load(), CalendarMgr::LoadCalendarsFromDB(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureSpawnDataTemplates(), ObjectMgr::LoadCreatureSpellLists(), ScriptMgr::LoadDbScriptRandomTemplates(), ObjectMgr::LoadFishingBaseSkillLevel(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGossipMenuItems(), Item::LoadLootFromDB(), LootStore::LoadLootTable(), ObjectMgr::LoadMangosStrings(), Guild::LoadMembersFromDB(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadReputationOnKill(), ScriptMgr::LoadScripts(), LoadSkillDiscoveryTable(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellAreas(), ScriptMgr::LoadStringIds(), ObjectMgr::LoadWorldStateNames(), Quest::Quest(), and PlayerbotAI::TalentSpecDBContainsError().
GetString()
const char* Field::GetString () const inline
Definition at line 45 of file Field.h.
References mValue.
Referenced by AuthSocket::_HandleLogonChallenge(), Player::BuildEnumData(), PlayerbotAI::CombatOrderRestore(), Map::CreateInstanceData(), WorldSocket::HandleAuthSession(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleBanListIPCommand(), GMTicket::Load(), ObjectMgr::LoadAccessRequirements(), ScriptDevAIMgr::LoadAreaTriggerScripts(), BattleGroundMgr::LoadBattleEventIndexes(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadTrainerGreetings(), and WorldSession::SendStablePet().
GetTime()
time_t Field::GetTime () const
Definition at line 24 of file Field.cpp.
References GetCppString().
Referenced by GameEventMgr::LoadFromDB().
GetType()
enum DataTypes Field::GetType () const inline
Definition at line 40 of file Field.h.
GetUInt16()
uint16 Field::GetUInt16 () const inline
Definition at line 57 of file Field.h.
References mValue.
Referenced by Player::_LoadHomeBind(), Player::_LoadSkills(), Player::DeleteFromDB(), ChatHandler::getCommandTable(), PlayerbotAI::GetTalentSpec(), PlayerbotAI::GetTalentSpecs(), ChatHandler::HandleAddItemCommand(), WorldSocket::HandleAuthSession(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListObjectCommand(), GameEventMgr::Initialize(), ObjectMgr::LoadAccessRequirements(), Guild::LoadBankRightsFromDB(), ObjectMgr::LoadCreatures(), CreatureLinkingMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolManager::LoadFromDB(), Item::LoadFromDB(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), LootStore::LoadLootTable(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPlayerInfo(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTrainers(), ObjectMgr::LoadVendors(), Quest::Quest(), and PlayerbotAI::TalentSpecDBContainsError().
GetUInt32()
uint32 Field::GetUInt32 () const inline
Definition at line 59 of file Field.h.
References mValue.
Referenced by PlayerbotAI::_HandleCommandSurvey(), AuthSocket::_HandleLogonProof(), Player::_LoadActions(), Player::_LoadArenaTeamInfo(), Player::_LoadAuras(), Pet::_LoadAuras(), Player::_LoadBGData(), Player::_LoadBoundInstances(), Player::_LoadCreatedInstanceTimers(), Player::_LoadDailyQuestStatus(), Player::_LoadEquipmentSets(), Player::_LoadGlyphs(), Player::_LoadHomeBind(), Player::_LoadInventory(), Player::_LoadItemLoot(), Player::_LoadMailedItems(), Player::_LoadMails(), Player::_LoadMonthlyQuestStatus(), Player::_LoadQuestStatus(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Player::_LoadSpells(), Player::_LoadTalents(), Player::_LoadWeeklyQuestStatus(), World::_UpdateRealmCharCount(), Guild::AddMember(), World::BanAccount(), Player::BuildEnumData(), CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), BattleGroundMgr::CreateInitialBattleGrounds(), Player::Customize(), AccountMgr::DeleteAccount(), Player::DeleteFromDB(), Pet::DeleteFromDB(), AuctionHouseBot::FillUintVectorFromQuery(), AccountMgr::GetCharactersCount(), ChatHandler::GetDeletedCharacterInfoList(), Player::GetGuildIdFromDB(), Player::GetLevelFromDB(), Player::GetRankFromDB(), PlayerbotAI::GetTalentSpecsAmount(), Player::GetZoneIdFromDB(), HandleAnticheatFingerprintAHistoryCommand(), HandleAnticheatFingerprintHistoryCommand(), WorldSocket::HandleAuthSession(), ChatHandler::HandleBanListHelper(), WorldSession::HandleChangePlayerNameOpcodeCallBack(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharDeleteOpcode(), ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleGoCreatureCommand(), ChatHandler::HandleGoObjectCommand(), ChatHandler::HandleLinkAddCommand(), ChatHandler::HandleLinkCheckCommand(), ChatHandler::HandleListCreatureCommand(), ChatHandler::HandleListItemCommand(), ChatHandler::HandleListObjectCommand(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandlePetitionRenameOpcode(), WorldSession::HandlePetitionShowSignOpcode(), WorldSession::HandlePetitionSignOpcode(), ChatHandler::HandlePInfoCommand(), WorldSession::HandleSendMail(), WorldSession::HandleStablePet(), WorldSession::HandleStableSwapPet(), WorldSession::HandleTurnInPetitionOpcode(), WorldSession::HandleUnstablePet(), ChatHandler::HandleWpAddCommand(), AuctionHouseBot::Initialize(), CreatureLinkingMgr::IsLinkingEntryValid(), PlayerbotAI::ListAuctions(), CombatConditionMgr::Load(), UnitConditionMgr::Load(), WaypointManager::Load(), WorldState::Load(), WorldStateExpressionMgr::Load(), GMTicket::Load(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), ObjectMgr::LoadAccessRequirements(), WorldSession::LoadAccountData(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), LootStore::LoadAndCheckReferenceNames(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ArenaTeam::LoadArenaTeamFromDB(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), Guild::LoadBankRightsFromDB(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastText(), ObjectMgr::LoadBroadcastTextLocales(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnDataTemplates(), ObjectMgr::LoadCreatureSpawnEntry(), ObjectMgr::LoadCreatureSpellLists(), ObjectMgr::LoadCreatureTemplateSpells(), ScriptMgr::LoadDbScriptRandomTemplates(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), CreatureLinkingMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolManager::LoadFromDB(), Player::LoadFromDB(), AchievementMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), SocialMgr::LoadFromDB(), Item::LoadFromDB(), Corpse::LoadFromDB(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipText(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), Group::LoadGroupFromDB(), ObjectMgr::LoadGroups(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), Guild::LoadGuildFromDB(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LFGMgr::LoadLFGDungeons(), Item::LoadLootFromDB(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMangosStrings(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), Pet::LoadPetFromDB(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), Player::LoadPositionFromDB(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), LoadRandomEnchantmentsTable(), Guild::LoadRanksFromDB(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), DungeonResetScheduler::LoadResetTimes(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), LFGMgr::LoadRewards(), SpellScriptMgr::LoadScripts(), ScriptMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), ObjectMgr::LoadTrainers(), MapManager::LoadTransports(), ObjectMgr::LoadVehicleSeatParameters(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherZoneChances(), ChatHandler::LookupPlayerSearchCommand(), Player::OnGossipSelect(), ObjectMgr::PackGroupIds(), Quest::Quest(), PlayerbotAI::RemoveAuction(), Pet::resetTalentsForAllPetsOf(), ObjectMgr::ReturnOrDeleteOldMails(), WorldSession::SendPetitionQueryOpcode(), PlayerbotAI::SetQuestNeedItems(), ChatHandler::ShowAccountListHelper(), ChatHandler::ShowPlayerListHelper(), StoreGUID(), PlayerbotAI::TalentSpecDBContainsError(), Pet::TryLoadFromDB(), and RealmList::UpdateRealms().
GetUInt64()
uint64 Field::GetUInt64 () const inline
Definition at line 60 of file Field.h.
References mValue, and UI64FMTD.
Referenced by Player::_LoadEquipmentSets(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), SpellMgr::CheckUsedSpells(), BattleGround::EndBattleGround(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleBanListIPCommand(), CalendarMgr::LoadCalendarsFromDB(), MapPersistentStateManager::LoadCreatureRespawnTimes(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildEventLogFromDB(), Guild::LoadGuildFromDB(), Guild::LoadMembersFromDB(), Pet::LoadPetFromDB(), and DungeonResetScheduler::LoadResetTimes().
GetUInt8()
uint8 Field::GetUInt8 () const inline
Definition at line 56 of file Field.h.
References mValue.
Referenced by AuthSocket::_HandleLogonChallenge(), Player::_LoadActions(), Player::_LoadBoundInstances(), Player::_LoadGlyphs(), Player::_LoadInventory(), Player::_LoadMails(), Player::_LoadQuestStatus(), Guild::AddMember(), PlayerbotAI::BotDataRestore(), Player::BuildEnumData(), PlayerbotAI::CombatOrderRestore(), WorldSocket::HandleAuthSession(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandlePetitionSignOpcode(), GMTicket::Load(), ObjectMgr::LoadAccessRequirements(), ObjectMgr::LoadAreaTriggerTeleports(), Guild::LoadBankRightsFromDB(), BattleGroundMgr::LoadBattleEventIndexes(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), Corpse::LoadFromDB(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGossipMenuItems(), Group::LoadGroupFromDB(), ObjectMgr::LoadGroups(), Guild::LoadGuildBankEventLogFromDB(), Guild::LoadGuildBankFromDB(), Guild::LoadGuildEventLogFromDB(), ObjectMgr::LoadInstanceEncounters(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ArenaTeam::LoadMembersFromDB(), Guild::LoadMembersFromDB(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPlayerInfo(), AuthSocket::LoadRealmlist(), LFGMgr::LoadRewards(), LoadSkillExtraItemTable(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), ObjectMgr::LoadVehicleSeatParameters(), ObjectMgr::ReturnOrDeleteOldMails(), WorldSession::SendNameQueryResponseFromDBCallBack(), ChatHandler::ShowPlayerListHelper(), and RealmList::UpdateRealms().
IsNULL()
bool Field::IsNULL () const inline
Definition at line 43 of file Field.h.
References mValue.
Referenced by ChatHandler::HandleBanInfoHelper().
operator=()
Field& Field::operator= (Field const &) private
SetType()
void Field::SetType (enum DataTypes type) inline
Definition at line 70 of file Field.h.
References mType.
SetValue()
void Field::SetValue (const char * value) inline
Definition at line 73 of file Field.h.
References mValue.
Field Documentation
mType
enum DataTypes Field::mType private
Definition at line 79 of file Field.h.
Referenced by SetType().
mValue
const char* Field::mValue private
Definition at line 79 of file Field.h.
Referenced by GetBool(), GetCppString(), GetFloat(), GetInt16(), GetInt32(), GetString(), GetUInt16(), GetUInt32(), GetUInt64(), GetUInt8(), IsNULL(), and SetValue().
The documentation for this class was generated from the following files:
Field.h
Field.cpp