CMaNGOS_WoTLK: PlayerDumpReader Class Reference
PlayerDumpReader Class Reference
#include <PlayerDump.h>
Public Member Functions
PlayerDumpReader ()
Static Public Member Functions
static DumpReturn LoadDump (const std::string &file, uint32 account, std::string name, uint32 guid)
Additional Inherited Members
Protected Member Functions inherited from PlayerDump
PlayerDump ()
Detailed Description
Definition at line 92 of file PlayerDump.h.
Constructor & Destructor Documentation
PlayerDumpReader()
PlayerDumpReader::PlayerDumpReader () inline
Definition at line 95 of file PlayerDump.h.
Member Function Documentation
LoadDump()
DumpReturn PlayerDumpReader::LoadDump (const std::string & file, uint32 account, std::string name, uint32 guid) static
Definition at line 407 of file PlayerDump.cpp.
References Database::BeginTransaction(), changeGuid(), changenth(), CHAR_NAME_SUCCESS, CharacterDatabase, ObjectMgr::CheckPlayerName(), Database::CommitTransaction(), DTT_CHAR_NAME_TABLE, DTT_CHAR_TABLE, DTT_CHARACTER, DTT_EQSET_TABLE, DTT_INVENTORY, DTT_ITEM, DTT_ITEM_GIFT, DTT_ITEM_LOOT, DTT_MAIL, DTT_MAIL_ITEM, DTT_PET, DTT_PET_DECL, DTT_PET_TABLE, DUMP_FILE_BROKEN, DUMP_FILE_OPEN_ERROR, DUMP_SUCCESS, DUMP_TOO_MANY_CHARS, dumpTables, Database::escape_string(), Database::Execute(), getnth(), gettablename(), DumpTable::isValid(), DumpTable::name, normalizePlayerName(), Database::PQuery(), ROLLBACK, sAccountMgr, sLog, sObjectMgr, and DumpTable::type.
Referenced by ChatHandler::HandlePDumpLoadCommand().
The documentation for this class was generated from the following files:
PlayerDump.h
PlayerDump.cpp