CMaNGOS_WoTLK: instance_stratholme Class Reference
instance_stratholme Class Reference
#include <stratholme.h>
Public Member Functions
instance_stratholme (Map *map)
~instance_stratholme ()
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
const char * Save () const override
void Load (const char *chrIn) override
bool CheckConditionCriteriaMeet (Player const *player, uint32 instanceConditionId, WorldObject const *conditionSource, uint32 conditionSourceType) const override
void OnCreatureEnterCombat (Creature *creature) override
void OnCreatureEvade (Creature *creature)
void OnCreatureDeath (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
bool StartSlaughterSquare ()
void DoSortZiggurats ()
void DoOpenSlaughterhouseDoor (bool open)
void ThazudinAcolyteJustDied (Creature *creature)
void DoSpawnScarletGuards (uint8 step, Player *summoner)
void DoSpawnScourgeInvaders (uint8 step, Player *summoner)
void DoMoveBackDefenders (uint8 step, Creature *creature)
void DoScarletBastionDefense (uint8 step, Creature *creature)
void DoGateTrap (uint8 gate)
void DoSpawnPlaguedCritters (uint8 gate, Player *player)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_gateTrapTimers [2][3]
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_baronRunTimer
uint32 m_barthilasRunTimer
uint32 m_mindlessSummonTimer
uint32 m_slaughterSquareTimer
uint32 m_slaughterDoorTimer
uint32 m_blackGuardsTimer
uint32 m_auriusSummonTimer
bool m_isSlaughterDoorOpen
uint32 m_yellCounter
uint32 m_mindlessCount
uint8 m_postboxesUsed
uint8 m_silverHandKilled
bool m_jarienKilled
bool m_sothosKilled
ZigguratStore m_zigguratStorage [MAX_ZIGGURATS]
GuidList m_crimsonDefendersLowGuids [MAX_DEFENSE_POINTS]
GuidList m_crystalGUIDs
GuidSet m_abominationGUIDs
GuidList m_acolyteGUIDs
GuidList m_undeadGUIDs
GuidList m_guardGUIDs
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 230 of file stratholme.h.
Constructor & Destructor Documentation
instance_stratholme()
instance_stratholme::instance_stratholme (Map * map)
Definition at line 27 of file stratholme.cpp.
References Initialize().
~instance_stratholme()
instance_stratholme::~instance_stratholme () inline
Definition at line 234 of file stratholme.h.
Member Function Documentation
CheckConditionCriteriaMeet()
bool instance_stratholme::CheckConditionCriteriaMeet (Player const * player, uint32 instanceConditionId, WorldObject const * conditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 1267 of file stratholme.cpp.
References DONE, GetData(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_NORMAL_MODE, script_error_log(), and TYPE_AURIUS.
DoGateTrap()
void instance_stratholme::DoGateTrap (uint8 gate) protected
Definition at line 977 of file stratholme.cpp.
References debug_log(), ScriptedInstance::DoUseDoorOrButton(), gates, IN_MILLISECONDS, m_gateTrapTimers, and MINUTE.
Referenced by Update().
DoMoveBackDefenders()
void instance_stratholme::DoMoveBackDefenders (uint8 step, Creature * creature) protected
Definition at line 903 of file stratholme.cpp.
References BARRICADE, DoScriptText(), FIRST_BARRICADES, Map::GetCreature(), Unit::GetMotionMaster(), InstanceData::instance, Unit::IsAlive(), Unit::IsInCombat(), m_crimsonDefendersLowGuids, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), ScarletEventYells, scarletLastStand, Creature::SetWalk(), and STAIRS.
Referenced by DoScarletBastionDefense().
DoOpenSlaughterhouseDoor()
void instance_stratholme::DoOpenSlaughterhouseDoor (bool open) protected
Definition at line 75 of file stratholme.cpp.
References ScriptedInstance::DoUseDoorOrButton(), GO_ZIGGURAT_DOOR_4, and m_isSlaughterDoorOpen.
Referenced by OnCreatureEvade(), SetData(), and Update().
DoScarletBastionDefense()
void instance_stratholme::DoScarletBastionDefense (uint8 step, Creature * creature) protected
Definition at line 944 of file stratholme.cpp.
References BARRICADE, CRIMSON_THRONE, DoMoveBackDefenders(), DoScriptText(), DoSpawnScarletGuards(), DoSpawnScourgeInvaders(), ENTRANCE, ScriptedInstance::GetPlayerInMap(), HALL_OF_LIGHTS, INNER_BASTION_1, INNER_BASTION_2, NPC_TIMMY_THE_CRUEL, ScarletEventYells, scourgeInvaders, STAIRS, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TIMMY.
Referenced by OnCreatureDeath().
DoSortZiggurats()
void instance_stratholme::DoSortZiggurats () protected
Definition at line 573 of file stratholme.cpp.
References Map::GetCreature(), Map::GetGameObject(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, WorldObject::IsWithinDistInMap(), m_acolyteGUIDs, m_crystalGUIDs, ScriptedInstance::m_npcEntryGuidStore, m_zigguratStorage, NPC_THUZADIN_ACOLYTE, and sortByHeight().
Referenced by SetData().
DoSpawnPlaguedCritters()
void instance_stratholme::DoSpawnPlaguedCritters (uint8 gate, Player * player) protected
Definition at line 996 of file stratholme.cpp.
References gateTrap, WorldObject::GetRandomPoint(), plaguedCritters, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and urand().
Referenced by Update().
DoSpawnScarletGuards()
void instance_stratholme::DoSpawnScarletGuards (uint8 step, Player * summoner) protected
Definition at line 820 of file stratholme.cpp.
References HALL_OF_LIGHTS, INNER_BASTION_2, EventLocation::m_fO, EventLocation::m_fX, EventLocation::m_fY, EventLocation::m_fZ, NPC_CRIMSON_GALLANT, NPC_CRIMSON_MONK, NPC_CRIMSON_SORCERER, scarletGuards, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by DoScarletBastionDefense().
DoSpawnScourgeInvaders()
void instance_stratholme::DoSpawnScourgeInvaders (uint8 step, Player * summoner) protected
Definition at line 855 of file stratholme.cpp.
References CRIMSON_THRONE, ENTRANCE, GetRandomGenerator(), INNER_BASTION_1, EventLocation::m_fO, EventLocation::m_fX, EventLocation::m_fY, EventLocation::m_fZ, NPC_SKELETAL_BERSERKER, NPC_SKELETAL_GUARDIAN, scourgeInvaders, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and urand().
Referenced by DoScarletBastionDefense().
GetData()
uint32 instance_stratholme::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 548 of file stratholme.cpp.
References m_auiEncounter, TYPE_AURIUS, TYPE_BARON, TYPE_BARON_RUN, TYPE_BARONESS, TYPE_BARTHILAS_RUN, TYPE_NERUB, TYPE_PALLID, TYPE_POSTMASTER, TYPE_RAMSTEIN, and TYPE_TRUE_MASTERS.
Referenced by CheckConditionCriteriaMeet(), boss_silver_hand_bossesAI::JustDied(), OnCreatureRespawn(), OnPlayerEnter(), SetData(), and Update().
Initialize()
void instance_stratholme::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 46 of file stratholme.cpp.
References m_auiEncounter, and m_gateTrapTimers.
Referenced by instance_stratholme().
Load()
void instance_stratholme::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 517 of file stratholme.cpp.
References DONE, IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, SPECIAL, TYPE_BARONESS, TYPE_NERUB, and TYPE_PALLID.
OnCreatureCreate()
void instance_stratholme::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 100 of file stratholme.cpp.
References BARRICADE, defensePoints, DONE, FIRST_BARRICADES, Object::GetEntry(), Object::GetObjectGuid(), WorldObject::IsWithinDist2d(), m_abominationGUIDs, m_acolyteGUIDs, m_auiEncounter, m_crimsonDefendersLowGuids, m_crystalGUIDs, EventLocation::m_fX, EventLocation::m_fY, ScriptedInstance::m_npcEntryGuidStore, NPC_ABOM_BILE, NPC_ABOM_VENOM, NPC_AURIUS, NPC_BARON, NPC_BARTHILAS, NPC_CRIMSON_BATTLE_MAGE, NPC_CRIMSON_CONJURER, NPC_CRIMSON_GALLANT, NPC_CRIMSON_GUARDSMAN, NPC_CRIMSON_INITIATE, NPC_CRYSTAL, NPC_PALADIN_QUEST_CREDIT, NPC_THUZADIN_ACOLYTE, NPC_YSIDA, Object::RemoveFlag(), Unit::SetStandState(), TIMMY, TYPE_AURIUS, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and UNIT_STAND_STATE_KNEEL.
OnCreatureDeath()
void instance_stratholme::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 704 of file stratholme.cpp.
References BARRICADE, CRIMSON_THRONE, DONE, DoScarletBastionDefense(), DoScriptText(), FIRST_BARRICADES, Object::GetEntry(), Object::GetObjectGuid(), Unit::GetSpawner(), IN_MILLISECONDS, m_blackGuardsTimer, m_crimsonDefendersLowGuids, m_guardGUIDs, m_jarienKilled, m_sothosKilled, m_undeadGUIDs, NPC_ABOM_BILE, NPC_ABOM_VENOM, NPC_AURIUS, NPC_BALNAZZAR, NPC_BARON, NPC_BARONESS_ANASTARI, NPC_BLACK_GUARD, NPC_CRIMSON_BATTLE_MAGE, NPC_CRIMSON_CONJURER, NPC_CRIMSON_GALLANT, NPC_CRIMSON_GUARDSMAN, NPC_CRIMSON_INITIATE, NPC_JARIEN, NPC_MALEKI_THE_PALLID, NPC_MINDLESS_UNDEAD, NPC_NERUBENKAN, NPC_RAMSTEIN, NPC_SOTHOS, NPC_THUZADIN_ACOLYTE, SAY_AURIUS_DEATH, SetData(), SPECIAL, SPELL_SUMMON_WINNER_BOX, ThazudinAcolyteJustDied(), TRIGGERED_OLD_TRIGGERED, TYPE_BARON, TYPE_BARONESS, TYPE_BLACK_GUARDS, TYPE_NERUB, TYPE_PALLID, and TYPE_RAMSTEIN.
OnCreatureEnterCombat()
void instance_stratholme::OnCreatureEnterCombat (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 653 of file stratholme.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_ABOM_BILE, NPC_ABOM_VENOM, NPC_BARON, NPC_BARONESS_ANASTARI, NPC_BLACK_GUARD, NPC_MALEKI_THE_PALLID, NPC_MINDLESS_UNDEAD, NPC_NERUBENKAN, NPC_RAMSTEIN, SetData(), SPECIAL, TYPE_BARON, TYPE_BARONESS, TYPE_BLACK_GUARDS, TYPE_NERUB, TYPE_PALLID, and TYPE_RAMSTEIN.
OnCreatureEvade()
void instance_stratholme::OnCreatureEvade (Creature * creature) virtual
Reimplemented from InstanceData.
Definition at line 677 of file stratholme.cpp.
References DoOpenSlaughterhouseDoor(), FAIL, Object::GetEntry(), NPC_ABOM_BILE, NPC_ABOM_VENOM, NPC_BARON, NPC_BARONESS_ANASTARI, NPC_BLACK_GUARD, NPC_MALEKI_THE_PALLID, NPC_MINDLESS_UNDEAD, NPC_NERUBENKAN, NPC_RAMSTEIN, SetData(), TYPE_BARON, TYPE_BARONESS, TYPE_BLACK_GUARDS, TYPE_NERUB, TYPE_PALLID, and TYPE_RAMSTEIN.
OnCreatureRespawn()
void instance_stratholme::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 774 of file stratholme.cpp.
References GetData(), Object::GetEntry(), m_jarienKilled, m_sothosKilled, Unit::NearTeleportTo(), NOT_STARTED, NPC_BARTHILAS, NPC_JARIEN, NPC_SOTHOS, stratholmeLocation, and TYPE_BARTHILAS_RUN.
OnObjectCreate()
void instance_stratholme::OnObjectCreate (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 151 of file stratholme.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_FLAG_LOCKED, GO_GAUNTLET_GATE1, GO_PORT_ELDERS, GO_PORT_GAUNTLET, GO_PORT_SLAUGHTER, GO_PORT_SLAUGHTER_GATE, GO_PORT_TRAP_GATE_1, GO_PORT_TRAP_GATE_2, GO_PORT_TRAP_GATE_3, GO_PORT_TRAP_GATE_4, GO_SERVICE_ENTRANCE, GO_STATE_ACTIVE, GO_YSIDA_CAGE, GO_ZIGGURAT_DOOR_1, GO_ZIGGURAT_DOOR_2, GO_ZIGGURAT_DOOR_3, GO_ZIGGURAT_DOOR_4, GO_ZIGGURAT_DOOR_5, m_auiEncounter, ZigguratStore::m_doorGuid, ScriptedInstance::m_goEntryGuidStore, m_zigguratStorage, Object::SetFlag(), GameObject::SetGoState(), SPECIAL, TYPE_BARONESS, TYPE_BLACK_GUARDS, TYPE_NERUB, TYPE_PALLID, and TYPE_RAMSTEIN.
OnPlayerEnter()
void instance_stratholme::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 57 of file stratholme.cpp.
References Unit::CastSpell(), DONE, FAIL, GetData(), EventLocation::m_fO, EventLocation::m_fX, EventLocation::m_fY, EventLocation::m_fZ, NPC_YSIDA, stratholmeLocation, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, and TYPE_BARON_RUN.
Save()
const char* instance_stratholme::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 246 of file stratholme.h.
References m_strInstData.
SetData()
void instance_stratholme::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 210 of file stratholme.cpp.
References debug_log(), DONE, DoOpenSlaughterhouseDoor(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), DoSortZiggurats(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::DoUseOpenableObject(), FAIL, Map::GetCreature(), MotionMaster::GetCurrentMovementGeneratorType(), GetData(), Unit::GetMotionMaster(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_PORT_GAUNTLET, GO_PORT_SLAUGHTER_GATE, GO_YSIDA_CAGE, GO_ZIGGURAT_DOOR_5, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), Unit::IsInCombat(), m_abominationGUIDs, m_auiEncounter, m_auriusSummonTimer, m_baronRunTimer, m_barthilasRunTimer, EventLocation::m_fO, EventLocation::m_fX, EventLocation::m_fY, EventLocation::m_fZ, m_guardGUIDs, m_mindlessCount, m_mindlessSummonTimer, m_postboxesUsed, m_silverHandKilled, m_slaughterDoorTimer, m_slaughterSquareTimer, m_strInstData, m_undeadGUIDs, m_zigguratStorage, MAX_SILVERHAND, MINUTE, MotionMaster::MovementExpired(), MotionMaster::MovePoint(), NPC_AURIUS, NPC_BARON, NPC_BARTHILAS, NPC_BLACK_GUARD, NPC_RAMSTEIN, NPC_YSIDA, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, POINT_MOTION_TYPE, QUEST_DEAD_MAN_PLEA, QUEST_STATUS_INCOMPLETE, InstanceData::SaveToDB(), SAY_ANNOUNCE_RAMSTEIN, SAY_ANNOUNCE_RUN_START, SAY_AURIUS_DEATH, SAY_EPILOGUE, SAY_UNDEAD_DEFEAT, SAY_WARN_BARON, Creature::SetWalk(), SPECIAL, SPELL_BARON_ULTIMATUM, SPELL_YSIDA_FREED, StartSlaughterSquare(), stratholmeLocation, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_AURIUS, TYPE_BARON, TYPE_BARON_RUN, TYPE_BARONESS, TYPE_BARTHILAS_RUN, TYPE_BLACK_GUARDS, TYPE_NERUB, TYPE_PALLID, TYPE_POSTMASTER, TYPE_RAMSTEIN, TYPE_TRUE_MASTERS, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and UNIT_STAND_STATE_DEAD.
Referenced by boss_silver_hand_bossesAI::JustDied(), OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), ThazudinAcolyteJustDied(), and Update().
StartSlaughterSquare()
bool instance_stratholme::StartSlaughterSquare () protected
Definition at line 84 of file stratholme.cpp.
References debug_log(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), ScriptedInstance::DoUseDoorOrButton(), GO_PORT_GAUNTLET, GO_PORT_SLAUGHTER, m_auiEncounter, NPC_BARON, SAY_ANNOUNCE_RIVENDARE, SPECIAL, TYPE_BARONESS, TYPE_NERUB, and TYPE_PALLID.
Referenced by SetData().
ThazudinAcolyteJustDied()
void instance_stratholme::ThazudinAcolyteJustDied (Creature * creature) protected
Definition at line 791 of file stratholme.cpp.
References ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), Map::GetCreature(), Object::GetObjectGuid(), InstanceData::instance, ZigguratStore::m_crystalGuid, ZigguratStore::m_zigguratAcolyteGuid, m_zigguratStorage, MAX_ZIGGURATS, NPC_THUZADIN_ACOLYTE, SAY_ANNOUNCE_ZIGGURAT_1, SAY_ANNOUNCE_ZIGGURAT_2, SAY_ANNOUNCE_ZIGGURAT_3, SetData(), SPECIAL, SPELL_SUICIDE, TRIGGERED_OLD_TRIGGERED, TYPE_BARONESS, TYPE_NERUB, and TYPE_PALLID.
Referenced by OnCreatureDeath().
Update()
void instance_stratholme::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 1011 of file stratholme.cpp.
References Creature::AI(), UnitAI::AttackStart(), MotionMaster::Clear(), debug_log(), DoGateTrap(), DONE, DoOpenSlaughterhouseDoor(), ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), DoSpawnPlaguedCritters(), ScriptedInstance::DoUseDoorOrButton(), FACTION_VICTIM, FAIL, gates, gateTrap, Map::GetCreature(), MotionMaster::GetCurrentMovementGeneratorType(), GetData(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::GetPet(), ScriptedInstance::GetPlayerInMap(), Map::GetPlayers(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_PORT_SLAUGHTER, GO_YSIDA_CAGE, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), Unit::IsInCombat(), WorldObject::IsWithinDist2d(), m_abominationGUIDs, m_auriusSummonTimer, m_baronRunTimer, m_barthilasRunTimer, m_blackGuardsTimer, EventLocation::m_fO, EventLocation::m_fX, EventLocation::m_fY, EventLocation::m_fZ, m_gateTrapTimers, m_guardGUIDs, m_mindlessCount, m_mindlessSummonTimer, m_slaughterDoorTimer, m_slaughterSquareTimer, m_undeadGUIDs, m_yellCounter, MINUTE, MotionMaster::MoveIdle(), MotionMaster::MovePoint(), Unit::NearTeleportTo(), NPC_AURIUS, NPC_BARON, NPC_BARTHILAS, NPC_MINDLESS_UNDEAD, NPC_YSIDA, POINT_MOTION_TYPE, Object::RemoveFlag(), SAY_ANNOUNCE_RUN_10_MIN, SAY_ANNOUNCE_RUN_5_MIN, SAY_ANNOUNCE_RUN_FAIL, SAY_AURIUS_AGGRO, SAY_YSIDA_RUN_5_MIN, SAY_YSIDA_RUN_FAIL, SetData(), Creature::SetFactionTemporary(), Creature::SetRespawnCoord(), Unit::SetStandState(), SPELL_BARON_SOUL_DRAIN, stratholmeLocation, WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, TYPE_BARON, TYPE_BARON_RUN, TYPE_BARTHILAS_RUN, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, UNIT_STAND_STATE_STAND, and urand().
Field Documentation
m_abominationGUIDs
GuidSet instance_stratholme::m_abominationGUIDs protected
Definition at line 297 of file stratholme.h.
Referenced by OnCreatureCreate(), SetData(), and Update().
m_acolyteGUIDs
GuidList instance_stratholme::m_acolyteGUIDs protected
Definition at line 298 of file stratholme.h.
Referenced by DoSortZiggurats(), and OnCreatureCreate().
m_auiEncounter
uint32 instance_stratholme::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 273 of file stratholme.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), SetData(), and StartSlaughterSquare().
m_auriusSummonTimer
uint32 instance_stratholme::m_auriusSummonTimer protected
Definition at line 282 of file stratholme.h.
Referenced by SetData(), and Update().
m_baronRunTimer
uint32 instance_stratholme::m_baronRunTimer protected
Definition at line 276 of file stratholme.h.
Referenced by SetData(), and Update().
m_barthilasRunTimer
uint32 instance_stratholme::m_barthilasRunTimer protected
Definition at line 277 of file stratholme.h.
Referenced by SetData(), and Update().
m_blackGuardsTimer
uint32 instance_stratholme::m_blackGuardsTimer protected
Definition at line 281 of file stratholme.h.
Referenced by OnCreatureDeath(), and Update().
m_crimsonDefendersLowGuids
GuidList instance_stratholme::m_crimsonDefendersLowGuids[MAX_DEFENSE_POINTS] protected
Definition at line 295 of file stratholme.h.
Referenced by DoMoveBackDefenders(), OnCreatureCreate(), and OnCreatureDeath().
m_crystalGUIDs
GuidList instance_stratholme::m_crystalGUIDs protected
Definition at line 296 of file stratholme.h.
Referenced by DoSortZiggurats(), and OnCreatureCreate().
m_gateTrapTimers
uint32 instance_stratholme::m_gateTrapTimers[2][3] protected
Definition at line 271 of file stratholme.h.
Referenced by DoGateTrap(), Initialize(), and Update().
m_guardGUIDs
GuidList instance_stratholme::m_guardGUIDs protected
Definition at line 300 of file stratholme.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_isSlaughterDoorOpen
bool instance_stratholme::m_isSlaughterDoorOpen protected
Definition at line 283 of file stratholme.h.
Referenced by DoOpenSlaughterhouseDoor().
m_jarienKilled
bool instance_stratholme::m_jarienKilled protected
Definition at line 290 of file stratholme.h.
Referenced by OnCreatureDeath(), and OnCreatureRespawn().
m_mindlessCount
uint32 instance_stratholme::m_mindlessCount protected
Definition at line 286 of file stratholme.h.
Referenced by SetData(), and Update().
m_mindlessSummonTimer
uint32 instance_stratholme::m_mindlessSummonTimer protected
Definition at line 278 of file stratholme.h.
Referenced by SetData(), and Update().
m_postboxesUsed
uint8 instance_stratholme::m_postboxesUsed protected
Definition at line 287 of file stratholme.h.
Referenced by SetData().
m_silverHandKilled
uint8 instance_stratholme::m_silverHandKilled protected
Definition at line 288 of file stratholme.h.
Referenced by SetData().
m_slaughterDoorTimer
uint32 instance_stratholme::m_slaughterDoorTimer protected
Definition at line 280 of file stratholme.h.
Referenced by SetData(), and Update().
m_slaughterSquareTimer
uint32 instance_stratholme::m_slaughterSquareTimer protected
Definition at line 279 of file stratholme.h.
Referenced by SetData(), and Update().
m_sothosKilled
bool instance_stratholme::m_sothosKilled protected
Definition at line 291 of file stratholme.h.
Referenced by OnCreatureDeath(), and OnCreatureRespawn().
m_strInstData
std::string instance_stratholme::m_strInstData protected
Definition at line 274 of file stratholme.h.
Referenced by Save(), and SetData().
m_undeadGUIDs
GuidList instance_stratholme::m_undeadGUIDs protected
Definition at line 299 of file stratholme.h.
Referenced by OnCreatureDeath(), SetData(), and Update().
m_yellCounter
uint32 instance_stratholme::m_yellCounter protected
Definition at line 285 of file stratholme.h.
Referenced by Update().
m_zigguratStorage
ZigguratStore instance_stratholme::m_zigguratStorage[MAX_ZIGGURATS] protected
Definition at line 293 of file stratholme.h.
Referenced by DoSortZiggurats(), OnObjectCreate(), SetData(), and ThazudinAcolyteJustDied().
The documentation for this class was generated from the following files:
stratholme.h
stratholme.cpp