CMaNGOS_WoTLK: NamreebAnticheat::AnticheatLib Class Reference
NamreebAnticheat::AnticheatLib Class Reference
#include <libanticheat.hpp>
Data Structures
struct ExtrapDebugPoint
Public Member Functions
virtual void Reload ()
virtual void Initialize ()
virtual std::unique_ptr< SessionAnticheatInterface > NewSession (WorldSession *, const BigNumber &K)
virtual bool ValidateGuildName (const std::string &name) const
virtual std::string NormalizeString (const std::string &string, uint32 mask)
void EnableExtrapolationDebug (uint32 seconds)
void OfferExtrapolationData (const MovementInfo &start, float speed1, float speed2, const MovementInfo &theirEnd, const Position &extrapEnd, float errorDistance)
Private Attributes
std::atomic_bool _extrapDebugActive
uint32 _extrapDebugTimer
std::mutex _extrapMutex
nam::priority< ExtrapDebugPoint, float, 15 > _extrapPoints
Detailed Description
Definition at line 205 of file libanticheat.hpp.
Member Function Documentation
EnableExtrapolationDebug()
void NamreebAnticheat::AnticheatLib::EnableExtrapolationDebug (uint32 seconds)
Definition at line 260 of file libanticheat.cpp.
References _extrapDebugActive, _extrapDebugTimer, WorldTimer::getMSTime(), and IN_MILLISECONDS.
Initialize()
void NamreebAnticheat::AnticheatLib::Initialize () virtual
Implements AnticheatLibInterface.
Definition at line 232 of file libanticheat.cpp.
References Warden::LoadScriptedScans(), Reload(), and sLog.
NewSession()
std::unique_ptr< SessionAnticheatInterface > NamreebAnticheat::AnticheatLib::NewSession (WorldSession * session, const BigNumber & K) virtual
Implements AnticheatLibInterface.
Definition at line 241 of file libanticheat.cpp.
References sAnticheatConfig.
NormalizeString()
std::string NamreebAnticheat::AnticheatLib::NormalizeString (const std::string & string, uint32 mask) virtual
Implements AnticheatLibInterface.
Definition at line 255 of file libanticheat.cpp.
References sAntispamMgr.
OfferExtrapolationData()
void NamreebAnticheat::AnticheatLib::OfferExtrapolationData (const MovementInfo & start, float speed1, float speed2, const MovementInfo & theirEnd, const Position & extrapEnd, float errorDistance)
Definition at line 266 of file libanticheat.cpp.
References _extrapDebugActive, _extrapDebugTimer, _extrapMutex, _extrapPoints, WorldTimer::getMSTime(), and sLog.
Reload()
void NamreebAnticheat::AnticheatLib::Reload () virtual
Implements AnticheatLibInterface.
Definition at line 216 of file libanticheat.cpp.
References _LIB_ANTICHEAT_CONFIG, sAnticheatConfig, sAntispamMgr, sLog, and sWardenScanMgr.
Referenced by Initialize().
ValidateGuildName()
bool NamreebAnticheat::AnticheatLib::ValidateGuildName (const std::string & name) const virtual
Implements AnticheatLibInterface.
Definition at line 249 of file libanticheat.cpp.
References sAntispamMgr.
Field Documentation
_extrapDebugActive
std::atomic_bool NamreebAnticheat::AnticheatLib::_extrapDebugActive private
Definition at line 208 of file libanticheat.hpp.
Referenced by EnableExtrapolationDebug(), and OfferExtrapolationData().
_extrapDebugTimer
uint32 NamreebAnticheat::AnticheatLib::_extrapDebugTimer private
Definition at line 209 of file libanticheat.hpp.
Referenced by EnableExtrapolationDebug(), and OfferExtrapolationData().
_extrapMutex
std::mutex NamreebAnticheat::AnticheatLib::_extrapMutex private
Definition at line 211 of file libanticheat.hpp.
Referenced by OfferExtrapolationData().
_extrapPoints
nam::priority<ExtrapDebugPoint, float, 15> NamreebAnticheat::AnticheatLib::_extrapPoints private
Definition at line 223 of file libanticheat.hpp.
Referenced by OfferExtrapolationData().
The documentation for this class was generated from the following files:
libanticheat.hpp
libanticheat.cpp