CMaNGOS_WoTLK: instance_culling_of_stratholme Class Reference
instance_culling_of_stratholme Class Reference
#include <culling_of_stratholme.h>
Public Member Functions
instance_culling_of_stratholme (Map *pMap)
~instance_culling_of_stratholme ()
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void GetCratesBunnyOrderedList (CreatureList &lList)
void DoSpawnChromieIfNeeded (Unit *pSummoner)
void DoSpawnArthasIfNeeded (Unit *pSummoner)
bool CanGrainEventProgress (Creature *pCrate)
void DoSpawnBurningCityUndead (Unit *pSummoner)
void DoEventAtTriggerIfCan (uint32 uiTriggerId)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoSetupEntranceSoldiers (Unit *pSummoner)
void DoSpawnCorruptorIfNeeded (Unit *pSummoner)
void DoChromieWhisper (int32 iEntry)
void DoUpdateZombieResidents ()
void DoSpawnNextScourgeWave ()
uint32 GetRandomMobOfType (uint8 uiType) const
uint8 GetInstancePosition ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_bStartedInnEvent
uint8 m_uiGrainCrateCount
uint32 m_uiRemoveCrateStateTimer
uint32 m_uiArthasRespawnTimer
uint32 m_uiScourgeWaveTimer
uint32 m_uiScourgeWaveCount
uint8 m_uiCurrentUndeadPos
GuidList m_luiCratesBunnyGUIDs
GuidList m_luiResidentGUIDs
GuidList m_luiGateSoldiersGUIDs
GuidList m_luiCurrentScourgeWaveGUIDs
GuidSet m_sGrainCratesGuidSet
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 189 of file culling_of_stratholme.h.
Constructor & Destructor Documentation
instance_culling_of_stratholme()
instance_culling_of_stratholme::instance_culling_of_stratholme (Map * pMap)
Definition at line 134 of file instance_culling_of_stratholme.cpp.
References Initialize().
~instance_culling_of_stratholme()
instance_culling_of_stratholme::~instance_culling_of_stratholme () inline
Definition at line 193 of file culling_of_stratholme.h.
Member Function Documentation
CanGrainEventProgress()
bool instance_culling_of_stratholme::CanGrainEventProgress (Creature * pCrate)
Definition at line 702 of file instance_culling_of_stratholme.cpp.
References DONE, GetData(), Object::GetObjectGuid(), IN_PROGRESS, m_sGrainCratesGuidSet, SetData(), and TYPE_GRAIN_EVENT.
DoChromieWhisper()
void instance_culling_of_stratholme::DoChromieWhisper (int32 iEntry) protected
Definition at line 514 of file instance_culling_of_stratholme.cpp.
References DoScriptText(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, LinkedListHead::isEmpty(), and NPC_CHROMIE_ENTRANCE.
Referenced by SetData(), and Update().
DoEventAtTriggerIfCan()
void instance_culling_of_stratholme::DoEventAtTriggerIfCan (uint32 uiTriggerId)
Definition at line 718 of file instance_culling_of_stratholme.cpp.
References AREATRIGGER_INN, ScriptedInstance::GetSingleCreatureFromStorage(), m_bStartedInnEvent, NPC_MICHAEL_BELFAST, and UNIT_STAND_STATE_STAND.
DoSetupEntranceSoldiers()
void instance_culling_of_stratholme::DoSetupEntranceSoldiers (Unit * pSummoner) protected
Definition at line 653 of file instance_culling_of_stratholme.cpp.
References Map::GetCreature(), InstanceData::instance, m_aIntroActorsSpawnLocs, m_luiGateSoldiersGUIDs, NPC_HIGH_ELF_MAGE_PRIEST, NPC_LORDAERON_FOOTMAN, WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_DESPAWN.
Referenced by DoSpawnArthasIfNeeded().
DoSpawnArthasIfNeeded()
void instance_culling_of_stratholme::DoSpawnArthasIfNeeded (Unit * pSummoner)
Definition at line 573 of file instance_culling_of_stratholme.cpp.
References DoSetupEntranceSoldiers(), GetInstancePosition(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), m_aArthasSpawnLocs, m_aIntroActorsSpawnLocs, sSpawnLocation::m_fO, sSpawnLocation::m_fX, sSpawnLocation::m_fY, sSpawnLocation::m_fZ, M_PI_F, MAX_ARTHAS_SPAWN_POS, MotionMaster::MoveWaypoint(), NPC_ARTHAS, NPC_JAINA_PROUDMOORE, NPC_KNIGHT_SILVERHAND, NPC_UTHER_LIGHTBRINGER, POS_ARTHAS_INTRO, POS_ARTHAS_WAVES, Object::RemoveFlag(), Creature::SetWalk(), WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_TIMED_DESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by OnPlayerEnter(), SetData(), and Update().
DoSpawnBurningCityUndead()
void instance_culling_of_stratholme::DoSpawnBurningCityUndead (Unit * pSummoner)
Definition at line 795 of file instance_culling_of_stratholme.cpp.
References GetRandomMobOfType(), WorldObject::GetRandomPoint(), m_aBurningScourgeLocs, NPC_ZOMBIE, SCOURGE_TYPE_ACOLYTES, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by npc_arthasAI::ReceiveAIEvent().
DoSpawnChromieIfNeeded()
void instance_culling_of_stratholme::DoSpawnChromieIfNeeded (Unit * pSummoner)
Definition at line 630 of file instance_culling_of_stratholme.cpp.
References GetInstancePosition(), ScriptedInstance::GetSingleCreatureFromStorage(), m_aChromieSpawnLocs, NPC_CHROMIE_END, NPC_CHROMIE_ENTRANCE, NPC_HOURGLASS, POS_ARTHAS_INTRO, POS_INSTANCE_FINISHED, WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by OnPlayerEnter(), SetData(), and Update().
DoSpawnCorruptorIfNeeded()
void instance_culling_of_stratholme::DoSpawnCorruptorIfNeeded (Unit * pSummoner) protected
Definition at line 675 of file instance_culling_of_stratholme.cpp.
References Unit::CastSpell(), ScriptedInstance::GetSingleCreatureFromStorage(), m_aHeroicEventSpawnLocs, sSpawnLocation::m_fO, sSpawnLocation::m_fX, sSpawnLocation::m_fY, sSpawnLocation::m_fZ, NPC_GUARDIAN_OF_TIME, NPC_INFINITE_CORRUPTER, NPC_TIME_RIFT, SPELL_CORRUPTION_OF_TIME, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TRIGGERED_NONE.
Referenced by OnPlayerEnter(), and SetData().
DoSpawnNextScourgeWave()
void instance_culling_of_stratholme::DoSpawnNextScourgeWave () protected
Definition at line 738 of file instance_culling_of_stratholme.cpp.
References DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), GetData(), GetRandomMobOfType(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_aScourgeWavesLocs, sScourgeSpawnLoc::m_fO, sScourgeSpawnLoc::m_fX, sScourgeSpawnLoc::m_fY, sScourgeSpawnLoc::m_fZ, m_uiCurrentUndeadPos, m_uiScourgeWaveCount, MAX_SCOURGE_TYPE_PER_WAVE, NPC_ARTHAS, NPC_LORDAERON_CRIER, POS_ELDERS_SQUARE, POS_FESTIVAL_LANE, SCOURGE_TYPE_ACOLYTES, SCOURGE_TYPE_BOSS, SetData(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_INFINITE_CORRUPTER, uiScourgeWaveDef, and urand().
Referenced by Update().
DoUpdateZombieResidents()
void instance_culling_of_stratholme::DoUpdateZombieResidents () protected
Definition at line 691 of file instance_culling_of_stratholme.cpp.
References Map::GetCreature(), InstanceData::instance, m_luiResidentGUIDs, and NPC_ZOMBIE.
Referenced by SetData().
GetCratesBunnyOrderedList()
void instance_culling_of_stratholme::GetCratesBunnyOrderedList (CreatureList & lList)
Definition at line 557 of file instance_culling_of_stratholme.cpp.
References Map::GetCreature(), InstanceData::instance, m_luiCratesBunnyGUIDs, and sortFromEastToWest().
GetData()
uint32 instance_culling_of_stratholme::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 444 of file instance_culling_of_stratholme.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by CanGrainEventProgress(), DoSpawnNextScourgeWave(), GetRandomMobOfType(), OnCreatureCreate(), OnCreatureDeath(), OnPlayerEnter(), SetData(), and Update().
GetInstancePosition()
uint8 instance_culling_of_stratholme::GetInstancePosition () protected
Definition at line 531 of file instance_culling_of_stratholme.cpp.
References DONE, m_auiEncounter, POS_ARTHAS_ESCORTING, POS_ARTHAS_INTRO, POS_ARTHAS_MALGANIS, POS_ARTHAS_TOWNHALL, POS_ARTHAS_WAVES, POS_INSTANCE_FINISHED, TYPE_ARTHAS_ESCORT_EVENT, TYPE_ARTHAS_INTRO_EVENT, TYPE_EPOCH_EVENT, TYPE_GRAIN_EVENT, TYPE_MALGANIS_EVENT, TYPE_MEATHOOK_EVENT, and TYPE_SALRAMM_EVENT.
Referenced by DoSpawnArthasIfNeeded(), and DoSpawnChromieIfNeeded().
GetRandomMobOfType()
uint32 instance_culling_of_stratholme::GetRandomMobOfType (uint8 uiType) const protected
Definition at line 835 of file instance_culling_of_stratholme.cpp.
References GetData(), IN_PROGRESS, NPC_ACOLYTE, NPC_BILE_GOLEM, NPC_CRYPT_FIEND, NPC_DARK_NECROMANCER, NPC_DEVOURING_GHOUL, NPC_ENRAGING_GHOUL, NPC_MASTER_NECROMANCER, NPC_MEATHOOK, NPC_PATCHWORK_CONSTRUCT, NPC_SALRAMM_THE_FLESHCRAFTER, NPC_TOMB_STALKER, SCOURGE_TYPE_ACOLYTES, SCOURGE_TYPE_BOSS, SCOURGE_TYPE_FIEND, SCOURGE_TYPE_GHOUL, SCOURGE_TYPE_GOLEM, SCOURGE_TYPE_NECROMANCER, TYPE_MEATHOOK_EVENT, TYPE_SALRAMM_EVENT, and urand().
Referenced by DoSpawnBurningCityUndead(), and DoSpawnNextScourgeWave().
Initialize()
void instance_culling_of_stratholme::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 146 of file instance_culling_of_stratholme.cpp.
References m_auiEncounter.
Referenced by instance_culling_of_stratholme().
Load()
void instance_culling_of_stratholme::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 482 of file instance_culling_of_stratholme.cpp.
References IN_PROGRESS, m_auiEncounter, MAX_ENCOUNTER, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, TYPE_INFINITE_CORRUPTER, and TYPE_INFINITE_CORRUPTER_TIME.
OnCreatureCreate()
void instance_culling_of_stratholme::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 210 of file instance_culling_of_stratholme.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), Creature::IsTemporarySummon(), m_auiEncounter, m_luiCratesBunnyGUIDs, m_luiCurrentScourgeWaveGUIDs, m_luiGateSoldiersGUIDs, m_luiResidentGUIDs, ScriptedInstance::m_npcEntryGuidStore, NPC_ACOLYTE, NPC_AGIATED_STRATHOLME_CITIZEN, NPC_AGIATED_STRATHOLME_RESIDENT, NPC_ARTHAS, NPC_BARTLEBY_BATTSON, NPC_BILE_GOLEM, NPC_CHROMIE_END, NPC_CHROMIE_ENTRANCE, NPC_CRYPT_FIEND, NPC_DARK_NECROMANCER, NPC_DEVOURING_GHOUL, NPC_ENRAGING_GHOUL, NPC_FOOTMAN_JAMES, NPC_FRAS_SIABI, NPC_GRAIN_CRATE_HELPER, NPC_GRYAN_STOUTMANTLE, NPC_HEARTHSINGER_FORRESTEN, NPC_HIGH_ELF_MAGE_PRIEST, NPC_INFINITE_CORRUPTER, NPC_JENA_ANDERSON, NPC_LORD_EPOCH, NPC_LORDAERON_CRIER, NPC_LORDAERON_FOOTMAN, NPC_MAL_CORRICKS, NPC_MALCOM_MOORE, NPC_MALGANIS, NPC_MASTER_NECROMANCER, NPC_MICHAEL_BELFAST, NPC_PATCHWORK_CONSTRUCT, NPC_PATRICIA_O_REILLY, NPC_ROGER_OWENS, NPC_SERGEANT_MORIGAN, NPC_STRATHOLME_CITIZEN, NPC_STRATHOLME_RESIDENT, NPC_TOMB_STALKER, NPC_ZOMBIE, TYPE_ARTHAS_INTRO_EVENT, TYPE_SALRAMM_EVENT, and Creature::UpdateEntry().
OnCreatureDeath()
void instance_culling_of_stratholme::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 452 of file instance_culling_of_stratholme.cpp.
References DONE, GetData(), Object::GetEntry(), Object::GetObjectGuid(), Creature::IsTemporarySummon(), m_luiCurrentScourgeWaveGUIDs, m_uiScourgeWaveTimer, NPC_ACOLYTE, NPC_BILE_GOLEM, NPC_CRYPT_FIEND, NPC_DARK_NECROMANCER, NPC_DEVOURING_GHOUL, NPC_ENRAGING_GHOUL, NPC_INFINITE_CORRUPTER, NPC_LORD_EPOCH, NPC_MASTER_NECROMANCER, NPC_MEATHOOK, NPC_PATCHWORK_CONSTRUCT, NPC_SALRAMM_THE_FLESHCRAFTER, NPC_TOMB_STALKER, SetData(), TYPE_EPOCH_EVENT, TYPE_INFINITE_CORRUPTER, TYPE_MEATHOOK_EVENT, and TYPE_SALRAMM_EVENT.
OnObjectCreate()
void instance_culling_of_stratholme::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 270 of file instance_culling_of_stratholme.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_CITY_ENTRANCE_GATE, GO_DARK_RUNED_CHEST, GO_DARK_RUNED_CHEST_H, GO_DOOR_BOOKCASE, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, GameObject::SetGoState(), and TYPE_EPOCH_EVENT.
OnPlayerEnter()
void instance_culling_of_stratholme::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 151 of file instance_culling_of_stratholme.cpp.
References DONE, DoSpawnArthasIfNeeded(), DoSpawnChromieIfNeeded(), DoSpawnCorruptorIfNeeded(), GetData(), IN_MILLISECONDS, IN_PROGRESS, m_uiScourgeWaveCount, m_uiScourgeWaveTimer, MINUTE, Player::SendUpdateWorldState(), SetData(), SPECIAL, TYPE_ARTHAS_INTRO_EVENT, TYPE_GRAIN_EVENT, TYPE_INFINITE_CORRUPTER_TIME, TYPE_MEATHOOK_EVENT, TYPE_SALRAMM_EVENT, WORLD_STATE_CRATES, WORLD_STATE_TIME, WORLD_STATE_TIME_COUNTER, and WORLD_STATE_WAVE.
Save()
const char* instance_culling_of_stratholme::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 205 of file culling_of_stratholme.h.
References m_strInstData.
SetData()
void instance_culling_of_stratholme::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 289 of file instance_culling_of_stratholme.cpp.
References DoChromieWhisper(), DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), ScriptedInstance::DoRespawnGameObject(), DoSpawnArthasIfNeeded(), DoSpawnChromieIfNeeded(), DoSpawnCorruptorIfNeeded(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUpdateWorldState(), DoUpdateZombieResidents(), ScriptedInstance::DoUseDoorOrButton(), FAIL, GetData(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CITY_ENTRANCE_GATE, GO_DARK_RUNED_CHEST, GO_DARK_RUNED_CHEST_H, GO_FLAG_NO_INTERACT, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, m_strInstData, m_uiArthasRespawnTimer, m_uiGrainCrateCount, m_uiRemoveCrateStateTimer, m_uiScourgeWaveCount, m_uiScourgeWaveTimer, MAX_GRAIN_CRATES, MINUTE, NPC_ARTHAS, NPC_INFINITE_CORRUPTER, NPC_LORD_EPOCH, NPC_MALGANIS, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SAY_CORRUPTOR_DESPAWN, SPECIAL, TYPE_ARTHAS_ESCORT_EVENT, TYPE_ARTHAS_INTRO_EVENT, TYPE_ARTHAS_TOWNHALL_EVENT, TYPE_EPOCH_EVENT, TYPE_GRAIN_EVENT, TYPE_INFINITE_CORRUPTER, TYPE_INFINITE_CORRUPTER_TIME, TYPE_MALGANIS_EVENT, TYPE_MEATHOOK_EVENT, TYPE_SALRAMM_EVENT, WHISPER_CHROMIE_GUARDIAN, WHISPER_CHROMIE_HURRY, WORLD_STATE_CRATES, WORLD_STATE_CRATES_COUNT, WORLD_STATE_TIME, and WORLD_STATE_TIME_COUNTER.
Referenced by CanGrainEventProgress(), DoSpawnNextScourgeWave(), npc_arthasAI::JustDidDialogueStep(), npc_arthasAI::JustDied(), npc_arthasAI::MovementInform(), OnCreatureDeath(), OnPlayerEnter(), Update(), and npc_arthasAI::WaypointReached().
Update()
void instance_culling_of_stratholme::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 861 of file instance_culling_of_stratholme.cpp.
References DoChromieWhisper(), DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoSpawnArthasIfNeeded(), DoSpawnChromieIfNeeded(), DoSpawnNextScourgeWave(), ScriptedInstance::DoUpdateWorldState(), FAIL, GetData(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, IN_PROGRESS, m_auiEncounter, m_uiArthasRespawnTimer, m_uiRemoveCrateStateTimer, m_uiScourgeWaveCount, m_uiScourgeWaveTimer, MINUTE, NPC_ARTHAS, SAY_MEET_TOWN_HALL, SetData(), SPECIAL, TYPE_INFINITE_CORRUPTER, TYPE_INFINITE_CORRUPTER_TIME, TYPE_SALRAMM_EVENT, WHISPER_CHROMIE_CRATES, WORLD_STATE_CRATES, and WORLD_STATE_WAVE.
Field Documentation
m_auiEncounter
uint32 instance_culling_of_stratholme::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 228 of file culling_of_stratholme.h.
Referenced by GetData(), GetInstancePosition(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), SetData(), and Update().
m_bStartedInnEvent
bool instance_culling_of_stratholme::m_bStartedInnEvent protected
Definition at line 231 of file culling_of_stratholme.h.
Referenced by DoEventAtTriggerIfCan().
m_luiCratesBunnyGUIDs
GuidList instance_culling_of_stratholme::m_luiCratesBunnyGUIDs protected
Definition at line 241 of file culling_of_stratholme.h.
Referenced by GetCratesBunnyOrderedList(), and OnCreatureCreate().
m_luiCurrentScourgeWaveGUIDs
GuidList instance_culling_of_stratholme::m_luiCurrentScourgeWaveGUIDs protected
Definition at line 244 of file culling_of_stratholme.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_luiGateSoldiersGUIDs
GuidList instance_culling_of_stratholme::m_luiGateSoldiersGUIDs protected
Definition at line 243 of file culling_of_stratholme.h.
Referenced by DoSetupEntranceSoldiers(), and OnCreatureCreate().
m_luiResidentGUIDs
GuidList instance_culling_of_stratholme::m_luiResidentGUIDs protected
Definition at line 242 of file culling_of_stratholme.h.
Referenced by DoUpdateZombieResidents(), and OnCreatureCreate().
m_sGrainCratesGuidSet
GuidSet instance_culling_of_stratholme::m_sGrainCratesGuidSet protected
Definition at line 246 of file culling_of_stratholme.h.
Referenced by CanGrainEventProgress().
m_strInstData
std::string instance_culling_of_stratholme::m_strInstData protected
Definition at line 229 of file culling_of_stratholme.h.
Referenced by Save(), and SetData().
m_uiArthasRespawnTimer
uint32 instance_culling_of_stratholme::m_uiArthasRespawnTimer protected
Definition at line 235 of file culling_of_stratholme.h.
Referenced by SetData(), and Update().
m_uiCurrentUndeadPos
uint8 instance_culling_of_stratholme::m_uiCurrentUndeadPos protected
Definition at line 239 of file culling_of_stratholme.h.
Referenced by DoSpawnNextScourgeWave().
m_uiGrainCrateCount
uint8 instance_culling_of_stratholme::m_uiGrainCrateCount protected
Definition at line 233 of file culling_of_stratholme.h.
Referenced by SetData().
m_uiRemoveCrateStateTimer
uint32 instance_culling_of_stratholme::m_uiRemoveCrateStateTimer protected
Definition at line 234 of file culling_of_stratholme.h.
Referenced by SetData(), and Update().
m_uiScourgeWaveCount
uint32 instance_culling_of_stratholme::m_uiScourgeWaveCount protected
Definition at line 238 of file culling_of_stratholme.h.
Referenced by DoSpawnNextScourgeWave(), OnPlayerEnter(), SetData(), and Update().
m_uiScourgeWaveTimer
uint32 instance_culling_of_stratholme::m_uiScourgeWaveTimer protected
Definition at line 237 of file culling_of_stratholme.h.
Referenced by OnCreatureDeath(), OnPlayerEnter(), SetData(), and Update().
The documentation for this class was generated from the following files:
culling_of_stratholme.h
instance_culling_of_stratholme.cpp