CMaNGOS_WoTLK: SpellTargetMgr Class Reference
SpellTargetMgr Class Reference
#include <SpellTargets.h>
Static Public Member Functions
static void Initialize ()
static SpellTargetingData & GetSpellTargetingData (uint32 spellId)
static bool CanEffectBeFilledWithMask (uint32 spellId, uint32 effIdx, uint32 mask)
static bool CanEffectConsumeTarget (SpellTargetImplicitType targetType, SpellTargetImplicitType effectTargetType)
static float GetJumpRadius (uint32 spellId)
static SpellTargetFilterScheme GetSpellTargetingFilterScheme (SpellTargetFilterScheme oldScheme, uint32 spellId)
Static Private Attributes
static std::map< uint32, SpellTargetingData > spellTargetingData
Detailed Description
Definition at line 53 of file SpellTargets.h.
Member Function Documentation
CanEffectBeFilledWithMask()
bool SpellTargetMgr::CanEffectBeFilledWithMask (uint32 spellId, uint32 effIdx, uint32 mask) static
Definition at line 555 of file SpellTargets.cpp.
References GetSpellTargetingData(), SpellTargetingData::implicitType, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_GAMEOBJECT, TARGET_FLAG_ITEM, TARGET_FLAG_LOCKED, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_ALLY, TARGET_FLAG_UNIT_DEAD, TARGET_FLAG_UNIT_ENEMY, TARGET_TYPE_CORPSE, TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_ITEM, TARGET_TYPE_LOCATION_DEST, TARGET_TYPE_LOCATION_TRAJ, TARGET_TYPE_LOCK, TARGET_TYPE_PLAYER, TARGET_TYPE_SPECIAL_DEST, TARGET_TYPE_UNIT, and TARGET_TYPE_UNIT_DEST.
Referenced by Spell::FillTargetMap().
CanEffectConsumeTarget()
bool SpellTargetMgr::CanEffectConsumeTarget (SpellTargetImplicitType targetType, SpellTargetImplicitType effectTargetType) static
Definition at line 574 of file SpellTargets.cpp.
References TARGET_TYPE_LOCATION_DEST, and TARGET_TYPE_UNIT.
Referenced by Initialize().
GetJumpRadius()
float SpellTargetMgr::GetJumpRadius (uint32 spellId) static
Definition at line 585 of file SpellTargets.cpp.
References CHAIN_SPELL_JUMP_RADIUS.
Referenced by Spell::Spell().
GetSpellTargetingData()
SpellTargetingData & SpellTargetMgr::GetSpellTargetingData (uint32 spellId) static
Definition at line 317 of file SpellTargets.cpp.
References spellTargetingData.
Referenced by Spell::AddUnitTarget(), CanEffectBeFilledWithMask(), Spell::EffectDummy(), Spell::EffectScriptEffect(), Spell::FillTargetMap(), and Spell::Spell().
GetSpellTargetingFilterScheme()
SpellTargetFilterScheme SpellTargetMgr::GetSpellTargetingFilterScheme (SpellTargetFilterScheme oldScheme, uint32 spellId) static
Definition at line 616 of file SpellTargets.cpp.
References SCHEME_CLOSEST, SCHEME_FURTHEST, and SCHEME_HIGHEST_HP.
Referenced by Initialize().
Initialize()
void SpellTargetMgr::Initialize () static
Definition at line 334 of file SpellTargets.cpp.
References CanEffectConsumeTarget(), CheckBoundsEqualForEffects(), SpellEntry::Effect, SpellEntry::EffectChainTarget, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectRadiusIndex, SpellTargetInfo::enumerator, SpellTargetInfo::filter, SpellTargetingData::filteringScheme, SQLMultiStorage::getBounds(), SQLStorageBase::GetMaxEntry(), GetSpellTargetingFilterScheme(), SpellEntry::Id, SpellTargetingData::ignoredTargets, SpellTargetingData::implicitType, SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, SpellEffectInfo::requiredTarget, SCHEME_CLOSEST_CHAIN, SCHEME_LOWEST_HP_CHAIN, SCHEME_RANDOM, SCHEME_RANDOM_CHAIN, sLog, SpellEffectInfoTable, SpellTargetInfoTable, spellTargetingData, sSpellScriptTargetStorage, sSpellTemplate, TARGET_ENUMERATOR_CHAIN, TARGET_ENUMERATOR_SINGLE, TARGET_NONE, TARGET_SCRIPT, TARGET_TYPE_CORPSE, TARGET_TYPE_DYNAMIC, TARGET_TYPE_DYNAMIC_ANY, TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_LOCATION_DEST, TARGET_TYPE_LOCATION_SRC, TARGET_TYPE_LOCATION_TRAJ, TARGET_TYPE_LOCK, TARGET_TYPE_NONE, TARGET_TYPE_PLAYER, TARGET_TYPE_SPECIAL_UNIT, TARGET_TYPE_UNIT, TARGET_TYPE_UNIT_DEST, TARGET_UNIT, TARGET_UNIT_ENEMY, TARGET_UNIT_ENEMY_NEAR_CASTER, TARGET_UNIT_FRIEND_CHAIN_HEAL, TARGET_UNIT_FRIEND_NEAR_CASTER, TARGET_UNIT_NEAR_CASTER, SpellTargetingData::targetMask, and SpellTargetInfo::type.
Referenced by World::SetInitialWorldSettings().
Field Documentation
spellTargetingData
std::map< uint32, SpellTargetingData > SpellTargetMgr::spellTargetingData static private
Definition at line 65 of file SpellTargets.h.
Referenced by GetSpellTargetingData(), and Initialize().
The documentation for this class was generated from the following files:
SpellTargets.h
SpellTargets.cpp