CMaNGOS_WoTLK: HMACSHA1 Class Reference
HMACSHA1 Class Reference
#include <HMACSHA1.h>
Public Member Functions
HMACSHA1 (uint32 len, const uint8 *seed)
HMACSHA1 (uint32 len, const uint8 *seed, bool)
~HMACSHA1 ()
void UpdateBigNumber (BigNumber *bn)
void UpdateData (const uint8 *data, int length)
void UpdateData (const std::string &str)
void Initialize ()
void Finalize ()
uint8 * ComputeHash (BigNumber *bn)
uint8 * GetDigest ()
Static Public Member Functions
static int GetLength ()
Private Attributes
HMAC_CTX * m_ctx
uint8 m_key [SEED_KEY_SIZE]
uint8 m_digest [SHA_DIGEST_LENGTH]
Detailed Description
Definition at line 30 of file HMACSHA1.h.
Constructor & Destructor Documentation
HMACSHA1() [1/2]
HMACSHA1::HMACSHA1 (uint32 len, const uint8 * seed)
Definition at line 22 of file HMACSHA1.cpp.
References m_ctx, and m_key.
HMACSHA1() [2/2]
HMACSHA1::HMACSHA1 (uint32 len, const uint8 * seed, bool)
Definition at line 40 of file HMACSHA1.cpp.
References m_ctx.
~HMACSHA1()
HMACSHA1::~HMACSHA1 ()
Definition at line 57 of file HMACSHA1.cpp.
References m_ctx, m_key, and SEED_KEY_SIZE.
Member Function Documentation
ComputeHash()
uint8 * HMACSHA1::ComputeHash (BigNumber * bn)
Definition at line 112 of file HMACSHA1.cpp.
References BigNumber::AsByteArray(), Finalize(), BigNumber::GetNumBytes(), m_digest, and UpdateData().
Referenced by AuthCrypt::Init().
Finalize()
void HMACSHA1::Finalize ()
Definition at line 100 of file HMACSHA1.cpp.
References m_ctx, m_digest, and MANGOS_ASSERT.
Referenced by ComputeHash(), WorldSession::SendRedirectClient(), WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), and WindowsModuleScan::WindowsModuleScan().
GetDigest()
uint8* HMACSHA1::GetDigest () inline
Definition at line 42 of file HMACSHA1.h.
References m_digest.
Referenced by WorldSession::SendRedirectClient(), WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), and WindowsModuleScan::WindowsModuleScan().
GetLength()
static int HMACSHA1::GetLength () inline static
Definition at line 43 of file HMACSHA1.h.
Referenced by WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), and WindowsModuleScan::WindowsModuleScan().
Initialize()
void HMACSHA1::Initialize ()
Definition at line 87 of file HMACSHA1.cpp.
References m_ctx, m_key, and SEED_KEY_SIZE.
UpdateBigNumber()
void HMACSHA1::UpdateBigNumber (BigNumber * bn)
Definition at line 68 of file HMACSHA1.cpp.
References BigNumber::AsByteArray(), BigNumber::GetNumBytes(), and UpdateData().
UpdateData() [1/2]
void HMACSHA1::UpdateData (const std::string & str)
Definition at line 82 of file HMACSHA1.cpp.
References UpdateData().
UpdateData() [2/2]
void HMACSHA1::UpdateData (const uint8 * data, int length)
Definition at line 73 of file HMACSHA1.cpp.
References m_ctx.
Referenced by ComputeHash(), WorldSession::SendRedirectClient(), UpdateBigNumber(), UpdateData(), WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), and WindowsModuleScan::WindowsModuleScan().
Field Documentation
m_ctx
HMAC_CTX* HMACSHA1::m_ctx private
Definition at line 49 of file HMACSHA1.h.
Referenced by Finalize(), HMACSHA1(), Initialize(), UpdateData(), and ~HMACSHA1().
m_digest
uint8 HMACSHA1::m_digest[SHA_DIGEST_LENGTH] private
Definition at line 52 of file HMACSHA1.h.
Referenced by ComputeHash(), Finalize(), and GetDigest().
m_key
uint8 HMACSHA1::m_key[SEED_KEY_SIZE] private
Definition at line 51 of file HMACSHA1.h.
Referenced by HMACSHA1(), Initialize(), and ~HMACSHA1().
The documentation for this class was generated from the following files:
HMACSHA1.h
HMACSHA1.cpp