CMaNGOS_WoTLK: WanderMovementGenerator Class Reference
WanderMovementGenerator Class Reference
#include <RandomMovementGenerator.h>
Public Member Functions
WanderMovementGenerator (Creature const &npc)
WanderMovementGenerator (float x, float y, float z, float radius, float verticalZ=0.0f)
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from AbstractRandomMovementGenerator
AbstractRandomMovementGenerator (uint32 stateActive, uint32 stateMotion, uint32 delayMin, uint32 delayMax, uint32 movesMax=1)
void Initialize (Unit &owner) override
void Reset (Unit &owner) override
bool Update (Unit &owner, const uint32 &diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Additional Inherited Members
Protected Member Functions inherited from AbstractRandomMovementGenerator
virtual int32 _setLocation (Unit &owner)
Protected Attributes inherited from AbstractRandomMovementGenerator
float i_x
float i_y
float i_z
float i_radius
float i_verticalZ
float i_pathLength
bool i_walk
std::unique_ptr< PathFinder > m_pathFinder
ShortTimeTracker i_nextMoveTimer
uint32 i_nextMoveCount
uint32 i_nextMoveCountMax
uint32 i_nextMoveDelayMin
uint32 i_nextMoveDelayMax
uint32 i_stateActive
uint32 i_stateMotion
Detailed Description
Definition at line 69 of file RandomMovementGenerator.h.
Constructor & Destructor Documentation
WanderMovementGenerator() [1/2]
WanderMovementGenerator::WanderMovementGenerator (Creature const & npc) explicit
Definition at line 171 of file RandomMovementGenerator.cpp.
References Creature::GetRespawnCoord(), AbstractRandomMovementGenerator::i_radius, AbstractRandomMovementGenerator::i_x, AbstractRandomMovementGenerator::i_y, and AbstractRandomMovementGenerator::i_z.
WanderMovementGenerator() [2/2]
WanderMovementGenerator::WanderMovementGenerator (float x, float y, float z, float radius, float verticalZ = 0.0f)
Definition at line 161 of file RandomMovementGenerator.cpp.
References AbstractRandomMovementGenerator::i_radius, AbstractRandomMovementGenerator::i_verticalZ, AbstractRandomMovementGenerator::i_x, AbstractRandomMovementGenerator::i_y, and AbstractRandomMovementGenerator::i_z.
Member Function Documentation
Finalize()
void WanderMovementGenerator::Finalize (Unit & owner) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 177 of file RandomMovementGenerator.cpp.
References AbstractRandomMovementGenerator::Finalize(), Object::GetTypeId(), Unit::hasUnitState(), TYPEID_UNIT, and UNIT_STAT_RUNNING_STATE.
GetMovementGeneratorType()
MovementGeneratorType WanderMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Reimplemented in TimedWanderMovementGenerator.
Definition at line 78 of file RandomMovementGenerator.h.
References RANDOM_MOTION_TYPE.
Interrupt()
void WanderMovementGenerator::Interrupt (Unit & owner) override virtual
Reimplemented from AbstractRandomMovementGenerator.
Definition at line 185 of file RandomMovementGenerator.cpp.
References Object::GetTypeId(), Unit::hasUnitState(), AbstractRandomMovementGenerator::Interrupt(), TYPEID_UNIT, and UNIT_STAT_RUNNING_STATE.
The documentation for this class was generated from the following files:
RandomMovementGenerator.h
RandomMovementGenerator.cpp