CMaNGOS_WoTLK: SRP6 Class Reference
SRP6 Class Reference
#include <SRP6.h>
Public Member Functions
SRP6 (void)
Initializes SRP with a predefined prime (N) and generator module (g)
void CalculateHostPublicEphemeral (void)
calculates the host public ephemeral (B)
void CalculateProof (std::string username)
calculates proof (M) of the strong session key (K)
bool CalculateSessionKey (uint8 *lp_A, int l)
calculates a session key (S) based on client public ephemeral (A)
bool CalculateVerifier (const std::string &rI)
calculates the password verifier (v)
bool CalculateVerifier (const std::string &rI, const char *salt)
calculates the password verifier (v) based on a predefined salt (s)
void HashSessionKey (void)
generates a strong session key (K) of session key (S)
bool Proof (uint8 *lp_M, int l)
compares proof (M) of strong session key (K)
bool ProofVerifier (std::string vC)
compare password verifier (v)
void Finalize (Sha1Hash &sha)
generate hash for proof of strong session key (K)
BigNumber GetHostPublicEphemeral (void)
BigNumber GetGeneratorModulo (void)
BigNumber GetPrime (void)
BigNumber GetProof (void)
BigNumber GetSalt (void)
BigNumber GetStrongSessionKey (void)
BigNumber GetVerifier (void)
bool SetSalt (const char *new_s)
void SetStrongSessionKey (const char *new_K)
bool SetVerifier (const char *new_v)
Static Public Attributes
static const int s_BYTE_SIZE = 32
Private Attributes
BigNumber A
BigNumber u
BigNumber S
BigNumber N
BigNumber s
BigNumber g
BigNumber v
BigNumber b
BigNumber B
BigNumber K
BigNumber M
Detailed Description
Secure Remote Password protocol
Definition at line 30 of file SRP6.h.
Constructor & Destructor Documentation
SRP6()
SRP6::SRP6 (void)
Initializes SRP with a predefined prime (N) and generator module (g)
Definition at line 25 of file SRP6.cpp.
References g, N, BigNumber::SetDword(), and BigNumber::SetHexStr().
Member Function Documentation
CalculateHostPublicEphemeral()
void SRP6::CalculateHostPublicEphemeral (void)
calculates the host public ephemeral (B)
generates also a random number as host private ephemeral (b)
Definition at line 31 of file SRP6.cpp.
References B, b, g, BigNumber::GetNumBytes(), MANGOS_ASSERT, BigNumber::ModExp(), N, BigNumber::SetRand(), and v.
Referenced by AuthSocket::_HandleLogonChallenge().
CalculateProof()
void SRP6::CalculateProof (std::string username)
calculates proof (M) of the strong session key (K)
Parameters
username the unique identity of the account to authenticate
Definition at line 40 of file SRP6.cpp.
References A, B, CryptoHash< Algorithm, DigestSize >::Finalize(), g, CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength(), CryptoHash< Algorithm, DigestSize >::Initialize(), K, M, N, s, BigNumber::SetBinary(), CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), and CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by AuthSocket::_HandleLogonProof().
CalculateSessionKey()
bool SRP6::CalculateSessionKey (uint8 * lp_A, int l)
calculates a session key (S) based on client public ephemeral (A)
safeguard conditions are (A != 0) and (A % N != 0)
Parameters
lp_A the client public ephemeral (A)
l the length of client public ephemeral (A)
Returns
true on valid safeguard conditions otherwise false
Definition at line 73 of file SRP6.cpp.
References A, b, B, CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), BigNumber::isZero(), BigNumber::ModExp(), N, S, BigNumber::SetBinary(), u, CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers(), and v.
Referenced by AuthSocket::_HandleLogonProof().
CalculateVerifier() [1/2]
bool SRP6::CalculateVerifier (const std::string & rI)
calculates the password verifier (v)
Parameters
rI a sha1 hash of USERNAME:PASSWORD
Returns
true on success otherwise false if s is faulty
Definition at line 93 of file SRP6.cpp.
References BigNumber::AsHexStr(), s_BYTE_SIZE, and BigNumber::SetRand().
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), AccountMgr::CheckPassword(), and AccountMgr::CreateAccount().
CalculateVerifier() [2/2]
bool SRP6::CalculateVerifier (const std::string & rI, const char * salt)
calculates the password verifier (v) based on a predefined salt (s)
Parameters
rI a sha1 hash of USERNAME:PASSWORD
salt a predefined salt (s)
Returns
true on success otherwise false if s is faulty
Definition at line 103 of file SRP6.cpp.
References BigNumber::AsByteArray(), CryptoHash< Algorithm, DigestSize >::Finalize(), g, CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< EVP_sha1, SHA_DIGEST_LENGTH >::GetLength(), BigNumber::GetNumBytes(), BigNumber::isZero(), BigNumber::ModExp(), N, s, BigNumber::SetBinary(), BigNumber::SetHexStr(), CryptoHash< Algorithm, DigestSize >::UpdateData(), and v.
Finalize()
void SRP6::Finalize (Sha1Hash & sha)
generate hash for proof of strong session key (K)
this hash has to be send to the client for client-side proof. client has to show it's proof first. If the server detects an incorrect proof it must abort without showing it's proof.
Parameters
sha reference to an empty Sha1Hash object
Definition at line 188 of file SRP6.cpp.
References A, CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::Initialize(), K, M, and CryptoHash< Algorithm, DigestSize >::UpdateBigNumbers().
Referenced by AuthSocket::_HandleLogonProof().
GetGeneratorModulo()
BigNumber SRP6::GetGeneratorModulo (void) inline
Definition at line 104 of file SRP6.h.
References g.
Referenced by AuthSocket::_HandleLogonChallenge().
GetHostPublicEphemeral()
BigNumber SRP6::GetHostPublicEphemeral (void) inline
Definition at line 103 of file SRP6.h.
References B.
Referenced by AuthSocket::_HandleLogonChallenge().
GetPrime()
BigNumber SRP6::GetPrime (void) inline
Definition at line 105 of file SRP6.h.
References N.
Referenced by AuthSocket::_HandleLogonChallenge().
GetProof()
BigNumber SRP6::GetProof (void) inline
Definition at line 106 of file SRP6.h.
References M.
GetSalt()
BigNumber SRP6::GetSalt (void) inline
Definition at line 107 of file SRP6.h.
References s.
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), and AccountMgr::CreateAccount().
GetStrongSessionKey()
BigNumber SRP6::GetStrongSessionKey (void) inline
Definition at line 108 of file SRP6.h.
References K.
Referenced by AuthSocket::_HandleLogonProof(), and AuthSocket::_HandleReconnectProof().
GetVerifier()
BigNumber SRP6::GetVerifier (void) inline
Definition at line 109 of file SRP6.h.
References v.
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), and AccountMgr::CreateAccount().
HashSessionKey()
void SRP6::HashSessionKey (void)
generates a strong session key (K) of session key (S)
Definition at line 133 of file SRP6.cpp.
References BigNumber::AsByteArray(), CryptoHash< Algorithm, DigestSize >::Finalize(), CryptoHash< Algorithm, DigestSize >::GetDigest(), CryptoHash< Algorithm, DigestSize >::Initialize(), K, S, BigNumber::SetBinary(), and CryptoHash< Algorithm, DigestSize >::UpdateData().
Referenced by AuthSocket::_HandleLogonProof().
Proof()
bool SRP6::Proof (uint8 * lp_M, int l)
compares proof (M) of strong session key (K)
Parameters
lp_M client proof (M) of the strong session key (K)
l the length of client proof (M)
Returns
true if client and server proof matches otherwise false
Definition at line 165 of file SRP6.cpp.
References BigNumber::AsByteArray(), and M.
Referenced by AuthSocket::_HandleLogonProof().
ProofVerifier()
bool SRP6::ProofVerifier (std::string vC)
compare password verifier (v)
verifies if provided password matches the password verifier (v) requires to use the same salt (s) which was initially used to compute v.
Parameters
vC predefined password verifier (v) read from database
Returns
true if password verifier matches otherwise false
Definition at line 173 of file SRP6.cpp.
References BigNumber::AsHexStr(), and v.
Referenced by AccountMgr::CheckPassword().
SetSalt()
bool SRP6::SetSalt (const char * new_s)
Definition at line 195 of file SRP6.cpp.
References BigNumber::isZero(), s, and BigNumber::SetHexStr().
Referenced by AuthSocket::_HandleLogonChallenge().
SetStrongSessionKey()
void SRP6::SetStrongSessionKey (const char * new_K) inline
Definition at line 112 of file SRP6.h.
References K, and BigNumber::SetHexStr().
Referenced by AuthSocket::_HandleReconnectChallenge().
SetVerifier()
bool SRP6::SetVerifier (const char * new_v)
Definition at line 201 of file SRP6.cpp.
References BigNumber::isZero(), BigNumber::SetHexStr(), and v.
Referenced by AuthSocket::_HandleLogonChallenge().
Field Documentation
A
BigNumber SRP6::A private
Definition at line 116 of file SRP6.h.
Referenced by CalculateProof(), CalculateSessionKey(), and Finalize().
b
BigNumber SRP6::b private
Definition at line 118 of file SRP6.h.
Referenced by CalculateHostPublicEphemeral(), and CalculateSessionKey().
B
BigNumber SRP6::B private
Definition at line 118 of file SRP6.h.
Referenced by CalculateHostPublicEphemeral(), CalculateProof(), CalculateSessionKey(), and GetHostPublicEphemeral().
g
BigNumber SRP6::g private
Definition at line 117 of file SRP6.h.
Referenced by CalculateHostPublicEphemeral(), CalculateProof(), CalculateVerifier(), GetGeneratorModulo(), and SRP6().
K
BigNumber SRP6::K private
Definition at line 119 of file SRP6.h.
Referenced by CalculateProof(), Finalize(), GetStrongSessionKey(), HashSessionKey(), and SetStrongSessionKey().
M
BigNumber SRP6::M private
Definition at line 120 of file SRP6.h.
Referenced by CalculateProof(), Finalize(), GetProof(), and Proof().
N
BigNumber SRP6::N private
Definition at line 117 of file SRP6.h.
Referenced by CalculateHostPublicEphemeral(), CalculateProof(), CalculateSessionKey(), CalculateVerifier(), GetPrime(), and SRP6().
S
BigNumber SRP6::S private
Definition at line 116 of file SRP6.h.
Referenced by CalculateSessionKey(), and HashSessionKey().
s
BigNumber SRP6::s private
Definition at line 117 of file SRP6.h.
Referenced by CalculateProof(), CalculateVerifier(), GetSalt(), and SetSalt().
s_BYTE_SIZE
const int SRP6::s_BYTE_SIZE = 32 static
length of salt
Definition at line 33 of file SRP6.h.
Referenced by CalculateVerifier().
u
BigNumber SRP6::u private
Definition at line 116 of file SRP6.h.
Referenced by CalculateSessionKey().
v
BigNumber SRP6::v private
Definition at line 117 of file SRP6.h.
Referenced by CalculateHostPublicEphemeral(), CalculateSessionKey(), CalculateVerifier(), GetVerifier(), ProofVerifier(), and SetVerifier().
The documentation for this class was generated from the following files:
SRP6.h
SRP6.cpp