CMaNGOS_WoTLK: OutdoorPvPEP Class Reference
OutdoorPvPEP Class Reference
#include <OutdoorPvPEP.h>
Public Member Functions
OutdoorPvPEP ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleObjectiveComplete (uint32 eventId, const PlayerList &players, Team team) override
void HandleCreatureCreate (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
bool HandleGameObjectUse (Player *player, GameObject *go) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
bool ProcessCaptureEvent (GameObject *go, uint32 towerId, Team team, uint32 newWorldState)
void InitBanner (GameObject *go, uint32 towerId)
void UnsummonFlightMaster (const WorldObject *objRef)
void UnsummonSoldiers (const WorldObject *objRef)
Private Attributes
Team m_towerOwner [MAX_EP_TOWERS]
uint32 m_towerWorldState [MAX_EP_TOWERS]
uint8 m_towersAlliance
uint8 m_towersHorde
ObjectGuid m_flightMaster
ObjectGuid m_lordaeronShrineAlliance
ObjectGuid m_lordaeronShrineHorde
GuidList m_soldiers
GuidList m_towerBanners [MAX_EP_TOWERS]
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 204 of file OutdoorPvPEP.h.
Constructor & Destructor Documentation
OutdoorPvPEP()
OutdoorPvPEP::OutdoorPvPEP ()
Definition at line 28 of file OutdoorPvPEP.cpp.
References GRAVEYARD_ID_EASTERN_PLAGUE, GRAVEYARD_ZONE_EASTERN_PLAGUE, m_towerOwner, m_towerWorldState, OutdoorPvP::SetGraveYardLinkTeam(), TEAM_INVALID, TEAM_NONE, WORLD_STATE_EP_CROWNGUARD_NEUTRAL, WORLD_STATE_EP_EASTWALL_NEUTRAL, WORLD_STATE_EP_NORTHPASS_NEUTRAL, and WORLD_STATE_EP_PLAGUEWOOD_NEUTRAL.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPEP::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 44 of file OutdoorPvPEP.cpp.
References FillInitialWorldState(), m_towersAlliance, m_towersHorde, m_towerWorldState, WORLD_STATE_ADD, WORLD_STATE_EP_TOWER_COUNT_ALLIANCE, and WORLD_STATE_EP_TOWER_COUNT_HORDE.
HandleCreatureCreate()
void OutdoorPvPEP::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 92 of file OutdoorPvPEP.cpp.
References ALLIANCE, Unit::CastSpell(), FACTION_FLIGHT_MASTER_ALLIANCE, FACTION_FLIGHT_MASTER_HORDE, Object::GetEntry(), Object::GetObjectGuid(), m_flightMaster, m_soldiers, m_towerOwner, NPC_LORDAERON_COMMANDER, NPC_LORDAERON_FIGHTER, NPC_LORDAERON_SOLDIER, NPC_LORDAERON_VETERAN, NPC_SPECTRAL_FLIGHT_MASTER, Unit::setFaction(), SPELL_SPIRIT_PARTICLES_BLUE, SPELL_SPIRIT_PARTICLES_RED, TOWER_ID_PLAGUEWOOD, and TRIGGERED_OLD_TRIGGERED.
HandleEvent()
bool OutdoorPvPEP::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 184 of file OutdoorPvPEP.cpp.
References Object::GetEntry(), Object::IsGameObject(), m_towerOwner, MAX_EP_TOWERS, plaguelandsBanners, plaguelandsTowerEvents, ProcessCaptureEvent(), sWorld, and ZONE_ID_EASTERN_PLAGUELANDS.
HandleGameObjectCreate()
void OutdoorPvPEP::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 110 of file OutdoorPvPEP.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_LORDAERON_SHRINE_ALLIANCE, GO_LORDAERON_SHRINE_HORDE, GO_TOWER_BANNER, GO_TOWER_BANNER_CROWNGUARD, GO_TOWER_BANNER_EASTWALL, GO_TOWER_BANNER_NORTHPASS, GO_TOWER_BANNER_PLAGUEWOOD, OutdoorPvP::HandleGameObjectCreate(), InitBanner(), WorldObject::IsWithinDist2d(), m_lordaeronShrineAlliance, m_lordaeronShrineHorde, plaguelandsTowerLocations, TOWER_ID_CROWNGUARD, TOWER_ID_EASTWALL, TOWER_ID_NORTHPASS, and TOWER_ID_PLAGUEWOOD.
HandleGameObjectUse()
bool OutdoorPvPEP::HandleGameObjectUse (Player * player, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 334 of file OutdoorPvPEP.cpp.
References Object::GetEntry(), GO_LORDAERON_SHRINE_ALLIANCE, GO_LORDAERON_SHRINE_HORDE, and GameObject::SetRespawnTime().
HandleObjectiveComplete()
void OutdoorPvPEP::HandleObjectiveComplete (uint32 eventId, const PlayerList & players, Team team) override virtual
Reimplemented from OutdoorPvP.
Definition at line 148 of file OutdoorPvPEP.cpp.
References EVENT_CROWNGUARD_PROGRESS_ALLIANCE, EVENT_CROWNGUARD_PROGRESS_HORDE, EVENT_EASTWALL_PROGRESS_ALLIANCE, EVENT_EASTWALL_PROGRESS_HORDE, EVENT_NORTHPASS_PROGRESS_ALLIANCE, EVENT_NORTHPASS_PROGRESS_HORDE, EVENT_PLAGUEWOOD_PROGRESS_ALLIANCE, EVENT_PLAGUEWOOD_PROGRESS_HORDE, HONOR_REWARD_PLAGUELANDS, NPC_CROWNGUARD_TOWER_QUEST_DOODAD, NPC_EASTWALL_TOWER_QUEST_DOODAD, NPC_NORTHPASS_TOWER_QUEST_DOODAD, and NPC_PLAGUEWOOD_TOWER_QUEST_DOODAD.
HandlePlayerEnterZone()
void OutdoorPvPEP::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 59 of file OutdoorPvPEP.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), HORDE, m_towersAlliance, m_towersHorde, plaguelandsTowerBuffs, Unit::RemoveAurasDueToSpell(), and TRIGGERED_OLD_TRIGGERED.
HandlePlayerLeaveZone()
void OutdoorPvPEP::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 83 of file OutdoorPvPEP.cpp.
References ALLIANCE, Player::GetTeam(), OutdoorPvP::HandlePlayerLeaveZone(), plaguelandsTowerBuffs, and Unit::RemoveAurasDueToSpell().
InitBanner()
void OutdoorPvPEP::InitBanner (GameObject * go, uint32 towerId) private
Definition at line 343 of file OutdoorPvPEP.cpp.
References OutdoorPvP::GetBannerArtKit(), Object::GetObjectGuid(), m_towerBanners, m_towerOwner, and GameObject::SetGoArtKit().
Referenced by HandleGameObjectCreate().
ProcessCaptureEvent()
bool OutdoorPvPEP::ProcessCaptureEvent (GameObject * go, uint32 towerId, Team team, uint32 newWorldState) private
Definition at line 218 of file OutdoorPvPEP.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), CAPTURE_ANIM_ALLIANCE, CAPTURE_ANIM_HORDE, CAPTURE_ANIM_NEUTRAL, CAPTURE_ARTKIT_ALLIANCE, CAPTURE_ARTKIT_HORDE, CAPTURE_ARTKIT_NEUTRAL, GRAVEYARD_ID_EASTERN_PLAGUE, GRAVEYARD_ZONE_EASTERN_PLAGUE, HORDE, m_lordaeronShrineAlliance, m_lordaeronShrineHorde, m_towerBanners, m_towerOwner, m_towersAlliance, m_towersHorde, m_towerWorldState, plaguelandsTowerBuffs, OutdoorPvP::RespawnGO(), OutdoorPvP::SendUpdateWorldState(), OutdoorPvP::SetBannerVisual(), OutdoorPvP::SetGraveYardLinkTeam(), TEAM_INVALID, TEAM_NONE, TOWER_ID_CROWNGUARD, TOWER_ID_EASTWALL, TOWER_ID_NORTHPASS, TOWER_ID_PLAGUEWOOD, UnsummonFlightMaster(), UnsummonSoldiers(), WORLD_STATE_ADD, WORLD_STATE_EP_TOWER_COUNT_ALLIANCE, WORLD_STATE_EP_TOWER_COUNT_HORDE, and WORLD_STATE_REMOVE.
Referenced by HandleEvent().
SendRemoveWorldStates()
void OutdoorPvPEP::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 53 of file OutdoorPvPEP.cpp.
References m_towerWorldState, Player::SendUpdateWorldState(), and WORLD_STATE_REMOVE.
UnsummonFlightMaster()
void OutdoorPvPEP::UnsummonFlightMaster (const WorldObject * objRef) private
Definition at line 350 of file OutdoorPvPEP.cpp.
References Map::GetCreature(), WorldObject::GetMap(), and m_flightMaster.
Referenced by ProcessCaptureEvent().
UnsummonSoldiers()
void OutdoorPvPEP::UnsummonSoldiers (const WorldObject * objRef) private
Definition at line 357 of file OutdoorPvPEP.cpp.
References Map::GetCreature(), WorldObject::GetMap(), and m_soldiers.
Referenced by ProcessCaptureEvent().
Field Documentation
m_flightMaster
ObjectGuid OutdoorPvPEP::m_flightMaster private
Definition at line 237 of file OutdoorPvPEP.h.
Referenced by HandleCreatureCreate(), and UnsummonFlightMaster().
m_lordaeronShrineAlliance
ObjectGuid OutdoorPvPEP::m_lordaeronShrineAlliance private
Definition at line 238 of file OutdoorPvPEP.h.
Referenced by HandleGameObjectCreate(), and ProcessCaptureEvent().
m_lordaeronShrineHorde
ObjectGuid OutdoorPvPEP::m_lordaeronShrineHorde private
Definition at line 239 of file OutdoorPvPEP.h.
Referenced by HandleGameObjectCreate(), and ProcessCaptureEvent().
m_soldiers
GuidList OutdoorPvPEP::m_soldiers private
Definition at line 241 of file OutdoorPvPEP.h.
Referenced by HandleCreatureCreate(), and UnsummonSoldiers().
m_towerBanners
GuidList OutdoorPvPEP::m_towerBanners[MAX_EP_TOWERS] private
Definition at line 243 of file OutdoorPvPEP.h.
Referenced by InitBanner(), and ProcessCaptureEvent().
m_towerOwner
Team OutdoorPvPEP::m_towerOwner[MAX_EP_TOWERS] private
Definition at line 232 of file OutdoorPvPEP.h.
Referenced by HandleCreatureCreate(), HandleEvent(), InitBanner(), OutdoorPvPEP(), and ProcessCaptureEvent().
m_towersAlliance
uint8 OutdoorPvPEP::m_towersAlliance private
Definition at line 234 of file OutdoorPvPEP.h.
Referenced by FillInitialWorldStates(), HandlePlayerEnterZone(), and ProcessCaptureEvent().
m_towersHorde
uint8 OutdoorPvPEP::m_towersHorde private
Definition at line 235 of file OutdoorPvPEP.h.
Referenced by FillInitialWorldStates(), HandlePlayerEnterZone(), and ProcessCaptureEvent().
m_towerWorldState
uint32 OutdoorPvPEP::m_towerWorldState[MAX_EP_TOWERS] private
Definition at line 233 of file OutdoorPvPEP.h.
Referenced by FillInitialWorldStates(), OutdoorPvPEP(), ProcessCaptureEvent(), and SendRemoveWorldStates().
The documentation for this class was generated from the following files:
OutdoorPvPEP.h
OutdoorPvPEP.cpp