CMaNGOS_WoTLK: HostileRefManager Class Reference
HostileRefManager Class Reference
#include <HostileRefManager.h>
Public Member Functions
HostileRefManager (Unit *owner)
~HostileRefManager ()
Unit * getOwner () const
void threatAssist (Unit *victim, float threat, SpellEntry const *threatSpell=nullptr, bool singleTarget=false, bool ignoreTimer=false)
void threatTemporaryFade (Unit *victim, float threat, bool apply)
void addThreatPercent (int32 threatPercent)
void deleteReferences ()
void deleteReferencesForFaction (uint32 faction)
HostileReference * getFirst ()
void updateThreatTables ()
void setOnlineOfflineState (bool isOnline)
void updateOnlineOfflineState (bool pIsOnline)
void setOnlineOfflineState (Unit *victim, bool isOnline)
void deleteReference (Unit *victim)
void SetThreatRedirection (ObjectGuid guid, uint32 pct, uint32 spellId)
void ResetThreatRedirection (uint32 spellId)
std::map< uint32, RedirectionData > const & GetThreatRedirectionData () const
Unit * GetThreatRedirectionTarget (uint32 spellId) const
void HandleSuppressed (bool apply, bool immunity=false)
Public Member Functions inherited from RefManager< Unit, ThreatManager >
RefManager ()
virtual ~RefManager ()
Reference< Unit, ThreatManager > * getFirst ()
Reference< Unit, ThreatManager > const * getFirst () const
Reference< Unit, ThreatManager > * getLast ()
Reference< Unit, ThreatManager > const * getLast () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
iterator rbegin ()
iterator rend ()
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Private Attributes
Unit * iOwner
std::map< uint32, RedirectionData > m_redirectionData
Additional Inherited Members
Public Types inherited from RefManager< Unit, ThreatManager >
typedef LinkedListHead::Iterator< Reference< Unit, ThreatManager > > iterator
typedef LinkedListHead::Iterator< Reference< Unit, ThreatManager > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Detailed Description
Definition at line 41 of file HostileRefManager.h.
Constructor & Destructor Documentation
HostileRefManager()
HostileRefManager::HostileRefManager (Unit * owner) explicit
Definition at line 27 of file HostileRefManager.cpp.
~HostileRefManager()
HostileRefManager::~HostileRefManager ()
Definition at line 31 of file HostileRefManager.cpp.
References deleteReferences().
Member Function Documentation
addThreatPercent()
void HostileRefManager::addThreatPercent (int32 threatPercent)
Definition at line 74 of file HostileRefManager.cpp.
References HostileReference::addThreatPercent(), getFirst(), and HostileReference::next().
Referenced by Spell::EffectSanctuary(), and Unit::SetFeignDeath().
deleteReference()
void HostileRefManager::deleteReference (Unit * victim)
Definition at line 177 of file HostileRefManager.cpp.
References getFirst(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Player::BeforeVisibilityDestroy(), npc_dawnblade_blood_knight::ReceiveAIEvent(), Unit::TakeCharmOf(), and Unit::TakePossessOf().
deleteReferences()
void HostileRefManager::deleteReferences ()
Definition at line 144 of file HostileRefManager.cpp.
References getFirst(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Unit::DeleteThreatList(), WorldSession::LogoutPlayer(), and ~HostileRefManager().
deleteReferencesForFaction()
void HostileRefManager::deleteReferencesForFaction (uint32 faction)
Definition at line 159 of file HostileRefManager.cpp.
References FactionTemplateEntry::faction, Unit::GetFactionTemplateEntry(), getFirst(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), HostileReference::next(), and HostileReference::removeReference().
Referenced by Unit::StopAttackFaction().
getFirst()
HostileReference * HostileRefManager::getFirst ()
Definition at line 230 of file HostileRefManager.cpp.
References RefManager< TO, FROM >::getFirst().
Referenced by addThreatPercent(), deleteReference(), deleteReferences(), deleteReferencesForFaction(), setOnlineOfflineState(), threatAssist(), threatTemporaryFade(), PlayerbotAI::UpdateAttackersForTarget(), and updateThreatTables().
getOwner()
Unit* HostileRefManager::getOwner () const inline
Definition at line 47 of file HostileRefManager.h.
References iOwner.
Referenced by threatAssist().
GetThreatRedirectionData()
std::map<uint32, RedirectionData> const& HostileRefManager::GetThreatRedirectionData () const inline
Definition at line 82 of file HostileRefManager.h.
References m_redirectionData.
Referenced by ThreatManager::addThreat().
GetThreatRedirectionTarget()
Unit * HostileRefManager::GetThreatRedirectionTarget (uint32 spellId) const
Definition at line 203 of file HostileRefManager.cpp.
References WorldObject::GetMap(), Map::GetUnit(), iOwner, and m_redirectionData.
Referenced by Aura::HandleAuraDummy(), and Unit::HandleDummyAuraProc().
HandleSuppressed()
void HostileRefManager::HandleSuppressed (bool apply, bool immunity = false)
Definition at line 235 of file HostileRefManager.cpp.
References ByteConverter::apply(), Unit::GetMainAttackSchoolMask(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), Reference< TO, FROM >::getTarget(), Unit::IsImmuneToDamage(), Unit::IsSuppressedTarget(), HostileReference::SetHostileState(), HostileReference::SetSuppressabilityToggle(), and STATE_SUPPRESSED.
Referenced by Aura::HandleAuraModDmgImmunity(), Aura::HandleAuraModSchoolImmunity(), Aura::HandleAuraModStun(), Aura::HandleModConfuse(), and Aura::HandleModFear().
ResetThreatRedirection()
void HostileRefManager::ResetThreatRedirection (uint32 spellId)
Definition at line 198 of file HostileRefManager.cpp.
References m_redirectionData.
Referenced by Aura::HandleAuraDummy(), and Aura::HandleAuraProcTriggerSpell().
setOnlineOfflineState() [1/2]
void HostileRefManager::setOnlineOfflineState (bool isOnline)
Definition at line 106 of file HostileRefManager.cpp.
References getFirst(), HostileReference::next(), and HostileReference::setOnlineOfflineState().
Referenced by ShadowOfDeath::OnApply(), and updateOnlineOfflineState().
setOnlineOfflineState() [2/2]
void HostileRefManager::setOnlineOfflineState (Unit * victim, bool isOnline)
Definition at line 215 of file HostileRefManager.cpp.
References getFirst(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), HostileReference::next(), and HostileReference::setOnlineOfflineState().
SetThreatRedirection()
void HostileRefManager::SetThreatRedirection (ObjectGuid guid, uint32 pct, uint32 spellId)
Definition at line 193 of file HostileRefManager.cpp.
References m_redirectionData.
Referenced by Spell::EffectRedirectThreat().
threatAssist()
void HostileRefManager::threatAssist (Unit * victim, float threat, SpellEntry const * threatSpell = nullptr, bool singleTarget = false, bool ignoreTimer = false)
Definition at line 41 of file HostileRefManager.cpp.
References ThreatManager::addThreat(), Unit::CanAttack(), Unit::CanEnterCombat(), Unit::GetCombatManager(), getFirst(), getOwner(), ThreatManager::getOwner(), Reference< TO, FROM >::getSource(), GetSpellSchoolMask(), SpellEntry::HasAttribute(), Unit::IsCrowdControlled(), HostileReference::next(), SPELL_ATTR_EX2_NO_INITIAL_THREAT, SPELL_ATTR_EX4_NO_HELPFUL_THREAT, SPELL_ATTR_EX_NO_THREAT, SPELL_SCHOOL_MASK_NORMAL, and CombatManager::TriggerCombatTimer().
Referenced by Unit::CasterHitTargetWithSpell(), Spell::DoAllEffectOnTarget(), Unit::EnergizeBySpell(), Spell::HandleThreatSpells(), and Aura::PeriodicTick().
threatTemporaryFade()
void HostileRefManager::threatTemporaryFade (Unit * victim, float threat, bool apply)
Definition at line 84 of file HostileRefManager.cpp.
References ByteConverter::apply(), getFirst(), HostileReference::getThreat(), HostileReference::next(), HostileReference::resetFadeoutThreatReduction(), and HostileReference::setFadeoutThreatReduction().
Referenced by Aura::HandleAuraModTotalThreat().
updateOnlineOfflineState()
void HostileRefManager::updateOnlineOfflineState (bool pIsOnline)
Definition at line 116 of file HostileRefManager.cpp.
References iOwner, Unit::IsFeigningDeathSuccessfully(), Unit::IsInCombat(), and setOnlineOfflineState().
Referenced by Player::OnTaxiFlightSplineEnd(), Player::OnTaxiFlightSplineStart(), and Unit::SetFeignDeath().
updateThreatTables()
void HostileRefManager::updateThreatTables ()
Definition at line 130 of file HostileRefManager.cpp.
References getFirst(), HostileReference::next(), and HostileReference::updateOnlineStatus().
Referenced by Player::SetEnvironmentFlags().
Field Documentation
iOwner
Unit* HostileRefManager::iOwner private
Definition at line 89 of file HostileRefManager.h.
Referenced by getOwner(), GetThreatRedirectionTarget(), and updateOnlineOfflineState().
m_redirectionData
std::map<uint32, RedirectionData> HostileRefManager::m_redirectionData private
Definition at line 91 of file HostileRefManager.h.
Referenced by GetThreatRedirectionData(), GetThreatRedirectionTarget(), ResetThreatRedirection(), and SetThreatRedirection().
The documentation for this class was generated from the following files:
HostileRefManager.h
HostileRefManager.cpp