CMaNGOS_WoTLK: MapReference Class Reference
MapReference Class Reference
#include <MapReference.h>
Public Member Functions
MapReference ()
~MapReference ()
MapReference * next ()
MapReference const * next () const
MapReference * nockeck_prev ()
MapReference const * nocheck_prev () const
Public Member Functions inherited from Reference< Map, Player >
Reference ()
virtual ~Reference ()
void link (Map *toObj, Player *fromObj)
void unlink ()
void invalidate ()
bool isValid () const
Reference< Map, Player > * next ()
Reference< Map, Player > const * next () const
Reference< Map, Player > * prev ()
Reference< Map, Player > const * prev () const
Reference< Map, Player > * nocheck_next ()
Reference< Map, Player > const * nocheck_next () const
Reference< Map, Player > * nocheck_prev ()
Reference< Map, Player > const * nocheck_prev () const
Map * operator-> () const
Map * getTarget () const
Player * getSource () const
Public Member Functions inherited from LinkedListElement
LinkedListElement ()
~LinkedListElement ()
bool hasNext () const
bool hasPrev () const
bool isInList () const
LinkedListElement * next ()
LinkedListElement const * next () const
LinkedListElement * prev ()
LinkedListElement const * prev () const
LinkedListElement * nocheck_next ()
LinkedListElement const * nocheck_next () const
LinkedListElement * nocheck_prev ()
LinkedListElement const * nocheck_prev () const
void delink ()
void insertBefore (LinkedListElement *pElem)
void insertAfter (LinkedListElement *pElem)
Protected Member Functions
void targetObjectBuildLink () override
void targetObjectDestroyLink () override
void sourceObjectDestroyLink () override
Detailed Description
Definition at line 25 of file MapReference.h.
Constructor & Destructor Documentation
MapReference()
MapReference::MapReference () inline
Definition at line 45 of file MapReference.h.
~MapReference()
MapReference::~MapReference () inline
Definition at line 46 of file MapReference.h.
References Reference< Map, Player >::unlink().
Member Function Documentation
next() [1/2]
MapReference* MapReference::next () inline
Definition at line 47 of file MapReference.h.
References Reference< TO, FROM >::next().
next() [2/2]
MapReference const* MapReference::next () const inline
Definition at line 48 of file MapReference.h.
References Reference< TO, FROM >::next().
nocheck_prev()
MapReference const* MapReference::nocheck_prev () const inline
Definition at line 50 of file MapReference.h.
References Reference< TO, FROM >::nocheck_prev().
Referenced by Map::Remove().
nockeck_prev()
MapReference* MapReference::nockeck_prev () inline
Definition at line 49 of file MapReference.h.
References Reference< TO, FROM >::nocheck_prev().
sourceObjectDestroyLink()
void MapReference::sourceObjectDestroyLink () inline override protected virtual
Implements Reference< Map, Player >.
Definition at line 39 of file MapReference.h.
References LinkedListHead::decSize(), Reference< Map, Player >::getTarget(), and Map::m_mapRefManager.
targetObjectBuildLink()
void MapReference::targetObjectBuildLink () inline override protected virtual
Implements Reference< Map, Player >.
Definition at line 28 of file MapReference.h.
References Reference< Map, Player >::getTarget(), LinkedListHead::incSize(), LinkedListHead::insertFirst(), and Map::m_mapRefManager.
targetObjectDestroyLink()
void MapReference::targetObjectDestroyLink () inline override protected virtual
Implements Reference< Map, Player >.
Definition at line 34 of file MapReference.h.
References LinkedListHead::decSize(), Reference< Map, Player >::getTarget(), Reference< Map, Player >::isValid(), and Map::m_mapRefManager.
The documentation for this class was generated from the following file:
MapReference.h