CMaNGOS_WoTLK: instance_gundrak Class Reference
instance_gundrak Class Reference
#include <gundrak.h>
Public Member Functions
instance_gundrak (Map *pMap)
~instance_gundrak ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnPlayerDeath (Player *) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
ObjectGuid SelectRandomSladranTargetGuid ()
void SetLessRabiAchievementCriteria (bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoAltarVisualEffect (uint8 uiType)
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
TypeTimerMap m_mAltarInProgress
TypeTimerMap m_mBeamInProgress
TypeTimerMap m_mKeyInProgress
GuidList m_luiStalkerGUIDs
GuidList m_lSummonTargetsGuids
GuidVector m_vStalkerCasterGuids
GuidVector m_vStalkerTargetGuids
GuidSet m_sColossusMojosGuids
GuidSet m_sRuinsDwelerGuids
bool m_bLessRabi
std::set< uint32 > m_uisShareLoveAchievPlayers
std::set< uint32 > m_uisWhySnakesAchievPlayers
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 74 of file gundrak.h.
Constructor & Destructor Documentation
instance_gundrak()
instance_gundrak::instance_gundrak (Map * pMap)
Definition at line 45 of file gundrak.cpp.
References Initialize().
~instance_gundrak()
instance_gundrak::~instance_gundrak () inline
Definition at line 78 of file gundrak.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_gundrak::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 293 of file gundrak.cpp.
References ACHIEV_CRIT_LESS_RABI, ACHIEV_CRIT_SHARE_LOVE, ACHIEV_CRIT_WHY_SNAKES, Object::GetGUIDLow(), m_bLessRabi, m_uisShareLoveAchievPlayers, m_uisWhySnakesAchievPlayers, and MIN_LOVE_SHARE_PLAYERS.
DoAltarVisualEffect()
void instance_gundrak::DoAltarVisualEffect (uint8 uiType) protected
Definition at line 344 of file gundrak.cpp.
References Unit::CastSpell(), Map::GetCreature(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ALTAR_OF_COLOSSUS, InstanceData::instance, m_luiStalkerGUIDs, m_vStalkerCasterGuids, m_vStalkerTargetGuids, sortFromEastToWest(), SPELL_BEAM_ELEMENTAL, SPELL_BEAM_MAMMOTH, SPELL_BEAM_SNAKE, TRIGGERED_NONE, TYPE_COLOSSUS, TYPE_MOORABI, and TYPE_SLADRAN.
Referenced by Update().
GetData()
uint32 instance_gundrak::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 285 of file gundrak.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnPlayerDeath().
Initialize()
void instance_gundrak::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 51 of file gundrak.cpp.
References m_auiEncounter, m_vStalkerCasterGuids, and m_vStalkerTargetGuids.
Referenced by instance_gundrak().
Load()
void instance_gundrak::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 171 of file gundrak.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, OUT_LOAD_INST_DATA_FAIL, TYPE_COLOSSUS, TYPE_ECK, TYPE_GALDARAH, TYPE_MOORABI, and TYPE_SLADRAN.
OnCreatureCreate()
void instance_gundrak::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 59 of file gundrak.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionZ(), m_lSummonTargetsGuids, m_luiStalkerGUIDs, ScriptedInstance::m_npcEntryGuidStore, m_sColossusMojosGuids, m_sRuinsDwelerGuids, NPC_COLOSSUS, NPC_ECK, NPC_ELEMENTAL, NPC_INVISIBLE_STALKER, NPC_LIVIN_MOJO, NPC_RUINS_DWELLER, NPC_SLADRAN, and NPC_SLADRAN_SUMMON_T.
OnCreatureDeath()
void instance_gundrak::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 138 of file gundrak.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_sRuinsDwelerGuids, NPC_ECK, NPC_RUINS_DWELLER, SetData(), and TYPE_ECK.
OnCreatureEnterCombat()
void instance_gundrak::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 311 of file gundrak.cpp.
References Map::GetCreature(), Object::GetEntry(), Object::GetObjectGuid(), InstanceData::instance, m_sColossusMojosGuids, and NPC_LIVIN_MOJO.
OnObjectCreate()
void instance_gundrak::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 89 of file gundrak.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ALTAR_OF_COLOSSUS, GO_ALTAR_OF_MOORABI, GO_ALTAR_OF_SLADRAN, GO_BRIDGE, GO_COLLISION, GO_ECK_DOOR, GO_ECK_UNDERWATER_DOOR, GO_EXIT_DOOR_L, GO_EXIT_DOOR_R, GO_FLAG_NO_INTERACT, GO_GALDARAH_DOOR, GO_MAMMOTH_KEY, GO_RHINO_KEY, GO_SNAKE_KEY, GO_STATE_ACTIVE, GO_TROLL_KEY, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), GameObject::SetGoState(), TYPE_COLOSSUS, TYPE_ECK, TYPE_GALDARAH, TYPE_MOORABI, and TYPE_SLADRAN.
OnPlayerDeath()
void instance_gundrak::OnPlayerDeath (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 165 of file gundrak.cpp.
References Unit::CastSpell(), GetData(), IN_PROGRESS, TRIGGERED_OLD_TRIGGERED, and TYPE_SLADRAN.
Save()
const char* instance_gundrak::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 92 of file gundrak.h.
References m_strInstData.
SelectRandomSladranTargetGuid()
ObjectGuid instance_gundrak::SelectRandomSladranTargetGuid ()
Definition at line 328 of file gundrak.cpp.
References m_lSummonTargetsGuids, and urand().
Referenced by boss_sladranAI::ExecuteAction().
SetData()
void instance_gundrak::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 193 of file gundrak.cpp.
References debug_log(), DONE, ScriptedInstance::DoUseDoorOrButton(), FAIL, GAMEOBJECT_FLAGS, Map::GetCreature(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ALTAR_OF_COLOSSUS, GO_ALTAR_OF_MOORABI, GO_ALTAR_OF_SLADRAN, GO_ECK_DOOR, GO_ECK_UNDERWATER_DOOR, GO_EXIT_DOOR_L, GO_EXIT_DOOR_R, GO_FLAG_NO_INTERACT, GO_GALDARAH_DOOR, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, m_mAltarInProgress, m_sColossusMojosGuids, m_strInstData, m_uisShareLoveAchievPlayers, m_uisWhySnakesAchievPlayers, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), script_error_log(), SetLessRabiAchievementCriteria(), SPECIAL, TIMER_VISUAL_ALTAR, TYPE_ACHIEV_SHARE_LOVE, TYPE_ACHIEV_WHY_SNAKES, TYPE_COLOSSUS, TYPE_ECK, TYPE_GALDARAH, TYPE_MOORABI, and TYPE_SLADRAN.
Referenced by boss_moorabiAI::Aggro(), boss_moorabiAI::JustDied(), SnakeWrap::OnApply(), and OnCreatureDeath().
SetLessRabiAchievementCriteria()
void instance_gundrak::SetLessRabiAchievementCriteria (bool bIsMet) inline
Definition at line 97 of file gundrak.h.
References m_bLessRabi.
Referenced by SetData(), and boss_moorabiAI::SpellHitTarget().
Update()
void instance_gundrak::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 402 of file gundrak.cpp.
References DoAltarVisualEffect(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::DoUseOpenableObject(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_BRIDGE, GO_COLLISION, GO_MAMMOTH_KEY, GO_RHINO_KEY, GO_SNAKE_KEY, GO_STATE_ACTIVE_ALTERNATIVE, GO_TROLL_KEY, m_auiEncounter, m_mAltarInProgress, m_mBeamInProgress, m_mKeyInProgress, SPECIAL, TIMER_VISUAL_BEAM, TIMER_VISUAL_KEY, TYPE_COLOSSUS, TYPE_MOORABI, and TYPE_SLADRAN.
Field Documentation
m_auiEncounter
uint32 instance_gundrak::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 104 of file gundrak.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), SetData(), and Update().
m_bLessRabi
bool instance_gundrak::m_bLessRabi protected
Definition at line 118 of file gundrak.h.
Referenced by CheckAchievementCriteriaMeet(), and SetLessRabiAchievementCriteria().
m_lSummonTargetsGuids
GuidList instance_gundrak::m_lSummonTargetsGuids protected
Definition at line 112 of file gundrak.h.
Referenced by OnCreatureCreate(), and SelectRandomSladranTargetGuid().
m_luiStalkerGUIDs
GuidList instance_gundrak::m_luiStalkerGUIDs protected
Definition at line 111 of file gundrak.h.
Referenced by DoAltarVisualEffect(), and OnCreatureCreate().
m_mAltarInProgress
TypeTimerMap instance_gundrak::m_mAltarInProgress protected
Definition at line 107 of file gundrak.h.
Referenced by SetData(), and Update().
m_mBeamInProgress
TypeTimerMap instance_gundrak::m_mBeamInProgress protected
Definition at line 108 of file gundrak.h.
Referenced by Update().
m_mKeyInProgress
TypeTimerMap instance_gundrak::m_mKeyInProgress protected
Definition at line 109 of file gundrak.h.
Referenced by Update().
m_sColossusMojosGuids
GuidSet instance_gundrak::m_sColossusMojosGuids protected
Definition at line 115 of file gundrak.h.
Referenced by OnCreatureCreate(), OnCreatureEnterCombat(), and SetData().
m_sRuinsDwelerGuids
GuidSet instance_gundrak::m_sRuinsDwelerGuids protected
Definition at line 116 of file gundrak.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_strInstData
std::string instance_gundrak::m_strInstData protected
Definition at line 105 of file gundrak.h.
Referenced by Save(), and SetData().
m_uisShareLoveAchievPlayers
std::set<uint32> instance_gundrak::m_uisShareLoveAchievPlayers protected
Definition at line 120 of file gundrak.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_uisWhySnakesAchievPlayers
std::set<uint32> instance_gundrak::m_uisWhySnakesAchievPlayers protected
Definition at line 121 of file gundrak.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_vStalkerCasterGuids
GuidVector instance_gundrak::m_vStalkerCasterGuids protected
Definition at line 113 of file gundrak.h.
Referenced by DoAltarVisualEffect(), and Initialize().
m_vStalkerTargetGuids
GuidVector instance_gundrak::m_vStalkerTargetGuids protected
Definition at line 114 of file gundrak.h.
Referenced by DoAltarVisualEffect(), and Initialize().
The documentation for this class was generated from the following files:
gundrak.h
gundrak.cpp