CMaNGOS_WoTLK: instance_ulduar Class Reference
instance_ulduar Class Reference
#include <ulduar.h>
Public Member Functions
instance_ulduar (Map *pMap)
~instance_ulduar ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnPlayerDeath (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnObjectSpawn (GameObject *go) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
void SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
bool CheckConditionCriteriaMeet (Player const *pPlayer, uint32 uiInstanceConditionId, WorldObject const *pConditionSource, uint32 conditionSourceType) const override
void DoSpawnThorimNpcs (Player *pSummoner)
void DoProcessShatteredEvent ()
ObjectGuid GetKoloRubbleStalker (bool bRightSide)
ObjectGuid GetVezaxBunnyGuid (bool bAnimus)
void GetDefenderGuids (GuidList &lDefenders) const
void GetEngineersGuids (GuidList &lEngineers) const
void GetTrappersGuids (GuidList &lTrappers) const
void GetHarpoonsGuids (GuidVector &vHarpoons) const
void GetToyPileGuids (GuidVector &vToyPiles) const
void GetThorimBunniesGuids (GuidList &lBunnies, bool bUpper)
void GetThunderOrbsGuids (GuidList &lOrbs) const
void GetSmashTargetsGuids (GuidList &lTargets, bool bLeft)
void GetOminousCloudGuids (GuidList &lClouds) const
void SetTramRotateTimer ()
void Update (uint32 uiDiff)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void SpawnFriendlyKeeper (uint32 uiWho)
void SpawnKeeperHelper (uint32 uiWho)
void DoSpawnHodirNpcs (Player *pSummoner)
void DoOpenMadnessDoorIfCan ()
void DoCallLeviathanHelp ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
std::string m_strInstData
uint32 m_auiEncounter [MAX_ENCOUNTER]
uint32 m_auiHardBoss [HARD_MODE_ENCOUNTER]
uint32 m_auiUlduarKeepers [KEEPER_ENCOUNTER]
uint32 m_auiUlduarTowers [KEEPER_ENCOUNTER]
bool m_abAchievCriteria [MAX_SPECIAL_ACHIEV_CRITS]
uint32 m_auiAchievEncounter [MAX_ACHIEV_ENCOUNTER]
bool m_bHelpersLoaded
bool m_bTramAtCenter
uint32 m_uiAlgalonTimer
uint32 m_uiYoggResetTimer
uint32 m_uiShatterAchievTimer
uint32 m_uiGauntletStatus
uint32 m_uiStairsSpawnTimer
uint32 m_uiTramRotateTimer
uint8 m_uiSlayedArenaMobs
ObjectGuid m_leftKoloStalkerGuid
ObjectGuid m_rightKoloStalkerGuid
ObjectGuid m_animusVezaxBunnyGuid
ObjectGuid m_vaporVezaxBunnyGuid
GuidVector m_vToyPileGuidVector
GuidVector m_vBrokenHarpoonsGuids
GuidList m_lEngineersGuids
GuidList m_lTrappersGuids
GuidList m_lDefendersGuids
GuidList m_lHarpoonDummyGuids
GuidList m_lRepairedHarpoonsGuids
GuidList m_lThorimBunniesGuids
GuidList m_lUpperBunniesGuids
GuidList m_lUpperThunderOrbsGuids
GuidList m_lLeftHandBunniesGuids
GuidList m_lRightHandBunniesGuids
GuidList m_lOminousCloudsGuids
GuidSet m_sColossusGuidSet
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Detailed Description
Definition at line 580 of file ulduar.h.
Constructor & Destructor Documentation
instance_ulduar()
instance_ulduar::instance_ulduar (Map * pMap)
Definition at line 75 of file ulduar.cpp.
References Initialize().
~instance_ulduar()
instance_ulduar::~instance_ulduar () inline
Definition at line 584 of file ulduar.h.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_ulduar::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 1379 of file ulduar.cpp.
References ACHIEV_CRIT_ALONE_DARK_H, ACHIEV_CRIT_ALONE_DARK_N, ACHIEV_CRIT_BACK_NATURE_H, ACHIEV_CRIT_BACK_NATURE_N, ACHIEV_CRIT_BRUNDIR_H, ACHIEV_CRIT_BRUNDIR_N, ACHIEV_CRIT_CAT_LADY_H, ACHIEV_CRIT_CAT_LADY_N, ACHIEV_CRIT_CHAMP_AURIAYA, ACHIEV_CRIT_CHAMP_COUNCIL, ACHIEV_CRIT_CHAMP_FREYA, ACHIEV_CRIT_CHAMP_HODIR, ACHIEV_CRIT_CHAMP_IGNIS, ACHIEV_CRIT_CHAMP_KOLO, ACHIEV_CRIT_CHAMP_LEVI, ACHIEV_CRIT_CHAMP_MIMIRON, ACHIEV_CRIT_CHAMP_RAZOR, ACHIEV_CRIT_CHAMP_THORIM, ACHIEV_CRIT_CHAMP_VEZAX, ACHIEV_CRIT_CHAMP_XT, ACHIEV_CRIT_CHAMP_YOGG, ACHIEV_CRIT_CHEESE_H, ACHIEV_CRIT_CHEESE_N, ACHIEV_CRIT_CONQ_AURIAYA, ACHIEV_CRIT_CONQ_COUNCIL, ACHIEV_CRIT_CONQ_FREYA, ACHIEV_CRIT_CONQ_HODIR, ACHIEV_CRIT_CONQ_IGNIS, ACHIEV_CRIT_CONQ_KOLO, ACHIEV_CRIT_CONQ_LEVI, ACHIEV_CRIT_CONQ_MIMIRON, ACHIEV_CRIT_CONQ_RAZOR, ACHIEV_CRIT_CONQ_THORIM, ACHIEV_CRIT_CONQ_VEZAX, ACHIEV_CRIT_CONQ_XT, ACHIEV_CRIT_CONQ_YOGG, ACHIEV_CRIT_COOL_FRIENDS_H, ACHIEV_CRIT_COOL_FRIENDS_N, ACHIEV_CRIT_DISARMED_H, ACHIEV_CRIT_DISARMED_N, ACHIEV_CRIT_DRIVE_CRAZY_H, ACHIEV_CRIT_DRIVE_CRAZY_N, ACHIEV_CRIT_FIREFIGHTER_H, ACHIEV_CRIT_FIREFIGHTER_N, ACHIEV_CRIT_HEARTBREAKER_H, ACHIEV_CRIT_HEARTBREAKER_N, ACHIEV_CRIT_KNOCK_1_H, ACHIEV_CRIT_KNOCK_1_N, ACHIEV_CRIT_KNOCK_2_H, ACHIEV_CRIT_KNOCK_2_N, ACHIEV_CRIT_KNOCK_3_H, ACHIEV_CRIT_KNOCK_3_N, ACHIEV_CRIT_LIGHTNING_H, ACHIEV_CRIT_LIGHTNING_N, ACHIEV_CRIT_LOOKS_KILL_H, ACHIEV_CRIT_LOOKS_KILL_N, ACHIEV_CRIT_LOSE_ILLUSION_H, ACHIEV_CRIT_LOSE_ILLUSION_N, ACHIEV_CRIT_MOLGEIM_H, ACHIEV_CRIT_MOLGEIM_N, ACHIEV_CRIT_NERF_ENG_H, ACHIEV_CRIT_NERF_ENG_N, ACHIEV_CRIT_NINE_LIVES_H, ACHIEV_CRIT_NINE_LIVES_N, ACHIEV_CRIT_ONE_LIGHT_H, ACHIEV_CRIT_ONE_LIGHT_N, ACHIEV_CRIT_OPEN_ARMS_H, ACHIEV_CRIT_OPEN_ARMS_N, ACHIEV_CRIT_ORB_BOMB_H, ACHIEV_CRIT_ORB_BOMB_N, ACHIEV_CRIT_ORB_DEV_H, ACHIEV_CRIT_ORB_DEV_N, ACHIEV_CRIT_ORB_NUKED_H, ACHIEV_CRIT_ORB_NUKED_N, ACHIEV_CRIT_ORBITUARY_H, ACHIEV_CRIT_ORBITUARY_N, ACHIEV_CRIT_QUICK_SHAVE_H, ACHIEV_CRIT_QUICK_SHAVE_N, ACHIEV_CRIT_RARE_CACHE_H, ACHIEV_CRIT_RARE_CACHE_N, ACHIEV_CRIT_RUBBLE_ROLL_H, ACHIEV_CRIT_RUBBLE_ROLL_N, ACHIEV_CRIT_SARONITE_H, ACHIEV_CRIT_SARONITE_N, ACHIEV_CRIT_SHADOWDODGER_H, ACHIEV_CRIT_SHADOWDODGER_N, ACHIEV_CRIT_SHATTERED_H, ACHIEV_CRIT_SHATTERED_N, ACHIEV_CRIT_SHUTOUT_H, ACHIEV_CRIT_SHUTOUT_N, ACHIEV_CRIT_STEELBREAKER_H, ACHIEV_CRIT_STEELBREAKER_N, ACHIEV_CRIT_STUNNED_BRUND_H, ACHIEV_CRIT_STUNNED_BRUND_N, ACHIEV_CRIT_STUNNED_MOLG_H, ACHIEV_CRIT_STUNNED_MOLG_N, ACHIEV_CRIT_STUNNED_STEEL_H, ACHIEV_CRIT_STUNNED_STEEL_N, ACHIEV_CRIT_THREE_LIGHTS_H, ACHIEV_CRIT_THREE_LIGHTS_N, ACHIEV_CRIT_TWO_LIGHTS_H, ACHIEV_CRIT_TWO_LIGHTS_N, DONE, GetData(), m_abAchievCriteria, m_auiEncounter, SPECIAL, TYPE_ACHIEV_BACK_NATURE, TYPE_ACHIEV_BRUNDIR, TYPE_ACHIEV_CAT_LADY, TYPE_ACHIEV_CHEESE_FREEZE, TYPE_ACHIEV_COOL_FRIENDS, TYPE_ACHIEV_DISARMED, TYPE_ACHIEV_DRIVE_CRAZY, TYPE_ACHIEV_LIGHTNING, TYPE_ACHIEV_LOOKS_KILL, TYPE_ACHIEV_MOLGEIM, TYPE_ACHIEV_NERF_ENG, TYPE_ACHIEV_NINE_LIVES, TYPE_ACHIEV_OPEN_ARMS, TYPE_ACHIEV_QUICK_SHAVE, TYPE_ACHIEV_RUBBLE, TYPE_ACHIEV_SHADOWDODGER, TYPE_ACHIEV_SHATTERED, TYPE_ACHIEV_SHUTOUT, TYPE_ACHIEV_STEELBREAKER, TYPE_ACHIEV_STUNNED, TYPE_ASSEMBLY, TYPE_CHAMPION_FAILED, TYPE_FREYA_HARD, TYPE_HODIR_HARD, TYPE_LEVIATHAN_HARD, TYPE_MIMIRON_HARD, TYPE_THORIM_HARD, TYPE_VEZAX_HARD, TYPE_XT002_HARD, TYPE_YOGGSARON, and TYPE_YOGGSARON_HARD.
CheckConditionCriteriaMeet()
bool instance_ulduar::CheckConditionCriteriaMeet (Player const * pPlayer, uint32 uiInstanceConditionId, WorldObject const * pConditionSource, uint32 conditionSourceType) const override virtual
Reimplemented from InstanceData.
Definition at line 1051 of file ulduar.cpp.
References DONE, FAIL, GetData(), Object::GetEntry(), Object::GetGuidStr(), IN_PROGRESS, INSTANCE_CONDITION_ID_HARD_MODE, INSTANCE_CONDITION_ID_HARD_MODE_2, INSTANCE_CONDITION_ID_HARD_MODE_3, INSTANCE_CONDITION_ID_HARD_MODE_4, INSTANCE_CONDITION_ID_NORMAL_MODE, INSTANCE_CONDITION_ID_ULDUAR, NPC_LEVIATHAN, NPC_VEZAX, NPC_XT002, NPC_YOGGSARON, script_error_log(), SPECIAL, TYPE_LEVIATHAN, TYPE_LEVIATHAN_GAUNTLET, TYPE_LEVIATHAN_HARD, TYPE_VEZAX_HARD, TYPE_XT002_HARD, and TYPE_YOGGSARON_HARD.
DoCallLeviathanHelp()
void instance_ulduar::DoCallLeviathanHelp () protected
Definition at line 1542 of file ulduar.cpp.
References afReinforcementsHeroic, afReinforcementsNormal, ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Map::IsRegularDifficulty(), NPC_LEVIATHAN, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by OnPlayerEnter(), and SetData().
DoOpenMadnessDoorIfCan()
void instance_ulduar::DoOpenMadnessDoorIfCan () protected
Definition at line 501 of file ulduar.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), GO_ANCIENT_GATE, m_auiEncounter, TYPE_FREYA, TYPE_HODIR, TYPE_MIMIRON, and TYPE_THORIM.
Referenced by SetData().
DoProcessShatteredEvent()
void instance_ulduar::DoProcessShatteredEvent ()
Definition at line 1558 of file ulduar.cpp.
References m_uiShatterAchievTimer, SetSpecialAchievementCriteria(), and TYPE_ACHIEV_SHATTERED.
DoSpawnHodirNpcs()
void instance_ulduar::DoSpawnHodirNpcs (Player * pSummoner) protected
Definition at line 1567 of file ulduar.cpp.
References afHodirHelpersHeroic, afHodirHelpersNormal, ALLIANCE, DONE, GetData(), Player::GetTeam(), InstanceData::instance, Map::IsRegularDifficulty(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_HODIR.
Referenced by OnPlayerEnter(), and SetData().
DoSpawnThorimNpcs()
void instance_ulduar::DoSpawnThorimNpcs (Player * pSummoner)
Definition at line 1582 of file ulduar.cpp.
References afThorimSpawns, ALLIANCE, DONE, GetData(), Player::GetTeam(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_THORIM.
Referenced by boss_thorimAI::MoveInLineOfSight().
GetData()
uint32 instance_ulduar::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 1100 of file ulduar.cpp.
References ACHIEV_FREYA_CONSPEEDATORY, m_auiAchievEncounter, m_auiEncounter, m_auiHardBoss, m_auiUlduarKeepers, m_auiUlduarTowers, m_uiGauntletStatus, TYPE_ALGALON, TYPE_ALGALON_TIMER, TYPE_ASSEMBLY, TYPE_AURIAYA, TYPE_CHAMPION_FAILED, TYPE_FREYA, TYPE_FREYA_CONSPEEDATORY, TYPE_FREYA_HARD, TYPE_HODIR, TYPE_HODIR_HARD, TYPE_IGNIS, TYPE_KEEPER_FREYA, TYPE_KEEPER_HODIR, TYPE_KEEPER_MIMIRON, TYPE_KEEPER_THORIM, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_LEVIATHAN_GAUNTLET, TYPE_LEVIATHAN_HARD, TYPE_MIMIRON, TYPE_MIMIRON_HARD, TYPE_RAZORSCALE, TYPE_THORIM, TYPE_THORIM_HARD, TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, TYPE_TOWER_THORIM, TYPE_VEZAX, TYPE_VEZAX_HARD, TYPE_XT002, TYPE_XT002_HARD, TYPE_YOGGSARON, and TYPE_YOGGSARON_HARD.
Referenced by boss_algalonAI::Aggro(), boss_leviathan_mk2AI::Aggro(), boss_vx001AI::Aggro(), boss_aerial_unitAI::Aggro(), CheckAchievementCriteriaMeet(), CheckConditionCriteriaMeet(), boss_freyaAI::DamageTaken(), boss_thorimAI::DamageTaken(), boss_saraAI::DoInitialiseKeepers(), DoSpawnHodirNpcs(), DoSpawnThorimNpcs(), boss_flame_leviathanAI::FetchTowers(), GossipHello_go_ulduar_teleporter(), boss_mimironAI::JustDidDialogueStep(), boss_algalonAI::JustReachedHome(), boss_yogg_saronAI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), boss_aerial_unitAI::JustSummoned(), boss_thorimAI::MoveInLineOfSight(), boss_thorimAI::MovementInform(), OnCreatureDeath(), OnCreatureRespawn(), OnPlayerEnter(), boss_yogg_saronAI::Reset(), SetData(), Update(), boss_general_vezaxAI::UpdateAI(), and boss_xt_002AI::UpdateAI().
GetDefenderGuids()
void instance_ulduar::GetDefenderGuids (GuidList & lDefenders) const inline
Definition at line 615 of file ulduar.h.
References m_lDefendersGuids.
Referenced by npc_expedition_commanderAI::JustDidDialogueStep().
GetEngineersGuids()
void instance_ulduar::GetEngineersGuids (GuidList & lEngineers) const inline
Definition at line 616 of file ulduar.h.
References m_lEngineersGuids.
Referenced by boss_razorscaleAI::Aggro().
GetHarpoonsGuids()
void instance_ulduar::GetHarpoonsGuids (GuidVector & vHarpoons) const inline
Definition at line 618 of file ulduar.h.
References m_vBrokenHarpoonsGuids.
Referenced by boss_razorscaleAI::Aggro().
GetKoloRubbleStalker()
ObjectGuid instance_ulduar::GetKoloRubbleStalker (bool bRightSide) inline
Definition at line 612 of file ulduar.h.
References m_leftKoloStalkerGuid, and m_rightKoloStalkerGuid.
Referenced by boss_kologarnAI::SummonedCreatureJustDied().
GetOminousCloudGuids()
void instance_ulduar::GetOminousCloudGuids (GuidList & lClouds) const inline
Definition at line 623 of file ulduar.h.
References m_lOminousCloudsGuids.
Referenced by boss_saraAI::DamageTaken().
GetSmashTargetsGuids()
void instance_ulduar::GetSmashTargetsGuids (GuidList & lTargets, bool bLeft) inline
Definition at line 622 of file ulduar.h.
References m_lLeftHandBunniesGuids, and m_lRightHandBunniesGuids.
Referenced by npc_runic_colossusAI::SpellHit().
GetThorimBunniesGuids()
void instance_ulduar::GetThorimBunniesGuids (GuidList & lBunnies, bool bUpper) inline
Definition at line 620 of file ulduar.h.
References m_lThorimBunniesGuids, and m_lUpperBunniesGuids.
Referenced by boss_thorimAI::Aggro(), and boss_sifAI::ReceiveAIEvent().
GetThunderOrbsGuids()
void instance_ulduar::GetThunderOrbsGuids (GuidList & lOrbs) const inline
Definition at line 621 of file ulduar.h.
References m_lUpperThunderOrbsGuids.
Referenced by boss_thorimAI::Aggro().
GetToyPileGuids()
void instance_ulduar::GetToyPileGuids (GuidVector & vToyPiles) const inline
Definition at line 619 of file ulduar.h.
References m_vToyPileGuidVector.
Referenced by boss_heart_deconstructorAI::ReceiveAIEvent().
GetTrappersGuids()
void instance_ulduar::GetTrappersGuids (GuidList & lTrappers) const inline
Definition at line 617 of file ulduar.h.
References m_lTrappersGuids.
Referenced by boss_razorscaleAI::Aggro().
GetVezaxBunnyGuid()
ObjectGuid instance_ulduar::GetVezaxBunnyGuid (bool bAnimus) inline
Definition at line 613 of file ulduar.h.
References m_animusVezaxBunnyGuid, and m_vaporVezaxBunnyGuid.
Referenced by boss_general_vezaxAI::DoPrepareAnimusIfCan(), boss_general_vezaxAI::ReceiveAIEvent(), and boss_general_vezaxAI::UpdateAI().
Initialize()
void instance_ulduar::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 89 of file ulduar.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_abAchievCriteria, m_auiEncounter, m_auiHardBoss, m_auiUlduarKeepers, and m_auiUlduarTowers.
Referenced by instance_ulduar().
IsEncounterInProgress()
bool instance_ulduar::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 166 of file ulduar.cpp.
References IN_PROGRESS, m_auiEncounter, and TYPE_ALGALON.
Referenced by OnPlayerDeath().
JustDidDialogueStep()
void instance_ulduar::JustDidDialogueStep (int32) override protected virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 1591 of file ulduar.cpp.
References afLeviathanMovePos, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_LEVIATHAN_GATE, MOVE_RUN, NPC_BRONZEBEARD_RADIO, NPC_LEVIATHAN, SAY_PRE_LEVIATHAN_1, SAY_PRE_LEVIATHAN_2, and SAY_PRE_LEVIATHAN_3.
Load()
void instance_ulduar::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 1345 of file ulduar.cpp.
References ACHIEV_FREYA_CONSPEEDATORY, IN_PROGRESS, m_auiAchievEncounter, m_auiEncounter, m_auiUlduarKeepers, m_auiUlduarTowers, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_ulduar::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 176 of file ulduar.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_animusVezaxBunnyGuid, m_lDefendersGuids, m_leftKoloStalkerGuid, m_lEngineersGuids, m_lHarpoonDummyGuids, m_lLeftHandBunniesGuids, m_lOminousCloudsGuids, m_lRightHandBunniesGuids, m_lThorimBunniesGuids, m_lTrappersGuids, m_lUpperBunniesGuids, m_lUpperThunderOrbsGuids, ScriptedInstance::m_npcEntryGuidStore, m_rightKoloStalkerGuid, m_sColossusGuidSet, m_vaporVezaxBunnyGuid, m_vToyPileGuidVector, NPC_AERIAL_UNIT, NPC_ALEXSTRASZA, NPC_ALGALON, NPC_AURIAYA, NPC_BRANN_ALGALON, NPC_BRANN_ARCHIVUM, NPC_BRANN_BRONZEBEARD, NPC_BRUNDIR, NPC_COMPUTER, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRACH, NPC_ELDER_STONEBARK, NPC_EXPEDITION_COMMANDER, NPC_EXPEDITION_DEFENDER, NPC_EXPEDITION_ENGINEER, NPC_EXPEDITION_TRAPPER, NPC_EXPLORER_DELLORAH, NPC_FERAL_DEFENDER, NPC_FREYA, NPC_FREYA_ACHIEV_TRIGGER, NPC_FREYA_HELPER, NPC_GARONA, NPC_HEART_DECONSTRUCTOR, NPC_HODIR, NPC_HODIR_HELPER, NPC_IMMOLATED_CHAMPION, NPC_JORMUNGAR_BEHEMOTH, NPC_KING_LLANE, NPC_KOLOGARN, NPC_LEFT_ARM, NPC_LEFT_HAND_BUNNY, NPC_LEVIATHAN, NPC_LEVIATHAN_MK, NPC_LEVIATHAN_MK_TURRET, NPC_LICH_KING, NPC_MALYGOS, NPC_MIMIRON, NPC_MIMIRON_HELPER, NPC_MOLGEIM, NPC_NELTHARION, NPC_OMINOUS_CLOUD, NPC_ORBITAL_SUPPORT, NPC_RAZORSCALE, NPC_RAZORSCALE_CONTROLLER, NPC_RIGHT_ARM, NPC_RIGHT_HAND_BUNNY, NPC_RUBBLE_STALKER, NPC_RUNE_GIANT, NPC_RUNIC_COLOSSUS, NPC_SARA, NPC_SARONITE_ANIMUS, NPC_SIF, NPC_STEELBREAKER, NPC_THORIM, NPC_THORIM_COMBAT_TRIGGER, NPC_THORIM_EVENT_BUNNY, NPC_THORIM_HELPER, NPC_THUNDER_ORB, NPC_ULDUAR_COLOSSUS, NPC_VEZAX, NPC_VEZAX_BUNNY, NPC_VOICE_OF_YOGG, NPC_VX001, NPC_WORLD_TRIGGER_FLAMES, NPC_XT002, NPC_XT_TOY_PILE, NPC_YOGG_BRAIN, NPC_YOGGSARON, NPC_YOGGSARON_ILLUSION, and NPC_YSERA.
OnCreatureDeath()
void instance_ulduar::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 1252 of file ulduar.cpp.
References afLeviathanSpawnPos, Creature::AI(), AI_EVENT_CUSTOM_C, DONE, ScriptedInstance::DoUseDoorOrButton(), GetData(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_RUNED_STONE_DOOR, GO_THORIM_STONE_DOOR, IN_PROGRESS, m_sColossusGuidSet, m_uiSlayedArenaMobs, m_uiStairsSpawnTimer, NPC_CAPTAIN_ALLIANCE, NPC_CAPTAIN_HORDE, NPC_CORRUPTED_SERVITOR, NPC_DARK_RUNE_ACOLYTE, NPC_DRUID_ALLIANCE_H, NPC_DRUID_ALLIANCE_N, NPC_DRUID_HORDE_H, NPC_DRUID_HORDE_N, NPC_FOREST_SWARMER, NPC_GUARDIAN_LASHER, NPC_GUARDIAN_OF_LIFE, NPC_IRONROOT_LASHER, NPC_JORMUNGAR_BEHEMOTH, NPC_LEVIATHAN, NPC_MAGE_ALLIANCE_H, NPC_MAGE_ALLIANCE_N, NPC_MAGE_HORDE_H, NPC_MAGE_HORDE_N, NPC_MANGROVE_ENT, NPC_MISGUIDED_NYMPH, NPC_NATURES_BLADE, NPC_PRIEST_ALLIANCE_H, NPC_PRIEST_ALLIANCE_N, NPC_PRIEST_HORDE_H, NPC_PRIEST_HORDE_N, NPC_RUNE_GIANT, NPC_RUNIC_COLOSSUS, NPC_SANCTUM_SENTRY, NPC_SARONITE_ANIMUS, NPC_SHAMAN_ALLIANCE_H, NPC_SHAMAN_ALLIANCE_N, NPC_SHAMAN_HORDE_H, NPC_SHAMAN_HORDE_N, NPC_SOLDIER_ALLIANCE, NPC_SOLDIER_HORDE, NPC_THORIM, NPC_ULDUAR_COLOSSUS, NPC_VEZAX, SAY_PRE_LEVIATHAN_1, UnitAI::SendAIEvent(), SetData(), SetSpecialAchievementCriteria(), SPECIAL, DialogueHelper::StartNextDialogueText(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_ACHIEV_CAT_LADY, TYPE_ACHIEV_COOL_FRIENDS, TYPE_AURIAYA, TYPE_FREYA_CONSPEEDATORY, TYPE_HODIR, TYPE_LEVIATHAN, TYPE_LEVIATHAN_GAUNTLET, and TYPE_VEZAX_HARD.
OnCreatureEnterCombat()
void instance_ulduar::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 1242 of file ulduar.cpp.
References Object::GetEntry(), m_uiStairsSpawnTimer, and NPC_RUNE_GIANT.
OnCreatureRespawn()
void instance_ulduar::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 307 of file ulduar.cpp.
References TimerManager::AddCustomAction(), Creature::AI(), Unit::CastSpell(), GetData(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::HasAura(), IN_PROGRESS, NPC_HODIR_HELPER, TIMER_HODIRS_PROTECTIVE_GAZE, TRIGGERED_NONE, and TYPE_YOGGSARON.
OnObjectCreate()
void instance_ulduar::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 323 of file ulduar.cpp.
References DONE, FAIL, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ACTIVATE_TRAM, GO_ANCIENT_GATE, GO_ARCHIVUM_DOOR, GO_AZEROTH_GLOBE, GO_BRAIN_DOOR_CHAMBER, GO_BRAIN_DOOR_ICECROWN, GO_BRAIN_DOOR_STORMWIND, GO_BROKEN_HARPOON, GO_CACHE_OF_INOV_10, GO_CACHE_OF_INOV_10_H, GO_CACHE_OF_INOV_25, GO_CACHE_OF_INOV_25_H, GO_CACHE_OF_LIVING_STONE_10, GO_CACHE_OF_LIVING_STONE_25, GO_CACHE_OF_RARE_WINTER_10, GO_CACHE_OF_RARE_WINTER_25, GO_CACHE_OF_STORMS_10, GO_CACHE_OF_STORMS_10_H, GO_CACHE_OF_STORMS_25, GO_CACHE_OF_STORMS_25_H, GO_CACHE_OF_WINTER_10, GO_CACHE_OF_WINTER_25, GO_CALL_TRAM_CENTER, GO_CALL_TRAM_MIMIRON, GO_CELESTIAL_ACCES, GO_CELESTIAL_ACCES_H, GO_CELESTIAL_DOOR_1, GO_CELESTIAL_DOOR_2, GO_CELESTIAL_DOOR_COMBAT, GO_DARK_IRON_PORTCULIS, GO_DOOR_LEVER, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_FREYA_CRYSTAL, GO_GIFT_OF_OBSERVER_10, GO_GIFT_OF_OBSERVER_25, GO_HARPOON_GUN_1, GO_HARPOON_GUN_2, GO_HARPOON_GUN_3, GO_HARPOON_GUN_4, GO_HODIR_CRYSTAL, GO_HODIR_ENTER, GO_HODIR_EXIT, GO_HODIR_ICE_WALL, GO_IRON_ENTRANCE_DOOR, GO_KOLOGARN_BRIDGE, GO_LEVIATHAN_GATE, GO_LIGHTNING_DOOR, GO_LIGHTNING_FIELD, GO_MIMIRON_BUTTON, GO_MIMIRON_CRYSTAL, GO_MIMIRON_DOOR_1, GO_MIMIRON_DOOR_2, GO_MIMIRON_DOOR_3, GO_MIMIRON_ELEVATOR, GO_RUNED_STONE_DOOR, GO_SHIELD_WALL, GO_STATE_ACTIVE, GO_STATE_READY, GO_THORIM_CRYSTAL, GO_THORIM_STONE_DOOR, GO_TRAM, GO_TRAM_TURNAROUND_CENTER, GO_TRAM_TURNAROUND_MIMIRON, GO_ULDUAR_TELEPORTER, GO_UNIVERSE_FLOOR, GO_UNIVERSE_FLOOR_COMBAT, GO_VEZAX_GATE, GO_XT002_GATE, GO_YOGG_GATE, m_auiEncounter, m_auiUlduarTowers, ScriptedInstance::m_goEntryGuidStore, m_lRepairedHarpoonsGuids, m_vBrokenHarpoonsGuids, NOT_STARTED, Object::RemoveFlag(), Object::SetFlag(), GameObject::SetGoState(), SPECIAL, TYPE_ALGALON, TYPE_ASSEMBLY, TYPE_FREYA, TYPE_HODIR, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_THORIM, TYPE_VEZAX, and TYPE_XT002.
OnObjectSpawn()
void instance_ulduar::OnObjectSpawn (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 490 of file ulduar.cpp.
References Object::GetEntry(), WorldObject::GetMap(), GO_TRAM, and WorldObject::SpawnGameObject().
OnPlayerDeath()
void instance_ulduar::OnPlayerDeath (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 160 of file ulduar.cpp.
References DONE, IsEncounterInProgress(), SetData(), and TYPE_CHAMPION_FAILED.
OnPlayerEnter()
void instance_ulduar::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 102 of file ulduar.cpp.
References afAlgalonMovePos, afBrannArchivumSpawnPos, afLeviathanMovePos, afProspectorSpawnPos, Map::ChangeGOPathfinding(), DoCallLeviathanHelp(), DONE, DoSpawnHodirNpcs(), FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, Map::IsRegularDifficulty(), m_aKeeperHelperLocs, m_aKeepersSpawnLocs, m_bHelpersLoaded, NPC_ALGALON, NPC_BRANN_ARCHIVUM, NPC_LEVIATHAN, NPC_PROSPECTOR_DOREN, NPC_PROSPECTOR_DOREN_H, Player::SendUpdateWorldState(), SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, TEMPSPAWN_DEAD_DESPAWN, TYPE_ALGALON_TIMER, TYPE_ASSEMBLY, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_YOGGSARON, WORLD_STATE_TIMER, and WORLD_STATE_TIMER_COUNT.
Save()
const char* instance_ulduar::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 602 of file ulduar.h.
References m_strInstData.
SetData()
void instance_ulduar::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 507 of file ulduar.cpp.
References ACHIEV_FREYA_CONSPEEDATORY, ACHIEV_START_FREYA_ID, ACHIEV_START_IGNIS_ID, ACHIEV_START_XT002_ID, ACHIEV_START_YOGG_ID, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, afBrannArchivumSpawnPos, afProspectorSpawnPos, AI_EVENT_CUSTOM_A, DoCallLeviathanHelp(), DONE, DoOpenMadnessDoorIfCan(), ScriptedInstance::DoRespawnGameObject(), DoSpawnHodirNpcs(), ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), GetData(), Map::GetGameObject(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ARCHIVUM_DOOR, GO_AZEROTH_GLOBE, GO_BRAIN_DOOR_CHAMBER, GO_BRAIN_DOOR_ICECROWN, GO_BRAIN_DOOR_STORMWIND, GO_CACHE_OF_INOV_10, GO_CACHE_OF_INOV_10_H, GO_CACHE_OF_INOV_25, GO_CACHE_OF_INOV_25_H, GO_CACHE_OF_LIVING_STONE_10, GO_CACHE_OF_LIVING_STONE_25, GO_CACHE_OF_RARE_WINTER_10, GO_CACHE_OF_RARE_WINTER_25, GO_CACHE_OF_STORMS_10, GO_CACHE_OF_STORMS_10_H, GO_CACHE_OF_STORMS_25, GO_CACHE_OF_STORMS_25_H, GO_CACHE_OF_WINTER_10, GO_CACHE_OF_WINTER_25, GO_CELESTIAL_DOOR_COMBAT, GO_DOOR_LEVER, GO_FLAG_NO_INTERACT, GO_FREYA_CRYSTAL, GO_GIFT_OF_OBSERVER_10, GO_GIFT_OF_OBSERVER_25, GO_HODIR_CRYSTAL, GO_HODIR_ENTER, GO_HODIR_EXIT, GO_HODIR_ICE_WALL, GO_IRON_ENTRANCE_DOOR, GO_JUST_DEACTIVATED, GO_KOLOGARN_BRIDGE, GO_LIGHTNING_DOOR, GO_LIGHTNING_FIELD, GO_MIMIRON_BUTTON, GO_MIMIRON_CRYSTAL, GO_MIMIRON_DOOR_1, GO_MIMIRON_DOOR_2, GO_MIMIRON_DOOR_3, GO_MIMIRON_ELEVATOR, GO_RUNED_STONE_DOOR, GO_SHIELD_WALL, GO_STATE_ACTIVE, GO_STATE_READY, GO_THORIM_CRYSTAL, GO_THORIM_STONE_DOOR, GO_UNIVERSE_FLOOR, GO_UNIVERSE_FLOOR_COMBAT, GO_VEZAX_GATE, GO_XT002_GATE, GO_YOGG_GATE, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_aKeeperHelperLocs, m_auiAchievEncounter, m_auiEncounter, m_auiHardBoss, m_auiUlduarKeepers, m_auiUlduarTowers, m_lDefendersGuids, m_lEngineersGuids, m_lHarpoonDummyGuids, m_lOminousCloudsGuids, m_lRepairedHarpoonsGuids, m_lTrappersGuids, m_strInstData, m_uiGauntletStatus, m_uiSlayedArenaMobs, m_uiStairsSpawnTimer, m_uiYoggResetTimer, m_vBrokenHarpoonsGuids, MINUTE, NPC_AERIAL_UNIT, NPC_ALGALON, NPC_BRANN_ARCHIVUM, NPC_COMPUTER, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRACH, NPC_ELDER_STONEBARK, NPC_EXPEDITION_COMMANDER, NPC_FREYA_HELPER, NPC_HODIR_HELPER, NPC_KEEPER_FREYA, NPC_KEEPER_HODIR, NPC_KEEPER_MIMIRON, NPC_KEEPER_THORIM, NPC_LEVIATHAN_MK, NPC_MIMIRON, NPC_MIMIRON_HELPER, NPC_PROSPECTOR_DOREN, NPC_PROSPECTOR_DOREN_H, NPC_RUNIC_COLOSSUS, NPC_SARA, NPC_THORIM_HELPER, NPC_VOICE_OF_YOGG, NPC_VX001, NPC_YOGG_BRAIN, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SetSpecialAchievementCriteria(), SpawnFriendlyKeeper(), SpawnKeeperHelper(), SPECIAL, SPELL_AURA_CONTROL_VEHICLE, SPELL_CLEAR_INSANE, SPELL_KEEPER_ACTIVE, SPELL_TELEPORT, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_ACHIEV_BRUNDIR, TYPE_ACHIEV_CAT_LADY, TYPE_ACHIEV_CHEESE_FREEZE, TYPE_ACHIEV_COOL_FRIENDS, TYPE_ACHIEV_DISARMED, TYPE_ACHIEV_DRIVE_CRAZY, TYPE_ACHIEV_LIGHTNING, TYPE_ACHIEV_LOOKS_KILL, TYPE_ACHIEV_MOLGEIM, TYPE_ACHIEV_NERF_ENG, TYPE_ACHIEV_NINE_LIVES, TYPE_ACHIEV_OPEN_ARMS, TYPE_ACHIEV_QUICK_SHAVE, TYPE_ACHIEV_RUBBLE, TYPE_ACHIEV_SHADOWDODGER, TYPE_ACHIEV_SHATTERED, TYPE_ACHIEV_SHUTOUT, TYPE_ACHIEV_STEELBREAKER, TYPE_ACHIEV_STUNNED, TYPE_ALGALON, TYPE_ALGALON_TIMER, TYPE_ASSEMBLY, TYPE_AURIAYA, TYPE_CHAMPION_FAILED, TYPE_FREYA, TYPE_FREYA_CONSPEEDATORY, TYPE_FREYA_HARD, TYPE_HODIR, TYPE_HODIR_HARD, TYPE_IGNIS, TYPE_KEEPER_FREYA, TYPE_KEEPER_HODIR, TYPE_KEEPER_MIMIRON, TYPE_KEEPER_THORIM, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_LEVIATHAN_GAUNTLET, TYPE_LEVIATHAN_HARD, TYPE_MIMIRON, TYPE_MIMIRON_HARD, TYPE_RAZORSCALE, TYPE_THORIM, TYPE_THORIM_HARD, TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, TYPE_TOWER_THORIM, TYPE_VEZAX, TYPE_VEZAX_HARD, TYPE_XT002, TYPE_XT002_HARD, TYPE_YOGGSARON, TYPE_YOGGSARON_HARD, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, WORLD_STATE_TIMER, and WORLD_STATE_TIMER_COUNT.
Referenced by boss_brundirAI::Aggro(), boss_molgeimAI::Aggro(), boss_steelbreakerAI::Aggro(), boss_algalonAI::Aggro(), boss_auriayaAI::Aggro(), boss_flame_leviathanAI::Aggro(), boss_freyaAI::Aggro(), boss_general_vezaxAI::Aggro(), boss_hodirAI::Aggro(), boss_ignisAI::Aggro(), boss_kologarnAI::Aggro(), boss_razorscaleAI::Aggro(), boss_thorimAI::Aggro(), boss_xt_002AI::Aggro(), boss_algalonAI::DamageTaken(), boss_freyaAI::DamageTaken(), boss_mimironAI::DamageTaken(), boss_thorimAI::DamageTaken(), boss_saraAI::DoInitialiseKeepers(), boss_freyaAI::FetchElders(), boss_flame_leviathanAI::FetchTowers(), boss_brundirAI::JustDied(), boss_molgeimAI::JustDied(), boss_steelbreakerAI::JustDied(), boss_auriayaAI::JustDied(), boss_flame_leviathanAI::JustDied(), boss_general_vezaxAI::JustDied(), boss_ignisAI::JustDied(), boss_kologarnAI::JustDied(), boss_leviathan_mk2AI::JustDied(), boss_razorscaleAI::JustDied(), boss_xt_002AI::JustDied(), boss_yogg_saronAI::JustDied(), boss_brundirAI::JustReachedHome(), boss_molgeimAI::JustReachedHome(), boss_steelbreakerAI::JustReachedHome(), boss_algalonAI::JustReachedHome(), boss_auriayaAI::JustReachedHome(), boss_flame_leviathanAI::JustReachedHome(), boss_freyaAI::JustReachedHome(), boss_general_vezaxAI::JustReachedHome(), boss_hodirAI::JustReachedHome(), boss_ignisAI::JustReachedHome(), boss_kologarnAI::JustReachedHome(), boss_leviathan_mk2AI::JustReachedHome(), boss_aerial_unitAI::JustReachedHome(), boss_razorscaleAI::JustReachedHome(), boss_thorimAI::JustReachedHome(), boss_xt_002AI::JustReachedHome(), boss_yogg_saronAI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), boss_saraAI::MoveInLineOfSight(), OnCreatureDeath(), OnPlayerDeath(), ProcessEventId_event_boss_hodir(), ProcessEventId_event_go_ulduar_tower(), boss_mimironAI::ReceiveAIEvent(), boss_xt_002AI::ReceiveAIEvent(), boss_brundirAI::SpellHit(), boss_molgeimAI::SpellHit(), boss_steelbreakerAI::SpellHit(), boss_thorimAI::SpellHit(), Update(), and boss_hodirAI::UpdateAI().
SetSpecialAchievementCriteria()
void instance_ulduar::SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
Definition at line 1373 of file ulduar.cpp.
References m_abAchievCriteria, and MAX_SPECIAL_ACHIEV_CRITS.
Referenced by boss_freyaAI::DamageTaken(), DoProcessShatteredEvent(), boss_brundirAI::JustDied(), boss_molgeimAI::JustDied(), boss_steelbreakerAI::JustDied(), boss_feral_defenderAI::JustDied(), OnCreatureDeath(), boss_kologarnAI::ReceiveAIEvent(), SetData(), boss_brundirAI::SpellHitTarget(), boss_general_vezaxAI::SpellHitTarget(), npc_voice_yogg_saronAI::SpellHitTarget(), npc_focused_eyebeamAI::SpellHitTarget(), boss_thorimAI::SpellHitTarget(), boss_kologarnAI::SummonedCreatureJustDied(), boss_kologarnAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), and npc_flash_freezeAI::UpdateAI().
SetTramRotateTimer()
void instance_ulduar::SetTramRotateTimer () inline
Definition at line 626 of file ulduar.h.
References m_bTramAtCenter, and m_uiTramRotateTimer.
Referenced by GOUse_go_activate_tram().
SpawnFriendlyKeeper()
void instance_ulduar::SpawnFriendlyKeeper (uint32 uiWho) protected
Definition at line 1187 of file ulduar.cpp.
References ScriptedInstance::GetPlayerInMap(), m_aKeepersSpawnLocs, NPC_KEEPER_FREYA, NPC_KEEPER_HODIR, NPC_KEEPER_MIMIRON, NPC_KEEPER_THORIM, WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_DESPAWN.
Referenced by SetData().
SpawnKeeperHelper()
void instance_ulduar::SpawnKeeperHelper (uint32 uiWho) protected
Definition at line 1203 of file ulduar.cpp.
References DoScriptText(), UlduarKeeperSpawns::fO, UlduarKeeperSpawns::fX, UlduarKeeperSpawns::fY, UlduarKeeperSpawns::fZ, ScriptedInstance::GetPlayerInMap(), m_aKeeperHelperLocs, NPC_FREYA_HELPER, NPC_HODIR_HELPER, NPC_MIMIRON_HELPER, NPC_THORIM_HELPER, SPELL_KEEPER_ACTIVE, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, and TRIGGERED_NONE.
Referenced by SetData().
Update()
void instance_ulduar::Update (uint32 uiDiff) virtual
Reimplemented from InstanceData.
Definition at line 1621 of file ulduar.cpp.
References DialogueHelper::DialogueUpdate(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CALL_TRAM_CENTER, GO_CALL_TRAM_MIMIRON, GO_FLAG_NO_INTERACT, GO_TRAM_TURNAROUND_CENTER, GO_TRAM_TURNAROUND_MIMIRON, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_bTramAtCenter, m_lOminousCloudsGuids, m_uiAlgalonTimer, m_uiShatterAchievTimer, m_uiStairsSpawnTimer, m_uiTramRotateTimer, m_uiYoggResetTimer, MINUTE, NPC_HONOR_GUARD_STAIRS, NPC_RUNE_ACOLYTE_STAIRS, NPC_RUNE_GIANT, NPC_SARA, NPC_VOICE_OF_YOGG, NPC_YOGG_BRAIN, SetData(), TEMPSPAWN_DEAD_DESPAWN, TYPE_ALGALON, TYPE_ALGALON_TIMER, TYPE_IGNIS, and urand().
Field Documentation
m_abAchievCriteria
bool instance_ulduar::m_abAchievCriteria[MAX_SPECIAL_ACHIEV_CRITS] protected
Definition at line 643 of file ulduar.h.
Referenced by CheckAchievementCriteriaMeet(), Initialize(), and SetSpecialAchievementCriteria().
m_animusVezaxBunnyGuid
ObjectGuid instance_ulduar::m_animusVezaxBunnyGuid protected
Definition at line 659 of file ulduar.h.
Referenced by GetVezaxBunnyGuid(), and OnCreatureCreate().
m_auiAchievEncounter
uint32 instance_ulduar::m_auiAchievEncounter[MAX_ACHIEV_ENCOUNTER] protected
Definition at line 644 of file ulduar.h.
Referenced by GetData(), Load(), and SetData().
m_auiEncounter
uint32 instance_ulduar::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 639 of file ulduar.h.
Referenced by CheckAchievementCriteriaMeet(), DoOpenMadnessDoorIfCan(), GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), SetData(), and Update().
m_auiHardBoss
uint32 instance_ulduar::m_auiHardBoss[HARD_MODE_ENCOUNTER] protected
Definition at line 640 of file ulduar.h.
Referenced by GetData(), Initialize(), and SetData().
m_auiUlduarKeepers
uint32 instance_ulduar::m_auiUlduarKeepers[KEEPER_ENCOUNTER] protected
Definition at line 641 of file ulduar.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_auiUlduarTowers
uint32 instance_ulduar::m_auiUlduarTowers[KEEPER_ENCOUNTER] protected
Definition at line 642 of file ulduar.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_bHelpersLoaded
bool instance_ulduar::m_bHelpersLoaded protected
Definition at line 646 of file ulduar.h.
Referenced by OnPlayerEnter().
m_bTramAtCenter
bool instance_ulduar::m_bTramAtCenter protected
Definition at line 647 of file ulduar.h.
Referenced by SetTramRotateTimer(), and Update().
m_lDefendersGuids
GuidList instance_ulduar::m_lDefendersGuids protected
Definition at line 666 of file ulduar.h.
Referenced by GetDefenderGuids(), OnCreatureCreate(), and SetData().
m_leftKoloStalkerGuid
ObjectGuid instance_ulduar::m_leftKoloStalkerGuid protected
Definition at line 657 of file ulduar.h.
Referenced by GetKoloRubbleStalker(), and OnCreatureCreate().
m_lEngineersGuids
GuidList instance_ulduar::m_lEngineersGuids protected
Definition at line 664 of file ulduar.h.
Referenced by GetEngineersGuids(), OnCreatureCreate(), and SetData().
m_lHarpoonDummyGuids
GuidList instance_ulduar::m_lHarpoonDummyGuids protected
Definition at line 667 of file ulduar.h.
Referenced by OnCreatureCreate(), and SetData().
m_lLeftHandBunniesGuids
GuidList instance_ulduar::m_lLeftHandBunniesGuids protected
Definition at line 672 of file ulduar.h.
Referenced by GetSmashTargetsGuids(), and OnCreatureCreate().
m_lOminousCloudsGuids
GuidList instance_ulduar::m_lOminousCloudsGuids protected
Definition at line 674 of file ulduar.h.
Referenced by GetOminousCloudGuids(), OnCreatureCreate(), SetData(), and Update().
m_lRepairedHarpoonsGuids
GuidList instance_ulduar::m_lRepairedHarpoonsGuids protected
Definition at line 668 of file ulduar.h.
Referenced by OnObjectCreate(), and SetData().
m_lRightHandBunniesGuids
GuidList instance_ulduar::m_lRightHandBunniesGuids protected
Definition at line 673 of file ulduar.h.
Referenced by GetSmashTargetsGuids(), and OnCreatureCreate().
m_lThorimBunniesGuids
GuidList instance_ulduar::m_lThorimBunniesGuids protected
Definition at line 669 of file ulduar.h.
Referenced by GetThorimBunniesGuids(), and OnCreatureCreate().
m_lTrappersGuids
GuidList instance_ulduar::m_lTrappersGuids protected
Definition at line 665 of file ulduar.h.
Referenced by GetTrappersGuids(), OnCreatureCreate(), and SetData().
m_lUpperBunniesGuids
GuidList instance_ulduar::m_lUpperBunniesGuids protected
Definition at line 670 of file ulduar.h.
Referenced by GetThorimBunniesGuids(), and OnCreatureCreate().
m_lUpperThunderOrbsGuids
GuidList instance_ulduar::m_lUpperThunderOrbsGuids protected
Definition at line 671 of file ulduar.h.
Referenced by GetThunderOrbsGuids(), and OnCreatureCreate().
m_rightKoloStalkerGuid
ObjectGuid instance_ulduar::m_rightKoloStalkerGuid protected
Definition at line 658 of file ulduar.h.
Referenced by GetKoloRubbleStalker(), and OnCreatureCreate().
m_sColossusGuidSet
GuidSet instance_ulduar::m_sColossusGuidSet protected
Definition at line 675 of file ulduar.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_strInstData
std::string instance_ulduar::m_strInstData protected
Definition at line 638 of file ulduar.h.
Referenced by Save(), and SetData().
m_uiAlgalonTimer
uint32 instance_ulduar::m_uiAlgalonTimer protected
Definition at line 649 of file ulduar.h.
Referenced by Update().
m_uiGauntletStatus
uint32 instance_ulduar::m_uiGauntletStatus protected
Definition at line 652 of file ulduar.h.
Referenced by GetData(), and SetData().
m_uiShatterAchievTimer
uint32 instance_ulduar::m_uiShatterAchievTimer protected
Definition at line 651 of file ulduar.h.
Referenced by DoProcessShatteredEvent(), and Update().
m_uiSlayedArenaMobs
uint8 instance_ulduar::m_uiSlayedArenaMobs protected
Definition at line 655 of file ulduar.h.
Referenced by OnCreatureDeath(), and SetData().
m_uiStairsSpawnTimer
uint32 instance_ulduar::m_uiStairsSpawnTimer protected
Definition at line 653 of file ulduar.h.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), SetData(), and Update().
m_uiTramRotateTimer
uint32 instance_ulduar::m_uiTramRotateTimer protected
Definition at line 654 of file ulduar.h.
Referenced by SetTramRotateTimer(), and Update().
m_uiYoggResetTimer
uint32 instance_ulduar::m_uiYoggResetTimer protected
Definition at line 650 of file ulduar.h.
Referenced by SetData(), and Update().
m_vaporVezaxBunnyGuid
ObjectGuid instance_ulduar::m_vaporVezaxBunnyGuid protected
Definition at line 660 of file ulduar.h.
Referenced by GetVezaxBunnyGuid(), and OnCreatureCreate().
m_vBrokenHarpoonsGuids
GuidVector instance_ulduar::m_vBrokenHarpoonsGuids protected
Definition at line 663 of file ulduar.h.
Referenced by GetHarpoonsGuids(), OnObjectCreate(), and SetData().
m_vToyPileGuidVector
GuidVector instance_ulduar::m_vToyPileGuidVector protected
Definition at line 662 of file ulduar.h.
Referenced by GetToyPileGuids(), and OnCreatureCreate().
The documentation for this class was generated from the following files:
ulduar.h
ulduar.cpp