CMaNGOS_WoTLK: Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > Class Template Reference
Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES > Class Template Reference
#include <Grid.h>
Public Member Functions
~Grid ()
destructor to clean up its resources.
template<class SPECIFIC_OBJECT >
bool AddWorldObject (SPECIFIC_OBJECT *obj)
an object of interested enters the grid
template<class SPECIFIC_OBJECT >
bool RemoveWorldObject (SPECIFIC_OBJECT *obj)
an object of interested exits the grid
template<class T >
void Visit (TypeContainerVisitor< T, TypeMapContainer< GRID_OBJECT_TYPES > > &visitor)
Grid visitor for grid objects.
template<class T >
void Visit (TypeContainerVisitor< T, TypeMapContainer< WORLD_OBJECT_TYPES > > &visitor)
Grid visitor for world objects.
uint32 ActiveObjectsInGrid () const
Returns the number of object within the grid.
template<class SPECIFIC_OBJECT >
bool AddGridObject (SPECIFIC_OBJECT *obj)
Inserts a container type object into the grid.
template<class SPECIFIC_OBJECT >
bool RemoveGridObject (SPECIFIC_OBJECT *obj)
Removes a containter type object from the grid.
Private Types
typedef std::set< void * > ActiveGridObjects
Private Attributes
TypeMapContainer< GRID_OBJECT_TYPES > i_container
TypeMapContainer< WORLD_OBJECT_TYPES > i_objects
ActiveGridObjects m_activeGridObjects
Friends
template<class A , class T , class O >
class GridLoader
Detailed Description
template<class ACTIVE_OBJECT, class WORLD_OBJECT_TYPES, class GRID_OBJECT_TYPES>
class Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >
Definition at line 47 of file Grid.h.
Member Typedef Documentation
ActiveGridObjects
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > typedef std::set<void*> Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ActiveGridObjects private
Definition at line 124 of file Grid.h.
Constructor & Destructor Documentation
~Grid()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::~Grid () inline
destructor to clean up its resources.
This includes unloading the grid if it has not been unload.
Definition at line 57 of file Grid.h.
Member Function Documentation
ActiveObjectsInGrid()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > uint32 Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ActiveObjectsInGrid () const inline
Returns the number of object within the grid.
Definition at line 93 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_objects, and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::m_activeGridObjects.
AddGridObject()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class SPECIFIC_OBJECT > bool Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject (SPECIFIC_OBJECT * obj) inline
Inserts a container type object into the grid.
Definition at line 101 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_container, and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::m_activeGridObjects.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), and LoadHelper().
AddWorldObject()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class SPECIFIC_OBJECT > bool Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject (SPECIFIC_OBJECT * obj) inline
an object of interested enters the grid
Definition at line 62 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_objects.
Referenced by ObjectAccessor::AddCorpsesToGrid(), NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Camera::Event_AddedToWorld(), Camera::Event_Moved(), and LoadHelper().
RemoveGridObject()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class SPECIFIC_OBJECT > bool Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveGridObject (SPECIFIC_OBJECT * obj) inline
Removes a containter type object from the grid.
Definition at line 112 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_container, and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::m_activeGridObjects.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveGridObject().
RemoveWorldObject()
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class SPECIFIC_OBJECT > bool Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveWorldObject (SPECIFIC_OBJECT * obj) inline
an object of interested exits the grid
Definition at line 70 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_objects.
Referenced by NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveWorldObject().
Visit() [1/2]
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class T > void Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit (TypeContainerVisitor< T, TypeMapContainer< GRID_OBJECT_TYPES > > & visitor) inline
Grid visitor for grid objects.
Definition at line 78 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_container.
Referenced by ObjectGridLoader::Load(), ObjectGridRespawnMover::Move(), ObjectGridStoper::Stop(), ObjectGridUnloader::Unload(), and NGrid< N, ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
Visit() [2/2]
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class T > void Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit (TypeContainerVisitor< T, TypeMapContainer< WORLD_OBJECT_TYPES > > & visitor) inline
Grid visitor for world objects.
Definition at line 86 of file Grid.h.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_objects.
Friends And Related Function Documentation
GridLoader
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > template<class A , class T , class O > friend class GridLoader friend
Definition at line 50 of file Grid.h.
Field Documentation
i_container
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > TypeMapContainer<GRID_OBJECT_TYPES> Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_container private
Definition at line 122 of file Grid.h.
Referenced by Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveGridObject(), and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
i_objects
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > TypeMapContainer<WORLD_OBJECT_TYPES> Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::i_objects private
Definition at line 123 of file Grid.h.
Referenced by Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ActiveObjectsInGrid(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveWorldObject(), and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
m_activeGridObjects
template<class ACTIVE_OBJECT , class WORLD_OBJECT_TYPES , class GRID_OBJECT_TYPES > ActiveGridObjects Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::m_activeGridObjects private
Definition at line 125 of file Grid.h.
Referenced by Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::ActiveObjectsInGrid(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), and Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::RemoveGridObject().
The documentation for this class was generated from the following file:
Grid.h