CMaNGOS_WoTLK: MapPersistentState Class Reference
MapPersistentState Class Reference abstract
#include <MapPersistentStateMgr.h>
Public Member Functions
virtual ~MapPersistentState ()
uint32 GetInstanceId () const
ObjectGuid GetInstanceGuid () const
uint32 GetMapId () const
MapEntry const * GetMapEntry () const
Difficulty GetDifficulty () const
bool IsUsedByMap () const
Map * GetMap () const
void SetUsedByMapState (Map *map)
time_t GetCreatureRespawnTime (uint32 loguid) const
void SaveCreatureRespawnTime (uint32 loguid, time_t t)
time_t GetGORespawnTime (uint32 loguid) const
void SaveGORespawnTime (uint32 loguid, time_t t)
time_t GetObjectRespawnTime (uint32 typeId, uint32 loguid) const
void SaveObjectRespawnTime (uint32 typeId, uint32 loguid, time_t t)
void InitPools ()
SpawnedPoolData & GetSpawnedPoolData ()
template<typename T >
bool IsSpawnedPoolObject (uint32 db_guid_or_pool_id)
MapCellObjectGuids const & GetCellObjectGuids (uint32 cell_id)
void AddCreatureToGrid (uint32 guid, CreatureData const *data)
void RemoveCreatureFromGrid (uint32 guid, CreatureData const *data)
void AddGameobjectToGrid (uint32 guid, GameObjectData const *data)
void RemoveGameobjectFromGrid (uint32 guid, GameObjectData const *data)
virtual uint32 GetCompletedEncountersMask () const
Static Public Member Functions
static Difficulty GetSaveDifficulty (Difficulty difficulty, MapEntry const *entry)
Protected Member Functions
MapPersistentState (uint16 MapId, uint32 InstanceId, Difficulty difficulty)
virtual bool CanBeUnload () const =0
bool UnloadIfEmpty ()
void ClearRespawnTimes ()
bool HasRespawnTimes () const
Private Types
typedef std::unordered_map< uint32, time_t > RespawnTimes
Private Member Functions
void SetCreatureRespawnTime (uint32 loguid, time_t t)
void SetGORespawnTime (uint32 loguid, time_t t)
Private Attributes
uint32 m_instanceid
uint32 m_mapid
Difficulty m_difficulty
Map * m_usedByMap
RespawnTimes m_creatureRespawnTimes
RespawnTimes m_goRespawnTimes
MapCellObjectGuidsMap m_gridObjectGuids
SpawnedPoolData m_spawnedPoolData
Friends
class MapPersistentStateManager
Detailed Description
Definition at line 58 of file MapPersistentStateMgr.h.
Member Typedef Documentation
RespawnTimes
typedef std::unordered_map<uint32, time_t> MapPersistentState::RespawnTimes private
Definition at line 136 of file MapPersistentStateMgr.h.
Constructor & Destructor Documentation
MapPersistentState()
MapPersistentState::MapPersistentState (uint16 MapId, uint32 InstanceId, Difficulty difficulty) protected
Definition at line 46 of file MapPersistentStateMgr.cpp.
~MapPersistentState()
MapPersistentState::~MapPersistentState () virtual
Definition at line 52 of file MapPersistentStateMgr.cpp.
Member Function Documentation
AddCreatureToGrid()
void MapPersistentState::AddCreatureToGrid (uint32 guid, CreatureData const * data)
Definition at line 165 of file MapPersistentStateMgr.cpp.
References MaNGOS::ComputeCellPair(), m_gridObjectGuids, CreatureData::posX, CreatureData::posY, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by SpawnGroup::Spawn(), and PoolGroup< T >::Spawn1Object().
AddGameobjectToGrid()
void MapPersistentState::AddGameobjectToGrid (uint32 guid, GameObjectData const * data)
Definition at line 181 of file MapPersistentStateMgr.cpp.
References MaNGOS::ComputeCellPair(), m_gridObjectGuids, GameObjectData::posX, GameObjectData::posY, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by SpawnGroup::Spawn(), and PoolGroup< T >::Spawn1Object().
CanBeUnload()
bool MapPersistentState::CanBeUnload () const inline protected pure virtual
Implemented in BattleGroundPersistentState, DungeonPersistentState, and WorldPersistentState.
Definition at line 151 of file MapPersistentStateMgr.h.
References m_usedByMap.
Referenced by DungeonPersistentState::CanBeUnload(), BattleGroundPersistentState::CanBeUnload(), and UnloadIfEmpty().
ClearRespawnTimes()
void MapPersistentState::ClearRespawnTimes () protected
Definition at line 157 of file MapPersistentStateMgr.cpp.
References m_creatureRespawnTimes, m_goRespawnTimes, and UnloadIfEmpty().
Referenced by DungeonPersistentState::DeleteRespawnTimes().
GetCellObjectGuids()
MapCellObjectGuids const& MapPersistentState::GetCellObjectGuids (uint32 cell_id) inline
Definition at line 115 of file MapPersistentStateMgr.h.
References m_gridObjectGuids.
Referenced by ObjectGridLoader::Visit().
GetCompletedEncountersMask()
virtual uint32 MapPersistentState::GetCompletedEncountersMask () const inline virtual
Reimplemented in DungeonPersistentState.
Definition at line 121 of file MapPersistentStateMgr.h.
Referenced by Map::Initialize().
GetCreatureRespawnTime()
time_t MapPersistentState::GetCreatureRespawnTime (uint32 loguid) const inline
Definition at line 92 of file MapPersistentStateMgr.h.
References m_creatureRespawnTimes.
Referenced by GetObjectRespawnTime(), CreatureLinkingHolder::IsRespawnReady(), and Creature::LoadFromDB().
GetDifficulty()
Difficulty MapPersistentState::GetDifficulty () const inline
Definition at line 81 of file MapPersistentStateMgr.h.
References m_difficulty.
Referenced by DungeonMap::Add(), Player::BindToInstance(), Group::BindToInstance(), DungeonPersistentState::GetResetTimeForDB(), WorldSession::HandleCalendarGetCalendar(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), DungeonPersistentState::SaveToDB(), CalendarMgr::SendCalendarRaidLockoutAdd(), CalendarMgr::SendCalendarRaidLockoutRemove(), Player::SendRaidInfo(), DungeonPersistentState::UnbindThisState(), and DungeonPersistentState::UpdateEncounterState().
GetGORespawnTime()
time_t MapPersistentState::GetGORespawnTime (uint32 loguid) const inline
Definition at line 98 of file MapPersistentStateMgr.h.
References m_goRespawnTimes.
Referenced by GetObjectRespawnTime(), and GameObject::LoadFromDB().
GetInstanceGuid()
ObjectGuid MapPersistentState::GetInstanceGuid () const inline
Definition at line 74 of file MapPersistentStateMgr.h.
References GetInstanceId(), and HIGHGUID_INSTANCE.
Referenced by Player::SendRaidInfo().
GetInstanceId()
uint32 MapPersistentState::GetInstanceId () const inline
Definition at line 73 of file MapPersistentStateMgr.h.
References m_instanceid.
Referenced by DungeonMap::Add(), Player::BindToInstance(), Group::BindToInstance(), DungeonPersistentState::DeleteFromDB(), DungeonPersistentState::DeleteRespawnTimes(), Player::GetAreaTriggerLockStatus(), GetInstanceGuid(), WorldSession::HandleCalendarGetCalendar(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), Player::ResetInstances(), Group::ResetInstances(), DungeonPersistentState::SaveToDB(), CalendarMgr::SendCalendarRaidLockoutAdd(), CalendarMgr::SendCalendarRaidLockoutRemove(), Player::TeleportTo(), UnloadIfEmpty(), DungeonPersistentState::UpdateEncounterState(), and DungeonPersistentState::~DungeonPersistentState().
GetMap()
Map* MapPersistentState::GetMap () const inline
Definition at line 84 of file MapPersistentStateMgr.h.
References m_usedByMap.
Referenced by PoolGroup< T >::CanSpawn(), DungeonPersistentState::SaveToDB(), PoolGroup< T >::Spawn1Object(), and DungeonPersistentState::UpdateEncounterState().
GetMapEntry()
MapEntry const * MapPersistentState::GetMapEntry () const
Definition at line 56 of file MapPersistentStateMgr.cpp.
References m_mapid, and sMapStore.
Referenced by ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), PoolManager::InitSpawnPool(), SaveCreatureRespawnTime(), and SaveGORespawnTime().
GetMapId()
uint32 MapPersistentState::GetMapId () const inline
Definition at line 75 of file MapPersistentStateMgr.h.
References m_mapid.
Referenced by DungeonMap::Add(), Player::BindToInstance(), Group::BindToInstance(), PoolGroup< T >::Despawn1Object(), DungeonPersistentState::GetResetTimeForDB(), DungeonPersistentState::GetTemplate(), WorldSession::HandleCalendarGetCalendar(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), Player::ResetInstances(), Group::ResetInstances(), PoolGroup< T >::ReSpawn1Object(), DungeonPersistentState::SaveToDB(), CalendarMgr::SendCalendarRaidLockoutAdd(), CalendarMgr::SendCalendarRaidLockoutRemove(), Player::SendRaidInfo(), DungeonPersistentState::UnbindThisState(), UnloadIfEmpty(), DungeonPersistentState::UpdateEncounterState(), and DungeonPersistentState::~DungeonPersistentState().
GetObjectRespawnTime()
time_t MapPersistentState::GetObjectRespawnTime (uint32 typeId, uint32 loguid) const
Definition at line 122 of file MapPersistentStateMgr.cpp.
References GetCreatureRespawnTime(), GetGORespawnTime(), and TYPEID_UNIT.
Referenced by SpawnGroup::RemoveObject(), and SpawnGroup::Spawn().
GetSaveDifficulty()
Difficulty MapPersistentState::GetSaveDifficulty (Difficulty difficulty, MapEntry const * entry) static
Definition at line 197 of file MapPersistentStateMgr.cpp.
References MapEntry::IsDynamicDifficultyMap(), and RAID_DIFFICULTY_10MAN_HEROIC.
Referenced by MapPersistentStateManager::AddPersistentState(), Group::GetBoundInstance(), and Player::GetBoundInstanceSaveForSelfOrGroup().
GetSpawnedPoolData()
SpawnedPoolData& MapPersistentState::GetSpawnedPoolData () inline
Definition at line 109 of file MapPersistentStateMgr.h.
References m_spawnedPoolData.
Referenced by PoolGroup< T >::DespawnObject(), ChatHandler::HandlePoolInfoCommand(), ChatHandler::HandlePoolSpawnsCommand(), InitPools(), IsSpawnedPoolObject(), and PoolGroup< T >::SpawnObject().
HasRespawnTimes()
bool MapPersistentState::HasRespawnTimes () const inline protected
Definition at line 129 of file MapPersistentStateMgr.h.
References m_creatureRespawnTimes, and m_goRespawnTimes.
Referenced by DungeonPersistentState::CanBeUnload().
InitPools()
void MapPersistentState::InitPools ()
Definition at line 205 of file MapPersistentStateMgr.cpp.
References GetSpawnedPoolData(), SpawnedPoolData::SetInitialized(), sGameEventMgr, and sPoolMgr.
Referenced by Map::Initialize().
IsSpawnedPoolObject()
template<typename T > bool MapPersistentState::IsSpawnedPoolObject (uint32 db_guid_or_pool_id) inline
Definition at line 112 of file MapPersistentStateMgr.h.
References GetSpawnedPoolData(), and SpawnedPoolData::IsSpawnedObject().
Referenced by ChatHandler::HandleGameObjectTargetCommand(), CreatureLinkingHolder::IsRespawnReady(), FindCreatureData::operator()(), and FindGOData::operator()().
IsUsedByMap()
bool MapPersistentState::IsUsedByMap () const inline
Definition at line 83 of file MapPersistentStateMgr.h.
References m_usedByMap.
RemoveCreatureFromGrid()
void MapPersistentState::RemoveCreatureFromGrid (uint32 guid, CreatureData const * data)
Definition at line 173 of file MapPersistentStateMgr.cpp.
References MaNGOS::ComputeCellPair(), m_gridObjectGuids, CreatureData::posX, CreatureData::posY, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by CreatureGroup::Despawn(), and CreatureGroup::RemoveObject().
RemoveGameobjectFromGrid()
void MapPersistentState::RemoveGameobjectFromGrid (uint32 guid, GameObjectData const * data)
Definition at line 189 of file MapPersistentStateMgr.cpp.
References MaNGOS::ComputeCellPair(), m_gridObjectGuids, GameObjectData::posX, GameObjectData::posY, TOTAL_NUMBER_OF_CELLS_PER_MAP, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by GameObjectGroup::Despawn(), and GameObjectGroup::RemoveObject().
SaveCreatureRespawnTime()
void MapPersistentState::SaveCreatureRespawnTime (uint32 loguid, time_t t)
Definition at line 72 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Database::CreateStatement(), GetMapEntry(), m_instanceid, SqlStatement::PExecute(), SetCreatureRespawnTime(), and sWorld.
Referenced by ChatHandler::HandleRespawnCommand(), Creature::LoadFromDB(), MaNGOS::RespawnDo::operator()(), CreatureRespawnDeleteWorker::operator()(), Creature::Respawn(), SpawnManager::RespawnAll(), SpawnManager::RespawnCreature(), SaveObjectRespawnTime(), Creature::SaveRespawnTime(), and PoolGroup< T >::Spawn1Object().
SaveGORespawnTime()
void MapPersistentState::SaveGORespawnTime (uint32 loguid, time_t t)
Definition at line 97 of file MapPersistentStateMgr.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), Database::CreateStatement(), GetMapEntry(), m_instanceid, SqlStatement::PExecute(), SetGORespawnTime(), and sWorld.
Referenced by GameObject::LoadFromDB(), GameObjectRespawnDeleteWorker::operator()(), GameObject::Respawn(), SpawnManager::RespawnAll(), SpawnManager::RespawnGameObject(), SaveObjectRespawnTime(), GameObject::SaveRespawnTime(), and PoolGroup< T >::Spawn1Object().
SaveObjectRespawnTime()
void MapPersistentState::SaveObjectRespawnTime (uint32 typeId, uint32 loguid, time_t t)
Definition at line 127 of file MapPersistentStateMgr.cpp.
References SaveCreatureRespawnTime(), SaveGORespawnTime(), and TYPEID_UNIT.
Referenced by CreatureGroup::ClearRespawnTimes(), CreatureGroup::Despawn(), GameObjectGroup::Despawn(), SpawnGroup::RemoveObject(), SpawnGroup::RespawnIfInVicinity(), and SpawnGroup::Spawn().
SetCreatureRespawnTime()
void MapPersistentState::SetCreatureRespawnTime (uint32 loguid, time_t t) private
Definition at line 135 of file MapPersistentStateMgr.cpp.
References m_creatureRespawnTimes, sWorld, and UnloadIfEmpty().
Referenced by MapPersistentStateManager::LoadCreatureRespawnTimes(), and SaveCreatureRespawnTime().
SetGORespawnTime()
void MapPersistentState::SetGORespawnTime (uint32 loguid, time_t t) private
Definition at line 146 of file MapPersistentStateMgr.cpp.
References m_goRespawnTimes, sWorld, and UnloadIfEmpty().
Referenced by MapPersistentStateManager::LoadGameobjectRespawnTimes(), and SaveGORespawnTime().
SetUsedByMapState()
void MapPersistentState::SetUsedByMapState (Map * map) inline
Definition at line 85 of file MapPersistentStateMgr.h.
References m_usedByMap, and UnloadIfEmpty().
Referenced by Map::Initialize(), and Map::~Map().
UnloadIfEmpty()
bool MapPersistentState::UnloadIfEmpty () protected
Definition at line 62 of file MapPersistentStateMgr.cpp.
References CanBeUnload(), GetInstanceId(), GetMapId(), and sMapPersistentStateMgr.
Referenced by ClearRespawnTimes(), DungeonPersistentState::RemoveGroup(), DungeonPersistentState::RemovePlayer(), SetCreatureRespawnTime(), SetGORespawnTime(), and SetUsedByMapState().
Friends And Related Function Documentation
MapPersistentStateManager
friend class MapPersistentStateManager friend
Definition at line 60 of file MapPersistentStateMgr.h.
Field Documentation
m_creatureRespawnTimes
RespawnTimes MapPersistentState::m_creatureRespawnTimes private
Definition at line 144 of file MapPersistentStateMgr.h.
Referenced by ClearRespawnTimes(), GetCreatureRespawnTime(), HasRespawnTimes(), and SetCreatureRespawnTime().
m_difficulty
Difficulty MapPersistentState::m_difficulty private
Definition at line 140 of file MapPersistentStateMgr.h.
Referenced by GetDifficulty().
m_goRespawnTimes
RespawnTimes MapPersistentState::m_goRespawnTimes private
Definition at line 145 of file MapPersistentStateMgr.h.
Referenced by ClearRespawnTimes(), GetGORespawnTime(), HasRespawnTimes(), and SetGORespawnTime().
m_gridObjectGuids
MapCellObjectGuidsMap MapPersistentState::m_gridObjectGuids private
Definition at line 146 of file MapPersistentStateMgr.h.
Referenced by AddCreatureToGrid(), AddGameobjectToGrid(), GetCellObjectGuids(), RemoveCreatureFromGrid(), and RemoveGameobjectFromGrid().
m_instanceid
uint32 MapPersistentState::m_instanceid private
Definition at line 138 of file MapPersistentStateMgr.h.
Referenced by GetInstanceId(), SaveCreatureRespawnTime(), and SaveGORespawnTime().
m_mapid
uint32 MapPersistentState::m_mapid private
Definition at line 139 of file MapPersistentStateMgr.h.
Referenced by GetMapEntry(), and GetMapId().
m_spawnedPoolData
SpawnedPoolData MapPersistentState::m_spawnedPoolData private
Definition at line 148 of file MapPersistentStateMgr.h.
Referenced by GetSpawnedPoolData().
m_usedByMap
Map* MapPersistentState::m_usedByMap private
Definition at line 141 of file MapPersistentStateMgr.h.
Referenced by CanBeUnload(), GetMap(), IsUsedByMap(), and SetUsedByMapState().
The documentation for this class was generated from the following files:
MapPersistentStateMgr.h
MapPersistentStateMgr.cpp