CMaNGOS_WoTLK: Movement::MoveSpline Class Reference
Movement::MoveSpline Class Reference
#include <MoveSpline.h>
Public Types
enum UpdateResult { Result_None = 0x01 , Result_Arrived = 0x02 , Result_NextCycle = 0x04 , Result_NextSegment = 0x08 }
typedef Spline< int32 > MySpline
Public Member Functions
const MySpline & _Spline () const
int32 _currentSplineIdx () const
void _Finalize ()
void _Interrupt ()
float GetElapsedValue () const
void Initialize (const MoveSplineInitArgs &)
bool Initialized () const
MoveSpline ()
template<class UpdateHandler >
void updateState (uint32 difftime, UpdateHandler &handler)
void updateState (uint32 difftime)
Location ComputePosition () const
uint32 GetId () const
bool Finalized () const
bool isCyclic () const
FacingInfo const & GetFacing () const
bool isFacing () const
bool isFacingPoint () const
bool isFacingTarget () const
bool isFacingAngle () const
bool IsBoarding () const
const Vector3 FinalDestination () const
const Vector3 CurrentDestination () const
int32 currentPathIdx () const
int32 GetRawPathIndex () const
uint32 Duration () const
uint32 DurationAtPointIdx (uint32 idx) const
int32 ComputeTimeToIndex (uint32 idx) const
float Speed () const
std::string ToString () const
Protected Member Functions
void init_spline (const MoveSplineInitArgs &args)
const MySpline::ControlArray & getPath () const
void computeParabolicElevation (float &el) const
void computeFallElevation (float &el) const
UpdateResult _updateState (uint32 &ms_time_diff)
============================================================================================
uint32 next_timestamp () const
uint32 segment_time_elapsed () const
uint32 timeElapsed () const
uint32 timePassed () const
Protected Attributes
MySpline spline
FacingInfo facing
uint32 m_Id
MoveSplineFlag splineflags
float speed
uint32 time_passed
float vertical_acceleration
float initialOrientation
int32 parabolic_start_time
int32 animation_start_time
int32 point_Idx
int32 point_Idx_offset
Friends
class PacketBuilder
Detailed Description
Definition at line 51 of file MoveSpline.h.
Member Typedef Documentation
MySpline
typedef Spline<int32> Movement::MoveSpline::MySpline
Definition at line 54 of file MoveSpline.h.
Member Enumeration Documentation
UpdateResult
enum Movement::MoveSpline::UpdateResult
Enumerator
Result_None
Result_Arrived
Result_NextCycle
Result_NextSegment
Definition at line 55 of file MoveSpline.h.
Constructor & Destructor Documentation
MoveSpline()
Movement::MoveSpline::MoveSpline () explicit
Definition at line 201 of file MoveSpline.cpp.
References Movement::MoveSplineFlag::done, and splineflags.
Member Function Documentation
_currentSplineIdx()
int32 Movement::MoveSpline::_currentSplineIdx () const inline
Definition at line 100 of file MoveSpline.h.
References point_Idx.
_Finalize()
void Movement::MoveSpline::_Finalize ()
Definition at line 346 of file MoveSpline.cpp.
References Movement::MoveSplineFlag::done, Duration(), Movement::SplineBase::last(), point_Idx, spline, splineflags, and time_passed.
Referenced by _updateState(), Unit::SetFacingTo(), and Unit::SetFacingToObject().
_Interrupt()
void Movement::MoveSpline::_Interrupt () inline
Definition at line 102 of file MoveSpline.h.
References Movement::MoveSplineFlag::done, and splineflags.
Referenced by Unit::DisableSpline(), and Unit::InterruptMoving().
_Spline()
const MySpline& Movement::MoveSpline::_Spline () const inline
Definition at line 99 of file MoveSpline.h.
References spline.
_updateState()
MoveSpline::UpdateResult Movement::MoveSpline::_updateState (uint32 & ms_time_diff) protected
============================================================================================
Definition at line 252 of file MoveSpline.cpp.
References _Finalize(), Duration(), Movement::MoveSplineFlag::enter_cycle, facing, Finalized(), Movement::SplineBase::first(), Movement::SplineBase::getPointCount(), Movement::SplineBase::getPoints(), init_spline(), Initialize(), Movement::SplineBase::isCyclic(), Movement::SplineBase::last(), m_Id, next_timestamp(), point_Idx, point_Idx_offset, Result_Arrived, Result_NextSegment, Result_None, segment_time_elapsed(), spline, splineflags, and time_passed.
Referenced by updateState().
computeFallElevation()
void Movement::MoveSpline::computeFallElevation (float & el) const protected
Definition at line 85 of file MoveSpline.cpp.
References Movement::computeFallElevation(), FinalDestination(), Movement::SplineBase::first(), Movement::SplineBase::getPoint(), Movement::MSToSec(), spline, and time_passed.
Referenced by ComputePosition().
computeParabolicElevation()
void Movement::MoveSpline::computeParabolicElevation (float & el) const protected
Definition at line 72 of file MoveSpline.cpp.
References Duration(), Movement::MSToSec(), parabolic_start_time, time_passed, and vertical_acceleration.
Referenced by ComputePosition().
ComputePosition()
Location Movement::MoveSpline::ComputePosition () const
Definition at line 30 of file MoveSpline.cpp.
References Movement::FacingInfo::angle, Movement::MoveSplineFlag::animation, computeFallElevation(), computeParabolicElevation(), Movement::MoveSplineFlag::done, Movement::Spline< length_type >::evaluate_derivative(), Movement::Spline< length_type >::evaluate_percent(), Movement::FacingInfo::f, facing, Movement::MoveSplineFlag::Falling, Movement::MoveSplineFlag::falling, Movement::MoveSplineFlag::final_angle, Movement::MoveSplineFlag::final_point, Movement::MoveSplineFlag::hasFlag(), Initialized(), initialOrientation, Movement::MoveSplineFlag::isFacing(), Movement::Spline< length_type >::length(), MANGOS_ASSERT, Movement::Location::orientation, Movement::MoveSplineFlag::OrientationFixed, Movement::MoveSplineFlag::orientationInversed, Movement::MoveSplineFlag::parabolic, point_Idx, spline, splineflags, time_passed, Movement::FacingInfo::x, and Movement::FacingInfo::y.
Referenced by FormationMovementGenerator::BuildPath(), Movement::MoveSplineInit::Launch(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), CharmInfo::SetStayPosition(), Movement::MoveSplineInit::Stop(), and Unit::UpdateSplinePosition().
ComputeTimeToIndex()
int32 Movement::MoveSpline::ComputeTimeToIndex (uint32 idx) const inline
Definition at line 146 of file MoveSpline.h.
References Movement::Spline< length_type >::length(), spline, and time_passed.
CurrentDestination()
const Vector3 Movement::MoveSpline::CurrentDestination () const inline
Definition at line 140 of file MoveSpline.h.
References Movement::SplineBase::getPoint(), Initialized(), point_Idx, and spline.
currentPathIdx()
int32 Movement::MoveSpline::currentPathIdx () const
Definition at line 370 of file MoveSpline.cpp.
References Finalized(), Movement::SplineBase::first(), isCyclic(), Movement::SplineBase::last(), point_Idx, point_Idx_offset, and spline.
Referenced by ToString(), WaypointMovementGenerator< Creature >::Update(), AbstractPathMovementGenerator::Update(), and TaxiMovementGenerator::Update().
Duration()
uint32 Movement::MoveSpline::Duration () const inline
Definition at line 144 of file MoveSpline.h.
References Movement::Spline< length_type >::length(), and spline.
Referenced by _Finalize(), _updateState(), computeParabolicElevation(), GetElapsedValue(), Initialize(), Movement::MoveSplineInit::Launch(), timeElapsed(), ToString(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::PacketBuilder::WriteCreate().
DurationAtPointIdx()
uint32 Movement::MoveSpline::DurationAtPointIdx (uint32 idx) const inline
Definition at line 145 of file MoveSpline.h.
References Movement::Spline< length_type >::length(), and spline.
Referenced by Initialize().
FinalDestination()
const Vector3 Movement::MoveSpline::FinalDestination () const
Definition at line 358 of file MoveSpline.cpp.
References Movement::SplineBase::getPoint(), Initialized(), isCyclic(), Movement::SplineBase::last(), and spline.
Referenced by computeFallElevation(), MotionMaster::GetDestination(), ChaseMovementGenerator::HandleTargetedMovement(), AbstractPathMovementGenerator::Update(), and Movement::PacketBuilder::WriteCreate().
Finalized()
bool Movement::MoveSpline::Finalized () const inline
Definition at line 131 of file MoveSpline.h.
References Movement::MoveSplineFlag::done, and splineflags.
Referenced by _updateState(), FormationMovementGenerator::BuildPath(), currentPathIdx(), ChaseMovementGenerator::DispatchSplineToPosition(), NamreebAnticheat::Movement::ExtrapolateMovement(), AbstractPathMovementGenerator::Finalize(), AbstractRandomMovementGenerator::Finalize(), AbstractWrapperMovementGenerator::Finalize(), PointMovementGenerator::Finalize(), MotionMaster::GetDestination(), NamreebAnticheat::Movement::GetMaxAllowedDist(), Unit::GetSpeedInMotion(), Unit::GetSpeedRateInMotion(), NamreebAnticheat::Movement::HandleAnticheatTests(), ChaseMovementGenerator::HandleTargetedMovement(), FormationMovementGenerator::HandleTargetedMovement(), AbstractPathMovementGenerator::Initialize(), AbstractRandomMovementGenerator::Initialize(), AbstractWrapperMovementGenerator::Initialize(), PointMovementGenerator::Initialize(), AbstractWrapperMovementGenerator::Interrupt(), Unit::InterruptMoving(), Movement::MoveSplineInit::Launch(), FollowMovementGenerator::Move(), FixedPathMovementGenerator::Move(), PathJumpGenerator::Move(), WaypointMovementGenerator< Creature >::OnArrived(), WorldSession::ProcessMovementInfo(), Unit::SendFlightSplineSyncIfNeeded(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), CharmInfo::SetStayPosition(), Movement::MoveSplineInit::Stop(), HomeMovementGenerator< Creature >::Update(), WaypointMovementGenerator< Creature >::Update(), AbstractPathMovementGenerator::Update(), AbstractWrapperMovementGenerator::Update(), AbstractRandomMovementGenerator::Update(), PointMovementGenerator::Update(), TaxiMovementGenerator::Update(), Unit::UpdateSplineMovement(), and NamreebAnticheat::Movement::VerifyMovementFlags().
GetElapsedValue()
float Movement::MoveSpline::GetElapsedValue () const inline
Definition at line 103 of file MoveSpline.h.
References Duration(), and time_passed.
Referenced by Unit::SendFlightSplineSyncIfNeeded().
GetFacing()
FacingInfo const& Movement::MoveSpline::GetFacing () const inline
Definition at line 133 of file MoveSpline.h.
References facing.
Referenced by AbstractWrapperMovementGenerator::Initialize(), and Unit::UpdateSplinePosition().
GetId()
uint32 Movement::MoveSpline::GetId (void) const inline
Definition at line 130 of file MoveSpline.h.
References m_Id.
Referenced by Movement::MoveSplineInit::Stop(), ToString(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::PacketBuilder::WriteCreate().
getPath()
const MySpline::ControlArray& Movement::MoveSpline::getPath () const inline protected
Definition at line 88 of file MoveSpline.h.
References Movement::SplineBase::getPoints(), and spline.
Referenced by Movement::PacketBuilder::WriteCreate().
GetRawPathIndex()
int32 Movement::MoveSpline::GetRawPathIndex () const inline
Definition at line 142 of file MoveSpline.h.
References point_Idx.
init_spline()
void Movement::MoveSpline::init_spline (const MoveSplineInitArgs & args) protected
Definition at line 127 of file MoveSpline.cpp.
References Movement::MoveSplineFlag::cyclic, Movement::MoveSplineFlag::enter_cycle, Movement::MoveSplineFlag::falling, Movement::SplineBase::first(), Movement::MoveSplineInitArgs::flags, Movement::SplineBase::getPoint(), Movement::Spline< length_type >::init_cyclic_spline(), Movement::Spline< length_type >::init_spline(), Movement::Spline< length_type >::initLengths(), Movement::SplineBase::isCyclic(), Movement::MoveSplineFlag::isSmooth(), Movement::SplineBase::last(), Movement::Spline< length_type >::length(), Movement::minimal_duration, Movement::SplineBase::ModeCatmullrom, Movement::SplineBase::ModeLinear, Movement::MoveSplineInitArgs::path, point_Idx, Movement::Spline< length_type >::set_length(), sLog, speed, spline, splineflags, and Movement::MoveSplineInitArgs::velocity.
Referenced by _updateState(), and Initialize().
Initialize()
void Movement::MoveSpline::Initialize (const MoveSplineInitArgs & args)
Definition at line 164 of file MoveSpline.cpp.
References Movement::MoveSplineFlag::Animation, Movement::MoveSplineInitArgs::animation_start_Idx, animation_start_time, Movement::Spline< length_type >::clear(), Movement::MoveSplineFlag::done, Duration(), DurationAtPointIdx(), facing, Movement::MoveSplineInitArgs::facing, Movement::MoveSplineInitArgs::flags, init_spline(), initialOrientation, Movement::MoveSplineInitArgs::initialOrientation, m_Id, Movement::MSToSec(), Movement::MoveSplineFlag::Parabolic, Movement::MoveSplineFlag::parabolic, Movement::MoveSplineInitArgs::parabolic_amplitude, Movement::MoveSplineInitArgs::parabolic_start_Idx, parabolic_start_time, Movement::MoveSplineInitArgs::path_Idx_offset, point_Idx_offset, spline, splineflags, Movement::MoveSplineInitArgs::splineId, time_passed, and vertical_acceleration.
Referenced by _updateState(), Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
Initialized()
bool Movement::MoveSpline::Initialized () const inline
Definition at line 108 of file MoveSpline.h.
References Movement::SplineBase::empty(), and spline.
Referenced by ComputePosition(), CurrentDestination(), FinalDestination(), and updateState().
IsBoarding()
bool Movement::MoveSpline::IsBoarding () const
Definition at line 353 of file MoveSpline.cpp.
References Movement::MoveSplineFlag::boardVehicle, Movement::MoveSplineFlag::exitVehicle, and splineflags.
Referenced by Object::BuildMovementUpdate(), and WorldSession::ProcessMovementInfo().
isCyclic()
bool Movement::MoveSpline::isCyclic () const inline
Definition at line 132 of file MoveSpline.h.
References Movement::MoveSplineFlag::cyclic, and splineflags.
Referenced by currentPathIdx(), FinalDestination(), Unit::SendFlightSplineSyncIfNeeded(), and Movement::PacketBuilder::WriteCreate().
isFacing()
bool Movement::MoveSpline::isFacing () const inline
Definition at line 134 of file MoveSpline.h.
References Movement::MoveSplineFlag::isFacing(), and splineflags.
Referenced by Unit::UpdateSplinePosition().
isFacingAngle()
bool Movement::MoveSpline::isFacingAngle () const inline
Definition at line 137 of file MoveSpline.h.
References Movement::MoveSplineFlag::final_angle, and splineflags.
Referenced by Unit::UpdateSplinePosition().
isFacingPoint()
bool Movement::MoveSpline::isFacingPoint () const inline
Definition at line 135 of file MoveSpline.h.
References Movement::MoveSplineFlag::final_point, and splineflags.
Referenced by Unit::UpdateSplinePosition().
isFacingTarget()
bool Movement::MoveSpline::isFacingTarget () const inline
Definition at line 136 of file MoveSpline.h.
References Movement::MoveSplineFlag::final_target, and splineflags.
Referenced by AbstractWrapperMovementGenerator::Initialize(), and Unit::UpdateSplinePosition().
next_timestamp()
uint32 Movement::MoveSpline::next_timestamp () const inline protected
Definition at line 93 of file MoveSpline.h.
References Movement::Spline< length_type >::length(), point_Idx, and spline.
Referenced by _updateState(), and segment_time_elapsed().
segment_time_elapsed()
uint32 Movement::MoveSpline::segment_time_elapsed () const inline protected
Definition at line 94 of file MoveSpline.h.
References next_timestamp(), and time_passed.
Referenced by _updateState().
Speed()
float Movement::MoveSpline::Speed () const inline
Definition at line 148 of file MoveSpline.h.
References speed.
Referenced by Unit::GetSpeedInMotion(), and Unit::GetSpeedRateInMotion().
timeElapsed()
uint32 Movement::MoveSpline::timeElapsed () const inline protected
Definition at line 95 of file MoveSpline.h.
References Duration(), and time_passed.
timePassed()
uint32 Movement::MoveSpline::timePassed () const inline protected
Definition at line 96 of file MoveSpline.h.
References time_passed.
Referenced by Movement::PacketBuilder::WriteCreate().
ToString()
std::string Movement::MoveSpline::ToString () const
Definition at line 325 of file MoveSpline.cpp.
References Movement::FacingInfo::angle, currentPathIdx(), Duration(), Movement::FacingInfo::f, facing, Movement::MoveSplineFlag::final_angle, Movement::MoveSplineFlag::final_point, Movement::MoveSplineFlag::final_target, GetId(), point_Idx, spline, splineflags, Movement::FacingInfo::target, time_passed, Movement::MoveSplineFlag::ToString(), Movement::SplineBase::ToString(), Movement::FacingInfo::x, Movement::FacingInfo::y, and Movement::FacingInfo::z.
updateState() [1/2]
void Movement::MoveSpline::updateState (uint32 difftime) inline
Definition at line 121 of file MoveSpline.h.
References _updateState(), Initialized(), and MANGOS_ASSERT.
updateState() [2/2]
template<class UpdateHandler > void Movement::MoveSpline::updateState (uint32 difftime, UpdateHandler & handler) inline
Definition at line 113 of file MoveSpline.h.
References _updateState(), Initialized(), and MANGOS_ASSERT.
Referenced by Unit::UpdateSplineMovement().
Friends And Related Function Documentation
PacketBuilder
friend class PacketBuilder friend
Definition at line 62 of file MoveSpline.h.
Field Documentation
animation_start_time
int32 Movement::MoveSpline::animation_start_time protected
Definition at line 81 of file MoveSpline.h.
Referenced by Initialize(), and Movement::PacketBuilder::WriteCommonMonsterMovePart().
facing
FacingInfo Movement::MoveSpline::facing protected
Definition at line 66 of file MoveSpline.h.
Referenced by _updateState(), ComputePosition(), GetFacing(), Initialize(), ToString(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::PacketBuilder::WriteCreate().
initialOrientation
float Movement::MoveSpline::initialOrientation protected
Definition at line 79 of file MoveSpline.h.
Referenced by ComputePosition(), and Initialize().
m_Id
uint32 Movement::MoveSpline::m_Id protected
Definition at line 68 of file MoveSpline.h.
Referenced by _updateState(), GetId(), and Initialize().
parabolic_start_time
int32 Movement::MoveSpline::parabolic_start_time protected
Definition at line 80 of file MoveSpline.h.
Referenced by computeParabolicElevation(), Initialize(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::PacketBuilder::WriteCreate().
point_Idx
int32 Movement::MoveSpline::point_Idx protected
Definition at line 82 of file MoveSpline.h.
Referenced by _currentSplineIdx(), _Finalize(), _updateState(), ComputePosition(), CurrentDestination(), currentPathIdx(), GetRawPathIndex(), init_spline(), next_timestamp(), and ToString().
point_Idx_offset
int32 Movement::MoveSpline::point_Idx_offset protected
Definition at line 83 of file MoveSpline.h.
Referenced by _updateState(), currentPathIdx(), and Initialize().
speed
float Movement::MoveSpline::speed protected
Definition at line 72 of file MoveSpline.h.
Referenced by init_spline(), and Speed().
spline
MySpline Movement::MoveSpline::spline protected
Definition at line 64 of file MoveSpline.h.
Referenced by _Finalize(), _Spline(), _updateState(), computeFallElevation(), ComputePosition(), ComputeTimeToIndex(), CurrentDestination(), currentPathIdx(), Duration(), DurationAtPointIdx(), FinalDestination(), getPath(), init_spline(), Initialize(), Initialized(), next_timestamp(), ToString(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), Movement::PacketBuilder::WriteCreate(), and Movement::PacketBuilder::WriteMonsterMove().
splineflags
MoveSplineFlag Movement::MoveSpline::splineflags protected
Definition at line 70 of file MoveSpline.h.
Referenced by _Finalize(), _Interrupt(), _updateState(), ComputePosition(), Finalized(), init_spline(), Initialize(), IsBoarding(), isCyclic(), isFacing(), isFacingAngle(), isFacingPoint(), isFacingTarget(), MoveSpline(), ToString(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), Movement::PacketBuilder::WriteCreate(), and Movement::PacketBuilder::WriteMonsterMove().
time_passed
uint32 Movement::MoveSpline::time_passed protected
Definition at line 74 of file MoveSpline.h.
Referenced by _Finalize(), _updateState(), computeFallElevation(), computeParabolicElevation(), ComputePosition(), ComputeTimeToIndex(), GetElapsedValue(), Initialize(), segment_time_elapsed(), timeElapsed(), timePassed(), and ToString().
vertical_acceleration
float Movement::MoveSpline::vertical_acceleration protected
Definition at line 78 of file MoveSpline.h.
Referenced by computeParabolicElevation(), Initialize(), Movement::PacketBuilder::WriteCommonMonsterMovePart(), and Movement::PacketBuilder::WriteCreate().
The documentation for this class was generated from the following files:
MoveSpline.h
MoveSpline.cpp