CMaNGOS_WoTLK: MaNGOS::AnySpellAssistableUnitInObjectRangeCheck Class Reference
MaNGOS::AnySpellAssistableUnitInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnySpellAssistableUnitInObjectRangeCheck (WorldObject const *obj, SpellEntry const *spellInfo, float range, bool ignorePhase=false)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
WorldObject const * i_obj
SpellEntry const * i_spellInfo
float i_range
bool i_ignorePhase
Detailed Description
Definition at line 1145 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnySpellAssistableUnitInObjectRangeCheck()
MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::AnySpellAssistableUnitInObjectRangeCheck (WorldObject const * obj, SpellEntry const * spellInfo, float range, bool ignorePhase = false) inline
Definition at line 1148 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::GetFocusObject () const inline
Definition at line 1150 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::operator() (Unit * u) inline
Definition at line 1151 of file GridNotifiers.h.
References WorldObject::CanAssistSpell(), i_ignorePhase, i_obj, i_range, i_spellInfo, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_ignorePhase
bool MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::i_ignorePhase private
Definition at line 1159 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const* MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::i_obj private
Definition at line 1156 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::i_range private
Definition at line 1158 of file GridNotifiers.h.
Referenced by operator()().
i_spellInfo
SpellEntry const* MaNGOS::AnySpellAssistableUnitInObjectRangeCheck::i_spellInfo private
Definition at line 1157 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h