CMaNGOS_WoTLK: LootTemplate::LootGroup Class Reference
LootTemplate::LootGroup Class Reference
Public Member Functions
void AddEntry (LootStoreItem &item)
bool HasQuestDrop () const
bool HasQuestDropForPlayer (Player const *player) const
void Process (Loot &loot, Player const *lootOwner) const
float RawTotalChance () const
float TotalChance () const
void Verify (LootStore const &lootstore, uint32 id, uint32 group_id) const
void CheckLootRefs (LootIdSet *ref_set) const
Private Member Functions
LootStoreItem const * Roll (Loot const &loot, Player const *lootOwner) const
Private Attributes
LootStoreItemList ExplicitlyChanced
LootStoreItemList EqualChanced
Detailed Description
Definition at line 61 of file LootMgr.cpp.
Member Function Documentation
AddEntry()
void LootTemplate::LootGroup::AddEntry (LootStoreItem & item)
Definition at line 2456 of file LootMgr.cpp.
References LootStoreItem::chance, EqualChanced, and ExplicitlyChanced.
CheckLootRefs()
void LootTemplate::LootGroup::CheckLootRefs (LootIdSet * ref_set) const
Definition at line 2607 of file LootMgr.cpp.
References LootStore::GetLootFor(), LootTemplates_Reference, and LootStore::ReportNotExistedId().
HasQuestDrop()
bool LootTemplate::LootGroup::HasQuestDrop () const
Definition at line 2539 of file LootMgr.cpp.
HasQuestDropForPlayer()
bool LootTemplate::LootGroup::HasQuestDropForPlayer (Player const * player) const
Definition at line 2551 of file LootMgr.cpp.
References Player::HasQuestForItem().
Process()
void LootTemplate::LootGroup::Process (Loot & loot, Player const * lootOwner) const
Definition at line 2563 of file LootMgr.cpp.
References Loot::AddItem().
RawTotalChance()
float LootTemplate::LootGroup::RawTotalChance () const
Definition at line 2571 of file LootMgr.cpp.
Roll()
LootStoreItem const * LootTemplate::LootGroup::Roll (Loot const & loot, Player const * lootOwner) const private
Definition at line 2465 of file LootMgr.cpp.
References LootStoreItem::chance, LootStoreItem::conditionId, GetRandomGenerator(), Loot::IsItemAlreadyIn(), LootStoreItem::itemid, LootTemplate::PlayerOrGroupFulfilsCondition(), rand_chance_f(), sLog, and urand().
TotalChance()
float LootTemplate::LootGroup::TotalChance () const
Definition at line 2583 of file LootMgr.cpp.
Verify()
void LootTemplate::LootGroup::Verify (LootStore const & lootstore, uint32 id, uint32 group_id) const
Definition at line 2593 of file LootMgr.cpp.
References LootStore::GetName(), and sLog.
Field Documentation
EqualChanced
LootStoreItemList LootTemplate::LootGroup::EqualChanced private
Definition at line 76 of file LootMgr.cpp.
Referenced by AddEntry().
ExplicitlyChanced
LootStoreItemList LootTemplate::LootGroup::ExplicitlyChanced private
Definition at line 75 of file LootMgr.cpp.
Referenced by AddEntry().
The documentation for this class was generated from the following file:
LootMgr.cpp