CMaNGOS_WoTLK: WaypointMovementGenerator< Creature > Class Reference
WaypointMovementGenerator< Creature > Class Reference
#include <WaypointMovementGenerator.h>
Public Member Functions
WaypointMovementGenerator (Creature &)
~WaypointMovementGenerator ()
void Initialize (Creature &creature)
void Interrupt (Creature &)
void Finalize (Creature &)
void Reset (Creature &creature)
bool Update (Creature &creature, const uint32 &diff)
void InitializeWaypointPath (Creature &u, int32 pathId, WaypointPathOrigin wpSource, uint32 initialDelay, uint32 overwriteEntry=0)
MovementGeneratorType GetMovementGeneratorType () const
bool GetResetPosition (Creature &, float &, float &, float &, float &) const
uint32 getLastReachedWaypoint () const
void GetPathInformation (uint32 &pathId, WaypointPathOrigin &wpOrigin) const
void GetPathInformation (std::ostringstream &oss) const
void AddToWaypointPauseTime (int32 waitTimeDiff, bool force=false)
bool SetNextWaypoint (uint32 pointId)
void SetForcedMovement (ForcedMovement forcedMovement)
void SetGuid (ObjectGuid guid)
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGeneratorMedium< Creature, WaypointMovementGenerator< Creature > >
void Initialize (Unit &u) override
void Initialize (U &u)
void Finalize (Unit &u) override
void Finalize (U &u)
void Interrupt (Unit &u) override
void Interrupt (U &u)
void Reset (Unit &u) override
void Reset (U &u)
bool Update (Unit &u, const uint32 &time_diff) override
bool Update (U &u, const uint32 &time_diff)
bool GetResetPosition (Unit &u, float &x, float &y, float &z, float &o) const override
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Public Member Functions inherited from PathMovementBase< Creature, WaypointPath const * >
PathMovementBase ()
virtual ~PathMovementBase ()
void LoadPath (Creature &)
uint32 GetCurrentNode () const
Protected Member Functions
virtual void SwitchToNextNode (Creature &creature, WaypointPath::const_iterator &nodeItr)
virtual bool GetNodeAfter (WaypointPath::const_iterator &nodeItr, bool looped=false)
Private Member Functions
void LoadPath (Creature &creature, int32 pathId, WaypointPathOrigin wpOrigin, uint32 overwriteEntry)
uint32 BuildIntPath (Movement::PointsArray &path, Creature &creature, G3D::Vector3 const &endPos)
void Stop (int32 time)
bool Stopped (Creature &u)
bool CanMove (int32 diff, Creature &u)
void OnArrived (Creature &)
void SendNextWayPointPath (Creature &)
void InformAI (Creature &creature, uint32 type, uint32 data)
Private Attributes
WaypointPath::const_iterator m_currentWaypointNode
ShortTimeTracker i_nextMoveTime
int32 m_scriptTime
uint32 m_lastReachedWaypoint
Position m_resetPoint
uint32 m_pathId
int32 m_pathDuration
std::list< int32 > m_nodeIndexes
WaypointPathOrigin m_PathOrigin
bool m_speedChanged
ForcedMovement m_forcedMovement
ObjectGuid m_guid
Additional Inherited Members
Protected Attributes inherited from PathMovementBase< Creature, WaypointPath const * >
WaypointPath const * i_path
uint32 i_currentNode
Detailed Description
Definition at line 69 of file WaypointMovementGenerator.h.
Constructor & Destructor Documentation
WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::WaypointMovementGenerator (Creature &) inline
Definition at line 74 of file WaypointMovementGenerator.h.
~WaypointMovementGenerator()
WaypointMovementGenerator< Creature >::~WaypointMovementGenerator () inline
Definition at line 78 of file WaypointMovementGenerator.h.
Member Function Documentation
AddToWaypointPauseTime()
void WaypointMovementGenerator< Creature >::AddToWaypointPauseTime (int32 waitTimeDiff, bool force = false)
Definition at line 569 of file WaypointMovementGenerator.cpp.
BuildIntPath()
uint32 WaypointMovementGenerator< Creature >::BuildIntPath (Movement::PointsArray & path, Creature & creature, G3D::Vector3 const & endPos) private
Definition at line 257 of file WaypointMovementGenerator.cpp.
References PathFinder::calculate(), MovementInfo::GetMovementFlags(), PathFinder::getPath(), Unit::GetSpeed(), MovementInfo::GetSpeedType(), and WorldObject::m_movementInfo.
CanMove()
bool WaypointMovementGenerator< Creature >::CanMove (int32 diff, Creature & u) private
Definition at line 506 of file WaypointMovementGenerator.cpp.
References Unit::hasUnitState(), and UNIT_STAT_WAYPOINT_PAUSED.
Finalize()
void WaypointMovementGenerator< Creature >::Finalize (Creature & creature)
Definition at line 135 of file WaypointMovementGenerator.cpp.
References Unit::clearUnitState(), Unit::hasUnitState(), Creature::SetWalk(), UNIT_STAT_ROAMING, UNIT_STAT_ROAMING_MOVE, and UNIT_STAT_RUNNING_STATE.
getLastReachedWaypoint()
uint32 WaypointMovementGenerator< Creature >::getLastReachedWaypoint () const inline
Definition at line 89 of file WaypointMovementGenerator.h.
GetMovementGeneratorType()
MovementGeneratorType WaypointMovementGenerator< Creature >::GetMovementGeneratorType () const inline virtual
Implements MovementGenerator.
Definition at line 86 of file WaypointMovementGenerator.h.
References WAYPOINT_MOTION_TYPE.
GetNodeAfter()
bool WaypointMovementGenerator< Creature >::GetNodeAfter (WaypointPath::const_iterator & nodeItr, bool looped = false) protected virtual
Reimplemented in LinearWPMovementGenerator< Creature >.
Definition at line 290 of file WaypointMovementGenerator.cpp.
GetPathInformation() [1/2]
void WaypointMovementGenerator< Creature >::GetPathInformation (std::ostringstream & oss) const
Definition at line 563 of file WaypointMovementGenerator.cpp.
References WaypointManager::GetOriginString().
GetPathInformation() [2/2]
void WaypointMovementGenerator< Creature >::GetPathInformation (uint32 & pathId, WaypointPathOrigin & wpOrigin) const inline
Definition at line 90 of file WaypointMovementGenerator.h.
Referenced by MotionMaster::GetWaypointPathInformation().
GetResetPosition()
bool WaypointMovementGenerator< Creature >::GetResetPosition (Creature & , float & x, float & y, float & z, float & o) const
Definition at line 515 of file WaypointMovementGenerator.cpp.
References M_PI_F, MANGOS_ASSERT, WaypointNode::orientation, WaypointNode::x, WaypointNode::y, and WaypointNode::z.
InformAI()
void WaypointMovementGenerator< Creature >::InformAI (Creature & creature, uint32 type, uint32 data) private
Definition at line 417 of file WaypointMovementGenerator.cpp.
References Creature::AI(), Map::GetAnyTypeCreature(), WorldObject::GetMap(), WorldObject::GetSpawnerGuid(), ObjectGuid::IsCreatureOrPet(), Creature::IsTemporarySummon(), and UnitAI::MovementInform().
Initialize()
void WaypointMovementGenerator< Creature >::Initialize (Creature & creature)
Definition at line 86 of file WaypointMovementGenerator.cpp.
References Unit::addUnitState(), Unit::clearUnitState(), UNIT_STAT_ROAMING, and UNIT_STAT_WAYPOINT_PAUSED.
InitializeWaypointPath()
void WaypointMovementGenerator< Creature >::InitializeWaypointPath (Creature & u, int32 pathId, WaypointPathOrigin wpSource, uint32 initialDelay, uint32 overwriteEntry = 0)
Definition at line 92 of file WaypointMovementGenerator.cpp.
References Object::GetGuidStr(), WorldObject::GetPosition(), WorldObject::GetTransport(), and sLog.
Referenced by MotionMaster::MoveLinearWP(), and MotionMaster::MoveWaypoint().
Interrupt()
void WaypointMovementGenerator< Creature >::Interrupt (Creature & creature)
Definition at line 141 of file WaypointMovementGenerator.cpp.
References Unit::clearUnitState(), WorldObject::GetPosition(), WorldObject::GetTransport(), Unit::hasUnitState(), Unit::InterruptMoving(), Creature::SetWalk(), UNIT_STAT_ROAMING, UNIT_STAT_ROAMING_MOVE, and UNIT_STAT_RUNNING_STATE.
LoadPath()
void WaypointMovementGenerator< Creature >::LoadPath (Creature & creature, int32 pathId, WaypointPathOrigin wpOrigin, uint32 overwriteEntry) private
Definition at line 35 of file WaypointMovementGenerator.cpp.
References WaypointNode::delay, DETAIL_FILTER_LOG, Object::GetDbGuid(), Object::GetEntry(), Object::GetGuidStr(), LOG_FILTER_AI_AND_MOVEGENSS, PATH_FROM_ENTRY, PATH_FROM_EXTERNAL, PATH_NO_PATH, sLog, and sWaypointMgr.
OnArrived()
void WaypointMovementGenerator< Creature >::OnArrived (Creature & creature) private
Definition at line 173 of file WaypointMovementGenerator.cpp.
References Creature::AI(), Unit::clearUnitState(), DEBUG_FILTER_LOG, WaypointNode::delay, EXTERNAL_WAYPOINT_MOVE, EXTERNAL_WAYPOINT_MOVE_START, Movement::MoveSpline::Finalized(), UnitAI::GetCurrentWaypointPath(), Object::GetGuidStr(), WorldObject::GetMap(), WorldObject::GetPosition(), WorldObject::GetTransport(), Map::GetWorldObject(), LOG_FILTER_AI_AND_MOVEGENSS, Unit::movespline, PATH_FROM_EXTERNAL, PATH_FROM_WAYPOINT_PATH, WaypointNode::script_id, SCRIPT_TYPE_CREATURE_MOVEMENT, Map::ScriptsStart(), Movement::MoveSplineInit::Stop(), UNIT_STAT_ROAMING_MOVE, and WAYPOINT_MOTION_TYPE.
Reset()
void WaypointMovementGenerator< Creature >::Reset (Creature & creature)
Definition at line 155 of file WaypointMovementGenerator.cpp.
References Unit::addUnitState(), and UNIT_STAT_ROAMING.
SendNextWayPointPath()
void WaypointMovementGenerator< Creature >::SendNextWayPointPath (Creature & creature) private
Definition at line 305 of file WaypointMovementGenerator.cpp.
References Unit::addUnitState(), Creature::AI(), Movement::MoveSpline::ComputePosition(), WaypointNode::delay, EXTERNAL_WAYPOINT_FINISHED_LAST, EXTERNAL_WAYPOINT_MOVE_START, Movement::MoveSpline::Finalized(), FORCED_MOVEMENT_RUN, FORCED_MOVEMENT_WALK, UnitAI::GetCurrentWaypointPath(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTransport(), Unit::hasUnitState(), Unit::InterruptMoving(), Unit::IsAlive(), Unit::IsClientControlled(), Unit::IsDead(), Unit::IsImmobilizedState(), Object::IsInWorld(), Unit::IsNonMeleeSpellCasted(), Movement::MoveSplineInit::Launch(), MinimumPathTime, Movement::MoveSplineInit::MovebyPath(), Unit::movespline, WaypointNode::orientation, PATH_FROM_EXTERNAL, PATH_FROM_WAYPOINT_PATH, PreSendTime, Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetWalk(), Unit::StopMoving(), UNIT_STAT_ROAMING_MOVE, UNIT_STAT_RUNNING, WaypointNode::x, WaypointNode::y, and WaypointNode::z.
SetForcedMovement()
void WaypointMovementGenerator< Creature >::SetForcedMovement (ForcedMovement forcedMovement) inline
Definition at line 95 of file WaypointMovementGenerator.h.
Referenced by MotionMaster::MoveLinearWP(), and MotionMaster::MoveWaypoint().
SetGuid()
void WaypointMovementGenerator< Creature >::SetGuid (ObjectGuid guid) inline
Definition at line 96 of file WaypointMovementGenerator.h.
Referenced by MotionMaster::MoveLinearWP(), and MotionMaster::MoveWaypoint().
SetNextWaypoint()
bool WaypointMovementGenerator< Creature >::SetNextWaypoint (uint32 pointId)
Definition at line 587 of file WaypointMovementGenerator.cpp.
Stop()
void WaypointMovementGenerator< Creature >::Stop (int32 time) inline private
Definition at line 109 of file WaypointMovementGenerator.h.
Stopped()
bool WaypointMovementGenerator< Creature >::Stopped (Creature & u) private
Definition at line 501 of file WaypointMovementGenerator.cpp.
References Unit::hasUnitState(), and UNIT_STAT_WAYPOINT_PAUSED.
SwitchToNextNode()
void WaypointMovementGenerator< Creature >::SwitchToNextNode (Creature & creature, WaypointPath::const_iterator & nodeItr) protected virtual
Reimplemented in LinearWPMovementGenerator< Creature >.
Definition at line 163 of file WaypointMovementGenerator.cpp.
UnitSpeedChanged()
void WaypointMovementGenerator< Creature >::UnitSpeedChanged () inline override virtual
Reimplemented from MovementGenerator.
Definition at line 98 of file WaypointMovementGenerator.h.
Update()
bool WaypointMovementGenerator< Creature >::Update (Creature & creature, const uint32 & diff)
Definition at line 429 of file WaypointMovementGenerator.cpp.
References Unit::clearUnitState(), Movement::MoveSpline::currentPathIdx(), Movement::MoveSpline::Finalized(), Unit::hasUnitState(), Unit::IsNonMeleeSpellCasted(), Unit::IsStopped(), Unit::movespline, Movement::MoveSplineInit::Stop(), UNIT_STAT_NOT_MOVE, and UNIT_STAT_ROAMING_MOVE.
Field Documentation
i_nextMoveTime
ShortTimeTracker WaypointMovementGenerator< Creature >::i_nextMoveTime private
Definition at line 118 of file WaypointMovementGenerator.h.
m_currentWaypointNode
WaypointPath::const_iterator WaypointMovementGenerator< Creature >::m_currentWaypointNode private
Definition at line 117 of file WaypointMovementGenerator.h.
m_forcedMovement
ForcedMovement WaypointMovementGenerator< Creature >::m_forcedMovement private
Definition at line 129 of file WaypointMovementGenerator.h.
m_guid
ObjectGuid WaypointMovementGenerator< Creature >::m_guid private
Definition at line 131 of file WaypointMovementGenerator.h.
m_lastReachedWaypoint
uint32 WaypointMovementGenerator< Creature >::m_lastReachedWaypoint private
Definition at line 120 of file WaypointMovementGenerator.h.
m_nodeIndexes
std::list<int32> WaypointMovementGenerator< Creature >::m_nodeIndexes private
Definition at line 125 of file WaypointMovementGenerator.h.
m_pathDuration
int32 WaypointMovementGenerator< Creature >::m_pathDuration private
Definition at line 124 of file WaypointMovementGenerator.h.
m_pathId
uint32 WaypointMovementGenerator< Creature >::m_pathId private
Definition at line 123 of file WaypointMovementGenerator.h.
m_PathOrigin
WaypointPathOrigin WaypointMovementGenerator< Creature >::m_PathOrigin private
Definition at line 126 of file WaypointMovementGenerator.h.
m_resetPoint
Position WaypointMovementGenerator< Creature >::m_resetPoint private
Definition at line 121 of file WaypointMovementGenerator.h.
m_scriptTime
int32 WaypointMovementGenerator< Creature >::m_scriptTime private
Definition at line 119 of file WaypointMovementGenerator.h.
m_speedChanged
bool WaypointMovementGenerator< Creature >::m_speedChanged private
Definition at line 128 of file WaypointMovementGenerator.h.
The documentation for this class was generated from the following files:
WaypointMovementGenerator.h
WaypointMovementGenerator.cpp