CMaNGOS_WoTLK: MaNGOS::WorldWorldTextBuilder Class Reference
MaNGOS::WorldWorldTextBuilder Class Reference
Public Types
typedef std::vector< std::unique_ptr< WorldPacket > > WorldPacketList
Public Member Functions
WorldWorldTextBuilder (int32 textId, va_list *args=nullptr)
void operator() (WorldPacketList &data_list, int32 loc_idx)
Private Member Functions
char * lineFromMessage (char *&pos) const
void do_helper (WorldPacketList &data_list, char *text)
Private Attributes
int32 i_textId
va_list * i_args
Detailed Description
Definition at line 1765 of file World.cpp.
Member Typedef Documentation
WorldPacketList
typedef std::vector<std::unique_ptr<WorldPacket> > MaNGOS::WorldWorldTextBuilder::WorldPacketList
Definition at line 1768 of file World.cpp.
Constructor & Destructor Documentation
WorldWorldTextBuilder()
MaNGOS::WorldWorldTextBuilder::WorldWorldTextBuilder (int32 textId, va_list * args = nullptr) inline explicit
Definition at line 1769 of file World.cpp.
Member Function Documentation
do_helper()
void MaNGOS::WorldWorldTextBuilder::do_helper (WorldPacketList & data_list, char * text) inline private
Definition at line 1791 of file World.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_SYSTEM, and lineFromMessage().
Referenced by operator()().
lineFromMessage()
char* MaNGOS::WorldWorldTextBuilder::lineFromMessage (char *& pos) const inline private
Definition at line 1790 of file World.cpp.
Referenced by do_helper().
operator()()
void MaNGOS::WorldWorldTextBuilder::operator() (WorldPacketList & data_list, int32 loc_idx) inline
Definition at line 1770 of file World.cpp.
References do_helper(), i_args, i_textId, and sObjectMgr.
Field Documentation
i_args
va_list* MaNGOS::WorldWorldTextBuilder::i_args private
Definition at line 1804 of file World.cpp.
Referenced by operator()().
i_textId
int32 MaNGOS::WorldWorldTextBuilder::i_textId private
Definition at line 1803 of file World.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
World.cpp