CMaNGOS_WoTLK: SqlStatementID Class Reference
SqlStatementID Class Reference
#include <SqlPreparedStatement.h>
Public Member Functions
SqlStatementID ()
int ID () const
uint32 arguments () const
bool initialized () const
Private Member Functions
void init (int nID, uint32 nArgs)
Private Attributes
int m_nIndex
uint32 m_nArguments
bool m_bInitialized
Friends
class Database
Detailed Description
Definition at line 172 of file SqlPreparedStatement.h.
Constructor & Destructor Documentation
SqlStatementID()
SqlStatementID::SqlStatementID () inline
Definition at line 175 of file SqlPreparedStatement.h.
Member Function Documentation
arguments()
uint32 SqlStatementID::arguments () const inline
Definition at line 178 of file SqlPreparedStatement.h.
References m_nArguments.
Referenced by SqlStatement::arguments().
ID()
int SqlStatementID::ID () const inline
Definition at line 177 of file SqlPreparedStatement.h.
References m_nIndex.
Referenced by SqlStatement::ID().
init()
void SqlStatementID::init (int nID, uint32 nArgs) inline private
Definition at line 183 of file SqlPreparedStatement.h.
References m_bInitialized, m_nArguments, and m_nIndex.
Referenced by Database::CreateStatement().
initialized()
bool SqlStatementID::initialized () const inline
Definition at line 179 of file SqlPreparedStatement.h.
References m_bInitialized.
Referenced by Database::CreateStatement().
Friends And Related Function Documentation
Database
friend class Database friend
Definition at line 182 of file SqlPreparedStatement.h.
Field Documentation
m_bInitialized
bool SqlStatementID::m_bInitialized private
Definition at line 187 of file SqlPreparedStatement.h.
Referenced by init(), and initialized().
m_nArguments
uint32 SqlStatementID::m_nArguments private
Definition at line 186 of file SqlPreparedStatement.h.
Referenced by arguments(), and init().
m_nIndex
int SqlStatementID::m_nIndex private
Definition at line 185 of file SqlPreparedStatement.h.
Referenced by ID(), and init().
The documentation for this class was generated from the following file:
SqlPreparedStatement.h