CMaNGOS_WoTLK: WorldUpdateCounter Class Reference
WorldUpdateCounter Class Reference
#include <Object.h>
Public Member Functions
WorldUpdateCounter ()
time_t timeElapsed ()
void Reset ()
Private Attributes
uint32 m_tmStart
Detailed Description
Definition at line 367 of file Object.h.
Constructor & Destructor Documentation
WorldUpdateCounter()
WorldUpdateCounter::WorldUpdateCounter () inline
Definition at line 370 of file Object.h.
Member Function Documentation
Reset()
void WorldUpdateCounter::Reset () inline
Definition at line 380 of file Object.h.
References m_tmStart, and WorldTimer::tickTime().
timeElapsed()
time_t WorldUpdateCounter::timeElapsed () inline
Definition at line 372 of file Object.h.
References WorldTimer::getMSTimeDiff(), m_tmStart, WorldTimer::tickPrevTime(), and WorldTimer::tickTime().
Field Documentation
m_tmStart
uint32 WorldUpdateCounter::m_tmStart private
Definition at line 383 of file Object.h.
Referenced by Reset(), and timeElapsed().
The documentation for this class was generated from the following file:
Object.h