CMaNGOS_WoTLK: ThreatContainer Class Reference
ThreatContainer Class Reference
#include <ThreatManager.h>
Public Member Functions
ThreatContainer ()
~ThreatContainer ()
HostileReference * addThreat (Unit *victim, float threat)
void modifyThreatPercent (Unit *victim, int32 threatPercent)
void modifyAllThreatPercent (int32 threatPercent)
HostileReference * selectNextVictim (Unit *attacker, HostileReference *currentVictim)
void setDirty (bool dirty)
bool isDirty () const
bool empty () const
HostileReference * getMostHated ()
HostileReference * getReferenceByTarget (Unit *victim)
ThreatList const & getThreatList () const
Protected Member Functions
void remove (HostileReference *ref)
void addReference (HostileReference *hostileReference)
void clearReferences ()
void update (bool force, bool isPlayer)
Protected Attributes
ThreatList iThreatList
Private Attributes
bool iDirty
Friends
class ThreatManager
Detailed Description
Definition at line 152 of file ThreatManager.h.
Constructor & Destructor Documentation
ThreatContainer()
ThreatContainer::ThreatContainer () inline
Definition at line 155 of file ThreatManager.h.
References iDirty.
~ThreatContainer()
ThreatContainer::~ThreatContainer () inline
Definition at line 156 of file ThreatManager.h.
References clearReferences().
Member Function Documentation
addReference()
void ThreatContainer::addReference (HostileReference * hostileReference) inline protected
Definition at line 180 of file ThreatManager.h.
References iThreatList.
Referenced by ThreatManager::addThreatDirectly(), and ThreatManager::processThreatEvent().
addThreat()
HostileReference * ThreatContainer::addThreat (Unit * victim, float threat)
Definition at line 260 of file ThreatManager.cpp.
References HostileReference::addThreat(), and getReferenceByTarget().
Referenced by ThreatManager::addThreatDirectly().
clearReferences()
void ThreatContainer::clearReferences () protected
Definition at line 230 of file ThreatManager.cpp.
References iThreatList.
Referenced by ThreatManager::clearReferences(), and ~ThreatContainer().
empty()
bool ThreatContainer::empty () const inline
Definition at line 169 of file ThreatManager.h.
References iThreatList.
Referenced by ThreatManager::isThreatListEmpty().
getMostHated()
HostileReference* ThreatContainer::getMostHated () inline
Definition at line 171 of file ThreatManager.h.
References iThreatList.
getReferenceByTarget()
HostileReference * ThreatContainer::getReferenceByTarget (Unit * victim)
Definition at line 243 of file ThreatManager.cpp.
References Object::GetObjectGuid(), and iThreatList.
Referenced by addThreat(), ThreatManager::FixateTarget(), ThreatManager::getThreat(), ThreatManager::HasThreat(), modifyThreatPercent(), ThreatManager::setCurrentVictimByTarget(), and ThreatManager::SetTargetSuppressed().
getThreatList()
ThreatList const& ThreatContainer::getThreatList () const inline
Definition at line 175 of file ThreatManager.h.
References iThreatList.
Referenced by ThreatManager::ClearSuppressed(), ThreatManager::DeleteOutOfRangeReferences(), ThreatManager::FixateTarget(), ThreatManager::GetHighestThreat(), ThreatManager::getThreatList(), and ThreatManager::TauntUpdate().
isDirty()
bool ThreatContainer::isDirty () const inline
Definition at line 167 of file ThreatManager.h.
References iDirty.
modifyAllThreatPercent()
void ThreatContainer::modifyAllThreatPercent (int32 threatPercent)
Definition at line 287 of file ThreatManager.cpp.
References HostileReference::addThreatPercent(), iThreatList, and HostileReference::removeReference().
Referenced by ThreatManager::modifyAllThreatPercent().
modifyThreatPercent()
void ThreatContainer::modifyThreatPercent (Unit * victim, int32 threatPercent)
Definition at line 270 of file ThreatManager.cpp.
References getReferenceByTarget().
Referenced by ThreatManager::modifyThreatPercent().
remove()
void ThreatContainer::remove (HostileReference * ref) inline protected
Definition at line 179 of file ThreatManager.h.
References iThreatList.
Referenced by ThreatManager::processThreatEvent().
selectNextVictim()
HostileReference * ThreatContainer::selectNextVictim (Unit * attacker, HostileReference * currentVictim)
Definition at line 350 of file ThreatManager.cpp.
References Unit::CanReachWithMeleeAttack(), HostileReference::GetHostileState(), Reference< TO, FROM >::getTarget(), HostileReference::GetTauntState(), HostileReference::getThreat(), Unit::IsIgnoringRangedTargets(), Object::IsPlayer(), iThreatList, and MANGOS_ASSERT.
Referenced by ThreatManager::getHostileTarget().
setDirty()
void ThreatContainer::setDirty (bool dirty) inline
Definition at line 165 of file ThreatManager.h.
References iDirty.
Referenced by ThreatManager::setDirty().
update()
void ThreatContainer::update (bool force, bool isPlayer) protected
Definition at line 307 of file ThreatManager.cpp.
References Unit::CanAttack(), Unit::CanReachWithMeleeAttack(), HostileReference::GetHostileState(), Reference< TO, FROM >::getSource(), Reference< TO, FROM >::getTarget(), HostileReference::GetTauntState(), HostileReference::getThreat(), iDirty, Object::IsPlayer(), and iThreatList.
Referenced by ThreatManager::UpdateContainers().
Friends And Related Function Documentation
ThreatManager
friend class ThreatManager friend
Definition at line 177 of file ThreatManager.h.
Field Documentation
iDirty
bool ThreatContainer::iDirty private
Definition at line 187 of file ThreatManager.h.
Referenced by isDirty(), setDirty(), ThreatContainer(), and update().
iThreatList
ThreatList ThreatContainer::iThreatList protected
Definition at line 185 of file ThreatManager.h.
Referenced by addReference(), clearReferences(), empty(), getMostHated(), getReferenceByTarget(), getThreatList(), modifyAllThreatPercent(), remove(), selectNextVictim(), and update().
The documentation for this class was generated from the following files:
ThreatManager.h
ThreatManager.cpp