CMaNGOS_WoTLK: MaNGOS::BattleGroundChatBuilder Class Reference
MaNGOS::BattleGroundChatBuilder Class Reference
Public Member Functions
BattleGroundChatBuilder (ChatMsg msgtype, int32 textId, Player const *source, va_list *args=nullptr)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
ChatMsg i_msgtype
int32 i_textId
Player const * i_source
va_list * i_args
Detailed Description
Definition at line 39 of file BattleGround.cpp.
Constructor & Destructor Documentation
BattleGroundChatBuilder()
MaNGOS::BattleGroundChatBuilder::BattleGroundChatBuilder (ChatMsg msgtype, int32 textId, Player const * source, va_list * args = nullptr) inline
Definition at line 42 of file BattleGround.cpp.
Member Function Documentation
operator()()
void MaNGOS::BattleGroundChatBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 44 of file BattleGround.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, WorldObject::GetName(), Object::GetObjectGuid(), i_args, i_msgtype, i_source, i_textId, LANG_UNIVERSAL, and sObjectMgr.
Field Documentation
i_args
va_list* MaNGOS::BattleGroundChatBuilder::i_args private
Definition at line 70 of file BattleGround.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::BattleGroundChatBuilder::i_msgtype private
Definition at line 67 of file BattleGround.cpp.
Referenced by operator()().
i_source
Player const* MaNGOS::BattleGroundChatBuilder::i_source private
Definition at line 69 of file BattleGround.cpp.
Referenced by operator()().
i_textId
int32 MaNGOS::BattleGroundChatBuilder::i_textId private
Definition at line 68 of file BattleGround.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
BattleGround.cpp