CMaNGOS_WoTLK: BrewfestEvent Class Reference
BrewfestEvent Class Reference
#include <brewfest.h>
Public Member Functions
BrewfestEvent (ScriptedInstance *instance)
void Update (const uint32 diff)
void StartKegTappingEvent ()
void StartDarkIronAttackEvent ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Private Member Functions
void HandleKegTappingEvent ()
Private Attributes
ScriptedInstance * m_instance
uint32 m_kegTappingStage
bool m_kalimdor
Additional Inherited Members
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Detailed Description
Definition at line 34 of file brewfest.h.
Constructor & Destructor Documentation
BrewfestEvent()
BrewfestEvent::BrewfestEvent (ScriptedInstance * instance)
Definition at line 777 of file brewfest.cpp.
References TimerManager::AddCustomAction(), BREWFEST_DARK_IRON_ATTACK_TIMER, BREWFEST_KEG_TAPPING_TIMER, Map::GetId(), HandleKegTappingEvent(), InstanceData::instance, m_instance, and m_kalimdor.
Member Function Documentation
HandleKegTappingEvent()
void BrewfestEvent::HandleKegTappingEvent () private
Definition at line 801 of file brewfest.cpp.
References BREWFEST_KEG_TAPPING_TIMER, DoBroadcastText(), ScriptedInstance::GetSingleCreatureFromStorage(), m_instance, m_kalimdor, m_kegTappingStage, NPC_IPFELKOFER_IRONKEG, NPC_MEKKATORQUE, NPC_TAPPER_SWINDLEKEG, NPC_VOLJIN, TimerManager::ResetTimer(), SAY_10_MEKKATORQUE, SAY_10_VOLJIN, SAY_20_MEKKATORQUE, and SAY_20_VOLJIN.
Referenced by BrewfestEvent(), and StartKegTappingEvent().
StartDarkIronAttackEvent()
void BrewfestEvent::StartDarkIronAttackEvent ()
Definition at line 829 of file brewfest.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), m_instance, m_kalimdor, NPC_DARK_IRON_HERALD, SPELL_PLAYERS_WON_A_SUMMON_DARK_IRON_DWARF_PLANS, SPELL_PLAYERS_WON_H_SUMMON_DARK_IRON_DWARF_PLANS, and TRIGGERED_OLD_TRIGGERED.
Referenced by world_map_eastern_kingdoms::OnEventHappened(), and world_map_kalimdor::OnEventHappened().
StartKegTappingEvent()
void BrewfestEvent::StartKegTappingEvent ()
Definition at line 795 of file brewfest.cpp.
References HandleKegTappingEvent(), and m_kegTappingStage.
Referenced by world_map_eastern_kingdoms::OnEventHappened(), and world_map_kalimdor::OnEventHappened().
Update()
void BrewfestEvent::Update (const uint32 diff)
Definition at line 790 of file brewfest.cpp.
References TimerManager::UpdateTimers().
Referenced by world_map_eastern_kingdoms::Update(), and world_map_kalimdor::Update().
Field Documentation
m_instance
ScriptedInstance* BrewfestEvent::m_instance private
Definition at line 46 of file brewfest.h.
Referenced by BrewfestEvent(), HandleKegTappingEvent(), and StartDarkIronAttackEvent().
m_kalimdor
bool BrewfestEvent::m_kalimdor private
Definition at line 48 of file brewfest.h.
Referenced by BrewfestEvent(), HandleKegTappingEvent(), and StartDarkIronAttackEvent().
m_kegTappingStage
uint32 BrewfestEvent::m_kegTappingStage private
Definition at line 47 of file brewfest.h.
Referenced by HandleKegTappingEvent(), and StartKegTappingEvent().
The documentation for this class was generated from the following files:
brewfest.h
brewfest.cpp