CMaNGOS_WoTLK: Item Class Reference
Item Class Reference
#include <Item.h>
Public Member Functions
Item * CloneItem (uint32 count, Player const *player=nullptr) const
Item ()
virtual bool Create (uint32 guidlow, uint32 itemid, Player const *owner)
ItemPrototype const * GetProto () const
ObjectGuid const & GetOwnerGuid () const
void SetOwnerGuid (ObjectGuid guid)
Player * GetOwner () const
void SetBinding (bool val)
bool IsSoulBound () const
bool IsBoundAccountWide () const
bool IsBindedNotWith (Player const *player) const
bool IsBoundByEnchant () const
bool IsMainHandOnlyEnchant (EnchantmentSlot slot) const
bool CanEnterArenaEnchant (EnchantmentSlot slot) const
virtual void SaveToDB ()
virtual bool LoadFromDB (uint32 guidLow, Field *fields, ObjectGuid ownerGuid=ObjectGuid())
virtual void DeleteFromDB ()
void DeleteFromInventoryDB () const
void LoadLootFromDB (Field *fields)
bool IsUnlocked () const
bool IsBag () const
bool IsBroken () const
bool CanBeTraded (bool mail=false) const
void SetInTrade (bool b=true)
bool IsInTrade () const
bool IsFitToSpellRequirements (SpellEntry const *spellInfo) const
bool IsTargetValidForItemUse (Unit *pUnitTarget) const
bool IsLimitedToAnotherMapOrZone (uint32 cur_mapId, uint32 cur_zoneId) const
bool GemsFitSockets () const
uint32 GetCount () const
void SetCount (uint32 value)
uint32 GetMaxStackCount () const
uint8 GetGemCountWithID (uint32 GemID) const
uint8 GetGemCountWithLimitCategory (uint32 limitCategory) const
InventoryResult CanBeMergedPartlyWith (ItemPrototype const *proto) const
uint8 GetSlot () const
Bag * GetContainer () const
uint8 GetBagSlot () const
void SetSlot (uint8 slot)
uint16 GetPos () const
void SetContainer (Bag *container)
bool IsInBag () const
bool IsEquipped () const
uint32 GetSkill () const
uint32 GetSpell () const
int32 GetItemRandomPropertyId () const
uint32 GetItemSuffixFactor () const
void SetItemRandomProperties (int32 randomPropId)
void UpdateItemSuffixFactor ()
void SetEnchantment (EnchantmentSlot slot, uint32 id, uint32 duration, uint32 charges, ObjectGuid caster=ObjectGuid())
void SetEnchantmentDuration (EnchantmentSlot slot, uint32 duration)
void SetEnchantmentCharges (EnchantmentSlot slot, uint32 charges)
void ClearEnchantment (EnchantmentSlot slot)
uint32 GetEnchantmentId (EnchantmentSlot slot) const
uint32 GetEnchantmentDuration (EnchantmentSlot slot) const
uint32 GetEnchantmentCharges (EnchantmentSlot slot) const
std::string const & GetText () const
void SetText (std::string const &text)
void SendUpdateSockets ()
void SendTimeUpdate (Player *owner) const
void UpdateDuration (Player *owner, uint32 diff)
int32 GetSpellCharges (uint8 index=0) const
void SetSpellCharges (uint8 index, int32 value)
bool HasMaxCharges () const
void RestoreCharges ()
void SetLootState (ItemLootUpdateState state)
bool HasGeneratedLoot () const
bool HasTemporaryLoot () const
bool HasSavedLoot () const
ItemUpdateState GetState () const
void SetState (ItemUpdateState state, Player *forplayer=nullptr)
void AddToUpdateQueueOf (Player *player)
void RemoveFromUpdateQueueOf (Player *player)
bool IsInUpdateQueue () const
uint16 GetQueuePos () const
void FSetState (ItemUpdateState state)
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32) const override
bool IsPotion () const
bool IsConjuredConsumable () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &update_players) override
bool IsUsedInSpell () const
void SetUsedInSpell (bool state)
uint32 GetTotalAP () const
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
virtual void AddToWorld ()
virtual void RemoveFromWorld ()
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Static Public Member Functions
static Item * CreateItem (uint32 item, uint32 count, Player const *player=nullptr, uint32 randomPropertyId=0)
static int32 GenerateItemRandomPropertyId (uint32 item_id)
Private Attributes
std::string m_text
uint8 m_slot
Bag * m_container
ItemUpdateState uState
int16 uQueuePos
bool mb_in_trade
ItemLootUpdateState m_lootState
bool m_usedInSpell
Additional Inherited Members
Data Fields inherited from Object
Loot * m_loot
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Detailed Description
Definition at line 271 of file Item.h.
Constructor & Destructor Documentation
Item()
Item::Item ()
Definition at line 200 of file Item.cpp.
References ITEM_END, ITEM_LOOT_NONE, ITEM_NEW, m_container, m_lootState, Object::m_objectType, Object::m_objectTypeId, m_slot, Object::m_updateFlag, m_usedInSpell, Object::m_valuesCount, mb_in_trade, TYPEID_ITEM, TYPEMASK_ITEM, UPDATEFLAG_HIGHGUID, uQueuePos, and uState.
Member Function Documentation
AddToClientUpdateList()
void Item::AddToClientUpdateList () override virtual
Reimplemented from Object.
Definition at line 1200 of file Item.cpp.
References GetOwner().
AddToUpdateQueueOf()
void Item::AddToUpdateQueueOf (Player * player)
Definition at line 778 of file Item.cpp.
References Object::GetGuidStr(), Object::GetObjectGuid(), GetOwner(), GetOwnerGuid(), IsInUpdateQueue(), Player::m_itemUpdateQueue, Player::m_itemUpdateQueueBlocked, sLog, and uQueuePos.
Referenced by SetState().
BuildUpdateData()
void Item::BuildUpdateData (UpdateDataMapType & update_players) override virtual
Reimplemented from Object.
Definition at line 1212 of file Item.cpp.
References Object::BuildUpdateDataForPlayer(), Object::ClearUpdateMask(), and GetOwner().
CanBeMergedPartlyWith()
InventoryResult Item::CanBeMergedPartlyWith (ItemPrototype const * proto) const
Definition at line 1239 of file Item.cpp.
References EQUIP_ERR_ALREADY_LOOTED, EQUIP_ERR_ITEM_CANT_STACK, EQUIP_ERR_OK, GetCount(), Object::GetEntry(), ItemPrototype::GetMaxStackSize(), HasGeneratedLoot(), and ItemPrototype::ItemId.
Referenced by Player::_CanStoreItem_InBag(), Player::_CanStoreItem_InInventorySlots(), Player::_CanStoreItem_InSpecificSlot(), and Player::CanStoreItems().
CanBeTraded()
bool Item::CanBeTraded (bool mail = false) const
Definition at line 848 of file Item.cpp.
References EQUIP_ERR_OK, Object::GetObjectGuid(), GetOwner(), GetPos(), HasGeneratedLoot(), IsBag(), Player::IsBagPos(), IsBoundAccountWide(), IsBoundByEnchant(), and IsSoulBound().
Referenced by PlayerbotAI::_doSellItem(), PlayerbotAI::DropGarbage(), WorldSession::HandleAuctionSellItem(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleSendMail(), WorldSession::HandleSetTradeItemOpcode(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), and PlayerbotAI::TradeItem().
CanEnterArenaEnchant()
bool Item::CanEnterArenaEnchant (EnchantmentSlot slot) const
Definition at line 901 of file Item.cpp.
References ENCHANTMENT_ALLOW_ENTERING_ARENA, SpellItemEnchantmentEntry::flags, GetEnchantmentId(), and sSpellItemEnchantmentStore.
Referenced by Player::RemoveAllEnchantments().
ClearEnchantment()
void Item::ClearEnchantment (EnchantmentSlot slot)
Definition at line 1006 of file Item.cpp.
References GetEnchantmentId(), Object::GetEntry(), GetOwner(), ITEM_CHANGED, ITEM_FIELD_ENCHANTMENT_1_1, MAX_ENCHANTMENT_OFFSET, MAX_INSPECTED_ENCHANTMENT_SLOT, SetState(), and Object::SetUInt32Value().
Referenced by WorldSession::HandleCancelTempEnchantmentOpcode(), Player::RemoveAllEnchantments(), and Player::SetVirtualItemSlot().
CloneItem()
Item * Item::CloneItem (uint32 count, Player const * player = nullptr) const
Definition at line 1160 of file Item.cpp.
References CreateItem(), Object::GetEntry(), Object::GetGuidValue(), GetItemRandomPropertyId(), Object::GetUInt32Value(), ITEM_FIELD_CREATOR, ITEM_FIELD_DURATION, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, Object::SetGuidValue(), and Object::SetUInt32Value().
Referenced by Player::_StoreItem(), Guild::_StoreItem(), MailDraft::CloneFrom(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleSellItemOpcode(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), Player::SplitItem(), and Guild::SwapItems().
Create()
bool Item::Create (uint32 guidlow, uint32 itemid, Player const * owner) virtual
Reimplemented in Bag.
Definition at line 218 of file Item.cpp.
References Object::_Create(), DEFAULT_OBJECT_SCALE, ItemPrototype::Duration, ObjectMgr::GetItemPrototype(), Object::GetObjectGuid(), HIGHGUID_ITEM, ITEM_FIELD_CONTAINED, ITEM_FIELD_DURABILITY, ITEM_FIELD_DURATION, ITEM_FIELD_MAXDURABILITY, ITEM_FIELD_OWNER, ITEM_FIELD_STACK_COUNT, MAX_ITEM_PROTO_SPELLS, ItemPrototype::MaxDurability, Object::SetEntry(), Object::SetGuidValue(), Object::SetObjectScale(), SetSpellCharges(), Object::SetUInt32Value(), _Spell::SpellCharges, and ItemPrototype::Spells.
Referenced by CreateItem(), and WorldSession::HandleMailCreateTextItem().
CreateItem()
Item * Item::CreateItem (uint32 item, uint32 count, Player const * player = nullptr, uint32 randomPropertyId = 0) static
Definition at line 1134 of file Item.cpp.
References Create(), GenerateItemRandomPropertyId(), ObjectMgr::GetItemPrototype(), MANGOS_ASSERT, NewItemOrBag(), SetCount(), SetItemRandomProperties(), and sObjectMgr.
Referenced by Player::CanEquipNewItem(), CloneItem(), AchievementMgr::CompletedAchievement(), Player::ConvertItem(), Player::EquipNewItem(), ChatHandler::HandleAuctionItemCommand(), ChatHandler::HandleSendItemsHelper(), MailDraft::prepareItems(), Mail::prepareTemplateItems(), BattleGroundMgr::RewardArenaSeason(), Player::SendItemRetrievalMail(), BattleGround::SendRewardMarkByMail(), Player::StoreNewItem(), and AuctionHouseBot::Update().
DeleteFromDB()
void Item::DeleteFromDB () virtual
Reimplemented in Bag.
Definition at line 561 of file Item.cpp.
References CharacterDatabase, Database::CreateStatement(), Object::GetGUIDLow(), and SqlStatement::PExecute().
Referenced by Guild::_StoreItem(), and Bag::DeleteFromDB().
DeleteFromInventoryDB()
void Item::DeleteFromInventoryDB () const
Definition at line 569 of file Item.cpp.
References CharacterDatabase, Database::CreateStatement(), Object::GetGUIDLow(), and SqlStatement::PExecute().
Referenced by Player::AutoUnequipOffhandIfNeed(), WorldSession::HandleSendMail(), Guild::MoveFromBankToChar(), and Guild::MoveFromCharToBank().
FSetState()
void Item::FSetState (ItemUpdateState state) inline
Definition at line 373 of file Item.h.
References uState.
Referenced by Player::_LoadInventory(), Player::_LoadMailedItems(), Player::_SaveInventory(), Guild::_StoreItem(), Player::DeleteFromDB(), Guild::MoveFromBankToChar(), and Guild::SwapItems().
GemsFitSockets()
bool Item::GemsFitSockets () const
Definition at line 1021 of file Item.cpp.
References _Socket::Color, GemPropertiesEntry::color, SpellItemEnchantmentEntry::GemID, ItemPrototype::GemProperties, GetEnchantmentId(), GetProto(), SQLStorage::LookupEntry(), MAX_GEM_SOCKETS, sGemPropertiesStore, sItemStorage, SOCK_ENCHANTMENT_SLOT, ItemPrototype::Socket, and sSpellItemEnchantmentStore.
Referenced by WorldSession::HandleSocketOpcode().
GenerateItemRandomPropertyId()
int32 Item::GenerateItemRandomPropertyId (uint32 item_id) static
Definition at line 666 of file Item.cpp.
References GetItemEnchantMod(), ItemRandomPropertiesEntry::ID, ItemRandomSuffixEntry::ID, SQLStorage::LookupEntry(), ItemPrototype::RandomProperty, ItemPrototype::RandomSuffix, sItemRandomPropertiesStore, sItemRandomSuffixStore, sItemStorage, and sLog.
Referenced by CreateItem(), Spell::DoCreateItem(), world_map_outland::ExecuteChatCommand(), ChatHandler::HandleAddItemCommand(), ChatHandler::HandleBagsCommand(), LootItem::LootItem(), Player::RewardQuest(), Player::StoreNewItemInBestSlots(), and Player::StoreNewItemInInventorySlot().
GetBagSlot()
uint8 Item::GetBagSlot () const
Definition at line 838 of file Item.cpp.
References GetSlot(), INVENTORY_SLOT_BAG_0, and m_container.
Referenced by PlayerbotAI::_doSellItem(), Player::_StoreItem(), Player::ConvertItem(), PlayerbotAI::Deposit(), Player::DestroyItemCount(), Player::DestroyItemWithOnStoreSpell(), PlayerbotAI::DropItem(), PlayerbotAI::EquipItem(), GetPos(), WorldSession::HandleAutoEquipItemOpcode(), ChatHandler::HandleDebugGetItemStateCommand(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleTurnInPetitionOpcode(), Loot::Release(), PlayerbotAI::Sell(), Player::SendNewItem(), PlayerbotAI::TradeItem(), UpdateDuration(), PlayerbotAI::UseItem(), and PlayerbotAI::Withdraw().
GetContainer()
Bag* Item::GetContainer () const inline
Definition at line 320 of file Item.h.
References m_container.
Referenced by Player::_LoadInventory(), ChatHandler::HandleDebugGetItemStateCommand(), and Player::SaveItemToInventory().
GetCount()
uint32 Item::GetCount () const inline
Definition at line 312 of file Item.h.
References Object::GetUInt32Value(), and ITEM_FIELD_STACK_COUNT.
Referenced by Player::_CanStoreItem_InBag(), Player::_CanStoreItem_InInventorySlots(), Player::_CanStoreItem_InSpecificSlot(), Guild::_CanStoreItem_InSpecificSlot(), Guild::_CanStoreItem_InTab(), PlayerbotAI::_doSellItem(), PlayerbotAI::_HandleCommandMail(), Player::_StoreItem(), Guild::_StoreItem(), AuctionHouseObject::AddAuction(), PlayerbotAI::AddAuction(), Guild::AppendDisplayGuildBankSlot(), AuctionEntry::BuildAuctionInfo(), Player::CanBankItem(), CanBeMergedPartlyWith(), Player::CanEquipItem(), Player::CanStoreItem(), Guild::CanStoreItem(), Player::CanStoreItems(), Player::CanTakeMoreSimilarItems(), Player::CanUnequipItem(), Player::CanUnequipItems(), Spell::CheckItems(), MailDraft::CloneFrom(), Player::DestroyItem(), Player::DestroyItemCount(), Player::EquipItem(), AuctionHouseMgr::GetAuctionDeposit(), Player::GetItemCount(), Bag::GetItemCount(), Bag::GetItemCountWithLimitCategory(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleBuybackItem(), WorldSession::HandleGetMailList(), WorldSession::HandleMailTakeItem(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), Player::HasItemCount(), Player::HasItemOrGemWithIdEquipped(), Player::HasItemOrGemWithLimitCategoryEquipped(), PlayerbotAI::ItemCountInInv(), PlayerbotAI::ListAuctions(), AuctionHouseMgr::LoadAuctions(), PlayerbotAI::MakeItemLink(), PlayerbotAI::MakeItemText(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), WorldSession::moveItems(), Player::MoveItemToInventory(), Loot::Release(), SaveToDB(), PlayerbotAI::Sell(), Player::SendNewItem(), Player::SplitItem(), Player::SwapItem(), Guild::SwapItems(), and AuctionHouseBot::Update().
GetEnchantmentCharges()
uint32 Item::GetEnchantmentCharges (EnchantmentSlot slot) const inline
Definition at line 344 of file Item.h.
References ENCHANTMENT_CHARGES_OFFSET, Object::GetUInt32Value(), ITEM_FIELD_ENCHANTMENT_1_1, and MAX_ENCHANTMENT_OFFSET.
Referenced by AuctionEntry::BuildAuctionInfo(), Player::ConvertItem(), WorldSession::HandleGetMailList(), SaveToDB(), SetEnchantment(), SetEnchantmentCharges(), and Player::SetVirtualItemSlot().
GetEnchantmentDuration()
uint32 Item::GetEnchantmentDuration (EnchantmentSlot slot) const inline
Definition at line 343 of file Item.h.
References ENCHANTMENT_DURATION_OFFSET, Object::GetUInt32Value(), ITEM_FIELD_ENCHANTMENT_1_1, and MAX_ENCHANTMENT_OFFSET.
Referenced by Player::AddEnchantmentDurations(), Player::ApplyEnchantment(), AuctionEntry::BuildAuctionInfo(), Player::ConvertItem(), WorldSession::HandleGetMailList(), SaveToDB(), SetEnchantment(), and SetEnchantmentDuration().
GetEnchantmentId()
uint32 Item::GetEnchantmentId (EnchantmentSlot slot) const inline
Definition at line 342 of file Item.h.
References ENCHANTMENT_ID_OFFSET, Object::GetUInt32Value(), ITEM_FIELD_ENCHANTMENT_1_1, and MAX_ENCHANTMENT_OFFSET.
Referenced by Player::_HandleDeadlyPoison(), Player::AddEnchantmentDurations(), Guild::AppendDisplayGuildBankSlot(), Player::ApplyEnchantment(), AuctionEntry::BuildAuctionInfo(), Player::BuildEnchantmentsInfoData(), CanEnterArenaEnchant(), Player::CanEquipUniqueItem(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), ClearEnchantment(), Player::ConvertItem(), Player::CorrectMetaGemEnchants(), PlayerbotRogueAI::DoNonCombatActions(), PlayerbotShamanAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), Spell::EffectDummy(), Spell::EffectEnchantHeldItem(), Player::EnchantmentFitsRequirements(), GemsFitSockets(), GetGemCountWithID(), GetGemCountWithLimitCategory(), WorldSession::HandleCancelTempEnchantmentOpcode(), Unit::HandleDummyAuraProc(), WorldSession::HandleGetMailList(), WorldSession::HandleSocketOpcode(), IsBoundByEnchant(), IsMainHandOnlyEnchant(), PlayerbotAI::MakeItemLink(), Player::RemoveAllEnchantments(), SaveToDB(), SendUpdateSockets(), SetEnchantment(), Player::SetVirtualItemSlot(), Player::SetVisibleItemSlot(), and Player::ToggleMetaGemsActive().
GetGemCountWithID()
uint8 Item::GetGemCountWithID (uint32 GemID) const
Definition at line 1061 of file Item.cpp.
References SpellItemEnchantmentEntry::GemID, GetEnchantmentId(), MAX_GEM_SOCKETS, SOCK_ENCHANTMENT_SLOT, and sSpellItemEnchantmentStore.
Referenced by Player::GetItemCount(), Bag::GetItemCount(), and Player::HasItemOrGemWithIdEquipped().
GetGemCountWithLimitCategory()
uint8 Item::GetGemCountWithLimitCategory (uint32 limitCategory) const
Definition at line 1080 of file Item.cpp.
References SpellItemEnchantmentEntry::GemID, GetEnchantmentId(), ObjectMgr::GetItemPrototype(), ItemPrototype::ItemLimitCategory, MAX_GEM_SOCKETS, SOCK_ENCHANTMENT_SLOT, and sSpellItemEnchantmentStore.
Referenced by Player::CanEquipUniqueItem(), and Player::HasItemOrGemWithLimitCategoryEquipped().
GetItemRandomPropertyId()
int32 Item::GetItemRandomPropertyId () const inline
Definition at line 333 of file Item.h.
References Object::GetInt32Value(), and ITEM_FIELD_RANDOM_PROPERTIES_ID.
Referenced by AuctionHouseObject::AddAuction(), Guild::AppendDisplayGuildBankSlot(), Player::ApplyEnchantment(), Aura::Aura(), AuctionEntry::BuildAuctionInfo(), Player::BuildEnchantmentsInfoData(), CloneItem(), WorldSession::HandleGetMailList(), AuctionHouseMgr::LoadAuctions(), LoadFromDB(), SaveToDB(), and Player::SendNewItem().
GetItemSuffixFactor()
uint32 Item::GetItemSuffixFactor () const inline
Definition at line 334 of file Item.h.
References Object::GetUInt32Value(), and ITEM_FIELD_PROPERTY_SEED.
Referenced by Guild::AppendDisplayGuildBankSlot(), Player::ApplyEnchantment(), Aura::Aura(), AuctionEntry::BuildAuctionInfo(), Player::BuildEnchantmentsInfoData(), WorldSession::HandleGetMailList(), Player::SendNewItem(), SetItemRandomProperties(), and UpdateItemSuffixFactor().
GetMaxStackCount()
uint32 Item::GetMaxStackCount () const inline
Definition at line 314 of file Item.h.
References ItemPrototype::GetMaxStackSize(), and GetProto().
Referenced by Guild::_CanStoreItem_InSpecificSlot(), Guild::_CanStoreItem_InTab(), Guild::CanStoreItem(), WorldSession::HandleAuctionSellItem(), WorldSession::HandleWrapItemOpcode(), LoadFromDB(), and Spell::TakeAmmo().
GetOwner()
Player * Item::GetOwner () const
Definition at line 582 of file Item.cpp.
References GetOwnerGuid(), and sObjectMgr.
Referenced by AddToClientUpdateList(), AddToUpdateQueueOf(), BuildUpdateData(), CanBeTraded(), Spell::CheckItems(), ClearEnchantment(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), IsBindedNotWith(), RemoveFromClientUpdateList(), RemoveFromUpdateQueueOf(), SaveToDB(), SendUpdateSockets(), and SetEnchantment().
GetOwnerGuid()
ObjectGuid const& Item::GetOwnerGuid () const inline
Definition at line 283 of file Item.h.
References Object::GetGuidValue(), and ITEM_FIELD_OWNER.
Referenced by AddToUpdateQueueOf(), Spell::CheckItems(), Spell::EffectOpenLock(), Spell::EffectSummonChangeItem(), GetOwner(), ChatHandler::HandleDebugGetItemStateCommand(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleWrapItemOpcode(), IsBindedNotWith(), LoadFromDB(), LoadLootFromDB(), Player::MoveItemToInventory(), RemoveFromUpdateQueueOf(), SaveToDB(), SetState(), and Bag::StoreItem().
GetPos()
uint16 Item::GetPos () const inline
Definition at line 323 of file Item.h.
References GetBagSlot(), and GetSlot().
Referenced by Player::_LoadInventory(), CanBeTraded(), Player::CastItemUseSpell(), Player::ConvertItem(), PlayerbotAI::EquipItem(), WorldSession::HandleAutoBankItemOpcode(), WorldSession::HandleAutoEquipItemOpcode(), WorldSession::HandleAutoEquipItemSlotOpcode(), WorldSession::HandleAutoStoreBagItemOpcode(), WorldSession::HandleEquipmentSetUseOpcode(), WorldSession::HandleRepairItemOpcode(), and PlayerbotAI::Repair().
GetProto()
ItemPrototype const * Item::GetProto () const
Definition at line 577 of file Item.cpp.
References Object::GetEntry(), and ObjectMgr::GetItemPrototype().
Referenced by Player::_ApplyAllItemMods(), Player::_ApplyAllLevelScaleItemMods(), Player::_ApplyItemMods(), Player::_CanStoreItem_InBag(), Player::_CanStoreItem_InSpecificSlot(), PlayerbotAI::_doSellItem(), Player::_fillGearScoreData(), PlayerbotAI::_findItemSlot(), PlayerbotAI::_HandleCommandMail(), PlayerbotAI::_HandleCommandProcess(), PlayerbotAI::_HandleCommandQuest(), Player::_LoadInventory(), Player::_RemoveAllItemMods(), Player::_StoreItem(), PlayerbotAI::AddAuction(), AddItemsSetItem(), Player::ApplyEnchantment(), Player::ApplyEquipCooldown(), Player::ApplyItemEquipSpell(), Player::ApplyItemOnStoreSpell(), PlayerbotAI::AutoEquipComparison(), Player::AutoUnequipOffhandIfNeed(), PlayerbotAI::AutoUpgradeEquipment(), PlayerbotAI::BankBalance(), WorldSession::BuildListAuctionItems(), Player::CanBankItem(), Unit::CanBlockInCombat(), Player::CanEquipItem(), Player::CanEquipUniqueItem(), PlayerbotAI::CanStore(), Player::CanStoreItems(), Player::CanUnequipItem(), Player::CanUseItem(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), Player::CheckAmmoCompatibility(), Spell::CheckCast(), Spell::CheckItems(), Player::CorrectMetaGemEnchants(), Player::CreateCorpse(), Player::DestroyItem(), Player::DestroyItemWithOnStoreSpell(), Spell::DoCreateItem(), PlayerbotHunterAI::DoNonCombatActions(), PlayerbotWarlockAI::DoNonCombatActions(), PlayerbotAI::DropGarbage(), Player::DurabilityRepair(), Spell::EffectDisEnchant(), Spell::EffectDummy(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Spell::EffectFeedPet(), Spell::EffectMilling(), Spell::EffectOpenLock(), Spell::EffectProspecting(), Spell::EffectSummonType(), Spell::EffectWeaponDmg(), Player::EnchantmentFitsRequirements(), Player::EquipItem(), EquippedOk(), PlayerbotAI::EstRepair(), PlayerbotAI::FindAmmo(), PlayerbotAI::FindBandage(), PlayerbotAI::FindConsumable(), PlayerbotAI::FindDrink(), PlayerbotAI::FindFood(), PlayerbotAI::FindItem(), PlayerbotAI::FindItemInBank(), PlayerbotAI::findItemsInEquip(), PlayerbotAI::findItemsInInv(), PlayerbotAI::FindMount(), PlayerbotAI::FindPoison(), GemsFitSockets(), Unit::GetAPMultiplier(), AuctionHouseMgr::GetAuctionDeposit(), Player::GetAverageItemLevel(), PlayerbotAI::GetFreeBagSpace(), Bag::GetItemByLimitedCategory(), Player::GetItemCount(), Bag::GetItemCount(), Bag::GetItemCountWithLimitCategory(), Player::GetItemDisplayIdInSlot(), GetMaxStackCount(), Player::GetShield(), GetSkill(), GetSpell(), GetTotalAP(), Player::GetWeaponForAttack(), WorldSession::HandleAuctionSellItem(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleDestroyItemOpcode(), WorldSession::HandleItemRefundInfoRequest(), WorldSession::HandleMailTakeItem(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleReadItemOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSocketOpcode(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWrapItemOpcode(), Player::HasItemOrGemWithIdEquipped(), Player::HasItemOrGemWithLimitCategoryEquipped(), Player::HasItemTotemCategory(), HasMaxCharges(), HasQuest(), Player::HasTwoHandWeaponInOneHand(), Spell::IgnoreItemRequirements(), IsBag(), IsBoundAccountWide(), IsConjuredConsumable(), IsFitToSpellRequirements(), IsLimitedToAnotherMapOrZone(), IsPotion(), IsTargetValidForItemUse(), Unit::IsTriggeredAtSpellProcEvent(), Player::IsTwoHandUsed(), PlayerbotAI::ListAuctions(), LoadFromDB(), Loot::Loot(), PlayerbotAI::MakeItemLink(), PlayerbotAI::MakeItemText(), AchievementCriteriaRequirement::Meets(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), WorldSession::moveItems(), ScriptDevAIMgr::OnEffectDummy(), ScriptDevAIMgr::OnItemLoot(), ScriptDevAIMgr::OnItemUse(), ScriptDevAIMgr::OnQuestAccept(), RestoreCharges(), Player::RewardReputation(), PlayerbotAI::Sell(), PlayerbotAI::SellGarbage(), Player::SendEquipError(), Spell::SendSpellCooldown(), Player::SetRegularAttackTime(), Player::SwapItem(), Spell::TakeAmmo(), Spell::TakeCastItem(), Spell::TakeReagents(), Player::ToggleMetaGemsActive(), AuctionHouseBot::Update(), Player::UpdateItemDuration(), Player::UpdateWeaponSkill(), PlayerbotAI::UseItem(), Player::VisualizeItem(), and Spell::WriteAmmoToPacket().
GetQueuePos()
uint16 Item::GetQueuePos () const inline
Definition at line 372 of file Item.h.
References uQueuePos.
Referenced by ChatHandler::HandleDebugGetItemStateCommand().
GetSkill()
uint32 Item::GetSkill () const
Definition at line 587 of file Item.cpp.
References ItemPrototype::Class, GetProto(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, MAX_ITEM_SUBCLASS_ARMOR, MAX_ITEM_SUBCLASS_WEAPON, SKILL_2H_AXES, SKILL_2H_MACES, SKILL_2H_SWORDS, SKILL_ASSASSINATION, SKILL_AXES, SKILL_BOWS, SKILL_CLOTH, SKILL_CROSSBOWS, SKILL_DAGGERS, SKILL_FISHING, SKILL_GUNS, SKILL_LEATHER, SKILL_MACES, SKILL_MAIL, SKILL_PLATE_MAIL, SKILL_POLEARMS, SKILL_SHIELD, SKILL_STAVES, SKILL_SWORDS, SKILL_THROWN, SKILL_UNARMED, SKILL_WANDS, and ItemPrototype::SubClass.
Referenced by Player::CanUseItem(), Player::GetWeaponSkillIdForAttack(), Unit::GetWeaponSkillValue(), and Player::UpdateWeaponSkill().
GetSlot()
uint8 Item::GetSlot () const inline
Definition at line 319 of file Item.h.
References m_slot.
Referenced by PlayerbotAI::_doSellItem(), Player::_StoreItem(), Player::ApplyEnchantment(), Spell::CheckItems(), Player::ConvertItem(), PlayerbotAI::Deposit(), Player::DestroyItemCount(), Player::DestroyItemWithOnStoreSpell(), PlayerbotAI::DropItem(), Player::DurabilityPointsLoss(), PlayerbotAI::EquipItem(), GetBagSlot(), GetPos(), WorldSession::HandleAutoEquipItemOpcode(), ChatHandler::HandleDebugGetItemStateCommand(), Unit::HandleDummyAuraProc(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleSendMail(), WorldSession::HandleSocketOpcode(), WorldSession::HandleTurnInPetitionOpcode(), SpellAuraHolder::IsWeaponBuffCoexistableWith(), Loot::Release(), Player::SaveItemToInventory(), PlayerbotAI::Sell(), Player::SendNewItem(), PlayerbotAI::TradeItem(), UpdateDuration(), PlayerbotAI::UseItem(), and PlayerbotAI::Withdraw().
GetSpell()
uint32 Item::GetSpell () const
Definition at line 626 of file Item.cpp.
References ItemPrototype::Class, GetProto(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, ITEM_SUBCLASS_ARMOR_CLOTH, ITEM_SUBCLASS_ARMOR_LEATHER, ITEM_SUBCLASS_ARMOR_MAIL, ITEM_SUBCLASS_ARMOR_PLATE, ITEM_SUBCLASS_ARMOR_SHIELD, ITEM_SUBCLASS_WEAPON_AXE, ITEM_SUBCLASS_WEAPON_AXE2, ITEM_SUBCLASS_WEAPON_BOW, ITEM_SUBCLASS_WEAPON_CROSSBOW, ITEM_SUBCLASS_WEAPON_DAGGER, ITEM_SUBCLASS_WEAPON_GUN, ITEM_SUBCLASS_WEAPON_MACE, ITEM_SUBCLASS_WEAPON_MACE2, ITEM_SUBCLASS_WEAPON_POLEARM, ITEM_SUBCLASS_WEAPON_SPEAR, ITEM_SUBCLASS_WEAPON_STAFF, ITEM_SUBCLASS_WEAPON_SWORD, ITEM_SUBCLASS_WEAPON_SWORD2, ITEM_SUBCLASS_WEAPON_THROWN, ITEM_SUBCLASS_WEAPON_WAND, and ItemPrototype::SubClass.
GetSpellCharges()
int32 Item::GetSpellCharges (uint8 index = 0) const inline
Definition at line 355 of file Item.h.
References Object::GetInt32Value(), and ITEM_FIELD_SPELL_CHARGES.
Referenced by PlayerbotAI::_doSellItem(), Guild::AppendDisplayGuildBankSlot(), AuctionEntry::BuildAuctionInfo(), Spell::CheckItems(), WorldSession::HandleGetMailList(), WorldSession::HandleSellItemOpcode(), HasMaxCharges(), RestoreCharges(), SaveToDB(), PlayerbotAI::Sell(), Spell::TakeCastItem(), and Spell::TakeReagents().
GetState()
ItemUpdateState Item::GetState () const inline
Definition at line 367 of file Item.h.
References uState.
Referenced by Player::_SaveInventory(), ChatHandler::HandleDebugGetItemStateCommand(), WorldSession::HandleWrapItemOpcode(), and Player::SaveItemToInventory().
GetText()
std::string const& Item::GetText () const inline
Definition at line 346 of file Item.h.
References m_text.
Referenced by SaveToDB().
GetTotalAP()
uint32 Item::GetTotalAP () const
Definition at line 1220 of file Item.cpp.
References GetProto(), ITEM_MOD_ATTACK_POWER, ITEM_SPELLTRIGGER_ON_EQUIP, ItemPrototype::ItemStat, _ItemStat::ItemStatType, _ItemStat::ItemStatValue, SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, MAX_ITEM_PROTO_SPELLS, SPELL_AURA_MOD_ATTACK_POWER, _Spell::SpellId, ItemPrototype::Spells, _Spell::SpellTrigger, sSpellTemplate, and ItemPrototype::StatsCount.
HasGeneratedLoot()
bool Item::HasGeneratedLoot () const inline
Definition at line 361 of file Item.h.
References ITEM_LOOT_NONE, ITEM_LOOT_REMOVED, Object::m_loot, and m_lootState.
Referenced by CanBeMergedPartlyWith(), CanBeTraded(), LootMgr::GetLoot(), IsBindedNotWith(), and Player::SplitItem().
HasInvolvedQuest()
bool Item::HasInvolvedQuest (uint32) const inline override virtual
Reimplemented from Object.
Definition at line 379 of file Item.h.
HasMaxCharges()
bool Item::HasMaxCharges () const
Definition at line 1275 of file Item.cpp.
References GetProto(), GetSpellCharges(), MAX_ITEM_PROTO_SPELLS, _Spell::SpellCharges, and ItemPrototype::Spells.
HasQuest()
bool Item::HasQuest (uint32 quest_id) const inline override virtual
Reimplemented from Object.
Definition at line 378 of file Item.h.
References GetProto(), and ItemPrototype::StartQuest.
HasSavedLoot()
bool Item::HasSavedLoot () const inline
Definition at line 364 of file Item.h.
References ITEM_LOOT_NEW, ITEM_LOOT_NONE, ITEM_LOOT_TEMPORARY, and m_lootState.
Referenced by SaveToDB().
HasTemporaryLoot()
bool Item::HasTemporaryLoot () const inline
Definition at line 362 of file Item.h.
References ITEM_LOOT_TEMPORARY, Object::m_loot, and m_lootState.
Referenced by Player::_CanStoreItem(), Player::CanBankItem(), Player::CanEquipItem(), Player::CanStoreItems(), Player::CanUnequipItem(), and Spell::CheckItems().
IsBag()
bool Item::IsBag () const inline
Definition at line 301 of file Item.h.
References GetProto(), ItemPrototype::InventoryType, and INVTYPE_BAG.
Referenced by Player::_CanStoreItem(), Player::_LoadInventory(), PlayerbotAI::AutoUpgradeEquipment(), Player::CanBankItem(), CanBeTraded(), Player::CanUnequipItem(), Player::DestroyItem(), PlayerbotAI::EquipItem(), WorldSession::HandleAutoEquipItemOpcode(), ChatHandler::HandleDebugGetItemStateCommand(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleWrapItemOpcode(), PlayerbotAI::SendNotEquipList(), and Player::SwapItem().
IsBindedNotWith()
bool Item::IsBindedNotWith (Player const * player) const
Definition at line 1173 of file Item.cpp.
References WorldSession::GetAccountId(), Object::GetObjectGuid(), GetOwner(), GetOwnerGuid(), Player::GetSession(), HasGeneratedLoot(), IsBoundAccountWide(), IsSoulBound(), and sObjectMgr.
Referenced by Player::_CanStoreItem(), Player::CanBankItem(), Player::CanEquipItem(), Player::CanStoreItems(), and Player::CanUseItem().
IsBoundAccountWide()
bool Item::IsBoundAccountWide () const inline
Definition at line 289 of file Item.h.
References GetProto(), and ITEM_FLAG_IS_BOUND_TO_ACCOUNT.
Referenced by CanBeTraded(), WorldSession::HandleSendMail(), and IsBindedNotWith().
IsBoundByEnchant()
bool Item::IsBoundByEnchant () const
Definition at line 873 of file Item.cpp.
References ENCHANTMENT_SOULBOUND, SpellItemEnchantmentEntry::flags, GetEnchantmentId(), MAX_ENCHANTMENT_SLOT, PERM_ENCHANTMENT_SLOT, and sSpellItemEnchantmentStore.
Referenced by CanBeTraded().
IsBroken()
bool Item::IsBroken () const inline
Definition at line 302 of file Item.h.
References Object::GetUInt32Value(), ITEM_FIELD_DURABILITY, and ITEM_FIELD_MAXDURABILITY.
Referenced by Player::_ApplyItemMods(), Player::ApplyEnchantment(), Unit::CanBlockInCombat(), Player::EnchantmentFitsRequirements(), Player::GetShield(), Player::GetWeaponForAttack(), and Unit::IsTriggeredAtSpellProcEvent().
IsConjuredConsumable()
bool Item::IsConjuredConsumable () const inline
Definition at line 381 of file Item.h.
References GetProto(), and ItemPrototype::IsConjuredConsumable().
IsEquipped()
bool Item::IsEquipped () const
Definition at line 843 of file Item.cpp.
References EQUIPMENT_SLOT_END, IsInBag(), and m_slot.
Referenced by Player::ApplyEnchantment(), Player::CanEquipUniqueItem(), Player::DestroyItem(), Player::DurabilityPointsLoss(), Unit::HandleDummyAuraProc(), WorldSession::HandleSocketOpcode(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWrapItemOpcode(), and SpellAuraHolder::IsWeaponBuffCoexistableWith().
IsFitToSpellRequirements()
bool Item::IsFitToSpellRequirements (SpellEntry const * spellInfo) const
Definition at line 910 of file Item.cpp.
References ItemPrototype::Class, SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectItemType, SpellEntry::EquippedItemClass, SpellEntry::EquippedItemInventoryTypeMask, SpellEntry::EquippedItemSubClassMask, GetProto(), ItemPrototype::InventoryType, ItemPrototype::IsVellum(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, ITEM_SUBCLASS_ARMOR_ENCHANTMENT, ITEM_SUBCLASS_WEAPON_ENCHANTMENT, SPELL_EFFECT_ENCHANT_ITEM, ItemPrototype::SubClass, TARGET_FLAG_ITEM, and SpellEntry::Targets.
Referenced by Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), Spell::CheckItems(), Spell::EffectTriggerSpell(), Player::HasItemFitToSpellReqirements(), Unit::MeleeDamageBonusDone(), Player::UpdateArmorPenetration(), and Player::UpdateExpertise().
IsInBag()
bool Item::IsInBag () const inline
Definition at line 326 of file Item.h.
References m_container.
Referenced by IsEquipped().
IsInTrade()
bool Item::IsInTrade () const inline
Definition at line 305 of file Item.h.
References mb_in_trade.
Referenced by Player::CanStoreItems(), Spell::CheckItems(), Player::DestroyItemCount(), WorldSession::HandleUseItemOpcode(), Player::HasItemCount(), PlayerbotAI::ItemCountInInv(), and PlayerbotAI::TradeItem().
IsInUpdateQueue()
bool Item::IsInUpdateQueue () const inline
Definition at line 371 of file Item.h.
References uQueuePos.
Referenced by AddToUpdateQueueOf(), ChatHandler::HandleDebugGetItemStateCommand(), and RemoveFromUpdateQueueOf().
IsLimitedToAnotherMapOrZone()
bool Item::IsLimitedToAnotherMapOrZone (uint32 cur_mapId, uint32 cur_zoneId) const
Definition at line 1103 of file Item.cpp.
References ItemPrototype::Area, GetProto(), and ItemPrototype::Map.
Referenced by Player::_LoadInventory().
IsMainHandOnlyEnchant()
bool Item::IsMainHandOnlyEnchant (EnchantmentSlot slot) const
Definition at line 892 of file Item.cpp.
References ENCHANTMENT_MAINHAND_ONLY, SpellItemEnchantmentEntry::flags, GetEnchantmentId(), and sSpellItemEnchantmentStore.
IsPotion()
bool Item::IsPotion () const inline
Definition at line 380 of file Item.h.
References GetProto(), and ItemPrototype::IsPotion().
Referenced by WorldSession::HandleUseItemOpcode(), and Spell::SendSpellCooldown().
IsSoulBound()
bool Item::IsSoulBound () const inline
Definition at line 288 of file Item.h.
References Object::HasFlag(), ITEM_DYNFLAG_BINDED, and ITEM_FIELD_FLAGS.
Referenced by CanBeTraded(), Guild::CanStoreItem(), WorldSession::HandleSendMail(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWrapItemOpcode(), IsBindedNotWith(), and LoadFromDB().
IsTargetValidForItemUse()
bool Item::IsTargetValidForItemUse (Unit * pUnitTarget) const
Definition at line 949 of file Item.cpp.
References GetProto(), and sObjectMgr.
Referenced by WorldSession::HandleUseItemOpcode().
IsUnlocked()
bool Item::IsUnlocked () const inline
Definition at line 300 of file Item.h.
References Object::HasFlag(), ITEM_DYNFLAG_UNLOCKED, and ITEM_FIELD_FLAGS.
Referenced by WorldSession::HandleGetMailList().
IsUsedInSpell()
bool Item::IsUsedInSpell () const inline
Definition at line 387 of file Item.h.
References m_usedInSpell.
Referenced by UpdateDuration().
LoadFromDB()
bool Item::LoadFromDB (uint32 guidLow, Field * fields, ObjectGuid ownerGuid = ObjectGuid()) virtual
Reimplemented in Bag.
Definition at line 415 of file Item.cpp.
References Object::_Create(), Object::_LoadIntoDataField(), SqlStatement::addUInt32(), Object::ApplyModFlag(), ItemPrototype::Bonding, CharacterDatabase, Database::CreateStatement(), ItemPrototype::Duration, SqlStatement::Execute(), ItemPrototype::Flags, Object::GetGUIDLow(), GetItemRandomPropertyId(), GetMaxStackCount(), GetOwnerGuid(), GetProto(), Field::GetUInt16(), Field::GetUInt32(), Object::GetUInt32Value(), Object::HasFlag(), HIGHGUID_ITEM, HIGHGUID_PLAYER, IsSoulBound(), ITEM_DYNFLAG_BINDED, ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_CREATE_PLAYED_TIME, ITEM_FIELD_CREATOR, ITEM_FIELD_DURABILITY, ITEM_FIELD_DURATION, ITEM_FIELD_ENCHANTMENT_1_1, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, ITEM_FIELD_MAXDURABILITY, ITEM_FIELD_RANDOM_PROPERTIES_ID, ITEM_FLAG_IS_WRAPPER, MAX_ENCHANTMENT_OFFSET, MAX_ENCHANTMENT_SLOT, MAX_ITEM_PROTO_SPELLS, ItemPrototype::MaxDurability, NO_BIND, SqlStatement::PExecute(), Object::RemoveFlag(), SetCount(), Object::SetEntry(), Object::SetGuidValue(), Object::SetInt32Value(), Object::SetObjectScale(), SetOwnerGuid(), SetSpellCharges(), SetText(), Object::SetUInt32Value(), StrSplit(), and UpdateItemSuffixFactor().
Referenced by Player::_LoadInventory(), Player::_LoadMailedItems(), Player::DeleteFromDB(), AuctionHouseMgr::LoadAuctionItems(), Bag::LoadFromDB(), and Guild::LoadGuildBankFromDB().
LoadLootFromDB()
void Item::LoadLootFromDB (Field * fields)
Definition at line 531 of file Item.cpp.
References Loot::AddItem(), CharacterDatabase, Object::GetGUIDLow(), Field::GetInt32(), ObjectMgr::GetItemPrototype(), GetOwnerGuid(), Field::GetUInt32(), ITEM_LOOT_UNCHANGED, Object::m_loot, Database::PExecute(), Loot::SetGoldAmount(), SetLootState(), and sLog.
Referenced by Player::_LoadItemLoot().
RemoveFromClientUpdateList()
void Item::RemoveFromClientUpdateList () override virtual
Reimplemented from Object.
Definition at line 1206 of file Item.cpp.
References GetOwner().
RemoveFromUpdateQueueOf()
void Item::RemoveFromUpdateQueueOf (Player * player)
Definition at line 808 of file Item.cpp.
References Object::GetGuidStr(), Object::GetObjectGuid(), GetOwner(), GetOwnerGuid(), IsInUpdateQueue(), Player::m_itemUpdateQueue, Player::m_itemUpdateQueueBlocked, sLog, and uQueuePos.
Referenced by WorldSession::HandleSellItemOpcode(), WorldSession::HandleWrapItemOpcode(), and SetState().
RestoreCharges()
void Item::RestoreCharges ()
Definition at line 1286 of file Item.cpp.
References GetProto(), GetSpellCharges(), ITEM_CHANGED, MAX_ITEM_PROTO_SPELLS, SetSpellCharges(), SetState(), _Spell::SpellCharges, and ItemPrototype::Spells.
Referenced by Player::_LoadInventory(), and Spell::EffectRestoreItemCharges().
SaveToDB()
void Item::SaveToDB () virtual
Reimplemented in Bag.
Definition at line 265 of file Item.cpp.
References SqlStatement::addInt32(), SqlStatement::addUInt32(), SqlStatement::addUInt8(), CharacterDatabase, LootItem::count, Database::CreateStatement(), SqlStatement::Execute(), GetCount(), GetEnchantmentCharges(), GetEnchantmentDuration(), GetEnchantmentId(), Object::GetEntry(), Loot::GetGoldAmount(), Object::GetGUIDLow(), Object::GetGuidValue(), GetItemRandomPropertyId(), Loot::GetLootItemsListFor(), GetOwner(), GetOwnerGuid(), GetSpellCharges(), GetText(), Object::GetUInt32Value(), Object::HasFlag(), HasSavedLoot(), ITEM_CHANGED, ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_CREATE_PLAYED_TIME, ITEM_FIELD_CREATOR, ITEM_FIELD_DURABILITY, ITEM_FIELD_DURATION, ITEM_FIELD_FLAGS, ITEM_FIELD_GIFTCREATOR, ITEM_LOOT_CHANGED, ITEM_LOOT_NEW, ITEM_LOOT_NONE, ITEM_LOOT_REMOVED, ITEM_LOOT_TEMPORARY, ITEM_LOOT_UNCHANGED, ITEM_NEW, ITEM_REMOVED, ITEM_UNCHANGED, LootItem::itemId, Object::m_loot, m_lootState, MAX_ENCHANTMENT_SLOT, MAX_ITEM_PROTO_SPELLS, SqlStatement::PExecute(), LootItem::randomPropertyId, LootItem::randomSuffix, SetLootState(), SetState(), and uState.
Referenced by Player::_LoadInventory(), Player::_LoadMailedItems(), Guild::_StoreItem(), AuctionHouseObject::AddAuction(), Player::AutoUnequipOffhandIfNeed(), MailDraft::CloneFrom(), AchievementMgr::CompletedAchievement(), Player::DeleteFromDB(), WorldSession::HandleSendMail(), Guild::MoveFromBankToChar(), BattleGroundMgr::RewardArenaSeason(), Player::SaveItemToInventory(), Bag::SaveToDB(), MailDraft::SendReturnToSender(), and Guild::SwapItems().
SendTimeUpdate()
void Item::SendTimeUpdate (Player * owner) const
Definition at line 1122 of file Item.cpp.
References Object::GetObjectGuid(), Player::GetSession(), Object::GetUInt32Value(), ITEM_FIELD_DURATION, WorldSession::SendPacket(), and SMSG_ITEM_TIME_UPDATE.
Referenced by Player::AddItemDurations().
SendUpdateSockets()
void Item::SendUpdateSockets ()
Definition at line 1109 of file Item.cpp.
References BONUS_ENCHANTMENT_SLOT, GetEnchantmentId(), Object::GetObjectGuid(), GetOwner(), Player::SendDirectMessage(), SMSG_SOCKET_GEMS_RESULT, and SOCK_ENCHANTMENT_SLOT.
Referenced by WorldSession::HandleSocketOpcode().
SetBinding()
void Item::SetBinding (bool val) inline
Definition at line 287 of file Item.h.
References Object::ApplyModFlag(), ITEM_DYNFLAG_BINDED, and ITEM_FIELD_FLAGS.
Referenced by Player::_StoreItem(), ChatHandler::HandleAddItemCommand(), ChatHandler::HandleAddItemSetCommand(), WorldSession::HandleUseItemOpcode(), and Player::VisualizeItem().
SetContainer()
void Item::SetContainer (Bag * container) inline
Definition at line 324 of file Item.h.
References m_container.
Referenced by Player::_LoadInventory(), Player::_StoreItem(), Bag::RemoveItem(), Bag::StoreItem(), and Player::VisualizeItem().
SetCount()
void Item::SetCount (uint32 value) inline
Definition at line 313 of file Item.h.
References ITEM_FIELD_STACK_COUNT, and Object::SetUInt32Value().
Referenced by Player::_StoreItem(), Guild::_StoreItem(), CreateItem(), Player::DestroyItemCount(), Player::EquipItem(), WorldSession::HandleSellItemOpcode(), LoadFromDB(), Guild::MoveFromBankToChar(), Guild::MoveFromCharToBank(), Player::SplitItem(), Player::SwapItem(), and Guild::SwapItems().
SetEnchantment()
void Item::SetEnchantment (EnchantmentSlot slot, uint32 id, uint32 duration, uint32 charges, ObjectGuid caster = ObjectGuid())
Definition at line 966 of file Item.cpp.
References ENCHANTMENT_CHARGES_OFFSET, ENCHANTMENT_DURATION_OFFSET, ENCHANTMENT_ID_OFFSET, GetEnchantmentCharges(), GetEnchantmentDuration(), GetEnchantmentId(), Object::GetEntry(), GetOwner(), ITEM_CHANGED, ITEM_FIELD_ENCHANTMENT_1_1, MAX_ENCHANTMENT_OFFSET, MAX_INSPECTED_ENCHANTMENT_SLOT, Unit::SendEnchantmentLog(), SetState(), and Object::SetUInt32Value().
Referenced by Player::ConvertItem(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), WorldSession::HandleSocketOpcode(), and SetItemRandomProperties().
SetEnchantmentCharges()
void Item::SetEnchantmentCharges (EnchantmentSlot slot, uint32 charges)
Definition at line 997 of file Item.cpp.
References ENCHANTMENT_CHARGES_OFFSET, GetEnchantmentCharges(), ITEM_CHANGED, ITEM_FIELD_ENCHANTMENT_1_1, MAX_ENCHANTMENT_OFFSET, SetState(), and Object::SetUInt32Value().
Referenced by Player::SetVirtualItemSlot().
SetEnchantmentDuration()
void Item::SetEnchantmentDuration (EnchantmentSlot slot, uint32 duration)
Definition at line 988 of file Item.cpp.
References ENCHANTMENT_DURATION_OFFSET, GetEnchantmentDuration(), ITEM_CHANGED, ITEM_FIELD_ENCHANTMENT_1_1, MAX_ENCHANTMENT_OFFSET, SetState(), and Object::SetUInt32Value().
Referenced by Player::RemoveEnchantmentDurations().
SetInTrade()
void Item::SetInTrade (bool b = true) inline
Definition at line 304 of file Item.h.
References mb_in_trade.
Referenced by clearAcceptTradeMode(), and setAcceptTradeMode().
SetItemRandomProperties()
void Item::SetItemRandomProperties (int32 randomPropId)
Definition at line 702 of file Item.cpp.
References ItemRandomPropertiesEntry::enchant_id, ItemRandomSuffixEntry::enchant_id, Object::GetInt32Value(), GetItemSuffixFactor(), ItemRandomPropertiesEntry::ID, ItemRandomSuffixEntry::ID, ITEM_CHANGED, ITEM_FIELD_RANDOM_PROPERTIES_ID, PROP_ENCHANTMENT_SLOT_0, PROP_ENCHANTMENT_SLOT_2, SetEnchantment(), Object::SetInt32Value(), SetState(), sItemRandomPropertiesStore, sItemRandomSuffixStore, and UpdateItemSuffixFactor().
Referenced by CreateItem().
SetLootState()
void Item::SetLootState (ItemLootUpdateState state)
Definition at line 1300 of file Item.cpp.
References ITEM_CHANGED, ITEM_LOOT_CHANGED, ITEM_LOOT_NEW, ITEM_LOOT_NONE, ITEM_LOOT_REMOVED, ITEM_LOOT_TEMPORARY, ITEM_LOOT_UNCHANGED, m_lootState, and SetState().
Referenced by LoadLootFromDB(), Loot::Loot(), Loot::Release(), and SaveToDB().
SetOwnerGuid()
void Item::SetOwnerGuid (ObjectGuid guid) inline
Definition at line 284 of file Item.h.
References ITEM_FIELD_OWNER, and Object::SetGuidValue().
Referenced by Player::_StoreItem(), Player::EquipItem(), LoadFromDB(), and Player::MoveItemToInventory().
SetSlot()
void Item::SetSlot (uint8 slot) inline
Definition at line 322 of file Item.h.
References m_slot.
Referenced by Player::_LoadInventory(), Player::_StoreItem(), Player::DestroyItem(), Bag::StoreItem(), and Player::VisualizeItem().
SetSpellCharges()
void Item::SetSpellCharges (uint8 index, int32 value) inline
Definition at line 356 of file Item.h.
References ITEM_FIELD_SPELL_CHARGES, and Object::SetInt32Value().
Referenced by Create(), LoadFromDB(), RestoreCharges(), and Spell::TakeCastItem().
SetState()
void Item::SetState (ItemUpdateState state, Player * forplayer = nullptr)
Definition at line 750 of file Item.cpp.
References AddToUpdateQueueOf(), GetOwnerGuid(), ITEM_NEW, ITEM_REMOVED, ITEM_UNCHANGED, RemoveFromUpdateQueueOf(), uQueuePos, and uState.
Referenced by Player::_LoadInventory(), Player::_StoreItem(), ClearEnchantment(), Player::DestroyItem(), Player::DestroyItemCount(), Player::DurabilityPointsLoss(), Player::DurabilityRepair(), Player::EquipItem(), WorldSession::HandleOpenItemOpcode(), WorldSession::HandlePetitionBuyOpcode(), WorldSession::HandleSellItemOpcode(), WorldSession::HandleUseItemOpcode(), WorldSession::HandleWrapItemOpcode(), Guild::MoveFromCharToBank(), Player::MoveItemToInventory(), Player::RemoveItemFromBuyBackSlot(), RestoreCharges(), SaveToDB(), SetEnchantment(), SetEnchantmentCharges(), SetEnchantmentDuration(), SetItemRandomProperties(), SetLootState(), Player::SplitItem(), Player::SwapItem(), Spell::TakeCastItem(), UpdateDuration(), and Player::VisualizeItem().
SetText()
void Item::SetText (std::string const & text) inline
Definition at line 347 of file Item.h.
References m_text.
Referenced by WorldSession::HandleMailCreateTextItem(), and LoadFromDB().
SetUsedInSpell()
void Item::SetUsedInSpell (bool state) inline
Definition at line 388 of file Item.h.
References m_usedInSpell.
Referenced by Player::CastItemUseSpell(), Spell::EffectSummonChangeItem(), Spell::TakeCastItem(), Spell::TakeReagents(), and Spell::~Spell().
UpdateDuration()
void Item::UpdateDuration (Player * owner, uint32 diff)
Definition at line 244 of file Item.cpp.
References Player::ConvertItem(), Player::DestroyItem(), GetBagSlot(), Object::GetEntry(), GetSlot(), Object::GetUInt32Value(), IsUsedInSpell(), ITEM_CHANGED, ITEM_FIELD_DURATION, SetState(), Object::SetUInt32Value(), and sObjectMgr.
Referenced by Player::UpdateItemDuration().
UpdateItemSuffixFactor()
void Item::UpdateItemSuffixFactor ()
Definition at line 740 of file Item.cpp.
References GenerateEnchSuffixFactor(), Object::GetEntry(), GetItemSuffixFactor(), ITEM_FIELD_PROPERTY_SEED, and Object::SetUInt32Value().
Referenced by LoadFromDB(), and SetItemRandomProperties().
Field Documentation
m_container
Bag* Item::m_container private
Definition at line 394 of file Item.h.
Referenced by GetBagSlot(), GetContainer(), IsInBag(), Item(), and SetContainer().
m_lootState
ItemLootUpdateState Item::m_lootState private
Definition at line 398 of file Item.h.
Referenced by HasGeneratedLoot(), HasSavedLoot(), HasTemporaryLoot(), Item(), SaveToDB(), and SetLootState().
m_slot
uint8 Item::m_slot private
Definition at line 393 of file Item.h.
Referenced by GetSlot(), IsEquipped(), Item(), and SetSlot().
m_text
std::string Item::m_text private
Definition at line 392 of file Item.h.
Referenced by GetText(), and SetText().
m_usedInSpell
bool Item::m_usedInSpell private
Definition at line 399 of file Item.h.
Referenced by IsUsedInSpell(), Item(), and SetUsedInSpell().
mb_in_trade
bool Item::mb_in_trade private
Definition at line 397 of file Item.h.
Referenced by IsInTrade(), Item(), and SetInTrade().
uQueuePos
int16 Item::uQueuePos private
Definition at line 396 of file Item.h.
Referenced by AddToUpdateQueueOf(), GetQueuePos(), IsInUpdateQueue(), Item(), RemoveFromUpdateQueueOf(), and SetState().
uState
ItemUpdateState Item::uState private
Definition at line 395 of file Item.h.
Referenced by FSetState(), GetState(), Item(), SaveToDB(), and SetState().
The documentation for this class was generated from the following files:
Item.h
Item.cpp