CMaNGOS_WoTLK: Creature Class Reference
Creature Class Reference
#include <Creature.h>
Public Types
enum CooldownResult { COOLDOWN_RESULT_NOT_FOUND = 0 , COOLDOWN_RESULT_FOUND = 1 , COOLDOWN_RESULT_CATEGORY_FOUND = 2 }
Public Types inherited from Unit
enum class SpellProcEventTriggerCheck { SPELL_PROC_TRIGGER_FAILED = 0 , SPELL_PROC_TRIGGER_ROLL_FAILED = 1 , SPELL_PROC_TRIGGER_OK = 2 }
typedef std::set< Unit * > AttackerSet
typedef std::multimap< uint32, SpellAuraHolder * > SpellAuraHolderMap
typedef std::pair< SpellAuraHolderMap::iterator, SpellAuraHolderMap::iterator > SpellAuraHolderBounds
typedef std::pair< SpellAuraHolderMap::const_iterator, SpellAuraHolderMap::const_iterator > SpellAuraHolderConstBounds
typedef std::list< SpellAuraHolder * > SpellAuraHolderList
typedef std::list< Aura * > AuraList
typedef std::list< DiminishingReturn > Diminishing
typedef std::set< uint32 > ComboPointHolderSet
typedef std::map< uint8, uint32 > VisibleAuraMap
typedef std::map< SpellEntry const *, ObjectGuid > TrackedAuraTargetMap
typedef std::set< PetAura const * > PetAuraSet
Public Member Functions
Creature (CreatureSubtype subtype=CREATURE_SUBTYPE_GENERIC)
virtual ~Creature ()
void AddToWorld () override
void RemoveFromWorld () override
virtual void CleanupsBeforeDelete () override
bool Create (uint32 dbGuid, uint32 guidlow, CreatureCreatePos &cPos, CreatureInfo const *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
bool LoadCreatureAddon (bool reload)
void SelectLevel (uint32 forcedLevel=USE_DEFAULT_DATABASE_LEVEL)
void LoadEquipment (uint32 equip_entry, bool force=false)
bool HasStaticDBSpawnData () const
char const * GetSubName () const
void Update (const uint32 diff) override
virtual void RegenerateAll (uint32 update_diff)
uint32 GetEquipmentId () const
CreatureSubtype GetSubtype () const
bool IsPet () const
bool IsTotem () const
bool IsTemporarySummon () const
bool IsCritter () const
bool IsCorpse () const
bool IsDespawned () const
void SetCorpseDelay (uint32 delay)
void ReduceCorpseDecayTimer ()
TimePoint GetCorpseDecayTimer () const
bool CanRestockPickpocketLoot () const
void StartPickpocketRestockTimer ()
bool IsRacialLeader () const
bool IsCivilian () const
bool IsNoAggroOnSight () const
bool IsGuard () const
bool CanWalk () const
bool CanSwim () const
bool IsSwimming () const
bool CanFly () const override
bool IsFlying () const override
bool IsTrainerOf (Player *pPlayer, bool msg) const
bool CanInteractWithBattleMaster (Player *pPlayer, bool msg) const
bool CanTrainAndResetTalentsOf (Player *pPlayer) const
void FillGuidsListFromThreatList (GuidVector &guids, uint32 maxamount=0)
bool IsImmuneToSpell (SpellEntry const *spellInfo, bool castOnSelf, uint8 effectMask, WorldObject const *caster) override
bool IsImmuneToDamage (SpellSchoolMask meleeSchoolMask) override
bool IsImmuneToSpellEffect (SpellEntry const *spellInfo, SpellEffectIndex index, bool castOnSelf) const override
bool IsElite () const
bool IsWorldBoss () const
uint32 GetLevelForTarget (Unit const *target) const override
uint8 getRace () const override
bool AIM_Initialize ()
virtual UnitAI * AI () override
virtual CombatData * GetCombatData () override
void SetWalk (bool enable, bool asDefault=true)
uint32 GetShieldBlockValue () const override
bool HasSpell (uint32 spellID) const override
void UpdateSpell (int32 index, int32 newSpellId)
void SetSpellList (uint32 spellSet)
void UpdateImmunitiesSet (uint32 immunitySet)
bool UpdateEntry (uint32 Entry, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr, bool preserveHPAndPower=true, bool randomizeLevels=true)
void ResetEntry (bool respawn=false)
void ApplyGameEventSpells (GameEventCreatureData const *eventData, bool activated)
bool UpdateStats (Stats stat) override
bool UpdateAllStats () override
void UpdateResistances (uint32 school) override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers power) override
void UpdateAttackPowerAndDamage (bool ranged=false) override
void UpdateDamagePhysical (WeaponAttackType attType) override
uint32 GetCurrentEquipmentId () const
VendorItemData const * GetVendorItems () const
VendorItemData const * GetVendorTemplateItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
TrainerSpellData const * GetTrainerTemplateSpells () const
TrainerSpellData const * GetTrainerSpells () const
CreatureInfo const * GetCreatureInfo () const
CreatureDataAddon const * GetCreatureAddon () const
std::string GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
const char * GetNameForLocaleIdx (int32 loc_idx) const override
void SetDeathState (DeathState s) override
bool LoadFromDB (uint32 dbGuid, Map *map, uint32 newGuid, uint32 forcedEntry, GenericTransport *transport=nullptr)
virtual void SaveToDB ()
virtual void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask)
virtual void DeleteFromDB ()
void PrepareBodyLootState ()
CreatureLootStatus GetLootStatus () const
virtual void InspectingLoot () override
void SetLootStatus (CreatureLootStatus status, bool forced=false)
bool IsTappedBy (Player *plr) const
ObjectGuid GetLootRecipientGuid () const
uint32 GetLootGroupRecipientId () const
Player * GetLootRecipient () const
Return player who can loot tapped creature (member of group or single player)
Group * GetGroupLootRecipient () const
Return group if player tap creature as group member, independent is player after leave group or stil be group member.
void SetCorpseAccelerationDelay (uint32 delay)
bool HasLootRecipient () const
bool IsGroupLootRecipient () const
void SetLootRecipient (Unit *unit)
Set player and group (if player group member) who tap creature.
Player * GetOriginalLootRecipient () const
Return original player who tap creature, it can be different from player/group allowed to loot so not use it for loot code.
SpellEntry const * ReachWithSpellAttack (Unit *pVictim)
SpellEntry const * ReachWithSpellCure (Unit *pVictim)
void CallForHelp (float radius)
void CallAssistance ()
void SetNoCallAssistance (bool val)
bool CanAssistTo (const Unit *u, const Unit *enemy, bool checkfaction=true) const
if enemy provided, check for initial combat help against enemy
bool CanInitiateAttack () const
bool CanCallForAssistance () const override
void SetCanCallForAssistance (bool state)
bool IsInGroup (Unit const *other, bool party, bool ignoreCharms) const override
[Serverside] Group: Extension for creatures, player-controlled defaults to unit, creatures check based on friendliness
MovementGeneratorType GetDefaultMovementType () const
void SetDefaultMovementType (MovementGeneratorType mgt)
bool IsVisibleInGridForPlayer (Player *pl) const override
void RemoveCorpse (bool inPlace=false)
virtual void ForcedDespawn (uint32 timeMSToDespawn=0, bool onlyAlive=false)
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn ()
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay, bool once=false)
float GetRespawnRadius () const
void SetRespawnRadius (float dist)
void SendZoneUnderAttackMessage (Player *attacker) const
Sends a message to LocalDefense and WorldDefense channels for players of the other team.
void SetInCombatWithZone (bool checkAttackability=true)
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32 quest_id) const override
void SetDefaultGossipMenuId (uint32 menuId)
uint32 GetDefaultGossipMenuId () const
uint32 GetInteractionPauseTimer () const
GridReference< Creature > & GetGridRef ()
bool IsRegeneratingHealth () const
bool IsRegeneratingPower () const
virtual uint8 GetPetAutoSpellSize () const
virtual uint32 GetPetAutoSpellOnPos (uint8 pos) const
void SetCombatStartPosition (Position const &pos)
void GetCombatStartPosition (Position &pos) const
Position const & GetCombatStartPosition () const
uint32 GetPursuit () const override
void SetRespawnCoord (CreatureCreatePos const &pos)
void SetRespawnCoord (float x, float y, float z, float ori)
void GetRespawnCoord (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
Position const & GetRespawnPosition () const
void ResetRespawnCoord ()
void SetFactionTemporary (uint32 factionId, uint32 tempFactionFlags=TEMPFACTION_ALL)
void ClearTemporaryFaction ()
uint32 GetTemporaryFactionFlags () const
void SendAreaSpiritHealerQueryOpcode (Player *pl) const
void SetVirtualItem (VirtualItemSlot slot, uint32 item_id)
bool hasWeapon (WeaponAttackType type) const override
Checks if the current Unit has a weapon equipped at the moment.
bool hasWeaponForAttack (WeaponAttackType type) const override
Checks if the current Unit has a usable weapon at the moment.
virtual void SetCanDualWield (bool value)
void SetInvisible (bool invisible)
bool IsInvisible () const
void SetIgnoreMMAP (bool ignore)
bool IsIgnoringMMAP () const
void OnEventHappened (uint16 eventId, bool activate, bool resume) override
void SetForceAttackingCapability (bool state)
bool GetForceAttackingCapability () const
void SetSpawnCounting (bool state)
uint32 GetDetectionRange () const override
void SetDetectionRange (uint32 range)
void SetBaseWalkSpeed (float speed) override
void SetBaseRunSpeed (float speed, bool force=true) override
void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration) override
bool CanAggro () const
void SetCanAggro (bool canAggro)
bool CanCheckForHelp () const override
void SetCanCheckForHelp (bool state)
void SetNoRewards ()
bool IsNoXp ()
void SetNoXP (bool state)
bool IsNoLoot ()
void SetNoLoot (bool state)
bool IsNoReputation ()
void SetNoReputation (bool state)
bool IsIgnoringFeignDeath () const
void SetIgnoreFeignDeath (bool state)
void SetNoWoundedSlowdown (bool state)
bool IsNoWoundedSlowdown () const
bool IsSlowedInCombat () const override
void SetNoWeaponSkillGain (bool state)
bool IsNoWeaponSkillGain () const override
bool IsPreventingDeath () const override
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false) override
bool HasBeenHitBySpell (uint32 spellId)
void RegisterHitBySpell (uint32 spellId)
void UnregisterHitBySpell (uint32 spellId)
void ResetSpellHitCounter ()
HighGuid GetParentHigh () const override
void Heartbeat () override
CreatureSpellList const & GetSpellList () const
std::vector< uint32 > GetCharmSpells () const
CooldownResult GetSpellCooldown (uint32 spellId, uint32 &cooldown) const
void SetCreatureGroup (CreatureGroup *group)
void ClearCreatureGroup ()
CreatureGroup * GetCreatureGroup () const
CreatureSettings const & GetSettings () const
CreatureSettings & GetSettings ()
void StartCooldown (Unit *owner)
bool IsOnlyVisibleTo (ObjectGuid guid) const override
void SetOnlyVisibleTo (ObjectGuid guid)
ObjectGuid GetKillerGuid () const
void SetKillerGuid (ObjectGuid guid)
virtual uint32 GetDuration () const
Public Member Functions inherited from Unit
virtual ~Unit ()
void AddToWorld () override
void RemoveFromWorld () override
void CleanupsBeforeDelete () override
float GetCollisionHeight () const override
float GetCollisionWidth () const override
float GetObjectBoundingRadius () const override
float GetCombatReach () const override
DiminishingLevels GetDiminishing (DiminishingGroup group)
Gets the current DiminishingLevels for the given group.
void IncrDiminishing (DiminishingGroup group, bool pvp)
Increases the level of the DiminishingGroup by one level up until DIMINISHING_LEVEL_IMMUNE where the target becomes immune to spells of that DiminishingGroup.
void ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, bool isReflected, SpellEntry const *spellInfo, bool hasAuraScript)
Calculates how long the duration of a spell should be considering diminishing returns, ie, if the Level passed in is DIMINISHING_LEVEL_IMMUNE then the duration will be zeroed out.
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
Applies a diminishing return to the given group if apply is true, otherwise lowers the level by one (?)
void ClearDiminishings ()
Clears all the current diminishing returns for this Unit.
void Update (const uint32 diff) override
void Heartbeat () override
void setAttackTimer (WeaponAttackType type, uint32 time)
Updates the attack time for the given WeaponAttackType.
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
Resets the attack timer to the base value decided by Unit::m_modAttackSpeedPct and Unit::GetAttackTime.
uint32 getAttackTimer (WeaponAttackType type) const
Get's the remaining time until we can do an attack.
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
Checks whether the unit can do an attack.
bool hasMainhandWeapon () const
bool hasOffhandWeapon () const
bool hasRangedWeapon () const
bool hasMainhandWeaponForAttack () const
bool hasOffhandWeaponForAttack () const
bool hasRangedWeaponForAttack () const
bool UpdateMeleeAttackingState ()
Does an attack if any of the timers allow it and resets them, if the user isn't in range or behind the target an error is sent to the client.
bool CanUseEquippedWeapon (WeaponAttackType attackType) const
Check is a given equipped weapon can be used, ie the mainhand, offhand etc.
bool CanReachWithMeleeAttack (Unit const *pVictim, float flat_mod=0.0f) const
Returns if the Unit can reach a victim with Melee Attack.
void DoExtraAttacks (Unit *pVictim)
bool IsAttackedBy (Unit *attacker) const
bool _addAttacker (Unit *pAttacker)
void _removeAttacker (Unit *pAttacker)
Unit * getAttackerForHelper ()
bool Attack (Unit *victim, bool meleeAttack)
Tries to attack a Unit/Player, also makes sure to stop attacking the current target if we're already attacking someone.
void AttackedBy (Unit *attacker)
Called when we are attacked by someone in someway, might be when a fear runs out and we want to notify AI to attack again or when a spell hits.
void CastStop (uint32 except_spellid=0)
Stop all spells from casting except the one give by except_spellid.
bool AttackStop (bool targetSwitch=false, bool includingCast=false, bool includingCombo=false, bool clientInitiated=false)
Stops attacking whatever we are attacking at the moment and tells the Unit we are attacking that we are not doing that anymore.
void RemoveAllAttackers ()
Removes all attackers from the Unit::m_attackers set and logs it if someone that wasn't attacking it was in the list.
void MeleeAttackStart (Unit *victim)
void MeleeAttackStop (Unit *victim)
AttackerSet const & getAttackers () const
Returns the Unit::m_attackers, that stores the units that are attacking you.
Unit * GetVictim () const
void CombatStop (bool includingCast=false, bool includingCombo=true)
void CombatStopWithPets (bool includingCast=false, bool includingCombo=true)
void StopAttackFaction (uint32 faction_id)
Unit * SelectRandomUnfriendlyTarget (Unit *except=nullptr, float radius=ATTACK_DISTANCE) const
Unit * SelectRandomFriendlyTarget (Unit *except=nullptr, float radius=ATTACK_DISTANCE) const
bool HasDamageInterruptibleStunAura () const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr, uint32 excludeAuraApplyMSTimeCutoff=0) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura, uint32 excludeAuraApplyMSTimeCutoff) const
bool HasAuraPetShouldAvoidBreaking (Unit *excludeCasterChannel=nullptr, uint32 excludeAuraApplyMSTimeCutoff=0) const
void SendMeleeAttackStop (const Unit &victim) const
void SendMeleeAttackStart (const Unit &victim) const
void addUnitState (uint32 f)
bool hasUnitState (uint32 f) const
void clearUnitState (uint32 f)
bool CanFreeMove () const
bool IsTrivialForTarget (Unit const *pov) const
Trivial: Unit does not count as a worthy target for another unit.
void SetLevel (uint32 lvl)
uint32 GetLevel () const override
uint32 getRaceMask () const
uint8 getClass () const
uint32 getClassMask () const
uint8 getGender () const
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
int32 GetArmor () const
void SetArmor (int32 val)
int32 GetResistance (SpellSchools school) const
void SetResistance (SpellSchools school, int32 val)
uint32 GetHealth () const
uint32 GetMaxHealth () const
float GetHealthPercent () const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetHealthPercent (float percent)
int32 ModifyHealth (int32 dVal)
float OCTRegenHPPerSpirit () const
float OCTRegenMPPerSpirit () const
Powers GetPowerType () const
void SetPowerType (Powers new_powertype, bool sendUpdate=true)
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
float GetPowerPercent () const
float GetPowerPercent (Powers power) const
void SetPower (Powers power, uint32 val, bool withPowerUpdate=true)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 dVal)
void ApplyPowerMod (Powers power, uint32 val, bool apply)
void ApplyMaxPowerMod (Powers power, uint32 val, bool apply)
bool HasMana ()
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint32 GetFaction () const override
void setFaction (uint32 faction)
FactionTemplateEntry const * GetFactionTemplateEntry () const
void RestoreOriginalFaction ()
bool IsNeutralToAll () const
bool IsContestedGuard () const
Player const * GetControllingPlayer (bool ignoreCharms=false) const
Controlling player: get which player is the "master" of the unit gameplay-wise.
ReputationRank GetReactionTo (Unit const *unit) const override
Get unit to unit reaction.
ReputationRank GetReactionTo (Corpse const *corpse) const override
Get unit to corpse reaction.
bool IsEnemy (Unit const *unit) const override
Reaction preset: Unit sees another unit as an enemy.
bool IsFriend (Unit const *unit) const override
Reaction preset: Unit sees another unit as a friend.
bool CanAssist (Unit const *unit, bool ignoreFlags=false) const
Assistance: Unit treats another unit as an ally it can help.
bool CanAssist (Corpse const *corpse) const
Assistance: Unit treats a corpse as an ally corpse it can help.
bool CanAttack (Unit const *unit, bool ignoreUntargetable=false) const
Opposition: Unit treats another unit as an enemy it can attack (generic)
bool CanAttackNow (Unit const *unit) const
Opposition: Unit treats another unit as an enemy it can attack (immediate response)
bool CanCooperate (Unit const *unit) const
Cooperation: Unit can cooperate with another unit.
bool CanInteract (GameObject const *object) const
Interaction: Unit can interact with an object (generic)
bool CanInteract (Unit const *unit) const
Interaction: Unit can interact with another unit (generic)
bool CanInteractNow (Unit const *unit) const
Interaction: Unit can interact with another unit (immediate response)
bool IsCivilianForTarget (Unit const *pov) const
Civilian: Unit counts as a dishonorable kill for another unit.
bool IsFogOfWarVisibleStealth (Unit const *other) const
[Serverside] Fog of War: Unit can be seen by other unit through invisibility effects
bool IsFogOfWarVisibleHealth (Unit const *other) const
[Serverside] Fog of War: Unit's health values can be seen by other unit
bool IsFogOfWarVisibleStats (Unit const *other) const
[Serverside] Fog of War: Unit's stat values can be seen by other unit
bool IsInParty (Unit const *other, bool ignoreCharms=false) const
bool IsInGuild (Unit const *other, bool ignoreCharms=false) const
[Serverside] Guild: Unit counts as being placed in the same guild with another unit (for gameplay purposes)
bool IsInTeam (Unit const *other, bool ignoreCharms=true) const
[Serverside] Team: Check if both units are in the same faction team (for gameplay purposes)
virtual bool CanAttackSpell (Unit const *target, SpellEntry const *spellInfo=nullptr, bool isAOE=false) const override
[Serverside] Opposition: Unit can target a target with a harmful spell
virtual bool CanAssistSpell (Unit const *target, SpellEntry const *spellInfo=nullptr) const override
[Serverside] Assistance: Unit can target a target with a helpful spell
bool CanAttackOnSight (Unit const *target) const
[Serverside] Opposition: Unit can attack a target on sight
bool CanAttackInCombat (Unit const *target, bool ignoreUntargetable=false) const
[Serverside] Opposition: Unit can attack a target on sight
bool CanAssistInCombatAgainst (Unit const *who, Unit const *enemy) const
[Serverside] Opposition: this can assist who in attacking enemy
bool CanJoinInAttacking (Unit const *enemy) const
[Serverside] Opposition: this can join combat against enemy
bool IsImmuneToNPC () const
void SetImmuneToNPC (bool state)
bool IsImmuneToPlayer () const
void SetImmuneToPlayer (bool state)
bool IsPlayerControlled () const
uint32 GetCreatedBySpellId () const
bool IsPvP () const
void SetPvP (bool state)
bool IsPvPFreeForAll () const
void SetPvPFreeForAll (bool state)
bool IsPvPContested () const
void SetPvPContested (bool state)
bool IsPvPSanctuary () const
void SetPvPSanctuary (bool state)
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
bool IsSeatedState () const
bool IsStandUpOnMovementState () const
void SetStandState (uint8 state, bool acknowledge=false)
void SetVisFlags (uint8 flags)
void RemoveVisFlags (uint8 flags)
bool HasVisFlags (uint8 flags)
bool IsMounted () const
uint32 GetMountID () const
virtual bool Mount (uint32 displayid, const Aura *aura=nullptr)
virtual bool Unmount (const Aura *aura=nullptr)
VehicleInfo * GetVehicleInfo () const
bool IsVehicle () const
void SetVehicleId (uint32 entry, uint32 overwriteNpcEntry)
Unit const * FindRootVehicle (const Unit *whichVehicle=nullptr) const
uint16 GetSkillMaxForLevel (Unit const *target=nullptr) const
void Suicide ()
void FallSuicide ()
int32 DealHeal (Unit *pVictim, uint32 addhealth, SpellEntry const *spellProto, bool critical=false, uint32 absorb=0)
void InterruptOrDelaySpell (Unit *pVictim, DamageEffectType damagetype, SpellEntry const *spellProto)
void PetOwnerKilledUnit (Unit *pVictim)
void ProcDamageAndSpellFor (ProcSystemArguments &data, bool isVictim)
void ProcSkillsAndReactives (bool isVictim, Unit *target, uint32 procFlags, uint32 procEx, WeaponAttackType attType)
void HandleEmote (uint32 emote_id)
void HandleEmoteCommand (uint32 emote_id)
void HandleEmoteState (uint32 emote_id)
void AttackerStateUpdate (Unit *pVictim, WeaponAttackType attType=BASE_ATTACK, bool extra=false)
void CalculateMeleeDamage (Unit *pVictim, CalcDamageInfo *calcDamageInfo, WeaponAttackType attackType=BASE_ATTACK)
void DealMeleeDamage (CalcDamageInfo *calcDamageInfo, bool durabilityLoss)
void CalculateSpellDamage (SpellNonMeleeDamage *spellDamageInfo, int32 damage, SpellEntry const *spellInfo, WeaponAttackType attackType=BASE_ATTACK)
uint32 GetResilienceRatingDamageReduction (uint32 damage, SpellDmgClass dmgClass, bool periodic=false, Powers pwrType=POWER_HEALTH) const
SpellMissInfo MeleeSpellHitResult (Unit *pVictim, SpellEntry const *spell, uint32 *heartbeatResistChance=nullptr)
SpellMissInfo MagicSpellHitResult (Unit *pVictim, SpellEntry const *spell, SpellSchoolMask schoolMask, uint32 *heartbeatResistChance=nullptr)
bool CanDualWield () const
bool CanDodge () const
bool CanParry () const
bool CanBlock () const
bool CanCrush () const
bool CanGlance () const
bool CanDaze () const
void SetCanDodge (const bool flag)
void SetCanParry (const bool flag)
void SetCanBlock (const bool flag)
bool CanReactInCombat () const
bool CanCastSpellInCombat () const
bool CanDodgeInCombat () const
bool CanDodgeInCombat (const Unit *attacker) const
bool CanParryInCombat () const
bool CanParryInCombat (const Unit *attacker) const
bool CanBlockInCombat (SpellSchoolMask weaponSchoolMask=SPELL_SCHOOL_MASK_NORMAL) const
bool CanBlockInCombat (const Unit *attacker, SpellSchoolMask weaponSchoolMask=SPELL_SCHOOL_MASK_NORMAL) const
bool CanCrushInCombat () const
bool CanCrushInCombat (const Unit *victim) const
bool CanGlanceInCombat () const
bool CanGlanceInCombat (const Unit *victim) const
bool CanDazeInCombat () const
bool CanDazeInCombat (const Unit *victim) const
bool CanReactOnAbility (const SpellEntry *ability) const
bool CanDodgeAbility (const Unit *attacker, const SpellEntry *ability) const
bool CanParryAbility (const Unit *attacker, const SpellEntry *ability) const
bool CanBlockAbility (const Unit *attacker, const SpellEntry *ability, bool miss=false) const
bool CanDeflectAbility (const Unit *attacker, const SpellEntry *ability) const
float CalculateEffectiveDodgeChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveParryChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveBlockChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveCrushChance (const Unit *victim, WeaponAttackType attType) const
float CalculateEffectiveGlanceChance (const Unit *victim, WeaponAttackType attType) const
float CalculateEffectiveDazeChance (const Unit *victim, WeaponAttackType attType) const
uint32 CalculateGlanceAmount (CalcDamageInfo *meleeInfo) const
float CalculateAbilityDeflectChance (const Unit *attacker, const SpellEntry *ability) const
bool RollAbilityPartialBlockOutcome (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability) const
float GetDodgeChance () const
float GetParryChance () const
float GetBlockChance () const
float GetReflectChance (SpellSchoolMask schoolMask) const
virtual bool CanCrit (WeaponAttackType attType) const
virtual bool CanCrit (SpellSchoolMask schoolMask) const
virtual bool CanCrit (const SpellEntry *entry, SpellSchoolMask schoolMask, WeaponAttackType attType) const
virtual float GetCritChance (WeaponAttackType attType) const
virtual float GetCritChance (SpellSchoolMask schoolMask) const
virtual float GetCritChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
virtual float GetCritTakenChance (Unit const *attacker, SpellSchoolMask dmgSchoolMask, SpellDmgClass dmgClass, SpellEntry const *spellInfo=nullptr, bool heal=false) const
virtual float GetCritMultiplier (SpellSchoolMask dmgSchoolMask, uint32 creatureTypeMask, const SpellEntry *spell=nullptr, bool heal=false) const
virtual float GetCritTakenMultiplier (SpellSchoolMask dmgSchoolMask, SpellDmgClass dmgClass, float ignorePct=0.0f, bool heal=false) const
uint32 CalculateCritAmount (const Unit *victim, uint32 amount, const SpellEntry *entry, bool heal=false) const
uint32 CalculateCritAmount (CalcDamageInfo *meleeInfo) const
virtual float GetHitChance (WeaponAttackType attackType) const
virtual float GetHitChance (SpellSchoolMask schoolMask) const
virtual float GetHitChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
virtual float GetMissChance (WeaponAttackType attackType) const
virtual float GetMissChance (SpellSchoolMask schoolMask) const
virtual float GetMissChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
float CalculateEffectiveCritChance (const Unit *victim, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveMissChance (const Unit *victim, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateSpellCritChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
float CalculateSpellMissChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
void SetAlwaysHit (bool value)
float GetExpertisePercent (WeaponAttackType attType) const
virtual int32 GetResistancePenetration (SpellSchools school) const
float CalculateEffectiveMagicResistancePercent (const Unit *attacker, SpellSchoolMask schoolMask, bool binary=false) const
float CalculateSpellResistChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
bool IsBlockCritical () const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *pVictim, WeaponAttackType attType, SpellSchoolMask schoolMask) const
bool isVendor () const
bool isTrainer () const
bool isQuestGiver () const
bool isGossip () const
bool isTaxi () const
bool isGuildMaster () const
bool isBattleMaster () const
bool isBanker () const
bool isInnkeeper () const
bool isSpiritHealer () const
bool isSpiritGuide () const
bool isTabardDesigner () const
bool isAuctioner () const
bool isArmorer () const
bool isServiceProvider () const
bool isSpiritService () const
bool IsTaxiFlying () const
bool IsInCombat () const
void SetInCombatState (bool PvP, Unit *enemy=nullptr)
void SetInCombatWith (Unit *enemy)
void SetInCombatWithAggressor (Unit *aggressor, bool touchOnly=false)
void SetOutOfCombatWithAggressor (Unit *aggressor)
void SetInCombatWithAssisted (Unit *assisted, bool touchOnly=false)
void SetOutOfCombatWithAssisted (Unit *assisted)
void SetInCombatWithVictim (Unit *victim, bool touchOnly=false)
void SetOutOfCombatWithVictim (Unit *victim)
void EngageInCombatWith (Unit *enemy)
void EngageInCombatWithAggressor (Unit *aggressor)
void ClearInCombat ()
void HandleExitCombat (bool pvpCombat=false)
SpellAuraHolderBounds GetSpellAuraHolderBounds (uint32 spell_id)
SpellAuraHolderConstBounds GetSpellAuraHolderBounds (uint32 spell_id) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAuraType (AuraType auraType) const
bool HasAffectedAura (AuraType auraType, SpellEntry const *spellProto) const
bool HasAura (uint32 spellId, SpellEffectIndex effIndex) const
bool HasAura (uint32 spellId) const
bool HasAuraOfDifficulty (uint32 spellId) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasMechanicMaskOrDispelMaskAura (uint32 dispelMask, uint32 mechanicMask, Unit const *caster) const
bool HasNegativeAuraWithInterruptFlag (SpellAuraInterruptFlags flag) const
template<typename Func >
bool HasAuraHolder (Func func) const
template<typename Func >
bool HasAura (Func func, AuraType type) const
bool HasAuraTypeWithMiscvalue (AuraType auraType, int32 miscvalue) const
bool HasStealthAura () const
bool HasInvisibilityAura () const
bool isFeared () const
bool isInRoots () const
bool IsPolymorphed () const
bool isFrozen () const
bool IsIgnoreUnitState (SpellEntry const *spell, IgnoreUnitState ignoreState) const
virtual bool IsInWater () const
bool IsInSwimmableWater () const
virtual bool IsUnderwater () const
bool IsAboveGround (float diff=0.5f) const
bool isInAccessablePlaceFor (Unit const *unit) const
void EnergizeBySpell (Unit *victim, SpellEntry const *spellInfo, uint32 damage, Powers powerType, bool sendLog=true)
uint32 SpellNonMeleeDamageLog (Unit *pVictim, uint32 spellID, uint32 damage)
SpellCastResult CastSpell (Unit *Victim, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastTargets &targets, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (SpellCastTargets &targets, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
void DeMorph ()
void SendAIReaction (AiReaction reactionType)
void SendAttackStateUpdate (CalcDamageInfo *calcDamageInfo) const
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, int32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendEnergizeSpellLog (Unit *pVictim, uint32 SpellID, uint32 Damage, Powers powertype) const
void SendEnvironmentalDamageLog (uint8 type, uint32 damage, uint32 absorb, int32 resist) const
void SendHealSpellLog (Unit *pVictim, uint32 SpellID, uint32 Damage, uint32 OverHeal, bool critical=false, uint32 absorb=0) const
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo) const
void SendSpellDamageResist (Unit *target, uint32 spellId) const
void SendEnchantmentLog (ObjectGuid targetGuid, uint32 itemEntry, uint32 enchantId) const
bool CanInitiateAttack () const
Unit * SelectAttackingTarget (AttackingTarget target, uint32 position, uint32 spellId, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
Unit * SelectAttackingTarget (AttackingTarget target, uint32 position, SpellEntry const *spellInfo=nullptr, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
void SelectAttackingTargets (std::vector< Unit * > &selectedTargets, AttackingTarget target, uint32 position, uint32 spellId, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
void SelectAttackingTargets (std::vector< Unit * > &selectedTargets, AttackingTarget target, uint32 position, SpellEntry const *spellInfo=nullptr, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
bool IsUnitConditionSatisfied (int32 unitConditionId, Unit const *otherUnit) const
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool transportLeave=false)
void MonsterMoveWithSpeed (float x, float y, float z, float speed, bool generatePath=false, bool forceDestination=false)
void SendTeleportPacket (float x, float y, float z, float ori, GenericTransport *transport)
void SendHeartBeat ()
void SendMoveRoot (bool state, bool broadcastOnly=false)
bool IsMoving () const
bool IsMovingIgnoreFlying () const
bool IsMovingForward () const
bool IsLevitating () const
bool IsWalking () const
bool IsRooted () const
bool IsFalling () const
bool IsDebuggingMovement () const
void SetDebuggingMovement (bool state)
void SetLevitate (bool enabled)
void SetSwim (bool enabled)
void SetCanFly (bool enabled)
void SetFeatherFall (bool enabled)
void SetHover (bool enabled)
void SetWaterWalk (bool enabled)
void SetInFront (Unit const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *pObject)
void SendHighestThreatUpdate (HostileReference *pHostilReference)
void SendThreatClear () const
void SendThreatRemove (HostileReference *pHostileReference) const
void SendThreatUpdate ()
bool IsAlive () const
bool IsDead () const
DeathState GetDeathState () const
bool IsTargetUnderControl (Unit const &target) const
bool HasCharm (ObjectGuid const &exactGuid=ObjectGuid()) const
bool HasCharmer (ObjectGuid const &exactGuid) const
bool HasCharmer () const
bool HasMaster () const
bool HasTarget (ObjectGuid const &exactGuid=ObjectGuid()) const
bool HasChannelObject (ObjectGuid const &exactGuid=ObjectGuid()) const
Unit * GetCharm (WorldObject const *pov=nullptr) const
Unit * GetCharmer (WorldObject const *pov=nullptr) const
Unit * GetCreator (WorldObject const *pov=nullptr) const
Unit * GetTarget (WorldObject const *pov=nullptr) const
WorldObject * GetChannelObject (WorldObject const *pov=nullptr) const
void SetCharm (Unit *charmed)
void SetCharmer (Unit *charmer)
void SetTarget (WorldObject *target)
void SetChannelObject (WorldObject *object)
ObjectGuid const & GetOwnerGuid () const override
void SetOwnerGuid (ObjectGuid owner) override
ObjectGuid const & GetPetGuid () const
void SetPetGuid (ObjectGuid pet)
virtual ObjectGuid const & GetSelectionGuid () const
virtual void SetSelectionGuid (ObjectGuid guid)
ObjectGuid const & GetMasterGuid () const
Unit * GetOwner (WorldObject const *pov=nullptr, bool recursive=false) const
Unit * GetMaster (WorldObject const *pov=nullptr) const
Unit * GetSpawner (WorldObject const *pov=nullptr) const
Unit * GetBeneficiary () const
Player * GetBeneficiaryPlayer () const
bool IsClientControlled (Player const *exactClient=nullptr) const
Player const * GetClientControlling () const
Pet * GetPet () const
void SetPet (Unit *pet)
Pet * GetMiniPet () const
void SetMiniPet (Unit *pet)
void RemoveMiniPet ()
void AddGuardian (Pet *pet)
void RemoveGuardian (Pet *pet)
void RemoveGuardians (bool force=true)
Pet * FindGuardianWithEntry (uint32 entry)
uint32 CountGuardiansWithEntry (uint32 entry)
Pet * GetProtectorPet ()
bool HasAnyPet () const
CharmInfo * GetCharmInfo () const
virtual CharmInfo * InitCharmInfo (Unit *charm)
virtual void DeleteCharmInfo ()
ObjectGuid const & GetTotemGuid (TotemSlot slot) const
Totem * GetTotem (TotemSlot slot) const
bool IsAllTotemSlotsUsed () const
void _AddTotem (TotemSlot slot, Totem *totem)
void _RemoveTotem (Totem *totem)
template<typename Func >
void CallForAllControlledUnits (Func const &func, uint32 controlledMask)
template<typename Func >
bool CheckAllControlledUnits (Func const &func, uint32 controlledMask) const
bool AddSpellAuraHolder (SpellAuraHolder *holder)
void AddAuraToModList (Aura *aura)
void RemoveAura (Aura *Aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSpellAuraHolder (SpellAuraHolder *holder, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSingleAuraFromSpellAuraHolder (SpellAuraHolder *holder, SpellEffectIndex index, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSingleAuraFromSpellAuraHolder (uint32 spellId, SpellEffectIndex effindex, ObjectGuid casterGuid, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpell (uint32 spellId, SpellAuraHolder *except=nullptr, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToItemSpell (Item *castItem, uint32 spellId)
void RemoveAurasByCasterSpell (uint32 spellId, ObjectGuid casterGuid, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellBySteal (SpellAuraHolder *holder, Unit *stealer)
void RemoveAurasDueToSpellByCancel (uint32 spellId)
void RemoveAurasTriggeredBySpell (uint32 spellId, ObjectGuid casterGuid=ObjectGuid())
void RemoveAuraStack (uint32 spellId, int32 modifier=-1)
void RemoveAuraCharge (uint32 spellId)
void RemoveNotOwnTrackedTargetAuras (uint32 newPhase=0x0)
void RemoveAurasAtMechanicImmunity (uint32 mechMask, uint32 exceptSpellId, bool non_positive=false)
void RemoveSpellsCausingAura (AuraType auraType)
void RemoveSpellsCausingAura (AuraType auraType, SpellAuraHolder *except)
void RemoveSpellsCausingAura (AuraType auraType, SpellAuraHolder *except, bool onlyMechanic)
void RemoveSpellsCausingAura (AuraType auraType, ObjectGuid casterGuid)
void RemoveRankAurasDueToSpell (uint32 spellId)
bool RemoveNoStackAurasDueToAuraHolder (SpellAuraHolder *holder)
void RemoveAurasWithInterruptFlags (uint32 flags)
void RemoveAurasWithInterruptFlags (uint32 flags, SpellAuraHolder *except)
void RemoveAurasWithDispelType (DispelType type, ObjectGuid casterGuid=ObjectGuid())
void RemoveAllAuras (AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveArenaAuras (bool onleave=false)
void RemoveAllAurasOnDeath ()
void RemoveAllAurasOnEvade ()
void RemoveAllGroupBuffsFromCaster (ObjectGuid casterGuid)
template<class T >
void RemoveAurasWithAttribute (T flags)
void RemoveAurasOnCast (uint32 flag, SpellEntry const *castedSpellEntry)
void RemoveAuraHolderFromStack (uint32 spellId, uint32 stackAmount=1, ObjectGuid casterGuid=ObjectGuid(), AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraHolderDueToSpellByDispel (uint32 spellId, uint32 dispellingSpellId, uint32 stackAmount, ObjectGuid casterGuid, Unit *dispeller)
void DelaySpellAuraHolder (uint32 spellId, int32 delaytime, ObjectGuid casterGuid)
float GetResistanceBuffMods (SpellSchools school, bool positive) const
void SetResistanceBuffMods (SpellSchools school, bool positive, float val)
void ApplyResistanceBuffModsMod (SpellSchools school, bool positive, float val, bool apply)
void ApplyResistanceBuffModsPercentMod (SpellSchools school, bool positive, float val, bool apply)
void InitStatBuffMods ()
void ApplyStatBuffMod (Stats stat, float val, bool apply)
void ApplyStatPercentBuffMod (Stats stat, float val, bool apply)
void SetCreateStat (Stats stat, float val)
void SetCreateHealth (uint32 val)
uint32 GetCreateHealth () const
void SetCreateMana (uint32 val)
uint32 GetCreateMana () const
uint32 GetCreatePowers (Powers power) const
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
float GetCreateStat (Stats stat) const
void SetCreateResistance (SpellSchools school, int32 val)
int32 GetCreateResistance (SpellSchools school) const
void SetCurrentCastedSpell (Spell *pSpell)
virtual void ProhibitSpellSchool (SpellSchoolMask, uint32)
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool sendAutoRepeatCancelToClient=true)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
bool IsNonMeleeSpellCasted (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool forMovement=false, bool forAutoIgnore=false, bool forEquip=false) const
bool IsDelayCombatTimerSpellCasted () const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spell_id=0)
void InterruptSpellsWithChannelFlags (uint32 flags)
void InterruptSpellsAndAurasWithInterruptFlags (uint32 flags)
bool IsInterruptible () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsShapeShifted () const
bool IsNoWeaponShapeShift () const
bool IsInDisallowedMountForm () const
bool HandleStatModifier (UnitMods unitMod, UnitModifierType modifierType, float amount, bool apply)
void SetModifierValue (UnitMods unitMod, UnitModifierType modifierType, float value)
float GetModifierValue (UnitMods unitMod, UnitModifierType modifierType) const
float GetTotalStatValue (Stats stat) const
float GetTotalResistanceValue (SpellSchools school) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
Stats GetStatByAuraGroup (UnitMods unitMod) const
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
bool CanModifyStats () const
void SetCanModifyStats (bool modifyStats)
float GetTotalAttackPowerValue (WeaponAttackType attType) const
float GetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, uint8 index=0) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value, uint8 index=0)
SpellSchools GetWeaponDamageSchool (WeaponAttackType attType, uint8 index=0) const
void SetWeaponDamageSchool (WeaponAttackType attType, SpellSchools school, uint8 index=0)
SpellSchoolMask GetAttackDamageSchoolMask (WeaponAttackType attType, bool first=false) const
void SetAttackDamageSchool (WeaponAttackType attType, SpellSchools school)
SpellSchoolMask GetRangedDamageSchoolMask (bool first=false) const
void SetRangedDamageSchool (SpellSchools school)
SpellSchoolMask GetMeleeDamageSchoolMask (bool main, bool first=false) const
SpellSchoolMask GetMeleeDamageSchoolMask () const
void SetMeleeDamageSchool (bool main, SpellSchools school)
void SetMeleeDamageSchool (SpellSchools school)
SpellSchoolMask GetMainAttackSchoolMask ()
UnitVisibility GetVisibility () const
void SetVisibility (UnitVisibility x)
void SetVisibilityWithoutUpdate (UnitVisibility x)
void UpdateVisibilityAndView () override
bool IsVisibleForOrDetect (Unit const *u, WorldObject const *viewPoint, bool detect, bool inVisibleList=false, bool is3dDistance=true, bool spell=false, bool ignorePhase=false) const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const override
bool isInvisibleForAlive () const
returns true if creature can't be seen by alive units
TrackedAuraTargetMap & GetTrackedAuraTargets (TrackedAuraType type)
TrackedAuraTargetMap const & GetTrackedAuraTargets (TrackedAuraType type) const
bool IsAOEImmune () const
void SetAOEImmune (bool state)
bool IsChainImmune () const
void SetChainImmune (bool state)
bool CanHaveThreatList (bool ignoreAliveState=false) const
void AddThreat (Unit *pVictim, float threat=0.0f, bool crit=false, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NONE, SpellEntry const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float threat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void DeleteThreatList ()
bool SelectHostileTarget ()
bool IsSuppressedTarget (Unit *target) const
bool IsOfflineTarget (Unit *victim) const
void TauntUpdate ()
void FixateTarget (Unit *taunter)
ThreatManager & getThreatManager ()
ThreatManager const & getThreatManager () const
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefManager & getHostileRefManager ()
HostileRefManager const & getHostileRefManager () const
void SetNoThreatState (bool state)
bool GetNoThreatState ()
CombatManager & GetCombatManager ()
CombatManager const & GetCombatManager () const
void TriggerEvadeEvents ()
void TriggerHomeEvents ()
void EvadeTimerExpired ()
uint32 GetVisibleAura (uint8 slot) const
void SetVisibleAura (uint8 slot, uint32 spellid)
VisibleAuraMap const & GetVisibleAuras () const
uint8 GetVisibleAurasCount () const
Aura * GetAura (uint32 spellId, SpellEffectIndex effindex)
Aura * GetAura (AuraType type, SpellFamily family, uint64 familyFlag, uint32 familyFlag2=0, ObjectGuid casterGuid=ObjectGuid()) const
Aura * GetTriggeredByClientAura (uint32 spellId) const
SpellAuraHolder * GetSpellAuraHolder (uint32 spellid) const
SpellAuraHolder * GetSpellAuraHolder (uint32 spellid, ObjectGuid casterGuid) const
SpellAuraHolderMap & GetSpellAuraHolderMap ()
SpellAuraHolderMap const & GetSpellAuraHolderMap () const
AuraList const & GetAurasByType (AuraType type) const
void ApplyAuraProcTriggerDamage (Aura *aura, bool apply)
int32 GetTotalAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype, std::function< bool(Aura const *)> predicate) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype) const
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValueForMask (AuraType auratype, uint32 mask) const
Aura * GetDummyAura (uint32 spell_id) const
uint32 GetDisplayId () const
void SetDisplayId (uint32 modelId)
uint32 GetNativeDisplayId () const
void SetNativeDisplayId (uint32 modelId)
void RestoreDisplayId ()
void UpdateModelData ()
void SendCollisionHeightUpdate (float height)
DynamicObject * GetDynObject (uint32 spellId, SpellEffectIndex effIndex, Unit *target=nullptr)
DynamicObject * GetDynObject (uint32 spellId)
void AddDynObject (DynamicObject *dynObj)
void RemoveDynObject (uint32 spellid)
void RemoveDynObjectWithGUID (ObjectGuid guid)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void AddWildGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del, bool removeAura=true)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
void AddCreature (uint32 spellId, Creature *creature)
void RemoveCreature (uint32 spellId, bool del)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, uint8 index=0)
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
void ModifyAuraState (AuraState flag, bool apply)
bool HasAuraState (AuraState flag) const
bool HasAuraStateForCaster (AuraState flag, ObjectGuid casterGuid) const
void UnsummonAllTotems () const
Unit * SelectMagnetTarget (Unit *victim, Spell *spell=nullptr)
int32 SpellBonusWithCoeffs (SpellEntry const *spellProto, int32 total, int32 benefit, int32 ap_benefit, DamageEffectType damagetype, bool donePart, float defCoeffMod=1.0f)
Calculate spell coefficents and level penalties for spell/melee damage or heal.
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask) const
uint32 SpellDamageBonusDone (Unit *victim, SpellSchoolMask schoolMask, SpellEntry const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
Calculates caster part of spell damage bonuses, also includes different bonuses dependent from target auras.
uint32 SpellDamageBonusTaken (Unit *caster, SpellSchoolMask schoolMask, SpellEntry const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
Calculates target part of spell damage bonuses, will be called on each tick for periodic damage over time auras.
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseHealingBonusTaken (SpellSchoolMask schoolMask) const
uint32 SpellHealingBonusDone (Unit *victim, SpellEntry const *spellProto, int32 healamount, DamageEffectType damagetype, uint32 stack=1)
Calculates caster part of healing spell bonuses, also includes different bonuses dependent from target auras.
uint32 SpellHealingBonusTaken (Unit *caster, SpellEntry const *spellProto, int32 healamount, DamageEffectType damagetype, uint32 stack=1)
Calculates target part of healing spell bonuses, will be called on each tick for periodic damage over time auras.
uint32 MeleeDamageBonusDone (Unit *victim, uint32 damage, WeaponAttackType attType, SpellSchoolMask schoolMask, SpellEntry const *spellProto=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, uint32 stack=1, bool flat=true)
Calculates caster part of melee damage bonuses, also includes different bonuses dependent from target auras.
uint32 MeleeDamageBonusTaken (Unit *caster, uint32 pdamage, WeaponAttackType attType, SpellSchoolMask schoolMask, SpellEntry const *spellProto=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, uint32 stack=1, bool flat=true)
Calculates target part of melee damage bonuses, will be called on each tick for periodic damage over time auras.
SpellProcEventTriggerCheck IsTriggeredAtSpellProcEvent (ProcExecutionData &data, SpellAuraHolder *holder, SpellProcEventEntry const *&spellProcEvent)
SpellAuraProcResult TriggerProccedSpell (Unit *target, std::array< int32, MAX_EFFECT_INDEX > &basepoints, uint32 triggeredSpellId, Item *castItem, Aura *triggeredByAura, uint32 cooldown, ObjectGuid originalCaster)
SpellAuraProcResult TriggerProccedSpell (Unit *target, std::array< int32, MAX_EFFECT_INDEX > &basepoints, SpellEntry const *spellInfo, Item *castItem, Aura *triggeredByAura, uint32 cooldown, ObjectGuid originalCaster)
SpellAuraProcResult HandleDummyAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleHasteAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleSpellCritChanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleProcTriggerSpellAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleProcTriggerDamageAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleOverrideClassScriptAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRaidProcFromChargeAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRaidProcFromChargeWithValueAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModCastingSpeedNotStackAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleReflectSpellsSchoolAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModPowerCostSchoolAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleMagnetAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleMechanicImmuneResistanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModDamageFromCasterAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleAddFlatModifierAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleAddPctModifierAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModDamagePercentDoneAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModRating (ProcExecutionData &data)
SpellAuraProcResult HandleSpellMagnetAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleManaShieldAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModResistanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRemoveByDamageChanceProc (ProcExecutionData &data)
SpellAuraProcResult HandleInvisibilityAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandlePeriodicAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleNULLProc (ProcExecutionData &)
SpellAuraProcResult HandleCantTrigger (ProcExecutionData &)
void SetLastManaUse ()
bool IsUnderLastManaUseEffect () const
uint32 GetRegenTimer () const
void SetContestedPvP (Player *attackedPlayer=nullptr)
void ApplySpellImmune (Aura const *aura, uint32 op, uint32 type, bool apply)
void ApplySpellDispelImmunity (Aura const *aura, DispelType type, bool apply)
bool IsImmuneToSchool (SpellEntry const *spellInfo, uint8 effectMask) const
uint32 GetSchoolImmunityMask () const
uint32 GetDamageImmunityMask () const
uint32 GetMechanicImmunityMask () const
void CalculateDamageAbsorbAndResist (Unit *caster, SpellSchoolMask schoolMask, DamageEffectType damagetype, const uint32 damage, uint32 *absorb, int32 *resist, bool canReflect=false, bool canResist=true, bool binary=false)
void CalculateAbsorbResistBlock (Unit *caster, SpellNonMeleeDamage *spellDamageInfo, SpellEntry const *spellProto, WeaponAttackType attType=BASE_ATTACK)
void CalculateHealAbsorb (uint32 heal, uint32 *absorb)
void UpdateSpeed (UnitMoveType mtype, bool forced, float ratio=1.0f)
float GetSpeedInMotion () const
float GetSpeed (UnitMoveType mtype) const
float GetXYFlagBasedSpeed () const
float GetXYFlagBasedSpeed (uint32 moveFlags) const
float GetSpeedRateInMotion () const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeedRate (UnitMoveType mtype, float rate, bool forced=false)
void KnockBackFrom (Unit *target, float horizontalSpeed, float verticalSpeed)
void KnockBackWithAngle (float angle, float horizontalSpeed, float verticalSpeed)
bool HasHoverAura () const
template<typename Func >
bool HasAuraWithCondition (Func const &func) const
void _RemoveAllAuraMods ()
void _ApplyAllAuraMods ()
uint32 CalcNotIgnoreAbsorbDamage (uint32 damage, SpellSchoolMask damageSchoolMask, SpellEntry const *spellInfo=nullptr) const
uint32 CalcNotIgnoreDamageReduction (uint32 damage, SpellSchoolMask damageSchoolMask) const
int32 CalculateAuraDuration (SpellEntry const *spellProto, uint32 effectMask, int32 duration, Unit const *caster)
float CalculateLevelPenalty (SpellEntry const *spellProto) const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
MotionMaster * GetMotionMaster ()
MotionMaster const * GetMotionMaster () const
bool IsStopped () const
void StopMoving (bool forceSendStop=false)
-------—End of Pet responses methods-------—
void InterruptMoving (bool forceSendStop=false)
bool IsCrowdControlled () const
-------—Various crowd control methods--------------—
bool IsConfused () const
bool SetConfused (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0)
bool IsFleeing () const
bool SetFleeing (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, uint32 duration=0)
bool IsStunned () const
bool SetStunned (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, bool logout=false)
bool IsStunnedByLogout () const
bool SetStunnedByLogout (bool apply)
bool IsInPanic () const
bool SetInPanic (uint32 duration)
bool IsImmobilizedState () const
void SetImmobilizedState (bool apply, bool stun=false, bool logout=false)
bool IsFeigningDeath () const
-------—End of crowd control methods-------—
bool IsFeigningDeathSuccessfully () const
void SetFeignDeath (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, bool dynamic=true, bool success=true)
void InterruptSpellsCastedOnMe (bool killDelayed=false)
void AddComboPointHolder (uint32 lowguid)
void RemoveComboPointHolder (uint32 lowguid)
void ClearComboPointHolders ()
void SendPetActionFeedback (uint8 msg) const
-------—Pet responses methods--------------—
void SendPetTalk (uint32 pettalk) const
void SendPetAIReaction () const
void SendPetDismiss (uint32 soundId) const
void propagateSpeedChange ()
-------—End of Pet responses methods-------—
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
void UpdateAuraForGroup (uint8 slot)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void ScheduleAINotify (uint32 delay, bool forced=false)
bool IsAINotifyScheduled () const
void FinalizeAINotifyEvent ()
void AbortAINotifyEvent ()
void OnRelocated ()
bool IsLinkingEventTrigger () const
void TriggerAggroLinkingEvent (Unit *enemy)
bool TakePossessOf (Unit *possessed)
Unit * TakePossessOf (SpellEntry const *spellEntry, SummonPropertiesEntry const *summonProp, uint32 effIdx, float x, float y, float z, float ang)
bool TakeCharmOf (Unit *charmed, uint32 spellId=0, bool advertised=true)
void BreakCharmOutgoing (Unit *charmed)
void BreakCharmOutgoing (bool advertisedOnly=false)
void BreakCharmIncoming ()
void Uncharm (Unit *charmed, uint32 spellId=0)
void RemoveUnattackableTargets (Unit *charmer=nullptr)
bool CanEnterCombat () const
void SetCanEnterCombat (bool can)
void SetIgnoreRangedTargets (bool state)
bool IsIgnoringRangedTargets ()
void SetSupportThreatOnly (bool state)
bool IsSupportThreatOnly ()
void DisableThreatPropagationToOwner ()
bool IsPropagatingThreatToOwner ()
float GetAttackDistance (Unit const *target) const
virtual CombatData const * GetCombatData () const
float GetBaseRunSpeed ()
bool IsSpellProccingHappening () const
void AddDelayedHolderDueToProc (SpellAuraHolder *holder)
void ResetAutoRepeatSpells ()
const uint64 & GetAuraUpdateMask () const
void SetAuraUpdateMask (uint8 slot)
void ResetAuraUpdateMask ()
void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const override
void AdjustZForCollision (float x, float y, float &z, float halfHeight) const override
virtual uint32 GetSpellRank (SpellEntry const *spellInfo)
Player * GetNextRandomRaidMember (float radius, AuraType noAuraType)
bool HasOverrideScript (uint32 id) const
Aura * GetOverrideScript (uint32 id) const
void RegisterOverrideScriptAura (Aura *aura, uint32 id, bool apply)
void RegisterScriptedLocationAura (Aura *aura, AuraScriptLocation location, bool apply)
std::vector< Aura * > & GetScriptedLocationAuras (AuraScriptLocation location)
uint8 GetComboPoints () const
ObjectGuid const & GetComboTargetGuid () const
void AddComboPoints (Unit *target, int8 count)
void ClearComboPoints ()
void RegisterScalingAura (Aura *aura, bool apply)
void UpdateScalingAuras ()
uint32 GetDamageDoneByOthers ()
uint32 GetModifierXpBasedOnDamageReceived (uint32 xp)
void OverrideMountDisplayId (uint32 newDisplayId)
void UpdateSplinePosition (bool relocateOnly=false)
void SendFlightSplineSyncIfNeeded ()
void CharmCooldownInitialize (WorldPacket &data) const
FormationSlotDataSPtr GetFormationSlot ()
void SetFormationSlot (FormationSlotDataSPtr fSlot)
void AddSummonForOnDeathDespawn (ObjectGuid guid)
void DespawnSummonsOnDeath ()
virtual bool IsNoMountedFollow () const
Public Member Functions inherited from WorldObject
virtual ~WorldObject ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
virtual ObjectGuid const GetSpawnerGuid () const
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
bool IsControlledByPlayer () const
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
void SetNotifyOnEventState (bool state)
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
void PrintCooldownList (ChatHandler &chat) const
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Static Public Member Functions
static float _GetHealthMod (int32 Rank)
Get custom factor to scale health (default 1, CONFIG_FLOAT_RATE_CREATURE_*_HP)
static float _GetDamageMod (int32 Rank)
Get custom factor to scale damage (default 1, CONFIG_FLOAT_RATE_*_DAMAGE)
static float _GetSpellDamageMod (int32 Rank)
Get custom factor to scale spell damage (default 1, CONFIG_FLOAT_RATE_*_SPELLDAMAGE)
static uint32 ChooseDisplayId (const CreatureInfo *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
static void DeleteFromDB (uint32 lowguid, CreatureData const *data)
static void AddToRemoveListInMaps (uint32 db_guid, CreatureData const *data)
static void SpawnInMaps (uint32 db_guid, CreatureData const *data)
Static Public Member Functions inherited from Unit
static void DealDamageMods (Unit *dealer, Unit *victim, uint32 &damage, uint32 *absorb, DamageEffectType damagetype, SpellEntry const *spellProto=nullptr)
static uint32 DealDamage (Unit *dealer, Unit *victim, uint32 damage, CleanDamage const *cleanDamage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask, SpellEntry const *spellProto, bool durabilityLoss, Spell *spell=nullptr)
static void Kill (Unit *killer, Unit *victim, DamageEffectType damagetype, SpellEntry const *spellProto, bool durabilityLoss, bool duel_hasEnded)
static void HandleDamageDealt (Unit *dealer, Unit *victim, uint32 &damage, CleanDamage const *cleanDamage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask, SpellEntry const *spellProto, bool duel_hasEnded)
static void ProcDamageAndSpell (ProcSystemArguments &&data)
static bool IsAllowedDamageInArea (Unit *attacker, Unit *victim)
static void DealSpellDamage (Unit *affectiveCaster, SpellNonMeleeDamage *spellDamageInfo, bool durabilityLoss, bool resetLeash)
static SpellMissInfo SpellHitResult (WorldObject *caster, Unit *victim, SpellEntry const *spell, uint8 effectMask, bool reflectable=false, bool reflected=false, uint32 *heartbeatResistChance=nullptr)
static bool RollSpellCritOutcome (Unit *caster, const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell)
static float RollMagicResistanceMultiplierOutcomeAgainst (const Unit *attacker, const Unit *victim, SpellSchoolMask schoolMask, DamageEffectType dmgType, bool binary=false)
static void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
static void SendSpellNonMeleeDamageLog (WorldObject *attacker, Unit *target, uint32 spellID, uint32 damage, SpellSchoolMask damageSchoolMask, uint32 absorbedDamage, int32 resist, bool isPeriodic, uint32 blocked, bool criticalHit=false, bool split=false)
static void SendSpellMiss (WorldObject *caster, Unit *target, uint32 spellID, SpellMissInfo missInfo)
static void SendSpellOrDamageImmune (ObjectGuid casterGuid, Unit *target, uint32 spellId)
static void CasterHitTargetWithSpell (Unit *realCaster, Unit *target, SpellEntry const *spellInfo, bool triggered, bool success=true)
static float CalcArmorReducedDamage (WorldObject *attacker, Unit *victim, const float damage)
Static Public Member Functions inherited from WorldObject
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Protected Member Functions
bool CreateFromProto (uint32 dbGuid, uint32 guidlow, CreatureInfo const *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
bool InitEntry (uint32 Entry, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
change the entry of creature until respawn
uint32 GetCreatureConditionalSpawnEntry (uint32 guidlow, Map *map) const
void UnsummonCleanup ()
bool IsCorpseExpired () const
void RegeneratePower (float timerMultiplier)
virtual void RegenerateHealth ()
Protected Member Functions inherited from Unit
bool MeetsSelectAttackingRequirement (Unit *target, SpellEntry const *spellInfo, uint32 selectFlags, SelectAttackingTargetParams params, int32 unitConditionId) const
Unit ()
void _UpdateSpells (uint32 time)
void _UpdateAutoRepeatSpell ()
void DisableSpline ()
ObjectGuid const & GetCharmGuid () const
void SetCharmGuid (ObjectGuid const &charm)
ObjectGuid const & GetSummonGuid () const
void SetSummonGuid (ObjectGuid const &summon)
ObjectGuid const & GetCharmerGuid () const
void SetCharmerGuid (ObjectGuid const &owner)
ObjectGuid const & GetSummonerGuid () const
void SetSummonerGuid (ObjectGuid const &owner)
ObjectGuid const & GetCreatorGuid () const
void SetCreatorGuid (ObjectGuid const &creator)
ObjectGuid const & GetTargetGuid () const
void SetTargetGuid (ObjectGuid const &targetGuid)
ObjectGuid const & GetChannelObjectGuid () const
void SetChannelObjectGuid (ObjectGuid const &targetGuid)
ObjectGuid const & GetCritterGuid () const
void SetCritterGuid (ObjectGuid critterGuid)
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes
VendorItemCounts m_vendorItemCounts
uint32 m_gossipMenuId
uint32 m_lootMoney
ObjectGuid m_lootRecipientGuid
uint32 m_lootGroupRecipientId
CreatureLootStatus m_lootStatus
uint32 m_corpseAccelerationDecayDelay
TimePoint m_corpseExpirationTime
Timers.
time_t m_respawnTime
uint32 m_respawnDelay
bool m_respawnOverriden
bool m_respawnOverrideOnce
uint32 m_corpseDelay
TimePoint m_pickpocketRestockTime
bool m_canAggro
bool m_checkForHelp
float m_respawnradius
uint32 m_interactionPauseTimer
CreatureSubtype m_subtype
MovementGeneratorType m_defaultMovementType
uint32 m_equipmentId
uint32 m_detectionRange
bool m_AlreadyCallAssistance
bool m_canCallForAssistance
uint32 m_temporaryFactionFlags
uint32 m_originalEntry
Position m_combatStartPos
Position m_respawnPos
uint32 m_gameEventVendorId
uint32 m_immunitySet
std::unique_ptr< UnitAI > m_ai
bool m_isInvisible
bool m_ignoreMMAP
bool m_forceAttackingCapability
bool m_noReputation
CreatureSettings m_settings
bool m_countSpawns
ObjectGuid m_onlyVisibleTo
std::set< uint32 > m_hitBySpells
CreatureSpellList m_spellList
CreatureGroup * m_creatureGroup
ObjectGuid m_killer
bool m_imposedCooldown
Protected Attributes inherited from Unit
bool m_AutoRepeatFirstCast
uint32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
int32 m_createResistances [MAX_SPELL_SCHOOL]
Unit * m_attacking
DeathState m_deathState
SpellAuraHolderMap m_spellAuraHolders
SpellAuraHolderMap::iterator m_spellAuraHoldersUpdateIterator
AuraList m_deletedAuras
SpellAuraHolderList m_deletedHolders
std::map< uint32, Aura * > m_classScripts
std::vector< Aura * > m_scriptedLocations [SCRIPT_LOCATION_MAX]
std::vector< Aura * > m_scalingAuras
TrackedAuraTargetMap m_trackedAuraTargets [MAX_TRACKED_AURA_TYPES]
GuidList m_dynObjGUIDs
GameObjectList m_gameObj
WildGameObjectMap m_wildGameObjs
bool m_isSorted
uint32 m_transform
std::map< uint32, Creature * > m_creatures
AuraList m_modAuras [TOTAL_AURAS]
float m_auraModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_END]
WeaponDamageInfo m_weaponDamageInfo
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
MotionMaster i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
uint32 m_regenTimer
uint32 m_lastManaUseTimer
bool m_canDodge
bool m_canParry
bool m_canBlock
bool m_canDualWield = false
VehicleInfo * m_vehicleInfo
bool m_isCreatureLinkingTrigger
bool m_isSpawningLinked
CombatData * m_combatData
CombatManager m_combatManager
float m_baseSpeedWalk
float m_baseSpeedRun
FormationSlotDataSPtr m_formationSlot
Protected Attributes inherited from WorldObject
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Private Attributes
GridReference< Creature > m_gridRef
CreatureInfo const * m_creatureInfo
Additional Inherited Members
Data Fields inherited from Unit
uint32 m_extraAttacks
ObjectGuid m_ObjectSlotGuid [4]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
float m_modSpellCritChance [MAX_SPELL_SCHOOL]
float m_modCritChance [MAX_ATTACK]
float m_modDodgeChance
float m_modDodgeChanceDiminishing
float m_modParryChance
float m_modParryChanceDiminishing
float m_modBlockChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
float m_modAttackBaseDPSPct [MAX_ATTACK] = { 1.0f, 1.0f, 1.0f }
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_AuraFlags
PetAuraSet m_petAuras
Movement::MoveSpline * movespline
Data Fields inherited from WorldObject
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Protected Types inherited from Unit
typedef std::map< uint32, ObjectGuid > WildGameObjectMap
Detailed Description
Definition at line 544 of file Creature.h.
Member Enumeration Documentation
CooldownResult
enum Creature::CooldownResult
Enumerator
COOLDOWN_RESULT_NOT_FOUND
COOLDOWN_RESULT_FOUND
COOLDOWN_RESULT_CATEGORY_FOUND
Definition at line 860 of file Creature.h.
Constructor & Destructor Documentation
Creature()
Creature::Creature (CreatureSubtype subtype = CREATURE_SUBTYPE_GENERIC) explicit
Definition at line 139 of file Creature.cpp.
References Object::m_valuesCount, SetWalk(), and UNIT_END.
~Creature()
Creature::~Creature () virtual
Definition at line 160 of file Creature.cpp.
References CleanupsBeforeDelete().
Member Function Documentation
_GetDamageMod()
float Creature::_GetDamageMod (int32 Rank) static
Get custom factor to scale damage (default 1, CONFIG_FLOAT_RATE_*_DAMAGE)
Definition at line 1490 of file Creature.cpp.
References CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_DAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_DAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_DAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE, CONFIG_FLOAT_RATE_CREATURE_NORMAL_DAMAGE, CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, and sWorld.
Referenced by Pet::InitStatsForLevel(), and SelectLevel().
_GetHealthMod()
float Creature::_GetHealthMod (int32 Rank) static
Get custom factor to scale health (default 1, CONFIG_FLOAT_RATE_CREATURE_*_HP)
Definition at line 1471 of file Creature.cpp.
References CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_HP, CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_HP, CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_HP, CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_HP, CONFIG_FLOAT_RATE_CREATURE_NORMAL_HP, CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, and sWorld.
Referenced by Pet::InitStatsForLevel(), and SelectLevel().
_GetSpellDamageMod()
float Creature::_GetSpellDamageMod (int32 Rank) static
Get custom factor to scale spell damage (default 1, CONFIG_FLOAT_RATE_*_SPELLDAMAGE)
Definition at line 1509 of file Creature.cpp.
References CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_SPELLDAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE, CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE, CONFIG_FLOAT_RATE_CREATURE_NORMAL_SPELLDAMAGE, CREATURE_ELITE_ELITE, CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, and sWorld.
Referenced by Unit::SpellDamageBonusDone().
AddCooldown()
void Creature::AddCooldown (SpellEntry const & spellEntry, ItemPrototype const * itemProto = nullptr, bool permanent = false, uint32 forcedDuration = 0, bool ignoreCat = false) override virtual
Reimplemented from WorldObject.
Definition at line 3054 of file Creature.cpp.
References CooldownContainer::AddCooldown(), SpellEntry::Category, SpellEntry::CategoryRecoveryTime, COOLDOWN_RESULT_CATEGORY_FOUND, COOLDOWN_RESULT_FOUND, COOLDOWN_RESULT_NOT_FOUND, GetCreatureInfo(), WorldObject::GetMap(), Unit::GetMaster(), Object::GetObjectGuid(), GetSpellCooldown(), WorldObject::GetSpellModOwner(), SpellEntry::HasAttribute(), SpellEntry::Id, WorldObject::m_cooldownMap, SpellEntry::RecoveryTime, SMSG_COOLDOWN_EVENT, SMSG_SPELL_COOLDOWN, sObjectMgr, SPELL_ATTR_COOLDOWN_ON_EVENT, and SPELLMOD_COOLDOWN.
Referenced by npc_corrupted_lightning_totemAI::JustRespawned().
AddToRemoveListInMaps()
void Creature::AddToRemoveListInMaps (uint32 db_guid, CreatureData const * data) static
Definition at line 2694 of file Creature.cpp.
References CreatureData::mapid, and sMapMgr.
Referenced by GameEventMgr::GameEventUnspawn(), and ChatHandler::HandleNpcDeleteCommand().
AddToWorld()
void Creature::AddToWorld () override virtual
Register the creature for guid lookup
Reimplemented from WorldObject.
Reimplemented in Pet.
Definition at line 165 of file Creature.cpp.
References Map::AddDbGuidObject(), Map::AddToSpawnCount(), Unit::AddToWorld(), CREATURE_EXTRA_FLAG_ACTIVE, CREATURE_SUBTYPE_PET, CREATURE_SUBTYPE_TEMPORARY_SUMMON, GetCreatureInfo(), Object::GetDbGuid(), Object::GetEntry(), WorldObject::GetMap(), WorldObject::GetMapId(), Object::GetObjectGuid(), Map::GetObjectsStore(), GetSubtype(), Map::GetTempCreatures(), Map::GetTempPets(), TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::insert(), Object::IsInWorld(), m_countSpawns, WorldObject::SetActiveObjectState(), and sWorld.
AI()
virtual UnitAI* Creature::AI () inline override virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 632 of file Creature.h.
References CharmInfo::GetAI(), m_ai, and Unit::m_charmInfo.
Referenced by boss_kelidan_the_breakerAI::AddJustAggroed(), boss_kalecgosAI::Aggro(), mob_fel_orc_convertAI::Aggro(), mob_shadowmoon_soulstealerAI::Aggro(), AreaTrigger_at_commander_dawnforge(), AreaTrigger_at_nats_landing(), AreaTrigger_at_twiggy_flathead(), AttackPlayerWithQuest(), npc_shadow_imageAI::AttackRandomTarget(), CallAssistance(), npc_theramore_spar_controller::CombatantSeparate(), CreatureVisitCreatureWorker(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), Spell::DoAllEffectOnTarget(), npc_threshwackonatorAI::DoAtEnd(), npc_eris_havenfireAI::DoAttackArchersTarget(), CreatureLinkingHolder::DoCreatureLinkingEvent(), boss_kaelthasAI::DoDespawnSummons(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), boss_kelidan_the_breakerAI::DoSetupAdds(), boss_moroesAI::DoSpawnGuests(), npc_Shattered_Hand_Scout::DoStartRunning(), instance_black_temple::DoTeleportAkamaIfCan(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_spell_aura_dummy_npc(), EffectDummyCreature_awaken_kerlonian(), EffectDummyCreature_black_knight_res(), EffectDummyCreature_boss_ionar(), EffectDummyCreature_kael_phase_2(), EffectDummyCreature_lazy_peon_spell(), EffectDummyCreature_npc_bot_trigger(), EffectDummyCreature_npc_chess_generic(), EffectDummyCreature_npc_death_knight_initiate(), EffectDummyCreature_npc_decaying_ghoul(), EffectDummyCreature_npc_dragonmaw_peon(), EffectDummyCreature_npc_fel_guard_hound(), EffectDummyCreature_npc_grand_admiral_westwind(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_putricide(), EffectDummyCreature_npc_redemption_target(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_npc_shay_leafrunner(), EffectDummyCreature_npc_simon_game_bunny(), EffectDummyCreature_npc_snufflenose_gopher(), EffectDummyCreature_npc_taelan_fordring(), EffectDummyCreature_npc_teleportation_portal(), EffectDummyCreature_npc_time_rift_channel(), EffectDummyCreature_npc_vault_warder(), EffectDummyCreature_npc_wants_fruit_credit(), EffectDummyCreature_spell_capture_grark(), EffectDummyCreature_spell_drink_poison(), EffectDummyCreature_spell_dummy_npc(), EffectDummyCreature_spell_dummy_permafrost(), EffectDummyCreature_worm_emerge(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_boss_freya(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_spell_diminution_powder(), EffectScriptEffectCreature_spell_stun_break(), EffectScriptEffectCreature_spell_unstable_ooze(), Spell::EffectSummonType(), mob_shadowmoon_soulstealerAI::EnterEvadeMode(), ScriptAction::ExecuteDbscriptCommand(), GossipHello_npc_adyen_the_lightwarden(), GossipHello_npc_anchorite_barada(), GossipHello_npc_ashli(), GossipHello_npc_colonel_jules(), GossipHello_npc_demoniac_scryer(), GossipHello_npc_gossip_npc(), GossipHello_npc_harkor(), GossipHello_npc_kraz(), GossipHello_npc_reginald_windsor(), GossipHello_npc_silvermoon_harry(), GossipHello_npc_squire_rowe(), GossipHello_npc_tanzar(), GossipSelect_boss_majordomo(), GossipSelect_boss_vaelastrasz(), GossipSelect_boss_victor_nefarius(), GossipSelect_example_creature(), GossipSelect_example_escort(), GossipSelect_go_manaforge(), GossipSelect_npc_adyen_the_lightwarden(), GossipSelect_npc_akama(), GossipSelect_npc_akama_illidan(), GossipSelect_npc_anchorite_barada(), GossipSelect_npc_arthas(), GossipSelect_npc_artorius(), GossipSelect_npc_ashli(), GossipSelect_npc_barnes(), GossipSelect_npc_blastmaster_emi_shortfuse(), GossipSelect_npc_brann_hos(), GossipSelect_npc_corrupt_saber(), GossipSelect_npc_dirty_larry(), GossipSelect_npc_disciple_of_naralex(), GossipSelect_npc_expedition_commander(), GossipSelect_npc_general_andorov(), GossipSelect_npc_harkor(), GossipSelect_npc_harrison_jones_za(), GossipSelect_npc_highlord_darion_mograine(), GossipSelect_npc_injured_miner(), GossipSelect_npc_jaina_proudmoore(), GossipSelect_npc_klinfran(), GossipSelect_npc_kraz(), GossipSelect_npc_mistress_nagmara(), GossipSelect_npc_orphan_matron(), GossipSelect_npc_prospector_anvilward(), GossipSelect_npc_reginald_windsor(), GossipSelect_npc_regthar_deathgate(), GossipSelect_npc_saeed(), GossipSelect_npc_salsalabim(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_shadowfang_prisoner(), GossipSelect_npc_silvermoon_harry(), GossipSelect_npc_simone_the_inconspicuous(), GossipSelect_npc_solenor(), GossipSelect_npc_squire_rowe(), GossipSelect_npc_tanzar(), GossipSelect_npc_thrall(), GossipSelect_npc_thrall_old_hillsbrad(), GossipSelect_npc_threshwackonator(), GossipSelect_npc_tipsy_mcmanus(), GOUse_go_cage_trap(), WorldState::HandleActiveZone(), boss_nefarianAI::HandleAttackStart(), BattleGroundIC::HandleKillUnit(), ChatHandler::HandleNpcAIInfoCommand(), ChatHandler::HandleNpcEvade(), ChatHandler::HandleNpcInfoCommand(), WaypointMovementGenerator< Creature >::InformAI(), npc_akamaAI::JustDidDialogueStep(), instance_blackrock_spire::JustDidDialogueStep(), boss_brutallusAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), boss_golemaggAI::JustDied(), boss_eye_of_cthunAI::JustDied(), boss_shade_of_akamaAI::JustDied(), mob_ashtongue_channelerAI::JustDied(), mob_ashtongue_sorcererAI::JustDied(), Council_Base_AI::JustDied(), boss_warbringer_omroggAI::JustDied(), mob_shadowmoon_soulstealerAI::JustDied(), Unit::JustKilledCreature(), npc_simone_seductressAI::JustReachedHome(), npc_kaylaan_the_lostAI::JustReachedHome(), mob_shadowmoon_soulstealerAI::JustRespawned(), boss_uromAI::JustSummoned(), npc_professor_phizzlethorpeAI::JustSummoned(), boss_general_angerforgeAI::JustSummoned(), boss_overlordwyrmthalakAI::JustSummoned(), npc_grark_lorkrubAI::JustSummoned(), npc_eris_havenfireAI::JustSummoned(), npc_apprentice_mirvedaAI::JustSummoned(), npc_infused_crystalAI::JustSummoned(), boss_dorotheeAI::JustSummoned(), boss_julianneAI::JustSummoned(), npc_miranAI::JustSummoned(), npc_highlord_darion_mograineAI::JustSummoned(), boss_headless_horsemanAI::JustSummoned(), boss_cannon_master_willeyAI::JustSummoned(), npc_anchorite_truuenAI::JustSummoned(), npc_tapoke_slim_jahnAI::JustSummoned(), example_escortAI::JustSummoned(), npc_muglashAI::JustSummoned(), npc_torekAI::JustSummoned(), npc_feero_ironhandAI::JustSummoned(), npc_arthasAI::JustSummoned(), npc_time_riftAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_volcorAI::JustSummoned(), npc_areiAI::JustSummoned(), boss_noxxionAI::JustSummoned(), npc_willix_the_importerAI::JustSummoned(), mob_anubisath_guardianAI::JustSummoned(), npc_solenorAI::JustSummoned(), npc_kayaAI::JustSummoned(), npc_wizzlecranks_shredderAI::JustSummoned(), npc_lakota_windsongAI::JustSummoned(), boss_zumrahAI::JustSummoned(), mob_ahnkahar_eggAI::JustSummoned(), boss_taldaramAI::JustSummoned(), boss_volazjAI::JustSummoned(), boss_krikthirAI::JustSummoned(), npc_proudhoofAI::JustSummoned(), boss_black_knightAI::JustSummoned(), boss_anubarak_trialAI::JustSummoned(), boss_jaraxxusAI::JustSummoned(), twin_jormungars_commonAI::JustSummoned(), boss_icehowlAI::JustSummoned(), npc_destructive_wardAI::JustSummoned(), boss_novosAI::JustSummoned(), npc_harrison_jonesAI::JustSummoned(), npc_squad_leaderAI::JustSummoned(), boss_devourer_of_soulsAI::JustSummoned(), boss_lich_king_horAI::JustSummoned(), boss_taldaram_iccAI::JustSummoned(), boss_lady_deathwhisperAI::JustSummoned(), boss_professor_putricideAI::JustSummoned(), boss_malygosAI::JustSummoned(), boss_ormorokAI::JustSummoned(), boss_telestraAI::JustSummoned(), boss_eregosAI::JustSummoned(), boss_ionarAI::JustSummoned(), boss_volkhanAI::JustSummoned(), boss_molgeimAI::JustSummoned(), boss_freyaAI::JustSummoned(), boss_kologarnAI::JustSummoned(), boss_aerial_unitAI::JustSummoned(), boss_exarch_maladaarAI::JustSummoned(), npc_shaheenAI::JustSummoned(), boss_darkweaver_sythAI::JustSummoned(), npc_warp_gate::JustSummoned(), boss_warchief_kargath_bladefistAI::JustSummoned(), npc_demoniac_scryerAI::JustSummoned(), npc_wounded_blood_elfAI::JustSummoned(), npc_colonel_julesAI::JustSummoned(), npc_nagrand_captiveAI::JustSummoned(), npc_manaforge_control_consoleAI::JustSummoned(), npc_protectorate_demolitionistAI::JustSummoned(), npc_drijyaAI::JustSummoned(), npc_salhadaarAI::JustSummoned(), npc_wildaAI::JustSummoned(), npc_warden_mellicharAI::JustSummoned(), boss_harbinger_skyrissAI::JustSummoned(), boss_high_botanist_freywinnAI::JustSummoned(), boss_lajAI::JustSummoned(), boss_high_astromancer_solarianAI::JustSummoned(), boss_pathaleon_the_calculatorAI::JustSummoned(), npc_akunoAI::JustSummoned(), npc_letollAI::JustSummoned(), npc_skywingAI::JustSummoned(), npc_skyguard_prisonerAI::JustSummoned(), boss_coren_direbrewAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_midnightAI::JustSummoned(), boss_nightbaneAI::JustSummoned(), boss_aranAI::JustSummoned(), boss_terestianAI::JustSummoned(), boss_felblood_kaelthasAI::JustSummoned(), npc_zelfanAI::JustSummoned(), boss_vexallusAI::JustSummoned(), boss_ragnarosAI::JustSummoned(), boss_brutallusAI::JustSummoned(), npc_demonic_vaporAI::JustSummoned(), boss_sathrovarrAI::JustSummoned(), boss_kiljaedenAI::JustSummoned(), boss_muruAI::JustSummoned(), npc_portal_targetAI::JustSummoned(), npc_darknessAI::JustSummoned(), boss_halazziAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_zuljinAI::JustSummoned(), boss_jeklikAI::JustSummoned(), boss_mandokirAI::JustSummoned(), boss_anetheronAI::JustSummoned(), boss_archimondeAI::JustSummoned(), npc_oox22feAI::JustSummoned(), npc_clintar_dw_spiritAI::JustSummoned(), npc_keeper_remulosAI::JustSummoned(), boss_ayamissAI::JustSummoned(), npc_buru_eggAI::JustSummoned(), boss_moamAI::JustSummoned(), npc_oox17tnAI::JustSummoned(), boss_eye_of_cthunAI::JustSummoned(), boss_cthunAI::JustSummoned(), boss_fankrissAI::JustSummoned(), boss_skeramAI::JustSummoned(), boss_viscidusAI::JustSummoned(), npc_kanatiAI::JustSummoned(), boss_drakkari_colossusAI::JustSummoned(), boss_sladranAI::JustSummoned(), boss_krickAI::JustSummoned(), boss_rimefang_posAI::JustSummoned(), boss_deathbringer_saurfangAI::JustSummoned(), boss_anubrekhanAI::JustSummoned(), boss_loathebAI::JustSummoned(), boss_nothAI::JustSummoned(), boss_ichoronAI::JustSummoned(), boss_xevozzAI::JustSummoned(), boss_nexusprince_shaffarAI::JustSummoned(), boss_anzuAI::JustSummoned(), npc_grand_collectorAI::JustSummoned(), boss_gurtogg_bloodboilAI::JustSummoned(), boss_illidan_stormrageAI::JustSummoned(), npc_akama_illidanAI::JustSummoned(), npc_flame_of_azzinothAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_supremusAI::JustSummoned(), boss_terokkAI::JustSummoned(), boss_fathomguard_sharkkisAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_leotheras_the_blindAI::JustSummoned(), boss_morogrim_tidewalkerAI::JustSummoned(), boss_ahuneAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_omor_the_unscarredAI::JustSummoned(), npc_lord_illidan_stormrageAI::JustSummoned(), boss_kaelthasAI::JustSummoned(), boss_emerald_dragonAI::JustSummoned(), mob_phoenix_tkAI::JustSummoned(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_air_force_botsAI::MoveInLineOfSight(), npc_shattered_hands_zealotAI::MovementInform(), npc_shade_of_the_horsemanAI::MovementInform(), boss_shade_of_akamaAI::MovementInform(), boss_eranikusAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_deadsoul_orb::MovementInform(), NpcSpellClick_npc_descent_madness(), HodirsProtectiveGaze::OnAbsorb(), WaypointMovementGenerator< Creature >::OnArrived(), instance_temple_of_ahnqiraj::OnCreatureCreate(), world_map_outland::OnCreatureCreate(), instance_ulduar::OnCreatureDeath(), instance_karazhan::OnCreatureRespawn(), instance_shadowfang_keep::OnCreatureRespawn(), instance_sunwell_plateau::OnCreatureRespawn(), instance_zulaman::OnCreatureRespawn(), instance_mount_hyjal::OnCreatureRespawn(), instance_temple_of_ahnqiraj::OnCreatureRespawn(), instance_naxxramas::OnCreatureRespawn(), instance_nexus::OnCreatureRespawn(), instance_ulduar::OnCreatureRespawn(), instance_utgarde_keep::OnCreatureRespawn(), instance_pinnacle::OnCreatureRespawn(), world_map_outland::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_trial_of_the_crusader::OnCreatureRespawn(), instance_pit_of_saron::OnCreatureRespawn(), instance_icecrown_citadel::OnCreatureRespawn(), instance_eye_of_eternity::OnCreatureRespawn(), instance_oculus::OnCreatureRespawn(), instance_ruby_sanctum::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), instance_violet_hold::OnCreatureRespawn(), SendHead::OnEffectExecute(), HeadRequestsBody::OnEffectExecute(), spell_tag_troll::OnEffectExecute(), IceBolt::OnEffectExecute(), OnEventHappened(), GreaterInvisibilityMob::OnPeriodicTickEnd(), ZombieChowSearch::OnPeriodicTrigger(), spell_effect_summon_no_follow_movement::OnSummon(), ArmyOfTheDeadGhoul::OnSummon(), SummonPlagueSpray::OnSummon(), TailsUpSummonFemaleFrostLeopard::OnSummon(), TailsUpSummonFemaleIcepawBear::OnSummon(), SummonBoss::OnSummon(), Bloodworm::OnSummon(), DancingRuneWeapon::OnSummon(), SummonGargoyle::OnSummon(), Shadowfiend::OnSummon(), MaNGOS::CallOfHelpCreatureInRangeDo::operator()(), PlayerVisitCreatureWorker(), CreatureEventAI::ProcessAction(), BattleGroundEY::ProcessCaptureEvent(), ProcessEventId_event_spell_summon_nightbane(), instance_dire_maul::ProcessForceFieldOpening(), CreatureLinkingHolder::ProcessSlave(), QuestAccept_npc_00x09hl(), QuestAccept_npc_akuno(), QuestAccept_npc_ame01(), QuestAccept_npc_anchorite_truuen(), QuestAccept_npc_apothecary_hanes(), QuestAccept_npc_arei(), QuestAccept_npc_bartleby(), QuestAccept_npc_belnistrasz(), QuestAccept_npc_bessy(), QuestAccept_npc_bonker_togglevolt(), QuestAccept_npc_calvin_montague(), QuestAccept_npc_captured_arkonarin(), QuestAccept_npc_captured_vanguard(), QuestAccept_npc_commander(), QuestAccept_npc_cork_gizelton(), QuestAccept_npc_corporal_keeshan(), QuestAccept_npc_dalinda_malem(), QuestAccept_npc_daphne_stilwell(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_deathstalker_erland(), QuestAccept_npc_deathstalker_faerleia(), QuestAccept_npc_defias_traitor(), QuestAccept_npc_demolitionist_legoso(), QuestAccept_npc_doctor(), QuestAccept_npc_dorius_stonetender(), QuestAccept_npc_dragonmaw_racer(), QuestAccept_npc_drijya(), QuestAccept_npc_emily(), QuestAccept_npc_eris_havenfire(), QuestAccept_npc_evergrove_druid(), QuestAccept_npc_father_kamaros(), QuestAccept_npc_feero_ironhand(), QuestAccept_npc_fhwoor(), QuestAccept_npc_galen_goodward(), QuestAccept_npc_gilthares(), QuestAccept_npc_grark_lorkrub(), QuestAccept_npc_harrison_jones(), QuestAccept_npc_helice(), QuestAccept_npc_injured_miner(), QuestAccept_npc_injured_rainspeaker(), QuestAccept_npc_isla_starmane(), QuestAccept_npc_kanati(), QuestAccept_npc_kaya(), QuestAccept_npc_kayra_longmane(), QuestAccept_npc_keeper_remulos(), QuestAccept_npc_kelerun_bloodmourn(), QuestAccept_npc_kerlonian(), QuestAccept_npc_kernobee(), QuestAccept_npc_kindal_moonweaver(), QuestAccept_npc_kinelory(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_letoll(), QuestAccept_npc_lurgglbr(), QuestAccept_npc_magwin(), QuestAccept_npc_major_mills(), QuestAccept_npc_marshal_windsor(), QuestAccept_npc_maxx_a_million(), QuestAccept_npc_melizza_brimbuzzle(), QuestAccept_npc_mikhail(), QuestAccept_npc_miran(), QuestAccept_npc_mist(), QuestAccept_npc_mootoo_the_younger(), QuestAccept_npc_morokk(), QuestAccept_npc_muglash(), QuestAccept_npc_nagrand_captive(), QuestAccept_npc_ogron(), QuestAccept_npc_oox17tn(), QuestAccept_npc_oox22fe(), QuestAccept_npc_orphan_matron(), QuestAccept_npc_paoka_swiftmountain(), QuestAccept_npc_private_hendel(), QuestAccept_npc_professor_phizzlethorpe(), QuestAccept_npc_prospector_remtravel(), QuestAccept_npc_proudhoof(), QuestAccept_npc_ranger_lilatha(), QuestAccept_npc_ranshalla(), QuestAccept_npc_reginald_windsor(), QuestAccept_npc_regthar_deathgate(), QuestAccept_npc_ringo(), QuestAccept_npc_rinji(), QuestAccept_npc_ruul_snowhoof(), QuestAccept_npc_shaheen(), QuestAccept_npc_shay_leafrunner(), QuestAccept_npc_skyguard_prisoner(), QuestAccept_npc_skywing(), QuestAccept_npc_squad_leader(), QuestAccept_npc_stinky_ignatz(), QuestAccept_npc_taelan_fordring(), QuestAccept_npc_therylune(), QuestAccept_npc_tooga(), QuestAccept_npc_torek(), QuestAccept_npc_volcor(), QuestAccept_npc_wilda(), QuestAccept_npc_willix_the_importer(), QuestAccept_npc_wizzlecranks_shredder(), QuestAccept_npc_wounded_blood_elf(), QuestAccept_unexpected_results(), QuestComplete_npc_nazgrel(), QuestComplete_npc_trollbane(), QuestRewarded_boss_apothecary_hummel(), QuestRewarded_npc_coren_direbrew(), QuestRewarded_npc_lady_sylvanas_windrunner(), QuestRewarded_npc_mistress_nagmara(), QuestRewarded_npc_rocknot(), QuestRewarded_npc_taelan_fordring(), npc_akamaAI::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), RemoveCorpse(), RemoveFromWorld(), npc_building_triggerAI::Reset(), WaypointMovementGenerator< Creature >::SendNextWayPointPath(), npc_twiggy_flatheadAI::SetChallengerReady(), Unit::SetInCombatState(), SetInCombatWithZone(), SetSpellList(), world_map_outland::SpawnAlliesAtCrystalforge(), instance_mount_hyjal::SpawnWave(), world_map_outland::StartBashirLandingEvent(), npc_theramore_spar_controller::StartSparring(), world_map_outland::StartTransitionPhase(), boss_cthunAI::SummonedCreatureDespawn(), npc_crystal_channel_targetAI::SummonedMovementInform(), npc_emilyAI::SummonedMovementInform(), npc_dorius_stonetenderAI::SummonedMovementInform(), boss_muruAI::SummonedMovementInform(), npc_creature_generatorAI::SummonedMovementInform(), npc_scrapped_fel_reaverAI::SummonedMovementInform(), boss_the_lurker_belowAI::SummonedMovementInform(), boss_eranikusAI::SummonedMovementInform(), npc_theramore_spar_controller::SwitchMembers(), boss_veklorAI::TeleportTwin(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), TemporarySpawn::UnSummon(), Totem::UnSummon(), world_map_ebon_hold::Update(), instance_stratholme::Update(), instance_uldaman::Update(), Update(), boss_eranikusAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), npc_tenebron_egg_controllerAI::UpdateAI(), boss_murmurAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), mob_shadowmoon_soulstealerAI::UpdateAI(), CreatureSettings::updateFlag(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_rocknotAI::WaypointReached(), and npc_prospector_anvilwardAI::WaypointReached().
AIM_Initialize()
bool Creature::AIM_Initialize ()
Definition at line 894 of file Creature.cpp.
References CREATOR_LOOT, Unit::GetCreator(), WorldObject::GetInstanceData(), GetSettings(), Object::HasFlag(), Unit::i_motionMaster, MotionMaster::Initialize(), m_ai, FactorySelector::selectAI(), and SetLootRecipient().
Referenced by Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::EffectCreateTamedPet(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectSummonPet(), Spell::EffectSummonType(), Spell::EffectTameCreature(), LoadFromDB(), Pet::LoadPetFromDB(), spell_feigh_death_pos_aura::OnApply(), spell_dark_transformation_aura::OnApply(), spell_dark_empowerment_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_dark_adherent_martyrdom_aura::OnApply(), ResetEntry(), TemporarySpawn::Summon(), Totem::Summon(), and Unit::TakePossessOf().
ApplyGameEventSpells()
void Creature::ApplyGameEventSpells (GameEventCreatureData const * eventData, bool activated)
Definition at line 2652 of file Creature.cpp.
References Unit::CastSpell(), IsSpellAppliesAura(), SQLStorage::LookupEntry(), Unit::RemoveAurasDueToSpell(), GameEventCreatureData::spell_id_end, GameEventCreatureData::spell_id_start, sSpellTemplate, and TRIGGERED_OLD_TRIGGERED.
Referenced by UpdateEntry().
CallAssistance()
void Creature::CallAssistance ()
Definition at line 2131 of file Creature.cpp.
References AI(), AI_EVENT_CALL_ASSISTANCE, CreatureInfo::CallForHelp, CallForHelp(), CanCallForAssistance(), CONFIG_FLOAT_CREATURE_FAMILY_ASSISTANCE_RADIUS, CONFIG_UINT32_CREATURE_FAMILY_ASSISTANCE_DELAY, GetCreatureInfo(), Unit::GetVictim(), Unit::HasCharmer(), m_AlreadyCallAssistance, MANGOS_ASSERT, UnitAI::SendAIEventAround(), SetNoCallAssistance(), and sWorld.
Referenced by CreatureAI::RetreatingArrived(), and Unit::SetInCombatState().
CallForHelp()
void Creature::CallForHelp (float radius)
Definition at line 2150 of file Creature.cpp.
References CreatureInfo::CallForHelp, GetCreatureInfo(), Unit::GetVictim(), Unit::HasCharmer(), IsPet(), and Cell::VisitGridObjects().
Referenced by boss_emperor_dagran_thaurissanAI::Aggro(), CallAssistance(), and CreatureAI::DoCallForHelp().
CanAggro()
bool Creature::CanAggro () const inline
Definition at line 820 of file Creature.h.
References m_canAggro.
Referenced by CanInitiateAttack(), Heartbeat(), and Unit::SetInCombatState().
CanAssistTo()
bool Creature::CanAssistTo (const Unit * u, const Unit * enemy, bool checkfaction = true) const
if enemy provided, check for initial combat help against enemy
Definition at line 2164 of file Creature.cpp.
References Unit::CanAttack(), Unit::GetFaction(), Unit::GetMasterGuid(), Object::HasFlag(), Unit::IsAlive(), Unit::IsEnemy(), Unit::IsInCombat(), IsNoAggroOnSight(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_SPAWNING, and UNIT_FLAG_UNINTERACTIBLE.
CanCallForAssistance()
bool Creature::CanCallForAssistance () const inline override virtual
Reimplemented from Unit.
Definition at line 725 of file Creature.h.
References m_canCallForAssistance.
Referenced by CallAssistance().
CanCheckForHelp()
bool Creature::CanCheckForHelp () const inline override virtual
Reimplemented from Unit.
Definition at line 823 of file Creature.h.
References m_checkForHelp.
CanFly()
bool Creature::CanFly () const inline override virtual
Implements Unit.
Definition at line 597 of file Creature.h.
References Object::GetByteValue(), GetCreatureInfo(), MovementInfo::HasMovementFlag(), INHABIT_AIR, WorldObject::m_movementInfo, MOVEFLAG_CAN_FLY, MOVEFLAG_HOVER, MOVEFLAG_LEVITATING, UNIT_BYTE1_FLAG_FLY_ANIM, and UNIT_FIELD_BYTES_1.
Referenced by LoadFromDB(), and GuardAI::MoveInLineOfSight().
CanInitiateAttack()
bool Creature::CanInitiateAttack () const
Definition at line 2204 of file Creature.cpp.
References CanAggro(), Object::HasFlag(), Unit::hasUnitState(), m_forceAttackingCapability, UNIT_FIELD_FLAGS, UNIT_FLAG_SPAWNING, UNIT_FLAG_UNINTERACTIBLE, UNIT_STAT_FEIGN_DEATH, and UNIT_STAT_STUNNED.
Referenced by GuardAI::MoveInLineOfSight().
CanInteractWithBattleMaster()
bool Creature::CanInteractWithBattleMaster (Player * pPlayer, bool msg) const
Definition at line 1054 of file Creature.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_NA, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_TYPE_NONE, BATTLEGROUND_WS, PlayerMenu::ClearMenus(), Player::GetBGAccessByLevel(), Object::GetEntry(), Object::GetObjectGuid(), Player::GetPlayerMenu(), Unit::isBattleMaster(), sBattleGroundMgr, and PlayerMenu::SendGossipMenu().
Referenced by Player::PrepareGossipMenu().
CanRestockPickpocketLoot()
bool Creature::CanRestockPickpocketLoot () const
Definition at line 3016 of file Creature.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), and m_pickpocketRestockTime.
Referenced by Spell::EffectPickPocket().
CanSwim()
bool Creature::CanSwim () const inline virtual
Implements Unit.
Reimplemented in Pet.
Definition at line 595 of file Creature.h.
References GetCreatureInfo(), and INHABIT_WATER.
Referenced by Pet::CanSwim(), and PathFinder::createFilter().
CanTrainAndResetTalentsOf()
bool Creature::CanTrainAndResetTalentsOf (Player * pPlayer) const
Definition at line 1089 of file Creature.cpp.
References Unit::getClass(), GetCreatureInfo(), Unit::GetLevel(), TRAINER_TYPE_CLASS, CreatureInfo::TrainerClass, and CreatureInfo::TrainerType.
Referenced by PlayerbotAI::findNearbyCreature(), WorldSession::HandleTalentWipeConfirmOpcode(), and Player::PrepareGossipMenu().
CanWalk()
bool Creature::CanWalk () const inline virtual
Implements Unit.
Definition at line 594 of file Creature.h.
References GetCreatureInfo(), and INHABIT_GROUND.
Referenced by PathFinder::createFilter().
ChooseDisplayId()
uint32 Creature::ChooseDisplayId (const CreatureInfo * cinfo, const CreatureData * data = nullptr, GameEventCreatureData const * eventData = nullptr) static
Definition at line 659 of file Creature.cpp.
References CreatureInfo::Entry, ObjectMgr::GetCreatureTemplate(), MAX_CREATURE_MODEL, CreatureInfo::ModelId, CreatureSpawnTemplate::modelId, GameEventCreatureData::modelid, sLog, sObjectMgr, CreatureData::spawnTemplate, and urand().
Referenced by EffectDummyCreature_npc_kitten(), Spell::EffectScriptEffect(), ScriptAction::ExecuteDbscriptCommand(), ObjectMgr::GetModelForRace(), ObjectMgr::GetTaxiMountDisplayId(), Aura::HandleAuraMounted(), Aura::HandleAuraTransform(), InitEntry(), boss_tharonjaAI::JustReachedHome(), GraspOfTheEmeraldDream::OnEffectExecute(), CreatureEventAI::ProcessAction(), npc_clintar_dw_spiritAI::Reset(), and boss_tharonjaAI::UpdateAI().
CleanupsBeforeDelete()
void Creature::CleanupsBeforeDelete () override virtual
Reimplemented from WorldObject.
Definition at line 254 of file Creature.cpp.
References Unit::CleanupsBeforeDelete(), GetCreatureGroup(), CreatureGroup::GetFormationData(), m_vendorItemCounts, and FormationData::OnDelete().
Referenced by ~Creature().
ClearCreatureGroup()
void Creature::ClearCreatureGroup ()
Definition at line 1555 of file Creature.cpp.
References CreatureGroup::GetFormationData(), m_creatureGroup, FormationData::Remove(), and CreatureGroup::RemoveObject().
Referenced by RemoveFromWorld(), and SetDeathState().
ClearTemporaryFaction()
void Creature::ClearTemporaryFaction ()
Definition at line 2616 of file Creature.cpp.
References GetCreatureInfo(), Unit::HasCharmer(), m_temporaryFactionFlags, Unit::setFaction(), Object::SetFlag(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), TEMPFACTION_NONE, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, TEMPFACTION_TOGGLE_NON_ATTACKABLE, TEMPFACTION_TOGGLE_NOT_SELECTABLE, TEMPFACTION_TOGGLE_PACIFIED, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_PACIFIED, UNIT_FLAG_SPAWNING, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by HomeMovementGenerator< Creature >::Finalize(), npc_melizza_brimbuzzleAI::JustDidDialogueStep(), CreatureEventAI::ProcessAction(), npc_bonechewer_brawler::ReceiveAIEvent(), npc_apprentice_mirvedaAI::Reset(), SetDeathState(), Unit::Uncharm(), npc_bonechewer_combatant::UpdateAI(), and npc_drijyaAI::WaypointReached().
Create()
bool Creature::Create (uint32 dbGuid, uint32 guidlow, CreatureCreatePos & cPos, CreatureInfo const * cinfo, const CreatureData * data = nullptr, GameEventCreatureData const * eventData = nullptr)
Definition at line 912 of file Creature.cpp.
References CreatureLinkingHolder::AddMasterToHolder(), CreatureLinkingHolder::AddSlaveToHolder(), CreateFromProto(), Map::GetCreatureLinkingHolder(), Map::GetInstanceData(), CreatureCreatePos::GetMap(), WorldObject::GetMap(), CreatureCreatePos::GetPhaseMask(), WorldObject::GetZoneId(), LoadCreatureAddon(), Unit::m_isCreatureLinkingTrigger, CreatureCreatePos::Relocate(), sCreatureLinkingMgr, CreatureCreatePos::SelectFinalPoint(), WorldObject::SetMap(), Unit::SetPhaseMask(), SetRespawnCoord(), and sOutdoorPvPMgr.
Referenced by ChatHandler::HandleNpcAddCommand(), LoadFromDB(), WorldObject::SummonCreature(), and Unit::TakePossessOf().
CreateFromProto()
bool Creature::CreateFromProto (uint32 dbGuid, uint32 guidlow, CreatureInfo const * cinfo, const CreatureData * data = nullptr, GameEventCreatureData const * eventData = nullptr) protected
Definition at line 1579 of file Creature.cpp.
References Object::_Create(), CreatureInfo::Entry, Object::GetDbGuid(), CreatureInfo::GetHighGuid(), m_originalEntry, sObjectMgr, and UpdateEntry().
Referenced by Create(), and Totem::Create().
DeleteFromDB() [1/2]
void Creature::DeleteFromDB () virtual
Reimplemented in TemporarySpawn, and Pet.
Definition at line 1816 of file Creature.cpp.
References DEBUG_LOG, Object::GetGUIDLow(), and sObjectMgr.
Referenced by ChatHandler::HandleNpcDeleteCommand().
DeleteFromDB() [2/2]
void Creature::DeleteFromDB (uint32 lowguid, CreatureData const * data) static
Definition at line 1828 of file Creature.cpp.
References Database::BeginTransaction(), Database::CommitTransaction(), CreatureData::mapid, Database::PExecuteLog(), sMapPersistentStateMgr, sObjectMgr, and WorldDatabase.
FillGuidsListFromThreatList()
void Creature::FillGuidsListFromThreatList (GuidVector & guids, uint32 maxamount = 0)
Definition at line 2666 of file Creature.cpp.
References Unit::CanHaveThreatList(), ThreatManager::getThreatList(), and Unit::getThreatManager().
Referenced by boss_grandmaster_vorpilAI::DoTeleportToPlatform().
ForcedDespawn()
void Creature::ForcedDespawn (uint32 timeMSToDespawn = 0, bool onlyAlive = false) virtual
Reimplemented in Pet.
Definition at line 1939 of file Creature.cpp.
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), Unit::IsAlive(), IsDespawned(), JUST_DIED, WorldObject::m_events, RemoveCorpse(), SetDeathState(), and Unit::SetHealth().
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), boss_ouroAI::Burrow(), BattleGround::ChangeBgCreatureSpawnState(), npc_serpentshrine_parasiteAI::DamageDeal(), npc_akamaAI::DamageTaken(), npc_death_knight_initiateAI::DamageTaken(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_simone_seductressAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_adyen_the_lightwardenAI::DespawnEvent(), boss_silithidRoyaltyAI::DoDummyConsume(), npc_daphne_stilwellAI::DoEndEscort(), npc_cenarion_sparrowhawkAI::DoFindNearbyStones(), npc_teleportation_portalAI::DoSummon(), Spell::DoSummonVehicle(), EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_spell_aura_dummy_npc(), Spell::EffectDummy(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_npc_scorch(), EffectScriptEffectCreature_spell_eat_ooze(), Spell::EffectTameCreature(), npc_adyen_the_lightwardenAI::EndEvent(), boss_nefarianAI::EnterEvadeMode(), boss_nightbaneAI::EnterEvadeMode(), boss_felblood_kaelthasAI::EnterEvadeMode(), boss_felmystAI::EnterEvadeMode(), boss_kalecgos_humanoidAI::EnterEvadeMode(), boss_kiljaedenAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), npc_ouro_moundAI::EnterEvadeMode(), OuroScarab::EnterEvadeMode(), npc_precious_the_devourerAI::EnterEvadeMode(), npc_beast_combat_stalkerAI::EnterEvadeMode(), boss_fjolaAI::EnterEvadeMode(), boss_gothikAI::EnterEvadeMode(), boss_kelthuzadAI::EnterEvadeMode(), boss_nothAI::EnterEvadeMode(), boss_ichoronAI::EnterEvadeMode(), boss_xevozzAI::EnterEvadeMode(), essence_base_AI::EnterEvadeMode(), boss_essence_of_angerAI::EnterEvadeMode(), npc_enslaved_soulAI::EnterEvadeMode(), npc_the_cleanerAI::EnterEvadeMode(), ForcedDespawnDelayEvent::Execute(), npc_magister_aledisAI::ExecuteAction(), npc_adyen_the_lightwardenAI::FailEvent(), mob_torlothAI::FailEvent(), npc_dragonmaw_racerAI::FailRace(), Pet::ForcedDespawn(), GossipHello_npc_aged_dying_ancient_kodo(), GossipSelect_npc_grandmother(), GossipSelect_npc_keeper_norgannon(), GossipSelect_npc_saronite_mine_slave(), GOUse_go_cage_trap(), mob_torlothAI::HandleAnimation(), BattlefieldWG::HandleCreatureCreate(), npc_ethereal_sphereAI::HandleDelayExpired(), npc_general_andorovAI::HandleDespawn(), Aura::HandleModCharm(), Aura::HandleModPossess(), npc_akama_illidanAI::HandleOutro(), WorldSession::HandlePetActionHelper(), world_map_outland::HandleShartuulEventReset(), npc_singularityAI::HandleSpawn(), npc_shadowfang_prisonerAI::HandleSpeech(), npc_kalecgosAI::HandleTransform(), npc_taelan_fordringAI::JustDidDialogueStep(), boss_maievAI::JustDidDialogueStep(), npc_tapoke_slim_jahnAI::JustDidDialogueStep(), npc_areiAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), boss_algalonAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), boss_thorimAI::JustDidDialogueStep(), npc_chess_piece_genericAI::JustDied(), npc_medivh_black_morassAI::JustDied(), boss_skeramAI::JustDied(), npc_snakeWrapAI::JustDied(), boss_thaddiusAI::JustDied(), npc_brann_hosAI::JustDied(), boss_warbringer_omroggAI::JustDied(), npc_spirit_shadeAI::JustDied(), npc_a_special_surpriseAI::JustDied(), npc_warchief_blackhandAI::JustDied(), boss_attumenAI::JustReachedHome(), boss_dorotheeAI::JustReachedHome(), boss_strawmanAI::JustReachedHome(), boss_tinheadAI::JustReachedHome(), boss_roarAI::JustReachedHome(), boss_croneAI::JustReachedHome(), boss_bigbadwolfAI::JustReachedHome(), boss_julianneAI::JustReachedHome(), boss_romuloAI::JustReachedHome(), npc_scarlet_courierAI::JustReachedHome(), boss_headless_horsemanAI::JustReachedHome(), boss_arlokkAI::JustReachedHome(), npc_morokkAI::JustReachedHome(), boss_ouroAI::JustReachedHome(), boss_skeramAI::JustReachedHome(), boss_drakkari_elementalAI::JustReachedHome(), boss_thaddiusAI::JustReachedHome(), boss_yogg_saronAI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), npc_evergrove_druidAI::JustReachedHome(), boss_the_lurker_belowAI::JustReachedHome(), boss_ahuneAI::JustReachedHome(), npc_salhadaarAI::JustReachedHome(), npc_shadow_imageAI::JustRespawned(), npc_zulian_prowlerAI::JustRespawned(), npc_web_wrapAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustSummoned(), boss_devourer_of_soulsAI::JustSummoned(), boss_professor_putricideAI::JustSummoned(), boss_brundirAI::JustSummoned(), boss_algalonAI::JustSummoned(), boss_hodirAI::JustSummoned(), boss_kologarnAI::JustSummoned(), boss_ingvarAI::JustSummoned(), npc_teleportation_portalAI::JustSummoned(), npc_colonel_julesAI::JustSummoned(), npc_demonic_vaporAI::JustSummoned(), boss_muruAI::JustSummoned(), npc_ouro_spawnerAI::JustSummoned(), npc_ouro_moundAI::JustSummoned(), boss_veras_darkshadowAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_tethyrAI::KilledUnit(), npc_bone_spikeAI::KilledUnit(), npc_rabid_bearAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_corrupted_soul_fragmentAI::MoveInLineOfSight(), boss_lich_king_horAI::MoveInLineOfSight(), npc_ball_of_flameAI::MoveInLineOfSight(), npc_power_sparkAI::MoveInLineOfSight(), npc_planar_anomalyAI::MoveInLineOfSight(), npc_black_holeAI::MoveInLineOfSight(), npc_scrapbotAI::MoveInLineOfSight(), npc_charged_sphereAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_veneratus_spawn_nodeAI::MoveInLineOfSight(), npc_spirit_shadeAI::MoveInLineOfSight(), npc_ingvar_throw_dummyAI::MoveInLineOfSight(), npc_cage_trap_triggerAI::MoveInLineOfSight(), mob_water_globuleAI::MoveInLineOfSight(), npc_shade_of_the_horsemanAI::MovementInform(), FollowerAI::MovementInform(), boss_midnightAI::MovementInform(), boss_kalecgosAI::MovementInform(), npc_amanishi_lookoutAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), npc_forest_frogAI::MovementInform(), npc_skyguard_aether_techAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), npc_escortAI::MovementInform(), npc_living_mojoAI::MovementInform(), boss_tethyrAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_spirit_prisoner_of_bladespire::MovementInform(), npc_deadsoul_orb::MovementInform(), npc_Shattered_Hand_Scout::MovementInform(), npc_queen_lanathel_introAI::MovementInform(), npc_kinetic_bombAI::MovementInform(), npc_decaying_ghoulAI::MovementInform(), mobs_nether_drakeAI::MovementInform(), npc_rethhedronAI::MovementInform(), mob_enslaved_netherwing_drakeAI::MovementInform(), npc_barrett_ramseyAI::MovementInform(), npc_grand_admiral_westwindAI::MovementInform(), npc_flame_tsunamiAI::MovementInform(), mob_spark_of_ionarAI::MovementInform(), npc_brann_hosAI::MovementInform(), npc_deadsoul_orb::MoveToNextTrigger(), NecroticShard::NecroticShard(), npc_commanderAI::npc_commanderAI(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), npc_ethereum_prisoner_dungeonAI::npc_ethereum_prisoner_dungeonAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_fire_nova_totemAI::npc_fire_nova_totemAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), NpcSpellClick_npc_crystalline_ice_giant(), NpcSpellClick_npc_descent_madness(), NpcSpellClick_npc_scalawag_frog(), PossessionTransfer::OnApply(), instance_blackrock_depths::OnCreatureCreate(), instance_serpentshrine_cavern::OnCreatureCreate(), instance_eye_of_eternity::OnCreatureDeath(), instance_arcatraz::OnCreatureDeath(), instance_zulaman::OnCreatureEvade(), world_map_outland::OnCreatureEvade(), instance_blackrock_spire::OnCreatureEvade(), instance_sunwell_plateau::OnCreatureEvade(), instance_ahnkahet::OnCreatureEvade(), instance_karazhan::OnCreatureRespawn(), instance_black_temple::OnCreatureRespawn(), spell_slave_trigger_closest::OnEffectExecute(), spell_devour_humanoid::OnEffectExecute(), spell_light_ball_passive::OnEffectExecute(), spell_dark_ball_passive::OnEffectExecute(), spell_out_cold::OnEffectExecute(), spell_assemble_cage::OnEffectExecute(), spell_ooze_combine::OnEffectExecute(), KoiKoiDeath::OnEffectExecute(), LightwellRelay::OnEffectExecute(), npc_anubarak_trial_spikeAI::PermafrostHit(), CreatureEventAI::ProcessAction(), CreatureLinkingHolder::ProcessSlave(), boss_malacrassAI::ReceiveAIEvent(), boss_illidan_stormrageAI::ReceiveAIEvent(), MouthAI::ReceiveAIEvent(), mob_pure_energyAI::ReceiveAIEvent(), npc_ice_spear_bunnyAI::ReceiveAIEvent(), npc_scrap_reaverAI::ReceiveAIEvent(), boss_ossirianAI::ReceiveAIEvent(), npc_emilyAI::ReceiveAIEvent(), npc_arcane_beamAI::Reset(), npc_floating_spiritAI::Reset(), npc_healthy_sporeAI::Reset(), npc_rocket_strikeAI::Reset(), npc_manaforge_control_consoleAI::ResetControlConsoleAndDespawn(), instance_blackrock_spire::SetData(), instance_scarlet_monastery::SetData(), npc_ranshallaAI::SpellHit(), npc_saplingAI::SpellHit(), npc_buru_eggAI::SpellHit(), npc_frostbiteAI::SpellHit(), npc_rabid_bearAI::SpellHit(), npc_injured_patientAI::SpellHit(), NecropolisRelayAI::SpellHitTarget(), NecropolisProxyAI::SpellHitTarget(), NecropolisHealthAI::SpellHitTarget(), npc_time_riftAI::SummonedCreatureDespawn(), npc_teleportation_portalAI::SummonedCreatureDespawn(), mob_phoenix_tkAI::SummonedCreatureJustDied(), npc_time_riftAI::SummonedCreatureJustDied(), npc_beast_combat_stalkerAI::SummonedCreatureJustDied(), npc_putricides_trapAI::SummonedCreatureJustDied(), npc_teleportation_portalAI::SummonedCreatureJustDied(), npc_soulgrinderAI::SummonedCreatureJustDied(), boss_fankrissAI::SummonedCreatureJustDied(), npc_ethereal_frostworgAI::SummonedCreatureJustDied(), boss_maexxnaAI::SummonedJustReachedHome(), npc_eris_havenfireAI::SummonedMovementInform(), npc_image_of_medivhAI::SummonedMovementInform(), npc_anachronos_the_ancientAI::SummonedMovementInform(), boss_varosAI::SummonedMovementInform(), npc_kiljaeden_controllerAI::SummonedMovementInform(), boss_viscidusAI::SummonedMovementInform(), boss_illidan_stormrageAI::SummonedMovementInform(), boss_reliquary_of_soulsAI::SummonedMovementInform(), npc_totem_of_spiritsAI::SummonedMovementInform(), npc_simone_the_inconspicuousAI::Transform(), Aura::TriggerSpell(), npc_escortAI::UpdateAI(), FollowerAI::UpdateAI(), boss_eranikusAI::UpdateAI(), boss_highlord_kruulAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_eris_havenfireAI::UpdateAI(), npc_infused_crystalAI::UpdateAI(), npc_eye_of_acherusAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), mobs_spectral_ghostly_citizenAI::UpdateAI(), mobs_spitelashesAI::UpdateAI(), boss_mawsAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), npc_rabid_bearAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), npc_impale_targetAI::UpdateAI(), npc_seaforium_depth_chargeAI::UpdateAI(), mob_frost_bombAI::UpdateAI(), npc_planar_anomalyAI::UpdateAI(), npc_tenebron_egg_controllerAI::UpdateAI(), boss_freyaAI::UpdateAI(), npc_nature_bombAI::UpdateAI(), boss_hodirAI::UpdateAI(), npc_proximity_mineAI::UpdateAI(), npc_frost_bombAI::UpdateAI(), npc_annhyldeAI::UpdateAI(), mob_omrogg_headsAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), npc_living_flareAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_injured_patientAI::UpdateAI(), npc_the_cleanerAI::UpdateAI(), npc_mage_mirror_imageAI::UpdateAI(), npc_grandmotherAI::UpdateAI(), npc_warlock_mount_ritualAI::UpdateAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_rinjiAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_kernobeeAI::UpdateFollowerAI(), npc_scrap_reaverAI::UpdateTimers(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_ranger_lilathaAI::WaypointReached(), npc_kayra_longmaneAI::WaypointReached(), npc_shadowfang_prisonerAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_ruul_snowhoofAI::WaypointReached(), npc_captured_sprite_darterAI::WaypointReached(), npc_prospector_anvilwardAI::WaypointReached(), npc_miranAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_injured_minerAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), and npc_skyguard_prisonerAI::WaypointReached().
GetAIName()
std::string Creature::GetAIName () const
Definition at line 2482 of file Creature.cpp.
References CreatureInfo::AIName, ObjectMgr::GetCreatureTemplate(), and Object::GetEntry().
Referenced by ScriptedAI::GetAIName(), ChatHandler::HandleNpcAIInfoCommand(), CreatureEventAI::Permissible(), and FactorySelector::selectAI().
GetCharmSpells()
std::vector< uint32 > Creature::GetCharmSpells () const virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 1528 of file Creature.cpp.
References CREATURE_MAX_SPELLS, m_spellList, and CreatureSpellList::Spells.
Referenced by Pet::GetCharmSpells().
GetCombatData()
virtual CombatData* Creature::GetCombatData () inline override virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 638 of file Creature.h.
References CharmInfo::GetCombatData(), Unit::m_charmInfo, and Unit::m_combatData.
GetCombatStartPosition() [1/2]
Position const& Creature::GetCombatStartPosition () const inline
Definition at line 778 of file Creature.h.
References m_combatStartPos.
GetCombatStartPosition() [2/2]
void Creature::GetCombatStartPosition (Position & pos) const inline
Definition at line 777 of file Creature.h.
References m_combatStartPos.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), boss_archimondeAI::CheckLeash(), boss_hydross_the_unstableAI::CheckTransition(), FollowerAI::EnterEvadeMode(), Unit::SetInCombatState(), Unit::TakeCharmOf(), Unit::TakePossessOf(), and CombatManager::Update().
GetCorpseDecayTimer()
TimePoint Creature::GetCorpseDecayTimer () const inline
Definition at line 586 of file Creature.h.
References m_corpseExpirationTime.
Referenced by ChatHandler::HandleNpcInfoCommand().
GetCreatureAddon()
CreatureDataAddon const * Creature::GetCreatureAddon () const
Definition at line 2229 of file Creature.cpp.
References ObjectMgr::GetCreatureAddon(), GetCreatureInfo(), ObjectMgr::GetCreatureTemplateAddon(), Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), and HIGHGUID_PET.
Referenced by LoadCreatureAddon(), and Unit::SetInCombatState().
GetCreatureConditionalSpawnEntry()
uint32 Creature::GetCreatureConditionalSpawnEntry (uint32 guidlow, Map * map) const protected
Definition at line 2982 of file Creature.cpp.
References ALLIANCE, CreatureConditionalSpawn::EntryAlliance, CreatureConditionalSpawn::EntryHorde, ObjectMgr::GetCreatureConditionalSpawn(), DungeonMap::GetInstanceTeam(), HORDE, and Map::IsDungeon().
Referenced by LoadFromDB().
GetCreatureGroup()
CreatureGroup* Creature::GetCreatureGroup () const inline
Definition at line 870 of file Creature.h.
References m_creatureGroup.
Referenced by CleanupsBeforeDelete(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleNpcGroupInfoCommand(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandleWpShowCommand(), Unit::JustKilledCreature(), LoadFromDB(), npc_cork_gizeltonAI::MakeQuestFailAndClean(), instance_ramparts::OnCreatureRespawn(), SetDeathState(), Update(), npc_escortAI::UpdateAI(), and npc_cork_gizeltonAI::UpdateEscortAI().
GetCreatureInfo()
CreatureInfo const* Creature::GetCreatureInfo () const inline
Definition at line 680 of file Creature.h.
References m_creatureInfo.
Referenced by PlayerbotAI::_HandleCommandGet(), PlayerbotAI::AddAuction(), AddCooldown(), AddToWorld(), boss_moamAI::Aggro(), npc_escortAI::AssistPlayerInCombat(), FollowerAI::AssistPlayerInCombat(), Player::BuildPetTalentsInfoData(), CallAssistance(), CallForHelp(), CanFly(), Unit::CanInteract(), Unit::CanInteractNow(), CanSwim(), CanTrainAndResetTalentsOf(), CanWalk(), Spell::CheckCast(), WorldSession::CheckMailBox(), ClearTemporaryFaction(), Totem::Create(), Pet::CreateBaseAtCreature(), CreatureAI::CreatureAI(), Unit::DealMeleeDamage(), PlayerbotAI::DoLoot(), PlayerbotRogueAI::DoNextCombatManeuver(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), EffectAuraDummy_npc_oil_stained_wolf(), Spell::EffectDummy(), Spell::EffectSkinning(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::findNearbyCorpse(), PlayerbotAI::findNearbyCreature(), MaNGOS::XP::Gain(), GargoyleDeathKnightAI::GargoyleDeathKnightAI(), GetCreatureAddon(), GetPursuit(), GetSubName(), GetTrainerTemplateSpells(), GetVendorTemplateItems(), GossipHello_npc_field_marshal_afrasiabi(), GossipHello_npc_high_overlord_saurfang(), GossipHello_npc_major_mattingly(), GossipHello_npc_overlord_runthalak(), Aura::HandleAuraTransform(), PlayerbotAI::HandleBotOutgoingPacket(), ChatHandler::HandleDebugLootDropStats(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), PlayerbotMgr::HandleMasterIncomingPacket(), ChatHandler::HandleNpcFactionIdCommand(), ChatHandler::HandleNpcInfoCommand(), boss_telestraAI::HandlePersonalityMerge(), Pet::HaveInDiet(), InitEntry(), Pet::InitLevelupSpellsForLevel(), Pet::InitStatsForLevel(), IsCivilian(), IsElite(), IsGuard(), IsImmuneToDamage(), IsImmuneToSpell(), IsImmuneToSpellEffect(), IsNoAggroOnSight(), IsRacialLeader(), IsRegeneratingHealth(), IsRegeneratingPower(), IsTrainerOf(), IsVisibleInGridForPlayer(), IsWorldBoss(), Unit::JustKilledCreature(), boss_telestraAI::JustReachedHome(), Pet::LearnPetPassives(), Player::LearnPetTalent(), Pet::LoadPetFromDB(), LockOutSpells(), Loot::Loot(), DeepFreezeImmunityState::OnCheckProc(), Player::PetSpellInitialize(), Player::PrepareGossipMenu(), boss_moorabiAI::Reset(), npc_supplicantAI::ResetOgreState(), Pet::resetTalents(), Unit::RestoreOriginalFaction(), RewardGroupAtKill_helper(), Player::RewardReputation(), Player::RewardSinglePlayerAtKill(), SaveToDB(), SelectLevel(), FactorySelector::selectMovementGenerator(), WorldSession::SendTrainerList(), npc_aoe_damage_triggerAI::SetAuraPassive(), SetDeathState(), ScriptedAI::SetEquipmentSlots(), Unit::SetInCombatState(), Aura::TriggerSpell(), CombatManager::Update(), generic_creatureAI::UpdateAI(), UpdateEntry(), and UpdateImmunitiesSet().
GetCurrentEquipmentId()
uint32 Creature::GetCurrentEquipmentId () const inline
Definition at line 666 of file Creature.h.
References m_equipmentId.
GetDefaultGossipMenuId()
uint32 Creature::GetDefaultGossipMenuId () const inline
Definition at line 762 of file Creature.h.
References m_gossipMenuId.
Referenced by WorldSession::HandleGossipHelloOpcode(), and WorldSession::HandleQuestgiverHelloOpcode().
GetDefaultMovementType()
MovementGeneratorType Creature::GetDefaultMovementType () const inline
Definition at line 729 of file Creature.h.
References m_defaultMovementType.
Referenced by npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), SaveToDB(), and FactorySelector::selectMovementGenerator().
GetDetectionRange()
uint32 Creature::GetDetectionRange () const inline override virtual
Reimplemented from Unit.
Definition at line 812 of file Creature.h.
References m_detectionRange.
Referenced by Heartbeat(), and GreaterInvisibilityMob::OnPeriodicTickEnd().
GetDuration()
virtual uint32 Creature::GetDuration () const inline virtual
Reimplemented in TemporarySpawn, and Pet.
Definition at line 883 of file Creature.h.
Referenced by Player::CharmSpellInitialize(), and Player::VehicleSpellInitialize().
GetEquipmentId()
uint32 Creature::GetEquipmentId () const inline
Definition at line 569 of file Creature.h.
References m_equipmentId.
GetForceAttackingCapability()
bool Creature::GetForceAttackingCapability () const inline
Definition at line 808 of file Creature.h.
References m_forceAttackingCapability.
GetGridRef()
GridReference<Creature>& Creature::GetGridRef () inline
Definition at line 765 of file Creature.h.
References m_gridRef.
GetGroupLootRecipient()
Group * Creature::GetGroupLootRecipient () const
Return group if player tap creature as group member, independent is player after leave group or stil be group member.
Definition at line 1130 of file Creature.cpp.
References m_lootGroupRecipientId, and sObjectMgr.
Referenced by GetLootRecipient().
GetInteractionPauseTimer()
uint32 Creature::GetInteractionPauseTimer () const inline
Definition at line 763 of file Creature.h.
References m_interactionPauseTimer.
Referenced by WorldSession::HandleBattlemasterHelloOpcode(), WorldSession::HandleGossipHelloOpcode(), WorldSession::HandleQuestgiverHelloOpcode(), and WorldSession::SendListInventory().
GetKillerGuid()
ObjectGuid Creature::GetKillerGuid () const inline
Definition at line 880 of file Creature.h.
References m_killer.
Referenced by TribalDeath::OnEffectExecute().
GetLevelForTarget()
uint32 Creature::GetLevelForTarget (Unit const * target) const override virtual
Reimplemented from Unit.
Definition at line 2469 of file Creature.cpp.
References CONFIG_UINT32_WORLD_BOSS_LEVEL_DIFF, Unit::GetLevel(), Unit::GetLevelForTarget(), IsWorldBoss(), and sWorld.
GetLootGroupRecipientId()
uint32 Creature::GetLootGroupRecipientId () const inline
Definition at line 707 of file Creature.h.
References m_lootGroupRecipientId.
Referenced by ChatHandler::HandleDebugGetLootRecipientCommand().
GetLootRecipient()
Player * Creature::GetLootRecipient () const
Return player who can loot tapped creature (member of group or single player)
In case when original player tap creature as group member then group tap prefered. This is for example important if player after tap leave group. If group not exist or disbanded or player tap creature not as group member return player
Definition at line 1143 of file Creature.cpp.
References Group::GetFirstMember(), Player::GetGroup(), GetGroupLootRecipient(), GetOriginalLootRecipient(), and GroupReference::next().
Referenced by EffectDummyCreature_spell_dummy_npc(), CreatureEventAI::GetTargetByType(), ChatHandler::HandleDebugGetLootRecipientCommand(), IsTappedBy(), PrepareBodyLootState(), and CreatureEventAI::ProcessAction().
GetLootRecipientGuid()
ObjectGuid Creature::GetLootRecipientGuid () const inline
Definition at line 706 of file Creature.h.
References m_lootRecipientGuid.
Referenced by ChatHandler::HandleDebugGetLootRecipientCommand().
GetLootStatus()
CreatureLootStatus Creature::GetLootStatus () const inline
Definition at line 702 of file Creature.h.
References m_lootStatus.
Referenced by Spell::CheckCast(), Spell::EffectPickPocket(), and PlayerbotAI::HandleBotOutgoingPacket().
GetNameForLocaleIdx()
const char * Creature::GetNameForLocaleIdx (int32 loc_idx) const override virtual
Reimplemented from WorldObject.
Reimplemented in Pet.
Definition at line 2592 of file Creature.cpp.
References Object::GetEntry(), WorldObject::GetName(), and sObjectMgr.
Referenced by Pet::CreateBaseAtCreature().
GetOriginalLootRecipient()
Player * Creature::GetOriginalLootRecipient () const
Return original player who tap creature, it can be different from player/group allowed to loot so not use it for loot code.
Definition at line 1122 of file Creature.cpp.
References ObjectAccessor::FindPlayer(), and m_lootRecipientGuid.
Referenced by GetLootRecipient(), and CreatureEventAI::GetTargetByType().
GetParentHigh()
HighGuid Creature::GetParentHigh () const inline override virtual
Reimplemented from WorldObject.
Definition at line 853 of file Creature.h.
References HIGHGUID_UNIT.
GetPetAutoSpellOnPos()
virtual uint32 Creature::GetPetAutoSpellOnPos (uint8 pos) const inline virtual
Reimplemented in Pet.
Definition at line 769 of file Creature.h.
References ACT_ENABLED, CREATURE_MAX_SPELLS, UnitActionBarEntry::GetAction(), CharmInfo::GetCharmSpell(), UnitActionBarEntry::GetType(), and Unit::m_charmInfo.
Referenced by PetAI::UpdateAI().
GetPetAutoSpellSize()
virtual uint8 Creature::GetPetAutoSpellSize () const inline virtual
Reimplemented in Pet.
Definition at line 768 of file Creature.h.
References CREATURE_MAX_SPELLS.
Referenced by PetAI::UpdateAI().
GetPursuit()
uint32 Creature::GetPursuit () const inline override virtual
Reimplemented from Unit.
Definition at line 779 of file Creature.h.
References GetCreatureInfo(), and CreatureInfo::Pursuit.
getRace()
uint8 Creature::getRace () const override virtual
Reimplemented from Unit.
Definition at line 2355 of file Creature.cpp.
References GetCreatureModelRace(), Unit::GetNativeDisplayId(), and Unit::getRace().
Referenced by WorldSession::HandleGetMirrorimageData().
GetRespawnCoord()
void Creature::GetRespawnCoord (float & x, float & y, float & z, float * ori = nullptr, float * dist = nullptr) const
Definition at line 2439 of file Creature.cpp.
References GetRespawnRadius(), MaNGOS::IsValidMapCoord(), m_respawnPos, MANGOS_ASSERT, Position::o, WorldObject::PrintCoordinatesError(), Position::x, Position::y, and Position::z.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), Map::AddToActive(), boss_heiganAI::boss_heiganAI(), CreatureLinkingHolder::CanSpawn(), Map::CreatureRespawnRelocation(), npc_apexis_flayerAI::CrystalStrike(), instance_draktharon_keep::DoSortNovosDummies(), instance_blackfathom_deeps::DoSpawnMobs(), boss_jeklikAI::EnterEvadeMode(), ScriptAction::ExecuteDbscriptCommand(), world_map_outland::HandleBashirMobDeath(), OutdoorPvPNA::HandleCreatureDeath(), Aura::HandleModPossess(), CreatureLinkingHolder::IsSlaveInRangeOfMaster(), boss_viscidusAI::JustSummoned(), npc_commanderAI::MovementInform(), npc_commanderAI::npc_commanderAI(), instance_trial_of_the_champion::OnCreatureDespawn(), CreatureEventAI::ProcessAction(), RemoveCorpse(), Map::RemoveFromActive(), npc_warp_gate::Reset(), CreatureLinkingHolder::SetFollowing(), FormationData::SetFormationSlot(), npc_lazy_peonAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_savianaAI::UpdateAI(), npc_dark_matterAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), ObjectGridRespawnMover::Visit(), and WanderMovementGenerator::WanderMovementGenerator().
GetRespawnDelay()
uint32 Creature::GetRespawnDelay () const inline
Definition at line 744 of file Creature.h.
References m_respawnDelay.
Referenced by npc_the_scourge_cauldronAI::DoDie(), ChatHandler::HandleNpcInfoCommand(), instance_shattered_halls::OnCreatureRespawn(), CreatureLinkingHolder::ProcessSlave(), and PoolGroup< T >::Spawn1Object().
GetRespawnPosition()
Position const& Creature::GetRespawnPosition () const inline
Definition at line 784 of file Creature.h.
References m_respawnPos.
Referenced by boss_felblood_kaelthasAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), boss_felblood_kaelthasAI::HandleGravityLapse(), boss_felblood_kaelthasAI::HandleOutro(), CreatureGroup::MoveHome(), world_map_outland::OnCreatureRespawn(), npc_theramore_spar_controller::SwitchMembers(), NecropolisAI::UpdateAI(), NecropolisProxyAI::UpdateAI(), and NecropolisRelayAI::UpdateAI().
GetRespawnRadius()
float Creature::GetRespawnRadius () const inline
Definition at line 747 of file Creature.h.
References m_respawnradius.
Referenced by GetRespawnCoord(), and ChatHandler::HandleNpcSpawnDistCommand().
GetRespawnTime()
time_t const& Creature::GetRespawnTime () const inline
Definition at line 738 of file Creature.h.
References m_respawnTime.
Referenced by CreatureLinkingHolder::ProcessSlave().
GetRespawnTimeEx()
time_t Creature::GetRespawnTimeEx () const
Definition at line 2429 of file Creature.cpp.
References IsCorpseExpired(), m_corpseExpirationTime, and m_respawnTime.
Referenced by ChatHandler::HandleNpcInfoCommand().
GetScriptId()
uint32 Creature::GetScriptId () const
Definition at line 2492 of file Creature.cpp.
References ObjectMgr::GetCreatureTemplate(), Object::GetEntry(), and CreatureInfo::ScriptID.
Referenced by ScriptDevAIMgr::GetCreatureAI(), ScriptDevAIMgr::GetDialogStatus(), GetScriptName(), ScriptDevAIMgr::OnEffectDummy(), ScriptDevAIMgr::OnEffectScriptEffect(), ScriptDevAIMgr::OnGossipHello(), ScriptDevAIMgr::OnGossipSelect(), ScriptDevAIMgr::OnNpcSpellClick(), ScriptDevAIMgr::OnQuestAccept(), and ScriptDevAIMgr::OnQuestRewarded().
GetScriptName()
std::string Creature::GetScriptName () const
Definition at line 2487 of file Creature.cpp.
References GetScriptId(), and sScriptDevAIMgr.
Referenced by ChatHandler::HandleNpcAIInfoCommand(), ChatHandler::HandleWpShowCommand(), and npc_escortAI::Start().
GetSettings() [1/2]
CreatureSettings& Creature::GetSettings () inline
Definition at line 873 of file Creature.h.
References m_settings.
GetSettings() [2/2]
CreatureSettings const& Creature::GetSettings () const inline
Definition at line 872 of file Creature.h.
References m_settings.
Referenced by AIM_Initialize(), CreatureAI::CreatureAI(), CreatureAI::DamageTaken(), CreatureAI::EnterCombat(), CreatureAI::SetDeathPrevention(), and SetDeathState().
GetShieldBlockValue()
uint32 Creature::GetShieldBlockValue () const inline override virtual
Implements Unit.
Definition at line 647 of file Creature.h.
References Unit::GetLevel(), Unit::GetStat(), and STAT_STRENGTH.
GetSpellCooldown()
Creature::CooldownResult Creature::GetSpellCooldown (uint32 spellId, uint32 & cooldown) const
Definition at line 1536 of file Creature.cpp.
References COOLDOWN_RESULT_CATEGORY_FOUND, COOLDOWN_RESULT_FOUND, COOLDOWN_RESULT_NOT_FOUND, m_spellList, SPELL_LIST_FLAG_CATEGORY_COOLDOWN, CreatureSpellList::Spells, and urand().
Referenced by AddCooldown().
GetSpellList()
CreatureSpellList const& Creature::GetSpellList () const inline
Definition at line 858 of file Creature.h.
References m_spellList.
Referenced by CreatureAI::GetSpellList(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandleNpcListSpells(), and Pet::InitializeSpellsForControllableGuardian().
GetSubName()
char const* Creature::GetSubName () const inline
Definition at line 564 of file Creature.h.
References GetCreatureInfo(), and CreatureInfo::SubName.
GetSubtype()
CreatureSubtype Creature::GetSubtype () const inline
Definition at line 571 of file Creature.h.
References m_subtype.
Referenced by AddToWorld(), ChatHandler::HandleNpcDeleteCommand(), ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), and RemoveFromWorld().
GetTemporaryFactionFlags()
uint32 Creature::GetTemporaryFactionFlags () const inline
Definition at line 789 of file Creature.h.
References m_temporaryFactionFlags.
Referenced by HomeMovementGenerator< Creature >::Finalize(), and SetDeathState().
GetTrainerSpells()
TrainerSpellData const * Creature::GetTrainerSpells () const
Definition at line 2586 of file Creature.cpp.
References Object::GetEntry(), and sObjectMgr.
Referenced by PlayerbotAI::_HandleCommandSkill(), WorldSession::HandleTrainerBuySpellOpcode(), IsTrainerOf(), and WorldSession::SendTrainerList().
GetTrainerTemplateSpells()
TrainerSpellData const * Creature::GetTrainerTemplateSpells () const
Definition at line 2580 of file Creature.cpp.
References GetCreatureInfo(), sObjectMgr, and CreatureInfo::TrainerTemplateId.
Referenced by PlayerbotAI::_HandleCommandSkill(), WorldSession::HandleTrainerBuySpellOpcode(), IsTrainerOf(), and WorldSession::SendTrainerList().
GetVendorItemCurrentCount()
uint32 Creature::GetVendorItemCurrentCount (VendorItem const * vItem)
Definition at line 2508 of file Creature.cpp.
References ItemPrototype::BuyCount, VendorItemCount::count, ObjectMgr::GetItemPrototype(), VendorItem::incrtime, VendorItem::item, VendorItemCount::lastIncrementTime, m_vendorItemCounts, and VendorItem::maxcount.
Referenced by Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
GetVendorItems()
VendorItemData const * Creature::GetVendorItems () const
Definition at line 2497 of file Creature.cpp.
References Object::GetEntry(), and sObjectMgr.
Referenced by PlayerbotAI::Buy(), Player::BuyItemFromVendorSlot(), Player::PrepareGossipMenu(), and WorldSession::SendListInventory().
GetVendorTemplateItems()
VendorItemData const * Creature::GetVendorTemplateItems () const
Definition at line 2502 of file Creature.cpp.
References GetCreatureInfo(), sObjectMgr, and CreatureInfo::VendorTemplateId.
Referenced by PlayerbotAI::Buy(), Player::BuyItemFromVendorSlot(), Player::PrepareGossipMenu(), and WorldSession::SendListInventory().
HasBeenHitBySpell()
bool Creature::HasBeenHitBySpell (uint32 spellId)
Definition at line 3026 of file Creature.cpp.
References m_hitBySpells.
Referenced by Spell::OnCheckCast(), TagGreaterFelfireDiemetradon::OnCheckCast(), BurnBody::OnCheckCast(), UseBricksBonesaw::OnCheckCast(), and RaiseDead::OnCheckTarget().
HasInvolvedQuest()
bool Creature::HasInvolvedQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1786 of file Creature.cpp.
References Object::GetEntry(), and sObjectMgr.
HasLootRecipient()
bool Creature::HasLootRecipient () const inline
Definition at line 712 of file Creature.h.
References m_lootGroupRecipientId, and m_lootRecipientGuid.
Referenced by Spell::EffectDummy(), CreatureEventAI::GetTargetByType(), and ChatHandler::HandleDebugGetLootRecipientCommand().
HasQuest()
bool Creature::HasQuest (uint32 quest_id) const override virtual
Reimplemented from Object.
Definition at line 1775 of file Creature.cpp.
References Object::GetEntry(), and sObjectMgr.
HasSpell()
bool Creature::HasSpell (uint32 spellID) const override virtual
Reimplemented from Unit.
Reimplemented in Pet.
Definition at line 2361 of file Creature.cpp.
References m_spellList, and CreatureSpellList::Spells.
Referenced by Pet::HasSpell().
HasStaticDBSpawnData()
bool Creature::HasStaticDBSpawnData () const
Definition at line 2729 of file Creature.cpp.
References Object::GetDbGuid(), Object::GetObjectGuid(), HIGHGUID_PET, and sObjectMgr.
Referenced by Map::AddToActive(), ChatHandler::HandleNpcChangeLevelCommand(), ChatHandler::HandleNpcSetModelCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcSetPhaseCommand(), ChatHandler::HandleWpAddCommand(), Map::RemoveFromActive(), Respawn(), and SaveRespawnTime().
hasWeapon()
bool Creature::hasWeapon (WeaponAttackType type) const override virtual
Checks if the current Unit has a weapon equipped at the moment.
Returns
True if there is a weapon.
Implements Unit.
Definition at line 2736 of file Creature.cpp.
References Unit::CanDualWield(), ItemEntry::Class, Object::GetUInt32Value(), ITEM_CLASS_WEAPON, OFF_ATTACK, sItemStore, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by hasWeaponForAttack(), ScriptedAI::SetEquipmentSlots(), UpdateDamagePhysical(), and Pet::UpdateDamagePhysical().
hasWeaponForAttack()
bool Creature::hasWeaponForAttack (WeaponAttackType type) const inline override virtual
Checks if the current Unit has a usable weapon at the moment.
Returns
True if there is a weapon.
Reimplemented from Unit.
Definition at line 796 of file Creature.h.
References hasWeapon(), and Unit::hasWeaponForAttack().
Referenced by UpdateDamagePhysical(), and Pet::UpdateDamagePhysical().
Heartbeat()
void Creature::Heartbeat () override virtual
Reimplemented from WorldObject.
Definition at line 3046 of file Creature.cpp.
References CanAggro(), GetDetectionRange(), Unit::Heartbeat(), MAX_CREATURE_ATTACK_RADIUS, and Unit::ScheduleAINotify().
InitEntry()
bool Creature::InitEntry (uint32 Entry, const CreatureData * data = nullptr, GameEventCreatureData const * eventData = nullptr) protected
change the entry of creature until respawn
Definition at line 321 of file Creature.cpp.
References MovementInfo::AddMovementFlag(), ChooseDisplayId(), CLASS_MAGE, CLASS_PALADIN, CLASS_ROGUE, CLASS_WARRIOR, CONFIG_UINT32_CORPSE_DECAY_ELITE, CONFIG_UINT32_CORPSE_DECAY_NORMAL, CONFIG_UINT32_CORPSE_DECAY_RARE, CONFIG_UINT32_CORPSE_DECAY_RAREELITE, CONFIG_UINT32_CORPSE_DECAY_WORLDBOSS, CONFIG_UINT32_INTERACTION_PAUSE_TIMER, CreatureInfo::CorpseDelay, CREATURE_ELITE_ELITE, CREATURE_ELITE_RARE, CREATURE_ELITE_RAREELITE, CREATURE_ELITE_WORLDBOSS, CREATURE_EXTRA_FLAG_DUAL_WIELD_FORCED, CREATURE_EXTRA_FLAG_FORCE_ATTACKING_CAPABILITY, CREATURE_EXTRA_FLAG_NO_BLOCK, CREATURE_EXTRA_FLAG_NO_CALL_ASSIST, CREATURE_EXTRA_FLAG_NO_PARRY, CREATURE_EXTRA_FLAG_WALK_IN_WATER, CreatureInfo::DamageSchool, CreatureInfo::Detection, CreatureInfo::DifficultyEntry, GameEventCreatureData::entry_id, GameEventCreatureData::equipment_id, CreatureSpawnTemplate::equipmentId, CreatureInfo::EquipmentTemplateId, CreatureInfo::ExtraFlags, CreatureModelInfo::gender, Unit::GetCollisionHeight(), GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), Object::GetEntry(), WorldObject::GetMap(), WorldObject::GetMapId(), GetPrevDifficulty(), WorldObject::GetTerrain(), CreatureInfo::HoverHeight, INHABIT_AIR, INHABIT_WATER, CreatureInfo::InhabitType, CreatureInfo::InteractionPauseTimer, CreatureSpawnTemplate::IsHovering(), IsPet(), CreatureSpawnTemplate::IsRunning(), LoadEquipment(), m_corpseDelay, m_creatureInfo, m_defaultMovementType, m_interactionPauseTimer, WorldObject::m_movementInfo, m_respawnPos, CreatureModelInfo::modelid, MOVEFLAG_SWIMMING, CreatureInfo::MovementType, CreatureData::movementType, CreatureInfo::Name, POWER_ENERGY, POWER_MANA, POWER_RAGE, CreatureInfo::Rank, REGULAR_DIFFICULTY, CreatureInfo::Scale, Object::SetByteValue(), Unit::SetCanBlock(), SetCanCallForAssistance(), SetCanDualWield(), Unit::SetCanParry(), SetCorpseDelay(), SetDetectionRange(), Unit::SetDisplayId(), Object::SetEntry(), Object::SetFloatValue(), SetForceAttackingCapability(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetMeleeDamageSchool(), WorldObject::SetName(), Unit::SetNativeDisplayId(), SetNoReputation(), Object::SetObjectScale(), Unit::SetPowerType(), SetWalk(), sLog, sObjectMgr, CreatureData::spawnTemplate, sWorld, UNIT_BYTES_0_OFFSET_CLASS, UNIT_BYTES_0_OFFSET_GENDER, UNIT_BYTES_0_OFFSET_RACE, UNIT_FIELD_BYTES_0, UNIT_FIELD_HOVERHEIGHT, UNIT_MOD_CAST_SPEED, CreatureInfo::UnitClass, Position::x, Position::y, and Position::z.
Referenced by Pet::Create(), and UpdateEntry().
InspectingLoot()
void Creature::InspectingLoot () override virtual
Reimplemented from WorldObject.
Definition at line 2768 of file Creature.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), m_corpseAccelerationDecayDelay, and m_corpseExpirationTime.
IsCivilian()
bool Creature::IsCivilian () const inline
Definition at line 590 of file Creature.h.
References CREATURE_EXTRA_FLAG_CIVILIAN, and GetCreatureInfo().
Referenced by CreatureAI::AttackStart(), and CreatureAI::EnterCombat().
IsCorpse()
bool Creature::IsCorpse () const inline
Definition at line 582 of file Creature.h.
References CORPSE, and Unit::GetDeathState().
Referenced by CreatureLinkingHolder::DoCreatureLinkingEvent(), EffectDummyCreature_spell_dummy_npc(), PlayerbotAI::findNearbyCorpse(), MaNGOS::NearestCreatureEntryWithLiveStateInObjectRangeCheck::operator()(), MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::operator()(), CreatureLinkingHolder::ProcessSlaveGuidList(), and TemporarySpawn::Update().
IsCorpseExpired()
bool Creature::IsCorpseExpired () const protected
Definition at line 2962 of file Creature.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), and m_corpseExpirationTime.
Referenced by GetRespawnTimeEx(), IsVisibleInGridForPlayer(), SaveRespawnTime(), Update(), and Pet::Update().
IsCritter()
bool Creature::IsCritter () const inline
Definition at line 575 of file Creature.h.
References CREATURE_TYPE_CRITTER, CreatureInfo::CreatureType, and m_creatureInfo.
Referenced by MaNGOS::XP::Gain(), GameobjectCallForHelpOnUsage::OnSuccessfulStart(), Unit::SelectRandomUnfriendlyTarget(), and UpdateEntry().
IsDespawned()
bool Creature::IsDespawned () const inline
Definition at line 583 of file Creature.h.
References DEAD, and Unit::GetDeathState().
Referenced by PlayerbotAI::DoLoot(), PlayerbotAI::findNearbyCorpse(), ForcedDespawn(), Pet::ForcedDespawn(), CreatureLinkingHolder::ProcessSlave(), Respawn(), and TemporarySpawn::Update().
IsElite()
bool Creature::IsElite () const inline
Definition at line 609 of file Creature.h.
References CREATURE_ELITE_NORMAL, CREATURE_ELITE_RARE, GetCreatureInfo(), IsPet(), and CreatureInfo::Rank.
Referenced by Spell::EffectSkinning(), and MaNGOS::XP::Gain().
IsFlying()
bool Creature::IsFlying () const inline override virtual
Reimplemented from Unit.
Definition at line 598 of file Creature.h.
References MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, MOVEFLAG_FLYING, MOVEFLAG_HOVER, and MOVEFLAG_LEVITATING.
IsGroupLootRecipient()
bool Creature::IsGroupLootRecipient () const inline
Definition at line 713 of file Creature.h.
References m_lootGroupRecipientId.
IsGuard()
bool Creature::IsGuard () const inline
Definition at line 592 of file Creature.h.
References CREATURE_EXTRA_FLAG_GUARD, and GetCreatureInfo().
Referenced by CreatureAI::CreatureAI(), CreatureAI::EnterCombat(), GuardAI::Permissible(), PetAI::PetAI(), and FactorySelector::selectAI().
IsIgnoringFeignDeath()
bool Creature::IsIgnoringFeignDeath () const virtual
Reimplemented from Unit.
Definition at line 2913 of file Creature.cpp.
References CreatureSettings::HasFlag(), IGNORE_FEIGN_DEATH, and m_settings.
IsIgnoringMMAP()
bool Creature::IsIgnoringMMAP () const inline
Definition at line 803 of file Creature.h.
References m_ignoreMMAP.
IsImmuneToDamage()
bool Creature::IsImmuneToDamage (SpellSchoolMask meleeSchoolMask) override virtual
Reimplemented from Unit.
Definition at line 1977 of file Creature.cpp.
References GetCreatureInfo(), and Unit::IsImmuneToDamage().
IsImmuneToSpell()
bool Creature::IsImmuneToSpell (SpellEntry const * spellInfo, bool castOnSelf, uint8 effectMask, WorldObject const * caster) override virtual
Reimplemented from Unit.
Definition at line 1960 of file Creature.cpp.
References GetCreatureInfo(), Unit::IsImmuneToSpell(), SpellEntry::Mechanic, and SpellEntry::SchoolMask.
Referenced by Spell::CheckCast().
IsImmuneToSpellEffect()
bool Creature::IsImmuneToSpellEffect (SpellEntry const * spellInfo, SpellEffectIndex index, bool castOnSelf) const override virtual
Reimplemented from Unit.
Reimplemented in Totem.
Definition at line 1985 of file Creature.cpp.
References SpellEntry::EffectMechanic, GetCreatureInfo(), and Unit::IsImmuneToSpellEffect().
Referenced by Totem::IsImmuneToSpellEffect().
IsInGroup()
bool Creature::IsInGroup (Unit const * other, bool party, bool ignoreCharms) const override virtual
[Serverside] Group: Extension for creatures, player-controlled defaults to unit, creatures check based on friendliness
Note
Relations API Tier 2
No client counterpart, since client only deals with player-controlled entities
Reimplemented from Unit.
Definition at line 1021 of file Relations.cpp.
References Object::HasFlag(), Unit::IsFriend(), Unit::IsInGroup(), MANGOS_ASSERT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
IsInvisible()
bool Creature::IsInvisible () const inline
Definition at line 800 of file Creature.h.
References m_isInvisible.
Referenced by IsVisibleInGridForPlayer().
IsNoAggroOnSight()
bool Creature::IsNoAggroOnSight () const inline
Definition at line 591 of file Creature.h.
References CREATURE_EXTRA_FLAG_NO_AGGRO_ON_SIGHT, and GetCreatureInfo().
Referenced by CanAssistTo(), CreatureAI::CreatureAI(), CreatureEventAI::JustRespawned(), and CreatureEventAI::Permissible().
IsNoLoot()
bool Creature::IsNoLoot ()
Definition at line 2900 of file Creature.cpp.
References CreatureSettings::HasFlag(), m_settings, and NO_LOOT.
Referenced by PrepareBodyLootState().
IsNoReputation()
bool Creature::IsNoReputation () inline
Definition at line 831 of file Creature.h.
References m_noReputation.
Referenced by Player::RewardReputation().
IsNoWeaponSkillGain()
bool Creature::IsNoWeaponSkillGain () const override virtual
Reimplemented from Unit.
Definition at line 2952 of file Creature.cpp.
References CreatureSettings::HasFlag(), m_settings, and NO_SKILL_GAINS.
IsNoWoundedSlowdown()
bool Creature::IsNoWoundedSlowdown () const
Definition at line 2934 of file Creature.cpp.
References CreatureSettings::HasFlag(), m_settings, and NO_WOUNDED_SLOWDOWN.
Referenced by IsSlowedInCombat().
IsNoXp()
bool Creature::IsNoXp ()
Definition at line 2887 of file Creature.cpp.
References CreatureSettings::HasFlag(), m_settings, and NO_XP.
Referenced by MaNGOS::XP::Gain(), and Player::isHonorOrXPTarget().
IsOnlyVisibleTo()
bool Creature::IsOnlyVisibleTo (ObjectGuid guid) const override virtual
Reimplemented from Unit.
Definition at line 1566 of file Creature.cpp.
References ObjectGuid::IsEmpty(), and m_onlyVisibleTo.
IsPet()
bool Creature::IsPet () const inline
Definition at line 572 of file Creature.h.
References CREATURE_SUBTYPE_PET, and m_subtype.
Referenced by CreatureLinkingHolder::AddMasterToHolder(), Map::AddToActive(), Map::AddToGrid(), Player::BeforeVisibilityDestroy(), CallForHelp(), Unit::CanAttackOnSight(), Unit::CanHaveThreatList(), Spell::CheckCast(), Spell::CheckPetCast(), Spell::EffectDummy(), Spell::EffectSummonType(), MaNGOS::XP::Gain(), Unit::GetChannelObject(), Unit::GetCharm(), Unit::GetCharmer(), Unit::GetCreator(), Unit::GetSpawner(), Unit::GetTarget(), ChatHandler::HandleLevelUpCommand(), Aura::HandleModPossessPet(), ChatHandler::HandleNpcChangeLevelCommand(), ChatHandler::HandleNpcSetModelCommand(), ChatHandler::HandleNpcTameCommand(), WorldSession::HandlePetAbandon(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePetSetAction(), WorldSession::HandlePetSpellAutocastOpcode(), ChatHandler::HandleResetTalentsCommand(), InitEntry(), IsElite(), Player::isHonorOrXPTarget(), IsWorldBoss(), Unit::JustKilledCreature(), spell_dispel_scarlet_ghoul_credit::OnEffectExecute(), MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::operator()(), GuardianAI::Permissible(), PetAI::Permissible(), PetAI::PetAI(), CreatureLinkingHolder::ProcessSlaveGuidList(), RegeneratePower(), Map::RemoveFromActive(), Map::RemoveFromGrid(), Unit::RestoreOriginalFaction(), SaveRespawnTime(), FactorySelector::selectAI(), SelectLevel(), FactorySelector::selectMovementGenerator(), WorldSession::SendPetNameQuery(), Unit::TakePossessOf(), Transport::TeleportTransport(), Unit::Uncharm(), GuardianAI::UpdateAI(), PetAI::UpdateAI(), npc_escortAI::UpdateAI(), and ObjectGridRespawnMover::Visit().
IsPreventingDeath()
bool Creature::IsPreventingDeath () const override virtual
Reimplemented from Unit.
Definition at line 2957 of file Creature.cpp.
References CreatureSettings::HasFlag(), m_settings, and UNKILLABLE.
IsRacialLeader()
bool Creature::IsRacialLeader () const inline
Definition at line 589 of file Creature.h.
References GetCreatureInfo(), and CreatureInfo::RacialLeader.
Referenced by Player::RewardHonor().
IsRegeneratingHealth()
bool Creature::IsRegeneratingHealth () const inline
Definition at line 766 of file Creature.h.
References CREATURE_TYPEFLAGS_SIEGE_WEAPON, CreatureInfo::CreatureTypeFlags, GetCreatureInfo(), and REGEN_FLAG_HEALTH.
Referenced by RegenerateHealth(), and Pet::RegenerateHealth().
IsRegeneratingPower()
bool Creature::IsRegeneratingPower () const
Definition at line 1797 of file Creature.cpp.
References GetCreatureInfo(), Unit::IsInCombat(), REGEN_FLAG_POWER, and REGEN_FLAG_POWER_IN_COMBAT.
Referenced by RegeneratePower(), SelectLevel(), and UpdateEntry().
IsSlowedInCombat()
bool Creature::IsSlowedInCombat () const override virtual
Reimplemented from Unit.
Definition at line 2939 of file Creature.cpp.
References AURA_STATE_HEALTHLESS_20_PERCENT, Unit::HasAuraState(), and IsNoWoundedSlowdown().
IsSwimming()
bool Creature::IsSwimming () const inline
Definition at line 596 of file Creature.h.
References MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, and MOVEFLAG_SWIMMING.
IsTappedBy()
bool Creature::IsTappedBy (Player * plr) const
Definition at line 2826 of file Creature.cpp.
References Player::GetGroup(), and GetLootRecipient().
Referenced by Object::BuildValuesUpdate().
IsTemporarySummon()
bool Creature::IsTemporarySummon () const inline
Definition at line 574 of file Creature.h.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, and m_subtype.
Referenced by FormationData::Add(), boss_felmystAI::boss_felmystAI(), boss_felmystAI::CorpseRemoved(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), HomeMovementGenerator< Creature >::Finalize(), BattlefieldWG::HandleCreatureCreate(), BattleGroundSA::HandleCreatureCreate(), OutdoorPvPGH::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), WorldSession::HandlePetActionHelper(), AbstractWrapperMovementGenerator::Inform(), WaypointMovementGenerator< Creature >::InformAI(), npc_shaheenAI::JustDidDialogueStep(), npc_bone_spikeAI::JustDied(), npc_iron_rootsAI::JustDied(), npc_flash_freezeAI::JustDied(), Unit::JustKilledCreature(), boss_head_of_horsemanAI::JustPreventedDeath(), boss_volazjAI::JustSummoned(), boss_kologarnAI::JustSummoned(), npc_nesingwary_trapperAI::MoveInLineOfSight(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_light_orb_collectorAI::MoveInLineOfSight(), npc_ingvar_throw_dummyAI::MoveInLineOfSight(), AbstractPathMovementGenerator::MovementInform(), PointMovementGenerator::MovementInform(), npc_gurubashi_bat_riderAI::npc_gurubashi_bat_riderAI(), npc_raging_flamesAI::npc_raging_flamesAI(), instance_shadowfang_keep::OnCreatureCreate(), instance_black_temple::OnCreatureCreate(), instance_shattered_halls::OnCreatureCreate(), world_map_outland::OnCreatureCreate(), instance_blackwing_lair::OnCreatureCreate(), world_map_ebon_hold::OnCreatureCreate(), instance_culling_of_stratholme::OnCreatureCreate(), instance_azjol_nerub::OnCreatureCreate(), instance_pit_of_saron::OnCreatureCreate(), instance_icecrown_citadel::OnCreatureCreate(), instance_halls_of_stone::OnCreatureCreate(), instance_violet_hold::OnCreatureCreate(), instance_mechanar::OnCreatureCreate(), instance_blackrock_spire::OnCreatureDeath(), world_map_ebon_hold::OnCreatureDeath(), instance_culling_of_stratholme::OnCreatureDeath(), instance_mount_hyjal::OnCreatureDeath(), world_map_kalimdor::OnCreatureDeath(), instance_ahnkahet::OnCreatureDeath(), instance_pit_of_saron::OnCreatureDeath(), instance_azjol_nerub::OnCreatureEnterCombat(), instance_blackrock_spire::OnCreatureEvade(), instance_sunwell_plateau::OnCreatureRespawn(), instance_pinnacle::OnCreatureRespawn(), world_map_outland::OnCreatureRespawn(), world_map_ebon_hold::OnCreatureRespawn(), instance_pit_of_saron::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), LightwellRelay::OnEffectExecute(), npc_ghoul_feeding_bunnyAI::ReceiveAIEvent(), npc_arcane_beamAI::Reset(), npc_frozen_coreAI::Reset(), FactorySelector::selectAI(), npc_infused_crystalAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), npc_bone_spikeAI::UpdateAI(), npc_power_blue_flightAI::UpdateAI(), and npc_flash_freezeAI::UpdateAI().
IsTotem()
bool Creature::IsTotem () const inline
Definition at line 573 of file Creature.h.
References CREATURE_SUBTYPE_TOTEM, and m_subtype.
Referenced by Unit::CanHaveThreatList(), MaNGOS::XP::Gain(), Unit::GetTotem(), Player::isHonorOrXPTarget(), npc_nagrand_captiveAI::JustSummoned(), TotemAI::Permissible(), Unit::RestoreOriginalFaction(), and FactorySelector::selectAI().
IsTrainerOf()
bool Creature::IsTrainerOf (Player * pPlayer, bool msg) const
Definition at line 952 of file Creature.cpp.
References CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, PlayerMenu::ClearMenus(), Unit::getClass(), GetCreatureInfo(), Object::GetEntry(), Unit::GetFactionTemplateEntry(), Object::GetGUIDLow(), Object::GetObjectGuid(), Player::GetPlayerMenu(), Unit::getRace(), Player::GetReputationRank(), GetTrainerSpells(), GetTrainerTemplateSpells(), Player::HasSpell(), Unit::isTrainer(), RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD, REP_EXALTED, PlayerMenu::SendGossipMenu(), sLog, TrainerSpellData::spellList, TRAINER_TYPE_CLASS, TRAINER_TYPE_MOUNTS, TRAINER_TYPE_PETS, and TRAINER_TYPE_TRADESKILLS.
Referenced by PlayerbotAI::_HandleCommandSkill(), WorldSession::HandleTrainerBuySpellOpcode(), Player::PrepareGossipMenu(), and WorldSession::SendTrainerList().
IsVisibleInGridForPlayer()
bool Creature::IsVisibleInGridForPlayer (Player * pl) const override virtual
Implements Unit.
Definition at line 2096 of file Creature.cpp.
References CONFIG_FLOAT_RATE_CREATURE_AGGRO, CREATURE_TYPEFLAGS_GHOST_VISIBLE, Player::GetCorpse(), GetCreatureInfo(), Object::HasFlag(), Unit::IsAlive(), IsCorpseExpired(), Player::IsGameMaster(), IsInvisible(), WorldObject::IsWithinDistInMap(), PLAYER_FLAGS, PLAYER_FLAGS_GHOST, and sWorld.
IsWorldBoss()
bool Creature::IsWorldBoss () const inline
Definition at line 618 of file Creature.h.
References CREATURE_ELITE_WORLDBOSS, GetCreatureInfo(), IsPet(), and CreatureInfo::Rank.
Referenced by GetLevelForTarget(), RemoveCorpse(), SetDeathState(), PoolGroup< T >::Spawn1Object(), and UpdateEntry().
LoadCreatureAddon()
bool Creature::LoadCreatureAddon (bool reload)
Definition at line 2248 of file Creature.cpp.
References CreatureDataAddon::auras, Unit::CastSpell(), CreatureDataAddon::emote, GetCreatureAddon(), Object::GetEntry(), Object::GetGUIDLow(), WorldObject::GetMap(), GetSpellEntryByDifficulty(), Unit::HasAuraOfDifficulty(), SQLStorage::LookupEntry(), CreatureDataAddon::mount, Unit::Mount(), CreatureDataAddon::pvp_flags, Object::SetByteValue(), Unit::SetLevitate(), Object::SetUInt32Value(), CreatureDataAddon::sheath_state, sLog, SpellEntry::SpellDifficultyId, SPLINEFLAG_FLYING, CreatureDataAddon::splineFlags, sSpellTemplate, CreatureDataAddon::standState, TRIGGERED_OLD_TRIGGERED, UNIT_BYTES_1_OFFSET_STAND_STATE, UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_BYTES_2_OFFSET_SHEATH_STATE, UNIT_FIELD_BYTES_1, UNIT_FIELD_BYTES_2, and UNIT_NPC_EMOTESTATE.
Referenced by Create(), Totem::Create(), mob_yennikuAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), mob_molten_golemAI::EnterEvadeMode(), boss_maievAI::EnterEvadeMode(), npc_magister_aledisAI::EnterEvadeMode(), npc_spawned_oronok_tornheartAI::EnterEvadeMode(), npc_millhouse_manastormAI::EnterEvadeMode(), boss_dalliahAI::EnterEvadeMode(), boss_soccothratesAI::EnterEvadeMode(), HomeMovementGenerator< Creature >::Finalize(), and SetDeathState().
LoadEquipment()
void Creature::LoadEquipment (uint32 equip_entry, bool force = false)
Definition at line 1753 of file Creature.cpp.
References EquipmentInfo::equipentry, m_equipmentId, MAX_VIRTUAL_ITEM_SLOT, SetVirtualItem(), and sObjectMgr.
Referenced by ScriptAction::ExecuteDbscriptCommand(), Aura::HandleAuraTransform(), boss_telestraAI::HandlePersonalityMerge(), InitEntry(), boss_telestraAI::JustReachedHome(), npc_supplicantAI::ResetOgreState(), ScriptedAI::SetEquipmentSlots(), npc_harrison_jones_zaAI::SetHoldState(), WorldObject::SummonCreature(), npc_forest_frogAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), and npc_harrison_jones_zaAI::WaypointReached().
LoadFromDB()
bool Creature::LoadFromDB (uint32 dbGuid, Map * map, uint32 newGuid, uint32 forcedEntry, GenericTransport * transport = nullptr)
Definition at line 1593 of file Creature.cpp.
References Map::Add(), GenericTransport::AddPassenger(), AIM_Initialize(), ALIVE, GenericTransport::CalculatePassengerPosition(), CanFly(), Unit::CastSpell(), CONFIG_UINT32_RABBIT_DAY, Create(), CREATURE_EXTRA_FLAG_DYNGUID, CREATURE_GROUP_EVENT_RESPAWN, DEAD, CreatureLinkingHolder::DoCreatureLinkingEvent(), GameEventCreatureData::entry_id, CreatureInfo::ExtraFlags, Map::GenerateLocalLowGuid(), Map::GetCreature(), GetCreatureConditionalSpawnEntry(), GetCreatureGroup(), Map::GetCreatureLinkingHolder(), MapPersistentState::GetCreatureRespawnTime(), ObjectMgr::GetCreatureTemplate(), CreatureGroup::GetFormationData(), SpawnGroup::GetGuidEntry(), TerrainInfo::GetHeightStatic(), CreatureInfo::GetHighGuid(), WorldObject::GetMap(), Map::GetMapDataContainer(), Map::GetPersistentState(), CreatureData::GetRandomRespawnTime(), SpawnManager::GetSpawnGroup(), MapDataContainer::GetSpawnGroupByGuid(), Map::GetSpawnManager(), WorldObject::GetTerrain(), CreatureData::id, SpawnGroupEntry::Id, Unit::IsAlive(), Map::IsDynguidForced(), WorldObject::IsUsingNewSpawningSystem(), LINKING_EVENT_RESPAWN, m_corpseDelay, m_creatureGroup, Unit::m_deathState, Unit::m_isCreatureLinkingTrigger, Unit::m_isSpawningLinked, WorldObject::m_movementInfo, m_respawnDelay, m_respawnradius, m_respawnTime, Position::o, CreatureData::orientation, CreatureData::phaseMask, CreatureData::posX, CreatureData::posY, CreatureData::posZ, CreatureSpawnTemplate::relayId, WorldObject::Relocate(), MapPersistentState::SaveCreatureRespawnTime(), sCreatureLinkingMgr, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), SetCreatureGroup(), FormationData::SetFormationSlot(), Unit::SetHealth(), SetRespawnCoord(), WorldObject::SetStringId(), MovementInfo::SetTransportPos(), sGameEventMgr, sLog, sObjectMgr, CreatureData::spawndist, CreatureData::spawnTemplate, SpawnGroupEntry::StringId, sWorld, TRIGGERED_OLD_TRIGGERED, CreatureGroup::TriggerLinkingEvent(), TYPEID_UNIT, urand(), Position::x, Position::y, and Position::z.
Referenced by ChatHandler::HandleNpcAddCommand(), SpawnCreatureInMapsWorker::operator()(), PoolGroup< T >::Spawn1Object(), and WorldObject::SpawnCreature().
LockOutSpells()
void Creature::LockOutSpells (SpellSchoolMask schoolMask, uint32 duration) override virtual
Reimplemented from WorldObject.
Definition at line 2872 of file Creature.cpp.
References GetCreatureInfo(), WorldObject::LockOutSpells(), and MECHANIC_SILENCE.
OnEventHappened()
void Creature::OnEventHappened (uint16 eventId, bool activate, bool resume) inline override virtual
Reimplemented from WorldObject.
Definition at line 805 of file Creature.h.
References AI(), and UnitAI::OnEventHappened().
PrepareBodyLootState()
void Creature::PrepareBodyLootState ()
Definition at line 1096 of file Creature.cpp.
References CREATURE_LOOT_STATUS_LOOTED, GetLootRecipient(), Object::HasFlag(), IsNoLoot(), LOOT_CORPSE, Object::m_loot, m_lootStatus, ReduceCorpseDecayTimer(), SetLootStatus(), UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
Referenced by Unit::JustKilledCreature().
ReachWithSpellAttack()
SpellEntry const * Creature::ReachWithSpellAttack (Unit * pVictim)
Definition at line 1993 of file Creature.cpp.
References DIST_CALC_COMBAT_REACH, DIST_CALC_COMBAT_REACH_WITH_MELEE, SpellEntry::Effect, WorldObject::GetDistance(), Unit::GetPower(), GetSpellMaxRange(), GetSpellMinRange(), Object::HasFlag(), SQLStorage::LookupEntry(), m_spellList, SpellEntry::manaCost, POWER_MANA, SpellEntry::PreventionType, SpellEntry::rangeIndex, sLog, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, SPELL_RANGE_IDX_COMBAT, CreatureSpellList::Spells, sSpellRangeStore, sSpellTemplate, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
Referenced by guardAI::Aggro().
ReachWithSpellCure()
SpellEntry const * Creature::ReachWithSpellCure (Unit * pVictim)
Definition at line 2046 of file Creature.cpp.
References DIST_CALC_COMBAT_REACH, DIST_CALC_COMBAT_REACH_WITH_MELEE, SpellEntry::Effect, WorldObject::GetDistance(), Unit::GetPower(), GetSpellMaxRange(), GetSpellMinRange(), Object::HasFlag(), SQLStorage::LookupEntry(), m_spellList, SpellEntry::manaCost, POWER_MANA, SpellEntry::PreventionType, SpellEntry::rangeIndex, sLog, SPELL_EFFECT_HEAL, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, SPELL_RANGE_IDX_COMBAT, CreatureSpellList::Spells, sSpellRangeStore, sSpellTemplate, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, and UNIT_FLAG_SILENCED.
ReduceCorpseDecayTimer()
void Creature::ReduceCorpseDecayTimer ()
Definition at line 2779 of file Creature.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), Object::IsInWorld(), m_corpseAccelerationDecayDelay, and m_corpseExpirationTime.
Referenced by PrepareBodyLootState(), and SetLootStatus().
RegenerateAll()
void Creature::RegenerateAll (uint32 update_diff) virtual
Reimplemented in Pet.
Definition at line 801 of file Creature.cpp.
References Unit::GetCombatManager(), Unit::IsInCombat(), Unit::m_regenTimer, REGEN_TIME_FULL_UNIT, RegenerateHealth(), and RegeneratePower().
Referenced by Update().
RegenerateHealth()
void Creature::RegenerateHealth () protected virtual
Reimplemented in Pet.
Definition at line 877 of file Creature.cpp.
References Unit::GetHealth(), Unit::GetMaxHealth(), Unit::IsPlayerControlled(), IsRegeneratingHealth(), and Unit::ModifyHealth().
Referenced by RegenerateAll().
RegeneratePower()
void Creature::RegeneratePower (float timerMultiplier) protected
Definition at line 815 of file Creature.cpp.
References CONFIG_FLOAT_RATE_POWER_ENERGY, CONFIG_FLOAT_RATE_POWER_FOCUS, CONFIG_FLOAT_RATE_POWER_MANA, Unit::GetAurasByType(), Unit::GetMasterGuid(), Unit::GetMaxPower(), Unit::GetPower(), Unit::GetPowerType(), Unit::GetStat(), Object::HasFlag(), Unit::IsInCombat(), IsPet(), IsRegeneratingPower(), Unit::IsUnderLastManaUseEffect(), Modifier::m_amount, Modifier::m_miscvalue, Unit::ModifyPower(), Unit::OCTRegenMPPerSpirit(), POWER_ENERGY, POWER_FOCUS, POWER_MANA, SPELL_AURA_MOD_POWER_REGEN, SPELL_AURA_MOD_POWER_REGEN_PERCENT, STAT_INTELLECT, sWorld, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by RegenerateAll(), and Pet::RegenerateAll().
RegisterHitBySpell()
void Creature::RegisterHitBySpell (uint32 spellId)
Definition at line 3031 of file Creature.cpp.
References m_hitBySpells.
RemoveCorpse()
void Creature::RemoveCorpse (bool inPlace = false)
Definition at line 263 of file Creature.cpp.
References WorldObject::AddObjectToRemoveList(), AI(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, CORPSE, UnitAI::CorpseRemoved(), CREATURE_LOOT_STATUS_NONE, Map::CreatureRelocation(), DEAD, DEBUG_FILTER_LOG, CreatureLinkingHolder::DoCreatureLinkingEvent(), Map::GetCreatureLinkingHolder(), Unit::GetDeathState(), Object::GetGuidStr(), WorldObject::GetInstanceData(), WorldObject::GetMap(), GetRespawnCoord(), Unit::GetVisibility(), Unit::InterruptMoving(), Object::IsInWorld(), WorldObject::IsUsingNewSpawningSystem(), IsWorldBoss(), LINKING_EVENT_DESPAWN, LOG_FILTER_AI_AND_MOVEGENSS, m_corpseExpirationTime, Unit::m_isCreatureLinkingTrigger, Object::m_loot, m_lootStatus, m_respawnTime, SaveRespawnTime(), SetDeathState(), Unit::SetVisibility(), sWorld, WorldObject::UpdateObjectVisibility(), and VISIBILITY_REMOVE_CORPSE.
Referenced by ForcedDespawn(), Pet::ForcedDespawn(), Respawn(), and Update().
RemoveFromWorld()
void Creature::RemoveFromWorld () override virtual
Remove the creature from the accessor
Reimplemented from WorldObject.
Reimplemented in Pet.
Definition at line 204 of file Creature.cpp.
References AI(), ClearCreatureGroup(), CREATURE_SUBTYPE_PET, CREATURE_SUBTYPE_TEMPORARY_SUMMON, TypeUnorderedMapContainer< OBJECT_TYPES, KEY_TYPE >::erase(), Unit::GetCreatedBySpellId(), Object::GetDbGuid(), Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetObjectsStore(), Unit::GetOwner(), Unit::GetSpawner(), GetSubtype(), Map::GetTempCreatures(), Map::GetTempPets(), Object::GetUInt32Value(), Object::IsInWorld(), m_countSpawns, UnitAI::RelinquishFollow(), Map::RemoveDbGuidObject(), Map::RemoveFromSpawnCount(), Unit::RemoveFromWorld(), StartCooldown(), and UNIT_CREATED_BY_SPELL.
Referenced by npc_simone_seductressAI::DemonDespawn(), WorldState::SummonMouth(), and WorldState::SummonPallid().
ResetEntry()
void Creature::ResetEntry (bool respawn = false)
Definition at line 635 of file Creature.cpp.
References AIM_Initialize(), Object::GetDbGuid(), ObjectGuid::GetHigh(), WorldObject::GetMap(), Object::GetObjectGuid(), HIGHGUID_PET, m_originalEntry, CreatureSpawnTemplate::relayId, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), sGameEventMgr, sObjectMgr, CreatureData::spawnTemplate, and UpdateEntry().
Referenced by SetDeathState().
ResetRespawnCoord()
void Creature::ResetRespawnCoord ()
Definition at line 2455 of file Creature.cpp.
References Object::GetDbGuid(), Object::GetObjectGuid(), HIGHGUID_PET, m_respawnPos, Position::o, sObjectMgr, Position::x, Position::y, and Position::z.
ResetSpellHitCounter()
void Creature::ResetSpellHitCounter ()
Definition at line 3041 of file Creature.cpp.
References m_hitBySpells.
Referenced by SetDeathState().
Respawn()
void Creature::Respawn ()
Definition at line 1925 of file Creature.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Map::GetPersistentState(), HasStaticDBSpawnData(), IsDespawned(), Object::IsInWorld(), m_respawnTime, RemoveCorpse(), and MapPersistentState::SaveCreatureRespawnTime().
Referenced by BattleGround::ChangeBgCreatureSpawnState(), CreatureLinkingHolder::DoCreatureLinkingEvent(), npc_daphne_stilwellAI::DoEndEscort(), boss_kelidan_the_breakerAI::DoSetupAdds(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcSpawnDistCommand(), ChatHandler::HandleRespawnCommand(), ChatHandler::HandleWpModifyCommand(), npc_escortAI::MovementInform(), instance_temple_of_ahnqiraj::OnCreatureCreate(), instance_zulaman::OnCreatureEvade(), MaNGOS::RespawnDo::operator()(), CreatureLinkingHolder::ProcessSlave(), npc_escortAI::UpdateAI(), npc_aged_dying_ancient_kodoAI::UpdateAI(), npc_anchorite_baradaAI::UpdateAI(), and npc_kindal_moonweaverAI::UpdateFollowerAI().
SaveRespawnTime()
void Creature::SaveRespawnTime () override virtual
Reimplemented from WorldObject.
Definition at line 2218 of file Creature.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Map::GetPersistentState(), HasStaticDBSpawnData(), IsCorpseExpired(), IsPet(), WorldObject::IsUsingNewSpawningSystem(), m_corpseExpirationTime, m_respawnTime, and MapPersistentState::SaveCreatureRespawnTime().
Referenced by npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_klinfranAI::JustDied(), npc_solenorAI::JustDied(), npc_artoriusAI::JustDied(), instance_black_temple::OnCreatureDeath(), RemoveCorpse(), SetDeathState(), and PoolGroup< T >::Spawn1Object().
SaveToDB() [1/2]
void Creature::SaveToDB () virtual
Reimplemented in TemporarySpawn.
Definition at line 1200 of file Creature.cpp.
References Object::GetDbGuid(), WorldObject::GetMapId(), WorldObject::GetPhaseMask(), sLog, sObjectMgr, and CreatureData::spawnMask.
Referenced by ChatHandler::HandleNpcAddCommand(), ChatHandler::HandleNpcChangeLevelCommand(), ChatHandler::HandleNpcSetModelCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcSetPhaseCommand(), and ChatHandler::HandleWpModifyCommand().
SaveToDB() [2/2]
void Creature::SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask) virtual
Reimplemented in TemporarySpawn, and Pet.
Definition at line 1214 of file Creature.cpp.
References Database::BeginTransaction(), Database::CommitTransaction(), GetCreatureInfo(), GetDefaultMovementType(), Object::GetEntry(), Object::GetGUIDLow(), Unit::GetNativeDisplayId(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), CreatureData::id, IDLE_MOTION_TYPE, m_respawnDelay, m_respawnradius, CreatureData::mapid, MAX_CREATURE_MODEL, CreatureInfo::ModelId, CreatureData::movementType, CreatureData::orientation, Database::PExecuteLog(), CreatureData::phaseMask, CreatureData::posX, CreatureData::posY, CreatureData::posZ, RANDOM_MOTION_TYPE, sObjectMgr, CreatureData::spawndist, CreatureData::spawnMask, CreatureData::spawnTemplate, CreatureData::spawntimesecsmax, CreatureData::spawntimesecsmin, and WorldDatabase.
SelectLevel()
void Creature::SelectLevel (uint32 forcedLevel = USE_DEFAULT_DATABASE_LEVEL)
Definition at line 1285 of file Creature.cpp.
References _GetDamageMod(), _GetHealthMod(), CreatureInfo::Armor, CreatureInfo::ArmorMultiplier, BASE_ATTACK, BASE_VALUE, CreatureInfo::DamageMultiplier, CreatureInfo::DamageVariance, CreatureInfo::Expansion, GetCreatureInfo(), Object::GetGuidStr(), CreatureInfo::HealthMultiplier, IsPet(), IsRegeneratingPower(), MAXDAMAGE, CreatureInfo::MaxLevel, CreatureInfo::MaxLevelHealth, CreatureInfo::MaxLevelMana, CreatureInfo::MaxMeleeDmg, CreatureInfo::MaxRangedDmg, CreatureInfo::MeleeAttackPower, CreatureInfo::MeleeBaseAttackTime, MINDAMAGE, CreatureInfo::MinLevel, CreatureInfo::MinLevelHealth, CreatureInfo::MinLevelMana, CreatureInfo::MinMeleeDmg, CreatureInfo::MinRangedDmg, OFF_ATTACK, POWER_ENERGY, POWER_FOCUS, POWER_FOCUS_DEFAULT, POWER_HAPPINESS, POWER_HAPPINESS_DEFAULT, POWER_MANA, POWER_RAGE, POWER_RUNE, POWER_RUNIC_POWER, CreatureInfo::PowerMultiplier, RANGED_ATTACK, CreatureInfo::RangedAttackPower, CreatureInfo::RangedBaseAttackTime, CreatureInfo::Rank, Unit::SetBaseWeaponDamage(), Unit::SetCreateHealth(), Unit::SetCreateMana(), Unit::SetHealth(), Unit::SetLevel(), Unit::SetMaxHealth(), Unit::SetMaxPower(), Unit::SetModifierValue(), Unit::SetPower(), sLog, sObjectMgr, UNIT_MOD_ARMOR, UNIT_MOD_ATTACK_POWER, UNIT_MOD_ATTACK_POWER_RANGED, UNIT_MOD_POWER_START, CreatureInfo::UnitClass, UpdateAllStats(), urand(), and USE_DEFAULT_DATABASE_LEVEL.
Referenced by Spell::DoSummonCritter(), Pet::InitStatsForLevel(), WorldObject::SummonCreature(), Unit::TakePossessOf(), and UpdateEntry().
SendAreaSpiritHealerQueryOpcode()
void Creature::SendAreaSpiritHealerQueryOpcode (Player * pl) const
Definition at line 2641 of file Creature.cpp.
References CURRENT_CHANNELED_SPELL, Unit::GetCurrentSpell(), Object::GetObjectGuid(), Player::SendDirectMessage(), and SMSG_AREA_SPIRIT_HEALER_TIME.
Referenced by WorldSession::HandleAreaSpiritHealerQueryOpcode(), and WorldSession::HandleGossipHelloOpcode().
SendZoneUnderAttackMessage()
void Creature::SendZoneUnderAttackMessage (Player * attacker) const
Sends a message to LocalDefense and WorldDefense channels for players of the other team.
Definition at line 2305 of file Creature.cpp.
References ALLIANCE, Player::GetTeam(), WorldObject::GetZoneId(), HORDE, and sWorld.
Referenced by CreatureAI::EnterCombat(), and guardAI::JustDied().
SetBaseRunSpeed()
void Creature::SetBaseRunSpeed (float speed, bool force = true) override virtual
Reimplemented from Unit.
Definition at line 2859 of file Creature.cpp.
References Unit::m_baseSpeedRun, m_creatureInfo, MOVE_RUN, CreatureInfo::SpeedRun, and Unit::UpdateSpeed().
Referenced by ScriptAction::ExecuteDbscriptCommand(), boss_silithidRoyaltyAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), and boss_silithidRoyaltyAI::ReceiveAIEvent().
SetBaseWalkSpeed()
void Creature::SetBaseWalkSpeed (float speed) override virtual
Reimplemented from Unit.
Definition at line 2846 of file Creature.cpp.
References Unit::m_baseSpeedWalk, m_creatureInfo, MOVE_WALK, CreatureInfo::SpeedWalk, and Unit::UpdateSpeed().
SetCanAggro()
void Creature::SetCanAggro (bool canAggro) inline
Definition at line 821 of file Creature.h.
References m_canAggro.
Referenced by UnitVisitObjectsInRangeNotifyEvent::Execute(), Unit::SetInCombatState(), and Update().
SetCanCallForAssistance()
void Creature::SetCanCallForAssistance (bool state) inline
Definition at line 726 of file Creature.h.
References m_canCallForAssistance.
Referenced by InitEntry(), boss_kelthuzadAI::JustSummoned(), and instance_sunwell_plateau::OnCreatureRespawn().
SetCanCheckForHelp()
void Creature::SetCanCheckForHelp (bool state) inline
Definition at line 824 of file Creature.h.
References m_checkForHelp.
Referenced by Unit::SetInCombatState().
SetCanDualWield()
void Creature::SetCanDualWield (bool value) virtual
Reimplemented from Unit.
Definition at line 3010 of file Creature.cpp.
References OFF_ATTACK, Unit::SetCanDualWield(), and UpdateDamagePhysical().
Referenced by InitEntry(), and ScriptedAI::SetEquipmentSlots().
SetCombatStartPosition()
void Creature::SetCombatStartPosition (Position const & pos) inline
Definition at line 776 of file Creature.h.
References m_combatStartPos.
Referenced by HomeMovementGenerator< Creature >::Finalize(), and Unit::SetInCombatState().
SetCorpseAccelerationDelay()
void Creature::SetCorpseAccelerationDelay (uint32 delay) inline
Definition at line 710 of file Creature.h.
References m_corpseAccelerationDecayDelay.
Referenced by boss_brutallusAI::boss_brutallusAI().
SetCorpseDelay()
void Creature::SetCorpseDelay (uint32 delay) inline
Definition at line 584 of file Creature.h.
References m_corpseDelay.
Referenced by Pet::Create(), boss_malacrassAI::DoInitializeAdds(), InitEntry(), npc_shadow_imageAI::JustRespawned(), OuroScarab::JustRespawned(), boss_coren_direbrewAI::JustSummoned(), boss_nefarianAI::JustSummoned(), boss_ayamissAI::JustSummoned(), boss_moamAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_morogrim_tidewalkerAI::JustSummoned(), boss_kaelthasAI::JustSummoned(), mob_phoenix_tkAI::JustSummoned(), npc_buru_eggAI::npc_buru_eggAI(), npc_power_blue_flightAI::npc_power_blue_flightAI(), npc_shadow_demonAI::npc_shadow_demonAI(), instance_zulaman::OnCreatureCreate(), instance_sunwell_plateau::OnCreatureCreate(), world_map_ebon_hold::OnCreatureDeath(), instance_blackwing_lair::OnCreatureRespawn(), instance_mount_hyjal::OnCreatureRespawn(), instance_ruins_of_ahnqiraj::OnCreatureRespawn(), instance_temple_of_ahnqiraj::OnCreatureRespawn(), world_map_outland::OnCreatureRespawn(), ProcessEventId_sedai_vision(), boss_alythessAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), npc_cultist_engineer::ReceiveAIEvent(), boss_alythessAI::Reset(), boss_sacrolashAI::Reset(), instance_sunwell_plateau::SpawnGauntlet(), instance_mount_hyjal::SpawnInvasionWave(), and WorldObject::SummonCreature().
SetCreatureGroup()
void Creature::SetCreatureGroup (CreatureGroup * group)
Definition at line 1549 of file Creature.cpp.
References SpawnGroup::AddObject(), Object::GetDbGuid(), Object::GetEntry(), and m_creatureGroup.
Referenced by LoadFromDB().
SetDeathState()
void Creature::SetDeathState (DeathState s) override virtual
Reimplemented from Unit.
Reimplemented in TemporarySpawn, and Pet.
Definition at line 1846 of file Creature.cpp.
References SpawnManager::AddCreature(), ALIVE, ClearCreatureGroup(), ClearTemporaryFaction(), Unit::clearUnitState(), CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY, CORPSE, CREATOR_LOOT, Unit::GetCreator(), GetCreatureGroup(), GetCreatureInfo(), Map::GetCurrentClockTime(), Object::GetDbGuid(), WorldObject::GetMap(), Unit::GetOwner(), GetSettings(), Map::GetSpawnManager(), GetTemporaryFactionFlags(), Object::GetUInt32Value(), Object::HasFlag(), Unit::i_motionMaster, IN_MILLISECONDS, MotionMaster::Initialize(), WorldObject::IsUsingNewSpawningSystem(), IsWorldBoss(), JUST_ALIVED, JUST_DIED, LoadCreatureAddon(), m_corpseDelay, m_corpseExpirationTime, m_killer, m_respawnDelay, m_respawnOverriden, m_respawnOverrideOnce, m_respawnTime, Object::RemoveFlag(), ResetEntry(), ResetSpellHitCounter(), SaveRespawnTime(), Unit::SetDeathState(), SetLootRecipient(), Unit::SetMeleeDamageSchool(), Unit::SetTargetGuid(), Object::SetUInt32Value(), SetWalk(), sObjectMgr, StartCooldown(), sWorld, TEMPFACTION_RESTORE_RESPAWN, UNIT_CREATED_BY_SPELL, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, UNIT_STAT_ALL_STATE, and Unit::Unmount().
Referenced by ForcedDespawn(), ChatHandler::HandleNpcMoveCommand(), ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcSpawnDistCommand(), ChatHandler::HandleWpModifyCommand(), Unit::JustKilledCreature(), npc_escortAI::MovementInform(), RemoveCorpse(), Pet::SetDeathState(), TemporarySpawn::SetDeathState(), Totem::UnSummon(), Update(), npc_escortAI::UpdateAI(), npc_aged_dying_ancient_kodoAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), and npc_injured_patientAI::UpdateAI().
SetDefaultGossipMenuId()
void Creature::SetDefaultGossipMenuId (uint32 menuId) inline
Definition at line 761 of file Creature.h.
References m_gossipMenuId.
Referenced by UpdateEntry().
SetDefaultMovementType()
void Creature::SetDefaultMovementType (MovementGeneratorType mgt) inline
Definition at line 730 of file Creature.h.
References m_defaultMovementType.
Referenced by ChatHandler::HandleNpcSetMoveTypeCommand(), ChatHandler::HandleNpcSpawnDistCommand(), ChatHandler::HandleWpModifyCommand(), npc_klinfranAI::Reset(), npc_solenorAI::Reset(), npc_artoriusAI::Reset(), and WorldObject::SummonCreature().
SetDetectionRange()
void Creature::SetDetectionRange (uint32 range) inline
Definition at line 813 of file Creature.h.
References m_detectionRange.
Referenced by InitEntry(), and npc_sunblade_protectorAI::npc_sunblade_protectorAI().
SetFactionTemporary()
void Creature::SetFactionTemporary (uint32 factionId, uint32 tempFactionFlags = TEMPFACTION_ALL)
Definition at line 2599 of file Creature.cpp.
References m_temporaryFactionFlags, Object::RemoveFlag(), Unit::setFaction(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, TEMPFACTION_TOGGLE_NON_ATTACKABLE, TEMPFACTION_TOGGLE_NOT_SELECTABLE, TEMPFACTION_TOGGLE_PACIFIED, UNIT_FIELD_FLAGS, UNIT_FLAG_PACIFIED, UNIT_FLAG_SPAWNING, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by AreaTrigger_at_huldar_miran(), boss_plugger_spazzringAI::AttackThief(), npc_deathstalker_vincentAI::DamageTaken(), mob_lumpAI::DamageTaken(), argent_champion_commonAI::DamageTaken(), boss_hodirAI::DamageTaken(), boss_thorimAI::DamageTaken(), npc_threshwackonatorAI::DoAtEnd(), mob_unkor_the_ruthlessAI::DoNice(), boss_kalecgosAI::DoStartOutro(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_oil_stained_wolf(), EffectDummyCreature_spell_capture_grark(), EffectDummyCreature_spell_dummy_npc(), EffectScriptEffectCreature_spell_diminution_powder(), mob_yennikuAI::EnterEvadeMode(), npc_magister_aledisAI::ExecuteAction(), GossipSelect_example_creature(), GossipSelect_npc_disciple_of_naralex(), GossipSelect_npc_saeed(), GossipSelect_npc_salsalabim(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_silvermoon_harry(), npc_doomguard_punisherAI::HandleAttackDelay(), npc_shivan_assassinAI::HandleAttackDelay(), npc_eye_of_shartuulAI::HandleAttackDelay(), npc_dreadmawAI::HandleAttackDelay(), BattleGroundIC::HandleCreatureCreate(), BattleGroundSA::HandleCreatureCreate(), boss_deathbringer_saurfangAI::HandleDeath(), npc_bonechewer_combatant::HandleEventStart(), npc_shartuulAI::HandleFightSequence(), npc_taskmaster_fizzuleAI::HandleFlareOrKneel(), boss_vaelastraszAI::HandleSpeech(), boss_victor_nefariusAI::JustDidDialogueStep(), npc_death_knight_initiateAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), boss_majordomoAI::JustReachedHome(), boss_zumrahAI::MoveInLineOfSight(), npc_protectorate_demolitionistAI::MoveInLineOfSight(), npc_magrami_spectre::MovementInform(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), instance_blackrock_depths::OnCreatureCreate(), instance_dire_maul::OnCreatureCreate(), spell_repair_cannon::OnEffectExecute(), KoiKoiDeath::OnEffectExecute(), CreatureEventAI::ProcessAction(), QuestAccept_npc_00x09hl(), QuestAccept_npc_akuno(), QuestAccept_npc_ame01(), QuestAccept_npc_bartleby(), QuestAccept_npc_belnistrasz(), QuestAccept_npc_bessy(), QuestAccept_npc_calvin_montague(), QuestAccept_npc_dalinda_malem(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_deathstalker_faerleia(), QuestAccept_npc_feero_ironhand(), QuestAccept_npc_galen_goodward(), QuestAccept_npc_gilthares(), QuestAccept_npc_helice(), QuestAccept_npc_injured_rainspeaker(), QuestAccept_npc_isla_starmane(), QuestAccept_npc_kanati(), QuestAccept_npc_kaya(), QuestAccept_npc_kayra_longmane(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_letoll(), QuestAccept_npc_lurgglbr(), QuestAccept_npc_marshal_windsor(), QuestAccept_npc_maxx_a_million(), QuestAccept_npc_muglash(), QuestAccept_npc_ogron(), QuestAccept_npc_oox17tn(), QuestAccept_npc_oox22fe(), QuestAccept_npc_paoka_swiftmountain(), QuestAccept_npc_private_hendel(), QuestAccept_npc_professor_phizzlethorpe(), QuestAccept_npc_prospector_remtravel(), QuestAccept_npc_ranger_lilatha(), QuestAccept_npc_ranshalla(), QuestAccept_npc_ruul_snowhoof(), QuestAccept_npc_skywing(), QuestAccept_npc_therylune(), QuestAccept_npc_wilda(), QuestAccept_npc_willix_the_importer(), QuestAccept_npc_wizzlecranks_shredder(), QuestAccept_npc_wounded_blood_elf(), npc_taelan_fordringAI::ReceiveAIEvent(), npc_bonechewer_brawler::ReceiveAIEvent(), npc_corporal_keeshan_escortAI::ReceiveAIEvent(), npc_dorius_stonetenderAI::ReceiveAIEvent(), npc_stinky_ignatzAI::ReceiveAIEvent(), npc_captured_arkonarinAI::ReceiveAIEvent(), npc_areiAI::ReceiveAIEvent(), npc_proudhoofAI::ReceiveAIEvent(), npc_apothecary_hanesAI::ReceiveAIEvent(), npc_injured_minerAI::ReceiveAIEvent(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_drijyaAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_fhwoorAI::ReceiveAIEvent(), npc_demolitionist_legosoAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_plucky_johnsonAI::ReceiveEmote(), mob_enslaved_netherwing_drakeAI::SpellHit(), npc_volcorAI::StartEscort(), npc_magwinAI::StartEvent(), npc_apprentice_mirvedaAI::StartEvent(), FollowerAI::StartFollow(), npc_theramore_spar_controller::StartSparring(), Unit::TakeCharmOf(), Unit::TakePossessOf(), instance_stratholme::Update(), boss_plugger_spazzringAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_phalanxAI::WaypointReached(), npc_prospector_anvilwardAI::WaypointReached(), npc_tapoke_slim_jahnAI::WaypointReached(), and npc_melizza_brimbuzzleAI::WaypointReached().
SetForceAttackingCapability()
void Creature::SetForceAttackingCapability (bool state) inline
Definition at line 807 of file Creature.h.
References m_forceAttackingCapability.
Referenced by InitEntry(), boss_devourer_of_soulsAI::JustSummoned(), boss_lady_deathwhisperAI::JustSummoned(), boss_malchezaarAI::JustSummoned(), and instance_utgarde_keep::OnCreatureRespawn().
SetIgnoreFeignDeath()
void Creature::SetIgnoreFeignDeath (bool state)
Definition at line 2918 of file Creature.cpp.
References IGNORE_FEIGN_DEATH, m_settings, CreatureSettings::RemoveFlag(), and CreatureSettings::SetFlag().
SetIgnoreMMAP()
void Creature::SetIgnoreMMAP (bool ignore) inline
Definition at line 802 of file Creature.h.
References m_ignoreMMAP.
Referenced by boss_brutallusAI::JustDidDialogueStep(), and boss_nightbaneAI::MovementInform().
SetInCombatWithZone()
void Creature::SetInCombatWithZone (bool checkAttackability = true)
Definition at line 2310 of file Creature.cpp.
References AI(), Unit::CanAttack(), Unit::CanHaveThreatList(), Unit::EngageInCombatWith(), Object::GetEntry(), Map::GetId(), WorldObject::GetMap(), Map::GetPlayers(), Map::IsDungeon(), LinkedListHead::isEmpty(), and sLog.
Referenced by npc_sunblade_scoutAI::Aggro(), npc_sunblade_protectorAI::Aggro(), npc_amanishi_scoutAI::Aggro(), boss_eye_of_cthunAI::Aggro(), boss_cthunAI::Aggro(), boss_gothikAI::Aggro(), npc_greater_shadowfiend::Aggro(), boss_nethermancer_sepethreaAI::Aggro(), boss_essence_of_angerAI::boss_essence_of_angerAI(), boss_vazruden_heraldAI::DoMoveToCenter(), mob_illidari_councilAI::DoStartEvent(), essence_base_AI::essence_base_AI(), ScriptAction::ExecuteDbscriptCommand(), boss_dorotheeAI::HandleAggro(), boss_attumenAI::HandleAttackDelay(), boss_nightbaneAI::HandleAttackDelay(), npc_sinister_reflectionAI::HandleAttackDelay(), boss_entropiusAI::HandleAttackDelay(), DarkFiendAI::HandleAttackDelay(), boss_vazruden_heraldAI::HandleAttackDelay(), mob_phoenix_tkAI::HandleAttackDelay(), boss_nefarianAI::HandleAttackStart(), OuroScarab::HandleDelayedAttack(), boss_cthunAI::HandleEmerge(), boss_ragnarosAI::HandleEnterCombat(), boss_gothikAI::HandleGroundPhase(), boss_the_lurker_belowAI::HandleInitialAggro(), npc_singularityAI::HandleSpawn(), boss_vaelastraszAI::HandleSpeech(), boss_victor_nefariusAI::JustDidDialogueStep(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_saraAI::JustDidDialogueStep(), npc_rimefang_iccAI::JustDied(), npc_spinestalker_iccAI::JustDied(), boss_kiljaedenAI::JustRespawned(), mob_soaring_eagleAI::JustRespawned(), npc_corrupted_lightning_totemAI::JustRespawned(), npc_feather_vortexAI::JustRespawned(), boss_ouroAI::JustRespawned(), npc_nerubian_burrowerAI::JustRespawned(), npc_doom_blossomAI::JustRespawned(), npc_caribdis_cyclone::JustRespawned(), mob_water_globuleAI::JustRespawned(), npc_serpentshrine_parasiteAI::JustRespawned(), boss_baltharusAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), boss_onyxiaAI::JustSummoned(), npc_beast_combat_stalkerAI::JustSummoned(), boss_keleseth_iccAI::JustSummoned(), boss_professor_putricideAI::JustSummoned(), mob_twilight_eggsAI::JustSummoned(), npc_fire_cycloneAI::JustSummoned(), npc_meteor_strike_initialAI::JustSummoned(), npc_worm_holeAI::JustSummoned(), npc_freya_wardAI::JustSummoned(), boss_general_vezaxAI::JustSummoned(), npc_rubble_stalkerAI::JustSummoned(), npc_razorscale_spawnerAI::JustSummoned(), boss_thorimAI::JustSummoned(), boss_saraAI::JustSummoned(), npc_voice_yogg_saronAI::JustSummoned(), npc_ominous_cloudAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_malchezaarAI::JustSummoned(), boss_aranAI::JustSummoned(), boss_terestianAI::JustSummoned(), npc_fiendish_portalAI::JustSummoned(), boss_ragnarosAI::JustSummoned(), boss_kiljaedenAI::JustSummoned(), npc_darknessAI::JustSummoned(), boss_akilzonAI::JustSummoned(), boss_halazziAI::JustSummoned(), boss_janalaiAI::JustSummoned(), boss_archimondeAI::JustSummoned(), boss_moamAI::JustSummoned(), boss_yaujAI::JustSummoned(), boss_fankrissAI::JustSummoned(), boss_sladranAI::JustSummoned(), boss_gothikAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), boss_maexxnaAI::JustSummoned(), boss_nothAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_supremusAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), boss_morogrim_tidewalkerAI::JustSummoned(), boss_broggokAI::JustSummoned(), boss_vazruden_heraldAI::JustSummoned(), boss_warp_splinterAI::JustSummoned(), mob_fel_orc_convertAI::MoveInLineOfSight(), boss_kaelthasAI::MoveInLineOfSight(), npc_shattered_hands_zealotAI::MovementInform(), boss_broggokAI::MovementInform(), boss_mandokirAI::MovementInform(), boss_high_inquisitor_whitemaneAI::MovementInform(), boss_flame_leviathanAI::MovementInform(), dummy_dragonAI::MovementInform(), npc_demonic_vaporAI::npc_demonic_vaporAI(), npc_enslaved_soulAI::npc_enslaved_soulAI(), npc_flame_of_azzinothAI::npc_flame_of_azzinothAI(), npc_parasitic_shadowfiendAI::npc_parasitic_shadowfiendAI(), instance_blackwing_lair::OnCreatureRespawn(), instance_zulaman::OnCreatureRespawn(), instance_temple_of_ahnqiraj::OnCreatureRespawn(), npc_ouro_moundAI::PickNewTarget(), CreatureEventAI::ProcessAction(), ProcessEventId_event_go_focusing_iris(), boss_magtheridonAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::ReceiveAIEvent(), boss_leotheras_the_blindAI::ReceiveAIEvent(), Unit::SetInCombatState(), npc_feather_vortexAI::StartAttacking(), boss_onyxiaAI::SummonedMovementInform(), boss_muruAI::SummonedMovementInform(), npc_creature_generatorAI::SummonedMovementInform(), boss_kelthuzadAI::SummonedMovementInform(), boss_the_lurker_belowAI::SummonedMovementInform(), npc_shattered_hand_legionnaire::SummonedMovementInform(), boss_strawmanAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_julianneAI::UpdateAI(), and npc_spawn_of_hydrossAI::UpdateAI().
SetInvisible()
void Creature::SetInvisible (bool invisible) inline
Definition at line 799 of file Creature.h.
References m_isInvisible.
SetKillerGuid()
void Creature::SetKillerGuid (ObjectGuid guid) inline
Definition at line 881 of file Creature.h.
References m_killer.
Referenced by Unit::JustKilledCreature().
SetLootRecipient()
void Creature::SetLootRecipient (Unit * unit)
Set player and group (if player group member) who tap creature.
Definition at line 1172 of file Creature.cpp.
References ObjectGuid::Clear(), Object::ForceValuesUpdateAtIndex(), Unit::GetBeneficiaryPlayer(), Player::GetGroup(), Object::GetObjectGuid(), m_lootGroupRecipientId, m_lootRecipientGuid, and UNIT_DYNAMIC_FLAGS.
Referenced by AIM_Initialize(), npc_death_knight_initiateAI::DamageTaken(), Spell::EffectDummy(), FollowerAI::EnterEvadeMode(), mob_yennikuAI::EnterEvadeMode(), npc_taelan_fordringAI::EnterEvadeMode(), npc_isillienAI::EnterEvadeMode(), npc_tirion_fordringAI::EnterEvadeMode(), hyjalAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), npc_general_andorovAI::EnterEvadeMode(), npc_kaldorei_eliteAI::EnterEvadeMode(), npc_disciple_of_naralexAI::EnterEvadeMode(), boss_jaraxxusAI::EnterEvadeMode(), npc_infantryAI::EnterEvadeMode(), npc_grand_admiral_westwindAI::EnterEvadeMode(), npc_rimefang_iccAI::EnterEvadeMode(), npc_spinestalker_iccAI::EnterEvadeMode(), boss_uromAI::EnterEvadeMode(), mob_molten_golemAI::EnterEvadeMode(), boss_freyaAI::EnterEvadeMode(), boss_hodirAI::EnterEvadeMode(), boss_thorimAI::EnterEvadeMode(), boss_sifAI::EnterEvadeMode(), boss_maievAI::EnterEvadeMode(), npc_magister_aledisAI::EnterEvadeMode(), npc_scrapped_fel_reaverAI::EnterEvadeMode(), npc_spawned_oronok_tornheartAI::EnterEvadeMode(), npc_millhouse_manastormAI::EnterEvadeMode(), boss_dalliahAI::EnterEvadeMode(), boss_soccothratesAI::EnterEvadeMode(), boss_majordomoAI::JustReachedHome(), SetDeathState(), and npc_rabid_bearAI::SpellHit().
SetLootStatus()
void Creature::SetLootStatus (CreatureLootStatus status, bool forced = false)
Definition at line 2789 of file Creature.cpp.
References CREATURE_LOOT_STATUS_LOOTED, CREATURE_LOOT_STATUS_PICKPOCKETED, CREATURE_LOOT_STATUS_SKIN_AVAILABLE, CREATURE_LOOT_STATUS_SKINNED, m_corpseExpirationTime, m_creatureInfo, m_lootStatus, ReduceCorpseDecayTimer(), Object::RemoveFlag(), Object::SetFlag(), CreatureInfo::SkinningLootId, StartPickpocketRestockTimer(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_LOOTABLE, UNIT_FIELD_FLAGS, and UNIT_FLAG_SKINNABLE.
Referenced by Spell::EffectPickPocket(), Loot::Loot(), PrepareBodyLootState(), and Loot::Release().
SetNoCallAssistance()
void Creature::SetNoCallAssistance (bool val) inline
Definition at line 722 of file Creature.h.
References m_AlreadyCallAssistance.
Referenced by CallAssistance(), CreatureAI::HandleAssistanceCall(), boss_morogrim_tidewalkerAI::JustSummoned(), and CreatureAI::RetreatingArrived().
SetNoLoot()
void Creature::SetNoLoot (bool state)
Definition at line 2905 of file Creature.cpp.
References m_settings, NO_LOOT, CreatureSettings::RemoveFlag(), and CreatureSettings::SetFlag().
Referenced by boss_silithidRoyaltyAI::DoDummyConsume(), boss_alythessAI::JustPreventedDeath(), boss_sacrolashAI::JustPreventedDeath(), instance_blackwing_lair::OnCreatureRespawn(), instance_mount_hyjal::OnCreatureRespawn(), boss_alythessAI::Reset(), boss_sacrolashAI::Reset(), SetNoRewards(), instance_sunwell_plateau::SpawnGauntlet(), and instance_mount_hyjal::SpawnWave().
SetNoReputation()
void Creature::SetNoReputation (bool state) inline
Definition at line 832 of file Creature.h.
References m_noReputation.
Referenced by InitEntry(), instance_mount_hyjal::OnCreatureRespawn(), SetNoRewards(), and instance_mount_hyjal::SpawnWave().
SetNoRewards()
void Creature::SetNoRewards ()
Definition at line 2880 of file Creature.cpp.
References SetNoLoot(), SetNoReputation(), and SetNoXP().
Referenced by instance_shattered_halls::OnCreatureRespawn().
SetNoWeaponSkillGain()
void Creature::SetNoWeaponSkillGain (bool state)
Definition at line 2944 of file Creature.cpp.
References m_settings, NO_SKILL_GAINS, CreatureSettings::RemoveFlag(), and CreatureSettings::SetFlag().
SetNoWoundedSlowdown()
void Creature::SetNoWoundedSlowdown (bool state)
Definition at line 2926 of file Creature.cpp.
References m_settings, NO_WOUNDED_SLOWDOWN, CreatureSettings::RemoveFlag(), and CreatureSettings::SetFlag().
SetNoXP()
void Creature::SetNoXP (bool state)
Definition at line 2892 of file Creature.cpp.
References m_settings, NO_XP, CreatureSettings::RemoveFlag(), and CreatureSettings::SetFlag().
Referenced by instance_mount_hyjal::OnCreatureRespawn(), SetNoRewards(), and instance_mount_hyjal::SpawnWave().
SetOnlyVisibleTo()
void Creature::SetOnlyVisibleTo (ObjectGuid guid)
Definition at line 1574 of file Creature.cpp.
References m_onlyVisibleTo.
Referenced by Spell::EffectSummonType().
SetRespawnCoord() [1/2]
void Creature::SetRespawnCoord (CreatureCreatePos const & pos) inline
Definition at line 781 of file Creature.h.
References CreatureCreatePos::m_pos, and m_respawnPos.
Referenced by Create(), Spell::DoSummonCritter(), Spell::DoSummonGuardian(), Spell::DoSummonPet(), Spell::DoSummonTotem(), Spell::EffectCreateTamedPet(), Spell::EffectSummonPet(), LoadFromDB(), npc_champion_mountAI::MovementInform(), boss_algalonAI::MovementInform(), WorldObject::SummonCreature(), trial_companion_commonAI::SummonedMovementInform(), Unit::TakePossessOf(), and instance_stratholme::Update().
SetRespawnCoord() [2/2]
void Creature::SetRespawnCoord (float x, float y, float z, float ori) inline
Definition at line 782 of file Creature.h.
References m_respawnPos, Position::o, Position::x, Position::y, and Position::z.
SetRespawnDelay()
void Creature::SetRespawnDelay (uint32 delay, bool once = false) inline
Definition at line 745 of file Creature.h.
References m_respawnDelay, m_respawnOverriden, and m_respawnOverrideOnce.
Referenced by HomeMovementGenerator< Creature >::_setTargetLocation(), BattleGround::ChangeBgCreatureSpawnState(), npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_the_scourge_cauldronAI::DoDie(), boss_felblood_kaelthasAI::EnterEvadeMode(), boss_felmystAI::EnterEvadeMode(), boss_gothikAI::EnterEvadeMode(), boss_kelthuzadAI::EnterEvadeMode(), boss_nothAI::EnterEvadeMode(), ChatHandler::HandleNpcSpawnTimeCommand(), npc_tapoke_slim_jahnAI::JustDidDialogueStep(), npc_klinfranAI::JustDied(), npc_solenorAI::JustDied(), npc_artoriusAI::JustDied(), npc_brann_hosAI::JustDied(), npc_a_special_surpriseAI::JustDied(), boss_thaddiusAI::JustReachedHome(), boss_majordomoAI::JustSummoned(), npc_ouro_spawnerAI::JustSummoned(), npc_brann_hosAI::MovementInform(), instance_black_temple::OnCreatureDeath(), instance_black_temple::OnCreatureRespawn(), boss_ossirianAI::ReceiveAIEvent(), npc_klinfranAI::Reset(), boss_archimondeAI::Reset(), npc_solenorAI::Reset(), npc_simone_the_inconspicuousAI::Reset(), npc_artoriusAI::Reset(), instance_scarlet_monastery::SetData(), PoolGroup< T >::Spawn1Object(), instance_mount_hyjal::SpawnInvasionWave(), npc_keeper_remulosAI::UpdateEscortAI(), and npc_ranger_lilathaAI::WaypointReached().
SetRespawnRadius()
void Creature::SetRespawnRadius (float dist) inline
Definition at line 748 of file Creature.h.
References m_respawnradius.
Referenced by ChatHandler::HandleNpcSpawnDistCommand().
SetRespawnTime()
void Creature::SetRespawnTime (uint32 respawn) inline
Definition at line 740 of file Creature.h.
References m_respawnTime.
Referenced by npc_klinfranAI::DemonDespawn(), npc_solenorAI::DemonDespawn(), npc_artoriusAI::DemonDespawn(), npc_klinfranAI::JustDied(), npc_solenorAI::JustDied(), npc_artoriusAI::JustDied(), npc_klinfranAI::Reset(), npc_solenorAI::Reset(), npc_simone_the_inconspicuousAI::Reset(), npc_artoriusAI::Reset(), PoolGroup< T >::Spawn1Object(), and npc_shadowlord_deathwailAI::UpdateAI().
SetSpawnCounting()
void Creature::SetSpawnCounting (bool state) inline
Definition at line 810 of file Creature.h.
References m_countSpawns.
Referenced by WorldObject::SummonCreature().
SetSpellList()
void Creature::SetSpellList (uint32 spellSet)
Definition at line 2382 of file Creature.cpp.
References AI(), MapDataContainer::GetCreatureSpellList(), WorldObject::GetMap(), Map::GetMapDataContainer(), m_spellList, UnitAI::SpellListChanged(), CreatureSpellList::Spells, and urand().
Referenced by boss_thekalAI::boss_thekalAI(), Totem::Create(), boss_galdarahAI::DoPhaseSwitch(), Spell::DoSummonGuardian(), boss_arlokkAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_venoxisAI::ExecuteAction(), boss_loathebAI::ExecuteAction(), boss_patchwerkAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), GargoyleDeathKnightAI::GargoyleDeathKnightAI(), boss_arlokkAI::JustReachedHome(), boss_marliAI::JustReachedHome(), boss_venoxisAI::JustReachedHome(), boss_sapphironAI::MovementInform(), ShivanShapeshiftForm::OnApply(), instance_oculus::OnCreatureCreate(), IceBolt::OnEffectExecute(), CreatureEventAI::ProcessAction(), boss_jeklikAI::Reset(), boss_thekalAI::Reset(), boss_moorabiAI::Reset(), boss_anubrekhanAI::Reset(), boss_loathebAI::Reset(), boss_patchwerkAI::Reset(), boss_razuviousAI::Reset(), boss_sapphironAI::Reset(), boss_moorabiAI::SpellHitTarget(), and UpdateEntry().
SetVirtualItem()
void Creature::SetVirtualItem (VirtualItemSlot slot, uint32 item_id) inline
Definition at line 793 of file Creature.h.
References Object::SetUInt32Value(), and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by ScriptAction::ExecuteDbscriptCommand(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), boss_forgemaster_garfrostAI::JustReachedHome(), boss_forgemaster_garfrostAI::JustRespawned(), LoadEquipment(), boss_forgemaster_garfrostAI::MovementInform(), boss_telestraAI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), npc_supplicantAI::ReceiveAIEvent(), ScriptedAI::SetEquipmentSlots(), and npc_supplicantAI::UpdateAI().
SetWalk()
void Creature::SetWalk (bool enable, bool asDefault = true)
Definition at line 2744 of file Creature.cpp.
References MovementInfo::AddMovementFlag(), Unit::addUnitState(), Unit::clearUnitState(), Object::GetPackGUID(), MovementInfo::HasMovementFlag(), WorldObject::m_movementInfo, MOVEFLAG_WALK_MODE, MovementInfo::RemoveMovementFlag(), WorldObject::SendMessageToSet(), SMSG_SPLINE_MOVE_SET_RUN_MODE, SMSG_SPLINE_MOVE_SET_WALK_MODE, and UNIT_STAT_RUNNING.
Referenced by npc_amanishi_scoutAI::Aggro(), boss_jeklikAI::Aggro(), boss_lady_blaumeuxAI::Aggro(), boss_rivendare_naxxAI::Aggro(), boss_thane_korthazzAI::Aggro(), boss_sir_zeliekAI::Aggro(), boss_aerial_unitAI::Aggro(), AreaTrigger_at_shadowforge_bridge(), boss_sindragosaAI::AttackStart(), npc_lazy_peonAI::Awaken(), boss_ayamissAI::boss_ayamissAI(), boss_headless_horsemanAI::boss_headless_horsemanAI(), boss_razorgoreAI::boss_razorgoreAI(), boss_selin_fireheartAI::boss_selin_fireheartAI(), boss_zuljinAI::boss_zuljinAI(), boss_sartharionAI::CallDragon(), Creature(), npc_anubarak_trial_frostsphereAI::DamageTaken(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), npc_cenarion_sparrowhawkAI::DoFindNearbyStones(), npc_felhound_trackerAI::DoFindNewCrystal(), npc_rookery_hatcherAI::DoFindNewEgg(), instance_stratholme::DoMoveBackDefenders(), boss_vazruden_heraldAI::DoMoveToCombat(), boss_general_vezaxAI::DoPrepareAnimusIfCan(), npc_akama_illidanAI::DoResumeEvent(), instance_culling_of_stratholme::DoSpawnArthasIfNeeded(), world_map_ebon_hold::DoSpawnUndeadWave(), npc_highlord_darion_mograineAI::DoStartConclusion(), npc_Shattered_Hand_Scout::DoStartRunning(), boss_lady_deathwhisperAI::DoStartSecondPhase(), trial_companion_commonAI::DoUseNearbyMountIfCan(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), EffectAuraDummy_npc_scourged_flamespitter(), EffectDummyCreature_npc_oil_stained_wolf(), npc_disciple_of_naralexAI::EnterEvadeMode(), npc_living_mojoAI::EnterEvadeMode(), npc_magister_aledisAI::EnterEvadeMode(), boss_warlord_kalithreshAI::ExecuteActions(), ScriptAction::ExecuteDbscriptCommand(), WaypointMovementGenerator< Creature >::Finalize(), npc_dragonmaw_racerAI::FinishRace(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_tobias_seecher(), npc_general_andorovAI::HandleMove(), InitEntry(), WaypointMovementGenerator< Creature >::Interrupt(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), instance_blackrock_spire::JustDidDialogueStep(), npc_smolderwing::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_millhouse_manastormAI::JustDidDialogueStep(), boss_nefarianAI::JustRespawned(), boss_shade_of_akamaAI::JustRespawned(), npc_bird_spiritAI::JustRespawned(), npc_caribdis_cyclone::JustRespawned(), npc_rinjiAI::JustSummoned(), npc_image_of_medivhAI::JustSummoned(), npc_highlord_darion_mograineAI::JustSummoned(), npc_time_riftAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_twiggy_flatheadAI::JustSummoned(), boss_jedogaAI::JustSummoned(), npc_beast_combat_stalkerAI::JustSummoned(), npc_emilyAI::JustSummoned(), npc_putricides_trapAI::JustSummoned(), boss_algalonAI::JustSummoned(), npc_prison_event_controllerAI::JustSummoned(), npc_shaheenAI::JustSummoned(), npc_squire_roweAI::JustSummoned(), boss_brutallusAI::JustSummoned(), npc_amanishi_tempestAI::JustSummoned(), npc_keeper_remulosAI::JustSummoned(), boss_eranikusAI::JustSummoned(), boss_ayamissAI::JustSummoned(), boss_sladranAI::JustSummoned(), npc_creature_generatorAI::JustSummoned(), boss_lady_vashjAI::JustSummoned(), instance_trial_of_the_champion::MoveChampionToHome(), npc_harkorAI::MovementInform(), npc_tanzarAI::MovementInform(), npc_ashliAI::MovementInform(), npc_lazy_peonAI::MovementInform(), npc_deadsoul_orb::MovementInform(), npc_krunAI::MovementInform(), npc_ashliAI::npc_ashliAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_flame_tsunamiAI::npc_flame_tsunamiAI(), npc_shadow_demonAI::npc_shadow_demonAI(), instance_pit_of_saron::OnCreatureDeath(), instance_pit_of_saron::OnCreatureEnterCombat(), instance_violet_hold::OnCreatureEvade(), instance_pinnacle::OnCreatureRespawn(), world_map_ebon_hold::OnCreatureRespawn(), instance_azjol_nerub::OnCreatureRespawn(), instance_halls_of_stone::OnCreatureRespawn(), spell_tag_troll::OnEffectExecute(), spell_out_cold::OnEffectExecute(), npc_brann_hosAI::PrepareTribunalEvent(), CreatureEventAI::ProcessAction(), npc_akama_illidanAI::ReceiveAIEvent(), boss_head_of_horsemanAI::ReceiveAIEvent(), boss_razorscaleAI::ReceiveAIEvent(), npc_decaying_ghoulAI::ReceiveAIEvent(), npc_domesticated_felboarAI::ReceiveAIEvent(), npc_amanishi_hatcherAI::Reset(), npc_amanishi_scoutAI::Reset(), boss_vemAI::Reset(), npc_concentrated_bulletAI::Reset(), boss_illidan_stormrageAI::Reset(), boss_doomwalkerAI::Reset(), boss_lady_vashjAI::Reset(), npc_bessyAI::Reset(), npc_dragonmaw_racerAI::Reset(), boss_alarAI::Reset(), guard_hallows_end_helperAI::Reset(), world_map_outland::ScriptAction(), instance_zulaman::SendNextBearWave(), instance_stratholme::SetData(), SetDeathState(), boss_sindragosaAI::SetFlying(), npc_rimefang_iccAI::SetFlying(), npc_spinestalker_iccAI::SetFlying(), npc_escortAI::SetRun(), npc_injured_patientAI::SpellHit(), npc_escortAI::Start(), npc_amanishi_lookoutAI::StartEvent(), npc_commanderAI::StartEvent(), boss_nefarianAI::StartLanding(), npc_dragonmaw_racerAI::StartRace(), npc_brann_hosAI::StartSjonnirEvent(), npc_brann_hosAI::StartTribunalEvent(), WorldObject::SummonCreature(), npc_thrall_old_hillsbradAI::SummonedMovementInform(), boss_lady_vashjAI::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), Unit::TakeCharmOf(), Unit::TakePossessOf(), npc_harkorAI::UpdateAI(), npc_ashliAI::UpdateAI(), boss_eranikusAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), npc_anachronos_the_ancientAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), npc_firecrackers_bunnyAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_savianaAI::UpdateAI(), boss_volkhanAI::UpdateAI(), npc_dark_matterAI::UpdateAI(), npc_graufAI::UpdateAI(), boss_ymironAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_light_orb_collectorAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_ruul_snowhoofAI::WaypointReached(), and npc_cork_gizeltonAI::WaypointReached().
SpawnInMaps()
void Creature::SpawnInMaps (uint32 db_guid, CreatureData const * data) static
Definition at line 2723 of file Creature.cpp.
References CreatureData::mapid, and sMapMgr.
Referenced by GameEventMgr::GameEventSpawn().
StartCooldown()
void Creature::StartCooldown (Unit * owner)
Definition at line 3110 of file Creature.cpp.
References WorldObject::AddCooldown(), Object::GetUInt32Value(), SpellEntry::HasAttribute(), SQLStorage::LookupEntry(), m_imposedCooldown, SPELL_ATTR_COOLDOWN_ON_EVENT, sSpellTemplate, and UNIT_CREATED_BY_SPELL.
Referenced by RemoveFromWorld(), SetDeathState(), and Pet::Unsummon().
StartPickpocketRestockTimer()
void Creature::StartPickpocketRestockTimer ()
Definition at line 3021 of file Creature.cpp.
References CONFIG_UINT32_CREATURE_PICKPOCKET_RESTOCK_DELAY, Map::GetCurrentClockTime(), WorldObject::GetMap(), IN_MILLISECONDS, m_pickpocketRestockTime, and sWorld.
Referenced by SetLootStatus().
UnregisterHitBySpell()
void Creature::UnregisterHitBySpell (uint32 spellId)
Definition at line 3036 of file Creature.cpp.
References m_hitBySpells.
UnsummonCleanup()
void Creature::UnsummonCleanup () protected
Definition at line 2970 of file Creature.cpp.
References Unit::BreakCharmIncoming(), Unit::BreakCharmOutgoing(), Unit::CombatStop(), Unit::InterruptNonMeleeSpells(), Unit::RemoveAllAurasOnDeath(), Unit::RemoveGuardians(), Unit::RemoveMiniPet(), and Unit::UnsummonAllTotems().
Referenced by TemporarySpawn::UnSummon().
Update()
void Creature::Update (const uint32 diff) override virtual
Reimplemented from WorldObject.
Reimplemented in Totem, TemporarySpawn, and Pet.
Definition at line 719 of file Creature.cpp.
References Map::Add(), AI(), ALIVE, CORPSE, CREATURE_GROUP_EVENT_RESPAWN, DEAD, DEBUG_FILTER_LOG, CreatureLinkingHolder::DoCreatureLinkingEvent(), GetCreatureGroup(), Map::GetCreatureLinkingHolder(), Object::GetDbGuid(), Object::GetEntry(), Object::GetGUIDLow(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPersistentState(), HIGHGUID_PET, Unit::IsAlive(), IsCorpseExpired(), JUST_ALIVED, JUST_DIED, UnitAI::JustRespawned(), LINKING_EVENT_RESPAWN, LOG_FILTER_AI_AND_MOVEGENSS, Unit::m_deathState, Unit::m_isCreatureLinkingTrigger, Unit::m_isSpawningLinked, Object::m_loot, m_respawnTime, RegenerateAll(), Unit::RemoveAllAuras(), RemoveCorpse(), SetCanAggro(), SetDeathState(), Object::SetUInt32Value(), sLog, sPoolMgr, CreatureGroup::TriggerLinkingEvent(), UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, Loot::Update(), and Unit::Update().
Referenced by Pet::Update(), TemporarySpawn::Update(), and Totem::Update().
UpdateAllStats()
bool Creature::UpdateAllStats () override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 815 of file StatSystem.cpp.
References MAX_POWERS, MAX_SPELL_SCHOOL, POWER_MANA, SPELL_SCHOOL_NORMAL, UpdateAttackPowerAndDamage(), UpdateMaxHealth(), UpdateMaxPower(), and UpdateResistances().
Referenced by SelectLevel(), and UpdateEntry().
UpdateArmor()
void Creature::UpdateArmor () override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 841 of file StatSystem.cpp.
References Unit::GetTotalResistanceValue(), Unit::SetArmor(), and SPELL_SCHOOL_NORMAL.
Referenced by Pet::UpdateArmor(), and UpdateResistances().
UpdateAttackPowerAndDamage()
void Creature::UpdateAttackPowerAndDamage (bool ranged = false) override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 871 of file StatSystem.cpp.
References BASE_ATTACK, BASE_PCT, BASE_VALUE, Unit::GetModifierValue(), OFF_ATTACK, RANGED_ATTACK, Object::SetFloatValue(), Object::SetInt32Value(), TOTAL_PCT, TOTAL_VALUE, UNIT_FIELD_ATTACK_POWER, UNIT_FIELD_ATTACK_POWER_MODS, UNIT_FIELD_ATTACK_POWER_MULTIPLIER, UNIT_FIELD_RANGED_ATTACK_POWER, UNIT_FIELD_RANGED_ATTACK_POWER_MODS, UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER, UNIT_MOD_ATTACK_POWER, UNIT_MOD_ATTACK_POWER_RANGED, and UpdateDamagePhysical().
Referenced by UpdateAllStats().
UpdateDamagePhysical()
void Creature::UpdateDamagePhysical (WeaponAttackType attType) override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 905 of file StatSystem.cpp.
References BASE_ATTACK, BASE_PCT, BASE_VALUE, Unit::GetAPMultiplier(), Unit::GetBaseWeaponDamage(), Unit::GetModifierValue(), hasWeapon(), hasWeaponForAttack(), MAXDAMAGE, MINDAMAGE, OFF_ATTACK, RANGED_ATTACK, Object::SetStatFloatValue(), TOTAL_PCT, TOTAL_VALUE, UNIT_FIELD_MAXDAMAGE, UNIT_FIELD_MAXOFFHANDDAMAGE, UNIT_FIELD_MAXRANGEDDAMAGE, UNIT_FIELD_MINDAMAGE, UNIT_FIELD_MINOFFHANDDAMAGE, UNIT_FIELD_MINRANGEDDAMAGE, UNIT_MOD_ATTACK_POWER, UNIT_MOD_ATTACK_POWER_RANGED, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, and UNIT_MOD_DAMAGE_RANGED.
Referenced by SetCanDualWield(), ScriptedAI::SetEquipmentSlots(), and UpdateAttackPowerAndDamage().
UpdateEntry()
bool Creature::UpdateEntry (uint32 Entry, const CreatureData * data = nullptr, GameEventCreatureData const * eventData = nullptr, bool preserveHPAndPower = true, bool randomizeLevels = true)
Definition at line 502 of file Creature.cpp.
References ALIVE, ApplyGameEventSpells(), Unit::ApplySpellImmune(), AREA_FLAG_SANCTUARY, BASE_ATTACK, CREATURE_EXTRA_FLAG_COUNT_SPAWNS, CREATURE_EXTRA_FLAG_INVISIBLE, CREATURE_EXTRA_FLAG_MMAP_FORCE_DISABLE, CreatureSpawnTemplate::curHealth, CreatureSpawnTemplate::curMana, CreatureInfo::ExtraFlags, CreatureInfo::Faction, CreatureSpawnTemplate::faction, FACTION_TEMPLATE_FLAG_ASSIST_PLAYERS, AreaTableEntry::flags, GetAreaEntryByAreaID(), WorldObject::GetAreaId(), GetCreatureInfo(), Unit::GetHealthPercent(), Unit::GetLevel(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Unit::GetPowerType(), Object::GetUInt32Value(), Object::HasFlag(), MovementInfo::HasMovementFlag(), IMMUNITY_STATE, InitEntry(), IsCritter(), IsRegeneratingPower(), IsWorldBoss(), m_countSpawns, Unit::m_deathState, m_ignoreMMAP, m_isInvisible, WorldObject::m_movementInfo, m_settings, CreatureInfo::MeleeBaseAttackTime, MOVEFLAG_SWIMMING, CreatureInfo::NpcFlags, CreatureSpawnTemplate::npcFlags, OFF_ATTACK, POWER_MANA, RANGED_ATTACK, REGEN_FLAG_POWER, REGEN_FLAG_POWER_IN_COMBAT, CreatureSettings::ResetStaticFlags(), SelectLevel(), Unit::SetAOEImmune(), Unit::SetAttackTime(), Unit::SetCanModifyStats(), Unit::SetChainImmune(), Unit::SetCreateResistance(), SetDefaultGossipMenuId(), Unit::setFaction(), Object::SetFlag(), Unit::SetHealth(), Unit::SetHealthPercent(), Unit::SetPower(), Unit::SetPvP(), Unit::SetSheath(), SetSpellList(), WorldObject::SetStringId(), Object::SetUInt32Value(), Unit::SetVehicleId(), sFactionTemplateStore, SHEATH_STATE_MELEE, CreatureData::spawnTemplate, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELL_SCHOOL_ARCANE, SPELL_SCHOOL_FIRE, SPELL_SCHOOL_FROST, SPELL_SCHOOL_HOLY, SPELL_SCHOOL_NATURE, SPELL_SCHOOL_SHADOW, CreatureSpawnTemplate::stringId, UNIT_DYNAMIC_FLAGS, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_REGENERATE_POWER, UNIT_FLAG_IN_COMBAT, UNIT_FLAG_SWIMMING, UNIT_NPC_FLAGS, CreatureInfo::UnitFlags, CreatureSpawnTemplate::unitFlags, UpdateAllStats(), UpdateImmunitiesSet(), and USE_DEFAULT_DATABASE_LEVEL.
Referenced by Map::ChangeMapDifficulty(), CreateFromProto(), boss_halazziAI::DoReuniteSpirits(), npc_forest_frogAI::DoSpawnRandom(), boss_vazruden_heraldAI::DoSplit(), EffectAuraDummy_spell_aura_dummy_npc(), EffectDummyCreature_npc_aged_dying_ancient_kodo(), EffectDummyCreature_spell_dummy_npc(), boss_halazziAI::EnterEvadeMode(), boss_eranikusAI::EnterEvadeMode(), mob_molten_golemAI::EnterEvadeMode(), ScriptAction::ExecuteDbscriptCommand(), ChatHandler::HandleNpcChangeEntryCommand(), boss_ingvarAI::JustReachedHome(), npc_disobedient_dragonmaw_peonAI::MovementInform(), spell_feigh_death_pos_aura::OnApply(), spell_dark_transformation_aura::OnApply(), spell_dark_empowerment_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_dark_adherent_martyrdom_aura::OnApply(), spell_ingvar_transform_aura::OnApply(), instance_blackrock_depths::OnCreatureCreate(), instance_culling_of_stratholme::OnCreatureCreate(), spell_repair_cannon::OnEffectExecute(), CreatureEventAI::ProcessAction(), boss_dathrohan_balnazzarAI::Reset(), npc_kyle_the_frenziedAI::Reset(), boss_vazruden_heraldAI::Reset(), ResetEntry(), boss_halazziAI::SpellHit(), npc_rabid_bearAI::SpellHit(), mobs_nether_drakeAI::SpellHit(), boss_yorAI::StartEvent(), npc_ethereum_prisoner_dungeonAI::StartEvent(), npc_ethereum_prisonerAI::StartEvent(), npc_klinfranAI::Transform(), npc_solenorAI::Transform(), npc_artoriusAI::Transform(), npc_kyle_the_frenziedAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_harrison_jones_zaAI::WaypointReached(), and npc_marshal_windsorAI::WaypointReached().
UpdateImmunitiesSet()
void Creature::UpdateImmunitiesSet (uint32 immunitySet)
Definition at line 2408 of file Creature.cpp.
References Unit::ApplySpellImmune(), GetCreatureInfo(), m_immunitySet, and sObjectMgr.
Referenced by CreatureEventAI::ProcessAction(), and UpdateEntry().
UpdateMaxHealth()
void Creature::UpdateMaxHealth () override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 847 of file StatSystem.cpp.
References BASE_PCT, BASE_VALUE, Unit::GetCreateHealth(), Unit::GetModifierValue(), Unit::SetMaxHealth(), TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_HEALTH.
Referenced by UpdateAllStats().
UpdateMaxPower()
void Creature::UpdateMaxPower (Powers power) override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 859 of file StatSystem.cpp.
References BASE_PCT, BASE_VALUE, Unit::GetCreatePowers(), Unit::GetModifierValue(), Unit::SetMaxPower(), TOTAL_PCT, TOTAL_VALUE, and UNIT_MOD_POWER_START.
Referenced by UpdateAllStats().
UpdateResistances()
void Creature::UpdateResistances (uint32 school) override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 830 of file StatSystem.cpp.
References Unit::GetTotalResistanceValue(), Unit::SetResistance(), SPELL_SCHOOL_NORMAL, and UpdateArmor().
Referenced by UpdateAllStats(), and Pet::UpdateResistances().
UpdateSpell()
void Creature::UpdateSpell (int32 index, int32 newSpellId)
Definition at line 2370 of file Creature.cpp.
References m_spellList, and CreatureSpellList::Spells.
UpdateStats()
bool Creature::UpdateStats (Stats stat) override virtual
Implements Unit.
Reimplemented in Totem, and Pet.
Definition at line 810 of file StatSystem.cpp.
UpdateVendorItemCurrentCount()
uint32 Creature::UpdateVendorItemCurrentCount (VendorItem const * vItem, uint32 used_count)
Definition at line 2543 of file Creature.cpp.
References ItemPrototype::BuyCount, VendorItemCount::count, ObjectMgr::GetItemPrototype(), VendorItem::incrtime, VendorItem::item, VendorItemCount::lastIncrementTime, m_vendorItemCounts, and VendorItem::maxcount.
Referenced by Player::BuyItemFromVendorSlot().
Field Documentation
m_ai
std::unique_ptr<UnitAI> Creature::m_ai protected
Definition at line 939 of file Creature.h.
Referenced by AI(), Pet::AI(), and AIM_Initialize().
m_AlreadyCallAssistance
bool Creature::m_AlreadyCallAssistance protected
Definition at line 926 of file Creature.h.
Referenced by CallAssistance(), and SetNoCallAssistance().
m_canAggro
bool Creature::m_canAggro protected
Definition at line 913 of file Creature.h.
Referenced by CanAggro(), and SetCanAggro().
m_canCallForAssistance
bool Creature::m_canCallForAssistance protected
Definition at line 927 of file Creature.h.
Referenced by CanCallForAssistance(), and SetCanCallForAssistance().
m_checkForHelp
bool Creature::m_checkForHelp protected
Definition at line 914 of file Creature.h.
Referenced by CanCheckForHelp(), and SetCanCheckForHelp().
m_combatStartPos
Position Creature::m_combatStartPos protected
Definition at line 932 of file Creature.h.
Referenced by GetCombatStartPosition(), and SetCombatStartPosition().
m_corpseAccelerationDecayDelay
uint32 Creature::m_corpseAccelerationDecayDelay protected
Definition at line 903 of file Creature.h.
Referenced by InspectingLoot(), ReduceCorpseDecayTimer(), and SetCorpseAccelerationDelay().
m_corpseDelay
uint32 Creature::m_corpseDelay protected
Definition at line 911 of file Creature.h.
Referenced by InitEntry(), LoadFromDB(), SetCorpseDelay(), and SetDeathState().
m_corpseExpirationTime
TimePoint Creature::m_corpseExpirationTime protected
Timers.
Definition at line 906 of file Creature.h.
Referenced by GetCorpseDecayTimer(), GetRespawnTimeEx(), InspectingLoot(), IsCorpseExpired(), ReduceCorpseDecayTimer(), RemoveCorpse(), Pet::ResetCorpseRespawn(), SaveRespawnTime(), SetDeathState(), and SetLootStatus().
m_countSpawns
bool Creature::m_countSpawns protected
Definition at line 948 of file Creature.h.
Referenced by AddToWorld(), RemoveFromWorld(), SetSpawnCounting(), and UpdateEntry().
m_creatureGroup
CreatureGroup* Creature::m_creatureGroup protected
Definition at line 957 of file Creature.h.
Referenced by ClearCreatureGroup(), GetCreatureGroup(), LoadFromDB(), and SetCreatureGroup().
m_creatureInfo
CreatureInfo const* Creature::m_creatureInfo private
Definition at line 965 of file Creature.h.
Referenced by GetCreatureInfo(), InitEntry(), IsCritter(), SetBaseRunSpeed(), SetBaseWalkSpeed(), and SetLootStatus().
m_defaultMovementType
MovementGeneratorType Creature::m_defaultMovementType protected
Definition at line 921 of file Creature.h.
Referenced by GetDefaultMovementType(), InitEntry(), and SetDefaultMovementType().
m_detectionRange
uint32 Creature::m_detectionRange protected
Definition at line 923 of file Creature.h.
Referenced by GetDetectionRange(), and SetDetectionRange().
m_equipmentId
uint32 Creature::m_equipmentId protected
Definition at line 922 of file Creature.h.
Referenced by GetCurrentEquipmentId(), GetEquipmentId(), and LoadEquipment().
m_forceAttackingCapability
bool Creature::m_forceAttackingCapability protected
Definition at line 942 of file Creature.h.
Referenced by CanInitiateAttack(), GetForceAttackingCapability(), and SetForceAttackingCapability().
m_gameEventVendorId
uint32 Creature::m_gameEventVendorId protected
Definition at line 935 of file Creature.h.
m_gossipMenuId
uint32 Creature::m_gossipMenuId protected
Definition at line 898 of file Creature.h.
Referenced by GetDefaultGossipMenuId(), and SetDefaultGossipMenuId().
m_gridRef
GridReference<Creature> Creature::m_gridRef private
Definition at line 964 of file Creature.h.
Referenced by GetGridRef().
m_hitBySpells
std::set<uint32> Creature::m_hitBySpells protected
Definition at line 952 of file Creature.h.
Referenced by HasBeenHitBySpell(), RegisterHitBySpell(), ResetSpellHitCounter(), and UnregisterHitBySpell().
m_ignoreMMAP
bool Creature::m_ignoreMMAP protected
Definition at line 941 of file Creature.h.
Referenced by IsIgnoringMMAP(), SetIgnoreMMAP(), and UpdateEntry().
m_immunitySet
uint32 Creature::m_immunitySet protected
Definition at line 937 of file Creature.h.
Referenced by UpdateImmunitiesSet().
m_imposedCooldown
bool Creature::m_imposedCooldown protected
Definition at line 961 of file Creature.h.
Referenced by StartCooldown().
m_interactionPauseTimer
uint32 Creature::m_interactionPauseTimer protected
Definition at line 916 of file Creature.h.
Referenced by GetInteractionPauseTimer(), and InitEntry().
m_isInvisible
bool Creature::m_isInvisible protected
Definition at line 940 of file Creature.h.
Referenced by IsInvisible(), SetInvisible(), and UpdateEntry().
m_killer
ObjectGuid Creature::m_killer protected
Definition at line 959 of file Creature.h.
Referenced by GetKillerGuid(), SetDeathState(), and SetKillerGuid().
m_lootGroupRecipientId
uint32 Creature::m_lootGroupRecipientId protected
Definition at line 901 of file Creature.h.
Referenced by GetGroupLootRecipient(), GetLootGroupRecipientId(), HasLootRecipient(), IsGroupLootRecipient(), and SetLootRecipient().
m_lootMoney
uint32 Creature::m_lootMoney protected
Definition at line 899 of file Creature.h.
m_lootRecipientGuid
ObjectGuid Creature::m_lootRecipientGuid protected
Definition at line 900 of file Creature.h.
Referenced by GetLootRecipientGuid(), GetOriginalLootRecipient(), HasLootRecipient(), and SetLootRecipient().
m_lootStatus
CreatureLootStatus Creature::m_lootStatus protected
Definition at line 902 of file Creature.h.
Referenced by GetLootStatus(), PrepareBodyLootState(), RemoveCorpse(), and SetLootStatus().
m_noReputation
bool Creature::m_noReputation protected
Definition at line 943 of file Creature.h.
Referenced by IsNoReputation(), and SetNoReputation().
m_onlyVisibleTo
ObjectGuid Creature::m_onlyVisibleTo protected
Definition at line 949 of file Creature.h.
Referenced by IsOnlyVisibleTo(), and SetOnlyVisibleTo().
m_originalEntry
uint32 Creature::m_originalEntry protected
Definition at line 930 of file Creature.h.
Referenced by Pet::Create(), CreateFromProto(), and ResetEntry().
m_pickpocketRestockTime
TimePoint Creature::m_pickpocketRestockTime protected
Definition at line 912 of file Creature.h.
Referenced by CanRestockPickpocketLoot(), and StartPickpocketRestockTimer().
m_respawnDelay
uint32 Creature::m_respawnDelay protected
Definition at line 908 of file Creature.h.
Referenced by GetRespawnDelay(), LoadFromDB(), SaveToDB(), SetDeathState(), SetRespawnDelay(), and TemporarySpawn::SetSummonProperties().
m_respawnOverriden
bool Creature::m_respawnOverriden protected
Definition at line 909 of file Creature.h.
Referenced by SetDeathState(), and SetRespawnDelay().
m_respawnOverrideOnce
bool Creature::m_respawnOverrideOnce protected
Definition at line 910 of file Creature.h.
Referenced by SetDeathState(), and SetRespawnDelay().
m_respawnPos
Position Creature::m_respawnPos protected
Definition at line 933 of file Creature.h.
Referenced by GetRespawnCoord(), GetRespawnPosition(), InitEntry(), ResetRespawnCoord(), and SetRespawnCoord().
m_respawnradius
float Creature::m_respawnradius protected
Definition at line 915 of file Creature.h.
Referenced by GetRespawnRadius(), LoadFromDB(), SaveToDB(), and SetRespawnRadius().
m_respawnTime
time_t Creature::m_respawnTime protected
Definition at line 907 of file Creature.h.
Referenced by GetRespawnTime(), GetRespawnTimeEx(), LoadFromDB(), RemoveCorpse(), Respawn(), SaveRespawnTime(), SetDeathState(), SetRespawnTime(), and Update().
m_settings
CreatureSettings Creature::m_settings protected
Definition at line 945 of file Creature.h.
Referenced by GetSettings(), IsIgnoringFeignDeath(), IsNoLoot(), IsNoWeaponSkillGain(), IsNoWoundedSlowdown(), IsNoXp(), IsPreventingDeath(), SetIgnoreFeignDeath(), SetNoLoot(), SetNoWeaponSkillGain(), SetNoWoundedSlowdown(), SetNoXP(), and UpdateEntry().
m_spellList
CreatureSpellList Creature::m_spellList protected
Definition at line 955 of file Creature.h.
Referenced by GetCharmSpells(), Totem::GetSpell(), GetSpellCooldown(), GetSpellList(), HasSpell(), ReachWithSpellAttack(), ReachWithSpellCure(), SetSpellList(), Totem::Summon(), and UpdateSpell().
m_subtype
CreatureSubtype Creature::m_subtype protected
Definition at line 918 of file Creature.h.
Referenced by GetSubtype(), IsPet(), IsTemporarySummon(), and IsTotem().
m_temporaryFactionFlags
uint32 Creature::m_temporaryFactionFlags protected
Definition at line 928 of file Creature.h.
Referenced by ClearTemporaryFaction(), GetTemporaryFactionFlags(), and SetFactionTemporary().
m_vendorItemCounts
VendorItemCounts Creature::m_vendorItemCounts protected
Definition at line 896 of file Creature.h.
Referenced by CleanupsBeforeDelete(), GetVendorItemCurrentCount(), and UpdateVendorItemCurrentCount().
The documentation for this class was generated from the following files:
Creature.h
Creature.cpp
Relations.cpp
StatSystem.cpp