CMaNGOS_WoTLK: BattleGroundIC Class Reference
BattleGroundIC Class Reference
#include <BattleGroundIC.h>
Public Member Functions
BattleGroundIC ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *plr) override
Method that is called when adding a player to the battleground.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
void HandleCreatureCreate (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleKillUnit (Creature *creature, Player *killer) override
void HandleKillPlayer (Player *player, Player *killer) override
Method that handles killing players.
void HandlePlayerClickedOnFlag (Player *player, GameObject *go) override
void HandleGameObjectDamaged (Player *player, GameObject *object, uint32 spellId) override
bool CheckAchievementCriteriaMeet (uint32 criteriaId, Player const *source, Unit const *target, uint32 miscvalue1) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual bool HandleAreaTrigger (Player *, uint32)
virtual void HandlePlayerDroppedFlag (Player *)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual Team GetPrematureWinner ()
Function that returns the premature winner.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Private Member Functions
void DoApplyTeamBuff (PvpTeamIndex teamIdx, uint32 spellEntry, bool apply)
void DoCaptureObjective (IsleObjective nodeId)
void DoApplyObjectiveBenefits (IsleObjective nodeId, GameObject *objRef)
void DoResetObjective (IsleObjective nodeId)
void DoChangeBannerState (IsleObjective nodeId)
void DoUpdateReinforcements (PvpTeamIndex teamIdx, int32 value)
int32 GetReinforcements (PvpTeamIndex teamIdx)
void SetReinforcements (PvpTeamIndex teamIdx, int32 reinforcements)
Private Attributes
IsleNode m_isleNode [BG_IC_MAX_OBJECTIVES]
ObjectGuid m_keepGatesGuid [PVP_TEAM_COUNT][BG_IC_MAX_KEEP_GATES]
ObjectGuid m_workshopMechanicGuids [PVP_TEAM_COUNT]
ObjectGuid m_hordeInnerGateGuid
ObjectGuid m_allianceInnerGate1Guid
ObjectGuid m_allianceInnerGate2Guid
uint32 m_gatesAllianceState [BG_IC_MAX_KEEP_GATES]
uint32 m_gatesHordeState [BG_IC_MAX_KEEP_GATES]
uint32 m_resourceTickTimer [BG_IC_MAX_RESOURCE_NODES]
uint32 m_closeDoorTimer
bool m_isKeepInvaded [PVP_TEAM_COUNT]
std::set< uint32 > m_hangarPortalsGuids [PVP_TEAM_COUNT]
std::set< uint32 > m_hangarAnimGuids [PVP_TEAM_COUNT]
std::set< uint32 > m_seaforiumBombsGuids [PVP_TEAM_COUNT]
GuidList m_towerGatesGuids
GuidList m_teleporterGuids
GuidList m_teleporterAnimGuids
GuidList m_boatFiresGuids
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
virtual void RemovePlayer (Player *, ObjectGuid)
Method that handles generic logic when removing a player.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 704 of file BattleGroundIC.h.
Constructor & Destructor Documentation
BattleGroundIC()
BattleGroundIC::BattleGroundIC ()
Definition at line 28 of file BattleGroundIC.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_IC_BEGIN, LANG_BG_IC_START_HALF_MINUTE, LANG_BG_IC_START_ONE_MINUTE, LANG_BG_IC_START_TWO_MINUTES, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundIC::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 135 of file BattleGroundIC.cpp.
References BattleGround::AddPlayer(), ALLIANCE, BG_IC_OBJECTIVE_KEEP_ALLY, BG_IC_OBJECTIVE_KEEP_HORDE, BG_IC_OBJECTIVE_QUARY, BG_IC_OBJECTIVE_REFINERY, BG_IC_SPELL_QUARRY, BG_IC_SPELL_REFINERY, BG_NPC_HON_DEFENDER_TRIGGER_A, BG_NPC_HON_DEFENDER_TRIGGER_H, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, Unit::CastSpell(), IsleNode::creatureGuids, Object::GetObjectGuid(), Player::GetTeam(), GetTeamIdByTeamIndex(), IsleNode::honorableDefenderGuid, HORDE, iocHonorTriggerAllySpawns, iocHonorTriggerHordeSpawns, isleGraveyardData, isleObjectiveData, m_isleNode, BattleGround::m_playerScores, IsleGraveyardSpawnData::o, IsleNode::spiritHealerGuid, WorldObject::SummonCreature(), TEAM_INDEX_NEUTRAL, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, IsleObjectiveBasicData::x, IsleGraveyardSpawnData::x, IsleObjectiveBasicData::y, IsleGraveyardSpawnData::y, IsleObjectiveBasicData::z, and IsleGraveyardSpawnData::z.
CheckAchievementCriteriaMeet()
bool BattleGroundIC::CheckAchievementCriteriaMeet (uint32 criteriaId, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 675 of file BattleGroundIC.cpp.
References BG_IC_CRIT_GLAIVE_GRAVE, BG_IC_CRIT_MINE_A_1, BG_IC_CRIT_MINE_A_2, BG_IC_CRIT_MINE_H_1, BG_IC_CRIT_MINE_H_2, BG_IC_CRIT_MOVED_DOWN_PLAYER, BG_IC_CRIT_MOVED_DOWN_VEHICLE, BG_IC_CRIT_RESOURCE_GLUT_A, BG_IC_CRIT_RESOURCE_GLUT_H, BG_IC_OBJECTIVE_DOCKS, BG_IC_OBJECTIVE_HANGAR, BG_IC_OBJECTIVE_QUARY, BG_IC_OBJECTIVE_REFINERY, BG_IC_OBJECTIVE_WORKSHOP, BG_IC_VEHICLE_GLAIVE_THROWER_A, BG_IC_VEHICLE_GLAIVE_THROWER_H, BG_IC_VEHICLE_KEEP_CANNON, Object::GetEntry(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), WorldObject::IsBoarded(), m_isleNode, IsleNode::nodeOwner, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
DoApplyObjectiveBenefits()
void BattleGroundIC::DoApplyObjectiveBenefits (IsleObjective nodeId, GameObject * objRef) private
Definition at line 755 of file BattleGroundIC.cpp.
References BG_IC_OBJECTIVE_DOCKS, BG_IC_OBJECTIVE_HANGAR, BG_IC_OBJECTIVE_KEEP_ALLY, BG_IC_OBJECTIVE_KEEP_HORDE, BG_IC_OBJECTIVE_QUARY, BG_IC_OBJECTIVE_REFINERY, BG_IC_OBJECTIVE_WORKSHOP, BG_IC_RESOURCE_QUARY, BG_IC_RESOURCE_REFINERY, BG_IC_RESOURCE_TICK_TIMER, BG_IC_ZONE_ID_ISLE, BG_NPC_HON_DEFENDER_TRIGGER_A, BG_NPC_HON_DEFENDER_TRIGGER_H, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, BattleGround::ChangeBgObjectSpawnState(), IsleNode::creatureGuids, DoApplyTeamBuff(), BattleGround::GetBgMap(), Map::GetGraveyardManager(), GetTeamIdByTeamIndex(), GO_STATE_ACTIVE, IsleObjectiveBasicData::graveyardId, HIGHGUID_MO_TRANSPORT, IsleNode::honorableDefenderGuid, iocBoatsSpawns, iocDocksSpawns, iocGunships, iocHangarSpawns, iocHonorTriggerAllySpawns, iocHonorTriggerHordeSpawns, iocRefinerySpawns, iocWorkshopSpawns, isleGraveyardData, isleObjectiveData, m_hangarAnimGuids, m_hangarPortalsGuids, m_isleNode, m_resourceTickTimer, m_seaforiumBombsGuids, IsleNode::nodeOwner, IsleGraveyardSpawnData::o, RESPAWN_IMMEDIATELY, GraveyardManager::SetGraveYardLinkTeam(), IsleNode::specialCreatureGuid, IsleObjectiveBasicData::spellEntry, IsleNode::spiritHealerGuid, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEMPSPAWN_DEAD_DESPAWN, IsleObjectiveBasicData::x, IsleGraveyardSpawnData::x, IsleObjectiveBasicData::y, IsleGraveyardSpawnData::y, IsleObjectiveBasicData::z, and IsleGraveyardSpawnData::z.
Referenced by DoCaptureObjective(), and HandlePlayerClickedOnFlag().
DoApplyTeamBuff()
void BattleGroundIC::DoApplyTeamBuff (PvpTeamIndex teamIdx, uint32 spellEntry, bool apply) private
Definition at line 1016 of file BattleGroundIC.cpp.
References ByteConverter::apply(), BattleGround::CastSpellOnTeam(), GetTeamIdByTeamIndex(), BattleGround::m_players, and sObjectMgr.
Referenced by DoApplyObjectiveBenefits(), and DoResetObjective().
DoCaptureObjective()
void BattleGroundIC::DoCaptureObjective (IsleObjective nodeId) private
Definition at line 715 of file BattleGroundIC.cpp.
References IsleNode::bannerChangeTimer, BG_IC_SOUND_NODE_CAPTURED_ALLIANCE, BG_IC_SOUND_NODE_CAPTURED_HORDE, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, IsleNode::currentBannerEntry, DoApplyObjectiveBenefits(), BattleGround::GetBgMap(), BattleGround::GetSingleGameObjectFromStorage(), Map::GetVariableManager(), isleGameObjectConquerData, isleObjectiveData, LANG_BG_AB_NODE_TAKEN, LANG_BG_ALLY, LANG_BG_HORDE, m_isleNode, IsleNode::nodeConquerer, IsleNode::nodeOwner, IsleNode::nodeWorldState, IsleNode::oldBannerEntry, BattleGround::PlaySoundToAll(), BattleGround::SendMessage2ToAll(), WorldStateVariableManager::SetVariable(), TEAM_INDEX_ALLIANCE, WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
Referenced by Update().
DoChangeBannerState()
void BattleGroundIC::DoChangeBannerState (IsleObjective nodeId) private
Definition at line 705 of file BattleGroundIC.cpp.
References BattleGround::ChangeBgObjectSpawnState(), BattleGround::GetSingleGameObjectFromStorage(), m_isleNode, RESPAWN_IMMEDIATELY, and RESPAWN_ONE_DAY.
Referenced by Update().
DoResetObjective()
void BattleGroundIC::DoResetObjective (IsleObjective nodeId) private
Definition at line 885 of file BattleGroundIC.cpp.
References AI_EVENT_CUSTOM_A, BG_IC_OBJECTIVE_DOCKS, BG_IC_OBJECTIVE_HANGAR, BG_IC_OBJECTIVE_KEEP_ALLY, BG_IC_OBJECTIVE_KEEP_HORDE, BG_IC_OBJECTIVE_QUARY, BG_IC_OBJECTIVE_REFINERY, BG_IC_OBJECTIVE_WORKSHOP, BG_IC_RESOURCE_QUARY, BG_IC_RESOURCE_REFINERY, BG_IC_SPELL_BOAT_FIRE, BG_IC_ZONE_ID_ISLE, BattleGround::ChangeBgObjectSpawnState(), IsleNode::creatureGuids, DoApplyTeamBuff(), BattleGround::GetBgMap(), Map::GetGraveyardManager(), GO_STATE_READY, IsleObjectiveBasicData::graveyardId, HIGHGUID_MO_TRANSPORT, iocGunships, isleObjectiveData, m_boatFiresGuids, m_hangarAnimGuids, m_hangarPortalsGuids, m_isleNode, m_resourceTickTimer, m_seaforiumBombsGuids, IsleNode::nodeOwner, RESPAWN_ONE_DAY, GraveyardManager::SetGraveYardLinkTeam(), IsleObjectiveBasicData::spellEntry, TEAM_INVALID, and TRIGGERED_OLD_TRIGGERED.
Referenced by HandlePlayerClickedOnFlag().
DoUpdateReinforcements()
void BattleGroundIC::DoUpdateReinforcements (PvpTeamIndex teamIdx, int32 value) private
Definition at line 498 of file BattleGroundIC.cpp.
References GetReinforcements(), and SetReinforcements().
Referenced by HandleKillPlayer(), and Update().
EndBattleGround()
void BattleGroundIC::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 663 of file BattleGroundIC.cpp.
References ALLIANCE, BattleGround::EndBattleGround(), BattleGround::GetBonusHonorFromKill(), HORDE, and BattleGround::RewardHonorToTeam().
Referenced by HandleKillPlayer(), and HandleKillUnit().
GetReinforcements()
int32 BattleGroundIC::GetReinforcements (PvpTeamIndex teamIdx) private
Definition at line 503 of file BattleGroundIC.cpp.
References BG_IC_STATE_ALLY_REINFORCE_COUNT, BG_IC_STATE_HORDE_REINFORCE_COUNT, BattleGround::GetBgMap(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), and TEAM_INDEX_ALLIANCE.
Referenced by DoUpdateReinforcements(), and HandleKillPlayer().
HandleCreatureCreate()
void BattleGroundIC::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from BattleGround.
Definition at line 522 of file BattleGroundIC.cpp.
References BG_IC_FACTION_ID_ALLIANCE, BG_IC_FACTION_ID_HORDE, BG_IC_NPC_BOAT_FIRE, BG_IC_NPC_GNOMISH_MECHANIC, BG_IC_NPC_GOBLIN_MECHANIC, BG_IC_OBJECTIVE_DOCKS, BG_IC_OBJECTIVE_WORKSHOP, BG_IC_VEHICLE_CATAPULT, BG_IC_VEHICLE_DEMOLISHER, BG_IC_VEHICLE_KEEP_CANNON, Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), iocTeamFactions, m_boatFiresGuids, m_isleNode, m_workshopMechanicGuids, IsleNode::nodeOwner, Creature::SetFactionTemporary(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and TEMPFACTION_NONE.
HandleEvent()
bool BattleGroundIC::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from BattleGround.
Definition at line 243 of file BattleGroundIC.cpp.
References BG_IC_GO_BANNER_ALLIANCE_KEEP_A, BG_IC_GO_BANNER_HORDE_KEEP_H, BG_IC_MAX_KEEP_GATES, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, DEBUG_LOG, GAMEOBJECT_FLAGS, BattleGround::GetBgMap(), Object::GetEntry(), BattleGround::GetSingleGameObjectFromStorage(), Map::GetVariableManager(), GO_FLAG_NO_INTERACT, iocAllianceKeepSpawns, iocHordeKeepSpawns, Object::IsGameObject(), isleAllianceWallsData, isleHordeWallsData, m_allianceInnerGate1Guid, m_allianceInnerGate2Guid, m_gatesAllianceState, m_gatesHordeState, m_hordeInnerGateGuid, m_isKeepInvaded, m_keepGatesGuid, Object::RemoveFlag(), BattleGround::SendMessage2ToAll(), WorldStateVariableManager::SetVariable(), IsleWallsData::stateOpened, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEMPSPAWN_DEAD_DESPAWN, WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
HandleGameObjectCreate()
void BattleGroundIC::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 554 of file BattleGroundIC.cpp.
References BG_IC_GATE_EAST, BG_IC_GATE_FRONT, BG_IC_GATE_WEST, BG_IC_GO_BANNER_ALLIANCE_KEEP_A, BG_IC_GO_BANNER_ALLIANCE_KEEP_A_GREY, BG_IC_GO_BANNER_ALLIANCE_KEEP_H, BG_IC_GO_BANNER_ALLIANCE_KEEP_H_GREY, BG_IC_GO_BANNER_DOCKS, BG_IC_GO_BANNER_DOCKS_A, BG_IC_GO_BANNER_DOCKS_A_GREY, BG_IC_GO_BANNER_DOCKS_H, BG_IC_GO_BANNER_DOCKS_H_GREY, BG_IC_GO_BANNER_HANGAR, BG_IC_GO_BANNER_HANGAR_A, BG_IC_GO_BANNER_HANGAR_A_GREY, BG_IC_GO_BANNER_HANGAR_H, BG_IC_GO_BANNER_HANGAR_H_GREY, BG_IC_GO_BANNER_HORDE_KEEP_A, BG_IC_GO_BANNER_HORDE_KEEP_A_GREY, BG_IC_GO_BANNER_HORDE_KEEP_H, BG_IC_GO_BANNER_HORDE_KEEP_H_GREY, BG_IC_GO_BANNER_QUARRY, BG_IC_GO_BANNER_QUARRY_A, BG_IC_GO_BANNER_QUARRY_A_GREY, BG_IC_GO_BANNER_QUARRY_H, BG_IC_GO_BANNER_QUARRY_H_GREY, BG_IC_GO_BANNER_REFINERY, BG_IC_GO_BANNER_REFINERY_A, BG_IC_GO_BANNER_REFINERY_A_GREY, BG_IC_GO_BANNER_REFINERY_H, BG_IC_GO_BANNER_REFINERY_H_GREY, BG_IC_GO_BANNER_WORKSHOP, BG_IC_GO_BANNER_WORKSHOP_A, BG_IC_GO_BANNER_WORKSHOP_A_GREY, BG_IC_GO_BANNER_WORKSHOP_H, BG_IC_GO_BANNER_WORKSHOP_H_GREY, BG_IC_GO_GUNSHIP_A, BG_IC_GO_GUNSHIP_GROUND_PORTAL_A, BG_IC_GO_GUNSHIP_GROUND_PORTAL_H, BG_IC_GO_GUNSHIP_H, BG_IC_GO_GUNSHIP_PORTAL_EFFECTS_A, BG_IC_GO_GUNSHIP_PORTAL_EFFECTS_H, BG_IC_GO_PORTCULLIS_GATE_A, BG_IC_GO_PORTCULLIS_GATE_H, BG_IC_GO_PORTCULLIS_KEEP_A1, BG_IC_GO_PORTCULLIS_KEEP_A2, BG_IC_GO_PORTCULLIS_KEEP_H, BG_IC_GO_PORTCULLIS_TOWER_A, BG_IC_GO_PORTCULLIS_TOWER_H, BG_IC_GO_SEAFORIUM_BOMBS_A, BG_IC_GO_SEAFORIUM_BOMBS_H, BG_IC_GO_TELEPORTER_EFFECTS_A, BG_IC_GO_TELEPORTER_EFFECTS_H, BG_IC_GO_TELEPORTER_INSIDE_A, BG_IC_GO_TELEPORTER_INSIDE_H, BG_IC_GO_TELEPORTER_OUTSIDE_A, BG_IC_GO_TELEPORTER_OUTSIDE_H, Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), m_allianceInnerGate1Guid, m_allianceInnerGate2Guid, BattleGround::m_goEntryGuidStore, m_hangarAnimGuids, m_hangarPortalsGuids, m_hordeInnerGateGuid, m_keepGatesGuid, m_seaforiumBombsGuids, m_teleporterAnimGuids, m_teleporterGuids, m_towerGatesGuids, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
HandleGameObjectDamaged()
void BattleGroundIC::HandleGameObjectDamaged (Player * player, GameObject * object, uint32 spellId) override virtual
Reimplemented from BattleGround.
Definition at line 513 of file BattleGroundIC.cpp.
References BG_IC_SPELL_BOMB_CREDIT, BG_IC_SPELL_HUGE_BOMB_CREDIT, BG_IC_SPELL_HUGE_SEAFORIUM_BLAST, BG_IC_SPELL_SEAFORIUM_BLAST, Unit::CastSpell(), and TRIGGERED_OLD_TRIGGERED.
HandleKillPlayer()
void BattleGroundIC::HandleKillPlayer (Player * player, Player * killer) override virtual
Method that handles killing players.
also handles generic logic for arena updates
Parameters
victim player
killer player
Reimplemented from BattleGround.
Definition at line 481 of file BattleGroundIC.cpp.
References DoUpdateReinforcements(), EndBattleGround(), GetReinforcements(), BattleGround::GetStatus(), Player::GetTeam(), GetTeamIndexByTeamId(), BattleGround::HandleKillPlayer(), and STATUS_IN_PROGRESS.
HandleKillUnit()
void BattleGroundIC::HandleKillUnit (Creature * creature, Player * killer) override virtual
Reimplemented from BattleGround.
Definition at line 434 of file BattleGroundIC.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_EVENTAI_B, ALLIANCE, BG_IC_BONUS_HONOR_BOSS_KILL, BG_IC_NPC_COMMANDER_WYRMBANE, BG_IC_NPC_OVERLORD_AGMAR, BG_IC_OBJECTIVE_WORKSHOP, BG_IC_SPELL_ACHIEV_DESTROYED_VEHICLE, BG_IC_VEHICLE_CATAPULT, BG_IC_VEHICLE_DEMOLISHER, BG_IC_VEHICLE_GLAIVE_THROWER_A, BG_IC_VEHICLE_GLAIVE_THROWER_H, BG_IC_VEHICLE_SIEGE_ENGINE_A, BG_IC_VEHICLE_SIEGE_ENGINE_H, Unit::CastSpell(), IsleNode::creatureGuids, DEBUG_LOG, EndBattleGround(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), Object::GetEntry(), BattleGround::GetStatus(), HORDE, iocWorkshopSpawns, m_isleNode, m_workshopMechanicGuids, IsleDualSummonData::o, BattleGround::RewardHonorToTeam(), UnitAI::SendAIEvent(), STATUS_IN_PROGRESS, WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, IsleDualSummonData::x, IsleDualSummonData::y, and IsleDualSummonData::z.
HandlePlayerClickedOnFlag()
void BattleGroundIC::HandlePlayerClickedOnFlag (Player * player, GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 325 of file BattleGroundIC.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, IsleNode::bannerChangeTimer, BG_IC_FLAG_CAPTURING_TIME, BG_IC_SOUND_NODE_ASSAULTED_ALLIANCE, BG_IC_SOUND_NODE_ASSAULTED_HORDE, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, IsleNode::currentBannerEntry, DEBUG_LOG, DoApplyObjectiveBenefits(), DoResetObjective(), BattleGround::GetBgMap(), Object::GetEntry(), Player::GetTeam(), GetTeamIndexByTeamId(), Map::GetVariableManager(), isleGameObjectContestedData, isleGameObjectNeutralData, isleGameObjectOwnedData, isleObjectiveData, LANG_BG_ALLY, LANG_BG_HORDE, LANG_BG_IC_NODE_ASSAULTED, LANG_BG_IC_NODE_DEFENDED, m_isleNode, IsleNode::nodeChangeTimer, IsleNode::nodeConquerer, IsleNode::nodeOwner, IsleNode::nodeWorldState, IsleNode::oldBannerEntry, BattleGround::PlaySoundToAll(), SCORE_BASES_ASSAULTED, SCORE_BASES_DEFENDED, BattleGround::SendMessage2ToAll(), WorldStateVariableManager::SetVariable(), TEAM_INDEX_ALLIANCE, Player::UpdateAchievementCriteria(), UpdatePlayerScore(), WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
Reset()
void BattleGroundIC::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 38 of file BattleGroundIC.cpp.
References ALLIANCE, IsleNode::bannerChangeTimer, BG_IC_GRAVEYARD_ID_ALLIANCE, BG_IC_GRAVEYARD_ID_DOCKS, BG_IC_GRAVEYARD_ID_HANGAR, BG_IC_GRAVEYARD_ID_HORDE, BG_IC_GRAVEYARD_ID_KEEP_ALLY, BG_IC_GRAVEYARD_ID_KEEP_HORDE, BG_IC_GRAVEYARD_ID_WORKSHOP, BG_IC_MAX_KEEP_GATES, BG_IC_MAX_OBJECTIVES, BG_IC_MAX_REINFORCEMENTS, BG_IC_MAX_RESOURCE_NODES, BG_IC_OBJECTIVE_KEEP_ALLY, BG_IC_OBJECTIVE_KEEP_HORDE, BG_IC_STATE_ALLY_REINFORCE_COUNT, BG_IC_STATE_ALLY_REINFORCE_SHOW, BG_IC_STATE_HORDE_REINFORCE_COUNT, BG_IC_STATE_HORDE_REINFORCE_SHOW, BG_IC_ZONE_ID_ISLE, BattleGround::GetBgMap(), Map::GetGraveyardManager(), Map::GetVariableManager(), HORDE, iocDefaultStates, isleAllianceWallsData, isleGameObjectConquerData, isleGameObjectContestedData, isleGameObjectNeutralData, isleGameObjectOwnedData, isleHordeWallsData, m_closeDoorTimer, m_gatesAllianceState, m_gatesHordeState, m_isKeepInvaded, m_isleNode, m_resourceTickTimer, IsleNode::nodeChangeTimer, IsleNode::nodeConquerer, IsleNode::nodeOwner, IsleNode::nodeWorldState, PVP_TEAM_COUNT, BattleGround::Reset(), GraveyardManager::SetGraveYardLinkTeam(), SetReinforcements(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_INDEX_NEUTRAL, TEAM_INVALID, and WORLD_STATE_ADD.
SetReinforcements()
void BattleGroundIC::SetReinforcements (PvpTeamIndex teamIdx, int32 reinforcements) private
Definition at line 508 of file BattleGroundIC.cpp.
References BG_IC_STATE_ALLY_REINFORCE_COUNT, BG_IC_STATE_HORDE_REINFORCE_COUNT, BattleGround::GetBgMap(), Map::GetVariableManager(), WorldStateVariableManager::SetVariable(), and TEAM_INDEX_ALLIANCE.
Referenced by DoUpdateReinforcements(), and Reset().
StartingEventOpenDoors()
void BattleGroundIC::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 191 of file BattleGroundIC.cpp.
References BG_IC_CLOSE_DOORS_TIME, GAMEOBJECT_FLAGS, BattleGround::GetBgMap(), GO_FLAG_NO_INTERACT, m_closeDoorTimer, m_keepGatesGuid, m_teleporterAnimGuids, m_teleporterGuids, m_towerGatesGuids, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Update()
void BattleGroundIC::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 1036 of file BattleGroundIC.cpp.
References IsleNode::bannerChangeTimer, BG_IC_MAX_OBJECTIVES, BG_IC_MAX_RESOURCE_NODES, BG_IC_OBJECTIVE_QUARY, BG_IC_OBJECTIVE_REFINERY, BG_IC_RESOURCE_QUARY, BG_IC_RESOURCE_REFINERY, BG_IC_RESOURCE_TICK_TIMER, DoCaptureObjective(), DoChangeBannerState(), DoUpdateReinforcements(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), GetTeamIdByTeamIndex(), m_closeDoorTimer, m_isleNode, m_keepGatesGuid, m_resourceTickTimer, IsleNode::nodeChangeTimer, IsleNode::nodeOwner, BattleGround::RewardHonorToTeam(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, and BattleGround::Update().
UpdatePlayerScore()
void BattleGroundIC::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 221 of file BattleGroundIC.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_BASES_ASSAULTED, SCORE_BASES_DEFENDED, and BattleGround::UpdatePlayerScore().
Referenced by HandlePlayerClickedOnFlag().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 706 of file BattleGroundIC.h.
Field Documentation
m_allianceInnerGate1Guid
ObjectGuid BattleGroundIC::m_allianceInnerGate1Guid private
Definition at line 750 of file BattleGroundIC.h.
Referenced by HandleEvent(), and HandleGameObjectCreate().
m_allianceInnerGate2Guid
ObjectGuid BattleGroundIC::m_allianceInnerGate2Guid private
Definition at line 751 of file BattleGroundIC.h.
Referenced by HandleEvent(), and HandleGameObjectCreate().
m_boatFiresGuids
GuidList BattleGroundIC::m_boatFiresGuids private
Definition at line 766 of file BattleGroundIC.h.
Referenced by DoResetObjective(), and HandleCreatureCreate().
m_closeDoorTimer
uint32 BattleGroundIC::m_closeDoorTimer private
Definition at line 756 of file BattleGroundIC.h.
Referenced by Reset(), StartingEventOpenDoors(), and Update().
m_gatesAllianceState
uint32 BattleGroundIC::m_gatesAllianceState[BG_IC_MAX_KEEP_GATES] private
Definition at line 753 of file BattleGroundIC.h.
Referenced by HandleEvent(), and Reset().
m_gatesHordeState
uint32 BattleGroundIC::m_gatesHordeState[BG_IC_MAX_KEEP_GATES] private
Definition at line 754 of file BattleGroundIC.h.
Referenced by HandleEvent(), and Reset().
m_hangarAnimGuids
std::set<uint32> BattleGroundIC::m_hangarAnimGuids[PVP_TEAM_COUNT] private
Definition at line 761 of file BattleGroundIC.h.
Referenced by DoApplyObjectiveBenefits(), DoResetObjective(), and HandleGameObjectCreate().
m_hangarPortalsGuids
std::set<uint32> BattleGroundIC::m_hangarPortalsGuids[PVP_TEAM_COUNT] private
Definition at line 760 of file BattleGroundIC.h.
Referenced by DoApplyObjectiveBenefits(), DoResetObjective(), and HandleGameObjectCreate().
m_hordeInnerGateGuid
ObjectGuid BattleGroundIC::m_hordeInnerGateGuid private
Definition at line 749 of file BattleGroundIC.h.
Referenced by HandleEvent(), and HandleGameObjectCreate().
m_isKeepInvaded
bool BattleGroundIC::m_isKeepInvaded[PVP_TEAM_COUNT] private
Definition at line 758 of file BattleGroundIC.h.
Referenced by HandleEvent(), and Reset().
m_isleNode
IsleNode BattleGroundIC::m_isleNode[BG_IC_MAX_OBJECTIVES] private
Definition at line 745 of file BattleGroundIC.h.
Referenced by AddPlayer(), CheckAchievementCriteriaMeet(), DoApplyObjectiveBenefits(), DoCaptureObjective(), DoChangeBannerState(), DoResetObjective(), HandleCreatureCreate(), HandleKillUnit(), HandlePlayerClickedOnFlag(), Reset(), and Update().
m_keepGatesGuid
ObjectGuid BattleGroundIC::m_keepGatesGuid[PVP_TEAM_COUNT][BG_IC_MAX_KEEP_GATES] private
Definition at line 747 of file BattleGroundIC.h.
Referenced by HandleEvent(), HandleGameObjectCreate(), StartingEventOpenDoors(), and Update().
m_resourceTickTimer
uint32 BattleGroundIC::m_resourceTickTimer[BG_IC_MAX_RESOURCE_NODES] private
Definition at line 755 of file BattleGroundIC.h.
Referenced by DoApplyObjectiveBenefits(), DoResetObjective(), Reset(), and Update().
m_seaforiumBombsGuids
std::set<uint32> BattleGroundIC::m_seaforiumBombsGuids[PVP_TEAM_COUNT] private
Definition at line 762 of file BattleGroundIC.h.
Referenced by DoApplyObjectiveBenefits(), DoResetObjective(), and HandleGameObjectCreate().
m_teleporterAnimGuids
GuidList BattleGroundIC::m_teleporterAnimGuids private
Definition at line 765 of file BattleGroundIC.h.
Referenced by HandleGameObjectCreate(), and StartingEventOpenDoors().
m_teleporterGuids
GuidList BattleGroundIC::m_teleporterGuids private
Definition at line 764 of file BattleGroundIC.h.
Referenced by HandleGameObjectCreate(), and StartingEventOpenDoors().
m_towerGatesGuids
GuidList BattleGroundIC::m_towerGatesGuids private
Definition at line 763 of file BattleGroundIC.h.
Referenced by HandleGameObjectCreate(), and StartingEventOpenDoors().
m_workshopMechanicGuids
ObjectGuid BattleGroundIC::m_workshopMechanicGuids[PVP_TEAM_COUNT] private
Definition at line 748 of file BattleGroundIC.h.
Referenced by HandleCreatureCreate(), and HandleKillUnit().
The documentation for this class was generated from the following files:
BattleGroundIC.h
BattleGroundIC.cpp