CMaNGOS_WoTLK: BattleGroundMgr Class Reference
BattleGroundMgr Class Reference
#include <BattleGroundMgr.h>
Public Member Functions
BattleGroundMgr ()
~BattleGroundMgr ()
void Update (uint32)
Update method.
void BuildPlayerJoinedBattleGroundPacket (WorldPacket &, Player *) const
Send player join from battleground packet.
void BuildPlayerLeftBattleGroundPacket (WorldPacket &, ObjectGuid) const
Send player leave from battleground packet.
void BuildBattleGroundListPacket (WorldPacket &, ObjectGuid, Player *, BattleGroundTypeId, uint8) const
Method that builds battleground list data.
void BuildGroupJoinedBattlegroundPacket (WorldPacket &, GroupJoinBattlegroundResult) const
Send battleground joined packet.
void BuildUpdateWorldStatePacket (WorldPacket &, uint32, uint32) const
Send battleground world state packet.
void BuildPvpLogDataPacket (WorldPacket &, BattleGround *) const
Send battleground log update.
void BuildBattleGroundStatusPacket (WorldPacket &, BattleGround *, uint8, uint8, uint32, uint32, ArenaType, Team) const
Send battleground status update.
void BuildPlaySoundPacket (WorldPacket &, uint32) const
Send battleground sound packet.
BattleGround * GetBattleGroundThroughClientInstance (uint32, BattleGroundTypeId)
Function that returns battleground from client instance id and battleground type.
BattleGround * GetBattleGround (uint32, BattleGroundTypeId)
Function that returns battleground from instance id and battleground type.
BattleGround * GetBattleGroundTemplate (BattleGroundTypeId)
Function that returns battleground from template id.
BattleGround * CreateNewBattleGround (BattleGroundTypeId, PvPDifficultyEntry const *, ArenaType, bool)
Function that creates a new battleground that is actually used.
uint32 CreateBattleGround (BattleGroundTypeId, bool, uint32, uint32, uint32, uint32, char const *, uint32, float, float, float, float, float, float, float, float, float, uint32)
Function that creates battleground templates.
void AddBattleGround (uint32 instanceId, BattleGroundTypeId bgTypeId, BattleGround *bg)
void RemoveBattleGround (uint32 instanceId, BattleGroundTypeId bgTypeId)
uint32 CreateClientVisibleInstanceId (BattleGroundTypeId, BattleGroundBracketId)
Function that returns client instance id from battleground type id and bracket id.
void DeleteClientVisibleInstanceId (BattleGroundTypeId bgTypeId, BattleGroundBracketId bracketId, uint32 clientInstanceId)
void CreateInitialBattleGrounds ()
Method that loads battleground data from DB.
void DeleteAllBattleGrounds ()
Method that deletes all battlegrounds.
void SendToBattleGround (Player *, uint32, BattleGroundTypeId)
Method that sends player to battleground.
void ScheduleQueueUpdate (uint32, ArenaType, BattleGroundQueueTypeId, BattleGroundTypeId, BattleGroundBracketId)
Method that schedules queue update.
uint32 GetMaxRatingDifference () const
Function that returns max arena rating difference.
uint32 GetRatingDiscardTimer () const
Function that returns the arena rating discard timer.
uint32 GetPrematureFinishTime () const
Function that returns the premature finish time.
void InitAutomaticArenaPointDistribution ()
Method that initiates the automatic arena points distribution.
void DistributeArenaPoints () const
Method that distributes the arena points distribution.
void RewardArenaSeason (uint32)
Method that computes arena season rewards.
void ResetAllArenaData ()
Method that resets all arena data.
void ToggleArenaTesting ()
Method that toggles arena test mode on / off.
void ToggleTesting ()
Method that toggles battleground test mode on / off.
void LoadBattleMastersEntry ()
Method that loads battlemaster entries from DB.
BattleGroundTypeId GetBattleMasterBG (uint32 entry) const
void LoadBattleEventIndexes ()
Method that loads battleground events used in battleground scripts.
const BattleGroundEventIdx GetCreatureEventIndex (uint32 dbGuid) const
const BattleGroundEventIdx GetGameObjectEventIndex (uint32 dbGuid) const
bool IsArenaTesting () const
bool IsTesting () const
std::set< uint32 > const & GetUsedRefLootIds () const
Static Public Member Functions
static bool IsArenaType (BattleGroundTypeId)
Function that returns the arena type.
static bool IsBattleGroundType (BattleGroundTypeId bgTypeId)
static BattleGroundQueueTypeId BgQueueTypeId (BattleGroundTypeId, ArenaType)
Function that returns the queue type for battleground type id.
static BattleGroundTypeId BgTemplateId (BattleGroundQueueTypeId)
Function that returns the battleground type id from battleground queue id.
static ArenaType BgArenaType (BattleGroundQueueTypeId)
Function that returns the arena type from battleground queue id.
static HolidayIds BgTypeToWeekendHolidayId (BattleGroundTypeId)
Function that returns the holiday id from battleground type id.
static BattleGroundTypeId WeekendHolidayIdToBgType (HolidayIds)
Function that returns the battleground type id from holiday id.
static bool IsBgWeekend (BattleGroundTypeId)
Function that checks if it's an active battleground holiday weekend.
Data Fields
BattleGroundQueue m_battleGroundQueues [MAX_BATTLEGROUND_QUEUE_TYPES]
BgFreeSlotQueueType BgFreeSlotQueue [MAX_BATTLEGROUND_TYPE_ID]
Private Types
typedef std::set< uint32 > ClientBattleGroundIdSet
Private Attributes
std::mutex schedulerLock
BattleMastersMap m_battleMastersMap
CreatureBattleEventIndexesMap m_creatureBattleEventIndexMap
GameObjectBattleEventIndexesMap m_gameObjectBattleEventIndexMap
BattleGroundSet m_battleGrounds [MAX_BATTLEGROUND_TYPE_ID]
std::vector< uint64 > m_queueUpdateScheduler
ClientBattleGroundIdSet m_clientBattleGroundIds [MAX_BATTLEGROUND_TYPE_ID][MAX_BATTLEGROUND_BRACKETS]
uint32 m_nextRatingDiscardUpdate
time_t m_nextAutoDistributionTime
uint32 m_autoDistributionTimeChecker
bool m_arenaTesting
bool m_testing
std::set< uint32 > m_usedRefloot
Detailed Description
Definition at line 191 of file BattleGroundMgr.h.
Member Typedef Documentation
ClientBattleGroundIdSet
typedef std::set<uint32> BattleGroundMgr::ClientBattleGroundIdSet private
Definition at line 302 of file BattleGroundMgr.h.
Constructor & Destructor Documentation
BattleGroundMgr()
BattleGroundMgr::BattleGroundMgr ()
Definition at line 1268 of file BattleGroundMgr.cpp.
References BATTLEGROUND_TYPE_NONE, CONFIG_UINT32_ARENA_RATING_DISCARD_TIMER, m_battleGrounds, m_nextRatingDiscardUpdate, m_testing, MAX_BATTLEGROUND_TYPE_ID, and sWorld.
~BattleGroundMgr()
BattleGroundMgr::~BattleGroundMgr ()
Definition at line 1276 of file BattleGroundMgr.cpp.
References DeleteAllBattleGrounds().
Member Function Documentation
AddBattleGround()
void BattleGroundMgr::AddBattleGround (uint32 instanceId, BattleGroundTypeId bgTypeId, BattleGround * bg) inline
Definition at line 218 of file BattleGroundMgr.h.
References m_battleGrounds.
Referenced by CreateBattleGround().
BgArenaType()
ArenaType BattleGroundMgr::BgArenaType (BattleGroundQueueTypeId bgQueueTypeId) static
Function that returns the arena type from battleground queue id.
Parameters
battleground queue id
Definition at line 2563 of file BattleGroundMgr.cpp.
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, ARENA_TYPE_5v5, ARENA_TYPE_NONE, BATTLEGROUND_QUEUE_2v2, BATTLEGROUND_QUEUE_3v3, and BATTLEGROUND_QUEUE_5v5.
Referenced by WorldSession::HandleBattlefieldStatusOpcode(), and Update().
BgQueueTypeId()
BattleGroundQueueTypeId BattleGroundMgr::BgQueueTypeId (BattleGroundTypeId bgTypeId, ArenaType arenaType) static
Function that returns the queue type for battleground type id.
Parameters
battleground type id
arena type
Definition at line 2486 of file BattleGroundMgr.cpp.
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, ARENA_TYPE_5v5, BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_QUEUE_2v2, BATTLEGROUND_QUEUE_3v3, BATTLEGROUND_QUEUE_5v5, BATTLEGROUND_QUEUE_AB, BATTLEGROUND_QUEUE_AV, BATTLEGROUND_QUEUE_EY, BATTLEGROUND_QUEUE_IC, BATTLEGROUND_QUEUE_NONE, BATTLEGROUND_QUEUE_RB, BATTLEGROUND_QUEUE_SA, BATTLEGROUND_QUEUE_WS, BATTLEGROUND_RB, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, and BATTLEGROUND_WS.
Referenced by Group::CanJoinBattleGroundQueue(), BattleGround::EndBattleGround(), BgQueueInviteEvent::Execute(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), BattleGroundQueue::InviteGroupToBg(), Player::LoadFromDB(), BattleGround::PlayerAddedToBgCheckIfBgIsRunning(), BattleGroundQueue::RemovePlayer(), and BattleGround::RemovePlayerAtLeave().
BgTemplateId()
BattleGroundTypeId BattleGroundMgr::BgTemplateId (BattleGroundQueueTypeId bgQueueTypeId) static
Function that returns the battleground type id from battleground queue id.
Parameters
battleground queue id
Definition at line 2531 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_QUEUE_2v2, BATTLEGROUND_QUEUE_3v3, BATTLEGROUND_QUEUE_5v5, BATTLEGROUND_QUEUE_AB, BATTLEGROUND_QUEUE_AV, BATTLEGROUND_QUEUE_EY, BATTLEGROUND_QUEUE_IC, BATTLEGROUND_QUEUE_RB, BATTLEGROUND_QUEUE_SA, BATTLEGROUND_QUEUE_WS, BATTLEGROUND_RB, BATTLEGROUND_SA, and BATTLEGROUND_WS.
Referenced by WorldSession::HandleBattlefieldStatusOpcode().
BgTypeToWeekendHolidayId()
HolidayIds BattleGroundMgr::BgTypeToWeekendHolidayId (BattleGroundTypeId bgTypeId) static
Function that returns the holiday id from battleground type id.
Parameters
battleground type id
Definition at line 2709 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_SA, BATTLEGROUND_WS, HOLIDAY_CALL_TO_ARMS_AB, HOLIDAY_CALL_TO_ARMS_AV, HOLIDAY_CALL_TO_ARMS_EY, HOLIDAY_CALL_TO_ARMS_SA, HOLIDAY_CALL_TO_ARMS_WS, and HOLIDAY_NONE.
Referenced by IsBgWeekend().
BuildBattleGroundListPacket()
void BattleGroundMgr::BuildBattleGroundListPacket (WorldPacket & data, ObjectGuid guid, Player * player, BattleGroundTypeId bgTypeId, uint8 fromWhere) const
Method that builds battleground list data.
Parameters
packet
battlemaster guid
player
battleground type id
joining source
Definition at line 2367 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_RB, BG_REWARD_LOOSER_HONOR_FIRST, BG_REWARD_LOOSER_HONOR_LAST, BG_REWARD_WINNER_ARENA_FIRST, BG_REWARD_WINNER_ARENA_LAST, BG_REWARD_WINNER_HONOR_FIRST, BG_REWARD_WINNER_HONOR_LAST, GetBattlegroundBracketByLevel(), Unit::GetLevel(), Player::HasWonRandomBattleground(), MaNGOS::Honor::hk_honor_at_level(), WorldPacket::Initialize(), m_clientBattleGroundIds, ByteBuffer::put(), sBattleGroundMgr, SMSG_BATTLEFIELD_LIST, and ByteBuffer::wpos().
BuildBattleGroundStatusPacket()
void BattleGroundMgr::BuildBattleGroundStatusPacket (WorldPacket & data, BattleGround * bg, uint8 queueSlot, uint8 statusId, uint32 time1, uint32 time2, ArenaType arenaType, Team arenaTeam) const
Send battleground status update.
Parameters
packet
battleground
queue slot
status id
time1
time2
arena type
arena team
Definition at line 1379 of file BattleGroundMgr.cpp.
References ALLIANCE, BattleGround::GetClientInstanceId(), BattleGround::GetMapId(), BattleGround::GetMaxLevel(), BattleGround::GetMinLevel(), BattleGround::GetTypeId(), WorldPacket::Initialize(), BattleGround::IsRated(), sLog, SMSG_BATTLEFIELD_STATUS, STATUS_IN_PROGRESS, STATUS_WAIT_JOIN, and STATUS_WAIT_QUEUE.
BuildGroupJoinedBattlegroundPacket()
void BattleGroundMgr::BuildGroupJoinedBattlegroundPacket (WorldPacket & data, GroupJoinBattlegroundResult result) const
Send battleground joined packet.
Parameters
packet
result
Definition at line 1557 of file BattleGroundMgr.cpp.
References ERR_BATTLEGROUND_JOIN_FAILED, ERR_BATTLEGROUND_JOIN_TIMED_OUT, WorldPacket::Initialize(), and SMSG_GROUP_JOINED_BATTLEGROUND.
BuildPlayerJoinedBattleGroundPacket()
void BattleGroundMgr::BuildPlayerJoinedBattleGroundPacket (WorldPacket & data, Player * player) const
Send player join from battleground packet.
Parameters
packet
player
Definition at line 1609 of file BattleGroundMgr.cpp.
References Object::GetObjectGuid(), WorldPacket::Initialize(), and SMSG_BATTLEGROUND_PLAYER_JOINED.
BuildPlayerLeftBattleGroundPacket()
void BattleGroundMgr::BuildPlayerLeftBattleGroundPacket (WorldPacket & data, ObjectGuid guid) const
Send player leave from battleground packet.
Parameters
packet
object guid
Definition at line 1597 of file BattleGroundMgr.cpp.
References WorldPacket::Initialize(), and SMSG_BATTLEGROUND_PLAYER_LEFT.
BuildPlaySoundPacket()
void BattleGroundMgr::BuildPlaySoundPacket (WorldPacket & data, uint32 soundId) const
Send battleground sound packet.
Parameters
packet
sound id
Definition at line 1585 of file BattleGroundMgr.cpp.
References WorldPacket::Initialize(), and SMSG_PLAY_SOUND.
BuildPvpLogDataPacket()
void BattleGroundMgr::BuildPvpLogDataPacket (WorldPacket & data, BattleGround * bg) const
Send battleground log update.
Parameters
packet
battleground
Definition at line 1433 of file BattleGroundMgr.cpp.
References ALLIANCE, BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_RB, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_WS, BattleGroundScore::bonusHonor, BattleGroundScore::damageDone, BattleGroundScore::deaths, DEBUG_LOG, ArenaTeam::GetName(), BattleGround::GetPlayerScoresBegin(), BattleGround::GetPlayerScoresEnd(), BattleGround::GetPlayerScoresSize(), BattleGround::GetPlayerTeam(), BattleGround::GetStatus(), BattleGround::GetTypeId(), BattleGround::GetWinner(), BattleGroundScore::healingDone, BattleGroundScore::honorableKills, HORDE, WorldPacket::Initialize(), BattleGround::IsArena(), BattleGroundScore::killingBlows, BattleGround::m_arenaTeamIds, BattleGround::m_arenaTeamRatingChanges, MSG_PVP_LOG_DATA, sObjectMgr, and STATUS_WAIT_LEAVE.
BuildUpdateWorldStatePacket()
void BattleGroundMgr::BuildUpdateWorldStatePacket (WorldPacket & data, uint32 field, uint32 value) const
Send battleground world state packet.
Parameters
packet
field
value
Definition at line 1572 of file BattleGroundMgr.cpp.
References WorldPacket::Initialize(), and SMSG_UPDATE_WORLD_STATE.
CreateBattleGround()
uint32 BattleGroundMgr::CreateBattleGround (BattleGroundTypeId bgTypeId, bool IsArena, uint32 minPlayersPerTeam, uint32 maxPlayersPerTeam, uint32 levelMin, uint32 levelMax, char const * battleGroundName, uint32 mapId, float team1StartLocX, float team1StartLocY, float team1StartLocZ, float team1StartLocO, float team2StartLocX, float team2StartLocY, float team2StartLocZ, float team2StartLocO, float startMaxDist, uint32 playerSkinReflootId)
Function that creates battleground templates.
Parameters
battleground type id
isArena
min players per team
max players per team
level min
level max
battleground name
map id
team 1 start location X
team 1 start location Y
team 1 start location Z
team 1 start location O
team 2 start location X
team 2 start location Y
team 2 start location Z
team 2 start location O
start max distance
Definition at line 1848 of file BattleGroundMgr.cpp.
References AddBattleGround(), ALLIANCE, BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_RB, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_WS, BattleGround::GetInstanceId(), BattleGround::GetTypeId(), HORDE, BattleGround::SetArenaorBGType(), BattleGround::SetLevelRange(), BattleGround::SetMapId(), BattleGround::SetMaxPlayers(), BattleGround::SetMaxPlayersPerTeam(), BattleGround::SetMinPlayers(), BattleGround::SetMinPlayersPerTeam(), BattleGround::SetName(), BattleGround::SetPlayerSkinRefLootId(), BattleGround::SetStartMaxDist(), BattleGround::SetTeamStartLoc(), and BattleGround::SetTypeId().
Referenced by CreateInitialBattleGrounds().
CreateClientVisibleInstanceId()
uint32 BattleGroundMgr::CreateClientVisibleInstanceId (BattleGroundTypeId bgTypeId, BattleGroundBracketId bracketId)
Function that returns client instance id from battleground type id and bracket id.
Parameters
battleground type id
bracket id
Definition at line 1683 of file BattleGroundMgr.cpp.
References IsArenaType(), and m_clientBattleGroundIds.
Referenced by CreateNewBattleGround().
CreateInitialBattleGrounds()
void BattleGroundMgr::CreateInitialBattleGrounds ()
Method that loads battleground data from DB.
Definition at line 1894 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_RB, CreateBattleGround(), QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), SQLStorage::LookupEntry(), m_usedRefloot, BattlemasterListEntry::mapid, BattlemasterListEntry::maxLevel, BattlemasterListEntry::minLevel, BattlemasterListEntry::name, QueryResult::NextRow(), WorldSafeLocsEntry::o, Database::Query(), sBattlemasterListStore, sLog, sLootMgr, BarGoLink::step(), sWorld, sWorldSafeLocsStore, BattlemasterListEntry::type, TYPE_ARENA, WorldDatabase, WorldSafeLocsEntry::x, WorldSafeLocsEntry::y, and WorldSafeLocsEntry::z.
CreateNewBattleGround()
BattleGround * BattleGroundMgr::CreateNewBattleGround (BattleGroundTypeId bgTypeId, PvPDifficultyEntry const * bracketEntry, ArenaType arenaType, bool isRated)
Function that creates a new battleground that is actually used.
Parameters
battleground type id
bracket entry
arena type
isRated
Definition at line 1716 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_EY, BATTLEGROUND_IC, BATTLEGROUND_NA, BATTLEGROUND_RB, BATTLEGROUND_RL, BATTLEGROUND_RV, BATTLEGROUND_SA, BATTLEGROUND_WS, countof, CreateClientVisibleInstanceId(), GetBattleGroundTemplate(), PvPDifficultyEntry::GetBracketId(), BattleGround::GetMapId(), BattleGround::IsArena(), BattleGround::Reset(), BattleGround::SetArenaType(), BattleGround::SetBracket(), BattleGround::SetClientInstanceId(), BattleGround::SetRandom(), BattleGround::SetRandomTypeId(), BattleGround::SetRated(), BattleGround::SetStatus(), BattleGround::SetTypeId(), sLog, sMapMgr, STATUS_WAIT_JOIN, and urand().
DeleteAllBattleGrounds()
void BattleGroundMgr::DeleteAllBattleGrounds ()
Method that deletes all battlegrounds.
Definition at line 1284 of file BattleGroundMgr.cpp.
References BATTLEGROUND_TYPE_NONE, m_battleGrounds, and MAX_BATTLEGROUND_TYPE_ID.
Referenced by ~BattleGroundMgr().
DeleteClientVisibleInstanceId()
void BattleGroundMgr::DeleteClientVisibleInstanceId (BattleGroundTypeId bgTypeId, BattleGroundBracketId bracketId, uint32 clientInstanceId) inline
Definition at line 222 of file BattleGroundMgr.h.
References m_clientBattleGroundIds.
DistributeArenaPoints()
void BattleGroundMgr::DistributeArenaPoints () const
Method that distributes the arena points distribution.
Definition at line 2080 of file BattleGroundMgr.cpp.
References CharacterDatabase, HIGHGUID_PLAYER, LANG_DIST_ARENA_POINTS_END, LANG_DIST_ARENA_POINTS_ONLINE_END, LANG_DIST_ARENA_POINTS_ONLINE_START, LANG_DIST_ARENA_POINTS_START, LANG_DIST_ARENA_POINTS_TEAM_END, LANG_DIST_ARENA_POINTS_TEAM_START, Database::PExecute(), SEC_GAMEMASTER, sObjectMgr, and sWorld.
Referenced by Update().
GetBattleGround()
BattleGround * BattleGroundMgr::GetBattleGround (uint32 instanceId, BattleGroundTypeId bgTypeId)
Function that returns battleground from instance id and battleground type.
Parameters
instance id
battleground type id
Definition at line 1647 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AV, BATTLEGROUND_TYPE_NONE, m_battleGrounds, and MAX_BATTLEGROUND_TYPE_ID.
Referenced by GetBattleGroundThroughClientInstance(), and SendToBattleGround().
GetBattleGroundTemplate()
BattleGround * BattleGroundMgr::GetBattleGroundTemplate (BattleGroundTypeId bgTypeId)
Function that returns battleground from template id.
Parameters
battleground type id
Definition at line 1671 of file BattleGroundMgr.cpp.
References m_battleGrounds.
Referenced by CreateNewBattleGround(), and GetBattleGroundThroughClientInstance().
GetBattleGroundThroughClientInstance()
BattleGround * BattleGroundMgr::GetBattleGroundThroughClientInstance (uint32 instanceId, BattleGroundTypeId bgTypeId)
Function that returns battleground from client instance id and battleground type.
Parameters
instance id
battleground type id
Definition at line 1621 of file BattleGroundMgr.cpp.
References GetBattleGround(), GetBattleGroundTemplate(), BattleGround::IsArena(), and m_battleGrounds.
GetBattleMasterBG()
BattleGroundTypeId BattleGroundMgr::GetBattleMasterBG (uint32 entry) const inline
Definition at line 251 of file BattleGroundMgr.h.
References BATTLEGROUND_TYPE_NONE, and m_battleMastersMap.
GetCreatureEventIndex()
const BattleGroundEventIdx BattleGroundMgr::GetCreatureEventIndex (uint32 dbGuid) const inline
Definition at line 261 of file BattleGroundMgr.h.
References m_creatureBattleEventIndexMap.
GetGameObjectEventIndex()
const BattleGroundEventIdx BattleGroundMgr::GetGameObjectEventIndex (uint32 dbGuid) const inline
Definition at line 270 of file BattleGroundMgr.h.
References m_gameObjectBattleEventIndexMap.
GetMaxRatingDifference()
uint32 BattleGroundMgr::GetMaxRatingDifference () const
Function that returns max arena rating difference.
Definition at line 2632 of file BattleGroundMgr.cpp.
References CONFIG_UINT32_ARENA_MAX_RATING_DIFFERENCE, and sWorld.
GetPrematureFinishTime()
uint32 BattleGroundMgr::GetPrematureFinishTime () const
Function that returns the premature finish time.
Definition at line 2652 of file BattleGroundMgr.cpp.
References CONFIG_UINT32_BATTLEGROUND_PREMATURE_FINISH_TIMER, and sWorld.
GetRatingDiscardTimer()
uint32 BattleGroundMgr::GetRatingDiscardTimer () const
Function that returns the arena rating discard timer.
Definition at line 2644 of file BattleGroundMgr.cpp.
References CONFIG_UINT32_ARENA_RATING_DISCARD_TIMER, and sWorld.
GetUsedRefLootIds()
std::set<uint32> const& BattleGroundMgr::GetUsedRefLootIds () const inline
Definition at line 292 of file BattleGroundMgr.h.
References m_usedRefloot.
InitAutomaticArenaPointDistribution()
void BattleGroundMgr::InitAutomaticArenaPointDistribution ()
Method that initiates the automatic arena points distribution.
Definition at line 2024 of file BattleGroundMgr.cpp.
References CharacterDatabase, CONFIG_BOOL_ARENA_AUTO_DISTRIBUTE_POINTS, CONFIG_UINT32_ARENA_FIRST_RESET_DAY, CONFIG_UINT32_QUEST_DAILY_RESET_HOUR, m_nextAutoDistributionTime, Database::PExecute(), Database::Query(), sWorld, and UI64FMTD.
IsArenaTesting()
bool BattleGroundMgr::IsArenaTesting () const inline
Definition at line 279 of file BattleGroundMgr.h.
References m_arenaTesting.
IsArenaType()
bool BattleGroundMgr::IsArenaType (BattleGroundTypeId bgTypeId) static
Function that returns the arena type.
Parameters
battleground type id
Definition at line 2464 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_BE, BATTLEGROUND_DS, BATTLEGROUND_NA, BATTLEGROUND_RL, and BATTLEGROUND_RV.
Referenced by CreateClientVisibleInstanceId(), and IsBattleGroundType().
IsBattleGroundType()
static bool BattleGroundMgr::IsBattleGroundType (BattleGroundTypeId bgTypeId) inline static
Definition at line 283 of file BattleGroundMgr.h.
References IsArenaType().
IsBgWeekend()
bool BattleGroundMgr::IsBgWeekend (BattleGroundTypeId bgTypeId) static
Function that checks if it's an active battleground holiday weekend.
Parameters
battleground type id
Definition at line 2745 of file BattleGroundMgr.cpp.
References BgTypeToWeekendHolidayId(), and sGameEventMgr.
Referenced by Player::FillBGWeekendWorldStates(), BattleGroundAB::Reset(), BattleGroundAV::Reset(), BattleGroundEY::Reset(), and BattleGroundWS::Reset().
IsTesting()
bool BattleGroundMgr::IsTesting () const inline
Definition at line 280 of file BattleGroundMgr.h.
References m_testing.
LoadBattleEventIndexes()
void BattleGroundMgr::LoadBattleEventIndexes ()
Method that loads battleground events used in battleground scripts.
Definition at line 2753 of file BattleGroundMgr.cpp.
References BG_EVENT_NONE, BattleGroundEventIdx::event1, BattleGroundEventIdx::event2, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetString(), Field::GetUInt32(), Field::GetUInt8(), m_creatureBattleEventIndexMap, m_gameObjectBattleEventIndexMap, QueryResult::NextRow(), Database::Query(), sLog, BarGoLink::step(), and WorldDatabase.
LoadBattleMastersEntry()
void BattleGroundMgr::LoadBattleMastersEntry ()
Method that loads battlemaster entries from DB.
Definition at line 2660 of file BattleGroundMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), m_battleMastersMap, QueryResult::NextRow(), Database::Query(), sBattlemasterListStore, sLog, BarGoLink::step(), and WorldDatabase.
RemoveBattleGround()
void BattleGroundMgr::RemoveBattleGround (uint32 instanceId, BattleGroundTypeId bgTypeId) inline
Definition at line 219 of file BattleGroundMgr.h.
References m_battleGrounds.
ResetAllArenaData()
void BattleGroundMgr::ResetAllArenaData ()
Method that resets all arena data.
Definition at line 2345 of file BattleGroundMgr.cpp.
References sObjectMgr.
Referenced by RewardArenaSeason().
RewardArenaSeason()
void BattleGroundMgr::RewardArenaSeason (uint32 seasonId)
Method that computes arena season rewards.
Parameters
season id
Definition at line 2181 of file BattleGroundMgr.cpp.
References MailDraft::AddItem(), ARENA_TYPE_2v2, ARENA_TYPE_3v3, ARENA_TYPE_5v5, CharacterDatabase, CheckPlayersAndAddToWinners(), Item::CreateItem(), QueryResult::Fetch(), Player::GetArenaPoints(), Field::GetCppString(), ArenaTeam::GetStats(), LANG_DIST_ARENA_REWARDS_END, LANG_DIST_ARENA_REWARDS_START, Player::ModifyHonorPoints(), Database::PExecute(), Database::PQuery(), ArenaTeamStats::rating, ResetAllArenaData(), Player::SaveTitles(), Item::SaveToDB(), sCharTitlesStore, SEC_GAMEMASTER, MailDraft::SendMailTo(), Player::SetArenaPoints(), MailDraft::SetSubjectAndBody(), Player::SetTitle(), SetTitleValues(), sObjectAccessor, sObjectMgr, StrSplit(), and sWorld.
ScheduleQueueUpdate()
void BattleGroundMgr::ScheduleQueueUpdate (uint32 arenaRating, ArenaType arenaType, BattleGroundQueueTypeId bgQueueTypeId, BattleGroundTypeId bgTypeId, BattleGroundBracketId bracketId)
Method that schedules queue update.
Parameters
arena rating
arena type
battleground queue type id
battleground type id
bracket id
Definition at line 2611 of file BattleGroundMgr.cpp.
References m_queueUpdateScheduler.
SendToBattleGround()
void BattleGroundMgr::SendToBattleGround (Player * player, uint32 instanceId, BattleGroundTypeId bgTypeId)
Method that sends player to battleground.
Parameters
player
instance id
battleground type id
Definition at line 2438 of file BattleGroundMgr.cpp.
References DETAIL_LOG, GetBattleGround(), Player::GetBGTeam(), Object::GetGUIDLow(), BattleGround::GetMapId(), WorldObject::GetName(), Player::GetTeam(), BattleGround::GetTeamStartLoc(), sLog, and Player::TeleportTo().
ToggleArenaTesting()
void BattleGroundMgr::ToggleArenaTesting ()
Method that toggles arena test mode on / off.
Definition at line 2593 of file BattleGroundMgr.cpp.
References LANG_DEBUG_ARENA_OFF, LANG_DEBUG_ARENA_ON, m_arenaTesting, and sWorld.
ToggleTesting()
void BattleGroundMgr::ToggleTesting ()
Method that toggles battleground test mode on / off.
Definition at line 2581 of file BattleGroundMgr.cpp.
References LANG_DEBUG_BG_OFF, LANG_DEBUG_BG_ON, m_testing, and sWorld.
Update()
void BattleGroundMgr::Update (uint32 diff)
Update method.
Parameters
diff
Definition at line 1303 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AA, BATTLEGROUND_ARENA_POINT_DISTRIBUTION_DAY, BATTLEGROUND_QUEUE_2v2, BATTLEGROUND_QUEUE_5v5, BG_BRACKET_ID_FIRST, BgArenaType(), CharacterDatabase, CONFIG_BOOL_ARENA_AUTO_DISTRIBUTE_POINTS, CONFIG_UINT32_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS, CONFIG_UINT32_ARENA_MAX_RATING_DIFFERENCE, CONFIG_UINT32_ARENA_RATING_DISCARD_TIMER, DEBUG_LOG, DistributeArenaPoints(), m_autoDistributionTimeChecker, m_battleGroundQueues, m_nextAutoDistributionTime, m_nextRatingDiscardUpdate, m_queueUpdateScheduler, MAX_BATTLEGROUND_BRACKETS, Database::PExecute(), sWorld, UI64FMTD, and BattleGroundQueue::Update().
WeekendHolidayIdToBgType()
BattleGroundTypeId BattleGroundMgr::WeekendHolidayIdToBgType (HolidayIds holiday) static
Function that returns the battleground type id from holiday id.
Parameters
holiday id
Definition at line 2727 of file BattleGroundMgr.cpp.
References BATTLEGROUND_AB, BATTLEGROUND_AV, BATTLEGROUND_EY, BATTLEGROUND_SA, BATTLEGROUND_TYPE_NONE, BATTLEGROUND_WS, HOLIDAY_CALL_TO_ARMS_AB, HOLIDAY_CALL_TO_ARMS_AV, HOLIDAY_CALL_TO_ARMS_EY, HOLIDAY_CALL_TO_ARMS_SA, and HOLIDAY_CALL_TO_ARMS_WS.
Referenced by GameEventMgr::UpdateWorldStates().
Field Documentation
BgFreeSlotQueue
BgFreeSlotQueueType BattleGroundMgr::BgFreeSlotQueue[MAX_BATTLEGROUND_TYPE_ID]
Definition at line 236 of file BattleGroundMgr.h.
m_arenaTesting
bool BattleGroundMgr::m_arenaTesting private
Definition at line 307 of file BattleGroundMgr.h.
Referenced by IsArenaTesting(), and ToggleArenaTesting().
m_autoDistributionTimeChecker
uint32 BattleGroundMgr::m_autoDistributionTimeChecker private
Definition at line 306 of file BattleGroundMgr.h.
Referenced by Update().
m_battleGroundQueues
BattleGroundQueue BattleGroundMgr::m_battleGroundQueues[MAX_BATTLEGROUND_QUEUE_TYPES]
Definition at line 234 of file BattleGroundMgr.h.
Referenced by Update().
m_battleGrounds
BattleGroundSet BattleGroundMgr::m_battleGrounds[MAX_BATTLEGROUND_TYPE_ID] private
Definition at line 300 of file BattleGroundMgr.h.
Referenced by AddBattleGround(), BattleGroundMgr(), DeleteAllBattleGrounds(), GetBattleGround(), GetBattleGroundTemplate(), GetBattleGroundThroughClientInstance(), and RemoveBattleGround().
m_battleMastersMap
BattleMastersMap BattleGroundMgr::m_battleMastersMap private
Definition at line 295 of file BattleGroundMgr.h.
Referenced by GetBattleMasterBG(), and LoadBattleMastersEntry().
m_clientBattleGroundIds
ClientBattleGroundIdSet BattleGroundMgr::m_clientBattleGroundIds[MAX_BATTLEGROUND_TYPE_ID][MAX_BATTLEGROUND_BRACKETS] private
Definition at line 303 of file BattleGroundMgr.h.
Referenced by BuildBattleGroundListPacket(), CreateClientVisibleInstanceId(), and DeleteClientVisibleInstanceId().
m_creatureBattleEventIndexMap
CreatureBattleEventIndexesMap BattleGroundMgr::m_creatureBattleEventIndexMap private
Definition at line 296 of file BattleGroundMgr.h.
Referenced by GetCreatureEventIndex(), and LoadBattleEventIndexes().
m_gameObjectBattleEventIndexMap
GameObjectBattleEventIndexesMap BattleGroundMgr::m_gameObjectBattleEventIndexMap private
Definition at line 297 of file BattleGroundMgr.h.
Referenced by GetGameObjectEventIndex(), and LoadBattleEventIndexes().
m_nextAutoDistributionTime
time_t BattleGroundMgr::m_nextAutoDistributionTime private
Definition at line 305 of file BattleGroundMgr.h.
Referenced by InitAutomaticArenaPointDistribution(), and Update().
m_nextRatingDiscardUpdate
uint32 BattleGroundMgr::m_nextRatingDiscardUpdate private
Definition at line 304 of file BattleGroundMgr.h.
Referenced by BattleGroundMgr(), and Update().
m_queueUpdateScheduler
std::vector<uint64> BattleGroundMgr::m_queueUpdateScheduler private
Definition at line 301 of file BattleGroundMgr.h.
Referenced by ScheduleQueueUpdate(), and Update().
m_testing
bool BattleGroundMgr::m_testing private
Definition at line 308 of file BattleGroundMgr.h.
Referenced by BattleGroundMgr(), IsTesting(), and ToggleTesting().
m_usedRefloot
std::set<uint32> BattleGroundMgr::m_usedRefloot private
Definition at line 309 of file BattleGroundMgr.h.
Referenced by CreateInitialBattleGrounds(), and GetUsedRefLootIds().
schedulerLock
std::mutex BattleGroundMgr::schedulerLock private
Definition at line 294 of file BattleGroundMgr.h.
The documentation for this class was generated from the following files:
BattleGroundMgr.h
BattleGroundMgr.cpp