CMaNGOS_WoTLK: instance_gnomeregan Class Reference
instance_gnomeregan Class Reference
#include <gnomeregan.h>
Public Member Functions
instance_gnomeregan (Map *pMap)
~instance_gnomeregan ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
sBombFace * GetBombFaces ()
void DoActivateBombFace (uint8 uiIndex)
void DoDeactivateBombFace (uint8 uiIndex)
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
sBombFace m_asBombFaces [MAX_GNOME_FACES]
ObjectGuid m_aExplosiveSortedGuids [2][MAX_EXPLOSIVES_PER_SIDE]
GuidList m_luiExplosiveChargeGUIDs
GuidList m_luiSpawnedExplosiveChargeGUIDs
GuidList m_lRedRocketGUIDs
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Detailed Description
Definition at line 54 of file gnomeregan.h.
Constructor & Destructor Documentation
instance_gnomeregan()
instance_gnomeregan::instance_gnomeregan (Map * pMap)
Definition at line 27 of file instance_gnomeregan.cpp.
References Initialize().
~instance_gnomeregan()
instance_gnomeregan::~instance_gnomeregan () inline
Definition at line 58 of file gnomeregan.h.
Member Function Documentation
DoActivateBombFace()
void instance_gnomeregan::DoActivateBombFace (uint8 uiIndex)
Definition at line 248 of file instance_gnomeregan.cpp.
References ScriptedInstance::DoUseDoorOrButton(), m_asBombFaces, sBombFace::m_bActivated, sBombFace::m_uiBombTimer, and MAX_GNOME_FACES.
Referenced by SetData().
DoDeactivateBombFace()
void instance_gnomeregan::DoDeactivateBombFace (uint8 uiIndex)
Definition at line 261 of file instance_gnomeregan.cpp.
References ScriptedInstance::DoUseDoorOrButton(), m_asBombFaces, sBombFace::m_bActivated, sBombFace::m_uiBombTimer, and MAX_GNOME_FACES.
Referenced by GOUse_go_gnomeface_button(), and SetData().
GetBombFaces()
sBombFace * instance_gnomeregan::GetBombFaces ()
Definition at line 243 of file instance_gnomeregan.cpp.
References m_asBombFaces.
Referenced by boss_thermapluggAI::Aggro().
GetData()
uint32 instance_gnomeregan::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 232 of file instance_gnomeregan.cpp.
References m_auiEncounter, TYPE_GRUBBIS, and TYPE_THERMAPLUGG.
Referenced by npc_blastmaster_emi_shortfuseAI::npc_blastmaster_emi_shortfuseAI().
Initialize()
void instance_gnomeregan::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 32 of file instance_gnomeregan.cpp.
References m_asBombFaces, and m_auiEncounter.
Referenced by instance_gnomeregan().
Load()
void instance_gnomeregan::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 210 of file instance_gnomeregan.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_gnomeregan::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 43 of file instance_gnomeregan.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, and NPC_BLASTMASTER_SHORTFUSE.
OnObjectCreate()
void instance_gnomeregan::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 49 of file instance_gnomeregan.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_CAVE_IN_NORTH, GO_CAVE_IN_SOUTH, GO_EXPLOSIVE_CHARGE, GO_GNOME_FACE_1, GO_GNOME_FACE_2, GO_GNOME_FACE_3, GO_GNOME_FACE_4, GO_GNOME_FACE_5, GO_GNOME_FACE_6, GO_RED_ROCKET, GO_THE_FINAL_CHAMBER, m_asBombFaces, sBombFace::m_gnomeFaceGuid, ScriptedInstance::m_goEntryGuidStore, m_lRedRocketGUIDs, and m_luiExplosiveChargeGUIDs.
Save()
const char* instance_gnomeregan::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 72 of file gnomeregan.h.
References m_strInstData.
SetData()
void instance_gnomeregan::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 76 of file instance_gnomeregan.cpp.
References DATA_EXPLOSIVE_CHARGE_1, DATA_EXPLOSIVE_CHARGE_2, DATA_EXPLOSIVE_CHARGE_3, DATA_EXPLOSIVE_CHARGE_4, DATA_EXPLOSIVE_CHARGE_USE, DoActivateBombFace(), DoDeactivateBombFace(), DONE, ScriptedInstance::DoRespawnGameObject(), FAIL, GAMEOBJECT_FLAGS, Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ACTIVATED, GO_CAVE_IN_NORTH, GO_CAVE_IN_SOUTH, GO_FLAG_LOCKED, GO_READY, GO_THE_FINAL_CHAMBER, HOUR, IN_PROGRESS, InstanceData::instance, m_aExplosiveSortedGuids, m_auiEncounter, m_lRedRocketGUIDs, m_luiExplosiveChargeGUIDs, m_luiSpawnedExplosiveChargeGUIDs, m_strInstData, MAX_EXPLOSIVES_PER_SIDE, MAX_GNOME_FACES, NPC_BLASTMASTER_SHORTFUSE, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), sortFromEastToWest(), TYPE_EXPLOSIVE_CHARGE, TYPE_GRUBBIS, and TYPE_THERMAPLUGG.
Referenced by boss_thermapluggAI::Aggro(), boss_thermapluggAI::JustDied(), npc_blastmaster_emi_shortfuseAI::JustDied(), boss_thermapluggAI::JustReachedHome(), npc_blastmaster_emi_shortfuseAI::StartEvent(), npc_blastmaster_emi_shortfuseAI::SummonedCreatureJustDied(), and npc_blastmaster_emi_shortfuseAI::UpdateEscortAI().
Field Documentation
m_aExplosiveSortedGuids
ObjectGuid instance_gnomeregan::m_aExplosiveSortedGuids[2][MAX_EXPLOSIVES_PER_SIDE] protected
Definition at line 80 of file gnomeregan.h.
Referenced by SetData().
m_asBombFaces
sBombFace instance_gnomeregan::m_asBombFaces[MAX_GNOME_FACES] protected
Definition at line 79 of file gnomeregan.h.
Referenced by DoActivateBombFace(), DoDeactivateBombFace(), GetBombFaces(), Initialize(), and OnObjectCreate().
m_auiEncounter
uint32 instance_gnomeregan::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 76 of file gnomeregan.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_lRedRocketGUIDs
GuidList instance_gnomeregan::m_lRedRocketGUIDs protected
Definition at line 84 of file gnomeregan.h.
Referenced by OnObjectCreate(), and SetData().
m_luiExplosiveChargeGUIDs
GuidList instance_gnomeregan::m_luiExplosiveChargeGUIDs protected
Definition at line 82 of file gnomeregan.h.
Referenced by OnObjectCreate(), and SetData().
m_luiSpawnedExplosiveChargeGUIDs
GuidList instance_gnomeregan::m_luiSpawnedExplosiveChargeGUIDs protected
Definition at line 83 of file gnomeregan.h.
Referenced by SetData().
m_strInstData
std::string instance_gnomeregan::m_strInstData protected
Definition at line 77 of file gnomeregan.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
gnomeregan.h
instance_gnomeregan.cpp