CMaNGOS_WoTLK: CalendarMgr Class Reference
CalendarMgr Class Reference
#include <Calendar.h>
Public Member Functions
CalendarMgr ()
~CalendarMgr ()
void GetPlayerEventsList (ObjectGuid const &guid, CalendarEventsList &calEventList)
void GetPlayerInvitesList (ObjectGuid const &guid, CalendarInvitesList &calInvList)
CalendarEvent * AddEvent (ObjectGuid const &guid, std::string title, std::string description, uint32 type, uint32 repeatable, uint32 maxInvites, int32 dungeonId, time_t eventTime, time_t unkTime, uint32 flags)
CalendarInvite * AddInvite (CalendarEvent *event, ObjectGuid const &senderGuid, ObjectGuid const &inviteeGuid, CalendarInviteStatus status, CalendarModerationRank rank, const std::string &text, time_t statusTime)
void RemoveEvent (uint64 eventId, Player *remover)
bool RemoveInvite (uint64 eventId, uint64 inviteId, ObjectGuid const &removerGuid)
void RemovePlayerCalendar (ObjectGuid const &playerGuid)
void RemoveGuildCalendar (ObjectGuid const &playerGuid, uint32 GuildId)
void CopyEvent (uint64 eventId, time_t newTime, ObjectGuid const &guid)
uint32 GetPlayerNumPending (ObjectGuid const &guid)
CalendarEvent * GetEventById (uint64 eventId)
void LoadCalendarsFromDB ()
void SendCalendarEventInvite (CalendarInvite const *invite) const
void SendCalendarEventInviteAlert (CalendarInvite const *invite) const
void SendCalendarCommandResult (Player *player, CalendarError err, char const *param=nullptr) const
void SendCalendarEventRemovedAlert (CalendarEvent const *event) const
void SendCalendarEvent (Player *player, CalendarEvent const *event, uint32 sendType) const
void SendCalendarEventInviteRemoveAlert (Player *player, CalendarEvent const *event, CalendarInviteStatus status) const
void SendCalendarEventInviteRemove (CalendarInvite const *invite, uint32 flags) const
void SendCalendarEventStatus (CalendarInvite const *invite) const
void SendCalendarClearPendingAction (Player *player) const
void SendCalendarEventModeratorStatusAlert (CalendarInvite const *invite) const
void SendCalendarEventUpdateAlert (CalendarEvent const *event, time_t oldEventTime) const
void SendCalendarRaidLockoutRemove (Player *player, DungeonPersistentState const *save) const
void SendCalendarRaidLockoutAdd (Player *player, DungeonPersistentState const *save) const
void SendPacketToAllEventRelatives (const WorldPacket &packet, CalendarEvent const *event) const
Private Member Functions
uint64 GetNewEventId ()
uint64 GetNewInviteId ()
bool CanAddInviteTo (ObjectGuid const &guid)
bool CanAddGuildEvent (uint32 guildId)
bool CanAddEvent (ObjectGuid const &guid)
Private Attributes
CalendarEventStore m_EventStore
uint64 m_MaxEventId
uint64 m_MaxInviteId
Detailed Description
Definition at line 217 of file Calendar.h.
Constructor & Destructor Documentation
CalendarMgr()
CalendarMgr::CalendarMgr () inline
Definition at line 220 of file Calendar.h.
~CalendarMgr()
CalendarMgr::~CalendarMgr () inline
Definition at line 221 of file Calendar.h.
Member Function Documentation
AddEvent()
CalendarEvent * CalendarMgr::AddEvent (ObjectGuid const & guid, std::string title, std::string description, uint32 type, uint32 repeatable, uint32 maxInvites, int32 dungeonId, time_t eventTime, time_t unkTime, uint32 flags)
Definition at line 249 of file Calendar.cpp.
References CALENDAR_ERROR_EVENTS_EXCEEDED, CALENDAR_ERROR_GUILD_EVENTS_EXCEEDED, CALENDAR_ERROR_GUILD_PLAYER_NOT_IN_GUILD, CALENDAR_ERROR_INVALID_DATE, CALENDAR_ERROR_NEEDS_TITLE, CALENDAR_FLAG_GUILD_ANNOUNCEMENT, CALENDAR_FLAG_GUILD_EVENT, CanAddEvent(), CanAddGuildEvent(), CharacterDatabase, CalendarEvent::CreatorGuid, DEBUG_FILTER_LOG, CalendarEvent::Description, CalendarEvent::DungeonId, Database::escape_string(), CalendarEvent::EventId, CalendarEvent::EventTime, CalendarEvent::Flags, ObjectGuid::GetCounter(), Player::GetGuildId(), GetNewEventId(), CalendarEvent::GuildId, LOG_FILTER_CALENDAR, m_EventStore, Database::PExecute(), CalendarEvent::Repeatable, SendCalendarCommandResult(), sObjectMgr, CalendarEvent::Title, CalendarEvent::Type, and UI64FMTD.
Referenced by CopyEvent().
AddInvite()
CalendarInvite * CalendarMgr::AddInvite (CalendarEvent * event, ObjectGuid const & senderGuid, ObjectGuid const & inviteeGuid, CalendarInviteStatus status, CalendarModerationRank rank, const std::string & text, time_t statusTime)
Definition at line 357 of file Calendar.cpp.
References CalendarEvent::AddInvite(), CALENDAR_ERROR_ALREADY_INVITED_TO_EVENT_S, CALENDAR_ERROR_OTHER_INVITES_EXCEEDED_S, CanAddInviteTo(), CharacterDatabase, CalendarEvent::CreatorGuid, DEBUG_FILTER_LOG, CalendarEvent::EventId, ObjectGuid::GetCounter(), CalendarEvent::GetInviteByGuid(), GetNewInviteId(), ObjectGuid::GetString(), CalendarInvite::InviteeGuid, CalendarInvite::InviteId, CalendarEvent::IsGuildAnnouncement(), CalendarEvent::IsGuildEvent(), LOG_FILTER_CALENDAR, Database::PExecute(), SendCalendarCommandResult(), SendCalendarEventInvite(), SendCalendarEventInviteAlert(), sLog, sObjectMgr, and UI64FMTD.
Referenced by CopyEvent().
CanAddEvent()
bool CalendarMgr::CanAddEvent (ObjectGuid const & guid) private
Definition at line 686 of file Calendar.cpp.
References CALENDAR_MAX_EVENTS, and m_EventStore.
Referenced by AddEvent().
CanAddGuildEvent()
bool CalendarMgr::CanAddGuildEvent (uint32 guildId) private
Definition at line 697 of file Calendar.cpp.
References CALENDAR_MAX_GUILD_EVENTS, and m_EventStore.
Referenced by AddEvent().
CanAddInviteTo()
bool CalendarMgr::CanAddInviteTo (ObjectGuid const & guid) private
Definition at line 711 of file Calendar.cpp.
References CALENDAR_MAX_INVITES, CalendarEvent::GetInviteMap(), and m_EventStore.
Referenced by AddInvite().
CopyEvent()
void CalendarMgr::CopyEvent (uint64 eventId, time_t newTime, ObjectGuid const & guid)
Definition at line 468 of file Calendar.cpp.
References AddEvent(), AddInvite(), CALENDAR_ERROR_EVENT_INVALID, CALENDAR_MAX_INVITES, CALENDAR_RANK_MODERATOR, CALENDAR_RANK_OWNER, CALENDAR_RANK_PLAYER, CALENDAR_SENDTYPE_COPY, CALENDAR_STATUS_CONFIRMED, CALENDAR_STATUS_INVITED, GetEventById(), CalendarInvite::InviteeGuid, CalendarEvent::IsGuildAnnouncement(), CalendarInvite::Rank, SendCalendarCommandResult(), SendCalendarEvent(), and sObjectMgr.
GetEventById()
CalendarEvent* CalendarMgr::GetEventById (uint64 eventId) inline
Definition at line 239 of file Calendar.h.
References m_EventStore.
Referenced by CopyEvent(), and LoadCalendarsFromDB().
GetNewEventId()
uint64 CalendarMgr::GetNewEventId () inline private
Definition at line 266 of file Calendar.h.
References m_MaxEventId.
Referenced by AddEvent().
GetNewInviteId()
uint64 CalendarMgr::GetNewInviteId () inline private
Definition at line 267 of file Calendar.h.
References m_MaxInviteId.
Referenced by AddInvite().
GetPlayerEventsList()
void CalendarMgr::GetPlayerEventsList (ObjectGuid const & guid, CalendarEventsList & calEventList)
Definition at line 196 of file Calendar.cpp.
References Player::GetGuildId(), Player::GetGuildIdFromDB(), m_EventStore, and sObjectMgr.
GetPlayerInvitesList()
void CalendarMgr::GetPlayerInvitesList (ObjectGuid const & guid, CalendarInvitesList & calInvList)
Definition at line 223 of file Calendar.cpp.
References CalendarEvent::GetInviteMap(), and m_EventStore.
Referenced by GetPlayerNumPending().
GetPlayerNumPending()
uint32 CalendarMgr::GetPlayerNumPending (ObjectGuid const & guid)
Definition at line 439 of file Calendar.cpp.
References CALENDAR_FLAG_INVITES_LOCKED, CALENDAR_STATUS_INVITED, CALENDAR_STATUS_NOT_SIGNED_UP, CALENDAR_STATUS_TENTATIVE, and GetPlayerInvitesList().
LoadCalendarsFromDB()
void CalendarMgr::LoadCalendarsFromDB ()
Definition at line 567 of file Calendar.cpp.
References CharacterDatabase, CalendarEvent::CreatorGuid, CalendarEvent::Description, Database::DirectExecute(), CalendarEvent::DungeonId, CalendarEvent::EventId, CalendarEvent::EventTime, QueryResult::Fetch(), CalendarEvent::Flags, Field::GetCppString(), GetEventById(), Field::GetInt32(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt64(), CalendarEvent::GuildId, HIGHGUID_PLAYER, m_EventStore, m_MaxEventId, m_MaxInviteId, QueryResult::NextRow(), Database::PExecute(), Database::Query(), sLog, BarGoLink::step(), CalendarEvent::Title, CalendarEvent::Type, and UI64FMTD.
RemoveEvent()
void CalendarMgr::RemoveEvent (uint64 eventId, Player * remover)
Definition at line 329 of file Calendar.cpp.
References CALENDAR_ERROR_EVENT_INVALID, CALENDAR_ERROR_PERMISSIONS, CharacterDatabase, Object::GetObjectGuid(), m_EventStore, Database::PExecute(), SendCalendarCommandResult(), SendCalendarEventRemovedAlert(), and UI64FMTD.
RemoveGuildCalendar()
void CalendarMgr::RemoveGuildCalendar (ObjectGuid const & playerGuid, uint32 GuildId)
Definition at line 539 of file Calendar.cpp.
References m_EventStore.
RemoveInvite()
bool CalendarMgr::RemoveInvite (uint64 eventId, uint64 inviteId, ObjectGuid const & removerGuid)
Definition at line 423 of file Calendar.cpp.
References CALENDAR_ERROR_EVENT_INVALID, m_EventStore, CalendarEvent::RemoveInviteById(), SendCalendarCommandResult(), and sObjectMgr.
RemovePlayerCalendar()
void CalendarMgr::RemovePlayerCalendar (ObjectGuid const & playerGuid)
Definition at line 517 of file Calendar.cpp.
References m_EventStore, and CalendarEvent::RemoveInviteByGuid().
SendCalendarClearPendingAction()
void CalendarMgr::SendCalendarClearPendingAction (Player * player) const
Definition at line 955 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, Object::GetGuidStr(), LOG_FILTER_CALENDAR, Player::SendDirectMessage(), and SMSG_CALENDAR_CLEAR_PENDING_ACTION.
SendCalendarCommandResult()
void CalendarMgr::SendCalendarCommandResult (Player * player, CalendarError err, char const * param = nullptr) const
Definition at line 820 of file CalendarHandler.cpp.
References CALENDAR_ERROR_ALREADY_INVITED_TO_EVENT_S, CALENDAR_ERROR_IGNORING_YOU_S, CALENDAR_ERROR_OTHER_INVITES_EXCEEDED_S, DEBUG_FILTER_LOG, LOG_FILTER_CALENDAR, Player::SendDirectMessage(), and SMSG_CALENDAR_COMMAND_RESULT.
Referenced by AddEvent(), AddInvite(), CopyEvent(), RemoveEvent(), and RemoveInvite().
SendCalendarEvent()
void CalendarMgr::SendCalendarEvent (Player * player, CalendarEvent const * event, uint32 sendType) const
Definition at line 857 of file CalendarHandler.cpp.
References CALENDAR_MAX_INVITES, CalendarEvent::CreatorGuid, DEBUG_FILTER_LOG, CalendarEvent::EventId, CalendarEvent::EventTime, CalendarEvent::Flags, Player::GetGuildId(), Player::GetGuildIdFromDB(), Unit::GetLevel(), Player::GetLevelFromDB(), ObjectGuid::GetString(), CalendarEvent::GuildId, CalendarInvite::InviteeGuid, CalendarInvite::InviteId, CalendarEvent::IsGuildEvent(), CalendarInvite::LastUpdateTime, LOG_FILTER_CALENDAR, CalendarInvite::Rank, CalendarEvent::Repeatable, secsToTimeBitFields(), Player::SendDirectMessage(), ByteBuffer::size(), SMSG_CALENDAR_SEND_EVENT, sObjectMgr, CalendarInvite::Status, CalendarInvite::Text, CalendarEvent::Title, CalendarEvent::Type, UI64FMTD, CalendarEvent::UnknownTime, and ObjectGuid::WriteAsPacked().
Referenced by CopyEvent().
SendCalendarEventInvite()
void CalendarMgr::SendCalendarEventInvite (CalendarInvite const * invite) const
Definition at line 779 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, CalendarInvite::GetCalendarEvent(), Unit::GetLevel(), Player::GetLevelFromDB(), ObjectGuid::GetString(), CalendarInvite::InviteeGuid, CalendarInvite::InviteId, CalendarInvite::LastUpdateTime, LOG_FILTER_CALENDAR, secsToTimeBitFields(), CalendarInvite::SenderGuid, SendPacketToAllEventRelatives(), SMSG_CALENDAR_EVENT_INVITE, sObjectMgr, CalendarInvite::Status, UI64FMTD, and ObjectGuid::WriteAsPacked().
Referenced by AddInvite().
SendCalendarEventInviteAlert()
void CalendarMgr::SendCalendarEventInviteAlert (CalendarInvite const * invite) const
Definition at line 745 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, DEBUG_LOG, CalendarInvite::GetCalendarEvent(), ObjectGuid::GetString(), CalendarInvite::InviteeGuid, CalendarInvite::InviteId, LOG_FILTER_CALENDAR, CalendarInvite::Rank, secsToTimeBitFields(), CalendarInvite::SenderGuid, sGuildMgr, SMSG_CALENDAR_EVENT_INVITE_ALERT, sObjectMgr, CalendarInvite::Status, UI64FMTD, and ObjectGuid::WriteAsPacked().
Referenced by AddInvite().
SendCalendarEventInviteRemove()
void CalendarMgr::SendCalendarEventInviteRemove (CalendarInvite const * invite, uint32 flags) const
Definition at line 908 of file CalendarHandler.cpp.
References ByteBuffer::appendPackGUID(), DEBUG_FILTER_LOG, CalendarInvite::GetCalendarEvent(), CalendarInvite::InviteeGuid, LOG_FILTER_CALENDAR, SendPacketToAllEventRelatives(), and SMSG_CALENDAR_EVENT_INVITE_REMOVED.
SendCalendarEventInviteRemoveAlert()
void CalendarMgr::SendCalendarEventInviteRemoveAlert (Player * player, CalendarEvent const * event, CalendarInviteStatus status) const
Definition at line 923 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, CalendarEvent::EventId, CalendarEvent::EventTime, CalendarEvent::Flags, LOG_FILTER_CALENDAR, secsToTimeBitFields(), Player::SendDirectMessage(), and SMSG_CALENDAR_EVENT_INVITE_REMOVED_ALERT.
SendCalendarEventModeratorStatusAlert()
void CalendarMgr::SendCalendarEventModeratorStatusAlert (CalendarInvite const * invite) const
Definition at line 965 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, CalendarInvite::GetCalendarEvent(), CalendarInvite::InviteeGuid, LOG_FILTER_CALENDAR, CalendarInvite::Rank, SendPacketToAllEventRelatives(), SMSG_CALENDAR_EVENT_MODERATOR_STATUS_ALERT, and ObjectGuid::WriteAsPacked().
SendCalendarEventRemovedAlert()
void CalendarMgr::SendCalendarEventRemovedAlert (CalendarEvent const * event) const
Definition at line 846 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, CalendarEvent::EventId, CalendarEvent::EventTime, LOG_FILTER_CALENDAR, secsToTimeBitFields(), SendPacketToAllEventRelatives(), and SMSG_CALENDAR_EVENT_REMOVED_ALERT.
Referenced by RemoveEvent().
SendCalendarEventStatus()
void CalendarMgr::SendCalendarEventStatus (CalendarInvite const * invite) const
Definition at line 938 of file CalendarHandler.cpp.
References DEBUG_FILTER_LOG, CalendarInvite::GetCalendarEvent(), CalendarInvite::InviteeGuid, CalendarInvite::LastUpdateTime, LOG_FILTER_CALENDAR, CalendarInvite::Rank, secsToTimeBitFields(), SendPacketToAllEventRelatives(), SMSG_CALENDAR_EVENT_STATUS, CalendarInvite::Status, and ObjectGuid::WriteAsPacked().
SendCalendarEventUpdateAlert()
void CalendarMgr::SendCalendarEventUpdateAlert (CalendarEvent const * event, time_t oldEventTime) const
Definition at line 978 of file CalendarHandler.cpp.
References CALENDAR_MAX_INVITES, DEBUG_FILTER_LOG, CalendarEvent::Description, CalendarEvent::DungeonId, CalendarEvent::EventId, CalendarEvent::EventTime, CalendarEvent::Flags, LOG_FILTER_CALENDAR, CalendarEvent::Repeatable, secsToTimeBitFields(), SendPacketToAllEventRelatives(), SMSG_CALENDAR_EVENT_UPDATED_ALERT, CalendarEvent::Title, CalendarEvent::Type, and CalendarEvent::UnknownTime.
SendCalendarRaidLockoutAdd()
void CalendarMgr::SendCalendarRaidLockoutAdd (Player * player, DungeonPersistentState const * save) const
Definition at line 1032 of file CalendarHandler.cpp.
References DEBUG_LOG, MapPersistentState::GetDifficulty(), Object::GetGuidStr(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMapId(), DungeonPersistentState::GetResetTime(), secsToTimeBitFields(), Player::SendDirectMessage(), and SMSG_CALENDAR_RAID_LOCKOUT_ADDED.
SendCalendarRaidLockoutRemove()
void CalendarMgr::SendCalendarRaidLockoutRemove (Player * player, DungeonPersistentState const * save) const
Definition at line 1015 of file CalendarHandler.cpp.
References DEBUG_LOG, MapPersistentState::GetDifficulty(), Object::GetGuidStr(), MapPersistentState::GetInstanceId(), MapPersistentState::GetMapId(), DungeonPersistentState::GetResetTime(), Player::SendDirectMessage(), and SMSG_CALENDAR_RAID_LOCKOUT_REMOVED.
SendPacketToAllEventRelatives()
void CalendarMgr::SendPacketToAllEventRelatives (const WorldPacket & packet, CalendarEvent const * event) const
Definition at line 1000 of file CalendarHandler.cpp.
References CalendarEvent::GuildId, CalendarEvent::IsGuildAnnouncement(), CalendarEvent::IsGuildEvent(), sGuildMgr, and sObjectMgr.
Referenced by SendCalendarEventInvite(), SendCalendarEventInviteRemove(), SendCalendarEventModeratorStatusAlert(), SendCalendarEventRemovedAlert(), SendCalendarEventStatus(), and SendCalendarEventUpdateAlert().
Field Documentation
m_EventStore
CalendarEventStore CalendarMgr::m_EventStore private
Definition at line 273 of file Calendar.h.
Referenced by AddEvent(), CanAddEvent(), CanAddGuildEvent(), CanAddInviteTo(), GetEventById(), GetPlayerEventsList(), GetPlayerInvitesList(), LoadCalendarsFromDB(), RemoveEvent(), RemoveGuildCalendar(), RemoveInvite(), and RemovePlayerCalendar().
m_MaxEventId
uint64 CalendarMgr::m_MaxEventId private
Definition at line 274 of file Calendar.h.
Referenced by GetNewEventId(), and LoadCalendarsFromDB().
m_MaxInviteId
uint64 CalendarMgr::m_MaxInviteId private
Definition at line 275 of file Calendar.h.
Referenced by GetNewInviteId(), and LoadCalendarsFromDB().
The documentation for this class was generated from the following files:
Calendar.h
Calendar.cpp
CalendarHandler.cpp