CMaNGOS_WoTLK: CreatureSettings Class Reference
CreatureSettings Class Reference
#include <CreatureSettings.h>
Public Member Functions
CreatureSettings (Creature *owner)
void ResetStaticFlags (CreatureStaticFlags staticFlags, CreatureStaticFlags2 staticFlags2, CreatureStaticFlags3 staticFlags3, CreatureStaticFlags4 staticFlags4)
void SetFlag (CreatureStaticFlags flag)
void SetFlag (CreatureStaticFlags2 flag)
void SetFlag (CreatureStaticFlags3 flag)
void SetFlag (CreatureStaticFlags4 flag)
void RemoveFlag (CreatureStaticFlags flag)
void RemoveFlag (CreatureStaticFlags2 flag)
void RemoveFlag (CreatureStaticFlags3 flag)
void RemoveFlag (CreatureStaticFlags4 flag)
bool HasFlag (CreatureStaticFlags flag) const
bool HasFlag (CreatureStaticFlags2 flag) const
bool HasFlag (CreatureStaticFlags3 flag) const
bool HasFlag (CreatureStaticFlags4 flag) const
Private Member Functions
void updateFlag (CreatureStaticFlags flag, bool apply)
void updateFlag (CreatureStaticFlags2 flag, bool apply)
void updateFlag (CreatureStaticFlags3 flag, bool apply)
void updateFlag (CreatureStaticFlags4 flag, bool apply)
Private Attributes
CreatureStaticFlags m_flags
CreatureStaticFlags2 m_flags2
CreatureStaticFlags3 m_flags3
CreatureStaticFlags4 m_flags4
Creature * m_owner
Detailed Description
Definition at line 25 of file CreatureSettings.h.
Constructor & Destructor Documentation
CreatureSettings()
CreatureSettings::CreatureSettings (Creature * owner)
Definition at line 25 of file CreatureSettings.cpp.
Member Function Documentation
HasFlag() [1/4]
bool CreatureSettings::HasFlag (CreatureStaticFlags flag) const
Definition at line 93 of file CreatureSettings.cpp.
References m_flags.
Referenced by CreatureAI::CreatureAI(), CreatureAI::DamageTaken(), CreatureAI::EnterCombat(), Creature::IsIgnoringFeignDeath(), Creature::IsNoLoot(), Creature::IsNoWeaponSkillGain(), Creature::IsNoWoundedSlowdown(), Creature::IsNoXp(), Creature::IsPreventingDeath(), and ResetStaticFlags().
HasFlag() [2/4]
bool CreatureSettings::HasFlag (CreatureStaticFlags2 flag) const
Definition at line 98 of file CreatureSettings.cpp.
References m_flags2.
HasFlag() [3/4]
bool CreatureSettings::HasFlag (CreatureStaticFlags3 flag) const
Definition at line 103 of file CreatureSettings.cpp.
References m_flags3.
HasFlag() [4/4]
bool CreatureSettings::HasFlag (CreatureStaticFlags4 flag) const
Definition at line 108 of file CreatureSettings.cpp.
References m_flags4.
RemoveFlag() [1/4]
void CreatureSettings::RemoveFlag (CreatureStaticFlags flag)
Definition at line 69 of file CreatureSettings.cpp.
References m_flags, and updateFlag().
Referenced by CreatureAI::SetDeathPrevention(), Creature::SetIgnoreFeignDeath(), Creature::SetNoLoot(), Creature::SetNoWeaponSkillGain(), Creature::SetNoWoundedSlowdown(), and Creature::SetNoXP().
RemoveFlag() [2/4]
void CreatureSettings::RemoveFlag (CreatureStaticFlags2 flag)
Definition at line 75 of file CreatureSettings.cpp.
References m_flags2, and updateFlag().
RemoveFlag() [3/4]
void CreatureSettings::RemoveFlag (CreatureStaticFlags3 flag)
Definition at line 81 of file CreatureSettings.cpp.
References m_flags3, and updateFlag().
RemoveFlag() [4/4]
void CreatureSettings::RemoveFlag (CreatureStaticFlags4 flag)
Definition at line 87 of file CreatureSettings.cpp.
References m_flags4, and updateFlag().
ResetStaticFlags()
void CreatureSettings::ResetStaticFlags (CreatureStaticFlags staticFlags, CreatureStaticFlags2 staticFlags2, CreatureStaticFlags3 staticFlags3, CreatureStaticFlags4 staticFlags4)
Definition at line 29 of file CreatureSettings.cpp.
References WorldObject::GetVisibilityData(), Gigantic, GIGANTIC_AOI, HasFlag(), Infinite, INFINITE_AOI, Large, LARGE_AOI, m_flags, m_flags2, m_flags3, m_flags4, m_owner, and VisibilityData::SetVisibilityDistanceOverride().
Referenced by Creature::UpdateEntry().
SetFlag() [1/4]
void CreatureSettings::SetFlag (CreatureStaticFlags flag)
Definition at line 45 of file CreatureSettings.cpp.
References m_flags, and updateFlag().
Referenced by CreatureAI::SetDeathPrevention(), Creature::SetIgnoreFeignDeath(), Creature::SetNoLoot(), Creature::SetNoWeaponSkillGain(), Creature::SetNoWoundedSlowdown(), and Creature::SetNoXP().
SetFlag() [2/4]
void CreatureSettings::SetFlag (CreatureStaticFlags2 flag)
Definition at line 51 of file CreatureSettings.cpp.
References m_flags2, and updateFlag().
SetFlag() [3/4]
void CreatureSettings::SetFlag (CreatureStaticFlags3 flag)
Definition at line 57 of file CreatureSettings.cpp.
References m_flags3, and updateFlag().
SetFlag() [4/4]
void CreatureSettings::SetFlag (CreatureStaticFlags4 flag)
Definition at line 63 of file CreatureSettings.cpp.
References m_flags4, and updateFlag().
updateFlag() [1/4]
void CreatureSettings::updateFlag (CreatureStaticFlags flag, bool apply) private
Definition at line 113 of file CreatureSettings.cpp.
References Creature::AI(), ByteConverter::apply(), m_owner, NO_MELEE_FLEE, SESSILE, UnitAI::SetAIImmobilizedState(), UnitAI::SetMeleeEnabled(), and UNKILLABLE.
Referenced by RemoveFlag(), and SetFlag().
updateFlag() [2/4]
void CreatureSettings::updateFlag (CreatureStaticFlags2 flag, bool apply) private
Definition at line 131 of file CreatureSettings.cpp.
updateFlag() [3/4]
void CreatureSettings::updateFlag (CreatureStaticFlags3 flag, bool apply) private
Definition at line 135 of file CreatureSettings.cpp.
updateFlag() [4/4]
void CreatureSettings::updateFlag (CreatureStaticFlags4 flag, bool apply) private
Definition at line 139 of file CreatureSettings.cpp.
Field Documentation
m_flags
CreatureStaticFlags CreatureSettings::m_flags private
Definition at line 50 of file CreatureSettings.h.
Referenced by HasFlag(), RemoveFlag(), ResetStaticFlags(), and SetFlag().
m_flags2
CreatureStaticFlags2 CreatureSettings::m_flags2 private
Definition at line 51 of file CreatureSettings.h.
Referenced by HasFlag(), RemoveFlag(), ResetStaticFlags(), and SetFlag().
m_flags3
CreatureStaticFlags3 CreatureSettings::m_flags3 private
Definition at line 52 of file CreatureSettings.h.
Referenced by HasFlag(), RemoveFlag(), ResetStaticFlags(), and SetFlag().
m_flags4
CreatureStaticFlags4 CreatureSettings::m_flags4 private
Definition at line 53 of file CreatureSettings.h.
Referenced by HasFlag(), RemoveFlag(), ResetStaticFlags(), and SetFlag().
m_owner
Creature* CreatureSettings::m_owner private
Definition at line 54 of file CreatureSettings.h.
Referenced by ResetStaticFlags(), and updateFlag().
The documentation for this class was generated from the following files:
CreatureSettings.h
CreatureSettings.cpp