CMaNGOS_WoTLK: SpawnManager Class Reference
SpawnManager Class Reference
#include <SpawnManager.h>
Public Member Functions
SpawnManager (Map &map)
~SpawnManager ()
void Initialize ()
void AddCreature (uint32 respawnDelay, uint32 dbguid)
void AddGameObject (uint32 respawnDelay, uint32 dbguid)
void RespawnCreature (uint32 dbguid, uint32 respawnDelay=0)
void RespawnGameObject (uint32 dbguid, uint32 respawnDelay=0)
void RespawnAll ()
void Update ()
std::string GetRespawnList ()
SpawnGroup * GetSpawnGroup (uint32 Id)
void RespawnSpawnGroupsInVicinity (Position pos, float range)
Private Attributes
Map & m_map
std::vector< SpawnInfo > m_spawns
std::map< uint32, SpawnGroup * > m_spawnGroups
Detailed Description
Definition at line 51 of file SpawnManager.h.
Constructor & Destructor Documentation
SpawnManager()
SpawnManager::SpawnManager (Map & map) inline
Definition at line 54 of file SpawnManager.h.
~SpawnManager()
SpawnManager::~SpawnManager ()
Definition at line 44 of file SpawnManager.cpp.
References m_spawnGroups.
Member Function Documentation
AddCreature()
void SpawnManager::AddCreature (uint32 respawnDelay, uint32 dbguid)
Definition at line 78 of file SpawnManager.cpp.
References Map::GetCurrentClockTime(), HIGHGUID_UNIT, m_map, and m_spawns.
Referenced by RespawnCreature(), instance_sunwell_plateau::SetData(), and Creature::SetDeathState().
AddGameObject()
void SpawnManager::AddGameObject (uint32 respawnDelay, uint32 dbguid)
Definition at line 84 of file SpawnManager.cpp.
References Map::GetCurrentClockTime(), HIGHGUID_GAMEOBJECT, m_map, and m_spawns.
Referenced by RespawnGameObject(), and GameObject::Update().
GetRespawnList()
std::string SpawnManager::GetRespawnList ()
Definition at line 170 of file SpawnManager.cpp.
References Map::GetCurrentClockTime(), HIGHGUID_UNIT, HOUR, IN_MILLISECONDS, m_map, m_spawns, and MINUTE.
Referenced by ChatHandler::HandleDebugSpawnsList().
GetSpawnGroup()
SpawnGroup * SpawnManager::GetSpawnGroup (uint32 Id)
Definition at line 196 of file SpawnManager.cpp.
References m_spawnGroups.
Referenced by ScriptAction::ExecuteDbscriptCommand(), Creature::LoadFromDB(), GameObject::LoadFromDB(), and CreatureGroup::TriggerLinkingEvent().
Initialize()
void SpawnManager::Initialize ()
Definition at line 50 of file SpawnManager.cpp.
References SpawnGroupEntry::DbGuids, Map::GetId(), Map::GetMapDataContainer(), MapDataContainer::GetSpawnGroups(), SpawnGroupEntry::Id, m_map, m_spawnGroups, sObjectMgr, SPAWN_GROUP_CREATURE, and SpawnGroupEntry::Type.
Referenced by Map::Initialize().
RespawnAll()
void SpawnManager::RespawnAll ()
Definition at line 140 of file SpawnManager.cpp.
References Map::GetPersistentState(), HIGHGUID_GAMEOBJECT, HIGHGUID_UNIT, m_map, m_spawns, MapPersistentState::SaveCreatureRespawnTime(), and MapPersistentState::SaveGORespawnTime().
Referenced by ChatHandler::HandleDebugRespawnDynguid().
RespawnCreature()
void SpawnManager::RespawnCreature (uint32 dbguid, uint32 respawnDelay = 0)
Definition at line 90 of file SpawnManager.cpp.
References AddCreature(), Map::GetCurrentClockTime(), Map::GetPersistentState(), HIGHGUID_UNIT, m_map, m_spawns, and MapPersistentState::SaveCreatureRespawnTime().
Referenced by BattleGround::ChangeBgCreatureSpawnState(), CreatureLinkingHolder::DoCreatureLinkingEvent(), ChatHandler::HandleDebugRespawnDynguid(), ChatHandler::HandleRespawnCommand(), MaNGOS::RespawnDo::operator()(), CreatureLinkingHolder::ProcessSlaveGuidList(), and ScriptedInstance::RespawnDbGuids().
RespawnGameObject()
void SpawnManager::RespawnGameObject (uint32 dbguid, uint32 respawnDelay = 0)
Definition at line 115 of file SpawnManager.cpp.
References AddGameObject(), Map::GetCurrentClockTime(), Map::GetPersistentState(), HIGHGUID_GAMEOBJECT, m_map, m_spawns, and MapPersistentState::SaveGORespawnTime().
Referenced by BattleGround::ChangeBgObjectSpawnState(), and PoolGroup< T >::Spawn1Object().
RespawnSpawnGroupsInVicinity()
void SpawnManager::RespawnSpawnGroupsInVicinity (Position pos, float range)
Definition at line 205 of file SpawnManager.cpp.
References m_spawnGroups.
Referenced by ChatHandler::HandleRespawnCommand().
Update()
void SpawnManager::Update ()
Definition at line 153 of file SpawnManager.cpp.
References Map::GetCurrentClockTime(), m_map, m_spawnGroups, and m_spawns.
Referenced by Map::Update().
Field Documentation
m_map
Map& SpawnManager::m_map private
Definition at line 74 of file SpawnManager.h.
Referenced by AddCreature(), AddGameObject(), GetRespawnList(), Initialize(), RespawnAll(), RespawnCreature(), RespawnGameObject(), and Update().
m_spawnGroups
std::map<uint32, SpawnGroup*> SpawnManager::m_spawnGroups private
Definition at line 77 of file SpawnManager.h.
Referenced by GetSpawnGroup(), Initialize(), RespawnSpawnGroupsInVicinity(), Update(), and ~SpawnManager().
m_spawns
std::vector<SpawnInfo> SpawnManager::m_spawns private
Definition at line 76 of file SpawnManager.h.
Referenced by AddCreature(), AddGameObject(), GetRespawnList(), RespawnAll(), RespawnCreature(), RespawnGameObject(), and Update().
The documentation for this class was generated from the following files:
SpawnManager.h
SpawnManager.cpp