CMaNGOS_WoTLK: ObjectGridRespawnMover Class Reference
ObjectGridRespawnMover Class Reference
Public Member Functions
ObjectGridRespawnMover ()
void Move (GridType &grid)
template<class T >
void Visit (GridRefManager< T > &)
void Visit (CreatureMapType &m)
Detailed Description
Definition at line 30 of file ObjectGridLoader.cpp.
Constructor & Destructor Documentation
ObjectGridRespawnMover()
ObjectGridRespawnMover::ObjectGridRespawnMover () inline
Definition at line 33 of file ObjectGridLoader.cpp.
Member Function Documentation
Move()
void ObjectGridRespawnMover::Move (GridType & grid)
Definition at line 42 of file ObjectGridLoader.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::Visit().
Referenced by ObjectGridUnloader::MoveToRespawnN().
Visit() [1/2]
void ObjectGridRespawnMover::Visit (CreatureMapType & m)
Definition at line 49 of file ObjectGridLoader.cpp.
References GridRefManager< OBJECT >::begin(), MaNGOS::ComputeCellPair(), Map::CreatureRespawnRelocation(), Cell::DiffGrid(), GridRefManager< OBJECT >::end(), WorldObject::GetCurrentCell(), WorldObject::GetMap(), Creature::GetRespawnCoord(), Creature::IsPet(), and MANGOS_ASSERT.
Visit() [2/2]
template<class T > void ObjectGridRespawnMover::Visit (GridRefManager< T > &) inline
Definition at line 37 of file ObjectGridLoader.cpp.
The documentation for this class was generated from the following file:
ObjectGridLoader.cpp