CMaNGOS_WoTLK: CreatureEventAI Class Reference
CreatureEventAI Class Reference
#include <CreatureEventAI.h>
Public Member Functions
CreatureEventAI (Creature *creature)
~CreatureEventAI ()
void InitAI ()
void GetAIInformation (ChatHandler &reader) override
== Information about AI ========================
void JustRespawned () override
Called when creature is respawned (for reseting variables)
void Reset () override
void JustReachedHome () override
Called at reaching home after MoveTargetedHome.
void EnterCombat (Unit *enemy) override
Called for reaction at enter to combat if not in combat yet.
void EnterEvadeMode () override
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
void JustDied (Unit *killer) override
Called when the creature is killed.
void KilledUnit (Unit *victim) override
Called when the creature kills a unit.
void JustSummoned (Creature *summoned) override
Called when the creature summon successfully other creature.
void MoveInLineOfSight (Unit *who) override
== Reactions At =================================
void SpellHit (Unit *unit, const SpellEntry *spellInfo) override
Called when hit by a spell.
void SpellHitTarget (Unit *target, const SpellEntry *spell) override
void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damagetype, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
void JustPreventedDeath (Unit *attacker)
void HealedBy (Unit *healer, uint32 &healedAmount) override
Called at any Heal received from any Unit.
void ReceiveEmote (Player *player, uint32 textEmote) override
Called at text emote receive from player.
void SummonedCreatureJustDied (Creature *summoned) override
Called when a summoned creature is killed.
void SummonedCreatureDespawn (Creature *summoned) override
Called when a summoned creature gets TemporarySummon::UnSummon ed.
void ReceiveAIEvent (AIEventType eventType, Unit *sender, Unit *invoker, uint32 miscValue) override
Called when an AI Event is received.
void CorpseRemoved (uint32 &respawnDelay) override
Called when the corpse of this creature gets removed.
void OnSpellCast (SpellEntry const *spellInfo, Unit *target) override
virtual void UpdateEventTimers (const uint32 diff) override
void ProcessEvents (Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
bool CheckEvent (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
void ResetEvent (CreatureEventAIHolder &holder)
void CheckAndReadyEventForExecution (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
void IncreaseDepthIfNecessary ()
virtual bool ProcessEvent (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
virtual bool ProcessAction (CreatureEventAI_Action const &action, uint32 rnd, uint32 eventId, Unit *actionInvoker, Unit *AIEventSender, Unit *eventTarget)
uint32 GetRandActionParam (uint32 rnd, uint32 param1, uint32 param2, uint32 param3) const
int32 GetRandActionParam (uint32 rnd, int32 param1, int32 param2, int32 param3) const
Unit * GetTargetByType (uint32 target, Unit *actionInvoker, Unit *AIEventSender, Unit *eventTarget, bool &isError, uint32 forSpellId=0, uint32 selectFlags=0) const
If the bool& param is true, an error should be reported.
bool SpawnedEventConditionsCheck (CreatureEventAI_Event const &event) const
MovementGeneratorType GetDefaultMovement ()
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Static Public Member Functions
static int Permissible (const Creature *creature)
Protected Types
typedef std::vector< CreatureEventAIHolder > CreatureEventAIList
Protected Member Functions
std::string GetAIName () override
bool IsTimerExecutedEvent (EventAI_Type type) const
bool IsRepeatableEvent (EventAI_Type type) const
bool IsTimerBasedEvent (EventAI_Type type) const
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes
uint32 m_EventUpdateTime
uint32 m_EventDiff
bool m_bEmptyList
CreatureEventAIList m_CreatureEventAIList
std::vector< std::vector< std::reference_wrapper< CreatureEventAIHolder > > > m_creatureEventAITempList
uint32 m_depth
uint8 m_Phase
bool m_HasOOCLoSEvent
uint32 m_InvinceabilityHpLevel
uint32 m_throwAIEventMask
uint32 m_throwAIEventStep
float m_LastSpellMaxRange
uint32 m_despawnAggregationMask
std::set< uint32 > m_entriesForDespawn
GuidVector m_despawnGuids
MovementGeneratorType m_defaultMovement
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 855 of file CreatureEventAI.h.
Member Typedef Documentation
CreatureEventAIList
typedef std::vector<CreatureEventAIHolder> CreatureEventAI::CreatureEventAIList protected
Definition at line 920 of file CreatureEventAI.h.
Constructor & Destructor Documentation
CreatureEventAI()
CreatureEventAI::CreatureEventAI (Creature * creature) explicit
Definition at line 94 of file CreatureEventAI.cpp.
~CreatureEventAI()
CreatureEventAI::~CreatureEventAI () inline
Definition at line 859 of file CreatureEventAI.h.
References m_CreatureEventAIList.
Member Function Documentation
CheckAndReadyEventForExecution()
void CreatureEventAI::CheckAndReadyEventForExecution (CreatureEventAIHolder & holder, Unit * actionInvoker = nullptr, Unit * AIEventSender = nullptr)
Definition at line 622 of file CreatureEventAI.cpp.
References CheckEvent(), CreatureEventAIHolder::inProgress, m_creatureEventAITempList, and m_depth.
Referenced by EnterCombat(), GuardianAI::EnterEvadeMode(), TotemAI::EnterEvadeMode(), EnterEvadeMode(), JustDied(), JustPreventedDeath(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), OnSpellCast(), ReceiveAIEvent(), ReceiveEmote(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), SummonedCreatureJustDied(), and UpdateEventTimers().
CheckEvent()
bool CreatureEventAI::CheckEvent (CreatureEventAIHolder & holder, Unit * actionInvoker = nullptr, Unit * AIEventSender = nullptr)
Definition at line 295 of file CreatureEventAI.cpp.
References ATTACKING_TARGET_RANDOM, UnitAI::CanExecuteCombatAction(), CONDITION_FROM_EVENTAI, DEBUG_FILTER_LOG, UnitAI::DoFindFriendlyEligibleDispel(), UnitAI::DoFindFriendlyMissingBuff(), UnitAI::DoSelectLowestHpFriendly(), EFLAG_COMBAT_ACTION, EFLAG_MELEE_MODE_ONLY, EFLAG_RANGED_MODE_ONLY, CreatureEventAIHolder::enabled, CreatureEventAIHolder::event, CreatureEventAI_Event::event_flags, CreatureEventAI_Event::event_id, CreatureEventAI_Event::event_inverse_phase_mask, EVENT_T_AGGRO, EVENT_T_AURA, EVENT_T_DEATH, EVENT_T_DEATH_PREVENTED, EVENT_T_ENERGY, EVENT_T_EVADE, EVENT_T_FACING_TARGET, EVENT_T_FRIENDLY_HP, EVENT_T_FRIENDLY_IS_CC, EVENT_T_FRIENDLY_MISSING_BUFF, EVENT_T_HP, EVENT_T_KILL, EVENT_T_MANA, EVENT_T_MISSING_AURA, EVENT_T_OOC_LOS, EVENT_T_RANGE, EVENT_T_REACHED_HOME, EVENT_T_RECEIVE_AI_EVENT, EVENT_T_RECEIVE_EMOTE, EVENT_T_SELECT_ATTACKING_TARGET, EVENT_T_SPAWNED, EVENT_T_SPELL_CAST, EVENT_T_SPELLHIT, EVENT_T_SPELLHIT_TARGET, EVENT_T_SUMMONED_JUST_DESPAWN, EVENT_T_SUMMONED_JUST_DIED, EVENT_T_SUMMONED_UNIT, EVENT_T_TARGET_AURA, EVENT_T_TARGET_CASTING, EVENT_T_TARGET_HP, EVENT_T_TARGET_MANA, EVENT_T_TARGET_MISSING_AURA, EVENT_T_TARGET_NOT_REACHABLE, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, EVENT_T_TIMER_OOC, CreatureEventAI_Event::event_type, CreatureEventAIHolder::eventTarget, CreatureEventAI_EventComputedData::friendlyHp, GetAIName(), Unit::GetBeneficiaryPlayer(), Unit::GetCombatManager(), MotionMaster::GetCurrent(), MapDataContainer::GetEAIComputedDataMap(), Object::GetEntry(), Unit::GetHealth(), WorldObject::GetMap(), Map::GetMapDataContainer(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Unit::GetMotionMaster(), Unit::GetPower(), Unit::GetSpellAuraHolder(), SpellAuraHolder::GetStackAmount(), Object::GetTypeId(), Unit::GetVictim(), Unit::HasMana(), CreatureEventAIHolder::inProgress, UnitAI::IsCombatMovement(), WorldObject::isInBackInMap(), Unit::IsInCombat(), CombatManager::IsInEvadeMode(), WorldObject::isInFrontInMap(), WorldObject::IsInMap(), WorldObject::IsInRange(), Unit::IsNonMeleeSpellCasted(), MovementGenerator::IsReachable(), IsTimerExecutedEvent(), LOG_FILTER_EVENT_AI_DEV, LOG_PROCESS_EVENT, CreatureAI::m_creature, UnitAI::m_currentRangedMode, m_Phase, POWER_ENERGY, POWER_MANA, SelectAttackingTargetParams::range, SELECT_FLAG_RANGE_RANGE, Unit::SelectAttackingTarget(), sLog, sObjectMgr, CreatureEventAIHolder::timer, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by CheckAndReadyEventForExecution().
CorpseRemoved()
void CreatureEventAI::CorpseRemoved (uint32 &) override virtual
Called when the corpse of this creature gets removed.
Parameters
uiRespawnDelay Delay (in seconds). If != 0, then this is the time after which the creature will respawn, if = 0 the default respawn-delay will be used
Reimplemented from UnitAI.
Definition at line 1606 of file CreatureEventAI.cpp.
References AGGREGATION_EVADE, UnitAI::CorpseRemoved(), UnitAI::DespawnGuids(), m_despawnAggregationMask, and m_despawnGuids.
DamageTaken()
void CreatureEventAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellEntry const *) override virtual
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
Parameters
pDealer Unit* who will deal Damage to the creature
uiDamage Amount of Damage that will be dealt, can be changed here
Reimplemented from CreatureAI.
Definition at line 1875 of file CreatureEventAI.cpp.
References AI_EVENT_CRITICAL_HEALTH, AI_EVENT_LOST_HEALTH, AI_EVENT_LOST_SOME_HEALTH, AIEVENT_DEFAULT_THROW_RADIUS, CreatureAI::DamageTaken(), Unit::GetHealth(), Unit::GetMaxHealth(), HEALTH_STEPS, CreatureAI::m_creature, m_throwAIEventMask, m_throwAIEventStep, and UnitAI::SendAIEventAround().
EnterCombat()
void CreatureEventAI::EnterCombat (Unit *) override virtual
Called for reaction at enter to combat if not in combat yet.
Parameters
enemy Unit* of whom the Creature enters combat with, can be nullptr
Reimplemented from CreatureAI.
Definition at line 1626 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), CreatureAI::EnterCombat(), EVENT_T_AGGRO, EVENT_T_FRIENDLY_HP, EVENT_T_FRIENDLY_IS_CC, EVENT_T_FRIENDLY_MISSING_BUFF, EVENT_T_SELECT_ATTACKING_TARGET, EVENT_T_TIMER_IN_COMBAT, EVENT_UPDATE_TIME, IncreaseDepthIfNecessary(), CreatureAI::m_creature, m_CreatureEventAIList, m_EventDiff, m_EventUpdateTime, and ProcessEvents().
EnterEvadeMode()
void CreatureEventAI::EnterEvadeMode () override virtual
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
Reimplemented from UnitAI.
Definition at line 1504 of file CreatureEventAI.cpp.
References AGGREGATION_EVADE, CheckAndReadyEventForExecution(), UnitAI::DespawnGuids(), UnitAI::EnterEvadeMode(), EVENT_T_EVADE, IncreaseDepthIfNecessary(), m_CreatureEventAIList, m_despawnAggregationMask, m_despawnGuids, and ProcessEvents().
Referenced by ProcessAction().
GetAIInformation()
void CreatureEventAI::GetAIInformation (ChatHandler &) override virtual
== Information about AI ========================
This funcion is used to display information about the AI. It is called when the .npc aiinfo command is used. Use this for on-the-fly debugging
Parameters
reader is a ChatHandler to send messages to.
Reimplemented from UnitAI.
Definition at line 65 of file CreatureEventAI.cpp.
References ACTION_T_NONE, UnitAI::GetCombatScriptStatus(), ChatHandler::GetOnOffStr(), Unit::hasUnitState(), LANG_NPC_EVENTAI_COMBAT, LANG_NPC_EVENTAI_MOVE, LANG_NPC_EVENTAI_PHASE, LOG_FILTER_EVENT_AI_DEV, CreatureAI::m_creature, m_CreatureEventAIList, UnitAI::m_currentRangedMode, UnitAI::m_meleeEnabled, m_Phase, ChatHandler::PSendSysMessage(), sLog, and UNIT_STAT_NO_COMBAT_MOVEMENT.
GetAIName()
std::string CreatureEventAI::GetAIName () inline override protected virtual
Reimplemented from UnitAI.
Definition at line 909 of file CreatureEventAI.h.
Referenced by CheckEvent(), and ProcessAction().
GetDefaultMovement()
MovementGeneratorType CreatureEventAI::GetDefaultMovement () inline
Definition at line 907 of file CreatureEventAI.h.
References m_defaultMovement.
Referenced by GuardianAI::CombatStop(), and GuardianAI::JustRespawned().
GetRandActionParam() [1/2]
int32 CreatureEventAI::GetRandActionParam (uint32 rnd, int32 param1, int32 param2, int32 param3) const inline
Definition at line 1733 of file CreatureEventAI.cpp.
GetRandActionParam() [2/2]
uint32 CreatureEventAI::GetRandActionParam (uint32 rnd, uint32 param1, uint32 param2, uint32 param3) const inline
Definition at line 1722 of file CreatureEventAI.cpp.
Referenced by ProcessAction().
GetTargetByType()
Unit * CreatureEventAI::GetTargetByType (uint32 target, Unit * actionInvoker, Unit * AIEventSender, Unit * eventTarget, bool & isError, uint32 forSpellId = 0, uint32 selectFlags = 0) const inline
If the bool& param is true, an error should be reported.
Definition at line 1744 of file CreatureEventAI.cpp.
References ATTACKING_TARGET_BOTTOMAGGRO, ATTACKING_TARGET_FARTHEST_AWAY, ATTACKING_TARGET_NEAREST_BY, ATTACKING_TARGET_RANDOM, ATTACKING_TARGET_TOPAGGRO, Unit::GetBeneficiary(), Creature::GetLootRecipient(), Creature::GetOriginalLootRecipient(), Unit::GetSpawner(), Unit::GetVictim(), Creature::HasLootRecipient(), CreatureAI::m_creature, SELECT_FLAG_NOT_IN_MELEE_RANGE, SELECT_FLAG_PLAYER, SELECT_FLAG_POWER_MANA, SELECT_FLAG_USE_EFFECT_RADIUS, Unit::SelectAttackingTarget(), TARGET_T_ACTION_INVOKER, TARGET_T_ACTION_INVOKER_OWNER, TARGET_T_EVENT_SENDER, TARGET_T_EVENT_SPECIFIC, TARGET_T_HOSTILE, TARGET_T_HOSTILE_FARTHEST_AWAY, TARGET_T_HOSTILE_LAST_AGGRO, TARGET_T_HOSTILE_RANDOM, TARGET_T_HOSTILE_RANDOM_MANA, TARGET_T_HOSTILE_RANDOM_NOT_TOP, TARGET_T_HOSTILE_RANDOM_NOT_TOP_PLAYER, TARGET_T_HOSTILE_RANDOM_PLAYER, TARGET_T_HOSTILE_SECOND_AGGRO, TARGET_T_NEAREST_AOE_TARGET, TARGET_T_NONE, TARGET_T_PLAYER_INVOKER, TARGET_T_PLAYER_TAPPED, TARGET_T_SELF, and TARGET_T_SPAWNER.
Referenced by ProcessAction().
HealedBy()
void CreatureEventAI::HealedBy (Unit * , uint32 &) override virtual
Called at any Heal received from any Unit.
Parameters
pHealer Unit* which deals the heal
uiHealedAmount Amount of healing received
Reimplemented from UnitAI.
Definition at line 1918 of file CreatureEventAI.cpp.
References AI_EVENT_GOT_FULL_HEALTH, AIEVENT_DEFAULT_THROW_RADIUS, Unit::GetHealth(), Unit::GetMaxHealth(), CreatureAI::m_creature, m_throwAIEventMask, m_throwAIEventStep, and UnitAI::SendAIEventAround().
IncreaseDepthIfNecessary()
void CreatureEventAI::IncreaseDepthIfNecessary () inline
Definition at line 897 of file CreatureEventAI.h.
References m_creatureEventAITempList, and m_depth.
Referenced by EnterCombat(), GuardianAI::EnterEvadeMode(), TotemAI::EnterEvadeMode(), EnterEvadeMode(), JustDied(), JustPreventedDeath(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), OnSpellCast(), ReceiveAIEvent(), ReceiveEmote(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), SummonedCreatureJustDied(), and UpdateEventTimers().
InitAI()
void CreatureEventAI::InitAI ()
Definition at line 109 of file CreatureEventAI.cpp.
References ACTION_T_CAST, UnitAI::AddDistanceSpell(), UnitAI::AddMainSpell(), CAST_DISTANCE_YOURSELF, CAST_MAIN_SPELL, EFLAG_DEBUG_ONLY, EFLAG_DIFFICULTY_ALL, EVENT_T_OOC_LOS, MapDataContainer::GetCreatureEventEntryAIMap(), MapDataContainer::GetCreatureEventGuidAIMap(), Object::GetDbGuid(), Map::GetDifficulty(), Object::GetEntry(), WorldObject::GetMap(), Map::GetMapDataContainer(), WorldObject::GetMapId(), Map::GetSpawnMode(), Map::IsDungeon(), IsEventFlagsFitForNormalMap(), CreatureAI::m_creature, m_CreatureEventAIList, m_HasOOCLoSEvent, MAX_ACTIONS, and sLog.
Referenced by JustRespawned().
IsRepeatableEvent()
bool CreatureEventAI::IsRepeatableEvent (EventAI_Type type) const protected
Definition at line 234 of file CreatureEventAI.cpp.
References EVENT_T_AGGRO, EVENT_T_DEATH, EVENT_T_EVADE, EVENT_T_REACHED_HOME, and EVENT_T_SPAWNED.
Referenced by ResetEvent().
IsTimerBasedEvent()
bool CreatureEventAI::IsTimerBasedEvent (EventAI_Type type) const protected
Definition at line 249 of file CreatureEventAI.cpp.
References EVENT_T_AURA, EVENT_T_ENERGY, EVENT_T_FACING_TARGET, EVENT_T_FRIENDLY_HP, EVENT_T_FRIENDLY_IS_CC, EVENT_T_FRIENDLY_MISSING_BUFF, EVENT_T_HP, EVENT_T_KILL, EVENT_T_MANA, EVENT_T_MISSING_AURA, EVENT_T_OOC_LOS, EVENT_T_RANGE, EVENT_T_SELECT_ATTACKING_TARGET, EVENT_T_SPELLHIT, EVENT_T_SPELLHIT_TARGET, EVENT_T_SUMMONED_JUST_DESPAWN, EVENT_T_SUMMONED_JUST_DIED, EVENT_T_SUMMONED_UNIT, EVENT_T_TARGET_AURA, EVENT_T_TARGET_CASTING, EVENT_T_TARGET_HP, EVENT_T_TARGET_MANA, EVENT_T_TARGET_MISSING_AURA, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, and EVENT_T_TIMER_OOC.
Referenced by ResetEvent().
IsTimerExecutedEvent()
bool CreatureEventAI::IsTimerExecutedEvent (EventAI_Type type) const protected
Definition at line 205 of file CreatureEventAI.cpp.
References EVENT_T_AURA, EVENT_T_ENERGY, EVENT_T_FACING_TARGET, EVENT_T_FRIENDLY_HP, EVENT_T_FRIENDLY_IS_CC, EVENT_T_FRIENDLY_MISSING_BUFF, EVENT_T_HP, EVENT_T_MANA, EVENT_T_MISSING_AURA, EVENT_T_RANGE, EVENT_T_SELECT_ATTACKING_TARGET, EVENT_T_TARGET_AURA, EVENT_T_TARGET_CASTING, EVENT_T_TARGET_HP, EVENT_T_TARGET_MANA, EVENT_T_TARGET_MISSING_AURA, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, and EVENT_T_TIMER_OOC.
Referenced by CheckEvent(), and UpdateEventTimers().
JustDied()
void CreatureEventAI::JustDied (Unit *) override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from UnitAI.
Reimplemented in SentryTotemAI.
Definition at line 1521 of file CreatureEventAI.cpp.
References AGGREGATION_DEATH, AI_EVENT_JUST_DIED, AIEVENT_DEFAULT_THROW_RADIUS, CheckAndReadyEventForExecution(), UnitAI::DespawnGuids(), EVENT_T_DEATH, IncreaseDepthIfNecessary(), UnitAI::JustDied(), m_CreatureEventAIList, m_despawnAggregationMask, m_despawnGuids, m_Phase, m_throwAIEventMask, ProcessEvents(), Reset(), and UnitAI::SendAIEventAround().
Referenced by GuardianAI::JustDied(), and SentryTotemAI::JustDied().
JustPreventedDeath()
void CreatureEventAI::JustPreventedDeath (Unit * attacker) virtual
Reimplemented from CreatureAI.
Definition at line 1907 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_DEATH_PREVENTED, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
JustReachedHome()
void CreatureEventAI::JustReachedHome () override virtual
Called at reaching home after MoveTargetedHome.
Reimplemented from UnitAI.
Definition at line 1491 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_REACHED_HOME, IncreaseDepthIfNecessary(), m_CreatureEventAIList, ProcessEvents(), and Reset().
JustRespawned()
void CreatureEventAI::JustRespawned () override virtual
Called when creature is respawned (for reseting variables)
Reimplemented from UnitAI.
Definition at line 1415 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SPAWNED, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, EVENT_T_TIMER_OOC, EVENT_UPDATE_TIME, IncreaseDepthIfNecessary(), InitAI(), Creature::IsNoAggroOnSight(), UnitAI::JustRespawned(), CreatureAI::m_creature, m_CreatureEventAIList, m_EventDiff, m_EventUpdateTime, m_LastSpellMaxRange, m_throwAIEventStep, ProcessEvents(), REACT_AGGRESSIVE, REACT_DEFENSIVE, UnitAI::SetReactState(), and SpawnedEventConditionsCheck().
Referenced by GuardianAI::JustRespawned().
JustSummoned()
void CreatureEventAI::JustSummoned (Creature *) override virtual
Called when the creature summon successfully other creature.
Parameters
pSummoned Creature that got summoned
Reimplemented from UnitAI.
Definition at line 1556 of file CreatureEventAI.cpp.
References AGGREGATION_ENABLED, CheckAndReadyEventForExecution(), EVENT_T_SUMMONED_UNIT, Object::GetEntry(), Object::GetObjectGuid(), IncreaseDepthIfNecessary(), m_CreatureEventAIList, m_despawnAggregationMask, m_despawnGuids, m_entriesForDespawn, and ProcessEvents().
KilledUnit()
void CreatureEventAI::KilledUnit (Unit *) override virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented from UnitAI.
Definition at line 1545 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_KILL, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
MoveInLineOfSight()
void CreatureEventAI::MoveInLineOfSight (Unit * who) override virtual
== Reactions At =================================
Called if IsVisible(Unit* pWho) is true at each (relative) override pWho move, reaction at visibility zone enter Note: The Unit* pWho can be out of Line of Sight, usually this is only visibiliy (by state) and range dependendend Note: This function is not called for creatures who are in evade mode
Parameters
pWho Unit* who moved in the visibility range and is visisble
Reimplemented from UnitAI.
Definition at line 1663 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_OOC_LOS, Object::GetTypeId(), Unit::GetVictim(), IncreaseDepthIfNecessary(), Unit::IsEnemy(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), CreatureAI::m_creature, m_CreatureEventAIList, m_HasOOCLoSEvent, UnitAI::MoveInLineOfSight(), ProcessEvents(), and TYPEID_PLAYER.
OnSpellCast()
void CreatureEventAI::OnSpellCast (SpellEntry const * spellInfo, Unit * target) override virtual
Reimplemented from UnitAI.
Definition at line 1614 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SPELL_CAST, SpellEntry::Id, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
Permissible()
int CreatureEventAI::Permissible (const Creature * creature) static
Definition at line 51 of file CreatureEventAI.cpp.
References Creature::GetAIName(), Unit::IsNeutralToAll(), Creature::IsNoAggroOnSight(), PERMIT_BASE_NO, PERMIT_BASE_PROACTIVE, PERMIT_BASE_REACTIVE, and PERMIT_BASE_SPECIAL.
ProcessAction()
bool CreatureEventAI::ProcessAction (CreatureEventAI_Action const & action, uint32 rnd, uint32 eventId, Unit * actionInvoker, Unit * AIEventSender, Unit * eventTarget) virtual
Definition at line 698 of file CreatureEventAI.cpp.
References ACTION_T_ATTACK_START, ACTION_T_AUTO_ATTACK, ACTION_T_CALL_FOR_HELP, ACTION_T_CAST, ACTION_T_CAST_EVENT, ACTION_T_CAST_EVENT_ALL, ACTION_T_CHANCED_TEXT, ACTION_T_CHANGE_MOVEMENT, ACTION_T_COMBAT_MOVEMENT, ACTION_T_DESPAWN_GUARDIANS, ACTION_T_DIE, ACTION_T_EMOTE, ACTION_T_EVADE, ACTION_T_FLEE_FOR_ASSIST, ACTION_T_FORCE_DESPAWN, ACTION_T_INC_PHASE, ACTION_T_INTERRUPT_SPELL, ACTION_T_KILLED_MONSTER, ACTION_T_MORPH_TO_ENTRY_OR_MODEL, ACTION_T_MOUNT_TO_ENTRY_OR_MODEL, ACTION_T_NONE, ACTION_T_PAUSE_WAYPOINTS, ACTION_T_QUEST_EVENT, ACTION_T_QUEST_EVENT_ALL, ACTION_T_RANDOM_EMOTE, ACTION_T_RANDOM_PHASE, ACTION_T_RANDOM_PHASE_RANGE, ACTION_T_RANDOM_SOUND, ACTION_T_RANGED_MOVEMENT, ACTION_T_REMOVE_UNIT_FLAG, ACTION_T_REMOVEAURASFROMSPELL, ACTION_T_SET_DEATH_PREVENTION, ACTION_T_SET_DESPAWN_AGGREGATION, ACTION_T_SET_FACING, ACTION_T_SET_FACTION, ACTION_T_SET_FOLLOW_MOVEMENT, ACTION_T_SET_IMMOBILIZED_STATE, ACTION_T_SET_IMMUNITY_SET, ACTION_T_SET_INST_DATA, ACTION_T_SET_INST_DATA64, ACTION_T_SET_PHASE, ACTION_T_SET_RANGED_MODE, ACTION_T_SET_REACT_STATE, ACTION_T_SET_SHEATH, ACTION_T_SET_SPELL_SET, ACTION_T_SET_STAND_STATE, ACTION_T_SET_THROW_MASK, ACTION_T_SET_UNIT_FIELD, ACTION_T_SET_UNIT_FLAG, ACTION_T_SET_WALK, ACTION_T_SOUND, ACTION_T_SPAWN, ACTION_T_START_RELAY_SCRIPT, ACTION_T_SUMMON_ID, ACTION_T_TEXT, ACTION_T_TEXT_NEW, ACTION_T_THREAT_ALL_PCT, ACTION_T_THREAT_SINGLE, ACTION_T_THROW_AI_EVENT, ACTION_T_UPDATE_TEMPLATE, ACTION_T_ZONE_COMBAT_PULSE, ThreatManager::addThreat(), AGGREGATION_ENABLED, Creature::AI(), Player::AreaExploredOrEventHappens(), UnitAI::AttackClosestEnemy(), UnitAI::AttackStart(), CreatureAI::AttackStart(), CreatureEventAI_Action::attackStart, CreatureEventAI_Action::auto_attack, CreatureEventAI_Action::call_for_help, CreatureEventAI_Action::cast, CAST_AURA_NOT_PRESENT, CAST_DISTANCE_YOURSELF, CreatureEventAI_Action::cast_event, CreatureEventAI_Action::cast_event_all, CAST_FORCE_CAST, CAST_FORCE_TARGET_SELF, CAST_MAIN_SPELL, CAST_OK, CAST_PLAYER_ONLY, CAST_TARGET_CASTING, CAST_TRIGGERED, CreatureEventAI_Action::chanced_text, CHANGE_MOVEMENT_FLAG_AS_DEFAULT, CHANGE_MOVEMENT_FLAG_WAYPOINT_PATH, CreatureEventAI_Action::changeMovement, CHASE_MOTION_TYPE, Creature::ChooseDisplayId(), MotionMaster::Clear(), Creature::ClearTemporaryFaction(), CreatureEventAI_Action::combat_movement, Unit::CombatStopWithPets(), CreatureEventAI_Action::deathPrevention, DEBUG_FILTER_LOG, Unit::DeMorph(), CreatureEventAI_Action::despawnAggregation, CreatureEventAI_Action::despawnGuardians, CreatureAI::DoCallForHelp(), UnitAI::DoCastSpellIfCan(), DoDisplayText(), UnitAI::DoFlee(), CreatureEventAI_Action::emote, EnterEvadeMode(), CreatureEventAI_Action::evade, Unit::FindGuardianWithEntry(), CreatureEventAI_Action::followMovement, CreatureEventAI_Action::forced_despawn, Creature::ForcedDespawn(), GetAIName(), Unit::GetBeneficiaryPlayer(), ObjectMgr::GetCreatureTemplate(), MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Object::GetGuidStr(), WorldObject::GetInstanceData(), Creature::GetLootRecipient(), WorldObject::GetMap(), Unit::GetMotionMaster(), Object::GetObjectGuid(), Unit::GetOwner(), Map::GetPlayer(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetRandActionParam(), ObjectGuid::GetRawValue(), Creature::GetRespawnCoord(), GetTargetByType(), ThreatManager::getThreatList(), Unit::getThreatManager(), Object::GetTypeId(), Unit::GetVictim(), Unit::HandleEmote(), Unit::hasUnitState(), IDLE_MOTION_TYPE, CreatureEventAI_Action::immobilizedState, CreatureEventAI_Action::immunitySet, CreatureEventAI_Action::interruptSpell, Unit::InterruptSpell(), Unit::IsDead(), IsIgnoreLosSpellCast(), Unit::IsInCombat(), Unit::IsNonMeleeSpellCasted(), CreatureEventAI_Action::killed_monster, LINEAR_WP_MOTION_TYPE, LOG_FILTER_EVENT_AI_DEV, SQLStorage::LookupEntry(), UnitAI::m_attackAngle, UnitAI::m_attackDistance, UnitAI::m_chaseRun, CreatureAI::m_creature, m_defaultMovement, m_despawnAggregationMask, m_despawnGuids, m_entriesForDespawn, UnitAI::m_mainSpellInfo, m_Phase, M_PI_F, UnitAI::m_reactState, m_throwAIEventMask, MAX_PHASE, ThreatManager::modifyAllThreatPercent(), ThreatManager::modifyThreatPercent(), CreatureEventAI_Action::morph, CreatureEventAI_Action::mount, Unit::Mount(), MotionMaster::MoveChase(), MotionMaster::MoveIdle(), MotionMaster::MoveLinearWP(), MotionMaster::MovePath(), MotionMaster::MoveRandomAroundPoint(), MotionMaster::MoveWaypoint(), OBJECT_END, CreatureEventAI_Summon::orientation, PATH_FROM_WAYPOINT_PATH, PATH_MOTION_TYPE, PATH_NO_PATH, CreatureEventAI_Action::pauseWaypoint, MotionMaster::PauseWaypoints(), PET_SAVE_AS_DELETED, WorldObject::PlayDirectSound(), CreatureEventAI_Summon::position_x, CreatureEventAI_Summon::position_y, CreatureEventAI_Summon::position_z, CreatureEventAI_Action::quest_event, CreatureEventAI_Action::quest_event_all, CreatureEventAI_Action::random_emote, RANDOM_MOTION_TYPE, CreatureEventAI_Action::random_phase, CreatureEventAI_Action::random_phase_range, CreatureEventAI_Action::random_sound, CreatureEventAI_Action::ranged_movement, CreatureEventAI_Action::rangedMode, CreatureEventAI_Action::relayScript, CreatureEventAI_Action::remove_aura, Unit::RemoveGuardian(), Unit::RemoveGuardians(), Player::RewardPlayerAndGroupAtEventExplored(), RUN_CHASE, RUN_DEFAULT, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), SELECT_FLAG_CASTING, SELECT_FLAG_IN_LOS, SELECT_FLAG_NOT_AURA, SELECT_FLAG_PLAYER, UnitAI::SendAIEventAround(), Unit::SendMeleeAttackStart(), Unit::SendMeleeAttackStop(), CreatureEventAI_Action::set_faction, CreatureEventAI_Action::set_inc_phase, CreatureEventAI_Action::set_inst_data, CreatureEventAI_Action::set_inst_data64, CreatureEventAI_Action::set_phase, CreatureEventAI_Action::set_sheath, CreatureEventAI_Action::set_unit_field, UnitAI::SetAIImmobilizedState(), UnitAI::SetCombatMovement(), InstanceData::SetData(), InstanceData::SetData64(), CreatureAI::SetDeathPrevention(), Unit::SetDisplayId(), CreatureEventAI_Action::setFacing, Unit::SetFacingTo(), Unit::SetFacingToObject(), Creature::SetFactionTemporary(), UnitAI::SetFollowMovement(), Creature::SetInCombatWithZone(), UnitAI::SetMeleeEnabled(), UnitAI::SetRangedMode(), CreatureEventAI_Action::setReactState, Unit::SetSheath(), Creature::SetSpellList(), CreatureEventAI_Action::setStandState, Unit::SetStandState(), CreatureEventAI_Action::setThrowMask, Object::SetUInt32Value(), Creature::SetWalk(), sEventAIMgr, sLog, CreatureEventAI_Action::sound, CreatureEventAI_Summon::SpawnTimeSecs, CreatureEventAI_Action::spellSet, sScriptMgr, sSpellTemplate, Unit::StopMoving(), Unit::Suicide(), CreatureEventAI_Action::summon, CreatureEventAI_Action::summon_id, WorldObject::SummonCreature(), TARGET_T_SELF, TEMPSPAWN_TIMED_OOC_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, CreatureEventAI_Action::text, CreatureEventAI_Action::textNew, CreatureEventAI_Action::threat_all_pct, CreatureEventAI_Action::threat_single, CreatureEventAI_Action::throwEvent, CreatureEventAI_Action::type, TYPE_NONE, TYPEID_PLAYER, UNIT_END, UNIT_FIELD_FLAGS, CreatureEventAI_Action::unit_flag, UNIT_STAT_CAN_NOT_REACT, UNIT_STAT_NO_COMBAT_MOVEMENT, Unit::Unmount(), MotionMaster::UnpauseWaypoints(), CreatureEventAI_Action::update_template, Creature::UpdateEntry(), Creature::UpdateImmunitiesSet(), WALK_CHASE, WALK_DEFAULT, CreatureEventAI_Action::walkSetting, and WAYPOINT_MOTION_TYPE.
Referenced by ProcessEvent().
ProcessEvent()
bool CreatureEventAI::ProcessEvent (CreatureEventAIHolder & holder, Unit * actionInvoker = nullptr, Unit * AIEventSender = nullptr) virtual
Definition at line 631 of file CreatureEventAI.cpp.
References CreatureEventAI_Event::action, ACTION_T_NONE, UnitAI::CanExecuteCombatAction(), EFLAG_COMBAT_ACTION, EFLAG_RANDOM_ACTION, CreatureEventAIHolder::event, CreatureEventAI_Event::event_chance, CreatureEventAI_Event::event_flags, CreatureEventAI_Event::event_id, CreatureEventAIHolder::eventTarget, CreatureEventAIHolder::inProgress, MAX_ACTIONS, ProcessAction(), ResetEvent(), CreatureEventAI_Action::type, and urand().
Referenced by ProcessEvents().
ProcessEvents()
void CreatureEventAI::ProcessEvents (Unit * actionInvoker = nullptr, Unit * AIEventSender = nullptr)
Definition at line 284 of file CreatureEventAI.cpp.
References m_creatureEventAITempList, m_depth, and ProcessEvent().
Referenced by EnterCombat(), GuardianAI::EnterEvadeMode(), TotemAI::EnterEvadeMode(), EnterEvadeMode(), JustDied(), JustPreventedDeath(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), OnSpellCast(), ReceiveAIEvent(), ReceiveEmote(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), SummonedCreatureJustDied(), and UpdateEventTimers().
ReceiveAIEvent()
void CreatureEventAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) override virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented from UnitAI.
Definition at line 1592 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_RECEIVE_AI_EVENT, Object::GetEntry(), IncreaseDepthIfNecessary(), m_CreatureEventAIList, MANGOS_ASSERT, and ProcessEvents().
ReceiveEmote()
void CreatureEventAI::ReceiveEmote (Player * , uint32) override virtual
Called at text emote receive from player.
Parameters
pPlayer Player* who sent the emote
uiEmote ID of the emote the player used with the creature as target
Reimplemented from UnitAI.
Definition at line 1857 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_RECEIVE_EMOTE, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
Reset()
void CreatureEventAI::Reset () override virtual
Reimplemented from CreatureAI.
Definition at line 1454 of file CreatureEventAI.cpp.
References UnitAI::ClearCombatOnlyRoot(), EVENT_T_AGGRO, EVENT_T_TIMER_GENERIC, EVENT_T_TIMER_IN_COMBAT, EVENT_T_TIMER_OOC, EVENT_UPDATE_TIME, UnitAI::m_attackDistance, UnitAI::m_chaseDistance, CreatureAI::m_creature, m_CreatureEventAIList, UnitAI::m_currentRangedMode, m_EventDiff, m_EventUpdateTime, m_LastSpellMaxRange, UnitAI::m_rangedMode, m_throwAIEventStep, ORDER_NONE, UnitAI::SetAIOrder(), and UnitAI::SetCombatScriptStatus().
Referenced by JustDied(), and JustReachedHome().
ResetEvent()
void CreatureEventAI::ResetEvent (CreatureEventAIHolder & holder)
Definition at line 608 of file CreatureEventAI.cpp.
References EFLAG_REPEATABLE, CreatureEventAIHolder::enabled, CreatureEventAIHolder::event, CreatureEventAI_Event::event_flags, CreatureEventAI_Event::event_type, GetRepeatTimers(), IsRepeatableEvent(), IsTimerBasedEvent(), CreatureAI::m_creature, and CreatureEventAIHolder::UpdateRepeatTimer().
Referenced by ProcessEvent().
SpawnedEventConditionsCheck()
bool CreatureEventAI::SpawnedEventConditionsCheck (CreatureEventAI_Event const & event) const
Definition at line 1931 of file CreatureEventAI.cpp.
References EVENT_T_SPAWNED, CreatureEventAI_Event::event_type, WorldObject::GetMapId(), WorldObject::GetZoneAndAreaId(), CreatureAI::m_creature, CreatureEventAI_Event::spawned, SPAWNED_EVENT_ALWAY, SPAWNED_EVENT_MAP, and SPAWNED_EVENT_ZONE.
Referenced by JustRespawned().
SpellHit()
void CreatureEventAI::SpellHit (Unit * , const SpellEntry *) override virtual
Called when hit by a spell.
Parameters
pCaster Caster who casted the spell
pSpell The spell that hit the creature
Reimplemented from UnitAI.
Definition at line 1696 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SPELLHIT, SpellEntry::Id, IncreaseDepthIfNecessary(), m_CreatureEventAIList, ProcessEvents(), and SpellEntry::SchoolMask.
SpellHitTarget()
void CreatureEventAI::SpellHitTarget (Unit * target, const SpellEntry * spell) override virtual
Reimplemented from UnitAI.
Definition at line 1709 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SPELLHIT_TARGET, SpellEntry::Id, IncreaseDepthIfNecessary(), m_CreatureEventAIList, ProcessEvents(), and SpellEntry::SchoolMask.
SummonedCreatureDespawn()
void CreatureEventAI::SummonedCreatureDespawn (Creature *) override virtual
Called when a summoned creature gets TemporarySummon::UnSummon ed.
Parameters
pSummoned Summoned creature that despawned
Reimplemented from UnitAI.
Definition at line 1581 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SUMMONED_JUST_DESPAWN, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
SummonedCreatureJustDied()
void CreatureEventAI::SummonedCreatureJustDied (Creature *) override virtual
Called when a summoned creature is killed.
Parameters
pSummoned Summoned Creature* that got killed
Reimplemented from UnitAI.
Definition at line 1570 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_SUMMONED_JUST_DIED, IncreaseDepthIfNecessary(), m_CreatureEventAIList, and ProcessEvents().
UpdateEventTimers()
void CreatureEventAI::UpdateEventTimers (const uint32 diff) override virtual
Reimplemented from UnitAI.
Definition at line 1958 of file CreatureEventAI.cpp.
References CheckAndReadyEventForExecution(), EVENT_T_TARGET_NOT_REACHABLE, EVENT_UPDATE_TIME, IncreaseDepthIfNecessary(), IsTimerExecutedEvent(), m_CreatureEventAIList, m_EventDiff, m_EventUpdateTime, m_Phase, and ProcessEvents().
Referenced by TotemAI::UpdateAI().
Field Documentation
m_bEmptyList
bool CreatureEventAI::m_bEmptyList protected
Definition at line 917 of file CreatureEventAI.h.
m_CreatureEventAIList
CreatureEventAIList CreatureEventAI::m_CreatureEventAIList protected
Definition at line 921 of file CreatureEventAI.h.
Referenced by EnterCombat(), GuardianAI::EnterEvadeMode(), TotemAI::EnterEvadeMode(), EnterEvadeMode(), GetAIInformation(), InitAI(), JustDied(), JustPreventedDeath(), JustReachedHome(), JustRespawned(), JustSummoned(), KilledUnit(), MoveInLineOfSight(), OnSpellCast(), ReceiveAIEvent(), ReceiveEmote(), Reset(), SpellHit(), SpellHitTarget(), SummonedCreatureDespawn(), SummonedCreatureJustDied(), UpdateEventTimers(), and ~CreatureEventAI().
m_creatureEventAITempList
std::vector<std::vector<std::reference_wrapper<CreatureEventAIHolder> > > CreatureEventAI::m_creatureEventAITempList protected
Definition at line 922 of file CreatureEventAI.h.
Referenced by CheckAndReadyEventForExecution(), IncreaseDepthIfNecessary(), and ProcessEvents().
m_defaultMovement
MovementGeneratorType CreatureEventAI::m_defaultMovement protected
Definition at line 939 of file CreatureEventAI.h.
Referenced by GetDefaultMovement(), GuardianAI::GuardianAI(), and ProcessAction().
m_depth
uint32 CreatureEventAI::m_depth protected
Definition at line 923 of file CreatureEventAI.h.
Referenced by CheckAndReadyEventForExecution(), IncreaseDepthIfNecessary(), and ProcessEvents().
m_despawnAggregationMask
uint32 CreatureEventAI::m_despawnAggregationMask protected
Definition at line 935 of file CreatureEventAI.h.
Referenced by CorpseRemoved(), EnterEvadeMode(), JustDied(), JustSummoned(), and ProcessAction().
m_despawnGuids
GuidVector CreatureEventAI::m_despawnGuids protected
Definition at line 937 of file CreatureEventAI.h.
Referenced by CorpseRemoved(), EnterEvadeMode(), JustDied(), JustSummoned(), and ProcessAction().
m_entriesForDespawn
std::set<uint32> CreatureEventAI::m_entriesForDespawn protected
Definition at line 936 of file CreatureEventAI.h.
Referenced by JustSummoned(), and ProcessAction().
m_EventDiff
uint32 CreatureEventAI::m_EventDiff protected
Definition at line 916 of file CreatureEventAI.h.
Referenced by EnterCombat(), JustRespawned(), Reset(), and UpdateEventTimers().
m_EventUpdateTime
uint32 CreatureEventAI::m_EventUpdateTime protected
Definition at line 915 of file CreatureEventAI.h.
Referenced by EnterCombat(), JustRespawned(), Reset(), and UpdateEventTimers().
m_HasOOCLoSEvent
bool CreatureEventAI::m_HasOOCLoSEvent protected
Definition at line 926 of file CreatureEventAI.h.
Referenced by InitAI(), and MoveInLineOfSight().
m_InvinceabilityHpLevel
uint32 CreatureEventAI::m_InvinceabilityHpLevel protected
Definition at line 927 of file CreatureEventAI.h.
m_LastSpellMaxRange
float CreatureEventAI::m_LastSpellMaxRange protected
Definition at line 933 of file CreatureEventAI.h.
Referenced by JustRespawned(), and Reset().
m_Phase
uint8 CreatureEventAI::m_Phase protected
Definition at line 925 of file CreatureEventAI.h.
Referenced by CheckEvent(), GetAIInformation(), JustDied(), ProcessAction(), and UpdateEventTimers().
m_throwAIEventMask
uint32 CreatureEventAI::m_throwAIEventMask protected
Definition at line 929 of file CreatureEventAI.h.
Referenced by DamageTaken(), HealedBy(), JustDied(), and ProcessAction().
m_throwAIEventStep
uint32 CreatureEventAI::m_throwAIEventStep protected
Definition at line 932 of file CreatureEventAI.h.
Referenced by DamageTaken(), HealedBy(), JustRespawned(), and Reset().
The documentation for this class was generated from the following files:
CreatureEventAI.h
CreatureEventAI.cpp