CMaNGOS_WoTLK: MapDataContainer Class Reference
MapDataContainer Class Reference
#include <MapDataContainer.h>
Public Member Functions
MapDataContainer ()
void SetCreatureSpellListContainer (std::shared_ptr< CreatureSpellListContainer > container)
CreatureSpellList * GetCreatureSpellList (uint32 Id) const
SpawnGroupEntry * GetSpawnGroup (uint32 Id) const
SpawnGroupEntry * GetSpawnGroupByGuid (uint32 dbGuid, uint32 high) const
std::shared_ptr< SpawnGroupEntryContainer > GetSpawnGroups () const
void SetEventAIContainers (std::shared_ptr< CreatureEventAI_Event_Map > entryContainer, std::shared_ptr< CreatureEventAI_Event_Map > guidContainer, std::shared_ptr< CreatureEventAI_EventComputedData_Map > computedContainer)
std::shared_ptr< CreatureEventAI_Event_Map > GetCreatureEventEntryAIMap () const
std::shared_ptr< CreatureEventAI_Event_Map > GetCreatureEventGuidAIMap () const
std::shared_ptr< CreatureEventAI_EventComputedData_Map > GetEAIComputedDataMap () const
void SetScriptMap (ScriptMapType scriptMapType, std::shared_ptr< ScriptMapMapName > scriptMap)
std::shared_ptr< ScriptMapMapName > GetScriptMap (ScriptMapType scriptMapType)
void SetStringIdMaps (std::shared_ptr< StringIdMap > stringIds, std::shared_ptr< StringIdMapByString > stringIdsByString)
uint32 GetStringId (std::string &stringId) const
void SetUnitConditions (std::shared_ptr< std::map< int32, UnitConditionEntry >> unitConditions)
void SetCombatConditions (std::shared_ptr< std::map< int32, WorldStateExpressionEntry >> worldStateExpressions)
void SetWorldStateExpressions (std::shared_ptr< std::map< int32, CombatConditionEntry >> combatConditions)
std::shared_ptr< std::map< int32, UnitConditionEntry > > GetUnitConditions () const
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > GetWorldStateExpressions () const
std::shared_ptr< std::map< int32, CombatConditionEntry > > GetCombatConditions () const
Private Attributes
std::shared_ptr< CreatureSpellListContainer > m_spellListContainer
std::shared_ptr< SpawnGroupEntryContainer > m_spawnGroupContainer
std::shared_ptr< CreatureEventAI_Event_Map > m_CreatureEventAIEventEntryMap
std::shared_ptr< CreatureEventAI_Event_Map > m_CreatureEventAIEventGuidMap
std::shared_ptr< CreatureEventAI_EventComputedData_Map > m_creatureEventAIComputedDataMap
std::shared_ptr< ScriptMapMapName > m_scriptMaps [SCRIPT_TYPE_MAX]
std::shared_ptr< StringIdMap > m_stringIds
std::shared_ptr< StringIdMapByString > m_stringIdsByString
std::shared_ptr< std::map< int32, UnitConditionEntry > > m_unitConditions
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > m_worldStateExpressions
std::shared_ptr< std::map< int32, CombatConditionEntry > > m_combatConditions
Detailed Description
Definition at line 50 of file MapDataContainer.h.
Constructor & Destructor Documentation
MapDataContainer()
MapDataContainer::MapDataContainer ()
Definition at line 28 of file MapDataContainer.cpp.
References SCRIPT_TYPE_MAX, SetScriptMap(), and sScriptMgr.
Member Function Documentation
GetCombatConditions()
std::shared_ptr< std::map< int32, CombatConditionEntry > > MapDataContainer::GetCombatConditions () const
Definition at line 141 of file MapDataContainer.cpp.
References m_combatConditions.
GetCreatureEventEntryAIMap()
std::shared_ptr< CreatureEventAI_Event_Map > MapDataContainer::GetCreatureEventEntryAIMap () const
Definition at line 82 of file MapDataContainer.cpp.
References m_CreatureEventAIEventEntryMap.
Referenced by CreatureEventAI::InitAI().
GetCreatureEventGuidAIMap()
std::shared_ptr< CreatureEventAI_Event_Map > MapDataContainer::GetCreatureEventGuidAIMap () const
Definition at line 87 of file MapDataContainer.cpp.
References m_CreatureEventAIEventGuidMap.
Referenced by CreatureEventAI::InitAI().
GetCreatureSpellList()
CreatureSpellList * MapDataContainer::GetCreatureSpellList (uint32 Id) const
Definition at line 43 of file MapDataContainer.cpp.
References m_spellListContainer.
Referenced by Creature::SetSpellList().
GetEAIComputedDataMap()
std::shared_ptr< CreatureEventAI_EventComputedData_Map > MapDataContainer::GetEAIComputedDataMap () const
Definition at line 92 of file MapDataContainer.cpp.
References m_creatureEventAIComputedDataMap.
Referenced by CreatureEventAI::CheckEvent().
GetScriptMap()
std::shared_ptr< ScriptMapMapName > MapDataContainer::GetScriptMap (ScriptMapType scriptMapType)
Definition at line 102 of file MapDataContainer.cpp.
References m_scriptMaps.
Referenced by Map::ScriptsStart().
GetSpawnGroup()
SpawnGroupEntry * MapDataContainer::GetSpawnGroup (uint32 Id) const
Definition at line 52 of file MapDataContainer.cpp.
References m_spawnGroupContainer.
Referenced by ScriptAction::GetScriptProcessTargets().
GetSpawnGroupByGuid()
SpawnGroupEntry * MapDataContainer::GetSpawnGroupByGuid (uint32 dbGuid, uint32 high) const
Definition at line 61 of file MapDataContainer.cpp.
References m_spawnGroupContainer.
Referenced by ChatHandler::HandleGameObjectNearCommand(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleRespawnCommand(), Creature::LoadFromDB(), GameObject::LoadFromDB(), and MaNGOS::RespawnDo::operator()().
GetSpawnGroups()
std::shared_ptr< SpawnGroupEntryContainer > MapDataContainer::GetSpawnGroups () const
Definition at line 70 of file MapDataContainer.cpp.
References m_spawnGroupContainer.
Referenced by SpawnManager::Initialize().
GetStringId()
uint32 MapDataContainer::GetStringId (std::string & stringId) const
Definition at line 107 of file MapDataContainer.cpp.
References m_stringIdsByString.
Referenced by WorldObject::AddStringId(), and WorldObject::RemoveStringId().
GetUnitConditions()
std::shared_ptr< std::map< int32, UnitConditionEntry > > MapDataContainer::GetUnitConditions () const
Definition at line 131 of file MapDataContainer.cpp.
References m_unitConditions.
Referenced by UnitConditionMgr::Meets().
GetWorldStateExpressions()
std::shared_ptr< std::map< int32, WorldStateExpressionEntry > > MapDataContainer::GetWorldStateExpressions () const
Definition at line 136 of file MapDataContainer.cpp.
References m_worldStateExpressions.
Referenced by WorldStateExpressionMgr::Meets().
SetCombatConditions()
void MapDataContainer::SetCombatConditions (std::shared_ptr< std::map< int32, WorldStateExpressionEntry >> worldStateExpressions)
Definition at line 121 of file MapDataContainer.cpp.
References m_worldStateExpressions.
SetCreatureSpellListContainer()
void MapDataContainer::SetCreatureSpellListContainer (std::shared_ptr< CreatureSpellListContainer > container)
Definition at line 38 of file MapDataContainer.cpp.
References m_spellListContainer.
SetEventAIContainers()
void MapDataContainer::SetEventAIContainers (std::shared_ptr< CreatureEventAI_Event_Map > entryContainer, std::shared_ptr< CreatureEventAI_Event_Map > guidContainer, std::shared_ptr< CreatureEventAI_EventComputedData_Map > computedContainer)
Definition at line 75 of file MapDataContainer.cpp.
References m_creatureEventAIComputedDataMap, m_CreatureEventAIEventEntryMap, and m_CreatureEventAIEventGuidMap.
SetScriptMap()
void MapDataContainer::SetScriptMap (ScriptMapType scriptMapType, std::shared_ptr< ScriptMapMapName > scriptMap)
Definition at line 97 of file MapDataContainer.cpp.
References m_scriptMaps.
Referenced by MapDataContainer().
SetStringIdMaps()
void MapDataContainer::SetStringIdMaps (std::shared_ptr< StringIdMap > stringIds, std::shared_ptr< StringIdMapByString > stringIdsByString)
Definition at line 146 of file MapDataContainer.cpp.
References m_stringIds, and m_stringIdsByString.
SetUnitConditions()
void MapDataContainer::SetUnitConditions (std::shared_ptr< std::map< int32, UnitConditionEntry >> unitConditions)
Definition at line 116 of file MapDataContainer.cpp.
References m_unitConditions.
SetWorldStateExpressions()
void MapDataContainer::SetWorldStateExpressions (std::shared_ptr< std::map< int32, CombatConditionEntry >> combatConditions)
Definition at line 126 of file MapDataContainer.cpp.
References m_combatConditions.
Field Documentation
m_combatConditions
std::shared_ptr<std::map<int32, CombatConditionEntry> > MapDataContainer::m_combatConditions private
Definition at line 93 of file MapDataContainer.h.
Referenced by GetCombatConditions(), and SetWorldStateExpressions().
m_creatureEventAIComputedDataMap
std::shared_ptr<CreatureEventAI_EventComputedData_Map> MapDataContainer::m_creatureEventAIComputedDataMap private
Definition at line 83 of file MapDataContainer.h.
Referenced by GetEAIComputedDataMap(), and SetEventAIContainers().
m_CreatureEventAIEventEntryMap
std::shared_ptr<CreatureEventAI_Event_Map> MapDataContainer::m_CreatureEventAIEventEntryMap private
Definition at line 81 of file MapDataContainer.h.
Referenced by GetCreatureEventEntryAIMap(), and SetEventAIContainers().
m_CreatureEventAIEventGuidMap
std::shared_ptr<CreatureEventAI_Event_Map> MapDataContainer::m_CreatureEventAIEventGuidMap private
Definition at line 82 of file MapDataContainer.h.
Referenced by GetCreatureEventGuidAIMap(), and SetEventAIContainers().
m_scriptMaps
std::shared_ptr<ScriptMapMapName> MapDataContainer::m_scriptMaps[SCRIPT_TYPE_MAX] private
Definition at line 85 of file MapDataContainer.h.
Referenced by GetScriptMap(), and SetScriptMap().
m_spawnGroupContainer
std::shared_ptr<SpawnGroupEntryContainer> MapDataContainer::m_spawnGroupContainer private
Definition at line 79 of file MapDataContainer.h.
Referenced by GetSpawnGroup(), GetSpawnGroupByGuid(), and GetSpawnGroups().
m_spellListContainer
std::shared_ptr<CreatureSpellListContainer> MapDataContainer::m_spellListContainer private
Definition at line 78 of file MapDataContainer.h.
Referenced by GetCreatureSpellList(), and SetCreatureSpellListContainer().
m_stringIds
std::shared_ptr<StringIdMap> MapDataContainer::m_stringIds private
Definition at line 88 of file MapDataContainer.h.
Referenced by SetStringIdMaps().
m_stringIdsByString
std::shared_ptr<StringIdMapByString> MapDataContainer::m_stringIdsByString private
Definition at line 89 of file MapDataContainer.h.
Referenced by GetStringId(), and SetStringIdMaps().
m_unitConditions
std::shared_ptr<std::map<int32, UnitConditionEntry> > MapDataContainer::m_unitConditions private
Definition at line 91 of file MapDataContainer.h.
Referenced by GetUnitConditions(), and SetUnitConditions().
m_worldStateExpressions
std::shared_ptr<std::map<int32, WorldStateExpressionEntry> > MapDataContainer::m_worldStateExpressions private
Definition at line 92 of file MapDataContainer.h.
Referenced by GetWorldStateExpressions(), and SetCombatConditions().
The documentation for this class was generated from the following files:
MapDataContainer.h
MapDataContainer.cpp