CMaNGOS_WoTLK: instance_sunwell_plateau Class Reference
instance_sunwell_plateau Class Reference
#include <sunwell_plateau.h>
Public Member Functions
instance_sunwell_plateau (Map *pMap)
~instance_sunwell_plateau ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *pPlayer) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureEnterCombat (Creature *creature) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnPlayerDeath (Player *player)
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
void Update (const uint32 diff) override
ObjectGuid SelectFelmystFlightTrigger (bool bLeftSide, uint8 uiIndex)
void AddToSpectralRealm (ObjectGuid playerGuid)
void RemoveFromSpectralRealm (ObjectGuid playerGuid)
void DoEjectSpectralPlayers ()
const char * Save () const override
void Load (const char *chrIn) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
bool IsBrutallusIntroStarted () const
void StartBrutallusIntro ()
void DropFog ()
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Protected Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoSortFlightTriggers ()
void SpawnFelmyst ()
void SpawnGauntlet (bool respawn=false)
void SpawnTwins ()
void SpawnMuru ()
void SpawnKiljaeden ()
void FailKiljaeden ()
void StartImps ()
void StopImps ()
void ResetGauntlet (bool stop=false)
void RespawnGauntlet ()
void ImpYell ()
void StartMiniEvent ()
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_brutallusIntroStarted
bool m_firstEnter
bool m_spawnedGauntlet
bool m_impsStarted
bool m_miniAttackEvent
TimePoint m_gauntletRespawnTime
uint8 m_uiDeceiversKilled
uint32 m_uiSpectralRealmTimer
uint32 m_uiMuruBerserkTimer
uint32 m_uiKiljaedenYellTimer
GuidSet m_spectralRealmPlayers
GuidVector m_vRightFlightTriggersVect
GuidVector m_vLeftFlightTriggersVect
GuidList m_lAllFlightTriggersList
GuidList m_lBackdoorTriggersList
std::vector< uint32 > m_kiljaedenRespawnDbGuids
GuidVector m_muruTrashGuids
GuidVector m_felmystSpawns
GuidVector m_gauntletSpawns
GuidVector m_twinsSpawns
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Detailed Description
Definition at line 151 of file sunwell_plateau.h.
Constructor & Destructor Documentation
instance_sunwell_plateau()
instance_sunwell_plateau::instance_sunwell_plateau (Map * pMap)
Definition at line 47 of file sunwell_plateau.cpp.
References Initialize().
~instance_sunwell_plateau()
instance_sunwell_plateau::~instance_sunwell_plateau () inline
Definition at line 155 of file sunwell_plateau.h.
Member Function Documentation
AddToSpectralRealm()
void instance_sunwell_plateau::AddToSpectralRealm (ObjectGuid playerGuid) inline
Definition at line 176 of file sunwell_plateau.h.
References m_spectralRealmPlayers.
Referenced by boss_sathrovarrAI::ReceiveAIEvent(), and boss_kalecgosAI::ReceiveAIEvent().
DoEjectSpectralPlayers()
void instance_sunwell_plateau::DoEjectSpectralPlayers ()
Definition at line 762 of file sunwell_plateau.cpp.
References Map::GetPlayer(), InstanceData::instance, m_spectralRealmPlayers, and SPELL_SPECTRAL_REALM_AURA.
Referenced by boss_kalecgosAI::DoStartOutro(), boss_kalecgosAI::EnterEvadeMode(), and boss_kalecgos_humanoidAI::JustDied().
DoSortFlightTriggers()
void instance_sunwell_plateau::DoSortFlightTriggers () protected
Definition at line 567 of file sunwell_plateau.cpp.
References Map::GetCreature(), InstanceData::instance, m_lAllFlightTriggersList, m_vLeftFlightTriggersVect, m_vRightFlightTriggersVect, NPC_FELMYST, script_error_log(), and sortByPositionX().
Referenced by SetData().
DropFog()
void instance_sunwell_plateau::DropFog ()
Definition at line 778 of file sunwell_plateau.cpp.
References Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), InstanceData::instance, NPC_WORLD_TRIGGER_LARGE, SPELL_FOG_CORRUPTION, and triggers.
Referenced by boss_felmystAI::HandleBreath(), and SetData().
ExecuteChatCommand()
void instance_sunwell_plateau::ExecuteChatCommand (ChatHandler * handler, char * args) override virtual
Reimplemented from InstanceData.
Definition at line 826 of file sunwell_plateau.cpp.
References ChatHandler::ExtractLiteralArg(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_BRUTALLUS, ResetGauntlet(), SetData(), SpawnFelmyst(), SpawnGauntlet(), SpawnKiljaeden(), SpawnMuru(), SpawnTwins(), SPECIAL, TYPE_BRUTALLUS, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
FailKiljaeden()
void instance_sunwell_plateau::FailKiljaeden () protected
Definition at line 651 of file sunwell_plateau.cpp.
References Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_JUST_DEACTIVATED, GO_ORB_BLUE_FLIGHT_1, GO_ORB_BLUE_FLIGHT_2, GO_ORB_BLUE_FLIGHT_3, GO_ORB_BLUE_FLIGHT_4, InstanceData::instance, m_kiljaedenRespawnDbGuids, m_uiDeceiversKilled, NPC_BLUE_ORB_TARGET, NPC_KALECGOS, NPC_SINISTER_REFLECTION, ScriptedInstance::RespawnDbGuids(), and SPELL_RING_BLUE_FLAME.
Referenced by SetData().
GetData()
uint32 instance_sunwell_plateau::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 442 of file sunwell_plateau.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by AreaTrigger_at_sunwell_plateau(), boss_felmystAI::CorpseRemoved(), boss_kalecgosAI::EnterEvadeMode(), boss_brutallusAI::GetAIInformation(), boss_felmystAI::JustRespawned(), OnCreatureEnterCombat(), OnPlayerDeath(), boss_muruAI::Reset(), RespawnGauntlet(), SetData(), and Update().
ImpYell()
void instance_sunwell_plateau::ImpYell () protected
Definition at line 687 of file sunwell_plateau.cpp.
References DoScriptText(), Map::GetCreature(), GUID_PREFIX, InstanceData::instance, and SAY_GAUNTLET_IMPS.
Referenced by Initialize().
Initialize()
void instance_sunwell_plateau::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 67 of file sunwell_plateau.cpp.
References ACTION_IMP_YELL, ACTION_MURU_DOOR, ACTION_SPAWN_MURU, TimerManager::AddCustomAction(), ScriptedInstance::DoUseOpenableObject(), Unit::GetCombatManager(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_MURU_ENTER_GATE, ImpYell(), DialogueHelper::InitializeDialogueHelper(), CombatManager::IsEvadingHome(), Unit::IsInCombat(), m_auiEncounter, NPC_MURU, and SpawnMuru().
Referenced by instance_sunwell_plateau().
IsBrutallusIntroStarted()
bool instance_sunwell_plateau::IsBrutallusIntroStarted () const inline
Definition at line 186 of file sunwell_plateau.h.
References m_brutallusIntroStarted.
Referenced by boss_brutallusAI::UpdateAI().
IsEncounterInProgress()
bool instance_sunwell_plateau::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 83 of file sunwell_plateau.cpp.
References IN_PROGRESS, and m_auiEncounter.
Referenced by Update().
JustDidDialogueStep()
void instance_sunwell_plateau::JustDidDialogueStep (int32) override protected virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 787 of file sunwell_plateau.cpp.
References aKalecLoc, ScriptedInstance::GetSingleCreatureFromStorage(), NPC_BRUTALLUS, NPC_FELMYST, NPC_FLIGHT_TRIGGER_LEFT, NPC_KALECGOS_MADRIGOSA, Position::o, SpawnGauntlet(), SPELL_OPEN_BACK_DOOR, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, TRIGGERED_NONE, Position::x, Position::y, and Position::z.
Load()
void instance_sunwell_plateau::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 539 of file sunwell_plateau.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_sunwell_plateau::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 127 of file sunwell_plateau.cpp.
References Unit::GetCombatManager(), Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_felmystSpawns, m_gauntletSpawns, m_kiljaedenRespawnDbGuids, m_lAllFlightTriggersList, m_lBackdoorTriggersList, m_muruTrashGuids, ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, m_twinsSpawns, NPC_ALYTHESS, NPC_ANVEENA, NPC_ANVEENA_MARKER, NPC_BERSERKER, NPC_BLUE_ORB_TARGET, NPC_BRUTALLUS, NPC_DARK_FIEND, NPC_DARKNESS, NPC_DEMONIC_VAPOR, NPC_DEMONIC_VAPOR_TRAIL, NPC_ENTROPIUS, NPC_FELMYST, NPC_FLIGHT_TRIGGER_LEFT, NPC_FLIGHT_TRIGGER_RIGHT, NPC_FURY_MAGE, NPC_GAUNTLET_IMP_TRIGGER, NPC_HAND_OF_THE_DECEIVER, NPC_KALECGOS, NPC_KALECGOS_DRAGON, NPC_KALECGOS_HUMAN, NPC_KALECGOS_MADRIGOSA, NPC_KILJAEDEN, NPC_KILJAEDEN_CONTROLLER, NPC_LIADRIN, NPC_MADRIGOSA, NPC_MURU, NPC_MURU_PORTAL_TARGET, NPC_SACROLASH, NPC_SATHROVARR, NPC_SHADOW_IMAGE, NPC_SHADOWSWORD_DEATHBRINGER, NPC_SINGULARITY, NPC_SINISTER_REFLECTION, NPC_UNYELDING_DEAD, NPC_VELEN, NPC_VOID_SENTINEL, NPC_VOID_SPAWN, NPC_VOLATILE_FIEND, NPC_WORLD_TRIGGER, NPC_WORLD_TRIGGER_LARGE, WorldObject::SetActiveObjectState(), Creature::SetCorpseDelay(), and CombatManager::SetLeashingCheck().
OnCreatureDeath()
void instance_sunwell_plateau::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 229 of file sunwell_plateau.cpp.
References aKalegSpawnLoc, Map::GetCurrentClockTime(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_gauntletRespawnTime, m_spawnedGauntlet, m_uiDeceiversKilled, MAX_DECEIVERS, NPC_ANVEENA_MARKER, NPC_HAND_OF_THE_DECEIVER, NPC_KALECGOS, NPC_KILJAEDEN, NPC_KILJAEDEN_CONTROLLER, NPC_SHADOWSWORD_COMMANDER, SpawnTwins(), SPELL_ANVEENA_DRAIN, StopImps(), WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, and TEMPSPAWN_DEAD_DESPAWN.
OnCreatureEnterCombat()
void instance_sunwell_plateau::OnCreatureEnterCombat (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 220 of file sunwell_plateau.cpp.
References GetData(), Object::GetDbGuid(), Object::GetEntry(), GUID_PREFIX, IN_PROGRESS, m_gauntletRespawnTime, NPC_HAND_OF_THE_DECEIVER, SetData(), StartImps(), and TYPE_KILJAEDEN.
OnCreatureEvade()
void instance_sunwell_plateau::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 258 of file sunwell_plateau.cpp.
References FAIL, Creature::ForcedDespawn(), Object::GetDbGuid(), Object::GetEntry(), GUID_PREFIX, m_gauntletRespawnTime, NPC_HAND_OF_THE_DECEIVER, SetData(), and TYPE_KILJAEDEN.
OnCreatureRespawn()
void instance_sunwell_plateau::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 204 of file sunwell_plateau.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_EVENTAI_A, Object::GetEntry(), Creature::IsTemporarySummon(), NPC_SHADOWSWORD_DEATHBRINGER, NPC_VOLATILE_FIEND, NPC_WORLD_TRIGGER_LARGE, REACT_PASSIVE, UnitAI::SendAIEvent(), Creature::SetCanCallForAssistance(), Unit::SetCanEnterCombat(), UnitAI::SetCombatMovement(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_sunwell_plateau::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 273 of file sunwell_plateau.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_BLAZE, GO_BOSS_COLLISION_1, GO_BOSS_COLLISION_2, GO_FIRE_BARRIER, GO_FORCEFIELD, GO_ICE_BARRIER, GO_MURU_ENTER_GATE, GO_MURU_EXIT_GATE, GO_ORB_BLUE_FLIGHT_1, GO_ORB_BLUE_FLIGHT_2, GO_ORB_BLUE_FLIGHT_3, GO_ORB_BLUE_FLIGHT_4, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, m_twinsSpawns, GameObject::SetCooldown(), GameObject::SetGoState(), TYPE_FELMYST, and TYPE_MURU.
OnPlayerDeath()
void instance_sunwell_plateau::OnPlayerDeath (Player * player) virtual
Reimplemented from InstanceData.
Definition at line 267 of file sunwell_plateau.cpp.
References GetData(), IN_PROGRESS, Unit::RemoveAurasDueToSpell(), SPELL_SPECTRAL_REALM_AURA, and TYPE_KALECGOS.
OnPlayerEnter()
void instance_sunwell_plateau::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 94 of file sunwell_plateau.cpp.
References DONE, ScriptedInstance::GetSingleCreatureFromStorage(), m_auiEncounter, m_firstEnter, NPC_ANVEENA, NPC_FELMYST, NPC_MURU, SpawnFelmyst(), SpawnGauntlet(), SpawnKiljaeden(), SpawnMuru(), TYPE_BRUTALLUS, TYPE_EREDAR_TWINS, TYPE_FELMYST, TYPE_KILJAEDEN, and TYPE_MURU.
RemoveFromSpectralRealm()
void instance_sunwell_plateau::RemoveFromSpectralRealm (ObjectGuid playerGuid) inline
Definition at line 177 of file sunwell_plateau.h.
References m_spectralRealmPlayers.
ResetGauntlet()
void instance_sunwell_plateau::ResetGauntlet (bool stop = false) protected
Definition at line 728 of file sunwell_plateau.cpp.
References ScriptedInstance::DespawnGuids(), Map::GetCreature(), Map::GetCurrentClockTime(), GUID_PREFIX, InstanceData::instance, m_gauntletRespawnTime, m_gauntletSpawns, m_impsStarted, m_spawnedGauntlet, and StopImps().
Referenced by ExecuteChatCommand(), and Update().
RespawnGauntlet()
void instance_sunwell_plateau::RespawnGauntlet () protected
Definition at line 743 of file sunwell_plateau.cpp.
References DONE, GetData(), m_gauntletRespawnTime, SpawnGauntlet(), and TYPE_EREDAR_TWINS.
Referenced by Update().
Save()
const char* instance_sunwell_plateau::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 180 of file sunwell_plateau.h.
References m_strInstData.
SelectFelmystFlightTrigger()
ObjectGuid instance_sunwell_plateau::SelectFelmystFlightTrigger (bool bLeftSide, uint8 uiIndex)
Definition at line 751 of file sunwell_plateau.cpp.
References m_vLeftFlightTriggersVect, and m_vRightFlightTriggersVect.
Referenced by boss_felmystAI::HandleBreath(), and boss_felmystAI::HandlePreBreath().
SetData()
void instance_sunwell_plateau::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 306 of file sunwell_plateau.cpp.
References ACTION_MURU_DOOR, ACTION_SPAWN_MURU, SpawnManager::AddCreature(), AI_EVENT_CUSTOM_B, AI_EVENT_CUSTOM_E, ScriptedInstance::BanPlayersIfNoGm(), DB_ENCOUNTER_TWINS, ScriptedInstance::DespawnGuids(), DONE, DoSortFlightTriggers(), ScriptedInstance::DoUseDoorOrButton(), ScriptedInstance::DoUseOpenableObject(), DropFog(), ENCOUNTER_CREDIT_SCRIPT, FAIL, FailKiljaeden(), FORCED_MOVEMENT_WALK, Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetSpawnManager(), GO_BOSS_COLLISION_1, GO_BOSS_COLLISION_2, GO_FORCEFIELD, GO_MURU_ENTER_GATE, GO_MURU_EXIT_GATE, GUID_PREFIX, IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_felmystSpawns, m_muruTrashGuids, m_strInstData, m_twinsSpawns, m_uiMuruBerserkTimer, MINUTE, NPC_ALYTHESS, NPC_ENTROPIUS, NPC_KALECGOS_DRAGON, NPC_KALECGOS_MADRIGOSA, NPC_MURU, NPC_MURU_PORTAL_TARGET, NPC_SACROLASH, NPC_SATHROVARR, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, TimerManager::ResetTimer(), InstanceData::SaveToDB(), SpawnKiljaeden(), SpawnMuru(), SPECIAL, SPELL_TRANSFORM_VISUAL_PERIODIC, DialogueHelper::StartNextDialogueText(), TYPE_BRUTALLUS, TYPE_EREDAR_TWINS, TYPE_FELMYST, TYPE_KALECGOS, TYPE_KILJAEDEN, and TYPE_MURU.
Referenced by boss_kalecgosAI::Aggro(), boss_muruAI::Aggro(), boss_brutallusAI::Aggro(), boss_felmystAI::Aggro(), AreaTrigger_at_sunwell_plateau(), boss_kalecgosAI::DoStartOutro(), boss_felmystAI::EnterEvadeMode(), boss_kalecgosAI::EnterEvadeMode(), boss_kiljaedenAI::EnterEvadeMode(), boss_muruAI::EnterEvadeMode(), boss_entropiusAI::EnterEvadeMode(), ExecuteChatCommand(), boss_brutallusAI::JustDied(), boss_felmystAI::JustDied(), boss_kalecgos_humanoidAI::JustDied(), boss_kiljaedenAI::JustDied(), boss_entropiusAI::JustDied(), boss_brutallusAI::JustReachedHome(), OnCreatureEnterCombat(), and OnCreatureEvade().
ShowChatCommands()
void instance_sunwell_plateau::ShowChatCommands (ChatHandler * handler) override virtual
Reimplemented from InstanceData.
Definition at line 821 of file sunwell_plateau.cpp.
References ChatHandler::SendSysMessage().
SpawnFelmyst()
void instance_sunwell_plateau::SpawnFelmyst () protected
Definition at line 596 of file sunwell_plateau.cpp.
References aMadrigosaLoc, InstanceData::instance, NPC_FELMYST, WorldObject::SummonCreature(), and TEMPSPAWN_MANUAL_DESPAWN.
Referenced by ExecuteChatCommand(), and OnPlayerEnter().
SpawnGauntlet()
void instance_sunwell_plateau::SpawnGauntlet (bool respawn = false) protected
Definition at line 601 of file sunwell_plateau.cpp.
References Map::GetCreature(), GUID_PREFIX, InstanceData::instance, m_impsStarted, m_spawnedGauntlet, Creature::SetCorpseDelay(), Creature::SetNoLoot(), WorldObject::SpawnCreature(), SPELL_CRYSTAL_CHANNEL, and TRIGGERED_NONE.
Referenced by ExecuteChatCommand(), JustDidDialogueStep(), OnPlayerEnter(), and RespawnGauntlet().
SpawnKiljaeden()
void instance_sunwell_plateau::SpawnKiljaeden () protected
Definition at line 645 of file sunwell_plateau.cpp.
References GUID_PREFIX, InstanceData::instance, and WorldObject::SpawnCreature().
Referenced by ExecuteChatCommand(), OnPlayerEnter(), and SetData().
SpawnMuru()
void instance_sunwell_plateau::SpawnMuru () protected
Definition at line 635 of file sunwell_plateau.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), NPC_MURU, REACT_AGGRESSIVE, and VISIBILITY_ON.
Referenced by ExecuteChatCommand(), Initialize(), OnPlayerEnter(), and SetData().
SpawnTwins()
void instance_sunwell_plateau::SpawnTwins () protected
Definition at line 627 of file sunwell_plateau.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), GUID_PREFIX, InstanceData::instance, NPC_SACROLASH, and WorldObject::SpawnCreature().
Referenced by ExecuteChatCommand(), and OnCreatureDeath().
StartBrutallusIntro()
void instance_sunwell_plateau::StartBrutallusIntro () inline
Definition at line 187 of file sunwell_plateau.h.
References m_brutallusIntroStarted.
Referenced by boss_brutallusAI::DoStartIntro().
StartImps()
void instance_sunwell_plateau::StartImps () protected
Definition at line 706 of file sunwell_plateau.cpp.
References ACTION_IMP_YELL, Map::GetCreature(), GUID_PREFIX, InstanceData::instance, m_impsStarted, and TimerManager::ResetTimer().
Referenced by OnCreatureEnterCombat().
StartMiniEvent()
void instance_sunwell_plateau::StartMiniEvent () protected
Definition at line 693 of file sunwell_plateau.cpp.
References FORCED_MOVEMENT_RUN, Map::GetCreature(), GUID_PREFIX, InstanceData::instance, and m_miniAttackEvent.
Referenced by Update().
StopImps()
void instance_sunwell_plateau::StopImps () protected
Definition at line 718 of file sunwell_plateau.cpp.
References Map::GetCreature(), GUID_PREFIX, InstanceData::instance, and m_impsStarted.
Referenced by OnCreatureDeath(), and ResetGauntlet().
Update()
void instance_sunwell_plateau::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 450 of file sunwell_plateau.cpp.
References DialogueHelper::DialogueUpdate(), DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), FAIL, Map::GetCreature(), GetData(), Map::GetPlayers(), ScriptedInstance::GetSingleCreatureFromStorage(), GUID_PREFIX, Object::HasFlag(), IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), IsEncounterInProgress(), Unit::IsFeigningDeathSuccessfully(), Player::IsGameMaster(), WorldObject::IsWithinDist(), m_auiEncounter, m_gauntletRespawnTime, m_impsStarted, m_miniAttackEvent, m_uiKiljaedenYellTimer, m_uiMuruBerserkTimer, MINUTE, NOT_STARTED, NPC_ENTROPIUS, NPC_KILJAEDEN_CONTROLLER, NPC_MURU, ResetGauntlet(), RespawnGauntlet(), SAY_ORDER_1, SAY_ORDER_2, SAY_ORDER_3, SAY_ORDER_4, SAY_ORDER_5, SPELL_MURU_BERSERK, StartMiniEvent(), TRIGGERED_OLD_TRIGGERED, TYPE_KILJAEDEN, TYPE_MURU, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_FLAG_UNTARGETABLE, TimerManager::UpdateTimers(), and urand().
Field Documentation
m_auiEncounter
uint32 instance_sunwell_plateau::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 208 of file sunwell_plateau.h.
Referenced by GetData(), Initialize(), IsEncounterInProgress(), Load(), OnObjectCreate(), OnPlayerEnter(), SetData(), and Update().
m_brutallusIntroStarted
bool instance_sunwell_plateau::m_brutallusIntroStarted protected
Definition at line 211 of file sunwell_plateau.h.
Referenced by IsBrutallusIntroStarted(), and StartBrutallusIntro().
m_felmystSpawns
GuidVector instance_sunwell_plateau::m_felmystSpawns protected
Definition at line 232 of file sunwell_plateau.h.
Referenced by OnCreatureCreate(), and SetData().
m_firstEnter
bool instance_sunwell_plateau::m_firstEnter protected
Definition at line 213 of file sunwell_plateau.h.
Referenced by OnPlayerEnter().
m_gauntletRespawnTime
TimePoint instance_sunwell_plateau::m_gauntletRespawnTime protected
Definition at line 217 of file sunwell_plateau.h.
Referenced by OnCreatureDeath(), OnCreatureEnterCombat(), OnCreatureEvade(), ResetGauntlet(), RespawnGauntlet(), and Update().
m_gauntletSpawns
GuidVector instance_sunwell_plateau::m_gauntletSpawns protected
Definition at line 233 of file sunwell_plateau.h.
Referenced by OnCreatureCreate(), and ResetGauntlet().
m_impsStarted
bool instance_sunwell_plateau::m_impsStarted protected
Definition at line 215 of file sunwell_plateau.h.
Referenced by ResetGauntlet(), SpawnGauntlet(), StartImps(), StopImps(), and Update().
m_kiljaedenRespawnDbGuids
std::vector<uint32> instance_sunwell_plateau::m_kiljaedenRespawnDbGuids protected
Definition at line 230 of file sunwell_plateau.h.
Referenced by FailKiljaeden(), and OnCreatureCreate().
m_lAllFlightTriggersList
GuidList instance_sunwell_plateau::m_lAllFlightTriggersList protected
Definition at line 228 of file sunwell_plateau.h.
Referenced by DoSortFlightTriggers(), and OnCreatureCreate().
m_lBackdoorTriggersList
GuidList instance_sunwell_plateau::m_lBackdoorTriggersList protected
Definition at line 229 of file sunwell_plateau.h.
Referenced by OnCreatureCreate().
m_miniAttackEvent
bool instance_sunwell_plateau::m_miniAttackEvent protected
Definition at line 216 of file sunwell_plateau.h.
Referenced by StartMiniEvent(), and Update().
m_muruTrashGuids
GuidVector instance_sunwell_plateau::m_muruTrashGuids protected
Definition at line 231 of file sunwell_plateau.h.
Referenced by OnCreatureCreate(), and SetData().
m_spawnedGauntlet
bool instance_sunwell_plateau::m_spawnedGauntlet protected
Definition at line 214 of file sunwell_plateau.h.
Referenced by OnCreatureDeath(), ResetGauntlet(), and SpawnGauntlet().
m_spectralRealmPlayers
GuidSet instance_sunwell_plateau::m_spectralRealmPlayers protected
Definition at line 225 of file sunwell_plateau.h.
Referenced by AddToSpectralRealm(), DoEjectSpectralPlayers(), and RemoveFromSpectralRealm().
m_strInstData
std::string instance_sunwell_plateau::m_strInstData protected
Definition at line 209 of file sunwell_plateau.h.
Referenced by Save(), and SetData().
m_twinsSpawns
GuidVector instance_sunwell_plateau::m_twinsSpawns protected
Definition at line 234 of file sunwell_plateau.h.
Referenced by OnCreatureCreate(), OnObjectCreate(), and SetData().
m_uiDeceiversKilled
uint8 instance_sunwell_plateau::m_uiDeceiversKilled protected
Definition at line 220 of file sunwell_plateau.h.
Referenced by FailKiljaeden(), and OnCreatureDeath().
m_uiKiljaedenYellTimer
uint32 instance_sunwell_plateau::m_uiKiljaedenYellTimer protected
Definition at line 223 of file sunwell_plateau.h.
Referenced by Update().
m_uiMuruBerserkTimer
uint32 instance_sunwell_plateau::m_uiMuruBerserkTimer protected
Definition at line 222 of file sunwell_plateau.h.
Referenced by SetData(), and Update().
m_uiSpectralRealmTimer
uint32 instance_sunwell_plateau::m_uiSpectralRealmTimer protected
Definition at line 221 of file sunwell_plateau.h.
m_vLeftFlightTriggersVect
GuidVector instance_sunwell_plateau::m_vLeftFlightTriggersVect protected
Definition at line 227 of file sunwell_plateau.h.
Referenced by DoSortFlightTriggers(), and SelectFelmystFlightTrigger().
m_vRightFlightTriggersVect
GuidVector instance_sunwell_plateau::m_vRightFlightTriggersVect protected
Definition at line 226 of file sunwell_plateau.h.
Referenced by DoSortFlightTriggers(), and SelectFelmystFlightTrigger().
The documentation for this class was generated from the following files:
sunwell_plateau.h
sunwell_plateau.cpp