CMaNGOS_WoTLK: VMAP::VMapFactory Class Reference
VMAP::VMapFactory Class Reference
#include <VMapFactory.h>
Static Public Member Functions
static IVMapManager * createOrGetVMapManager ()
static void clear ()
static void chompAndTrim (std::string &str)
static bool getNextId (const std::string &pString, unsigned int &pStartPos, unsigned int &pId)
Detailed Description
Definition at line 32 of file VMapFactory.h.
Member Function Documentation
chompAndTrim()
void VMAP::VMapFactory::chompAndTrim (std::string & str) static
Definition at line 26 of file VMapFactory.cpp.
Referenced by World::LoadConfigSettings().
clear()
void VMAP::VMapFactory::clear () static
Definition at line 97 of file VMapFactory.cpp.
References VMAP::gVMapManager, and VMAP::m_vmapMutex.
Referenced by World::~World().
createOrGetVMapManager()
IVMapManager * VMAP::VMapFactory::createOrGetVMapManager () static
Definition at line 84 of file VMapFactory.cpp.
References VMAP::gVMapManager, and VMAP::m_vmapMutex.
Referenced by Spell::CheckCast(), GridMap::ExistVMap(), Map::GetHeightInRange(), Map::GetHitPosition(), ChatHandler::HandleGPSCommand(), GameObjectModel::initialize(), Map::IsInLineOfSight(), World::LoadConfigSettings(), TerrainInfo::TerrainInfo(), and GameObjectModel::~GameObjectModel().
getNextId()
bool VMAP::VMapFactory::getNextId (const std::string & pString, unsigned int & pStartPos, unsigned int & pId) static
Definition at line 60 of file VMapFactory.cpp.
Referenced by World::LoadConfigSettings().
The documentation for this class was generated from the following files:
VMapFactory.h
VMapFactory.cpp