CMaNGOS_WoTLK: MaNGOS::Socket Class Reference
MaNGOS::Socket Class Reference abstract
#include <Socket.hpp>
Data Structures
class custom_alloc_handler
class handler_allocator
Public Member Functions
Socket (boost::asio::io_service &service, std::function< void(Socket *)> closeHandler)
virtual ~Socket ()=default
virtual bool Open ()
void Close ()
bool IsClosed () const
virtual bool Deletable () const
bool Read (char *buffer, int length)
void ReadSkip (int length)
void Write (const char *buffer, int length)
void Write (const char *header, int headerSize, const char *content, int contentSize)
boost::asio::ip::tcp::socket & GetAsioSocket ()
const std::string & GetRemoteEndpoint () const
const std::string & GetRemoteAddress () const
template<typename T >
std::shared_ptr< T > shared ()
boost::asio::ip::address GetRemoteIpAddress () const
uint16 GetRemotePort () const
Protected Member Functions
virtual bool ProcessIncomingData ()=0
const uint8 * InPeak () const
int ReadLengthRemaining () const
void ForceFlushOut ()
Protected Attributes
const std::string m_address
const std::string m_remoteEndpoint
boost::asio::ip::address m_remoteAddress
uint16 m_remotePort
Private Types
enum class WriteState { Idle , Buffering , Sending }
enum class ReadState { Idle , Reading }
Private Member Functions
void StartAsyncRead ()
void OnRead (const boost::system::error_code &error, size_t length)
void StartWriteFlushTimer ()
void OnWriteComplete (const boost::system::error_code &error, size_t length)
void FlushOut ()
void OnError (const boost::system::error_code &error)
Static Private Member Functions
template<typename Handler >
static custom_alloc_handler< Handler > make_custom_alloc_handler (handler_allocator &a, Handler h)
Private Attributes
WriteState m_writeState
ReadState m_readState
boost::asio::ip::tcp::socket m_socket
std::function< void(Socket *)> m_closeHandler
std::unique_ptr< PacketBuffer > m_inBuffer
std::unique_ptr< PacketBuffer > m_outBuffer
std::unique_ptr< PacketBuffer > m_secondaryOutBuffer
std::mutex m_mutex
std::mutex m_closeMutex
boost::asio::deadline_timer m_outBufferFlushTimer
handler_allocator m_allocator
Static Private Attributes
static const int BufferTimeout = 50
Detailed Description
Definition at line 35 of file Socket.hpp.
Member Enumeration Documentation
ReadState
enum MaNGOS::Socket::ReadState strong private
Enumerator
Idle
Reading
Definition at line 49 of file Socket.hpp.
WriteState
enum MaNGOS::Socket::WriteState strong private
Enumerator
Idle
Buffering
Sending
Definition at line 42 of file Socket.hpp.
Constructor & Destructor Documentation
Socket()
MaNGOS::Socket::Socket (boost::asio::io_service & service, std::function< void(Socket *)> closeHandler)
Definition at line 35 of file Socket.cpp.
~Socket()
virtual MaNGOS::Socket::~Socket () virtual default
Member Function Documentation
Close()
void MaNGOS::Socket::Close ()
Definition at line 64 of file Socket.cpp.
References IsClosed(), m_closeHandler, m_closeMutex, and m_socket.
Referenced by AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleReconnectProof(), AuthSocket::_HandleXferCancel(), OnError(), OnRead(), and AuthSocket::Open().
Deletable()
virtual bool MaNGOS::Socket::Deletable () const inline virtual
Definition at line 101 of file Socket.hpp.
References IsClosed().
FlushOut()
void MaNGOS::Socket::FlushOut () private
Definition at line 224 of file Socket.cpp.
References Buffering, Idle, IsClosed(), m_allocator, m_mutex, m_outBuffer, m_socket, m_writeState, make_custom_alloc_handler(), and Sending.
ForceFlushOut()
void MaNGOS::Socket::ForceFlushOut () protected
Definition at line 249 of file Socket.cpp.
References m_outBufferFlushTimer.
Referenced by WorldSocket::SendPacket().
GetAsioSocket()
boost::asio::ip::tcp::socket& MaNGOS::Socket::GetAsioSocket () inline
Definition at line 109 of file Socket.hpp.
References m_socket.
GetRemoteAddress()
const std::string& MaNGOS::Socket::GetRemoteAddress () const inline
Definition at line 112 of file Socket.hpp.
References m_address.
Referenced by WorldSocket::HandleAuthSession(), WorldSocket::HandlePing(), and WorldSocket::ProcessIncomingData().
GetRemoteEndpoint()
const std::string& MaNGOS::Socket::GetRemoteEndpoint () const inline
Definition at line 111 of file Socket.hpp.
References m_remoteEndpoint.
Referenced by WorldSocket::ProcessIncomingData(), and WorldSocket::SendPacket().
GetRemoteIpAddress()
boost::asio::ip::address MaNGOS::Socket::GetRemoteIpAddress () const inline
Definition at line 117 of file Socket.hpp.
References m_remoteAddress.
Referenced by WorldSocket::ProcessIncomingData(), and WorldSocket::SendPacket().
GetRemotePort()
uint16 MaNGOS::Socket::GetRemotePort () const inline
Definition at line 118 of file Socket.hpp.
References m_remotePort.
Referenced by WorldSocket::ProcessIncomingData(), and WorldSocket::SendPacket().
InPeak()
const uint8* MaNGOS::Socket::InPeak () const inline protected
Definition at line 87 of file Socket.hpp.
References m_inBuffer.
Referenced by WorldSocket::ProcessIncomingData(), and AuthSocket::ProcessIncomingData().
IsClosed()
bool MaNGOS::Socket::IsClosed () const inline
Definition at line 100 of file Socket.hpp.
References m_socket.
Referenced by Close(), Deletable(), FlushOut(), WorldSocket::HandleAuthSession(), OnError(), OnRead(), OnWriteComplete(), AuthSocket::Open(), WorldSocket::ProcessIncomingData(), WorldSocket::SendPacket(), StartAsyncRead(), and StartWriteFlushTimer().
make_custom_alloc_handler()
template<typename Handler > static custom_alloc_handler<Handler> MaNGOS::Socket::make_custom_alloc_handler (handler_allocator & a, Handler h) inline static private
Definition at line 196 of file Socket.hpp.
Referenced by FlushOut(), OnWriteComplete(), and StartAsyncRead().
OnError()
void MaNGOS::Socket::OnError (const boost::system::error_code & error) private
Definition at line 151 of file Socket.cpp.
References Close(), IsClosed(), and sLog.
Referenced by OnRead(), and OnWriteComplete().
OnRead()
void MaNGOS::Socket::OnRead (const boost::system::error_code & error, size_t length) private
Definition at line 93 of file Socket.cpp.
References Close(), Idle, IsClosed(), m_inBuffer, m_readState, m_socket, OnError(), ProcessIncomingData(), and StartAsyncRead().
OnWriteComplete()
void MaNGOS::Socket::OnWriteComplete (const boost::system::error_code & error, size_t length) private
Definition at line 254 of file Socket.cpp.
References Idle, IsClosed(), m_allocator, m_mutex, m_outBuffer, m_secondaryOutBuffer, m_socket, m_writeState, make_custom_alloc_handler(), OnError(), and Sending.
Open()
bool MaNGOS::Socket::Open () virtual
Reimplemented in AuthSocket, RASocket, and WorldSocket.
Definition at line 40 of file Socket.cpp.
References m_address, m_inBuffer, m_outBuffer, m_remoteAddress, m_remoteEndpoint, m_remotePort, m_secondaryOutBuffer, m_socket, sLog, and StartAsyncRead().
ProcessIncomingData()
virtual bool MaNGOS::Socket::ProcessIncomingData () protected pure virtual
Implemented in AuthSocket, RASocket, and WorldSocket.
Referenced by OnRead().
Read()
bool MaNGOS::Socket::Read (char * buffer, int length)
Definition at line 162 of file Socket.cpp.
References m_inBuffer, and ReadLengthRemaining().
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleReconnectProof(), WorldSocket::ProcessIncomingData(), and RASocket::ProcessIncomingData().
ReadLengthRemaining()
int MaNGOS::Socket::ReadLengthRemaining () const inline protected
Definition at line 89 of file Socket.hpp.
References m_inBuffer.
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleXferResume(), WorldSocket::ProcessIncomingData(), RASocket::ProcessIncomingData(), AuthSocket::ProcessIncomingData(), and Read().
ReadSkip()
void MaNGOS::Socket::ReadSkip (int length) inline
Definition at line 104 of file Socket.hpp.
References m_inBuffer.
Referenced by AuthSocket::_HandleRealmList(), AuthSocket::_HandleXferAccept(), AuthSocket::_HandleXferCancel(), AuthSocket::_HandleXferResume(), and WorldSocket::ProcessIncomingData().
shared()
template<typename T > std::shared_ptr<T> MaNGOS::Socket::shared () inline
Definition at line 115 of file Socket.hpp.
Referenced by MaNGOS::NetworkThread< SocketType >::RemoveSocket(), and WorldSession::RequestNewSocket().
StartAsyncRead()
void MaNGOS::Socket::StartAsyncRead () private
Definition at line 78 of file Socket.cpp.
References Idle, IsClosed(), m_allocator, m_inBuffer, m_readState, m_socket, make_custom_alloc_handler(), and Reading.
Referenced by OnRead(), and Open().
StartWriteFlushTimer()
void MaNGOS::Socket::StartWriteFlushTimer () private
Definition at line 205 of file Socket.cpp.
References Buffering, BufferTimeout, Idle, IsClosed(), m_outBufferFlushTimer, and m_writeState.
Referenced by Write().
Write() [1/2]
void MaNGOS::Socket::Write (const char * buffer, int length)
Definition at line 189 of file Socket.cpp.
References Idle, m_mutex, m_outBuffer, m_secondaryOutBuffer, m_writeState, Sending, StartWriteFlushTimer(), and MaNGOS::PacketBuffer::Write().
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), AuthSocket::_HandleRealmList(), AuthSocket::_HandleReconnectChallenge(), AuthSocket::_HandleReconnectProof(), RASocket::Send(), WorldSocket::SendPacket(), and AuthSocket::SendProof().
Write() [2/2]
void MaNGOS::Socket::Write (const char * header, int headerSize, const char * content, int contentSize)
Definition at line 171 of file Socket.cpp.
References Idle, m_mutex, m_outBuffer, m_secondaryOutBuffer, m_writeState, Sending, StartWriteFlushTimer(), and MaNGOS::PacketBuffer::Write().
Field Documentation
BufferTimeout
const int MaNGOS::Socket::BufferTimeout = 50 static private
Definition at line 40 of file Socket.hpp.
Referenced by StartWriteFlushTimer().
m_address
const std::string MaNGOS::Socket::m_address protected
Definition at line 80 of file Socket.hpp.
Referenced by AuthSocket::_HandleLogonChallenge(), AuthSocket::_HandleLogonProof(), GetRemoteAddress(), Open(), and RASocket::Open().
m_allocator
handler_allocator MaNGOS::Socket::m_allocator private
Definition at line 201 of file Socket.hpp.
Referenced by FlushOut(), OnWriteComplete(), and StartAsyncRead().
m_closeHandler
std::function<void(Socket *)> MaNGOS::Socket::m_closeHandler private
Definition at line 60 of file Socket.hpp.
Referenced by Close().
m_closeMutex
std::mutex MaNGOS::Socket::m_closeMutex private
Definition at line 67 of file Socket.hpp.
Referenced by Close().
m_inBuffer
std::unique_ptr<PacketBuffer> MaNGOS::Socket::m_inBuffer private
Definition at line 62 of file Socket.hpp.
Referenced by InPeak(), OnRead(), Open(), Read(), ReadLengthRemaining(), ReadSkip(), and StartAsyncRead().
m_mutex
std::mutex MaNGOS::Socket::m_mutex private
Definition at line 66 of file Socket.hpp.
Referenced by FlushOut(), OnWriteComplete(), and Write().
m_outBuffer
std::unique_ptr<PacketBuffer> MaNGOS::Socket::m_outBuffer private
Definition at line 63 of file Socket.hpp.
Referenced by FlushOut(), OnWriteComplete(), Open(), and Write().
m_outBufferFlushTimer
boost::asio::deadline_timer MaNGOS::Socket::m_outBufferFlushTimer private
Definition at line 68 of file Socket.hpp.
Referenced by ForceFlushOut(), and StartWriteFlushTimer().
m_readState
ReadState MaNGOS::Socket::m_readState private
Definition at line 56 of file Socket.hpp.
Referenced by OnRead(), and StartAsyncRead().
m_remoteAddress
boost::asio::ip::address MaNGOS::Socket::m_remoteAddress protected
Definition at line 82 of file Socket.hpp.
Referenced by GetRemoteIpAddress(), and Open().
m_remoteEndpoint
const std::string MaNGOS::Socket::m_remoteEndpoint protected
Definition at line 81 of file Socket.hpp.
Referenced by GetRemoteEndpoint(), and Open().
m_remotePort
uint16 MaNGOS::Socket::m_remotePort protected
Definition at line 83 of file Socket.hpp.
Referenced by GetRemotePort(), and Open().
m_secondaryOutBuffer
std::unique_ptr<PacketBuffer> MaNGOS::Socket::m_secondaryOutBuffer private
Definition at line 64 of file Socket.hpp.
Referenced by OnWriteComplete(), Open(), and Write().
m_socket
boost::asio::ip::tcp::socket MaNGOS::Socket::m_socket private
Definition at line 58 of file Socket.hpp.
Referenced by Close(), FlushOut(), GetAsioSocket(), IsClosed(), OnRead(), OnWriteComplete(), Open(), and StartAsyncRead().
m_writeState
WriteState MaNGOS::Socket::m_writeState private
Definition at line 55 of file Socket.hpp.
Referenced by FlushOut(), OnWriteComplete(), StartWriteFlushTimer(), and Write().
The documentation for this class was generated from the following files:
Socket.hpp
Socket.cpp