CMaNGOS_WoTLK: MaNGOS::ExplodeCorpseObjectCheck Class Reference
MaNGOS::ExplodeCorpseObjectCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
ExplodeCorpseObjectCheck (WorldObject const *fobj, float range)
WorldObject const & GetFocusObject () const
bool operator() (Player *u)
bool operator() (Creature *u)
template<class NOT_INTERESTED >
bool operator() (NOT_INTERESTED *)
Private Attributes
WorldObject const * i_fobj
float i_range
Detailed Description
Definition at line 605 of file GridNotifiers.h.
Constructor & Destructor Documentation
ExplodeCorpseObjectCheck()
MaNGOS::ExplodeCorpseObjectCheck::ExplodeCorpseObjectCheck (WorldObject const * fobj, float range) inline
Definition at line 608 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::ExplodeCorpseObjectCheck::GetFocusObject () const inline
Definition at line 609 of file GridNotifiers.h.
References i_fobj.
operator()() [1/3]
bool MaNGOS::ExplodeCorpseObjectCheck::operator() (Creature * u) inline
Definition at line 618 of file GridNotifiers.h.
References CORPSE, CREATURE_TYPEMASK_MECHANICAL_OR_ELEMENTAL, Unit::GetCreatureTypeMask(), Unit::GetDeathState(), Unit::GetDisplayId(), Unit::GetNativeDisplayId(), i_fobj, i_range, Unit::IsTaxiFlying(), and WorldObject::IsWithinDistInMap().
operator()() [2/3]
template<class NOT_INTERESTED > bool MaNGOS::ExplodeCorpseObjectCheck::operator() (NOT_INTERESTED *) inline
Definition at line 627 of file GridNotifiers.h.
operator()() [3/3]
bool MaNGOS::ExplodeCorpseObjectCheck::operator() (Player * u) inline
Definition at line 610 of file GridNotifiers.h.
References CORPSE, Unit::GetDeathState(), Unit::GetDisplayId(), Unit::GetNativeDisplayId(), Unit::HasAuraType(), i_fobj, i_range, Unit::IsTaxiFlying(), WorldObject::IsWithinDistInMap(), and SPELL_AURA_GHOST.
Field Documentation
i_fobj
WorldObject const* MaNGOS::ExplodeCorpseObjectCheck::i_fobj private
Definition at line 629 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::ExplodeCorpseObjectCheck::i_range private
Definition at line 630 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h