CMaNGOS_WoTLK: instance_blackfathom_deeps Class Reference
instance_blackfathom_deeps Class Reference
#include <blackfathom_deeps.h>
Public Member Functions
instance_blackfathom_deeps (Map *pMap)
~instance_blackfathom_deeps ()
void Initialize () override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void Update (const uint32 diff) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Protected Member Functions
void DoSpawnMobs (uint8 uiWaveIndex)
bool IsWaveEventFinished () const
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint32 m_uiSpawnMobsTimer [MAX_FIRES]
uint8 m_uiWaveCounter
std::list< uint32 > m_lWaveMobsGuids [MAX_FIRES]
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Detailed Description
Definition at line 88 of file blackfathom_deeps.h.
Constructor & Destructor Documentation
instance_blackfathom_deeps()
instance_blackfathom_deeps::instance_blackfathom_deeps (Map * pMap)
Definition at line 33 of file instance_blackfathom_deeps.cpp.
References Initialize().
~instance_blackfathom_deeps()
instance_blackfathom_deeps::~instance_blackfathom_deeps () inline
Definition at line 92 of file blackfathom_deeps.h.
Member Function Documentation
DoSpawnMobs()
void instance_blackfathom_deeps::DoSpawnMobs (uint8 uiWaveIndex) protected
Definition at line 71 of file instance_blackfathom_deeps.cpp.
References aSpawnLocations, aWaveSummonInformation, Creature::GetRespawnCoord(), ScriptedInstance::GetSingleCreatureFromStorage(), INTERACTION_DISTANCE, m_lWaveMobsGuids, MAX_COUNT_POS, NPC_KELRIS, Position::o, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, Position::x, Position::y, and Position::z.
Referenced by Update().
GetData()
uint32 instance_blackfathom_deeps::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 148 of file instance_blackfathom_deeps.cpp.
References m_auiEncounter, TYPE_AQUANIS, TYPE_KELRIS, and TYPE_SHRINE.
Referenced by GOUse_go_fathom_stone(), and GOUse_go_fire_of_akumai().
Initialize()
void instance_blackfathom_deeps::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 39 of file instance_blackfathom_deeps.cpp.
References m_auiEncounter, and m_uiSpawnMobsTimer.
Referenced by instance_blackfathom_deeps().
IsWaveEventFinished()
bool instance_blackfathom_deeps::IsWaveEventFinished () const protected
Definition at line 212 of file instance_blackfathom_deeps.cpp.
References m_lWaveMobsGuids, m_uiWaveCounter, and MAX_FIRES.
Referenced by OnCreatureDeath().
Load()
void instance_blackfathom_deeps::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 160 of file instance_blackfathom_deeps.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_blackfathom_deeps::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 45 of file instance_blackfathom_deeps.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, and NPC_KELRIS.
OnCreatureDeath()
void instance_blackfathom_deeps::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 182 of file instance_blackfathom_deeps.cpp.
References DONE, Object::GetEntry(), Object::GetGUIDLow(), IN_PROGRESS, IsWaveEventFinished(), m_auiEncounter, m_lWaveMobsGuids, NPC_AKUMAI_SERVANT, NPC_AKUMAI_SNAPJAW, NPC_BARBED_CRUSTACEAN, NPC_BARON_AQUANIS, NPC_MURKSHALLOW_SOFTSHELL, SetData(), TYPE_AQUANIS, and TYPE_SHRINE.
OnObjectCreate()
void instance_blackfathom_deeps::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 51 of file instance_blackfathom_deeps.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_PORTAL_DOOR, GO_SHRINE_1, GO_SHRINE_2, GO_SHRINE_3, GO_SHRINE_4, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, and GameObject::SetGoState().
Save()
const char* instance_blackfathom_deeps::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 105 of file blackfathom_deeps.h.
References m_strInstData.
SetData()
void instance_blackfathom_deeps::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 111 of file instance_blackfathom_deeps.cpp.
References DONE, ScriptedInstance::DoUseDoorOrButton(), GO_PORTAL_DOOR, IN_PROGRESS, m_auiEncounter, m_strInstData, m_uiSpawnMobsTimer, m_uiWaveCounter, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), TYPE_AQUANIS, TYPE_KELRIS, and TYPE_SHRINE.
Referenced by GOUse_go_fathom_stone(), GOUse_go_fire_of_akumai(), and OnCreatureDeath().
Update()
void instance_blackfathom_deeps::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 228 of file instance_blackfathom_deeps.cpp.
References DoSpawnMobs(), IN_PROGRESS, m_auiEncounter, m_uiSpawnMobsTimer, and MAX_FIRES.
Field Documentation
m_auiEncounter
uint32 instance_blackfathom_deeps::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 112 of file blackfathom_deeps.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureDeath(), OnObjectCreate(), SetData(), and Update().
m_lWaveMobsGuids
std::list<uint32> instance_blackfathom_deeps::m_lWaveMobsGuids[MAX_FIRES] protected
Definition at line 118 of file blackfathom_deeps.h.
Referenced by DoSpawnMobs(), IsWaveEventFinished(), and OnCreatureDeath().
m_strInstData
std::string instance_blackfathom_deeps::m_strInstData protected
Definition at line 113 of file blackfathom_deeps.h.
Referenced by Save(), and SetData().
m_uiSpawnMobsTimer
uint32 instance_blackfathom_deeps::m_uiSpawnMobsTimer[MAX_FIRES] protected
Definition at line 115 of file blackfathom_deeps.h.
Referenced by Initialize(), SetData(), and Update().
m_uiWaveCounter
uint8 instance_blackfathom_deeps::m_uiWaveCounter protected
Definition at line 116 of file blackfathom_deeps.h.
Referenced by IsWaveEventFinished(), and SetData().
The documentation for this class was generated from the following files:
blackfathom_deeps.h
instance_blackfathom_deeps.cpp