CMaNGOS_WoTLK: MaNGOS::AllGameObjectEntriesListInPosRangeCheck Class Reference
MaNGOS::AllGameObjectEntriesListInPosRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AllGameObjectEntriesListInPosRangeCheck (WorldObject const &obj, float x, float y, float z, std::set< uint32 > &entries, float range, bool is3D=true)
bool operator() (GameObject *go)
WorldObject const & GetFocusObject () const
Data Fields
std::vector< uint32 > i_ranges
Private Member Functions
AllGameObjectEntriesListInPosRangeCheck (AllGameObjectEntriesListInObjectRangeCheck const &)
Private Attributes
float i_x
float i_y
float i_z
std::set< uint32 > & i_entries
float i_range
bool i_is3D
WorldObject const & i_obj
Detailed Description
Definition at line 823 of file GridNotifiers.h.
Constructor & Destructor Documentation
AllGameObjectEntriesListInPosRangeCheck() [1/2]
MaNGOS::AllGameObjectEntriesListInPosRangeCheck::AllGameObjectEntriesListInPosRangeCheck (WorldObject const & obj, float x, float y, float z, std::set< uint32 > & entries, float range, bool is3D = true) inline
Definition at line 826 of file GridNotifiers.h.
AllGameObjectEntriesListInPosRangeCheck() [2/2]
MaNGOS::AllGameObjectEntriesListInPosRangeCheck::AllGameObjectEntriesListInPosRangeCheck (AllGameObjectEntriesListInObjectRangeCheck const &) private
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AllGameObjectEntriesListInPosRangeCheck::GetFocusObject () const inline
Definition at line 836 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AllGameObjectEntriesListInPosRangeCheck::operator() (GameObject * go) inline
Definition at line 827 of file GridNotifiers.h.
References DIST_CALC_COMBAT_REACH, WorldObject::GetDistance(), Object::GetEntry(), i_entries, i_range, i_x, i_y, i_z, and GameObject::IsSpawned().
Field Documentation
i_entries
std::set<uint32>& MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_entries private
Definition at line 839 of file GridNotifiers.h.
Referenced by operator()().
i_is3D
bool MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_is3D private
Definition at line 841 of file GridNotifiers.h.
i_obj
WorldObject const& MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_obj private
Definition at line 842 of file GridNotifiers.h.
Referenced by GetFocusObject().
i_range
float MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_range private
Definition at line 840 of file GridNotifiers.h.
Referenced by operator()().
i_ranges
std::vector<uint32> MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_ranges
Definition at line 835 of file GridNotifiers.h.
i_x
float MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_x private
Definition at line 838 of file GridNotifiers.h.
Referenced by operator()().
i_y
float MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_y private
Definition at line 838 of file GridNotifiers.h.
Referenced by operator()().
i_z
float MaNGOS::AllGameObjectEntriesListInPosRangeCheck::i_z private
Definition at line 838 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h