CMaNGOS_WoTLK: AchievementGlobalMgr Class Reference
AchievementGlobalMgr Class Reference
#include <AchievementMgr.h>
Public Member Functions
AchievementCriteriaEntryList const & GetAchievementCriteriaByType (AchievementCriteriaTypes type) const
AchievementCriteriaEntryList const * GetAchievementCriteriaByAchievement (uint32 id)
AchievementEntryList const * GetAchievementByReferencedId (uint32 id) const
AchievementReward const * GetAchievementReward (AchievementEntry const *achievement, uint8 gender) const
AchievementRewardLocale const * GetAchievementRewardLocale (AchievementEntry const *achievement, uint8 gender) const
AchievementCriteriaRequirementSet const * GetCriteriaRequirementSet (AchievementCriteriaEntry const *achievementCriteria)
bool IsRealmCompleted (AchievementEntry const *achievement) const
void SetRealmCompleted (AchievementEntry const *achievement)
void LoadAchievementCriteriaList ()
void LoadAchievementCriteriaRequirements ()
void LoadAchievementReferenceList ()
void LoadCompletedAchievements ()
void LoadRewards ()
void LoadRewardLocales ()
Private Types
typedef std::set< uint32 > AllCompletedAchievements
Private Attributes
AchievementCriteriaRequirementMap m_criteriaRequirementMap
AchievementCriteriaEntryList m_AchievementCriteriasByType [ACHIEVEMENT_CRITERIA_TYPE_TOTAL]
AchievementCriteriaListByAchievement m_AchievementCriteriaListByAchievement
AchievementListByReferencedId m_AchievementListByReferencedId
AllCompletedAchievements m_allCompletedAchievements
AchievementRewardsMap m_achievementRewards
AchievementRewardLocalesMap m_achievementRewardLocales
Detailed Description
Definition at line 328 of file AchievementMgr.h.
Member Typedef Documentation
AllCompletedAchievements
typedef std::set<uint32> AchievementGlobalMgr::AllCompletedAchievements private
Definition at line 358 of file AchievementMgr.h.
Member Function Documentation
GetAchievementByReferencedId()
AchievementEntryList const * AchievementGlobalMgr::GetAchievementByReferencedId (uint32 id) const
Definition at line 2467 of file AchievementMgr.cpp.
References m_AchievementListByReferencedId.
GetAchievementCriteriaByAchievement()
AchievementCriteriaEntryList const * AchievementGlobalMgr::GetAchievementCriteriaByAchievement (uint32 id)
Definition at line 2461 of file AchievementMgr.cpp.
References m_AchievementCriteriaListByAchievement.
GetAchievementCriteriaByType()
AchievementCriteriaEntryList const & AchievementGlobalMgr::GetAchievementCriteriaByType (AchievementCriteriaTypes type) const
Definition at line 2456 of file AchievementMgr.cpp.
References m_AchievementCriteriasByType.
GetAchievementReward()
AchievementReward const * AchievementGlobalMgr::GetAchievementReward (AchievementEntry const * achievement, uint8 gender) const
Definition at line 2473 of file AchievementMgr.cpp.
References GENDER_NONE, AchievementEntry::ID, and m_achievementRewards.
GetAchievementRewardLocale()
AchievementRewardLocale const * AchievementGlobalMgr::GetAchievementRewardLocale (AchievementEntry const * achievement, uint8 gender) const
Definition at line 2483 of file AchievementMgr.cpp.
References GENDER_NONE, AchievementEntry::ID, and m_achievementRewardLocales.
GetCriteriaRequirementSet()
AchievementCriteriaRequirementSet const * AchievementGlobalMgr::GetCriteriaRequirementSet (AchievementCriteriaEntry const * achievementCriteria)
Definition at line 2493 of file AchievementMgr.cpp.
References AchievementCriteriaEntry::ID, and m_criteriaRequirementMap.
Referenced by LoadAchievementCriteriaRequirements().
IsRealmCompleted()
bool AchievementGlobalMgr::IsRealmCompleted (AchievementEntry const * achievement) const
Definition at line 2499 of file AchievementMgr.cpp.
References AchievementEntry::ID, and m_allCompletedAchievements.
LoadAchievementCriteriaList()
void AchievementGlobalMgr::LoadAchievementCriteriaList ()
Definition at line 2509 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_TOTAL, m_AchievementCriteriaListByAchievement, m_AchievementCriteriasByType, MANGOS_ASSERT, AchievementCriteriaEntry::referredAchievement, AchievementCriteriaEntry::requiredType, sAchievementCriteriaStore, sAchievementStore, sLog, and BarGoLink::step().
LoadAchievementCriteriaRequirements()
void AchievementGlobalMgr::LoadAchievementCriteriaRequirements ()
Definition at line 2590 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_CONDITION_NO_LOOSE, ACHIEVEMENT_CRITERIA_REQUIRE_DISABLED, ACHIEVEMENT_CRITERIA_REQUIRE_NONE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, AchievementCriteriaRequirementSet::Add(), AchievementCriteriaEntry::do_emote, QueryResult::Fetch(), GetCriteriaRequirementSet(), QueryResult::GetRowCount(), Field::GetUInt32(), AchievementEntry::ID, AchievementCriteriaEntry::ID, AchievementCriteriaRequirement::IsValid(), AchievementCriteriaEntry::loot_type, m_criteriaRequirementMap, QueryResult::NextRow(), Database::Query(), AchievementCriteriaEntry::referredAchievement, AchievementCriteriaEntry::requiredType, AchievementCriteriaRequirement::requirementType, sAchievementCriteriaStore, sAchievementStore, AchievementCriteriaRequirementSet::SetCriteriaId(), sLog, BarGoLink::step(), AchievementCriteriaEntry::win_bg, AchievementCriteriaEntry::win_duel, AchievementCriteriaEntry::win_rated_arena, and WorldDatabase.
LoadAchievementReferenceList()
void AchievementGlobalMgr::LoadAchievementReferenceList ()
Definition at line 2551 of file AchievementMgr.cpp.
References m_AchievementListByReferencedId, AchievementEntry::refAchievement, sAchievementStore, sLog, and BarGoLink::step().
LoadCompletedAchievements()
void AchievementGlobalMgr::LoadCompletedAchievements ()
Definition at line 2721 of file AchievementMgr.cpp.
References CharacterDatabase, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), m_allCompletedAchievements, QueryResult::NextRow(), Database::PExecute(), Database::Query(), sAchievementStore, SIZEFMTD, sLog, and BarGoLink::step().
LoadRewardLocales()
void AchievementGlobalMgr::LoadRewardLocales ()
Definition at line 2892 of file AchievementMgr.cpp.
References QueryResult::Fetch(), AchievementRewardLocale::gender, GENDER_NONE, QueryResult::GetRowCount(), Field::GetUInt32(), m_achievementRewardLocales, m_achievementRewards, MAX_GENDER, MAX_LOCALE, QueryResult::NextRow(), Database::Query(), SIZEFMTD, sLog, sObjectMgr, BarGoLink::step(), AchievementRewardLocale::subject, AchievementRewardLocale::text, and WorldDatabase.
LoadRewards()
void AchievementGlobalMgr::LoadRewards ()
Definition at line 2760 of file AchievementMgr.cpp.
References QueryResult::Fetch(), AchievementReward::gender, GENDER_NONE, Field::GetCppString(), ObjectMgr::GetCreatureTemplate(), ObjectMgr::GetItemPrototype(), QueryResult::GetRowCount(), Field::GetUInt32(), AchievementReward::itemId, m_achievementRewards, MAX_GENDER, QueryResult::NextRow(), Database::Query(), sAchievementStore, sCharTitlesStore, AchievementReward::sender, sLog, BarGoLink::step(), AchievementReward::subject, AchievementReward::text, AchievementReward::titleId, and WorldDatabase.
SetRealmCompleted()
void AchievementGlobalMgr::SetRealmCompleted (AchievementEntry const * achievement)
Definition at line 2504 of file AchievementMgr.cpp.
References AchievementEntry::ID, and m_allCompletedAchievements.
Field Documentation
m_AchievementCriteriaListByAchievement
AchievementCriteriaListByAchievement AchievementGlobalMgr::m_AchievementCriteriaListByAchievement private
Definition at line 354 of file AchievementMgr.h.
Referenced by GetAchievementCriteriaByAchievement(), and LoadAchievementCriteriaList().
m_AchievementCriteriasByType
AchievementCriteriaEntryList AchievementGlobalMgr::m_AchievementCriteriasByType[ACHIEVEMENT_CRITERIA_TYPE_TOTAL] private
Definition at line 352 of file AchievementMgr.h.
Referenced by GetAchievementCriteriaByType(), and LoadAchievementCriteriaList().
m_AchievementListByReferencedId
AchievementListByReferencedId AchievementGlobalMgr::m_AchievementListByReferencedId private
Definition at line 356 of file AchievementMgr.h.
Referenced by GetAchievementByReferencedId(), and LoadAchievementReferenceList().
m_achievementRewardLocales
AchievementRewardLocalesMap AchievementGlobalMgr::m_achievementRewardLocales private
Definition at line 362 of file AchievementMgr.h.
Referenced by GetAchievementRewardLocale(), and LoadRewardLocales().
m_achievementRewards
AchievementRewardsMap AchievementGlobalMgr::m_achievementRewards private
Definition at line 361 of file AchievementMgr.h.
Referenced by GetAchievementReward(), LoadRewardLocales(), and LoadRewards().
m_allCompletedAchievements
AllCompletedAchievements AchievementGlobalMgr::m_allCompletedAchievements private
Definition at line 359 of file AchievementMgr.h.
Referenced by IsRealmCompleted(), LoadCompletedAchievements(), and SetRealmCompleted().
m_criteriaRequirementMap
AchievementCriteriaRequirementMap AchievementGlobalMgr::m_criteriaRequirementMap private
Definition at line 349 of file AchievementMgr.h.
Referenced by GetCriteriaRequirementSet(), and LoadAchievementCriteriaRequirements().
The documentation for this class was generated from the following files:
AchievementMgr.h
AchievementMgr.cpp