CMaNGOS_WoTLK: Spell Class Reference
Spell Class Reference
#include <Spell.h>
Data Structures
struct CorpseTargetInfo
struct CreaturePosition
struct DestTargetInfo
struct EffectSkillInfo
struct GOTargetInfo
struct ItemTargetInfo
struct TargetInfo
struct TempTargetData
struct TempTargetingData
Public Types
typedef std::vector< CreaturePosition > CreatureSummonPositions
typedef std::list< TargetInfo > TargetList
typedef std::list< GOTargetInfo > GOTargetList
typedef std::list< ItemTargetInfo > ItemTargetList
typedef std::list< CorpseTargetInfo > CorpseTargetList
Public Member Functions
void EffectEmpty (SpellEffectIndex eff_idx)
void EffectNULL (SpellEffectIndex eff_idx)
void EffectUnused (SpellEffectIndex eff_idx)
void EffectDistract (SpellEffectIndex eff_idx)
void EffectPull (SpellEffectIndex eff_idx)
void EffectSchoolDMG (SpellEffectIndex eff_idx)
void EffectEnvironmentalDMG (SpellEffectIndex eff_idx)
void EffectInstaKill (SpellEffectIndex eff_idx)
void EffectDummy (SpellEffectIndex eff_idx)
void EffectTeleportUnits (SpellEffectIndex eff_idx)
void EffectApplyAura (SpellEffectIndex eff_idx)
void EffectSendEvent (SpellEffectIndex eff_idx)
void EffectPowerBurn (SpellEffectIndex eff_idx)
void EffectPowerDrain (SpellEffectIndex eff_idx)
void EffectHeal (SpellEffectIndex eff_idx)
void EffectBind (SpellEffectIndex eff_idx)
void EffectHealthLeech (SpellEffectIndex eff_idx)
void EffectQuestComplete (SpellEffectIndex eff_idx)
void EffectCreateItem (SpellEffectIndex eff_idx)
void EffectCreateItem2 (SpellEffectIndex eff_idx)
void EffectCreateRandomItem (SpellEffectIndex eff_idx)
void EffectPersistentAA (SpellEffectIndex eff_idx)
void EffectEnergize (SpellEffectIndex eff_idx)
void EffectOpenLock (SpellEffectIndex eff_idx)
void EffectSummonChangeItem (SpellEffectIndex eff_idx)
void EffectProficiency (SpellEffectIndex eff_idx)
void EffectTeleportGraveyard (SpellEffectIndex eff_idx)
void EffectApplyAreaAura (SpellEffectIndex eff_idx)
void EffectSummonType (SpellEffectIndex eff_idx)
void EffectLearnSpell (SpellEffectIndex eff_idx)
void EffectDispel (SpellEffectIndex eff_idx)
void EffectDualWield (SpellEffectIndex eff_idx)
void EffectPickPocket (SpellEffectIndex eff_idx)
void EffectAddFarsight (SpellEffectIndex eff_idx)
void EffectHealMechanical (SpellEffectIndex eff_idx)
void EffectJump (SpellEffectIndex eff_idx)
void EffectTeleUnitsFaceCaster (SpellEffectIndex eff_idx)
void EffectLearnSkill (SpellEffectIndex eff_idx)
void EffectAddHonor (SpellEffectIndex eff_idx)
void EffectSpawn (SpellEffectIndex eff_idx)
void EffectTradeSkill (SpellEffectIndex eff_idx)
void EffectEnchantItemPerm (SpellEffectIndex eff_idx)
void EffectEnchantItemTmp (SpellEffectIndex eff_idx)
void EffectTameCreature (SpellEffectIndex eff_idx)
void EffectSummonPet (SpellEffectIndex eff_idx)
void EffectLearnPetSpell (SpellEffectIndex eff_idx)
void EffectWeaponDmg (SpellEffectIndex eff_idx)
void EffectClearQuest (SpellEffectIndex eff_idx)
void EffectForceCast (SpellEffectIndex eff_idx)
void EffectTriggerSpell (SpellEffectIndex eff_idx)
void EffectTriggerMissileSpell (SpellEffectIndex eff_idx)
void EffectThreat (SpellEffectIndex eff_idx)
void EffectRestoreItemCharges (SpellEffectIndex eff_idx)
void EffectHealMaxHealth (SpellEffectIndex eff_idx)
void EffectInterruptCast (SpellEffectIndex eff_idx)
void EffectSummonObjectWild (SpellEffectIndex eff_idx)
void EffectScriptEffect (SpellEffectIndex eff_idx)
void EffectSanctuary (SpellEffectIndex eff_idx)
void EffectAddComboPoints (SpellEffectIndex eff_idx)
void EffectDuel (SpellEffectIndex eff_idx)
void EffectStuck (SpellEffectIndex eff_idx)
void EffectSummonPlayer (SpellEffectIndex eff_idx)
void EffectActivateObject (SpellEffectIndex eff_idx)
void EffectApplyGlyph (SpellEffectIndex eff_idx)
void EffectEnchantHeldItem (SpellEffectIndex eff_idx)
void EffectSummonObject (SpellEffectIndex eff_idx)
void EffectResurrect (SpellEffectIndex eff_idx)
void EffectParry (SpellEffectIndex eff_idx)
void EffectBlock (SpellEffectIndex eff_idx)
void EffectLeapForward (SpellEffectIndex eff_idx)
void EffectLeapBack (SpellEffectIndex eff_idx)
void EffectTransmitted (SpellEffectIndex eff_idx)
void EffectDisEnchant (SpellEffectIndex eff_idx)
void EffectInebriate (SpellEffectIndex eff_idx)
void EffectFeedPet (SpellEffectIndex eff_idx)
void EffectDismissPet (SpellEffectIndex eff_idx)
void EffectReputation (SpellEffectIndex eff_idx)
void EffectSelfResurrect (SpellEffectIndex eff_idx)
void EffectSkinning (SpellEffectIndex eff_idx)
void EffectCharge (SpellEffectIndex eff_idx)
void EffectChargeDest (SpellEffectIndex eff_idx)
void EffectProspecting (SpellEffectIndex eff_idx)
void EffectRedirectThreat (SpellEffectIndex eff_idx)
void EffectMilling (SpellEffectIndex eff_idx)
void EffectRenamePet (SpellEffectIndex eff_idx)
void EffectSendTaxi (SpellEffectIndex eff_idx)
void EffectKnockBack (SpellEffectIndex eff_idx)
void EffectPullTowards (SpellEffectIndex eff_idx)
void EffectDispelMechanic (SpellEffectIndex eff_idx)
void EffectSummonDeadPet (SpellEffectIndex eff_idx)
void EffectSummonAllTotems (SpellEffectIndex eff_idx)
void EffectBreakPlayerTargeting (SpellEffectIndex eff_idx)
void EffectDestroyAllTotems (SpellEffectIndex eff_idx)
void EffectDurabilityDamage (SpellEffectIndex eff_idx)
void EffectSkill (SpellEffectIndex eff_idx)
void EffectTaunt (SpellEffectIndex eff_idx)
void EffectDurabilityDamagePCT (SpellEffectIndex eff_idx)
void EffectModifyThreatPercent (SpellEffectIndex eff_idx)
void EffectAddExtraAttacks (SpellEffectIndex eff_idx)
void EffectSpiritHeal (SpellEffectIndex eff_idx)
void EffectSkinPlayerCorpse (SpellEffectIndex eff_idx)
void EffectStealBeneficialBuff (SpellEffectIndex eff_idx)
void EffectUnlearnSpecialization (SpellEffectIndex eff_idx)
void EffectHealPct (SpellEffectIndex eff_idx)
void EffectEnergisePct (SpellEffectIndex eff_idx)
void EffectTriggerSpellWithValue (SpellEffectIndex eff_idx)
void EffectTriggerRitualOfSummoning (SpellEffectIndex eff_idx)
void EffectKillCreditPersonal (SpellEffectIndex eff_idx)
void EffectKillCreditGroup (SpellEffectIndex eff_idx)
void EffectQuestFail (SpellEffectIndex eff_idx)
void EffectQuestOffer (SpellEffectIndex eff_idx)
void EffectActivateRune (SpellEffectIndex eff_idx)
void EffectTeachTaxiNode (SpellEffectIndex eff_idx)
void EffectWMODamage (SpellEffectIndex eff_idx)
void EffectWMORepair (SpellEffectIndex eff_idx)
void EffectWMOChange (SpellEffectIndex eff_idx)
void EffectTitanGrip (SpellEffectIndex eff_idx)
void EffectEnchantItemPrismatic (SpellEffectIndex eff_idx)
void EffectPlaySound (SpellEffectIndex eff_idx)
void EffectPlayMusic (SpellEffectIndex eff_idx)
void EffectSpecCount (SpellEffectIndex eff_idx)
void EffectActivateSpec (SpellEffectIndex eff_idx)
void EffectCancelAura (SpellEffectIndex eff_idx)
void EffectKnockBackFromPosition (SpellEffectIndex eff_idx)
void EffectSummonRafFriend (SpellEffectIndex eff_idx)
void EffectCreateTamedPet (SpellEffectIndex eff_ifx)
Spell (WorldObject *caster, SpellEntry const *info, uint32 triggeredFlags, ObjectGuid originalCasterGUID=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
virtual ~Spell ()
SpellCastResult SpellStart (SpellCastTargets const *targets, Aura *triggeredByAura=nullptr)
void cancel ()
void update (uint32 difftime)
SpellCastResult cast (bool skipCheck=false)
void finish (bool ok=true)
void TakePower ()
void TakeAmmo () const
void TakeReagents ()
void TakeCastItem ()
SpellCastResult CheckCast (bool strict)
SpellCastResult CheckPetCast (Unit *target)
void handle_immediate ()
uint64 handle_delayed (uint64 t_offset)
void _handle_immediate_phase ()
void _handle_finish_phase ()
SpellCastResult CheckItems ()
SpellCastResult CheckRange (bool strict)
SpellCastResult CheckPower (bool strict)
SpellCastResult CheckOrTakeRunePower (bool take)
SpellCastResult CheckCasterAuras (uint32 &param1) const
bool CheckSpellCancelsAuraEffect (AuraType auraType, uint32 &param1) const
bool CheckSpellCancelsCharm (uint32 &param1) const
bool CheckSpellCancelsStun (uint32 &param1) const
bool CheckSpellCancelsSilence (uint32 &param1) const
bool CheckSpellCancelsPacify (uint32 &param1) const
bool CheckSpellCancelsFear (uint32 &param1) const
bool CheckSpellCancelsConfuse (uint32 &param1) const
int32 CalculateSpellEffectValue (SpellEffectIndex i, Unit *target, bool maximum=false, bool finalUse=true)
int32 CalculateSpellEffectDamage (Unit *unitTarget, int32 damage)
bool HaveTargetsForEffect (SpellEffectIndex effect) const
void Delayed ()
void DelayedChannel ()
uint32 getState () const
void setState (uint32 state)
uint32 GetUsableHealthStoneItemType (Unit *unitTarget)
bool DoCreateItem (SpellEffectIndex eff_idx, uint32 itemtype, bool reportError=true)
bool DoSummonPet (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx)
bool DoSummonTotem (CreatureSummonPositions &list, SpellEffectIndex eff_idx, uint8 slot_dbc=0)
bool DoSummonWild (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx, uint32 level)
bool DoSummonCritter (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx, uint32 level)
bool DoSummonGuardian (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx, uint32 level)
bool DoSummonPossessed (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx, uint32 level)
bool DoSummonVehicle (CreatureSummonPositions &list, SummonPropertiesEntry const *prop, SpellEffectIndex effIdx, uint32 level)
void ProcessDispelList (std::list< std::pair< SpellAuraHolder *, uint32 > > &dispelList, std::list< std::pair< SpellAuraHolder *, uint32 > > &successList, std::list< uint32 > &failList)
void EvaluateResultLists (std::list< std::pair< SpellAuraHolder *, uint32 > > &successList, std::list< uint32 > &failList)
void WriteSpellGoTargets (WorldPacket &data)
void WriteAmmoToPacket (WorldPacket &data) const
template<typename T >
WorldObject * FindCorpseUsing ()
bool CheckTarget (Unit *target, SpellEffectIndex eff, bool targetB, CheckException exception=EXCEPTION_NONE) const
bool CanAutoCast (Unit *target)
void SendCastResult (SpellCastResult result) const
void SendSpellStart () const
void SendSpellGo ()
void SendSpellCooldown ()
void SendInterrupted (SpellCastResult result) const
void SendChannelUpdate (uint32 time, uint32 lastTick=0) const
void SendChannelStart (uint32 duration)
void StopCast (SpellCastResult castResult)
void ExecuteEffects (Unit *unitTarget, Item *itemTarget, GameObject *GOTarget, uint32 effectMask)
void HandleEffect (Unit *unitTarget, Item *itemTarget, GameObject *GOTarget, SpellEffectIndex effIdx, float damageMultiplier=1.0)
void HandleThreatSpells ()
void ProcessAOECaps ()
void SetCastItem (Item *item)
Item * GetCastItem ()
int32 GetCastTime () const
uint32 GetCastedTime () const
bool IsAutoRepeat () const
void SetAutoRepeat (bool rep)
void ReSetTimer ()
bool IsRangedSpell () const
bool IsSpellRequiringAmmo () const
bool IsChannelActive () const
bool IsMeleeAttackResetSpell () const
bool IsRangedAttackResetSpell () const
bool IsEffectWithImplementedMultiplier (uint32 effectId) const
bool IsDeletable () const
void SetReferencedFromCurrent (bool yes)
void SetExecutedCurrently (bool yes)
bool IsExecutedCurrently () const
uint64 GetDelayStart () const
void SetDelayStart (uint64 m_time)
uint64 GetDelayMoment () const
void SetSpellStartTravelling (uint32 time)
uint32 GetSpellStartTravelling () const
bool IsNeedSendToClient () const
bool IsTriggeredSpellWithRedundantCastTime () const
bool IsTriggeredByAura () const
SpellEntry const * GetTriggeredByAuraSpellInfo () const
CurrentSpellTypes GetCurrentContainer () const
Unit * GetCaster () const
WorldObject * GetAffectiveCasterObject () const
Unit * GetAffectiveCaster () const
WorldObject * GetCastingObject () const
float GetSpellSpeed () const
bool IsDelayedSpell () const
void RecalculateDelayMomentForDest ()
void UpdatePointers ()
void AddTriggeredSpell (SpellEntry const *spellInfo)
void AddPrecastSpell (SpellEntry const *spellInfo)
void AddTriggeredSpell (uint32 spellId)
void AddPrecastSpell (uint32 spellId)
void CastPreCastSpells (Unit *target)
void CastTriggerSpells ()
void CleanupTargetList ()
void ClearCastItem ()
void SetForwardedCastItem (ObjectGuid guid)
bool IsInterruptible () const
bool CanBeInterrupted () const
void RegisterAuraProc (Aura *aura)
bool IsAuraProcced (Aura *aura)
void SetEffectChance (int32 triggerChance, SpellEffectIndex effIdx)
void ProcReflectProcs (TargetInfo &targetInfo)
SpellCastResult CheckScriptTargeting (SpellEffectIndex effIndex, uint32 chainTargets, float radius, uint32 targetMode, UnitList &tempUnitList, GameObjectList &tempGOList)
SpellScript * GetSpellScript () const
uint64 GetScriptValue () const
void SetScriptValue (uint64 value)
void OnInit ()
void OnSuccessfulStart ()
void OnSuccessfulFinish ()
SpellCastResult OnCheckCast (bool strict)
void OnEffectExecute (SpellEffectIndex effIndex)
void OnRadiusCalculate (SpellEffectIndex effIndex, bool targetB, float &radius)
void OnDestTarget ()
bool OnCheckTarget (GameObject *target, SpellEffectIndex eff) const
bool OnCheckTarget (Unit *target, SpellEffectIndex eff) const
void OnCast ()
void OnHit (SpellMissInfo missInfo)
void OnAfterHit ()
void OnSummon (GameObject *summon)
void OnSummon (Creature *summon)
uint32 GetPhaseMaskOverride ()
Unit * GetUnitTarget ()
Item * GetItemTarget ()
GameObject * GetGOTarget ()
uint32 GetDamage ()
void SetDamage (uint32 newDamage)
SpellSchoolMask GetSchoolMask ()
uint32 GetTotalTargetDamage ()
uint32 GetTotalTargetAbsorb ()
void SetTotalTargetValueModifier (float modifier)
void SetMaxAffectedTargets (uint32 newValue)
void SetChainTargetsCount (SpellEffectIndex effIdx, uint32 newValue)
void SetJumpRadius (float newValue)
void SetFilteringScheme (SpellEffectIndex effIdx, bool targetB, SpellTargetFilterScheme scheme)
uint32 GetPowerCost () const
void SetPowerCost (uint32 powerCost)
TargetList & GetTargetList ()
SpellAuraHolder * GetSpellAuraHolder ()
void SetEventTarget (WorldObject *object)
uint8 GetOldRuneState () const
uint8 GetNewRuneState () const
void SetFakeCaster (Unit *caster)
WorldObject * GetTrueCaster () const
Unit * GetAffectiveCasterOrOwner () const
void SetParam1 (uint32 param1)
void SetParam2 (uint32 param2)
void SetOverridenSpeed (float newSpeed)
void SetIgnoreRoot (bool state)
void SetIgnoreOwnerLevel (bool state)
Static Public Member Functions
static uint32 CalculatePowerCost (SpellEntry const *spellInfo, Unit *caster, Spell *spell=nullptr, Item *castItem=nullptr, bool finalUse=false)
static void SendCastResult (Player const *caster, SpellEntry const *spellInfo, uint8 cast_count, SpellCastResult result, bool isPetCastResult=false, uint32 param1=0, uint32 param2=0)
static bool CheckTargetCreatureType (Unit *target, SpellEntry const *spellInfo)
static void SelectMountByAreaAndSkill (Unit *target, SpellEntry const *parentSpell, uint32 spellId75, uint32 spellId150, uint32 spellId225, uint32 spellId300, uint32 spellIdSpecial)
static SpellCastResult CheckVehicle (Unit const *caster, SpellEntry const &spellInfo)
Data Fields
SpellEntry const * m_spellInfo
SpellEntry const * m_triggeredBySpellInfo
int32 m_currentBasePoints [MAX_EFFECT_INDEX]
uint8 m_cast_count
uint32 m_glyphIndex
SpellCastTargets m_targets
bool m_IsTriggeredSpell
bool m_ignoreHitResult
bool m_ignoreCastTime
bool m_ignoreUnselectableTarget
bool m_ignoreUnattackableTarget
bool m_triggerAutorepeat
bool m_doNotProc
bool m_petCast
bool m_notifyAI
bool m_ignoreGCD
bool m_ignoreCosts
bool m_ignoreCooldowns
bool m_ignoreConcurrentCasts
bool m_ignoreCasterAuraState
bool m_hideInCombatLog
bool m_resetLeash
bool m_channelOnly
bool m_clientCast
bool m_ignoreRoot
bool m_ignoreOwnerLevel
std::set< SpellModifierPair > m_usedAuraCharges
uint8 m_needAliveTargetMask
Protected Types
typedef std::list< SpellEntry const * > SpellInfoList
Protected Member Functions
void SendLoot (ObjectGuid guid, LootType loottype, LockType lockType)
bool IgnoreItemRequirements () const
void UpdateOriginalCasterPointer ()
SpellCastResult PreCastCheck (Aura *triggeredByAura=nullptr)
void Prepare ()
std::pair< float, float > GetMinMaxRange (bool strict)
bool isDelayableNoMore ()
void prepareDataForTriggerSystem ()
void PrepareMasksForProcSystem (uint8 effectMask, uint32 &procAttacker, uint32 &procVictim, WorldObject *caster, WorldObject *target)
void FillTargetMap ()
void SetTargetMap (SpellEffectIndex effIndex, uint32 targetMode, bool targetB, TempTargetingData &targetingData)
bool FillUnitTargets (TempTargetingData &targetingData, SpellTargetingData &data, uint32 i)
bool CheckAndAddMagnetTarget (Unit *unitTarget, SpellEffectIndex effIndex, bool targetB, TempTargetingData &data)
void FilterTargetMap (UnitList &filterUnitList, SpellTargetFilterScheme scheme, uint32 chainTargetCount)
void FillFromTargetFlags (TempTargetingData &targetingData, SpellEffectIndex effIndex)
void FillAreaTargets (UnitList &targetUnitMap, float radius, float cone, SpellNotifyPushType pushType, SpellTargets spellTargets, WorldObject *originalCaster=nullptr)
Fill target list by units around (x,y) points at radius distance.
void FillRaidOrPartyTargets (UnitList &targetUnitMap, Unit *member, Unit *center, float radius, bool raid, bool withPets, bool withcaster) const
void FillRaidOrPartyManaPriorityTargets (UnitList &targetUnitMap, Unit *member, Unit *center, float radius, uint32 count, bool raid, bool withPets, bool withCaster)
void FillRaidOrPartyHealthPriorityTargets (UnitList &targetUnitMap, Unit *member, Unit *center, float radius, uint32 count, bool raid, bool withPets, bool withCaster)
Unit * GetPrefilledUnitTargetOrUnitTarget (SpellEffectIndex effIndex) const
void GetSpellRangeAndRadius (SpellEffectIndex effIndex, float &radius, bool targetB, uint32 &effectChainTarget)
float GetCone ()
void AddUnitTarget (Unit *target, uint8 effectMask, CheckException exception=EXCEPTION_NONE)
void AddGOTarget (GameObject *target, uint8 effectMask)
void AddCorpseTarget (Corpse *target, uint8 effectMask)
void AddItemTarget (Item *item, uint8 effectMask)
void AddDestExecution (SpellEffectIndex effIndex)
void DoAllEffectOnTarget (TargetInfo *target)
void HandleImmediateEffectExecution (TargetInfo *target)
void InitializeDamageMultipliers ()
void ResetEffectDamageAndHeal ()
void DoSpellHitOnUnit (Unit *unit, uint32 effectMask, TargetInfo *target, bool isReflected=true)
void DoAllTargetlessEffects (bool dest)
void DoAllEffectOnTarget (GOTargetInfo *target)
void DoAllEffectOnTarget (ItemTargetInfo *target)
void DoAllEffectOnTarget (CorpseTargetInfo *target)
bool IsAliveUnitPresentInTargetList ()
bool IsValidDeadOrAliveTarget (Unit const *unit) const
SpellCastResult CanOpenLock (SpellEffectIndex effIndex, uint32 lockid, SkillType &skillId, int32 &reqSkillValue, int32 &skillValue)
void ProcSpellAuraTriggers ()
bool CanExecuteTriggersOnHit (uint8 effMask, SpellEntry const *triggeredByAura, bool auraTarget) const
uint64 CalculateDelayMomentForDst () const
bool CanSpellDiminish () const
Static Protected Member Functions
static void CheckSpellScriptTargets (SQLMultiStorage::SQLMSIteratorBounds< SpellTargetEntry > &bounds, UnitList &tempTargetUnitMap, UnitList &targetUnitMap, SpellEffectIndex effIndex)
Protected Attributes
Unit * m_caster
Item * m_CastItem
bool m_itemCastSpell
ObjectGuid m_forwardedCastItemGuid
ObjectGuid m_originalCasterGUID
Unit * m_originalCaster
SpellSchoolMask m_spellSchoolMask
WeaponAttackType m_attackType
uint32 m_powerCost
int32 m_casttime
int32 m_duration
bool m_reflectable
uint8 m_spellFlags
bool m_autoRepeat
float m_maxRange
uint8 m_runesState
uint8 m_runesStateAfterCast
uint8 m_delayAtDamageCount
uint64 m_delayStart
uint64 m_delayMoment
uint32 m_travellingStart
bool m_referencedFromCurrentSpell
bool m_executedCurrently
bool m_needSpellLog
uint8 m_applyMultiplierMask
float m_damageMultipliers [3]
Unit * unitTarget
Item * itemTarget
GameObject * gameObjTarget
Corpse * corpseTarget
SpellAuraHolder * m_spellAuraHolder
int32 damage
WorldObject * m_eventTarget
int32 m_damage
int32 m_absorb
int32 damagePerEffect [MAX_EFFECT_INDEX]
int32 m_damagePerEffect [MAX_EFFECT_INDEX]
int32 m_healing
int32 m_healingPerEffect [MAX_EFFECT_INDEX]
int32 m_healthLeech
bool m_canTrigger
uint8 m_negativeEffectMask
TargetList m_UniqueTargetInfo
GOTargetList m_UniqueGOTargetInfo
ItemTargetList m_UniqueItemInfo
uint32 m_targetlessMask
DestTargetInfo m_destTargetInfo
CorpseTargetList m_uniqueCorpseTargetInfo
uint32 m_partialApplicationMask
SpellInfoList m_TriggerSpells
SpellInfoList m_preCastSpells
uint64 m_scriptValue
SpellScript * m_spellScript
AuraScript * m_auraScript
int32 m_effectTriggerChance [MAX_EFFECT_INDEX]
uint32 m_spellState
uint32 m_timer
uint32 m_creationTime
bool m_updated
float m_castPositionX
float m_castPositionY
float m_castPositionZ
float m_castOrientation
uint32 m_affectedTargetCount
uint32 m_chainTargetCount [MAX_EFFECT_INDEX]
float m_jumpRadius
SpellTargetFilterScheme m_filteringScheme [MAX_EFFECT_INDEX][2]
std::set< Aura * > m_procOnceHolder
EffectSkillInfo m_effectSkillInfo [MAX_EFFECT_INDEX]
SpellEntry const * m_triggeredByAuraSpell
SpellEvent * m_spellEvent
Private Attributes
SpellLog m_spellLog
uint32 m_param1
uint32 m_param2
bool m_overrideSpeed
float m_overridenSpeed
WorldObject * m_trueCaster
Friends
struct MaNGOS::SpellNotifierPlayer
struct MaNGOS::SpellNotifierCreatureAndPlayer
void Unit::SetCurrentCastedSpell (Spell *pSpell)
Detailed Description
Definition at line 398 of file Spell.h.
Member Typedef Documentation
CorpseTargetList
typedef std::list<CorpseTargetInfo> Spell::CorpseTargetList
Definition at line 815 of file Spell.h.
CreatureSummonPositions
typedef std::vector<CreaturePosition> Spell::CreatureSummonPositions
Definition at line 594 of file Spell.h.
GOTargetList
typedef std::list<GOTargetInfo> Spell::GOTargetList
Definition at line 813 of file Spell.h.
ItemTargetList
typedef std::list<ItemTargetInfo> Spell::ItemTargetList
Definition at line 814 of file Spell.h.
SpellInfoList
typedef std::list<SpellEntry const*> Spell::SpellInfoList protected
Definition at line 1041 of file Spell.h.
TargetList
typedef std::list<TargetInfo> Spell::TargetList
Definition at line 812 of file Spell.h.
Constructor & Destructor Documentation
Spell()
Spell::Spell (WorldObject * caster, SpellEntry const * info, uint32 triggeredFlags, ObjectGuid originalCasterGUID = ObjectGuid(), SpellEntry const * triggeredBy = nullptr)
Definition at line 421 of file Spell.cpp.
References SpellEntry::Attributes, SpellEntry::CalculateSimpleValue(), CLASSMASK_WAND_USERS, CleanupTargetList(), corpseTarget, damagePerEffect, SpellEntry::EffectChainTarget, SpellTargetingData::filteringScheme, gameObjTarget, Unit::getClassMask(), Unit::GetControllingPlayer(), Map::GetCurrentMSTime(), Map::GetDifficulty(), SpellTargetMgr::GetJumpRadius(), WorldObject::GetMap(), Object::GetObjectGuid(), Unit::GetRangedDamageSchoolMask(), GetSpellEntryByDifficulty(), GetSpellSchoolMask(), SpellTargetMgr::GetSpellTargetingData(), Object::GetTypeId(), GetWeaponAttackType(), SpellEntry::HasAttribute(), SpellEntry::Id, SpellLog::Initialize(), IsAutoRepeatRangedSpell(), Map::IsDungeon(), IsIgnoreRootSpell(), Object::IsInWorld(), Map::IsRaid(), IsReflectableSpell(), itemTarget, SQLStorage::LookupEntry(), m_affectedTargetCount, m_applyMultiplierMask, m_attackType, m_autoRepeat, m_cast_count, m_caster, m_CastItem, m_castPositionX, m_castPositionY, m_castPositionZ, m_casttime, m_chainTargetCount, m_channelOnly, m_clientCast, m_creationTime, m_currentBasePoints, m_delayAtDamageCount, m_delayStart, m_doNotProc, m_duration, m_effectTriggerChance, m_eventTarget, m_executedCurrently, m_filteringScheme, m_glyphIndex, m_healthLeech, m_hideInCombatLog, m_ignoreCasterAuraState, m_ignoreCastTime, m_ignoreConcurrentCasts, m_ignoreCooldowns, m_ignoreCosts, m_ignoreGCD, m_ignoreHitResult, m_ignoreOwnerLevel, m_ignoreRoot, m_ignoreUnattackableTarget, m_ignoreUnselectableTarget, m_IsTriggeredSpell, m_itemCastSpell, m_jumpRadius, m_maxRange, m_needAliveTargetMask, m_needSpellLog, m_notifyAI, m_originalCasterGUID, m_overrideSpeed, m_petCast, m_powerCost, m_preCastSpells, m_referencedFromCurrentSpell, m_reflectable, m_resetLeash, m_runesState, m_runesStateAfterCast, m_scriptValue, m_spellAuraHolder, m_spellFlags, m_spellInfo, m_spellLog, m_spellSchoolMask, m_spellState, m_targetlessMask, m_timer, m_travellingStart, m_triggerAutorepeat, m_triggeredByAuraSpell, m_triggeredBySpellInfo, m_TriggerSpells, m_trueCaster, m_updated, MANGOS_ASSERT, MAX_EFFECT_INDEX, SpellEntry::MaxAffectedTargets, OnInit(), RANGED_ATTACK, SPELL_ATTR_DO_NOT_DISPLAY, SPELL_ATTR_DO_NOT_LOG, SPELL_ATTR_EX4_ALLOW_CAST_WHILE_CASTING, SPELL_ATTR_EX5_IGNORE_CASTER_REQUIREMENTS, SPELL_ATTR_EX6_ORIGINATE_FROM_CONTROLLER, SPELL_FLAG_NORMAL, SPELL_STATE_CREATED, SpellEntry::SpellDifficultyId, sSpellTemplate, TRIGGERED_AUTOREPEAT, TRIGGERED_CHANNEL_ONLY, TRIGGERED_DO_NOT_PROC, TRIGGERED_DO_NOT_RESET_LEASH, TRIGGERED_HIDE_CAST_IN_COMBAT_LOG, TRIGGERED_IGNORE_CASTER_AURA_STATE, TRIGGERED_IGNORE_COOLDOWNS, TRIGGERED_IGNORE_COSTS, TRIGGERED_IGNORE_CURRENT_CASTED_SPELL, TRIGGERED_IGNORE_GCD, TRIGGERED_IGNORE_HIT_CALCULATION, TRIGGERED_IGNORE_UNATTACKABLE_FLAG, TRIGGERED_IGNORE_UNSELECTABLE_FLAG, TRIGGERED_INSTANT_CAST, TRIGGERED_NORMAL_COMBAT_CAST, TRIGGERED_OLD_TRIGGERED, TRIGGERED_PET_CAST, TYPEID_PLAYER, unitTarget, and UpdateOriginalCasterPointer().
Referenced by CastTriggerSpells(), EffectEnchantItemTmp(), and ProcSpellAuraTriggers().
~Spell()
Spell::~Spell () virtual
Definition at line 565 of file Spell.cpp.
References m_CastItem, and Item::SetUsedInSpell().
Member Function Documentation
_handle_finish_phase()
void Spell::_handle_finish_phase ()
Definition at line 3959 of file Spell.cpp.
References Unit::DoExtraAttacks(), Unit::GetVictim(), IsSpellHaveEffect(), m_caster, Unit::m_extraAttacks, m_needSpellLog, m_spellInfo, m_spellLog, SpellLog::SendToSet(), and SPELL_EFFECT_ADD_EXTRA_ATTACKS.
Referenced by handle_delayed(), and handle_immediate().
_handle_immediate_phase()
void Spell::_handle_immediate_phase ()
Definition at line 3901 of file Spell.cpp.
References BASE_ATTACK, DoAllEffectOnTarget(), DoAllTargetlessEffects(), GetCastTime(), Object::GetObjectGuid(), HandleImmediateEffectExecution(), HandleThreatSpells(), SpellEntry::HasAttribute(), Unit::hasOffhandWeaponForAttack(), IsChanneledSpell(), IsDelayedSpell(), IsMeleeAttackResetSpell(), m_caster, m_duration, m_spellInfo, m_spellState, m_trueCaster, m_UniqueItemInfo, m_UniqueTargetInfo, OFF_ATTACK, ProcSpellAuraTriggers(), Unit::resetAttackTimer(), SendChannelStart(), SPELL_ATTR_EX2_DO_NOT_RESET_COMBAT_TIMERS, SPELL_ATTR_EX6_DOESNT_RESET_SWING_TIMER_IF_INSTANT, SPELL_ATTR_EX7_RESET_SWING_TIMER_AT_SPELL_START, SPELL_STATE_CHANNELING, SPELL_STATE_LANDING, and TakeCastItem().
Referenced by cast().
AddCorpseTarget()
void Spell::AddCorpseTarget (Corpse * target, uint8 effectMask) protected
Definition at line 1208 of file Spell.cpp.
References Spell::CorpseTargetInfo::corpseGUID, Spell::CorpseTargetInfo::effectMask, Object::GetObjectGuid(), m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_uniqueCorpseTargetInfo, and SpellEntry::Targets.
Referenced by FillTargetMap().
AddDestExecution()
void Spell::AddDestExecution (SpellEffectIndex effIndex) protected
Definition at line 1249 of file Spell.cpp.
References CalculateDelayMomentForDst(), Spell::DestTargetInfo::effectMask, GetSpellSpeed(), m_delayMoment, m_destTargetInfo, m_partialApplicationMask, and Spell::DestTargetInfo::timeDelay.
Referenced by FillTargetMap().
AddGOTarget()
void Spell::AddGOTarget (GameObject * target, uint8 effectMask) protected
Definition at line 1154 of file Spell.cpp.
References DIST_CALC_NONE, Spell::GOTargetInfo::effectMask, GetAffectiveCasterObject(), WorldObject::GetDistance(), SpellCastTargets::getElevation(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellCastTargets::getSpeed(), GetSpellSpeed(), m_delayMoment, SpellCastTargets::m_targetMask, m_targets, m_UniqueGOTargetInfo, Spell::GOTargetInfo::processed, TARGET_FLAG_GAMEOBJECT, Spell::GOTargetInfo::targetGUID, and Spell::GOTargetInfo::timeDelay.
Referenced by FillTargetMap().
AddItemTarget()
void Spell::AddItemTarget (Item * item, uint8 effectMask) protected
Definition at line 1229 of file Spell.cpp.
References Spell::ItemTargetInfo::effectMask, Spell::ItemTargetInfo::item, and m_UniqueItemInfo.
Referenced by FillTargetMap().
AddPrecastSpell() [1/2]
void Spell::AddPrecastSpell (SpellEntry const * spellInfo) inline
Definition at line 731 of file Spell.h.
References m_preCastSpells.
Referenced by cast(), LockAndLoadTrigger::OnCast(), Blizzard::OnCast(), and FingersOfFrostIgnore::OnCast().
AddPrecastSpell() [2/2]
void Spell::AddPrecastSpell (uint32 spellId)
Definition at line 5459 of file Spell.cpp.
References SpellEntry::Id, SQLStorage::LookupEntry(), m_preCastSpells, m_spellInfo, sLog, and sSpellTemplate.
AddTriggeredSpell() [1/2]
void Spell::AddTriggeredSpell (SpellEntry const * spellInfo) inline
Definition at line 730 of file Spell.h.
References m_TriggerSpells.
Referenced by cast().
AddTriggeredSpell() [2/2]
void Spell::AddTriggeredSpell (uint32 spellId)
Definition at line 5446 of file Spell.cpp.
References SpellEntry::Id, SQLStorage::LookupEntry(), m_spellInfo, m_TriggerSpells, sLog, and sSpellTemplate.
AddUnitTarget()
void Spell::AddUnitTarget (Unit * target, uint8 effectMask, CheckException exception = EXCEPTION_NONE) protected
Definition at line 973 of file Spell.cpp.
References Unit::ApplyDiminishingToDuration(), BASE_ATTACK, Unit::CalculateAuraDuration(), CalculateSpellDuration(), CanSpellDiminish(), Spell::TargetInfo::diminishDuration, Spell::TargetInfo::diminishGroup, DIMINISHING_LEVEL_1, DIMINISHING_LEVEL_IMMUNE, DIMINISHING_NONE, Spell::TargetInfo::diminishLevel, DIST_CALC_NONE, Spell::TargetInfo::effectDuration, Spell::TargetInfo::effectHitMask, Spell::TargetInfo::effectMask, Spell::TargetInfo::effectMaskProcessed, EXCEPTION_MAGNET, Spell::TargetInfo::executionless, GetAffectiveCasterObject(), GetAffectiveCasterOrOwner(), GetAuraEffectMask(), Unit::GetDiminishing(), GetDiminishingReturnsGroupForSpell(), WorldObject::GetDistance(), SpellCastTargets::getElevation(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellCastTargets::getSpeed(), GetSpellSpeed(), SpellTargetMgr::GetSpellTargetingData(), Map::GetWorldObject(), SpellEntry::HasAttribute(), Spell::TargetInfo::heartbeatResistChance, SpellEntry::Id, Spell::TargetInfo::initialDelay, IsAuraApplyEffects(), Spell::TargetInfo::isCrit, Unit::IsImmuneToSpellEffect(), ObjectGuid::IsUnit(), m_auraScript, m_caster, m_CastItem, m_delayMoment, m_ignoreHitResult, m_IsTriggeredSpell, m_originalCasterGUID, m_partialApplicationMask, m_reflectable, m_spellFlags, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_triggeredByAuraSpell, m_trueCaster, m_UniqueTargetInfo, Spell::TargetInfo::magnet, MAX_EFFECT_INDEX, Spell::TargetInfo::missCondition, PROC_EX_REFLECT, PROC_FLAG_NONE, PROC_FLAG_TAKE_HARMFUL_SPELL, Unit::ProcDamageAndSpell(), Spell::TargetInfo::processed, Spell::TargetInfo::procReflect, ProcReflectProcs(), Spell::TargetInfo::reflectResult, SPELL_ATTR_EX4_BOUNCY_CHAIN_MISSILES, SPELL_ATTR_EX4_NO_PARTIAL_IMMUNITY, SPELL_ATTR_EX7_REFLECTION_ONLY_DEFENDS, SPELL_FLAG_REFLECTED, SPELL_MISS_IMMUNE, SPELL_MISS_NONE, SPELL_MISS_REFLECT, Unit::SpellHitResult(), TARGET_FLAG_UNIT, TARGET_TYPE_SPECIAL_DEST, Spell::TargetInfo::targetGUID, and Spell::TargetInfo::timeDelay.
Referenced by FillUnitTargets().
CalculateDelayMomentForDst()
uint64 Spell::CalculateDelayMomentForDst () const protected
Definition at line 1265 of file Spell.cpp.
References GetAffectiveCasterObject(), SpellCastTargets::getDestination(), Position::GetDistance(), Position::GetDistance2d(), SpellCastTargets::getElevation(), WorldObject::GetPosition(), SpellCastTargets::getSource(), SpellCastTargets::getSpeed(), m_spellInfo, SpellCastTargets::m_targetMask, m_targets, SpellEntry::speed, and TARGET_FLAG_DEST_LOCATION.
Referenced by AddDestExecution(), and RecalculateDelayMomentForDest().
CalculatePowerCost()
uint32 Spell::CalculatePowerCost (SpellEntry const * spellInfo, Unit * caster, Spell * spell = nullptr, Item * castItem = nullptr, bool finalUse = false) static
Definition at line 7514 of file Spell.cpp.
References SpellEntry::baseLevel, DEBUG_LOG, Unit::GetAttackTime(), Unit::GetCreateHealth(), Unit::GetCreateMana(), GetFirstSchoolInMask(), Object::GetFloatValue(), Unit::GetHealth(), Object::GetInt32Value(), Unit::GetLevel(), Unit::GetMaxPower(), Unit::GetPower(), WorldObject::GetSpellModOwner(), Unit::GetSpellRank(), GetSpellSchoolMask(), SpellEntry::HasAttribute(), SpellEntry::Id, m_spellSchoolMask, SpellEntry::manaCost, SpellEntry::ManaCostPercentage, SpellEntry::manaCostPerlevel, MAX_POWERS, OFF_ATTACK, POWER_ENERGY, POWER_FOCUS, POWER_HAPPINESS, POWER_HEALTH, POWER_MANA, POWER_RAGE, POWER_RUNE, POWER_RUNIC_POWER, SpellEntry::powerType, GtNPCManaCostScalerEntry::ratio, sGtNPCManaCostScalerStore, sLog, SPELL_ATTR_EX4_WEAPON_SPEED_COST_SCALING, SPELL_ATTR_EX_USE_ALL_MANA, SPELL_ATTR_SCALES_WITH_CREATURE_LEVEL, SpellEntry::spellLevel, SPELLMOD_COST, UNIT_FIELD_POWER_COST_MODIFIER, and UNIT_FIELD_POWER_COST_MULTIPLIER.
Referenced by UnitAI::AddMainSpell(), boss_selin_fireheartAI::boss_selin_fireheartAI(), CheckPower(), and boss_curatorAI::ExecuteAction().
CalculateSpellEffectDamage()
int32 Spell::CalculateSpellEffectDamage (Unit * unitTarget, int32 damage)
Definition at line 7485 of file Spell.cpp.
References damage, SpellEntry::DmgClass, Object::IsGameObject(), m_attackType, m_caster, m_spellInfo, m_spellSchoolMask, m_trueCaster, Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), SPELL_DAMAGE_CLASS_MAGIC, SPELL_DAMAGE_CLASS_MELEE, SPELL_DAMAGE_CLASS_NONE, SPELL_DAMAGE_CLASS_RANGED, SPELL_DIRECT_DAMAGE, Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), and unitTarget.
Referenced by EffectPowerBurn(), EffectSchoolDMG(), and EffectWeaponDmg().
CalculateSpellEffectValue()
int32 Spell::CalculateSpellEffectValue (SpellEffectIndex i, Unit * target, bool maximum = false, bool finalUse = true) inline
Definition at line 570 of file Spell.h.
References WorldObject::CalculateSpellEffectValue(), m_currentBasePoints, m_spellInfo, and m_trueCaster.
Referenced by CanOpenLock(), CheckCast(), CheckItems(), EffectSchoolDMG(), EffectWeaponDmg(), HandleEffect(), PrayerOfMending::OnCheckCast(), CorpseExplosionDK::OnEffectExecute(), ExplodeGhoulCorpseExplosion::OnEffectExecute(), WarriorDevastate::OnEffectExecute(), ScourgeStrike::OnHit(), WildGrowth::OnInit(), DivineStorm::OnSuccessfulFinish(), and ProcessAOECaps().
CanAutoCast()
bool Spell::CanAutoCast (Unit * target)
Definition at line 7328 of file Spell.cpp.
References CheckPetCast(), SpellEntry::Effect, Unit::GetAura(), Unit::HasAura(), SpellEntry::Id, IsAreaAuraEffect(), m_spellInfo, MAX_EFFECT_INDEX, SPELL_CAST_OK, SPELL_EFFECT_APPLY_AURA, SPELL_FAILED_UNIT_NOT_INFRONT, and SpellEntry::StackAmount.
Referenced by PetAI::UpdateAI().
CanBeInterrupted()
bool Spell::CanBeInterrupted () const inline
Definition at line 748 of file Spell.h.
References m_spellState, SPELL_STATE_CHANNELING, and SPELL_STATE_DELAYED.
Referenced by IsInterruptible().
cancel()
void Spell::cancel ()
Definition at line 3421 of file Spell.cpp.
References finish(), Object::GetObjectGuid(), WorldObject::GetSpellModOwner(), ObjectAccessor::GetUnit(), SpellEntry::HasAttribute(), SpellEntry::Id, Unit::IsAlive(), IsChanneledSpell(), m_autoRepeat, m_caster, m_spellInfo, m_spellState, m_UniqueTargetInfo, m_usedAuraCharges, Unit::RemoveAurasByCasterSpell(), Unit::RemoveCreature(), Unit::RemoveDynObject(), Unit::RemoveGameObject(), WorldObject::RemoveSpellCooldown(), WorldObject::ResetGCD(), SendCastResult(), SendChannelUpdate(), SendInterrupted(), sLog, SPELL_ATTR_COOLDOWN_ON_EVENT, SPELL_FAILED_INTERRUPTED, SPELL_MISS_NONE, SPELL_STATE_CASTING, SPELL_STATE_CHANNELING, SPELL_STATE_CREATED, SPELL_STATE_FINISHED, SPELL_STATE_LANDING, SPELL_STATE_TARGETING, and SPELL_STATE_TRAVELING.
Referenced by SpellEvent::Abort(), cast(), SpellEvent::Execute(), PlayerbotAI::HandleBotOutgoingPacket(), Unit::InterruptSpell(), update(), and SpellEvent::~SpellEvent().
CanExecuteTriggersOnHit()
bool Spell::CanExecuteTriggersOnHit (uint8 effMask, SpellEntry const * triggeredByAura, bool auraTarget) const protected
Definition at line 8810 of file Spell.cpp.
References SpellEntry::HasAttribute(), MAX_EFFECT_INDEX, and SPELL_ATTR_EX4_CLASS_TRIGGER_ONLY_ON_TARGET.
Referenced by ProcSpellAuraTriggers().
CanOpenLock()
SpellCastResult Spell::CanOpenLock (SpellEffectIndex effIndex, uint32 lockid, SkillType & skillId, int32 & reqSkillValue, int32 & skillValue) protected
Definition at line 8600 of file Spell.cpp.
References CalculateSpellEffectValue(), SpellEntry::EffectMiscValue, Object::GetEntry(), SpellCastTargets::getGOTarget(), Unit::GetLevel(), SpellEntry::Id, LockEntry::Index, Object::IsPlayer(), LOCK_KEY_ITEM, LOCK_KEY_SKILL, LOCKTYPE_DISARM_TRAP, m_CastItem, m_currentBasePoints, m_spellInfo, m_targets, m_trueCaster, LockEntry::Skill, SKILL_NONE, SkillByLockType(), SkillLineAbilityEntry::skillId, sLockStore, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_LOW_CASTLEVEL, sSpellMgr, and LockEntry::Type.
Referenced by CheckCast().
CanSpellDiminish()
bool Spell::CanSpellDiminish () const protected
Definition at line 1794 of file Spell.cpp.
References IsCreatureDRSpell(), Unit::IsPlayerControlled(), m_caster, and m_spellInfo.
Referenced by AddUnitTarget().
cast()
SpellCastResult Spell::cast (bool skipCheck = false)
Definition at line 3485 of file Spell.cpp.
References _handle_immediate_phase(), ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, AddPrecastSpell(), AddTriggeredSpell(), Unit::AI(), AURA_INTERRUPT_FLAG_ACTION_LATE, CalculateSpellDuration(), Unit::CanAttack(), cancel(), Unit::CanEnterCombat(), SpellEntry::Category, WorldObject::CheckAndIncreaseCastCounter(), CheckCast(), WorldObject::DecreaseCastCounter(), SpellEntry::Effect, EFFECT_INDEX_0, FillTargetMap(), finish(), FORM_CAT, Unit::GetAura(), Unit::GetCharmer(), Unit::GetCombatManager(), Map::GetCurrentMSTime(), Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), Unit::GetPet(), Unit::GetShapeshiftForm(), WorldObject::GetSpellModOwner(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), SpellCastTargets::getUnitTargetGuid(), handle_immediate(), SpellEntry::HasAttribute(), Unit::HasAura(), Unit::hasOffhandWeaponForAttack(), Unit::HasTarget(), SpellEntry::Id, InitializeDamageMultipliers(), Object::IsCreature(), IsDelayedSpell(), Object::IsGameObject(), Object::IsPlayer(), Unit::IsPlayerControlled(), IsPositiveEffectMask(), Unit::IsVisibleForOrDetect(), m_attackType, m_auraScript, m_caster, m_CastItem, m_duration, m_IsTriggeredSpell, m_notifyAI, m_spellInfo, m_spellState, m_targets, m_triggeredByAuraSpell, m_trueCaster, m_UniqueTargetInfo, SpellEntry::Mechanic, MECHANIC_BANDAGE, MECHANIC_SHIELD, OnCast(), UnitAI::OnSpellCooldownAdded(), PET_SAVE_NOT_IN_SLOT, PROC_EX_CAST_END, PROC_EX_NORMAL_HIT, Unit::ProcDamageAndSpell(), Unit::RemoveAurasOnCast(), Unit::RemoveSpellsCausingAura(), roll_chance_i(), SendCastResult(), SendSpellCooldown(), SendSpellGo(), SetDelayStart(), SetExecutedCurrently(), Unit::SetInCombatWithVictim(), Unit::SetInFront(), SetSpellStartTravelling(), SpellModRAII::SetSuccess(), sLog, SPELL_ATTR_EX2_NO_INITIAL_THREAT, SPELL_ATTR_EX2_NOT_AN_ACTION, SPELL_ATTR_EX5_AI_DOESNT_FACE_TARGET, SPELL_ATTR_EX_DISMISS_PET_FIRST, SPELL_ATTR_EX_NO_THREAT, SPELL_ATTR_EX_THREAT_ONLY_ON_MISS, SPELL_AURA_HASTE_SPELLS, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_CAST_OK, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_FAILED_ERROR, SPELL_STATE_CHANNELING, SPELL_STATE_FINISHED, SPELL_STATE_TRAVELING, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellEntry::SpellVisual, StopCast(), TakeAmmo(), TakePower(), TakeReagents(), CombatManager::TriggerCombatTimer(), TYPEID_PLAYER, Player::UpdateAchievementCriteria(), UpdatePointers(), and SpellCastTargets::updateTradeSlotItem().
Referenced by Unit::AttackerStateUpdate(), Prepare(), and update().
CastPreCastSpells()
void Spell::CastPreCastSpells (Unit * target)
Definition at line 5481 of file Spell.cpp.
References Unit::CastSpell(), m_caster, m_CastItem, m_preCastSpells, and TRIGGERED_OLD_TRIGGERED.
Referenced by DoSpellHitOnUnit().
CastTriggerSpells()
void Spell::CastTriggerSpells ()
Definition at line 5472 of file Spell.cpp.
References m_originalCasterGUID, m_targets, m_TriggerSpells, m_trueCaster, Spell(), SpellStart(), and TRIGGERED_OLD_TRIGGERED.
Referenced by finish().
CheckAndAddMagnetTarget()
bool Spell::CheckAndAddMagnetTarget (Unit * unitTarget, SpellEffectIndex effIndex, bool targetB, TempTargetingData & data) protected
Definition at line 1898 of file Spell.cpp.
References Spell::TempTargetingData::data, m_caster, m_targets, Spell::TempTargetingData::magnet, Unit::SelectMagnetTarget(), SpellCastTargets::setUnitTarget(), and Spell::TempTargetData::tmpUnitList.
Referenced by SetTargetMap().
CheckCast()
SpellCastResult Spell::CheckCast (bool strict)
Definition at line 5496 of file Spell.cpp.
References AREA_LOCKSTATUS_OK, SpellEntry::AreaGroupId, SpellEntry::Attributes, AURA_STATE_FROZEN, PathFinder::calculate(), Aura::CalculateAuraEffectValue(), CalculateSpellEffectValue(), WorldObject::CanAssistSpell(), Unit::CanAssistSpell(), Unit::CanAttack(), WorldObject::CanAttackSpell(), VehicleInfo::CanBoard(), CanOpenLock(), Player::CanTameExoticPets(), SpellEntry::casterAuraSpell, SpellEntry::CasterAuraState, SpellEntry::CasterAuraStateNot, CheckCasterAuras(), CheckItems(), CheckPower(), CheckRange(), CheckTarget(), CheckTargetCreatureType(), CLASS_HUNTER, CLASS_WARLOCK, CLASS_WARRIOR, CONFIG_BOOL_VMAP_INDOOR_CHECK, VMAP::VMapFactory::createOrGetVMapManager(), CREATURE_LOOT_STATUS_LOOTED, CREATURE_TYPE_UNDEAD, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_MASK_ALL, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectItemType, SpellEntry::EffectMechanic, SpellEntry::EffectMiscValue, SpellEntry::EffectMiscValueB, SpellEntry::EffectRadiusIndex, SpellEntry::EffectTriggerSpell, EQUIP_ERR_OK, EXCEPTION_NONE, SpellEntry::excludeCasterAuraSpell, SpellEntry::excludeTargetAuraSpell, FillAreaTargets(), ChatHandler::FindCommand(), Unit::FindGuardianWithEntry(), ObjectAccessor::FindPlayer(), GAMEOBJECT_FLAGS, GetAffectiveCaster(), WorldObject::GetAngle(), Player::GetAreaTriggerLockStatus(), Unit::GetAurasByType(), Unit::GetBeneficiaryPlayer(), Player::GetBoundInstance(), SpellAuraHolder::GetCasterGuid(), GetCastingObject(), Unit::GetChannelObject(), Unit::GetCharm(), GetCheckCastEffectMask(), GetCheckCastSelfEffectMask(), Unit::getClass(), Unit::GetCombatReach(), Unit::GetComboTargetGuid(), Map::GetCorpse(), SpellCastTargets::getCorpseTargetGuid(), Creature::GetCreatureInfo(), Unit::GetCreatureType(), Pet::GetCurrentFoodBenefitLevel(), SpellCastTargets::getDestination(), Map::GetDifficulty(), Object::GetEntry(), GetErrorAtShapeshiftedCast(), WorldObject::GetFirstCollisionPosition(), SpellCastTargets::getGOTarget(), Unit::GetHealth(), ObjectMgr::GetInstanceTemplate(), SpellCastTargets::getItemTarget(), SpellCastTargets::getItemTargetGuid(), Unit::GetLevel(), Creature::GetLootStatus(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMaxHealth(), Unit::GetMountID(), Object::GetObjectGuid(), Unit::GetOwner(), Unit::GetOwnerGuid(), PathFinder::getPathType(), Unit::GetPet(), Map::GetPet(), Unit::GetPetGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetPowerType(), GetPrefilledUnitTargetOrUnitTarget(), Item::GetProto(), ObjectGuid::GetRawValue(), WorldSession::GetRecruitingFriendId(), CreatureInfo::GetRequiredLootSkill(), Player::GetSelectionGuid(), Player::GetSession(), Unit::GetShapeshiftForm(), Unit::GetSpellAuraHolderMap(), GetSpellMaxRange(), SpellAuraHolder::GetSpellProto(), GetSpellRadius(), Unit::GetTarget(), WorldObject::GetTerrain(), Unit::GetTotemGuid(), WorldObject::GetTransportInfo(), Object::GetTypeId(), Map::GetUnit(), SpellCastTargets::getUnitTarget(), Unit::GetVehicleInfo(), Map::GetVisibilityDistance(), WorldObject::GetZoneAndAreaId(), WorldObject::GetZoneId(), GO_FLAG_IN_USE, Unit::HasAffectedAura(), HasAreaAuraEffect(), SpellEntry::HasAttribute(), Unit::HasAura(), Unit::HasAuraState(), Unit::HasAuraStateForCaster(), Unit::HasAuraType(), Unit::HasAuraTypeWithMiscvalue(), Unit::HasCharm(), Unit::HasCharmer(), Object::HasFlag(), WorldObject::HasGCD(), WorldObject::HasInArc(), Unit::hasMainhandWeapon(), TransportBase::HasOnBoard(), TransportInfo::HasOnBoard(), Unit::HasOverrideScript(), Unit::HasStealthAura(), Unit::hasUnitState(), Pet::HaveInDiet(), SpellEntry::Id, IGNORE_UNIT_COMBAT_STATE, IGNORE_UNIT_TARGET_NON_FROZEN, IGNORE_UNIT_TARGET_STATE, irand(), Unit::IsAboveGround(), Unit::IsAlive(), IsAreaOfEffectSpell(), IsAuraApplyEffect(), IsAuraApplyEffects(), WorldObject::IsBoarded(), Object::IsCreature(), Unit::IsDead(), IsDeathOnlySpell(), MapEntry::IsDungeon(), CreatureInfo::IsExotic(), WorldObject::IsFacingTargetsBack(), WorldObject::IsFacingTargetsFront(), SpellEntry::IsFitToFamily(), Unit::IsFlying(), Object::IsGameObject(), IsIgnoreLosSpellCast(), IsIgnoreLosSpellEffect(), Unit::IsIgnoreUnitState(), Creature::IsImmuneToSpell(), Unit::IsInCombat(), Unit::IsInDisallowedMountForm(), Unit::IsInGroup(), Player::IsInGroup(), Player::IsInHighLiquid(), Unit::IsInWater(), Object::IsInWorld(), VMAP::IVMapManager::isLineOfSightCalcEnabled(), Map::IsMountAllowed(), Unit::IsMounted(), IsNonCombatSpell(), Unit::IsNoWeaponShapeShift(), IsOnlySelfTargeting(), TransportInfo::IsOnVehicle(), TerrainInfo::IsOutdoors(), IsPassiveSpell(), Creature::IsPet(), Object::IsPlayer(), Unit::IsPlayerControlled(), IsPositiveEffectMask(), IsPositiveSpell(), IsSimilarExistingAuraStronger(), IsSpellDoNotReportFailure(), IsSpellHaveAura(), IsSpellHaveEffect(), WorldObject::IsSpellReady(), IsSpellWithCasterSourceTargetsOnly(), IsSpellWithScriptUnitTarget(), Unit::IsStandState(), CreatureInfo::isTameable(), Unit::IsTaxiFlying(), Unit::IsTrivialForTarget(), Object::IsUnit(), Unit::IsVehicle(), Unit::IsVisibleForOrDetect(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), ITEM_DYNFLAG_UNLOCKED, ITEM_FIELD_FLAGS, ItemPrototype::ItemLevel, ItemPrototype::ItemLimitCategory, InstanceTemplate::levelMax, InstanceTemplate::levelMin, SQLStorage::LookupEntry(), m_auraScript, m_caster, m_CastItem, m_channelOnly, m_clientCast, m_effectSkillInfo, m_eventTarget, m_ignoreCooldowns, m_ignoreCosts, m_ignoreGCD, m_ignoreRoot, m_IsTriggeredSpell, m_param1, m_partialApplicationMask, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_triggeredByAuraSpell, m_triggeredBySpellInfo, m_trueCaster, MAX_EFFECT_INDEX, SpellEntry::MaxTargetLevel, SpellEntry::Mechanic, MOVEFLAG_ONTRANSPORT, NeedsComboPoints(), NULL_BAG, NULL_SLOT, AuraScript::OnAuraValueCalculate(), OnCheckCast(), PATHFIND_NOPATH, PATHFIND_SHORT, PETTAME_ANOTHERSUMMONACTIVE, PETTAME_CANTCONTROLEXOTIC, PETTAME_CREATUREALREADYOWNED, PETTAME_DEAD, PETTAME_NOTDEAD, PETTAME_NOTTAMEABLE, PETTAME_TOOHIGHLEVEL, PETTAME_UNITSCANTTAME, PETTAME_UNKNOWNERROR, CreatureInfo::PickpocketLootId, PLAYER_ALLOW_ONLY_ABILITY, PLAYER_FLAGS, POWER_MANA, PUSH_DEST_CENTER, SpellEntry::rangeIndex, Spell::EffectSkillInfo::reqSkillValue, SpellEntry::RequiresSpellFocus, Player::SendPetTameFailure(), PathFinder::setPathLengthLimit(), SpellCastTargets::setUnitTarget(), sGlyphPropertiesStore, SKILL_HERBALISM, SKILL_MINING, SKILL_NONE, Spell::EffectSkillInfo::skillId, sLog, sMapStore, sObjectMgr, SPELL_ATTR_ALLOW_CAST_WHILE_DEAD, SPELL_ATTR_ALLOW_WHILE_MOUNTED, SPELL_ATTR_ALLOW_WHILE_SITTING, SPELL_ATTR_CANCELS_AUTO_ATTACK_COMBAT, SPELL_ATTR_DO_NOT_SHEATH, SPELL_ATTR_EX2_ALLOW_LOW_LEVEL_BUFF, SPELL_ATTR_EX2_CANNOT_CAST_ON_TAPPED, SPELL_ATTR_EX2_INITIATE_COMBAT_POST_CAST, SPELL_ATTR_EX2_NO_ACTIVE_PETS, SPELL_ATTR_EX3_ALLOW_AURA_WHILE_DEAD, SPELL_ATTR_EX3_ONLY_ON_PLAYER, SPELL_ATTR_EX4_AURA_NEVER_BOUNCES, SPELL_ATTR_EX5_ALWAYS_LINE_OF_SIGHT, SPELL_ATTR_EX5_IMPLIED_TARGETING, SPELL_ATTR_EX5_NOT_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER_CONTROLLED_NPC, SPELL_ATTR_EX5_NOT_ON_TRIVIAL, SPELL_ATTR_EX5_SPELL_HASTE_AFFECTS_PERIODIC, SPELL_ATTR_EX6_CAN_TARGET_UNTARGETABLE, SPELL_ATTR_EX6_IGNORE_PHASE_SHIFT, SPELL_ATTR_EX6_NO_JUMP_PATHING, SPELL_ATTR_EX7_DEBUG_SPELL, SPELL_ATTR_EX7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT, SPELL_ATTR_EX_DISMISS_PET_FIRST, SPELL_ATTR_EX_EXCLUDE_CASTER, SPELL_ATTR_EX_INITIATES_COMBAT_ENABLES_AUTO_ATTACK, SPELL_ATTR_EX_ONLY_PEACEFUL_TARGETS, SPELL_ATTR_EX_TRACK_TARGET_IN_CHANNEL, SPELL_ATTR_IS_ABILITY, SPELL_ATTR_NOT_SHAPESHIFT, SPELL_ATTR_ONLY_INDOORS, SPELL_ATTR_ONLY_OUTDOORS, SPELL_ATTR_ONLY_STEALTHED, SPELL_ATTR_PASSIVE, SPELL_ATTR_SS_FACING_BACK, SPELL_AURA_ALLOW_ONLY_ABILITY, SPELL_AURA_AOE_CHARM, SPELL_AURA_BLOCK_SPELL_FAMILY, SPELL_AURA_CONTROL_VEHICLE, SPELL_AURA_DUMMY, SPELL_AURA_FLY, SPELL_AURA_MIRROR_IMAGE, SPELL_AURA_MOD_CHARM, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_DISARM, SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED, SPELL_AURA_MOD_IGNORE_SHAPESHIFT, SPELL_AURA_MOD_POSSESS, SPELL_AURA_MOD_POSSESS_PET, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_MOD_STUN, SPELL_AURA_MOUNTED, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PREVENT_RESURRECTION, SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS, SPELL_AURA_SPIRIT_OF_REDEMPTION, SPELL_CAST_OK, SPELL_EFFECT_APPLY_GLYPH, SPELL_EFFECT_CHARGE, SPELL_EFFECT_CHARGE_DEST, SPELL_EFFECT_CREATE_ITEM, SPELL_EFFECT_CREATE_PET, SPELL_EFFECT_DISPEL, SPELL_EFFECT_DISTRACT, SPELL_EFFECT_DUMMY, SPELL_EFFECT_FEED_PET, SPELL_EFFECT_HEAL, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_JUMP, SPELL_EFFECT_JUMP_DEST, SPELL_EFFECT_LEAP, SPELL_EFFECT_LEARN_PET_SPELL, SPELL_EFFECT_LEARN_SPELL, SPELL_EFFECT_OPEN_LOCK, SPELL_EFFECT_PICKPOCKET, SPELL_EFFECT_POWER_BURN, SPELL_EFFECT_POWER_DRAIN, SPELL_EFFECT_RESURRECT, SPELL_EFFECT_RESURRECT_NEW, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_SELF_RESURRECT, SPELL_EFFECT_SKINNING, SPELL_EFFECT_STEAL_BENEFICIAL_BUFF, SPELL_EFFECT_SUMMON, SPELL_EFFECT_SUMMON_DEAD_PET, SPELL_EFFECT_SUMMON_PET, SPELL_EFFECT_SUMMON_PLAYER, SPELL_EFFECT_SUMMON_RAF_FRIEND, SPELL_EFFECT_TAMECREATURE, SPELL_EFFECT_TELEPORT_UNITS_FACE_CASTER, SPELL_EFFECT_TRIGGER_SPELL_2, SPELL_FAILED_AFFECTING_COMBAT, SPELL_FAILED_ALREADY_HAVE_CHARM, SPELL_FAILED_ALREADY_HAVE_SUMMON, SPELL_FAILED_ALREADY_OPEN, SPELL_FAILED_AURA_BOUNCED, SPELL_FAILED_BAD_IMPLICIT_TARGETS, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_CANT_BE_CHARMED, SPELL_FAILED_CANT_CAST_ON_TAPPED, SPELL_FAILED_CASTER_AURASTATE, SPELL_FAILED_CASTER_DEAD, SPELL_FAILED_CHARMED, SPELL_FAILED_CHEST_IN_USE, SPELL_FAILED_CUSTOM_ERROR, SPELL_FAILED_CUSTOM_ERROR_65, SPELL_FAILED_DAMAGE_IMMUNE, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_ERROR, SPELL_FAILED_FIZZLE, SPELL_FAILED_FOOD_LOWLEVEL, SPELL_FAILED_HIGHLEVEL, SPELL_FAILED_IMMUNE, SPELL_FAILED_ITEM_GONE, SPELL_FAILED_ITEM_NOT_READY, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_LOW_CASTLEVEL, SPELL_FAILED_LOWLEVEL, SPELL_FAILED_NO_COMBO_POINTS, SPELL_FAILED_NO_EDIBLE_CORPSES, SPELL_FAILED_NO_MOUNTS_ALLOWED, SPELL_FAILED_NO_PET, SPELL_FAILED_NOPATH, SPELL_FAILED_NOT_BEHIND, SPELL_FAILED_NOT_HERE, SPELL_FAILED_NOT_INFRONT, SPELL_FAILED_NOT_KNOWN, SPELL_FAILED_NOT_MOUNTED, SPELL_FAILED_NOT_ON_TAXI, SPELL_FAILED_NOT_ON_TRANSPORT, SPELL_FAILED_NOT_READY, SPELL_FAILED_NOT_SHAPESHIFT, SPELL_FAILED_NOT_STANDING, SPELL_FAILED_NOT_TRADING, SPELL_FAILED_ONLY_ABOVEWATER, SPELL_FAILED_ONLY_INDOORS, SPELL_FAILED_ONLY_OUTDOORS, SPELL_FAILED_ONLY_SHAPESHIFT, SPELL_FAILED_ONLY_STEALTHED, SPELL_FAILED_OUT_OF_RANGE, SPELL_FAILED_REQUIRES_SPELL_FOCUS, SPELL_FAILED_ROOTED, SPELL_FAILED_SPELL_IN_PROGRESS, SPELL_FAILED_SPELL_UNAVAILABLE, SPELL_FAILED_TARGET_AFFECTING_COMBAT, SPELL_FAILED_TARGET_AURASTATE, SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED, SPELL_FAILED_TARGET_FRIENDLY, SPELL_FAILED_TARGET_IN_COMBAT, SPELL_FAILED_TARGET_IS_PLAYER, SPELL_FAILED_TARGET_IS_PLAYER_CONTROLLED, SPELL_FAILED_TARGET_IS_TRIVIAL, SPELL_FAILED_TARGET_LOCKED_TO_RAID_INSTANCE, SPELL_FAILED_TARGET_NO_POCKETS, SPELL_FAILED_TARGET_NO_WEAPONS, SPELL_FAILED_TARGET_NOT_DEAD, SPELL_FAILED_TARGET_NOT_IN_INSTANCE, SPELL_FAILED_TARGET_NOT_LOOTED, SPELL_FAILED_TARGET_UNSKINNABLE, SPELL_FAILED_TARGETS_DEAD, SPELL_FAILED_TOO_MANY_OF_ITEM, SPELL_FAILED_TOTEMS, SPELL_FAILED_TRY_AGAIN, SPELL_FAILED_UNIQUE_GLYPH, SPELL_FAILED_UNIT_NOT_INFRONT, SPELL_FAILED_UNKNOWN, SPELL_FAILED_WRONG_PET_FOOD, SPELL_TARGETS_AOE_ATTACKABLE, SPELLFAMILY_DRUID, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellEntry::spellLevel, SpellTargetInfoTable, SpellEntry::SpellVisual, sSpellMgr, sSpellRadiusStore, sSpellRangeStore, sSpellTemplate, sSummonPropertiesStore, STATUS_IN_PROGRESS, STATUS_WAIT_LEAVE, SUMMON_PROP_GROUP_PETS, sWorld, TARGET_ENUMERATOR_CHAIN, TARGET_ENUMERATOR_SINGLE, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_SELF, TARGET_FLAG_SOURCE_LOCATION, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_GAMEOBJECT, TARGET_GROUP, TARGET_HARMFUL, TARGET_HELPFUL, TARGET_PARTY, TARGET_SCRIPT, TARGET_TYPE_UNIT, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_MASTER, TARGET_UNIT_CASTER_PASSENGER_0, TARGET_UNIT_CASTER_PASSENGER_1, TARGET_UNIT_CASTER_PASSENGER_2, TARGET_UNIT_CASTER_PASSENGER_3, TARGET_UNIT_CASTER_PASSENGER_4, TARGET_UNIT_CASTER_PASSENGER_5, TARGET_UNIT_CASTER_PASSENGER_6, TARGET_UNIT_CASTER_PASSENGER_7, TARGET_UNIT_CASTER_PET, TARGET_UNIT_CASTER_VEHICLE, TARGET_UNIT_ENEMY, TARGET_UNIT_ENEMY_NEAR_CASTER, TARGET_UNIT_FRIEND_NEAR_CASTER, TARGET_UNIT_NEAR_CASTER, TARGET_UNIT_PARTY, SpellEntry::targetAuraSpell, SpellEntry::TargetAuraState, SpellEntry::TargetAuraStateNot, TOTEM_SLOT_FIRE, TRADE_SLOT_NONTRADED, TRIGGERED_OLD_TRIGGERED, Pet::TryLoadFromDB(), TYPEID_CORPSE, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_ALLOW_CHEAT_SPELLS, UNIT_FLAG_IMMUNE, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_FLAG_SKINNABLE, UNIT_FLAG_UNTARGETABLE, UNIT_STAT_ROOT, Cell::VisitGridObjects(), Position::x, Position::y, and Position::z.
Referenced by PlayerbotAI::_HandleCommandCraft(), cast(), PlayerbotAI::CheckBotCast(), CheckPetCast(), PlayerbotAI::FindMount(), WorldSession::HandleAcceptTradeOpcode(), PreCastCheck(), and PlayerbotAI::UpdateAI().
CheckCasterAuras()
SpellCastResult Spell::CheckCasterAuras (uint32 & param1) const
Definition at line 7168 of file Spell.cpp.
References CheckSpellCancelsCharm(), CheckSpellCancelsConfuse(), CheckSpellCancelsFear(), CheckSpellCancelsPacify(), CheckSpellCancelsSilence(), CheckSpellCancelsStun(), GetAllowedMechanicMask(), Unit::GetAurasByType(), Unit::GetCharmer(), Object::GetUInt32Value(), SpellEntry::HasAttribute(), Unit::HasAura(), SpellEntry::Id, Object::IsUnit(), m_caster, m_clientCast, m_ignoreCasterAuraState, m_spellInfo, m_trueCaster, MANGOS_ASSERT, SpellEntry::PreventionType, SPELL_ATTR_EX5_ALLOW_WHILE_CONFUSED, SPELL_ATTR_EX5_ALLOW_WHILE_FLEEING, SPELL_ATTR_EX5_ALLOW_WHILE_STUNNED, SPELL_ATTR_EX6_NOT_AN_ATTACK, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_FEAR, SPELL_AURA_MOD_STUN, SPELL_CAST_OK, SPELL_FAILED_CHARMED, SPELL_FAILED_CONFUSED, SPELL_FAILED_FLEEING, SPELL_FAILED_NOT_KNOWN, SPELL_FAILED_PACIFIED, SPELL_FAILED_PREVENTED_BY_MECHANIC, SPELL_FAILED_SILENCED, SPELL_FAILED_STUNNED, SPELL_PREVENTION_TYPE_PACIFY, SPELL_PREVENTION_TYPE_SILENCE, UNIT_FIELD_FLAGS, UNIT_FLAG_CONFUSED, UNIT_FLAG_FLEEING, UNIT_FLAG_PACIFIED, UNIT_FLAG_SILENCED, and UNIT_FLAG_STUNNED.
Referenced by CheckCast().
CheckItems()
SpellCastResult Spell::CheckItems ()
Definition at line 7661 of file Spell.cpp.
References SpellEntry::baseLevel, CalculateSpellEffectValue(), Player::CanNoReagentCast(), Player::CanStoreNewItem(), ItemPrototype::Class, ItemPrototype::DisenchantID, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectItemType, SpellEntry::EffectMiscValue, ENCHANTMENT_SOULBOUND, EQUIP_ERR_OK, EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_RANGED, ItemPrototype::Flags, SpellItemEnchantmentEntry::flags, Item::GetCount(), Unit::GetDummyAura(), Object::GetEntry(), Unit::GetHealth(), Player::GetItemByEntry(), Player::GetItemByLimitedCategory(), ObjectMgr::GetItemPrototype(), SpellCastTargets::getItemTarget(), SpellCastTargets::getItemTargetEntry(), SpellCastTargets::getItemTargetGuid(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Object::GetObjectGuid(), Item::GetOwner(), Item::GetOwnerGuid(), Unit::GetPower(), Item::GetProto(), Player::GetSkillValue(), Item::GetSlot(), Item::GetSpellCharges(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Player::HasItemCount(), Player::HasItemTotemCategory(), Item::HasTemporaryLoot(), LootStore::HaveLootFor(), IgnoreItemRequirements(), Item::IsFitToSpellRequirements(), Item::IsInTrade(), Object::IsPlayer(), ItemPrototype::IsVellum(), ITEM_CLASS_CONSUMABLE, ITEM_CLASS_PROJECTILE, ITEM_FLAG_IS_MILLABLE, ITEM_FLAG_IS_PROSPECTABLE, ITEM_FLAG_NO_REAGENT_COST, ITEM_SUBCLASS_ARROW, ITEM_SUBCLASS_BULLET, ITEM_SUBCLASS_WEAPON_BOW, ITEM_SUBCLASS_WEAPON_CROSSBOW, ITEM_SUBCLASS_WEAPON_GUN, ITEM_SUBCLASS_WEAPON_THROWN, ITEM_SUBCLASS_WEAPON_WAND, ItemPrototype::ItemLevel, itemTarget, LootTemplates_Milling, LootTemplates_Prospecting, m_attackType, m_caster, m_CastItem, m_IsTriggeredSpell, Object::m_loot, m_param1, m_param2, m_spellInfo, m_spellState, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, MAX_EFFECT_INDEX, MAX_ITEM_PROTO_SPELLS, MAX_POWERS, MAX_SPELL_REAGENTS, MAX_SPELL_TOTEM_CATEGORIES, MAX_SPELL_TOTEMS, NULL_BAG, NULL_SLOT, PLAYER_AMMO_ID, RANGED_ATTACK, SpellEntry::Reagent, SpellEntry::ReagentCount, ItemPrototype::RequiredDisenchantSkill, ItemPrototype::RequiredSkillRank, Player::SendEquipError(), SKILL_ENCHANTING, SKILL_INSCRIPTION, SKILL_JEWELCRAFTING, SPELL_ATTR_EX2_ENCHANT_OWN_ITEM_ONLY, SPELL_ATTR_HELD_ITEM_ONLY, SPELL_CAST_OK, SPELL_EFFECT_CREATE_ITEM, SPELL_EFFECT_DISENCHANT, SPELL_EFFECT_DUMMY, SPELL_EFFECT_ENCHANT_HELD_ITEM, SPELL_EFFECT_ENCHANT_ITEM, SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC, SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY, SPELL_EFFECT_ENERGIZE, SPELL_EFFECT_HEAL, SPELL_EFFECT_MILLING, SPELL_EFFECT_PROSPECTING, SPELL_EFFECT_RESTORE_ITEM_CHARGES, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, SPELL_FAILED_ALREADY_AT_FULL_HEALTH, SPELL_FAILED_ALREADY_AT_FULL_POWER, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_CANT_BE_DISENCHANTED, SPELL_FAILED_CANT_BE_MILLED, SPELL_FAILED_CANT_BE_PROSPECTED, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_EQUIPPED_ITEM, SPELL_FAILED_EQUIPPED_ITEM_CLASS, SPELL_FAILED_ERROR, SPELL_FAILED_ITEM_AT_MAX_CHARGES, SPELL_FAILED_ITEM_ENCHANT_TRADE_WINDOW, SPELL_FAILED_ITEM_GONE, SPELL_FAILED_ITEM_NOT_FOUND, SPELL_FAILED_LOW_CASTLEVEL, SPELL_FAILED_LOWLEVEL, SPELL_FAILED_MAINHAND_EMPTY, SPELL_FAILED_NEED_MORE_ITEMS, SPELL_FAILED_NO_AMMO, SPELL_FAILED_NO_CHARGES_REMAIN, SPELL_FAILED_NOT_TRADEABLE, SPELL_FAILED_NOT_WHILE_LOOTING, SPELL_FAILED_REAGENTS, SPELL_FAILED_TARGET_NOT_PLAYER, SPELL_FAILED_TOTEM_CATEGORY, SPELL_FAILED_TOTEMS, SPELL_STATE_TARGETING, _Spell::SpellCharges, ItemPrototype::Spells, sSpellItemEnchantmentStore, ItemPrototype::Stackable, ItemPrototype::SubClass, TARGET_FLAG_TRADE_ITEM, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_PET, SpellEntry::Totem, SpellEntry::TotemCategory, and TYPEID_PLAYER.
Referenced by CheckCast().
CheckOrTakeRunePower()
SpellCastResult Spell::CheckOrTakeRunePower (bool take)
Definition at line 5125 of file Spell.cpp.
References CLASS_DEATH_KNIGHT, CONFIG_FLOAT_RATE_POWER_RUNICPOWER_INCOME, Unit::getClass(), Player::GetCurrentRune(), Player::GetRuneBaseCooldown(), Player::GetRuneCooldown(), Player::GetRunesState(), Player::GetSpellModOwner(), Object::GetTypeId(), SpellEntry::Id, m_caster, m_runesState, m_runesStateAfterCast, m_spellInfo, MAX_RUNES, Unit::ModifyPower(), SpellRuneCostEntry::NoRuneCost(), SpellRuneCostEntry::NoRunicPowerGain(), NUM_RUNE_TYPES, POWER_RUNIC_POWER, Player::RestoreBaseRune(), RUNE_COOLDOWN, RUNE_DEATH, SpellRuneCostEntry::RuneCost, SpellEntry::runeCostID, SpellRuneCostEntry::runePowerGain, Player::SetRuneCooldown(), SPELL_CAST_OK, SPELL_FAILED_NO_POWER, SPELLMOD_COST, sSpellRuneCostStore, sWorld, and TYPEID_PLAYER.
Referenced by CheckPower(), and TakePower().
CheckPetCast()
SpellCastResult Spell::CheckPetCast (Unit * target)
Definition at line 7082 of file Spell.cpp.
References Unit::CanAssistSpell(), Unit::CanAttack(), CheckCast(), SpellEntry::EffectImplicitTargetA, Unit::GetMaster(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Unit::HasCharmer(), SpellEntry::Id, Unit::IsAlive(), Object::IsCreature(), Unit::IsDead(), Player::IsGhouled(), Unit::IsInCombat(), IsNonCombatSpell(), Unit::IsNonMeleeSpellCasted(), Creature::IsPet(), IsPositiveSpell(), WorldObject::IsSpellReady(), m_caster, m_ignoreConcurrentCasts, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, SpellCastTargets::setUnitTarget(), SPELL_ATTR_EX2_ALLOW_DEAD_TARGET, SPELL_FAILED_AFFECTING_COMBAT, SPELL_FAILED_BAD_IMPLICIT_TARGETS, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_CASTER_DEAD, SPELL_FAILED_NOT_READY, SPELL_FAILED_SPELL_IN_PROGRESS, TARGET_FLAG_UNIT, TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_LOCATION_SCRIPT_NEAR_CASTER, TARGET_UNIT, TARGET_UNIT_ENEMY, TARGET_UNIT_FRIEND, TARGET_UNIT_PARTY, TARGET_UNIT_RAID, TARGET_UNIT_SCRIPT_NEAR_CASTER, and TYPEID_PLAYER.
Referenced by CanAutoCast().
CheckPower()
SpellCastResult Spell::CheckPower (bool strict)
Definition at line 7588 of file Spell.cpp.
References CalculatePowerCost(), CheckOrTakeRunePower(), Unit::GetHealth(), Unit::GetPower(), Unit::GetRegenTimer(), Object::GetTypeId(), m_caster, m_CastItem, m_powerCost, m_spellInfo, MAX_POWERS, POWER_HEALTH, POWER_RUNE, SpellEntry::powerType, REGEN_TIME_PRECISE, Player::RegenerateAll(), sLog, SPELL_CAST_OK, SPELL_FAILED_CASTER_AURASTATE, SPELL_FAILED_NO_POWER, SPELL_FAILED_UNKNOWN, and TYPEID_PLAYER.
Referenced by PlayerbotAI::CastSpell(), and CheckCast().
CheckRange()
SpellCastResult Spell::CheckRange (bool strict)
Definition at line 7420 of file Spell.cpp.
References DIST_CALC_NONE, SpellEntry::FacingCasterFlags, Unit::GetCharm(), WorldObject::GetDistance(), SpellCastTargets::getGOTarget(), GetMinMaxRange(), Unit::GetPet(), SpellCastTargets::getUnitTarget(), WorldObject::HasInArc(), HasSpellTarget(), IsIgnoreLosSpell(), Object::IsPlayer(), WorldObject::IsWithinLOS(), m_caster, m_casttime, m_clientCast, SpellCastTargets::m_destPos, m_maxRange, m_spellInfo, SpellCastTargets::m_srcPos, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, SpellEntry::rangeIndex, SPELL_CAST_OK, SPELL_FACING_FLAG_INFRONT, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_OUT_OF_RANGE, SPELL_FAILED_TOO_CLOSE, SPELL_FAILED_UNIT_NOT_INFRONT, SPELL_RANGE_FLAG_MELEE, sSpellRangeStore, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_SOURCE_LOCATION, TARGET_UNIT_CASTER_PET, Position::x, Position::y, and Position::z.
Referenced by CheckCast().
CheckScriptTargeting()
SpellCastResult Spell::CheckScriptTargeting (SpellEffectIndex effIndex, uint32 chainTargets, float radius, uint32 targetMode, UnitList & tempUnitList, GameObjectList & tempGOList)
Definition at line 3007 of file Spell.cpp.
References DEFAULT_VISIBILITY_DISTANCE, DEFAULT_VISIBILITY_INSTANCE, DIST_CALC_NONE, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SQLMultiStorage::SQLMSIteratorBounds< T >::first, MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::FoundOutOfRange(), GetAffectiveCasterObject(), SQLMultiStorage::getBounds(), Map::GetCreature(), Map::GetCreatures(), WorldObject::GetDistance(), Map::GetGameObject(), Map::GetGameObjects(), WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), SpellEntry::Id, Map::IsDungeon(), WorldObject::IsWithinDistInMap(), m_spellInfo, m_targets, m_trueCaster, MAX_SPELL_TARGET_TYPE, OnCheckTarget(), SQLMultiStorage::SQLMSIteratorBounds< T >::second, SpellCastTargets::setDestination(), sLog, SPELL_ATTR_EX_EXCLUDE_CASTER, SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_OUT_OF_RANGE, SPELL_TARGET_TYPE_CREATURE, SPELL_TARGET_TYPE_CREATURE_GUID, SPELL_TARGET_TYPE_DEAD, SPELL_TARGET_TYPE_GAMEOBJECT, SPELL_TARGET_TYPE_GAMEOBJECT_GUID, SPELL_TARGET_TYPE_STRING_ID, sSpellScriptTargetStorage, TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, TARGET_LOCATION_SCRIPT_NEAR_CASTER, TARGET_UNIT_SCRIPT_NEAR_CASTER, TYPEID_UNIT, Cell::VisitAllObjects(), and Cell::VisitGridObjects().
Referenced by DemonBroiledSurprise::OnCheckCast(), RaiseDeadHyjal::OnCheckCast(), and SetTargetMap().
CheckSpellCancelsAuraEffect()
bool Spell::CheckSpellCancelsAuraEffect (AuraType auraType, uint32 & param1) const
Definition at line 7266 of file Spell.cpp.
References SpellEntry::EffectMechanic, Unit::GetAurasByType(), Object::IsGameObject(), m_caster, m_spellInfo, m_trueCaster, SpellEntry::Mechanic, and SpellCancelsAuraEffect().
Referenced by CheckSpellCancelsCharm(), CheckSpellCancelsConfuse(), CheckSpellCancelsFear(), CheckSpellCancelsPacify(), CheckSpellCancelsSilence(), and CheckSpellCancelsStun().
CheckSpellCancelsCharm()
bool Spell::CheckSpellCancelsCharm (uint32 & param1) const
Definition at line 7293 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), SPELL_AURA_AOE_CHARM, SPELL_AURA_MOD_CHARM, and SPELL_AURA_MOD_POSSESS.
Referenced by CheckCasterAuras().
CheckSpellCancelsConfuse()
bool Spell::CheckSpellCancelsConfuse (uint32 & param1) const
Definition at line 7323 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), and SPELL_AURA_MOD_CONFUSE.
Referenced by CheckCasterAuras().
CheckSpellCancelsFear()
bool Spell::CheckSpellCancelsFear (uint32 & param1) const
Definition at line 7318 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), and SPELL_AURA_MOD_FEAR.
Referenced by CheckCasterAuras().
CheckSpellCancelsPacify()
bool Spell::CheckSpellCancelsPacify (uint32 & param1) const
Definition at line 7312 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), SPELL_AURA_MOD_PACIFY, and SPELL_AURA_MOD_PACIFY_SILENCE.
Referenced by CheckCasterAuras().
CheckSpellCancelsSilence()
bool Spell::CheckSpellCancelsSilence (uint32 & param1) const
Definition at line 7306 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), SPELL_AURA_MOD_PACIFY_SILENCE, and SPELL_AURA_MOD_SILENCE.
Referenced by CheckCasterAuras().
CheckSpellCancelsStun()
bool Spell::CheckSpellCancelsStun (uint32 & param1) const
Definition at line 7300 of file Spell.cpp.
References CheckSpellCancelsAuraEffect(), SPELL_AURA_MOD_STUN, and SPELL_AURA_STRANGULATE.
Referenced by CheckCasterAuras().
CheckSpellScriptTargets()
void Spell::CheckSpellScriptTargets (SQLMultiStorage::SQLMSIteratorBounds< SpellTargetEntry > & bounds, UnitList & tempTargetUnitMap, UnitList & targetUnitMap, SpellEffectIndex effIndex) static protected
Definition at line 3231 of file Spell.cpp.
References SpellTargetEntry::CanNotHitWithSpellEffect(), SQLMultiStorage::SQLMSIteratorBounds< T >::first, Object::GetDbGuid(), Object::GetEntry(), Object::GetTypeId(), WorldObject::HasStringId(), Unit::IsAlive(), SQLMultiStorage::SQLMSIteratorBounds< T >::second, SPELL_TARGET_TYPE_CREATURE, SPELL_TARGET_TYPE_CREATURE_GUID, SPELL_TARGET_TYPE_DEAD, SPELL_TARGET_TYPE_GAMEOBJECT, SPELL_TARGET_TYPE_GAMEOBJECT_GUID, SPELL_TARGET_TYPE_STRING_ID, SpellTargetEntry::targetEntry, SpellTargetEntry::type, and TYPEID_UNIT.
Referenced by SetTargetMap().
CheckTarget()
bool Spell::CheckTarget (Unit * target, SpellEffectIndex eff, bool targetB, CheckException exception = EXCEPTION_NONE) const
Definition at line 8277 of file Spell.cpp.
References CheckTargetCreatureType(), SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellTargetInfo::enumerator, EXCEPTION_MAGNET, SpellTargetInfo::filter, GetAffectiveCaster(), GetCastingObject(), Unit::GetCollisionHeight(), Map::GetCorpse(), SpellCastTargets::getCorpseTargetGuid(), SpellCastTargets::getDestination(), Unit::GetDynObject(), Unit::GetLevel(), WorldObject::GetMap(), Unit::GetMasterGuid(), Object::GetObjectGuid(), Corpse::GetOwnerGuid(), SpellCastTargets::getSource(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Unit::GetVisibility(), SpellEntry::HasAttribute(), Object::HasFlag(), Unit::HasVisFlags(), SpellEntry::Id, Unit::IsAlive(), IsAllowingDeadTarget(), Unit::IsAOEImmune(), Unit::IsCrowdControlled(), Player::IsGameMaster(), IsIgnoreLosSpellEffect(), Unit::IsInCombat(), Object::IsPlayer(), Unit::IsPlayerControlled(), IsPositiveEffect(), Unit::IsTrivialForTarget(), WorldObject::IsWithinLOS(), WorldObject::IsWithinLOSInMap(), SpellTargetInfo::los, m_caster, m_ignoreUnselectableTarget, m_spellInfo, m_targets, m_triggeredByAuraSpell, m_trueCaster, SpellEntry::MaxTargetLevel, OnCheckTarget(), SPELL_ATTR_ALLOW_CAST_WHILE_DEAD, SPELL_ATTR_EX2_CANNOT_CAST_ON_TAPPED, SPELL_ATTR_EX3_NOT_ON_AOE_IMMUNE, SPELL_ATTR_EX3_ONLY_ON_GHOSTS, SPELL_ATTR_EX3_ONLY_ON_PLAYER, SPELL_ATTR_EX5_ALWAYS_AOE_LINE_OF_SIGHT, SPELL_ATTR_EX5_NOT_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER_CONTROLLED_NPC, SPELL_ATTR_EX5_NOT_ON_TRIVIAL, SPELL_ATTR_EX5_TREAT_AS_AREA_EFFECT, SPELL_ATTR_EX6_CAN_TARGET_UNTARGETABLE, SPELL_ATTR_EX6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS, SPELL_ATTR_EX_ONLY_PEACEFUL_TARGETS, SPELL_EFFECT_RESURRECT_NEW, SPELL_EFFECT_SUMMON_PLAYER, SpellTargetInfoTable, TARGET_ENUMERATOR_CHAIN, TARGET_HELPFUL, TARGET_LOCATION_CHANNEL_TARGET_DEST, TARGET_LOS_CASTER, TARGET_LOS_DEST, TARGET_LOS_SRC, TARGET_SCRIPT, TARGET_TYPE_UNIT, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_PET, SpellTargetInfo::type, TYPEID_PLAYER, UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, UNIT_FLAG_UNTARGETABLE, UNIT_VIS_FLAG_GHOST, and VISIBILITY_OFF.
Referenced by CheckCast(), and FillUnitTargets().
CheckTargetCreatureType()
bool Spell::CheckTargetCreatureType (Unit * target, SpellEntry const * spellInfo) static
Definition at line 8249 of file Spell.cpp.
References Unit::GetCreatureTypeMask(), SpellEntry::Id, and SpellEntry::TargetCreatureType.
Referenced by UnitAI::CanCastSpell(), CheckCast(), and CheckTarget().
CheckVehicle()
SpellCastResult Spell::CheckVehicle (Unit const * caster, SpellEntry const & spellInfo) static
Definition at line 9950 of file Spell.cpp.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectMiscValue, SpellEntry::EffectMiscValueB, SpellShapeshiftFormEntry::flags1, VehicleInfo::GetSeatForPassenger(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), SummonPropertiesEntry::Group, SpellEntry::HasAttribute(), IsSpellHaveAura(), Object::IsUnit(), VehicleSeatEntry::m_flags, MAX_EFFECT_INDEX, SEAT_FLAG_CAN_ATTACK, SEAT_FLAG_CAN_CAST_MOUNT_SPELL, SEAT_FLAG_CAN_CONTROL, SEAT_FLAG_UNCONTROLLED, SEAT_FLAG_UNK25, SPELL_ATTR_ALLOW_WHILE_MOUNTED, SPELL_ATTR_EX6_ALLOW_WHILE_RIDING_VEHICLE, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_MOUNTED, SPELL_CAST_OK, SPELL_EFFECT_SUMMON, SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW, sSpellShapeshiftFormStore, sSummonPropertiesStore, SUMMON_PROP_GROUP_WILD, and TYPEID_PLAYER.
Referenced by WorldSession::HandleCastSpellOpcode().
CleanupTargetList()
void Spell::CleanupTargetList ()
Definition at line 965 of file Spell.cpp.
References m_delayMoment, m_UniqueGOTargetInfo, m_UniqueItemInfo, and m_UniqueTargetInfo.
Referenced by Spell().
ClearCastItem()
void Spell::ClearCastItem ()
Definition at line 8936 of file Spell.cpp.
References SpellCastTargets::getItemTarget(), m_CastItem, m_targets, and SpellCastTargets::setItemTarget().
Referenced by EffectDummy(), EffectSummonChangeItem(), and TakeCastItem().
Delayed()
void Spell::Delayed ()
Definition at line 8134 of file Spell.cpp.
References DETAIL_FILTER_LOG, Object::GetPackGUID(), Unit::GetTotalAuraModifier(), SpellEntry::HasAttribute(), SpellEntry::Id, SpellEntry::InterruptFlags, isDelayableNoMore(), Object::IsPlayer(), LOG_FILTER_SPELL_CAST, m_caster, m_casttime, m_spellInfo, m_spellState, m_timer, m_trueCaster, WorldObject::SendMessageToSet(), SMSG_SPELL_DELAYED, SPELL_ATTR_EX6_NO_PUSHBACK, SPELL_AURA_REDUCE_PUSHBACK, SPELL_INTERRUPT_FLAG_DAMAGE_PUSHBACK, SPELL_STATE_TRAVELING, and SPELLMOD_NOT_LOSE_CASTING_TIME.
DelayedChannel()
void Spell::DelayedChannel ()
Definition at line 8179 of file Spell.cpp.
References DEBUG_FILTER_LOG, Unit::GetDynObject(), Object::GetObjectGuid(), GetSpellDuration(), getState(), Unit::GetTotalAuraModifier(), ObjectAccessor::GetUnit(), SpellEntry::Id, isDelayableNoMore(), Object::IsPlayer(), LOG_FILTER_SPELL_CAST, m_caster, m_spellInfo, m_timer, m_trueCaster, m_UniqueTargetInfo, MAX_EFFECT_INDEX, SendChannelUpdate(), SPELL_AURA_REDUCE_PUSHBACK, SPELL_MISS_NONE, SPELL_STATE_CHANNELING, and SPELLMOD_NOT_LOSE_CASTING_TIME.
DoAllEffectOnTarget() [1/4]
void Spell::DoAllEffectOnTarget (CorpseTargetInfo * target) protected
Definition at line 1736 of file Spell.cpp.
References Spell::CorpseTargetInfo::corpseGUID, corpseTarget, Spell::CorpseTargetInfo::effectMask, ExecuteEffects(), ObjectAccessor::GetCorpseInMap(), WorldObject::GetMapId(), and m_trueCaster.
DoAllEffectOnTarget() [2/4]
void Spell::DoAllEffectOnTarget (GOTargetInfo * target) protected
Definition at line 1694 of file Spell.cpp.
References Spell::GOTargetInfo::effectMask, ExecuteEffects(), gameObjTarget, Unit::GetBeneficiaryPlayer(), Map::GetGameObject(), WorldObject::GetMap(), SpellEntry::Id, IsAutoRepeat(), IsChannelActive(), IsNextMeleeSwingSpell(), m_caster, m_spellInfo, m_trueCaster, OnHit(), Spell::GOTargetInfo::processed, SPELL_MISS_NONE, and Spell::GOTargetInfo::targetGUID.
DoAllEffectOnTarget() [3/4]
void Spell::DoAllEffectOnTarget (ItemTargetInfo * target) protected
Definition at line 1723 of file Spell.cpp.
References Spell::ItemTargetInfo::effectMask, ExecuteEffects(), Spell::ItemTargetInfo::item, itemTarget, OnHit(), and SPELL_MISS_NONE.
DoAllEffectOnTarget() [4/4]
void Spell::DoAllEffectOnTarget (TargetInfo * target) protected
Definition at line 1296 of file Spell.cpp.
References SpellNonMeleeDamage::absorb, Unit::AddDelayedHolderDueToProc(), Unit::AI(), Creature::AI(), Unit::CalcArmorReducedDamage(), Unit::CalculateAbsorbResistBlock(), Unit::CalculateCritAmount(), Unit::CalculateHealAbsorb(), Unit::CasterHitTargetWithSpell(), Unit::CastSpell(), createProcExtendMask(), SpellNonMeleeDamage::damage, Spell::TargetInfo::damage, Unit::DealDamageMods(), Unit::DealHeal(), Unit::DealSpellDamage(), DoSpellHitOnUnit(), Spell::TargetInfo::effectHitMask, Spell::TargetInfo::effectMask, GetAffectiveCasterOrOwner(), Unit::GetBeneficiaryPlayer(), Unit::GetDummyAura(), Unit::getHostileRefManager(), Object::GetObjectGuid(), ObjectAccessor::GetUnit(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Spell::TargetInfo::healing, SpellNonMeleeDamage::HitInfo, Spell::TargetInfo::HitInfo, SpellEntry::Id, IsAutoRepeat(), IsChannelActive(), Object::IsCreature(), Spell::TargetInfo::isCrit, IsNextMeleeSwingSpell(), Object::IsPlayer(), Unit::IsSpellProccingHappening(), m_absorb, m_attackType, m_canTrigger, m_caster, m_damage, m_healing, m_IsTriggeredSpell, m_negativeEffectMask, m_resetLeash, m_spellAuraHolder, m_spellInfo, m_spellSchoolMask, m_targets, m_trueCaster, Spell::TargetInfo::magnet, Spell::TargetInfo::missCondition, NEGATIVE_TRIGGER_MASK, OnAfterHit(), OnHit(), PrepareMasksForProcSystem(), PROC_EX_CRITICAL_HIT, PROC_EX_MAGNET, PROC_EX_NONE, PROC_EX_NORMAL_HIT, PROC_FLAG_NONE, PROC_FLAG_ON_TRAP_ACTIVATION, PROC_FLAG_TAKE_ANY_DAMAGE, Unit::ProcDamageAndSpell(), Spell::TargetInfo::processed, Spell::TargetInfo::reflectResult, ResetEffectDamageAndHeal(), Unit::SendSpellNonMeleeDamageLog(), SpellAuraHolder::SetState(), SPELL_ATTR_EX3_IGNORE_CASTER_MODIFIERS, SPELL_ATTR_EX7_CAN_CAUSE_INTERRUPT, SPELL_DIRECT_DAMAGE, SPELL_HIT_TYPE_CRIT, SPELL_INTERRUPT_NONPLAYER, SPELL_MISS_EVADE, SPELL_MISS_NONE, SPELL_MISS_REFLECT, SPELL_SCHOOL_MASK_NORMAL, SPELLAURAHOLDER_STATE_READY, SPELLFAMILY_WARLOCK, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, UnitAI::SpellHit(), UnitAI::SpellHitTarget(), SpellEntry::SpellIconID, sSpellMgr, SpellNonMeleeDamage::target, Spell::TargetInfo::targetGUID, HostileRefManager::threatAssist(), TRIGGERED_IGNORE_CURRENT_CASTED_SPELL, TRIGGERED_IGNORE_GCD, and unitTarget.
Referenced by _handle_immediate_phase(), handle_delayed(), and handle_immediate().
DoAllTargetlessEffects()
void Spell::DoAllTargetlessEffects (bool dest) protected
Definition at line 1642 of file Spell.cpp.
References Spell::DestTargetInfo::effectMask, Spell::DestTargetInfo::effectMaskProcessed, SpellCastTargets::getUnitTarget(), HandleEffect(), IsEffectHandledImmediatelySpellLaunch(), m_attackType, m_caster, m_destTargetInfo, m_spellInfo, m_targetlessMask, m_targets, m_trueCaster, MAX_EFFECT_INDEX, OnHit(), PrepareMasksForProcSystem(), PROC_EX_NONE, PROC_FLAG_NONE, PROC_FLAG_ON_TRAP_ACTIVATION, Unit::ProcDamageAndSpell(), SPELL_MISS_NONE, and unitTarget.
Referenced by _handle_immediate_phase(), and handle_delayed().
DoCreateItem()
bool Spell::DoCreateItem (SpellEffectIndex eff_idx, uint32 itemtype, bool reportError = true)
Definition at line 5398 of file SpellEffects.cpp.
References canCreateExtraItems(), Player::CanStoreNewItem(), ItemPrototype::Class, damage, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EQUIP_ERR_CANT_CARRY_MORE_OF_THIS, EQUIP_ERR_INVENTORY_FULL, EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, Item::GenerateItemRandomPropertyId(), ObjectMgr::GetItemPrototype(), ItemPrototype::GetMaxStackSize(), Object::GetObjectGuid(), Item::GetProto(), Object::GetTypeId(), SpellEntry::Id, ITEM_CLASS_CONSUMABLE, ITEM_CLASS_QUEST, ITEM_FIELD_CREATOR, m_spellInfo, NULL_BAG, NULL_SLOT, roll_chance_f(), Player::SendEquipError(), Player::SendNewItem(), Object::SetGuidValue(), SPELL_EFFECT_DUMMY, Player::StoreNewItem(), TYPEID_PLAYER, unitTarget, and Player::UpdateCraftSkill().
Referenced by EffectCreateItem(), EffectCreateItem2(), EffectDummy(), EffectEnchantItemPerm(), and EffectScriptEffect().
DoSpellHitOnUnit()
void Spell::DoSpellHitOnUnit (Unit * unit, uint32 effectMask, TargetInfo * target, bool isReflected = true) protected
Definition at line 1491 of file Spell.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, Unit::AddSpellAuraHolder(), Unit::ApplyDiminishingToDuration(), WorldObject::CanAttackSpell(), Unit::CasterHitTargetWithSpell(), CastPreCastSpells(), CreateSpellAuraHolder(), Spell::TargetInfo::diminishDuration, Spell::TargetInfo::diminishGroup, DIMINISHING_LEVEL_1, DIMINISHING_NONE, Spell::TargetInfo::diminishLevel, Spell::TargetInfo::effectDuration, Spell::TargetInfo::effectHitMask, Spell::TargetInfo::effectMaskProcessed, ExecuteEffects(), Player::GetAchievementMgr(), GetAffectiveCasterOrOwner(), SpellAuraHolder::GetAuraMaxDuration(), Unit::GetDiminishing(), GetSpellSchoolMask(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Object::HasFlag(), Spell::TargetInfo::heartbeatResistChance, SpellEntry::Id, Unit::IncrDiminishing(), Unit::IsAlive(), WorldObject::IsControlledByPlayer(), SpellAuraHolder::IsEmptyHolder(), Object::IsGameObject(), Unit::IsImmuneToDamage(), Unit::IsImmuneToSpell(), Unit::IsImmuneToSpellEffect(), Object::IsPlayer(), Unit::IsPlayerControlled(), SpellAuraHolder::IsPositive(), IsPositiveSpell(), IsSpellAppliesAura(), IsSpellWithNonAuraEffect(), IsSubjectToDiminishingLevels(), Unit::IsVisibleForOrDetect(), m_auraScript, m_caster, m_CastItem, m_duration, m_IsTriggeredSpell, m_spellAuraHolder, m_spellInfo, m_spellState, m_targets, m_triggeredBySpellInfo, m_trueCaster, MAX_EFFECT_INDEX, ResetEffectDamageAndHeal(), Unit::SendSpellMiss(), SpellAuraHolder::SetAuraDuration(), SpellAuraHolder::SetAuraMaxDuration(), SpellAuraHolder::setDiminishGroup(), SpellAuraHolder::SetHeartbeatResist(), SPELL_ATTR_EX5_IGNORE_AREA_EFFECT_PVP_CHECK, SPELL_ATTR_EX6_IGNORE_PHASE_SHIFT, SPELL_ATTR_NO_IMMUNITIES, SPELL_MISS_IMMUNE, SPELL_STATE_TRAVELING, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, AchievementMgr::UpdateAchievementCriteria(), and Player::UpdateAchievementCriteria().
Referenced by DoAllEffectOnTarget().
DoSummonCritter()
bool Spell::DoSummonCritter (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx, uint32 level)
Definition at line 6312 of file SpellEffects.cpp.
References Pet::Create(), SpellEntry::EffectMiscValue, Map::GenerateLocalLowGuid(), Creature::GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), Object::GetEntry(), Unit::GetFaction(), WorldObject::GetMap(), Unit::GetMiniPet(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), Object::GetTypeId(), Object::HasFlag(), HIGHGUID_PET, SpellEntry::Id, Pet::InitPetCreateSpells(), m_caster, m_duration, m_spellInfo, MANGOS_ASSERT, MINI_PET, CreatureInfo::NpcFlags, Unit::RemoveMiniPet(), Creature::SelectLevel(), Object::SetByteFlag(), Pet::SetDuration(), Unit::setFaction(), Object::SetFlag(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Pet::SetLoading(), Unit::SetMiniPet(), Pet::SetOwnerGuid(), Creature::SetRespawnCoord(), Object::SetUInt32Value(), sLog, TYPEID_PLAYER, UNIT_BYTE2_FLAG_UNK5, UNIT_CREATED_BY_SPELL, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_NPC_FLAGS, and CreatureInfo::UnitFlags.
Referenced by EffectSummonType().
DoSummonGuardian()
bool Spell::DoSummonGuardian (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx, uint32 level)
Definition at line 6389 of file SpellEffects.cpp.
References Map::Add(), Unit::AddGuardian(), Creature::AIM_Initialize(), SpellEntry::Category, Pet::Create(), SpellEntry::DurationIndex, SpellEntry::EffectMiscValue, CreatureInfo::Entry, Unit::FindGuardianWithEntry(), SummonPropertiesEntry::Flags, Map::GenerateLocalLowGuid(), Unit::GetCharmInfo(), Creature::GetCreatureInfo(), ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), Unit::GetProtectorPet(), Object::GetTypeId(), SummonPropertiesEntry::Group, GUARDIAN_PET, Object::HasFlag(), HIGHGUID_PET, SpellEntry::Id, Pet::InitializeSpellsForControllableGuardian(), Pet::InitStatsForLevel(), Unit::IsImmuneToNPC(), Unit::IsImmuneToPlayer(), Object::IsPlayer(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), m_caster, m_duration, m_IsTriggeredSpell, m_spellInfo, MANGOS_ASSERT, CreatureInfo::NpcFlags, PET_SAVE_AS_DELETED, PROTECTOR_PET, Object::SetByteFlag(), Unit::SetCanModifyStats(), Pet::SetControllableGuardian(), Pet::SetDuration(), Unit::setFaction(), Object::SetFlag(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Pet::SetLoading(), Pet::SetNoMountedFollow(), Pet::SetOwnerGuid(), Unit::SetPet(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), Creature::SetRespawnCoord(), Creature::SetSpellList(), Object::SetUInt32Value(), sLog, sObjectMgr, CreatureInfo::SpellList, SUMMON_PROP_FLAG_DO_NOT_FOLLOW_MOUNTED_SUMMONER, SUMMON_PROP_FLAG_DO_NOT_TOGGLE, SUMMON_PROP_FLAG_SAVE_PET_AUTOCAST, SUMMON_PROP_GROUP_PETS, SummonPropertiesEntry::Title, TYPEID_PLAYER, UNIT_BYTE2_FLAG_UNK5, UNIT_CREATED_BY_SPELL, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_NPC_FLAGS, CreatureInfo::UnitFlags, UNITNAME_SUMMON_TITLE_COMPANION, and UNITNAME_SUMMON_TITLE_PET.
Referenced by EffectSummonType().
DoSummonPet()
bool Spell::DoSummonPet (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx)
Definition at line 6627 of file SpellEffects.cpp.
References Map::Add(), Unit::AI(), Pet::AI(), Creature::AIM_Initialize(), CLASS_PRIEST, Pet::Create(), SpellEntry::EffectMiscValue, SpellEntry::EffectMultipleValue, CreatureInfo::Entry, Map::GenerateLocalLowGuid(), Unit::GetCharmInfo(), Unit::getClass(), ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Unit::GetPetGuid(), WorldObject::GetPhaseMask(), Object::GetTypeId(), Object::HasFlag(), HIGHGUID_PET, SpellEntry::Id, Pet::InitLevelupSpellsForLevel(), Pet::InitPetCreateSpells(), Pet::InitStatsForLevel(), Pet::isControlled(), Unit::IsImmuneToNPC(), Unit::IsImmuneToPlayer(), Object::IsPlayer(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), UnitAI::JustSummoned(), Pet::LoadPetFromDB(), m_caster, SpellCastTargets::m_destPos, m_duration, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, MANGOS_ASSERT, PET_SAVE_AS_CURRENT, REACT_DEFENSIVE, WorldObject::Relocate(), Pet::SavePetToDB(), Unit::SetCanModifyStats(), Pet::SetDuration(), Unit::setFaction(), Object::SetFlag(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Pet::SetLoading(), Pet::SetOwnerGuid(), Unit::SetPet(), Pet::setPetType(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), UnitAI::SetReactState(), Creature::SetRespawnCoord(), Object::SetUInt32Value(), sLog, sObjectMgr, SUMMON_PET, TARGET_FLAG_DEST_LOCATION, TYPEID_PLAYER, UNIT_CREATED_BY_SPELL, UNIT_FIELD_FLAGS, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_FLAG_PLAYER_CONTROLLED, Position::x, Position::y, and Position::z.
DoSummonPossessed()
bool Spell::DoSummonPossessed (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx, uint32 level)
Definition at line 6610 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, WorldObject::GetOrientation(), SpellEntry::Id, m_caster, m_spellInfo, MANGOS_ASSERT, sLog, and Unit::TakePossessOf().
Referenced by EffectSummonType().
DoSummonTotem()
bool Spell::DoSummonTotem (CreatureSummonPositions & list, SpellEffectIndex eff_idx, uint8 slot_dbc = 0)
Definition at line 6522 of file SpellEffects.cpp.
References Unit::_AddTotem(), SpellLog::AddLog(), Totem::Create(), damage, SpellEntry::EffectMiscValue, Map::GenerateLocalLowGuid(), ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), Unit::GetTotem(), Object::HasFlag(), HIGHGUID_UNIT, SpellEntry::Id, Unit::IsImmuneToNPC(), Unit::IsImmuneToPlayer(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), m_caster, m_duration, m_spellInfo, m_spellLog, MAX_TOTEM_SLOT, OnSummon(), Totem::SetDuration(), Unit::setFaction(), Object::SetFlag(), Unit::SetHealth(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Unit::SetLevel(), Unit::SetMaxHealth(), Unit::SetOwnerGuid(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), Creature::SetRespawnCoord(), Totem::SetTypeBySummonSpell(), Object::SetUInt32Value(), sLog, SMSG_TOTEM_CREATED, SPELL_EFFECT_SUMMON, Totem::Summon(), TOTEM_SLOT_NONE, TYPEID_PLAYER, UNIT_CREATED_BY_SPELL, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by EffectSummonType().
DoSummonVehicle()
bool Spell::DoSummonVehicle (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx, uint32 level)
Definition at line 6747 of file SpellEffects.cpp.
References SpellEntry::CalculateSimpleValue(), Unit::CastCustomSpell(), Unit::CastSpell(), SpellEntry::EffectMiscValue, TempSpawnSettings::faction, SummonPropertiesEntry::FactionId, Creature::ForcedDespawn(), ObjectMgr::GetCreatureTemplate(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), Unit::HasAuraType(), SpellEntry::Id, IsSpellHaveAura(), SQLStorage::LookupEntry(), m_caster, m_duration, m_spellInfo, MANGOS_ASSERT, MAX_VEHICLE_SEAT, TempSpawnSettings::ownerGuid, sLog, SPELL_AURA_CONTROL_VEHICLE, SPELL_RIDE_VEHICLE_HARDCODED, TempSpawnSettings::spellId, sSpellTemplate, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_CORPSE_DESPAWN, and TRIGGERED_OLD_TRIGGERED.
Referenced by EffectSummonType().
DoSummonWild()
bool Spell::DoSummonWild (CreatureSummonPositions & list, SummonPropertiesEntry const * prop, SpellEffectIndex effIdx, uint32 level)
Definition at line 6255 of file SpellEffects.cpp.
References CAST_AURA_NOT_PRESENT, CAST_TRIGGERED, GameObject::CastSpell(), Unit::CastSpell(), SpellEntry::EffectMiscValue, SummonPropertiesEntry::Flags, ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), GetPhaseMaskOverride(), Object::GetTypeId(), SummonPropertiesEntry::Group, SpellEntry::Id, Unit::IsPlayerControlled(), IsSpellSetRun(), m_caster, m_duration, m_spellInfo, m_trueCaster, MANGOS_ASSERT, sLog, SUMMON_PROP_FLAG_IGNORE_SUMMONERS_PHASE, SUMMON_PROP_GROUP_FRIENDLY, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_GAMEOBJECT, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by EffectSummonType().
EffectActivateObject()
void Spell::EffectActivateObject (SpellEffectIndex eff_idx)
Definition at line 11382 of file SpellEffects.cpp.
References ANIMATE_CUSTOM_0, ANIMATE_CUSTOM_1, ANIMATE_CUSTOM_2, ANIMATE_CUSTOM_3, Object::ApplyModFlag(), GameObjectTemplateAddon::artKits, CLOSE, CLOSE_AND_LOCK, DESPAWN, DESTROY, DISTURB, SpellEntry::EffectMiscValue, GameObject::ForcedDespawn(), frand(), GAMEOBJECT_FLAGS, gameObjTarget, WorldObject::GetAngle(), WorldObject::GetClosePoint(), Object::GetEntry(), WorldObject::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GameObject::GetTemplateAddon(), GO_FLAG_IN_USE, GO_FLAG_LOCKED, GO_FLAG_NO_INTERACT, GO_JUST_DEACTIVATED, SpellEntry::Id, IN_MILLISECONDS, INTERACTION_DISTANCE, LOCK, m_caster, M_PI_F, m_spellInfo, MAKE_ACTIVE, MAKE_INERT, MINUTE, OPEN, OPEN_AND_UNLOCK, REBUILD, GameObject::ResetDoorOrButton(), WorldObject::SendGameObjectCustomAnim(), Object::SetFlag(), GameObject::SetGoArtKit(), GameObject::SetLootState(), sLog, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, UNLOCK, urand(), GameObject::Use(), USE_ART_KIT_0, USE_ART_KIT_1, USE_ART_KIT_2, USE_ART_KIT_3, and GameObject::UseDoorOrButton().
EffectActivateRune()
void Spell::EffectActivateRune (SpellEffectIndex eff_idx)
Definition at line 12769 of file SpellEffects.cpp.
References Player::ActivateRunes(), CLASS_DEATH_KNIGHT, damage, SpellEntry::EffectMiscValue, Unit::getClass(), Object::GetTypeId(), m_caster, m_spellInfo, Player::ResyncRunes(), and TYPEID_PLAYER.
EffectActivateSpec()
void Spell::EffectActivateSpec (SpellEffectIndex eff_idx)
Definition at line 12845 of file SpellEffects.cpp.
References damage, Object::GetTypeId(), TYPEID_PLAYER, and unitTarget.
EffectAddComboPoints()
void Spell::EffectAddComboPoints (SpellEffectIndex eff_idx)
Definition at line 11216 of file SpellEffects.cpp.
References Unit::AddComboPoints(), damage, Object::IsPlayer(), Unit::IsVehicle(), m_caster, and unitTarget.
EffectAddExtraAttacks()
void Spell::EffectAddExtraAttacks (SpellEffectIndex eff_idx)
Definition at line 11883 of file SpellEffects.cpp.
References SpellLog::AddLog(), damage, Object::GetPackGUID(), Unit::IsAlive(), Unit::m_extraAttacks, m_spellLog, SPELL_EFFECT_ADD_EXTRA_ATTACKS, and unitTarget.
EffectAddFarsight()
void Spell::EffectAddFarsight (SpellEffectIndex eff_idx)
Definition at line 7081 of file SpellEffects.cpp.
References Map::Add(), Unit::AddDynObject(), DynamicObject::Create(), damage, DYNAMIC_OBJECT_FARSIGHT_FOCUS, Map::GenerateLocalLowGuid(), WorldObject::GetMap(), WorldObject::GetTransport(), Object::GetTypeId(), HIGHGUID_DYNAMICOBJECT, SpellEntry::Id, m_caster, m_currentBasePoints, SpellCastTargets::m_destPos, m_duration, m_spellInfo, m_targets, TARGET_NONE, TYPEID_PLAYER, Position::x, Position::y, and Position::z.
EffectAddHonor()
void Spell::EffectAddHonor (SpellEffectIndex eff_idx)
Definition at line 7139 of file SpellEffects.cpp.
References damage, DEBUG_FILTER_LOG, Object::GetEntry(), Unit::GetLevel(), Object::GetTypeId(), MaNGOS::Honor::hk_honor_at_level(), SpellEntry::Id, LOG_FILTER_SPELL_CAST, m_CastItem, m_spellInfo, sLog, TYPEID_PLAYER, and unitTarget.
EffectApplyAreaAura()
void Spell::EffectApplyAreaAura (SpellEffectIndex eff_idx)
Definition at line 5914 of file SpellEffects.cpp.
References SpellAuraHolder::AddAura(), CreateAura(), damage, GetScriptValue(), Unit::IsAlive(), m_caster, m_CastItem, m_currentBasePoints, m_spellAuraHolder, m_spellInfo, and unitTarget.
EffectApplyAura()
void Spell::EffectApplyAura (SpellEffectIndex eff_idx)
Definition at line 5061 of file SpellEffects.cpp.
References SpellAuraHolder::AddAura(), CreateAura(), damage, DEBUG_FILTER_LOG, SpellEntry::EffectApplyAuraName, GetAffectiveCaster(), GetScriptValue(), Object::GetTypeId(), Unit::IsAlive(), IsDeathOnlySpell(), IsDeathPersistentSpell(), LOG_FILTER_SPELL_CAST, m_CastItem, m_currentBasePoints, m_spellAuraHolder, m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectApplyGlyph()
void Spell::EffectApplyGlyph (SpellEffectIndex eff_idx)
Definition at line 11593 of file SpellEffects.cpp.
References Player::ApplyGlyph(), SpellEntry::EffectMiscValue, Player::GetGlyphSlot(), Object::GetTypeId(), m_caster, m_glyphIndex, m_spellInfo, SendCastResult(), Player::SendTalentsInfoData(), Player::SetGlyph(), sGlyphPropertiesStore, sGlyphSlotStore, SPELL_FAILED_INVALID_GLYPH, and TYPEID_PLAYER.
EffectBind()
void Spell::EffectBind (SpellEffectIndex eff_idx)
Definition at line 12855 of file SpellEffects.cpp.
References WorldLocation::coord_x, WorldLocation::coord_y, WorldLocation::coord_z, DEBUG_LOG, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectMiscValue, WorldObject::GetAreaId(), Object::GetGuidStr(), Object::GetObjectGuid(), WorldObject::GetPosition(), Object::GetTypeId(), SpellEntry::Id, WorldPacket::Initialize(), m_caster, m_spellInfo, WorldLocation::mapid, WorldLocation::orientation, Player::SendDirectMessage(), Player::SetHomebindToLocation(), sLog, SMSG_BINDPOINTUPDATE, SMSG_PLAYERBOUND, sSpellMgr, sTerrainMgr, TARGET_LOCATION_DATABASE, SpellTargetPosition::target_mapId, SpellTargetPosition::target_Orientation, SpellTargetPosition::target_X, SpellTargetPosition::target_Y, SpellTargetPosition::target_Z, TYPEID_PLAYER, and unitTarget.
EffectBlock()
void Spell::EffectBlock (SpellEffectIndex eff_idx)
Definition at line 11900 of file SpellEffects.cpp.
References m_caster, and Unit::SetCanBlock().
EffectBreakPlayerTargeting()
void Spell::EffectBreakPlayerTargeting (SpellEffectIndex eff_idx)
Definition at line 12224 of file SpellEffects.cpp.
References Unit::getAttackers(), WorldObject::GetClientGuidsIAmAt(), WorldObject::GetMap(), Object::GetObjectGuid(), Object::GetPackGUID(), Map::GetPlayer(), SMSG_BREAK_TARGET, SMSG_CLEAR_TARGET, TYPEID_UNIT, and unitTarget.
EffectCancelAura()
void Spell::EffectCancelAura (SpellEffectIndex eff_idx)
Definition at line 12980 of file SpellEffects.cpp.
References SpellEntry::EffectTriggerSpell, SQLStorage::LookupEntry(), m_spellInfo, Unit::RemoveAurasDueToSpell(), sLog, sSpellTemplate, and unitTarget.
EffectCharge()
void Spell::EffectCharge (SpellEffectIndex eff_idx)
Definition at line 12046 of file SpellEffects.cpp.
References Unit::Attack(), BASE_CHARGE_SPEED, Unit::CanAttackNow(), Unit::CanAttackSpell(), Unit::GetMotionMaster(), WorldObject::GetPositionZ(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, m_caster, m_spellInfo, MotionMaster::MoveCharge(), Player::SetFallInformation(), SpellEntry::speed, SPELL_ATTR_EX7_ATTACK_ON_CHARGE_TO_UNIT, SPELL_ATTR_USES_RANGED_SLOT, TYPEID_PLAYER, and unitTarget.
EffectChargeDest()
void Spell::EffectChargeDest (SpellEffectIndex eff_idx)
Definition at line 12067 of file SpellEffects.cpp.
References BASE_CHARGE_SPEED, SpellCastTargets::getDestination(), Unit::GetMotionMaster(), Object::GetTypeId(), SpellEntry::Id, m_caster, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, MotionMaster::MoveCharge(), SpellEntry::speed, TARGET_FLAG_DEST_LOCATION, and TYPEID_PLAYER.
EffectClearQuest()
void Spell::EffectClearQuest (SpellEffectIndex eff_idx)
Definition at line 4559 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Player::GetQuestSlotQuestId(), Player::getQuestStatusMap(), Object::GetTypeId(), SpellEntry::Id, m_caster, m_spellInfo, MAX_QUEST_LOG_SIZE, QUEST_STATUS_NONE, Player::SetQuestSlot(), Player::SetQuestStatus(), sLog, sObjectMgr, Player::TakeQuestSourceItem(), and TYPEID_PLAYER.
EffectCreateItem()
void Spell::EffectCreateItem (SpellEffectIndex eff_idx)
Definition at line 5484 of file SpellEffects.cpp.
References SpellLog::AddLog(), DoCreateItem(), SpellEntry::EffectItemType, SpellEntry::HasAttribute(), m_spellInfo, m_spellLog, SPELL_ATTR_DO_NOT_LOG, and SPELL_EFFECT_CREATE_ITEM.
EffectCreateItem2()
void Spell::EffectCreateItem2 (SpellEffectIndex eff_idx)
Definition at line 5490 of file SpellEffects.cpp.
References SpellLog::AddLog(), Loot::AutoStore(), Player::DestroyItemCount(), DoCreateItem(), SpellEntry::EffectItemType, Loot::GetLootItemsListFor(), Object::GetTypeId(), Player::HasItemCount(), SpellEntry::Id, IsLootCraftingSpell(), LOOT_SPELL, m_caster, m_spellInfo, m_spellLog, SPELL_EFFECT_CREATE_ITEM_2, TYPEID_PLAYER, and Player::UpdateCraftSkill().
EffectCreateRandomItem()
void Spell::EffectCreateRandomItem (SpellEffectIndex eff_idx)
Definition at line 5528 of file SpellEffects.cpp.
References SpellLog::AddLog(), Loot::AutoStore(), Loot::GetLootItemsListFor(), Object::GetTypeId(), SpellEntry::Id, LOOT_SPELL, m_caster, m_spellInfo, m_spellLog, SPELL_EFFECT_CREATE_RANDOM_ITEM, and TYPEID_PLAYER.
EffectCreateTamedPet()
void Spell::EffectCreateTamedPet (SpellEffectIndex eff_ifx)
Definition at line 13033 of file SpellEffects.cpp.
References Map::Add(), Creature::AIM_Initialize(), CLASS_HUNTER, Pet::Create(), SpellEntry::EffectMiscValue, Map::GenerateLocalLowGuid(), Unit::GetCharmInfo(), Unit::getClass(), WorldObject::GetClosePoint(), ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), Unit::GetLevel(), WorldObject::GetMap(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), HIGHGUID_PET, HUNTER_PET, SpellEntry::Id, Pet::InitLevelupSpellsForLevel(), Pet::InitPetCreateSpells(), Pet::InitStatsForLevel(), Pet::InitTalentForLevel(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), m_caster, m_spellInfo, PET_SAVE_AS_CURRENT, Player::PetSpellInitialize(), WorldObject::Relocate(), Pet::SavePetToDB(), Object::SetByteFlag(), Unit::SetCanModifyStats(), Unit::setFaction(), Pet::SetOwnerGuid(), Unit::SetPet(), CharmInfo::SetPetNumber(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), Creature::SetRespawnCoord(), Object::SetUInt32Value(), sLog, sObjectMgr, UNIT_BYTES_2_OFFSET_PET_FLAGS, UNIT_CAN_BE_ABANDONED, UNIT_CAN_BE_RENAMED, UNIT_CREATED_BY_SPELL, UNIT_FIELD_BYTES_2, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, and unitTarget.
EffectDestroyAllTotems()
void Spell::EffectDestroyAllTotems (SpellEffectIndex eff_idx)
Definition at line 12200 of file SpellEffects.cpp.
References Unit::CastCustomSpell(), damage, Unit::GetCreateMana(), Unit::GetTotem(), SQLStorage::LookupEntry(), m_caster, MAX_TOTEM_SLOT, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, and UNIT_CREATED_BY_SPELL.
EffectDisEnchant()
void Spell::EffectDisEnchant (SpellEffectIndex eff_idx)
Definition at line 11665 of file SpellEffects.cpp.
References ItemPrototype::DisenchantID, Loot::GetLootType(), Item::GetProto(), Object::GetTypeId(), SpellEntry::Id, itemTarget, LOOT_DISENCHANTING, m_caster, Object::m_loot, m_spellInfo, Loot::ShowContentTo(), TYPEID_PLAYER, and Player::UpdateCraftSkill().
EffectDismissPet()
void Spell::EffectDismissPet (SpellEffectIndex eff_idx)
Definition at line 11745 of file SpellEffects.cpp.
References SpellLog::AddLog(), Object::GetPackGUID(), Unit::GetPet(), Object::GetTypeId(), Unit::IsAlive(), m_caster, m_spellLog, PET_SAVE_NOT_IN_SLOT, SpellLog::SendToSet(), SPELL_EFFECT_DISMISS_PET, TYPEID_PLAYER, and Pet::Unsummon().
EffectDispel()
void Spell::EffectDispel (SpellEffectIndex eff_idx)
Definition at line 6827 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, EvaluateResultLists(), GetDispellMask(), Unit::GetSpellAuraHolderMap(), SpellAuraHolder::GetSpellProto(), SpellAuraHolder::GetStackAmount(), SpellEntry::Id, SpellAuraHolder::IsDispellableByMask(), m_caster, m_spellInfo, ProcessDispelList(), and unitTarget.
EffectDispelMechanic()
void Spell::EffectDispelMechanic (SpellEffectIndex eff_idx)
Definition at line 6854 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, EvaluateResultLists(), Unit::GetSpellAuraHolderMap(), m_spellInfo, ProcessDispelList(), and unitTarget.
EffectDistract()
void Spell::EffectDistract (SpellEffectIndex eff_idx)
Definition at line 6986 of file SpellEffects.cpp.
References Unit::clearUnitState(), damage, WorldObject::GetAngle(), Unit::GetMotionMaster(), Object::GetTypeId(), Unit::hasUnitState(), IN_MILLISECONDS, Unit::IsInCombat(), SpellCastTargets::m_destPos, m_targets, MotionMaster::MoveDistract(), Unit::SetFacingTo(), WorldObject::SetOrientation(), TYPEID_UNIT, UNIT_STAT_CAN_NOT_REACT, UNIT_STAT_MOVING, unitTarget, Position::x, and Position::y.
EffectDualWield()
void Spell::EffectDualWield (SpellEffectIndex eff_idx)
Definition at line 6974 of file SpellEffects.cpp.
References Unit::SetCanDualWield(), and unitTarget.
EffectDuel()
void Spell::EffectDuel (SpellEffectIndex eff_idx)
Definition at line 11230 of file SpellEffects.cpp.
References Map::Add(), Unit::AddGameObject(), SpellLog::AddLog(), GameObject::AIM_Initialize(), AREA_FLAG_DUEL, GameObject::Create(), Player::duel, SpellEntry::EffectMiscValue, AreaTableEntry::flags, GAMEOBJECT_FACTION, GAMEOBJECT_LEVEL, Map::GenerateLocalLowGuid(), GetAreaEntryByAreaID(), WorldObject::GetAreaId(), Unit::GetFaction(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Player::GetSession(), Player::GetSocial(), Object::GetTypeId(), PlayerSocial::HasIgnore(), HIGHGUID_GAMEOBJECT, SpellEntry::Id, IN_MILLISECONDS, DuelInfo::initiator, m_caster, m_duration, m_spellInfo, m_spellLog, m_trueCaster, DuelInfo::opponent, PLAYER_DUEL_ARBITER, SendCastResult(), WorldSession::SendPacket(), Object::SetGuidValue(), GameObject::SetRespawnTime(), GameObject::SetSpawnerGuid(), GameObject::SetSpellId(), Object::SetUInt32Value(), SMSG_DUEL_REQUESTED, SPELL_EFFECT_DUEL, SPELL_FAILED_NO_DUELING, DuelInfo::startTime, DuelInfo::startTimer, TYPEID_PLAYER, unitTarget, and Unit::UpdateAllowedPositionZ().
EffectDummy()
void Spell::EffectDummy (SpellEffectIndex eff_idx)
Definition at line 772 of file SpellEffects.cpp.
References Unit::AddPetAura(), Unit::AddThreat(), Unit::addUnitState(), Unit::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_EVENTAI_A, AI_EVENT_CUSTOM_EVENTAI_B, AI_EVENT_CUSTOM_EVENTAI_C, ALLIANCE, UnitAI::AttackStart(), Unit::AttackStop(), BASE_ATTACK, SpellEntry::CalculateSimpleValue(), Unit::CanAssistSpell(), Unit::CanAttack(), Unit::CanAttackOnSight(), Unit::CanReachWithMeleeAttack(), ScriptMgr::CanSpellEffectStartDBScript(), Unit::CastCustomSpell(), Unit::CastSpell(), CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, ClearCastItem(), Unit::clearUnitState(), countof, CREATURE_TYPE_BEAST, CURRENT_CHANNELED_SPELL, damage, Unit::DealDamage(), DEBUG_FILTER_LOG, ItemPrototype::Delay, Unit::DeleteThreatList(), DIRECT_DAMAGE, SpellEntry::Dispel, DISPEL_DISEASE, DISPEL_POISON, SpellEntry::DmgMultiplier, DoCreateItem(), DoScriptText(), SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectBasePoints, finish(), Creature::ForcedDespawn(), frand(), gameObjTarget, GENDER_MALE, GetAffectiveCaster(), WorldObject::GetAreaId(), Unit::GetAura(), SpellAuraHolder::GetAuraDuration(), Unit::GetAurasByType(), Aura::GetAuraTicks(), ReputationMgr::GetBaseReputation(), Unit::getClass(), GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), Player::GetCorpse(), Creature::GetCreatureInfo(), Unit::GetCreatureType(), SpellCastTargets::getDestination(), Map::GetDifficulty(), Item::GetEnchantmentId(), Object::GetEntry(), ObjectGuid::GetEntry(), Unit::getGender(), Object::GetGUIDLow(), Unit::GetHealth(), Unit::GetHealthPercent(), Aura::GetHolder(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Unit::GetMotionMaster(), WorldObject::GetNearPoint2d(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Unit::GetOwner(), Unit::GetPet(), Map::GetPlayer(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetPowerType(), Unit::GetProtectorPet(), Item::GetProto(), GetRandomGenerator(), Player::GetReputationMgr(), Unit::GetSpawner(), Unit::GetSpeedRate(), Unit::GetSpellAuraHolder(), Unit::GetSpellAuraHolderMap(), GetSpellMaxRange(), GetSpellRecoveryTime(), GetSpellSchoolMask(), SpellTargetMgr::GetSpellTargetingData(), ThreatManager::getThreat(), Unit::getThreatManager(), Unit::GetTotalAttackPowerValue(), Unit::GetTotem(), Object::GetTypeId(), Map::GetUnit(), Unit::GetVictim(), Player::GetWeaponForAttack(), GO_JUST_DEACTIVATED, Unit::HasAura(), Unit::HasAuraType(), Creature::HasLootRecipient(), Unit::hasUnitState(), HEAL, SpellEntry::Id, IN_MILLISECONDS, Unit::InterruptSpell(), Unit::IsAlive(), Unit::IsAllTotemSlotsUsed(), Object::IsCreature(), Map::IsDungeon(), SpellEntry::IsFitToFamilyMask(), Unit::IsInCombat(), Unit::IsMounted(), Creature::IsPet(), Object::IsPlayer(), Map::IsRegularDifficulty(), GameObject::IsSpawned(), WorldObject::IsWithinLOSInMap(), ITEM_ENCHANTMENT_TYPE_COMBAT_SPELL, ITEM_LIMIT_CATEGORY_MANA_GEM, itemTarget, JUST_DIED, LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), m_caster, m_CastItem, m_currentBasePoints, m_damage, m_duration, m_originalCasterGUID, M_PI_F, m_scriptValue, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_triggeredByAuraSpell, m_triggeredBySpellInfo, m_trueCaster, m_UniqueTargetInfo, MAX_EFFECT_INDEX, MINUTE, ThreatManager::modifyThreatPercent(), Unit::MonsterMoveWithSpeed(), MOVE_FLIGHT, MOVE_RUN, MotionMaster::MovementExpired(), OFF_ATTACK, PLAY_TARGET, WorldObject::PlayDirectSound(), WorldObject::PlaySpellVisual(), POWER_MANA, Player::QueueOrAddResurrectRequest(), RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, SpellEntry::rangeIndex, GameObject::Refresh(), Unit::RemoveAllAuras(), Unit::RemoveAurasDueToSpell(), Unit::RemoveAuraStack(), Unit::RemoveAurasWithDispelType(), Object::RemoveFlag(), Unit::RemoveSpellsCausingAura(), Player::RewardPlayerAndGroupAtEventCredit(), roll_chance_i(), SCRIPT_TYPE_SPELL, Map::ScriptsStart(), UnitAI::SendAIEvent(), SpellAuraHolder::SendAuraUpdate(), SendCastResult(), SpellAuraHolder::SetAuraDuration(), SpellAuraHolder::SetAuraMaxDuration(), Unit::SetDeathState(), Unit::SetDisplayId(), Unit::SetFacingTo(), Unit::SetFacingToObject(), Unit::setFaction(), Object::SetFlag(), Unit::SetHealth(), Unit::SetHealthPercent(), Unit::SetImmuneToNPC(), Creature::SetLootRecipient(), GameObject::SetLootState(), Unit::SetMaxHealth(), ReputationMgr::SetReputation(), GameObject::SetRespawnTime(), Unit::SetStandState(), sFactionStore, sLog, SMSG_SPIRIT_HEALER_CONFIRM, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_DUMMY, SPELL_AURA_FLY, SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED, SPELL_AURA_MOUNTED, SPELL_AURA_PERIODIC_HEAL, SPELL_DIRECT_DAMAGE, SPELL_EFFECT_CREATE_ITEM, SPELL_FAILED_TARGET_ENEMY, SPELL_FAILED_TARGET_NOT_DEAD, SPELL_MISS_NONE, SPELL_SCHOOL_MASK_FROST, SPELL_SCHOOL_MASK_NORMAL, Unit::SpellBaseDamageBonusDone(), Unit::SpellBaseDamageBonusTaken(), Unit::SpellBonusWithCoeffs(), SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, Unit::SpellHealingBonusTaken(), SpellEntry::SpellIconID, SpellItemEnchantmentEntry::spellid, SpellEntry::SpellVisual, sScriptDevAIMgr, sSpellCastTimesStore, sSpellItemEnchantmentStore, sSpellMgr, sSpellRangeStore, sSpellTemplate, Unit::Suicide(), WorldObject::SummonCreature(), TARGET_FLAG_DEST_LOCATION, TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_LOCK, TARGET_TYPE_UNIT, TARGET_TYPE_UNIT_DEST, TEMP_ENCHANTMENT_SLOT, TEMPSPAWN_TIMED_OOC_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TOTEM_SLOT_FIRE, TRIGGERED_IGNORE_CURRENT_CASTED_SPELL, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, SpellItemEnchantmentEntry::type, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_UNINTERACTIBLE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, UNIT_STAND_STATE_DEAD, UNIT_STAT_FOLLOW, UNIT_STAT_FOLLOW_MOVE, UNIT_STAT_NO_FREE_MOVE, UNIT_STAT_ROOT, unitTarget, urand(), and Cell::VisitGridObjects().
EffectDurabilityDamage()
void Spell::EffectDurabilityDamage (SpellEffectIndex eff_idx)
Definition at line 12256 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, Object::GetTypeId(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectDurabilityDamagePCT()
void Spell::EffectDurabilityDamagePCT (SpellEffectIndex eff_idx)
Definition at line 12279 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, Object::GetTypeId(), INVENTORY_SLOT_BAG_0, INVENTORY_SLOT_BAG_END, m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectEmpty()
void Spell::EffectEmpty (SpellEffectIndex eff_idx)
Definition at line 229 of file SpellEffects.cpp.
EffectEnchantHeldItem()
void Spell::EffectEnchantHeldItem (SpellEffectIndex eff_idx)
Definition at line 11623 of file SpellEffects.cpp.
References Player::ApplyEnchantment(), SpellEntry::EffectMiscValue, EQUIPMENT_SLOT_MAINHAND, Item::GetEnchantmentId(), Player::GetItemByPos(), Object::GetObjectGuid(), Object::GetTypeId(), IN_MILLISECONDS, INVENTORY_SLOT_BAG_0, m_caster, m_currentBasePoints, m_duration, m_spellInfo, Item::SetEnchantment(), sSpellItemEnchantmentStore, TEMP_ENCHANTMENT_SLOT, TYPEID_PLAYER, and unitTarget.
EffectEnchantItemPerm()
void Spell::EffectEnchantItemPerm (SpellEffectIndex eff_idx)
Definition at line 7181 of file SpellEffects.cpp.
References Player::ApplyEnchantment(), CONFIG_BOOL_GM_LOG_TRADE, Player::DestroyItemCount(), DoCreateItem(), SpellEntry::EffectItemType, SpellEntry::EffectMiscValue, ItemPrototype::Flags, WorldSession::GetAccountId(), Object::GetEntry(), WorldObject::GetName(), Object::GetObjectGuid(), Item::GetOwner(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), Object::GetTypeId(), SpellEntry::Id, ItemPrototype::IsVellum(), ITEM_FLAG_NO_REAGENT_COST, ItemPrototype::ItemId, itemTarget, m_caster, m_CastItem, m_spellInfo, ItemPrototype::Name1, PERM_ENCHANTMENT_SLOT, SEC_PLAYER, Item::SetEnchantment(), sLog, sSpellItemEnchantmentStore, sWorld, TYPEID_PLAYER, unitTarget, and Player::UpdateCraftSkill().
EffectEnchantItemPrismatic()
void Spell::EffectEnchantItemPrismatic (SpellEffectIndex eff_idx)
Definition at line 7237 of file SpellEffects.cpp.
References Player::ApplyEnchantment(), CONFIG_BOOL_GM_LOG_TRADE, SpellEntry::EffectMiscValue, WorldSession::GetAccountId(), Object::GetEntry(), WorldObject::GetName(), Object::GetObjectGuid(), Item::GetOwner(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), Object::GetTypeId(), SpellEntry::Id, ITEM_ENCHANTMENT_TYPE_PRISMATIC_SOCKET, itemTarget, m_caster, m_spellInfo, ItemPrototype::Name1, PRISMATIC_ENCHANTMENT_SLOT, SEC_PLAYER, Item::SetEnchantment(), sLog, SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC, sSpellItemEnchantmentStore, sWorld, SpellItemEnchantmentEntry::type, and TYPEID_PLAYER.
EffectEnchantItemTmp()
void Spell::EffectEnchantItemTmp (SpellEffectIndex eff_idx)
Definition at line 7295 of file SpellEffects.cpp.
References Player::ApplyEnchantment(), CONFIG_BOOL_GM_LOG_TRADE, damage, SpellEntry::EffectMiscValue, WorldSession::GetAccountId(), Object::GetEntry(), WorldObject::GetName(), Object::GetObjectGuid(), Item::GetOwner(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), Object::GetTypeId(), SpellEntry::Id, itemTarget, SQLStorage::LookupEntry(), m_caster, m_spellInfo, ItemPrototype::Name1, SEC_PLAYER, Item::SetEnchantment(), SpellCastTargets::setItemTarget(), sLog, Spell(), SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellStart(), SpellEntry::SpellVisual, sSpellItemEnchantmentStore, sSpellTemplate, sWorld, TEMP_ENCHANTMENT_SLOT, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
EffectEnergisePct()
void Spell::EffectEnergisePct (SpellEffectIndex eff_idx)
Definition at line 5693 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, Unit::EnergizeBySpell(), Unit::GetMaxPower(), Unit::IsAlive(), m_caster, m_spellInfo, MAX_POWERS, and unitTarget.
EffectEnergize()
void Spell::EffectEnergize (SpellEffectIndex eff_idx)
Definition at line 5580 of file SpellEffects.cpp.
References Unit::CastSpell(), CLASS_ROGUE, damage, SpellEntry::EffectMiscValue, ELIXIR_FLASK_MASK, ELIXIR_SHATTRATH_MASK, ELIXIR_UNSTABLE_MASK, Unit::EnergizeBySpell(), Unit::getClass(), Unit::GetCreateMana(), Aura::GetId(), Unit::GetLevel(), Unit::GetMaxPower(), Unit::GetSpellAuraHolderMap(), Object::GetTypeId(), Unit::HasAura(), Player::HasSkill(), SpellEntry::Id, Unit::IsAlive(), SQLStorage::LookupEntry(), m_caster, m_CastItem, m_spellInfo, MAX_POWERS, SKILL_ENGINEERING, SPELLFAMILY_POTION, SpellEntry::SpellFamilyName, SpellEntry::spellLevel, sSpellMgr, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, unitTarget, and urand().
EffectEnvironmentalDMG()
void Spell::EffectEnvironmentalDMG (SpellEffectIndex eff_idx)
Definition at line 263 of file SpellEffects.cpp.
References Unit::CalculateDamageAbsorbAndResist(), SpellEntry::CalculateSimpleValue(), damage, DAMAGE_FIRE, GetSpellSchoolMask(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, m_caster, m_spellInfo, m_trueCaster, Unit::SendSpellNonMeleeDamageLog(), SPELL_ATTR_EX5_NO_PARTIAL_RESISTS, SPELL_DIRECT_DAMAGE, and TYPEID_PLAYER.
EffectFeedPet()
void Spell::EffectFeedPet (SpellEffectIndex eff_idx)
Definition at line 11712 of file SpellEffects.cpp.
References SpellLog::AddLog(), Unit::CastCustomSpell(), Player::DestroyItemCount(), SpellEntry::EffectTriggerSpell, Pet::GetCurrentFoodBenefitLevel(), Object::GetEntry(), SpellCastTargets::getItemTarget(), Unit::GetPet(), Item::GetProto(), Object::GetTypeId(), Unit::IsAlive(), ItemPrototype::ItemLevel, m_caster, m_spellInfo, m_spellLog, m_targets, SpellLog::SendToSet(), SPELL_EFFECT_FEED_PET, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
EffectForceCast()
void Spell::EffectForceCast (SpellEffectIndex eff_idx)
Definition at line 4591 of file SpellEffects.cpp.
References Unit::CastCustomSpell(), Unit::CastSpell(), damage, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, SpellCastTargets::getDestination(), WorldObject::GetPosition(), SpellEntry::Id, IsSpellRequireTarget(), SQLStorage::LookupEntry(), m_caster, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, SpellCastTargets::setDestination(), SpellCastTargets::setUnitTarget(), sLog, SPELL_EFFECT_FORCE_CAST_2, SPELL_EFFECT_FORCE_CAST_WITH_VALUE, sSpellTemplate, TARGET_FLAG_DEST_LOCATION, TARGET_LOCATION_UNIT_MINION_POSITION, SpellEntry::Targets, TRIGGERED_OLD_TRIGGERED, and unitTarget.
EffectHeal()
void Spell::EffectHeal (SpellEffectIndex eff_idx)
Definition at line 5196 of file SpellEffects.cpp.
References AURA_STATE_SWIFTMEND, BASE_ATTACK, damage, SpellEntry::EffectAmplitude, SpellEntry::EffectApplyAuraName, GetAffectiveCaster(), Unit::GetAura(), Aura::GetAuraDuration(), Unit::GetAurasByType(), GetCaster(), Aura::GetCasterGuid(), Object::GetGUIDLow(), Aura::GetId(), Unit::GetMaxHealth(), Aura::GetModifier(), Object::GetObjectGuid(), GetSpellDuration(), Aura::GetSpellProto(), GetSpellSchoolMask(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Unit::HasAura(), Unit::HasAuraState(), Player::HasSkill(), HEAL, SpellEntry::Id, Unit::IsAlive(), Modifier::m_amount, m_caster, m_healingPerEffect, m_spellInfo, m_targets, Unit::RemoveAurasByCasterSpell(), Unit::RemoveAurasDueToSpell(), SKILL_ENGINEERING, sLog, SPELL_AURA_DUMMY, SPELL_AURA_PERIODIC_HEAL, Unit::SpellBaseHealingBonusDone(), SPELLFAMILY_DRUID, SPELLFAMILY_POTION, SPELLFAMILY_SHAMAN, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), SpellEntry::TargetAuraState, TYPEID_PLAYER, and unitTarget.
EffectHealMaxHealth()
void Spell::EffectHealMaxHealth (SpellEffectIndex eff_idx)
Definition at line 8025 of file SpellEffects.cpp.
References Unit::GetMaxHealth(), Unit::IsAlive(), m_caster, m_healing, and unitTarget.
EffectHealMechanical()
void Spell::EffectHealMechanical (SpellEffectIndex eff_idx)
Definition at line 5344 of file SpellEffects.cpp.
References Unit::CalculateHealAbsorb(), damage, GetAffectiveCaster(), HEAL, Unit::IsAlive(), m_healingPerEffect, m_spellInfo, Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), and unitTarget.
EffectHealPct()
void Spell::EffectHealPct (SpellEffectIndex eff_idx)
Definition at line 5323 of file SpellEffects.cpp.
References Unit::CalculateHealAbsorb(), damage, GetAffectiveCaster(), Unit::GetMaxHealth(), HEAL, Unit::IsAlive(), m_healingPerEffect, m_spellInfo, Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), and unitTarget.
EffectHealthLeech()
void Spell::EffectHealthLeech (SpellEffectIndex eff_idx)
Definition at line 5364 of file SpellEffects.cpp.
References Unit::CalculateHealAbsorb(), damage, Unit::DealHeal(), DEBUG_FILTER_LOG, SpellEntry::EffectMultipleValue, Unit::GetHealth(), WorldObject::GetSpellModOwner(), HEAL, SpellEntry::Id, Unit::IsAlive(), LOG_FILTER_SPELL_CAST, m_caster, m_spellInfo, Unit::SpellHealingBonusTaken(), SPELLMOD_MULTIPLE_VALUE, Unit::SpellNonMeleeDamageLog(), and unitTarget.
EffectInebriate()
void Spell::EffectInebriate (SpellEffectIndex eff_idx)
Definition at line 11693 of file SpellEffects.cpp.
References Unit::CastSpell(), damage, Player::GetDrunkValue(), Object::GetEntry(), Object::GetTypeId(), m_CastItem, roll_chance_i(), Player::SetDrunkValue(), TRIGGERED_NONE, TYPEID_PLAYER, and unitTarget.
EffectInstaKill()
void Spell::EffectInstaKill (SpellEffectIndex eff_idx)
Definition at line 244 of file SpellEffects.cpp.
References Unit::DealDamage(), finish(), GetCastingObject(), Unit::GetHealth(), Object::GetObjectGuid(), Object::GetTypeId(), SpellEntry::Id, INSTAKILL, Unit::IsAlive(), m_caster, m_spellInfo, WorldObject::SendMessageToSet(), SMSG_SPELLINSTAKILLLOG, SPELL_SCHOOL_MASK_NORMAL, TYPEID_GAMEOBJECT, and unitTarget.
EffectInterruptCast()
void Spell::EffectInterruptCast (SpellEffectIndex eff_idx)
Definition at line 8037 of file SpellEffects.cpp.
References SpellLog::AddLog(), Unit::CalculateAuraDuration(), CURRENT_FIRST_NON_MELEE_SPELL, CURRENT_MAX_SPELL, Unit::GetCurrentSpell(), Object::GetPackGUID(), GetSpellDuration(), GetSpellSchoolMask(), SpellEntry::Id, Unit::InterruptSpell(), Unit::IsAlive(), WorldObject::LockOutSpells(), m_caster, m_spellInfo, m_spellLog, SPELL_EFFECT_INTERRUPT_CAST, and unitTarget.
EffectJump()
void Spell::EffectJump (SpellEffectIndex eff_idx)
Definition at line 4815 of file SpellEffects.cpp.
References baseMoveSpeed, CONTACT_DISTANCE, DIST_CALC_NONE, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectMiscValue, SpellEntry::EffectMiscValueB, SpellEntry::EffectMultipleValue, EVENT_JUMP, gameObjTarget, WorldObject::GetContactPoint(), SpellCastTargets::getDestination(), WorldObject::GetDistance2d(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), Unit::GetSpeed(), Object::GetTypeId(), Map::GetUnit(), SpellCastTargets::getUnitTarget(), Unit::GetVictim(), Movement::gravity, SpellEntry::Id, Object::IsCreature(), Unit::IsTaxiFlying(), Object::IsUnit(), m_caster, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, MOVE_RUN, MotionMaster::MoveJumpFacingVerticalSpeed(), Position::o, sLog, TARGET_FLAG_DEST_LOCATION, TARGET_LOCATION_UNIT_BACK, TYPEID_PLAYER, unitTarget, Unit::UpdateAllowedPositionZ(), Position::x, Position::y, and Position::z.
EffectKillCreditGroup()
void Spell::EffectKillCreditGroup (SpellEffectIndex eff_idx)
Definition at line 12753 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectKillCreditPersonal()
void Spell::EffectKillCreditPersonal (SpellEffectIndex eff_idx)
Definition at line 12745 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectKnockBack()
void Spell::EffectKnockBack (SpellEffectIndex eff_idx)
Definition at line 12082 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, SpellEntry::Id, Unit::KnockBackFrom(), m_caster, m_spellInfo, m_triggeredByAuraSpell, Unit::RemoveAurasDueToSpell(), and unitTarget.
EffectKnockBackFromPosition()
void Spell::EffectKnockBackFromPosition (SpellEffectIndex eff_idx)
Definition at line 12996 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, WorldObject::GetAngle(), SpellCastTargets::getDestination(), WorldObject::GetPosition(), Unit::KnockBackWithAngle(), m_caster, M_PI_F, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, TARGET_FLAG_DEST_LOCATION, and unitTarget.
EffectLeapBack()
void Spell::EffectLeapBack (SpellEffectIndex eff_idx)
Definition at line 11918 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, Unit::IsTaxiFlying(), Unit::KnockBackFrom(), m_caster, m_spellInfo, and unitTarget.
EffectLeapForward()
void Spell::EffectLeapForward (SpellEffectIndex eff_idx)
Definition at line 11905 of file SpellEffects.cpp.
References SpellCastTargets::getDestination(), WorldObject::GetOrientation(), m_caster, m_targets, Unit::NearTeleportTo(), and unitTarget.
EffectLearnPetSpell()
void Spell::EffectLearnPetSpell (SpellEffectIndex eff_idx)
Definition at line 7657 of file SpellEffects.cpp.
References DEBUG_LOG, SpellEntry::EffectTriggerSpell, GetCastingObject(), Object::GetGuidStr(), Unit::GetPet(), Object::GetTypeId(), SpellEntry::Id, Unit::IsAlive(), Pet::learnSpell(), SQLStorage::LookupEntry(), m_caster, m_spellInfo, PET_SAVE_AS_CURRENT, Player::PetSpellInitialize(), Pet::SavePetToDB(), sSpellTemplate, and TYPEID_PLAYER.
Referenced by EffectLearnSpell().
EffectLearnSkill()
void Spell::EffectLearnSkill (SpellEffectIndex eff_idx)
Definition at line 7121 of file SpellEffects.cpp.
References damage, DEBUG_LOG, SpellEntry::EffectMiscValue, GetCastingObject(), Object::GetGuidStr(), Object::GetTypeId(), m_spellInfo, Player::SetSkillStep(), TYPEID_PLAYER, and unitTarget.
EffectLearnSpell()
void Spell::EffectLearnSpell (SpellEffectIndex eff_idx)
Definition at line 6805 of file SpellEffects.cpp.
References damage, DEBUG_LOG, EffectLearnPetSpell(), SpellEntry::EffectTriggerSpell, GetCastingObject(), Object::GetGuidStr(), Object::GetTypeId(), SpellEntry::Id, Player::learnSpell(), m_caster, m_spellInfo, SPELL_ID_GENERIC_LEARN, SPELL_ID_GENERIC_LEARN_PET, TYPEID_PLAYER, and unitTarget.
EffectMilling()
void Spell::EffectMilling (SpellEffectIndex eff_idx)
Definition at line 12505 of file SpellEffects.cpp.
References CONFIG_BOOL_SKILL_MILLING, Item::GetProto(), Player::GetSkillValuePure(), Object::GetTypeId(), itemTarget, LOOT_MILLING, m_caster, Object::m_loot, ItemPrototype::RequiredSkillRank, Loot::ShowContentTo(), SKILL_INSCRIPTION, sWorld, TYPEID_PLAYER, and Player::UpdateGatherSkill().
EffectModifyThreatPercent()
void Spell::EffectModifyThreatPercent (SpellEffectIndex eff_idx)
Definition at line 12305 of file SpellEffects.cpp.
References damage, Unit::getThreatManager(), m_caster, ThreatManager::modifyThreatPercent(), and unitTarget.
EffectNULL()
void Spell::EffectNULL (SpellEffectIndex eff_idx)
Definition at line 234 of file SpellEffects.cpp.
References DEBUG_LOG.
EffectOpenLock()
void Spell::EffectOpenLock (SpellEffectIndex eff_idx)
Definition at line 5789 of file SpellEffects.cpp.
References SpellLog::AddLog(), GameObject::AddToSkillupList(), DEBUG_LOG, SpellEntry::EffectMiscValue, gameObjTarget, GameObject::GetGOInfo(), GameObjectInfo::GetLockId(), Object::GetObjectGuid(), Item::GetOwnerGuid(), Object::GetPackGUID(), Item::GetProto(), Player::GetSkillValuePure(), Object::GetTypeId(), GameObject::IsInSkillupList(), ITEM_DYNFLAG_UNLOCKED, ITEM_FIELD_FLAGS, itemTarget, ItemPrototype::LockID, LOOT_SKINNING, m_caster, m_CastItem, m_effectSkillInfo, Object::m_loot, m_spellInfo, m_spellLog, SendLoot(), Object::SetFlag(), SKILL_NONE, Spell::EffectSkillInfo::skillId, SPELL_EFFECT_OPEN_LOCK, TYPEID_PLAYER, and Player::UpdateGatherSkill().
EffectParry()
void Spell::EffectParry (SpellEffectIndex eff_idx)
Definition at line 11895 of file SpellEffects.cpp.
References m_caster, and Unit::SetCanParry().
EffectPersistentAA()
void Spell::EffectPersistentAA (SpellEffectIndex eff_idx)
Definition at line 5544 of file SpellEffects.cpp.
References Map::Add(), Unit::AddDynObject(), DynamicObject::Create(), damage, DYNAMIC_OBJECT_AREA_SPELL, EFFECT_INDEX_0, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectRadiusIndex, Map::GenerateLocalLowGuid(), GetAffectiveCaster(), WorldObject::GetMap(), WorldObject::GetSpellModOwner(), GetSpellRadius(), WorldObject::GetTransport(), HIGHGUID_DYNAMICOBJECT, SpellEntry::Id, IsChanneledSpell(), m_caster, m_currentBasePoints, SpellCastTargets::m_destPos, m_duration, m_spellInfo, m_targets, Object::SendForcedObjectUpdate(), Unit::SetChannelObject(), SPELLMOD_RADIUS, sSpellRadiusStore, Position::x, Position::y, and Position::z.
EffectPickPocket()
void Spell::EffectPickPocket (SpellEffectIndex eff_idx)
Definition at line 7007 of file SpellEffects.cpp.
References Unit::AttackedBy(), AURA_INTERRUPT_FLAG_INTERACTING, Unit::CanAttackNow(), Creature::CanRestockPickpocketLoot(), CREATURE_LOOT_STATUS_NONE, CREATURE_LOOT_STATUS_PICKPOCKETED, Unit::GetLevel(), Creature::GetLootStatus(), Loot::GetLootType(), Object::GetObjectGuid(), Object::GetTypeId(), LOOT_ERROR_ALREADY_PICKPOCKETED, LOOT_PICKPOCKETING, m_caster, Object::m_loot, Unit::RemoveAurasWithInterruptFlags(), Player::SendLootError(), Creature::SetLootStatus(), Loot::ShowContentTo(), TYPEID_PLAYER, TYPEID_UNIT, unitTarget, and urand().
EffectPlayMusic()
void Spell::EffectPlayMusic (SpellEffectIndex eff_idx)
Definition at line 12822 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), SpellEntry::Id, m_caster, m_spellInfo, PLAY_TARGET, WorldObject::PlayMusic(), sLog, sSoundEntriesStore, TYPEID_PLAYER, and unitTarget.
EffectPlaySound()
void Spell::EffectPlaySound (SpellEffectIndex eff_idx)
Definition at line 12807 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), SpellEntry::Id, m_spellInfo, PLAY_TARGET, WorldObject::PlayDirectSound(), sLog, sSoundEntriesStore, TYPEID_PLAYER, and unitTarget.
EffectPowerBurn()
void Spell::EffectPowerBurn (SpellEffectIndex eff_idx)
Definition at line 5151 of file SpellEffects.cpp.
References SpellLog::AddLog(), CalculateSpellEffectDamage(), damage, SpellEntry::DmgClass, SpellEntry::EffectMiscValue, SpellEntry::EffectMultipleValue, Unit::GetMaxPower(), Object::GetPackGUID(), Unit::GetPower(), Unit::GetPowerType(), Unit::GetResilienceRatingDamageReduction(), WorldObject::GetSpellModOwner(), SpellEntry::Id, Unit::IsAlive(), m_caster, m_damagePerEffect, m_spellInfo, m_spellLog, SpellEntry::ManaCostPercentage, MAX_POWERS, Unit::ModifyPower(), SPELL_EFFECT_POWER_BURN, SPELLMOD_MULTIPLE_VALUE, and unitTarget.
EffectPowerDrain()
void Spell::EffectPowerDrain (SpellEffectIndex eff_idx)
Definition at line 5094 of file SpellEffects.cpp.
References SpellLog::AddLog(), damage, SpellEntry::DmgClass, SpellEntry::EffectMiscValue, SpellEntry::EffectMultipleValue, Unit::EnergizeBySpell(), Object::GetPackGUID(), Unit::GetPower(), Unit::GetPowerType(), Unit::GetResilienceRatingDamageReduction(), WorldObject::GetSpellModOwner(), SpellEntry::Id, Unit::IsAlive(), m_caster, m_spellInfo, m_spellLog, m_spellSchoolMask, MAX_POWERS, Unit::ModifyPower(), SPELL_DIRECT_DAMAGE, SPELL_EFFECT_POWER_DRAIN, Unit::SpellDamageBonusDone(), Unit::SpellDamageBonusTaken(), SPELLMOD_MULTIPLE_VALUE, and unitTarget.
EffectProficiency()
void Spell::EffectProficiency (SpellEffectIndex eff_idx)
Definition at line 5895 of file SpellEffects.cpp.
References Player::AddArmorProficiency(), Player::AddWeaponProficiency(), SpellEntry::EquippedItemClass, SpellEntry::EquippedItemSubClassMask, Player::GetArmorProficiency(), Object::GetTypeId(), Player::GetWeaponProficiency(), ITEM_CLASS_ARMOR, ITEM_CLASS_WEAPON, m_caster, m_spellInfo, Player::SendProficiency(), and TYPEID_PLAYER.
EffectProspecting()
void Spell::EffectProspecting (SpellEffectIndex eff_idx)
Definition at line 12483 of file SpellEffects.cpp.
References CONFIG_BOOL_SKILL_PROSPECTING, Item::GetProto(), Player::GetSkillValuePure(), Object::GetTypeId(), itemTarget, LOOT_PROSPECTING, m_caster, Object::m_loot, ItemPrototype::RequiredSkillRank, Loot::ShowContentTo(), SKILL_JEWELCRAFTING, sWorld, TYPEID_PLAYER, and Player::UpdateGatherSkill().
EffectPull()
void Spell::EffectPull (SpellEffectIndex eff_idx)
Definition at line 6980 of file SpellEffects.cpp.
References DEBUG_LOG.
EffectPullTowards()
void Spell::EffectPullTowards (SpellEffectIndex eff_idx)
Definition at line 12112 of file SpellEffects.cpp.
References damage, DIST_CALC_NONE, SpellEntry::Effect, SpellEntry::EffectMiscValue, WorldObject::GetAngle(), SpellCastTargets::getDestination(), WorldObject::GetDistance(), WorldObject::GetDistance2d(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Movement::gravity, Unit::KnockBackWithAngle(), m_caster, m_spellInfo, m_targets, SPELL_EFFECT_PULL_TOWARDS, and unitTarget.
EffectQuestComplete()
void Spell::EffectQuestComplete (SpellEffectIndex eff_idx)
Definition at line 11946 of file SpellEffects.cpp.
References SpellEntry::CalculateSimpleValue(), SpellEntry::EffectMiscValue, Object::GetTypeId(), Unit::HasAura(), SpellEntry::Id, m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectQuestFail()
void Spell::EffectQuestFail (SpellEffectIndex eff_idx)
Definition at line 12761 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectQuestOffer()
void Spell::EffectQuestOffer (SpellEffectIndex eff_idx)
Definition at line 12966 of file SpellEffects.cpp.
References Player::CanTakeQuest(), SpellEntry::EffectMiscValue, Object::GetObjectGuid(), Player::GetPlayerMenu(), Object::GetTypeId(), m_spellInfo, PlayerMenu::SendQuestGiverQuestDetails(), sObjectMgr, TYPEID_PLAYER, and unitTarget.
EffectRedirectThreat()
void Spell::EffectRedirectThreat (SpellEffectIndex eff_idx)
Definition at line 12931 of file SpellEffects.cpp.
References damage, Unit::GetDummyAura(), Unit::getHostileRefManager(), Object::GetObjectGuid(), SpellEntry::Id, m_caster, m_spellInfo, HostileRefManager::SetThreatRedirection(), and unitTarget.
EffectRenamePet()
void Spell::EffectRenamePet (SpellEffectIndex eff_idx)
Definition at line 12798 of file SpellEffects.cpp.
References Object::GetTypeId(), HUNTER_PET, Object::RemoveByteFlag(), TYPEID_UNIT, UNIT_BYTES_2_OFFSET_PET_FLAGS, UNIT_CAN_BE_RENAMED, UNIT_FIELD_BYTES_2, and unitTarget.
EffectReputation()
void Spell::EffectReputation (SpellEffectIndex eff_idx)
Definition at line 11926 of file SpellEffects.cpp.
References Player::CalculateReputationGain(), SpellEntry::EffectMiscValue, Player::GetReputationMgr(), Object::GetTypeId(), m_currentBasePoints, m_spellInfo, ReputationMgr::ModifyReputation(), REPUTATION_SOURCE_SPELL, sFactionStore, TYPEID_PLAYER, and unitTarget.
EffectRestoreItemCharges()
void Spell::EffectRestoreItemCharges (SpellEffectIndex eff_idx)
Definition at line 12909 of file SpellEffects.cpp.
References SpellEntry::EffectItemType, ObjectMgr::GetItemPrototype(), Object::GetTypeId(), ItemPrototype::ItemLimitCategory, m_spellInfo, Item::RestoreCharges(), TYPEID_PLAYER, and unitTarget.
EffectResurrect()
void Spell::EffectResurrect (SpellEffectIndex eff_idx)
Definition at line 11833 of file SpellEffects.cpp.
References SpellLog::AddLog(), Unit::CastSpell(), corpseTarget, damage, SpellEntry::Effect, Object::GetPackGUID(), Object::GetTypeId(), SpellEntry::Id, Unit::IsAlive(), Object::IsInWorld(), m_caster, m_CastItem, m_spellInfo, m_spellLog, Player::QueueOrAddResurrectRequest(), roll_chance_i(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and unitTarget.
EffectSanctuary()
void Spell::EffectSanctuary (SpellEffectIndex eff_idx)
Definition at line 11196 of file SpellEffects.cpp.
References HostileRefManager::addThreatPercent(), Unit::AttackStop(), Unit::CombatStop(), CONFIG_BOOL_INSTANCE_STRICT_COMBAT_LOCKDOWN, Unit::getHostileRefManager(), WorldObject::GetInstanceData(), Unit::InterruptSpellsCastedOnMe(), InstanceData::IsEncounterInProgress(), SpellEntry::IsFitToFamily(), m_spellInfo, SPELL_AURA_MOD_ROOT, SPELLFAMILY_ROGUE, sWorld, and unitTarget.
EffectSchoolDMG()
void Spell::EffectSchoolDMG (SpellEffectIndex eff_idx)
Definition at line 280 of file SpellEffects.cpp.
References AURA_STATE_CONFLAGRATE, BASE_ATTACK, CalculateSpellEffectDamage(), CalculateSpellEffectValue(), WorldObject::CalculateSpellEffectValue(), Unit::CastSpell(), SpellEntry::Category, damage, DIST_CALC_COMBAT_REACH, SpellEntry::DmgMultiplier, EFFECT_INDEX_1, EFFECT_INDEX_2, FORM_SHADOW, Unit::GetAttackTime(), Unit::GetAura(), Unit::GetAurasByType(), Unit::GetBaseWeaponDamage(), Unit::GetComboPoints(), WorldObject::GetDistance(), Unit::GetDummyAura(), Unit::GetFaction(), Object::GetFloatValue(), Unit::GetHealth(), Aura::GetId(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Aura::GetModifier(), Object::GetObjectGuid(), WorldObject::GetPosition(), Unit::GetPower(), Unit::GetShapeshiftForm(), Unit::GetShieldBlockValue(), GetSpellSchoolMask(), Aura::GetStackAmount(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), SpellCastTargets::getUnitTargetGuid(), Unit::HasAura(), Unit::HasAuraState(), SpellEntry::Id, IN_MILLISECONDS, irand(), Unit::IsAlive(), Modifier::m_amount, m_caster, m_damagePerEffect, m_spellInfo, m_targets, m_UniqueTargetInfo, MAXDAMAGE, MINDAMAGE, POWER_ENERGY, POWER_MANA, RANGED_ATTACK, Unit::RemoveAuraHolderFromStack(), Unit::RemoveAurasByCasterSpell(), roll_chance_i(), Unit::SetPower(), sLog, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_DURATION_OF_EFFECTS_BY_DISPEL, SPELL_AURA_PERIODIC_DAMAGE, Unit::SpellBaseDamageBonusDone(), SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellEntry::SpellVisual, SpellEntry::TargetAuraState, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, UNIT_FIELD_MAXDAMAGE, UNIT_FIELD_MINDAMAGE, and unitTarget.
EffectScriptEffect()
void Spell::EffectScriptEffect (SpellEffectIndex eff_idx)
Definition at line 8121 of file SpellEffects.cpp.
References Unit::AddThreat(), Unit::AI(), Creature::AI(), ATTACKING_TARGET_RANDOM, UnitAI::AttackStart(), SpellEntry::CalculateSimpleValue(), ScriptMgr::CanSpellEffectStartDBScript(), Unit::CastCustomSpell(), Unit::CastSpell(), Creature::ChooseDisplayId(), Unit::CombatStop(), damage, DEBUG_FILTER_LOG, DISPEL_CURSE, DISPEL_DISEASE, DISPEL_MAGIC, DISPEL_POISON, DIST_CALC_BOUNDING_RADIUS, DoCreateItem(), UnitAI::DoResetThreat(), EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, EMOTE_ONESHOT_CHEER, EMOTE_STATE_DANCE, EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, Unit::FindGuardianWithEntry(), Creature::ForcedDespawn(), frand(), gameObjTarget, GENDER_MALE, GetAffectiveCasterObject(), WorldObject::GetAreaId(), Unit::getAttackerForHelper(), SpellAuraHolder::GetAuraByEffectIndex(), Aura::GetAuraMaxTicks(), Unit::GetAurasByType(), Unit::GetBeneficiaryPlayer(), SpellAuraHolder::GetCasterGuid(), GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), ObjectMgr::GetCreatureTemplate(), Unit::GetDisplayId(), WorldObject::GetDistance(), Unit::GetDummyAura(), Object::GetEntry(), GetExplicitDiscoverySpell(), Unit::GetFaction(), Unit::getGender(), Unit::GetHealth(), Unit::GetHealthPercent(), WorldObject::GetMap(), Unit::GetMaster(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Aura::GetModifier(), Unit::GetMotionMaster(), WorldObject::GetNearPoint(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetPower(), Unit::GetPowerType(), Unit::getRace(), WorldObject::GetRandomPoint(), Map::GetReachableRandomPosition(), Unit::GetSpawner(), WorldObject::GetSpawnerGuid(), Unit::GetSpellAuraHolder(), Unit::GetSpellAuraHolderMap(), SpellAuraHolder::GetSpellProto(), GetSpellStore(), SpellTargetMgr::GetSpellTargetingData(), ThreatManager::getThreatList(), Unit::getThreatManager(), Object::GetTypeId(), Object::GetUInt32Value(), Map::GetUnit(), SpellCastTargets::getUnitTarget(), GetUsableHealthStoneItemType(), Unit::GetVictim(), GO_READY, Unit::HandleEmote(), Unit::HandleEmoteCommand(), Unit::HasAura(), Object::HasFlag(), Unit::hasUnitState(), SpellEntry::Id, IMMUNE_TO_INCAPACITATE_MASK, IMMUNE_TO_ROOT_AND_SNARE_MASK, IN_MILLISECONDS, INTERACTION_DISTANCE, Unit::InterruptNonMeleeSpells(), INVENTORY_SLOT_BAG_0, Unit::IsAlive(), WorldObject::IsControlledByPlayer(), ClassFamilyMask::IsFitToFamilyMask(), WorldObject::IsInMap(), Unit::IsInWater(), ObjectGuid::IsPlayer(), Map::IsRegularDifficulty(), Creature::IsTemporarySummon(), itemTarget, LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), Modifier::m_amount, m_caster, m_originalCaster, m_originalCasterGUID, M_PI_F, m_spellInfo, m_targets, m_trueCaster, MINUTE, ThreatManager::modifyThreatPercent(), MotionMaster::MovementExpired(), MotionMaster::MovePoint(), CreatureInfo::NpcFlags, PET_SAVE_AS_DELETED, PLAY_TARGET, WorldObject::PlayDirectSound(), WorldObject::PlayMusic(), POWER_ENERGY, POWER_FOCUS, POWER_HAPPINESS, POWER_HEALTH, POWER_MANA, POWER_RAGE, POWER_RUNE, POWER_RUNIC_POWER, QUEST_STATUS_INCOMPLETE, RACE_BLOODELF, RACE_DRAENEI, RACE_DWARF, RACE_GNOME, RACE_HUMAN, RACE_NIGHTELF, RACE_ORC, RACE_TAUREN, RACE_TROLL, RACE_UNDEAD, GameObject::Refresh(), SpellAuraHolder::RefreshHolder(), Unit::RemoveAuraHolderFromStack(), Unit::RemoveAurasAtMechanicImmunity(), Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasWithDispelType(), Object::RemoveFlag(), Unit::RemoveSpellsCausingAura(), roll_chance_i(), SCRIPT_TYPE_SPELL, Map::ScriptsStart(), SELECT_FLAG_PLAYER, Unit::SelectAttackingTarget(), SelectMountByAreaAndSkill(), Unit::SetDisplayId(), Object::SetFlag(), Unit::SetHealth(), Unit::SetHealthPercent(), GameObject::SetLootState(), GameObject::SetRespawnTime(), Object::SetUInt32Value(), sObjectMgr, SPELL_AURA_DUMMY, SPELL_AURA_MIRROR_IMAGE, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STALKED, SPELL_AURA_MOD_STUN, SPELL_AURA_MOUNTED, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_POTION, SPELLFAMILY_PRIEST, SPELLFAMILY_WARLOCK, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, sScriptDevAIMgr, sSpellTemplate, SpellEntry::StackAmount, Unit::Suicide(), WorldObject::SummonCreature(), TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_LOCK, TARGET_TYPE_UNIT, TARGET_TYPE_UNIT_DEST, TEMPSPAWN_TIMED_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_INNKEEPER, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, UNIT_STAT_ROAMING, UNIT_STAT_ROAMING_MOVE, unitTarget, TemporarySpawn::UnSummon(), urand(), VIRTUAL_ITEM_SLOT_0, VIRTUAL_ITEM_SLOT_1, Cell::VisitAllObjects(), and Cell::VisitGridObjects().
EffectSelfResurrect()
void Spell::EffectSelfResurrect (SpellEffectIndex eff_idx)
Definition at line 11974 of file SpellEffects.cpp.
References damage, SpellEntry::EffectMiscValue, Unit::GetMaxHealth(), Unit::GetMaxPower(), Object::GetTypeId(), m_caster, m_spellInfo, POWER_ENERGY, POWER_MANA, POWER_RAGE, Player::ResurrectPlayer(), Unit::SetHealth(), Unit::SetPower(), Player::SpawnCorpseBones(), and TYPEID_PLAYER.
EffectSendEvent()
void Spell::EffectSendEvent (SpellEffectIndex eff_idx)
Definition at line 5145 of file SpellEffects.cpp.
References DEBUG_FILTER_LOG, SpellEntry::EffectMiscValue, WorldObject::GetMap(), SpellEntry::Id, LOG_FILTER_SPELL_CAST, m_eventTarget, m_spellInfo, m_trueCaster, and StartEvents_Event().
EffectSendTaxi()
void Spell::EffectSendTaxi (SpellEffectIndex eff_idx)
Definition at line 12104 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetTypeId(), SpellEntry::Id, m_spellInfo, TYPEID_PLAYER, and unitTarget.
EffectSkill()
void Spell::EffectSkill (SpellEffectIndex eff_idx)
Definition at line 12526 of file SpellEffects.cpp.
References DEBUG_LOG.
EffectSkinning()
void Spell::EffectSkinning (SpellEffectIndex eff_idx)
Definition at line 12007 of file SpellEffects.cpp.
References Creature::GetCreatureInfo(), Unit::GetLevel(), Loot::GetLootType(), CreatureInfo::GetRequiredLootSkill(), Object::GetTypeId(), Creature::IsElite(), LOOT_SKINNING, m_caster, Object::m_loot, Object::RemoveFlag(), Loot::ShowContentTo(), TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, and unitTarget.
EffectSkinPlayerCorpse()
void Spell::EffectSkinPlayerCorpse (SpellEffectIndex eff_idx)
Definition at line 12567 of file SpellEffects.cpp.
References CORPSE_DYNFLAG_LOOTABLE, CORPSE_FIELD_DYNAMIC_FLAGS, corpseTarget, DEBUG_LOG, Loot::GetLootType(), Corpse::GetOwnerGuid(), Object::IsPlayer(), LOOT_INSIGNIA, Corpse::lootRecipient, m_caster, Object::m_loot, Object::SetFlag(), Loot::ShowContentTo(), sObjectAccessor, and unitTarget.
EffectSpawn()
void Spell::EffectSpawn (SpellEffectIndex eff_idx)
Definition at line 7167 of file SpellEffects.cpp.
References m_caster, Object::RemoveFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_SPAWNING.
EffectSpecCount()
void Spell::EffectSpecCount (SpellEffectIndex eff_idx)
Definition at line 12837 of file SpellEffects.cpp.
References damage, Object::GetTypeId(), TYPEID_PLAYER, and unitTarget.
EffectSpiritHeal()
void Spell::EffectSpiritHeal (SpellEffectIndex eff_idx)
Definition at line 12531 of file SpellEffects.cpp.
References Unit::CastSpell(), CLASS_HUNTER, CLASS_WARLOCK, WorldObject::GetAreaId(), Pet::GetPetSpawnPosition(), Object::GetTypeId(), Unit::HasAura(), SpellEntry::Id, Unit::IsAlive(), Object::IsInWorld(), Pet::LoadPetFromDB(), m_spellInfo, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and unitTarget.
EffectStealBeneficialBuff()
void Spell::EffectStealBeneficialBuff (SpellEffectIndex eff_idx)
Definition at line 12612 of file SpellEffects.cpp.
References DEBUG_LOG, SpellEntry::Dispel, SpellEntry::EffectMiscValue, GetDispellMask(), Object::GetObjectGuid(), Object::GetPackGUID(), Unit::GetSpellAuraHolderMap(), SpellAuraHolder::GetSpellProto(), SpellAuraHolder::GetStackAmount(), SpellEntry::HasAttribute(), SpellEntry::Id, SpellAuraHolder::IsPassive(), SpellAuraHolder::IsPositive(), m_caster, m_spellInfo, ProcessDispelList(), Unit::RemoveAurasDueToSpellBySteal(), WorldObject::SendMessageToSet(), SMSG_DISPEL_FAILED, SMSG_SPELLSTEALLOG, SPELL_ATTR_EX4_CANNOT_BE_STOLEN, and unitTarget.
EffectStuck()
void Spell::EffectStuck (SpellEffectIndex eff_idx)
Definition at line 11315 of file SpellEffects.cpp.
References Unit::CastSpell(), CONFIG_BOOL_CAST_UNSTUCK, DEBUG_LOG, DEFAULT_WORLD_OBJECT_SIZE, DETAIL_LOG, Object::GetGUIDLow(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), WorldObject::GetNearPoint(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Object::GetTypeId(), Object::HasFlag(), Player::HasItemCount(), Map::IsDungeon(), WorldObject::IsSpellReady(), Unit::IsTaxiFlying(), m_caster, Unit::NearTeleportTo(), PLAYER_FLAGS, PLAYER_FLAGS_GHOST, Player::RepopAtGraveyard(), sObjectMgr, sWorld, AreaTrigger::target_X, AreaTrigger::target_Y, AreaTrigger::target_Z, TRIGGERED_INSTANT_CAST, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
EffectSummonAllTotems()
void Spell::EffectSummonAllTotems (SpellEffectIndex eff_idx)
Definition at line 12185 of file SpellEffects.cpp.
References ACTION_BUTTON_SHAMAN_TOTEMS_BAR, ACTION_BUTTON_SPELL, Unit::CastSpell(), SpellEntry::EffectMiscValue, SpellEntry::EffectMiscValueB, Object::GetTypeId(), m_caster, m_spellInfo, TRIGGERED_IGNORE_GCD, TRIGGERED_INSTANT_CAST, TYPEID_PLAYER, and unitTarget.
EffectSummonChangeItem()
void Spell::EffectSummonChangeItem (SpellEffectIndex eff_idx)
Definition at line 5858 of file SpellEffects.cpp.
References ClearCastItem(), Player::ConvertItem(), SpellEntry::EffectItemType, Player::GetItemCount(), Object::GetObjectGuid(), Item::GetOwnerGuid(), Object::GetTypeId(), Player::ItemAddedQuestCheck(), m_caster, m_CastItem, m_spellInfo, Player::SendNewItem(), Item::SetUsedInSpell(), and TYPEID_PLAYER.
EffectSummonDeadPet()
void Spell::EffectSummonDeadPet (SpellEffectIndex eff_idx)
Definition at line 12147 of file SpellEffects.cpp.
References ALIVE, Unit::clearUnitState(), damage, SpellCastTargets::getDestination(), WorldObject::GetDistance(), Unit::GetMaxHealth(), WorldObject::GetOrientation(), Unit::GetPet(), Object::GetTypeId(), Unit::IsAlive(), Pet::LoadPetFromDB(), m_caster, SpellCastTargets::m_destPos, m_targets, Unit::NearTeleportTo(), Position::o, PET_SAVE_AS_CURRENT, Object::RemoveFlag(), Pet::ResetCorpseRespawn(), Pet::SavePetToDB(), Pet::SetDeathState(), Unit::SetHealth(), Object::SetUInt32Value(), TYPEID_PLAYER, UNIT_DYNAMIC_FLAGS, UNIT_DYNFLAG_NONE, UNIT_FIELD_FLAGS, UNIT_FLAG_SKINNABLE, UNIT_STAT_ALL_STATE, Position::x, Position::y, and Position::z.
EffectSummonObject()
void Spell::EffectSummonObject (SpellEffectIndex eff_idx)
Definition at line 11763 of file SpellEffects.cpp.
References Map::Add(), Unit::AddGameObject(), SpellLog::AddLog(), Unit::AI(), GameObject::AIM_Initialize(), ObjectGuid::Clear(), GameObject::Create(), DEFAULT_WORLD_OBJECT_SIZE, SpellEntry::Effect, SpellEntry::EffectMiscValue, GAMEOBJECT_LEVEL, Map::GenerateLocalLowGuid(), WorldObject::GetClosePoint(), SpellCastTargets::getDestination(), Map::GetGameObject(), Unit::GetLevel(), GameObject::GetLinkedTrap(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), GO_JUST_DEACTIVATED, HIGHGUID_GAMEOBJECT, SpellEntry::Id, IN_MILLISECONDS, UnitAI::JustSummoned(), m_caster, m_duration, Unit::m_ObjectSlotGuid, m_originalCaster, m_spellInfo, m_spellLog, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, OnSummon(), Unit::RemoveGameObject(), GameObject::SetRespawnTime(), GameObject::SetSpawnerGuid(), GameObject::SetSpellId(), Object::SetUInt32Value(), SPELL_EFFECT_SUMMON_OBJECT_SLOT1, SPELL_EFFECT_SUMMON_OBJECT_SLOT2, SPELL_EFFECT_SUMMON_OBJECT_SLOT3, SPELL_EFFECT_SUMMON_OBJECT_SLOT4, and TARGET_FLAG_DEST_LOCATION.
EffectSummonObjectWild()
void Spell::EffectSummonObjectWild (SpellEffectIndex eff_idx)
Definition at line 8066 of file SpellEffects.cpp.
References Map::Add(), SpellLog::AddLog(), Unit::AddWildGameObject(), Unit::AI(), GameObject::AIM_Initialize(), GameObject::Create(), DEFAULT_WORLD_OBJECT_SIZE, SpellEntry::EffectMiscValue, Map::GenerateLocalLowGuid(), WorldObject::GetClosePoint(), SpellCastTargets::getDestination(), GameObject::GetLinkedTrap(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), HIGHGUID_GAMEOBJECT, SpellEntry::Id, IN_MILLISECONDS, Object::IsGameObject(), UnitAI::JustSummoned(), m_caster, m_duration, m_eventTarget, m_originalCaster, m_spellInfo, m_spellLog, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, OnSummon(), GameObject::SetRespawnTime(), GameObject::SetSpawnerGuid(), GameObject::SetSpellId(), SPELL_EFFECT_SUMMON_OBJECT_WILD, and TARGET_FLAG_DEST_LOCATION.
EffectSummonPet()
void Spell::EffectSummonPet (SpellEffectIndex eff_idx)
Definition at line 7501 of file SpellEffects.cpp.
References Map::Add(), Unit::AddGuardian(), SpellLog::AddLog(), Unit::AI(), Pet::AI(), Creature::AIM_Initialize(), Pet::CastOwnerTalentAuras(), Pet::CastPetAuras(), CLASS_HUNTER, Pet::Create(), DEBUG_LOG, SpellEntry::EffectMiscValue, SpellEntry::EffectMultipleValue, Map::GenerateLocalLowGuid(), Unit::GetCharmInfo(), Unit::getClass(), ObjectMgr::GetCreatureTemplate(), Unit::GetFaction(), Object::GetGUIDLow(), Unit::GetLevel(), WorldObject::GetMap(), Unit::GetMaxHealth(), Unit::GetMaxPower(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), Unit::GetPet(), Pet::getPetType(), WorldObject::GetPhaseMask(), WorldObject::GetTransport(), Object::GetTypeId(), GUARDIAN_PET, Object::HasFlag(), HIGHGUID_PET, SpellEntry::Id, Pet::InitLevelupSpellsForLevel(), Pet::InitPetCreateSpells(), Pet::InitStatsForLevel(), Pet::InitTalentForLevel(), Unit::IsImmuneToNPC(), Unit::IsImmuneToPlayer(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), UnitAI::JustSummoned(), Pet::LearnPetPassives(), Pet::LoadPetFromDB(), m_caster, SpellCastTargets::m_destPos, m_ignoreOwnerLevel, m_originalCaster, m_spellInfo, m_spellLog, m_targets, CreatureInfo::MaxLevel, CreatureInfo::MinLevel, CreatureInfo::NpcFlags, Position::o, OnSummon(), PET_SAVE_AS_CURRENT, PET_SAVE_NOT_IN_SLOT, Player::PetSpellInitialize(), POWER_MANA, REACT_DEFENSIVE, Pet::SavePetToDB(), Object::SetByteValue(), Unit::SetCanModifyStats(), Unit::setFaction(), Object::SetFlag(), Unit::SetHealth(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Pet::SetLoading(), WorldObject::SetName(), Pet::SetOwnerGuid(), Unit::SetPet(), CharmInfo::SetPetNumber(), Pet::setPetType(), Unit::SetPower(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), UnitAI::SetReactState(), Creature::SetRespawnCoord(), Object::SetUInt32Value(), sLog, sObjectMgr, SPELL_EFFECT_SUMMON_PET, SUMMON_PET, TYPEID_PLAYER, UNIT_BYTE2_FLAG_AURAS, UNIT_CREATED_BY_SPELL, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FIELD_PET_NAME_TIMESTAMP, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_NPC_FLAG_NONE, UNIT_NPC_FLAGS, CreatureInfo::UnitFlags, Pet::Unsummon(), Pet::UpdateAllStats(), urand(), Position::x, Position::y, and Position::z.
EffectSummonPlayer()
void Spell::EffectSummonPlayer (SpellEffectIndex eff_idx)
Definition at line 11361 of file SpellEffects.cpp.
References Unit::GetDummyAura(), WorldObject::GetMapId(), Object::GetObjectGuid(), WorldObject::GetPosition(), WorldObject::GetZoneId(), IN_MILLISECONDS, Object::IsPlayer(), m_caster, MAX_PLAYER_SUMMON_DELAY, SMSG_SUMMON_REQUEST, and unitTarget.
EffectSummonRafFriend()
void Spell::EffectSummonRafFriend (SpellEffectIndex eff_idx)
Definition at line 13013 of file SpellEffects.cpp.
References Unit::CastSpell(), SpellEntry::EffectTriggerSpell, WorldSession::GetRecruitingFriendId(), Player::GetSession(), SpellEntry::Id, Object::IsPlayer(), SQLStorage::LookupEntry(), m_caster, m_spellInfo, sLog, sSpellTemplate, sWorld, TRIGGERED_INSTANT_CAST, and TRIGGERED_OLD_TRIGGERED.
EffectSummonType()
void Spell::EffectSummonType (SpellEffectIndex eff_idx)
Definition at line 5925 of file SpellEffects.cpp.
References Map::Add(), SpellLog::AddLog(), Unit::AddThreat(), Unit::AI(), Creature::AI(), Creature::AIM_Initialize(), UnitAI::AttackClosestEnemy(), UnitAI::AttackStart(), Unit::CanAssist(), Unit::CanAttack(), Unit::CanEnterCombat(), Unit::CanHaveThreatList(), CREATURE_TYPE_TOTEM, damage, DEFAULT_MAX_CREATURE_LEVEL, DoSummonCritter(), DoSummonGuardian(), DoSummonPossessed(), DoSummonTotem(), DoSummonVehicle(), DoSummonWild(), SpellEntry::Effect, SpellEntry::EffectMiscValue, SpellEntry::EffectMiscValueB, SpellEntry::EffectMultipleValue, SpellEntry::EffectRadiusIndex, SummonPropertiesEntry::FactionId, SummonPropertiesEntry::Flags, frand(), GetCastingObject(), WorldObject::GetClosePoint(), ObjectMgr::GetCreatureTemplate(), SpellCastTargets::getDestination(), WorldObject::GetFaction(), Object::GetGuidStr(), Map::GetHitPosition(), Unit::getHostileRefManager(), WorldObject::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), Unit::GetOwner(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), WorldObject::GetPosition(), Item::GetProto(), WorldObject::GetRandomPoint(), GetSpellRadius(), ThreatManager::getThreatList(), Unit::getThreatManager(), Object::GetTypeId(), SummonPropertiesEntry::Group, SpellEntry::Id, ItemPrototype::InventoryType, INVTYPE_TRINKET, WorldObject::IsControlledByPlayer(), Object::IsCreature(), Creature::IsPet(), Object::IsPlayer(), Creature::IsTemporarySummon(), ThreatManager::isThreatListEmpty(), UnitAI::JustSummoned(), m_caster, m_CastItem, m_ignoreOwnerLevel, m_originalCaster, M_PI_F, m_spellInfo, m_spellLog, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, MANGOS_ASSERT, OnSummon(), ItemPrototype::RequiredSkill, Unit::setFaction(), Object::SetFlag(), Creature::SetOnlyVisibleTo(), SKILL_ENGINEERING, sLog, SummonPropertiesEntry::Slot, SPELL_EFFECT_SUMMON, sSpellRadiusStore, sSummonPropertiesStore, SUMMON_PROP_FLAG_ATTACK_SUMMONER, SUMMON_PROP_FLAG_CANNOT_DISMISS_PET, SUMMON_PROP_FLAG_HELP_WHEN_SUMMONED_IN_COMBAT, SUMMON_PROP_FLAG_JOIN_SUMMONERS_SPAWN_GROUP, SUMMON_PROP_FLAG_ONLY_VISIBLE_TO_SUMMONER, SUMMON_PROP_FLAG_USE_CREATURE_LEVEL, SUMMON_PROP_FLAG_USE_SUMMONER_FACTION, SUMMON_PROP_GROUP_CONTROLLABLE, SUMMON_PROP_GROUP_FRIENDLY, SUMMON_PROP_GROUP_PETS, SUMMON_PROP_GROUP_UNCONTROLLABLE_VEHICLE, SUMMON_PROP_GROUP_VEHICLE, SUMMON_PROP_GROUP_WILD, SUMMON_PROP_SLOT_CRITTER, SUMMON_PROP_SLOT_QUEST_PLAYERS_ONLY, TARGET_FLAG_DEST_LOCATION, SummonPropertiesEntry::Title, TYPEID_GAMEOBJECT, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNITNAME_SUMMON_TITLE_BUTLER, UNITNAME_SUMMON_TITLE_COMPANION, UNITNAME_SUMMON_TITLE_CONSTRUCT, UNITNAME_SUMMON_TITLE_GUARDIAN, UNITNAME_SUMMON_TITLE_LIGHTWELL, UNITNAME_SUMMON_TITLE_MINION, UNITNAME_SUMMON_TITLE_MOUNT, UNITNAME_SUMMON_TITLE_NONE, UNITNAME_SUMMON_TITLE_OPPONENT, UNITNAME_SUMMON_TITLE_PET, UNITNAME_SUMMON_TITLE_RUNEBLADE, UNITNAME_SUMMON_TITLE_TOTEM, UNITNAME_SUMMON_TITLE_VEHICLE, WorldObject::UpdateAllowedPositionZ(), and urand().
EffectTameCreature()
void Spell::EffectTameCreature (SpellEffectIndex eff_idx)
Definition at line 7412 of file SpellEffects.cpp.
References Map::Add(), Pet::AI(), Creature::AIM_Initialize(), Pet::CastOwnerTalentAuras(), Pet::CastPetAuras(), Pet::CreateBaseAtCreature(), finish(), Creature::ForcedDespawn(), GetAffectiveCaster(), Unit::GetCharmInfo(), Unit::GetFaction(), Unit::GetHealthPercent(), Unit::GetLevel(), WorldObject::GetMap(), Object::GetObjectGuid(), Object::HasFlag(), HUNTER_PET, SpellEntry::Id, Pet::InitLevelupSpellsForLevel(), Pet::InitPetCreateSpells(), Pet::InitStatsForLevel(), Pet::InitTalentForLevel(), Unit::IsImmuneToNPC(), Unit::IsImmuneToPlayer(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsPvPSanctuary(), Pet::LearnPetPassives(), m_spellInfo, PET_SAVE_AS_CURRENT, Player::PetSpellInitialize(), REACT_DEFENSIVE, Pet::SavePetToDB(), Unit::SetCanModifyStats(), Unit::setFaction(), Object::SetFlag(), Unit::SetHealthPercent(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Pet::SetLoading(), Pet::SetOwnerGuid(), Unit::SetPet(), CharmInfo::SetPetNumber(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), UnitAI::SetReactState(), Object::SetUInt32Value(), sObjectMgr, UNIT_CREATED_BY_SPELL, UNIT_FIELD_FLAGS, UNIT_FIELD_LEVEL, UNIT_FLAG_PLAYER_CONTROLLED, unitTarget, and Pet::UpdateAllStats().
EffectTaunt()
void Spell::EffectTaunt (SpellEffectIndex eff_idx)
Definition at line 7683 of file SpellEffects.cpp.
References ThreatManager::addThreatDirectly(), Unit::AI(), Unit::CanHaveThreatList(), SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellTargetInfo::enumerator, ThreatManager::GetHighestThreat(), ThreatManager::getThreat(), Unit::getThreatManager(), Object::GetTypeId(), Unit::GetVictim(), Unit::hasUnitState(), m_caster, m_spellInfo, REACT_PASSIVE, SendCastResult(), ThreatManager::setCurrentVictimByTarget(), SPELL_FAILED_DONT_REPORT, SpellTargetInfoTable, TARGET_ENUMERATOR_SINGLE, TYPEID_PLAYER, UNIT_STAT_CAN_NOT_REACT_OR_LOST_CONTROL, and unitTarget.
EffectTeachTaxiNode()
void Spell::EffectTeachTaxiNode (SpellEffectIndex eff_idx)
Definition at line 12943 of file SpellEffects.cpp.
References SpellEntry::EffectMiscValue, Object::GetObjectGuid(), Object::GetTypeId(), WorldPacket::Initialize(), m_caster, m_spellInfo, Player::m_taxi, Player::SendDirectMessage(), PlayerTaxi::SetTaximaskNode(), SMSG_NEW_TAXI_PATH, SMSG_TAXINODE_STATUS, sTaxiNodesStore, TYPEID_PLAYER, and unitTarget.
EffectTeleportGraveyard()
void Spell::EffectTeleportGraveyard (SpellEffectIndex eff_idx)
Definition at line 13105 of file SpellEffects.cpp.
References WorldObject::GetMap(), Map::IsBattleGround(), Object::IsPlayer(), Player::RepopAtGraveyard(), and unitTarget.
EffectTeleportUnits()
void Spell::EffectTeleportUnits (SpellEffectIndex eff_idx)
Definition at line 4892 of file SpellEffects.cpp.
References ALLIANCE, Unit::CastSpell(), Player::CheckAndRevivePlayerOnDungeonEnter(), SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, Position::GetAngle(), SpellCastTargets::getDestination(), Unit::GetLevel(), WorldObject::GetMapId(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetTypeId(), SpellEntry::Id, Unit::IsAlive(), MapEntry::IsDungeon(), Unit::IsMoving(), Object::IsPlayer(), Unit::IsTaxiFlying(), m_caster, SpellCastTargets::m_destPos, SpellCastTargets::m_mapId, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, Unit::NearTeleportTo(), Position::o, roll_chance_i(), sLog, sMapStore, TARGET_FLAG_DEST_LOCATION, TARGET_LOCATION_DATABASE, TELE_TO_SPELL, Player::TeleportTo(), TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, unitTarget, urand(), Position::x, Position::y, and Position::z.
EffectTeleUnitsFaceCaster()
void Spell::EffectTeleUnitsFaceCaster (SpellEffectIndex eff_idx)
Definition at line 7104 of file SpellEffects.cpp.
References SpellCastTargets::getDestination(), WorldObject::GetOrientation(), Unit::IsTaxiFlying(), m_caster, SpellCastTargets::m_targetMask, m_targets, Unit::NearTeleportTo(), TARGET_FLAG_DEST_LOCATION, and unitTarget.
EffectThreat()
void Spell::EffectThreat (SpellEffectIndex eff_idx)
Definition at line 8006 of file SpellEffects.cpp.
References Unit::AddThreat(), Unit::AI(), UnitAI::AttackStart(), Unit::CanHaveThreatList(), damage, Unit::EngageInCombatWith(), GetSpellSchoolMask(), Unit::IsAlive(), Unit::IsInCombat(), m_caster, m_spellInfo, and unitTarget.
EffectTitanGrip()
void Spell::EffectTitanGrip (SpellEffectIndex eff_idx)
Definition at line 12784 of file SpellEffects.cpp.
References Unit::CastSpell(), SpellEntry::EffectMiscValue, Object::GetTypeId(), Unit::HasAura(), Player::HasTwoHandWeaponInOneHand(), SpellEntry::Id, m_caster, m_spellInfo, Player::SetCanTitanGrip(), sLog, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and unitTarget.
EffectTradeSkill()
void Spell::EffectTradeSkill (SpellEffectIndex eff_idx)
Definition at line 7172 of file SpellEffects.cpp.
References Object::GetTypeId(), TYPEID_PLAYER, and unitTarget.
EffectTransmitted()
void Spell::EffectTransmitted (SpellEffectIndex eff_idx)
Definition at line 12313 of file SpellEffects.cpp.
References Map::Add(), Unit::AddGameObject(), SpellLog::AddLog(), GameObject::AddUniqueUse(), Unit::AI(), GameObject::AIM_Initialize(), GameObjectInfo::button, GameObject::Create(), DEBUG_LOG, DEFAULT_WORLD_OBJECT_SIZE, SpellEntry::EffectMiscValue, SpellEntry::EffectRadiusIndex, FISHING_BOBBER_READY_TIME, GAMEOBJECT_LEVEL, GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_FISHINGHOLE, GAMEOBJECT_TYPE_FISHINGNODE, GAMEOBJECT_TYPE_SPELLCASTER, GAMEOBJECT_TYPE_SUMMONING_RITUAL, Map::GenerateLocalLowGuid(), WorldObject::GetClosePoint(), SpellCastTargets::getDestination(), Unit::GetDisplayId(), ObjectMgr::GetGameObjectInfo(), Unit::GetLevel(), GameObject::GetLinkedTrap(), WorldObject::GetMap(), GetModelMidpoint(), WorldObject::GetNearPoint2d(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), Object::GetObjectScale(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPhaseMask(), WorldObject::GetPosition(), WorldObject::GetPositionZ(), Player::GetSelectionGuid(), GetSpellMaxRange(), GetSpellMinRange(), GetSpellRadius(), WorldObject::GetTerrain(), Object::GetTypeId(), GO_STATE_ACTIVE, GO_STATE_READY, Unit::HasAura(), HIGHGUID_GAMEOBJECT, SpellEntry::Id, IN_MILLISECONDS, TerrainInfo::IsAboveWater(), WorldObject::IsWithinLOS(), UnitAI::JustSummoned(), m_caster, m_duration, m_originalCaster, m_spellInfo, m_spellLog, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, OnSummon(), rand_norm_f(), SpellEntry::rangeIndex, SendCastResult(), SendChannelUpdate(), GameObject::SetActionTarget(), Unit::SetChannelObject(), GameObject::SetGoState(), GameObject::SetOwnerGuid(), GameObject::SetRespawnTime(), GameObject::SetSpawnerGuid(), GameObject::SetSpellId(), Object::SetUInt32Value(), sLog, SpellEntry::speed, SPELL_EFFECT_TRANS_DOOR, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_NOT_FISHABLE, SPELL_FAILED_ONLY_ABOVEWATER, SPELL_FAILED_SUCCESS, sSpellRadiusStore, sSpellRangeStore, TARGET_FLAG_DEST_LOCATION, GameObjectInfo::type, TYPEID_PLAYER, and urand().
EffectTriggerMissileSpell()
void Spell::EffectTriggerMissileSpell (SpellEffectIndex eff_idx)
Definition at line 4770 of file SpellEffects.cpp.
References Unit::CastCustomSpell(), Unit::CastSpell(), damage, DEBUG_FILTER_LOG, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, gameObjTarget, WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellEntry::Id, LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), m_caster, m_CastItem, SpellCastTargets::m_destPos, m_originalCasterGUID, m_spellInfo, m_targets, SCRIPT_TYPE_SPELL, Map::ScriptsStart(), SpellCastTargets::setDestination(), SpellCastTargets::setGOTarget(), SpellCastTargets::setUnitTarget(), sLog, SPELL_EFFECT_TRIGGER_MISSILE_SPELL_WITH_VALUE, sSpellTemplate, TARGET_FLAG_DEST_LOCATION, TARGET_LOCATION_CASTER_DEST, SpellEntry::Targets, TRIGGERED_OLD_TRIGGERED, unitTarget, Position::x, Position::y, and Position::z.
EffectTriggerRitualOfSummoning()
void Spell::EffectTriggerRitualOfSummoning (SpellEffectIndex eff_idx)
Definition at line 4543 of file SpellEffects.cpp.
References Unit::CastSpell(), SpellEntry::EffectTriggerSpell, finish(), SpellEntry::Id, SQLStorage::LookupEntry(), m_caster, m_spellInfo, sLog, sSpellTemplate, TRIGGERED_NONE, and unitTarget.
EffectTriggerSpell()
void Spell::EffectTriggerSpell (SpellEffectIndex eff_idx)
Definition at line 4645 of file SpellEffects.cpp.
References BASE_ATTACK, ScriptMgr::CanSpellEffectStartDBScript(), Unit::CastSpell(), DEBUG_FILTER_LOG, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectTriggerSpell, SpellEntry::EquippedItemClass, SpellCastTargets::getDestination(), WorldObject::GetMap(), WorldObject::GetPosition(), Object::GetTypeId(), SpellEntry::HasAttribute(), Unit::HasAura(), SpellEntry::Id, Item::IsFitToSpellRequirements(), IsSpellRequireTarget(), LOG_FILTER_SPELL_CAST, SQLStorage::LookupEntry(), m_caster, m_CastItem, m_originalCasterGUID, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, OFF_ATTACK, Unit::RemoveAurasDueToSpellByCancel(), RUNE_DEATH, RUNE_FROST, SCRIPT_TYPE_SPELL, Map::ScriptsStart(), SpellCastTargets::setDestination(), SpellCastTargets::setUnitTarget(), sLog, SPELL_ATTR_EX3_REQUIRES_MAIN_HAND_WEAPON, SPELL_ATTR_EX3_REQUIRES_OFFHAND_WEAPON, sSpellTemplate, TARGET_FLAG_DEST_LOCATION, TARGET_LOCATION_UNIT_MINION_POSITION, SpellEntry::Targets, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, unitTarget, and urand().
EffectTriggerSpellWithValue()
void Spell::EffectTriggerSpellWithValue (SpellEffectIndex eff_idx)
Definition at line 4526 of file SpellEffects.cpp.
References Unit::CastCustomSpell(), damage, SpellEntry::EffectTriggerSpell, SpellEntry::Id, SQLStorage::LookupEntry(), m_caster, m_CastItem, m_originalCasterGUID, m_spellInfo, sLog, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, and unitTarget.
EffectUnlearnSpecialization()
void Spell::EffectUnlearnSpecialization (SpellEffectIndex eff_idx)
Definition at line 5080 of file SpellEffects.cpp.
References DEBUG_LOG, SpellEntry::EffectTriggerSpell, GetCastingObject(), Object::GetGuidStr(), Object::GetTypeId(), m_spellInfo, Player::removeSpell(), TYPEID_PLAYER, and unitTarget.
EffectUnused()
void Spell::EffectUnused (SpellEffectIndex eff_idx)
Definition at line 239 of file SpellEffects.cpp.
EffectWeaponDmg()
void Spell::EffectWeaponDmg (SpellEffectIndex eff_idx)
Definition at line 7726 of file SpellEffects.cpp.
References AURA_STATE_DEADLY_POISON, BASE_ATTACK, Unit::CalculateDamage(), CalculateSpellEffectDamage(), CalculateSpellEffectValue(), Unit::CastSpell(), damagePerEffect, DISPEL_DISEASE, DISPEL_POISON, SpellEntry::DmgClass, SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_2, Unit::GetModifierValue(), Object::GetObjectGuid(), Unit::GetOverrideScript(), Unit::GetPower(), Item::GetProto(), Unit::GetSpellAuraHolderMap(), GetSpellSchoolMask(), Unit::GetTotalAttackPowerValue(), Object::GetTypeId(), Unit::HasAura(), Unit::HasAuraState(), Unit::HasAuraType(), SpellEntry::Id, Unit::IsAlive(), SpellEntry::IsFitToFamily(), ITEM_SUBCLASS_WEAPON_DAGGER, m_attackType, m_caster, m_damagePerEffect, m_spellInfo, m_UniqueTargetInfo, MAX_EFFECT_INDEX, OFF_ATTACK, POWER_RUNIC_POWER, RANGED_ATTACK, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_DAMAGE_CLASS_MAGIC, SPELL_DAMAGE_CLASS_MELEE, SPELL_DAMAGE_CLASS_NONE, SPELL_DAMAGE_CLASS_RANGED, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, SPELL_EFFECT_WEAPON_PERCENT_DAMAGE, Unit::SpellBaseDamageBonusDone(), SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_PALADIN, SPELLFAMILY_ROGUE, SPELLFAMILY_SHAMAN, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, ItemPrototype::SubClass, TOTAL_PCT, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, UNIT_MOD_DAMAGE_MAINHAND, UNIT_MOD_DAMAGE_OFFHAND, UNIT_MOD_DAMAGE_RANGED, and unitTarget.
EffectWMOChange()
void Spell::EffectWMOChange (SpellEffectIndex eff_idx)
Definition at line 12723 of file SpellEffects.cpp.
References DEBUG_LOG, SpellEntry::EffectMiscValue, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, gameObjTarget, GetAffectiveCaster(), Object::GetEntry(), GameObject::GetGoType(), SpellEntry::Id, m_caster, m_spellInfo, GameObject::SetDestructibleState(), and sLog.
EffectWMODamage()
void Spell::EffectWMODamage (SpellEffectIndex eff_idx)
Definition at line 12671 of file SpellEffects.cpp.
References damage, GameObject::DealGameObjectDamage(), DEBUG_LOG, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, gameObjTarget, GetAffectiveCaster(), Object::GetEntry(), GameObject::GetGoType(), GameObject::GetHealth(), WorldObject::GetMap(), Object::GetTypeId(), SpellEntry::Id, Map::IsBattleGround(), m_spellInfo, sLog, and TYPEID_PLAYER.
EffectWMORepair()
void Spell::EffectWMORepair (SpellEffectIndex eff_idx)
Definition at line 12702 of file SpellEffects.cpp.
References DEBUG_LOG, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, gameObjTarget, GetAffectiveCaster(), Object::GetEntry(), GameObject::GetGoType(), SpellEntry::Id, m_spellInfo, GameObject::RebuildGameObject(), and sLog.
EvaluateResultLists()
void Spell::EvaluateResultLists (std::list< std::pair< SpellAuraHolder *, uint32 > > & successList, std::list< uint32 > & failList)
Definition at line 6931 of file SpellEffects.cpp.
References SpellEntry::CalculateSimpleValue(), Unit::CastCustomSpell(), SpellEntry::Category, EFFECT_INDEX_1, SpellAuraHolder::GetCasterGuid(), SpellAuraHolder::GetId(), Object::GetObjectGuid(), Object::GetPackGUID(), SpellEntry::Id, m_caster, m_spellInfo, Unit::RemoveAuraHolderDueToSpellByDispel(), WorldObject::SendMessageToSet(), SMSG_DISPEL_FAILED, SMSG_SPELLDISPELLOG, SPELLCATEGORY_DEVOUR_MAGIC, SPELLFAMILY_WARLOCK, SpellEntry::SpellFamilyName, TRIGGERED_OLD_TRIGGERED, and unitTarget.
Referenced by EffectDispel(), and EffectDispelMechanic().
ExecuteEffects()
void Spell::ExecuteEffects (Unit * unitTarget, Item * itemTarget, GameObject * GOTarget, uint32 effectMask)
Definition at line 5377 of file Spell.cpp.
References SpellEntry::DmgMultiplier, GetAffectiveCaster(), WorldObject::GetSpellModOwner(), HandleEffect(), SpellEntry::Id, itemTarget, m_applyMultiplierMask, m_damageMultipliers, m_spellInfo, MAX_EFFECT_INDEX, SPELLMOD_EFFECT_PAST_FIRST, and unitTarget.
Referenced by DoAllEffectOnTarget(), DoSpellHitOnUnit(), and HandleImmediateEffectExecution().
FillAreaTargets()
void Spell::FillAreaTargets (UnitList & targetUnitMap, float radius, float cone, SpellNotifyPushType pushType, SpellTargets spellTargets, WorldObject * originalCaster = nullptr) protected
Fill target list by units around (x,y) points at radius distance.
Parameters
targetUnitMap Reference to target list that filled by function
x X coordinates of center point for target search
y Y coordinates of center point for target search
radius Radius around (x,y) for target search
pushType Additional rules for target area selection (in front, angle, etc)
spellTargets Additional rules for target selection base at hostile/friendly state to original spell caster
originalCaster If provided set alternative original caster, if =nullptr then used Spell::GetAffectiveObject() return
Definition at line 8697 of file Spell.cpp.
References MaNGOS::SpellNotifierCreatureAndPlayer::GetCenterX(), MaNGOS::SpellNotifierCreatureAndPlayer::GetCenterY(), WorldObject::GetMap(), m_trueCaster, and Cell::VisitAllObjects().
Referenced by CheckCast(), and SetTargetMap().
FillFromTargetFlags()
void Spell::FillFromTargetFlags (TempTargetingData & targetingData, SpellEffectIndex effIndex) protected
Definition at line 9353 of file Spell.cpp.
References Spell::TempTargetingData::data, GetCastingObject(), SpellCastTargets::getCorpseTarget(), SpellCastTargets::getCorpseTargetGuid(), SpellCastTargets::getItemTarget(), SpellCastTargets::getUnitTarget(), SpellEntry::Id, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, SpellCastTargets::setDestination(), sLog, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_ITEM, TARGET_FLAG_TRADE_ITEM, TARGET_FLAG_UNIT, TARGET_FLAG_UNIT_ALLY, TARGET_FLAG_UNIT_ENEMY, SpellEntry::Targets, Spell::TempTargetData::tempCorpseList, Spell::TempTargetData::tempItemList, and Spell::TempTargetData::tmpUnitList.
Referenced by FillTargetMap().
FillRaidOrPartyHealthPriorityTargets()
void Spell::FillRaidOrPartyHealthPriorityTargets (UnitList & targetUnitMap, Unit * member, Unit * center, float radius, uint32 count, bool raid, bool withPets, bool withCaster) protected
Definition at line 8752 of file Spell.cpp.
References FillRaidOrPartyTargets().
FillRaidOrPartyManaPriorityTargets()
void Spell::FillRaidOrPartyManaPriorityTargets (UnitList & targetUnitMap, Unit * member, Unit * center, float radius, uint32 count, bool raid, bool withPets, bool withCaster) protected
Definition at line 8747 of file Spell.cpp.
References FillRaidOrPartyTargets().
FillRaidOrPartyTargets()
void Spell::FillRaidOrPartyTargets (UnitList & targetUnitMap, Unit * member, Unit * center, float radius, bool raid, bool withPets, bool withcaster) const protected
Definition at line 8703 of file Spell.cpp.
References Unit::CanAssistSpell(), Unit::GetBeneficiary(), Unit::GetBeneficiaryPlayer(), Group::GetFirstMember(), Player::GetGroup(), Unit::GetPet(), Player::GetSubGroup(), WorldObject::IsWithinDistInMap(), m_caster, m_spellInfo, and GroupReference::next().
Referenced by FillRaidOrPartyHealthPriorityTargets(), FillRaidOrPartyManaPriorityTargets(), and SetTargetMap().
FillTargetMap()
void Spell::FillTargetMap () protected
Definition at line 591 of file Spell.cpp.
References AddCorpseTarget(), AddDestExecution(), AddGOTarget(), AddItemTarget(), SpellTargetMgr::CanEffectBeFilledWithMask(), Spell::TempTargetingData::chainTargetCount, Spell::TempTargetingData::data, SpellEffectInfo::defaultTarget, SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, FillFromTargetFlags(), FillUnitTargets(), finish(), Unit::GetAurasByType(), GetCastingObject(), SpellTargetMgr::GetSpellTargetingData(), SpellCastTargets::getUnitTargetGuid(), SpellEntry::HasAttribute(), SpellEntry::Id, Object::IsUnit(), m_affectedTargetCount, m_caster, m_chainTargetCount, m_filteringScheme, m_spellInfo, m_targetlessMask, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, m_UniqueTargetInfo, MAX_EFFECT_INDEX, OnCheckTarget(), OnDestTarget(), SendCastResult(), SpellCastTargets::setSource(), SetTargetMap(), SPELL_ATTR_EX2_FAIL_ON_ALL_TARGETS_IMMUNE, SPELL_ATTR_EX_REQUIRE_ALL_TARGETS, SPELL_AURA_MOD_MAX_AFFECTED_TARGETS, SPELL_EFFECT_NONE, SPELL_FAILED_IMMUNE, SPELL_MISS_IMMUNE, SPELL_MISS_IMMUNE2, SPELL_MISS_NONE, SpellEffectInfoTable, SpellTargetInfoTable, TARGET_ENUMERATOR_AOE, TARGET_ENUMERATOR_SINGLE, TARGET_FLAG_SOURCE_LOCATION, TARGET_NONE, TARGET_TYPE_CORPSE, TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_ITEM, TARGET_TYPE_LOCATION_DEST, TARGET_TYPE_LOCATION_TRAJ, TARGET_TYPE_LOCK, TARGET_TYPE_NONE, TARGET_TYPE_PLAYER, TARGET_TYPE_SPECIAL_DEST, TARGET_TYPE_SPECIAL_UNIT, TARGET_TYPE_UNIT, TARGET_TYPE_UNIT_DEST, SpellEntry::Targets, Spell::TempTargetData::tempCorpseList, Spell::TempTargetData::tempItemList, Spell::TempTargetData::tmpGOList, Spell::TempTargetData::tmpUnitList, and urand().
Referenced by cast().
FillUnitTargets()
bool Spell::FillUnitTargets (TempTargetingData & targetingData, SpellTargetingData & data, uint32 i) protected
Definition at line 794 of file Spell.cpp.
References AddUnitTarget(), AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, Spell::TempTargetingData::chainTargetCount, CheckTarget(), Spell::TempTargetingData::data, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, FilterTargetMap(), finish(), Unit::GetBeneficiaryPlayer(), SpellEntry::HasAttribute(), SpellEntry::Id, SpellTargetingData::ignoredTargets, Player::IsInDuelWith(), Object::IsPlayer(), Unit::IsPvP(), m_filteringScheme, m_spellInfo, m_trueCaster, Spell::TempTargetingData::magnet, Unit::RemoveAurasWithInterruptFlags(), SendCastResult(), SPELL_ATTR_EX_REQUIRE_ALL_TARGETS, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_OUT_OF_RANGE, SpellTargetInfoTable, TARGET_TYPE_PLAYER, TARGET_TYPE_UNIT, SpellTargetingData::targetMask, Spell::TempTargetData::tmpUnitList, SpellTargetInfo::type, and Player::UpdatePvP().
Referenced by FillTargetMap().
FilterTargetMap()
void Spell::FilterTargetMap (UnitList & filterUnitList, SpellTargetFilterScheme scheme, uint32 chainTargetCount) protected
Definition at line 9162 of file Spell.cpp.
References Unit::CanReachWithMeleeAttack(), DIST_CALC_NONE, WorldObject::GetDistance(), Unit::GetHealth(), SpellCastTargets::getUnitTarget(), Unit::IsInGroup(), WorldObject::IsWithinLOSInMap(), m_affectedTargetCount, m_caster, m_jumpRadius, m_targets, m_trueCaster, POWER_MANA, SCHEME_CLOSEST, SCHEME_CLOSEST_CHAIN, SCHEME_FURTHEST, SCHEME_HIGHEST_HP, SCHEME_LOWEST_HP_CHAIN, SCHEME_PRIORITIZE_HEALTH, SCHEME_PRIORITIZE_MANA, SCHEME_RANDOM, SCHEME_RANDOM_CHAIN, unitTarget, and urand().
Referenced by FillUnitTargets().
FindCorpseUsing()
template<typename T > WorldObject * Spell::FindCorpseUsing
Definition at line 572 of file Spell.cpp.
References GetSpellMaxRange(), m_caster, m_spellInfo, SpellEntry::rangeIndex, sSpellRangeStore, Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
finish()
void Spell::finish (bool ok = true)
Definition at line 4246 of file Spell.cpp.
References Unit::AI(), Unit::AttackStop(), Unit::CalculateHealAbsorb(), CastTriggerSpells(), Unit::ClearComboPoints(), CURRENT_AUTOREPEAT_SPELL, Unit::DealHeal(), ENCOUNTER_CREDIT_CAST_SPELL, Unit::GetClientControlling(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetSpellModOwner(), SpellEntry::HasAttribute(), SpellEntry::Id, Unit::InterruptSpell(), Unit::IsClientControlled(), Map::IsDungeon(), Object::IsInWorld(), Object::IsPlayer(), IsPositiveSpell(), IsRangedSpell(), m_caster, m_healthLeech, m_notifyAI, m_powerCost, m_spellInfo, m_spellState, m_TriggerSpells, m_trueCaster, m_UniqueTargetInfo, Unit::ModifyPower(), NeedsComboPoints(), UnitAI::OnSpellCastStateChange(), OnSuccessfulFinish(), SpellEntry::powerType, SPELL_ATTR_CANCELS_AUTO_ATTACK_COMBAT, SPELL_ATTR_EX_DISCOUNT_POWER_ON_MISS, SPELL_ATTR_EX_FINISHING_MOVE_DAMAGE, SPELL_MISS_DEFLECT, SPELL_MISS_DODGE, SPELL_MISS_MISS, SPELL_MISS_NONE, SPELL_MISS_PARRY, SPELL_STATE_CHANNELING, SPELL_STATE_FINISHED, and SPELLMOD_SPELL_COST_REFUND_ON_FAIL.
Referenced by cancel(), cast(), EffectDummy(), EffectInstaKill(), EffectTameCreature(), EffectTriggerRitualOfSummoning(), FillTargetMap(), FillUnitTargets(), Unit::FinishSpell(), handle_delayed(), handle_immediate(), SetTargetMap(), SpellStart(), StopCast(), and update().
GetAffectiveCaster()
Unit* Spell::GetAffectiveCaster () const inline
Definition at line 718 of file Spell.h.
References m_caster, m_originalCaster, and m_originalCasterGUID.
Referenced by CheckCast(), CheckTarget(), EffectApplyAura(), EffectDummy(), EffectHeal(), EffectHealMechanical(), EffectHealPct(), EffectPersistentAA(), EffectTameCreature(), EffectWMOChange(), EffectWMODamage(), EffectWMORepair(), ExecuteEffects(), GetSpellRangeAndRadius(), HandleImmediateEffectExecution(), InitializeDamageMultipliers(), spell_burrower_submerge::OnCheckCast(), spell_pursuit::OnEffectExecute(), spell_slave_trigger_closest::OnEffectExecute(), spell_summon_undead::OnEffectExecute(), spell_jainas_call::OnEffectExecute(), spell_call_of_sylvanas::OnEffectExecute(), spell_aggro_nearest_slave::OnEffectExecute(), spell_emblazon_runeblade::OnEffectExecute(), spell_siphon_of_acherus::OnEffectExecute(), spell_recall_eye_of_acherus::OnEffectExecute(), spell_devour_humanoid::OnEffectExecute(), spell_pursuing_spikes::OnEffectExecute(), spell_light_ball_passive::OnEffectExecute(), spell_dark_ball_passive::OnEffectExecute(), spell_create_lance::OnEffectExecute(), spell_mirrored_soul::OnEffectExecute(), spell_mirrored_soul_proc::OnEffectExecute(), spell_halls_of_reflection_clone::OnEffectExecute(), spell_icy_blast::OnEffectExecute(), spell_mark_fallen_champion::OnEffectExecute(), spell_coldflame_targeting::OnEffectExecute(), spell_incinerating_blast::OnEffectExecute(), spell_ride_red_dragon_buddy::OnEffectExecute(), spell_arcane_storm::OnEffectExecute(), spell_align_disk_aggro::OnEffectExecute(), spell_call_oculus_drake::OnEffectExecute(), ConflagrationTargeting::OnEffectExecute(), ConflagrationSaviana::OnEffectExecute(), spell_pulsing_shockwave::OnEffectExecute(), spell_ooze_combine::OnEffectExecute(), spell_taunt_brann::OnEffectExecute(), spell_water_globule_missile::OnEffectExecute(), spell_water_globule_merge::OnEffectExecute(), spell_summon_players::OnEffectExecute(), and spell_eject_all_passengers::OnEffectExecute().
GetAffectiveCasterObject()
WorldObject * Spell::GetAffectiveCasterObject () const
Definition at line 8757 of file Spell.cpp.
References Map::GetDynamicObject(), Map::GetGameObject(), WorldObject::GetMap(), ObjectGuid::IsDynamicObject(), ObjectGuid::IsGameObject(), Object::IsInWorld(), m_originalCaster, m_originalCasterGUID, and m_trueCaster.
Referenced by AddGOTarget(), AddUnitTarget(), CalculateDelayMomentForDst(), CheckScriptTargeting(), EffectScriptEffect(), FlagAuraBg::OnEffectExecute(), spell_battleground_banner_trigger::OnEffectExecute(), spell_outdoor_pvp_banner_trigger::OnEffectExecute(), SetTargetMap(), and MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer().
GetAffectiveCasterOrOwner()
Unit * Spell::GetAffectiveCasterOrOwner () const
Definition at line 8769 of file Spell.cpp.
References Object::IsUnit(), m_caster, and m_trueCaster.
Referenced by AddUnitTarget(), DoAllEffectOnTarget(), DoSpellHitOnUnit(), and HandleThreatSpells().
GetCastedTime()
uint32 Spell::GetCastedTime () const inline
Definition at line 669 of file Spell.h.
References m_timer.
GetCaster()
Unit* Spell::GetCaster () const inline
Definition at line 714 of file Spell.h.
References m_caster.
Referenced by EffectHeal(), SpellEvent::Execute(), spell_lingering_fumes_targetting::OnAfterHit(), ChaosStrikeDamage::OnAfterHit(), DirebrewDisarm::OnCast(), FaceRandomTarget::OnCast(), spell_acherus_deathcharger::OnCast(), BreathHaste::OnCast(), ShieldOfTheBlue::OnCast(), FlameDartMain::OnCast(), DarknessMuru::OnCast(), SurgeNalorakk::OnCast(), PlantWarsongBanner::OnCast(), BurnBody::OnCast(), WidowsEmbrace::OnCast(), NecroticAura::OnCast(), TargetCrystal::OnCast(), KillCreditDrakkariSkullcrusher::OnCast(), DeployParachute::OnCast(), Ghostly::OnCast(), SuperJump::OnCast(), CounterCharge::OnCast(), RibbonPoleDancerCheck::OnCast(), JuggleTorchCatchQuest::OnCast(), JuggleTorchCatch::OnCast(), Shadowmeld::OnCast(), Blizzard::OnCast(), VanishRogue::OnCast(), VictoryRush::OnCast(), SpellReflection::OnCast(), Intervene::OnCast(), PrayerOfMending::OnCheckCast(), LifeTap::OnCheckCast(), InactiveBattleground::OnCheckCast(), GraspOfTheEmeraldDream::OnCheckCast(), PlantWarsongBanner::OnCheckCast(), ScrapeCorrosiveSpit::OnCheckCast(), DropOffVillager::OnCheckCast(), HourglassOfEternity::OnCheckCast(), spell_tag_troll::OnCheckCast(), CheckCrystalFocusSpell::OnCheckCast(), ArcaneOrb::OnCheckCast(), GiddyUp::OnCheckCast(), deflection::OnCheckCast(), RetaliationCreature::OnCheckCast(), PreventSpellIfSameAuraOnCaster::OnCheckCast(), Disengage::OnCheckCast(), DevourMagic::OnCheckCast(), DemonicCircleTeleport::OnCheckCast(), ArcaneConcentration::OnCheckProc(), CurseOfBoundlessAgony::OnCheckTarget(), RaiseDeadDk::OnCheckTarget(), CorpseExplosionDK::OnCheckTarget(), AnetheronSleep::OnCheckTarget(), Enfeeble::OnCheckTarget(), TriggerStrafe::OnCheckTarget(), SpectralBlast::OnCheckTarget(), AzgalorDoom::OnCheckTarget(), HatefulStrikePrimer::OnCheckTarget(), VashjPersuasion::OnCheckTarget(), InsidiousWhisper::OnCheckTarget(), WateryGrave::OnCheckTarget(), StalkerLevitate::OnCheckTarget(), HurtfulStrikePrimer::OnCheckTarget(), JuggleTorchCatchQuest::OnCheckTarget(), HorsemanStartFire::OnCheckTarget(), Replenishment::OnCheckTarget(), DawnbladeAttack::OnCheckTarget(), WildGrowth::OnCheckTarget(), DivineHymn::OnCheckTarget(), HymnOfHope::OnCheckTarget(), CircleOfHealing::OnCheckTarget(), SpellReflectionRaid::OnCheckTarget(), SummonVoidSentinelSummoner::OnDestTarget(), FlignTorch::OnDestTarget(), MidnightMount::OnEffectExecute(), spell_split_teleport_boat::OnEffectExecute(), spell_gunship_portal_click::OnEffectExecute(), DestroyEgg::OnEffectExecute(), PortalAttunement::OnEffectExecute(), BlinkArcaneAnomaly::OnEffectExecute(), spell_dispel_scarlet_ghoul_credit::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_acherus_deathcharger::OnEffectExecute(), SendHead::OnEffectExecute(), HeadRequestsBody::OnEffectExecute(), spell_lingering_fumes_targetting::OnEffectExecute(), spell_valentine_boss_validate_area::OnEffectExecute(), spell_valentine_trigger_vial_a::OnEffectExecute(), spell_valentine_trigger_vial_b::OnEffectExecute(), SummonHakkar::OnEffectExecute(), HakkarSummoned::OnEffectExecute(), FogOfCorruption::OnEffectExecute(), SpectralRealmNotify::OnEffectExecute(), SinisterReflectionClone::OnEffectExecute(), CopyOffhandWeapon::OnEffectExecute(), ArlokkVanish::OnEffectExecute(), BloodSiphon::OnEffectExecute(), ThousandBladesRenataki::OnEffectExecute(), RenatakiVanish::OnEffectExecute(), ThekalResurrect::OnEffectExecute(), SummonNightmareIllusion::OnEffectExecute(), RandomAggro::OnEffectExecute(), GraspOfTheEmeraldDream::OnEffectExecute(), ConjureDreamRift::OnEffectExecute(), SummonManaFiendsMoam::OnEffectExecute(), HookTentacleTrigger::OnEffectExecute(), EntangleFankriss::OnEffectExecute(), AQWhirlwind::OnEffectExecute(), InitializeImages::OnEffectExecute(), InitializeImage::OnEffectExecute(), ViscidusExplode::OnEffectExecute(), SharePowers::OnEffectExecute(), spell_ley_line_focus_item_trigger::OnEffectExecute(), LiquidFireOfElune::OnEffectExecute(), GrapplingHook::OnEffectExecute(), GrapplingBeam::OnEffectExecute(), GluthDecimate::OnEffectExecute(), ToAnchorOne::OnEffectExecute(), ToAnchorTwo::OnEffectExecute(), ChooseRandomSkullPile::OnEffectExecute(), AnchorToSkull::OnEffectExecute(), HatefulStrikePrimer::OnEffectExecute(), FrostBreath::OnEffectExecute(), SapphironBlizzardInit::OnEffectExecute(), ThaddiusTeslaEffect::OnEffectExecute(), spell_ritual_of_the_sword::OnEffectExecute(), HarvestBlightCrystal::OnEffectExecute(), FixateBT::OnEffectExecute(), StormBlink::OnEffectExecute(), WateryGrave::OnEffectExecute(), SparrowhawkNet::OnEffectExecute(), ThrowAxe::OnEffectExecute(), SuperJump::OnEffectExecute(), RampagingCharge::OnEffectExecute(), AbsorbLife::OnEffectExecute(), ShartuulDiveBomb::OnEffectExecute(), ShartuulFireballBarrage::OnEffectExecute(), ChaosStrike::OnEffectExecute(), ChaosStrikeTransform::OnEffectExecute(), DeathBlast::OnEffectExecute(), DemonBroiledSurprise::OnEffectExecute(), PossessDemonShartuul::OnEffectExecute(), SmashShield::OnEffectExecute(), GDRChannel::OnEffectExecute(), LunarFestivalFirework::OnEffectExecute(), LightBonfire::OnEffectExecute(), ThrowTorch::OnEffectExecute(), JuggleTorchCatch::OnEffectExecute(), InheritMastersThreatList::OnEffectExecute(), HorsemanCreateWaterBucket::OnEffectExecute(), HorsemanStartFire::OnEffectExecute(), FireExtinguish::OnEffectExecute(), TKDive::OnEffectExecute(), HateToHalf::OnEffectExecute(), HateToZero::OnEffectExecute(), RaiseDeadDk::OnEffectExecute(), DeathCoilDK::OnEffectExecute(), CorpseExplosionDK::OnEffectExecute(), ExplodeGhoulCorpseExplosion::OnEffectExecute(), AggroRadius8YD::OnEffectExecute(), GuardianAggroSpell::OnEffectExecute(), RighteousDefense::OnEffectExecute(), DivineStormHeal::OnEffectExecute(), SpiritOfRedemptionHeal::OnEffectExecute(), PrayerOfMending::OnEffectExecute(), KillingSpree::OnEffectExecute(), LavaLash::OnEffectExecute(), StoneclawTotemAbsorb::OnEffectExecute(), LifeTap::OnEffectExecute(), ShadowBite::OnEffectExecute(), DemonicCircleTeleport::OnEffectExecute(), WarriorDevastate::OnEffectExecute(), RequestSecondMug::OnEffectExecute(), SummonMoleMachineTargetPicker::OnEffectExecute(), ShatteredSunMarksmanShoot::OnEffectExecute(), NetherBeam::OnEffectExecute(), SummonBlizzard::OnEffectExecute(), MassiveMagneticPull::OnEffectExecute(), FlameWreath::OnEffectExecute(), WrathOfTheTitansStacker::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), SpectralBlast::OnEffectExecute(), EntropiusDarkEnergy::OnEffectExecute(), TaunkaFaceMeSpellScript::OnEffectExecute(), spell_escape_from_silverbrook_credit_master::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), WebWrapMaexxna::OnEffectExecute(), WebWrapMessage::OnEffectExecute(), IceBolt::OnEffectExecute(), SapphironAchievementCheck::OnEffectExecute(), ShootRJR::OnEffectExecute(), GymersThrow::OnEffectExecute(), AssistBT::OnEffectExecute(), SupremusHatefulStrikePrimer::OnEffectExecute(), LeoWhirlwindProc::OnEffectExecute(), SomeoneGrabMe::OnEffectExecute(), HurtfulStrikePrimer::OnEffectExecute(), FaceHighestThreat::OnEffectExecute(), QuakeMagth::OnEffectExecute(), LivingFlareDetonator::OnEffectExecute(), Soulbind::OnEffectExecute(), DragonmawKnockdownTheAggroCheck::OnEffectExecute(), CleansingFlame::OnEffectExecute(), Iceblast::OnEffectExecute(), StunRopeAttunement::OnEffectExecute(), WOTAOldMainCastAndJump::OnEffectExecute(), WOTAOldSearch::OnEffectExecute(), NetherVaporSummonParent::OnEffectExecute(), BrewfestMountTransformation::OnEffectExecute(), BrewfestMountTransformationFactionSwap::OnEffectExecute(), FaceStringIDFacingBunny::OnEffectExecute(), FaceMe::OnEffectExecute(), BrewfestThrowKegPlayerDND::OnEffectExecute(), BrewfestRelayRacePlayerIncreaseMountDuration::OnEffectExecute(), BanishExile::OnEffectExecute(), TestRibbonPoleChannelTrigger::OnEffectExecute(), RevelerApplauseCheer::OnEffectExecute(), TorchToss::OnEffectExecute(), FlignTorch::OnEffectExecute(), JuggleTorchCatchQuest::OnEffectExecute(), ImpInABottleSay::OnEffectExecute(), GossipNPCPeriodicTriggerFidget::OnEffectExecute(), GossipNPCPeriodicTriggerTalk::OnEffectExecute(), DespawnerSelf::OnEffectExecute(), HorsemanStartFireTargetTest::OnEffectExecute(), HorsemanConflagrateTargetTest::OnEffectExecute(), BucketLands::OnEffectExecute(), HumanChildLaughter::OnEffectExecute(), HumanChildCrying::OnEffectExecute(), OrcChildLaughter::OnEffectExecute(), AstralBite::OnEffectExecute(), TribalDeath::OnEffectExecute(), BirthNoVisualInstantSpawn::OnEffectExecute(), DawnbladeAttack::OnEffectExecute(), spell_judgement::OnEffectExecute(), DivineStormCooldown::OnEffectExecute(), JudgementsOfTheWiseEnergize::OnEffectExecute(), LightwellRelay::OnEffectExecute(), Preparation::OnEffectExecute(), AncestralAwakeningSearch::OnEffectExecute(), VictoryRush::OnEffectExecute(), ScourgeStrike::OnHit(), ShredDruid::OnHit(), WarriorExecuteDamage::OnHit(), DelusionsOfJindo::OnHit(), ImpalingCharge::OnHit(), MagneticPullThaddius::OnHit(), FlameTsunamiDamage::OnHit(), QuelDanasShoot::OnHit(), KillCommand::OnHit(), ShadowWordDeath::OnHit(), EntropiusDarkEnergy::OnInit(), HatchEggs::OnInit(), ConflagrationTargeting::OnInit(), WildGrowth::OnInit(), DivineHymn::OnInit(), HymnOfHope::OnInit(), CircleOfHealing::OnInit(), LifeTap::OnInit(), SunderArmor::OnInit(), SpellReflectionRaid::OnInit(), Intervene::OnInit(), CheckReset::OnSuccessfulFinish(), KillCreditDrakkariSkullcrusher::OnSuccessfulFinish(), DragonmawKnockdownTheAggroCheck::OnSuccessfulFinish(), AllFiresOutTest::OnSuccessfulFinish(), BucketLands::OnSuccessfulFinish(), ExplodeGhoulCorpseExplosion::OnSuccessfulFinish(), DivineStorm::OnSuccessfulFinish(), OpeningCapping::OnSuccessfulStart(), GameobjectCallForHelpOnUsage::OnSuccessfulStart(), SummonCrusaderLeCraft::OnSummon(), SummonCrusaderLamoof::OnSummon(), SummonCrusaderJosephine::OnSummon(), SummonPlagueSpray::OnSummon(), TailsUpSummonFemaleFrostLeopard::OnSummon(), TailsUpSummonFemaleIcepawBear::OnSummon(), SummonMoleMachinePovBunny::OnSummon(), OCWAuchindounSummonAdventurer::OnSummon(), SummonBoss::OnSummon(), InstillLordValthalaksSpirit::OnSummon(), DancingRuneWeapon::OnSummon(), SummonGargoyle::OnSummon(), SentryTotem::OnSummon(), EartbindTotem::OnSummon(), EyeOfKilrogg::OnSummon(), SummonMoleMachine::OnSummon(), and SpellEvent::~SpellEvent().
GetCastingObject()
WorldObject * Spell::GetCastingObject () const
Definition at line 8774 of file Spell.cpp.
References Map::GetDynamicObject(), Map::GetGameObject(), WorldObject::GetMap(), ObjectGuid::IsDynamicObject(), Object::IsGameObject(), ObjectGuid::IsGameObject(), Object::IsInWorld(), m_originalCasterGUID, and m_trueCaster.
Referenced by Unit::CastCustomSpell(), GameObject::CastSpell(), Unit::CastSpell(), CheckCast(), CheckTarget(), EffectInstaKill(), EffectLearnPetSpell(), EffectLearnSkill(), EffectLearnSpell(), EffectSummonType(), EffectUnlearnSpecialization(), FillFromTargetFlags(), FillTargetMap(), ABEffect000::OnCheckTarget(), WondervoltTrap::OnEffectExecute(), PowerOfTheBlueFlight::OnEffectExecute(), SetTargetMap(), and MaNGOS::SpellNotifierPlayer::SpellNotifierPlayer().
GetCastItem()
Item* Spell::GetCastItem () inline
Definition at line 634 of file Spell.h.
References m_CastItem.
Referenced by GetSpellCastTime().
GetCastTime()
int32 Spell::GetCastTime () const inline
Definition at line 668 of file Spell.h.
References m_casttime.
Referenced by _handle_immediate_phase(), and UnitAI::OnSpellCastStateChange().
GetCone()
float Spell::GetCone () protected
Definition at line 9138 of file Spell.cpp.
References SpellEntry::Id, SQLStorage::LookupEntry(), M_PI_F, m_spellInfo, sSpellCones, and sSpellMgr.
Referenced by SetTargetMap().
GetCurrentContainer()
CurrentSpellTypes Spell::GetCurrentContainer () const
Definition at line 8266 of file Spell.cpp.
References CURRENT_AUTOREPEAT_SPELL, CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, CURRENT_MELEE_SPELL, IsAutoRepeat(), IsChanneledSpell(), IsNextMeleeSwingSpell(), and m_spellInfo.
Referenced by Unit::SetCurrentCastedSpell().
GetDamage()
uint32 Spell::GetDamage () inline
Definition at line 858 of file Spell.h.
References damage.
Referenced by MoltenFuryFlamebringer::OnEffectExecute(), spell_incinerating_blast::OnEffectExecute(), spell_pulsing_shockwave::OnEffectExecute(), ThrowAxe::OnEffectExecute(), SuperJump::OnEffectExecute(), ChaosStrikeDamage::OnEffectExecute(), DiveBomb::OnEffectExecute(), SplitDamage::OnEffectExecute(), DeathCoilDK::OnEffectExecute(), DivineStormHeal::OnEffectExecute(), PrayerOfMending::OnEffectExecute(), LavaLash::OnEffectExecute(), StoneclawTotemAbsorb::OnEffectExecute(), ShadowBite::OnEffectExecute(), WarriorDevastate::OnEffectExecute(), HeroicStrike::OnEffectExecute(), Iceblast::OnEffectExecute(), JudgementsOfTheWiseEnergize::OnEffectExecute(), AncestralAwakeningSearch::OnEffectExecute(), and VictoryRush::OnEffectExecute().
GetDelayMoment()
uint64 Spell::GetDelayMoment () const inline
Definition at line 701 of file Spell.h.
References m_delayMoment.
Referenced by SpellEvent::Execute().
GetDelayStart()
uint64 Spell::GetDelayStart () const inline
Definition at line 699 of file Spell.h.
References m_delayStart.
Referenced by SpellEvent::Execute(), and RecalculateDelayMomentForDest().
GetGOTarget()
GameObject* Spell::GetGOTarget () inline
Definition at line 857 of file Spell.h.
References gameObjTarget.
Referenced by spell_split_teleport_boat::OnEffectExecute(), DestroyEgg::OnEffectExecute(), LunarFestivalFirework::OnEffectExecute(), BonfireArtkit::OnEffectExecute(), and InvisibleCampfireRemove::OnEffectExecute().
GetItemTarget()
Item* Spell::GetItemTarget () inline
Definition at line 856 of file Spell.h.
References itemTarget.
GetMinMaxRange()
std::pair< float, float > Spell::GetMinMaxRange (bool strict) protected
Definition at line 7360 of file Spell.cpp.
References WorldObject::CanAssistSpell(), SpellRangeEntry::Flags, WorldObject::GetCombatReach(), Unit::GetCombatReach(), WorldObject::GetCombinedCombatReach(), SpellCastTargets::getCorpseTarget(), GetSpellMaxRange(), GetSpellMinRange(), WorldObject::GetSpellModOwner(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Player::GetWeaponForAttack(), SpellEntry::HasAttribute(), SpellEntry::Id, Unit::IsMovingForward(), IsNextMeleeSwingSpell(), Unit::IsWalking(), m_spellInfo, m_targets, m_trueCaster, MELEE_LEEWAY, RANGED_ATTACK, SpellEntry::rangeIndex, SPELL_ATTR_USES_RANGED_SLOT, SPELL_RANGE_FLAG_MELEE, SPELL_RANGE_FLAG_RANGED, SPELLMOD_RANGE, sSpellRangeStore, and TYPEID_PLAYER.
Referenced by CheckRange().
GetNewRuneState()
uint8 Spell::GetNewRuneState () const inline
Definition at line 882 of file Spell.h.
References m_runesStateAfterCast.
Referenced by DeathRuneDK::OnProc(), and SendSpellGo().
GetOldRuneState()
uint8 Spell::GetOldRuneState () const inline
Definition at line 881 of file Spell.h.
References m_runesState.
Referenced by DeathRuneDK::OnProc(), and SendSpellGo().
GetPhaseMaskOverride()
uint32 Spell::GetPhaseMaskOverride ()
Definition at line 9916 of file Spell.cpp.
References GetSpellScript().
Referenced by DoSummonWild().
GetPowerCost()
uint32 Spell::GetPowerCost () const inline
Definition at line 872 of file Spell.h.
References m_powerCost.
GetPrefilledUnitTargetOrUnitTarget()
Unit * Spell::GetPrefilledUnitTargetOrUnitTarget (SpellEffectIndex effIndex) const protected
Definition at line 5487 of file Spell.cpp.
References WorldObject::GetMap(), Map::GetUnit(), SpellCastTargets::getUnitTarget(), m_targets, m_trueCaster, and m_UniqueTargetInfo.
Referenced by CheckCast().
GetSchoolMask()
SpellSchoolMask Spell::GetSchoolMask () inline
Definition at line 860 of file Spell.h.
References m_spellSchoolMask.
Referenced by ViscidusFrostWeakness::OnProc().
GetScriptValue()
uint64 Spell::GetScriptValue () const inline
Definition at line 836 of file Spell.h.
References m_scriptValue.
Referenced by EffectApplyAreaAura(), EffectApplyAura(), DivineStorm::OnAfterHit(), LifeTap::OnCheckCast(), PolarityShift::OnEffectExecute(), WateryGrave::OnEffectExecute(), CorpseExplosionDK::OnEffectExecute(), LifeTap::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), InciteChaos::OnEffectExecute(), KillCreditDrakkariSkullcrusher::OnSuccessfulFinish(), DragonmawKnockdownTheAggroCheck::OnSuccessfulFinish(), AllFiresOutTest::OnSuccessfulFinish(), BucketLands::OnSuccessfulFinish(), and DivineStorm::OnSuccessfulFinish().
GetSpellAuraHolder()
SpellAuraHolder* Spell::GetSpellAuraHolder () inline
Definition at line 877 of file Spell.h.
References m_spellAuraHolder.
GetSpellRangeAndRadius()
void Spell::GetSpellRangeAndRadius (SpellEffectIndex effIndex, float & radius, bool targetB, uint32 & effectChainTarget) protected
Definition at line 8944 of file Spell.cpp.
References AOE_LEEWAY, CONTACT_DISTANCE, CURRENT_GENERIC_SPELL, DEFAULT_VISIBILITY_BGARENAS, DEFAULT_VISIBILITY_INSTANCE, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectRadiusIndex, SpellTargetInfo::enumerator, SpellTargetInfo::filter, GetAffectiveCaster(), Unit::GetCurrentSpell(), Unit::GetSpellAuraHolder(), GetSpellMaxRange(), Player::GetSpellModOwner(), GetSpellRadius(), GetTriggeredByAuraSpellInfo(), SpellEntry::Id, INTERACTION_DISTANCE, Unit::IsMoving(), Unit::IsWalking(), m_caster, m_spellInfo, MAX_VISIBILITY_DISTANCE, OnRadiusCalculate(), SpellEntry::rangeIndex, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_PALADIN, SpellEntry::SpellFamilyName, SPELLMOD_JUMP_TARGETS, SPELLMOD_RADIUS, SpellTargetInfoTable, sSpellRadiusStore, sSpellRangeStore, TARGET_ENUMERATOR_AOE, TARGET_ENUMERATOR_CHAIN, TARGET_ENUMERATOR_CONE, TARGET_LOCATION_CASTER_BACK, TARGET_LOCATION_CASTER_BACK_LEFT, TARGET_LOCATION_CASTER_BACK_RIGHT, TARGET_LOCATION_CASTER_FRONT, TARGET_LOCATION_CASTER_FRONT_LEFT, TARGET_LOCATION_CASTER_FRONT_RIGHT, TARGET_LOCATION_CASTER_LEFT, TARGET_LOCATION_CASTER_RIGHT, TARGET_SCRIPT, TARGET_TYPE_GAMEOBJECT, TARGET_TYPE_LOCATION_DEST, TARGET_TYPE_LOCATION_TRAJ, TARGET_TYPE_UNIT, and SpellTargetInfo::type.
Referenced by SetTargetMap().
GetSpellScript()
SpellScript* Spell::GetSpellScript () const inline
Definition at line 834 of file Spell.h.
References m_spellScript.
Referenced by GetPhaseMaskOverride(), OnAfterHit(), OnCast(), OnCheckCast(), OnCheckTarget(), OnDestTarget(), OnEffectExecute(), OnHit(), OnInit(), OnRadiusCalculate(), OnSuccessfulFinish(), OnSuccessfulStart(), and OnSummon().
GetSpellSpeed()
float Spell::GetSpellSpeed () const
Definition at line 8786 of file Spell.cpp.
References IsChanneledSpell(), Object::IsGameObject(), m_overridenSpeed, m_overrideSpeed, m_spellInfo, m_trueCaster, and SpellEntry::speed.
Referenced by AddDestExecution(), AddGOTarget(), AddUnitTarget(), IsDelayedSpell(), ProcSpellAuraTriggers(), and update().
GetSpellStartTravelling()
uint32 Spell::GetSpellStartTravelling () const inline
Definition at line 703 of file Spell.h.
References m_travellingStart.
Referenced by Unit::DealDamage().
getState()
uint32 Spell::getState () const inline
Definition at line 578 of file Spell.h.
References m_spellState.
Referenced by SpellEvent::Abort(), DelayedChannel(), SpellEvent::Execute(), and SpellEvent::~SpellEvent().
GetTargetList()
TargetList& Spell::GetTargetList () inline
Definition at line 875 of file Spell.h.
References m_UniqueTargetInfo.
Referenced by FaceRandomTarget::OnCast(), spell_acherus_deathcharger::OnCast(), CorrosiveSpit::OnCast(), RibbonPoleDancerCheck::OnCast(), JuggleTorchCatchQuest::OnCast(), JuggleTorchCatch::OnCast(), spell_vortex::OnEffectExecute(), spell_rallying_shout::OnEffectExecute(), DiveBomb::OnEffectExecute(), SplitDamage::OnEffectExecute(), RaiseDeadDk::OnEffectExecute(), DivineStormHeal::OnEffectExecute(), SapphironAchievementCheck::OnEffectExecute(), SupremusHatefulStrikePrimer::OnEffectExecute(), and HurtfulStrikePrimer::OnEffectExecute().
GetTotalTargetAbsorb()
uint32 Spell::GetTotalTargetAbsorb () inline
Definition at line 863 of file Spell.h.
References m_absorb.
Referenced by ShadowWordDeath::OnHit().
GetTotalTargetDamage()
uint32 Spell::GetTotalTargetDamage () inline
Definition at line 862 of file Spell.h.
References m_damage.
Referenced by DivineStorm::OnAfterHit(), ScourgeStrike::OnHit(), and ShadowWordDeath::OnHit().
GetTriggeredByAuraSpellInfo()
SpellEntry const* Spell::GetTriggeredByAuraSpellInfo () const inline
Definition at line 708 of file Spell.h.
References m_triggeredByAuraSpell.
Referenced by GetSpellRangeAndRadius(), NetherBeam::OnCheckTarget(), AQWhirlwind::OnEffectExecute(), DivineHymn::OnInit(), and HymnOfHope::OnInit().
GetTrueCaster()
WorldObject* Spell::GetTrueCaster () const inline
Definition at line 889 of file Spell.h.
References m_trueCaster.
Referenced by SpellEvent::Execute(), SpellLog::Initialize(), FlagClickBg::OnCheckCast(), SummonVoidSentinelSummoner::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), FlagClickBg::OnEffectExecute(), Entrapment::OnProc(), and SpellLog::SendToSet().
GetUnitTarget()
Unit* Spell::GetUnitTarget () inline
Definition at line 855 of file Spell.h.
References unitTarget.
Referenced by ChaosStrikeDamage::OnAfterHit(), DiveBomb::OnAfterHit(), GiddyUp::OnAfterHit(), MidnightMount::OnEffectExecute(), spell_conjure_flame_sphere::OnEffectExecute(), spell_teleporting_dalaran::OnEffectExecute(), spell_pursuit::OnEffectExecute(), spell_necromantic_power::OnEffectExecute(), spell_slave_trigger_closest::OnEffectExecute(), spell_jainas_call::OnEffectExecute(), spell_call_of_sylvanas::OnEffectExecute(), spell_aggro_nearest_slave::OnEffectExecute(), spell_awaken_gortok::OnEffectExecute(), spell_launch_harpoon::OnEffectExecute(), spell_poisoned_spear::OnEffectExecute(), spell_avenging_spirits::OnEffectExecute(), VazrudenLiquidFire::OnEffectExecute(), SoccothratesCharge::OnEffectExecute(), FlagAuraBg::OnEffectExecute(), spell_battleground_banner_trigger::OnEffectExecute(), spell_outdoor_pvp_banner_trigger::OnEffectExecute(), spell_gunship_portal_click::OnEffectExecute(), spell_repair_cannon::OnEffectExecute(), spell_end_of_round::OnEffectExecute(), spell_teleport_sota::OnEffectExecute(), PortalAttunement::OnEffectExecute(), BlinkArcaneAnomaly::OnEffectExecute(), spell_death_knight_initiate_visual::OnEffectExecute(), spell_siphon_of_acherus::OnEffectExecute(), spell_siphon_of_acherus_credit::OnEffectExecute(), spell_summon_ghouls_scarlet_crusade::OnEffectExecute(), spell_ghoulplosion::OnEffectExecute(), spell_dispel_scarlet_ghoul_credit::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_devour_humanoid::OnEffectExecute(), spell_portal_to_capital_city::OnEffectExecute(), spell_skeletal_gryphon_escape::OnEffectExecute(), spell_death_gate::OnEffectExecute(), SendHead::OnEffectExecute(), HeadRequestsBody::OnEffectExecute(), spell_lingering_fumes_targetting::OnEffectExecute(), spell_valentine_boss_validate_area::OnEffectExecute(), spell_valentine_trigger_vial_a::OnEffectExecute(), spell_valentine_trigger_vial_b::OnEffectExecute(), StompBrutallus::OnEffectExecute(), FogOfCorruption::OnEffectExecute(), SpectralRealmNotify::OnEffectExecute(), CurseOfBoundlessAgonyRemoval::OnEffectExecute(), SinisterReflectionClone::OnEffectExecute(), CopyOffhandWeapon::OnEffectExecute(), FlameDart::OnEffectExecute(), HakkarPowerDown::OnEffectExecute(), BloodSiphon::OnEffectExecute(), DespawnChainedSpirits::OnEffectExecute(), RenatakiVanish::OnEffectExecute(), RandomAggro::OnEffectExecute(), GraspOfTheEmeraldDream::OnEffectExecute(), SummonCThunTentacles::OnEffectExecute(), RotateTrigger::OnEffectExecute(), HookTentacleTrigger::OnEffectExecute(), ExitStomach::OnEffectExecute(), InitializeImages::OnEffectExecute(), InitializeImage::OnEffectExecute(), TeleportImage::OnEffectExecute(), SummonToxicSlime::OnEffectExecute(), ViscidusSummonGlobs::OnEffectExecute(), ViscidusShrinks::OnEffectExecute(), RejoinViscidus::OnEffectExecute(), ViscidusGrows::OnEffectExecute(), SharePowers::OnEffectExecute(), spell_burrower_submerge::OnEffectExecute(), spell_pursuing_spikes::OnEffectExecute(), spell_disengage::OnEffectExecute(), spell_nether_power::OnEffectExecute(), spell_light_ball_passive::OnEffectExecute(), spell_dark_ball_passive::OnEffectExecute(), spell_clear_valkyr_essence::OnEffectExecute(), spell_clear_valkyr_touch::OnEffectExecute(), spell_powering_up::OnEffectExecute(), spell_ley_line_focus_item_trigger::OnEffectExecute(), LiquidFireOfElune::OnEffectExecute(), spell_tag_troll::OnEffectExecute(), spell_out_cold::OnEffectExecute(), spell_assemble_cage::OnEffectExecute(), MoltenFuryFlamebringer::OnEffectExecute(), spell_eck_spit::OnEffectExecute(), GrapplingHook::OnEffectExecute(), GrapplingBeam::OnEffectExecute(), spell_create_lance::OnEffectExecute(), spell_consume_soul::OnEffectExecute(), spell_wailing_souls::OnEffectExecute(), spell_mirrored_soul::OnEffectExecute(), spell_mirrored_soul_proc::OnEffectExecute(), spell_halls_of_reflection_clone::OnEffectExecute(), spell_start_halls_of_reflection_quest::OnEffectExecute(), spell_mark_fallen_champion::OnEffectExecute(), spell_blood_link::OnEffectExecute(), spell_dark_transformation::OnEffectExecute(), spell_dark_empowerment::OnEffectExecute(), spell_dark_martyrdom::OnEffectExecute(), spell_bone_spike_graveyard::OnEffectExecute(), spell_bone_spike_graveyard_storm::OnEffectExecute(), spell_coldflame_targeting::OnEffectExecute(), spell_coldflame::OnEffectExecute(), spell_coldflame_summon::OnEffectExecute(), PlayMovie::OnEffectExecute(), spell_incinerating_blast::OnEffectExecute(), GluthDecimate::OnEffectExecute(), ToAnchorOne::OnEffectExecute(), ToAnchorTwo::OnEffectExecute(), ChooseRandomSkullPile::OnEffectExecute(), AnchorToSkull::OnEffectExecute(), HatefulStrikePrimer::OnEffectExecute(), SapphironBlizzardInit::OnEffectExecute(), ShockThaddius::OnEffectExecute(), ThaddiusLightningVisual::OnEffectExecute(), PolarityShift::OnEffectExecute(), TriggerTeslas::OnEffectExecute(), ThaddiusTeslaEffect::OnEffectExecute(), spell_ride_red_dragon_buddy::OnEffectExecute(), spell_arcane_bomb::OnEffectExecute(), spell_arcane_storm::OnEffectExecute(), spell_vortex::OnEffectExecute(), spell_align_disk_aggro::OnEffectExecute(), spell_charge_rifts::OnEffectExecute(), spell_crystal_spikes::OnEffectExecute(), spell_summon_telestra_clones::OnEffectExecute(), spell_lava_strike::OnEffectExecute(), spell_clear_debuffs::OnEffectExecute(), ConflagrationTargeting::OnEffectExecute(), ConflagrationSaviana::OnEffectExecute(), spell_rallying_shout::OnEffectExecute(), spell_pulsing_shockwave::OnEffectExecute(), spell_ooze_combine::OnEffectExecute(), spell_shatter::OnEffectExecute(), spell_taunt_brann::OnEffectExecute(), spell_cauterize::OnEffectExecute(), spell_ritual_of_the_sword::OnEffectExecute(), spell_svala_transforming::OnEffectExecute(), spell_water_globule_missile::OnEffectExecute(), spell_water_globule_merge::OnEffectExecute(), spell_summon_players::OnEffectExecute(), spell_teleport_inside_violet_hold::OnEffectExecute(), spell_teleport_lake_wintergrasp::OnEffectExecute(), spell_build_wintergrasp_vehicle::OnEffectExecute(), ATangledSkeinEncasingWebsEffect::OnEffectExecute(), FixateBT::OnEffectExecute(), StormBlink::OnEffectExecute(), ParasiticShadowfiendAura::OnEffectExecute(), ShadowPrison::OnEffectExecute(), TidalSurge::OnEffectExecute(), ClearConsumingMadness::OnEffectExecute(), WateryGrave::OnEffectExecute(), StalkerLevitate::OnEffectExecute(), MagneticPull::OnEffectExecute(), SummonSmokeBeacon::OnEffectExecute(), SparrowhawkNet::OnEffectExecute(), UltraDeconsolodationZapper::OnEffectExecute(), ThrowAxe::OnEffectExecute(), SuperJump::OnEffectExecute(), RampagingCharge::OnEffectExecute(), ShartuulFireballBarrage::OnEffectExecute(), ChaosStrike::OnEffectExecute(), ChaosStrikeDamage::OnEffectExecute(), DeathBlast::OnEffectExecute(), DiveBomb::OnEffectExecute(), RamFatigue::OnEffectExecute(), JuggleTorchCatch::OnEffectExecute(), InheritMastersThreatList::OnEffectExecute(), HorsemanCreateWaterBucket::OnEffectExecute(), HorsemanStartFire::OnEffectExecute(), FireExtinguish::OnEffectExecute(), TKDive::OnEffectExecute(), WondervoltTrap::OnEffectExecute(), HateToHalf::OnEffectExecute(), HateToZero::OnEffectExecute(), ForgetArmorsmith::OnEffectExecute(), ForgetWeaponsmith::OnEffectExecute(), ForgetSwordsmith::OnEffectExecute(), ForgetAxesmith::OnEffectExecute(), ForgetHammersmith::OnEffectExecute(), RaiseDeadDk::OnEffectExecute(), DeathCoilDK::OnEffectExecute(), CorpseExplosionDK::OnEffectExecute(), ExplodeGhoulCorpseExplosion::OnEffectExecute(), AggroRadius8YD::OnEffectExecute(), GuardianAggroSpell::OnEffectExecute(), RighteousDefense::OnEffectExecute(), DivineStormHeal::OnEffectExecute(), PrayerOfMending::OnEffectExecute(), KillingSpree::OnEffectExecute(), LavaLash::OnEffectExecute(), StoneclawTotemAbsorb::OnEffectExecute(), WarriorDevastate::OnEffectExecute(), HeroicStrike::OnEffectExecute(), VigilanceTrigger::OnEffectExecute(), DespawnMushrooms::OnEffectExecute(), FlagClickBg::OnEffectExecute(), RequestSecondMug::OnEffectExecute(), SummonMoleMachineTargetPicker::OnEffectExecute(), NetherBeam::OnEffectExecute(), EnfeebleRemoval::OnEffectExecute(), SummonBlizzard::OnEffectExecute(), DispelBlizzard::OnEffectExecute(), MassiveMagneticPull::OnEffectExecute(), FlameWreath::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), spell_clear_flight_mgt::OnEffectExecute(), spell_fel_crystal_dummy::OnEffectExecute(), spell_clear_energy_feedback::OnEffectExecute(), SpellBurnBrutallus::OnEffectExecute(), FreezeMadrigosa::OnEffectExecute(), SoulSever::OnEffectExecute(), SpectralBlast::OnEffectExecute(), SpectralRealm::OnEffectExecute(), SinisterReflection::OnEffectExecute(), PowerOfTheBlueFlight::OnEffectExecute(), DarkFiendDummy::OnEffectExecute(), SummonBloodElvesScript::OnEffectExecute(), EntropiusDarkEnergy::OnEffectExecute(), OpenAllPortals::OnEffectExecute(), OpenPortalMuru::OnEffectExecute(), SummonVoidSentinelSummonerVisual::OnEffectExecute(), SunwellTeleport::OnEffectExecute(), LeftForDead::OnEffectExecute(), ViscidusDespawnAdds::OnEffectExecute(), ViscidusSuicideTrigger::OnEffectExecute(), TaunkaFaceMeSpellScript::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), WebWrapMessage::OnEffectExecute(), DespawnIceBlock::OnEffectExecute(), ShootRJR::OnEffectExecute(), PotCheck::OnEffectExecute(), InciteChaos::OnEffectExecute(), AssistBT::OnEffectExecute(), SupremusHatefulStrikePrimer::OnEffectExecute(), KoiKoiDeath::OnEffectExecute(), SporeDropEffect::OnEffectExecute(), Spout::OnEffectExecute(), SomeoneGrabMe::OnEffectExecute(), HurtfulStrikePrimer::OnEffectExecute(), LivingFlareDetonator::OnEffectExecute(), CursedScarabPeriodicTrigger::OnEffectExecute(), CursedScarabDespawnPeriodicTrigger::OnEffectExecute(), ExposeRazorthornRoot::OnEffectExecute(), Soulbind::OnEffectExecute(), DragonmawKnockdownTheAggroCheck::OnEffectExecute(), TouchOfMadness::OnEffectExecute(), MadnessRift::OnEffectExecute(), Iceblast::OnEffectExecute(), StunRopeAttunement::OnEffectExecute(), AlarEmberBlast::OnEffectExecute(), WOTAOldMainCastAndJump::OnEffectExecute(), WOTAOldSearch::OnEffectExecute(), WOTAOldRemove::OnEffectExecute(), RemoveWeapons::OnEffectExecute(), FaceStringIDFacingBunny::OnEffectExecute(), FaceMe::OnEffectExecute(), MakeBunnySummonMoleMachine::OnEffectExecute(), OcwSilvermoonLvl70EtcCheer::OnEffectExecute(), BanishExile::OnEffectExecute(), RevelerApplauseCheer::OnEffectExecute(), TorchToss::OnEffectExecute(), TorchTargetPicker::OnEffectExecute(), JuggleTorchCatchQuest::OnEffectExecute(), GossipNPCPeriodicTriggerTalk::OnEffectExecute(), CommuniqueTrigger::OnEffectExecute(), HorsemanStartFireTargetTest::OnEffectExecute(), AllFiresOutTest::OnEffectExecute(), HorsemanConflagrateTargetTest::OnEffectExecute(), BucketLands::OnEffectExecute(), UseCorpse::OnEffectExecute(), TribalDeath::OnEffectExecute(), Submerged::OnEffectExecute(), Stand::OnEffectExecute(), DawnbladeAttack::OnEffectExecute(), spell_judgement::OnEffectExecute(), LightwellRelay::OnEffectExecute(), AncestralAwakeningSearch::OnEffectExecute(), ScourgeStrike::OnHit(), ShredDruid::OnHit(), SapRogue::OnHit(), ImpalingCharge::OnHit(), MagneticPullThaddius::OnHit(), FlameTsunamiDamage::OnHit(), QuelDanasShoot::OnHit(), and CheckReset::OnSuccessfulFinish().
GetUsableHealthStoneItemType()
uint32 Spell::GetUsableHealthStoneItemType (Unit * unitTarget)
Definition at line 13114 of file SpellEffects.cpp.
References Unit::GetAurasByType(), Object::GetTypeId(), SpellEntry::Id, m_spellInfo, SPELL_AURA_DUMMY, and TYPEID_PLAYER.
Referenced by EffectScriptEffect(), and OnCheckCast().
handle_delayed()
uint64 Spell::handle_delayed (uint64 t_offset)
Definition at line 3838 of file Spell.cpp.
References _handle_finish_phase(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), Spell::DestTargetInfo::effectMask, Spell::DestTargetInfo::effectMaskProcessed, finish(), WorldObject::GetSpellModOwner(), m_destTargetInfo, m_trueCaster, m_UniqueGOTargetInfo, m_UniqueTargetInfo, ProcReflectProcs(), and Spell::DestTargetInfo::timeDelay.
Referenced by SpellEvent::Execute().
handle_immediate()
void Spell::handle_immediate ()
Definition at line 3817 of file Spell.cpp.
References _handle_finish_phase(), DoAllEffectOnTarget(), finish(), m_spellState, m_uniqueCorpseTargetInfo, m_UniqueGOTargetInfo, m_UniqueTargetInfo, ProcessAOECaps(), and SPELL_STATE_CHANNELING.
Referenced by cast(), and SpellEvent::Execute().
HandleEffect()
void Spell::HandleEffect (Unit * unitTarget, Item * itemTarget, GameObject * GOTarget, SpellEffectIndex effIdx, float damageMultiplier = 1.0)
Definition at line 5399 of file Spell.cpp.
References CalculateSpellEffectValue(), damage, damagePerEffect, DEBUG_FILTER_LOG, SpellEntry::Effect, gameObjTarget, Object::GetGuidStr(), SpellEntry::Id, irand(), IsEffectWithImplementedMultiplier(), itemTarget, LOG_FILTER_SPELL_CAST, m_damage, m_damagePerEffect, m_effectTriggerChance, m_healing, m_healingPerEffect, m_spellInfo, MAX_SPELL_EFFECTS, OnEffectExecute(), sLog, and unitTarget.
Referenced by DoAllTargetlessEffects(), and ExecuteEffects().
HandleImmediateEffectExecution()
void Spell::HandleImmediateEffectExecution (TargetInfo * target) protected
Definition at line 1750 of file Spell.cpp.
References Spell::TargetInfo::damage, Spell::TargetInfo::effectHitMask, Spell::TargetInfo::effectMask, Spell::TargetInfo::effectMaskProcessed, ExecuteEffects(), GetAffectiveCaster(), Object::GetObjectGuid(), ObjectAccessor::GetUnit(), Spell::TargetInfo::healing, Spell::TargetInfo::HitInfo, Spell::TargetInfo::isCrit, IsEffectHandledImmediatelySpellLaunch(), m_absorb, m_caster, m_damage, m_healing, m_spellInfo, m_spellSchoolMask, m_trueCaster, MAX_EFFECT_INDEX, Spell::TargetInfo::missCondition, Spell::TargetInfo::reflectResult, Unit::RollSpellCritOutcome(), SPELL_MISS_NONE, SPELL_MISS_REFLECT, Spell::TargetInfo::targetGUID, and unitTarget.
Referenced by _handle_immediate_phase().
HandleThreatSpells()
void Spell::HandleThreatSpells ()
Definition at line 5311 of file Spell.cpp.
References Unit::AddThreat(), SpellThreatEntry::ap_bonus, Unit::CanHaveThreatList(), DEBUG_FILTER_LOG, SpellEntry::Effect, GetAffectiveCasterOrOwner(), Unit::getHostileRefManager(), Object::GetObjectGuid(), GetSpellSchoolMask(), Unit::GetTotalAttackPowerValue(), ObjectAccessor::GetUnit(), GetWeaponAttackType(), SpellEntry::Id, LOG_FILTER_SPELL_CAST, m_caster, m_negativeEffectMask, m_spellInfo, m_trueCaster, m_UniqueTargetInfo, MAX_EFFECT_INDEX, SIZEFMTD, SPELL_MISS_NONE, sSpellMgr, SpellThreatEntry::threat, and HostileRefManager::threatAssist().
Referenced by _handle_immediate_phase().
HaveTargetsForEffect()
bool Spell::HaveTargetsForEffect (SpellEffectIndex effect) const
Definition at line 8464 of file Spell.cpp.
References m_UniqueGOTargetInfo, m_UniqueItemInfo, and m_UniqueTargetInfo.
IgnoreItemRequirements()
bool Spell::IgnoreItemRequirements () const protected
Check if it's an enchant scroll. These have no required reagents even though their spell does.
Not own traded item (in trader trade slot) req. reagents including triggered spell case
Some triggered spells have same reagents that have master spell expected in test: master spell have reagents in first slot then triggered don't must use own
Definition at line 7636 of file Spell.cpp.
References ItemPrototype::Flags, SpellCastTargets::getItemTarget(), Object::GetObjectGuid(), Item::GetProto(), SpellEntry::Id, ITEM_FLAG_NO_REAGENT_COST, m_caster, m_CastItem, m_channelOnly, m_ignoreCosts, m_IsTriggeredSpell, m_spellInfo, m_targets, m_triggeredBySpellInfo, and SpellEntry::Reagent.
Referenced by CheckItems(), and TakeReagents().
InitializeDamageMultipliers()
void Spell::InitializeDamageMultipliers () protected
Definition at line 1799 of file Spell.cpp.
References SpellEntry::Effect, SpellEntry::EffectChainTarget, SpellEntry::EffectImplicitTargetA, GetAffectiveCaster(), Player::GetSpellModOwner(), SpellEntry::Id, m_applyMultiplierMask, m_damageMultipliers, m_spellInfo, MAX_EFFECT_INDEX, SPELLMOD_JUMP_TARGETS, TARGET_UNIT_ENEMY, and TARGET_UNIT_FRIEND_CHAIN_HEAL.
Referenced by cast().
IsAliveUnitPresentInTargetList()
bool Spell::IsAliveUnitPresentInTargetList () protected
Definition at line 1817 of file Spell.cpp.
References SpellEntry::Effect, Object::GetObjectGuid(), ObjectAccessor::GetUnit(), IsValidDeadOrAliveTarget(), m_caster, m_needAliveTargetMask, m_spellInfo, m_trueCaster, m_UniqueTargetInfo, MAX_EFFECT_INDEX, SPELL_EFFECT_APPLY_AURA, and SPELL_MISS_NONE.
Referenced by update().
IsAuraProcced()
bool Spell::IsAuraProcced (Aura * aura)
Definition at line 8931 of file Spell.cpp.
References m_procOnceHolder.
Referenced by Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::IsTriggeredAtSpellProcEvent().
IsAutoRepeat()
bool Spell::IsAutoRepeat () const inline
Definition at line 670 of file Spell.h.
References m_autoRepeat.
Referenced by DoAllEffectOnTarget(), GetCurrentContainer(), GetSpellCastTime(), PreCastCheck(), Prepare(), update(), and PlayerbotAI::UpdateAI().
IsChannelActive()
bool Spell::IsChannelActive () const inline
Definition at line 690 of file Spell.h.
References Object::GetUInt32Value(), m_caster, and UNIT_FIELD_CHANNEL_SPELL.
Referenced by DoAllEffectOnTarget(), and PlayerbotAI::UpdateAI().
isDelayableNoMore()
bool Spell::isDelayableNoMore () inline protected
Definition at line 934 of file Spell.h.
References m_delayAtDamageCount.
Referenced by Delayed(), and DelayedChannel().
IsDelayedSpell()
bool Spell::IsDelayedSpell () const
Definition at line 8799 of file Spell.cpp.
References GetSpellSpeed(), IsChanneledSpell(), and m_spellInfo.
Referenced by _handle_immediate_phase(), and cast().
IsDeletable()
bool Spell::IsDeletable () const inline
Definition at line 695 of file Spell.h.
References m_executedCurrently, and m_referencedFromCurrentSpell.
Referenced by SpellEvent::Execute(), SpellEvent::IsDeletable(), and SpellEvent::~SpellEvent().
IsEffectWithImplementedMultiplier()
bool Spell::IsEffectWithImplementedMultiplier (uint32 effectId) const
Definition at line 9386 of file Spell.cpp.
References SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEAL_PCT, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_POWER_BURN, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, and SPELL_EFFECT_WEAPON_PERCENT_DAMAGE.
Referenced by HandleEffect().
IsExecutedCurrently()
bool Spell::IsExecutedCurrently () const inline
Definition at line 698 of file Spell.h.
References m_executedCurrently.
IsInterruptible()
bool Spell::IsInterruptible () const
Definition at line 8921 of file Spell.cpp.
References CanBeInterrupted(), SpellEntry::InterruptFlags, m_spellInfo, SpellEntry::PreventionType, SPELL_INTERRUPT_FLAG_COMBAT, and SPELL_PREVENTION_TYPE_SILENCE.
IsMeleeAttackResetSpell()
bool Spell::IsMeleeAttackResetSpell () const inline
Definition at line 691 of file Spell.h.
References SpellEntry::InterruptFlags, m_IsTriggeredSpell, m_spellInfo, and SPELL_INTERRUPT_FLAG_COMBAT.
Referenced by _handle_immediate_phase().
IsNeedSendToClient()
bool Spell::IsNeedSendToClient () const
Definition at line 8447 of file Spell.cpp.
References SpellEntry::HasAttribute(), IsChanneledSpell(), m_channelOnly, m_IsTriggeredSpell, m_spellInfo, m_triggeredByAuraSpell, SpellEntry::speed, SPELL_ATTR_EX7_ALWAYS_CAST_LOG, and SpellEntry::SpellVisual.
Referenced by SendSpellGo(), and SendSpellStart().
IsRangedAttackResetSpell()
bool Spell::IsRangedAttackResetSpell () const inline
Definition at line 692 of file Spell.h.
References SpellEntry::InterruptFlags, IsRangedSpell(), m_IsTriggeredSpell, m_spellInfo, and SPELL_INTERRUPT_FLAG_COMBAT.
IsRangedSpell()
bool Spell::IsRangedSpell () const inline
Definition at line 673 of file Spell.h.
References SpellEntry::HasAttribute(), m_spellInfo, and SPELL_ATTR_USES_RANGED_SLOT.
Referenced by finish(), GetSpellCastTime(), IsRangedAttackResetSpell(), and IsSpellRequiringAmmo().
IsSpellRequiringAmmo()
bool Spell::IsSpellRequiringAmmo () const inline
Definition at line 677 of file Spell.h.
References IsRangedSpell(), m_spellInfo, SpellEntry::speed, SpellEntry::SpellVisual, and sSpellVisualStore.
Referenced by SendSpellGo(), and SendSpellStart().
IsTriggeredByAura()
bool Spell::IsTriggeredByAura () const inline
Definition at line 707 of file Spell.h.
References m_triggeredByAuraSpell.
IsTriggeredSpellWithRedundantCastTime()
bool Spell::IsTriggeredSpellWithRedundantCastTime () const
Definition at line 8459 of file Spell.cpp.
References m_IsTriggeredSpell, m_spellInfo, SpellEntry::manaCost, and SpellEntry::ManaCostPercentage.
Referenced by GetSpellCastTime().
IsValidDeadOrAliveTarget()
bool Spell::IsValidDeadOrAliveTarget (Unit const * unit) const protected
Definition at line 1850 of file Spell.cpp.
References Unit::IsAlive(), IsAllowingDeadTarget(), IsDeathOnlySpell(), and m_spellInfo.
Referenced by IsAliveUnitPresentInTargetList().
OnAfterHit()
void Spell::OnAfterHit ()
Definition at line 9898 of file Spell.cpp.
References GetSpellScript().
Referenced by DoAllEffectOnTarget().
OnCast()
void Spell::OnCast ()
Definition at line 9886 of file Spell.cpp.
References GetSpellScript().
Referenced by cast().
OnCheckCast()
SpellCastResult Spell::OnCheckCast (bool strict)
Definition at line 9465 of file Spell.cpp.
References WorldObject::GetMap(), GetSpellScript(), SpellCastTargets::getUnitTarget(), SpellCastTargets::getUnitTargetGuid(), GetUsableHealthStoneItemType(), Unit::HasAura(), Creature::HasBeenHitBySpell(), SpellEntry::Id, Object::IsCreature(), Object::IsPlayer(), Unit::IsTaxiFlying(), ItemPrototype::ItemLimitCategory, m_caster, m_param1, m_spellInfo, m_targets, sObjectMgr, Map::SpawnedCountForEntry(), SPELL_CAST_OK, SPELL_FAILED_BAD_TARGETS, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_FIZZLE, SPELL_FAILED_NOT_HERE, SPELL_FAILED_ONLY_MOUNTED, and SPELL_FAILED_TOO_MANY_OF_ITEM.
Referenced by CheckCast().
OnCheckTarget() [1/2]
bool Spell::OnCheckTarget (GameObject * target, SpellEffectIndex eff) const
Definition at line 9591 of file Spell.cpp.
References GameObject::GetLootState(), GetSpellScript(), GO_ACTIVATED, SpellEntry::Id, and m_spellInfo.
Referenced by CheckScriptTargeting(), CheckTarget(), and FillTargetMap().
OnCheckTarget() [2/2]
bool Spell::OnCheckTarget (Unit * target, SpellEffectIndex eff) const
Definition at line 9607 of file Spell.cpp.
References Unit::AI(), Unit::CanReachWithMeleeAttack(), CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, DIST_CALC_COMBAT_REACH, DIST_CALC_NONE, EFFECT_INDEX_0, Unit::getClass(), WorldObject::GetDistance(), Object::GetEntry(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Unit::GetPowerType(), UnitAI::GetScriptData(), GetSpellScript(), ThreatManager::getThreatList(), Unit::getThreatManager(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Unit::GetVictim(), Unit::HasAura(), Object::HasFlag(), SpellEntry::Id, Player::IsInHighLiquid(), Unit::IsInWater(), WorldObject::IsWithinDist(), m_caster, m_spellInfo, m_targets, POWER_MANA, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
OnDestTarget()
void Spell::OnDestTarget ()
Definition at line 9585 of file Spell.cpp.
References GetSpellScript().
Referenced by FillTargetMap().
OnEffectExecute()
void Spell::OnEffectExecute (SpellEffectIndex effIndex)
Definition at line 9573 of file Spell.cpp.
References GetSpellScript().
Referenced by HandleEffect().
OnHit()
void Spell::OnHit (SpellMissInfo missInfo)
Definition at line 9892 of file Spell.cpp.
References GetSpellScript().
Referenced by DoAllEffectOnTarget(), and DoAllTargetlessEffects().
OnInit()
void Spell::OnInit ()
Definition at line 9422 of file Spell.cpp.
References GetSpellScript().
Referenced by Spell().
OnRadiusCalculate()
void Spell::OnRadiusCalculate (SpellEffectIndex effIndex, bool targetB, float & radius)
Definition at line 9579 of file Spell.cpp.
References GetSpellScript().
Referenced by GetSpellRangeAndRadius().
OnSuccessfulFinish()
void Spell::OnSuccessfulFinish ()
Definition at line 9434 of file Spell.cpp.
References GetSpellScript(), SpellEntry::Id, m_caster, m_scriptValue, m_spellInfo, Unit::RemoveAurasDueToSpell(), and Unit::RemoveAuraStack().
Referenced by finish().
OnSuccessfulStart()
void Spell::OnSuccessfulStart ()
Definition at line 9428 of file Spell.cpp.
References GetSpellScript().
Referenced by Prepare().
OnSummon() [1/2]
void Spell::OnSummon (Creature * summon)
Definition at line 9910 of file Spell.cpp.
References GetSpellScript().
OnSummon() [2/2]
void Spell::OnSummon (GameObject * summon)
Definition at line 9904 of file Spell.cpp.
References GetSpellScript().
Referenced by DoSummonTotem(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonType(), and EffectTransmitted().
PreCastCheck()
SpellCastResult Spell::PreCastCheck (Aura * triggeredByAura = nullptr) protected
Definition at line 3289 of file Spell.cpp.
References CheckCast(), Aura::GetHolder(), IsAutoRepeat(), m_triggerAutorepeat, SendChannelUpdate(), SpellAuraHolder::SetAuraDuration(), and SPELL_CAST_OK.
Referenced by SpellStart().
Prepare()
void Spell::Prepare () protected
Definition at line 3342 of file Spell.cpp.
References WorldObject::AddGCD(), Unit::AI(), AURA_INTERRUPT_FLAG_ACTION, BASE_ATTACK, cast(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellCastTime(), WorldObject::GetSpellModOwner(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Unit::hasOffhandWeaponForAttack(), IsAutoRepeat(), IsChanneledSpell(), Object::IsGameObject(), IsNextMeleeSwingSpell(), m_caster, m_castOrientation, m_castPositionX, m_castPositionY, m_castPositionZ, m_casttime, m_ignoreCastTime, m_ignoreConcurrentCasts, m_IsTriggeredSpell, m_notifyAI, m_spellInfo, m_spellState, m_targets, m_timer, m_triggerAutorepeat, m_trueCaster, OFF_ATTACK, UnitAI::OnSpellCastStateChange(), OnSuccessfulStart(), prepareDataForTriggerSystem(), Unit::RemoveAurasOnCast(), Unit::resetAttackTimer(), ReSetTimer(), SendSpellStart(), Unit::SetCurrentCastedSpell(), SPELL_ATTR_EX2_NOT_AN_ACTION, SPELL_ATTR_EX6_DOESNT_RESET_SWING_TIMER_IF_INSTANT, SPELL_ATTR_EX7_RESET_SWING_TIMER_AT_SPELL_START, and SPELL_STATE_CASTING.
Referenced by SpellStart().
prepareDataForTriggerSystem()
void Spell::prepareDataForTriggerSystem () protected
Definition at line 857 of file Spell.cpp.
References IsPositiveEffect(), m_canTrigger, m_CastItem, m_doNotProc, m_negativeEffectMask, m_spellInfo, MAX_EFFECT_INDEX, and SpellEntry::SpellFamilyFlags.
Referenced by Prepare().
PrepareMasksForProcSystem()
void Spell::PrepareMasksForProcSystem (uint8 effectMask, uint32 & procAttacker, uint32 & procVictim, WorldObject * caster, WorldObject * target) protected
Definition at line 879 of file Spell.cpp.
References BASE_ATTACK, SpellEntry::DmgClass, SpellEntry::HasAttribute(), SpellEntry::IsFitToFamilyMask(), IsNextMeleeSwingSpell(), IsPositiveEffectMask(), m_attackType, m_spellInfo, OFF_ATTACK, PROC_FLAG_DEAL_HARMFUL_ABILITY, PROC_FLAG_DEAL_HARMFUL_PERIODIC, PROC_FLAG_DEAL_HARMFUL_SPELL, PROC_FLAG_DEAL_HELPFUL_ABILITY, PROC_FLAG_DEAL_HELPFUL_SPELL, PROC_FLAG_DEAL_MELEE_ABILITY, PROC_FLAG_DEAL_MELEE_SWING, PROC_FLAG_DEAL_RANGED_ABILITY, PROC_FLAG_DEAL_RANGED_ATTACK, PROC_FLAG_MAIN_HAND_WEAPON_SWING, PROC_FLAG_OFF_HAND_WEAPON_SWING, PROC_FLAG_ON_TRAP_ACTIVATION, PROC_FLAG_TAKE_HARMFUL_ABILITY, PROC_FLAG_TAKE_HARMFUL_PERIODIC, PROC_FLAG_TAKE_HARMFUL_SPELL, PROC_FLAG_TAKE_HELPFUL_ABILITY, PROC_FLAG_TAKE_HELPFUL_SPELL, PROC_FLAG_TAKE_MELEE_ABILITY, PROC_FLAG_TAKE_MELEE_SWING, PROC_FLAG_TAKE_RANGED_ABILITY, PROC_FLAG_TAKE_RANGED_ATTACK, SPELL_ATTR_EX2_AUTO_REPEAT, SPELL_ATTR_EX3_SUPPRESS_CASTER_PROCS, SPELL_ATTR_EX3_TREAT_AS_PERIODIC, SPELL_ATTR_IS_ABILITY, SPELL_DAMAGE_CLASS_MELEE, SPELL_DAMAGE_CLASS_RANGED, SPELLFAMILY_HUNTER, and SpellEntry::SpellFamilyName.
Referenced by DoAllEffectOnTarget(), and DoAllTargetlessEffects().
ProcessAOECaps()
void Spell::ProcessAOECaps ()
Definition at line 3974 of file Spell.cpp.
References CalculateSpellEffectValue(), SpellEntry::Effect, SpellEntry::HasAttribute(), m_spellInfo, m_UniqueTargetInfo, MAX_EFFECT_INDEX, SPELL_ATTR_SS_AOE_CAP, and SPELL_EFFECT_SCHOOL_DAMAGE.
Referenced by handle_immediate().
ProcessDispelList()
void Spell::ProcessDispelList (std::list< std::pair< SpellAuraHolder *, uint32 > > & dispelList, std::list< std::pair< SpellAuraHolder *, uint32 > > & successList, std::list< uint32 > & failList)
Definition at line 6874 of file SpellEffects.cpp.
References damage, SpellAuraHolder::GetCaster(), SpellAuraHolder::GetCasterGuid(), SpellAuraHolder::GetId(), Player::GetSpellModOwner(), SpellAuraHolder::GetSpellProto(), SpellEntry::Id, roll_chance_i(), SPELL_AURA_MOD_DISPEL_RESIST, SPELLMOD_RESIST_DISPEL_CHANCE, and urand().
Referenced by EffectDispel(), EffectDispelMechanic(), and EffectStealBeneficialBuff().
ProcReflectProcs()
void Spell::ProcReflectProcs (TargetInfo & targetInfo)
Definition at line 9146 of file Spell.cpp.
References BASE_ATTACK, Object::GetObjectGuid(), ObjectAccessor::GetUnit(), m_caster, m_spellInfo, m_trueCaster, PROC_EX_REFLECT, PROC_FLAG_NONE, PROC_FLAG_TAKE_HARMFUL_SPELL, Unit::ProcDamageAndSpell(), Spell::TargetInfo::reflectResult, SPELL_MISS_REFLECT, and Spell::TargetInfo::targetGUID.
Referenced by AddUnitTarget(), and handle_delayed().
ProcSpellAuraTriggers()
void Spell::ProcSpellAuraTriggers () protected
Definition at line 8821 of file Spell.cpp.
References WorldObject::CalculateSpellEffectValue(), CanExecuteTriggersOnHit(), SpellEntry::EffectTriggerSpell, Unit::GetAurasByType(), Object::GetObjectGuid(), GetSpellSpeed(), ObjectAccessor::GetUnit(), Unit::IsAlive(), SQLStorage::LookupEntry(), m_caster, m_spellInfo, m_UniqueTargetInfo, roll_chance_i(), SetOverridenSpeed(), SpellCastTargets::setUnitTarget(), Spell(), SPELL_AURA_ADD_TARGET_TRIGGER, SPELL_MISS_NONE, SpellStart(), sSpellTemplate, and TRIGGERED_OLD_TRIGGERED.
Referenced by _handle_immediate_phase().
RecalculateDelayMomentForDest()
void Spell::RecalculateDelayMomentForDest ()
Definition at line 1290 of file Spell.cpp.
References CalculateDelayMomentForDst(), GetDelayStart(), m_delayMoment, WorldObject::m_events, m_spellEvent, m_trueCaster, and EventProcessor::ModifyEventTime().
Referenced by WorldSession::HandleOnMissileTrajectoryCollision().
RegisterAuraProc()
void Spell::RegisterAuraProc (Aura * aura)
Definition at line 8926 of file Spell.cpp.
References m_procOnceHolder.
Referenced by Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::ProcDamageAndSpellFor().
ResetEffectDamageAndHeal()
void Spell::ResetEffectDamageAndHeal () protected
Definition at line 8804 of file Spell.cpp.
References m_damage, and m_healing.
Referenced by DoAllEffectOnTarget(), and DoSpellHitOnUnit().
ReSetTimer()
void Spell::ReSetTimer () inline
Definition at line 672 of file Spell.h.
References m_casttime, and m_timer.
Referenced by Prepare().
SelectMountByAreaAndSkill()
void Spell::SelectMountByAreaAndSkill (Unit * target, SpellEntry const * parentSpell, uint32 spellId75, uint32 spellId150, uint32 spellId225, uint32 spellId300, uint32 spellIdSpecial) static
Definition at line 8859 of file Spell.cpp.
References SpellEntry::CalculateSimpleValue(), Unit::CastSpell(), SpellEntry::EffectApplyAuraName, Unit::GetBeneficiaryPlayer(), Object::GetGuidStr(), WorldObject::GetMapId(), WorldObject::GetZoneAndAreaId(), SpellEntry::HasAttribute(), Object::IsPlayer(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, PLAYERSPELL_REMOVED, Unit::RemoveSpellsCausingAura(), SKILL_RIDING, sLog, SPELL_ATTR_EX7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT, SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED, SPELL_AURA_MOUNTED, SPELL_CAST_OK, sSpellMgr, sSpellTemplate, TRIGGERED_NONE, and TRIGGERED_OLD_TRIGGERED.
Referenced by EffectScriptEffect(), and Aura::HandleAuraDummy().
SendCastResult() [1/2]
void Spell::SendCastResult (Player const * caster, SpellEntry const * spellInfo, uint8 cast_count, SpellCastResult result, bool isPetCastResult = false, uint32 param1 = 0, uint32 param2 = 0) static
Definition at line 4392 of file Spell.cpp.
References SpellEntry::EquippedItemClass, SpellEntry::EquippedItemSubClassMask, Player::GetSession(), SpellEntry::HasAttribute(), SpellEntry::Id, IsPassiveSpell(), WorldObject::IsSpellOnPermanentCooldown(), SpellEntry::RequiresSpellFocus, WorldSession::SendPacket(), SMSG_CAST_RESULT, SMSG_PET_CAST_FAILED, SPELL_ATTR_COOLDOWN_ON_EVENT, SPELL_ATTR_EX2_DO_NOT_REPORT_SPELL_FAILURE, SPELL_CAST_OK, SPELL_FAILED_CUSTOM_ERROR, SPELL_FAILED_DONT_REPORT, SPELL_FAILED_EQUIPPED_ITEM_CLASS, SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND, SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND, SPELL_FAILED_FISHING_TOO_LOW, SPELL_FAILED_MIN_SKILL, SPELL_FAILED_NEED_EXOTIC_AMMO, SPELL_FAILED_NEED_MORE_ITEMS, SPELL_FAILED_NOT_READY, SPELL_FAILED_PREVENTED_BY_MECHANIC, SPELL_FAILED_REAGENTS, SPELL_FAILED_REQUIRES_AREA, SPELL_FAILED_REQUIRES_SPELL_FOCUS, SPELL_FAILED_TOO_MANY_OF_ITEM, SPELL_FAILED_TOTEM_CATEGORY, SPELL_FAILED_TOTEMS, SpellEntry::Totem, and SpellEntry::TotemCategory.
Referenced by PlayerbotAI::_HandleCommandCraft(), cancel(), cast(), EffectApplyGlyph(), EffectDuel(), EffectDummy(), EffectTaunt(), EffectTransmitted(), FillTargetMap(), FillUnitTargets(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleUseItemOpcode(), ItemUse_item_arcane_charges(), ItemUse_item_gor_dreks_ointment(), ItemUse_item_orb_of_draconic_energy(), ItemUse_item_petrov_cluster_bombs(), RighteousDefense::OnEffectExecute(), SendCastResult(), SetTargetMap(), SpellStart(), and StopCast().
SendCastResult() [2/2]
void Spell::SendCastResult (SpellCastResult result) const
Definition at line 4356 of file Spell.cpp.
References Unit::GetControllingPlayer(), Player::GetSession(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), Object::IsPlayer(), m_cast_count, m_caster, m_param1, m_param2, m_petCast, m_spellInfo, m_spellScript, m_targets, m_triggeredByAuraSpell, m_trueCaster, SpellScript::OnSpellCastResultOverride(), WorldSession::PlayerLoading(), SendCastResult(), and SPELL_ATTR_EX7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET.
SendChannelStart()
void Spell::SendChannelStart (uint32 duration)
Definition at line 4917 of file Spell.cpp.
References Unit::addUnitState(), Unit::AI(), DIMINISHING_LEVEL_1, DIMINISHING_LEVEL_IMMUNE, DIMINISHING_NONE, SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, SpellEntry::EffectRadiusIndex, Unit::GetDynObject(), Map::GetGameObject(), WorldObject::GetMap(), Object::GetObjectGuid(), Object::GetPackGUID(), GetSpellRadius(), ObjectAccessor::GetUnit(), SpellCastTargets::getUnitTarget(), SpellEntry::HasAttribute(), SpellEntry::Id, WorldPacket::Initialize(), m_caster, m_CastItem, m_maxRange, m_spellInfo, m_targets, m_timer, m_UniqueGOTargetInfo, m_UniqueTargetInfo, MSG_CHANNEL_START, UnitAI::OnChannelStateChange(), ByteBuffer::put(), WorldObject::SendMessageToSet(), Unit::SetChannelObject(), Object::SetUInt32Value(), SMSG_SPELL_UPDATE_CHAIN_TARGETS, SPELL_ATTR_EX_IS_CHANNELED, SPELL_AURA_BIND_SIGHT, SPELL_AURA_MOD_POSSESS, SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_MISS_NONE, sSpellRadiusStore, UNIT_FIELD_CHANNEL_SPELL, UNIT_STAT_CHANNELING, and ByteBuffer::wpos().
Referenced by _handle_immediate_phase().
SendChannelUpdate()
void Spell::SendChannelUpdate (uint32 time, uint32 lastTick = 0) const
Definition at line 4865 of file Spell.cpp.
References Unit::AI(), AURA_REMOVE_BY_CANCEL, AURA_REMOVE_BY_EXPIRE, Unit::clearUnitState(), Unit::GetChannelObject(), Object::GetObjectGuid(), Object::GetPackGUID(), Unit::GetSpellAuraHolder(), Object::GetUInt32Value(), Unit::HasChannelObject(), SpellEntry::Id, m_caster, m_spellInfo, m_timer, MSG_CHANNEL_UPDATE, UnitAI::OnChannelStateChange(), Unit::RemoveAurasByCasterSpell(), Unit::RemoveAuraStack(), WorldObject::SendMessageToSet(), Unit::SetChannelObject(), Object::SetUInt32Value(), SpellEntry::StackAmount, UNIT_FIELD_CHANNEL_SPELL, and UNIT_STAT_CHANNELING.
Referenced by cancel(), DelayedChannel(), EffectTransmitted(), Unit::FinishSpell(), PreCastCheck(), and update().
SendInterrupted()
void Spell::SendInterrupted (SpellCastResult result) const
Definition at line 4848 of file Spell.cpp.
References Object::GetPackGUID(), SpellEntry::Id, WorldPacket::Initialize(), m_cast_count, m_spellInfo, m_trueCaster, WorldObject::SendMessageToSet(), SMSG_SPELL_FAILED_OTHER, and SMSG_SPELL_FAILURE.
Referenced by cancel(), and StopCast().
SendLoot()
void Spell::SendLoot (ObjectGuid guid, LootType loottype, LockType lockType) protected
Definition at line 5713 of file SpellEffects.cpp.
References GAMEOBJECT_TYPE_BUTTON, GAMEOBJECT_TYPE_CHEST, GAMEOBJECT_TYPE_DOOR, GAMEOBJECT_TYPE_FLAGSTAND, GAMEOBJECT_TYPE_GOOBER, GAMEOBJECT_TYPE_QUESTGIVER, GAMEOBJECT_TYPE_SPELL_FOCUS, GAMEOBJECT_TYPE_TRAP, gameObjTarget, Object::GetEntry(), GameObject::GetGoType(), ObjectGuid::GetHigh(), ObjectGuid::GetString(), Object::GetTypeId(), GO_ACTIVATED, HIGHGUID_GAMEOBJECT, HIGHGUID_ITEM, SpellEntry::Id, itemTarget, LOCKTYPE_DISARM_TRAP, LOCKTYPE_NONE, LOCKTYPE_OPEN_ATTACKING, m_caster, Object::m_loot, m_spellInfo, GameObject::SetLootState(), Loot::ShowContentTo(), sLog, TakeCastItem(), TYPEID_PLAYER, and GameObject::Use().
Referenced by EffectOpenLock().
SendSpellCooldown()
void Spell::SendSpellCooldown ()
Definition at line 4010 of file Spell.cpp.
References WorldObject::AddCooldown(), SpellEntry::Category, Object::GetEntry(), Item::GetProto(), SpellEntry::HasAttribute(), SpellEntry::Id, Object::IsPlayer(), Item::IsPotion(), m_caster, m_CastItem, m_channelOnly, m_spellInfo, m_trueCaster, Player::SetCooldownEventOnLeaveCombatSpellId(), Player::SetLastPotionId(), SPELL_ATTR_COOLDOWN_ON_EVENT, SPELL_ATTR_PASSIVE, SPELL_CATEGORY_FLAG_EVENT_ON_LEAVE_COMBAT, ItemPrototype::Spells, and sSpellCategoryStore.
Referenced by cast().
SendSpellGo()
void Spell::SendSpellGo ()
Definition at line 4545 of file Spell.cpp.
References CAST_FLAG_ADJUST_MISSILE, CAST_FLAG_AMMO, CAST_FLAG_HIDDEN_COMBATLOG, CAST_FLAG_NO_GCD, CAST_FLAG_PREDICTED_POWER, CAST_FLAG_PREDICTED_RUNES, CAST_FLAG_UNKNOWN7, CAST_FLAG_UNKNOWN9, CAST_FLAG_VISUAL_CHAIN, CLASS_DEATH_KNIGHT, DEBUG_FILTER_LOG, Unit::getClass(), Map::GetCurrentMSTime(), WorldObject::GetDestLocCounter(), SpellCastTargets::getDestTransportGuid(), SpellCastTargets::getElevation(), WorldObject::GetMap(), GetNewRuneState(), Object::GetObjectGuid(), GetOldRuneState(), Object::GetPackGUID(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Unit::GetPower(), SpellCastTargets::getSpeed(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), SpellEntry::HasAttribute(), SpellEntry::Id, WorldObject::IncrementDestLocCounter(), Object::IsGameObject(), IsNeedSendToClient(), Object::IsPlayer(), IsSpellRequiringAmmo(), LOG_FILTER_SPELL_CAST, m_cast_count, m_caster, m_CastItem, m_delayMoment, SpellCastTargets::m_destPos, m_forwardedCastItemGuid, m_hideInCombatLog, m_powerCost, m_spellInfo, SpellCastTargets::m_srcPos, SpellCastTargets::m_targetMask, m_targets, m_triggeredByAuraSpell, m_trueCaster, MAX_RUNES, POWER_HEALTH, SpellEntry::powerType, SpellEntry::runeCostID, WorldObject::SendMessageToSet(), SMSG_NOTIFY_DEST_LOC_SPELL_CAST, SMSG_SPELL_GO, SPELL_ATTR_EX2_RETAIN_ITEM_CAST, SpellEntry::StartRecoveryTime, MaNGOS::SpellMessageDestLocDeliverer::StopAccumulating(), TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_VISUAL_CHAIN, Cell::VisitAllObjects(), WriteAmmoToPacket(), ObjectGuid::WriteAsPacked(), WriteSpellGoTargets(), Position::x, Position::y, and Position::z.
Referenced by cast().
SendSpellStart()
void Spell::SendSpellStart () const
Definition at line 4481 of file Spell.cpp.
References CAST_FLAG_ADJUST_MISSILE, CAST_FLAG_AMMO, CAST_FLAG_HIDDEN_COMBATLOG, CAST_FLAG_IMMUNITY, CAST_FLAG_NO_GCD, CAST_FLAG_PERSISTENT_AA, CAST_FLAG_UNKNOWN2, DEBUG_FILTER_LOG, Object::GetPackGUID(), SpellCastTargets::getSpeed(), HasPersistentAuraEffect(), SpellEntry::Id, Object::IsGameObject(), IsNeedSendToClient(), IsSpellRequiringAmmo(), Object::IsUnit(), LOG_FILTER_SPELL_CAST, m_cast_count, m_caster, m_CastItem, m_hideInCombatLog, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_timer, m_triggeredByAuraSpell, m_trueCaster, POWER_RUNE, SpellEntry::powerType, SpellEntry::runeCostID, WorldObject::SendMessageToSet(), SMSG_SPELL_START, TARGET_FLAG_DEST_LOCATION, WriteAmmoToPacket(), and ObjectGuid::WriteAsPacked().
Referenced by Prepare().
SetAutoRepeat()
void Spell::SetAutoRepeat (bool rep) inline
Definition at line 671 of file Spell.h.
References m_autoRepeat.
SetCastItem()
void Spell::SetCastItem (Item * item)
Definition at line 4003 of file Spell.cpp.
References m_CastItem, and m_itemCastSpell.
Referenced by Unit::CastCustomSpell(), Player::CastItemUseSpell(), GameObject::CastSpell(), Unit::CastSpell(), and WorldSession::HandleAcceptTradeOpcode().
SetChainTargetsCount()
void Spell::SetChainTargetsCount (SpellEffectIndex effIdx, uint32 newValue) inline
Definition at line 867 of file Spell.h.
References m_chainTargetCount.
Referenced by SunderArmor::OnInit().
SetDamage()
void Spell::SetDamage (uint32 newDamage) inline
Definition at line 859 of file Spell.h.
References damage.
Referenced by spell_launch_harpoon::OnEffectExecute(), MoltenFuryFlamebringer::OnEffectExecute(), spell_incinerating_blast::OnEffectExecute(), spell_pulsing_shockwave::OnEffectExecute(), DiveBomb::OnEffectExecute(), SplitDamage::OnEffectExecute(), ExplodeGhoulCorpseExplosion::OnEffectExecute(), SpiritOfRedemptionHeal::OnEffectExecute(), PrayerOfMending::OnEffectExecute(), LavaLash::OnEffectExecute(), ShadowBite::OnEffectExecute(), WarriorDevastate::OnEffectExecute(), HeroicStrike::OnEffectExecute(), Iceblast::OnEffectExecute(), AlarEmberBlast::OnEffectExecute(), JudgementsOfTheWiseEnergize::OnEffectExecute(), and VictoryRush::OnEffectExecute().
SetDelayStart()
void Spell::SetDelayStart (uint64 m_time) inline
Definition at line 700 of file Spell.h.
References m_delayStart.
Referenced by cast(), SpellEvent::Execute(), and update().
SetEffectChance()
void Spell::SetEffectChance (int32 triggerChance, SpellEffectIndex effIdx) inline
Definition at line 753 of file Spell.h.
References m_effectTriggerChance.
Referenced by CounterCharge::OnCast(), and HarvestSilithidEgg::OnInit().
SetEventTarget()
void Spell::SetEventTarget (WorldObject * object) inline
Definition at line 879 of file Spell.h.
References m_eventTarget.
Referenced by FlagAuraBg::OnEffectExecute().
SetExecutedCurrently()
void Spell::SetExecutedCurrently (bool yes) inline
Definition at line 697 of file Spell.h.
References m_executedCurrently.
Referenced by cast(), and StopCast().
SetFakeCaster()
void Spell::SetFakeCaster (Unit * caster) inline
Definition at line 888 of file Spell.h.
References m_caster.
Referenced by GameObject::CastSpell().
SetFilteringScheme()
void Spell::SetFilteringScheme (SpellEffectIndex effIdx, bool targetB, SpellTargetFilterScheme scheme) inline
Definition at line 870 of file Spell.h.
References m_filteringScheme.
Referenced by NetherBeam::OnInit(), TriggerStrafe::OnInit(), HatefulStrikePrimer::OnInit(), ForcedObedience::OnInit(), WOTAOldSearch::OnInit(), FelInfusion::OnInit(), Replenishment::OnInit(), WildGrowth::OnInit(), DivineHymn::OnInit(), HymnOfHope::OnInit(), CircleOfHealing::OnInit(), AncestralAwakeningSearch::OnInit(), and SpellReflectionRaid::OnInit().
SetForwardedCastItem()
void Spell::SetForwardedCastItem (ObjectGuid guid) inline
Definition at line 740 of file Spell.h.
References m_forwardedCastItemGuid.
Referenced by Aura::CastTriggeredSpell().
SetIgnoreOwnerLevel()
void Spell::SetIgnoreOwnerLevel (bool state) inline
Definition at line 899 of file Spell.h.
References m_ignoreOwnerLevel.
SetIgnoreRoot()
void Spell::SetIgnoreRoot (bool state) inline
Definition at line 898 of file Spell.h.
References m_ignoreRoot.
Referenced by Intervene::OnInit().
SetJumpRadius()
void Spell::SetJumpRadius (float newValue) inline
Definition at line 868 of file Spell.h.
References m_jumpRadius.
SetMaxAffectedTargets()
void Spell::SetMaxAffectedTargets (uint32 newValue) inline
Definition at line 866 of file Spell.h.
References m_affectedTargetCount.
Referenced by SummonMoleMachineTargetPicker::OnInit(), Enfeeble::OnInit(), BlinkArcaneAnomaly::OnInit(), FlameSear::OnInit(), TriggerStrafe::OnInit(), EntropiusDarkEnergy::OnInit(), HatchEggs::OnInit(), ConflagrationTargeting::OnInit(), LightningWhirl::OnInit(), LightningWhirlHeroic::OnInit(), SuppressionBlast::OnInit(), InsidiousWhisper::OnInit(), StalkerLevitate::OnInit(), SomeoneGrabMe::OnInit(), WOTAOldSearch::OnInit(), FelInfusion::OnInit(), RaiseDead::OnInit(), Replenishment::OnInit(), DawnbladeAttack::OnInit(), WildGrowth::OnInit(), DivineStorm::OnInit(), DivineStormHeal::OnInit(), DivineHymn::OnInit(), HymnOfHope::OnInit(), CircleOfHealing::OnInit(), AncestralAwakeningSearch::OnInit(), and SpellReflectionRaid::OnInit().
SetOverridenSpeed()
void Spell::SetOverridenSpeed (float newSpeed)
Definition at line 9416 of file Spell.cpp.
References m_overridenSpeed, and m_overrideSpeed.
Referenced by ProcSpellAuraTriggers().
SetParam1()
void Spell::SetParam1 (uint32 param1) inline
Definition at line 893 of file Spell.h.
References m_param1.
Referenced by DemonicCircleTeleport::OnCheckCast().
SetParam2()
void Spell::SetParam2 (uint32 param2) inline
Definition at line 894 of file Spell.h.
References m_param2.
SetPowerCost()
void Spell::SetPowerCost (uint32 powerCost) inline
Definition at line 873 of file Spell.h.
References m_powerCost.
Referenced by LifeTap::OnCheckCast().
SetReferencedFromCurrent()
void Spell::SetReferencedFromCurrent (bool yes) inline
Definition at line 696 of file Spell.h.
References m_referencedFromCurrentSpell.
Referenced by Unit::InterruptSpell(), and Unit::SetCurrentCastedSpell().
SetScriptValue()
void Spell::SetScriptValue (uint64 value) inline
Definition at line 837 of file Spell.h.
References m_scriptValue.
Referenced by Unit::CastSpell(), DivineStorm::OnAfterHit(), KillCreditDrakkariSkullcrusher::OnCast(), PolarityShift::OnEffectExecute(), WateryGrave::OnEffectExecute(), CorpseExplosionDK::OnEffectExecute(), spell_gravity_lapse_mgt::OnEffectExecute(), InciteChaos::OnEffectExecute(), DragonmawKnockdownTheAggroCheck::OnEffectExecute(), AllFiresOutTest::OnEffectExecute(), BucketLands::OnEffectExecute(), and LifeTap::OnInit().
SetSpellStartTravelling()
void Spell::SetSpellStartTravelling (uint32 time) inline
Definition at line 702 of file Spell.h.
References m_travellingStart.
Referenced by cast(), and update().
setState()
void Spell::setState (uint32 state) inline
Definition at line 579 of file Spell.h.
References m_spellState.
SetTargetMap()
void Spell::SetTargetMap (SpellEffectIndex effIndex, uint32 targetMode, bool targetB, TempTargetingData & targetingData) protected
Definition at line 1912 of file Spell.cpp.
References AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, WorldObject::CanAssistSpell(), Unit::CanAssistSpell(), Spell::TempTargetingData::chainTargetCount, CheckAndAddMagnetTarget(), CheckScriptTargeting(), CheckSpellScriptTargets(), Spell::TempTargetingData::data, DIST_CALC_COMBAT_REACH, SpellEntry::Effect, SpellEntry::EffectRadiusIndex, FillAreaTargets(), FillRaidOrPartyTargets(), ObjectAccessor::FindPlayer(), finish(), SQLMultiStorage::SQLMSIteratorBounds< T >::first, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetAffectiveCasterObject(), WorldObject::GetAngle(), Unit::GetBeneficiaryPlayer(), SQLMultiStorage::getBounds(), GetCastingObject(), GetChainJumpRange(), Unit::GetChannelObject(), Unit::GetCharm(), Unit::GetCharmer(), Unit::getClass(), WorldObject::GetClosePoint(), GetCone(), Unit::GetControllingPlayer(), SpellCastTargets::getDestination(), WorldObject::GetDistance(), WorldObject::GetFirstCollisionPosition(), Group::GetFirstMember(), WorldObject::GetFirstRandomAngleCollisionPosition(), SpellCastTargets::getGOTarget(), Player::GetGroup(), Object::GetGuidStr(), Map::GetHeightInRange(), Map::GetHitPosition(), SpellCastTargets::getItemTarget(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMaster(), WorldObject::GetNearPoint2d(), WorldObject::GetObjectBoundingRadius(), Unit::GetObjectBoundingRadius(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Unit::GetOwner(), VehicleInfo::GetPassenger(), Unit::GetPet(), Map::GetPet(), WorldObject::GetPhaseMask(), WorldObject::GetPosition(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellCastTargets::getSource(), GetSpellMaxRange(), GetSpellMinRange(), GetSpellRadius(), GetSpellRangeAndRadius(), Player::GetSubGroup(), Unit::GetTarget(), WorldObject::GetTerrain(), Map::GetTerrain(), WorldObject::GetTransport(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Unit::GetVehicleInfo(), TerrainInfo::GetWaterLevel(), SpellEntry::HasAttribute(), WorldObject::HasInArc(), MovementInfo::HasMovementFlag(), SpellEntry::Id, WorldObject::IsBoarded(), Player::IsInDuelWith(), TerrainInfo::IsInWater(), Group::IsMember(), TransportInfo::IsOnVehicle(), Object::IsPlayer(), IsPositiveSpell(), Unit::IsPvP(), Unit::IsVehicle(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOS(), GridMapLiquidData::level, m_affectedTargetCount, m_caster, SpellCastTargets::m_destPos, m_jumpRadius, SpellCastTargets::m_mapId, WorldObject::m_movementInfo, m_originalCaster, M_PI_F, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, MINI_PET, MOVEFLAG_FALLING, WorldObject::MovePositionToFirstCollision(), GroupReference::next(), Position::o, PUSH_CONE, PUSH_DEST_CENTER, PUSH_SELF_CENTER, PUSH_SRC_CENTER, PUSH_TARGET_CENTER, rand_norm_f(), SpellEntry::rangeIndex, Unit::RemoveAurasWithInterruptFlags(), SQLMultiStorage::SQLMSIteratorBounds< T >::second, SendCastResult(), SpellCastTargets::setDestination(), SpellCastTargets::setSource(), sLog, SPELL_ATTR_EX2_CHAIN_FROM_CASTER, SPELL_ATTR_EX5_IMPLIED_TARGETING, SPELL_ATTR_EX5_MELEE_CHAIN_TARGETING, SPELL_ATTR_EX6_IGNORE_PHASE_SHIFT, SPELL_ATTR_EX_EXCLUDE_CASTER, SPELL_CAST_OK, SPELL_EFFECT_BIND, SPELL_EFFECT_TELEPORT_UNITS, SPELL_EFFECT_WMO_CHANGE, SPELL_EFFECT_WMO_DAMAGE, SPELL_EFFECT_WMO_REPAIR, SPELL_FAILED_LINE_OF_SIGHT, SPELL_FAILED_NOT_FISHABLE, SPELL_TARGET_TYPE_GAMEOBJECT, SPELL_TARGETS_ALL, SPELL_TARGETS_AOE_ATTACKABLE, SPELL_TARGETS_ASSISTABLE, SPELL_TARGETS_CHAIN_ATTACKABLE, sSpellMgr, sSpellRadiusStore, sSpellRangeStore, sSpellScriptTargetStorage, TARGET_CORPSE_ENEMY_NEAR_CASTER, TARGET_ENUM_GAMEOBJECTS_IN_CONE, TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_104, TARGET_ENUM_UNITS_ENEMY_IN_CONE_24, TARGET_ENUM_UNITS_ENEMY_IN_CONE_54, TARGET_ENUM_UNITS_ENEMY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_FRIEND_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_FRIEND_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_FRIEND_IN_CONE, TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_SCRIPT_IN_CONE_110, TARGET_ENUM_UNITS_SCRIPT_IN_CONE_60, TARGET_FLAG_DEST_LOCATION, TARGET_FLAG_SOURCE_LOCATION, TARGET_GAMEOBJECT, TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER, TARGET_LOCATION_CASTER_BACK, TARGET_LOCATION_CASTER_BACK_LEFT, TARGET_LOCATION_CASTER_BACK_RIGHT, TARGET_LOCATION_CASTER_DEST, TARGET_LOCATION_CASTER_FISHING_SPOT, TARGET_LOCATION_CASTER_FRONT, TARGET_LOCATION_CASTER_FRONT_LEAP, TARGET_LOCATION_CASTER_FRONT_LEFT, TARGET_LOCATION_CASTER_FRONT_RIGHT, TARGET_LOCATION_CASTER_HOME_BIND, TARGET_LOCATION_CASTER_LEFT, TARGET_LOCATION_CASTER_RANDOM_CIRCUMFERENCE, TARGET_LOCATION_CASTER_RANDOM_SIDE, TARGET_LOCATION_CASTER_RIGHT, TARGET_LOCATION_CASTER_SRC, TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_LOCATION_CHANNEL_TARGET_DEST, TARGET_LOCATION_CURRENT_REFERENCE, TARGET_LOCATION_DATABASE, TARGET_LOCATION_EAST, TARGET_LOCATION_NE, TARGET_LOCATION_NORTH, TARGET_LOCATION_NW, TARGET_LOCATION_RANDOM_CIRCUMFERENCE, TARGET_LOCATION_RANDOM_SIDE, TARGET_LOCATION_SCRIPT_NEAR_CASTER, TARGET_LOCATION_SE, TARGET_LOCATION_SOUTH, TARGET_LOCATION_SW, TARGET_LOCATION_TRAJECTORY, TARGET_LOCATION_UNIT_BACK, TARGET_LOCATION_UNIT_BACK_LEFT, TARGET_LOCATION_UNIT_BACK_RIGHT, TARGET_LOCATION_UNIT_FRONT, TARGET_LOCATION_UNIT_FRONT_LEFT, TARGET_LOCATION_UNIT_FRONT_RIGHT, TARGET_LOCATION_UNIT_LEFT, TARGET_LOCATION_UNIT_MINION_POSITION, TARGET_LOCATION_UNIT_POSITION, TARGET_LOCATION_UNIT_RANDOM_CIRCUMFERENCE, TARGET_LOCATION_UNIT_RANDOM_SIDE, TARGET_LOCATION_UNIT_RIGHT, TARGET_LOCATION_WEST, TARGET_LOCKED, TARGET_UNIT, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_COMPANION, TARGET_UNIT_CASTER_DRIVER, TARGET_UNIT_CASTER_MASTER, TARGET_UNIT_CASTER_PASSENGER_0, TARGET_UNIT_CASTER_PASSENGER_1, TARGET_UNIT_CASTER_PASSENGER_2, TARGET_UNIT_CASTER_PASSENGER_3, TARGET_UNIT_CASTER_PASSENGER_4, TARGET_UNIT_CASTER_PASSENGER_5, TARGET_UNIT_CASTER_PASSENGER_6, TARGET_UNIT_CASTER_PASSENGER_7, TARGET_UNIT_CASTER_PET, TARGET_UNIT_CASTER_SUMMONER, TARGET_UNIT_CASTER_VEHICLE, TARGET_UNIT_CHANNEL_TARGET, TARGET_UNIT_ENEMY, TARGET_UNIT_ENEMY_NEAR_CASTER, TARGET_UNIT_FRIEND, TARGET_UNIT_FRIEND_AND_PARTY, TARGET_UNIT_FRIEND_CHAIN_HEAL, TARGET_UNIT_FRIEND_NEAR_CASTER, TARGET_UNIT_NEAR_CASTER, TARGET_UNIT_PARTY, TARGET_UNIT_RAID, TARGET_UNIT_RAID_AND_CLASS, TARGET_UNIT_SCRIPT_NEAR_CASTER, Spell::TempTargetData::tempItemList, Spell::TempTargetData::tmpGOList, Spell::TempTargetData::tmpUnitList, TYPEID_CORPSE, TYPEID_GAMEOBJECT, TYPEID_PLAYER, TYPEID_UNIT, unitTarget, Player::UpdatePvP(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), Position::x, Position::y, and Position::z.
Referenced by FillTargetMap().
SetTotalTargetValueModifier()
void Spell::SetTotalTargetValueModifier (float modifier)
Definition at line 9924 of file Spell.cpp.
References m_damage.
SpellStart()
SpellCastResult Spell::SpellStart (SpellCastTargets const * targets, Aura * triggeredByAura = nullptr)
Definition at line 3305 of file Spell.cpp.
References EventProcessor::AddEvent(), EventProcessor::CalculateTime(), finish(), Aura::GetSpellProto(), Object::IsGameObject(), Unit::IsNonMeleeSpellCasted(), m_cast_count, m_caster, WorldObject::m_events, m_ignoreConcurrentCasts, m_spellEvent, m_spellState, m_targets, m_triggeredByAuraSpell, m_trueCaster, PreCastCheck(), Prepare(), SendCastResult(), SPELL_CAST_OK, SPELL_FAILED_SPELL_IN_PROGRESS, and SPELL_STATE_TARGETING.
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandProcess(), Unit::_UpdateAutoRepeatSpell(), Unit::CastCustomSpell(), Player::CastItemUseSpell(), Player::CastQueuedSpell(), GameObject::CastSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), CastTriggerSpells(), EffectEnchantItemTmp(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), ProcSpellAuraTriggers(), PetAI::UpdateAI(), PlayerbotAI::UpdateAI(), and GameObject::Use().
StopCast()
void Spell::StopCast (SpellCastResult castResult)
Definition at line 9407 of file Spell.cpp.
References WorldObject::DecreaseCastCounter(), finish(), m_trueCaster, SendCastResult(), SendInterrupted(), and SetExecutedCurrently().
Referenced by cast().
TakeAmmo()
void Spell::TakeAmmo () const
Definition at line 5223 of file Spell.cpp.
References Player::DestroyItemCount(), Player::DurabilityPointLossForEquipSlot(), EQUIPMENT_SLOT_RANGED, Unit::GetAurasByType(), Item::GetMaxStackCount(), Item::GetProto(), Object::GetUInt32Value(), Player::GetWeaponForAttack(), ItemPrototype::InventoryType, INVTYPE_THROWN, Object::IsPlayer(), ITEM_SUBCLASS_WEAPON_WAND, m_attackType, m_spellInfo, m_trueCaster, PLAYER_AMMO_ID, RANGED_ATTACK, SPELL_AURA_ABILITY_CONSUME_NO_AMMO, and ItemPrototype::SubClass.
Referenced by cast().
TakeCastItem()
void Spell::TakeCastItem ()
Definition at line 5027 of file Spell.cpp.
References ClearCastItem(), Object::GetGuidStr(), Item::GetProto(), Item::GetSpellCharges(), Object::IsPlayer(), IsSpellHaveEffect(), ITEM_CHANGED, m_caster, m_CastItem, m_IsTriggeredSpell, m_spellInfo, SpellCastTargets::m_targetMask, m_targets, m_trueCaster, MAX_ITEM_PROTO_SPELLS, Item::SetSpellCharges(), Item::SetState(), Item::SetUsedInSpell(), sLog, SPELL_EFFECT_SUMMON_CHANGE_ITEM, _Spell::SpellCharges, _Spell::SpellId, ItemPrototype::Spells, ItemPrototype::Stackable, and TARGET_FLAG_TRADE_ITEM.
Referenced by _handle_immediate_phase(), and SendLoot().
TakePower()
void Spell::TakePower ()
Definition at line 5092 of file Spell.cpp.
References CheckOrTakeRunePower(), SpellEntry::HasAttribute(), m_caster, m_CastItem, m_powerCost, m_spellInfo, m_triggeredByAuraSpell, MAX_POWERS, Unit::ModifyHealth(), Unit::ModifyPower(), POWER_HEALTH, POWER_MANA, POWER_RUNE, SpellEntry::powerType, Unit::SetLastManaUse(), sLog, SPELL_ATTR_EX2_DONT_BLOCK_MANA_REGEN, and SPELL_ATTR_EX6_DO_NOT_CONSUME_RESOURCES.
Referenced by cast().
TakeReagents()
void Spell::TakeReagents ()
Definition at line 5261 of file Spell.cpp.
References Player::CanNoReagentCast(), Player::DestroyItemCount(), SpellCastTargets::getItemTargetEntry(), Item::GetProto(), Item::GetSpellCharges(), SpellEntry::HasAttribute(), IgnoreItemRequirements(), Object::IsPlayer(), ItemPrototype::ItemId, m_caster, m_CastItem, m_spellInfo, m_targets, m_trueCaster, MAX_ITEM_PROTO_SPELLS, MAX_SPELL_REAGENTS, SpellEntry::Reagent, SpellEntry::ReagentCount, SpellCastTargets::setItemTarget(), Item::SetUsedInSpell(), SPELL_ATTR_EX6_DO_NOT_CONSUME_RESOURCES, _Spell::SpellCharges, and ItemPrototype::Spells.
Referenced by cast().
update()
void Spell::update (uint32 difftime)
Definition at line 4052 of file Spell.cpp.
References AURA_INTERRUPT_FLAG_MOVING, AURA_INTERRUPT_FLAG_TURNING, cancel(), cast(), SpellEntry::ChannelInterruptFlags, SpellEntry::Effect, EFFECT_INDEX_0, finish(), WorldObject::GetAngle(), Unit::GetBeneficiaryPlayer(), Unit::GetChannelObject(), Map::GetCurrentMSTime(), Map::GetGameObject(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetSpellSpeed(), Unit::GetTarget(), Object::GetTypeId(), ObjectAccessor::GetUnit(), SpellCastTargets::getUnitTarget(), SpellCastTargets::getUnitTargetGuid(), SpellEntry::HasAttribute(), Unit::HasChannelObject(), MovementInfo::HasMovementFlag(), SpellEntry::Id, SpellEntry::InterruptFlags, IsAliveUnitPresentInTargetList(), IsAutoRepeat(), Unit::IsClientControlled(), ObjectGuid::IsCreatureOrVehicle(), Unit::IsCrowdControlled(), IsNextMeleeSwingSpell(), Object::IsUnit(), WorldObject::IsWithinCombatDistInMap(), m_caster, m_castOrientation, m_castPositionX, m_castPositionY, m_castPositionZ, m_creationTime, m_duration, m_IsTriggeredSpell, m_maxRange, WorldObject::m_movementInfo, M_PI_F, m_spellInfo, m_spellState, m_targets, m_timer, m_trueCaster, m_UniqueGOTargetInfo, m_UniqueTargetInfo, m_updated, MOVEFLAG_FALLING, MOVEFLAG_FALLINGFAR, SendChannelUpdate(), SetDelayStart(), Unit::SetFacingTo(), WorldObject::SetOrientation(), SetSpellStartTravelling(), SPELL_ATTR_EX2_SPECIAL_TAMING_FLAG, SPELL_ATTR_EX3_IGNORE_CASTER_AND_TARGET_RESTRICTIONS, SPELL_ATTR_EX5_ALLOW_ACTIONS_DURING_CHANNEL, SPELL_ATTR_EX_IS_CHANNELED, SPELL_ATTR_EX_TRACK_TARGET_IN_CHANNEL, SPELL_EFFECT_STUCK, SPELL_INTERRUPT_FLAG_MOVEMENT, SPELL_STATE_CASTING, SPELL_STATE_CHANNELING, SPELL_STATE_TRAVELING, Spell::TargetInfo::targetGUID, Spell::GOTargetInfo::targetGUID, TYPEID_PLAYER, TYPEID_UNIT, and UpdatePointers().
Referenced by SpellEvent::Execute().
UpdateOriginalCasterPointer()
void Spell::UpdateOriginalCasterPointer () protected
Definition at line 8226 of file Spell.cpp.
References Map::GetGameObject(), WorldObject::GetMap(), Object::GetObjectGuid(), GameObject::GetOwner(), ObjectAccessor::GetUnit(), ObjectGuid::IsGameObject(), Object::IsInWorld(), Object::IsUnit(), m_originalCaster, m_originalCasterGUID, and m_trueCaster.
Referenced by Spell(), and UpdatePointers().
UpdatePointers()
void Spell::UpdatePointers ()
Definition at line 8242 of file Spell.cpp.
References m_targets, m_trueCaster, SpellCastTargets::Update(), and UpdateOriginalCasterPointer().
Referenced by cast(), and update().
WriteAmmoToPacket()
void Spell::WriteAmmoToPacket (WorldPacket & data) const
Definition at line 4685 of file Spell.cpp.
References ItemPrototype::DisplayInfoID, Unit::GetDummyAura(), ObjectMgr::GetItemPrototype(), Item::GetProto(), Object::GetUInt32Value(), ItemPrototype::InventoryType, INVTYPE_AMMO, INVTYPE_THROWN, Object::IsPlayer(), ITEM_CLASS_WEAPON, ITEM_SUBCLASS_WEAPON_BOW, ITEM_SUBCLASS_WEAPON_CROSSBOW, ITEM_SUBCLASS_WEAPON_GUN, ITEM_SUBCLASS_WEAPON_THROWN, m_caster, m_trueCaster, MAX_VIRTUAL_ITEM_SLOT, PLAYER_AMMO_ID, RANGED_ATTACK, sItemStore, and UNIT_VIRTUAL_ITEM_SLOT_ID.
Referenced by SendSpellGo(), and SendSpellStart().
WriteSpellGoTargets()
void Spell::WriteSpellGoTargets (WorldPacket & data)
Definition at line 4769 of file Spell.cpp.
References Object::GetObjectGuid(), ObjectGuid::GetString(), SpellCastTargets::getUnitTargetGuid(), SpellEntry::Id, IsChanneledSpell(), m_caster, m_duration, m_needAliveTargetMask, m_spellInfo, m_targets, m_UniqueGOTargetInfo, m_UniqueTargetInfo, ByteBuffer::put(), sLog, SPELL_MISS_IMMUNE2, SPELL_MISS_NONE, SPELL_MISS_REFLECT, SPELL_MISS_RESIST, and ByteBuffer::wpos().
Referenced by SendSpellGo().
Friends And Related Function Documentation
MaNGOS::SpellNotifierCreatureAndPlayer
friend struct MaNGOS::SpellNotifierCreatureAndPlayer friend
Definition at line 401 of file Spell.h.
MaNGOS::SpellNotifierPlayer
friend struct MaNGOS::SpellNotifierPlayer friend
Definition at line 400 of file Spell.h.
Unit::SetCurrentCastedSpell
void Unit::SetCurrentCastedSpell (Spell * pSpell) friend
Field Documentation
corpseTarget
Corpse* Spell::corpseTarget protected
Definition at line 959 of file Spell.h.
Referenced by DoAllEffectOnTarget(), EffectResurrect(), EffectSkinPlayerCorpse(), and Spell().
damage
int32 Spell::damage protected
Definition at line 961 of file Spell.h.
Referenced by CalculateSpellEffectDamage(), DoCreateItem(), DoSummonTotem(), EffectActivateRune(), EffectActivateSpec(), EffectAddComboPoints(), EffectAddExtraAttacks(), EffectAddFarsight(), EffectAddHonor(), EffectApplyAreaAura(), EffectApplyAura(), EffectDestroyAllTotems(), EffectDistract(), EffectDummy(), EffectDurabilityDamage(), EffectDurabilityDamagePCT(), EffectEnchantItemTmp(), EffectEnergisePct(), EffectEnergize(), EffectEnvironmentalDMG(), EffectForceCast(), EffectHeal(), EffectHealMechanical(), EffectHealPct(), EffectHealthLeech(), EffectInebriate(), EffectKnockBack(), EffectKnockBackFromPosition(), EffectLeapBack(), EffectLearnSkill(), EffectLearnSpell(), EffectModifyThreatPercent(), EffectPersistentAA(), EffectPowerBurn(), EffectPowerDrain(), EffectPullTowards(), EffectRedirectThreat(), EffectResurrect(), EffectSchoolDMG(), EffectScriptEffect(), EffectSelfResurrect(), EffectSpecCount(), EffectSummonDeadPet(), EffectSummonType(), EffectThreat(), EffectTriggerMissileSpell(), EffectTriggerSpellWithValue(), EffectWMODamage(), GetDamage(), HandleEffect(), ProcessDispelList(), and SetDamage().
damagePerEffect
int32 Spell::damagePerEffect[MAX_EFFECT_INDEX] protected
Definition at line 969 of file Spell.h.
Referenced by EffectWeaponDmg(), HandleEffect(), and Spell().
gameObjTarget
GameObject* Spell::gameObjTarget protected
Definition at line 958 of file Spell.h.
Referenced by DoAllEffectOnTarget(), EffectActivateObject(), EffectDummy(), EffectJump(), EffectOpenLock(), EffectScriptEffect(), EffectTriggerMissileSpell(), EffectWMOChange(), EffectWMODamage(), EffectWMORepair(), GetGOTarget(), HandleEffect(), SendLoot(), and Spell().
itemTarget
Item* Spell::itemTarget protected
Definition at line 957 of file Spell.h.
Referenced by CheckItems(), DoAllEffectOnTarget(), EffectDisEnchant(), EffectDummy(), EffectEnchantItemPerm(), EffectEnchantItemPrismatic(), EffectEnchantItemTmp(), EffectMilling(), EffectOpenLock(), EffectProspecting(), EffectScriptEffect(), ExecuteEffects(), GetItemTarget(), HandleEffect(), SendLoot(), and Spell().
m_absorb
int32 Spell::m_absorb protected
Definition at line 968 of file Spell.h.
Referenced by DoAllEffectOnTarget(), GetTotalTargetAbsorb(), and HandleImmediateEffectExecution().
m_affectedTargetCount
uint32 Spell::m_affectedTargetCount protected
Definition at line 1061 of file Spell.h.
Referenced by FillTargetMap(), FilterTargetMap(), SetMaxAffectedTargets(), SetTargetMap(), and Spell().
m_applyMultiplierMask
uint8 Spell::m_applyMultiplierMask protected
Definition at line 952 of file Spell.h.
Referenced by ExecuteEffects(), InitializeDamageMultipliers(), and Spell().
m_attackType
WeaponAttackType Spell::m_attackType protected
Definition at line 922 of file Spell.h.
Referenced by CalculateSpellEffectDamage(), cast(), CheckItems(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), EffectWeaponDmg(), PrepareMasksForProcSystem(), Spell(), and TakeAmmo().
m_auraScript
AuraScript* Spell::m_auraScript protected
Definition at line 1048 of file Spell.h.
Referenced by AddUnitTarget(), cast(), CheckCast(), and DoSpellHitOnUnit().
m_autoRepeat
bool Spell::m_autoRepeat protected
Definition at line 928 of file Spell.h.
Referenced by cancel(), IsAutoRepeat(), SetAutoRepeat(), and Spell().
m_canTrigger
bool Spell::m_canTrigger protected
Definition at line 978 of file Spell.h.
Referenced by DoAllEffectOnTarget(), and prepareDataForTriggerSystem().
m_cast_count
uint8 Spell::m_cast_count
Definition at line 639 of file Spell.h.
Referenced by Player::CastItemUseSpell(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandlePetCastSpellOpcode(), SendCastResult(), SendInterrupted(), SendSpellGo(), SendSpellStart(), Spell(), and SpellStart().
m_caster
Unit* Spell::m_caster protected
Definition at line 911 of file Spell.h.
Referenced by _handle_finish_phase(), _handle_immediate_phase(), AddUnitTarget(), CalculateSpellEffectDamage(), cancel(), CanSpellDiminish(), cast(), CastPreCastSpells(), CheckAndAddMagnetTarget(), CheckCast(), CheckCasterAuras(), CheckItems(), CheckOrTakeRunePower(), CheckPetCast(), CheckPower(), CheckRange(), CheckSpellCancelsAuraEffect(), CheckTarget(), Delayed(), DelayedChannel(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), DoSpellHitOnUnit(), DoSummonCritter(), DoSummonGuardian(), DoSummonPet(), DoSummonPossessed(), DoSummonTotem(), DoSummonVehicle(), DoSummonWild(), EffectActivateObject(), EffectActivateRune(), EffectAddComboPoints(), EffectAddFarsight(), EffectApplyAreaAura(), EffectApplyGlyph(), EffectBind(), EffectBlock(), EffectCharge(), EffectChargeDest(), EffectClearQuest(), EffectCreateItem2(), EffectCreateRandomItem(), EffectCreateTamedPet(), EffectDestroyAllTotems(), EffectDisEnchant(), EffectDismissPet(), EffectDispel(), EffectDuel(), EffectDummy(), EffectEnchantHeldItem(), EffectEnchantItemPerm(), EffectEnchantItemPrismatic(), EffectEnchantItemTmp(), EffectEnergisePct(), EffectEnergize(), EffectEnvironmentalDMG(), EffectFeedPet(), EffectForceCast(), EffectHeal(), EffectHealMaxHealth(), EffectHealthLeech(), EffectInstaKill(), EffectInterruptCast(), EffectJump(), EffectKnockBack(), EffectKnockBackFromPosition(), EffectLeapBack(), EffectLeapForward(), EffectLearnPetSpell(), EffectLearnSpell(), EffectMilling(), EffectModifyThreatPercent(), EffectOpenLock(), EffectParry(), EffectPersistentAA(), EffectPickPocket(), EffectPlayMusic(), EffectPowerBurn(), EffectPowerDrain(), EffectProficiency(), EffectProspecting(), EffectPullTowards(), EffectRedirectThreat(), EffectResurrect(), EffectSchoolDMG(), EffectScriptEffect(), EffectSelfResurrect(), EffectSkinning(), EffectSkinPlayerCorpse(), EffectSpawn(), EffectStealBeneficialBuff(), EffectStuck(), EffectSummonAllTotems(), EffectSummonChangeItem(), EffectSummonDeadPet(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonPlayer(), EffectSummonRafFriend(), EffectSummonType(), EffectTaunt(), EffectTeachTaxiNode(), EffectTeleportUnits(), EffectTeleUnitsFaceCaster(), EffectThreat(), EffectTitanGrip(), EffectTransmitted(), EffectTriggerMissileSpell(), EffectTriggerRitualOfSummoning(), EffectTriggerSpell(), EffectTriggerSpellWithValue(), EffectWeaponDmg(), EffectWMOChange(), EvaluateResultLists(), FillRaidOrPartyTargets(), FillTargetMap(), FilterTargetMap(), FindCorpseUsing(), finish(), GetAffectiveCaster(), GetAffectiveCasterOrOwner(), GetCaster(), GetSpellRangeAndRadius(), HandleImmediateEffectExecution(), HandleThreatSpells(), IgnoreItemRequirements(), IsAliveUnitPresentInTargetList(), IsChannelActive(), OnCheckCast(), OnCheckTarget(), OnSuccessfulFinish(), Prepare(), ProcReflectProcs(), ProcSpellAuraTriggers(), SendCastResult(), SendChannelStart(), SendChannelUpdate(), SendLoot(), SendSpellCooldown(), SendSpellGo(), SendSpellStart(), SetFakeCaster(), SetTargetMap(), Spell(), SpellStart(), TakeCastItem(), TakePower(), TakeReagents(), update(), WriteAmmoToPacket(), and WriteSpellGoTargets().
m_CastItem
Item* Spell::m_CastItem protected
Definition at line 912 of file Spell.h.
Referenced by AddUnitTarget(), CanOpenLock(), cast(), CastPreCastSpells(), CheckCast(), CheckItems(), CheckPower(), ClearCastItem(), DoSpellHitOnUnit(), EffectAddHonor(), EffectApplyAreaAura(), EffectApplyAura(), EffectDummy(), EffectEnchantItemPerm(), EffectEnergize(), EffectInebriate(), EffectOpenLock(), EffectResurrect(), EffectSummonChangeItem(), EffectSummonType(), EffectTriggerMissileSpell(), EffectTriggerSpell(), EffectTriggerSpellWithValue(), GetCastItem(), IgnoreItemRequirements(), prepareDataForTriggerSystem(), SendChannelStart(), SendSpellCooldown(), SendSpellGo(), SendSpellStart(), SetCastItem(), Spell(), TakeCastItem(), TakePower(), TakeReagents(), and ~Spell().
m_castOrientation
float Spell::m_castOrientation protected
Definition at line 1059 of file Spell.h.
Referenced by Prepare(), and update().
m_castPositionX
float Spell::m_castPositionX protected
Definition at line 1056 of file Spell.h.
Referenced by Prepare(), Spell(), and update().
m_castPositionY
float Spell::m_castPositionY protected
Definition at line 1057 of file Spell.h.
Referenced by Prepare(), Spell(), and update().
m_castPositionZ
float Spell::m_castPositionZ protected
Definition at line 1058 of file Spell.h.
Referenced by Prepare(), Spell(), and update().
m_casttime
int32 Spell::m_casttime protected
Definition at line 924 of file Spell.h.
Referenced by CheckRange(), Delayed(), GetCastTime(), Prepare(), ReSetTimer(), and Spell().
m_chainTargetCount
uint32 Spell::m_chainTargetCount[MAX_EFFECT_INDEX] protected
Definition at line 1062 of file Spell.h.
Referenced by FillTargetMap(), SetChainTargetsCount(), and Spell().
m_channelOnly
bool Spell::m_channelOnly
Definition at line 660 of file Spell.h.
Referenced by CheckCast(), IgnoreItemRequirements(), IsNeedSendToClient(), SendSpellCooldown(), and Spell().
m_clientCast
bool Spell::m_clientCast
Definition at line 662 of file Spell.h.
Referenced by Player::CastItemUseSpell(), CheckCast(), CheckCasterAuras(), CheckRange(), WorldSession::HandleCastSpellOpcode(), and Spell().
m_creationTime
uint32 Spell::m_creationTime protected
Definition at line 1053 of file Spell.h.
Referenced by Spell(), and update().
m_currentBasePoints
int32 Spell::m_currentBasePoints[MAX_EFFECT_INDEX]
Definition at line 638 of file Spell.h.
Referenced by CalculateSpellEffectValue(), CanOpenLock(), Unit::CastCustomSpell(), Player::CastItemUseSpell(), Unit::CastSpell(), Aura::CastTriggeredSpell(), EffectAddFarsight(), EffectApplyAreaAura(), EffectApplyAura(), EffectDummy(), EffectEnchantHeldItem(), EffectPersistentAA(), EffectReputation(), InitializeImage::OnEffectExecute(), ViscidusGrows::OnEffectExecute(), SharePowers::OnEffectExecute(), LifeTap::OnInit(), and Spell().
m_damage
int32 Spell::m_damage protected
Definition at line 967 of file Spell.h.
Referenced by DoAllEffectOnTarget(), EffectDummy(), GetTotalTargetDamage(), HandleEffect(), HandleImmediateEffectExecution(), ResetEffectDamageAndHeal(), and SetTotalTargetValueModifier().
m_damageMultipliers
float Spell::m_damageMultipliers[3] protected
Definition at line 953 of file Spell.h.
Referenced by ExecuteEffects(), and InitializeDamageMultipliers().
m_damagePerEffect
int32 Spell::m_damagePerEffect[MAX_EFFECT_INDEX] protected
Definition at line 970 of file Spell.h.
Referenced by EffectPowerBurn(), EffectSchoolDMG(), EffectWeaponDmg(), and HandleEffect().
m_delayAtDamageCount
uint8 Spell::m_delayAtDamageCount protected
Definition at line 933 of file Spell.h.
Referenced by isDelayableNoMore(), and Spell().
m_delayMoment
uint64 Spell::m_delayMoment protected
Definition at line 945 of file Spell.h.
Referenced by AddDestExecution(), AddGOTarget(), AddUnitTarget(), CleanupTargetList(), GetDelayMoment(), RecalculateDelayMomentForDest(), and SendSpellGo().
m_delayStart
uint64 Spell::m_delayStart protected
Definition at line 944 of file Spell.h.
Referenced by GetDelayStart(), SetDelayStart(), and Spell().
m_destTargetInfo
DestTargetInfo Spell::m_destTargetInfo protected
Definition at line 1011 of file Spell.h.
Referenced by AddDestExecution(), DoAllTargetlessEffects(), and handle_delayed().
m_doNotProc
bool Spell::m_doNotProc
Definition at line 650 of file Spell.h.
Referenced by prepareDataForTriggerSystem(), and Spell().
m_duration
int32 Spell::m_duration protected
Definition at line 925 of file Spell.h.
Referenced by _handle_immediate_phase(), cast(), DoSpellHitOnUnit(), DoSummonCritter(), DoSummonGuardian(), DoSummonPet(), DoSummonTotem(), DoSummonVehicle(), DoSummonWild(), EffectAddFarsight(), EffectDuel(), EffectDummy(), EffectEnchantHeldItem(), EffectPersistentAA(), EffectSummonObject(), EffectSummonObjectWild(), EffectTransmitted(), Spell(), update(), and WriteSpellGoTargets().
m_effectSkillInfo
EffectSkillInfo Spell::m_effectSkillInfo[MAX_EFFECT_INDEX] protected
Definition at line 1075 of file Spell.h.
Referenced by CheckCast(), and EffectOpenLock().
m_effectTriggerChance
int32 Spell::m_effectTriggerChance[MAX_EFFECT_INDEX] protected
Definition at line 1049 of file Spell.h.
Referenced by HandleEffect(), SetEffectChance(), and Spell().
m_eventTarget
WorldObject* Spell::m_eventTarget protected
Definition at line 964 of file Spell.h.
Referenced by CheckCast(), EffectSendEvent(), EffectSummonObjectWild(), SetEventTarget(), and Spell().
m_executedCurrently
bool Spell::m_executedCurrently protected
Definition at line 950 of file Spell.h.
Referenced by IsDeletable(), IsExecutedCurrently(), SetExecutedCurrently(), and Spell().
m_filteringScheme
SpellTargetFilterScheme Spell::m_filteringScheme[MAX_EFFECT_INDEX][2] protected
Definition at line 1064 of file Spell.h.
Referenced by FillTargetMap(), FillUnitTargets(), SetFilteringScheme(), and Spell().
m_forwardedCastItemGuid
ObjectGuid Spell::m_forwardedCastItemGuid protected
Definition at line 914 of file Spell.h.
Referenced by SendSpellGo(), and SetForwardedCastItem().
m_glyphIndex
uint32 Spell::m_glyphIndex
Definition at line 640 of file Spell.h.
Referenced by Player::CastItemUseSpell(), EffectApplyGlyph(), and Spell().
m_healing
int32 Spell::m_healing protected
Definition at line 971 of file Spell.h.
Referenced by DoAllEffectOnTarget(), EffectHealMaxHealth(), HandleEffect(), HandleImmediateEffectExecution(), and ResetEffectDamageAndHeal().
m_healingPerEffect
int32 Spell::m_healingPerEffect[MAX_EFFECT_INDEX] protected
Definition at line 972 of file Spell.h.
Referenced by EffectHeal(), EffectHealMechanical(), EffectHealPct(), and HandleEffect().
m_healthLeech
int32 Spell::m_healthLeech protected
Definition at line 973 of file Spell.h.
Referenced by finish(), and Spell().
m_hideInCombatLog
bool Spell::m_hideInCombatLog
Definition at line 658 of file Spell.h.
Referenced by SendSpellGo(), SendSpellStart(), and Spell().
m_ignoreCasterAuraState
bool Spell::m_ignoreCasterAuraState
Definition at line 657 of file Spell.h.
Referenced by CheckCasterAuras(), and Spell().
m_ignoreCastTime
bool Spell::m_ignoreCastTime
Definition at line 646 of file Spell.h.
Referenced by Prepare(), and Spell().
m_ignoreConcurrentCasts
bool Spell::m_ignoreConcurrentCasts
Definition at line 656 of file Spell.h.
Referenced by CheckPetCast(), Prepare(), Spell(), and SpellStart().
m_ignoreCooldowns
bool Spell::m_ignoreCooldowns
Definition at line 655 of file Spell.h.
Referenced by CheckCast(), and Spell().
m_ignoreCosts
bool Spell::m_ignoreCosts
Definition at line 654 of file Spell.h.
Referenced by CheckCast(), IgnoreItemRequirements(), and Spell().
m_ignoreGCD
bool Spell::m_ignoreGCD
Definition at line 653 of file Spell.h.
Referenced by CheckCast(), and Spell().
m_ignoreHitResult
bool Spell::m_ignoreHitResult
Definition at line 645 of file Spell.h.
Referenced by AddUnitTarget(), and Spell().
m_ignoreOwnerLevel
bool Spell::m_ignoreOwnerLevel
Definition at line 666 of file Spell.h.
Referenced by EffectSummonPet(), EffectSummonType(), SetIgnoreOwnerLevel(), and Spell().
m_ignoreRoot
bool Spell::m_ignoreRoot
Definition at line 665 of file Spell.h.
Referenced by CheckCast(), SetIgnoreRoot(), and Spell().
m_ignoreUnattackableTarget
bool Spell::m_ignoreUnattackableTarget
Definition at line 648 of file Spell.h.
Referenced by Spell().
m_ignoreUnselectableTarget
bool Spell::m_ignoreUnselectableTarget
Definition at line 647 of file Spell.h.
Referenced by CheckTarget(), and Spell().
m_IsTriggeredSpell
bool Spell::m_IsTriggeredSpell
Definition at line 644 of file Spell.h.
Referenced by AddUnitTarget(), cast(), CheckCast(), CheckItems(), DoAllEffectOnTarget(), DoSpellHitOnUnit(), DoSummonGuardian(), IgnoreItemRequirements(), IsMeleeAttackResetSpell(), IsNeedSendToClient(), IsRangedAttackResetSpell(), Unit::IsTriggeredAtSpellProcEvent(), IsTriggeredSpellWithRedundantCastTime(), Prepare(), Unit::SetCurrentCastedSpell(), Spell(), TakeCastItem(), and update().
m_itemCastSpell
bool Spell::m_itemCastSpell protected
Definition at line 913 of file Spell.h.
Referenced by SetCastItem(), and Spell().
m_jumpRadius
float Spell::m_jumpRadius protected
Definition at line 1063 of file Spell.h.
Referenced by FilterTargetMap(), SetJumpRadius(), SetTargetMap(), and Spell().
m_maxRange
float Spell::m_maxRange protected
Definition at line 929 of file Spell.h.
Referenced by CheckRange(), SendChannelStart(), Spell(), and update().
m_needAliveTargetMask
uint8 Spell::m_needAliveTargetMask
Definition at line 781 of file Spell.h.
Referenced by IsAliveUnitPresentInTargetList(), Spell(), and WriteSpellGoTargets().
m_needSpellLog
bool Spell::m_needSpellLog protected
Definition at line 951 of file Spell.h.
Referenced by _handle_finish_phase(), and Spell().
m_negativeEffectMask
uint8 Spell::m_negativeEffectMask protected
Definition at line 979 of file Spell.h.
Referenced by DoAllEffectOnTarget(), HandleThreatSpells(), and prepareDataForTriggerSystem().
m_notifyAI
bool Spell::m_notifyAI
Definition at line 652 of file Spell.h.
Referenced by cast(), finish(), Prepare(), and Spell().
m_originalCaster
Unit* Spell::m_originalCaster protected
Definition at line 918 of file Spell.h.
Referenced by EffectScriptEffect(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonType(), EffectTransmitted(), GetAffectiveCaster(), GetAffectiveCasterObject(), SetTargetMap(), and UpdateOriginalCasterPointer().
m_originalCasterGUID
ObjectGuid Spell::m_originalCasterGUID protected
Definition at line 916 of file Spell.h.
Referenced by AddUnitTarget(), CastTriggerSpells(), EffectDummy(), EffectScriptEffect(), EffectTriggerMissileSpell(), EffectTriggerSpell(), EffectTriggerSpellWithValue(), GetAffectiveCaster(), GetAffectiveCasterObject(), GetCastingObject(), Spell(), and UpdateOriginalCasterPointer().
m_overridenSpeed
float Spell::m_overridenSpeed private
Definition at line 1094 of file Spell.h.
Referenced by GetSpellSpeed(), and SetOverridenSpeed().
m_overrideSpeed
bool Spell::m_overrideSpeed private
Definition at line 1093 of file Spell.h.
Referenced by GetSpellSpeed(), SetOverridenSpeed(), and Spell().
m_param1
uint32 Spell::m_param1 private
Definition at line 1089 of file Spell.h.
Referenced by CheckCast(), CheckItems(), OnCheckCast(), SendCastResult(), and SetParam1().
m_param2
uint32 Spell::m_param2 private
Definition at line 1090 of file Spell.h.
Referenced by CheckItems(), SendCastResult(), and SetParam2().
m_partialApplicationMask
uint32 Spell::m_partialApplicationMask protected
Definition at line 1013 of file Spell.h.
Referenced by AddDestExecution(), AddUnitTarget(), and CheckCast().
m_petCast
bool Spell::m_petCast
Definition at line 651 of file Spell.h.
Referenced by SendCastResult(), and Spell().
m_powerCost
uint32 Spell::m_powerCost protected
Definition at line 923 of file Spell.h.
Referenced by CheckPower(), finish(), GetPowerCost(), SendSpellGo(), SetPowerCost(), Spell(), and TakePower().
m_preCastSpells
SpellInfoList Spell::m_preCastSpells protected
Definition at line 1043 of file Spell.h.
Referenced by AddPrecastSpell(), CastPreCastSpells(), and Spell().
m_procOnceHolder
std::set<Aura*> Spell::m_procOnceHolder protected
Definition at line 1066 of file Spell.h.
Referenced by IsAuraProcced(), and RegisterAuraProc().
m_referencedFromCurrentSpell
bool Spell::m_referencedFromCurrentSpell protected
Definition at line 949 of file Spell.h.
Referenced by IsDeletable(), SetReferencedFromCurrent(), and Spell().
m_reflectable
bool Spell::m_reflectable protected
Definition at line 926 of file Spell.h.
Referenced by AddUnitTarget(), and Spell().
m_resetLeash
bool Spell::m_resetLeash
Definition at line 659 of file Spell.h.
Referenced by DoAllEffectOnTarget(), and Spell().
m_runesState
uint8 Spell::m_runesState protected
Definition at line 930 of file Spell.h.
Referenced by CheckOrTakeRunePower(), GetOldRuneState(), and Spell().
m_runesStateAfterCast
uint8 Spell::m_runesStateAfterCast protected
Definition at line 931 of file Spell.h.
Referenced by CheckOrTakeRunePower(), GetNewRuneState(), and Spell().
m_scriptValue
uint64 Spell::m_scriptValue protected
Definition at line 1046 of file Spell.h.
Referenced by EffectDummy(), GetScriptValue(), OnSuccessfulFinish(), SetScriptValue(), and Spell().
m_spellAuraHolder
SpellAuraHolder* Spell::m_spellAuraHolder protected
Definition at line 960 of file Spell.h.
Referenced by DoAllEffectOnTarget(), DoSpellHitOnUnit(), EffectApplyAreaAura(), EffectApplyAura(), GetSpellAuraHolder(), and Spell().
m_spellEvent
SpellEvent* Spell::m_spellEvent protected
Definition at line 1082 of file Spell.h.
Referenced by RecalculateDelayMomentForDest(), and SpellStart().
m_spellFlags
uint8 Spell::m_spellFlags protected
Definition at line 927 of file Spell.h.
Referenced by AddUnitTarget(), and Spell().
m_spellInfo
SpellEntry const* Spell::m_spellInfo
Definition at line 636 of file Spell.h.
Referenced by _handle_finish_phase(), _handle_immediate_phase(), Unit::_UpdateAutoRepeatSpell(), AddCorpseTarget(), AddPrecastSpell(), AddTriggeredSpell(), AddUnitTarget(), CalculateDelayMomentForDst(), CalculateSpellEffectDamage(), CalculateSpellEffectValue(), CanAutoCast(), cancel(), CanOpenLock(), CanSpellDiminish(), cast(), CheckCast(), CheckCasterAuras(), CheckItems(), CheckOrTakeRunePower(), CheckPetCast(), CheckPower(), CheckRange(), CheckScriptTargeting(), CheckSpellCancelsAuraEffect(), CheckTarget(), Unit::DealDamage(), Delayed(), DelayedChannel(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), DoCreateItem(), DoSpellHitOnUnit(), DoSummonCritter(), DoSummonGuardian(), DoSummonPet(), DoSummonPossessed(), DoSummonTotem(), DoSummonVehicle(), DoSummonWild(), EffectActivateObject(), EffectActivateRune(), EffectAddFarsight(), EffectAddHonor(), EffectApplyAreaAura(), EffectApplyAura(), EffectApplyGlyph(), EffectBind(), EffectCancelAura(), EffectCharge(), EffectChargeDest(), EffectClearQuest(), EffectCreateItem(), EffectCreateItem2(), EffectCreateRandomItem(), EffectCreateTamedPet(), EffectDisEnchant(), EffectDispel(), EffectDispelMechanic(), EffectDuel(), EffectDummy(), EffectDurabilityDamage(), EffectDurabilityDamagePCT(), EffectEnchantHeldItem(), EffectEnchantItemPerm(), EffectEnchantItemPrismatic(), EffectEnchantItemTmp(), EffectEnergisePct(), EffectEnergize(), EffectEnvironmentalDMG(), EffectFeedPet(), EffectForceCast(), EffectHeal(), EffectHealMechanical(), EffectHealPct(), EffectHealthLeech(), EffectInstaKill(), EffectInterruptCast(), EffectJump(), EffectKillCreditGroup(), EffectKillCreditPersonal(), EffectKnockBack(), EffectKnockBackFromPosition(), EffectLeapBack(), EffectLearnPetSpell(), EffectLearnSkill(), EffectLearnSpell(), EffectOpenLock(), EffectPersistentAA(), EffectPlayMusic(), EffectPlaySound(), EffectPowerBurn(), EffectPowerDrain(), EffectProficiency(), EffectPullTowards(), EffectQuestComplete(), EffectQuestFail(), EffectQuestOffer(), EffectRedirectThreat(), EffectReputation(), EffectRestoreItemCharges(), EffectResurrect(), EffectSanctuary(), EffectSchoolDMG(), EffectScriptEffect(), EffectSelfResurrect(), EffectSendEvent(), EffectSendTaxi(), EffectSpiritHeal(), EffectStealBeneficialBuff(), EffectSummonAllTotems(), EffectSummonChangeItem(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonRafFriend(), EffectSummonType(), EffectTameCreature(), EffectTaunt(), EffectTeachTaxiNode(), EffectTeleportUnits(), EffectThreat(), EffectTitanGrip(), EffectTransmitted(), EffectTriggerMissileSpell(), EffectTriggerRitualOfSummoning(), EffectTriggerSpell(), EffectTriggerSpellWithValue(), EffectUnlearnSpecialization(), EffectWeaponDmg(), EffectWMOChange(), EffectWMODamage(), EffectWMORepair(), EvaluateResultLists(), SpellEvent::Execute(), ExecuteEffects(), FillFromTargetFlags(), FillRaidOrPartyTargets(), FillTargetMap(), FillUnitTargets(), FindCorpseUsing(), finish(), GetCone(), GetCurrentContainer(), GetMinMaxRange(), GetSpellRangeAndRadius(), GetSpellSpeed(), GetUsableHealthStoneItemType(), HandleEffect(), HandleImmediateEffectExecution(), HandleThreatSpells(), WorldSession::HandleUpdateMissileTrajectory(), IgnoreItemRequirements(), SpellLog::Initialize(), InitializeDamageMultipliers(), Unit::InterruptOrDelaySpell(), Unit::InterruptSpell(), IsAliveUnitPresentInTargetList(), IsDelayedSpell(), IsInterruptible(), IsMeleeAttackResetSpell(), IsNeedSendToClient(), IsRangedAttackResetSpell(), IsRangedSpell(), IsSpellRequiringAmmo(), Unit::IsTriggeredAtSpellProcEvent(), IsTriggeredSpellWithRedundantCastTime(), IsValidDeadOrAliveTarget(), Unit::JustKilledCreature(), PlantWarsongBanner::OnCast(), BurnBody::OnCast(), UseBricksBonesaw::OnCast(), SuperJump::OnCast(), UnitAI::OnChannelStateChange(), OnCheckCast(), DemonBroiledSurprise::OnCheckCast(), RaiseDeadHyjal::OnCheckCast(), TagGreaterFelfireDiemetradon::OnCheckCast(), FlagClickBg::OnCheckCast(), BurnBody::OnCheckCast(), UseBricksBonesaw::OnCheckCast(), CheckCrystalFocusSpell::OnCheckCast(), BanishExile::OnCheckCast(), PreventSpellIfSameAuraOnCaster::OnCheckCast(), SpellAbsorption::OnCheckProc(), CurseOfBoundlessAgony::OnCheckTarget(), ThaddiusChargeDamage::OnCheckTarget(), ThaddiusTeslaEffect::OnCheckTarget(), WhipFrenzyHorses::OnCheckTarget(), HorsemanStartFireTargetTest::OnCheckTarget(), TribalDeath::OnCheckTarget(), OnCheckTarget(), spell_pursuit::OnEffectExecute(), spell_aggro_nearest_slave::OnEffectExecute(), spell_poisoned_spear::OnEffectExecute(), FlagAuraBg::OnEffectExecute(), spell_split_teleport_boat::OnEffectExecute(), spell_teleport_sota::OnEffectExecute(), spell_emblazon_runeblade::OnEffectExecute(), spell_siphon_of_acherus_credit::OnEffectExecute(), spell_dispel_scarlet_ghoul_credit::OnEffectExecute(), spell_gift_of_the_harvester::OnEffectExecute(), spell_devour_humanoid::OnEffectExecute(), spell_portal_to_capital_city::OnEffectExecute(), spell_skeletal_gryphon_escape::OnEffectExecute(), spell_death_gate::OnEffectExecute(), FogOfCorruption::OnEffectExecute(), SinisterReflectionClone::OnEffectExecute(), CopyOffhandWeapon::OnEffectExecute(), SummonCThunTentacles::OnEffectExecute(), EntangleFankriss::OnEffectExecute(), AQWhirlwind::OnEffectExecute(), spell_nether_power::OnEffectExecute(), spell_clear_valkyr_essence::OnEffectExecute(), spell_clear_valkyr_touch::OnEffectExecute(), spell_powering_up::OnEffectExecute(), spell_ley_line_focus_item_trigger::OnEffectExecute(), spell_consume_soul::OnEffectExecute(), spell_halls_of_reflection_clone::OnEffectExecute(), spell_mark_fallen_champion::OnEffectExecute(), spell_bone_spike_graveyard::OnEffectExecute(), spell_coldflame_targeting::OnEffectExecute(), spell_coldflame::OnEffectExecute(), spell_coldflame_summon::OnEffectExecute(), ToAnchorOne::OnEffectExecute(), ToAnchorTwo::OnEffectExecute(), ChooseRandomSkullPile::OnEffectExecute(), AnchorToSkull::OnEffectExecute(), ThaddiusTeslaEffect::OnEffectExecute(), spell_ride_red_dragon_buddy::OnEffectExecute(), spell_crystal_spikes::OnEffectExecute(), spell_call_oculus_drake::OnEffectExecute(), spell_lava_strike::OnEffectExecute(), spell_clear_debuffs::OnEffectExecute(), ConflagrationSaviana::OnEffectExecute(), spell_shatter::OnEffectExecute(), spell_taunt_brann::OnEffectExecute(), spell_cauterize::OnEffectExecute(), spell_svala_transforming::OnEffectExecute(), spell_build_wintergrasp_vehicle::OnEffectExecute(), FixateBT::OnEffectExecute(), BonfireArtkit::OnEffectExecute(), SplitDamage::OnEffectExecute(), TKDive::OnEffectExecute(), RaiseDeadDk::OnEffectExecute(), DeathCoilDK::OnEffectExecute(), RighteousDefense::OnEffectExecute(), KillingSpree::OnEffectExecute(), LavaLash::OnEffectExecute(), LifeTap::OnEffectExecute(), ShadowBite::OnEffectExecute(), HeroicStrike::OnEffectExecute(), FlagClickBg::OnEffectExecute(), SunwellTeleport::OnEffectExecute(), TriggerKTAdd::OnEffectExecute(), WebWrapMaexxna::OnEffectExecute(), HorsemanStartFireTargetTest::OnEffectExecute(), TribalDeath::OnEffectExecute(), spell_judgement::OnEffectExecute(), TagGreaterFelfireDiemetradon::OnHit(), TriggerStrafe::OnInit(), LifeTap::OnInit(), TossIceBoulder::OnRadiusCalculate(), RandomRadiusPicker::OnRadiusCalculate(), UnitAI::OnSpellCastStateChange(), OnSuccessfulFinish(), InstillLordValthalaksSpirit::OnSummon(), StoneclawTotem::OnSummon(), Prepare(), prepareDataForTriggerSystem(), PrepareMasksForProcSystem(), ProcessAOECaps(), ProcReflectProcs(), ProcSpellAuraTriggers(), Unit::SelectMagnetTarget(), SendCastResult(), SendChannelStart(), SendChannelUpdate(), SendInterrupted(), SendLoot(), SendSpellCooldown(), SendSpellGo(), SendSpellStart(), Unit::SetCurrentCastedSpell(), SetTargetMap(), Spell(), TakeAmmo(), TakeCastItem(), TakePower(), TakeReagents(), update(), PlayerbotAI::UpdateAI(), MaNGOS::SpellNotifierCreatureAndPlayer::Visit(), MaNGOS::SpellNotifierPlayer::Visit(), WriteSpellGoTargets(), and SpellEvent::~SpellEvent().
m_spellLog
SpellLog Spell::m_spellLog private
Definition at line 1086 of file Spell.h.
Referenced by _handle_finish_phase(), DoSummonTotem(), EffectAddExtraAttacks(), EffectCreateItem(), EffectCreateItem2(), EffectCreateRandomItem(), EffectDismissPet(), EffectDuel(), EffectFeedPet(), EffectInterruptCast(), EffectOpenLock(), EffectPowerBurn(), EffectPowerDrain(), EffectResurrect(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonType(), EffectTransmitted(), and Spell().
m_spellSchoolMask
SpellSchoolMask Spell::m_spellSchoolMask protected
Definition at line 921 of file Spell.h.
Referenced by CalculatePowerCost(), CalculateSpellEffectDamage(), DoAllEffectOnTarget(), EffectPowerDrain(), GetSchoolMask(), HandleImmediateEffectExecution(), and Spell().
m_spellScript
SpellScript* Spell::m_spellScript protected
Definition at line 1047 of file Spell.h.
Referenced by GetSpellScript(), and SendCastResult().
m_spellState
uint32 Spell::m_spellState protected
Definition at line 1051 of file Spell.h.
Referenced by _handle_immediate_phase(), CanBeInterrupted(), cancel(), cast(), CheckItems(), Delayed(), DoSpellHitOnUnit(), finish(), getState(), handle_immediate(), Prepare(), setState(), Spell(), SpellStart(), and update().
m_targetlessMask
uint32 Spell::m_targetlessMask protected
Definition at line 1010 of file Spell.h.
Referenced by DoAllTargetlessEffects(), FillTargetMap(), and Spell().
m_targets
SpellCastTargets Spell::m_targets
Definition at line 641 of file Spell.h.
Referenced by AddCorpseTarget(), AddGOTarget(), AddUnitTarget(), CalculateDelayMomentForDst(), CanOpenLock(), cast(), CastTriggerSpells(), CheckAndAddMagnetTarget(), PlayerbotAI::CheckBotCast(), CheckCast(), CheckItems(), CheckPetCast(), CheckRange(), CheckScriptTargeting(), CheckTarget(), ClearCastItem(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), DoSpellHitOnUnit(), DoSummonPet(), EffectAddFarsight(), EffectChargeDest(), EffectDistract(), EffectDummy(), EffectFeedPet(), EffectForceCast(), EffectHeal(), EffectJump(), EffectKnockBackFromPosition(), EffectLeapForward(), EffectPersistentAA(), EffectPullTowards(), EffectSchoolDMG(), EffectScriptEffect(), EffectSummonDeadPet(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonPet(), EffectSummonType(), EffectTeleportUnits(), EffectTeleUnitsFaceCaster(), EffectTransmitted(), EffectTriggerMissileSpell(), EffectTriggerSpell(), FillFromTargetFlags(), FillTargetMap(), FilterTargetMap(), GetMinMaxRange(), GetPrefilledUnitTargetOrUnitTarget(), GetSpellCastTime(), WorldSession::HandleAcceptTradeOpcode(), WorldSession::HandleOnMissileTrajectoryCollision(), WorldSession::HandleUpdateMissileTrajectory(), IgnoreItemRequirements(), DiveBomb::OnAfterHit(), BlazeTwins::OnCast(), PlantWarsongBanner::OnCast(), CorrosiveSpit::OnCast(), BurnBody::OnCast(), UseBricksBonesaw::OnCast(), GymersBuddy::OnCast(), JuggleTorchCatchQuest::OnCast(), JuggleTorchCatch::OnCast(), OnCheckCast(), CalmDragonkin::OnCheckCast(), TwistingBlade::OnCheckCast(), MentalInterferenceSpellScript::OnCheckCast(), TagGreaterFelfireDiemetradon::OnCheckCast(), PrayerOfMending::OnCheckCast(), CastNetStormforgedPursuer::OnCheckCast(), GammeritaTurtleCamera::OnCheckCast(), SpecificTargetScript::OnCheckCast(), PlantWarsongBanner::OnCheckCast(), CaptureJormungarSpawnSpellScript::OnCheckCast(), ContainerOfRatsSpellScript::OnCheckCast(), LiquidFireOfElune::OnCheckCast(), spell_eagle_eyes::OnCheckCast(), spell_assemble_cage::OnCheckCast(), BurnBody::OnCheckCast(), UseBricksBonesaw::OnCheckCast(), ShootRJR::OnCheckCast(), CrusaderParachute::OnCheckCast(), ExorcismFeather::OnCheckCast(), SparrowhawkNet::OnCheckCast(), BanishExile::OnCheckCast(), MirrorImageFrostbolt::OnCheckCast(), RetaliationCreature::OnCheckCast(), Misdirection::OnCheckCast(), PowerInfusion::OnCheckCast(), CurseOfDoom::OnCheckCast(), DevourMagic::OnCheckCast(), SeedOfCorruptionDamage::OnCheckTarget(), OnCheckTarget(), ArmageddonAnimation::OnDestTarget(), SummonVoidSentinelSummoner::OnDestTarget(), BlackHoleEffect::OnDestTarget(), TeleportSelf::OnDestTarget(), SummonConstrictorSladran::OnDestTarget(), spell_gravity_well_effect::OnDestTarget(), spell_summon_banshee::OnDestTarget(), SummonStefan::OnDestTarget(), EtherealRingSignalFlare::OnDestTarget(), SummonBlossomMoveTarget::OnDestTarget(), CallingRider::OnDestTarget(), NetherVaporSummon::OnDestTarget(), LunarFestivalFireworkSingle::OnDestTarget(), LunarFestivalClusterSmallD::OnDestTarget(), LunarFestivalClusterSmallN::OnDestTarget(), LunarFestivalClusterSmallSE::OnDestTarget(), LunarFestivalClusterSmallSW::OnDestTarget(), LunarFestivalClusterSmallU::OnDestTarget(), LunarFestivalClusterBigD::OnDestTarget(), LunarFestivalClusterBigN::OnDestTarget(), LunarFestivalClusterBigSE::OnDestTarget(), LunarFestivalClusterBigSW::OnDestTarget(), LunarFestivalClusterBigU::OnDestTarget(), SummonRibbonPoleCritter::OnDestTarget(), FlignTorch::OnDestTarget(), BrazierOfDancingFlames::OnDestTarget(), ThousandBladesRenataki::OnEffectExecute(), spell_icy_blast::OnEffectExecute(), ThrowTorch::OnEffectExecute(), ShatteredSunMarksmanShoot::OnEffectExecute(), FlignTorch::OnEffectExecute(), TagGreaterFelfireDiemetradon::OnHit(), BucketLands::OnSuccessfulFinish(), BrazierOfDancingFlames::OnSummon(), SummonGargoyle::OnSummon(), Shadowfiend::OnSummon(), Prepare(), SendCastResult(), SendChannelStart(), SendSpellGo(), SendSpellStart(), SetTargetMap(), MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer(), SpellStart(), TakeCastItem(), TakeReagents(), update(), UpdatePointers(), MaNGOS::SpellNotifierPlayer::Visit(), and WriteSpellGoTargets().
m_timer
uint32 Spell::m_timer protected
Definition at line 1052 of file Spell.h.
Referenced by Delayed(), DelayedChannel(), GetCastedTime(), Prepare(), ReSetTimer(), SendChannelStart(), SendChannelUpdate(), SendSpellStart(), Spell(), and update().
m_travellingStart
uint32 Spell::m_travellingStart protected
Definition at line 946 of file Spell.h.
Referenced by GetSpellStartTravelling(), SetSpellStartTravelling(), and Spell().
m_triggerAutorepeat
bool Spell::m_triggerAutorepeat
Definition at line 649 of file Spell.h.
Referenced by PreCastCheck(), Prepare(), and Spell().
m_triggeredByAuraSpell
SpellEntry const* Spell::m_triggeredByAuraSpell protected
Definition at line 1080 of file Spell.h.
Referenced by AddUnitTarget(), cast(), CheckCast(), CheckTarget(), EffectDummy(), EffectKnockBack(), GetTriggeredByAuraSpellInfo(), IsNeedSendToClient(), IsTriggeredByAura(), SendCastResult(), SendSpellGo(), SendSpellStart(), Spell(), SpellStart(), and TakePower().
m_triggeredBySpellInfo
SpellEntry const* Spell::m_triggeredBySpellInfo
Definition at line 637 of file Spell.h.
Referenced by CheckCast(), DoSpellHitOnUnit(), EffectDummy(), IgnoreItemRequirements(), and Spell().
m_TriggerSpells
SpellInfoList Spell::m_TriggerSpells protected
Definition at line 1042 of file Spell.h.
Referenced by AddTriggeredSpell(), CastTriggerSpells(), finish(), and Spell().
m_trueCaster
WorldObject* Spell::m_trueCaster private
Definition at line 1097 of file Spell.h.
Referenced by _handle_immediate_phase(), AddUnitTarget(), CalculateSpellEffectDamage(), CalculateSpellEffectValue(), CanOpenLock(), cast(), CastTriggerSpells(), CheckCast(), CheckCasterAuras(), CheckItems(), CheckRange(), CheckScriptTargeting(), CheckSpellCancelsAuraEffect(), CheckTarget(), Delayed(), DelayedChannel(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), DoSpellHitOnUnit(), DoSummonWild(), EffectDuel(), EffectDummy(), EffectEnvironmentalDMG(), EffectJump(), EffectScriptEffect(), EffectSendEvent(), EffectSummonObject(), EffectSummonObjectWild(), EffectSummonType(), EffectTransmitted(), FillAreaTargets(), FillTargetMap(), FillUnitTargets(), FilterTargetMap(), finish(), GetAffectiveCasterObject(), GetAffectiveCasterOrOwner(), GetCastingObject(), GetMinMaxRange(), GetPrefilledUnitTargetOrUnitTarget(), GetSpellSpeed(), GetTrueCaster(), handle_delayed(), HandleImmediateEffectExecution(), HandleThreatSpells(), IsAliveUnitPresentInTargetList(), Prepare(), ProcReflectProcs(), RecalculateDelayMomentForDest(), SendCastResult(), SendInterrupted(), SendSpellCooldown(), SendSpellGo(), SendSpellStart(), SetTargetMap(), Spell(), SpellStart(), StopCast(), TakeAmmo(), TakeCastItem(), TakeReagents(), update(), UpdateOriginalCasterPointer(), UpdatePointers(), and WriteAmmoToPacket().
m_uniqueCorpseTargetInfo
CorpseTargetList Spell::m_uniqueCorpseTargetInfo protected
Definition at line 1012 of file Spell.h.
Referenced by AddCorpseTarget(), and handle_immediate().
m_UniqueGOTargetInfo
GOTargetList Spell::m_UniqueGOTargetInfo protected
Definition at line 1008 of file Spell.h.
Referenced by AddGOTarget(), CleanupTargetList(), handle_delayed(), handle_immediate(), HaveTargetsForEffect(), SendChannelStart(), update(), and WriteSpellGoTargets().
m_UniqueItemInfo
ItemTargetList Spell::m_UniqueItemInfo protected
Definition at line 1009 of file Spell.h.
Referenced by _handle_immediate_phase(), AddItemTarget(), CleanupTargetList(), and HaveTargetsForEffect().
m_UniqueTargetInfo
TargetList Spell::m_UniqueTargetInfo protected
Definition at line 1007 of file Spell.h.
Referenced by _handle_immediate_phase(), AddUnitTarget(), cancel(), cast(), CleanupTargetList(), DelayedChannel(), EffectDummy(), EffectSchoolDMG(), EffectWeaponDmg(), FillTargetMap(), finish(), GetPrefilledUnitTargetOrUnitTarget(), GetTargetList(), handle_delayed(), handle_immediate(), HandleThreatSpells(), HaveTargetsForEffect(), IsAliveUnitPresentInTargetList(), ProcessAOECaps(), ProcSpellAuraTriggers(), SendChannelStart(), update(), and WriteSpellGoTargets().
m_updated
bool Spell::m_updated protected
Definition at line 1054 of file Spell.h.
Referenced by Spell(), and update().
m_usedAuraCharges
std::set<SpellModifierPair> Spell::m_usedAuraCharges
Definition at line 743 of file Spell.h.
Referenced by cancel(), Player::SetSpellModSpell(), and SpellModRAII::~SpellModRAII().
unitTarget
Unit* Spell::unitTarget protected
Definition at line 956 of file Spell.h.
Referenced by CalculateSpellEffectDamage(), DoAllEffectOnTarget(), DoAllTargetlessEffects(), DoCreateItem(), EffectActivateSpec(), EffectAddComboPoints(), EffectAddExtraAttacks(), EffectAddHonor(), EffectApplyAreaAura(), EffectApplyAura(), EffectBind(), EffectBreakPlayerTargeting(), EffectCancelAura(), EffectCharge(), EffectCreateTamedPet(), EffectDispel(), EffectDispelMechanic(), EffectDistract(), EffectDualWield(), EffectDuel(), EffectDummy(), EffectDurabilityDamage(), EffectDurabilityDamagePCT(), EffectEnchantHeldItem(), EffectEnchantItemPerm(), EffectEnergisePct(), EffectEnergize(), EffectForceCast(), EffectHeal(), EffectHealMaxHealth(), EffectHealMechanical(), EffectHealPct(), EffectHealthLeech(), EffectInebriate(), EffectInstaKill(), EffectInterruptCast(), EffectJump(), EffectKillCreditGroup(), EffectKillCreditPersonal(), EffectKnockBack(), EffectKnockBackFromPosition(), EffectLeapBack(), EffectLeapForward(), EffectLearnSkill(), EffectLearnSpell(), EffectModifyThreatPercent(), EffectPickPocket(), EffectPlayMusic(), EffectPlaySound(), EffectPowerBurn(), EffectPowerDrain(), EffectPullTowards(), EffectQuestComplete(), EffectQuestFail(), EffectQuestOffer(), EffectRedirectThreat(), EffectRenamePet(), EffectReputation(), EffectRestoreItemCharges(), EffectResurrect(), EffectSanctuary(), EffectSchoolDMG(), EffectScriptEffect(), EffectSendTaxi(), EffectSkinning(), EffectSkinPlayerCorpse(), EffectSpecCount(), EffectSpiritHeal(), EffectStealBeneficialBuff(), EffectSummonAllTotems(), EffectSummonPlayer(), EffectTameCreature(), EffectTaunt(), EffectTeachTaxiNode(), EffectTeleportGraveyard(), EffectTeleportUnits(), EffectTeleUnitsFaceCaster(), EffectThreat(), EffectTitanGrip(), EffectTradeSkill(), EffectTriggerMissileSpell(), EffectTriggerRitualOfSummoning(), EffectTriggerSpell(), EffectTriggerSpellWithValue(), EffectUnlearnSpecialization(), EffectWeaponDmg(), EvaluateResultLists(), ExecuteEffects(), FilterTargetMap(), GetUnitTarget(), HandleEffect(), HandleImmediateEffectExecution(), SetTargetMap(), and Spell().
The documentation for this class was generated from the following files:
Spell.h
Spell.cpp
SpellEffects.cpp