CMaNGOS_WoTLK: TemporarySpawn Class Reference
TemporarySpawn Class Reference
#include <TemporarySpawn.h>
Public Member Functions
TemporarySpawn (ObjectGuid summoner=ObjectGuid())
virtual ~TemporarySpawn ()
void Update (const uint32 diff) override
void SetSummonProperties (TempSpawnType type, uint32 lifetime)
void Summon (TempSpawnType type, uint32 lifetime)
void UnSummon ()
void SaveToDB ()
ObjectGuid const GetSpawnerGuid () const override
void SetLinkedToOwnerAura (uint32 flags)
void SetDeathState (DeathState state) override
uint32 GetDuration () const override
Public Member Functions inherited from Creature
Creature (CreatureSubtype subtype=CREATURE_SUBTYPE_GENERIC)
virtual ~Creature ()
void AddToWorld () override
void RemoveFromWorld () override
virtual void CleanupsBeforeDelete () override
bool Create (uint32 dbGuid, uint32 guidlow, CreatureCreatePos &cPos, CreatureInfo const *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
bool LoadCreatureAddon (bool reload)
void SelectLevel (uint32 forcedLevel=USE_DEFAULT_DATABASE_LEVEL)
void LoadEquipment (uint32 equip_entry, bool force=false)
bool HasStaticDBSpawnData () const
char const * GetSubName () const
virtual void RegenerateAll (uint32 update_diff)
uint32 GetEquipmentId () const
CreatureSubtype GetSubtype () const
bool IsPet () const
bool IsTotem () const
bool IsTemporarySummon () const
bool IsCritter () const
bool IsCorpse () const
bool IsDespawned () const
void SetCorpseDelay (uint32 delay)
void ReduceCorpseDecayTimer ()
TimePoint GetCorpseDecayTimer () const
bool CanRestockPickpocketLoot () const
void StartPickpocketRestockTimer ()
bool IsRacialLeader () const
bool IsCivilian () const
bool IsNoAggroOnSight () const
bool IsGuard () const
bool CanWalk () const
bool CanSwim () const
bool IsSwimming () const
bool CanFly () const override
bool IsFlying () const override
bool IsTrainerOf (Player *pPlayer, bool msg) const
bool CanInteractWithBattleMaster (Player *pPlayer, bool msg) const
bool CanTrainAndResetTalentsOf (Player *pPlayer) const
void FillGuidsListFromThreatList (GuidVector &guids, uint32 maxamount=0)
bool IsImmuneToSpell (SpellEntry const *spellInfo, bool castOnSelf, uint8 effectMask, WorldObject const *caster) override
bool IsImmuneToDamage (SpellSchoolMask meleeSchoolMask) override
bool IsImmuneToSpellEffect (SpellEntry const *spellInfo, SpellEffectIndex index, bool castOnSelf) const override
bool IsElite () const
bool IsWorldBoss () const
uint32 GetLevelForTarget (Unit const *target) const override
uint8 getRace () const override
bool AIM_Initialize ()
virtual UnitAI * AI () override
virtual CombatData * GetCombatData () override
void SetWalk (bool enable, bool asDefault=true)
uint32 GetShieldBlockValue () const override
bool HasSpell (uint32 spellID) const override
void UpdateSpell (int32 index, int32 newSpellId)
void SetSpellList (uint32 spellSet)
void UpdateImmunitiesSet (uint32 immunitySet)
bool UpdateEntry (uint32 Entry, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr, bool preserveHPAndPower=true, bool randomizeLevels=true)
void ResetEntry (bool respawn=false)
void ApplyGameEventSpells (GameEventCreatureData const *eventData, bool activated)
bool UpdateStats (Stats stat) override
bool UpdateAllStats () override
void UpdateResistances (uint32 school) override
void UpdateArmor () override
void UpdateMaxHealth () override
void UpdateMaxPower (Powers power) override
void UpdateAttackPowerAndDamage (bool ranged=false) override
void UpdateDamagePhysical (WeaponAttackType attType) override
uint32 GetCurrentEquipmentId () const
VendorItemData const * GetVendorItems () const
VendorItemData const * GetVendorTemplateItems () const
uint32 GetVendorItemCurrentCount (VendorItem const *vItem)
uint32 UpdateVendorItemCurrentCount (VendorItem const *vItem, uint32 used_count)
TrainerSpellData const * GetTrainerTemplateSpells () const
TrainerSpellData const * GetTrainerSpells () const
CreatureInfo const * GetCreatureInfo () const
CreatureDataAddon const * GetCreatureAddon () const
std::string GetAIName () const
std::string GetScriptName () const
uint32 GetScriptId () const
const char * GetNameForLocaleIdx (int32 loc_idx) const override
bool LoadFromDB (uint32 dbGuid, Map *map, uint32 newGuid, uint32 forcedEntry, GenericTransport *transport=nullptr)
void PrepareBodyLootState ()
CreatureLootStatus GetLootStatus () const
virtual void InspectingLoot () override
void SetLootStatus (CreatureLootStatus status, bool forced=false)
bool IsTappedBy (Player *plr) const
ObjectGuid GetLootRecipientGuid () const
uint32 GetLootGroupRecipientId () const
Player * GetLootRecipient () const
Return player who can loot tapped creature (member of group or single player)
Group * GetGroupLootRecipient () const
Return group if player tap creature as group member, independent is player after leave group or stil be group member.
void SetCorpseAccelerationDelay (uint32 delay)
bool HasLootRecipient () const
bool IsGroupLootRecipient () const
void SetLootRecipient (Unit *unit)
Set player and group (if player group member) who tap creature.
Player * GetOriginalLootRecipient () const
Return original player who tap creature, it can be different from player/group allowed to loot so not use it for loot code.
SpellEntry const * ReachWithSpellAttack (Unit *pVictim)
SpellEntry const * ReachWithSpellCure (Unit *pVictim)
void CallForHelp (float radius)
void CallAssistance ()
void SetNoCallAssistance (bool val)
bool CanAssistTo (const Unit *u, const Unit *enemy, bool checkfaction=true) const
if enemy provided, check for initial combat help against enemy
bool CanInitiateAttack () const
bool CanCallForAssistance () const override
void SetCanCallForAssistance (bool state)
bool IsInGroup (Unit const *other, bool party, bool ignoreCharms) const override
[Serverside] Group: Extension for creatures, player-controlled defaults to unit, creatures check based on friendliness
MovementGeneratorType GetDefaultMovementType () const
void SetDefaultMovementType (MovementGeneratorType mgt)
bool IsVisibleInGridForPlayer (Player *pl) const override
void RemoveCorpse (bool inPlace=false)
virtual void ForcedDespawn (uint32 timeMSToDespawn=0, bool onlyAlive=false)
time_t const & GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (uint32 respawn)
void Respawn ()
void SaveRespawnTime () override
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay, bool once=false)
float GetRespawnRadius () const
void SetRespawnRadius (float dist)
void SendZoneUnderAttackMessage (Player *attacker) const
Sends a message to LocalDefense and WorldDefense channels for players of the other team.
void SetInCombatWithZone (bool checkAttackability=true)
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32 quest_id) const override
void SetDefaultGossipMenuId (uint32 menuId)
uint32 GetDefaultGossipMenuId () const
uint32 GetInteractionPauseTimer () const
GridReference< Creature > & GetGridRef ()
bool IsRegeneratingHealth () const
bool IsRegeneratingPower () const
virtual uint8 GetPetAutoSpellSize () const
virtual uint32 GetPetAutoSpellOnPos (uint8 pos) const
void SetCombatStartPosition (Position const &pos)
void GetCombatStartPosition (Position &pos) const
Position const & GetCombatStartPosition () const
uint32 GetPursuit () const override
void SetRespawnCoord (CreatureCreatePos const &pos)
void SetRespawnCoord (float x, float y, float z, float ori)
void GetRespawnCoord (float &x, float &y, float &z, float *ori=nullptr, float *dist=nullptr) const
Position const & GetRespawnPosition () const
void ResetRespawnCoord ()
void SetFactionTemporary (uint32 factionId, uint32 tempFactionFlags=TEMPFACTION_ALL)
void ClearTemporaryFaction ()
uint32 GetTemporaryFactionFlags () const
void SendAreaSpiritHealerQueryOpcode (Player *pl) const
void SetVirtualItem (VirtualItemSlot slot, uint32 item_id)
bool hasWeapon (WeaponAttackType type) const override
Checks if the current Unit has a weapon equipped at the moment.
bool hasWeaponForAttack (WeaponAttackType type) const override
Checks if the current Unit has a usable weapon at the moment.
virtual void SetCanDualWield (bool value)
void SetInvisible (bool invisible)
bool IsInvisible () const
void SetIgnoreMMAP (bool ignore)
bool IsIgnoringMMAP () const
void OnEventHappened (uint16 eventId, bool activate, bool resume) override
void SetForceAttackingCapability (bool state)
bool GetForceAttackingCapability () const
void SetSpawnCounting (bool state)
uint32 GetDetectionRange () const override
void SetDetectionRange (uint32 range)
void SetBaseWalkSpeed (float speed) override
void SetBaseRunSpeed (float speed, bool force=true) override
void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration) override
bool CanAggro () const
void SetCanAggro (bool canAggro)
bool CanCheckForHelp () const override
void SetCanCheckForHelp (bool state)
void SetNoRewards ()
bool IsNoXp ()
void SetNoXP (bool state)
bool IsNoLoot ()
void SetNoLoot (bool state)
bool IsNoReputation ()
void SetNoReputation (bool state)
bool IsIgnoringFeignDeath () const
void SetIgnoreFeignDeath (bool state)
void SetNoWoundedSlowdown (bool state)
bool IsNoWoundedSlowdown () const
bool IsSlowedInCombat () const override
void SetNoWeaponSkillGain (bool state)
bool IsNoWeaponSkillGain () const override
bool IsPreventingDeath () const override
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false) override
bool HasBeenHitBySpell (uint32 spellId)
void RegisterHitBySpell (uint32 spellId)
void UnregisterHitBySpell (uint32 spellId)
void ResetSpellHitCounter ()
HighGuid GetParentHigh () const override
void Heartbeat () override
CreatureSpellList const & GetSpellList () const
std::vector< uint32 > GetCharmSpells () const
CooldownResult GetSpellCooldown (uint32 spellId, uint32 &cooldown) const
void SetCreatureGroup (CreatureGroup *group)
void ClearCreatureGroup ()
CreatureGroup * GetCreatureGroup () const
CreatureSettings const & GetSettings () const
CreatureSettings & GetSettings ()
void StartCooldown (Unit *owner)
bool IsOnlyVisibleTo (ObjectGuid guid) const override
void SetOnlyVisibleTo (ObjectGuid guid)
ObjectGuid GetKillerGuid () const
void SetKillerGuid (ObjectGuid guid)
Public Member Functions inherited from Unit
virtual ~Unit ()
void AddToWorld () override
void RemoveFromWorld () override
void CleanupsBeforeDelete () override
float GetCollisionHeight () const override
float GetCollisionWidth () const override
float GetObjectBoundingRadius () const override
float GetCombatReach () const override
DiminishingLevels GetDiminishing (DiminishingGroup group)
Gets the current DiminishingLevels for the given group.
void IncrDiminishing (DiminishingGroup group, bool pvp)
Increases the level of the DiminishingGroup by one level up until DIMINISHING_LEVEL_IMMUNE where the target becomes immune to spells of that DiminishingGroup.
void ApplyDiminishingToDuration (DiminishingGroup group, int32 &duration, Unit *caster, DiminishingLevels Level, bool isReflected, SpellEntry const *spellInfo, bool hasAuraScript)
Calculates how long the duration of a spell should be considering diminishing returns, ie, if the Level passed in is DIMINISHING_LEVEL_IMMUNE then the duration will be zeroed out.
void ApplyDiminishingAura (DiminishingGroup group, bool apply)
Applies a diminishing return to the given group if apply is true, otherwise lowers the level by one (?)
void ClearDiminishings ()
Clears all the current diminishing returns for this Unit.
void Update (const uint32 diff) override
void Heartbeat () override
void setAttackTimer (WeaponAttackType type, uint32 time)
Updates the attack time for the given WeaponAttackType.
void resetAttackTimer (WeaponAttackType type=BASE_ATTACK)
Resets the attack timer to the base value decided by Unit::m_modAttackSpeedPct and Unit::GetAttackTime.
uint32 getAttackTimer (WeaponAttackType type) const
Get's the remaining time until we can do an attack.
bool isAttackReady (WeaponAttackType type=BASE_ATTACK) const
Checks whether the unit can do an attack.
bool hasMainhandWeapon () const
bool hasOffhandWeapon () const
bool hasRangedWeapon () const
bool hasMainhandWeaponForAttack () const
bool hasOffhandWeaponForAttack () const
bool hasRangedWeaponForAttack () const
bool UpdateMeleeAttackingState ()
Does an attack if any of the timers allow it and resets them, if the user isn't in range or behind the target an error is sent to the client.
bool CanUseEquippedWeapon (WeaponAttackType attackType) const
Check is a given equipped weapon can be used, ie the mainhand, offhand etc.
bool CanReachWithMeleeAttack (Unit const *pVictim, float flat_mod=0.0f) const
Returns if the Unit can reach a victim with Melee Attack.
void DoExtraAttacks (Unit *pVictim)
bool IsAttackedBy (Unit *attacker) const
bool _addAttacker (Unit *pAttacker)
void _removeAttacker (Unit *pAttacker)
Unit * getAttackerForHelper ()
bool Attack (Unit *victim, bool meleeAttack)
Tries to attack a Unit/Player, also makes sure to stop attacking the current target if we're already attacking someone.
void AttackedBy (Unit *attacker)
Called when we are attacked by someone in someway, might be when a fear runs out and we want to notify AI to attack again or when a spell hits.
void CastStop (uint32 except_spellid=0)
Stop all spells from casting except the one give by except_spellid.
bool AttackStop (bool targetSwitch=false, bool includingCast=false, bool includingCombo=false, bool clientInitiated=false)
Stops attacking whatever we are attacking at the moment and tells the Unit we are attacking that we are not doing that anymore.
void RemoveAllAttackers ()
Removes all attackers from the Unit::m_attackers set and logs it if someone that wasn't attacking it was in the list.
void MeleeAttackStart (Unit *victim)
void MeleeAttackStop (Unit *victim)
AttackerSet const & getAttackers () const
Returns the Unit::m_attackers, that stores the units that are attacking you.
Unit * GetVictim () const
void CombatStop (bool includingCast=false, bool includingCombo=true)
void CombatStopWithPets (bool includingCast=false, bool includingCombo=true)
void StopAttackFaction (uint32 faction_id)
Unit * SelectRandomUnfriendlyTarget (Unit *except=nullptr, float radius=ATTACK_DISTANCE) const
Unit * SelectRandomFriendlyTarget (Unit *except=nullptr, float radius=ATTACK_DISTANCE) const
bool HasDamageInterruptibleStunAura () const
bool HasBreakableByDamageCrowdControlAura (Unit *excludeCasterChannel=nullptr, uint32 excludeAuraApplyMSTimeCutoff=0) const
bool HasBreakableByDamageAuraType (AuraType type, uint32 excludeAura, uint32 excludeAuraApplyMSTimeCutoff) const
bool HasAuraPetShouldAvoidBreaking (Unit *excludeCasterChannel=nullptr, uint32 excludeAuraApplyMSTimeCutoff=0) const
void SendMeleeAttackStop (const Unit &victim) const
void SendMeleeAttackStart (const Unit &victim) const
void addUnitState (uint32 f)
bool hasUnitState (uint32 f) const
void clearUnitState (uint32 f)
bool CanFreeMove () const
bool IsTrivialForTarget (Unit const *pov) const
Trivial: Unit does not count as a worthy target for another unit.
void SetLevel (uint32 lvl)
uint32 GetLevel () const override
uint32 getRaceMask () const
uint8 getClass () const
uint32 getClassMask () const
uint8 getGender () const
float GetStat (Stats stat) const
void SetStat (Stats stat, int32 val)
int32 GetArmor () const
void SetArmor (int32 val)
int32 GetResistance (SpellSchools school) const
void SetResistance (SpellSchools school, int32 val)
uint32 GetHealth () const
uint32 GetMaxHealth () const
float GetHealthPercent () const
void SetHealth (uint32 val)
void SetMaxHealth (uint32 val)
void SetHealthPercent (float percent)
int32 ModifyHealth (int32 dVal)
float OCTRegenHPPerSpirit () const
float OCTRegenMPPerSpirit () const
Powers GetPowerType () const
void SetPowerType (Powers new_powertype, bool sendUpdate=true)
uint32 GetPower (Powers power) const
uint32 GetMaxPower (Powers power) const
float GetPowerPercent () const
float GetPowerPercent (Powers power) const
void SetPower (Powers power, uint32 val, bool withPowerUpdate=true)
void SetMaxPower (Powers power, uint32 val)
int32 ModifyPower (Powers power, int32 dVal)
void ApplyPowerMod (Powers power, uint32 val, bool apply)
void ApplyMaxPowerMod (Powers power, uint32 val, bool apply)
bool HasMana ()
uint32 GetAttackTime (WeaponAttackType att) const
void SetAttackTime (WeaponAttackType att, uint32 val)
void ApplyAttackTimePercentMod (WeaponAttackType att, float val, bool apply)
void ApplyCastTimePercentMod (float val, bool apply)
SheathState GetSheath () const
virtual void SetSheath (SheathState sheathed)
uint32 GetFaction () const override
void setFaction (uint32 faction)
FactionTemplateEntry const * GetFactionTemplateEntry () const
void RestoreOriginalFaction ()
bool IsNeutralToAll () const
bool IsContestedGuard () const
Player const * GetControllingPlayer (bool ignoreCharms=false) const
Controlling player: get which player is the "master" of the unit gameplay-wise.
ReputationRank GetReactionTo (Unit const *unit) const override
Get unit to unit reaction.
ReputationRank GetReactionTo (Corpse const *corpse) const override
Get unit to corpse reaction.
bool IsEnemy (Unit const *unit) const override
Reaction preset: Unit sees another unit as an enemy.
bool IsFriend (Unit const *unit) const override
Reaction preset: Unit sees another unit as a friend.
bool CanAssist (Unit const *unit, bool ignoreFlags=false) const
Assistance: Unit treats another unit as an ally it can help.
bool CanAssist (Corpse const *corpse) const
Assistance: Unit treats a corpse as an ally corpse it can help.
bool CanAttack (Unit const *unit, bool ignoreUntargetable=false) const
Opposition: Unit treats another unit as an enemy it can attack (generic)
bool CanAttackNow (Unit const *unit) const
Opposition: Unit treats another unit as an enemy it can attack (immediate response)
bool CanCooperate (Unit const *unit) const
Cooperation: Unit can cooperate with another unit.
bool CanInteract (GameObject const *object) const
Interaction: Unit can interact with an object (generic)
bool CanInteract (Unit const *unit) const
Interaction: Unit can interact with another unit (generic)
bool CanInteractNow (Unit const *unit) const
Interaction: Unit can interact with another unit (immediate response)
bool IsCivilianForTarget (Unit const *pov) const
Civilian: Unit counts as a dishonorable kill for another unit.
bool IsFogOfWarVisibleStealth (Unit const *other) const
[Serverside] Fog of War: Unit can be seen by other unit through invisibility effects
bool IsFogOfWarVisibleHealth (Unit const *other) const
[Serverside] Fog of War: Unit's health values can be seen by other unit
bool IsFogOfWarVisibleStats (Unit const *other) const
[Serverside] Fog of War: Unit's stat values can be seen by other unit
bool IsInParty (Unit const *other, bool ignoreCharms=false) const
bool IsInGuild (Unit const *other, bool ignoreCharms=false) const
[Serverside] Guild: Unit counts as being placed in the same guild with another unit (for gameplay purposes)
bool IsInTeam (Unit const *other, bool ignoreCharms=true) const
[Serverside] Team: Check if both units are in the same faction team (for gameplay purposes)
virtual bool CanAttackSpell (Unit const *target, SpellEntry const *spellInfo=nullptr, bool isAOE=false) const override
[Serverside] Opposition: Unit can target a target with a harmful spell
virtual bool CanAssistSpell (Unit const *target, SpellEntry const *spellInfo=nullptr) const override
[Serverside] Assistance: Unit can target a target with a helpful spell
bool CanAttackOnSight (Unit const *target) const
[Serverside] Opposition: Unit can attack a target on sight
bool CanAttackInCombat (Unit const *target, bool ignoreUntargetable=false) const
[Serverside] Opposition: Unit can attack a target on sight
bool CanAssistInCombatAgainst (Unit const *who, Unit const *enemy) const
[Serverside] Opposition: this can assist who in attacking enemy
bool CanJoinInAttacking (Unit const *enemy) const
[Serverside] Opposition: this can join combat against enemy
bool IsImmuneToNPC () const
void SetImmuneToNPC (bool state)
bool IsImmuneToPlayer () const
void SetImmuneToPlayer (bool state)
bool IsPlayerControlled () const
uint32 GetCreatedBySpellId () const
bool IsPvP () const
void SetPvP (bool state)
bool IsPvPFreeForAll () const
void SetPvPFreeForAll (bool state)
bool IsPvPContested () const
void SetPvPContested (bool state)
bool IsPvPSanctuary () const
void SetPvPSanctuary (bool state)
uint32 GetCreatureType () const
uint32 GetCreatureTypeMask () const
uint8 getStandState () const
bool IsSitState () const
bool IsStandState () const
bool IsSeatedState () const
bool IsStandUpOnMovementState () const
void SetStandState (uint8 state, bool acknowledge=false)
void SetVisFlags (uint8 flags)
void RemoveVisFlags (uint8 flags)
bool HasVisFlags (uint8 flags)
bool IsMounted () const
uint32 GetMountID () const
virtual bool Mount (uint32 displayid, const Aura *aura=nullptr)
virtual bool Unmount (const Aura *aura=nullptr)
VehicleInfo * GetVehicleInfo () const
bool IsVehicle () const
void SetVehicleId (uint32 entry, uint32 overwriteNpcEntry)
Unit const * FindRootVehicle (const Unit *whichVehicle=nullptr) const
uint16 GetSkillMaxForLevel (Unit const *target=nullptr) const
void Suicide ()
void FallSuicide ()
int32 DealHeal (Unit *pVictim, uint32 addhealth, SpellEntry const *spellProto, bool critical=false, uint32 absorb=0)
void InterruptOrDelaySpell (Unit *pVictim, DamageEffectType damagetype, SpellEntry const *spellProto)
void PetOwnerKilledUnit (Unit *pVictim)
void ProcDamageAndSpellFor (ProcSystemArguments &data, bool isVictim)
void ProcSkillsAndReactives (bool isVictim, Unit *target, uint32 procFlags, uint32 procEx, WeaponAttackType attType)
void HandleEmote (uint32 emote_id)
void HandleEmoteCommand (uint32 emote_id)
void HandleEmoteState (uint32 emote_id)
void AttackerStateUpdate (Unit *pVictim, WeaponAttackType attType=BASE_ATTACK, bool extra=false)
void CalculateMeleeDamage (Unit *pVictim, CalcDamageInfo *calcDamageInfo, WeaponAttackType attackType=BASE_ATTACK)
void DealMeleeDamage (CalcDamageInfo *calcDamageInfo, bool durabilityLoss)
void CalculateSpellDamage (SpellNonMeleeDamage *spellDamageInfo, int32 damage, SpellEntry const *spellInfo, WeaponAttackType attackType=BASE_ATTACK)
uint32 GetResilienceRatingDamageReduction (uint32 damage, SpellDmgClass dmgClass, bool periodic=false, Powers pwrType=POWER_HEALTH) const
SpellMissInfo MeleeSpellHitResult (Unit *pVictim, SpellEntry const *spell, uint32 *heartbeatResistChance=nullptr)
SpellMissInfo MagicSpellHitResult (Unit *pVictim, SpellEntry const *spell, SpellSchoolMask schoolMask, uint32 *heartbeatResistChance=nullptr)
bool CanDualWield () const
bool CanDodge () const
bool CanParry () const
bool CanBlock () const
bool CanCrush () const
bool CanGlance () const
bool CanDaze () const
void SetCanDodge (const bool flag)
void SetCanParry (const bool flag)
void SetCanBlock (const bool flag)
bool CanReactInCombat () const
bool CanCastSpellInCombat () const
bool CanDodgeInCombat () const
bool CanDodgeInCombat (const Unit *attacker) const
bool CanParryInCombat () const
bool CanParryInCombat (const Unit *attacker) const
bool CanBlockInCombat (SpellSchoolMask weaponSchoolMask=SPELL_SCHOOL_MASK_NORMAL) const
bool CanBlockInCombat (const Unit *attacker, SpellSchoolMask weaponSchoolMask=SPELL_SCHOOL_MASK_NORMAL) const
bool CanCrushInCombat () const
bool CanCrushInCombat (const Unit *victim) const
bool CanGlanceInCombat () const
bool CanGlanceInCombat (const Unit *victim) const
bool CanDazeInCombat () const
bool CanDazeInCombat (const Unit *victim) const
bool CanReactOnAbility (const SpellEntry *ability) const
bool CanDodgeAbility (const Unit *attacker, const SpellEntry *ability) const
bool CanParryAbility (const Unit *attacker, const SpellEntry *ability) const
bool CanBlockAbility (const Unit *attacker, const SpellEntry *ability, bool miss=false) const
bool CanDeflectAbility (const Unit *attacker, const SpellEntry *ability) const
float CalculateEffectiveDodgeChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveParryChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveBlockChance (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveCrushChance (const Unit *victim, WeaponAttackType attType) const
float CalculateEffectiveGlanceChance (const Unit *victim, WeaponAttackType attType) const
float CalculateEffectiveDazeChance (const Unit *victim, WeaponAttackType attType) const
uint32 CalculateGlanceAmount (CalcDamageInfo *meleeInfo) const
float CalculateAbilityDeflectChance (const Unit *attacker, const SpellEntry *ability) const
bool RollAbilityPartialBlockOutcome (const Unit *attacker, WeaponAttackType attType, const SpellEntry *ability) const
float GetDodgeChance () const
float GetParryChance () const
float GetBlockChance () const
float GetReflectChance (SpellSchoolMask schoolMask) const
virtual bool CanCrit (WeaponAttackType attType) const
virtual bool CanCrit (SpellSchoolMask schoolMask) const
virtual bool CanCrit (const SpellEntry *entry, SpellSchoolMask schoolMask, WeaponAttackType attType) const
virtual float GetCritChance (WeaponAttackType attType) const
virtual float GetCritChance (SpellSchoolMask schoolMask) const
virtual float GetCritChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
virtual float GetCritTakenChance (Unit const *attacker, SpellSchoolMask dmgSchoolMask, SpellDmgClass dmgClass, SpellEntry const *spellInfo=nullptr, bool heal=false) const
virtual float GetCritMultiplier (SpellSchoolMask dmgSchoolMask, uint32 creatureTypeMask, const SpellEntry *spell=nullptr, bool heal=false) const
virtual float GetCritTakenMultiplier (SpellSchoolMask dmgSchoolMask, SpellDmgClass dmgClass, float ignorePct=0.0f, bool heal=false) const
uint32 CalculateCritAmount (const Unit *victim, uint32 amount, const SpellEntry *entry, bool heal=false) const
uint32 CalculateCritAmount (CalcDamageInfo *meleeInfo) const
virtual float GetHitChance (WeaponAttackType attackType) const
virtual float GetHitChance (SpellSchoolMask schoolMask) const
virtual float GetHitChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
virtual float GetMissChance (WeaponAttackType attackType) const
virtual float GetMissChance (SpellSchoolMask schoolMask) const
virtual float GetMissChance (const SpellEntry *entry, SpellSchoolMask schoolMask) const
float CalculateEffectiveCritChance (const Unit *victim, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateEffectiveMissChance (const Unit *victim, WeaponAttackType attType, const SpellEntry *ability=nullptr) const
float CalculateSpellCritChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
float CalculateSpellMissChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
void SetAlwaysHit (bool value)
float GetExpertisePercent (WeaponAttackType attType) const
virtual int32 GetResistancePenetration (SpellSchools school) const
float CalculateEffectiveMagicResistancePercent (const Unit *attacker, SpellSchoolMask schoolMask, bool binary=false) const
float CalculateSpellResistChance (const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell) const
bool IsBlockCritical () const
uint32 GetUnitMeleeSkill (Unit const *target=nullptr) const
uint32 GetDefenseSkillValue (Unit const *target=nullptr) const
uint32 GetWeaponSkillValue (WeaponAttackType attType, Unit const *target=nullptr) const
float GetWeaponProcChance () const
float GetPPMProcChance (uint32 WeaponSpeed, float PPM) const
MeleeHitOutcome RollMeleeOutcomeAgainst (const Unit *pVictim, WeaponAttackType attType, SpellSchoolMask schoolMask) const
bool isVendor () const
bool isTrainer () const
bool isQuestGiver () const
bool isGossip () const
bool isTaxi () const
bool isGuildMaster () const
bool isBattleMaster () const
bool isBanker () const
bool isInnkeeper () const
bool isSpiritHealer () const
bool isSpiritGuide () const
bool isTabardDesigner () const
bool isAuctioner () const
bool isArmorer () const
bool isServiceProvider () const
bool isSpiritService () const
bool IsTaxiFlying () const
bool IsInCombat () const
void SetInCombatState (bool PvP, Unit *enemy=nullptr)
void SetInCombatWith (Unit *enemy)
void SetInCombatWithAggressor (Unit *aggressor, bool touchOnly=false)
void SetOutOfCombatWithAggressor (Unit *aggressor)
void SetInCombatWithAssisted (Unit *assisted, bool touchOnly=false)
void SetOutOfCombatWithAssisted (Unit *assisted)
void SetInCombatWithVictim (Unit *victim, bool touchOnly=false)
void SetOutOfCombatWithVictim (Unit *victim)
void EngageInCombatWith (Unit *enemy)
void EngageInCombatWithAggressor (Unit *aggressor)
void ClearInCombat ()
void HandleExitCombat (bool pvpCombat=false)
SpellAuraHolderBounds GetSpellAuraHolderBounds (uint32 spell_id)
SpellAuraHolderConstBounds GetSpellAuraHolderBounds (uint32 spell_id) const
uint32 GetAuraCount (uint32 spellId) const
bool HasAuraType (AuraType auraType) const
bool HasAffectedAura (AuraType auraType, SpellEntry const *spellProto) const
bool HasAura (uint32 spellId, SpellEffectIndex effIndex) const
bool HasAura (uint32 spellId) const
bool HasAuraOfDifficulty (uint32 spellId) const
bool HasAuraTypeWithCaster (AuraType auratype, ObjectGuid caster) const
bool HasMechanicMaskOrDispelMaskAura (uint32 dispelMask, uint32 mechanicMask, Unit const *caster) const
bool HasNegativeAuraWithInterruptFlag (SpellAuraInterruptFlags flag) const
template<typename Func >
bool HasAuraHolder (Func func) const
template<typename Func >
bool HasAura (Func func, AuraType type) const
bool HasAuraTypeWithMiscvalue (AuraType auraType, int32 miscvalue) const
bool HasStealthAura () const
bool HasInvisibilityAura () const
bool isFeared () const
bool isInRoots () const
bool IsPolymorphed () const
bool isFrozen () const
bool IsIgnoreUnitState (SpellEntry const *spell, IgnoreUnitState ignoreState) const
virtual bool IsInWater () const
bool IsInSwimmableWater () const
virtual bool IsUnderwater () const
bool IsAboveGround (float diff=0.5f) const
bool isInAccessablePlaceFor (Unit const *unit) const
void EnergizeBySpell (Unit *victim, SpellEntry const *spellInfo, uint32 damage, Powers powerType, bool sendLog=true)
uint32 SpellNonMeleeDamageLog (Unit *pVictim, uint32 spellID, uint32 damage)
SpellCastResult CastSpell (Unit *Victim, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastTargets &targets, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (SpellCastTargets &targets, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, uint32 spellId, int32 const *bp0, int32 const *bp1, int32 const *bp2, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *Victim, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastCustomSpell (Unit *Victim, SpellEntry const *spellInfo, int32 const *bp0, int32 const *bp1, int32 const *bp2, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (float x, float y, float z, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (SpellCastArgs &args, SpellEntry const *spellInfo, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
void DeMorph ()
void SendAIReaction (AiReaction reactionType)
void SendAttackStateUpdate (CalcDamageInfo *calcDamageInfo) const
void SendAttackStateUpdate (uint32 HitInfo, Unit *target, SpellSchoolMask damageSchoolMask, uint32 Damage, uint32 AbsorbDamage, int32 Resist, VictimState TargetState, uint32 BlockedAmount)
void SendEnergizeSpellLog (Unit *pVictim, uint32 SpellID, uint32 Damage, Powers powertype) const
void SendEnvironmentalDamageLog (uint8 type, uint32 damage, uint32 absorb, int32 resist) const
void SendHealSpellLog (Unit *pVictim, uint32 SpellID, uint32 Damage, uint32 OverHeal, bool critical=false, uint32 absorb=0) const
void SendPeriodicAuraLog (SpellPeriodicAuraLogInfo *pInfo) const
void SendSpellDamageResist (Unit *target, uint32 spellId) const
void SendEnchantmentLog (ObjectGuid targetGuid, uint32 itemEntry, uint32 enchantId) const
bool CanInitiateAttack () const
Unit * SelectAttackingTarget (AttackingTarget target, uint32 position, uint32 spellId, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
Unit * SelectAttackingTarget (AttackingTarget target, uint32 position, SpellEntry const *spellInfo=nullptr, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
void SelectAttackingTargets (std::vector< Unit * > &selectedTargets, AttackingTarget target, uint32 position, uint32 spellId, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
void SelectAttackingTargets (std::vector< Unit * > &selectedTargets, AttackingTarget target, uint32 position, SpellEntry const *spellInfo=nullptr, uint32 selectFlags=0, SelectAttackingTargetParams params=SelectAttackingTargetParams(), int32 unitConditionId=0) const
bool IsUnitConditionSatisfied (int32 unitConditionId, Unit const *otherUnit) const
void NearTeleportTo (float x, float y, float z, float orientation, bool casting=false, bool transportLeave=false)
void MonsterMoveWithSpeed (float x, float y, float z, float speed, bool generatePath=false, bool forceDestination=false)
void SendTeleportPacket (float x, float y, float z, float ori, GenericTransport *transport)
void SendHeartBeat ()
void SendMoveRoot (bool state, bool broadcastOnly=false)
bool IsMoving () const
bool IsMovingIgnoreFlying () const
bool IsMovingForward () const
bool IsLevitating () const
bool IsWalking () const
bool IsRooted () const
bool IsFalling () const
bool IsDebuggingMovement () const
void SetDebuggingMovement (bool state)
void SetLevitate (bool enabled)
void SetSwim (bool enabled)
void SetCanFly (bool enabled)
void SetFeatherFall (bool enabled)
void SetHover (bool enabled)
void SetWaterWalk (bool enabled)
void SetInFront (Unit const *target)
void SetFacingTo (float ori)
void SetFacingToObject (WorldObject *pObject)
void SendHighestThreatUpdate (HostileReference *pHostilReference)
void SendThreatClear () const
void SendThreatRemove (HostileReference *pHostileReference) const
void SendThreatUpdate ()
bool IsAlive () const
bool IsDead () const
DeathState GetDeathState () const
bool IsTargetUnderControl (Unit const &target) const
bool HasCharm (ObjectGuid const &exactGuid=ObjectGuid()) const
bool HasCharmer (ObjectGuid const &exactGuid) const
bool HasCharmer () const
bool HasMaster () const
bool HasTarget (ObjectGuid const &exactGuid=ObjectGuid()) const
bool HasChannelObject (ObjectGuid const &exactGuid=ObjectGuid()) const
Unit * GetCharm (WorldObject const *pov=nullptr) const
Unit * GetCharmer (WorldObject const *pov=nullptr) const
Unit * GetCreator (WorldObject const *pov=nullptr) const
Unit * GetTarget (WorldObject const *pov=nullptr) const
WorldObject * GetChannelObject (WorldObject const *pov=nullptr) const
void SetCharm (Unit *charmed)
void SetCharmer (Unit *charmer)
void SetTarget (WorldObject *target)
void SetChannelObject (WorldObject *object)
ObjectGuid const & GetOwnerGuid () const override
void SetOwnerGuid (ObjectGuid owner) override
ObjectGuid const & GetPetGuid () const
void SetPetGuid (ObjectGuid pet)
virtual ObjectGuid const & GetSelectionGuid () const
virtual void SetSelectionGuid (ObjectGuid guid)
ObjectGuid const & GetMasterGuid () const
Unit * GetOwner (WorldObject const *pov=nullptr, bool recursive=false) const
Unit * GetMaster (WorldObject const *pov=nullptr) const
Unit * GetSpawner (WorldObject const *pov=nullptr) const
Unit * GetBeneficiary () const
Player * GetBeneficiaryPlayer () const
bool IsClientControlled (Player const *exactClient=nullptr) const
Player const * GetClientControlling () const
Pet * GetPet () const
void SetPet (Unit *pet)
Pet * GetMiniPet () const
void SetMiniPet (Unit *pet)
void RemoveMiniPet ()
void AddGuardian (Pet *pet)
void RemoveGuardian (Pet *pet)
void RemoveGuardians (bool force=true)
Pet * FindGuardianWithEntry (uint32 entry)
uint32 CountGuardiansWithEntry (uint32 entry)
Pet * GetProtectorPet ()
bool HasAnyPet () const
CharmInfo * GetCharmInfo () const
virtual CharmInfo * InitCharmInfo (Unit *charm)
virtual void DeleteCharmInfo ()
ObjectGuid const & GetTotemGuid (TotemSlot slot) const
Totem * GetTotem (TotemSlot slot) const
bool IsAllTotemSlotsUsed () const
void _AddTotem (TotemSlot slot, Totem *totem)
void _RemoveTotem (Totem *totem)
template<typename Func >
void CallForAllControlledUnits (Func const &func, uint32 controlledMask)
template<typename Func >
bool CheckAllControlledUnits (Func const &func, uint32 controlledMask) const
bool AddSpellAuraHolder (SpellAuraHolder *holder)
void AddAuraToModList (Aura *aura)
void RemoveAura (Aura *Aur, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSpellAuraHolder (SpellAuraHolder *holder, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSingleAuraFromSpellAuraHolder (SpellAuraHolder *holder, SpellEffectIndex index, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveSingleAuraFromSpellAuraHolder (uint32 spellId, SpellEffectIndex effindex, ObjectGuid casterGuid, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpell (uint32 spellId, SpellAuraHolder *except=nullptr, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToItemSpell (Item *castItem, uint32 spellId)
void RemoveAurasByCasterSpell (uint32 spellId, ObjectGuid casterGuid, AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAurasDueToSpellBySteal (SpellAuraHolder *holder, Unit *stealer)
void RemoveAurasDueToSpellByCancel (uint32 spellId)
void RemoveAurasTriggeredBySpell (uint32 spellId, ObjectGuid casterGuid=ObjectGuid())
void RemoveAuraStack (uint32 spellId, int32 modifier=-1)
void RemoveAuraCharge (uint32 spellId)
void RemoveNotOwnTrackedTargetAuras (uint32 newPhase=0x0)
void RemoveAurasAtMechanicImmunity (uint32 mechMask, uint32 exceptSpellId, bool non_positive=false)
void RemoveSpellsCausingAura (AuraType auraType)
void RemoveSpellsCausingAura (AuraType auraType, SpellAuraHolder *except)
void RemoveSpellsCausingAura (AuraType auraType, SpellAuraHolder *except, bool onlyMechanic)
void RemoveSpellsCausingAura (AuraType auraType, ObjectGuid casterGuid)
void RemoveRankAurasDueToSpell (uint32 spellId)
bool RemoveNoStackAurasDueToAuraHolder (SpellAuraHolder *holder)
void RemoveAurasWithInterruptFlags (uint32 flags)
void RemoveAurasWithInterruptFlags (uint32 flags, SpellAuraHolder *except)
void RemoveAurasWithDispelType (DispelType type, ObjectGuid casterGuid=ObjectGuid())
void RemoveAllAuras (AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveArenaAuras (bool onleave=false)
void RemoveAllAurasOnDeath ()
void RemoveAllAurasOnEvade ()
void RemoveAllGroupBuffsFromCaster (ObjectGuid casterGuid)
template<class T >
void RemoveAurasWithAttribute (T flags)
void RemoveAurasOnCast (uint32 flag, SpellEntry const *castedSpellEntry)
void RemoveAuraHolderFromStack (uint32 spellId, uint32 stackAmount=1, ObjectGuid casterGuid=ObjectGuid(), AuraRemoveMode mode=AURA_REMOVE_BY_DEFAULT)
void RemoveAuraHolderDueToSpellByDispel (uint32 spellId, uint32 dispellingSpellId, uint32 stackAmount, ObjectGuid casterGuid, Unit *dispeller)
void DelaySpellAuraHolder (uint32 spellId, int32 delaytime, ObjectGuid casterGuid)
float GetResistanceBuffMods (SpellSchools school, bool positive) const
void SetResistanceBuffMods (SpellSchools school, bool positive, float val)
void ApplyResistanceBuffModsMod (SpellSchools school, bool positive, float val, bool apply)
void ApplyResistanceBuffModsPercentMod (SpellSchools school, bool positive, float val, bool apply)
void InitStatBuffMods ()
void ApplyStatBuffMod (Stats stat, float val, bool apply)
void ApplyStatPercentBuffMod (Stats stat, float val, bool apply)
void SetCreateStat (Stats stat, float val)
void SetCreateHealth (uint32 val)
uint32 GetCreateHealth () const
void SetCreateMana (uint32 val)
uint32 GetCreateMana () const
uint32 GetCreatePowers (Powers power) const
float GetPosStat (Stats stat) const
float GetNegStat (Stats stat) const
float GetCreateStat (Stats stat) const
void SetCreateResistance (SpellSchools school, int32 val)
int32 GetCreateResistance (SpellSchools school) const
void SetCurrentCastedSpell (Spell *pSpell)
virtual void ProhibitSpellSchool (SpellSchoolMask, uint32)
void InterruptSpell (CurrentSpellTypes spellType, bool withDelayed=true, bool sendAutoRepeatCancelToClient=true)
void FinishSpell (CurrentSpellTypes spellType, bool ok=true)
bool IsNonMeleeSpellCasted (bool withDelayed, bool skipChanneled=false, bool skipAutorepeat=false, bool forMovement=false, bool forAutoIgnore=false, bool forEquip=false) const
bool IsDelayCombatTimerSpellCasted () const
void InterruptNonMeleeSpells (bool withDelayed, uint32 spell_id=0)
void InterruptSpellsWithChannelFlags (uint32 flags)
void InterruptSpellsAndAurasWithInterruptFlags (uint32 flags)
bool IsInterruptible () const
Spell * GetCurrentSpell (CurrentSpellTypes spellType) const
Spell * FindCurrentSpellBySpellId (uint32 spell_id) const
ShapeshiftForm GetShapeshiftForm () const
void SetShapeshiftForm (ShapeshiftForm form)
bool IsShapeShifted () const
bool IsNoWeaponShapeShift () const
bool IsInDisallowedMountForm () const
bool HandleStatModifier (UnitMods unitMod, UnitModifierType modifierType, float amount, bool apply)
void SetModifierValue (UnitMods unitMod, UnitModifierType modifierType, float value)
float GetModifierValue (UnitMods unitMod, UnitModifierType modifierType) const
float GetTotalStatValue (Stats stat) const
float GetTotalResistanceValue (SpellSchools school) const
float GetTotalAuraModValue (UnitMods unitMod) const
SpellSchools GetSpellSchoolByAuraGroup (UnitMods unitMod) const
Stats GetStatByAuraGroup (UnitMods unitMod) const
Powers GetPowerTypeByAuraGroup (UnitMods unitMod) const
bool CanModifyStats () const
void SetCanModifyStats (bool modifyStats)
float GetTotalAttackPowerValue (WeaponAttackType attType) const
float GetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, uint8 index=0) const
void SetBaseWeaponDamage (WeaponAttackType attType, WeaponDamageRange damageRange, float value, uint8 index=0)
SpellSchools GetWeaponDamageSchool (WeaponAttackType attType, uint8 index=0) const
void SetWeaponDamageSchool (WeaponAttackType attType, SpellSchools school, uint8 index=0)
SpellSchoolMask GetAttackDamageSchoolMask (WeaponAttackType attType, bool first=false) const
void SetAttackDamageSchool (WeaponAttackType attType, SpellSchools school)
SpellSchoolMask GetRangedDamageSchoolMask (bool first=false) const
void SetRangedDamageSchool (SpellSchools school)
SpellSchoolMask GetMeleeDamageSchoolMask (bool main, bool first=false) const
SpellSchoolMask GetMeleeDamageSchoolMask () const
void SetMeleeDamageSchool (bool main, SpellSchools school)
void SetMeleeDamageSchool (SpellSchools school)
SpellSchoolMask GetMainAttackSchoolMask ()
UnitVisibility GetVisibility () const
void SetVisibility (UnitVisibility x)
void SetVisibilityWithoutUpdate (UnitVisibility x)
void UpdateVisibilityAndView () override
bool IsVisibleForOrDetect (Unit const *u, WorldObject const *viewPoint, bool detect, bool inVisibleList=false, bool is3dDistance=true, bool spell=false, bool ignorePhase=false) const
void SetPhaseMask (uint32 newPhaseMask, bool update) override
bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const override
bool isInvisibleForAlive () const
returns true if creature can't be seen by alive units
TrackedAuraTargetMap & GetTrackedAuraTargets (TrackedAuraType type)
TrackedAuraTargetMap const & GetTrackedAuraTargets (TrackedAuraType type) const
bool IsAOEImmune () const
void SetAOEImmune (bool state)
bool IsChainImmune () const
void SetChainImmune (bool state)
bool CanHaveThreatList (bool ignoreAliveState=false) const
void AddThreat (Unit *pVictim, float threat=0.0f, bool crit=false, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NONE, SpellEntry const *threatSpell=nullptr)
float ApplyTotalThreatModifier (float threat, SpellSchoolMask schoolMask=SPELL_SCHOOL_MASK_NORMAL)
void DeleteThreatList ()
bool SelectHostileTarget ()
bool IsSuppressedTarget (Unit *target) const
bool IsOfflineTarget (Unit *victim) const
void TauntUpdate ()
void FixateTarget (Unit *taunter)
ThreatManager & getThreatManager ()
ThreatManager const & getThreatManager () const
void addHatedBy (HostileReference *pHostileReference)
void removeHatedBy (HostileReference *)
HostileRefManager & getHostileRefManager ()
HostileRefManager const & getHostileRefManager () const
void SetNoThreatState (bool state)
bool GetNoThreatState ()
CombatManager & GetCombatManager ()
CombatManager const & GetCombatManager () const
void TriggerEvadeEvents ()
void TriggerHomeEvents ()
void EvadeTimerExpired ()
uint32 GetVisibleAura (uint8 slot) const
void SetVisibleAura (uint8 slot, uint32 spellid)
VisibleAuraMap const & GetVisibleAuras () const
uint8 GetVisibleAurasCount () const
Aura * GetAura (uint32 spellId, SpellEffectIndex effindex)
Aura * GetAura (AuraType type, SpellFamily family, uint64 familyFlag, uint32 familyFlag2=0, ObjectGuid casterGuid=ObjectGuid()) const
Aura * GetTriggeredByClientAura (uint32 spellId) const
SpellAuraHolder * GetSpellAuraHolder (uint32 spellid) const
SpellAuraHolder * GetSpellAuraHolder (uint32 spellid, ObjectGuid casterGuid) const
SpellAuraHolderMap & GetSpellAuraHolderMap ()
SpellAuraHolderMap const & GetSpellAuraHolderMap () const
AuraList const & GetAurasByType (AuraType type) const
void ApplyAuraProcTriggerDamage (Aura *aura, bool apply)
int32 GetTotalAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifier (AuraType auratype, std::function< bool(Aura const *)> predicate) const
float GetTotalAuraMultiplier (AuraType auratype) const
int32 GetMaxPositiveAuraModifier (AuraType auratype) const
int32 GetMaxNegativeAuraModifier (AuraType auratype) const
int32 GetTotalAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
float GetTotalAuraMultiplierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxPositiveAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetMaxNegativeAuraModifierByMiscMask (AuraType auratype, uint32 misc_mask) const
int32 GetTotalAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxPositiveAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
int32 GetMaxNegativeAuraModifierByMiscValue (AuraType auratype, int32 misc_value) const
float GetTotalAuraMultiplierByMiscValueForMask (AuraType auratype, uint32 mask) const
Aura * GetDummyAura (uint32 spell_id) const
uint32 GetDisplayId () const
void SetDisplayId (uint32 modelId)
uint32 GetNativeDisplayId () const
void SetNativeDisplayId (uint32 modelId)
void RestoreDisplayId ()
void UpdateModelData ()
void SendCollisionHeightUpdate (float height)
DynamicObject * GetDynObject (uint32 spellId, SpellEffectIndex effIndex, Unit *target=nullptr)
DynamicObject * GetDynObject (uint32 spellId)
void AddDynObject (DynamicObject *dynObj)
void RemoveDynObject (uint32 spellid)
void RemoveDynObjectWithGUID (ObjectGuid guid)
void RemoveAllDynObjects ()
GameObject * GetGameObject (uint32 spellId) const
void AddGameObject (GameObject *gameObj)
void AddWildGameObject (GameObject *gameObj)
void RemoveGameObject (GameObject *gameObj, bool del, bool removeAura=true)
void RemoveGameObject (uint32 spellid, bool del)
void RemoveAllGameObjects ()
void AddCreature (uint32 spellId, Creature *creature)
void RemoveCreature (uint32 spellId, bool del)
uint32 CalculateDamage (WeaponAttackType attType, bool normalized, uint8 index=0)
float GetAPMultiplier (WeaponAttackType attType, bool normalized)
void ModifyAuraState (AuraState flag, bool apply)
bool HasAuraState (AuraState flag) const
bool HasAuraStateForCaster (AuraState flag, ObjectGuid casterGuid) const
void UnsummonAllTotems () const
Unit * SelectMagnetTarget (Unit *victim, Spell *spell=nullptr)
int32 SpellBonusWithCoeffs (SpellEntry const *spellProto, int32 total, int32 benefit, int32 ap_benefit, DamageEffectType damagetype, bool donePart, float defCoeffMod=1.0f)
Calculate spell coefficents and level penalties for spell/melee damage or heal.
int32 SpellBaseDamageBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseDamageBonusTaken (SpellSchoolMask schoolMask) const
uint32 SpellDamageBonusDone (Unit *victim, SpellSchoolMask schoolMask, SpellEntry const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
Calculates caster part of spell damage bonuses, also includes different bonuses dependent from target auras.
uint32 SpellDamageBonusTaken (Unit *caster, SpellSchoolMask schoolMask, SpellEntry const *spellProto, uint32 pdamage, DamageEffectType damagetype, uint32 stack=1)
Calculates target part of spell damage bonuses, will be called on each tick for periodic damage over time auras.
int32 SpellBaseHealingBonusDone (SpellSchoolMask schoolMask)
int32 SpellBaseHealingBonusTaken (SpellSchoolMask schoolMask) const
uint32 SpellHealingBonusDone (Unit *victim, SpellEntry const *spellProto, int32 healamount, DamageEffectType damagetype, uint32 stack=1)
Calculates caster part of healing spell bonuses, also includes different bonuses dependent from target auras.
uint32 SpellHealingBonusTaken (Unit *caster, SpellEntry const *spellProto, int32 healamount, DamageEffectType damagetype, uint32 stack=1)
Calculates target part of healing spell bonuses, will be called on each tick for periodic damage over time auras.
uint32 MeleeDamageBonusDone (Unit *victim, uint32 damage, WeaponAttackType attType, SpellSchoolMask schoolMask, SpellEntry const *spellProto=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, uint32 stack=1, bool flat=true)
Calculates caster part of melee damage bonuses, also includes different bonuses dependent from target auras.
uint32 MeleeDamageBonusTaken (Unit *caster, uint32 pdamage, WeaponAttackType attType, SpellSchoolMask schoolMask, SpellEntry const *spellProto=nullptr, DamageEffectType damagetype=DIRECT_DAMAGE, uint32 stack=1, bool flat=true)
Calculates target part of melee damage bonuses, will be called on each tick for periodic damage over time auras.
SpellProcEventTriggerCheck IsTriggeredAtSpellProcEvent (ProcExecutionData &data, SpellAuraHolder *holder, SpellProcEventEntry const *&spellProcEvent)
SpellAuraProcResult TriggerProccedSpell (Unit *target, std::array< int32, MAX_EFFECT_INDEX > &basepoints, uint32 triggeredSpellId, Item *castItem, Aura *triggeredByAura, uint32 cooldown, ObjectGuid originalCaster)
SpellAuraProcResult TriggerProccedSpell (Unit *target, std::array< int32, MAX_EFFECT_INDEX > &basepoints, SpellEntry const *spellInfo, Item *castItem, Aura *triggeredByAura, uint32 cooldown, ObjectGuid originalCaster)
SpellAuraProcResult HandleDummyAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleHasteAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleSpellCritChanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleProcTriggerSpellAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleProcTriggerDamageAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleOverrideClassScriptAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRaidProcFromChargeAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRaidProcFromChargeWithValueAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModCastingSpeedNotStackAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleReflectSpellsSchoolAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModPowerCostSchoolAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleMagnetAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleMechanicImmuneResistanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModDamageFromCasterAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleAddFlatModifierAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleAddPctModifierAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModDamagePercentDoneAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModRating (ProcExecutionData &data)
SpellAuraProcResult HandleSpellMagnetAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleManaShieldAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleModResistanceAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleRemoveByDamageChanceProc (ProcExecutionData &data)
SpellAuraProcResult HandleInvisibilityAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandlePeriodicAuraProc (ProcExecutionData &data)
SpellAuraProcResult HandleNULLProc (ProcExecutionData &)
SpellAuraProcResult HandleCantTrigger (ProcExecutionData &)
void SetLastManaUse ()
bool IsUnderLastManaUseEffect () const
uint32 GetRegenTimer () const
void SetContestedPvP (Player *attackedPlayer=nullptr)
void ApplySpellImmune (Aura const *aura, uint32 op, uint32 type, bool apply)
void ApplySpellDispelImmunity (Aura const *aura, DispelType type, bool apply)
bool IsImmuneToSchool (SpellEntry const *spellInfo, uint8 effectMask) const
uint32 GetSchoolImmunityMask () const
uint32 GetDamageImmunityMask () const
uint32 GetMechanicImmunityMask () const
void CalculateDamageAbsorbAndResist (Unit *caster, SpellSchoolMask schoolMask, DamageEffectType damagetype, const uint32 damage, uint32 *absorb, int32 *resist, bool canReflect=false, bool canResist=true, bool binary=false)
void CalculateAbsorbResistBlock (Unit *caster, SpellNonMeleeDamage *spellDamageInfo, SpellEntry const *spellProto, WeaponAttackType attType=BASE_ATTACK)
void CalculateHealAbsorb (uint32 heal, uint32 *absorb)
void UpdateSpeed (UnitMoveType mtype, bool forced, float ratio=1.0f)
float GetSpeedInMotion () const
float GetSpeed (UnitMoveType mtype) const
float GetXYFlagBasedSpeed () const
float GetXYFlagBasedSpeed (uint32 moveFlags) const
float GetSpeedRateInMotion () const
float GetSpeedRate (UnitMoveType mtype) const
void SetSpeedRate (UnitMoveType mtype, float rate, bool forced=false)
void KnockBackFrom (Unit *target, float horizontalSpeed, float verticalSpeed)
void KnockBackWithAngle (float angle, float horizontalSpeed, float verticalSpeed)
bool HasHoverAura () const
template<typename Func >
bool HasAuraWithCondition (Func const &func) const
void _RemoveAllAuraMods ()
void _ApplyAllAuraMods ()
uint32 CalcNotIgnoreAbsorbDamage (uint32 damage, SpellSchoolMask damageSchoolMask, SpellEntry const *spellInfo=nullptr) const
uint32 CalcNotIgnoreDamageReduction (uint32 damage, SpellSchoolMask damageSchoolMask) const
int32 CalculateAuraDuration (SpellEntry const *spellProto, uint32 effectMask, int32 duration, Unit const *caster)
float CalculateLevelPenalty (SpellEntry const *spellProto) const
void addFollower (FollowerReference *pRef)
void removeFollower (FollowerReference *)
MotionMaster * GetMotionMaster ()
MotionMaster const * GetMotionMaster () const
bool IsStopped () const
void StopMoving (bool forceSendStop=false)
-------—End of Pet responses methods-------—
void InterruptMoving (bool forceSendStop=false)
bool IsCrowdControlled () const
-------—Various crowd control methods--------------—
bool IsConfused () const
bool SetConfused (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0)
bool IsFleeing () const
bool SetFleeing (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, uint32 duration=0)
bool IsStunned () const
bool SetStunned (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, bool logout=false)
bool IsStunnedByLogout () const
bool SetStunnedByLogout (bool apply)
bool IsInPanic () const
bool SetInPanic (uint32 duration)
bool IsImmobilizedState () const
void SetImmobilizedState (bool apply, bool stun=false, bool logout=false)
bool IsFeigningDeath () const
-------—End of crowd control methods-------—
bool IsFeigningDeathSuccessfully () const
void SetFeignDeath (bool apply, ObjectGuid casterGuid=ObjectGuid(), uint32 spellID=0, bool dynamic=true, bool success=true)
void InterruptSpellsCastedOnMe (bool killDelayed=false)
void AddComboPointHolder (uint32 lowguid)
void RemoveComboPointHolder (uint32 lowguid)
void ClearComboPointHolders ()
void SendPetActionFeedback (uint8 msg) const
-------—Pet responses methods--------------—
void SendPetTalk (uint32 pettalk) const
void SendPetAIReaction () const
void SendPetDismiss (uint32 soundId) const
void propagateSpeedChange ()
-------—End of Pet responses methods-------—
void ClearAllReactives ()
void StartReactiveTimer (ReactiveType reactive)
void UpdateReactives (uint32 p_time)
void UpdateAuraForGroup (uint8 slot)
void AddPetAura (PetAura const *petSpell)
void RemovePetAura (PetAura const *petSpell)
void ScheduleAINotify (uint32 delay, bool forced=false)
bool IsAINotifyScheduled () const
void FinalizeAINotifyEvent ()
void AbortAINotifyEvent ()
void OnRelocated ()
bool IsLinkingEventTrigger () const
void TriggerAggroLinkingEvent (Unit *enemy)
bool TakePossessOf (Unit *possessed)
Unit * TakePossessOf (SpellEntry const *spellEntry, SummonPropertiesEntry const *summonProp, uint32 effIdx, float x, float y, float z, float ang)
bool TakeCharmOf (Unit *charmed, uint32 spellId=0, bool advertised=true)
void BreakCharmOutgoing (Unit *charmed)
void BreakCharmOutgoing (bool advertisedOnly=false)
void BreakCharmIncoming ()
void Uncharm (Unit *charmed, uint32 spellId=0)
void RemoveUnattackableTargets (Unit *charmer=nullptr)
bool CanEnterCombat () const
void SetCanEnterCombat (bool can)
void SetIgnoreRangedTargets (bool state)
bool IsIgnoringRangedTargets ()
void SetSupportThreatOnly (bool state)
bool IsSupportThreatOnly ()
void DisableThreatPropagationToOwner ()
bool IsPropagatingThreatToOwner ()
float GetAttackDistance (Unit const *target) const
virtual CombatData const * GetCombatData () const
float GetBaseRunSpeed ()
bool IsSpellProccingHappening () const
void AddDelayedHolderDueToProc (SpellAuraHolder *holder)
void ResetAutoRepeatSpells ()
const uint64 & GetAuraUpdateMask () const
void SetAuraUpdateMask (uint8 slot)
void ResetAuraUpdateMask ()
void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const override
void AdjustZForCollision (float x, float y, float &z, float halfHeight) const override
virtual uint32 GetSpellRank (SpellEntry const *spellInfo)
Player * GetNextRandomRaidMember (float radius, AuraType noAuraType)
bool HasOverrideScript (uint32 id) const
Aura * GetOverrideScript (uint32 id) const
void RegisterOverrideScriptAura (Aura *aura, uint32 id, bool apply)
void RegisterScriptedLocationAura (Aura *aura, AuraScriptLocation location, bool apply)
std::vector< Aura * > & GetScriptedLocationAuras (AuraScriptLocation location)
uint8 GetComboPoints () const
ObjectGuid const & GetComboTargetGuid () const
void AddComboPoints (Unit *target, int8 count)
void ClearComboPoints ()
void RegisterScalingAura (Aura *aura, bool apply)
void UpdateScalingAuras ()
uint32 GetDamageDoneByOthers ()
uint32 GetModifierXpBasedOnDamageReceived (uint32 xp)
void OverrideMountDisplayId (uint32 newDisplayId)
void UpdateSplinePosition (bool relocateOnly=false)
void SendFlightSplineSyncIfNeeded ()
void CharmCooldownInitialize (WorldPacket &data) const
FormationSlotDataSPtr GetFormationSlot ()
void SetFormationSlot (FormationSlotDataSPtr fSlot)
void AddSummonForOnDeathDespawn (ObjectGuid guid)
void DespawnSummonsOnDeath ()
virtual bool IsNoMountedFollow () const
Public Member Functions inherited from WorldObject
virtual ~WorldObject ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
bool IsControlledByPlayer () const
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
void SetNotifyOnEventState (bool state)
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
void PrintCooldownList (ChatHandler &chat) const
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Private Member Functions
bool IsExpired () const
bool CheckAuraOnOwner ()
void RemoveAuraFromOwner ()
void SaveToDB (uint32, uint8, uint32) override
void DeleteFromDB () override
Private Attributes
TempSpawnType m_type
TimePoint m_expirationTimestamp
uint32 m_lifetime
ObjectGuid m_spawner
uint32 m_linkedToOwnerAura
Additional Inherited Members
Public Types inherited from Creature
enum CooldownResult { COOLDOWN_RESULT_NOT_FOUND = 0 , COOLDOWN_RESULT_FOUND = 1 , COOLDOWN_RESULT_CATEGORY_FOUND = 2 }
Public Types inherited from Unit
enum class SpellProcEventTriggerCheck { SPELL_PROC_TRIGGER_FAILED = 0 , SPELL_PROC_TRIGGER_ROLL_FAILED = 1 , SPELL_PROC_TRIGGER_OK = 2 }
typedef std::set< Unit * > AttackerSet
typedef std::multimap< uint32, SpellAuraHolder * > SpellAuraHolderMap
typedef std::pair< SpellAuraHolderMap::iterator, SpellAuraHolderMap::iterator > SpellAuraHolderBounds
typedef std::pair< SpellAuraHolderMap::const_iterator, SpellAuraHolderMap::const_iterator > SpellAuraHolderConstBounds
typedef std::list< SpellAuraHolder * > SpellAuraHolderList
typedef std::list< Aura * > AuraList
typedef std::list< DiminishingReturn > Diminishing
typedef std::set< uint32 > ComboPointHolderSet
typedef std::map< uint8, uint32 > VisibleAuraMap
typedef std::map< SpellEntry const *, ObjectGuid > TrackedAuraTargetMap
typedef std::set< PetAura const * > PetAuraSet
Static Public Member Functions inherited from Creature
static float _GetHealthMod (int32 Rank)
Get custom factor to scale health (default 1, CONFIG_FLOAT_RATE_CREATURE_*_HP)
static float _GetDamageMod (int32 Rank)
Get custom factor to scale damage (default 1, CONFIG_FLOAT_RATE_*_DAMAGE)
static float _GetSpellDamageMod (int32 Rank)
Get custom factor to scale spell damage (default 1, CONFIG_FLOAT_RATE_*_SPELLDAMAGE)
static uint32 ChooseDisplayId (const CreatureInfo *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
static void DeleteFromDB (uint32 lowguid, CreatureData const *data)
static void AddToRemoveListInMaps (uint32 db_guid, CreatureData const *data)
static void SpawnInMaps (uint32 db_guid, CreatureData const *data)
Static Public Member Functions inherited from Unit
static void DealDamageMods (Unit *dealer, Unit *victim, uint32 &damage, uint32 *absorb, DamageEffectType damagetype, SpellEntry const *spellProto=nullptr)
static uint32 DealDamage (Unit *dealer, Unit *victim, uint32 damage, CleanDamage const *cleanDamage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask, SpellEntry const *spellProto, bool durabilityLoss, Spell *spell=nullptr)
static void Kill (Unit *killer, Unit *victim, DamageEffectType damagetype, SpellEntry const *spellProto, bool durabilityLoss, bool duel_hasEnded)
static void HandleDamageDealt (Unit *dealer, Unit *victim, uint32 &damage, CleanDamage const *cleanDamage, DamageEffectType damagetype, SpellSchoolMask damageSchoolMask, SpellEntry const *spellProto, bool duel_hasEnded)
static void ProcDamageAndSpell (ProcSystemArguments &&data)
static bool IsAllowedDamageInArea (Unit *attacker, Unit *victim)
static void DealSpellDamage (Unit *affectiveCaster, SpellNonMeleeDamage *spellDamageInfo, bool durabilityLoss, bool resetLeash)
static SpellMissInfo SpellHitResult (WorldObject *caster, Unit *victim, SpellEntry const *spell, uint8 effectMask, bool reflectable=false, bool reflected=false, uint32 *heartbeatResistChance=nullptr)
static bool RollSpellCritOutcome (Unit *caster, const Unit *victim, SpellSchoolMask schoolMask, const SpellEntry *spell)
static float RollMagicResistanceMultiplierOutcomeAgainst (const Unit *attacker, const Unit *victim, SpellSchoolMask schoolMask, DamageEffectType dmgType, bool binary=false)
static void SendSpellNonMeleeDamageLog (SpellNonMeleeDamage *log)
static void SendSpellNonMeleeDamageLog (WorldObject *attacker, Unit *target, uint32 spellID, uint32 damage, SpellSchoolMask damageSchoolMask, uint32 absorbedDamage, int32 resist, bool isPeriodic, uint32 blocked, bool criticalHit=false, bool split=false)
static void SendSpellMiss (WorldObject *caster, Unit *target, uint32 spellID, SpellMissInfo missInfo)
static void SendSpellOrDamageImmune (ObjectGuid casterGuid, Unit *target, uint32 spellId)
static void CasterHitTargetWithSpell (Unit *realCaster, Unit *target, SpellEntry const *spellInfo, bool triggered, bool success=true)
static float CalcArmorReducedDamage (WorldObject *attacker, Unit *victim, const float damage)
Static Public Member Functions inherited from WorldObject
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Data Fields inherited from Unit
uint32 m_extraAttacks
ObjectGuid m_ObjectSlotGuid [4]
float m_modMeleeHitChance
float m_modRangedHitChance
float m_modSpellHitChance
float m_modSpellCritChance [MAX_SPELL_SCHOOL]
float m_modCritChance [MAX_ATTACK]
float m_modDodgeChance
float m_modDodgeChanceDiminishing
float m_modParryChance
float m_modParryChanceDiminishing
float m_modBlockChance
float m_threatModifier [MAX_SPELL_SCHOOL]
float m_modAttackSpeedPct [3]
float m_modAttackBaseDPSPct [MAX_ATTACK] = { 1.0f, 1.0f, 1.0f }
SpellImmuneList m_spellImmune [MAX_SPELL_IMMUNITY]
uint32 m_AuraFlags
PetAuraSet m_petAuras
Movement::MoveSpline * movespline
Data Fields inherited from WorldObject
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Protected Types inherited from Unit
typedef std::map< uint32, ObjectGuid > WildGameObjectMap
Protected Member Functions inherited from Creature
bool CreateFromProto (uint32 dbGuid, uint32 guidlow, CreatureInfo const *cinfo, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
bool InitEntry (uint32 Entry, const CreatureData *data=nullptr, GameEventCreatureData const *eventData=nullptr)
change the entry of creature until respawn
uint32 GetCreatureConditionalSpawnEntry (uint32 guidlow, Map *map) const
void UnsummonCleanup ()
bool IsCorpseExpired () const
void RegeneratePower (float timerMultiplier)
virtual void RegenerateHealth ()
Protected Member Functions inherited from Unit
bool MeetsSelectAttackingRequirement (Unit *target, SpellEntry const *spellInfo, uint32 selectFlags, SelectAttackingTargetParams params, int32 unitConditionId) const
Unit ()
void _UpdateSpells (uint32 time)
void _UpdateAutoRepeatSpell ()
void DisableSpline ()
ObjectGuid const & GetCharmGuid () const
void SetCharmGuid (ObjectGuid const &charm)
ObjectGuid const & GetSummonGuid () const
void SetSummonGuid (ObjectGuid const &summon)
ObjectGuid const & GetCharmerGuid () const
void SetCharmerGuid (ObjectGuid const &owner)
ObjectGuid const & GetSummonerGuid () const
void SetSummonerGuid (ObjectGuid const &owner)
ObjectGuid const & GetCreatorGuid () const
void SetCreatorGuid (ObjectGuid const &creator)
ObjectGuid const & GetTargetGuid () const
void SetTargetGuid (ObjectGuid const &targetGuid)
ObjectGuid const & GetChannelObjectGuid () const
void SetChannelObjectGuid (ObjectGuid const &targetGuid)
ObjectGuid const & GetCritterGuid () const
void SetCritterGuid (ObjectGuid critterGuid)
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes inherited from Creature
VendorItemCounts m_vendorItemCounts
uint32 m_gossipMenuId
uint32 m_lootMoney
ObjectGuid m_lootRecipientGuid
uint32 m_lootGroupRecipientId
CreatureLootStatus m_lootStatus
uint32 m_corpseAccelerationDecayDelay
TimePoint m_corpseExpirationTime
Timers.
time_t m_respawnTime
uint32 m_respawnDelay
bool m_respawnOverriden
bool m_respawnOverrideOnce
uint32 m_corpseDelay
TimePoint m_pickpocketRestockTime
bool m_canAggro
bool m_checkForHelp
float m_respawnradius
uint32 m_interactionPauseTimer
CreatureSubtype m_subtype
MovementGeneratorType m_defaultMovementType
uint32 m_equipmentId
uint32 m_detectionRange
bool m_AlreadyCallAssistance
bool m_canCallForAssistance
uint32 m_temporaryFactionFlags
uint32 m_originalEntry
Position m_combatStartPos
Position m_respawnPos
uint32 m_gameEventVendorId
uint32 m_immunitySet
std::unique_ptr< UnitAI > m_ai
bool m_isInvisible
bool m_ignoreMMAP
bool m_forceAttackingCapability
bool m_noReputation
CreatureSettings m_settings
bool m_countSpawns
ObjectGuid m_onlyVisibleTo
std::set< uint32 > m_hitBySpells
CreatureSpellList m_spellList
CreatureGroup * m_creatureGroup
ObjectGuid m_killer
bool m_imposedCooldown
Protected Attributes inherited from Unit
bool m_AutoRepeatFirstCast
uint32 m_attackTimer [MAX_ATTACK]
float m_createStats [MAX_STATS]
int32 m_createResistances [MAX_SPELL_SCHOOL]
Unit * m_attacking
DeathState m_deathState
SpellAuraHolderMap m_spellAuraHolders
SpellAuraHolderMap::iterator m_spellAuraHoldersUpdateIterator
AuraList m_deletedAuras
SpellAuraHolderList m_deletedHolders
std::map< uint32, Aura * > m_classScripts
std::vector< Aura * > m_scriptedLocations [SCRIPT_LOCATION_MAX]
std::vector< Aura * > m_scalingAuras
TrackedAuraTargetMap m_trackedAuraTargets [MAX_TRACKED_AURA_TYPES]
GuidList m_dynObjGUIDs
GameObjectList m_gameObj
WildGameObjectMap m_wildGameObjs
bool m_isSorted
uint32 m_transform
std::map< uint32, Creature * > m_creatures
AuraList m_modAuras [TOTAL_AURAS]
float m_auraModifiersGroup [UNIT_MOD_END][MODIFIER_TYPE_END]
WeaponDamageInfo m_weaponDamageInfo
bool m_canModifyStats
VisibleAuraMap m_visibleAuras
float m_speed_rate [MAX_MOVE_TYPE]
CharmInfo * m_charmInfo
MotionMaster i_motionMaster
uint32 m_reactiveTimer [MAX_REACTIVE]
uint32 m_regenTimer
uint32 m_lastManaUseTimer
bool m_canDodge
bool m_canParry
bool m_canBlock
bool m_canDualWield = false
VehicleInfo * m_vehicleInfo
bool m_isCreatureLinkingTrigger
bool m_isSpawningLinked
CombatData * m_combatData
CombatManager m_combatManager
float m_baseSpeedWalk
float m_baseSpeedRun
FormationSlotDataSPtr m_formationSlot
Protected Attributes inherited from WorldObject
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Detailed Description
Definition at line 25 of file TemporarySpawn.h.
Constructor & Destructor Documentation
TemporarySpawn()
TemporarySpawn::TemporarySpawn (ObjectGuid summoner = ObjectGuid()) explicit
Definition at line 23 of file TemporarySpawn.cpp.
~TemporarySpawn()
virtual TemporarySpawn::~TemporarySpawn () inline virtual
Definition at line 29 of file TemporarySpawn.h.
Member Function Documentation
CheckAuraOnOwner()
bool TemporarySpawn::CheckAuraOnOwner () private
Definition at line 256 of file TemporarySpawn.cpp.
References Unit::GetSpawner(), Object::GetUInt32Value(), and UNIT_CREATED_BY_SPELL.
Referenced by Update().
DeleteFromDB()
void TemporarySpawn::DeleteFromDB () inline override private virtual
Reimplemented from Creature.
Definition at line 51 of file TemporarySpawn.h.
References MANGOS_ASSERT.
GetDuration()
uint32 TemporarySpawn::GetDuration () const override virtual
Reimplemented from Creature.
Definition at line 286 of file TemporarySpawn.cpp.
References WorldObject::GetMap(), and m_expirationTimestamp.
GetSpawnerGuid()
ObjectGuid const TemporarySpawn::GetSpawnerGuid () const inline override virtual
Reimplemented from WorldObject.
Definition at line 36 of file TemporarySpawn.h.
References m_spawner.
Referenced by ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpExportCommand(), ChatHandler::HandleWpModifyCommand(), ChatHandler::HandleWpShowCommand(), UnSummon(), and UnsummonVisualWaypoints().
IsExpired()
bool TemporarySpawn::IsExpired () const private
Definition at line 291 of file TemporarySpawn.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), and m_expirationTimestamp.
Referenced by Update().
RemoveAuraFromOwner()
void TemporarySpawn::RemoveAuraFromOwner () private
Definition at line 266 of file TemporarySpawn.cpp.
References Unit::GetSpawner(), Object::GetUInt32Value(), and UNIT_CREATED_BY_SPELL.
Referenced by UnSummon(), and Update().
SaveToDB() [1/2]
void TemporarySpawn::SaveToDB () virtual
Reimplemented from Creature.
Definition at line 275 of file TemporarySpawn.cpp.
SaveToDB() [2/2]
void TemporarySpawn::SaveToDB (uint32 , uint8 , uint32) inline override private virtual
Reimplemented from Creature.
Definition at line 47 of file TemporarySpawn.h.
References MANGOS_ASSERT.
SetDeathState()
void TemporarySpawn::SetDeathState (DeathState state) override virtual
Reimplemented from Creature.
Definition at line 279 of file TemporarySpawn.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), JUST_DIED, m_expirationTimestamp, m_lifetime, m_type, Creature::SetDeathState(), and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
SetLinkedToOwnerAura()
void TemporarySpawn::SetLinkedToOwnerAura (uint32 flags) inline
Definition at line 37 of file TemporarySpawn.h.
References m_linkedToOwnerAura.
Referenced by Unit::TakePossessOf().
SetSummonProperties()
void TemporarySpawn::SetSummonProperties (TempSpawnType type, uint32 lifetime)
Definition at line 217 of file TemporarySpawn.cpp.
References Map::GetCurrentClockTime(), WorldObject::GetMap(), m_expirationTimestamp, m_lifetime, Creature::m_respawnDelay, m_type, and MONTH.
Referenced by boss_felmystAI::boss_felmystAI(), Summon(), and Unit::TakePossessOf().
Summon()
void TemporarySpawn::Summon (TempSpawnType type, uint32 lifetime)
Definition at line 227 of file TemporarySpawn.cpp.
References Map::Add(), Creature::AIM_Initialize(), WorldObject::GetMap(), and SetSummonProperties().
Referenced by WorldObject::SummonCreature().
UnSummon()
void TemporarySpawn::UnSummon ()
Definition at line 236 of file TemporarySpawn.cpp.
References WorldObject::AddObjectToRemoveList(), Creature::AI(), WorldObject::GetMap(), GetSpawnerGuid(), m_linkedToOwnerAura, RemoveAuraFromOwner(), UnitAI::SummonedCreatureDespawn(), TEMPSPAWN_LINKED_AURA_REMOVE_OWNER, and Creature::UnsummonCleanup().
Referenced by Spell::EffectScriptEffect(), UnsummonVisualWaypoints(), Update(), and npc_bird_spiritAI::UpdateAI().
Update()
void TemporarySpawn::Update (const uint32 diff) override virtual
Reimplemented from Creature.
Definition at line 28 of file TemporarySpawn.cpp.
References ALIVE, CheckAuraOnOwner(), CORPSE, DEAD, Unit::GetCharmerGuid(), Map::GetCurrentClockTime(), Object::GetEntry(), WorldObject::GetMap(), Unit::IsAlive(), Creature::IsCorpse(), Unit::IsDead(), Creature::IsDespawned(), IsExpired(), Unit::IsInCombat(), Unit::m_deathState, m_expirationTimestamp, m_lifetime, m_linkedToOwnerAura, m_type, RemoveAuraFromOwner(), sLog, TEMPSPAWN_CORPSE_DESPAWN, TEMPSPAWN_CORPSE_TIMED_DESPAWN, TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_LINKED_AURA_OWNER_CHECK, TEMPSPAWN_LINKED_AURA_REMOVE_OWNER, TEMPSPAWN_MANUAL_DESPAWN, TEMPSPAWN_TIMED_DESPAWN, TEMPSPAWN_TIMED_OOC_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_CORPSE_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TEMPSPAWN_TIMED_OR_CORPSE_DESPAWN, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, UnSummon(), and Creature::Update().
Field Documentation
m_expirationTimestamp
TimePoint TemporarySpawn::m_expirationTimestamp private
Definition at line 57 of file TemporarySpawn.h.
Referenced by GetDuration(), IsExpired(), SetDeathState(), SetSummonProperties(), and Update().
m_lifetime
uint32 TemporarySpawn::m_lifetime private
Definition at line 58 of file TemporarySpawn.h.
Referenced by SetDeathState(), SetSummonProperties(), and Update().
m_linkedToOwnerAura
uint32 TemporarySpawn::m_linkedToOwnerAura private
Definition at line 60 of file TemporarySpawn.h.
Referenced by SetLinkedToOwnerAura(), UnSummon(), and Update().
m_spawner
ObjectGuid TemporarySpawn::m_spawner private
Definition at line 59 of file TemporarySpawn.h.
Referenced by GetSpawnerGuid().
m_type
TempSpawnType TemporarySpawn::m_type private
Definition at line 56 of file TemporarySpawn.h.
Referenced by SetDeathState(), SetSummonProperties(), and Update().
The documentation for this class was generated from the following files:
TemporarySpawn.h
TemporarySpawn.cpp