CMaNGOS_WoTLK: NullSessionAnticheat Class Reference
NullSessionAnticheat Class Reference
#include <Anticheat.hpp>
Public Member Functions
NullSessionAnticheat (WorldSession *session)
virtual void Update (uint32)
virtual bool IsSilenced () const
virtual void SendCharEnum (WorldPacket &&packet)
virtual void NewPlayer ()
virtual void LeaveWorld ()
virtual void Disconnect ()
virtual bool ReadAddonInfo (WorldPacket *Source, WorldPacket &Target)
virtual void SendPlayerInfo (ChatHandler *) const
virtual void RecordCheat (uint32 actionMask, const char *, const char *,...)
virtual bool Movement (MovementInfo &, const WorldPacket &packet)
virtual void TimeSkipped (const ObjectGuid &, uint32)
virtual bool ExtrapolateMovement (MovementInfo const &, uint32, Position &)
virtual bool SpeedChangeAck (MovementInfo &, const WorldPacket &, float)
virtual bool IsInKnockBack () const
virtual void KnockBack (float, float, float, float)
virtual void OnExplore (const AreaTableEntry *)
virtual void Teleport (const Position &)
virtual void OrderSent (uint16, uint32)
virtual void OrderAck (uint16, uint32)
virtual void WardenPacket (WorldPacket &)
virtual void AutoReply (const std::string &)
virtual void Whisper (const std::string &, const ObjectGuid &)
virtual void Say (const std::string &)
virtual void Yell (const std::string &)
virtual void Channel (const std::string &)
virtual void Mail (const std::string &, const std::string &, const ObjectGuid &)
virtual void ChannelInvite (const std::string &, const ObjectGuid &) override
virtual void PartyInvite (const ObjectGuid &)
Public Member Functions inherited from SessionAnticheatInterface
virtual ~SessionAnticheatInterface ()=default
Private Attributes
WorldSession *const _session
bool _inKnockBack
Detailed Description
Definition at line 138 of file Anticheat.hpp.
Constructor & Destructor Documentation
NullSessionAnticheat()
NullSessionAnticheat::NullSessionAnticheat (WorldSession * session) inline
Definition at line 145 of file Anticheat.hpp.
Member Function Documentation
AutoReply()
virtual void NullSessionAnticheat::AutoReply (const std::string &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 290 of file Anticheat.hpp.
Channel()
virtual void NullSessionAnticheat::Channel (const std::string &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 294 of file Anticheat.hpp.
ChannelInvite()
virtual void NullSessionAnticheat::ChannelInvite (const std::string & , const ObjectGuid &) inline override virtual
Implements SessionAnticheatInterface.
Definition at line 296 of file Anticheat.hpp.
Disconnect()
virtual void NullSessionAnticheat::Disconnect () inline virtual
Implements SessionAnticheatInterface.
Definition at line 156 of file Anticheat.hpp.
ExtrapolateMovement()
virtual bool NullSessionAnticheat::ExtrapolateMovement (MovementInfo const & , uint32 , Position &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 276 of file Anticheat.hpp.
IsInKnockBack()
virtual bool NullSessionAnticheat::IsInKnockBack () const inline virtual
Implements SessionAnticheatInterface.
Definition at line 278 of file Anticheat.hpp.
References _inKnockBack.
IsSilenced()
virtual bool NullSessionAnticheat::IsSilenced () const inline virtual
Implements SessionAnticheatInterface.
Definition at line 149 of file Anticheat.hpp.
KnockBack()
virtual void NullSessionAnticheat::KnockBack (float , float , float , float) inline virtual
Implements SessionAnticheatInterface.
Definition at line 279 of file Anticheat.hpp.
References _inKnockBack.
LeaveWorld()
virtual void NullSessionAnticheat::LeaveWorld () inline virtual
Implements SessionAnticheatInterface.
Definition at line 155 of file Anticheat.hpp.
Mail()
virtual void NullSessionAnticheat::Mail (const std::string & , const std::string & , const ObjectGuid &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 295 of file Anticheat.hpp.
Movement()
virtual bool NullSessionAnticheat::Movement (MovementInfo & , const WorldPacket & packet) inline virtual
Implements SessionAnticheatInterface.
Definition at line 268 of file Anticheat.hpp.
References _inKnockBack, WorldPacket::GetOpcode(), and MSG_MOVE_FALL_LAND.
NewPlayer()
virtual void NullSessionAnticheat::NewPlayer () inline virtual
Implements SessionAnticheatInterface.
Definition at line 154 of file Anticheat.hpp.
OnExplore()
virtual void NullSessionAnticheat::OnExplore (const AreaTableEntry *) inline virtual
Implements SessionAnticheatInterface.
Definition at line 280 of file Anticheat.hpp.
OrderAck()
virtual void NullSessionAnticheat::OrderAck (uint16 , uint32) inline virtual
Implements SessionAnticheatInterface.
Definition at line 284 of file Anticheat.hpp.
OrderSent()
virtual void NullSessionAnticheat::OrderSent (uint16 , uint32) inline virtual
Implements SessionAnticheatInterface.
Definition at line 283 of file Anticheat.hpp.
PartyInvite()
virtual void NullSessionAnticheat::PartyInvite (const ObjectGuid &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 297 of file Anticheat.hpp.
ReadAddonInfo()
virtual bool NullSessionAnticheat::ReadAddonInfo (WorldPacket * Source, WorldPacket & Target) inline virtual
Implements SessionAnticheatInterface.
Definition at line 159 of file Anticheat.hpp.
References ByteBuffer::contents(), ByteBuffer::resize(), ByteBuffer::rpos(), ByteBuffer::size(), and SMSG_ADDON_INFO.
RecordCheat()
virtual void NullSessionAnticheat::RecordCheat (uint32 actionMask, const char * , const char * , ...) inline virtual
Implements SessionAnticheatInterface.
Definition at line 261 of file Anticheat.hpp.
References _session, CHEAT_ACTION_KICK, and WorldSession::KickPlayer().
Say()
virtual void NullSessionAnticheat::Say (const std::string &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 292 of file Anticheat.hpp.
SendCharEnum()
virtual void NullSessionAnticheat::SendCharEnum (WorldPacket && packet) inline virtual
Implements SessionAnticheatInterface.
Definition at line 152 of file Anticheat.hpp.
References _session, and WorldSession::SendPacket().
SendPlayerInfo()
virtual void NullSessionAnticheat::SendPlayerInfo (ChatHandler *) const inline virtual
Implements SessionAnticheatInterface.
Definition at line 258 of file Anticheat.hpp.
SpeedChangeAck()
virtual bool NullSessionAnticheat::SpeedChangeAck (MovementInfo & , const WorldPacket & , float) inline virtual
Implements SessionAnticheatInterface.
Definition at line 277 of file Anticheat.hpp.
Teleport()
virtual void NullSessionAnticheat::Teleport (const Position &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 281 of file Anticheat.hpp.
TimeSkipped()
virtual void NullSessionAnticheat::TimeSkipped (const ObjectGuid & , uint32) inline virtual
Implements SessionAnticheatInterface.
Definition at line 275 of file Anticheat.hpp.
Update()
virtual void NullSessionAnticheat::Update (uint32) inline virtual
Implements SessionAnticheatInterface.
Definition at line 147 of file Anticheat.hpp.
WardenPacket()
virtual void NullSessionAnticheat::WardenPacket (WorldPacket &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 287 of file Anticheat.hpp.
Whisper()
virtual void NullSessionAnticheat::Whisper (const std::string & , const ObjectGuid &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 291 of file Anticheat.hpp.
Yell()
virtual void NullSessionAnticheat::Yell (const std::string &) inline virtual
Implements SessionAnticheatInterface.
Definition at line 293 of file Anticheat.hpp.
Field Documentation
_inKnockBack
bool NullSessionAnticheat::_inKnockBack private
Definition at line 142 of file Anticheat.hpp.
Referenced by IsInKnockBack(), KnockBack(), and Movement().
_session
WorldSession* const NullSessionAnticheat::_session private
Definition at line 141 of file Anticheat.hpp.
Referenced by RecordCheat(), and SendCharEnum().
The documentation for this class was generated from the following file:
Anticheat.hpp