CMaNGOS_WoTLK: BattleGroundEY Class Reference
BattleGroundEY Class Reference
#include <BattleGroundEY.h>
Public Member Functions
BattleGroundEY ()
void Reset () override
Method that is called when no players remains in battleground.
void Update (uint32 diff) override
Update method.
void AddPlayer (Player *player) override
Method that is called when adding a player to the battleground.
void RemovePlayer (Player *player, ObjectGuid guid) override
Method that handles generic logic when removing a player.
void StartingEventOpenDoors () override
void EndBattleGround (Team winner) override
Method that ends battleground.
void UpdatePlayerScore (Player *source, uint32 type, uint32 value) override
Method that updates player score.
Team GetPrematureWinner () override
Function that returns the premature winner.
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
bool HandleAreaTrigger (Player *source, uint32 trigger) override
void HandleGameObjectCreate (GameObject *go) override
void HandleKillPlayer (Player *player, Player *killer) override
Method that handles killing players.
void HandlePlayerClickedOnFlag (Player *player, GameObject *go) override
void HandlePlayerDroppedFlag (Player *source) override
ObjectGuid const & GetFlagCarrierGuid () const
bool CheckAchievementCriteriaMeet (uint32 criteriaId, Player const *source, Unit const *target, uint32 miscvalue1) override
Public Member Functions inherited from BattleGround
BattleGround ()
virtual ~BattleGround ()
Deconstructor.
virtual void StartingEventCloseDoors ()
char const * GetName () const
BattleGroundTypeId GetTypeId (bool getRandom=false) const
BattleGroundBracketId GetBracketId () const
uint32 GetInstanceId () const
BattleGroundStatus GetStatus () const
uint32 GetClientInstanceId () const
uint32 GetStartTime () const
uint32 GetEndTime () const
uint32 GetMaxPlayers () const
uint32 GetMinPlayers () const
uint32 GetMinLevel () const
uint32 GetMaxLevel () const
uint32 GetMaxPlayersPerTeam () const
uint32 GetMinPlayersPerTeam () const
int32 GetStartDelayTime () const
ArenaType GetArenaType () const
BattleGroundWinner GetWinner () const
bool IsRandom () const
uint32 GetBattlemasterEntry () const
Function that returns the battleground master entry.
uint32 GetBonusHonorFromKill (uint32 kills) const
Method that calculates and rewars bonus honor from kill.
void SetName (char const *name)
void SetTypeId (BattleGroundTypeId typeId)
void SetRandomTypeId (BattleGroundTypeId typeId)
void SetBracket (PvPDifficultyEntry const *bracketEntry)
Method that sets the battleground bracket.
void SetStatus (BattleGroundStatus status)
void SetClientInstanceId (uint32 instanceId)
void SetStartTime (uint32 time)
void SetEndTime (uint32 time)
void SetMaxPlayers (uint32 maxPlayers)
void SetMinPlayers (uint32 minPlayers)
void SetLevelRange (uint32 min, uint32 max)
void SetRated (bool state)
void SetArenaType (ArenaType type)
void SetArenaorBGType (bool isArena)
void SetWinner (BattleGroundWinner winner)
void SetRandom (bool isRandom)
void ModifyStartDelayTime (int diff)
void SetStartDelayTime (int time)
void SetMaxPlayersPerTeam (uint32 maxPlayers)
void SetMinPlayersPerTeam (uint32 minPlayers)
void AddToBgFreeSlotQueue ()
Function that returns the number of players that can join a battleground based on the provided team.
void RemoveFromBgFreeSlotQueue ()
Method that removes this battleground from free queue - it must be called when deleting battleground.
void DecreaseInvitedCount (Team team)
void IncreaseInvitedCount (Team team)
uint32 GetInvitedCount (Team team) const
bool HasFreeSlots () const
uint32 GetFreeSlotsForTeam (Team team) const
Function that returns the number of players that can join a battleground based on the provided team.
bool IsArena () const
bool IsBattleGround () const
bool IsRated () const
BattleGroundPlayerMap const & GetPlayers () const
uint32 GetPlayersSize () const
BattleGroundScoreMap::const_iterator GetPlayerScoresBegin () const
BattleGroundScoreMap::const_iterator GetPlayerScoresEnd () const
uint32 GetPlayerScoresSize () const
void StartBattleGround ()
Method that starts the battleground.
GameObject * GetSingleGameObjectFromStorage (uint32 entry) const
Function that returns the gameobject pointer that was stored in m_goEntryGuidStore.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Function that returns pointer to a loaded Creature that was stored in m_goEntryGuidStore.
void SetMapId (uint32 mapId)
uint32 GetMapId () const
void SetBgMap (BattleGroundMap *map)
BattleGroundMap * GetBgMap () const
void SetTeamStartLoc (Team team, float x, float y, float z, float o)
Method that sets the team start location.
void GetTeamStartLoc (Team team, float &x, float &y, float &z, float &o) const
void SetStartMaxDist (float startMaxDist)
float GetStartMaxDist () const
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
void SendPacketToTeam (Team teamId, WorldPacket const &packet, Player *sender=nullptr, bool self=true)
Method that sends packet to the team.
void SendPacketToAll (WorldPacket const &packet)
Method that sends packet to all players.
template<class Do >
void BroadcastWorker (Do &_do)
void PlaySoundToTeam (uint32, Team)
Method that plays sound to the given team.
void PlaySoundToAll (uint32)
Method that plays sound to all players.
void CastSpellOnTeam (uint32, Team)
Method casts spell to an entire battleground team.
void RewardHonorToTeam (uint32, Team)
Method that rewards honor to team - called at the end of the battleground.
void RewardReputationToTeam (uint32, uint32, Team)
Method that rewards reputation to team - called at the end of the battleground.
void RewardMark (Player *, uint32)
Method that rewards battleground mark - called at the end of the battleground.
void SendRewardMarkByMail (Player *, uint32, uint32) const
Method that sends reward by mail - called at the end of the battleground.
void RewardItem (Player *, uint32, uint32)
Method that rewards item - called at the end of the battleground.
void RewardQuestComplete (Player *)
Method that rewards player quest complete - called at the end of the battleground.
void RewardSpellCast (Player *, uint32) const
Method that rewards spell cast - called at the end of the battleground.
void UpdateWorldState (uint32, uint32)
Method that updates world state for all players.
void UpdateWorldStateForPlayer (uint32, uint32, Player *) const
Method that updates world state for a give player.
void SendMessageToAll (int32, ChatMsg, Player const *source=nullptr)
Method that sends message to all players.
void SendMessageToAll (int32, ChatMsg, uint32, ObjectGuid)
Method that sends message to all players.
void PSendMessageToAll (int32, ChatMsg, Player const *,...)
Method that sends message to all players.
void SendMessage2ToAll (int32, ChatMsg, Player const *, int32 arg1=0, int32 arg2=0)
Method that sends message to all players.
void SendYellToAll (int32, uint32, Creature const *)
Method that sends yell to all players.
void SendYell2ToAll (int32, uint32, Creature const *, int32, int32)
Method that sends yell to all players.
void SendBcdToAll (int32 bcdEntry, ChatMsg msgtype, Creature const *source)
void SendBcdToTeam (int32 bcdEntry, ChatMsg msgtype, Creature const *source, Team team)
Group * GetBgRaid (Team team) const
void SetBgRaid (Team, Group *)
Method that sets battleground group as raid.
uint32 GetPlayersCountByTeam (Team team) const
uint32 GetAlivePlayersCountByTeam (Team) const
Function that counts the alive players by team.
void UpdatePlayersCountByTeam (Team team, bool remove)
void SetArenaTeamIdForTeam (Team team, uint32 arenaTeamId)
uint32 GetArenaTeamIdForTeam (Team team) const
void SetArenaTeamRatingChangeForTeam (Team team, int32 ratingChange)
int32 GetArenaTeamRatingChangeForTeam (Team team) const
void CheckArenaWinConditions ()
Method that checks arena win conditions.
virtual void HandleKillUnit (Creature *, Player *)
virtual void HandleCreatureCreate (Creature *)
virtual void HandleGameObjectDamaged (Player *, GameObject *, uint32)
void EventPlayerLoggedIn (Player *)
Method that handles players logging out from ongoing battlegrounds.
void EventPlayerLoggedOut (Player *)
Method that handles players logging out from ongoing battlegrounds.
void AddOrSetPlayerToCorrectBgGroup (Player *, ObjectGuid, Team)
Method that handles adding players to the correct BG group.
virtual void RemovePlayerAtLeave (ObjectGuid, bool, bool)
Method that handles player removal on leaving battleground.
void OnObjectDBLoad (Creature *)
Function that handles creature load from DB event map.
void OnObjectDBLoad (GameObject *)
Method that handles gameobject load from DB event map.
void SpawnEvent (uint8, uint8, bool)
Method that handles event spawn.
bool IsActiveEvent (uint8 event1, uint8 event2)
uint32 GetSingleCreatureGuid (uint8, uint8)
Function returns a creature guid from event map.
void OpenDoorEvent (uint8, uint8 event2=0)
Method that handles door opening.
bool IsDoorEvent (uint8, uint8) const
Function that checks if event handles doors.
void HandleTriggerBuff (ObjectGuid)
Method that handles buff triggering based on trap gameobjects.
void ChangeBgObjectSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground gameobject spawn state.
void ChangeBgCreatureSpawnState (uint32 dbGuid, uint32)
Method that changes the battleground creature spawn state.
void DoorOpen (uint32 dbGuid)
Method that handles opens doors.
void DoorClose (uint32 dbGuid)
Method that handles door closing.
virtual bool HandlePlayerUnderMap (Player *)
Team GetPlayerTeam (ObjectGuid)
Function that returns the team of the given player - used mainly in arenas.
bool IsPlayerInBattleGround (ObjectGuid)
Function that returns returns if player is in battleground.
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
void StartTimedAchievement (AchievementCriteriaTypes, uint32)
Method that starts timed achievements for all battleground players.
uint32 GetPlayerSkinRefLootId () const
void SetPlayerSkinRefLootId (uint32 reflootId)
virtual void AlterTeleportLocation (Player *player, ObjectGuid &transportGuid, float &x, float &y, float &z, float &ori)
Private Member Functions
void SetFlagCarrier (ObjectGuid guid)
void ClearFlagCarrier ()
bool IsFlagPickedUp () const
uint8 GetFlagState () const
void RespawnFlagAtCenter (bool wasCaptured)
void RespawnDroppedFlag ()
void ProcessCaptureEvent (GameObject *go, uint32 towerId, Team team, uint32 newWorldState, uint32 message)
void ProcessPlayerFlagScoreEvent (Player *source, EYNodes node)
bool AreAllNodesControlledByTeam (Team team)
void CheckVictory (Team team)
void UpdateResources ()
void AddPoints (Team team, uint32 points)
void SetFlagState (EYFlagState state)
void SetTowerOwner (EYNodes node, Team team)
Private Attributes
EYFlagState m_flagState
ObjectGuid m_flagCarrier
ObjectGuid m_droppedFlagGuid
uint32 m_mainFlagDbGuid
Team m_towerOwner [EY_MAX_NODES]
ObjectGuid m_towers [EY_MAX_NODES]
ObjectGuid m_spiritHealers [EY_MAX_NODES]
ObjectGuid m_honorableDefender [EY_MAX_NODES]
uint32 m_honorTicks
uint32 m_honorScoreTicks [PVP_TEAM_COUNT]
uint32 m_flagRespawnTimer
uint32 m_resourceUpdateTimer
uint32 m_felReaverFlagTimer
Friends
class BattleGroundMgr
Additional Inherited Members
Public Types inherited from BattleGround
typedef std::map< ObjectGuid, BattleGroundPlayer > BattleGroundPlayerMap
typedef std::map< ObjectGuid, BattleGroundScore * > BattleGroundScoreMap
typedef std::map< uint32, ObjectGuid > EntryGuidMap
Static Public Member Functions inherited from BattleGround
static void BlockMovement (Player *)
Method that blocks player movement - called at the end of battleground.
static Team GetOtherTeam (Team team)
static PvpTeamIndex GetOtherTeamIndex (PvpTeamIndex teamIdx)
Data Fields inherited from BattleGround
std::map< uint32, EventObjects > m_eventObjects
std::map< uint8, uint8 > m_activeEvents
Protected Member Functions inherited from BattleGround
void EndNow ()
Function that ends the battleground immediately.
void PlayerAddedToBgCheckIfBgIsRunning (Player *)
Method that handles player added to battleground when battleground is in progress.
Protected Attributes inherited from BattleGround
BattleGroundScoreMap m_playerScores
BattleGroundPlayerMap m_players
uint8 m_events
BattleGroundStartTimeIntervals m_startDelayTimes [BG_STARTING_EVENT_COUNT]
uint32 m_startMessageIds [BG_STARTING_EVENT_COUNT]
bool m_buffChange
bool m_isRandom
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
Detailed Description
Definition at line 294 of file BattleGroundEY.h.
Constructor & Destructor Documentation
BattleGroundEY()
BattleGroundEY::BattleGroundEY ()
Definition at line 32 of file BattleGroundEY.cpp.
References BG_STARTING_EVENT_FIRST, BG_STARTING_EVENT_FOURTH, BG_STARTING_EVENT_SECOND, BG_STARTING_EVENT_THIRD, LANG_BG_EY_HAS_BEGUN, LANG_BG_EY_START_HALF_MINUTE, LANG_BG_EY_START_ONE_MINUTE, and BattleGround::m_startMessageIds.
Member Function Documentation
AddPlayer()
void BattleGroundEY::AddPlayer (Player * player) override virtual
Method that is called when adding a player to the battleground.
Parameters
player
Reimplemented from BattleGround.
Definition at line 214 of file BattleGroundEY.cpp.
References BattleGround::AddPlayer(), Object::GetObjectGuid(), and BattleGround::m_playerScores.
AddPoints()
void BattleGroundEY::AddPoints (Team team, uint32 points) private
Definition at line 109 of file BattleGroundEY.cpp.
References ALLIANCE, BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), GetTeamIndexByTeamId(), Map::GetVariableManager(), m_honorScoreTicks, m_honorTicks, BattleGround::RewardHonorToTeam(), WorldStateVariableManager::SetVariable(), WORLD_STATE_EY_RESOURCES_ALLIANCE, and WORLD_STATE_EY_RESOURCES_HORDE.
Referenced by ProcessPlayerFlagScoreEvent(), and UpdateResources().
AreAllNodesControlledByTeam()
bool BattleGroundEY::AreAllNodesControlledByTeam (Team team) private
Definition at line 656 of file BattleGroundEY.cpp.
References m_towerOwner.
Referenced by CheckAchievementCriteriaMeet().
CheckAchievementCriteriaMeet()
bool BattleGroundEY::CheckAchievementCriteriaMeet (uint32 criteriaId, Player const * source, Unit const * target, uint32 miscvalue1) override virtual
Reimplemented from BattleGround.
Definition at line 665 of file BattleGroundEY.cpp.
References AreAllNodesControlledByTeam(), EY_ACHIEV_CRIT_DOMINATION, EY_ACHIEV_CRIT_STORM_GLORY, and Player::GetTeam().
CheckVictory()
void BattleGroundEY::CheckVictory (Team team) private
Definition at line 185 of file BattleGroundEY.cpp.
References ALLIANCE, EndBattleGround(), EY_MAX_TEAM_SCORE, BattleGround::GetBgMap(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), WORLD_STATE_EY_RESOURCES_ALLIANCE, and WORLD_STATE_EY_RESOURCES_HORDE.
Referenced by UpdateResources().
ClearFlagCarrier()
void BattleGroundEY::ClearFlagCarrier () inline private
Definition at line 330 of file BattleGroundEY.h.
References ObjectGuid::Clear(), and m_flagCarrier.
Referenced by HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), and RemovePlayer().
EndBattleGround()
void BattleGroundEY::EndBattleGround (Team winner) override virtual
Method that ends battleground.
Parameters
winner team
Reimplemented from BattleGround.
Definition at line 197 of file BattleGroundEY.cpp.
References ALLIANCE, BattleGround::EndBattleGround(), BattleGround::GetBgMap(), BattleGround::GetBonusHonorFromKill(), GO_JUST_DEACTIVATED, HORDE, m_towers, and BattleGround::RewardHonorToTeam().
Referenced by CheckVictory().
GetFlagCarrierGuid()
ObjectGuid const& BattleGroundEY::GetFlagCarrierGuid () const inline
Definition at line 322 of file BattleGroundEY.h.
References m_flagCarrier.
Referenced by HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), and Update().
GetFlagState()
uint8 BattleGroundEY::GetFlagState () const inline private
Definition at line 333 of file BattleGroundEY.h.
References m_flagState.
GetPrematureWinner()
Team BattleGroundEY::GetPrematureWinner () override virtual
Function that returns the premature winner.
Reimplemented from BattleGround.
Definition at line 677 of file BattleGroundEY.cpp.
References ALLIANCE, BattleGround::GetBgMap(), BattleGround::GetPrematureWinner(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), HORDE, WORLD_STATE_EY_RESOURCES_ALLIANCE, and WORLD_STATE_EY_RESOURCES_HORDE.
HandleAreaTrigger()
bool BattleGroundEY::HandleAreaTrigger (Player * source, uint32 trigger) override virtual
Reimplemented from BattleGround.
Definition at line 401 of file BattleGroundEY.cpp.
References AREATRIGGER_BLOOD_ELF_TOWER_POINT, AREATRIGGER_DRAENEI_RUINS_POINT, AREATRIGGER_FEL_REAVER_RUINS_POINT, AREATRIGGER_MAGE_TOWER_POINT, BattleGround::GetStatus(), Player::GetTeam(), Unit::IsAlive(), m_towerOwner, NODE_BLOOD_ELF_TOWER, NODE_DRAENEI_RUINS, NODE_FEL_REAVER_RUINS, NODE_MAGE_TOWER, ProcessPlayerFlagScoreEvent(), and STATUS_IN_PROGRESS.
HandleEvent()
bool BattleGroundEY::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from BattleGround.
Definition at line 275 of file BattleGroundEY.cpp.
References DEBUG_LOG, EVENT_NETHERSTORM_FLAG_SPELL, EY_MAX_NODES, eyTowerEvents, eyTowers, Object::GetEntry(), HandlePlayerClickedOnFlag(), Object::IsGameObject(), Object::IsPlayer(), and ProcessCaptureEvent().
HandleGameObjectCreate()
void BattleGroundEY::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 244 of file BattleGroundEY.cpp.
References CAPTURE_SLIDER_MIDDLE, Object::GetDbGuid(), Object::GetEntry(), Object::GetObjectGuid(), GO_CAPTURE_POINT_BLOOD_ELF_TOWER, GO_CAPTURE_POINT_DRAENEI_RUINS, GO_CAPTURE_POINT_FEL_REAVER_RUINS, GO_CAPTURE_POINT_MAGE_TOWER, GO_EY_NETHERSTORM_FLAG, GO_EY_NETHERSTORM_FLAG_DROP, m_droppedFlagGuid, m_mainFlagDbGuid, m_towers, NODE_BLOOD_ELF_TOWER, NODE_DRAENEI_RUINS, NODE_FEL_REAVER_RUINS, NODE_MAGE_TOWER, and GameObject::SetCapturePointSlider().
HandleKillPlayer()
void BattleGroundEY::HandleKillPlayer (Player * player, Player * killer) override virtual
Method that handles killing players.
also handles generic logic for arena updates
Parameters
victim player
killer player
Reimplemented from BattleGround.
Definition at line 518 of file BattleGroundEY.cpp.
References BattleGround::GetStatus(), BattleGround::HandleKillPlayer(), HandlePlayerDroppedFlag(), and STATUS_IN_PROGRESS.
HandlePlayerClickedOnFlag()
void BattleGroundEY::HandlePlayerClickedOnFlag (Player * player, GameObject * go) override virtual
Reimplemented from BattleGround.
Definition at line 559 of file BattleGroundEY.cpp.
References ALLIANCE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, DEBUG_LOG, EY_FLAG_STATE_ON_ALLIANCE_PLAYER, EY_FLAG_STATE_ON_HORDE_PLAYER, EY_SOUND_FLAG_PICKED_UP_ALLIANCE, EY_SOUND_FLAG_PICKED_UP_HORDE, Object::GetEntry(), WorldObject::GetName(), Object::GetObjectGuid(), BattleGround::GetStatus(), Player::GetTeam(), GO_JUST_DEACTIVATED, HORDE, IsFlagPickedUp(), WorldObject::IsWithinDistInMap(), LANG_BG_EY_HAS_TAKEN_FLAG, BattleGround::PlaySoundToAll(), BattleGround::PSendMessageToAll(), Unit::RemoveAurasWithInterruptFlags(), SetFlagCarrier(), SetFlagState(), GameObject::SetLootState(), and STATUS_IN_PROGRESS.
Referenced by HandleEvent().
HandlePlayerDroppedFlag()
void BattleGroundEY::HandlePlayerDroppedFlag (Player * source) override virtual
Reimplemented from BattleGround.
Definition at line 530 of file BattleGroundEY.cpp.
References ALLIANCE, Unit::CastSpell(), CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, ClearFlagCarrier(), DEBUG_LOG, EY_FLAG_RESPAWN_TIME, EY_FLAG_STATE_ON_GROUND, EY_SPELL_NETHERSTORM_FLAG, EY_SPELL_PLAYER_DROPPED_FLAG, GetFlagCarrierGuid(), Object::GetObjectGuid(), BattleGround::GetStatus(), Player::GetTeam(), IsFlagPickedUp(), LANG_BG_EY_DROPPED_FLAG, m_flagRespawnTimer, Unit::RemoveAurasDueToSpell(), BattleGround::SendMessageToAll(), SetFlagState(), SPELL_RECENTLY_DROPPED_FLAG, STATUS_IN_PROGRESS, and TRIGGERED_OLD_TRIGGERED.
Referenced by HandleKillPlayer(), and RemovePlayer().
IsFlagPickedUp()
bool BattleGroundEY::IsFlagPickedUp () const inline private
Definition at line 332 of file BattleGroundEY.h.
References ObjectGuid::IsEmpty(), and m_flagCarrier.
Referenced by HandlePlayerClickedOnFlag(), HandlePlayerDroppedFlag(), RemovePlayer(), and Update().
ProcessCaptureEvent()
void BattleGroundEY::ProcessCaptureEvent (GameObject * go, uint32 towerId, Team team, uint32 newWorldState, uint32 message) private
Definition at line 314 of file BattleGroundEY.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, ALLIANCE, BG_NPC_HON_DEFENDER_TRIGGER_A, BG_NPC_HON_DEFENDER_TRIGGER_H, BG_NPC_SPIRIT_GUIDE_ALLIANCE, BG_NPC_SPIRIT_GUIDE_HORDE, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, DEBUG_LOG, EY_ZONE_ID_MAIN, eyeGraveyardData, eyeTowerdData, BattleGround::GetBgMap(), GetClosestCreatureWithEntry(), Object::GetEntry(), Map::GetGraveyardManager(), Map::GetVariableManager(), HORDE, m_honorableDefender, m_spiritHealers, m_towerOwner, EyeSummonData::o, UnitAI::SendAIEvent(), BattleGround::SendMessageToAll(), GraveyardManager::SetGraveYardLinkTeam(), SetTowerOwner(), WorldStateVariableManager::SetVariable(), BattleGround::SpawnEvent(), WorldObject::SummonCreature(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_INDEX_NEUTRAL, TEAM_INVALID, TEAM_NONE, TEMPSPAWN_DEAD_DESPAWN, WORLD_STATE_EY_TOWER_COUNT_ALLIANCE, WORLD_STATE_EY_TOWER_COUNT_HORDE, EyeSummonData::x, EyeSummonData::y, and EyeSummonData::z.
Referenced by HandleEvent().
ProcessPlayerFlagScoreEvent()
void BattleGroundEY::ProcessPlayerFlagScoreEvent (Player * source, EYNodes node) private
Definition at line 596 of file BattleGroundEY.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, AddPoints(), ALLIANCE, AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, CHAT_MSG_BG_SYSTEM_ALLIANCE, CHAT_MSG_BG_SYSTEM_HORDE, ClearFlagCarrier(), DEBUG_LOG, EY_EVENT_CAPTURE_FLAG, EY_FLAG_RESPAWN_TIME, EY_FLAG_STATE_WAIT_RESPAWN, EY_SOUND_FLAG_CAPTURED_ALLIANCE, EY_SOUND_FLAG_CAPTURED_HORDE, EY_SPELL_NETHERSTORM_FLAG, eyFlagPoints, BattleGround::GetBgMap(), GetFlagCarrierGuid(), Object::GetObjectGuid(), BattleGround::GetStatus(), Player::GetTeam(), HORDE, LANG_BG_EY_CAPTURED_FLAG_A, LANG_BG_EY_CAPTURED_FLAG_H, m_flagRespawnTimer, BattleGround::PlaySoundToAll(), Unit::RemoveAurasDueToSpell(), Unit::RemoveAurasWithInterruptFlags(), SCORE_FLAG_CAPTURES, BattleGround::SendMessageToAll(), SetFlagState(), BattleGround::SpawnEvent(), STATUS_IN_PROGRESS, Player::UpdateAchievementCriteria(), UpdatePlayerScore(), WORLD_STATE_EY_TOWER_COUNT_ALLIANCE, and WORLD_STATE_EY_TOWER_COUNT_HORDE.
Referenced by HandleAreaTrigger(), and Update().
RemovePlayer()
void BattleGroundEY::RemovePlayer (Player * , ObjectGuid) override virtual
Method that handles generic logic when removing a player.
used mainly for arena logic
Parameters
player
guid
Reimplemented from BattleGround.
Definition at line 224 of file BattleGroundEY.cpp.
References ClearFlagCarrier(), HandlePlayerDroppedFlag(), IsFlagPickedUp(), m_flagCarrier, RespawnFlagAtCenter(), and sLog.
Reset()
void BattleGroundEY::Reset () override virtual
Method that is called when no players remains in battleground.
Reimplemented from BattleGround.
Definition at line 433 of file BattleGroundEY.cpp.
References ALLIANCE, ObjectGuid::Clear(), EY_EVENT2_FLAG_CENTER, EY_EVENT_CAPTURE_FLAG, EY_FLAG_STATE_ON_BASE, EY_MAX_NODES, EY_NORMAL_HONOR_INTERVAL, EY_WEEKEND_HONOR_INTERVAL, EY_ZONE_ID_MAIN, eyeGraveyardData, eyTowerEvents, BattleGround::GetBgMap(), Map::GetGraveyardManager(), BattleGround::GetTypeId(), Map::GetVariableManager(), GRAVEYARD_EY_MAIN_ALLIANCE, GRAVEYARD_EY_MAIN_HORDE, HORDE, BattleGroundMgr::IsBgWeekend(), BattleGround::m_activeEvents, m_droppedFlagGuid, m_felReaverFlagTimer, m_flagCarrier, m_flagRespawnTimer, m_honorScoreTicks, m_honorTicks, m_resourceUpdateTimer, BattleGround::Reset(), SetFlagState(), GraveyardManager::SetGraveYardLinkTeam(), SetTowerOwner(), WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, TEAM_INDEX_NEUTRAL, TEAM_INVALID, TEAM_NONE, WORLD_STATE_EY_CAPTURE_POINT_SLIDER_DISPLAY, WORLD_STATE_EY_NETHERSTORM_FLAG_READY, WORLD_STATE_EY_NETHERSTORM_FLAG_STATE_ALLIANCE, WORLD_STATE_EY_NETHERSTORM_FLAG_STATE_HORDE, WORLD_STATE_EY_RESOURCES_ALLIANCE, WORLD_STATE_EY_RESOURCES_HORDE, WORLD_STATE_EY_TOWER_COUNT_ALLIANCE, WORLD_STATE_EY_TOWER_COUNT_HORDE, and WORLD_STATE_REMOVE.
RespawnDroppedFlag()
void BattleGroundEY::RespawnDroppedFlag () private
Definition at line 508 of file BattleGroundEY.cpp.
References ObjectGuid::Clear(), BattleGround::GetBgMap(), GO_JUST_DEACTIVATED, m_droppedFlagGuid, and RespawnFlagAtCenter().
Referenced by Update().
RespawnFlagAtCenter()
void BattleGroundEY::RespawnFlagAtCenter (bool wasCaptured) private
Definition at line 490 of file BattleGroundEY.cpp.
References BattleGround::ChangeBgObjectSpawnState(), CHAT_MSG_BG_SYSTEM_NEUTRAL, DEBUG_LOG, EY_EVENT2_FLAG_CENTER, EY_EVENT_CAPTURE_FLAG, EY_FLAG_STATE_ON_BASE, EY_SOUND_FLAG_RESET, LANG_BG_EY_RESETED_FLAG, m_mainFlagDbGuid, BattleGround::PlaySoundToAll(), RESPAWN_IMMEDIATELY, BattleGround::SendMessageToAll(), SetFlagState(), and BattleGround::SpawnEvent().
Referenced by RemovePlayer(), RespawnDroppedFlag(), and Update().
SetFlagCarrier()
void BattleGroundEY::SetFlagCarrier (ObjectGuid guid) inline private
Definition at line 329 of file BattleGroundEY.h.
References m_flagCarrier.
Referenced by HandlePlayerClickedOnFlag().
SetFlagState()
void BattleGroundEY::SetFlagState (EYFlagState state) private
Definition at line 123 of file BattleGroundEY.cpp.
References EY_FLAG_STATE_ON_ALLIANCE_PLAYER, EY_FLAG_STATE_ON_BASE, EY_FLAG_STATE_ON_HORDE_PLAYER, BattleGround::GetBgMap(), Map::GetVariableManager(), m_flagState, WorldStateVariableManager::SetVariable(), WORLD_STATE_EY_NETHERSTORM_FLAG_READY, WORLD_STATE_EY_NETHERSTORM_FLAG_STATE_ALLIANCE, and WORLD_STATE_EY_NETHERSTORM_FLAG_STATE_HORDE.
Referenced by HandlePlayerClickedOnFlag(), HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), Reset(), and RespawnFlagAtCenter().
SetTowerOwner()
void BattleGroundEY::SetTowerOwner (EYNodes node, Team team) private
Definition at line 132 of file BattleGroundEY.cpp.
References ALLIANCE, BattleGround::GetBgMap(), Map::GetVariableManager(), HORDE, m_towerOwner, NODE_BLOOD_ELF_TOWER, NODE_DRAENEI_RUINS, NODE_FEL_REAVER_RUINS, NODE_MAGE_TOWER, WorldStateVariableManager::SetVariable(), TEAM_NONE, WORLD_STATE_EY_BLOOD_ELF_TOWER_ALLIANCE, WORLD_STATE_EY_BLOOD_ELF_TOWER_HORDE, WORLD_STATE_EY_BLOOD_ELF_TOWER_NEUTRAL, WORLD_STATE_EY_DRAENEI_RUINS_ALLIANCE, WORLD_STATE_EY_DRAENEI_RUINS_HORDE, WORLD_STATE_EY_DRAENEI_RUINS_NEUTRAL, WORLD_STATE_EY_FEL_REAVER_RUINS_ALLIANCE, WORLD_STATE_EY_FEL_REAVER_RUINS_HORDE, WORLD_STATE_EY_FEL_REAVER_RUINS_NEUTRAL, WORLD_STATE_EY_MAGE_TOWER_ALLIANCE, WORLD_STATE_EY_MAGE_TOWER_HORDE, and WORLD_STATE_EY_MAGE_TOWER_NEUTRAL.
Referenced by ProcessCaptureEvent(), and Reset().
StartingEventOpenDoors()
void BattleGroundEY::StartingEventOpenDoors () override virtual
Reimplemented from BattleGround.
Definition at line 96 of file BattleGroundEY.cpp.
References ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ALLIANCE, BG_EVENT_DOOR, EY_TIMED_ACHIEV_FLURRY, EY_ZONE_ID_MAIN, BattleGround::GetBgMap(), Map::GetGraveyardManager(), GRAVEYARD_EY_MAIN_ALLIANCE, GRAVEYARD_EY_MAIN_HORDE, HORDE, BattleGround::OpenDoorEvent(), GraveyardManager::SetGraveYardLinkTeam(), and BattleGround::StartTimedAchievement().
Update()
void BattleGroundEY::Update (uint32 diff) override virtual
Update method.
Parameters
diff
Reimplemented from BattleGround.
Definition at line 41 of file BattleGroundEY.cpp.
References EY_FEL_REAVER_FLAG_UPDATE_TIME, EY_FLAG_STATE_ON_GROUND, EY_FLAG_STATE_WAIT_RESPAWN, EY_RESOURCES_UPDATE_TIME, GetFlagCarrierGuid(), BattleGround::GetStatus(), Player::GetTeam(), IsFlagPickedUp(), WorldObject::IsWithinDist3d(), m_felReaverFlagTimer, m_flagRespawnTimer, m_flagState, m_resourceUpdateTimer, m_towerOwner, NODE_FEL_REAVER_RUINS, ProcessPlayerFlagScoreEvent(), RespawnDroppedFlag(), RespawnFlagAtCenter(), sObjectMgr, STATUS_IN_PROGRESS, BattleGround::Update(), and UpdateResources().
UpdatePlayerScore()
void BattleGroundEY::UpdatePlayerScore (Player * player, uint32 type, uint32 value) override virtual
Method that updates player score.
Parameters
player
type
value
Reimplemented from BattleGround.
Definition at line 639 of file BattleGroundEY.cpp.
References Object::GetObjectGuid(), BattleGround::m_playerScores, SCORE_FLAG_CAPTURES, and BattleGround::UpdatePlayerScore().
Referenced by ProcessPlayerFlagScoreEvent().
UpdateResources()
void BattleGroundEY::UpdateResources () private
Definition at line 169 of file BattleGroundEY.cpp.
References AddPoints(), ALLIANCE, CheckVictory(), eyTickPoints, BattleGround::GetBgMap(), HORDE, WORLD_STATE_EY_TOWER_COUNT_ALLIANCE, and WORLD_STATE_EY_TOWER_COUNT_HORDE.
Referenced by Update().
Friends And Related Function Documentation
BattleGroundMgr
friend class BattleGroundMgr friend
Definition at line 296 of file BattleGroundEY.h.
Field Documentation
m_droppedFlagGuid
ObjectGuid BattleGroundEY::m_droppedFlagGuid private
Definition at line 352 of file BattleGroundEY.h.
Referenced by HandleGameObjectCreate(), Reset(), and RespawnDroppedFlag().
m_felReaverFlagTimer
uint32 BattleGroundEY::m_felReaverFlagTimer private
Definition at line 365 of file BattleGroundEY.h.
Referenced by Reset(), and Update().
m_flagCarrier
ObjectGuid BattleGroundEY::m_flagCarrier private
Definition at line 351 of file BattleGroundEY.h.
Referenced by ClearFlagCarrier(), GetFlagCarrierGuid(), IsFlagPickedUp(), RemovePlayer(), Reset(), and SetFlagCarrier().
m_flagRespawnTimer
uint32 BattleGroundEY::m_flagRespawnTimer private
Definition at line 363 of file BattleGroundEY.h.
Referenced by HandlePlayerDroppedFlag(), ProcessPlayerFlagScoreEvent(), Reset(), and Update().
m_flagState
EYFlagState BattleGroundEY::m_flagState private
Definition at line 350 of file BattleGroundEY.h.
Referenced by GetFlagState(), SetFlagState(), and Update().
m_honorableDefender
ObjectGuid BattleGroundEY::m_honorableDefender[EY_MAX_NODES] private
Definition at line 358 of file BattleGroundEY.h.
Referenced by ProcessCaptureEvent().
m_honorScoreTicks
uint32 BattleGroundEY::m_honorScoreTicks[PVP_TEAM_COUNT] private
Definition at line 361 of file BattleGroundEY.h.
Referenced by AddPoints(), and Reset().
m_honorTicks
uint32 BattleGroundEY::m_honorTicks private
Definition at line 360 of file BattleGroundEY.h.
Referenced by AddPoints(), and Reset().
m_mainFlagDbGuid
uint32 BattleGroundEY::m_mainFlagDbGuid private
Definition at line 353 of file BattleGroundEY.h.
Referenced by HandleGameObjectCreate(), and RespawnFlagAtCenter().
m_resourceUpdateTimer
uint32 BattleGroundEY::m_resourceUpdateTimer private
Definition at line 364 of file BattleGroundEY.h.
Referenced by Reset(), and Update().
m_spiritHealers
ObjectGuid BattleGroundEY::m_spiritHealers[EY_MAX_NODES] private
Definition at line 357 of file BattleGroundEY.h.
Referenced by ProcessCaptureEvent().
m_towerOwner
Team BattleGroundEY::m_towerOwner[EY_MAX_NODES] private
Definition at line 355 of file BattleGroundEY.h.
Referenced by AreAllNodesControlledByTeam(), HandleAreaTrigger(), ProcessCaptureEvent(), SetTowerOwner(), and Update().
m_towers
ObjectGuid BattleGroundEY::m_towers[EY_MAX_NODES] private
Definition at line 356 of file BattleGroundEY.h.
Referenced by EndBattleGround(), and HandleGameObjectCreate().
The documentation for this class was generated from the following files:
BattleGroundEY.h
BattleGroundEY.cpp