CMaNGOS_WoTLK: GridCrawler Class Reference
GridCrawler Class Reference
#include <MapWorkers.h>
Public Member Functions
GridCrawler (Map &map, std::vector< Cell > &cells, uint32 diff, MapUpdater &updater)
void execute () override
Public Member Functions inherited from Worker
Worker (MapUpdater &updater)
virtual ~Worker ()=default
Private Attributes
Map & m_map
std::vector< Cell > & m_cells
uint32 m_diff
Additional Inherited Members
Protected Member Functions inherited from Worker
MapUpdater & GetWorker ()
Detailed Description
Definition at line 61 of file MapWorkers.h.
Constructor & Destructor Documentation
GridCrawler()
GridCrawler::GridCrawler (Map & map, std::vector< Cell > & cells, uint32 diff, MapUpdater & updater) inline
Definition at line 64 of file MapWorkers.h.
Member Function Documentation
execute()
void GridCrawler::execute () inline override virtual
Reimplemented from Worker.
Definition at line 68 of file MapWorkers.h.
References Worker::GetWorker(), m_cells, m_diff, m_map, MapUpdater::update_finished(), and Map::Visit().
Field Documentation
m_cells
std::vector<Cell>& GridCrawler::m_cells private
Definition at line 86 of file MapWorkers.h.
Referenced by execute().
m_diff
uint32 GridCrawler::m_diff private
Definition at line 87 of file MapWorkers.h.
Referenced by execute().
m_map
Map& GridCrawler::m_map private
Definition at line 85 of file MapWorkers.h.
Referenced by execute().
The documentation for this class was generated from the following file:
MapWorkers.h