CMaNGOS_WoTLK: MaNGOS::BattleGroundBroadcastBuilder Class Reference
MaNGOS::BattleGroundBroadcastBuilder Class Reference
Public Member Functions
BattleGroundBroadcastBuilder (BroadcastText const *bcd, ChatMsg msgtype, Creature const *source, Unit const *target)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
ChatMsg i_msgtype
Creature const * i_source
BroadcastText const * i_bcd
Unit const * i_target
Detailed Description
Definition at line 136 of file BattleGround.cpp.
Constructor & Destructor Documentation
BattleGroundBroadcastBuilder()
MaNGOS::BattleGroundBroadcastBuilder::BattleGroundBroadcastBuilder (BroadcastText const * bcd, ChatMsg msgtype, Creature const * source, Unit const * target) inline
Definition at line 139 of file BattleGround.cpp.
Member Function Documentation
operator()()
void MaNGOS::BattleGroundBroadcastBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 141 of file BattleGround.cpp.
References ChatHandler::BuildChatPacket(), CHAT_TAG_NONE, GENDER_NONE, Unit::getGender(), WorldObject::GetName(), Object::GetObjectGuid(), BroadcastText::GetText(), i_bcd, i_msgtype, i_source, i_target, and BroadcastText::languageId.
Field Documentation
i_bcd
BroadcastText const* MaNGOS::BattleGroundBroadcastBuilder::i_bcd private
Definition at line 148 of file BattleGround.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::BattleGroundBroadcastBuilder::i_msgtype private
Definition at line 146 of file BattleGround.cpp.
Referenced by operator()().
i_source
Creature const* MaNGOS::BattleGroundBroadcastBuilder::i_source private
Definition at line 147 of file BattleGround.cpp.
Referenced by operator()().
i_target
Unit const* MaNGOS::BattleGroundBroadcastBuilder::i_target private
Definition at line 149 of file BattleGround.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
BattleGround.cpp