CMaNGOS_WoTLK: MaNGOS::EmoteChatBuilder Class Reference
MaNGOS::EmoteChatBuilder Class Reference
Public Member Functions
EmoteChatBuilder (Player const &pl, uint32 text_emote, uint32 emote_num, Unit const *target)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
Player const & i_player
uint32 i_text_emote
uint32 i_emote_num
Unit const * i_target
Detailed Description
Definition at line 622 of file ChatHandler.cpp.
Constructor & Destructor Documentation
EmoteChatBuilder()
MaNGOS::EmoteChatBuilder::EmoteChatBuilder (Player const & pl, uint32 text_emote, uint32 emote_num, Unit const * target) inline
Definition at line 625 of file ChatHandler.cpp.
Member Function Documentation
operator()()
void MaNGOS::EmoteChatBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 628 of file ChatHandler.cpp.
References ByteBuffer::append(), WorldObject::GetNameForLocaleIdx(), Object::GetObjectGuid(), i_emote_num, i_player, i_target, i_text_emote, WorldPacket::Initialize(), and SMSG_TEXT_EMOTE.
Field Documentation
i_emote_num
uint32 MaNGOS::EmoteChatBuilder::i_emote_num private
Definition at line 647 of file ChatHandler.cpp.
Referenced by operator()().
i_player
Player const& MaNGOS::EmoteChatBuilder::i_player private
Definition at line 645 of file ChatHandler.cpp.
Referenced by operator()().
i_target
Unit const* MaNGOS::EmoteChatBuilder::i_target private
Definition at line 648 of file ChatHandler.cpp.
Referenced by operator()().
i_text_emote
uint32 MaNGOS::EmoteChatBuilder::i_text_emote private
Definition at line 646 of file ChatHandler.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
ChatHandler.cpp