CMaNGOS_WoTLK: Referencable< Countable > Class Template Reference
Referencable< Countable > Class Template Reference
#include <GridMap.h>
Public Member Functions
Referencable ()
void AddRef ()
bool Release ()
bool IsReferenced () const
Private Member Functions
Referencable (const Referencable &)
Referencable & operator= (const Referencable &)
Private Attributes
Countable m_count
Detailed Description
template<typename Countable>
class Referencable< Countable >
Definition at line 122 of file GridMap.h.
Constructor & Destructor Documentation
Referencable() [1/2]
template<typename Countable > Referencable< Countable >::Referencable () inline
Definition at line 125 of file GridMap.h.
References Referencable< Countable >::m_count.
Referencable() [2/2]
template<typename Countable > Referencable< Countable >::Referencable (const Referencable< Countable > &) private
Member Function Documentation
AddRef()
template<typename Countable > void Referencable< Countable >::AddRef () inline
Definition at line 127 of file GridMap.h.
References Referencable< Countable >::m_count.
Referenced by Map::Initialize().
IsReferenced()
template<typename Countable > bool Referencable< Countable >::IsReferenced () const inline
Definition at line 129 of file GridMap.h.
References Referencable< Countable >::m_count.
Referenced by TerrainManager::UnloadTerrain().
operator=()
template<typename Countable > Referencable& Referencable< Countable >::operator= (const Referencable< Countable > &) private
Release()
template<typename Countable > bool Referencable< Countable >::Release () inline
Definition at line 128 of file GridMap.h.
References Referencable< Countable >::m_count.
Referenced by Map::~Map().
Field Documentation
m_count
template<typename Countable > Countable Referencable< Countable >::m_count private
Definition at line 135 of file GridMap.h.
Referenced by Referencable< Countable >::AddRef(), Referencable< Countable >::IsReferenced(), Referencable< Countable >::Referencable(), and Referencable< Countable >::Release().
The documentation for this class was generated from the following file:
GridMap.h