CMaNGOS_WoTLK: Guild Class Reference
Guild Class Reference
#include <Guild.h>
Public Types
typedef std::unordered_map< uint32, MemberSlot > MemberList
typedef std::vector< RankInfo > RankList
Public Member Functions
Guild ()
~Guild ()
bool Create (Player *leader, std::string gname)
void CreateDefaultGuildRanks (int locale_idx)
void Disband ()
Disband guild including cleanup structures and DB.
void DeleteGuildBankItems (bool alsoInDB=false)
uint32 GetId () const
ObjectGuid GetLeaderGuid () const
std::string const & GetName () const
std::string const & GetMOTD () const
std::string const & GetGINFO () const
time_t GetCreatedDate () const
uint32 GetEmblemStyle () const
uint32 GetEmblemColor () const
uint32 GetBorderStyle () const
uint32 GetBorderColor () const
uint32 GetBackgroundColor () const
void SetLeader (ObjectGuid guid)
bool AddMember (ObjectGuid plGuid, uint32 plRank)
bool DelMember (ObjectGuid guid, bool isDisbanding=false)
Remove character from guild.
uint32 GetLowestRank () const
void SetMOTD (std::string motd)
void SetGINFO (std::string ginfo)
void SetEmblem (uint32 emblemStyle, uint32 emblemColor, uint32 borderStyle, uint32 borderColor, uint32 backgroundColor)
uint32 GetMemberSize () const
uint32 GetAccountsNumber ()
Return the number of accounts that are in the guild after possible update if required A player may have many characters in the guild, but with the same account.
bool LoadGuildFromDB (QueryResult *guildDataResult)
bool CheckGuildStructure ()
bool LoadRanksFromDB (QueryResult *guildRanksResult)
bool LoadMembersFromDB (QueryResult *guildMembersResult)
void BroadcastToGuild (WorldSession *session, const std::string &msg, uint32 language=LANG_UNIVERSAL)
void BroadcastToOfficers (WorldSession *session, const std::string &msg, uint32 language=LANG_UNIVERSAL)
void BroadcastPacketToRank (WorldPacket const &packet, uint32 rankId)
void BroadcastPacket (WorldPacket const &packet)
void MassInviteToEvent (WorldSession *session, uint32 minLevel, uint32 maxLevel, uint32 minRank)
void BroadcastEvent (GuildEvents event, ObjectGuid guid, char const *str1=nullptr, char const *str2=nullptr, char const *str3=nullptr)
void BroadcastEvent (GuildEvents event, char const *str1=nullptr, char const *str2=nullptr, char const *str3=nullptr)
template<class Do >
void BroadcastWorker (Do &_do, Player *except=nullptr)
void CreateRank (std::string name_, uint32 rights)
void DelRank ()
std::string GetRankName (uint32 rankId)
uint32 GetRankRights (uint32 rankId)
uint32 GetRanksSize () const
void SetRankName (uint32 rankId, std::string name_)
void SetRankRights (uint32 rankId, uint32 rights)
bool HasRankRight (uint32 rankId, uint32 right)
int32 GetRank (ObjectGuid guid)
MemberSlot * GetMemberSlot (ObjectGuid guid)
MemberSlot * GetMemberSlot (const std::string &name)
void Roster (WorldSession *session=nullptr)
void Query (WorldSession *session)
void LoadGuildEventLogFromDB ()
void DisplayGuildEventLog (WorldSession *session)
void LogGuildEvent (uint8 EventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2=ObjectGuid(), uint8 newRank=0)
ObjectGuid GetGuildInviter (ObjectGuid playerGuid) const
void DisplayGuildBankContent (WorldSession *session, uint8 TabId)
void DisplayGuildBankMoneyUpdate (WorldSession *session)
void SwapItems (Player *pl, uint8 BankTab, uint8 BankTabSlot, uint8 BankTabDst, uint8 BankTabSlotDst, uint32 SplitedAmount)
void MoveFromBankToChar (Player *pl, uint8 BankTab, uint8 BankTabSlot, uint8 PlayerBag, uint8 PlayerSlot, uint32 SplitedAmount)
void MoveFromCharToBank (Player *pl, uint8 PlayerBag, uint8 PlayerSlot, uint8 BankTab, uint8 BankTabSlot, uint32 SplitedAmount)
void DisplayGuildBankTabsInfo (WorldSession *session)
void CreateNewBankTab ()
void SetGuildBankTabText (uint8 TabId, std::string text)
void SendGuildBankTabText (WorldSession *session, uint8 TabId)
void SetGuildBankTabInfo (uint8 TabId, std::string Name, std::string Icon)
uint8 GetPurchasedTabs () const
uint32 GetBankRights (uint32 rankId, uint8 TabId) const
bool IsMemberHaveRights (uint32 LowGuid, uint8 TabId, uint32 rights) const
void LoadGuildBankFromDB ()
void SendMoneyInfo (WorldSession *session, uint32 LowGuid)
bool MemberMoneyWithdraw (uint32 amount, uint32 LowGuid)
uint64 GetGuildBankMoney () const
void SetBankMoney (int64 money)
bool MemberItemWithdraw (uint8 TabId, uint32 LowGuid)
uint32 GetMemberSlotWithdrawRem (uint32 LowGuid, uint8 TabId)
uint32 GetMemberMoneyWithdrawRem (uint32 LowGuid)
void SetBankMoneyPerDay (uint32 rankId, uint32 money)
void SetBankRightsAndSlots (uint32 rankId, uint8 TabId, uint32 right, uint32 nbSlots, bool db)
uint32 GetBankMoneyPerDay (uint32 rankId)
uint32 GetBankSlotPerDay (uint32 rankId, uint8 TabId)
bool LoadBankRightsFromDB (QueryResult *guildBankTabRightsResult)
void LoadGuildBankEventLogFromDB ()
void DisplayGuildBankLogs (WorldSession *session, uint8 TabId)
void LogBankEvent (uint8 EventType, uint8 TabId, uint32 PlayerGuidLow, uint32 ItemOrMoney, uint8 ItemStackCount=0, uint8 DestTabId=0)
bool AddGBankItemToDB (uint32 GuildId, uint32 BankTab, uint32 BankTabSlot, uint32 GUIDLow, uint32 Entry) const
Protected Types
typedef std::list< GuildEventLogEntry > GuildEventLog
These are actually ordered lists.
typedef std::list< GuildBankEventLogEntry > GuildBankEventLog
Protected Member Functions
void AddRank (const std::string &name_, uint32 rights, uint32 money)
Protected Attributes
uint32 m_Id
std::string m_Name
ObjectGuid m_LeaderGuid
std::string MOTD
std::string GINFO
time_t m_CreatedDate
uint32 m_EmblemStyle
uint32 m_EmblemColor
uint32 m_BorderStyle
uint32 m_BorderColor
uint32 m_BackgroundColor
uint32 m_accountsNumber
RankList m_Ranks
MemberList members
std::vector< GuildBankTab > m_TabList
GuildEventLog m_GuildEventLog
GuildBankEventLog m_GuildBankEventLog_Money
GuildBankEventLog m_GuildBankEventLog_Item [GUILD_BANK_MAX_TABS]
uint32 m_GuildEventLogNextGuid
uint32 m_GuildBankEventLogNextGuid_Money
uint32 m_GuildBankEventLogNextGuid_Item [GUILD_BANK_MAX_TABS]
uint64 m_GuildBankMoney
Private Member Functions
void UpdateAccountsNumber ()
Item * GetItem (uint8 TabId, uint8 SlotId)
InventoryResult CanStoreItem (uint8 tab, uint8 slot, GuildItemPosCountVec &dest, uint32 count, Item *pItem, bool swap=false) const
Item * StoreItem (uint8 tabId, GuildItemPosCountVec const &dest, Item *pItem)
void RemoveItem (uint8 tab, uint8 slot)
void DisplayGuildBankContentUpdate (uint8 TabId, int32 slot1, int32 slot2=-1)
void DisplayGuildBankContentUpdate (uint8 TabId, GuildItemPosCountVec const &slots)
void AppendDisplayGuildBankSlot (WorldPacket &data, GuildBankTab const &tab, int32 slot) const
InventoryResult _CanStoreItem_InSpecificSlot (uint8 tab, uint8 slot, GuildItemPosCountVec &dest, uint32 &count, bool swap, Item *pSrcItem) const
InventoryResult _CanStoreItem_InTab (uint8 tab, GuildItemPosCountVec &dest, uint32 &count, bool merge, Item *pSrcItem, uint8 skip_slot) const
Item * _StoreItem (uint8 tab, uint8 slot, Item *pItem, uint32 count, bool clone)
Detailed Description
Definition at line 297 of file Guild.h.
Member Typedef Documentation
GuildBankEventLog
typedef std::list<GuildBankEventLogEntry> Guild::GuildBankEventLog protected
Definition at line 474 of file Guild.h.
GuildEventLog
typedef std::list<GuildEventLogEntry> Guild::GuildEventLog protected
These are actually ordered lists.
The first element is the oldest entry.
Definition at line 473 of file Guild.h.
MemberList
typedef std::unordered_map<uint32, MemberSlot> Guild::MemberList
Definition at line 308 of file Guild.h.
RankList
typedef std::vector<RankInfo> Guild::RankList
Definition at line 309 of file Guild.h.
Constructor & Destructor Documentation
Guild()
Guild::Guild ()
Definition at line 82 of file Guild.cpp.
References GINFO, m_accountsNumber, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_CreatedDate, m_EmblemColor, m_EmblemStyle, m_GuildBankEventLogNextGuid_Item, m_GuildBankEventLogNextGuid_Money, m_GuildBankMoney, m_GuildEventLogNextGuid, m_Id, m_Name, and MOTD.
~Guild()
Guild::~Guild ()
Definition at line 105 of file Guild.cpp.
References DeleteGuildBankItems().
Member Function Documentation
_CanStoreItem_InSpecificSlot()
InventoryResult Guild::_CanStoreItem_InSpecificSlot (uint8 tab, uint8 slot, GuildItemPosCountVec & dest, uint32 & count, bool swap, Item * pSrcItem) const private
Definition at line 1813 of file Guild.cpp.
References EQUIP_ERR_ITEM_CANT_STACK, EQUIP_ERR_OK, Item::GetCount(), Object::GetEntry(), Item::GetMaxStackCount(), GuildItemPosCount::isContainedIn(), and m_TabList.
Referenced by CanStoreItem().
_CanStoreItem_InTab()
InventoryResult Guild::_CanStoreItem_InTab (uint8 tab, GuildItemPosCountVec & dest, uint32 & count, bool merge, Item * pSrcItem, uint8 skip_slot) const private
Definition at line 1856 of file Guild.cpp.
References EQUIP_ERR_OK, Item::GetCount(), Object::GetEntry(), Item::GetMaxStackCount(), GUILD_BANK_MAX_SLOTS, GuildItemPosCount::isContainedIn(), and m_TabList.
Referenced by CanStoreItem().
_StoreItem()
Item * Guild::_StoreItem (uint8 tab, uint8 slot, Item * pItem, uint32 count, bool clone) private
Definition at line 1763 of file Guild.cpp.
References AddGBankItemToDB(), Item::CloneItem(), DEBUG_LOG, Item::DeleteFromDB(), Item::FSetState(), Item::GetCount(), Object::GetEntry(), Object::GetGUIDLow(), GetId(), ITEM_CHANGED, ITEM_FIELD_CONTAINED, ITEM_FIELD_OWNER, ITEM_NEW, m_TabList, Object::RemoveFromWorld(), Item::SaveToDB(), Item::SetCount(), and Object::SetGuidValue().
Referenced by StoreItem().
AddGBankItemToDB()
bool Guild::AddGBankItemToDB (uint32 GuildId, uint32 BankTab, uint32 BankTabSlot, uint32 GUIDLow, uint32 Entry) const
Definition at line 1690 of file Guild.cpp.
References CharacterDatabase, and Database::PExecute().
Referenced by _StoreItem().
AddMember()
bool Guild::AddMember (ObjectGuid plGuid, uint32 plRank)
Definition at line 171 of file Guild.cpp.
References MemberSlot::accountId, MemberSlot::BankResetTimeMoney, MemberSlot::BankResetTimeTab, CharacterDatabase, MemberSlot::Class, CLASSMASK_ALL_PLAYABLE, Database::escape_string(), QueryResult::Fetch(), MemberSlot::Gender_, WorldSession::GetAccountId(), Unit::getClass(), ObjectGuid::GetCounter(), Field::GetCppString(), Unit::getGender(), Player::GetGuildId(), Player::GetGuildIdFromDB(), Field::GetInt32(), Unit::GetLevel(), WorldObject::GetName(), Player::GetSession(), ObjectGuid::GetString(), Field::GetUInt32(), Field::GetUInt8(), WorldObject::GetZoneId(), MemberSlot::guid, MemberSlot::Level, MemberSlot::LogoutTime, m_Id, members, MemberSlot::Name, MemberSlot::OFFnote, Database::PExecute(), MemberSlot::Pnote, Database::PQuery(), MemberSlot::RankId, Player::RemovePetitionsAndSigns(), Player::SetGuildIdInvited(), Player::SetInGuild(), Player::SetRank(), sLog, sObjectMgr, UpdateAccountsNumber(), and MemberSlot::ZoneId.
Referenced by Create(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildAcceptOpcode(), ChatHandler::HandleGuildInviteCommand(), and WorldSession::HandleTurnInPetitionOpcode().
AddRank()
void Guild::AddRank (const std::string & name_, uint32 rights, uint32 money) protected
Definition at line 693 of file Guild.cpp.
References m_Ranks.
Referenced by CreateRank(), and LoadRanksFromDB().
AppendDisplayGuildBankSlot()
void Guild::AppendDisplayGuildBankSlot (WorldPacket & data, GuildBankTab const & tab, int32 slot) const private
Definition at line 1698 of file Guild.cpp.
References Item::GetCount(), Item::GetEnchantmentId(), Object::GetEntry(), Item::GetItemRandomPropertyId(), Item::GetItemSuffixFactor(), Item::GetSpellCharges(), MAX_GEM_SOCKETS, PERM_ENCHANTMENT_SLOT, ByteBuffer::put(), GuildBankTab::Slots, SOCK_ENCHANTMENT_SLOT, and ByteBuffer::wpos().
Referenced by DisplayGuildBankContent(), and DisplayGuildBankContentUpdate().
BroadcastEvent() [1/2]
void Guild::BroadcastEvent (GuildEvents event, char const * str1 = nullptr, char const * str2 = nullptr, char const * str3 = nullptr) inline
Definition at line 351 of file Guild.h.
References BroadcastEvent().
BroadcastEvent() [2/2]
void Guild::BroadcastEvent (GuildEvents event, ObjectGuid guid, char const * str1 = nullptr, char const * str2 = nullptr, char const * str3 = nullptr)
Definition at line 2425 of file Guild.cpp.
References BroadcastPacket(), DEBUG_LOG, and SMSG_GUILD_EVENT.
Referenced by BroadcastEvent(), DelMember(), Disband(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildMOTDOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandlePlayerLogin(), and WorldSession::HandlePlayerReconnect().
BroadcastPacket()
void Guild::BroadcastPacket (WorldPacket const & packet)
Definition at line 615 of file Guild.cpp.
References ObjectAccessor::FindPlayer(), Player::GetSession(), HIGHGUID_PLAYER, members, and WorldSession::SendPacket().
Referenced by BroadcastEvent(), DisplayGuildBankMoneyUpdate(), Roster(), and SendGuildBankTabText().
BroadcastPacketToRank()
void Guild::BroadcastPacketToRank (WorldPacket const & packet, uint32 rankId)
Definition at line 625 of file Guild.cpp.
References ObjectAccessor::FindPlayer(), Player::GetSession(), HIGHGUID_PLAYER, members, and WorldSession::SendPacket().
BroadcastToGuild()
void Guild::BroadcastToGuild (WorldSession * session, const std::string & msg, uint32 language = LANG_UNIVERSAL)
Definition at line 573 of file Guild.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_GUILD, ObjectAccessor::FindPlayer(), Player::GetChatTag(), WorldObject::GetName(), Object::GetObjectGuid(), WorldSession::GetPlayer(), Player::GetRank(), Player::GetSession(), Player::GetSocial(), GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, PlayerSocial::HasIgnore(), HasRankRight(), HIGHGUID_PLAYER, members, and WorldSession::SendPacket().
BroadcastToOfficers()
void Guild::BroadcastToOfficers (WorldSession * session, const std::string & msg, uint32 language = LANG_UNIVERSAL)
Definition at line 594 of file Guild.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_OFFICER, ObjectAccessor::FindPlayer(), Player::GetChatTag(), WorldObject::GetName(), Object::GetObjectGuid(), WorldSession::GetPlayer(), Player::GetRank(), Player::GetSession(), Player::GetSocial(), GR_RIGHT_OFFCHATLISTEN, GR_RIGHT_OFFCHATSPEAK, PlayerSocial::HasIgnore(), HasRankRight(), HIGHGUID_PLAYER, members, and WorldSession::SendPacket().
BroadcastWorker()
template<class Do > void Guild::BroadcastWorker (Do & _do, Player * except = nullptr) inline
Definition at line 357 of file Guild.h.
References ObjectAccessor::FindPlayer(), HIGHGUID_PLAYER, and members.
CanStoreItem()
InventoryResult Guild::CanStoreItem (uint8 tab, uint8 slot, GuildItemPosCountVec & dest, uint32 count, Item * pItem, bool swap = false) const private
Definition at line 1913 of file Guild.cpp.
References _CanStoreItem_InSpecificSlot(), _CanStoreItem_InTab(), DEBUG_LOG, EQUIP_ERR_BANK_FULL, EQUIP_ERR_CANT_DROP_SOULBOUND, EQUIP_ERR_COULDNT_SPLIT_ITEMS, EQUIP_ERR_OK, Item::GetCount(), Object::GetEntry(), Item::GetMaxStackCount(), Item::IsSoulBound(), and NULL_SLOT.
Referenced by MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
CheckGuildStructure()
bool Guild::CheckGuildStructure ()
Definition at line 307 of file Guild.cpp.
References MemberSlot::ChangeRank(), DelMember(), GetRank(), GR_GUILDMASTER, GR_OFFICER, MemberSlot::guid, m_LeaderGuid, members, MemberSlot::RankId, and SetLeader().
Referenced by GuildMgr::LoadGuilds().
Create()
bool Guild::Create (Player * leader, std::string gname)
Definition at line 110 of file Guild.cpp.
References AddMember(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CreateDefaultGuildRanks(), DEBUG_LOG, Database::escape_string(), ObjectGuid::GetCounter(), Object::GetObjectGuid(), Player::GetSession(), WorldSession::GetSessionDbLocaleIndex(), ObjectGuid::GetString(), GINFO, GR_GUILDMASTER, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_CreatedDate, m_EmblemColor, m_EmblemStyle, m_GuildBankMoney, m_Id, m_LeaderGuid, m_Name, MOTD, Database::PExecute(), sAnticheatLib, sGuildMgr, sLog, sObjectMgr, and UI64FMTD.
Referenced by ChatHandler::HandleGuildCreateCommand(), WorldSession::HandleGuildCreateOpcode(), and WorldSession::HandleTurnInPetitionOpcode().
CreateDefaultGuildRanks()
void Guild::CreateDefaultGuildRanks (int locale_idx)
Definition at line 157 of file Guild.cpp.
References CharacterDatabase, CreateRank(), GR_GUILDMASTER, GR_RIGHT_ALL, GR_RIGHT_GCHATLISTEN, GR_RIGHT_GCHATSPEAK, LANG_GUILD_INITIATE, LANG_GUILD_MASTER, LANG_GUILD_MEMBER, LANG_GUILD_OFFICER, LANG_GUILD_VETERAN, m_Id, Database::PExecute(), SetBankMoneyPerDay(), sObjectMgr, and WITHDRAW_MONEY_UNLIMITED.
Referenced by Create(), and LoadRanksFromDB().
CreateNewBankTab()
void Guild::CreateNewBankTab ()
Definition at line 1140 of file Guild.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), GetPurchasedTabs(), GUILD_BANK_MAX_TABS, m_Id, m_TabList, and Database::PExecute().
Referenced by WorldSession::HandleGuildBankBuyTab().
CreateRank()
void Guild::CreateRank (std::string name_, uint32 rights)
Definition at line 671 of file Guild.cpp.
References AddRank(), CharacterDatabase, Database::escape_string(), GetPurchasedTabs(), GUILD_RANKS_MAX_COUNT, m_Id, m_Ranks, and Database::PExecute().
Referenced by CreateDefaultGuildRanks(), and WorldSession::HandleGuildAddRankOpcode().
DeleteGuildBankItems()
void Guild::DeleteGuildBankItems (bool alsoInDB = false)
Definition at line 2455 of file Guild.cpp.
References GUILD_BANK_MAX_SLOTS, and m_TabList.
Referenced by Disband(), and ~Guild().
DelMember()
bool Guild::DelMember (ObjectGuid guid, bool isDisbanding = false)
Remove character from guild.
Parameters
guid Character that removed from guild
isDisbanding Flag set if function called from Guild::Disband, so not need update DB in per-member mode only or leader update
Returns
true, if guild need to be disband and erase (no members or can't setup leader)
Definition at line 512 of file Guild.cpp.
References BroadcastEvent(), CharacterDatabase, GE_LEADER_CHANGED, GE_LEFT, ObjectGuid::GetCounter(), GR_GUILDMASTER, HIGHGUID_PLAYER, m_LeaderGuid, members, MemberSlot::Name, Database::PExecute(), MemberSlot::RankId, Player::SetInGuild(), SetLeader(), Player::SetRank(), sObjectMgr, and UpdateAccountsNumber().
Referenced by CheckGuildStructure(), Disband(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildRemoveOpcode(), and ChatHandler::HandleGuildUninviteCommand().
DelRank()
void Guild::DelRank ()
Definition at line 698 of file Guild.cpp.
References CharacterDatabase, GetLowestRank(), GUILD_RANKS_MIN_COUNT, m_Id, m_Ranks, and Database::PExecute().
Referenced by WorldSession::HandleGuildDelRankOpcode().
Disband()
void Guild::Disband ()
Disband guild including cleanup structures and DB.
Note: guild object need deleted after this in caller code.
Definition at line 755 of file Guild.cpp.
References Database::BeginTransaction(), BroadcastEvent(), CharacterDatabase, Database::CommitTransaction(), DeleteGuildBankItems(), DelMember(), GE_DISBANDED, HIGHGUID_PLAYER, m_Id, members, Database::PExecute(), and sGuildMgr.
Referenced by ChatHandler::HandleGuildDeleteCommand(), WorldSession::HandleGuildDisbandOpcode(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildRemoveOpcode(), ChatHandler::HandleGuildUninviteCommand(), and GuildMgr::LoadGuilds().
DisplayGuildBankContent()
void Guild::DisplayGuildBankContent (WorldSession * session, uint8 TabId)
Definition at line 987 of file Guild.cpp.
References AppendDisplayGuildBankSlot(), DEBUG_LOG, Object::GetGUIDLow(), GetGuildBankMoney(), GetMemberSlotWithdrawRem(), WorldSession::GetPlayer(), GUILD_BANK_MAX_SLOTS, GUILD_BANK_RIGHT_VIEW_TAB, IsMemberHaveRights(), m_TabList, WorldSession::SendPacket(), and SMSG_GUILD_BANK_LIST.
Referenced by WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankQueryTab(), WorldSession::HandleGuildBankUpdateTab(), and WorldSession::HandleGuildBankWithdrawMoney().
DisplayGuildBankContentUpdate() [1/2]
void Guild::DisplayGuildBankContentUpdate (uint8 TabId, GuildItemPosCountVec const & slots) private
Definition at line 1073 of file Guild.cpp.
References AppendDisplayGuildBankSlot(), DEBUG_LOG, ObjectAccessor::FindPlayer(), Object::GetGUIDLow(), GetGuildBankMoney(), GetMemberSlotWithdrawRem(), Player::GetSession(), GUILD_BANK_RIGHT_VIEW_TAB, HIGHGUID_PLAYER, IsMemberHaveRights(), m_TabList, members, ByteBuffer::put(), WorldSession::SendPacket(), SMSG_GUILD_BANK_LIST, and ByteBuffer::wpos().
DisplayGuildBankContentUpdate() [2/2]
void Guild::DisplayGuildBankContentUpdate (uint8 TabId, int32 slot1, int32 slot2 = -1) private
Definition at line 1026 of file Guild.cpp.
References AppendDisplayGuildBankSlot(), DEBUG_LOG, ObjectAccessor::FindPlayer(), Object::GetGUIDLow(), GetGuildBankMoney(), GetMemberSlotWithdrawRem(), Player::GetSession(), GUILD_BANK_RIGHT_VIEW_TAB, HIGHGUID_PLAYER, IsMemberHaveRights(), m_TabList, members, ByteBuffer::put(), WorldSession::SendPacket(), SMSG_GUILD_BANK_LIST, and ByteBuffer::wpos().
Referenced by MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
DisplayGuildBankLogs()
void Guild::DisplayGuildBankLogs (WorldSession * session, uint8 TabId)
Definition at line 1582 of file Guild.cpp.
References DEBUG_LOG, GUILD_BANK_LOG_DEPOSIT_MONEY, GUILD_BANK_LOG_MOVE_ITEM, GUILD_BANK_LOG_MOVE_ITEM2, GUILD_BANK_LOG_REPAIR_MONEY, GUILD_BANK_LOG_UNK1, GUILD_BANK_LOG_UNK2, GUILD_BANK_LOG_WITHDRAW_MONEY, GUILD_BANK_MAX_TABS, HIGHGUID_PLAYER, m_GuildBankEventLog_Item, m_GuildBankEventLog_Money, MSG_GUILD_BANK_LOG_QUERY, and WorldSession::SendPacket().
Referenced by WorldSession::HandleGuildBankLogQuery().
DisplayGuildBankMoneyUpdate()
void Guild::DisplayGuildBankMoneyUpdate (WorldSession * session)
Definition at line 1012 of file Guild.cpp.
References BroadcastPacket(), DEBUG_LOG, Object::GetGUIDLow(), GetGuildBankMoney(), GetMemberSlotWithdrawRem(), WorldSession::GetPlayer(), and SMSG_GUILD_BANK_LIST.
Referenced by WorldSession::HandleGuildBankDepositMoney(), and WorldSession::HandleGuildBankWithdrawMoney().
DisplayGuildBankTabsInfo()
void Guild::DisplayGuildBankTabsInfo (WorldSession * session)
Definition at line 1118 of file Guild.cpp.
References DEBUG_LOG, Object::GetGUIDLow(), GetGuildBankMoney(), GetMemberSlotWithdrawRem(), WorldSession::GetPlayer(), GetPurchasedTabs(), m_TabList, WorldSession::SendPacket(), and SMSG_GUILD_BANK_LIST.
Referenced by WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankUpdateTab(), WorldSession::HandleGuildBankWithdrawMoney(), and WorldSession::HandlePlayerLogin().
DisplayGuildEventLog()
void Guild::DisplayGuildEventLog (WorldSession * session)
Definition at line 898 of file Guild.cpp.
References DEBUG_LOG, GUILD_EVENT_LOG_DEMOTE_PLAYER, GUILD_EVENT_LOG_JOIN_GUILD, GUILD_EVENT_LOG_LEAVE_GUILD, GUILD_EVENT_LOG_PROMOTE_PLAYER, HIGHGUID_PLAYER, m_GuildEventLog, MSG_GUILD_EVENT_LOG_QUERY, and WorldSession::SendPacket().
GetAccountsNumber()
uint32 Guild::GetAccountsNumber ()
Return the number of accounts that are in the guild after possible update if required A player may have many characters in the guild, but with the same account.
Definition at line 878 of file Guild.cpp.
References m_accountsNumber, and members.
Referenced by WorldSession::HandleGuildInfoOpcode().
GetBackgroundColor()
uint32 Guild::GetBackgroundColor () const inline
Definition at line 323 of file Guild.h.
References m_BackgroundColor.
GetBankMoneyPerDay()
uint32 Guild::GetBankMoneyPerDay (uint32 rankId)
Definition at line 1435 of file Guild.cpp.
References GR_GUILDMASTER, m_Ranks, and WITHDRAW_MONEY_UNLIMITED.
Referenced by GetMemberMoneyWithdrawRem().
GetBankRights()
uint32 Guild::GetBankRights (uint32 rankId, uint8 TabId) const
Definition at line 1167 of file Guild.cpp.
References GUILD_BANK_MAX_TABS, and m_Ranks.
Referenced by GetMemberSlotWithdrawRem(), and IsMemberHaveRights().
GetBankSlotPerDay()
uint32 Guild::GetBankSlotPerDay (uint32 rankId, uint8 TabId)
Definition at line 1445 of file Guild.cpp.
References GR_GUILDMASTER, GUILD_BANK_MAX_TABS, m_Ranks, and WITHDRAW_SLOT_UNLIMITED.
Referenced by GetMemberSlotWithdrawRem().
GetBorderColor()
uint32 Guild::GetBorderColor () const inline
Definition at line 322 of file Guild.h.
References m_BorderColor.
GetBorderStyle()
uint32 Guild::GetBorderStyle () const inline
Definition at line 321 of file Guild.h.
References m_BorderStyle.
GetCreatedDate()
time_t Guild::GetCreatedDate () const inline
Definition at line 317 of file Guild.h.
References m_CreatedDate.
Referenced by WorldSession::HandleGuildInfoOpcode().
GetEmblemColor()
uint32 Guild::GetEmblemColor () const inline
Definition at line 320 of file Guild.h.
References m_EmblemColor.
GetEmblemStyle()
uint32 Guild::GetEmblemStyle () const inline
Definition at line 319 of file Guild.h.
References m_EmblemStyle.
GetGINFO()
std::string const& Guild::GetGINFO () const inline
Definition at line 315 of file Guild.h.
References GINFO.
GetGuildBankMoney()
uint64 Guild::GetGuildBankMoney () const inline
Definition at line 431 of file Guild.h.
References m_GuildBankMoney.
Referenced by DisplayGuildBankContent(), DisplayGuildBankContentUpdate(), DisplayGuildBankMoneyUpdate(), DisplayGuildBankTabsInfo(), Player::DurabilityRepair(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankWithdrawMoney(), MemberMoneyWithdraw(), and PlayerbotAI::Repair().
GetGuildInviter()
ObjectGuid Guild::GetGuildInviter (ObjectGuid playerGuid) const
Definition at line 2414 of file Guild.cpp.
References GUILD_EVENT_LOG_INVITE_PLAYER, HIGHGUID_PLAYER, and m_GuildEventLog.
GetId()
uint32 Guild::GetId () const inline
Definition at line 311 of file Guild.h.
References m_Id.
Referenced by _StoreItem(), GuildMgr::AddGuild(), WorldSession::HandleGuildLeaveOpcode(), and RemoveItem().
GetItem()
Item * Guild::GetItem (uint8 TabId, uint8 SlotId) private
Definition at line 1108 of file Guild.cpp.
References GetPurchasedTabs(), GUILD_BANK_MAX_SLOTS, and m_TabList.
Referenced by MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
GetLeaderGuid()
ObjectGuid Guild::GetLeaderGuid () const inline
Definition at line 312 of file Guild.h.
References m_LeaderGuid.
Referenced by PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildAddRankOpcode(), WorldSession::HandleGuildDelRankOpcode(), WorldSession::HandleGuildDisbandOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildLeaveOpcode(), ChatHandler::HandleGuildRankCommand(), WorldSession::HandleGuildRankOpcode(), and WorldSession::HandleSaveGuildEmblemOpcode().
GetLowestRank()
uint32 Guild::GetLowestRank () const inline
Definition at line 329 of file Guild.h.
References m_Ranks.
Referenced by DelRank(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildDemoteOpcode(), ChatHandler::HandleGuildInviteCommand(), ChatHandler::HandleGuildRankCommand(), WorldSession::HandleTurnInPetitionOpcode(), and LoadMembersFromDB().
GetMemberMoneyWithdrawRem()
uint32 Guild::GetMemberMoneyWithdrawRem (uint32 LowGuid)
Definition at line 1357 of file Guild.cpp.
References MemberSlot::BankRemMoney, MemberSlot::BankResetTimeMoney, CharacterDatabase, GetBankMoneyPerDay(), GR_GUILDMASTER, HOUR, m_Id, members, MINUTE, Database::PExecute(), MemberSlot::RankId, and WITHDRAW_MONEY_UNLIMITED.
Referenced by Player::DurabilityRepair(), MemberMoneyWithdraw(), and SendMoneyInfo().
GetMemberSize()
uint32 Guild::GetMemberSize () const inline
Definition at line 335 of file Guild.h.
References members.
Referenced by WorldSession::HandleGuildInfoOpcode(), and WorldSession::HandleGuildLeaveOpcode().
GetMemberSlot() [1/2]
MemberSlot* Guild::GetMemberSlot (const std::string & name) inline
Definition at line 390 of file Guild.h.
References members.
GetMemberSlot() [2/2]
MemberSlot* Guild::GetMemberSlot (ObjectGuid guid) inline
Definition at line 384 of file Guild.h.
References ObjectGuid::GetCounter(), and members.
Referenced by GetRank(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildPromoteOpcode(), ChatHandler::HandleGuildRankCommand(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), and SetLeader().
GetMemberSlotWithdrawRem()
uint32 Guild::GetMemberSlotWithdrawRem (uint32 LowGuid, uint8 TabId)
Definition at line 1333 of file Guild.cpp.
References MemberSlot::BankRemSlotsTab, MemberSlot::BankResetTimeTab, CharacterDatabase, GetBankRights(), GetBankSlotPerDay(), GR_GUILDMASTER, GUILD_BANK_RIGHT_VIEW_TAB, HOUR, m_Id, members, MINUTE, Database::PExecute(), MemberSlot::RankId, and WITHDRAW_SLOT_UNLIMITED.
Referenced by DisplayGuildBankContent(), DisplayGuildBankContentUpdate(), DisplayGuildBankMoneyUpdate(), DisplayGuildBankTabsInfo(), MemberItemWithdraw(), MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
GetMOTD()
std::string const& Guild::GetMOTD () const inline
Definition at line 314 of file Guild.h.
References MOTD.
Referenced by WorldSession::HandlePlayerLogin(), and WorldSession::HandlePlayerReconnect().
GetName()
std::string const& Guild::GetName () const inline
Definition at line 313 of file Guild.h.
References m_Name.
Referenced by WorldSession::HandleGuildInfoOpcode(), WorldSession::HandleGuildInviteOpcode(), and WorldSession::HandleGuildLeaveOpcode().
GetPurchasedTabs()
uint8 Guild::GetPurchasedTabs () const inline
Definition at line 423 of file Guild.h.
References m_TabList.
Referenced by CreateNewBankTab(), CreateRank(), DisplayGuildBankTabsInfo(), GetItem(), WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankLogQuery(), WorldSession::HandleGuildBankQueryTab(), WorldSession::HandleGuildBankSwapItems(), WorldSession::HandleGuildBankUpdateTab(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleQueryGuildBankTabText(), WorldSession::HandleSetGuildBankTabText(), LoadGuildBankEventLogFromDB(), LoadGuildBankFromDB(), SetBankRightsAndSlots(), and SetGuildBankTabText().
GetRank()
int32 Guild::GetRank (ObjectGuid guid) inline
Definition at line 378 of file Guild.h.
References GetMemberSlot(), and MemberSlot::RankId.
Referenced by CheckGuildStructure().
GetRankName()
std::string Guild::GetRankName (uint32 rankId)
Definition at line 712 of file Guild.cpp.
References m_Ranks.
Referenced by WorldSession::HandleGuildDemoteOpcode(), and WorldSession::HandleGuildPromoteOpcode().
GetRankRights()
uint32 Guild::GetRankRights (uint32 rankId)
Definition at line 720 of file Guild.cpp.
References m_Ranks.
Referenced by HasRankRight().
GetRanksSize()
uint32 Guild::GetRanksSize () const inline
Definition at line 369 of file Guild.h.
References m_Ranks.
Referenced by WorldSession::HandleGuildAddRankOpcode().
HasRankRight()
bool Guild::HasRankRight (uint32 rankId, uint32 right) inline
Definition at line 373 of file Guild.h.
References GetRankRights(), and GR_RIGHT_EMPTY.
Referenced by BroadcastToGuild(), BroadcastToOfficers(), Player::DurabilityRepair(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleGuildChangeInfoTextOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildMOTDOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), PlayerbotAI::Repair(), and Roster().
IsMemberHaveRights()
bool Guild::IsMemberHaveRights (uint32 LowGuid, uint8 TabId, uint32 rights) const
Definition at line 1321 of file Guild.cpp.
References GetBankRights(), GR_GUILDMASTER, and members.
Referenced by DisplayGuildBankContent(), DisplayGuildBankContentUpdate(), MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
LoadBankRightsFromDB()
bool Guild::LoadBankRightsFromDB (QueryResult * guildBankTabRightsResult)
Definition at line 1458 of file Guild.cpp.
References CharacterDatabase, QueryResult::Fetch(), Field::GetUInt16(), Field::GetUInt32(), Field::GetUInt8(), m_Id, QueryResult::NextRow(), Database::PExecute(), SetBankRightsAndSlots(), and sLog.
Referenced by GuildMgr::LoadGuilds().
LoadGuildBankEventLogFromDB()
void Guild::LoadGuildBankEventLogFromDB ()
Definition at line 1496 of file Guild.cpp.
References CharacterDatabase, GuildBankEventLogEntry::DestTabId, GuildBankEventLogEntry::EventType, QueryResult::Fetch(), GetPurchasedTabs(), Field::GetUInt32(), Field::GetUInt64(), Field::GetUInt8(), GUILD_BANK_MAX_LOGS, GUILD_BANK_MONEY_LOGS_TAB, GuildBankEventLogEntry::isMoneyEvent(), GuildBankEventLogEntry::ItemOrMoney, GuildBankEventLogEntry::ItemStackCount, m_GuildBankEventLog_Item, m_GuildBankEventLog_Money, m_GuildBankEventLogNextGuid_Item, m_GuildBankEventLogNextGuid_Money, m_Id, QueryResult::NextRow(), Database::PExecute(), GuildBankEventLogEntry::PlayerGuid, Database::PQuery(), sLog, and GuildBankEventLogEntry::TimeStamp.
Referenced by GuildMgr::LoadGuilds().
LoadGuildBankFromDB()
void Guild::LoadGuildBankFromDB ()
Definition at line 1179 of file Guild.cpp.
References Object::AddToWorld(), CharacterDatabase, QueryResult::Fetch(), Field::GetCppString(), ObjectMgr::GetItemPrototype(), GetPurchasedTabs(), Field::GetUInt32(), Field::GetUInt8(), GUILD_BANK_MAX_SLOTS, Item::LoadFromDB(), m_Id, m_TabList, NewItemOrBag(), QueryResult::NextRow(), Database::PExecute(), Database::PQuery(), and sLog.
Referenced by GuildMgr::LoadGuilds().
LoadGuildEventLogFromDB()
void Guild::LoadGuildEventLogFromDB ()
Definition at line 924 of file Guild.cpp.
References CharacterDatabase, GuildEventLogEntry::EventType, QueryResult::Fetch(), Field::GetUInt32(), Field::GetUInt64(), Field::GetUInt8(), GUILD_EVENTLOG_MAX_RECORDS, m_GuildEventLog, m_GuildEventLogNextGuid, m_Id, GuildEventLogEntry::NewRank, QueryResult::NextRow(), GuildEventLogEntry::PlayerGuid1, GuildEventLogEntry::PlayerGuid2, Database::PQuery(), and GuildEventLogEntry::TimeStamp.
Referenced by GuildMgr::LoadGuilds().
LoadGuildFromDB()
bool Guild::LoadGuildFromDB (QueryResult * guildDataResult)
Definition at line 277 of file Guild.cpp.
References QueryResult::Fetch(), Field::GetCppString(), Field::GetUInt32(), Field::GetUInt64(), GINFO, GUILD_BANK_MAX_TABS, HIGHGUID_PLAYER, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_CreatedDate, m_EmblemColor, m_EmblemStyle, m_GuildBankMoney, m_Id, m_LeaderGuid, m_Name, m_TabList, and MOTD.
Referenced by GuildMgr::LoadGuilds().
LoadMembersFromDB()
bool Guild::LoadMembersFromDB (QueryResult * guildMembersResult)
Definition at line 409 of file Guild.cpp.
References MemberSlot::accountId, MemberSlot::BankRemMoney, MemberSlot::BankRemSlotsTab, MemberSlot::BankResetTimeMoney, MemberSlot::BankResetTimeTab, CharacterDatabase, MemberSlot::Class, CLASSMASK_ALL_PLAYABLE, QueryResult::Fetch(), MemberSlot::Gender_, Field::GetCppString(), Field::GetInt32(), GetLowestRank(), ObjectGuid::GetString(), Field::GetUInt32(), Field::GetUInt64(), Field::GetUInt8(), Player::GetZoneIdFromDB(), MemberSlot::guid, GUILD_BANK_MAX_TABS, HIGHGUID_PLAYER, MemberSlot::Level, MemberSlot::LogoutTime, m_Id, m_Ranks, members, MemberSlot::Name, QueryResult::NextRow(), MemberSlot::OFFnote, Database::PExecute(), MemberSlot::Pnote, MemberSlot::RankId, sLog, UpdateAccountsNumber(), and MemberSlot::ZoneId.
Referenced by GuildMgr::LoadGuilds().
LoadRanksFromDB()
bool Guild::LoadRanksFromDB (QueryResult * guildRanksResult)
Definition at line 332 of file Guild.cpp.
References AddRank(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CreateDefaultGuildRanks(), Database::escape_string(), QueryResult::Fetch(), Field::GetCppString(), Field::GetUInt32(), GR_RIGHT_ALL, GUILD_RANKS_MIN_COUNT, m_Id, m_Ranks, QueryResult::NextRow(), Database::PExecute(), and sLog.
Referenced by GuildMgr::LoadGuilds().
LogBankEvent()
void Guild::LogBankEvent (uint8 EventType, uint8 TabId, uint32 PlayerGuidLow, uint32 ItemOrMoney, uint8 ItemStackCount = 0, uint8 DestTabId = 0)
Definition at line 1649 of file Guild.cpp.
References CharacterDatabase, CONFIG_UINT32_GUILD_BANK_EVENT_LOG_COUNT, GuildBankEventLogEntry::DestTabId, GuildBankEventLogEntry::EventType, GUILD_BANK_MAX_LOGS, GUILD_BANK_MONEY_LOGS_TAB, GuildBankEventLogEntry::isMoneyEvent(), GuildBankEventLogEntry::ItemOrMoney, GuildBankEventLogEntry::ItemStackCount, m_GuildBankEventLog_Item, m_GuildBankEventLog_Money, m_GuildBankEventLogNextGuid_Item, m_GuildBankEventLogNextGuid_Money, m_Id, Database::PExecute(), GuildBankEventLogEntry::PlayerGuid, sWorld, GuildBankEventLogEntry::TimeStamp, and UI64FMTD.
Referenced by WorldSession::HandleGuildBankDepositMoney(), WorldSession::HandleGuildBankWithdrawMoney(), WorldSession::HandleRepairItemOpcode(), MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
LogGuildEvent()
void Guild::LogGuildEvent (uint8 EventType, ObjectGuid playerGuid1, ObjectGuid playerGuid2 = ObjectGuid(), uint8 newRank = 0)
Definition at line 961 of file Guild.cpp.
References CharacterDatabase, CONFIG_UINT32_GUILD_EVENT_LOG_COUNT, GuildEventLogEntry::EventType, ObjectGuid::GetCounter(), GUILD_EVENTLOG_MAX_RECORDS, m_GuildEventLog, m_GuildEventLogNextGuid, m_Id, GuildEventLogEntry::NewRank, Database::PExecute(), GuildEventLogEntry::PlayerGuid1, GuildEventLogEntry::PlayerGuid2, sWorld, GuildEventLogEntry::TimeStamp, and UI64FMTD.
Referenced by PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleGuildAcceptOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaveOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), and WorldSession::HandleTurnInPetitionOpcode().
MassInviteToEvent()
void Guild::MassInviteToEvent (WorldSession * session, uint32 minLevel, uint32 maxLevel, uint32 minRank)
Definition at line 639 of file Guild.cpp.
References CALENDAR_ERROR_INVITES_EXCEEDED, CALENDAR_MAX_INVITES, Player::GetLevelFromDB(), Object::GetObjectGuid(), WorldSession::GetPlayer(), MemberSlot::guid, members, ByteBuffer::put(), MemberSlot::RankId, sCalendarMgr, WorldSession::SendPacket(), SMSG_CALENDAR_FILTER_GUILD, and ObjectGuid::WriteAsPacked().
MemberItemWithdraw()
bool Guild::MemberItemWithdraw (uint8 TabId, uint32 LowGuid)
Definition at line 1302 of file Guild.cpp.
References CharacterDatabase, GetMemberSlotWithdrawRem(), m_Id, members, Database::PExecute(), and WITHDRAW_SLOT_UNLIMITED.
Referenced by MoveFromBankToChar(), and MoveFromCharToBank().
MemberMoneyWithdraw()
bool Guild::MemberMoneyWithdraw (uint32 amount, uint32 LowGuid)
Definition at line 1269 of file Guild.cpp.
References CharacterDatabase, GetGuildBankMoney(), GetMemberMoneyWithdrawRem(), m_Id, members, Database::PExecute(), SetBankMoney(), and WITHDRAW_MONEY_UNLIMITED.
Referenced by Player::DurabilityRepair(), and WorldSession::HandleGuildBankWithdrawMoney().
MoveFromBankToChar()
void Guild::MoveFromBankToChar (Player * pl, uint8 BankTab, uint8 BankTabSlot, uint8 PlayerBag, uint8 PlayerSlot, uint32 SplitedAmount)
Definition at line 2116 of file Guild.cpp.
References Database::BeginTransaction(), Item::CanBeTraded(), Player::CanStoreItem(), CanStoreItem(), CharacterDatabase, Item::CloneItem(), Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, Item::DeleteFromInventoryDB(), DisplayGuildBankContentUpdate(), EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_ITEMS_CANT_BE_SWAPPED, EQUIP_ERR_OK, Item::FSetState(), WorldSession::GetAccountId(), Item::GetCount(), Object::GetEntry(), Object::GetGUIDLow(), GetItem(), Player::GetItemByPos(), GetMemberSlotWithdrawRem(), WorldObject::GetName(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), GUILD_BANK_LOG_DEPOSIT_ITEM, GUILD_BANK_LOG_WITHDRAW_ITEM, GUILD_BANK_RIGHT_DEPOSIT_ITEM, IsMemberHaveRights(), ITEM_CHANGED, LogBankEvent(), m_Id, MemberItemWithdraw(), Player::MoveItemFromInventory(), Player::MoveItemToInventory(), ItemPrototype::Name1, RemoveItem(), Player::SaveInventoryAndGoldToDB(), Item::SaveToDB(), SEC_PLAYER, Player::SendEquipError(), Item::SetCount(), sLog, StoreItem(), and sWorld.
Referenced by WorldSession::HandleGuildBankSwapItems().
MoveFromCharToBank()
void Guild::MoveFromCharToBank (Player * pl, uint8 PlayerBag, uint8 PlayerSlot, uint8 BankTab, uint8 BankTabSlot, uint32 SplitedAmount)
Definition at line 2264 of file Guild.cpp.
References Database::BeginTransaction(), Item::CanBeTraded(), Player::CanStoreItem(), CanStoreItem(), CharacterDatabase, Item::CloneItem(), Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, Item::DeleteFromInventoryDB(), DisplayGuildBankContentUpdate(), EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_ITEMS_CANT_BE_SWAPPED, EQUIP_ERR_OK, WorldSession::GetAccountId(), Item::GetCount(), Object::GetEntry(), Object::GetGUIDLow(), GetItem(), Player::GetItemByPos(), GetMemberSlotWithdrawRem(), WorldObject::GetName(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), GUILD_BANK_LOG_DEPOSIT_ITEM, GUILD_BANK_LOG_WITHDRAW_ITEM, GUILD_BANK_RIGHT_DEPOSIT_ITEM, IsMemberHaveRights(), ITEM_CHANGED, Player::ItemRemovedQuestCheck(), LogBankEvent(), m_Id, MemberItemWithdraw(), Player::MoveItemFromInventory(), Player::MoveItemToInventory(), ItemPrototype::Name1, RemoveItem(), Player::SaveInventoryAndGoldToDB(), SEC_PLAYER, Player::SendEquipError(), Item::SetCount(), Item::SetState(), sLog, StoreItem(), and sWorld.
Referenced by WorldSession::HandleGuildBankSwapItems().
Query()
void Guild::Query (WorldSession * session)
Definition at line 837 of file Guild.cpp.
References DEBUG_LOG, GUILD_RANKS_MAX_COUNT, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_EmblemColor, m_EmblemStyle, m_Id, m_Name, m_Ranks, WorldSession::SendPacket(), and SMSG_GUILD_QUERY_RESPONSE.
Referenced by WorldSession::HandleGuildAddRankOpcode(), WorldSession::HandleGuildDelRankOpcode(), WorldSession::HandleGuildRankOpcode(), and WorldSession::HandleSaveGuildEmblemOpcode().
RemoveItem()
void Guild::RemoveItem (uint8 tab, uint8 slot) private
Definition at line 1806 of file Guild.cpp.
References CharacterDatabase, GetId(), m_TabList, and Database::PExecute().
Referenced by MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
Roster()
void Guild::Roster (WorldSession * session = nullptr)
Definition at line 781 of file Guild.cpp.
References BroadcastPacket(), DAY, DEBUG_LOG, ObjectAccessor::FindPlayer(), WorldSession::GetPlayer(), Player::GetRank(), GINFO, GR_RIGHT_VIEWOFFNOTE, GUILD_BANK_MAX_TABS, HasRankRight(), HIGHGUID_PLAYER, m_Ranks, members, MOTD, WorldSession::SendPacket(), and SMSG_GUILD_ROSTER.
Referenced by WorldSession::HandleGuildAddRankOpcode(), WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildDelRankOpcode(), WorldSession::HandleGuildRankOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), and WorldSession::HandleGuildSetPublicNoteOpcode().
SendGuildBankTabText()
void Guild::SendGuildBankTabText (WorldSession * session, uint8 TabId)
Definition at line 1977 of file Guild.cpp.
References BroadcastPacket(), m_TabList, MSG_QUERY_GUILD_BANK_TEXT, WorldSession::SendPacket(), and GuildBankTab::Text.
Referenced by WorldSession::HandleQueryGuildBankTabText(), and SetGuildBankTabText().
SendMoneyInfo()
void Guild::SendMoneyInfo (WorldSession * session, uint32 LowGuid)
Definition at line 1261 of file Guild.cpp.
References DEBUG_LOG, GetMemberMoneyWithdrawRem(), MSG_GUILD_BANK_MONEY_WITHDRAWN, and WorldSession::SendPacket().
Referenced by WorldSession::HandleGuildBankQueryTab(), WorldSession::HandleGuildBankWithdrawMoney(), and WorldSession::HandleRepairItemOpcode().
SetBankMoney()
void Guild::SetBankMoney (int64 money)
Definition at line 1290 of file Guild.cpp.
References CharacterDatabase, m_GuildBankMoney, m_Id, Database::PExecute(), and UI64FMTD.
Referenced by WorldSession::HandleGuildBankDepositMoney(), and MemberMoneyWithdraw().
SetBankMoneyPerDay()
void Guild::SetBankMoneyPerDay (uint32 rankId, uint32 money)
Definition at line 1379 of file Guild.cpp.
References MemberSlot::BankResetTimeMoney, CharacterDatabase, GR_GUILDMASTER, m_Id, m_Ranks, members, Database::PExecute(), MemberSlot::RankId, and WITHDRAW_MONEY_UNLIMITED.
Referenced by CreateDefaultGuildRanks(), and WorldSession::HandleGuildRankOpcode().
SetBankRightsAndSlots()
void Guild::SetBankRightsAndSlots (uint32 rankId, uint8 TabId, uint32 right, uint32 nbSlots, bool db)
Definition at line 1400 of file Guild.cpp.
References MemberSlot::BankResetTimeTab, CharacterDatabase, GetPurchasedTabs(), GR_GUILDMASTER, GUILD_BANK_RIGHT_FULL, m_Id, m_Ranks, members, Database::PExecute(), MemberSlot::RankId, and WITHDRAW_SLOT_UNLIMITED.
Referenced by WorldSession::HandleGuildBankBuyTab(), WorldSession::HandleGuildRankOpcode(), and LoadBankRightsFromDB().
SetEmblem()
void Guild::SetEmblem (uint32 emblemStyle, uint32 emblemColor, uint32 borderStyle, uint32 borderColor, uint32 backgroundColor)
Definition at line 863 of file Guild.cpp.
References CharacterDatabase, m_BackgroundColor, m_BorderColor, m_BorderStyle, m_EmblemColor, m_EmblemStyle, m_Id, and Database::PExecute().
Referenced by WorldSession::HandleSaveGuildEmblemOpcode().
SetGINFO()
void Guild::SetGINFO (std::string ginfo)
Definition at line 268 of file Guild.cpp.
References CharacterDatabase, Database::escape_string(), GINFO, m_Id, and Database::PExecute().
Referenced by WorldSession::HandleGuildChangeInfoTextOpcode().
SetGuildBankTabInfo()
void Guild::SetGuildBankTabInfo (uint8 TabId, std::string Name, std::string Icon)
Definition at line 1154 of file Guild.cpp.
References CharacterDatabase, Database::escape_string(), m_Id, m_TabList, and Database::PExecute().
Referenced by WorldSession::HandleGuildBankUpdateTab().
SetGuildBankTabText()
void Guild::SetGuildBankTabText (uint8 TabId, std::string text)
Definition at line 1958 of file Guild.cpp.
References CharacterDatabase, Database::escape_string(), GetPurchasedTabs(), m_Id, m_TabList, Database::PExecute(), SendGuildBankTabText(), and utf8truncate().
Referenced by WorldSession::HandleSetGuildBankTabText().
SetLeader()
void Guild::SetLeader (ObjectGuid guid)
Definition at line 492 of file Guild.cpp.
References MemberSlot::ChangeRank(), CharacterDatabase, ObjectGuid::GetCounter(), GetMemberSlot(), GR_GUILDMASTER, m_Id, m_LeaderGuid, and Database::PExecute().
Referenced by CheckGuildStructure(), DelMember(), WorldSession::HandleGuildLeaderOpcode(), and ChatHandler::HandleGuildRankCommand().
SetMOTD()
void Guild::SetMOTD (std::string motd)
Definition at line 259 of file Guild.cpp.
References CharacterDatabase, Database::escape_string(), m_Id, MOTD, and Database::PExecute().
Referenced by WorldSession::HandleGuildMOTDOpcode().
SetRankName()
void Guild::SetRankName (uint32 rankId, std::string name_)
Definition at line 728 of file Guild.cpp.
References CharacterDatabase, Database::escape_string(), m_Id, m_Ranks, and Database::PExecute().
Referenced by WorldSession::HandleGuildRankOpcode().
SetRankRights()
void Guild::SetRankRights (uint32 rankId, uint32 rights)
Definition at line 740 of file Guild.cpp.
References CharacterDatabase, m_Id, m_Ranks, and Database::PExecute().
Referenced by WorldSession::HandleGuildRankOpcode().
StoreItem()
Item * Guild::StoreItem (uint8 tabId, GuildItemPosCountVec const & dest, Item * pItem) private
Definition at line 1736 of file Guild.cpp.
References _StoreItem().
Referenced by MoveFromBankToChar(), MoveFromCharToBank(), and SwapItems().
SwapItems()
void Guild::SwapItems (Player * pl, uint8 BankTab, uint8 BankTabSlot, uint8 BankTabDst, uint8 BankTabSlotDst, uint32 SplitedAmount)
Definition at line 1991 of file Guild.cpp.
References Database::BeginTransaction(), CanStoreItem(), CharacterDatabase, Item::CloneItem(), Database::CommitTransaction(), DisplayGuildBankContentUpdate(), EQUIP_ERR_ITEM_NOT_FOUND, EQUIP_ERR_OK, Item::FSetState(), Item::GetCount(), Object::GetEntry(), Object::GetGUIDLow(), GetItem(), GetMemberSlotWithdrawRem(), GUILD_BANK_LOG_MOVE_ITEM, GUILD_BANK_RIGHT_DEPOSIT_ITEM, IsMemberHaveRights(), ITEM_CHANGED, Player::ItemRemovedQuestCheck(), LogBankEvent(), RemoveItem(), Item::SaveToDB(), Player::SendEquipError(), Item::SetCount(), and StoreItem().
Referenced by WorldSession::HandleGuildBankSwapItems().
UpdateAccountsNumber()
void Guild::UpdateAccountsNumber () inline private
Definition at line 486 of file Guild.h.
References m_accountsNumber.
Referenced by AddMember(), DelMember(), and LoadMembersFromDB().
Field Documentation
GINFO
std::string Guild::GINFO protected
Definition at line 456 of file Guild.h.
Referenced by Create(), GetGINFO(), Guild(), LoadGuildFromDB(), Roster(), and SetGINFO().
m_accountsNumber
uint32 Guild::m_accountsNumber protected
Definition at line 464 of file Guild.h.
Referenced by GetAccountsNumber(), Guild(), and UpdateAccountsNumber().
m_BackgroundColor
uint32 Guild::m_BackgroundColor protected
Definition at line 463 of file Guild.h.
Referenced by Create(), GetBackgroundColor(), Guild(), LoadGuildFromDB(), Query(), and SetEmblem().
m_BorderColor
uint32 Guild::m_BorderColor protected
Definition at line 462 of file Guild.h.
Referenced by Create(), GetBorderColor(), Guild(), LoadGuildFromDB(), Query(), and SetEmblem().
m_BorderStyle
uint32 Guild::m_BorderStyle protected
Definition at line 461 of file Guild.h.
Referenced by Create(), GetBorderStyle(), Guild(), LoadGuildFromDB(), Query(), and SetEmblem().
m_CreatedDate
time_t Guild::m_CreatedDate protected
Definition at line 457 of file Guild.h.
Referenced by Create(), GetCreatedDate(), Guild(), and LoadGuildFromDB().
m_EmblemColor
uint32 Guild::m_EmblemColor protected
Definition at line 460 of file Guild.h.
Referenced by Create(), GetEmblemColor(), Guild(), LoadGuildFromDB(), Query(), and SetEmblem().
m_EmblemStyle
uint32 Guild::m_EmblemStyle protected
Definition at line 459 of file Guild.h.
Referenced by Create(), GetEmblemStyle(), Guild(), LoadGuildFromDB(), Query(), and SetEmblem().
m_GuildBankEventLog_Item
GuildBankEventLog Guild::m_GuildBankEventLog_Item[GUILD_BANK_MAX_TABS] protected
Definition at line 477 of file Guild.h.
Referenced by DisplayGuildBankLogs(), LoadGuildBankEventLogFromDB(), and LogBankEvent().
m_GuildBankEventLog_Money
GuildBankEventLog Guild::m_GuildBankEventLog_Money protected
Definition at line 476 of file Guild.h.
Referenced by DisplayGuildBankLogs(), LoadGuildBankEventLogFromDB(), and LogBankEvent().
m_GuildBankEventLogNextGuid_Item
uint32 Guild::m_GuildBankEventLogNextGuid_Item[GUILD_BANK_MAX_TABS] protected
Definition at line 481 of file Guild.h.
Referenced by Guild(), LoadGuildBankEventLogFromDB(), and LogBankEvent().
m_GuildBankEventLogNextGuid_Money
uint32 Guild::m_GuildBankEventLogNextGuid_Money protected
Definition at line 480 of file Guild.h.
Referenced by Guild(), LoadGuildBankEventLogFromDB(), and LogBankEvent().
m_GuildBankMoney
uint64 Guild::m_GuildBankMoney protected
Definition at line 483 of file Guild.h.
Referenced by Create(), GetGuildBankMoney(), Guild(), LoadGuildFromDB(), and SetBankMoney().
m_GuildEventLog
GuildEventLog Guild::m_GuildEventLog protected
Definition at line 475 of file Guild.h.
Referenced by DisplayGuildEventLog(), GetGuildInviter(), LoadGuildEventLogFromDB(), and LogGuildEvent().
m_GuildEventLogNextGuid
uint32 Guild::m_GuildEventLogNextGuid protected
Definition at line 479 of file Guild.h.
Referenced by Guild(), LoadGuildEventLogFromDB(), and LogGuildEvent().
m_Id
uint32 Guild::m_Id protected
Definition at line 452 of file Guild.h.
Referenced by AddMember(), Create(), CreateDefaultGuildRanks(), CreateNewBankTab(), CreateRank(), DelRank(), Disband(), GetId(), GetMemberMoneyWithdrawRem(), GetMemberSlotWithdrawRem(), Guild(), LoadBankRightsFromDB(), LoadGuildBankEventLogFromDB(), LoadGuildBankFromDB(), LoadGuildEventLogFromDB(), LoadGuildFromDB(), LoadMembersFromDB(), LoadRanksFromDB(), LogBankEvent(), LogGuildEvent(), MemberItemWithdraw(), MemberMoneyWithdraw(), MoveFromBankToChar(), MoveFromCharToBank(), Query(), SetBankMoney(), SetBankMoneyPerDay(), SetBankRightsAndSlots(), SetEmblem(), SetGINFO(), SetGuildBankTabInfo(), SetGuildBankTabText(), SetLeader(), SetMOTD(), SetRankName(), and SetRankRights().
m_LeaderGuid
ObjectGuid Guild::m_LeaderGuid protected
Definition at line 454 of file Guild.h.
Referenced by CheckGuildStructure(), Create(), DelMember(), GetLeaderGuid(), LoadGuildFromDB(), and SetLeader().
m_Name
std::string Guild::m_Name protected
Definition at line 453 of file Guild.h.
Referenced by Create(), GetName(), Guild(), LoadGuildFromDB(), and Query().
m_Ranks
RankList Guild::m_Ranks protected
Definition at line 466 of file Guild.h.
Referenced by AddRank(), CreateRank(), DelRank(), GetBankMoneyPerDay(), GetBankRights(), GetBankSlotPerDay(), GetLowestRank(), GetRankName(), GetRankRights(), GetRanksSize(), LoadMembersFromDB(), LoadRanksFromDB(), Query(), Roster(), SetBankMoneyPerDay(), SetBankRightsAndSlots(), SetRankName(), and SetRankRights().
m_TabList
std::vector<GuildBankTab> Guild::m_TabList protected
Definition at line 470 of file Guild.h.
Referenced by _CanStoreItem_InSpecificSlot(), _CanStoreItem_InTab(), _StoreItem(), CreateNewBankTab(), DeleteGuildBankItems(), DisplayGuildBankContent(), DisplayGuildBankContentUpdate(), DisplayGuildBankTabsInfo(), GetItem(), GetPurchasedTabs(), LoadGuildBankFromDB(), LoadGuildFromDB(), RemoveItem(), SendGuildBankTabText(), SetGuildBankTabInfo(), and SetGuildBankTabText().
members
MemberList Guild::members protected
Definition at line 468 of file Guild.h.
Referenced by AddMember(), BroadcastPacket(), BroadcastPacketToRank(), BroadcastToGuild(), BroadcastToOfficers(), BroadcastWorker(), CheckGuildStructure(), DelMember(), Disband(), DisplayGuildBankContentUpdate(), GetAccountsNumber(), GetMemberMoneyWithdrawRem(), GetMemberSize(), GetMemberSlot(), GetMemberSlotWithdrawRem(), IsMemberHaveRights(), LoadMembersFromDB(), MassInviteToEvent(), MemberItemWithdraw(), MemberMoneyWithdraw(), Roster(), SetBankMoneyPerDay(), and SetBankRightsAndSlots().
MOTD
std::string Guild::MOTD protected
Definition at line 455 of file Guild.h.
Referenced by Create(), GetMOTD(), Guild(), LoadGuildFromDB(), Roster(), and SetMOTD().
The documentation for this class was generated from the following files:
Guild.h
Guild.cpp