CMaNGOS_WoTLK: MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck Class Reference
MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyFriendlyOrGroupMemberUnitInUnitRangeCheck (Unit const *obj, Unit const *target, Group const *group, SpellEntry const *spellInfo, float range)
Unit const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Group const * i_group
Unit const * i_obj
Unit const * i_target
SpellEntry const * i_spellInfo
float i_range
Detailed Description
Definition at line 1178 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyFriendlyOrGroupMemberUnitInUnitRangeCheck()
MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck (Unit const * obj, Unit const * target, Group const * group, SpellEntry const * spellInfo, float range) inline
Definition at line 1181 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
Unit const& MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::GetFocusObject () const inline
Definition at line 1183 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::operator() (Unit * u) inline
Definition at line 1184 of file GridNotifiers.h.
References Unit::CanAssistSpell(), Unit::GetOwner(), Object::GetTypeId(), i_group, i_obj, i_range, i_spellInfo, i_target, Unit::IsAlive(), Object::IsCreature(), Creature::IsPet(), WorldObject::IsWithinDistInMap(), TYPEID_PLAYER, and TYPEID_UNIT.
Field Documentation
i_group
Group const* MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::i_group private
Definition at line 1233 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Unit const* MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::i_obj private
Definition at line 1234 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::i_range private
Definition at line 1237 of file GridNotifiers.h.
Referenced by operator()().
i_spellInfo
SpellEntry const* MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::i_spellInfo private
Definition at line 1236 of file GridNotifiers.h.
Referenced by operator()().
i_target
Unit const* MaNGOS::AnyFriendlyOrGroupMemberUnitInUnitRangeCheck::i_target private
Definition at line 1235 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h