CMaNGOS_WoTLK: GMTicket Class Reference
GMTicket Class Reference
#include <GMTicketMgr.h>
Public Member Functions
GMTicket (Player *player, std::string message, uint8 category, time_t when=time(nullptr))
GMTicket (Field *fields)
void Load (Field *fields)
void Save (SqlStatement &stmt) const
void Recycle (Player *player, std::string message, uint8 category, time_t when=time(nullptr))
uint32 GetId () const
std::string GetIdTag () const
uint8 GetCategory () const
GMTicketState GetState () const
GMTicketEscalationStatus GetStatus () const
uint8 GetLevel () const
ObjectGuid const & GetAuthorGuid () const
const char * GetAuthorName () const
const char * GetLocale () const
LocaleConstant GetDbcLocale () const
int GetDbLocaleIndex () const
uint32 GetMapId () const
Position GetPosition () const
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
float GetPositionO () const
const char * GetText () const
time_t GetCreatedAt () const
time_t GetUpdatedAt () const
time_t GetSeenAt () const
time_t GetAnsweredAt () const
time_t GetClosedAt () const
ObjectGuid const & GetAssigneeGuid () const
const char * GetAssigneeName () const
std::string const & GetConclusion () const
std::string const & GetNotes () const
bool IsAssignedTo (ObjectGuid guid) const
bool IsAssignedTo (const char *name) const
bool IsAssigned () const
bool IsEscalated () const
bool IsOpen () const
bool IsSeen () const
bool IsSurveyed () const
void AddNote (const std::string &line)
void SetState (GMTicketState state, time_t when=time(nullptr))
void SetCategory (uint8 id)
void SetAnswered (time_t when)
void SetSeen (time_t when)
void SetUpdated (const std::string &text, time_t when=time(nullptr))
void SetAssignee (uint8 level, WorldSession *session=nullptr)
void SetConclusion (const std::string &response)
void UpdateStatsChat (bool incoming)
time_t GetLastSeenAt () const
Static Public Member Functions
static bool Compare (GMTicket *a, GMTicket *b)
static std::string GetIdTag (uint32 id)
Private Attributes
uint32 m_id
uint8 m_category
GMTicketState m_state
GMTicketEscalationStatus m_status
uint8 m_level
ObjectGuid m_authorGuid
std::string m_authorName
std::string m_locale
uint32 m_map
float m_x
float m_y
float m_z
float m_o
std::string m_text
time_t m_created
time_t m_updated
time_t m_seen
time_t m_answered
time_t m_closed
ObjectGuid m_assigneeGuid
std::string m_assigneeName
std::string m_conclusion
std::string m_notes
uint32 m_statsChatIn
uint32 m_statsChatOut
uint32 m_statsEscalations
time_t m_statsLastSeen
Detailed Description
Definition at line 93 of file GMTicketMgr.h.
Constructor & Destructor Documentation
GMTicket() [1/2]
GMTicket::GMTicket (Player * player, std::string message, uint8 category, time_t when = time(nullptr)) explicit
Definition at line 57 of file GMTicketMgr.cpp.
References DEFAULT_LOCALE, WorldObject::GetMapId(), WorldObject::GetName(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldSession::GetSecurity(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, GMTICKET_STATE_OPEN, localeNames, m_answered, m_assigneeGuid, m_assigneeName, m_authorGuid, m_authorName, m_category, m_closed, m_conclusion, m_created, m_id, m_level, m_locale, m_map, m_notes, m_o, m_seen, m_state, m_statsChatIn, m_statsChatOut, m_statsEscalations, m_statsLastSeen, m_status, m_text, m_updated, m_x, m_y, m_z, SEC_PLAYER, sTicketMgr, and utf8limit().
GMTicket() [2/2]
GMTicket::GMTicket (Field * fields) inline explicit
Definition at line 97 of file GMTicketMgr.h.
References Load().
Member Function Documentation
AddNote()
void GMTicket::AddNote (const std::string & line) inline
Definition at line 143 of file GMTicketMgr.h.
References m_notes.
Referenced by GMTicketMgr::Comment().
Compare()
bool GMTicket::Compare (GMTicket * a, GMTicket * b) static
Definition at line 39 of file GMTicketMgr.cpp.
References GetCreatedAt(), IsEscalated(), IsOpen(), and IsSeen().
Referenced by GMTicketMgr::Escalate(), GMTicketMgr::LoadGMTickets(), GMTicketMgr::Read(), GMTicketMgr::Recycle(), and GMTicketMgr::Update().
GetAnsweredAt()
time_t GMTicket::GetAnsweredAt () const inline
Definition at line 127 of file GMTicketMgr.h.
References m_answered.
Referenced by GMTicketMgr::Print().
GetAssigneeGuid()
ObjectGuid const& GMTicket::GetAssigneeGuid () const inline
Definition at line 129 of file GMTicketMgr.h.
References m_assigneeGuid.
Referenced by GMTicketMgr::Close(), GMTicketMgr::Escalate(), GMTicketMgr::Print(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), and GMTicketMgr::TicketChatOutgoing().
GetAssigneeName()
const char* GMTicket::GetAssigneeName () const inline
Definition at line 130 of file GMTicketMgr.h.
References m_assigneeName.
Referenced by GMTicketMgr::Close(), GMTicketMgr::Print(), GMTicketMgr::PrintMailResponse(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), and GMTicketMgr::Whisper().
GetAuthorGuid()
ObjectGuid const& GMTicket::GetAuthorGuid () const inline
Definition at line 112 of file GMTicketMgr.h.
References m_authorGuid.
Referenced by GMTicketMgr::Close(), GMTicketMgr::Escalate(), GMTicketMgr::GetTicketByPlayer(), GMTicketMgr::Print(), GMTicketMgr::PrintTicketSummaryLine(), GMTicketMgr::Read(), GMTicketMgr::SetSystemStatus(), GMTicketMgr::Sort(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), GMTicketMgr::Update(), GMTicketMgr::UpdateTicketQueueTimers(), and GMTicketMgr::Whisper().
GetAuthorName()
const char* GMTicket::GetAuthorName () const inline
Definition at line 113 of file GMTicketMgr.h.
References m_authorName.
Referenced by GMTicketMgr::Add(), GMTicketMgr::CanClose(), GMTicketMgr::Close(), ChatHandler::HandleTicketGoNameCommand(), GMTicketMgr::HookGMTicketWhisper(), GMTicketMgr::Print(), GMTicketMgr::PrintTicketSummaryLine(), GMTicketMgr::Recycle(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), and GMTicketMgr::TicketChatOutgoing().
GetCategory()
uint8 GMTicket::GetCategory () const inline
Definition at line 108 of file GMTicketMgr.h.
References m_category.
Referenced by GMTicketMgr::Print(), GMTicketMgr::PrintTicketCategory(), GMTicketMgr::PrintTicketSummaryLine(), WorldSession::SendGMTicket(), and GMTicketMgr::Sort().
GetClosedAt()
time_t GMTicket::GetClosedAt () const inline
Definition at line 128 of file GMTicketMgr.h.
References m_closed.
Referenced by GMTicketMgr::Print().
GetConclusion()
std::string const& GMTicket::GetConclusion () const inline
Definition at line 131 of file GMTicketMgr.h.
References m_conclusion.
Referenced by GMTicketMgr::Print(), GMTicketMgr::PrintMailResponse(), and WorldSession::SendGMTicketResponse().
GetCreatedAt()
time_t GMTicket::GetCreatedAt () const inline
Definition at line 124 of file GMTicketMgr.h.
References m_created.
Referenced by Compare(), GMTicketMgr::Print(), WorldSession::SendGMTicket(), and GMTicketMgr::UpdateTicketQueueStats().
GetDbcLocale()
LocaleConstant GMTicket::GetDbcLocale () const inline
Definition at line 205 of file GMTicketMgr.cpp.
References GetLocaleByName(), m_locale, and sWorld.
Referenced by GetDbLocaleIndex().
GetDbLocaleIndex()
int GMTicket::GetDbLocaleIndex () const inline
Definition at line 210 of file GMTicketMgr.cpp.
References GetDbcLocale(), and sObjectMgr.
GetId()
uint32 GMTicket::GetId () const inline
Definition at line 105 of file GMTicketMgr.h.
References m_id.
Referenced by GMTicketMgr::Add(), GMTicketMgr::HookGMTicketWhisper(), GMTicketMgr::Print(), GMTicketMgr::PrintTicketSummaryLine(), GMTicketMgr::Recycle(), GMTicketMgr::Remove(), GMTicketMgr::Save(), WorldSession::SendGMTicket(), and WorldSession::SendGMTicketResponse().
GetIdTag() [1/2]
std::string GMTicket::GetIdTag () const inline
Definition at line 107 of file GMTicketMgr.h.
References GetIdTag(), and m_id.
Referenced by GetIdTag(), ChatHandler::HandleTicketGoCommand(), ChatHandler::HandleTicketGoNameCommand(), and HandleTicketMgrCommandResult().
GetIdTag() [2/2]
static std::string GMTicket::GetIdTag (uint32 id) inline static
Definition at line 106 of file GMTicketMgr.h.
Referenced by GMTicketMgr::Abandon(), GMTicketMgr::Add(), GMTicketMgr::Close(), GMTicketMgr::Comment(), GMTicketMgr::Escalate(), GMTicketMgr::Recycle(), GMTicketMgr::Sort(), GMTicketMgr::Survey(), GMTicketMgr::TicketChatAlert(), GMTicketMgr::TicketChatIncoming(), GMTicketMgr::TicketChatOutgoing(), GMTicketMgr::Update(), and GMTicketMgr::Whisper().
GetLastSeenAt()
time_t GMTicket::GetLastSeenAt () const inline
Definition at line 157 of file GMTicketMgr.h.
References m_statsLastSeen.
Referenced by GMTicketMgr::Print().
GetLevel()
uint8 GMTicket::GetLevel () const inline
Definition at line 111 of file GMTicketMgr.h.
References m_level.
Referenced by GMTicketMgr::CanClose(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), GMTicketMgr::Escalate(), GMTicketMgr::Print(), and GMTicketMgr::PrintTicketSummaryLine().
GetLocale()
const char* GMTicket::GetLocale () const inline
Definition at line 114 of file GMTicketMgr.h.
References m_locale.
Referenced by GMTicketMgr::Close(), GMTicketMgr::Print(), GMTicketMgr::PrintMailResponse(), and GMTicketMgr::PrintTicketSummaryLine().
GetMapId()
uint32 GMTicket::GetMapId () const inline
Definition at line 117 of file GMTicketMgr.h.
References m_map.
Referenced by ChatHandler::HandleTicketGoCommand(), and GMTicketMgr::Print().
GetNotes()
std::string const& GMTicket::GetNotes () const inline
Definition at line 132 of file GMTicketMgr.h.
References m_notes.
Referenced by GMTicketMgr::Print().
GetPosition()
Position GMTicket::GetPosition () const inline
Definition at line 118 of file GMTicketMgr.h.
References m_o, m_x, m_y, and m_z.
GetPositionO()
float GMTicket::GetPositionO () const inline
Definition at line 122 of file GMTicketMgr.h.
References m_o.
Referenced by ChatHandler::HandleTicketGoCommand().
GetPositionX()
float GMTicket::GetPositionX () const inline
Definition at line 119 of file GMTicketMgr.h.
References m_x.
Referenced by ChatHandler::HandleTicketGoCommand(), and GMTicketMgr::Print().
GetPositionY()
float GMTicket::GetPositionY () const inline
Definition at line 120 of file GMTicketMgr.h.
References m_y.
Referenced by ChatHandler::HandleTicketGoCommand(), and GMTicketMgr::Print().
GetPositionZ()
float GMTicket::GetPositionZ () const inline
Definition at line 121 of file GMTicketMgr.h.
References m_z.
Referenced by ChatHandler::HandleTicketGoCommand(), and GMTicketMgr::Print().
GetSeenAt()
time_t GMTicket::GetSeenAt () const inline
Definition at line 126 of file GMTicketMgr.h.
References m_seen.
GetState()
GMTicketState GMTicket::GetState () const inline
Definition at line 109 of file GMTicketMgr.h.
References m_state.
Referenced by GMTicketMgr::GetTicketByPlayer(), GMTicketMgr::PrintTicketStatus(), GMTicketMgr::PrintTicketStatusColorSequence(), and GMTicketMgr::Recycle().
GetStatus()
GMTicketEscalationStatus GMTicket::GetStatus () const inline
Definition at line 110 of file GMTicketMgr.h.
References m_status.
Referenced by GMTicketMgr::PrintTicketStatus(), GMTicketMgr::PrintTicketStatusColorSequence(), and WorldSession::SendGMTicket().
GetText()
const char* GMTicket::GetText () const inline
Definition at line 123 of file GMTicketMgr.h.
References m_text.
Referenced by GMTicketMgr::Print(), WorldSession::SendGMTicket(), WorldSession::SendGMTicketResponse(), and GMTicketMgr::Update().
GetUpdatedAt()
time_t GMTicket::GetUpdatedAt () const inline
Definition at line 125 of file GMTicketMgr.h.
References m_updated.
Referenced by GMTicketMgr::Print().
IsAssigned()
bool GMTicket::IsAssigned () const inline
Definition at line 137 of file GMTicketMgr.h.
References GMTICKET_ASSIGNEDTOGM_STATUS_ASSIGNED, and m_status.
Referenced by GMTicketMgr::CanClose(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), GMTicketMgr::Escalate(), GMTicketMgr::GetTicketByPlayer(), SetAssignee(), GMTicketMgr::TicketChatAlert(), and GMTicketMgr::Whisper().
IsAssignedTo() [1/2]
bool GMTicket::IsAssignedTo (const char * name) const inline
Definition at line 135 of file GMTicketMgr.h.
References m_assigneeName.
IsAssignedTo() [2/2]
bool GMTicket::IsAssignedTo (ObjectGuid guid) const inline
Definition at line 134 of file GMTicketMgr.h.
References m_assigneeGuid.
Referenced by GMTicketMgr::CanClose(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), GMTicketMgr::Escalate(), GMTicketMgr::GetTicketByPlayer(), and GMTicketMgr::TicketChatAlert().
IsEscalated()
bool GMTicket::IsEscalated () const inline
Definition at line 138 of file GMTicketMgr.h.
References GMTICKET_ASSIGNEDTOGM_STATUS_ESCALATED, and m_status.
Referenced by Compare(), GMTicketMgr::Escalate(), Load(), SetAssignee(), SetUpdated(), GMTicketMgr::Update(), and GMTicketMgr::UpdateTicketQueueTimers().
IsOpen()
bool GMTicket::IsOpen () const inline
Definition at line 139 of file GMTicketMgr.h.
References GMTICKET_STATE_OPEN, and m_state.
Referenced by GMTicketMgr::Abandon(), GMTicketMgr::Add(), GMTicketMgr::CanClose(), GMTicketMgr::CanComment(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), Compare(), GMTicketMgr::Escalate(), GMTicketMgr::Print(), GMTicketMgr::Read(), GMTicketMgr::Remove(), GMTicketMgr::SetSystemStatus(), SetUpdated(), GMTicketMgr::Survey(), GMTicketMgr::Update(), and GMTicketMgr::UpdateTicketQueueTimers().
IsSeen()
bool GMTicket::IsSeen () const inline
Definition at line 140 of file GMTicketMgr.h.
References m_seen, and m_updated.
Referenced by GMTicketMgr::CanClose(), GMTicketMgr::CanComment(), GMTicketMgr::CanSort(), GMTicketMgr::CanWhisper(), Compare(), GMTicketMgr::Escalate(), GMTicketMgr::PrintTicketStatus(), GMTicketMgr::PrintTicketStatusColorSequence(), GMTicketMgr::Read(), WorldSession::SendGMTicket(), and GMTicketMgr::UpdateTicketQueueTimers().
IsSurveyed()
bool GMTicket::IsSurveyed () const inline
Definition at line 141 of file GMTicketMgr.h.
References GMTICKET_STATE_CLOSED, m_state, m_statsChatIn, m_statsChatOut, and m_statsEscalations.
Referenced by GMTicketMgr::Close(), and GMTicketMgr::Survey().
Load()
void GMTicket::Load (Field * fields)
Definition at line 93 of file GMTicketMgr.cpp.
References clamp(), Field::GetCppString(), Field::GetFloat(), Field::GetString(), Field::GetUInt32(), Field::GetUInt8(), GMTICKET_ASSIGNEDTOGM_STATUS_ESCALATED, GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, GMTICKET_STATE_ABANDONED, GMTICKET_STATE_OPEN, HIGHGUID_PLAYER, IsEscalated(), m_answered, m_assigneeGuid, m_assigneeName, m_authorGuid, m_authorName, m_category, m_closed, m_conclusion, m_created, m_id, m_level, m_locale, m_map, m_notes, m_o, m_seen, m_state, m_statsChatIn, m_statsChatOut, m_statsEscalations, m_statsLastSeen, m_status, m_text, m_updated, m_x, m_y, m_z, and utf8limit().
Referenced by GMTicket().
Recycle()
void GMTicket::Recycle (Player * player, std::string message, uint8 category, time_t when = time(nullptr))
Definition at line 171 of file GMTicketMgr.cpp.
References DEFAULT_LOCALE, WorldObject::GetMapId(), WorldObject::GetName(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldSession::GetSecurity(), Player::GetSession(), WorldSession::GetSessionDbcLocale(), GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, localeNames, m_answered, m_assigneeGuid, m_assigneeName, m_authorGuid, m_authorName, m_category, m_closed, m_conclusion, m_created, m_level, m_locale, m_map, m_notes, m_o, m_seen, m_statsChatIn, m_statsChatOut, m_statsEscalations, m_statsLastSeen, m_status, m_text, m_updated, m_x, m_y, m_z, SEC_PLAYER, and utf8limit().
Save()
void GMTicket::Save (SqlStatement & stmt) const inline
Definition at line 127 of file GMTicketMgr.cpp.
References SqlStatement::addFloat(), SqlStatement::addString(), SqlStatement::addUInt32(), SqlStatement::addUInt64(), SqlStatement::addUInt8(), ObjectGuid::GetCounter(), m_answered, m_assigneeGuid, m_assigneeName, m_authorGuid, m_authorName, m_category, m_closed, m_conclusion, m_created, m_id, m_level, m_locale, m_map, m_notes, m_o, m_seen, m_state, m_status, m_text, m_updated, m_x, m_y, and m_z.
Referenced by GMTicketMgr::Save().
SetAnswered()
void GMTicket::SetAnswered (time_t when) inline
Definition at line 148 of file GMTicketMgr.h.
References m_answered.
Referenced by GMTicketMgr::Whisper().
SetAssignee()
void GMTicket::SetAssignee (uint8 level, WorldSession * session = nullptr)
Definition at line 244 of file GMTicketMgr.cpp.
References WorldSession::GetPlayer(), WorldSession::GetPlayerName(), GMTICKET_ASSIGNEDTOGM_STATUS_ASSIGNED, GMTICKET_ASSIGNEDTOGM_STATUS_ESCALATED, IsAssigned(), IsEscalated(), m_assigneeGuid, m_assigneeName, m_level, m_statsEscalations, and m_status.
Referenced by GMTicketMgr::Close(), GMTicketMgr::Escalate(), and GMTicketMgr::Whisper().
SetCategory()
void GMTicket::SetCategory (uint8 id) inline
Definition at line 146 of file GMTicketMgr.h.
References m_category.
Referenced by GMTicketMgr::Sort().
SetConclusion()
void GMTicket::SetConclusion (const std::string & response) inline
Definition at line 153 of file GMTicketMgr.h.
References m_conclusion.
Referenced by GMTicketMgr::Close().
SetSeen()
void GMTicket::SetSeen (time_t when) inline
Definition at line 149 of file GMTicketMgr.h.
References m_seen, and m_statsLastSeen.
Referenced by GMTicketMgr::Read().
SetState()
void GMTicket::SetState (GMTicketState state, time_t when = time(nullptr))
Definition at line 215 of file GMTicketMgr.cpp.
References GMTICKET_STATE_ABANDONED, GMTICKET_STATE_CLOSED, m_closed, m_notes, m_state, and m_text.
Referenced by GMTicketMgr::Abandon(), GMTicketMgr::Close(), and GMTicketMgr::Recycle().
SetUpdated()
void GMTicket::SetUpdated (const std::string & text, time_t when = time(nullptr))
Definition at line 229 of file GMTicketMgr.cpp.
References GMTICKET_ASSIGNEDTOGM_STATUS_NOT_ASSIGNED, IsEscalated(), IsOpen(), m_status, m_text, m_updated, and utf8limit().
Referenced by GMTicketMgr::Update().
UpdateStatsChat()
void GMTicket::UpdateStatsChat (bool incoming)
Definition at line 267 of file GMTicketMgr.cpp.
References m_statsChatIn, and m_statsChatOut.
Referenced by GMTicketMgr::TicketChatIncoming(), and GMTicketMgr::TicketChatOutgoing().
Field Documentation
m_answered
time_t GMTicket::m_answered private
Definition at line 177 of file GMTicketMgr.h.
Referenced by GetAnsweredAt(), GMTicket(), Load(), Recycle(), Save(), and SetAnswered().
m_assigneeGuid
ObjectGuid GMTicket::m_assigneeGuid private
Definition at line 179 of file GMTicketMgr.h.
Referenced by GetAssigneeGuid(), GMTicket(), IsAssignedTo(), Load(), Recycle(), Save(), and SetAssignee().
m_assigneeName
std::string GMTicket::m_assigneeName private
Definition at line 180 of file GMTicketMgr.h.
Referenced by GetAssigneeName(), GMTicket(), IsAssignedTo(), Load(), Recycle(), Save(), and SetAssignee().
m_authorGuid
ObjectGuid GMTicket::m_authorGuid private
Definition at line 165 of file GMTicketMgr.h.
Referenced by GetAuthorGuid(), GMTicket(), Load(), Recycle(), and Save().
m_authorName
std::string GMTicket::m_authorName private
Definition at line 166 of file GMTicketMgr.h.
Referenced by GetAuthorName(), GMTicket(), Load(), Recycle(), and Save().
m_category
uint8 GMTicket::m_category private
Definition at line 161 of file GMTicketMgr.h.
Referenced by GetCategory(), GMTicket(), Load(), Recycle(), Save(), and SetCategory().
m_closed
time_t GMTicket::m_closed private
Definition at line 178 of file GMTicketMgr.h.
Referenced by GetClosedAt(), GMTicket(), Load(), Recycle(), Save(), and SetState().
m_conclusion
std::string GMTicket::m_conclusion private
Definition at line 181 of file GMTicketMgr.h.
Referenced by GetConclusion(), GMTicket(), Load(), Recycle(), Save(), and SetConclusion().
m_created
time_t GMTicket::m_created private
Definition at line 174 of file GMTicketMgr.h.
Referenced by GetCreatedAt(), GMTicket(), Load(), Recycle(), and Save().
m_id
uint32 GMTicket::m_id private
Definition at line 160 of file GMTicketMgr.h.
Referenced by GetId(), GetIdTag(), GMTicket(), Load(), and Save().
m_level
uint8 GMTicket::m_level private
Definition at line 164 of file GMTicketMgr.h.
Referenced by GetLevel(), GMTicket(), Load(), Recycle(), Save(), and SetAssignee().
m_locale
std::string GMTicket::m_locale private
Definition at line 167 of file GMTicketMgr.h.
Referenced by GetDbcLocale(), GetLocale(), GMTicket(), Load(), Recycle(), and Save().
m_map
uint32 GMTicket::m_map private
Definition at line 168 of file GMTicketMgr.h.
Referenced by GetMapId(), GMTicket(), Load(), Recycle(), and Save().
m_notes
std::string GMTicket::m_notes private
Definition at line 182 of file GMTicketMgr.h.
Referenced by AddNote(), GetNotes(), GMTicket(), Load(), Recycle(), Save(), and SetState().
m_o
float GMTicket::m_o private
Definition at line 172 of file GMTicketMgr.h.
Referenced by GetPosition(), GetPositionO(), GMTicket(), Load(), Recycle(), and Save().
m_seen
time_t GMTicket::m_seen private
Definition at line 176 of file GMTicketMgr.h.
Referenced by GetSeenAt(), GMTicket(), IsSeen(), Load(), Recycle(), Save(), and SetSeen().
m_state
GMTicketState GMTicket::m_state private
Definition at line 162 of file GMTicketMgr.h.
Referenced by GetState(), GMTicket(), IsOpen(), IsSurveyed(), Load(), Save(), and SetState().
m_statsChatIn
uint32 GMTicket::m_statsChatIn private
Definition at line 185 of file GMTicketMgr.h.
Referenced by GMTicket(), IsSurveyed(), Load(), Recycle(), and UpdateStatsChat().
m_statsChatOut
uint32 GMTicket::m_statsChatOut private
Definition at line 186 of file GMTicketMgr.h.
Referenced by GMTicket(), IsSurveyed(), Load(), Recycle(), and UpdateStatsChat().
m_statsEscalations
uint32 GMTicket::m_statsEscalations private
Definition at line 187 of file GMTicketMgr.h.
Referenced by GMTicket(), IsSurveyed(), Load(), Recycle(), and SetAssignee().
m_statsLastSeen
time_t GMTicket::m_statsLastSeen private
Definition at line 188 of file GMTicketMgr.h.
Referenced by GetLastSeenAt(), GMTicket(), Load(), Recycle(), and SetSeen().
m_status
GMTicketEscalationStatus GMTicket::m_status private
Definition at line 163 of file GMTicketMgr.h.
Referenced by GetStatus(), GMTicket(), IsAssigned(), IsEscalated(), Load(), Recycle(), Save(), SetAssignee(), and SetUpdated().
m_text
std::string GMTicket::m_text private
Definition at line 173 of file GMTicketMgr.h.
Referenced by GetText(), GMTicket(), Load(), Recycle(), Save(), SetState(), and SetUpdated().
m_updated
time_t GMTicket::m_updated private
Definition at line 175 of file GMTicketMgr.h.
Referenced by GetUpdatedAt(), GMTicket(), IsSeen(), Load(), Recycle(), Save(), and SetUpdated().
m_x
float GMTicket::m_x private
Definition at line 169 of file GMTicketMgr.h.
Referenced by GetPosition(), GetPositionX(), GMTicket(), Load(), Recycle(), and Save().
m_y
float GMTicket::m_y private
Definition at line 170 of file GMTicketMgr.h.
Referenced by GetPosition(), GetPositionY(), GMTicket(), Load(), Recycle(), and Save().
m_z
float GMTicket::m_z private
Definition at line 171 of file GMTicketMgr.h.
Referenced by GetPosition(), GetPositionZ(), GMTicket(), Load(), Recycle(), and Save().
The documentation for this class was generated from the following files:
GMTicketMgr.h
GMTicketMgr.cpp