CMaNGOS_WoTLK: OutdoorPvPGH Class Reference
OutdoorPvPGH Class Reference
#include <OutdoorPvPGH.h>
Public Member Functions
OutdoorPvPGH ()
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleCreatureCreate (Creature *creature) override
void HandleCreatureDeath (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void FillInitialWorldStates (WorldPacket &, uint32 &)
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleGameObjectRemove (GameObject *)
virtual bool HandleGameObjectUse (Player *, GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
void DespawnVendors (const WorldObject *objRef)
void LockLighthouse (const WorldObject *objRef)
void UnlockLighthouse (const WorldObject *objRef)
Private Attributes
Team m_zoneOwner
GuidList m_teamVendors
ObjectGuid m_capturePoint
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterZone (Player *, bool)
virtual void HandlePlayerLeaveZone (Player *, bool)
Function that removes a player from the players of the affected outdoor pvp zones.
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
virtual void SendRemoveWorldStates (Player *)
virtual void HandlePlayerKillInsideArea (Player *, Unit *)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 58 of file OutdoorPvPGH.h.
Constructor & Destructor Documentation
OutdoorPvPGH()
OutdoorPvPGH::OutdoorPvPGH ()
Definition at line 25 of file OutdoorPvPGH.cpp.
Member Function Documentation
DespawnVendors()
void OutdoorPvPGH::DespawnVendors (const WorldObject * objRef) private
Definition at line 131 of file OutdoorPvPGH.cpp.
References Map::GetCreature(), WorldObject::GetMap(), and m_teamVendors.
Referenced by HandleEvent().
HandleCreatureCreate()
void OutdoorPvPGH::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 30 of file OutdoorPvPGH.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), Creature::IsTemporarySummon(), m_teamVendors, NPC_BLACKSMITH_JASON_RIGGINS, NPC_BLACKSMITH_KOLOTH, NPC_HORSE, NPC_RIDING_WOLF, NPC_STABLE_MASTER_KOR, NPC_STABLE_MASTER_TIM, NPC_VENDOR_ADAMS, and NPC_VENDOR_PURKOM.
HandleCreatureDeath()
void OutdoorPvPGH::HandleCreatureDeath (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 51 of file OutdoorPvPGH.cpp.
References Object::GetEntry(), NPC_COMMANDER_HOWSER, NPC_GENERAL_GORLOK, and UnlockLighthouse().
HandleEvent()
bool OutdoorPvPGH::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 76 of file OutdoorPvPGH.cpp.
References ALLIANCE, CAPTURE_ANIM_ALLIANCE, CAPTURE_ANIM_HORDE, CAPTURE_ANIM_NEUTRAL, CAPTURE_ARTKIT_ALLIANCE, CAPTURE_ARTKIT_HORDE, CAPTURE_ARTKIT_NEUTRAL, DespawnVendors(), EVENT_LIGHTHOUSE_NEUTRAL_ALLIANCE, EVENT_LIGHTHOUSE_NEUTRAL_HORDE, EVENT_LIGHTHOUSE_PROGRESS_ALLIANCE, EVENT_LIGHTHOUSE_PROGRESS_HORDE, EVENT_LIGHTHOUSE_WIN_ALLIANCE, EVENT_LIGHTHOUSE_WIN_HORDE, Object::GetEntry(), GO_VENTURE_BAY_LIGHTHOUSE, HORDE, Object::IsGameObject(), LockLighthouse(), m_zoneOwner, OutdoorPvP::SetBannerVisual(), and TEAM_NONE.
HandleGameObjectCreate()
void OutdoorPvPGH::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 64 of file OutdoorPvPGH.cpp.
References OutdoorPvP::GetBannerArtKit(), Object::GetEntry(), Object::GetObjectGuid(), GO_VENTURE_BAY_LIGHTHOUSE, OutdoorPvP::HandleGameObjectCreate(), m_capturePoint, m_zoneOwner, and GameObject::SetGoArtKit().
LockLighthouse()
void OutdoorPvPGH::LockLighthouse (const WorldObject * objRef) private
Definition at line 143 of file OutdoorPvPGH.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, Map::GetGameObject(), WorldObject::GetMap(), GO_JUST_DEACTIVATED, GO_VENTURE_BAY_LIGHTHOUSE, m_capturePoint, m_zoneOwner, and sOutdoorPvPMgr.
Referenced by HandleEvent().
UnlockLighthouse()
void OutdoorPvPGH::UnlockLighthouse (const WorldObject * objRef) private
Definition at line 156 of file OutdoorPvPGH.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, Map::GetGameObject(), WorldObject::GetMap(), GO_ACTIVATED, GO_VENTURE_BAY_LIGHTHOUSE, m_capturePoint, m_zoneOwner, and sOutdoorPvPMgr.
Referenced by HandleCreatureDeath().
Field Documentation
m_capturePoint
ObjectGuid OutdoorPvPGH::m_capturePoint private
Definition at line 80 of file OutdoorPvPGH.h.
Referenced by HandleGameObjectCreate(), LockLighthouse(), and UnlockLighthouse().
m_teamVendors
GuidList OutdoorPvPGH::m_teamVendors private
Definition at line 78 of file OutdoorPvPGH.h.
Referenced by DespawnVendors(), and HandleCreatureCreate().
m_zoneOwner
Team OutdoorPvPGH::m_zoneOwner private
Definition at line 76 of file OutdoorPvPGH.h.
Referenced by HandleEvent(), HandleGameObjectCreate(), LockLighthouse(), and UnlockLighthouse().
The documentation for this class was generated from the following files:
OutdoorPvPGH.h
OutdoorPvPGH.cpp