CMaNGOS_WoTLK: SpawnInfo Class Reference
SpawnInfo Class Reference
#include <SpawnManager.h>
Public Member Functions
SpawnInfo (TimePoint when, uint32 dbguid, HighGuid high)
TimePoint const & GetRespawnTime () const
void SetRespawnTime (TimePoint const &time)
bool ConstructForMap (Map &map)
uint32 GetDbGuid () const
HighGuid GetHighGuid () const
void SetUsed ()
bool IsUsed () const
Private Attributes
TimePoint m_respawnTime
uint32 m_dbguid
HighGuid m_high
bool m_used
bool m_inUse
Detailed Description
Definition at line 30 of file SpawnManager.h.
Constructor & Destructor Documentation
SpawnInfo()
SpawnInfo::SpawnInfo (TimePoint when, uint32 dbguid, HighGuid high) inline
Definition at line 33 of file SpawnManager.h.
Member Function Documentation
ConstructForMap()
bool SpawnInfo::ConstructForMap (Map & map)
Definition at line 30 of file SpawnManager.cpp.
References GetDbGuid(), GetHighGuid(), HIGHGUID_GAMEOBJECT, HIGHGUID_UNIT, m_inUse, SetUsed(), WorldObject::SpawnCreature(), and WorldObject::SpawnGameObject().
GetDbGuid()
uint32 SpawnInfo::GetDbGuid () const inline
Definition at line 37 of file SpawnManager.h.
References m_dbguid.
Referenced by ConstructForMap().
GetHighGuid()
HighGuid SpawnInfo::GetHighGuid () const inline
Definition at line 38 of file SpawnManager.h.
References m_high.
Referenced by ConstructForMap().
GetRespawnTime()
TimePoint const& SpawnInfo::GetRespawnTime () const inline
Definition at line 34 of file SpawnManager.h.
References m_respawnTime.
Referenced by operator<().
IsUsed()
bool SpawnInfo::IsUsed () const inline
Definition at line 40 of file SpawnManager.h.
References m_inUse, and m_used.
SetRespawnTime()
void SpawnInfo::SetRespawnTime (TimePoint const & time) inline
Definition at line 35 of file SpawnManager.h.
References m_respawnTime.
SetUsed()
void SpawnInfo::SetUsed () inline
Definition at line 39 of file SpawnManager.h.
References m_used.
Referenced by ConstructForMap().
Field Documentation
m_dbguid
uint32 SpawnInfo::m_dbguid private
Definition at line 43 of file SpawnManager.h.
Referenced by GetDbGuid().
m_high
HighGuid SpawnInfo::m_high private
Definition at line 44 of file SpawnManager.h.
Referenced by GetHighGuid().
m_inUse
bool SpawnInfo::m_inUse private
Definition at line 46 of file SpawnManager.h.
Referenced by ConstructForMap(), and IsUsed().
m_respawnTime
TimePoint SpawnInfo::m_respawnTime private
Definition at line 42 of file SpawnManager.h.
Referenced by GetRespawnTime(), and SetRespawnTime().
m_used
bool SpawnInfo::m_used private
Definition at line 45 of file SpawnManager.h.
Referenced by IsUsed(), and SetUsed().
The documentation for this class was generated from the following files:
SpawnManager.h
SpawnManager.cpp