CMaNGOS_WoTLK: BattleGroundScore Class Reference
BattleGroundScore Class Reference
#include <BattleGround.h>
Public Member Functions
BattleGroundScore ()
virtual ~BattleGroundScore ()
uint32 GetKillingBlows () const
uint32 GetDeaths () const
uint32 GetHonorableKills () const
uint32 GetBonusHonor () const
uint32 GetDamageDone () const
uint32 GetHealingDone () const
virtual uint32 GetAttr1 () const
virtual uint32 GetAttr2 () const
virtual uint32 GetAttr3 () const
virtual uint32 GetAttr4 () const
virtual uint32 GetAttr5 () const
Data Fields
uint32 killingBlows
uint32 deaths
uint32 honorableKills
uint32 bonusHonor
uint32 damageDone
uint32 healingDone
uint32 Team
Detailed Description
Definition at line 296 of file BattleGround.h.
Constructor & Destructor Documentation
BattleGroundScore()
BattleGroundScore::BattleGroundScore () inline
Definition at line 299 of file BattleGround.h.
~BattleGroundScore()
virtual BattleGroundScore::~BattleGroundScore () inline virtual
Definition at line 302 of file BattleGround.h.
Member Function Documentation
GetAttr1()
virtual uint32 BattleGroundScore::GetAttr1 () const inline virtual
Reimplemented in BattleGroundWGScore, BattleGroundAVScore, BattleGroundABScore, BattleGroundSAScore, and BattleGroundICScore.
Definition at line 311 of file BattleGround.h.
Referenced by BattleGround::EndBattleGround().
GetAttr2()
virtual uint32 BattleGroundScore::GetAttr2 () const inline virtual
Reimplemented in BattleGroundWGScore, BattleGroundAVScore, BattleGroundABScore, BattleGroundSAScore, and BattleGroundICScore.
Definition at line 312 of file BattleGround.h.
Referenced by BattleGround::EndBattleGround().
GetAttr3()
virtual uint32 BattleGroundScore::GetAttr3 () const inline virtual
Reimplemented in BattleGroundAVScore.
Definition at line 313 of file BattleGround.h.
Referenced by BattleGround::EndBattleGround().
GetAttr4()
virtual uint32 BattleGroundScore::GetAttr4 () const inline virtual
Reimplemented in BattleGroundAVScore.
Definition at line 314 of file BattleGround.h.
Referenced by BattleGround::EndBattleGround().
GetAttr5()
virtual uint32 BattleGroundScore::GetAttr5 () const inline virtual
Reimplemented in BattleGroundAVScore.
Definition at line 315 of file BattleGround.h.
Referenced by BattleGround::EndBattleGround().
GetBonusHonor()
uint32 BattleGroundScore::GetBonusHonor () const inline
Definition at line 307 of file BattleGround.h.
References bonusHonor.
Referenced by BattleGround::EndBattleGround().
GetDamageDone()
uint32 BattleGroundScore::GetDamageDone () const inline
Definition at line 308 of file BattleGround.h.
References damageDone.
Referenced by BattleGround::EndBattleGround().
GetDeaths()
uint32 BattleGroundScore::GetDeaths () const inline
Definition at line 305 of file BattleGround.h.
References deaths.
Referenced by BattleGround::EndBattleGround().
GetHealingDone()
uint32 BattleGroundScore::GetHealingDone () const inline
Definition at line 309 of file BattleGround.h.
References healingDone.
Referenced by BattleGround::EndBattleGround().
GetHonorableKills()
uint32 BattleGroundScore::GetHonorableKills () const inline
Definition at line 306 of file BattleGround.h.
References honorableKills.
Referenced by BattleGround::EndBattleGround().
GetKillingBlows()
uint32 BattleGroundScore::GetKillingBlows () const inline
Definition at line 304 of file BattleGround.h.
References killingBlows.
Referenced by BattleGround::EndBattleGround().
Field Documentation
bonusHonor
uint32 BattleGroundScore::bonusHonor
Definition at line 320 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetBonusHonor().
damageDone
uint32 BattleGroundScore::damageDone
Definition at line 321 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetDamageDone().
deaths
uint32 BattleGroundScore::deaths
Definition at line 318 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetDeaths().
healingDone
uint32 BattleGroundScore::healingDone
Definition at line 322 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetHealingDone().
honorableKills
uint32 BattleGroundScore::honorableKills
Definition at line 319 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetHonorableKills().
killingBlows
uint32 BattleGroundScore::killingBlows
Definition at line 317 of file BattleGround.h.
Referenced by BattleGroundMgr::BuildPvpLogDataPacket(), and GetKillingBlows().
Team
uint32 BattleGroundScore::Team
Definition at line 324 of file BattleGround.h.
Referenced by BattleGround::AddPlayer().
The documentation for this class was generated from the following file:
BattleGround.h