CMaNGOS_WoTLK: HashMapHolder< T > Class Template Reference
HashMapHolder< T > Class Template Reference
#include <ObjectAccessor.h>
Public Types
typedef std::unordered_map< ObjectGuid, T * > MapType
typedef std::mutex LockType
typedef std::lock_guard< std::mutex > ReadGuard
typedef std::lock_guard< std::mutex > WriteGuard
Static Public Member Functions
static void Insert (T *o)
static void Remove (T *o)
static T * Find (ObjectGuid guid)
static MapType & GetContainer ()
static LockType & GetLock ()
Private Member Functions
HashMapHolder ()
Static Private Attributes
static LockType i_lock
static MapType m_objectMap
Define the static member of HashMapHolder.
Detailed Description
template<class T>
class HashMapHolder< T >
Definition at line 42 of file ObjectAccessor.h.
Member Typedef Documentation
LockType
template<class T > typedef std::mutex HashMapHolder< T >::LockType
Definition at line 47 of file ObjectAccessor.h.
MapType
template<class T > typedef std::unordered_map<ObjectGuid, T*> HashMapHolder< T >::MapType
Definition at line 46 of file ObjectAccessor.h.
ReadGuard
template<class T > typedef std::lock_guard<std::mutex> HashMapHolder< T >::ReadGuard
Definition at line 48 of file ObjectAccessor.h.
WriteGuard
template<class T > typedef std::lock_guard<std::mutex> HashMapHolder< T >::WriteGuard
Definition at line 49 of file ObjectAccessor.h.
Constructor & Destructor Documentation
HashMapHolder()
template<class T > HashMapHolder< T >::HashMapHolder () inline private
Definition at line 64 of file ObjectAccessor.h.
Member Function Documentation
Find()
template<class T > T * HashMapHolder< T >::Find (ObjectGuid guid) static
Definition at line 53 of file ObjectAccessor.cpp.
Referenced by ObjectAccessor::FindPlayer(), ObjectAccessor::GetCorpseInMap(), and ScriptAction::GetScriptCommandObject().
GetContainer()
template<class T > HashMapHolder< T >::MapType & HashMapHolder< T >::GetContainer static
Definition at line 61 of file ObjectAccessor.cpp.
Referenced by ObjectAccessor::GetPlayers().
GetLock()
template<class T > HashMapHolder< T >::LockType & HashMapHolder< T >::GetLock static
Definition at line 64 of file ObjectAccessor.cpp.
Insert()
template<class T > void HashMapHolder< T >::Insert (T * o) static
Definition at line 39 of file ObjectAccessor.cpp.
Referenced by ObjectAccessor::AddObject().
Remove()
template<class T > void HashMapHolder< T >::Remove (T * o) static
Definition at line 46 of file ObjectAccessor.cpp.
Referenced by ObjectAccessor::RemoveObject().
Field Documentation
i_lock
template<class T > std::mutex HashMapHolder< T >::i_lock static private
Definition at line 66 of file ObjectAccessor.h.
m_objectMap
template<class T > HashMapHolder< T >::MapType HashMapHolder< T >::m_objectMap static private
Define the static member of HashMapHolder.
Definition at line 67 of file ObjectAccessor.h.
The documentation for this class was generated from the following files:
ObjectAccessor.h
ObjectAccessor.cpp