CMaNGOS_WoTLK: OutdoorPvPZM Class Reference
OutdoorPvPZM Class Reference
#include <OutdoorPvPZM.h>
Public Member Functions
OutdoorPvPZM ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleCreatureCreate (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
void HandlePlayerKillInsideArea (Player *player, Unit *) override
bool HandleGameObjectUse (Player *player, GameObject *go) override
bool IsConditionFulfilled (Player const *source, uint32 conditionId, WorldObject const *conditionSource, uint32 conditionSourceType) override
void HandleConditionStateChange (uint32 conditionId, bool state) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleObjectiveComplete (uint32, const PlayerList &, Team)
virtual void HandleGameObjectRemove (GameObject *)
virtual void HandleCreatureDeath (Creature *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
virtual void Update (uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
bool ProcessCaptureEvent (GameObject *go, uint32 towerId, Team team, uint32 newWorldState, uint32 newMapState)
void UpdateScoutState (Team team, bool spawned)
void SetBeaconArtKit (const WorldObject *objRef, ObjectGuid creatureGuid, uint32 auraId)
Private Attributes
uint32 m_towerWorldState [MAX_ZM_TOWERS]
uint32 m_towerMapState [MAX_ZM_TOWERS]
Team m_towerOwner [MAX_ZM_TOWERS]
Team m_graveyardOwner
uint32 m_graveyardWorldState
uint32 m_scoutWorldStateAlliance
uint32 m_scoutWorldStateHorde
uint8 m_towersAlliance
uint8 m_towersHorde
bool m_flagReady [PVP_TEAM_COUNT]
bool m_playerCarryingFlag [PVP_TEAM_COUNT]
ObjectGuid m_towerBanners [MAX_ZM_TOWERS]
ObjectGuid m_graveyardBannerAlliance
ObjectGuid m_graveyardBannerHorde
ObjectGuid m_graveyardBannerNeutral
ObjectGuid m_beamTowerBlue [MAX_ZM_TOWERS]
ObjectGuid m_beamTowerRed [MAX_ZM_TOWERS]
ObjectGuid m_beamGraveyardBlue
ObjectGuid m_beamGraveyardRed
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 109 of file OutdoorPvPZM.h.
Constructor & Destructor Documentation
OutdoorPvPZM()
OutdoorPvPZM::OutdoorPvPZM ()
Definition at line 28 of file OutdoorPvPZM.cpp.
References GRAVEYARD_ID_TWIN_SPIRE, GRAVEYARD_ZONE_TWIN_SPIRE, m_flagReady, m_playerCarryingFlag, m_towerMapState, m_towerOwner, m_towerWorldState, PVP_TEAM_COUNT, OutdoorPvP::SetGraveYardLinkTeam(), TEAM_INVALID, TEAM_NONE, WORLD_STATE_ZM_BEACON_EAST_NEUTRAL, WORLD_STATE_ZM_BEACON_EAST_UI_NEUTRAL, WORLD_STATE_ZM_BEACON_WEST_NEUTRAL, and WORLD_STATE_ZM_BEACON_WEST_UI_NEUTRAL.
Member Function Documentation
FillInitialWorldStates()
void OutdoorPvPZM::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 55 of file OutdoorPvPZM.cpp.
References FillInitialWorldState(), m_graveyardWorldState, m_scoutWorldStateAlliance, m_scoutWorldStateHorde, m_towerMapState, m_towerWorldState, MAX_ZM_TOWERS, and WORLD_STATE_ADD.
HandleConditionStateChange()
void OutdoorPvPZM::HandleConditionStateChange (uint32 conditionId, bool state) override virtual
Reimplemented from OutdoorPvP.
Definition at line 424 of file OutdoorPvPZM.cpp.
References m_playerCarryingFlag, OPVP_COND_ZM_ALLY_SCOUT_FLAG_READY, OPVP_COND_ZM_HORDE_SCOUT_FLAG_READY, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
HandleCreatureCreate()
void OutdoorPvPZM::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 101 of file OutdoorPvPZM.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionY(), m_beamGraveyardBlue, m_beamGraveyardRed, m_beamTowerBlue, m_beamTowerRed, NPC_PVP_BEAM_BLUE, and NPC_PVP_BEAM_RED.
HandleEvent()
bool OutdoorPvPZM::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 167 of file OutdoorPvPZM.cpp.
References Object::GetEntry(), Object::IsGameObject(), m_towerOwner, MAX_ZM_TOWERS, ProcessCaptureEvent(), sWorld, zangarmarshTowerEvents, zangarmarshTowers, and ZONE_ID_ZANGARMARSH.
HandleGameObjectCreate()
void OutdoorPvPZM::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 124 of file OutdoorPvPZM.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_ZANGA_BANNER_CENTER_ALLIANCE, GO_ZANGA_BANNER_CENTER_HORDE, GO_ZANGA_BANNER_CENTER_NEUTRAL, GO_ZANGA_BANNER_EAST, GO_ZANGA_BANNER_WEST, OutdoorPvP::HandleGameObjectCreate(), m_graveyardBannerAlliance, m_graveyardBannerHorde, m_graveyardBannerNeutral, and m_towerBanners.
HandleGameObjectUse()
bool OutdoorPvPZM::HandleGameObjectUse (Player * player, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 305 of file OutdoorPvPZM.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), Object::GetEntry(), Player::GetTeam(), GO_ZANGA_BANNER_CENTER_ALLIANCE, GO_ZANGA_BANNER_CENTER_HORDE, GO_ZANGA_BANNER_CENTER_NEUTRAL, GRAVEYARD_ID_TWIN_SPIRE, GRAVEYARD_ZONE_TWIN_SPIRE, Unit::HasAura(), HORDE, LANG_OPVP_ZM_CAPTURE_GRAVEYARD_A, LANG_OPVP_ZM_CAPTURE_GRAVEYARD_H, m_beamGraveyardBlue, m_beamGraveyardRed, m_graveyardBannerAlliance, m_graveyardBannerHorde, m_graveyardBannerNeutral, m_graveyardOwner, m_graveyardWorldState, Unit::RemoveAurasDueToSpell(), OutdoorPvP::RespawnGO(), OutdoorPvP::SendUpdateWorldState(), SetBeaconArtKit(), OutdoorPvP::SetGraveYardLinkTeam(), SPELL_BATTLE_STANDARD_ALLIANCE, SPELL_BATTLE_STANDARD_HORDE, SPELL_BEAM_BLUE, SPELL_BEAM_RED, SPELL_TWIN_SPIRE_BLESSING, sWorld, TEAM_NONE, UpdateScoutState(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_ZM_GRAVEYARD_ALLIANCE, WORLD_STATE_ZM_GRAVEYARD_HORDE, ZONE_ID_SERPENTSHRINE_CAVERN, ZONE_ID_SLAVE_PENS, ZONE_ID_STEAMVAULT, ZONE_ID_UNDERBOG, and ZONE_ID_ZANGARMARSH.
HandlePlayerEnterZone()
void OutdoorPvPZM::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 81 of file OutdoorPvPZM.cpp.
References Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), m_graveyardOwner, Unit::RemoveAurasDueToSpell(), SPELL_TWIN_SPIRE_BLESSING, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerKillInsideArea()
void OutdoorPvPZM::HandlePlayerKillInsideArea (Player * player, Unit * victim) override virtual
Reimplemented from OutdoorPvP.
Definition at line 149 of file OutdoorPvPZM.cpp.
References ALLIANCE, GameObjectInfo::capturePoint, Unit::CastSpell(), Map::GetGameObject(), WorldObject::GetMap(), Player::GetTeam(), WorldObject::IsWithinDistInMap(), m_towerBanners, SPELL_ZANGA_TOWER_TOKEN_ALLIANCE, SPELL_ZANGA_TOWER_TOKEN_HORDE, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerLeaveZone()
void OutdoorPvPZM::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 93 of file OutdoorPvPZM.cpp.
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and SPELL_TWIN_SPIRE_BLESSING.
IsConditionFulfilled()
bool OutdoorPvPZM::IsConditionFulfilled (Player const * source, uint32 conditionId, WorldObject const * conditionSource, uint32 conditionSourceType) override virtual
Reimplemented from OutdoorPvP.
Definition at line 410 of file OutdoorPvPZM.cpp.
References m_flagReady, m_playerCarryingFlag, OPVP_COND_ZM_ALLY_SCOUT_FLAG_READY, OPVP_COND_ZM_HORDE_SCOUT_FLAG_READY, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
ProcessCaptureEvent()
bool OutdoorPvPZM::ProcessCaptureEvent (GameObject * go, uint32 towerId, Team team, uint32 newWorldState, uint32 newMapState) private
Definition at line 201 of file OutdoorPvPZM.cpp.
References ALLIANCE, HORDE, LANG_OPVP_ZM_CAPTURE_BOTH_BEACONS_A, LANG_OPVP_ZM_CAPTURE_BOTH_BEACONS_H, m_beamTowerBlue, m_beamTowerRed, m_graveyardOwner, m_towerMapState, m_towerOwner, m_towersAlliance, m_towersHorde, m_towerWorldState, MAX_ZM_TOWERS, OutdoorPvP::SendUpdateWorldState(), SetBeaconArtKit(), SPELL_BEAM_BLUE, SPELL_BEAM_RED, sWorld, UpdateScoutState(), WORLD_STATE_ADD, WORLD_STATE_REMOVE, and ZONE_ID_ZANGARMARSH.
Referenced by HandleEvent().
SendRemoveWorldStates()
void OutdoorPvPZM::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 68 of file OutdoorPvPZM.cpp.
References m_graveyardWorldState, m_scoutWorldStateAlliance, m_scoutWorldStateHorde, m_towerMapState, m_towerWorldState, MAX_ZM_TOWERS, Player::SendUpdateWorldState(), and WORLD_STATE_REMOVE.
SetBeaconArtKit()
void OutdoorPvPZM::SetBeaconArtKit (const WorldObject * objRef, ObjectGuid creatureGuid, uint32 auraId) private
Definition at line 398 of file OutdoorPvPZM.cpp.
References Map::GetCreature(), WorldObject::GetMap(), and TRIGGERED_OLD_TRIGGERED.
Referenced by HandleGameObjectUse(), and ProcessCaptureEvent().
UpdateScoutState()
void OutdoorPvPZM::UpdateScoutState (Team team, bool spawned) private
Definition at line 278 of file OutdoorPvPZM.cpp.
References ALLIANCE, LANG_OPVP_ZM_SPAWN_FIELD_SCOUT_A, LANG_OPVP_ZM_SPAWN_FIELD_SCOUT_H, m_flagReady, m_scoutWorldStateAlliance, m_scoutWorldStateHorde, OutdoorPvP::SendUpdateWorldState(), sWorld, TEAM_INDEX_ALLIANCE, TEAM_INDEX_HORDE, WORLD_STATE_ADD, WORLD_STATE_REMOVE, WORLD_STATE_ZM_FLAG_NOT_READY_ALLIANCE, WORLD_STATE_ZM_FLAG_NOT_READY_HORDE, WORLD_STATE_ZM_FLAG_READY_ALLIANCE, WORLD_STATE_ZM_FLAG_READY_HORDE, and ZONE_ID_ZANGARMARSH.
Referenced by HandleGameObjectUse(), and ProcessCaptureEvent().
Field Documentation
m_beamGraveyardBlue
ObjectGuid OutdoorPvPZM::m_beamGraveyardBlue private
Definition at line 162 of file OutdoorPvPZM.h.
Referenced by HandleCreatureCreate(), and HandleGameObjectUse().
m_beamGraveyardRed
ObjectGuid OutdoorPvPZM::m_beamGraveyardRed private
Definition at line 163 of file OutdoorPvPZM.h.
Referenced by HandleCreatureCreate(), and HandleGameObjectUse().
m_beamTowerBlue
ObjectGuid OutdoorPvPZM::m_beamTowerBlue[MAX_ZM_TOWERS] private
Definition at line 160 of file OutdoorPvPZM.h.
Referenced by HandleCreatureCreate(), and ProcessCaptureEvent().
m_beamTowerRed
ObjectGuid OutdoorPvPZM::m_beamTowerRed[MAX_ZM_TOWERS] private
Definition at line 161 of file OutdoorPvPZM.h.
Referenced by HandleCreatureCreate(), and ProcessCaptureEvent().
m_flagReady
bool OutdoorPvPZM::m_flagReady[PVP_TEAM_COUNT] private
Definition at line 152 of file OutdoorPvPZM.h.
Referenced by IsConditionFulfilled(), OutdoorPvPZM(), and UpdateScoutState().
m_graveyardBannerAlliance
ObjectGuid OutdoorPvPZM::m_graveyardBannerAlliance private
Definition at line 156 of file OutdoorPvPZM.h.
Referenced by HandleGameObjectCreate(), and HandleGameObjectUse().
m_graveyardBannerHorde
ObjectGuid OutdoorPvPZM::m_graveyardBannerHorde private
Definition at line 157 of file OutdoorPvPZM.h.
Referenced by HandleGameObjectCreate(), and HandleGameObjectUse().
m_graveyardBannerNeutral
ObjectGuid OutdoorPvPZM::m_graveyardBannerNeutral private
Definition at line 158 of file OutdoorPvPZM.h.
Referenced by HandleGameObjectCreate(), and HandleGameObjectUse().
m_graveyardOwner
Team OutdoorPvPZM::m_graveyardOwner private
Definition at line 144 of file OutdoorPvPZM.h.
Referenced by HandleGameObjectUse(), HandlePlayerEnterZone(), and ProcessCaptureEvent().
m_graveyardWorldState
uint32 OutdoorPvPZM::m_graveyardWorldState private
Definition at line 146 of file OutdoorPvPZM.h.
Referenced by FillInitialWorldStates(), HandleGameObjectUse(), and SendRemoveWorldStates().
m_playerCarryingFlag
bool OutdoorPvPZM::m_playerCarryingFlag[PVP_TEAM_COUNT] private
Definition at line 153 of file OutdoorPvPZM.h.
Referenced by HandleConditionStateChange(), IsConditionFulfilled(), and OutdoorPvPZM().
m_scoutWorldStateAlliance
uint32 OutdoorPvPZM::m_scoutWorldStateAlliance private
Definition at line 147 of file OutdoorPvPZM.h.
Referenced by FillInitialWorldStates(), SendRemoveWorldStates(), and UpdateScoutState().
m_scoutWorldStateHorde
uint32 OutdoorPvPZM::m_scoutWorldStateHorde private
Definition at line 148 of file OutdoorPvPZM.h.
Referenced by FillInitialWorldStates(), SendRemoveWorldStates(), and UpdateScoutState().
m_towerBanners
ObjectGuid OutdoorPvPZM::m_towerBanners[MAX_ZM_TOWERS] private
Definition at line 155 of file OutdoorPvPZM.h.
Referenced by HandleGameObjectCreate(), and HandlePlayerKillInsideArea().
m_towerMapState
uint32 OutdoorPvPZM::m_towerMapState[MAX_ZM_TOWERS] private
Definition at line 141 of file OutdoorPvPZM.h.
Referenced by FillInitialWorldStates(), OutdoorPvPZM(), ProcessCaptureEvent(), and SendRemoveWorldStates().
m_towerOwner
Team OutdoorPvPZM::m_towerOwner[MAX_ZM_TOWERS] private
Definition at line 143 of file OutdoorPvPZM.h.
Referenced by HandleEvent(), OutdoorPvPZM(), and ProcessCaptureEvent().
m_towersAlliance
uint8 OutdoorPvPZM::m_towersAlliance private
Definition at line 149 of file OutdoorPvPZM.h.
Referenced by ProcessCaptureEvent().
m_towersHorde
uint8 OutdoorPvPZM::m_towersHorde private
Definition at line 150 of file OutdoorPvPZM.h.
Referenced by ProcessCaptureEvent().
m_towerWorldState
uint32 OutdoorPvPZM::m_towerWorldState[MAX_ZM_TOWERS] private
Definition at line 140 of file OutdoorPvPZM.h.
Referenced by FillInitialWorldStates(), OutdoorPvPZM(), ProcessCaptureEvent(), and SendRemoveWorldStates().
The documentation for this class was generated from the following files:
OutdoorPvPZM.h
OutdoorPvPZM.cpp