CMaNGOS_WoTLK: Messager< T > Class Template Reference
Messager< T > Class Template Reference
#include <Messager.h>
Public Member Functions
void AddMessage (const std::function< void(T *)> &message)
void Execute (T *object)
Private Attributes
std::vector< std::function< void(T *)> > m_messageVector
std::mutex m_messageMutex
Detailed Description
template<class T>
class Messager< T >
Definition at line 27 of file Messager.h.
Member Function Documentation
AddMessage()
template<class T > void Messager< T >::AddMessage (const std::function< void(T *)> & message) inline
Definition at line 30 of file Messager.h.
References Messager< T >::m_messageMutex, and Messager< T >::m_messageVector.
Referenced by OutdoorPvP::BuffTeam(), WorldState::HandleActiveZone(), WorldSocket::HandleAuthSession(), WorldSession::HandleCastSpellOpcode(), WorldSession::HandleMoveWorldportAckOpcode(), WorldState::OnDisable(), WorldSession::ProcessByteBufferException(), World::SendGMTextFlags(), WorldState::StartSunsReachPhase(), WorldState::SummonMouth(), WorldState::SummonPallid(), and Transport::TeleportTransport().
Execute()
template<class T > void Messager< T >::Execute (T * object) inline
Definition at line 35 of file Messager.h.
References function, Messager< T >::m_messageMutex, and Messager< T >::m_messageVector.
Referenced by LFGQueue::Update(), Map::Update(), WorldSession::Update(), and World::Update().
Field Documentation
m_messageMutex
template<class T > std::mutex Messager< T >::m_messageMutex private
Definition at line 49 of file Messager.h.
Referenced by Messager< T >::AddMessage(), and Messager< T >::Execute().
m_messageVector
template<class T > std::vector<std::function<void(T*)> > Messager< T >::m_messageVector private
Definition at line 48 of file Messager.h.
Referenced by Messager< T >::AddMessage(), and Messager< T >::Execute().
The documentation for this class was generated from the following file:
Messager.h