CMaNGOS_WoTLK: FindGOData Class Reference
FindGOData Class Reference
#include <ObjectMgr.h>
Public Member Functions
FindGOData (uint32 id, Player *player)
bool operator() (GameObjectDataPair const &dataPair)
GameObjectDataPair const * GetResult () const
Private Attributes
uint32 i_id
Player * i_player
GameObjectDataPair const * i_anyData
GameObjectDataPair const * i_mapData
float i_mapDist
GameObjectDataPair const * i_spawnedData
float i_spawnedDist
Detailed Description
Definition at line 221 of file ObjectMgr.h.
Constructor & Destructor Documentation
FindGOData()
FindGOData::FindGOData (uint32 id, Player * player) inline
Definition at line 224 of file ObjectMgr.h.
Member Function Documentation
GetResult()
GameObjectDataPair const * FindGOData::GetResult () const
Definition at line 10695 of file ObjectMgr.cpp.
References i_anyData, i_mapData, and i_spawnedData.
Referenced by ChatHandler::ExtractLocationFromLink(), and ChatHandler::HandleGoObjectCommand().
operator()()
bool FindGOData::operator() (GameObjectDataPair const & dataPair)
Definition at line 10656 of file ObjectMgr.cpp.
References WorldObject::GetDistance2d(), WorldObject::GetMap(), WorldObject::GetMapId(), Map::GetPersistentState(), i_anyData, i_id, i_mapData, i_mapDist, i_player, i_spawnedData, i_spawnedDist, MapPersistentState::IsSpawnedPoolObject(), and sPoolMgr.
Field Documentation
i_anyData
GameObjectDataPair const* FindGOData::i_anyData private
Definition at line 234 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_id
uint32 FindGOData::i_id private
Definition at line 231 of file ObjectMgr.h.
Referenced by operator()().
i_mapData
GameObjectDataPair const* FindGOData::i_mapData private
Definition at line 235 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_mapDist
float FindGOData::i_mapDist private
Definition at line 236 of file ObjectMgr.h.
Referenced by operator()().
i_player
Player* FindGOData::i_player private
Definition at line 232 of file ObjectMgr.h.
Referenced by operator()().
i_spawnedData
GameObjectDataPair const* FindGOData::i_spawnedData private
Definition at line 237 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_spawnedDist
float FindGOData::i_spawnedDist private
Definition at line 238 of file ObjectMgr.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
ObjectMgr.h
ObjectMgr.cpp