CMaNGOS_WoTLK: FindCreatureData Class Reference
FindCreatureData Class Reference
#include <ObjectMgr.h>
Public Member Functions
FindCreatureData (uint32 id, Player *player)
bool operator() (CreatureDataPair const &dataPair)
CreatureDataPair const * GetResult () const
Private Attributes
uint32 i_id
Player * i_player
CreatureDataPair const * i_anyData
CreatureDataPair const * i_mapData
float i_mapDist
CreatureDataPair const * i_spawnedData
float i_spawnedDist
Detailed Description
Definition at line 198 of file ObjectMgr.h.
Constructor & Destructor Documentation
FindCreatureData()
FindCreatureData::FindCreatureData (uint32 id, Player * player) inline
Definition at line 201 of file ObjectMgr.h.
Member Function Documentation
GetResult()
CreatureDataPair const * FindCreatureData::GetResult () const
Definition at line 10645 of file ObjectMgr.cpp.
References i_anyData, i_mapData, and i_spawnedData.
Referenced by ChatHandler::ExtractLocationFromLink(), and ChatHandler::HandleGoCreatureCommand().
operator()()
bool FindCreatureData::operator() (CreatureDataPair const & dataPair)
Definition at line 10606 of file ObjectMgr.cpp.
References WorldObject::GetDistance2d(), WorldObject::GetMap(), WorldObject::GetMapId(), Map::GetPersistentState(), i_anyData, i_id, i_mapData, i_mapDist, i_player, i_spawnedData, i_spawnedDist, MapPersistentState::IsSpawnedPoolObject(), and sPoolMgr.
Field Documentation
i_anyData
CreatureDataPair const* FindCreatureData::i_anyData private
Definition at line 211 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_id
uint32 FindCreatureData::i_id private
Definition at line 208 of file ObjectMgr.h.
Referenced by operator()().
i_mapData
CreatureDataPair const* FindCreatureData::i_mapData private
Definition at line 212 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_mapDist
float FindCreatureData::i_mapDist private
Definition at line 213 of file ObjectMgr.h.
Referenced by operator()().
i_player
Player* FindCreatureData::i_player private
Definition at line 209 of file ObjectMgr.h.
Referenced by operator()().
i_spawnedData
CreatureDataPair const* FindCreatureData::i_spawnedData private
Definition at line 214 of file ObjectMgr.h.
Referenced by GetResult(), and operator()().
i_spawnedDist
float FindCreatureData::i_spawnedDist private
Definition at line 215 of file ObjectMgr.h.
Referenced by operator()().
The documentation for this class was generated from the following files:
ObjectMgr.h
ObjectMgr.cpp