CMaNGOS_WoTLK: PointMovementGenerator Class Reference
PointMovementGenerator Class Reference
#include <PointMovementGenerator.h>
Public Member Functions
PointMovementGenerator (uint32 id, float x, float y, float z, float o, bool generatePath, uint32 forcedMovement, float speed=0.f, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
PointMovementGenerator (uint32 id, float x, float y, float z, bool generatePath, uint32 forcedMovement, float speed=0.f)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
void Reset (Unit &unit) override
bool Update (Unit &unit, const uint32 &) override
void UnitSpeedChanged () override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual void Move (Unit &unit)
virtual void MovementInform (Unit &unit)
Protected Attributes
float m_x
float m_y
float m_z
float m_o
float m_speed
bool m_generatePath
uint32 m_forcedMovement
Private Attributes
uint32 m_id
bool m_speedChanged
ObjectGuid m_guid
uint32 m_relayId
Detailed Description
Definition at line 24 of file PointMovementGenerator.h.
Constructor & Destructor Documentation
PointMovementGenerator() [1/2]
PointMovementGenerator::PointMovementGenerator (uint32 id, float x, float y, float z, float o, bool generatePath, uint32 forcedMovement, float speed = 0.f, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0) inline
Definition at line 27 of file PointMovementGenerator.h.
PointMovementGenerator() [2/2]
PointMovementGenerator::PointMovementGenerator (uint32 id, float x, float y, float z, bool generatePath, uint32 forcedMovement, float speed = 0.f) inline
Definition at line 30 of file PointMovementGenerator.h.
Member Function Documentation
Finalize()
void PointMovementGenerator::Finalize (Unit & unit) override virtual
Implements MovementGenerator.
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 49 of file PointMovementGenerator.cpp.
References Unit::clearUnitState(), Movement::MoveSpline::Finalized(), Unit::InterruptMoving(), Unit::IsClientControlled(), MovementInform(), Unit::movespline, Unit::StopMoving(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Referenced by RetreatMovementGenerator::Finalize(), and StayMovementGenerator::Finalize().
GetMovementGeneratorType()
MovementGeneratorType PointMovementGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 41 of file PointMovementGenerator.h.
References POINT_MOTION_TYPE.
Referenced by MovementInform().
Initialize()
void PointMovementGenerator::Initialize (Unit & unit) override virtual
Implements MovementGenerator.
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 28 of file PointMovementGenerator.cpp.
References Unit::addUnitState(), Movement::MoveSpline::Finalized(), Unit::hasUnitState(), Unit::InterruptMoving(), Unit::IsClientControlled(), m_speedChanged, Move(), Unit::movespline, Unit::StopMoving(), UNIT_STAT_NO_FREE_MOVE, UNIT_STAT_NOT_MOVE, UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Referenced by RetreatMovementGenerator::Initialize(), StayMovementGenerator::Initialize(), Reset(), and Update().
Interrupt()
void PointMovementGenerator::Interrupt (Unit & unit) override virtual
Implements MovementGenerator.
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 65 of file PointMovementGenerator.cpp.
References Unit::clearUnitState(), Unit::InterruptMoving(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Referenced by RetreatMovementGenerator::Interrupt(), and StayMovementGenerator::Interrupt().
Move()
void PointMovementGenerator::Move (Unit & unit) protected virtual
Reimplemented in PointTOLMovementGenerator.
Definition at line 91 of file PointMovementGenerator.cpp.
References FORCED_MOVEMENT_FLIGHT, FORCED_MOVEMENT_RUN, FORCED_MOVEMENT_WALK, Unit::hasUnitState(), Movement::MoveSplineInit::Launch(), m_forcedMovement, m_generatePath, m_o, m_speed, m_x, m_y, m_z, Movement::MoveSplineInit::MoveTo(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetFly(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), and UNIT_STAT_RUNNING.
Referenced by Initialize().
MovementInform()
void PointMovementGenerator::MovementInform (Unit & unit) protected virtual
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 109 of file PointMovementGenerator.cpp.
References Unit::AI(), Map::GetCreature(), WorldObject::GetMap(), GetMovementGeneratorType(), WorldObject::GetSpawnerGuid(), Object::GetTypeId(), Map::GetWorldObject(), ObjectGuid::IsAnyTypeCreature(), Creature::IsTemporarySummon(), m_guid, m_id, m_relayId, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), and TYPEID_UNIT.
Referenced by Finalize().
Reset()
void PointMovementGenerator::Reset (Unit & unit) override virtual
Implements MovementGenerator.
Reimplemented in RetreatMovementGenerator.
Definition at line 71 of file PointMovementGenerator.cpp.
References Unit::addUnitState(), Initialize(), and UNIT_STAT_ROAMING.
Referenced by RetreatMovementGenerator::Reset().
UnitSpeedChanged()
void PointMovementGenerator::UnitSpeedChanged () inline override virtual
Reimplemented from MovementGenerator.
Definition at line 39 of file PointMovementGenerator.h.
References m_speedChanged.
Update()
bool PointMovementGenerator::Update (Unit & unit, const uint32 &) override virtual
Implements MovementGenerator.
Reimplemented in StayMovementGenerator, and RetreatMovementGenerator.
Definition at line 77 of file PointMovementGenerator.cpp.
References Unit::clearUnitState(), Movement::MoveSpline::Finalized(), Unit::hasUnitState(), Initialize(), m_speedChanged, Unit::movespline, UNIT_STAT_CAN_NOT_MOVE, and UNIT_STAT_ROAMING_MOVE.
Referenced by RetreatMovementGenerator::Update(), and StayMovementGenerator::Update().
Field Documentation
m_forcedMovement
uint32 PointMovementGenerator::m_forcedMovement protected
Definition at line 50 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
m_generatePath
bool PointMovementGenerator::m_generatePath protected
Definition at line 49 of file PointMovementGenerator.h.
Referenced by Move().
m_guid
ObjectGuid PointMovementGenerator::m_guid private
Definition at line 55 of file PointMovementGenerator.h.
Referenced by MovementInform().
m_id
uint32 PointMovementGenerator::m_id private
Definition at line 53 of file PointMovementGenerator.h.
Referenced by MovementInform().
m_o
float PointMovementGenerator::m_o protected
Definition at line 48 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
m_relayId
uint32 PointMovementGenerator::m_relayId private
Definition at line 56 of file PointMovementGenerator.h.
Referenced by MovementInform().
m_speed
float PointMovementGenerator::m_speed protected
Definition at line 48 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
m_speedChanged
bool PointMovementGenerator::m_speedChanged private
Definition at line 54 of file PointMovementGenerator.h.
Referenced by Initialize(), UnitSpeedChanged(), and Update().
m_x
float PointMovementGenerator::m_x protected
Definition at line 48 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
m_y
float PointMovementGenerator::m_y protected
Definition at line 48 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
m_z
float PointMovementGenerator::m_z protected
Definition at line 48 of file PointMovementGenerator.h.
Referenced by Move(), and PointTOLMovementGenerator::Move().
The documentation for this class was generated from the following files:
PointMovementGenerator.h
PointMovementGenerator.cpp