CMaNGOS_WoTLK: Corpse Class Reference
Corpse Class Reference
#include <Corpse.h>
Public Member Functions
Corpse (CorpseType type=CORPSE_BONES)
~Corpse ()
void AddToWorld () override
void RemoveFromWorld () override
bool Create (uint32 guidlow)
bool Create (uint32 guidlow, Player *owner)
void SaveToDB ()
bool LoadFromDB (uint32 lowguid, Field *fields)
void DeleteBonesFromWorld ()
void DeleteFromDB () const
ObjectGuid const & GetOwnerGuid () const override
void SetOwnerGuid (ObjectGuid guid) override
uint8 getRace () const
uint32 getRaceMask () const
uint8 getGender () const
uint32 GetFaction () const
time_t const & GetGhostTime () const
void ResetGhostTime ()
CorpseType GetType () const
GridPair const & GetGrid () const
void SetGrid (GridPair const &grid)
bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const override
GridReference< Corpse > & GetGridRef ()
bool IsExpired (time_t t) const
Team GetTeam () const
Public Member Functions inherited from WorldObject
virtual ~WorldObject ()
virtual void Update (const uint32)
virtual void Heartbeat ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
virtual float GetCollisionHeight () const
virtual float GetCollisionWidth () const
virtual float GetObjectBoundingRadius () const
virtual float GetCombatReach () const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
virtual void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const
virtual void AdjustZForCollision (float, float, float &, float) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
virtual void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
virtual const char * GetNameForLocaleIdx (int32) const
virtual ObjectGuid const GetSpawnerGuid () const
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
virtual bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void CleanupsBeforeDelete ()
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
virtual ReputationRank GetReactionTo (Unit const *unit) const
[Serverside] Get default WorldObject (hierarchy) reaction to a unit
virtual ReputationRank GetReactionTo (Corpse const *corpse) const
[Serverside] Get default WorldObject (hierarchy) reaction to a corpse
virtual bool IsEnemy (Unit const *unit) const
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as an enemy
virtual bool IsFriend (Unit const *unit) const
[Serverside] Reaction preset: WorldObject (hierarchy) sees a unit as a friend
bool IsControlledByPlayer () const
virtual void SaveRespawnTime ()
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
virtual void UpdateVisibilityAndView ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
virtual void OnEventHappened (uint16, bool, bool)
void SetNotifyOnEventState (bool state)
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
virtual void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration)
void PrintCooldownList (ChatHandler &chat) const
virtual void InspectingLoot ()
virtual bool CanAttackSpell (Unit const *, SpellEntry const *=nullptr, bool=false) const
virtual bool CanAssistSpell (Unit const *, SpellEntry const *=nullptr) const
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
virtual HighGuid GetParentHigh () const
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
virtual uint32 GetLevel () const
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
virtual bool HasQuest (uint32) const
virtual bool HasInvolvedQuest (uint32) const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Data Fields
Player * lootRecipient
bool lootForBody
Data Fields inherited from WorldObject
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Private Attributes
GridReference< Corpse > m_gridRef
CorpseType m_type
time_t m_time
GridPair m_grid
Additional Inherited Members
Static Public Member Functions inherited from WorldObject
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes inherited from WorldObject
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Detailed Description
Definition at line 49 of file Corpse.h.
Constructor & Destructor Documentation
Corpse()
Corpse::Corpse (CorpseType type = CORPSE_BONES) explicit
Definition at line 27 of file Corpse.cpp.
References CORPSE_END, Object::m_objectType, Object::m_objectTypeId, m_time, m_type, Object::m_updateFlag, Object::m_valuesCount, TYPEID_CORPSE, TYPEMASK_CORPSE, UPDATEFLAG_HAS_POSITION, UPDATEFLAG_HIGHGUID, and UPDATEFLAG_POSITION.
~Corpse()
Corpse::~Corpse ()
Definition at line 43 of file Corpse.cpp.
Member Function Documentation
AddToWorld()
void Corpse::AddToWorld () override virtual
Register the corpse for guid lookup
Reimplemented from WorldObject.
Definition at line 47 of file Corpse.cpp.
References WorldObject::AddToWorld(), Object::IsInWorld(), and sObjectAccessor.
Referenced by LoadHelper().
Create() [1/2]
bool Corpse::Create (uint32 guidlow)
Definition at line 65 of file Corpse.cpp.
References Object::_Create(), and HIGHGUID_CORPSE.
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), and Player::CreateCorpse().
Create() [2/2]
bool Corpse::Create (uint32 guidlow, Player * owner)
Definition at line 71 of file Corpse.cpp.
References WorldObject::_Create(), MaNGOS::ComputeGridPair(), DEFAULT_OBJECT_SCALE, WorldObject::GetMap(), WorldObject::GetName(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), HIGHGUID_CORPSE, WorldObject::IsPositionValid(), m_grid, MANGOS_ASSERT, WorldObject::Relocate(), WorldObject::SetMap(), Object::SetObjectScale(), SetOwnerGuid(), and sLog.
DeleteBonesFromWorld()
void Corpse::DeleteBonesFromWorld ()
Definition at line 123 of file Corpse.cpp.
References WorldObject::AddObjectToRemoveList(), CORPSE_BONES, Map::GetCorpse(), Object::GetGUIDLow(), WorldObject::GetMap(), Object::GetObjectGuid(), GetType(), MANGOS_ASSERT, and sLog.
DeleteFromDB()
void Corpse::DeleteFromDB () const
Definition at line 137 of file Corpse.cpp.
References CharacterDatabase, CORPSE_BONES, Database::CreateStatement(), GetOwnerGuid(), GetType(), MANGOS_ASSERT, and SqlStatement::PExecute().
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), and SaveToDB().
GetFaction()
uint32 Corpse::GetFaction () const virtual
Reimplemented from WorldObject.
Definition at line 253 of file Corpse.cpp.
References getRace(), and sChrRacesStore.
Referenced by Unit::GetReactionTo().
getGender()
uint8 Corpse::getGender () const inline
Definition at line 72 of file Corpse.h.
References CORPSE_FIELD_BYTES_1, and Object::GetByteValue().
GetGhostTime()
time_t const& Corpse::GetGhostTime () const inline
Definition at line 77 of file Corpse.h.
References m_time.
Referenced by WorldSession::HandleReclaimCorpseOpcode(), Player::SendCorpseReclaimDelay(), and PlayerbotAI::UpdateAI().
GetGrid()
GridPair const& Corpse::GetGrid () const inline
Definition at line 81 of file Corpse.h.
References m_grid.
Referenced by ObjectAccessor::ConvertCorpseForPlayer().
GetGridRef()
GridReference<Corpse>& Corpse::GetGridRef () inline
Definition at line 89 of file Corpse.h.
References m_gridRef.
GetOwnerGuid()
ObjectGuid const& Corpse::GetOwnerGuid () const inline override virtual
Reimplemented from WorldObject.
Definition at line 67 of file Corpse.h.
References CORPSE_FIELD_OWNER, and Object::GetGuidValue().
Referenced by ObjectAccessor::AddCorpse(), Object::BuildValuesUpdate(), Spell::CheckTarget(), DeleteFromDB(), Spell::EffectSkinPlayerCorpse(), Player::GetReactionTo(), LoadFromDB(), Loot::Loot(), MaNGOS::CannibalizeObjectCheck::operator()(), MaNGOS::TauntFlagObjectCheck::operator()(), Player::QueueOrAddResurrectRequest(), ObjectAccessor::RemoveCorpse(), and SaveToDB().
getRace()
uint8 Corpse::getRace () const inline
Definition at line 70 of file Corpse.h.
References CORPSE_FIELD_BYTES_1, and Object::GetByteValue().
Referenced by Object::BuildValuesUpdate(), GetFaction(), getRaceMask(), and GetTeam().
getRaceMask()
uint32 Corpse::getRaceMask () const inline
Definition at line 71 of file Corpse.h.
References getRace().
GetTeam()
Team Corpse::GetTeam () const
Definition at line 275 of file Corpse.cpp.
References getRace(), and Player::TeamForRace().
GetType()
CorpseType Corpse::GetType () const inline
Definition at line 79 of file Corpse.h.
References m_type.
Referenced by ObjectAccessor::AddCorpse(), Map::AddToGrid(), DeleteBonesFromWorld(), DeleteFromDB(), WorldSession::HandleReclaimCorpseOpcode(), Loot::Loot(), MaNGOS::CannibalizeObjectCheck::operator()(), MaNGOS::TauntFlagObjectCheck::operator()(), ObjectAccessor::RemoveCorpse(), Map::RemoveFromGrid(), SaveToDB(), Player::SendCorpseReclaimDelay(), and PlayerbotAI::UpdateAI().
IsExpired()
bool Corpse::IsExpired (time_t t) const
Definition at line 268 of file Corpse.cpp.
References CORPSE_BONES, DAY, m_time, m_type, and MINUTE.
isVisibleForInState()
bool Corpse::isVisibleForInState (Player const * u, WorldObject const * viewPoint, bool inVisibleList) const override virtual
Implements WorldObject.
Definition at line 263 of file Corpse.cpp.
References WorldObject::GetMap(), Object::IsInWorld(), and WorldObject::IsWithinDistInMap().
LoadFromDB()
bool Corpse::LoadFromDB (uint32 lowguid, Field * fields)
Definition at line 149 of file Corpse.cpp.
References Object::_Create(), MaNGOS::ComputeGridPair(), CORPSE_FIELD_BYTES_1, CORPSE_FIELD_BYTES_2, CORPSE_FIELD_DISPLAY_ID, CORPSE_FIELD_FLAGS, CORPSE_FIELD_GUILD, CORPSE_FIELD_ITEM, CORPSE_FLAG_HIDE_CLOAK, CORPSE_FLAG_HIDE_HELM, CORPSE_FLAG_UNK2, DEFAULT_OBJECT_SCALE, PlayerInfo::displayId_f, PlayerInfo::displayId_m, ItemPrototype::DisplayInfoID, EQUIPMENT_SLOT_END, GENDER_FEMALE, Field::GetFloat(), Object::GetGUIDLow(), Object::GetGuidStr(), ObjectMgr::GetItemPrototype(), GetOwnerGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Field::GetUInt32(), GetUInt32ValueFromArray(), Field::GetUInt8(), HIGHGUID_CORPSE, HIGHGUID_PLAYER, ItemPrototype::InventoryType, WorldObject::IsPositionValid(), m_grid, m_time, m_type, MAX_CORPSE_TYPE, OBJECT_FIELD_GUID, PLAYER_FLAGS_HIDE_CLOAK, PLAYER_FLAGS_HIDE_HELM, WorldObject::Relocate(), Object::SetGuidValue(), WorldObject::SetLocationInstanceId(), WorldObject::SetLocationMapId(), Object::SetObjectScale(), SetOwnerGuid(), WorldObject::SetPhaseMask(), Object::SetUInt32Value(), sLog, sObjectMgr, and StrSplit().
Referenced by ObjectMgr::LoadCorpses().
RemoveFromWorld()
void Corpse::RemoveFromWorld () override virtual
Remove the corpse from the accessor
Reimplemented from WorldObject.
Definition at line 56 of file Corpse.cpp.
References Object::IsInWorld(), Object::RemoveFromWorld(), and sObjectAccessor.
Referenced by ObjectAccessor::RemoveCorpse().
ResetGhostTime()
void Corpse::ResetGhostTime () inline
Definition at line 78 of file Corpse.h.
References m_time.
Referenced by Player::BuildPlayerRepop().
SaveToDB()
void Corpse::SaveToDB ()
Definition at line 97 of file Corpse.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CORPSE_BONES, DeleteFromDB(), Database::Execute(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), WorldObject::GetInstanceId(), WorldObject::GetMapId(), WorldObject::GetOrientation(), GetOwnerGuid(), WorldObject::GetPhaseMask(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GetType(), m_time, and MANGOS_ASSERT.
Referenced by Player::CreateCorpse().
SetGrid()
void Corpse::SetGrid (GridPair const & grid) inline
Definition at line 82 of file Corpse.h.
References m_grid.
Referenced by ObjectAccessor::ConvertCorpseForPlayer().
SetOwnerGuid()
void Corpse::SetOwnerGuid (ObjectGuid guid) inline override virtual
Reimplemented from WorldObject.
Definition at line 68 of file Corpse.h.
References CORPSE_FIELD_OWNER, and Object::SetGuidValue().
Referenced by ObjectAccessor::ConvertCorpseForPlayer(), Create(), and LoadFromDB().
Field Documentation
lootForBody
bool Corpse::lootForBody
Definition at line 87 of file Corpse.h.
Referenced by Loot::Loot().
lootRecipient
Player* Corpse::lootRecipient
Definition at line 86 of file Corpse.h.
Referenced by Spell::EffectSkinPlayerCorpse(), and Player::RemovedInsignia().
m_grid
GridPair Corpse::m_grid private
Definition at line 98 of file Corpse.h.
Referenced by Create(), GetGrid(), LoadFromDB(), and SetGrid().
m_gridRef
GridReference<Corpse> Corpse::m_gridRef private
Definition at line 94 of file Corpse.h.
Referenced by GetGridRef().
m_time
time_t Corpse::m_time private
Definition at line 97 of file Corpse.h.
Referenced by Corpse(), GetGhostTime(), IsExpired(), LoadFromDB(), ResetGhostTime(), and SaveToDB().
m_type
CorpseType Corpse::m_type private
Definition at line 96 of file Corpse.h.
Referenced by Corpse(), GetType(), IsExpired(), and LoadFromDB().
The documentation for this class was generated from the following files:
Corpse.h
Corpse.cpp