CMaNGOS_WoTLK: SocialMgr Class Reference
SocialMgr Class Reference
#include <SocialMgr.h>
Public Member Functions
SocialMgr ()
~SocialMgr ()
void RemovePlayerSocial (uint32 guid)
void GetFriendInfo (Player *player, uint32 friend_lowguid, FriendInfo &friendInfo) const
void SendFriendStatus (Player *player, FriendsResult result, ObjectGuid friend_guid, bool broadcast)
void BroadcastToFriendListers (Player *player, WorldPacket const &packet)
PlayerSocial * LoadFromDB (QueryResult *result, ObjectGuid guid)
Static Public Member Functions
static void MakeFriendStatusPacket (FriendsResult result, uint32 guid, WorldPacket &data)
Private Attributes
SocialMap m_socialMap
Detailed Description
Definition at line 134 of file SocialMgr.h.
Constructor & Destructor Documentation
SocialMgr()
SocialMgr::SocialMgr ()
Definition at line 171 of file SocialMgr.cpp.
~SocialMgr()
SocialMgr::~SocialMgr ()
Definition at line 175 of file SocialMgr.cpp.
Member Function Documentation
BroadcastToFriendListers()
void SocialMgr::BroadcastToFriendListers (Player * player, WorldPacket const & packet)
Definition at line 265 of file SocialMgr.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST, ObjectAccessor::FindPlayer(), Object::GetGUIDLow(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeam(), HIGHGUID_PLAYER, Object::IsInWorld(), Player::IsVisibleGloballyFor(), m_socialMap, SEC_PLAYER, WorldSession::SendPacket(), SOCIAL_FLAG_FRIEND, and sWorld.
Referenced by SendFriendStatus().
GetFriendInfo()
void SocialMgr::GetFriendInfo (Player * player, uint32 friend_lowguid, FriendInfo & friendInfo) const
Definition at line 179 of file SocialMgr.cpp.
References FriendInfo::Area, FriendInfo::Class, CONFIG_BOOL_ALLOW_TWO_SIDE_WHO_LIST, CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST, ObjectAccessor::FindPlayer(), FRIEND_STATUS_AFK, FRIEND_STATUS_DND, FRIEND_STATUS_OFFLINE, FRIEND_STATUS_ONLINE, Unit::getClass(), Unit::GetLevel(), WorldObject::GetName(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetSocial(), Player::GetTeam(), WorldObject::GetZoneId(), HIGHGUID_PLAYER, Player::isAFK(), Player::isDND(), Player::IsVisibleGloballyFor(), FriendInfo::Level, PlayerSocial::m_playerSocialMap, FriendInfo::Note, SEC_PLAYER, FriendInfo::Status, and sWorld.
Referenced by SendFriendStatus().
LoadFromDB()
PlayerSocial * SocialMgr::LoadFromDB (QueryResult * result, ObjectGuid guid)
Definition at line 296 of file SocialMgr.cpp.
References QueryResult::Fetch(), ObjectGuid::GetCounter(), Field::GetCppString(), Field::GetUInt32(), PlayerSocial::m_playerSocialMap, m_socialMap, QueryResult::NextRow(), PlayerSocial::SetPlayerGuid(), SOCIAL_FLAG_FRIEND, SOCIAL_FLAG_IGNORED, SOCIALMGR_FRIEND_LIMIT, and SOCIALMGR_IGNORE_LIMIT.
MakeFriendStatusPacket()
void SocialMgr::MakeFriendStatusPacket (FriendsResult result, uint32 guid, WorldPacket & data) static
Definition at line 220 of file SocialMgr.cpp.
References HIGHGUID_PLAYER, WorldPacket::Initialize(), and SMSG_FRIEND_STATUS.
Referenced by SendFriendStatus().
RemovePlayerSocial()
void SocialMgr::RemovePlayerSocial (uint32 guid) inline
Definition at line 140 of file SocialMgr.h.
References m_socialMap.
SendFriendStatus()
void SocialMgr::SendFriendStatus (Player * player, FriendsResult result, ObjectGuid friend_guid, bool broadcast)
Definition at line 227 of file SocialMgr.cpp.
References FriendInfo::Area, BroadcastToFriendListers(), FriendInfo::Class, FRIEND_ADDED_OFFLINE, FRIEND_ADDED_ONLINE, FRIEND_ONLINE, ObjectGuid::GetCounter(), GetFriendInfo(), Player::GetSession(), FriendInfo::Level, MakeFriendStatusPacket(), FriendInfo::Note, WorldSession::SendPacket(), and FriendInfo::Status.
Field Documentation
m_socialMap
SocialMap SocialMgr::m_socialMap private
Definition at line 150 of file SocialMgr.h.
Referenced by BroadcastToFriendListers(), LoadFromDB(), and RemovePlayerSocial().
The documentation for this class was generated from the following files:
SocialMgr.h
SocialMgr.cpp