CMaNGOS_WoTLK: WheatyExceptionReport Class Reference
WheatyExceptionReport Class Reference
#include <WheatyExceptionReport.h>
Public Member Functions
WheatyExceptionReport ()
~WheatyExceptionReport ()
Static Public Member Functions
static LONG WINAPI WheatyUnhandledExceptionFilter (PEXCEPTION_POINTERS pExceptionInfo)
static void __cdecl WheatyCrtHandler (wchar_t const *expression, wchar_t const *function, wchar_t const *file, unsigned int line, uintptr_t pReserved)
static void printTracesForAllThreads (bool)
Private Types
typedef NTSTATUS(NTAPI * pRtlGetVersion) (PRTL_OSVERSIONINFOW lpVersionInformation)
Static Private Member Functions
static void GenerateExceptionReport (PEXCEPTION_POINTERS pExceptionInfo)
static void PrintSystemInfo ()
static BOOL _GetWindowsVersion (TCHAR *szVersion, DWORD cntMax)
static BOOL _GetProcessorName (TCHAR *sProcessorName, DWORD maxcount)
static LPCTSTR GetExceptionString (DWORD dwCode)
static BOOL GetLogicalAddress (PVOID addr, PTSTR szModule, DWORD len, DWORD &section, DWORD_PTR &offset)
static void WriteStackDetails (PCONTEXT pContext, bool bWriteVariables, HANDLE pThreadHandle)
static BOOL CALLBACK EnumerateSymbolsCallback (PSYMBOL_INFO, ULONG, PVOID)
static bool FormatSymbolValue (PSYMBOL_INFO, STACKFRAME64 *)
static void DumpTypeIndex (DWORD64, DWORD, DWORD_PTR, bool &, char const *, char const *, bool, bool)
static void FormatOutputValue (char *pszCurrBuffer, BasicType basicType, DWORD64 length, PVOID pAddress, size_t bufferSize, size_t countOverride=0)
static BasicType GetBasicType (DWORD typeIndex, DWORD64 modBase)
static DWORD_PTR DereferenceUnsafePointer (DWORD_PTR address)
static int __cdecl Log (const TCHAR *format,...)
static bool StoreSymbol (DWORD type, DWORD_PTR offset)
static void ClearSymbols ()
static void PushSymbolDetail ()
static void PopSymbolDetail ()
static void PrintSymbolDetail ()
Static Private Attributes
static TCHAR m_szLogFileName [MAX_PATH]
static TCHAR m_szDumpFileName [MAX_PATH]
static LPTOP_LEVEL_EXCEPTION_FILTER m_previousFilter
static _invalid_parameter_handler m_previousCrtHandler
static FILE * m_hReportFile
static HANDLE m_hDumpFile
static HANDLE m_hProcess
static SymbolPairs symbols
static std::stack< SymbolDetail > symbolDetails
static bool alreadyCrashed
static std::mutex alreadyCrashedLock
static pRtlGetVersion RtlGetVersion
Detailed Description
Definition at line 135 of file WheatyExceptionReport.h.
Member Typedef Documentation
pRtlGetVersion
typedef NTSTATUS(NTAPI* WheatyExceptionReport::pRtlGetVersion) (PRTL_OSVERSIONINFOW lpVersionInformation) private
Definition at line 191 of file WheatyExceptionReport.h.
Constructor & Destructor Documentation
WheatyExceptionReport()
WheatyExceptionReport::WheatyExceptionReport ()
Definition at line 73 of file WheatyExceptionReport.cpp.
References alreadyCrashed, m_hProcess, m_previousCrtHandler, m_previousFilter, RtlGetVersion, WheatyCrtHandler(), and WheatyUnhandledExceptionFilter().
~WheatyExceptionReport()
WheatyExceptionReport::~WheatyExceptionReport ()
Definition at line 93 of file WheatyExceptionReport.cpp.
References ClearSymbols(), m_previousCrtHandler, and m_previousFilter.
Member Function Documentation
_GetProcessorName()
BOOL WheatyExceptionReport::_GetProcessorName (TCHAR * sProcessorName, DWORD maxcount) static private
Definition at line 197 of file WheatyExceptionReport.cpp.
Referenced by PrintSystemInfo().
_GetWindowsVersion()
BOOL WheatyExceptionReport::_GetWindowsVersion (TCHAR * szVersion, DWORD cntMax) static private
Definition at line 236 of file WheatyExceptionReport.cpp.
References RtlGetVersion, and ToTchar().
Referenced by PrintSystemInfo().
ClearSymbols()
void WheatyExceptionReport::ClearSymbols () static private
Definition at line 1499 of file WheatyExceptionReport.cpp.
References symbolDetails, and symbols.
Referenced by EnumerateSymbolsCallback(), and ~WheatyExceptionReport().
DereferenceUnsafePointer()
DWORD_PTR WheatyExceptionReport::DereferenceUnsafePointer (DWORD_PTR address) static private
Definition at line 1469 of file WheatyExceptionReport.cpp.
Referenced by DumpTypeIndex().
DumpTypeIndex()
void WheatyExceptionReport::DumpTypeIndex (DWORD64 modBase, DWORD dwTypeIndex, DWORD_PTR offset, bool & bHandled, char const * Name, char const * , bool newSymbol, bool logChildren) static private
Definition at line 1025 of file WheatyExceptionReport.cpp.
References btChar, btNoType, btStdString, btVoid, MaNGOS::Count(), DataIsGlobal, DataIsStaticLocal, DataIsStaticMember, DereferenceUnsafePointer(), FormatOutputValue(), GetBasicType(), m_hProcess, PopSymbolDetail(), PushSymbolDetail(), rgBaseType, StoreSymbol(), symbolDetails, WER_MAX_ARRAY_ELEMENTS_COUNT, WER_MAX_NESTING_LEVEL, and WER_SMALL_BUFFER_SIZE.
Referenced by FormatSymbolValue().
EnumerateSymbolsCallback()
BOOL CALLBACK WheatyExceptionReport::EnumerateSymbolsCallback (PSYMBOL_INFO pSymInfo, ULONG , PVOID UserContext) static private
Definition at line 930 of file WheatyExceptionReport.cpp.
References ClearSymbols(), FormatSymbolValue(), and Log().
Referenced by WriteStackDetails().
FormatOutputValue()
void WheatyExceptionReport::FormatOutputValue (char * pszCurrBuffer, BasicType basicType, DWORD64 length, PVOID pAddress, size_t bufferSize, size_t countOverride = 0) static private
Definition at line 1366 of file WheatyExceptionReport.cpp.
References btChar, btFloat, and btStdString.
Referenced by DumpTypeIndex(), and FormatSymbolValue().
FormatSymbolValue()
bool WheatyExceptionReport::FormatSymbolValue (PSYMBOL_INFO pSym, STACKFRAME64 * sf) static private
Definition at line 954 of file WheatyExceptionReport.cpp.
References DumpTypeIndex(), FormatOutputValue(), GetBasicType(), PopSymbolDetail(), PushSymbolDetail(), rgBaseType, and symbolDetails.
Referenced by EnumerateSymbolsCallback(), and GenerateExceptionReport().
GenerateExceptionReport()
void WheatyExceptionReport::GenerateExceptionReport (PEXCEPTION_POINTERS pExceptionInfo) static private
Definition at line 498 of file WheatyExceptionReport.cpp.
References ErrorMessage(), FormatSymbolValue(), GetExceptionString(), GetLogicalAddress(), Log(), m_hProcess, PrintSystemInfo(), printTracesForAllThreads(), and WriteStackDetails().
Referenced by WheatyUnhandledExceptionFilter().
GetBasicType()
BasicType WheatyExceptionReport::GetBasicType (DWORD typeIndex, DWORD64 modBase) static private
Definition at line 1445 of file WheatyExceptionReport.cpp.
References btNoType, and m_hProcess.
Referenced by DumpTypeIndex(), and FormatSymbolValue().
GetExceptionString()
LPCTSTR WheatyExceptionReport::GetExceptionString (DWORD dwCode) static private
Definition at line 693 of file WheatyExceptionReport.cpp.
References EXCEPTION.
Referenced by GenerateExceptionReport().
GetLogicalAddress()
BOOL WheatyExceptionReport::GetLogicalAddress (PVOID addr, PTSTR szModule, DWORD len, DWORD & section, DWORD_PTR & offset) static private
Definition at line 743 of file WheatyExceptionReport.cpp.
Referenced by GenerateExceptionReport(), and WriteStackDetails().
Log()
int __cdecl WheatyExceptionReport::Log (const TCHAR * format, ...) static private
Definition at line 1485 of file WheatyExceptionReport.cpp.
References m_hReportFile.
Referenced by EnumerateSymbolsCallback(), GenerateExceptionReport(), PrintSymbolDetail(), PrintSystemInfo(), and WriteStackDetails().
PopSymbolDetail()
void WheatyExceptionReport::PopSymbolDetail () static private
Definition at line 1513 of file WheatyExceptionReport.cpp.
References PrintSymbolDetail(), and symbolDetails.
Referenced by DumpTypeIndex(), and FormatSymbolValue().
PrintSymbolDetail()
void WheatyExceptionReport::PrintSymbolDetail () static private
Definition at line 1519 of file WheatyExceptionReport.cpp.
References Log(), and symbolDetails.
Referenced by PopSymbolDetail(), and PushSymbolDetail().
PrintSystemInfo()
void WheatyExceptionReport::PrintSystemInfo () static private
Definition at line 422 of file WheatyExceptionReport.cpp.
References _GetProcessorName(), _GetWindowsVersion(), and Log().
Referenced by GenerateExceptionReport().
printTracesForAllThreads()
void WheatyExceptionReport::printTracesForAllThreads (bool bWriteVariables) static
Definition at line 447 of file WheatyExceptionReport.cpp.
References m_hProcess, and WriteStackDetails().
Referenced by GenerateExceptionReport().
PushSymbolDetail()
void WheatyExceptionReport::PushSymbolDetail () static private
Definition at line 1506 of file WheatyExceptionReport.cpp.
References PrintSymbolDetail(), and symbolDetails.
Referenced by DumpTypeIndex(), and FormatSymbolValue().
StoreSymbol()
bool WheatyExceptionReport::StoreSymbol (DWORD type, DWORD_PTR offset) static private
Definition at line 1494 of file WheatyExceptionReport.cpp.
References symbols.
Referenced by DumpTypeIndex().
WheatyCrtHandler()
void __cdecl WheatyExceptionReport::WheatyCrtHandler (wchar_t const * expression, wchar_t const * function, wchar_t const * file, unsigned int line, uintptr_t pReserved) static
Definition at line 192 of file WheatyExceptionReport.cpp.
Referenced by WheatyExceptionReport().
WheatyUnhandledExceptionFilter()
LONG WINAPI WheatyExceptionReport::WheatyUnhandledExceptionFilter (PEXCEPTION_POINTERS pExceptionInfo) static
Definition at line 105 of file WheatyExceptionReport.cpp.
References alreadyCrashed, alreadyCrashedLock, CrashFolder, GenerateExceptionReport(), m_hDumpFile, m_hReportFile, m_previousFilter, m_szDumpFileName, and m_szLogFileName.
Referenced by WheatyExceptionReport().
WriteStackDetails()
void WheatyExceptionReport::WriteStackDetails (PCONTEXT pContext, bool bWriteVariables, HANDLE pThreadHandle) static private
Definition at line 808 of file WheatyExceptionReport.cpp.
References EnumerateSymbolsCallback(), GetLogicalAddress(), Log(), and m_hProcess.
Referenced by GenerateExceptionReport(), and printTracesForAllThreads().
Field Documentation
alreadyCrashed
bool WheatyExceptionReport::alreadyCrashed static private
Definition at line 189 of file WheatyExceptionReport.h.
Referenced by WheatyExceptionReport(), and WheatyUnhandledExceptionFilter().
alreadyCrashedLock
std::mutex WheatyExceptionReport::alreadyCrashedLock static private
Definition at line 190 of file WheatyExceptionReport.h.
Referenced by WheatyUnhandledExceptionFilter().
m_hDumpFile
HANDLE WheatyExceptionReport::m_hDumpFile static private
Definition at line 185 of file WheatyExceptionReport.h.
Referenced by WheatyUnhandledExceptionFilter().
m_hProcess
HANDLE WheatyExceptionReport::m_hProcess static private
Definition at line 186 of file WheatyExceptionReport.h.
Referenced by DumpTypeIndex(), GenerateExceptionReport(), GetBasicType(), printTracesForAllThreads(), WheatyExceptionReport(), and WriteStackDetails().
m_hReportFile
FILE * WheatyExceptionReport::m_hReportFile static private
Definition at line 184 of file WheatyExceptionReport.h.
Referenced by Log(), and WheatyUnhandledExceptionFilter().
m_previousCrtHandler
_invalid_parameter_handler WheatyExceptionReport::m_previousCrtHandler static private
Definition at line 183 of file WheatyExceptionReport.h.
Referenced by WheatyExceptionReport(), and ~WheatyExceptionReport().
m_previousFilter
LPTOP_LEVEL_EXCEPTION_FILTER WheatyExceptionReport::m_previousFilter static private
Definition at line 182 of file WheatyExceptionReport.h.
Referenced by WheatyExceptionReport(), WheatyUnhandledExceptionFilter(), and ~WheatyExceptionReport().
m_szDumpFileName
TCHAR WheatyExceptionReport::m_szDumpFileName static private
Definition at line 181 of file WheatyExceptionReport.h.
Referenced by WheatyUnhandledExceptionFilter().
m_szLogFileName
TCHAR WheatyExceptionReport::m_szLogFileName static private
Definition at line 180 of file WheatyExceptionReport.h.
Referenced by WheatyUnhandledExceptionFilter().
RtlGetVersion
WheatyExceptionReport::pRtlGetVersion WheatyExceptionReport::RtlGetVersion static private
Definition at line 192 of file WheatyExceptionReport.h.
Referenced by _GetWindowsVersion(), and WheatyExceptionReport().
symbolDetails
std::stack< SymbolDetail > WheatyExceptionReport::symbolDetails static private
Definition at line 188 of file WheatyExceptionReport.h.
Referenced by ClearSymbols(), DumpTypeIndex(), FormatSymbolValue(), PopSymbolDetail(), PrintSymbolDetail(), and PushSymbolDetail().
symbols
SymbolPairs WheatyExceptionReport::symbols static private
Definition at line 187 of file WheatyExceptionReport.h.
Referenced by ClearSymbols(), and StoreSymbol().
The documentation for this class was generated from the following files:
WheatyExceptionReport.h
WheatyExceptionReport.cpp