CMaNGOS_WoTLK: DynamicMapTree Class Reference
DynamicMapTree Class Reference
#include <DynamicTree.h>
Public Member Functions
DynamicMapTree ()
~DynamicMapTree ()
bool isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask, bool ignoreM2Model) const
bool getIntersectionTime (uint32 phasemask, const G3D::Ray &ray, const G3D::Vector3 &endPos, float &pMaxDist) const
If intersection is found within pMaxDist, sets pMaxDist to intersection distance and returns true.
bool getObjectHitPos (uint32 phasemask, const G3D::Vector3 &pPos1, const G3D::Vector3 &pPos2, G3D::Vector3 &pResultHitPos, float pModifyDist) const
bool getObjectHitPos (uint32 phasemask, float x1, float y1, float z1, float x2, float y2, float z2, float &rx, float &ry, float &rz, float pModifyDist) const
float getHeight (float x, float y, float z, float maxSearchDist, uint32 phasemask) const
void insert (const GameObjectModel &)
void remove (const GameObjectModel &)
bool contains (const GameObjectModel &) const
int size () const
void balance ()
void update (uint32 t_diff)
Private Attributes
struct DynTreeImpl & impl
Detailed Description
Definition at line 31 of file DynamicTree.h.
Constructor & Destructor Documentation
DynamicMapTree()
DynamicMapTree::DynamicMapTree ()
Definition at line 102 of file DynamicTree.cpp.
~DynamicMapTree()
DynamicMapTree::~DynamicMapTree ()
Definition at line 106 of file DynamicTree.cpp.
References impl.
Member Function Documentation
balance()
void DynamicMapTree::balance ()
Definition at line 126 of file DynamicTree.cpp.
References DynTreeImpl::balance(), and impl.
contains()
bool DynamicMapTree::contains (const GameObjectModel & mdl) const
Definition at line 121 of file DynamicTree.cpp.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::contains(), and impl.
Referenced by Map::ContainsGameObjectModel().
getHeight()
float DynamicMapTree::getHeight (float x, float y, float z, float maxSearchDist, uint32 phasemask) const
Definition at line 264 of file DynamicTree.cpp.
References DynamicTreeIntersectionCallback::didHit(), impl, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay().
Referenced by Map::GetHeight(), and Map::GetHeightInRange().
getIntersectionTime()
bool DynamicMapTree::getIntersectionTime (uint32 phasemask, const G3D::Ray & ray, const G3D::Vector3 & endPos, float & pMaxDist) const
If intersection is found within pMaxDist, sets pMaxDist to intersection distance and returns true.
Else, pMaxDist is not modified and returns false;
Definition at line 182 of file DynamicTree.cpp.
References DynamicTreeIntersectionCallback::didHit(), impl, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay().
getObjectHitPos() [1/2]
bool DynamicMapTree::getObjectHitPos (uint32 phasemask, const G3D::Vector3 & pPos1, const G3D::Vector3 & pPos2, G3D::Vector3 & pResultHitPos, float pModifyDist) const
Referenced by Map::GetHitPosition(), and getObjectHitPos().
getObjectHitPos() [2/2]
bool DynamicMapTree::getObjectHitPos (uint32 phasemask, float x1, float y1, float z1, float x2, float y2, float z2, float & rx, float & ry, float & rz, float pModifyDist) const
Definition at line 193 of file DynamicTree.cpp.
References getObjectHitPos().
insert()
void DynamicMapTree::insert (const GameObjectModel & mdl)
Definition at line 111 of file DynamicTree.cpp.
References impl, and DynTreeImpl::insert().
Referenced by Map::InsertGameObjectModel().
isInLineOfSight()
bool DynamicMapTree::isInLineOfSight (float x1, float y1, float z1, float x2, float y2, float z2, uint32 phasemask, bool ignoreM2Model) const
Definition at line 248 of file DynamicTree.cpp.
References DynamicTreeIntersectionCallback::did_hit, impl, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay().
Referenced by Map::IsInLineOfSight().
remove()
void DynamicMapTree::remove (const GameObjectModel & mdl)
Definition at line 116 of file DynamicTree.cpp.
References impl, and DynTreeImpl::remove().
Referenced by Map::RemoveGameObjectModel().
size()
int DynamicMapTree::size () const
Definition at line 131 of file DynamicTree.cpp.
References impl, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::size().
update()
void DynamicMapTree::update (uint32 t_diff)
Definition at line 136 of file DynamicTree.cpp.
References impl, and DynTreeImpl::update().
Referenced by Map::Update().
Field Documentation
impl
struct DynTreeImpl& DynamicMapTree::impl private
Definition at line 51 of file DynamicTree.h.
Referenced by balance(), contains(), getHeight(), getIntersectionTime(), insert(), isInLineOfSight(), remove(), size(), update(), and ~DynamicMapTree().
The documentation for this class was generated from the following files:
DynamicTree.h
DynamicTree.cpp