CMaNGOS_WoTLK: MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck Class Reference
MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AllCreatureEntriesWithLiveStateInObjectRangeCheck (WorldObject const &obj, std::set< uint32 > &entries, bool alive, float range, bool guids=false, bool excludeSelf=false, bool is3D=true)
WorldObject const & GetFocusObject () const
bool operator() (Creature *u)
bool FoundOutOfRange () const
Private Member Functions
AllCreatureEntriesWithLiveStateInObjectRangeCheck (AllCreatureEntriesWithLiveStateInObjectRangeCheck const &)
Private Attributes
WorldObject const & i_obj
std::set< uint32 > & i_entries
float i_range
bool i_guids
bool i_alive
bool i_excludeSelf
bool i_is3D
bool i_foundOutOfRange
Detailed Description
Definition at line 1451 of file GridNotifiers.h.
Constructor & Destructor Documentation
AllCreatureEntriesWithLiveStateInObjectRangeCheck() [1/2]
MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::AllCreatureEntriesWithLiveStateInObjectRangeCheck (WorldObject const & obj, std::set< uint32 > & entries, bool alive, float range, bool guids = false, bool excludeSelf = false, bool is3D = true) inline
Definition at line 1454 of file GridNotifiers.h.
AllCreatureEntriesWithLiveStateInObjectRangeCheck() [2/2]
MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::AllCreatureEntriesWithLiveStateInObjectRangeCheck (AllCreatureEntriesWithLiveStateInObjectRangeCheck const &) private
Member Function Documentation
FoundOutOfRange()
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::FoundOutOfRange () const inline
Definition at line 1467 of file GridNotifiers.h.
References i_foundOutOfRange.
Referenced by Spell::CheckScriptTargeting().
GetFocusObject()
WorldObject const& MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::GetFocusObject () const inline
Definition at line 1456 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::operator() (Creature * u) inline
Definition at line 1457 of file GridNotifiers.h.
References Object::GetDbGuid(), Object::GetEntry(), i_alive, i_entries, i_excludeSelf, i_foundOutOfRange, i_guids, i_is3D, i_obj, i_range, Unit::IsAlive(), Creature::IsCorpse(), and WorldObject::IsWithinCombatDistInMap().
Field Documentation
i_alive
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_alive private
Definition at line 1473 of file GridNotifiers.h.
Referenced by operator()().
i_entries
std::set<uint32>& MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_entries private
Definition at line 1470 of file GridNotifiers.h.
Referenced by operator()().
i_excludeSelf
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_excludeSelf private
Definition at line 1474 of file GridNotifiers.h.
Referenced by operator()().
i_foundOutOfRange
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_foundOutOfRange private
Definition at line 1476 of file GridNotifiers.h.
Referenced by FoundOutOfRange(), and operator()().
i_guids
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_guids private
Definition at line 1472 of file GridNotifiers.h.
Referenced by operator()().
i_is3D
bool MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_is3D private
Definition at line 1475 of file GridNotifiers.h.
Referenced by operator()().
i_obj
WorldObject const& MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_obj private
Definition at line 1469 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AllCreatureEntriesWithLiveStateInObjectRangeCheck::i_range private
Definition at line 1471 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h