CMaNGOS_WoTLK: Taxi::Tracker Class Reference
Taxi::Tracker Class Reference
This is a container representing player's current taxi ride's routes and destinations.
#include <Taxi.h>
Public Member Functions
Tracker (Player &owner)
Tracker (Tracker const &)=delete
void operator= (const Tracker &)=delete
Tracker (Tracker &&)=delete
Tracker & operator= (Tracker &&)=delete
std::string Save ()
Save contents: string serialization.
bool Load (std::string &string, DestID &destOrphan)
Load contents: string deserialization.
TrackerState GetState () const
bool SetState (TrackerState state)
Notify the container to switch into certain state if applicable.
const Route & GetRoute () const
Get current active route (a single taxi path)
const Roadmap & GetRoadmap () const
Get all pre-calculated routes.
const Map & GetMap () const
Get the current spline for the map.
const Atlas & GetAtlas () const
Get a collection of splines for the entire ride.
uint32 GetCost () const
Get cost of the current route.
uint32 GetCostTotal () const
Get total cost of the entire ride with all routes included.
uint32 GetMountDisplayId () const
Get flying mount displayid for the entire ride (in effect until logout)
Waypoint GetCurrentWaypoint () const
Get the last tracked waypoint on the current taxi spline.
size_t GetCurrentWaypointIndex () const
Get the last tracked node position on the current taxi spline.
size_t GetResumeWaypointIndex () const
Get the last known node we must resume from in the current taxi spline in the case of loading.
bool AddRoute (TaxiPathEntry const *entry, float discountMulti=0.0f, bool requireModel=true)
Add a taxi flight path to the container in addition to the last one, returns true if input is correct.
bool AddRoute (PathID pathID, float discountMulti=0.0f, bool requireModel=true)
Add a taxi flight path to the container by ID in addition to the last one, returns true if input is correct.
bool AddRoute (DestID start, DestID end, float discountMulti=0.0f, bool requireModel=true)
Add a taxi flight path to the container by destinations in addition to the last one, returns true if input is correct.
bool AddRoutes (std::vector< DestID > const &destinations, float discountMulti=0.0f, bool requireModel=true)
Replace any existing container contents with a chain of flights defined by a vector of destinations, returns true if input is correct.
bool AddRoutes (std::deque< PathID > const &paths, float discountMulti=0.0f, bool requireModel=true)
Replace any existing container contents with a chain of flights defined by a deque of flight path ids, returns true if input is correct.
bool Prepare (Index nodeResume=0)
Finalize the container and prepare for the tracking of the flight. Used when all routes are added. It will be impossible to alter the container until the flight ends.
bool Clear (bool forced=false)
Clear the container by removing all contents. Can't be performed if taxi flight tracking is currently active, unless forced.
bool UpdateRoute (const TaxiPathNodeEntry *entry, PathID &start, PathID &end)
Update tick: notify the container about arrival at the taxi spline node, advances internal node tracker and provides info about changes. Returns true when current route has changed.
Static Public Member Functions
static bool Trim (Route &first, Route &second)
Try to join two routes together by determining junction points. Returns true on success.
Data Fields
bool m_debug
Private Attributes
Player & m_owner
TrackerState m_state
uint32 m_cost
uint32 m_displayId
Waypoint m_location
size_t m_locationIndex
size_t m_resumeIndex
Roadmap m_routes
Atlas m_atlas
Detailed Description
This is a container representing player's current taxi ride's routes and destinations.
Definition at line 75 of file Taxi.h.
Constructor & Destructor Documentation
Tracker() [1/3]
Taxi::Tracker::Tracker (Player & owner) inline explicit
Definition at line 78 of file Taxi.h.
Tracker() [2/3]
Taxi::Tracker::Tracker (Tracker const &) delete
Tracker() [3/3]
Taxi::Tracker::Tracker (Tracker &&) delete
Member Function Documentation
AddRoute() [1/3]
bool Tracker::AddRoute (DestID start, DestID end, float discountMulti = 0.0f, bool requireModel = true)
Add a taxi flight path to the container by destinations in addition to the last one, returns true if input is correct.
Definition at line 179 of file Taxi.cpp.
References AddRoute(), m_state, sObjectMgr, and Taxi::TRACKER_STAGING.
AddRoute() [2/3]
bool Tracker::AddRoute (PathID pathID, float discountMulti = 0.0f, bool requireModel = true)
Add a taxi flight path to the container by ID in addition to the last one, returns true if input is correct.
Definition at line 168 of file Taxi.cpp.
References AddRoute(), m_state, sTaxiPathStore, and Taxi::TRACKER_STAGING.
AddRoute() [3/3]
bool Tracker::AddRoute (TaxiPathEntry const * entry, float discountMulti = 0.0f, bool requireModel = true)
Add a taxi flight path to the container in addition to the last one, returns true if input is correct.
Definition at line 124 of file Taxi.cpp.
References Path< PathElem, PathNode >::back(), CONFIG_BOOL_LONG_TAXI_PATHS_PERSISTENCE, TaxiPathEntry::from, Path< PathElem, PathNode >::front(), Player::GetTeam(), TaxiPathEntry::ID, m_cost, m_displayId, m_owner, m_routes, m_state, TaxiPathEntry::price, sObjectMgr, sTaxiPathNodesByPath, sWorld, TaxiPathEntry::to, Taxi::TRACKER_STAGING, and Trim().
Referenced by AddRoute(), and AddRoutes().
AddRoutes() [1/2]
bool Tracker::AddRoutes (std::deque< PathID > const & paths, float discountMulti = 0.0f, bool requireModel = true)
Replace any existing container contents with a chain of flights defined by a deque of flight path ids, returns true if input is correct.
Definition at line 207 of file Taxi.cpp.
References AddRoute(), Clear(), and m_routes.
AddRoutes() [2/2]
bool Tracker::AddRoutes (std::vector< DestID > const & destinations, float discountMulti = 0.0f, bool requireModel = true)
Replace any existing container contents with a chain of flights defined by a vector of destinations, returns true if input is correct.
Definition at line 191 of file Taxi.cpp.
References AddRoute(), Clear(), and m_routes.
Referenced by Player::ActivateTaxiPathTo(), and Load().
Clear()
bool Tracker::Clear (bool forced = false)
Clear the container by removing all contents. Can't be performed if taxi flight tracking is currently active, unless forced.
Definition at line 303 of file Taxi.cpp.
References m_atlas, m_cost, m_displayId, m_location, m_locationIndex, m_resumeIndex, m_routes, m_state, Taxi::TRACKER_EMPTY, and Taxi::TRACKER_STAGING.
Referenced by Player::ActivateTaxiPathTo(), AddRoutes(), Load(), and Player::OnTaxiFlightEject().
GetAtlas()
const Atlas& Taxi::Tracker::GetAtlas () const inline
Get a collection of splines for the entire ride.
Definition at line 103 of file Taxi.h.
References m_atlas.
Referenced by Player::GetTaxiPathSpline(), Player::LoadFromDB(), Player::OnTaxiFlightSplineUpdate(), and Player::OnTaxiFlightUpdate().
GetCost()
uint32 Taxi::Tracker::GetCost () const inline
Get cost of the current route.
Definition at line 106 of file Taxi.h.
References m_routes.
Referenced by Player::OnTaxiFlightRouteEnd(), and Player::OnTaxiFlightRouteStart().
GetCostTotal()
uint32 Taxi::Tracker::GetCostTotal () const inline
Get total cost of the entire ride with all routes included.
Definition at line 108 of file Taxi.h.
References m_cost.
Referenced by Player::ActivateTaxiPathTo().
GetCurrentWaypoint()
Waypoint Taxi::Tracker::GetCurrentWaypoint () const inline
Get the last tracked waypoint on the current taxi spline.
Definition at line 114 of file Taxi.h.
References m_location.
Referenced by Player::OnTaxiFlightUpdate().
GetCurrentWaypointIndex()
size_t Taxi::Tracker::GetCurrentWaypointIndex () const inline
Get the last tracked node position on the current taxi spline.
Definition at line 116 of file Taxi.h.
References m_locationIndex.
Referenced by Player::OnTaxiFlightUpdate().
GetMap()
const Map& Taxi::Tracker::GetMap () const inline
Get the current spline for the map.
Definition at line 101 of file Taxi.h.
References m_atlas.
Referenced by Player::GetTaxiPathSpline(), Player::LoadFromDB(), Player::OnTaxiFlightSplineUpdate(), Player::OnTaxiFlightUpdate(), Save(), and UpdateRoute().
GetMountDisplayId()
uint32 Taxi::Tracker::GetMountDisplayId () const inline
Get flying mount displayid for the entire ride (in effect until logout)
Definition at line 111 of file Taxi.h.
References m_displayId.
Referenced by Player::OnTaxiFlightSplineStart().
GetResumeWaypointIndex()
size_t Taxi::Tracker::GetResumeWaypointIndex () const inline
Get the last known node we must resume from in the current taxi spline in the case of loading.
Definition at line 118 of file Taxi.h.
References m_resumeIndex.
Referenced by Player::GetTaxiPathSplineOffset(), Player::LoadFromDB(), and Player::OnTaxiFlightSplineUpdate().
GetRoadmap()
const Roadmap& Taxi::Tracker::GetRoadmap () const inline
Get all pre-calculated routes.
Definition at line 99 of file Taxi.h.
References m_routes.
Referenced by Player::LoadFromDB().
GetRoute()
const Route& Taxi::Tracker::GetRoute () const inline
Get current active route (a single taxi path)
Definition at line 97 of file Taxi.h.
References m_routes.
Referenced by Player::LoadFromDB(), Save(), and UpdateRoute().
GetState()
TrackerState Taxi::Tracker::GetState () const inline
Definition at line 92 of file Taxi.h.
References m_state.
Referenced by Player::OnTaxiFlightSplineStart(), Player::OnTaxiFlightSplineUpdate(), Player::OnTaxiFlightUpdate(), Player::SetBattleGroundEntryPoint(), and Player::TaxiFlightResume().
Load()
bool Tracker::Load (std::string & string, DestID & destOrphan)
Load contents: string deserialization.
Definition at line 64 of file Taxi.cpp.
References AddRoutes(), Clear(), Prepare(), and StrSplit().
Referenced by Player::LoadFromDB().
operator=() [1/2]
void Taxi::Tracker::operator= (const Tracker &) delete
operator=() [2/2]
Tracker& Taxi::Tracker::operator= (Tracker &&) delete
Prepare()
bool Tracker::Prepare (Index nodeResume = 0)
Finalize the container and prepare for the tracking of the flight. Used when all routes are added. It will be impossible to alter the container until the flight ends.
Definition at line 223 of file Taxi.cpp.
References Path< PathElem, PathNode >::begin(), CONFIG_BOOL_LONG_TAXI_PATHS_PERSISTENCE, Taxi::Route::cost, Path< PathElem, PathNode >::end(), m_atlas, m_cost, m_locationIndex, m_resumeIndex, m_routes, m_state, MANGOS_ASSERT, TaxiPathNodeEntry::mapid, Taxi::Route::nodeEnd, Taxi::Route::pathID, sLog, sMapStore, sTaxiPathNodesByPath, sWorld, Taxi::TRACKER_STAGING, and Taxi::TRACKER_STANDBY.
Referenced by Player::ActivateTaxiPathTo(), and Load().
Save()
std::string Tracker::Save ()
Save contents: string serialization.
Definition at line 34 of file Taxi.cpp.
References CONFIG_BOOL_LONG_TAXI_PATHS_PERSISTENCE, GetMap(), GetRoute(), m_atlas, m_locationIndex, m_routes, m_state, MANGOS_ASSERT, sWorld, and Taxi::TRACKER_FLIGHT.
Referenced by Player::SaveToDB().
SetState()
bool Tracker::SetState (TrackerState state)
Notify the container to switch into certain state if applicable.
Definition at line 107 of file Taxi.cpp.
References m_state, Taxi::TRACKER_FLIGHT, Taxi::TRACKER_STANDBY, and Taxi::TRACKER_TRANSFER.
Referenced by Player::OnTaxiFlightSplineEnd(), and Player::OnTaxiFlightSplineStart().
Trim()
bool Tracker::Trim (Route & first, Route & second) static
Try to join two routes together by determining junction points. Returns true on success.
Definition at line 381 of file Taxi.cpp.
References Path< PathElem, PathNode >::begin(), Taxi::Route::destEnd, Taxi::Route::destStart, Path< PathElem, PathNode >::end(), TaxiShortcutData::lengthLanding, TaxiShortcutData::lengthTakeoff, TaxiPathNodeEntry::mapid, Taxi::Route::nodeEnd, Taxi::Route::nodeStart, Taxi::Route::pathID, Path< PathElem, PathNode >::rbegin(), Path< PathElem, PathNode >::rend(), sObjectMgr, sTaxiNodesStore, sTaxiPathNodesByPath, TaxiNodesEntry::x, and TaxiNodesEntry::y.
Referenced by AddRoute().
UpdateRoute()
bool Tracker::UpdateRoute (const TaxiPathNodeEntry * entry, PathID & start, PathID & end)
Update tick: notify the container about arrival at the taxi spline node, advances internal node tracker and provides info about changes. Returns true when current route has changed.
Definition at line 319 of file Taxi.cpp.
References Taxi::Route::cost, GetMap(), GetRoute(), TaxiPathNodeEntry::index, m_atlas, m_cost, m_displayId, m_location, m_locationIndex, m_resumeIndex, m_routes, m_state, MANGOS_ASSERT, Taxi::Route::nodeEnd, Taxi::Route::nodeStart, Taxi::Route::pathID, Taxi::TRACKER_EMPTY, and Taxi::TRACKER_FLIGHT.
Referenced by Player::OnTaxiFlightUpdate().
Field Documentation
m_atlas
Atlas Taxi::Tracker::m_atlas private
Definition at line 150 of file Taxi.h.
Referenced by Clear(), GetAtlas(), GetMap(), Prepare(), Save(), and UpdateRoute().
m_cost
uint32 Taxi::Tracker::m_cost private
Definition at line 144 of file Taxi.h.
Referenced by AddRoute(), Clear(), GetCostTotal(), Prepare(), and UpdateRoute().
m_debug
bool Taxi::Tracker::m_debug
Definition at line 153 of file Taxi.h.
Referenced by Player::IsTaxiDebug(), and Player::ToggleTaxiDebug().
m_displayId
uint32 Taxi::Tracker::m_displayId private
Definition at line 145 of file Taxi.h.
Referenced by AddRoute(), Clear(), GetMountDisplayId(), and UpdateRoute().
m_location
Waypoint Taxi::Tracker::m_location private
Definition at line 146 of file Taxi.h.
Referenced by Clear(), GetCurrentWaypoint(), and UpdateRoute().
m_locationIndex
size_t Taxi::Tracker::m_locationIndex private
Definition at line 147 of file Taxi.h.
Referenced by Clear(), GetCurrentWaypointIndex(), Prepare(), Save(), and UpdateRoute().
m_owner
Player& Taxi::Tracker::m_owner private
Definition at line 142 of file Taxi.h.
Referenced by AddRoute().
m_resumeIndex
size_t Taxi::Tracker::m_resumeIndex private
Definition at line 148 of file Taxi.h.
Referenced by Clear(), GetResumeWaypointIndex(), Prepare(), and UpdateRoute().
m_routes
Roadmap Taxi::Tracker::m_routes private
Definition at line 149 of file Taxi.h.
Referenced by AddRoute(), AddRoutes(), Clear(), GetCost(), GetRoadmap(), GetRoute(), Prepare(), Save(), and UpdateRoute().
m_state
TrackerState Taxi::Tracker::m_state private
Definition at line 143 of file Taxi.h.
Referenced by AddRoute(), Clear(), GetState(), Prepare(), Save(), SetState(), and UpdateRoute().
The documentation for this class was generated from the following files:
Taxi.h
Taxi.cpp