CMaNGOS_WoTLK: HomeMovementGenerator< Creature > Class Reference
HomeMovementGenerator< Creature > Class Reference
#include <HomeMovementGenerator.h>
Public Member Functions
HomeMovementGenerator (bool _runHome=true)
~HomeMovementGenerator ()
void Initialize (Creature &)
void Finalize (Creature &)
void Interrupt (Creature &)
void Reset (Creature &)
bool Update (Creature &, const uint32 &)
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from MovementGeneratorMedium< Creature, HomeMovementGenerator< Creature > >
void Initialize (Unit &u) override
void Initialize (U &u)
void Finalize (Unit &u) override
void Finalize (U &u)
void Interrupt (Unit &u) override
void Interrupt (U &u)
void Reset (Unit &u) override
void Reset (U &u)
bool Update (Unit &u, const uint32 &time_diff) override
bool Update (U &u, const uint32 &time_diff)
bool GetResetPosition (Unit &u, float &x, float &y, float &z, float &o) const override
bool GetResetPosition (U &, float &, float &, float &, float &) const
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Private Member Functions
void _setTargetLocation (Creature &)
Private Attributes
bool arrived
bool runHome
bool wasActive
Detailed Description
Definition at line 30 of file HomeMovementGenerator.h.
Constructor & Destructor Documentation
HomeMovementGenerator()
HomeMovementGenerator< Creature >::HomeMovementGenerator (bool _runHome = true) inline
Definition at line 35 of file HomeMovementGenerator.h.
~HomeMovementGenerator()
HomeMovementGenerator< Creature >::~HomeMovementGenerator () inline
Definition at line 39 of file HomeMovementGenerator.h.
Member Function Documentation
_setTargetLocation()
void HomeMovementGenerator< Creature >::_setTargetLocation (Creature & owner) private
Definition at line 40 of file HomeMovementGenerator.cpp.
References PathFinder::calculate(), Unit::clearUnitState(), DIST_CALC_NONE, Creature::ForcedDespawn(), Creature::GetCombatStartPosition(), WorldObject::GetDistance(), WorldObject::GetMap(), Unit::GetMotionMaster(), PathFinder::getPath(), PathFinder::getPathType(), WorldObject::GetPosition(), Position::GetPositionO(), Position::GetPositionX(), Position::GetPositionY(), Position::GetPositionZ(), Creature::GetRespawnCoord(), WorldObject::GetTransport(), Unit::hasUnitState(), Map::IsDungeon(), Position::IsEmpty(), Object::IsInWorld(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MovebyPath(), Position::o, PATHFIND_NOPATH, PATHFIND_SHORTCUT, Movement::MoveSplineInit::SetFacing(), Creature::SetRespawnDelay(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), UNIT_STAT_ALL_DYN_STATES, UNIT_STAT_NOT_MOVE, Position::x, Position::y, and Position::z.
Finalize()
void HomeMovementGenerator< Creature >::Finalize (Creature & owner)
Definition at line 88 of file HomeMovementGenerator.cpp.
References Creature::ClearTemporaryFaction(), EVADE_NONE, Map::GetAnyTypeCreature(), Unit::GetCombatManager(), WorldObject::GetMap(), WorldObject::GetSpawnerGuid(), Creature::GetTemporaryFactionFlags(), ObjectGuid::IsCreatureOrPet(), Creature::IsTemporarySummon(), Creature::LoadCreatureAddon(), WorldObject::SetActiveObjectState(), Creature::SetCombatStartPosition(), CombatManager::SetEvadeState(), TEMPFACTION_RESTORE_REACH_HOME, and Unit::TriggerHomeEvents().
GetMovementGeneratorType()
MovementGeneratorType HomeMovementGenerator< Creature >::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Definition at line 46 of file HomeMovementGenerator.h.
References HOME_MOTION_TYPE.
Initialize()
void HomeMovementGenerator< Creature >::Initialize (Creature & owner)
Definition at line 26 of file HomeMovementGenerator.cpp.
References EVADE_HOME, Unit::GetCombatManager(), WorldObject::isActiveObject(), WorldObject::SetActiveObjectState(), and CombatManager::SetEvadeState().
Interrupt()
void HomeMovementGenerator< Creature >::Interrupt (Creature &) inline
Definition at line 43 of file HomeMovementGenerator.h.
Reset()
void HomeMovementGenerator< Creature >::Reset (Creature &)
Definition at line 36 of file HomeMovementGenerator.cpp.
Update()
bool HomeMovementGenerator< Creature >::Update (Creature & owner, const uint32 &)
Definition at line 82 of file HomeMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), and Unit::movespline.
Field Documentation
arrived
bool HomeMovementGenerator< Creature >::arrived private
Definition at line 50 of file HomeMovementGenerator.h.
runHome
bool HomeMovementGenerator< Creature >::runHome private
Definition at line 51 of file HomeMovementGenerator.h.
wasActive
bool HomeMovementGenerator< Creature >::wasActive private
Definition at line 52 of file HomeMovementGenerator.h.
The documentation for this class was generated from the following files:
HomeMovementGenerator.h
HomeMovementGenerator.cpp