CMaNGOS_WoTLK: WintergraspFactory Class Reference
WintergraspFactory Class Reference
#include <BattlefieldWG.h>
Public Member Functions
WintergraspFactory (uint32 entry)
Team GetOwner () const
void SetOwner (Team newOwner)
void SetCapturePointEntry (PvpTeamIndex teamIndex, uint32 entry)
uint32 GetCapturePointEntry (PvpTeamIndex teamIndex)
void SetCapturePointGuid (PvpTeamIndex teamIndex, ObjectGuid guid)
ObjectGuid GetCapturePointGuid (PvpTeamIndex teamIndex)
void SetGraveyardId (uint32 id)
uint32 GetGraveyardId ()
void SetAreaId (uint32 id)
uint32 GetAreaId ()
void SetConditionId (uint32 id)
uint32 GetConditionId ()
Public Member Functions inherited from BattlefieldBuilding
BattlefieldBuilding (uint32 goEntry)
virtual ~BattlefieldBuilding ()=default
bool IsIntact () const
bool IsDamaged () const
bool IsDestroyed () const
uint32 GetWorldState () const
void SetWorldState (uint32 newWorldState)
BattlefieldGoState GetGoState () const
void SetGoState (BattlefieldGoState newState)
BattlefieldGoState GetNeutralGoState () const
BattlefieldGoState GetOppositeGoState () const
void SetGoGuid (ObjectGuid goGuid)
ObjectGuid GetGoGuid ()
uint32 GetGoEntry () const
Protected Attributes
Team m_objectOwner
ObjectGuid m_capturePointGuid [PVP_TEAM_COUNT]
uint32 m_capturePointEntry [PVP_TEAM_COUNT]
uint32 m_graveyardId
uint32 m_areaId
uint32 m_conditionId
Detailed Description
Definition at line 598 of file BattlefieldWG.h.
Constructor & Destructor Documentation
WintergraspFactory()
WintergraspFactory::WintergraspFactory (uint32 entry) inline
Definition at line 601 of file BattlefieldWG.h.
References m_capturePointEntry, m_capturePointGuid, and PVP_TEAM_COUNT.
Member Function Documentation
GetAreaId()
uint32 WintergraspFactory::GetAreaId () inline
Definition at line 628 of file BattlefieldWG.h.
References m_areaId.
GetCapturePointEntry()
uint32 WintergraspFactory::GetCapturePointEntry (PvpTeamIndex teamIndex) inline
Definition at line 616 of file BattlefieldWG.h.
References m_capturePointEntry.
Referenced by BattlefieldWG::LockWorkshops().
GetCapturePointGuid()
ObjectGuid WintergraspFactory::GetCapturePointGuid (PvpTeamIndex teamIndex) inline
Definition at line 620 of file BattlefieldWG.h.
References m_capturePointGuid.
Referenced by BattlefieldWG::LockWorkshops().
GetConditionId()
uint32 WintergraspFactory::GetConditionId () inline
Definition at line 632 of file BattlefieldWG.h.
References m_conditionId.
GetGraveyardId()
uint32 WintergraspFactory::GetGraveyardId () inline
Definition at line 624 of file BattlefieldWG.h.
References m_graveyardId.
GetOwner()
Team WintergraspFactory::GetOwner () const inline
Definition at line 611 of file BattlefieldWG.h.
References m_objectOwner.
Referenced by BattlefieldWG::LockWorkshops().
SetAreaId()
void WintergraspFactory::SetAreaId (uint32 id) inline
Definition at line 627 of file BattlefieldWG.h.
References m_areaId.
Referenced by BattlefieldWG::Reset().
SetCapturePointEntry()
void WintergraspFactory::SetCapturePointEntry (PvpTeamIndex teamIndex, uint32 entry) inline
Definition at line 615 of file BattlefieldWG.h.
References m_capturePointEntry.
Referenced by BattlefieldWG::Reset().
SetCapturePointGuid()
void WintergraspFactory::SetCapturePointGuid (PvpTeamIndex teamIndex, ObjectGuid guid) inline
Definition at line 619 of file BattlefieldWG.h.
References m_capturePointGuid.
SetConditionId()
void WintergraspFactory::SetConditionId (uint32 id) inline
Definition at line 631 of file BattlefieldWG.h.
References m_conditionId.
Referenced by BattlefieldWG::Reset().
SetGraveyardId()
void WintergraspFactory::SetGraveyardId (uint32 id) inline
Definition at line 623 of file BattlefieldWG.h.
References m_graveyardId.
Referenced by BattlefieldWG::Reset().
SetOwner()
void WintergraspFactory::SetOwner (Team newOwner) inline
Definition at line 612 of file BattlefieldWG.h.
References m_objectOwner.
Referenced by BattlefieldWG::Reset().
Field Documentation
m_areaId
uint32 WintergraspFactory::m_areaId protected
Definition at line 641 of file BattlefieldWG.h.
Referenced by GetAreaId(), and SetAreaId().
m_capturePointEntry
uint32 WintergraspFactory::m_capturePointEntry[PVP_TEAM_COUNT] protected
Definition at line 639 of file BattlefieldWG.h.
Referenced by GetCapturePointEntry(), SetCapturePointEntry(), and WintergraspFactory().
m_capturePointGuid
ObjectGuid WintergraspFactory::m_capturePointGuid[PVP_TEAM_COUNT] protected
Definition at line 637 of file BattlefieldWG.h.
Referenced by GetCapturePointGuid(), SetCapturePointGuid(), and WintergraspFactory().
m_conditionId
uint32 WintergraspFactory::m_conditionId protected
Definition at line 642 of file BattlefieldWG.h.
Referenced by GetConditionId(), and SetConditionId().
m_graveyardId
uint32 WintergraspFactory::m_graveyardId protected
Definition at line 640 of file BattlefieldWG.h.
Referenced by GetGraveyardId(), and SetGraveyardId().
m_objectOwner
Team WintergraspFactory::m_objectOwner protected
Definition at line 635 of file BattlefieldWG.h.
Referenced by GetOwner(), and SetOwner().
The documentation for this class was generated from the following file:
BattlefieldWG.h