CMaNGOS_WoTLK: SQLHashStorage Class Reference
SQLHashStorage Class Reference
#include <SQLStorage.h>
Public Member Functions
SQLHashStorage (const char *fmt, const char *_entry_field, const char *sqlname)
SQLHashStorage (const char *src_fmt, const char *dst_fmt, const char *_entry_field, const char *sqlname)
~SQLHashStorage ()
template<class T >
T const * LookupEntry (uint32 id) const
void Load ()
void EraseEntry (uint32 id)
Public Member Functions inherited from SQLStorageBase
char const * GetTableName () const
char const * EntryFieldName () const
FieldFormat GetDstFormat (uint32 idx) const
const char * GetDstFormat () const
FieldFormat GetSrcFormat (uint32 idx) const
const char * GetSrcFormat () const
uint32 GetMaxEntry () const
uint32 GetRecordCount () const
template<typename T >
SQLSIterator< T > getDataBegin () const
template<typename T >
SQLSIterator< T > getDataEnd () const
Protected Member Functions
void prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override
void JustCreatedRecord (uint32 recordId, char *record) override
void Free () override
Protected Member Functions inherited from SQLStorageBase
SQLStorageBase ()
virtual ~SQLStorageBase ()
void Initialize (const char *tableName, const char *entry_field, const char *src_format, const char *dst_format)
uint32 GetDstFieldCount () const
uint32 GetSrcFieldCount () const
uint32 GetRecordSize () const
Private Types
typedef std::unordered_map< uint32, char * > RecordMap
Private Attributes
RecordMap m_indexMap
Friends
template<class DerivedLoader , class StorageClass >
class SQLStorageLoaderBase
Detailed Description
Definition at line 138 of file SQLStorage.h.
Member Typedef Documentation
RecordMap
typedef std::unordered_map<uint32 , char* > SQLHashStorage::RecordMap private
Definition at line 171 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLHashStorage() [1/2]
SQLHashStorage::SQLHashStorage (const char * fmt, const char * _entry_field, const char * sqlname)
Definition at line 196 of file SQLStorage.cpp.
References SQLStorageBase::Initialize().
SQLHashStorage() [2/2]
SQLHashStorage::SQLHashStorage (const char * src_fmt, const char * dst_fmt, const char * _entry_field, const char * sqlname)
Definition at line 201 of file SQLStorage.cpp.
References SQLStorageBase::Initialize().
~SQLHashStorage()
SQLHashStorage::~SQLHashStorage () inline
Definition at line 146 of file SQLStorage.h.
References Free().
Member Function Documentation
EraseEntry()
void SQLHashStorage::EraseEntry (uint32 id)
Definition at line 188 of file SQLStorage.cpp.
References m_indexMap.
Free()
void SQLHashStorage::Free () override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 174 of file SQLStorage.cpp.
References SQLStorageBase::Free(), and m_indexMap.
Referenced by prepareToLoad(), and ~SQLHashStorage().
JustCreatedRecord()
void SQLHashStorage::JustCreatedRecord (uint32 recordId, char * record) inline override protected virtual
Implements SQLStorageBase.
Definition at line 163 of file SQLStorage.h.
References m_indexMap.
Load()
void SQLHashStorage::Load ()
Definition at line 168 of file SQLStorage.cpp.
References SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load().
LookupEntry()
template<class T > T const* SQLHashStorage::LookupEntry (uint32 id) const inline
Definition at line 149 of file SQLStorage.h.
References m_indexMap.
Referenced by CheckGOLinkedTrapId(), PlayerbotClassAI::FleeFromTrapGOIfCan(), ObjectMgr::GetGameObjectInfo(), Player::LoadFromDB(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellScriptTarget(), TransportMgr::LoadTransportTemplates(), and GameObject::TriggerLinkedGameObject().
prepareToLoad()
void SQLHashStorage::prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 180 of file SQLStorage.cpp.
References Free(), and SQLStorageBase::prepareToLoad().
Friends And Related Function Documentation
SQLStorageLoaderBase
template<class DerivedLoader , class StorageClass > friend class SQLStorageLoaderBase friend
Definition at line 140 of file SQLStorage.h.
Field Documentation
m_indexMap
RecordMap SQLHashStorage::m_indexMap private
Definition at line 172 of file SQLStorage.h.
Referenced by EraseEntry(), Free(), JustCreatedRecord(), and LookupEntry().
The documentation for this class was generated from the following files:
SQLStorage.h
SQLStorage.cpp