CMaNGOS_WoTLK: Channel Class Reference
Channel Class Reference
#include <Channel.h>
Data Structures
struct PlayerInfo
Public Types
enum ChannelFlags {
CHANNEL_FLAG_NONE = 0x00 , CHANNEL_FLAG_CUSTOM = 0x01 , CHANNEL_FLAG_TRADE = 0x04 , CHANNEL_FLAG_NOT_LFG = 0x08 ,
CHANNEL_FLAG_GENERAL = 0x10 , CHANNEL_FLAG_CITY = 0x20 , CHANNEL_FLAG_LFG = 0x40 , CHANNEL_FLAG_VOICE = 0x80
}
enum ChannelDBCFlags {
CHANNEL_DBC_FLAG_NONE = 0x00000 , CHANNEL_DBC_FLAG_INITIAL = 0x00001 , CHANNEL_DBC_FLAG_ZONE_DEP = 0x00002 , CHANNEL_DBC_FLAG_GLOBAL = 0x00004 ,
CHANNEL_DBC_FLAG_TRADE = 0x00008 , CHANNEL_DBC_FLAG_CITY_ONLY = 0x00010 , CHANNEL_DBC_FLAG_CITY_ONLY2 = 0x00020 , CHANNEL_DBC_FLAG_DEFENSE = 0x10000 ,
CHANNEL_DBC_FLAG_GUILD_REQ = 0x20000 , CHANNEL_DBC_FLAG_LFG = 0x40000
}
enum ChannelMemberFlags : uint8 {
MEMBER_FLAG_NONE = 0x00 , MEMBER_FLAG_OWNER = 0x01 , MEMBER_FLAG_MODERATOR = 0x02 , MEMBER_FLAG_VOICED = 0x04 ,
MEMBER_FLAG_MUTED = 0x08 , MEMBER_FLAG_CUSTOM = 0x10 , MEMBER_FLAG_MIC_MUTED = 0x20
}
Public Member Functions
Channel (const std::string &name, uint32 channel_id=0)
std::string GetName () const
uint32 GetChannelId () const
const ChatChannelsEntry * GetChannelEntry () const
bool IsConstant () const
bool IsStatic () const
bool IsLFG () const
bool IsPublic () const
std::string GetPassword () const
size_t GetNumPlayers () const
uint8 GetFlags () const
bool HasFlag (uint8 flag) const
void Join (Player *player, const char *password)
void Leave (Player *player, bool send=true)
void KickOrBan (Player *player, const char *targetName, bool ban)
void Kick (Player *player, const char *targetName)
void Ban (Player *player, const char *targetName)
void UnBan (Player *player, const char *targetName)
void SetPassword (Player *player, const char *password)
void SetModeFlags (Player *player, const char *targetName, ChannelMemberFlags flags, bool set)
void SetModerator (Player *player, const char *targetName, bool set)
void SetMute (Player *player, const char *targetName, bool set)
void SetOwner (Player *player, const char *targetName)
void SendChannelOwnerResponse (Player *player) const
void SendChannelListResponse (Player *player, bool display=false)
void ToggleAnnouncements (Player *player)
void ToggleModeration (Player *player)
void Say (Player *player, const char *text, uint32 lang)
void Invite (Player *player, const char *targetName)
void Voice (ObjectGuid guid1, ObjectGuid guid2) const
void DeVoice (ObjectGuid guid1, ObjectGuid guid2) const
void JoinNotify (ObjectGuid guid)
void LeaveNotify (ObjectGuid guid)
bool SetStatic (bool state, bool command=false)
Static Public Member Functions
static void MakeNotifyPacket (WorldPacket &data, const std::string &channel, ChatNotify type)
static void MakeJoined (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeLeft (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeYouJoined (WorldPacket &data, const std::string &channel, const Channel &which)
static void MakeYouLeft (WorldPacket &data, const std::string &channel, const Channel &which)
static void MakeWrongPassword (WorldPacket &data, const std::string &channel)
static void MakeNotMember (WorldPacket &data, const std::string &channel)
static void MakeNotModerator (WorldPacket &data, const std::string &channel)
static void MakePasswordChanged (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeOwnerChanged (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakePlayerNotFound (WorldPacket &data, const std::string &channel, const std::string &name)
static void MakeNotOwner (WorldPacket &data, const std::string &channel)
static void MakeChannelOwner (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeModeChange (WorldPacket &data, const std::string &channel, const ObjectGuid &guid, uint8 oldflags, uint8 newFlags)
static void MakeAnnouncementsOn (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeAnnouncementsOff (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeModerationOn (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeModerationOff (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeMuted (WorldPacket &data, const std::string &channel)
static void MakePlayerKicked (WorldPacket &data, const std::string &channel, const ObjectGuid &target, const ObjectGuid &source)
static void MakeBanned (WorldPacket &data, const std::string &channel)
static void MakePlayerBanned (WorldPacket &data, const std::string &channel, const ObjectGuid &target, const ObjectGuid &source)
static void MakePlayerUnbanned (WorldPacket &data, const std::string &channel, const ObjectGuid &target, const ObjectGuid &source)
static void MakePlayerNotBanned (WorldPacket &data, const std::string &channel, const std::string &name)
static void MakePlayerAlreadyMember (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeInvite (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeInviteWrongFaction (WorldPacket &data, const std::string &channel)
static void MakeWrongFaction (WorldPacket &data, const std::string &channel)
static void MakeInvalidName (WorldPacket &data, const std::string &channel)
static void MakeNotModerated (WorldPacket &data, const std::string &channel)
static void MakePlayerInvited (WorldPacket &data, const std::string &channel, const std::string &name)
static void MakePlayerInviteBanned (WorldPacket &data, const std::string &channel, const std::string &name)
static void MakeThrottled (WorldPacket &data, const std::string &channel)
static void MakeNotInArea (WorldPacket &data, const std::string &channel)
static void MakeNotInLFG (WorldPacket &data, const std::string &channel)
static void MakeVoiceOn (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeVoiceOff (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
static void MakeVoiceTrialRestricted (WorldPacket &data, const std::string &channel, const ObjectGuid &guid)
Private Types
typedef std::map< ObjectGuid, PlayerInfo > PlayerList
Private Member Functions
void SendToOne (WorldPacket const &data, ObjectGuid receiver) const
void SendToAll (WorldPacket const &data) const
void SendMessage (WorldPacket const &data, ObjectGuid sender) const
bool IsOn (ObjectGuid who) const
bool IsBanned (ObjectGuid guid) const
uint8 GetPlayerFlags (ObjectGuid guid) const
ObjectGuid SelectNewOwner () const
void SetModeFlags (ObjectGuid guid, ChannelMemberFlags flags, bool set)
void SetOwner (ObjectGuid guid, bool exclaim=true)
Private Attributes
std::string m_name
std::string m_password
ObjectGuid m_ownerGuid
PlayerList m_players
GuidSet m_banned
const ChatChannelsEntry * m_entry = nullptr
bool m_announcements = false
bool m_moderation = false
uint8 m_flags = CHANNEL_FLAG_NONE
bool m_static = false
bool m_realmzone = false
Detailed Description
Definition at line 72 of file Channel.h.
Member Typedef Documentation
PlayerList
typedef std::map<ObjectGuid, PlayerInfo> Channel::PlayerList private
Definition at line 137 of file Channel.h.
Member Enumeration Documentation
ChannelDBCFlags
enum Channel::ChannelDBCFlags
Enumerator
CHANNEL_DBC_FLAG_NONE
CHANNEL_DBC_FLAG_INITIAL
CHANNEL_DBC_FLAG_ZONE_DEP
CHANNEL_DBC_FLAG_GLOBAL
CHANNEL_DBC_FLAG_TRADE
CHANNEL_DBC_FLAG_CITY_ONLY
CHANNEL_DBC_FLAG_CITY_ONLY2
CHANNEL_DBC_FLAG_DEFENSE
CHANNEL_DBC_FLAG_GUILD_REQ
CHANNEL_DBC_FLAG_LFG
Definition at line 93 of file Channel.h.
ChannelFlags
enum Channel::ChannelFlags
Enumerator
CHANNEL_FLAG_NONE
CHANNEL_FLAG_CUSTOM
CHANNEL_FLAG_TRADE
CHANNEL_FLAG_NOT_LFG
CHANNEL_FLAG_GENERAL
CHANNEL_FLAG_CITY
CHANNEL_FLAG_LFG
CHANNEL_FLAG_VOICE
Definition at line 75 of file Channel.h.
ChannelMemberFlags
enum Channel::ChannelMemberFlags : uint8
Enumerator
MEMBER_FLAG_NONE
MEMBER_FLAG_OWNER
MEMBER_FLAG_MODERATOR
MEMBER_FLAG_VOICED
MEMBER_FLAG_MUTED
MEMBER_FLAG_CUSTOM
MEMBER_FLAG_MIC_MUTED
Definition at line 107 of file Channel.h.
Constructor & Destructor Documentation
Channel()
Channel::Channel (const std::string & name, uint32 channel_id = 0)
Definition at line 26 of file Channel.cpp.
References CHANNEL_DBC_FLAG_CITY_ONLY2, CHANNEL_DBC_FLAG_LFG, CHANNEL_DBC_FLAG_TRADE, CHANNEL_FLAG_CITY, CHANNEL_FLAG_CUSTOM, CHANNEL_FLAG_GENERAL, CHANNEL_FLAG_LFG, CHANNEL_FLAG_NOT_LFG, CHANNEL_FLAG_TRADE, GetChatChannelsEntryFor(), m_announcements, m_entry, m_flags, m_name, m_realmzone, and sObjectMgr.
Member Function Documentation
Ban()
void Channel::Ban (Player * player, const char * targetName) inline
Definition at line 157 of file Channel.h.
References KickOrBan().
DeVoice()
void Channel::DeVoice (ObjectGuid guid1, ObjectGuid guid2) const
Definition at line 765 of file Channel.cpp.
GetChannelEntry()
const ChatChannelsEntry* Channel::GetChannelEntry () const inline
Definition at line 143 of file Channel.h.
References m_entry.
GetChannelId()
uint32 Channel::GetChannelId () const inline
Definition at line 142 of file Channel.h.
References ChatChannelsEntry::ChannelID, and m_entry.
Referenced by MakeYouJoined(), and MakeYouLeft().
GetFlags()
uint8 Channel::GetFlags () const inline
Definition at line 150 of file Channel.h.
References m_flags.
Referenced by IsLFG(), Join(), JoinNotify(), LeaveNotify(), MakeYouJoined(), and SendChannelListResponse().
GetName()
std::string Channel::GetName () const inline
Definition at line 141 of file Channel.h.
References m_name.
Referenced by Player::CleanupChannels(), ChatHandler::HandleChannelStaticCommand(), JoinNotify(), LeaveNotify(), and SendChannelListResponse().
GetNumPlayers()
size_t Channel::GetNumPlayers () const inline
Definition at line 149 of file Channel.h.
References m_players.
Referenced by ChatHandler::HandleChannelListCommand(), JoinNotify(), LeaveNotify(), ChannelMgr::LeftChannel(), and SetStatic().
GetPassword()
std::string Channel::GetPassword () const inline
Definition at line 148 of file Channel.h.
References m_password.
Referenced by ChatHandler::HandleChannelStaticCommand().
GetPlayerFlags()
uint8 Channel::GetPlayerFlags (ObjectGuid guid) const inline private
Definition at line 227 of file Channel.h.
References m_players.
Referenced by JoinNotify(), SetModeFlags(), and SetOwner().
HasFlag()
bool Channel::HasFlag (uint8 flag) const inline
Definition at line 151 of file Channel.h.
References m_flags.
Referenced by Join(), SetModeFlags(), and SetStatic().
Invite()
void Channel::Invite (Player * player, const char * targetName)
Definition at line 679 of file Channel.cpp.
References SessionAnticheatInterface::ChannelInvite(), ByteBuffer::clear(), CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, WorldSession::GetAnticheat(), Object::GetObjectGuid(), Player::GetSession(), Player::GetSocial(), Player::GetTeam(), PlayerSocial::HasIgnore(), IsBanned(), IsOn(), SessionAnticheatInterface::IsSilenced(), m_name, MakeInvite(), MakeInviteWrongFaction(), MakeNotMember(), MakePlayerAlreadyMember(), MakePlayerInviteBanned(), MakePlayerInvited(), MakePlayerNotFound(), SendToOne(), sObjectMgr, and sWorld.
IsBanned()
bool Channel::IsBanned (ObjectGuid guid) const inline private
Definition at line 225 of file Channel.h.
References m_banned.
Referenced by Invite(), Join(), KickOrBan(), and UnBan().
IsConstant()
bool Channel::IsConstant () const inline
Definition at line 144 of file Channel.h.
References m_entry.
Referenced by IsPublic(), Join(), JoinNotify(), ChannelMgr::LeftChannel(), Say(), and SetStatic().
IsLFG()
bool Channel::IsLFG () const inline
Definition at line 146 of file Channel.h.
References CHANNEL_FLAG_LFG, and GetFlags().
IsOn()
bool Channel::IsOn (ObjectGuid who) const inline private
Definition at line 224 of file Channel.h.
References m_players.
Referenced by Invite(), Join(), KickOrBan(), Leave(), Say(), SendChannelListResponse(), SendChannelOwnerResponse(), SetModeFlags(), SetOwner(), SetPassword(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
IsPublic()
bool Channel::IsPublic () const inline
Definition at line 147 of file Channel.h.
References IsConstant(), and IsStatic().
Referenced by Join(), KickOrBan(), Leave(), and Say().
IsStatic()
bool Channel::IsStatic () const inline
Definition at line 145 of file Channel.h.
References m_static.
Referenced by ChatHandler::HandleChannelStaticCommand(), and IsPublic().
Join()
void Channel::Join (Player * player, const char * password)
Definition at line 59 of file Channel.cpp.
References CHANNEL_FLAG_LFG, ByteBuffer::clear(), CONFIG_BOOL_CHANNEL_RESTRICTED_LFG, CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, CONFIG_UINT32_GM_LEVEL_CHANNEL_SILENT_JOIN, Channel::PlayerInfo::flags, GetFlags(), Player::GetGuildId(), Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), HasFlag(), IsBanned(), IsConstant(), IsOn(), IsPublic(), Player::JoinedChannel(), JoinNotify(), m_announcements, m_name, m_ownerGuid, m_password, m_players, MakeBanned(), MakeJoined(), MakeNotInLFG(), MakePlayerAlreadyMember(), MakeWrongPassword(), MakeYouJoined(), MEMBER_FLAG_NONE, Channel::PlayerInfo::player, SEC_PLAYER, SendToAll(), SendToOne(), SetOwner(), SetStatic(), and sWorld.
Referenced by Player::UpdateLocalChannels().
JoinNotify()
void Channel::JoinNotify (ObjectGuid guid)
Definition at line 769 of file Channel.cpp.
References GetFlags(), GetName(), GetNumPlayers(), GetPlayerFlags(), WorldPacket::Initialize(), IsConstant(), SendToAll(), SMSG_USERLIST_ADD, and SMSG_USERLIST_UPDATE.
Referenced by Join().
Kick()
void Channel::Kick (Player * player, const char * targetName) inline
Definition at line 156 of file Channel.h.
References KickOrBan().
KickOrBan()
void Channel::KickOrBan (Player * player, const char * targetName, bool ban)
Definition at line 183 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsBanned(), IsOn(), IsPublic(), Player::LeftChannel(), m_banned, m_name, m_ownerGuid, m_players, MakeNotMember(), MakeNotModerator(), MakeNotOwner(), MakePlayerBanned(), MakePlayerKicked(), MakePlayerNotFound(), SelectNewOwner(), SendToAll(), SendToOne(), SetOwner(), sObjectMgr, and sWorld.
Referenced by Ban(), and Kick().
Leave()
void Channel::Leave (Player * player, bool send = true)
Definition at line 138 of file Channel.cpp.
References ByteBuffer::clear(), CONFIG_UINT32_GM_LEVEL_CHANNEL_SILENT_JOIN, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), IsPublic(), LeaveNotify(), Player::LeftChannel(), m_announcements, m_name, m_players, MakeLeft(), MakeNotMember(), MakeYouLeft(), SelectNewOwner(), SendToAll(), SendToOne(), SetOwner(), and sWorld.
Referenced by Player::CleanupChannels().
LeaveNotify()
void Channel::LeaveNotify (ObjectGuid guid)
Definition at line 786 of file Channel.cpp.
References GetFlags(), GetName(), GetNumPlayers(), SendToAll(), and SMSG_USERLIST_REMOVE.
Referenced by Leave().
MakeAnnouncementsOff()
void Channel::MakeAnnouncementsOff (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 895 of file Channel.cpp.
References CHAT_ANNOUNCEMENTS_OFF_NOTICE, and MakeNotifyPacket().
Referenced by SetStatic(), and ToggleAnnouncements().
MakeAnnouncementsOn()
void Channel::MakeAnnouncementsOn (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 889 of file Channel.cpp.
References CHAT_ANNOUNCEMENTS_ON_NOTICE, and MakeNotifyPacket().
Referenced by ToggleAnnouncements().
MakeBanned()
void Channel::MakeBanned (WorldPacket & data, const std::string & channel) static
Definition at line 925 of file Channel.cpp.
References CHAT_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by Join().
MakeChannelOwner()
void Channel::MakeChannelOwner (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 868 of file Channel.cpp.
References CHAT_CHANNEL_OWNER_NOTICE, MakeNotifyPacket(), and sObjectMgr.
Referenced by SendChannelOwnerResponse().
MakeInvalidName()
void Channel::MakeInvalidName (WorldPacket & data, const std::string & channel) static
Definition at line 972 of file Channel.cpp.
References CHAT_INVALID_NAME_NOTICE, and MakeNotifyPacket().
MakeInvite()
void Channel::MakeInvite (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 956 of file Channel.cpp.
References CHAT_INVITE_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakeInviteWrongFaction()
void Channel::MakeInviteWrongFaction (WorldPacket & data, const std::string & channel) static
Definition at line 962 of file Channel.cpp.
References CHAT_INVITE_WRONG_FACTION_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakeJoined()
void Channel::MakeJoined (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 803 of file Channel.cpp.
References CHAT_JOINED_NOTICE, and MakeNotifyPacket().
Referenced by Join().
MakeLeft()
void Channel::MakeLeft (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 809 of file Channel.cpp.
References CHAT_LEFT_NOTICE, and MakeNotifyPacket().
Referenced by Leave().
MakeModeChange()
void Channel::MakeModeChange (WorldPacket & data, const std::string & channel, const ObjectGuid & guid, uint8 oldflags, uint8 newFlags) static
Definition at line 881 of file Channel.cpp.
References CHAT_MODE_CHANGE_NOTICE, and MakeNotifyPacket().
Referenced by SetModeFlags(), and SetOwner().
MakeModerationOff()
void Channel::MakeModerationOff (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 907 of file Channel.cpp.
References CHAT_MODERATION_OFF_NOTICE, and MakeNotifyPacket().
Referenced by SetStatic(), and ToggleModeration().
MakeModerationOn()
void Channel::MakeModerationOn (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 901 of file Channel.cpp.
References CHAT_MODERATION_ON_NOTICE, and MakeNotifyPacket().
Referenced by ToggleModeration().
MakeMuted()
void Channel::MakeMuted (WorldPacket & data, const std::string & channel) static
Definition at line 913 of file Channel.cpp.
References CHAT_MUTED_NOTICE, and MakeNotifyPacket().
Referenced by Say().
MakeNotifyPacket()
void Channel::MakeNotifyPacket (WorldPacket & data, const std::string & channel, ChatNotify type) static
Definition at line 796 of file Channel.cpp.
References WorldPacket::Initialize(), and SMSG_CHANNEL_NOTIFY.
Referenced by MakeAnnouncementsOff(), MakeAnnouncementsOn(), MakeBanned(), MakeChannelOwner(), MakeInvalidName(), MakeInvite(), MakeInviteWrongFaction(), MakeJoined(), MakeLeft(), MakeModeChange(), MakeModerationOff(), MakeModerationOn(), MakeMuted(), MakeNotInArea(), MakeNotInLFG(), MakeNotMember(), MakeNotModerated(), MakeNotModerator(), MakeNotOwner(), MakeOwnerChanged(), MakePasswordChanged(), MakePlayerAlreadyMember(), MakePlayerBanned(), MakePlayerInviteBanned(), MakePlayerInvited(), MakePlayerKicked(), MakePlayerNotBanned(), MakePlayerNotFound(), MakePlayerUnbanned(), MakeThrottled(), MakeVoiceOff(), MakeVoiceOn(), MakeVoiceTrialRestricted(), MakeWrongFaction(), MakeWrongPassword(), MakeYouJoined(), and MakeYouLeft().
MakeNotInArea()
void Channel::MakeNotInArea (WorldPacket & data, const std::string & channel) static
Definition at line 999 of file Channel.cpp.
References CHAT_NOT_IN_AREA_NOTICE, and MakeNotifyPacket().
MakeNotInLFG()
void Channel::MakeNotInLFG (WorldPacket & data, const std::string & channel) static
Definition at line 1004 of file Channel.cpp.
References CHAT_NOT_IN_LFG_NOTICE, and MakeNotifyPacket().
Referenced by Join().
MakeNotMember()
void Channel::MakeNotMember (WorldPacket & data, const std::string & channel) static
Definition at line 835 of file Channel.cpp.
References CHAT_NOT_MEMBER_NOTICE, and MakeNotifyPacket().
Referenced by ChannelMgr::GetChannel(), Invite(), KickOrBan(), Leave(), Say(), SendChannelListResponse(), SendChannelOwnerResponse(), SetModeFlags(), SetOwner(), SetPassword(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
MakeNotModerated()
void Channel::MakeNotModerated (WorldPacket & data, const std::string & channel) static
Definition at line 977 of file Channel.cpp.
References CHAT_NOT_MODERATED_NOTICE, and MakeNotifyPacket().
MakeNotModerator()
void Channel::MakeNotModerator (WorldPacket & data, const std::string & channel) static
Definition at line 840 of file Channel.cpp.
References CHAT_NOT_MODERATOR_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan(), Say(), SetModeFlags(), SetPassword(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
MakeNotOwner()
void Channel::MakeNotOwner (WorldPacket & data, const std::string & channel) static
Definition at line 863 of file Channel.cpp.
References CHAT_NOT_OWNER_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan(), SetModeFlags(), and SetOwner().
MakeOwnerChanged()
void Channel::MakeOwnerChanged (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 851 of file Channel.cpp.
References CHAT_OWNER_CHANGED_NOTICE, and MakeNotifyPacket().
Referenced by SetOwner().
MakePasswordChanged()
void Channel::MakePasswordChanged (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 845 of file Channel.cpp.
References CHAT_PASSWORD_CHANGED_NOTICE, and MakeNotifyPacket().
Referenced by SetPassword().
MakePlayerAlreadyMember()
void Channel::MakePlayerAlreadyMember (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 950 of file Channel.cpp.
References CHAT_PLAYER_ALREADY_MEMBER_NOTICE, and MakeNotifyPacket().
Referenced by Invite(), and Join().
MakePlayerBanned()
void Channel::MakePlayerBanned (WorldPacket & data, const std::string & channel, const ObjectGuid & target, const ObjectGuid & source) static
Definition at line 930 of file Channel.cpp.
References CHAT_PLAYER_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan().
MakePlayerInviteBanned()
void Channel::MakePlayerInviteBanned (WorldPacket & data, const std::string & channel, const std::string & name) static
Definition at line 988 of file Channel.cpp.
References CHAT_PLAYER_INVITE_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakePlayerInvited()
void Channel::MakePlayerInvited (WorldPacket & data, const std::string & channel, const std::string & name) static
Definition at line 982 of file Channel.cpp.
References CHAT_PLAYER_INVITED_NOTICE, and MakeNotifyPacket().
Referenced by Invite().
MakePlayerKicked()
void Channel::MakePlayerKicked (WorldPacket & data, const std::string & channel, const ObjectGuid & target, const ObjectGuid & source) static
Definition at line 918 of file Channel.cpp.
References CHAT_PLAYER_KICKED_NOTICE, and MakeNotifyPacket().
Referenced by KickOrBan().
MakePlayerNotBanned()
void Channel::MakePlayerNotBanned (WorldPacket & data, const std::string & channel, const std::string & name) static
Definition at line 944 of file Channel.cpp.
References CHAT_PLAYER_NOT_BANNED_NOTICE, and MakeNotifyPacket().
Referenced by UnBan().
MakePlayerNotFound()
void Channel::MakePlayerNotFound (WorldPacket & data, const std::string & channel, const std::string & name) static
Definition at line 857 of file Channel.cpp.
References CHAT_PLAYER_NOT_FOUND_NOTICE, and MakeNotifyPacket().
Referenced by Invite(), KickOrBan(), SetModeFlags(), SetOwner(), and UnBan().
MakePlayerUnbanned()
void Channel::MakePlayerUnbanned (WorldPacket & data, const std::string & channel, const ObjectGuid & target, const ObjectGuid & source) static
Definition at line 937 of file Channel.cpp.
References CHAT_PLAYER_UNBANNED_NOTICE, and MakeNotifyPacket().
Referenced by UnBan().
MakeThrottled()
void Channel::MakeThrottled (WorldPacket & data, const std::string & channel) static
Definition at line 994 of file Channel.cpp.
References CHAT_THROTTLED_NOTICE, and MakeNotifyPacket().
MakeVoiceOff()
void Channel::MakeVoiceOff (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 1015 of file Channel.cpp.
References CHAT_VOICE_OFF_NOTICE, and MakeNotifyPacket().
MakeVoiceOn()
void Channel::MakeVoiceOn (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 1009 of file Channel.cpp.
References CHAT_VOICE_ON_NOTICE, and MakeNotifyPacket().
MakeVoiceTrialRestricted()
void Channel::MakeVoiceTrialRestricted (WorldPacket & data, const std::string & channel, const ObjectGuid & guid) static
Definition at line 1021 of file Channel.cpp.
References CHAT_VOICE_TRIAL_RESTRICTED, and MakeNotifyPacket().
MakeWrongFaction()
void Channel::MakeWrongFaction (WorldPacket & data, const std::string & channel) static
Definition at line 967 of file Channel.cpp.
References CHAT_WRONG_FACTION_NOTICE, and MakeNotifyPacket().
MakeWrongPassword()
void Channel::MakeWrongPassword (WorldPacket & data, const std::string & channel) static
Definition at line 830 of file Channel.cpp.
References CHAT_WRONG_PASSWORD_NOTICE, and MakeNotifyPacket().
Referenced by Join().
MakeYouJoined()
void Channel::MakeYouJoined (WorldPacket & data, const std::string & channel, const Channel & which) static
Definition at line 815 of file Channel.cpp.
References CHAT_YOU_JOINED_NOTICE, GetChannelId(), GetFlags(), and MakeNotifyPacket().
Referenced by Join().
MakeYouLeft()
void Channel::MakeYouLeft (WorldPacket & data, const std::string & channel, const Channel & which) static
Definition at line 823 of file Channel.cpp.
References CHAT_YOU_LEFT_NOTICE, GetChannelId(), and MakeNotifyPacket().
Referenced by Leave().
Say()
void Channel::Say (Player * player, const char * text, uint32 lang)
Definition at line 608 of file Channel.cpp.
References ChatHandler::BuildChatPacket(), CHAT_MSG_CHANNEL, CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, CONFIG_UINT32_CHANNEL_RESTRICTED_LANGUAGE_MODE, CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, WorldSession::GetAnticheat(), Player::GetChatTag(), WorldObject::GetName(), Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsConstant(), IsOn(), IsPublic(), SessionAnticheatInterface::IsSilenced(), LANG_UNIVERSAL, m_moderation, m_name, m_players, m_realmzone, MakeMuted(), MakeNotMember(), MakeNotModerator(), SendMessage(), WorldSession::SendPacket(), SendToOne(), sObjectMgr, and sWorld.
SelectNewOwner()
ObjectGuid Channel::SelectNewOwner () const private
Definition at line 1027 of file Channel.cpp.
References m_players.
Referenced by KickOrBan(), Leave(), and SetStatic().
SendChannelListResponse()
void Channel::SendChannelListResponse (Player * player, bool display = false)
Definition at line 493 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST, GetFlags(), GetName(), Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), m_name, m_players, MakeNotMember(), ByteBuffer::put(), SEC_PLAYER, SendToOne(), SMSG_CHANNEL_LIST, sObjectMgr, sWorld, and ByteBuffer::wpos().
SendChannelOwnerResponse()
void Channel::SendChannelOwnerResponse (Player * player) const
Definition at line 460 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), m_name, m_ownerGuid, MakeChannelOwner(), MakeNotMember(), SEC_PLAYER, SendToOne(), sObjectMgr, and sWorld.
SendMessage()
void Channel::SendMessage (WorldPacket const & data, ObjectGuid sender) const private
Definition at line 753 of file Channel.cpp.
References m_players, and sObjectMgr.
Referenced by Say().
SendToAll()
void Channel::SendToAll (WorldPacket const & data) const private
Definition at line 747 of file Channel.cpp.
References m_players, and SendToOne().
Referenced by Join(), JoinNotify(), KickOrBan(), Leave(), LeaveNotify(), SetModeFlags(), SetOwner(), SetPassword(), SetStatic(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
SendToOne()
void Channel::SendToOne (WorldPacket const & data, ObjectGuid receiver) const private
Definition at line 741 of file Channel.cpp.
References sObjectMgr.
Referenced by Invite(), Join(), KickOrBan(), Leave(), Say(), SendChannelListResponse(), SendChannelOwnerResponse(), SendToAll(), SetModeFlags(), SetOwner(), SetPassword(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
SetModeFlags() [1/2]
void Channel::SetModeFlags (ObjectGuid guid, ChannelMemberFlags flags, bool set) private
Definition at line 1039 of file Channel.cpp.
References GetPlayerFlags(), HasFlag(), m_name, m_players, MakeModeChange(), MEMBER_FLAG_MODERATOR, MEMBER_FLAG_MUTED, and SendToAll().
SetModeFlags() [2/2]
void Channel::SetModeFlags (Player * player, const char * targetName, ChannelMemberFlags flags, bool set)
Definition at line 333 of file Channel.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeam(), IsOn(), m_name, m_ownerGuid, m_players, MakeNotMember(), MakeNotModerator(), MakeNotOwner(), MakePlayerNotFound(), MEMBER_FLAG_MODERATOR, MEMBER_FLAG_MUTED, SendToOne(), sObjectMgr, and sWorld.
Referenced by SetModerator(), SetMute(), and SetStatic().
SetModerator()
void Channel::SetModerator (Player * player, const char * targetName, bool set) inline
Definition at line 161 of file Channel.h.
References MEMBER_FLAG_MODERATOR, and SetModeFlags().
SetMute()
void Channel::SetMute (Player * player, const char * targetName, bool set) inline
Definition at line 162 of file Channel.h.
References MEMBER_FLAG_MUTED, and SetModeFlags().
SetOwner() [1/2]
void Channel::SetOwner (ObjectGuid guid, bool exclaim = true) private
Definition at line 1055 of file Channel.cpp.
References GetPlayerFlags(), m_name, m_ownerGuid, m_players, MakeModeChange(), MakeOwnerChanged(), and SendToAll().
SetOwner() [2/2]
void Channel::SetOwner (Player * player, const char * targetName)
Definition at line 407 of file Channel.cpp.
References CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL, CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), Player::GetTeam(), IsOn(), m_name, m_ownerGuid, m_players, MakeNotMember(), MakeNotOwner(), MakePlayerNotFound(), SendToOne(), sObjectMgr, and sWorld.
Referenced by Join(), KickOrBan(), Leave(), and SetStatic().
SetPassword()
void Channel::SetPassword (Player * player, const char * password)
Definition at line 302 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), m_name, m_password, m_players, MakeNotMember(), MakeNotModerator(), MakePasswordChanged(), SendToAll(), SendToOne(), and sWorld.
SetStatic()
bool Channel::SetStatic (bool state, bool command = false)
Definition at line 1098 of file Channel.cpp.
References CHANNEL_FLAG_CUSTOM, CONFIG_UINT32_CHANNEL_STATIC_AUTO_TRESHOLD, GetNumPlayers(), HasFlag(), IsConstant(), m_announcements, m_moderation, m_name, m_ownerGuid, m_password, m_players, m_static, MakeAnnouncementsOff(), MakeModerationOff(), MEMBER_FLAG_MODERATOR, SelectNewOwner(), SendToAll(), SetModeFlags(), SetOwner(), and sWorld.
Referenced by ChatHandler::HandleChannelStaticCommand(), and Join().
ToggleAnnouncements()
void Channel::ToggleAnnouncements (Player * player)
Definition at line 538 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), m_announcements, m_name, m_players, MakeAnnouncementsOff(), MakeAnnouncementsOn(), MakeNotMember(), MakeNotModerator(), SendToAll(), SendToOne(), and sWorld.
ToggleModeration()
void Channel::ToggleModeration (Player * player)
Definition at line 573 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsOn(), m_moderation, m_name, m_players, MakeModerationOff(), MakeModerationOn(), MakeNotMember(), MakeNotModerator(), SendToAll(), SendToOne(), and sWorld.
UnBan()
void Channel::UnBan (Player * player, const char * targetName)
Definition at line 253 of file Channel.cpp.
References CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION, Object::GetObjectGuid(), WorldSession::GetSecurity(), Player::GetSession(), IsBanned(), IsOn(), m_banned, m_name, m_players, MakeNotMember(), MakeNotModerator(), MakePlayerNotBanned(), MakePlayerNotFound(), MakePlayerUnbanned(), SendToAll(), SendToOne(), sObjectMgr, and sWorld.
Voice()
void Channel::Voice (ObjectGuid guid1, ObjectGuid guid2) const
Definition at line 761 of file Channel.cpp.
Field Documentation
m_announcements
bool Channel::m_announcements = false private
Definition at line 248 of file Channel.h.
Referenced by Channel(), Join(), Leave(), SetStatic(), and ToggleAnnouncements().
m_banned
GuidSet Channel::m_banned private
Definition at line 246 of file Channel.h.
Referenced by IsBanned(), KickOrBan(), and UnBan().
m_entry
const ChatChannelsEntry* Channel::m_entry = nullptr private
Definition at line 247 of file Channel.h.
Referenced by Channel(), GetChannelEntry(), GetChannelId(), and IsConstant().
m_flags
uint8 Channel::m_flags = CHANNEL_FLAG_NONE private
Definition at line 250 of file Channel.h.
Referenced by Channel(), GetFlags(), and HasFlag().
m_moderation
bool Channel::m_moderation = false private
Definition at line 249 of file Channel.h.
Referenced by Say(), SetStatic(), and ToggleModeration().
m_name
std::string Channel::m_name private
Definition at line 242 of file Channel.h.
Referenced by Channel(), GetName(), Invite(), Join(), KickOrBan(), Leave(), Say(), SendChannelListResponse(), SendChannelOwnerResponse(), SetModeFlags(), SetOwner(), SetPassword(), SetStatic(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
m_ownerGuid
ObjectGuid Channel::m_ownerGuid private
Definition at line 244 of file Channel.h.
Referenced by Join(), KickOrBan(), SendChannelOwnerResponse(), SetModeFlags(), SetOwner(), and SetStatic().
m_password
std::string Channel::m_password private
Definition at line 243 of file Channel.h.
Referenced by GetPassword(), Join(), SetPassword(), and SetStatic().
m_players
PlayerList Channel::m_players private
Definition at line 245 of file Channel.h.
Referenced by GetNumPlayers(), GetPlayerFlags(), IsOn(), Join(), KickOrBan(), Leave(), Say(), SelectNewOwner(), SendChannelListResponse(), SendMessage(), SendToAll(), SetModeFlags(), SetOwner(), SetPassword(), SetStatic(), ToggleAnnouncements(), ToggleModeration(), and UnBan().
m_realmzone
bool Channel::m_realmzone = false private
Definition at line 253 of file Channel.h.
Referenced by Channel(), and Say().
m_static
bool Channel::m_static = false private
Definition at line 252 of file Channel.h.
Referenced by IsStatic(), and SetStatic().
The documentation for this class was generated from the following files:
Channel.h
Channel.cpp