CMaNGOS_WoTLK: MaNGOS::RespawnDo Class Reference
MaNGOS::RespawnDo Class Reference
#include <GridNotifiers.h>
Public Member Functions
RespawnDo ()
void operator() (Creature *u) const
void operator() (GameObject *u) const
void operator() (WorldObject *) const
void operator() (Corpse *) const
Detailed Description
Definition at line 682 of file GridNotifiers.h.
Constructor & Destructor Documentation
RespawnDo()
MaNGOS::RespawnDo::RespawnDo () inline
Definition at line 685 of file GridNotifiers.h.
Member Function Documentation
operator()() [1/4]
void MaNGOS::RespawnDo::operator() (Corpse *) const inline
Definition at line 689 of file GridNotifiers.h.
operator()() [2/4]
void MaNGOS::RespawnDo::operator() (Creature * u) const
Definition at line 267 of file GridNotifiers.cpp.
References BattleGroundEventIdx::event1, BattleGroundEventIdx::event2, Object::GetDbGuid(), WorldObject::GetMap(), Map::GetMapDataContainer(), Map::GetPersistentState(), MapDataContainer::GetSpawnGroupByGuid(), Map::GetSpawnManager(), Map::IsBattleGroundOrArena(), WorldObject::IsUsingNewSpawningSystem(), Creature::Respawn(), SpawnManager::RespawnCreature(), MapPersistentState::SaveCreatureRespawnTime(), sBattleGroundMgr, and TYPEID_UNIT.
operator()() [3/4]
void MaNGOS::RespawnDo::operator() (GameObject * u) const
Definition at line 289 of file GridNotifiers.cpp.
References BattleGroundEventIdx::event1, BattleGroundEventIdx::event2, Object::GetDbGuid(), WorldObject::GetMap(), Map::IsBattleGroundOrArena(), GameObject::Respawn(), and sBattleGroundMgr.
operator()() [4/4]
void MaNGOS::RespawnDo::operator() (WorldObject *) const inline
Definition at line 688 of file GridNotifiers.h.
The documentation for this class was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp