CMaNGOS_WoTLK: RefManager< TO, FROM > Class Template Reference
RefManager< TO, FROM > Class Template Reference
#include <RefManager.h>
Public Types
typedef LinkedListHead::Iterator< Reference< TO, FROM > > iterator
typedef LinkedListHead::Iterator< Reference< TO, FROM > const > const_iterator
Public Types inherited from LinkedListHead
typedef Iterator< LinkedListElement > iterator
Public Member Functions
RefManager ()
virtual ~RefManager ()
Reference< TO, FROM > * getFirst ()
Reference< TO, FROM > const * getFirst () const
Reference< TO, FROM > * getLast ()
Reference< TO, FROM > const * getLast () const
iterator begin ()
iterator end ()
iterator rbegin ()
iterator rend ()
const_iterator begin () const
const_iterator end () const
void clearReferences ()
Public Member Functions inherited from LinkedListHead
LinkedListHead ()
bool isEmpty () const
LinkedListElement * getFirst ()
LinkedListElement const * getFirst () const
LinkedListElement * getLast ()
LinkedListElement const * getLast () const
void insertFirst (LinkedListElement *pElem)
void insertLast (LinkedListElement *pElem)
uint32 getSize () const
void incSize ()
void decSize ()
Detailed Description
template<class TO, class FROM>
class RefManager< TO, FROM >
Definition at line 28 of file RefManager.h.
Member Typedef Documentation
const_iterator
template<class TO , class FROM > typedef LinkedListHead::Iterator<Reference<TO, FROM> const > RefManager< TO, FROM >::const_iterator
Definition at line 33 of file RefManager.h.
iterator
template<class TO , class FROM > typedef LinkedListHead::Iterator<Reference<TO, FROM> > RefManager< TO, FROM >::iterator
Definition at line 32 of file RefManager.h.
Constructor & Destructor Documentation
RefManager()
template<class TO , class FROM > RefManager< TO, FROM >::RefManager () inline
Definition at line 34 of file RefManager.h.
~RefManager()
template<class TO , class FROM > virtual RefManager< TO, FROM >::~RefManager () inline virtual
Definition at line 35 of file RefManager.h.
References RefManager< TO, FROM >::clearReferences().
Member Function Documentation
begin() [1/2]
template<class TO , class FROM > iterator RefManager< TO, FROM >::begin () inline
Definition at line 42 of file RefManager.h.
References RefManager< TO, FROM >::getFirst().
Referenced by CharmInfo::ProcessUnattackableTargets().
begin() [2/2]
template<class TO , class FROM > const_iterator RefManager< TO, FROM >::begin () const inline
Definition at line 46 of file RefManager.h.
References RefManager< TO, FROM >::getFirst().
clearReferences()
template<class TO , class FROM > void RefManager< TO, FROM >::clearReferences () inline
Definition at line 49 of file RefManager.h.
References LinkedListElement::delink(), and RefManager< TO, FROM >::getFirst().
Referenced by SetGameMasterOnHelper::operator()(), SetGameMasterOffHelper::operator()(), Unit::RemoveFromWorld(), and RefManager< TO, FROM >::~RefManager().
end() [1/2]
template<class TO , class FROM > iterator RefManager< TO, FROM >::end () inline
Definition at line 43 of file RefManager.h.
Referenced by CharmInfo::ProcessUnattackableTargets().
end() [2/2]
template<class TO , class FROM > const_iterator RefManager< TO, FROM >::end () const inline
Definition at line 47 of file RefManager.h.
getFirst() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* RefManager< TO, FROM >::getFirst () inline
Definition at line 37 of file RefManager.h.
References LinkedListHead::getFirst().
Referenced by RefManager< TO, FROM >::begin(), RefManager< TO, FROM >::clearReferences(), HostileRefManager::getFirst(), and MapRefManager::getFirst().
getFirst() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* RefManager< TO, FROM >::getFirst () const inline
Definition at line 38 of file RefManager.h.
References LinkedListHead::getFirst().
getLast() [1/2]
template<class TO , class FROM > Reference<TO, FROM>* RefManager< TO, FROM >::getLast () inline
Definition at line 39 of file RefManager.h.
References LinkedListHead::getLast().
Referenced by MapRefManager::getLast(), and RefManager< TO, FROM >::rbegin().
getLast() [2/2]
template<class TO , class FROM > Reference<TO, FROM> const* RefManager< TO, FROM >::getLast () const inline
Definition at line 40 of file RefManager.h.
References LinkedListHead::getLast().
rbegin()
template<class TO , class FROM > iterator RefManager< TO, FROM >::rbegin () inline
Definition at line 44 of file RefManager.h.
References RefManager< TO, FROM >::getLast().
rend()
template<class TO , class FROM > iterator RefManager< TO, FROM >::rend () inline
Definition at line 45 of file RefManager.h.
The documentation for this class was generated from the following file:
RefManager.h