CMaNGOS_WoTLK: AbstractRandomMovementGenerator Class Reference
AbstractRandomMovementGenerator Class Reference
#include <RandomMovementGenerator.h>
Public Member Functions
AbstractRandomMovementGenerator (uint32 stateActive, uint32 stateMotion, uint32 delayMin, uint32 delayMax, uint32 movesMax=1)
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
void Reset (Unit &owner) override
bool Update (Unit &owner, const uint32 &diff) override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual MovementGeneratorType GetMovementGeneratorType () const =0
virtual Unit * GetCurrentTarget () const
virtual void UnitSpeedChanged ()
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual int32 _setLocation (Unit &owner)
Protected Attributes
float i_x
float i_y
float i_z
float i_radius
float i_verticalZ
float i_pathLength
bool i_walk
std::unique_ptr< PathFinder > m_pathFinder
ShortTimeTracker i_nextMoveTimer
uint32 i_nextMoveCount
uint32 i_nextMoveCountMax
uint32 i_nextMoveDelayMin
uint32 i_nextMoveDelayMax
uint32 i_stateActive
uint32 i_stateMotion
Detailed Description
Definition at line 27 of file RandomMovementGenerator.h.
Constructor & Destructor Documentation
AbstractRandomMovementGenerator()
AbstractRandomMovementGenerator::AbstractRandomMovementGenerator (uint32 stateActive, uint32 stateMotion, uint32 delayMin, uint32 delayMax, uint32 movesMax = 1) inline explicit
Definition at line 30 of file RandomMovementGenerator.h.
Member Function Documentation
_setLocation()
int32 AbstractRandomMovementGenerator::_setLocation (Unit & owner) protected virtual
Reimplemented in FleeingMovementGenerator.
Definition at line 119 of file RandomMovementGenerator.cpp.
References Unit::addUnitState(), Unit::GetHealthPercent(), i_pathLength, i_radius, i_stateMotion, i_walk, i_x, i_y, i_z, Unit::IsSlowedInCombat(), Movement::MoveSplineInit::Launch(), m_pathFinder, Movement::MoveSplineInit::MovebyPath(), PATHFIND_NOPATH, Movement::MoveSplineInit::SetCombatSlowed(), and Movement::MoveSplineInit::SetWalk().
Referenced by FleeingMovementGenerator::_setLocation(), and Update().
Finalize()
void AbstractRandomMovementGenerator::Finalize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PanicMovementGenerator, and WanderMovementGenerator.
Definition at line 51 of file RandomMovementGenerator.cpp.
References Unit::clearUnitState(), Movement::MoveSpline::Finalized(), Unit::GetClientControlling(), i_stateActive, i_stateMotion, Unit::InterruptMoving(), Unit::IsClientControlled(), Unit::movespline, and Unit::StopMoving().
Referenced by WanderMovementGenerator::Finalize(), and PanicMovementGenerator::Finalize().
Initialize()
void AbstractRandomMovementGenerator::Initialize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PanicMovementGenerator.
Definition at line 25 of file RandomMovementGenerator.cpp.
References Unit::addUnitState(), Unit::AI(), Movement::MoveSpline::Finalized(), Unit::GetClientControlling(), Unit::GetVictim(), i_stateActive, Unit::InterruptMoving(), Unit::IsClientControlled(), m_pathFinder, Unit::MeleeAttackStop(), Unit::movespline, Unit::SetTarget(), and Unit::StopMoving().
Referenced by PanicMovementGenerator::Initialize(), and Reset().
Interrupt()
void AbstractRandomMovementGenerator::Interrupt (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in PanicMovementGenerator, and WanderMovementGenerator.
Definition at line 69 of file RandomMovementGenerator.cpp.
References Unit::clearUnitState(), i_stateMotion, and Unit::InterruptMoving().
Referenced by WanderMovementGenerator::Interrupt(), and PanicMovementGenerator::Interrupt().
Reset()
void AbstractRandomMovementGenerator::Reset (Unit & owner) override virtual
Implements MovementGenerator.
Definition at line 76 of file RandomMovementGenerator.cpp.
References i_nextMoveTimer, Initialize(), and ShortTimeTracker::Reset().
Update()
bool AbstractRandomMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Implements MovementGenerator.
Reimplemented in PanicMovementGenerator, and TimedWanderMovementGenerator.
Definition at line 83 of file RandomMovementGenerator.cpp.
References _setLocation(), Unit::clearUnitState(), Movement::MoveSpline::Finalized(), Object::HasFlag(), Unit::hasUnitState(), i_nextMoveCount, i_nextMoveCountMax, i_nextMoveDelayMax, i_nextMoveDelayMin, i_nextMoveTimer, i_stateActive, i_stateMotion, Unit::IsAlive(), Unit::movespline, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_STAT_NO_FREE_MOVE, ShortTimeTracker::Update(), and urand().
Referenced by TimedWanderMovementGenerator::Update(), and PanicMovementGenerator::Update().
Field Documentation
i_nextMoveCount
uint32 AbstractRandomMovementGenerator::i_nextMoveCount protected
Definition at line 55 of file RandomMovementGenerator.h.
Referenced by Update().
i_nextMoveCountMax
uint32 AbstractRandomMovementGenerator::i_nextMoveCountMax protected
Definition at line 55 of file RandomMovementGenerator.h.
Referenced by Update().
i_nextMoveDelayMax
uint32 AbstractRandomMovementGenerator::i_nextMoveDelayMax protected
Definition at line 56 of file RandomMovementGenerator.h.
Referenced by Update().
i_nextMoveDelayMin
uint32 AbstractRandomMovementGenerator::i_nextMoveDelayMin protected
Definition at line 56 of file RandomMovementGenerator.h.
Referenced by Update().
i_nextMoveTimer
ShortTimeTracker AbstractRandomMovementGenerator::i_nextMoveTimer protected
Definition at line 54 of file RandomMovementGenerator.h.
Referenced by Reset(), and Update().
i_pathLength
float AbstractRandomMovementGenerator::i_pathLength protected
Definition at line 50 of file RandomMovementGenerator.h.
Referenced by _setLocation(), and FleeingMovementGenerator::FleeingMovementGenerator().
i_radius
float AbstractRandomMovementGenerator::i_radius protected
Definition at line 48 of file RandomMovementGenerator.h.
Referenced by _setLocation(), FleeingMovementGenerator::_setLocation(), ConfusedMovementGenerator::ConfusedMovementGenerator(), and WanderMovementGenerator::WanderMovementGenerator().
i_stateActive
uint32 AbstractRandomMovementGenerator::i_stateActive protected
Definition at line 57 of file RandomMovementGenerator.h.
Referenced by Finalize(), Initialize(), and Update().
i_stateMotion
uint32 AbstractRandomMovementGenerator::i_stateMotion protected
Definition at line 57 of file RandomMovementGenerator.h.
Referenced by _setLocation(), Finalize(), Interrupt(), and Update().
i_verticalZ
float AbstractRandomMovementGenerator::i_verticalZ protected
Definition at line 49 of file RandomMovementGenerator.h.
Referenced by WanderMovementGenerator::WanderMovementGenerator().
i_walk
bool AbstractRandomMovementGenerator::i_walk protected
Definition at line 51 of file RandomMovementGenerator.h.
Referenced by _setLocation(), and FleeingMovementGenerator::FleeingMovementGenerator().
i_x
float AbstractRandomMovementGenerator::i_x protected
Definition at line 47 of file RandomMovementGenerator.h.
Referenced by _setLocation(), FleeingMovementGenerator::_setLocation(), ConfusedMovementGenerator::ConfusedMovementGenerator(), FleeingMovementGenerator::FleeingMovementGenerator(), and WanderMovementGenerator::WanderMovementGenerator().
i_y
float AbstractRandomMovementGenerator::i_y protected
Definition at line 47 of file RandomMovementGenerator.h.
Referenced by _setLocation(), FleeingMovementGenerator::_setLocation(), ConfusedMovementGenerator::ConfusedMovementGenerator(), FleeingMovementGenerator::FleeingMovementGenerator(), and WanderMovementGenerator::WanderMovementGenerator().
i_z
float AbstractRandomMovementGenerator::i_z protected
Definition at line 47 of file RandomMovementGenerator.h.
Referenced by _setLocation(), FleeingMovementGenerator::_setLocation(), ConfusedMovementGenerator::ConfusedMovementGenerator(), FleeingMovementGenerator::FleeingMovementGenerator(), and WanderMovementGenerator::WanderMovementGenerator().
m_pathFinder
std::unique_ptr<PathFinder> AbstractRandomMovementGenerator::m_pathFinder protected
Definition at line 53 of file RandomMovementGenerator.h.
Referenced by _setLocation(), and Initialize().
The documentation for this class was generated from the following files:
RandomMovementGenerator.h
RandomMovementGenerator.cpp