CMaNGOS_WoTLK: PlayerbotPaladinAI Class Reference
PlayerbotPaladinAI Class Reference
#include <PlayerbotPaladinAI.h>
Public Member Functions
PlayerbotPaladinAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotPaladinAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
bool CanPull () override
bool Pull () override
void DoNonCombatActions () override
bool CastHoTOnTank ()
Data Fields
uint32 RETRIBUTION_AURA
uint32 SEAL_OF_COMMAND
uint32 JUDGEMENT_OF_LIGHT
uint32 JUDGEMENT_OF_WISDOM
uint32 GREATER_BLESSING_OF_WISDOM
uint32 GREATER_BLESSING_OF_MIGHT
uint32 BLESSING_OF_WISDOM
uint32 BLESSING_OF_MIGHT
uint32 HAMMER_OF_JUSTICE
uint32 RIGHTEOUS_FURY
uint32 CRUSADER_AURA
uint32 CRUSADER_STRIKE
uint32 AVENGING_WRATH
uint32 DIVINE_STORM
uint32 JUDGEMENT_OF_JUSTICE
uint32 ART_OF_WAR
uint32 FLASH_OF_LIGHT
uint32 HOLY_LIGHT
uint32 DIVINE_SHIELD
uint32 HAMMER_OF_WRATH
uint32 CONSECRATION
uint32 CONCENTRATION_AURA
uint32 DIVINE_FAVOR
uint32 SACRED_SHIELD
uint32 HOLY_SHOCK
uint32 HOLY_WRATH
uint32 LAY_ON_HANDS
uint32 EXORCISM
uint32 REDEMPTION
uint32 DIVINE_PLEA
uint32 SEAL_OF_CORRUPTION
uint32 SEAL_OF_JUSTICE
uint32 SEAL_OF_LIGHT
uint32 SEAL_OF_RIGHTEOUSNESS
uint32 SEAL_OF_VENGEANCE
uint32 SEAL_OF_WISDOM
uint32 PURIFY
uint32 CLEANSE
uint32 GREATER_BLESSING_OF_KINGS
uint32 BLESSING_OF_KINGS
uint32 HAND_OF_PROTECTION
uint32 SHADOW_RESISTANCE_AURA
uint32 DEVOTION_AURA
uint32 FIRE_RESISTANCE_AURA
uint32 FROST_RESISTANCE_AURA
uint32 DEFENSIVE_STANCE
uint32 BERSERKER_STANCE
uint32 BATTLE_STANCE
uint32 DIVINE_SACRIFICE
uint32 DIVINE_PROTECTION
uint32 DIVINE_INTERVENTION
uint32 HOLY_SHIELD
uint32 AVENGERS_SHIELD
uint32 RIGHTEOUS_DEFENSE
uint32 BLESSING_OF_SANCTUARY
uint32 GREATER_BLESSING_OF_SANCTUARY
uint32 HAND_OF_SACRIFICE
uint32 SHIELD_OF_RIGHTEOUSNESS
uint32 HAND_OF_RECKONING
uint32 HAMMER_OF_THE_RIGHTEOUS
uint32 FORBEARANCE
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 EVERY_MAN_FOR_HIMSELF
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 PRAYER_OF_SHADOW_PROTECTION
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns HealPlayer (Player *target) override
CombatManeuverReturns ResurrectPlayer (Player *target) override
CombatManeuverReturns DispelPlayer (Player *target=nullptr)
void CheckAuras ()
bool CheckSeals ()
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual uint32 Neutralize (uint8 creatureType)
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Static Private Member Functions
static bool BuffHelper (PlayerbotAI *ai, uint32 spellId, Unit *target)
BuffHelper BuffHelper is a static function, takes an AI, spellId (ignored for paladin) and a target and attempts to buff them as well as their pets as best as possible.
Private Attributes
uint32 SpellSequence
uint32 CombatCounter
uint32 HealCounter
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 83 of file PlayerbotPaladinAI.h.
Constructor & Destructor Documentation
PlayerbotPaladinAI()
PlayerbotPaladinAI::PlayerbotPaladinAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotPaladinAI.cpp.
References ARCANE_TORRENT, ARCANE_TORRENT_MANA_CLASSES, ART_OF_WAR, ART_OF_WAR_1, AVENGERS_SHIELD, AVENGERS_SHIELD_1, AVENGING_WRATH, AVENGING_WRATH_1, BATTLE_STANCE, BERSERKER_STANCE, BLESSING_OF_KINGS, BLESSING_OF_KINGS_1, BLESSING_OF_MIGHT, BLESSING_OF_MIGHT_1, BLESSING_OF_SANCTUARY, BLESSING_OF_SANCTUARY_1, BLESSING_OF_WISDOM, BLESSING_OF_WISDOM_1, CLEANSE, CLEANSE_1, CONCENTRATION_AURA, CONCENTRATION_AURA_1, CONSECRATION, CONSECRATION_1, CRUSADER_AURA, CRUSADER_AURA_1, CRUSADER_STRIKE, CRUSADER_STRIKE_1, DEFENSIVE_STANCE, DEVOTION_AURA, DEVOTION_AURA_1, DIVINE_FAVOR, DIVINE_FAVOR_1, DIVINE_INTERVENTION, DIVINE_INTERVENTION_1, DIVINE_PLEA, DIVINE_PLEA_1, DIVINE_PROTECTION, DIVINE_PROTECTION_1, DIVINE_SACRIFICE, DIVINE_SACRIFICE_1, DIVINE_SHIELD, DIVINE_SHIELD_1, DIVINE_STORM, DIVINE_STORM_1, EVERY_MAN_FOR_HIMSELF, EVERY_MAN_FOR_HIMSELF_ALL, EXORCISM, EXORCISM_1, FIRE_RESISTANCE_AURA, FIRE_RESISTANCE_AURA_1, FLASH_OF_LIGHT, FLASH_OF_LIGHT_1, FORBEARANCE, FROST_RESISTANCE_AURA, FROST_RESISTANCE_AURA_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_PALADIN, GREATER_BLESSING_OF_KINGS, GREATER_BLESSING_OF_KINGS_1, GREATER_BLESSING_OF_MIGHT, GREATER_BLESSING_OF_MIGHT_1, GREATER_BLESSING_OF_SANCTUARY, GREATER_BLESSING_OF_SANCTUARY_1, GREATER_BLESSING_OF_WISDOM, GREATER_BLESSING_OF_WISDOM_1, HAMMER_OF_JUSTICE, HAMMER_OF_JUSTICE_1, HAMMER_OF_THE_RIGHTEOUS, HAMMER_OF_THE_RIGHTEOUS_1, HAMMER_OF_WRATH, HAMMER_OF_WRATH_1, HAND_OF_PROTECTION, HAND_OF_PROTECTION_1, HAND_OF_RECKONING, HAND_OF_RECKONING_1, HAND_OF_SACRIFICE, HAND_OF_SACRIFICE_1, HOLY_LIGHT, HOLY_LIGHT_1, HOLY_SHIELD, HOLY_SHIELD_1, HOLY_SHOCK, HOLY_SHOCK_1, HOLY_WRATH, HOLY_WRATH_1, PlayerbotAI::initSpell(), JUDGEMENT_OF_JUSTICE, JUDGEMENT_OF_JUSTICE_1, JUDGEMENT_OF_LIGHT, JUDGEMENT_OF_LIGHT_1, JUDGEMENT_OF_WISDOM, JUDGEMENT_OF_WISDOM_1, LAY_ON_HANDS, LAY_ON_HANDS_1, PlayerbotClassAI::m_ai, PURIFY, PURIFY_1, PlayerbotClassAI::RECENTLY_BANDAGED, REDEMPTION, REDEMPTION_1, RETRIBUTION_AURA, RETRIBUTION_AURA_1, RIGHTEOUS_DEFENSE, RIGHTEOUS_DEFENSE_1, RIGHTEOUS_FURY, RIGHTEOUS_FURY_1, SACRED_SHIELD, SACRED_SHIELD_1, SEAL_OF_COMMAND, SEAL_OF_COMMAND_1, SEAL_OF_CORRUPTION, SEAL_OF_CORRUPTION_1, SEAL_OF_JUSTICE, SEAL_OF_JUSTICE_1, SEAL_OF_LIGHT, SEAL_OF_LIGHT_1, SEAL_OF_RIGHTEOUSNESS, SEAL_OF_RIGHTEOUSNESS_1, SEAL_OF_VENGEANCE, SEAL_OF_VENGEANCE_1, SEAL_OF_WISDOM, SEAL_OF_WISDOM_1, SHADOW_RESISTANCE_AURA, SHADOW_RESISTANCE_AURA_1, SHIELD_OF_RIGHTEOUSNESS, SHIELD_OF_RIGHTEOUSNESS_1, STONEFORM, and STONEFORM_ALL.
~PlayerbotPaladinAI()
PlayerbotPaladinAI::~PlayerbotPaladinAI () virtual
Definition at line 102 of file PlayerbotPaladinAI.cpp.
Member Function Documentation
BuffHelper()
bool PlayerbotPaladinAI::BuffHelper (PlayerbotAI * ai, uint32 spellId, Unit * target) static private
BuffHelper BuffHelper is a static function, takes an AI, spellId (ignored for paladin) and a target and attempts to buff them as well as their pets as best as possible.
Return bool - returns true if a buff took place.
Hunter pet if (pet && ai->CanReceiveSpecificSpell(SPELL_BLESSING, pet) && !pet->HasAuraType(SPELL_AURA_MOD_UNATTACKABLE)) { petSpellId = c->BLESSING_OF_MIGHT; if (!petSpellId) { petSpellId = c->BLESSING_OF_KINGS; if (!petSpellId) petSpellId = c->BLESSING_OF_SANCTUARY; } }
Definition at line 563 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::Buff(), CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, Unit::getClass(), PlayerbotAI::GetClassAI(), Unit::GetPet(), Unit::GetPowerType(), Unit::HasAuraType(), PlayerbotAI::HasSpellReagents(), POWER_MANA, SPELL_AURA_MOD_UNATTACKABLE, and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
CanPull()
bool PlayerbotPaladinAI::CanPull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 684 of file PlayerbotPaladinAI.cpp.
References EXORCISM, HAND_OF_RECKONING, WorldObject::IsSpellReady(), and PlayerbotClassAI::m_bot.
CastHoTOnTank()
bool PlayerbotPaladinAI::CastHoTOnTank ()
Definition at line 701 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::IsHealer(), and PlayerbotClassAI::m_ai.
CheckAuras()
void PlayerbotPaladinAI::CheckAuras () private
Definition at line 415 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), CONCENTRATION_AURA, DEVOTION_AURA, FIRE_RESISTANCE_AURA, FROST_RESISTANCE_AURA, PlayerbotAI::GetCombatOrder(), Player::GetGroup(), Group::GetMemberSlots(), PlayerbotClassAI::GetTargetJob(), Unit::HasAura(), JOB_MAIN_TANK, JOB_TANK, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_RESIST_FIRE, PlayerbotAI::ORDERS_RESIST_FROST, PlayerbotAI::ORDERS_RESIST_SHADOW, PALADIN_SPEC_HOLY, PALADIN_SPEC_PROTECTION, PALADIN_SPEC_RETRIBUTION, RETRIBUTION_AURA, SHADOW_RESISTANCE_AURA, and sObjectMgr.
Referenced by DoNonCombatActions().
CheckSeals()
bool PlayerbotPaladinAI::CheckSeals () private
Definition at line 480 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), EFFECT_INDEX_0, PlayerbotAI::GetCombatOrder(), Unit::HasAura(), PlayerbotAI::IsHealer(), PlayerbotAI::IsTank(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_ASSIST, PALADIN_SPEC_HOLY, PALADIN_SPEC_PROTECTION, PALADIN_SPEC_RETRIBUTION, SEAL_OF_COMMAND, SEAL_OF_RIGHTEOUSNESS, SEAL_OF_WISDOM, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DispelPlayer()
CombatManeuverReturns PlayerbotPaladinAI::DispelPlayer (Player * target = nullptr) private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 377 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), CLEANSE, DISPEL_DISEASE, DISPEL_MAGIC, DISPEL_POISON, PlayerbotClassAI::DispelPlayer(), PlayerbotClassAI::GetDispelTarget(), PlayerbotClassAI::m_ai, PURIFY, RETURN_CONTINUE, RETURN_NO_ACTION_OK, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotPaladinAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 104 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::Attack(), Unit::CanReachWithMeleeAttack(), PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCurrentTarget(), PlayerbotClassAI::GetHealTarget(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), HealPlayer(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_HEAL, PlayerbotAI::ORDERS_TANK, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, PlayerbotAI::SCENARIO_PVP_OPENWORLD, and PlayerbotAI::SetGroupIgnoreUpdateTime().
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotPaladinAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 165 of file PlayerbotPaladinAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotPaladinAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 170 of file PlayerbotPaladinAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotPaladinAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 175 of file PlayerbotPaladinAI.cpp.
References CheckSeals(), DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, RETURN_CONTINUE, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotPaladinAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 195 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, ART_OF_WAR, AVENGERS_SHIELD, AVENGING_WRATH, PlayerbotAI::CastSpell(), PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, CONSECRATION, CRUSADER_STRIKE, DispelPlayer(), DIVINE_PROTECTION, DIVINE_SHIELD, DIVINE_STORM, EFFECT_INDEX_0, EXORCISM, PlayerbotAI::FindAttacker(), PlayerbotClassAI::FindTargetAndHeal(), FORBEARANCE, PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCombatStyle(), Unit::GetHealth(), PlayerbotAI::GetHealthPercent(), Unit::GetMaxHealth(), HAMMER_OF_JUSTICE, HAMMER_OF_THE_RIGHTEOUS, HAMMER_OF_WRATH, HAND_OF_RECKONING, Unit::HasAura(), PlayerbotAI::HasDispelOrder(), HOLY_SHIELD, PlayerbotAI::In_Reach(), PlayerbotAI::IsElite(), PlayerbotAI::IsHealer(), PlayerbotAI::IsNeutralized(), WorldObject::IsSpellReady(), JUDGEMENT_OF_LIGHT, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, PlayerbotAI::ORDERS_TANK, PALADIN_SPEC_HOLY, PALADIN_SPEC_PROTECTION, PALADIN_SPEC_RETRIBUTION, RETURN_CONTINUE, RETURN_NO_ACTION_INVALIDTARGET, RETURN_NO_ACTION_OK, PlayerbotAI::SetCombatStyle(), SHIELD_OF_RIGHTEOUSNESS, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotPaladinAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 299 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), HAMMER_OF_JUSTICE, PlayerbotClassAI::m_ai, RETURN_CONTINUE, and SPELL_CAST_OK.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotPaladinAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 511 of file PlayerbotPaladinAI.cpp.
References PlayerbotClassAI::Buff(), BuffHelper(), CheckAuras(), DispelPlayer(), PlayerbotClassAI::EatDrinkBandage(), PlayerbotClassAI::GetHealTarget(), PlayerbotClassAI::GetResurrectionTarget(), Unit::HasAura(), PlayerbotAI::HasDispelOrder(), HealPlayer(), Unit::IsAlive(), PlayerbotAI::IsHealer(), PlayerbotAI::IsTank(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, Unit::RemoveAurasDueToSpell(), ResurrectPlayer(), RETURN_CONTINUE, RIGHTEOUS_FURY, and PlayerbotAI::SelfBuff().
HealPlayer()
CombatManeuverReturns PlayerbotPaladinAI::HealPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 307 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), DIVINE_FAVOR, DIVINE_PROTECTION, DIVINE_SHIELD, EFFECT_INDEX_0, FLASH_OF_LIGHT, FORBEARANCE, Unit::GetHealthPercent(), Unit::GetMotionMaster(), WorldObject::GetOrientation(), PlayerbotClassAI::GetTargetJob(), HAND_OF_PROTECTION, Unit::HasAura(), PlayerbotClassAI::HealPlayer(), HOLY_LIGHT, HOLY_SHOCK, PlayerbotAI::In_Reach(), WorldObject::IsSpellReady(), JOB_HEAL, JOB_MAIN_TANK, JOB_TANK, LAY_ON_HANDS, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MotionMaster::MoveFollow(), PlayerbotAI::MOVEMENT_STAY, RETURN_CONTINUE, RETURN_NO_ACTION_OK, RETURN_NO_ACTION_UNKNOWN, and SPELL_CAST_OK.
Referenced by DoFirstCombatManeuver(), and DoNonCombatActions().
Pull()
bool PlayerbotPaladinAI::Pull () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 693 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), EXORCISM, HAND_OF_RECKONING, PlayerbotClassAI::m_ai, and SPELL_CAST_OK.
ResurrectPlayer()
CombatManeuverReturns PlayerbotPaladinAI::ResurrectPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 358 of file PlayerbotPaladinAI.cpp.
References PlayerbotAI::CastSpell(), WorldObject::GetName(), PlayerbotAI::In_Reach(), PlayerbotAI::IsInCombat(), LANG_UNIVERSAL, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, REDEMPTION, PlayerbotClassAI::ResurrectPlayer(), RETURN_CONTINUE, RETURN_NO_ACTION_ERROR, RETURN_NO_ACTION_OK, Player::Say(), and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
Field Documentation
ARCANE_TORRENT
uint32 PlayerbotPaladinAI::ARCANE_TORRENT
Definition at line 193 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
ART_OF_WAR
uint32 PlayerbotPaladinAI::ART_OF_WAR
Definition at line 139 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
AVENGERS_SHIELD
uint32 PlayerbotPaladinAI::AVENGERS_SHIELD
Definition at line 180 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
AVENGING_WRATH
uint32 PlayerbotPaladinAI::AVENGING_WRATH
Definition at line 136 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
BATTLE_STANCE
uint32 PlayerbotPaladinAI::BATTLE_STANCE
Definition at line 175 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BERSERKER_STANCE
uint32 PlayerbotPaladinAI::BERSERKER_STANCE
Definition at line 174 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BERSERKING
uint32 PlayerbotPaladinAI::BERSERKING
Definition at line 201 of file PlayerbotPaladinAI.h.
BLESSING_OF_KINGS
uint32 PlayerbotPaladinAI::BLESSING_OF_KINGS
Definition at line 167 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BLESSING_OF_MIGHT
uint32 PlayerbotPaladinAI::BLESSING_OF_MIGHT
Definition at line 131 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BLESSING_OF_SANCTUARY
uint32 PlayerbotPaladinAI::BLESSING_OF_SANCTUARY
Definition at line 182 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BLESSING_OF_WISDOM
uint32 PlayerbotPaladinAI::BLESSING_OF_WISDOM
Definition at line 130 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
BLOOD_FURY
uint32 PlayerbotPaladinAI::BLOOD_FURY
Definition at line 199 of file PlayerbotPaladinAI.h.
CLEANSE
uint32 PlayerbotPaladinAI::CLEANSE
Definition at line 163 of file PlayerbotPaladinAI.h.
Referenced by DispelPlayer(), and PlayerbotPaladinAI().
CombatCounter
uint32 PlayerbotPaladinAI::CombatCounter private
Definition at line 208 of file PlayerbotPaladinAI.h.
CONCENTRATION_AURA
uint32 PlayerbotPaladinAI::CONCENTRATION_AURA
Definition at line 147 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
CONSECRATION
uint32 PlayerbotPaladinAI::CONSECRATION
Definition at line 146 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
CRUSADER_AURA
uint32 PlayerbotPaladinAI::CRUSADER_AURA
Definition at line 134 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
CRUSADER_STRIKE
uint32 PlayerbotPaladinAI::CRUSADER_STRIKE
Definition at line 135 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
DEFENSIVE_STANCE
uint32 PlayerbotPaladinAI::DEFENSIVE_STANCE
Definition at line 173 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
DEVOTION_AURA
uint32 PlayerbotPaladinAI::DEVOTION_AURA
Definition at line 170 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
DIVINE_FAVOR
uint32 PlayerbotPaladinAI::DIVINE_FAVOR
Definition at line 148 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
DIVINE_INTERVENTION
uint32 PlayerbotPaladinAI::DIVINE_INTERVENTION
Definition at line 178 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
DIVINE_PLEA
uint32 PlayerbotPaladinAI::DIVINE_PLEA
Definition at line 155 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
DIVINE_PROTECTION
uint32 PlayerbotPaladinAI::DIVINE_PROTECTION
Definition at line 177 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotPaladinAI().
DIVINE_SACRIFICE
uint32 PlayerbotPaladinAI::DIVINE_SACRIFICE
Definition at line 176 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
DIVINE_SHIELD
uint32 PlayerbotPaladinAI::DIVINE_SHIELD
Definition at line 144 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotPaladinAI().
DIVINE_STORM
uint32 PlayerbotPaladinAI::DIVINE_STORM
Definition at line 137 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
ESCAPE_ARTIST
uint32 PlayerbotPaladinAI::ESCAPE_ARTIST
Definition at line 196 of file PlayerbotPaladinAI.h.
EVERY_MAN_FOR_HIMSELF
uint32 PlayerbotPaladinAI::EVERY_MAN_FOR_HIMSELF
Definition at line 197 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
EXORCISM
uint32 PlayerbotPaladinAI::EXORCISM
Definition at line 153 of file PlayerbotPaladinAI.h.
Referenced by CanPull(), DoNextCombatManeuverPVE(), PlayerbotPaladinAI(), and Pull().
FIRE_RESISTANCE_AURA
uint32 PlayerbotPaladinAI::FIRE_RESISTANCE_AURA
Definition at line 171 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
FLASH_OF_LIGHT
uint32 PlayerbotPaladinAI::FLASH_OF_LIGHT
Definition at line 142 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
FORBEARANCE
uint32 PlayerbotPaladinAI::FORBEARANCE
Definition at line 190 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), HealPlayer(), and PlayerbotPaladinAI().
FROST_RESISTANCE_AURA
uint32 PlayerbotPaladinAI::FROST_RESISTANCE_AURA
Definition at line 172 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotPaladinAI::GIFT_OF_THE_NAARU
Definition at line 194 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
GREATER_BLESSING_OF_KINGS
uint32 PlayerbotPaladinAI::GREATER_BLESSING_OF_KINGS
Definition at line 166 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
GREATER_BLESSING_OF_MIGHT
uint32 PlayerbotPaladinAI::GREATER_BLESSING_OF_MIGHT
Definition at line 129 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
GREATER_BLESSING_OF_SANCTUARY
uint32 PlayerbotPaladinAI::GREATER_BLESSING_OF_SANCTUARY
Definition at line 183 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
GREATER_BLESSING_OF_WISDOM
uint32 PlayerbotPaladinAI::GREATER_BLESSING_OF_WISDOM
Definition at line 128 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
HAMMER_OF_JUSTICE
uint32 PlayerbotPaladinAI::HAMMER_OF_JUSTICE
Definition at line 132 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotPaladinAI().
HAMMER_OF_THE_RIGHTEOUS
uint32 PlayerbotPaladinAI::HAMMER_OF_THE_RIGHTEOUS
Definition at line 187 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
HAMMER_OF_WRATH
uint32 PlayerbotPaladinAI::HAMMER_OF_WRATH
Definition at line 145 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
HAND_OF_PROTECTION
uint32 PlayerbotPaladinAI::HAND_OF_PROTECTION
Definition at line 168 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
HAND_OF_RECKONING
uint32 PlayerbotPaladinAI::HAND_OF_RECKONING
Definition at line 186 of file PlayerbotPaladinAI.h.
Referenced by CanPull(), DoNextCombatManeuverPVE(), PlayerbotPaladinAI(), and Pull().
HAND_OF_SACRIFICE
uint32 PlayerbotPaladinAI::HAND_OF_SACRIFICE
Definition at line 184 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
HealCounter
uint32 PlayerbotPaladinAI::HealCounter private
Definition at line 208 of file PlayerbotPaladinAI.h.
HOLY_LIGHT
uint32 PlayerbotPaladinAI::HOLY_LIGHT
Definition at line 143 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
HOLY_SHIELD
uint32 PlayerbotPaladinAI::HOLY_SHIELD
Definition at line 179 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
HOLY_SHOCK
uint32 PlayerbotPaladinAI::HOLY_SHOCK
Definition at line 150 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
HOLY_WRATH
uint32 PlayerbotPaladinAI::HOLY_WRATH
Definition at line 151 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
JUDGEMENT_OF_JUSTICE
uint32 PlayerbotPaladinAI::JUDGEMENT_OF_JUSTICE
Definition at line 138 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
JUDGEMENT_OF_LIGHT
uint32 PlayerbotPaladinAI::JUDGEMENT_OF_LIGHT
Definition at line 126 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
JUDGEMENT_OF_WISDOM
uint32 PlayerbotPaladinAI::JUDGEMENT_OF_WISDOM
Definition at line 127 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
LAY_ON_HANDS
uint32 PlayerbotPaladinAI::LAY_ON_HANDS
Definition at line 152 of file PlayerbotPaladinAI.h.
Referenced by HealPlayer(), and PlayerbotPaladinAI().
PRAYER_OF_SHADOW_PROTECTION
uint32 PlayerbotPaladinAI::PRAYER_OF_SHADOW_PROTECTION
Definition at line 205 of file PlayerbotPaladinAI.h.
PURIFY
uint32 PlayerbotPaladinAI::PURIFY
Definition at line 162 of file PlayerbotPaladinAI.h.
Referenced by DispelPlayer(), and PlayerbotPaladinAI().
REDEMPTION
uint32 PlayerbotPaladinAI::REDEMPTION
Definition at line 154 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI(), and ResurrectPlayer().
RETRIBUTION_AURA
uint32 PlayerbotPaladinAI::RETRIBUTION_AURA
Definition at line 124 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
RIGHTEOUS_DEFENSE
uint32 PlayerbotPaladinAI::RIGHTEOUS_DEFENSE
Definition at line 181 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
RIGHTEOUS_FURY
uint32 PlayerbotPaladinAI::RIGHTEOUS_FURY
Definition at line 133 of file PlayerbotPaladinAI.h.
Referenced by DoNonCombatActions(), and PlayerbotPaladinAI().
SACRED_SHIELD
uint32 PlayerbotPaladinAI::SACRED_SHIELD
Definition at line 149 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
SEAL_OF_COMMAND
uint32 PlayerbotPaladinAI::SEAL_OF_COMMAND
Definition at line 125 of file PlayerbotPaladinAI.h.
Referenced by CheckSeals(), and PlayerbotPaladinAI().
SEAL_OF_CORRUPTION
uint32 PlayerbotPaladinAI::SEAL_OF_CORRUPTION
Definition at line 156 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
SEAL_OF_JUSTICE
uint32 PlayerbotPaladinAI::SEAL_OF_JUSTICE
Definition at line 157 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
SEAL_OF_LIGHT
uint32 PlayerbotPaladinAI::SEAL_OF_LIGHT
Definition at line 158 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
SEAL_OF_RIGHTEOUSNESS
uint32 PlayerbotPaladinAI::SEAL_OF_RIGHTEOUSNESS
Definition at line 159 of file PlayerbotPaladinAI.h.
Referenced by CheckSeals(), and PlayerbotPaladinAI().
SEAL_OF_VENGEANCE
uint32 PlayerbotPaladinAI::SEAL_OF_VENGEANCE
Definition at line 160 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
SEAL_OF_WISDOM
uint32 PlayerbotPaladinAI::SEAL_OF_WISDOM
Definition at line 161 of file PlayerbotPaladinAI.h.
Referenced by CheckSeals(), and PlayerbotPaladinAI().
SHADOW_RESISTANCE_AURA
uint32 PlayerbotPaladinAI::SHADOW_RESISTANCE_AURA
Definition at line 169 of file PlayerbotPaladinAI.h.
Referenced by CheckAuras(), and PlayerbotPaladinAI().
SHADOWMELD
uint32 PlayerbotPaladinAI::SHADOWMELD
Definition at line 198 of file PlayerbotPaladinAI.h.
SHIELD_OF_RIGHTEOUSNESS
uint32 PlayerbotPaladinAI::SHIELD_OF_RIGHTEOUSNESS
Definition at line 185 of file PlayerbotPaladinAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotPaladinAI().
SpellSequence
uint32 PlayerbotPaladinAI::SpellSequence private
Definition at line 208 of file PlayerbotPaladinAI.h.
STONEFORM
uint32 PlayerbotPaladinAI::STONEFORM
Definition at line 195 of file PlayerbotPaladinAI.h.
Referenced by PlayerbotPaladinAI().
WAR_STOMP
uint32 PlayerbotPaladinAI::WAR_STOMP
Definition at line 200 of file PlayerbotPaladinAI.h.
WILL_OF_THE_FORSAKEN
uint32 PlayerbotPaladinAI::WILL_OF_THE_FORSAKEN
Definition at line 202 of file PlayerbotPaladinAI.h.
The documentation for this class was generated from the following files:
PlayerbotPaladinAI.h
PlayerbotPaladinAI.cpp