CMaNGOS_WoTLK: Transport Class Reference
Transport Class Reference
#include <Transports.h>
Public Member Functions
Transport (TransportTemplate const &transportTemplate)
bool Create (uint32 guidlow, uint32 mapid, float x, float y, float z, float ang, uint8 animprogress, uint16 dynamicHighValue)
void Update (const uint32 diff) override
uint32 GetPeriod () const
void SetPeriod (uint32 period)
KeyFrameVec const & GetKeyFrames () const
void SpawnPassengers () override
void DespawnPassengers () override
Public Member Functions inherited from GenericTransport
GenericTransport ()
bool AddPassenger (WorldObject *passenger, bool adjustCoords=true)
bool RemovePassenger (WorldObject *passenger)
bool AddPetToTransport (Unit *passenger, Pet *pet)
void UpdatePosition (float x, float y, float z, float o)
void UpdatePassengerPosition (WorldObject *object)
PassengerSet & GetPassengers ()
void CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const
This method transforms supplied transport offsets into global coordinates.
void CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const
This method transforms supplied global coordinates into local offsets.
void CalculatePassengerOrientation (float &o) const
uint32 GetPathProgress () const
void SetGoState (GOState state) override
Public Member Functions inherited from GameObject
GameObject ()
~GameObject ()
void AddToWorld () override
void RemoveFromWorld () override
virtual bool Create (uint32 dbGuid, uint32 guidlow, uint32 name_id, Map *map, uint32 phaseMask, float x, float y, float z, float ang, const QuaternionData &rotation=QuaternionData(), uint8 animprogress=GO_ANIMPROGRESS_DEFAULT, GOState go_state=GO_STATE_READY)
void Heartbeat () override
GameObjectInfo const * GetGOInfo () const
GameObjectTemplateAddon const * GetTemplateAddon () const
bool IsTransport () const
bool IsMoTransport () const
bool IsDynTransport () const
bool HasStaticDBSpawnData () const
void SetLocalRotationAngles (float z_rot, float y_rot, float x_rot)
void SetLocalRotation (float qx, float qy, float qz, float qw)
void SetTransportPathRotation (const QuaternionData &rotation)
int64 GetPackedLocalRotation () const
QuaternionData GetWorldRotation () const
QuaternionData const GetLocalRotation () const
const char * GetNameForLocaleIdx (int32 loc_idx) const override
void SaveToDB () const
void SaveToDB (uint32 mapid, uint8 spawnMask, uint32 phaseMask) const
bool LoadFromDB (uint32 dbGuid, Map *map, uint32 newGuid, uint32 forcedEntry, GenericTransport *transport=nullptr)
void DeleteFromDB () const
ObjectGuid const & GetOwnerGuid () const override
void SetOwnerGuid (ObjectGuid guid) override
ObjectGuid const GetSpawnerGuid () const
void SetSpawnerGuid (ObjectGuid guid)
Unit * GetOwner () const
WorldObject * GetSpawner () const
void SetSpellId (uint32 id)
uint32 GetSpellId () const
void ForcedDespawn (uint32 timeMSToDespawn=0)
time_t GetRespawnTime () const
time_t GetRespawnTimeEx () const
void SetRespawnTime (time_t respawn)
void Respawn ()
bool IsSpawned () const
bool IsSpawnedByDefault () const
uint32 GetRespawnDelay () const
void SetRespawnDelay (uint32 delay, bool once=false)
void SetForcedDespawn ()
void Refresh ()
void Delete ()
GameobjectTypes GetGoType () const
void SetGoType (GameobjectTypes type)
GOState GetGoState () const
uint8 GetGoArtKit () const
void SetGoArtKit (uint8 artkit)
uint8 GetGoAnimProgress () const
void SetGoAnimProgress (uint8 animprogress)
uint32 GetDisplayId () const
void SetDisplayId (uint32 modelId)
void SetPhaseMask (uint32 newPhaseMask, bool update)
uint32 GetFaction () const override
void SetFaction (uint32 faction)
uint32 GetLevel () const override
void Use (Unit *user, SpellEntry const *spellInfo=nullptr)
LootState GetLootState () const
void SetLootState (LootState state, Unit *user=nullptr)
void AddToSkillupList (Player *player)
bool IsInSkillupList (Player *player) const
void ClearSkillupList ()
void ClearAllUsesData ()
void SetActionTarget (ObjectGuid guid)
void AddUniqueUse (Player *player)
void AddUse ()
bool IsInUse () const
void SetInUse (bool use)
uint32 GetUseCount () const
uint32 GetUniqueUseCount () const
void SaveRespawnTime () override
ObjectGuid GetLootRecipientGuid () const
uint32 GetLootGroupRecipientId () const
Player * GetLootRecipient () const
Group * GetGroupLootRecipient () const
bool HasLootRecipient () const
bool IsGroupLootRecipient () const
void SetLootRecipient (Unit *pUnit)
Player * GetOriginalLootRecipient () const
bool HasQuest (uint32 quest_id) const override
bool HasInvolvedQuest (uint32 quest_id) const override
bool ActivateToQuest (Player *pTarget) const
void UseDoorOrButton (uint32 time_to_restore=0, bool alternative=false)
void ResetDoorOrButton (Unit *user=nullptr)
void UseOpenableObject (bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
ReputationRank GetReactionTo (Unit const *unit) const override
Get GO to unit reaction.
bool IsEnemy (Unit const *unit) const override
[Serverside] Reaction preset: GO sees a unit as an enemy
bool IsFriend (Unit const *unit) const override
[Serverside] Reaction preset: GO sees a unit as a friend
bool CanAttackSpell (Unit const *target, SpellEntry const *spellInfo=nullptr, bool isAOE=false) const override
[Serverside] Opposition: GameObject can target a target with a harmful spell
bool CanAssistSpell (Unit const *target, SpellEntry const *spellInfo=nullptr) const override
[Serverside] Assistance: GameObject can target a target with a helpful spell
GameObject * SummonLinkedTrapIfAny () const
void TriggerLinkedGameObject (Unit *target) const
GameObject * GetLinkedTrap ()
void SetLinkedTrap (GameObject *linkedTrap)
void DealGameObjectDamage (uint32 damage, uint32 spell, Unit *caster)
void RebuildGameObject (Unit *caster)
void SetDestructibleState (GameObjectDestructibleState state, Unit *attackerOrHealer=nullptr, bool setHealth=false)
GameObjectDestructibleState GetDestructibleState () const
uint32 GetHealth () const
uint32 GetMaxHealth () const
bool isVisibleForInState (Player const *u, WorldObject const *viewPoint, bool inVisibleList) const override
bool IsCollisionEnabled () const
GameObject * LookupFishingHoleAround (float range) const
void SetCapturePointSlider (float value, bool isLocked)
float GetCapturePointSliderValue () const
float GetInteractionDistance () const
float GetCollisionHeight () const override
GridReference< GameObject > & GetGridRef ()
uint32 GetScriptId () const
void AIM_Initialize ()
void OnEventHappened (uint16 eventId, bool activate, bool resume) override
GameObjectAI * AI () const
void AddModelToMap ()
void RemoveModelFromMap ()
void UpdateModelPosition ()
bool _IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D) const override
bool IsAtInteractDistance (Position const &pos, float radius, bool is3D=true) const
bool IsAtInteractDistance (Player const *player, uint32 maxRange=0) const
SpellEntry const * GetSpellForLock (Player const *player) const
float GetStationaryX () const
float GetStationaryY () const
float GetStationaryZ () const
float GetStationaryO () const
std::pair< float, float > GetClosestChairSlotPosition (Unit *user) const
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, uint32 spellId, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, uint32 spellId, TriggerCastFlags triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
SpellCastResult CastSpell (Unit *temporaryCaster, Unit *Victim, SpellEntry const *spellInfo, uint32 triggeredFlags, Item *castItem=nullptr, Aura *triggeredByAura=nullptr, ObjectGuid originalCaster=ObjectGuid(), SpellEntry const *triggeredBy=nullptr)
void GenerateLootFor (Player *player)
HighGuid GetParentHigh () const override
void SetCooldown (uint32 cooldown)
void SetGameObjectGroup (GameObjectGroup *group)
void ClearGameObjectGroup ()
GameObjectGroup * GetGameObjectGroup () const
Public Member Functions inherited from WorldObject
virtual ~WorldObject ()
virtual uint32 GetHeartbeatDuration () const
void _Create (uint32 guidlow, HighGuid guidhigh, uint32 phaseMask)
TransportInfo * GetTransportInfo () const
bool IsBoarded () const
void SetTransportInfo (TransportInfo *transportInfo)
void Relocate (float x, float y, float z, float orientation)
void Relocate (float x, float y, float z)
void SetOrientation (float orientation)
float GetPositionX () const
float GetPositionY () const
float GetPositionZ () const
void GetPosition (float &x, float &y, float &z, GenericTransport *transport=nullptr) const
void GetPosition (WorldLocation &loc) const
Position const & GetPosition (GenericTransport *transport=nullptr) const
float GetOrientation () const
void GetNearPoint2d (float &x, float &y, float distance2d, float absAngle) const
Gives a 2d-point in distance distance2d in direction absAngle around the current position (point-to-point)
void GetNearPoint (WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
Gives a "free" spot for searcher in distance distance2d in direction absAngle on "good" height.
void GetNearPointAt (const float posX, const float posY, const float posZ, WorldObject const *searcher, float &x, float &y, float &z, float searcher_bounding_radius, float distance2d, float absAngle, bool isInWater=false) const
void GetClosePoint (float &x, float &y, float &z, float bounding_radius, float distance2d=0.0f, float angle=0.0f, const WorldObject *obj=nullptr) const
Gives a "free" spot for a searcher on the distance (including bounding-radius calculation)
void GetContactPoint (const WorldObject *obj, float &x, float &y, float &z, float distance2d=CONTACT_DISTANCE) const
Gives a "free" spot for a searcher in contact-range of "this" (including bounding-radius calculation)
bool GetFanningPoint (const Unit *mover, float &x, float &y, float &z, float dist, float angle) const
virtual float GetCollisionWidth () const
virtual float GetObjectBoundingRadius () const
virtual float GetCombatReach () const
float GetCombinedCombatReach (WorldObject const *pVictim, bool forMeleeRange=true, float flat_mod=0.0f) const
float GetCombinedCombatReach (bool forMeleeRange=true, float flat_mod=0.0f) const
bool IsPositionValid () const
void UpdateGroundPositionZ (float x, float y, float &z) const
virtual void UpdateAllowedPositionZ (float x, float y, float &z, Map *atMap=nullptr) const
virtual void AdjustZForCollision (float, float, float &, float) const
void MovePositionToFirstCollision (Position &pos, float dist, float angle)
void GetFirstCollisionPosition (Position &pos, float dist, float angle)
Position GetFirstRandomAngleCollisionPosition (float dist, float angle)
void GetRandomPoint (float x, float y, float z, float distance, float &rand_x, float &rand_y, float &rand_z, float minDist=0.0f, float const *ori=nullptr) const
uint32 GetMapId () const
uint32 GetInstanceId () const
uint32 GetPhaseMask () const
bool InSamePhase (WorldObject const *obj) const
bool InSamePhase (uint32 phasemask) const
uint32 GetZoneId () const
uint32 GetAreaId () const
AreaNameInfo GetAreaName (LocaleConstant locale) const
void GetZoneAndAreaId (uint32 &zoneid, uint32 &areaid) const
InstanceData * GetInstanceData () const
char const * GetName () const
std::string const & GetNameStr () const
void SetName (const std::string &newname)
float GetDistance (const WorldObject *obj, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistance (float x, float y, float z, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS, bool transport=false) const
float GetDistance2d (float x, float y, DistanceCalculation distcalc=DIST_CALC_BOUNDING_RADIUS) const
float GetDistanceZ (const WorldObject *obj) const
bool IsInMapIgnorePhase (const WorldObject *obj) const
bool IsInMap (const WorldObject *obj) const
bool IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinCombatDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinDist3d (float x, float y, float z, float dist2compare) const
bool IsWithinDist2d (float x, float y, float dist2compare) const
bool _IsWithinCombatDist (WorldObject const *obj, float dist2compare, bool is3D) const
bool IsWithinDist (WorldObject const *obj, float dist2compare, bool is3D=true) const
bool IsWithinDistInMap (WorldObject const *obj, float dist2compare, bool is3D=true, bool ignorePhase=false) const
bool IsWithinLOS (float ox, float oy, float oz, bool ignoreM2Model=false) const
bool IsWithinLOSForMe (float x, float y, float z, float collisionHeight, bool ignoreM2Model=false) const
bool IsWithinLOSInMap (const WorldObject *obj, bool ignoreM2Model=false) const
bool GetDistanceOrder (WorldObject const *obj1, WorldObject const *obj2, bool is3D=true, DistanceCalculation distcalc=DIST_CALC_NONE) const
bool IsInRange (WorldObject const *obj, float minRange, float maxRange, bool is3D=true, bool combat=false) const
bool IsInRange2d (float x, float y, float minRange, float maxRange, bool combat=false) const
bool IsInRange3d (float x, float y, float z, float minRange, float maxRange, bool combat=false) const
float GetAngle (float x, float y) const
float GetAngleAt (float x, float y, const WorldObject *obj) const
float GetAngle (const WorldObject *obj) const
bool HasInArcAt (float x, float y, float o, const WorldObject *target, float arc=M_PI_F) const
bool HasInArc (const WorldObject *target, float arc=M_PI_F) const
bool isInFrontInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBackInMap (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInFront (WorldObject const *target, float distance, float arc=M_PI_F) const
bool isInBack (WorldObject const *target, float distance, float arc=M_PI_F) const
bool IsFacingTargetsBack (const WorldObject *target, float arc=M_PI_F) const
bool IsFacingTargetsFront (const WorldObject *target, float arc=M_PI_F) const
virtual void CleanupsBeforeDelete ()
virtual void SendMessageToSet (WorldPacket const &data, bool self) const
virtual void SendMessageToSetInRange (WorldPacket const &data, float dist, bool self) const
void SendMessageToSetExcept (WorldPacket const &data, Player const *skipped_receiver) const
virtual void SendMessageToAllWhoSeeMe (WorldPacket const &data, bool self) const
void MonsterSay (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterYell (const char *text, uint32 language, Unit const *target=nullptr) const
void MonsterTextEmote (const char *text, Unit const *target, bool IsBossEmote=false) const
void MonsterWhisper (const char *text, Unit const *target, bool IsBossWhisper=false) const
void MonsterText (std::vector< std::string > content, uint32 type, Language lang, Unit const *target) const
Function that sends a text associated to a MangosString or BroadcastText.
void PlayDistanceSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayDirectSound (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlayMusic (uint32 sound_id, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void PlaySpellVisual (uint32 artKitId, PlayPacketParameters parameters=PlayPacketParameters(PLAY_SET)) const
void HandlePlayPacketSettings (WorldPacket &msg, PlayPacketParameters &parameters) const
void SendObjectDeSpawnAnim (ObjectGuid guid) const
void SendGameObjectCustomAnim (ObjectGuid guid, uint32 animId=0) const
virtual ReputationRank GetReactionTo (Corpse const *corpse) const
[Serverside] Get default WorldObject (hierarchy) reaction to a corpse
bool IsControlledByPlayer () const
void AddObjectToRemoveList ()
void UpdateObjectVisibility ()
virtual void UpdateVisibilityAndView ()
bool isVisibleFor (Player const *u, WorldObject const *viewPoint) const
void SetMap (Map *map)
Map * GetMap () const
virtual void ResetMap ()
TerrainInfo const * GetTerrain () const
void AddToClientUpdateList () override
void RemoveFromClientUpdateList () override
void BuildUpdateData (UpdateDataMapType &) override
Creature * SummonCreature (uint32 id, float x, float y, float z, float ang, TempSpawnType spwtype, uint32 despwtime, bool asActiveObject=false, bool setRun=false, uint32 pathId=0, uint32 faction=0, uint32 modelId=0, bool spawnCounting=false, bool forcedOnTop=false)
bool isActiveObject () const
void SetActiveObjectState (bool active)
ViewPoint & GetViewPoint ()
bool PrintCoordinatesError (float x, float y, float z, char const *descr) const
virtual bool IsNotifyOnEventObject ()
void SetNotifyOnEventState (bool state)
virtual void AddGCD (SpellEntry const &spellEntry, uint32 forcedDuration=0, bool updateClient=false)
virtual bool HasGCD (SpellEntry const *spellEntry) const
TimePoint GetGCD (SpellEntry const *spellEntry) const
void ResetGCD (SpellEntry const *spellEntry=nullptr)
virtual void AddCooldown (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr, bool permanent=false, uint32 forcedDuration=0, bool ignoreCat=false)
virtual void RemoveSpellCooldown (SpellEntry const &spellEntry, bool updateClient=true)
void RemoveSpellCooldown (uint32 spellId, bool updateClient=true)
virtual void RemoveSpellCategoryCooldown (uint32 category, bool updateClient=true)
virtual void RemoveAllCooldowns (bool=false)
bool IsSpellReady (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr) const
bool IsSpellReady (uint32 spellId, ItemPrototype const *itemProto=nullptr) const
bool IsSpellOnPermanentCooldown (SpellEntry const &spellEntry) const
bool HasGCDOrCooldownWithinMargin (SpellEntry const &spellEntry, ItemPrototype const *itemProto=nullptr)
virtual void LockOutSpells (SpellSchoolMask schoolMask, uint32 duration)
void PrintCooldownList (ChatHandler &chat) const
virtual void InspectingLoot ()
int32 CalculateSpellEffectValue (Unit const *target, SpellEntry const *spellProto, SpellEffectIndex effect_index, int32 const *basePoints=nullptr, bool maximum=false, bool finalUse=true) const
VisibilityData const & GetVisibilityData () const
VisibilityData & GetVisibilityData ()
bool HaveDebugFlag (CMDebugFlags flag) const
void SetDebugFlag (CMDebugFlags flag)
void ClearDebugFlag (CMDebugFlags flag)
Cell const & GetCurrentCell () const
void SetCurrentCell (Cell const &cell)
GenericTransport * GetTransport () const
void SetTransport (GenericTransport *t)
float GetTransOffsetX () const
float GetTransOffsetY () const
float GetTransOffsetZ () const
float GetTransOffsetO () const
uint32 GetTransTime () const
int8 GetTransSeat () const
uint8 GetDestLocCounter ()
void IncrementDestLocCounter ()
bool IsUsingNewSpawningSystem () const
void AddClientIAmAt (Player const *player)
void RemoveClientIAmAt (Player const *player)
GuidSet & GetClientGuidsIAmAt ()
bool CheckAndIncreaseCastCounter ()
void DecreaseCastCounter ()
virtual Player * GetSpellModOwner () const
void AddStringId (std::string &stringId)
void RemoveStringId (std::string &stringId)
bool HasStringId (std::string &stringId) const
bool HasStringId (uint32 stringId) const
void SetStringId (uint32 stringId, bool apply)
Public Member Functions inherited from Object
virtual ~Object ()
const bool & IsInWorld () const
ObjectGuid const & GetObjectGuid () const
uint32 GetGUIDLow () const
uint32 GetGUIDHigh () const
PackedGuid const & GetPackGUID () const
uint32 GetDbGuid () const
std::string GetGuidStr () const
uint32 GetEntry () const
void SetEntry (uint32 entry)
float GetObjectScale () const
void SetObjectScale (float newScale)
uint8 GetTypeId () const
uint8 GetTypeMask () const
bool isType (TypeMask mask) const
virtual void BuildCreateUpdateBlockForPlayer (UpdateData *data, Player *target) const
void SendCreateUpdateToPlayer (Player *player) const
void MarkForClientUpdate ()
void SendForcedObjectUpdate ()
void BuildValuesUpdateBlockForPlayer (UpdateData &data, Player *target) const
void BuildValuesUpdateBlockForPlayerWithFlags (UpdateData &data, Player *target, UpdateFieldFlags flags) const
void BuildValuesUpdateBlockForPlayer (UpdateData &data, UpdateMask &updateMask, Player *target) const
void BuildForcedValuesUpdateBlockForPlayer (UpdateData *data, Player *target) const
void BuildOutOfRangeUpdateBlock (UpdateData *data) const
void BuildMovementUpdateBlock (UpdateData *data, uint16 flags=0) const
virtual void DestroyForPlayer (Player *target, bool anim=false) const
const int32 & GetInt32Value (uint16 index) const
const uint32 & GetUInt32Value (uint16 index) const
const uint64 & GetUInt64Value (uint16 index) const
const float & GetFloatValue (uint16 index) const
uint8 GetByteValue (uint16 index, uint8 offset) const
uint16 GetUInt16Value (uint16 index, uint8 offset) const
ObjectGuid const & GetGuidValue (uint16 index) const
void SetInt32Value (uint16 index, int32 value)
void SetUInt32Value (uint16 index, uint32 value)
void SetUInt64Value (uint16 index, const uint64 &value)
void SetFloatValue (uint16 index, float value)
void SetByteValue (uint16 index, uint8 offset, uint8 value)
void SetUInt16Value (uint16 index, uint8 offset, uint16 value)
void SetInt16Value (uint16 index, uint8 offset, int16 value)
void SetGuidValue (uint16 index, ObjectGuid const &value)
void SetStatFloatValue (uint16 index, float value)
void SetStatInt32Value (uint16 index, int32 value)
void ApplyModUInt32Value (uint16 index, int32 val, bool apply)
void ApplyModInt32Value (uint16 index, int32 val, bool apply)
void ApplyModPositiveFloatValue (uint16 index, float val, bool apply)
void ApplyModSignedFloatValue (uint16 index, float val, bool apply)
void ApplyPercentModFloatValue (uint16 index, float val, bool apply)
void ForceValuesUpdateAtIndex (uint16 index)
void MarkUpdateFieldsWithFlagForUpdate (UpdateMask &updateMask, uint16 flag) const
void SetFlag (uint16 index, uint32 newFlag)
void RemoveFlag (uint16 index, uint32 oldFlag)
void ToggleFlag (uint16 index, uint32 flag)
bool HasFlag (uint16 index, uint32 flag) const
void ApplyModFlag (uint16 index, uint32 flag, bool apply)
void SetByteFlag (uint16 index, uint8 offset, uint8 newFlag)
void RemoveByteFlag (uint16 index, uint8 offset, uint8 oldFlag)
void ToggleByteFlag (uint16 index, uint8 offset, uint8 flag)
bool HasByteFlag (uint16 index, uint8 offset, uint8 flag) const
void ApplyModByteFlag (uint16 index, uint8 offset, uint32 flag, bool apply)
void SetShortFlag (uint16 index, bool highpart, uint16 newFlag)
void RemoveShortFlag (uint16 index, bool highpart, uint16 oldFlag)
void ToggleShortFlag (uint16 index, bool highpart, uint8 flag)
bool HasShortFlag (uint16 index, bool highpart, uint8 flag) const
void ApplyModShortFlag (uint16 index, bool highpart, uint32 flag, bool apply)
void SetFlag64 (uint16 index, uint64 newFlag)
void RemoveFlag64 (uint16 index, uint64 oldFlag)
void ToggleFlag64 (uint16 index, uint64 flag)
bool HasFlag64 (uint16 index, uint64 flag) const
void ApplyModFlag64 (uint16 index, uint64 flag, bool apply)
void ClearUpdateMask (bool remove)
void _LoadIntoDataField (const char *data, uint32 startOffset, uint32 count)
uint16 GetValuesCount () const
void SetItsNewObject (bool enable)
bool IsPlayer () const
bool IsCreature () const
bool IsUnit () const
bool IsGameObject () const
bool IsCorpse () const
bool PrintIndexError (uint32 index, bool set) const
bool PrintEntryError (char const *descr) const
Static Public Member Functions
static bool IsSpawnedByDefault (uint32 entry, Team team)
static void LoadTransport (TransportTemplate const &transportTemplate, Map *map, bool spawnOnDemand=false)
Static Public Member Functions inherited from GenericTransport
static void CalculatePassengerPosition (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
static void CalculatePassengerOffset (float &x, float &y, float &z, float *o, float transX, float transY, float transZ, float transO)
Static Public Member Functions inherited from GameObject
static GameObject * CreateGameObject (uint32 entry)
static void AddToRemoveListInMaps (uint32 db_guid, GameObjectData const *data)
static void SpawnInMaps (uint32 db_guid, GameObjectData const *data)
Static Public Member Functions inherited from WorldObject
static void GetNearPoint2dAt (const float posX, const float posY, float &x, float &y, float distance2d, float absAngle)
static float GetAngleAt (float x, float y, float ox, float oy)
static Creature * SummonCreature (TempSpawnSettings settings, Map *map, uint32 phaseMask)
static GameObject * SpawnGameObject (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
static Creature * SpawnCreature (uint32 dbGuid, Map *map, uint32 forcedEntry=0, GenericTransport *transport=nullptr)
Private Member Functions
void TeleportTransport (uint32 newMapid, float x, float y, float z, float o)
void UpdateForMap (Map const *targetMap, bool newMap)
void DoEventIfAny (TaxiPathNodeEntry const &node, bool departure)
void MoveToNextWayPoint ()
float CalculateSegmentPos (float perc)
bool IsMoving () const
void SetMoving (bool val)
Private Attributes
ShortTimeTracker m_positionChangeTimer
ShortTimeTracker m_dynamicChangeTimer
bool m_isMoving
KeyFrameVec::const_iterator m_currentFrame
KeyFrameVec::const_iterator m_nextFrame
uint32 m_pathTime
uint32 m_period
int32 m_lastStopIndex
TransportTemplate const & m_transportTemplate
Additional Inherited Members
Public Types inherited from GenericTransport
typedef std::set< Player * > PlayerSet
Data Fields inherited from GameObject
GameObjectModel * m_model
Data Fields inherited from WorldObject
MovementInfo m_movementInfo
GenericTransport * m_transport
EventProcessor m_events
Data Fields inherited from Object
Loot * m_loot
Protected Member Functions inherited from GenericTransport
void UpdatePassengerPositions (PassengerSet &passengers)
Protected Member Functions inherited from GameObject
void TriggerSummoningRitual ()
void TriggerDelayedAction ()
Protected Member Functions inherited from WorldObject
WorldObject ()
void SetLocationMapId (uint32 _mapId)
void SetLocationInstanceId (uint32 _instanceId)
void UpdateCooldowns (TimePoint const &now)
bool CheckLockout (SpellSchoolMask schoolMask, TimePoint const &now) const
bool GetExpireTime (SpellEntry const &spellEntry, TimePoint &expireTime, bool &isPermanent) const
Protected Member Functions inherited from Object
Object ()
void _InitValues ()
void _Create (uint32 dbGuid, uint32 guidlow, uint32 entry, HighGuid guidhigh)
uint16 GetUpdateFieldFlagsForTarget (Player const *target, uint16 const *&flags) const
void _SetUpdateBits (UpdateMask &updateMask, Player *target) const
void _SetCreateBits (UpdateMask &updateMask, Player *target) const
void BuildMovementUpdate (ByteBuffer *data, uint16 updateFlags) const
void BuildValuesUpdate (uint8 updatetype, ByteBuffer *data, UpdateMask *updateMask, Player *target) const
void BuildUpdateDataForPlayer (Player *pl, UpdateDataMapType &update_players) const
Protected Attributes inherited from GenericTransport
PassengerSet m_passengers
PassengerSet::iterator m_passengerTeleportIterator
uint32 m_pathProgress
uint32 m_movementStarted
bool m_stopped
std::set< ObjectGuid > m_staticPassengers
Protected Attributes inherited from GameObject
uint32 m_spellId
time_t m_respawnTime
uint32 m_respawnDelay
bool m_respawnOverriden
bool m_respawnOverrideOnce
bool m_forcedDespawn
LootState m_lootState
bool m_spawnedByDefault
time_t m_cooldownTime
uint32 m_captureTimer
float m_captureSlider
CapturePointState m_captureState
GuidSet m_SkillupSet
uint32 m_useTimes
ObjectGuid m_firstUser
GuidSet m_UniqueUsers
GameObjectInfo const * m_goInfo
GameObjectDisplayInfoEntry const * m_displayInfo
int64 m_packedRotation
QuaternionData m_localRotation
Position m_stationaryPosition
ObjectGuid m_lootRecipientGuid
uint32 m_lootGroupRecipientId
time_t m_rearmTimer
bool m_isInUse
time_t m_reStockTimer
time_t m_despawnTimer
uint32 m_delayedActionTimer
ObjectGuid m_actionTarget
ObjectGuid m_linkedTrap
std::unique_ptr< GameObjectAI > m_AI
ObjectGuid m_spawnerGuid
GameObjectGroup * m_goGroup
Protected Attributes inherited from WorldObject
GCDMap m_GCDCatMap
LockoutMap m_lockoutMap
CooldownContainer m_cooldownMap
std::string m_name
TransportInfo * m_transportInfo
Cell m_currentCell
bool m_isOnEventNotified
VisibilityData m_visibilityData
ShortTimeTracker m_heartBeatTimer
Protected Attributes inherited from Object
uint16 m_objectType
uint8 m_objectTypeId
uint16 m_updateFlag
union {
int32 * m_int32Values
uint32 * m_uint32Values
float * m_floatValues
};
std::vector< bool > m_changedValues
uint16 m_valuesCount
bool m_objectUpdated
Detailed Description
Definition at line 93 of file Transports.h.
Constructor & Destructor Documentation
Transport()
Transport::Transport (TransportTemplate const & transportTemplate) explicit
Definition at line 126 of file Transports.cpp.
References Object::m_updateFlag, UPDATEFLAG_HAS_POSITION, UPDATEFLAG_HIGHGUID, UPDATEFLAG_ROTATION, and UPDATEFLAG_TRANSPORT.
Referenced by LoadTransport().
Member Function Documentation
CalculateSegmentPos()
float Transport::CalculateSegmentPos (float perc) private
Definition at line 570 of file Transports.cpp.
References TransportTemplate::accelDist, TransportTemplate::accelTime, KeyFrame::DepartureTime, KeyFrame::DistSinceStop, KeyFrame::DistUntilStop, IN_MILLISECONDS, m_currentFrame, GameObject::m_goInfo, m_transportTemplate, GameObjectInfo::moTransport, KeyFrame::NextDistFromPrev, KeyFrame::TimeFrom, and KeyFrame::TimeTo.
Referenced by Update().
Create()
bool Transport::Create (uint32 guidlow, uint32 mapid, float x, float y, float z, float ang, uint8 animprogress, uint16 dynamicHighValue)
Definition at line 187 of file Transports.cpp.
References Object::_Create(), GameObjectInfo::displayId, GameObjectInfo::faction, GAMEOBJECT_DYNAMIC, GAMEOBJECT_FACTION, GAMEOBJECT_FLAGS, GAMEOBJECT_LEVEL, ObjectMgr::GetGameObjectInfo(), GetKeyFrames(), WorldObject::GetVisibilityData(), Gigantic, GO_FLAG_NODESPAWN, GO_FLAG_TRANSPORT, GO_STATE_READY, HIGHGUID_MO_TRANSPORT, GameObjectInfo::id, WorldObject::IsPositionValid(), m_currentFrame, GameObject::m_goInfo, GenericTransport::m_movementStarted, m_nextFrame, GenericTransport::m_pathProgress, m_period, GameObjectInfo::name, WorldObject::Relocate(), GameObject::SetDisplayId(), Object::SetEntry(), GameObject::SetGoAnimProgress(), GameObject::SetGoArtKit(), GenericTransport::SetGoState(), GameObject::SetGoType(), WorldObject::SetName(), Object::SetObjectScale(), Object::SetUInt16Value(), Object::SetUInt32Value(), VisibilityData::SetVisibilityDistanceOverride(), GameObjectInfo::size, sLog, and GameObjectInfo::type.
Referenced by LoadTransport().
DespawnPassengers()
void Transport::DespawnPassengers () override virtual
Reimplemented from GenericTransport.
Definition at line 267 of file Transports.cpp.
References WorldObject::GetMap(), GenericTransport::m_staticPassengers, and GenericTransport::RemovePassenger().
Referenced by Update().
DoEventIfAny()
void Transport::DoEventIfAny (TaxiPathNodeEntry const & node, bool departure) private
Definition at line 870 of file Transports.cpp.
References TaxiPathNodeEntry::arrivalEventID, DEBUG_FILTER_LOG, TaxiPathNodeEntry::departureEventID, Object::GetGuidStr(), WorldObject::GetMap(), WorldObject::GetName(), TaxiPathNodeEntry::index, LOG_FILTER_TRANSPORT_MOVES, and StartEvents_Event().
Referenced by Update().
GetKeyFrames()
KeyFrameVec const& Transport::GetKeyFrames () const inline
Definition at line 106 of file Transports.h.
References TransportTemplate::keyFrames, and m_transportTemplate.
Referenced by Create(), LoadTransport(), MoveToNextWayPoint(), and Update().
GetPeriod()
uint32 Transport::GetPeriod () const inline
Definition at line 103 of file Transports.h.
References m_period.
Referenced by Update().
IsMoving()
bool Transport::IsMoving () const inline private
Definition at line 117 of file Transports.h.
References m_isMoving.
Referenced by Update().
IsSpawnedByDefault()
bool Transport::IsSpawnedByDefault (uint32 entry, Team team) static
Definition at line 131 of file Transports.cpp.
References ALLIANCE, and HORDE.
LoadTransport()
void Transport::LoadTransport (TransportTemplate const & transportTemplate, Map * map, bool spawnOnDemand = false) static
Definition at line 154 of file Transports.cpp.
References Map::AddTransport(), Create(), TransportTemplate::entry, Map::GetId(), GetKeyFrames(), GO_ANIMPROGRESS_DEFAULT, TransportTemplate::keyFrames, TransportTemplate::pathTime, WorldObject::SetMap(), SetPeriod(), SpawnPassengers(), Transport(), UpdateForMap(), TaxiPathNodeEntry::x, TaxiPathNodeEntry::y, and TaxiPathNodeEntry::z.
Referenced by instance_icecrown_citadel::ExecuteChatCommand(), instance_icecrown_citadel::JustDidDialogueStep(), Map::LoadTransports(), and instance_icecrown_citadel::SetData().
MoveToNextWayPoint()
void Transport::MoveToNextWayPoint () private
Definition at line 244 of file Transports.cpp.
References GetKeyFrames(), m_currentFrame, and m_nextFrame.
Referenced by Update().
SetMoving()
void Transport::SetMoving (bool val) inline private
Definition at line 118 of file Transports.h.
References m_isMoving.
Referenced by Update().
SetPeriod()
void Transport::SetPeriod (uint32 period) inline
Definition at line 104 of file Transports.h.
References m_period.
Referenced by LoadTransport().
SpawnPassengers()
void Transport::SpawnPassengers () override virtual
Reimplemented from GenericTransport.
Definition at line 251 of file Transports.cpp.
References GameObject::GetGOInfo(), WorldObject::GetMap(), GameObjectInfo::moTransport, sObjectMgr, WorldObject::SpawnCreature(), WorldObject::SpawnGameObject(), TYPEID_GAMEOBJECT, and TYPEID_UNIT.
Referenced by LoadTransport(), and Update().
TeleportTransport()
void Transport::TeleportTransport (uint32 newMapid, float x, float y, float z, float o) private
Definition at line 281 of file Transports.cpp.
References Messager< T >::AddMessage(), WorldObject::AddObjectToRemoveList(), Map::AddTransport(), WorldObject::GetMap(), WorldObject::GetMapId(), Map::GetMessager(), GenericTransport::GetPassengers(), MovementInfo::GetTransportPos(), Object::GetTypeId(), Unit::GetVehicleInfo(), Object::HasFlag(), Object::IsCreature(), Unit::IsDead(), Creature::IsPet(), Object::IsUnit(), WorldObject::m_movementInfo, GenericTransport::m_passengers, GenericTransport::m_passengerTeleportIterator, Position::o, PLAYER_FLAGS, PLAYER_FLAGS_GHOST, WorldObject::Relocate(), Object::RemoveFromWorld(), GameObject::RemoveModelFromMap(), GenericTransport::RemovePassenger(), Map::RemoveTransport(), WorldObject::ResetMap(), Player::ResurrectPlayer(), sMapMgr, TELE_TO_NOT_LEAVE_TRANSPORT, VehicleInfo::TeleportPassengers(), Player::TeleportTo(), TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_PLAYER, TYPEID_UNIT, UpdateForMap(), GameObject::UpdateModelPosition(), GenericTransport::UpdatePassengerPositions(), Position::x, Position::y, and Position::z.
Referenced by Update().
Update()
void Transport::Update (const uint32 diff) override virtual
Reimplemented from GameObject.
Definition at line 459 of file Transports.cpp.
References GameObject::AI(), CalculateSegmentPos(), GameObjectInfo::canBeStopped, DespawnPassengers(), DETAIL_FILTER_LOG, DoEventIfAny(), GAMEOBJECT_DYNAMIC, Map::GetCurrentMSTime(), GameObject::GetGOInfo(), GetKeyFrames(), WorldObject::GetMap(), WorldObject::GetMapId(), WorldObject::GetName(), GetPeriod(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Object::GetUInt16Value(), GO_DYNFLAG_LO_STOPPED, GO_STATE_READY, Object::IsInWorld(), Map::IsLoaded(), IsMoving(), GameObjectAI::JustReachedStopPoint(), LOG_FILTER_TRANSPORT_MOVES, m_currentFrame, m_dynamicChangeTimer, m_lastStopIndex, GenericTransport::m_movementStarted, m_nextFrame, GenericTransport::m_pathProgress, M_PI, m_positionChangeTimer, GenericTransport::m_staticPassengers, GenericTransport::m_stopped, MoveToNextWayPoint(), ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), GameObject::SetGoState(), SetMoving(), Object::SetUInt16Value(), SpawnPassengers(), TeleportTransport(), ShortTimeTracker::Update(), GameObjectAI::UpdateAI(), and GenericTransport::UpdatePosition().
Referenced by Map::Update().
UpdateForMap()
void Transport::UpdateForMap (Map const * targetMap, bool newMap) private
Definition at line 832 of file Transports.cpp.
References Player::AddAtClient(), Object::BuildCreateUpdateBlockForPlayer(), Object::BuildOutOfRangeUpdateBlock(), UpdateData::BuildPacket(), Map::GetPlayers(), WorldObject::GetTransport(), LinkedListHead::isEmpty(), Player::RemoveAtClient(), and Player::SendDirectMessage().
Referenced by LoadTransport(), and TeleportTransport().
Field Documentation
m_currentFrame
KeyFrameVec::const_iterator Transport::m_currentFrame private
Definition at line 124 of file Transports.h.
Referenced by CalculateSegmentPos(), Create(), MoveToNextWayPoint(), and Update().
m_dynamicChangeTimer
ShortTimeTracker Transport::m_dynamicChangeTimer private
Definition at line 121 of file Transports.h.
Referenced by Update().
m_isMoving
bool Transport::m_isMoving private
Definition at line 122 of file Transports.h.
Referenced by IsMoving(), and SetMoving().
m_lastStopIndex
int32 Transport::m_lastStopIndex private
Definition at line 129 of file Transports.h.
Referenced by Update().
m_nextFrame
KeyFrameVec::const_iterator Transport::m_nextFrame private
Definition at line 125 of file Transports.h.
Referenced by Create(), MoveToNextWayPoint(), and Update().
m_pathTime
uint32 Transport::m_pathTime private
Definition at line 126 of file Transports.h.
m_period
uint32 Transport::m_period private
Definition at line 128 of file Transports.h.
Referenced by Create(), GetPeriod(), and SetPeriod().
m_positionChangeTimer
ShortTimeTracker Transport::m_positionChangeTimer private
Definition at line 120 of file Transports.h.
Referenced by Update().
m_transportTemplate
TransportTemplate const& Transport::m_transportTemplate private
Definition at line 131 of file Transports.h.
Referenced by CalculateSegmentPos(), and GetKeyFrames().
The documentation for this class was generated from the following files:
Transports.h
Transports.cpp