CMaNGOS_WoTLK: instance_nexus Class Reference
instance_nexus Class Reference
#include <nexus.h>
Public Member Functions
instance_nexus (Map *pMap)
void Initialize () override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureRespawn (Creature *creature) override
uint32 GetData (uint32 uiType) const override
void SetData (uint32 uiType, uint32 uiData) override
void SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
const char * Save () const override
void Load (const char *chrIn) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void Update (const uint32)
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDeath (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
bool m_abAchievCriteria [MAX_SPECIAL_ACHIEV_CRITS]
std::set< uint32 > m_sIntenseColdFailPlayers
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 46 of file nexus.h.
Constructor & Destructor Documentation
instance_nexus()
instance_nexus::instance_nexus (Map * pMap)
Definition at line 50 of file nexus.cpp.
References Initialize(), and m_abAchievCriteria.
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_nexus::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 201 of file nexus.cpp.
References ACHIEV_CRIT_CHAOS_THEORY, ACHIEV_CRIT_INTENSE_COLD, ACHIEV_CRIT_SPLIT_PERSONALITY, Object::GetGUIDLow(), m_abAchievCriteria, m_sIntenseColdFailPlayers, TYPE_ACHIEV_CHAOS_THEORY, and TYPE_ACHIEV_SPLIT_PERSONALITY.
GetData()
uint32 instance_nexus::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 122 of file nexus.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by OnCreatureRespawn(), and boss_keristraszaAI::Reset().
Initialize()
void instance_nexus::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 58 of file nexus.cpp.
References m_auiEncounter.
Referenced by instance_nexus().
Load()
void instance_nexus::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 218 of file nexus.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_nexus::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 86 of file nexus.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidStore, NPC_ANOMALUS, NPC_KERISTRASZA, and NPC_ORMOROK.
OnCreatureRespawn()
void instance_nexus::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 98 of file nexus.cpp.
References Creature::AI(), UnitAI::AttackStart(), GetData(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_PROGRESS, WorldObject::IsWithinDistInMap(), NPC_ANOMALUS, NPC_CRAZED_MANA_WRAITH, NPC_CRYSTAL_SPIKE, NPC_CRYSTAL_SPIKE_INITIAL, NPC_CRYSTAL_SPIKE_TRIGGER, REACT_PASSIVE, Unit::SetCanEnterCombat(), UnitAI::SetReactState(), and TYPE_ANOMALUS.
OnObjectCreate()
void instance_nexus::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 63 of file nexus.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_CONTAINMENT_SPHERE_ANOMALUS, GO_CONTAINMENT_SPHERE_ORMOROK, GO_CONTAINMENT_SPHERE_TELESTRA, GO_FLAG_NO_INTERACT, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, Object::RemoveFlag(), TYPE_ANOMALUS, TYPE_ORMOROK, and TYPE_TELESTRA.
Save()
const char* instance_nexus::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 63 of file nexus.h.
References m_strInstData.
SetData()
void instance_nexus::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 130 of file nexus.cpp.
References DONE, ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CONTAINMENT_SPHERE_ANOMALUS, GO_CONTAINMENT_SPHERE_ORMOROK, GO_CONTAINMENT_SPHERE_TELESTRA, GO_FLAG_NO_INTERACT, IN_PROGRESS, Unit::IsAlive(), m_auiEncounter, m_sIntenseColdFailPlayers, m_strInstData, NPC_KERISTRASZA, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), InstanceData::SaveToDB(), script_error_log(), SetSpecialAchievementCriteria(), SPECIAL, SPELL_FROZEN_PRISON, TYPE_ACHIEV_CHAOS_THEORY, TYPE_ACHIEV_SPLIT_PERSONALITY, TYPE_ANOMALUS, TYPE_INTENSE_COLD_FAILED, TYPE_KERISTRASZA, TYPE_ORMOROK, TYPE_TELESTRA, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Referenced by boss_anomalusAI::Aggro(), boss_keristraszaAI::Aggro(), boss_telestraAI::Aggro(), boss_ormorokAI::JustDied(), boss_anomalusAI::JustDied(), boss_keristraszaAI::JustDied(), boss_telestraAI::JustDied(), and boss_telestraAI::JustReachedHome().
SetSpecialAchievementCriteria()
void instance_nexus::SetSpecialAchievementCriteria (uint32 uiType, bool bIsMet)
Definition at line 195 of file nexus.cpp.
References m_abAchievCriteria, and MAX_SPECIAL_ACHIEV_CRITS.
Referenced by boss_telestraAI::ReceiveAIEvent(), SetData(), and boss_anomalusAI::SummonedCreatureJustDied().
Field Documentation
m_abAchievCriteria
bool instance_nexus::m_abAchievCriteria[MAX_SPECIAL_ACHIEV_CRITS] private
Definition at line 71 of file nexus.h.
Referenced by CheckAchievementCriteriaMeet(), instance_nexus(), and SetSpecialAchievementCriteria().
m_auiEncounter
uint32 instance_nexus::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 68 of file nexus.h.
Referenced by GetData(), Initialize(), Load(), OnObjectCreate(), and SetData().
m_sIntenseColdFailPlayers
std::set<uint32> instance_nexus::m_sIntenseColdFailPlayers private
Definition at line 73 of file nexus.h.
Referenced by CheckAchievementCriteriaMeet(), and SetData().
m_strInstData
std::string instance_nexus::m_strInstData private
Definition at line 69 of file nexus.h.
Referenced by Save(), and SetData().
The documentation for this class was generated from the following files:
nexus.h
nexus.cpp