CMaNGOS_WoTLK: SqlQueryHolder Class Reference
SqlQueryHolder Class Reference
#include <SqlOperations.h>
Public Member Functions
SqlQueryHolder ()
virtual ~SqlQueryHolder ()
bool SetQuery (size_t index, const char *sql)
bool SetPQuery (size_t index, const char *format,...) ATTR_PRINTF(3
bool void SetSize (size_t size)
QueryResult * GetResult (size_t index)
void SetResult (size_t index, QueryResult *result)
bool Execute (MaNGOS::IQueryCallback *callback, SqlDelayThread *thread, SqlResultQueue *queue)
Private Types
typedef std::pair< const char *, QueryResult * > SqlResultPair
Private Attributes
std::vector< SqlResultPair > m_queries
Friends
class SqlQueryHolderEx
Detailed Description
Definition at line 119 of file SqlOperations.h.
Member Typedef Documentation
SqlResultPair
typedef std::pair<const char*, QueryResult*> SqlQueryHolder::SqlResultPair private
Definition at line 123 of file SqlOperations.h.
Constructor & Destructor Documentation
SqlQueryHolder()
SqlQueryHolder::SqlQueryHolder () inline
Definition at line 126 of file SqlOperations.h.
~SqlQueryHolder()
SqlQueryHolder::~SqlQueryHolder () virtual
if the result was never used, free the resources results used already (getresult called) are expected to be deleted
Definition at line 198 of file SqlOperations.cpp.
References m_queries.
Member Function Documentation
Execute()
bool SqlQueryHolder::Execute (MaNGOS::IQueryCallback * callback, SqlDelayThread * thread, SqlResultQueue * queue)
delay the execution of the queries, sync them with the delay thread which will in turn resync on execution (via the queue) and call back
Definition at line 120 of file SqlOperations.cpp.
References SqlDelayThread::Delay(), and SqlQueryHolderEx.
Referenced by Database::DelayQueryHolder().
GetResult()
QueryResult * SqlQueryHolder::GetResult (size_t index)
the query strings are freed on the first GetResult or in the destructor
when you get a result aways remember to delete it!
Definition at line 175 of file SqlOperations.cpp.
References m_queries.
Referenced by WorldSession::HandlePlayerLogin(), and Player::LoadFromDB().
SetPQuery()
bool SqlQueryHolder::SetPQuery (size_t index, const char * format, ...)
Definition at line 152 of file SqlOperations.cpp.
References MAX_QUERY_LEN, SetQuery(), SIZEFMTD, and sLog.
Referenced by LoginQueryHolder::Initialize().
SetQuery()
bool SqlQueryHolder::SetQuery (size_t index, const char * sql)
not executed yet, just stored (it's not called a holder for nothing)
Definition at line 132 of file SqlOperations.cpp.
References m_queries, mangos_strdup(), SIZEFMTD, and sLog.
Referenced by SetPQuery().
SetResult()
void SqlQueryHolder::SetResult (size_t index, QueryResult * result)
store the result in the holder
Definition at line 191 of file SqlOperations.cpp.
References m_queries.
Referenced by SqlQueryHolderEx::Execute().
SetSize()
void SqlQueryHolder::SetSize (size_t size)
to optimize push_back, reserve the number of queries about to be executed
Definition at line 212 of file SqlOperations.cpp.
References m_queries.
Referenced by LoginQueryHolder::Initialize().
Friends And Related Function Documentation
SqlQueryHolderEx
friend class SqlQueryHolderEx friend
Definition at line 121 of file SqlOperations.h.
Referenced by Execute().
Field Documentation
m_queries
std::vector<SqlResultPair> SqlQueryHolder::m_queries private
Definition at line 124 of file SqlOperations.h.
Referenced by SqlQueryHolderEx::Execute(), GetResult(), SetQuery(), SetResult(), SetSize(), and ~SqlQueryHolder().
The documentation for this class was generated from the following files:
SqlOperations.h
SqlOperations.cpp