CMaNGOS_WoTLK: FreezeDetectorRunnable Class Reference
FreezeDetectorRunnable Class Reference
Public Member Functions
FreezeDetectorRunnable ()
void SetDelayTime (uint32 t)
void run (void)
Public Member Functions inherited from MaNGOS::Runnable
virtual ~Runnable ()
void incReference ()
void decReference ()
Data Fields
uint32 m_loops
uint32 m_lastchange
uint32 w_loops
uint32 w_lastchange
uint32 _delaytime
Detailed Description
Definition at line 58 of file Master.cpp.
Constructor & Destructor Documentation
FreezeDetectorRunnable()
FreezeDetectorRunnable::FreezeDetectorRunnable () inline
Definition at line 61 of file Master.cpp.
References _delaytime.
Member Function Documentation
run()
void FreezeDetectorRunnable::run (void) inline virtual
Implements MaNGOS::Runnable.
Definition at line 66 of file Master.cpp.
References _delaytime, WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), World::IsStopped(), m_lastchange, m_loops, World::m_worldLoopCounter, MaNGOS::Thread::Sleep(), sLog, w_lastchange, and w_loops.
SetDelayTime()
void FreezeDetectorRunnable::SetDelayTime (uint32 t) inline
Definition at line 65 of file Master.cpp.
References _delaytime.
Referenced by Master::Run().
Field Documentation
_delaytime
uint32 FreezeDetectorRunnable::_delaytime
Definition at line 64 of file Master.cpp.
Referenced by FreezeDetectorRunnable(), run(), and SetDelayTime().
m_lastchange
uint32 FreezeDetectorRunnable::m_lastchange
Definition at line 62 of file Master.cpp.
Referenced by run().
m_loops
uint32 FreezeDetectorRunnable::m_loops
Definition at line 62 of file Master.cpp.
Referenced by run().
w_lastchange
uint32 FreezeDetectorRunnable::w_lastchange
Definition at line 63 of file Master.cpp.
Referenced by run().
w_loops
uint32 FreezeDetectorRunnable::w_loops
Definition at line 63 of file Master.cpp.
Referenced by run().
The documentation for this class was generated from the following file:
Master.cpp