CMaNGOS_WoTLK: Master Class Reference
Master Class Reference
Mangos Daemon
Start the server.
#include <Master.h>
Public Member Functions
int Run ()
Main function.
Static Public Attributes
static volatile bool m_canBeKilled = false
Private Member Functions
bool _StartDB ()
Initialize connection to the databases.
void _HookSignals ()
Define hook '_OnSignal' for all termination signals.
void _UnhookSignals ()
Unhook the signals before leaving.
void clearOnlineAccounts ()
Clear 'online' status for all accounts with characters in this realm.
Static Private Member Functions
static void _OnSignal (int s)
Handle termination signals.
Detailed Description
Start the server.
Definition at line 30 of file Master.h.
Member Function Documentation
_HookSignals()
void Master::_HookSignals () private
Define hook '_OnSignal' for all termination signals.
Definition at line 506 of file Master.cpp.
References _OnSignal().
Referenced by Run().
_OnSignal()
void Master::_OnSignal (int s) static private
Handle termination signals.
Definition at line 479 of file Master.cpp.
References m_canBeKilled, RESTART_EXIT_CODE, SHUTDOWN_EXIT_CODE, and World::StopNow().
Referenced by _HookSignals().
_StartDB()
bool Master::_StartDB () private
Initialize connection to the databases.
Get world database info from configuration file
Initialise the world database
Wait for already started DB delay threads to end
Wait for already started DB delay threads to end
Initialise the Character database
Wait for already started DB delay threads to end
Wait for already started DB delay threads to end
Get login database info from configuration file
Wait for already started DB delay threads to end
Initialise the login database
Wait for already started DB delay threads to end
Wait for already started DB delay threads to end
Get logs database info from configuration file
Wait for already started DB delay threads to end
Initialise the logs database
Wait for already started DB delay threads to end
Wait for already started DB delay threads to end
Get the realm Id from the configuration file
Wait for already started DB delay threads to end
Clean the database before starting
Definition at line 310 of file Master.cpp.
References CharacterDatabase, Database::CheckRequiredField(), clearOnlineAccounts(), Database::HaltDelayThread(), Database::Initialize(), LoginDatabase, LogsDatabase, realmID, REVISION_DB_CHARACTERS, REVISION_DB_LOGS, REVISION_DB_MANGOS, REVISION_DB_REALMD, sConfig, sLog, sWorld, and WorldDatabase.
Referenced by Run().
_UnhookSignals()
void Master::_UnhookSignals () private
Unhook the signals before leaving.
Definition at line 516 of file Master.cpp.
Referenced by Run().
clearOnlineAccounts()
void Master::clearOnlineAccounts () private
Clear 'online' status for all accounts with characters in this realm.
Todo:
Only accounts with characters logged on this realm should have online status reset. Move the online column from 'account' to 'realmcharacters'?
Definition at line 466 of file Master.cpp.
References CharacterDatabase, Database::Execute(), LoginDatabase, Database::PExecute(), and realmID.
Referenced by _StartDB(), and Run().
Run()
int Master::Run ()
Main function.
worldd PID file creation
Start the databases
Initialize the World
Catch termination signals
Launch WorldRunnable thread
Launch CliRunnable thread
Handle affinity for multiple processors and process priority on Windows
Start up freeze catcher thread
Stop freeze protection before shutdown tasks
Set server offline in realmlist
Remove signal handling before leaving
Clean account database before leaving
Wait for DB delay threads to end
Exit the process with specified return value
Definition at line 99 of file Master.cpp.
References _HookSignals(), _StartDB(), _UnhookSignals(), AcceptableClientBuildsListStr(), Database::AllowAsyncTransactions(), CharacterDatabase, clearOnlineAccounts(), CONFIG_UINT32_PORT_WORLD, CreatePIDFile(), MaNGOS::Thread::destroy(), detachDaemon(), Database::DirectPExecute(), Database::escape_string(), World::GetExitCode(), Database::HaltDelayThread(), World::IsStopped(), LoginDatabase, LogsDatabase, m_canBeKilled, MaNGOS::Priority_Highest, REALM_FLAG_OFFLINE, realmID, sConfig, FreezeDetectorRunnable::SetDelayTime(), MaNGOS::Thread::setPriority(), sLog, sMassMailMgr, sWorld, MaNGOS::Thread::wait(), Log::WaitBeforeContinueIfNeed(), and WorldDatabase.
Field Documentation
m_canBeKilled
volatile bool Master::m_canBeKilled = false static
Definition at line 34 of file Master.h.
Referenced by _OnSignal(), and Run().
The documentation for this class was generated from the following files:
Master.h
Master.cpp