CMaNGOS_WoTLK: BarGoLink Class Reference
BarGoLink Class Reference
#include <ProgressBar.h>
Public Member Functions
BarGoLink (size_t row_count)
~BarGoLink ()
void step ()
Static Public Member Functions
static void SetOutputState (bool on)
Private Member Functions
void init (size_t row_count)
Private Attributes
size_t rec_no
size_t rec_pos
size_t num_rec
size_t indic_len
Static Private Attributes
static bool m_showOutput = true
static char const *const empty = " "
static char const *const full = "*"
Detailed Description
Definition at line 24 of file ProgressBar.h.
Constructor & Destructor Documentation
BarGoLink()
BarGoLink::BarGoLink (size_t row_count) explicit
Definition at line 33 of file ProgressBar.cpp.
References init().
~BarGoLink()
BarGoLink::~BarGoLink ()
Definition at line 38 of file ProgressBar.cpp.
References m_showOutput.
Member Function Documentation
init()
void BarGoLink::init (size_t row_count) private
Definition at line 47 of file ProgressBar.cpp.
References empty, indic_len, m_showOutput, num_rec, rec_no, and rec_pos.
Referenced by BarGoLink().
SetOutputState()
void BarGoLink::SetOutputState (bool on) static
Definition at line 103 of file ProgressBar.cpp.
References m_showOutput.
Referenced by main().
step()
void BarGoLink::step ()
Definition at line 71 of file ProgressBar.cpp.
References empty, full, indic_len, m_showOutput, num_rec, rec_no, and rec_pos.
Referenced by CharacterDatabaseCleaner::CheckUnique(), SpellMgr::CheckUsedSpells(), MapPersistentStateManager::CleanupInstances(), BattleGroundMgr::CreateInitialBattleGrounds(), AuctionHouseBot::FillUintVectorFromQuery(), ScriptDevAIMgr::Initialize(), CombatConditionMgr::Load(), UnitConditionMgr::Load(), WaypointManager::Load(), WorldStateExpressionMgr::Load(), SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load(), ObjectMgr::LoadAccessRequirements(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), AchievementGlobalMgr::LoadAchievementReferenceList(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadArenaTeams(), AuctionHouseMgr::LoadAuctionItems(), AuctionHouseMgr::LoadAuctions(), BattleGroundMgr::LoadBattleEventIndexes(), BattleGroundMgr::LoadBattleMastersEntry(), ObjectMgr::LoadBroadcastText(), ObjectMgr::LoadBroadcastTextLocales(), CalendarMgr::LoadCalendarsFromDB(), AchievementGlobalMgr::LoadCompletedAchievements(), ObjectMgr::LoadCorpses(), ObjectMgr::LoadCreatureClassLvlStats(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatureLocales(), ObjectMgr::LoadCreatureModelRace(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpawnDataTemplates(), ObjectMgr::LoadCreatureSpawnEntry(), LoadDBC(), ScriptDevAIMgr::LoadEventIdScripts(), ObjectMgr::LoadExplorationBaseXP(), ObjectMgr::LoadFishingBaseSkillLevel(), CreatureLinkingMgr::LoadFromDB(), GameEventMgr::LoadFromDB(), PoolManager::LoadFromDB(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameObjectLocales(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGameObjectSpawnEntry(), ObjectMgr::LoadGameObjectTemplateAddons(), ObjectMgr::LoadGameTele(), GMTicketMgr::LoadGMTickets(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadGossipMenuItemsLocales(), ObjectMgr::LoadGossipText(), ObjectMgr::LoadGossipTextLocales(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), GuildMgr::LoadGuilds(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemLocales(), ObjectMgr::LoadItemRequiredTarget(), LFGMgr::LoadLFGDungeons(), LootStore::LoadLootTable(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadMangosStrings(), ObjectMgr::LoadNpcGossips(), ObjectMgr::LoadNPCSpellClickSpells(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPetNames(), ObjectMgr::LoadPetNumber(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadPointOfInterestLocales(), ObjectMgr::LoadPointsOfInterest(), ObjectMgr::LoadQuestAreaTriggers(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuestLocales(), ObjectMgr::LoadQuestPOI(), ObjectMgr::LoadQuestRelationsHelper(), ObjectMgr::LoadQuests(), LoadRandomEnchantmentsTable(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ObjectMgr::LoadReservedPlayersNames(), AchievementGlobalMgr::LoadRewardLocales(), AchievementGlobalMgr::LoadRewards(), LFGMgr::LoadRewards(), ScriptDevAIMgr::LoadScriptNames(), ScriptMgr::LoadScripts(), SystemMgr::LoadScriptWaypoints(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSkillLineAbilityMaps(), SpellMgr::LoadSkillRaceClassInfoMap(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellTargetPositions(), SpellMgr::LoadSpellThreats(), ScriptMgr::LoadStringIds(), ObjectMgr::LoadTavernAreaTriggers(), ObjectMgr::LoadTaxiShortcuts(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), ObjectMgr::LoadTrainers(), MapManager::LoadTransports(), ObjectMgr::LoadVehicleSeatParameters(), ObjectMgr::LoadVendors(), WeatherMgr::LoadWeatherZoneChances(), ObjectMgr::LoadWorldStateNames(), ObjectMgr::PackGroupIds(), MapPersistentStateManager::PackInstances(), ObjectMgr::ReturnOrDeleteOldMails(), PlayerbotAI::TalentSpecDBContainsError(), and Log::WaitBeforeContinueIfNeed().
Field Documentation
empty
char const *const BarGoLink::empty = " " static private
Definition at line 38 of file ProgressBar.h.
Referenced by init(), and step().
full
char const *const BarGoLink::full = "*" static private
Definition at line 39 of file ProgressBar.h.
Referenced by step().
indic_len
size_t BarGoLink::indic_len private
Definition at line 44 of file ProgressBar.h.
Referenced by init(), and step().
m_showOutput
bool BarGoLink::m_showOutput = true static private
Definition at line 37 of file ProgressBar.h.
Referenced by init(), SetOutputState(), step(), and ~BarGoLink().
num_rec
size_t BarGoLink::num_rec private
Definition at line 43 of file ProgressBar.h.
Referenced by init(), and step().
rec_no
size_t BarGoLink::rec_no private
Definition at line 41 of file ProgressBar.h.
Referenced by init(), and step().
rec_pos
size_t BarGoLink::rec_pos private
Definition at line 42 of file ProgressBar.h.
Referenced by init(), and step().
The documentation for this class was generated from the following files:
ProgressBar.h
ProgressBar.cpp