CMaNGOS_WoTLK: SqlQuery Class Reference
SqlQuery Class Reference
#include <SqlOperations.h>
Public Member Functions
SqlQuery (const char *sql, MaNGOS::IQueryCallback *callback, SqlResultQueue *queue)
bool Execute (SqlConnection *conn) override
-— ASYNC QUERIES -—
Public Member Functions inherited from SqlOperation
virtual void OnRemove ()
virtual ~SqlOperation ()
Private Attributes
std::vector< char > m_sql
MaNGOS::IQueryCallback *const m_callback
SqlResultQueue *const m_queue
Detailed Description
Definition at line 102 of file SqlOperations.h.
Constructor & Destructor Documentation
SqlQuery()
SqlQuery::SqlQuery (const char * sql, MaNGOS::IQueryCallback * callback, SqlResultQueue * queue) inline
Definition at line 110 of file SqlOperations.h.
References m_sql.
Member Function Documentation
Execute()
bool SqlQuery::Execute (SqlConnection * conn) override virtual
-— ASYNC QUERIES -—
execute the query and store the result in the callback
add the callback to the sql result queue of the thread it originated from
Implements SqlOperation.
Definition at line 87 of file SqlOperations.cpp.
References SqlResultQueue::Add(), LOCK_DB_CONN, m_callback, m_queue, m_sql, SqlConnection::Query(), and MaNGOS::IQueryCallback::SetResult().
Field Documentation
m_callback
MaNGOS::IQueryCallback* const SqlQuery::m_callback private
Definition at line 106 of file SqlOperations.h.
Referenced by Execute().
m_queue
SqlResultQueue* const SqlQuery::m_queue private
Definition at line 107 of file SqlOperations.h.
Referenced by Execute().
m_sql
std::vector<char> SqlQuery::m_sql private
Definition at line 105 of file SqlOperations.h.
Referenced by Execute(), and SqlQuery().
The documentation for this class was generated from the following files:
SqlOperations.h
SqlOperations.cpp