CMaNGOS_WoTLK: instance_trial_of_the_champion Class Reference
instance_trial_of_the_champion Class Reference
#include <trial_of_the_champion.h>
Public Member Functions
instance_trial_of_the_champion (Map *pMap)
void Initialize () override
void OnPlayerEnter (Player *pPlayer) override
void OnCreatureCreate (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void OnCreatureDeath (Creature *pCreature) override
void OnCreatureEvade (Creature *pCreature) override
void OnCreatureDespawn (Creature *pCreature) override
void OnCreatureEnterCombat (Creature *pCreature) override
void SetData (uint32 uiType, uint32 uiData) override
uint32 GetData (uint32 uiType) const override
uint32 GetPlayerTeam () const
const char * Save () const override
void Load (const char *chrIn) override
void DoPrepareChampions (bool bSkipIntro)
void MoveChampionToHome (Creature *pChampion)
void InformChampionReachHome ()
void DoSendChampionsToExit ()
void DoSetChamptionsInCombat (Unit *pTarget)
void SetHadWorseAchievFailed ()
void DoPrepareArgentChallenge ()
void DoPrepareBlackKnight ()
bool CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const *pSource, Unit const *pTarget, uint32 uiMiscValue1) const override
uint32 GetMountEntryForChampion () const
bool IsArenaChallengeComplete (uint32 uiType)
void Update (const uint32 diff) override
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Private Member Functions
void JustDidDialogueStep (int32 iEntry) override
Will be called when a dialogue step was done.
void DoSummonHeraldIfNeeded (Unit *pSummoner)
void DoSendNextArenaWave ()
void DoCleanupArenaOnWipe ()
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
Team m_uiTeam
uint32 m_uiHeraldEntry
uint32 m_uiGrandChampionEntry
uint32 m_uiIntroTimer
uint32 m_uiIntroStage
uint32 m_uiArenaStage
uint32 m_uiGateResetTimer
uint32 m_uiChampionsCount
uint32 m_uiChampionsTimer
bool m_bSkipIntro
bool m_bHadWorseAchiev
ObjectGuid m_ArenaChampionsGuids [MAX_CHAMPIONS_ARENA]
ObjectGuid m_ArenaMountsGuids [MAX_CHAMPIONS_ARENA]
std::vector< uint8 > m_vChampionsIndex
GuidVector m_vAllianceTriggersGuids
GuidVector m_vHordeTriggersGuids
GuidList m_lArenaMountsGuids
GuidList m_lArgentTrashGuids
GuidSet m_sArenaHelpersGuids [MAX_CHAMPIONS_ARENA]
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 273 of file trial_of_the_champion.h.
Constructor & Destructor Documentation
instance_trial_of_the_champion()
instance_trial_of_the_champion::instance_trial_of_the_champion (Map * pMap)
Definition at line 152 of file instance_trial_of_the_champion.cpp.
References Initialize().
Member Function Documentation
CheckAchievementCriteriaMeet()
bool instance_trial_of_the_champion::CheckAchievementCriteriaMeet (uint32 uiCriteriaId, Player const * pSource, Unit const * pTarget, uint32 uiMiscValue1) const override virtual
Reimplemented from InstanceData.
Definition at line 465 of file instance_trial_of_the_champion.cpp.
References ACHIEV_CRIT_HAD_WORSE, and m_bHadWorseAchiev.
DoCleanupArenaOnWipe()
void instance_trial_of_the_champion::DoCleanupArenaOnWipe () private
Definition at line 680 of file instance_trial_of_the_champion.cpp.
References Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_ArenaChampionsGuids, m_ArenaMountsGuids, m_sArenaHelpersGuids, m_uiHeraldEntry, MAX_CHAMPIONS_ARENA, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by SetData().
DoPrepareArgentChallenge()
void instance_trial_of_the_champion::DoPrepareArgentChallenge () inline
Definition at line 306 of file trial_of_the_champion.h.
References NPC_ARGENT_MONK, and DialogueHelper::StartNextDialogueText().
Referenced by GossipSelect_npc_toc_herald().
DoPrepareBlackKnight()
void instance_trial_of_the_champion::DoPrepareBlackKnight () inline
Definition at line 307 of file trial_of_the_champion.h.
References DialogueHelper::StartNextDialogueText(), and TYPE_BLACK_KNIGHT.
Referenced by GossipSelect_npc_toc_herald().
DoPrepareChampions()
void instance_trial_of_the_champion::DoPrepareChampions (bool bSkipIntro)
Definition at line 709 of file instance_trial_of_the_champion.cpp.
References aHeraldPositions, ScriptedInstance::GetSingleCreatureFromStorage(), m_bSkipIntro, m_uiHeraldEntry, SAY_TIRION_CHALLENGE_WELCOME, DialogueHelper::StartNextDialogueText(), and TYPE_ARENA_CHALLENGE.
Referenced by GossipSelect_npc_toc_herald().
DoSendChampionsToExit()
void instance_trial_of_the_champion::DoSendChampionsToExit ()
Definition at line 788 of file instance_trial_of_the_champion.cpp.
References aChampsPositions, DONE, Map::GetCreature(), GetData(), InstanceData::instance, m_ArenaChampionsGuids, POINT_ID_EXIT, SPELL_CHAMPION_KILL_CREDIT, TRIGGERED_OLD_TRIGGERED, TYPE_GRAND_CHAMPIONS, and UNIT_STAND_STATE_STAND.
Referenced by SetData().
DoSendNextArenaWave()
void instance_trial_of_the_champion::DoSendNextArenaWave () private
Definition at line 636 of file instance_trial_of_the_champion.cpp.
References WorldObject::GetContactPoint(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, INTERACTION_DISTANCE, m_ArenaChampionsGuids, m_ArenaMountsGuids, m_sArenaHelpersGuids, m_uiArenaStage, MAX_CHAMPIONS_ARENA, NPC_WORLD_TRIGGER, POINT_ID_COMBAT, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Referenced by OnCreatureDeath(), and SetData().
DoSetChamptionsInCombat()
void instance_trial_of_the_champion::DoSetChamptionsInCombat (Unit * pTarget)
Definition at line 807 of file instance_trial_of_the_champion.cpp.
References Map::GetCreature(), InstanceData::instance, and m_ArenaChampionsGuids.
Referenced by trial_companion_commonAI::Aggro().
DoSummonHeraldIfNeeded()
void instance_trial_of_the_champion::DoSummonHeraldIfNeeded (Unit * pSummoner) private
Definition at line 617 of file instance_trial_of_the_champion.cpp.
References aHeraldPositions, ALLIANCE, aTrialChampionsMounts, DONE, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiHeraldEntry, m_uiTeam, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_GRAND_CHAMPIONS.
Referenced by OnPlayerEnter().
GetData()
uint32 instance_trial_of_the_champion::GetData (uint32 uiType) const override virtual
Reimplemented from InstanceData.
Definition at line 435 of file instance_trial_of_the_champion.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by trial_companion_commonAI::Aggro(), boss_champion_mageAI::AttackStart(), boss_champion_hunterAI::AttackStart(), trial_companion_commonAI::DamageTaken(), DoSendChampionsToExit(), DoSummonHeraldIfNeeded(), GossipHello_npc_toc_herald(), IsArenaChallengeComplete(), argent_champion_commonAI::JustReachedHome(), trial_companion_commonAI::JustReachedHome(), trial_companion_commonAI::MovementInform(), OnCreatureDespawn(), OnCreatureEvade(), trial_companion_commonAI::Reset(), and trial_companion_commonAI::UpdateAI().
GetMountEntryForChampion()
uint32 instance_trial_of_the_champion::GetMountEntryForChampion () const inline
Definition at line 311 of file trial_of_the_champion.h.
References ALLIANCE, m_uiTeam, NPC_BATTLEWORG_ALLIANCE, and NPC_WARHORSE_HORDE.
Referenced by trial_companion_commonAI::DoUseNearbyMountIfCan(), and trial_companion_commonAI::MovementInform().
GetPlayerTeam()
uint32 instance_trial_of_the_champion::GetPlayerTeam () const inline
Definition at line 293 of file trial_of_the_champion.h.
References m_uiTeam.
Referenced by boss_black_knightAI::Aggro().
InformChampionReachHome()
void instance_trial_of_the_champion::InformChampionReachHome ()
Definition at line 751 of file instance_trial_of_the_champion.cpp.
References ALLIANCE, WorldObject::GetAngle(), Map::GetCreature(), WorldObject::GetNearPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, M_PI_F, m_sArenaHelpersGuids, m_uiIntroStage, m_uiIntroTimer, m_uiTeam, m_vAllianceTriggersGuids, m_vChampionsIndex, m_vHordeTriggersGuids, MAX_CHAMPIONS_ARENA, NPC_WORLD_TRIGGER, and POINT_ID_HOME.
Referenced by npc_champion_mountAI::MovementInform().
Initialize()
void instance_trial_of_the_champion::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 168 of file instance_trial_of_the_champion.cpp.
References DialogueHelper::InitializeDialogueHelper(), m_auiEncounter, m_vAllianceTriggersGuids, m_vHordeTriggersGuids, and MAX_CHAMPIONS_AVAILABLE.
Referenced by instance_trial_of_the_champion().
IsArenaChallengeComplete()
bool instance_trial_of_the_champion::IsArenaChallengeComplete (uint32 uiType)
Definition at line 587 of file instance_trial_of_the_champion.cpp.
References DONE, Map::GetCreature(), GetData(), InstanceData::instance, m_ArenaChampionsGuids, SPECIAL, TYPE_ARENA_CHALLENGE, TYPE_GRAND_CHAMPIONS, UNIT_STAND_STATE_DEAD, and UNIT_STAND_STATE_KNEEL.
Referenced by trial_companion_commonAI::DamageTaken(), and trial_companion_commonAI::DoUseNearbyMountIfCan().
JustDidDialogueStep()
void instance_trial_of_the_champion::JustDidDialogueStep (int32) override private virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 816 of file instance_trial_of_the_champion.cpp.
References aArgentChallengeHelpers, aHeraldPositions, aKnightPositions, DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), EMOTE_ALLIANCE_ARGENT_CHAMPION, EMOTE_HORDE_ARGENT_CHAMPION, ArgentChallengeData::fO, FORCED_MOVEMENT_NONE, ArgentChallengeData::fX, ArgentChallengeData::fY, ArgentChallengeData::fZ, ScriptedInstance::GetSingleCreatureFromStorage(), GO_MAIN_GATE, m_uiGateResetTimer, m_uiGrandChampionEntry, m_uiHeraldEntry, m_uiIntroStage, m_uiIntroTimer, MAX_ARGENT_TRASH, NPC_ARGENT_MONK, NPC_BLACK_KNIGHT, NPC_BLACK_KNIGHT_GRYPHON, NPC_EADRIC, NPC_JAEREN_SUNSWORN, NPC_PALETRESS, NPC_SPECTATOR_ALLIANCE, NPC_SPECTATOR_HORDE, NPC_TIRION_FORDRING, NPC_WORLD_TRIGGER, POINT_ID_CENTER, POINT_ID_EXIT, SAY_BLACK_KNIGHT_INTRO_1, SAY_BLACK_KNIGHT_INTRO_3, SAY_EADRIC_INTRO, SAY_HERALD_ALLIANCE_CHALLENGE, SAY_HERALD_BLACK_KNIGHT_SPAWN, SAY_HERALD_EADRIC, SAY_HERALD_HORDE_CHALLENGE, SAY_HERALD_PALETRESS, SAY_PALETRESS_INTRO_1, SAY_PALETRESS_INTRO_2, SAY_TIRION_ARGENT_CHAMPION_BEGIN, SAY_TIRION_ARGENT_CHAMPION_COMPLETE, SOUND_ID_CHALLENGE, SPELL_ARGENT_GET_PLAYER_COUNT, SPELL_ARGENT_HERALD_FEIGN_DEATH, SPELL_ARGENT_SUMMON_BOSS_4, SPELL_DEATHS_RESPITE, SPELL_HERALD_FACE_DARK_KNIGHT, SPELL_RIDE_VEHICLE_HARDCODED, SPELL_SPECTATOR_FORCE_CHEER, SPELL_SPECTATOR_FORCE_CHEER_2, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPE_ARENA_CHALLENGE, TYPE_ARGENT_CHAMPION, TYPE_BLACK_KNIGHT, ArgentChallengeData::uiEntry, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Load()
void instance_trial_of_the_champion::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 443 of file instance_trial_of_the_champion.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
MoveChampionToHome()
void instance_trial_of_the_champion::MoveChampionToHome (Creature * pChampion)
Definition at line 728 of file instance_trial_of_the_champion.cpp.
References aHeraldPositions, ALLIANCE, Map::GetCreature(), Unit::GetMotionMaster(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_uiHeraldEntry, m_uiIntroStage, m_uiTeam, m_vAllianceTriggersGuids, m_vChampionsIndex, m_vHordeTriggersGuids, MAX_CHAMPIONS_ARENA, MotionMaster::MovePoint(), POINT_ID_HOME, and Creature::SetWalk().
Referenced by npc_champion_mountAI::MovementInform().
OnCreatureCreate()
void instance_trial_of_the_champion::OnCreatureCreate (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 205 of file instance_trial_of_the_champion.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), m_lArenaMountsGuids, m_lArgentTrashGuids, ScriptedInstance::m_npcEntryGuidStore, m_vAllianceTriggersGuids, m_vHordeTriggersGuids, NPC_ALLIANCE_HUNTER, NPC_ALLIANCE_MAGE, NPC_ALLIANCE_ROGUE, NPC_ALLIANCE_SHAMAN, NPC_ALLIANCE_WARRIOR, NPC_ARELAS_BRIGHTSTAR, NPC_ARGENT_LIGHTWIELDER, NPC_ARGENT_MONK, NPC_ARGENT_PRIESTESS, NPC_BATTLEWORG_ALLIANCE, NPC_BATTLEWORG_HORDE, NPC_BLACK_KNIGHT, NPC_BLACK_KNIGHT_GRYPHON, NPC_EADRIC, NPC_GARROSH, NPC_HORDE_HUNTER, NPC_HORDE_MAGE, NPC_HORDE_ROGUE, NPC_HORDE_SHAMAN, NPC_HORDE_WARRIOR, NPC_JAEREN_SUNSWORN, NPC_PALETRESS, NPC_SPECTATOR_ALLIANCE, NPC_SPECTATOR_BLOOD_ELF, NPC_SPECTATOR_DRAENEI, NPC_SPECTATOR_DWARF, NPC_SPECTATOR_GENERIC, NPC_SPECTATOR_GNOME, NPC_SPECTATOR_HORDE, NPC_SPECTATOR_HUMAN, NPC_SPECTATOR_NIGHT_ELF, NPC_SPECTATOR_ORC, NPC_SPECTATOR_TAUREN, NPC_SPECTATOR_TROLL, NPC_SPECTATOR_UNDEAD, NPC_THRALL, NPC_TIRION_FORDRING, NPC_VARIAN_WRYNN, NPC_WARHORSE_ALLIANCE, NPC_WARHORSE_HORDE, and NPC_WORLD_TRIGGER.
OnCreatureDeath()
void instance_trial_of_the_champion::OnCreatureDeath (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 479 of file instance_trial_of_the_champion.cpp.
References DoSendNextArenaWave(), FACTION_CHAMPION_HOSTILE, Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_lArgentTrashGuids, m_sArenaHelpersGuids, m_uiArenaStage, m_uiGrandChampionEntry, NPC_ALLIANCE_HUNTER_CHAMPION, NPC_ALLIANCE_MAGE_CHAMPION, NPC_ALLIANCE_ROGUE_CHAMPION, NPC_ALLIANCE_SHAMAN_CHAMPION, NPC_ALLIANCE_WARRIOR_CHAMPION, NPC_ARGENT_LIGHTWIELDER, NPC_ARGENT_MONK, NPC_ARGENT_PRIESTESS, NPC_HORDE_HUNTER_CHAMPION, NPC_HORDE_MAGE_CHAMPION, NPC_HORDE_ROGUE_CHAMPION, NPC_HORDE_SHAMAN_CHAMPION, NPC_HORDE_WARRIOR_CHAMPION, POINT_ID_CENTER, and TEMPFACTION_NONE.
OnCreatureDespawn()
void instance_trial_of_the_champion::OnCreatureDespawn (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 555 of file instance_trial_of_the_champion.cpp.
References DONE, GetData(), Object::GetEntry(), Creature::GetRespawnCoord(), ScriptedInstance::GetSingleCreatureFromStorage(), m_uiHeraldEntry, NPC_BATTLEWORG_ALLIANCE, NPC_BATTLEWORG_HORDE, NPC_WARHORSE_ALLIANCE, NPC_WARHORSE_HORDE, TEMPSPAWN_DEAD_DESPAWN, and TYPE_ARENA_CHALLENGE.
OnCreatureEnterCombat()
void instance_trial_of_the_champion::OnCreatureEnterCombat (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 577 of file instance_trial_of_the_champion.cpp.
References Object::GetEntry(), IN_PROGRESS, NPC_BLACK_KNIGHT, SAY_BLACK_KNIGHT_AGGRO, SetData(), DialogueHelper::StartNextDialogueText(), and TYPE_BLACK_KNIGHT.
OnCreatureEvade()
void instance_trial_of_the_champion::OnCreatureEvade (Creature * pCreature) override virtual
Reimplemented from InstanceData.
Definition at line 525 of file instance_trial_of_the_champion.cpp.
References FAIL, GetData(), Object::GetEntry(), IN_PROGRESS, NPC_ALLIANCE_HUNTER, NPC_ALLIANCE_HUNTER_CHAMPION, NPC_ALLIANCE_MAGE, NPC_ALLIANCE_MAGE_CHAMPION, NPC_ALLIANCE_ROGUE, NPC_ALLIANCE_ROGUE_CHAMPION, NPC_ALLIANCE_SHAMAN, NPC_ALLIANCE_SHAMAN_CHAMPION, NPC_ALLIANCE_WARRIOR, NPC_ALLIANCE_WARRIOR_CHAMPION, NPC_HORDE_HUNTER, NPC_HORDE_HUNTER_CHAMPION, NPC_HORDE_MAGE, NPC_HORDE_MAGE_CHAMPION, NPC_HORDE_ROGUE, NPC_HORDE_ROGUE_CHAMPION, NPC_HORDE_SHAMAN, NPC_HORDE_SHAMAN_CHAMPION, NPC_HORDE_WARRIOR, NPC_HORDE_WARRIOR_CHAMPION, SetData(), and TYPE_ARENA_CHALLENGE.
OnObjectCreate()
void instance_trial_of_the_champion::OnObjectCreate (GameObject * pGo) override virtual
Reimplemented from InstanceData.
Definition at line 301 of file instance_trial_of_the_champion.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_CHAMPIONS_LOOT, GO_CHAMPIONS_LOOT_H, GO_EADRIC_LOOT, GO_EADRIC_LOOT_H, GO_MAIN_GATE, GO_NORTH_GATE, GO_PALETRESS_LOOT, GO_PALETRESS_LOOT_H, and ScriptedInstance::m_goEntryGuidStore.
OnPlayerEnter()
void instance_trial_of_the_champion::OnPlayerEnter (Player * pPlayer) override virtual
Reimplemented from InstanceData.
Definition at line 177 of file instance_trial_of_the_champion.cpp.
References ALLIANCE, DoSummonHeraldIfNeeded(), GetRandomGenerator(), Player::GetTeam(), m_uiGrandChampionEntry, m_uiHeraldEntry, m_uiTeam, m_vChampionsIndex, MAX_CHAMPIONS_AVAILABLE, NPC_ARELAS_BRIGHTSTAR, NPC_EADRIC, NPC_JAEREN_SUNSWORN, NPC_PALETRESS, DialogueHelper::SetDialogueSide(), and urand().
Save()
const char* instance_trial_of_the_champion::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 295 of file trial_of_the_champion.h.
References m_strInstData.
SetData()
void instance_trial_of_the_champion::SetData (uint32 uiType, uint32 uiData) override virtual
Reimplemented from InstanceData.
Definition at line 321 of file instance_trial_of_the_champion.cpp.
References aHeraldPositions, DoCleanupArenaOnWipe(), DONE, ScriptedInstance::DoRespawnGameObject(), DoSendChampionsToExit(), DoSendNextArenaWave(), ScriptedInstance::DoUseDoorOrButton(), FAIL, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_CHAMPIONS_LOOT, GO_CHAMPIONS_LOOT_H, GO_EADRIC_LOOT, GO_EADRIC_LOOT_H, GO_NORTH_GATE, GO_PALETRESS_LOOT, GO_PALETRESS_LOOT_H, IN_PROGRESS, InstanceData::instance, Map::IsRegularDifficulty(), m_auiEncounter, m_bHadWorseAchiev, m_lArenaMountsGuids, m_strInstData, m_uiArenaStage, m_uiChampionsCount, m_uiChampionsTimer, m_uiGrandChampionEntry, m_uiHeraldEntry, MAX_CHAMPIONS_ARENA, MINUTE, NOT_STARTED, NPC_ARELAS_BRIGHTSTAR, NPC_EADRIC, NPC_PALETRESS, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, POINT_ID_MOUNT, InstanceData::SaveToDB(), script_error_log(), SPECIAL, SPELL_SPECTATOR_FORCE_CHEER, DialogueHelper::StartNextDialogueText(), TYPE_ARENA_CHALLENGE, TYPE_ARGENT_CHAMPION, TYPE_BLACK_KNIGHT, TYPE_GRAND_CHAMPIONS, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by argent_champion_commonAI::Aggro(), trial_companion_commonAI::Aggro(), argent_champion_commonAI::DamageTaken(), trial_companion_commonAI::DamageTaken(), trial_companion_commonAI::DoUseNearbyMountIfCan(), boss_black_knightAI::JustDied(), argent_champion_commonAI::JustReachedHome(), boss_black_knightAI::JustReachedHome(), trial_companion_commonAI::JustReachedHome(), trial_companion_commonAI::MovementInform(), OnCreatureEnterCombat(), OnCreatureEvade(), and Update().
SetHadWorseAchievFailed()
void instance_trial_of_the_champion::SetHadWorseAchievFailed () inline
Definition at line 304 of file trial_of_the_champion.h.
References m_bHadWorseAchiev.
Referenced by npc_black_knight_ghoulAI::SpellHitTarget().
Update()
void instance_trial_of_the_champion::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 995 of file instance_trial_of_the_champion.cpp.
References aAllianceChampions, aChampsPositions, aHordeChampions, aIntroPositions, ALLIANCE, Unit::CastSpell(), DialogueHelper::DialogueUpdate(), DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), FORCED_MOVEMENT_NONE, WorldObject::GetAngle(), WorldObject::GetContactPoint(), Map::GetCreature(), WorldObject::GetNearPoint(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_MAIN_GATE, IN_PROGRESS, InstanceData::instance, INTERACTION_DISTANCE, m_ArenaChampionsGuids, m_ArenaMountsGuids, m_bSkipIntro, M_PI_F, m_sArenaHelpersGuids, m_uiChampionsTimer, m_uiGateResetTimer, m_uiHeraldEntry, m_uiIntroStage, m_uiIntroTimer, m_uiTeam, m_vAllianceTriggersGuids, m_vChampionsIndex, m_vHordeTriggersGuids, MAX_CHAMPIONS_ARENA, NPC_TIRION_FORDRING, NPC_WORLD_TRIGGER, POINT_ID_CENTER, SAY_TIRION_CHALLENGE_BEGIN, SetData(), Unit::SetFacingToObject(), SPELL_ARGENT_SUMMON_CHAMPION_1, SPELL_ARGENT_SUMMON_CHAMPION_2, SPELL_ARGENT_SUMMON_CHAMPION_3, SPELL_RIDE_VEHICLE_HARDCODED, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_ARENA_CHALLENGE, ChampionsData::uiChampion, ChampionsData::uiEntry, and ChampionsData::uiMount.
Field Documentation
m_ArenaChampionsGuids
ObjectGuid instance_trial_of_the_champion::m_ArenaChampionsGuids[MAX_CHAMPIONS_ARENA] private
Definition at line 341 of file trial_of_the_champion.h.
Referenced by DoCleanupArenaOnWipe(), DoSendChampionsToExit(), DoSendNextArenaWave(), DoSetChamptionsInCombat(), IsArenaChallengeComplete(), and Update().
m_ArenaMountsGuids
ObjectGuid instance_trial_of_the_champion::m_ArenaMountsGuids[MAX_CHAMPIONS_ARENA] private
Definition at line 342 of file trial_of_the_champion.h.
Referenced by DoCleanupArenaOnWipe(), DoSendNextArenaWave(), and Update().
m_auiEncounter
uint32 instance_trial_of_the_champion::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 323 of file trial_of_the_champion.h.
Referenced by GetData(), Initialize(), Load(), and SetData().
m_bHadWorseAchiev
bool instance_trial_of_the_champion::m_bHadWorseAchiev private
Definition at line 339 of file trial_of_the_champion.h.
Referenced by CheckAchievementCriteriaMeet(), SetData(), and SetHadWorseAchievFailed().
m_bSkipIntro
bool instance_trial_of_the_champion::m_bSkipIntro private
Definition at line 338 of file trial_of_the_champion.h.
Referenced by DoPrepareChampions(), and Update().
m_lArenaMountsGuids
GuidList instance_trial_of_the_champion::m_lArenaMountsGuids private
Definition at line 349 of file trial_of_the_champion.h.
Referenced by OnCreatureCreate(), and SetData().
m_lArgentTrashGuids
GuidList instance_trial_of_the_champion::m_lArgentTrashGuids private
Definition at line 350 of file trial_of_the_champion.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_sArenaHelpersGuids
GuidSet instance_trial_of_the_champion::m_sArenaHelpersGuids[MAX_CHAMPIONS_ARENA] private
Definition at line 351 of file trial_of_the_champion.h.
Referenced by DoCleanupArenaOnWipe(), DoSendNextArenaWave(), InformChampionReachHome(), OnCreatureDeath(), and Update().
m_strInstData
std::string instance_trial_of_the_champion::m_strInstData private
Definition at line 324 of file trial_of_the_champion.h.
Referenced by Save(), and SetData().
m_uiArenaStage
uint32 instance_trial_of_the_champion::m_uiArenaStage private
Definition at line 333 of file trial_of_the_champion.h.
Referenced by DoSendNextArenaWave(), OnCreatureDeath(), and SetData().
m_uiChampionsCount
uint32 instance_trial_of_the_champion::m_uiChampionsCount private
Definition at line 335 of file trial_of_the_champion.h.
Referenced by SetData().
m_uiChampionsTimer
uint32 instance_trial_of_the_champion::m_uiChampionsTimer private
Definition at line 336 of file trial_of_the_champion.h.
Referenced by SetData(), and Update().
m_uiGateResetTimer
uint32 instance_trial_of_the_champion::m_uiGateResetTimer private
Definition at line 334 of file trial_of_the_champion.h.
Referenced by JustDidDialogueStep(), and Update().
m_uiGrandChampionEntry
uint32 instance_trial_of_the_champion::m_uiGrandChampionEntry private
Definition at line 329 of file trial_of_the_champion.h.
Referenced by JustDidDialogueStep(), OnCreatureDeath(), OnPlayerEnter(), and SetData().
m_uiHeraldEntry
uint32 instance_trial_of_the_champion::m_uiHeraldEntry private
Definition at line 328 of file trial_of_the_champion.h.
Referenced by DoCleanupArenaOnWipe(), DoPrepareChampions(), DoSummonHeraldIfNeeded(), JustDidDialogueStep(), MoveChampionToHome(), OnCreatureDespawn(), OnPlayerEnter(), SetData(), and Update().
m_uiIntroStage
uint32 instance_trial_of_the_champion::m_uiIntroStage private
Definition at line 332 of file trial_of_the_champion.h.
Referenced by InformChampionReachHome(), JustDidDialogueStep(), MoveChampionToHome(), and Update().
m_uiIntroTimer
uint32 instance_trial_of_the_champion::m_uiIntroTimer private
Definition at line 331 of file trial_of_the_champion.h.
Referenced by InformChampionReachHome(), JustDidDialogueStep(), and Update().
m_uiTeam
Team instance_trial_of_the_champion::m_uiTeam private
Definition at line 326 of file trial_of_the_champion.h.
Referenced by DoSummonHeraldIfNeeded(), GetMountEntryForChampion(), GetPlayerTeam(), InformChampionReachHome(), MoveChampionToHome(), OnPlayerEnter(), and Update().
m_vAllianceTriggersGuids
GuidVector instance_trial_of_the_champion::m_vAllianceTriggersGuids private
Definition at line 346 of file trial_of_the_champion.h.
Referenced by InformChampionReachHome(), Initialize(), MoveChampionToHome(), OnCreatureCreate(), and Update().
m_vChampionsIndex
std::vector<uint8> instance_trial_of_the_champion::m_vChampionsIndex private
Definition at line 344 of file trial_of_the_champion.h.
Referenced by InformChampionReachHome(), MoveChampionToHome(), OnPlayerEnter(), and Update().
m_vHordeTriggersGuids
GuidVector instance_trial_of_the_champion::m_vHordeTriggersGuids private
Definition at line 347 of file trial_of_the_champion.h.
Referenced by InformChampionReachHome(), Initialize(), MoveChampionToHome(), OnCreatureCreate(), and Update().
The documentation for this class was generated from the following files:
trial_of_the_champion.h
instance_trial_of_the_champion.cpp