CMaNGOS_WoTLK: SqlStmtParameters Class Reference
SqlStmtParameters Class Reference
#include <SqlPreparedStatement.h>
Public Types
typedef std::vector< SqlStmtFieldData > ParameterContainer
Public Member Functions
SqlStmtParameters (uint32 nParams)
~SqlStmtParameters ()
uint32 boundParams () const
void addParam (const SqlStmtFieldData &data)
void reset (const SqlStatement &stmt)
void swap (SqlStmtParameters &obj)
const ParameterContainer & params () const
Private Member Functions
SqlStmtParameters & operator= (const SqlStmtParameters &obj)
Private Attributes
ParameterContainer m_params
Detailed Description
Definition at line 142 of file SqlPreparedStatement.h.
Member Typedef Documentation
ParameterContainer
typedef std::vector<SqlStmtFieldData> SqlStmtParameters::ParameterContainer
Definition at line 145 of file SqlPreparedStatement.h.
Constructor & Destructor Documentation
SqlStmtParameters()
SqlStmtParameters::SqlStmtParameters (uint32 nParams) explicit
Definition at line 21 of file SqlPreparedStatement.cpp.
References m_params.
~SqlStmtParameters()
SqlStmtParameters::~SqlStmtParameters () inline
Definition at line 150 of file SqlPreparedStatement.h.
Member Function Documentation
addParam()
void SqlStmtParameters::addParam (const SqlStmtFieldData & data) inline
Definition at line 155 of file SqlPreparedStatement.h.
References m_params.
Referenced by SqlStatement::arg().
boundParams()
uint32 SqlStmtParameters::boundParams () const inline
Definition at line 153 of file SqlPreparedStatement.h.
References m_params.
Referenced by MySqlPreparedStatement::bind(), SqlPlainPreparedStatement::bind(), SqlStatement::DirectExecute(), and SqlStatement::Execute().
operator=()
SqlStmtParameters& SqlStmtParameters::operator= (const SqlStmtParameters & obj) private
params()
const ParameterContainer& SqlStmtParameters::params () const inline
Definition at line 162 of file SqlPreparedStatement.h.
References m_params.
Referenced by MySqlPreparedStatement::bind(), and SqlPlainPreparedStatement::bind().
reset()
void SqlStmtParameters::reset (const SqlStatement & stmt)
Definition at line 28 of file SqlPreparedStatement.cpp.
References SqlStatement::arguments(), and m_params.
swap()
void SqlStmtParameters::swap (SqlStmtParameters & obj)
Field Documentation
m_params
ParameterContainer SqlStmtParameters::m_params private
Definition at line 168 of file SqlPreparedStatement.h.
Referenced by addParam(), boundParams(), params(), reset(), and SqlStmtParameters().
The documentation for this class was generated from the following files:
SqlPreparedStatement.h
SqlPreparedStatement.cpp