CMaNGOS_WoTLK: MaNGOS::MostHPPercentMissingInRangeCheck Class Reference
MaNGOS::MostHPPercentMissingInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
MostHPPercentMissingInRangeCheck (Unit const *obj, float range, float hp, bool onlyInCombat, bool targetSelf)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
float i_hp
bool i_onlyInCombat
bool i_targetSelf
Detailed Description
Definition at line 991 of file GridNotifiers.h.
Constructor & Destructor Documentation
MostHPPercentMissingInRangeCheck()
MaNGOS::MostHPPercentMissingInRangeCheck::MostHPPercentMissingInRangeCheck (Unit const * obj, float range, float hp, bool onlyInCombat, bool targetSelf) inline
Definition at line 994 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::MostHPPercentMissingInRangeCheck::GetFocusObject () const inline
Definition at line 995 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::MostHPPercentMissingInRangeCheck::operator() (Unit * u) inline
Definition at line 996 of file GridNotifiers.h.
References Unit::CanAssist(), Unit::GetHealthPercent(), i_hp, i_obj, i_onlyInCombat, i_range, i_targetSelf, Unit::IsAlive(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_hp
float MaNGOS::MostHPPercentMissingInRangeCheck::i_hp private
Definition at line 1017 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Unit const* MaNGOS::MostHPPercentMissingInRangeCheck::i_obj private
Definition at line 1015 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_onlyInCombat
bool MaNGOS::MostHPPercentMissingInRangeCheck::i_onlyInCombat private
Definition at line 1018 of file GridNotifiers.h.
Referenced by operator()().
i_range
float MaNGOS::MostHPPercentMissingInRangeCheck::i_range private
Definition at line 1016 of file GridNotifiers.h.
Referenced by operator()().
i_targetSelf
bool MaNGOS::MostHPPercentMissingInRangeCheck::i_targetSelf private
Definition at line 1019 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h