CMaNGOS_WoTLK: PathJumpGenerator Class Reference
PathJumpGenerator Class Reference
#include <PathMovementGenerator.h>
Public Member Functions
PathJumpGenerator (uint32 pathId, uint32 forcedMovement, float horizontalSpeed, float maxHeight, ObjectGuid guid)
void Initialize (Unit &unit) override
void Finalize (Unit &unit) override
void Interrupt (Unit &unit) override
void Reset (Unit &unit) override
MovementGeneratorType GetMovementGeneratorType () const override
Public Member Functions inherited from AbstractPathMovementGenerator
AbstractPathMovementGenerator (const Movement::PointsArray &path, float orientation=0, int32 offset=0)
AbstractPathMovementGenerator (const WaypointPath *path, int32 offset=0, bool cyclic=false, ObjectGuid guid=ObjectGuid())
bool Update (Unit &owner, const uint32 &) override
void UnitSpeedChanged () override
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Member Functions
virtual bool Move (Unit &unit) const
Protected Member Functions inherited from AbstractPathMovementGenerator
virtual void MovementInform (Unit &unit)
Private Attributes
uint32 m_forcedMovement
float m_horizontalSpeed
float m_maxHeight
Additional Inherited Members
Protected Attributes inherited from AbstractPathMovementGenerator
WaypointPath m_path
int32 m_pathIndex
Movement::PointsArray m_spline
float m_orientation
ShortTimeTracker m_timer
bool m_cyclic
bool m_firstCycle
uint32 m_startPoint
ObjectGuid m_guid
Detailed Description
Definition at line 108 of file PathMovementGenerator.h.
Constructor & Destructor Documentation
PathJumpGenerator()
PathJumpGenerator::PathJumpGenerator (uint32 pathId, uint32 forcedMovement, float horizontalSpeed, float maxHeight, ObjectGuid guid) explicit
Definition at line 419 of file PathMovementGenerator.cpp.
Member Function Documentation
Finalize()
void PathJumpGenerator::Finalize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 438 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Finalize(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
GetMovementGeneratorType()
MovementGeneratorType PathJumpGenerator::GetMovementGeneratorType () const inline override virtual
Implements MovementGenerator.
Definition at line 118 of file PathMovementGenerator.h.
References PATH_MOTION_TYPE.
Initialize()
void PathJumpGenerator::Initialize (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 424 of file PathMovementGenerator.cpp.
References Unit::addUnitState(), AbstractPathMovementGenerator::Initialize(), AbstractPathMovementGenerator::m_firstCycle, AbstractPathMovementGenerator::m_pathIndex, AbstractPathMovementGenerator::m_spline, AbstractPathMovementGenerator::m_startPoint, Move(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Interrupt()
void PathJumpGenerator::Interrupt (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 444 of file PathMovementGenerator.cpp.
References Unit::clearUnitState(), AbstractPathMovementGenerator::Interrupt(), UNIT_STAT_ROAMING, and UNIT_STAT_ROAMING_MOVE.
Move()
bool PathJumpGenerator::Move (Unit & unit) const protected virtual
Definition at line 456 of file PathMovementGenerator.cpp.
References Movement::MoveSplineInit::CheckBounds(), ERROR_DB_FILTER_LOG, Movement::MoveSpline::Finalized(), FORCED_MOVEMENT_RUN, FORCED_MOVEMENT_WALK, Unit::GetMotionMaster(), WorldObject::GetName(), MotionMaster::GetPathId(), WorldObject::GetPosition(), WorldObject::GetTransport(), Unit::hasUnitState(), Movement::MoveSplineInit::Launch(), LOG_FILTER_AI_AND_MOVEGENSS, m_forcedMovement, m_horizontalSpeed, m_maxHeight, AbstractPathMovementGenerator::m_orientation, AbstractPathMovementGenerator::m_pathIndex, AbstractPathMovementGenerator::m_spline, Movement::MoveSplineInit::MovebyPath(), Unit::movespline, Movement::MoveSplineInit::Path(), Movement::MoveSplineInit::SetFacing(), Movement::MoveSplineInit::SetFirstPointId(), Movement::MoveSplineInit::SetParabolic(), Movement::MoveSplineInit::SetVelocity(), Movement::MoveSplineInit::SetWalk(), UNIT_STAT_RUNNING, Unit::UpdateSplinePosition(), Position::x, Position::y, and Position::z.
Referenced by Initialize().
Reset()
void PathJumpGenerator::Reset (Unit & unit) override virtual
Reimplemented from AbstractPathMovementGenerator.
Definition at line 450 of file PathMovementGenerator.cpp.
References Unit::addUnitState(), AbstractPathMovementGenerator::Reset(), and UNIT_STAT_ROAMING.
Field Documentation
m_forcedMovement
uint32 PathJumpGenerator::m_forcedMovement private
Definition at line 124 of file PathMovementGenerator.h.
Referenced by Move().
m_horizontalSpeed
float PathJumpGenerator::m_horizontalSpeed private
Definition at line 125 of file PathMovementGenerator.h.
Referenced by Move().
m_maxHeight
float PathJumpGenerator::m_maxHeight private
Definition at line 126 of file PathMovementGenerator.h.
Referenced by Move().
The documentation for this class was generated from the following files:
PathMovementGenerator.h
PathMovementGenerator.cpp