CMaNGOS_WoTLK: Movement::PacketBuilder Class Reference
Movement::PacketBuilder Class Reference
#include <packet_builder.h>
Static Public Member Functions
static void WriteMonsterMove (const MoveSpline &move_spline, WorldPacket &data)
static void WriteCreate (const MoveSpline &move_spline, ByteBuffer &data)
Static Private Member Functions
static void WriteCommonMonsterMovePart (const MoveSpline &move_spline, WorldPacket &data)
Detailed Description
Definition at line 28 of file packet_builder.h.
Member Function Documentation
WriteCommonMonsterMovePart()
void Movement::PacketBuilder::WriteCommonMonsterMovePart (const MoveSpline & move_spline, WorldPacket & data) static private
Definition at line 35 of file packet_builder.cpp.
References Movement::FacingInfo::angle, Movement::MoveSplineFlag::animation, Movement::MoveSpline::animation_start_time, Movement::MoveSpline::Duration(), Movement::FacingInfo::f, Movement::MoveSpline::facing, Movement::MoveSplineFlag::Final_Angle, Movement::MoveSplineFlag::Final_Point, Movement::MoveSplineFlag::Final_Target, Movement::SplineBase::first(), Movement::MoveSplineFlag::getAnimationId(), Movement::MoveSpline::GetId(), Movement::SplineBase::getPoint(), Movement::MoveSplineFlag::Mask_Final_Facing, Movement::MoveSplineFlag::Mask_No_Monster_Move, Movement::MonsterMoveFacingAngle, Movement::MonsterMoveFacingSpot, Movement::MonsterMoveFacingTarget, Movement::MonsterMoveNormal, Movement::MoveSplineFlag::parabolic, Movement::MoveSpline::parabolic_start_time, Movement::MoveSpline::spline, Movement::MoveSpline::splineflags, Movement::FacingInfo::target, Movement::MoveSpline::vertical_acceleration, Movement::FacingInfo::x, Movement::FacingInfo::y, and Movement::FacingInfo::z.
Referenced by WriteMonsterMove().
WriteCreate()
void Movement::PacketBuilder::WriteCreate (const MoveSpline & move_spline, ByteBuffer & data) static
Definition at line 129 of file packet_builder.cpp.
References Movement::FacingInfo::angle, ByteBuffer::append(), Movement::MoveSpline::Duration(), Movement::FacingInfo::f, Movement::MoveSpline::facing, Movement::MoveSplineFlag::final_angle, Movement::MoveSplineFlag::final_point, Movement::MoveSplineFlag::final_target, Movement::MoveSpline::FinalDestination(), Movement::MoveSpline::GetId(), Movement::MoveSpline::getPath(), Movement::MoveSpline::isCyclic(), Movement::SplineBase::mode(), Movement::MoveSpline::parabolic_start_time, Movement::MoveSplineFlag::raw(), Movement::MoveSpline::spline, Movement::MoveSpline::splineflags, Movement::FacingInfo::target, Movement::MoveSpline::timePassed(), Movement::MoveSpline::vertical_acceleration, Movement::FacingInfo::x, Movement::FacingInfo::y, and Movement::FacingInfo::z.
Referenced by Object::BuildMovementUpdate().
WriteMonsterMove()
void Movement::PacketBuilder::WriteMonsterMove (const MoveSpline & move_spline, WorldPacket & data) static
Definition at line 112 of file packet_builder.cpp.
References Movement::MoveSplineFlag::cyclic, Movement::MoveSplineFlag::Mask_CatmullRom, Movement::MoveSpline::spline, Movement::MoveSpline::splineflags, Movement::WriteCatmullRomCyclicPath(), Movement::WriteCatmullRomPath(), WriteCommonMonsterMovePart(), and Movement::WriteLinearPath().
Referenced by Movement::MoveSplineInit::Launch().
The documentation for this class was generated from the following files:
packet_builder.h
packet_builder.cpp