CMaNGOS_WoTLK: MaNGOS::AchievementChatBuilder Class Reference
MaNGOS::AchievementChatBuilder Class Reference
Public Member Functions
AchievementChatBuilder (Player const &pl, ChatMsg msgtype, int32 textId, uint32 ach_id)
void operator() (WorldPacket &data, int32 loc_idx)
Private Attributes
Player const & i_player
ChatMsg i_msgtype
int32 i_textId
uint32 i_achievementId
Detailed Description
Definition at line 52 of file AchievementMgr.cpp.
Constructor & Destructor Documentation
AchievementChatBuilder()
MaNGOS::AchievementChatBuilder::AchievementChatBuilder (Player const & pl, ChatMsg msgtype, int32 textId, uint32 ach_id) inline
Definition at line 55 of file AchievementMgr.cpp.
Member Function Documentation
operator()()
void MaNGOS::AchievementChatBuilder::operator() (WorldPacket & data, int32 loc_idx) inline
Definition at line 57 of file AchievementMgr.cpp.
References ChatHandler::BuildChatPacket(), Player::GetChatTag(), Object::GetObjectGuid(), i_achievementId, i_msgtype, i_player, i_textId, LANG_UNIVERSAL, and sObjectMgr.
Field Documentation
i_achievementId
uint32 MaNGOS::AchievementChatBuilder::i_achievementId private
Definition at line 69 of file AchievementMgr.cpp.
Referenced by operator()().
i_msgtype
ChatMsg MaNGOS::AchievementChatBuilder::i_msgtype private
Definition at line 67 of file AchievementMgr.cpp.
Referenced by operator()().
i_player
Player const& MaNGOS::AchievementChatBuilder::i_player private
Definition at line 66 of file AchievementMgr.cpp.
Referenced by operator()().
i_textId
int32 MaNGOS::AchievementChatBuilder::i_textId private
Definition at line 68 of file AchievementMgr.cpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
AchievementMgr.cpp