CMaNGOS_WoTLK: OutdoorPvPNA Class Reference
OutdoorPvPNA Class Reference
#include <OutdoorPvPNA.h>
Public Member Functions
OutdoorPvPNA ()
void HandlePlayerEnterZone (Player *player, bool isMainZone) override
void HandlePlayerLeaveZone (Player *player, bool isMainZone) override
Function that removes a player from the players of the affected outdoor pvp zones.
void FillInitialWorldStates (WorldPacket &data, uint32 &count) override
void SendRemoveWorldStates (Player *player) override
bool HandleEvent (uint32 eventId, Object *source, Object *target) override
void HandleObjectiveComplete (uint32 eventId, const PlayerList &players, Team team) override
void HandleCreatureCreate (Creature *creature) override
void HandleGameObjectCreate (GameObject *go) override
void HandleCreatureDeath (Creature *creature) override
void HandlePlayerKillInsideArea (Player *player, Unit *) override
bool HandleGameObjectUse (Player *player, GameObject *go) override
void Update (uint32 diff) override
Public Member Functions inherited from OutdoorPvP
OutdoorPvP ()
virtual ~OutdoorPvP ()
virtual void HandleGameObjectRemove (GameObject *)
virtual bool HandleAreaTrigger (Player *, uint32)
virtual bool HandleDropFlag (Player *, uint32)
void HandlePlayerKill (Player *killer, Unit *victim)
Function that handles kills in the main outdoor pvp zones.
void BuffTeam (Team team, uint32 spellId, bool remove=false, const uint32 areaId=0)
void SendUpdateWorldState (uint32 field, uint32 value)
Function that updates the world state for all the players of the outdoor pvp zone.
void SetBannerVisual (const WorldObject *objRef, ObjectGuid goGuid, uint32 artKit, uint32 animId)
void SetBannerVisual (GameObject *go, uint32 artKit, uint32 animId)
bool IsBattlefield () const
virtual bool IsConditionFulfilled (Player const *, uint32, WorldObject const *, uint32)
virtual void HandleConditionStateChange (uint32, bool)
void SetGraveYardLinkTeam (uint32 id, uint32 locKey, Team team, uint32 mapId)
Function that adds a player to the players of the affected outdoor pvp zones.
virtual bool CheckAchievementCriteriaMeet (uint32, Player const *, Unit const *, uint32)
Private Member Functions
void UpdateWorldState (uint32 value)
void UpdateWyvernsWorldState (uint32 value)
void ProcessCaptureEvent (GameObject *go, Team team)
void DespawnVendors (const WorldObject *objRef)
void HandleFactionObjects (const WorldObject *objRef)
void LockHalaa (const WorldObject *objRef)
void UnlockHalaa (const WorldObject *objRef)
void RespawnSoldier ()
Private Attributes
Team m_zoneOwner
uint32 m_soldiersRespawnTimer
uint32 m_zoneWorldState
uint32 m_zoneMapState
uint32 m_roostWorldState [MAX_NA_ROOSTS]
uint8 m_guardsLeft
bool m_isUnderSiege
ObjectGuid m_capturePoint
ObjectGuid m_roostsAlliance [MAX_NA_ROOSTS]
ObjectGuid m_roostsHorde [MAX_NA_ROOSTS]
ObjectGuid m_roostsBrokenAlliance [MAX_NA_ROOSTS]
ObjectGuid m_roostsBrokenHorde [MAX_NA_ROOSTS]
ObjectGuid m_wagonsAlliance [MAX_NA_ROOSTS]
ObjectGuid m_wagonsHorde [MAX_NA_ROOSTS]
GuidList m_teamVendors
std::queue< HalaaSoldiersSpawns > m_deadSoldiers
Additional Inherited Members
Protected Member Functions inherited from OutdoorPvP
virtual void HandlePlayerEnterArea (Player *, uint32, bool)
virtual void HandlePlayerLeaveArea (Player *, uint32, bool)
uint32 GetBannerArtKit (Team team, uint32 artKitAlliance=CAPTURE_ARTKIT_ALLIANCE, uint32 artKitHorde=CAPTURE_ARTKIT_HORDE, uint32 artKitNeutral=CAPTURE_ARTKIT_NEUTRAL) const
void RespawnGO (const WorldObject *objRef, ObjectGuid goGuid, bool respawn)
Protected Attributes inherited from OutdoorPvP
GuidZoneMap m_zonePlayers
bool m_isBattlefield
Detailed Description
Definition at line 126 of file OutdoorPvPNA.h.
Constructor & Destructor Documentation
OutdoorPvPNA()
OutdoorPvPNA::OutdoorPvPNA ()
Definition at line 29 of file OutdoorPvPNA.cpp.
References GRAVEYARD_ID_HALAA, GRAVEYARD_ZONE_ID_HALAA, OutdoorPvP::SetGraveYardLinkTeam(), and TEAM_INVALID.
Member Function Documentation
DespawnVendors()
void OutdoorPvPNA::DespawnVendors (const WorldObject * objRef) private
Definition at line 391 of file OutdoorPvPNA.cpp.
References Map::GetCreature(), WorldObject::GetMap(), and m_teamVendors.
Referenced by ProcessCaptureEvent().
FillInitialWorldStates()
void OutdoorPvPNA::FillInitialWorldStates (WorldPacket & data, uint32 & count) override virtual
Reimplemented from OutdoorPvP.
Definition at line 41 of file OutdoorPvPNA.cpp.
References FillInitialWorldState(), m_guardsLeft, m_roostWorldState, m_zoneMapState, m_zoneOwner, m_zoneWorldState, MAX_NA_GUARDS, TEAM_NONE, WORLD_STATE_ADD, WORLD_STATE_NA_GUARDS_LEFT, and WORLD_STATE_NA_GUARDS_MAX.
HandleCreatureCreate()
void OutdoorPvPNA::HandleCreatureCreate (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 105 of file OutdoorPvPNA.cpp.
References ALLIANCE, Object::GetEntry(), Object::GetObjectGuid(), LockHalaa(), m_guardsLeft, m_teamVendors, m_zoneMapState, m_zoneOwner, MAX_NA_GUARDS, NPC_ALLIANCE_HANAANI_GUARD, NPC_AMMUNITIONER_BANRO, NPC_AMMUNITIONER_TASALDAN, NPC_HORDE_HALAANI_GUARD, NPC_MERCHANT_ALDRAAN, NPC_MERCHANT_COREIEL, NPC_QUARTERMASTER_DAVIAN, NPC_QUARTERMASTER_NORELIQE, NPC_RESEARCHER_AMERELDINE, NPC_RESEARCHER_KARTOS, NPC_VENDOR_CENDRII, NPC_VENDOR_EMBELAR, OutdoorPvP::SendUpdateWorldState(), WORLD_STATE_ADD, WORLD_STATE_NA_GUARDS_LEFT, WORLD_STATE_NA_HALAA_ALLIANCE, WORLD_STATE_NA_HALAA_HORDE, and WORLD_STATE_REMOVE.
HandleCreatureDeath()
void OutdoorPvPNA::HandleCreatureDeath (Creature * creature) override virtual
Reimplemented from OutdoorPvP.
Definition at line 143 of file OutdoorPvPNA.cpp.
References ALLIANCE, Object::GetEntry(), Creature::GetRespawnCoord(), HOUR, IN_MILLISECONDS, LANG_OPVP_NA_DEFENSELESS, m_deadSoldiers, m_guardsLeft, m_isUnderSiege, m_soldiersRespawnTimer, m_zoneMapState, m_zoneOwner, MINUTE, NPC_ALLIANCE_HANAANI_GUARD, NPC_HORDE_HALAANI_GUARD, OutdoorPvP::SendUpdateWorldState(), sWorld, UnlockHalaa(), WORLD_STATE_ADD, WORLD_STATE_NA_GUARDS_LEFT, WORLD_STATE_NA_HALAA_NEUTRAL_A, WORLD_STATE_NA_HALAA_NEUTRAL_H, WORLD_STATE_REMOVE, and ZONE_ID_NAGRAND.
HandleEvent()
bool OutdoorPvPNA::HandleEvent (uint32 eventId, Object * source, Object * target) override virtual
Reimplemented from OutdoorPvP.
Definition at line 286 of file OutdoorPvPNA.cpp.
References ALLIANCE, CAPTURE_ANIM_ALLIANCE, CAPTURE_ANIM_HORDE, CAPTURE_ARTKIT_ALLIANCE, CAPTURE_ARTKIT_HORDE, EVENT_HALAA_BANNER_PROGRESS_ALLIANCE, EVENT_HALAA_BANNER_PROGRESS_HORDE, EVENT_HALAA_BANNER_WIN_ALLIANCE, EVENT_HALAA_BANNER_WIN_HORDE, Object::GetEntry(), GO_HALAA_BANNER, HORDE, Object::IsGameObject(), LANG_OPVP_NA_PROGRESS_A, LANG_OPVP_NA_PROGRESS_H, ProcessCaptureEvent(), OutdoorPvP::SetBannerVisual(), sWorld, and ZONE_ID_NAGRAND.
HandleFactionObjects()
void OutdoorPvPNA::HandleFactionObjects (const WorldObject * objRef) private
Definition at line 360 of file OutdoorPvPNA.cpp.
References ALLIANCE, m_roostsAlliance, m_roostsBrokenAlliance, m_roostsBrokenHorde, m_roostsHorde, m_roostWorldState, m_wagonsAlliance, m_wagonsHorde, m_zoneOwner, MAX_NA_ROOSTS, nagrandRoostStatesAllianceNeutral, nagrandRoostStatesHordeNeutral, and OutdoorPvP::RespawnGO().
Referenced by ProcessCaptureEvent().
HandleGameObjectCreate()
void OutdoorPvPNA::HandleGameObjectCreate (GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 180 of file OutdoorPvPNA.cpp.
References OutdoorPvP::GetBannerArtKit(), Object::GetEntry(), Object::GetObjectGuid(), GO_BOMB_WAGON_ALLIANCE_EAST, GO_BOMB_WAGON_ALLIANCE_NORTH, GO_BOMB_WAGON_ALLIANCE_SOUTH, GO_BOMB_WAGON_ALLIANCE_WEST, GO_BOMB_WAGON_HORDE_EAST, GO_BOMB_WAGON_HORDE_NORTH, GO_BOMB_WAGON_HORDE_SOUTH, GO_BOMB_WAGON_HORDE_WEST, GO_DESTROYED_ROOST_ALLIANCE_EAST, GO_DESTROYED_ROOST_ALLIANCE_NORTH, GO_DESTROYED_ROOST_ALLIANCE_SOUTH, GO_DESTROYED_ROOST_ALLIANCE_WEST, GO_DESTROYED_ROOST_HORDE_EAST, GO_DESTROYED_ROOST_HORDE_NORTH, GO_DESTROYED_ROOST_HORDE_SOUTH, GO_DESTROYED_ROOST_HORDE_WEST, GO_HALAA_BANNER, GO_WYVERN_ROOST_ALLIANCE_EAST, GO_WYVERN_ROOST_ALLIANCE_NORTH, GO_WYVERN_ROOST_ALLIANCE_SOUTH, GO_WYVERN_ROOST_ALLIANCE_WEST, GO_WYVERN_ROOST_HORDE_EAST, GO_WYVERN_ROOST_HORDE_NORTH, GO_WYVERN_ROOST_HORDE_SOUTH, GO_WYVERN_ROOST_HORDE_WEST, OutdoorPvP::HandleGameObjectCreate(), m_capturePoint, m_roostsAlliance, m_roostsBrokenAlliance, m_roostsBrokenHorde, m_roostsHorde, m_wagonsAlliance, m_wagonsHorde, m_zoneOwner, and GameObject::SetGoArtKit().
HandleGameObjectUse()
bool OutdoorPvPNA::HandleGameObjectUse (Player * player, GameObject * go) override virtual
Reimplemented from OutdoorPvP.
Definition at line 402 of file OutdoorPvPNA.cpp.
References ALLIANCE, Object::GetEntry(), Player::GetTeam(), HORDE, m_roostsAlliance, m_roostsBrokenAlliance, m_roostsBrokenHorde, m_roostsHorde, m_roostWorldState, m_wagonsAlliance, m_wagonsHorde, MAX_NA_ROOSTS, nagrandRoostsAlliance, nagrandRoostsBrokenAlliance, nagrandRoostsBrokenHorde, nagrandRoostsHorde, nagrandRoostStatesAlliance, nagrandRoostStatesAllianceNeutral, nagrandRoostStatesHorde, nagrandRoostStatesHordeNeutral, nagrandWagonsAlliance, nagrandWagonsHorde, OutdoorPvP::RespawnGO(), GameObject::SetRespawnTime(), Player::UpdatePvP(), UpdateWyvernsWorldState(), WORLD_STATE_ADD, and WORLD_STATE_REMOVE.
HandleObjectiveComplete()
void OutdoorPvPNA::HandleObjectiveComplete (uint32 eventId, const PlayerList & players, Team team) override virtual
Reimplemented from OutdoorPvP.
Definition at line 86 of file OutdoorPvPNA.cpp.
References EVENT_HALAA_BANNER_WIN_ALLIANCE, EVENT_HALAA_BANNER_WIN_HORDE, and NPC_HALAA_COMBATANT.
HandlePlayerEnterZone()
void OutdoorPvPNA::HandlePlayerEnterZone (Player * player, bool isMainZone) override virtual
Reimplemented from OutdoorPvP.
Definition at line 66 of file OutdoorPvPNA.cpp.
References Unit::CastSpell(), Player::GetTeam(), OutdoorPvP::HandlePlayerEnterZone(), m_zoneOwner, Unit::RemoveAurasDueToSpell(), SPELL_STRENGTH_HALAANI, and TRIGGERED_OLD_TRIGGERED.
HandlePlayerKillInsideArea()
void OutdoorPvPNA::HandlePlayerKillInsideArea (Player * player, Unit * victim) override virtual
Reimplemented from OutdoorPvP.
Definition at line 99 of file OutdoorPvPNA.cpp.
References ALLIANCE, Unit::CastSpell(), WorldObject::GetAreaId(), Player::GetTeam(), SPELL_NAGRAND_TOKEN_ALLIANCE, SPELL_NAGRAND_TOKEN_HORDE, TRIGGERED_OLD_TRIGGERED, and ZONE_HALAA.
HandlePlayerLeaveZone()
void OutdoorPvPNA::HandlePlayerLeaveZone (Player * player, bool isMainZone) override virtual
Function that removes a player from the players of the affected outdoor pvp zones.
Parameters
player to remove
whether zone is main outdoor pvp zone or a affected zone
Reimplemented from OutdoorPvP.
Definition at line 78 of file OutdoorPvPNA.cpp.
References OutdoorPvP::HandlePlayerLeaveZone(), Unit::RemoveAurasDueToSpell(), and SPELL_STRENGTH_HALAANI.
LockHalaa()
void OutdoorPvPNA::LockHalaa (const WorldObject * objRef) private
Definition at line 538 of file OutdoorPvPNA.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, Map::GetGameObject(), WorldObject::GetMap(), GO_HALAA_BANNER, GO_JUST_DEACTIVATED, m_capturePoint, m_zoneOwner, and sOutdoorPvPMgr.
Referenced by HandleCreatureCreate(), and ProcessCaptureEvent().
ProcessCaptureEvent()
void OutdoorPvPNA::ProcessCaptureEvent (GameObject * go, Team team) private
Definition at line 322 of file OutdoorPvPNA.cpp.
References ALLIANCE, OutdoorPvP::BuffTeam(), DespawnVendors(), GRAVEYARD_ID_HALAA, GRAVEYARD_ZONE_ID_HALAA, HandleFactionObjects(), LANG_OPVP_NA_CAPTURE_A, LANG_OPVP_NA_CAPTURE_H, LockHalaa(), m_guardsLeft, m_isUnderSiege, m_soldiersRespawnTimer, m_zoneMapState, m_zoneOwner, m_zoneWorldState, MAX_NA_GUARDS, OutdoorPvP::SendUpdateWorldState(), OutdoorPvP::SetGraveYardLinkTeam(), SPELL_STRENGTH_HALAANI, sWorld, UpdateWorldState(), WORLD_STATE_ADD, WORLD_STATE_NA_GUARDS_ALLIANCE, WORLD_STATE_NA_GUARDS_HORDE, WORLD_STATE_NA_GUARDS_LEFT, WORLD_STATE_NA_HALAA_ALLIANCE, WORLD_STATE_NA_HALAA_HORDE, WORLD_STATE_REMOVE, and ZONE_ID_NAGRAND.
Referenced by HandleEvent().
RespawnSoldier()
void OutdoorPvPNA::RespawnSoldier () private
Definition at line 518 of file OutdoorPvPNA.cpp.
References ALLIANCE, m_deadSoldiers, m_zoneOwner, OutdoorPvP::m_zonePlayers, NPC_ALLIANCE_HANAANI_GUARD, NPC_HORDE_HALAANI_GUARD, HalaaSoldiersSpawns::o, sObjectMgr, TEMPSPAWN_DEAD_DESPAWN, HalaaSoldiersSpawns::x, HalaaSoldiersSpawns::y, and HalaaSoldiersSpawns::z.
Referenced by Update().
SendRemoveWorldStates()
void OutdoorPvPNA::SendRemoveWorldStates (Player * player) override virtual
Reimplemented from OutdoorPvP.
Definition at line 57 of file OutdoorPvPNA.cpp.
References m_roostWorldState, m_zoneMapState, m_zoneWorldState, Player::SendUpdateWorldState(), and WORLD_STATE_REMOVE.
UnlockHalaa()
void OutdoorPvPNA::UnlockHalaa (const WorldObject * objRef) private
Definition at line 551 of file OutdoorPvPNA.cpp.
References ALLIANCE, CAPTURE_SLIDER_ALLIANCE, CAPTURE_SLIDER_HORDE, Map::GetGameObject(), WorldObject::GetMap(), GO_ACTIVATED, GO_HALAA_BANNER, m_capturePoint, m_zoneOwner, and sOutdoorPvPMgr.
Referenced by HandleCreatureDeath().
Update()
void OutdoorPvPNA::Update (uint32 diff) override virtual
Reimplemented from OutdoorPvP.
Definition at line 498 of file OutdoorPvPNA.cpp.
References HOUR, IN_MILLISECONDS, m_guardsLeft, m_isUnderSiege, m_soldiersRespawnTimer, MAX_NA_GUARDS, MINUTE, and RespawnSoldier().
UpdateWorldState()
void OutdoorPvPNA::UpdateWorldState (uint32 value) private
Definition at line 271 of file OutdoorPvPNA.cpp.
References m_zoneMapState, m_zoneWorldState, OutdoorPvP::SendUpdateWorldState(), and UpdateWyvernsWorldState().
Referenced by ProcessCaptureEvent().
UpdateWyvernsWorldState()
void OutdoorPvPNA::UpdateWyvernsWorldState (uint32 value) private
Definition at line 279 of file OutdoorPvPNA.cpp.
References m_roostWorldState, and OutdoorPvP::SendUpdateWorldState().
Referenced by HandleGameObjectUse(), and UpdateWorldState().
Field Documentation
m_capturePoint
ObjectGuid OutdoorPvPNA::m_capturePoint private
Definition at line 175 of file OutdoorPvPNA.h.
Referenced by HandleGameObjectCreate(), LockHalaa(), and UnlockHalaa().
m_deadSoldiers
std::queue<HalaaSoldiersSpawns> OutdoorPvPNA::m_deadSoldiers private
Definition at line 185 of file OutdoorPvPNA.h.
Referenced by HandleCreatureDeath(), and RespawnSoldier().
m_guardsLeft
uint8 OutdoorPvPNA::m_guardsLeft private
Definition at line 171 of file OutdoorPvPNA.h.
Referenced by FillInitialWorldStates(), HandleCreatureCreate(), HandleCreatureDeath(), ProcessCaptureEvent(), and Update().
m_isUnderSiege
bool OutdoorPvPNA::m_isUnderSiege private
Definition at line 173 of file OutdoorPvPNA.h.
Referenced by HandleCreatureDeath(), ProcessCaptureEvent(), and Update().
m_roostsAlliance
ObjectGuid OutdoorPvPNA::m_roostsAlliance[MAX_NA_ROOSTS] private
Definition at line 176 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_roostsBrokenAlliance
ObjectGuid OutdoorPvPNA::m_roostsBrokenAlliance[MAX_NA_ROOSTS] private
Definition at line 178 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_roostsBrokenHorde
ObjectGuid OutdoorPvPNA::m_roostsBrokenHorde[MAX_NA_ROOSTS] private
Definition at line 179 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_roostsHorde
ObjectGuid OutdoorPvPNA::m_roostsHorde[MAX_NA_ROOSTS] private
Definition at line 177 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_roostWorldState
uint32 OutdoorPvPNA::m_roostWorldState[MAX_NA_ROOSTS] private
Definition at line 170 of file OutdoorPvPNA.h.
Referenced by FillInitialWorldStates(), HandleFactionObjects(), HandleGameObjectUse(), SendRemoveWorldStates(), and UpdateWyvernsWorldState().
m_soldiersRespawnTimer
uint32 OutdoorPvPNA::m_soldiersRespawnTimer private
Definition at line 167 of file OutdoorPvPNA.h.
Referenced by HandleCreatureDeath(), ProcessCaptureEvent(), and Update().
m_teamVendors
GuidList OutdoorPvPNA::m_teamVendors private
Definition at line 183 of file OutdoorPvPNA.h.
Referenced by DespawnVendors(), and HandleCreatureCreate().
m_wagonsAlliance
ObjectGuid OutdoorPvPNA::m_wagonsAlliance[MAX_NA_ROOSTS] private
Definition at line 180 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_wagonsHorde
ObjectGuid OutdoorPvPNA::m_wagonsHorde[MAX_NA_ROOSTS] private
Definition at line 181 of file OutdoorPvPNA.h.
Referenced by HandleFactionObjects(), HandleGameObjectCreate(), and HandleGameObjectUse().
m_zoneMapState
uint32 OutdoorPvPNA::m_zoneMapState private
Definition at line 169 of file OutdoorPvPNA.h.
Referenced by FillInitialWorldStates(), HandleCreatureCreate(), HandleCreatureDeath(), ProcessCaptureEvent(), SendRemoveWorldStates(), and UpdateWorldState().
m_zoneOwner
Team OutdoorPvPNA::m_zoneOwner private
Definition at line 166 of file OutdoorPvPNA.h.
Referenced by FillInitialWorldStates(), HandleCreatureCreate(), HandleCreatureDeath(), HandleFactionObjects(), HandleGameObjectCreate(), HandlePlayerEnterZone(), LockHalaa(), ProcessCaptureEvent(), RespawnSoldier(), and UnlockHalaa().
m_zoneWorldState
uint32 OutdoorPvPNA::m_zoneWorldState private
Definition at line 168 of file OutdoorPvPNA.h.
Referenced by FillInitialWorldStates(), ProcessCaptureEvent(), SendRemoveWorldStates(), and UpdateWorldState().
The documentation for this class was generated from the following files:
OutdoorPvPNA.h
OutdoorPvPNA.cpp