CMaNGOS_WoTLK: instance_shadowfang_keep Class Reference
instance_shadowfang_keep Class Reference
#include <shadowfang_keep.h>
Public Member Functions
instance_shadowfang_keep (Map *map)
void Initialize () override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void DoSpeech ()
void JustDidDialogueStep (int32 entry) override
Will be called when a dialogue step was done.
void OnCreatureEvade (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void GetCrownApothecaryGuids (GuidList &lApothecaryList) const
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Public Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
Private Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
uint8 m_uiApothecaryDead
GuidList m_lNandosWolvesGuids
GuidList m_lCrownApothecaryGuids
uint32 m_uiApothecaryResetTimer
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Member Functions inherited from DialogueHelper
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
virtual Unit * GetDialogueTarget ()
Will be called to get a target; OPTIONAL.
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 97 of file shadowfang_keep.h.
Constructor & Destructor Documentation
instance_shadowfang_keep()
instance_shadowfang_keep::instance_shadowfang_keep (Map * map)
Definition at line 54 of file instance_shadowfang_keep.cpp.
References Initialize().
Member Function Documentation
DoSpeech()
void instance_shadowfang_keep::DoSpeech ()
Definition at line 211 of file instance_shadowfang_keep.cpp.
References DoScriptText(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), NPC_ADA, NPC_ASH, SAY_BOSS_DIE_AD, and SAY_BOSS_DIE_AS.
Referenced by SetData().
GetCrownApothecaryGuids()
void instance_shadowfang_keep::GetCrownApothecaryGuids (GuidList & lApothecaryList) const inline
Definition at line 123 of file shadowfang_keep.h.
References m_lCrownApothecaryGuids.
Referenced by npc_valentine_boss_managerAI::DoStartValentineEvent().
GetData()
uint32 instance_shadowfang_keep::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 320 of file instance_shadowfang_keep.cpp.
References m_auiEncounter, TYPE_APOTHECARY, TYPE_FENRUS, TYPE_FREE_NPC, TYPE_INTRO, TYPE_NANDOS, and TYPE_RETHILGORE.
Initialize()
void instance_shadowfang_keep::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 61 of file instance_shadowfang_keep.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_shadowfang_keep().
JustDidDialogueStep()
void instance_shadowfang_keep::JustDidDialogueStep (int32) override virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 384 of file instance_shadowfang_keep.cpp.
References AI_EVENT_CUSTOM_A, ARCHMAGE_FIRE, ARCHMAGE_INVIS, ARCHMAGE_LIGHTNING, ARCHMAGE_VOIDWALKERS, ARUGAL_EMOTE_EXCLAMATION, ARUGAL_EMOTE_LAUGH, ARUGAL_EMOTE_POINT, ARUGAL_INTRO_DONE, ARUGAL_TELEPORT_IN, ARUGAL_TELEPORT_OUT, ARUGAL_TURN_TO_VINCENT, ARUGAL_VISIBLE, DONE, EMOTE_ONESHOT_EXCLAMATION, EMOTE_ONESHOT_LAUGH, EMOTE_ONESHOT_POINT, ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ARUGAL_FOCUS, NPC_ARCHMAGE_ARUGAL, NPC_ARUGAL, NPC_VINCENT, SetData(), SPELL_ARUGAL_TELEPORT, SPELL_FIRE, SPELL_SPAWN, TYPE_INTRO, UNIT_STAND_STATE_DEAD, VINCENT_DEATH, VISIBILITY_OFF, VISIBILITY_ON, and YELL_FENRUS.
Load()
void instance_shadowfang_keep::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 336 of file instance_shadowfang_keep.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_shadowfang_keep::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 73 of file instance_shadowfang_keep.cpp.
References DONE, Waypoint::fZ, Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetPositionZ(), Creature::IsTemporarySummon(), m_auiEncounter, m_lCrownApothecaryGuids, m_lNandosWolvesGuids, ScriptedInstance::m_npcEntryGuidStore, nandosMovement, NPC_ADA, NPC_APOTHECARY_GENERATOR, NPC_ARCHMAGE_ARUGAL, NPC_ARUGAL, NPC_ASH, NPC_BAXTER, NPC_BLEAK_WORG, NPC_CROWN_APOTHECARY, NPC_FENRUS, NPC_FRYE, NPC_HUMMEL, NPC_LUPINE_HORROR, NPC_MASTER_NANDOS, NPC_SLAVERING_WORG, NPC_VALENTINE_BOSS_MGR, NPC_VINCENT, NPC_WOLFGUARD_WORG, Unit::SetStandState(), Unit::SetVisibility(), DialogueHelper::StartNextDialogueText(), UNIT_STAND_STATE_DEAD, and VISIBILITY_OFF.
OnCreatureDeath()
void instance_shadowfang_keep::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 146 of file instance_shadowfang_keep.cpp.
References DoScriptText(), Waypoint::fX, Waypoint::fY, Waypoint::fZ, Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_lNandosWolvesGuids, nandosMovement, NPC_BAXTER, NPC_BLEAK_WORG, NPC_FRYE, NPC_LUPINE_HORROR, NPC_MASTER_NANDOS, NPC_SLAVERING_WORG, NPC_WOLFGUARD_WORG, SetData(), SPECIAL, TYPE_APOTHECARY, and YELL_PACK_DEAD.
OnCreatureEvade()
void instance_shadowfang_keep::OnCreatureEvade (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 181 of file instance_shadowfang_keep.cpp.
References FAIL, Object::GetEntry(), NPC_BAXTER, NPC_FRYE, NPC_HUMMEL, SetData(), and TYPE_APOTHECARY.
OnCreatureRespawn()
void instance_shadowfang_keep::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 193 of file instance_shadowfang_keep.cpp.
References Creature::AI(), UnitAI::AttackStart(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_CRAZED_APOTHECARY, NPC_HUMMEL, NPC_VALENTINE_VIAL_BUNNY, REACT_PASSIVE, Unit::SetCanEnterCombat(), and UnitAI::SetReactState().
OnObjectCreate()
void instance_shadowfang_keep::OnObjectCreate (GameObject * go) override virtual
Reimplemented from InstanceData.
Definition at line 117 of file instance_shadowfang_keep.cpp.
References DONE, Object::GetEntry(), Object::GetObjectGuid(), GO_APOTHECARE_VIALS, GO_ARUGAL_DOOR, GO_ARUGAL_FOCUS, GO_CHEMISTRY_SET, GO_COURTYARD_DOOR, GO_SORCERER_DOOR, GO_STATE_ACTIVE, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, and GameObject::SetGoState().
OnPlayerEnter()
void instance_shadowfang_keep::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 67 of file instance_shadowfang_keep.cpp.
References LFGData::GetDungeon(), Player::GetLfgData(), Map::GetVariableManager(), InstanceData::instance, SEASONAL_CROWN_CHEMICAL_CO, WorldStateVariableManager::SetVariable(), and WORLD_STATE_CUSTOM_CROWN_CHEMICAL_CO_DUNGEON.
Save()
const char* instance_shadowfang_keep::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 118 of file shadowfang_keep.h.
References m_strInstData.
SetData()
void instance_shadowfang_keep::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 223 of file instance_shadowfang_keep.cpp.
References Map::AwardLFGRewards(), DONE, DoSpeech(), ScriptedInstance::DoUseDoorOrButton(), FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), GO_ARUGAL_DOOR, GO_COURTYARD_DOOR, GO_SORCERER_DOOR, IN_PROGRESS, InstanceData::instance, m_auiEncounter, m_strInstData, m_uiApothecaryDead, m_uiApothecaryResetTimer, MAX_APOTHECARY, NPC_ARCHMAGE_ARUGAL, NPC_BAXTER, NPC_FENRUS, NPC_FRYE, NPC_HUMMEL, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SEASONAL_CROWN_CHEMICAL_CO, SPECIAL, DialogueHelper::StartNextDialogueText(), TEMPSPAWN_TIMED_DESPAWN, TYPE_APOTHECARY, TYPE_FENRUS, TYPE_FREE_NPC, TYPE_INTRO, TYPE_NANDOS, TYPE_RETHILGORE, TYPE_VOIDWALKER, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by JustDidDialogueStep(), npc_valentine_boss_managerAI::JustDidDialogueStep(), boss_apothecary_hummelAI::JustPreventedDeath(), OnCreatureDeath(), and OnCreatureEvade().
Update()
void instance_shadowfang_keep::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 359 of file instance_shadowfang_keep.cpp.
References DialogueHelper::DialogueUpdate(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_lCrownApothecaryGuids, m_uiApothecaryResetTimer, NPC_BAXTER, NPC_FRYE, and NPC_HUMMEL.
Field Documentation
m_auiEncounter
uint32 instance_shadowfang_keep::m_auiEncounter[MAX_ENCOUNTER] private
Definition at line 126 of file shadowfang_keep.h.
Referenced by GetData(), Initialize(), Load(), OnCreatureCreate(), OnObjectCreate(), and SetData().
m_lCrownApothecaryGuids
GuidList instance_shadowfang_keep::m_lCrownApothecaryGuids private
Definition at line 131 of file shadowfang_keep.h.
Referenced by GetCrownApothecaryGuids(), OnCreatureCreate(), and Update().
m_lNandosWolvesGuids
GuidList instance_shadowfang_keep::m_lNandosWolvesGuids private
Definition at line 130 of file shadowfang_keep.h.
Referenced by OnCreatureCreate(), and OnCreatureDeath().
m_strInstData
std::string instance_shadowfang_keep::m_strInstData private
Definition at line 127 of file shadowfang_keep.h.
Referenced by Save(), and SetData().
m_uiApothecaryDead
uint8 instance_shadowfang_keep::m_uiApothecaryDead private
Definition at line 129 of file shadowfang_keep.h.
Referenced by SetData().
m_uiApothecaryResetTimer
uint32 instance_shadowfang_keep::m_uiApothecaryResetTimer private
Definition at line 133 of file shadowfang_keep.h.
Referenced by SetData(), and Update().
The documentation for this class was generated from the following files:
shadowfang_keep.h
instance_shadowfang_keep.cpp