CMaNGOS_WoTLK: AbstractWrapperMovementGenerator Class Reference
AbstractWrapperMovementGenerator Class Reference abstract
#include <WrapperMovementGenerator.h>
Public Member Functions
AbstractWrapperMovementGenerator (Movement::MoveSplineInit &spline, uint32 id=0, bool delayed=false, bool resident=true, ObjectGuid guid=ObjectGuid(), uint32 relayId=0)
void Initialize (Unit &owner) override
void Finalize (Unit &owner) override
void Interrupt (Unit &owner) override
void Reset (Unit &owner) override
bool Update (Unit &owner, const uint32 &) override
void UnitSpeedChanged () override=0
MovementGeneratorType GetMovementGeneratorType () const override=0
void Inform (Unit &owner)
Public Member Functions inherited from MovementGenerator
virtual ~MovementGenerator ()
virtual Unit * GetCurrentTarget () const
virtual bool GetResetPosition (Unit &, float &, float &, float &, float &) const
virtual bool IsReachable () const
virtual bool IsRemovedOnExpire () const
bool IsActive (Unit &u)
Protected Attributes
Movement::MoveSplineInit i_spline
uint32 i_id
bool i_delayed
bool i_resident
bool i_dispatched
bool i_informed
bool i_useTimer
bool i_timerSet
ShortTimeTracker m_delayTimer
ObjectGuid m_guid
uint32 m_relayId
Detailed Description
Definition at line 25 of file WrapperMovementGenerator.h.
Constructor & Destructor Documentation
AbstractWrapperMovementGenerator()
AbstractWrapperMovementGenerator::AbstractWrapperMovementGenerator (Movement::MoveSplineInit & spline, uint32 id = 0, bool delayed = false, bool resident = true, ObjectGuid guid = ObjectGuid(), uint32 relayId = 0) inline
Definition at line 28 of file WrapperMovementGenerator.h.
Member Function Documentation
Finalize()
void AbstractWrapperMovementGenerator::Finalize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in EffectMovementGenerator.
Definition at line 61 of file WrapperMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), i_informed, Inform(), Unit::InterruptMoving(), Unit::IsClientControlled(), Unit::movespline, and Unit::StopMoving().
Referenced by EffectMovementGenerator::Finalize().
GetMovementGeneratorType()
MovementGeneratorType AbstractWrapperMovementGenerator::GetMovementGeneratorType () const override pure virtual
Implements MovementGenerator.
Implemented in FallMovementGenerator, and EffectMovementGenerator.
Referenced by Inform().
Inform()
void AbstractWrapperMovementGenerator::Inform (Unit & owner)
Definition at line 117 of file WrapperMovementGenerator.cpp.
References Unit::AI(), EVENT_JUMP, Map::GetAnyTypeCreature(), WorldObject::GetMap(), GetMovementGeneratorType(), WorldObject::GetSpawnerGuid(), Object::GetTypeId(), Map::GetWorldObject(), i_id, i_informed, ObjectGuid::IsCreatureOrPet(), Creature::IsTemporarySummon(), m_guid, m_relayId, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), and TYPEID_UNIT.
Referenced by Finalize(), and Update().
Initialize()
void AbstractWrapperMovementGenerator::Initialize (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in EffectMovementGenerator.
Definition at line 26 of file WrapperMovementGenerator.cpp.
References Unit::AI(), Unit::Attack(), Unit::CanAttackInCombat(), Movement::MoveSpline::Finalized(), Movement::MoveSpline::GetFacing(), ObjectAccessor::GetUnit(), i_delayed, i_dispatched, i_id, i_spline, i_useTimer, Unit::InterruptMoving(), Unit::IsClientControlled(), Movement::MoveSpline::isFacingTarget(), UnitAI::IsMeleeEnabled(), Unit::IsPlayerControlled(), Movement::MoveSplineInit::Launch(), Unit::movespline, Unit::SetTarget(), Unit::StopMoving(), and Movement::FacingInfo::target.
Referenced by EffectMovementGenerator::Initialize(), and Reset().
Interrupt()
void AbstractWrapperMovementGenerator::Interrupt (Unit & owner) override virtual
Implements MovementGenerator.
Reimplemented in EffectMovementGenerator.
Definition at line 76 of file WrapperMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), i_dispatched, i_resident, Unit::InterruptMoving(), and Unit::movespline.
Referenced by EffectMovementGenerator::Interrupt().
Reset()
void AbstractWrapperMovementGenerator::Reset (Unit & owner) override virtual
Implements MovementGenerator.
Definition at line 82 of file WrapperMovementGenerator.cpp.
References Initialize().
UnitSpeedChanged()
void AbstractWrapperMovementGenerator::UnitSpeedChanged () override pure virtual
Reimplemented from MovementGenerator.
Implemented in EffectMovementGenerator.
Update()
bool AbstractWrapperMovementGenerator::Update (Unit & owner, const uint32 & diff) override virtual
Implements MovementGenerator.
Reimplemented in EffectMovementGenerator.
Definition at line 87 of file WrapperMovementGenerator.cpp.
References Movement::MoveSpline::Finalized(), i_delayed, i_dispatched, i_informed, i_spline, i_timerSet, i_useTimer, Inform(), Movement::MoveSplineInit::Launch(), m_delayTimer, Unit::movespline, ShortTimeTracker::Passed(), ShortTimeTracker::Reset(), and ShortTimeTracker::Update().
Referenced by EffectMovementGenerator::Update().
Field Documentation
i_delayed
bool AbstractWrapperMovementGenerator::i_delayed protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Initialize(), EffectMovementGenerator::Initialize(), Update(), and EffectMovementGenerator::Update().
i_dispatched
bool AbstractWrapperMovementGenerator::i_dispatched protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Initialize(), EffectMovementGenerator::Initialize(), Interrupt(), Update(), and EffectMovementGenerator::Update().
i_id
uint32 AbstractWrapperMovementGenerator::i_id protected
Definition at line 45 of file WrapperMovementGenerator.h.
Referenced by Inform(), and Initialize().
i_informed
bool AbstractWrapperMovementGenerator::i_informed protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Finalize(), Inform(), and Update().
i_resident
bool AbstractWrapperMovementGenerator::i_resident protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Interrupt().
i_spline
Movement::MoveSplineInit AbstractWrapperMovementGenerator::i_spline protected
Definition at line 44 of file WrapperMovementGenerator.h.
Referenced by Initialize(), and Update().
i_timerSet
bool AbstractWrapperMovementGenerator::i_timerSet protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Update().
i_useTimer
bool AbstractWrapperMovementGenerator::i_useTimer protected
Definition at line 46 of file WrapperMovementGenerator.h.
Referenced by Initialize(), and Update().
m_delayTimer
ShortTimeTracker AbstractWrapperMovementGenerator::m_delayTimer protected
Definition at line 47 of file WrapperMovementGenerator.h.
Referenced by Update().
m_guid
ObjectGuid AbstractWrapperMovementGenerator::m_guid protected
Definition at line 48 of file WrapperMovementGenerator.h.
Referenced by Inform().
m_relayId
uint32 AbstractWrapperMovementGenerator::m_relayId protected
Definition at line 49 of file WrapperMovementGenerator.h.
Referenced by Inform().
The documentation for this class was generated from the following files:
WrapperMovementGenerator.h
WrapperMovementGenerator.cpp