CMaNGOS_WoTLK: MaNGOS::MostHPMissingInRangeCheck Class Reference
MaNGOS::MostHPMissingInRangeCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
MostHPMissingInRangeCheck (Unit const *obj, float range, float hp, bool onlyInCombat, bool targetSelf)
WorldObject const & GetFocusObject () const
bool operator() (Unit *u)
Private Attributes
Unit const * i_obj
float i_range
float i_hp
bool i_onlyInCombat
bool i_targetSelf
Detailed Description
Definition at line 960 of file GridNotifiers.h.
Constructor & Destructor Documentation
MostHPMissingInRangeCheck()
MaNGOS::MostHPMissingInRangeCheck::MostHPMissingInRangeCheck (Unit const * obj, float range, float hp, bool onlyInCombat, bool targetSelf) inline
Definition at line 963 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::MostHPMissingInRangeCheck::GetFocusObject () const inline
Definition at line 964 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::MostHPMissingInRangeCheck::operator() (Unit * u) inline
Definition at line 965 of file GridNotifiers.h.
References Unit::CanAssist(), Unit::GetHealth(), Unit::GetMaxHealth(), i_hp, i_obj, i_onlyInCombat, i_range, i_targetSelf, Unit::IsAlive(), Unit::IsInCombat(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_hp
float MaNGOS::MostHPMissingInRangeCheck::i_hp private
Definition at line 986 of file GridNotifiers.h.
Referenced by operator()().
i_obj
Unit const* MaNGOS::MostHPMissingInRangeCheck::i_obj private
Definition at line 984 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_onlyInCombat
bool MaNGOS::MostHPMissingInRangeCheck::i_onlyInCombat private
Definition at line 987 of file GridNotifiers.h.
Referenced by operator()().
i_range
float MaNGOS::MostHPMissingInRangeCheck::i_range private
Definition at line 985 of file GridNotifiers.h.
Referenced by operator()().
i_targetSelf
bool MaNGOS::MostHPMissingInRangeCheck::i_targetSelf private
Definition at line 988 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h