CMaNGOS_WoTLK: Common.h File Reference
Common.h File Reference
#include "Platform/Define.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <cmath>
#include <errno.h>
#include <signal.h>
#include <assert.h>
#include <set>
#include <vector>
#include <list>
#include <string>
#include <map>
#include <queue>
#include <sstream>
#include <algorithm>
#include <unordered_map>
#include <unordered_set>
#include <chrono>
#include "Platform/Filesystem.h"
#include "Util/Errors.h"
#include "Multithreading/Threading.h"
#include <thread>
#include <float.h>
#include <cinttypes>
Data Structures
struct CMDebugCommandTableStruct
Macros
#define I32FMT "%08I32X"
#define I64FMT "%016I64X"
#define __STDC_FORMAT_MACROS
#define UI64FMTD "%" PRIu64
#define SI64FMTD "%" PRId64
#define SIZEFMTD "%Iu"
#define STRINGIZE(a) #a
#define MAKE_PAIR64(l, h) uint64(uint32(l) | (uint64(h) << 32))
#define PAIR64_HIPART(x) (uint32)((uint64(x) >> 32) & uint64(0x00000000FFFFFFFF))
#define PAIR64_LOPART(x) (uint32)(uint64(x) & uint64(0x00000000FFFFFFFF))
#define MAKE_PAIR32(l, h) uint32(uint16(l) | (uint32(h) << 16))
#define PAIR32_HIPART(x) uint16(((uint32(x) >> 16) & 0x0000FFFF))
#define PAIR32_LOPART(x) uint16((uint32(x) & 0x0000FFFF))
#define MAX_NETCLIENT_PACKET_SIZE (32767 - 1)
#define M_PI 3.14159265358979323846
#define M_PI_F float(M_PI)
#define countof(array) (sizeof(array) / sizeof((array)[0]))
Typedefs
typedef std::chrono::system_clock Clock
typedef std::chrono::time_point< std::chrono::system_clock, std::chrono::milliseconds > TimePoint
Enumerations
enum TimeConstants {
MINUTE = 60 , HOUR = MINUTE * 60 , DAY = HOUR * 24 , WEEK = DAY * 7 ,
MONTH = DAY * 30 , YEAR = MONTH * 12 , IN_MILLISECONDS = 1000
}
enum AccountTypes : uint32 {
SEC_PLAYER = 0 , SEC_MODERATOR = 1 , SEC_GAMEMASTER = 2 , SEC_ADMINISTRATOR = 3 ,
SEC_CONSOLE = 4
}
enum RealmFlags {
REALM_FLAG_NONE = 0x00 , REALM_FLAG_INVALID = 0x01 , REALM_FLAG_OFFLINE = 0x02 , REALM_FLAG_SPECIFYBUILD = 0x04 ,
REALM_FLAG_UNK1 = 0x08 , REALM_FLAG_UNK2 = 0x10 , REALM_FLAG_NEW_PLAYERS = 0x20 , REALM_FLAG_RECOMMENDED = 0x40 ,
REALM_FLAG_FULL = 0x80
}
enum CMDebugFlags { CMDEBUGFLAG_NONE = 0x00000000 , CMDEBUGFLAG_WP_PATH = 0x00000001 , CMDEBUGFLAG_DEV_USE1 = 0x80000000 , CMDEBUGFLAG_DEV_USE2 = 0x80000000 }
Functions
float finiteAlways (float f)
char * mangos_strdup (const char *source)
Variables
static const std::vector< CMDebugCommandTableStruct > CMDebugCommandTable
Macro Definition Documentation
__STDC_FORMAT_MACROS
#define __STDC_FORMAT_MACROS
Definition at line 82 of file Common.h.
countof
#define countof (array) (sizeof(array) / sizeof((array)[0]))
Definition at line 170 of file Common.h.
I32FMT
#define I32FMT "%08I32X"
Definition at line 64 of file Common.h.
I64FMT
#define I64FMT "%016I64X"
Definition at line 65 of file Common.h.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 162 of file Common.h.
M_PI_F
#define M_PI_F float(M_PI)
Definition at line 166 of file Common.h.
MAKE_PAIR32
#define MAKE_PAIR32 (l, h) uint32(uint16(l) | (uint32(h) << 16))
Definition at line 104 of file Common.h.
MAKE_PAIR64
#define MAKE_PAIR64 (l, h) uint64(uint32(l) | (uint64(h) << 32))
Definition at line 100 of file Common.h.
MAX_NETCLIENT_PACKET_SIZE
#define MAX_NETCLIENT_PACKET_SIZE (32767 - 1)
Definition at line 108 of file Common.h.
PAIR32_HIPART
#define PAIR32_HIPART (x) uint16(((uint32(x) >> 16) & 0x0000FFFF))
Definition at line 105 of file Common.h.
PAIR32_LOPART
#define PAIR32_LOPART (x) uint16((uint32(x) & 0x0000FFFF))
Definition at line 106 of file Common.h.
PAIR64_HIPART
#define PAIR64_HIPART (x) (uint32)((uint64(x) >> 32) & uint64(0x00000000FFFFFFFF))
Definition at line 101 of file Common.h.
PAIR64_LOPART
#define PAIR64_LOPART (x) (uint32)(uint64(x) & uint64(0x00000000FFFFFFFF))
Definition at line 102 of file Common.h.
SI64FMTD
#define SI64FMTD "%" PRId64
Definition at line 87 of file Common.h.
SIZEFMTD
#define SIZEFMTD "%Iu"
Definition at line 90 of file Common.h.
STRINGIZE
#define STRINGIZE (a) #a
Definition at line 97 of file Common.h.
UI64FMTD
#define UI64FMTD "%" PRIu64
Definition at line 85 of file Common.h.
Typedef Documentation
Clock
typedef std::chrono::system_clock Clock
Definition at line 57 of file Common.h.
TimePoint
typedef std::chrono::time_point<std::chrono::system_clock, std::chrono::milliseconds> TimePoint
Definition at line 58 of file Common.h.
Enumeration Type Documentation
AccountTypes
enum AccountTypes : uint32
Enumerator
SEC_PLAYER
SEC_MODERATOR
SEC_GAMEMASTER
SEC_ADMINISTRATOR
SEC_CONSOLE
Definition at line 121 of file Common.h.
CMDebugFlags
enum CMDebugFlags
Enumerator
CMDEBUGFLAG_NONE
CMDEBUGFLAG_WP_PATH
CMDEBUGFLAG_DEV_USE1
CMDEBUGFLAG_DEV_USE2
Definition at line 175 of file Common.h.
RealmFlags
enum RealmFlags
Enumerator
REALM_FLAG_NONE
REALM_FLAG_INVALID
REALM_FLAG_OFFLINE
REALM_FLAG_SPECIFYBUILD
REALM_FLAG_UNK1
REALM_FLAG_UNK2
REALM_FLAG_NEW_PLAYERS
REALM_FLAG_RECOMMENDED
REALM_FLAG_FULL
Definition at line 131 of file Common.h.
TimeConstants
enum TimeConstants
Enumerator
MINUTE
HOUR
DAY
WEEK
MONTH
YEAR
IN_MILLISECONDS
Definition at line 110 of file Common.h.
Function Documentation
finiteAlways()
float finiteAlways (float f) inline
Definition at line 95 of file Common.h.
Referenced by Player::SaveToDB().
mangos_strdup()
char* mangos_strdup (const char * source) inline
Definition at line 145 of file Common.h.
Referenced by ChatHandler::HandleTicketGoNameCommand(), ChatHandler::SendGlobalSysMessage(), ChatHandler::SendSysMessage(), and SqlQueryHolder::SetQuery().
Variable Documentation
CMDebugCommandTable
const std::vector<CMDebugCommandTableStruct> CMDebugCommandTable static
Initial value:
=
{
    { "clearall"                , "reset all flags"                         , CMDEBUGFLAG_NONE                  },
    { "setall"                  , "set all flags"                           , CMDEBUGFLAG_NONE                  },
    { "wppath"                  , "show waypoint path send to client"       , CMDEBUGFLAG_WP_PATH               },
    { "dev1"                    , "for general use during development"      , CMDEBUGFLAG_DEV_USE1              },
    { "dev2"                    , "for general use during development"      , CMDEBUGFLAG_DEV_USE2              }
}
Definition at line 196 of file Common.h.
Referenced by ChatHandler::HandleDebugObjectFlags().