CMaNGOS_WoTLK: Conditions.h File Reference
Conditions.h File Reference
#include "Globals/SharedDefines.h"
Data Structures
class ConditionEntry
Enumerations
enum ConditionType {
CONDITION_NOT = -3 , CONDITION_OR = -2 , CONDITION_AND = -1 , CONDITION_NONE = 0 ,
CONDITION_AURA = 1 , CONDITION_ITEM = 2 , CONDITION_ITEM_EQUIPPED = 3 , CONDITION_AREAID = 4 ,
CONDITION_REPUTATION_RANK_MIN = 5 , CONDITION_TEAM = 6 , CONDITION_SKILL = 7 , CONDITION_QUESTREWARDED = 8 ,
CONDITION_QUESTTAKEN = 9 , CONDITION_AD_COMMISSION_AURA = 10 , CONDITION_PVP_RANK = 11 , CONDITION_ACTIVE_GAME_EVENT = 12 ,
CONDITION_AREA_FLAG = 13 , CONDITION_RACE_CLASS = 14 , CONDITION_LEVEL = 15 , CONDITION_UNUSED_2 = 16 ,
CONDITION_SPELL = 17 , CONDITION_INSTANCE_SCRIPT = 18 , CONDITION_QUESTAVAILABLE = 19 , CONDITION_ACHIEVEMENT = 20 ,
CONDITION_ACHIEVEMENT_REALM = 21 , CONDITION_QUEST_NONE = 22 , CONDITION_ITEM_WITH_BANK = 23 , CONDITION_UNUSED_3 = 24 ,
CONDITION_UNUSED_4 = 25 , CONDITION_ACTIVE_HOLIDAY = 26 , CONDITION_UNUSED_5 = 27 , CONDITION_LEARNABLE_ABILITY = 28 ,
CONDITION_SKILL_BELOW = 29 , CONDITION_REPUTATION_RANK_MAX = 30 , CONDITION_COMPLETED_ENCOUNTER = 31 , CONDITION_UNUSED_6 = 32 ,
CONDITION_LAST_WAYPOINT = 33 , CONDITION_XP_USER = 34 , CONDITION_GENDER = 35 , CONDITION_DEAD_OR_AWAY = 36 ,
CONDITION_CREATURE_IN_RANGE = 37 , CONDITION_PVP_SCRIPT = 38 , CONDITION_SPAWN_COUNT = 39 , CONDITION_WORLD_SCRIPT = 40 ,
CONDITION_UNUSED_7 = 41 , CONDITION_WORLDSTATE = 42
}
enum ConditionFlags { CONDITION_FLAG_REVERSE_RESULT = 0x1 , CONDITION_FLAG_SWAP_TARGETS = 0x2 }
enum ConditionSource {
CONDITION_FROM_LOOT = 0 , CONDITION_FROM_REFERING_LOOT = 1 , CONDITION_FROM_GOSSIP_MENU = 2 , CONDITION_FROM_GOSSIP_OPTION = 3 ,
CONDITION_FROM_EVENTAI = 4 , CONDITION_FROM_HARDCODED = 5 , CONDITION_FROM_VENDOR = 6 , CONDITION_FROM_SPELL_AREA = 7 ,
CONDITION_FROM_SPELLCLICK = 8 , CONDITION_FROM_DBSCRIPTS = 9 , CONDITION_FROM_TRAINER = 10 , CONDITION_FROM_AREATRIGGER_TELEPORT = 11 ,
CONDITION_FROM_QUEST = 12 , CONDITION_FROM_WORLDSTATE = 13
}
enum ConditionRequirement {
CONDITION_REQ_NONE , CONDITION_REQ_TARGET_WORLDOBJECT , CONDITION_REQ_TARGET_GAMEOBJECT , CONDITION_REQ_TARGET_UNIT ,
CONDITION_REQ_TARGET_UNIT_OR_CORPSE , CONDITION_REQ_TARGET_CREATURE , CONDITION_REQ_TARGET_PLAYER , CONDITION_REQ_TARGET_PLAYER_OR_CORPSE ,
CONDITION_REQ_SOURCE_WORLDOBJECT , CONDITION_REQ_SOURCE_GAMEOBJECT , CONDITION_REQ_SOURCE_UNIT , CONDITION_REQ_SOURCE_CREATURE ,
CONDITION_REQ_SOURCE_PLAYER , CONDITION_REQ_ANY_WORLDOBJECT , CONDITION_REQ_MAP_OR_WORLDOBJECT , CONDITION_REQ_BOTH_WORLDOBJECTS ,
CONDITION_REQ_BOTH_GAMEOBJECTS , CONDITION_REQ_BOTH_UNITS , CONDITION_REQ_BOTH_PLAYERS
}
enum class ConditionOperation : uint8 {
NONE = 0 , EQUAL_TO = 1 , NOT_EQUAL_TO = 2 , LESS_THAN = 3 ,
LESS_THAN_OR_EQUAL_TO = 4 , GREATER_THAN = 5 , GREATER_THAN_OR_EQUAL_TO = 6 , MAX
}
enum class ConditionLogic : uint8 { NONE = 0 , AND = 1 , OR = 2 , XOR = 3 }
Functions
bool IsConditionSatisfied (uint32 conditionId, WorldObject const *target, Map const *map, WorldObject const *source, ConditionSource conditionSourceType)
Enumeration Type Documentation
ConditionFlags
enum ConditionFlags
Enumerator
CONDITION_FLAG_REVERSE_RESULT
CONDITION_FLAG_SWAP_TARGETS
Definition at line 84 of file Conditions.h.
ConditionLogic
enum ConditionLogic : uint8 strong
Enumerator
NONE
AND
OR
XOR
Definition at line 145 of file Conditions.h.
ConditionOperation
enum ConditionOperation : uint8 strong
Enumerator
NONE
EQUAL_TO
NOT_EQUAL_TO
LESS_THAN
LESS_THAN_OR_EQUAL_TO
GREATER_THAN
GREATER_THAN_OR_EQUAL_TO
MAX
Definition at line 132 of file Conditions.h.
ConditionRequirement
enum ConditionRequirement
Enumerator
CONDITION_REQ_NONE
CONDITION_REQ_TARGET_WORLDOBJECT
CONDITION_REQ_TARGET_GAMEOBJECT
CONDITION_REQ_TARGET_UNIT
CONDITION_REQ_TARGET_UNIT_OR_CORPSE
CONDITION_REQ_TARGET_CREATURE
CONDITION_REQ_TARGET_PLAYER
CONDITION_REQ_TARGET_PLAYER_OR_CORPSE
CONDITION_REQ_SOURCE_WORLDOBJECT
CONDITION_REQ_SOURCE_GAMEOBJECT
CONDITION_REQ_SOURCE_UNIT
CONDITION_REQ_SOURCE_CREATURE
CONDITION_REQ_SOURCE_PLAYER
CONDITION_REQ_ANY_WORLDOBJECT
CONDITION_REQ_MAP_OR_WORLDOBJECT
CONDITION_REQ_BOTH_WORLDOBJECTS
CONDITION_REQ_BOTH_GAMEOBJECTS
CONDITION_REQ_BOTH_UNITS
CONDITION_REQ_BOTH_PLAYERS
Definition at line 108 of file Conditions.h.
ConditionSource
enum ConditionSource
Enumerator
CONDITION_FROM_LOOT
CONDITION_FROM_REFERING_LOOT
CONDITION_FROM_GOSSIP_MENU
CONDITION_FROM_GOSSIP_OPTION
CONDITION_FROM_EVENTAI
CONDITION_FROM_HARDCODED
CONDITION_FROM_VENDOR
CONDITION_FROM_SPELL_AREA
CONDITION_FROM_SPELLCLICK
CONDITION_FROM_DBSCRIPTS
CONDITION_FROM_TRAINER
CONDITION_FROM_AREATRIGGER_TELEPORT
CONDITION_FROM_QUEST
CONDITION_FROM_WORLDSTATE
Definition at line 90 of file Conditions.h.
ConditionType
enum ConditionType
Enumerator
CONDITION_NOT
CONDITION_OR
CONDITION_AND
CONDITION_NONE
CONDITION_AURA
CONDITION_ITEM
CONDITION_ITEM_EQUIPPED
CONDITION_AREAID
CONDITION_REPUTATION_RANK_MIN
CONDITION_TEAM
CONDITION_SKILL
CONDITION_QUESTREWARDED
CONDITION_QUESTTAKEN
CONDITION_AD_COMMISSION_AURA
CONDITION_PVP_RANK
CONDITION_ACTIVE_GAME_EVENT
CONDITION_AREA_FLAG
CONDITION_RACE_CLASS
CONDITION_LEVEL
CONDITION_UNUSED_2
CONDITION_SPELL
CONDITION_INSTANCE_SCRIPT
CONDITION_QUESTAVAILABLE
CONDITION_ACHIEVEMENT
CONDITION_ACHIEVEMENT_REALM
CONDITION_QUEST_NONE
CONDITION_ITEM_WITH_BANK
CONDITION_UNUSED_3
CONDITION_UNUSED_4
CONDITION_ACTIVE_HOLIDAY
CONDITION_UNUSED_5
CONDITION_LEARNABLE_ABILITY
CONDITION_SKILL_BELOW
CONDITION_REPUTATION_RANK_MAX
CONDITION_COMPLETED_ENCOUNTER
CONDITION_UNUSED_6
CONDITION_LAST_WAYPOINT
CONDITION_XP_USER
CONDITION_GENDER
CONDITION_DEAD_OR_AWAY
CONDITION_CREATURE_IN_RANGE
CONDITION_PVP_SCRIPT
CONDITION_SPAWN_COUNT
CONDITION_WORLD_SCRIPT
CONDITION_UNUSED_7
CONDITION_WORLDSTATE
Definition at line 27 of file Conditions.h.
Function Documentation
IsConditionSatisfied()
bool IsConditionSatisfied (uint32 conditionId, WorldObject const * target, Map const * map, WorldObject const * source, ConditionSource conditionSourceType)
Definition at line 1060 of file Conditions.cpp.
References SQLStorage::LookupEntry(), and sConditionStorage.
Referenced by SpawnGroup::IsWorldstateConditionSatisfied(), and AchievementCriteriaRequirement::Meets().