CMaNGOS_WoTLK: Conditions.cpp File Reference
Conditions.cpp File Reference
#include "Globals/Conditions.h"
#include "Entities/Unit.h"
#include "Entities/Player.h"
#include "GameEvents/GameEventMgr.h"
#include "Spells/SpellAuras.h"
#include "World/World.h"
#include "World/WorldState.h"
#include "Maps/InstanceData.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/CellImpl.h"
#include "Spells/SpellMgr.h"
Functions
bool IsConditionSatisfied (uint32 conditionId, WorldObject const *target, Map const *map, WorldObject const *source, ConditionSource conditionSourceType)
Variables
char const * conditionSourceToStr []
uint8 const ConditionTargetsInternal []
uint8 const * ConditionTargets = &ConditionTargetsInternal[3]
Function Documentation
IsConditionSatisfied()
bool IsConditionSatisfied (uint32 conditionId, WorldObject const * target, Map const * map, WorldObject const * source, ConditionSource conditionSourceType)
Definition at line 1060 of file Conditions.cpp.
References SQLStorage::LookupEntry(), and sConditionStorage.
Referenced by SpawnGroup::IsWorldstateConditionSatisfied(), and AchievementCriteriaRequirement::Meets().
Variable Documentation
conditionSourceToStr
char const* conditionSourceToStr[]
Initial value:
=
{
    "loot system",
    "referencing loot",
    "gossip menu",
    "gossip menu option",
    "event AI",
    "hardcoded",
    "vendor's item check",
    "spell_area check",
    "npc_spellclick_spells check",
    "DBScript engine",
    "trainer's spell check",
    "areatrigger teleport check",
    "quest template",
    "world state"
}
Definition at line 34 of file Conditions.cpp.
Referenced by ConditionEntry::Evaluate(), and ConditionEntry::Meets().
ConditionTargets
uint8 const* ConditionTargets = &ConditionTargetsInternal[3]
Definition at line 105 of file Conditions.cpp.
Referenced by ConditionEntry::CanBeUsedWithoutPlayer(), and ConditionEntry::CheckParamRequirements().
ConditionTargetsInternal
uint8 const ConditionTargetsInternal[]
Definition at line 54 of file Conditions.cpp.