CMaNGOS_WoTLK: culling_of_stratholme.cpp File Reference
culling_of_stratholme.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "culling_of_stratholme.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_arthasAI
Enumerations
enum {
QUEST_DISPELLING_ILLUSIONS = 13149 , QUEST_A_ROYAL_ESCORT = 13151 , ITEM_ARCANE_DISRUPTOR = 37888 , GOSSIP_ITEM_ENTRANCE_1 = -3595000 ,
GOSSIP_ITEM_ENTRANCE_2 = -3595001 , GOSSIP_ITEM_ENTRANCE_3 = -3595002 , TEXT_ID_ENTRANCE_1 = 12992 , TEXT_ID_ENTRANCE_2 = 12993 ,
TEXT_ID_ENTRANCE_3 = 12994 , TEXT_ID_ENTRANCE_4 = 12995 , GOSSIP_ITEM_INN_1 = -3595003 , GOSSIP_ITEM_INN_2 = -3595004 ,
GOSSIP_ITEM_INN_3 = -3595005 , GOSSIP_ITEM_INN_SKIP = -3595006 , GOSSIP_ITEM_INN_TELEPORT = -3595007 , TEXT_ID_INN_1 = 12939 ,
TEXT_ID_INN_2 = 12949 , TEXT_ID_INN_3 = 12950 , TEXT_ID_INN_4 = 12952 , TEXT_ID_INN_TELEPORT = 13470 ,
SPELL_TELEPORT_COT_P4 = 53435
}
enum { SAY_SOLDIERS_REPORT = -1595000 , SPELL_ARCANE_DISRUPTION = 49590 , SPELL_CRATES_KILL_CREDIT = 58109 }
enum {
SAY_ARTHAS_FOLLOW = -1595009 , SAY_CITIZEN_ARRIVED = -1595010 , SAY_ARTHAS_BEFORE_PLAGUE = -1595011 , SAY_ARTHAS_SORCERY = -1595012 ,
SAY_CITIZEN_NO_UNDERSTAD = -1595013 , SAY_ARTHAS_MORE_SCOURGE = -1595014 , SAY_ARTHAS_MORE_SORCERY = -1595015 , SAY_ARTHAS_MOVE_ON = -1595016 ,
SAY_ARTHAS_WATCH_BACK = -1595017 , SAY_ARTHAS_NOT_EASY = -1595018 , SAY_ARTHAS_PERSISTENT = -1595019 , SAY_ARTHAS_WHAT_ELSE = -1595020 ,
SAY_EPOCH_DARKNESS = -1595021 , SAY_ARTHAS_DO_WHAT_MUST = -1595022 , SAY_ARTHAS_QUICK_PATH = -1595023 , SAY_ARTHAS_TAKE_A_MOMENT = -1595024 ,
SAY_ARTHAS_PASSAGE = -1595025 , SAY_ARTHAS_MOVE_QUICKLY = -1595026 , SAY_ARTHAS_REST = -1595027 , SAY_ARTHAS_REST_COMPLETE = -1595028 ,
SAY_ARTHAS_CRUSADER_SQUARE = -1595029 , SAY_ARTHAS_JUSTICE_DONE = -1595030 , SAY_ARTHAS_MALGANIS = -1595031 , SAY_MALGANIS_JOURNEY = -1595032 ,
SAY_ARTHAS_HUNT_MALGANIS = -1595033 , SAY_ARTHAS_EVENT_COMPLETE = -1595034 , SAY_ARTHAS_HALF_HP = -1595035 , SAY_ARTHAS_LOW_HP = -1595036 ,
SAY_ARTHAS_SLAY_1 = -1595037 , SAY_ARTHAS_SLAY_2 = -1595038 , SAY_ARTHAS_SLAY_3 = -1595039 , SAY_ARTHAS_DEATH = -1595040 ,
MUSIC_ID_EVENT_COMPLETE = 14951 , GOSSIP_ITEM_CITY_GATES = -3595008 , GOSSIP_ITEM_TOWN_HALL_1 = -3595009 , GOSSIP_ITEM_TOWN_HALL_2 = -3595010 ,
GOSSIP_ITEM_EPOCH = -3595011 , GOSSIP_ITEM_ESCORT = -3595012 , GOSSIP_ITEM_DREADLORD = -3595013 , TEXT_ID_CITY_GATES = 13076 ,
TEXT_ID_TOWN_HALL_1 = 13125 , TEXT_ID_TOWN_HALL_2 = 13126 , TEXT_ID_EPOCH = 13177 , TEXT_ID_ESCORT = 13179 ,
TEXT_ID_DREADLORD = 13287 , SPELL_HOLY_LIGHT = 52444 , SPELL_EXORCISM = 52445 , SPELL_EXORCISM_H = 58822 ,
SPELL_DEVOTION_AURA = 52442 , SPELL_CRUSADER_STRIKE = 50773 , SPELL_MALGANIS_KILL_CREDIT = 58124 , SPELL_MALGANIS_ACHIEVEMENT = 58630 ,
SPELL_TRANSFORM = 33133 , SPELL_SHADOWSTEP_COSMETIC = 51908 , FACTION_ARTHAS_2 = 2077 , POINT_ID_INTRO_COMPLETE = 31 ,
POINT_ID_ESCORT_CITY = 47 , POINT_ID_MARKET_ROW = 70
}
Functions
bool GossipHello_npc_chromie (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_chromie (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool QuestAccept_npc_chromie (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool EffectAuraDummy_spell_aura_dummy_npc_crates_dummy (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_arthas (Creature *pCreature)
bool GossipHello_npc_arthas (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_arthas (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool EffectDummyCreature_npc_spell_dummy_crusader_strike (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_culling_of_stratholme ()
Variables
static const DialogueEntry aArthasDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_DISPELLING_ILLUSIONS
QUEST_A_ROYAL_ESCORT
ITEM_ARCANE_DISRUPTOR
GOSSIP_ITEM_ENTRANCE_1
GOSSIP_ITEM_ENTRANCE_2
GOSSIP_ITEM_ENTRANCE_3
TEXT_ID_ENTRANCE_1
TEXT_ID_ENTRANCE_2
TEXT_ID_ENTRANCE_3
TEXT_ID_ENTRANCE_4
GOSSIP_ITEM_INN_1
GOSSIP_ITEM_INN_2
GOSSIP_ITEM_INN_3
GOSSIP_ITEM_INN_SKIP
GOSSIP_ITEM_INN_TELEPORT
TEXT_ID_INN_1
TEXT_ID_INN_2
TEXT_ID_INN_3
TEXT_ID_INN_4
TEXT_ID_INN_TELEPORT
SPELL_TELEPORT_COT_P4
Definition at line 33 of file culling_of_stratholme.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_SOLDIERS_REPORT
SPELL_ARCANE_DISRUPTION
SPELL_CRATES_KILL_CREDIT
Definition at line 203 of file culling_of_stratholme.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ARTHAS_FOLLOW
SAY_CITIZEN_ARRIVED
SAY_ARTHAS_BEFORE_PLAGUE
SAY_ARTHAS_SORCERY
SAY_CITIZEN_NO_UNDERSTAD
SAY_ARTHAS_MORE_SCOURGE
SAY_ARTHAS_MORE_SORCERY
SAY_ARTHAS_MOVE_ON
SAY_ARTHAS_WATCH_BACK
SAY_ARTHAS_NOT_EASY
SAY_ARTHAS_PERSISTENT
SAY_ARTHAS_WHAT_ELSE
SAY_EPOCH_DARKNESS
SAY_ARTHAS_DO_WHAT_MUST
SAY_ARTHAS_QUICK_PATH
SAY_ARTHAS_TAKE_A_MOMENT
SAY_ARTHAS_PASSAGE
SAY_ARTHAS_MOVE_QUICKLY
SAY_ARTHAS_REST
SAY_ARTHAS_REST_COMPLETE
SAY_ARTHAS_CRUSADER_SQUARE
SAY_ARTHAS_JUSTICE_DONE
SAY_ARTHAS_MALGANIS
SAY_MALGANIS_JOURNEY
SAY_ARTHAS_HUNT_MALGANIS
SAY_ARTHAS_EVENT_COMPLETE
SAY_ARTHAS_HALF_HP
SAY_ARTHAS_LOW_HP
SAY_ARTHAS_SLAY_1
SAY_ARTHAS_SLAY_2
SAY_ARTHAS_SLAY_3
SAY_ARTHAS_DEATH
MUSIC_ID_EVENT_COMPLETE
GOSSIP_ITEM_CITY_GATES
GOSSIP_ITEM_TOWN_HALL_1
GOSSIP_ITEM_TOWN_HALL_2
GOSSIP_ITEM_EPOCH
GOSSIP_ITEM_ESCORT
GOSSIP_ITEM_DREADLORD
TEXT_ID_CITY_GATES
TEXT_ID_TOWN_HALL_1
TEXT_ID_TOWN_HALL_2
TEXT_ID_EPOCH
TEXT_ID_ESCORT
TEXT_ID_DREADLORD
SPELL_HOLY_LIGHT
SPELL_EXORCISM
SPELL_EXORCISM_H
SPELL_DEVOTION_AURA
SPELL_CRUSADER_STRIKE
SPELL_MALGANIS_KILL_CREDIT
SPELL_MALGANIS_ACHIEVEMENT
SPELL_TRANSFORM
SPELL_SHADOWSTEP_COSMETIC
FACTION_ARTHAS_2
POINT_ID_INTRO_COMPLETE
POINT_ID_ESCORT_CITY
POINT_ID_MARKET_ROW
Definition at line 296 of file culling_of_stratholme.cpp.
Function Documentation
AddSC_culling_of_stratholme()
void AddSC_culling_of_stratholme ()
Definition at line 984 of file culling_of_stratholme.cpp.
References EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), EffectDummyCreature_npc_spell_dummy_crusader_strike(), Script::GetAI, GetAI_npc_arthas(), GossipHello_npc_arthas(), GossipHello_npc_chromie(), GossipSelect_npc_arthas(), GossipSelect_npc_chromie(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_chromie(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_npc_crates_dummy()
bool EffectAuraDummy_spell_aura_dummy_npc_crates_dummy (const Aura * pAura, bool bApply)
Definition at line 211 of file culling_of_stratholme.cpp.
References DONE, EFFECT_INDEX_0, GetClosestGameObjectWithEntry(), Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), GO_CRATE_HIGHLIGHT, GO_JUST_DEACTIVATED, GO_PLAGUE_GRAIN_CRATE, GO_SUSPICIOUS_GRAIN_CRATE, HOUR, IN_MILLISECONDS, NPC_BARTLEBY_BATTSON, NPC_GRAIN_CRATE_HELPER, NPC_JENA_ANDERSON, NPC_LORDAERON_CRIER, NPC_MALCOM_MOORE, NPC_ROGER_OWENS, NPC_SERGEANT_MORIGAN, SAY_SOLDIERS_REPORT, SPELL_ARCANE_DISRUPTION, SPELL_CRATES_KILL_CREDIT, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_GRAIN_EVENT, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_culling_of_stratholme().
EffectDummyCreature_npc_spell_dummy_crusader_strike()
bool EffectDummyCreature_npc_spell_dummy_crusader_strike (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 969 of file culling_of_stratholme.cpp.
References EFFECT_INDEX_0, Object::GetEntry(), NPC_STRATHOLME_CITIZEN, NPC_STRATHOLME_RESIDENT, SPELL_CRUSADER_STRIKE, and Unit::Suicide().
Referenced by AddSC_culling_of_stratholme().
GetAI_npc_arthas()
UnitAI* GetAI_npc_arthas (Creature * pCreature)
Definition at line 880 of file culling_of_stratholme.cpp.
Referenced by AddSC_culling_of_stratholme().
GossipHello_npc_arthas()
bool GossipHello_npc_arthas (Player * pPlayer, Creature * pCreature)
Definition at line 885 of file culling_of_stratholme.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_CITY_GATES, GOSSIP_ITEM_DREADLORD, GOSSIP_ITEM_EPOCH, GOSSIP_ITEM_ESCORT, GOSSIP_ITEM_TOWN_HALL_1, GOSSIP_SENDER_MAIN, IN_PROGRESS, TEXT_ID_CITY_GATES, TEXT_ID_DREADLORD, TEXT_ID_EPOCH, TEXT_ID_ESCORT, TEXT_ID_TOWN_HALL_1, TYPE_ARTHAS_ESCORT_EVENT, TYPE_ARTHAS_INTRO_EVENT, TYPE_ARTHAS_TOWNHALL_EVENT, TYPE_EPOCH_EVENT, TYPE_MALGANIS_EVENT, and TYPE_SALRAMM_EVENT.
Referenced by AddSC_culling_of_stratholme().
GossipHello_npc_chromie()
bool GossipHello_npc_chromie (Player * pPlayer, Creature * pCreature)
Definition at line 64 of file culling_of_stratholme.cpp.
References DONE, Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetQuestRewardStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ENTRANCE_1, GOSSIP_ITEM_INN_1, GOSSIP_ITEM_INN_SKIP, GOSSIP_SENDER_MAIN, Player::HasItemCount(), Unit::isQuestGiver(), ITEM_ARCANE_DISRUPTOR, NOT_STARTED, NPC_CHROMIE_ENTRANCE, NPC_CHROMIE_INN, Player::PrepareQuestMenu(), QUEST_A_ROYAL_ESCORT, QUEST_DISPELLING_ILLUSIONS, TEXT_ID_ENTRANCE_1, TEXT_ID_INN_1, TYPE_ARTHAS_INTRO_EVENT, and TYPE_GRAIN_EVENT.
Referenced by AddSC_culling_of_stratholme().
GossipSelect_npc_arthas()
bool GossipSelect_npc_arthas (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 923 of file culling_of_stratholme.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, AI_EVENT_START_ESCORT, AI_EVENT_START_ESCORT_B, Unit::clearUnitState(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TOWN_HALL_2, GOSSIP_SENDER_MAIN, Object::RemoveFlag(), UnitAI::SendAIEvent(), TEXT_ID_TOWN_HALL_2, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and UNIT_STAT_WAYPOINT_PAUSED.
Referenced by AddSC_culling_of_stratholme().
GossipSelect_npc_chromie()
bool GossipSelect_npc_chromie (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 93 of file culling_of_stratholme.cpp.
References Unit::CastSpell(), DONE, Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ENTRANCE_2, GOSSIP_ITEM_ENTRANCE_3, GOSSIP_ITEM_INN_2, GOSSIP_ITEM_INN_3, GOSSIP_ITEM_INN_TELEPORT, GOSSIP_SENDER_MAIN, Player::HasItemCount(), IN_PROGRESS, ITEM_ARCANE_DISRUPTOR, NOT_STARTED, NPC_CHROMIE_ENTRANCE, NPC_CHROMIE_INN, Player::SendNewItem(), SPECIAL, SPELL_TELEPORT_COT_P4, Player::StoreNewItemInInventorySlot(), TEXT_ID_ENTRANCE_2, TEXT_ID_ENTRANCE_3, TEXT_ID_ENTRANCE_4, TEXT_ID_INN_2, TEXT_ID_INN_3, TEXT_ID_INN_4, TEXT_ID_INN_TELEPORT, TRIGGERED_OLD_TRIGGERED, TYPE_ARTHAS_INTRO_EVENT, and TYPE_GRAIN_EVENT.
Referenced by AddSC_culling_of_stratholme().
QuestAccept_npc_chromie()
bool QuestAccept_npc_chromie (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 174 of file culling_of_stratholme.cpp.
References WorldObject::GetInstanceData(), Quest::GetQuestId(), IN_PROGRESS, NOT_STARTED, QUEST_A_ROYAL_ESCORT, QUEST_DISPELLING_ILLUSIONS, SPECIAL, TYPE_ARTHAS_INTRO_EVENT, and TYPE_GRAIN_EVENT.
Referenced by AddSC_culling_of_stratholme().
Variable Documentation
aArthasDialogue
const DialogueEntry aArthasDialogue[] static
Definition at line 375 of file culling_of_stratholme.cpp.