CMaNGOS_WoTLK: dalaran.cpp File Reference
dalaran.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "AI/ScriptDevAI//scripts/northrend/world_northrend.h"
Data Structures
struct npc_dalaran_guardian_mageAI
struct spell_teleporting_dalaran
Enumerations
enum {
SPELL_TRESPASSER_H = 54029 , SPELL_TRESPASSER_A = 54028 , SPELL_COVENANT_DISGUISE_1 = 70971 , SPELL_COVENANT_DISGUISE_2 = 70972 ,
SPELL_SUNREAVER_DISGUISE_1 = 70973 , SPELL_SUNREAVER_DISGUISE_2 = 70974 , AREA_ID_SUNREAVER = 4616 , AREA_ID_SILVER_ENCLAVE = 4740
}
enum { NPC_SILVER_COVENANT_AGENT = 36774 , ITEM_SILVER_COVENANT_ORDERS = 49872 , QUEST_THE_SILVER_COVENANTS_SCHEME = 24557 }
enum { NPC_SUNREAVER_AGENT = 36776 , ITEM_SUNREAVER_ORDERS = 49536 , QUEST_THE_SUNREAVER_PLAN = 14457 }
Functions
bool AreaTrigger_at_underbelly_h (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_underbelly_a (Player *player, AreaTriggerEntry const *)
void AddSC_dalaran ()
Variables
static const Position m_silvercovenantagent = { 5816.17f, 760.211f, 640.561f, 1.75213f }
static const Position m_sunreaveragent = { 5783.11f, 534.748f, 641.56f, 6.27889f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_TRESPASSER_H
SPELL_TRESPASSER_A
SPELL_COVENANT_DISGUISE_1
SPELL_COVENANT_DISGUISE_2
SPELL_SUNREAVER_DISGUISE_1
SPELL_SUNREAVER_DISGUISE_2
AREA_ID_SUNREAVER
AREA_ID_SILVER_ENCLAVE
Definition at line 33 of file dalaran.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_SILVER_COVENANT_AGENT
ITEM_SILVER_COVENANT_ORDERS
QUEST_THE_SILVER_COVENANTS_SCHEME
Definition at line 116 of file dalaran.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_SUNREAVER_AGENT
ITEM_SUNREAVER_ORDERS
QUEST_THE_SUNREAVER_PLAN
Definition at line 165 of file dalaran.cpp.
Function Documentation
AddSC_dalaran()
void AddSC_dalaran ()
Definition at line 210 of file dalaran.cpp.
References AreaTrigger_at_underbelly_a(), AreaTrigger_at_underbelly_h(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_underbelly_a()
bool AreaTrigger_at_underbelly_a (Player * player, AreaTriggerEntry const *)
Definition at line 174 of file dalaran.cpp.
References AI_EVENT_CUSTOM_EVENTAI_B, GetCreatureListWithEntryInGrid(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetQuestStatus(), Player::HasItemCount(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), ITEM_SUNREAVER_ORDERS, m_sunreaveragent, MINUTE, NPC_SUNREAVER_AGENT, Position::o, QUEST_STATUS_NONE, QUEST_THE_SUNREAVER_PLAN, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, Position::x, Position::y, and Position::z.
Referenced by AddSC_dalaran().
AreaTrigger_at_underbelly_h()
bool AreaTrigger_at_underbelly_h (Player * player, AreaTriggerEntry const *)
Definition at line 125 of file dalaran.cpp.
References AI_EVENT_CUSTOM_EVENTAI_B, GetCreatureListWithEntryInGrid(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetQuestStatus(), Player::HasItemCount(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), ITEM_SILVER_COVENANT_ORDERS, m_silvercovenantagent, MINUTE, NPC_SILVER_COVENANT_AGENT, Position::o, QUEST_STATUS_NONE, QUEST_THE_SILVER_COVENANTS_SCHEME, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, Position::x, Position::y, and Position::z.
Referenced by AddSC_dalaran().
Variable Documentation
m_silvercovenantagent
const Position m_silvercovenantagent = { 5816.17f, 760.211f, 640.561f, 1.75213f } static
Definition at line 123 of file dalaran.cpp.
Referenced by AreaTrigger_at_underbelly_h().
m_sunreaveragent
const Position m_sunreaveragent = { 5783.11f, 534.748f, 641.56f, 6.27889f } static
Definition at line 172 of file dalaran.cpp.
Referenced by AreaTrigger_at_underbelly_a().