CMaNGOS_WoTLK: darkshore.cpp File Reference
darkshore.cpp File Reference
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Grids/GridNotifiers.h"
#include "Grids/CellImpl.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
#include "Entities/UpdateData.h"
Data Structures
struct npc_kerlonianAI
struct npc_prospector_remtravelAI
struct npc_threshwackonatorAI
struct SummonLocation
struct npc_volcorAI
struct npc_theryluneAI
struct npc_rabid_bearAI
struct npc_corrupted_furbolgAI
Enumerations
enum {
SAY_KER_START = -1000434 , EMOTE_KER_SLEEP_1 = -1000435 , EMOTE_KER_SLEEP_2 = -1000436 , EMOTE_KER_SLEEP_3 = -1000437 ,
SAY_KER_SLEEP_1 = -1000438 , SAY_KER_SLEEP_2 = -1000439 , SAY_KER_SLEEP_3 = -1000440 , SAY_KER_SLEEP_4 = -1000441 ,
EMOTE_KER_AWAKEN = -1000445 , SAY_KER_ALERT_1 = -1000442 , SAY_KER_ALERT_2 = -1000443 , SAY_KER_END = -1000444 ,
SPELL_BEAR_FORM = 18309 , SPELL_SLEEP_VISUAL = 25148 , SPELL_AWAKEN = 17536 , QUEST_SLEEPER_AWAKENED = 5321 ,
NPC_LILADRIS = 11219
}
enum {
SAY_REM_START = -1000327 , SAY_REM_AGGRO = -1000339 , SAY_REM_RAMP1_1 = -1000328 , SAY_REM_RAMP1_2 = -1000329 ,
SAY_REM_BOOK = -1000330 , SAY_REM_TENT1_1 = -1000331 , SAY_REM_TENT1_2 = -1000332 , SAY_REM_MOSS = -1000333 ,
EMOTE_REM_MOSS = -1000334 , SAY_REM_MOSS_PROGRESS = -1000335 , SAY_REM_PROGRESS = -1000336 , SAY_REM_REMEMBER = -1000337 ,
EMOTE_REM_END = -1000338 , QUEST_ABSENT_MINDED_PT2 = 731 , NPC_GRAVEL_SCOUT = 2158 , NPC_GRAVEL_BONE = 2159 ,
NPC_GRAVEL_GEO = 2160
}
enum {
EMOTE_START = -1000325 , SAY_AT_CLOSE = -1000326 , QUEST_GYROMAST_REV = 2078 , NPC_GELKAK = 6667 ,
FACTION_HOSTILE = 14 , TEXT_ID_THRESH_DEFAULT = 718 , TEXT_ID_KEY_READY = 758 , GOSSIP_ITEM_TURN_KEY = -3000115
}
enum {
SAY_START = -1000789 , SAY_END = -1000790 , SAY_FIRST_AMBUSH = -1000791 , SAY_AGGRO_1 = -1000792 ,
SAY_AGGRO_2 = -1000793 , SAY_AGGRO_3 = -1000794 , SAY_ESCAPE = -1000195 , NPC_BLACKWOOD_SHAMAN = 2171 ,
NPC_BLACKWOOD_URSA = 2170 , SPELL_MOONSTALKER_FORM = 10849 , WAYPOINT_ID_QUEST_STEALTH = 16 , FACTION_FRIENDLY = 35 ,
QUEST_ESCAPE_THROUGH_FORCE = 994 , QUEST_ESCAPE_THROUGH_STEALTH = 995
}
enum { SAY_THERYLUNE_START = -1000905 , SAY_THERYLUNE_FINISH = -1000906 , NPC_THERYSIL = 3585 , QUEST_ID_THERYLUNE_ESCAPE = 945 }
enum {
QUEST_PLAGUED_LANDS = 2118 , NPC_CAPTURED_RABID_THISTLE_BEAR = 11836 , NPC_THARNARIUN_TREETENDER = 3701 , GO_NIGHT_ELVEN_BEAR_TRAP = 111148 ,
SPELL_RABIES = 3150 , SPELL_BEAR_CAPTURED = 9439
}
enum {
NPC_BLACKWOOD_WARRIOR = 2168 , NPC_BLACKWOOD_TOTEMIC = 2169 , GO_PURIFIED_FOOD = 175336 , FACTION_BLACKWOOD = 35 ,
EMOTE_LURED = -1010027 , EMOTE_PURIFIED = -1010028 , EMOTE_GENERIC_FLEE = -1000007 , SPELL_BATTLE_STANCE = 7165 ,
SPELL_THUNDERCLAP = 8078 , SPELL_HEALING_WARD = 5605 , EVENT_BECOME_PURIFIED = 0 , EVENT_FURBOLG_RESET = 1 ,
EVENT_START_PURIFICATION = 2 , ACTION_FLEE = 3 , ACTION_THUNDERCLAP = 4 , ACTION_HEALING_WARD = 5 ,
ACTION_MAX = 6 , BOWL_DISTANCE = 5
}
Functions
UnitAI * GetAI_npc_kerlonian (Creature *pCreature)
bool QuestAccept_npc_kerlonian (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool EffectDummyCreature_awaken_kerlonian (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_prospector_remtravel (Creature *pCreature)
bool QuestAccept_npc_prospector_remtravel (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_threshwackonator (Creature *pCreature)
bool GossipHello_npc_threshwackonator (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_threshwackonator (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_volcor (Creature *pCreature)
bool QuestAccept_npc_volcor (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_therylune (Creature *pCreature)
bool QuestAccept_npc_therylune (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_rabid_bear (Creature *pCreature)
bool ProcessEventId_event_purify_food (uint32, Object *source, Object *target, bool)
bool GOUse_go_furbolg_food (Player *player, GameObject *go)
void AddSC_darkshore ()
Variables
static const SummonLocation aVolcorSpawnLocs []
static const std::vector< uint32 > furbolgList = { NPC_BLACKWOOD_WARRIOR, NPC_BLACKWOOD_TOTEMIC }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_KER_START
EMOTE_KER_SLEEP_1
EMOTE_KER_SLEEP_2
EMOTE_KER_SLEEP_3
SAY_KER_SLEEP_1
SAY_KER_SLEEP_2
SAY_KER_SLEEP_3
SAY_KER_SLEEP_4
EMOTE_KER_AWAKEN
SAY_KER_ALERT_1
SAY_KER_ALERT_2
SAY_KER_END
SPELL_BEAR_FORM
SPELL_SLEEP_VISUAL
SPELL_AWAKEN
QUEST_SLEEPER_AWAKENED
NPC_LILADRIS
Definition at line 50 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_REM_START
SAY_REM_AGGRO
SAY_REM_RAMP1_1
SAY_REM_RAMP1_2
SAY_REM_BOOK
SAY_REM_TENT1_1
SAY_REM_TENT1_2
SAY_REM_MOSS
EMOTE_REM_MOSS
SAY_REM_MOSS_PROGRESS
SAY_REM_PROGRESS
SAY_REM_REMEMBER
EMOTE_REM_END
QUEST_ABSENT_MINDED_PT2
NPC_GRAVEL_SCOUT
NPC_GRAVEL_BONE
NPC_GRAVEL_GEO
Definition at line 226 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_START
SAY_AT_CLOSE
QUEST_GYROMAST_REV
NPC_GELKAK
FACTION_HOSTILE
TEXT_ID_THRESH_DEFAULT
TEXT_ID_KEY_READY
GOSSIP_ITEM_TURN_KEY
Definition at line 352 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_END
SAY_FIRST_AMBUSH
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_ESCAPE
NPC_BLACKWOOD_SHAMAN
NPC_BLACKWOOD_URSA
SPELL_MOONSTALKER_FORM
WAYPOINT_ID_QUEST_STEALTH
FACTION_FRIENDLY
QUEST_ESCAPE_THROUGH_FORCE
QUEST_ESCAPE_THROUGH_STEALTH
Definition at line 435 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_THERYLUNE_START
SAY_THERYLUNE_FINISH
NPC_THERYSIL
QUEST_ID_THERYLUNE_ESCAPE
Definition at line 599 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_PLAGUED_LANDS
NPC_CAPTURED_RABID_THISTLE_BEAR
NPC_THARNARIUN_TREETENDER
GO_NIGHT_ELVEN_BEAR_TRAP
SPELL_RABIES
SPELL_BEAR_CAPTURED
Definition at line 663 of file darkshore.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_BLACKWOOD_WARRIOR
NPC_BLACKWOOD_TOTEMIC
GO_PURIFIED_FOOD
FACTION_BLACKWOOD
EMOTE_LURED
EMOTE_PURIFIED
EMOTE_GENERIC_FLEE
SPELL_BATTLE_STANCE
SPELL_THUNDERCLAP
SPELL_HEALING_WARD
EVENT_BECOME_PURIFIED
EVENT_FURBOLG_RESET
EVENT_START_PURIFICATION
ACTION_FLEE
ACTION_THUNDERCLAP
ACTION_HEALING_WARD
ACTION_MAX
BOWL_DISTANCE
Definition at line 776 of file darkshore.cpp.
Function Documentation
AddSC_darkshore()
void AddSC_darkshore ()
Definition at line 1003 of file darkshore.cpp.
References EffectDummyCreature_awaken_kerlonian(), Script::GetAI, GetAI_npc_kerlonian(), GetAI_npc_prospector_remtravel(), GetAI_npc_rabid_bear(), GetAI_npc_therylune(), GetAI_npc_threshwackonator(), GetAI_npc_volcor(), GossipHello_npc_threshwackonator(), GossipSelect_npc_threshwackonator(), GOUse_go_furbolg_food(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_event_purify_food(), QuestAccept_npc_kerlonian(), QuestAccept_npc_prospector_remtravel(), QuestAccept_npc_therylune(), QuestAccept_npc_volcor(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_awaken_kerlonian()
bool EffectDummyCreature_awaken_kerlonian (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 211 of file darkshore.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, UnitAI::SendAIEvent(), and SPELL_AWAKEN.
Referenced by AddSC_darkshore().
GetAI_npc_kerlonian()
UnitAI* GetAI_npc_kerlonian (Creature * pCreature)
Definition at line 189 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GetAI_npc_prospector_remtravel()
UnitAI* GetAI_npc_prospector_remtravel (Creature * pCreature)
Definition at line 330 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GetAI_npc_rabid_bear()
UnitAI* GetAI_npc_rabid_bear (Creature * pCreature)
Definition at line 767 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GetAI_npc_therylune()
UnitAI* GetAI_npc_therylune (Creature * pCreature)
Definition at line 639 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GetAI_npc_threshwackonator()
UnitAI* GetAI_npc_threshwackonator (Creature * pCreature)
Definition at line 397 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GetAI_npc_volcor()
UnitAI* GetAI_npc_volcor (Creature * pCreature)
Definition at line 579 of file darkshore.cpp.
Referenced by AddSC_darkshore().
GossipHello_npc_threshwackonator()
bool GossipHello_npc_threshwackonator (Player * pPlayer, Creature * pCreature)
Definition at line 402 of file darkshore.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TURN_KEY, GOSSIP_SENDER_MAIN, QUEST_GYROMAST_REV, QUEST_STATUS_INCOMPLETE, TEXT_ID_KEY_READY, and TEXT_ID_THRESH_DEFAULT.
Referenced by AddSC_darkshore().
GossipSelect_npc_threshwackonator()
bool GossipSelect_npc_threshwackonator (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 415 of file darkshore.cpp.
References Creature::AI(), DoScriptText(), EMOTE_START, and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_darkshore().
GOUse_go_furbolg_food()
bool GOUse_go_furbolg_food (Player * player, GameObject * go)
Definition at line 983 of file darkshore.cpp.
References GetClosestCreatureWithEntry(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetRandomPoint(), NPC_BLACKWOOD_WARRIOR, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN.
Referenced by AddSC_darkshore().
ProcessEventId_event_purify_food()
bool ProcessEventId_event_purify_food (uint32 , Object * source, Object * target, bool)
Definition at line 942 of file darkshore.cpp.
References BOWL_DISTANCE, furbolgList, GetCreatureListWithEntryInGrid(), WorldObject::GetFirstCollisionPosition(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetRandomPoint(), Object::GetTypeId(), NPC_BLACKWOOD_WARRIOR, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TYPEID_GAMEOBJECT, and TYPEID_PLAYER.
Referenced by AddSC_darkshore().
QuestAccept_npc_kerlonian()
bool QuestAccept_npc_kerlonian (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 194 of file darkshore.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_PASSIVE, Quest::GetQuestId(), QUEST_SLEEPER_AWAKENED, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_KER_START, Unit::SetStandState(), SPELL_BEAR_FORM, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_darkshore().
QuestAccept_npc_prospector_remtravel()
bool QuestAccept_npc_prospector_remtravel (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 335 of file darkshore.cpp.
References Creature::AI(), FACTION_ESCORT_A_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_ABSENT_MINDED_PT2, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_darkshore().
QuestAccept_npc_therylune()
bool QuestAccept_npc_therylune (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 644 of file darkshore.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_A_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_ID_THERYLUNE_ESCAPE, SAY_THERYLUNE_START, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_darkshore().
QuestAccept_npc_volcor()
bool QuestAccept_npc_volcor (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 584 of file darkshore.cpp.
References Creature::AI(), Quest::GetQuestId(), QUEST_ESCAPE_THROUGH_FORCE, and QUEST_ESCAPE_THROUGH_STEALTH.
Referenced by AddSC_darkshore().
Variable Documentation
aVolcorSpawnLocs
const SummonLocation aVolcorSpawnLocs[] static
Initial value:
=
{
    {4630.2f, 22.6f, 70.1f, 2.4f},
    {4603.8f, 53.5f, 70.4f, 5.4f},
    {4627.5f, 100.4f, 62.7f, 5.8f},
    {4692.8f, 75.8f, 56.7f, 3.1f},
    {4747.8f, 152.8f, 54.6f, 2.4f},
    {4711.7f, 109.1f, 53.5f, 2.4f},
}
Definition at line 464 of file darkshore.cpp.
Referenced by npc_volcorAI::WaypointReached().
furbolgList
const std::vector<uint32> furbolgList = { NPC_BLACKWOOD_WARRIOR, NPC_BLACKWOOD_TOTEMIC } static
Definition at line 805 of file darkshore.cpp.
Referenced by ProcessEventId_event_purify_food().