CMaNGOS_WoTLK: dark_portalScripts.cpp File Reference
dark_portalScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "dark_portal.h"
Data Structures
struct npc_medivh_black_morassAI
struct RiftWaveData
struct npc_time_riftAI
Enumerations
enum { SAY_DEATH = -1269025 , SPELL_CORRUPT = 31326 }
enum {
SPELL_RIFT_PERIODIC = 31320 , SAY_CHRONO_LORD_ENTER = -1269006 , SAY_TEMPORUS_ENTER = -1269000 , SAY_AEONUS_ENTER = -1269012 ,
SPELL_INFINITE_WHELP = 37606 , SPELL_INFINITE_ASSASSIN = 31318 , SPELL_INFINITE_ASSASSIN_2 = 36229 , SPELL_INFINITE_CHRONOMANCER = 31421 ,
SPELL_INFINITE_CHRONOMANCER_2 = 36231 , SPELL_INFINITE_EXECUTIONER = 33363 , SPELL_INFINITE_EXECUTIONER_2 = 36232 , SPELL_INFINITE_VANQUISHER = 33364 ,
SPELL_INFINITE_VANQUISHER_2 = 36233 , SPELL_RIFT_LORD = 31321 , SPELL_RIFT_LORD_2 = 36234 , SPELL_RIFT_KEEPER = 36235 ,
SPELL_RIFT_KEEPER_2 = 36236 , SPELL_CHRONO_LORD_DEJA = 31391 , SPELL_INFINITE_CHRONO_LORD = 37177 , SPELL_TEMPORUS = 31392 ,
SPELL_INFINITE_TIMEREAVER = 37178 , SPELL_RIFT_END_BOSS = 31393 , SPELL_QUIET_SUICIDE_UNUSED = 3617
}
Functions
UnitAI * GetAI_npc_medivh_black_morass (Creature *pCreature)
bool EffectDummyCreature_npc_medivh_black_morass (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_time_rift (Creature *pCreature)
bool EffectDummyCreature_npc_time_rift_channel (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_dark_portal ()
Variables
static const RiftWaveData aPortalWaves []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DEATH
SPELL_CORRUPT
Definition at line 36 of file dark_portalScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RIFT_PERIODIC
SAY_CHRONO_LORD_ENTER
SAY_TEMPORUS_ENTER
SAY_AEONUS_ENTER
SPELL_INFINITE_WHELP
SPELL_INFINITE_ASSASSIN
SPELL_INFINITE_ASSASSIN_2
SPELL_INFINITE_CHRONOMANCER
SPELL_INFINITE_CHRONOMANCER_2
SPELL_INFINITE_EXECUTIONER
SPELL_INFINITE_EXECUTIONER_2
SPELL_INFINITE_VANQUISHER
SPELL_INFINITE_VANQUISHER_2
SPELL_RIFT_LORD
SPELL_RIFT_LORD_2
SPELL_RIFT_KEEPER
SPELL_RIFT_KEEPER_2
SPELL_CHRONO_LORD_DEJA
SPELL_INFINITE_CHRONO_LORD
SPELL_TEMPORUS
SPELL_INFINITE_TIMEREAVER
SPELL_RIFT_END_BOSS
SPELL_QUIET_SUICIDE_UNUSED
Definition at line 94 of file dark_portalScripts.cpp.
Function Documentation
AddSC_dark_portal()
void AddSC_dark_portal ()
Definition at line 395 of file dark_portalScripts.cpp.
References EffectDummyCreature_npc_medivh_black_morass(), EffectDummyCreature_npc_time_rift_channel(), Script::GetAI, GetAI_npc_medivh_black_morass(), GetAI_npc_time_rift(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_medivh_black_morass()
bool EffectDummyCreature_npc_medivh_black_morass (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 75 of file dark_portalScripts.cpp.
References EFFECT_INDEX_0, WorldObject::GetInstanceData(), SPECIAL, SPELL_CORRUPT, SPELL_CORRUPT_AEONUS, and TYPE_SHIELD.
Referenced by AddSC_dark_portal().
EffectDummyCreature_npc_time_rift_channel()
bool EffectDummyCreature_npc_time_rift_channel (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 380 of file dark_portalScripts.cpp.
References Creature::AI(), EFFECT_INDEX_0, and SPELL_RIFT_PERIODIC.
Referenced by AddSC_dark_portal().
GetAI_npc_medivh_black_morass()
UnitAI* GetAI_npc_medivh_black_morass (Creature * pCreature)
Definition at line 70 of file dark_portalScripts.cpp.
Referenced by AddSC_dark_portal().
GetAI_npc_time_rift()
UnitAI* GetAI_npc_time_rift (Creature * pCreature)
Definition at line 375 of file dark_portalScripts.cpp.
Referenced by AddSC_dark_portal().
Variable Documentation
aPortalWaves
const RiftWaveData aPortalWaves[] static
Initial value:
=
{
    {{NPC_ASSASSIN,    NPC_WHELP,        NPC_CHRONOMANCER, 0}},
    {{NPC_EXECUTIONER, NPC_CHRONOMANCER, NPC_WHELP,        NPC_ASSASSIN}},
    {{NPC_EXECUTIONER, NPC_VANQUISHER,   NPC_CHRONOMANCER, NPC_ASSASSIN}}
}
Definition at line 130 of file dark_portalScripts.cpp.
Referenced by npc_time_riftAI::DoSummon().