CMaNGOS_WoTLK: DBCStores.h File Reference
DBCStores.h File Reference
#include "Common.h"
#include "Database/DBCStore.h"
#include "Server/DBCStructure.h"
#include <list>
#include <vector>
Typedefs
typedef std::list< uint32 > SimpleFactionsList
typedef std::map< uint32, MapDifficultyEntry const * > MapDifficultyMap
Enumerations
enum ContentLevels { CONTENT_1_60 = 0 , CONTENT_61_70 , CONTENT_71_80 }
Functions
bool IsAcceptableClientBuild (uint32 build)
std::string AcceptableClientBuildsListStr ()
SimpleFactionsList const * GetFactionTeamList (uint32 faction)
char const * GetPetName (uint32 petfamily, uint32 dbclang)
uint32 GetTalentSpellCost (uint32 spellId)
uint32 GetTalentSpellCost (TalentSpellPos const *pos)
TalentSpellPos const * GetTalentSpellPos (uint32 spellId)
int32 GetAreaFlagByAreaID (uint32 area_id)
uint32 GetAreaFlagByMapId (uint32 mapid)
std::vector< WMOAreaTableEntry const * > & GetWMOAreaTableEntriesByTripple (int32 rootid, int32 adtid, int32 groupid)
AreaTableEntry const * GetAreaEntryByAreaID (uint32 area_id)
AreaTableEntry const * GetAreaEntryByAreaFlagAndMap (uint32 area_flag, uint32 map_id)
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
ChatChannelsEntry const * GetChatChannelsEntryFor (const std::string &name, uint32 channel_id=0)
bool IsTotemCategoryCompatiableWith (uint32 itemTotemCategoryId, uint32 requiredTotemCategoryId)
CharacterFacialHairStylesEntry const * GetCharFacialHairEntry (uint8 race, uint8 gender, uint8 facialHairId)
CharSectionsEntry const * GetCharSectionEntry (uint8 race, CharSectionType genType, uint8 gender, uint8 type, uint8 color)
bool MapCoordinateVsZoneCheck (float x, float y, uint32 mapid, uint32 zone)
bool Zone2MapCoordinates (float &x, float &y, uint32 zone)
bool Map2ZoneCoordinates (float &x, float &y, uint32 zone)
MapDifficultyEntry const * GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
Difficulty GetPrevDifficulty (Difficulty diff, bool isRaid)
uint32 const * GetTalentTabPages (uint32 cls)
bool IsPointInAreaTriggerZone (AreaTriggerEntry const *atEntry, uint32 mapid, float x, float y, float z, float delta=0.0f)
PvPDifficultyEntry const * GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
PvPDifficultyEntry const * GetBattlegroundBracketById (uint32 mapid, BattleGroundBracketId id)
uint32 GetCreatureModelRace (uint32 modelId)
float GetModelMidpoint (uint32 modelId)
uint32 GetDefaultMapLight (uint32 mapId)
void LoadDBCStores (const std::string &dataPath)
DBCStorage< SoundEntriesEntry > const * GetSoundEntriesStore ()
DBCStorage< SpellRangeEntry > const * GetSpellRangeStore ()
DBCStorage< FactionEntry > const * GetFactionStore ()
DBCStorage< ItemEntry > const * GetItemDisplayStore ()
DBCStorage< CreatureDisplayInfoEntry > const * GetCreatureDisplayStore ()
DBCStorage< EmotesEntry > const * GetEmotesStore ()
DBCStorage< EmotesTextEntry > const * GetEmotesTextStore ()
LFGDungeonEntry const * GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Variables
DBCStorage< AchievementEntry > sAchievementStore
DBCStorage< AchievementCriteriaEntry > sAchievementCriteriaStore
DBCStorage< AreaTableEntry > sAreaStore
DBCStorage< AreaTriggerEntry > sAreaTriggerStore
DBCStorage< AuctionHouseEntry > sAuctionHouseStore
DBCStorage< BankBagSlotPricesEntry > sBankBagSlotPricesStore
DBCStorage< BarberShopStyleEntry > sBarberShopStyleStore
DBCStorage< BattlemasterListEntry > sBattlemasterListStore
DBCStorage< CharStartOutfitEntry > sCharStartOutfitStore
DBCStorage< CharTitlesEntry > sCharTitlesStore
DBCStorage< ChatChannelsEntry > sChatChannelsStore
DBCStorage< CharacterFacialHairStylesEntry > sCharacterFacialHairStylesStore
DBCStorage< CharSectionsEntry > sCharSectionsStore
DBCStorage< ChrClassesEntry > sChrClassesStore
DBCStorage< ChrRacesEntry > sChrRacesStore
DBCStorage< CinematicCameraEntry > sCinematicCameraStore
DBCStorage< CinematicSequencesEntry > sCinematicSequencesStore
DBCStorage< CreatureDisplayInfoEntry > sCreatureDisplayInfoStore
DBCStorage< CreatureDisplayInfoExtraEntry > sCreatureDisplayInfoExtraStore
DBCStorage< CreatureModelDataEntry > sCreatureModelDataStore
DBCStorage< CreatureFamilyEntry > sCreatureFamilyStore
DBCStorage< CreatureSpellDataEntry > sCreatureSpellDataStore
DBCStorage< CreatureTypeEntry > sCreatureTypeStore
DBCStorage< CurrencyTypesEntry > sCurrencyTypesStore
DBCStorage< DestructibleModelDataEntry > sDestructibleModelDataStore
DBCStorage< DurabilityCostsEntry > sDurabilityCostsStore
DBCStorage< DurabilityQualityEntry > sDurabilityQualityStore
DBCStorage< EmotesEntry > sEmotesStore
DBCStorage< EmotesTextEntry > sEmotesTextStore
DBCStorage< FactionEntry > sFactionStore
DBCStorage< FactionTemplateEntry > sFactionTemplateStore
DBCStorage< GameObjectArtKitEntry > sGameObjectArtKitStore
DBCStorage< GameObjectDisplayInfoEntry > sGameObjectDisplayInfoStore
DBCStorage< GemPropertiesEntry > sGemPropertiesStore
DBCStorage< GlyphPropertiesEntry > sGlyphPropertiesStore
DBCStorage< GlyphSlotEntry > sGlyphSlotStore
DBCStorage< GMSurveyAnswersEntry > sGMSurveyAnswersStore
DBCStorage< GMSurveyCurrentSurveyEntry > sGMSurveyCurrentSurveyStore
DBCStorage< GMSurveyQuestionsEntry > sGMSurveyQuestionsStore
DBCStorage< GMSurveyEntry > sGMSurveySurveysStore
DBCStorage< GMTicketCategoryEntry > sGMTicketCategoryStore
DBCStorage< GtBarberShopCostBaseEntry > sGtBarberShopCostBaseStore
DBCStorage< GtCombatRatingsEntry > sGtCombatRatingsStore
DBCStorage< GtChanceToMeleeCritBaseEntry > sGtChanceToMeleeCritBaseStore
DBCStorage< GtChanceToMeleeCritEntry > sGtChanceToMeleeCritStore
DBCStorage< GtChanceToSpellCritBaseEntry > sGtChanceToSpellCritBaseStore
DBCStorage< GtChanceToSpellCritEntry > sGtChanceToSpellCritStore
DBCStorage< GtOCTClassCombatRatingScalarEntry > sGtOCTClassCombatRatingScalarStore
DBCStorage< GtOCTRegenHPEntry > sGtOCTRegenHPStore
DBCStorage< GtNPCManaCostScalerEntry > sGtNPCManaCostScalerStore
DBCStorage< GtRegenHPPerSptEntry > sGtRegenHPPerSptStore
DBCStorage< GtRegenMPPerSptEntry > sGtRegenMPPerSptStore
DBCStorage< HolidaysEntry > sHolidaysStore
DBCStorage< ItemEntry > sItemStore
DBCStorage< ItemBagFamilyEntry > sItemBagFamilyStore
DBCStorage< ItemClassEntry > sItemClassStore
DBCStorage< ItemExtendedCostEntry > sItemExtendedCostStore
DBCStorage< ItemLimitCategoryEntry > sItemLimitCategoryStore
DBCStorage< ItemRandomPropertiesEntry > sItemRandomPropertiesStore
DBCStorage< ItemRandomSuffixEntry > sItemRandomSuffixStore
DBCStorage< ItemSetEntry > sItemSetStore
DBCStorage< LFGDungeonEntry > sLFGDungeonStore
DBCStorage< LfgDungeonExpansionEntry > sLFGDungeonExpansionStore
DBCStorage< LiquidTypeEntry > sLiquidTypeStore
DBCStorage< LockEntry > sLockStore
DBCStorage< MailTemplateEntry > sMailTemplateStore
DBCStorage< MapEntry > sMapStore
DBCStorage< MapDifficultyEntry > sMapDifficultyStore
MapDifficultyMap sMapDifficultyMap
DBCStorage< MovieEntry > sMovieStore
DBCStorage< OverrideSpellDataEntry > sOverrideSpellDataStore
DBCStorage< QuestFactionRewardEntry > sQuestFactionRewardStore
DBCStorage< QuestSortEntry > sQuestSortStore
DBCStorage< QuestXPLevel > sQuestXPLevelStore
DBCStorage< PowerDisplayEntry > sPowerDisplayStore
DBCStorage< RandomPropertiesPointsEntry > sRandomPropertiesPointsStore
DBCStorage< ScalingStatDistributionEntry > sScalingStatDistributionStore
DBCStorage< ScalingStatValuesEntry > sScalingStatValuesStore
DBCStorage< SkillLineEntry > sSkillLineStore
DBCStorage< SkillLineAbilityEntry > sSkillLineAbilityStore
DBCStorage< SkillRaceClassInfoEntry > sSkillRaceClassInfoStore
DBCStorage< SkillTiersEntry > sSkillTiersStore
DBCStorage< SoundEntriesEntry > sSoundEntriesStore
DBCStorage< SpellCastTimesEntry > sSpellCastTimesStore
DBCStorage< SpellCategoryEntry > sSpellCategoryStore
DBCStorage< SpellDifficultyEntry > sSpellDifficultyStore
DBCStorage< SpellDurationEntry > sSpellDurationStore
DBCStorage< SpellFocusObjectEntry > sSpellFocusObjectStore
DBCStorage< SpellItemEnchantmentEntry > sSpellItemEnchantmentStore
DBCStorage< SpellItemEnchantmentConditionEntry > sSpellItemEnchantmentConditionStore
ItemSpellCategoryStore sItemSpellCategoryStore
PetFamilySpellsStore sPetFamilySpellsStore
DBCStorage< SpellRadiusEntry > sSpellRadiusStore
DBCStorage< SpellRangeEntry > sSpellRangeStore
DBCStorage< SpellRuneCostEntry > sSpellRuneCostStore
DBCStorage< SpellShapeshiftFormEntry > sSpellShapeshiftFormStore
DBCStorage< SpellVisualEntry > sSpellVisualStore
DBCStorage< StableSlotPricesEntry > sStableSlotPricesStore
DBCStorage< SummonPropertiesEntry > sSummonPropertiesStore
DBCStorage< TalentEntry > sTalentStore
DBCStorage< TalentTabEntry > sTalentTabStore
DBCStorage< TaxiNodesEntry > sTaxiNodesStore
DBCStorage< TaxiPathEntry > sTaxiPathStore
TaxiMask sTaxiNodesMask
TaxiMask sOldContinentsNodesMask
TaxiPathSetBySource sTaxiPathSetBySource
TaxiPathNodesByPath sTaxiPathNodesByPath
DBCStorage< TeamContributionPoints > sTeamContributionPoints
DBCStorage< TotemCategoryEntry > sTotemCategoryStore
DBCStorage< TransportAnimationEntry > sTransportAnimationStore
DBCStorage< TransportRotationEntry > sTransportRotationStore
DBCStorage< VehicleEntry > sVehicleStore
DBCStorage< VehicleSeatEntry > sVehicleSeatStore
DBCStorage< WMOAreaTableEntry > sWMOAreaTableStore
DBCStorage< WorldMapOverlayEntry > sWorldMapOverlayStore
Typedef Documentation
MapDifficultyMap
typedef std::map<uint32, MapDifficultyEntry const*> MapDifficultyMap
Definition at line 69 of file DBCStores.h.
SimpleFactionsList
typedef std::list<uint32> SimpleFactionsList
Definition at line 32 of file DBCStores.h.
Enumeration Type Documentation
ContentLevels
enum ContentLevels
Enumerator
CONTENT_1_60
CONTENT_61_70
CONTENT_71_80
Definition at line 50 of file DBCStores.h.
Function Documentation
AcceptableClientBuildsListStr()
std::string AcceptableClientBuildsListStr ()
Definition at line 228 of file DBCStores.cpp.
References EXPECTED_MANGOSD_CLIENT_BUILD.
Referenced by LoadDBCStores(), and Master::Run().
GetAreaEntryByAreaFlagAndMap()
AreaTableEntry const* GetAreaEntryByAreaFlagAndMap (uint32 area_flag, uint32 map_id)
Definition at line 865 of file DBCStores.cpp.
References GetAreaEntryByAreaID(), sAreaStore, and sMapStore.
Referenced by Player::CheckAreaExploreAndOutdoor(), TerrainManager::GetAreaIdByAreaFlag(), TerrainInfo::GetAreaName(), TerrainInfo::getLiquidStatus(), TerrainManager::GetZoneAndAreaIdByAreaFlag(), and TerrainManager::GetZoneIdByAreaFlag().
GetAreaEntryByAreaID()
AreaTableEntry const* GetAreaEntryByAreaID (uint32 area_id)
Definition at line 856 of file DBCStores.cpp.
References GetAreaFlagByAreaID(), and sAreaStore.
Referenced by Player::CanStartFlyInArea(), NamreebAnticheat::Movement::CheckTeleport(), Spell::EffectDuel(), ConditionEntry::Evaluate(), GetAreaEntryByAreaFlagAndMap(), TerrainInfo::GetAreaFlag(), TerrainInfo::GetAreaName(), GridMap::getLiquidStatus(), TerrainInfo::getLiquidStatus(), GossipHello_npc_innkeeper(), Aura::HandleAuraDummy(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleListAreaTriggerCommand(), WorldSession::HandleTogglePvP(), WorldSession::HandleWhoOpcode(), Unit::IsAllowedDamageInArea(), TerrainInfo::IsOutdoors(), ConditionEntry::IsValid(), AchievementCriteriaRequirement::IsValid(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadFishingBaseSkillLevel(), World::LoadGraveyardZones(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellAreas(), Player::RepopAtGraveyard(), Player::UpdateArea(), Creature::UpdateEntry(), Player::UpdateLocalChannels(), and Player::UpdateZone().
GetAreaFlagByAreaID()
int32 GetAreaFlagByAreaID (uint32 area_id)
Definition at line 823 of file DBCStores.cpp.
References sAreaFlagByAreaID.
Referenced by GetAreaEntryByAreaID(), ChatHandler::HandleHideAreaCommand(), ChatHandler::HandleShowAreaCommand(), and AchievementMgr::UpdateAchievementCriteria().
GetAreaFlagByMapId()
uint32 GetAreaFlagByMapId (uint32 mapid)
Definition at line 876 of file DBCStores.cpp.
References sAreaFlagByMapID.
Referenced by TerrainInfo::GetAreaFlag().
GetBattlegroundBracketById()
PvPDifficultyEntry const* GetBattlegroundBracketById (uint32 mapid, BattleGroundBracketId id)
Definition at line 1071 of file DBCStores.cpp.
References sPvPDifficultyStore.
Referenced by BattleGroundQueue::Update().
GetBattlegroundBracketByLevel()
PvPDifficultyEntry const* GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
Definition at line 1047 of file DBCStores.cpp.
References PvPDifficultyEntry::maxLevel, and sPvPDifficultyStore.
Referenced by BattleGroundMgr::BuildBattleGroundListPacket(), Group::CanJoinBattleGroundQueue(), MapManager::CreateBattleGroundMap(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
GetCharFacialHairEntry()
CharacterFacialHairStylesEntry const* GetCharFacialHairEntry (uint8 race, uint8 gender, uint8 facialHairId)
Definition at line 913 of file DBCStores.cpp.
References sCharFacialHairMap.
Referenced by Player::ValidateAppearance().
GetCharSectionEntry()
CharSectionsEntry const* GetCharSectionEntry (uint8 race, CharSectionType genType, uint8 gender, uint8 type, uint8 color)
Definition at line 922 of file DBCStores.cpp.
References sCharSectionMap, and SECTION_FLAG_PLAYABLE.
Referenced by Player::ValidateAppearance().
GetChatChannelsEntryFor()
ChatChannelsEntry const* GetChatChannelsEntryFor (const std::string & name, uint32 channel_id = 0)
Definition at line 935 of file DBCStores.cpp.
References MAX_LOCALE, sChatChannelsStore, and Utf8toWStr().
Referenced by Channel::Channel().
GetContentLevelsForMapAndZone()
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 895 of file DBCStores.cpp.
References CONTENT_1_60, CONTENT_61_70, CONTENT_71_80, MapEntry::Expansion(), GetVirtualMapForMapAndZone(), and sMapStore.
Referenced by MaNGOS::XP::Gain().
GetCreatureDisplayStore()
DBCStorage<CreatureDisplayInfoEntry> const* GetCreatureDisplayStore ()
Definition at line 1171 of file DBCStores.cpp.
References sCreatureDisplayInfoStore.
GetCreatureModelRace()
uint32 GetCreatureModelRace (uint32 modelId)
Definition at line 1131 of file DBCStores.cpp.
References sCreatureDisplayInfoExtraStore, and sCreatureDisplayInfoStore.
Referenced by Creature::getRace().
GetDefaultMapLight()
uint32 GetDefaultMapLight (uint32 mapId)
Definition at line 1152 of file DBCStores.cpp.
References LightEntry::id, LightEntry::mapId, sLightStore, LightEntry::x, LightEntry::y, and LightEntry::z.
Referenced by Player::SendOverrideLightUpdate().
GetEmotesStore()
DBCStorage<EmotesEntry> const* GetEmotesStore ()
Definition at line 1172 of file DBCStores.cpp.
References sEmotesStore.
GetEmotesTextStore()
DBCStorage<EmotesTextEntry> const* GetEmotesTextStore ()
Definition at line 1173 of file DBCStores.cpp.
References sEmotesTextStore.
GetFactionStore()
DBCStorage<FactionEntry> const* GetFactionStore ()
Definition at line 1169 of file DBCStores.cpp.
References sFactionStore.
GetFactionTeamList()
SimpleFactionsList const* GetFactionTeamList (uint32 faction)
Definition at line 783 of file DBCStores.cpp.
References sFactionTeamMap.
Referenced by ReputationMgr::SetReputation().
GetItemDisplayStore()
DBCStorage<ItemEntry> const* GetItemDisplayStore ()
Definition at line 1170 of file DBCStores.cpp.
References sItemStore.
GetLFGDungeon()
LFGDungeonEntry const* GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Definition at line 1175 of file DBCStores.cpp.
References LFGDungeonEntry::Difficulty, LFGDungeonEntry::MapID, and sLFGDungeonStore.
GetMapDifficultyData()
MapDifficultyEntry const* GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
Definition at line 1041 of file DBCStores.cpp.
References MAKE_PAIR32, and sMapDifficultyMap.
Referenced by Player::_LoadBoundInstances(), MapPersistentStateManager::_ResetOrWarnAll(), MapManager::CreateDungeonMap(), Player::GetAreaTriggerLockStatus(), Group::GetBoundInstance(), Player::GetBoundInstance(), Map::GetMapDifficulty(), Map::GetMaxPlayers(), MapPersistentStateManager::GetSubsequentResetTime(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadGameObjects(), DungeonResetScheduler::LoadResetTimes(), Player::SendInitialPacketsBeforeAddToMap(), and DungeonResetScheduler::Update().
GetModelMidpoint()
float GetModelMidpoint (uint32 modelId)
Definition at line 1142 of file DBCStores.cpp.
References sCreatureDisplayInfoStore, and sCreatureModelDataStore.
Referenced by Spell::EffectTransmitted().
GetPetName()
char const* GetPetName (uint32 petfamily, uint32 dbclang)
Definition at line 791 of file DBCStores.cpp.
References CreatureFamilyEntry::Name, and sCreatureFamilyStore.
Referenced by ObjectMgr::GeneratePetName().
GetPrevDifficulty()
Difficulty GetPrevDifficulty (Difficulty diff, bool isRaid) inline
Definition at line 78 of file DBCStores.h.
References DUNGEON_DIFFICULTY_HEROIC, RAID_DIFFICULTY_10MAN_HEROIC, RAID_DIFFICULTY_10MAN_NORMAL, RAID_DIFFICULTY_25MAN_HEROIC, RAID_DIFFICULTY_25MAN_NORMAL, and REGULAR_DIFFICULTY.
Referenced by GetSpellEntryByDifficulty(), and Creature::InitEntry().
GetSoundEntriesStore()
DBCStorage<SoundEntriesEntry> const* GetSoundEntriesStore ()
Definition at line 1167 of file DBCStores.cpp.
References sSoundEntriesStore.
Referenced by ScriptedAI::DoPlaySoundToSet().
GetSpellRangeStore()
DBCStorage<SpellRangeEntry> const* GetSpellRangeStore ()
Definition at line 1168 of file DBCStores.cpp.
References sSpellRangeStore.
Referenced by ScriptedAI::CanCast(), PlayerbotAI::In_Range(), and ScriptedAI::SelectSpell().
GetTalentSpellCost() [1/2]
uint32 GetTalentSpellCost (TalentSpellPos const * pos)
Definition at line 810 of file DBCStores.cpp.
References TalentSpellPos::rank.
Referenced by Player::_SaveSpells(), Pet::addSpell(), Player::addSpell(), GetErrorAtShapeshiftedCast(), GetTalentSpellCost(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleListAurasCommand(), ChatHandler::HandleListTalentsCommand(), ChatHandler::HandleUnLearnCommand(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellLearnSpells(), ObjectMgr::LoadTrainers(), Player::removeSpell(), Pet::removeSpell(), Pet::resetTalentsForAllPetsOf(), and ChatHandler::ShowSpellListHelper().
GetTalentSpellCost() [2/2]
uint32 GetTalentSpellCost (uint32 spellId)
Definition at line 818 of file DBCStores.cpp.
References GetTalentSpellCost(), and GetTalentSpellPos().
GetTalentSpellPos()
TalentSpellPos const* GetTalentSpellPos (uint32 spellId)
Definition at line 801 of file DBCStores.cpp.
References sTalentSpellPosMap.
Referenced by Player::_LoadSpells(), Pet::addSpell(), Player::addSpell(), GetTalentSpellCost(), SpellMgr::LoadSpellChains(), Player::removeSpell(), and CharacterDatabaseCleaner::SpellCheck().
GetTalentTabPages()
uint32 const* GetTalentTabPages (uint32 cls)
Definition at line 1081 of file DBCStores.cpp.
References sTalentTabPages.
Referenced by Player::BuildPlayerTalentsInfoData().
GetVirtualMapForMapAndZone()
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 884 of file DBCStores.cpp.
References sWorldMapAreaStore.
Referenced by Player::CanStartFlyInArea(), GetContentLevelsForMapAndZone(), and SpellMgr::GetSpellAllowedInLocationError().
GetWMOAreaTableEntriesByTripple()
std::vector<WMOAreaTableEntry const*>& GetWMOAreaTableEntriesByTripple (int32 rootid, int32 adtid, int32 groupid)
Definition at line 851 of file DBCStores.cpp.
References sWMOAreaInfoByTripple.
Referenced by TerrainInfo::GetAreaFlag(), TerrainInfo::GetAreaName(), and TerrainInfo::IsOutdoors().
IsAcceptableClientBuild()
bool IsAcceptableClientBuild (uint32 build)
Definition at line 218 of file DBCStores.cpp.
References EXPECTED_MANGOSD_CLIENT_BUILD.
Referenced by GridMap::ExistMap(), WorldSocket::HandleAuthSession(), GridMap::loadData(), and LoadDBCStores().
IsPointInAreaTriggerZone()
bool IsPointInAreaTriggerZone (AreaTriggerEntry const * atEntry, uint32 mapid, float x, float y, float z, float delta = 0.0f)
Definition at line 1086 of file DBCStores.cpp.
References AreaTriggerEntry::box_orientation, AreaTriggerEntry::box_x, AreaTriggerEntry::box_y, AreaTriggerEntry::box_z, M_PI, AreaTriggerEntry::mapid, AreaTriggerEntry::radius, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by Player::CheckAreaExploreAndOutdoor(), WorldSession::HandleAreaTriggerOpcode(), and ChatHandler::HandleTriggerActiveCommand().
IsTotemCategoryCompatiableWith()
bool IsTotemCategoryCompatiableWith (uint32 itemTotemCategoryId, uint32 requiredTotemCategoryId)
Definition at line 985 of file DBCStores.cpp.
References TotemCategoryEntry::categoryMask, TotemCategoryEntry::categoryType, and sTotemCategoryStore.
Referenced by Player::HasItemTotemCategory().
LoadDBCStores()
void LoadDBCStores (const std::string & dataPath)
Definition at line 370 of file DBCStores.cpp.
References AcceptableClientBuildsListStr(), SpellEntry::Attributes, TalentTabEntry::ClassMask, CLASSMASK_ALL_PLAYABLE, SQLStorageBase::GetMaxEntry(), MapEntry::ghost_entrance_map, SpellEntry::Id, IsAcceptableClientBuild(), LoadDBC(), SQLStorage::LookupEntry(), MAKE_PAIR32, MANGOS_ASSERT, TaxiNodesEntry::map_id, MAX_BATTLEGROUND_BRACKETS, MAX_CLASSES, MAX_EFFECT_INDEX, MAX_TALENT_RANK, TaxiNodesEntry::MountCreatureID, RACEMASK_ALL_PLAYABLE, TalentEntry::RankID, ReadDBCBuild(), sAchievementCriteriaStore, sAchievementStore, sAreaFlagByAreaID, sAreaFlagByMapID, sAreaStore, sAreaTriggerStore, sAuctionHouseStore, sBankBagSlotPricesStore, sBarberShopStyleStore, sBattlemasterListStore, sCharacterFacialHairStylesStore, sCharFacialHairMap, sCharSectionMap, sCharSectionsStore, sCharStartOutfitStore, sCharTitlesStore, sChatChannelsStore, sChrClassesStore, sChrRacesStore, sCinematicCameraStore, sCinematicSequencesStore, sCreatureDisplayInfoExtraStore, sCreatureDisplayInfoStore, sCreatureFamilyStore, sCreatureModelDataStore, sCreatureSpellDataStore, sCreatureTypeStore, sCurrencyTypesStore, sDestructibleModelDataStore, sDurabilityCostsStore, sDurabilityQualityStore, sEmotesStore, sEmotesTextStore, sFactionStore, sFactionTeamMap, sFactionTemplateStore, sGameObjectArtKitStore, sGameObjectDisplayInfoStore, sGemPropertiesStore, sGlyphPropertiesStore, sGlyphSlotStore, sGMSurveyAnswersStore, sGMSurveyCurrentSurveyStore, sGMSurveyQuestionsStore, sGMSurveySurveysStore, sGMTicketCategoryStore, sGtBarberShopCostBaseStore, sGtChanceToMeleeCritBaseStore, sGtChanceToMeleeCritStore, sGtChanceToSpellCritBaseStore, sGtChanceToSpellCritStore, sGtCombatRatingsStore, sGtNPCManaCostScalerStore, sGtOCTClassCombatRatingScalarStore, sGtOCTRegenHPStore, sGtRegenHPPerSptStore, sGtRegenMPPerSptStore, sHolidaysStore, sItemBagFamilyStore, sItemClassStore, sItemExtendedCostStore, sItemLimitCategoryStore, sItemRandomPropertiesStore, sItemRandomSuffixStore, sItemSetStore, sItemStore, SkillLineAbilityEntry::skillId, CreatureFamilyEntry::skillLine, sLFGDungeonExpansionStore, sLFGDungeonStore, sLightStore, sLiquidTypeStore, sLockStore, sLog, sMailTemplateStore, sMapDifficultyMap, sMapDifficultyStore, sMapStore, sMovieStore, sOldContinentsNodesMask, sOverrideSpellDataStore, SPELL_ATTR_DO_NOT_DISPLAY, SPELL_ATTR_DO_NOT_LOG, SPELL_ATTR_IS_ABILITY, SPELL_ATTR_PASSIVE, SkillLineAbilityEntry::spellId, sPetFamilySpellsStore, sPowerDisplayStore, sPvPDifficultyStore, sQuestFactionRewardStore, sQuestSortStore, sQuestXPLevelStore, sRandomPropertiesPointsStore, sScalingStatDistributionStore, sScalingStatValuesStore, sSkillLineAbilityStore, sSkillLineStore, sSkillRaceClassInfoStore, sSkillTiersStore, sSoundEntriesStore, sSpellCastTimesStore, sSpellCategoryStore, sSpellDifficultyStore, sSpellDurationStore, sSpellFocusObjectStore, sSpellItemEnchantmentConditionStore, sSpellItemEnchantmentStore, sSpellRadiusStore, sSpellRangeStore, sSpellRuneCostStore, sSpellShapeshiftFormStore, sSpellTemplate, sSpellVisualStore, sStableSlotPricesStore, sSummonPropertiesStore, sTalentSpellPosMap, sTalentStore, sTalentTabPages, sTalentTabStore, sTaxiNodesMask, sTaxiNodesStore, sTaxiPathNodesByPath, sTaxiPathNodeStore, sTaxiPathSetBySource, sTaxiPathStore, sTeamContributionPoints, sTotemCategoryStore, sTransportAnimationStore, sTransportRotationStore, sVehicleSeatStore, sVehicleStore, sWMOAreaInfoByTripple, sWMOAreaTableStore, sWorldMapAreaStore, sWorldMapOverlayStore, TalentTabEntry::tabpage, FactionEntry::team, and Log::WaitBeforeContinueIfNeed().
Referenced by World::SetInitialWorldSettings().
Map2ZoneCoordinates()
bool Map2ZoneCoordinates (float & x, float & y, uint32 zone)
Definition at line 1026 of file DBCStores.cpp.
References sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by ChatHandler::HandleGPSCommand().
MapCoordinateVsZoneCheck()
bool MapCoordinateVsZoneCheck (float x, float y, uint32 mapid, uint32 zone)
Definition at line 1005 of file DBCStores.cpp.
References WorldMapAreaEntry::map_id, sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Zone2MapCoordinates()
bool Zone2MapCoordinates (float & x, float & y, uint32 zone)
Definition at line 1011 of file DBCStores.cpp.
References sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by ChatHandler::HandleGoZoneXYCommand().
Variable Documentation
sAchievementCriteriaStore
DBCStorage<AchievementCriteriaEntry> sAchievementCriteriaStore extern
sAchievementStore
DBCStorage<AchievementEntry> sAchievementStore extern
sAreaStore
DBCStorage<AreaTableEntry> sAreaStore extern
sAreaTriggerStore
DBCStorage<AreaTriggerEntry> sAreaTriggerStore extern
sAuctionHouseStore
DBCStorage<AuctionHouseEntry> sAuctionHouseStore extern
sBankBagSlotPricesStore
DBCStorage<BankBagSlotPricesEntry> sBankBagSlotPricesStore extern
sBarberShopStyleStore
DBCStorage<BarberShopStyleEntry> sBarberShopStyleStore extern
sBattlemasterListStore
DBCStorage<BattlemasterListEntry> sBattlemasterListStore extern
sCharacterFacialHairStylesStore
DBCStorage<CharacterFacialHairStylesEntry> sCharacterFacialHairStylesStore extern
sCharSectionsStore
DBCStorage<CharSectionsEntry> sCharSectionsStore extern
sCharStartOutfitStore
DBCStorage<CharStartOutfitEntry> sCharStartOutfitStore extern
sCharTitlesStore
DBCStorage<CharTitlesEntry> sCharTitlesStore extern
sChatChannelsStore
DBCStorage<ChatChannelsEntry> sChatChannelsStore extern
sChrClassesStore
DBCStorage<ChrClassesEntry> sChrClassesStore extern
sChrRacesStore
DBCStorage<ChrRacesEntry> sChrRacesStore extern
sCinematicCameraStore
DBCStorage<CinematicCameraEntry> sCinematicCameraStore extern
sCinematicSequencesStore
DBCStorage<CinematicSequencesEntry> sCinematicSequencesStore extern
sCreatureDisplayInfoExtraStore
DBCStorage<CreatureDisplayInfoExtraEntry> sCreatureDisplayInfoExtraStore extern
sCreatureDisplayInfoStore
DBCStorage<CreatureDisplayInfoEntry> sCreatureDisplayInfoStore extern
sCreatureFamilyStore
DBCStorage<CreatureFamilyEntry> sCreatureFamilyStore extern
sCreatureModelDataStore
DBCStorage<CreatureModelDataEntry> sCreatureModelDataStore extern
sCreatureSpellDataStore
DBCStorage<CreatureSpellDataEntry> sCreatureSpellDataStore extern
sCreatureTypeStore
DBCStorage<CreatureTypeEntry> sCreatureTypeStore extern
sCurrencyTypesStore
DBCStorage<CurrencyTypesEntry> sCurrencyTypesStore extern
sDestructibleModelDataStore
DBCStorage<DestructibleModelDataEntry> sDestructibleModelDataStore extern
sDurabilityCostsStore
DBCStorage<DurabilityCostsEntry> sDurabilityCostsStore extern
sDurabilityQualityStore
DBCStorage<DurabilityQualityEntry> sDurabilityQualityStore extern
sEmotesStore
DBCStorage<EmotesEntry> sEmotesStore extern
sEmotesTextStore
DBCStorage<EmotesTextEntry> sEmotesTextStore extern
sFactionStore
DBCStorage<FactionEntry> sFactionStore extern
sFactionTemplateStore
DBCStorage<FactionTemplateEntry> sFactionTemplateStore extern
sGameObjectArtKitStore
DBCStorage<GameObjectArtKitEntry> sGameObjectArtKitStore extern
sGameObjectDisplayInfoStore
DBCStorage<GameObjectDisplayInfoEntry> sGameObjectDisplayInfoStore extern
sGemPropertiesStore
DBCStorage<GemPropertiesEntry> sGemPropertiesStore extern
sGlyphPropertiesStore
DBCStorage<GlyphPropertiesEntry> sGlyphPropertiesStore extern
sGlyphSlotStore
DBCStorage<GlyphSlotEntry> sGlyphSlotStore extern
sGMSurveyAnswersStore
DBCStorage<GMSurveyAnswersEntry> sGMSurveyAnswersStore extern
sGMSurveyCurrentSurveyStore
DBCStorage<GMSurveyCurrentSurveyEntry> sGMSurveyCurrentSurveyStore extern
sGMSurveyQuestionsStore
DBCStorage<GMSurveyQuestionsEntry> sGMSurveyQuestionsStore extern
sGMSurveySurveysStore
DBCStorage<GMSurveyEntry> sGMSurveySurveysStore extern
sGMTicketCategoryStore
DBCStorage<GMTicketCategoryEntry> sGMTicketCategoryStore extern
sGtBarberShopCostBaseStore
DBCStorage<GtBarberShopCostBaseEntry> sGtBarberShopCostBaseStore extern
sGtChanceToMeleeCritBaseStore
DBCStorage<GtChanceToMeleeCritBaseEntry> sGtChanceToMeleeCritBaseStore extern
sGtChanceToMeleeCritStore
DBCStorage<GtChanceToMeleeCritEntry> sGtChanceToMeleeCritStore extern
sGtChanceToSpellCritBaseStore
DBCStorage<GtChanceToSpellCritBaseEntry> sGtChanceToSpellCritBaseStore extern
sGtChanceToSpellCritStore
DBCStorage<GtChanceToSpellCritEntry> sGtChanceToSpellCritStore extern
sGtCombatRatingsStore
DBCStorage<GtCombatRatingsEntry> sGtCombatRatingsStore extern
sGtNPCManaCostScalerStore
DBCStorage<GtNPCManaCostScalerEntry> sGtNPCManaCostScalerStore extern
sGtOCTClassCombatRatingScalarStore
DBCStorage<GtOCTClassCombatRatingScalarEntry> sGtOCTClassCombatRatingScalarStore extern
sGtOCTRegenHPStore
DBCStorage<GtOCTRegenHPEntry> sGtOCTRegenHPStore extern
sGtRegenHPPerSptStore
DBCStorage<GtRegenHPPerSptEntry> sGtRegenHPPerSptStore extern
sGtRegenMPPerSptStore
DBCStorage<GtRegenMPPerSptEntry> sGtRegenMPPerSptStore extern
sHolidaysStore
DBCStorage<HolidaysEntry> sHolidaysStore extern
sItemBagFamilyStore
DBCStorage<ItemBagFamilyEntry> sItemBagFamilyStore extern
sItemClassStore
DBCStorage<ItemClassEntry> sItemClassStore extern
sItemExtendedCostStore
DBCStorage<ItemExtendedCostEntry> sItemExtendedCostStore extern
sItemLimitCategoryStore
DBCStorage<ItemLimitCategoryEntry> sItemLimitCategoryStore extern
sItemRandomPropertiesStore
DBCStorage<ItemRandomPropertiesEntry> sItemRandomPropertiesStore extern
sItemRandomSuffixStore
DBCStorage<ItemRandomSuffixEntry> sItemRandomSuffixStore extern
sItemSetStore
DBCStorage<ItemSetEntry> sItemSetStore extern
sItemSpellCategoryStore
ItemSpellCategoryStore sItemSpellCategoryStore extern
Definition at line 172 of file DBCStores.cpp.
Referenced by ObjectMgr::LoadItemPrototypes().
sItemStore
DBCStorage<ItemEntry> sItemStore extern
sLFGDungeonExpansionStore
DBCStorage<LfgDungeonExpansionEntry> sLFGDungeonExpansionStore extern
sLFGDungeonStore
DBCStorage<LFGDungeonEntry> sLFGDungeonStore extern
sLiquidTypeStore
DBCStorage<LiquidTypeEntry> sLiquidTypeStore extern
sLockStore
DBCStorage<LockEntry> sLockStore extern
sMailTemplateStore
DBCStorage<MailTemplateEntry> sMailTemplateStore extern
sMapDifficultyMap
MapDifficultyMap sMapDifficultyMap extern
Definition at line 146 of file DBCStores.cpp.
Referenced by GetMapDifficultyData(), WorldSession::HandleCalendarGetCalendar(), LoadDBCStores(), and DungeonResetScheduler::LoadResetTimes().
sMapDifficultyStore
DBCStorage<MapDifficultyEntry> sMapDifficultyStore extern
sMapStore
DBCStorage<MapEntry> sMapStore extern
sMovieStore
DBCStorage<MovieEntry> sMovieStore extern
sOldContinentsNodesMask
TaxiMask sOldContinentsNodesMask extern
Definition at line 195 of file DBCStores.cpp.
Referenced by PlayerTaxi::InitTaxiNodesForLevel(), and LoadDBCStores().
sOverrideSpellDataStore
DBCStorage<OverrideSpellDataEntry> sOverrideSpellDataStore extern
sPetFamilySpellsStore
PetFamilySpellsStore sPetFamilySpellsStore extern
Definition at line 173 of file DBCStores.cpp.
Referenced by Pet::LearnPetPassives(), and LoadDBCStores().
sPowerDisplayStore
DBCStorage<PowerDisplayEntry> sPowerDisplayStore extern
sQuestFactionRewardStore
DBCStorage<QuestFactionRewardEntry> sQuestFactionRewardStore extern
sQuestSortStore
DBCStorage<QuestSortEntry> sQuestSortStore extern
sQuestXPLevelStore
DBCStorage<QuestXPLevel> sQuestXPLevelStore extern
sRandomPropertiesPointsStore
DBCStorage<RandomPropertiesPointsEntry> sRandomPropertiesPointsStore extern
sScalingStatDistributionStore
DBCStorage<ScalingStatDistributionEntry> sScalingStatDistributionStore extern
sScalingStatValuesStore
DBCStorage<ScalingStatValuesEntry> sScalingStatValuesStore extern
sSkillLineAbilityStore
DBCStorage<SkillLineAbilityEntry> sSkillLineAbilityStore extern
sSkillLineStore
DBCStorage<SkillLineEntry> sSkillLineStore extern
sSkillRaceClassInfoStore
DBCStorage<SkillRaceClassInfoEntry> sSkillRaceClassInfoStore extern
sSkillTiersStore
DBCStorage<SkillTiersEntry> sSkillTiersStore extern
sSoundEntriesStore
DBCStorage<SoundEntriesEntry> sSoundEntriesStore extern
sSpellCastTimesStore
DBCStorage<SpellCastTimesEntry> sSpellCastTimesStore extern
sSpellCategoryStore
DBCStorage<SpellCategoryEntry> sSpellCategoryStore extern
sSpellDifficultyStore
DBCStorage<SpellDifficultyEntry> sSpellDifficultyStore extern
sSpellDurationStore
DBCStorage<SpellDurationEntry> sSpellDurationStore extern
sSpellFocusObjectStore
DBCStorage<SpellFocusObjectEntry> sSpellFocusObjectStore extern
sSpellItemEnchantmentConditionStore
DBCStorage<SpellItemEnchantmentConditionEntry> sSpellItemEnchantmentConditionStore extern
sSpellItemEnchantmentStore
DBCStorage<SpellItemEnchantmentEntry> sSpellItemEnchantmentStore extern
sSpellRadiusStore
DBCStorage<SpellRadiusEntry> sSpellRadiusStore extern
sSpellRangeStore
DBCStorage<SpellRangeEntry> sSpellRangeStore extern
sSpellRuneCostStore
DBCStorage<SpellRuneCostEntry> sSpellRuneCostStore extern
sSpellShapeshiftFormStore
DBCStorage<SpellShapeshiftFormEntry> sSpellShapeshiftFormStore extern
sSpellVisualStore
DBCStorage<SpellVisualEntry> sSpellVisualStore extern
sStableSlotPricesStore
DBCStorage<StableSlotPricesEntry> sStableSlotPricesStore extern
sSummonPropertiesStore
DBCStorage<SummonPropertiesEntry> sSummonPropertiesStore extern
sTalentStore
DBCStorage<TalentEntry> sTalentStore extern
sTalentTabStore
DBCStorage<TalentTabEntry> sTalentTabStore extern
sTaxiNodesMask
TaxiMask sTaxiNodesMask extern
Definition at line 194 of file DBCStores.cpp.
Referenced by PlayerTaxi::AppendTaximaskTo(), ObjectMgr::GetNearestTaxiNode(), LoadDBCStores(), and PlayerTaxi::LoadTaxiMask().
sTaxiNodesStore
DBCStorage<TaxiNodesEntry> sTaxiNodesStore extern
sTaxiPathNodesByPath
TaxiPathNodesByPath sTaxiPathNodesByPath extern
Definition at line 202 of file DBCStores.cpp.
Referenced by Taxi::Tracker::AddRoute(), ScriptMgr::CollectPossibleEventIds(), TransportMgr::GenerateWaypoints(), LoadDBCStores(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadTaxiShortcuts(), Taxi::Tracker::Prepare(), and Taxi::Tracker::Trim().
sTaxiPathSetBySource
TaxiPathSetBySource sTaxiPathSetBySource extern
Definition at line 198 of file DBCStores.cpp.
Referenced by ObjectMgr::GetTaxiPath(), and LoadDBCStores().
sTaxiPathStore
DBCStorage<TaxiPathEntry> sTaxiPathStore extern
sTeamContributionPoints
DBCStorage<TeamContributionPoints> sTeamContributionPoints extern
sTotemCategoryStore
DBCStorage<TotemCategoryEntry> sTotemCategoryStore extern
sTransportAnimationStore
DBCStorage<TransportAnimationEntry> sTransportAnimationStore extern
sTransportRotationStore
DBCStorage<TransportRotationEntry> sTransportRotationStore extern
sVehicleSeatStore
DBCStorage<VehicleSeatEntry> sVehicleSeatStore extern
sVehicleStore
DBCStorage<VehicleEntry> sVehicleStore extern
sWMOAreaTableStore
DBCStorage<WMOAreaTableEntry> sWMOAreaTableStore extern
sWorldMapOverlayStore
DBCStorage<WorldMapOverlayEntry> sWorldMapOverlayStore extern