CMaNGOS_WoTLK: DBCStores.cpp File Reference
DBCStores.cpp File Reference
#include "Server/DBCStores.h"
#include "Policies/Singleton.h"
#include "Log.h"
#include "Util/ProgressBar.h"
#include "Util/Util.h"
#include "Globals/Locales.h"
#include "Globals/SharedDefines.h"
#include "Server/SQLStorages.h"
#include "DBCfmt.h"
#include <map>
Data Structures
struct WMOAreaTableTripple
struct LocalData
Typedefs
typedef std::map< uint16, uint32 > AreaFlagByAreaID
typedef std::map< uint32, uint32 > AreaFlagByMapID
typedef std::map< WMOAreaTableTripple, std::vector< WMOAreaTableEntry const * > > WMOAreaInfoByTripple
typedef std::map< uint32, SimpleFactionsList > FactionTeamMap
typedef std::list< std::string > StoreProblemList
Functions
bool IsAcceptableClientBuild (uint32 build)
std::string AcceptableClientBuildsListStr ()
static bool ReadDBCBuildFileText (const std::string &dbc_path, char const *localeName, std::string &text)
static uint32 ReadDBCBuild (const std::string &dbc_path, LocaleNameStr const *localeNameStr=nullptr)
static bool LoadDBC_assert_print (uint32 fsize, uint32 rsize, const std::string &filename)
template<class T >
void LoadDBC (LocalData &localeData, BarGoLink &bar, StoreProblemList &errlist, DBCStorage< T > &storage, const std::string &dbc_path, const std::string &filename)
void LoadDBCStores (const std::string &dataPath)
SimpleFactionsList const * GetFactionTeamList (uint32 faction)
char const * GetPetName (uint32 petfamily, uint32 dbclang)
TalentSpellPos const * GetTalentSpellPos (uint32 spellId)
uint32 GetTalentSpellCost (TalentSpellPos const *pos)
uint32 GetTalentSpellCost (uint32 spellId)
int32 GetAreaFlagByAreaID (uint32 area_id)
uint32 GetAreaIdByLocalizedName (const std::string &name)
std::vector< WMOAreaTableEntry const * > & GetWMOAreaTableEntriesByTripple (int32 rootid, int32 adtid, int32 groupid)
AreaTableEntry const * GetAreaEntryByAreaID (uint32 area_id)
AreaTableEntry const * GetAreaEntryByAreaFlagAndMap (uint32 area_flag, uint32 map_id)
uint32 GetAreaFlagByMapId (uint32 mapid)
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
CharacterFacialHairStylesEntry const * GetCharFacialHairEntry (uint8 race, uint8 gender, uint8 facialHairId)
CharSectionsEntry const * GetCharSectionEntry (uint8 race, CharSectionType genType, uint8 gender, uint8 type, uint8 color)
ChatChannelsEntry const * GetChatChannelsEntryFor (const std::string &name, uint32 channel_id)
bool IsTotemCategoryCompatiableWith (uint32 itemTotemCategoryId, uint32 requiredTotemCategoryId)
bool MapCoordinateVsZoneCheck (float x, float y, uint32 mapid, uint32 zone)
bool Zone2MapCoordinates (float &x, float &y, uint32 zone)
bool Map2ZoneCoordinates (float &x, float &y, uint32 zone)
MapDifficultyEntry const * GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
PvPDifficultyEntry const * GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
PvPDifficultyEntry const * GetBattlegroundBracketById (uint32 mapid, BattleGroundBracketId id)
uint32 const * GetTalentTabPages (uint32 cls)
bool IsPointInAreaTriggerZone (AreaTriggerEntry const *atEntry, uint32 mapid, float x, float y, float z, float delta)
uint32 GetCreatureModelRace (uint32 modelId)
float GetModelMidpoint (uint32 modelId)
uint32 GetDefaultMapLight (uint32 mapId)
DBCStorage< SoundEntriesEntry > const * GetSoundEntriesStore ()
DBCStorage< SpellRangeEntry > const * GetSpellRangeStore ()
DBCStorage< FactionEntry > const * GetFactionStore ()
DBCStorage< ItemEntry > const * GetItemDisplayStore ()
DBCStorage< CreatureDisplayInfoEntry > const * GetCreatureDisplayStore ()
DBCStorage< EmotesEntry > const * GetEmotesStore ()
DBCStorage< EmotesTextEntry > const * GetEmotesTextStore ()
LFGDungeonEntry const * GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Variables
DBCStorage< AreaTableEntry > sAreaStore (AreaTableEntryfmt)
static AreaFlagByAreaID sAreaFlagByAreaID
static AreaFlagByMapID sAreaFlagByMapID
static WMOAreaInfoByTripple sWMOAreaInfoByTripple
DBCStorage< AchievementEntry > sAchievementStore (Achievementfmt)
DBCStorage< AchievementCriteriaEntry > sAchievementCriteriaStore (AchievementCriteriafmt)
DBCStorage< AreaTriggerEntry > sAreaTriggerStore (AreaTriggerEntryfmt)
DBCStorage< AuctionHouseEntry > sAuctionHouseStore (AuctionHouseEntryfmt)
DBCStorage< BankBagSlotPricesEntry > sBankBagSlotPricesStore (BankBagSlotPricesEntryfmt)
DBCStorage< BattlemasterListEntry > sBattlemasterListStore (BattlemasterListEntryfmt)
DBCStorage< BarberShopStyleEntry > sBarberShopStyleStore (BarberShopStyleEntryfmt)
DBCStorage< CharStartOutfitEntry > sCharStartOutfitStore (CharStartOutfitEntryfmt)
DBCStorage< CharTitlesEntry > sCharTitlesStore (CharTitlesEntryfmt)
DBCStorage< ChatChannelsEntry > sChatChannelsStore (ChatChannelsEntryfmt)
DBCStorage< CharacterFacialHairStylesEntry > sCharacterFacialHairStylesStore (CharacterFacialHairStylesfmt)
std::unordered_map< uint32, CharacterFacialHairStylesEntry const * > sCharFacialHairMap
DBCStorage< CharSectionsEntry > sCharSectionsStore (CharSectionsEntryfmt)
std::multimap< uint32, CharSectionsEntry const * > sCharSectionMap
DBCStorage< ChrClassesEntry > sChrClassesStore (ChrClassesEntryfmt)
DBCStorage< ChrRacesEntry > sChrRacesStore (ChrRacesEntryfmt)
DBCStorage< CinematicCameraEntry > sCinematicCameraStore (CinematicCameraEntryfmt)
DBCStorage< CinematicSequencesEntry > sCinematicSequencesStore (CinematicSequencesEntryfmt)
DBCStorage< CreatureDisplayInfoEntry > sCreatureDisplayInfoStore (CreatureDisplayInfofmt)
DBCStorage< CreatureDisplayInfoExtraEntry > sCreatureDisplayInfoExtraStore (CreatureDisplayInfoExtrafmt)
DBCStorage< CreatureModelDataEntry > sCreatureModelDataStore (CreatureModelDatafmt)
DBCStorage< CreatureFamilyEntry > sCreatureFamilyStore (CreatureFamilyfmt)
DBCStorage< CreatureSpellDataEntry > sCreatureSpellDataStore (CreatureSpellDatafmt)
DBCStorage< CreatureTypeEntry > sCreatureTypeStore (CreatureTypefmt)
DBCStorage< CurrencyTypesEntry > sCurrencyTypesStore (CurrencyTypesfmt)
DBCStorage< DestructibleModelDataEntry > sDestructibleModelDataStore (DestructibleModelDataFmt)
DBCStorage< DurabilityQualityEntry > sDurabilityQualityStore (DurabilityQualityfmt)
DBCStorage< DurabilityCostsEntry > sDurabilityCostsStore (DurabilityCostsfmt)
DBCStorage< EmotesEntry > sEmotesStore (EmotesEntryfmt)
DBCStorage< EmotesTextEntry > sEmotesTextStore (EmotesTextEntryfmt)
static FactionTeamMap sFactionTeamMap
DBCStorage< FactionEntry > sFactionStore (FactionEntryfmt)
DBCStorage< FactionTemplateEntry > sFactionTemplateStore (FactionTemplateEntryfmt)
DBCStorage< GameObjectArtKitEntry > sGameObjectArtKitStore (GameObjectArtKitfmt)
DBCStorage< GameObjectDisplayInfoEntry > sGameObjectDisplayInfoStore (GameObjectDisplayInfofmt)
DBCStorage< GemPropertiesEntry > sGemPropertiesStore (GemPropertiesEntryfmt)
DBCStorage< GlyphPropertiesEntry > sGlyphPropertiesStore (GlyphPropertiesfmt)
DBCStorage< GlyphSlotEntry > sGlyphSlotStore (GlyphSlotfmt)
DBCStorage< GMSurveyAnswersEntry > sGMSurveyAnswersStore (GMSurveyAnswersfmt)
DBCStorage< GMSurveyCurrentSurveyEntry > sGMSurveyCurrentSurveyStore (GMSurveyCurrentSurveyfmt)
DBCStorage< GMSurveyQuestionsEntry > sGMSurveyQuestionsStore (GMSurveyQuestionsfmt)
DBCStorage< GMSurveyEntry > sGMSurveySurveysStore (GMSurveySurveysfmt)
DBCStorage< GMTicketCategoryEntry > sGMTicketCategoryStore (GMTicketCategoryfmt)
DBCStorage< GtBarberShopCostBaseEntry > sGtBarberShopCostBaseStore (GtBarberShopCostBasefmt)
DBCStorage< GtCombatRatingsEntry > sGtCombatRatingsStore (GtCombatRatingsfmt)
DBCStorage< GtChanceToMeleeCritBaseEntry > sGtChanceToMeleeCritBaseStore (GtChanceToMeleeCritBasefmt)
DBCStorage< GtChanceToMeleeCritEntry > sGtChanceToMeleeCritStore (GtChanceToMeleeCritfmt)
DBCStorage< GtChanceToSpellCritBaseEntry > sGtChanceToSpellCritBaseStore (GtChanceToSpellCritBasefmt)
DBCStorage< GtChanceToSpellCritEntry > sGtChanceToSpellCritStore (GtChanceToSpellCritfmt)
DBCStorage< GtOCTClassCombatRatingScalarEntry > sGtOCTClassCombatRatingScalarStore (GtOCTClassCombatRatingScalarfmt)
DBCStorage< GtOCTRegenHPEntry > sGtOCTRegenHPStore (GtOCTRegenHPfmt)
DBCStorage< GtNPCManaCostScalerEntry > sGtNPCManaCostScalerStore (GtNPCManaCostScalerfmt)
DBCStorage< GtRegenHPPerSptEntry > sGtRegenHPPerSptStore (GtRegenHPPerSptfmt)
DBCStorage< GtRegenMPPerSptEntry > sGtRegenMPPerSptStore (GtRegenMPPerSptfmt)
DBCStorage< HolidaysEntry > sHolidaysStore (Holidaysfmt)
DBCStorage< ItemEntry > sItemStore (Itemfmt)
DBCStorage< ItemBagFamilyEntry > sItemBagFamilyStore (ItemBagFamilyfmt)
DBCStorage< ItemClassEntry > sItemClassStore (ItemClassfmt)
DBCStorage< ItemExtendedCostEntry > sItemExtendedCostStore (ItemExtendedCostEntryfmt)
DBCStorage< ItemLimitCategoryEntry > sItemLimitCategoryStore (ItemLimitCategoryEntryfmt)
DBCStorage< ItemRandomPropertiesEntry > sItemRandomPropertiesStore (ItemRandomPropertiesfmt)
DBCStorage< ItemRandomSuffixEntry > sItemRandomSuffixStore (ItemRandomSuffixfmt)
DBCStorage< ItemSetEntry > sItemSetStore (ItemSetEntryfmt)
DBCStorage< LFGDungeonEntry > sLFGDungeonStore (LFGDungeonEntryfmt)
DBCStorage< LfgDungeonExpansionEntry > sLFGDungeonExpansionStore (LFGDungeonExpansionEntryfmt)
DBCStorage< LightEntry > sLightStore (LightEntryfmt)
DBCStorage< LiquidTypeEntry > sLiquidTypeStore (LiquidTypefmt)
DBCStorage< LockEntry > sLockStore (LockEntryfmt)
DBCStorage< MailTemplateEntry > sMailTemplateStore (MailTemplateEntryfmt)
DBCStorage< MapEntry > sMapStore (MapEntryfmt)
DBCStorage< MapDifficultyEntry > sMapDifficultyStore (MapDifficultyEntryfmt)
MapDifficultyMap sMapDifficultyMap
DBCStorage< MovieEntry > sMovieStore (MovieEntryfmt)
DBCStorage< OverrideSpellDataEntry > sOverrideSpellDataStore (OverrideSpellDatafmt)
DBCStorage< QuestFactionRewardEntry > sQuestFactionRewardStore (QuestFactionRewardfmt)
DBCStorage< QuestSortEntry > sQuestSortStore (QuestSortEntryfmt)
DBCStorage< QuestXPLevel > sQuestXPLevelStore (QuestXPLevelfmt)
DBCStorage< PowerDisplayEntry > sPowerDisplayStore (PowerDisplayfmt)
DBCStorage< PvPDifficultyEntry > sPvPDifficultyStore (PvPDifficultyfmt)
DBCStorage< RandomPropertiesPointsEntry > sRandomPropertiesPointsStore (RandomPropertiesPointsfmt)
DBCStorage< ScalingStatDistributionEntry > sScalingStatDistributionStore (ScalingStatDistributionfmt)
DBCStorage< ScalingStatValuesEntry > sScalingStatValuesStore (ScalingStatValuesfmt)
DBCStorage< SkillLineEntry > sSkillLineStore (SkillLinefmt)
DBCStorage< SkillLineAbilityEntry > sSkillLineAbilityStore (SkillLineAbilityfmt)
DBCStorage< SkillRaceClassInfoEntry > sSkillRaceClassInfoStore (SkillRaceClassInfofmt)
DBCStorage< SkillTiersEntry > sSkillTiersStore (SkillTiersfmt)
DBCStorage< SoundEntriesEntry > sSoundEntriesStore (SoundEntriesfmt)
DBCStorage< SpellItemEnchantmentEntry > sSpellItemEnchantmentStore (SpellItemEnchantmentfmt)
DBCStorage< SpellItemEnchantmentConditionEntry > sSpellItemEnchantmentConditionStore (SpellItemEnchantmentConditionfmt)
DBCStorage< SpellVisualEntry > sSpellVisualStore (SpellVisualfmt)
ItemSpellCategoryStore sItemSpellCategoryStore
PetFamilySpellsStore sPetFamilySpellsStore
DBCStorage< SpellCastTimesEntry > sSpellCastTimesStore (SpellCastTimefmt)
DBCStorage< SpellCategoryEntry > sSpellCategoryStore (SpellCategoryfmt)
DBCStorage< SpellDifficultyEntry > sSpellDifficultyStore (SpellDifficultyfmt)
DBCStorage< SpellDurationEntry > sSpellDurationStore (SpellDurationfmt)
DBCStorage< SpellFocusObjectEntry > sSpellFocusObjectStore (SpellFocusObjectfmt)
DBCStorage< SpellRadiusEntry > sSpellRadiusStore (SpellRadiusfmt)
DBCStorage< SpellRangeEntry > sSpellRangeStore (SpellRangefmt)
DBCStorage< SpellRuneCostEntry > sSpellRuneCostStore (SpellRuneCostfmt)
DBCStorage< SpellShapeshiftFormEntry > sSpellShapeshiftFormStore (SpellShapeshiftFormfmt)
DBCStorage< StableSlotPricesEntry > sStableSlotPricesStore (StableSlotPricesfmt)
DBCStorage< SummonPropertiesEntry > sSummonPropertiesStore (SummonPropertiesfmt)
DBCStorage< TalentEntry > sTalentStore (TalentEntryfmt)
TalentSpellPosMap sTalentSpellPosMap
DBCStorage< TalentTabEntry > sTalentTabStore (TalentTabEntryfmt)
static uint32 sTalentTabPages [MAX_CLASSES][3]
DBCStorage< TaxiNodesEntry > sTaxiNodesStore (TaxiNodesEntryfmt)
TaxiMask sTaxiNodesMask
TaxiMask sOldContinentsNodesMask
TaxiPathSetBySource sTaxiPathSetBySource
DBCStorage< TaxiPathEntry > sTaxiPathStore (TaxiPathEntryfmt)
TaxiPathNodesByPath sTaxiPathNodesByPath
static DBCStorage< TaxiPathNodeEntry > sTaxiPathNodeStore (TaxiPathNodeEntryfmt)
DBCStorage< TeamContributionPoints > sTeamContributionPoints (TeamContributionPointsfmt)
DBCStorage< TotemCategoryEntry > sTotemCategoryStore (TotemCategoryEntryfmt)
DBCStorage< TransportAnimationEntry > sTransportAnimationStore (TransportAnimationfmt)
DBCStorage< TransportRotationEntry > sTransportRotationStore (TransportRotationfmt)
DBCStorage< VehicleEntry > sVehicleStore (VehicleEntryfmt)
DBCStorage< VehicleSeatEntry > sVehicleSeatStore (VehicleSeatEntryfmt)
DBCStorage< WMOAreaTableEntry > sWMOAreaTableStore (WMOAreaTableEntryfmt)
DBCStorage< WorldMapAreaEntry > sWorldMapAreaStore (WorldMapAreaEntryfmt)
DBCStorage< WorldMapOverlayEntry > sWorldMapOverlayStore (WorldMapOverlayEntryfmt)
Typedef Documentation
AreaFlagByAreaID
typedef std::map<uint16, uint32> AreaFlagByAreaID
Definition at line 32 of file DBCStores.cpp.
AreaFlagByMapID
typedef std::map<uint32, uint32> AreaFlagByMapID
Definition at line 33 of file DBCStores.cpp.
FactionTeamMap
typedef std::map<uint32, SimpleFactionsList> FactionTeamMap
Definition at line 93 of file DBCStores.cpp.
StoreProblemList
typedef std::list<std::string> StoreProblemList
Definition at line 216 of file DBCStores.cpp.
WMOAreaInfoByTripple
typedef std::map<WMOAreaTableTripple, std::vector<WMOAreaTableEntry const*> > WMOAreaInfoByTripple
Definition at line 52 of file DBCStores.cpp.
Function Documentation
AcceptableClientBuildsListStr()
std::string AcceptableClientBuildsListStr ()
Definition at line 228 of file DBCStores.cpp.
References EXPECTED_MANGOSD_CLIENT_BUILD.
Referenced by LoadDBCStores(), and Master::Run().
GetAreaEntryByAreaFlagAndMap()
AreaTableEntry const* GetAreaEntryByAreaFlagAndMap (uint32 area_flag, uint32 map_id)
Definition at line 865 of file DBCStores.cpp.
References GetAreaEntryByAreaID(), sAreaStore, and sMapStore.
Referenced by Player::CheckAreaExploreAndOutdoor(), TerrainManager::GetAreaIdByAreaFlag(), TerrainInfo::GetAreaName(), TerrainInfo::getLiquidStatus(), TerrainManager::GetZoneAndAreaIdByAreaFlag(), and TerrainManager::GetZoneIdByAreaFlag().
GetAreaEntryByAreaID()
AreaTableEntry const* GetAreaEntryByAreaID (uint32 area_id)
Definition at line 856 of file DBCStores.cpp.
References GetAreaFlagByAreaID(), and sAreaStore.
Referenced by Player::CanStartFlyInArea(), NamreebAnticheat::Movement::CheckTeleport(), Spell::EffectDuel(), ConditionEntry::Evaluate(), GetAreaEntryByAreaFlagAndMap(), TerrainInfo::GetAreaFlag(), TerrainInfo::GetAreaName(), GridMap::getLiquidStatus(), TerrainInfo::getLiquidStatus(), GossipHello_npc_innkeeper(), Aura::HandleAuraDummy(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleListAreaTriggerCommand(), WorldSession::HandleTogglePvP(), WorldSession::HandleWhoOpcode(), Unit::IsAllowedDamageInArea(), TerrainInfo::IsOutdoors(), ConditionEntry::IsValid(), AchievementCriteriaRequirement::IsValid(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadFishingBaseSkillLevel(), World::LoadGraveyardZones(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellAreas(), Player::RepopAtGraveyard(), Player::UpdateArea(), Creature::UpdateEntry(), Player::UpdateLocalChannels(), and Player::UpdateZone().
GetAreaFlagByAreaID()
int32 GetAreaFlagByAreaID (uint32 area_id)
Definition at line 823 of file DBCStores.cpp.
References sAreaFlagByAreaID.
Referenced by GetAreaEntryByAreaID(), ChatHandler::HandleHideAreaCommand(), ChatHandler::HandleShowAreaCommand(), and AchievementMgr::UpdateAchievementCriteria().
GetAreaFlagByMapId()
uint32 GetAreaFlagByMapId (uint32 mapid)
Definition at line 876 of file DBCStores.cpp.
References sAreaFlagByMapID.
Referenced by TerrainInfo::GetAreaFlag().
GetAreaIdByLocalizedName()
uint32 GetAreaIdByLocalizedName (const std::string & name)
Definition at line 832 of file DBCStores.cpp.
References MAX_LOCALE, and sAreaStore.
GetBattlegroundBracketById()
PvPDifficultyEntry const* GetBattlegroundBracketById (uint32 mapid, BattleGroundBracketId id)
Definition at line 1071 of file DBCStores.cpp.
References sPvPDifficultyStore.
Referenced by BattleGroundQueue::Update().
GetBattlegroundBracketByLevel()
PvPDifficultyEntry const* GetBattlegroundBracketByLevel (uint32 mapid, uint32 level)
Definition at line 1047 of file DBCStores.cpp.
References PvPDifficultyEntry::maxLevel, and sPvPDifficultyStore.
Referenced by BattleGroundMgr::BuildBattleGroundListPacket(), Group::CanJoinBattleGroundQueue(), MapManager::CreateBattleGroundMap(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), and WorldSession::HandleBattlemasterJoinOpcode().
GetCharFacialHairEntry()
CharacterFacialHairStylesEntry const* GetCharFacialHairEntry (uint8 race, uint8 gender, uint8 facialHairId)
Definition at line 913 of file DBCStores.cpp.
References sCharFacialHairMap.
Referenced by Player::ValidateAppearance().
GetCharSectionEntry()
CharSectionsEntry const* GetCharSectionEntry (uint8 race, CharSectionType genType, uint8 gender, uint8 type, uint8 color)
Definition at line 922 of file DBCStores.cpp.
References sCharSectionMap, and SECTION_FLAG_PLAYABLE.
Referenced by Player::ValidateAppearance().
GetChatChannelsEntryFor()
ChatChannelsEntry const* GetChatChannelsEntryFor (const std::string & name, uint32 channel_id)
Definition at line 935 of file DBCStores.cpp.
References MAX_LOCALE, sChatChannelsStore, and Utf8toWStr().
Referenced by Channel::Channel().
GetContentLevelsForMapAndZone()
ContentLevels GetContentLevelsForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 895 of file DBCStores.cpp.
References CONTENT_1_60, CONTENT_61_70, CONTENT_71_80, MapEntry::Expansion(), GetVirtualMapForMapAndZone(), and sMapStore.
Referenced by MaNGOS::XP::Gain().
GetCreatureDisplayStore()
DBCStorage<CreatureDisplayInfoEntry> const* GetCreatureDisplayStore ()
Definition at line 1171 of file DBCStores.cpp.
References sCreatureDisplayInfoStore.
GetCreatureModelRace()
uint32 GetCreatureModelRace (uint32 modelId)
Definition at line 1131 of file DBCStores.cpp.
References sCreatureDisplayInfoExtraStore, and sCreatureDisplayInfoStore.
Referenced by Creature::getRace().
GetDefaultMapLight()
uint32 GetDefaultMapLight (uint32 mapId)
Definition at line 1152 of file DBCStores.cpp.
References LightEntry::id, LightEntry::mapId, sLightStore, LightEntry::x, LightEntry::y, and LightEntry::z.
Referenced by Player::SendOverrideLightUpdate().
GetEmotesStore()
DBCStorage<EmotesEntry> const* GetEmotesStore ()
Definition at line 1172 of file DBCStores.cpp.
References sEmotesStore.
GetEmotesTextStore()
DBCStorage<EmotesTextEntry> const* GetEmotesTextStore ()
Definition at line 1173 of file DBCStores.cpp.
References sEmotesTextStore.
GetFactionStore()
DBCStorage<FactionEntry> const* GetFactionStore ()
Definition at line 1169 of file DBCStores.cpp.
References sFactionStore.
GetFactionTeamList()
SimpleFactionsList const* GetFactionTeamList (uint32 faction)
Definition at line 783 of file DBCStores.cpp.
References sFactionTeamMap.
Referenced by ReputationMgr::SetReputation().
GetItemDisplayStore()
DBCStorage<ItemEntry> const* GetItemDisplayStore ()
Definition at line 1170 of file DBCStores.cpp.
References sItemStore.
GetLFGDungeon()
LFGDungeonEntry const* GetLFGDungeon (uint32 mapId, Difficulty difficulty)
Definition at line 1175 of file DBCStores.cpp.
References LFGDungeonEntry::Difficulty, LFGDungeonEntry::MapID, and sLFGDungeonStore.
GetMapDifficultyData()
MapDifficultyEntry const* GetMapDifficultyData (uint32 mapId, Difficulty difficulty)
Definition at line 1041 of file DBCStores.cpp.
References MAKE_PAIR32, and sMapDifficultyMap.
Referenced by Player::_LoadBoundInstances(), MapPersistentStateManager::_ResetOrWarnAll(), MapManager::CreateDungeonMap(), Player::GetAreaTriggerLockStatus(), Group::GetBoundInstance(), Player::GetBoundInstance(), Map::GetMapDifficulty(), Map::GetMaxPlayers(), MapPersistentStateManager::GetSubsequentResetTime(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadGameObjects(), DungeonResetScheduler::LoadResetTimes(), Player::SendInitialPacketsBeforeAddToMap(), and DungeonResetScheduler::Update().
GetModelMidpoint()
float GetModelMidpoint (uint32 modelId)
Definition at line 1142 of file DBCStores.cpp.
References sCreatureDisplayInfoStore, and sCreatureModelDataStore.
Referenced by Spell::EffectTransmitted().
GetPetName()
char const* GetPetName (uint32 petfamily, uint32 dbclang)
Definition at line 791 of file DBCStores.cpp.
References CreatureFamilyEntry::Name, and sCreatureFamilyStore.
Referenced by ObjectMgr::GeneratePetName().
GetSoundEntriesStore()
DBCStorage<SoundEntriesEntry> const* GetSoundEntriesStore ()
Definition at line 1167 of file DBCStores.cpp.
References sSoundEntriesStore.
Referenced by ScriptedAI::DoPlaySoundToSet().
GetSpellRangeStore()
DBCStorage<SpellRangeEntry> const* GetSpellRangeStore ()
Definition at line 1168 of file DBCStores.cpp.
References sSpellRangeStore.
Referenced by ScriptedAI::CanCast(), PlayerbotAI::In_Range(), and ScriptedAI::SelectSpell().
GetTalentSpellCost() [1/2]
uint32 GetTalentSpellCost (TalentSpellPos const * pos)
Definition at line 810 of file DBCStores.cpp.
References TalentSpellPos::rank.
Referenced by Player::_SaveSpells(), Pet::addSpell(), Player::addSpell(), GetErrorAtShapeshiftedCast(), GetTalentSpellCost(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleListAurasCommand(), ChatHandler::HandleListTalentsCommand(), ChatHandler::HandleUnLearnCommand(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellLearnSpells(), ObjectMgr::LoadTrainers(), Player::removeSpell(), Pet::removeSpell(), Pet::resetTalentsForAllPetsOf(), and ChatHandler::ShowSpellListHelper().
GetTalentSpellCost() [2/2]
uint32 GetTalentSpellCost (uint32 spellId)
Definition at line 818 of file DBCStores.cpp.
References GetTalentSpellCost(), and GetTalentSpellPos().
GetTalentSpellPos()
TalentSpellPos const* GetTalentSpellPos (uint32 spellId)
Definition at line 801 of file DBCStores.cpp.
References sTalentSpellPosMap.
Referenced by Player::_LoadSpells(), Pet::addSpell(), Player::addSpell(), GetTalentSpellCost(), SpellMgr::LoadSpellChains(), Player::removeSpell(), and CharacterDatabaseCleaner::SpellCheck().
GetTalentTabPages()
uint32 const* GetTalentTabPages (uint32 cls)
Definition at line 1081 of file DBCStores.cpp.
References sTalentTabPages.
Referenced by Player::BuildPlayerTalentsInfoData().
GetVirtualMapForMapAndZone()
uint32 GetVirtualMapForMapAndZone (uint32 mapid, uint32 zoneId)
Definition at line 884 of file DBCStores.cpp.
References sWorldMapAreaStore.
Referenced by Player::CanStartFlyInArea(), GetContentLevelsForMapAndZone(), and SpellMgr::GetSpellAllowedInLocationError().
GetWMOAreaTableEntriesByTripple()
std::vector<WMOAreaTableEntry const*>& GetWMOAreaTableEntriesByTripple (int32 rootid, int32 adtid, int32 groupid)
Definition at line 851 of file DBCStores.cpp.
References sWMOAreaInfoByTripple.
Referenced by TerrainInfo::GetAreaFlag(), TerrainInfo::GetAreaName(), and TerrainInfo::IsOutdoors().
IsAcceptableClientBuild()
bool IsAcceptableClientBuild (uint32 build)
Definition at line 218 of file DBCStores.cpp.
References EXPECTED_MANGOSD_CLIENT_BUILD.
Referenced by GridMap::ExistMap(), WorldSocket::HandleAuthSession(), GridMap::loadData(), and LoadDBCStores().
IsPointInAreaTriggerZone()
bool IsPointInAreaTriggerZone (AreaTriggerEntry const * atEntry, uint32 mapid, float x, float y, float z, float delta)
Definition at line 1086 of file DBCStores.cpp.
References AreaTriggerEntry::box_orientation, AreaTriggerEntry::box_x, AreaTriggerEntry::box_y, AreaTriggerEntry::box_z, M_PI, AreaTriggerEntry::mapid, AreaTriggerEntry::radius, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by Player::CheckAreaExploreAndOutdoor(), WorldSession::HandleAreaTriggerOpcode(), and ChatHandler::HandleTriggerActiveCommand().
IsTotemCategoryCompatiableWith()
bool IsTotemCategoryCompatiableWith (uint32 itemTotemCategoryId, uint32 requiredTotemCategoryId)
Definition at line 985 of file DBCStores.cpp.
References TotemCategoryEntry::categoryMask, TotemCategoryEntry::categoryType, and sTotemCategoryStore.
Referenced by Player::HasItemTotemCategory().
LoadDBC()
template<class T > void LoadDBC (LocalData & localeData, BarGoLink & bar, StoreProblemList & errlist, DBCStorage< T > & storage, const std::string & dbc_path, const std::string & filename) inline
Definition at line 309 of file DBCStores.cpp.
References LocalData::availableDbcLocales, LocalData::checkedDbcLocaleBuilds, fullLocaleNameList, DBCStorage< T >::GetFieldCount(), DBCStorage< T >::GetFormat(), DBCFileLoader::GetFormatRecordSize(), DBCStorage< T >::Load(), LoadDBC_assert_print(), DBCStorage< T >::LoadStringsFrom(), LocalData::main_build, MANGOS_ASSERT, LocaleNameStr::name, ReadDBCBuild(), SIZEFMTD, and BarGoLink::step().
Referenced by LoadDBCStores().
LoadDBC_assert_print()
static bool LoadDBC_assert_print (uint32 fsize, uint32 rsize, const std::string & filename) static
Definition at line 288 of file DBCStores.cpp.
References sLog.
Referenced by LoadDBC().
LoadDBCStores()
void LoadDBCStores (const std::string & dataPath)
Definition at line 370 of file DBCStores.cpp.
References AcceptableClientBuildsListStr(), SpellEntry::Attributes, TalentTabEntry::ClassMask, CLASSMASK_ALL_PLAYABLE, SQLStorageBase::GetMaxEntry(), MapEntry::ghost_entrance_map, SpellEntry::Id, IsAcceptableClientBuild(), LoadDBC(), SQLStorage::LookupEntry(), MAKE_PAIR32, MANGOS_ASSERT, TaxiNodesEntry::map_id, MAX_BATTLEGROUND_BRACKETS, MAX_CLASSES, MAX_EFFECT_INDEX, MAX_TALENT_RANK, TaxiNodesEntry::MountCreatureID, RACEMASK_ALL_PLAYABLE, TalentEntry::RankID, ReadDBCBuild(), sAchievementCriteriaStore, sAchievementStore, sAreaFlagByAreaID, sAreaFlagByMapID, sAreaStore, sAreaTriggerStore, sAuctionHouseStore, sBankBagSlotPricesStore, sBarberShopStyleStore, sBattlemasterListStore, sCharacterFacialHairStylesStore, sCharFacialHairMap, sCharSectionMap, sCharSectionsStore, sCharStartOutfitStore, sCharTitlesStore, sChatChannelsStore, sChrClassesStore, sChrRacesStore, sCinematicCameraStore, sCinematicSequencesStore, sCreatureDisplayInfoExtraStore, sCreatureDisplayInfoStore, sCreatureFamilyStore, sCreatureModelDataStore, sCreatureSpellDataStore, sCreatureTypeStore, sCurrencyTypesStore, sDestructibleModelDataStore, sDurabilityCostsStore, sDurabilityQualityStore, sEmotesStore, sEmotesTextStore, sFactionStore, sFactionTeamMap, sFactionTemplateStore, sGameObjectArtKitStore, sGameObjectDisplayInfoStore, sGemPropertiesStore, sGlyphPropertiesStore, sGlyphSlotStore, sGMSurveyAnswersStore, sGMSurveyCurrentSurveyStore, sGMSurveyQuestionsStore, sGMSurveySurveysStore, sGMTicketCategoryStore, sGtBarberShopCostBaseStore, sGtChanceToMeleeCritBaseStore, sGtChanceToMeleeCritStore, sGtChanceToSpellCritBaseStore, sGtChanceToSpellCritStore, sGtCombatRatingsStore, sGtNPCManaCostScalerStore, sGtOCTClassCombatRatingScalarStore, sGtOCTRegenHPStore, sGtRegenHPPerSptStore, sGtRegenMPPerSptStore, sHolidaysStore, sItemBagFamilyStore, sItemClassStore, sItemExtendedCostStore, sItemLimitCategoryStore, sItemRandomPropertiesStore, sItemRandomSuffixStore, sItemSetStore, sItemStore, SkillLineAbilityEntry::skillId, CreatureFamilyEntry::skillLine, sLFGDungeonExpansionStore, sLFGDungeonStore, sLightStore, sLiquidTypeStore, sLockStore, sLog, sMailTemplateStore, sMapDifficultyMap, sMapDifficultyStore, sMapStore, sMovieStore, sOldContinentsNodesMask, sOverrideSpellDataStore, SPELL_ATTR_DO_NOT_DISPLAY, SPELL_ATTR_DO_NOT_LOG, SPELL_ATTR_IS_ABILITY, SPELL_ATTR_PASSIVE, SkillLineAbilityEntry::spellId, sPetFamilySpellsStore, sPowerDisplayStore, sPvPDifficultyStore, sQuestFactionRewardStore, sQuestSortStore, sQuestXPLevelStore, sRandomPropertiesPointsStore, sScalingStatDistributionStore, sScalingStatValuesStore, sSkillLineAbilityStore, sSkillLineStore, sSkillRaceClassInfoStore, sSkillTiersStore, sSoundEntriesStore, sSpellCastTimesStore, sSpellCategoryStore, sSpellDifficultyStore, sSpellDurationStore, sSpellFocusObjectStore, sSpellItemEnchantmentConditionStore, sSpellItemEnchantmentStore, sSpellRadiusStore, sSpellRangeStore, sSpellRuneCostStore, sSpellShapeshiftFormStore, sSpellTemplate, sSpellVisualStore, sStableSlotPricesStore, sSummonPropertiesStore, sTalentSpellPosMap, sTalentStore, sTalentTabPages, sTalentTabStore, sTaxiNodesMask, sTaxiNodesStore, sTaxiPathNodesByPath, sTaxiPathNodeStore, sTaxiPathSetBySource, sTaxiPathStore, sTeamContributionPoints, sTotemCategoryStore, sTransportAnimationStore, sTransportRotationStore, sVehicleSeatStore, sVehicleStore, sWMOAreaInfoByTripple, sWMOAreaTableStore, sWorldMapAreaStore, sWorldMapOverlayStore, TalentTabEntry::tabpage, FactionEntry::team, and Log::WaitBeforeContinueIfNeed().
Referenced by World::SetInitialWorldSettings().
Map2ZoneCoordinates()
bool Map2ZoneCoordinates (float & x, float & y, uint32 zone)
Definition at line 1026 of file DBCStores.cpp.
References sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by ChatHandler::HandleGPSCommand().
MapCoordinateVsZoneCheck()
bool MapCoordinateVsZoneCheck (float x, float y, uint32 mapid, uint32 zone)
Definition at line 1005 of file DBCStores.cpp.
References WorldMapAreaEntry::map_id, sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
ReadDBCBuild()
static uint32 ReadDBCBuild (const std::string & dbc_path, LocaleNameStr const * localeNameStr = nullptr) static
Definition at line 253 of file DBCStores.cpp.
References fullLocaleNameList, LocaleNameStr::name, and ReadDBCBuildFileText().
Referenced by LoadDBC(), and LoadDBCStores().
ReadDBCBuildFileText()
static bool ReadDBCBuildFileText (const std::string & dbc_path, char const * localeName, std::string & text) static
Definition at line 237 of file DBCStores.cpp.
Referenced by ReadDBCBuild().
Zone2MapCoordinates()
bool Zone2MapCoordinates (float & x, float & y, uint32 zone)
Definition at line 1011 of file DBCStores.cpp.
References sWorldMapAreaStore, WorldMapAreaEntry::x1, WorldMapAreaEntry::x2, WorldMapAreaEntry::y1, and WorldMapAreaEntry::y2.
Referenced by ChatHandler::HandleGoZoneXYCommand().
Variable Documentation
sAchievementCriteriaStore
DBCStorage<AchievementCriteriaEntry> sAchievementCriteriaStore(AchievementCriteriafmt) (AchievementCriteriafmt)
Referenced by CharacterDatabaseCleaner::AchievementProgressCheck(), AchievementMgr::DoFailedTimedAchievementCriterias(), ChatHandler::HandleAchievementCriteriaAddCommand(), ChatHandler::HandleAchievementCriteriaRemoveCommand(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), LoadDBCStores(), AchievementMgr::LoadFromDB(), and AchievementMgr::SaveToDB().
sAchievementStore
DBCStorage<AchievementEntry> sAchievementStore(Achievementfmt) (Achievementfmt)
Referenced by ChatHandler::CheckEscapeSequences(), AchievementMgr::DoFailedTimedAchievementCriterias(), ConditionEntry::Evaluate(), ChatHandler::HandleAchievementAddCommand(), ChatHandler::HandleAchievementCommand(), ChatHandler::HandleAchievementCriteriaAddCommand(), ChatHandler::HandleAchievementCriteriaRemoveCommand(), ChatHandler::HandleAchievementRemoveCommand(), ChatHandler::HandleCharacterAchievementsCommand(), ChatHandler::HandleLookupAchievementCommand(), ConditionEntry::IsValid(), AchievementGlobalMgr::LoadAchievementCriteriaList(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), AchievementGlobalMgr::LoadAchievementReferenceList(), AchievementGlobalMgr::LoadCompletedAchievements(), LoadDBCStores(), AchievementMgr::LoadFromDB(), AchievementGlobalMgr::LoadRewards(), AchievementMgr::ResetAchievementCriteria(), AchievementMgr::StartTimedAchievementCriteria(), and AchievementMgr::UpdateAchievementCriteria().
sAreaFlagByAreaID
AreaFlagByAreaID sAreaFlagByAreaID static
Definition at line 55 of file DBCStores.cpp.
Referenced by GetAreaFlagByAreaID(), and LoadDBCStores().
sAreaFlagByMapID
AreaFlagByMapID sAreaFlagByMapID static
Definition at line 56 of file DBCStores.cpp.
Referenced by GetAreaFlagByMapId(), and LoadDBCStores().
sAreaStore
DBCStorage<AreaTableEntry> sAreaStore(AreaTableEntryfmt) (AreaTableEntryfmt)
Referenced by GetAreaEntryByAreaFlagAndMap(), GetAreaEntryByAreaID(), GetAreaIdByLocalizedName(), GridMap::getLiquidStatus(), WorldSession::HandleHearthandResurrect(), ChatHandler::HandleLookupAreaCommand(), LoadDBCStores(), and LoadLootTemplates_Fishing().
sAreaTriggerStore
DBCStorage<AreaTriggerEntry> sAreaTriggerStore(AreaTriggerEntryfmt) (AreaTriggerEntryfmt)
Referenced by Player::CheckAreaExploreAndOutdoor(), ChatHandler::ExtractLocationFromLink(), ObjectMgr::GetGoBackTrigger(), WorldSession::HandleAreaTriggerOpcode(), ChatHandler::HandleGoTriggerCommand(), ChatHandler::HandleListAreaTriggerCommand(), ChatHandler::HandleTriggerActiveCommand(), ChatHandler::HandleTriggerCommand(), ChatHandler::HandleTriggerNearCommand(), ScriptDevAIMgr::LoadAreaTriggerScripts(), ObjectMgr::LoadAreaTriggerTeleports(), LoadDBCStores(), ObjectMgr::LoadQuestAreaTriggers(), and ObjectMgr::LoadTavernAreaTriggers().
sAuctionHouseStore
DBCStorage<AuctionHouseEntry> sAuctionHouseStore(AuctionHouseEntryfmt) (AuctionHouseEntryfmt)
Referenced by AuctionHouseMgr::GetAuctionHouseEntry(), ChatHandler::HandleAuctionItemCommand(), AuctionHouseMgr::LoadAuctions(), LoadDBCStores(), PlayerbotAI::RemoveAuction(), and AuctionHouseBot::Update().
sBankBagSlotPricesStore
DBCStorage<BankBagSlotPricesEntry> sBankBagSlotPricesStore(BankBagSlotPricesEntryfmt) (BankBagSlotPricesEntryfmt)
Referenced by WorldSession::HandleBuyBankSlotOpcode(), and LoadDBCStores().
sBarberShopStyleStore
DBCStorage<BarberShopStyleEntry> sBarberShopStyleStore(BarberShopStyleEntryfmt) (BarberShopStyleEntryfmt)
Referenced by WorldSession::HandleAlterAppearanceOpcode(), and LoadDBCStores().
sBattlemasterListStore
DBCStorage<BattlemasterListEntry> sBattlemasterListStore(BattlemasterListEntryfmt) (BattlemasterListEntryfmt)
Referenced by Group::CanJoinBattleGroundQueue(), BattleGroundMgr::CreateInitialBattleGrounds(), Player::FillBGWeekendWorldStates(), WorldSession::HandleBattlefieldListOpcode(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlemasterJoinOpcode(), BattleGroundMgr::LoadBattleMastersEntry(), LoadDBCStores(), and GameEventMgr::UpdateWorldStates().
sCharacterFacialHairStylesStore
DBCStorage<CharacterFacialHairStylesEntry> sCharacterFacialHairStylesStore(CharacterFacialHairStylesfmt) (CharacterFacialHairStylesfmt)
Referenced by LoadDBCStores().
sCharFacialHairMap
std::unordered_map<uint32, CharacterFacialHairStylesEntry const*> sCharFacialHairMap
Definition at line 71 of file DBCStores.cpp.
Referenced by GetCharFacialHairEntry(), and LoadDBCStores().
sCharSectionMap
std::multimap<uint32, CharSectionsEntry const*> sCharSectionMap
Definition at line 73 of file DBCStores.cpp.
Referenced by GetCharSectionEntry(), and LoadDBCStores().
sCharSectionsStore
DBCStorage<CharSectionsEntry> sCharSectionsStore(CharSectionsEntryfmt) (CharSectionsEntryfmt)
Referenced by LoadDBCStores().
sCharStartOutfitStore
DBCStorage<CharStartOutfitEntry> sCharStartOutfitStore(CharStartOutfitEntryfmt) (CharStartOutfitEntryfmt)
Referenced by Player::Create(), LoadDBCStores(), and ObjectMgr::LoadItemPrototypes().
sCharTitlesStore
DBCStorage<CharTitlesEntry> sCharTitlesStore(CharTitlesEntryfmt) (CharTitlesEntryfmt)
Referenced by Player::_LoadIntoDataField(), Player::_LoadQuestStatus(), AchievementMgr::CompletedAchievement(), ChatHandler::HandleCharacterTitlesCommand(), ChatHandler::HandleLookupTitleCommand(), ChatHandler::HandleTitlesAddCommand(), ChatHandler::HandleTitlesCurrentCommand(), ChatHandler::HandleTitlesRemoveCommand(), ChatHandler::HandleTitlesSetMaskCommand(), ChatHandler::HandleTitlesSwapCommand(), AchievementMgr::IncompletedAchievement(), AchievementCriteriaRequirement::IsValid(), LoadDBCStores(), ObjectMgr::LoadQuests(), AchievementGlobalMgr::LoadRewards(), AchievementCriteriaRequirement::Meets(), BattleGroundMgr::RewardArenaSeason(), Player::RewardQuest(), and Player::SetTitle().
sChatChannelsStore
DBCStorage<ChatChannelsEntry> sChatChannelsStore(ChatChannelsEntryfmt) (ChatChannelsEntryfmt)
Referenced by GetChatChannelsEntryFor(), and LoadDBCStores().
sChrClassesStore
DBCStorage<ChrClassesEntry> sChrClassesStore(ChrClassesEntryfmt) (ChrClassesEntryfmt)
Referenced by Player::Create(), WorldSession::HandleCharCreateOpcode(), ChatHandler::HandleLearnAllMySpellsCommand(), WorldSession::HandlePlayerLogin(), HandleResetStatsOrLevelHelper(), Player::InitDataForForm(), LoadDBCStores(), ObjectMgr::LoadPlayerInfo(), and ChatHandler::ShowPlayerListHelper().
sChrRacesStore
DBCStorage<ChrRacesEntry> sChrRacesStore(ChrRacesEntryfmt) (ChrRacesEntryfmt)
Referenced by World::DetectDBCLang(), Corpse::GetFaction(), Player::getFactionForRace(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandlePlayerLogin(), ObjectMgr::LoadCreatureModelInfo(), LoadDBCStores(), ObjectMgr::LoadPlayerInfo(), ChatHandler::ShowPlayerListHelper(), and Player::TeamForRace().
sCinematicCameraStore
DBCStorage<CinematicCameraEntry> sCinematicCameraStore(CinematicCameraEntryfmt) (CinematicCameraEntryfmt)
Referenced by LoadDBCStores(), and LoadM2Cameras().
sCinematicSequencesStore
DBCStorage<CinematicSequencesEntry> sCinematicSequencesStore(CinematicSequencesEntryfmt) (CinematicSequencesEntryfmt)
Referenced by ChatHandler::HandleDebugPlayCinematicCommand(), LoadDBCStores(), and Player::SendCinematicStart().
sCreatureDisplayInfoExtraStore
DBCStorage<CreatureDisplayInfoExtraEntry> sCreatureDisplayInfoExtraStore(CreatureDisplayInfoExtrafmt) (CreatureDisplayInfoExtrafmt)
Referenced by GetCreatureModelRace(), and LoadDBCStores().
sCreatureDisplayInfoStore
DBCStorage<CreatureDisplayInfoEntry> sCreatureDisplayInfoStore(CreatureDisplayInfofmt) (CreatureDisplayInfofmt)
Referenced by Unit::GetCollisionHeight(), Unit::GetCollisionWidth(), GetCreatureDisplayStore(), GetCreatureModelRace(), GetModelMidpoint(), ChatHandler::HandleGMMountUpCommand(), ChatHandler::HandleModifyMorphCommand(), ObjectMgr::LoadCreatureAddons(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureModelRace(), LoadDBCStores(), and ScriptMgr::LoadScripts().
sCreatureFamilyStore
DBCStorage<CreatureFamilyEntry> sCreatureFamilyStore(CreatureFamilyfmt) (CreatureFamilyfmt)
Referenced by Player::BuildPetTalentsInfoData(), Pet::CreateBaseAtCreature(), GetPetName(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), Pet::HaveInDiet(), Pet::InitStatsForLevel(), Pet::LearnPetPassives(), Player::LearnPetTalent(), LoadDBCStores(), SpellMgr::LoadPetLevelupSpellMap(), and Pet::resetTalents().
sCreatureModelDataStore
DBCStorage<CreatureModelDataEntry> sCreatureModelDataStore(CreatureModelDatafmt) (CreatureModelDatafmt)
Referenced by Unit::GetCollisionHeight(), Unit::GetCollisionWidth(), GetModelMidpoint(), and LoadDBCStores().
sCreatureSpellDataStore
DBCStorage<CreatureSpellDataEntry> sCreatureSpellDataStore(CreatureSpellDatafmt) (CreatureSpellDatafmt)
Referenced by LoadDBCStores(), and SpellMgr::LoadPetDefaultSpells().
sCreatureTypeStore
DBCStorage<CreatureTypeEntry> sCreatureTypeStore(CreatureTypefmt) (CreatureTypefmt)
Referenced by LoadDBCStores().
sCurrencyTypesStore
DBCStorage<CurrencyTypesEntry> sCurrencyTypesStore(CurrencyTypesfmt) (CurrencyTypesfmt)
Referenced by LoadDBCStores(), ObjectMgr::LoadItemPrototypes(), and Player::UpdateKnownCurrencies().
sDestructibleModelDataStore
DBCStorage<DestructibleModelDataEntry> sDestructibleModelDataStore(DestructibleModelDataFmt) (DestructibleModelDataFmt)
Referenced by GameObject::ForceGameObjectHealth(), and LoadDBCStores().
sDurabilityCostsStore
DBCStorage<DurabilityCostsEntry> sDurabilityCostsStore(DurabilityCostsfmt) (DurabilityCostsfmt)
Referenced by Player::DurabilityRepair(), PlayerbotAI::EstRepair(), and LoadDBCStores().
sDurabilityQualityStore
DBCStorage<DurabilityQualityEntry> sDurabilityQualityStore(DurabilityQualityfmt) (DurabilityQualityfmt)
Referenced by Player::DurabilityRepair(), PlayerbotAI::EstRepair(), and LoadDBCStores().
sEmotesStore
DBCStorage<EmotesEntry> sEmotesStore(EmotesEntryfmt) (EmotesEntryfmt)
Referenced by GetEmotesStore(), Unit::HandleEmote(), ChatHandler::HandleModifyStandStateCommand(), ObjectMgr::LoadCreatureAddons(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), LoadDBCStores(), ObjectMgr::LoadMangosStrings(), ObjectMgr::LoadQuestgiverGreeting(), and ScriptMgr::LoadScripts().
sEmotesTextStore
DBCStorage<EmotesTextEntry> sEmotesTextStore(EmotesTextEntryfmt) (EmotesTextEntryfmt)
Referenced by GetEmotesTextStore(), WorldSession::HandleTextEmoteOpcode(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), and LoadDBCStores().
sFactionStore
DBCStorage<FactionEntry> sFactionStore(FactionEntryfmt) (FactionEntryfmt)
Referenced by PlayerbotAI::_HandleCommandQuest(), Player::AddQuest(), Player::CalculateReputationGain(), Unit::CanAttackInCombat(), Unit::CanAttackSpell(), Spell::EffectDummy(), Spell::EffectReputation(), ConditionEntry::Evaluate(), GetFactionReaction(), GetFactionStore(), Unit::GetReactionTo(), ReputationMgr::GetReputation(), Player::GetReputationRank(), OutdoorPvPSI::HandleAreaTrigger(), ChatHandler::HandleCharacterReputationCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleModifyRepCommand(), ChatHandler::HandleQuestCompleteCommand(), ReputationMgr::Initialize(), ReputationMgr::IsAtWar(), Unit::IsNeutralToAll(), ConditionEntry::IsValid(), LoadDBCStores(), ReputationMgr::LoadFromDB(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadQuests(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), Player::ReputationChanged(), Player::RewardReputation(), BattleGround::RewardReputationToTeam(), ReputationMgr::SetReputation(), and ReputationMgr::SetVisible().
sFactionTeamMap
FactionTeamMap sFactionTeamMap static
Definition at line 94 of file DBCStores.cpp.
Referenced by GetFactionTeamList(), and LoadDBCStores().
sFactionTemplateStore
DBCStorage<FactionTemplateEntry> sFactionTemplateStore(FactionTemplateEntryfmt) (FactionTemplateEntryfmt)
Referenced by AuctionHouseMgr::GetAuctionHouseEntry(), Unit::GetFactionTemplateEntry(), Unit::GetReactionTo(), GameObject::GetReactionTo(), Player::GetReactionTo(), Aura::HandleFactionOverride(), ChatHandler::HandleModifyFactionCommand(), ChatHandler::HandleNpcFactionIdCommand(), WorldSession::HandleSetSelectionOpcode(), WorldSession::HandleSetTargetOpcode(), GameObject::IsEnemy(), GameObject::IsFriend(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), LoadDBCStores(), ScriptMgr::LoadScripts(), and Creature::UpdateEntry().
sGameObjectArtKitStore
DBCStorage<GameObjectArtKitEntry> sGameObjectArtKitStore(GameObjectArtKitfmt) (GameObjectArtKitfmt)
Referenced by LoadDBCStores(), and ObjectMgr::LoadGameObjectTemplateAddons().
sGameObjectDisplayInfoStore
DBCStorage<GameObjectDisplayInfoEntry> sGameObjectDisplayInfoStore(GameObjectDisplayInfofmt) (GameObjectDisplayInfofmt)
Referenced by GameObjectModel::construct(), ChatHandler::HandleGameObjectAddCommand(), GameObject::IsAtInteractDistance(), LoadDBCStores(), ObjectMgr::LoadGameObjects(), and GameObject::SetDisplayId().
sGemPropertiesStore
DBCStorage<GemPropertiesEntry> sGemPropertiesStore(GemPropertiesEntryfmt) (GemPropertiesEntryfmt)
Referenced by Player::EnchantmentFitsRequirements(), Item::GemsFitSockets(), WorldSession::HandleSocketOpcode(), LoadDBCStores(), and ObjectMgr::LoadItemPrototypes().
sGlyphPropertiesStore
DBCStorage<GlyphPropertiesEntry> sGlyphPropertiesStore(GlyphPropertiesfmt) (GlyphPropertiesfmt)
Referenced by Player::_LoadGlyphs(), Player::ApplyGlyph(), Spell::CheckCast(), ChatHandler::CheckEscapeSequences(), Spell::EffectApplyGlyph(), ChatHandler::ExtractSpellIdFromLink(), and LoadDBCStores().
sGlyphSlotStore
DBCStorage<GlyphSlotEntry> sGlyphSlotStore(GlyphSlotfmt) (GlyphSlotfmt)
Referenced by Player::_LoadGlyphs(), Spell::EffectApplyGlyph(), Player::InitGlyphsForLevel(), and LoadDBCStores().
sGMSurveyAnswersStore
DBCStorage<GMSurveyAnswersEntry> sGMSurveyAnswersStore(GMSurveyAnswersfmt) (GMSurveyAnswersfmt)
Referenced by WorldSession::HandleGMSurveySubmitOpcode(), and LoadDBCStores().
sGMSurveyCurrentSurveyStore
DBCStorage<GMSurveyCurrentSurveyEntry> sGMSurveyCurrentSurveyStore(GMSurveyCurrentSurveyfmt) (GMSurveyCurrentSurveyfmt)
Referenced by WorldSession::HandleGMSurveySubmitOpcode(), and LoadDBCStores().
sGMSurveyQuestionsStore
DBCStorage<GMSurveyQuestionsEntry> sGMSurveyQuestionsStore(GMSurveyQuestionsfmt) (GMSurveyQuestionsfmt)
Referenced by LoadDBCStores().
sGMSurveySurveysStore
DBCStorage<GMSurveyEntry> sGMSurveySurveysStore(GMSurveySurveysfmt) (GMSurveySurveysfmt)
Referenced by WorldSession::HandleGMSurveySubmitOpcode(), and LoadDBCStores().
sGMTicketCategoryStore
DBCStorage<GMTicketCategoryEntry> sGMTicketCategoryStore(GMTicketCategoryfmt) (GMTicketCategoryfmt)
Referenced by ChatHandler::HandleTicketsListCommand(), ChatHandler::HandleTicketSortCommand(), LoadDBCStores(), and GMTicketMgr::PrintTicketCategory().
sGtBarberShopCostBaseStore
DBCStorage<GtBarberShopCostBaseEntry> sGtBarberShopCostBaseStore(GtBarberShopCostBasefmt) (GtBarberShopCostBasefmt)
Referenced by Player::GetBarberShopCost(), and LoadDBCStores().
sGtChanceToMeleeCritBaseStore
DBCStorage<GtChanceToMeleeCritBaseEntry> sGtChanceToMeleeCritBaseStore(GtChanceToMeleeCritBasefmt) (GtChanceToMeleeCritBasefmt)
Referenced by Player::GetMeleeCritFromAgility(), and LoadDBCStores().
sGtChanceToMeleeCritStore
DBCStorage<GtChanceToMeleeCritEntry> sGtChanceToMeleeCritStore(GtChanceToMeleeCritfmt) (GtChanceToMeleeCritfmt)
Referenced by Player::GetDodgeFromAgility(), Player::GetMeleeCritFromAgility(), and LoadDBCStores().
sGtChanceToSpellCritBaseStore
DBCStorage<GtChanceToSpellCritBaseEntry> sGtChanceToSpellCritBaseStore(GtChanceToSpellCritBasefmt) (GtChanceToSpellCritBasefmt)
Referenced by Player::GetSpellCritFromIntellect(), and LoadDBCStores().
sGtChanceToSpellCritStore
DBCStorage<GtChanceToSpellCritEntry> sGtChanceToSpellCritStore(GtChanceToSpellCritfmt) (GtChanceToSpellCritfmt)
Referenced by Player::GetSpellCritFromIntellect(), and LoadDBCStores().
sGtCombatRatingsStore
DBCStorage<GtCombatRatingsEntry> sGtCombatRatingsStore(GtCombatRatingsfmt) (GtCombatRatingsfmt)
Referenced by Player::GetRatingMultiplier(), and LoadDBCStores().
sGtNPCManaCostScalerStore
DBCStorage<GtNPCManaCostScalerEntry> sGtNPCManaCostScalerStore(GtNPCManaCostScalerfmt) (GtNPCManaCostScalerfmt)
Referenced by Spell::CalculatePowerCost(), WorldObject::CalculateSpellEffectValue(), and LoadDBCStores().
sGtOCTClassCombatRatingScalarStore
DBCStorage<GtOCTClassCombatRatingScalarEntry> sGtOCTClassCombatRatingScalarStore(GtOCTClassCombatRatingScalarfmt) (GtOCTClassCombatRatingScalarfmt)
Referenced by Player::GetRatingMultiplier(), and LoadDBCStores().
sGtOCTRegenHPStore
DBCStorage<GtOCTRegenHPEntry> sGtOCTRegenHPStore(GtOCTRegenHPfmt) (GtOCTRegenHPfmt)
Referenced by LoadDBCStores(), and Unit::OCTRegenHPPerSpirit().
sGtRegenHPPerSptStore
DBCStorage<GtRegenHPPerSptEntry> sGtRegenHPPerSptStore(GtRegenHPPerSptfmt) (GtRegenHPPerSptfmt)
Referenced by LoadDBCStores(), and Unit::OCTRegenHPPerSpirit().
sGtRegenMPPerSptStore
DBCStorage<GtRegenMPPerSptEntry> sGtRegenMPPerSptStore(GtRegenMPPerSptfmt) (GtRegenMPPerSptfmt)
Referenced by LoadDBCStores(), and Unit::OCTRegenMPPerSpirit().
sHolidaysStore
DBCStorage<HolidaysEntry> sHolidaysStore(Holidaysfmt) (Holidaysfmt)
Referenced by WorldSession::HandleCalendarGetCalendar(), AchievementCriteriaRequirement::IsValid(), LoadDBCStores(), GameEventMgr::LoadFromDB(), and ObjectMgr::LoadItemPrototypes().
sItemBagFamilyStore
DBCStorage<ItemBagFamilyEntry> sItemBagFamilyStore(ItemBagFamilyfmt) (ItemBagFamilyfmt)
Referenced by LoadDBCStores(), and ObjectMgr::LoadItemPrototypes().
sItemClassStore
DBCStorage<ItemClassEntry> sItemClassStore(ItemClassfmt) (ItemClassfmt)
Referenced by LoadDBCStores().
sItemExtendedCostStore
DBCStorage<ItemExtendedCostEntry> sItemExtendedCostStore(ItemExtendedCostEntryfmt) (ItemExtendedCostEntryfmt)
Referenced by Player::BuyItemFromVendorSlot(), ObjectMgr::IsVendorItemValid(), LoadDBCStores(), and Player::TakeExtendedCost().
sItemLimitCategoryStore
DBCStorage<ItemLimitCategoryEntry> sItemLimitCategoryStore(ItemLimitCategoryEntryfmt) (ItemLimitCategoryEntryfmt)
Referenced by Player::_CanTakeMoreSimilarItems(), Player::CanEquipUniqueItem(), WorldSession::HandleSocketOpcode(), LoadDBCStores(), and ObjectMgr::LoadItemPrototypes().
sItemRandomPropertiesStore
DBCStorage<ItemRandomPropertiesEntry> sItemRandomPropertiesStore(ItemRandomPropertiesfmt) (ItemRandomPropertiesfmt)
Referenced by ChatHandler::CheckEscapeSequences(), Item::GenerateItemRandomPropertyId(), LoadDBCStores(), ObjectMgr::LoadItemPrototypes(), and Item::SetItemRandomProperties().
sItemRandomSuffixStore
DBCStorage<ItemRandomSuffixEntry> sItemRandomSuffixStore(ItemRandomSuffixfmt) (ItemRandomSuffixfmt)
Referenced by Player::ApplyEnchantment(), Aura::Aura(), ChatHandler::CheckEscapeSequences(), Item::GenerateItemRandomPropertyId(), LoadDBCStores(), ObjectMgr::LoadItemPrototypes(), and Item::SetItemRandomProperties().
sItemSetStore
DBCStorage<ItemSetEntry> sItemSetStore(ItemSetEntryfmt) (ItemSetEntryfmt)
Referenced by AddItemsSetItem(), ChatHandler::HandleLookupItemSetCommand(), LoadDBCStores(), ObjectMgr::LoadItemPrototypes(), and RemoveItemsSetItem().
sItemSpellCategoryStore
ItemSpellCategoryStore sItemSpellCategoryStore
Definition at line 172 of file DBCStores.cpp.
Referenced by ObjectMgr::LoadItemPrototypes().
sItemStore
DBCStorage<ItemEntry> sItemStore(Itemfmt) (Itemfmt)
Referenced by GetItemDisplayStore(), WorldSession::HandleItemNameQueryOpcode(), Creature::hasWeapon(), LoadDBCStores(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadItemPrototypes(), and Spell::WriteAmmoToPacket().
sLFGDungeonExpansionStore
DBCStorage<LfgDungeonExpansionEntry> sLFGDungeonExpansionStore(LFGDungeonExpansionEntryfmt) (LFGDungeonExpansionEntryfmt)
Referenced by LFGDungeonData::LFGDungeonData(), and LoadDBCStores().
sLFGDungeonStore
DBCStorage<LFGDungeonEntry> sLFGDungeonStore(LFGDungeonEntryfmt) (LFGDungeonEntryfmt)
Referenced by GetLFGDungeon(), WorldSession::HandleLfgJoinOpcode(), LoadDBCStores(), and LFGMgr::LoadLFGDungeons().
sLightStore
DBCStorage<LightEntry> sLightStore(LightEntryfmt) (LightEntryfmt)
Referenced by GetDefaultMapLight(), and LoadDBCStores().
sLiquidTypeStore
DBCStorage<LiquidTypeEntry> sLiquidTypeStore(LiquidTypefmt) (LiquidTypefmt)
Referenced by GridMap::getLiquidStatus(), TerrainInfo::getLiquidStatus(), LoadDBCStores(), and Player::UpdateTerainEnvironmentFlags().
sLockStore
DBCStorage<LockEntry> sLockStore(LockEntryfmt) (LockEntryfmt)
Referenced by Spell::CanOpenLock(), CheckGOLockId(), PlayerbotAI::DoLoot(), GameObject::GetSpellForLock(), WorldSession::HandleOpenItemOpcode(), LoadDBCStores(), ObjectMgr::LoadItemPrototypes(), and Loot::Release().
sMailTemplateStore
DBCStorage<MailTemplateEntry> sMailTemplateStore(MailTemplateEntryfmt) (MailTemplateEntryfmt)
Referenced by Player::_LoadMails(), WorldSession::HandleMailCreateTextItem(), LoadDBCStores(), GameEventMgr::LoadFromDB(), LoadLootTemplates_Mail(), ObjectMgr::LoadMailLevelRewards(), ObjectMgr::LoadQuests(), and ScriptMgr::LoadScripts().
sMapDifficultyMap
MapDifficultyMap sMapDifficultyMap
Definition at line 146 of file DBCStores.cpp.
Referenced by GetMapDifficultyData(), WorldSession::HandleCalendarGetCalendar(), LoadDBCStores(), and DungeonResetScheduler::LoadResetTimes().
sMapDifficultyStore
DBCStorage<MapDifficultyEntry> sMapDifficultyStore(MapDifficultyEntryfmt) (MapDifficultyEntryfmt)
Referenced by LoadDBCStores(), and Player::SendTransferAbortedByLockStatus().
sMapStore
DBCStorage<MapEntry> sMapStore(MapEntryfmt) (MapEntryfmt)
Referenced by Player::_LoadBoundInstances(), Player::_LoadHomeBind(), MapPersistentStateManager::_ResetOrWarnAll(), PoolMapChecker::CheckAndRemember(), Player::CheckAndRevivePlayerOnDungeonEnter(), Spell::CheckCast(), NamreebAnticheat::Movement::CheckTeleport(), MapManager::CreateDungeonMap(), MapManager::CreateInstance(), MapManager::CreateMap(), MapPersistentStateManager::DoForAllStatesWithMapId(), Spell::EffectTeleportUnits(), TransportMgr::GenerateWaypoints(), GetAreaEntryByAreaFlagAndMap(), Player::GetAreaTriggerLockStatus(), Group::GetBoundInstance(), Player::GetBoundInstanceSaveForSelfOrGroup(), GraveyardManager::GetClosestGraveyardHelper(), GetContentLevelsForMapAndZone(), ObjectMgr::GetGoBackTrigger(), ObjectMgr::GetMapEntranceTrigger(), MapPersistentState::GetMapEntry(), DungeonPersistentState::GetResetTimeForDB(), SpellMgr::GetSpellAllowedInLocationError(), WorldSession::HandleAreaTriggerOpcode(), WorldSession::HandleCalendarGetCalendar(), WorldSession::HandleCorpseQueryOpcode(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), WorldSession::HandleMoveWorldportAckOpcode(), WorldSession::HandlePlayerLogin(), ChatHandler::HandleTeleGroupCommand(), MapPersistentStateManager::InitWorldMaps(), FollowMovementGenerator::IsBoostAllowed(), CreatureLinkingMgr::IsLinkingEntryValid(), AchievementCriteriaRequirement::IsValid(), MapManager::IsValidMAP(), Player::KillPlayer(), ObjectMgr::LoadAreaTriggerTeleports(), Player::LoadCorpse(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), LoadDBCStores(), Player::LoadFromDB(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), World::LoadGraveyardZones(), ObjectMgr::LoadGroups(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadItemPrototypes(), TerrainInfo::LoadMapAndVMap(), ObjectMgr::LoadPlayerInfo(), DungeonResetScheduler::LoadResetTimes(), ScriptMgr::LoadScripts(), SpellMgr::LoadSpellTargetPositions(), MapManager::LoadTransports(), ObjectMgr::LoadWorldTemplate(), Taxi::Tracker::Prepare(), Player::ResetInstances(), Group::ResetInstances(), Group::RewardGroupAtKill(), Player::RewardReputation(), Pet::SetDeathState(), and Player::TeleportTo().
sMovieStore
DBCStorage<MovieEntry> sMovieStore(MovieEntryfmt) (MovieEntryfmt)
Referenced by ChatHandler::HandleDebugPlayMovieCommand(), LoadDBCStores(), and ScriptMgr::LoadScripts().
sOldContinentsNodesMask
TaxiMask sOldContinentsNodesMask
Definition at line 195 of file DBCStores.cpp.
Referenced by PlayerTaxi::InitTaxiNodesForLevel(), and LoadDBCStores().
sOverrideSpellDataStore
DBCStorage<OverrideSpellDataEntry> sOverrideSpellDataStore(OverrideSpellDatafmt) (OverrideSpellDatafmt)
Referenced by Aura::HandleAuraAddMechanicAbilities(), and LoadDBCStores().
sPetFamilySpellsStore
PetFamilySpellsStore sPetFamilySpellsStore
Definition at line 173 of file DBCStores.cpp.
Referenced by Pet::LearnPetPassives(), and LoadDBCStores().
sPowerDisplayStore
DBCStorage<PowerDisplayEntry> sPowerDisplayStore(PowerDisplayfmt) (PowerDisplayfmt)
Referenced by VehicleInfo::Initialize(), and LoadDBCStores().
sPvPDifficultyStore
DBCStorage<PvPDifficultyEntry> sPvPDifficultyStore(PvPDifficultyfmt) (PvPDifficultyfmt)
Referenced by GetBattlegroundBracketById(), GetBattlegroundBracketByLevel(), and LoadDBCStores().
sQuestFactionRewardStore
DBCStorage<QuestFactionRewardEntry> sQuestFactionRewardStore(QuestFactionRewardfmt) (QuestFactionRewardfmt)
Referenced by LoadDBCStores(), and Player::RewardReputation().
sQuestSortStore
DBCStorage<QuestSortEntry> sQuestSortStore(QuestSortEntryfmt) (QuestSortEntryfmt)
Referenced by LoadDBCStores(), and ObjectMgr::LoadQuests().
sQuestXPLevelStore
DBCStorage<QuestXPLevel> sQuestXPLevelStore(QuestXPLevelfmt) (QuestXPLevelfmt)
Referenced by Quest::GetXPReward(), and LoadDBCStores().
sRandomPropertiesPointsStore
DBCStorage<RandomPropertiesPointsEntry> sRandomPropertiesPointsStore(RandomPropertiesPointsfmt) (RandomPropertiesPointsfmt)
Referenced by GenerateEnchSuffixFactor(), and LoadDBCStores().
sScalingStatDistributionStore
DBCStorage<ScalingStatDistributionEntry> sScalingStatDistributionStore(ScalingStatDistributionfmt) (ScalingStatDistributionfmt)
Referenced by Player::_ApplyItemBonuses(), Player::CanEquipItem(), Player::CanUseItem(), and LoadDBCStores().
sScalingStatValuesStore
DBCStorage<ScalingStatValuesEntry> sScalingStatValuesStore(ScalingStatValuesfmt) (ScalingStatValuesfmt)
Referenced by Player::_ApplyItemBonuses(), and LoadDBCStores().
sSkillLineAbilityStore
DBCStorage<SkillLineAbilityEntry> sSkillLineAbilityStore(SkillLineAbilityfmt) (SkillLineAbilityfmt)
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandSkill(), Player::CanUseItem(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnSkillRecipesHelper(), LoadDBCStores(), SpellMgr::LoadPetLevelupSpellMap(), and SpellMgr::LoadSkillLineAbilityMaps().
sSkillLineStore
DBCStorage<SkillLineEntry> sSkillLineStore(SkillLinefmt) (SkillLinefmt)
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandSkill(), Player::_LoadSkills(), ChatHandler::CheckEscapeSequences(), ChatHandler::HandleLearnAllCraftsCommand(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleSetSkillCommand(), IsPrimaryProfessionSkill(), ConditionEntry::IsValid(), Player::LearnDefaultSkills(), LoadDBCStores(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadQuests(), SpellMgr::LoadSkillRaceClassInfoMap(), Player::SetSkill(), CharacterDatabaseCleaner::SkillCheck(), Player::UpdateSkillsForLevel(), and Player::UpdateSpellTrainedSkills().
sSkillRaceClassInfoStore
DBCStorage<SkillRaceClassInfoEntry> sSkillRaceClassInfoStore(SkillRaceClassInfofmt) (SkillRaceClassInfofmt)
Referenced by LoadDBCStores(), and SpellMgr::LoadSkillRaceClassInfoMap().
sSkillTiersStore
DBCStorage<SkillTiersEntry> sSkillTiersStore(SkillTiersfmt) (SkillTiersfmt)
Referenced by Player::_LoadSkills(), Player::LearnDefaultSkills(), LoadDBCStores(), ObjectMgr::LoadPlayerInfo(), and Player::SetSkillStep().
sSoundEntriesStore
DBCStorage<SoundEntriesEntry> sSoundEntriesStore(SoundEntriesfmt) (SoundEntriesfmt)
Referenced by Spell::EffectPlayMusic(), Spell::EffectPlaySound(), GetSoundEntriesStore(), ChatHandler::HandleDebugPlayMusicCommand(), ChatHandler::HandleDebugPlaySoundCommand(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), LoadDBCStores(), ObjectMgr::LoadMangosStrings(), and ScriptMgr::LoadScripts().
sSpellCastTimesStore
DBCStorage<SpellCastTimesEntry> sSpellCastTimesStore(SpellCastTimefmt) (SpellCastTimefmt)
Referenced by PlayerbotAI::CastSpell(), ObjectMgr::ConvertCreatureAddonAuras(), Spell::EffectDummy(), GetSpellCastTime(), LoadDBCStores(), and PlayerbotAI::UseItem().
sSpellCategoryStore
DBCStorage<SpellCategoryEntry> sSpellCategoryStore(SpellCategoryfmt) (SpellCategoryfmt)
Referenced by SpellMgr::CheckUsedSpells(), LoadDBCStores(), and Spell::SendSpellCooldown().
sSpellDifficultyStore
DBCStorage<SpellDifficultyEntry> sSpellDifficultyStore(SpellDifficultyfmt) (SpellDifficultyfmt)
Referenced by GetSpellEntryByDifficulty(), and LoadDBCStores().
sSpellDurationStore
DBCStorage<SpellDurationEntry> sSpellDurationStore(SpellDurationfmt) (SpellDurationfmt)
Referenced by GetSpellDuration(), GetSpellMaxDuration(), and LoadDBCStores().
sSpellFocusObjectStore
DBCStorage<SpellFocusObjectEntry> sSpellFocusObjectStore(SpellFocusObjectfmt) (SpellFocusObjectfmt)
Referenced by LoadDBCStores(), and ObjectMgr::LoadGameobjectInfo().
sSpellItemEnchantmentConditionStore
DBCStorage<SpellItemEnchantmentConditionEntry> sSpellItemEnchantmentConditionStore(SpellItemEnchantmentConditionfmt) (SpellItemEnchantmentConditionfmt)
Referenced by Player::EnchantmentFitsRequirements(), and LoadDBCStores().
sSpellItemEnchantmentStore
DBCStorage<SpellItemEnchantmentEntry> sSpellItemEnchantmentStore(SpellItemEnchantmentfmt) (SpellItemEnchantmentfmt)
Referenced by Player::_HandleDeadlyPoison(), Player::ApplyEnchantment(), Aura::Aura(), Player::BuildEnumData(), Item::CanEnterArenaEnchant(), Player::CanEquipUniqueItem(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), Spell::CheckItems(), Player::CorrectMetaGemEnchants(), Spell::EffectDummy(), Spell::EffectEnchantHeldItem(), Spell::EffectEnchantItemPerm(), Spell::EffectEnchantItemPrismatic(), Spell::EffectEnchantItemTmp(), Player::EnchantmentFitsRequirements(), Item::GemsFitSockets(), Item::GetGemCountWithID(), Item::GetGemCountWithLimitCategory(), WorldSession::HandleSocketOpcode(), Item::IsBoundByEnchant(), Item::IsMainHandOnlyEnchant(), LoadDBCStores(), PlayerbotAI::MakeItemLink(), LavaLash::OnEffectExecute(), and Player::ToggleMetaGemsActive().
sSpellRadiusStore
DBCStorage<SpellRadiusEntry> sSpellRadiusStore(SpellRadiusfmt) (SpellRadiusfmt)
Referenced by AreaAura::AreaAura(), Spell::CheckCast(), Spell::EffectPersistentAA(), Spell::EffectSummonType(), Spell::EffectTransmitted(), PlayerbotClassAI::FleeFromAoEIfCan(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), Spell::GetSpellRangeAndRadius(), Unit::HandleDummyAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), LoadDBCStores(), Unit::MeetsSelectAttackingRequirement(), Aura::PeriodicDummyTick(), Spell::SendChannelStart(), Spell::SetTargetMap(), and go_aura_generator_000AI::UpdateAI().
sSpellRangeStore
DBCStorage<SpellRangeEntry> sSpellRangeStore(SpellRangefmt) (SpellRangefmt)
Referenced by UnitAI::AddMainSpell(), UnitAI::CalculateSpellRange(), Spell::CheckCast(), Spell::CheckRange(), Spell::EffectDummy(), Spell::EffectTransmitted(), Spell::FindCorpseUsing(), GetChainJumpRange(), Spell::GetMinMaxRange(), Spell::GetSpellRangeAndRadius(), GetSpellRangeStore(), Unit::HandleDummyAuraProc(), WorldSession::HandlePetActionHelper(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), PlayerbotAI::initSpell(), GameObject::IsAtInteractDistance(), LoadDBCStores(), Unit::MeetsSelectAttackingRequirement(), DemonBroiledSurprise::OnCheckCast(), RaiseDeadHyjal::OnCheckCast(), TossIceBoulder::OnRadiusCalculate(), RandomRadiusPicker::OnRadiusCalculate(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), Spell::SetTargetMap(), and TotemAI::UpdateAI().
sSpellRuneCostStore
DBCStorage<SpellRuneCostEntry> sSpellRuneCostStore(SpellRuneCostfmt) (SpellRuneCostfmt)
Referenced by Spell::CheckOrTakeRunePower(), and LoadDBCStores().
sSpellShapeshiftFormStore
DBCStorage<SpellShapeshiftFormEntry> sSpellShapeshiftFormStore(SpellShapeshiftFormfmt) (SpellShapeshiftFormfmt)
Referenced by Unit::CanInteractNow(), Spell::CheckVehicle(), Unit::GetCreatureType(), GetErrorAtShapeshiftedCast(), Aura::HandleAuraModShapeshift(), Player::InitDataForForm(), Unit::IsNoWeaponShapeShift(), Unit::IsShapeShifted(), LoadDBCStores(), and Player::UpdateAttackPowerAndDamage().
sSpellVisualStore
DBCStorage<SpellVisualEntry> sSpellVisualStore(SpellVisualfmt) (SpellVisualfmt)
Referenced by Spell::IsSpellRequiringAmmo(), and LoadDBCStores().
sStableSlotPricesStore
DBCStorage<StableSlotPricesEntry> sStableSlotPricesStore(StableSlotPricesfmt) (StableSlotPricesfmt)
Referenced by WorldSession::HandleBuyStableSlot(), and LoadDBCStores().
sSummonPropertiesStore
DBCStorage<SummonPropertiesEntry> sSummonPropertiesStore(SummonPropertiesfmt) (SummonPropertiesfmt)
Referenced by Spell::CheckCast(), Spell::CheckVehicle(), Spell::EffectSummonType(), and LoadDBCStores().
sTalentSpellPosMap
TalentSpellPosMap sTalentSpellPosMap
Definition at line 187 of file DBCStores.cpp.
Referenced by GetTalentSpellPos(), and LoadDBCStores().
sTalentStore
DBCStorage<TalentEntry> sTalentStore(TalentEntryfmt) (TalentEntryfmt)
Referenced by Player::_LoadTalents(), Pet::addSpell(), Player::addSpell(), Player::BuildPetTalentsInfoData(), ChatHandler::CheckEscapeSequences(), ChatHandler::ExtractSpellIdFromLink(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), Player::LearnPetTalent(), Player::LearnTalent(), LoadDBCStores(), SpellMgr::LoadSpellChains(), Pet::resetTalents(), and CharacterDatabaseCleaner::TalentCheck().
sTalentTabPages
uint32 sTalentTabPages[MAX_CLASSES][3] static
Definition at line 191 of file DBCStores.cpp.
Referenced by GetTalentTabPages(), and LoadDBCStores().
sTalentTabStore
DBCStorage<TalentTabEntry> sTalentTabStore(TalentTabEntryfmt) (TalentTabEntryfmt)
Referenced by Player::_LoadTalents(), Player::addSpell(), Player::BuildPetTalentsInfoData(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), Player::LearnPetTalent(), Player::LearnTalent(), LoadDBCStores(), Pet::resetTalents(), Player::resetTalents(), and CharacterDatabaseCleaner::TalentCheck().
sTaxiNodesMask
TaxiMask sTaxiNodesMask
Definition at line 194 of file DBCStores.cpp.
Referenced by PlayerTaxi::AppendTaximaskTo(), ObjectMgr::GetNearestTaxiNode(), LoadDBCStores(), and PlayerTaxi::LoadTaxiMask().
sTaxiNodesStore
DBCStorage<TaxiNodesEntry> sTaxiNodesStore(TaxiNodesEntryfmt) (TaxiNodesEntryfmt)
Referenced by Player::ActivateTaxiPathTo(), Spell::EffectTeachTaxiNode(), ChatHandler::ExtractLocationFromLink(), ObjectMgr::GetNearestTaxiNode(), ObjectMgr::GetTaxiMountDisplayId(), ChatHandler::HandleGoTaxinodeCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), LoadDBCStores(), Player::LoadFromDB(), Player::OnTaxiFlightEnd(), and Taxi::Tracker::Trim().
sTaxiPathNodesByPath
TaxiPathNodesByPath sTaxiPathNodesByPath
Definition at line 202 of file DBCStores.cpp.
Referenced by Taxi::Tracker::AddRoute(), ScriptMgr::CollectPossibleEventIds(), TransportMgr::GenerateWaypoints(), LoadDBCStores(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadTaxiShortcuts(), Taxi::Tracker::Prepare(), and Taxi::Tracker::Trim().
sTaxiPathNodeStore
DBCStorage<TaxiPathNodeEntry> sTaxiPathNodeStore(TaxiPathNodeEntryfmt) (TaxiPathNodeEntryfmt) static
Referenced by LoadDBCStores().
sTaxiPathSetBySource
TaxiPathSetBySource sTaxiPathSetBySource
Definition at line 198 of file DBCStores.cpp.
Referenced by ObjectMgr::GetTaxiPath(), and LoadDBCStores().
sTaxiPathStore
DBCStorage<TaxiPathEntry> sTaxiPathStore(TaxiPathEntryfmt) (TaxiPathEntryfmt)
Referenced by Player::ActivateTaxiPathTo(), Taxi::Tracker::AddRoute(), LoadDBCStores(), ScriptMgr::LoadScripts(), ObjectMgr::LoadTaxiShortcuts(), Player::OnTaxiFlightRouteEnd(), Player::OnTaxiFlightRouteStart(), and Player::OnTaxiFlightSplineStart().
sTeamContributionPoints
DBCStorage<TeamContributionPoints> sTeamContributionPoints(TeamContributionPointsfmt) (TeamContributionPointsfmt)
Referenced by Quest::CalculateRewardHonor(), and LoadDBCStores().
sTotemCategoryStore
DBCStorage<TotemCategoryEntry> sTotemCategoryStore(TotemCategoryEntryfmt) (TotemCategoryEntryfmt)
Referenced by IsTotemCategoryCompatiableWith(), LoadDBCStores(), and ObjectMgr::LoadItemPrototypes().
sTransportAnimationStore
DBCStorage<TransportAnimationEntry> sTransportAnimationStore(TransportAnimationfmt) (TransportAnimationfmt)
Referenced by LoadDBCStores(), and TransportMgr::LoadTransportAnimationAndRotation().
sTransportRotationStore
DBCStorage<TransportRotationEntry> sTransportRotationStore(TransportRotationfmt) (TransportRotationfmt)
Referenced by LoadDBCStores(), and TransportMgr::LoadTransportAnimationAndRotation().
sVehicleSeatStore
DBCStorage<VehicleSeatEntry> sVehicleSeatStore(VehicleSeatEntryfmt) (VehicleSeatEntryfmt)
Referenced by CreatureAI::AttackPassengersIfCan(), LoadDBCStores(), ObjectMgr::LoadVehicleSeatParameters(), and VehicleInfo::VehicleInfo().
sVehicleStore
DBCStorage<VehicleEntry> sVehicleStore(VehicleEntryfmt) (VehicleEntryfmt)
Referenced by LoadDBCStores(), and Unit::SetVehicleId().
sWMOAreaInfoByTripple
WMOAreaInfoByTripple sWMOAreaInfoByTripple static
Definition at line 58 of file DBCStores.cpp.
Referenced by GetWMOAreaTableEntriesByTripple(), and LoadDBCStores().
sWMOAreaTableStore
DBCStorage<WMOAreaTableEntry> sWMOAreaTableStore(WMOAreaTableEntryfmt) (WMOAreaTableEntryfmt)
Referenced by LoadDBCStores().
sWorldMapAreaStore
DBCStorage<WorldMapAreaEntry> sWorldMapAreaStore(WorldMapAreaEntryfmt) (WorldMapAreaEntryfmt)
Referenced by GetVirtualMapForMapAndZone(), LoadDBCStores(), Map2ZoneCoordinates(), MapCoordinateVsZoneCheck(), and Zone2MapCoordinates().
sWorldMapOverlayStore
DBCStorage<WorldMapOverlayEntry> sWorldMapOverlayStore(WorldMapOverlayEntryfmt) (WorldMapOverlayEntryfmt)
Referenced by LoadDBCStores(), and AchievementMgr::UpdateAchievementCriteria().