CMaNGOS_WoTLK: desolace.cpp File Reference
desolace.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
Data Structures
struct npc_aged_dying_ancient_kodoAI
struct npc_dalinda_malemAI
struct SummonLocation
struct npc_melizza_brimbuzzleAI
struct npc_cork_gizeltonAI
struct npc_rigger_gizeltonAI
struct npc_magrami_spectre
Enumerations
enum {
SAY_SMEED_HOME_1 = -1000348 , SAY_SMEED_HOME_2 = -1000349 , SAY_SMEED_HOME_3 = -1000350 , QUEST_KODO = 5561 ,
NPC_SMEED = 11596 , NPC_AGED_KODO = 4700 , NPC_DYING_KODO = 4701 , NPC_ANCIENT_KODO = 4702 ,
NPC_TAMED_KODO = 11627 , SPELL_KODO_KOMBO_ITEM = 18153 , SPELL_KODO_KOMBO_PLAYER_BUFF = 18172 , SPELL_KODO_KOMBO_DESPAWN_BUFF = 18377 ,
SPELL_KODO_KOMBO_GOSSIP = 18362 , SPELL_KODO_KOMBOBULATOR = 18793 , SPELL_KODO_DESPAWN = 22970
}
enum { QUEST_RETURN_TO_VAHLARRIEL = 1440 }
enum {
QUEST_GET_ME_OUT_OF_HERE = 6132 , GO_MELIZZAS_CAGE = 177706 , SAY_MELIZZA_START = -1000784 , SAY_MELIZZA_FINISH = -1000785 ,
SAY_MELIZZA_1 = -1000786 , SAY_MELIZZA_2 = -1000787 , SAY_MELIZZA_3 = -1000788 , SAY_HORNIZZ_1 = -1010030 ,
SAY_HORNIZZ_2 = -1010031 , NPC_MARAUDINE_MARAUDER = 4659 , NPC_MARAUDINE_BONEPAW = 4660 , NPC_MARAUDINE_WRANGLER = 4655 ,
NPC_MELIZZA = 12277 , POINT_ID_QUEST_COMPLETE = 1 , POINT_ID_EVENT_COMPLETE = 2 , MAX_MARAUDERS = 2 ,
MAX_WRANGLERS = 3
}
enum {
NPC_CORK_GIZELTON = 11625 , NPC_RIGGER_GIZELTON = 11626 , NPC_VENDOR_TRON = 12245 , NPC_SUPER_SELLER = 12246 ,
QUEST_BODYGUARD_TO_HIRE = 5821 , QUEST_GIZELTON_CARAVAN = 5943 , WAYPOINT_PATH_ID = 19019 , PATH_ID_CORK_GIZELTON = 11625 ,
PATH_ID_RIGGER_GIZELTON = 11626 , WAYPOINT_PATH_POINT_AFTER_ESCORT_1 = 33 , WAYPOINT_PATH_POINT_AFTER_ESCORT_2 = 100 , GIZELTON_TIMER_AFTER_FAIL = 60 * IN_MILLISECONDS
}
enum {
SPELL_CURSE_OF_MAGRAMI = 18159 , SPELL_GHOST_SPAWN_IN = 17321 , SPELL_BLUE_AURA = 17327 , SPELL_GREEN_AURA = 18951 ,
SPELL_CHILLING_TOUCH = 18146 , FACTION_HOSTILE = 16 , SAY_EMOTE_1 = -1001239 , SAY_EMOTE_2 = -1001240
}
Functions
UnitAI * GetAI_npc_aged_dying_ancient_kodo (Creature *pCreature)
bool EffectDummyCreature_npc_aged_dying_ancient_kodo (Unit *pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature *pCreatureTarget, ObjectGuid)
bool GossipHello_npc_aged_dying_ancient_kodo (Player *pPlayer, Creature *pCreature)
UnitAI * GetAI_npc_dalinda_malem (Creature *pCreature)
bool QuestAccept_npc_dalinda_malem (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_melizza_brimbuzzle (Creature *pCreature)
bool QuestAccept_npc_melizza_brimbuzzle (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool QuestAccept_npc_cork_gizelton (Player *player, Creature *creature, const Quest *quest)
bool QuestAccept_npc_rigger_gizelton (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_magrami_spectre (Creature *pCreature)
void AddSC_desolace ()
Variables
static const DialogueEntry aIntroDialogue []
static const SummonLocation aMarauderSpawn []
static const SummonLocation wranglerSpawn = { -1393.194f, 2429.465f, 88.689f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SMEED_HOME_1
SAY_SMEED_HOME_2
SAY_SMEED_HOME_3
QUEST_KODO
NPC_SMEED
NPC_AGED_KODO
NPC_DYING_KODO
NPC_ANCIENT_KODO
NPC_TAMED_KODO
SPELL_KODO_KOMBO_ITEM
SPELL_KODO_KOMBO_PLAYER_BUFF
SPELL_KODO_KOMBO_DESPAWN_BUFF
SPELL_KODO_KOMBO_GOSSIP
SPELL_KODO_KOMBOBULATOR
SPELL_KODO_DESPAWN
Definition at line 38 of file desolace.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_RETURN_TO_VAHLARRIEL
Definition at line 184 of file desolace.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_GET_ME_OUT_OF_HERE
GO_MELIZZAS_CAGE
SAY_MELIZZA_START
SAY_MELIZZA_FINISH
SAY_MELIZZA_1
SAY_MELIZZA_2
SAY_MELIZZA_3
SAY_HORNIZZ_1
SAY_HORNIZZ_2
NPC_MARAUDINE_MARAUDER
NPC_MARAUDINE_BONEPAW
NPC_MARAUDINE_WRANGLER
NPC_MELIZZA
POINT_ID_QUEST_COMPLETE
POINT_ID_EVENT_COMPLETE
MAX_MARAUDERS
MAX_WRANGLERS
Definition at line 237 of file desolace.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_CORK_GIZELTON
NPC_RIGGER_GIZELTON
NPC_VENDOR_TRON
NPC_SUPER_SELLER
QUEST_BODYGUARD_TO_HIRE
QUEST_GIZELTON_CARAVAN
WAYPOINT_PATH_ID
PATH_ID_CORK_GIZELTON
PATH_ID_RIGGER_GIZELTON
WAYPOINT_PATH_POINT_AFTER_ESCORT_1
WAYPOINT_PATH_POINT_AFTER_ESCORT_2
GIZELTON_TIMER_AFTER_FAIL
Definition at line 422 of file desolace.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CURSE_OF_MAGRAMI
SPELL_GHOST_SPAWN_IN
SPELL_BLUE_AURA
SPELL_GREEN_AURA
SPELL_CHILLING_TOUCH
FACTION_HOSTILE
SAY_EMOTE_1
SAY_EMOTE_2
Definition at line 595 of file desolace.cpp.
Function Documentation
AddSC_desolace()
void AddSC_desolace ()
Definition at line 667 of file desolace.cpp.
References EffectDummyCreature_npc_aged_dying_ancient_kodo(), Script::GetAI, GetAI_npc_aged_dying_ancient_kodo(), GetAI_npc_dalinda_malem(), GetAI_npc_magrami_spectre(), GetAI_npc_melizza_brimbuzzle(), GossipHello_npc_aged_dying_ancient_kodo(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pQuestAcceptNPC, QuestAccept_npc_cork_gizelton(), QuestAccept_npc_dalinda_malem(), QuestAccept_npc_melizza_brimbuzzle(), QuestAccept_npc_rigger_gizelton(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_aged_dying_ancient_kodo()
bool EffectDummyCreature_npc_aged_dying_ancient_kodo (Unit * pCaster, uint32 spellId, SpellEffectIndex effIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 134 of file desolace.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, MotionMaster::GetCurrentMovementGeneratorType(), Object::GetEntry(), Unit::GetMotionMaster(), Unit::HasAura(), MotionMaster::MoveFollow(), MotionMaster::MoveIdle(), NPC_AGED_KODO, NPC_ANCIENT_KODO, NPC_DYING_KODO, NPC_TAMED_KODO, PET_FOLLOW_ANGLE, PET_FOLLOW_DIST, SPELL_KODO_KOMBO_DESPAWN_BUFF, SPELL_KODO_KOMBO_ITEM, SPELL_KODO_KOMBO_PLAYER_BUFF, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, Creature::UpdateEntry(), and WAYPOINT_MOTION_TYPE.
Referenced by AddSC_desolace().
GetAI_npc_aged_dying_ancient_kodo()
UnitAI* GetAI_npc_aged_dying_ancient_kodo (Creature * pCreature)
Definition at line 129 of file desolace.cpp.
Referenced by AddSC_desolace().
GetAI_npc_dalinda_malem()
UnitAI* GetAI_npc_dalinda_malem (Creature * pCreature)
Definition at line 214 of file desolace.cpp.
Referenced by AddSC_desolace().
GetAI_npc_magrami_spectre()
UnitAI* GetAI_npc_magrami_spectre (Creature * pCreature)
Definition at line 662 of file desolace.cpp.
Referenced by AddSC_desolace().
GetAI_npc_melizza_brimbuzzle()
UnitAI* GetAI_npc_melizza_brimbuzzle (Creature * pCreature)
Definition at line 402 of file desolace.cpp.
Referenced by AddSC_desolace().
GossipHello_npc_aged_dying_ancient_kodo()
bool GossipHello_npc_aged_dying_ancient_kodo (Player * pPlayer, Creature * pCreature)
Definition at line 164 of file desolace.cpp.
References Creature::ForcedDespawn(), Player::GetDefaultGossipMenuForSource(), Object::GetEntry(), Object::GetObjectGuid(), Unit::HasAura(), Player::PrepareGossipMenu(), Unit::RemoveAurasDueToSpell(), Player::SendPreparedGossip(), SPELL_KODO_KOMBO_DESPAWN_BUFF, SPELL_KODO_KOMBO_PLAYER_BUFF, and Player::TalkedToCreature().
Referenced by AddSC_desolace().
QuestAccept_npc_cork_gizelton()
bool QuestAccept_npc_cork_gizelton (Player * player, Creature * creature, const Quest * quest)
Definition at line 561 of file desolace.cpp.
References Creature::AI(), Quest::GetQuestId(), PATH_ID_CORK_GIZELTON, and QUEST_BODYGUARD_TO_HIRE.
Referenced by AddSC_desolace().
QuestAccept_npc_dalinda_malem()
bool QuestAccept_npc_dalinda_malem (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 219 of file desolace.cpp.
References Creature::AI(), FACTION_ESCORT_A_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_RETURN_TO_VAHLARRIEL, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_desolace().
QuestAccept_npc_melizza_brimbuzzle()
bool QuestAccept_npc_melizza_brimbuzzle (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 407 of file desolace.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_GET_ME_OUT_OF_HERE.
Referenced by AddSC_desolace().
QuestAccept_npc_rigger_gizelton()
bool QuestAccept_npc_rigger_gizelton (Player * player, Creature * creature, const Quest * quest)
Definition at line 582 of file desolace.cpp.
References GetClosestCreatureWithEntry(), Quest::GetQuestId(), NPC_CORK_GIZELTON, and QUEST_GIZELTON_CARAVAN.
Referenced by AddSC_desolace().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {POINT_ID_QUEST_COMPLETE,   0,              1000},
    {QUEST_GET_ME_OUT_OF_HERE,  NPC_MELIZZA,    0},
    {POINT_ID_EVENT_COMPLETE,   0,              2000},
    {SAY_MELIZZA_1,             NPC_MELIZZA,    4000},
    {SAY_MELIZZA_2,             NPC_MELIZZA,    5000},
    {SAY_MELIZZA_3,             NPC_MELIZZA,    4000},
    {NPC_MELIZZA,               0,              6000},
    {SAY_HORNIZZ_1,             NPC_HORNIZZ,    10000},
    {SAY_HORNIZZ_2,             NPC_HORNIZZ,    0},
    {0, 0, 0},
}
Definition at line 266 of file desolace.cpp.
aMarauderSpawn
const SummonLocation aMarauderSpawn[] static
Initial value:
=
{
    { -1291.492f, 2644.650f, 111.556f},
    { -1306.730f, 2675.163f, 111.561f},
}
Definition at line 285 of file desolace.cpp.
Referenced by npc_melizza_brimbuzzleAI::WaypointReached().
wranglerSpawn
const SummonLocation wranglerSpawn = { -1393.194f, 2429.465f, 88.689f } static
Definition at line 291 of file desolace.cpp.
Referenced by npc_melizza_brimbuzzleAI::WaypointReached().