CMaNGOS_WoTLK: dire_maul.cpp File Reference
dire_maul.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "dire_maul.h"
Data Structures
struct npc_warlock_mount_ritualAI
struct DreadsteedQuestObjects
struct RitualCandleAura
Enumerations
enum { EVENT_ID_SUMMON_JEEVEE = 8420 , EVENT_ID_SUMMON_DREADSTEED = 8428 }
enum { SUMMON_WAVES_RELAY_SCRIPT_START_ID = 1450100 }
Functions
bool ProcessEventId_event_spells_warlock_dreadsteed (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
void AddSC_dire_maul ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EVENT_ID_SUMMON_JEEVEE
EVENT_ID_SUMMON_DREADSTEED
Definition at line 37 of file dire_maul.cpp.
anonymous enum
anonymous enum
Enumerator
SUMMON_WAVES_RELAY_SCRIPT_START_ID
Definition at line 88 of file dire_maul.cpp.
Function Documentation
AddSC_dire_maul()
void AddSC_dire_maul ()
Definition at line 236 of file dire_maul.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spells_warlock_dreadsteed(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_spells_warlock_dreadsteed()
bool ProcessEventId_event_spells_warlock_dreadsteed (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 43 of file dire_maul.cpp.
References DONE, EVENT_ID_SUMMON_DREADSTEED, EVENT_ID_SUMMON_JEEVEE, FAIL, Object::GetTypeId(), IN_PROGRESS, NOT_STARTED, NPC_JEEVEE, NPC_WARLOCK_DUMMY_INFERNAL, SPECIAL, TEMPSPAWN_DEAD_DESPAWN, TYPE_DREADSTEED, and TYPEID_PLAYER.
Referenced by AddSC_dire_maul().