CMaNGOS_WoTLK: dragonblight.cpp File Reference
dragonblight.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_destructive_wardAI
struct TaunkaFaceMeSpellScript
struct CaptureJormungarSpawnSpellScript
struct ScrapeCorrosiveSpit
struct ContainerOfRatsSpellScript
struct DropOffVillager
struct ArmyOfTheDead
struct CorrosiveSpit
struct go_scrying_orb
struct TwistingBlade
struct spell_ley_line_focus_item
struct spell_ley_line_focus_item_trigger
struct LiquidFireOfElune
struct HourglassOfEternity
struct RescueVillager
struct DropOffGnome
Enumerations
enum {
SAY_WARD_POWERUP = -1000664 , SAY_WARD_CHARGED = -1000665 , SPELL_DESTRUCTIVE_PULSE = 48733 , SPELL_DESTRUCTIVE_BARRAGE = 48734 ,
SPELL_DESTRUCTIVE_WARD_POWERUP = 48735 , SPELL_SUMMON_SMOLDERING_SKELETON = 48715 , SPELL_SUMMON_SMOLDERING_CONSTRUCT = 48718 , SPELL_DESTRUCTIVE_WARD_KILL_CREDIT = 52409 ,
MAX_STACK = 1
}
enum { SPELL_FEIGN_DEATH_PERMANENT = 31261 , ITEM_ID_SAMPLE_ROCKFLESH = 36765 , NPC_CRYSTALLINE_GIANT = 26809 }
enum { SPELL_UNDIGESTIBLE = 47430 }
enum {
SPELL_LIQUID_FIRE = 46770 , SPELL_LIQUID_FIRE_AURA = 47972 , NPC_ELK = 26616 , NPC_GRIZZLY = 26643 ,
NPC_ELK_BUNNY = 27111 , NPC_GRIZZLY_BUNNY = 27112
}
Functions
UnitAI * GetAI_npc_destructive_ward (Creature *pCreature)
bool NpcSpellClick_npc_crystalline_ice_giant (Player *pPlayer, Creature *pClickedCreature, uint32)
void AddSC_dragonblight ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_WARD_POWERUP
SAY_WARD_CHARGED
SPELL_DESTRUCTIVE_PULSE
SPELL_DESTRUCTIVE_BARRAGE
SPELL_DESTRUCTIVE_WARD_POWERUP
SPELL_SUMMON_SMOLDERING_SKELETON
SPELL_SUMMON_SMOLDERING_CONSTRUCT
SPELL_DESTRUCTIVE_WARD_KILL_CREDIT
MAX_STACK
Definition at line 39 of file dragonblight.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FEIGN_DEATH_PERMANENT
ITEM_ID_SAMPLE_ROCKFLESH
NPC_CRYSTALLINE_GIANT
Definition at line 177 of file dragonblight.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_UNDIGESTIBLE
Definition at line 298 of file dragonblight.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_LIQUID_FIRE
SPELL_LIQUID_FIRE_AURA
NPC_ELK
NPC_GRIZZLY
NPC_ELK_BUNNY
NPC_GRIZZLY_BUNNY
Definition at line 376 of file dragonblight.cpp.
Function Documentation
AddSC_dragonblight()
void AddSC_dragonblight ()
Definition at line 465 of file dragonblight.cpp.
References Script::GetAI, GetAI_npc_destructive_ward(), Script::GetGameObjectAI, Script::Name, NpcSpellClick_npc_crystalline_ice_giant(), Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_destructive_ward()
UnitAI* GetAI_npc_destructive_ward (Creature * pCreature)
Definition at line 168 of file dragonblight.cpp.
Referenced by AddSC_dragonblight().
NpcSpellClick_npc_crystalline_ice_giant()
bool NpcSpellClick_npc_crystalline_ice_giant (Player * pPlayer, Creature * pClickedCreature, uint32)
Definition at line 184 of file dragonblight.cpp.
References Creature::ForcedDespawn(), Object::GetEntry(), Unit::HasAura(), ITEM_ID_SAMPLE_ROCKFLESH, NPC_CRYSTALLINE_GIANT, Player::SendNewItem(), SPELL_FEIGN_DEATH_PERMANENT, and Player::StoreNewItemInInventorySlot().
Referenced by AddSC_dragonblight().