CMaNGOS_WoTLK: durotar.cpp File Reference
durotar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_lazy_peonAI
Enumerations
enum {
SAY_PEON_AWOKEN = -1000795 , SOUND_PEON_WORK = 6197 , SOUND_PEON_AWAKE_1 = 6292 , SOUND_PEON_AWAKE_2 = 6294 ,
SPELL_PEON_SLEEP = 17743 , SPELL_AWAKEN_PEON = 19938 , NPC_SLEEPING_PEON = 10556 , GO_LUMBERPILE = 175784
}
Functions
UnitAI * GetAI_npc_lazy_peon (Creature *pCreature)
bool EffectDummyCreature_lazy_peon_spell (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_durotar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PEON_AWOKEN
SOUND_PEON_WORK
SOUND_PEON_AWAKE_1
SOUND_PEON_AWAKE_2
SPELL_PEON_SLEEP
SPELL_AWAKEN_PEON
NPC_SLEEPING_PEON
GO_LUMBERPILE
Definition at line 34 of file durotar.cpp.
Function Documentation
AddSC_durotar()
void AddSC_durotar ()
Definition at line 246 of file durotar.cpp.
References EffectDummyCreature_lazy_peon_spell(), Script::GetAI, GetAI_npc_lazy_peon(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_lazy_peon_spell()
bool EffectDummyCreature_lazy_peon_spell (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 231 of file durotar.cpp.
References Creature::AI(), EFFECT_INDEX_0, and SPELL_AWAKEN_PEON.
Referenced by AddSC_durotar().
GetAI_npc_lazy_peon()
UnitAI* GetAI_npc_lazy_peon (Creature * pCreature)
Definition at line 226 of file durotar.cpp.
Referenced by AddSC_durotar().