CMaNGOS_WoTLK: dustwallow_marsh.cpp File Reference
dustwallow_marsh.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Entities/TemporarySpawn.h"
#include "World/WorldStateDefines.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include <unordered_map>
Data Structures
struct mobs_risen_husk_spiritAI
struct npc_restless_apparitionAI
struct npc_morokkAI
struct npc_ogronAI
struct OutroSpawnLocation
struct npc_private_hendelAI
struct npc_stinky_ignatzAI
struct mob_invis_firework_helper
struct boss_tethyrAI
struct npc_major_mills
struct npc_smolderwing
struct npc_theramore_spar_controller
Enumerations
enum {
QUEST_WHATS_HAUNTING_WITCH_HILL = 11180 , SPELL_SUMMON_RESTLESS_APPARITION = 42511 , SPELL_CONSUME_FLESH = 37933 , SPELL_INTANGIBLE_PRESENCE = 43127 ,
NPC_RISEN_HUSK = 23555 , NPC_RISEN_SPIRIT = 23554
}
enum {
SAY_RAND_1 = -1000543 , SAY_RAND_2 = -1000544 , SAY_RAND_3 = -1000545 , SAY_RAND_4 = -1000546 ,
SAY_RAND_5 = -1000547 , SAY_RAND_6 = -1000548 , SAY_RAND_7 = -1000549 , SAY_RAND_8 = -1000550
}
enum {
SAY_MOR_CHALLENGE = -1000499 , SAY_MOR_SCARED = -1000500 , NPC_MOROKK = 4500 , QUEST_CHALLENGE_MOROKK = 1173 ,
FACTION_MOR_HOSTILE = 168 , FACTION_MOR_RUNNING = 35 , FACTION_MOR_SPAWN = 29
}
enum {
SAY_OGR_START = -1000452 , SAY_OGR_SPOT = -1000453 , SAY_OGR_RET_WHAT = -1000454 , SAY_OGR_RET_SWEAR = -1000455 ,
SAY_OGR_REPLY_RET = -1000456 , SAY_OGR_RET_TAKEN = -1000457 , SAY_OGR_TELL_FIRE = -1000458 , SAY_OGR_RET_NOCLOSER = -1000459 ,
SAY_OGR_RET_NOFIRE = -1000460 , SAY_OGR_RET_HEAR = -1000461 , SAY_OGR_CAL_FOUND = -1000462 , SAY_OGR_CAL_MERCY = -1000463 ,
SAY_OGR_HALL_GLAD = -1000464 , EMOTE_OGR_RET_ARROW = -1000465 , SAY_OGR_RET_ARROW = -1000466 , SAY_OGR_CAL_CLEANUP = -1000467 ,
SAY_OGR_NODIE = -1000468 , SAY_OGR_SURVIVE = -1000469 , SAY_OGR_RET_LUCKY = -1000470 , SAY_OGR_THANKS = -1000471 ,
QUEST_QUESTIONING = 1273 , FACTION_GENERIC_FRIENDLY = 35 , FACTION_THER_HOSTILE = 151 , NPC_REETHE = 4980 ,
NPC_CALDWELL = 5046 , NPC_HALLAN = 5045 , NPC_SKIRMISHER = 5044 , SPELL_FAKE_SHOT = 7105 ,
PHASE_INTRO = 0 , PHASE_GUESTS = 1 , PHASE_FIGHT = 2 , PHASE_COMPLETE = 3
}
enum {
EMOTE_SURRENDER = -1000415 , QUEST_MISSING_DIPLO_PT16 = 1324 , FACTION_HOSTILE = 168 , NPC_SENTRY = 5184 ,
NPC_JAINA = 4968 , NPC_TERVOSH = 4967 , NPC_PAINED = 4965 , SPELL_TELEPORT_VISUAL = 12980 ,
SPELL_TELEPORT = 7079
}
enum {
QUEST_ID_STINKYS_ESCAPE_ALLIANCE = 1222 , QUEST_ID_STINKYS_ESCAPE_HORDE = 1270 , SAY_STINKY_BEGIN = -1000958 , SAY_STINKY_FIRST_STOP = -1000959 ,
SAY_STINKY_SECOND_STOP = -1001141 , SAY_STINKY_THIRD_STOP_1 = -1001142 , SAY_STINKY_THIRD_STOP_2 = -1001143 , SAY_STINKY_THIRD_STOP_3 = -1001144 ,
SAY_STINKY_PLANT_GATHERED = -1001145 , SAY_STINKY_END = -1000962 , SAY_STINKY_END_EMOTE = -1010032 , SAY_STINKY_AGGRO_1 = -1000960 ,
SAY_STINKY_AGGRO_2 = -1000961 , SAY_STINKY_AGGRO_3 = -1001146 , SAY_STINKY_AGGRO_4 = -1001147 , GO_BOGBEAN_PLANT = 20939
}
enum { QUEST_NATS_BARGAIN = 11209 , SPELL_FISH_PASTE = 42644 , NPC_LURKING_SHARK = 23928 }
enum { SPELL_BLUE_THERAMORE_ROCKET = 42813 , SPELL_YELLOW_THERAMORE_ROCKET = 42815 , SPELL_PURPLE_THERAMORE_ROCKET = 42816 }
enum {
SPELL_WATER_BOLT = 42574 , SPELL_SPOUT_LEFT = 42581 , SPELL_SPOUT_RIGHT = 42582 , SPELL_CANNON_BLAST = 42578 ,
SPELL_CANNON_BLAST_DMG = 42576 , NPC_TETHYR = 23899 , NPC_THERAMORE_MARKSMAN = 23900 , NPC_THERAMORE_CANNON = 23907 ,
NPC_FIREWORK_HELPER = 24025 , GO_COVE_CANNON = 186432 , QUEST_TAKE_DOWN_TETHYR = 11198 , PHASE_TETHYR_INTRO = 0 ,
PHASE_TETHYR_NORMAL = 1 , PHASE_TETHYR_SPOUT = 2 , PHASE_TETHYR_MOVING = 3
}
enum { DBSCRIPT_RELAY_TAKE_DOWN_TETHYR = 10161 }
enum SentryPoint { QUEST_MISSING_DIPLO_PT14 = 1265 , SPELL_TELEPORT_VISUAL_2 = 799 , NPC_SENTRY_POINT_GUARD = 5085 }
enum {
DO_NOTHING = 111111 , SAY_1 = -1000343 , SAY_2 = -1000344 , NPC_SMOLDERWING = 23789 ,
SPELL_SMOLDERWING_FIRE_BREATH = 42433 , GO_STONEMAUL_BANNER = 186335 , MAP_ID_KALIMDOR = 1 , ZONE_ID_ONY_LAIR = 2159
}
enum {
NPC_GUARD_NARRISHA = 5093 , NPC_GUARD_KAHIL = 5091 , NPC_GUARD_EDWARD = 4922 , NPC_GUARD_TARK = 5094 ,
NPC_GUARD_LANA = 5092 , NPC_GUARD_JARAD = 4923 , NPC_MEDIC_HELAINA = 5200 , NPC_MEDIC_TAMBERLYN = 5199 ,
NPC_MASTER_SZIGETI = 5090 , NPC_MASTER_CRITON = 4924 , NPC_BLUE_CAPTAIN = 5096 , NPC_RED_CAPTAIN = 5095 ,
SPELL_FIRST_AID = 7162 , BLUE_TEAM = 1621 , RED_TEAM = 1622 , FACTION_THERAMORE_FRIENDLY = 151 ,
SAY_RED_WINNER = 1794 , SAY_BLUE_WINNER = 1795 , SAY_RED_WINNER_OVERALL = 1773 , SAY_BLUE_WINNER_OVERALL = 1774 ,
SAY_BACK_TO_CORNERS = 1636 , SAY_FOR_THE_RED = 1778 , SAY_FOR_THE_BLUE = 1777 , SAY_FIRST_COMBATANTS = 1771 ,
SAY_FIGHT_INTRO = 1643 , SAY_FIGHT_START = 1641 , SAY_EDWARD_LOSS = 1760 , SAY_KAHIL_LOSS = 1762 ,
SAY_NARRISHA_LOSS = 1763 , SAY_JARAD_LOSS = 1766 , SAY_LANA_LOSS = 1767 , SAY_TARK_LOSS = 1768 ,
SAY_RED_MOTIVATION_WIN = 1769 , SAY_RED_MOTIVATION_LOSS = 1770 , SAY_BLUE_MOTIVATION_LOSS = 1765 , SAY_BLUE_MOTIVATION_WIN = 1764 ,
SAY_RED_FIRST = 1776 , SAY_BLUE_FIRST = 1775
}
enum CombatantActions {
COMBATANT_CHECK_HP , COMBATANT_BLUE_WIN , COMBATANT_RED_WIN , COMBATANT_START_POSITION ,
COMBATANT_START_SPAR , COMBATANT_GET_ALL , COMBATANT_SALUTE , COMBATANT_SWITCH ,
COMBATANT_SEPARATE , COMBATANT_INTRO , COMBATANT_MOTIVATION , COMBATANT_ACTION_MAX
}
Functions
UnitAI * GetAI_mobs_risen_husk_spirit (Creature *pCreature)
UnitAI * GetAI_npc_restless_apparition (Creature *pCreature)
UnitAI * GetAI_npc_morokk (Creature *pCreature)
bool QuestAccept_npc_morokk (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool QuestAccept_npc_ogron (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_ogron (Creature *pCreature)
bool QuestAccept_npc_private_hendel (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_private_hendel (Creature *pCreature)
UnitAI * GetAI_npc_stinky_ignatz (Creature *pCreature)
bool QuestAccept_npc_stinky_ignatz (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool AreaTrigger_at_nats_landing (Player *pPlayer, const AreaTriggerEntry *)
UnitAI * GetAI_mob_invis_firework_helper (Creature *pCreature)
UnitAI * GetAI_npc_major_mills (Creature *pCreature)
bool QuestAccept_npc_major_mills (Player *player, Creature *creature, const Quest *quest)
bool AreaTrigger_at_sentry_point (Player *pPlayer, const AreaTriggerEntry *)
UnitAI * GetAI_npc_smolderwing (Creature *pCreature)
static std::unordered_map< uint32, const Position > startingPositions ({ {BLUE_TEAM, {-3643.574707f, -4505.717773f, 9.462863f, 3.855592f}}, {RED_TEAM, {-3652.405273f, -4514.126953f, 9.462863f, 0.717925f}} })
void AddSC_dustwallow_marsh ()
Variables
static float m_afSpawn [] = { -3383.501953f, -3203.383301f, 36.149f}
static float m_afMoveTo [] = { -3371.414795f, -3212.179932f, 34.210f}
const OutroSpawnLocation lOutroSpawns []
const float fSentryFleePoint [] {-2917.56f, -3329.90f, 30.37f}
int32 fireworkMidPoint = -4650
static const DialogueEntry SmolderDialogue []
static const uint32 theramore_blue_team [] = {NPC_GUARD_EDWARD, NPC_GUARD_KAHIL, NPC_GUARD_NARRISHA}
static const uint32 theramore_red_team [] = {NPC_GUARD_JARAD, NPC_GUARD_LANA, NPC_GUARD_TARK}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_WHATS_HAUNTING_WITCH_HILL
SPELL_SUMMON_RESTLESS_APPARITION
SPELL_CONSUME_FLESH
SPELL_INTANGIBLE_PRESENCE
NPC_RISEN_HUSK
NPC_RISEN_SPIRIT
Definition at line 47 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_RAND_1
SAY_RAND_2
SAY_RAND_3
SAY_RAND_4
SAY_RAND_5
SAY_RAND_6
SAY_RAND_7
SAY_RAND_8
Definition at line 133 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MOR_CHALLENGE
SAY_MOR_SCARED
NPC_MOROKK
QUEST_CHALLENGE_MOROKK
FACTION_MOR_HOSTILE
FACTION_MOR_RUNNING
FACTION_MOR_SPAWN
Definition at line 191 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_OGR_START
SAY_OGR_SPOT
SAY_OGR_RET_WHAT
SAY_OGR_RET_SWEAR
SAY_OGR_REPLY_RET
SAY_OGR_RET_TAKEN
SAY_OGR_TELL_FIRE
SAY_OGR_RET_NOCLOSER
SAY_OGR_RET_NOFIRE
SAY_OGR_RET_HEAR
SAY_OGR_CAL_FOUND
SAY_OGR_CAL_MERCY
SAY_OGR_HALL_GLAD
EMOTE_OGR_RET_ARROW
SAY_OGR_RET_ARROW
SAY_OGR_CAL_CLEANUP
SAY_OGR_NODIE
SAY_OGR_SURVIVE
SAY_OGR_RET_LUCKY
SAY_OGR_THANKS
QUEST_QUESTIONING
FACTION_GENERIC_FRIENDLY
FACTION_THER_HOSTILE
NPC_REETHE
NPC_CALDWELL
NPC_HALLAN
NPC_SKIRMISHER
SPELL_FAKE_SHOT
PHASE_INTRO
PHASE_GUESTS
PHASE_FIGHT
PHASE_COMPLETE
Definition at line 315 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_SURRENDER
QUEST_MISSING_DIPLO_PT16
FACTION_HOSTILE
NPC_SENTRY
NPC_JAINA
NPC_TERVOSH
NPC_PAINED
SPELL_TELEPORT_VISUAL
SPELL_TELEPORT
Definition at line 619 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ID_STINKYS_ESCAPE_ALLIANCE
QUEST_ID_STINKYS_ESCAPE_HORDE
SAY_STINKY_BEGIN
SAY_STINKY_FIRST_STOP
SAY_STINKY_SECOND_STOP
SAY_STINKY_THIRD_STOP_1
SAY_STINKY_THIRD_STOP_2
SAY_STINKY_THIRD_STOP_3
SAY_STINKY_PLANT_GATHERED
SAY_STINKY_END
SAY_STINKY_END_EMOTE
SAY_STINKY_AGGRO_1
SAY_STINKY_AGGRO_2
SAY_STINKY_AGGRO_3
SAY_STINKY_AGGRO_4
GO_BOGBEAN_PLANT
Definition at line 786 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_NATS_BARGAIN
SPELL_FISH_PASTE
NPC_LURKING_SHARK
Definition at line 914 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BLUE_THERAMORE_ROCKET
SPELL_YELLOW_THERAMORE_ROCKET
SPELL_PURPLE_THERAMORE_ROCKET
Definition at line 940 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_WATER_BOLT
SPELL_SPOUT_LEFT
SPELL_SPOUT_RIGHT
SPELL_CANNON_BLAST
SPELL_CANNON_BLAST_DMG
NPC_TETHYR
NPC_THERAMORE_MARKSMAN
NPC_THERAMORE_CANNON
NPC_FIREWORK_HELPER
GO_COVE_CANNON
QUEST_TAKE_DOWN_TETHYR
PHASE_TETHYR_INTRO
PHASE_TETHYR_NORMAL
PHASE_TETHYR_SPOUT
PHASE_TETHYR_MOVING
Definition at line 1017 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
DBSCRIPT_RELAY_TAKE_DOWN_TETHYR
Definition at line 1298 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
DO_NOTHING
SAY_1
SAY_2
NPC_SMOLDERWING
SPELL_SMOLDERWING_FIRE_BREATH
GO_STONEMAUL_BANNER
MAP_ID_KALIMDOR
ZONE_ID_ONY_LAIR
Definition at line 1378 of file dustwallow_marsh.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_GUARD_NARRISHA
NPC_GUARD_KAHIL
NPC_GUARD_EDWARD
NPC_GUARD_TARK
NPC_GUARD_LANA
NPC_GUARD_JARAD
NPC_MEDIC_HELAINA
NPC_MEDIC_TAMBERLYN
NPC_MASTER_SZIGETI
NPC_MASTER_CRITON
NPC_BLUE_CAPTAIN
NPC_RED_CAPTAIN
SPELL_FIRST_AID
BLUE_TEAM
RED_TEAM
FACTION_THERAMORE_FRIENDLY
SAY_RED_WINNER
SAY_BLUE_WINNER
SAY_RED_WINNER_OVERALL
SAY_BLUE_WINNER_OVERALL
SAY_BACK_TO_CORNERS
SAY_FOR_THE_RED
SAY_FOR_THE_BLUE
SAY_FIRST_COMBATANTS
SAY_FIGHT_INTRO
SAY_FIGHT_START
SAY_EDWARD_LOSS
SAY_KAHIL_LOSS
SAY_NARRISHA_LOSS
SAY_JARAD_LOSS
SAY_LANA_LOSS
SAY_TARK_LOSS
SAY_RED_MOTIVATION_WIN
SAY_RED_MOTIVATION_LOSS
SAY_BLUE_MOTIVATION_LOSS
SAY_BLUE_MOTIVATION_WIN
SAY_RED_FIRST
SAY_BLUE_FIRST
Definition at line 1502 of file dustwallow_marsh.cpp.
CombatantActions
enum CombatantActions
Enumerator
COMBATANT_CHECK_HP
COMBATANT_BLUE_WIN
COMBATANT_RED_WIN
COMBATANT_START_POSITION
COMBATANT_START_SPAR
COMBATANT_GET_ALL
COMBATANT_SALUTE
COMBATANT_SWITCH
COMBATANT_SEPARATE
COMBATANT_INTRO
COMBATANT_MOTIVATION
COMBATANT_ACTION_MAX
Definition at line 1559 of file dustwallow_marsh.cpp.
SentryPoint
enum SentryPoint
Enumerator
QUEST_MISSING_DIPLO_PT14
SPELL_TELEPORT_VISUAL_2
NPC_SENTRY_POINT_GUARD
Definition at line 1344 of file dustwallow_marsh.cpp.
Function Documentation
AddSC_dustwallow_marsh()
void AddSC_dustwallow_marsh ()
Definition at line 1926 of file dustwallow_marsh.cpp.
References AreaTrigger_at_nats_landing(), AreaTrigger_at_sentry_point(), Script::GetAI, GetAI_mob_invis_firework_helper(), GetAI_mobs_risen_husk_spirit(), GetAI_npc_major_mills(), GetAI_npc_morokk(), GetAI_npc_ogron(), GetAI_npc_private_hendel(), GetAI_npc_restless_apparition(), GetAI_npc_smolderwing(), GetAI_npc_stinky_ignatz(), Script::Name, Script::pAreaTrigger, Script::pQuestAcceptNPC, QuestAccept_npc_major_mills(), QuestAccept_npc_morokk(), QuestAccept_npc_ogron(), QuestAccept_npc_private_hendel(), QuestAccept_npc_stinky_ignatz(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_nats_landing()
bool AreaTrigger_at_nats_landing (Player * pPlayer, const AreaTriggerEntry *)
Definition at line 921 of file dustwallow_marsh.cpp.
References Creature::AI(), UnitAI::AttackStart(), GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::HasAura(), NPC_LURKING_SHARK, QUEST_NATS_BARGAIN, QUEST_STATUS_INCOMPLETE, SPELL_FISH_PASTE, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_DESPAWN.
Referenced by AddSC_dustwallow_marsh().
AreaTrigger_at_sentry_point()
bool AreaTrigger_at_sentry_point (Player * pPlayer, const AreaTriggerEntry *)
Definition at line 1351 of file dustwallow_marsh.cpp.
References EMOTE_ONESHOT_SALUTE, GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::IsDead(), NPC_SENTRY_POINT_GUARD, NPC_TERVOSH, QUEST_MISSING_DIPLO_PT14, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, SPELL_TELEPORT_VISUAL_2, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_dustwallow_marsh().
GetAI_mob_invis_firework_helper()
UnitAI* GetAI_mob_invis_firework_helper (Creature * pCreature)
Definition at line 1008 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_mobs_risen_husk_spirit()
UnitAI* GetAI_mobs_risen_husk_spirit (Creature * pCreature)
Definition at line 124 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_major_mills()
UnitAI* GetAI_npc_major_mills (Creature * pCreature)
Definition at line 1324 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_morokk()
UnitAI* GetAI_npc_morokk (Creature * pCreature)
Definition at line 293 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_ogron()
UnitAI* GetAI_npc_ogron (Creature * pCreature)
Definition at line 610 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_private_hendel()
UnitAI* GetAI_npc_private_hendel (Creature * pCreature)
Definition at line 776 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_restless_apparition()
UnitAI* GetAI_npc_restless_apparition (Creature * pCreature)
Definition at line 182 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_smolderwing()
UnitAI* GetAI_npc_smolderwing (Creature * pCreature)
Definition at line 1493 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
GetAI_npc_stinky_ignatz()
UnitAI* GetAI_npc_stinky_ignatz (Creature * pCreature)
Definition at line 898 of file dustwallow_marsh.cpp.
Referenced by AddSC_dustwallow_marsh().
QuestAccept_npc_major_mills()
bool QuestAccept_npc_major_mills (Player * player, Creature * creature, const Quest * quest)
Definition at line 1329 of file dustwallow_marsh.cpp.
References Creature::AI(), DBSCRIPT_RELAY_TAKE_DOWN_TETHYR, InstanceData::GetData(), Map::GetInstanceData(), WorldObject::GetMap(), Object::GetObjectGuid(), Quest::GetQuestId(), NOT_STARTED, QUEST_TAKE_DOWN_TETHYR, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), and TYPE_TETHYR.
Referenced by AddSC_dustwallow_marsh().
QuestAccept_npc_morokk()
bool QuestAccept_npc_morokk (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 298 of file dustwallow_marsh.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_CHALLENGE_MOROKK.
Referenced by AddSC_dustwallow_marsh().
QuestAccept_npc_ogron()
bool QuestAccept_npc_ogron (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 595 of file dustwallow_marsh.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_PASSIVE, Quest::GetQuestId(), QUEST_QUESTIONING, SAY_OGR_START, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_dustwallow_marsh().
QuestAccept_npc_private_hendel()
bool QuestAccept_npc_private_hendel (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 751 of file dustwallow_marsh.cpp.
References Creature::AI(), UnitAI::AttackStart(), FACTION_HOSTILE, GetCreatureListWithEntryInGrid(), Quest::GetQuestId(), NPC_SENTRY, QUEST_MISSING_DIPLO_PT16, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_COMBAT_STOP, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_dustwallow_marsh().
QuestAccept_npc_stinky_ignatz()
bool QuestAccept_npc_stinky_ignatz (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 903 of file dustwallow_marsh.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_STINKYS_ESCAPE_ALLIANCE, QUEST_ID_STINKYS_ESCAPE_HORDE, and UnitAI::SendAIEvent().
Referenced by AddSC_dustwallow_marsh().
startingPositions()
static std::unordered_map<uint32, const Position> startingPositions ({ {BLUE_TEAM, {-3643.574707f, -4505.717773f, 9.462863f, 3.855592f}}, {RED_TEAM, {-3652.405273f, -4514.126953f, 9.462863f, 0.717925f}} }) static
References BLUE_TEAM, and RED_TEAM.
Referenced by npc_theramore_spar_controller::CombatantSeparate(), npc_theramore_spar_controller::MoveIntoPosition(), and npc_theramore_spar_controller::SwitchMembers().
Variable Documentation
fireworkMidPoint
int32 fireworkMidPoint = -4650
Definition at line 947 of file dustwallow_marsh.cpp.
Referenced by mob_invis_firework_helper::GroupDeterminerFunc(), and boss_tethyrAI::SpellHit().
fSentryFleePoint
const float fSentryFleePoint[] {-2917.56f, -3329.90f, 30.37f}
Definition at line 661 of file dustwallow_marsh.cpp.
Referenced by npc_private_hendelAI::DamageTaken().
lOutroSpawns
const OutroSpawnLocation lOutroSpawns[]
Initial value:
=
{
    {
        -2857.604492f, -3354.784912f, 35.369640f, 3.16604f,
        -2881.546631f, -3346.477539f, 34.143719f,
        NPC_TERVOSH
    },
    {
        -2858.120117f, -3358.469971f, 36.086300f, 3.16604f,
        -2879.697998f, -3347.789063f, 34.772892f,
        NPC_JAINA
    },
    {
        -2857.379883f, -3351.370117f, 34.178001f, 3.16604f,
        -2879.959961f, -3344.469971f, 34.670502f,
        NPC_PAINED
    }
}
Definition at line 642 of file dustwallow_marsh.cpp.
Referenced by npc_private_hendelAI::DamageTaken().
m_afMoveTo
float m_afMoveTo[] = { -3371.414795f, -3212.179932f, 34.210f} static
Definition at line 357 of file dustwallow_marsh.cpp.
Referenced by npc_ogronAI::JustSummoned().
m_afSpawn
float m_afSpawn[] = { -3383.501953f, -3203.383301f, 36.149f} static
Definition at line 356 of file dustwallow_marsh.cpp.
Referenced by npc_ogronAI::UpdateEscortAI().
SmolderDialogue
const DialogueEntry SmolderDialogue[] static
Initial value:
=
{
    {DO_NOTHING,                    0,               2000},
    {SAY_1,                         NPC_SMOLDERWING, 6500},
    {SAY_2,                         NPC_SMOLDERWING, 5000},
    {SPELL_SMOLDERWING_FIRE_BREATH, 0,               4000},
    {GO_STONEMAUL_BANNER,           0,               0},
    {0, 0, 0 },
}
Definition at line 1395 of file dustwallow_marsh.cpp.
theramore_blue_team
const uint32 theramore_blue_team[] = {NPC_GUARD_EDWARD, NPC_GUARD_KAHIL, NPC_GUARD_NARRISHA} static
Definition at line 1580 of file dustwallow_marsh.cpp.
Referenced by npc_theramore_spar_controller::GetCombatants(), and npc_theramore_spar_controller::HandleBlueWin().
theramore_red_team
const uint32 theramore_red_team[] = {NPC_GUARD_JARAD, NPC_GUARD_LANA, NPC_GUARD_TARK} static
Definition at line 1581 of file dustwallow_marsh.cpp.
Referenced by npc_theramore_spar_controller::GetCombatants(), and npc_theramore_spar_controller::HandleRedWin().