CMaNGOS_WoTLK: eastern_plaguelands.cpp File Reference
eastern_plaguelands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_eris_havenfireAI
Enumerations
enum {
SAY_PHASE_HEAL = -1000815 , SAY_EVENT_END = -1000816 , SAY_EVENT_FAIL_1 = -1000817 , SAY_EVENT_FAIL_2 = -1000818 ,
SAY_PEASANT_APPEAR_1 = -1000819 , SAY_PEASANT_APPEAR_2 = -1000820 , SAY_PEASANT_APPEAR_3 = -1000821 , SPELL_ENTER_THE_LIGHT_DND = 23107 ,
SPELL_BLESSING_OF_NORDRASSIL = 23108 , NPC_INJURED_PEASANT = 14484 , NPC_PLAGUED_PEASANT = 14485 , NPC_SCOURGE_ARCHER = 14489 ,
NPC_SCOURGE_FOOTSOLDIER = 14486 , NPC_THE_CLEANER = 14503 , QUEST_BALANCE_OF_LIGHT_AND_SHADOW = 7622 , BASE_PEASANTS_PER_WAVE = 11 ,
MAX_KILLED_PEASANT = 15 , MAX_SAVED_PEASANT = 50 , MAX_ARCHERS = 8
}
Functions
UnitAI * GetAI_npc_eris_havenfire (Creature *pCreature)
bool QuestAccept_npc_eris_havenfire (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_eastern_plaguelands ()
Variables
static const float aArcherSpawn [8][4]
static const float aPeasantSpawnLoc [3] = {3360.12f, -3047.79f, 165.26f}
static const float aPeasantMoveLoc [3] = {3335.0f, -2994.04f, 161.14f}
static const int32 aPeasantSpawnYells [3] = {SAY_PEASANT_APPEAR_1, SAY_PEASANT_APPEAR_2, SAY_PEASANT_APPEAR_3}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PHASE_HEAL
SAY_EVENT_END
SAY_EVENT_FAIL_1
SAY_EVENT_FAIL_2
SAY_PEASANT_APPEAR_1
SAY_PEASANT_APPEAR_2
SAY_PEASANT_APPEAR_3
SPELL_ENTER_THE_LIGHT_DND
SPELL_BLESSING_OF_NORDRASSIL
NPC_INJURED_PEASANT
NPC_PLAGUED_PEASANT
NPC_SCOURGE_ARCHER
NPC_SCOURGE_FOOTSOLDIER
NPC_THE_CLEANER
QUEST_BALANCE_OF_LIGHT_AND_SHADOW
BASE_PEASANTS_PER_WAVE
MAX_KILLED_PEASANT
MAX_SAVED_PEASANT
MAX_ARCHERS
Definition at line 34 of file eastern_plaguelands.cpp.
Function Documentation
AddSC_eastern_plaguelands()
void AddSC_eastern_plaguelands ()
Definition at line 354 of file eastern_plaguelands.cpp.
References Script::GetAI, GetAI_npc_eris_havenfire(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_eris_havenfire(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_eris_havenfire()
UnitAI* GetAI_npc_eris_havenfire (Creature * pCreature)
Definition at line 338 of file eastern_plaguelands.cpp.
Referenced by AddSC_eastern_plaguelands().
QuestAccept_npc_eris_havenfire()
bool QuestAccept_npc_eris_havenfire (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 343 of file eastern_plaguelands.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_BALANCE_OF_LIGHT_AND_SHADOW.
Referenced by AddSC_eastern_plaguelands().
Variable Documentation
aArcherSpawn
const float aArcherSpawn[8][4] static
Initial value:
=
{
    {3327.42f, -3021.11f, 170.57f, 6.01f},
    {3335.4f,  -3054.3f,  173.63f, 0.49f},
    {3351.3f,  -3079.08f, 178.67f, 1.15f},
    {3358.93f, -3076.1f,  174.87f, 1.57f},
    {3371.58f, -3069.24f, 175.20f, 1.99f},
    {3369.46f, -3023.11f, 171.83f, 3.69f},
    {3383.25f, -3057.01f, 181.53f, 2.21f},
    {3380.03f, -3062.73f, 181.90f, 2.31f},
}
Definition at line 63 of file eastern_plaguelands.cpp.
Referenced by npc_eris_havenfireAI::DoSummonWave().
aPeasantMoveLoc
const float aPeasantMoveLoc[3] = {3335.0f, -2994.04f, 161.14f} static
Definition at line 76 of file eastern_plaguelands.cpp.
Referenced by npc_eris_havenfireAI::JustSummoned().
aPeasantSpawnLoc
const float aPeasantSpawnLoc[3] = {3360.12f, -3047.79f, 165.26f} static
Definition at line 75 of file eastern_plaguelands.cpp.
Referenced by npc_eris_havenfireAI::DoSummonWave().
aPeasantSpawnYells
const int32 aPeasantSpawnYells[3] = {SAY_PEASANT_APPEAR_1, SAY_PEASANT_APPEAR_2, SAY_PEASANT_APPEAR_3} static
Definition at line 78 of file eastern_plaguelands.cpp.
Referenced by npc_eris_havenfireAI::DoSummonWave().