CMaNGOS_WoTLK: ebon_hold.cpp File Reference
ebon_hold.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "world_map_ebon_hold.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "Entities/TemporarySpawn.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct npc_a_special_surpriseAI
struct npc_death_knight_initiateAI
struct npc_eye_of_acherusAI
struct npc_scarlet_ghoulAI
struct npc_highlord_darion_mograineAI
struct npc_scarlet_courierAI
struct spell_emblazon_runeblade
struct spell_emblazon_runeblade_aura
struct spell_death_knight_initiate_visual
struct spell_siphon_of_acherus_aura
struct spell_siphon_of_acherus
struct spell_siphon_of_acherus_credit
struct spell_recall_eye_of_acherus
struct spell_summon_ghouls_scarlet_crusade
struct spell_ghoulplosion
struct spell_dispel_scarlet_ghoul_credit
struct spell_gift_of_the_harvester
struct go_plague_cauldron
struct spell_devour_humanoid
struct spell_portal_to_capital_city
struct spell_acherus_deathcharger
struct spell_skeletal_gryphon_escape
struct spell_death_gate
struct EyeOfAcherus
Enumerations
enum SpecialSurprise {
SAY_EXEC_START_1 = -1609025 , SAY_EXEC_START_2 = -1609026 , SAY_EXEC_START_3 = -1609027 , SAY_EXEC_PROG_1 = -1609028 ,
SAY_EXEC_PROG_2 = -1609029 , SAY_EXEC_PROG_3 = -1609030 , SAY_EXEC_PROG_4 = -1609031 , SAY_EXEC_PROG_5 = -1609032 ,
SAY_EXEC_PROG_6 = -1609033 , SAY_EXEC_PROG_7 = -1609034 , SAY_EXEC_NAME_1 = -1609035 , SAY_EXEC_NAME_2 = -1609036 ,
SAY_EXEC_RECOG_1 = -1609037 , SAY_EXEC_RECOG_2 = -1609038 , SAY_EXEC_RECOG_3 = -1609039 , SAY_EXEC_RECOG_4 = -1609040 ,
SAY_EXEC_RECOG_5 = -1609041 , SAY_EXEC_RECOG_6 = -1609042 , SAY_EXEC_NOREM_1 = -1609043 , SAY_EXEC_NOREM_2 = -1609044 ,
SAY_EXEC_NOREM_3 = -1609045 , SAY_EXEC_NOREM_4 = -1609046 , SAY_EXEC_NOREM_5 = -1609047 , SAY_EXEC_NOREM_6 = -1609048 ,
SAY_EXEC_NOREM_7 = -1609049 , SAY_EXEC_NOREM_8 = -1609050 , SAY_EXEC_NOREM_9 = -1609051 , SAY_EXEC_NOREM_10 = -1609015 ,
SAY_EXEC_THINK_1 = -1609052 , SAY_EXEC_THINK_2 = -1609053 , SAY_EXEC_THINK_3 = -1609054 , SAY_EXEC_THINK_4 = -1609055 ,
SAY_EXEC_THINK_5 = -1609056 , SAY_EXEC_THINK_6 = -1609057 , SAY_EXEC_THINK_7 = -1609058 , SAY_EXEC_THINK_8 = -1609059 ,
SAY_EXEC_THINK_9 = -1609060 , SAY_EXEC_THINK_10 = -1609061 , SAY_EXEC_LISTEN_1 = -1609062 , SAY_EXEC_LISTEN_2 = -1609063 ,
SAY_EXEC_LISTEN_3 = -1609064 , SAY_EXEC_LISTEN_4 = -1609065 , SAY_PLAGUEFIST = -1609066 , SAY_EXEC_TIME_1 = -1609067 ,
SAY_EXEC_TIME_2 = -1609068 , SAY_EXEC_TIME_3 = -1609069 , SAY_EXEC_TIME_4 = -1609070 , SAY_EXEC_TIME_5 = -1609071 ,
SAY_EXEC_TIME_6 = -1609072 , SAY_EXEC_TIME_7 = -1609073 , SAY_EXEC_TIME_8 = -1609074 , SAY_EXEC_TIME_9 = -1609075 ,
SAY_EXEC_TIME_10 = -1609076 , SAY_EXEC_WAITING = -1609077 , EMOTE_DIES = -1609078 , NPC_PRISONER_TAUREN = 29032 ,
NPC_PRISONER_HUMAN = 29061 , NPC_PRISONER_NIGHT_ELF = 29065 , NPC_PRISONER_DWARF = 29067 , NPC_PRISONER_GNOME = 29068 ,
NPC_PRISONER_DRAENEI = 29070 , NPC_PRISONER_UNDEAD = 29071 , NPC_PRISONER_ORC = 29072 , NPC_PRISONER_TROLL = 29073 ,
NPC_PRISONER_BLOOD_ELF = 29074 , NPC_PLAGUEFIST = 29053 , DATA_NPC_STAND = 1 , DATA_NPC_TALK = 2 ,
DATA_NPC_EMOTE = 3 , DATA_NPC_EXCLAMATION = 4 , DATA_NPC_CRY = 5 , DATA_NPC_EXECUTION = 6
}
enum {
SAY_DUEL_A = -1609016 , SAY_DUEL_B = -1609017 , SAY_DUEL_C = -1609018 , SAY_DUEL_D = -1609019 ,
SAY_DUEL_E = -1609020 , SAY_DUEL_F = -1609021 , SAY_DUEL_G = -1609022 , SAY_DUEL_H = -1609023 ,
SAY_DUEL_I = -1609024 , EMOTE_DUEL_BEGIN = -1001137 , EMOTE_DUEL_BEGIN_3 = -1001138 , EMOTE_DUEL_BEGIN_2 = -1001139 ,
EMOTE_DUEL_BEGIN_1 = -1001140 , GOSSIP_ITEM_ACCEPT_DUEL = -3609000 , GOSSIP_TEXT_ID_DUEL = 13433 , SPELL_DUEL = 52996 ,
SPELL_DUEL_TRIGGERED = 52990 , SPELL_DUEL_VICTORY = 52994 , SPELL_DUEL_FLAG = 52991 , SPELL_BLOOD_STRIKE = 52374 ,
SPELL_DEATH_COIL = 52375 , SPELL_ICY_TOUCH = 52372 , SPELL_PLAGUE_STRIKE = 52373 , GO_DUEL_FLAG = 191126 ,
NPC_DEATH_KNIGHT_INITIATE = 28406 , QUEST_DEATH_CHALLENGE = 12733 , FACTION_HOSTILE = 2068
}
enum InitiateActions {
INITIATE_BLOOD_STRIKE , INITIATE_DEATH_COIL , INITIATE_ICY_TOUCH , INITIATE_PLAGUE_STRIKE ,
INITIATE_ACTION_MAX
}
enum {
SPELL_EYE_CONTROL = 51852 , SPELL_EYE_VISUAL = 51892 , SPELL_EYE_FLIGHT = 51890 , SPELL_EYE_FLIGHT_BOOST = 51923 ,
SPELL_RECALL_EYE = 52694 , EMOTE_DESTIANTION = -1609089 , EMOTE_CONTROL = -1609090 , POINT_EYE_START_POS = 0 ,
POINT_EYE_DESTINATION = 1 , START_POINT_PAUSE_TIME = 5000
}
enum {
SAY_GHUL_SPAWN_1 = -1609091 , SAY_GHUL_SPAWN_2 = -1609092 , SAY_GHUL_SPAWN_3 = -1609093 , SAY_GHUL_SPAWN_4 = -1609094 ,
SAY_GHUL_SPAWN_5 = -1609095 , SAY_GOTHIK_THROW_IN_PIT_1 = -1609096 , SAY_GOTHIK_THROW_IN_PIT_2 = -1609097 , SPELL_GHOUL_SUMMONED = 52500 ,
SPELL_GOTHIK_GHOUL_PING = 52514 , SPELL_GHOUL_CREDIT = 52517 , SPELL_GHOULPLOSION = 52519 , NPC_GOTHIK = 28658
}
enum LightOfDawn {
SAY_LIGHT_OF_DAWN_INTRO_1 = -1609201 , SAY_LIGHT_OF_DAWN_INTRO_2 = -1609202 , SAY_LIGHT_OF_DAWN_PREPARE_1 = -1609203 , SAY_LIGHT_OF_DAWN_PREPARE_2 = -1609204 ,
SAY_LIGHT_OF_DAWN_PREPARE_3 = -1609205 , SAY_LIGHT_OF_DAWN_PREPARE_4 = -1609206 , SAY_LIGHT_OF_DAWN_STAND_1 = -1609207 , SAY_LIGHT_OF_DAWN_STAND_2 = -1609208 ,
SAY_LIGHT_OF_DAWN_BATTLE_1 = -1609209 , SAY_LIGHT_OF_DAWN_BATTLE_2 = -1609210 , SAY_LIGHT_OF_DAWN_BATTLE_3 = -1609211 , SAY_LIGHT_OF_DAWN_BATTLE_4 = -1609212 ,
SAY_LIGHT_OF_DAWN_BATTLE_5 = -1609213 , SAY_LIGHT_OF_DAWN_BATTLE_6 = -1609214 , SAY_LIGHT_OF_DAWN_BATTLE_7 = -1609215 , SAY_LIGHT_OF_DAWN_BATTLE_8 = -1609216 ,
SAY_LIGHT_OF_DAWN_BATTLE_9 = -1609224 , SAY_LIGHT_OF_DAWN_BATTLE_10 = -1609217 , SAY_LIGHT_OF_DAWN_BATTLE_11 = -1609218 , SAY_LIGHT_OF_DAWN_BATTLE_12 = -1609219 ,
SAY_LIGHT_OF_DAWN_BATTLE_13 = -1609220 , SAY_LIGHT_OF_DAWN_BATTLE_14 = -1609221 , SAY_LIGHT_OF_DAWN_BATTLE_15 = -1609222 , SAY_LIGHT_OF_DAWN_BATTLE_16 = -1609223 ,
SAY_LIGHT_OF_DAWN_OUTRO_1 = -1609225 , SAY_LIGHT_OF_DAWN_OUTRO_2 = -1609226 , SAY_LIGHT_OF_DAWN_OUTRO_3 = -1609227 , SAY_LIGHT_OF_DAWN_OUTRO_4 = -1609228 ,
SAY_LIGHT_OF_DAWN_OUTRO_5 = -1609229 , SAY_LIGHT_OF_DAWN_OUTRO_6 = -1609230 , SAY_LIGHT_OF_DAWN_OUTRO_7 = -1609231 , SAY_LIGHT_OF_DAWN_VISION_1 = -1609232 ,
SAY_LIGHT_OF_DAWN_VISION_2 = -1609233 , SAY_LIGHT_OF_DAWN_VISION_3 = -1609234 , SAY_LIGHT_OF_DAWN_VISION_4 = -1609235 , SAY_LIGHT_OF_DAWN_VISION_5 = -1609236 ,
SAY_LIGHT_OF_DAWN_VISION_6 = -1609237 , SAY_LIGHT_OF_DAWN_VISION_7 = -1609238 , SAY_LIGHT_OF_DAWN_VISION_8 = -1609239 , SAY_LIGHT_OF_DAWN_VISION_9 = -1609240 ,
SAY_LIGHT_OF_DAWN_VISION_10 = -1609241 , SAY_LIGHT_OF_DAWN_VISION_11 = -1609242 , SAY_LIGHT_OF_DAWN_KING_VISIT_1 = -1609243 , SAY_LIGHT_OF_DAWN_KING_VISIT_2 = -1609245 ,
SAY_LIGHT_OF_DAWN_KING_VISIT_3 = -1609244 , SAY_LIGHT_OF_DAWN_KING_VISIT_4 = -1609246 , SAY_LIGHT_OF_DAWN_KING_VISIT_5 = -1609247 , SAY_LIGHT_OF_DAWN_KING_VISIT_6 = -1609248 ,
SAY_LIGHT_OF_DAWN_KING_VISIT_7 = -1609249 , SAY_LIGHT_OF_DAWN_KING_VISIT_8 = -1609250 , SAY_LIGHT_OF_DAWN_KING_VISIT_9 = -1609251 , SAY_LIGHT_OF_DAWN_KING_VISIT_10 = -1609252 ,
SAY_LIGHT_OF_DAWN_KING_VISIT_11 = -1609253 , SAY_LIGHT_OF_DAWN_KING_VISIT_12 = -1609254 , SAY_LIGHT_OF_DAWN_KING_VISIT_13 = -1609255 , SAY_LIGHT_OF_DAWN_KING_VISIT_14 = -1609256 ,
SAY_LIGHT_OF_DAWN_KING_VISIT_15 = -1609257 , SAY_LIGHT_OF_DAWN_KING_VISIT_16 = -1609258 , SAY_LIGHT_OF_DAWN_KING_VISIT_17 = -1609259 , SAY_LIGHT_OF_DAWN_EPILOGUE_1 = -1609260 ,
SAY_LIGHT_OF_DAWN_EPILOGUE_2 = -1609261 , SAY_LIGHT_OF_DAWN_EPILOGUE_3 = -1609262 , SAY_LIGHT_OF_DAWN_EPILOGUE_4 = -1609263 , SAY_LIGHT_OF_DAWN_EPILOGUE_5 = -1609264 ,
SAY_LIGHT_OF_DAWN_EPILOGUE_6 = -1609265 , SAY_LIGHT_OF_DAWN_EPILOGUE_7 = -1609266 , SAY_LIGHT_OF_DAWN_EPILOGUE_8 = -1609267 , SAY_LIGHT_OF_DAWN_EPILOGUE_9 = -1609268 ,
EMOTE_LIGHT_OF_DAWN_FLEE = -1609272 , EMOTE_LIGHT_OF_DAWN_KNEEL = -1609273 , EMOTE_LIGHT_OF_DAWN_HUG = -1609276 , EMOTE_LIGHT_OF_DAWN_GRASP = -1609280 ,
EMOTE_LIGHT_OF_DAWN_COLAPSE = -1609283 , SOUND_ID_LK_LAUGH = 14820 , SOUND_ID_TIRION_ROAR = 12300 , SPELL_HERO_AGGRO_AURA = 53627 ,
SPELL_SCOURGE_AGGRO_AURA = 53624 , SPELL_ANTI_MAGIC_ZONE_DARION = 52893 , SPELL_DEATH_STRIKE = 53639 , SPELL_DEATH_EMBRACE = 53635 ,
SPELL_ICY_TOUCH_DARION = 49723 , SPELL_PLAGUE_STRIKE_KNIGHTS = 50688 , SPELL_THE_MIGHT_OF_MOGRAINE = 53642 , SPELL_UNHOLY_BLIGHT = 53640 ,
SPELL_THE_LIGHT_OF_DAWN_DUMMY = 53658 , SPELL_THE_LIGHT_OF_DAWN_DAMAGE_LOSS = 53645 , SPELL_MOGRAINE_CHARGE = 53679 , SPELL_ASHBRINGER = 53701 ,
SPELL_THE_LIGHT_OF_DAWN_CREDIT = 53606 , SPELL_APOCALYPSE = 53210 , SPELL_TELEPORT_VISUAL = 52233 , SPELL_SOUL_FEAST_ALEX = 53677 ,
SPELL_SOUL_FEAST_TIRION = 53685 , SPELL_REBUKE = 53680 , EQUIP_HIGHLORD_TIRION_FORDRING = 13262 , SPELL_LAY_ON_HANDS = 53778 ,
SPELL_REBIRTH_OF_THE_ASHBRINGER = 53702 , SPELL_TIRION_CHARGE = 53705 , QUEST_ID_LIGHT_OF_DAWN = 12801 , GOSSIP_ITEM_READY = -3609001 ,
GOSSIP_TEXT_ID_READY = 13485 , DATA_PREPARE_DIALOGUE = 1 , DATA_SUMMON_CHAMPIONS = 2 , DATA_SUMMON_DEFENDERS = 3 ,
DATA_SUMMON_ARMY_1 = 4 , DATA_SUMMON_ARMY_2 = 5 , DATA_SUMMON_ARMY_3 = 6 , DATA_SUMMON_ARMY_4 = 7 ,
DATA_UNDEAD_ARMY_MARCH = 8 , DATA_LICH_KING_POINT = 9 , DATA_LICH_KING_MOVE = 10 , DATA_LICH_KING_LAUGH = 11 ,
DATA_RESET_CHAMPIONS = 12 , DATA_LICH_KING_FACE_TIRION = 13 , DATA_LICH_KING_DEFEAT = 14 , DATA_TIRION_CONCLUSION = 15 ,
DATA_DARION_EXCLAMATION = 16
}
enum DarionActions {
DARION_ANTI_MAGIC_ZONE , DARION_DEATH_STRIKE , DARION_DEATH_EMBRACE , DARION_ICY_TOUCH ,
DARION_UNHOLY_BLIGHT , DARION_COMBAT_YELL , DARION_DEFEAT_YELL , DARION_ACTION_MAX
}
enum { SAY_TREE_1 = -1609079 , SAY_TREE_2 = -1609080 , GO_TREE = 191144 }
Functions
bool GossipHello_npc_death_knight_initiate (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_death_knight_initiate (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool EffectDummyCreature_npc_death_knight_initiate (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool EffectDummyCreature_npc_scarlet_ghoul (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GossipHello_npc_highlord_darion_mograine (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_highlord_darion_mograine (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_ebon_hold ()
Variables
static const DialogueEntry aSurpriseDialogue []
static const DialogueEntry aInitiateDialogue []
int32 m_auiRandomSay []
static const float aEyeDestination [3] = { 1758.007f, -5876.785f, 166.8667f }
static const float aEyeStartPos [3] = { 2361.21f, -5660.45f, 503.8283f }
static const float aPitPosition [3] = { 2369.276f, -5778.689f, 151.367f}
static const DialogueEntry aDarionDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DUEL_A
SAY_DUEL_B
SAY_DUEL_C
SAY_DUEL_D
SAY_DUEL_E
SAY_DUEL_F
SAY_DUEL_G
SAY_DUEL_H
SAY_DUEL_I
EMOTE_DUEL_BEGIN
EMOTE_DUEL_BEGIN_3
EMOTE_DUEL_BEGIN_2
EMOTE_DUEL_BEGIN_1
GOSSIP_ITEM_ACCEPT_DUEL
GOSSIP_TEXT_ID_DUEL
SPELL_DUEL
SPELL_DUEL_TRIGGERED
SPELL_DUEL_VICTORY
SPELL_DUEL_FLAG
SPELL_BLOOD_STRIKE
SPELL_DEATH_COIL
SPELL_ICY_TOUCH
SPELL_PLAGUE_STRIKE
GO_DUEL_FLAG
NPC_DEATH_KNIGHT_INITIATE
QUEST_DEATH_CHALLENGE
FACTION_HOSTILE
Definition at line 483 of file ebon_hold.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_EYE_CONTROL
SPELL_EYE_VISUAL
SPELL_EYE_FLIGHT
SPELL_EYE_FLIGHT_BOOST
SPELL_RECALL_EYE
EMOTE_DESTIANTION
EMOTE_CONTROL
POINT_EYE_START_POS
POINT_EYE_DESTINATION
START_POINT_PAUSE_TIME
Definition at line 735 of file ebon_hold.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_GHUL_SPAWN_1
SAY_GHUL_SPAWN_2
SAY_GHUL_SPAWN_3
SAY_GHUL_SPAWN_4
SAY_GHUL_SPAWN_5
SAY_GOTHIK_THROW_IN_PIT_1
SAY_GOTHIK_THROW_IN_PIT_2
SPELL_GHOUL_SUMMONED
SPELL_GOTHIK_GHOUL_PING
SPELL_GHOUL_CREDIT
SPELL_GHOULPLOSION
NPC_GOTHIK
Definition at line 872 of file ebon_hold.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_TREE_1
SAY_TREE_2
GO_TREE
Definition at line 1823 of file ebon_hold.cpp.
DarionActions
enum DarionActions
Enumerator
DARION_ANTI_MAGIC_ZONE
DARION_DEATH_STRIKE
DARION_DEATH_EMBRACE
DARION_ICY_TOUCH
DARION_UNHOLY_BLIGHT
DARION_COMBAT_YELL
DARION_DEFEAT_YELL
DARION_ACTION_MAX
Definition at line 1240 of file ebon_hold.cpp.
InitiateActions
enum InitiateActions
Enumerator
INITIATE_BLOOD_STRIKE
INITIATE_DEATH_COIL
INITIATE_ICY_TOUCH
INITIATE_PLAGUE_STRIKE
INITIATE_ACTION_MAX
Definition at line 538 of file ebon_hold.cpp.
LightOfDawn
enum LightOfDawn
Enumerator
SAY_LIGHT_OF_DAWN_INTRO_1
SAY_LIGHT_OF_DAWN_INTRO_2
SAY_LIGHT_OF_DAWN_PREPARE_1
SAY_LIGHT_OF_DAWN_PREPARE_2
SAY_LIGHT_OF_DAWN_PREPARE_3
SAY_LIGHT_OF_DAWN_PREPARE_4
SAY_LIGHT_OF_DAWN_STAND_1
SAY_LIGHT_OF_DAWN_STAND_2
SAY_LIGHT_OF_DAWN_BATTLE_1
SAY_LIGHT_OF_DAWN_BATTLE_2
SAY_LIGHT_OF_DAWN_BATTLE_3
SAY_LIGHT_OF_DAWN_BATTLE_4
SAY_LIGHT_OF_DAWN_BATTLE_5
SAY_LIGHT_OF_DAWN_BATTLE_6
SAY_LIGHT_OF_DAWN_BATTLE_7
SAY_LIGHT_OF_DAWN_BATTLE_8
SAY_LIGHT_OF_DAWN_BATTLE_9
SAY_LIGHT_OF_DAWN_BATTLE_10
SAY_LIGHT_OF_DAWN_BATTLE_11
SAY_LIGHT_OF_DAWN_BATTLE_12
SAY_LIGHT_OF_DAWN_BATTLE_13
SAY_LIGHT_OF_DAWN_BATTLE_14
SAY_LIGHT_OF_DAWN_BATTLE_15
SAY_LIGHT_OF_DAWN_BATTLE_16
SAY_LIGHT_OF_DAWN_OUTRO_1
SAY_LIGHT_OF_DAWN_OUTRO_2
SAY_LIGHT_OF_DAWN_OUTRO_3
SAY_LIGHT_OF_DAWN_OUTRO_4
SAY_LIGHT_OF_DAWN_OUTRO_5
SAY_LIGHT_OF_DAWN_OUTRO_6
SAY_LIGHT_OF_DAWN_OUTRO_7
SAY_LIGHT_OF_DAWN_VISION_1
SAY_LIGHT_OF_DAWN_VISION_2
SAY_LIGHT_OF_DAWN_VISION_3
SAY_LIGHT_OF_DAWN_VISION_4
SAY_LIGHT_OF_DAWN_VISION_5
SAY_LIGHT_OF_DAWN_VISION_6
SAY_LIGHT_OF_DAWN_VISION_7
SAY_LIGHT_OF_DAWN_VISION_8
SAY_LIGHT_OF_DAWN_VISION_9
SAY_LIGHT_OF_DAWN_VISION_10
SAY_LIGHT_OF_DAWN_VISION_11
SAY_LIGHT_OF_DAWN_KING_VISIT_1
SAY_LIGHT_OF_DAWN_KING_VISIT_2
SAY_LIGHT_OF_DAWN_KING_VISIT_3
SAY_LIGHT_OF_DAWN_KING_VISIT_4
SAY_LIGHT_OF_DAWN_KING_VISIT_5
SAY_LIGHT_OF_DAWN_KING_VISIT_6
SAY_LIGHT_OF_DAWN_KING_VISIT_7
SAY_LIGHT_OF_DAWN_KING_VISIT_8
SAY_LIGHT_OF_DAWN_KING_VISIT_9
SAY_LIGHT_OF_DAWN_KING_VISIT_10
SAY_LIGHT_OF_DAWN_KING_VISIT_11
SAY_LIGHT_OF_DAWN_KING_VISIT_12
SAY_LIGHT_OF_DAWN_KING_VISIT_13
SAY_LIGHT_OF_DAWN_KING_VISIT_14
SAY_LIGHT_OF_DAWN_KING_VISIT_15
SAY_LIGHT_OF_DAWN_KING_VISIT_16
SAY_LIGHT_OF_DAWN_KING_VISIT_17
SAY_LIGHT_OF_DAWN_EPILOGUE_1
SAY_LIGHT_OF_DAWN_EPILOGUE_2
SAY_LIGHT_OF_DAWN_EPILOGUE_3
SAY_LIGHT_OF_DAWN_EPILOGUE_4
SAY_LIGHT_OF_DAWN_EPILOGUE_5
SAY_LIGHT_OF_DAWN_EPILOGUE_6
SAY_LIGHT_OF_DAWN_EPILOGUE_7
SAY_LIGHT_OF_DAWN_EPILOGUE_8
SAY_LIGHT_OF_DAWN_EPILOGUE_9
EMOTE_LIGHT_OF_DAWN_FLEE
EMOTE_LIGHT_OF_DAWN_KNEEL
EMOTE_LIGHT_OF_DAWN_HUG
EMOTE_LIGHT_OF_DAWN_GRASP
EMOTE_LIGHT_OF_DAWN_COLAPSE
SOUND_ID_LK_LAUGH
SOUND_ID_TIRION_ROAR
SPELL_HERO_AGGRO_AURA
SPELL_SCOURGE_AGGRO_AURA
SPELL_ANTI_MAGIC_ZONE_DARION
SPELL_DEATH_STRIKE
SPELL_DEATH_EMBRACE
SPELL_ICY_TOUCH_DARION
SPELL_PLAGUE_STRIKE_KNIGHTS
SPELL_THE_MIGHT_OF_MOGRAINE
SPELL_UNHOLY_BLIGHT
SPELL_THE_LIGHT_OF_DAWN_DUMMY
SPELL_THE_LIGHT_OF_DAWN_DAMAGE_LOSS
SPELL_MOGRAINE_CHARGE
SPELL_ASHBRINGER
SPELL_THE_LIGHT_OF_DAWN_CREDIT
SPELL_APOCALYPSE
SPELL_TELEPORT_VISUAL
SPELL_SOUL_FEAST_ALEX
SPELL_SOUL_FEAST_TIRION
SPELL_REBUKE
EQUIP_HIGHLORD_TIRION_FORDRING
SPELL_LAY_ON_HANDS
SPELL_REBIRTH_OF_THE_ASHBRINGER
SPELL_TIRION_CHARGE
QUEST_ID_LIGHT_OF_DAWN
GOSSIP_ITEM_READY
GOSSIP_TEXT_ID_READY
DATA_PREPARE_DIALOGUE
DATA_SUMMON_CHAMPIONS
DATA_SUMMON_DEFENDERS
DATA_SUMMON_ARMY_1
DATA_SUMMON_ARMY_2
DATA_SUMMON_ARMY_3
DATA_SUMMON_ARMY_4
DATA_UNDEAD_ARMY_MARCH
DATA_LICH_KING_POINT
DATA_LICH_KING_MOVE
DATA_LICH_KING_LAUGH
DATA_RESET_CHAMPIONS
DATA_LICH_KING_FACE_TIRION
DATA_LICH_KING_DEFEAT
DATA_TIRION_CONCLUSION
DATA_DARION_EXCLAMATION
Definition at line 989 of file ebon_hold.cpp.
SpecialSurprise
enum SpecialSurprise
Enumerator
SAY_EXEC_START_1
SAY_EXEC_START_2
SAY_EXEC_START_3
SAY_EXEC_PROG_1
SAY_EXEC_PROG_2
SAY_EXEC_PROG_3
SAY_EXEC_PROG_4
SAY_EXEC_PROG_5
SAY_EXEC_PROG_6
SAY_EXEC_PROG_7
SAY_EXEC_NAME_1
SAY_EXEC_NAME_2
SAY_EXEC_RECOG_1
SAY_EXEC_RECOG_2
SAY_EXEC_RECOG_3
SAY_EXEC_RECOG_4
SAY_EXEC_RECOG_5
SAY_EXEC_RECOG_6
SAY_EXEC_NOREM_1
SAY_EXEC_NOREM_2
SAY_EXEC_NOREM_3
SAY_EXEC_NOREM_4
SAY_EXEC_NOREM_5
SAY_EXEC_NOREM_6
SAY_EXEC_NOREM_7
SAY_EXEC_NOREM_8
SAY_EXEC_NOREM_9
SAY_EXEC_NOREM_10
SAY_EXEC_THINK_1
SAY_EXEC_THINK_2
SAY_EXEC_THINK_3
SAY_EXEC_THINK_4
SAY_EXEC_THINK_5
SAY_EXEC_THINK_6
SAY_EXEC_THINK_7
SAY_EXEC_THINK_8
SAY_EXEC_THINK_9
SAY_EXEC_THINK_10
SAY_EXEC_LISTEN_1
SAY_EXEC_LISTEN_2
SAY_EXEC_LISTEN_3
SAY_EXEC_LISTEN_4
SAY_PLAGUEFIST
SAY_EXEC_TIME_1
SAY_EXEC_TIME_2
SAY_EXEC_TIME_3
SAY_EXEC_TIME_4
SAY_EXEC_TIME_5
SAY_EXEC_TIME_6
SAY_EXEC_TIME_7
SAY_EXEC_TIME_8
SAY_EXEC_TIME_9
SAY_EXEC_TIME_10
SAY_EXEC_WAITING
EMOTE_DIES
NPC_PRISONER_TAUREN
NPC_PRISONER_HUMAN
NPC_PRISONER_NIGHT_ELF
NPC_PRISONER_DWARF
NPC_PRISONER_GNOME
NPC_PRISONER_DRAENEI
NPC_PRISONER_UNDEAD
NPC_PRISONER_ORC
NPC_PRISONER_TROLL
NPC_PRISONER_BLOOD_ELF
NPC_PLAGUEFIST
DATA_NPC_STAND
DATA_NPC_TALK
DATA_NPC_EMOTE
DATA_NPC_EXCLAMATION
DATA_NPC_CRY
DATA_NPC_EXECUTION
Definition at line 54 of file ebon_hold.cpp.
Function Documentation
AddSC_ebon_hold()
void AddSC_ebon_hold ()
Definition at line 2348 of file ebon_hold.cpp.
References EffectDummyCreature_npc_death_knight_initiate(), EffectDummyCreature_npc_scarlet_ghoul(), Script::GetAI, Script::GetGameObjectAI, GossipHello_npc_death_knight_initiate(), GossipHello_npc_highlord_darion_mograine(), GossipSelect_npc_death_knight_initiate(), GossipSelect_npc_highlord_darion_mograine(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_death_knight_initiate()
bool EffectDummyCreature_npc_death_knight_initiate (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 720 of file ebon_hold.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, EFFECT_INDEX_0, UnitAI::SendAIEvent(), and SPELL_DUEL_TRIGGERED.
Referenced by AddSC_ebon_hold().
EffectDummyCreature_npc_scarlet_ghoul()
bool EffectDummyCreature_npc_scarlet_ghoul (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 973 of file ebon_hold.cpp.
References Unit::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, UnitAI::SendAIEvent(), and SPELL_GOTHIK_GHOUL_PING.
Referenced by AddSC_ebon_hold().
GossipHello_npc_death_knight_initiate()
bool GossipHello_npc_death_knight_initiate (Player * pPlayer, Creature * pCreature)
Definition at line 691 of file ebon_hold.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ACCEPT_DUEL, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_DUEL, QUEST_DEATH_CHALLENGE, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_ebon_hold().
GossipHello_npc_highlord_darion_mograine()
bool GossipHello_npc_highlord_darion_mograine (Player * pPlayer, Creature * pCreature)
Definition at line 1782 of file ebon_hold.cpp.
References BATTLE_STATE_NOT_STARTED, WorldObject::GetInstanceData(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_READY, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_READY, Unit::isQuestGiver(), Player::PrepareQuestMenu(), QUEST_ID_LIGHT_OF_DAWN, QUEST_STATUS_INCOMPLETE, and TYPE_BATTLE.
Referenced by AddSC_ebon_hold().
GossipSelect_npc_death_knight_initiate()
bool GossipSelect_npc_death_knight_initiate (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 702 of file ebon_hold.cpp.
References Unit::CastSpell(), countof, DoScriptText(), GOSSIP_ACTION_INFO_DEF, m_auiRandomSay, Object::RemoveFlag(), Unit::SetFacingToObject(), SPELL_DUEL, SPELL_DUEL_FLAG, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, UNIT_FLAG_SWIMMING, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and urand().
Referenced by AddSC_ebon_hold().
GossipSelect_npc_highlord_darion_mograine()
bool GossipSelect_npc_highlord_darion_mograine (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1799 of file ebon_hold.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, BATTLE_STATE_PREPARE, WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, UnitAI::SendAIEvent(), and TYPE_BATTLE.
Referenced by AddSC_ebon_hold().
Variable Documentation
aDarionDialogue
const DialogueEntry aDarionDialogue[] static
Definition at line 1153 of file ebon_hold.cpp.
aEyeDestination
const float aEyeDestination[3] = { 1758.007f, -5876.785f, 166.8667f } static
Definition at line 753 of file ebon_hold.cpp.
Referenced by npc_eye_of_acherusAI::UpdateAI().
aEyeStartPos
const float aEyeStartPos[3] = { 2361.21f, -5660.45f, 503.8283f } static
Definition at line 754 of file ebon_hold.cpp.
Referenced by npc_eye_of_acherusAI::UpdateAI().
aInitiateDialogue
const DialogueEntry aInitiateDialogue[] static
Initial value:
=
{
    {GO_DUEL_FLAG,              0,                         5000},
    {EMOTE_DUEL_BEGIN,          NPC_DEATH_KNIGHT_INITIATE, 1000},
    {EMOTE_DUEL_BEGIN_3,        NPC_DEATH_KNIGHT_INITIATE, 1000},
    {EMOTE_DUEL_BEGIN_2,        NPC_DEATH_KNIGHT_INITIATE, 1000},
    {EMOTE_DUEL_BEGIN_1,        NPC_DEATH_KNIGHT_INITIATE, 1000},
    {NPC_DEATH_KNIGHT_INITIATE, 0,                         0},
    {0, 0, 0},
}
Definition at line 522 of file ebon_hold.cpp.
aPitPosition
const float aPitPosition[3] = { 2369.276f, -5778.689f, 151.367f} static
Definition at line 890 of file ebon_hold.cpp.
Referenced by npc_scarlet_ghoulAI::ReceiveAIEvent().
aSurpriseDialogue
const DialogueEntry aSurpriseDialogue[] static
Definition at line 144 of file ebon_hold.cpp.
m_auiRandomSay
int32 m_auiRandomSay[]
Initial value:
=
{
    SAY_DUEL_A, SAY_DUEL_B, SAY_DUEL_C, SAY_DUEL_D, SAY_DUEL_E, SAY_DUEL_F, SAY_DUEL_G, SAY_DUEL_H, SAY_DUEL_I
}
Definition at line 533 of file ebon_hold.cpp.
Referenced by GossipSelect_npc_death_knight_initiate().