CMaNGOS_WoTLK: eversong_woods.cpp File Reference
eversong_woods.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Entities/TemporarySpawn.h"
#include <inttypes.h>
Data Structures
struct npc_kelerun_bloodmournAI
struct npc_prospector_anvilwardAI
struct npc_apprentice_mirvedaAI
struct npc_infused_crystalAI
Enumerations
enum {
NPC_KELERUN = 17807 , NPC_BLOODWRATH = 17809 , NPC_LIGHTREND = 17810 , NPC_SWIFTBLADE = 17811 ,
NPC_SUNSTRIKER = 17812 , GO_SECOND_TRIAL = 182052 , QUEST_SECOND_TRIAL = 9686 , MAX_CHALLENGER = 4
}
enum {
SAY_ANVIL1 = 11734 , SAY_ANVIL2 = 11735 , GOSSIP_ITEM_MOMENT = -3000108 , GOSSIP_ITEM_SHOW = -3000110 ,
GOSSIP_TEXT_ID_MOMENT = 8239 , GOSSIP_TEXT_ID_SHOW = 8240 , FACTION_HOSTILE = 14 , QUEST_THE_DWARVEN_SPY = 8483
}
enum { QUEST_UNEXPECTED_RESULT = 8488 , SPELL_FIREBALL = 20811 , NPC_GHARSUL = 15958 , NPC_ANGERSHADE = 15656 }
enum { QUEST_POWERING_OUR_DEFENSES = 8490 , SAY_DEFENSE_FINISH = -1000668 , NPC_ENRAGED_WRAITH = 17086 }
Functions
UnitAI * GetAI_npc_kelerun_bloodmourn (Creature *pCreature)
bool QuestAccept_npc_kelerun_bloodmourn (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GOUse_go_harbinger_second_trial (Player *, GameObject *pGO)
UnitAI * GetAI_npc_prospector_anvilward (Creature *pCreature)
bool GossipHello_npc_prospector_anvilward (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_prospector_anvilward (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool QuestAccept_unexpected_results (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_apprentice_mirvedaAI (Creature *pCreature)
UnitAI * GetAI_npc_infused_crystalAI (Creature *pCreature)
void AddSC_eversong_woods ()
Variables
const uint32 uiChallengerId [4] = {NPC_BLOODWRATH, NPC_LIGHTREND, NPC_SWIFTBLADE, NPC_SUNSTRIKER}
const int32 uiSayId [4]
float fChallengerLoc [4][4]
static const float aSummonPos [6][4]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_KELERUN
NPC_BLOODWRATH
NPC_LIGHTREND
NPC_SWIFTBLADE
NPC_SUNSTRIKER
GO_SECOND_TRIAL
QUEST_SECOND_TRIAL
MAX_CHALLENGER
Definition at line 41 of file eversong_woods.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ANVIL1
SAY_ANVIL2
GOSSIP_ITEM_MOMENT
GOSSIP_ITEM_SHOW
GOSSIP_TEXT_ID_MOMENT
GOSSIP_TEXT_ID_SHOW
FACTION_HOSTILE
QUEST_THE_DWARVEN_SPY
Definition at line 256 of file eversong_woods.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_UNEXPECTED_RESULT
SPELL_FIREBALL
NPC_GHARSUL
NPC_ANGERSHADE
Definition at line 341 of file eversong_woods.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_POWERING_OUR_DEFENSES
SAY_DEFENSE_FINISH
NPC_ENRAGED_WRAITH
Definition at line 474 of file eversong_woods.cpp.
Function Documentation
AddSC_eversong_woods()
void AddSC_eversong_woods ()
Definition at line 568 of file eversong_woods.cpp.
References Script::GetAI, GetAI_npc_apprentice_mirvedaAI(), GetAI_npc_infused_crystalAI(), GetAI_npc_kelerun_bloodmourn(), GetAI_npc_prospector_anvilward(), GossipHello_npc_prospector_anvilward(), GossipSelect_npc_prospector_anvilward(), GOUse_go_harbinger_second_trial(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_kelerun_bloodmourn(), QuestAccept_unexpected_results(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_apprentice_mirvedaAI()
UnitAI* GetAI_npc_apprentice_mirvedaAI (Creature * pCreature)
Definition at line 465 of file eversong_woods.cpp.
Referenced by AddSC_eversong_woods().
GetAI_npc_infused_crystalAI()
UnitAI* GetAI_npc_infused_crystalAI (Creature * pCreature)
Definition at line 563 of file eversong_woods.cpp.
Referenced by AddSC_eversong_woods().
GetAI_npc_kelerun_bloodmourn()
UnitAI* GetAI_npc_kelerun_bloodmourn (Creature * pCreature)
Definition at line 222 of file eversong_woods.cpp.
Referenced by AddSC_eversong_woods().
GetAI_npc_prospector_anvilward()
UnitAI* GetAI_npc_prospector_anvilward (Creature * pCreature)
Definition at line 301 of file eversong_woods.cpp.
Referenced by AddSC_eversong_woods().
GossipHello_npc_prospector_anvilward()
bool GossipHello_npc_prospector_anvilward (Player * pPlayer, Creature * pCreature)
Definition at line 306 of file eversong_woods.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_MOMENT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_MOMENT, QUEST_STATUS_INCOMPLETE, and QUEST_THE_DWARVEN_SPY.
Referenced by AddSC_eversong_woods().
GossipSelect_npc_prospector_anvilward()
bool GossipSelect_npc_prospector_anvilward (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 315 of file eversong_woods.cpp.
References Creature::AI(), DoBroadcastText(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SHOW, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_SHOW, and SAY_ANVIL1.
Referenced by AddSC_eversong_woods().
GOUse_go_harbinger_second_trial()
bool GOUse_go_harbinger_second_trial (Player * , GameObject * pGO)
Definition at line 239 of file eversong_woods.cpp.
References GAMEOBJECT_TYPE_GOOBER, GetClosestCreatureWithEntry(), GameObject::GetGoType(), and NPC_KELERUN.
Referenced by AddSC_eversong_woods().
QuestAccept_npc_kelerun_bloodmourn()
bool QuestAccept_npc_kelerun_bloodmourn (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 228 of file eversong_woods.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_SECOND_TRIAL.
Referenced by AddSC_eversong_woods().
QuestAccept_unexpected_results()
bool QuestAccept_unexpected_results (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 457 of file eversong_woods.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_UNEXPECTED_RESULT.
Referenced by AddSC_eversong_woods().
Variable Documentation
aSummonPos
const float aSummonPos[6][4] static
Initial value:
=
{
    {8250.539f, -7239.028f, 139.7099f, 0.8975816f},
    {8263.437f, -7181.188f, 139.4102f, 5.237229f},
    {8317.124f, -7210.098f, 140.1064f, 3.022202f},
    {8293.848f, -7179.062f, 138.6693f, 4.153376f},
    {8239.229f, -7207.673f, 139.1196f, 0.06059111f},
    {8301.548f, -7247.548f, 139.974f, 1.828518f}
}
Definition at line 481 of file eversong_woods.cpp.
Referenced by npc_infused_crystalAI::UpdateAI().
fChallengerLoc
float fChallengerLoc[4][4]
Initial value:
=
{
    {10110.667f, -6628.059f, 4.100f, 2.708f},
    {10093.919f, -6634.340f, 4.098f, 1.106f},
    {10087.565f, -6617.282f, 4.098f, 5.887f},
    {10104.807f, -6611.145f, 4.101f, 4.265f}
}
Definition at line 64 of file eversong_woods.cpp.
Referenced by npc_kelerun_bloodmournAI::DoSpawnChallengers().
uiChallengerId
const uint32 uiChallengerId[4] = {NPC_BLOODWRATH, NPC_LIGHTREND, NPC_SWIFTBLADE, NPC_SUNSTRIKER}
Definition at line 54 of file eversong_woods.cpp.
Referenced by npc_kelerun_bloodmournAI::DoSpawnChallengers().
uiSayId
const int32 uiSayId[4]
Initial value:
=
{
    -1000319,
    -1000320,
    -1000321,
    -1000322
}
Definition at line 56 of file eversong_woods.cpp.
Referenced by npc_kelerun_bloodmournAI::UpdateAI().