CMaNGOS_WoTLK: example_escort.cpp File Reference
example_escort.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct example_escortAI
Macros
#define GOSSIP_ITEM_1 "Click to Test Escort(Attack, Run)"
#define GOSSIP_ITEM_2 "Click to Test Escort(NoAttack, Walk)"
#define GOSSIP_ITEM_3 "Click to Test Escort(NoAttack, Run)"
Enumerations
enum {
NPC_FELBOAR = 21878 , SPELL_DEATH_COIL = 33130 , SPELL_ELIXIR_OF_FORTITUDE = 3593 , SPELL_BLUE_FIREWORK = 11540 ,
SAY_AGGRO1 = -1999910 , SAY_AGGRO2 = -1999911 , SAY_WP_1 = -1999912 , SAY_WP_2 = -1999913 ,
SAY_WP_3 = -1999914 , SAY_WP_4 = -1999915 , SAY_DEATH_1 = -1999916 , SAY_DEATH_2 = -1999917 ,
SAY_DEATH_3 = -1999918 , SAY_SPELL = -1999919 , SAY_RAND_1 = -1999920 , SAY_RAND_2 = -1999921
}
Functions
UnitAI * GetAI_example_escort (Creature *pCreature)
bool GossipHello_example_escort (Player *pPlayer, Creature *pCreature)
bool GossipSelect_example_escort (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_example_escort ()
Macro Definition Documentation
GOSSIP_ITEM_1
#define GOSSIP_ITEM_1 "Click to Test Escort(Attack, Run)"
Definition at line 49 of file example_escort.cpp.
GOSSIP_ITEM_2
#define GOSSIP_ITEM_2 "Click to Test Escort(NoAttack, Walk)"
Definition at line 50 of file example_escort.cpp.
GOSSIP_ITEM_3
#define GOSSIP_ITEM_3 "Click to Test Escort(NoAttack, Run)"
Definition at line 51 of file example_escort.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_FELBOAR
SPELL_DEATH_COIL
SPELL_ELIXIR_OF_FORTITUDE
SPELL_BLUE_FIREWORK
SAY_AGGRO1
SAY_AGGRO2
SAY_WP_1
SAY_WP_2
SAY_WP_3
SAY_WP_4
SAY_DEATH_1
SAY_DEATH_2
SAY_DEATH_3
SAY_SPELL
SAY_RAND_1
SAY_RAND_2
Definition at line 27 of file example_escort.cpp.
Function Documentation
AddSC_example_escort()
void AddSC_example_escort ()
Definition at line 225 of file example_escort.cpp.
References Script::GetAI, GetAI_example_escort(), GossipHello_example_escort(), GossipSelect_example_escort(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_example_escort()
UnitAI* GetAI_example_escort (Creature * pCreature)
Definition at line 175 of file example_escort.cpp.
Referenced by AddSC_example_escort().
GossipHello_example_escort()
bool GossipHello_example_escort (Player * pPlayer, Creature * pCreature)
Definition at line 180 of file example_escort.cpp.
References Player::GetDefaultGossipMenuForSource(), Object::GetEntry(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_1, GOSSIP_ITEM_2, GOSSIP_ITEM_3, GOSSIP_SENDER_MAIN, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and Player::TalkedToCreature().
Referenced by AddSC_example_escort().
GossipSelect_example_escort()
bool GossipSelect_example_escort (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 194 of file example_escort.cpp.
References Creature::AI(), GOSSIP_ACTION_INFO_DEF, and npc_escortAI::Start().
Referenced by AddSC_example_escort().