CMaNGOS_WoTLK: example_gossip_codebox.cpp File Reference
example_gossip_codebox.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include <cstring>
Macros
#define GOSSIP_ITEM_1 "A quiz: what's your name?"
#define GOSSIP_ITEM_2 "I'm not interested"
Enumerations
enum {
SPELL_POLYMORPH = 12826 , SPELL_MARK_OF_THE_WILD = 26990 , SAY_NOT_INTERESTED = -1999922 , SAY_WRONG = -1999923 ,
SAY_CORRECT = -1999924
}
Functions
bool GossipHello_example_gossip_codebox (Player *pPlayer, Creature *pCreature)
bool GossipSelect_example_gossip_codebox (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipSelectWithCode_example_gossip_codebox (Player *pPlayer, Creature *pCreature, uint32 uiSender, uint32 uiAction, const char *sCode)
void AddSC_example_gossip_codebox ()
Macro Definition Documentation
GOSSIP_ITEM_1
#define GOSSIP_ITEM_1 "A quiz: what's your name?"
Definition at line 38 of file example_gossip_codebox.cpp.
GOSSIP_ITEM_2
#define GOSSIP_ITEM_2 "I'm not interested"
Definition at line 39 of file example_gossip_codebox.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_POLYMORPH
SPELL_MARK_OF_THE_WILD
SAY_NOT_INTERESTED
SAY_WRONG
SAY_CORRECT
Definition at line 27 of file example_gossip_codebox.cpp.
Function Documentation
AddSC_example_gossip_codebox()
void AddSC_example_gossip_codebox ()
Definition at line 90 of file example_gossip_codebox.cpp.
References GossipHello_example_gossip_codebox(), GossipSelect_example_gossip_codebox(), GossipSelectWithCode_example_gossip_codebox(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGossipSelectWithCode, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_example_gossip_codebox()
bool GossipHello_example_gossip_codebox (Player * pPlayer, Creature * pCreature)
Definition at line 42 of file example_gossip_codebox.cpp.
References Object::GetObjectGuid(), Player::GetPlayerMenu(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_1, GOSSIP_ITEM_2, GOSSIP_SENDER_MAIN, and PlayerMenu::SendGossipMenu().
Referenced by AddSC_example_gossip_codebox().
GossipSelect_example_gossip_codebox()
bool GossipSelect_example_gossip_codebox (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 53 of file example_gossip_codebox.cpp.
References DoScriptText(), GOSSIP_ACTION_INFO_DEF, and SAY_NOT_INTERESTED.
Referenced by AddSC_example_gossip_codebox().
GossipSelectWithCode_example_gossip_codebox()
bool GossipSelectWithCode_example_gossip_codebox (Player * pPlayer, Creature * pCreature, uint32 uiSender, uint32 uiAction, const char * sCode)
Definition at line 64 of file example_gossip_codebox.cpp.
References Unit::CastSpell(), DoScriptText(), WorldObject::GetName(), GOSSIP_ACTION_INFO_DEF, GOSSIP_SENDER_MAIN, SAY_CORRECT, SAY_WRONG, SPELL_MARK_OF_THE_WILD, SPELL_POLYMORPH, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_example_gossip_codebox().