CMaNGOS_WoTLK: example_misc.cpp File Reference
example_misc.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Enumerations
enum { SAY_HI = -1999925 }
Functions
bool AreaTrigger_at_example (Player *pPlayer, AreaTriggerEntry const *)
void LoadDatabase ()
bool ItemUse_example_item (Player *, Item *, SpellCastTargets const &)
bool GOUse_example_go_teleporter (Player *pPlayer, GameObject *)
void AddSC_example_misc ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_HI
Definition at line 26 of file example_misc.cpp.
Function Documentation
AddSC_example_misc()
void AddSC_example_misc ()
Definition at line 50 of file example_misc.cpp.
References AreaTrigger_at_example(), GOUse_example_go_teleporter(), ItemUse_example_item(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pItemUse, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_example()
bool AreaTrigger_at_example (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 31 of file example_misc.cpp.
References DoScriptText(), and SAY_HI.
Referenced by AddSC_example_misc().
GOUse_example_go_teleporter()
bool GOUse_example_go_teleporter (Player * pPlayer, GameObject *)
Definition at line 44 of file example_misc.cpp.
References Player::TeleportTo().
Referenced by AddSC_example_misc().
ItemUse_example_item()
bool ItemUse_example_item (Player * , Item * , SpellCastTargets const &)
Definition at line 38 of file example_misc.cpp.
References LoadDatabase().
Referenced by AddSC_example_misc().
LoadDatabase()
void LoadDatabase ()
Definition at line 24 of file ScriptDevAIMgr.cpp.
References pSystemMgr.
Referenced by ScriptDevAIMgr::Initialize(), and ItemUse_example_item().