CMaNGOS_WoTLK: example_creature.cpp File Reference
example_creature.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct example_creatureAI
Macros
#define GOSSIP_ITEM "I'm looking for a fight"
Enumerations
enum {
SAY_AGGRO = -1999900 , SAY_RANDOM_0 = -1999901 , SAY_RANDOM_1 = -1999902 , SAY_RANDOM_2 = -1999903 ,
SAY_RANDOM_3 = -1999904 , SAY_RANDOM_4 = -1999905 , SAY_BESERK = -1999906 , SAY_PHASE = -1999907 ,
SAY_DANCE = -1999908 , SAY_SALUTE = -1999909 , SPELL_BUFF = 25661 , SPELL_ONE = 12555 ,
SPELL_ONE_ALT = 24099 , SPELL_TWO = 10017 , SPELL_THREE = 26027 , SPELL_ENRAGE = 23537 ,
SPELL_BESERK = 32309 , TEXT_ID_GREET = 907 , FACTION_WORGEN = 24
}
Functions
UnitAI * GetAI_example_creature (Creature *pCreature)
bool GossipHello_example_creature (Player *pPlayer, Creature *pCreature)
bool GossipSelect_example_creature (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_example_creature ()
Macro Definition Documentation
GOSSIP_ITEM
#define GOSSIP_ITEM "I'm looking for a fight"
Definition at line 70 of file example_creature.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_RANDOM_0
SAY_RANDOM_1
SAY_RANDOM_2
SAY_RANDOM_3
SAY_RANDOM_4
SAY_BESERK
SAY_PHASE
SAY_DANCE
SAY_SALUTE
SPELL_BUFF
SPELL_ONE
SPELL_ONE_ALT
SPELL_TWO
SPELL_THREE
SPELL_ENRAGE
SPELL_BESERK
TEXT_ID_GREET
FACTION_WORGEN
Definition at line 38 of file example_creature.cpp.
Function Documentation
AddSC_example_creature()
void AddSC_example_creature ()
Definition at line 281 of file example_creature.cpp.
References Script::GetAI, GetAI_example_creature(), GossipHello_example_creature(), GossipSelect_example_creature(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_example_creature()
UnitAI* GetAI_example_creature (Creature * pCreature)
Definition at line 249 of file example_creature.cpp.
Referenced by AddSC_example_creature().
GossipHello_example_creature()
bool GossipHello_example_creature (Player * pPlayer, Creature * pCreature)
Definition at line 256 of file example_creature.cpp.
References Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM, GOSSIP_SENDER_MAIN, and TEXT_ID_GREET.
Referenced by AddSC_example_creature().
GossipSelect_example_creature()
bool GossipSelect_example_creature (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 266 of file example_creature.cpp.
References Creature::AI(), UnitAI::AttackStart(), FACTION_WORGEN, GOSSIP_ACTION_INFO_DEF, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_example_creature().