CMaNGOS_WoTLK: felwood.cpp File Reference
felwood.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Globals/ObjectMgr.h"
Data Structures
struct npc_kittenAI
struct npc_captured_arkonarinAI
struct npc_areiAI
Macros
#define GOSSIP_ITEM_RELEASE "I want to release the corrupted saber to Winna."
Enumerations
enum {
EMOTE_SAB_JUMP = -1000541 , EMOTE_SAB_FOLLOW = -1000542 , SPELL_CORRUPT_SABER_VISUAL = 16510 , QUEST_CORRUPT_SABER = 4506 ,
NPC_WINNA = 9996 , NPC_CORRUPT_SABER = 10042
}
enum {
SAY_ESCORT_START = 6433 , SPELL_MORTAL_STRIKE = 16856 , SPELL_CLEAVE = 15496 , QUEST_ID_RESCUE_JAEDENAR = 5203 ,
NPC_JAEDENAR_LEGIONNAIRE = 9862 , NPC_SPIRT_TREY = 11141 , GO_ARKONARIN_CAGE = 176306 , PATH_ID = 11016
}
enum {
SAY_AREI_ESCORT_START = -1001159 , SAY_ATTACK_IRONTREE = -1001160 , SAY_ATTACK_TOXIC_HORROR = -1001161 , SAY_EXIT_WOODS = -1001162 ,
SAY_CLEAR_PATH = -1001163 , SAY_ASHENVALE = -1001164 , SAY_TRANSFORM = -1001165 , SAY_LIFT_CURSE = -1001166 ,
SAY_AREI_ESCORT_COMPLETE = -1001167 , SPELL_WITHER_STRIKE = 5337 , SPELL_AREI_TRANSFORM = 14888 , NPC_AREI = 9598 ,
NPC_TOXIC_HORROR = 7132 , NPC_IRONTREE_WANDERER = 7138 , NPC_IRONTREE_STOMPER = 7139 , QUEST_ID_ANCIENT_SPIRIT = 4261
}
Functions
UnitAI * GetAI_npc_kitten (Creature *pCreature)
bool EffectDummyCreature_npc_kitten (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GossipHello_npc_corrupt_saber (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_corrupt_saber (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_captured_arkonarin (Creature *pCreature)
bool QuestAccept_npc_captured_arkonarin (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_arei (Creature *pCreature)
bool QuestAccept_npc_arei (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_felwood ()
Variables
static const int32 aRandomAggro [] = { 6801, 6802, 6803 }
static const DialogueEntry aEpilogDialogue []
Macro Definition Documentation
GOSSIP_ITEM_RELEASE
#define GOSSIP_ITEM_RELEASE "I want to release the corrupted saber to Winna."
Definition at line 53 of file felwood.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_SAB_JUMP
EMOTE_SAB_FOLLOW
SPELL_CORRUPT_SABER_VISUAL
QUEST_CORRUPT_SABER
NPC_WINNA
NPC_CORRUPT_SABER
Definition at line 41 of file felwood.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SPELL_MORTAL_STRIKE
SPELL_CLEAVE
QUEST_ID_RESCUE_JAEDENAR
NPC_JAEDENAR_LEGIONNAIRE
NPC_SPIRT_TREY
GO_ARKONARIN_CAGE
PATH_ID
Definition at line 169 of file felwood.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_AREI_ESCORT_START
SAY_ATTACK_IRONTREE
SAY_ATTACK_TOXIC_HORROR
SAY_EXIT_WOODS
SAY_CLEAR_PATH
SAY_ASHENVALE
SAY_TRANSFORM
SAY_LIFT_CURSE
SAY_AREI_ESCORT_COMPLETE
SPELL_WITHER_STRIKE
SPELL_AREI_TRANSFORM
NPC_AREI
NPC_TOXIC_HORROR
NPC_IRONTREE_WANDERER
NPC_IRONTREE_STOMPER
QUEST_ID_ANCIENT_SPIRIT
Definition at line 313 of file felwood.cpp.
Function Documentation
AddSC_felwood()
void AddSC_felwood ()
Definition at line 494 of file felwood.cpp.
References EffectDummyCreature_npc_kitten(), Script::GetAI, GetAI_npc_arei(), GetAI_npc_captured_arkonarin(), GetAI_npc_kitten(), GossipHello_npc_corrupt_saber(), GossipSelect_npc_corrupt_saber(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_arei(), QuestAccept_npc_captured_arkonarin(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_kitten()
bool EffectDummyCreature_npc_kitten (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 115 of file felwood.cpp.
References Creature::ChooseDisplayId(), DoScriptText(), EFFECT_INDEX_0, EMOTE_SAB_FOLLOW, GetCreatureTemplateStore(), Unit::GetOwner(), NPC_CORRUPT_SABER, OBJECT_FIELD_SCALE_X, Unit::SetDisplayId(), Object::SetEntry(), Object::SetFloatValue(), WorldObject::SetName(), and SPELL_CORRUPT_SABER_VISUAL.
Referenced by AddSC_felwood().
GetAI_npc_arei()
UnitAI* GetAI_npc_arei (Creature * pCreature)
Definition at line 481 of file felwood.cpp.
Referenced by AddSC_felwood().
GetAI_npc_captured_arkonarin()
UnitAI* GetAI_npc_captured_arkonarin (Creature * pCreature)
Definition at line 296 of file felwood.cpp.
Referenced by AddSC_felwood().
GetAI_npc_kitten()
UnitAI* GetAI_npc_kitten (Creature * pCreature)
Definition at line 110 of file felwood.cpp.
Referenced by AddSC_felwood().
GossipHello_npc_corrupt_saber()
bool GossipHello_npc_corrupt_saber (Player * pPlayer, Creature * pCreature)
Definition at line 138 of file felwood.cpp.
References GetClosestCreatureWithEntry(), Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_RELEASE, GOSSIP_SENDER_MAIN, INTERACTION_DISTANCE, NPC_WINNA, QUEST_CORRUPT_SABER, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_felwood().
GossipSelect_npc_corrupt_saber()
bool GossipSelect_npc_corrupt_saber (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 150 of file felwood.cpp.
References Creature::AI(), Player::AreaExploredOrEventHappens(), GOSSIP_ACTION_INFO_DEF, and QUEST_CORRUPT_SABER.
Referenced by AddSC_felwood().
QuestAccept_npc_arei()
bool QuestAccept_npc_arei (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 486 of file felwood.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_ANCIENT_SPIRIT, and UnitAI::SendAIEvent().
Referenced by AddSC_felwood().
QuestAccept_npc_captured_arkonarin()
bool QuestAccept_npc_captured_arkonarin (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 301 of file felwood.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_RESCUE_JAEDENAR, and UnitAI::SendAIEvent().
Referenced by AddSC_felwood().
Variable Documentation
aEpilogDialogue
const DialogueEntry aEpilogDialogue[] static
Initial value:
=
{
    {SAY_CLEAR_PATH,            NPC_AREI,   4000},
    {SPELL_WITHER_STRIKE,       0,          5000},
    {SAY_TRANSFORM,             NPC_AREI,   3000},
    {SPELL_AREI_TRANSFORM,      0,          7000},
    {QUEST_ID_ANCIENT_SPIRIT,   0,          0},
    {0, 0, 0},
}
Definition at line 335 of file felwood.cpp.
aRandomAggro
const int32 aRandomAggro[] = { 6801, 6802, 6803 } static
Definition at line 187 of file felwood.cpp.
Referenced by npc_captured_arkonarinAI::Aggro().