CMaNGOS_WoTLK: feralas.cpp File Reference
feralas.cpp File Reference
#include "Grids/GridNotifiers.h"
#include "Grids/CellImpl.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_oox22feAI
struct npc_shay_leafrunnerAI
struct npc_captured_sprite_darterAI
struct npc_kindal_moonweaverAI
struct SpecificTargetScript
struct CaptureBeast
struct CaptureHippogryph
struct CaptureFaerieDragon
struct CaptureTreant
struct CaptureMountainGiant
Enumerations
enum {
SAY_OOX_START = -1000287 , SAY_OOX_AGGRO1 = -1000288 , SAY_OOX_AGGRO2 = -1000289 , SAY_OOX_AMBUSH = -1000290 ,
SAY_OOX_END = -1000292 , NPC_YETI = 7848 , NPC_GORILLA = 5260 , NPC_WOODPAW_REAVER = 5255 ,
NPC_WOODPAW_BRUTE = 5253 , NPC_WOODPAW_ALPHA = 5258 , NPC_WOODPAW_MYSTIC = 5254 , QUEST_RESCUE_OOX22FE = 2767
}
enum {
SAY_ESCORT_START = -1001106 , SAY_WANDER_1 = -1001107 , SAY_WANDER_2 = -1001108 , SAY_WANDER_3 = -1001109 ,
SAY_WANDER_4 = -1001110 , SAY_WANDER_DONE_1 = -1001111 , SAY_WANDER_DONE_2 = -1001112 , SAY_WANDER_DONE_3 = -1001113 ,
EMOTE_WANDER = -1001114 , SAY_EVENT_COMPLETE_1 = -1001115 , SAY_EVENT_COMPLETE_2 = -1001116 , SPELL_SHAYS_BELL = 11402 ,
NPC_ROCKBITER = 7765 , QUEST_ID_WANDERING_SHAY = 2845
}
enum {
SAY_KINDAL_QUEST_START = -1010023 , SAY_KINDAL_INITIAL_AGGRO = -1010024 , SAY_KINDAL_AGGRO = -1010025 , SAY_KINDAL_QUEST_COMPLETE = -1010026 ,
NPC_CAPTURED_SPRITE_DARTER = 7997 , NPC_GRIMTOTEM_RAIDER = 7725 , NPC_KINDAL_MOONWEAVER = 7956 , QUEST_FREEDOM_ALL_CREATURES = 2969 ,
SPELL_MANA_BURN = 11981 , SPELL_SHOOT = 14443 , SPELL_MULTI_SHOT = 6660
}
Functions
UnitAI * GetAI_npc_oox22fe (Creature *pCreature)
bool QuestAccept_npc_oox22fe (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_shay_leafrunner (Creature *pCreature)
bool QuestAccept_npc_shay_leafrunner (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool EffectDummyCreature_npc_shay_leafrunner (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_captured_sprite_darter (Creature *pCreature)
bool GOUse_go_cage_door (Player *player, GameObject *go)
UnitAI * GetAI_npc_kindal_moonweaver (Creature *pCreature)
bool QuestAccept_npc_kindal_moonweaver (Player *player, Creature *creature, const Quest *quest)
void AddSC_feralas ()
Variables
static const float raiderSpawnPos [4] = { -4515.35f, 811.36f, 62.99f, 3.60244f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_OOX_START
SAY_OOX_AGGRO1
SAY_OOX_AGGRO2
SAY_OOX_AMBUSH
SAY_OOX_END
NPC_YETI
NPC_GORILLA
NPC_WOODPAW_REAVER
NPC_WOODPAW_BRUTE
NPC_WOODPAW_ALPHA
NPC_WOODPAW_MYSTIC
QUEST_RESCUE_OOX22FE
Definition at line 45 of file feralas.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_WANDER_1
SAY_WANDER_2
SAY_WANDER_3
SAY_WANDER_4
SAY_WANDER_DONE_1
SAY_WANDER_DONE_2
SAY_WANDER_DONE_3
EMOTE_WANDER
SAY_EVENT_COMPLETE_1
SAY_EVENT_COMPLETE_2
SPELL_SHAYS_BELL
NPC_ROCKBITER
QUEST_ID_WANDERING_SHAY
Definition at line 162 of file feralas.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_KINDAL_QUEST_START
SAY_KINDAL_INITIAL_AGGRO
SAY_KINDAL_AGGRO
SAY_KINDAL_QUEST_COMPLETE
NPC_CAPTURED_SPRITE_DARTER
NPC_GRIMTOTEM_RAIDER
NPC_KINDAL_MOONWEAVER
QUEST_FREEDOM_ALL_CREATURES
SPELL_MANA_BURN
SPELL_SHOOT
SPELL_MULTI_SHOT
Definition at line 324 of file feralas.cpp.
Function Documentation
AddSC_feralas()
void AddSC_feralas ()
Definition at line 627 of file feralas.cpp.
References EffectDummyCreature_npc_shay_leafrunner(), Script::GetAI, GetAI_npc_captured_sprite_darter(), GetAI_npc_kindal_moonweaver(), GetAI_npc_oox22fe(), GetAI_npc_shay_leafrunner(), GOUse_go_cage_door(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_kindal_moonweaver(), QuestAccept_npc_oox22fe(), QuestAccept_npc_shay_leafrunner(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_shay_leafrunner()
bool EffectDummyCreature_npc_shay_leafrunner (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 306 of file feralas.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, Object::GetTypeId(), UnitAI::SendAIEvent(), SPELL_SHAYS_BELL, and TYPEID_PLAYER.
Referenced by AddSC_feralas().
GetAI_npc_captured_sprite_darter()
UnitAI* GetAI_npc_captured_sprite_darter (Creature * pCreature)
Definition at line 395 of file feralas.cpp.
Referenced by AddSC_feralas().
GetAI_npc_kindal_moonweaver()
UnitAI* GetAI_npc_kindal_moonweaver (Creature * pCreature)
Definition at line 557 of file feralas.cpp.
Referenced by AddSC_feralas().
GetAI_npc_oox22fe()
UnitAI* GetAI_npc_oox22fe (Creature * pCreature)
Definition at line 138 of file feralas.cpp.
Referenced by AddSC_feralas().
GetAI_npc_shay_leafrunner()
UnitAI* GetAI_npc_shay_leafrunner (Creature * pCreature)
Definition at line 291 of file feralas.cpp.
Referenced by AddSC_feralas().
GOUse_go_cage_door()
bool GOUse_go_cage_door (Player * player, GameObject * go)
Definition at line 404 of file feralas.cpp.
References DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), IN_MILLISECONDS, IN_PROGRESS, MINUTE, NPC_CAPTURED_SPRITE_DARTER, NPC_GRIMTOTEM_RAIDER, NPC_KINDAL_MOONWEAVER, raiderSpawnPos, SAY_KINDAL_INITIAL_AGGRO, InstanceData::SetData(), WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, TEMPSPAWN_DEAD_DESPAWN, TYPE_FREEDOM_CREATURES, and Cell::VisitGridObjects().
Referenced by AddSC_feralas().
QuestAccept_npc_kindal_moonweaver()
bool QuestAccept_npc_kindal_moonweaver (Player * player, Creature * creature, const Quest * quest)
Definition at line 562 of file feralas.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_A_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_FREEDOM_ALL_CREATURES, SAY_KINDAL_QUEST_START, Unit::SetImmuneToNPC(), Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
Referenced by AddSC_feralas().
QuestAccept_npc_oox22fe()
bool QuestAccept_npc_oox22fe (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 143 of file feralas.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, Quest::GetQuestId(), QUEST_RESCUE_OOX22FE, SAY_OOX_START, WorldObject::SetActiveObjectState(), Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_feralas().
QuestAccept_npc_shay_leafrunner()
bool QuestAccept_npc_shay_leafrunner (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 296 of file feralas.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, DoScriptText(), Quest::GetQuestId(), QUEST_ID_WANDERING_SHAY, SAY_ESCORT_START, and UnitAI::SendAIEvent().
Referenced by AddSC_feralas().
Variable Documentation
raiderSpawnPos
const float raiderSpawnPos[4] = { -4515.35f, 811.36f, 62.99f, 3.60244f } static
Definition at line 341 of file feralas.cpp.
Referenced by GOUse_go_cage_door().