CMaNGOS_WoTLK: ghostlands.cpp File Reference
ghostlands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_ranger_lilathaAI
Enumerations
enum {
SAY_START = 15894 , SAY_PROGRESS1 = 12187 , SAY_PROGRESS2 = 12188 , SAY_PROGRESS3 = 12189 ,
SAY_END1 = 12191 , SAY_END2 = 12190 , CAPTAIN_ANSWER = 12193 , WAYPOINT_PATH_ID = 16295 ,
QUEST_CATACOMBS = 9212 , GO_CAGE = 181152 , NPC_CAPTAIN_HELIOS = 16220 , NPC_MUMMIFIED_HEADHUNTER = 16342 ,
NPC_SHADOWPINE_ORACLE = 16343
}
Functions
bool QuestAccept_npc_ranger_lilatha (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_ghostlands ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_PROGRESS1
SAY_PROGRESS2
SAY_PROGRESS3
SAY_END1
SAY_END2
CAPTAIN_ANSWER
WAYPOINT_PATH_ID
QUEST_CATACOMBS
GO_CAGE
NPC_CAPTAIN_HELIOS
NPC_MUMMIFIED_HEADHUNTER
NPC_SHADOWPINE_ORACLE
Definition at line 35 of file ghostlands.cpp.
Function Documentation
AddSC_ghostlands()
void AddSC_ghostlands ()
Definition at line 166 of file ghostlands.cpp.
References Script::GetAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_ranger_lilatha(), and Script::RegisterSelf().
Referenced by AddScripts().
QuestAccept_npc_ranger_lilatha()
bool QuestAccept_npc_ranger_lilatha (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 150 of file ghostlands.cpp.
References Creature::AI(), DoBroadcastText(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_CATACOMBS, Object::RemoveFlag(), SAY_START, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, UNIT_STAND_STATE_STAND, and WAYPOINT_PATH_ID.
Referenced by AddSC_ghostlands().