CMaNGOS_WoTLK: gnomeregan.cpp File Reference
gnomeregan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "gnomeregan.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
Data Structures
struct sSummonInformation
struct npc_blastmaster_emi_shortfuseAI
struct npc_kernobeeAI
Enumerations
enum {
SAY_START = -1090000 , SAY_INTRO_1 = -1090001 , SAY_INTRO_2 = -1090002 , SAY_INTRO_3 = -1090003 ,
SAY_INTRO_4 = -1090004 , SAY_LOOK_1 = -1090005 , SAY_HEAR_1 = -1090006 , SAY_AGGRO_1 = -1090007 ,
SAY_CHARGE_1 = -1090008 , SAY_CHARGE_2 = -1090009 , SAY_BLOW_1_10 = -1090010 , SAY_BLOW_1_5 = -1090011 ,
SAY_BLOW_1 = -1090012 , SAY_FINISH_1 = -1090013 , SAY_LOOK_2 = -1090014 , SAY_HEAR_2 = -1090015 ,
SAY_CHARGE_3 = -1090016 , SAY_CHARGE_4 = -1090017 , SAY_BLOW_2_10 = -1090018 , SAY_BLOW_2_5 = -1090019 ,
SAY_BLOW_SOON = -1090020 , SAY_BLOW_2 = -1090021 , SAY_FINISH_2 = -1090022 , SAY_AGGRO_2 = -1090028 ,
SAY_GRUBBIS_SPAWN = -1090023 , GOSSIP_ITEM_START = -3090000 , SPELL_EXPLOSION_NORTH = 12158 , SPELL_EXPLOSION_SOUTH = 12159 ,
SPELL_FIREWORKS_RED = 11542 , MAX_SUMMON_POSITIONS = 33 , NPC_GRUBBIS = 7361 , NPC_CHOMPER = 6215 ,
NPC_CAVERNDEEP_BURROWER = 6206 , NPC_CAVERNDEEP_AMBUSHER = 6207
}
enum { QUEST_A_FINE_MESS = 2904 , TRIGGER_GNOME_EXIT = 324 }
Functions
UnitAI * GetAI_npc_blastmaster_emi_shortfuse (Creature *pCreature)
bool GossipHello_npc_blastmaster_emi_shortfuse (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_blastmaster_emi_shortfuse (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_kernobee (Creature *pCreature)
bool QuestAccept_npc_kernobee (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_gnomeregan ()
Variables
static const sSummonInformation asSummonInfo [MAX_SUMMON_POSITIONS]
static const float aKernobeePositions [2][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_INTRO_1
SAY_INTRO_2
SAY_INTRO_3
SAY_INTRO_4
SAY_LOOK_1
SAY_HEAR_1
SAY_AGGRO_1
SAY_CHARGE_1
SAY_CHARGE_2
SAY_BLOW_1_10
SAY_BLOW_1_5
SAY_BLOW_1
SAY_FINISH_1
SAY_LOOK_2
SAY_HEAR_2
SAY_CHARGE_3
SAY_CHARGE_4
SAY_BLOW_2_10
SAY_BLOW_2_5
SAY_BLOW_SOON
SAY_BLOW_2
SAY_FINISH_2
SAY_AGGRO_2
SAY_GRUBBIS_SPAWN
GOSSIP_ITEM_START
SPELL_EXPLOSION_NORTH
SPELL_EXPLOSION_SOUTH
SPELL_FIREWORKS_RED
MAX_SUMMON_POSITIONS
NPC_GRUBBIS
NPC_CHOMPER
NPC_CAVERNDEEP_BURROWER
NPC_CAVERNDEEP_AMBUSHER
Definition at line 38 of file gnomeregan.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_A_FINE_MESS
TRIGGER_GNOME_EXIT
Definition at line 635 of file gnomeregan.cpp.
Function Documentation
AddSC_gnomeregan()
void AddSC_gnomeregan ()
Definition at line 706 of file gnomeregan.cpp.
References Script::GetAI, GetAI_npc_blastmaster_emi_shortfuse(), GetAI_npc_kernobee(), GossipHello_npc_blastmaster_emi_shortfuse(), GossipSelect_npc_blastmaster_emi_shortfuse(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_kernobee(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_blastmaster_emi_shortfuse()
UnitAI* GetAI_npc_blastmaster_emi_shortfuse (Creature * pCreature)
Definition at line 594 of file gnomeregan.cpp.
Referenced by AddSC_gnomeregan().
GetAI_npc_kernobee()
UnitAI* GetAI_npc_kernobee (Creature * pCreature)
Definition at line 693 of file gnomeregan.cpp.
Referenced by AddSC_gnomeregan().
GossipHello_npc_blastmaster_emi_shortfuse()
bool GossipHello_npc_blastmaster_emi_shortfuse (Player * pPlayer, Creature * pCreature)
Definition at line 599 of file gnomeregan.cpp.
References FAIL, Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_START, GOSSIP_SENDER_MAIN, NOT_STARTED, and TYPE_GRUBBIS.
Referenced by AddSC_gnomeregan().
GossipSelect_npc_blastmaster_emi_shortfuse()
bool GossipSelect_npc_blastmaster_emi_shortfuse (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 612 of file gnomeregan.cpp.
References Creature::AI(), FAIL, WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, NOT_STARTED, and TYPE_GRUBBIS.
Referenced by AddSC_gnomeregan().
QuestAccept_npc_kernobee()
bool QuestAccept_npc_kernobee (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 698 of file gnomeregan.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, Quest::GetQuestId(), QUEST_A_FINE_MESS, and UnitAI::SendAIEvent().
Referenced by AddSC_gnomeregan().
Variable Documentation
aKernobeePositions
const float aKernobeePositions[2][3] static
Initial value:
=
{
    { -330.92f, -3.03f, -152.85f},
    { -297.32f, -7.32f, -152.85f}
}
Definition at line 641 of file gnomeregan.cpp.
Referenced by npc_kernobeeAI::UpdateFollowerAI().
asSummonInfo
const sSummonInformation asSummonInfo[MAX_SUMMON_POSITIONS] static
Definition at line 88 of file gnomeregan.cpp.
Referenced by npc_blastmaster_emi_shortfuseAI::DoSummonPack().