CMaNGOS_WoTLK: go_scripts.cpp File Reference
go_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "GameEvents/GameEventMgr.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "Entities/TemporarySpawn.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
Data Structures
struct npc_ethereum_prisonerAI
struct go_ai_bell
struct go_ai_dmf_music
struct go_brewfest_music
struct go_midsummer_music
struct go_pirate_day_music
struct go_elemental_rift
struct go_fel_cannonball_stack_trap
struct go_dragon_head
struct go_unadorned_spike
struct go_containment
struct go_aura_generator
struct go_ai_ectoplasmic_distiller_trap
Enumerations
enum {
FACTION_LC = 1011 , FACTION_SHAT = 935 , FACTION_CE = 942 , FACTION_CON = 933 ,
FACTION_KT = 989 , FACTION_SPOR = 970 , SPELL_REP_LC = 39456 , SPELL_REP_SHAT = 39457 ,
SPELL_REP_CE = 39460 , SPELL_REP_CON = 39474 , SPELL_REP_KT = 39475 , SPELL_REP_SPOR = 39476 ,
SAY_LC = -1000176 , SAY_SHAT = -1000177 , SAY_CE = -1000178 , SAY_CON = -1000179 ,
SAY_KT = -1000180 , SAY_SPOR = -1000181 , NPC_PRISONER = 20520 , NPC_FORGOSH = 20788 ,
NPC_THUK = 22920 , NPC_PRISONER_GROUP = 20889 , NPC_TRELOPADES = 22828 , SPELL_C_C_D = 35465 ,
SPELL_PURPLE_BANISH_STATE = 32566 , SPELL_SHADOWFORM_1 = 39579 , SPELL_SHADOWFORM_2 = 37816 , FACTION_HOSTILE = 14 ,
SAY_TRELOPADES_AGGRO_1 = -1015029 , SAY_TRELOPADES_AGGRO_2 = -1015030
}
enum StasisType { EVENT_PRISON = 0 , EVENT_PRISON_ALPHA = 1 , EVENT_PRISON_GROUP = 2 }
enum PrisonerActions {
PRISONER_ATTACK , PRISONER_TALK , PRISONER_CAST , PRISONER_CREDIT ,
PRISONER_ATTACK , PRISONER_TALK , PRISONER_CAST
}
enum { SPELL_JUMP_A_TRON = 33382 , NPC_JUMP_A_TRON = 19041 }
enum { SPELL_SUMMON_DEEP_JORMUNGAR = 66510 , SPELL_SUMMON_MOLE_MACHINE = 66492 , SPELL_SUMMON_MARAUDER = 66491 }
enum { QUEST_LEARN_LEAVE_RETURN = 12790 , QUEST_TELE_CRYSTAL_FLAG = 12845 }
enum {
QUEST_ALL_ALONG_THE_WATCHTOWERS_ALLIANCE = 5097 , QUEST_ALL_ALONG_THE_WATCHTOWERS_HORDE = 5098 , NPC_ANDORHAL_TOWER_1 = 10902 , NPC_ANDORHAL_TOWER_2 = 10903 ,
NPC_ANDORHAL_TOWER_3 = 10904 , NPC_ANDORHAL_TOWER_4 = 10905 , GO_ANDORHAL_TOWER_1 = 176094 , GO_ANDORHAL_TOWER_2 = 176095 ,
GO_ANDORHAL_TOWER_3 = 176096 , GO_ANDORHAL_TOWER_4 = 176097
}
enum { SPELL_GYMER_LOCK_EXPLOSION = 55529 , NPC_GYMER_LOCK_DUMMY = 29928 }
enum { EVENT_ID_BELLS = 1024 }
enum BellHourlySoundFX {
BELLTOLLTRIBAL = 6595 , BELLTOLLHORDE = 6675 , BELLTOLLALLIANCE = 6594 , BELLTOLLNIGHTELF = 6674 ,
BELLTOLLDWARFGNOME = 7234 , BELLTOLLKARAZHAN = 9154
}
enum BellHourlySoundAreas {
TELDRASSIL_ZONE = 141 , TARREN_MILL_AREA = 272 , KARAZHAN_MAPID = 532 , IRONFORGE_1_AREA = 809 ,
BRILL_AREA = 2118 , UNDERCITY_AREA = 1497 , STORMWIND_AREA = 1519 , IRONFORGE_2_AREA = 1537 ,
DARNASSUS_AREA = 1657
}
enum BellHourlyObjects { GO_HORDE_BELL = 175885 , GO_ALLIANCE_BELL = 176573 , GO_KARAZHAN_BELL = 182064 }
enum { MUSIC_DARKMOON_FAIRE_MUSIC = 8440 }
enum BrewfestMusic {
EVENT_BREWFESTDWARF01 = 11810 , EVENT_BREWFESTDWARF02 = 11812 , EVENT_BREWFESTDWARF03 = 11813 , EVENT_BREWFESTGOBLIN01 = 11811 ,
EVENT_BREWFESTGOBLIN02 = 11814 , EVENT_BREWFESTGOBLIN03 = 11815
}
enum BrewfestMusicTime : int32 {
EVENT_BREWFESTDWARF01_TIME = 95000 , EVENT_BREWFESTDWARF02_TIME = 155000 , EVENT_BREWFESTDWARF03_TIME = 23000 , EVENT_BREWFESTGOBLIN01_TIME = 68000 ,
EVENT_BREWFESTGOBLIN02_TIME = 93000 , EVENT_BREWFESTGOBLIN03_TIME = 28000
}
enum BrewfestMusicAreas {
SILVERMOON = 3430 , UNDERCITY = 1497 , ORGRIMMAR_1 = 1296 , ORGRIMMAR_2 = 14 ,
THUNDERBLUFF = 1638 , IRONFORGE_1 = 809 , IRONFORGE_2 = 1 , STORMWIND = 12 ,
EXODAR = 3557 , DARNASSUS = 1657 , SHATTRATH = 3703
}
enum BrewfestMusicEvents { EVENT_BM_SELECT_MUSIC = 1 , EVENT_BM_START_MUSIC = 2 }
enum MidsummerMusic { EVENTMIDSUMMERFIREFESTIVAL_A = 12319 , EVENTMIDSUMMERFIREFESTIVAL_H = 12325 }
enum MidsummerMusicEvents { EVENT_MM_START_MUSIC = 1 }
enum PirateDayMusic { MUSIC_PIRATE_DAY_MUSIC = 12845 }
enum PirateDayMusicEvents { EVENT_PDM_START_MUSIC = 1 }
enum { ITEM_GOBLIN_TRANSPONDER = 9173 }
enum {
NPC_WHIRLING_INVADER = 14455 , NPC_WATERY_INVADER = 14458 , NPC_BLAZING_INVADER = 14460 , NPC_THUNDERING_INVADER = 14462 ,
GO_EARTH_ELEMENTAL_RIFT = 179664 , GO_WATER_ELEMENTAL_RIFT = 179665 , GO_FIRE_ELEMENTAL_RIFT = 179666 , GO_AIR_ELEMENTAL_RIFT = 179667
}
enum { SPELL_BOMBING_RUN_DUMMY_SUMMON = 40181 , NPC_BOMBING_RUN_TARGET_BUNNY = 23118 }
enum {
SPELL_RALLYING_CRY_OF_THE_DRAGONSLAYER = 22888 , NPC_OVERLORD_RUNTHAK = 14392 , NPC_MAJOR_MATTINGLY = 14394 , NPC_HIGH_OVERLORD_SAURFANG = 14720 ,
NPC_FIELD_MARSHAL_AFRASIABI = 14721 , GO_ONYXIA_H = 179556 , GO_ONYXIA_A = 179558 , GO_NEFARIAN_H = 179881 ,
GO_NEFARIAN_A = 179882
}
enum { SPELL_WARCHIEFS_BLESSING = 16609 , NPC_THRALL = 4949 }
enum { NPC_RIFT_SPAWN = 6492 }
Functions
bool GOUse_go_ethereum_prison (Player *player, GameObject *go)
bool GOUse_go_ethereum_stasis (Player *player, GameObject *go)
bool GOUse_go_stasis_chamber_alpha (Player *player, GameObject *go)
bool GOUse_go_jump_a_tron (Player *pPlayer, GameObject *pGo)
bool GOUse_go_mysterious_snow_mound (Player *pPlayer, GameObject *pGo)
bool GOUse_go_tele_to_dalaran_crystal (Player *pPlayer, GameObject *)
bool GOUse_go_tele_to_violet_stand (Player *pPlayer, GameObject *)
bool GOUse_go_andorhal_tower (Player *pPlayer, GameObject *pGo)
bool GOUse_go_scourge_enclosure (Player *pPlayer, GameObject *pGo)
GameObjectAI * GetAI_go_bells (GameObject *go)
GameObjectAI * GetAI_go_darkmoon_faire_music (GameObject *go)
GameObjectAI * GetAIgo_brewfest_music (GameObject *go)
GameObjectAI * GetAIgo_midsummer_music (GameObject *go)
GameObjectAI * GetAIgo_pirate_day_music (GameObject *go)
bool TrapTargetSearch (Unit *unit)
GameObjectAI * GetAI_go_elemental_rift (GameObject *go)
GameObjectAI * GetAI_go_fel_cannonball_stack_trap (GameObject *go)
GameObjectAI * GetAI_go_dragon_head (GameObject *go)
GameObjectAI * GetAI_go_unadorned_spike (GameObject *go)
GameObjectAI * GetAI_go_containment (GameObject *go)
void AddSC_go_scripts ()
Variables
const uint32 npcPrisonEntry []
const uint32 npcStasisEntry []
std::function< bool(Unit *)> function = &TrapTargetSearch
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FACTION_LC
FACTION_SHAT
FACTION_CE
FACTION_CON
FACTION_KT
FACTION_SPOR
SPELL_REP_LC
SPELL_REP_SHAT
SPELL_REP_CE
SPELL_REP_CON
SPELL_REP_KT
SPELL_REP_SPOR
SAY_LC
SAY_SHAT
SAY_CE
SAY_CON
SAY_KT
SAY_SPOR
NPC_PRISONER
NPC_FORGOSH
NPC_THUK
NPC_PRISONER_GROUP
NPC_TRELOPADES
SPELL_C_C_D
SPELL_PURPLE_BANISH_STATE
SPELL_SHADOWFORM_1
SPELL_SHADOWFORM_2
FACTION_HOSTILE
SAY_TRELOPADES_AGGRO_1
SAY_TRELOPADES_AGGRO_2
Definition at line 46 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_JUMP_A_TRON
NPC_JUMP_A_TRON
Definition at line 267 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_DEEP_JORMUNGAR
SPELL_SUMMON_MOLE_MACHINE
SPELL_SUMMON_MARAUDER
Definition at line 285 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_LEARN_LEAVE_RETURN
QUEST_TELE_CRYSTAL_FLAG
Definition at line 315 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ALL_ALONG_THE_WATCHTOWERS_ALLIANCE
QUEST_ALL_ALONG_THE_WATCHTOWERS_HORDE
NPC_ANDORHAL_TOWER_1
NPC_ANDORHAL_TOWER_2
NPC_ANDORHAL_TOWER_3
NPC_ANDORHAL_TOWER_4
GO_ANDORHAL_TOWER_1
GO_ANDORHAL_TOWER_2
GO_ANDORHAL_TOWER_3
GO_ANDORHAL_TOWER_4
Definition at line 343 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GYMER_LOCK_EXPLOSION
NPC_GYMER_LOCK_DUMMY
Definition at line 379 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
EVENT_ID_BELLS
Definition at line 404 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
MUSIC_DARKMOON_FAIRE_MUSIC
Definition at line 575 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
ITEM_GOBLIN_TRANSPONDER
Definition at line 861 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_WHIRLING_INVADER
NPC_WATERY_INVADER
NPC_BLAZING_INVADER
NPC_THUNDERING_INVADER
GO_EARTH_ELEMENTAL_RIFT
GO_WATER_ELEMENTAL_RIFT
GO_FIRE_ELEMENTAL_RIFT
GO_AIR_ELEMENTAL_RIFT
Definition at line 882 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BOMBING_RUN_DUMMY_SUMMON
NPC_BOMBING_RUN_TARGET_BUNNY
Definition at line 958 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RALLYING_CRY_OF_THE_DRAGONSLAYER
NPC_OVERLORD_RUNTHAK
NPC_MAJOR_MATTINGLY
NPC_HIGH_OVERLORD_SAURFANG
NPC_FIELD_MARSHAL_AFRASIABI
GO_ONYXIA_H
GO_ONYXIA_A
GO_NEFARIAN_H
GO_NEFARIAN_A
Definition at line 989 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_WARCHIEFS_BLESSING
NPC_THRALL
Definition at line 1030 of file go_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_RIFT_SPAWN
Definition at line 1060 of file go_scripts.cpp.
BellHourlyObjects
enum BellHourlyObjects
Enumerator
GO_HORDE_BELL
GO_ALLIANCE_BELL
GO_KARAZHAN_BELL
Definition at line 436 of file go_scripts.cpp.
BellHourlySoundAreas
enum BellHourlySoundAreas
Enumerator
TELDRASSIL_ZONE
TARREN_MILL_AREA
KARAZHAN_MAPID
IRONFORGE_1_AREA
BRILL_AREA
UNDERCITY_AREA
STORMWIND_AREA
IRONFORGE_2_AREA
DARNASSUS_AREA
Definition at line 420 of file go_scripts.cpp.
BellHourlySoundFX
enum BellHourlySoundFX
Enumerator
BELLTOLLTRIBAL
BELLTOLLHORDE
BELLTOLLALLIANCE
BELLTOLLNIGHTELF
BELLTOLLDWARFGNOME
BELLTOLLKARAZHAN
Definition at line 410 of file go_scripts.cpp.
BrewfestMusic
enum BrewfestMusic
Enumerator
EVENT_BREWFESTDWARF01
EVENT_BREWFESTDWARF02
EVENT_BREWFESTDWARF03
EVENT_BREWFESTGOBLIN01
EVENT_BREWFESTGOBLIN02
EVENT_BREWFESTGOBLIN03
Definition at line 610 of file go_scripts.cpp.
BrewfestMusicAreas
enum BrewfestMusicAreas
Enumerator
SILVERMOON
UNDERCITY
ORGRIMMAR_1
ORGRIMMAR_2
THUNDERBLUFF
IRONFORGE_1
IRONFORGE_2
STORMWIND
EXODAR
DARNASSUS
SHATTRATH
Definition at line 631 of file go_scripts.cpp.
BrewfestMusicEvents
enum BrewfestMusicEvents
Enumerator
EVENT_BM_SELECT_MUSIC
EVENT_BM_START_MUSIC
Definition at line 646 of file go_scripts.cpp.
BrewfestMusicTime
enum BrewfestMusicTime : int32
Enumerator
EVENT_BREWFESTDWARF01_TIME
EVENT_BREWFESTDWARF02_TIME
EVENT_BREWFESTDWARF03_TIME
EVENT_BREWFESTGOBLIN01_TIME
EVENT_BREWFESTGOBLIN02_TIME
EVENT_BREWFESTGOBLIN03_TIME
Definition at line 621 of file go_scripts.cpp.
MidsummerMusic
enum MidsummerMusic
Enumerator
EVENTMIDSUMMERFIREFESTIVAL_A
EVENTMIDSUMMERFIREFESTIVAL_H
Definition at line 771 of file go_scripts.cpp.
MidsummerMusicEvents
enum MidsummerMusicEvents
Enumerator
EVENT_MM_START_MUSIC
Definition at line 777 of file go_scripts.cpp.
PirateDayMusic
enum PirateDayMusic
Enumerator
MUSIC_PIRATE_DAY_MUSIC
Definition at line 822 of file go_scripts.cpp.
PirateDayMusicEvents
enum PirateDayMusicEvents
Enumerator
EVENT_PDM_START_MUSIC
Definition at line 827 of file go_scripts.cpp.
PrisonerActions
enum PrisonerActions
Enumerator
PRISONER_ATTACK
PRISONER_TALK
PRISONER_CAST
PRISONER_CREDIT
PRISONER_ATTACK
PRISONER_TALK
PRISONER_CAST
Definition at line 98 of file go_scripts.cpp.
StasisType
enum StasisType
Enumerator
EVENT_PRISON
EVENT_PRISON_ALPHA
EVENT_PRISON_GROUP
Definition at line 91 of file go_scripts.cpp.
Function Documentation
AddSC_go_scripts()
void AddSC_go_scripts ()
Definition at line 1208 of file go_scripts.cpp.
References Script::GetAI, GetAI_go_bells(), GetAI_go_containment(), GetAI_go_darkmoon_faire_music(), GetAI_go_dragon_head(), GetAI_go_elemental_rift(), GetAI_go_fel_cannonball_stack_trap(), GetAI_go_unadorned_spike(), GetAIgo_brewfest_music(), GetAIgo_midsummer_music(), GetAIgo_pirate_day_music(), Script::GetGameObjectAI, GOUse_go_andorhal_tower(), GOUse_go_ethereum_prison(), GOUse_go_ethereum_stasis(), GOUse_go_jump_a_tron(), GOUse_go_mysterious_snow_mound(), GOUse_go_scourge_enclosure(), GOUse_go_stasis_chamber_alpha(), GOUse_go_tele_to_dalaran_crystal(), GOUse_go_tele_to_violet_stand(), Script::Name, Script::pGOUse, Script::pTrapSearching, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_go_bells()
GameObjectAI* GetAI_go_bells (GameObject * go)
Definition at line 566 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_containment()
GameObjectAI* GetAI_go_containment (GameObject * go)
Definition at line 1092 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_darkmoon_faire_music()
GameObjectAI* GetAI_go_darkmoon_faire_music (GameObject * go)
Definition at line 601 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_dragon_head()
GameObjectAI* GetAI_go_dragon_head (GameObject * go)
Definition at line 1025 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_elemental_rift()
GameObjectAI* GetAI_go_elemental_rift (GameObject * go)
Definition at line 951 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_fel_cannonball_stack_trap()
GameObjectAI* GetAI_go_fel_cannonball_stack_trap (GameObject * go)
Definition at line 984 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAI_go_unadorned_spike()
GameObjectAI* GetAI_go_unadorned_spike (GameObject * go)
Definition at line 1051 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAIgo_brewfest_music()
GameObjectAI* GetAIgo_brewfest_music (GameObject * go)
Definition at line 762 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAIgo_midsummer_music()
GameObjectAI* GetAIgo_midsummer_music (GameObject * go)
Definition at line 813 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GetAIgo_pirate_day_music()
GameObjectAI* GetAIgo_pirate_day_music (GameObject * go)
Definition at line 856 of file go_scripts.cpp.
Referenced by AddSC_go_scripts().
GOUse_go_andorhal_tower()
bool GOUse_go_andorhal_tower (Player * pPlayer, GameObject * pGo)
Definition at line 357 of file go_scripts.cpp.
References Object::GetEntry(), Player::GetQuestStatus(), GO_ANDORHAL_TOWER_1, GO_ANDORHAL_TOWER_2, GO_ANDORHAL_TOWER_3, GO_ANDORHAL_TOWER_4, Player::KilledMonsterCredit(), NPC_ANDORHAL_TOWER_1, NPC_ANDORHAL_TOWER_2, NPC_ANDORHAL_TOWER_3, NPC_ANDORHAL_TOWER_4, QUEST_ALL_ALONG_THE_WATCHTOWERS_ALLIANCE, QUEST_ALL_ALONG_THE_WATCHTOWERS_HORDE, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_go_scripts().
GOUse_go_ethereum_prison()
bool GOUse_go_ethereum_prison (Player * player, GameObject * go)
Definition at line 226 of file go_scripts.cpp.
References EVENT_PRISON, GetClosestCreatureWithEntry(), NPC_PRISONER, and npc_ethereum_prisonerAI::StartEvent().
Referenced by AddSC_go_scripts().
GOUse_go_ethereum_stasis()
bool GOUse_go_ethereum_stasis (Player * player, GameObject * go)
Definition at line 241 of file go_scripts.cpp.
References EVENT_PRISON_GROUP, GetClosestCreatureWithEntry(), NPC_PRISONER_GROUP, and npc_ethereum_prisonerAI::StartEvent().
Referenced by AddSC_go_scripts().
GOUse_go_jump_a_tron()
bool GOUse_go_jump_a_tron (Player * pPlayer, GameObject * pGo)
Definition at line 273 of file go_scripts.cpp.
References GetClosestCreatureWithEntry(), INTERACTION_DISTANCE, NPC_JUMP_A_TRON, SPELL_JUMP_A_TRON, and TRIGGERED_NONE.
Referenced by AddSC_go_scripts().
GOUse_go_mysterious_snow_mound()
bool GOUse_go_mysterious_snow_mound (Player * pPlayer, GameObject * pGo)
Definition at line 292 of file go_scripts.cpp.
References Unit::CastSpell(), GO_JUST_DEACTIVATED, GameObject::SetLootState(), SPELL_SUMMON_DEEP_JORMUNGAR, SPELL_SUMMON_MARAUDER, SPELL_SUMMON_MOLE_MACHINE, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by AddSC_go_scripts().
GOUse_go_scourge_enclosure()
bool GOUse_go_scourge_enclosure (Player * pPlayer, GameObject * pGo)
Definition at line 385 of file go_scripts.cpp.
References GetCreatureListWithEntryInGrid(), Player::KilledMonsterCredit(), NPC_GYMER_LOCK_DUMMY, SPELL_GYMER_LOCK_EXPLOSION, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_go_scripts().
GOUse_go_stasis_chamber_alpha()
bool GOUse_go_stasis_chamber_alpha (Player * player, GameObject * go)
Definition at line 252 of file go_scripts.cpp.
References EVENT_PRISON_ALPHA, GetClosestCreatureWithEntry(), NPC_PRISONER_GROUP, and npc_ethereum_prisonerAI::StartEvent().
Referenced by AddSC_go_scripts().
GOUse_go_tele_to_dalaran_crystal()
bool GOUse_go_tele_to_dalaran_crystal (Player * pPlayer, GameObject *)
Definition at line 321 of file go_scripts.cpp.
References Player::GetQuestRewardStatus(), and QUEST_TELE_CRYSTAL_FLAG.
Referenced by AddSC_go_scripts().
GOUse_go_tele_to_violet_stand()
bool GOUse_go_tele_to_violet_stand (Player * pPlayer, GameObject *)
Definition at line 334 of file go_scripts.cpp.
References Player::GetQuestRewardStatus(), Player::GetQuestStatus(), QUEST_LEARN_LEAVE_RETURN, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_go_scripts().
TrapTargetSearch()
bool TrapTargetSearch (Unit * unit)
Definition at line 866 of file go_scripts.cpp.
References Object::GetTypeId(), Player::HasItemCount(), ITEM_GOBLIN_TRANSPONDER, and TYPEID_PLAYER.
Variable Documentation
function
std::function<bool(Unit*)> function = &TrapTargetSearch
Definition at line 956 of file go_scripts.cpp.
Referenced by Messager< T >::Execute(), GameObject::Update(), and GameObject::Use().
npcPrisonEntry
const uint32 npcPrisonEntry[]
Initial value:
=
{
    22810, 22811, 22812, 22813, 22814, 22815,
    20783, 20784, 20785, 20786, 20788, 20789, 20790
}
Definition at line 105 of file go_scripts.cpp.
Referenced by npc_ethereum_prisonerAI::StartEvent().
npcStasisEntry
const uint32 npcStasisEntry[]
Initial value:
=
{
    22825, 20888, 22827, 22826, 22828
}
Definition at line 111 of file go_scripts.cpp.
Referenced by npc_ethereum_prisonerAI::StartEvent().