CMaNGOS_WoTLK: GridNotifiersImpl.h File Reference
GridNotifiersImpl.h File Reference
#include "Grids/GridNotifiers.h"
#include "Server/WorldPacket.h"
#include "Entities/Player.h"
#include "AI/BaseAI/UnitAI.h"
#include "Spells/SpellAuras.h"
#include "Server/DBCEnums.h"
#include "Server/DBCStores.h"
#include "Server/SQLStorages.h"
#include "Spells/SpellMgr.h"
Functions
void UnitVisitObjectsNotifierWorker (Unit *unitA, Unit *unitB)
void PlayerVisitCreatureWorker (Player *pl, Creature *c)
void PlayerVisitPlayerWorker (Player *p1, Player *p2)
void CreatureVisitCreatureWorker (Creature *c1, Creature *c2)
Function Documentation
CreatureVisitCreatureWorker()
void CreatureVisitCreatureWorker (Creature * c1, Creature * c2) inline
Definition at line 88 of file GridNotifiersImpl.h.
References Creature::AI(), Unit::GetCombatManager(), Unit::hasUnitState(), CombatManager::IsInEvadeMode(), UnitAI::IsVisible(), UnitAI::MoveInLineOfSight(), and UNIT_STAT_LOST_CONTROL.
PlayerVisitCreatureWorker()
void PlayerVisitCreatureWorker (Player * pl, Creature * c) inline
Definition at line 58 of file GridNotifiersImpl.h.
References Creature::AI(), Player::AI(), Unit::GetCombatManager(), Unit::hasUnitState(), CombatManager::IsInEvadeMode(), UnitAI::IsVisible(), UnitAI::MoveInLineOfSight(), and UNIT_STAT_LOST_CONTROL.
PlayerVisitPlayerWorker()
void PlayerVisitPlayerWorker (Player * p1, Player * p2) inline
Definition at line 73 of file GridNotifiersImpl.h.
References Player::AI(), Unit::GetCombatManager(), Unit::hasUnitState(), CombatManager::IsInEvadeMode(), UnitAI::IsVisible(), UnitAI::MoveInLineOfSight(), and UNIT_STAT_LOST_CONTROL.
UnitVisitObjectsNotifierWorker()
void UnitVisitObjectsNotifierWorker (Unit * unitA, Unit * unitB) inline
Definition at line 48 of file GridNotifiersImpl.h.
References Unit::AI(), Unit::GetCombatManager(), Unit::hasUnitState(), CombatManager::IsInEvadeMode(), UnitAI::IsVisible(), UnitAI::MoveInLineOfSight(), and UNIT_STAT_LOST_CONTROL.
Referenced by MaNGOS::PlayerVisitObjectsNotifier::Visit(), and MaNGOS::CreatureVisitObjectsNotifier::Visit().