CMaNGOS_WoTLK: grizzly_hills.cpp File Reference
grizzly_hills.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "Entities/Vehicle.h"
Data Structures
struct npc_depleted_war_golemAI
struct npc_harrison_jonesAI
struct npc_emilyAI
struct spell_eagle_eyes
struct spell_escape_from_silverbrook_credit_master
struct spell_tag_troll
struct spell_out_cold
struct spell_assemble_cage
struct MoltenFuryFlamebringer
Enumerations
enum {
SAY_GOLEM_CHARGE = -1000626 , SAY_GOLEM_COMPLETE = -1000627 , NPC_LIGHTNING_SENTRY = 26407 , SPELL_CHARGE_GOLEM = 47799 ,
SPELL_GOLEM_CHARGE_CREDIT = 47797
}
enum {
SAY_HARRISON_ESCORT_START = -1001053 , SAY_HARRISON_CHAMBER_1 = -1001054 , SAY_HARRISON_CHAMBER_2 = -1001055 , SAY_HARRISON_CHAMBER_RELEASE = -1001056 ,
SAY_ADARRAH_THANK_YOU = -1001057 , SAY_HARRISON_CHAMBER_3 = -1001058 , SAY_HARRISON_CHAMBER_4 = -1001059 , SAY_HARRISON_CHAMBER_5 = -1001060 ,
SAY_HARRISON_CHAMBER_6 = -1001061 , SAY_HARRISON_CHAMBER_7 = -1001062 , SAY_HARRISON_ESCORT_COMPELTE = -1001063 , QUEST_ID_DUN_DA_DUN_TAH = 12082 ,
NPC_ADARRAH = 24405 , NPC_TECAHUNA = 26865 , NPC_MUMMY_EFFECT_BUNNY = 26867 , NPC_ANCIENT_DRAKKARI_KING = 26871 ,
SPELL_BUNNY_IMMOLATION = 48150 , SPELL_GONG_EFFECT = 47730 , SPELL_TECAHUNA_SPIRIT_BEAM = 47601 , SPELL_SUMMON_DRAKKARI_KING = 47602 ,
GO_HARRISON_CAGE = 188465 , GO_ADARRAH_CAGE = 188487 , GO_FIRE_DOOR = 188480
}
enum {
SAY_ESCORT_START = -1001173 , SAY_FIRST_WOLF = -1001174 , SAY_FIRST_WOLF_ATTACK = -1001175 , SAY_HELP_FLOPPY_1 = -1001176 ,
SAY_FIRST_WOLF_DEFEAT = -1001177 , SAY_SECOND_WOLF = -1001178 , SAY_HELP_FLOPPY_2 = -1001179 , SAY_FLOPPY_ALMOST_DEAD = -1001180 ,
SAY_SECOND_WOLF_DEFEAT = -1001181 , SAY_RESUME_ESCORT = -1001182 , SAY_ESCORT_COMPLETE = -1001183 , SPELL_FLOPPY_BECOMES_LUNCH = 47184 ,
NPC_HUNGRY_WORG = 26586 , NPC_RAVENOUS_WORG = 26590 , NPC_MR_FLOPPY = 26589 , QUEST_ID_MR_FLOPPY_ADVENTURE = 12027
}
enum {
SAY_BUDD_TAG_TROLL = -1020009 , SPELL_BUDDS_ATTENTION = 47014 , SPELL_BUDDS_SNEAK = 47032 , SPELL_TAG_TROLL = 47031 ,
SPELL_OUT_COLD = 47035 , NPC_DRAKKARI_SHAMAN = 26447 , NPC_DRAKKARI_WARRIOR = 26425
}
Functions
UnitAI * GetAI_npc_depleted_war_golem (Creature *pCreature)
bool EffectAuraDummy_npc_depleted_war_golem (const Aura *pAura, bool bApply)
UnitAI * GetAI_npc_harrison_jones (Creature *pCreature)
bool QuestAccept_npc_harrison_jones (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_emily (Creature *pCreature)
bool QuestAccept_npc_emily (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_grizzly_hills ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GOLEM_CHARGE
SAY_GOLEM_COMPLETE
NPC_LIGHTNING_SENTRY
SPELL_CHARGE_GOLEM
SPELL_GOLEM_CHARGE_CREDIT
Definition at line 45 of file grizzly_hills.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_HARRISON_ESCORT_START
SAY_HARRISON_CHAMBER_1
SAY_HARRISON_CHAMBER_2
SAY_HARRISON_CHAMBER_RELEASE
SAY_ADARRAH_THANK_YOU
SAY_HARRISON_CHAMBER_3
SAY_HARRISON_CHAMBER_4
SAY_HARRISON_CHAMBER_5
SAY_HARRISON_CHAMBER_6
SAY_HARRISON_CHAMBER_7
SAY_HARRISON_ESCORT_COMPELTE
QUEST_ID_DUN_DA_DUN_TAH
NPC_ADARRAH
NPC_TECAHUNA
NPC_MUMMY_EFFECT_BUNNY
NPC_ANCIENT_DRAKKARI_KING
SPELL_BUNNY_IMMOLATION
SPELL_GONG_EFFECT
SPELL_TECAHUNA_SPIRIT_BEAM
SPELL_SUMMON_DRAKKARI_KING
GO_HARRISON_CAGE
GO_ADARRAH_CAGE
GO_FIRE_DOOR
Definition at line 112 of file grizzly_hills.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_FIRST_WOLF
SAY_FIRST_WOLF_ATTACK
SAY_HELP_FLOPPY_1
SAY_FIRST_WOLF_DEFEAT
SAY_SECOND_WOLF
SAY_HELP_FLOPPY_2
SAY_FLOPPY_ALMOST_DEAD
SAY_SECOND_WOLF_DEFEAT
SAY_RESUME_ESCORT
SAY_ESCORT_COMPLETE
SPELL_FLOPPY_BECOMES_LUNCH
NPC_HUNGRY_WORG
NPC_RAVENOUS_WORG
NPC_MR_FLOPPY
QUEST_ID_MR_FLOPPY_ADVENTURE
Definition at line 378 of file grizzly_hills.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_BUDD_TAG_TROLL
SPELL_BUDDS_ATTENTION
SPELL_BUDDS_SNEAK
SPELL_TAG_TROLL
SPELL_OUT_COLD
NPC_DRAKKARI_SHAMAN
NPC_DRAKKARI_WARRIOR
Definition at line 573 of file grizzly_hills.cpp.
Function Documentation
AddSC_grizzly_hills()
void AddSC_grizzly_hills ()
Definition at line 718 of file grizzly_hills.cpp.
References EffectAuraDummy_npc_depleted_war_golem(), Script::GetAI, GetAI_npc_depleted_war_golem(), GetAI_npc_emily(), GetAI_npc_harrison_jones(), Script::Name, Script::pEffectAuraDummy, Script::pQuestAcceptNPC, QuestAccept_npc_emily(), QuestAccept_npc_harrison_jones(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_npc_depleted_war_golem()
bool EffectAuraDummy_npc_depleted_war_golem (const Aura * pAura, bool bApply)
Definition at line 78 of file grizzly_hills.cpp.
References Unit::addUnitState(), Unit::CastSpell(), Unit::clearUnitState(), DoScriptText(), EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), Aura::GetTarget(), SAY_GOLEM_CHARGE, SAY_GOLEM_COMPLETE, SPELL_CHARGE_GOLEM, SPELL_GOLEM_CHARGE_CREDIT, TRIGGERED_OLD_TRIGGERED, and UNIT_STAT_STUNNED.
Referenced by AddSC_grizzly_hills().
GetAI_npc_depleted_war_golem()
UnitAI* GetAI_npc_depleted_war_golem (Creature * pCreature)
Definition at line 73 of file grizzly_hills.cpp.
Referenced by AddSC_grizzly_hills().
GetAI_npc_emily()
UnitAI* GetAI_npc_emily (Creature * pCreature)
Definition at line 522 of file grizzly_hills.cpp.
Referenced by AddSC_grizzly_hills().
GetAI_npc_harrison_jones()
UnitAI* GetAI_npc_harrison_jones (Creature * pCreature)
Definition at line 358 of file grizzly_hills.cpp.
Referenced by AddSC_grizzly_hills().
QuestAccept_npc_emily()
bool QuestAccept_npc_emily (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 527 of file grizzly_hills.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_MR_FLOPPY_ADVENTURE, and UnitAI::SendAIEvent().
Referenced by AddSC_grizzly_hills().
QuestAccept_npc_harrison_jones()
bool QuestAccept_npc_harrison_jones (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 363 of file grizzly_hills.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_DUN_DA_DUN_TAH, and UnitAI::SendAIEvent().
Referenced by AddSC_grizzly_hills().