CMaNGOS_WoTLK: System to link groups of NPCs together
System to link groups of NPCs together
This NPC-linking system in MaNGOS consists of 2 files:
Files
file CreatureLinkingMgr.cpp
This file contains the code needed for MaNGOS to link npcs together Currently implemented.
file CreatureLinkingMgr.h
This file contains the the headers needed for MaNGOS to link NPCs together.
Data Structures
struct CreatureLinkingInfo
class CreatureLinkingMgr
A class to represent the static information of linking NPCs together.
class CreatureLinkingHolder
A class to represent the dynamic information of linking NPCs together.
Macros
#define INVALID_MAP_ID 0xFFFFFFFF
#define sCreatureLinkingMgr MaNGOS::Singleton<CreatureLinkingMgr>::Instance()
Enumerations
enum EventMask {
EVENT_MASK_ON_AGGRO = FLAG_AGGRO_ON_AGGRO , EVENT_MASK_ON_EVADE = FLAG_RESPAWN_ON_EVADE | FLAG_DESPAWN_ON_EVADE | FLAG_EVADE_ON_EVADE , EVENT_MASK_ON_DIE = FLAG_DESPAWN_ON_DEATH | FLAG_SELFKILL_ON_DEATH | FLAG_RESPAWN_ON_DEATH | FLAG_FOLLOW , EVENT_MASK_ON_RESPAWN = FLAG_RESPAWN_ON_RESPAWN | FLAG_DESPAWN_ON_RESPAWN | FLAG_FOLLOW ,
EVENT_MASK_TRIGGER_TO = FLAG_TO_AGGRO_ON_AGGRO | FLAG_TO_RESPAWN_ON_EVADE | FLAG_FOLLOW , EVENT_MASK_ON_DESPAWN = FLAG_DESPAWN_ON_DESPAWN
}
enum CreatureLinkingEvent {
LINKING_EVENT_AGGRO = 0 , LINKING_EVENT_EVADE = 1 , LINKING_EVENT_DIE = 2 , LINKING_EVENT_RESPAWN = 3 ,
LINKING_EVENT_DESPAWN = 4
}
enum CreatureLinkingFlags {
FLAG_AGGRO_ON_AGGRO = 0x0001 , FLAG_TO_AGGRO_ON_AGGRO = 0x0002 , FLAG_RESPAWN_ON_EVADE = 0x0004 , FLAG_TO_RESPAWN_ON_EVADE = 0x0008 ,
FLAG_DESPAWN_ON_EVADE = 0x1000 , FLAG_DESPAWN_ON_DEATH = 0x0010 , FLAG_SELFKILL_ON_DEATH = 0x0020 , FLAG_RESPAWN_ON_DEATH = 0x0040 ,
FLAG_RESPAWN_ON_RESPAWN = 0x0080 , FLAG_DESPAWN_ON_RESPAWN = 0x0100 , FLAG_EVADE_ON_EVADE = 0x4000 , FLAG_FOLLOW = 0x0200 ,
FLAG_DESPAWN_ON_DESPAWN = 0x2000 , FLAG_CANT_SPAWN_IF_BOSS_DEAD = 0x0400 , FLAG_CANT_SPAWN_IF_BOSS_ALIVE = 0x0800 , LINKING_FLAG_INVALID = 0x8000
}
Functions
INSTANTIATE_SINGLETON_1 (CreatureLinkingMgr)
void CreatureLinkingMgr::LoadFromDB ()
static bool CreatureLinkingMgr::IsLinkingEntryValid (uint32 slaveEntry, CreatureLinkingInfo *pTmp, bool byEntry)
This function is used to check if a DB-Entry is valid.
bool CreatureLinkingMgr::IsLinkedEventTrigger (Creature *pCreature) const
bool CreatureLinkingMgr::IsLinkedMaster (Creature *pCreature) const
bool CreatureLinkingMgr::IsSpawnedByLinkedMob (Creature *pCreature) const
bool CreatureLinkingMgr::IsSpawnedByLinkedMob (CreatureLinkingInfo const *pInfo) const
CreatureLinkingInfo const * CreatureLinkingMgr::GetLinkedTriggerInformation (Creature *pCreature) const
CreatureLinkingInfo const * CreatureLinkingMgr::GetLinkedTriggerInformation (uint32 entry, uint32 lowGuid, uint32 mapId) const
void CreatureLinkingHolder::AddSlaveToHolder (Creature *pCreature)
void CreatureLinkingHolder::AddMasterToHolder (Creature *pCreature)
void CreatureLinkingHolder::DoCreatureLinkingEvent (CreatureLinkingEvent eventType, Creature *pSource, Unit *pEnemy=nullptr)
void CreatureLinkingHolder::ProcessSlaveGuidList (CreatureLinkingEvent eventType, Creature *pSource, uint32 flag, uint16 searchRange, std::list< std::pair< uint32, ObjectGuid >> &slaveGuidList, Unit *pEnemy)
void CreatureLinkingHolder::ProcessSlave (CreatureLinkingEvent eventType, Creature *pSource, uint32 flag, Creature *pSlave, Unit *pEnemy)
void CreatureLinkingHolder::SetFollowing (Creature *pWho, Creature *pWhom) const
bool CreatureLinkingHolder::IsSlaveInRangeOfMaster (Creature const *pSlave, Creature const *pBoss, uint16 searchRange) const
bool CreatureLinkingHolder::IsSlaveInRangeOfMaster (Creature const *pBoss, float sX, float sY, uint16 searchRange) const
bool CreatureLinkingHolder::IsRespawnReady (uint32 dbLowGuid, Map *_map) const
bool CreatureLinkingHolder::CanSpawn (Creature *pCreature) const
bool CreatureLinkingHolder::CanSpawn (uint32 lowGuid, Map *_map, CreatureLinkingInfo const *pInfo, float sx, float sy) const
Worker function to check if a spawning condition is met.
bool CreatureLinkingHolder::TryFollowMaster (Creature *pCreature)
Detailed Description
This NPC-linking system in MaNGOS consists of 2 files:
CreatureLinkingMgr.h
CreatureLinkingMgr.cpp as well of
hooks in Creature.cpp, to trigger actions
holder of the linked npcs for every map
Macro Definition Documentation
INVALID_MAP_ID
#define INVALID_MAP_ID 0xFFFFFFFF
Definition at line 47 of file CreatureLinkingMgr.cpp.
sCreatureLinkingMgr
#define sCreatureLinkingMgr MaNGOS::Singleton<CreatureLinkingMgr>::Instance()
Definition at line 209 of file CreatureLinkingMgr.h.
Enumeration Type Documentation
CreatureLinkingEvent
enum CreatureLinkingEvent
Enumerator
LINKING_EVENT_AGGRO
LINKING_EVENT_EVADE
LINKING_EVENT_DIE
LINKING_EVENT_RESPAWN
LINKING_EVENT_DESPAWN
Definition at line 46 of file CreatureLinkingMgr.h.
CreatureLinkingFlags
enum CreatureLinkingFlags
Enumerator
FLAG_AGGRO_ON_AGGRO
FLAG_TO_AGGRO_ON_AGGRO
FLAG_RESPAWN_ON_EVADE
FLAG_TO_RESPAWN_ON_EVADE
FLAG_DESPAWN_ON_EVADE
FLAG_DESPAWN_ON_DEATH
FLAG_SELFKILL_ON_DEATH
FLAG_RESPAWN_ON_DEATH
FLAG_RESPAWN_ON_RESPAWN
FLAG_DESPAWN_ON_RESPAWN
FLAG_EVADE_ON_EVADE
FLAG_FOLLOW
FLAG_DESPAWN_ON_DESPAWN
FLAG_CANT_SPAWN_IF_BOSS_DEAD
FLAG_CANT_SPAWN_IF_BOSS_ALIVE
LINKING_FLAG_INVALID
Definition at line 58 of file CreatureLinkingMgr.h.
EventMask
enum EventMask
Enumerator
EVENT_MASK_ON_AGGRO
EVENT_MASK_ON_EVADE
EVENT_MASK_ON_DIE
EVENT_MASK_ON_RESPAWN
EVENT_MASK_TRIGGER_TO
EVENT_MASK_ON_DESPAWN
Definition at line 264 of file CreatureLinkingMgr.cpp.
Function Documentation
AddMasterToHolder()
void CreatureLinkingHolder::AddMasterToHolder (Creature * pCreature)
Definition at line 389 of file CreatureLinkingMgr.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), Creature::IsPet(), CreatureLinkingHolder::m_masterGuid, and sCreatureLinkingMgr.
Referenced by Creature::Create().
AddSlaveToHolder()
void CreatureLinkingHolder::AddSlaveToHolder (Creature * pCreature)
Definition at line 334 of file CreatureLinkingMgr.cpp.
References Object::GetDbGuid(), Object::GetObjectGuid(), INVALID_MAP_ID, CreatureLinkingHolder::InfoAndGuids::linkedGuids, CreatureLinkingInfo::linkingFlag, CreatureLinkingHolder::InfoAndGuids::linkingFlag, CreatureLinkingHolder::m_holderGuidMap, CreatureLinkingHolder::m_holderMap, CreatureLinkingInfo::mapId, CreatureLinkingInfo::masterId, sCreatureLinkingMgr, CreatureLinkingInfo::searchRange, and CreatureLinkingHolder::InfoAndGuids::searchRange.
Referenced by Creature::Create().
CanSpawn() [1/2]
bool CreatureLinkingHolder::CanSpawn (Creature * pCreature) const
Definition at line 686 of file CreatureLinkingMgr.cpp.
References Object::GetDbGuid(), WorldObject::GetMap(), Creature::GetRespawnCoord(), and sCreatureLinkingMgr.
Referenced by Map::CanSpawn(), and CreatureLinkingHolder::IsRespawnReady().
CanSpawn() [2/2]
bool CreatureLinkingHolder::CanSpawn (uint32 dbGuid, Map * _map, CreatureLinkingInfo const * pInfo, float sx, float sy) const
Worker function to check if a spawning condition is met.
This function is used directly from above function, and for recursive use in case of recursive use it is used only on _map with information of dbGuid.
Parameters
dbGuid (only relevant in case of recursive uses) – db-guid of the npc that is checked
_map Map on which things are checked
pInfo (only shipped in case of initial use) – used as marker of first use, also in first use filled directly
sx,sy (spawn position of the checked npc with initial use)
Definition at line 707 of file CreatureLinkingMgr.cpp.
References FLAG_CANT_SPAWN_IF_BOSS_ALIVE, FLAG_CANT_SPAWN_IF_BOSS_DEAD, Map::GetCreature(), Map::GetDifficulty(), Map::GetInstanceData(), CreatureData::id, Unit::IsAlive(), CreatureLinkingHolder::IsRespawnReady(), CreatureLinkingHolder::IsSlaveInRangeOfMaster(), CreatureLinkingInfo::linkingFlag, CreatureLinkingHolder::m_masterGuid, CreatureData::mapid, CreatureLinkingInfo::masterDBGuid, CreatureLinkingInfo::masterId, CreatureData::posX, CreatureData::posY, sCreatureLinkingMgr, CreatureLinkingInfo::searchRange, sObjectMgr, and CreatureData::spawnMask.
DoCreatureLinkingEvent()
void CreatureLinkingHolder::DoCreatureLinkingEvent (CreatureLinkingEvent eventType, Creature * pSource, Unit * pEnemy = nullptr)
Definition at line 408 of file CreatureLinkingMgr.cpp.
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), EVENT_MASK_ON_AGGRO, EVENT_MASK_ON_DESPAWN, EVENT_MASK_ON_DIE, EVENT_MASK_ON_EVADE, EVENT_MASK_ON_RESPAWN, FLAG_FOLLOW, FLAG_TO_AGGRO_ON_AGGRO, FLAG_TO_RESPAWN_ON_EVADE, Unit::GetCombatManager(), Map::GetCreature(), ObjectMgr::GetCreatureTemplate(), Object::GetDbGuid(), Object::GetEntry(), WorldObject::GetMap(), Map::GetSpawnManager(), CreatureData::id, INVALID_MAP_ID, Unit::IsAlive(), WorldObject::IsControlledByPlayer(), Creature::IsCorpse(), Unit::IsInCombat(), CreatureLinkingHolder::IsSlaveInRangeOfMaster(), WorldObject::IsUsingNewSpawningSystem(), LINKING_EVENT_AGGRO, LINKING_EVENT_DESPAWN, LINKING_EVENT_DIE, LINKING_EVENT_EVADE, LINKING_EVENT_RESPAWN, CreatureLinkingHolder::m_holderGuidMap, CreatureLinkingHolder::m_holderMap, CreatureLinkingHolder::m_masterGuid, CreatureLinkingHolder::ProcessSlaveGuidList(), Creature::Respawn(), SpawnManager::RespawnCreature(), sCreatureLinkingMgr, CreatureLinkingHolder::SetFollowing(), Unit::SetInCombatWith(), sObjectMgr, and CombatManager::TriggerCombatTimer().
Referenced by Unit::JustKilledCreature(), Creature::LoadFromDB(), Creature::RemoveCorpse(), WorldObject::SummonCreature(), Unit::TakePossessOf(), Unit::TriggerAggroLinkingEvent(), Unit::TriggerEvadeEvents(), and Creature::Update().
GetLinkedTriggerInformation() [1/2]
CreatureLinkingInfo const * CreatureLinkingMgr::GetLinkedTriggerInformation (Creature * pCreature) const
Definition at line 311 of file CreatureLinkingMgr.cpp.
References Object::GetDbGuid(), Object::GetEntry(), and WorldObject::GetMapId().
Referenced by CreatureLinkingMgr::IsLinkedEventTrigger(), and CreatureLinkingMgr::IsSpawnedByLinkedMob().
GetLinkedTriggerInformation() [2/2]
CreatureLinkingInfo const * CreatureLinkingMgr::GetLinkedTriggerInformation (uint32 entry, uint32 lowGuid, uint32 mapId) const
Definition at line 315 of file CreatureLinkingMgr.cpp.
References CreatureLinkingMgr::m_creatureLinkingGuidMap, and CreatureLinkingMgr::m_creatureLinkingMap.
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (CreatureLinkingMgr)
IsLinkedEventTrigger()
bool CreatureLinkingMgr::IsLinkedEventTrigger (Creature * pCreature) const
Definition at line 275 of file CreatureLinkingMgr.cpp.
References EVENT_MASK_TRIGGER_TO, Object::GetDbGuid(), Object::GetEntry(), CreatureLinkingMgr::GetLinkedTriggerInformation(), CreatureLinkingMgr::m_eventGuidTriggers, and CreatureLinkingMgr::m_eventTriggers.
IsLinkedMaster()
bool CreatureLinkingMgr::IsLinkedMaster (Creature * pCreature) const
Definition at line 294 of file CreatureLinkingMgr.cpp.
References Object::GetEntry(), and CreatureLinkingMgr::m_eventTriggers.
IsLinkingEntryValid()
bool CreatureLinkingMgr::IsLinkingEntryValid (uint32 slaveEntry, CreatureLinkingInfo * pTmp, bool byEntry) static private
This function is used to check if a DB-Entry is valid.
Parameters
byEntry is the first parameter of the function a npc entry or a npc guid?
slaveEntry dependend on byEntry param this is either the slave's npc-entry or the npc-guid
pTmp Information about the CreatureLinking of the npc. Note that this information may be changed in some cases
In case of checking by entry and in case of linked spawning and searchRange == 0, pTmp will be changed to keep information about the (unique!) master's db-guid
Definition at line 176 of file CreatureLinkingMgr.cpp.
References QueryResult::Fetch(), FLAG_CANT_SPAWN_IF_BOSS_ALIVE, FLAG_CANT_SPAWN_IF_BOSS_DEAD, FLAG_DESPAWN_ON_RESPAWN, FLAG_FOLLOW, ObjectMgr::GetCreatureTemplate(), QueryResult::GetRowCount(), Field::GetUInt32(), LINKING_FLAG_INVALID, CreatureLinkingInfo::linkingFlag, CreatureData::mapid, CreatureLinkingInfo::mapId, CreatureLinkingInfo::masterDBGuid, CreatureLinkingInfo::masterId, Database::PQuery(), CreatureLinkingInfo::searchRange, sLog, sMapStore, sObjectMgr, and WorldDatabase.
Referenced by CreatureLinkingMgr::LoadFromDB().
IsRespawnReady()
bool CreatureLinkingHolder::IsRespawnReady (uint32 dbLowGuid, Map * _map) const private
Definition at line 671 of file CreatureLinkingMgr.cpp.
References CreatureLinkingHolder::CanSpawn(), MapPersistentState::GetCreatureRespawnTime(), Map::GetPersistentState(), MapPersistentState::IsSpawnedPoolObject(), and sPoolMgr.
Referenced by CreatureLinkingHolder::CanSpawn().
IsSlaveInRangeOfMaster() [1/2]
bool CreatureLinkingHolder::IsSlaveInRangeOfMaster (Creature const * pBoss, float sX, float sY, uint16 searchRange) const private
Definition at line 655 of file CreatureLinkingMgr.cpp.
References Creature::GetRespawnCoord().
IsSlaveInRangeOfMaster() [2/2]
bool CreatureLinkingHolder::IsSlaveInRangeOfMaster (Creature const * pSlave, Creature const * pBoss, uint16 searchRange) const private
Definition at line 649 of file CreatureLinkingMgr.cpp.
References Creature::GetRespawnCoord().
Referenced by CreatureLinkingHolder::CanSpawn(), CreatureLinkingHolder::DoCreatureLinkingEvent(), CreatureLinkingHolder::ProcessSlaveGuidList(), and CreatureLinkingHolder::TryFollowMaster().
IsSpawnedByLinkedMob() [1/2]
bool CreatureLinkingMgr::IsSpawnedByLinkedMob (Creature * pCreature) const
Definition at line 300 of file CreatureLinkingMgr.cpp.
References CreatureLinkingMgr::GetLinkedTriggerInformation().
IsSpawnedByLinkedMob() [2/2]
bool CreatureLinkingMgr::IsSpawnedByLinkedMob (CreatureLinkingInfo const * pInfo) const
Definition at line 304 of file CreatureLinkingMgr.cpp.
References FLAG_CANT_SPAWN_IF_BOSS_ALIVE, FLAG_CANT_SPAWN_IF_BOSS_DEAD, CreatureLinkingInfo::linkingFlag, CreatureLinkingInfo::masterDBGuid, and CreatureLinkingInfo::searchRange.
LoadFromDB()
void CreatureLinkingMgr::LoadFromDB ()
Definition at line 64 of file CreatureLinkingMgr.cpp.
References QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt16(), Field::GetUInt32(), INVALID_MAP_ID, CreatureLinkingMgr::IsLinkingEntryValid(), CreatureLinkingInfo::linkingFlag, CreatureLinkingMgr::m_creatureLinkingGuidMap, CreatureLinkingMgr::m_creatureLinkingMap, CreatureLinkingMgr::m_eventGuidTriggers, CreatureLinkingMgr::m_eventTriggers, CreatureLinkingInfo::mapId, CreatureLinkingInfo::masterDBGuid, CreatureLinkingInfo::masterId, QueryResult::NextRow(), Database::Query(), CreatureLinkingInfo::searchRange, sLog, BarGoLink::step(), and WorldDatabase.
ProcessSlave()
void CreatureLinkingHolder::ProcessSlave (CreatureLinkingEvent eventType, Creature * pSource, uint32 flag, Creature * pSlave, Unit * pEnemy) private
Definition at line 563 of file CreatureLinkingMgr.cpp.
References Unit::AddThreat(), Creature::AI(), UnitAI::AttackStart(), UnitAI::EnterEvadeMode(), FLAG_AGGRO_ON_AGGRO, FLAG_DESPAWN_ON_DEATH, FLAG_DESPAWN_ON_DESPAWN, FLAG_DESPAWN_ON_EVADE, FLAG_DESPAWN_ON_RESPAWN, FLAG_EVADE_ON_EVADE, FLAG_FOLLOW, FLAG_RESPAWN_ON_DEATH, FLAG_RESPAWN_ON_EVADE, FLAG_RESPAWN_ON_RESPAWN, FLAG_SELFKILL_ON_DEATH, Creature::ForcedDespawn(), Unit::GetCombatManager(), Creature::GetRespawnDelay(), Creature::GetRespawnTime(), Unit::IsAlive(), WorldObject::IsControlledByPlayer(), Creature::IsDespawned(), Unit::IsInCombat(), LINKING_EVENT_AGGRO, LINKING_EVENT_DESPAWN, LINKING_EVENT_DIE, LINKING_EVENT_EVADE, LINKING_EVENT_RESPAWN, Creature::Respawn(), CreatureLinkingHolder::SetFollowing(), Unit::SetInCombatWith(), Unit::Suicide(), and CombatManager::TriggerCombatTimer().
Referenced by CreatureLinkingHolder::ProcessSlaveGuidList().
ProcessSlaveGuidList()
void CreatureLinkingHolder::ProcessSlaveGuidList (CreatureLinkingEvent eventType, Creature * pSource, uint32 flag, uint16 searchRange, std::list< std::pair< uint32, ObjectGuid >> & slaveGuidList, Unit * pEnemy) private
Definition at line 521 of file CreatureLinkingMgr.cpp.
References FLAG_RESPAWN_ON_DEATH, FLAG_RESPAWN_ON_EVADE, FLAG_RESPAWN_ON_RESPAWN, Map::GetCreature(), WorldObject::GetMap(), Map::GetSpawnManager(), Creature::IsCorpse(), Creature::IsPet(), CreatureLinkingHolder::IsSlaveInRangeOfMaster(), WorldObject::IsUsingNewSpawningSystem(), CreatureLinkingHolder::ProcessSlave(), and SpawnManager::RespawnCreature().
Referenced by CreatureLinkingHolder::DoCreatureLinkingEvent().
SetFollowing()
void CreatureLinkingHolder::SetFollowing (Creature * pWho, Creature * pWhom) const private
Definition at line 623 of file CreatureLinkingMgr.cpp.
References Unit::GetMotionMaster(), Unit::GetObjectBoundingRadius(), Creature::GetRespawnCoord(), M_PI_F, and MotionMaster::MoveFollow().
Referenced by CreatureLinkingHolder::DoCreatureLinkingEvent(), CreatureLinkingHolder::ProcessSlave(), and CreatureLinkingHolder::TryFollowMaster().
TryFollowMaster()
bool CreatureLinkingHolder::TryFollowMaster (Creature * pCreature)
Definition at line 764 of file CreatureLinkingMgr.cpp.
References FLAG_FOLLOW, Map::GetCreature(), ObjectMgr::GetCreatureTemplate(), WorldObject::GetMap(), CreatureData::id, INVALID_MAP_ID, Unit::IsAlive(), CreatureLinkingHolder::IsSlaveInRangeOfMaster(), CreatureLinkingInfo::linkingFlag, CreatureLinkingHolder::m_masterGuid, CreatureLinkingInfo::mapId, CreatureLinkingInfo::masterDBGuid, CreatureLinkingInfo::masterId, sCreatureLinkingMgr, CreatureLinkingInfo::searchRange, CreatureLinkingHolder::SetFollowing(), and sObjectMgr.
Referenced by Unit::TriggerHomeEvents().