CMaNGOS_WoTLK: The World
The World
Files
file Weather.cpp
file Weather.h
file World.cpp
file World.h
Data Structures
class Weather
Weather for one zone.
class WeatherSystem
Weathers for one map.
struct WeatherSeasonChances
struct WeatherZoneChances
class WeatherMgr
struct CliCommandHolder
Storage class for commands issued for delayed execution.
class World
The World.
Macros
#define WEATHER_SEASONS 4
#define sWeatherMgr MaNGOS::Singleton<WeatherMgr>::Instance()
#define sWorld MaNGOS::Singleton<World>::Instance()
Typedefs
typedef std::unordered_map< uint32, Weather * > WeatherSystem::WeatherMap
typedef std::unordered_map< uint32, WeatherZoneChances > WeatherMgr::WeatherZoneMap
Enumerations
enum WeatherState {
WEATHER_STATE_FINE = 0 , WEATHER_STATE_LIGHT_RAIN = 3 , WEATHER_STATE_MEDIUM_RAIN = 4 , WEATHER_STATE_HEAVY_RAIN = 5 ,
WEATHER_STATE_LIGHT_SNOW = 6 , WEATHER_STATE_MEDIUM_SNOW = 7 , WEATHER_STATE_HEAVY_SNOW = 8 , WEATHER_STATE_LIGHT_SANDSTORM = 22 ,
WEATHER_STATE_MEDIUM_SANDSTORM = 41 , WEATHER_STATE_HEAVY_SANDSTORM = 42 , WEATHER_STATE_THUNDERS = 86 , WEATHER_STATE_BLACKRAIN = 90
}
enum ServerMessageType {
SERVER_MSG_SHUTDOWN_TIME = 1 , SERVER_MSG_RESTART_TIME = 2 , SERVER_MSG_CUSTOM = 3 , SERVER_MSG_SHUTDOWN_CANCELLED = 4 ,
SERVER_MSG_RESTART_CANCELLED = 5 , SERVER_MSG_BG_SHUTDOWN_TIME = 6 , SERVER_MSG_BG_RESTART_TIME = 7 , SERVER_MSG_INSTANCE_SHUTDOWN_TIME = 8 ,
SERVER_MSG_INSTANCE_RESTART_TIME = 9
}
enum ShutdownMask { SHUTDOWN_MASK_RESTART = 1 , SHUTDOWN_MASK_IDLE = 2 }
enum ShutdownExitCode { SHUTDOWN_EXIT_CODE = 0 , ERROR_EXIT_CODE = 1 , RESTART_EXIT_CODE = 2 }
enum WorldTimers {
WUPDATE_AUCTIONS = 0 , WUPDATE_UPTIME = 1 , WUPDATE_CORPSES = 2 , WUPDATE_EVENTS = 3 ,
WUPDATE_DELETECHARS = 4 , WUPDATE_AHBOT = 5 , WUPDATE_GROUPS = 6 , WUPDATE_RAID_BROWSER = 7 ,
WUPDATE_METRICS = 8 , WUPDATE_COUNT = 9
}
Timers for different object refresh rates.
enum eConfigUInt32Values {
CONFIG_UINT32_COMPRESSION = 0 , CONFIG_UINT32_INTERVAL_SAVE , CONFIG_UINT32_INTERVAL_GRIDCLEAN , CONFIG_UINT32_INTERVAL_MAPUPDATE ,
CONFIG_UINT32_INTERVAL_CHANGEWEATHER , CONFIG_UINT32_PORT_WORLD , CONFIG_UINT32_GAME_TYPE , CONFIG_UINT32_REALM_ZONE ,
CONFIG_UINT32_STRICT_PLAYER_NAMES , CONFIG_UINT32_STRICT_CHARTER_NAMES , CONFIG_UINT32_STRICT_PET_NAMES , CONFIG_UINT32_MIN_PLAYER_NAME ,
CONFIG_UINT32_MIN_CHARTER_NAME , CONFIG_UINT32_MIN_PET_NAME , CONFIG_UINT32_CHARACTERS_CREATING_DISABLED , CONFIG_UINT32_CHARACTERS_PER_ACCOUNT ,
CONFIG_UINT32_CHARACTERS_PER_REALM , CONFIG_UINT32_HEROIC_CHARACTERS_PER_REALM , CONFIG_UINT32_MIN_LEVEL_FOR_HEROIC_CHARACTER_CREATING , CONFIG_UINT32_SKIP_CINEMATICS ,
CONFIG_UINT32_MAX_PLAYER_LEVEL , CONFIG_UINT32_START_PLAYER_LEVEL , CONFIG_UINT32_START_HEROIC_PLAYER_LEVEL , CONFIG_UINT32_START_PLAYER_MONEY ,
CONFIG_UINT32_MAX_HONOR_POINTS , CONFIG_UINT32_START_HONOR_POINTS , CONFIG_UINT32_MAX_ARENA_POINTS , CONFIG_UINT32_START_ARENA_POINTS ,
CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR , CONFIG_UINT32_INSTANCE_UNLOAD_DELAY , CONFIG_UINT32_MAX_SPELL_CASTS_IN_CHAIN , CONFIG_UINT32_BIRTHDAY_TIME ,
CONFIG_UINT32_RABBIT_DAY , CONFIG_UINT32_MAX_PRIMARY_TRADE_SKILL , CONFIG_UINT32_TRADE_SKILL_GMIGNORE_MAX_PRIMARY_COUNT , CONFIG_UINT32_TRADE_SKILL_GMIGNORE_LEVEL ,
CONFIG_UINT32_TRADE_SKILL_GMIGNORE_SKILL , CONFIG_UINT32_MIN_PETITION_SIGNS , CONFIG_UINT32_GM_LOGIN_STATE , CONFIG_UINT32_GM_VISIBLE_STATE ,
CONFIG_UINT32_GM_ACCEPT_TICKETS , CONFIG_UINT32_GM_LEVEL_ACCEPT_TICKETS , CONFIG_UINT32_GM_CHAT , CONFIG_UINT32_GM_LEVEL_CHAT ,
CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION , CONFIG_UINT32_GM_LEVEL_CHANNEL_SILENT_JOIN , CONFIG_UINT32_GM_WISPERING_TO , CONFIG_UINT32_GM_LEVEL_IN_GM_LIST ,
CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST , CONFIG_UINT32_START_GM_LEVEL , CONFIG_UINT32_GM_INVISIBLE_AURA , CONFIG_UINT32_MAIL_DELIVERY_DELAY ,
CONFIG_UINT32_MASS_MAILER_SEND_PER_TICK , CONFIG_UINT32_UPTIME_UPDATE , CONFIG_UINT32_NUM_MAP_THREADS , CONFIG_UINT32_AUCTION_DEPOSIT_MIN ,
CONFIG_UINT32_SKILL_CHANCE_ORANGE , CONFIG_UINT32_SKILL_CHANCE_YELLOW , CONFIG_UINT32_SKILL_CHANCE_GREEN , CONFIG_UINT32_SKILL_CHANCE_GREY ,
CONFIG_UINT32_SKILL_CHANCE_MINING_STEPS , CONFIG_UINT32_SKILL_CHANCE_SKINNING_STEPS , CONFIG_UINT32_SKILL_GAIN_CRAFTING , CONFIG_UINT32_SKILL_GAIN_DEFENSE ,
CONFIG_UINT32_SKILL_GAIN_GATHERING , CONFIG_UINT32_SKILL_GAIN_WEAPON , CONFIG_UINT32_MAX_OVERSPEED_PINGS , CONFIG_UINT32_EXPANSION ,
CONFIG_UINT32_CHATFLOOD_MESSAGE_COUNT , CONFIG_UINT32_CHATFLOOD_MESSAGE_DELAY , CONFIG_UINT32_CHATFLOOD_MUTE_TIME , CONFIG_UINT32_CREATURE_FAMILY_ASSISTANCE_DELAY ,
CONFIG_UINT32_CREATURE_FAMILY_FLEE_DELAY , CONFIG_UINT32_WORLD_BOSS_LEVEL_DIFF , CONFIG_UINT32_QUEST_DAILY_RESET_HOUR , CONFIG_UINT32_QUEST_WEEKLY_RESET_WEEK_DAY ,
CONFIG_UINT32_QUEST_WEEKLY_RESET_HOUR , CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_SEVERITY , CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_KICK , CONFIG_UINT32_CHANNEL_RESTRICTED_LANGUAGE_MODE ,
CONFIG_UINT32_CORPSE_DECAY_NORMAL , CONFIG_UINT32_CORPSE_DECAY_RARE , CONFIG_UINT32_CORPSE_DECAY_ELITE , CONFIG_UINT32_CORPSE_DECAY_RAREELITE ,
CONFIG_UINT32_CORPSE_DECAY_WORLDBOSS , CONFIG_UINT32_INSTANT_LOGOUT , CONFIG_UINT32_BATTLEGROUND_INVITATION_TYPE , CONFIG_UINT32_BATTLEGROUND_PREMATURE_FINISH_TIMER ,
CONFIG_UINT32_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH , CONFIG_UINT32_BATTLEGROUND_QUEUE_ANNOUNCER_JOIN , CONFIG_UINT32_BATTLEGROUND_RANDOM_RESET_HOUR , CONFIG_UINT32_ARENA_MAX_RATING_DIFFERENCE ,
CONFIG_UINT32_ARENA_RATING_DISCARD_TIMER , CONFIG_UINT32_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS , CONFIG_UINT32_ARENA_SEASON_ID , CONFIG_UINT32_ARENA_FIRST_RESET_DAY ,
CONFIG_UINT32_ARENA_SEASON_PREVIOUS_ID , CONFIG_UINT32_GROUP_OFFLINE_LEADER_DELAY , CONFIG_UINT32_BATTLEFIELD_COOLDOWN_DURATION , CONFIG_UINT32_BATTLEFIELD_BATTLE_DURATION ,
CONFIG_UINT32_BATTLEFIELD_MAX_PLAYERS_PER_TEAM , CONFIG_UINT32_CLIENTCACHE_VERSION , CONFIG_UINT32_GUILD_EVENT_LOG_COUNT , CONFIG_UINT32_GUILD_BANK_EVENT_LOG_COUNT ,
CONFIG_UINT32_MIRRORTIMER_FATIGUE_MAX , CONFIG_UINT32_MIRRORTIMER_BREATH_MAX , CONFIG_UINT32_MIRRORTIMER_ENVIRONMENTAL_MAX , CONFIG_UINT32_ENVIRONMENTAL_DAMAGE_MIN ,
CONFIG_UINT32_ENVIRONMENTAL_DAMAGE_MAX , CONFIG_UINT32_INTERACTION_PAUSE_TIMER , CONFIG_UINT32_MIN_LEVEL_STAT_SAVE , CONFIG_UINT32_CHARDELETE_KEEP_DAYS ,
CONFIG_UINT32_CHARDELETE_METHOD , CONFIG_UINT32_CHARDELETE_MIN_LEVEL , CONFIG_UINT32_GUID_RESERVE_SIZE_CREATURE , CONFIG_UINT32_GUID_RESERVE_SIZE_GAMEOBJECT ,
CONFIG_UINT32_MIN_LEVEL_FOR_RAID , CONFIG_UINT32_CREATURE_RESPAWN_AGGRO_DELAY , CONFIG_UINT32_CREATURE_CHECK_FOR_HELP_AGGRO_DELAY , CONFIG_UINT32_MAX_WHOLIST_RETURNS ,
CONFIG_UINT32_FOGOFWAR_STEALTH , CONFIG_UINT32_FOGOFWAR_HEALTH , CONFIG_UINT32_FOGOFWAR_STATS , CONFIG_UINT32_CREATURE_PICKPOCKET_RESTOCK_DELAY ,
CONFIG_UINT32_CHANNEL_STATIC_AUTO_TRESHOLD , CONFIG_UINT32_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL , CONFIG_UINT32_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL_DIFFERENCE , CONFIG_UINT32_SUNSREACH_COUNTER ,
CONFIG_UINT32_VALUE_COUNT
}
Configuration elements.
enum eConfigInt32Values {
CONFIG_INT32_DEATH_SICKNESS_LEVEL = 0 , CONFIG_INT32_ARENA_STARTRATING , CONFIG_INT32_ARENA_STARTPERSONALRATING , CONFIG_INT32_QUEST_LOW_LEVEL_HIDE_DIFF ,
CONFIG_INT32_QUEST_HIGH_LEVEL_HIDE_DIFF , CONFIG_INT32_VALUE_COUNT
}
Configuration elements.
enum eConfigFloatValues {
CONFIG_FLOAT_RATE_HEALTH = 0 , CONFIG_FLOAT_RATE_POWER_MANA , CONFIG_FLOAT_RATE_POWER_RAGE_INCOME , CONFIG_FLOAT_RATE_POWER_RAGE_LOSS ,
CONFIG_FLOAT_RATE_POWER_RUNICPOWER_INCOME , CONFIG_FLOAT_RATE_POWER_RUNICPOWER_LOSS , CONFIG_FLOAT_RATE_POWER_FOCUS , CONFIG_FLOAT_RATE_POWER_ENERGY ,
CONFIG_FLOAT_RATE_SKILL_DISCOVERY , CONFIG_FLOAT_RATE_DROP_ITEM_POOR , CONFIG_FLOAT_RATE_DROP_ITEM_NORMAL , CONFIG_FLOAT_RATE_DROP_ITEM_UNCOMMON ,
CONFIG_FLOAT_RATE_DROP_ITEM_RARE , CONFIG_FLOAT_RATE_DROP_ITEM_EPIC , CONFIG_FLOAT_RATE_DROP_ITEM_LEGENDARY , CONFIG_FLOAT_RATE_DROP_ITEM_ARTIFACT ,
CONFIG_FLOAT_RATE_DROP_ITEM_REFERENCED , CONFIG_FLOAT_RATE_DROP_ITEM_QUEST , CONFIG_FLOAT_RATE_DROP_MONEY , CONFIG_FLOAT_RATE_PET_XP_KILL ,
CONFIG_FLOAT_RATE_XP_KILL , CONFIG_FLOAT_RATE_XP_QUEST , CONFIG_FLOAT_RATE_XP_EXPLORE , CONFIG_FLOAT_RATE_REPUTATION_GAIN ,
CONFIG_FLOAT_RATE_REPUTATION_LOWLEVEL_KILL , CONFIG_FLOAT_RATE_REPUTATION_LOWLEVEL_QUEST , CONFIG_FLOAT_RATE_CREATURE_NORMAL_HP , CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_HP ,
CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_HP , CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_HP , CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_HP , CONFIG_FLOAT_RATE_CREATURE_NORMAL_DAMAGE ,
CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_DAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_DAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_DAMAGE ,
CONFIG_FLOAT_RATE_CREATURE_NORMAL_SPELLDAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE , CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE ,
CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_SPELLDAMAGE , CONFIG_FLOAT_RATE_CREATURE_AGGRO , CONFIG_FLOAT_RATE_REST_INGAME , CONFIG_FLOAT_RATE_REST_OFFLINE_IN_TAVERN_OR_CITY ,
CONFIG_FLOAT_RATE_REST_OFFLINE_IN_WILDERNESS , CONFIG_FLOAT_RATE_DAMAGE_FALL , CONFIG_FLOAT_RATE_AUCTION_TIME , CONFIG_FLOAT_RATE_AUCTION_DEPOSIT ,
CONFIG_FLOAT_RATE_AUCTION_CUT , CONFIG_FLOAT_RATE_HONOR , CONFIG_FLOAT_RATE_MINING_AMOUNT , CONFIG_FLOAT_RATE_MINING_NEXT ,
CONFIG_FLOAT_RATE_TALENT , CONFIG_FLOAT_RATE_CORPSE_DECAY_LOOTED , CONFIG_FLOAT_RATE_INSTANCE_RESET_TIME , CONFIG_FLOAT_RATE_DURABILITY_LOSS_DAMAGE ,
CONFIG_FLOAT_RATE_DURABILITY_LOSS_PARRY , CONFIG_FLOAT_RATE_DURABILITY_LOSS_ABSORB , CONFIG_FLOAT_RATE_DURABILITY_LOSS_BLOCK , CONFIG_FLOAT_SIGHT_GUARDER ,
CONFIG_FLOAT_SIGHT_MONSTER , CONFIG_FLOAT_LISTEN_RANGE_SAY , CONFIG_FLOAT_LISTEN_RANGE_YELL , CONFIG_FLOAT_LISTEN_RANGE_TEXTEMOTE ,
CONFIG_FLOAT_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS , CONFIG_FLOAT_CREATURE_FAMILY_ASSISTANCE_RADIUS , CONFIG_FLOAT_CREATURE_CHECK_FOR_HELP_RADIUS , CONFIG_FLOAT_GROUP_XP_DISTANCE ,
CONFIG_FLOAT_GHOST_RUN_SPEED_WORLD , CONFIG_FLOAT_GHOST_RUN_SPEED_BG , CONFIG_FLOAT_LEASH_RADIUS , CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_FRIENDLY ,
CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_HONORED , CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_REVERED , CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_EXALTED , CONFIG_FLOAT_MOD_INCREASED_XP ,
CONFIG_FLOAT_MOD_INCREASED_GOLD , CONFIG_FLOAT_MAX_RECRUIT_A_FRIEND_DISTANCE , CONFIG_FLOAT_VALUE_COUNT
}
Server config.
enum eConfigBoolValues {
CONFIG_BOOL_GRID_UNLOAD = 0 , CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY , CONFIG_BOOL_OFFHAND_CHECK_AT_TALENTS_RESET , CONFIG_BOOL_ALLOW_TWO_SIDE_ACCOUNTS ,
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHAT , CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL , CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GROUP , CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD ,
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_AUCTION , CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_MAIL , CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CALENDAR , CONFIG_BOOL_ALLOW_TWO_SIDE_WHO_LIST ,
CONFIG_BOOL_ALLOW_TWO_SIDE_ADD_FRIEND , CONFIG_BOOL_INSTANCE_IGNORE_LEVEL , CONFIG_BOOL_INSTANCE_IGNORE_RAID , CONFIG_BOOL_INSTANCE_STRICT_COMBAT_LOCKDOWN ,
CONFIG_BOOL_CAST_UNSTUCK , CONFIG_BOOL_GM_LOG_TRADE , CONFIG_BOOL_GM_LOWER_SECURITY , CONFIG_BOOL_GM_TICKETS_QUEUE_STATUS ,
CONFIG_BOOL_GM_ALLOW_ACHIEVEMENT_GAINS , CONFIG_BOOL_SKILL_PROSPECTING , CONFIG_BOOL_ALWAYS_MAX_SKILL_FOR_LEVEL , CONFIG_BOOL_WEATHER ,
CONFIG_BOOL_EVENT_ANNOUNCE , CONFIG_BOOL_QUEST_IGNORE_RAID , CONFIG_BOOL_DETECT_POS_COLLISION , CONFIG_BOOL_CHAT_RESTRICTED_RAID_WARNINGS ,
CONFIG_BOOL_CHANNEL_RESTRICTED_LFG , CONFIG_BOOL_TALENTS_INSPECTING , CONFIG_BOOL_CHAT_FAKE_MESSAGE_PREVENTING , CONFIG_BOOL_CHAT_STRICT_LINK_CHECKING_SEVERITY ,
CONFIG_BOOL_CHAT_STRICT_LINK_CHECKING_KICK , CONFIG_BOOL_ADDON_CHANNEL , CONFIG_BOOL_CORPSE_EMPTY_LOOT_SHOW , CONFIG_BOOL_CORPSE_ALLOW_ALL_ITEMS_SHOW_IN_MASTER_LOOT ,
CONFIG_BOOL_DEATH_CORPSE_RECLAIM_DELAY_PVP , CONFIG_BOOL_DEATH_CORPSE_RECLAIM_DELAY_PVE , CONFIG_BOOL_DEATH_BONES_WORLD , CONFIG_BOOL_DEATH_BONES_BG_OR_ARENA ,
CONFIG_BOOL_TAXI_FLIGHT_CHAT_FIX , CONFIG_BOOL_LONG_TAXI_PATHS_PERSISTENCE , CONFIG_BOOL_ALL_TAXI_PATHS , CONFIG_BOOL_DECLINED_NAMES_USED ,
CONFIG_BOOL_SKILL_MILLING , CONFIG_BOOL_SKILL_FAIL_LOOT_FISHING , CONFIG_BOOL_SKILL_FAIL_GAIN_FISHING , CONFIG_BOOL_SKILL_FAIL_POSSIBLE_FISHINGPOOL ,
CONFIG_BOOL_BATTLEGROUND_CAST_DESERTER , CONFIG_BOOL_BATTLEGROUND_QUEUE_ANNOUNCER_START , CONFIG_BOOL_BATTLEGROUND_SCORE_STATISTICS , CONFIG_BOOL_ARENA_AUTO_DISTRIBUTE_POINTS ,
CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_JOIN , CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_EXIT , CONFIG_BOOL_OUTDOORPVP_SI_ENABLED , CONFIG_BOOL_OUTDOORPVP_EP_ENABLED ,
CONFIG_BOOL_OUTDOORPVP_HP_ENABLED , CONFIG_BOOL_OUTDOORPVP_ZM_ENABLED , CONFIG_BOOL_OUTDOORPVP_TF_ENABLED , CONFIG_BOOL_OUTDOORPVP_NA_ENABLED ,
CONFIG_BOOL_OUTDOORPVP_GH_ENABLED , CONFIG_BOOL_BATTLEFIELD_WG_ENABLED , CONFIG_BOOL_KICK_PLAYER_ON_BAD_PACKET , CONFIG_BOOL_STATS_SAVE_ONLY_ON_LOGOUT ,
CONFIG_BOOL_CLEAN_CHARACTER_DB , CONFIG_BOOL_VMAP_INDOOR_CHECK , CONFIG_BOOL_PET_UNSUMMON_AT_MOUNT , CONFIG_BOOL_PET_ATTACK_FROM_BEHIND ,
CONFIG_BOOL_AUTO_DOWNRANK , CONFIG_BOOL_MMAP_ENABLED , CONFIG_BOOL_PLAYER_COMMANDS , CONFIG_BOOL_AUTOLOAD_ACTIVE ,
CONFIG_BOOL_PATH_FIND_OPTIMIZE , CONFIG_BOOL_PATH_FIND_NORMALIZE_Z , CONFIG_BOOL_ALWAYS_SHOW_QUEST_GREETING , CONFIG_BOOL_VALUE_COUNT
}
Configuration elements.
enum BillingPlanFlags {
SESSION_NONE = 0x00 , SESSION_UNUSED = 0x01 , SESSION_RECURRING_BILL = 0x02 , SESSION_FREE_TRIAL = 0x04 ,
SESSION_IGR = 0x08 , SESSION_USAGE = 0x10 , SESSION_TIME_MIXTURE = 0x20 , SESSION_RESTRICTED = 0x40 ,
SESSION_ENABLE_CAIS = 0x80
}
Can be used in SMSG_AUTH_RESPONSE packet.
enum RealmType {
REALM_TYPE_NORMAL = 0 , REALM_TYPE_PVP = 1 , REALM_TYPE_NORMAL2 = 4 , REALM_TYPE_RP = 6 ,
REALM_TYPE_RPPVP = 8 , REALM_TYPE_FFA_PVP = 16
}
Type of server, this is values from second column of Cfg_Configs.dbc (1.12.1 have another numeration)
enum RealmZone {
REALM_ZONE_UNKNOWN = 0 , REALM_ZONE_DEVELOPMENT = 1 , REALM_ZONE_UNITED_STATES = 2 , REALM_ZONE_OCEANIC = 3 ,
REALM_ZONE_LATIN_AMERICA = 4 , REALM_ZONE_TOURNAMENT_5 = 5 , REALM_ZONE_KOREA = 6 , REALM_ZONE_TOURNAMENT_7 = 7 ,
REALM_ZONE_ENGLISH = 8 , REALM_ZONE_GERMAN = 9 , REALM_ZONE_FRENCH = 10 , REALM_ZONE_SPANISH = 11 ,
REALM_ZONE_RUSSIAN = 12 , REALM_ZONE_TOURNAMENT_13 = 13 , REALM_ZONE_TAIWAN = 14 , REALM_ZONE_TOURNAMENT_15 = 15 ,
REALM_ZONE_CHINA = 16 , REALM_ZONE_CN1 = 17 , REALM_ZONE_CN2 = 18 , REALM_ZONE_CN3 = 19 ,
REALM_ZONE_CN4 = 20 , REALM_ZONE_CN5 = 21 , REALM_ZONE_CN6 = 22 , REALM_ZONE_CN7 = 23 ,
REALM_ZONE_CN8 = 24 , REALM_ZONE_TOURNAMENT_25 = 25 , REALM_ZONE_TEST_SERVER = 26 , REALM_ZONE_TOURNAMENT_27 = 27 ,
REALM_ZONE_QA_SERVER = 28 , REALM_ZONE_CN9 = 29 , REALM_ZONE_TEST_SERVER_2 = 30 , REALM_ZONE_CN10 = 31 ,
REALM_ZONE_CTC = 32 , REALM_ZONE_CNC = 33 , REALM_ZONE_CN1_4 = 34 , REALM_ZONE_CN2_6_9 = 35 ,
REALM_ZONE_CN3_7 = 36 , REALM_ZONE_CN5_8 = 37
}
This is values from first column of Cfg_Categories.dbc (1.12.1 have another numeration)
Functions
Weather::Weather (uint32 zone, WeatherZoneChances const *weatherChances)
Create the Weather object.
Weather::~Weather ()
void Weather::SendWeatherUpdateToPlayer (Player *player)
Send Weather to one player.
void Weather::SetWeather (WeatherType type, float grade, Map const *_map, bool isPermanent)
Set the weather.
bool Weather::Update (uint32 diff, Map const *_map)
Update the weather in this zone, when the timer is expired the weather will be rolled again.
static bool Weather::IsValidWeatherType (uint32 type)
Check if a type is valid.
bool Weather::SendWeatherForPlayersInZone (Map const *_map)
Send SMSG_WEATHER to all players in the zone.
bool Weather::ReGenerate ()
Calculate new weather.
WeatherState Weather::GetWeatherState () const
Calculate state based on type and grade.
void Weather::NormalizeGrade ()
void Weather::LogWeatherState (WeatherState state) const
WeatherSystem::WeatherSystem (Map const *_map)
WeatherSystem::~WeatherSystem ()
Weather * WeatherSystem::FindOrCreateWeather (uint32 zoneId)
Find or Create a Weather object by the given zoneid.
void WeatherSystem::UpdateWeathers (uint32 diff)
Update Weathers for the different zones.
WeatherMgr::WeatherMgr ()
WeatherMgr::~WeatherMgr ()
void WeatherMgr::LoadWeatherZoneChances ()
Load Weather chanced from table game_weather.
WeatherZoneChances const * WeatherMgr::GetWeatherChances (uint32 zone_id) const
Variables
uint32 Weather::m_zone
WeatherType Weather::m_type
float Weather::m_grade
ShortIntervalTimer Weather::m_timer
WeatherZoneChances const * Weather::m_weatherChances
bool Weather::m_isPermanentWeather
Map const *const WeatherSystem::m_map
WeatherMap WeatherSystem::m_weathers
uint32 WeatherSeasonChances::rainChance
uint32 WeatherSeasonChances::snowChance
uint32 WeatherSeasonChances::stormChance
WeatherSeasonChances WeatherZoneChances::data [WEATHER_SEASONS]
WeatherZoneMap WeatherMgr::mWeatherZoneMap
uint32 realmID
Id of the realm.
Detailed Description
Macro Definition Documentation
sWeatherMgr
#define sWeatherMgr MaNGOS::Singleton<WeatherMgr>::Instance()
Definition at line 164 of file Weather.h.
sWorld
#define sWorld MaNGOS::Singleton<World>::Instance()
Definition at line 832 of file World.h.
WEATHER_SEASONS
#define WEATHER_SEASONS 4
Definition at line 130 of file Weather.h.
Typedef Documentation
WeatherMap
typedef std::unordered_map<uint32 , Weather*> WeatherSystem::WeatherMap private
Definition at line 122 of file Weather.h.
WeatherZoneMap
typedef std::unordered_map<uint32 , WeatherZoneChances> WeatherMgr::WeatherZoneMap private
Definition at line 160 of file Weather.h.
Enumeration Type Documentation
BillingPlanFlags
enum BillingPlanFlags
Can be used in SMSG_AUTH_RESPONSE packet.
Enumerator
SESSION_NONE
SESSION_UNUSED
SESSION_RECURRING_BILL
SESSION_FREE_TRIAL
SESSION_IGR
SESSION_USAGE
SESSION_TIME_MIXTURE
SESSION_RESTRICTED
SESSION_ENABLE_CAIS
Definition at line 407 of file World.h.
eConfigBoolValues
enum eConfigBoolValues
Configuration elements.
Enumerator
CONFIG_BOOL_GRID_UNLOAD
CONFIG_BOOL_SAVE_RESPAWN_TIME_IMMEDIATELY
CONFIG_BOOL_OFFHAND_CHECK_AT_TALENTS_RESET
CONFIG_BOOL_ALLOW_TWO_SIDE_ACCOUNTS
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHAT
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CHANNEL
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GROUP
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_GUILD
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_AUCTION
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_MAIL
CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_CALENDAR
CONFIG_BOOL_ALLOW_TWO_SIDE_WHO_LIST
CONFIG_BOOL_ALLOW_TWO_SIDE_ADD_FRIEND
CONFIG_BOOL_INSTANCE_IGNORE_LEVEL
CONFIG_BOOL_INSTANCE_IGNORE_RAID
CONFIG_BOOL_INSTANCE_STRICT_COMBAT_LOCKDOWN
CONFIG_BOOL_CAST_UNSTUCK
CONFIG_BOOL_GM_LOG_TRADE
CONFIG_BOOL_GM_LOWER_SECURITY
CONFIG_BOOL_GM_TICKETS_QUEUE_STATUS
CONFIG_BOOL_GM_ALLOW_ACHIEVEMENT_GAINS
CONFIG_BOOL_SKILL_PROSPECTING
CONFIG_BOOL_ALWAYS_MAX_SKILL_FOR_LEVEL
CONFIG_BOOL_WEATHER
CONFIG_BOOL_EVENT_ANNOUNCE
CONFIG_BOOL_QUEST_IGNORE_RAID
CONFIG_BOOL_DETECT_POS_COLLISION
CONFIG_BOOL_CHAT_RESTRICTED_RAID_WARNINGS
CONFIG_BOOL_CHANNEL_RESTRICTED_LFG
CONFIG_BOOL_TALENTS_INSPECTING
CONFIG_BOOL_CHAT_FAKE_MESSAGE_PREVENTING
CONFIG_BOOL_CHAT_STRICT_LINK_CHECKING_SEVERITY
CONFIG_BOOL_CHAT_STRICT_LINK_CHECKING_KICK
CONFIG_BOOL_ADDON_CHANNEL
CONFIG_BOOL_CORPSE_EMPTY_LOOT_SHOW
CONFIG_BOOL_CORPSE_ALLOW_ALL_ITEMS_SHOW_IN_MASTER_LOOT
CONFIG_BOOL_DEATH_CORPSE_RECLAIM_DELAY_PVP
CONFIG_BOOL_DEATH_CORPSE_RECLAIM_DELAY_PVE
CONFIG_BOOL_DEATH_BONES_WORLD
CONFIG_BOOL_DEATH_BONES_BG_OR_ARENA
CONFIG_BOOL_TAXI_FLIGHT_CHAT_FIX
CONFIG_BOOL_LONG_TAXI_PATHS_PERSISTENCE
CONFIG_BOOL_ALL_TAXI_PATHS
CONFIG_BOOL_DECLINED_NAMES_USED
CONFIG_BOOL_SKILL_MILLING
CONFIG_BOOL_SKILL_FAIL_LOOT_FISHING
CONFIG_BOOL_SKILL_FAIL_GAIN_FISHING
CONFIG_BOOL_SKILL_FAIL_POSSIBLE_FISHINGPOOL
CONFIG_BOOL_BATTLEGROUND_CAST_DESERTER
CONFIG_BOOL_BATTLEGROUND_QUEUE_ANNOUNCER_START
CONFIG_BOOL_BATTLEGROUND_SCORE_STATISTICS
CONFIG_BOOL_ARENA_AUTO_DISTRIBUTE_POINTS
CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_JOIN
CONFIG_BOOL_ARENA_QUEUE_ANNOUNCER_EXIT
CONFIG_BOOL_OUTDOORPVP_SI_ENABLED
CONFIG_BOOL_OUTDOORPVP_EP_ENABLED
CONFIG_BOOL_OUTDOORPVP_HP_ENABLED
CONFIG_BOOL_OUTDOORPVP_ZM_ENABLED
CONFIG_BOOL_OUTDOORPVP_TF_ENABLED
CONFIG_BOOL_OUTDOORPVP_NA_ENABLED
CONFIG_BOOL_OUTDOORPVP_GH_ENABLED
CONFIG_BOOL_BATTLEFIELD_WG_ENABLED
CONFIG_BOOL_KICK_PLAYER_ON_BAD_PACKET
CONFIG_BOOL_STATS_SAVE_ONLY_ON_LOGOUT
CONFIG_BOOL_CLEAN_CHARACTER_DB
CONFIG_BOOL_VMAP_INDOOR_CHECK
CONFIG_BOOL_PET_UNSUMMON_AT_MOUNT
CONFIG_BOOL_PET_ATTACK_FROM_BEHIND
CONFIG_BOOL_AUTO_DOWNRANK
CONFIG_BOOL_MMAP_ENABLED
CONFIG_BOOL_PLAYER_COMMANDS
CONFIG_BOOL_AUTOLOAD_ACTIVE
CONFIG_BOOL_PATH_FIND_OPTIMIZE
CONFIG_BOOL_PATH_FIND_NORMALIZE_Z
CONFIG_BOOL_ALWAYS_SHOW_QUEST_GREETING
CONFIG_BOOL_VALUE_COUNT
Definition at line 326 of file World.h.
eConfigFloatValues
enum eConfigFloatValues
Server config.
Enumerator
CONFIG_FLOAT_RATE_HEALTH
CONFIG_FLOAT_RATE_POWER_MANA
CONFIG_FLOAT_RATE_POWER_RAGE_INCOME
CONFIG_FLOAT_RATE_POWER_RAGE_LOSS
CONFIG_FLOAT_RATE_POWER_RUNICPOWER_INCOME
CONFIG_FLOAT_RATE_POWER_RUNICPOWER_LOSS
CONFIG_FLOAT_RATE_POWER_FOCUS
CONFIG_FLOAT_RATE_POWER_ENERGY
CONFIG_FLOAT_RATE_SKILL_DISCOVERY
CONFIG_FLOAT_RATE_DROP_ITEM_POOR
CONFIG_FLOAT_RATE_DROP_ITEM_NORMAL
CONFIG_FLOAT_RATE_DROP_ITEM_UNCOMMON
CONFIG_FLOAT_RATE_DROP_ITEM_RARE
CONFIG_FLOAT_RATE_DROP_ITEM_EPIC
CONFIG_FLOAT_RATE_DROP_ITEM_LEGENDARY
CONFIG_FLOAT_RATE_DROP_ITEM_ARTIFACT
CONFIG_FLOAT_RATE_DROP_ITEM_REFERENCED
CONFIG_FLOAT_RATE_DROP_ITEM_QUEST
CONFIG_FLOAT_RATE_DROP_MONEY
CONFIG_FLOAT_RATE_PET_XP_KILL
CONFIG_FLOAT_RATE_XP_KILL
CONFIG_FLOAT_RATE_XP_QUEST
CONFIG_FLOAT_RATE_XP_EXPLORE
CONFIG_FLOAT_RATE_REPUTATION_GAIN
CONFIG_FLOAT_RATE_REPUTATION_LOWLEVEL_KILL
CONFIG_FLOAT_RATE_REPUTATION_LOWLEVEL_QUEST
CONFIG_FLOAT_RATE_CREATURE_NORMAL_HP
CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_HP
CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_HP
CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_HP
CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_HP
CONFIG_FLOAT_RATE_CREATURE_NORMAL_DAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_DAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_DAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_DAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_DAMAGE
CONFIG_FLOAT_RATE_CREATURE_NORMAL_SPELLDAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_ELITE_SPELLDAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_RAREELITE_SPELLDAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_WORLDBOSS_SPELLDAMAGE
CONFIG_FLOAT_RATE_CREATURE_ELITE_RARE_SPELLDAMAGE
CONFIG_FLOAT_RATE_CREATURE_AGGRO
CONFIG_FLOAT_RATE_REST_INGAME
CONFIG_FLOAT_RATE_REST_OFFLINE_IN_TAVERN_OR_CITY
CONFIG_FLOAT_RATE_REST_OFFLINE_IN_WILDERNESS
CONFIG_FLOAT_RATE_DAMAGE_FALL
CONFIG_FLOAT_RATE_AUCTION_TIME
CONFIG_FLOAT_RATE_AUCTION_DEPOSIT
CONFIG_FLOAT_RATE_AUCTION_CUT
CONFIG_FLOAT_RATE_HONOR
CONFIG_FLOAT_RATE_MINING_AMOUNT
CONFIG_FLOAT_RATE_MINING_NEXT
CONFIG_FLOAT_RATE_TALENT
CONFIG_FLOAT_RATE_CORPSE_DECAY_LOOTED
CONFIG_FLOAT_RATE_INSTANCE_RESET_TIME
CONFIG_FLOAT_RATE_DURABILITY_LOSS_DAMAGE
CONFIG_FLOAT_RATE_DURABILITY_LOSS_PARRY
CONFIG_FLOAT_RATE_DURABILITY_LOSS_ABSORB
CONFIG_FLOAT_RATE_DURABILITY_LOSS_BLOCK
CONFIG_FLOAT_SIGHT_GUARDER
CONFIG_FLOAT_SIGHT_MONSTER
CONFIG_FLOAT_LISTEN_RANGE_SAY
CONFIG_FLOAT_LISTEN_RANGE_YELL
CONFIG_FLOAT_LISTEN_RANGE_TEXTEMOTE
CONFIG_FLOAT_CREATURE_FAMILY_FLEE_ASSISTANCE_RADIUS
CONFIG_FLOAT_CREATURE_FAMILY_ASSISTANCE_RADIUS
CONFIG_FLOAT_CREATURE_CHECK_FOR_HELP_RADIUS
CONFIG_FLOAT_GROUP_XP_DISTANCE
CONFIG_FLOAT_GHOST_RUN_SPEED_WORLD
CONFIG_FLOAT_GHOST_RUN_SPEED_BG
CONFIG_FLOAT_LEASH_RADIUS
CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_FRIENDLY
CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_HONORED
CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_REVERED
CONFIG_FLOAT_MOD_DISCOUNT_REPUTATION_EXALTED
CONFIG_FLOAT_MOD_INCREASED_XP
CONFIG_FLOAT_MOD_INCREASED_GOLD
CONFIG_FLOAT_MAX_RECRUIT_A_FRIEND_DISTANCE
CONFIG_FLOAT_VALUE_COUNT
Definition at line 242 of file World.h.
eConfigInt32Values
enum eConfigInt32Values
Configuration elements.
Enumerator
CONFIG_INT32_DEATH_SICKNESS_LEVEL
CONFIG_INT32_ARENA_STARTRATING
CONFIG_INT32_ARENA_STARTPERSONALRATING
CONFIG_INT32_QUEST_LOW_LEVEL_HIDE_DIFF
CONFIG_INT32_QUEST_HIGH_LEVEL_HIDE_DIFF
CONFIG_INT32_VALUE_COUNT
Definition at line 231 of file World.h.
eConfigUInt32Values
enum eConfigUInt32Values
Configuration elements.
Enumerator
CONFIG_UINT32_COMPRESSION
CONFIG_UINT32_INTERVAL_SAVE
CONFIG_UINT32_INTERVAL_GRIDCLEAN
CONFIG_UINT32_INTERVAL_MAPUPDATE
CONFIG_UINT32_INTERVAL_CHANGEWEATHER
CONFIG_UINT32_PORT_WORLD
CONFIG_UINT32_GAME_TYPE
CONFIG_UINT32_REALM_ZONE
CONFIG_UINT32_STRICT_PLAYER_NAMES
CONFIG_UINT32_STRICT_CHARTER_NAMES
CONFIG_UINT32_STRICT_PET_NAMES
CONFIG_UINT32_MIN_PLAYER_NAME
CONFIG_UINT32_MIN_CHARTER_NAME
CONFIG_UINT32_MIN_PET_NAME
CONFIG_UINT32_CHARACTERS_CREATING_DISABLED
CONFIG_UINT32_CHARACTERS_PER_ACCOUNT
CONFIG_UINT32_CHARACTERS_PER_REALM
CONFIG_UINT32_HEROIC_CHARACTERS_PER_REALM
CONFIG_UINT32_MIN_LEVEL_FOR_HEROIC_CHARACTER_CREATING
CONFIG_UINT32_SKIP_CINEMATICS
CONFIG_UINT32_MAX_PLAYER_LEVEL
CONFIG_UINT32_START_PLAYER_LEVEL
CONFIG_UINT32_START_HEROIC_PLAYER_LEVEL
CONFIG_UINT32_START_PLAYER_MONEY
CONFIG_UINT32_MAX_HONOR_POINTS
CONFIG_UINT32_START_HONOR_POINTS
CONFIG_UINT32_MAX_ARENA_POINTS
CONFIG_UINT32_START_ARENA_POINTS
CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR
CONFIG_UINT32_INSTANCE_UNLOAD_DELAY
CONFIG_UINT32_MAX_SPELL_CASTS_IN_CHAIN
CONFIG_UINT32_BIRTHDAY_TIME
CONFIG_UINT32_RABBIT_DAY
CONFIG_UINT32_MAX_PRIMARY_TRADE_SKILL
CONFIG_UINT32_TRADE_SKILL_GMIGNORE_MAX_PRIMARY_COUNT
CONFIG_UINT32_TRADE_SKILL_GMIGNORE_LEVEL
CONFIG_UINT32_TRADE_SKILL_GMIGNORE_SKILL
CONFIG_UINT32_MIN_PETITION_SIGNS
CONFIG_UINT32_GM_LOGIN_STATE
CONFIG_UINT32_GM_VISIBLE_STATE
CONFIG_UINT32_GM_ACCEPT_TICKETS
CONFIG_UINT32_GM_LEVEL_ACCEPT_TICKETS
CONFIG_UINT32_GM_CHAT
CONFIG_UINT32_GM_LEVEL_CHAT
CONFIG_UINT32_GM_LEVEL_CHANNEL_MODERATION
CONFIG_UINT32_GM_LEVEL_CHANNEL_SILENT_JOIN
CONFIG_UINT32_GM_WISPERING_TO
CONFIG_UINT32_GM_LEVEL_IN_GM_LIST
CONFIG_UINT32_GM_LEVEL_IN_WHO_LIST
CONFIG_UINT32_START_GM_LEVEL
CONFIG_UINT32_GM_INVISIBLE_AURA
CONFIG_UINT32_MAIL_DELIVERY_DELAY
CONFIG_UINT32_MASS_MAILER_SEND_PER_TICK
CONFIG_UINT32_UPTIME_UPDATE
CONFIG_UINT32_NUM_MAP_THREADS
CONFIG_UINT32_AUCTION_DEPOSIT_MIN
CONFIG_UINT32_SKILL_CHANCE_ORANGE
CONFIG_UINT32_SKILL_CHANCE_YELLOW
CONFIG_UINT32_SKILL_CHANCE_GREEN
CONFIG_UINT32_SKILL_CHANCE_GREY
CONFIG_UINT32_SKILL_CHANCE_MINING_STEPS
CONFIG_UINT32_SKILL_CHANCE_SKINNING_STEPS
CONFIG_UINT32_SKILL_GAIN_CRAFTING
CONFIG_UINT32_SKILL_GAIN_DEFENSE
CONFIG_UINT32_SKILL_GAIN_GATHERING
CONFIG_UINT32_SKILL_GAIN_WEAPON
CONFIG_UINT32_MAX_OVERSPEED_PINGS
CONFIG_UINT32_EXPANSION
CONFIG_UINT32_CHATFLOOD_MESSAGE_COUNT
CONFIG_UINT32_CHATFLOOD_MESSAGE_DELAY
CONFIG_UINT32_CHATFLOOD_MUTE_TIME
CONFIG_UINT32_CREATURE_FAMILY_ASSISTANCE_DELAY
CONFIG_UINT32_CREATURE_FAMILY_FLEE_DELAY
CONFIG_UINT32_WORLD_BOSS_LEVEL_DIFF
CONFIG_UINT32_QUEST_DAILY_RESET_HOUR
CONFIG_UINT32_QUEST_WEEKLY_RESET_WEEK_DAY
CONFIG_UINT32_QUEST_WEEKLY_RESET_HOUR
CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_SEVERITY
CONFIG_UINT32_CHAT_STRICT_LINK_CHECKING_KICK
CONFIG_UINT32_CHANNEL_RESTRICTED_LANGUAGE_MODE
CONFIG_UINT32_CORPSE_DECAY_NORMAL
CONFIG_UINT32_CORPSE_DECAY_RARE
CONFIG_UINT32_CORPSE_DECAY_ELITE
CONFIG_UINT32_CORPSE_DECAY_RAREELITE
CONFIG_UINT32_CORPSE_DECAY_WORLDBOSS
CONFIG_UINT32_INSTANT_LOGOUT
CONFIG_UINT32_BATTLEGROUND_INVITATION_TYPE
CONFIG_UINT32_BATTLEGROUND_PREMATURE_FINISH_TIMER
CONFIG_UINT32_BATTLEGROUND_PREMADE_GROUP_WAIT_FOR_MATCH
CONFIG_UINT32_BATTLEGROUND_QUEUE_ANNOUNCER_JOIN
CONFIG_UINT32_BATTLEGROUND_RANDOM_RESET_HOUR
CONFIG_UINT32_ARENA_MAX_RATING_DIFFERENCE
CONFIG_UINT32_ARENA_RATING_DISCARD_TIMER
CONFIG_UINT32_ARENA_AUTO_DISTRIBUTE_INTERVAL_DAYS
CONFIG_UINT32_ARENA_SEASON_ID
CONFIG_UINT32_ARENA_FIRST_RESET_DAY
CONFIG_UINT32_ARENA_SEASON_PREVIOUS_ID
CONFIG_UINT32_GROUP_OFFLINE_LEADER_DELAY
CONFIG_UINT32_BATTLEFIELD_COOLDOWN_DURATION
CONFIG_UINT32_BATTLEFIELD_BATTLE_DURATION
CONFIG_UINT32_BATTLEFIELD_MAX_PLAYERS_PER_TEAM
CONFIG_UINT32_CLIENTCACHE_VERSION
CONFIG_UINT32_GUILD_EVENT_LOG_COUNT
CONFIG_UINT32_GUILD_BANK_EVENT_LOG_COUNT
CONFIG_UINT32_MIRRORTIMER_FATIGUE_MAX
CONFIG_UINT32_MIRRORTIMER_BREATH_MAX
CONFIG_UINT32_MIRRORTIMER_ENVIRONMENTAL_MAX
CONFIG_UINT32_ENVIRONMENTAL_DAMAGE_MIN
CONFIG_UINT32_ENVIRONMENTAL_DAMAGE_MAX
CONFIG_UINT32_INTERACTION_PAUSE_TIMER
CONFIG_UINT32_MIN_LEVEL_STAT_SAVE
CONFIG_UINT32_CHARDELETE_KEEP_DAYS
CONFIG_UINT32_CHARDELETE_METHOD
CONFIG_UINT32_CHARDELETE_MIN_LEVEL
CONFIG_UINT32_GUID_RESERVE_SIZE_CREATURE
CONFIG_UINT32_GUID_RESERVE_SIZE_GAMEOBJECT
CONFIG_UINT32_MIN_LEVEL_FOR_RAID
CONFIG_UINT32_CREATURE_RESPAWN_AGGRO_DELAY
CONFIG_UINT32_CREATURE_CHECK_FOR_HELP_AGGRO_DELAY
CONFIG_UINT32_MAX_WHOLIST_RETURNS
CONFIG_UINT32_FOGOFWAR_STEALTH
CONFIG_UINT32_FOGOFWAR_HEALTH
CONFIG_UINT32_FOGOFWAR_STATS
CONFIG_UINT32_CREATURE_PICKPOCKET_RESTOCK_DELAY
CONFIG_UINT32_CHANNEL_STATIC_AUTO_TRESHOLD
CONFIG_UINT32_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL
CONFIG_UINT32_MAX_RECRUIT_A_FRIEND_BONUS_PLAYER_LEVEL_DIFFERENCE
CONFIG_UINT32_SUNSREACH_COUNTER
CONFIG_UINT32_VALUE_COUNT
Definition at line 97 of file World.h.
RealmType
enum RealmType
Type of server, this is values from second column of Cfg_Configs.dbc (1.12.1 have another numeration)
Enumerator
REALM_TYPE_NORMAL
REALM_TYPE_PVP
REALM_TYPE_NORMAL2
REALM_TYPE_RP
REALM_TYPE_RPPVP
REALM_TYPE_FFA_PVP
Definition at line 421 of file World.h.
RealmZone
enum RealmZone
This is values from first column of Cfg_Categories.dbc (1.12.1 have another numeration)
Enumerator
REALM_ZONE_UNKNOWN
REALM_ZONE_DEVELOPMENT
REALM_ZONE_UNITED_STATES
REALM_ZONE_OCEANIC
REALM_ZONE_LATIN_AMERICA
REALM_ZONE_TOURNAMENT_5
REALM_ZONE_KOREA
REALM_ZONE_TOURNAMENT_7
REALM_ZONE_ENGLISH
REALM_ZONE_GERMAN
REALM_ZONE_FRENCH
REALM_ZONE_SPANISH
REALM_ZONE_RUSSIAN
REALM_ZONE_TOURNAMENT_13
REALM_ZONE_TAIWAN
REALM_ZONE_TOURNAMENT_15
REALM_ZONE_CHINA
REALM_ZONE_CN1
REALM_ZONE_CN2
REALM_ZONE_CN3
REALM_ZONE_CN4
REALM_ZONE_CN5
REALM_ZONE_CN6
REALM_ZONE_CN7
REALM_ZONE_CN8
REALM_ZONE_TOURNAMENT_25
REALM_ZONE_TEST_SERVER
REALM_ZONE_TOURNAMENT_27
REALM_ZONE_QA_SERVER
REALM_ZONE_CN9
REALM_ZONE_TEST_SERVER_2
REALM_ZONE_CN10
REALM_ZONE_CTC
REALM_ZONE_CNC
REALM_ZONE_CN1_4
REALM_ZONE_CN2_6_9
REALM_ZONE_CN3_7
REALM_ZONE_CN5_8
Definition at line 433 of file World.h.
ServerMessageType
enum ServerMessageType
Enumerator
SERVER_MSG_SHUTDOWN_TIME
SERVER_MSG_RESTART_TIME
SERVER_MSG_CUSTOM
SERVER_MSG_SHUTDOWN_CANCELLED
SERVER_MSG_RESTART_CANCELLED
SERVER_MSG_BG_SHUTDOWN_TIME
SERVER_MSG_BG_RESTART_TIME
SERVER_MSG_INSTANCE_SHUTDOWN_TIME
SERVER_MSG_INSTANCE_RESTART_TIME
Definition at line 55 of file World.h.
ShutdownExitCode
enum ShutdownExitCode
Enumerator
SHUTDOWN_EXIT_CODE
ERROR_EXIT_CODE
RESTART_EXIT_CODE
Definition at line 74 of file World.h.
ShutdownMask
enum ShutdownMask
Enumerator
SHUTDOWN_MASK_RESTART
SHUTDOWN_MASK_IDLE
Definition at line 68 of file World.h.
WeatherState
enum WeatherState
Enumerator
WEATHER_STATE_FINE
WEATHER_STATE_LIGHT_RAIN
WEATHER_STATE_MEDIUM_RAIN
WEATHER_STATE_HEAVY_RAIN
WEATHER_STATE_LIGHT_SNOW
WEATHER_STATE_MEDIUM_SNOW
WEATHER_STATE_HEAVY_SNOW
WEATHER_STATE_LIGHT_SANDSTORM
WEATHER_STATE_MEDIUM_SANDSTORM
WEATHER_STATE_HEAVY_SANDSTORM
WEATHER_STATE_THUNDERS
WEATHER_STATE_BLACKRAIN
Definition at line 37 of file Weather.h.
WorldTimers
enum WorldTimers
Timers for different object refresh rates.
Enumerator
WUPDATE_AUCTIONS
WUPDATE_UPTIME
WUPDATE_CORPSES
WUPDATE_EVENTS
WUPDATE_DELETECHARS
WUPDATE_AHBOT
WUPDATE_GROUPS
WUPDATE_RAID_BROWSER
WUPDATE_METRICS
WUPDATE_COUNT
Definition at line 82 of file World.h.
Function Documentation
FindOrCreateWeather()
Weather * WeatherSystem::FindOrCreateWeather (uint32 zoneId)
Find or Create a Weather object by the given zoneid.
Definition at line 352 of file Weather.cpp.
References WeatherSystem::m_weathers, and sWeatherMgr.
Referenced by Map::SetWeather(), and Player::UpdateZone().
GetWeatherChances()
WeatherZoneChances const* WeatherMgr::GetWeatherChances (uint32 zone_id) const inline
Definition at line 151 of file Weather.h.
References WeatherMgr::mWeatherZoneMap.
GetWeatherState()
WeatherState Weather::GetWeatherState () const private
Calculate state based on type and grade.
Definition at line 238 of file Weather.cpp.
References Weather::m_grade, Weather::m_type, WEATHER_STATE_BLACKRAIN, WEATHER_STATE_FINE, WEATHER_STATE_HEAVY_RAIN, WEATHER_STATE_HEAVY_SANDSTORM, WEATHER_STATE_HEAVY_SNOW, WEATHER_STATE_LIGHT_RAIN, WEATHER_STATE_LIGHT_SANDSTORM, WEATHER_STATE_LIGHT_SNOW, WEATHER_STATE_MEDIUM_RAIN, WEATHER_STATE_MEDIUM_SANDSTORM, WEATHER_STATE_MEDIUM_SNOW, WEATHER_STATE_THUNDERS, WEATHER_TYPE_BLACKRAIN, WEATHER_TYPE_FINE, WEATHER_TYPE_RAIN, WEATHER_TYPE_SNOW, WEATHER_TYPE_STORM, and WEATHER_TYPE_THUNDERS.
Referenced by Weather::SendWeatherForPlayersInZone(), and Weather::SendWeatherUpdateToPlayer().
IsValidWeatherType()
static bool Weather::IsValidWeatherType (uint32 type) inline static
Check if a type is valid.
Definition at line 69 of file Weather.h.
References WEATHER_TYPE_BLACKRAIN, WEATHER_TYPE_FINE, WEATHER_TYPE_RAIN, WEATHER_TYPE_SNOW, WEATHER_TYPE_STORM, and WEATHER_TYPE_THUNDERS.
Referenced by ChatHandler::HandleChangeWeatherCommand().
LoadWeatherZoneChances()
void WeatherMgr::LoadWeatherZoneChances ()
Load Weather chanced from table game_weather.
Definition at line 383 of file Weather.cpp.
References WeatherZoneChances::data, QueryResult::Fetch(), QueryResult::GetRowCount(), Field::GetUInt32(), MAX_WEATHER_TYPE, WeatherMgr::mWeatherZoneMap, QueryResult::NextRow(), Database::Query(), WeatherSeasonChances::rainChance, sLog, WeatherSeasonChances::snowChance, BarGoLink::step(), WeatherSeasonChances::stormChance, WEATHER_SEASONS, and WorldDatabase.
LogWeatherState()
void Weather::LogWeatherState (WeatherState state) const private
Definition at line 288 of file Weather.cpp.
References DETAIL_FILTER_LOG, LOG_FILTER_WEATHER, Weather::m_grade, Weather::m_type, Weather::m_zone, WEATHER_STATE_BLACKRAIN, WEATHER_STATE_FINE, WEATHER_STATE_HEAVY_RAIN, WEATHER_STATE_HEAVY_SANDSTORM, WEATHER_STATE_HEAVY_SNOW, WEATHER_STATE_LIGHT_RAIN, WEATHER_STATE_LIGHT_SANDSTORM, WEATHER_STATE_LIGHT_SNOW, WEATHER_STATE_MEDIUM_RAIN, WEATHER_STATE_MEDIUM_SANDSTORM, WEATHER_STATE_MEDIUM_SNOW, and WEATHER_STATE_THUNDERS.
Referenced by Weather::SendWeatherForPlayersInZone().
NormalizeGrade()
void Weather::NormalizeGrade () private
Definition at line 279 of file Weather.cpp.
References Weather::m_grade.
Referenced by Weather::ReGenerate(), Weather::SendWeatherForPlayersInZone(), and Weather::SendWeatherUpdateToPlayer().
ReGenerate()
bool Weather::ReGenerate () private
Calculate new weather.
Calculate the new weather, returns true if and only if the weather changed.
Weather statistics:
30% - no change
30% - weather gets better (if not fine) or change weather type
30% - weather worsens (if not fine)
10% - radical change (if not fine)
Radical change:
if light -> heavy
if medium -> change weather type
if heavy -> 50% light, 50% change weather type
New weather statistics (if not fine):
85% light
7% medium
7% heavy If fine 100% sun (no fog)
Definition at line 65 of file Weather.cpp.
References WeatherZoneChances::data, DEBUG_FILTER_LOG, LOG_FILTER_WEATHER, Weather::m_grade, Weather::m_isPermanentWeather, Weather::m_type, Weather::m_weatherChances, Weather::m_zone, Weather::NormalizeGrade(), WeatherSeasonChances::rainChance, rand_norm_f(), WeatherSeasonChances::snowChance, WeatherSeasonChances::stormChance, sWorld, urand(), WEATHER_SEASONS, WEATHER_TYPE_FINE, WEATHER_TYPE_RAIN, WEATHER_TYPE_SNOW, and WEATHER_TYPE_STORM.
Referenced by Weather::Update().
SendWeatherForPlayersInZone()
bool Weather::SendWeatherForPlayersInZone (Map const * _map) private
Send SMSG_WEATHER to all players in the zone.
Send the weather packet to all players in this zone
Log the event
Definition at line 204 of file Weather.cpp.
References Weather::GetWeatherState(), Weather::LogWeatherState(), Weather::m_grade, Weather::m_zone, Weather::NormalizeGrade(), Map::SendToPlayersInZone(), and SMSG_WEATHER.
Referenced by Weather::SetWeather(), and Weather::Update().
SendWeatherUpdateToPlayer()
void Weather::SendWeatherUpdateToPlayer (Player * player)
Send Weather to one player.
Definition at line 191 of file Weather.cpp.
References Player::GetSession(), Weather::GetWeatherState(), Weather::m_grade, Weather::NormalizeGrade(), WorldSession::SendPacket(), and SMSG_WEATHER.
Referenced by Player::UpdateZone().
SetWeather()
void Weather::SetWeather (WeatherType type, float grade, Map const * _map, bool isPermanent)
Set the weather.
Definition at line 225 of file Weather.cpp.
References Weather::m_grade, Weather::m_isPermanentWeather, Weather::m_type, and Weather::SendWeatherForPlayersInZone().
Referenced by Map::SetWeather().
Update()
bool Weather::Update (uint32 diff, Map const * _map)
Update the weather in this zone, when the timer is expired the weather will be rolled again.
Launch a weather update.
If the timer has passed, ReGenerate the weather
Weather will be removed if not updated (no players in zone anymore)
Definition at line 45 of file Weather.cpp.
References Weather::m_timer, ShortIntervalTimer::Passed(), Weather::ReGenerate(), ShortIntervalTimer::Reset(), Weather::SendWeatherForPlayersInZone(), and ShortIntervalTimer::Update().
UpdateWeathers()
void WeatherSystem::UpdateWeathers (uint32 diff)
Update Weathers for the different zones.
Send an update signal to Weather objects
and remove Weather objects for zones with no player
Definition at line 365 of file Weather.cpp.
References WeatherSystem::m_map, and WeatherSystem::m_weathers.
Referenced by Map::Update().
Weather()
Weather::Weather (uint32 zone, WeatherZoneChances const * weatherChances)
Create the Weather object.
Definition at line 33 of file Weather.cpp.
References CONFIG_UINT32_INTERVAL_CHANGEWEATHER, DETAIL_FILTER_LOG, ShortIntervalTimer::GetInterval(), IN_MILLISECONDS, LOG_FILTER_WEATHER, Weather::m_timer, Weather::m_zone, MINUTE, ShortIntervalTimer::SetInterval(), and sWorld.
WeatherMgr()
WeatherMgr::WeatherMgr () inline
Definition at line 146 of file Weather.h.
WeatherSystem()
WeatherSystem::WeatherSystem (Map const * _map)
Definition at line 339 of file Weather.cpp.
~Weather()
Weather::~Weather () inline
Definition at line 60 of file Weather.h.
~WeatherMgr()
WeatherMgr::~WeatherMgr () inline
Definition at line 147 of file Weather.h.
~WeatherSystem()
WeatherSystem::~WeatherSystem ()
Empty the WeatherMap
Definition at line 342 of file Weather.cpp.
References WeatherSystem::m_weathers.
Variable Documentation
data
WeatherSeasonChances WeatherZoneChances::data[WEATHER_SEASONS]
Definition at line 140 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherZoneChances(), and Weather::ReGenerate().
m_grade
float Weather::m_grade private
Definition at line 99 of file Weather.h.
Referenced by Weather::GetWeatherState(), Weather::LogWeatherState(), Weather::NormalizeGrade(), Weather::ReGenerate(), Weather::SendWeatherForPlayersInZone(), Weather::SendWeatherUpdateToPlayer(), and Weather::SetWeather().
m_isPermanentWeather
bool Weather::m_isPermanentWeather private
Definition at line 102 of file Weather.h.
Referenced by Weather::ReGenerate(), and Weather::SetWeather().
m_map
Map const* const WeatherSystem::m_map private
Definition at line 120 of file Weather.h.
Referenced by WeatherSystem::UpdateWeathers().
m_timer
ShortIntervalTimer Weather::m_timer private
Definition at line 100 of file Weather.h.
Referenced by Weather::Update(), and Weather::Weather().
m_type
WeatherType Weather::m_type private
Definition at line 98 of file Weather.h.
Referenced by Weather::GetWeatherState(), Weather::LogWeatherState(), Weather::ReGenerate(), and Weather::SetWeather().
m_weatherChances
WeatherZoneChances const* Weather::m_weatherChances private
Definition at line 101 of file Weather.h.
Referenced by Weather::ReGenerate().
m_weathers
WeatherMap WeatherSystem::m_weathers private
Definition at line 123 of file Weather.h.
Referenced by WeatherSystem::FindOrCreateWeather(), WeatherSystem::UpdateWeathers(), and WeatherSystem::~WeatherSystem().
m_zone
uint32 Weather::m_zone private
Definition at line 97 of file Weather.h.
Referenced by Weather::LogWeatherState(), Weather::ReGenerate(), Weather::SendWeatherForPlayersInZone(), and Weather::Weather().
mWeatherZoneMap
WeatherZoneMap WeatherMgr::mWeatherZoneMap private
Definition at line 161 of file Weather.h.
Referenced by WeatherMgr::GetWeatherChances(), and WeatherMgr::LoadWeatherZoneChances().
rainChance
uint32 WeatherSeasonChances::rainChance
Definition at line 133 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherZoneChances(), and Weather::ReGenerate().
realmID
uint32 realmID extern
Id of the realm.
Definition at line 66 of file mangosd/Main.cpp.
Referenced by Master::_StartDB(), World::_UpdateRealmCharCount(), World::AddSession_(), Master::clearOnlineAccounts(), ChatHandler::HandleAccountOnlineListCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandlePlayerLogin(), NamreebAnticheat::Antispam::Notify(), Master::Run(), World::SetInitialWorldSettings(), World::SetPlayerLimit(), NamreebAnticheat::Antispam::Silence(), WardenWin::Update(), and World::Update().
snowChance
uint32 WeatherSeasonChances::snowChance
Definition at line 134 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherZoneChances(), and Weather::ReGenerate().
stormChance
uint32 WeatherSeasonChances::stormChance
Definition at line 135 of file Weather.h.
Referenced by WeatherMgr::LoadWeatherZoneChances(), and Weather::ReGenerate().