CMaNGOS_WoTLK: Group.cpp File Reference
Group.cpp File Reference
#include "Common.h"
#include "Server/Opcodes.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "Entities/Player.h"
#include "Globals/ObjectMgr.h"
#include "Entities/ObjectGuid.h"
#include "Entities/UpdateData.h"
#include "Entities/UpdateMask.h"
#include "Groups/Group.h"
#include "Tools/Formulas.h"
#include "Globals/ObjectAccessor.h"
#include "BattleGround/BattleGround.h"
#include "BattleGround/BattleGroundMgr.h"
#include "Maps/MapManager.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Spells/SpellAuras.h"
Functions
GroupMemberStatus GetGroupMemberStatus (const Player *member=nullptr)
static void GetDataForXPAtKill_helper (Player *player, Unit const *victim, uint32 &sum_level, Player *&member_with_max_level, Player *&not_gray_member_with_max_level)
static void RewardGroupAtKill_helper (Player *pGroupGuy, Unit *pVictim, uint32 count, bool PvP, float group_rate, uint32 sum_level, bool is_dungeon, Player *not_gray_member_with_max_level, Player *member_with_max_level, uint32 xp)
Function Documentation
GetDataForXPAtKill_helper()
static void GetDataForXPAtKill_helper (Player * player, Unit const * victim, uint32 & sum_level, Player *& member_with_max_level, Player *& not_gray_member_with_max_level) static
Definition at line 588 of file Group.cpp.
References Unit::GetLevel(), Unit::GetLevelForTarget(), and MaNGOS::XP::IsTrivialLevelDifference().
Referenced by Group::GetDataForXPAtKill().
GetGroupMemberStatus()
GroupMemberStatus GetGroupMemberStatus (const Player * member = nullptr)
Definition at line 42 of file Group.cpp.
References MEMBER_STATUS_AFK, MEMBER_STATUS_DEAD, MEMBER_STATUS_DND, MEMBER_STATUS_GHOST, MEMBER_STATUS_OFFLINE, MEMBER_STATUS_ONLINE, MEMBER_STATUS_PVP, MEMBER_STATUS_PVP_FFA, MEMBER_STATUS_ZONE_OUT, PLAYER_FLAGS, and PLAYER_FLAGS_GHOST.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket(), WorldSession::HandleRequestPartyMemberStatsOpcode(), and Group::SendUpdateTo().
RewardGroupAtKill_helper()
static void RewardGroupAtKill_helper (Player * pGroupGuy, Unit * pVictim, uint32 count, bool PvP, float group_rate, uint32 sum_level, bool is_dungeon, Player * not_gray_member_with_max_level, Player * member_with_max_level, uint32 xp) static
Definition at line 1622 of file Group.cpp.
References MaNGOS::XP::Gain(), Creature::GetCreatureInfo(), Unit::GetLevel(), Unit::GetPet(), Object::GetTypeId(), Player::GiveXP(), Object::HasFlag(), Unit::IsAlive(), Player::KilledMonster(), Player::KilledPlayerCredit(), PLAYER_FLAGS, PLAYER_FLAGS_GHOST, Player::RewardHonor(), Player::RewardReputation(), TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by Group::RewardGroupAtKill().