CMaNGOS_WoTLK: Group.h File Reference
Group.h File Reference
#include "Common.h"
#include "Entities/ObjectGuid.h"
#include "GroupReference.h"
#include "GroupRefManager.h"
#include "BattleGround/BattleGround.h"
#include "Battlefield/Battlefield.h"
#include "Server/DBCEnums.h"
#include "Globals/SharedDefines.h"
#include "LFG/LFG.h"
Data Structures
struct InstanceGroupBind
class Group
request member stats checken
struct Group::MemberSlot
Macros
#define MAX_GROUP_SIZE 5
#define MAX_RAID_SIZE 40
#define MAX_RAID_SUBGROUPS (MAX_RAID_SIZE / MAX_GROUP_SIZE)
#define TARGET_ICON_COUNT 8
#define GROUP_UPDATE_FLAGS_COUNT 20
Enumerations
enum GroupMemberStatus {
MEMBER_STATUS_OFFLINE = 0x0000 , MEMBER_STATUS_ONLINE = 0x0001 , MEMBER_STATUS_PVP = 0x0002 , MEMBER_STATUS_DEAD = 0x0004 ,
MEMBER_STATUS_GHOST = 0x0008 , MEMBER_STATUS_PVP_FFA = 0x0010 , MEMBER_STATUS_ZONE_OUT = 0x0020 , MEMBER_STATUS_AFK = 0x0040 ,
MEMBER_STATUS_DND = 0x0080
}
enum GroupType {
GROUP_FLAG_NORMAL = 0x00 , GROUP_FLAG_BG = 0x01 , GROUP_FLAG_RAID = 0x02 , GROUP_FLAGS_BGRAID = GROUP_FLAG_BG | GROUP_FLAG_RAID ,
GROUP_FLAG_LFG_RESTRICTED = 0x04 , GROUP_FLAG_LFG = 0x08 , GROUP_FLAG_DESTROYED = 0x010
}
enum GroupFlagMask { GROUP_ASSISTANT = 0x01 , GROUP_MAIN_ASSISTANT = 0x02 , GROUP_MAIN_TANK = 0x04 }
enum GroupUpdateFlags {
GROUP_UPDATE_FLAG_NONE = 0x00000000 , GROUP_UPDATE_FLAG_STATUS = 0x00000001 , GROUP_UPDATE_FLAG_CUR_HP = 0x00000002 , GROUP_UPDATE_FLAG_MAX_HP = 0x00000004 ,
GROUP_UPDATE_FLAG_POWER_TYPE = 0x00000008 , GROUP_UPDATE_FLAG_CUR_POWER = 0x00000010 , GROUP_UPDATE_FLAG_MAX_POWER = 0x00000020 , GROUP_UPDATE_FLAG_LEVEL = 0x00000040 ,
GROUP_UPDATE_FLAG_ZONE = 0x00000080 , GROUP_UPDATE_FLAG_POSITION = 0x00000100 , GROUP_UPDATE_FLAG_AURAS = 0x00000200 , GROUP_UPDATE_FLAG_PET_GUID = 0x00000400 ,
GROUP_UPDATE_FLAG_PET_NAME = 0x00000800 , GROUP_UPDATE_FLAG_PET_MODEL_ID = 0x00001000 , GROUP_UPDATE_FLAG_PET_CUR_HP = 0x00002000 , GROUP_UPDATE_FLAG_PET_MAX_HP = 0x00004000 ,
GROUP_UPDATE_FLAG_PET_POWER_TYPE = 0x00008000 , GROUP_UPDATE_FLAG_PET_CUR_POWER = 0x00010000 , GROUP_UPDATE_FLAG_PET_MAX_POWER = 0x00020000 , GROUP_UPDATE_FLAG_PET_AURAS = 0x00040000 ,
GROUP_UPDATE_FLAG_VEHICLE_SEAT = 0x00080000 , GROUP_UPDATE_PET = 0x0007FC00 , GROUP_UPDATE_FULL = 0x0007FFFF
}
Functions
GroupMemberStatus GetGroupMemberStatus (const Player *member)
Variables
static const uint8 GroupUpdateLength [GROUP_UPDATE_FLAGS_COUNT] = { 0, 2, 2, 2, 1, 2, 2, 2, 2, 4, 8, 8, 1, 2, 2, 2, 1, 2, 2, 8}
Macro Definition Documentation
GROUP_UPDATE_FLAGS_COUNT
#define GROUP_UPDATE_FLAGS_COUNT 20
Definition at line 107 of file Group.h.
MAX_GROUP_SIZE
#define MAX_GROUP_SIZE 5
Definition at line 42 of file Group.h.
MAX_RAID_SIZE
#define MAX_RAID_SIZE 40
Definition at line 43 of file Group.h.
MAX_RAID_SUBGROUPS
#define MAX_RAID_SUBGROUPS (MAX_RAID_SIZE / MAX_GROUP_SIZE)
Definition at line 44 of file Group.h.
TARGET_ICON_COUNT
#define TARGET_ICON_COUNT 8
Definition at line 45 of file Group.h.
Enumeration Type Documentation
GroupFlagMask
enum GroupFlagMask
Enumerator
GROUP_ASSISTANT
GROUP_MAIN_ASSISTANT
GROUP_MAIN_TANK
Definition at line 73 of file Group.h.
GroupMemberStatus
enum GroupMemberStatus
Enumerator
MEMBER_STATUS_OFFLINE
MEMBER_STATUS_ONLINE
MEMBER_STATUS_PVP
MEMBER_STATUS_DEAD
MEMBER_STATUS_GHOST
MEMBER_STATUS_PVP_FFA
MEMBER_STATUS_ZONE_OUT
MEMBER_STATUS_AFK
MEMBER_STATUS_DND
Definition at line 47 of file Group.h.
GroupType
enum GroupType
Enumerator
GROUP_FLAG_NORMAL
GROUP_FLAG_BG
GROUP_FLAG_RAID
GROUP_FLAGS_BGRAID
GROUP_FLAG_LFG_RESTRICTED
GROUP_FLAG_LFG
GROUP_FLAG_DESTROYED
Definition at line 62 of file Group.h.
GroupUpdateFlags
enum GroupUpdateFlags
Enumerator
GROUP_UPDATE_FLAG_NONE
GROUP_UPDATE_FLAG_STATUS
GROUP_UPDATE_FLAG_CUR_HP
GROUP_UPDATE_FLAG_MAX_HP
GROUP_UPDATE_FLAG_POWER_TYPE
GROUP_UPDATE_FLAG_CUR_POWER
GROUP_UPDATE_FLAG_MAX_POWER
GROUP_UPDATE_FLAG_LEVEL
GROUP_UPDATE_FLAG_ZONE
GROUP_UPDATE_FLAG_POSITION
GROUP_UPDATE_FLAG_AURAS
GROUP_UPDATE_FLAG_PET_GUID
GROUP_UPDATE_FLAG_PET_NAME
GROUP_UPDATE_FLAG_PET_MODEL_ID
GROUP_UPDATE_FLAG_PET_CUR_HP
GROUP_UPDATE_FLAG_PET_MAX_HP
GROUP_UPDATE_FLAG_PET_POWER_TYPE
GROUP_UPDATE_FLAG_PET_CUR_POWER
GROUP_UPDATE_FLAG_PET_MAX_POWER
GROUP_UPDATE_FLAG_PET_AURAS
GROUP_UPDATE_FLAG_VEHICLE_SEAT
GROUP_UPDATE_PET
GROUP_UPDATE_FULL
Definition at line 80 of file Group.h.
Function Documentation
GetGroupMemberStatus()
GroupMemberStatus GetGroupMemberStatus (const Player * member)
Definition at line 42 of file Group.cpp.
References MEMBER_STATUS_AFK, MEMBER_STATUS_DEAD, MEMBER_STATUS_DND, MEMBER_STATUS_GHOST, MEMBER_STATUS_OFFLINE, MEMBER_STATUS_ONLINE, MEMBER_STATUS_PVP, MEMBER_STATUS_PVP_FFA, MEMBER_STATUS_ZONE_OUT, PLAYER_FLAGS, and PLAYER_FLAGS_GHOST.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket(), WorldSession::HandleRequestPartyMemberStatsOpcode(), and Group::SendUpdateTo().
Variable Documentation
GroupUpdateLength
const uint8 GroupUpdateLength[GROUP_UPDATE_FLAGS_COUNT] = { 0, 2, 2, 2, 1, 2, 2, 2, 2, 4, 8, 8, 1, 2, 2, 2, 1, 2, 2, 8} static
Definition at line 109 of file Group.h.
Referenced by WorldSession::BuildPartyMemberStatsChangedPacket().