CMaNGOS_WoTLK: to provide abstract support for transported entities
to provide abstract support for transported entities
The Transport System in MaNGOS consists of these files:
Files
file Vehicle.cpp
This file contains the code needed for CMaNGOS to support vehicles Currently implemented.
file Vehicle.h
This file contains the headers for the functionality required by Vehicles.
file TransportSystem.cpp
This file contains the code needed for MaNGOS to provide abstract support for transported entities Currently implemented.
file TransportSystem.h
This file contains the headers for base clases needed for MaNGOS to handle passengers on transports.
Data Structures
struct VehicleAccessory
struct VehicleSeatParameters
class VehicleInfo
A class to provide support for each vehicle.
class TransportBase
A class to provide basic support for each transporter.
class TransportInfo
A class to provide basic information for each transported passenger.
Typedefs
typedef std::map< uint8, VehicleSeatEntry const * > VehicleSeatMap
typedef std::unordered_map< WorldObject *, TransportInfo * > PassengerMap
Enumerations
enum ExitParamType { SEAT_EXIT_PARAMS_OFFSET = 1 , SEAT_EXIT_PARAMS_ABSOLUTE_POS = 2 }
Functions
void ObjectMgr::LoadVehicleAccessory ()
void ObjectMgr::LoadVehicleSeatParameters ()
VehicleInfo::VehicleInfo (Unit *owner, VehicleEntry const *vehicleEntry, uint32 overwriteNpcEntry)
Constructor of VehicleInfo.
VehicleInfo::~VehicleInfo ()
void VehicleInfo::Initialize ()
Initializes the accessories.
void VehicleInfo::Board (Unit *passenger, uint8 seat)
This function will board a passenger onto a vehicle.
void VehicleInfo::ChangeSeat (Unit *passenger, uint8 currentSeat, bool next)
void VehicleInfo::SwitchSeat (Unit *passenger, uint8 seat)
This function will switch the seat of a passenger on the same vehicle.
void VehicleInfo::UnBoard (Unit *passenger, bool changeVehicle)
This function will Unboard a passenger.
bool VehicleInfo::CanBoard (Unit *passenger) const
This function will check if a passenger can be boarded.
Unit * VehicleInfo::GetPassenger (uint8 seat) const
void VehicleInfo::CalculateBoardingPositionOf (float gx, float gy, float gz, float go, float &lx, float &ly, float &lz, float &lo) const
void VehicleInfo::RemoveAccessoriesFromMap ()
Unsummones accessory in case of far-teleport or death.
void VehicleInfo::TeleportPassengers (uint32 mapId)
VehicleSeatEntry const * VehicleInfo::GetSeatEntry (uint8 seat) const
Get the Vehicle SeatEntry of a seat by position.
VehicleSeatEntry const * VehicleInfo::GetSeatForPassenger (Unit const *passenger) const
bool VehicleInfo::GetUsableSeatFor (Unit *passenger, uint8 &seat, bool reset, bool next) const
This function will get a usable seat for a passenger.
bool VehicleInfo::IsSeatAvailableFor (Unit *passenger, uint8 seat) const
Returns if a @passenger could board onto @seat - @passenger MUST be provided.
uint8 VehicleInfo::GetTakenSeatsMask () const
Wrapper to collect all taken seats.
bool VehicleInfo::IsUsableSeatForPlayer (uint32 seatFlags, uint32 seatFlagsB) const
void VehicleInfo::ApplySeatMods (Unit *passenger, uint32 seatFlags)
Add control and such modifiers to a passenger if required.
void VehicleInfo::RemoveSeatMods (Unit *passenger, uint32 seatFlags)
Remove control and such modifiers to a passenger if they were added.
TransportBase::TransportBase (WorldObject *owner)
virtual TransportBase::~TransportBase ()
void TransportBase::Update (uint32 diff)
void TransportBase::UpdateGlobalPositions ()
void TransportBase::UpdateGlobalPositionOf (WorldObject *passenger, float lx, float ly, float lz, float lo) const
void TransportBase::RotateLocalPosition (float lx, float ly, float &rx, float &ry) const
void TransportBase::NormalizeRotatedPosition (float rx, float ry, float &lx, float &ly) const
void TransportBase::CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const
void TransportBase::CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const
This method transforms supplied global coordinates into local offsets.
bool TransportBase::HasOnBoard (WorldObject const *passenger) const
void TransportBase::BoardPassenger (WorldObject *passenger, float lx, float ly, float lz, float lo, uint8 seat)
void TransportBase::UnBoardPassenger (WorldObject *passenger)
TransportInfo::TransportInfo (WorldObject *owner, TransportBase *transport, float lx, float ly, float lz, float lo, uint8 seat)
void TransportInfo::SetLocalPosition (float lx, float ly, float lz, float lo)
Detailed Description
The Transport System in MaNGOS consists of these files:
TransportSystem.h to provide the basic classes TransportBase and TransportInfo
TransportSystem.cpp which implements these classes
Vehicle.h as a vehicle is a transporter it will inherit itr transporter-information from TransportBase
Transports.h to implement the MOTransporter (subclas of gameobject) - Remains TODO as well of
impacts to various files
Typedef Documentation
PassengerMap
typedef std::unordered_map<WorldObject* , TransportInfo* > PassengerMap
Definition at line 44 of file TransportSystem.h.
VehicleSeatMap
typedef std::map<uint8 , VehicleSeatEntry const*> VehicleSeatMap
Definition at line 71 of file Vehicle.h.
Enumeration Type Documentation
ExitParamType
enum ExitParamType
Enumerator
SEAT_EXIT_PARAMS_OFFSET
SEAT_EXIT_PARAMS_ABSOLUTE_POS
Definition at line 54 of file Vehicle.h.
Function Documentation
ApplySeatMods()
void VehicleInfo::ApplySeatMods (Unit * passenger, uint32 seatFlags) private
Add control and such modifiers to a passenger if required.
Definition at line 648 of file Vehicle.cpp.
References Unit::addUnitState(), Unit::AI(), MotionMaster::Clear(), Player::GetCamera(), Unit::GetFaction(), Player::GetGroup(), Unit::GetMotionMaster(), UnitAI::GetReactState(), Object::GetTypeId(), GROUP_UPDATE_FLAG_VEHICLE_SEAT, Unit::InitCharmInfo(), CharmInfo::InitVehicleCreateSpells(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), Unit::IsWalking(), VehicleInfo::m_originalFaction, TransportBase::m_owner, MotionMaster::MoveIdle(), REACT_PASSIVE, SEAT_FLAG_CAN_CAST, SEAT_FLAG_CAN_CONTROL, SEAT_FLAG_NOT_SELECTABLE, Object::SendForcedObjectUpdate(), Unit::SetCharm(), Unit::SetCharmer(), Object::SetFlag(), Player::SetGroupUpdateFlag(), Player::SetMover(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), UnitAI::SetReactState(), Camera::SetView(), Unit::StopMoving(), TEMPFACTION_NONE, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_FLAG_POSSESSED, UNIT_FLAG_UNINTERACTIBLE, UNIT_STAT_POSSESSED, Player::UpdateClientControl(), and Player::VehicleSpellInitialize().
Referenced by VehicleInfo::Board(), and VehicleInfo::SwitchSeat().
Board()
void VehicleInfo::Board (Unit * passenger, uint8 seat)
This function will board a passenger onto a vehicle.
Parameters
passenger MUST be provided. This Unit will be boarded onto the vehicles (if it checks out)
seat Seat to which the passenger will be boarded (if can, elsewise an alternative will be selected if possible)
Definition at line 235 of file Vehicle.cpp.
References MovementInfo::AddMovementFlag(), VehicleInfo::ApplySeatMods(), TransportBase::BoardPassenger(), VehicleInfo::CalculateBoardingPositionOf(), VehicleInfo::CanBoard(), DEBUG_LOG, Object::GetGuidStr(), Object::GetObjectGuid(), WorldObject::GetOrientation(), Object::GetPackGUID(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), VehicleInfo::GetSeatEntry(), Player::GetSession(), WorldObject::GetTransport(), Object::GetTypeId(), VehicleInfo::GetUsableSeatFor(), WorldPacket::Initialize(), Unit::IsRooted(), VehicleInfo::IsSeatAvailableFor(), Movement::MoveSplineInit::Launch(), VehicleSeatEntry::m_flags, WorldObject::m_movementInfo, TransportBase::m_owner, MANGOS_ASSERT, MOVEFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), WorldSession::SendPacket(), Movement::MoveSplineInit::SetBoardVehicle(), Movement::MoveSplineInit::SetFacing(), Unit::SetImmobilizedState(), MovementInfo::SetTransportData(), PackedGuid::size(), SMSG_BREAK_TARGET, SMSG_ON_CANCEL_EXPECTED_RIDE_VEHICLE_AURA, TYPEID_PLAYER, TYPEID_UNIT, and Player::UnsummonPetTemporaryIfAny().
Referenced by Aura::HandleAuraControlVehicle().
BoardPassenger()
void TransportBase::BoardPassenger (WorldObject * passenger, float lx, float ly, float lz, float lo, uint8 seat) protected
Definition at line 157 of file TransportSystem.cpp.
References TransportBase::m_passengers, and WorldObject::SetTransportInfo().
Referenced by VehicleInfo::Board().
CalculateBoardingPositionOf()
void VehicleInfo::CalculateBoardingPositionOf (float gx, float gy, float gz, float go, float & lx, float & ly, float & lz, float & lo) const private
Definition at line 527 of file Vehicle.cpp.
References WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), TransportBase::m_owner, MapManager::NormalizeOrientation(), and TransportBase::NormalizeRotatedPosition().
Referenced by VehicleInfo::Board().
CalculatePassengerOffset()
void TransportBase::CalculatePassengerOffset (float & x, float & y, float & z, float * o = nullptr) const
This method transforms supplied global coordinates into local offsets.
Definition at line 134 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerOffset(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), and TransportBase::m_owner.
Referenced by TransportInfo::CalculatePassengerOffset().
CalculatePassengerPosition()
void TransportBase::CalculatePassengerPosition (float & x, float & y, float & z, float * o = nullptr) const
Definition at line 129 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerPosition(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), and TransportBase::m_owner.
Referenced by TransportInfo::CalculatePassengerPosition().
CanBoard()
bool VehicleInfo::CanBoard (Unit * passenger) const
This function will check if a passenger can be boarded.
Parameters
passenger Unit that attempts to board onto a vehicle
Definition at line 484 of file Vehicle.cpp.
References VehicleInfo::GetEmptySeats(), VehicleInfo::GetEmptySeatsMask(), TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), Object::GetTypeId(), Unit::GetVehicleInfo(), TransportBase::HasOnBoard(), WorldObject::IsBoarded(), Unit::IsVehicle(), VehicleInfo::m_creatureSeats, TransportBase::m_owner, TransportBase::m_passengers, VehicleInfo::m_playerSeats, and TYPEID_PLAYER.
Referenced by VehicleInfo::Board(), and Spell::CheckCast().
ChangeSeat()
void VehicleInfo::ChangeSeat (Unit * passenger, uint8 currentSeat, bool next)
Definition at line 309 of file Vehicle.cpp.
References VehicleInfo::GetUsableSeatFor(), VehicleEntry::m_flags, VehicleInfo::m_vehicleEntry, VehicleInfo::SwitchSeat(), and VEHICLE_FLAG_DISABLE_SWITCH.
Referenced by WorldSession::HandleRequestVehicleNextSeat().
GetPassenger()
Unit * VehicleInfo::GetPassenger (uint8 seat) const
Definition at line 517 of file Vehicle.cpp.
References TransportBase::m_passengers.
Referenced by CreatureAI::AttackPassengersIfCan(), spell_escape_from_silverbrook_credit_master::OnEffectExecute(), and Spell::SetTargetMap().
GetSeatEntry()
VehicleSeatEntry const * VehicleInfo::GetSeatEntry (uint8 seat) const
Get the Vehicle SeatEntry of a seat by position.
Definition at line 569 of file Vehicle.cpp.
References VehicleInfo::m_vehicleSeats.
Referenced by VehicleInfo::Board(), VehicleInfo::GetSeatForPassenger(), WorldSession::HandleEjectPassenger(), WorldSession::HandleRequestVehicleExit(), VehicleInfo::SwitchSeat(), and VehicleInfo::UnBoard().
GetSeatForPassenger()
VehicleSeatEntry const * VehicleInfo::GetSeatForPassenger (Unit const * passenger) const
Definition at line 575 of file Vehicle.cpp.
References VehicleInfo::GetSeatEntry(), and WorldObject::GetTransSeat().
Referenced by Spell::CheckVehicle().
GetTakenSeatsMask()
uint8 VehicleInfo::GetTakenSeatsMask () const private
Wrapper to collect all taken seats.
Definition at line 627 of file Vehicle.cpp.
References TransportBase::m_passengers.
Referenced by VehicleInfo::GetEmptySeatsMask().
GetUsableSeatFor()
bool VehicleInfo::GetUsableSeatFor (Unit * passenger, uint8 & seat, bool reset, bool next) const private
This function will get a usable seat for a passenger.
Parameters
passenger MUST be provided. Unit for which to try to get a free seat
seat will contain an available seat if returned true
Returns
return TRUE if and only if an available seat was found. In this case @seat will contain the id
Definition at line 587 of file Vehicle.cpp.
References VehicleInfo::GetEmptySeatsMask(), Object::GetTypeId(), VehicleInfo::m_creatureSeats, VehicleInfo::m_playerSeats, MANGOS_ASSERT, MAX_VEHICLE_SEAT, and TYPEID_PLAYER.
Referenced by VehicleInfo::Board(), and VehicleInfo::ChangeSeat().
HasOnBoard()
bool TransportBase::HasOnBoard (WorldObject const * passenger) const
Definition at line 140 of file TransportSystem.cpp.
References TransportInfo::GetTransport(), WorldObject::GetTransportInfo(), WorldObject::IsBoarded(), TransportBase::m_owner, and MANGOS_ASSERT.
Referenced by VehicleInfo::CanBoard(), Spell::CheckCast(), WorldSession::HandleEjectPassenger(), and TransportInfo::HasOnBoard().
Initialize()
void VehicleInfo::Initialize ()
Initializes the accessories.
Definition at line 171 of file Vehicle.cpp.
References MovementInfo::AddMovementFlags2(), Unit::AI(), DEBUG_LOG, SQLMultiStorage::SQLMSIteratorBounds< T >::first, SQLMultiStorage::getBounds(), Object::GetEntry(), Object::GetGuidStr(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Object::GetTypeId(), VehicleInfo::GetVehicleEntry(), VehicleInfo::m_accessoryGuids, VehicleInfo::m_disabledAccessoryInit, VehicleEntry::m_flags, VehicleInfo::m_isInitialized, WorldObject::m_movementInfo, VehicleInfo::m_overwriteNpcEntry, TransportBase::m_owner, MOVEFLAG2_ALLOW_PITCHING, MOVEFLAG2_FULLSPEEDPITCHING, MOVEFLAG2_FULLSPEEDTURNING, MOVEFLAG2_NO_JUMPING, MOVEFLAG2_NO_STRAFE, REACT_PASSIVE, SQLMultiStorage::SQLMSIteratorBounds< T >::second, Unit::SetCanEnterCombat(), Unit::SetImmobilizedState(), Unit::SetPowerType(), UnitAI::SetReactState(), SPELL_RIDE_VEHICLE_HARDCODED, sPowerDisplayStore, WorldObject::SummonCreature(), sVehicleAccessoryStorage, TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPEID_UNIT, VEHICLE_FLAG_ALLOW_PITCHING, VEHICLE_FLAG_FIXED_POSITION, VEHICLE_FLAG_FULLSPEEDPITCHING, VEHICLE_FLAG_FULLSPEEDTURNING, VEHICLE_FLAG_NO_JUMPING, VEHICLE_FLAG_NO_STRAFE, and VEHICLE_FLAG_PASSIVE.
Referenced by Unit::Update().
IsSeatAvailableFor()
bool VehicleInfo::IsSeatAvailableFor (Unit * passenger, uint8 seat) const private
Returns if a @passenger could board onto @seat - @passenger MUST be provided.
Definition at line 618 of file Vehicle.cpp.
References VehicleInfo::GetEmptySeatsMask(), Object::GetTypeId(), VehicleInfo::m_creatureSeats, VehicleInfo::m_playerSeats, MANGOS_ASSERT, MAX_VEHICLE_SEAT, and TYPEID_PLAYER.
Referenced by VehicleInfo::Board(), and VehicleInfo::SwitchSeat().
IsUsableSeatForPlayer()
bool VehicleInfo::IsUsableSeatForPlayer (uint32 seatFlags, uint32 seatFlagsB) const private
Definition at line 637 of file Vehicle.cpp.
References SEAT_FLAG_B_USABLE_FORCED, SEAT_FLAG_B_USABLE_FORCED_2, SEAT_FLAG_B_USABLE_FORCED_3, SEAT_FLAG_B_USABLE_FORCED_4, SEAT_FLAG_CAN_EXIT, SEAT_FLAG_HAS_ENTER_ANIM, SEAT_FLAG_HAS_RIDE_ANIM, and SEAT_FLAG_UNCONTROLLED.
Referenced by VehicleInfo::VehicleInfo().
LoadVehicleAccessory()
void ObjectMgr::LoadVehicleAccessory ()
Definition at line 48 of file Vehicle.cpp.
References SQLMultiStorage::EraseEntry(), SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), SQLStorageBase::GetRecordCount(), SQLMultiStorage::Load(), SQLStorage::LookupEntry(), MAX_VEHICLE_SEAT, sCreatureStorage, sLog, and sVehicleAccessoryStorage.
LoadVehicleSeatParameters()
void ObjectMgr::LoadVehicleSeatParameters ()
Definition at line 78 of file Vehicle.cpp.
References VehicleSeatParameters::exitParamO, VehicleSeatParameters::exitParamValue, VehicleSeatParameters::exitParamX, VehicleSeatParameters::exitParamY, VehicleSeatParameters::exitParamZ, Field::GetFloat(), Field::GetUInt32(), Field::GetUInt8(), ObjectMgr::m_seatParameters, Database::Query(), VehicleSeatParameters::seatEntry, VehicleSeatParameters::seatOrientation, sLog, BarGoLink::step(), sVehicleSeatStore, and WorldDatabase.
NormalizeRotatedPosition()
void TransportBase::NormalizeRotatedPosition (float rx, float ry, float & lx, float & ly) const
Definition at line 123 of file TransportSystem.cpp.
References TransportBase::m_cosO, and TransportBase::m_sinO.
Referenced by VehicleInfo::CalculateBoardingPositionOf().
RemoveAccessoriesFromMap()
void VehicleInfo::RemoveAccessoriesFromMap ()
Unsummones accessory in case of far-teleport or death.
Definition at line 535 of file Vehicle.cpp.
References VehicleInfo::m_accessoryGuids, and VehicleInfo::m_isInitialized.
Referenced by Unit::SetDeathState(), Player::TeleportTo(), and VehicleInfo::~VehicleInfo().
RemoveSeatMods()
void VehicleInfo::RemoveSeatMods (Unit * passenger, uint32 seatFlags) private
Remove control and such modifiers to a passenger if they were added.
Definition at line 743 of file Vehicle.cpp.
References Unit::AI(), MotionMaster::Clear(), Unit::clearUnitState(), Player::GetCamera(), Player::GetGroup(), Unit::GetMotionMaster(), Object::GetTypeId(), VehicleInfo::GetVehicleEntry(), Unit::GetVictim(), GROUP_UPDATE_FLAG_VEHICLE_SEAT, MotionMaster::Initialize(), Unit::IsPvP(), Unit::IsPvPFreeForAll(), VehicleEntry::m_flags, VehicleInfo::m_originalFaction, TransportBase::m_owner, REACT_AGGRESSIVE, Object::RemoveFlag(), Player::RemovePetActionBar(), Camera::ResetView(), SEAT_FLAG_CAN_CAST, SEAT_FLAG_CAN_CONTROL, SEAT_FLAG_NOT_SELECTABLE, Unit::SetCharm(), Unit::SetCharmer(), Player::SetGroupUpdateFlag(), Player::SetMover(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), UnitAI::SetReactState(), Unit::StopMoving(), TEMPFACTION_NONE, TYPEID_PLAYER, TYPEID_UNIT, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, UNIT_FLAG_POSSESSED, UNIT_FLAG_UNINTERACTIBLE, UNIT_STAT_POSSESSED, Player::UpdateClientControl(), and VEHICLE_FLAG_PASSIVE.
Referenced by VehicleInfo::SwitchSeat(), and VehicleInfo::UnBoard().
RotateLocalPosition()
void TransportBase::RotateLocalPosition (float lx, float ly, float & rx, float & ry) const
Definition at line 116 of file TransportSystem.cpp.
References TransportBase::m_cosO, and TransportBase::m_sinO.
SetLocalPosition()
void TransportInfo::SetLocalPosition (float lx, float ly, float lz, float lo)
Definition at line 196 of file TransportSystem.cpp.
References TransportInfo::m_localPosition, TransportInfo::m_owner, TransportInfo::m_transport, Position::o, TransportBase::UpdateGlobalPositionOf(), Position::x, Position::y, and Position::z.
SwitchSeat()
void VehicleInfo::SwitchSeat (Unit * passenger, uint8 seat)
This function will switch the seat of a passenger on the same vehicle.
Parameters
passenger MUST be provided. This Unit will change its seat on the vehicle
seat Seat to which the passenger will be switched
Definition at line 327 of file Vehicle.cpp.
References VehicleInfo::ApplySeatMods(), VehicleSeatEntry::CanSwitchFromSeat(), DEBUG_LOG, Object::GetGuidStr(), VehicleInfo::GetSeatEntry(), VehicleInfo::IsSeatAvailableFor(), Movement::MoveSplineInit::Launch(), VehicleEntry::m_flags, VehicleSeatEntry::m_flags, TransportBase::m_passengers, VehicleInfo::m_vehicleEntry, MANGOS_ASSERT, Movement::MoveSplineInit::MoveTo(), VehicleInfo::RemoveSeatMods(), and VEHICLE_FLAG_DISABLE_SWITCH.
Referenced by VehicleInfo::ChangeSeat(), WorldSession::HandleChangeSeatsOnControlledVehicle(), and WorldSession::HandleRequestVehicleSwitchSeat().
TeleportPassengers()
void VehicleInfo::TeleportPassengers (uint32 mapId)
Definition at line 543 of file Vehicle.cpp.
References TransportBase::GetOwner(), WorldObject::GetPosition(), WorldObject::GetTransport(), TransportBase::m_passengers, Position::o, PLAYER_FLAGS, PLAYER_FLAGS_GHOST, TELE_TO_NOT_LEAVE_TRANSPORT, VehicleInfo::UnBoard(), Position::x, Position::y, and Position::z.
Referenced by Transport::TeleportTransport().
TransportBase()
TransportBase::TransportBase (WorldObject * owner) explicit
Definition at line 38 of file TransportSystem.cpp.
References TransportBase::m_owner, and MANGOS_ASSERT.
TransportInfo()
TransportInfo::TransportInfo (WorldObject * owner, TransportBase * transport, float lx, float ly, float lz, float lo, uint8 seat) explicit
Definition at line 187 of file TransportSystem.cpp.
References TransportInfo::m_transport, and MANGOS_ASSERT.
UnBoard()
void VehicleInfo::UnBoard (Unit * passenger, bool changeVehicle)
This function will Unboard a passenger.
Parameters
passenger MUST be provided. This Unit will be unboarded from the vehicle
changeVehicle If set, the passenger is expected to be directly boarded to another vehicle, and hence he will not be unboarded but only removed from this vehicle.
Definition at line 383 of file Vehicle.cpp.
References Unit::CastSpell(), MovementInfo::ClearTransportData(), DEBUG_LOG, Object::GetGuidStr(), Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPosition(), WorldObject::GetPositionZ(), VehicleInfo::GetSeatEntry(), WorldObject::GetTransport(), Object::GetTypeId(), Unit::HasAuraType(), Unit::hasUnitState(), Unit::IsFlying(), Object::IsPlayer(), Object::IsUnit(), Movement::MoveSplineInit::Launch(), VehicleInfo::m_accessoryGuids, VehicleEntry::m_flags, VehicleSeatEntry::m_flags, VehicleSeatEntry::m_ID, WorldObject::m_movementInfo, TransportBase::m_owner, TransportBase::m_passengers, VehicleInfo::m_vehicleEntry, MANGOS_ASSERT, MOVEFLAG_ONTRANSPORT, Movement::MoveSplineInit::MoveTo(), Position::o, Position::RelocateOffset(), MovementInfo::RemoveMovementFlag(), VehicleInfo::RemoveSeatMods(), Player::ResummonPetTemporaryUnSummonedIfAny(), SEAT_EXIT_PARAMS_ABSOLUTE_POS, SEAT_EXIT_PARAMS_OFFSET, SEAT_FLAG_CAN_CONTROL, Movement::MoveSplineInit::SetExitVehicle(), Movement::MoveSplineInit::SetFacing(), Player::SetFallInformation(), Unit::SetImmobilizedState(), sObjectMgr, SPELL_AURA_MOD_ROOT, SPELL_VEHICLE_PARACHUTE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, TYPEID_UNIT, TransportBase::UnBoardPassenger(), UNIT_STAT_ROOT, WorldObject::UpdateAllowedPositionZ(), VEHICLE_FLAG_NOT_DISMISSED, VEHICLE_FLAG_UNK4, Position::x, Position::y, and Position::z.
Referenced by Aura::HandleAuraControlVehicle(), Aura::HandleAuraDummy(), and VehicleInfo::TeleportPassengers().
UnBoardPassenger()
void TransportBase::UnBoardPassenger (WorldObject * passenger) protected
Definition at line 168 of file TransportSystem.cpp.
References TransportBase::m_passengers, and WorldObject::SetTransportInfo().
Referenced by VehicleInfo::UnBoard().
Update()
void TransportBase::Update (uint32 diff)
Definition at line 55 of file TransportSystem.cpp.
References WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), TransportBase::m_lastPosition, TransportBase::m_owner, TransportBase::m_updatePositionsTimer, MapManager::NormalizeOrientation(), Position::o, TransportBase::UpdateGlobalPositions(), Position::x, Position::y, and Position::z.
Referenced by Unit::Update().
UpdateGlobalPositionOf()
void TransportBase::UpdateGlobalPositionOf (WorldObject * passenger, float lx, float ly, float lz, float lo) const
Definition at line 93 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerPosition(), Map::CreatureRelocation(), WorldObject::GetMap(), WorldObject::GetPosition(), Object::GetTypeId(), TransportBase::m_owner, Position::o, Map::PlayerRelocation(), TYPEID_PLAYER, TYPEID_UNIT, Position::x, Position::y, and Position::z.
Referenced by TransportInfo::SetLocalPosition(), and TransportBase::UpdateGlobalPositions().
UpdateGlobalPositions()
void TransportBase::UpdateGlobalPositions ()
Definition at line 72 of file TransportSystem.cpp.
References WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), TransportBase::m_cosO, TransportBase::m_lastPosition, TransportBase::m_owner, TransportBase::m_passengers, TransportBase::m_sinO, MapManager::NormalizeOrientation(), Position::o, and TransportBase::UpdateGlobalPositionOf().
Referenced by Unit::OnRelocated(), and TransportBase::Update().
VehicleInfo()
VehicleInfo::VehicleInfo (Unit * owner, VehicleEntry const * vehicleEntry, uint32 overwriteNpcEntry) explicit
Constructor of VehicleInfo.
Parameters
owner MUST be provided owner of the vehicle (type Unit)
vehicleEntry MUST be provided dbc-entry of the vehicle
overwriteNpcEntry Use to overwrite the GetEntry() result for selecting associated passengers
This function will initialise the VehicleInfo of the vehicle owner Also the seat-map is created here
Definition at line 134 of file Vehicle.cpp.
References VehicleInfo::IsUsableSeatForCreature(), VehicleInfo::IsUsableSeatForPlayer(), VehicleInfo::m_creatureSeats, VehicleInfo::m_playerSeats, VehicleEntry::m_seatID, VehicleInfo::m_vehicleSeats, MANGOS_ASSERT, MAX_VEHICLE_SEAT, and sVehicleSeatStore.
~TransportBase()
TransportBase::~TransportBase () virtual
Definition at line 48 of file TransportSystem.cpp.
References TransportBase::m_passengers, and MANGOS_ASSERT.
~VehicleInfo()
VehicleInfo::~VehicleInfo ()
Definition at line 164 of file Vehicle.cpp.
References TransportBase::m_owner, VehicleInfo::RemoveAccessoriesFromMap(), and SPELL_AURA_CONTROL_VEHICLE.