CMaNGOS_WoTLK: Game
Game
Files
file Unit.h
Data Structures
struct SpellImmune
struct DiminishingReturn
Structure to keep track of diminishing returns, for more information about the idea behind diminishing returns, see: http://www.wowwiki.com/Diminishing_returns.
struct CleanDamage
struct SubDamageInfo
struct CalcDamageInfo
struct SpellNonMeleeDamage
struct SpellPeriodicAuraLogInfo
struct CombatData
struct ProcSystemArguments
struct ProcExecutionData
struct UnitActionBarEntry
struct CharmInfo
struct SelectAttackingTargetParams
class Unit
struct TargetDistanceOrderNear
struct TargetDistanceOrderFarAway
struct LowestHPNearestOrder
class UnitLambdaEvent
Macros
#define NUM_SPELL_PARTIAL_RESISTS 11
#define BASE_MELEERANGE_OFFSET 1.33f
#define BASE_MINDAMAGE 1.0f
#define BASE_MAXDAMAGE 2.0f
#define BASE_ATTACK_TIME 2000
#define SCALE_SPELLPOWER_HEALING 1.88f
#define MAX_UNIT_STAND_STATE 10
#define MAX_SHEATH_STATE 3
#define CREATURE_MAX_SPELLS 10
#define BASE_CHARGE_SPEED 27.0f
#define MAX_COMBAT_RATING 25
#define NUM_UNIT_COMBAT_DIE_SIDES (UNIT_COMBAT_DIE_HIT + 1)
#define CURRENT_FIRST_NON_MELEE_SPELL 1
#define UNIT_ACTION_BUTTON_ACTION(X) (uint32(X) & 0x00FFFFFF)
#define UNIT_ACTION_BUTTON_TYPE(X) ((uint32(X) & 0xFF000000) >> 24)
#define MAX_UNIT_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
#define MAKE_UNIT_ACTION_BUTTON(A, T) (uint32(A) | (uint32(T) << 24))
#define MAX_UNIT_ACTION_BAR_INDEX (ACTION_BAR_INDEX_END-ACTION_BAR_INDEX_START)
#define REACTIVE_TIMER_START 4000
#define MAX_REACTIVE 3
#define ATTACK_DISPLAY_DELAY 200
#define MAX_PLAYER_STEALTH_DETECT_RANGE 45.0f
#define MAX_CREATURE_ATTACK_RADIUS 45.0f
#define REGEN_TIME_FULL 2000
#define REGEN_TIME_FULL_UNIT 5000
#define REGEN_TIME_PRECISE 500
Typedefs
typedef std::list< SpellImmune > SpellImmuneList
typedef const Opcodes SpeedOpcodePair[3]
typedef SpellAuraProcResult(Unit::* pAuraProcHandler) (ProcExecutionData &data)
typedef UnitActionBarEntry CharmSpellEntry
Enumerations
enum SpellPartialResist {
SPELL_PARTIAL_RESIST_NONE = 0 , SPELL_PARTIAL_RESIST_PCT_10 , SPELL_PARTIAL_RESIST_PCT_20 , SPELL_PARTIAL_RESIST_PCT_30 ,
SPELL_PARTIAL_RESIST_PCT_40 , SPELL_PARTIAL_RESIST_PCT_50 , SPELL_PARTIAL_RESIST_PCT_60 , SPELL_PARTIAL_RESIST_PCT_70 ,
SPELL_PARTIAL_RESIST_PCT_80 , SPELL_PARTIAL_RESIST_PCT_90 , SPELL_PARTIAL_RESIST_PCT_100
}
enum UnitBytes0Offsets : uint8 { UNIT_BYTES_0_OFFSET_RACE = 0 , UNIT_BYTES_0_OFFSET_CLASS = 1 , UNIT_BYTES_0_OFFSET_GENDER = 2 , UNIT_BYTES_0_OFFSET_POWER_TYPE = 3 }
enum UnitBytes1Offsets : uint8 { UNIT_BYTES_1_OFFSET_STAND_STATE = 0 , UNIT_BYTES_1_OFFSET_PET_LOYALTY = 1 , UNIT_BYTES_1_OFFSET_VIS_FLAGS = 2 , UNIT_BYTES_1_OFFSET_MISC_FLAGS = 3 }
enum UnitBytes2Offsets : uint8 { UNIT_BYTES_2_OFFSET_SHEATH_STATE = 0 , UNIT_BYTES_2_OFFSET_PVP_FLAG = 1 , UNIT_BYTES_2_OFFSET_PET_FLAGS = 2 , UNIT_BYTES_2_OFFSET_SHAPESHIFT = 3 }
enum UnitStandStateType {
UNIT_STAND_STATE_STAND = 0 , UNIT_STAND_STATE_SIT = 1 , UNIT_STAND_STATE_SIT_CHAIR = 2 , UNIT_STAND_STATE_SLEEP = 3 ,
UNIT_STAND_STATE_SIT_LOW_CHAIR = 4 , UNIT_STAND_STATE_SIT_MEDIUM_CHAIR = 5 , UNIT_STAND_STATE_SIT_HIGH_CHAIR = 6 , UNIT_STAND_STATE_DEAD = 7 ,
UNIT_STAND_STATE_KNEEL = 8 , UNIT_STAND_STATE_CUSTOM = 9
}
enum UnitVisFlags {
UNIT_VIS_FLAG_GHOST = 0x01 , UNIT_VIS_FLAG_CREEP = 0x02 , UNIT_VIS_FLAG_UNTRACKABLE = 0x04 , UNIT_VIS_FLAG_UNK4 = 0x08 ,
UNIT_VIS_FLAG_UNK5 = 0x10 , UNIT_VIS_FLAGS_ALL = 0xFF
}
enum UnitMiscFlags { UNIT_BYTE1_FLAG_ALWAYS_STAND = 0x01 , UNIT_BYTE1_FLAG_FLY_ANIM = 0x02 , UNIT_BYTE1_FLAG_ALL = 0xFF }
enum SheathState { SHEATH_STATE_UNARMED = 0 , SHEATH_STATE_MELEE = 1 , SHEATH_STATE_RANGED = 2 }
enum UnitPVPStateFlags {
UNIT_BYTE2_FLAG_PVP = 0x01 , UNIT_BYTE2_FLAG_UNK1 = 0x02 , UNIT_BYTE2_FLAG_FFA_PVP = 0x04 , UNIT_BYTE2_FLAG_SANCTUARY = 0x08 ,
UNIT_BYTE2_FLAG_AURAS = 0x10 , UNIT_BYTE2_FLAG_UNK5 = 0x20 , UNIT_BYTE2_FLAG_UNK6 = 0x40 , UNIT_BYTE2_FLAG_UNK7 = 0x80
}
enum UnitRename { UNIT_CAN_BE_RENAMED = 0x01 , UNIT_CAN_BE_ABANDONED = 0x02 }
enum Swing { NOSWING = 0 , SINGLEHANDEDSWING = 1 , TWOHANDEDSWING = 2 }
enum VictimState {
VICTIMSTATE_UNAFFECTED = 0 , VICTIMSTATE_NORMAL = 1 , VICTIMSTATE_DODGE = 2 , VICTIMSTATE_PARRY = 3 ,
VICTIMSTATE_INTERRUPT = 4 , VICTIMSTATE_BLOCKS = 5 , VICTIMSTATE_EVADES = 6 , VICTIMSTATE_IS_IMMUNE = 7 ,
VICTIMSTATE_DEFLECTS = 8
}
enum HitInfo {
HITINFO_NORMALSWING = 0x00000000 , HITINFO_UNK0 = 0x00000001 , HITINFO_NORMALSWING2 = 0x00000002 , HITINFO_LEFTSWING = 0x00000004 ,
HITINFO_UNK3 = 0x00000008 , HITINFO_MISS = 0x00000010 , HITINFO_ABSORB = 0x00000020 , HITINFO_ABSORB2 = 0x00000040 ,
HITINFO_RESIST = 0x00000080 , HITINFO_RESIST2 = 0x00000100 , HITINFO_CRITICALHIT = 0x00000200 , HITINFO_BLOCK = 0x00002000 ,
HITINFO_GLANCING = 0x00010000 , HITINFO_CRUSHING = 0x00020000 , HITINFO_NOACTION = 0x00040000 , HITINFO_SWINGNOHITSOUND = 0x00200000 ,
HITINFO_UNK22 = 0x00800000
}
enum UnitModifierType {
BASE_VALUE = 0 , BASE_PCT = 1 , TOTAL_VALUE = 2 , TOTAL_PCT = 3 ,
MODIFIER_TYPE_END = 4
}
enum WeaponDamageRange { MINDAMAGE , MAXDAMAGE }
enum DamageTypeToSchool { RESISTANCE , DAMAGE_DEALT , DAMAGE_TAKEN }
enum AuraRemoveMode {
AURA_REMOVE_BY_DEFAULT , AURA_REMOVE_BY_STACK , AURA_REMOVE_BY_CANCEL , AURA_REMOVE_BY_DISPEL ,
AURA_REMOVE_BY_DEATH , AURA_REMOVE_BY_DELETE , AURA_REMOVE_BY_SHIELD_BREAK , AURA_REMOVE_BY_EXPIRE ,
AURA_REMOVE_BY_TRACKING , AURA_REMOVE_BY_GAINED_STACK
}
enum AuraScriptLocation : uint32 {
SCRIPT_LOCATION_MELEE_DAMAGE_DONE , SCRIPT_LOCATION_MELEE_DAMAGE_TAKEN , SCRIPT_LOCATION_SPELL_DAMAGE_DONE , SCRIPT_LOCATION_SPELL_DAMAGE_TAKEN ,
SCRIPT_LOCATION_SPELL_HEALING_DONE , SCRIPT_LOCATION_SPELL_HEALING_TAKEN , SCRIPT_LOCATION_MAX
}
enum UnitMods {
UNIT_MOD_STAT_STRENGTH , UNIT_MOD_STAT_AGILITY , UNIT_MOD_STAT_STAMINA , UNIT_MOD_STAT_INTELLECT ,
UNIT_MOD_STAT_SPIRIT , UNIT_MOD_HEALTH , UNIT_MOD_MANA , UNIT_MOD_RAGE ,
UNIT_MOD_FOCUS , UNIT_MOD_ENERGY , UNIT_MOD_HAPPINESS , UNIT_MOD_RUNE ,
UNIT_MOD_RUNIC_POWER , UNIT_MOD_ARMOR , UNIT_MOD_RESISTANCE_HOLY , UNIT_MOD_RESISTANCE_FIRE ,
UNIT_MOD_RESISTANCE_NATURE , UNIT_MOD_RESISTANCE_FROST , UNIT_MOD_RESISTANCE_SHADOW , UNIT_MOD_RESISTANCE_ARCANE ,
UNIT_MOD_ATTACK_POWER , UNIT_MOD_ATTACK_POWER_RANGED , UNIT_MOD_DAMAGE_MAINHAND , UNIT_MOD_DAMAGE_OFFHAND ,
UNIT_MOD_DAMAGE_RANGED , UNIT_MOD_END , UNIT_MOD_STAT_START = UNIT_MOD_STAT_STRENGTH , UNIT_MOD_STAT_END = UNIT_MOD_STAT_SPIRIT + 1 ,
UNIT_MOD_RESISTANCE_START = UNIT_MOD_ARMOR , UNIT_MOD_RESISTANCE_END = UNIT_MOD_RESISTANCE_ARCANE + 1 , UNIT_MOD_POWER_START = UNIT_MOD_MANA , UNIT_MOD_POWER_END = UNIT_MOD_RUNIC_POWER + 1
}
enum BaseModGroup {
CRIT_PERCENTAGE , RANGED_CRIT_PERCENTAGE , OFFHAND_CRIT_PERCENTAGE , SHIELD_BLOCK_VALUE ,
BASEMOD_END
}
enum BaseModType { FLAT_MOD , PCT_MOD , MOD_END }
enum DeathState {
ALIVE = 0 , JUST_DIED = 1 , CORPSE = 2 , DEAD = 3 ,
JUST_ALIVED = 4
}
enum UnitState {
UNIT_STAT_MELEE_ATTACKING = 0x00000001 , UNIT_STAT_LOGOUT_TIMER = 0x00000002 , UNIT_STAT_FEIGN_DEATH = 0x00000004 , UNIT_STAT_STUNNED = 0x00000008 ,
UNIT_STAT_ROOT = 0x00000010 , UNIT_STAT_ISOLATED = 0x00000020 , UNIT_STAT_POSSESSED = 0x00000040 , UNIT_STAT_TAXI_FLIGHT = 0x00000080 ,
UNIT_STAT_PROPELLED = 0x00000100 , UNIT_STAT_PANIC = 0x00000200 , UNIT_STAT_RETREATING = 0x00000400 , UNIT_STAT_DISTRACTED = 0x00000800 ,
UNIT_STAT_STAY = 0x00001000 , UNIT_STAT_CONFUSED = 0x00002000 , UNIT_STAT_CONFUSED_MOVE = 0x00004000 , UNIT_STAT_ROAMING = 0x00008000 ,
UNIT_STAT_ROAMING_MOVE = 0x00010000 , UNIT_STAT_CHASE = 0x00020000 , UNIT_STAT_CHASE_MOVE = 0x00040000 , UNIT_STAT_FOLLOW = 0x00080000 ,
UNIT_STAT_FOLLOW_MOVE = 0x00100000 , UNIT_STAT_FLEEING = 0x00200000 , UNIT_STAT_FLEEING_MOVE = 0x00400000 , UNIT_STAT_CHANNELING = 0x00800000 ,
UNIT_STAT_NO_COMBAT_MOVEMENT = 0x01000000 , UNIT_STAT_NO_FOLLOW_MOVEMENT = 0x02000000 , UNIT_STAT_RUNNING = 0x04000000 , UNIT_STAT_WAYPOINT_PAUSED = 0x08000000 ,
UNIT_STAT_IGNORE_PATHFINDING = 0x10000000 , UNIT_STAT_AI_ROOT = 0x20000000 , UNIT_STAT_CAN_NOT_MOVE = UNIT_STAT_ROOT | UNIT_STAT_STUNNED | UNIT_STAT_LOGOUT_TIMER | UNIT_STAT_FEIGN_DEATH | UNIT_STAT_AI_ROOT , UNIT_STAT_NOT_MOVE ,
UNIT_STAT_NO_FREE_MOVE , UNIT_STAT_CAN_NOT_REACT , UNIT_STAT_LOST_CONTROL = UNIT_STAT_CONFUSED | UNIT_STAT_FLEEING | UNIT_STAT_POSSESSED , UNIT_STAT_CAN_NOT_REACT_OR_LOST_CONTROL = UNIT_STAT_CAN_NOT_REACT | UNIT_STAT_LOST_CONTROL ,
UNIT_STAT_MOVING = UNIT_STAT_ROAMING_MOVE | UNIT_STAT_CHASE_MOVE | UNIT_STAT_FOLLOW_MOVE | UNIT_STAT_FLEEING_MOVE , UNIT_STAT_RUNNING_STATE = UNIT_STAT_CHASE_MOVE | UNIT_STAT_FLEEING_MOVE | UNIT_STAT_RUNNING , UNIT_STAT_ALL_STATE = 0xFFFFFFFF , UNIT_STAT_ALL_DYN_STATES = UNIT_STAT_ALL_STATE & ~(UNIT_STAT_NO_COMBAT_MOVEMENT | UNIT_STAT_RUNNING | UNIT_STAT_WAYPOINT_PAUSED | UNIT_STAT_IGNORE_PATHFINDING)
}
enum CombatRating {
CR_WEAPON_SKILL = 0 , CR_DEFENSE_SKILL = 1 , CR_DODGE = 2 , CR_PARRY = 3 ,
CR_BLOCK = 4 , CR_HIT_MELEE = 5 , CR_HIT_RANGED = 6 , CR_HIT_SPELL = 7 ,
CR_CRIT_MELEE = 8 , CR_CRIT_RANGED = 9 , CR_CRIT_SPELL = 10 , CR_HIT_TAKEN_MELEE = 11 ,
CR_HIT_TAKEN_RANGED = 12 , CR_HIT_TAKEN_SPELL = 13 , CR_CRIT_TAKEN_MELEE = 14 , CR_CRIT_TAKEN_RANGED = 15 ,
CR_CRIT_TAKEN_SPELL = 16 , CR_HASTE_MELEE = 17 , CR_HASTE_RANGED = 18 , CR_HASTE_SPELL = 19 ,
CR_WEAPON_SKILL_MAINHAND = 20 , CR_WEAPON_SKILL_OFFHAND = 21 , CR_WEAPON_SKILL_RANGED = 22 , CR_EXPERTISE = 23 ,
CR_ARMOR_PENETRATION = 24
}
enum UnitAuraFlags { UNIT_AURAFLAG_ALIVE_INVISIBLE = 0x1 }
internal used flags for marking special auras - for example some dummy-auras
enum UnitVisibility {
VISIBILITY_OFF = 0 , VISIBILITY_ON = 1 , VISIBILITY_GROUP_STEALTH = 2 , VISIBILITY_GROUP_INVISIBILITY = 3 ,
VISIBILITY_GROUP_NO_DETECT = 4 , VISIBILITY_REMOVE_CORPSE = 5
}
enum UnitFlags {
UNIT_FLAG_UNK_0 = 0x00000001 , UNIT_FLAG_SPAWNING = 0x00000002 , UNIT_FLAG_CLIENT_CONTROL_LOST = 0x00000004 , UNIT_FLAG_PLAYER_CONTROLLED = 0x00000008 ,
UNIT_FLAG_RENAME = 0x00000010 , UNIT_FLAG_PREPARATION = 0x00000020 , UNIT_FLAG_UNK_6 = 0x00000040 , UNIT_FLAG_NOT_ATTACKABLE_1 = 0x00000080 ,
UNIT_FLAG_IMMUNE_TO_PLAYER = 0x00000100 , UNIT_FLAG_IMMUNE_TO_NPC = 0x00000200 , UNIT_FLAG_LOOTING = 0x00000400 , UNIT_FLAG_PET_IN_COMBAT = 0x00000800 ,
UNIT_FLAG_PVP_DEPRECATED = 0x00001000 , UNIT_FLAG_SILENCED = 0x00002000 , UNIT_FLAG_UNK_14 = 0x00004000 , UNIT_FLAG_SWIMMING = 0x00008000 ,
UNIT_FLAG_UNTARGETABLE = 0x00010000 , UNIT_FLAG_PACIFIED = 0x00020000 , UNIT_FLAG_STUNNED = 0x00040000 , UNIT_FLAG_IN_COMBAT = 0x00080000 ,
UNIT_FLAG_TAXI_FLIGHT = 0x00100000 , UNIT_FLAG_DISARMED = 0x00200000 , UNIT_FLAG_CONFUSED = 0x00400000 , UNIT_FLAG_FLEEING = 0x00800000 ,
UNIT_FLAG_POSSESSED = 0x01000000 , UNIT_FLAG_UNINTERACTIBLE = 0x02000000 , UNIT_FLAG_SKINNABLE = 0x04000000 , UNIT_FLAG_MOUNT = 0x08000000 ,
UNIT_FLAG_UNK_28 = 0x10000000 , UNIT_FLAG_PREVENT_ANIM = 0x20000000 , UNIT_FLAG_SHEATHE = 0x40000000 , UNIT_FLAG_IMMUNE = 0x80000000
}
enum UnitFlags2 {
UNIT_FLAG2_FEIGN_DEATH = 0x00000001 , UNIT_FLAG2_HIDE_BODY = 0x00000002 , UNIT_FLAG2_IGNORE_REPUTATION = 0x00000004 , UNIT_FLAG2_COMPREHEND_LANG = 0x00000008 ,
UNIT_FLAG2_CLONED = 0x00000010 , UNIT_FLAG2_DO_NOT_FADE_IN = 0x00000020 , UNIT_FLAG2_FORCE_MOVE = 0x00000040 , UNIT_FLAG2_DISARM_OFFHAND = 0x00000080 ,
UNIT_FLAG2_UNK8 = 0x00000100 , UNIT_FLAG2_UNK9 = 0x00000200 , UNIT_FLAG2_DISARM_RANGED = 0x00000400 , UNIT_FLAG2_REGENERATE_POWER = 0x00000800 ,
UNIT_FLAG2_SPELL_CLICK_IN_GROUP = 0x00001000 , UNIT_FLAG2_SPELL_CLICK_DISABLED = 0x00002000 , UNIT_FLAG2_INTERACT_ANY_REACTION = 0x00004000 , UNIT_FLAG2_UNK15 = 0x00008000 ,
UNIT_FLAG2_UNK16 = 0x00010000 , UNIT_FLAG2_ALLOW_CHEAT_SPELLS = 0x00040000
}
enum NPCFlags {
UNIT_NPC_FLAG_NONE = 0x00000000 , UNIT_NPC_FLAG_GOSSIP = 0x00000001 , UNIT_NPC_FLAG_QUESTGIVER = 0x00000002 , UNIT_NPC_FLAG_UNK1 = 0x00000004 ,
UNIT_NPC_FLAG_UNK2 = 0x00000008 , UNIT_NPC_FLAG_TRAINER = 0x00000010 , UNIT_NPC_FLAG_TRAINER_CLASS = 0x00000020 , UNIT_NPC_FLAG_TRAINER_PROFESSION = 0x00000040 ,
UNIT_NPC_FLAG_VENDOR = 0x00000080 , UNIT_NPC_FLAG_VENDOR_AMMO = 0x00000100 , UNIT_NPC_FLAG_VENDOR_FOOD = 0x00000200 , UNIT_NPC_FLAG_VENDOR_POISON = 0x00000400 ,
UNIT_NPC_FLAG_VENDOR_REAGENT = 0x00000800 , UNIT_NPC_FLAG_REPAIR = 0x00001000 , UNIT_NPC_FLAG_FLIGHTMASTER = 0x00002000 , UNIT_NPC_FLAG_SPIRITHEALER = 0x00004000 ,
UNIT_NPC_FLAG_SPIRITGUIDE = 0x00008000 , UNIT_NPC_FLAG_INNKEEPER = 0x00010000 , UNIT_NPC_FLAG_BANKER = 0x00020000 , UNIT_NPC_FLAG_PETITIONER = 0x00040000 ,
UNIT_NPC_FLAG_TABARDDESIGNER = 0x00080000 , UNIT_NPC_FLAG_BATTLEMASTER = 0x00100000 , UNIT_NPC_FLAG_AUCTIONEER = 0x00200000 , UNIT_NPC_FLAG_STABLEMASTER = 0x00400000 ,
UNIT_NPC_FLAG_GUILD_BANKER = 0x00800000 , UNIT_NPC_FLAG_SPELLCLICK = 0x01000000 , UNIT_NPC_FLAG_PLAYER_VEHICLE = 0x02000000
}
Non Player Character flags.
enum DiminishingLevels { DIMINISHING_LEVEL_1 = 0 , DIMINISHING_LEVEL_2 = 1 , DIMINISHING_LEVEL_3 = 2 , DIMINISHING_LEVEL_IMMUNE = 3 }
The different available diminishing return levels.
enum MeleeHitOutcome {
MELEE_HIT_EVADE = 0 , MELEE_HIT_MISS = 1 , MELEE_HIT_DODGE = 2 , MELEE_HIT_BLOCK = 3 ,
MELEE_HIT_PARRY = 4 , MELEE_HIT_GLANCING = 5 , MELEE_HIT_CRIT = 6 , MELEE_HIT_CRUSHING = 7 ,
MELEE_HIT_NORMAL = 8
}
enum UnitCombatDieSide {
UNIT_COMBAT_DIE_MISS , UNIT_COMBAT_DIE_RESIST , UNIT_COMBAT_DIE_DODGE , UNIT_COMBAT_DIE_PARRY ,
UNIT_COMBAT_DIE_DEFLECT , UNIT_COMBAT_DIE_BLOCK , UNIT_COMBAT_DIE_GLANCE , UNIT_COMBAT_DIE_CRIT ,
UNIT_COMBAT_DIE_CRUSH , UNIT_COMBAT_DIE_HIT
}
enum SpellAuraProcResult { SPELL_AURA_PROC_OK = 0 , SPELL_AURA_PROC_FAILED = 1 , SPELL_AURA_PROC_CANT_TRIGGER = 2 }
enum CurrentSpellTypes {
CURRENT_MELEE_SPELL = 0 , CURRENT_GENERIC_SPELL = 1 , CURRENT_AUTOREPEAT_SPELL = 2 , CURRENT_CHANNELED_SPELL = 3 ,
CURRENT_MAX_SPELL
}
enum ActiveStates {
ACT_PASSIVE = 0x01 , ACT_DISABLED = 0x81 , ACT_ENABLED = 0xC1 , ACT_COMMAND = 0x07 ,
ACT_REACTION = 0x06 , ACT_DECIDE = 0x00
}
enum CommandStates { COMMAND_STAY = 0 , COMMAND_FOLLOW = 1 , COMMAND_ATTACK = 2 , COMMAND_DISMISS = 3 }
enum ActionBarIndex { ACTION_BAR_INDEX_START = 0 , ACTION_BAR_INDEX_PET_SPELL_START = 3 , ACTION_BAR_INDEX_PET_SPELL_END = 7 , ACTION_BAR_INDEX_END = 10 }
enum ControlledUnitMask {
CONTROLLED_PET = 0x01 , CONTROLLED_MINIPET = 0x02 , CONTROLLED_GUARDIANS = 0x04 , CONTROLLED_CHARM = 0x08 ,
CONTROLLED_TOTEMS = 0x10
}
enum ReactiveType { REACTIVE_DEFENSE = 0 , REACTIVE_HUNTER_PARRY = 1 , REACTIVE_OVERPOWER = 2 }
enum IgnoreUnitState { IGNORE_UNIT_TARGET_STATE = 0 , IGNORE_UNIT_COMBAT_STATE = 1 , IGNORE_UNIT_TARGET_NON_FROZEN = 126 }
enum PowerDefaults {
POWER_RAGE_DEFAULT = 1000 , POWER_FOCUS_DEFAULT = 100 , POWER_ENERGY_DEFAULT = 100 , POWER_HAPPINESS_DEFAULT = 1000000 ,
POWER_RUNE_DEFAULT = 8 , POWER_RUNIC_POWER_DEFAULT = 1000
}
enum AttackingTarget {
ATTACKING_TARGET_RANDOM = 0 , ATTACKING_TARGET_TOPAGGRO , ATTACKING_TARGET_BOTTOMAGGRO , ATTACKING_TARGET_NEAREST_BY ,
ATTACKING_TARGET_FARTHEST_AWAY , ATTACKING_TARGET_ALL_SUITABLE
}
enum SelectFlags {
SELECT_FLAG_IN_LOS = 0x0001 , SELECT_FLAG_PLAYER = 0x0002 , SELECT_FLAG_POWER_MANA = 0x0004 , SELECT_FLAG_POWER_RAGE = 0x0008 ,
SELECT_FLAG_POWER_ENERGY = 0x0010 , SELECT_FLAG_IN_MELEE_RANGE = 0x0040 , SELECT_FLAG_NOT_IN_MELEE_RANGE = 0x0080 , SELECT_FLAG_HAS_AURA = 0x0100 ,
SELECT_FLAG_NOT_AURA = 0x0200 , SELECT_FLAG_RANGE_RANGE = 0x0400 , SELECT_FLAG_RANGE_AOE_RANGE = 0x0800 , SELECT_FLAG_POWER_NOT_MANA = 0x1000 ,
SELECT_FLAG_USE_EFFECT_RADIUS = 0x2000 , SELECT_FLAG_SKIP_TANK = 0x4000 , SELECT_FLAG_CASTING = 0x8000 , SELECT_FLAG_SKIP_CUSTOM =0x10000 ,
SELECT_FLAG_NOT_IMMUNE =0x20000 , SELECT_FLAG_USE_EFFECT_RADIUS_OF_TRIGGERED_SPELL = 0x40000
}
Functions
const char * UnitCombatDieSideText (UnitCombatDieSide side)
uint32 createProcExtendMask (SpellNonMeleeDamage *damageInfo, SpellMissInfo missCondition)
template<typename Func >
void Unit::CallForAllControlledUnits (Func const &func, uint32 controlledMask)
template<typename Func >
bool Unit::CheckAllControlledUnits (Func const &func, uint32 controlledMask) const
Variables
SpeedOpcodePair SetSpeed2Opc_table [MAX_MOVE_TYPE]
pAuraProcHandler AuraProcHandler [TOTAL_AURAS]
float baseMoveSpeed [MAX_MOVE_TYPE]
Detailed Description
Macro Definition Documentation
ATTACK_DISPLAY_DELAY
#define ATTACK_DISPLAY_DELAY 200
Definition at line 1070 of file Unit.h.
BASE_ATTACK_TIME
#define BASE_ATTACK_TIME 2000
Definition at line 73 of file Unit.h.
BASE_CHARGE_SPEED
#define BASE_CHARGE_SPEED 27.0f
Definition at line 437 of file Unit.h.
BASE_MAXDAMAGE
#define BASE_MAXDAMAGE 2.0f
Definition at line 72 of file Unit.h.
BASE_MELEERANGE_OFFSET
#define BASE_MELEERANGE_OFFSET 1.33f
Definition at line 70 of file Unit.h.
BASE_MINDAMAGE
#define BASE_MINDAMAGE 1.0f
Definition at line 71 of file Unit.h.
CREATURE_MAX_SPELLS
#define CREATURE_MAX_SPELLS 10
Definition at line 173 of file Unit.h.
CURRENT_FIRST_NON_MELEE_SPELL
#define CURRENT_FIRST_NON_MELEE_SPELL 1
Definition at line 869 of file Unit.h.
MAKE_UNIT_ACTION_BUTTON
#define MAKE_UNIT_ACTION_BUTTON (A, T) (uint32(A) | (uint32(T) << 24))
Definition at line 892 of file Unit.h.
MAX_COMBAT_RATING
#define MAX_COMBAT_RATING 25
Definition at line 482 of file Unit.h.
MAX_CREATURE_ATTACK_RADIUS
#define MAX_CREATURE_ATTACK_RADIUS 45.0f
Definition at line 1072 of file Unit.h.
MAX_PLAYER_STEALTH_DETECT_RANGE
#define MAX_PLAYER_STEALTH_DETECT_RANGE 45.0f
Definition at line 1071 of file Unit.h.
MAX_REACTIVE
#define MAX_REACTIVE 3
Definition at line 1059 of file Unit.h.
MAX_SHEATH_STATE
#define MAX_SHEATH_STATE 3
Definition at line 149 of file Unit.h.
MAX_UNIT_ACTION_BAR_INDEX
#define MAX_UNIT_ACTION_BAR_INDEX (ACTION_BAR_INDEX_END-ACTION_BAR_INDEX_START)
Definition at line 935 of file Unit.h.
MAX_UNIT_ACTION_BUTTON_ACTION_VALUE
#define MAX_UNIT_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
Definition at line 891 of file Unit.h.
MAX_UNIT_STAND_STATE
#define MAX_UNIT_STAND_STATE 10
Definition at line 116 of file Unit.h.
NUM_SPELL_PARTIAL_RESISTS
#define NUM_SPELL_PARTIAL_RESISTS 11
Definition at line 68 of file Unit.h.
NUM_UNIT_COMBAT_DIE_SIDES
#define NUM_UNIT_COMBAT_DIE_SIDES (UNIT_COMBAT_DIE_HIT + 1)
Definition at line 674 of file Unit.h.
REACTIVE_TIMER_START
#define REACTIVE_TIMER_START 4000
Definition at line 1050 of file Unit.h.
REGEN_TIME_FULL
#define REGEN_TIME_FULL 2000
Definition at line 1075 of file Unit.h.
REGEN_TIME_FULL_UNIT
#define REGEN_TIME_FULL_UNIT 5000
Definition at line 1076 of file Unit.h.
REGEN_TIME_PRECISE
#define REGEN_TIME_PRECISE 500
Definition at line 1077 of file Unit.h.
SCALE_SPELLPOWER_HEALING
#define SCALE_SPELLPOWER_HEALING 1.88f
Definition at line 75 of file Unit.h.
UNIT_ACTION_BUTTON_ACTION
#define UNIT_ACTION_BUTTON_ACTION (X) (uint32(X) & 0x00FFFFFF)
Definition at line 889 of file Unit.h.
UNIT_ACTION_BUTTON_TYPE
#define UNIT_ACTION_BUTTON_TYPE (X) ((uint32(X) & 0xFF000000) >> 24)
Definition at line 890 of file Unit.h.
Typedef Documentation
CharmSpellEntry
typedef UnitActionBarEntry CharmSpellEntry
Definition at line 925 of file Unit.h.
pAuraProcHandler
typedef SpellAuraProcResult(Unit::* pAuraProcHandler) (ProcExecutionData &data)
Definition at line 857 of file Unit.h.
SpeedOpcodePair
typedef const Opcodes SpeedOpcodePair[3]
Definition at line 439 of file Unit.h.
SpellImmuneList
typedef std::list<SpellImmune> SpellImmuneList
Definition at line 249 of file Unit.h.
Enumeration Type Documentation
ActionBarIndex
enum ActionBarIndex
Enumerator
ACTION_BAR_INDEX_START
ACTION_BAR_INDEX_PET_SPELL_START
ACTION_BAR_INDEX_PET_SPELL_END
ACTION_BAR_INDEX_END
Definition at line 927 of file Unit.h.
ActiveStates
enum ActiveStates
Enumerator
ACT_PASSIVE
ACT_DISABLED
ACT_ENABLED
ACT_COMMAND
ACT_REACTION
ACT_DECIDE
Definition at line 871 of file Unit.h.
AttackingTarget
enum AttackingTarget
Enumerator
ATTACKING_TARGET_RANDOM
ATTACKING_TARGET_TOPAGGRO
ATTACKING_TARGET_BOTTOMAGGRO
ATTACKING_TARGET_NEAREST_BY
ATTACKING_TARGET_FARTHEST_AWAY
ATTACKING_TARGET_ALL_SUITABLE
Definition at line 1091 of file Unit.h.
AuraRemoveMode
enum AuraRemoveMode
Enumerator
AURA_REMOVE_BY_DEFAULT
AURA_REMOVE_BY_STACK
AURA_REMOVE_BY_CANCEL
AURA_REMOVE_BY_DISPEL
AURA_REMOVE_BY_DEATH
AURA_REMOVE_BY_DELETE
AURA_REMOVE_BY_SHIELD_BREAK
AURA_REMOVE_BY_EXPIRE
AURA_REMOVE_BY_TRACKING
AURA_REMOVE_BY_GAINED_STACK
Definition at line 273 of file Unit.h.
AuraScriptLocation
enum AuraScriptLocation : uint32
Enumerator
SCRIPT_LOCATION_MELEE_DAMAGE_DONE
SCRIPT_LOCATION_MELEE_DAMAGE_TAKEN
SCRIPT_LOCATION_SPELL_DAMAGE_DONE
SCRIPT_LOCATION_SPELL_DAMAGE_TAKEN
SCRIPT_LOCATION_SPELL_HEALING_DONE
SCRIPT_LOCATION_SPELL_HEALING_TAKEN
SCRIPT_LOCATION_MAX
Definition at line 287 of file Unit.h.
BaseModGroup
enum BaseModGroup
Enumerator
CRIT_PERCENTAGE
RANGED_CRIT_PERCENTAGE
OFFHAND_CRIT_PERCENTAGE
SHIELD_BLOCK_VALUE
BASEMOD_END
Definition at line 335 of file Unit.h.
BaseModType
enum BaseModType
Enumerator
FLAT_MOD
PCT_MOD
MOD_END
Definition at line 344 of file Unit.h.
CombatRating
enum CombatRating
Enumerator
CR_WEAPON_SKILL
CR_DEFENSE_SKILL
CR_DODGE
CR_PARRY
CR_BLOCK
CR_HIT_MELEE
CR_HIT_RANGED
CR_HIT_SPELL
CR_CRIT_MELEE
CR_CRIT_RANGED
CR_CRIT_SPELL
CR_HIT_TAKEN_MELEE
CR_HIT_TAKEN_RANGED
CR_HIT_TAKEN_SPELL
CR_CRIT_TAKEN_MELEE
CR_CRIT_TAKEN_RANGED
CR_CRIT_TAKEN_SPELL
CR_HASTE_MELEE
CR_HASTE_RANGED
CR_HASTE_SPELL
CR_WEAPON_SKILL_MAINHAND
CR_WEAPON_SKILL_OFFHAND
CR_WEAPON_SKILL_RANGED
CR_EXPERTISE
CR_ARMOR_PENETRATION
Definition at line 453 of file Unit.h.
CommandStates
enum CommandStates
Enumerator
COMMAND_STAY
COMMAND_FOLLOW
COMMAND_ATTACK
COMMAND_DISMISS
Definition at line 881 of file Unit.h.
ControlledUnitMask
enum ControlledUnitMask
Enumerator
CONTROLLED_PET
CONTROLLED_MINIPET
CONTROLLED_GUARDIANS
CONTROLLED_CHARM
CONTROLLED_TOTEMS
Definition at line 1040 of file Unit.h.
CurrentSpellTypes
enum CurrentSpellTypes
Enumerator
CURRENT_MELEE_SPELL
CURRENT_GENERIC_SPELL
CURRENT_AUTOREPEAT_SPELL
CURRENT_CHANNELED_SPELL
CURRENT_MAX_SPELL
Definition at line 860 of file Unit.h.
DamageTypeToSchool
enum DamageTypeToSchool
Enumerator
RESISTANCE
DAMAGE_DEALT
DAMAGE_TAKEN
Definition at line 266 of file Unit.h.
DeathState
enum DeathState
Enumerator
ALIVE
JUST_DIED
CORPSE
DEAD
JUST_ALIVED
Definition at line 351 of file Unit.h.
DiminishingLevels
enum DiminishingLevels
The different available diminishing return levels.
See also
DiminishingReturn
Enumerator
DIMINISHING_LEVEL_1
DIMINISHING_LEVEL_2
DIMINISHING_LEVEL_3
DIMINISHING_LEVEL_IMMUNE
Definition at line 601 of file Unit.h.
HitInfo
enum HitInfo
Enumerator
HITINFO_NORMALSWING
HITINFO_UNK0
HITINFO_NORMALSWING2
HITINFO_LEFTSWING
HITINFO_UNK3
HITINFO_MISS
HITINFO_ABSORB
HITINFO_ABSORB2
HITINFO_RESIST
HITINFO_RESIST2
HITINFO_CRITICALHIT
HITINFO_BLOCK
HITINFO_GLANCING
HITINFO_CRUSHING
HITINFO_NOACTION
HITINFO_SWINGNOHITSOUND
HITINFO_UNK22
Definition at line 195 of file Unit.h.
IgnoreUnitState
enum IgnoreUnitState
Enumerator
IGNORE_UNIT_TARGET_STATE
IGNORE_UNIT_COMBAT_STATE
IGNORE_UNIT_TARGET_NON_FROZEN
Definition at line 1062 of file Unit.h.
MeleeHitOutcome
enum MeleeHitOutcome
Enumerator
MELEE_HIT_EVADE
MELEE_HIT_MISS
MELEE_HIT_DODGE
MELEE_HIT_BLOCK
MELEE_HIT_PARRY
MELEE_HIT_GLANCING
MELEE_HIT_CRIT
MELEE_HIT_CRUSHING
MELEE_HIT_NORMAL
Definition at line 647 of file Unit.h.
NPCFlags
enum NPCFlags
Non Player Character flags.
Enumerator
UNIT_NPC_FLAG_NONE
UNIT_NPC_FLAG_GOSSIP
UNIT_NPC_FLAG_QUESTGIVER
UNIT_NPC_FLAG_UNK1
UNIT_NPC_FLAG_UNK2
UNIT_NPC_FLAG_TRAINER
UNIT_NPC_FLAG_TRAINER_CLASS
UNIT_NPC_FLAG_TRAINER_PROFESSION
UNIT_NPC_FLAG_VENDOR
UNIT_NPC_FLAG_VENDOR_AMMO
UNIT_NPC_FLAG_VENDOR_FOOD
UNIT_NPC_FLAG_VENDOR_POISON
UNIT_NPC_FLAG_VENDOR_REAGENT
UNIT_NPC_FLAG_REPAIR
UNIT_NPC_FLAG_FLIGHTMASTER
UNIT_NPC_FLAG_SPIRITHEALER
UNIT_NPC_FLAG_SPIRITGUIDE
UNIT_NPC_FLAG_INNKEEPER
UNIT_NPC_FLAG_BANKER
UNIT_NPC_FLAG_PETITIONER
UNIT_NPC_FLAG_TABARDDESIGNER
UNIT_NPC_FLAG_BATTLEMASTER
UNIT_NPC_FLAG_AUCTIONEER
UNIT_NPC_FLAG_STABLEMASTER
UNIT_NPC_FLAG_GUILD_BANKER
UNIT_NPC_FLAG_SPELLCLICK
UNIT_NPC_FLAG_PLAYER_VEHICLE
Definition at line 561 of file Unit.h.
PowerDefaults
enum PowerDefaults
Enumerator
POWER_RAGE_DEFAULT
POWER_FOCUS_DEFAULT
POWER_ENERGY_DEFAULT
POWER_HAPPINESS_DEFAULT
POWER_RUNE_DEFAULT
POWER_RUNIC_POWER_DEFAULT
Definition at line 1080 of file Unit.h.
ReactiveType
enum ReactiveType
Enumerator
REACTIVE_DEFENSE
REACTIVE_HUNTER_PARRY
REACTIVE_OVERPOWER
Definition at line 1052 of file Unit.h.
SelectFlags
enum SelectFlags
Enumerator
SELECT_FLAG_IN_LOS
SELECT_FLAG_PLAYER
SELECT_FLAG_POWER_MANA
SELECT_FLAG_POWER_RAGE
SELECT_FLAG_POWER_ENERGY
SELECT_FLAG_IN_MELEE_RANGE
SELECT_FLAG_NOT_IN_MELEE_RANGE
SELECT_FLAG_HAS_AURA
SELECT_FLAG_NOT_AURA
SELECT_FLAG_RANGE_RANGE
SELECT_FLAG_RANGE_AOE_RANGE
SELECT_FLAG_POWER_NOT_MANA
SELECT_FLAG_USE_EFFECT_RADIUS
SELECT_FLAG_SKIP_TANK
SELECT_FLAG_CASTING
SELECT_FLAG_SKIP_CUSTOM
SELECT_FLAG_NOT_IMMUNE
SELECT_FLAG_USE_EFFECT_RADIUS_OF_TRIGGERED_SPELL
Definition at line 1101 of file Unit.h.
SheathState
enum SheathState
Enumerator
SHEATH_STATE_UNARMED
SHEATH_STATE_MELEE
SHEATH_STATE_RANGED
Definition at line 142 of file Unit.h.
SpellAuraProcResult
enum SpellAuraProcResult
Enumerator
SPELL_AURA_PROC_OK
SPELL_AURA_PROC_FAILED
SPELL_AURA_PROC_CANT_TRIGGER
Definition at line 784 of file Unit.h.
SpellPartialResist
enum SpellPartialResist
Enumerator
SPELL_PARTIAL_RESIST_NONE
SPELL_PARTIAL_RESIST_PCT_10
SPELL_PARTIAL_RESIST_PCT_20
SPELL_PARTIAL_RESIST_PCT_30
SPELL_PARTIAL_RESIST_PCT_40
SPELL_PARTIAL_RESIST_PCT_50
SPELL_PARTIAL_RESIST_PCT_60
SPELL_PARTIAL_RESIST_PCT_70
SPELL_PARTIAL_RESIST_PCT_80
SPELL_PARTIAL_RESIST_PCT_90
SPELL_PARTIAL_RESIST_PCT_100
Definition at line 53 of file Unit.h.
Swing
enum Swing
Enumerator
NOSWING
SINGLEHANDEDSWING
TWOHANDEDSWING
Definition at line 175 of file Unit.h.
UnitAuraFlags
enum UnitAuraFlags
internal used flags for marking special auras - for example some dummy-auras
Enumerator
UNIT_AURAFLAG_ALIVE_INVISIBLE
Definition at line 485 of file Unit.h.
UnitBytes0Offsets
enum UnitBytes0Offsets : uint8
Enumerator
UNIT_BYTES_0_OFFSET_RACE
UNIT_BYTES_0_OFFSET_CLASS
UNIT_BYTES_0_OFFSET_GENDER
UNIT_BYTES_0_OFFSET_POWER_TYPE
Definition at line 77 of file Unit.h.
UnitBytes1Offsets
enum UnitBytes1Offsets : uint8
Enumerator
UNIT_BYTES_1_OFFSET_STAND_STATE
UNIT_BYTES_1_OFFSET_PET_LOYALTY
UNIT_BYTES_1_OFFSET_VIS_FLAGS
UNIT_BYTES_1_OFFSET_MISC_FLAGS
Definition at line 85 of file Unit.h.
UnitBytes2Offsets
enum UnitBytes2Offsets : uint8
Enumerator
UNIT_BYTES_2_OFFSET_SHEATH_STATE
UNIT_BYTES_2_OFFSET_PVP_FLAG
UNIT_BYTES_2_OFFSET_PET_FLAGS
UNIT_BYTES_2_OFFSET_SHAPESHIFT
Definition at line 93 of file Unit.h.
UnitCombatDieSide
enum UnitCombatDieSide
Enumerator
UNIT_COMBAT_DIE_MISS
UNIT_COMBAT_DIE_RESIST
UNIT_COMBAT_DIE_DODGE
UNIT_COMBAT_DIE_PARRY
UNIT_COMBAT_DIE_DEFLECT
UNIT_COMBAT_DIE_BLOCK
UNIT_COMBAT_DIE_GLANCE
UNIT_COMBAT_DIE_CRIT
UNIT_COMBAT_DIE_CRUSH
UNIT_COMBAT_DIE_HIT
Definition at line 660 of file Unit.h.
UnitFlags
enum UnitFlags
Enumerator
UNIT_FLAG_UNK_0
UNIT_FLAG_SPAWNING
UNIT_FLAG_CLIENT_CONTROL_LOST
UNIT_FLAG_PLAYER_CONTROLLED
UNIT_FLAG_RENAME
UNIT_FLAG_PREPARATION
UNIT_FLAG_UNK_6
UNIT_FLAG_NOT_ATTACKABLE_1
UNIT_FLAG_IMMUNE_TO_PLAYER
UNIT_FLAG_IMMUNE_TO_NPC
UNIT_FLAG_LOOTING
UNIT_FLAG_PET_IN_COMBAT
UNIT_FLAG_PVP_DEPRECATED
UNIT_FLAG_SILENCED
UNIT_FLAG_UNK_14
UNIT_FLAG_SWIMMING
UNIT_FLAG_UNTARGETABLE
UNIT_FLAG_PACIFIED
UNIT_FLAG_STUNNED
UNIT_FLAG_IN_COMBAT
UNIT_FLAG_TAXI_FLIGHT
UNIT_FLAG_DISARMED
UNIT_FLAG_CONFUSED
UNIT_FLAG_FLEEING
UNIT_FLAG_POSSESSED
UNIT_FLAG_UNINTERACTIBLE
UNIT_FLAG_SKINNABLE
UNIT_FLAG_MOUNT
UNIT_FLAG_UNK_28
UNIT_FLAG_PREVENT_ANIM
UNIT_FLAG_SHEATHE
UNIT_FLAG_IMMUNE
Definition at line 501 of file Unit.h.
UnitFlags2
enum UnitFlags2
Enumerator
UNIT_FLAG2_FEIGN_DEATH
UNIT_FLAG2_HIDE_BODY
UNIT_FLAG2_IGNORE_REPUTATION
UNIT_FLAG2_COMPREHEND_LANG
UNIT_FLAG2_CLONED
UNIT_FLAG2_DO_NOT_FADE_IN
UNIT_FLAG2_FORCE_MOVE
UNIT_FLAG2_DISARM_OFFHAND
UNIT_FLAG2_UNK8
UNIT_FLAG2_UNK9
UNIT_FLAG2_DISARM_RANGED
UNIT_FLAG2_REGENERATE_POWER
UNIT_FLAG2_SPELL_CLICK_IN_GROUP
UNIT_FLAG2_SPELL_CLICK_DISABLED
UNIT_FLAG2_INTERACT_ANY_REACTION
UNIT_FLAG2_UNK15
UNIT_FLAG2_UNK16
UNIT_FLAG2_ALLOW_CHEAT_SPELLS
Definition at line 538 of file Unit.h.
UnitMiscFlags
enum UnitMiscFlags
Enumerator
UNIT_BYTE1_FLAG_ALWAYS_STAND
UNIT_BYTE1_FLAG_FLY_ANIM
UNIT_BYTE1_FLAG_ALL
Definition at line 134 of file Unit.h.
UnitModifierType
enum UnitModifierType
Enumerator
BASE_VALUE
BASE_PCT
TOTAL_VALUE
TOTAL_PCT
MODIFIER_TYPE_END
Definition at line 251 of file Unit.h.
UnitMods
enum UnitMods
Enumerator
UNIT_MOD_STAT_STRENGTH
UNIT_MOD_STAT_AGILITY
UNIT_MOD_STAT_STAMINA
UNIT_MOD_STAT_INTELLECT
UNIT_MOD_STAT_SPIRIT
UNIT_MOD_HEALTH
UNIT_MOD_MANA
UNIT_MOD_RAGE
UNIT_MOD_FOCUS
UNIT_MOD_ENERGY
UNIT_MOD_HAPPINESS
UNIT_MOD_RUNE
UNIT_MOD_RUNIC_POWER
UNIT_MOD_ARMOR
UNIT_MOD_RESISTANCE_HOLY
UNIT_MOD_RESISTANCE_FIRE
UNIT_MOD_RESISTANCE_NATURE
UNIT_MOD_RESISTANCE_FROST
UNIT_MOD_RESISTANCE_SHADOW
UNIT_MOD_RESISTANCE_ARCANE
UNIT_MOD_ATTACK_POWER
UNIT_MOD_ATTACK_POWER_RANGED
UNIT_MOD_DAMAGE_MAINHAND
UNIT_MOD_DAMAGE_OFFHAND
UNIT_MOD_DAMAGE_RANGED
UNIT_MOD_END
UNIT_MOD_STAT_START
UNIT_MOD_STAT_END
UNIT_MOD_RESISTANCE_START
UNIT_MOD_RESISTANCE_END
UNIT_MOD_POWER_START
UNIT_MOD_POWER_END
Definition at line 298 of file Unit.h.
UnitPVPStateFlags
enum UnitPVPStateFlags
Enumerator
UNIT_BYTE2_FLAG_PVP
UNIT_BYTE2_FLAG_UNK1
UNIT_BYTE2_FLAG_FFA_PVP
UNIT_BYTE2_FLAG_SANCTUARY
UNIT_BYTE2_FLAG_AURAS
UNIT_BYTE2_FLAG_UNK5
UNIT_BYTE2_FLAG_UNK6
UNIT_BYTE2_FLAG_UNK7
Definition at line 152 of file Unit.h.
UnitRename
enum UnitRename
Enumerator
UNIT_CAN_BE_RENAMED
UNIT_CAN_BE_ABANDONED
Definition at line 165 of file Unit.h.
UnitStandStateType
enum UnitStandStateType
Enumerator
UNIT_STAND_STATE_STAND
UNIT_STAND_STATE_SIT
UNIT_STAND_STATE_SIT_CHAIR
UNIT_STAND_STATE_SLEEP
UNIT_STAND_STATE_SIT_LOW_CHAIR
UNIT_STAND_STATE_SIT_MEDIUM_CHAIR
UNIT_STAND_STATE_SIT_HIGH_CHAIR
UNIT_STAND_STATE_DEAD
UNIT_STAND_STATE_KNEEL
UNIT_STAND_STATE_CUSTOM
Definition at line 102 of file Unit.h.
UnitState
enum UnitState
Enumerator
UNIT_STAT_MELEE_ATTACKING
UNIT_STAT_LOGOUT_TIMER
UNIT_STAT_FEIGN_DEATH
UNIT_STAT_STUNNED
UNIT_STAT_ROOT
UNIT_STAT_ISOLATED
UNIT_STAT_POSSESSED
UNIT_STAT_TAXI_FLIGHT
UNIT_STAT_PROPELLED
UNIT_STAT_PANIC
UNIT_STAT_RETREATING
UNIT_STAT_DISTRACTED
UNIT_STAT_STAY
UNIT_STAT_CONFUSED
UNIT_STAT_CONFUSED_MOVE
UNIT_STAT_ROAMING
UNIT_STAT_ROAMING_MOVE
UNIT_STAT_CHASE
UNIT_STAT_CHASE_MOVE
UNIT_STAT_FOLLOW
UNIT_STAT_FOLLOW_MOVE
UNIT_STAT_FLEEING
UNIT_STAT_FLEEING_MOVE
UNIT_STAT_CHANNELING
UNIT_STAT_NO_COMBAT_MOVEMENT
UNIT_STAT_NO_FOLLOW_MOVEMENT
UNIT_STAT_RUNNING
UNIT_STAT_WAYPOINT_PAUSED
UNIT_STAT_IGNORE_PATHFINDING
UNIT_STAT_AI_ROOT
UNIT_STAT_CAN_NOT_MOVE
UNIT_STAT_NOT_MOVE
UNIT_STAT_NO_FREE_MOVE
UNIT_STAT_CAN_NOT_REACT
UNIT_STAT_LOST_CONTROL
UNIT_STAT_CAN_NOT_REACT_OR_LOST_CONTROL
UNIT_STAT_MOVING
UNIT_STAT_RUNNING_STATE
UNIT_STAT_ALL_STATE
UNIT_STAT_ALL_DYN_STATES
Definition at line 361 of file Unit.h.
UnitVisFlags
enum UnitVisFlags
Enumerator
UNIT_VIS_FLAG_GHOST
UNIT_VIS_FLAG_CREEP
UNIT_VIS_FLAG_UNTRACKABLE
UNIT_VIS_FLAG_UNK4
UNIT_VIS_FLAG_UNK5
UNIT_VIS_FLAGS_ALL
Definition at line 122 of file Unit.h.
UnitVisibility
enum UnitVisibility
Enumerator
VISIBILITY_OFF
VISIBILITY_ON
VISIBILITY_GROUP_STEALTH
VISIBILITY_GROUP_INVISIBILITY
VISIBILITY_GROUP_NO_DETECT
VISIBILITY_REMOVE_CORPSE
Definition at line 490 of file Unit.h.
VictimState
enum VictimState
Enumerator
VICTIMSTATE_UNAFFECTED
VICTIMSTATE_NORMAL
VICTIMSTATE_DODGE
VICTIMSTATE_PARRY
VICTIMSTATE_INTERRUPT
VICTIMSTATE_BLOCKS
VICTIMSTATE_EVADES
VICTIMSTATE_IS_IMMUNE
VICTIMSTATE_DEFLECTS
Definition at line 182 of file Unit.h.
WeaponDamageRange
enum WeaponDamageRange
Enumerator
MINDAMAGE
MAXDAMAGE
Definition at line 260 of file Unit.h.
Function Documentation
CallForAllControlledUnits()
template<typename Func > void Unit::CallForAllControlledUnits (Func const & func, uint32 controlledMask)
Definition at line 2810 of file Unit.h.
References Unit::_GetTotem(), Unit::_GetUnit(), CONTROLLED_CHARM, CONTROLLED_GUARDIANS, CONTROLLED_MINIPET, CONTROLLED_PET, CONTROLLED_TOTEMS, Unit::GetCharm(), WorldObject::GetMap(), Unit::GetMiniPet(), Unit::GetPet(), Unit::m_charmedUnitsPrivate, Unit::m_guardianPets, Unit::m_guardianPetsIterator, and MAX_TOTEM_SLOT.
Referenced by Unit::CombatStopWithPets(), Unit::HandleExitCombat(), Unit::PetOwnerKilledUnit(), Aura::ReapplyAffectedPassiveAuras(), CombatManager::SetEvadeState(), Player::SetGameMaster(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), Unit::SetPhaseMask(), Unit::SetPvP(), Unit::SetPvPFreeForAll(), Unit::SetPvPSanctuary(), Unit::SetSpeedRate(), Unit::StopAttackFaction(), Unit::TriggerEvadeEvents(), and Player::UpdateZoneDependentPets().
CheckAllControlledUnits()
template<typename Func > bool Unit::CheckAllControlledUnits (Func const & func, uint32 controlledMask) const
Definition at line 2846 of file Unit.h.
References Unit::_GetTotem(), Unit::_GetUnit(), CONTROLLED_CHARM, CONTROLLED_GUARDIANS, CONTROLLED_MINIPET, CONTROLLED_PET, CONTROLLED_TOTEMS, Unit::GetCharm(), WorldObject::GetMap(), Unit::GetMiniPet(), Unit::GetPet(), Unit::m_charmedUnitsPrivate, Unit::m_guardianPets, and MAX_TOTEM_SLOT.
createProcExtendMask()
uint32 createProcExtendMask (SpellNonMeleeDamage * damageInfo, SpellMissInfo missCondition)
Definition at line 363 of file UnitAuraProcHandler.cpp.
References SpellNonMeleeDamage::absorb, SpellNonMeleeDamage::blocked, SpellNonMeleeDamage::HitInfo, PROC_EX_ABSORB, PROC_EX_BLOCK, PROC_EX_CRITICAL_HIT, PROC_EX_DEFLECT, PROC_EX_DODGE, PROC_EX_EVADE, PROC_EX_IMMUNE, PROC_EX_MISS, PROC_EX_NONE, PROC_EX_NORMAL_HIT, PROC_EX_PARRY, PROC_EX_REFLECT, PROC_EX_RESIST, SPELL_HIT_TYPE_CRIT, SPELL_MISS_ABSORB, SPELL_MISS_BLOCK, SPELL_MISS_DEFLECT, SPELL_MISS_DODGE, SPELL_MISS_EVADE, SPELL_MISS_IMMUNE, SPELL_MISS_IMMUNE2, SPELL_MISS_MISS, SPELL_MISS_NONE, SPELL_MISS_PARRY, SPELL_MISS_REFLECT, and SPELL_MISS_RESIST.
Referenced by Spell::DoAllEffectOnTarget(), and Aura::PeriodicTick().
UnitCombatDieSideText()
const char* UnitCombatDieSideText (UnitCombatDieSide side) inline
Definition at line 677 of file Unit.h.
References UNIT_COMBAT_DIE_BLOCK, UNIT_COMBAT_DIE_CRIT, UNIT_COMBAT_DIE_CRUSH, UNIT_COMBAT_DIE_DEFLECT, UNIT_COMBAT_DIE_DODGE, UNIT_COMBAT_DIE_GLANCE, UNIT_COMBAT_DIE_HIT, UNIT_COMBAT_DIE_MISS, UNIT_COMBAT_DIE_PARRY, and UNIT_COMBAT_DIE_RESIST.
Referenced by Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), and Unit::RollMeleeOutcomeAgainst().
Variable Documentation
AuraProcHandler
pAuraProcHandler AuraProcHandler[TOTAL_AURAS] extern
Definition at line 31 of file UnitAuraProcHandler.cpp.
Referenced by Unit::ProcDamageAndSpellFor().
baseMoveSpeed
float baseMoveSpeed[MAX_MOVE_TYPE] extern
Definition at line 63 of file Unit.cpp.
Referenced by Spell::EffectJump(), Unit::GetSpeed(), and Unit::UpdateSpeed().
SetSpeed2Opc_table
SpeedOpcodePair SetSpeed2Opc_table[MAX_MOVE_TYPE]
Initial value:
=
{
    {SMSG_FORCE_WALK_SPEED_CHANGE,        SMSG_SPLINE_SET_WALK_SPEED,           MSG_MOVE_SET_WALK_SPEED},
    {SMSG_FORCE_RUN_SPEED_CHANGE,         SMSG_SPLINE_SET_RUN_SPEED,            MSG_MOVE_SET_RUN_SPEED},
    {SMSG_FORCE_RUN_BACK_SPEED_CHANGE,    SMSG_SPLINE_SET_RUN_BACK_SPEED,       MSG_MOVE_SET_RUN_BACK_SPEED},
    {SMSG_FORCE_SWIM_SPEED_CHANGE,        SMSG_SPLINE_SET_SWIM_SPEED,           MSG_MOVE_SET_SWIM_SPEED},
    {SMSG_FORCE_SWIM_BACK_SPEED_CHANGE,   SMSG_SPLINE_SET_SWIM_BACK_SPEED,      MSG_MOVE_SET_SWIM_BACK_SPEED},
    {SMSG_FORCE_TURN_RATE_CHANGE,         SMSG_SPLINE_SET_TURN_RATE,            MSG_MOVE_SET_TURN_RATE},
    {SMSG_FORCE_FLIGHT_SPEED_CHANGE,      SMSG_SPLINE_SET_FLIGHT_SPEED,         MSG_MOVE_SET_FLIGHT_SPEED},
    {SMSG_FORCE_FLIGHT_BACK_SPEED_CHANGE, SMSG_SPLINE_SET_FLIGHT_BACK_SPEED,    MSG_MOVE_SET_FLIGHT_BACK_SPEED},
    {SMSG_FORCE_PITCH_RATE_CHANGE,        SMSG_SPLINE_SET_PITCH_RATE,           MSG_MOVE_SET_PITCH_RATE},
}
Definition at line 440 of file Unit.h.
Referenced by WorldSession::HandleForceSpeedChangeAckOpcodes(), and Unit::SetSpeedRate().