CMaNGOS_WoTLK: guards.cpp File Reference
guards.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/guard_ai.h"
#include "GameEvents/GameEventMgr.h"
Data Structures
struct guard_hallows_end_helperAI
struct guard_shattrath_aldorAI
struct guard_shattrath_scryerAI
struct guardAI_stormwind
Enumerations
enum { SPELL_WINDSOR_INSPIRATION_EFFECT = 20275 , MAX_GUARD_SALUTES = 7 }
enum {
SPELL_RETURN_ORGRIMMAR = 58552 , SPELL_RETURN_STORMWIND = 58533 , SPELL_TOSS_APPLE = 58509 , SPELL_TOSS_BANANA = 58513 ,
SPELL_SPIT = 58520 , EMOTE_APPLE = -1609081 , EMOTE_BANANA = -1609082 , EMOTE_SPIT = -1609083 ,
SAY_RANDOM_1 = -1609084 , SAY_RANDOM_2 = -1609085 , SAY_RANDOM_3 = -1609086 , SAY_RANDOM_4 = -1609087 ,
SAY_RANDOM_5 = -1609088 , SAY_RANDOM_6 = -1609287 , SAY_RANDOM_7 = -1609288 , SAY_RANDOM_8 = -1609289
}
Functions
bool GossipHello_guard_hallows_end_helper (Player *player, Creature *creature)
UnitAI * GetAI_guard_azuremyst (Creature *pCreature)
UnitAI * GetAI_guard_bluffwatcher (Creature *pCreature)
UnitAI * GetAI_guard_contested (Creature *pCreature)
UnitAI * GetAI_guard_darnassus (Creature *pCreature)
UnitAI * GetAI_guard_dunmorogh (Creature *pCreature)
UnitAI * GetAI_guard_durotar (Creature *pCreature)
UnitAI * GetAI_guard_elwynnforest (Creature *pCreature)
UnitAI * GetAI_guard_eversong (Creature *pCreature)
UnitAI * GetAI_guard_exodar (Creature *pCreature)
UnitAI * GetAI_guard_ironforge (Creature *pCreature)
UnitAI * GetAI_guard_mulgore (Creature *pCreature)
UnitAI * GetAI_guard_orgrimmar (Creature *pCreature)
UnitAI * GetAI_guard_shattrath (Creature *pCreature)
UnitAI * GetAI_guard_shattrath_aldor (Creature *pCreature)
UnitAI * GetAI_guard_shattrath_scryer (Creature *pCreature)
UnitAI * GetAI_guard_silvermoon (Creature *pCreature)
UnitAI * GetAI_guard_stormwind (Creature *pCreature)
UnitAI * GetAI_guard_teldrassil (Creature *pCreature)
UnitAI * GetAI_guard_tirisfal (Creature *pCreature)
UnitAI * GetAI_guard_undercity (Creature *pCreature)
bool EffectDummyCreature_npc_city_guard (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_guards ()
Variables
static const int32 aGuardSalute [MAX_GUARD_SALUTES] = { -1000842, -1000843, -1000844, -1000845, -1000846, -1000847, -1000848}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_WINDSOR_INSPIRATION_EFFECT
MAX_GUARD_SALUTES
Definition at line 425 of file guards.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RETURN_ORGRIMMAR
SPELL_RETURN_STORMWIND
SPELL_TOSS_APPLE
SPELL_TOSS_BANANA
SPELL_SPIT
EMOTE_APPLE
EMOTE_BANANA
EMOTE_SPIT
SAY_RANDOM_1
SAY_RANDOM_2
SAY_RANDOM_3
SAY_RANDOM_4
SAY_RANDOM_5
SAY_RANDOM_6
SAY_RANDOM_7
SAY_RANDOM_8
Definition at line 499 of file guards.cpp.
Function Documentation
AddSC_guards()
void AddSC_guards ()
Definition at line 558 of file guards.cpp.
References EffectDummyCreature_npc_city_guard(), Script::GetAI, GetAI_guard_azuremyst(), GetAI_guard_bluffwatcher(), GetAI_guard_contested(), GetAI_guard_darnassus(), GetAI_guard_dunmorogh(), GetAI_guard_durotar(), GetAI_guard_elwynnforest(), GetAI_guard_eversong(), GetAI_guard_exodar(), GetAI_guard_ironforge(), GetAI_guard_mulgore(), GetAI_guard_orgrimmar(), GetAI_guard_shattrath(), GetAI_guard_shattrath_aldor(), GetAI_guard_shattrath_scryer(), GetAI_guard_silvermoon(), GetAI_guard_stormwind(), GetAI_guard_teldrassil(), GetAI_guard_tirisfal(), GetAI_guard_undercity(), GossipHello_guard_hallows_end_helper(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_city_guard()
bool EffectDummyCreature_npc_city_guard (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 521 of file guards.cpp.
References Unit::CastSpell(), DoScriptText(), EFFECT_INDEX_0, EMOTE_APPLE, EMOTE_BANANA, EMOTE_SPIT, SAY_RANDOM_1, SAY_RANDOM_2, SAY_RANDOM_3, SAY_RANDOM_4, SAY_RANDOM_5, SAY_RANDOM_6, SAY_RANDOM_7, SAY_RANDOM_8, SPELL_RETURN_ORGRIMMAR, SPELL_RETURN_STORMWIND, SPELL_SPIT, SPELL_TOSS_APPLE, SPELL_TOSS_BANANA, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by AddSC_guards().
GetAI_guard_azuremyst()
UnitAI* GetAI_guard_azuremyst (Creature * pCreature)
Definition at line 221 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_bluffwatcher()
UnitAI* GetAI_guard_bluffwatcher (Creature * pCreature)
Definition at line 226 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_contested()
UnitAI* GetAI_guard_contested (Creature * pCreature)
Definition at line 231 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_darnassus()
UnitAI* GetAI_guard_darnassus (Creature * pCreature)
Definition at line 236 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_dunmorogh()
UnitAI* GetAI_guard_dunmorogh (Creature * pCreature)
Definition at line 241 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_durotar()
UnitAI* GetAI_guard_durotar (Creature * pCreature)
Definition at line 246 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_elwynnforest()
UnitAI* GetAI_guard_elwynnforest (Creature * pCreature)
Definition at line 251 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_eversong()
UnitAI* GetAI_guard_eversong (Creature * pCreature)
Definition at line 256 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_exodar()
UnitAI* GetAI_guard_exodar (Creature * pCreature)
Definition at line 261 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_ironforge()
UnitAI* GetAI_guard_ironforge (Creature * pCreature)
Definition at line 266 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_mulgore()
UnitAI* GetAI_guard_mulgore (Creature * pCreature)
Definition at line 271 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_orgrimmar()
UnitAI* GetAI_guard_orgrimmar (Creature * pCreature)
Definition at line 276 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_shattrath()
UnitAI* GetAI_guard_shattrath (Creature * pCreature)
Definition at line 281 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_shattrath_aldor()
UnitAI* GetAI_guard_shattrath_aldor (Creature * pCreature)
Definition at line 348 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_shattrath_scryer()
UnitAI* GetAI_guard_shattrath_scryer (Creature * pCreature)
Definition at line 415 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_silvermoon()
UnitAI* GetAI_guard_silvermoon (Creature * pCreature)
Definition at line 420 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_stormwind()
UnitAI* GetAI_guard_stormwind (Creature * pCreature)
Definition at line 475 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_teldrassil()
UnitAI* GetAI_guard_teldrassil (Creature * pCreature)
Definition at line 480 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_tirisfal()
UnitAI* GetAI_guard_tirisfal (Creature * pCreature)
Definition at line 485 of file guards.cpp.
Referenced by AddSC_guards().
GetAI_guard_undercity()
UnitAI* GetAI_guard_undercity (Creature * pCreature)
Definition at line 490 of file guards.cpp.
Referenced by AddSC_guards().
GossipHello_guard_hallows_end_helper()
bool GossipHello_guard_hallows_end_helper (Player * player, Creature * creature)
Definition at line 185 of file guards.cpp.
References Object::GetDbGuid(), Player::GetDefaultGossipMenuForSource(), Object::GetEntry(), Object::GetObjectGuid(), NPC_AZUREMYST_PEACEKEEPER, NPC_DEATHGUARD_FLORENCE, NPC_IRONFORGE_MOUNTAINEER, NPC_RAZOR_HILL_GRUNT, NPC_SILVERMOON_GUARDIAN, NPC_STORMWIND_GUARD, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), sGameEventMgr, TEXT_ID_AZUREMYST_PEACEKEEPER, TEXT_ID_DEATHGUARD_FLORENCE, TEXT_ID_IRONFORGE_MOUNTAINEER, TEXT_ID_RAZOR_HILL_GRUNT, TEXT_ID_SILVERMOON_GUARDIAN, and TEXT_ID_STORMWIND_GUARD.
Referenced by AddSC_guards().
Variable Documentation
aGuardSalute
const int32 aGuardSalute[MAX_GUARD_SALUTES] = { -1000842, -1000843, -1000844, -1000845, -1000846, -1000847, -1000848} static
Definition at line 430 of file guards.cpp.
Referenced by guardAI_stormwind::SpellHit().