CMaNGOS_WoTLK: gundrak.cpp File Reference
gundrak.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "gundrak.h"
Functions
bool GOUse_go_gundrak_altar (Player *, GameObject *go)
static bool sortFromEastToWest (Creature *first, Creature *second)
void AddSC_instance_gundrak ()
Function Documentation
AddSC_instance_gundrak()
void AddSC_instance_gundrak ()
Definition at line 489 of file gundrak.cpp.
References Script::GetInstanceData, GOUse_go_gundrak_altar(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GOUse_go_gundrak_altar()
bool GOUse_go_gundrak_altar (Player * , GameObject * go)
Definition at line 27 of file gundrak.cpp.
References Object::GetEntry(), WorldObject::GetInstanceData(), GO_ALTAR_OF_COLOSSUS, GO_ALTAR_OF_MOORABI, GO_ALTAR_OF_SLADRAN, InstanceData::SetData(), SPECIAL, TYPE_COLOSSUS, TYPE_MOORABI, TYPE_SLADRAN, and GameObject::UseDoorOrButton().
Referenced by AddSC_instance_gundrak().
sortFromEastToWest()
static bool sortFromEastToWest (Creature * first, Creature * second) static
Definition at line 339 of file gundrak.cpp.
References WorldObject::GetPositionY().
Referenced by instance_gundrak::DoAltarVisualEffect().