CMaNGOS_WoTLK: gunship_battle.cpp File Reference
gunship_battle.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct spell_incinerating_blast
Enumerations
enum {
GOSSIP_ITEM_ID_START_HORDE = -3631006 , GOSSIP_ITEM_ID_START_ALLIANCE = -3631007 , TEXT_ID_START_HORDE = 15219 , TEXT_ID_START_ALLIANCE = 15101 ,
SPELL_TELEPORT_PLAYERS_RESET_A = 70446 , SPELL_TELEPORT_PLAYERS_RESET_H = 71284 , SPELL_GUNSHIP_FALL_TELEPORT = 67335 , SPELL_LOCK_PLAYERS_TAP_CHEST = 72347 ,
SPELL_HATE_TO_ZERO = 63984 , SPELL_MELEE_TARGETING_A = 70219 , SPELL_MELEE_TARGETING_H = 70294 , SPELL_EXPLOSION_FAIL = 72134 ,
SPELL_EXPLOSION_VICTORY = 72137 , SPELL_TELEPORT_ENEMY_SHIP = 70104 , SPELL_BERSERK = 72525 , SPELL_BATTLE_EXPERIENCE = 71201
}
Functions
bool GossipHello_npc_saurfang_gunship (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_saurfang_gunship (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipHello_npc_muradin_gunship (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_muradin_gunship (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_gunship_battle ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ID_START_HORDE
GOSSIP_ITEM_ID_START_ALLIANCE
TEXT_ID_START_HORDE
TEXT_ID_START_ALLIANCE
SPELL_TELEPORT_PLAYERS_RESET_A
SPELL_TELEPORT_PLAYERS_RESET_H
SPELL_GUNSHIP_FALL_TELEPORT
SPELL_LOCK_PLAYERS_TAP_CHEST
SPELL_HATE_TO_ZERO
SPELL_MELEE_TARGETING_A
SPELL_MELEE_TARGETING_H
SPELL_EXPLOSION_FAIL
SPELL_EXPLOSION_VICTORY
SPELL_TELEPORT_ENEMY_SHIP
SPELL_BERSERK
SPELL_BATTLE_EXPERIENCE
Definition at line 29 of file gunship_battle.cpp.
Function Documentation
AddSC_gunship_battle()
void AddSC_gunship_battle ()
Definition at line 156 of file gunship_battle.cpp.
References GossipHello_npc_muradin_gunship(), GossipHello_npc_saurfang_gunship(), GossipSelect_npc_muradin_gunship(), GossipSelect_npc_saurfang_gunship(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_muradin_gunship()
bool GossipHello_npc_muradin_gunship (Player * pPlayer, Creature * pCreature)
Definition at line 95 of file gunship_battle.cpp.
References FAIL, Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_START_ALLIANCE, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), NOT_STARTED, Player::PrepareQuestMenu(), TEXT_ID_START_ALLIANCE, and TYPE_GUNSHIP_BATTLE.
Referenced by AddSC_gunship_battle().
GossipHello_npc_saurfang_gunship()
bool GossipHello_npc_saurfang_gunship (Player * pPlayer, Creature * pCreature)
Definition at line 61 of file gunship_battle.cpp.
References FAIL, Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_START_HORDE, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), NOT_STARTED, Player::PrepareQuestMenu(), TEXT_ID_START_HORDE, and TYPE_GUNSHIP_BATTLE.
Referenced by AddSC_gunship_battle().
GossipSelect_npc_muradin_gunship()
bool GossipSelect_npc_muradin_gunship (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 114 of file gunship_battle.cpp.
References WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, Object::RemoveFlag(), SPECIAL, TYPE_GUNSHIP_BATTLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_gunship_battle().
GossipSelect_npc_saurfang_gunship()
bool GossipSelect_npc_saurfang_gunship (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 80 of file gunship_battle.cpp.
References WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, Object::RemoveFlag(), SPECIAL, TYPE_GUNSHIP_BATTLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_gunship_battle().