CMaNGOS_WoTLK: halls_of_stone.cpp File Reference
halls_of_stone.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_stone.h"
Data Structures
struct SortHelper
Enumerations
enum {
SPELL_GLARE_OF_THE_TRIBUNAL = 50988 , SPELL_GLARE_OF_THE_TRIBUNAL_H = 59870 , SPELL_SUMMON_SEARING_GAZE_TARGET = 51146 , SPELL_KILL_TRIBUNAL_ADD = 51289 ,
SPELL_ACHIEVEMENT_CHECK = 59046 , SPELL_LIGHTNING_CHANNEL_1 = 50626 , SPELL_LIGHTNING_CHANNEL_2 = 50639 , SPELL_LIGHTNING_CHANNEL_3 = 50640 ,
SPELL_SUMMON_PROTECTOR = 51780 , SPELL_SUMMON_STORMCALLER = 51050 , SPELL_SUMMON_CUSTODIAN = 51051
}
Functions
static void GetValidNPCsOfList (Map *pMap, GuidList &lGUIDs, CreatureList &lNPCs)
InstanceData * GetInstanceData_instance_halls_of_stone (Map *pMap)
void AddSC_instance_halls_of_stone ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_GLARE_OF_THE_TRIBUNAL
SPELL_GLARE_OF_THE_TRIBUNAL_H
SPELL_SUMMON_SEARING_GAZE_TARGET
SPELL_KILL_TRIBUNAL_ADD
SPELL_ACHIEVEMENT_CHECK
SPELL_LIGHTNING_CHANNEL_1
SPELL_LIGHTNING_CHANNEL_2
SPELL_LIGHTNING_CHANNEL_3
SPELL_SUMMON_PROTECTOR
SPELL_SUMMON_STORMCALLER
SPELL_SUMMON_CUSTODIAN
Definition at line 27 of file halls_of_stone.cpp.
Function Documentation
AddSC_instance_halls_of_stone()
void AddSC_instance_halls_of_stone ()
Definition at line 692 of file halls_of_stone.cpp.
References Script::GetInstanceData, GetInstanceData_instance_halls_of_stone(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_halls_of_stone()
InstanceData* GetInstanceData_instance_halls_of_stone (Map * pMap)
Definition at line 687 of file halls_of_stone.cpp.
Referenced by AddSC_instance_halls_of_stone().
GetValidNPCsOfList()
static void GetValidNPCsOfList (Map * pMap, GuidList & lGUIDs, CreatureList & lNPCs) static
Definition at line 370 of file halls_of_stone.cpp.
References Map::GetCreature().
Referenced by instance_halls_of_stone::SortFaces().