CMaNGOS_WoTLK: halls_of_reflection.cpp File Reference
halls_of_reflection.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_reflection.h"
#include "Entities/Transports.h"
Enumerations
enum {
SAY_ALLY_INTRO_1 = -1668001 , SAY_ALLY_INTRO_2 = -1668002 , SAY_HORDE_INTRO_1 = -1668003 , SAY_HORDE_INTRO_2 = -1668004 ,
SAY_QUELDELAR_INTRO = -1668009 , SPELL_START_HALLS_REFLECTION = 72900 , SPELL_SPIRIT_ACTIVATE_VISUAL = 72130 , SPELL_FINDING_JAINA_CREDIT = 71538 ,
SPELL_FINDING_SYLVANAS_CREDIT = 71536 , QUEST_ID_HALLS_REFLECTION_ALLY = 24480 , QUEST_ID_HALLS_REFLECTION_HORDE = 24561
}
Functions
InstanceData * GetInstanceData_instance_halls_of_reflection (Map *pMap)
void AddSC_instance_halls_of_reflection ()
Variables
static const DialogueEntryTwoSide aHoRDialogues []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ALLY_INTRO_1
SAY_ALLY_INTRO_2
SAY_HORDE_INTRO_1
SAY_HORDE_INTRO_2
SAY_QUELDELAR_INTRO
SPELL_START_HALLS_REFLECTION
SPELL_SPIRIT_ACTIVATE_VISUAL
SPELL_FINDING_JAINA_CREDIT
SPELL_FINDING_SYLVANAS_CREDIT
QUEST_ID_HALLS_REFLECTION_ALLY
QUEST_ID_HALLS_REFLECTION_HORDE
Definition at line 28 of file halls_of_reflection.cpp.
Function Documentation
AddSC_instance_halls_of_reflection()
void AddSC_instance_halls_of_reflection ()
Definition at line 701 of file halls_of_reflection.cpp.
References Script::GetInstanceData, GetInstanceData_instance_halls_of_reflection(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_halls_of_reflection()
InstanceData* GetInstanceData_instance_halls_of_reflection (Map * pMap)
Definition at line 696 of file halls_of_reflection.cpp.
Referenced by AddSC_instance_halls_of_reflection().
Variable Documentation
aHoRDialogues
const DialogueEntryTwoSide aHoRDialogues[] static
Initial value:
=
{
    {SAY_ALLY_INTRO_1,      NPC_LICH_KING,      SAY_HORDE_INTRO_1,  NPC_LICH_KING,      12000},
    {NPC_LICH_KING,         0,                  0,                  0,                  5000},
    {SAY_ALLY_INTRO_2,      NPC_JAINA_PART2,    SAY_HORDE_INTRO_2,  NPC_SYLVANAS_PART2, 0},
    {NPC_FROSTMOURNE_ALTAR_BUNNY, 0,            0,                  0,                  3000},
    {NPC_UTHER,             0,                  0,                  0,                  1000},
    {SAY_QUELDELAR_INTRO,   NPC_UTHER,          0,                  0,                  0},
    {0, 0, 0},
}
Definition at line 49 of file halls_of_reflection.cpp.