CMaNGOS_WoTLK: halls_of_stoneScripts.cpp File Reference
halls_of_stoneScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_stone.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_brann_hosAI
struct npc_dark_matterAI
struct spell_shatter
struct spell_petrifying_grip_aura
struct spell_carve_stone_aura
struct spell_taunt_brann
Enumerations
enum {
SAY_KILL_1 = -1599012 , SAY_KILL_2 = -1599013 , SAY_KILL_3 = -1599014 , SAY_LOW_HEALTH = -1599015 ,
SAY_DEATH = -1599016 , SAY_PLAYER_DEATH_1 = -1599017 , SAY_PLAYER_DEATH_2 = -1599018 , SAY_PLAYER_DEATH_3 = -1599019 ,
SAY_ESCORT_START = -1599020 , SAY_EVENT_INTRO_2 = -1599026 , SAY_EVENT_INTRO_3_ABED = -1599027 , SAY_EVENT_A_1 = -1599028 ,
SAY_EVENT_A_2_KADD = -1599029 , SAY_EVENT_A_3 = -1599030 , SAY_EVENT_B_1 = -1599031 , SAY_EVENT_B_2_MARN = -1599032 ,
SAY_EVENT_B_3 = -1599033 , SAY_EVENT_C_1 = -1599034 , SAY_EVENT_C_2_ABED = -1599035 , SAY_EVENT_C_3 = -1599036 ,
SAY_EVENT_D_1 = -1599037 , SAY_EVENT_D_2_ABED = -1599038 , SAY_EVENT_D_3 = -1599039 , SAY_EVENT_D_4_ABED = -1599040 ,
SAY_EVENT_END_01 = -1599041 , SAY_EVENT_END_02 = -1599042 , SAY_EVENT_END_03_ABED = -1599043 , SAY_EVENT_END_04 = -1599044 ,
SAY_EVENT_END_05_ABED = -1599045 , SAY_EVENT_END_06 = -1599046 , SAY_EVENT_END_07_ABED = -1599047 , SAY_EVENT_END_08 = -1599048 ,
SAY_EVENT_END_09_KADD = -1599049 , SAY_EVENT_END_10 = -1599050 , SAY_EVENT_END_11_KADD = -1599051 , SAY_EVENT_END_12 = -1599052 ,
SAY_EVENT_END_13_KADD = -1599053 , SAY_EVENT_END_14 = -1599054 , SAY_EVENT_END_15_MARN = -1599055 , SAY_EVENT_END_16 = -1599056 ,
SAY_EVENT_END_17_MARN = -1599057 , SAY_EVENT_END_18 = -1599058 , SAY_EVENT_END_19_MARN = -1599059 , SAY_EVENT_END_20 = -1599060 ,
SAY_EVENT_END_21_ABED = -1599061 , SAY_ENTRANCE_MEET = -1599064 , GOSSIP_ITEM_ID_START = -3599000 , GOSSIP_ITEM_ID_PROGRESS = -3599001 ,
GOSSIP_ITEM_ID_END_TRIBUNAL = -3599002 , GOSSIP_ITEM_ID_START_SJONNIR = -3599003 , TEXT_ID_START = 13100 , TEXT_ID_PROGRESS = 13101 ,
TEXT_ID_END_TRIBUNAL = 14176 , TEXT_ID_START_SJONNIR = 13883 , SPELL_BRANN_HEALTH_CHECK = 51810 , EVENT_ID_BRANN_ACHIEV_FAIL = 20645 ,
PHASE_GETTING_THERE = 0 , PHASE_TRIBUNAL = 1 , PHASE_ENDING = 2 , PHASE_DESPAWN = 3 ,
PHASE_SJONNIR = 4
}
enum { SPELL_SUMMON_DARK_MATTER_TARGET = 51003 , SPELL_DARK_MATTER = 51012 , SPELL_DARK_MATTER_H = 59868 }
Functions
bool GossipHello_npc_brann_hos (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_brann_hos (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool ProcessEventId_event_spell_brann_achievement_fail (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_halls_of_stone ()
Variables
static const DialogueEntry aTribunalDialogue []
static const float fBrannResetLocation [4] = { 939.6467f, 375.48926f, 207.42229f, 3.92699f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_KILL_1
SAY_KILL_2
SAY_KILL_3
SAY_LOW_HEALTH
SAY_DEATH
SAY_PLAYER_DEATH_1
SAY_PLAYER_DEATH_2
SAY_PLAYER_DEATH_3
SAY_ESCORT_START
SAY_EVENT_INTRO_2
SAY_EVENT_INTRO_3_ABED
SAY_EVENT_A_1
SAY_EVENT_A_2_KADD
SAY_EVENT_A_3
SAY_EVENT_B_1
SAY_EVENT_B_2_MARN
SAY_EVENT_B_3
SAY_EVENT_C_1
SAY_EVENT_C_2_ABED
SAY_EVENT_C_3
SAY_EVENT_D_1
SAY_EVENT_D_2_ABED
SAY_EVENT_D_3
SAY_EVENT_D_4_ABED
SAY_EVENT_END_01
SAY_EVENT_END_02
SAY_EVENT_END_03_ABED
SAY_EVENT_END_04
SAY_EVENT_END_05_ABED
SAY_EVENT_END_06
SAY_EVENT_END_07_ABED
SAY_EVENT_END_08
SAY_EVENT_END_09_KADD
SAY_EVENT_END_10
SAY_EVENT_END_11_KADD
SAY_EVENT_END_12
SAY_EVENT_END_13_KADD
SAY_EVENT_END_14
SAY_EVENT_END_15_MARN
SAY_EVENT_END_16
SAY_EVENT_END_17_MARN
SAY_EVENT_END_18
SAY_EVENT_END_19_MARN
SAY_EVENT_END_20
SAY_EVENT_END_21_ABED
SAY_ENTRANCE_MEET
GOSSIP_ITEM_ID_START
GOSSIP_ITEM_ID_PROGRESS
GOSSIP_ITEM_ID_END_TRIBUNAL
GOSSIP_ITEM_ID_START_SJONNIR
TEXT_ID_START
TEXT_ID_PROGRESS
TEXT_ID_END_TRIBUNAL
TEXT_ID_START_SJONNIR
SPELL_BRANN_HEALTH_CHECK
EVENT_ID_BRANN_ACHIEV_FAIL
PHASE_GETTING_THERE
PHASE_TRIBUNAL
PHASE_ENDING
PHASE_DESPAWN
PHASE_SJONNIR
Definition at line 29 of file halls_of_stoneScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_DARK_MATTER_TARGET
SPELL_DARK_MATTER
SPELL_DARK_MATTER_H
Definition at line 509 of file halls_of_stoneScripts.cpp.
Function Documentation
AddSC_halls_of_stone()
void AddSC_halls_of_stone ()
Definition at line 694 of file halls_of_stoneScripts.cpp.
References Script::GetAI, GossipHello_npc_brann_hos(), GossipSelect_npc_brann_hos(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_brann_achievement_fail(), and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_brann_hos()
bool GossipHello_npc_brann_hos (Player * pPlayer, Creature * pCreature)
Definition at line 453 of file halls_of_stoneScripts.cpp.
References DONE, FAIL, Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_END_TRIBUNAL, GOSSIP_ITEM_ID_PROGRESS, GOSSIP_ITEM_ID_START, GOSSIP_ITEM_ID_START_SJONNIR, GOSSIP_SENDER_MAIN, IN_PROGRESS, Unit::isQuestGiver(), NOT_STARTED, Player::PrepareQuestMenu(), SPECIAL, TEXT_ID_END_TRIBUNAL, TEXT_ID_PROGRESS, TEXT_ID_START, TEXT_ID_START_SJONNIR, TYPE_SJONNIR, and TYPE_TRIBUNAL.
Referenced by AddSC_halls_of_stone().
GossipSelect_npc_brann_hos()
bool GossipSelect_npc_brann_hos (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 487 of file halls_of_stoneScripts.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, AI_EVENT_CUSTOM_C, AI_EVENT_CUSTOM_D, GOSSIP_ACTION_INFO_DEF, PHASE_DESPAWN, PHASE_GETTING_THERE, PHASE_SJONNIR, PHASE_TRIBUNAL, and UnitAI::SendAIEvent().
Referenced by AddSC_halls_of_stone().
ProcessEventId_event_spell_brann_achievement_fail()
bool ProcessEventId_event_spell_brann_achievement_fail (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 678 of file halls_of_stoneScripts.cpp.
References EVENT_ID_BRANN_ACHIEV_FAIL, WorldObject::GetInstanceData(), Object::IsCreature(), and instance_halls_of_stone::SetBrannSpankin().
Referenced by AddSC_halls_of_stone().
Variable Documentation
aTribunalDialogue
const DialogueEntry aTribunalDialogue[] static
Definition at line 115 of file halls_of_stoneScripts.cpp.
fBrannResetLocation
const float fBrannResetLocation[4] = { 939.6467f, 375.48926f, 207.42229f, 3.92699f } static
Definition at line 169 of file halls_of_stoneScripts.cpp.
Referenced by npc_brann_hosAI::JustRespawned().