CMaNGOS_WoTLK: halls_of_reflectionScripts.cpp File Reference
halls_of_reflectionScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "halls_of_reflection.h"
#include "Entities/TemporarySpawn.h"
#include "Spells/SpellAuras.h"
Data Structures
struct spell_gunship_cannon_fire_aura
struct spell_halls_of_reflection_clone
struct spell_start_halls_of_reflection_quest
Enumerations
enum { SAY_MARWYN_GAUNTLET_START = -1668000 }
enum { SPELL_FROSTMOURNE_EQUIP = 72729 }
enum { SPELL_FROZEN_POSITION = 69609 , SPELL_HALLS_OF_REFLECTION_CLONE_NAME = 69837 , SPELL_HALLS_OF_REFLECTION_CLONE = 69828 , SPELL_HALLS_OF_REFLECTION_GHOST = 69861 }
enum { SPELL_SUMMON_REFLECTIONS = 69223 , SPELL_JUMPT_TO_TARGET = 69886 }
enum { SPELL_QUELDELARS_WILL = 70698 }
Functions
bool AreaTrigger_at_frostmourne_chamber (Player *pPlayer, AreaTriggerEntry const *pAt)
bool EffectAuraDummy_spell_aura_dummy_frostmourne_equip (const Aura *pAura, bool bApply)
bool AreaTrigger_at_frostworn_general (Player *pPlayer, AreaTriggerEntry const *pAt)
bool EffectDummyCreature_spell_summon_reflections (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool AreaTrigger_at_queldelar_start (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_halls_of_reflection ()
Variables
static const float afFalricSpawnLoc [4] = { 5276.583f, 2037.450f, 709.402f, 5.532f }
static const float afMarwybSpawnLoc [4] = { 5342.232f, 1975.696f, 709.402f, 2.391f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_MARWYN_GAUNTLET_START
Definition at line 40 of file halls_of_reflectionScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FROSTMOURNE_EQUIP
Definition at line 80 of file halls_of_reflectionScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FROZEN_POSITION
SPELL_HALLS_OF_REFLECTION_CLONE_NAME
SPELL_HALLS_OF_REFLECTION_CLONE
SPELL_HALLS_OF_REFLECTION_GHOST
Definition at line 113 of file halls_of_reflectionScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_REFLECTIONS
SPELL_JUMPT_TO_TARGET
Definition at line 186 of file halls_of_reflectionScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_QUELDELARS_WILL
Definition at line 235 of file halls_of_reflectionScripts.cpp.
Function Documentation
AddSC_halls_of_reflection()
void AddSC_halls_of_reflection ()
Definition at line 339 of file halls_of_reflectionScripts.cpp.
References AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_queldelar_start(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), EffectDummyCreature_spell_summon_reflections(), Script::Name, Script::pAreaTrigger, Script::pEffectAuraDummy, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_frostmourne_chamber()
bool AreaTrigger_at_frostmourne_chamber (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 48 of file halls_of_reflectionScripts.cpp.
References afFalricSpawnLoc, afMarwybSpawnLoc, AREATRIGGER_FROSTMOURNE_ALTAR, DONE, DoScriptText(), FAIL, instance_halls_of_reflection::GetData(), WorldObject::GetInstanceData(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), NPC_FALRIC, NPC_MARWYN, SAY_MARWYN_GAUNTLET_START, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_FALRIC, TYPE_FROSTMOURNE_INTRO, TYPE_MARWYN, and TYPE_QUEL_DELAR.
Referenced by AddSC_halls_of_reflection().
AreaTrigger_at_frostworn_general()
bool AreaTrigger_at_frostworn_general (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 121 of file halls_of_reflectionScripts.cpp.
References AREATRIGGER_FROSTWORN_GENERAL, Unit::CastSpell(), DONE, Map::GetCreature(), instance_halls_of_reflection::GetData(), instance_halls_of_reflection::GetDungeonTrapsGUIDList(), WorldObject::GetInstanceData(), WorldObject::GetMap(), WorldObject::GetOrientation(), Map::GetPlayers(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), AreaTriggerEntry::id, IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), LinkedListHead::isEmpty(), Player::IsGameMaster(), NPC_SPIRITUAL_REFLECTION_1, NPC_SPIRITUAL_REFLECTION_2, script_error_log(), instance_halls_of_reflection::SetData(), SPELL_HALLS_OF_REFLECTION_CLONE, SPELL_HALLS_OF_REFLECTION_CLONE_NAME, SPELL_HALLS_OF_REFLECTION_GHOST, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_FROSTWORN_GENERAL, TYPE_MARWYN, and urand().
Referenced by AddSC_halls_of_reflection().
AreaTrigger_at_queldelar_start()
bool AreaTrigger_at_queldelar_start (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 240 of file halls_of_reflectionScripts.cpp.
References AREATRIGGER_QUELDELAR_START, Unit::CastSpell(), instance_halls_of_reflection::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::HasAura(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), NPC_UTHER, instance_halls_of_reflection::SetData(), SPECIAL, SPELL_QUELDELAR_COMPULSION, SPELL_QUELDELARS_WILL, TRIGGERED_OLD_TRIGGERED, and TYPE_QUEL_DELAR.
Referenced by AddSC_halls_of_reflection().
EffectAuraDummy_spell_aura_dummy_frostmourne_equip()
bool EffectAuraDummy_spell_aura_dummy_frostmourne_equip (const Aura * pAura, bool bApply)
Definition at line 89 of file halls_of_reflectionScripts.cpp.
References EFFECT_INDEX_0, Aura::GetEffIndex(), Aura::GetId(), ScriptedInstance::GetSingleGameObjectFromStorage(), Aura::GetTarget(), GO_FROSTMOURNE, and SPELL_FROSTMOURNE_EQUIP.
Referenced by AddSC_halls_of_reflection().
EffectDummyCreature_spell_summon_reflections()
bool EffectDummyCreature_spell_summon_reflections (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 192 of file halls_of_reflectionScripts.cpp.
References EFFECT_INDEX_0, Map::GetCreature(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Map::GetPlayer(), instance_halls_of_reflection::GetReflectionsGUIDList(), script_error_log(), SPELL_FROZEN_POSITION, SPELL_JUMPT_TO_TARGET, SPELL_SUMMON_REFLECTIONS, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_halls_of_reflection().
Variable Documentation
afFalricSpawnLoc
const float afFalricSpawnLoc[4] = { 5276.583f, 2037.450f, 709.402f, 5.532f } static
Definition at line 45 of file halls_of_reflectionScripts.cpp.
Referenced by AreaTrigger_at_frostmourne_chamber().
afMarwybSpawnLoc
const float afMarwybSpawnLoc[4] = { 5342.232f, 1975.696f, 709.402f, 2.391f } static
Definition at line 46 of file halls_of_reflectionScripts.cpp.
Referenced by AreaTrigger_at_frostmourne_chamber().