CMaNGOS_WoTLK: hellfire_peninsula.cpp File Reference
hellfire_peninsula.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "AI/BaseAI/PetAI.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Entities/TemporarySpawn.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_aeranasAI
struct npc_ancestral_wolfAI
struct npc_demoniac_scryerAI
struct DemoniacVisitation
struct npc_wounded_blood_elfAI
struct npc_fel_guard_houndAI
struct npc_colonel_julesAI
struct npc_anchorite_baradaAI
struct npc_magister_aledisAI
struct npc_living_flareAI
struct LivingFlareDetonator
struct LivingFlareMaster
struct LivingFlareUnstable
struct npc_danath_trollbaneAI
struct npc_nazgrelAI
struct npc_vindicator_sedaiAI
struct npc_krunAI
struct npc_laughing_skullAI
struct npc_maghar_escortAI
struct KaliriNest
struct go_smoke_beacon
struct npc_credit_marker_they_must_burnAI
struct SummonSmokeBeacon
struct CursedScarabPeriodicTrigger
struct CursedScarabDespawnPeriodicTrigger
struct ExposeRazorthornRoot
struct npc_razorthorn_ravager_pet
struct npc_razorthorn_ravager
struct CharmRavager
Macros
#define GOSSIP_ITEM_ATTUNE "Yes, Scryer. You may possess me."
Enumerations
enum {
SAY_FREE = -1000139 , FACTION_HOSTILE = 16 , FACTION_FRIENDLY = 35 , SPELL_ENVELOPING_WINDS = 15535 ,
SPELL_SHOCK = 12553
}
enum {
EMOTE_WOLF_LIFT_HEAD = -1000496 , EMOTE_WOLF_HOWL = -1000497 , SAY_WOLF_WELCOME = -1000498 , SPELL_ANCESTRAL_WOLF_BUFF = 29981 ,
SPELL_SELF_SNARE = 30011 , NPC_RYGA = 17123 , SOUND_HOWL = 1018
}
enum {
GOSSIP_TEXTID_PROTECT = 10659 , GOSSIP_TEXTID_ATTUNED = 10643 , QUEST_DEMONIAC = 10838 , NPC_HELLFIRE_WARDLING = 22259 ,
NPC_BUTTRESS = 22267 , NPC_SPAWNER = 22260 , MAX_BUTTRESS = 4 , TIME_TOTAL = MINUTE * 10 * IN_MILLISECONDS ,
SPELL_SUMMONED_DEMON = 7741 , SPELL_DEMONIAC_VISITATION = 38708 , SAY_DEMONIAC_VISITATION_END = 20154 , SPELL_BUTTRESS_APPERANCE = 38719 ,
SPELL_SUCKER_CHANNEL = 38721 , SPELL_SUCKER_DESPAWN_MOB = 38691
}
enum {
SAY_ELF_START = -1000117 , SAY_ELF_SUMMON1 = -1000118 , SAY_ELF_RESTING = -1000119 , SAY_ELF_SUMMON2 = -1000120 ,
SAY_ELF_COMPLETE = -1000121 , SAY_ELF_JUST_KILLED = -1000122 , NPC_WINDWALKER = 16966 , NPC_TALONGUARD = 16967 ,
QUEST_ROAD_TO_FALCON_WATCH = 9375 , DBSCRIPT_END_TALERIS_INT = 10028 , FACTION_TROLL_FROSTMANE = 33
}
enum { SPELL_CREATE_POODAD = 37688 , SPELL_FAKE_DOG_SPART = 37692 , SPELL_INFORM_DOG = 37689 , NPC_DERANGED_HELBOAR = 16863 }
enum {
SAY_EXORCISM_1 = -1000981 , SAY_EXORCISM_2 = -1000982 , SAY_EXORCISM_3 = -1000983 , SAY_EXORCISM_4 = -1000991 ,
SAY_EXORCISM_5 = -1000988 , SAY_EXORCISM_6 = -1000992 , SAY_EXORCISM_7 = -1000986 , BARADA_SAY_EXORCISM_RANDOM_1 = -1000987 ,
BARADA_SAY_EXORCISM_RANDOM_2 = -1015009 , BARADA_SAY_EXORCISM_RANDOM_3 = -1000989 , BARADA_SAY_EXORCISM_RANDOM_4 = -1015010 , BARADA_SAY_EXORCISM_RANDOM_5 = -1000984 ,
BARADA_SAY_EXORCISM_RANDOM_6 = -1015005 , BARADA_SAY_EXORCISM_RANDOM_7 = -1015007 , JULES_SAY_EXORCISM_RANDOM_1 = -1000990 , JULES_SAY_EXORCISM_RANDOM_2 = -1015006 ,
JULES_SAY_EXORCISM_RANDOM_3 = -1015008 , JULES_SAY_EXORCISM_RANDOM_4 = -1015011 , JULES_SAY_EXORCISM_RANDOM_5 = -1000985 , SPELL_BARADA_COMMANDS = 39277 ,
SPELL_BARADA_FALTERS = 39278 , SPELL_HEAL_SELF = 39321 , SPELL_JULES_THREATENS_AURA = 39284 , SPELL_JULES_GOES_UPRIGHT = 39294 ,
SPELL_JULES_VOMITS = 39295 , SPELL_JULES_RELEASE_DARKNESS = 39306 , SPELL_JULES_GOES_PRONE = 39283 , SPELL_FLYING_SKULL_DESPAWN = 39307 ,
NPC_ANCHORITE_BARADA = 22431 , NPC_COLONEL_JULES = 22432 , NPC_DARKNESS_RELEASED = 22507 , NPC_FOUL_PURGE = 22506 ,
NPC_BUBBLING_SLIMER_BUNNY = 22505 , NPC_EXORCISM_LIGHTNING_CLOUD = 22508 , GOSSIP_ITEM_EXORCISM = -3000111 , QUEST_ID_EXORCISM = 10935 ,
TEXT_ID_CLEANSED = 10706 , TEXT_ID_POSSESSED = 10707 , TEXT_ID_ANCHORITE = 10683
}
enum {
SAY_ALEDIS_DEFEAT = -1001172 , SPELL_PYROBLAST = 33975 , SPELL_FROST_NOVA = 11831 , SPELL_FIREBALL = 20823 ,
FACTION_ALLEDIS_FRIENDLY = 35 , FACTION_ALLEDIS_HOSTILE = 634 , POINT_MOVE_DISTANCE = 1
}
enum AledisActions {
ALEDIS_LOW_HP , ALEDIS_ACTION_PYROBLAST , ALEDIS_ACTION_FROSTNOVA , ALEDIS_ACTION_FIREBALL ,
ALEDIS_ACTION_MAX
}
enum {
NPC_LIVING_FLARE = 24916 , NPC_GENERIC_QUEST_TRIGGER_LAB = 24959 , NPC_UNSTABLE_LIVING_FLARE = 24958 , GO_LARGE_FIRE = 187084 ,
SPELL_LIVING_FLARE_MASTER = 44877 , SPELL_FEL_FLAREUP = 44944 , SPELL_TRANSFORM = 44943 , SPELL_QUEST_CREDIT = 44947 ,
SPELL_DETONATOR = 44948 , SPELL_LIVING_COSMETIC = 44880 , SPELL_UNSTABLE_COSMETIC = 46196 , SPELL_HUGE_EXPLOSION_TEST = 46225 ,
EMOTE_LIVING_FLARE = -1001214 , EMOTE_UNSTABLE_FLARE = -1001215
}
enum {
QUEST_FALL_OF_MAGETHERIDON_A = 11002 , QUEST_FALL_OF_MAGETHERIDON_H = 11003 , YELL_1_DELAY = 2000 , YELL_2_DELAY = 8000 ,
YELL_TROLLBANE_1 = -1000590 , YELL_TROLLBANE_2 = -1000591 , YELL_NAZGREL_1 = -1000592 , YELL_NAZGREL_2 = -1000593 ,
SPELL_TROLLBANES_COMMAND = 39911 , SPELL_NAZGRELS_FAVOR = 39913 , MAX_SEARCH_DIST = 2170 , OBJECT_MAGTHERIDONS_HEAD = 184640
}
enum {
QUEST_SEERS_RELIC = 9545 , NPC_SEDAI = 17404 , NPC_SEDAI_CORPSE = 16852 , NPC_MAGHAR_ESCORT = 17417 ,
NPC_FEL_ORC = 17418 , NPC_KRUN = 17405 , NPC_SEDAI_QCM = 17413 , SAY_EVENT_MAGHAR_ESCORT = -1015066 ,
SAY_EVENT_SEDAI_1 = -1015067 , SAY_EVENT_SEDAI_2 = -1015068 , SAY_EVENT_SEDAI_3 = -1015069 , SAY_EVENT_SEDAI_4 = -1015070 ,
SAY_EVENT_KRUN = -1015071 , SPELL_EXECUTE_SEDAI = 30462 , SPELL_HOLY_FIRE = 17141 , SPELL_HAMMER_OF_JUSTICE = 13005 ,
SPELL_KICK = 30460
}
enum SedaiActions : uint32 {
SEDAI_COMBAT_ACTION_HOLYFIRE , SEDAI_COMBAT_ACTION_HAMMER , SEDAI_COMBAT_ACTION_MAX , SEDAI_ACTION_FACE_ESCORT ,
SEDAI_ACTION_ESCORT_KICK , SEDAI_ACTION_ESCORT_SAY , SEDAI_ACTION_SEDAI_KNEEL , SEDAI_ACTION_ESCORTS_MOVE_1 ,
SEDAI_ACTION_FELORC_SPAWN_ATTACK , SEDAI_ACTION_QUEST_COMPLETE , SEDAI_ACTION_SEDAI_MOVE_2 , SEDAI_ACTION_SEDAI_START_ATTACK
}
enum KrunActions : uint32 { KRUN_ACTION_EXECUTE_SEDAI , KRUN_ACTION_LAUGH , KRUN_ACTION_DESPAWN }
enum {
NPC_GRYPHON_BRIGADIER_SOUTH = 21170 , NPC_GRYPHON_BRIGADIER_NORTH = 22404 , NPC_GRYPHON_BRIGADIER_FORGE = 22405 , NPC_GRYPHON_BRIGADIER_FOOTHILL = 22406 ,
NPC_CREDIT_MARKER_SOUTH = 21182 , NPC_CREDIT_MARKER_NORTH = 22401 , NPC_CREDIT_MARKER_FORGE = 22402 , NPC_CREDIT_MARKER_FOOTHILL = 22403 ,
NPC_CREDIT_MARKER_THEY_MUST_BURN = 21173 , SPELL_SUMMON_BRIGADIER_SOUTH = 36302 , SPELL_SUMMON_BRIGADIER_NORTH = 39106 , SPELL_SUMMON_BRIGADIER_FORGE = 39107 ,
SPELL_SUMMON_BRIGADIER_FOOTHILL = 39108 , COUNT_SPAWNS = 4
}
enum { FACTION_SCARAB_HOSTILE = 14 }
enum {
SPELL_EXPOSE_RAZORTHORN_ROOT = 44935 , SPELL_SUMMON_RAZORTHORN_ROOT = 44941 , NPC_RAZORTHORN_RAVAGER = 24922 , GO_RAZORTHORN_DIRT_MOUND = 187073 ,
SPELL_REND = 13443 , SPELL_RAVAGE = 33781 , POINT_MOUND = 1
}
enum RazorthornActions { RAZORTHORN_REND , RAZORTHORN_RAVAGE , RAZORTHORN_ACTION_MAX }
Functions
UnitAI * GetAI_npc_aeranas (Creature *pCreature)
UnitAI * GetAI_npc_ancestral_wolf (Creature *pCreature)
UnitAI * GetAI_npc_demoniac_scryer (Creature *pCreature)
bool GossipHello_npc_demoniac_scryer (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_demoniac_scryer (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_wounded_blood_elf (Creature *pCreature)
bool QuestAccept_npc_wounded_blood_elf (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_fel_guard_hound (Creature *pCreature)
bool EffectDummyCreature_npc_fel_guard_hound (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_colonel_jules (Creature *pCreature)
UnitAI * GetAI_npc_anchorite_barada (Creature *pCreature)
bool GossipHello_npc_anchorite_barada (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_anchorite_barada (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipHello_npc_colonel_jules (Player *pPlayer, Creature *pCreature)
bool QuestComplete_npc_trollbane (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_danath_trollbane (Creature *pCreature)
bool QuestComplete_npc_nazgrel (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_nazgrel (Creature *pCreature)
UnitAI * GetAI_npc_vindicator_sedai (Creature *creature)
UnitAI * GetAI_npc_krun (Creature *creature)
UnitAI * GetAI_npc_laughing_skull (Creature *creature)
UnitAI * GetAI_npc_maghar_escort (Creature *creature)
bool ProcessEventId_sedai_vision (uint32, Object *source, Object *, bool)
GameObjectAI * GetAI_go_smoke_beacon (GameObject *go)
UnitAI * GetAI_npc_credit_marker_they_must_burn (Creature *pCreature)
void AddSC_hellfire_peninsula ()
Variables
static const DialogueEntry aExorcismDialogue []
static const int32 aAnchoriteTexts [7] = {BARADA_SAY_EXORCISM_RANDOM_1, BARADA_SAY_EXORCISM_RANDOM_2, BARADA_SAY_EXORCISM_RANDOM_3, BARADA_SAY_EXORCISM_RANDOM_4, BARADA_SAY_EXORCISM_RANDOM_5, BARADA_SAY_EXORCISM_RANDOM_6, BARADA_SAY_EXORCISM_RANDOM_7}
static const int32 aColonelTexts [5] = {JULES_SAY_EXORCISM_RANDOM_1, JULES_SAY_EXORCISM_RANDOM_2, JULES_SAY_EXORCISM_RANDOM_3, JULES_SAY_EXORCISM_RANDOM_4, JULES_SAY_EXORCISM_RANDOM_5}
Macro Definition Documentation
GOSSIP_ITEM_ATTUNE
#define GOSSIP_ITEM_ATTUNE "Yes, Scryer. You may possess me."
Definition at line 183 of file hellfire_peninsula.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_FREE
FACTION_HOSTILE
FACTION_FRIENDLY
SPELL_ENVELOPING_WINDS
SPELL_SHOCK
Definition at line 48 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_WOLF_LIFT_HEAD
EMOTE_WOLF_HOWL
SAY_WOLF_WELCOME
SPELL_ANCESTRAL_WOLF_BUFF
SPELL_SELF_SNARE
NPC_RYGA
SOUND_HOWL
Definition at line 118 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_TEXTID_PROTECT
GOSSIP_TEXTID_ATTUNED
QUEST_DEMONIAC
NPC_HELLFIRE_WARDLING
NPC_BUTTRESS
NPC_SPAWNER
MAX_BUTTRESS
TIME_TOTAL
SPELL_SUMMONED_DEMON
SPELL_DEMONIAC_VISITATION
SAY_DEMONIAC_VISITATION_END
SPELL_BUTTRESS_APPERANCE
SPELL_SUCKER_CHANNEL
SPELL_SUCKER_DESPAWN_MOB
Definition at line 185 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ELF_START
SAY_ELF_SUMMON1
SAY_ELF_RESTING
SAY_ELF_SUMMON2
SAY_ELF_COMPLETE
SAY_ELF_JUST_KILLED
NPC_WINDWALKER
NPC_TALONGUARD
QUEST_ROAD_TO_FALCON_WATCH
DBSCRIPT_END_TALERIS_INT
FACTION_TROLL_FROSTMANE
Definition at line 365 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CREATE_POODAD
SPELL_FAKE_DOG_SPART
SPELL_INFORM_DOG
NPC_DERANGED_HELBOAR
Definition at line 474 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_EXORCISM_1
SAY_EXORCISM_2
SAY_EXORCISM_3
SAY_EXORCISM_4
SAY_EXORCISM_5
SAY_EXORCISM_6
SAY_EXORCISM_7
BARADA_SAY_EXORCISM_RANDOM_1
BARADA_SAY_EXORCISM_RANDOM_2
BARADA_SAY_EXORCISM_RANDOM_3
BARADA_SAY_EXORCISM_RANDOM_4
BARADA_SAY_EXORCISM_RANDOM_5
BARADA_SAY_EXORCISM_RANDOM_6
BARADA_SAY_EXORCISM_RANDOM_7
JULES_SAY_EXORCISM_RANDOM_1
JULES_SAY_EXORCISM_RANDOM_2
JULES_SAY_EXORCISM_RANDOM_3
JULES_SAY_EXORCISM_RANDOM_4
JULES_SAY_EXORCISM_RANDOM_5
SPELL_BARADA_COMMANDS
SPELL_BARADA_FALTERS
SPELL_HEAL_SELF
SPELL_JULES_THREATENS_AURA
SPELL_JULES_GOES_UPRIGHT
SPELL_JULES_VOMITS
SPELL_JULES_RELEASE_DARKNESS
SPELL_JULES_GOES_PRONE
SPELL_FLYING_SKULL_DESPAWN
NPC_ANCHORITE_BARADA
NPC_COLONEL_JULES
NPC_DARKNESS_RELEASED
NPC_FOUL_PURGE
NPC_BUBBLING_SLIMER_BUNNY
NPC_EXORCISM_LIGHTNING_CLOUD
GOSSIP_ITEM_EXORCISM
QUEST_ID_EXORCISM
TEXT_ID_CLEANSED
TEXT_ID_POSSESSED
TEXT_ID_ANCHORITE
Definition at line 565 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ALEDIS_DEFEAT
SPELL_PYROBLAST
SPELL_FROST_NOVA
SPELL_FIREBALL
FACTION_ALLEDIS_FRIENDLY
FACTION_ALLEDIS_HOSTILE
POINT_MOVE_DISTANCE
Definition at line 1108 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_LIVING_FLARE
NPC_GENERIC_QUEST_TRIGGER_LAB
NPC_UNSTABLE_LIVING_FLARE
GO_LARGE_FIRE
SPELL_LIVING_FLARE_MASTER
SPELL_FEL_FLAREUP
SPELL_TRANSFORM
SPELL_QUEST_CREDIT
SPELL_DETONATOR
SPELL_LIVING_COSMETIC
SPELL_UNSTABLE_COSMETIC
SPELL_HUGE_EXPLOSION_TEST
EMOTE_LIVING_FLARE
EMOTE_UNSTABLE_FLARE
Definition at line 1255 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_FALL_OF_MAGETHERIDON_A
QUEST_FALL_OF_MAGETHERIDON_H
YELL_1_DELAY
YELL_2_DELAY
YELL_TROLLBANE_1
YELL_TROLLBANE_2
YELL_NAZGREL_1
YELL_NAZGREL_2
SPELL_TROLLBANES_COMMAND
SPELL_NAZGRELS_FAVOR
MAX_SEARCH_DIST
OBJECT_MAGTHERIDONS_HEAD
Definition at line 1431 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SEERS_RELIC
NPC_SEDAI
NPC_SEDAI_CORPSE
NPC_MAGHAR_ESCORT
NPC_FEL_ORC
NPC_KRUN
NPC_SEDAI_QCM
SAY_EVENT_MAGHAR_ESCORT
SAY_EVENT_SEDAI_1
SAY_EVENT_SEDAI_2
SAY_EVENT_SEDAI_3
SAY_EVENT_SEDAI_4
SAY_EVENT_KRUN
SPELL_EXECUTE_SEDAI
SPELL_HOLY_FIRE
SPELL_HAMMER_OF_JUSTICE
SPELL_KICK
Definition at line 1632 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_GRYPHON_BRIGADIER_SOUTH
NPC_GRYPHON_BRIGADIER_NORTH
NPC_GRYPHON_BRIGADIER_FORGE
NPC_GRYPHON_BRIGADIER_FOOTHILL
NPC_CREDIT_MARKER_SOUTH
NPC_CREDIT_MARKER_NORTH
NPC_CREDIT_MARKER_FORGE
NPC_CREDIT_MARKER_FOOTHILL
NPC_CREDIT_MARKER_THEY_MUST_BURN
SPELL_SUMMON_BRIGADIER_SOUTH
SPELL_SUMMON_BRIGADIER_NORTH
SPELL_SUMMON_BRIGADIER_FORGE
SPELL_SUMMON_BRIGADIER_FOOTHILL
COUNT_SPAWNS
Definition at line 2069 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
FACTION_SCARAB_HOSTILE
Definition at line 2220 of file hellfire_peninsula.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_EXPOSE_RAZORTHORN_ROOT
SPELL_SUMMON_RAZORTHORN_ROOT
NPC_RAZORTHORN_RAVAGER
GO_RAZORTHORN_DIRT_MOUND
SPELL_REND
SPELL_RAVAGE
POINT_MOUND
Definition at line 2245 of file hellfire_peninsula.cpp.
AledisActions
enum AledisActions
Enumerator
ALEDIS_LOW_HP
ALEDIS_ACTION_PYROBLAST
ALEDIS_ACTION_FROSTNOVA
ALEDIS_ACTION_FIREBALL
ALEDIS_ACTION_MAX
Definition at line 1122 of file hellfire_peninsula.cpp.
KrunActions
enum KrunActions : uint32
Enumerator
KRUN_ACTION_EXECUTE_SEDAI
KRUN_ACTION_LAUGH
KRUN_ACTION_DESPAWN
Definition at line 1925 of file hellfire_peninsula.cpp.
RazorthornActions
enum RazorthornActions
Enumerator
RAZORTHORN_REND
RAZORTHORN_RAVAGE
RAZORTHORN_ACTION_MAX
Definition at line 2342 of file hellfire_peninsula.cpp.
SedaiActions
enum SedaiActions : uint32
Enumerator
SEDAI_COMBAT_ACTION_HOLYFIRE
SEDAI_COMBAT_ACTION_HAMMER
SEDAI_COMBAT_ACTION_MAX
SEDAI_ACTION_FACE_ESCORT
SEDAI_ACTION_ESCORT_KICK
SEDAI_ACTION_ESCORT_SAY
SEDAI_ACTION_SEDAI_KNEEL
SEDAI_ACTION_ESCORTS_MOVE_1
SEDAI_ACTION_FELORC_SPAWN_ATTACK
SEDAI_ACTION_QUEST_COMPLETE
SEDAI_ACTION_SEDAI_MOVE_2
SEDAI_ACTION_SEDAI_START_ATTACK
Definition at line 1656 of file hellfire_peninsula.cpp.
Function Documentation
AddSC_hellfire_peninsula()
void AddSC_hellfire_peninsula ()
Definition at line 2398 of file hellfire_peninsula.cpp.
References EffectDummyCreature_npc_fel_guard_hound(), Script::GetAI, GetAI_danath_trollbane(), GetAI_go_smoke_beacon(), GetAI_nazgrel(), GetAI_npc_aeranas(), GetAI_npc_ancestral_wolf(), GetAI_npc_anchorite_barada(), GetAI_npc_colonel_jules(), GetAI_npc_credit_marker_they_must_burn(), GetAI_npc_demoniac_scryer(), GetAI_npc_fel_guard_hound(), GetAI_npc_krun(), GetAI_npc_laughing_skull(), GetAI_npc_maghar_escort(), GetAI_npc_vindicator_sedai(), GetAI_npc_wounded_blood_elf(), Script::GetGameObjectAI, GossipHello_npc_anchorite_barada(), GossipHello_npc_colonel_jules(), GossipHello_npc_demoniac_scryer(), GossipSelect_npc_anchorite_barada(), GossipSelect_npc_demoniac_scryer(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, ProcessEventId_sedai_vision(), QuestAccept_npc_wounded_blood_elf(), QuestComplete_npc_nazgrel(), QuestComplete_npc_trollbane(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_fel_guard_hound()
bool EffectDummyCreature_npc_fel_guard_hound (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 543 of file hellfire_peninsula.cpp.
References Creature::AI(), EFFECT_INDEX_0, Object::GetEntry(), NPC_DERANGED_HELBOAR, and SPELL_INFORM_DOG.
Referenced by AddSC_hellfire_peninsula().
GetAI_danath_trollbane()
UnitAI* GetAI_danath_trollbane (Creature * pCreature)
Definition at line 1535 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_go_smoke_beacon()
GameObjectAI* GetAI_go_smoke_beacon (GameObject * go)
Definition at line 2117 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_nazgrel()
UnitAI* GetAI_nazgrel (Creature * pCreature)
Definition at line 1621 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_aeranas()
UnitAI* GetAI_npc_aeranas (Creature * pCreature)
Definition at line 109 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_ancestral_wolf()
UnitAI* GetAI_npc_ancestral_wolf (Creature * pCreature)
Definition at line 174 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_anchorite_barada()
UnitAI* GetAI_npc_anchorite_barada (Creature * pCreature)
Definition at line 1042 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_colonel_jules()
UnitAI* GetAI_npc_colonel_jules (Creature * pCreature)
Definition at line 746 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_credit_marker_they_must_burn()
UnitAI* GetAI_npc_credit_marker_they_must_burn (Creature * pCreature)
Definition at line 2195 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_demoniac_scryer()
UnitAI* GetAI_npc_demoniac_scryer (Creature * pCreature)
Definition at line 319 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_fel_guard_hound()
UnitAI* GetAI_npc_fel_guard_hound (Creature * pCreature)
Definition at line 538 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_krun()
UnitAI* GetAI_npc_krun (Creature * creature)
Definition at line 1974 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_laughing_skull()
UnitAI* GetAI_npc_laughing_skull (Creature * creature)
Definition at line 2002 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_maghar_escort()
UnitAI* GetAI_npc_maghar_escort (Creature * creature)
Definition at line 2037 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_vindicator_sedai()
UnitAI* GetAI_npc_vindicator_sedai (Creature * creature)
Definition at line 1914 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GetAI_npc_wounded_blood_elf()
UnitAI* GetAI_npc_wounded_blood_elf (Creature * pCreature)
Definition at line 450 of file hellfire_peninsula.cpp.
Referenced by AddSC_hellfire_peninsula().
GossipHello_npc_anchorite_barada()
bool GossipHello_npc_anchorite_barada (Player * pPlayer, Creature * pCreature)
Definition at line 1047 of file hellfire_peninsula.cpp.
References Creature::AI(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_EXORCISM, GOSSIP_SENDER_MAIN, Player::IsCurrentQuest(), QUEST_ID_EXORCISM, and TEXT_ID_ANCHORITE.
Referenced by AddSC_hellfire_peninsula().
GossipHello_npc_colonel_jules()
bool GossipHello_npc_colonel_jules (Player * pPlayer, Creature * pCreature)
Definition at line 1070 of file hellfire_peninsula.cpp.
References Creature::AI(), GetClosestCreatureWithEntry(), Object::GetEntry(), Object::GetObjectGuid(), Player::GetQuestStatus(), Player::IsCurrentQuest(), NPC_ANCHORITE_BARADA, QUEST_ID_EXORCISM, QUEST_STATUS_COMPLETE, Player::RewardPlayerAndGroupAtEventCredit(), Object::SetFlag(), TEXT_ID_CLEANSED, TEXT_ID_POSSESSED, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_hellfire_peninsula().
GossipHello_npc_demoniac_scryer()
bool GossipHello_npc_demoniac_scryer (Player * pPlayer, Creature * pCreature)
Definition at line 324 of file hellfire_peninsula.cpp.
References Creature::AI(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ATTUNE, GOSSIP_SENDER_MAIN, GOSSIP_TEXTID_ATTUNED, GOSSIP_TEXTID_PROTECT, QUEST_DEMONIAC, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_hellfire_peninsula().
GossipSelect_npc_anchorite_barada()
bool GossipSelect_npc_anchorite_barada (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1059 of file hellfire_peninsula.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, GOSSIP_ACTION_INFO_DEF, and UnitAI::SendAIEvent().
Referenced by AddSC_hellfire_peninsula().
GossipSelect_npc_demoniac_scryer()
bool GossipSelect_npc_demoniac_scryer (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 342 of file hellfire_peninsula.cpp.
References Unit::CastSpell(), GOSSIP_ACTION_INFO_DEF, SPELL_DEMONIAC_VISITATION, and TRIGGERED_NONE.
Referenced by AddSC_hellfire_peninsula().
ProcessEventId_sedai_vision()
bool ProcessEventId_sedai_vision (uint32 , Object * source, Object * , bool)
Definition at line 2042 of file hellfire_peninsula.cpp.
References GetClosestCreatureWithEntry(), NPC_SEDAI, Creature::SetCorpseDelay(), WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OR_DEAD_DESPAWN.
Referenced by AddSC_hellfire_peninsula().
QuestAccept_npc_wounded_blood_elf()
bool QuestAccept_npc_wounded_blood_elf (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 455 of file hellfire_peninsula.cpp.
References Creature::AI(), FACTION_TROLL_FROSTMANE, Quest::GetQuestId(), QUEST_ROAD_TO_FALCON_WATCH, Object::RemoveFlag(), Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by AddSC_hellfire_peninsula().
QuestComplete_npc_nazgrel()
bool QuestComplete_npc_nazgrel (Player * player, Creature * creature, const Quest * quest)
Definition at line 1610 of file hellfire_peninsula.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, Quest::GetQuestId(), QUEST_FALL_OF_MAGETHERIDON_H, and UnitAI::SendAIEvent().
Referenced by AddSC_hellfire_peninsula().
QuestComplete_npc_trollbane()
bool QuestComplete_npc_trollbane (Player * player, Creature * creature, const Quest * quest)
Definition at line 1523 of file hellfire_peninsula.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, Quest::GetQuestId(), QUEST_FALL_OF_MAGETHERIDON_A, and UnitAI::SendAIEvent().
Referenced by AddSC_hellfire_peninsula().
Variable Documentation
aAnchoriteTexts
const int32 aAnchoriteTexts[7] = {BARADA_SAY_EXORCISM_RANDOM_1, BARADA_SAY_EXORCISM_RANDOM_2, BARADA_SAY_EXORCISM_RANDOM_3, BARADA_SAY_EXORCISM_RANDOM_4, BARADA_SAY_EXORCISM_RANDOM_5, BARADA_SAY_EXORCISM_RANDOM_6, BARADA_SAY_EXORCISM_RANDOM_7} static
Definition at line 787 of file hellfire_peninsula.cpp.
Referenced by npc_anchorite_baradaAI::JustDidDialogueStep().
aColonelTexts
const int32 aColonelTexts[5] = {JULES_SAY_EXORCISM_RANDOM_1, JULES_SAY_EXORCISM_RANDOM_2, JULES_SAY_EXORCISM_RANDOM_3, JULES_SAY_EXORCISM_RANDOM_4, JULES_SAY_EXORCISM_RANDOM_5} static
Definition at line 788 of file hellfire_peninsula.cpp.
Referenced by npc_anchorite_baradaAI::JustDidDialogueStep().
aExorcismDialogue
const DialogueEntry aExorcismDialogue[] static
Definition at line 751 of file hellfire_peninsula.cpp.