CMaNGOS_WoTLK: hinterlands.cpp File Reference
hinterlands.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "world_eastern_kingdoms.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_00x09hlAI
struct npc_rinjiAI
struct GammeritaTurtleCamera
Enumerations
enum {
SAY_OOX_START = -1000287 , SAY_OOX_AGGRO1 = -1000288 , SAY_OOX_AGGRO2 = -1000289 , SAY_OOX_AMBUSH = -1000290 ,
SAY_OOX_END = -1000292 , QUEST_RESQUE_OOX_09 = 836 , NPC_MARAUDING_OWL = 7808 , NPC_VILE_AMBUSHER = 7809
}
enum {
SAY_RIN_FREE = -1000403 , SAY_RIN_BY_OUTRUNNER = -1000404 , SAY_RIN_HELP_1 = -1000405 , SAY_RIN_HELP_2 = -1000406 ,
SAY_RIN_COMPLETE = -1000407 , SAY_RIN_PROGRESS_1 = -1000408 , SAY_RIN_PROGRESS_2 = -1000409 , QUEST_RINJI_TRAPPED = 2742 ,
NPC_RANGER = 2694 , NPC_OUTRUNNER = 2691 , GO_RINJI_CAGE = 142036
}
enum { YELL_FALSTAD_INVADERS = -27 }
Functions
bool QuestAccept_npc_00x09hl (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_00x09hl (Creature *pCreature)
bool QuestAccept_npc_rinji (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_rinji (Creature *pCreature)
bool ProcessEventId_WildhammerMessage (uint32, Object *source, Object *, bool)
void AddSC_hinterlands ()
Variables
Position m_afAmbushSpawn []
Position m_afAmbushMoveTo []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_OOX_START
SAY_OOX_AGGRO1
SAY_OOX_AGGRO2
SAY_OOX_AMBUSH
SAY_OOX_END
QUEST_RESQUE_OOX_09
NPC_MARAUDING_OWL
NPC_VILE_AMBUSHER
Definition at line 39 of file hinterlands.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_RIN_FREE
SAY_RIN_BY_OUTRUNNER
SAY_RIN_HELP_1
SAY_RIN_HELP_2
SAY_RIN_COMPLETE
SAY_RIN_PROGRESS_1
SAY_RIN_PROGRESS_2
QUEST_RINJI_TRAPPED
NPC_RANGER
NPC_OUTRUNNER
GO_RINJI_CAGE
Definition at line 170 of file hinterlands.cpp.
anonymous enum
anonymous enum
Enumerator
YELL_FALSTAD_INVADERS
Definition at line 356 of file hinterlands.cpp.
Function Documentation
AddSC_hinterlands()
void AddSC_hinterlands ()
Definition at line 391 of file hinterlands.cpp.
References Script::GetAI, GetAI_npc_00x09hl(), GetAI_npc_rinji(), Script::Name, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_WildhammerMessage(), QuestAccept_npc_00x09hl(), QuestAccept_npc_rinji(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_00x09hl()
UnitAI* GetAI_npc_00x09hl (Creature * pCreature)
Definition at line 161 of file hinterlands.cpp.
Referenced by AddSC_hinterlands().
GetAI_npc_rinji()
UnitAI* GetAI_npc_rinji (Creature * pCreature)
Definition at line 351 of file hinterlands.cpp.
Referenced by AddSC_hinterlands().
ProcessEventId_WildhammerMessage()
bool ProcessEventId_WildhammerMessage (uint32 , Object * source, Object * , bool)
Definition at line 361 of file hinterlands.cpp.
References AURA_INTERRUPT_FLAG_PVP_ACTIVE_CANCELS, DoScriptText(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Object::IsPlayer(), NPC_FALSTAD_WILDHAMMER, Unit::RemoveAurasWithInterruptFlags(), Player::UpdatePvP(), and YELL_FALSTAD_INVADERS.
Referenced by AddSC_hinterlands().
QuestAccept_npc_00x09hl()
bool QuestAccept_npc_00x09hl (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 146 of file hinterlands.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, Quest::GetQuestId(), QUEST_RESQUE_OOX_09, SAY_OOX_START, WorldObject::SetActiveObjectState(), Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_hinterlands().
QuestAccept_npc_rinji()
bool QuestAccept_npc_rinji (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 336 of file hinterlands.cpp.
References Creature::AI(), GetClosestGameObjectWithEntry(), Quest::GetQuestId(), GO_RINJI_CAGE, INTERACTION_DISTANCE, QUEST_RINJI_TRAPPED, Object::RemoveFlag(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by AddSC_hinterlands().
Variable Documentation
m_afAmbushMoveTo
Position m_afAmbushMoveTo[]
Initial value:
=
{
    {166.63038f, -2824.780273f, 108.153f, 0.f},
    {70.886589f, -2874.335449f, 116.675f, 0.f}
}
Definition at line 192 of file hinterlands.cpp.
Referenced by npc_rinjiAI::JustSummoned().
m_afAmbushSpawn
Position m_afAmbushSpawn[]
Initial value:
=
{
    {191.29620f, -2839.329346f, 107.388f, 0.f},
    {70.972466f, -2848.674805f, 109.459f, 0.f}
}
Definition at line 186 of file hinterlands.cpp.
Referenced by npc_rinjiAI::DoSpawnAmbush().