CMaNGOS_WoTLK: howling_fjord.cpp File Reference
howling_fjord.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_ancient_male_vrykulAI
struct npc_silvermoon_harryAI
struct npc_lich_king_villageAI
struct npc_king_ymironAI
struct npc_firecrackers_bunnyAI
struct npc_apothecary_hanesAI
struct FlyingMachineControls
struct GrapplingHook
struct GrapplingBeam
struct BurnBody
struct UseBricksBonesaw
Enumerations
enum {
SPELL_ECHO_OF_YMIRON = 42786 , SPELL_SECRET_OF_WYRMSKULL = 43458 , QUEST_ECHO_OF_YMIRON = 11343 , NPC_MALE_VRYKUL = 24314 ,
NPC_FEMALE_VRYKUL = 24315 , SAY_VRYKUL_CURSED = -1000635 , EMOTE_VRYKUL_POINT = -1000636 , EMOTE_VRYKUL_SOB = -1000637 ,
SAY_VRYKUL_DISPOSE = -1000638 , SAY_VRYKUL_BEG = -1000639 , SAY_VRYKUL_WHAT = -1000640 , SAY_VRYKUL_HIDE = -1000641
}
enum {
QUEST_GAMBLING_DEBT = 11464 , SAY_AGGRO = -1000603 , SAY_BEATEN = -1000604 , GOSSIP_ITEM_GAMBLING_DEBT = -3000101 ,
GOSSIP_ITEM_PAYING = -3000102 , SPELL_BLAST_WAVE = 15091 , SPELL_SCORCH = 50183 , ITEM_HARRY_DEBT = 34115 ,
FACTION_HOSTILE_SH = 90
}
enum {
EMOTE_LICH_KING_FACE = -1000920 , SAY_LICH_KING_1 = -1000921 , SAY_PREPARE = -1000922 , SAY_LICH_KING_2 = -1000923 ,
SAY_LICH_KING_3 = -1000924 , SAY_LICH_KING_4 = -1000925 , SAY_LICH_KING_5 = -1000926 , SAY_PERSISTANCE = -1000927 ,
SPELL_GRASP_OF_THE_LICH_KING = 43489 , SPELL_MAGNETIC_PULL = 29661 , SPELL_WRATH_LICH_KING_FIRST = 43488 , SPELL_WRATH_LICH_KING = 50156 ,
NPC_VALKYR_SOULCLAIMER = 24327 , NPC_LICH_KING_WYRMSKULL = 24248 , QUEST_ID_LK_FLAG = 12485
}
enum {
EMOTE_KING_SILENCE = -1000928 , SAY_KING_YMIRON_SPEECH_1 = -1000929 , SAY_KING_YMIRON_SPEECH_2 = -1000930 , EMOTE_YMIRON_CROWD_1 = -1000931 ,
SAY_KING_YMIRON_SPEECH_3 = -1000932 , SAY_KING_YMIRON_SPEECH_4 = -1000933 , SAY_KING_YMIRON_SPEECH_5 = -1000934 , SAY_KING_YMIRON_SPEECH_6 = -1000935 ,
SAY_KING_YMIRON_SPEECH_7 = -1000936 , EMOTE_YMIRON_CROWD_2 = -1000937 , SAY_KING_YMIRON_SPEECH_8 = -1000938 , EMOTE_YMIRON_CROWD_3 = -1000939 ,
SAY_KING_YMIRON_SPEECH_9 = -1000940 , SPELL_ECHO_OF_YMIRON_NIFFLEVAR = 43466 , SPELL_SECRETS_OF_NIFFLEVAR = 43468 , NPC_CITIZEN_OF_NIFFLEVAR_MALE = 24322 ,
NPC_CITIZEN_OF_NIFFLEVAR_FEMALE = 24323 , NPC_KING_YMIRON = 24321 , QUEST_ID_ANGUISH_OF_NIFFLEVAR = 11344 , MAX_CROWD_TEXT_ENTRIES = 7
}
enum { SPELL_FIRECRACKER_VISUAL = 43314 , SPELL_SUMMON_DARKCLAW_GUANO = 43307 , NPC_DARKCLAW_BAT = 23959 }
enum {
SAY_HANES_ESCORT_START = -1001064 , SAY_HANES_FIRE_1 = -1001065 , SAY_HANES_FIRE_2 = -1001066 , SAY_HANES_SUPPLIES_1 = -1001067 ,
SAY_HANES_SUPPLIES_2 = -1001068 , SAY_HANES_SUPPLIES_ESCAPE = -1001069 , SAY_HANES_SUPPLIES_COMPLETE = -1001070 , SAY_HANES_ARRIVE_BASE = -1001071 ,
SPELL_HEALING_POTION = 17534 , SPELL_LOW_POLY_FIRE = 51195 , NPC_HANES_TRIGGER = 23968 , QUEST_ID_TRIAL_OF_FIRE = 11241
}
enum { ITEM_ID_SCALAWAG_FROG = 35803 , NPC_SCALAWAG_FROG = 26503 }
enum { SPELL_GRAPPLING_BEAM = 43789 }
Functions
UnitAI * GetAI_npc_ancient_male_vrykul (Creature *pCreature)
bool AreaTrigger_at_ancient_male_vrykul (Player *pPlayer, AreaTriggerEntry const *)
UnitAI * GetAI_npc_silvermoon_harry (Creature *pCreature)
bool GossipHello_npc_silvermoon_harry (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_silvermoon_harry (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_lich_king_village (Creature *pCreature)
UnitAI * GetAI_npc_king_ymiron (Creature *pCreature)
bool AreaTrigger_at_nifflevar (Player *pPlayer, AreaTriggerEntry const *pAt)
UnitAI * GetAI_npc_firecrackers_bunny (Creature *pCreature)
UnitAI * GetAI_npc_apothecary_hanes (Creature *pCreature)
bool QuestAccept_npc_apothecary_hanes (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool NpcSpellClick_npc_scalawag_frog (Player *pPlayer, Creature *pClickedCreature, uint32)
void AddSC_howling_fjord ()
Variables
static const DialogueEntry aLichDialogue []
static const DialogueEntry aNifflevarDialogue []
static const int32 aRandomTextEntries [MAX_CROWD_TEXT_ENTRIES] = { -1000941, -1000942, -1000943, -1000944, -1000945, -1000946, -1000947}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_ECHO_OF_YMIRON
SPELL_SECRET_OF_WYRMSKULL
QUEST_ECHO_OF_YMIRON
NPC_MALE_VRYKUL
NPC_FEMALE_VRYKUL
SAY_VRYKUL_CURSED
EMOTE_VRYKUL_POINT
EMOTE_VRYKUL_SOB
SAY_VRYKUL_DISPOSE
SAY_VRYKUL_BEG
SAY_VRYKUL_WHAT
SAY_VRYKUL_HIDE
Definition at line 41 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_GAMBLING_DEBT
SAY_AGGRO
SAY_BEATEN
GOSSIP_ITEM_GAMBLING_DEBT
GOSSIP_ITEM_PAYING
SPELL_BLAST_WAVE
SPELL_SCORCH
ITEM_HARRY_DEBT
FACTION_HOSTILE_SH
Definition at line 154 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_LICH_KING_FACE
SAY_LICH_KING_1
SAY_PREPARE
SAY_LICH_KING_2
SAY_LICH_KING_3
SAY_LICH_KING_4
SAY_LICH_KING_5
SAY_PERSISTANCE
SPELL_GRASP_OF_THE_LICH_KING
SPELL_MAGNETIC_PULL
SPELL_WRATH_LICH_KING_FIRST
SPELL_WRATH_LICH_KING
NPC_VALKYR_SOULCLAIMER
NPC_LICH_KING_WYRMSKULL
QUEST_ID_LK_FLAG
Definition at line 315 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_KING_SILENCE
SAY_KING_YMIRON_SPEECH_1
SAY_KING_YMIRON_SPEECH_2
EMOTE_YMIRON_CROWD_1
SAY_KING_YMIRON_SPEECH_3
SAY_KING_YMIRON_SPEECH_4
SAY_KING_YMIRON_SPEECH_5
SAY_KING_YMIRON_SPEECH_6
SAY_KING_YMIRON_SPEECH_7
EMOTE_YMIRON_CROWD_2
SAY_KING_YMIRON_SPEECH_8
EMOTE_YMIRON_CROWD_3
SAY_KING_YMIRON_SPEECH_9
SPELL_ECHO_OF_YMIRON_NIFFLEVAR
SPELL_SECRETS_OF_NIFFLEVAR
NPC_CITIZEN_OF_NIFFLEVAR_MALE
NPC_CITIZEN_OF_NIFFLEVAR_FEMALE
NPC_KING_YMIRON
QUEST_ID_ANGUISH_OF_NIFFLEVAR
MAX_CROWD_TEXT_ENTRIES
Definition at line 438 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FIRECRACKER_VISUAL
SPELL_SUMMON_DARKCLAW_GUANO
NPC_DARKCLAW_BAT
Definition at line 622 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_HANES_ESCORT_START
SAY_HANES_FIRE_1
SAY_HANES_FIRE_2
SAY_HANES_SUPPLIES_1
SAY_HANES_SUPPLIES_2
SAY_HANES_SUPPLIES_ESCAPE
SAY_HANES_SUPPLIES_COMPLETE
SAY_HANES_ARRIVE_BASE
SPELL_HEALING_POTION
SPELL_LOW_POLY_FIRE
NPC_HANES_TRIGGER
QUEST_ID_TRIAL_OF_FIRE
Definition at line 722 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
ITEM_ID_SCALAWAG_FROG
NPC_SCALAWAG_FROG
Definition at line 857 of file howling_fjord.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GRAPPLING_BEAM
Definition at line 899 of file howling_fjord.cpp.
Function Documentation
AddSC_howling_fjord()
void AddSC_howling_fjord ()
Definition at line 977 of file howling_fjord.cpp.
References AreaTrigger_at_ancient_male_vrykul(), AreaTrigger_at_nifflevar(), Script::GetAI, GetAI_npc_ancient_male_vrykul(), GetAI_npc_apothecary_hanes(), GetAI_npc_firecrackers_bunny(), GetAI_npc_king_ymiron(), GetAI_npc_lich_king_village(), GetAI_npc_silvermoon_harry(), GossipHello_npc_silvermoon_harry(), GossipSelect_npc_silvermoon_harry(), Script::Name, NpcSpellClick_npc_scalawag_frog(), Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pNpcSpellClick, Script::pQuestAcceptNPC, QuestAccept_npc_apothecary_hanes(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_ancient_male_vrykul()
bool AreaTrigger_at_ancient_male_vrykul (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 135 of file howling_fjord.cpp.
References GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::HasAura(), Unit::IsAlive(), NPC_MALE_VRYKUL, QUEST_ECHO_OF_YMIRON, QUEST_STATUS_INCOMPLETE, and SPELL_ECHO_OF_YMIRON.
Referenced by AddSC_howling_fjord().
AreaTrigger_at_nifflevar()
bool AreaTrigger_at_nifflevar (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 605 of file howling_fjord.cpp.
References AI_EVENT_CUSTOM_A, GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::HasAura(), Unit::IsAlive(), NPC_KING_YMIRON, QUEST_ID_ANGUISH_OF_NIFFLEVAR, QUEST_STATUS_INCOMPLETE, and SPELL_ECHO_OF_YMIRON_NIFFLEVAR.
Referenced by AddSC_howling_fjord().
GetAI_npc_ancient_male_vrykul()
UnitAI* GetAI_npc_ancient_male_vrykul (Creature * pCreature)
Definition at line 130 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GetAI_npc_apothecary_hanes()
UnitAI* GetAI_npc_apothecary_hanes (Creature * pCreature)
Definition at line 837 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GetAI_npc_firecrackers_bunny()
UnitAI* GetAI_npc_firecrackers_bunny (Creature * pCreature)
Definition at line 713 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GetAI_npc_king_ymiron()
UnitAI* GetAI_npc_king_ymiron (Creature * pCreature)
Definition at line 600 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GetAI_npc_lich_king_village()
UnitAI* GetAI_npc_lich_king_village (Creature * pCreature)
Definition at line 429 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GetAI_npc_silvermoon_harry()
UnitAI* GetAI_npc_silvermoon_harry (Creature * pCreature)
Definition at line 252 of file howling_fjord.cpp.
Referenced by AddSC_howling_fjord().
GossipHello_npc_silvermoon_harry()
bool GossipHello_npc_silvermoon_harry (Player * pPlayer, Creature * pCreature)
Definition at line 257 of file howling_fjord.cpp.
References Creature::AI(), Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ICON_CHAT, GOSSIP_ICON_VENDOR, GOSSIP_ITEM_GAMBLING_DEBT, GOSSIP_ITEM_PAYING, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_BROWSE_GOODS, Unit::isQuestGiver(), Unit::isVendor(), Player::PrepareQuestMenu(), QUEST_GAMBLING_DEBT, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_howling_fjord().
GossipSelect_npc_silvermoon_harry()
bool GossipSelect_npc_silvermoon_harry (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 281 of file howling_fjord.cpp.
References Creature::AI(), UnitAI::AttackStart(), DoScriptText(), UnitAI::EnterEvadeMode(), FACTION_HOSTILE_SH, Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, Player::HasItemCount(), ITEM_HARRY_DEBT, SAY_AGGRO, Player::SendNewItem(), Creature::SetFactionTemporary(), Player::StoreNewItemInInventorySlot(), TEMPFACTION_RESTORE_COMBAT_STOP, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_howling_fjord().
NpcSpellClick_npc_scalawag_frog()
bool NpcSpellClick_npc_scalawag_frog (Player * pPlayer, Creature * pClickedCreature, uint32)
Definition at line 863 of file howling_fjord.cpp.
References Creature::ForcedDespawn(), Object::GetEntry(), ITEM_ID_SCALAWAG_FROG, NPC_SCALAWAG_FROG, Player::SendNewItem(), and Player::StoreNewItemInInventorySlot().
Referenced by AddSC_howling_fjord().
QuestAccept_npc_apothecary_hanes()
bool QuestAccept_npc_apothecary_hanes (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 842 of file howling_fjord.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_TRIAL_OF_FIRE, and UnitAI::SendAIEvent().
Referenced by AddSC_howling_fjord().
Variable Documentation
aLichDialogue
const DialogueEntry aLichDialogue[] static
Initial value:
=
{
    {EMOTE_LICH_KING_FACE,          NPC_LICH_KING_WYRMSKULL, 4000},
    {QUEST_ID_LK_FLAG,              0,                       3000},
    {SAY_LICH_KING_1,               NPC_LICH_KING_WYRMSKULL, 20000},
    {NPC_VALKYR_SOULCLAIMER,        0,                       4000},
    {SAY_LICH_KING_2,               NPC_LICH_KING_WYRMSKULL, 10000},
    {SAY_LICH_KING_3,               NPC_LICH_KING_WYRMSKULL, 25000},
    {SAY_LICH_KING_4,               NPC_LICH_KING_WYRMSKULL, 25000},
    {SAY_LICH_KING_5,               NPC_LICH_KING_WYRMSKULL, 20000},
    {SPELL_WRATH_LICH_KING_FIRST,   0,                       10000},
    {NPC_LICH_KING_WYRMSKULL,       0,                       0},
    {SAY_PERSISTANCE,               NPC_LICH_KING_WYRMSKULL, 15000},
    {SPELL_WRATH_LICH_KING,         0,                       10000},
    {NPC_LICH_KING_WYRMSKULL,       0,                       0},
    {0, 0, 0},
}
Definition at line 337 of file howling_fjord.cpp.
aNifflevarDialogue
const DialogueEntry aNifflevarDialogue[] static
Initial value:
=
{
    {EMOTE_KING_SILENCE,            NPC_KING_YMIRON,    3000},
    {SAY_KING_YMIRON_SPEECH_1,      NPC_KING_YMIRON,    5000},
    {SAY_KING_YMIRON_SPEECH_2,      NPC_KING_YMIRON,    2000},
    {EMOTE_YMIRON_CROWD_1,          NPC_KING_YMIRON,    5000},
    {SAY_KING_YMIRON_SPEECH_3,      NPC_KING_YMIRON,    10000},
    {SAY_KING_YMIRON_SPEECH_4,      NPC_KING_YMIRON,    9000},
    {SAY_KING_YMIRON_SPEECH_5,      NPC_KING_YMIRON,    7000},
    {SAY_KING_YMIRON_SPEECH_6,      NPC_KING_YMIRON,    5000},
    {SAY_KING_YMIRON_SPEECH_7,      NPC_KING_YMIRON,    9000},
    {EMOTE_YMIRON_CROWD_2,          NPC_KING_YMIRON,    5000},
    {SAY_KING_YMIRON_SPEECH_8,      NPC_KING_YMIRON,    8000},
    {EMOTE_YMIRON_CROWD_3,          NPC_KING_YMIRON,    4000},
    {SAY_KING_YMIRON_SPEECH_9,      NPC_KING_YMIRON,    10000},
    {SPELL_SECRETS_OF_NIFFLEVAR,    0,                  10000},
    {QUEST_ID_ANGUISH_OF_NIFFLEVAR, 0,                  0},
    {0, 0, 0},
}
Definition at line 466 of file howling_fjord.cpp.
aRandomTextEntries
const int32 aRandomTextEntries[MAX_CROWD_TEXT_ENTRIES] = { -1000941, -1000942, -1000943, -1000944, -1000945, -1000946, -1000947} static
Definition at line 486 of file howling_fjord.cpp.
Referenced by npc_king_ymironAI::UpdateAI().