CMaNGOS_WoTLK: hyjal.cpp File Reference
hyjal.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "hyjal.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct EternalSilence
Functions
std::array< HyjalWave, MAX_WAVES > InitHyjalWaves ()
std::array< InvasionWave, MAX_INVASION_WAVES > InitInvasionWaves ()
uint32 GetInfernalsPerWave (uint32 index)
uint8 GetRandomWavePath (WavePaths path)
uint32 GetRunningPerWaveMobEntry (uint32 entry, uint32 waveIndex)
void AddSC_instance_mount_hyjal ()
Variables
static const float aArchimondeSpawnLoc [4] = { 5601.938f, -3446.284f, 1577.485f, 3.700098f }
Function Documentation
AddSC_instance_mount_hyjal()
void AddSC_instance_mount_hyjal ()
Definition at line 1883 of file hyjal.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInfernalsPerWave()
uint32 GetInfernalsPerWave (uint32 index)
Definition at line 773 of file hyjal.cpp.
Referenced by instance_mount_hyjal::SpawnWave(), and instance_mount_hyjal::SpawnWaveInfernals().
GetRandomWavePath()
uint8 GetRandomWavePath (WavePaths path)
Definition at line 784 of file hyjal.cpp.
References ALLY_GROUND, HORDE_FROST_WYRM_1, HORDE_FROST_WYRM_2, HORDE_GARGOYLE_1, HORDE_GARGOYLE_2, HORDE_GROUND, NELF_GROUND, PATH_NONE, and urand().
Referenced by instance_mount_hyjal::SpawnInvasionWave(), and instance_mount_hyjal::SpawnWave().
GetRunningPerWaveMobEntry()
uint32 GetRunningPerWaveMobEntry (uint32 entry, uint32 waveIndex)
Definition at line 808 of file hyjal.cpp.
References NPC_AZGALOR, NPC_FROST, and NPC_KAZROGAL.
Referenced by instance_mount_hyjal::SpawnWave().
InitHyjalWaves()
std::array<HyjalWave, MAX_WAVES> InitHyjalWaves ()
Definition at line 44 of file hyjal.cpp.
References ALLY_GROUND, HORDE_FROST_WYRM_1, HORDE_FROST_WYRM_2, HORDE_GARGOYLE_1, HORDE_GARGOYLE_2, HORDE_GROUND, NPC_ABOMI, NPC_ANETHERON, NPC_AZGALOR, NPC_BANSH, NPC_CRYPT, NPC_FROST, NPC_GARGO, NPC_GHOUL, NPC_KAZROGAL, NPC_NECRO, NPC_STALK, and NPC_WINTERCHILL.
InitInvasionWaves()
std::array<InvasionWave, MAX_INVASION_WAVES> InitInvasionWaves ()
Definition at line 555 of file hyjal.cpp.
References ALLY_GROUND, HORDE_GROUND, NELF_GROUND, NPC_ABOMI, NPC_BUILDING_TRIGGER, NPC_CRYPT, NPC_GARGO, NPC_GHOUL, NPC_INFERNAL_TARGET, and PATH_NONE.
Variable Documentation
aArchimondeSpawnLoc
const float aArchimondeSpawnLoc[4] = { 5601.938f, -3446.284f, 1577.485f, 3.700098f } static
Definition at line 42 of file hyjal.cpp.
Referenced by instance_mount_hyjal::SpawnArchimonde().