CMaNGOS_WoTLK: hyjalScripts.cpp File Reference
hyjalScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "hyjalAI.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_jaina_proudmooreAI
struct npc_thrallAI
struct npc_building_triggerAI
struct npc_tyrande_whisperwindAI
struct RaiseDeadHyjal
Enumerations
enum JainaActions {
JAINA_20 = HYJAL_AI_ACTION_MAX , JAINA_BLIZZARD , JAINA_PYROBLAST , JAINA_SUMMON_ELEMENTALS ,
JAINA_ACTION_MAX
}
enum ThrallActions { THRALL_FERAL_SPIRITS = HYJAL_AI_ACTION_MAX , THRALL_CHAIN_LIGHTNING , THRALL_ACTION_MAX }
enum TyrandeActions { TYRANDE_STARFALL = HYJAL_AI_ACTION_MAX , TYRANDE_TRUESHOT_AURA , TYRANDE_ACTION_MAX }
Functions
bool GossipSelect_npc_jaina_proudmoore (Player *player, Creature *creature, uint32, uint32 action)
bool GossipSelect_npc_thrall (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_hyjal ()
Enumeration Type Documentation
JainaActions
enum JainaActions
Enumerator
JAINA_20
JAINA_BLIZZARD
JAINA_PYROBLAST
JAINA_SUMMON_ELEMENTALS
JAINA_ACTION_MAX
Definition at line 35 of file hyjalScripts.cpp.
ThrallActions
enum ThrallActions
Enumerator
THRALL_FERAL_SPIRITS
THRALL_CHAIN_LIGHTNING
THRALL_ACTION_MAX
Definition at line 127 of file hyjalScripts.cpp.
TyrandeActions
enum TyrandeActions
Enumerator
TYRANDE_STARFALL
TYRANDE_TRUESHOT_AURA
TYRANDE_ACTION_MAX
Definition at line 268 of file hyjalScripts.cpp.
Function Documentation
AddSC_hyjal()
void AddSC_hyjal ()
Definition at line 315 of file hyjalScripts.cpp.
References Script::GetAI, GossipSelect_npc_jaina_proudmoore(), GossipSelect_npc_thrall(), Script::Name, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipSelect_npc_jaina_proudmoore()
bool GossipSelect_npc_jaina_proudmoore (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 86 of file hyjalScripts.cpp.
References Creature::AI(), DONE, WorldObject::GetInstanceData(), JAINA_FIRST_BOSS, JAINA_SECOND_BOSS, JAINA_WIN, Player::PrepareGossipMenu(), Object::RemoveFlag(), Player::SendPreparedGossip(), WorldObject::SetActiveObjectState(), TYPE_AZGALOR, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_hyjal().
GossipSelect_npc_thrall()
bool GossipSelect_npc_thrall (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 184 of file hyjalScripts.cpp.
References Creature::AI(), WorldObject::GetInstanceData(), Player::PrepareGossipMenu(), Object::RemoveFlag(), Player::SendPreparedGossip(), WorldObject::SetActiveObjectState(), THRALL_FIRST_BOSS, THRALL_SECOND_BOSS, THRALL_WIN, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_hyjal().