CMaNGOS_WoTLK: icecrown_citadel.cpp File Reference
icecrown_citadel.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
#include "Entities/Transports.h"
Enumerations
enum {
SAY_MARROWGAR_INTRO = -1631001 , SAY_DEATHWHISPER_SPEECH_1 = -1631011 , SAY_DEATHWHISPER_SPEECH_2 = -1631012 , SAY_DEATHWHISPER_SPEECH_3 = -1631013 ,
SAY_DEATHWHISPER_SPEECH_4 = -1631014 , SAY_DEATHWHISPER_SPEECH_5 = -1631015 , SAY_DEATHWHISPER_SPEECH_6 = -1631016 , SAY_DEATHWHISPER_SPEECH_7 = -1631017 ,
MUSIC_ID_GUNSHIP = 17289 , SAY_GUNSHIP_START_ALLY_1 = -1631035 , SAY_GUNSHIP_START_ALLY_2 = -1631036 , SAY_GUNSHIP_START_ALLY_3 = -1631037 ,
SAY_GUNSHIP_START_ALLY_4 = -1631038 , SAY_GUNSHIP_START_ALLY_5 = -1631039 , SAY_GUNSHIP_START_ALLY_6 = -1631040 , SAY_GUNSHIP_START_ALLY_7 = -1631041 ,
SAY_GUNSHIP_START_ALLY_8 = -1631042 , SAY_GUNSHIP_HORDE_SOLDIERS = -1631043 , SAY_GUNSHIP_HORDE_MAGE = -1631044 , SAY_GUNSHIP_HORDE_ATTACK_1 = -1631045 ,
SAY_GUNSHIP_HORDE_ATTACK_2 = -1631046 , SAY_GUNSHIP_ALLY_WIN = -1631047 , SAY_GUNSHIP_START_HORDE_1 = -1631048 , SAY_GUNSHIP_START_HORDE_2 = -1631049 ,
SAY_GUNSHIP_START_HORDE_3 = -1631050 , SAY_GUNSHIP_START_HORDE_4 = -1631051 , SAY_GUNSHIP_START_HORDE_5 = -1631052 , SAY_GUNSHIP_START_HORDE_6 = -1631053 ,
SAY_GUNSHIP_START_HORDE_7 = -1631054 , SAY_GUNSHIP_ALLY_SOLDIERS = -1631055 , SAY_GUNSHIP_ALLY_MAGE = -1631056 , SAY_GUNSHIP_ALLY_ATTACK_1 = -1631057 ,
SAY_GUNSHIP_ALLY_ATTACK_2 = -1631058 , SAY_GUNSHIP_HORDE_WIN = -1631059 , SAY_MURADIN_AGGRO = -1631060 , SAY_SAURFANG_AGGRO = -1631061 ,
SAY_STINKY_DIES = -1631081 , SAY_PRECIOUS_DIES = -1631070 , SPELL_AWARD_REPUTATION = 73845 , SPELL_GUNSHIP_ACHIEVEMENT = 72959 ,
SPELL_TELEPORT_PLAYERS_VICTORY = 72340 , SPELL_CHECK_FOR_PLAYERS = 70332
}
Functions
InstanceData * GetInstanceData_instance_icecrown_citadel (Map *pMap)
bool AreaTrigger_at_icecrown_citadel (Player *pPlayer, AreaTriggerEntry const *pAt)
bool ProcessEventId_event_gameobject_citadel_valve (uint32, Object *pSource, Object *, bool bIsStart)
void AddSC_instance_icecrown_citadel ()
Variables
static const DialogueEntry aCitadelDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_MARROWGAR_INTRO
SAY_DEATHWHISPER_SPEECH_1
SAY_DEATHWHISPER_SPEECH_2
SAY_DEATHWHISPER_SPEECH_3
SAY_DEATHWHISPER_SPEECH_4
SAY_DEATHWHISPER_SPEECH_5
SAY_DEATHWHISPER_SPEECH_6
SAY_DEATHWHISPER_SPEECH_7
MUSIC_ID_GUNSHIP
SAY_GUNSHIP_START_ALLY_1
SAY_GUNSHIP_START_ALLY_2
SAY_GUNSHIP_START_ALLY_3
SAY_GUNSHIP_START_ALLY_4
SAY_GUNSHIP_START_ALLY_5
SAY_GUNSHIP_START_ALLY_6
SAY_GUNSHIP_START_ALLY_7
SAY_GUNSHIP_START_ALLY_8
SAY_GUNSHIP_HORDE_SOLDIERS
SAY_GUNSHIP_HORDE_MAGE
SAY_GUNSHIP_HORDE_ATTACK_1
SAY_GUNSHIP_HORDE_ATTACK_2
SAY_GUNSHIP_ALLY_WIN
SAY_GUNSHIP_START_HORDE_1
SAY_GUNSHIP_START_HORDE_2
SAY_GUNSHIP_START_HORDE_3
SAY_GUNSHIP_START_HORDE_4
SAY_GUNSHIP_START_HORDE_5
SAY_GUNSHIP_START_HORDE_6
SAY_GUNSHIP_START_HORDE_7
SAY_GUNSHIP_ALLY_SOLDIERS
SAY_GUNSHIP_ALLY_MAGE
SAY_GUNSHIP_ALLY_ATTACK_1
SAY_GUNSHIP_ALLY_ATTACK_2
SAY_GUNSHIP_HORDE_WIN
SAY_MURADIN_AGGRO
SAY_SAURFANG_AGGRO
SAY_STINKY_DIES
SAY_PRECIOUS_DIES
SPELL_AWARD_REPUTATION
SPELL_GUNSHIP_ACHIEVEMENT
SPELL_TELEPORT_PLAYERS_VICTORY
SPELL_CHECK_FOR_PLAYERS
Definition at line 28 of file icecrown_citadel.cpp.
Function Documentation
AddSC_instance_icecrown_citadel()
void AddSC_instance_icecrown_citadel ()
Definition at line 1196 of file icecrown_citadel.cpp.
References AreaTrigger_at_icecrown_citadel(), Script::GetInstanceData, GetInstanceData_instance_icecrown_citadel(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_gameobject_citadel_valve(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_icecrown_citadel()
bool AreaTrigger_at_icecrown_citadel (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 1165 of file icecrown_citadel.cpp.
References AT_DEATHWHISPER_INTRO, AT_MARROWGAR_INTRO, AT_SINDRAGOSA_PLATFORM, WorldObject::GetInstanceData(), AreaTriggerEntry::id, Unit::IsDead(), and Player::IsGameMaster().
Referenced by AddSC_instance_icecrown_citadel().
GetInstanceData_instance_icecrown_citadel()
InstanceData* GetInstanceData_instance_icecrown_citadel (Map * pMap)
Definition at line 1160 of file icecrown_citadel.cpp.
Referenced by AddSC_instance_icecrown_citadel().
ProcessEventId_event_gameobject_citadel_valve()
bool ProcessEventId_event_gameobject_citadel_valve (uint32 , Object * pSource, Object * , bool bIsStart)
Definition at line 1180 of file icecrown_citadel.cpp.
References DONE, Object::GetTypeId(), TYPE_FESTERGUT, TYPE_ROTFACE, and TYPEID_PLAYER.
Referenced by AddSC_instance_icecrown_citadel().
Variable Documentation
aCitadelDialogue
const DialogueEntry aCitadelDialogue[] static
Definition at line 87 of file icecrown_citadel.cpp.