CMaNGOS_WoTLK: icecrown.cpp File Reference
icecrown.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_squad_leaderAI
struct npc_infantryAI
struct npc_father_kamarosAI
struct npc_grand_admiral_westwindAI
struct SpellCreateLanceData
struct spell_create_lance
Enumerations
enum {
SAY_HORDE_SQUAD_RUN = -1001018 , SAY_ALLIANCE_SQUAD_RUN = -1001019 , SAY_SQUAD_AGGRO_1 = -1001020 , SAY_SQUAD_AGGRO_2 = -1001021 ,
SAY_HORDE_SQUAD_AGGRO_1 = -1001022 , SAY_HORDE_SQUAD_AGGRO_2 = -1001023 , SAY_HORDE_SQUAD_AGGRO_3 = -1001024 , SAY_HORDE_SQUAD_AGGRO_4 = -1001025 ,
SAY_ALLIANCE_SQUAD_AGGRO_1 = -1001026 , SAY_ALLIANCE_SQUAD_AGGRO_2 = -1001027 , SAY_ALLIANCE_SQUAD_AGGRO_3 = -1001028 , SAY_ALLIANCE_SQUAD_AGGRO_4 = -1001029 ,
SAY_HORDE_SQUAD_BREAK = -1001030 , SAY_HORDE_SQUAD_BREAK_DONE = -1001031 , SAY_ALLIANCE_SQUAD_BREAK = -1001032 , SAY_ALLIANCE_SQUAD_BREAK_DONE = -1001033 ,
SAY_EVENT_COMPLETE = -1001034 , SAY_DEFENDER_AGGRO_1 = -1001035 , SAY_DEFENDER_AGGRO_2 = -1001036 , SAY_DEFENDER_AGGRO_3 = -1001037 ,
SAY_DEFENDER_AGGRO_4 = -1001038 , SAY_DEFENDER_AGGRO_5 = -1001039 , SAY_DEFENDER_AGGRO_6 = -1001040 , SAY_DEFENDER_AGGRO_7 = -1001041 ,
SAY_DEFENDER_AGGRO_8 = -1001042 , SAY_DEFENDER_AGGRO_9 = -1001043 , SPELL_CLEAVE = 15496 , SPELL_FROST_SHOT = 12551 ,
SPELL_ALLIANCE_TROOP_CREDIT = 59677 , SPELL_HORDE_TROOP_CREDIT = 59764 , NPC_SKYBREAKER_SQUAD_LEADER = 31737 , NPC_SKYBREAKER_INFANTRY = 31701 ,
NPC_KORKRON_SQUAD_LEADER = 31833 , NPC_KORKRON_INFANTRY = 31832 , NPC_YMIRHEIM_DEFENDER = 31746 , QUEST_ID_ASSAULT_BY_GROUND_A = 13284 ,
QUEST_ID_ASSAULT_BY_GROUND_H = 13301
}
enum { SPELL_SHOOT = 15547 , SPELL_HEROIC_STRIKE = 29426 }
enum {
SAY_KAMAROS_START_1 = -1001044 , SAY_KAMAROS_START_2 = -1001045 , SAY_KAMAROS_AGGRO_1 = -1001046 , SAY_KAMAROS_AGGRO_2 = -1001047 ,
SAY_KAMAROS_AGGRO_3 = -1001048 , SAY_KAMAROS_COMPLETE_1 = -1001050 , SAY_KAMAROS_COMPLETE_2 = -1001049 , SPELL_HOLY_SMITE = 25054 ,
SPELL_POWER_WORD_FORTITUDE = 58921 , SPELL_POWER_WORD_SHIELD = 32595 , SPELL_SHADOW_WORD_PAIN = 17146 , NPC_SPIKED_GHOUL = 30597 ,
NPC_KAMAROS_1 = 31279 , NPC_KAMAROS_2 = 32800 , QUEST_ID_NOT_DEAD_YET_A = 13221 , QUEST_ID_NOT_DEAD_YET_H = 13229 ,
QUEST_ID_GET_OUT_OF_HERE_A = 13482 , QUEST_ID_GET_OUT_OF_HERE_H = 13481
}
enum {
SAY_MINER_SUICIDE_1 = -1001117 , SAY_MINER_SUICIDE_2 = -1001118 , SAY_MINER_SUICIDE_3 = -1001119 , SAY_MINER_SUICIDE_4 = -1001120 ,
SAY_MINER_SUICIDE_5 = -1001121 , SAY_MINER_SUICIDE_6 = -1001122 , SAY_MINER_SUICIDE_7 = -1001123 , SAY_MINER_SUICIDE_8 = -1001124 ,
GOSSIP_ITEM_SLAVE_FREE = -3000113 , TEXT_ID = 14068 , NPC_SARONITE_KILL_CREDIT_BUNNY = 31866 , FACTION_HOSTILE = 14 ,
QUEST_SLAVES_TO_SARONITE_A = 13300 , QUEST_SLAVES_TO_SARONITE_H = 13302
}
enum {
SAY_AGGRO = -1001184 , SAY_SPHERE = -1001185 , SAY_NO_MATTER = -1001186 , SAY_TRANSFORM = -1001187 ,
SAY_20_HP = -1001188 , SAY_DEFEATED = -1001189 , SAY_ESCAPE = -1001190 , SPELL_WHIRLWIND = 49807 ,
SPELL_HEROIC_STRIKE_ADMIRAL = 57846 , SPELL_CLEAVE_ADMIRAL = 15284 , SPELL_PROTECTION_SPHERE = 50161 , SPELL_NULLIFIER = 31699 ,
SPELL_SLEEP = 53045 , SPELL_MIND_BLAST = 60500 , SPELL_VAMPIRIC_TOUCH = 60501 , SPELL_CARRION_SWARM = 60502 ,
SPELL_ADMIRAL_PORTAL = 27731 , SPELL_TELEPORT = 35502 , MODEL_ID_MALGANIS = 26582 , NPC_WESTWIND_CREDIT_BUNNY = 29627
}
Functions
UnitAI * GetAI_npc_squad_leader (Creature *pCreature)
bool QuestAccept_npc_squad_leader (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_infantry (Creature *pCreature)
UnitAI * GetAI_npc_father_kamaros (Creature *pCreature)
bool QuestAccept_npc_father_kamaros (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GossipHello_npc_saronite_mine_slave (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_saronite_mine_slave (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_grand_admiral_westwind (Creature *pCreature)
bool EffectDummyCreature_npc_grand_admiral_westwind (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_icecrown ()
Variables
static const float afPointSlaveSalvation [3] = {7030.59f, 1866.73f, 533.94f}
static const float afPointSlaveSuicide1 [3] = {6965.99f, 2051.44f, 519.49f}
static const float afPointSlaveSuicide2 [3] = {6920.47f, 1973.46f, 523.38f}
static const float afPointSlaveSuicide3 [3] = {6915.35f, 2026.35f, 518.53f}
static const float afPortalSpawnLoc [4] = {7494.89f, 4871.53f, -12.65f, 1.37f}
static const float afExitLocation [3] = {7494.78f, 4872.56f, -12.72f}
static const SpellCreateLanceData createLanceData []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_HORDE_SQUAD_RUN
SAY_ALLIANCE_SQUAD_RUN
SAY_SQUAD_AGGRO_1
SAY_SQUAD_AGGRO_2
SAY_HORDE_SQUAD_AGGRO_1
SAY_HORDE_SQUAD_AGGRO_2
SAY_HORDE_SQUAD_AGGRO_3
SAY_HORDE_SQUAD_AGGRO_4
SAY_ALLIANCE_SQUAD_AGGRO_1
SAY_ALLIANCE_SQUAD_AGGRO_2
SAY_ALLIANCE_SQUAD_AGGRO_3
SAY_ALLIANCE_SQUAD_AGGRO_4
SAY_HORDE_SQUAD_BREAK
SAY_HORDE_SQUAD_BREAK_DONE
SAY_ALLIANCE_SQUAD_BREAK
SAY_ALLIANCE_SQUAD_BREAK_DONE
SAY_EVENT_COMPLETE
SAY_DEFENDER_AGGRO_1
SAY_DEFENDER_AGGRO_2
SAY_DEFENDER_AGGRO_3
SAY_DEFENDER_AGGRO_4
SAY_DEFENDER_AGGRO_5
SAY_DEFENDER_AGGRO_6
SAY_DEFENDER_AGGRO_7
SAY_DEFENDER_AGGRO_8
SAY_DEFENDER_AGGRO_9
SPELL_CLEAVE
SPELL_FROST_SHOT
SPELL_ALLIANCE_TROOP_CREDIT
SPELL_HORDE_TROOP_CREDIT
NPC_SKYBREAKER_SQUAD_LEADER
NPC_SKYBREAKER_INFANTRY
NPC_KORKRON_SQUAD_LEADER
NPC_KORKRON_INFANTRY
NPC_YMIRHEIM_DEFENDER
QUEST_ID_ASSAULT_BY_GROUND_A
QUEST_ID_ASSAULT_BY_GROUND_H
Definition at line 39 of file icecrown.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SHOOT
SPELL_HEROIC_STRIKE
Definition at line 310 of file icecrown.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_KAMAROS_START_1
SAY_KAMAROS_START_2
SAY_KAMAROS_AGGRO_1
SAY_KAMAROS_AGGRO_2
SAY_KAMAROS_AGGRO_3
SAY_KAMAROS_COMPLETE_1
SAY_KAMAROS_COMPLETE_2
SPELL_HOLY_SMITE
SPELL_POWER_WORD_FORTITUDE
SPELL_POWER_WORD_SHIELD
SPELL_SHADOW_WORD_PAIN
NPC_SPIKED_GHOUL
NPC_KAMAROS_1
NPC_KAMAROS_2
QUEST_ID_NOT_DEAD_YET_A
QUEST_ID_NOT_DEAD_YET_H
QUEST_ID_GET_OUT_OF_HERE_A
QUEST_ID_GET_OUT_OF_HERE_H
Definition at line 410 of file icecrown.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MINER_SUICIDE_1
SAY_MINER_SUICIDE_2
SAY_MINER_SUICIDE_3
SAY_MINER_SUICIDE_4
SAY_MINER_SUICIDE_5
SAY_MINER_SUICIDE_6
SAY_MINER_SUICIDE_7
SAY_MINER_SUICIDE_8
GOSSIP_ITEM_SLAVE_FREE
TEXT_ID
NPC_SARONITE_KILL_CREDIT_BUNNY
FACTION_HOSTILE
QUEST_SLAVES_TO_SARONITE_A
QUEST_SLAVES_TO_SARONITE_H
Definition at line 564 of file icecrown.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SPHERE
SAY_NO_MATTER
SAY_TRANSFORM
SAY_20_HP
SAY_DEFEATED
SAY_ESCAPE
SPELL_WHIRLWIND
SPELL_HEROIC_STRIKE_ADMIRAL
SPELL_CLEAVE_ADMIRAL
SPELL_PROTECTION_SPHERE
SPELL_NULLIFIER
SPELL_SLEEP
SPELL_MIND_BLAST
SPELL_VAMPIRIC_TOUCH
SPELL_CARRION_SWARM
SPELL_ADMIRAL_PORTAL
SPELL_TELEPORT
MODEL_ID_MALGANIS
NPC_WESTWIND_CREDIT_BUNNY
Definition at line 661 of file icecrown.cpp.
Function Documentation
AddSC_icecrown()
void AddSC_icecrown ()
Definition at line 980 of file icecrown.cpp.
References EffectDummyCreature_npc_grand_admiral_westwind(), Script::GetAI, GetAI_npc_father_kamaros(), GetAI_npc_grand_admiral_westwind(), GetAI_npc_infantry(), GetAI_npc_squad_leader(), GossipHello_npc_saronite_mine_slave(), GossipSelect_npc_saronite_mine_slave(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_father_kamaros(), QuestAccept_npc_squad_leader(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_grand_admiral_westwind()
bool EffectDummyCreature_npc_grand_admiral_westwind (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 922 of file icecrown.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, Object::GetTypeId(), Unit::HasAura(), UnitAI::SendAIEvent(), SPELL_NULLIFIER, SPELL_PROTECTION_SPHERE, and TYPEID_PLAYER.
Referenced by AddSC_icecrown().
GetAI_npc_father_kamaros()
UnitAI* GetAI_npc_father_kamaros (Creature * pCreature)
Definition at line 543 of file icecrown.cpp.
Referenced by AddSC_icecrown().
GetAI_npc_grand_admiral_westwind()
UnitAI* GetAI_npc_grand_admiral_westwind (Creature * pCreature)
Definition at line 917 of file icecrown.cpp.
Referenced by AddSC_icecrown().
GetAI_npc_infantry()
UnitAI* GetAI_npc_infantry (Creature * pCreature)
Definition at line 401 of file icecrown.cpp.
Referenced by AddSC_icecrown().
GetAI_npc_squad_leader()
UnitAI* GetAI_npc_squad_leader (Creature * pCreature)
Definition at line 290 of file icecrown.cpp.
Referenced by AddSC_icecrown().
GossipHello_npc_saronite_mine_slave()
bool GossipHello_npc_saronite_mine_slave (Player * pPlayer, Creature * pCreature)
Definition at line 591 of file icecrown.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SLAVE_FREE, GOSSIP_SENDER_MAIN, QUEST_SLAVES_TO_SARONITE_A, QUEST_SLAVES_TO_SARONITE_H, QUEST_STATUS_INCOMPLETE, and TEXT_ID.
Referenced by AddSC_icecrown().
GossipSelect_npc_saronite_mine_slave()
bool GossipSelect_npc_saronite_mine_slave (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 600 of file icecrown.cpp.
References afPointSlaveSalvation, afPointSlaveSuicide1, afPointSlaveSuicide2, afPointSlaveSuicide3, Creature::AI(), UnitAI::AttackStart(), DoScriptText(), FACTION_HOSTILE, Creature::ForcedDespawn(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, Player::KilledMonsterCredit(), MotionMaster::MovePoint(), NPC_SARONITE_KILL_CREDIT_BUNNY, Object::RemoveFlag(), SAY_MINER_SUICIDE_1, SAY_MINER_SUICIDE_2, SAY_MINER_SUICIDE_3, SAY_MINER_SUICIDE_4, SAY_MINER_SUICIDE_5, SAY_MINER_SUICIDE_6, SAY_MINER_SUICIDE_7, SAY_MINER_SUICIDE_8, Creature::SetFactionTemporary(), Creature::SetWalk(), TEMPFACTION_RESTORE_REACH_HOME, TEMPFACTION_RESTORE_RESPAWN, UNIT_NPC_FLAG_GOSSIP, UNIT_NPC_FLAGS, and urand().
Referenced by AddSC_icecrown().
QuestAccept_npc_father_kamaros()
bool QuestAccept_npc_father_kamaros (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 548 of file icecrown.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_GET_OUT_OF_HERE_A, QUEST_ID_GET_OUT_OF_HERE_H, QUEST_ID_NOT_DEAD_YET_A, QUEST_ID_NOT_DEAD_YET_H, and UnitAI::SendAIEvent().
Referenced by AddSC_icecrown().
QuestAccept_npc_squad_leader()
bool QuestAccept_npc_squad_leader (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 295 of file icecrown.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_ASSAULT_BY_GROUND_A, QUEST_ID_ASSAULT_BY_GROUND_H, and UnitAI::SendAIEvent().
Referenced by AddSC_icecrown().
Variable Documentation
afExitLocation
const float afExitLocation[3] = {7494.78f, 4872.56f, -12.72f} static
Definition at line 692 of file icecrown.cpp.
Referenced by npc_grand_admiral_westwindAI::UpdateAI().
afPointSlaveSalvation
const float afPointSlaveSalvation[3] = {7030.59f, 1866.73f, 533.94f} static
Definition at line 586 of file icecrown.cpp.
Referenced by GossipSelect_npc_saronite_mine_slave().
afPointSlaveSuicide1
const float afPointSlaveSuicide1[3] = {6965.99f, 2051.44f, 519.49f} static
Definition at line 587 of file icecrown.cpp.
Referenced by GossipSelect_npc_saronite_mine_slave().
afPointSlaveSuicide2
const float afPointSlaveSuicide2[3] = {6920.47f, 1973.46f, 523.38f} static
Definition at line 588 of file icecrown.cpp.
Referenced by GossipSelect_npc_saronite_mine_slave().
afPointSlaveSuicide3
const float afPointSlaveSuicide3[3] = {6915.35f, 2026.35f, 518.53f} static
Definition at line 589 of file icecrown.cpp.
Referenced by GossipSelect_npc_saronite_mine_slave().
afPortalSpawnLoc
const float afPortalSpawnLoc[4] = {7494.89f, 4871.53f, -12.65f, 1.37f} static
Definition at line 691 of file icecrown.cpp.
Referenced by npc_grand_admiral_westwindAI::DamageTaken().
createLanceData
const SpellCreateLanceData createLanceData[] static
Initial value:
=
{
    {RACE_HUMAN,    63914, 46069},
    {RACE_DWARF,    63915, 46069},
    {RACE_NIGHTELF, 63916, 46069},
    {RACE_GNOME,    63917, 46069},
    {RACE_DRAENEI,  63918, 46069},
    {RACE_ORC,      63919, 46070},
    {RACE_UNDEAD,   63920, 46070},
    {RACE_TAUREN,   63921, 46070},
    {RACE_TROLL,    63922, 46070},
    {RACE_BLOODELF, 63923, 46070},
}
Definition at line 946 of file icecrown.cpp.
Referenced by spell_create_lance::OnEffectExecute().