CMaNGOS_WoTLK: icecrown_citadelScripts.cpp File Reference
icecrown_citadelScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "icecrown_citadel.h"
#include "AI/BaseAI/GameObjectAI.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct npc_putricides_trapAI
struct LadyDeathwhisperElevator
struct RocketPack
struct RocketPackPeriodic
Enumerations
enum TeleporterSpells {
SPELL_TELE_LIGHTS_HAMMER = 70781 , SPELL_TELE_ORATORY_DAMNED = 70856 , SPELL_TELE_RAMPART_OF_SKULLS = 70857 , SPELL_TELE_DEATHBRINGERS_RISE = 70858 ,
SPELL_TELE_UPPER_SPIRE = 70859 , SPELL_TELE_FROZEN_THRONE = 70860 , SPELL_TELE_SINDRAGOSAS_LAIR = 70861 , SPELL_TELE_EXPEDITION_BASE_CAMP = 64014 ,
SPELL_TELE_FORMATION_GROUNDS = 64032 , SPELL_TELE_COLOSSAL_FORGE = 64028 , SPELL_TELE_SCRAPYARD = 64031 , SPELL_TELE_ANTECHAMBER_OF_ULDUAR = 64030 ,
SPELL_TELE_SHATTERED_WALKWAY = 64029 , SPELL_TELE_CONSERVATORY_OF_LIFE = 64024 , SPELL_TELE_SPARK_OF_IMAGINATION = 65061 , SPELL_TELE_PRISON_OF_YOGG = 65042
}
enum TeleporterGossipItems {
GOSSIP_ITEM_TELE_LIGHTS_HAMMER = -3631000 , GOSSIP_ITEM_TELE_ORATORY_DAMNED = -3631001 , GOSSIP_ITEM_TELE_RAMPART_OF_SKULLS = -3631002 , GOSSIP_ITEM_TELE_DEATHBRINGERS_RISE = -3631003 ,
GOSSIP_ITEM_TELE_UPPER_SPIRE = -3631004 , GOSSIP_ITEM_TELE_SINDRAGOSAS_LAIR = -3631005 , GOSSIP_ITEM_TELE_BASE_CAMP = -3603000 , GOSSIP_ITEM_TELE_FORMATION_GROUNDS = -3603001 ,
GOSSIP_ITEM_TELE_COLOSSAL_FORGE = -3603002 , GOSSIP_ITEM_TELE_SCRAPYARD = -3603003 , GOSSIP_ITEM_TELE_ANTECHAMBER = -3603004 , GOSSIP_ITEM_TELE_WALKWAY = -3603005 ,
GOSSIP_ITEM_TELE_CONSERVATORY = -3603006 , GOSSIP_ITEM_TELE_SPARK_IMAGINATION = -3603007 , GOSSIP_ITEM_TELE_YOGG_SARON = -3603008
}
enum { SPELL_WEB_BEAM = 69887 , NPC_NERUBAR_BROODKEEPER = 36725 }
enum { SPELL_GIANT_INSECT_SWARM = 70475 , NPC_FLESH_EATING_INSECT = 37782 , MAX_INSECT_PER_ROUND = 8 , TOTAL_INSECTS_PER_EVENT = 100 }
Functions
bool GossipHello_go_icc_teleporter (Player *pPlayer, GameObject *pGo)
bool GossipSelect_go_icc_teleporter (Player *pPlayer, GameObject *pGo, uint32 uiSender, uint32 uiAction)
bool AreaTrigger_at_frozen_throne_tele (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_lights_hammer (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_rampart_skull (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_putricides_trap (Player *pPlayer, AreaTriggerEntry const *pAt)
UnitAI * GetAI_npc_putricides_trap (Creature *pCreature)
void AddSC_icecrown_citadel ()
Variables
static const float aFrostwyrmAllySpawnLocs [3] = { -326.5525f, 2236.194f, 328.9574f }
static const float aFrostwyrmHordeSpawnLocs [3] = { -317.854f ,2190.76f ,328.711f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_WEB_BEAM
NPC_NERUBAR_BROODKEEPER
Definition at line 179 of file icecrown_citadelScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GIANT_INSECT_SWARM
NPC_FLESH_EATING_INSECT
MAX_INSECT_PER_ROUND
TOTAL_INSECTS_PER_EVENT
Definition at line 264 of file icecrown_citadelScripts.cpp.
TeleporterGossipItems
enum TeleporterGossipItems
Enumerator
GOSSIP_ITEM_TELE_LIGHTS_HAMMER
GOSSIP_ITEM_TELE_ORATORY_DAMNED
GOSSIP_ITEM_TELE_RAMPART_OF_SKULLS
GOSSIP_ITEM_TELE_DEATHBRINGERS_RISE
GOSSIP_ITEM_TELE_UPPER_SPIRE
GOSSIP_ITEM_TELE_SINDRAGOSAS_LAIR
GOSSIP_ITEM_TELE_BASE_CAMP
GOSSIP_ITEM_TELE_FORMATION_GROUNDS
GOSSIP_ITEM_TELE_COLOSSAL_FORGE
GOSSIP_ITEM_TELE_SCRAPYARD
GOSSIP_ITEM_TELE_ANTECHAMBER
GOSSIP_ITEM_TELE_WALKWAY
GOSSIP_ITEM_TELE_CONSERVATORY
GOSSIP_ITEM_TELE_SPARK_IMAGINATION
GOSSIP_ITEM_TELE_YOGG_SARON
Definition at line 45 of file icecrown_citadelScripts.cpp.
TeleporterSpells
enum TeleporterSpells
Enumerator
SPELL_TELE_LIGHTS_HAMMER
SPELL_TELE_ORATORY_DAMNED
SPELL_TELE_RAMPART_OF_SKULLS
SPELL_TELE_DEATHBRINGERS_RISE
SPELL_TELE_UPPER_SPIRE
SPELL_TELE_FROZEN_THRONE
SPELL_TELE_SINDRAGOSAS_LAIR
SPELL_TELE_EXPEDITION_BASE_CAMP
SPELL_TELE_FORMATION_GROUNDS
SPELL_TELE_COLOSSAL_FORGE
SPELL_TELE_SCRAPYARD
SPELL_TELE_ANTECHAMBER_OF_ULDUAR
SPELL_TELE_SHATTERED_WALKWAY
SPELL_TELE_CONSERVATORY_OF_LIFE
SPELL_TELE_SPARK_OF_IMAGINATION
SPELL_TELE_PRISON_OF_YOGG
Definition at line 33 of file icecrown_citadelScripts.cpp.
Function Documentation
AddSC_icecrown_citadel()
void AddSC_icecrown_citadel ()
Definition at line 484 of file icecrown_citadelScripts.cpp.
References AreaTrigger_at_frozen_throne_tele(), AreaTrigger_at_lights_hammer(), AreaTrigger_at_putricides_trap(), AreaTrigger_at_rampart_skull(), Script::GetAI, GetAI_npc_putricides_trap(), Script::GetGameObjectAI, GossipHello_go_icc_teleporter(), GossipSelect_go_icc_teleporter(), Script::Name, Script::pAreaTrigger, Script::pGossipHelloGO, Script::pGossipSelectGO, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_frozen_throne_tele()
bool AreaTrigger_at_frozen_throne_tele (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 154 of file icecrown_citadelScripts.cpp.
References AT_FROZEN_THRONE_TELE, Unit::CastSpell(), DONE, instance_icecrown_citadel::GetData(), WorldObject::GetInstanceData(), AreaTriggerEntry::id, Player::IsGameMaster(), Unit::IsInCombat(), SPELL_TELE_FROZEN_THRONE, TRIGGERED_OLD_TRIGGERED, TYPE_PROFESSOR_PUTRICIDE, TYPE_QUEEN_LANATHEL, and TYPE_SINDRAGOSA.
Referenced by AddSC_icecrown_citadel().
AreaTrigger_at_lights_hammer()
bool AreaTrigger_at_lights_hammer (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 190 of file icecrown_citadelScripts.cpp.
References AT_LIGHTS_HAMMER_INTRO_1, AT_LIGHTS_HAMMER_INTRO_2, GetCreatureListWithEntryInGrid(), AreaTriggerEntry::id, Unit::IsDead(), Player::IsGameMaster(), NPC_NERUBAR_BROODKEEPER, SPELL_WEB_BEAM, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, and UNIT_FLAG_IMMUNE_TO_PLAYER.
Referenced by AddSC_icecrown_citadel().
AreaTrigger_at_putricides_trap()
bool AreaTrigger_at_putricides_trap (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 279 of file icecrown_citadelScripts.cpp.
References AT_PUTRICIDES_TRAP, DONE, instance_icecrown_citadel::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsDead(), Player::IsGameMaster(), NPC_PUTRICIDES_TRAP, instance_icecrown_citadel::SetData(), SPELL_GIANT_INSECT_SWARM, TRIGGERED_NONE, and TYPE_PLAGUE_WING_ENTRANCE.
Referenced by AddSC_icecrown_citadel().
AreaTrigger_at_rampart_skull()
bool AreaTrigger_at_rampart_skull (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 240 of file icecrown_citadelScripts.cpp.
References aFrostwyrmAllySpawnLocs, aFrostwyrmHordeSpawnLocs, ALLIANCE, AT_RAMPART_ALLIANCE, AT_RAMPART_HORDE, DONE, instance_icecrown_citadel::GetData(), WorldObject::GetInstanceData(), instance_icecrown_citadel::GetPlayerTeam(), ScriptedInstance::GetSingleCreatureFromStorage(), HORDE, AreaTriggerEntry::id, Unit::IsDead(), Player::IsGameMaster(), NPC_SPIRE_FROSTWYRM, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TYPE_LADY_DEATHWHISPER, and TYPE_SPIRE_FROSTWYRM.
Referenced by AddSC_icecrown_citadel().
GetAI_npc_putricides_trap()
UnitAI* GetAI_npc_putricides_trap (Creature * pCreature)
Definition at line 434 of file icecrown_citadelScripts.cpp.
Referenced by AddSC_icecrown_citadel().
GossipHello_go_icc_teleporter()
bool GossipHello_go_icc_teleporter (Player * pPlayer, GameObject * pGo)
Definition at line 55 of file icecrown_citadelScripts.cpp.
References DONE, instance_icecrown_citadel::GetData(), Object::GetEntry(), GameObject::GetGOInfo(), GameObjectInfo::GetGossipMenuId(), Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GO_TRANSPORTER_DEATHBRINGER, GO_TRANSPORTER_LIGHTS_HAMMER, GO_TRANSPORTER_ORATORY_DAMNED, GO_TRANSPORTER_RAMPART_SKULLS, GO_TRANSPORTER_SINDRAGOSA, GO_TRANSPORTER_UPPER_SPIRE, GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TELE_DEATHBRINGERS_RISE, GOSSIP_ITEM_TELE_LIGHTS_HAMMER, GOSSIP_ITEM_TELE_ORATORY_DAMNED, GOSSIP_ITEM_TELE_RAMPART_OF_SKULLS, GOSSIP_ITEM_TELE_SINDRAGOSAS_LAIR, GOSSIP_ITEM_TELE_UPPER_SPIRE, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), TYPE_DEATHBRINGER_SAURFANG, TYPE_GUNSHIP_BATTLE, TYPE_LADY_DEATHWHISPER, TYPE_MARROWGAR, and TYPE_VALITHRIA.
Referenced by AddSC_icecrown_citadel().
GossipSelect_go_icc_teleporter()
bool GossipSelect_go_icc_teleporter (Player * pPlayer, GameObject * pGo, uint32 uiSender, uint32 uiAction)
Definition at line 105 of file icecrown_citadelScripts.cpp.
References GameObject::CastSpell(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, Unit::IsInCombat(), SPELL_TELE_DEATHBRINGERS_RISE, SPELL_TELE_LIGHTS_HAMMER, SPELL_TELE_ORATORY_DAMNED, SPELL_TELE_RAMPART_OF_SKULLS, SPELL_TELE_SINDRAGOSAS_LAIR, SPELL_TELE_UPPER_SPIRE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_icecrown_citadel().
Variable Documentation
aFrostwyrmAllySpawnLocs
const float aFrostwyrmAllySpawnLocs[3] = { -326.5525f, 2236.194f, 328.9574f } static
Definition at line 237 of file icecrown_citadelScripts.cpp.
Referenced by AreaTrigger_at_rampart_skull().
aFrostwyrmHordeSpawnLocs
const float aFrostwyrmHordeSpawnLocs[3] = { -317.854f ,2190.76f ,328.711f } static
Definition at line 238 of file icecrown_citadelScripts.cpp.
Referenced by AreaTrigger_at_rampart_skull().