CMaNGOS_WoTLK: instance_dire_maul.cpp File Reference
instance_dire_maul.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "dire_maul.h"
Data Structures
struct go_ai_fixed_trap
Functions
InstanceData * GetInstanceData_instance_dire_maul (Map *pMap)
GameObjectAI * GetAI_go_fixed_trap (GameObject *go)
bool EffectDummyCreature_spell_guard_slip_kik (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex, Creature *, ObjectGuid)
void AddSC_instance_dire_maul ()
Function Documentation
AddSC_instance_dire_maul()
void AddSC_instance_dire_maul ()
Definition at line 677 of file instance_dire_maul.cpp.
References EffectDummyCreature_spell_guard_slip_kik(), GetAI_go_fixed_trap(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_dire_maul(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_guard_slip_kik()
bool EffectDummyCreature_spell_guard_slip_kik (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex , Creature * , ObjectGuid)
Definition at line 662 of file instance_dire_maul.cpp.
References FACTION_OGRE, WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_GUARD_SLIPKIK, and SPELL_GUARD_SLIPKIK_TRIGGER.
Referenced by AddSC_instance_dire_maul().
GetAI_go_fixed_trap()
GameObjectAI* GetAI_go_fixed_trap (GameObject * go)
Definition at line 653 of file instance_dire_maul.cpp.
Referenced by AddSC_instance_dire_maul().
GetInstanceData_instance_dire_maul()
InstanceData* GetInstanceData_instance_dire_maul (Map * pMap)
Definition at line 619 of file instance_dire_maul.cpp.
Referenced by AddSC_instance_dire_maul().