CMaNGOS_WoTLK: instance_scarlet_monastery.cpp File Reference
instance_scarlet_monastery.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/include/sc_instance.h"
#include "scarlet_monastery.h"
#include "World/WorldStateDefines.h"
Data Structures
struct ABEffect000
Functions
InstanceData * GetInstanceData_instance_scarlet_monastery (Map *pMap)
bool AreaTrigger_at_cathedral_entrance (Player *player, AreaTriggerEntry const *areaTrigger)
void AddSC_instance_scarlet_monastery ()
Function Documentation
AddSC_instance_scarlet_monastery()
void AddSC_instance_scarlet_monastery ()
Definition at line 220 of file instance_scarlet_monastery.cpp.
References AreaTrigger_at_cathedral_entrance(), Script::GetInstanceData, GetInstanceData_instance_scarlet_monastery(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_cathedral_entrance()
bool AreaTrigger_at_cathedral_entrance (Player * player, AreaTriggerEntry const * areaTrigger)
Definition at line 198 of file instance_scarlet_monastery.cpp.
References WorldObject::GetInstanceData(), Player::HasItemCount(), Unit::IsAlive(), Player::IsGameMaster(), and ITEM_CORRUPTED_ASHRBRINGER.
Referenced by AddSC_instance_scarlet_monastery().
GetInstanceData_instance_scarlet_monastery()
InstanceData* GetInstanceData_instance_scarlet_monastery (Map * pMap)
Definition at line 179 of file instance_scarlet_monastery.cpp.
Referenced by AddSC_instance_scarlet_monastery().