CMaNGOS_WoTLK: instance_trial_of_the_champion.cpp File Reference
instance_trial_of_the_champion.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_champion.h"
Enumerations
enum {
SAY_HERALD_HORDE_CHALLENGE = -1650000 , SAY_HERALD_ALLIANCE_CHALLENGE = -1650006 , SAY_TIRION_CHALLENGE_WELCOME = -1650012 , SAY_TIRION_FIRST_CHALLENGE = -1650013 ,
SAY_THRALL_ALLIANCE_CHALLENGE = -1650014 , SAY_GARROSH_ALLIANCE_CHALLENGE = -1650015 , SAY_VARIAN_HORDE_CHALLENGE = -1650016 , SAY_TIRION_CHALLENGE_BEGIN = -1650017 ,
SAY_TIRION_ARGENT_CHAMPION = -1650028 , SAY_TIRION_ARGENT_CHAMPION_BEGIN = -1650029 , SAY_HERALD_EADRIC = -1650030 , SAY_HERALD_PALETRESS = -1650031 ,
EMOTE_HORDE_ARGENT_CHAMPION = -1650032 , EMOTE_ALLIANCE_ARGENT_CHAMPION = -1650033 , SAY_EADRIC_INTRO = -1650034 , SAY_PALETRESS_INTRO_1 = -1650035 ,
SAY_PALETRESS_INTRO_2 = -1650036 , SAY_TIRION_ARGENT_CHAMPION_COMPLETE = -1650037 , SAY_HERALD_BLACK_KNIGHT_SPAWN = -1650038 , SAY_BLACK_KNIGHT_INTRO_1 = -1650039 ,
SAY_TIRION_BLACK_KNIGHT_INTRO_2 = -1650040 , SAY_BLACK_KNIGHT_INTRO_3 = -1650041 , SAY_BLACK_KNIGHT_INTRO_4 = -1650042 , SAY_BLACK_KNIGHT_AGGRO = -1650065 ,
SAY_GARROSH_BLACK_KNIGHT = -1650047 , SAY_VARIAN_BLACK_KNIGHT = -1650050 , SAY_TIRION_EPILOG_1 = -1650043 , SAY_TIRION_EPILOG_2 = -1650044 ,
SAY_VARIAN_ALLIANCE_EPILOG_3 = -1650045 , SAY_THRALL_HORDE_EPILOG_3 = -1650046 , SAY_THRALL_OTHER_2 = -1650048 , SAY_GARROSH_OTHER_3 = -1650049 ,
SAY_VARIAN_OTHER_5 = -1650051 , SOUND_ID_CHALLENGE = 15852 , SPELL_ARGENT_GET_PLAYER_COUNT = 66986 , SPELL_ARGENT_SUMMON_CHAMPION_1 = 66654 ,
SPELL_ARGENT_SUMMON_CHAMPION_2 = 66671 , SPELL_ARGENT_SUMMON_CHAMPION_3 = 66673 , SPELL_ARGENT_SUMMON_BOSS_4 = 67396 , SPELL_CHAMPION_KILL_CREDIT = 68572 ,
SPELL_HERALD_FACE_DARK_KNIGHT = 67482 , SPELL_DEATHS_RESPITE = 66798 , SPELL_ARGENT_HERALD_FEIGN_DEATH = 66804 , SPELL_SPECTATOR_FORCE_CHEER = 66384 ,
SPELL_SPECTATOR_FORCE_CHEER_2 = 66385 , FACTION_CHAMPION_HOSTILE = 16
}
Functions
InstanceData * GetInstanceData_instance_trial_of_the_champion (Map *pMap)
void AddSC_instance_trial_of_the_champion ()
Variables
static const DialogueEntryTwoSide aTocDialogues []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_HERALD_HORDE_CHALLENGE
SAY_HERALD_ALLIANCE_CHALLENGE
SAY_TIRION_CHALLENGE_WELCOME
SAY_TIRION_FIRST_CHALLENGE
SAY_THRALL_ALLIANCE_CHALLENGE
SAY_GARROSH_ALLIANCE_CHALLENGE
SAY_VARIAN_HORDE_CHALLENGE
SAY_TIRION_CHALLENGE_BEGIN
SAY_TIRION_ARGENT_CHAMPION
SAY_TIRION_ARGENT_CHAMPION_BEGIN
SAY_HERALD_EADRIC
SAY_HERALD_PALETRESS
EMOTE_HORDE_ARGENT_CHAMPION
EMOTE_ALLIANCE_ARGENT_CHAMPION
SAY_EADRIC_INTRO
SAY_PALETRESS_INTRO_1
SAY_PALETRESS_INTRO_2
SAY_TIRION_ARGENT_CHAMPION_COMPLETE
SAY_HERALD_BLACK_KNIGHT_SPAWN
SAY_BLACK_KNIGHT_INTRO_1
SAY_TIRION_BLACK_KNIGHT_INTRO_2
SAY_BLACK_KNIGHT_INTRO_3
SAY_BLACK_KNIGHT_INTRO_4
SAY_BLACK_KNIGHT_AGGRO
SAY_GARROSH_BLACK_KNIGHT
SAY_VARIAN_BLACK_KNIGHT
SAY_TIRION_EPILOG_1
SAY_TIRION_EPILOG_2
SAY_VARIAN_ALLIANCE_EPILOG_3
SAY_THRALL_HORDE_EPILOG_3
SAY_THRALL_OTHER_2
SAY_GARROSH_OTHER_3
SAY_VARIAN_OTHER_5
SOUND_ID_CHALLENGE
SPELL_ARGENT_GET_PLAYER_COUNT
SPELL_ARGENT_SUMMON_CHAMPION_1
SPELL_ARGENT_SUMMON_CHAMPION_2
SPELL_ARGENT_SUMMON_CHAMPION_3
SPELL_ARGENT_SUMMON_BOSS_4
SPELL_CHAMPION_KILL_CREDIT
SPELL_HERALD_FACE_DARK_KNIGHT
SPELL_DEATHS_RESPITE
SPELL_ARGENT_HERALD_FEIGN_DEATH
SPELL_SPECTATOR_FORCE_CHEER
SPELL_SPECTATOR_FORCE_CHEER_2
FACTION_CHAMPION_HOSTILE
Definition at line 33 of file instance_trial_of_the_champion.cpp.
Function Documentation
AddSC_instance_trial_of_the_champion()
void AddSC_instance_trial_of_the_champion ()
Definition at line 1188 of file instance_trial_of_the_champion.cpp.
References Script::GetInstanceData, GetInstanceData_instance_trial_of_the_champion(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_trial_of_the_champion()
InstanceData* GetInstanceData_instance_trial_of_the_champion (Map * pMap)
Definition at line 1183 of file instance_trial_of_the_champion.cpp.
Referenced by AddSC_instance_trial_of_the_champion().
Variable Documentation
aTocDialogues
const DialogueEntryTwoSide aTocDialogues[] static
Definition at line 107 of file instance_trial_of_the_champion.cpp.