CMaNGOS_WoTLK: instance_scholomance.cpp File Reference
instance_scholomance.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "scholomance.h"
#include "GameEvents/GameEventMgr.h"
Functions
InstanceData * GetInstanceData_instance_scholomance (Map *pMap)
bool ProcessEventId_event_spell_gandling_shadow_portal (uint32 uiEventId, Object *pSource, Object *, bool)
bool ProcessEventId_dawn_gambit (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_instance_scholomance ()
Function Documentation
AddSC_instance_scholomance()
void AddSC_instance_scholomance ()
Definition at line 509 of file instance_scholomance.cpp.
References Script::GetInstanceData, GetInstanceData_instance_scholomance(), Script::Name, Script::pProcessEventId, ProcessEventId_dawn_gambit(), ProcessEventId_event_spell_gandling_shadow_portal(), and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_scholomance()
InstanceData* GetInstanceData_instance_scholomance (Map * pMap)
Definition at line 469 of file instance_scholomance.cpp.
Referenced by AddSC_instance_scholomance().
ProcessEventId_dawn_gambit()
bool ProcessEventId_dawn_gambit (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 496 of file instance_scholomance.cpp.
References EVENT_ID_DAWN_GAMBIT.
Referenced by AddSC_instance_scholomance().
ProcessEventId_event_spell_gandling_shadow_portal()
bool ProcessEventId_event_spell_gandling_shadow_portal (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 474 of file instance_scholomance.cpp.
References aGandlingEvents, Object::GetTypeId(), SPECIAL, and TYPEID_UNIT.
Referenced by AddSC_instance_scholomance().