CMaNGOS_WoTLK: instance_blackrock_spire.cpp File Reference
instance_blackrock_spire.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackrock_spire.h"
Data Structures
struct npc_rookery_hatcherAI
Enumerations
enum {
AREATRIGGER_ENTER_UBRS = 2046 , AREATRIGGER_STADIUM = 2026 , AREATRIGGER_BEAST_AGGRO = 2066 , AREATRIGGER_BEAST_INTRO = 2067 ,
SAY_NEFARIUS_INTRO_1 = -1229004 , SAY_NEFARIUS_INTRO_2 = -1229005 , SAY_NEFARIUS_LOSE1 = -1229014 , SAY_REND_ATTACK = -1229015 ,
SAY_NEFARIUS_WARCHIEF = -1229016 , SAY_NEFARIUS_VICTORY = -1229018 , SAY_NEFARIUS_TAUNT1 = -1229006 , SAY_NEFARIUS_TAUNT2 = -1229008 ,
SAY_NEFARIUS_TAUNT3 = -1229009 , SAY_NEFARIUS_TAUNT4 = -1229010 , SAY_NEFARIUS_TAUNT5 = -1229013 , SAY_NEFARIUS_TAUNT6 = -1229021 ,
SAY_NEFARIUS_TAUNT7 = -1229022 , SAY_NEFARIUS_TAUNT8 = -1229023 , SAY_REND_TAUNT1 = -1229007 , SAY_REND_TAUNT2 = -1229011 ,
SAY_REND_TAUNT3 = -1229012 , SAY_REND_TAUNT4 = -1229024 , EMOTE_BEGIN = -1229000 , SPELL_EMBERSEER_GROWING = 16048 ,
SAY_ROOKERY_EVENT_START = -1229020 , NPC_ROOKERY_GUARDIAN = 10258 , NPC_ROOKERY_HATCHER = 10683 , SPELL_FINKLE_IS_EINHORN = 16710
}
enum { SPELL_STRIKE = 15580 , SPELL_SUNDER_ARMOR = 15572 , SPELL_DISTURB_EGGS = 15746 }
Functions
InstanceData * GetInstanceData_instance_blackrock_spire (Map *pMap)
bool AreaTrigger_at_blackrock_spire (Player *pPlayer, AreaTriggerEntry const *pAt)
bool ProcessEventId_event_spell_altar_emberseer (uint32, Object *pSource, Object *, bool bIsStart)
bool GOUse_go_father_flame (Player *, GameObject *pGo)
UnitAI * GetAI_npc_rookery_hatcher (Creature *pCreature)
void AddSC_instance_blackrock_spire ()
Variables
static const DialogueEntry aStadiumDialogue []
static const float rookeryEventSpawnPos [3] = {51.11098f, -266.0549f, 92.87846f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AREATRIGGER_ENTER_UBRS
AREATRIGGER_STADIUM
AREATRIGGER_BEAST_AGGRO
AREATRIGGER_BEAST_INTRO
SAY_NEFARIUS_INTRO_1
SAY_NEFARIUS_INTRO_2
SAY_NEFARIUS_LOSE1
SAY_REND_ATTACK
SAY_NEFARIUS_WARCHIEF
SAY_NEFARIUS_VICTORY
SAY_NEFARIUS_TAUNT1
SAY_NEFARIUS_TAUNT2
SAY_NEFARIUS_TAUNT3
SAY_NEFARIUS_TAUNT4
SAY_NEFARIUS_TAUNT5
SAY_NEFARIUS_TAUNT6
SAY_NEFARIUS_TAUNT7
SAY_NEFARIUS_TAUNT8
SAY_REND_TAUNT1
SAY_REND_TAUNT2
SAY_REND_TAUNT3
SAY_REND_TAUNT4
EMOTE_BEGIN
SPELL_EMBERSEER_GROWING
SAY_ROOKERY_EVENT_START
NPC_ROOKERY_GUARDIAN
NPC_ROOKERY_HATCHER
SPELL_FINKLE_IS_EINHORN
Definition at line 27 of file instance_blackrock_spire.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_STRIKE
SPELL_SUNDER_ARMOR
SPELL_DISTURB_EGGS
Definition at line 831 of file instance_blackrock_spire.cpp.
Function Documentation
AddSC_instance_blackrock_spire()
void AddSC_instance_blackrock_spire ()
Definition at line 963 of file instance_blackrock_spire.cpp.
References AreaTrigger_at_blackrock_spire(), Script::GetAI, GetAI_npc_rookery_hatcher(), Script::GetInstanceData, GetInstanceData_instance_blackrock_spire(), GOUse_go_father_flame(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_spell_altar_emberseer(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_blackrock_spire()
bool AreaTrigger_at_blackrock_spire (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 733 of file instance_blackrock_spire.cpp.
References aBeastLocs, AREATRIGGER_BEAST_AGGRO, AREATRIGGER_BEAST_INTRO, AREATRIGGER_ENTER_UBRS, AREATRIGGER_STADIUM, aStadiumLocs, DONE, FACTION_BLACK_DRAGON, WorldObject::GetInstanceData(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), NPC_BLACKHAND_ELITE, NPC_LORD_VICTOR_NEFARIUS, NPC_REND_BLACKHAND, NPC_THE_BEAST, Position::o, WorldObject::SummonCreature(), TEMPFACTION_NONE, TEMPSPAWN_CORPSE_DESPAWN, TEMPSPAWN_DEAD_DESPAWN, TYPE_STADIUM, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, Position::x, Position::y, and Position::z.
Referenced by AddSC_instance_blackrock_spire().
GetAI_npc_rookery_hatcher()
UnitAI* GetAI_npc_rookery_hatcher (Creature * pCreature)
Definition at line 958 of file instance_blackrock_spire.cpp.
Referenced by AddSC_instance_blackrock_spire().
GetInstanceData_instance_blackrock_spire()
InstanceData* GetInstanceData_instance_blackrock_spire (Map * pMap)
Definition at line 728 of file instance_blackrock_spire.cpp.
Referenced by AddSC_instance_blackrock_spire().
GOUse_go_father_flame()
bool GOUse_go_father_flame (Player * , GameObject * pGo)
Definition at line 823 of file instance_blackrock_spire.cpp.
References WorldObject::GetInstanceData().
Referenced by AddSC_instance_blackrock_spire().
ProcessEventId_event_spell_altar_emberseer()
bool ProcessEventId_event_spell_altar_emberseer (uint32 , Object * pSource, Object * , bool bIsStart)
Definition at line 810 of file instance_blackrock_spire.cpp.
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by AddSC_instance_blackrock_spire().
Variable Documentation
aStadiumDialogue
const DialogueEntry aStadiumDialogue[] static
Initial value:
=
{
    {NPC_LORD_VICTOR_NEFARIUS,  0,                          1000},
    {SAY_NEFARIUS_INTRO_1,      NPC_LORD_VICTOR_NEFARIUS,   7000},
    {SAY_NEFARIUS_INTRO_2,      NPC_LORD_VICTOR_NEFARIUS,   5000},
    {NPC_BLACKHAND_HANDLER,     0,                          0},
    {SAY_NEFARIUS_LOSE1,       NPC_LORD_VICTOR_NEFARIUS,   3000},
    {SAY_REND_ATTACK,           NPC_REND_BLACKHAND,         2000},
    {SAY_NEFARIUS_WARCHIEF,     NPC_LORD_VICTOR_NEFARIUS,   0},
    {SAY_NEFARIUS_VICTORY,      NPC_LORD_VICTOR_NEFARIUS,   5000},
    {NPC_REND_BLACKHAND,        0,                          0},
    {0, 0, 0},
}
Definition at line 83 of file instance_blackrock_spire.cpp.
rookeryEventSpawnPos
const float rookeryEventSpawnPos[3] = {51.11098f, -266.0549f, 92.87846f} static
Definition at line 97 of file instance_blackrock_spire.cpp.
Referenced by instance_blackrock_spire::DoSendNextFlamewreathWave().