CMaNGOS_WoTLK: instance_blackfathom_deeps.cpp File Reference
instance_blackfathom_deeps.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "blackfathom_deeps.h"
Functions
InstanceData * GetInstanceData_instance_blackfathom_deeps (Map *pMap)
bool GOUse_go_fire_of_akumai (Player *, GameObject *pGo)
bool GOUse_go_fathom_stone (Player *pPlayer, GameObject *pGo)
void AddSC_instance_blackfathom_deeps ()
Function Documentation
AddSC_instance_blackfathom_deeps()
void AddSC_instance_blackfathom_deeps ()
Definition at line 288 of file instance_blackfathom_deeps.cpp.
References Script::GetInstanceData, GetInstanceData_instance_blackfathom_deeps(), GOUse_go_fathom_stone(), GOUse_go_fire_of_akumai(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_blackfathom_deeps()
InstanceData* GetInstanceData_instance_blackfathom_deeps (Map * pMap)
Definition at line 249 of file instance_blackfathom_deeps.cpp.
Referenced by AddSC_instance_blackfathom_deeps().
GOUse_go_fathom_stone()
bool GOUse_go_fathom_stone (Player * pPlayer, GameObject * pGo)
Definition at line 273 of file instance_blackfathom_deeps.cpp.
References afAquanisPos, instance_blackfathom_deeps::GetData(), WorldObject::GetInstanceData(), IN_PROGRESS, NOT_STARTED, NPC_BARON_AQUANIS, instance_blackfathom_deeps::SetData(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_AQUANIS.
Referenced by AddSC_instance_blackfathom_deeps().
GOUse_go_fire_of_akumai()
bool GOUse_go_fire_of_akumai (Player * , GameObject * pGo)
Definition at line 254 of file instance_blackfathom_deeps.cpp.
References DONE, instance_blackfathom_deeps::GetData(), WorldObject::GetInstanceData(), IN_PROGRESS, instance_blackfathom_deeps::SetData(), TYPE_KELRIS, and TYPE_SHRINE.
Referenced by AddSC_instance_blackfathom_deeps().