CMaNGOS_WoTLK: instance_shadowfang_keep.cpp File Reference
instance_shadowfang_keep.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shadowfang_keep.h"
#include "LFG/LFGDefines.h"
#include "World/WorldStateDefines.h"
Functions
InstanceData * GetInstanceData_instance_shadowfang_keep (Map *map)
void AddSC_instance_shadowfang_keep ()
Variables
static const DialogueEntry aArugalDialogue []
Function Documentation
AddSC_instance_shadowfang_keep()
void AddSC_instance_shadowfang_keep ()
Definition at line 462 of file instance_shadowfang_keep.cpp.
References Script::GetInstanceData, GetInstanceData_instance_shadowfang_keep(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_shadowfang_keep()
InstanceData* GetInstanceData_instance_shadowfang_keep (Map * map)
Definition at line 457 of file instance_shadowfang_keep.cpp.
Referenced by AddSC_instance_shadowfang_keep().
Variable Documentation
aArugalDialogue
const DialogueEntry aArugalDialogue[] static
Initial value:
=
{
    {NPC_VINCENT,                      0,   3000},
    {VINCENT_DEATH,          NPC_VINCENT,   8000},
    {ARUGAL_VISIBLE,          NPC_ARUGAL,    100},
    {ARUGAL_TELEPORT_IN,      NPC_ARUGAL,   3200},
    {ARUGAL_TURN_TO_VINCENT,  NPC_ARUGAL,    100},
    {SAY_ARUGAL_INTRO_1,      NPC_ARUGAL,   3500},
    {ARUGAL_EMOTE_POINT,      NPC_ARUGAL,   2000},
    {SAY_ARUGAL_INTRO_2,      NPC_ARUGAL,   1500},
    {ARUGAL_EMOTE_EXCLAMATION,NPC_ARUGAL,   3000},
    {SAY_ARUGAL_INTRO_3,      NPC_ARUGAL,   3000},
    {ARUGAL_EMOTE_LAUGH,      NPC_ARUGAL,   2500},
    {SAY_ARUGAL_INTRO_4,      NPC_ARUGAL,   2500},
    {ARUGAL_TELEPORT_OUT,     NPC_ARUGAL,   2000},
    {ARUGAL_INTRO_DONE,       NPC_ARUGAL,      0},
    {NPC_ARCHMAGE_ARUGAL,              0,    100},
    {YELL_FENRUS,    NPC_ARCHMAGE_ARUGAL,   2000},
    {ARCHMAGE_FIRE,  NPC_ARCHMAGE_ARUGAL,   5000},
    {ARCHMAGE_LIGHTNING, NPC_ARCHMAGE_ARUGAL, 5000},
    {ARCHMAGE_INVIS, NPC_ARCHMAGE_ARUGAL,    500},
    {ARCHMAGE_VOIDWALKERS, NPC_ARCHMAGE_ARUGAL, 0},
    {0, 0, 0},
}
Definition at line 29 of file instance_shadowfang_keep.cpp.