CMaNGOS_WoTLK: instance_culling_of_stratholme.cpp File Reference
instance_culling_of_stratholme.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "culling_of_stratholme.h"
Data Structures
struct sSpawnLocation
struct sScourgeSpawnLoc
struct sBurningScourgeSpawnLoc
Enumerations
enum {
MAX_ARTHAS_SPAWN_POS = 5 , MAX_GRAIN_CRATES = 5 , MAX_SCOURGE_SPAWN_POS = 5 , MAX_BURNING_SCOURGE_POS = 15 ,
SAY_SCOURGE_FESTIVAL_LANE = -1595003 , SAY_SCOURGE_KINGS_SQUARE = -1595004 , SAY_SCOURGE_MARKET_ROW = -1595005 , SAY_SCOURGE_TOWN_HALL = -1595006 ,
SAY_SCOURGE_ELDERS_SQUARE = -1595007 , SAY_MEET_TOWN_HALL = -1595008 , SAY_CORRUPTOR_DESPAWN = -1595041 , WHISPER_CHROMIE_CRATES = -1595001 ,
WHISPER_CHROMIE_GUARDIAN = -1595002 , WHISPER_CHROMIE_HURRY = -1000000 , SPELL_CORRUPTION_OF_TIME = 60422
}
Functions
static bool sortFromEastToWest (Creature *pFirst, Creature *pSecond)
InstanceData * GetInstanceData_instance_culling_of_stratholme (Map *pMap)
bool AreaTrigger_at_culling_of_stratholme (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_instance_culling_of_stratholme ()
Variables
static sSpawnLocation m_aArthasSpawnLocs []
static sSpawnLocation m_aIntroActorsSpawnLocs []
static sSpawnLocation m_aChromieSpawnLocs []
static sSpawnLocation m_aHeroicEventSpawnLocs []
static sScourgeSpawnLoc m_aScourgeWavesLocs []
static sBurningScourgeSpawnLoc m_aBurningScourgeLocs [MAX_BURNING_SCOURGE_POS]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAX_ARTHAS_SPAWN_POS
MAX_GRAIN_CRATES
MAX_SCOURGE_SPAWN_POS
MAX_BURNING_SCOURGE_POS
SAY_SCOURGE_FESTIVAL_LANE
SAY_SCOURGE_KINGS_SQUARE
SAY_SCOURGE_MARKET_ROW
SAY_SCOURGE_TOWN_HALL
SAY_SCOURGE_ELDERS_SQUARE
SAY_MEET_TOWN_HALL
SAY_CORRUPTOR_DESPAWN
WHISPER_CHROMIE_CRATES
WHISPER_CHROMIE_GUARDIAN
WHISPER_CHROMIE_HURRY
SPELL_CORRUPTION_OF_TIME
Definition at line 27 of file instance_culling_of_stratholme.cpp.
Function Documentation
AddSC_instance_culling_of_stratholme()
void AddSC_instance_culling_of_stratholme ()
Definition at line 960 of file instance_culling_of_stratholme.cpp.
References AreaTrigger_at_culling_of_stratholme(), Script::GetInstanceData, GetInstanceData_instance_culling_of_stratholme(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_culling_of_stratholme()
bool AreaTrigger_at_culling_of_stratholme (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 946 of file instance_culling_of_stratholme.cpp.
References AREATRIGGER_INN, WorldObject::GetInstanceData(), AreaTriggerEntry::id, Unit::IsDead(), and Player::IsGameMaster().
Referenced by AddSC_instance_culling_of_stratholme().
GetInstanceData_instance_culling_of_stratholme()
InstanceData* GetInstanceData_instance_culling_of_stratholme (Map * pMap)
Definition at line 941 of file instance_culling_of_stratholme.cpp.
Referenced by AddSC_instance_culling_of_stratholme().
sortFromEastToWest()
static bool sortFromEastToWest (Creature * pFirst, Creature * pSecond) static
Definition at line 551 of file instance_culling_of_stratholme.cpp.
References WorldObject::GetPositionY().
Referenced by instance_culling_of_stratholme::GetCratesBunnyOrderedList().
Variable Documentation
m_aArthasSpawnLocs
sSpawnLocation m_aArthasSpawnLocs[] static
Initial value:
=
{
    {1957.13f, 1287.43f, 145.65f, 2.96f},
    {2091.99f, 1277.25f, 140.47f, 0.43f},
    {2366.24f, 1195.25f, 132.04f, 3.15f},
    {2534.98f, 1126.16f, 130.86f, 2.84f},
    {2363.44f, 1404.90f, 128.64f, 2.77f},
}
Definition at line 55 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSpawnArthasIfNeeded().
m_aBurningScourgeLocs
sBurningScourgeSpawnLoc m_aBurningScourgeLocs[MAX_BURNING_SCOURGE_POS] static
Initial value:
=
{
    {SCOURGE_TYPE_GHOUL, 2571.570f, 1169.945f, 126.191f},
    {SCOURGE_TYPE_GOLEM, 2560.524f, 1208.296f, 125.613f},
    {SCOURGE_TYPE_GHOUL, 2562.075f, 1182.137f, 126.499f},
    {SCOURGE_TYPE_FIEND, 2552.720f, 1227.233f, 125.620f},
    {SCOURGE_TYPE_GHOUL, 2545.070f, 1245.650f, 125.991f},
    {SCOURGE_TYPE_GHOUL, 2534.250f, 1258.379f, 127.030f},
    {SCOURGE_TYPE_ACOLYTES, 2532.075f, 1271.579f, 127.243f},
    {SCOURGE_TYPE_GHOUL, 2529.144f, 1281.680f, 128.429f},
    {SCOURGE_TYPE_GHOUL, 2491.742f, 1365.169f, 130.827f},
    {SCOURGE_TYPE_FIEND, 2490.869f, 1366.189f, 130.678f},
    {SCOURGE_TYPE_GHOUL, 2479.944f, 1393.666f, 129.975f},
    {SCOURGE_TYPE_GOLEM, 2484.858f, 1380.665f, 130.075f},
    {SCOURGE_TYPE_GHOUL, 2474.965f, 1399.063f, 130.317f},
    {SCOURGE_TYPE_ACOLYTES, 2461.411f, 1416.090f, 130.663f},
    {SCOURGE_TYPE_GHOUL, 2448.391f, 1426.428f, 130.853f},
}
Definition at line 115 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSpawnBurningCityUndead().
m_aChromieSpawnLocs
sSpawnLocation m_aChromieSpawnLocs[] static
Initial value:
=
{
    {1813.298f, 1283.578f, 142.3258f, 3.96f},
    {2319.562f, 1506.409f, 152.0499f, 3.78f},
    {1810.875f, 1285.035f, 142.4917f, 4.48f},
}
Definition at line 79 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSpawnChromieIfNeeded().
m_aHeroicEventSpawnLocs
sSpawnLocation m_aHeroicEventSpawnLocs[] static
Initial value:
=
{
    {2331.642f, 1273.273f, 132.954f, 3.71f},
    {2334.626f, 1280.450f, 133.006f, 1.72f},
    {2321.489f, 1268.383f, 132.850f, 0.41f},
}
Definition at line 86 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSpawnCorruptorIfNeeded().
m_aIntroActorsSpawnLocs
sSpawnLocation m_aIntroActorsSpawnLocs[] static
Initial value:
=
{
    {1876.78f, 1305.72f, 146.24f, 6.07f},
    {1786.18f, 1268.63f, 140.02f, 0.42f},
    {1780.26f, 1261.87f, 139.55f, 0.57f},
    {1778.59f, 1265.03f, 139.43f, 0.40f},
    {1777.04f, 1268.16f, 139.35f, 0.59f},
    {2091.47f, 1294.28f, 139.82f, 6.27f},
    {2091.26f, 1281.71f, 139.92f, 6.27f},
    {2096.12f, 1290.53f, 138.81f, 6.27f},
    {2096.41f, 1284.22f, 138.79f, 6.27f},
    {2096.93f, 1297.57f, 138.96f, 6.27f},
    {2096.32f, 1278.98f, 139.43f, 6.27f}
}
Definition at line 64 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSetupEntranceSoldiers(), and instance_culling_of_stratholme::DoSpawnArthasIfNeeded().
m_aScourgeWavesLocs
sScourgeSpawnLoc m_aScourgeWavesLocs[] static
Initial value:
=
{
    {POS_FESTIVAL_LANE, SAY_SCOURGE_FESTIVAL_LANE,  2176.517f, 1244.970f, 136.021f, 1.86f},
    {POS_KINGS_SQUARE,  SAY_SCOURGE_KINGS_SQUARE,   2130.760f, 1353.649f, 131.396f, 6.02f},
    {POS_MARKET_ROW,    SAY_SCOURGE_MARKET_ROW,     2219.825f, 1331.119f, 127.978f, 3.08f},
    {POS_TOWN_HALL,     SAY_SCOURGE_TOWN_HALL,      2351.475f, 1211.893f, 130.361f, 4.50f},
    {POS_ELDERS_SQUARE, SAY_SCOURGE_ELDERS_SQUARE,  2259.153f, 1153.199f, 138.431f, 2.39f},
}
Definition at line 100 of file instance_culling_of_stratholme.cpp.
Referenced by instance_culling_of_stratholme::DoSpawnNextScourgeWave().