CMaNGOS_WoTLK: instance_uldaman.cpp File Reference
instance_uldaman.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "uldaman.h"
Functions
InstanceData * GetInstanceData_instance_uldaman (Map *pMap)
bool ProcessEventId_event_spell_altar_boss_aggro (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
void AddSC_instance_uldaman ()
Function Documentation
AddSC_instance_uldaman()
void AddSC_instance_uldaman ()
Definition at line 325 of file instance_uldaman.cpp.
References Script::GetInstanceData, GetInstanceData_instance_uldaman(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_altar_boss_aggro(), and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_uldaman()
InstanceData* GetInstanceData_instance_uldaman (Map * pMap)
Definition at line 307 of file instance_uldaman.cpp.
Referenced by AddSC_instance_uldaman().
ProcessEventId_event_spell_altar_boss_aggro()
bool ProcessEventId_event_spell_altar_boss_aggro (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 312 of file instance_uldaman.cpp.
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by AddSC_instance_uldaman().