CMaNGOS_WoTLK: isle_of_queldanas.cpp File Reference
isle_of_queldanas.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct npc_converted_sentryAI
struct npc_shattered_sun_fighterAI
struct npc_shattered_sun_warriorAI
struct npc_shattered_sun_marksmanAI
struct ShatteredSunMarksmanShoot
struct npc_dawnblade_blood_knight
struct SparAuras
Enumerations
enum { SAY_CONVERTED_1 = -1000188 , SAY_CONVERTED_2 = -1000189 , SPELL_CONVERT_CREDIT = 45009 , TIME_PET_DURATION = 7500 }
enum {
ZONEID_ISLE_OF_QUELDANAS = 4080 , NPC_SHATTERED_SUN_WARRIOR = 25115 , NPC_SHATTERED_SUN_MARKSMAN = 24938 , SCRIPT_TRANSFORM_ARCHER_BE_MALE = 2493801 ,
SCRIPT_TRANSFORM_ARCHER_BE_FEMALE = 2493802 , SCRIPT_TRANSFORM_ARCHER_DRAENEI_MALE = 2493803 , SCRIPT_TRANSFORM_ARCHER_DRAENEI_FEMALE = 2493804 , SCRIPT_TRANSFORM_WARRIOR_BE_MALE = 2511502 ,
SCRIPT_TRANSFORM_WARRIOR_BE_FEMALE = 2511501 , SCRIPT_TRANSFORM_WARRIOR_DRAENEI_MALE = 2511504 , SCRIPT_TRANSFORM_WARRIOR_DRAENEI_FEMALE = 2511503
}
enum { SPELL_SHOOT_BLOODELF_NW = 45219 , SPELL_SHOOT_DRAENEI_NW = 45223 , SPELL_SHOOT_BLOODELF_SE = 45229 , SPELL_SHOOT_DRAENEI_SE = 45233 }
enum {
NPC_DAWNBLADE_BLOOD_KNIGHT = 24976 , SPELL_SEAL_OF_WRATH = 45095 , SPELL_JOUST = 45105 , SPELL_JUDGEMENT_OF_WRATH = 45337 ,
SPELL_HOLY_LIGHT = 13952 , SPELL_FACTION_SPAR = 45091 , SPELL_FACTION_SPAR_BUDDY = 45092 , AREA_ID_DAWNSTAR_VILLAGE = 4089 ,
FACTION_SPARRING_DAWNBLADE = 1965 , FACTION_SPAR_BUDDY = 1814
}
enum DawnbladeBloodKnightActions {
DAWNBLADE_BLOOD_KNIGHT_STOP_EVENT , DAWNBLADE_BLOOD_KNIGHT_SEAL_OF_WRATH , DAWNBLADE_BLOOD_KNIGHT_JUDGEMENT_OF_WRATH , DAWNBLADE_BLOOD_KNIGHT_HOLY_LIGHT ,
DAWNBLADE_BLOOD_KNIGHT_ACTION_MAX , DAWNBLADE_BLOOD_KNIGHT_START_EVENT
}
Functions
UnitAI * GetAI_npc_converted_sentry (Creature *pCreature)
void AddSC_isle_of_queldanas ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_CONVERTED_1
SAY_CONVERTED_2
SPELL_CONVERT_CREDIT
TIME_PET_DURATION
Definition at line 35 of file isle_of_queldanas.cpp.
anonymous enum
anonymous enum
Enumerator
ZONEID_ISLE_OF_QUELDANAS
NPC_SHATTERED_SUN_WARRIOR
NPC_SHATTERED_SUN_MARKSMAN
SCRIPT_TRANSFORM_ARCHER_BE_MALE
SCRIPT_TRANSFORM_ARCHER_BE_FEMALE
SCRIPT_TRANSFORM_ARCHER_DRAENEI_MALE
SCRIPT_TRANSFORM_ARCHER_DRAENEI_FEMALE
SCRIPT_TRANSFORM_WARRIOR_BE_MALE
SCRIPT_TRANSFORM_WARRIOR_BE_FEMALE
SCRIPT_TRANSFORM_WARRIOR_DRAENEI_MALE
SCRIPT_TRANSFORM_WARRIOR_DRAENEI_FEMALE
Definition at line 85 of file isle_of_queldanas.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SHOOT_BLOODELF_NW
SPELL_SHOOT_DRAENEI_NW
SPELL_SHOOT_BLOODELF_SE
SPELL_SHOOT_DRAENEI_SE
Definition at line 171 of file isle_of_queldanas.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_DAWNBLADE_BLOOD_KNIGHT
SPELL_SEAL_OF_WRATH
SPELL_JOUST
SPELL_JUDGEMENT_OF_WRATH
SPELL_HOLY_LIGHT
SPELL_FACTION_SPAR
SPELL_FACTION_SPAR_BUDDY
AREA_ID_DAWNSTAR_VILLAGE
FACTION_SPARRING_DAWNBLADE
FACTION_SPAR_BUDDY
Definition at line 239 of file isle_of_queldanas.cpp.
DawnbladeBloodKnightActions
enum DawnbladeBloodKnightActions
Enumerator
DAWNBLADE_BLOOD_KNIGHT_STOP_EVENT
DAWNBLADE_BLOOD_KNIGHT_SEAL_OF_WRATH
DAWNBLADE_BLOOD_KNIGHT_JUDGEMENT_OF_WRATH
DAWNBLADE_BLOOD_KNIGHT_HOLY_LIGHT
DAWNBLADE_BLOOD_KNIGHT_ACTION_MAX
DAWNBLADE_BLOOD_KNIGHT_START_EVENT
Definition at line 256 of file isle_of_queldanas.cpp.
Function Documentation
AddSC_isle_of_queldanas()
void AddSC_isle_of_queldanas ()
Definition at line 418 of file isle_of_queldanas.cpp.
References Script::GetAI, GetAI_npc_converted_sentry(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_converted_sentry()
UnitAI* GetAI_npc_converted_sentry (Creature * pCreature)
Definition at line 76 of file isle_of_queldanas.cpp.
Referenced by AddSC_isle_of_queldanas().