CMaNGOS_WoTLK: ItemEnchantmentMgr.cpp File Reference
ItemEnchantmentMgr.cpp File Reference
#include "Entities/ItemEnchantmentMgr.h"
#include "Database/DatabaseEnv.h"
#include "Log.h"
#include "Globals/ObjectMgr.h"
#include "Util/ProgressBar.h"
#include "Util/Util.h"
#include <list>
#include <vector>
Data Structures
struct EnchStoreItem
Typedefs
typedef std::vector< EnchStoreItem > EnchStoreList
typedef std::unordered_map< uint32, EnchStoreList > EnchantmentStore
Functions
void LoadRandomEnchantmentsTable ()
uint32 GetItemEnchantMod (uint32 entry)
uint32 GenerateEnchSuffixFactor (uint32 item_id)
Variables
static EnchantmentStore RandomItemEnch
Typedef Documentation
EnchantmentStore
typedef std::unordered_map<uint32, EnchStoreList> EnchantmentStore
Definition at line 42 of file ItemEnchantmentMgr.cpp.
EnchStoreList
typedef std::vector<EnchStoreItem> EnchStoreList
Definition at line 41 of file ItemEnchantmentMgr.cpp.
Function Documentation
GenerateEnchSuffixFactor()
uint32 GenerateEnchSuffixFactor (uint32 item_id)
Definition at line 120 of file ItemEnchantmentMgr.cpp.
References RandomPropertiesPointsEntry::EpicPropertiesPoints, ObjectMgr::GetItemPrototype(), ItemPrototype::InventoryType, INVTYPE_2HWEAPON, INVTYPE_AMMO, INVTYPE_BAG, INVTYPE_BODY, INVTYPE_CHEST, INVTYPE_CLOAK, INVTYPE_FEET, INVTYPE_FINGER, INVTYPE_HANDS, INVTYPE_HEAD, INVTYPE_HOLDABLE, INVTYPE_LEGS, INVTYPE_NECK, INVTYPE_NON_EQUIP, INVTYPE_QUIVER, INVTYPE_RANGED, INVTYPE_RANGEDRIGHT, INVTYPE_RELIC, INVTYPE_ROBE, INVTYPE_SHIELD, INVTYPE_SHOULDERS, INVTYPE_TABARD, INVTYPE_THROWN, INVTYPE_TRINKET, INVTYPE_WAIST, INVTYPE_WEAPON, INVTYPE_WEAPONMAINHAND, INVTYPE_WEAPONOFFHAND, INVTYPE_WRISTS, ITEM_QUALITY_ARTIFACT, ITEM_QUALITY_EPIC, ITEM_QUALITY_LEGENDARY, ITEM_QUALITY_RARE, ITEM_QUALITY_UNCOMMON, ItemPrototype::ItemLevel, ItemPrototype::Quality, ItemPrototype::RandomSuffix, RandomPropertiesPointsEntry::RarePropertiesPoints, sRandomPropertiesPointsStore, and RandomPropertiesPointsEntry::UncommonPropertiesPoints.
Referenced by LootItem::LootItem(), and Item::UpdateItemSuffixFactor().
GetItemEnchantMod()
uint32 GetItemEnchantMod (uint32 entry)
Definition at line 83 of file ItemEnchantmentMgr.cpp.
References irand(), rand_chance(), RandomItemEnch, and sLog.
Referenced by Item::GenerateItemRandomPropertyId(), and ObjectMgr::LoadItemPrototypes().
LoadRandomEnchantmentsTable()
void LoadRandomEnchantmentsTable ()
Definition at line 46 of file ItemEnchantmentMgr.cpp.
References QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), QueryResult::NextRow(), Database::Query(), RandomItemEnch, sLog, BarGoLink::step(), and WorldDatabase.
Referenced by ChatHandler::HandleReloadItemEnchantementsCommand(), and World::SetInitialWorldSettings().
Variable Documentation
RandomItemEnch
EnchantmentStore RandomItemEnch static
Definition at line 44 of file ItemEnchantmentMgr.cpp.
Referenced by GetItemEnchantMod(), and LoadRandomEnchantmentsTable().