CMaNGOS_WoTLK: Item.h File Reference
Item.h File Reference
#include "Common.h"
#include "Entities/Object.h"
#include "Entities/ItemPrototype.h"
Data Structures
struct ItemSetEffect
struct ItemRequiredTarget
class Item
Macros
#define MAX_VISIBLE_ITEM_OFFSET 2
#define MAX_GEM_SOCKETS MAX_ITEM_PROTO_SOCKETS
#define MAX_ENCHANTMENT_OFFSET 3
#define MAX_ITEM_REQ_TARGET_TYPE 2
Enumerations
enum InventoryResult {
EQUIP_ERR_OK = 0 , EQUIP_ERR_CANT_EQUIP_LEVEL_I = 1 , EQUIP_ERR_CANT_EQUIP_SKILL = 2 , EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT = 3 ,
EQUIP_ERR_BAG_FULL = 4 , EQUIP_ERR_NONEMPTY_BAG_OVER_OTHER_BAG = 5 , EQUIP_ERR_CANT_TRADE_EQUIP_BAGS = 6 , EQUIP_ERR_ONLY_AMMO_CAN_GO_HERE = 7 ,
EQUIP_ERR_NO_REQUIRED_PROFICIENCY = 8 , EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE = 9 , EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM = 10 , EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM2 = 11 ,
EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE2 = 12 , EQUIP_ERR_CANT_EQUIP_WITH_TWOHANDED = 13 , EQUIP_ERR_CANT_DUAL_WIELD = 14 , EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG = 15 ,
EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG2 = 16 , EQUIP_ERR_CANT_CARRY_MORE_OF_THIS = 17 , EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE3 = 18 , EQUIP_ERR_ITEM_CANT_STACK = 19 ,
EQUIP_ERR_ITEM_CANT_BE_EQUIPPED = 20 , EQUIP_ERR_ITEMS_CANT_BE_SWAPPED = 21 , EQUIP_ERR_SLOT_IS_EMPTY = 22 , EQUIP_ERR_ITEM_NOT_FOUND = 23 ,
EQUIP_ERR_CANT_DROP_SOULBOUND = 24 , EQUIP_ERR_OUT_OF_RANGE = 25 , EQUIP_ERR_TRIED_TO_SPLIT_MORE_THAN_COUNT = 26 , EQUIP_ERR_COULDNT_SPLIT_ITEMS = 27 ,
EQUIP_ERR_MISSING_REAGENT = 28 , EQUIP_ERR_NOT_ENOUGH_MONEY = 29 , EQUIP_ERR_NOT_A_BAG = 30 , EQUIP_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS = 31 ,
EQUIP_ERR_DONT_OWN_THAT_ITEM = 32 , EQUIP_ERR_CAN_EQUIP_ONLY1_QUIVER = 33 , EQUIP_ERR_MUST_PURCHASE_THAT_BAG_SLOT = 34 , EQUIP_ERR_TOO_FAR_AWAY_FROM_BANK = 35 ,
EQUIP_ERR_ITEM_LOCKED = 36 , EQUIP_ERR_YOU_ARE_STUNNED = 37 , EQUIP_ERR_YOU_ARE_DEAD = 38 , EQUIP_ERR_CANT_DO_RIGHT_NOW = 39 ,
EQUIP_ERR_INT_BAG_ERROR = 40 , EQUIP_ERR_CAN_EQUIP_ONLY1_BOLT = 41 , EQUIP_ERR_CAN_EQUIP_ONLY1_AMMOPOUCH = 42 , EQUIP_ERR_STACKABLE_CANT_BE_WRAPPED = 43 ,
EQUIP_ERR_EQUIPPED_CANT_BE_WRAPPED = 44 , EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED = 45 , EQUIP_ERR_BOUND_CANT_BE_WRAPPED = 46 , EQUIP_ERR_UNIQUE_CANT_BE_WRAPPED = 47 ,
EQUIP_ERR_BAGS_CANT_BE_WRAPPED = 48 , EQUIP_ERR_ALREADY_LOOTED = 49 , EQUIP_ERR_INVENTORY_FULL = 50 , EQUIP_ERR_BANK_FULL = 51 ,
EQUIP_ERR_ITEM_IS_CURRENTLY_SOLD_OUT = 52 , EQUIP_ERR_BAG_FULL3 = 53 , EQUIP_ERR_ITEM_NOT_FOUND2 = 54 , EQUIP_ERR_ITEM_CANT_STACK2 = 55 ,
EQUIP_ERR_BAG_FULL4 = 56 , EQUIP_ERR_ITEM_SOLD_OUT = 57 , EQUIP_ERR_OBJECT_IS_BUSY = 58 , EQUIP_ERR_NONE = 59 ,
EQUIP_ERR_NOT_IN_COMBAT = 60 , EQUIP_ERR_NOT_WHILE_DISARMED = 61 , EQUIP_ERR_BAG_FULL6 = 62 , EQUIP_ERR_CANT_EQUIP_RANK = 63 ,
EQUIP_ERR_CANT_EQUIP_REPUTATION = 64 , EQUIP_ERR_TOO_MANY_SPECIAL_BAGS = 65 , EQUIP_ERR_LOOT_CANT_LOOT_THAT_NOW = 66 , EQUIP_ERR_ITEM_UNIQUE_EQUIPABLE = 67 ,
EQUIP_ERR_VENDOR_MISSING_TURNINS = 68 , EQUIP_ERR_NOT_ENOUGH_HONOR_POINTS = 69 , EQUIP_ERR_NOT_ENOUGH_ARENA_POINTS = 70 , EQUIP_ERR_ITEM_MAX_COUNT_SOCKETED = 71 ,
EQUIP_ERR_MAIL_BOUND_ITEM = 72 , EQUIP_ERR_NO_SPLIT_WHILE_PROSPECTING = 73 , EQUIP_ERR_BAG_FULL7 = 74 , EQUIP_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED = 75 ,
EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED = 76 , EQUIP_ERR_TOO_MUCH_GOLD = 77 , EQUIP_ERR_NOT_DURING_ARENA_MATCH = 78 , EQUIP_ERR_CANNOT_TRADE_THAT = 79 ,
EQUIP_ERR_PERSONAL_ARENA_RATING_TOO_LOW = 80 , EQUIP_ERR_EVENT_AUTOEQUIP_BIND_CONFIRM = 81 , EQUIP_ERR_ARTEFACTS_ONLY_FOR_OWN_CHARACTERS = 82 , EQUIP_ERR_OK2 = 83 ,
EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED_IS = 84 , EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_SOCKETED_EXCEEDED_IS = 85 , EQUIP_ERR_SCALING_STAT_ITEM_LEVEL_EXCEEDED = 86 , EQUIP_ERR_PURCHASE_LEVEL_TOO_LOW = 87 ,
EQUIP_ERR_CANT_EQUIP_NEED_TALENT = 88 , EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED_IS = 89
}
enum BuyResult {
BUY_ERR_CANT_FIND_ITEM = 0 , BUY_ERR_ITEM_ALREADY_SOLD = 1 , BUY_ERR_NOT_ENOUGHT_MONEY = 2 , BUY_ERR_SELLER_DONT_LIKE_YOU = 4 ,
BUY_ERR_DISTANCE_TOO_FAR = 5 , BUY_ERR_ITEM_SOLD_OUT = 7 , BUY_ERR_CANT_CARRY_MORE = 8 , BUY_ERR_RANK_REQUIRE = 11 ,
BUY_ERR_REPUTATION_REQUIRE = 12
}
enum SellResult {
SELL_ERR_CANT_FIND_ITEM = 1 , SELL_ERR_CANT_SELL_ITEM = 2 , SELL_ERR_CANT_FIND_VENDOR = 3 , SELL_ERR_YOU_DONT_OWN_THAT_ITEM = 4 ,
SELL_ERR_UNK = 5 , SELL_ERR_ONLY_EMPTY_BAG = 6
}
enum EnchantmentSlot {
PERM_ENCHANTMENT_SLOT = 0 , TEMP_ENCHANTMENT_SLOT = 1 , SOCK_ENCHANTMENT_SLOT = 2 , SOCK_ENCHANTMENT_SLOT_2 = 3 ,
SOCK_ENCHANTMENT_SLOT_3 = 4 , BONUS_ENCHANTMENT_SLOT = 5 , PRISMATIC_ENCHANTMENT_SLOT = 6 , MAX_INSPECTED_ENCHANTMENT_SLOT = 7 ,
PROP_ENCHANTMENT_SLOT_0 = 7 , PROP_ENCHANTMENT_SLOT_1 = 8 , PROP_ENCHANTMENT_SLOT_2 = 9 , PROP_ENCHANTMENT_SLOT_3 = 10 ,
PROP_ENCHANTMENT_SLOT_4 = 11 , MAX_ENCHANTMENT_SLOT = 12
}
enum EnchantmentOffset { ENCHANTMENT_ID_OFFSET = 0 , ENCHANTMENT_DURATION_OFFSET = 1 , ENCHANTMENT_CHARGES_OFFSET = 2 }
enum EnchantmentSlotMask { ENCHANTMENT_SOULBOUND = 0x01 , ENCHANTMENT_DO_NOT_LOG = 0x02 , ENCHANTMENT_MAINHAND_ONLY = 0x04 , ENCHANTMENT_ALLOW_ENTERING_ARENA = 0x08 }
enum ItemUpdateState { ITEM_UNCHANGED = 0 , ITEM_CHANGED = 1 , ITEM_NEW = 2 , ITEM_REMOVED = 3 }
enum ItemLootUpdateState {
ITEM_LOOT_NONE = 0 , ITEM_LOOT_TEMPORARY = 1 , ITEM_LOOT_UNCHANGED = 2 , ITEM_LOOT_CHANGED = 3 ,
ITEM_LOOT_NEW = 4 , ITEM_LOOT_REMOVED = 5
}
enum ItemDynFlags {
ITEM_DYNFLAG_BINDED = 0x00000001 , ITEM_DYNFLAG_UNK1 = 0x00000002 , ITEM_DYNFLAG_UNLOCKED = 0x00000004 , ITEM_DYNFLAG_WRAPPED = 0x00000008 ,
ITEM_DYNFLAG_UNK4 = 0x00000010 , ITEM_DYNFLAG_UNK5 = 0x00000020 , ITEM_DYNFLAG_UNK6 = 0x00000040 , ITEM_DYNFLAG_UNK7 = 0x00000080 ,
ITEM_DYNFLAG_UNK8 = 0x00000100 , ITEM_DYNFLAG_READABLE = 0x00000200 , ITEM_DYNFLAG_UNK10 = 0x00000400 , ITEM_DYNFLAG_UNK11 = 0x00000800 ,
ITEM_DYNFLAG_UNK12 = 0x00001000 , ITEM_DYNFLAG_UNK13 = 0x00002000 , ITEM_DYNFLAG_UNK14 = 0x00004000 , ITEM_DYNFLAG_UNK15 = 0x00008000 ,
ITEM_DYNFLAG_UNK16 = 0x00010000 , ITEM_DYNFLAG_UNK17 = 0x00020000 , ITEM_DYNFLAG_UNK18 = 0x00040000 , ITEM_DYNFLAG_UNK19 = 0x00080000 ,
ITEM_DYNFLAG_UNK20 = 0x00100000 , ITEM_DYNFLAG_UNK21 = 0x00200000 , ITEM_DYNFLAG_UNK22 = 0x00400000 , ITEM_DYNFLAG_UNK23 = 0x00800000 ,
ITEM_DYNFLAG_UNK24 = 0x01000000 , ITEM_DYNFLAG_UNK25 = 0x02000000 , ITEM_DYNFLAG_UNK26 = 0x04000000 , ITEM_DYNFLAG_UNK27 = 0x08000000 ,
ITEM_DYNFLAG_UNK28 = 0x10000000 , ITEM_DYNFLAG_UNK29 = 0x20000000 , ITEM_DYNFLAG_UNK30 = 0x40000000 , ITEM_DYNFLAG_UNK31 = 0x80000000
}
enum ItemRequiredTargetType { ITEM_TARGET_TYPE_CREATURE = 1 , ITEM_TARGET_TYPE_DEAD = 2 }
Functions
bool ItemCanGoIntoBag (ItemPrototype const *pProto, ItemPrototype const *pBagProto)
Macro Definition Documentation
MAX_ENCHANTMENT_OFFSET
#define MAX_ENCHANTMENT_OFFSET 3
Definition at line 186 of file Item.h.
MAX_GEM_SOCKETS
#define MAX_GEM_SOCKETS MAX_ITEM_PROTO_SOCKETS
Definition at line 177 of file Item.h.
MAX_ITEM_REQ_TARGET_TYPE
#define MAX_ITEM_REQ_TARGET_TYPE 2
Definition at line 257 of file Item.h.
MAX_VISIBLE_ITEM_OFFSET
#define MAX_VISIBLE_ITEM_OFFSET 2
Definition at line 175 of file Item.h.
Enumeration Type Documentation
BuyResult
enum BuyResult
Enumerator
BUY_ERR_CANT_FIND_ITEM
BUY_ERR_ITEM_ALREADY_SOLD
BUY_ERR_NOT_ENOUGHT_MONEY
BUY_ERR_SELLER_DONT_LIKE_YOU
BUY_ERR_DISTANCE_TOO_FAR
BUY_ERR_ITEM_SOLD_OUT
BUY_ERR_CANT_CARRY_MORE
BUY_ERR_RANK_REQUIRE
BUY_ERR_REPUTATION_REQUIRE
Definition at line 132 of file Item.h.
EnchantmentOffset
enum EnchantmentOffset
Enumerator
ENCHANTMENT_ID_OFFSET
ENCHANTMENT_DURATION_OFFSET
ENCHANTMENT_CHARGES_OFFSET
Definition at line 179 of file Item.h.
EnchantmentSlot
enum EnchantmentSlot
Enumerator
PERM_ENCHANTMENT_SLOT
TEMP_ENCHANTMENT_SLOT
SOCK_ENCHANTMENT_SLOT
SOCK_ENCHANTMENT_SLOT_2
SOCK_ENCHANTMENT_SLOT_3
BONUS_ENCHANTMENT_SLOT
PRISMATIC_ENCHANTMENT_SLOT
MAX_INSPECTED_ENCHANTMENT_SLOT
PROP_ENCHANTMENT_SLOT_0
PROP_ENCHANTMENT_SLOT_1
PROP_ENCHANTMENT_SLOT_2
PROP_ENCHANTMENT_SLOT_3
PROP_ENCHANTMENT_SLOT_4
MAX_ENCHANTMENT_SLOT
Definition at line 156 of file Item.h.
EnchantmentSlotMask
enum EnchantmentSlotMask
Enumerator
ENCHANTMENT_SOULBOUND
ENCHANTMENT_DO_NOT_LOG
ENCHANTMENT_MAINHAND_ONLY
ENCHANTMENT_ALLOW_ENTERING_ARENA
Definition at line 188 of file Item.h.
InventoryResult
enum InventoryResult
Enumerator
EQUIP_ERR_OK
EQUIP_ERR_CANT_EQUIP_LEVEL_I
EQUIP_ERR_CANT_EQUIP_SKILL
EQUIP_ERR_ITEM_DOESNT_GO_TO_SLOT
EQUIP_ERR_BAG_FULL
EQUIP_ERR_NONEMPTY_BAG_OVER_OTHER_BAG
EQUIP_ERR_CANT_TRADE_EQUIP_BAGS
EQUIP_ERR_ONLY_AMMO_CAN_GO_HERE
EQUIP_ERR_NO_REQUIRED_PROFICIENCY
EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE
EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM
EQUIP_ERR_YOU_CAN_NEVER_USE_THAT_ITEM2
EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE2
EQUIP_ERR_CANT_EQUIP_WITH_TWOHANDED
EQUIP_ERR_CANT_DUAL_WIELD
EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG
EQUIP_ERR_ITEM_DOESNT_GO_INTO_BAG2
EQUIP_ERR_CANT_CARRY_MORE_OF_THIS
EQUIP_ERR_NO_EQUIPMENT_SLOT_AVAILABLE3
EQUIP_ERR_ITEM_CANT_STACK
EQUIP_ERR_ITEM_CANT_BE_EQUIPPED
EQUIP_ERR_ITEMS_CANT_BE_SWAPPED
EQUIP_ERR_SLOT_IS_EMPTY
EQUIP_ERR_ITEM_NOT_FOUND
EQUIP_ERR_CANT_DROP_SOULBOUND
EQUIP_ERR_OUT_OF_RANGE
EQUIP_ERR_TRIED_TO_SPLIT_MORE_THAN_COUNT
EQUIP_ERR_COULDNT_SPLIT_ITEMS
EQUIP_ERR_MISSING_REAGENT
EQUIP_ERR_NOT_ENOUGH_MONEY
EQUIP_ERR_NOT_A_BAG
EQUIP_ERR_CAN_ONLY_DO_WITH_EMPTY_BAGS
EQUIP_ERR_DONT_OWN_THAT_ITEM
EQUIP_ERR_CAN_EQUIP_ONLY1_QUIVER
EQUIP_ERR_MUST_PURCHASE_THAT_BAG_SLOT
EQUIP_ERR_TOO_FAR_AWAY_FROM_BANK
EQUIP_ERR_ITEM_LOCKED
EQUIP_ERR_YOU_ARE_STUNNED
EQUIP_ERR_YOU_ARE_DEAD
EQUIP_ERR_CANT_DO_RIGHT_NOW
EQUIP_ERR_INT_BAG_ERROR
EQUIP_ERR_CAN_EQUIP_ONLY1_BOLT
EQUIP_ERR_CAN_EQUIP_ONLY1_AMMOPOUCH
EQUIP_ERR_STACKABLE_CANT_BE_WRAPPED
EQUIP_ERR_EQUIPPED_CANT_BE_WRAPPED
EQUIP_ERR_WRAPPED_CANT_BE_WRAPPED
EQUIP_ERR_BOUND_CANT_BE_WRAPPED
EQUIP_ERR_UNIQUE_CANT_BE_WRAPPED
EQUIP_ERR_BAGS_CANT_BE_WRAPPED
EQUIP_ERR_ALREADY_LOOTED
EQUIP_ERR_INVENTORY_FULL
EQUIP_ERR_BANK_FULL
EQUIP_ERR_ITEM_IS_CURRENTLY_SOLD_OUT
EQUIP_ERR_BAG_FULL3
EQUIP_ERR_ITEM_NOT_FOUND2
EQUIP_ERR_ITEM_CANT_STACK2
EQUIP_ERR_BAG_FULL4
EQUIP_ERR_ITEM_SOLD_OUT
EQUIP_ERR_OBJECT_IS_BUSY
EQUIP_ERR_NONE
EQUIP_ERR_NOT_IN_COMBAT
EQUIP_ERR_NOT_WHILE_DISARMED
EQUIP_ERR_BAG_FULL6
EQUIP_ERR_CANT_EQUIP_RANK
EQUIP_ERR_CANT_EQUIP_REPUTATION
EQUIP_ERR_TOO_MANY_SPECIAL_BAGS
EQUIP_ERR_LOOT_CANT_LOOT_THAT_NOW
EQUIP_ERR_ITEM_UNIQUE_EQUIPABLE
EQUIP_ERR_VENDOR_MISSING_TURNINS
EQUIP_ERR_NOT_ENOUGH_HONOR_POINTS
EQUIP_ERR_NOT_ENOUGH_ARENA_POINTS
EQUIP_ERR_ITEM_MAX_COUNT_SOCKETED
EQUIP_ERR_MAIL_BOUND_ITEM
EQUIP_ERR_NO_SPLIT_WHILE_PROSPECTING
EQUIP_ERR_BAG_FULL7
EQUIP_ERR_ITEM_MAX_COUNT_EQUIPPED_SOCKETED
EQUIP_ERR_ITEM_UNIQUE_EQUIPPABLE_SOCKETED
EQUIP_ERR_TOO_MUCH_GOLD
EQUIP_ERR_NOT_DURING_ARENA_MATCH
EQUIP_ERR_CANNOT_TRADE_THAT
EQUIP_ERR_PERSONAL_ARENA_RATING_TOO_LOW
EQUIP_ERR_EVENT_AUTOEQUIP_BIND_CONFIRM
EQUIP_ERR_ARTEFACTS_ONLY_FOR_OWN_CHARACTERS
EQUIP_ERR_OK2
EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_COUNT_EXCEEDED_IS
EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_SOCKETED_EXCEEDED_IS
EQUIP_ERR_SCALING_STAT_ITEM_LEVEL_EXCEEDED
EQUIP_ERR_PURCHASE_LEVEL_TOO_LOW
EQUIP_ERR_CANT_EQUIP_NEED_TALENT
EQUIP_ERR_ITEM_MAX_LIMIT_CATEGORY_EQUIPPED_EXCEEDED_IS
Definition at line 38 of file Item.h.
ItemDynFlags
enum ItemDynFlags
Enumerator
ITEM_DYNFLAG_BINDED
ITEM_DYNFLAG_UNK1
ITEM_DYNFLAG_UNLOCKED
ITEM_DYNFLAG_WRAPPED
ITEM_DYNFLAG_UNK4
ITEM_DYNFLAG_UNK5
ITEM_DYNFLAG_UNK6
ITEM_DYNFLAG_UNK7
ITEM_DYNFLAG_UNK8
ITEM_DYNFLAG_READABLE
ITEM_DYNFLAG_UNK10
ITEM_DYNFLAG_UNK11
ITEM_DYNFLAG_UNK12
ITEM_DYNFLAG_UNK13
ITEM_DYNFLAG_UNK14
ITEM_DYNFLAG_UNK15
ITEM_DYNFLAG_UNK16
ITEM_DYNFLAG_UNK17
ITEM_DYNFLAG_UNK18
ITEM_DYNFLAG_UNK19
ITEM_DYNFLAG_UNK20
ITEM_DYNFLAG_UNK21
ITEM_DYNFLAG_UNK22
ITEM_DYNFLAG_UNK23
ITEM_DYNFLAG_UNK24
ITEM_DYNFLAG_UNK25
ITEM_DYNFLAG_UNK26
ITEM_DYNFLAG_UNK27
ITEM_DYNFLAG_UNK28
ITEM_DYNFLAG_UNK29
ITEM_DYNFLAG_UNK30
ITEM_DYNFLAG_UNK31
Definition at line 215 of file Item.h.
ItemLootUpdateState
enum ItemLootUpdateState
Enumerator
ITEM_LOOT_NONE
ITEM_LOOT_TEMPORARY
ITEM_LOOT_UNCHANGED
ITEM_LOOT_CHANGED
ITEM_LOOT_NEW
ITEM_LOOT_REMOVED
Definition at line 204 of file Item.h.
ItemRequiredTargetType
enum ItemRequiredTargetType
Enumerator
ITEM_TARGET_TYPE_CREATURE
ITEM_TARGET_TYPE_DEAD
Definition at line 251 of file Item.h.
ItemUpdateState
enum ItemUpdateState
Enumerator
ITEM_UNCHANGED
ITEM_CHANGED
ITEM_NEW
ITEM_REMOVED
Definition at line 196 of file Item.h.
SellResult
enum SellResult
Enumerator
SELL_ERR_CANT_FIND_ITEM
SELL_ERR_CANT_SELL_ITEM
SELL_ERR_CANT_FIND_VENDOR
SELL_ERR_YOU_DONT_OWN_THAT_ITEM
SELL_ERR_UNK
SELL_ERR_ONLY_EMPTY_BAG
Definition at line 145 of file Item.h.
Function Documentation
ItemCanGoIntoBag()
bool ItemCanGoIntoBag (ItemPrototype const * pProto, ItemPrototype const * pBagProto)
Definition at line 135 of file Item.cpp.
References BAG_FAMILY_MASK_ARROWS, BAG_FAMILY_MASK_BULLETS, BAG_FAMILY_MASK_ENCHANTING_SUPP, BAG_FAMILY_MASK_ENGINEERING_SUPP, BAG_FAMILY_MASK_GEMS, BAG_FAMILY_MASK_HERBS, BAG_FAMILY_MASK_INSCRIPTION_SUPP, BAG_FAMILY_MASK_LEATHERWORKING_SUPP, BAG_FAMILY_MASK_MINING_SUPP, BAG_FAMILY_MASK_SOUL_SHARDS, ItemPrototype::BagFamily, ItemPrototype::Class, ITEM_CLASS_CONTAINER, ITEM_CLASS_QUIVER, ITEM_SUBCLASS_AMMO_POUCH, ITEM_SUBCLASS_CONTAINER, ITEM_SUBCLASS_ENCHANTING_CONTAINER, ITEM_SUBCLASS_ENGINEERING_CONTAINER, ITEM_SUBCLASS_GEM_CONTAINER, ITEM_SUBCLASS_HERB_CONTAINER, ITEM_SUBCLASS_INSCRIPTION_CONTAINER, ITEM_SUBCLASS_LEATHERWORKING_CONTAINER, ITEM_SUBCLASS_MINING_CONTAINER, ITEM_SUBCLASS_QUIVER, ITEM_SUBCLASS_SOUL_CONTAINER, and ItemPrototype::SubClass.
Referenced by Player::_CanStoreItem_InBag(), Player::_CanStoreItem_InSpecificSlot(), Player::CanStoreItems(), and Player::SwapItem().