CMaNGOS_WoTLK: item_scripts.cpp File Reference
item_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Spell.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct AshbringerItemAura
struct X52RocketHelmetAura
struct PowerCircleAura
struct GDRChannel
struct GDRPeriodicDamage
struct OgrilaFlasks
struct ReducedProcChancePast60
struct BanishExile
struct OrbOfDeception
Enumerations
enum { SPELL_DOMINION_SOUL = 16053 , NPC_EMBERSTRIFE = 10321 }
enum { SPELL_ARCANE_CHARGES = 45072 }
enum { NPC_TH_DIRE_WOLF = 20748 , SPELL_GORDREKS_OINTMENT = 32578 }
enum { SPELL_ASHBRINGER_EFFECT_001 = 28442 }
enum { SPELL_PETROV_BOMB = 42406 , AREA_ID_SHATTERED_STRAITS = 4064 , ZONE_ID_HOWLING = 495 }
enum { SPELL_PARACHUTE = 37897 }
enum { SPELL_LIMITLESS_POWER = 45044 }
enum { SPELL_GDR_PERIODIC_DAMAGE = 13493 , SPELL_GDR_DAMAGE_HIT = 13279 }
Functions
bool ItemUse_item_orb_of_draconic_energy (Player *pPlayer, Item *pItem, const SpellCastTargets &)
bool ItemUse_item_arcane_charges (Player *pPlayer, Item *pItem, const SpellCastTargets &)
bool ItemUse_item_flying_machine (Player *pPlayer, Item *pItem, const SpellCastTargets &)
bool ItemUse_item_gor_dreks_ointment (Player *pPlayer, Item *pItem, const SpellCastTargets &pTargets)
bool ItemUse_item_petrov_cluster_bombs (Player *pPlayer, Item *pItem, const SpellCastTargets &)
void AddSC_item_scripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_DOMINION_SOUL
NPC_EMBERSTRIFE
Definition at line 40 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ARCANE_CHARGES
Definition at line 70 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_TH_DIRE_WOLF
SPELL_GORDREKS_OINTMENT
Definition at line 113 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ASHBRINGER_EFFECT_001
Definition at line 134 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_PETROV_BOMB
AREA_ID_SHATTERED_STRAITS
ZONE_ID_HOWLING
Definition at line 158 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_PARACHUTE
Definition at line 183 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_LIMITLESS_POWER
Definition at line 200 of file item_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GDR_PERIODIC_DAMAGE
SPELL_GDR_DAMAGE_HIT
Definition at line 217 of file item_scripts.cpp.
Function Documentation
AddSC_item_scripts()
void AddSC_item_scripts ()
Definition at line 355 of file item_scripts.cpp.
References ItemUse_item_arcane_charges(), ItemUse_item_flying_machine(), ItemUse_item_gor_dreks_ointment(), ItemUse_item_orb_of_draconic_energy(), ItemUse_item_petrov_cluster_bombs(), Script::Name, Script::pItemUse, and Script::RegisterSelf().
Referenced by AddScripts().
ItemUse_item_arcane_charges()
bool ItemUse_item_arcane_charges (Player * pPlayer, Item * pItem, const SpellCastTargets &)
Definition at line 75 of file item_scripts.cpp.
References EQUIP_ERR_NONE, GetSpellStore(), Unit::IsTaxiFlying(), Spell::SendCastResult(), Player::SendEquipError(), SPELL_ARCANE_CHARGES, and SPELL_FAILED_NOT_ON_GROUND.
Referenced by AddSC_item_scripts().
ItemUse_item_flying_machine()
bool ItemUse_item_flying_machine (Player * pPlayer, Item * pItem, const SpellCastTargets &)
Definition at line 92 of file item_scripts.cpp.
References debug_log(), EQUIP_ERR_CANT_EQUIP_SKILL, Object::GetEntry(), Player::GetSkillValueBase(), Player::SendEquipError(), and SKILL_RIDING.
Referenced by AddSC_item_scripts().
ItemUse_item_gor_dreks_ointment()
bool ItemUse_item_gor_dreks_ointment (Player * pPlayer, Item * pItem, const SpellCastTargets & pTargets)
Definition at line 119 of file item_scripts.cpp.
References EQUIP_ERR_NONE, GetSpellStore(), Object::GetTypeId(), SpellCastTargets::getUnitTarget(), Unit::HasAura(), Spell::SendCastResult(), Player::SendEquipError(), SPELL_FAILED_TARGET_AURASTATE, SPELL_GORDREKS_OINTMENT, and TYPEID_UNIT.
Referenced by AddSC_item_scripts().
ItemUse_item_orb_of_draconic_energy()
bool ItemUse_item_orb_of_draconic_energy (Player * pPlayer, Item * pItem, const SpellCastTargets &)
Definition at line 46 of file item_scripts.cpp.
References EQUIP_ERR_NONE, GetClosestCreatureWithEntry(), Unit::GetHealthPercent(), GetSpellStore(), Unit::HasAura(), NPC_EMBERSTRIFE, Spell::SendCastResult(), Player::SendEquipError(), SPELL_DOMINION_SOUL, and SPELL_FAILED_TARGET_AURASTATE.
Referenced by AddSC_item_scripts().
ItemUse_item_petrov_cluster_bombs()
bool ItemUse_item_petrov_cluster_bombs (Player * pPlayer, Item * pItem, const SpellCastTargets &)
Definition at line 165 of file item_scripts.cpp.
References AREA_ID_SHATTERED_STRAITS, EQUIP_ERR_NONE, WorldObject::GetAreaId(), GetSpellStore(), WorldObject::GetTransport(), WorldObject::GetZoneId(), Spell::SendCastResult(), Player::SendEquipError(), SPELL_FAILED_NOT_HERE, SPELL_PETROV_BOMB, and ZONE_ID_HOWLING.
Referenced by AddSC_item_scripts().