CMaNGOS_WoTLK: karazhanScripts.cpp File Reference
karazhanScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "karazhan.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_barnesAI
struct npc_image_of_medivhAI
struct npc_image_arcanagosAI
struct BlinkArcaneAnomaly
struct WrathOfTheTitansStacker
struct WrathOfTheTitansProcAura
struct HealingTouchHorses
struct WhipFrenzyHorses
Enumerations
enum {
SAY_BARNES_EVENT_START = -1532115 , SAY_BARNES_OZ_1 = -1532103 , SAY_BARNES_OZ_2 = -1532104 , SAY_BARNES_OZ_3 = -1532105 ,
SAY_BARNES_OZ_4 = -1532106 , SAY_BARNES_HOOD_1 = -1532107 , SAY_BARNES_HOOD_2 = -1532108 , SAY_BARNES_HOOD_3 = -1532109 ,
SAY_BARNES_HOOD_4 = -1532110 , SAY_BARNES_RAJ_1 = -1532111 , SAY_BARNES_RAJ_2 = -1532112 , SAY_BARNES_RAJ_3 = -1532113 ,
SAY_BARNES_RAJ_4 = -1532114 , GOSSIP_ITEM_OPERA_1 = -3532001 , GOSSIP_ITEM_OPERA_2 = -3532002 , GOSSIP_ITEM_JUL_WIPE = -3532003 ,
GOSSIP_ITEM_WOLF_WIPE = -3532004 , GOSSIP_ITEM_OPERA_OZ_WIPE = -3532019 , TEXT_ID_MOROES_ALIVE = 8969 , TEXT_ID_OPERA_1 = 8970 ,
TEXT_ID_OPERA_2 = 8971 , TEXT_ID_OPERA_WOLF_WIPE = 8975 , TEXT_ID_OPERA_OZ_WIPE = 8981 , TEXT_ID_OPERA_JUL_WIPE = 8982 ,
TEXT_ID_OPERA_DONE = 10471 , SPELL_TUXEDO = 32616 , NPC_SPOTLIGHT = 19525
}
enum {
SAY_MEDIVH_1 = -1532116 , SAY_ARCANAGOS_2 = -1532117 , SAY_MEDIVH_3 = -1532118 , SAY_ARCANAGOS_4 = -1532119 ,
SAY_MEDIVH_5 = -1532120 , SAY_ARCANAGOS_6 = -1532121 , EMOTE_CAST_SPELL = -1532122 , SAY_ARCANAGOS_7 = -1532123 ,
SAY_MEDIVH_8 = -1532124 , SPELL_REFLECTION = 30969 , SPELL_FIREBALL_REFLECT = 30971 , SPELL_CONFLAG_BLAST = 30977 ,
SPELL_EVOCATION = 30972 , SPELL_FIREBALL = 30967 , SPELL_MANA_SHIELD = 30973 , QUEST_MASTERS_TERRACE = 9645 ,
POINT_ID_INTRO = 1 , POINT_ID_DESPAWN = 2
}
enum { SPELL_BLINK = 29884 }
Functions
UnitAI * GetAI_npc_barnesAI (Creature *pCreature)
bool GossipHello_npc_barnes (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_barnes (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_image_of_medivhAI (Creature *pCreature)
UnitAI * GetAI_npc_image_arcanagosAI (Creature *pCreature)
bool ProcessEventId_event_spell_medivh_journal (uint32, Object *pSource, Object *, bool bIsStart)
void AddSC_karazhan ()
Variables
static const DialogueEntry aIntroDialogue []
static const float afMedivhSpawnLoc [4] = { -11153.18f, -1889.65f, 91.47f, 2.07f}
static const float afMedivhExitLoc [3] = { -11121.81f, -1881.24f, 91.47f}
static const float afArcanagosSpawnLoc [4] = { -11242.66f, -1778.55f, 125.35f, 0.0f}
static const float afArcanagosMoveLoc [3] = { -11170.28f, -1865.09f, 125.35f}
static const float afArcanagosFleeLoc [3] = { -11003.70f, -1760.18f, 180.25f}
static const DialogueEntry aMedivhDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_BARNES_EVENT_START
SAY_BARNES_OZ_1
SAY_BARNES_OZ_2
SAY_BARNES_OZ_3
SAY_BARNES_OZ_4
SAY_BARNES_HOOD_1
SAY_BARNES_HOOD_2
SAY_BARNES_HOOD_3
SAY_BARNES_HOOD_4
SAY_BARNES_RAJ_1
SAY_BARNES_RAJ_2
SAY_BARNES_RAJ_3
SAY_BARNES_RAJ_4
GOSSIP_ITEM_OPERA_1
GOSSIP_ITEM_OPERA_2
GOSSIP_ITEM_JUL_WIPE
GOSSIP_ITEM_WOLF_WIPE
GOSSIP_ITEM_OPERA_OZ_WIPE
TEXT_ID_MOROES_ALIVE
TEXT_ID_OPERA_1
TEXT_ID_OPERA_2
TEXT_ID_OPERA_WOLF_WIPE
TEXT_ID_OPERA_OZ_WIPE
TEXT_ID_OPERA_JUL_WIPE
TEXT_ID_OPERA_DONE
SPELL_TUXEDO
NPC_SPOTLIGHT
Definition at line 40 of file karazhanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MEDIVH_1
SAY_ARCANAGOS_2
SAY_MEDIVH_3
SAY_ARCANAGOS_4
SAY_MEDIVH_5
SAY_ARCANAGOS_6
EMOTE_CAST_SPELL
SAY_ARCANAGOS_7
SAY_MEDIVH_8
SPELL_REFLECTION
SPELL_FIREBALL_REFLECT
SPELL_CONFLAG_BLAST
SPELL_EVOCATION
SPELL_FIREBALL
SPELL_MANA_SHIELD
QUEST_MASTERS_TERRACE
POINT_ID_INTRO
POINT_ID_DESPAWN
Definition at line 291 of file karazhanScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BLINK
Definition at line 508 of file karazhanScripts.cpp.
Function Documentation
AddSC_karazhan()
void AddSC_karazhan ()
Definition at line 592 of file karazhanScripts.cpp.
References Script::GetAI, GetAI_npc_barnesAI(), GetAI_npc_image_arcanagosAI(), GetAI_npc_image_of_medivhAI(), GossipHello_npc_barnes(), GossipSelect_npc_barnes(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_medivh_journal(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_barnesAI()
UnitAI* GetAI_npc_barnesAI (Creature * pCreature)
Definition at line 180 of file karazhanScripts.cpp.
Referenced by AddSC_karazhan().
GetAI_npc_image_arcanagosAI()
UnitAI* GetAI_npc_image_arcanagosAI (Creature * pCreature)
Definition at line 481 of file karazhanScripts.cpp.
Referenced by AddSC_karazhan().
GetAI_npc_image_of_medivhAI()
UnitAI* GetAI_npc_image_of_medivhAI (Creature * pCreature)
Definition at line 447 of file karazhanScripts.cpp.
Referenced by AddSC_karazhan().
GossipHello_npc_barnes()
bool GossipHello_npc_barnes (Player * pPlayer, Creature * pCreature)
Definition at line 185 of file karazhanScripts.cpp.
References DONE, FAIL, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ICON_DOT, GOSSIP_ITEM_JUL_WIPE, GOSSIP_ITEM_OPERA_1, GOSSIP_ITEM_OPERA_OZ_WIPE, GOSSIP_ITEM_WOLF_WIPE, GOSSIP_SENDER_MAIN, IN_PROGRESS, Player::IsGameMaster(), NOT_STARTED, OPERA_EVENT_RED_RIDING_HOOD, OPERA_EVENT_ROMULO_AND_JUL, OPERA_EVENT_WIZARD_OZ, TEXT_ID_MOROES_ALIVE, TEXT_ID_OPERA_1, TEXT_ID_OPERA_DONE, TEXT_ID_OPERA_JUL_WIPE, TEXT_ID_OPERA_OZ_WIPE, TEXT_ID_OPERA_WOLF_WIPE, TYPE_MOROES, TYPE_OPERA, and TYPE_OPERA_PERFORMANCE.
Referenced by AddSC_karazhan().
GossipSelect_npc_barnes()
bool GossipSelect_npc_barnes (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 242 of file karazhanScripts.cpp.
References Creature::AI(), DoScriptText(), Object::GetGuidStr(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_OPERA_2, GOSSIP_SENDER_MAIN, OPERA_EVENT_RED_RIDING_HOOD, OPERA_EVENT_ROMULO_AND_JUL, OPERA_EVENT_WIZARD_OZ, outstring_log(), SAY_BARNES_EVENT_START, TEXT_ID_OPERA_2, and TYPE_OPERA_PERFORMANCE.
Referenced by AddSC_karazhan().
ProcessEventId_event_spell_medivh_journal()
bool ProcessEventId_event_spell_medivh_journal (uint32 , Object * pSource, Object * , bool bIsStart)
Definition at line 490 of file karazhanScripts.cpp.
References afArcanagosSpawnLoc, afMedivhSpawnLoc, Object::GetObjectGuid(), Object::GetTypeId(), NPC_IMAGE_OF_ARCANAGOS, NPC_IMAGE_OF_MEDIVH, TEMPSPAWN_DEAD_DESPAWN, and TYPEID_PLAYER.
Referenced by AddSC_karazhan().
Variable Documentation
afArcanagosFleeLoc
const float afArcanagosFleeLoc[3] = { -11003.70f, -1760.18f, 180.25f} static
Definition at line 338 of file karazhanScripts.cpp.
Referenced by npc_image_of_medivhAI::JustDidDialogueStep().
afArcanagosMoveLoc
const float afArcanagosMoveLoc[3] = { -11170.28f, -1865.09f, 125.35f} static
Definition at line 337 of file karazhanScripts.cpp.
Referenced by npc_image_of_medivhAI::JustSummoned().
afArcanagosSpawnLoc
const float afArcanagosSpawnLoc[4] = { -11242.66f, -1778.55f, 125.35f, 0.0f} static
Definition at line 336 of file karazhanScripts.cpp.
Referenced by ProcessEventId_event_spell_medivh_journal().
afMedivhExitLoc
const float afMedivhExitLoc[3] = { -11121.81f, -1881.24f, 91.47f} static
Definition at line 334 of file karazhanScripts.cpp.
Referenced by npc_image_of_medivhAI::SummonedMovementInform().
afMedivhSpawnLoc
const float afMedivhSpawnLoc[4] = { -11153.18f, -1889.65f, 91.47f, 2.07f} static
Definition at line 333 of file karazhanScripts.cpp.
Referenced by ProcessEventId_event_spell_medivh_journal().
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SAY_BARNES_OZ_1,   NPC_BARNES,  6000},
    {SAY_BARNES_OZ_2,   NPC_BARNES,  18000},
    {SAY_BARNES_OZ_3,   NPC_BARNES,  9000},
    {SAY_BARNES_OZ_4,   NPC_BARNES,  15000},
    {OPERA_EVENT_WIZARD_OZ, 0,       0},
    {SAY_BARNES_HOOD_1, NPC_BARNES,  6000},
    {SAY_BARNES_HOOD_2, NPC_BARNES,  10000},
    {SAY_BARNES_HOOD_3, NPC_BARNES,  14000},
    {SAY_BARNES_HOOD_4, NPC_BARNES,  15000},
    {OPERA_EVENT_RED_RIDING_HOOD, 0, 0},
    {SAY_BARNES_RAJ_1,  NPC_BARNES,  5000},
    {SAY_BARNES_RAJ_2,  NPC_BARNES,  7000},
    {SAY_BARNES_RAJ_3,  NPC_BARNES,  14000},
    {SAY_BARNES_RAJ_4,  NPC_BARNES,  14000},
    {OPERA_EVENT_ROMULO_AND_JUL, 0,  0},
    {0, 0, 0},
}
Definition at line 80 of file karazhanScripts.cpp.
aMedivhDialogue
const DialogueEntry aMedivhDialogue[] static
Initial value:
=
{
    {NPC_IMAGE_OF_MEDIVH,   0,                      10000},
    {SAY_MEDIVH_1,          NPC_IMAGE_OF_MEDIVH,    6000},
    {SAY_ARCANAGOS_2,       NPC_IMAGE_OF_ARCANAGOS, 10000},
    {SAY_MEDIVH_3,          NPC_IMAGE_OF_MEDIVH,    6000},
    {SAY_ARCANAGOS_4,       NPC_IMAGE_OF_ARCANAGOS, 8000},
    {SAY_MEDIVH_5,          NPC_IMAGE_OF_MEDIVH,    7000},
    {SAY_ARCANAGOS_6,       NPC_IMAGE_OF_ARCANAGOS, 0},
    {SPELL_MANA_SHIELD,     0,                      4000},
    {EMOTE_CAST_SPELL,      NPC_IMAGE_OF_MEDIVH,    5000},
    {SPELL_CONFLAG_BLAST,   0,                      1000},
    {SAY_ARCANAGOS_7,       NPC_IMAGE_OF_ARCANAGOS, 10000},
    {SAY_MEDIVH_8,          NPC_IMAGE_OF_MEDIVH,    0},
    {0, 0, 0},
}
Definition at line 340 of file karazhanScripts.cpp.