CMaNGOS_WoTLK: Level2.cpp File Reference
Level2.cpp File Reference
#include "BattleGround.h"
#include "Common.h"
#include "Database/DatabaseEnv.h"
#include "Server/DBCStores.h"
#include "Globals/ObjectMgr.h"
#include "Entities/ObjectGuid.h"
#include "Entities/Item.h"
#include "Entities/Player.h"
#include "Entities/TemporarySpawn.h"
#include "Entities/Totem.h"
#include "Entities/Pet.h"
#include "AI/BaseAI/CreatureAI.h"
#include "Entities/GameObject.h"
#include "Server/Opcodes.h"
#include "Chat/Chat.h"
#include "Globals/ObjectAccessor.h"
#include "Maps/MapManager.h"
#include "Tools/Language.h"
#include "World/World.h"
#include "GameEvents/GameEventMgr.h"
#include "Spells/SpellMgr.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Accounts/AccountMgr.h"
#include "GMTickets/GMTicketMgr.h"
#include "MotionGenerators/WaypointManager.h"
#include "Util/Util.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/CellImpl.h"
#include "MotionGenerators/WaypointMovementGenerator.h"
#include "MotionGenerators/TargetedMovementGenerator.h"
#include "MotionGenerators/MoveMap.h"
#include "MotionGenerators/PathFinder.h"
#include "Movement/MoveSplineInit.h"
#include "Anticheat/Anticheat.hpp"
#include "Entities/Transports.h"
#include <fstream>
#include <map>
#include <typeinfo>
Enumerations
enum CreatureLinkType { CREATURE_LINK_RAW = -1 , CREATURE_LINK_GUID = 0 , CREATURE_LINK_ENTRY = 1 }
enum GameobjectLinkType { GAMEOBJECT_LINK_RAW = -1 , GAMEOBJECT_LINK_GUID = 0 , GAMEOBJECT_LINK_ENTRY = 1 }
Functions
Creature * Helper_CreateWaypointFor (Creature *wpOwner, WaypointPathOrigin wpOrigin, int32 pathId, uint32 wpId, WaypointNode const *wpNode)
Helper function.
void UnsummonVisualWaypoints (Player const *player, ObjectGuid ownerGuid)
Variables
static uint32 ReputationRankStrIndex [MAX_REPUTATION_RANK]
static char const *const areatriggerKeys []
static char const *const creatureKeys []
static char const *const gameobjectKeys []
Enumeration Type Documentation
CreatureLinkType
enum CreatureLinkType
Enumerator
CREATURE_LINK_RAW
CREATURE_LINK_GUID
CREATURE_LINK_ENTRY
Definition at line 486 of file Level2.cpp.
GameobjectLinkType
enum GameobjectLinkType
Enumerator
GAMEOBJECT_LINK_RAW
GAMEOBJECT_LINK_GUID
GAMEOBJECT_LINK_ENTRY
Definition at line 693 of file Level2.cpp.
Function Documentation
Helper_CreateWaypointFor()
Creature* Helper_CreateWaypointFor (Creature * wpOwner, WaypointPathOrigin wpOrigin, int32 pathId, uint32 wpId, WaypointNode const * wpNode) inline
Helper function.
Definition at line 2982 of file Level2.cpp.
References TempSpawnSettings::activeObject, TempSpawnSettings::despawnTime, TempSpawnSettings::entry, WorldObject::GetMap(), WorldObject::GetPhaseMask(), IN_MILLISECONDS, MINUTE, TempSpawnSettings::ori, WaypointNode::orientation, TempSpawnSettings::pathOrigin, Unit::SetLevel(), TempSpawnSettings::spawnDataEntry, TempSpawnSettings::spawner, TempSpawnSettings::spawnPathId, TempSpawnSettings::spawnType, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, TempSpawnSettings::tempSpawnMovegen, VISUAL_WAYPOINT, TempSpawnSettings::waypointId, TempSpawnSettings::x, WaypointNode::x, TempSpawnSettings::y, WaypointNode::y, TempSpawnSettings::z, and WaypointNode::z.
Referenced by ChatHandler::HandleWpAddCommand(), ChatHandler::HandleWpModifyCommand(), and ChatHandler::HandleWpShowCommand().
UnsummonVisualWaypoints()
void UnsummonVisualWaypoints (Player const * player, ObjectGuid ownerGuid) inline
Definition at line 3006 of file Level2.cpp.
References CREATURE_SUBTYPE_TEMPORARY_SUMMON, TemporarySpawn::GetSpawnerGuid(), SIZE_OF_GRIDS, TemporarySpawn::UnSummon(), Cell::VisitGridObjects(), and VISUAL_WAYPOINT.
Referenced by ChatHandler::HandleWpAddCommand(), and ChatHandler::HandleWpShowCommand().
Variable Documentation
areatriggerKeys
char const* const areatriggerKeys[] static
Initial value:
=
{
    "Hareatrigger",
    "Hareatrigger_target",
    nullptr
}
Definition at line 415 of file Level2.cpp.
Referenced by ChatHandler::HandleGoTriggerCommand().
creatureKeys
char const* const creatureKeys[] static
Initial value:
=
{
    "Hcreature",
    "Hcreature_entry",
    nullptr
}
Definition at line 493 of file Level2.cpp.
Referenced by ChatHandler::HandleGoCreatureCommand().
gameobjectKeys
char const* const gameobjectKeys[] static
Initial value:
=
{
    "Hgameobject",
    "Hgameobject_entry",
    nullptr
}
Definition at line 700 of file Level2.cpp.
Referenced by ChatHandler::HandleGoObjectCommand().
ReputationRankStrIndex
uint32 ReputationRankStrIndex[MAX_REPUTATION_RANK] static
Initial value:
=
{
    LANG_REP_HATED,    LANG_REP_HOSTILE, LANG_REP_UNFRIENDLY, LANG_REP_NEUTRAL,
    LANG_REP_FRIENDLY, LANG_REP_HONORED, LANG_REP_REVERED,    LANG_REP_EXALTED
}
Definition at line 60 of file Level2.cpp.
Referenced by ChatHandler::HandleModifyRepCommand(), and ChatHandler::ShowFactionListHelper().