CMaNGOS_WoTLK: Level3.cpp File Reference
Level3.cpp File Reference
#include "Common.h"
#include "Database/DatabaseEnv.h"
#include "Server/WorldSession.h"
#include "World/World.h"
#include "Globals/ObjectMgr.h"
#include "Accounts/AccountMgr.h"
#include "Tools/PlayerDump.h"
#include "Spells/SpellMgr.h"
#include "Entities/Player.h"
#include "Entities/GameObject.h"
#include "Chat/Chat.h"
#include "Log.h"
#include "Guilds/Guild.h"
#include "Guilds/GuildMgr.h"
#include "Globals/ObjectAccessor.h"
#include "Maps/MapManager.h"
#include "Mails/MassMailMgr.h"
#include "DBScripts/ScriptMgr.h"
#include "Tools/Language.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/CellImpl.h"
#include "Weather/Weather.h"
#include "MotionGenerators/PointMovementGenerator.h"
#include "MotionGenerators/PathFinder.h"
#include "MotionGenerators/TargetedMovementGenerator.h"
#include "Skills/SkillDiscovery.h"
#include "Skills/SkillExtraItems.h"
#include "SystemConfig.h"
#include "Config/Config.h"
#include "Mails/Mail.h"
#include "Util/Util.h"
#include "Entities/ItemEnchantmentMgr.h"
#include "BattleGround/BattleGroundMgr.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Maps/InstanceData.h"
#include "AI/EventAI/CreatureEventAIMgr.h"
#include "Server/DBCEnums.h"
#include "Server/SQLStorages.h"
#include "Loot/LootMgr.h"
#include "World/WorldState.h"
#include "Arena/ArenaTeam.h"
#include "Server/PacketLog.h"
#include "Globals/UnitCondition.h"
#include "Globals/CombatCondition.h"
#include "World/WorldStateExpression.h"
Enumerations
enum ModSpells {
SPELL_MOD_STRENGTH = 13372 , SPELL_MOD_AGILITY = 13365 , SPELL_MOD_STAMINA = 13370 , SPELL_MOD_INTELLECT = 13366 ,
SPELL_MOD_SPIRIT = 13368 , SPELL_MOD_SPELL_POWER = 22747 , SPELL_MOD_ARMOR = 15170 , SPELL_MOD_RES_HOLY = 15171 ,
SPELL_MOD_RES_FIRE = 15172 , SPELL_MOD_RES_NATURE = 15173 , SPELL_MOD_RES_FROST = 15174 , SPELL_MOD_RES_SHADOW = 15175 ,
SPELL_MOD_RES_ARCANE = 15176 , SPELL_MOD_MELEE_AP = 15177 , SPELL_MOD_RANGE_AP = 15178 , SPELL_MOD_MELEE_CRIT = 15179 ,
SPELL_MOD_SPELL_CRIT = 15180 , SPELL_MOD_MELEE_HASTE = 15181 , SPELL_MOD_RANGE_HASTE = 15182 , SPELL_MOD_SPELL_HASTE = 15183 ,
SPELL_MOD_PARRY_CHANCE = 15184 , SPELL_MOD_DODGE_CHANCE = 15185 , SPELL_MOD_BLOCK_CHANCE = 15186
}
Functions
static bool HandleResetStatsOrLevelHelper (Player *player)
Enumeration Type Documentation
ModSpells
enum ModSpells
Enumerator
SPELL_MOD_STRENGTH
SPELL_MOD_AGILITY
SPELL_MOD_STAMINA
SPELL_MOD_INTELLECT
SPELL_MOD_SPIRIT
SPELL_MOD_SPELL_POWER
SPELL_MOD_ARMOR
SPELL_MOD_RES_HOLY
SPELL_MOD_RES_FIRE
SPELL_MOD_RES_NATURE
SPELL_MOD_RES_FROST
SPELL_MOD_RES_SHADOW
SPELL_MOD_RES_ARCANE
SPELL_MOD_MELEE_AP
SPELL_MOD_RANGE_AP
SPELL_MOD_MELEE_CRIT
SPELL_MOD_SPELL_CRIT
SPELL_MOD_MELEE_HASTE
SPELL_MOD_RANGE_HASTE
SPELL_MOD_SPELL_HASTE
SPELL_MOD_PARRY_CHANCE
SPELL_MOD_DODGE_CHANCE
SPELL_MOD_BLOCK_CHANCE
Definition at line 7902 of file Level3.cpp.
Function Documentation
HandleResetStatsOrLevelHelper()
static bool HandleResetStatsOrLevelHelper (Player * player) static
Definition at line 5008 of file Level3.cpp.
References DEFAULT_WORLD_OBJECT_SIZE, FORM_NONE, Unit::getClass(), Unit::getRace(), Unit::GetShapeshiftForm(), Unit::HasAuraType(), Player::InitDisplayIds(), PLAYER_FIELD_WATCHED_FACTION_INDEX, ChrClassesEntry::powerType, sChrClassesStore, Object::SetByteValue(), Player::setFactionForRace(), Object::SetFloatValue(), Object::SetInt32Value(), Unit::SetShapeshiftForm(), Object::SetUInt32Value(), sLog, SPELL_AURA_MOD_SHAPESHIFT, UNIT_BYTE2_FLAG_PVP, UNIT_BYTES_0_OFFSET_POWER_TYPE, UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_FIELD_BOUNDINGRADIUS, UNIT_FIELD_BYTES_0, UNIT_FIELD_BYTES_2, UNIT_FIELD_COMBATREACH, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by ChatHandler::HandleResetLevelCommand(), and ChatHandler::HandleResetStatsCommand().