CMaNGOS_WoTLK: loch_modan.cpp File Reference
loch_modan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct Location
struct npc_miranAI
Enumerations
enum {
QUEST_PROTECTING_THE_SHIPMENT = 309 , SAY_MIRAN_1 = -1000571 , SAY_DARK_IRON_DWARF = -1000572 , SAY_MIRAN_2 = -1000573 ,
SAY_MIRAN_3 = -1000574 , NPC_DARK_IRON_DWARF = 2149
}
Functions
bool QuestAccept_npc_miran (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_miran (Creature *pCreature)
void AddSC_loch_modan ()
Variables
static const Location m_afAmbushSpawn []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_PROTECTING_THE_SHIPMENT
SAY_MIRAN_1
SAY_DARK_IRON_DWARF
SAY_MIRAN_2
SAY_MIRAN_3
NPC_DARK_IRON_DWARF
Definition at line 35 of file loch_modan.cpp.
Function Documentation
AddSC_loch_modan()
void AddSC_loch_modan ()
Definition at line 130 of file loch_modan.cpp.
References Script::GetAI, GetAI_npc_miran(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_miran(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_miran()
UnitAI* GetAI_npc_miran (Creature * pCreature)
Definition at line 125 of file loch_modan.cpp.
Referenced by AddSC_loch_modan().
QuestAccept_npc_miran()
bool QuestAccept_npc_miran (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 115 of file loch_modan.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_PROTECTING_THE_SHIPMENT.
Referenced by AddSC_loch_modan().
Variable Documentation
m_afAmbushSpawn
const Location m_afAmbushSpawn[] static
Initial value:
=
{
    { -5691.93f, -3745.91f, 319.159f, 2.21f},
    { -5706.98f, -3745.39f, 318.728f, 1.04f}
}
Definition at line 52 of file loch_modan.cpp.
Referenced by npc_miranAI::WaypointReached().