CMaNGOS_WoTLK: Log.cpp File Reference
Log.cpp File Reference
#include "Common.h"
#include "Log.h"
#include "Policies/Singleton.h"
#include "Config/Config.h"
#include "Util/Util.h"
#include "Util/ByteBuffer.h"
#include "Util/ProgressBar.h"
#include <fstream>
#include <iostream>
#include <thread>
#include <cstdarg>
#include <boost/stacktrace.hpp>
Enumerations
enum LogType { LogNormal = 0 , LogDetails , LogDebug , LogError }
Functions
INSTANTIATE_SINGLETON_1 (Log)
void outstring_log ()
void outstring_log (const char *str,...)
void detail_log (const char *str,...)
void debug_log (const char *str,...)
void error_log (const char *str,...)
void error_db_log (const char *str,...)
void setScriptLibraryErrorFile (char const *fname, char const *libName)
void script_error_log (const char *str,...)
Variables
LogFilterData logFilterData [LOG_FILTER_COUNT]
const int LogType_count = int(LogError) + 1
Enumeration Type Documentation
LogType
enum LogType
Enumerator
LogNormal
LogDetails
LogDebug
LogError
Definition at line 61 of file Log.cpp.
Function Documentation
debug_log()
void debug_log (const char * str, ...)
Definition at line 1050 of file Log.cpp.
References DEBUG_LOG.
Referenced by npc_twiggy_flatheadAI::CanStartEvent(), npc_commander_dawnforgeAI::CanStartEvent(), boss_majordomoAI::CorpseRemoved(), instance_stratholme::DoGateTrap(), DoOrSimulateScriptTextForMap(), instance_karazhan::DoPrepareOperaStage(), instance_scholomance::DoRespawnEntranceRoom(), ScriptedInstance::DoRespawnGameObject(), instance_dark_portal::DoSpawnNextPortal(), ScriptedInstance::DoStartTimedAchievement(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUpdateWorldState(), ScriptedInstance::DoUseDoorOrButton(), FollowerAI::EnterEvadeMode(), EquippedOk(), FollowerAI::GetLeaderForFollower(), instance_old_hillsbrad::HandleThrallRelocation(), instance_blackwing_lair::InitiateBreath(), instance_blackwing_lair::InitiateDrakonid(), ItemUse_item_flying_machine(), boss_majordomoAI::JustRespawned(), dummy_dragonAI::MovementInform(), ScriptDevAIMgr::OnGossipSelect(), ScriptedPetAI::ResetPetCombat(), instance_stratholme::SetData(), instance_zulaman::SetData(), instance_mount_hyjal::SetData(), instance_old_hillsbrad::SetData(), instance_ahnkahet::SetData(), instance_gundrak::SetData(), instance_violet_hold::SetData(), instance_ramparts::SetData(), instance_violet_hold::SetPortalId(), instance_violet_hold::SetRandomBosses(), npc_escortAI::SetRun(), npc_escortAI::Start(), FollowerAI::StartFollow(), instance_stratholme::StartSlaughterSquare(), instance_stratholme::Update(), instance_zulaman::Update(), npc_escortAI::UpdateAI(), FollowerAI::UpdateAI(), and dummy_dragonAI::UpdateAI().
detail_log()
void detail_log (const char * str, ...)
Definition at line 1036 of file Log.cpp.
References sLog.
error_db_log()
void error_db_log (const char * str, ...)
Definition at line 1078 of file Log.cpp.
References sLog.
Referenced by SystemMgr::LoadScriptWaypoints(), npc_air_force_botsAI::npc_air_force_botsAI(), and npc_air_force_botsAI::SummonGuard().
error_log()
void error_log (const char * str, ...)
Definition at line 1064 of file Log.cpp.
References sLog.
Referenced by npc_regthar_deathgateAI::SpawnCreature().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (Log)
outstring_log() [1/2]
void outstring_log ()
Definition at line 1017 of file Log.cpp.
References sLog.
Referenced by ScriptDevAIMgr::CheckScriptNames(), GossipSelect_npc_barnes(), ScriptDevAIMgr::Initialize(), SystemMgr::LoadScriptGossipTexts(), SystemMgr::LoadScriptTexts(), SystemMgr::LoadScriptTextsCustom(), SystemMgr::LoadScriptWaypoints(), and SystemMgr::LoadVersion().
outstring_log() [2/2]
void outstring_log (const char * str, ...)
Definition at line 1022 of file Log.cpp.
References sLog.
script_error_log()
void script_error_log (const char * str, ...)
Definition at line 1097 of file Log.cpp.
References sLog.
Referenced by npc_anubisath_sentinelAI::Aggro(), AreaTrigger_at_frostworn_general(), npc_doctorAI::BeginEvent(), boss_baltharusAI::boss_baltharusAI(), instance_stratholme::CheckConditionCriteriaMeet(), world_map_eastern_kingdoms::CheckConditionCriteriaMeet(), instance_zulaman::CheckConditionCriteriaMeet(), world_map_kalimdor::CheckConditionCriteriaMeet(), world_map_outland::CheckConditionCriteriaMeet(), instance_blackwing_lair::CheckConditionCriteriaMeet(), instance_dark_portal::CheckConditionCriteriaMeet(), instance_mount_hyjal::CheckConditionCriteriaMeet(), instance_dire_maul::CheckConditionCriteriaMeet(), instance_obsidian_sanctum::CheckConditionCriteriaMeet(), instance_ulduar::CheckConditionCriteriaMeet(), instance_serpentshrine_cavern::CheckConditionCriteriaMeet(), instance_shattered_halls::CheckConditionCriteriaMeet(), ScriptDevAIMgr::CheckScriptNames(), DoBroadcastText(), DoOrSimulateScriptTextForMap(), ScriptedAI::DoPlaySoundToSet(), instance_karazhan::DoPrepareChessEvent(), instance_blackrock_spire::DoProcessEmberseerEvent(), instance_violet_hold::DoReleaseBoss(), instance_uldaman::DoResetKeeperEvent(), UnitAI::DoResetThreat(), npc_demolitionist_legosoAI::DoRespawnFires(), npc_demolitionist_legosoAI::DoRespawnObjects(), DoScriptText(), instance_ruins_of_ahnqiraj::DoSendNextArmyWave(), instance_halls_of_reflection::DoSendNextSpiritWave(), instance_sunwell_plateau::DoSortFlightTriggers(), boss_lady_deathwhisperAI::DoSortSummoningStalkers(), instance_violet_hold::DoSpawnIntroMob(), instance_pit_of_saron::DoSpawnTyrannusUndead(), world_map_ebon_hold::DoSpawnUndeadWave(), instance_pit_of_saron::DoStartAmbushEvent(), instance_pit_of_saron::DoStartIntroEvent(), instance_pit_of_saron::DoStartTyrannusEvent(), boss_lady_deathwhisperAI::DoSummonCultistWave(), ScriptedAI::DoTeleportPlayer(), ScriptedInstance::DoUseDoorOrButton(), EffectDummyCreature_spell_summon_reflections(), EffectScriptEffectCreature_npc_putricide(), npc_spawned_oronok_tornheartAI::EnterEvadeMode(), ScriptedInstance::GetSingleCreatureFromStorage(), BattleGround::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), npc_lazy_peonAI::GoLumberPile(), npc_khadgars_servantAI::HandleStart(), mob_arugal_voidwalkerAI::InitVoidWalkersGroup(), instance_naxxramas::IsInRightSideGothArea(), instance_trial_of_the_crusader::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), boss_eye_of_cthunAI::JustDied(), SystemMgr::LoadVersion(), boss_selin_fireheartAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_ancestral_wolfAI::npc_ancestral_wolfAI(), npc_doctorAI::PatientDied(), npc_doctorAI::PatientSaved(), Script::RegisterSelf(), npc_anubisath_sentinelAI::SetAbility(), npc_escortAI::SetCurrentWaypoint(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), instance_zulaman::SetData(), instance_ahnkahet::SetData(), instance_trial_of_the_champion::SetData(), instance_trial_of_the_crusader::SetData(), instance_gundrak::SetData(), instance_icecrown_citadel::SetData(), instance_nexus::SetData(), instance_pinnacle::SetData(), mob_arugal_voidwalkerAI::SetFollower(), mob_dragonflayer_forge_masterAI::SetMyForge(), instance_violet_hold::SetRandomBosses(), npc_escortAI::Start(), FollowerAI::StartFollow(), DialogueHelper::StartNextDialogueText(), boss_brutallusAI::SummonedCreatureJustDied(), world_map_ebon_hold::Update(), instance_halls_of_reflection::Update(), instance_pit_of_saron::Update(), boss_pyroguard_emberseerAI::UpdateAI(), npc_blackwing_orbAI::UpdateAI(), mob_big_oozeAI::UpdateAI(), boss_volkhanAI::UpdateAI(), boss_mimironAI::UpdateAI(), boss_leviathan_mk2AI::UpdateAI(), boss_xt_002AI::UpdateAI(), npc_storm_tempered_keeperAI::UpdateAI(), and npc_doctorAI::UpdateAI().
setScriptLibraryErrorFile()
void setScriptLibraryErrorFile (char const * fname, char const * libName)
Definition at line 1092 of file Log.cpp.
References sLog.
Referenced by ScriptDevAIMgr::~ScriptDevAIMgr().
Variable Documentation
logFilterData
LogFilterData logFilterData[LOG_FILTER_COUNT]
Initial value:
=
{
    { "transport_moves",     "LogFilter_TransportMoves",     true  },
    { "creature_moves",      "LogFilter_CreatureMoves",      true  },
    { "visibility_changes",  "LogFilter_VisibilityChanges",  true  },
    { "achievement_updates", "LogFilter_AchievementUpdates", true  },
    { "weather",             "LogFilter_Weather",            true  },
    { "player_stats",        "LogFilter_PlayerStats",        false },
    { "sql_text",            "LogFilter_SQLText",            true  },
    { "player_moves",        "LogFilter_PlayerMoves",        true  },
    { "periodic_effects",    "LogFilter_PeriodicAffects",    false },
    { "ai_and_movegens",     "LogFilter_AIAndMovegens",      false },
    { "damage",              "LogFilter_Damage",             false },
    { "combat",              "LogFilter_Combat",             false },
    { "spell_cast",          "LogFilter_SpellCast",          false },
    { "db_stricted_check",   "LogFilter_DbStrictedCheck",    true  },
    { "",                    "",                             true  },
    { "",                    "",                             true  },
    { "pathfinding",         "LogFilter_Pathfinding",        true  },
    { "map_loading",         "LogFilter_MapLoading",         true  },
    { "event_ai_dev",        "LogFilter_EventAiDev",         true  },
    { "calendar",            "LogFilter_Calendar",           true  },
    { "db_scripts_dev",      "LogFilter_DbScriptDev",        true  },
}
Definition at line 36 of file Log.cpp.
Referenced by ChatHandler::HandleServerLogFilterCommand(), and Log::Initialize().
LogType_count
const int LogType_count = int(LogError) + 1
Definition at line 69 of file Log.cpp.
Referenced by Log::InitColors().