CMaNGOS_WoTLK: Log.h File Reference
Log.h File Reference
#include "Common.h"
#include "Policies/Singleton.h"
#include <mutex>
Data Structures
struct LogFilterData
class Log
Macros
#define LOG_FILTER_COUNT 21
#define sLog MaNGOS::Singleton<Log>::Instance()
#define BASIC_LOG(...)
#define BASIC_FILTER_LOG(F, ...)
#define DETAIL_LOG(...)
#define DETAIL_FILTER_LOG(F, ...)
#define DEBUG_LOG(...)
#define DEBUG_FILTER_LOG(F, ...)
#define ERROR_DB_FILTER_LOG(F, ...)
#define ERROR_DB_STRICT_LOG(...) ERROR_DB_FILTER_LOG(LOG_FILTER_DB_STRICTED_CHECK, __VA_ARGS__)
Enumerations
enum LogLevel { LOG_LVL_MINIMAL = 0 , LOG_LVL_BASIC = 1 , LOG_LVL_DETAIL = 2 , LOG_LVL_DEBUG = 3 }
enum LogFilters {
LOG_FILTER_TRANSPORT_MOVES = 0x000001 , LOG_FILTER_CREATURE_MOVES = 0x000002 , LOG_FILTER_VISIBILITY_CHANGES = 0x000004 , LOG_FILTER_ACHIEVEMENT_UPDATES = 0x000008 ,
LOG_FILTER_WEATHER = 0x000010 , LOG_FILTER_PLAYER_STATS = 0x000020 , LOG_FILTER_SQL_TEXT = 0x000040 , LOG_FILTER_PLAYER_MOVES = 0x000080 ,
LOG_FILTER_PERIODIC_AFFECTS = 0x000100 , LOG_FILTER_AI_AND_MOVEGENSS = 0x000200 , LOG_FILTER_DAMAGE = 0x000400 , LOG_FILTER_COMBAT = 0x000800 ,
LOG_FILTER_SPELL_CAST = 0x001000 , LOG_FILTER_DB_STRICTED_CHECK = 0x002000 , LOG_FILTER_PATHFINDING = 0x010000 , LOG_FILTER_MAP_LOADING = 0x020000 ,
LOG_FILTER_EVENT_AI_DEV = 0x040000 , LOG_FILTER_CALENDAR = 0x080000 , LOG_FILTER_DB_SCRIPT = 0x100000
}
enum Color {
BLACK , RED , GREEN , BROWN ,
BLUE , MAGENTA , CYAN , GREY ,
YELLOW , LRED , LGREEN , LBLUE ,
LMAGENTA , LCYAN , WHITE
}
Functions
void outstring_log ()
void outstring_log (const char *str,...) ATTR_PRINTF(1
void void detail_log (const char *str,...) ATTR_PRINTF(1
void void void debug_log (const char *str,...) ATTR_PRINTF(1
void void void void error_log (const char *str,...) ATTR_PRINTF(1
void void void void void error_db_log (const char *str,...) ATTR_PRINTF(1
void void void void void void setScriptLibraryErrorFile (char const *fname, char const *libName)
void script_error_log (const char *str,...) ATTR_PRINTF(1
Variables
LogFilterData logFilterData [LOG_FILTER_COUNT]
const int Color_count = int(WHITE) + 1
Macro Definition Documentation
BASIC_FILTER_LOG
#define BASIC_FILTER_LOG (F, ...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_BASIC) && !sLog.HasLogFilter(F)) \
            sLog.outBasic(__VA_ARGS__);                 \
    } while(0)
Definition at line 244 of file Log.h.
BASIC_LOG
#define BASIC_LOG (...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_BASIC))    \
            sLog.outBasic(__VA_ARGS__);                 \
    } while(0)
Definition at line 238 of file Log.h.
DEBUG_FILTER_LOG
#define DEBUG_FILTER_LOG (F, ...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_DEBUG) && !sLog.HasLogFilter(F)) \
            sLog.outDebug(__VA_ARGS__);                 \
    } while(0)
Definition at line 268 of file Log.h.
DEBUG_LOG
#define DEBUG_LOG (...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_DEBUG))    \
            sLog.outDebug(__VA_ARGS__);                 \
    } while(0)
Definition at line 262 of file Log.h.
DETAIL_FILTER_LOG
#define DETAIL_FILTER_LOG (F, ...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_DETAIL) && !sLog.HasLogFilter(F)) \
            sLog.outDetail(__VA_ARGS__);                \
    } while(0)
Definition at line 256 of file Log.h.
DETAIL_LOG
#define DETAIL_LOG (...)
Value:
    do {                                                \
        if (sLog.HasLogLevelOrHigher(LOG_LVL_DETAIL))   \
            sLog.outDetail(__VA_ARGS__);                \
    } while(0)
Definition at line 250 of file Log.h.
ERROR_DB_FILTER_LOG
#define ERROR_DB_FILTER_LOG (F, ...)
Value:
    do {                                                \
        if (!sLog.HasLogFilter(F))                      \
            sLog.outErrorDb(__VA_ARGS__);               \
    } while(0)
Definition at line 274 of file Log.h.
ERROR_DB_STRICT_LOG
#define ERROR_DB_STRICT_LOG (...) ERROR_DB_FILTER_LOG(LOG_FILTER_DB_STRICTED_CHECK, __VA_ARGS__)
Definition at line 280 of file Log.h.
LOG_FILTER_COUNT
#define LOG_FILTER_COUNT 21
Definition at line 64 of file Log.h.
sLog
#define sLog MaNGOS::Singleton<Log>::Instance()
Definition at line 236 of file Log.h.
Enumeration Type Documentation
Color
enum Color
Enumerator
BLACK
RED
GREEN
BROWN
BLUE
MAGENTA
CYAN
GREY
YELLOW
LRED
LGREEN
LBLUE
LMAGENTA
LCYAN
WHITE
Definition at line 75 of file Log.h.
LogFilters
enum LogFilters
Enumerator
LOG_FILTER_TRANSPORT_MOVES
LOG_FILTER_CREATURE_MOVES
LOG_FILTER_VISIBILITY_CHANGES
LOG_FILTER_ACHIEVEMENT_UPDATES
LOG_FILTER_WEATHER
LOG_FILTER_PLAYER_STATS
LOG_FILTER_SQL_TEXT
LOG_FILTER_PLAYER_MOVES
LOG_FILTER_PERIODIC_AFFECTS
LOG_FILTER_AI_AND_MOVEGENSS
LOG_FILTER_DAMAGE
LOG_FILTER_COMBAT
LOG_FILTER_SPELL_CAST
LOG_FILTER_DB_STRICTED_CHECK
LOG_FILTER_PATHFINDING
LOG_FILTER_MAP_LOADING
LOG_FILTER_EVENT_AI_DEV
LOG_FILTER_CALENDAR
LOG_FILTER_DB_SCRIPT
Definition at line 39 of file Log.h.
LogLevel
enum LogLevel
Enumerator
LOG_LVL_MINIMAL
LOG_LVL_BASIC
LOG_LVL_DETAIL
LOG_LVL_DEBUG
Definition at line 30 of file Log.h.
Function Documentation
debug_log()
void void void debug_log (const char * str, ...)
detail_log()
void void detail_log (const char * str, ...)
error_db_log()
void void void void void error_db_log (const char * str, ...)
error_log()
void void void void error_log (const char * str, ...)
outstring_log() [1/2]
void outstring_log ()
Definition at line 1017 of file Log.cpp.
References sLog.
Referenced by ScriptDevAIMgr::CheckScriptNames(), GossipSelect_npc_barnes(), ScriptDevAIMgr::Initialize(), SystemMgr::LoadScriptGossipTexts(), SystemMgr::LoadScriptTexts(), SystemMgr::LoadScriptTextsCustom(), SystemMgr::LoadScriptWaypoints(), and SystemMgr::LoadVersion().
outstring_log() [2/2]
void outstring_log (const char * str, ...)
script_error_log()
void script_error_log (const char * str, ...)
setScriptLibraryErrorFile()
void void void void void void setScriptLibraryErrorFile (char const * fname, char const * libName)
Definition at line 1092 of file Log.cpp.
References sLog.
Referenced by ScriptDevAIMgr::~ScriptDevAIMgr().
Variable Documentation
Color_count
const int Color_count = int(WHITE) + 1
Definition at line 94 of file Log.h.
Referenced by Log::InitColors(), and Log::SetColor().
logFilterData
LogFilterData logFilterData[LOG_FILTER_COUNT] extern
Definition at line 36 of file Log.cpp.
Referenced by ChatHandler::HandleServerLogFilterCommand(), and Log::Initialize().