CMaNGOS_WoTLK: LootMgr.cpp File Reference
LootMgr.cpp File Reference
#include "Loot/LootMgr.h"
#include "Log.h"
#include "Globals/ObjectMgr.h"
#include "Util/ProgressBar.h"
#include "World/World.h"
#include "Util/Util.h"
#include "Globals/SharedDefines.h"
#include "Spells/SpellMgr.h"
#include "Server/DBCStores.h"
#include "Server/SQLStorages.h"
#include "Entities/ItemEnchantmentMgr.h"
#include "Tools/Language.h"
#include "BattleGround/BattleGroundMgr.h"
#include <sstream>
#include <iomanip>
Data Structures
class LootTemplate::LootGroup
Functions
INSTANTIATE_SINGLETON_1 (LootMgr)
bool IsEligibleForLoot (Player *looter, WorldObject *lootTarget)
ByteBuffer & operator<< (ByteBuffer &b, LootItem const &li)
void LoadLootTemplates_Creature ()
void LoadLootTemplates_Disenchant ()
void LoadLootTemplates_Fishing ()
void LoadLootTemplates_Gameobject ()
void LoadLootTemplates_Item ()
void LoadLootTemplates_Milling ()
void LoadLootTemplates_Pickpocketing ()
void LoadLootTemplates_Prospecting ()
void LoadLootTemplates_Mail ()
void LoadLootTemplates_Skinning ()
void LoadLootTemplates_Spell ()
void LoadLootTemplates_Reference (LootIdSet &ids_set)
void CheckLootTemplates_Reference (LootIdSet &ids_set)
Variables
static eConfigFloatValues const qualityToRate [MAX_ITEM_QUALITY]
LootStore LootTemplates_Creature ("creature_loot_template", "creature entry", true)
LootStore LootTemplates_Disenchant ("disenchant_loot_template", "item disenchant id", true)
LootStore LootTemplates_Fishing ("fishing_loot_template", "area id", true)
LootStore LootTemplates_Gameobject ("gameobject_loot_template", "gameobject lootid", true)
LootStore LootTemplates_Item ("item_loot_template", "item entry with ITEM_FLAG_LOOTABLE", true)
LootStore LootTemplates_Mail ("mail_loot_template", "mail template id", false)
LootStore LootTemplates_Milling ("milling_loot_template", "item entry (herb)", true)
LootStore LootTemplates_Pickpocketing ("pickpocketing_loot_template", "creature pickpocket lootid", true)
LootStore LootTemplates_Prospecting ("prospecting_loot_template", "item entry (ore)", true)
LootStore LootTemplates_Reference ("reference_loot_template", "reference id", false)
LootStore LootTemplates_Skinning ("skinning_loot_template", "creature skinning id", true)
LootStore LootTemplates_Spell ("spell_loot_template", "spell id (random item creating)", false)
Function Documentation
CheckLootTemplates_Reference()
void CheckLootTemplates_Reference (LootIdSet & ids_set)
Definition at line 3077 of file LootMgr.cpp.
References LootStore::CheckLootRefs(), LootTemplates_Creature, LootTemplates_Disenchant, LootTemplates_Fishing, LootTemplates_Gameobject, LootTemplates_Item, LootTemplates_Mail, LootTemplates_Milling, LootTemplates_Pickpocketing, LootTemplates_Prospecting, LootTemplates_Reference, LootTemplates_Skinning, LootTemplates_Spell, LootStore::ReportUnusedIds(), and sBattleGroundMgr.
Referenced by ChatHandler::HandleReloadLootTemplatesReferenceCommand(), and World::SetInitialWorldSettings().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (LootMgr)
IsEligibleForLoot()
bool IsEligibleForLoot (Player * looter, WorldObject * lootTarget)
Definition at line 1623 of file LootMgr.cpp.
References Unit::getThreatManager(), Object::GetTypeId(), ThreatManager::HasThreat(), Player::IsAtGroupRewardDistance(), and TYPEID_UNIT.
Referenced by Loot::SetGroupLootRight().
LoadLootTemplates_Creature()
void LoadLootTemplates_Creature ()
Definition at line 2798 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Creature, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sCreatureStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesCreatureCommand(), and LoadLootTables().
LoadLootTemplates_Disenchant()
void LoadLootTemplates_Disenchant ()
Definition at line 2828 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Disenchant, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sItemStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesDisenchantCommand(), and LoadLootTables().
LoadLootTemplates_Fishing()
void LoadLootTemplates_Fishing ()
Definition at line 2853 of file LootMgr.cpp.
References LootStore::LoadAndCollectLootIds(), LootTemplates_Fishing, LootStore::ReportUnusedIds(), and sAreaStore.
Referenced by ChatHandler::HandleReloadLootTemplatesFishingCommand(), and LoadLootTables().
LoadLootTemplates_Gameobject()
void LoadLootTemplates_Gameobject ()
Definition at line 2873 of file LootMgr.cpp.
References SQLStorageBase::getDataBegin(), SQLStorageBase::getDataEnd(), LootStore::LoadAndCollectLootIds(), LootTemplates_Gameobject, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sGOStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesGameobjectCommand(), and LoadLootTables().
LoadLootTemplates_Item()
void LoadLootTemplates_Item ()
Definition at line 2896 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), ITEM_FLAG_HAS_LOOT, LootStore::LoadAndCollectLootIds(), LOG_FILTER_DB_STRICTED_CHECK, SQLStorage::LookupEntry(), LootTemplates_Item, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), sItemStorage, and sLog.
Referenced by ChatHandler::HandleReloadLootTemplatesItemCommand(), and LoadLootTables().
LoadLootTemplates_Mail()
void LoadLootTemplates_Mail ()
Definition at line 2997 of file LootMgr.cpp.
References LootStore::LoadAndCollectLootIds(), LootTemplates_Mail, LootStore::ReportUnusedIds(), and sMailTemplateStore.
Referenced by ChatHandler::HandleReloadLootTemplatesMailCommand(), and LoadLootTables().
LoadLootTemplates_Milling()
void LoadLootTemplates_Milling ()
Definition at line 2921 of file LootMgr.cpp.
References ItemPrototype::Flags, SQLStorageBase::GetMaxEntry(), ITEM_FLAG_IS_MILLABLE, ItemPrototype::ItemId, LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Milling, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sItemStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesMillingCommand(), and LoadLootTables().
LoadLootTemplates_Pickpocketing()
void LoadLootTemplates_Pickpocketing ()
Definition at line 2946 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Pickpocketing, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sCreatureStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesPickpocketingCommand(), and LoadLootTables().
LoadLootTemplates_Prospecting()
void LoadLootTemplates_Prospecting ()
Definition at line 2972 of file LootMgr.cpp.
References ItemPrototype::Flags, SQLStorageBase::GetMaxEntry(), ITEM_FLAG_IS_PROSPECTABLE, ItemPrototype::ItemId, LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Prospecting, LootStore::ReportUnusedIds(), and sItemStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesProspectingCommand(), and LoadLootTables().
LoadLootTemplates_Reference()
void LoadLootTemplates_Reference (LootIdSet & ids_set)
Definition at line 3071 of file LootMgr.cpp.
References LootStore::LoadAndCheckReferenceNames(), LootStore::LoadAndCollectLootIds(), and LootTemplates_Reference.
Referenced by ChatHandler::HandleReloadLootTemplatesReferenceCommand(), and LoadLootTables().
LoadLootTemplates_Skinning()
void LoadLootTemplates_Skinning ()
Definition at line 3012 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Skinning, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), and sCreatureStorage.
Referenced by ChatHandler::HandleReloadLootTemplatesSkinningCommand(), and LoadLootTables().
LoadLootTemplates_Spell()
void LoadLootTemplates_Spell ()
Definition at line 3038 of file LootMgr.cpp.
References SQLStorageBase::GetMaxEntry(), SpellEntry::HasAttribute(), IsLootCraftingSpell(), LootStore::LoadAndCollectLootIds(), SQLStorage::LookupEntry(), LootTemplates_Spell, LootStore::ReportNotExistedId(), LootStore::ReportUnusedIds(), SPELL_ATTR_IS_TRADESKILL, SPELL_ATTR_NOT_SHAPESHIFT, and sSpellTemplate.
Referenced by ChatHandler::HandleReloadLootTemplatesSpellCommand(), and LoadLootTables().
operator<<()
ByteBuffer& operator<< (ByteBuffer & b, LootItem const & li)
Definition at line 2441 of file LootMgr.cpp.
References LootItem::count, ItemPrototype::DisplayInfoID, ObjectMgr::GetItemPrototype(), LootItem::itemId, LootItem::randomPropertyId, and LootItem::randomSuffix.
Variable Documentation
LootTemplates_Creature
LootStore LootTemplates_Creature("creature_loot_template", "creature entry", true) ("creature_loot_template" , "creature entry" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesCreatureCommand(), LoadLootTemplates_Creature(), Loot::Loot(), and AuctionHouseBot::Update().
LootTemplates_Disenchant
LootStore LootTemplates_Disenchant("disenchant_loot_template", "item disenchant id", true) ("disenchant_loot_template" , "item disenchant id" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesDisenchantCommand(), LoadLootTemplates_Disenchant(), Loot::Loot(), and AuctionHouseBot::Update().
LootTemplates_Fishing
LootStore LootTemplates_Fishing("fishing_loot_template", "area id", true) ("fishing_loot_template" , "area id" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesFishingCommand(), LoadLootTemplates_Fishing(), Loot::Loot(), and AuctionHouseBot::Update().
LootTemplates_Gameobject
LootStore LootTemplates_Gameobject("gameobject_loot_template", "gameobject lootid", true) ("gameobject_loot_template" , "gameobject lootid" , true)
Referenced by GameObject::ActivateToQuest(), LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesGameobjectCommand(), ObjectMgr::LoadGameObjectForQuests(), LoadLootTemplates_Gameobject(), Loot::Loot(), Loot::Release(), and AuctionHouseBot::Update().
LootTemplates_Item
LootStore LootTemplates_Item("item_loot_template", "item entry with ITEM_FLAG_LOOTABLE", true) ("item_loot_template" , "item entry with ITEM_FLAG_LOOTABLE" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesItemCommand(), LoadLootTemplates_Item(), and Loot::Loot().
LootTemplates_Mail
LootStore LootTemplates_Mail("mail_loot_template", "mail template id", false) ("mail_loot_template" , "mail template id" , false)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesMailCommand(), LoadLootTemplates_Mail(), and Loot::Loot().
LootTemplates_Milling
LootStore LootTemplates_Milling("milling_loot_template", "item entry (herb)", true) ("milling_loot_template" , "item entry (herb)" , true)
Referenced by LootMgr::CheckDropStats(), Spell::CheckItems(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesMillingCommand(), LoadLootTemplates_Milling(), and Loot::Loot().
LootTemplates_Pickpocketing
LootStore LootTemplates_Pickpocketing("pickpocketing_loot_template", "creature pickpocket lootid", true) ("pickpocketing_loot_template" , "creature pickpocket lootid" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesPickpocketingCommand(), LoadLootTemplates_Pickpocketing(), and Loot::Loot().
LootTemplates_Prospecting
LootStore LootTemplates_Prospecting("prospecting_loot_template", "item entry (ore)", true) ("prospecting_loot_template" , "item entry (ore)" , true)
Referenced by LootMgr::CheckDropStats(), Spell::CheckItems(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesProspectingCommand(), LoadLootTemplates_Prospecting(), and Loot::Loot().
LootTemplates_Reference
LootStore LootTemplates_Reference("reference_loot_template", "reference id", false) ("reference_loot_template" , "reference id" , false)
Referenced by LootTemplate::LootGroup::CheckLootRefs(), LootTemplate::CheckLootRefs(), CheckLootTemplates_Reference(), LootMgr::ExistsRefLootTemplate(), LoadLootTemplates_Reference(), Loot::Loot(), and LootTemplate::Process().
LootTemplates_Skinning
LootStore LootTemplates_Skinning("skinning_loot_template", "creature skinning id", true) ("skinning_loot_template" , "creature skinning id" , true)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesSkinningCommand(), LoadLootTemplates_Skinning(), Loot::Loot(), and AuctionHouseBot::Update().
LootTemplates_Spell
LootStore LootTemplates_Spell("spell_loot_template", "spell id (random item creating)", false) ("spell_loot_template" , "spell id (random item creating)" , false)
Referenced by LootMgr::CheckDropStats(), CheckLootTemplates_Reference(), ChatHandler::HandleReloadLootTemplatesSpellCommand(), LoadLootTemplates_Spell(), and Loot::Loot().
qualityToRate
eConfigFloatValues const qualityToRate[MAX_ITEM_QUALITY] static
Initial value:
=
{
    CONFIG_FLOAT_RATE_DROP_ITEM_POOR,
    CONFIG_FLOAT_RATE_DROP_ITEM_NORMAL,
    CONFIG_FLOAT_RATE_DROP_ITEM_UNCOMMON,
    CONFIG_FLOAT_RATE_DROP_ITEM_RARE,
    CONFIG_FLOAT_RATE_DROP_ITEM_EPIC,
    CONFIG_FLOAT_RATE_DROP_ITEM_LEGENDARY,
    CONFIG_FLOAT_RATE_DROP_ITEM_ARTIFACT,
}
Definition at line 37 of file LootMgr.cpp.
Referenced by LootStoreItem::Roll().