CMaNGOS_WoTLK: M2Stores.h File Reference
M2Stores.h File Reference
#include "Common.h"
Data Structures
struct CamLocation
struct FlyByCamera
Typedefs
typedef std::vector< FlyByCamera > FlyByCameraCollection
Functions
void LoadM2Cameras (std::string const &dataPath)
Variables
std::unordered_map< uint32, FlyByCameraCollection > sFlyByCameraStore
Typedef Documentation
FlyByCameraCollection
typedef std::vector<FlyByCamera> FlyByCameraCollection
Definition at line 37 of file M2Stores.h.
Function Documentation
LoadM2Cameras()
void LoadM2Cameras (std::string const & dataPath)
Definition at line 181 of file M2Stores.cpp.
References WorldTimer::getMSTime(), WorldTimer::getMSTimeDiff(), M2Header::ofsCameras, readCamera(), sCinematicCameraStore, sFlyByCameraStore, and sLog.
Referenced by World::SetInitialWorldSettings().
Variable Documentation
sFlyByCameraStore
std::unordered_map<uint32, FlyByCameraCollection> sFlyByCameraStore extern
Definition at line 28 of file M2Stores.cpp.
Referenced by CinematicMgr::BeginCinematic(), ChatHandler::HandleDebugPlayCinematicCommand(), LoadM2Cameras(), and readCamera().