CMaNGOS_WoTLK: magisters_terraceScripts.cpp File Reference
magisters_terraceScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "magisters_terrace.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct npc_kalecgosAI
Enumerations
enum {
SPELL_CAMERA_SHAKE_MED = 44762 , SPELL_TRANSFORM_VISUAL = 24085 , SPELL_ORB_KILL_CREDIT = 46307 , NPC_KALECGOS = 24848 ,
MAP_ID_MAGISTER = 585 , SAY_SPAWN = -1585032 , POINT_FINAL = 7 , ACTION_TRANSFORM = 1
}
Functions
bool ProcessEventId_event_go_scrying_orb (uint32, Object *source, Object *, bool isStart)
void AddSC_magisters_terrace ()
Variables
static const float afKaelLandPoint [4] = {200.36f, -270.77f, -8.73f, 0.01f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_CAMERA_SHAKE_MED
SPELL_TRANSFORM_VISUAL
SPELL_ORB_KILL_CREDIT
NPC_KALECGOS
MAP_ID_MAGISTER
SAY_SPAWN
POINT_FINAL
ACTION_TRANSFORM
Definition at line 36 of file magisters_terraceScripts.cpp.
Function Documentation
AddSC_magisters_terrace()
void AddSC_magisters_terrace ()
Definition at line 151 of file magisters_terraceScripts.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_scrying_orb(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_event_go_scrying_orb()
bool ProcessEventId_event_go_scrying_orb (uint32 , Object * source, Object * , bool isStart)
Definition at line 135 of file magisters_terraceScripts.cpp.
References Object::GetTypeId(), and TYPEID_PLAYER.
Referenced by AddSC_magisters_terrace().
Variable Documentation
afKaelLandPoint
const float afKaelLandPoint[4] = {200.36f, -270.77f, -8.73f, 0.01f} static
Definition at line 52 of file magisters_terraceScripts.cpp.
Referenced by npc_kalecgosAI::HandleTransform().