CMaNGOS_WoTLK: mana_tombsScripts.cpp File Reference
mana_tombsScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Entities/TemporarySpawn.h"
Data Structures
struct npc_shaheenAI
Enumerations
enum {
SAY_ESCORT_START = -1557015 , SAY_START = -1557016 , SAY_FIRST_STOP = -1557017 , SAY_FIRST_STOP_COMPLETE = -1557018 ,
SAY_COLLECTOR_SEARCH = -1557019 , SAY_COLLECTOR_FOUND = -1557020 , SAY_SECOND_STOP = -1557021 , SAY_THIRD_STOP = -1557022 ,
SAY_REST = -1557023 , SAY_READY_GO = -1557024 , SAY_BREAK_OVER = -1557025 , SAY_XIRAXIS_SPAWN = -1557026 ,
SAY_FINAL_STOP_1 = -1557027 , SAY_FINAL_STOP_2 = -1557028 , SAY_FINAL_STOP_3 = -1557029 , SAY_XIRAXIS_DEAD = -1557030 ,
SAY_EVENT_COMPLETE = -1557031 , EMOTE_TELEPORT = -1557032 , SAY_SPAWN = -1557033 , EMOTE_PANEL = -1557034 ,
SAY_ESCORT_READY = -1557035 , SPELL_ETHEREAL_TELEPORT = 34427 , NPC_ETHEREAL_SPELLBINDER = 18312 , NPC_ETHEREAL_THEURGIST = 18315 ,
NPC_ETHEREAL_SORCERER = 18313 , NPC_ETHEREAL_CRYPT_RAIDER = 18311 , NPC_NEXUS_TERROR = 19307 , NPC_ENGINEER_SHAEEN = 19671 ,
NPC_SHADOW_LORD_XIRAXIS = 19666 , QUEST_ID_HARD_WORK_PAYS_OFF = 10218
}
Functions
UnitAI * GetAI_npc_shaheen (Creature *pCreature)
bool QuestAccept_npc_shaheen (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_mana_tombs ()
Variables
static const DialogueEntry aIntroDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_START
SAY_FIRST_STOP
SAY_FIRST_STOP_COMPLETE
SAY_COLLECTOR_SEARCH
SAY_COLLECTOR_FOUND
SAY_SECOND_STOP
SAY_THIRD_STOP
SAY_REST
SAY_READY_GO
SAY_BREAK_OVER
SAY_XIRAXIS_SPAWN
SAY_FINAL_STOP_1
SAY_FINAL_STOP_2
SAY_FINAL_STOP_3
SAY_XIRAXIS_DEAD
SAY_EVENT_COMPLETE
EMOTE_TELEPORT
SAY_SPAWN
EMOTE_PANEL
SAY_ESCORT_READY
SPELL_ETHEREAL_TELEPORT
NPC_ETHEREAL_SPELLBINDER
NPC_ETHEREAL_THEURGIST
NPC_ETHEREAL_SORCERER
NPC_ETHEREAL_CRYPT_RAIDER
NPC_NEXUS_TERROR
NPC_ENGINEER_SHAEEN
NPC_SHADOW_LORD_XIRAXIS
QUEST_ID_HARD_WORK_PAYS_OFF
Definition at line 32 of file mana_tombsScripts.cpp.
Function Documentation
AddSC_mana_tombs()
void AddSC_mana_tombs ()
Definition at line 293 of file mana_tombsScripts.cpp.
References Script::GetAI, GetAI_npc_shaheen(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_shaheen(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_shaheen()
UnitAI* GetAI_npc_shaheen (Creature * pCreature)
Definition at line 277 of file mana_tombsScripts.cpp.
Referenced by AddSC_mana_tombs().
QuestAccept_npc_shaheen()
bool QuestAccept_npc_shaheen (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 282 of file mana_tombsScripts.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_HARD_WORK_PAYS_OFF, and UnitAI::SendAIEvent().
Referenced by AddSC_mana_tombs().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {SPELL_ETHEREAL_TELEPORT,   0,                       1000},
    {EMOTE_TELEPORT,            NPC_ENGINEER_SHAEEN,     3000},
    {NPC_ETHEREAL_SPELLBINDER,  0,                       5000},
    {EMOTE_PANEL,               NPC_ENGINEER_SHAEEN,     3000},
    {SAY_ESCORT_READY,          NPC_ENGINEER_SHAEEN,     0},
    {SAY_ESCORT_START,          NPC_ENGINEER_SHAEEN,     5000},
    {SAY_START,                 NPC_ENGINEER_SHAEEN,     0},
    {SAY_COLLECTOR_SEARCH,      NPC_ENGINEER_SHAEEN,     6000},
    {SAY_COLLECTOR_FOUND,       NPC_ENGINEER_SHAEEN,     0},
    {NPC_ETHEREAL_THEURGIST,    0,                       12000},
    {SAY_REST,                  NPC_ENGINEER_SHAEEN,     20000},
    {SAY_READY_GO,              NPC_ENGINEER_SHAEEN,     0},
    {SAY_FINAL_STOP_1,          NPC_SHADOW_LORD_XIRAXIS, 6000},
    {SAY_FINAL_STOP_2,          NPC_ENGINEER_SHAEEN,     4000},
    {SAY_FINAL_STOP_3,          NPC_SHADOW_LORD_XIRAXIS, 3000},
    {NPC_SHADOW_LORD_XIRAXIS,   0,                       0},
    {NPC_ENGINEER_SHAEEN,       0,                       3000},
    {SAY_XIRAXIS_DEAD,          NPC_ENGINEER_SHAEEN,     7000},
    {SAY_EVENT_COMPLETE,        NPC_ENGINEER_SHAEEN,     0},
    {0, 0, 0},
}
Definition at line 70 of file mana_tombsScripts.cpp.