CMaNGOS_WoTLK: mechanar.cpp File Reference
mechanar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "mechanar.h"
Functions
InstanceData * GetInstanceData_instance_mechanar (Map *pMap)
void AddSC_instance_mechanar ()
Function Documentation
AddSC_instance_mechanar()
void AddSC_instance_mechanar ()
Definition at line 312 of file mechanar.cpp.
References Script::GetInstanceData, GetInstanceData_instance_mechanar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_mechanar()
InstanceData* GetInstanceData_instance_mechanar (Map * pMap)
Definition at line 287 of file mechanar.cpp.
Referenced by AddSC_instance_mechanar().