CMaNGOS_WoTLK: midsummer_festival.cpp File Reference
midsummer_festival.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "World/WorldState.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct go_bonfire
struct LightBonfire
struct BonfireArtkit
struct TestRibbonPoleChannelTrigger
struct TestRibbonPoleChannel
struct RevelerApplauseCheer
struct RibbonPoleDancerCheckAura
struct RibbonPoleDancerCheck
struct SummonRibbonPoleCritter
struct TorchTossingTargetBunnyControllerAI
struct TorchToss
struct BraziersHit
struct TorchTargetPicker
struct FlignTorch
struct JuggleTorchCatchQuest
struct TorchesCaught
struct BrazierOfDancingFlames
struct ThrowTorch
struct JuggleTorchCatch
Enumerations
enum { SPELL_SUMMON_MIDSUMMER_BONFIRE_BUNNIES = 28784 , SPELL_STAMP_OUT_BONFIRE = 45437 , SPELL_STAMP_OUT_BONFIRE_ART_KIT = 46903 , SPELL_LIGHT_BONFIRE = 46904 }
enum {
SPELL_RIBBON_DANCE = 29175 , SPELL_RIBBON_POLE_DANCER_CHECK = 45405 , SPELL_GROUND_FLOWER = 46971 , SPELL_BIG_FLAME_DANCER = 46827 ,
SPELL_SUMMON_RIBBON_POLE_FIRE_SPIRAL_VISUAL = 45422 , SPELL_RIBBON_POLE_FIREWORK_LAUNCHER_AURA = 46830 , SPELL_HOLIDAY_MIDSUMMER_RIBBON_POLE_PERIODIC_VISUAL = 45406 , NPC_FIRE_EATER = 25962 ,
NPC_FLAME_EATER = 25994 , RELAY_SCRIPT_ID_DELAY_RESET_ORIENTATION = 10204
}
enum { SPELL_BRAZIERS_HIT = 45724 , SPELL_TARGET_INDICATOR_COSMETIC = 46901 , SPELL_TARGET_INDICATOR = 45723 , SPELL_TORCH_TARGET_PICKER = 45907 }
enum {
SPELL_JUGGLE_TORCH = 45638 , SPELL_JUGGLE_TORCH_OTHER_SLOW = 45792 , SPELL_JUGGLE_TORCH_OTHER_MEDIUM = 45806 , SPELL_JUGGLE_TORCH_OTHER_FAST = 45816 ,
SPELL_TORCH_TOSS_SHADOW_FAST = 46117 , SPELL_TORCH_TOSS_SHADOW_MEDIUM = 46118 , SPELL_TORCH_TOSS_SHADOW_SLOW = 46120 , SPELL_TORCH_TOSS_SHADOW_SELF = 46121 ,
SPELL_JUGGLE_TORCH_EXPLOSION_VISUAL = 45690 , SPELL_GIVE_TORCH = 45280
}
Functions
bool QuestRewardedBonfireDesecrate (Player *player, GameObject *, Quest const *)
void AddSC_midsummer_festival ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_MIDSUMMER_BONFIRE_BUNNIES
SPELL_STAMP_OUT_BONFIRE
SPELL_STAMP_OUT_BONFIRE_ART_KIT
SPELL_LIGHT_BONFIRE
Definition at line 21 of file midsummer_festival.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RIBBON_DANCE
SPELL_RIBBON_POLE_DANCER_CHECK
SPELL_GROUND_FLOWER
SPELL_BIG_FLAME_DANCER
SPELL_SUMMON_RIBBON_POLE_FIRE_SPIRAL_VISUAL
SPELL_RIBBON_POLE_FIREWORK_LAUNCHER_AURA
SPELL_HOLIDAY_MIDSUMMER_RIBBON_POLE_PERIODIC_VISUAL
NPC_FIRE_EATER
NPC_FLAME_EATER
RELAY_SCRIPT_ID_DELAY_RESET_ORIENTATION
Definition at line 91 of file midsummer_festival.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_BRAZIERS_HIT
SPELL_TARGET_INDICATOR_COSMETIC
SPELL_TARGET_INDICATOR
SPELL_TORCH_TARGET_PICKER
Definition at line 224 of file midsummer_festival.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_JUGGLE_TORCH
SPELL_JUGGLE_TORCH_OTHER_SLOW
SPELL_JUGGLE_TORCH_OTHER_MEDIUM
SPELL_JUGGLE_TORCH_OTHER_FAST
SPELL_TORCH_TOSS_SHADOW_FAST
SPELL_TORCH_TOSS_SHADOW_MEDIUM
SPELL_TORCH_TOSS_SHADOW_SLOW
SPELL_TORCH_TOSS_SHADOW_SELF
SPELL_JUGGLE_TORCH_EXPLOSION_VISUAL
SPELL_GIVE_TORCH
Definition at line 419 of file midsummer_festival.cpp.
Function Documentation
AddSC_midsummer_festival()
void AddSC_midsummer_festival ()
Definition at line 495 of file midsummer_festival.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, Script::pQuestRewardedGO, QuestRewardedBonfireDesecrate(), and Script::RegisterSelf().
Referenced by AddScripts().
QuestRewardedBonfireDesecrate()
bool QuestRewardedBonfireDesecrate (Player * player, GameObject * , Quest const *)
Definition at line 62 of file midsummer_festival.cpp.
References Unit::CastSpell(), SPELL_STAMP_OUT_BONFIRE, SPELL_STAMP_OUT_BONFIRE_ART_KIT, and TRIGGERED_NONE.
Referenced by AddSC_midsummer_festival().