CMaNGOS_WoTLK: molten_core.cpp File Reference
molten_core.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "molten_core.h"
Functions
InstanceData * GetInstance_instance_molten_core (Map *pMap)
void AddSC_instance_molten_core ()
Variables
static sSpawnLocation m_aBosspawnLocs [MAX_MAJORDOMO_ADDS]
Function Documentation
AddSC_instance_molten_core()
void AddSC_instance_molten_core ()
Definition at line 310 of file molten_core.cpp.
References GetInstance_instance_molten_core(), Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstance_instance_molten_core()
InstanceData* GetInstance_instance_molten_core (Map * pMap)
Definition at line 305 of file molten_core.cpp.
Referenced by AddSC_instance_molten_core().
Variable Documentation
m_aBosspawnLocs
sSpawnLocation m_aBosspawnLocs[MAX_MAJORDOMO_ADDS] static
Initial value:
=
{
    {NPC_FLAMEWAKER_ELITE,  737.945f, -1156.48f, -118.945f, 4.46804f},
    {NPC_FLAMEWAKER_ELITE,  752.520f, -1191.02f, -118.218f, 2.49582f},
    {NPC_FLAMEWAKER_ELITE,  752.953f, -1163.94f, -118.869f, 3.70010f},
    {NPC_FLAMEWAKER_ELITE,  738.814f, -1197.40f, -118.018f, 1.83260f},
    {NPC_FLAMEWAKER_HEALER, 746.939f, -1194.87f, -118.016f, 2.21657f},
    {NPC_FLAMEWAKER_HEALER, 747.132f, -1158.87f, -118.897f, 4.03171f},
    {NPC_FLAMEWAKER_HEALER, 757.116f, -1170.12f, -118.793f, 3.40339f},
    {NPC_FLAMEWAKER_HEALER, 755.910f, -1184.46f, -118.449f, 2.80998f}
}
Definition at line 27 of file molten_core.cpp.
Referenced by instance_molten_core::SpawnMajordomo().