CMaNGOS_WoTLK: moonglade.cpp File Reference
moonglade.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Globals/ObjectMgr.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
Data Structures
struct npc_clintar_dw_spiritAI
struct GraspOfTheEmeraldDream
struct npc_keeper_remulosAI
struct boss_eranikusAI
struct ConjureDreamRift
Enumerations
enum {
SAY_START = -1000280 , SAY_AGGRO_1 = -1000281 , SAY_AGGRO_2 = -1000282 , SAY_RELIC1 = -1000283 ,
SAY_RELIC2 = -1000284 , SAY_RELIC3 = -1000285 , SAY_END = -1000286 , QUEST_MERE_DREAM = 10965 ,
SPELL_EMERALD_DREAM = 39601 , NPC_CLINTAR_DW_SPIRIT = 22916 , NPC_CLINTAR_SPIRIT = 22901 , NPC_ASPECT_OF_RAVEN = 22915
}
enum {
SPELL_CONJURE_RIFT = 25813 , SPELL_DRAGON_HOVER = 18430 , SPELL_HEALING_TOUCH = 23381 , SPELL_REGROWTH = 20665 ,
SPELL_REJUVENATION = 20664 , SPELL_STARFIRE = 21668 , SPELL_ERANIKUS_REDEEMED = 25846 , NPC_ERANIKUS_TYRANT = 15491 ,
NPC_NIGHTMARE_PHANTASM = 15629 , NPC_REMULOS = 11832 , NPC_TYRANDE_WHISPERWIND = 15633 , NPC_ELUNE_PRIESTESS = 15634 ,
NPC_NIGHTHAVEN_DEFENDER = 15495 , FACTION_CENARION_CIRCLE = 996 , QUEST_NIGHTMARE_MANIFESTS = 8736 , SAY_REMULOS_INTRO_1 = -1000669 ,
SAY_REMULOS_INTRO_2 = -1000670 , SAY_REMULOS_INTRO_3 = -1000671 , SAY_REMULOS_INTRO_4 = -1000672 , SAY_REMULOS_INTRO_5 = -1000673 ,
EMOTE_SUMMON_ERANIKUS = -1000674 , SAY_ERANIKUS_SPAWN = -1000675 , SAY_REMULOS_TAUNT_1 = -1000676 , EMOTE_ERANIKUS_LAUGH = -1000677 ,
SAY_ERANIKUS_TAUNT_2 = -1000678 , SAY_REMULOS_TAUNT_3 = -1000679 , SAY_ERANIKUS_TAUNT_4 = -1000680 , EMOTE_ERANIKUS_ATTACK = -1000681 ,
SAY_REMULOS_DEFEND_1 = -1000682 , SAY_REMULOS_DEFEND_2 = -1000683 , SAY_ERANIKUS_SHADOWS = -1000684 , SAY_REMULOS_DEFEND_3 = -1000685 ,
SAY_ERANIKUS_ATTACK_1 = -1000686 , SAY_ERANIKUS_ATTACK_2 = -1000687 , SAY_ERANIKUS_ATTACK_3 = -1000688 , SAY_ERANIKUS_KILL = -1000706 ,
SAY_TYRANDE_APPEAR = -1000689 , SAY_TYRANDE_HEAL = -1000690 , SAY_TYRANDE_FORGIVEN_1 = -1000691 , SAY_TYRANDE_FORGIVEN_2 = -1000692 ,
SAY_TYRANDE_FORGIVEN_3 = -1000693 , SAY_ERANIKUS_DEFEAT_1 = -1000694 , SAY_ERANIKUS_DEFEAT_2 = -1000695 , SAY_ERANIKUS_DEFEAT_3 = -1000696 ,
EMOTE_ERANIKUS_REDEEM = -1000697 , PRIESTESS_MOUNT_ID = 9695 , EMOTE_TYRANDE_KNEEL = -1000698 , SAY_TYRANDE_REDEEMED = -1000699 ,
SAY_REDEEMED_1 = -1000700 , SAY_REDEEMED_2 = -1000701 , SAY_REDEEMED_3 = -1000702 , SAY_REDEEMED_4 = -1000703 ,
SAY_REMULOS_OUTRO_1 = -1000704 , SAY_REMULOS_OUTRO_2 = -1000705 , POINT_ID_ERANIKUS_FLIGHT = 1 , POINT_ID_ERANIKUS_COMBAT = 2 ,
POINT_ID_ERANIKUS_REDEEMED = 3 , MAX_SHADOWS = 3 , MAX_DEFENDERS = 10 , MAX_SUMMON_TURNS = 10
}
enum {
NPC_KEEPER_REMULOS = 11832 , NPC_ERANIKUS_REDEEMED = 15628 , SPELL_ACID_BREATH = 24839 , SPELL_NOXIOUS_BREATH = 24818 ,
SPELL_SHADOWBOLT_VOLLEY = 25586 , SPELL_ARCANE_CHANNELING = 23017 , FACTION_FRIENDLY = 35 , MAX_PRIESTESS = 7 ,
POINT_ID_TYRANDE_HEAL = 0 , POINT_ID_TYRANDE_ABSOLUTION = 1
}
Functions
UnitAI * GetAI_npc_keeper_remulos (Creature *creature)
bool QuestAccept_npc_keeper_remulos (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_boss_eranikus (Creature *creature)
bool GOUse_go_omen_cluster (Player *, GameObject *pGo)
void AddSC_moonglade ()
Variables
static const DialogueEntry aIntroDialogue []
static Position eranikusLocations []
static Position tyrandeLocations []
static Position shadowsLocations []
static Position defendersLocations []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_AGGRO_1
SAY_AGGRO_2
SAY_RELIC1
SAY_RELIC2
SAY_RELIC3
SAY_END
QUEST_MERE_DREAM
SPELL_EMERALD_DREAM
NPC_CLINTAR_DW_SPIRIT
NPC_CLINTAR_SPIRIT
NPC_ASPECT_OF_RAVEN
Definition at line 39 of file moonglade.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CONJURE_RIFT
SPELL_DRAGON_HOVER
SPELL_HEALING_TOUCH
SPELL_REGROWTH
SPELL_REJUVENATION
SPELL_STARFIRE
SPELL_ERANIKUS_REDEEMED
NPC_ERANIKUS_TYRANT
NPC_NIGHTMARE_PHANTASM
NPC_REMULOS
NPC_TYRANDE_WHISPERWIND
NPC_ELUNE_PRIESTESS
NPC_NIGHTHAVEN_DEFENDER
FACTION_CENARION_CIRCLE
QUEST_NIGHTMARE_MANIFESTS
SAY_REMULOS_INTRO_1
SAY_REMULOS_INTRO_2
SAY_REMULOS_INTRO_3
SAY_REMULOS_INTRO_4
SAY_REMULOS_INTRO_5
EMOTE_SUMMON_ERANIKUS
SAY_ERANIKUS_SPAWN
SAY_REMULOS_TAUNT_1
EMOTE_ERANIKUS_LAUGH
SAY_ERANIKUS_TAUNT_2
SAY_REMULOS_TAUNT_3
SAY_ERANIKUS_TAUNT_4
EMOTE_ERANIKUS_ATTACK
SAY_REMULOS_DEFEND_1
SAY_REMULOS_DEFEND_2
SAY_ERANIKUS_SHADOWS
SAY_REMULOS_DEFEND_3
SAY_ERANIKUS_ATTACK_1
SAY_ERANIKUS_ATTACK_2
SAY_ERANIKUS_ATTACK_3
SAY_ERANIKUS_KILL
SAY_TYRANDE_APPEAR
SAY_TYRANDE_HEAL
SAY_TYRANDE_FORGIVEN_1
SAY_TYRANDE_FORGIVEN_2
SAY_TYRANDE_FORGIVEN_3
SAY_ERANIKUS_DEFEAT_1
SAY_ERANIKUS_DEFEAT_2
SAY_ERANIKUS_DEFEAT_3
EMOTE_ERANIKUS_REDEEM
PRIESTESS_MOUNT_ID
EMOTE_TYRANDE_KNEEL
SAY_TYRANDE_REDEEMED
SAY_REDEEMED_1
SAY_REDEEMED_2
SAY_REDEEMED_3
SAY_REDEEMED_4
SAY_REMULOS_OUTRO_1
SAY_REMULOS_OUTRO_2
POINT_ID_ERANIKUS_FLIGHT
POINT_ID_ERANIKUS_COMBAT
POINT_ID_ERANIKUS_REDEEMED
MAX_SHADOWS
MAX_DEFENDERS
MAX_SUMMON_TURNS
Definition at line 170 of file moonglade.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_KEEPER_REMULOS
NPC_ERANIKUS_REDEEMED
SPELL_ACID_BREATH
SPELL_NOXIOUS_BREATH
SPELL_SHADOWBOLT_VOLLEY
SPELL_ARCANE_CHANNELING
FACTION_FRIENDLY
MAX_PRIESTESS
POINT_ID_TYRANDE_HEAL
POINT_ID_TYRANDE_ABSOLUTION
Definition at line 656 of file moonglade.cpp.
Function Documentation
AddSC_moonglade()
void AddSC_moonglade ()
Definition at line 1068 of file moonglade.cpp.
References Script::GetAI, GetAI_boss_eranikus(), GetAI_npc_keeper_remulos(), GOUse_go_omen_cluster(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_keeper_remulos(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_eranikus()
UnitAI* GetAI_boss_eranikus (Creature * creature)
Definition at line 1023 of file moonglade.cpp.
Referenced by AddSC_moonglade().
GetAI_npc_keeper_remulos()
UnitAI* GetAI_npc_keeper_remulos (Creature * creature)
Definition at line 633 of file moonglade.cpp.
Referenced by AddSC_moonglade().
GOUse_go_omen_cluster()
bool GOUse_go_omen_cluster (Player * , GameObject * pGo)
Definition at line 1049 of file moonglade.cpp.
References WorldObject::GetInstanceData(), GameObject::GetSpawner(), NOT_STARTED, InstanceData::SetData(), and TYPE_OMEN.
Referenced by AddSC_moonglade().
QuestAccept_npc_keeper_remulos()
bool QuestAccept_npc_keeper_remulos (Player * player, Creature * creature, const Quest * quest)
Definition at line 638 of file moonglade.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_NIGHTMARE_MANIFESTS.
Referenced by AddSC_moonglade().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {NPC_REMULOS,           0,                   14000},
    {SAY_REMULOS_INTRO_4,   NPC_REMULOS,         12000},
    {SAY_REMULOS_INTRO_5,   NPC_REMULOS,         5000},
    {SPELL_CONJURE_RIFT,    0,                   13000},
    {SAY_ERANIKUS_SPAWN,    NPC_ERANIKUS_TYRANT, 11000},
    {SAY_REMULOS_TAUNT_1,   NPC_REMULOS,         5000},
    {EMOTE_ERANIKUS_LAUGH,  NPC_ERANIKUS_TYRANT, 3000},
    {SAY_ERANIKUS_TAUNT_2,  NPC_ERANIKUS_TYRANT, 10000},
    {SAY_REMULOS_TAUNT_3,   NPC_REMULOS,         12000},
    {SAY_ERANIKUS_TAUNT_4,  NPC_ERANIKUS_TYRANT, 6000},
    {EMOTE_ERANIKUS_ATTACK, NPC_ERANIKUS_TYRANT, 7000},
    {NPC_ERANIKUS_TYRANT,   0,                   0},
    {SAY_REMULOS_DEFEND_2,  NPC_REMULOS,         6000},
    {SAY_ERANIKUS_SHADOWS,  NPC_ERANIKUS_TYRANT, 4000},
    {SAY_REMULOS_DEFEND_3,  NPC_REMULOS,         0},
    {0, 0, 0},
}
Definition at line 250 of file moonglade.cpp.
defendersLocations
Position defendersLocations[] static
Initial value:
=
{
    {7868.226f, -2556.95f, 487.07f},
    {7867.39f, -2578.96f, 486.95f}
}
Definition at line 299 of file moonglade.cpp.
Referenced by npc_keeper_remulosAI::UpdateEscortAI().
eranikusLocations
Position eranikusLocations[] static
Initial value:
=
{
    {7881.72f, -2651.23f, 493.29f, 0.40f},
    {7929.86f, -2574.88f, 505.35f},
    {7912.98f, -2568.99f, 488.71f},
    {7906.57f, -2565.63f, 488.39f},
}
Definition at line 270 of file moonglade.cpp.
Referenced by npc_keeper_remulosAI::JustDidDialogueStep(), ConjureDreamRift::OnEffectExecute(), boss_eranikusAI::UpdateAI(), and npc_keeper_remulosAI::UpdateEscortAI().
shadowsLocations
Position shadowsLocations[] static
Initial value:
=
{
    {7832.78f, -2604.57f, 489.29f},
    {7826.68f, -2538.46f, 489.30f},
    {7811.48f, -2573.20f, 488.49f},
    {7888.32f, -2566.25f, 487.02f},
    {7946.12f, -2577.10f, 489.97f},
    {7963.00f, -2492.03f, 487.84f}
}
Definition at line 286 of file moonglade.cpp.
Referenced by npc_keeper_remulosAI::UpdateEscortAI().
tyrandeLocations
Position tyrandeLocations[] static
Initial value:
=
{
    {7948.89f, -2575.58f, 490.05f, 3.03f},
    {7888.32f, -2566.25f, 487.02f},
    {7901.83f, -2565.24f, 488.04f},
}
Definition at line 278 of file moonglade.cpp.
Referenced by boss_eranikusAI::DoSummonHealers(), boss_eranikusAI::JustSummoned(), and boss_eranikusAI::UpdateAI().