CMaNGOS_WoTLK: MotionMaster.cpp File Reference
MotionMaster.cpp File Reference
#include "MotionGenerators/MotionMaster.h"
#include "HomeMovementGenerator.h"
#include "IdleMovementGenerator.h"
#include "MotionGenerators/PathMovementGenerator.h"
#include "MotionGenerators/PointMovementGenerator.h"
#include "MotionGenerators/RandomMovementGenerator.h"
#include "MotionGenerators/TargetedMovementGenerator.h"
#include "MotionGenerators/WaypointMovementGenerator.h"
#include "MotionGenerators/WrapperMovementGenerator.h"
#include "Movement/MoveSpline.h"
#include "Movement/MoveSplineInit.h"
#include "Maps/GridDefines.h"
#include "Maps/Map.h"
#include "AI/CreatureAISelector.h"
#include "Entities/Creature.h"
#include "Entities/CreatureLinkingMgr.h"
#include "Entities/Player.h"
#include "Entities/Pet.h"
#include "Server/DBCStores.h"
#include "Log.h"
#include "Maps/TransportSystem.h"
#include "Metric/Metric.h"
#include <cassert>
Functions
bool isStatic (MovementGenerator *mv)
Function Documentation
isStatic()
bool isStatic (MovementGenerator * mv) inline
Definition at line 54 of file MotionMaster.cpp.
References si_idleMovement.
Referenced by MotionMaster::DelayedClean(), MotionMaster::DelayedExpire(), MotionMaster::DirectClean(), MotionMaster::DirectExpire(), MotionMaster::MoveIdle(), MotionMaster::UpdateMotion(), and MotionMaster::~MotionMaster().