CMaNGOS_WoTLK: MaNGOS Namespace Reference
MaNGOS Namespace Reference
class Singleton
Namespaces
Honor
XP
Data Structures
class OperatorNew
OperatorNew policy creates an object on the heap using new.
class LocalStaticCreation
LocalStaticCreation policy creates an object on the stack the first time call Create.
class CreateUsingMalloc
CreateUsingMalloc by pass the memory manger.
class CreateOnCallBack
CreateOnCallBack creates the object base on the call back.
class ObjectLifeTime
class Singleton
class GeneralLock
class SingleThreaded
class ObjectLevelLockable
class ClassLevelLockable
class _Callback
class _Callback< Class, ParamType1, ParamType2, ParamType3 >
class _Callback< Class, ParamType1, ParamType2 >
class _Callback< Class, ParamType1 >
class _Callback< Class >
class _SCallback
-— Statics -—
class _SCallback< ParamType1, ParamType2, ParamType3 >
class _SCallback< ParamType1, ParamType2 >
class _SCallback< ParamType1 >
class _SCallback<>
class ICallback
class _ICallback
class Callback
class Callback< Class, ParamType1, ParamType2, ParamType3 >
class Callback< Class, ParamType1, ParamType2 >
class Callback< Class, ParamType1 >
class Callback< Class >
class IQueryCallback
class _IQueryCallback
class QueryCallback
class QueryCallback< Class, ParamType1, ParamType2 >
class QueryCallback< Class, ParamType1 >
class QueryCallback< Class >
class SQueryCallback
-— Statics -—
class SQueryCallback< ParamType1, ParamType2 >
class SQueryCallback< ParamType1 >
class SQueryCallback<>
class AchievementChatBuilder
class BattleGroundChatBuilder
class BattleGroundYellBuilder
class BattleGroundMessageBuilder
class BattleGroundBroadcastBuilder
class BattleGround2ChatBuilder
class BattleGround2YellBuilder
class EmoteChatBuilder
class MonsterChatBuilder
class NearUsedPosDo
struct VisibleNotifier
struct VisibleChangesNotifier
struct MessageDeliverer
struct MessageDelivererExcept
struct ObjectMessageDeliverer
struct MessageDistDeliverer
struct ObjectMessageDistDeliverer
struct SpellMessageDestLocDeliverer
struct ObjectUpdater
struct PlayerVisitObjectsNotifier
struct CreatureVisitObjectsNotifier
struct DynamicObjectUpdater
struct WorldObjectSearcher
struct WorldObjectListSearcher
struct WorldObjectWorker
struct GameObjectSearcher
struct GameObjectLastSearcher
struct GameObjectListSearcher
struct UnitSearcher
struct UnitLastSearcher
struct UnitListSearcher
struct CreatureSearcher
struct CreatureLastSearcher
struct CreatureListSearcher
struct CreatureWorker
struct PlayerSearcher
struct PlayerListSearcher
struct PlayerWorker
struct CameraDistWorker
struct CameraDistLambdaWorker
class RaiseDeadObjectCheck
class ExplodeCorpseObjectCheck
class CannibalizeObjectCheck
class TauntFlagObjectCheck
class RespawnDo
class GameObjectFocusCheck
class NearestGameObjectFishingHoleCheck
class NearestGameObjectEntryInObjectRangeCheck
class AllGameObjectEntriesListInObjectRangeCheck
class AllGameObjectsMatchingOneEntryInRange
class AllGameObjectEntriesListInPosRangeCheck
class NearestGameObjectEntryInPosRangeCheck
class GameObjectEntryInPosRangeCheck
class GameObjectTypeInPosRangeCheck
class GameObjectInPosRangeCheck
class MostHPMissingInRangeCheck
class MostHPPercentMissingInRangeCheck
class FriendlyEligibleUnitConditionCheck
class FriendlyEligibleDispelInRangeCheck
class FriendlyMissingBuffInRangeInCombatCheck
class FriendlyMissingBuffInRangeNotInCombatCheck
class AnyUnfriendlyUnitInObjectRangeCheck
class AnyUnfriendlyVisibleUnitInObjectRangeCheck
class AnySpellAssistableUnitInObjectRangeCheck
class AnyFriendlyUnitInObjectRangeCheck
class AnyFriendlyOrGroupMemberUnitInUnitRangeCheck
class AnyUnitInObjectRangeCheck
class AnyUnitFulfillingConditionInRangeCheck
class NearestAttackableUnitInObjectRangeCheck
class AnyAoETargetUnitInObjectRangeCheck
class CallOfHelpCreatureInRangeDo
class AnyDeadUnitCheck
class AnyStealthedCheck
class AnyAssistCreatureInRangeCheck
class NearestAssistCreatureInCreatureRangeCheck
class NearestCreatureEntryWithLiveStateInObjectRangeCheck
class AllCreatureEntriesWithLiveStateInObjectRangeCheck
class AllCreaturesOfEntryInRangeCheck
class AllCreaturesMatchingOneEntryInRange
class AnyPlayerInObjectRangeCheck
class AnyPlayerInObjectRangeWithAuraCheck
class AnyPlayerInCapturePointRange
class LocalizedPacketDo
class LocalizedPacketListDo
struct SpellNotifierPlayer
struct SpellNotifierCreatureAndPlayer
class WorldWorldTextBuilder
class Runnable
class Thread
class Listener
class NetworkThread
class PacketBuffer
class Socket
class thread_local_ptr
Enumerations
enum Priority {
Priority_Idle , Priority_Lowest , Priority_Low , Priority_Normal ,
Priority_High , Priority_Highest , Priority_Realtime
}
Functions
template<class SPECIFIC_TYPE >
size_t Count (const ContainerMapList< SPECIFIC_TYPE > &elements, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE >
size_t Count (const ContainerMapList< TypeNull > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
size_t Count (const ContainerMapList< T > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
size_t Count (const ContainerMapList< TypeList< SPECIFIC_TYPE, T > > &elements, SPECIFIC_TYPE *fake)
template<class SPECIFIC_TYPE , class H , class T >
size_t Count (const ContainerMapList< TypeList< H, T > > &elements, SPECIFIC_TYPE *fake)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Insert (ContainerMapList< SPECIFIC_TYPE > &elements, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Insert (ContainerMapList< TypeNull > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
SPECIFIC_TYPE * Insert (ContainerMapList< T > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class H , class T >
SPECIFIC_TYPE * Insert (ContainerMapList< TypeList< H, T > > &elements, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Remove (ContainerMapList< SPECIFIC_TYPE > &, SPECIFIC_TYPE *obj)
template<class SPECIFIC_TYPE >
SPECIFIC_TYPE * Remove (ContainerMapList< TypeNull > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T >
SPECIFIC_TYPE * Remove (ContainerMapList< T > &, SPECIFIC_TYPE *)
template<class SPECIFIC_TYPE , class T , class H >
SPECIFIC_TYPE * Remove (ContainerMapList< TypeList< H, T > > &elements, SPECIFIC_TYPE *obj)
void external_wrapper (void *p)
void at_exit (void(*func)())
template<class RET_TYPE , int CENTER_VAL>
RET_TYPE Compute (float x, float y, float center_offset, float size)
GridPair ComputeGridPair (float x, float y)
CellPair ComputeCellPair (float x, float y)
void NormalizeMapCoord (float &c)
bool IsValidMapCoord (float c)
bool IsValidMapCoord (float x, float y)
bool IsValidMapCoord (float x, float y, float z)
bool IsValidMapCoord (float x, float y, float z, float o)
Detailed Description
class Singleton
------— GENERIC CALLBACKS -------—
---------— BASE CLASSES ---------—
Enumeration Type Documentation
Priority
enum MaNGOS::Priority
Enumerator
Priority_Idle
Priority_Lowest
Priority_Low
Priority_Normal
Priority_High
Priority_Highest
Priority_Realtime
Definition at line 43 of file Threading.h.
Function Documentation
at_exit()
void MaNGOS::at_exit (void(*)() func)
Definition at line 29 of file ObjectLifeTime.cpp.
References external_wrapper().
Referenced by MaNGOS::ObjectLifeTime< T >::ScheduleCall().
Compute()
template<class RET_TYPE , int CENTER_VAL> RET_TYPE MaNGOS::Compute (float x, float y, float center_offset, float size) inline
Definition at line 147 of file GridDefines.h.
ComputeCellPair()
CellPair MaNGOS::ComputeCellPair (float x, float y) inline
Definition at line 163 of file GridDefines.h.
References CENTER_GRID_CELL_OFFSET, and SIZE_OF_GRID_CELL.
Referenced by Map::ActiveObjectsNearGrid(), Map::Add(), ObjectAccessor::AddCorpse(), ObjectMgr::AddCreatureToGrid(), MapPersistentState::AddCreatureToGrid(), ObjectMgr::AddGameobjectToGrid(), MapPersistentState::AddGameobjectToGrid(), Map::AddToActive(), Cell::CalculateCellArea(), Map::CreatePlayerOnClient(), Map::CreatureRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::ExecuteDistWorker(), PlayerbotAI::findNearbyCreature(), Map::ForceLoadGrid(), Map::GameObjectRelocation(), ChatHandler::HandleGPSCommand(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), Map::PlayerRelocation(), Map::Remove(), ObjectAccessor::RemoveCorpse(), ObjectMgr::RemoveCreatureFromGrid(), MapPersistentState::RemoveCreatureFromGrid(), ObjectMgr::RemoveGameobjectFromGrid(), MapPersistentState::RemoveGameobjectFromGrid(), WorldObject::UpdateObjectVisibility(), ObjectGridRespawnMover::Visit(), Cell::VisitAllObjects(), Cell::VisitGridObjects(), and Cell::VisitWorldObjects().
ComputeGridPair()
GridPair MaNGOS::ComputeGridPair (float x, float y) inline
Definition at line 158 of file GridDefines.h.
References CENTER_GRID_OFFSET, and SIZE_OF_GRIDS.
Referenced by Map::AddToActive(), Corpse::Create(), MapManager::ExistMapAndVMap(), ChatHandler::HandleGPSCommand(), Map::IsLoaded(), Map::IsRemovalGrid(), Corpse::LoadFromDB(), and Map::RemoveFromActive().
Count() [1/5]
template<class SPECIFIC_TYPE > size_t MaNGOS::Count (const ContainerMapList< SPECIFIC_TYPE > & elements, SPECIFIC_TYPE *)
Definition at line 37 of file TypeContainerFunctions.h.
References ContainerMapList< OBJECT >::_element.
Referenced by TypeMapContainer< OBJECT_TYPES >::Count(), Count(), WheatyExceptionReport::DumpTypeIndex(), CombatConditionMgr::Load(), UnitConditionMgr::Load(), WorldStateExpressionMgr::Load(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), and CreatureEventAIMgr::LoadCreatureEventAI_Summons().
Count() [2/5]
template<class SPECIFIC_TYPE , class T > size_t MaNGOS::Count (const ContainerMapList< T > & , SPECIFIC_TYPE *)
Definition at line 49 of file TypeContainerFunctions.h.
Count() [3/5]
template<class SPECIFIC_TYPE , class H , class T > size_t MaNGOS::Count (const ContainerMapList< TypeList< H, T > > & elements, SPECIFIC_TYPE * fake)
Definition at line 61 of file TypeContainerFunctions.h.
References Count().
Count() [4/5]
template<class SPECIFIC_TYPE , class T > size_t MaNGOS::Count (const ContainerMapList< TypeList< SPECIFIC_TYPE, T > > & elements, SPECIFIC_TYPE * fake)
Definition at line 55 of file TypeContainerFunctions.h.
References Count().
Count() [5/5]
template<class SPECIFIC_TYPE > size_t MaNGOS::Count (const ContainerMapList< TypeNull > & , SPECIFIC_TYPE *)
Definition at line 43 of file TypeContainerFunctions.h.
external_wrapper()
void MaNGOS::external_wrapper (void * p)
Definition at line 24 of file ObjectLifeTime.cpp.
Referenced by at_exit().
Insert() [1/4]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* MaNGOS::Insert (ContainerMapList< SPECIFIC_TYPE > & elements, SPECIFIC_TYPE * obj)
Definition at line 68 of file TypeContainerFunctions.h.
References ContainerMapList< OBJECT >::_element.
Referenced by Insert(), and TypeMapContainer< OBJECT_TYPES >::insert().
Insert() [2/4]
template<class SPECIFIC_TYPE , class T > SPECIFIC_TYPE* MaNGOS::Insert (ContainerMapList< T > & , SPECIFIC_TYPE *)
Definition at line 83 of file TypeContainerFunctions.h.
Insert() [3/4]
template<class SPECIFIC_TYPE , class H , class T > SPECIFIC_TYPE* MaNGOS::Insert (ContainerMapList< TypeList< H, T > > & elements, SPECIFIC_TYPE * obj)
Definition at line 90 of file TypeContainerFunctions.h.
References Insert().
Insert() [4/4]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* MaNGOS::Insert (ContainerMapList< TypeNull > & , SPECIFIC_TYPE *)
Definition at line 76 of file TypeContainerFunctions.h.
IsValidMapCoord() [1/4]
bool MaNGOS::IsValidMapCoord (float c) inline
Definition at line 176 of file GridDefines.h.
References MAP_HALFSIZE.
Referenced by WaypointManager::AddExternalNode(), CinematicMgr::BeginCinematic(), PathFinder::calculate(), NamreebAnticheat::Movement::ExtrapolateMovement(), Creature::GetRespawnCoord(), WorldObject::IsPositionValid(), IsValidMapCoord(), MapManager::IsValidMapCoord(), WaypointManager::Load(), CreatureEventAIMgr::LoadCreatureEventAI_Summons(), ObjectMgr::LoadCreatures(), Player::LoadFromDB(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadPointsOfInterest(), ScriptMgr::LoadScripts(), SpellCastTargets::read(), Player::SetPosition(), CinematicMgr::UpdateCinematicLocation(), GenericTransport::UpdatePassengerPosition(), and WorldSession::VerifyMovementInfo().
IsValidMapCoord() [2/4]
bool MaNGOS::IsValidMapCoord (float x, float y) inline
Definition at line 181 of file GridDefines.h.
References IsValidMapCoord().
IsValidMapCoord() [3/4]
bool MaNGOS::IsValidMapCoord (float x, float y, float z) inline
Definition at line 186 of file GridDefines.h.
References IsValidMapCoord().
IsValidMapCoord() [4/4]
bool MaNGOS::IsValidMapCoord (float x, float y, float z, float o) inline
Definition at line 191 of file GridDefines.h.
References IsValidMapCoord().
NormalizeMapCoord()
void MaNGOS::NormalizeMapCoord (float & c) inline
Definition at line 168 of file GridDefines.h.
References MAP_HALFSIZE.
Referenced by npc_anubarak_trial_frostsphereAI::DamageTaken(), WorldObject::GetNearPoint2dAt(), WorldObject::GetRandomPoint(), WaypointManager::Load(), and WorldObject::MovePositionToFirstCollision().
Remove() [1/4]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* MaNGOS::Remove (ContainerMapList< SPECIFIC_TYPE > & , SPECIFIC_TYPE * obj)
Definition at line 98 of file TypeContainerFunctions.h.
Referenced by Remove(), and TypeMapContainer< OBJECT_TYPES >::remove().
Remove() [2/4]
template<class SPECIFIC_TYPE , class T > SPECIFIC_TYPE* MaNGOS::Remove (ContainerMapList< T > & , SPECIFIC_TYPE *)
Definition at line 112 of file TypeContainerFunctions.h.
Remove() [3/4]
template<class SPECIFIC_TYPE , class T , class H > SPECIFIC_TYPE* MaNGOS::Remove (ContainerMapList< TypeList< H, T > > & elements, SPECIFIC_TYPE * obj)
Definition at line 118 of file TypeContainerFunctions.h.
References Remove().
Remove() [4/4]
template<class SPECIFIC_TYPE > SPECIFIC_TYPE* MaNGOS::Remove (ContainerMapList< TypeNull > & , SPECIFIC_TYPE *)
Definition at line 105 of file TypeContainerFunctions.h.