CMaNGOS_WoTLK: UpdateFields Namespace Reference
UpdateFields Namespace Reference
Functions
uint16 const * GetUpdateFieldFlagsArray (uint8 objectTypeId)
UpdateFieldData const * GetUpdateFieldDataByName (char const *name)
UpdateFieldData const * GetUpdateFieldDataByTypeMaskAndOffset (uint8 objectTypeMask, uint16 offset)
Function Documentation
GetUpdateFieldDataByName()
UpdateFieldData const * UpdateFields::GetUpdateFieldDataByName (char const * name)
Definition at line 476 of file UpdateFields.cpp.
References g_updateFieldsData.
Referenced by ChatHandler::HandleDebugGetValueByNameCommand(), and ChatHandler::HandleDebugSetValueByNameCommand().
GetUpdateFieldDataByTypeMaskAndOffset()
UpdateFieldData const * UpdateFields::GetUpdateFieldDataByTypeMaskAndOffset (uint8 objectTypeMask, uint16 offset)
Definition at line 486 of file UpdateFields.cpp.
References g_updateFieldsData.
Referenced by ChatHandler::ShowUpdateFieldHelper().
GetUpdateFieldFlagsArray()
uint16 const * UpdateFields::GetUpdateFieldFlagsArray (uint8 objectTypeId)
Definition at line 445 of file UpdateFields.cpp.
References g_containerUpdateFieldFlags, g_corpseUpdateFieldFlags, g_dynamicObjectUpdateFieldFlags, g_gameObjectUpdateFieldFlags, g_playerUpdateFieldFlags, sLog, TYPEID_CONTAINER, TYPEID_CORPSE, TYPEID_DYNAMICOBJECT, TYPEID_GAMEOBJECT, TYPEID_ITEM, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by Object::GetUpdateFieldFlagsForTarget(), and Object::MarkUpdateFieldsWithFlagForUpdate().