CMaNGOS_WoTLK: ByteConverter Namespace Reference
ByteConverter Namespace Reference
ByteConverter reverse your byte order.
Functions
template<size_t T>
void convert (char *val)
template<>
void convert< 0 > (char *)
template<>
void convert< 1 > (char *)
template<typename T >
void apply (T *val)
Detailed Description
ByteConverter reverse your byte order.
This is use for cross platform where they have different endians.
Function Documentation
apply()
template<typename T > void ByteConverter::apply (T * val) inline
Definition at line 42 of file ByteConverter.h.
Referenced by Player::_ApplyAllLevelScaleItemMods(), Player::_ApplyItemBonuses(), Player::_ApplyItemMods(), Player::_ApplyWeaponDependentAuraCritMod(), Player::_ApplyWeaponDependentAuraDamageMod(), Player::_ApplyWeaponDependentAuraMods(), Player::AddSpellMod(), Unit::ApplyAttackTimePercentMod(), SpellAuraHolder::ApplyAuraModifiers(), Unit::ApplyAuraProcTriggerDamage(), Unit::ApplyCastTimePercentMod(), Unit::ApplyDiminishingAura(), Player::ApplyEnchantment(), Player::ApplyEquipSpell(), Player::ApplyFeralAPBonus(), ReputationMgr::ApplyForceReaction(), Player::ApplyGlyph(), Player::ApplyGlyphs(), Player::ApplyItemEquipSpell(), Player::ApplyItemOnStoreSpell(), Player::ApplyManaRegenBonus(), Unit::ApplyMaxPowerMod(), Object::ApplyModByteFlag(), Object::ApplyModFlag(), Object::ApplyModFlag64(), ApplyModFloatVar(), Aura::ApplyModifier(), Object::ApplyModInt32Value(), Object::ApplyModPositiveFloatValue(), Object::ApplyModShortFlag(), Object::ApplyModSignedFloatValue(), Object::ApplyModUInt32Value(), ApplyModUInt32Var(), Object::ApplyPercentModFloatValue(), ApplyPercentModFloatVar(), Unit::ApplyPowerMod(), Player::ApplyRatingMod(), Unit::ApplyResistanceBuffModsMod(), Unit::ApplyResistanceBuffModsPercentMod(), Unit::ApplySpellDispelImmunity(), Unit::ApplySpellImmune(), Player::ApplySpellPowerBonus(), Unit::ApplyStatBuffMod(), Unit::ApplyStatPercentBuffMod(), Map::ChangeGOPathfinding(), go_aura_generator::ChangeState(), Player::CorrectMetaGemEnchants(), BattleGroundIC::DoApplyTeamBuff(), ScriptedInstance::DoToggleGameObjectFlags(), Aura::HandleAddModifier(), Aura::HandleAoECharm(), Aura::HandleArenaPreparation(), Aura::HandleAuraAddMechanicAbilities(), Aura::HandleAuraAllowFlight(), Aura::HandleAuraAllowOnlyAbility(), Aura::HandleAuraControlVehicle(), Aura::HandleAuraConvertRune(), Aura::HandleAuraDamageShield(), Aura::HandleAuraDummy(), Aura::HandleAuraEmpathy(), Aura::HandleAuraFakeInebriation(), Aura::HandleAuraFeatherFall(), Aura::HandleAuraGhost(), Aura::HandleAuraHover(), Aura::HandleAuraIncreaseBaseHealthPercent(), Aura::HandleAuraMirrorImage(), Aura::HandleAuraModAllCritChance(), Aura::HandleAuraModAttackPower(), Aura::HandleAuraModAttackPowerPercent(), Aura::HandleAuraModBaseResistancePercent(), Aura::HandleAuraModBlockPercent(), Aura::HandleAuraModCritPercent(), Aura::HandleAuraModDisarm(), Aura::HandleAuraModDispelImmunity(), Aura::HandleAuraModDispelResist(), Aura::HandleAuraModDmgImmunity(), Aura::HandleAuraModDodgePercent(), Aura::HandleAuraModEffectImmunity(), Aura::HandleAuraModIncreaseEnergy(), Aura::HandleAuraModIncreaseEnergyPercent(), Aura::HandleAuraModIncreaseFlightSpeed(), Aura::HandleAuraModIncreaseHealth(), Aura::HandleAuraModIncreaseHealthPercent(), Aura::HandleAuraModIncreaseMaxHealth(), Aura::HandleAuraModIncreaseMountedSpeed(), Aura::HandleAuraModPacify(), Aura::HandleAuraModPacifyAndSilence(), Aura::HandleAuraModParryPercent(), Aura::HandleAuraModRangedAttackPower(), Aura::HandleAuraModRangedAttackPowerPercent(), Aura::HandleAuraModRangedHaste(), Aura::HandleAuraModResistance(), Aura::HandleAuraModResistanceExclusive(), Aura::HandleAuraModRoot(), Aura::HandleAuraModSchoolImmunity(), Aura::HandleAuraModShapeshift(), Aura::HandleAuraModSilence(), Aura::HandleAuraModSkill(), Aura::HandleAuraModStalked(), Aura::HandleAuraModStat(), Aura::HandleAuraModStateImmunity(), Aura::HandleAuraModStun(), Aura::HandleAuraModTotalHealthPercentRegen(), Aura::HandleAuraModTotalManaPercentRegen(), Aura::HandleAuraModTotalThreat(), Aura::HandleAuraMounted(), Aura::HandleAuraOpenStable(), Aura::HandleAuraPeriodicDummy(), Aura::HandleAuraPowerBurn(), Aura::HandleAuraProcTriggerSpell(), Aura::HandleAuraRetainComboPoints(), Aura::HandleAuraSetVehicleId(), Aura::HandleAuraStopNaturalManaRegen(), Aura::HandleAuraTrackCreatures(), Aura::HandleAuraTrackResources(), Aura::HandleAuraTrackStealthed(), Aura::HandleAuraTransform(), Aura::HandleAuraUntrackable(), Aura::HandleAuraWaterWalk(), Player::HandleBaseModValue(), Aura::HandleBindSight(), Aura::HandleChannelDeathItem(), Aura::HandleComprehendLanguage(), Aura::HandleDamagePercentTaken(), Aura::HandleDetectAmore(), Aura::HandleFactionOverride(), Aura::HandleFarSight(), Aura::HandleFeignDeath(), Aura::HandleForceMoveForward(), Aura::HandleForceReaction(), Aura::HandleInvisibility(), Aura::HandleInvisibilityDetect(), Aura::HandleManaShield(), Aura::HandleMirrorName(), Aura::HandleModAttackSpeed(), Aura::HandleModBaseResistance(), Aura::HandleModCastingSpeed(), Aura::HandleModCharm(), Aura::HandleModCombatSpeedPct(), Aura::HandleModConfuse(), Aura::HandleModDamageDone(), Aura::HandleModDamagePercentDone(), Aura::HandleModFear(), Aura::HandleModHealingPCT(), Aura::HandleModHitChance(), Aura::HandleModMechanicImmunity(), Aura::HandleModMechanicImmunityMask(), Aura::HandleModMeleeRangedSpeedPct(), Aura::HandleModMeleeSpeedPct(), Aura::HandleModOffhandDamagePercent(), Aura::HandleModPercentStat(), Aura::HandleModPossess(), Aura::HandleModPossessPet(), Aura::HandleModPowerCost(), Aura::HandleModPowerCostPCT(), Aura::HandleModPowerRegen(), Aura::HandleModRating(), Aura::HandleModRatingFromStat(), Aura::HandleModRegen(), Aura::HandleModResistancePercent(), Aura::HandleModSpellCritChance(), Aura::HandleModSpellCritChanceShool(), Aura::HandleModSpellHitChance(), Aura::HandleModStealth(), Aura::HandleModStealthDetect(), Aura::HandleModStealthLevel(), Aura::HandleModTargetResistance(), Aura::HandleModThreat(), Aura::HandleModTotalPercentStat(), Aura::HandleModUnattackable(), Aura::HandleOverrideClassScript(), WorldSession::HandlePartyAssignmentOpcode(), Aura::HandlePeriodicDamage(), Aura::HandlePeriodicDamagePCT(), Aura::HandlePeriodicEnergize(), Aura::HandlePeriodicHeal(), Aura::HandlePeriodicHealthFunnel(), Aura::HandlePeriodicLeech(), Aura::HandlePeriodicManaLeech(), Aura::HandlePeriodicTriggerSpell(), Aura::HandlePeriodicTriggerSpellWithValue(), Aura::HandlePhase(), Aura::HandlePreventFleeing(), Aura::HandlePreventResurrection(), Aura::HandleRangedAmmoHaste(), Aura::HandleSchoolAbsorb(), Aura::HandleShapeshiftBoosts(), Aura::HandleShieldBlockValue(), SpellAuraHolder::HandleSpellSpecificBoosts(), Aura::HandleSpiritOfRedemption(), Unit::HandleStatModifier(), HostileRefManager::HandleSuppressed(), GiddyUp::HandleTickAndApplication(), Aura::HandleTriggerLinkedAura(), Aura::HandleWaterBreathing(), Unit::ModifyAuraState(), Aura::OnAfterApply(), SnakeWrap::OnApply(), NetherChargeTimer::OnApply(), AshbringerItemAura::OnApply(), X52RocketHelmetAura::OnApply(), PowerCircleAura::OnApply(), IncreasedHealingDoneDummy::OnApply(), IncreasedHolyLightHealing::OnApply(), ArenaPreparation::OnApply(), InactiveBattleground::OnApply(), spell_repair_cannon_aura::OnApply(), DirebrewDisarmPrecast::OnApply(), PossessRazorgore::OnApply(), UnarmedWoodcutter::OnApply(), SparAuras::OnApply(), MoroesVanish::OnApply(), Enfeeble::OnApply(), Sacrifice::OnApply(), spell_mana_rage_selin::OnApply(), EyeOfAcherus::OnApply(), AnastariPossess::OnApply(), HexOfJammalanAura::OnApply(), DeathCloudBrutallus::OnApply(), spell_break_ice::OnApply(), DarkFlameShadowAura::OnApply(), DarkFlameFireAura::OnApply(), FogOfCorruptionCharm::OnApply(), TriggerStrafe::OnApply(), Encapsulate::OnApply(), SpectralRealmAura::OnApply(), CurseOfBoundlessAgony::OnApply(), DarknessOfSouls::OnApply(), SinisterReflectionClone::OnApply(), OpenPortalFromShattrath::OnApply(), VengeanceOfTheBlueFlight::OnApply(), ShieldOfTheBlue::OnApply(), SpellFury::OnApply(), CallOfTheBeast::OnApply(), ThreateningGaze::OnApply(), RenatakiVanishTeleport::OnApply(), EternalSilence::OnApply(), CThunMouthTentacle::OnApply(), HuhuranWyvernSting::OnApply(), TrueFulfillment::OnApply(), MutateBug::OnApply(), ViscidusFreeze::OnApply(), spell_remove_mushroom_power::OnApply(), FlyingMachineControls::OnApply(), spell_corrupt_soul_aura::OnApply(), spell_pursuit::OnApply(), spell_strangulating_aura::OnApply(), spell_feigh_death_pos_aura::OnApply(), spell_grip_of_agony_aura::OnApply(), spell_dark_transformation_aura::OnApply(), spell_dark_empowerment_aura::OnApply(), spell_dark_fanatic_martyrdom_aura::OnApply(), spell_dark_adherent_martyrdom_aura::OnApply(), RocketPack::OnApply(), WidowsEmbrace::OnApply(), MutatingInjection::OnApply(), AuraPreWarning::OnApply(), AuraWarning::OnApply(), ForcedObedience::OnApply(), ThaddiusCharge::OnApply(), spell_crystal_spike_visual_aura::OnApply(), spell_telestra_clone_dies_aura::OnApply(), spell_ride_oculus_drake_saddle::OnApply(), spell_twilight_shift_aura::OnApply(), spell_leave_twilight_realm_aura::OnApply(), spell_fiery_combustion_aura::OnApply(), spell_soul_consumption_aura::OnApply(), spell_petrifying_grip_aura::OnApply(), spell_carve_stone_aura::OnApply(), spell_ingvar_transform_aura::OnApply(), spell_awaken_subboss_aura::OnApply(), spell_create_spirit_fount_beam_aura::OnApply(), spell_protective_bubble_aura::OnApply(), spell_drained_aura::OnApply(), spell_void_shift_aura::OnApply(), CharmGeist::OnApply(), CharmDrakuruServant::OnApply(), DrakuramasTeleportScript01::OnApply(), DrakuramasTeleportScript02::OnApply(), DrakuramasTeleportScript03::OnApply(), DropDisguise::OnApply(), ScourgeDisguiseExpiring::OnApply(), ArgentStandUnitRideGargoyle::OnApply(), HaveWitheredBatwing::OnApply(), HaveMuddyMireMaggot::OnApply(), HaveAmberseed::OnApply(), HaveChilledSerpentMucus::OnApply(), FetchAlchemistsApprentice::OnApply(), ShapeOfTheBeast::OnApply(), HarpoonersMark::OnApply(), ParasiticShadowfiendAura::OnApply(), SupremusRandomTarget::OnApply(), ShadowOfDeath::OnApply(), VerasVanish::OnApply(), VerasDeadlyPoisonTick::OnApply(), Soaring::OnApply(), CoaxMarmot::OnApply(), VashjPersuasion::OnApply(), InsidiousWhisper::OnApply(), LeoWhirlwindAura::OnApply(), GronnLordsGrasp::OnApply(), ShadowGraspCube::OnApply(), ShadowGraspMagth::OnApply(), LivingFlareMaster::OnApply(), LivingFlareUnstable::OnApply(), CharmRavager::OnApply(), ScrapReaverSpell::OnApply(), RingOfFlame::OnApply(), TagGreaterFelfireDiemetradon::OnApply(), DragonmawIllusionBase::OnApply(), DragonmawIllusionTransform::OnApply(), PossessionTransfer::OnApply(), EredarPreGateBeam::OnApply(), FlyingAttackAura::OnApply(), ShivanShapeshiftForm::OnApply(), BuildPortableFelCannon::OnApply(), WrathOfTheAstromancer::OnApply(), WOTAOldDOT::OnApply(), ShadowyDisguise::OnApply(), StormcrowAmulet::OnApply(), GiddyUp::OnApply(), RamsteinsSwiftWorkRam::OnApply(), AppleTrapFriendly::OnApply(), BrewfestBarkerBunny::OnApply(), GDRPeriodicDamage::OnApply(), OgrilaFlasks::OnApply(), TestRibbonPoleChannel::OnApply(), BraziersHit::OnApply(), TorchesCaught::OnApply(), HorsemanManiacalLaugh::OnApply(), GreaterInvisibilityMob::OnApply(), InebriateRemoval::OnApply(), AuchenaiPossess::OnApply(), GettingSleepyAura::OnApply(), AllergiesAura::OnApply(), Drink::OnApply(), Stoned::OnApply(), SleepVisualFlavor::OnApply(), CallOfTheFalcon::OnApply(), DeathKnightDisease::OnApply(), DancingRuneWeapon::OnApply(), Brambles::OnApply(), RapidKilling::OnApply(), FingersOfFrostDummy::OnApply(), PainSuppression::OnApply(), LightwellRenew::OnApply(), GlyphOfLightwell::OnApply(), GlyphOfShadowWordDeath::OnApply(), ShadowAffinityDots::OnApply(), DirtyDeeds::OnApply(), KillingSpree::OnApply(), SentryTotem::OnApply(), CurseOfDoom::OnApply(), SeedOfCorruption::OnApply(), DemonicCircleSummon::OnApply(), Overpower::OnApply(), SpellReflectionRaid::OnApply(), Aura::OnApply(), ScriptDevAIMgr::OnItemLoot(), OnLootItemTaintedCore(), Unit::RegisterOverrideScriptAura(), Unit::RegisterScalingAura(), Unit::RegisterScriptedLocationAura(), UnitAI::SetAIImmobilizedState(), WorldState::SetBonfireActive(), Unit::SetConfused(), Player::SetEnchantmentModifier(), Player::SetEnvironmentFlags(), Unit::SetFeignDeath(), Unit::SetFleeing(), Unit::SetImmobilizedState(), VisibilityData::SetInvisibilityDetectMask(), VisibilityData::SetInvisibilityMask(), Player::SetLaunched(), CombatManager::SetLeashingDisable(), World::SetOnlinePlayer(), VisibilityData::SetStealthMask(), WorldObject::SetStringId(), Unit::SetStunned(), Unit::SetStunnedByLogout(), HostileRefManager::threatTemporaryFade(), Pet::ToggleAutocast(), CharmInfo::ToggleCreatureAutocast(), Player::ToggleMetaGemsActive(), AreaAura::Update(), CreatureSettings::updateFlag(), Player::UpdateKnownCurrencies(), and Player::UpdateSpellTrainedSkills().
convert()
template<size_t T> void ByteConverter::convert (char * val) inline
Definition at line 32 of file ByteConverter.h.
Referenced by boss_grand_warlock_nethekurseAI::DoTauntPeons().
convert< 0 >()
template<> void ByteConverter::convert< 0 > (char *) inline
Definition at line 38 of file ByteConverter.h.
convert< 1 >()
template<> void ByteConverter::convert< 1 > (char *) inline
Definition at line 39 of file ByteConverter.h.