CMaNGOS_WoTLK: VMAP Namespace Reference
VMAP Namespace Reference
This is the minimum interface to the VMapMamager.
Data Structures
class IVMapManager
class MapRayCallback
class AreaInfoCallback
class LocationInfoCallback
struct GroupLocationInfo
struct LocationInfo
class StaticMapTree
struct AreaInfo
class ModelSpawn
class ModelInstance
struct WMOLiquidHeader
class ModelPosition
This Class is used to convert raw vector data into balanced BSP-Trees.
struct MapSpawns
struct GroupModel_Raw
struct WorldModel_Raw
class TileAssembler
class VMapFactory
class ManagedModel
class VMapManager2
class IntersectionCallBack
class MyCollisionDetection
class TriBoundFunc
struct GModelRayCallback
struct WModelRayCallBack
class WModelAreaCallback
class MeshTriangle
class WmoLiquid
class GroupModel
class WorldModel
Typedefs
typedef std::map< uint32, ModelSpawn > UniqueEntryMap
typedef std::multimap< uint32, uint32 > TileMap
typedef std::map< uint32, MapSpawns * > MapData
typedef std::unordered_map< uint32, StaticMapTree * > InstanceTreeMap
typedef std::unordered_map< std::string, ManagedModel > ModelFileMap
Enumerations
enum VMAPLoadResult { VMAP_LOAD_RESULT_ERROR , VMAP_LOAD_RESULT_OK , VMAP_LOAD_RESULT_IGNORED }
enum ModelFlags { MOD_M2 = 1 , MOD_WORLDSPAWN = 1 << 1 , MOD_HAS_BOUND = 1 << 2 }
Functions
bool readChunk (FILE *rf, char *dest, const char *compare, uint32 len)
bool IntersectTriangle (MeshTriangle const &tri, std::vector< Vector3 >::const_iterator points, G3D::Ray const &ray, float &distance)
Variables
const char VMAP_MAGIC [] = "VMAP_7.0"
const char RAW_VMAP_MAGIC [] = "VMAPs05"
const char GAMEOBJECT_MODELS [] = "temp_gameobject_models"
std::mutex m_vmapMutex
IVMapManager * gVMapManager = nullptr
Detailed Description
This is the minimum interface to the VMapMamager.
The Class is mainly taken from G3D/AABSPTree.h but modified to be able to use our internal data structure.
This is the main Class to manage loading and unloading of maps, line of sight, height calculation and so on.
This is the access point to the VMapManager.
For each map or map tile to load it reads a directory file that contains the ModelContainer files used by this map or map tile. Each global map or instance has its own dynamic BSP-Tree. The loaded ModelContainers are included in one of these BSP-Trees. Additionally a table to match map ids and map names is used.
This is an iterator that helps us analysing the BSP-Trees. The collision detection is modified to return true, if we are inside an object.
Typedef Documentation
InstanceTreeMap
typedef std::unordered_map<uint32, StaticMapTree*> VMAP::InstanceTreeMap
Definition at line 63 of file VMapManager2.h.
MapData
typedef std::map<uint32, MapSpawns*> VMAP::MapData
Definition at line 63 of file TileAssembler.h.
ModelFileMap
typedef std::unordered_map<std::string, ManagedModel> VMAP::ModelFileMap
Definition at line 64 of file VMapManager2.h.
TileMap
typedef std::multimap<uint32, uint32> VMAP::TileMap
Definition at line 55 of file TileAssembler.h.
UniqueEntryMap
typedef std::map<uint32, ModelSpawn> VMAP::UniqueEntryMap
Definition at line 54 of file TileAssembler.h.
Enumeration Type Documentation
ModelFlags
enum VMAP::ModelFlags
Enumerator
MOD_M2
MOD_WORLDSPAWN
MOD_HAS_BOUND
Definition at line 35 of file ModelInstance.h.
VMAPLoadResult
enum VMAP::VMAPLoadResult
Enumerator
VMAP_LOAD_RESULT_ERROR
VMAP_LOAD_RESULT_OK
VMAP_LOAD_RESULT_IGNORED
Definition at line 33 of file IVMapManager.h.
Function Documentation
IntersectTriangle()
bool VMAP::IntersectTriangle (MeshTriangle const & tri, std::vector< Vector3 >::const_iterator points, G3D::Ray const & ray, float & distance)
Definition at line 35 of file WorldModel.cpp.
References EPS, VMAP::MeshTriangle::idx0, VMAP::MeshTriangle::idx1, and VMAP::MeshTriangle::idx2.
Referenced by VMAP::GModelRayCallback::operator()().
readChunk()
bool VMAP::readChunk (FILE * rf, char * dest, const char * compare, uint32 len)
Definition at line 40 of file TileAssembler.cpp.
Referenced by VMAP::StaticMapTree::CanLoadMap(), VMAP::StaticMapTree::InitMap(), VMAP::StaticMapTree::LoadMapTile(), VMAP::WorldModel::readFile(), VMAP::GroupModel::readFromFile(), and VMAP::StaticMapTree::UnloadMapTile().
Variable Documentation
GAMEOBJECT_MODELS
const char VMAP::GAMEOBJECT_MODELS[] = "temp_gameobject_models"
Definition at line 28 of file VMapDefinitions.h.
Referenced by VMAP::TileAssembler::exportGameobjectModels(), and GameObjectModel::LoadGOVmapModels().
gVMapManager
IVMapManager* VMAP::gVMapManager = nullptr
Definition at line 55 of file VMapFactory.cpp.
Referenced by VMAP::VMapFactory::clear(), and VMAP::VMapFactory::createOrGetVMapManager().
m_vmapMutex
std::mutex VMAP::m_vmapMutex
Definition at line 54 of file VMapFactory.cpp.
Referenced by VMAP::VMapFactory::clear(), and VMAP::VMapFactory::createOrGetVMapManager().
RAW_VMAP_MAGIC
const char VMAP::RAW_VMAP_MAGIC[] = "VMAPs05"
Definition at line 27 of file VMapDefinitions.h.
Referenced by VMAP::WorldModel_Raw::Read().
VMAP_MAGIC
const char VMAP::VMAP_MAGIC[] = "VMAP_7.0"
Definition at line 26 of file VMapDefinitions.h.
Referenced by VMAP::StaticMapTree::CanLoadMap(), VMAP::TileAssembler::convertWorld2(), VMAP::StaticMapTree::InitMap(), VMAP::StaticMapTree::LoadMapTile(), VMAP::WorldModel::readFile(), VMAP::StaticMapTree::UnloadMapTile(), and VMAP::WorldModel::writeFile().