CMaNGOS_WoTLK: Movement Namespace Reference
Movement Namespace Reference
Data Structures
struct FallInitializer
struct CommonInitializer
struct Location
class MoveSpline
class MoveSplineFlag
class MoveSplineInit
union FacingInfo
struct MoveSplineInitArgs
class PacketBuilder
class SplineBase
class Spline
class counter
Typedefs
typedef std::vector< G3D::Vector3 > PointsArray
typedef counter< uint32, 0xFFFFFFFF > UInt32Counter
Enumerations
enum { minimal_duration = 1 }
enum MonsterMoveType {
MonsterMoveNormal = 0 , MonsterMoveStop = 1 , MonsterMoveFacingSpot = 2 , MonsterMoveFacingTarget = 3 ,
MonsterMoveFacingAngle = 4
}
enum AnimType { ToGround = 0 , FlyToFly = 1 , ToFly = 2 , FlyToGround = 3 }
Functions
float computeFallElevation (float time, bool slowFall, float initialSpeed)
float computeFallTime (float path_length, bool isSafeFall)
float computeFallElevation (float time_passed)
uint32 computeDuration (float length, float velocity)
void operator<< (ByteBuffer &b, const Vector3 &v)
void operator>> (ByteBuffer &b, Vector3 &v)
void WriteLinearPath (const Spline< int32 > &spline, ByteBuffer &data)
void WriteCatmullRomPath (const Spline< int32 > &spline, ByteBuffer &data)
void WriteCatmullRomCyclicPath (Spline< int32 > const &spline, ByteBuffer &data)
static const Matrix4 s_catmullRomCoeffs (-0.5f, 1.5f, -1.5f, 0.5f, 1.f, -2.5f, 2.f, -0.5f, -0.5f, 0.f, 0.5f, 0.f, 0.f, 1.f, 0.f, 0.f)
static const Matrix4 s_Bezier3Coeffs (-1.f, 3.f, -3.f, 1.f, 3.f, -6.f, 3.f, 0.f, -3.f, 3.f, 0.f, 0.f, 1.f, 0.f, 0.f, 0.f)
void C_Evaluate (const Vector3 *vertice, float t, const Matrix4 &matr, Vector3 &result)
void C_Evaluate_Derivative (const Vector3 *vertice, float t, const Matrix4 &matr, Vector3 &result)
uint32 SecToMS (float sec)
float MSToSec (uint32 ms)
template<class Flags , int N>
void print_flags (Flags t, const char *(&names)[N], std::string &str)
Variables
float gravity = 19.29110527038574f
static thread_local uint32 splineCounter = 1
float terminalVelocity = 60.148003f
Velocity bounds that makes fall speed limited.
float terminalSavefallVelocity = 7.f
const float terminal_length = float(terminalVelocity* terminalVelocity) / (2.f* gravity)
const float terminal_savefall_length = (terminalSavefallVelocity* terminalSavefallVelocity) / (2.f* gravity)
const float terminalFallTime = float(terminalVelocity / gravity)
const char * g_MovementFlag_names []
const char * g_SplineFlag_names [32]
Typedef Documentation
PointsArray
typedef std::vector< Vector3 > Movement::PointsArray
Definition at line 41 of file WaypointMovementGenerator.h.
UInt32Counter
typedef counter<uint32, 0xFFFFFFFF> Movement::UInt32Counter
Definition at line 69 of file typedefs.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
minimal_duration
Definition at line 110 of file MoveSpline.cpp.
AnimType
enum Movement::AnimType
Enumerator
ToGround
FlyToFly
ToFly
FlyToGround
Definition at line 32 of file MoveSplineInit.h.
MonsterMoveType
enum Movement::MonsterMoveType
Enumerator
MonsterMoveNormal
MonsterMoveStop
MonsterMoveFacingSpot
MonsterMoveFacingTarget
MonsterMoveFacingAngle
Definition at line 29 of file MoveSpline.h.
Function Documentation
C_Evaluate()
void Movement::C_Evaluate (const Vector3 * vertice, float t, const Matrix4 & matr, Vector3 & result) inline
Definition at line 98 of file spline.cpp.
Referenced by Movement::SplineBase::EvaluateBezier3(), Movement::SplineBase::EvaluateCatmullRom(), Movement::SplineBase::SegLengthBezier3(), and Movement::SplineBase::SegLengthCatmullRom().
C_Evaluate_Derivative()
void Movement::C_Evaluate_Derivative (const Vector3 * vertice, float t, const Matrix4 & matr, Vector3 & result) inline
Definition at line 107 of file spline.cpp.
Referenced by Movement::SplineBase::EvaluateDerivativeBezier3(), and Movement::SplineBase::EvaluateDerivativeCatmullRom().
computeDuration()
uint32 Movement::computeDuration (float length, float velocity) inline
Definition at line 95 of file MoveSpline.cpp.
References SecToMS().
computeFallElevation() [1/2]
float Movement::computeFallElevation (float time, bool slowFall, float initialSpeed)
Definition at line 58 of file util.cpp.
References gravity, terminalFallTime, terminalSavefallVelocity, and terminalVelocity.
Referenced by Movement::MoveSpline::computeFallElevation(), NamreebAnticheat::Movement::ExtrapolateMovement(), Unit::KnockBackWithAngle(), MotionMaster::MoveJumpFacingVerticalSpeed(), and MotionMaster::MovePathAndJumpVerticalSpeed().
computeFallElevation() [2/2]
float Movement::computeFallElevation (float time_passed)
Definition at line 84 of file util.cpp.
References gravity, terminal_length, terminalFallTime, and terminalVelocity.
computeFallTime()
float Movement::computeFallTime (float path_length, bool isSafeFall)
Definition at line 34 of file util.cpp.
References gravity, terminal_length, terminal_savefall_length, terminalFallTime, terminalSavefallVelocity, and terminalVelocity.
Referenced by Movement::FallInitializer::operator()().
MSToSec()
float Movement::MSToSec (uint32 ms) inline
Definition at line 42 of file typedefs.h.
Referenced by Movement::MoveSpline::computeFallElevation(), Movement::MoveSpline::computeParabolicElevation(), and Movement::MoveSpline::Initialize().
operator<<()
void Movement::operator<< (ByteBuffer & b, const Vector3 & v) inline
Definition at line 25 of file packet_builder.cpp.
operator>>()
void Movement::operator>> (ByteBuffer & b, Vector3 & v) inline
Definition at line 30 of file packet_builder.cpp.
print_flags()
template<class Flags , int N> void Movement::print_flags (Flags t, const char *(&) names[N], std::string & str)
Definition at line 192 of file util.cpp.
Referenced by Movement::MoveSplineFlag::ToString().
s_Bezier3Coeffs()
static const Matrix4 Movement::s_Bezier3Coeffs (-1. f, 3. f, -3. f, 1. f, 3. f, -6. f, 3. f, 0. f, -3. f, 3. f, 0. f, 0. f, 1. f, 0. f, 0. f, 0. f) static
Referenced by Movement::SplineBase::EvaluateBezier3(), Movement::SplineBase::EvaluateDerivativeBezier3(), and Movement::SplineBase::SegLengthBezier3().
s_catmullRomCoeffs()
static const Matrix4 Movement::s_catmullRomCoeffs (-0. 5f, 1. 5f, -1. 5f, 0. 5f, 1. f, -2. 5f, 2. f, -0. 5f, -0. 5f, 0. f, 0. 5f, 0. f, 0. f, 1. f, 0. f, 0. f) static
Referenced by Movement::SplineBase::EvaluateCatmullRom(), Movement::SplineBase::EvaluateDerivativeCatmullRom(), and Movement::SplineBase::SegLengthCatmullRom().
SecToMS()
uint32 Movement::SecToMS (float sec) inline
Definition at line 37 of file typedefs.h.
Referenced by computeDuration().
WriteCatmullRomCyclicPath()
void Movement::WriteCatmullRomCyclicPath (Spline< int32 > const & spline, ByteBuffer & data)
Definition at line 105 of file packet_builder.cpp.
References ByteBuffer::append(), Movement::SplineBase::getPoint(), and Movement::SplineBase::getPointCount().
Referenced by Movement::PacketBuilder::WriteMonsterMove().
WriteCatmullRomPath()
void Movement::WriteCatmullRomPath (const Spline< int32 > & spline, ByteBuffer & data)
Definition at line 98 of file packet_builder.cpp.
References ByteBuffer::append(), Movement::SplineBase::getPoint(), and Movement::SplineBase::getPointCount().
Referenced by Movement::PacketBuilder::WriteMonsterMove().
WriteLinearPath()
void Movement::WriteLinearPath (const Spline< int32 > & spline, ByteBuffer & data)
Definition at line 79 of file packet_builder.cpp.
References ByteBuffer::appendPackXYZ(), Movement::SplineBase::getPoint(), and Movement::SplineBase::getPointCount().
Referenced by Movement::PacketBuilder::WriteMonsterMove().
Variable Documentation
g_MovementFlag_names
const char* Movement::g_MovementFlag_names[]
Definition at line 102 of file util.cpp.
g_SplineFlag_names
const char* Movement::g_SplineFlag_names[32]
Definition at line 155 of file util.cpp.
Referenced by Movement::MoveSplineFlag::ToString().
gravity
float Movement::gravity = 19.29110527038574f
Definition at line 24 of file util.cpp.
Referenced by computeFallElevation(), computeFallTime(), Spell::EffectJump(), Spell::EffectPullTowards(), Unit::KnockBackWithAngle(), MotionMaster::MoveJumpFacingVerticalSpeed(), and MotionMaster::MovePathAndJumpVerticalSpeed().
splineCounter
thread_local uint32 Movement::splineCounter = 1 static
Definition at line 29 of file MoveSplineInit.cpp.
Referenced by Movement::MoveSplineInit::Launch(), and Movement::MoveSplineInit::Stop().
terminal_length
const float Movement::terminal_length = float(terminalVelocity* terminalVelocity) / (2.f* gravity)
Definition at line 30 of file util.cpp.
Referenced by computeFallElevation(), and computeFallTime().
terminal_savefall_length
const float Movement::terminal_savefall_length = (terminalSavefallVelocity* terminalSavefallVelocity) / (2.f* gravity)
Definition at line 31 of file util.cpp.
Referenced by computeFallTime().
terminalFallTime
const float Movement::terminalFallTime = float(terminalVelocity / gravity)
Definition at line 32 of file util.cpp.
Referenced by computeFallElevation(), and computeFallTime().
terminalSavefallVelocity
float Movement::terminalSavefallVelocity = 7.f
Definition at line 28 of file util.cpp.
Referenced by computeFallElevation(), and computeFallTime().
terminalVelocity
float Movement::terminalVelocity = 60.148003f
Velocity bounds that makes fall speed limited.
Definition at line 27 of file util.cpp.
Referenced by computeFallElevation(), computeFallTime(), and NamreebAnticheat::Movement::GetMaxAllowedDist().