CMaNGOS_WoTLK: MaNGOS::XP Namespace Reference
MaNGOS::XP Namespace Reference
Enumerations
enum XPColorChar {
RED , ORANGE , YELLOW , GREEN ,
GRAY
}
Functions
bool IsTrivialLevelDifference (uint32 unitLvl, uint32 targetLvl)
uint32 GetGrayLevel (uint32 pl_level)
XPColorChar GetColorCode (uint32 pl_level, uint32 mob_level)
uint32 GetZeroDifference (uint32 unit_level)
uint32 BaseGain (uint32 unit_level, uint32 mob_level, ContentLevels content)
uint32 Gain (Unit const *unit, Creature *target)
float xp_in_group_rate (uint32 count, bool)
Enumeration Type Documentation
XPColorChar
enum MaNGOS::XP::XPColorChar
Enumerator
RED
ORANGE
YELLOW
GREEN
GRAY
Definition at line 61 of file Formulas.h.
Function Documentation
BaseGain()
uint32 MaNGOS::XP::BaseGain (uint32 unit_level, uint32 mob_level, ContentLevels content) inline
Definition at line 103 of file Formulas.h.
References CONTENT_1_60, CONTENT_61_70, CONTENT_71_80, GetZeroDifference(), IsTrivialLevelDifference(), and sLog.
Referenced by Gain().
Gain()
uint32 MaNGOS::XP::Gain (Unit const * unit, Creature * target) inline
Definition at line 133 of file Formulas.h.
References BaseGain(), CONFIG_FLOAT_RATE_XP_KILL, CreatureInfo::ExperienceMultiplier, GetContentLevelsForMapAndZone(), Creature::GetCreatureInfo(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetModifierXpBasedOnDamageReceived(), WorldObject::GetZoneId(), Creature::IsCritter(), Creature::IsElite(), Map::IsNonRaidDungeon(), Creature::IsNoXp(), Creature::IsPet(), Creature::IsTotem(), and sWorld.
Referenced by Group::RewardGroupAtKill(), RewardGroupAtKill_helper(), and Player::RewardSinglePlayerAtKill().
GetColorCode()
XPColorChar MaNGOS::XP::GetColorCode (uint32 pl_level, uint32 mob_level) inline
Definition at line 74 of file Formulas.h.
References GetGrayLevel(), GRAY, GREEN, ORANGE, RED, and YELLOW.
GetGrayLevel()
uint32 MaNGOS::XP::GetGrayLevel (uint32 pl_level) inline
Definition at line 63 of file Formulas.h.
Referenced by GetColorCode(), and Player::RewardHonor().
GetZeroDifference()
uint32 MaNGOS::XP::GetZeroDifference (uint32 unit_level) inline
Definition at line 87 of file Formulas.h.
Referenced by BaseGain().
IsTrivialLevelDifference()
bool MaNGOS::XP::IsTrivialLevelDifference (uint32 unitLvl, uint32 targetLvl) inline
Definition at line 35 of file Formulas.h.
Referenced by BaseGain(), Player::CalculateReputationGain(), GetDataForXPAtKill_helper(), Player::isHonorOrXPTarget(), and Unit::IsTrivialForTarget().
xp_in_group_rate()
float MaNGOS::XP::xp_in_group_rate (uint32 count, bool) inline
Definition at line 157 of file Formulas.h.
Referenced by Group::RewardGroupAtKill().