CMaNGOS_WoTLK: FactorySelector Namespace Reference
FactorySelector Namespace Reference
Functions
UnitAI * selectAI (Creature *creature)
UnitAI * GetSpecificAI (Unit *unit, std::string const &ainame)
MovementGenerator * selectMovementGenerator (Creature *creature)
Function Documentation
GetSpecificAI()
UnitAI * FactorySelector::GetSpecificAI (Unit * unit, std::string const & ainame)
Definition at line 94 of file CreatureAISelector.cpp.
References FactoryHolder< T, Key >::Create(), Unit::getClass(), GetClassAI(), Object::GetGuidStr(), Object::GetTypeId(), MANGOS_ASSERT, sLog, sScriptDevAIMgr, and TYPEID_UNIT.
Referenced by CharmInfo::SetCharmState().
selectAI()
UnitAI * FactorySelector::selectAI (Creature * creature)
Definition at line 38 of file CreatureAISelector.cpp.
References FactoryHolder< T, Key >::Create(), DEBUG_FILTER_LOG, Creature::GetAIName(), Object::GetGUIDLow(), Unit::HasCharmer(), Pet::isControlled(), Creature::IsGuard(), Creature::IsPet(), Unit::IsPlayerControlled(), Creature::IsTemporarySummon(), Creature::IsTotem(), FactoryHolder< T, Key >::key(), LOG_FILTER_AI_AND_MOVEGENSS, MANGOS_ASSERT, Permissible< T >::Permit(), PERMIT_BASE_NO, and sScriptDevAIMgr.
Referenced by Creature::AIM_Initialize().
selectMovementGenerator()
MovementGenerator * FactorySelector::selectMovementGenerator (Creature * creature)
Definition at line 116 of file CreatureAISelector.cpp.
References FactoryHolder< T, Key >::Create(), FOLLOW_MOTION_TYPE, Creature::GetCreatureInfo(), Creature::GetDefaultMovementType(), Unit::GetOwnerGuid(), Creature::IsPet(), ObjectGuid::IsPlayer(), and MANGOS_ASSERT.
Referenced by MotionMaster::Initialize().