var namespaceMaNGOS =
[
    [ "Honor", "namespaceMaNGOS_1_1Honor.html", [
      [ "hk_honor_at_level", "namespaceMaNGOS_1_1Honor.html#a249974b98a142bca70c8c8d8e9e69a3e", null ]
    ] ],
    [ "XP", "namespaceMaNGOS_1_1XP.html", [
      [ "XPColorChar", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4b", [
        [ "RED", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4ba27cb135627459d75a5c20c216555d4e3", null ],
        [ "ORANGE", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4bab7126adf14b849854163036d8383de58", null ],
        [ "YELLOW", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4ba18e5f6ffcb1269aa4c2b518d94cfa63c", null ],
        [ "GREEN", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4baffe35fb7eaaf93513e9365b28b65024f", null ],
        [ "GRAY", "namespaceMaNGOS_1_1XP.html#afc54bbbcb5be759cb12031b094af3b4ba1267c1fee107cb7c6f4c3466eba6a949", null ]
      ] ],
      [ "BaseGain", "namespaceMaNGOS_1_1XP.html#a4ca3ba4c828ac6de532bff687d0916e8", null ],
      [ "Gain", "namespaceMaNGOS_1_1XP.html#ab52d2788aed3890ab90db0b93e5b7544", null ],
      [ "GetColorCode", "namespaceMaNGOS_1_1XP.html#a45fe41286a35ad4547320a7fc8738c62", null ],
      [ "GetGrayLevel", "namespaceMaNGOS_1_1XP.html#ae0ae11e67609d6cbd2690a2df4a40a79", null ],
      [ "GetZeroDifference", "namespaceMaNGOS_1_1XP.html#a3f86dd026b1f18e4234a8ea934325226", null ],
      [ "IsTrivialLevelDifference", "namespaceMaNGOS_1_1XP.html#a001bc937a9e1fdc76962e77589fc20e7", null ],
      [ "xp_in_group_rate", "namespaceMaNGOS_1_1XP.html#a672a29c6d214dac4a4c3e2fa551cfb48", null ]
    ] ],
    [ "OperatorNew", "classMaNGOS_1_1OperatorNew.html", "classMaNGOS_1_1OperatorNew" ],
    [ "LocalStaticCreation", "classMaNGOS_1_1LocalStaticCreation.html", "classMaNGOS_1_1LocalStaticCreation" ],
    [ "CreateUsingMalloc", "classMaNGOS_1_1CreateUsingMalloc.html", "classMaNGOS_1_1CreateUsingMalloc" ],
    [ "CreateOnCallBack", "classMaNGOS_1_1CreateOnCallBack.html", "classMaNGOS_1_1CreateOnCallBack" ],
    [ "ObjectLifeTime", "classMaNGOS_1_1ObjectLifeTime.html", "classMaNGOS_1_1ObjectLifeTime" ],
    [ "Singleton", "classMaNGOS_1_1Singleton.html", "classMaNGOS_1_1Singleton" ],
    [ "GeneralLock", "classMaNGOS_1_1GeneralLock.html", "classMaNGOS_1_1GeneralLock" ],
    [ "SingleThreaded", "classMaNGOS_1_1SingleThreaded.html", [
      [ "Lock", "structMaNGOS_1_1SingleThreaded_1_1Lock.html", "structMaNGOS_1_1SingleThreaded_1_1Lock" ]
    ] ],
    [ "ObjectLevelLockable", "classMaNGOS_1_1ObjectLevelLockable.html", "classMaNGOS_1_1ObjectLevelLockable" ],
    [ "ClassLevelLockable", "classMaNGOS_1_1ClassLevelLockable.html", "classMaNGOS_1_1ClassLevelLockable" ],
    [ "_Callback", "classMaNGOS_1_1__Callback.html", "classMaNGOS_1_1__Callback" ],
    [ "_Callback< Class, ParamType1, ParamType2, ParamType3 >", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_00_01ParamType2_00_01ParamType3_01_4.html", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_00_01ParamType2_00_01ParamType3_01_4" ],
    [ "_Callback< Class, ParamType1, ParamType2 >", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_00_01ParamType2_01_4.html", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_00_01ParamType2_01_4" ],
    [ "_Callback< Class, ParamType1 >", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_01_4.html", "classMaNGOS_1_1__Callback_3_01Class_00_01ParamType1_01_4" ],
    [ "_Callback< Class >", "classMaNGOS_1_1__Callback_3_01Class_01_4.html", "classMaNGOS_1_1__Callback_3_01Class_01_4" ],
    [ "_SCallback", "classMaNGOS_1_1__SCallback.html", "classMaNGOS_1_1__SCallback" ],
    [ "_SCallback< ParamType1, ParamType2, ParamType3 >", "classMaNGOS_1_1__SCallback_3_01ParamType1_00_01ParamType2_00_01ParamType3_01_4.html", "classMaNGOS_1_1__SCallback_3_01ParamType1_00_01ParamType2_00_01ParamType3_01_4" ],
    [ "_SCallback< ParamType1, ParamType2 >", "classMaNGOS_1_1__SCallback_3_01ParamType1_00_01ParamType2_01_4.html", "classMaNGOS_1_1__SCallback_3_01ParamType1_00_01ParamType2_01_4" ],
    [ "_SCallback< ParamType1 >", "classMaNGOS_1_1__SCallback_3_01ParamType1_01_4.html", "classMaNGOS_1_1__SCallback_3_01ParamType1_01_4" ],
    [ "_SCallback<>", "classMaNGOS_1_1__SCallback_3_4.html", "classMaNGOS_1_1__SCallback_3_4" ],
    [ "ICallback", "classMaNGOS_1_1ICallback.html", "classMaNGOS_1_1ICallback" ],
    [ "_ICallback", "classMaNGOS_1_1__ICallback.html", "classMaNGOS_1_1__ICallback" ],
    [ "Callback", "classMaNGOS_1_1Callback.html", "classMaNGOS_1_1Callback" ],
    [ "Callback< Class, ParamType1, ParamType2, ParamType3 >", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_00_01ParamType3_01_4.html", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_00_01ParamType3_01_4" ],
    [ "Callback< Class, ParamType1, ParamType2 >", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_01_4.html", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_00_01ParamType2_01_4" ],
    [ "Callback< Class, ParamType1 >", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_01_4.html", "classMaNGOS_1_1Callback_3_01Class_00_01ParamType1_01_4" ],
    [ "Callback< Class >", "classMaNGOS_1_1Callback_3_01Class_01_4.html", "classMaNGOS_1_1Callback_3_01Class_01_4" ],
    [ "IQueryCallback", "classMaNGOS_1_1IQueryCallback.html", "classMaNGOS_1_1IQueryCallback" ],
    [ "_IQueryCallback", "classMaNGOS_1_1__IQueryCallback.html", "classMaNGOS_1_1__IQueryCallback" ],
    [ "QueryCallback", "classMaNGOS_1_1QueryCallback.html", "classMaNGOS_1_1QueryCallback" ],
    [ "QueryCallback< Class, ParamType1, ParamType2 >", "classMaNGOS_1_1QueryCallback_3_01Class_00_01ParamType1_00_01ParamType2_01_4.html", "classMaNGOS_1_1QueryCallback_3_01Class_00_01ParamType1_00_01ParamType2_01_4" ],
    [ "QueryCallback< Class, ParamType1 >", "classMaNGOS_1_1QueryCallback_3_01Class_00_01ParamType1_01_4.html", "classMaNGOS_1_1QueryCallback_3_01Class_00_01ParamType1_01_4" ],
    [ "QueryCallback< Class >", "classMaNGOS_1_1QueryCallback_3_01Class_01_4.html", "classMaNGOS_1_1QueryCallback_3_01Class_01_4" ],
    [ "SQueryCallback", "classMaNGOS_1_1SQueryCallback.html", "classMaNGOS_1_1SQueryCallback" ],
    [ "SQueryCallback< ParamType1, ParamType2 >", "classMaNGOS_1_1SQueryCallback_3_01ParamType1_00_01ParamType2_01_4.html", "classMaNGOS_1_1SQueryCallback_3_01ParamType1_00_01ParamType2_01_4" ],
    [ "SQueryCallback< ParamType1 >", "classMaNGOS_1_1SQueryCallback_3_01ParamType1_01_4.html", "classMaNGOS_1_1SQueryCallback_3_01ParamType1_01_4" ],
    [ "SQueryCallback<>", "classMaNGOS_1_1SQueryCallback_3_4.html", "classMaNGOS_1_1SQueryCallback_3_4" ],
    [ "AchievementChatBuilder", "classMaNGOS_1_1AchievementChatBuilder.html", "classMaNGOS_1_1AchievementChatBuilder" ],
    [ "BattleGroundChatBuilder", "classMaNGOS_1_1BattleGroundChatBuilder.html", "classMaNGOS_1_1BattleGroundChatBuilder" ],
    [ "BattleGroundYellBuilder", "classMaNGOS_1_1BattleGroundYellBuilder.html", "classMaNGOS_1_1BattleGroundYellBuilder" ],
    [ "BattleGroundMessageBuilder", "classMaNGOS_1_1BattleGroundMessageBuilder.html", "classMaNGOS_1_1BattleGroundMessageBuilder" ],
    [ "BattleGroundBroadcastBuilder", "classMaNGOS_1_1BattleGroundBroadcastBuilder.html", "classMaNGOS_1_1BattleGroundBroadcastBuilder" ],
    [ "BattleGround2ChatBuilder", "classMaNGOS_1_1BattleGround2ChatBuilder.html", "classMaNGOS_1_1BattleGround2ChatBuilder" ],
    [ "BattleGround2YellBuilder", "classMaNGOS_1_1BattleGround2YellBuilder.html", "classMaNGOS_1_1BattleGround2YellBuilder" ],
    [ "EmoteChatBuilder", "classMaNGOS_1_1EmoteChatBuilder.html", "classMaNGOS_1_1EmoteChatBuilder" ],
    [ "MonsterChatBuilder", "classMaNGOS_1_1MonsterChatBuilder.html", "classMaNGOS_1_1MonsterChatBuilder" ],
    [ "NearUsedPosDo", "classMaNGOS_1_1NearUsedPosDo.html", "classMaNGOS_1_1NearUsedPosDo" ],
    [ "VisibleNotifier", "structMaNGOS_1_1VisibleNotifier.html", "structMaNGOS_1_1VisibleNotifier" ],
    [ "VisibleChangesNotifier", "structMaNGOS_1_1VisibleChangesNotifier.html", "structMaNGOS_1_1VisibleChangesNotifier" ],
    [ "MessageDeliverer", "structMaNGOS_1_1MessageDeliverer.html", "structMaNGOS_1_1MessageDeliverer" ],
    [ "MessageDelivererExcept", "structMaNGOS_1_1MessageDelivererExcept.html", "structMaNGOS_1_1MessageDelivererExcept" ],
    [ "ObjectMessageDeliverer", "structMaNGOS_1_1ObjectMessageDeliverer.html", "structMaNGOS_1_1ObjectMessageDeliverer" ],
    [ "MessageDistDeliverer", "structMaNGOS_1_1MessageDistDeliverer.html", "structMaNGOS_1_1MessageDistDeliverer" ],
    [ "ObjectMessageDistDeliverer", "structMaNGOS_1_1ObjectMessageDistDeliverer.html", "structMaNGOS_1_1ObjectMessageDistDeliverer" ],
    [ "SpellMessageDestLocDeliverer", "structMaNGOS_1_1SpellMessageDestLocDeliverer.html", "structMaNGOS_1_1SpellMessageDestLocDeliverer" ],
    [ "ObjectUpdater", "structMaNGOS_1_1ObjectUpdater.html", "structMaNGOS_1_1ObjectUpdater" ],
    [ "PlayerVisitObjectsNotifier", "structMaNGOS_1_1PlayerVisitObjectsNotifier.html", "structMaNGOS_1_1PlayerVisitObjectsNotifier" ],
    [ "CreatureVisitObjectsNotifier", "structMaNGOS_1_1CreatureVisitObjectsNotifier.html", "structMaNGOS_1_1CreatureVisitObjectsNotifier" ],
    [ "DynamicObjectUpdater", "structMaNGOS_1_1DynamicObjectUpdater.html", "structMaNGOS_1_1DynamicObjectUpdater" ],
    [ "WorldObjectSearcher", "structMaNGOS_1_1WorldObjectSearcher.html", "structMaNGOS_1_1WorldObjectSearcher" ],
    [ "WorldObjectListSearcher", "structMaNGOS_1_1WorldObjectListSearcher.html", "structMaNGOS_1_1WorldObjectListSearcher" ],
    [ "WorldObjectWorker", "structMaNGOS_1_1WorldObjectWorker.html", "structMaNGOS_1_1WorldObjectWorker" ],
    [ "GameObjectSearcher", "structMaNGOS_1_1GameObjectSearcher.html", "structMaNGOS_1_1GameObjectSearcher" ],
    [ "GameObjectLastSearcher", "structMaNGOS_1_1GameObjectLastSearcher.html", "structMaNGOS_1_1GameObjectLastSearcher" ],
    [ "GameObjectListSearcher", "structMaNGOS_1_1GameObjectListSearcher.html", "structMaNGOS_1_1GameObjectListSearcher" ],
    [ "UnitSearcher", "structMaNGOS_1_1UnitSearcher.html", "structMaNGOS_1_1UnitSearcher" ],
    [ "UnitLastSearcher", "structMaNGOS_1_1UnitLastSearcher.html", "structMaNGOS_1_1UnitLastSearcher" ],
    [ "UnitListSearcher", "structMaNGOS_1_1UnitListSearcher.html", "structMaNGOS_1_1UnitListSearcher" ],
    [ "CreatureSearcher", "structMaNGOS_1_1CreatureSearcher.html", "structMaNGOS_1_1CreatureSearcher" ],
    [ "CreatureLastSearcher", "structMaNGOS_1_1CreatureLastSearcher.html", "structMaNGOS_1_1CreatureLastSearcher" ],
    [ "CreatureListSearcher", "structMaNGOS_1_1CreatureListSearcher.html", "structMaNGOS_1_1CreatureListSearcher" ],
    [ "CreatureWorker", "structMaNGOS_1_1CreatureWorker.html", "structMaNGOS_1_1CreatureWorker" ],
    [ "PlayerSearcher", "structMaNGOS_1_1PlayerSearcher.html", "structMaNGOS_1_1PlayerSearcher" ],
    [ "PlayerListSearcher", "structMaNGOS_1_1PlayerListSearcher.html", "structMaNGOS_1_1PlayerListSearcher" ],
    [ "PlayerWorker", "structMaNGOS_1_1PlayerWorker.html", "structMaNGOS_1_1PlayerWorker" ],
    [ "CameraDistWorker", "structMaNGOS_1_1CameraDistWorker.html", "structMaNGOS_1_1CameraDistWorker" ],
    [ "CameraDistLambdaWorker", "structMaNGOS_1_1CameraDistLambdaWorker.html", "structMaNGOS_1_1CameraDistLambdaWorker" ],
    [ "RaiseDeadObjectCheck", "classMaNGOS_1_1RaiseDeadObjectCheck.html", "classMaNGOS_1_1RaiseDeadObjectCheck" ],
    [ "ExplodeCorpseObjectCheck", "classMaNGOS_1_1ExplodeCorpseObjectCheck.html", "classMaNGOS_1_1ExplodeCorpseObjectCheck" ],
    [ "CannibalizeObjectCheck", "classMaNGOS_1_1CannibalizeObjectCheck.html", "classMaNGOS_1_1CannibalizeObjectCheck" ],
    [ "TauntFlagObjectCheck", "classMaNGOS_1_1TauntFlagObjectCheck.html", "classMaNGOS_1_1TauntFlagObjectCheck" ],
    [ "RespawnDo", "classMaNGOS_1_1RespawnDo.html", "classMaNGOS_1_1RespawnDo" ],
    [ "GameObjectFocusCheck", "classMaNGOS_1_1GameObjectFocusCheck.html", "classMaNGOS_1_1GameObjectFocusCheck" ],
    [ "NearestGameObjectFishingHoleCheck", "classMaNGOS_1_1NearestGameObjectFishingHoleCheck.html", "classMaNGOS_1_1NearestGameObjectFishingHoleCheck" ],
    [ "NearestGameObjectEntryInObjectRangeCheck", "classMaNGOS_1_1NearestGameObjectEntryInObjectRangeCheck.html", "classMaNGOS_1_1NearestGameObjectEntryInObjectRangeCheck" ],
    [ "AllGameObjectEntriesListInObjectRangeCheck", "classMaNGOS_1_1AllGameObjectEntriesListInObjectRangeCheck.html", "classMaNGOS_1_1AllGameObjectEntriesListInObjectRangeCheck" ],
    [ "AllGameObjectsMatchingOneEntryInRange", "classMaNGOS_1_1AllGameObjectsMatchingOneEntryInRange.html", "classMaNGOS_1_1AllGameObjectsMatchingOneEntryInRange" ],
    [ "AllGameObjectEntriesListInPosRangeCheck", "classMaNGOS_1_1AllGameObjectEntriesListInPosRangeCheck.html", "classMaNGOS_1_1AllGameObjectEntriesListInPosRangeCheck" ],
    [ "NearestGameObjectEntryInPosRangeCheck", "classMaNGOS_1_1NearestGameObjectEntryInPosRangeCheck.html", "classMaNGOS_1_1NearestGameObjectEntryInPosRangeCheck" ],
    [ "GameObjectEntryInPosRangeCheck", "classMaNGOS_1_1GameObjectEntryInPosRangeCheck.html", "classMaNGOS_1_1GameObjectEntryInPosRangeCheck" ],
    [ "GameObjectTypeInPosRangeCheck", "classMaNGOS_1_1GameObjectTypeInPosRangeCheck.html", "classMaNGOS_1_1GameObjectTypeInPosRangeCheck" ],
    [ "GameObjectInPosRangeCheck", "classMaNGOS_1_1GameObjectInPosRangeCheck.html", "classMaNGOS_1_1GameObjectInPosRangeCheck" ],
    [ "MostHPMissingInRangeCheck", "classMaNGOS_1_1MostHPMissingInRangeCheck.html", "classMaNGOS_1_1MostHPMissingInRangeCheck" ],
    [ "MostHPPercentMissingInRangeCheck", "classMaNGOS_1_1MostHPPercentMissingInRangeCheck.html", "classMaNGOS_1_1MostHPPercentMissingInRangeCheck" ],
    [ "FriendlyEligibleUnitConditionCheck", "classMaNGOS_1_1FriendlyEligibleUnitConditionCheck.html", "classMaNGOS_1_1FriendlyEligibleUnitConditionCheck" ],
    [ "FriendlyEligibleDispelInRangeCheck", "classMaNGOS_1_1FriendlyEligibleDispelInRangeCheck.html", "classMaNGOS_1_1FriendlyEligibleDispelInRangeCheck" ],
    [ "FriendlyMissingBuffInRangeInCombatCheck", "classMaNGOS_1_1FriendlyMissingBuffInRangeInCombatCheck.html", "classMaNGOS_1_1FriendlyMissingBuffInRangeInCombatCheck" ],
    [ "FriendlyMissingBuffInRangeNotInCombatCheck", "classMaNGOS_1_1FriendlyMissingBuffInRangeNotInCombatCheck.html", "classMaNGOS_1_1FriendlyMissingBuffInRangeNotInCombatCheck" ],
    [ "AnyUnfriendlyUnitInObjectRangeCheck", "classMaNGOS_1_1AnyUnfriendlyUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnyUnfriendlyUnitInObjectRangeCheck" ],
    [ "AnyUnfriendlyVisibleUnitInObjectRangeCheck", "classMaNGOS_1_1AnyUnfriendlyVisibleUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnyUnfriendlyVisibleUnitInObjectRangeCheck" ],
    [ "AnySpellAssistableUnitInObjectRangeCheck", "classMaNGOS_1_1AnySpellAssistableUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnySpellAssistableUnitInObjectRangeCheck" ],
    [ "AnyFriendlyUnitInObjectRangeCheck", "classMaNGOS_1_1AnyFriendlyUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnyFriendlyUnitInObjectRangeCheck" ],
    [ "AnyFriendlyOrGroupMemberUnitInUnitRangeCheck", "classMaNGOS_1_1AnyFriendlyOrGroupMemberUnitInUnitRangeCheck.html", "classMaNGOS_1_1AnyFriendlyOrGroupMemberUnitInUnitRangeCheck" ],
    [ "AnyUnitInObjectRangeCheck", "classMaNGOS_1_1AnyUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnyUnitInObjectRangeCheck" ],
    [ "AnyUnitFulfillingConditionInRangeCheck", "classMaNGOS_1_1AnyUnitFulfillingConditionInRangeCheck.html", "classMaNGOS_1_1AnyUnitFulfillingConditionInRangeCheck" ],
    [ "NearestAttackableUnitInObjectRangeCheck", "classMaNGOS_1_1NearestAttackableUnitInObjectRangeCheck.html", "classMaNGOS_1_1NearestAttackableUnitInObjectRangeCheck" ],
    [ "AnyAoETargetUnitInObjectRangeCheck", "classMaNGOS_1_1AnyAoETargetUnitInObjectRangeCheck.html", "classMaNGOS_1_1AnyAoETargetUnitInObjectRangeCheck" ],
    [ "CallOfHelpCreatureInRangeDo", "classMaNGOS_1_1CallOfHelpCreatureInRangeDo.html", "classMaNGOS_1_1CallOfHelpCreatureInRangeDo" ],
    [ "AnyDeadUnitCheck", "classMaNGOS_1_1AnyDeadUnitCheck.html", "classMaNGOS_1_1AnyDeadUnitCheck" ],
    [ "AnyStealthedCheck", "classMaNGOS_1_1AnyStealthedCheck.html", "classMaNGOS_1_1AnyStealthedCheck" ],
    [ "AnyAssistCreatureInRangeCheck", "classMaNGOS_1_1AnyAssistCreatureInRangeCheck.html", "classMaNGOS_1_1AnyAssistCreatureInRangeCheck" ],
    [ "NearestAssistCreatureInCreatureRangeCheck", "classMaNGOS_1_1NearestAssistCreatureInCreatureRangeCheck.html", "classMaNGOS_1_1NearestAssistCreatureInCreatureRangeCheck" ],
    [ "NearestCreatureEntryWithLiveStateInObjectRangeCheck", "classMaNGOS_1_1NearestCreatureEntryWithLiveStateInObjectRangeCheck.html", "classMaNGOS_1_1NearestCreatureEntryWithLiveStateInObjectRangeCheck" ],
    [ "AllCreatureEntriesWithLiveStateInObjectRangeCheck", "classMaNGOS_1_1AllCreatureEntriesWithLiveStateInObjectRangeCheck.html", "classMaNGOS_1_1AllCreatureEntriesWithLiveStateInObjectRangeCheck" ],
    [ "AllCreaturesOfEntryInRangeCheck", "classMaNGOS_1_1AllCreaturesOfEntryInRangeCheck.html", "classMaNGOS_1_1AllCreaturesOfEntryInRangeCheck" ],
    [ "AllCreaturesMatchingOneEntryInRange", "classMaNGOS_1_1AllCreaturesMatchingOneEntryInRange.html", "classMaNGOS_1_1AllCreaturesMatchingOneEntryInRange" ],
    [ "AnyPlayerInObjectRangeCheck", "classMaNGOS_1_1AnyPlayerInObjectRangeCheck.html", "classMaNGOS_1_1AnyPlayerInObjectRangeCheck" ],
    [ "AnyPlayerInObjectRangeWithAuraCheck", "classMaNGOS_1_1AnyPlayerInObjectRangeWithAuraCheck.html", "classMaNGOS_1_1AnyPlayerInObjectRangeWithAuraCheck" ],
    [ "AnyPlayerInCapturePointRange", "classMaNGOS_1_1AnyPlayerInCapturePointRange.html", "classMaNGOS_1_1AnyPlayerInCapturePointRange" ],
    [ "LocalizedPacketDo", "classMaNGOS_1_1LocalizedPacketDo.html", "classMaNGOS_1_1LocalizedPacketDo" ],
    [ "LocalizedPacketListDo", "classMaNGOS_1_1LocalizedPacketListDo.html", "classMaNGOS_1_1LocalizedPacketListDo" ],
    [ "SpellNotifierPlayer", "structMaNGOS_1_1SpellNotifierPlayer.html", "structMaNGOS_1_1SpellNotifierPlayer" ],
    [ "SpellNotifierCreatureAndPlayer", "structMaNGOS_1_1SpellNotifierCreatureAndPlayer.html", "structMaNGOS_1_1SpellNotifierCreatureAndPlayer" ],
    [ "WorldWorldTextBuilder", "classMaNGOS_1_1WorldWorldTextBuilder.html", "classMaNGOS_1_1WorldWorldTextBuilder" ],
    [ "Runnable", "classMaNGOS_1_1Runnable.html", "classMaNGOS_1_1Runnable" ],
    [ "Thread", "classMaNGOS_1_1Thread.html", "classMaNGOS_1_1Thread" ],
    [ "Listener", "classMaNGOS_1_1Listener.html", "classMaNGOS_1_1Listener" ],
    [ "NetworkThread", "classMaNGOS_1_1NetworkThread.html", "classMaNGOS_1_1NetworkThread" ],
    [ "PacketBuffer", "classMaNGOS_1_1PacketBuffer.html", "classMaNGOS_1_1PacketBuffer" ],
    [ "Socket", "classMaNGOS_1_1Socket.html", "classMaNGOS_1_1Socket" ],
    [ "thread_local_ptr", "classMaNGOS_1_1thread__local__ptr.html", "classMaNGOS_1_1thread__local__ptr" ],
    [ "Priority", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6", [
      [ "Priority_Idle", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a49cf0b87d45e233ea05f7897784a28d0", null ],
      [ "Priority_Lowest", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a75c4e5555f911c2ce0eecf13bef1d34f", null ],
      [ "Priority_Low", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a4786e673814c550de631f6c630960c17", null ],
      [ "Priority_Normal", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a4c909c1693ed928791f5b7f1b89cf4e2", null ],
      [ "Priority_High", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a4ca3be5b84d68a313909a9886bc50d0c", null ],
      [ "Priority_Highest", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6a3b3b04e4810b988671eb29d83edc76d5", null ],
      [ "Priority_Realtime", "namespaceMaNGOS.html#a26bb3d86372e89c1043138b813d180b6aa2888d1fa1ee6c192199c9b46464b73d", null ]
    ] ],
    [ "at_exit", "namespaceMaNGOS.html#a534c8c2fe5b1f724889ba0d19bda3afd", null ],
    [ "Compute", "namespaceMaNGOS.html#a77769727b52114bfc49b6cd523c7936c", null ],
    [ "ComputeCellPair", "namespaceMaNGOS.html#a2030ee366e660e360eb8ad58bab504de", null ],
    [ "ComputeGridPair", "namespaceMaNGOS.html#a83eaae9c047b36a392abe0b9143e6ab1", null ],
    [ "Count", "namespaceMaNGOS.html#a6125162effed92302a44154f30d8ae76", null ],
    [ "Count", "namespaceMaNGOS.html#a7cd8e75a496aab0d15b23a6bd5ff35d8", null ],
    [ "Count", "namespaceMaNGOS.html#aef3c05c85853ea113a795291499607e3", null ],
    [ "Count", "namespaceMaNGOS.html#afb508809e8139157293bd1e48c6403ca", null ],
    [ "Count", "namespaceMaNGOS.html#a360fd2ebc6871021995db7864f3f234d", null ],
    [ "external_wrapper", "namespaceMaNGOS.html#a2204676ab02692c8a97e070e5f351a75", null ],
    [ "Insert", "namespaceMaNGOS.html#a896f0d4f419cb5d71ee46463b235547e", null ],
    [ "Insert", "namespaceMaNGOS.html#ac9c5207fb24e91d2c0ec714d7cb47d43", null ],
    [ "Insert", "namespaceMaNGOS.html#a5668685d4ad02bcf710d977a77b9a4a5", null ],
    [ "Insert", "namespaceMaNGOS.html#acde6b7d58222b8a670c41f0cc8afa7c0", null ],
    [ "IsValidMapCoord", "namespaceMaNGOS.html#ae0f51133c9887d1ccc5b1dcc7e39f5e9", null ],
    [ "IsValidMapCoord", "namespaceMaNGOS.html#ac7ced8ea605d09be1ef538f2e8d56012", null ],
    [ "IsValidMapCoord", "namespaceMaNGOS.html#a0111a55484c24954e4b15fe645184aba", null ],
    [ "IsValidMapCoord", "namespaceMaNGOS.html#ac5b062819b97466a1a3a29872a2e43ba", null ],
    [ "NormalizeMapCoord", "namespaceMaNGOS.html#ab141af3a8bd076c3c5186961d1ac1468", null ],
    [ "Remove", "namespaceMaNGOS.html#a8eb9f0041f8b8300680e1dd65b889ea2", null ],
    [ "Remove", "namespaceMaNGOS.html#a446cbd9de833f24435f6e211d76c5f55", null ],
    [ "Remove", "namespaceMaNGOS.html#a267f6042d1010b01d6559ecf551c28af", null ],
    [ "Remove", "namespaceMaNGOS.html#ac905e8bc500b3ea01d0fa5c8e896a452", null ]
];