CMaNGOS_WoTLK: naxxramas.cpp File Reference
naxxramas.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Functions
InstanceData * GetInstanceData_instance_naxxramas (Map *pMap)
bool AreaTrigger_at_naxxramas (Player *player, AreaTriggerEntry const *areaTrigger)
void AddSC_instance_naxxramas ()
Variables
static const DialogueEntry aNaxxDialogue []
Function Documentation
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
Definition at line 860 of file naxxramas.cpp.
References AreaTrigger_at_naxxramas(), Script::GetInstanceData, GetInstanceData_instance_naxxramas(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_naxxramas()
bool AreaTrigger_at_naxxramas (Player * player, AreaTriggerEntry const * areaTrigger)
Definition at line 803 of file naxxramas.cpp.
References AREATRIGGER_FROSTWYRM_TELE, AREATRIGGER_KELTHUZAD, AREATRIGGER_THADDIUS_DOOR, DONE, DoScriptText(), instance_naxxramas::GetData(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), NOT_STARTED, NPC_KELTHUZAD, NPC_THADDIUS, SAY_THADDIUS_GREET, instance_naxxramas::SetChamberCenterCoords(), instance_naxxramas::SetData(), SPECIAL, TYPE_FOUR_HORSEMEN, TYPE_KELTHUZAD, TYPE_LOATHEB, TYPE_MAEXXNA, TYPE_THADDIUS, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_instance_naxxramas().
GetInstanceData_instance_naxxramas()
InstanceData* GetInstanceData_instance_naxxramas (Map * pMap)
Definition at line 798 of file naxxramas.cpp.
Referenced by AddSC_instance_naxxramas().
Variable Documentation
aNaxxDialogue
const DialogueEntry aNaxxDialogue[] static
Initial value:
=
{
    {NPC_KELTHUZAD,         0,                  10000},
    {SAY_SAPP_DIALOG1,      NPC_KELTHUZAD,      8000},
    {SAY_SAPP_DIALOG2_LICH, NPC_THE_LICHKING,   14000},
    {SAY_SAPP_DIALOG3,      NPC_KELTHUZAD,      10000},
    {SAY_SAPP_DIALOG4_LICH, NPC_THE_LICHKING,   12000},
    {SAY_SAPP_DIALOG5,      NPC_KELTHUZAD,      0},
    {NPC_THANE,             0,                  10000},
    {SAY_KORT_TAUNT1,       NPC_THANE,          5000},
    {SAY_ZELI_TAUNT1,       NPC_ZELIEK,         6000},
    {SAY_BLAU_TAUNT1,       NPC_BLAUMEUX,       6000},
    {SAY_RIVE_TAUNT1,       NPC_RIVENDARE,      6000},
    {SAY_BLAU_TAUNT2,       NPC_BLAUMEUX,       6000},
    {SAY_ZELI_TAUNT2,       NPC_ZELIEK,         5000},
    {SAY_KORT_TAUNT2,       NPC_THANE,          7000},
    {SAY_RIVE_TAUNT2,       NPC_RIVENDARE,      0},
    {0, 0, 0}
}
Definition at line 27 of file naxxramas.cpp.