CMaNGOS_WoTLK: netherstorm.cpp File Reference
netherstorm.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "AI/ScriptDevAI/scripts/outland/world_outland.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_manaforge_spawnAI
struct npc_manaforge_control_consoleAI
struct npc_commander_dawnforgeAI
struct npc_bessyAI
struct npc_maxx_a_million_escortAI
struct npc_zeppitAI
struct npc_protectorate_demolitionistAI
struct npc_captured_vanguardAI
struct npc_drijyaAI
struct npc_saeed_escortAI
struct npc_dimensiusAI
struct npc_salhadaarAI
struct npc_energy_ballAI
struct npc_void_conduitAI
struct npc_scrap_reaverAI
struct ScrapReaverSpell
struct npc_scrapped_fel_reaverAI
struct npc_adyen_the_lightwardenAI
struct npc_kaylaan_the_lostAI
struct Soulbind
struct UltraDeconsolodationZapper
struct ThrowBoomsDoom
struct RingOfFlame
Macros
#define GOSSIP_ITEM_SHUTDOWN "<Begin emergency shutdown.>"
Enumerations
enum {
EMOTE_START = -1000211 , EMOTE_60 = -1000212 , EMOTE_30 = -1000213 , EMOTE_10 = -1000214 ,
EMOTE_COMPLETE = -1000215 , EMOTE_ABORT = -1000216 , SAY_MANFORGE_SHUTDOWN_1 = -1000474 , SAY_MANFORGE_SHUTDOWN_2 = -1000475 ,
YEL_MANFORGE_SHUTDOWN = -1000476 , GOSSIP_TEXT_CONSOLE = 10045 , GOSSIP_TEXT_CONSOLE_NOQUEST = 9922 , GO_BANAAR_C_CONSOLE = 183770 ,
GO_CORUU_C_CONSOLE = 183956 , GO_DURO_C_CONSOLE = 184311 , GO_ARA_C_CONSOLE = 184312 , NPC_BNAAR_C_CONSOLE = 20209 ,
NPC_CORUU_C_CONSOLE = 20417 , NPC_DURO_C_CONSOLE = 20418 , NPC_ARA_C_CONSOLE = 20440 , NPC_SUNFURY_TECH = 20218 ,
NPC_SUNFURY_PROT = 20436 , NPC_SUNFURY_WARP_MASTER = 18857 , NPC_SUNFURY_WARP_ENGINEER = 18852 , NPC_SUNFURY_RESEARCHER = 20136 ,
NPC_ARA_TECH = 20438 , NPC_ARA_ENGI = 20439 , NPC_ARA_GORKLONN = 20460 , QUEST_SHUTDOWN_BNAAR_ALDOR = 10299 ,
QUEST_SHUTDOWN_BNAAR_SCRYERS = 10329 , QUEST_SHUTDOWN_CORUU_ALDOR = 10321 , QUEST_SHUTDOWN_CORUU_SCRYERS = 10330 , QUEST_SHUTDOWN_DURO_ALDOR = 10322 ,
QUEST_SHUTDOWN_DURO_SCRYERS = 10338 , QUEST_SHUTDOWN_ARA_ALDOR = 10323 , QUEST_SHUTDOWN_ARA_SCRYERS = 10365 , ITEM_BNAAR_ACESS_CRYSTAL = 29366 ,
ITEM_CORUU_ACESS_CRYSTAL = 29396 , ITEM_DURO_ACESS_CRYSTAL = 29397 , ITEM_ARA_ACESS_CRYSTAL = 29411 , SPELL_DISABLE_VISUAL = 35031 ,
SPELL_INTERRUPT_1 = 35016 , SPELL_INTERRUPT_2 = 35176
}
enum {
SAY_COMMANDER_DAWNFORGE_1 = -1000128 , SAY_ARCANIST_ARDONIS_1 = -1000129 , SAY_COMMANDER_DAWNFORGE_2 = -1000130 , SAY_PATHALEON_THE_CALCULATOR_IMAGE_1 = -1000131 ,
SAY_COMMANDER_DAWNFORGE_3 = -1000132 , SAY_PATHALEON_THE_CALCULATOR_IMAGE_2 = -1000133 , SAY_PATHALEON_THE_CALCULATOR_IMAGE_2_1 = -1000134 , SAY_PATHALEON_THE_CALCULATOR_IMAGE_2_2 = -1000135 ,
SAY_COMMANDER_DAWNFORGE_4 = -1000136 , SAY_ARCANIST_ARDONIS_2 = -1000136 , SAY_COMMANDER_DAWNFORGE_5 = -1000137 , QUEST_INFO_GATHERING = 10198 ,
SPELL_SUNFURY_DISGUISE = 34603 , NPC_ARCANIST_ARDONIS = 19830 , NPC_COMMANDER_DAWNFORGE = 19831 , NPC_PATHALEON_THE_CALCULATOR_IMAGE = 21504
}
enum {
QUEST_COWS_COME_HOME = 10337 , NPC_THADELL = 20464 , NPC_TORMENTED_SOUL = 20512 , NPC_SEVERED_SPIRIT = 19881 ,
SAY_ESCORT_1 = -1015100 , SAY_ESCORT_2 = -1015101 , SAY_THADELL = -1015102
}
enum {
QUEST_MARK_V_IS_ALIVE = 10191 , NPC_BOT_SPECIALIST_ALLEY = 19578 , GO_DRAENEI_MACHINE = 183771 , SAY_START = -1000621 ,
SAY_ALLEY_FAREWELL = -1000622 , SAY_CONTINUE = -1000623 , SAY_ALLEY_FINISH = -1000624
}
enum { EMOTE_GATHER_BLOOD = -1000625 , NPC_WARP_CHASER = 18884 , SPELL_GATHER_WARP_BLOOD = 39244 }
enum {
SAY_INTRO = -1000891 , SAY_ATTACKED_1 = -1000892 , SAY_ATTACKED_2 = -1000893 , SAY_STAGING_GROUNDS = -1000894 ,
SAY_TOXIC_HORROR = -1000895 , SAY_SALHADAAR = -1000896 , SAY_DISRUPTOR = -1000897 , SAY_NEXUS_PROTECT = -1000898 ,
SAY_FINISH_1 = -1000899 , SAY_FINISH_2 = -1000900 , SPELL_SPAWN = 12980 , SPELL_PROTECTORATE = 35679 ,
NPC_NEXUS_STALKER = 20474 , NPC_ARCHON = 20458 , FACTION_ESCORT = 1795 , QUEST_ID_DELIVERING_MESSAGE = 10406
}
enum {
SAY_VANGUARD_INTRO = -1000901 , SAY_VANGUARD_START = -1000902 , SAY_VANGUARD_FINISH = -1000903 , EMOTE_VANGUARD_FINISH = -1000904 ,
SPELL_GLAIVE = 36500 , SPELL_HAMSTRING = 31553 , NPC_COMMANDER_AMEER = 20448 , NPC_ETHEREUM_GLADIATOR = 20854 ,
QUEST_ID_ESCAPE_STAGING_GROUNDS = 10425
}
enum {
SAY_DRIJYA_START = -1000968 , SAY_DRIJYA_1 = -1000969 , SAY_DRIJYA_2 = -1000970 , SAY_DRIJYA_3 = -1000971 ,
SAY_DRIJYA_4 = -1000972 , SAY_DRIJYA_5 = -1000973 , SAY_DRIJYA_6 = -1000974 , SAY_DRIJYA_7 = -1000975 ,
SAY_DRIJYA_COMPLETE = -1000976 , SPELL_EXPLOSION_VISUAL = 30934 , NPC_EXPLODE_TRIGGER = 20296 , NPC_TERROR_IMP = 20399 ,
NPC_LEGION_TROOPER = 20402 , NPC_LEGION_DESTROYER = 20403 , QUEST_ID_WARP_GATE = 10310 , MAX_TROOPERS = 3 ,
MAX_IMPS = 6
}
enum {
QUEST_DIMENSIUS_ALL_DEVOURING = 10439 , NPC_PROTECTORATE_DEFENDER = 20984 , NPC_PROTECTORATE_REGENERATOR = 21783 , NPC_PROTECTORATE_AVENGER = 21805 ,
NPC_DIMENSIUS = 19554 , FACTION_PROTECTORATE_ESCORT = 1807 , SAY_SAEED_START = -1015033 , SAY_SAEED_PREPARE = -1015034 ,
SAY_SAEED_ATTACK = -1015035 , EMOTE_DIMENSIUS_LAUGH = -1015036 , SAY_SAEED_TAUNT = -1015037 , SAY_AVENGER_QUEST_COMPLETE = -1015038 ,
SPELL_SAEED_CLEAVE = 15496 , SPELL_TELEPORT = 35517
}
enum {
SAY_AGGRO = -1001170 , SAY_SUMMON = -1001171 , SPELL_DIMENSIUS_FEEDING = 37450 , SPELL_SHADOW_SPIRAL = 37500 ,
SPELL_SHADOW_VAULT = 37412 , NPC_SPAWN_OF_DIMENSIUS = 21780 , NPC_CAPTAIN_SAEED = 20985 , MODEL_ID_DIMENSIUS_CLOUD = 20011
}
enum {
NPC_ENERGY_BALL = 20769 , NPC_SALHADAAR = 20454 , SPELL_FLOAT = 37613 , SPELL_SALAADIN_TESLA = 35515 ,
SPELL_PROTECTORATE_DISRUPTOR = 35683 , SPELL_SALAADIN_OVERSPARK = 35684 , SPELL_GRAVITY_FLUX = 36533 , SPELL_STASIS = 36527 ,
SPELL_MIRROR_IMAGE_1 = 36847 , SPELL_MIRROR_IMAGE_2 = 36848 , FACTION_SALHADAAR_HOSTILE = 14 , SAY_THREAT = -1000138
}
enum { SPELL_PHASE_DISRUPTOR = 35734 }
enum { NPC_NEGATRON = 19851 , SPELL_SCRAP_REAVER = 34630 , SAY_ON_DEATH = -1000472 , AREA_PROVING_GROUNDS = 3873 }
enum { SPELL_FEL_ZAPPER = 35282 , NPC_ZAXXIS_AMBUSHER = 20287 , SAY_EVENT_START = -1000473 , COUNT_SPAWNING_LOCATIONS = 4 }
enum {
QUEST_DEATHBLOW_TO_THE_LEGION = 10409 , FACTION_DEATHBLOW = 250 , FACTION_DEATHBLOW_IN_PROGRESS = 495 , FACTION_SHATTRATH = 1743 ,
FACTION_KAYLAAN_HOSTILE = 14 , FACTION_KAYLAAN_REDEEMED = 290 , NPC_ADYEN_THE_LIGHTWARDEN = 18537 , NPC_EXARCH_ORELIS = 19466 ,
NPC_ANCHORITE_KARJA = 19467 , NPC_ISHANAH = 18538 , NPC_KAYLAAN_THE_LOST = 20794 , NPC_WRATH_LORD = 20929 ,
GOSSIP_SHATTRATH = 8117 , GOSSIP_NETHERSTORM = 8215 , GOSSIP_SOCRETHAR_DEAD_PLACEHOLDER_ID = 40000 , GOSSIP_ACTION_START_DEATHBLOW = 1 ,
SPELL_POWER_OF_THE_LEGION = 35596 , SPELL_KAYLAN_WRATH = 35614 , SPELL_CANCEL_POWER_OF_THE_LEGION = 35597 , SPELL_WRATH_OF_SOCRETHAR = 35598 ,
SPELL_RESURRECTION = 35599 , SPELL_WRATH_OF_SOCRETHAR2 = 35600 , SPELL_DIVINE_SHIELD = 13874 , SPELL_PERMANENT_FEIGN_DEATH = 29266 ,
SPELL_CRUSADER_STRIKE = 14518 , SPELL_HAMMER_OF_JUSTICE = 13005 , SPELL_BURNING_LIGHT = 37552 , SPELL_HOLY_SLAM = 37572 ,
SPELL_HEAL = 37569 , SPELL_AVENGERS_SHEILD = 37554 , SPELL_HOLY_SMITE = 15238 , SPELL_POWER_WORD_SHIELD = 22187 ,
SPELL_GREATER_HEAL = 35096 , SPELL_HOLY_FIRE = 17141 , SPELL_DEMORALIZING_SHOUT = 13730 , SPELL_REND = 16509 ,
SPELL_HEROIC_STRIKE = 29426 , SPELL_CLEAVE = 15496 , SPELL_SHADOW_BOLT_VOLLEY = 28448 , SPELL_FIREBALL_BARRAGE = 37540 ,
SAY_ADYEN_1 = -1001254 , SAY_SOCRETHAR_1 = -1001255 , SAY_ADYEN_2 = -1001256 , SAY_SOCRETHAR_2 = -1001257 ,
SAY_ORELIS_1 = -1001258 , SAY_KAYLAAN_1 = -1001259 , SAY_KAYLAAN_2 = -1001260 , SAY_KAYLAAN_3 = -1001261 ,
SAY_ADYEN_3 = -1001262 , SAY_KAYLAAN_4 = -1001263 , SAY_SOCRETHAR_3 = -1001264 , SAY_SOCRETHAR_4 = -1001265 ,
SAY_KAYLAAN_5 = -1001266 , SAY_KAYLAAN_6 = -1001267 , SAY_ISHANAH_1 = -1001268 , SAY_ISHANAH_2 = -1001269 ,
SAY_SOCRETHAR_5 = -1001270 , SAY_KAYLAAN_7 = -1001271 , SAY_KAYLAAN_8 = -1001272 , SAY_SOCRETHAR_6 = -1001273 ,
EVENT_SOCRETHAR_SAY_1 = 0 , EVENT_ADYEN_SAY_2 = 1 , EVENT_SOCRETHAR_SAY_2 = 2 , EVENT_KAYLAAN_MOVE = 3 ,
EVENT_KAYLAAN_SAY_2 = 4 , EVENT_KAYLAAN_SAY_3 = 5 , EVENT_ADYEN_SAY_3 = 6 , EVENT_KAYLAAN_SAY_4 = 7 ,
EVENT_SOCRETHAR_CAST_POWER_OF_LEGION = 8 , EVENT_SOCRETHAR_SAY_3 = 9 , EVENT_KAYLAAN_SAY_5 = 10 , EVENT_KAYLAAN_KNEEL = 11 ,
EVENT_ISHANAH_SAY_1 = 12 , EVENT_ISHANAH_SAY_2 = 13 , EVENT_SOCRETHAR_SAY_5 = 14 , EVENT_SOCRETHAR_KILL_ISHANAH = 15 ,
EVENT_KAYLAAN_HORRIFIED = 16 , EVENT_KAYLAAN_SAVE_ISHANAH = 17 , EVENT_SOCRETHAR_SAY_6 = 18 , EVENT_SOCRETHAR_KILL_KAYLAAN = 19 ,
EVENT_SOCRETHAR_ATTACK = 20 , POINT_KAYLAAN_MOVE = 1 , POINT_KAYLAAN_SAVE_ISHANAH = 2 , PATH_ID_DEATHBLOW = 1 ,
WAYPOINT_ADYEN_LAST = 8 , DB_GUID_WRATH_LORD_1 = 73683 , DB_GUID_WRATH_LORD_2 = 73693 , PATH_ID_WRATH_LORD_1 = 1 ,
PATH_ID_WRATH_LORD_2 = 2
}
enum KaylaanActions {
KAYLAAN_ACTION_HEAL , KAYLAAN_ACTION_AVENGERS , KAYLAAN_ACTION_HOLY_SLAM , KAYLAAN_ACTION_BURNING_LIGHT ,
KAYLAAN_ACTION_MAX
}
enum { NPC_BOOM = 20284 , NPC_BOOM_BOT = 19692 }
Functions
UnitAI * GetAI_npc_manaforge_spawnAI (Creature *pCreature)
UnitAI * GetAI_npc_manaforge_control_console (Creature *pCreature)
bool GossipHello_go_manaforge (Player *pPlayer, GameObject *pGo)
bool GossipSelect_go_manaforge (Player *pPlayer, GameObject *pGo, uint32, uint32 uiAction)
UnitAI * GetAI_npc_commander_dawnforge (Creature *pCreature)
bool AreaTrigger_at_commander_dawnforge (Player *pPlayer, AreaTriggerEntry const *)
bool QuestAccept_npc_bessy (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_bessy (Creature *pCreature)
UnitAI * GetAI_npc_maxx_a_million (Creature *pCreature)
bool QuestAccept_npc_maxx_a_million (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_zeppit (Creature *pCreature)
UnitAI * GetAI_npc_protectorate_demolitionist (Creature *pCreature)
UnitAI * GetAI_npc_captured_vanguard (Creature *pCreature)
bool QuestAccept_npc_captured_vanguard (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_drijya (Creature *pCreature)
bool QuestAccept_npc_drijya (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_saeed (Creature *pCreature)
bool GossipSelect_npc_saeed (Player *player, Creature *creature, uint32, uint32 action)
UnitAI * GetAI_npc_dimensius (Creature *pCreature)
UnitAI * GetAI_npc_salhadaar (Creature *pCreature)
UnitAI * GetAI_npc_energy_ball (Creature *pCreature)
UnitAI * GetAI_npc_void_conduit (Creature *pCreature)
UnitAI * GetAI_npc_scrapped_fel_reaver (Creature *creature)
bool AreaTrigger_at_socrethar_seat (Player *player, AreaTriggerEntry const *)
bool GossipHello_npc_adyen_the_lightwarden (Player *player, Creature *creature)
bool GossipSelect_npc_adyen_the_lightwarden (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_netherstorm ()
Variables
static float m_afBanaarTechCoords [7][3]
static float m_afCoruuTechCoords [6][3]
static float m_afDuroTechCoords [7][3]
static float m_afAraTechCoords [18][3]
static const uint32 auiShadowRainSpells [5] = { 37399, 37405, 37397, 37396, 37409 }
float spawningLocations [COUNT_SPAWNING_LOCATIONS][4]
float movementDestinations [COUNT_SPAWNING_LOCATIONS *2][3]
Macro Definition Documentation
GOSSIP_ITEM_SHUTDOWN
#define GOSSIP_ITEM_SHUTDOWN "<Begin emergency shutdown.>"
Definition at line 103 of file netherstorm.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_START
EMOTE_60
EMOTE_30
EMOTE_10
EMOTE_COMPLETE
EMOTE_ABORT
SAY_MANFORGE_SHUTDOWN_1
SAY_MANFORGE_SHUTDOWN_2
YEL_MANFORGE_SHUTDOWN
GOSSIP_TEXT_CONSOLE
GOSSIP_TEXT_CONSOLE_NOQUEST
GO_BANAAR_C_CONSOLE
GO_CORUU_C_CONSOLE
GO_DURO_C_CONSOLE
GO_ARA_C_CONSOLE
NPC_BNAAR_C_CONSOLE
NPC_CORUU_C_CONSOLE
NPC_DURO_C_CONSOLE
NPC_ARA_C_CONSOLE
NPC_SUNFURY_TECH
NPC_SUNFURY_PROT
NPC_SUNFURY_WARP_MASTER
NPC_SUNFURY_WARP_ENGINEER
NPC_SUNFURY_RESEARCHER
NPC_ARA_TECH
NPC_ARA_ENGI
NPC_ARA_GORKLONN
QUEST_SHUTDOWN_BNAAR_ALDOR
QUEST_SHUTDOWN_BNAAR_SCRYERS
QUEST_SHUTDOWN_CORUU_ALDOR
QUEST_SHUTDOWN_CORUU_SCRYERS
QUEST_SHUTDOWN_DURO_ALDOR
QUEST_SHUTDOWN_DURO_SCRYERS
QUEST_SHUTDOWN_ARA_ALDOR
QUEST_SHUTDOWN_ARA_SCRYERS
ITEM_BNAAR_ACESS_CRYSTAL
ITEM_CORUU_ACESS_CRYSTAL
ITEM_DURO_ACESS_CRYSTAL
ITEM_ARA_ACESS_CRYSTAL
SPELL_DISABLE_VISUAL
SPELL_INTERRUPT_1
SPELL_INTERRUPT_2
Definition at line 48 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_COMMANDER_DAWNFORGE_1
SAY_ARCANIST_ARDONIS_1
SAY_COMMANDER_DAWNFORGE_2
SAY_PATHALEON_THE_CALCULATOR_IMAGE_1
SAY_COMMANDER_DAWNFORGE_3
SAY_PATHALEON_THE_CALCULATOR_IMAGE_2
SAY_PATHALEON_THE_CALCULATOR_IMAGE_2_1
SAY_PATHALEON_THE_CALCULATOR_IMAGE_2_2
SAY_COMMANDER_DAWNFORGE_4
SAY_ARCANIST_ARDONIS_2
SAY_COMMANDER_DAWNFORGE_5
QUEST_INFO_GATHERING
SPELL_SUNFURY_DISGUISE
NPC_ARCANIST_ARDONIS
NPC_COMMANDER_DAWNFORGE
NPC_PATHALEON_THE_CALCULATOR_IMAGE
Definition at line 974 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_COWS_COME_HOME
NPC_THADELL
NPC_TORMENTED_SOUL
NPC_SEVERED_SPIRIT
SAY_ESCORT_1
SAY_ESCORT_2
SAY_THADELL
Definition at line 1232 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MARK_V_IS_ALIVE
NPC_BOT_SPECIALIST_ALLEY
GO_DRAENEI_MACHINE
SAY_START
SAY_ALLEY_FAREWELL
SAY_CONTINUE
SAY_ALLEY_FINISH
Definition at line 1301 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_GATHER_BLOOD
NPC_WARP_CHASER
SPELL_GATHER_WARP_BLOOD
Definition at line 1456 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_INTRO
SAY_ATTACKED_1
SAY_ATTACKED_2
SAY_STAGING_GROUNDS
SAY_TOXIC_HORROR
SAY_SALHADAAR
SAY_DISRUPTOR
SAY_NEXUS_PROTECT
SAY_FINISH_1
SAY_FINISH_2
SPELL_SPAWN
SPELL_PROTECTORATE
NPC_NEXUS_STALKER
NPC_ARCHON
FACTION_ESCORT
QUEST_ID_DELIVERING_MESSAGE
Definition at line 1495 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_VANGUARD_INTRO
SAY_VANGUARD_START
SAY_VANGUARD_FINISH
EMOTE_VANGUARD_FINISH
SPELL_GLAIVE
SPELL_HAMSTRING
NPC_COMMANDER_AMEER
NPC_ETHEREUM_GLADIATOR
QUEST_ID_ESCAPE_STAGING_GROUNDS
Definition at line 1665 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_DRIJYA_START
SAY_DRIJYA_1
SAY_DRIJYA_2
SAY_DRIJYA_3
SAY_DRIJYA_4
SAY_DRIJYA_5
SAY_DRIJYA_6
SAY_DRIJYA_7
SAY_DRIJYA_COMPLETE
SPELL_EXPLOSION_VISUAL
NPC_EXPLODE_TRIGGER
NPC_TERROR_IMP
NPC_LEGION_TROOPER
NPC_LEGION_DESTROYER
QUEST_ID_WARP_GATE
MAX_TROOPERS
MAX_IMPS
Definition at line 1790 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_DIMENSIUS_ALL_DEVOURING
NPC_PROTECTORATE_DEFENDER
NPC_PROTECTORATE_REGENERATOR
NPC_PROTECTORATE_AVENGER
NPC_DIMENSIUS
FACTION_PROTECTORATE_ESCORT
SAY_SAEED_START
SAY_SAEED_PREPARE
SAY_SAEED_ATTACK
EMOTE_DIMENSIUS_LAUGH
SAY_SAEED_TAUNT
SAY_AVENGER_QUEST_COMPLETE
SPELL_SAEED_CLEAVE
SPELL_TELEPORT
Definition at line 2085 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_AGGRO
SAY_SUMMON
SPELL_DIMENSIUS_FEEDING
SPELL_SHADOW_SPIRAL
SPELL_SHADOW_VAULT
NPC_SPAWN_OF_DIMENSIUS
NPC_CAPTAIN_SAEED
MODEL_ID_DIMENSIUS_CLOUD
Definition at line 2330 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_ENERGY_BALL
NPC_SALHADAAR
SPELL_FLOAT
SPELL_SALAADIN_TESLA
SPELL_PROTECTORATE_DISRUPTOR
SPELL_SALAADIN_OVERSPARK
SPELL_GRAVITY_FLUX
SPELL_STASIS
SPELL_MIRROR_IMAGE_1
SPELL_MIRROR_IMAGE_2
FACTION_SALHADAAR_HOSTILE
SAY_THREAT
Definition at line 2477 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_PHASE_DISRUPTOR
Definition at line 2697 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_NEGATRON
SPELL_SCRAP_REAVER
SAY_ON_DEATH
AREA_PROVING_GROUNDS
Definition at line 2738 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FEL_ZAPPER
NPC_ZAXXIS_AMBUSHER
SAY_EVENT_START
COUNT_SPAWNING_LOCATIONS
Definition at line 2955 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_DEATHBLOW_TO_THE_LEGION
FACTION_DEATHBLOW
FACTION_DEATHBLOW_IN_PROGRESS
FACTION_SHATTRATH
FACTION_KAYLAAN_HOSTILE
FACTION_KAYLAAN_REDEEMED
NPC_ADYEN_THE_LIGHTWARDEN
NPC_EXARCH_ORELIS
NPC_ANCHORITE_KARJA
NPC_ISHANAH
NPC_KAYLAAN_THE_LOST
NPC_WRATH_LORD
GOSSIP_SHATTRATH
GOSSIP_NETHERSTORM
GOSSIP_SOCRETHAR_DEAD_PLACEHOLDER_ID
GOSSIP_ACTION_START_DEATHBLOW
SPELL_POWER_OF_THE_LEGION
SPELL_KAYLAN_WRATH
SPELL_CANCEL_POWER_OF_THE_LEGION
SPELL_WRATH_OF_SOCRETHAR
SPELL_RESURRECTION
SPELL_WRATH_OF_SOCRETHAR2
SPELL_DIVINE_SHIELD
SPELL_PERMANENT_FEIGN_DEATH
SPELL_CRUSADER_STRIKE
SPELL_HAMMER_OF_JUSTICE
SPELL_BURNING_LIGHT
SPELL_HOLY_SLAM
SPELL_HEAL
SPELL_AVENGERS_SHEILD
SPELL_HOLY_SMITE
SPELL_POWER_WORD_SHIELD
SPELL_GREATER_HEAL
SPELL_HOLY_FIRE
SPELL_DEMORALIZING_SHOUT
SPELL_REND
SPELL_HEROIC_STRIKE
SPELL_CLEAVE
SPELL_SHADOW_BOLT_VOLLEY
SPELL_FIREBALL_BARRAGE
SAY_ADYEN_1
SAY_SOCRETHAR_1
SAY_ADYEN_2
SAY_SOCRETHAR_2
SAY_ORELIS_1
SAY_KAYLAAN_1
SAY_KAYLAAN_2
SAY_KAYLAAN_3
SAY_ADYEN_3
SAY_KAYLAAN_4
SAY_SOCRETHAR_3
SAY_SOCRETHAR_4
SAY_KAYLAAN_5
SAY_KAYLAAN_6
SAY_ISHANAH_1
SAY_ISHANAH_2
SAY_SOCRETHAR_5
SAY_KAYLAAN_7
SAY_KAYLAAN_8
SAY_SOCRETHAR_6
EVENT_SOCRETHAR_SAY_1
EVENT_ADYEN_SAY_2
EVENT_SOCRETHAR_SAY_2
EVENT_KAYLAAN_MOVE
EVENT_KAYLAAN_SAY_2
EVENT_KAYLAAN_SAY_3
EVENT_ADYEN_SAY_3
EVENT_KAYLAAN_SAY_4
EVENT_SOCRETHAR_CAST_POWER_OF_LEGION
EVENT_SOCRETHAR_SAY_3
EVENT_KAYLAAN_SAY_5
EVENT_KAYLAAN_KNEEL
EVENT_ISHANAH_SAY_1
EVENT_ISHANAH_SAY_2
EVENT_SOCRETHAR_SAY_5
EVENT_SOCRETHAR_KILL_ISHANAH
EVENT_KAYLAAN_HORRIFIED
EVENT_KAYLAAN_SAVE_ISHANAH
EVENT_SOCRETHAR_SAY_6
EVENT_SOCRETHAR_KILL_KAYLAAN
EVENT_SOCRETHAR_ATTACK
POINT_KAYLAAN_MOVE
POINT_KAYLAAN_SAVE_ISHANAH
PATH_ID_DEATHBLOW
WAYPOINT_ADYEN_LAST
DB_GUID_WRATH_LORD_1
DB_GUID_WRATH_LORD_2
PATH_ID_WRATH_LORD_1
PATH_ID_WRATH_LORD_2
Definition at line 3154 of file netherstorm.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_BOOM
NPC_BOOM_BOT
Definition at line 4017 of file netherstorm.cpp.
KaylaanActions
enum KaylaanActions
Enumerator
KAYLAAN_ACTION_HEAL
KAYLAAN_ACTION_AVENGERS
KAYLAAN_ACTION_HOLY_SLAM
KAYLAAN_ACTION_BURNING_LIGHT
KAYLAAN_ACTION_MAX
Definition at line 3749 of file netherstorm.cpp.
Function Documentation
AddSC_netherstorm()
void AddSC_netherstorm ()
Definition at line 4044 of file netherstorm.cpp.
References AreaTrigger_at_commander_dawnforge(), AreaTrigger_at_socrethar_seat(), Script::GetAI, GetAI_npc_bessy(), GetAI_npc_captured_vanguard(), GetAI_npc_commander_dawnforge(), GetAI_npc_dimensius(), GetAI_npc_drijya(), GetAI_npc_energy_ball(), GetAI_npc_manaforge_control_console(), GetAI_npc_manaforge_spawnAI(), GetAI_npc_maxx_a_million(), GetAI_npc_protectorate_demolitionist(), GetAI_npc_saeed(), GetAI_npc_salhadaar(), GetAI_npc_scrapped_fel_reaver(), GetAI_npc_void_conduit(), GetAI_npc_zeppit(), GossipHello_go_manaforge(), GossipHello_npc_adyen_the_lightwarden(), GossipSelect_go_manaforge(), GossipSelect_npc_adyen_the_lightwarden(), GossipSelect_npc_saeed(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pQuestAcceptNPC, QuestAccept_npc_bessy(), QuestAccept_npc_captured_vanguard(), QuestAccept_npc_drijya(), QuestAccept_npc_maxx_a_million(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_commander_dawnforge()
bool AreaTrigger_at_commander_dawnforge (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 1206 of file netherstorm.cpp.
References Creature::AI(), EFFECT_INDEX_0, GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::HasAura(), Unit::IsAlive(), NPC_COMMANDER_DAWNFORGE, QUEST_INFO_GATHERING, QUEST_STATUS_INCOMPLETE, and SPELL_SUNFURY_DISGUISE.
Referenced by AddSC_netherstorm().
AreaTrigger_at_socrethar_seat()
bool AreaTrigger_at_socrethar_seat (Player * player, AreaTriggerEntry const *)
Definition at line 3938 of file netherstorm.cpp.
References FACTION_DEATHBLOW, WorldObject::GetMap(), Player::IsCurrentQuest(), NPC_ADYEN_THE_LIGHTWARDEN, NPC_ANCHORITE_KARJA, NPC_EXARCH_ORELIS, QUEST_DEATHBLOW_TO_THE_LEGION, Object::RemoveFlag(), Object::SetUInt32Value(), Map::SpawnedCountForEntry(), WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by AddSC_netherstorm().
GetAI_npc_bessy()
UnitAI* GetAI_npc_bessy (Creature * pCreature)
Definition at line 1292 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_captured_vanguard()
UnitAI* GetAI_npc_captured_vanguard (Creature * pCreature)
Definition at line 1768 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_commander_dawnforge()
UnitAI* GetAI_npc_commander_dawnforge (Creature * pCreature)
Definition at line 1201 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_dimensius()
UnitAI* GetAI_npc_dimensius (Creature * pCreature)
Definition at line 2472 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_drijya()
UnitAI* GetAI_npc_drijya (Creature * pCreature)
Definition at line 2065 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_energy_ball()
UnitAI* GetAI_npc_energy_ball (Creature * pCreature)
Definition at line 2692 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_manaforge_control_console()
UnitAI* GetAI_npc_manaforge_control_console (Creature * pCreature)
Definition at line 810 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_manaforge_spawnAI()
UnitAI* GetAI_npc_manaforge_spawnAI (Creature * pCreature)
Definition at line 248 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_maxx_a_million()
UnitAI* GetAI_npc_maxx_a_million (Creature * pCreature)
Definition at line 1430 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_protectorate_demolitionist()
UnitAI* GetAI_npc_protectorate_demolitionist (Creature * pCreature)
Definition at line 1656 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_saeed()
UnitAI* GetAI_npc_saeed (Creature * pCreature)
Definition at line 2269 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_salhadaar()
UnitAI* GetAI_npc_salhadaar (Creature * pCreature)
Definition at line 2626 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_scrapped_fel_reaver()
UnitAI* GetAI_npc_scrapped_fel_reaver (Creature * creature)
Definition at line 3145 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_void_conduit()
UnitAI* GetAI_npc_void_conduit (Creature * pCreature)
Definition at line 2733 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GetAI_npc_zeppit()
UnitAI* GetAI_npc_zeppit (Creature * pCreature)
Definition at line 1486 of file netherstorm.cpp.
Referenced by AddSC_netherstorm().
GossipHello_go_manaforge()
bool GossipHello_go_manaforge (Player * pPlayer, GameObject * pGo)
Definition at line 819 of file netherstorm.cpp.
References GAMEOBJECT_TYPE_QUESTGIVER, WorldObject::GetAreaId(), GameObject::GetGoType(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SHUTDOWN, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_CONSOLE, GOSSIP_TEXT_CONSOLE_NOQUEST, Player::HasItemCount(), ITEM_ARA_ACESS_CRYSTAL, ITEM_BNAAR_ACESS_CRYSTAL, ITEM_CORUU_ACESS_CRYSTAL, ITEM_DURO_ACESS_CRYSTAL, Player::PrepareQuestMenu(), QUEST_SHUTDOWN_ARA_ALDOR, QUEST_SHUTDOWN_ARA_SCRYERS, QUEST_SHUTDOWN_BNAAR_ALDOR, QUEST_SHUTDOWN_BNAAR_SCRYERS, QUEST_SHUTDOWN_CORUU_ALDOR, QUEST_SHUTDOWN_CORUU_SCRYERS, QUEST_SHUTDOWN_DURO_ALDOR, QUEST_SHUTDOWN_DURO_SCRYERS, QUEST_STATUS_INCOMPLETE, and Player::SendPreparedQuest().
Referenced by AddSC_netherstorm().
GossipHello_npc_adyen_the_lightwarden()
bool GossipHello_npc_adyen_the_lightwarden (Player * player, Creature * creature)
Definition at line 3955 of file netherstorm.cpp.
References Creature::AI(), FACTION_SHATTRATH, Unit::GetFaction(), Map::GetInstanceData(), WorldObject::GetMap(), GOSSIP_NETHERSTORM, GOSSIP_SHATTRATH, Unit::IsAlive(), Unit::IsInCombat(), NPC_SOCRETHAR, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_netherstorm().
GossipSelect_go_manaforge()
bool GossipSelect_go_manaforge (Player * pPlayer, GameObject * pGo, uint32 , uint32 uiAction)
Definition at line 887 of file netherstorm.cpp.
References Creature::AI(), GAMEOBJECT_FLAGS, WorldObject::GetAreaId(), GetCreatureListWithEntryInGrid(), Object::GetObjectGuid(), Player::GetQuestStatus(), GO_FLAG_IN_USE, GOSSIP_ACTION_INFO_DEF, Player::HasItemCount(), IN_MILLISECONDS, ITEM_ARA_ACESS_CRYSTAL, ITEM_BNAAR_ACESS_CRYSTAL, ITEM_CORUU_ACESS_CRYSTAL, ITEM_DURO_ACESS_CRYSTAL, MINUTE, NPC_ARA_C_CONSOLE, NPC_BNAAR_C_CONSOLE, NPC_CORUU_C_CONSOLE, NPC_DURO_C_CONSOLE, NPC_SUNFURY_RESEARCHER, NPC_SUNFURY_WARP_ENGINEER, NPC_SUNFURY_WARP_MASTER, QUEST_SHUTDOWN_ARA_ALDOR, QUEST_SHUTDOWN_ARA_SCRYERS, QUEST_SHUTDOWN_BNAAR_ALDOR, QUEST_SHUTDOWN_BNAAR_SCRYERS, QUEST_SHUTDOWN_CORUU_ALDOR, QUEST_SHUTDOWN_CORUU_SCRYERS, QUEST_SHUTDOWN_DURO_ALDOR, QUEST_SHUTDOWN_DURO_SCRYERS, QUEST_STATUS_INCOMPLETE, Object::SetFlag(), WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_OR_CORPSE_DESPAWN.
Referenced by AddSC_netherstorm().
GossipSelect_npc_adyen_the_lightwarden()
bool GossipSelect_npc_adyen_the_lightwarden (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 3976 of file netherstorm.cpp.
References Creature::AI().
Referenced by AddSC_netherstorm().
GossipSelect_npc_saeed()
bool GossipSelect_npc_saeed (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 2274 of file netherstorm.cpp.
References Creature::AI(), DoScriptText(), FACTION_PROTECTORATE_ESCORT, GetCreatureListWithEntryInGrid(), Object::GetEntry(), Player::GetGroup(), Object::GetObjectGuid(), Player::GetQuestStatus(), GetQuestTemplateStore(), Player::KilledMonsterCredit(), GroupReference::next(), NPC_PROTECTORATE_AVENGER, NPC_PROTECTORATE_DEFENDER, NPC_PROTECTORATE_REGENERATOR, QUEST_DIMENSIUS_ALL_DEVOURING, QUEST_STATUS_INCOMPLETE, Object::RemoveFlag(), SAY_SAEED_START, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_netherstorm().
QuestAccept_npc_bessy()
bool QuestAccept_npc_bessy (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1278 of file netherstorm.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_COWS_COME_HOME, SAY_ESCORT_1, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_NON_ATTACKABLE.
Referenced by AddSC_netherstorm().
QuestAccept_npc_captured_vanguard()
bool QuestAccept_npc_captured_vanguard (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1773 of file netherstorm.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_ID_ESCAPE_STAGING_GROUNDS, and SAY_VANGUARD_START.
Referenced by AddSC_netherstorm().
QuestAccept_npc_drijya()
bool QuestAccept_npc_drijya (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 2070 of file netherstorm.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_WARP_GATE, and UnitAI::SendAIEvent().
Referenced by AddSC_netherstorm().
QuestAccept_npc_maxx_a_million()
bool QuestAccept_npc_maxx_a_million (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1435 of file netherstorm.cpp.
References Creature::AI(), EMOTE_ONESHOT_NONE, FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), Unit::HandleEmote(), QUEST_MARK_V_IS_ALIVE, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and TEMPFACTION_TOGGLE_IMMUNE_TO_PLAYER.
Referenced by AddSC_netherstorm().
Variable Documentation
auiShadowRainSpells
const uint32 auiShadowRainSpells[5] = { 37399, 37405, 37397, 37396, 37409 } static
Definition at line 2345 of file netherstorm.cpp.
Referenced by npc_dimensiusAI::UpdateAI().
m_afAraTechCoords
float m_afAraTechCoords[18][3] static
Initial value:
=
{
    { 4047.705f, 4005.494f, 194.226f },
    { 4051.31f , 4001.424f, 194.023f },
    { 4052.456f, 4005.68f , 194.012f },
    { 4026.788f, 4025.399f, 192.597f },
    { 4028.071f, 4021.542f, 192.526f },
    { 4029.142f, 4027.635f, 193.009f },
    { 3974.354f, 4024.723f, 194.227f },
    { 3969.603f, 4022.106f, 194.227f },
    { 3968.554f, 4025.744f, 193.1f },
    { 4003.378f, 4033.91f , 192.706f },
    { 3999.738f, 4029.533f, 192.384f },
    { 3999.792f, 4035.362f, 193.058f },
    { 4024.814f, 4072.806f, 192.82f },
    { 4027.551f, 4077.417f, 192.82f },
    { 4024.087f, 4078.282f, 192.819f },
    { 4017.536f, 4043.038f, 193.896f },
    { 4021.246f, 4042.021f, 193.919f },
    { 4013.202f, 4043.497f, 193.848f }
}
Definition at line 134 of file netherstorm.cpp.
Referenced by npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), and npc_manaforge_control_consoleAI::DoWaveSpawnForCreature().
m_afBanaarTechCoords
float m_afBanaarTechCoords[7][3] static
Initial value:
=
{
    { 2871.506f, 4170.109f, 164.008f },
    { 2895.987f, 4155.230f, 163.65f },
    { 2927.997f, 4172.454f, 163.194f },
    { 2883.564f, 4202.966f, 163.454f },
    { 2908.597f, 4204.297f, 162.495f },
    { 2946.52f, 4201.42f, 163.47f },
    { 2931.257f, 4194.726f, 163.563f }
}
Definition at line 105 of file netherstorm.cpp.
Referenced by npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), and npc_manaforge_control_consoleAI::SummonedMovementInform().
m_afCoruuTechCoords
float m_afCoruuTechCoords[6][3] static
Initial value:
=
{
    { 2391.320f, 2724.3f  , 134.493f },
    { 2419.598f, 2742.209f, 133.186f },
    { 2459.519f, 2738.630f, 133.085f },
    { 2438.913f, 2748.224f, 134.493f },
    { 2426.102f, 2800.459f, 134.359f },
    { 2427.665f, 2768.984f, 132.92f }
}
Definition at line 115 of file netherstorm.cpp.
Referenced by npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), and npc_manaforge_control_consoleAI::DoWaveSpawnForCreature().
m_afDuroTechCoords
float m_afDuroTechCoords[7][3] static
Initial value:
=
{
    { 2998.085f, 2133.911f, 165.328f },
    { 3005.962f, 2179.238f, 164.428f },
    { 2989.977f, 2190.82f, 164.047f },
    { 2964.918f, 2156.918f, 163.904f },
    { 2966.12f , 2174.327f, 163.292f },
    { 2955.571f, 2232.075f, 163.920f },
    { 2968.885f, 2199.937f, 165.329f }
}
Definition at line 124 of file netherstorm.cpp.
Referenced by npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), and npc_manaforge_control_consoleAI::SummonedMovementInform().
movementDestinations
float movementDestinations[COUNT_SPAWNING_LOCATIONS *2][3]
Initial value:
=
{
    { 2556.563f, 3969.015f, 131.099f },
    { 2535.538f, 3992.952f, 137.4138f},
    { 2538.997f, 3957.29f, 128.0989f },
    { 2527.418f, 3972.693f, 127.7893f },
    { 2496.478f, 3987.993f, 129.061f },
    { 2510.035f, 3995.931f, 132.1609f },
    { 2494.564f, 4020.812f, 133.1337f },
    { 2518.717f, 4008.459f, 133.8864f },
}
Definition at line 2975 of file netherstorm.cpp.
spawningLocations
float spawningLocations[COUNT_SPAWNING_LOCATIONS][4]
Initial value:
=
{
    { 2593.983f, 3946.436f, 137.4138f, 2.598825f },
    { 2543.813f, 3932.396f, 135.5509f, 1.761495f },
    { 2467.507f, 3961.973f, 114.759f, 0.7313454f },
    { 2484.169f, 4042.952f, 131.2856f, 4.728844f },
}
Definition at line 2966 of file netherstorm.cpp.
Referenced by npc_scrapped_fel_reaverAI::ProcessEvent().