CMaNGOS_WoTLK: nexus.cpp File Reference
nexus.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "nexus.h"
Functions
bool GOUse_go_containment_sphere (Player *, GameObject *pGo)
InstanceData * GetInstanceData_instance_nexus (Map *pMap)
void AddSC_instance_nexus ()
Function Documentation
AddSC_instance_nexus()
void AddSC_instance_nexus ()
Definition at line 245 of file nexus.cpp.
References Script::GetInstanceData, GetInstanceData_instance_nexus(), GOUse_go_containment_sphere(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_nexus()
InstanceData* GetInstanceData_instance_nexus (Map * pMap)
Definition at line 240 of file nexus.cpp.
Referenced by AddSC_instance_nexus().
GOUse_go_containment_sphere()
bool GOUse_go_containment_sphere (Player * , GameObject * pGo)
Definition at line 27 of file nexus.cpp.
References GAMEOBJECT_FLAGS, GetClosestCreatureWithEntry(), Object::GetEntry(), WorldObject::GetInstanceData(), GO_CONTAINMENT_SPHERE_ANOMALUS, GO_CONTAINMENT_SPHERE_ORMOROK, GO_CONTAINMENT_SPHERE_TELESTRA, GO_FLAG_NO_INTERACT, NPC_BREATH_CASTER, InstanceData::SetData(), Object::SetFlag(), SPECIAL, TYPE_ANOMALUS, TYPE_ORMOROK, and TYPE_TELESTRA.
Referenced by AddSC_instance_nexus().