CMaNGOS_WoTLK: npc_professions.cpp File Reference
npc_professions.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Macros
#define GOSSIP_SENDER_LEARN 50
#define GOSSIP_SENDER_UNLEARN 51
#define GOSSIP_SENDER_CHECK 52
#define GOSSIP_UNLEARN_DRAGON "I wish to unlearn my Dragonscale Leatherworking specialization!"
#define BOX_UNLEARN_DRAGON "Do you really want to unlearn your Dragonscale Leatherworking specialization and lose all associated recipes?\n"
#define GOSSIP_LEARN_DRAGON "Please teach me how to become a Dragonscale leatherworker."
#define GOSSIP_UNLEARN_ELEMENTAL "I wish to unlearn my Elemental Leatherworking specialization!"
#define BOX_UNLEARN_ELEMENTAL "Do you really want to unlearn your Elemental Leatherworking specialization and lose all associated recipes?\n"
#define GOSSIP_LEARN_ELEMENTAL "Please teach me how to become an Elemental leatherworker."
#define GOSSIP_UNLEARN_TRIBAL "I wish to unlearn my Tribal Leatherworking specialization!"
#define BOX_UNLEARN_TRIBAL "Do you really want to unlearn your Tribal Leatherworking specialization and lose all associated recipes?\n"
#define GOSSIP_LEARN_TRIBAL "Please teach me how to become a Tribal leatherworker."
Enumerations
enum SpecializationSpells {
S_DRAGON = 10656 , S_ELEMENTAL = 10658 , S_TRIBAL = 10660 , S_LEARN_DRAGON = 10657 ,
S_LEARN_ELEMENTAL = 10659 , S_LEARN_TRIBAL = 10661 , S_UNLEARN_DRAGON = 36434 , S_UNLEARN_ELEMENTAL = 36328 ,
S_UNLEARN_TRIBAL = 36433 , S_SPELLFIRE = 26797 , S_MOONCLOTH = 26798 , S_SHADOWEAVE = 26801 ,
S_LEARN_SPELLFIRE = 26796 , S_LEARN_MOONCLOTH = 26799 , S_LEARN_SHADOWEAVE = 26800 , S_UNLEARN_SPELLFIRE = 41299 ,
S_UNLEARN_MOONCLOTH = 41558 , S_UNLEARN_SHADOWEAVE = 41559
}
enum SpecializationQuests {
Q_DRAGON_ALLY = 5141 , Q_DRAGON_HORDE = 5145 , Q_ELEMENTAL_ALLY = 5144 , Q_ELEMENTAL_HORDE = 5146 ,
Q_TRIBAL_ALLY = 5143 , Q_TRIBAL_HORDE = 5148
}
enum SpecializationTrainers {
N_TRAINER_DRAGON1 = 7866 , N_TRAINER_DRAGON2 = 7867 , N_TRAINER_ELEMENTAL1 = 7868 , N_TRAINER_ELEMENTAL2 = 7869 ,
N_TRAINER_TRIBAL1 = 7870 , N_TRAINER_TRIBAL2 = 7871
}
Functions
int32 GetUnlearnCostMedium (Player *pPlayer)
bool EquippedOk (Player *pPlayer, uint32 spellId)
void ProfessionUnlearnSpells (Player *pPlayer, uint32 type)
bool IsEligibleSpecializeLW (Player *pPlayer)
bool GossipHello_npc_prof_leather (Player *pPlayer, Creature *pCreature)
void SendActionMenu_npc_prof_leather (Player *pPlayer, Creature *pCreature, uint32 uiAction)
bool GossipSelect_npc_prof_leather (Player *pPlayer, Creature *pCreature, uint32 uiSender, uint32 uiAction)
void AddSC_npc_professions ()
Macro Definition Documentation
BOX_UNLEARN_DRAGON
#define BOX_UNLEARN_DRAGON "Do you really want to unlearn your Dragonscale Leatherworking specialization and lose all associated recipes?\n"
Definition at line 50 of file npc_professions.cpp.
BOX_UNLEARN_ELEMENTAL
#define BOX_UNLEARN_ELEMENTAL "Do you really want to unlearn your Elemental Leatherworking specialization and lose all associated recipes?\n"
Definition at line 54 of file npc_professions.cpp.
BOX_UNLEARN_TRIBAL
#define BOX_UNLEARN_TRIBAL "Do you really want to unlearn your Tribal Leatherworking specialization and lose all associated recipes?\n"
Definition at line 58 of file npc_professions.cpp.
GOSSIP_LEARN_DRAGON
#define GOSSIP_LEARN_DRAGON "Please teach me how to become a Dragonscale leatherworker."
Definition at line 51 of file npc_professions.cpp.
GOSSIP_LEARN_ELEMENTAL
#define GOSSIP_LEARN_ELEMENTAL "Please teach me how to become an Elemental leatherworker."
Definition at line 55 of file npc_professions.cpp.
GOSSIP_LEARN_TRIBAL
#define GOSSIP_LEARN_TRIBAL "Please teach me how to become a Tribal leatherworker."
Definition at line 59 of file npc_professions.cpp.
GOSSIP_SENDER_CHECK
#define GOSSIP_SENDER_CHECK 52
Definition at line 43 of file npc_professions.cpp.
GOSSIP_SENDER_LEARN
#define GOSSIP_SENDER_LEARN 50
Definition at line 41 of file npc_professions.cpp.
GOSSIP_SENDER_UNLEARN
#define GOSSIP_SENDER_UNLEARN 51
Definition at line 42 of file npc_professions.cpp.
GOSSIP_UNLEARN_DRAGON
#define GOSSIP_UNLEARN_DRAGON "I wish to unlearn my Dragonscale Leatherworking specialization!"
Definition at line 49 of file npc_professions.cpp.
GOSSIP_UNLEARN_ELEMENTAL
#define GOSSIP_UNLEARN_ELEMENTAL "I wish to unlearn my Elemental Leatherworking specialization!"
Definition at line 53 of file npc_professions.cpp.
GOSSIP_UNLEARN_TRIBAL
#define GOSSIP_UNLEARN_TRIBAL "I wish to unlearn my Tribal Leatherworking specialization!"
Definition at line 57 of file npc_professions.cpp.
Enumeration Type Documentation
SpecializationQuests
enum SpecializationQuests
Enumerator
Q_DRAGON_ALLY
Q_DRAGON_HORDE
Q_ELEMENTAL_ALLY
Q_ELEMENTAL_HORDE
Q_TRIBAL_ALLY
Q_TRIBAL_HORDE
Definition at line 86 of file npc_professions.cpp.
SpecializationSpells
enum SpecializationSpells
Enumerator
S_DRAGON
S_ELEMENTAL
S_TRIBAL
S_LEARN_DRAGON
S_LEARN_ELEMENTAL
S_LEARN_TRIBAL
S_UNLEARN_DRAGON
S_UNLEARN_ELEMENTAL
S_UNLEARN_TRIBAL
S_SPELLFIRE
S_MOONCLOTH
S_SHADOWEAVE
S_LEARN_SPELLFIRE
S_LEARN_MOONCLOTH
S_LEARN_SHADOWEAVE
S_UNLEARN_SPELLFIRE
S_UNLEARN_MOONCLOTH
S_UNLEARN_SHADOWEAVE
Definition at line 61 of file npc_professions.cpp.
SpecializationTrainers
enum SpecializationTrainers
Enumerator
N_TRAINER_DRAGON1
N_TRAINER_DRAGON2
N_TRAINER_ELEMENTAL1
N_TRAINER_ELEMENTAL2
N_TRAINER_TRIBAL1
N_TRAINER_TRIBAL2
Definition at line 97 of file npc_professions.cpp.
Function Documentation
AddSC_npc_professions()
void AddSC_npc_professions ()
Definition at line 375 of file npc_professions.cpp.
References GossipHello_npc_prof_leather(), GossipSelect_npc_prof_leather(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
EquippedOk()
bool EquippedOk (Player * pPlayer, uint32 spellId)
Definition at line 128 of file npc_professions.cpp.
References debug_log(), SpellEntry::EffectTriggerSpell, EQUIPMENT_SLOT_END, EQUIPMENT_SLOT_START, Player::GetItemByPos(), Item::GetProto(), GetSpellStore(), INVENTORY_SLOT_BAG_0, ItemPrototype::ItemId, SQLStorage::LookupEntry(), and ItemPrototype::RequiredSpell.
Referenced by SendActionMenu_npc_prof_leather().
GetUnlearnCostMedium()
int32 GetUnlearnCostMedium (Player * pPlayer)
Definition at line 112 of file npc_professions.cpp.
References Unit::GetLevel().
Referenced by GossipHello_npc_prof_leather(), and SendActionMenu_npc_prof_leather().
GossipHello_npc_prof_leather()
bool GossipHello_npc_prof_leather (Player * pPlayer, Creature * pCreature)
Definition at line 219 of file npc_professions.cpp.
References BOX_UNLEARN_DRAGON, BOX_UNLEARN_ELEMENTAL, BOX_UNLEARN_TRIBAL, Object::GetEntry(), Player::GetGossipTextId(), Unit::GetLevel(), Object::GetObjectGuid(), Player::GetSkillValueBase(), GetUnlearnCostMedium(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, GOSSIP_ICON_CHAT, GOSSIP_ICON_TRAINER, GOSSIP_ICON_VENDOR, GOSSIP_LEARN_DRAGON, GOSSIP_LEARN_ELEMENTAL, GOSSIP_LEARN_TRIBAL, GOSSIP_SENDER_CHECK, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_BROWSE_GOODS, GOSSIP_TEXT_TRAIN, GOSSIP_UNLEARN_DRAGON, GOSSIP_UNLEARN_ELEMENTAL, GOSSIP_UNLEARN_TRIBAL, Player::HasSkill(), Player::HasSpell(), IsEligibleSpecializeLW(), Unit::isQuestGiver(), Unit::isTrainer(), Unit::isVendor(), N_TRAINER_DRAGON1, N_TRAINER_DRAGON2, N_TRAINER_ELEMENTAL1, N_TRAINER_ELEMENTAL2, N_TRAINER_TRIBAL1, N_TRAINER_TRIBAL2, Player::PrepareQuestMenu(), S_DRAGON, S_ELEMENTAL, S_TRIBAL, and SKILL_LEATHERWORKING.
Referenced by AddSC_npc_professions().
GossipSelect_npc_prof_leather()
bool GossipSelect_npc_prof_leather (Player * pPlayer, Creature * pCreature, uint32 uiSender, uint32 uiAction)
Definition at line 346 of file npc_professions.cpp.
References GOSSIP_SENDER_CHECK, GOSSIP_SENDER_MAIN, and SendActionMenu_npc_prof_leather().
Referenced by AddSC_npc_professions().
IsEligibleSpecializeLW()
bool IsEligibleSpecializeLW (Player * pPlayer)
Definition at line 205 of file npc_professions.cpp.
References Player::GetQuestRewardStatus(), Player::HasSpell(), Q_DRAGON_ALLY, Q_DRAGON_HORDE, Q_ELEMENTAL_ALLY, Q_ELEMENTAL_HORDE, Q_TRIBAL_ALLY, Q_TRIBAL_HORDE, S_DRAGON, S_ELEMENTAL, and S_TRIBAL.
Referenced by GossipHello_npc_prof_leather().
ProfessionUnlearnSpells()
void ProfessionUnlearnSpells (Player * pPlayer, uint32 type)
Definition at line 155 of file npc_professions.cpp.
References Player::removeSpell(), S_UNLEARN_DRAGON, S_UNLEARN_ELEMENTAL, S_UNLEARN_MOONCLOTH, S_UNLEARN_SHADOWEAVE, S_UNLEARN_SPELLFIRE, and S_UNLEARN_TRIBAL.
Referenced by SendActionMenu_npc_prof_leather().
SendActionMenu_npc_prof_leather()
void SendActionMenu_npc_prof_leather (Player * pPlayer, Creature * pCreature, uint32 uiAction)
Definition at line 272 of file npc_professions.cpp.
References BUY_ERR_NOT_ENOUGHT_MONEY, Unit::CastSpell(), EQUIP_ERR_CANT_DO_RIGHT_NOW, EquippedOk(), Player::GetMoney(), Object::GetObjectGuid(), GetUnlearnCostMedium(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ACTION_TRADE, GOSSIP_ACTION_TRAIN, Player::ModifyMoney(), ProfessionUnlearnSpells(), S_LEARN_DRAGON, S_LEARN_ELEMENTAL, S_LEARN_TRIBAL, S_UNLEARN_DRAGON, S_UNLEARN_ELEMENTAL, S_UNLEARN_TRIBAL, Player::SendBuyError(), Player::SendEquipError(), and TRIGGERED_OLD_TRIGGERED.
Referenced by GossipSelect_npc_prof_leather().