CMaNGOS_WoTLK: npcs_special.cpp File Reference
npcs_special.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "Globals/ObjectMgr.h"
#include "GameEvents/GameEventMgr.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/SpellAuras.h"
#include "World/WorldState.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct SpawnAssociation
struct npc_air_force_botsAI
struct npc_chicken_cluckAI
struct Location
struct npc_doctorAI
struct npc_injured_patientAI
struct npc_garments_of_questsAI
struct npc_guardianAI
struct npc_spring_rabbitAI
struct npc_redemption_targetAI
struct npc_burster_wormAI
struct npc_aoe_damage_triggerAI
struct npc_the_cleanerAI
struct npc_shaman_elementalAI
struct npc_shaman_fire_elementalAI
struct npc_shaman_earth_elementalAI
struct npc_snakesAI
struct npc_nether_rayAI
struct npc_mage_mirror_imageAI
struct InheritMastersThreatList
struct MirrorImageFrostbolt
struct npc_mojoAI
struct npc_fire_nova_totemAI
struct mob_phoenix_tkAI
struct npc_advanced_target_dummyAI
struct go_imp_in_a_ball
struct npc_imp_in_a_ball
struct HarvestSilithidEgg
struct ImpInABottleSay
struct GossipNPCAI
struct GossipNPCPeriodicTriggerFidget
struct GossipNPCPeriodicTalk
struct GossipNPCPeriodicTriggerTalk
struct GossipNPCAppearanceAllBrewfest
struct GossipNPCAppearanceAllSpiritOfCompetition
struct GossipNPCAppearanceAllPirateDay
Macros
#define A_RUNTOX -3742.96f
#define A_RUNTOY -4531.52f
#define A_RUNTOZ 11.91f
#define H_RUNTOX -1016.44f
#define H_RUNTOY -3508.48f
#define H_RUNTOZ 62.96f
#define GOSSIP_ITEM_TRICK_OR_TREAT "Trick or Treat!"
#define GOSSIP_ITEM_WHAT_TO_DO "What can I do at an Inn?"
Enumerations
enum SpawnType { SPAWNTYPE_TRIPWIRE_ROOFTOP , SPAWNTYPE_ALARMBOT }
enum { SPELL_GUARDS_MARK = 38067 , AURA_DURATION_TIME_LEFT = 10000 }
enum {
EMOTE_CLUCK_TEXT1 = -1000204 , EMOTE_CLUCK_TEXT2 = -1000205 , QUEST_CLUCK = 3861 , FACTION_FRIENDLY = 35 ,
FACTION_CHICKEN = 31
}
enum {
SAY_DOC1 = -1000201 , SAY_DOC2 = -1000202 , SAY_DOC3 = -1000203 , QUEST_TRIAGE_H = 6622 ,
QUEST_TRIAGE_A = 6624 , DOCTOR_ALLIANCE = 12939 , DOCTOR_HORDE = 12920 , ALLIANCE_COORDS = 7 ,
HORDE_COORDS = 6
}
enum {
SPELL_LESSER_HEAL_R2 = 2052 , SPELL_FORTITUDE_R1 = 1243 , QUEST_MOON = 5621 , QUEST_LIGHT_1 = 5624 ,
QUEST_LIGHT_2 = 5625 , QUEST_SPIRIT = 5648 , QUEST_DARKNESS = 5650 , ENTRY_SHAYA = 12429 ,
ENTRY_ROBERTS = 12423 , ENTRY_DOLF = 12427 , ENTRY_KORJA = 12430 , ENTRY_DG_KEL = 12428 ,
SAY_COMMON_HEALED = -1000231 , SAY_DG_KEL_THANKS = -1000232 , SAY_DG_KEL_GOODBYE = -1000233 , SAY_ROBERTS_THANKS = -1000256 ,
SAY_ROBERTS_GOODBYE = -1000257 , SAY_KORJA_THANKS = -1000258 , SAY_KORJA_GOODBYE = -1000259 , SAY_DOLF_THANKS = -1000260 ,
SAY_DOLF_GOODBYE = -1000261 , SAY_SHAYA_THANKS = -1000262 , SAY_SHAYA_GOODBYE = -1000263
}
enum GuardianOfB { SPELL_DEATHTOUCH = 5 , SAY_AGGRO = 2077 }
enum { TEXT_ID_WHAT_TO_DO = 1853 , SPELL_TRICK_OR_TREAT = 24751 , SPELL_TRICK_OR_TREATED = 24755 }
enum {
NPC_SPRING_RABBIT = 32791 , SPELL_SPRING_RABBIT_JUMP = 61724 , SPELL_SPRING_RABBIT_WANDER = 61726 , SEPLL_SUMMON_BABY_BUNNY = 61727 ,
SPELL_SPRING_RABBIT_IN_LOVE = 61728 , SPELL_SPRING_FLING = 61875
}
enum {
SAY_HEAL = -1000187 , SAY_HEAL_HENZE_NARM_FAULK = 2283 , SPELL_SYMBOL_OF_LIFE = 8593 , SPELL_QUEST_SELF_HEALING = 25155 ,
SPELL_SHIMMERING_VESSEL = 31225 , SPELL_REVIVE_SELF = 32343 , NPC_HENZE_FAULK = 6172 , NPC_NARM_FAULK = 6177 ,
NPC_FURBOLG_SHAMAN = 17542 , NPC_BLOOD_KNIGHT = 17768
}
enum npc_burster_worm {
SPELL_TUNNEL_BORE_PASSIVE = 29147 , SPELL_TUNNEL_BORE = 29148 , SPELL_TUNNEL_BORE_RED = 34039 , SPELL_TUNNEL_BORE_BONE_PASSIVE = 37989 ,
SPELL_TUNNEL_BORE_RED_PASSIVE = 34038 , SPELL_DAMAGING_TUNNEL_BORE_BONE_PASSIVE = 38885 , SPELL_BONE_BORE = 37990 , SPELL_BONE_BORE_2 = 38886 ,
SPELL_SANDWORM_SUBMERGE_VISUAL = 33928 , SPELL_SUBMERGED = 37751 , SPELL_STAND = 37752 , SPELL_CRUST_BURST = 33922 ,
SPELL_POISON = 31747 , SPELL_POISON_SPIT = 32330 , SPELL_BORE = 32738 , SPELL_ENRAGE = 32714 ,
SPELL_WORM_SWEEP = 30732 , SPELL_WORM_BLAST = 31378 , NPC_TUNNELER = 16968 , NPC_NETHERMINE_BURSTER = 23285 ,
NPC_MARAUDING_BURSTER = 16857 , NPC_SAND_WORM = 17075 , NPC_FULGORGE = 18678 , NPC_GREATER_CRUST_BURSTER = 21380 ,
NPC_CRUST_BURSTER = 16844 , NPC_BONE_CRAWLER = 21849 , NPC_HAISHULUD = 22038 , NPC_BONE_SIFTER = 22466 ,
NPC_MATURE_BONE_SIFTER = 22482 , PHASE_COMBAT = 1 , PHASE_CHASE = 2
}
enum BursterActions {
BURSTER_CHASE_DISTANCE , BURSTER_RANGED_ATTACK , BURSTER_ENABLE_ENRAGE , BURSTER_ENRAGE ,
BURSTER_BORE , BURSTER_SWEEP , BURSTER_ACTION_MAX , BURSTER_BIRTH_DELAY ,
BURSTER_CHASE_SEQUENCE
}
enum npc_aoe_damage_trigger {
NPC_VOID_ZONE = 16697 , NPC_LESSER_SHADOW_FISSURE = 17471 , NPC_LESSER_SHADOW_FISSURE_H = 20570 , NPC_WILD_SHADOW_FISSURE = 18370 ,
NPC_WILD_SHADOW_FISSURE_H = 20598 , SPELL_CONSUMPTION_NPC_16697 = 28874 , SPELL_CONSUMPTION_NPC_17471 = 30497 , SPELL_CONSUMPTION_NPC_20570 = 35952
}
enum { SPELL_IMMUNITY = 29230 , SAY_CLEANER_AGGRO = -1001253 }
enum { SPELL_ANGERED_EARTH = 36213 , SPELL_FIRE_SHIELD = 13377 , SPELL_FIRE_BLAST = 13339 , SPELL_FIRE_NOVA = 12470 }
enum FireElementalActions { ELEMENTAL_ACTION_FIRE_NOVA , ELEMENTAL_ACTION_FIRE_BLAST , ELEMENTAL_ACTION_MAX }
enum { SPELL_DEADLY_POISON_PASSIVE = 34657 , SPELL_MIND_NUMBING_POISON = 25810 , SPELL_CRIPPLING_POISON = 25809 , SPELL_HUNTER_SNAKE_TRAP_SCALING_01 = 62915 }
enum { SPELL_DRAIN_MANA = 17008 , SPELL_TAIL_STING = 36659 , SPELL_NETHER_SHOCK = 35334 }
enum RayActions { RAY_ACTION_NETHER_SHOCK , RAY_ACTION_DRAIN_MANA , RAY_ACTION_TAIL_STING , RAY_ACTION_MAX }
enum {
SPELL_MAGE_CLONE_ME = 45204 , SPELL_MAGE_MASTERS_THREAT_LIST = 58838 , SPELL_COPY_WEAPON = 41055 , SPELL_COPY_OFFHAND_WEAPON = 45206 ,
SPELL_MAGE_FROST_BOLT = 59638 , SPELL_MAGE_FIRE_BLAST = 59637
}
enum { SPELL_FEELING_FROGGY = 43906 , SPELL_HEARTS = 20372 , MOJO_WHISPS_COUNT = 8 }
enum {
SPELL_FIRE_NOVA_TOTEM_1 = 32062 , SPELL_FIRE_NOVA_1 = 32167 , SPELL_FIRE_NOVA_TOTEM_2 = 43436 , SPELL_FIRE_NOVA_2 = 43464 ,
SPELL_FIRE_NOVA_TOTEM_3 = 44257 , SPELL_FIRE_NOVA_3 = 46551
}
enum {
SPELL_FULL_HEAL = 17683 , SPELL_BURN_TK = 36720 , SPELL_EMBER_BLAST_TK = 34341 , SPELL_REBIRTH_SPAWN_TK = 35369 ,
SPELL_REBIRTH_RESPAWN_TK = 41587 , SPELL_PHOENIX_EGG_TK = 36724 , SPELL_BURN_MGT = 44197 , SPELL_EMBER_BLAST_MGT = 44199 ,
SPELL_REBIRTH_SPAWN_MGT = 44196 , SPELL_REBIRTH_RESPAWN_MGT = 44200 , SPELL_PHOENIX_EGG_MGT = 44195 , NPC_PHOENIX_TK = 21362 ,
NPC_PHOENIX_MGT = 24674
}
enum PhoenixActions { PHOENIX_ACTION_MAX , PHOENIX_EMBER_BLAST , PHOENIX_REBIRTH , PHOENIX_ATTACK_DELAY }
enum { SUICIDE = 7 , TARGET_DUMMY_SPAWN_EFFECT = 4507 }
enum {
SPELL_IMP_IN_A_BOTTLE_SAY = 40526 , SPELL_IMP_IN_A_BOTTLE_OBJECT = 40527 , SPELL_IMP_IN_A_BOTTLE_CREATURE = 40528 , SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_NOT = 40533 ,
SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_ROGUE = 40537 , SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_ROGUE_SOUND = 40539 , SPELL_CREATE_IMP_IN_A_BALL = 40552 , SOUND_ID_IMP_1 = 766 ,
SOUND_ID_IMP_2 = 770
}
enum GossipNPCSpells {
SPELL_GOSSIP_NPC_PERIODIC_DESPAWN = 33209 , SPELL_GOSSIP_NPC_PERIODIC_FIDGET = 33207 , SPELL_GOSSIP_NPC_PERIODIC_TALK = 33208 , SPELL_GOSSIP_NPC_TRIGGER_TALK = 33227 ,
NPC_HUMAN_COMMONER = 18927 , NPC_DWARF_COMMONER = 19148 , NPC_BLOOD_ELF_COMMONER = 19169 , NPC_DRAENEI_COMMONER = 19171 ,
NPC_GNOME_COMMONER = 19172 , NPC_NIGHT_ELF_COMMONER = 19173 , NPC_ORC_COMMONER = 19175 , NPC_TAUREN_COMMONER = 19176 ,
NPC_TROLL_COMMONER = 19177 , NPC_FORSAKEN_COMMONER = 19178 , NPC_GOBLIN_COMMONER = 20102
}
enum GossipNPCEvents : uint32 {
GOSSIP_EVENT_WINTER_VEIL , GOSSIP_EVENT_LUNAR_FESTIVAL , GOSSIP_EVENT_HALLOWS_END , GOSSIP_EVENT_BREWFEST ,
GOSSIP_EVENT_MIDSUMMER , GOSSIP_EVENT_SPIRIT_OF_COMPETITION , GOSSIP_EVENT_PIRATES_DAY , GOSSIP_EVENT_DARK_PORTAL
}
enum GossipNpcGossips {
GOSSIP_WINTER_VEIL_A = 7907 , GOSSIP_WINTER_VEIL_H = 7911 , GOSSIP_WINTER_VEIL_GOBLIN = 8065 , GOSSIP_LUNAR_FESTIVAL = 0 ,
GOSSIP_HALLOWS_END = 8939 , GOSSIP_BREWFEST = 8988 , GOSSIP_MIDSUMMER = 9148 , GOSSIP_SPIRIT_OF_COMPETITION = 9522 ,
GOSSIP_PIRATES_DAY = 0 , GOSSIP_DARK_PORTAL = 0
}
Functions
UnitAI * GetAI_npc_air_force_bots (Creature *pCreature)
UnitAI * GetAI_npc_chicken_cluck (Creature *pCreature)
UnitAI * GetAI_npc_injured_patient (Creature *pCreature)
bool QuestAccept_npc_doctor (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_doctor (Creature *pCreature)
UnitAI * GetAI_npc_garments_of_quests (Creature *pCreature)
UnitAI * GetAI_npc_guardian (Creature *pCreature)
bool GossipHello_npc_innkeeper (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_innkeeper (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_spring_rabbit (Creature *pCreature)
UnitAI * GetAI_npc_redemption_target (Creature *pCreature)
bool EffectDummyCreature_npc_redemption_target (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_the_cleaner (Creature *pCreature)
UnitAI * GetAI_npc_snakes (Creature *pCreature)
UnitAI * GetAI_npc_mojo (Creature *pCreature)
uint32 GetRandomText (const std::vector< uint32 > texts)
bool GossipHello_npc_gossip_npc (Player *player, Creature *creature)
void AddSC_npcs_special ()
Variables
const float RANGE_TRIPWIRE = 15.0f
const float RANGE_GUARDS_MARK = 50.0f
SpawnAssociation m_aSpawnAssociations []
static Location AllianceCoords []
static Location HordeCoords []
static const uint32 A_INJURED_SOLDIER = 12938
static const uint32 A_BADLY_INJURED_SOLDIER = 12936
static const uint32 A_CRITICALLY_INJURED_SOLDIER = 12937
const uint32 AllianceSoldierId [3]
static const uint32 H_INJURED_SOLDIER = 12923
static const uint32 H_BADLY_INJURED_SOLDIER = 12924
static const uint32 H_CRITICALLY_INJURED_SOLDIER = 12925
const uint32 HordeSoldierId [3]
static const float DIST_START_EVENT = 15.0f
std::vector< uint32 > impInABallTexts = { 21157,21158,21159,21160,21161,21162,21163,21164,21165,21169,21170,21171,21172,21173,21174,21175,21176,21177,21178,21179,21180,21181,21182,21183,21184,21185,21186,21187,21188,21189,21190,21191,21192,21193,21194,21195,21196,21197,21198,21200,21205,21208,21209,21210,21211,21212,21213,21214,21215,21216,21217,21218,21219,21220,21221,21222,21223,21224,21225,21226,21227,21228,21229,21230,21231,21232,21233,21234,21235,21236,21237,21238,21239,21240,21241,21242,21243,21244,21245,21246,21247 }
const std::vector< uint32 > winterTextsAlliance = { 16422, 24341, 16032, 24342 }
const std::vector< uint32 > winterTextsHorde = { 16464, 24324, 24325 }
const std::vector< uint32 > winterTextsGoblin = { 16423, 16463 }
const std::vector< uint32 > midsummerTextsAlliance = { 24532, 24531 }
const std::vector< uint32 > midsummerTextsHorde = { 24533, 24534 }
const std::vector< uint32 > brewfestTextsAlliance = { 23629, 23630 }
const std::vector< uint32 > brewfestTextsHorde = { 23627, 23628 }
const std::vector< uint32 > hallowsEndTextsAlliance = { 24346, 24348, 24338, 24339, 23287, 23293, 24347, 23357 }
const std::vector< uint32 > hallowsEndTextsHorde = { 23295, 24331, 23298, 24329, 24336, 23351, 24337, 24330 }
const std::vector< uint32 > lunarTextsAlliance = { 24349, 24350 }
const std::vector< uint32 > lunarTextsHorde = { 24332, 24333 }
Macro Definition Documentation
A_RUNTOX
#define A_RUNTOX -3742.96f
Definition at line 362 of file npcs_special.cpp.
A_RUNTOY
#define A_RUNTOY -4531.52f
Definition at line 363 of file npcs_special.cpp.
A_RUNTOZ
#define A_RUNTOZ 11.91f
Definition at line 364 of file npcs_special.cpp.
GOSSIP_ITEM_TRICK_OR_TREAT
#define GOSSIP_ITEM_TRICK_OR_TREAT "Trick or Treat!"
Definition at line 1054 of file npcs_special.cpp.
GOSSIP_ITEM_WHAT_TO_DO
#define GOSSIP_ITEM_WHAT_TO_DO "What can I do at an Inn?"
Definition at line 1055 of file npcs_special.cpp.
H_RUNTOX
#define H_RUNTOX -1016.44f
Definition at line 377 of file npcs_special.cpp.
H_RUNTOY
#define H_RUNTOY -3508.48f
Definition at line 378 of file npcs_special.cpp.
H_RUNTOZ
#define H_RUNTOZ 62.96f
Definition at line 379 of file npcs_special.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_GUARDS_MARK
AURA_DURATION_TIME_LEFT
Definition at line 71 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_CLUCK_TEXT1
EMOTE_CLUCK_TEXT2
QUEST_CLUCK
FACTION_FRIENDLY
FACTION_CHICKEN
Definition at line 265 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_DOC1
SAY_DOC2
SAY_DOC3
QUEST_TRIAGE_H
QUEST_TRIAGE_A
DOCTOR_ALLIANCE
DOCTOR_HORDE
ALLIANCE_COORDS
HORDE_COORDS
Definition at line 330 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_LESSER_HEAL_R2
SPELL_FORTITUDE_R1
QUEST_MOON
QUEST_LIGHT_1
QUEST_LIGHT_2
QUEST_SPIRIT
QUEST_DARKNESS
ENTRY_SHAYA
ENTRY_ROBERTS
ENTRY_DOLF
ENTRY_KORJA
ENTRY_DG_KEL
SAY_COMMON_HEALED
SAY_DG_KEL_THANKS
SAY_DG_KEL_GOODBYE
SAY_ROBERTS_THANKS
SAY_ROBERTS_GOODBYE
SAY_KORJA_THANKS
SAY_KORJA_GOODBYE
SAY_DOLF_THANKS
SAY_DOLF_GOODBYE
SAY_SHAYA_THANKS
SAY_SHAYA_GOODBYE
Definition at line 794 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
TEXT_ID_WHAT_TO_DO
SPELL_TRICK_OR_TREAT
SPELL_TRICK_OR_TREATED
Definition at line 1046 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_SPRING_RABBIT
SPELL_SPRING_RABBIT_JUMP
SPELL_SPRING_RABBIT_WANDER
SEPLL_SUMMON_BABY_BUNNY
SPELL_SPRING_RABBIT_IN_LOVE
SPELL_SPRING_FLING
Definition at line 1104 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_HEAL
SAY_HEAL_HENZE_NARM_FAULK
SPELL_SYMBOL_OF_LIFE
SPELL_QUEST_SELF_HEALING
SPELL_SHIMMERING_VESSEL
SPELL_REVIVE_SELF
NPC_HENZE_FAULK
NPC_NARM_FAULK
NPC_FURBOLG_SHAMAN
NPC_BLOOD_KNIGHT
Definition at line 1282 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_IMMUNITY
SAY_CLEANER_AGGRO
Definition at line 1780 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ANGERED_EARTH
SPELL_FIRE_SHIELD
SPELL_FIRE_BLAST
SPELL_FIRE_NOVA
Definition at line 1832 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DEADLY_POISON_PASSIVE
SPELL_MIND_NUMBING_POISON
SPELL_CRIPPLING_POISON
SPELL_HUNTER_SNAKE_TRAP_SCALING_01
Definition at line 1929 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DRAIN_MANA
SPELL_TAIL_STING
SPELL_NETHER_SHOCK
Definition at line 1981 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_MAGE_CLONE_ME
SPELL_MAGE_MASTERS_THREAT_LIST
SPELL_COPY_WEAPON
SPELL_COPY_OFFHAND_WEAPON
SPELL_MAGE_FROST_BOLT
SPELL_MAGE_FIRE_BLAST
Definition at line 2057 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FEELING_FROGGY
SPELL_HEARTS
MOJO_WHISPS_COUNT
Definition at line 2165 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FIRE_NOVA_TOTEM_1
SPELL_FIRE_NOVA_1
SPELL_FIRE_NOVA_TOTEM_2
SPELL_FIRE_NOVA_2
SPELL_FIRE_NOVA_TOTEM_3
SPELL_FIRE_NOVA_3
Definition at line 2268 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FULL_HEAL
SPELL_BURN_TK
SPELL_EMBER_BLAST_TK
SPELL_REBIRTH_SPAWN_TK
SPELL_REBIRTH_RESPAWN_TK
SPELL_PHOENIX_EGG_TK
SPELL_BURN_MGT
SPELL_EMBER_BLAST_MGT
SPELL_REBIRTH_SPAWN_MGT
SPELL_REBIRTH_RESPAWN_MGT
SPELL_PHOENIX_EGG_MGT
NPC_PHOENIX_TK
NPC_PHOENIX_MGT
Definition at line 2312 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SUICIDE
TARGET_DUMMY_SPAWN_EFFECT
Definition at line 2496 of file npcs_special.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_IMP_IN_A_BOTTLE_SAY
SPELL_IMP_IN_A_BOTTLE_OBJECT
SPELL_IMP_IN_A_BOTTLE_CREATURE
SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_NOT
SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_ROGUE
SPELL_IMP_IN_A_BOTTLE_SPECIAL_CASE_ROGUE_SOUND
SPELL_CREATE_IMP_IN_A_BALL
SOUND_ID_IMP_1
SOUND_ID_IMP_2
Definition at line 2529 of file npcs_special.cpp.
BursterActions
enum BursterActions
Enumerator
BURSTER_CHASE_DISTANCE
BURSTER_RANGED_ATTACK
BURSTER_ENABLE_ENRAGE
BURSTER_ENRAGE
BURSTER_BORE
BURSTER_SWEEP
BURSTER_ACTION_MAX
BURSTER_BIRTH_DELAY
BURSTER_CHASE_SEQUENCE
Definition at line 1477 of file npcs_special.cpp.
FireElementalActions
enum FireElementalActions
Enumerator
ELEMENTAL_ACTION_FIRE_NOVA
ELEMENTAL_ACTION_FIRE_BLAST
ELEMENTAL_ACTION_MAX
Definition at line 1857 of file npcs_special.cpp.
GossipNPCEvents
enum GossipNPCEvents : uint32
Enumerator
GOSSIP_EVENT_WINTER_VEIL
GOSSIP_EVENT_LUNAR_FESTIVAL
GOSSIP_EVENT_HALLOWS_END
GOSSIP_EVENT_BREWFEST
GOSSIP_EVENT_MIDSUMMER
GOSSIP_EVENT_SPIRIT_OF_COMPETITION
GOSSIP_EVENT_PIRATES_DAY
GOSSIP_EVENT_DARK_PORTAL
Definition at line 2648 of file npcs_special.cpp.
GossipNpcGossips
enum GossipNpcGossips
Enumerator
GOSSIP_WINTER_VEIL_A
GOSSIP_WINTER_VEIL_H
GOSSIP_WINTER_VEIL_GOBLIN
GOSSIP_LUNAR_FESTIVAL
GOSSIP_HALLOWS_END
GOSSIP_BREWFEST
GOSSIP_MIDSUMMER
GOSSIP_SPIRIT_OF_COMPETITION
GOSSIP_PIRATES_DAY
GOSSIP_DARK_PORTAL
Definition at line 3073 of file npcs_special.cpp.
GossipNPCSpells
enum GossipNPCSpells
Enumerator
SPELL_GOSSIP_NPC_PERIODIC_DESPAWN
SPELL_GOSSIP_NPC_PERIODIC_FIDGET
SPELL_GOSSIP_NPC_PERIODIC_TALK
SPELL_GOSSIP_NPC_TRIGGER_TALK
NPC_HUMAN_COMMONER
NPC_DWARF_COMMONER
NPC_BLOOD_ELF_COMMONER
NPC_DRAENEI_COMMONER
NPC_GNOME_COMMONER
NPC_NIGHT_ELF_COMMONER
NPC_ORC_COMMONER
NPC_TAUREN_COMMONER
NPC_TROLL_COMMONER
NPC_FORSAKEN_COMMONER
NPC_GOBLIN_COMMONER
Definition at line 2628 of file npcs_special.cpp.
GuardianOfB
enum GuardianOfB
Enumerator
SPELL_DEATHTOUCH
SAY_AGGRO
Definition at line 1005 of file npcs_special.cpp.
npc_aoe_damage_trigger
enum npc_aoe_damage_trigger
Enumerator
NPC_VOID_ZONE
NPC_LESSER_SHADOW_FISSURE
NPC_LESSER_SHADOW_FISSURE_H
NPC_WILD_SHADOW_FISSURE
NPC_WILD_SHADOW_FISSURE_H
SPELL_CONSUMPTION_NPC_16697
SPELL_CONSUMPTION_NPC_17471
SPELL_CONSUMPTION_NPC_20570
Definition at line 1724 of file npcs_special.cpp.
npc_burster_worm
enum npc_burster_worm
Enumerator
SPELL_TUNNEL_BORE_PASSIVE
SPELL_TUNNEL_BORE
SPELL_TUNNEL_BORE_RED
SPELL_TUNNEL_BORE_BONE_PASSIVE
SPELL_TUNNEL_BORE_RED_PASSIVE
SPELL_DAMAGING_TUNNEL_BORE_BONE_PASSIVE
SPELL_BONE_BORE
SPELL_BONE_BORE_2
SPELL_SANDWORM_SUBMERGE_VISUAL
SPELL_SUBMERGED
SPELL_STAND
SPELL_CRUST_BURST
SPELL_POISON
SPELL_POISON_SPIT
SPELL_BORE
SPELL_ENRAGE
SPELL_WORM_SWEEP
SPELL_WORM_BLAST
NPC_TUNNELER
NPC_NETHERMINE_BURSTER
NPC_MARAUDING_BURSTER
NPC_SAND_WORM
NPC_FULGORGE
NPC_GREATER_CRUST_BURSTER
NPC_CRUST_BURSTER
NPC_BONE_CRAWLER
NPC_HAISHULUD
NPC_BONE_SIFTER
NPC_MATURE_BONE_SIFTER
PHASE_COMBAT
PHASE_CHASE
Definition at line 1431 of file npcs_special.cpp.
PhoenixActions
enum PhoenixActions
Enumerator
PHOENIX_ACTION_MAX
PHOENIX_EMBER_BLAST
PHOENIX_REBIRTH
PHOENIX_ATTACK_DELAY
Definition at line 2335 of file npcs_special.cpp.
RayActions
enum RayActions
Enumerator
RAY_ACTION_NETHER_SHOCK
RAY_ACTION_DRAIN_MANA
RAY_ACTION_TAIL_STING
RAY_ACTION_MAX
Definition at line 1988 of file npcs_special.cpp.
SpawnType
enum SpawnType
Enumerator
SPAWNTYPE_TRIPWIRE_ROOFTOP
SPAWNTYPE_ALARMBOT
Definition at line 58 of file npcs_special.cpp.
Function Documentation
AddSC_npcs_special()
void AddSC_npcs_special ()
Definition at line 3115 of file npcs_special.cpp.
References EffectDummyCreature_npc_redemption_target(), Script::GetAI, GetAI_npc_air_force_bots(), GetAI_npc_chicken_cluck(), GetAI_npc_doctor(), GetAI_npc_garments_of_quests(), GetAI_npc_guardian(), GetAI_npc_injured_patient(), GetAI_npc_mojo(), GetAI_npc_redemption_target(), GetAI_npc_snakes(), GetAI_npc_spring_rabbit(), GetAI_npc_the_cleaner(), Script::GetGameObjectAI, GossipHello_npc_gossip_npc(), GossipHello_npc_innkeeper(), GossipSelect_npc_innkeeper(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_doctor(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_redemption_target()
bool EffectDummyCreature_npc_redemption_target (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 1412 of file npcs_special.cpp.
References Creature::AI(), EFFECT_INDEX_0, Object::GetObjectGuid(), SPELL_SHIMMERING_VESSEL, and SPELL_SYMBOL_OF_LIFE.
Referenced by AddSC_npcs_special().
GetAI_npc_air_force_bots()
UnitAI* GetAI_npc_air_force_bots (Creature * pCreature)
Definition at line 256 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_chicken_cluck()
UnitAI* GetAI_npc_chicken_cluck (Creature * pCreature)
Definition at line 321 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_doctor()
UnitAI* GetAI_npc_doctor (Creature * pCreature)
Definition at line 785 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_garments_of_quests()
UnitAI* GetAI_npc_garments_of_quests (Creature * pCreature)
Definition at line 996 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_guardian()
UnitAI* GetAI_npc_guardian (Creature * pCreature)
Definition at line 1033 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_injured_patient()
UnitAI* GetAI_npc_injured_patient (Creature * pCreature)
Definition at line 578 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_mojo()
UnitAI* GetAI_npc_mojo (Creature * pCreature)
Definition at line 2263 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_redemption_target()
UnitAI* GetAI_npc_redemption_target (Creature * pCreature)
Definition at line 1407 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_snakes()
UnitAI* GetAI_npc_snakes (Creature * pCreature)
Definition at line 1976 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_spring_rabbit()
UnitAI* GetAI_npc_spring_rabbit (Creature * pCreature)
Definition at line 1273 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetAI_npc_the_cleaner()
UnitAI* GetAI_npc_the_cleaner (Creature * pCreature)
Definition at line 1827 of file npcs_special.cpp.
Referenced by AddSC_npcs_special().
GetRandomText()
uint32 GetRandomText (const std::vector< uint32 > texts)
Definition at line 2855 of file npcs_special.cpp.
References urand().
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
GossipHello_npc_gossip_npc()
bool GossipHello_npc_gossip_npc (Player * player, Creature * creature)
Definition at line 3087 of file npcs_special.cpp.
References Creature::AI(), ALLIANCE, GOSSIP_BREWFEST, GOSSIP_DARK_PORTAL, GOSSIP_EVENT_BREWFEST, GOSSIP_EVENT_DARK_PORTAL, GOSSIP_EVENT_HALLOWS_END, GOSSIP_EVENT_LUNAR_FESTIVAL, GOSSIP_EVENT_MIDSUMMER, GOSSIP_EVENT_PIRATES_DAY, GOSSIP_EVENT_SPIRIT_OF_COMPETITION, GOSSIP_EVENT_WINTER_VEIL, GOSSIP_HALLOWS_END, GOSSIP_LUNAR_FESTIVAL, GOSSIP_MIDSUMMER, GOSSIP_PIRATES_DAY, GOSSIP_SPIRIT_OF_COMPETITION, GOSSIP_WINTER_VEIL_A, GOSSIP_WINTER_VEIL_GOBLIN, GOSSIP_WINTER_VEIL_H, GossipNPCAI::m_chosenEvent, GossipNPCAI::m_team, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), and TEAM_NONE.
Referenced by AddSC_npcs_special().
GossipHello_npc_innkeeper()
bool GossipHello_npc_innkeeper (Player * pPlayer, Creature * pCreature)
Definition at line 1057 of file npcs_special.cpp.
References AREA_FLAG_LOWLEVEL, EFFECT_INDEX_0, GetAreaEntryByAreaID(), WorldObject::GetAreaId(), Player::GetDefaultGossipMenuForSource(), Object::GetEntry(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TRICK_OR_TREAT, GOSSIP_ITEM_WHAT_TO_DO, GOSSIP_SENDER_MAIN, Unit::HasAura(), HOLIDAY_HALLOWS_END, IsHolidayActive(), Player::PrepareGossipMenu(), Player::SendPreparedGossip(), SPELL_TRICK_OR_TREATED, and Player::TalkedToCreature().
Referenced by AddSC_npcs_special().
GossipSelect_npc_innkeeper()
bool GossipSelect_npc_innkeeper (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1076 of file npcs_special.cpp.
References Unit::CastSpell(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_OPTION_INNKEEPER, GOSSIP_OPTION_VENDOR, Player::SetBindPoint(), SPELL_TRICK_OR_TREAT, TEXT_ID_WHAT_TO_DO, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_npcs_special().
QuestAccept_npc_doctor()
bool QuestAccept_npc_doctor (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 774 of file npcs_special.cpp.
References Creature::AI(), Quest::GetQuestId(), QUEST_TRIAGE_A, and QUEST_TRIAGE_H.
Referenced by AddSC_npcs_special().
Variable Documentation
A_BADLY_INJURED_SOLDIER
const uint32 A_BADLY_INJURED_SOLDIER = 12936 static
Definition at line 382 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
A_CRITICALLY_INJURED_SOLDIER
const uint32 A_CRITICALLY_INJURED_SOLDIER = 12937 static
Definition at line 383 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
A_INJURED_SOLDIER
const uint32 A_INJURED_SOLDIER = 12938 static
Definition at line 381 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
AllianceCoords
Location AllianceCoords[] static
Initial value:
=
{
    { -3757.38f, -4533.05f, 14.16f, 3.62f },
    { -3754.36f, -4539.13f, 14.16f, 5.13f },
    { -3749.54f, -4540.25f, 14.28f, 3.34f },
    { -3742.10f, -4536.85f, 14.28f, 3.64f },
    { -3755.89f, -4529.07f, 14.05f, 0.57f },
    { -3749.51f, -4527.08f, 14.07f, 5.26f },
    { -3746.37f, -4525.35f, 14.16f, 5.22f },
}
Definition at line 350 of file npcs_special.cpp.
Referenced by npc_doctorAI::BeginEvent().
AllianceSoldierId
const uint32 AllianceSoldierId[3]
Initial value:
=
{
    A_INJURED_SOLDIER,
    A_BADLY_INJURED_SOLDIER,
    A_CRITICALLY_INJURED_SOLDIER
}
Definition at line 385 of file npcs_special.cpp.
Referenced by npc_doctorAI::UpdateAI().
brewfestTextsAlliance
const std::vector<uint32> brewfestTextsAlliance = { 23629, 23630 }
Definition at line 2846 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
brewfestTextsHorde
const std::vector<uint32> brewfestTextsHorde = { 23627, 23628 }
Definition at line 2847 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
DIST_START_EVENT
const float DIST_START_EVENT = 15.0f static
Definition at line 1115 of file npcs_special.cpp.
Referenced by npc_spring_rabbitAI::MoveInLineOfSight().
H_BADLY_INJURED_SOLDIER
const uint32 H_BADLY_INJURED_SOLDIER = 12924 static
Definition at line 393 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
H_CRITICALLY_INJURED_SOLDIER
const uint32 H_CRITICALLY_INJURED_SOLDIER = 12925 static
Definition at line 394 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
H_INJURED_SOLDIER
const uint32 H_INJURED_SOLDIER = 12923 static
Definition at line 392 of file npcs_special.cpp.
Referenced by npc_injured_patientAI::Reset(), and npc_injured_patientAI::SpellHit().
hallowsEndTextsAlliance
const std::vector<uint32> hallowsEndTextsAlliance = { 24346, 24348, 24338, 24339, 23287, 23293, 24347, 23357 }
Definition at line 2849 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
hallowsEndTextsHorde
const std::vector<uint32> hallowsEndTextsHorde = { 23295, 24331, 23298, 24329, 24336, 23351, 24337, 24330 }
Definition at line 2850 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
HordeCoords
Location HordeCoords[] static
Initial value:
=
{
    { -1013.75f, -3492.59f, 62.62f, 4.34f },
    { -1017.72f, -3490.92f, 62.62f, 4.34f },
    { -1015.77f, -3497.15f, 62.82f, 4.34f },
    { -1019.51f, -3495.49f, 62.82f, 4.34f },
    { -1017.25f, -3500.85f, 62.98f, 4.34f },
    { -1020.95f, -3499.21f, 62.98f, 4.34f }
}
Definition at line 366 of file npcs_special.cpp.
Referenced by npc_doctorAI::BeginEvent().
HordeSoldierId
const uint32 HordeSoldierId[3]
Initial value:
=
{
    H_INJURED_SOLDIER,
    H_BADLY_INJURED_SOLDIER,
    H_CRITICALLY_INJURED_SOLDIER
}
Definition at line 396 of file npcs_special.cpp.
Referenced by npc_doctorAI::UpdateAI().
impInABallTexts
std::vector<uint32> impInABallTexts = { 21157,21158,21159,21160,21161,21162,21163,21164,21165,21169,21170,21171,21172,21173,21174,21175,21176,21177,21178,21179,21180,21181,21182,21183,21184,21185,21186,21187,21188,21189,21190,21191,21192,21193,21194,21195,21196,21197,21198,21200,21205,21208,21209,21210,21211,21212,21213,21214,21215,21216,21217,21218,21219,21220,21221,21222,21223,21224,21225,21226,21227,21228,21229,21230,21231,21232,21233,21234,21235,21236,21237,21238,21239,21240,21241,21242,21243,21244,21245,21246,21247 }
Definition at line 2546 of file npcs_special.cpp.
Referenced by ImpInABottleSay::OnEffectExecute().
lunarTextsAlliance
const std::vector<uint32> lunarTextsAlliance = { 24349, 24350 }
Definition at line 2852 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
lunarTextsHorde
const std::vector<uint32> lunarTextsHorde = { 24332, 24333 }
Definition at line 2853 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
m_aSpawnAssociations
SpawnAssociation m_aSpawnAssociations[]
Initial value:
=
{
    {2614,  15241, SPAWNTYPE_ALARMBOT},
    {2615,  15242, SPAWNTYPE_ALARMBOT},
    {21974, 21976, SPAWNTYPE_ALARMBOT},
    {21993, 15242, SPAWNTYPE_ALARMBOT},
    {21996, 15241, SPAWNTYPE_ALARMBOT},
    {21997, 21976, SPAWNTYPE_ALARMBOT},
    {21999, 15241, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22001, 15242, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22002, 15242, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22003, 15241, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22063, 21976, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22065, 22064, SPAWNTYPE_ALARMBOT},
    {22066, 22067, SPAWNTYPE_ALARMBOT},
    {22068, 22064, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22069, 22064, SPAWNTYPE_ALARMBOT},
    {22070, 22067, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22071, 22067, SPAWNTYPE_ALARMBOT},
    {22078, 22077, SPAWNTYPE_ALARMBOT},
    {22079, 22077, SPAWNTYPE_ALARMBOT},
    {22080, 22077, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22086, 22085, SPAWNTYPE_ALARMBOT},
    {22087, 22085, SPAWNTYPE_ALARMBOT},
    {22088, 22085, SPAWNTYPE_TRIPWIRE_ROOFTOP},
    {22090, 22089, SPAWNTYPE_ALARMBOT},
    {22124, 22122, SPAWNTYPE_ALARMBOT},
    {22125, 22122, SPAWNTYPE_ALARMBOT},
    {22126, 22122, SPAWNTYPE_ALARMBOT}
}
Definition at line 80 of file npcs_special.cpp.
Referenced by npc_air_force_botsAI::npc_air_force_botsAI().
midsummerTextsAlliance
const std::vector<uint32> midsummerTextsAlliance = { 24532, 24531 }
Definition at line 2843 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
midsummerTextsHorde
const std::vector<uint32> midsummerTextsHorde = { 24533, 24534 }
Definition at line 2844 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
RANGE_GUARDS_MARK
const float RANGE_GUARDS_MARK = 50.0f
Definition at line 78 of file npcs_special.cpp.
Referenced by npc_air_force_botsAI::MoveInLineOfSight().
RANGE_TRIPWIRE
const float RANGE_TRIPWIRE = 15.0f
Definition at line 77 of file npcs_special.cpp.
Referenced by npc_air_force_botsAI::MoveInLineOfSight().
winterTextsAlliance
const std::vector<uint32> winterTextsAlliance = { 16422, 24341, 16032, 24342 }
Definition at line 2839 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
winterTextsGoblin
const std::vector<uint32> winterTextsGoblin = { 16423, 16463 }
Definition at line 2841 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().
winterTextsHorde
const std::vector<uint32> winterTextsHorde = { 16464, 24324, 24325 }
Definition at line 2840 of file npcs_special.cpp.
Referenced by GossipNPCPeriodicTriggerTalk::OnEffectExecute().