CMaNGOS_WoTLK: Object.cpp File Reference
Object.cpp File Reference
#include "Entities/Object.h"
#include "Globals/SharedDefines.h"
#include "Server/WorldPacket.h"
#include "Server/Opcodes.h"
#include "Log.h"
#include "World/World.h"
#include "Entities/Creature.h"
#include "Entities/Player.h"
#include "Entities/Vehicle.h"
#include "Entities/GameObject.h"
#include "Entities/Transports.h"
#include "Globals/ObjectMgr.h"
#include "Entities/ObjectGuid.h"
#include "Entities/UpdateData.h"
#include "UpdateMask.h"
#include "Util/Util.h"
#include "Grids/CellImpl.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Maps/GridDefines.h"
#include "Maps/MapManager.h"
#include "Maps/ObjectPosSelector.h"
#include "Entities/TemporarySpawn.h"
#include "Movement/packet_builder.h"
#include "Entities/CreatureLinkingMgr.h"
#include "Chat/Chat.h"
#include "Loot/LootMgr.h"
#include "Spells/SpellMgr.h"
#include "MotionGenerators/PathFinder.h"
#include "Movement/MoveSpline.h"
Data Structures
class MaNGOS::MonsterChatBuilder
class MaNGOS::NearUsedPosDo
struct WorldObjectChangeAccumulator
Namespaces
MaNGOS
class Singleton
Macros
#define OCCUPY_POS_DEPTH_FACTOR 1.8f
Functions
void _DoLocalizedTextAround (WorldObject const *source, std::vector< std::string > content, ChatMsg msgtype, Language language, Unit const *target, float range)
Helper function to create localized around a source.
void ConvertMillisecondToStr (std::chrono::milliseconds &duration, std::stringstream &durationStr)
bool operator!= (const Position &left, const Position &right)
Macro Definition Documentation
OCCUPY_POS_DEPTH_FACTOR
#define OCCUPY_POS_DEPTH_FACTOR 1.8f
Definition at line 2366 of file Object.cpp.
Function Documentation
_DoLocalizedTextAround()
void _DoLocalizedTextAround (WorldObject const * source, std::vector< std::string > content, ChatMsg msgtype, Language language, Unit const * target, float range)
Helper function to create localized around a source.
Definition at line 1989 of file Object.cpp.
References Cell::VisitWorldObjects().
Referenced by WorldObject::MonsterText().
ConvertMillisecondToStr()
void ConvertMillisecondToStr (std::chrono::milliseconds & duration, std::stringstream & durationStr)
Definition at line 3015 of file Object.cpp.
Referenced by WorldObject::PrintCooldownList().
operator!=()
bool operator!= (const Position & left, const Position & right)
Definition at line 3289 of file Object.cpp.
References Position::o, Position::x, Position::y, and Position::z.