CMaNGOS_WoTLK: ObjectGuid.h File Reference
ObjectGuid.h File Reference
#include "Common.h"
#include "Util/ByteBuffer.h"
#include <atomic>
Data Structures
struct PackedGuidReader
class ObjectGuid
class PackedGuid
class ObjectGuidGenerator< high >
class std::hash< ObjectGuid >
Namespaces
std
Macros
#define MAX_TYPE_ID 8
#define PACKED_GUID_MIN_BUFFER_SIZE 9
Typedefs
typedef std::set< ObjectGuid > GuidSet
typedef std::list< ObjectGuid > GuidList
typedef std::vector< ObjectGuid > GuidVector
Enumerations
enum TypeID {
TYPEID_OBJECT = 0 , TYPEID_ITEM = 1 , TYPEID_CONTAINER = 2 , TYPEID_UNIT = 3 ,
TYPEID_PLAYER = 4 , TYPEID_GAMEOBJECT = 5 , TYPEID_DYNAMICOBJECT = 6 , TYPEID_CORPSE = 7
}
enum TypeMask {
TYPEMASK_OBJECT = 0x0001 , TYPEMASK_ITEM = 0x0002 , TYPEMASK_CONTAINER = 0x0004 , TYPEMASK_UNIT = 0x0008 ,
TYPEMASK_PLAYER = 0x0010 , TYPEMASK_GAMEOBJECT = 0x0020 , TYPEMASK_DYNAMICOBJECT = 0x0040 , TYPEMASK_CORPSE = 0x0080 ,
TYPEMASK_CREATURE_OR_GAMEOBJECT = TYPEMASK_UNIT | TYPEMASK_GAMEOBJECT , TYPEMASK_CREATURE_GAMEOBJECT_OR_ITEM = TYPEMASK_UNIT | TYPEMASK_GAMEOBJECT | TYPEMASK_ITEM , TYPEMASK_CREATURE_GAMEOBJECT_PLAYER_OR_ITEM = TYPEMASK_UNIT | TYPEMASK_GAMEOBJECT | TYPEMASK_ITEM | TYPEMASK_PLAYER , TYPEMASK_WORLDOBJECT = TYPEMASK_UNIT | TYPEMASK_PLAYER | TYPEMASK_GAMEOBJECT | TYPEMASK_DYNAMICOBJECT | TYPEMASK_CORPSE
}
enum HighGuid {
HIGHGUID_ITEM = 0x470 , HIGHGUID_CONTAINER = 0x470 , HIGHGUID_PLAYER = 0x000 , HIGHGUID_GAMEOBJECT = 0xF11 ,
HIGHGUID_TRANSPORT = 0xF12 , HIGHGUID_UNIT = 0xF13 , HIGHGUID_PET = 0xF14 , HIGHGUID_VEHICLE = 0xF15 ,
HIGHGUID_DYNAMICOBJECT = 0xF10 , HIGHGUID_CORPSE = 0xF50 , HIGHGUID_MO_TRANSPORT = 0x1FC , HIGHGUID_INSTANCE = 0x1F4 ,
HIGHGUID_GROUP = 0x1F5
}
Functions
ByteBuffer & operator<< (ByteBuffer &buf, ObjectGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, ObjectGuid &guid)
ByteBuffer & operator<< (ByteBuffer &buf, PackedGuid const &guid)
ByteBuffer & operator>> (ByteBuffer &buf, PackedGuidReader const &guid)
Macro Definition Documentation
MAX_TYPE_ID
#define MAX_TYPE_ID 8
Definition at line 38 of file ObjectGuid.h.
PACKED_GUID_MIN_BUFFER_SIZE
#define PACKED_GUID_MIN_BUFFER_SIZE 9
Definition at line 214 of file ObjectGuid.h.
Typedef Documentation
GuidList
typedef std::list<ObjectGuid> GuidList
Definition at line 210 of file ObjectGuid.h.
GuidSet
typedef std::set<ObjectGuid> GuidSet
Definition at line 209 of file ObjectGuid.h.
GuidVector
typedef std::vector<ObjectGuid> GuidVector
Definition at line 211 of file ObjectGuid.h.
Enumeration Type Documentation
HighGuid
enum HighGuid
Enumerator
HIGHGUID_ITEM
HIGHGUID_CONTAINER
HIGHGUID_PLAYER
HIGHGUID_GAMEOBJECT
HIGHGUID_TRANSPORT
HIGHGUID_UNIT
HIGHGUID_PET
HIGHGUID_VEHICLE
HIGHGUID_DYNAMICOBJECT
HIGHGUID_CORPSE
HIGHGUID_MO_TRANSPORT
HIGHGUID_INSTANCE
HIGHGUID_GROUP
Definition at line 59 of file ObjectGuid.h.
TypeID
enum TypeID
Enumerator
TYPEID_OBJECT
TYPEID_ITEM
TYPEID_CONTAINER
TYPEID_UNIT
TYPEID_PLAYER
TYPEID_GAMEOBJECT
TYPEID_DYNAMICOBJECT
TYPEID_CORPSE
Definition at line 26 of file ObjectGuid.h.
TypeMask
enum TypeMask
Enumerator
TYPEMASK_OBJECT
TYPEMASK_ITEM
TYPEMASK_CONTAINER
TYPEMASK_UNIT
TYPEMASK_PLAYER
TYPEMASK_GAMEOBJECT
TYPEMASK_DYNAMICOBJECT
TYPEMASK_CORPSE
TYPEMASK_CREATURE_OR_GAMEOBJECT
TYPEMASK_CREATURE_GAMEOBJECT_OR_ITEM
TYPEMASK_CREATURE_GAMEOBJECT_PLAYER_OR_ITEM
TYPEMASK_WORLDOBJECT
Definition at line 40 of file ObjectGuid.h.
Function Documentation
operator<<() [1/2]
ByteBuffer& operator<< (ByteBuffer & buf, ObjectGuid const & guid)
Definition at line 77 of file ObjectGuid.cpp.
References ObjectGuid::GetRawValue().
operator<<() [2/2]
ByteBuffer& operator<< (ByteBuffer & buf, PackedGuid const & guid)
Definition at line 218 of file ObjectGuid.cpp.
operator>>() [1/2]
ByteBuffer& operator>> (ByteBuffer & buf, ObjectGuid & guid)
Definition at line 83 of file ObjectGuid.cpp.
References ByteBuffer::read(), and ObjectGuid::Set().
operator>>() [2/2]
ByteBuffer& operator>> (ByteBuffer & buf, PackedGuidReader const & guid)
Definition at line 95 of file ObjectGuid.cpp.
References PackedGuidReader::m_guidPtr, ByteBuffer::readPackGUID(), and ObjectGuid::Set().