CMaNGOS_WoTLK: ObjectGridLoader.cpp File Reference
ObjectGridLoader.cpp File Reference
#include "Grids/ObjectGridLoader.h"
#include "Globals/ObjectAccessor.h"
#include "Globals/ObjectMgr.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Entities/Creature.h"
#include "Entities/DynamicObject.h"
#include "Entities/Corpse.h"
#include "World/World.h"
#include "Grids/CellImpl.h"
#include "Maps/GridDefines.h"
Data Structures
class ObjectGridRespawnMover
class ObjectWorldLoader
Functions
template<class T >
void addUnitState (T *, CellPair const &)
template<>
void addUnitState (GameObject *obj, CellPair const &cell_pair)
template<>
void addUnitState (Creature *obj, CellPair const &cell_pair)
template<class T >
void LoadHelper (CellGuidSet const &guid_set, CellPair &cell, GridRefManager< T > &, uint32 &count, Map *map, GridType &grid)
void LoadHelper (CellCorpseSet const &cell_corpses, CellPair &cell, CorpseMapType &, uint32 &count, Map *map, GridType &grid)
Function Documentation
addUnitState() [1/3]
template<> void addUnitState (Creature * obj, CellPair const & cell_pair)
Definition at line 107 of file ObjectGridLoader.cpp.
References WorldObject::SetCurrentCell().
addUnitState() [2/3]
template<> void addUnitState (GameObject * obj, CellPair const & cell_pair)
Definition at line 100 of file ObjectGridLoader.cpp.
References WorldObject::SetCurrentCell().
addUnitState() [3/3]
template<class T > void addUnitState (T * , CellPair const &)
Definition at line 96 of file ObjectGridLoader.cpp.
Referenced by LoadHelper(), and MotionMaster::PauseWaypoints().
LoadHelper() [1/2]
void LoadHelper (CellCorpseSet const & cell_corpses, CellPair & cell, CorpseMapType & , uint32 & count, Map * map, GridType & grid)
Definition at line 156 of file ObjectGridLoader.cpp.
References Map::AddToActive(), Corpse::AddToWorld(), addUnitState(), Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddWorldObject(), Map::GetInstanceId(), HIGHGUID_PLAYER, WorldObject::isActiveObject(), WorldObject::SetMap(), and sObjectAccessor.
LoadHelper() [2/2]
template<class T > void LoadHelper (CellGuidSet const & guid_set, CellPair & cell, GridRefManager< T > & , uint32 & count, Map * map, GridType & grid)
Definition at line 115 of file ObjectGridLoader.cpp.
References Grid< ACTIVE_OBJECT, WORLD_OBJECT_TYPES, GRID_OBJECT_TYPES >::AddGridObject(), addUnitState(), GameObject::CreateGameObject(), GameObjectData::id, Map::IsBattleGroundOrArena(), MANGOS_ASSERT, BattleGround::OnObjectDBLoad(), and sObjectMgr.
Referenced by ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().