CMaNGOS_WoTLK: ObjectMgr.h File Reference
ObjectMgr.h File Reference
#include "Common.h"
#include "Entities/Object.h"
#include "Entities/Bag.h"
#include "Entities/Creature.h"
#include "Entities/Player.h"
#include "Entities/GameObject.h"
#include "Quests/QuestDef.h"
#include "Entities/ItemPrototype.h"
#include "Entities/NPCHandler.h"
#include "Database/DatabaseEnv.h"
#include "Maps/Map.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Globals/ObjectAccessor.h"
#include "Entities/ObjectGuid.h"
#include "Globals/Conditions.h"
#include "Maps/SpawnGroupDefines.h"
#include "Entities/Vehicle.h"
#include <map>
#include <climits>
#include <memory>
#include <tuple>
Data Structures
struct GameTele
struct SpellClickInfo
struct AreaTrigger
struct AccessRequirement
struct BroadcastText
struct CellObjectGuids
struct MangosStringLocale
class FindCreatureData
class FindGOData
struct PetLevelInfo
struct MailLevelReward
struct RepRewardRate
struct ReputationOnKillEntry
struct RepSpilloverTemplate
struct PointOfInterest
struct GossipMenuItems
struct GossipMenus
struct QuestPOIPoint
struct QuestPOI
struct DungeonEncounter
struct TaxiShortcutData
struct QuestgiverGreeting
struct QuestgiverGreetingLocale
struct TrainerGreeting
struct TrainerGreetingLocale
struct LanguageDesc
class IdGenerator< T >
struct CreatureImmunity
struct WorldStateName
class ObjectMgr
Macros
#define MIN_MANGOS_STRING_ID 1
#define MAX_MANGOS_STRING_ID 2000000000
#define MAX_PLAYER_NAME 12
#define MAX_INTERNAL_PLAYER_NAME 15
#define MAX_PET_NAME 12
#define MAX_CHARTER_NAME 24
#define sObjectMgr MaNGOS::Singleton<ObjectMgr>::Instance()
Typedefs
typedef std::unordered_map< uint32, GameTele > GameTeleMap
typedef std::multimap< uint32, SpellClickInfo > SpellClickInfoMap
typedef std::pair< SpellClickInfoMap::const_iterator, SpellClickInfoMap::const_iterator > SpellClickInfoMapBounds
typedef std::map< uint32, BroadcastText > BroadcastTextMap
typedef std::map< uint32, uint32 > CellCorpseSet
typedef std::unordered_map< uint32, CellObjectGuids > CellObjectGuidsMap
typedef std::unordered_map< uint32, CellObjectGuidsMap > MapObjectGuids
typedef std::unordered_map< uint32, CreatureSpawnTemplate > CreatureSpawnTemplateMap
typedef std::unordered_map< uint32, CreatureData > CreatureDataMap
typedef CreatureDataMap::value_type CreatureDataPair
typedef std::unordered_map< uint32, GameObjectData > GameObjectDataMap
typedef GameObjectDataMap::value_type GameObjectDataPair
typedef std::unordered_map< uint32, CreatureLocale > CreatureLocaleMap
typedef std::unordered_map< uint32, GameObjectLocale > GameObjectLocaleMap
typedef std::unordered_map< uint32, ItemLocale > ItemLocaleMap
typedef std::unordered_map< uint32, QuestLocale > QuestLocaleMap
typedef std::unordered_map< uint32, NpcTextLocale > NpcTextLocaleMap
typedef std::unordered_map< uint32, PageTextLocale > PageTextLocaleMap
typedef std::unordered_map< int32, MangosStringLocale > MangosStringLocaleMap
typedef std::unordered_map< uint32, GossipMenuItemsLocale > GossipMenuItemsLocaleMap
typedef std::unordered_map< uint32, PointOfInterestLocale > PointOfInterestLocaleMap
typedef std::unordered_map< uint32, uint32 > ItemConvertMap
typedef std::multimap< int32, uint32 > ExclusiveQuestGroupsMap
typedef std::multimap< uint32, ItemRequiredTarget > ItemRequiredTargetMap
typedef std::multimap< uint32, uint32 > QuestRelationsMap
typedef std::pair< ExclusiveQuestGroupsMap::const_iterator, ExclusiveQuestGroupsMap::const_iterator > ExclusiveQuestGroupsMapBounds
typedef std::pair< ItemRequiredTargetMap::const_iterator, ItemRequiredTargetMap::const_iterator > ItemRequiredTargetMapBounds
typedef std::pair< QuestRelationsMap::const_iterator, QuestRelationsMap::const_iterator > QuestRelationsMapBounds
typedef std::list< MailLevelReward > MailLevelRewardList
typedef std::unordered_map< uint8, MailLevelRewardList > MailLevelRewardMap
typedef std::multimap< uint32, GossipMenus > GossipMenusMap
typedef std::pair< GossipMenusMap::const_iterator, GossipMenusMap::const_iterator > GossipMenusMapBounds
typedef std::multimap< uint32, GossipMenuItems > GossipMenuItemsMap
typedef std::pair< GossipMenuItemsMap::const_iterator, GossipMenuItemsMap::const_iterator > GossipMenuItemsMapBounds
typedef std::vector< QuestPOI > QuestPOIVector
typedef std::unordered_map< uint32, QuestPOIVector > QuestPOIMap
typedef std::multimap< uint32, DungeonEncounter > DungeonEncounterMap
typedef std::pair< DungeonEncounterMap::const_iterator, DungeonEncounterMap::const_iterator > DungeonEncounterMapBounds
typedef std::unordered_multimap< uint32, TaxiShortcutData > TaxiShortcutMap
typedef std::map< uint32, QuestgiverGreeting > QuestgiverGreetingMap
typedef std::map< uint32, QuestgiverGreetingLocale > QuestgiverGreetingLocaleMap
typedef std::map< uint32, TrainerGreeting > TrainerGreetingMap
typedef std::map< uint32, TrainerGreetingLocale > TrainerGreetingLocaleMap
typedef std::unordered_map< uint32, uint32 > CacheNpcTextIdMap
typedef std::unordered_map< uint32, VendorItemData > CacheVendorItemMap
typedef std::unordered_map< uint32, TrainerSpellData > CacheTrainerSpellMap
typedef std::vector< CreatureImmunity > CreatureImmunityVector
typedef std::map< uint32, CreatureImmunityVector > CreatureImmunitySetMap
typedef std::map< uint32, CreatureImmunitySetMap > CreatureImmunityContainer
Enumerations
enum { QUESTGIVER_CREATURE = 0 , QUESTGIVER_GAMEOBJECT = 1 , QUESTGIVER_TYPE_MAX = 2 }
enum SkillRangeType {
SKILL_RANGE_LANGUAGE , SKILL_RANGE_LEVEL , SKILL_RANGE_MONO , SKILL_RANGE_RANK ,
SKILL_RANGE_NONE
}
Functions
SkillRangeType GetSkillRangeType (SkillLineEntry const *pSkill, bool racial)
bool normalizePlayerName (std::string &name, size_t max_len=MAX_INTERNAL_PLAYER_NAME)
LanguageDesc const * GetLanguageDescByID (uint32 lang)
bool DoDisplayText (WorldObject *source, int32 entry, Unit const *target=nullptr, uint32 chatTypeOverride=0)
generic text function
bool LoadMangosStrings (DatabaseType &db, char const *table, int32 start_value=-1000000, int32 end_value=std::numeric_limits< int32 >::min(), bool extra_content=false)
CreatureInfo const * GetCreatureTemplateStore (uint32 entry)
Quest const * GetQuestTemplateStore (uint32 entry)
MangosStringLocale const * GetMangosStringData (int32 entry)
Variables
LanguageDesc lang_description [LANGUAGES_COUNT]
Macro Definition Documentation
MAX_CHARTER_NAME
#define MAX_CHARTER_NAME 24
Definition at line 455 of file ObjectMgr.h.
MAX_INTERNAL_PLAYER_NAME
#define MAX_INTERNAL_PLAYER_NAME 15
Definition at line 453 of file ObjectMgr.h.
MAX_MANGOS_STRING_ID
#define MAX_MANGOS_STRING_ID 2000000000
Definition at line 180 of file ObjectMgr.h.
MAX_PET_NAME
#define MAX_PET_NAME 12
Definition at line 454 of file ObjectMgr.h.
MAX_PLAYER_NAME
#define MAX_PLAYER_NAME 12
Definition at line 452 of file ObjectMgr.h.
MIN_MANGOS_STRING_ID
#define MIN_MANGOS_STRING_ID 1
Definition at line 179 of file ObjectMgr.h.
sObjectMgr
#define sObjectMgr MaNGOS::Singleton<ObjectMgr>::Instance()
Definition at line 1464 of file ObjectMgr.h.
Typedef Documentation
BroadcastTextMap
typedef std::map<uint32, BroadcastText> BroadcastTextMap
Definition at line 166 of file ObjectMgr.h.
CacheNpcTextIdMap
typedef std::unordered_map<uint32, uint32> CacheNpcTextIdMap
Definition at line 436 of file ObjectMgr.h.
CacheTrainerSpellMap
typedef std::unordered_map<uint32, TrainerSpellData> CacheTrainerSpellMap
Definition at line 439 of file ObjectMgr.h.
CacheVendorItemMap
typedef std::unordered_map<uint32, VendorItemData> CacheVendorItemMap
Definition at line 438 of file ObjectMgr.h.
CellCorpseSet
typedef std::map< uint32, uint32 > CellCorpseSet
Definition at line 168 of file ObjectMgr.h.
CellObjectGuidsMap
typedef std::unordered_map<uint32, CellObjectGuids> CellObjectGuidsMap
Definition at line 175 of file ObjectMgr.h.
CreatureDataMap
typedef std::unordered_map<uint32 , CreatureData> CreatureDataMap
Definition at line 195 of file ObjectMgr.h.
CreatureDataPair
typedef CreatureDataMap::value_type CreatureDataPair
Definition at line 196 of file ObjectMgr.h.
CreatureImmunityContainer
typedef std::map<uint32, CreatureImmunitySetMap> CreatureImmunityContainer
Definition at line 497 of file ObjectMgr.h.
CreatureImmunitySetMap
typedef std::map<uint32, CreatureImmunityVector> CreatureImmunitySetMap
Definition at line 496 of file ObjectMgr.h.
CreatureImmunityVector
typedef std::vector<CreatureImmunity> CreatureImmunityVector
Definition at line 495 of file ObjectMgr.h.
CreatureLocaleMap
typedef std::unordered_map<uint32, CreatureLocale> CreatureLocaleMap
Definition at line 241 of file ObjectMgr.h.
CreatureSpawnTemplateMap
typedef std::unordered_map<uint32, CreatureSpawnTemplate> CreatureSpawnTemplateMap
Definition at line 194 of file ObjectMgr.h.
DungeonEncounterMap
typedef std::multimap<uint32, DungeonEncounter> DungeonEncounterMap
Definition at line 389 of file ObjectMgr.h.
DungeonEncounterMapBounds
typedef std::pair<DungeonEncounterMap::const_iterator, DungeonEncounterMap::const_iterator> DungeonEncounterMapBounds
Definition at line 390 of file ObjectMgr.h.
ExclusiveQuestGroupsMap
typedef std::multimap<int32, uint32> ExclusiveQuestGroupsMap
Definition at line 251 of file ObjectMgr.h.
ExclusiveQuestGroupsMapBounds
typedef std::pair<ExclusiveQuestGroupsMap::const_iterator, ExclusiveQuestGroupsMap::const_iterator> ExclusiveQuestGroupsMapBounds
Definition at line 254 of file ObjectMgr.h.
GameObjectDataMap
typedef std::unordered_map<uint32, GameObjectData> GameObjectDataMap
Definition at line 218 of file ObjectMgr.h.
GameObjectDataPair
typedef GameObjectDataMap::value_type GameObjectDataPair
Definition at line 219 of file ObjectMgr.h.
GameObjectLocaleMap
typedef std::unordered_map<uint32, GameObjectLocale> GameObjectLocaleMap
Definition at line 242 of file ObjectMgr.h.
GameTeleMap
typedef std::unordered_map<uint32, GameTele > GameTeleMap
Definition at line 68 of file ObjectMgr.h.
GossipMenuItemsLocaleMap
typedef std::unordered_map<uint32, GossipMenuItemsLocale> GossipMenuItemsLocaleMap
Definition at line 248 of file ObjectMgr.h.
GossipMenuItemsMap
typedef std::multimap<uint32, GossipMenuItems> GossipMenuItemsMap
Definition at line 349 of file ObjectMgr.h.
GossipMenuItemsMapBounds
typedef std::pair<GossipMenuItemsMap::const_iterator, GossipMenuItemsMap::const_iterator> GossipMenuItemsMapBounds
Definition at line 350 of file ObjectMgr.h.
GossipMenusMap
typedef std::multimap<uint32, GossipMenus> GossipMenusMap
Definition at line 347 of file ObjectMgr.h.
GossipMenusMapBounds
typedef std::pair<GossipMenusMap::const_iterator, GossipMenusMap::const_iterator> GossipMenusMapBounds
Definition at line 348 of file ObjectMgr.h.
ItemConvertMap
typedef std::unordered_map<uint32, uint32> ItemConvertMap
Definition at line 250 of file ObjectMgr.h.
ItemLocaleMap
typedef std::unordered_map<uint32, ItemLocale> ItemLocaleMap
Definition at line 243 of file ObjectMgr.h.
ItemRequiredTargetMap
typedef std::multimap<uint32, ItemRequiredTarget> ItemRequiredTargetMap
Definition at line 252 of file ObjectMgr.h.
ItemRequiredTargetMapBounds
typedef std::pair<ItemRequiredTargetMap::const_iterator, ItemRequiredTargetMap::const_iterator> ItemRequiredTargetMapBounds
Definition at line 255 of file ObjectMgr.h.
MailLevelRewardList
typedef std::list<MailLevelReward> MailLevelRewardList
Definition at line 278 of file ObjectMgr.h.
MailLevelRewardMap
typedef std::unordered_map<uint8, MailLevelRewardList> MailLevelRewardMap
Definition at line 279 of file ObjectMgr.h.
MangosStringLocaleMap
typedef std::unordered_map<int32, MangosStringLocale> MangosStringLocaleMap
Definition at line 247 of file ObjectMgr.h.
MapObjectGuids
typedef std::unordered_map<uint32, CellObjectGuidsMap> MapObjectGuids
Definition at line 176 of file ObjectMgr.h.
NpcTextLocaleMap
typedef std::unordered_map<uint32, NpcTextLocale> NpcTextLocaleMap
Definition at line 245 of file ObjectMgr.h.
PageTextLocaleMap
typedef std::unordered_map<uint32, PageTextLocale> PageTextLocaleMap
Definition at line 246 of file ObjectMgr.h.
PointOfInterestLocaleMap
typedef std::unordered_map<uint32, PointOfInterestLocale> PointOfInterestLocaleMap
Definition at line 249 of file ObjectMgr.h.
QuestgiverGreetingLocaleMap
typedef std::map<uint32, QuestgiverGreetingLocale> QuestgiverGreetingLocaleMap
Definition at line 413 of file ObjectMgr.h.
QuestgiverGreetingMap
typedef std::map<uint32, QuestgiverGreeting> QuestgiverGreetingMap
Definition at line 412 of file ObjectMgr.h.
QuestLocaleMap
typedef std::unordered_map<uint32, QuestLocale> QuestLocaleMap
Definition at line 244 of file ObjectMgr.h.
QuestPOIMap
typedef std::unordered_map<uint32, QuestPOIVector> QuestPOIMap
Definition at line 377 of file ObjectMgr.h.
QuestPOIVector
typedef std::vector<QuestPOI> QuestPOIVector
Definition at line 376 of file ObjectMgr.h.
QuestRelationsMap
typedef std::multimap<uint32, uint32> QuestRelationsMap
Definition at line 253 of file ObjectMgr.h.
QuestRelationsMapBounds
typedef std::pair<QuestRelationsMap::const_iterator, QuestRelationsMap::const_iterator> QuestRelationsMapBounds
Definition at line 256 of file ObjectMgr.h.
SpellClickInfoMap
typedef std::multimap<uint32 , SpellClickInfo> SpellClickInfoMap
Definition at line 83 of file ObjectMgr.h.
SpellClickInfoMapBounds
typedef std::pair<SpellClickInfoMap::const_iterator, SpellClickInfoMap::const_iterator> SpellClickInfoMapBounds
Definition at line 84 of file ObjectMgr.h.
TaxiShortcutMap
typedef std::unordered_multimap<uint32 , TaxiShortcutData> TaxiShortcutMap
Definition at line 398 of file ObjectMgr.h.
TrainerGreetingLocaleMap
typedef std::map<uint32, TrainerGreetingLocale> TrainerGreetingLocaleMap
Definition at line 433 of file ObjectMgr.h.
TrainerGreetingMap
typedef std::map<uint32, TrainerGreeting> TrainerGreetingMap
Definition at line 432 of file ObjectMgr.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUESTGIVER_CREATURE
QUESTGIVER_GAMEOBJECT
QUESTGIVER_TYPE_MAX
Definition at line 415 of file ObjectMgr.h.
SkillRangeType
enum SkillRangeType
Enumerator
SKILL_RANGE_LANGUAGE
SKILL_RANGE_LEVEL
SKILL_RANGE_MONO
SKILL_RANGE_RANK
SKILL_RANGE_NONE
Definition at line 441 of file ObjectMgr.h.
Function Documentation
DoDisplayText()
bool DoDisplayText (WorldObject * source, int32 entry, Unit const * target = nullptr, uint32 chatTypeOverride = 0)
generic text function
Definition at line 10706 of file ObjectMgr.cpp.
References _DoStringError(), CHAT_TYPE_BOSS_WHISPER, CHAT_TYPE_PARTY, CHAT_TYPE_WHISPER, CHAT_TYPE_ZONE_EMOTE, CHAT_TYPE_ZONE_YELL, DEFAULT_LOCALE, GENDER_FEMALE, GENDER_NONE, Object::GetGuidStr(), Object::GetTypeId(), WorldObject::GetZoneId(), Object::IsUnit(), LANG_UNIVERSAL, WorldObject::MonsterText(), PLAY_TARGET, PLAY_ZONE, WorldObject::PlayDirectSound(), sObjectMgr, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by AreaTrigger_at_shadowforge_bridge(), DoBroadcastText(), DoScriptText(), ScriptAction::ExecuteDbscriptCommand(), and CreatureEventAI::ProcessAction().
GetCreatureTemplateStore()
CreatureInfo const* GetCreatureTemplateStore (uint32 entry)
Definition at line 10591 of file ObjectMgr.cpp.
References SQLStorage::LookupEntry(), and sCreatureStorage.
Referenced by DoOrSimulateScriptTextForMap(), EffectDummyCreature_npc_kitten(), boss_tharonjaAI::JustReachedHome(), SystemMgr::LoadScriptWaypoints(), npc_air_force_botsAI::npc_air_force_botsAI(), GraspOfTheEmeraldDream::OnEffectExecute(), npc_clintar_dw_spiritAI::Reset(), and boss_tharonjaAI::UpdateAI().
GetLanguageDescByID()
LanguageDesc const* GetLanguageDescByID (uint32 lang)
Definition at line 108 of file ObjectMgr.cpp.
References lang_description.
Referenced by WorldSession::HandleMessagechatOpcode(), and ObjectMgr::LoadMangosStrings().
GetMangosStringData()
MangosStringLocale const* GetMangosStringData (int32 entry)
Definition at line 10601 of file ObjectMgr.cpp.
References sObjectMgr.
Referenced by DoOrSimulateScriptTextForMap().
GetQuestTemplateStore()
Quest const* GetQuestTemplateStore (uint32 entry)
Definition at line 10596 of file ObjectMgr.cpp.
References sObjectMgr.
Referenced by GossipSelect_npc_saeed(), npc_taelan_fordringAI::ReceiveAIEvent(), npc_kineloryAI::ReceiveAIEvent(), npc_kernobeeAI::ReceiveAIEvent(), npc_corporal_keeshan_escortAI::ReceiveAIEvent(), npc_dorius_stonetenderAI::ReceiveAIEvent(), npc_anchorite_truuenAI::ReceiveAIEvent(), npc_tapoke_slim_jahnAI::ReceiveAIEvent(), npc_stinky_ignatzAI::ReceiveAIEvent(), npc_captured_arkonarinAI::ReceiveAIEvent(), npc_areiAI::ReceiveAIEvent(), npc_shay_leafrunnerAI::ReceiveAIEvent(), npc_bonker_togglevoltAI::ReceiveAIEvent(), npc_mootoo_the_youngerAI::ReceiveAIEvent(), npc_proudhoofAI::ReceiveAIEvent(), npc_harrison_jonesAI::ReceiveAIEvent(), npc_apothecary_hanesAI::ReceiveAIEvent(), npc_squad_leaderAI::ReceiveAIEvent(), npc_father_kamarosAI::ReceiveAIEvent(), npc_injured_minerAI::ReceiveAIEvent(), npc_shaheenAI::ReceiveAIEvent(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_drijyaAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_fhwoorAI::ReceiveAIEvent(), npc_demolitionist_legosoAI::ReceiveAIEvent(), and npc_emilyAI::ReceiveAIEvent().
GetSkillRangeType()
SkillRangeType GetSkillRangeType (SkillLineEntry const * pSkill, bool racial)
Definition at line 9330 of file ObjectMgr.cpp.
References SkillLineEntry::categoryId, SkillLineEntry::id, IsProfessionOrRidingSkill(), SKILL_CATEGORY_ARMOR, SKILL_CATEGORY_ATTRIBUTES, SKILL_CATEGORY_CLASS, SKILL_CATEGORY_GENERIC, SKILL_CATEGORY_LANGUAGES, SKILL_CATEGORY_PROFESSION, SKILL_CATEGORY_SECONDARY, SKILL_CATEGORY_WEAPON, SKILL_FIST_WEAPONS, SKILL_LOCKPICKING, SKILL_RANGE_LANGUAGE, SKILL_RANGE_LEVEL, SKILL_RANGE_MONO, SKILL_RANGE_NONE, and SKILL_RANGE_RANK.
Referenced by Player::_LoadSkills(), Player::LearnDefaultSkills(), Player::UpdateSkillsForLevel(), and Player::UpdateSpellTrainedSkills().
LoadMangosStrings()
bool LoadMangosStrings (DatabaseType & db, char const * table, int32 start_value = -1000000, int32 end_value = std::numeric_limits< int32 >::min(), bool extra_content = false)
Definition at line 10477 of file ObjectMgr.cpp.
References sObjectMgr.
Referenced by SystemMgr::LoadScriptGossipTexts(), SystemMgr::LoadScriptTexts(), and SystemMgr::LoadScriptTextsCustom().
normalizePlayerName()
bool normalizePlayerName (std::string & name, size_t max_len = MAX_INTERNAL_PLAYER_NAME)
Definition at line 65 of file ObjectMgr.cpp.
References Utf8toWStr(), wcharToLower(), wcharToUpper(), and WStrToUtf8().
Referenced by ChatHandler::ExtractGuidFromLink(), ChatHandler::ExtractLocationFromLink(), ChatHandler::ExtractPlayerNameFromLink(), PlayerNameMapHolder::Find(), ChatHandler::GetDeletedCharacterInfoList(), WorldSession::HandleAddFriendOpcode(), WorldSession::HandleAddIgnoreOpcode(), WorldSession::HandleArenaTeamInviteOpcode(), WorldSession::HandleArenaTeamLeaderOpcode(), WorldSession::HandleArenaTeamRemoveOpcode(), ChatHandler::HandleBanHelper(), WorldSession::HandleChannelBanOpcode(), WorldSession::HandleChannelInviteOpcode(), WorldSession::HandleChannelKickOpcode(), WorldSession::HandleChannelModeratorOpcode(), WorldSession::HandleChannelMuteOpcode(), WorldSession::HandleChannelSetOwnerOpcode(), WorldSession::HandleChannelUnbanOpcode(), WorldSession::HandleChannelUnmoderatorOpcode(), WorldSession::HandleChannelUnmuteOpcode(), ChatHandler::HandleCharacterDeletedRestoreCommand(), WorldSession::HandleCharCreateOpcode(), WorldSession::HandleCharCustomizeOpcode(), WorldSession::HandleCharRenameOpcode(), ChatHandler::HandleDebugOverflowCommand(), WorldSession::HandleGroupInviteOpcode(), WorldSession::HandleGroupUninviteOpcode(), WorldSession::HandleGuildDemoteOpcode(), WorldSession::HandleGuildInviteOpcode(), WorldSession::HandleGuildLeaderOpcode(), WorldSession::HandleGuildPromoteOpcode(), WorldSession::HandleGuildRemoveOpcode(), WorldSession::HandleGuildSetOfficerNoteOpcode(), WorldSession::HandleGuildSetPublicNoteOpcode(), WorldSession::HandleMessagechatOpcode(), ChatHandler::HandlePDumpLoadCommand(), WorldSession::HandleSendMail(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), ChatHandler::HandleUnBanHelper(), WorldSession::HandleWhoisOpcode(), and PlayerDumpReader::LoadDump().
Variable Documentation
lang_description
LanguageDesc lang_description[LANGUAGES_COUNT] extern
Definition at line 85 of file ObjectMgr.cpp.
Referenced by GetLanguageDescByID(), and ChatHandler::HandleLearnAllLangCommand().