CMaNGOS_WoTLK: ObjectPosSelector.h File Reference
ObjectPosSelector.h File Reference
#include <Common.h>
#include <map>
Data Structures
struct ObjectPosSelector
struct ObjectPosSelector::OccupiedArea
Enumerations
enum UsedAreaSide { USED_POS_PLUS , USED_POS_MINUS }
Functions
UsedAreaSide operator~ (UsedAreaSide side)
float SignOf (UsedAreaSide side)
Enumeration Type Documentation
UsedAreaSide
enum UsedAreaSide
Enumerator
USED_POS_PLUS
USED_POS_MINUS
Definition at line 28 of file ObjectPosSelector.h.
Function Documentation
operator~()
UsedAreaSide operator~ (UsedAreaSide side) inline
Definition at line 30 of file ObjectPosSelector.h.
References USED_POS_MINUS, and USED_POS_PLUS.
SignOf()
float SignOf (UsedAreaSide side) inline
Definition at line 35 of file ObjectPosSelector.h.
References USED_POS_PLUS.
Referenced by ObjectPosSelector::CheckAngle(), ObjectPosSelector::NextSideAngle(), and ObjectPosSelector::NextUsedAngle().