CMaNGOS_WoTLK: old_hillsbradScripts.cpp File Reference
old_hillsbradScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "old_hillsbrad.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_thrall_old_hillsbradAI
struct npc_tarethaAI
struct npc_bartolo_ginsetti
Enumerations
enum { GOSSIP_ITEM_NEED_BOMBS = -3560001 , TEXT_ID_DEFAULT = 9778 , TEXT_ID_GOT_ITEM = 9515 , ITEM_ENTRY_BOMBS = 25853 }
enum {
SAY_TH_START_EVENT_PART_1 = -1560023 , SAY_ARMORER_CALL_GUARDS = -1560003 , SAY_TH_KILL_ARMORER = -1560050 , SAY_TH_ARMORY_1 = -1560024 ,
SAY_TH_ARMORY_2 = -1560005 , SAY_TH_SKARLOC_MEET = -1560025 , SAY_SKARLOC_ENTER = -1560000 , SAY_TH_SKARLOC_TAUNT = -1560026 ,
SAY_TH_START_EVENT_PART2 = -1560027 , SAY_TH_MOUNTS_UP = -1560028 , EMOTE_TH_STARTLE_HORSE = -1560006 , SAY_LOOKOUT_BARN_1 = -1560007 ,
SAY_PROTECTOR_BARN_2 = -1560008 , EMOTE_TH_CALM_HORSE = -1560009 , SAY_PROTECTOR_BARN_3 = -1560010 , SAY_TH_HEAD_TOWN = -1560011 ,
SAY_TH_CHURCH_ENTER = -1560012 , SAY_LOOKOUT_CHURCH = -1560016 , SAY_TH_CHURCH_END = -1560029 , SAY_LOOKOUT_INN = -1560017 ,
SAY_TA_ESCAPED = -1560049 , SAY_TH_MEET_TARETHA = -1560030 , SAY_EPOCH_ENTER1 = -1560013 , SAY_TH_EPOCH_WONDER = -1560031 ,
SAY_EPOCH_ENTER2 = -1560014 , SAY_TH_EPOCH_KILL_TARETHA = -1560032 , SAY_EPOCH_ENTER3 = -1560015 , SAY_INFINITE_DRAGON_AGGRO_1 = -1560004 ,
SAY_INFINITE_DRAGON_AGGRO_2 = -1560018 , SAY_INFINITE_DRAGON_AGGRO_3 = -1560019 , SAY_INFINITE_DRAGON_AGGRO_4 = -1560020 , SAY_TH_RANDOM_LOW_HP1 = -1560034 ,
SAY_TH_RANDOM_LOW_HP2 = -1560035 , SAY_TH_RANDOM_DIE1 = -1560036 , SAY_TH_RANDOM_DIE2 = -1560037 , SAY_TH_RANDOM_AGGRO1 = -1560038 ,
SAY_TH_RANDOM_AGGRO2 = -1560039 , SAY_TH_RANDOM_AGGRO3 = -1560040 , SAY_TH_RANDOM_AGGRO4 = -1560041 , SAY_TH_RANDOM_KILL1 = -1560042 ,
SAY_TH_RANDOM_KILL2 = -1560043 , SAY_TH_RANDOM_KILL3 = -1560044 , SAY_TH_LEAVE_COMBAT1 = -1560045 , SAY_TH_LEAVE_COMBAT2 = -1560046 ,
SAY_TH_LEAVE_COMBAT3 = -1560047 , SAY_ERONZION_RESET_THRALL = -1560001 , SAY_ERONZION_RESET_LAST = -1560002 , GOSSIP_ITEM_START = -3560000 ,
TEXT_ID_START = 9568 , GOSSIP_ITEM_SKARLOC_1 = -3560002 , TEXT_ID_SKARLOC_1 = 9578 , GOSSIP_ITEM_SKARLOC_2 = -3560003 ,
TEXT_ID_SKARLOC_2 = 9579 , GOSSIP_ITEM_SKARLOC_3 = -3560007 , TEXT_ID_SKARLOC_3 = 9580 , GOSSIP_ITEM_TARREN_1 = -3560004 ,
TEXT_ID_TARREN = 9597 , TEXT_ID_INN = 9614 , SPELL_KNOCKOUT_ARMORER = 32890 , SPELL_STRIKE = 14516 ,
SPELL_SHIELD_BLOCK = 12169 , SPELL_SHADOW_SPIKE = 33125 , SPELL_TRANSFORM = 33133 , SPELL_SUMMON_EROZION_IMAGE = 33954 ,
SPELL_SPAWN_EROZION_IMAGE = 33955 , EQUIP_ID_WEAPON = 927 , EQUIP_ID_SHIELD = 1961 , MODEL_THRALL_UNEQUIPPED = 17292 ,
MODEL_THRALL_EQUIPPED = 18165 , MODEL_SKARLOC_MOUNT = 8469 , EMOTE_YOUNG_BLANCHY_RILED = 377 , EMOTE_THRALL_NO = 274 ,
NPC_IMAGE_OF_ERONZION = 19438 , NPC_SKARLOC_MOUNT = 18798 , NPC_THRALL_QUEST_TRIGGER = 20156 , NPC_RIFLE = 17820 ,
NPC_WARDEN = 17833 , NPC_VETERAN = 17860 , NPC_MAGE = 18934 , NPC_SENTRY = 17819 ,
NPC_CHURCH_GUARDSMAN = 23176 , NPC_CHURCH_PROTECTOR = 23180 , NPC_CHURCH_LOOKOUT = 23178 , NPC_INFINITE_DEFILER = 18171 ,
NPC_INFINITE_SABOTEOR = 18172 , NPC_INFINITE_SLAYER = 18170
}
enum {
SAY_TA_FREE = -1560048 , SAY_TR_GLAD_SAFE = -1560054 , SAY_TA_NEVER_MET = -1560055 , SAY_TR_THEN_WHO = -1560056 ,
SAY_PRE_WIPE = -1560057 , SAY_WIPE_MEMORY = -1560051 , SAY_ABOUT_TARETHA = -1560052 , SAY_TH_EVENT_COMPLETE = -1560033 ,
SAY_TA_FAREWELL = -1560053 , SAY_AFTER_WIPE = -1560058 , GOSSIP_ITEM_EPOCH_1 = -3560005 , TEXT_ID_EPOCH_1 = 9610 ,
GOSSIP_ITEM_EPOCH_2 = -3560006 , TEXT_ID_EPOCH_2 = 9613 , SPELL_TELEPORT = 7791 , SPELL_MEMORY_WIPE = 33336 ,
SPELL_MEMORY_WP_RESUME = 33337 , SPELL_SHADOW_PRISON = 33071
}
enum { BARTOLO_SAY_1 = 18137 , BARTOLO_SAY_2 = 18138 }
Functions
bool GossipHello_npc_erozion (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_erozion (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_thrall_old_hillsbrad (Creature *pCreature)
bool GossipHello_npc_thrall_old_hillsbrad (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_thrall_old_hillsbrad (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_taretha (Creature *pCreature)
bool GossipHello_npc_taretha (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_taretha (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool AreaTrigger_at_bartolo_ginsetti (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_beggar (Player *player, AreaTriggerEntry const *)
void AddSC_old_hillsbrad ()
Variables
static const DialogueEntry aThrallDialogue []
static const DialogueEntry aTarethaDialogue []
std::vector< uint32 > beggarTexts = { 18148, 18149, 18150, 18151, 18152, 18153, 18154 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_NEED_BOMBS
TEXT_ID_DEFAULT
TEXT_ID_GOT_ITEM
ITEM_ENTRY_BOMBS
Definition at line 38 of file old_hillsbradScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_TH_START_EVENT_PART_1
SAY_ARMORER_CALL_GUARDS
SAY_TH_KILL_ARMORER
SAY_TH_ARMORY_1
SAY_TH_ARMORY_2
SAY_TH_SKARLOC_MEET
SAY_SKARLOC_ENTER
SAY_TH_SKARLOC_TAUNT
SAY_TH_START_EVENT_PART2
SAY_TH_MOUNTS_UP
EMOTE_TH_STARTLE_HORSE
SAY_LOOKOUT_BARN_1
SAY_PROTECTOR_BARN_2
EMOTE_TH_CALM_HORSE
SAY_PROTECTOR_BARN_3
SAY_TH_HEAD_TOWN
SAY_TH_CHURCH_ENTER
SAY_LOOKOUT_CHURCH
SAY_TH_CHURCH_END
SAY_LOOKOUT_INN
SAY_TA_ESCAPED
SAY_TH_MEET_TARETHA
SAY_EPOCH_ENTER1
SAY_TH_EPOCH_WONDER
SAY_EPOCH_ENTER2
SAY_TH_EPOCH_KILL_TARETHA
SAY_EPOCH_ENTER3
SAY_INFINITE_DRAGON_AGGRO_1
SAY_INFINITE_DRAGON_AGGRO_2
SAY_INFINITE_DRAGON_AGGRO_3
SAY_INFINITE_DRAGON_AGGRO_4
SAY_TH_RANDOM_LOW_HP1
SAY_TH_RANDOM_LOW_HP2
SAY_TH_RANDOM_DIE1
SAY_TH_RANDOM_DIE2
SAY_TH_RANDOM_AGGRO1
SAY_TH_RANDOM_AGGRO2
SAY_TH_RANDOM_AGGRO3
SAY_TH_RANDOM_AGGRO4
SAY_TH_RANDOM_KILL1
SAY_TH_RANDOM_KILL2
SAY_TH_RANDOM_KILL3
SAY_TH_LEAVE_COMBAT1
SAY_TH_LEAVE_COMBAT2
SAY_TH_LEAVE_COMBAT3
SAY_ERONZION_RESET_THRALL
SAY_ERONZION_RESET_LAST
GOSSIP_ITEM_START
TEXT_ID_START
GOSSIP_ITEM_SKARLOC_1
TEXT_ID_SKARLOC_1
GOSSIP_ITEM_SKARLOC_2
TEXT_ID_SKARLOC_2
GOSSIP_ITEM_SKARLOC_3
TEXT_ID_SKARLOC_3
GOSSIP_ITEM_TARREN_1
TEXT_ID_TARREN
TEXT_ID_INN
SPELL_KNOCKOUT_ARMORER
SPELL_STRIKE
SPELL_SHIELD_BLOCK
SPELL_SHADOW_SPIKE
SPELL_TRANSFORM
SPELL_SUMMON_EROZION_IMAGE
SPELL_SPAWN_EROZION_IMAGE
EQUIP_ID_WEAPON
EQUIP_ID_SHIELD
MODEL_THRALL_UNEQUIPPED
MODEL_THRALL_EQUIPPED
MODEL_SKARLOC_MOUNT
EMOTE_YOUNG_BLANCHY_RILED
EMOTE_THRALL_NO
NPC_IMAGE_OF_ERONZION
NPC_SKARLOC_MOUNT
NPC_THRALL_QUEST_TRIGGER
NPC_RIFLE
NPC_WARDEN
NPC_VETERAN
NPC_MAGE
NPC_SENTRY
NPC_CHURCH_GUARDSMAN
NPC_CHURCH_PROTECTOR
NPC_CHURCH_LOOKOUT
NPC_INFINITE_DEFILER
NPC_INFINITE_SABOTEOR
NPC_INFINITE_SLAYER
Definition at line 86 of file old_hillsbradScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_TA_FREE
SAY_TR_GLAD_SAFE
SAY_TA_NEVER_MET
SAY_TR_THEN_WHO
SAY_PRE_WIPE
SAY_WIPE_MEMORY
SAY_ABOUT_TARETHA
SAY_TH_EVENT_COMPLETE
SAY_TA_FAREWELL
SAY_AFTER_WIPE
GOSSIP_ITEM_EPOCH_1
TEXT_ID_EPOCH_1
GOSSIP_ITEM_EPOCH_2
TEXT_ID_EPOCH_2
SPELL_TELEPORT
SPELL_MEMORY_WIPE
SPELL_MEMORY_WP_RESUME
SPELL_SHADOW_PRISON
Definition at line 1099 of file old_hillsbradScripts.cpp.
anonymous enum
anonymous enum
Enumerator
BARTOLO_SAY_1
BARTOLO_SAY_2
Definition at line 1298 of file old_hillsbradScripts.cpp.
Function Documentation
AddSC_old_hillsbrad()
void AddSC_old_hillsbrad ()
Definition at line 1421 of file old_hillsbradScripts.cpp.
References AreaTrigger_at_bartolo_ginsetti(), AreaTrigger_at_beggar(), Script::GetAI, GetAI_npc_taretha(), GetAI_npc_thrall_old_hillsbrad(), GossipHello_npc_erozion(), GossipHello_npc_taretha(), GossipHello_npc_thrall_old_hillsbrad(), GossipSelect_npc_erozion(), GossipSelect_npc_taretha(), GossipSelect_npc_thrall_old_hillsbrad(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_bartolo_ginsetti()
bool AreaTrigger_at_bartolo_ginsetti (Player * player, AreaTriggerEntry const *)
Definition at line 1369 of file old_hillsbradScripts.cpp.
References WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), Player::IsGameMaster(), and NPC_BARTOLO.
Referenced by AddSC_old_hillsbrad().
AreaTrigger_at_beggar()
bool AreaTrigger_at_beggar (Player * player, AreaTriggerEntry const *)
Definition at line 1396 of file old_hillsbradScripts.cpp.
References beggarTexts, DoBroadcastText(), EMOTE_ONESHOT_BEG, GetClosestCreatureWithEntry(), Map::GetCurrentClockTime(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Unit::IsAlive(), Player::IsGameMaster(), instance_old_hillsbrad::m_beggarScriptTime, NPC_BEGGAR, and urand().
Referenced by AddSC_old_hillsbrad().
GetAI_npc_taretha()
UnitAI* GetAI_npc_taretha (Creature * pCreature)
Definition at line 1251 of file old_hillsbradScripts.cpp.
Referenced by AddSC_old_hillsbrad().
GetAI_npc_thrall_old_hillsbrad()
UnitAI* GetAI_npc_thrall_old_hillsbrad (Creature * pCreature)
Definition at line 981 of file old_hillsbradScripts.cpp.
Referenced by AddSC_old_hillsbrad().
GossipHello_npc_erozion()
bool GossipHello_npc_erozion (Player * pPlayer, Creature * pCreature)
Definition at line 47 of file old_hillsbradScripts.cpp.
References DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NEED_BOMBS, GOSSIP_SENDER_MAIN, Player::HasItemCount(), Unit::isQuestGiver(), ITEM_ENTRY_BOMBS, Player::PrepareQuestMenu(), TEXT_ID_DEFAULT, TYPE_BARREL_DIVERSION, and TYPE_EPOCH.
Referenced by AddSC_old_hillsbrad().
GossipHello_npc_taretha()
bool GossipHello_npc_taretha (Player * pPlayer, Creature * pCreature)
Definition at line 1256 of file old_hillsbradScripts.cpp.
References DONE, instance_old_hillsbrad::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_EPOCH_1, GOSSIP_SENDER_MAIN, TEXT_ID_EPOCH_1, TYPE_EPOCH, and TYPE_ESCORT_INN.
Referenced by AddSC_old_hillsbrad().
GossipHello_npc_thrall_old_hillsbrad()
bool GossipHello_npc_thrall_old_hillsbrad (Player * pPlayer, Creature * pCreature)
Definition at line 986 of file old_hillsbradScripts.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SKARLOC_1, GOSSIP_ITEM_START, GOSSIP_ITEM_TARREN_1, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), Player::SendPreparedQuest(), TEXT_ID_INN, TEXT_ID_SKARLOC_1, TEXT_ID_START, TEXT_ID_TARREN, TYPE_DRAKE, TYPE_ESCORT_BARN, TYPE_ESCORT_INN, and TYPE_SKARLOC.
Referenced by AddSC_old_hillsbrad().
GossipSelect_npc_erozion()
bool GossipSelect_npc_erozion (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 66 of file old_hillsbradScripts.cpp.
References Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, ITEM_ENTRY_BOMBS, Player::SendNewItem(), Player::StoreNewItemInInventorySlot(), and TEXT_ID_GOT_ITEM.
Referenced by AddSC_old_hillsbrad().
GossipSelect_npc_taretha()
bool GossipSelect_npc_taretha (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1269 of file old_hillsbradScripts.cpp.
References instance_old_hillsbrad::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_EPOCH_2, GOSSIP_SENDER_MAIN, IN_PROGRESS, NPC_THRALL, Object::RemoveFlag(), TEXT_ID_EPOCH_2, TYPE_THRALL_EVENT, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_old_hillsbrad().
GossipSelect_npc_thrall_old_hillsbrad()
bool GossipSelect_npc_thrall_old_hillsbrad (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 1021 of file old_hillsbradScripts.cpp.
References Creature::AI(), DoScriptText(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SKARLOC_2, GOSSIP_ITEM_SKARLOC_3, GOSSIP_SENDER_MAIN, IN_PROGRESS, SAY_TH_START_EVENT_PART2, SAY_TH_START_EVENT_PART_1, instance_old_hillsbrad::SetData(), TEXT_ID_SKARLOC_2, TEXT_ID_SKARLOC_3, TYPE_ESCORT_BARN, TYPE_ESCORT_INN, and TYPE_THRALL_EVENT.
Referenced by AddSC_old_hillsbrad().
Variable Documentation
aTarethaDialogue
const DialogueEntry aTarethaDialogue[] static
Initial value:
=
{
    {SAY_TA_FREE,           NPC_TARETHA,    4000},
    {SAY_TR_GLAD_SAFE,      NPC_THRALL,     9000},
    {SAY_TA_NEVER_MET,      NPC_TARETHA,    3000},
    {SAY_TR_THEN_WHO,       NPC_THRALL,     6000},
    {SPELL_MEMORY_WIPE,     0,              3000},
    {SAY_WIPE_MEMORY,       NPC_EROZION,    12000},
    {SAY_ABOUT_TARETHA,     NPC_EROZION,    6000},
    {SAY_TH_EVENT_COMPLETE, NPC_THRALL,     3000},
    {NPC_THRALL,            0,              2000},
    {SAY_TA_FAREWELL,       NPC_TARETHA,    3000},
    {NPC_TARETHA,           0,              0},
    {0, 0, 0},
}
Definition at line 1125 of file old_hillsbradScripts.cpp.
aThrallDialogue
const DialogueEntry aThrallDialogue[] static
Initial value:
=
{
    {SAY_LOOKOUT_BARN_1,    NPC_BARN_LOOKOUT,          5000},
    {SAY_PROTECTOR_BARN_2,  NPC_BARN_PROTECTOR,        3000},
    {NPC_YOUNG_BLANCHY,     0,                         4000},
    {EMOTE_TH_CALM_HORSE,   NPC_THRALL,                1000},
    {SAY_PROTECTOR_BARN_3,  NPC_BARN_PROTECTOR,         0},
    {NPC_EPOCH,             0,                         8000},
    {SAY_TH_EPOCH_WONDER,   NPC_THRALL,                4000},
    {SAY_EPOCH_ENTER2,      NPC_EPOCH,                 4000},
    {SAY_TH_EPOCH_KILL_TARETHA, NPC_THRALL,            2000},
    {NPC_THRALL,            0,                         0},
    {0, 0, 0},
}
Definition at line 218 of file old_hillsbradScripts.cpp.
beggarTexts
std::vector<uint32> beggarTexts = { 18148, 18149, 18150, 18151, 18152, 18153, 18154 }
Definition at line 1394 of file old_hillsbradScripts.cpp.
Referenced by AreaTrigger_at_beggar().