CMaNGOS_WoTLK: orgrimmar.cpp File Reference
orgrimmar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Enumerations
enum { GO_HEAD_OF_NEFARIAN_OG = 179881 , GO_HEAD_OF_ONYXIA_OG = 179556 , GOSSIP_HEAD_OG = 6024 }
Functions
bool GossipHello_npc_overlord_runthalak (Player *player, Creature *creature)
bool GossipHello_npc_high_overlord_saurfang (Player *player, Creature *creature)
void AddSC_orgrimmar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GO_HEAD_OF_NEFARIAN_OG
GO_HEAD_OF_ONYXIA_OG
GOSSIP_HEAD_OG
Definition at line 30 of file orgrimmar.cpp.
Function Documentation
AddSC_orgrimmar()
void AddSC_orgrimmar ()
Definition at line 62 of file orgrimmar.cpp.
References GossipHello_npc_high_overlord_saurfang(), GossipHello_npc_overlord_runthalak(), Script::Name, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_high_overlord_saurfang()
bool GossipHello_npc_high_overlord_saurfang (Player * player, Creature * creature)
Definition at line 50 of file orgrimmar.cpp.
References GetClosestGameObjectWithEntry(), Creature::GetCreatureInfo(), GO_HEAD_OF_ONYXIA_OG, GOSSIP_HEAD_OG, CreatureInfo::GossipMenuId, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_orgrimmar().
GossipHello_npc_overlord_runthalak()
bool GossipHello_npc_overlord_runthalak (Player * player, Creature * creature)
Definition at line 38 of file orgrimmar.cpp.
References GetClosestGameObjectWithEntry(), Creature::GetCreatureInfo(), GO_HEAD_OF_NEFARIAN_OG, GOSSIP_HEAD_OG, CreatureInfo::GossipMenuId, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_orgrimmar().