CMaNGOS_WoTLK: PetHandler.cpp File Reference
PetHandler.cpp File Reference
#include "Common.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "Globals/ObjectMgr.h"
#include "Spells/SpellMgr.h"
#include "Log.h"
#include "Server/Opcodes.h"
#include "Spells/Spell.h"
#include "AI/BaseAI/CreatureAI.h"
#include "Util/Util.h"
#include "Entities/Pet.h"
#include "Spells/SpellAuras.h"
#include "MotionGenerators/PathFinder.h"
Functions
bool CheckPathToTarget (Unit *pet, Unit *target)
void SendNoPathToOwner (Unit *pet)
Function Documentation
CheckPathToTarget()
bool CheckPathToTarget (Unit * pet, Unit * target)
Definition at line 33 of file PetHandler.cpp.
References Unit::AI(), PathFinder::calculate(), WorldObject::GetAngle(), UnitAI::GetAttackDistance(), Unit::GetCollisionHeight(), WorldObject::GetMap(), WorldObject::GetNearPoint(), Unit::GetObjectBoundingRadius(), PathFinder::getPath(), PathFinder::getPathType(), WorldObject::GetPhaseMask(), Map::IsInLineOfSight(), Unit::IsInWater(), and PATHFIND_NOPATH.
Referenced by WorldSession::HandlePetActionHelper().
SendNoPathToOwner()
void SendNoPathToOwner (Unit * pet)
Definition at line 58 of file PetHandler.cpp.
References FEEDBACK_NO_PATH, and Unit::SendPetActionFeedback().
Referenced by WorldSession::HandlePetActionHelper().