CMaNGOS_WoTLK: pit_of_saronScripts.cpp File Reference
pit_of_saronScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "pit_of_saron.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_collapsing_icicleAI
struct spell_necromantic_power
struct spell_strangulating_aura
struct spell_feigh_death_pos_aura
struct spell_slave_trigger_closest
struct spell_summon_undead
struct spell_jainas_call
struct spell_call_of_sylvanas
struct spell_aggro_nearest_slave
Enumerations
enum { SPELL_ICICLE = 69426 , SPELL_ICICLE_DUMMY = 69428 , SPELL_ICE_SHARDS_H = 70827 }
Functions
bool AreaTrigger_at_pit_of_saron (Player *pPlayer, AreaTriggerEntry const *pAt)
void AddSC_pit_of_saron ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_ICICLE
SPELL_ICICLE_DUMMY
SPELL_ICE_SHARDS_H
Definition at line 32 of file pit_of_saronScripts.cpp.
Function Documentation
AddSC_pit_of_saron()
void AddSC_pit_of_saron ()
Definition at line 315 of file pit_of_saronScripts.cpp.
References AreaTrigger_at_pit_of_saron(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_pit_of_saron()
bool AreaTrigger_at_pit_of_saron (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 90 of file pit_of_saronScripts.cpp.
References AREATRIGGER_ID_TUNNEL_END, AREATRIGGER_ID_TUNNEL_START, DONE, instance_pit_of_saron::GetData(), WorldObject::GetInstanceData(), AreaTriggerEntry::id, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), NOT_STARTED, instance_pit_of_saron::SetData(), TYPE_AMBUSH, TYPE_GARFROST, and TYPE_KRICK.
Referenced by AddSC_pit_of_saron().