CMaNGOS_WoTLK: pit_of_saron.cpp File Reference
pit_of_saron.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "pit_of_saron.h"
Enumerations
enum {
SAY_TYRANNUS_AMBUSH_1 = -1658047 , SAY_TYRANNUS_AMBUSH_2 = -1658048 , SAY_GAUNTLET = -1658049 , SPELL_ICICLE_SUMMON = 69424 ,
SPELL_ACHIEVEMENT_CHECK = 72845 , SAY_PREFIGHT_1 = -1658050 , SAY_PREFIGHT_2 = -1658052 , SPELL_EJECT_ALL_PASSENGERS = 50630
}
Functions
InstanceData * GetInstanceData_instance_pit_of_saron (Map *pMap)
void AddSC_instance_pit_of_saron ()
Variables
static const DialogueEntry aPoSDialogues []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_TYRANNUS_AMBUSH_1
SAY_TYRANNUS_AMBUSH_2
SAY_GAUNTLET
SPELL_ICICLE_SUMMON
SPELL_ACHIEVEMENT_CHECK
SAY_PREFIGHT_1
SAY_PREFIGHT_2
SPELL_EJECT_ALL_PASSENGERS
Definition at line 27 of file pit_of_saron.cpp.
Function Documentation
AddSC_instance_pit_of_saron()
void AddSC_instance_pit_of_saron ()
Definition at line 583 of file pit_of_saron.cpp.
References Script::GetInstanceData, GetInstanceData_instance_pit_of_saron(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_pit_of_saron()
InstanceData* GetInstanceData_instance_pit_of_saron (Map * pMap)
Definition at line 578 of file pit_of_saron.cpp.
Referenced by AddSC_instance_pit_of_saron().
Variable Documentation
aPoSDialogues
const DialogueEntry aPoSDialogues[] static
Initial value:
=
{
    {SAY_PREFIGHT_1,    NPC_TYRANNUS,   22000},
    {SAY_PREFIGHT_2,    NPC_TYRANNUS,   10000},
    {NPC_RIMEFANG,      0,              0},
    {0, 0, 0},
}
Definition at line 46 of file pit_of_saron.cpp.