CMaNGOS_WoTLK: Player.h File Reference
Player.h File Reference
#include "Common.h"
#include "Entities/ItemPrototype.h"
#include "Entities/Unit.h"
#include "Entities/Item.h"
#include "Database/DatabaseEnv.h"
#include "Quests/QuestDef.h"
#include "Groups/Group.h"
#include "Entities/Bag.h"
#include "Entities/Taxi.h"
#include "Server/WorldSession.h"
#include "Entities/Pet.h"
#include "Maps/MapReference.h"
#include "Util/Util.h"
#include "Achievements/AchievementMgr.h"
#include "Reputation/ReputationMgr.h"
#include "BattleGround/BattleGround.h"
#include "Globals/SharedDefines.h"
#include "Chat/Chat.h"
#include "Server/SQLStorages.h"
#include "Loot/LootMgr.h"
#include "Cinematics/CinematicMgr.h"
#include "LFG/LFG.h"
#include <functional>
#include <vector>
Data Structures
struct PlayerSpell
struct PlayerTalent
struct SpellCooldown
struct ActionButton
struct Glyph
struct PlayerCreateInfoItem
struct PlayerClassLevelInfo
struct PlayerClassInfo
struct PlayerLevelInfo
struct PlayerCreateInfoAction
struct PlayerCreateInfoSkill
struct PlayerInfo
struct PvPInfo
struct DuelInfo
struct Areas
struct RuneInfo
struct Runes
struct EnchantDuration
class MirrorTimer
struct SkillStatusData
struct EquipmentSet
struct ItemPosCount
struct InstancePlayerBind
class PlayerTaxi
struct BGData
Holder for BattleGround data.
struct TradeStatusInfo
class TradeData
class Player
struct Player::BgBattleGroundQueueID_Rec
Macros
#define PLAYER_MAX_SKILLS 127
#define PLAYER_MAX_DAILY_QUESTS 25
#define PLAYER_EXPLORED_ZONES_SIZE 128
#define PLAYER_NEW_INSTANCE_LIMIT_PER_HOUR 5
#define ACTION_BUTTON_ACTION(X) (uint32(X) & 0x00FFFFFF)
#define ACTION_BUTTON_TYPE(X) ((uint32(X) & 0xFF000000) >> 24)
#define MAX_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
#define MAX_ACTION_BUTTONS 144
#define MAX_RUNES 6
#define RUNE_COOLDOWN (2*5*IN_MILLISECONDS)
#define MAX_DRUNKEN 4
#define KNOWN_TITLES_SIZE 3
#define MAX_TITLE_INDEX (KNOWN_TITLES_SIZE*64)
#define MAX_QUEST_OFFSET 5
#define INVENTORY_SLOT_BAG_0 255
#define MAX_EQUIPMENT_SET_INDEX 10
#define MAX_PLAYED_TIME_INDEX 2
#define MAX_PLAYER_SUMMON_DELAY (2*MINUTE)
#define MAX_MONEY_AMOUNT (0x7FFFFFFF-1)
Typedefs
typedef std::deque< Mail * > PlayerMails
typedef std::unordered_map< uint32, PlayerSpell > PlayerSpellMap
typedef std::unordered_map< uint32, PlayerTalent > PlayerTalentMap
typedef std::map< uint32, SpellCooldown > SpellCooldowns
typedef std::map< uint8, ActionButton > ActionButtonList
typedef std::list< PlayerCreateInfoItem > PlayerCreateInfoItems
typedef std::list< uint32 > PlayerCreateInfoSpells
typedef std::list< PlayerCreateInfoAction > PlayerCreateInfoActions
typedef std::list< PlayerCreateInfoSkill > PlayerCreateInfoSkills
typedef std::list< EnchantDuration > EnchantDurationList
typedef std::list< Item * > ItemDurationList
typedef std::map< uint32, QuestStatusData > QuestStatusMap
typedef std::unordered_map< uint32, SkillStatusData > SkillStatusMap
typedef std::map< uint32, EquipmentSet > EquipmentSets
typedef std::vector< ItemPosCount > ItemPosCountVec
Enumerations
enum EnvironmentFlags {
ENVIRONMENT_FLAG_NONE = 0x00 , ENVIRONMENT_FLAG_IN_WATER = 0x01 , ENVIRONMENT_FLAG_IN_MAGMA = 0x02 , ENVIRONMENT_FLAG_IN_SLIME = 0x04 ,
ENVIRONMENT_FLAG_HIGH_SEA = 0x08 , ENVIRONMENT_FLAG_UNDERWATER = 0x10 , ENVIRONMENT_FLAG_HIGH_LIQUID = 0x20 , ENVIRONMENT_FLAG_LIQUID = 0x40 ,
ENVIRONMENT_MASK_LIQUID_HAZARD = (ENVIRONMENT_FLAG_IN_MAGMA | ENVIRONMENT_FLAG_IN_SLIME) , ENVIRONMENT_MASK_IN_LIQUID = (ENVIRONMENT_FLAG_IN_WATER | ENVIRONMENT_MASK_LIQUID_HAZARD) , ENVIRONMENT_MASK_LIQUID_FLAGS = (ENVIRONMENT_FLAG_UNDERWATER | ENVIRONMENT_MASK_IN_LIQUID | ENVIRONMENT_FLAG_HIGH_SEA | ENVIRONMENT_FLAG_LIQUID | ENVIRONMENT_FLAG_HIGH_LIQUID)
}
enum BuyBankSlotResult { ERR_BANKSLOT_FAILED_TOO_MANY = 0 , ERR_BANKSLOT_INSUFFICIENT_FUNDS = 1 , ERR_BANKSLOT_NOTBANKER = 2 , ERR_BANKSLOT_OK = 3 }
enum PlayerSpellState { PLAYERSPELL_UNCHANGED = 0 , PLAYERSPELL_CHANGED = 1 , PLAYERSPELL_NEW = 2 , PLAYERSPELL_REMOVED = 3 }
enum TrainerSpellState { TRAINER_SPELL_GREEN = 0 , TRAINER_SPELL_RED = 1 , TRAINER_SPELL_GRAY = 2 , TRAINER_SPELL_GREEN_DISABLED = 10 }
enum ActionButtonUpdateState { ACTIONBUTTON_UNCHANGED = 0 , ACTIONBUTTON_CHANGED = 1 , ACTIONBUTTON_NEW = 2 , ACTIONBUTTON_DELETED = 3 }
enum ActionButtonType {
ACTION_BUTTON_SPELL = 0x00 , ACTION_BUTTON_C = 0x01 , ACTION_BUTTON_EQSET = 0x20 , ACTION_BUTTON_MACRO = 0x40 ,
ACTION_BUTTON_CMACRO = ACTION_BUTTON_C | ACTION_BUTTON_MACRO , ACTION_BUTTON_ITEM = 0x80
}
enum ActionButtonIndex { ACTION_BUTTON_SHAMAN_TOTEMS_BAR = 132 }
enum GlyphUpdateState { GLYPH_UNCHANGED = 0 , GLYPH_CHANGED = 1 , GLYPH_NEW = 2 , GLYPH_DELETED = 3 }
enum RuneType {
RUNE_BLOOD = 0 , RUNE_UNHOLY = 1 , RUNE_FROST = 2 , RUNE_DEATH = 3 ,
NUM_RUNE_TYPES = 4
}
enum RaidGroupError {
ERR_RAID_GROUP_NONE = 0 , ERR_RAID_GROUP_LOWLEVEL = 1 , ERR_RAID_GROUP_ONLY = 2 , ERR_RAID_GROUP_FULL = 3 ,
ERR_RAID_GROUP_REQUIREMENTS_UNMATCH = 4
}
enum DrunkenState { DRUNKEN_SOBER = 0 , DRUNKEN_TIPSY = 1 , DRUNKEN_DRUNK = 2 , DRUNKEN_SMASHED = 3 }
enum PlayerFlags {
PLAYER_FLAGS_NONE = 0x00000000 , PLAYER_FLAGS_GROUP_LEADER = 0x00000001 , PLAYER_FLAGS_AFK = 0x00000002 , PLAYER_FLAGS_DND = 0x00000004 ,
PLAYER_FLAGS_GM = 0x00000008 , PLAYER_FLAGS_GHOST = 0x00000010 , PLAYER_FLAGS_RESTING = 0x00000020 , PLAYER_FLAGS_UNK7 = 0x00000040 ,
PLAYER_FLAGS_UNK8 = 0x00000080 , PLAYER_FLAGS_CONTESTED_PVP = 0x00000100 , PLAYER_FLAGS_PVP_DESIRED = 0x00000200 , PLAYER_FLAGS_HIDE_HELM = 0x00000400 ,
PLAYER_FLAGS_HIDE_CLOAK = 0x00000800 , PLAYER_FLAGS_PARTIAL_PLAY_TIME = 0x00001000 , PLAYER_FLAGS_NO_PLAY_TIME = 0x00002000 , PLAYER_FLAGS_IS_OUT_OF_BOUNDS = 0x00004000 ,
PLAYER_FLAGS_DEVELOPER = 0x00008000 , PLAYER_FLAGS_ENABLE_LOW_LEVEL_RAID = 0x00010000 , PLAYER_FLAGS_TAXI_BENCHMARK = 0x00020000 , PLAYER_FLAGS_PVP_TIMER = 0x00040000 ,
PLAYER_FLAGS_COMMENTATOR = 0x00080000 , PLAYER_FLAGS_UNK21 = 0x00100000 , PLAYER_FLAGS_UNK22 = 0x00200000 , PLAYER_FLAGS_COMMENTATOR_UBER = 0x00400000 ,
PLAYER_ALLOW_ONLY_ABILITY = 0x00800000 , PLAYER_FLAGS_UNK25 = 0x01000000 , PLAYER_FLAGS_XP_USER_DISABLED = 0x02000000
}
enum PlayerFieldByteFlags { PLAYER_FIELD_BYTE_TRACK_STEALTHED = 0x02 , PLAYER_FIELD_BYTE_RELEASE_TIMER = 0x08 , PLAYER_FIELD_BYTE_NO_RELEASE_WINDOW = 0x10 }
enum PlayerFieldByte2Flags {
PLAYER_FIELD_BYTE2_NONE = 0x00 , PLAYER_FIELD_BYTE2_DETECT_AMORE_0 = 0x02 , PLAYER_FIELD_BYTE2_DETECT_AMORE_1 = 0x04 , PLAYER_FIELD_BYTE2_DETECT_AMORE_2 = 0x08 ,
PLAYER_FIELD_BYTE2_DETECT_AMORE_3 = 0x10 , PLAYER_FIELD_BYTE2_STEALTH = 0x20 , PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW = 0x40
}
enum PlayerFieldBytesOffsets { PLAYER_FIELD_BYTES_OFFSET_FLAGS = 0 , PLAYER_FIELD_BYTES_OFFSET_RAF_GRANTABLE_LEVEL = 1 , PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES = 2 , PLAYER_FIELD_BYTES_OFFSET_LIFETIME_MAX_PVP_RANK = 3 }
enum PlayerExtraFlags {
PLAYER_EXTRA_GM_ON = 0x0001 , PLAYER_EXTRA_GM_ACCEPT_TICKETS = 0x0002 , PLAYER_EXTRA_ACCEPT_WHISPERS = 0x0004 , PLAYER_EXTRA_TAXICHEAT = 0x0008 ,
PLAYER_EXTRA_GM_INVISIBLE = 0x0010 , PLAYER_EXTRA_GM_CHAT = 0x0020 , PLAYER_EXTRA_AUCTION_NEUTRAL = 0x0040 , PLAYER_EXTRA_AUCTION_ENEMY = 0x0080 ,
PLAYER_EXTRA_PVP_DEATH = 0x0100 , PLAYER_EXTRA_WHISP_RESTRICTION = 0x0200
}
enum AtLoginFlags {
AT_LOGIN_NONE = 0x00 , AT_LOGIN_RENAME = 0x01 , AT_LOGIN_RESET_SPELLS = 0x02 , AT_LOGIN_RESET_TALENTS = 0x04 ,
AT_LOGIN_CUSTOMIZE = 0x08 , AT_LOGIN_RESET_PET_TALENTS = 0x10 , AT_LOGIN_FIRST = 0x20 , AT_LOGIN_RESET_TAXINODES = 0x40 ,
AT_LOGIN_ADD_BG_DESERTER = 0x80
}
enum QuestSlotOffsets { QUEST_ID_OFFSET = 0 , QUEST_STATE_OFFSET = 1 , QUEST_COUNTS_OFFSET = 2 , QUEST_TIME_OFFSET = 4 }
enum QuestSlotStateMask { QUEST_STATE_NONE = 0x0000 , QUEST_STATE_COMPLETE = 0x0001 , QUEST_STATE_FAIL = 0x0002 }
enum SkillUpdateState { SKILL_UNCHANGED = 0 , SKILL_CHANGED = 1 , SKILL_NEW = 2 , SKILL_DELETED = 3 }
enum PlayerSlots { PLAYER_SLOT_START = 0 , PLAYER_SLOT_END = 150 , PLAYER_SLOTS_COUNT = (PLAYER_SLOT_END - PLAYER_SLOT_START) }
enum EquipmentSlots {
EQUIPMENT_SLOT_START = 0 , EQUIPMENT_SLOT_HEAD = 0 , EQUIPMENT_SLOT_NECK = 1 , EQUIPMENT_SLOT_SHOULDERS = 2 ,
EQUIPMENT_SLOT_BODY = 3 , EQUIPMENT_SLOT_CHEST = 4 , EQUIPMENT_SLOT_WAIST = 5 , EQUIPMENT_SLOT_LEGS = 6 ,
EQUIPMENT_SLOT_FEET = 7 , EQUIPMENT_SLOT_WRISTS = 8 , EQUIPMENT_SLOT_HANDS = 9 , EQUIPMENT_SLOT_FINGER1 = 10 ,
EQUIPMENT_SLOT_FINGER2 = 11 , EQUIPMENT_SLOT_TRINKET1 = 12 , EQUIPMENT_SLOT_TRINKET2 = 13 , EQUIPMENT_SLOT_BACK = 14 ,
EQUIPMENT_SLOT_MAINHAND = 15 , EQUIPMENT_SLOT_OFFHAND = 16 , EQUIPMENT_SLOT_RANGED = 17 , EQUIPMENT_SLOT_TABARD = 18 ,
EQUIPMENT_SLOT_END = 19
}
enum InventorySlots { INVENTORY_SLOT_BAG_START = 19 , INVENTORY_SLOT_BAG_END = 23 }
enum InventoryPackSlots { INVENTORY_SLOT_ITEM_START = 23 , INVENTORY_SLOT_ITEM_END = 39 }
enum BankItemSlots { BANK_SLOT_ITEM_START = 39 , BANK_SLOT_ITEM_END = 67 }
enum BankBagSlots { BANK_SLOT_BAG_START = 67 , BANK_SLOT_BAG_END = 74 }
enum BuyBackSlots { BUYBACK_SLOT_START = 74 , BUYBACK_SLOT_END = 86 }
enum KeyRingSlots { KEYRING_SLOT_START = 86 , KEYRING_SLOT_END = 118 }
enum CurrencyTokenSlots { CURRENCYTOKEN_SLOT_START = 118 , CURRENCYTOKEN_SLOT_END = 150 }
enum EquipmentSetUpdateState { EQUIPMENT_SET_UNCHANGED = 0 , EQUIPMENT_SET_CHANGED = 1 , EQUIPMENT_SET_NEW = 2 , EQUIPMENT_SET_DELETED = 3 }
enum TradeSlots { TRADE_SLOT_COUNT = 7 , TRADE_SLOT_TRADED_COUNT = 6 , TRADE_SLOT_NONTRADED = 6 }
enum TransferAbortReason {
TRANSFER_ABORT_NONE = 0x00 , TRANSFER_ABORT_ERROR = 0x01 , TRANSFER_ABORT_MAX_PLAYERS = 0x02 , TRANSFER_ABORT_NOT_FOUND = 0x03 ,
TRANSFER_ABORT_TOO_MANY_INSTANCES = 0x04 , TRANSFER_ABORT_ZONE_IN_COMBAT = 0x06 , TRANSFER_ABORT_INSUF_EXPAN_LVL = 0x07 , TRANSFER_ABORT_DIFFICULTY = 0x08 ,
TRANSFER_ABORT_UNIQUE_MESSAGE = 0x09 , TRANSFER_ABORT_TOO_MANY_REALM_INSTANCES = 0x0A , TRANSFER_ABORT_NEED_GROUP = 0x0B , TRANSFER_ABORT_NOT_FOUND2 = 0x0C ,
TRANSFER_ABORT_NOT_FOUND3 = 0x0D , TRANSFER_ABORT_NOT_FOUND4 = 0x0E , TRANSFER_ABORT_REALM_ONLY = 0x0F , TRANSFER_ABORT_MAP_NOT_ALLOWED = 0x10
}
enum InstanceResetWarningType {
RAID_INSTANCE_WARNING_HOURS = 1 , RAID_INSTANCE_WARNING_MIN = 2 , RAID_INSTANCE_WARNING_MIN_SOON = 3 , RAID_INSTANCE_WELCOME = 4 ,
RAID_INSTANCE_EXPIRED = 5
}
enum ArenaTeamInfoType {
ARENA_TEAM_ID = 0 , ARENA_TEAM_TYPE = 1 , ARENA_TEAM_MEMBER = 2 , ARENA_TEAM_GAMES_WEEK = 3 ,
ARENA_TEAM_GAMES_SEASON = 4 , ARENA_TEAM_WINS_SEASON = 5 , ARENA_TEAM_PERSONAL_RATING = 6 , ARENA_TEAM_END = 7
}
enum RestType { REST_TYPE_NO = 0 , REST_TYPE_IN_TAVERN = 1 , REST_TYPE_IN_CITY = 2 , REST_TYPE_FACTION_AREA = 4 }
enum DuelCompleteType { DUEL_INTERRUPTED = 0 , DUEL_WON = 1 , DUEL_FLED = 2 }
enum TeleportToOptions {
TELE_TO_GM_MODE = 0x01 , TELE_TO_NOT_LEAVE_TRANSPORT = 0x02 , TELE_TO_NOT_LEAVE_COMBAT = 0x04 , TELE_TO_NOT_UNSUMMON_PET = 0x08 ,
TELE_TO_SPELL = 0x10
}
enum EnviromentalDamage {
DAMAGE_EXHAUSTED = 0 , DAMAGE_DROWNING = 1 , DAMAGE_FALL = 2 , DAMAGE_LAVA = 3 ,
DAMAGE_SLIME = 4 , DAMAGE_FIRE = 5 , DAMAGE_FALL_TO_VOID = 6
}
Type of environmental damages.
enum PlayedTimeIndex { PLAYED_TIME_TOTAL = 0 , PLAYED_TIME_LEVEL = 1 }
enum PlayerLoginQueryIndex {
PLAYER_LOGIN_QUERY_LOADFROM , PLAYER_LOGIN_QUERY_LOADGROUP , PLAYER_LOGIN_QUERY_LOADBOUNDINSTANCES , PLAYER_LOGIN_QUERY_LOADAURAS ,
PLAYER_LOGIN_QUERY_LOADSPELLS , PLAYER_LOGIN_QUERY_LOADQUESTSTATUS , PLAYER_LOGIN_QUERY_LOADDAILYQUESTSTATUS , PLAYER_LOGIN_QUERY_LOADREPUTATION ,
PLAYER_LOGIN_QUERY_LOADINVENTORY , PLAYER_LOGIN_QUERY_LOADITEMLOOT , PLAYER_LOGIN_QUERY_LOADACTIONS , PLAYER_LOGIN_QUERY_LOADSOCIALLIST ,
PLAYER_LOGIN_QUERY_LOADHOMEBIND , PLAYER_LOGIN_QUERY_LOADSPELLCOOLDOWNS , PLAYER_LOGIN_QUERY_LOADDECLINEDNAMES , PLAYER_LOGIN_QUERY_LOADGUILD ,
PLAYER_LOGIN_QUERY_LOADARENAINFO , PLAYER_LOGIN_QUERY_LOADACHIEVEMENTS , PLAYER_LOGIN_QUERY_LOADCRITERIAPROGRESS , PLAYER_LOGIN_QUERY_LOADEQUIPMENTSETS ,
PLAYER_LOGIN_QUERY_LOADBGDATA , PLAYER_LOGIN_QUERY_LOADACCOUNTDATA , PLAYER_LOGIN_QUERY_LOADSKILLS , PLAYER_LOGIN_QUERY_LOADGLYPHS ,
PLAYER_LOGIN_QUERY_LOADMAILS , PLAYER_LOGIN_QUERY_LOADMAILEDITEMS , PLAYER_LOGIN_QUERY_LOADTALENTS , PLAYER_LOGIN_QUERY_LOADWEEKLYQUESTSTATUS ,
PLAYER_LOGIN_QUERY_LOADMONTHLYQUESTSTATUS , PLAYER_LOGIN_QUERY_LOADRANDOMBATTLEGROUND , MAX_PLAYER_LOGIN_QUERY
}
enum PlayerDelayedOperations {
DELAYED_SAVE_PLAYER = 0x01 , DELAYED_RESURRECT_PLAYER = 0x02 , DELAYED_SPELL_CAST_DESERTER = 0x04 , DELAYED_BG_MOUNT_RESTORE = 0x08 ,
DELAYED_BG_TAXI_RESTORE = 0x10 , DELAYED_END
}
enum ReputationSource { REPUTATION_SOURCE_KILL , REPUTATION_SOURCE_QUEST , REPUTATION_SOURCE_SPELL }
enum BindExtensionState { EXTEND_STATE_EXPIRED = 0 , EXTEND_STATE_NORMAL = 1 , EXTEND_STATE_EXTENDED = 2 , EXTEND_STATE_KEEP = 255 }
enum ReferAFriendError {
ERR_REFER_A_FRIEND_NONE = 0x00 , ERR_REFER_A_FRIEND_NOT_REFERRED_BY = 0x01 , ERR_REFER_A_FRIEND_TARGET_TOO_HIGH = 0x02 , ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS = 0x03 ,
ERR_REFER_A_FRIEND_TOO_FAR = 0x04 , ERR_REFER_A_FRIEND_DIFFERENT_FACTION = 0x05 , ERR_REFER_A_FRIEND_NOT_NOW = 0x06 , ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I = 0x07 ,
ERR_REFER_A_FRIEND_NO_TARGET = 0x08 , ERR_REFER_A_FRIEND_NOT_IN_GROUP = 0x09 , ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I = 0x0A , ERR_REFER_A_FRIEND_SUMMON_COOLDOWN = 0x0B ,
ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL = 0x0C , ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S = 0x0D
}
enum PlayerRestState { REST_STATE_RESTED = 0x01 , REST_STATE_NORMAL = 0x02 , REST_STATE_RAF_LINKED = 0x04 }
enum SetPlayerDifficultyResult {
RESULT_SET_DIFFICULTY = 0 , RESULT_COOLDOWN = 1 , RESULT_WORLDSTATE = 2 , RESULT_ENCOUNTER_IN_PROGRESS = 3 ,
RESULT_PLAYER_IN_COMBAT = 4 , RESULT_PLAYER_BUSY = 5 , RESULT_START = 6 , RESULT_ALREADY_IN_PROGRESS = 7 ,
RESULT_FAILED_CONDITION = 8 , RESULT_COMPLETE = 9
}
Functions
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
void AddItemsSetItem (Player *player, Item *item)
void RemoveItemsSetItem (Player *player, ItemPrototype const *proto)
Macro Definition Documentation
ACTION_BUTTON_ACTION
#define ACTION_BUTTON_ACTION (X) (uint32(X) & 0x00FFFFFF)
Definition at line 163 of file Player.h.
ACTION_BUTTON_TYPE
#define ACTION_BUTTON_TYPE (X) ((uint32(X) & 0xFF000000) >> 24)
Definition at line 164 of file Player.h.
INVENTORY_SLOT_BAG_0
#define INVENTORY_SLOT_BAG_0 255
Definition at line 622 of file Player.h.
KNOWN_TITLES_SIZE
#define KNOWN_TITLES_SIZE 3
Definition at line 447 of file Player.h.
MAX_ACTION_BUTTON_ACTION_VALUE
#define MAX_ACTION_BUTTON_ACTION_VALUE (0x00FFFFFF+1)
Definition at line 165 of file Player.h.
MAX_ACTION_BUTTONS
#define MAX_ACTION_BUTTONS 144
Definition at line 195 of file Player.h.
MAX_DRUNKEN
#define MAX_DRUNKEN 4
Definition at line 414 of file Player.h.
MAX_EQUIPMENT_SET_INDEX
#define MAX_EQUIPMENT_SET_INDEX 10
Definition at line 716 of file Player.h.
MAX_MONEY_AMOUNT
#define MAX_MONEY_AMOUNT (0x7FFFFFFF-1)
Definition at line 878 of file Player.h.
MAX_PLAYED_TIME_INDEX
#define MAX_PLAYED_TIME_INDEX 2
Definition at line 820 of file Player.h.
MAX_PLAYER_SUMMON_DELAY
#define MAX_PLAYER_SUMMON_DELAY (2*MINUTE)
Definition at line 877 of file Player.h.
MAX_QUEST_OFFSET
#define MAX_QUEST_OFFSET 5
Definition at line 585 of file Player.h.
MAX_RUNES
#define MAX_RUNES 6
Definition at line 350 of file Player.h.
MAX_TITLE_INDEX
#define MAX_TITLE_INDEX (KNOWN_TITLES_SIZE*64)
Definition at line 448 of file Player.h.
PLAYER_EXPLORED_ZONES_SIZE
#define PLAYER_EXPLORED_ZONES_SIZE 128
Definition at line 74 of file Player.h.
PLAYER_MAX_DAILY_QUESTS
#define PLAYER_MAX_DAILY_QUESTS 25
Definition at line 73 of file Player.h.
PLAYER_MAX_SKILLS
#define PLAYER_MAX_SKILLS 127
Definition at line 72 of file Player.h.
PLAYER_NEW_INSTANCE_LIMIT_PER_HOUR
#define PLAYER_NEW_INSTANCE_LIMIT_PER_HOUR 5
Definition at line 77 of file Player.h.
RUNE_COOLDOWN
#define RUNE_COOLDOWN (2*5*IN_MILLISECONDS)
Definition at line 351 of file Player.h.
Typedef Documentation
ActionButtonList
typedef std::map<uint8, ActionButton> ActionButtonList
Definition at line 197 of file Player.h.
EnchantDurationList
typedef std::list<EnchantDuration> EnchantDurationList
Definition at line 394 of file Player.h.
EquipmentSets
typedef std::map<uint32, EquipmentSet> EquipmentSets
Definition at line 718 of file Player.h.
ItemDurationList
typedef std::list<Item*> ItemDurationList
Definition at line 395 of file Player.h.
ItemPosCountVec
typedef std::vector<ItemPosCount> ItemPosCountVec
Definition at line 727 of file Player.h.
PlayerCreateInfoActions
typedef std::list<PlayerCreateInfoAction> PlayerCreateInfoActions
Definition at line 284 of file Player.h.
PlayerCreateInfoItems
typedef std::list<PlayerCreateInfoItem> PlayerCreateInfoItems
Definition at line 249 of file Player.h.
PlayerCreateInfoSkills
typedef std::list<PlayerCreateInfoSkill> PlayerCreateInfoSkills
Definition at line 292 of file Player.h.
PlayerCreateInfoSpells
typedef std::list<uint32> PlayerCreateInfoSpells
Definition at line 272 of file Player.h.
PlayerMails
typedef std::deque<Mail*> PlayerMails
Definition at line 70 of file Player.h.
PlayerSpellMap
typedef std::unordered_map<uint32, PlayerSpell> PlayerSpellMap
Definition at line 126 of file Player.h.
PlayerTalentMap
typedef std::unordered_map<uint32, PlayerTalent> PlayerTalentMap
Definition at line 127 of file Player.h.
QuestStatusMap
typedef std::map<uint32, QuestStatusData> QuestStatusMap
Definition at line 575 of file Player.h.
SkillStatusMap
typedef std::unordered_map<uint32, SkillStatusData> SkillStatusMap
Definition at line 611 of file Player.h.
SpellCooldowns
typedef std::map<uint32, SpellCooldown> SpellCooldowns
Definition at line 135 of file Player.h.
Enumeration Type Documentation
ActionButtonIndex
enum ActionButtonIndex
Enumerator
ACTION_BUTTON_SHAMAN_TOTEMS_BAR
Definition at line 190 of file Player.h.
ActionButtonType
enum ActionButtonType
Enumerator
ACTION_BUTTON_SPELL
ACTION_BUTTON_C
ACTION_BUTTON_EQSET
ACTION_BUTTON_MACRO
ACTION_BUTTON_CMACRO
ACTION_BUTTON_ITEM
Definition at line 153 of file Player.h.
ActionButtonUpdateState
enum ActionButtonUpdateState
Enumerator
ACTIONBUTTON_UNCHANGED
ACTIONBUTTON_CHANGED
ACTIONBUTTON_NEW
ACTIONBUTTON_DELETED
Definition at line 145 of file Player.h.
ArenaTeamInfoType
enum ArenaTeamInfoType
Enumerator
ARENA_TEAM_ID
ARENA_TEAM_TYPE
ARENA_TEAM_MEMBER
ARENA_TEAM_GAMES_WEEK
ARENA_TEAM_GAMES_SEASON
ARENA_TEAM_WINS_SEASON
ARENA_TEAM_PERSONAL_RATING
ARENA_TEAM_END
Definition at line 766 of file Player.h.
AtLoginFlags
enum AtLoginFlags
Enumerator
AT_LOGIN_NONE
AT_LOGIN_RENAME
AT_LOGIN_RESET_SPELLS
AT_LOGIN_RESET_TALENTS
AT_LOGIN_CUSTOMIZE
AT_LOGIN_RESET_PET_TALENTS
AT_LOGIN_FIRST
AT_LOGIN_RESET_TAXINODES
AT_LOGIN_ADD_BG_DESERTER
Definition at line 562 of file Player.h.
BankBagSlots
enum BankBagSlots
Enumerator
BANK_SLOT_BAG_START
BANK_SLOT_BAG_END
Definition at line 667 of file Player.h.
BankItemSlots
enum BankItemSlots
Enumerator
BANK_SLOT_ITEM_START
BANK_SLOT_ITEM_END
Definition at line 661 of file Player.h.
BindExtensionState
enum BindExtensionState
Enumerator
EXTEND_STATE_EXPIRED
EXTEND_STATE_NORMAL
EXTEND_STATE_EXTENDED
EXTEND_STATE_KEEP
Definition at line 880 of file Player.h.
BuyBackSlots
enum BuyBackSlots
Enumerator
BUYBACK_SLOT_START
BUYBACK_SLOT_END
Definition at line 673 of file Player.h.
BuyBankSlotResult
enum BuyBankSlotResult
Enumerator
ERR_BANKSLOT_FAILED_TOO_MANY
ERR_BANKSLOT_INSUFFICIENT_FUNDS
ERR_BANKSLOT_NOTBANKER
ERR_BANKSLOT_OK
Definition at line 95 of file Player.h.
CurrencyTokenSlots
enum CurrencyTokenSlots
Enumerator
CURRENCYTOKEN_SLOT_START
CURRENCYTOKEN_SLOT_END
Definition at line 686 of file Player.h.
DrunkenState
enum DrunkenState
Enumerator
DRUNKEN_SOBER
DRUNKEN_TIPSY
DRUNKEN_DRUNK
DRUNKEN_SMASHED
Definition at line 406 of file Player.h.
DuelCompleteType
enum DuelCompleteType
Enumerator
DUEL_INTERRUPTED
DUEL_WON
DUEL_FLED
Definition at line 786 of file Player.h.
EnviromentalDamage
enum EnviromentalDamage
Type of environmental damages.
Enumerator
DAMAGE_EXHAUSTED
DAMAGE_DROWNING
DAMAGE_FALL
DAMAGE_LAVA
DAMAGE_SLIME
DAMAGE_FIRE
DAMAGE_FALL_TO_VOID
Definition at line 803 of file Player.h.
EnvironmentFlags
enum EnvironmentFlags
Enumerator
ENVIRONMENT_FLAG_NONE
ENVIRONMENT_FLAG_IN_WATER
ENVIRONMENT_FLAG_IN_MAGMA
ENVIRONMENT_FLAG_IN_SLIME
ENVIRONMENT_FLAG_HIGH_SEA
ENVIRONMENT_FLAG_UNDERWATER
ENVIRONMENT_FLAG_HIGH_LIQUID
ENVIRONMENT_FLAG_LIQUID
ENVIRONMENT_MASK_LIQUID_HAZARD
ENVIRONMENT_MASK_IN_LIQUID
ENVIRONMENT_MASK_LIQUID_FLAGS
Definition at line 79 of file Player.h.
EquipmentSetUpdateState
enum EquipmentSetUpdateState
Enumerator
EQUIPMENT_SET_UNCHANGED
EQUIPMENT_SET_CHANGED
EQUIPMENT_SET_NEW
EQUIPMENT_SET_DELETED
Definition at line 692 of file Player.h.
EquipmentSlots
enum EquipmentSlots
Enumerator
EQUIPMENT_SLOT_START
EQUIPMENT_SLOT_HEAD
EQUIPMENT_SLOT_NECK
EQUIPMENT_SLOT_SHOULDERS
EQUIPMENT_SLOT_BODY
EQUIPMENT_SLOT_CHEST
EQUIPMENT_SLOT_WAIST
EQUIPMENT_SLOT_LEGS
EQUIPMENT_SLOT_FEET
EQUIPMENT_SLOT_WRISTS
EQUIPMENT_SLOT_HANDS
EQUIPMENT_SLOT_FINGER1
EQUIPMENT_SLOT_FINGER2
EQUIPMENT_SLOT_TRINKET1
EQUIPMENT_SLOT_TRINKET2
EQUIPMENT_SLOT_BACK
EQUIPMENT_SLOT_MAINHAND
EQUIPMENT_SLOT_OFFHAND
EQUIPMENT_SLOT_RANGED
EQUIPMENT_SLOT_TABARD
EQUIPMENT_SLOT_END
Definition at line 624 of file Player.h.
GlyphUpdateState
enum GlyphUpdateState
Enumerator
GLYPH_UNCHANGED
GLYPH_CHANGED
GLYPH_NEW
GLYPH_DELETED
Definition at line 199 of file Player.h.
InstanceResetWarningType
enum InstanceResetWarningType
Enumerator
RAID_INSTANCE_WARNING_HOURS
RAID_INSTANCE_WARNING_MIN
RAID_INSTANCE_WARNING_MIN_SOON
RAID_INSTANCE_WELCOME
RAID_INSTANCE_EXPIRED
Definition at line 756 of file Player.h.
InventoryPackSlots
enum InventoryPackSlots
Enumerator
INVENTORY_SLOT_ITEM_START
INVENTORY_SLOT_ITEM_END
Definition at line 655 of file Player.h.
InventorySlots
enum InventorySlots
Enumerator
INVENTORY_SLOT_BAG_START
INVENTORY_SLOT_BAG_END
Definition at line 649 of file Player.h.
KeyRingSlots
enum KeyRingSlots
Enumerator
KEYRING_SLOT_START
KEYRING_SLOT_END
Definition at line 680 of file Player.h.
PlayedTimeIndex
enum PlayedTimeIndex
Enumerator
PLAYED_TIME_TOTAL
PLAYED_TIME_LEVEL
Definition at line 814 of file Player.h.
PlayerDelayedOperations
enum PlayerDelayedOperations
Enumerator
DELAYED_SAVE_PLAYER
DELAYED_RESURRECT_PLAYER
DELAYED_SPELL_CAST_DESERTER
DELAYED_BG_MOUNT_RESTORE
Flag to restore mount state after teleport from BG.
DELAYED_BG_TAXI_RESTORE
Flag to restore taxi state after teleport from BG.
DELAYED_END
Definition at line 859 of file Player.h.
PlayerExtraFlags
enum PlayerExtraFlags
Enumerator
PLAYER_EXTRA_GM_ON
PLAYER_EXTRA_GM_ACCEPT_TICKETS
PLAYER_EXTRA_ACCEPT_WHISPERS
PLAYER_EXTRA_TAXICHEAT
PLAYER_EXTRA_GM_INVISIBLE
PLAYER_EXTRA_GM_CHAT
PLAYER_EXTRA_AUCTION_NEUTRAL
PLAYER_EXTRA_AUCTION_ENEMY
PLAYER_EXTRA_PVP_DEATH
PLAYER_EXTRA_WHISP_RESTRICTION
Definition at line 544 of file Player.h.
PlayerFieldByte2Flags
enum PlayerFieldByte2Flags
Enumerator
PLAYER_FIELD_BYTE2_NONE
PLAYER_FIELD_BYTE2_DETECT_AMORE_0
PLAYER_FIELD_BYTE2_DETECT_AMORE_1
PLAYER_FIELD_BYTE2_DETECT_AMORE_2
PLAYER_FIELD_BYTE2_DETECT_AMORE_3
PLAYER_FIELD_BYTE2_STEALTH
PLAYER_FIELD_BYTE2_INVISIBILITY_GLOW
Definition at line 459 of file Player.h.
PlayerFieldByteFlags
enum PlayerFieldByteFlags
Enumerator
PLAYER_FIELD_BYTE_TRACK_STEALTHED
PLAYER_FIELD_BYTE_RELEASE_TIMER
PLAYER_FIELD_BYTE_NO_RELEASE_WINDOW
Definition at line 451 of file Player.h.
PlayerFieldBytesOffsets
enum PlayerFieldBytesOffsets
Enumerator
PLAYER_FIELD_BYTES_OFFSET_FLAGS
PLAYER_FIELD_BYTES_OFFSET_RAF_GRANTABLE_LEVEL
PLAYER_FIELD_BYTES_OFFSET_ACTION_BAR_TOGGLES
PLAYER_FIELD_BYTES_OFFSET_LIFETIME_MAX_PVP_RANK
Definition at line 470 of file Player.h.
PlayerFlags
enum PlayerFlags
Enumerator
PLAYER_FLAGS_NONE
PLAYER_FLAGS_GROUP_LEADER
PLAYER_FLAGS_AFK
PLAYER_FLAGS_DND
PLAYER_FLAGS_GM
PLAYER_FLAGS_GHOST
PLAYER_FLAGS_RESTING
PLAYER_FLAGS_UNK7
PLAYER_FLAGS_UNK8
PLAYER_FLAGS_CONTESTED_PVP
PLAYER_FLAGS_PVP_DESIRED
PLAYER_FLAGS_HIDE_HELM
PLAYER_FLAGS_HIDE_CLOAK
PLAYER_FLAGS_PARTIAL_PLAY_TIME
PLAYER_FLAGS_NO_PLAY_TIME
PLAYER_FLAGS_IS_OUT_OF_BOUNDS
PLAYER_FLAGS_DEVELOPER
PLAYER_FLAGS_ENABLE_LOW_LEVEL_RAID
PLAYER_FLAGS_TAXI_BENCHMARK
PLAYER_FLAGS_PVP_TIMER
PLAYER_FLAGS_COMMENTATOR
PLAYER_FLAGS_UNK21
PLAYER_FLAGS_UNK22
PLAYER_FLAGS_COMMENTATOR_UBER
PLAYER_ALLOW_ONLY_ABILITY
PLAYER_FLAGS_UNK25
PLAYER_FLAGS_XP_USER_DISABLED
Definition at line 416 of file Player.h.
PlayerLoginQueryIndex
enum PlayerLoginQueryIndex
Enumerator
PLAYER_LOGIN_QUERY_LOADFROM
PLAYER_LOGIN_QUERY_LOADGROUP
PLAYER_LOGIN_QUERY_LOADBOUNDINSTANCES
PLAYER_LOGIN_QUERY_LOADAURAS
PLAYER_LOGIN_QUERY_LOADSPELLS
PLAYER_LOGIN_QUERY_LOADQUESTSTATUS
PLAYER_LOGIN_QUERY_LOADDAILYQUESTSTATUS
PLAYER_LOGIN_QUERY_LOADREPUTATION
PLAYER_LOGIN_QUERY_LOADINVENTORY
PLAYER_LOGIN_QUERY_LOADITEMLOOT
PLAYER_LOGIN_QUERY_LOADACTIONS
PLAYER_LOGIN_QUERY_LOADSOCIALLIST
PLAYER_LOGIN_QUERY_LOADHOMEBIND
PLAYER_LOGIN_QUERY_LOADSPELLCOOLDOWNS
PLAYER_LOGIN_QUERY_LOADDECLINEDNAMES
PLAYER_LOGIN_QUERY_LOADGUILD
PLAYER_LOGIN_QUERY_LOADARENAINFO
PLAYER_LOGIN_QUERY_LOADACHIEVEMENTS
PLAYER_LOGIN_QUERY_LOADCRITERIAPROGRESS
PLAYER_LOGIN_QUERY_LOADEQUIPMENTSETS
PLAYER_LOGIN_QUERY_LOADBGDATA
PLAYER_LOGIN_QUERY_LOADACCOUNTDATA
PLAYER_LOGIN_QUERY_LOADSKILLS
PLAYER_LOGIN_QUERY_LOADGLYPHS
PLAYER_LOGIN_QUERY_LOADMAILS
PLAYER_LOGIN_QUERY_LOADMAILEDITEMS
PLAYER_LOGIN_QUERY_LOADTALENTS
PLAYER_LOGIN_QUERY_LOADWEEKLYQUESTSTATUS
PLAYER_LOGIN_QUERY_LOADMONTHLYQUESTSTATUS
PLAYER_LOGIN_QUERY_LOADRANDOMBATTLEGROUND
MAX_PLAYER_LOGIN_QUERY
Definition at line 823 of file Player.h.
PlayerRestState
enum PlayerRestState
Enumerator
REST_STATE_RESTED
REST_STATE_NORMAL
REST_STATE_RAF_LINKED
Definition at line 921 of file Player.h.
PlayerSlots
enum PlayerSlots
Enumerator
PLAYER_SLOT_START
PLAYER_SLOT_END
PLAYER_SLOTS_COUNT
Definition at line 613 of file Player.h.
PlayerSpellState
enum PlayerSpellState
Enumerator
PLAYERSPELL_UNCHANGED
PLAYERSPELL_CHANGED
PLAYERSPELL_NEW
PLAYERSPELL_REMOVED
Definition at line 103 of file Player.h.
QuestSlotOffsets
enum QuestSlotOffsets
Enumerator
QUEST_ID_OFFSET
QUEST_STATE_OFFSET
QUEST_COUNTS_OFFSET
QUEST_TIME_OFFSET
Definition at line 577 of file Player.h.
QuestSlotStateMask
enum QuestSlotStateMask
Enumerator
QUEST_STATE_NONE
QUEST_STATE_COMPLETE
QUEST_STATE_FAIL
Definition at line 587 of file Player.h.
RaidGroupError
enum RaidGroupError
Enumerator
ERR_RAID_GROUP_NONE
ERR_RAID_GROUP_LOWLEVEL
ERR_RAID_GROUP_ONLY
ERR_RAID_GROUP_FULL
ERR_RAID_GROUP_REQUIREMENTS_UNMATCH
Definition at line 397 of file Player.h.
ReferAFriendError
enum ReferAFriendError
Enumerator
ERR_REFER_A_FRIEND_NONE
ERR_REFER_A_FRIEND_NOT_REFERRED_BY
ERR_REFER_A_FRIEND_TARGET_TOO_HIGH
ERR_REFER_A_FRIEND_INSUFFICIENT_GRANTABLE_LEVELS
ERR_REFER_A_FRIEND_TOO_FAR
ERR_REFER_A_FRIEND_DIFFERENT_FACTION
ERR_REFER_A_FRIEND_NOT_NOW
ERR_REFER_A_FRIEND_GRANT_LEVEL_MAX_I
ERR_REFER_A_FRIEND_NO_TARGET
ERR_REFER_A_FRIEND_NOT_IN_GROUP
ERR_REFER_A_FRIEND_SUMMON_LEVEL_MAX_I
ERR_REFER_A_FRIEND_SUMMON_COOLDOWN
ERR_REFER_A_FRIEND_INSUF_EXPAN_LVL
ERR_REFER_A_FRIEND_SUMMON_OFFLINE_S
Definition at line 903 of file Player.h.
ReputationSource
enum ReputationSource
Enumerator
REPUTATION_SOURCE_KILL
REPUTATION_SOURCE_QUEST
REPUTATION_SOURCE_SPELL
Definition at line 869 of file Player.h.
RestType
enum RestType
Enumerator
REST_TYPE_NO
REST_TYPE_IN_TAVERN
REST_TYPE_IN_CITY
REST_TYPE_FACTION_AREA
Definition at line 778 of file Player.h.
RuneType
enum RuneType
Enumerator
RUNE_BLOOD
RUNE_UNHOLY
RUNE_FROST
RUNE_DEATH
NUM_RUNE_TYPES
Definition at line 353 of file Player.h.
SetPlayerDifficultyResult
enum SetPlayerDifficultyResult
Enumerator
RESULT_SET_DIFFICULTY
RESULT_COOLDOWN
RESULT_WORLDSTATE
RESULT_ENCOUNTER_IN_PROGRESS
RESULT_PLAYER_IN_COMBAT
RESULT_PLAYER_BUSY
RESULT_START
RESULT_ALREADY_IN_PROGRESS
RESULT_FAILED_CONDITION
RESULT_COMPLETE
Definition at line 928 of file Player.h.
SkillUpdateState
enum SkillUpdateState
Enumerator
SKILL_UNCHANGED
SKILL_CHANGED
SKILL_NEW
SKILL_DELETED
Definition at line 594 of file Player.h.
TeleportToOptions
enum TeleportToOptions
Enumerator
TELE_TO_GM_MODE
TELE_TO_NOT_LEAVE_TRANSPORT
TELE_TO_NOT_LEAVE_COMBAT
TELE_TO_NOT_UNSUMMON_PET
TELE_TO_SPELL
Definition at line 793 of file Player.h.
TradeSlots
enum TradeSlots
Enumerator
TRADE_SLOT_COUNT
TRADE_SLOT_TRADED_COUNT
TRADE_SLOT_NONTRADED
Definition at line 729 of file Player.h.
TrainerSpellState
enum TrainerSpellState
Enumerator
TRAINER_SPELL_GREEN
TRAINER_SPELL_RED
TRAINER_SPELL_GRAY
TRAINER_SPELL_GREEN_DISABLED
Definition at line 137 of file Player.h.
TransferAbortReason
enum TransferAbortReason
Enumerator
TRANSFER_ABORT_NONE
TRANSFER_ABORT_ERROR
TRANSFER_ABORT_MAX_PLAYERS
TRANSFER_ABORT_NOT_FOUND
TRANSFER_ABORT_TOO_MANY_INSTANCES
TRANSFER_ABORT_ZONE_IN_COMBAT
TRANSFER_ABORT_INSUF_EXPAN_LVL
TRANSFER_ABORT_DIFFICULTY
TRANSFER_ABORT_UNIQUE_MESSAGE
TRANSFER_ABORT_TOO_MANY_REALM_INSTANCES
TRANSFER_ABORT_NEED_GROUP
TRANSFER_ABORT_NOT_FOUND2
TRANSFER_ABORT_NOT_FOUND3
TRANSFER_ABORT_NOT_FOUND4
TRANSFER_ABORT_REALM_ONLY
TRANSFER_ABORT_MAP_NOT_ALLOWED
Definition at line 736 of file Player.h.
Function Documentation
AddItemsSetItem()
void AddItemsSetItem (Player * player, Item * item)
Definition at line 30 of file Item.cpp.
References Player::AddItemSetEffect(), Player::ApplyEquipSpell(), Player::GetItemSetEffect(), Item::GetProto(), Player::GetSkillValue(), SpellEntry::Id, ItemSetEffect::item_count, ItemPrototype::ItemId, ItemSetEntry::items_to_triggerspell, ItemPrototype::ItemSet, SQLStorage::LookupEntry(), ItemSetEntry::required_skill_id, ItemSetEntry::required_skill_value, sItemSetStore, sLog, ItemSetEffect::spells, ItemSetEntry::spells, and sSpellTemplate.
Referenced by Player::_ApplyAllItemMods(), and Player::EquipItem().
operator<<()
std::ostringstream& operator<< (std::ostringstream & ss, PlayerTaxi const & taxi)
Definition at line 970 of file Player.cpp.
References CLASS_DEATH_KNIGHT, Unit::getClass(), _Spell::SpellCategory, ItemPrototype::Spells, and ItemPrototype::Stackable.
RemoveItemsSetItem()
void RemoveItemsSetItem (Player * player, ItemPrototype const * proto)
Definition at line 90 of file Item.cpp.
References Player::ApplyEquipSpell(), Player::GetItemSetEffect(), ItemSetEffect::item_count, ItemPrototype::ItemId, ItemSetEntry::items_to_triggerspell, ItemPrototype::ItemSet, Player::RemoveItemSetEffect(), sItemSetStore, sLog, ItemSetEffect::spells, and ItemSetEntry::spells.
Referenced by Player::_RemoveAllItemMods(), Player::DestroyItem(), and Player::RemoveItem().