CMaNGOS_WoTLK: Player.cpp File Reference
Player.cpp File Reference
#include "Entities/Player.h"
#include "Tools/Language.h"
#include "Database/DatabaseEnv.h"
#include "Log.h"
#include "Server/Opcodes.h"
#include "Spells/SpellMgr.h"
#include "World/World.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "UpdateMask.h"
#include "Skills/SkillDiscovery.h"
#include "Quests/QuestDef.h"
#include "Entities/GossipDef.h"
#include "Entities/UpdateData.h"
#include "Chat/Channel.h"
#include "Chat/ChannelMgr.h"
#include "Maps/MapManager.h"
#include "Maps/MapPersistentStateMgr.h"
#include "Maps/InstanceData.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/CellImpl.h"
#include "Globals/ObjectMgr.h"
#include "Globals/ObjectAccessor.h"
#include "Tools/Formulas.h"
#include "Groups/Group.h"
#include "Guilds/Guild.h"
#include "Guilds/GuildMgr.h"
#include "Entities/Pet.h"
#include "Util/Util.h"
#include "Entities/Transports.h"
#include "Weather/Weather.h"
#include "BattleGround/BattleGround.h"
#include "BattleGround/BattleGroundMgr.h"
#include "OutdoorPvP/OutdoorPvP.h"
#include "Battlefield/Battlefield.h"
#include "Arena/ArenaTeam.h"
#include "Chat/Chat.h"
#include "Database/DatabaseImpl.h"
#include "Spells/Spell.h"
#include "AI/ScriptDevAI/ScriptDevAIMgr.h"
#include "Social/SocialMgr.h"
#include "Achievements/AchievementMgr.h"
#include "Mails/Mail.h"
#include "Spells/SpellAuras.h"
#include "Server/DBCStores.h"
#include "Server/SQLStorages.h"
#include "Entities/Vehicle.h"
#include "Calendar/Calendar.h"
#include "Loot/LootMgr.h"
#include "World/WorldStateDefines.h"
#include "World/WorldState.h"
#include "Anticheat/Anticheat.hpp"
#include <cmath>
Data Structures
struct SetGameMasterOnHelper
struct SetGameMasterOffHelper
struct UpdateZoneDependentPetsHelper
struct DoPlayerLearnSpell
Macros
#define ZONE_UPDATE_INTERVAL (1*IN_MILLISECONDS)
#define PLAYER_SKILL_INDEX(x) (PLAYER_SKILL_INFO_1_1 + ((x)*3))
#define PLAYER_SKILL_VALUE_INDEX(x) (PLAYER_SKILL_INDEX(x)+1)
#define PLAYER_SKILL_BONUS_INDEX(x) (PLAYER_SKILL_INDEX(x)+2)
#define SKILL_VALUE(x) PAIR32_LOPART(x)
#define SKILL_MAX(x) PAIR32_HIPART(x)
#define MAKE_SKILL_VALUE(v, m) MAKE_PAIR32(v,m)
#define SKILL_TEMP_BONUS(x) int16(PAIR32_LOPART(x))
#define SKILL_PERM_BONUS(x) int16(PAIR32_HIPART(x))
#define MAKE_SKILL_BONUS(t, p) MAKE_PAIR32(t,p)
#define DEATH_EXPIRE_STEP (5*MINUTE)
#define MAX_DEATH_COUNT 3
Enumerations
enum CharacterFlags {
CHARACTER_FLAG_NONE = 0x00000000 , CHARACTER_FLAG_UNK1 = 0x00000001 , CHARACTER_FLAG_UNK2 = 0x00000002 , CHARACTER_LOCKED_FOR_TRANSFER = 0x00000004 ,
CHARACTER_FLAG_UNK4 = 0x00000008 , CHARACTER_FLAG_UNK5 = 0x00000010 , CHARACTER_FLAG_UNK6 = 0x00000020 , CHARACTER_FLAG_UNK7 = 0x00000040 ,
CHARACTER_FLAG_UNK8 = 0x00000080 , CHARACTER_FLAG_UNK9 = 0x00000100 , CHARACTER_FLAG_UNK10 = 0x00000200 , CHARACTER_FLAG_HIDE_HELM = 0x00000400 ,
CHARACTER_FLAG_HIDE_CLOAK = 0x00000800 , CHARACTER_FLAG_UNK13 = 0x00001000 , CHARACTER_FLAG_GHOST = 0x00002000 , CHARACTER_FLAG_RENAME = 0x00004000 ,
CHARACTER_FLAG_UNK16 = 0x00008000 , CHARACTER_FLAG_UNK17 = 0x00010000 , CHARACTER_FLAG_UNK18 = 0x00020000 , CHARACTER_FLAG_UNK19 = 0x00040000 ,
CHARACTER_FLAG_UNK20 = 0x00080000 , CHARACTER_FLAG_UNK21 = 0x00100000 , CHARACTER_FLAG_UNK22 = 0x00200000 , CHARACTER_FLAG_UNK23 = 0x00400000 ,
CHARACTER_FLAG_UNK24 = 0x00800000 , CHARACTER_FLAG_LOCKED_BY_BILLING = 0x01000000 , CHARACTER_FLAG_DECLINED = 0x02000000 , CHARACTER_FLAG_UNK27 = 0x04000000 ,
CHARACTER_FLAG_UNK28 = 0x08000000 , CHARACTER_FLAG_UNK29 = 0x10000000 , CHARACTER_FLAG_UNK30 = 0x20000000 , CHARACTER_FLAG_UNK31 = 0x40000000 ,
CHARACTER_FLAG_UNK32 = 0x80000000
}
enum CharacterCustomizeFlags { CHAR_CUSTOMIZE_FLAG_NONE = 0x00000000 , CHAR_CUSTOMIZE_FLAG_CUSTOMIZE = 0x00000001 , CHAR_CUSTOMIZE_FLAG_FACTION = 0x00010000 , CHAR_CUSTOMIZE_FLAG_RACE = 0x00100000 }
enum TitleFactions {
FACTION_LEAGUE_OF_ARATHOR = 509 , FACTION_STORMPIKE_GUARD = 730 , FACTION_SILVERWING_SENTINELS = 890 , FACTION_DEFILERS = 510 ,
FACTION_FROSTWOLF_CLAN = 729 , FACTION_WARSONG_OUTRIDERS = 889 , TITLE_CONQUEROR = 47 , TITLE_JUSTICAR = 48
}
Functions
std::ostringstream & operator<< (std::ostringstream &ss, PlayerTaxi const &taxi)
static bool IsUnlearnSpellsPacketNeededForSpell (uint32 spellId)
int SkillGainChance (uint32 SkillValue, uint32 GrayLevel, uint32 GreenLevel, uint32 YellowLevel)
uint8 GetFishingStepsNeededToLevelUp (uint32 SkillValue)
template<class T >
void UpdateVisibilityOf_helper (GuidSet &s64, T *target)
template<>
void UpdateVisibilityOf_helper (GuidSet &s64, GameObject *target)
Variables
static const uint32 corpseReclaimDelay [MAX_DEATH_COUNT] = {30, 60, 120}
static const float PLAYER_AGI_TO_CRIT_TO_DODGE [MAX_CLASSES]
static uint32 bonusSkillLevels [] = {75, 150, 225, 300, 375, 450}
static RuneType runeSlotTypes [MAX_RUNES]
Macro Definition Documentation
DEATH_EXPIRE_STEP
#define DEATH_EXPIRE_STEP (5*MINUTE)
Definition at line 145 of file Player.cpp.
MAKE_SKILL_BONUS
#define MAKE_SKILL_BONUS (t, p) MAKE_PAIR32(t,p)
Definition at line 93 of file Player.cpp.
MAKE_SKILL_VALUE
#define MAKE_SKILL_VALUE (v, m) MAKE_PAIR32(v,m)
Definition at line 89 of file Player.cpp.
MAX_DEATH_COUNT
#define MAX_DEATH_COUNT 3
Definition at line 146 of file Player.cpp.
PLAYER_SKILL_BONUS_INDEX
#define PLAYER_SKILL_BONUS_INDEX (x) (PLAYER_SKILL_INDEX(x)+2)
Definition at line 85 of file Player.cpp.
PLAYER_SKILL_INDEX
#define PLAYER_SKILL_INDEX (x) (PLAYER_SKILL_INFO_1_1 + ((x)*3))
Definition at line 83 of file Player.cpp.
PLAYER_SKILL_VALUE_INDEX
#define PLAYER_SKILL_VALUE_INDEX (x) (PLAYER_SKILL_INDEX(x)+1)
Definition at line 84 of file Player.cpp.
SKILL_MAX
#define SKILL_MAX (x) PAIR32_HIPART(x)
Definition at line 88 of file Player.cpp.
SKILL_PERM_BONUS
#define SKILL_PERM_BONUS (x) int16(PAIR32_HIPART(x))
Definition at line 92 of file Player.cpp.
SKILL_TEMP_BONUS
#define SKILL_TEMP_BONUS (x) int16(PAIR32_LOPART(x))
Definition at line 91 of file Player.cpp.
SKILL_VALUE
#define SKILL_VALUE (x) PAIR32_LOPART(x)
Definition at line 87 of file Player.cpp.
ZONE_UPDATE_INTERVAL
#define ZONE_UPDATE_INTERVAL (1*IN_MILLISECONDS)
Definition at line 81 of file Player.cpp.
Enumeration Type Documentation
CharacterCustomizeFlags
enum CharacterCustomizeFlags
Enumerator
CHAR_CUSTOMIZE_FLAG_NONE
CHAR_CUSTOMIZE_FLAG_CUSTOMIZE
CHAR_CUSTOMIZE_FLAG_FACTION
CHAR_CUSTOMIZE_FLAG_RACE
Definition at line 136 of file Player.cpp.
CharacterFlags
enum CharacterFlags
Enumerator
CHARACTER_FLAG_NONE
CHARACTER_FLAG_UNK1
CHARACTER_FLAG_UNK2
CHARACTER_LOCKED_FOR_TRANSFER
CHARACTER_FLAG_UNK4
CHARACTER_FLAG_UNK5
CHARACTER_FLAG_UNK6
CHARACTER_FLAG_UNK7
CHARACTER_FLAG_UNK8
CHARACTER_FLAG_UNK9
CHARACTER_FLAG_UNK10
CHARACTER_FLAG_HIDE_HELM
CHARACTER_FLAG_HIDE_CLOAK
CHARACTER_FLAG_UNK13
CHARACTER_FLAG_GHOST
CHARACTER_FLAG_RENAME
CHARACTER_FLAG_UNK16
CHARACTER_FLAG_UNK17
CHARACTER_FLAG_UNK18
CHARACTER_FLAG_UNK19
CHARACTER_FLAG_UNK20
CHARACTER_FLAG_UNK21
CHARACTER_FLAG_UNK22
CHARACTER_FLAG_UNK23
CHARACTER_FLAG_UNK24
CHARACTER_FLAG_LOCKED_BY_BILLING
CHARACTER_FLAG_DECLINED
CHARACTER_FLAG_UNK27
CHARACTER_FLAG_UNK28
CHARACTER_FLAG_UNK29
CHARACTER_FLAG_UNK30
CHARACTER_FLAG_UNK31
CHARACTER_FLAG_UNK32
Definition at line 99 of file Player.cpp.
TitleFactions
enum TitleFactions
Enumerator
FACTION_LEAGUE_OF_ARATHOR
FACTION_STORMPIKE_GUARD
FACTION_SILVERWING_SENTINELS
FACTION_DEFILERS
FACTION_FROSTWOLF_CLAN
FACTION_WARSONG_OUTRIDERS
TITLE_CONQUEROR
TITLE_JUSTICAR
Definition at line 15726 of file Player.cpp.
Function Documentation
GetFishingStepsNeededToLevelUp()
uint8 GetFishingStepsNeededToLevelUp (uint32 SkillValue)
Definition at line 5774 of file Player.cpp.
Referenced by Player::UpdateFishingSkill().
IsUnlearnSpellsPacketNeededForSpell()
static bool IsUnlearnSpellsPacketNeededForSpell (uint32 spellId) inline static
Definition at line 3392 of file Player.cpp.
References sSpellMgr.
Referenced by Player::addSpell(), and Player::removeSpell().
operator<<()
std::ostringstream& operator<< (std::ostringstream & ss, PlayerTaxi const & taxi)
Definition at line 362 of file Player.cpp.
References CLASS_DEATH_KNIGHT, Unit::getClass(), _Spell::SpellCategory, ItemPrototype::Spells, and ItemPrototype::Stackable.
SkillGainChance()
int SkillGainChance (uint32 SkillValue, uint32 GrayLevel, uint32 GreenLevel, uint32 YellowLevel) inline
Definition at line 5697 of file Player.cpp.
References CONFIG_UINT32_SKILL_CHANCE_GREEN, CONFIG_UINT32_SKILL_CHANCE_GREY, CONFIG_UINT32_SKILL_CHANCE_ORANGE, CONFIG_UINT32_SKILL_CHANCE_YELLOW, and sWorld.
Referenced by Player::UpdateCraftSkill(), and Player::UpdateGatherSkill().
UpdateVisibilityOf_helper() [1/2]
template<> void UpdateVisibilityOf_helper (GuidSet & s64, GameObject * target) inline
Definition at line 21141 of file Player.cpp.
References Object::GetObjectGuid(), and GameObject::IsMoTransport().
UpdateVisibilityOf_helper() [2/2]
template<class T > void UpdateVisibilityOf_helper (GuidSet & s64, T * target) inline
Definition at line 21135 of file Player.cpp.
Variable Documentation
bonusSkillLevels
uint32 bonusSkillLevels[] = {75, 150, 225, 300, 375, 450} static
Definition at line 5812 of file Player.cpp.
Referenced by Player::UpdateSkillPro().
corpseReclaimDelay
const uint32 corpseReclaimDelay[MAX_DEATH_COUNT] = {30, 60, 120} static
Definition at line 148 of file Player.cpp.
Referenced by Player::GetCorpseReclaimDelay(), and Player::SendCorpseReclaimDelay().
PLAYER_AGI_TO_CRIT_TO_DODGE
const float PLAYER_AGI_TO_CRIT_TO_DODGE[MAX_CLASSES] static
Initial value:
=
{
    0.0f,
    0.85f / 1.15f,
    1.00f / 1.15f,
    1.11f / 1.15f,
    2.00f / 1.15f,
    1.00f / 1.15f,
    0.85f / 1.15f,
    1.60f / 1.15f,
    1.00f / 1.15f,
    0.97f / 1.15f,
    0.0f,
    2.00f / 1.15f,
}
Definition at line 5452 of file Player.cpp.
Referenced by Player::GetDodgeFromAgility().
runeSlotTypes
RuneType runeSlotTypes[MAX_RUNES] static
Initial value:
=
{
     RUNE_BLOOD,
     RUNE_BLOOD,
     RUNE_UNHOLY,
     RUNE_UNHOLY,
     RUNE_FROST,
     RUNE_FROST
}
Definition at line 22972 of file Player.cpp.
Referenced by Player::InitRunes().