CMaNGOS_WoTLK: PosixDaemon.cpp File Reference
PosixDaemon.cpp File Reference
#include "Config/Config.h"
#include "PosixDaemon.h"
#include <cstdio>
#include <iostream>
#include <fstream>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
Data Structures
struct WatchDog
Functions
void daemonSignal (int s)
void startDaemon (uint32_t timeout)
void stopDaemon ()
void detachDaemon ()
void exitDaemon ()
Variables
pid_t parent_pid = 0
pid_t sid = 0
WatchDog dog
Function Documentation
daemonSignal()
void daemonSignal (int s)
Definition at line 31 of file PosixDaemon.cpp.
References parent_pid, and sid.
Referenced by startDaemon().
detachDaemon()
void detachDaemon ()
Definition at line 118 of file PosixDaemon.cpp.
References parent_pid.
Referenced by main(), and Master::Run().
exitDaemon()
void exitDaemon ()
Definition at line 126 of file PosixDaemon.cpp.
References parent_pid.
Referenced by WatchDog::~WatchDog().
startDaemon()
void startDaemon (uint32_t timeout)
Definition at line 52 of file PosixDaemon.cpp.
References daemonSignal(), parent_pid, and sid.
Referenced by main().
stopDaemon()
void stopDaemon ()
Definition at line 95 of file PosixDaemon.cpp.
References sConfig.
Referenced by main().
Variable Documentation
dog
WatchDog dog
Definition at line 142 of file PosixDaemon.cpp.
parent_pid
pid_t parent_pid = 0
Definition at line 29 of file PosixDaemon.cpp.
Referenced by daemonSignal(), detachDaemon(), exitDaemon(), and startDaemon().
sid
pid_t sid = 0
Definition at line 29 of file PosixDaemon.cpp.
Referenced by daemonSignal(), and startDaemon().