CMaNGOS_WoTLK: PosixDaemon.h File Reference
PosixDaemon.h File Reference
#include "Common.h"
#include "Log.h"
Functions
void startDaemon (uint32_t timeout=10)
void stopDaemon ()
void detachDaemon ()
Function Documentation
detachDaemon()
void detachDaemon ()
Definition at line 118 of file PosixDaemon.cpp.
References parent_pid.
Referenced by main(), and Master::Run().
startDaemon()
void startDaemon (uint32_t timeout = 10)
Definition at line 52 of file PosixDaemon.cpp.
References daemonSignal(), parent_pid, and sid.
Referenced by main().
stopDaemon()
void stopDaemon ()
Definition at line 95 of file PosixDaemon.cpp.
References sConfig.
Referenced by main().