CMaNGOS_WoTLK: quest_scripts.cpp File Reference
quest_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_xiri
Enumerations
enum {
NPC_AKAMA = 22990 , NPC_VAGATH = 23152 , NPC_ASHTONGUE_DEATHSWORN = 21701 , NPC_SHADOWLORD = 22988 ,
NPC_MAIEV = 22989 , RELAY_SCRIPT_AKAMA = 10135 , QUEST_DISTRACTION_FOR_AKAMA = 10985 , QUEST_VIALS_OF_ETERNITY = 10445 ,
QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON = 10888 , QUEST_CUDGEL_OF_KARDESH = 10901 , TITLE_CHAMPION_OF_THE_NAARU = 53 , TITLE_HAND_OF_ADAL = 64
}
Functions
bool QuestRewarded_tbc_attunement_titles (Player *player, Creature *, Quest const *quest)
UnitAI * GetAI_npc_xiri (Creature *pCreature)
void AddSC_quests_scripts ()
Variables
float DeathswornSpawnCoords [8][3]
float ShadowlordSpawnCoords [6][3]
float * DeathswornPackLeader = DeathswornSpawnCoords[0]
float * DeathswornLeft1 = DeathswornSpawnCoords[1]
float * DeathswornRight1 = DeathswornSpawnCoords[2]
float * DeathswornLeft2 = DeathswornSpawnCoords[3]
float * DeathswornRight2 = DeathswornSpawnCoords[4]
float * DeathswornLeft3 = DeathswornSpawnCoords[5]
float * DeathswornRight3 = DeathswornSpawnCoords[6]
float * DeathswornCenter = DeathswornSpawnCoords[7]
float * ShadowlordLeader1 = ShadowlordSpawnCoords[2]
float * ShadowlordLeft1 = ShadowlordSpawnCoords[0]
float * ShadowlordRight1 = ShadowlordSpawnCoords[1]
float * ShadowlordLeader2 = ShadowlordSpawnCoords[5]
float * ShadowlordLeft2 = ShadowlordSpawnCoords[4]
float * ShadowlordRight2 = ShadowlordSpawnCoords[3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_AKAMA
NPC_VAGATH
NPC_ASHTONGUE_DEATHSWORN
NPC_SHADOWLORD
NPC_MAIEV
RELAY_SCRIPT_AKAMA
QUEST_DISTRACTION_FOR_AKAMA
QUEST_VIALS_OF_ETERNITY
QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON
QUEST_CUDGEL_OF_KARDESH
TITLE_CHAMPION_OF_THE_NAARU
TITLE_HAND_OF_ADAL
Definition at line 23 of file quest_scripts.cpp.
Function Documentation
AddSC_quests_scripts()
void AddSC_quests_scripts ()
Definition at line 300 of file quest_scripts.cpp.
References Script::GetAI, GetAI_npc_xiri(), Script::Name, Script::pQuestRewardedNPC, QuestRewarded_tbc_attunement_titles(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_xiri()
UnitAI* GetAI_npc_xiri (Creature * pCreature)
Definition at line 295 of file quest_scripts.cpp.
Referenced by AddSC_quests_scripts().
QuestRewarded_tbc_attunement_titles()
bool QuestRewarded_tbc_attunement_titles (Player * player, Creature * , Quest const * quest)
Definition at line 42 of file quest_scripts.cpp.
References Quest::GetQuestId(), Player::GetQuestStatus(), QUEST_CUDGEL_OF_KARDESH, QUEST_DISTRACTION_FOR_AKAMA, QUEST_STATUS_COMPLETE, QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON, QUEST_VIALS_OF_ETERNITY, Player::SetTitle(), TITLE_CHAMPION_OF_THE_NAARU, and TITLE_HAND_OF_ADAL.
Referenced by AddSC_quests_scripts().
Variable Documentation
DeathswornCenter
float* DeathswornCenter = DeathswornSpawnCoords[7]
Definition at line 88 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornLeft1
float* DeathswornLeft1 = DeathswornSpawnCoords[1]
Definition at line 82 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornLeft2
float* DeathswornLeft2 = DeathswornSpawnCoords[3]
Definition at line 84 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornLeft3
float* DeathswornLeft3 = DeathswornSpawnCoords[5]
Definition at line 86 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornPackLeader
float* DeathswornPackLeader = DeathswornSpawnCoords[0]
Definition at line 81 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornRight1
float* DeathswornRight1 = DeathswornSpawnCoords[2]
Definition at line 83 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornRight2
float* DeathswornRight2 = DeathswornSpawnCoords[4]
Definition at line 85 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornRight3
float* DeathswornRight3 = DeathswornSpawnCoords[6]
Definition at line 87 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
DeathswornSpawnCoords
float DeathswornSpawnCoords[8][3]
Initial value:
= {
    { -3562.689f, 696.251f, -8.158f },
    { -3559.341f, 699.388f, -8.877f },
    { -3567.493f, 699.383f, -8.488f },
    { -3556.366f, 703.439f, -9.633f },
    { -3569.277f, 702.603f, -8.984f },
    { -3554.079f, 707.530f, -10.408f },
    { -3571.522f, 706.726f, -9.5219f },
    { -3562.928f, 704.436f, -9.5568f } }
Definition at line 63 of file quest_scripts.cpp.
ShadowlordLeader1
float* ShadowlordLeader1 = ShadowlordSpawnCoords[2]
Definition at line 90 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordLeader2
float* ShadowlordLeader2 = ShadowlordSpawnCoords[5]
Definition at line 93 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordLeft1
float* ShadowlordLeft1 = ShadowlordSpawnCoords[0]
Definition at line 91 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordLeft2
float* ShadowlordLeft2 = ShadowlordSpawnCoords[4]
Definition at line 94 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordRight1
float* ShadowlordRight1 = ShadowlordSpawnCoords[1]
Definition at line 92 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordRight2
float* ShadowlordRight2 = ShadowlordSpawnCoords[3]
Definition at line 95 of file quest_scripts.cpp.
Referenced by npc_xiri::ReceiveAIEvent().
ShadowlordSpawnCoords
float ShadowlordSpawnCoords[6][3]
Initial value:
= {
    { -3612.274f, 400.077f, 32.444f },
    { -3591.716f, 392.962f, 32.895f },
    { -3601.192f, 403.606f, 32.621f },
    { -3513.504f, 410.263f, 30.440f },
    { -3515.933f, 376.395f, 33.786f },
    { -3508.507f, 392.346f, 32.418f } }
Definition at line 73 of file quest_scripts.cpp.