CMaNGOS_WoTLK: razorfen_downs.cpp File Reference
razorfen_downs.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_belnistraszAI
Enumerations
enum {
QUEST_EXTINGUISHING_THE_IDOL = 3525 , SAY_BELNISTRASZ_READY = -1129005 , SAY_BELNISTRASZ_START_RIT = -1129006 , SAY_BELNISTRASZ_AGGRO_1 = -1129007 ,
SAY_BELNISTRASZ_AGGRO_2 = -1129008 , SAY_BELNISTRASZ_3_MIN = -1129009 , SAY_BELNISTRASZ_2_MIN = -1129010 , SAY_BELNISTRASZ_1_MIN = -1129011 ,
SAY_BELNISTRASZ_FINISH = -1129012 , NPC_IDOL_ROOM_SPAWNER = 8611 , NPC_WITHERED_BATTLE_BOAR = 7333 , NPC_WITHERED_QUILGUARD = 7329 ,
NPC_DEATHS_HEAD_GEOMANCER = 7335 , NPC_PLAGUEMAW_THE_ROTTING = 7356 , GO_BELNISTRASZ_BRAZIER = 152097 , GO_IDOL_OVEN_FIRE = 151951 ,
GO_IDOL_CUP_FIRE = 151952 , GO_IDOL_MOUTH_FIRE = 151973 , SPELL_ARCANE_INTELLECT = 13326 , SPELL_FIREBALL = 9053 ,
SPELL_FROST_NOVA = 11831 , SPELL_IDOL_SHUTDOWN = 12774 , SPELL_IDOL_ROOM_SHAKE = 12816
}
Functions
UnitAI * GetAI_npc_belnistrasz (Creature *pCreature)
bool QuestAccept_npc_belnistrasz (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_razorfen_downs ()
Variables
static float m_fSpawnerCoord [3][4]
static const uint32 aGOList [] = {GO_IDOL_OVEN_FIRE, GO_IDOL_CUP_FIRE, GO_IDOL_MOUTH_FIRE}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_EXTINGUISHING_THE_IDOL
SAY_BELNISTRASZ_READY
SAY_BELNISTRASZ_START_RIT
SAY_BELNISTRASZ_AGGRO_1
SAY_BELNISTRASZ_AGGRO_2
SAY_BELNISTRASZ_3_MIN
SAY_BELNISTRASZ_2_MIN
SAY_BELNISTRASZ_1_MIN
SAY_BELNISTRASZ_FINISH
NPC_IDOL_ROOM_SPAWNER
NPC_WITHERED_BATTLE_BOAR
NPC_WITHERED_QUILGUARD
NPC_DEATHS_HEAD_GEOMANCER
NPC_PLAGUEMAW_THE_ROTTING
GO_BELNISTRASZ_BRAZIER
GO_IDOL_OVEN_FIRE
GO_IDOL_CUP_FIRE
GO_IDOL_MOUTH_FIRE
SPELL_ARCANE_INTELLECT
SPELL_FIREBALL
SPELL_FROST_NOVA
SPELL_IDOL_SHUTDOWN
SPELL_IDOL_ROOM_SHAKE
Definition at line 35 of file razorfen_downs.cpp.
Function Documentation
AddSC_razorfen_downs()
void AddSC_razorfen_downs ()
Definition at line 306 of file razorfen_downs.cpp.
References Script::GetAI, GetAI_npc_belnistrasz(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_belnistrasz(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_belnistrasz()
UnitAI* GetAI_npc_belnistrasz (Creature * pCreature)
Definition at line 286 of file razorfen_downs.cpp.
Referenced by AddSC_razorfen_downs().
QuestAccept_npc_belnistrasz()
bool QuestAccept_npc_belnistrasz (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 291 of file razorfen_downs.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_EXTINGUISHING_THE_IDOL, SAY_BELNISTRASZ_READY, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_razorfen_downs().
Variable Documentation
aGOList
const uint32 aGOList[] = {GO_IDOL_OVEN_FIRE, GO_IDOL_CUP_FIRE, GO_IDOL_MOUTH_FIRE} static
Definition at line 79 of file razorfen_downs.cpp.
Referenced by npc_belnistraszAI::UpdateEscortAI().
m_fSpawnerCoord
float m_fSpawnerCoord[3][4] static
Initial value:
=
{
    {2582.79f, 954.392f, 52.4821f, 3.78736f},
    {2569.42f, 956.380f, 52.2732f, 5.42797f},
    {2570.62f, 942.393f, 53.7433f, 0.71558f}
}
Definition at line 72 of file razorfen_downs.cpp.
Referenced by npc_belnistraszAI::DoSummonSpawner().