CMaNGOS_WoTLK: razorfen_kraul.cpp File Reference
razorfen_kraul.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
Data Structures
struct npc_willix_the_importerAI
struct npc_snufflenose_gopherAI
struct LeftForDead
Enumerations
enum {
QUEST_WILLIX_THE_IMPORTER = 1144 , SAY_WILLIX_READY = -1047000 , SAY_WILLIX_1 = -1047001 , SAY_WILLIX_2 = -1047002 ,
SAY_WILLIX_3 = -1047003 , SAY_WILLIX_4 = -1047004 , SAY_WILLIX_5 = -1047005 , SAY_WILLIX_6 = -1047006 ,
SAY_WILLIX_7 = -1047007 , SAY_WILLIX_END = -1047008 , SAY_WILLIX_AGGRO_1 = -1047009 , SAY_WILLIX_AGGRO_2 = -1047010 ,
SAY_WILLIX_AGGRO_3 = -1047011 , SAY_WILLIX_AGGRO_4 = -1047012 , NPC_RAGING_AGAMAR = 4514
}
enum { SPELL_SNUFFLENOSE_COMMAND = 8283 , NPC_SNUFFLENOSE_GOPHER = 4781 , GO_BLUELEAF_TUBBER = 20920 }
Functions
UnitAI * GetAI_npc_willix_the_importer (Creature *pCreature)
bool QuestAccept_npc_willix_the_importer (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_snufflenose_gopher (Creature *pCreature)
bool EffectDummyCreature_npc_snufflenose_gopher (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_razorfen_kraul ()
Variables
static const float aBoarSpawn [4][3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_WILLIX_THE_IMPORTER
SAY_WILLIX_READY
SAY_WILLIX_1
SAY_WILLIX_2
SAY_WILLIX_3
SAY_WILLIX_4
SAY_WILLIX_5
SAY_WILLIX_6
SAY_WILLIX_7
SAY_WILLIX_END
SAY_WILLIX_AGGRO_1
SAY_WILLIX_AGGRO_2
SAY_WILLIX_AGGRO_3
SAY_WILLIX_AGGRO_4
NPC_RAGING_AGAMAR
Definition at line 36 of file razorfen_kraul.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SNUFFLENOSE_COMMAND
NPC_SNUFFLENOSE_GOPHER
GO_BLUELEAF_TUBBER
Definition at line 157 of file razorfen_kraul.cpp.
Function Documentation
AddSC_razorfen_kraul()
void AddSC_razorfen_kraul ()
Definition at line 267 of file razorfen_kraul.cpp.
References EffectDummyCreature_npc_snufflenose_gopher(), Script::GetAI, GetAI_npc_snufflenose_gopher(), GetAI_npc_willix_the_importer(), Script::Name, Script::pEffectDummyNPC, Script::pQuestAcceptNPC, QuestAccept_npc_willix_the_importer(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_snufflenose_gopher()
bool EffectDummyCreature_npc_snufflenose_gopher (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 237 of file razorfen_kraul.cpp.
References Creature::AI(), EFFECT_INDEX_0, Object::GetEntry(), NPC_SNUFFLENOSE_GOPHER, and SPELL_SNUFFLENOSE_COMMAND.
Referenced by AddSC_razorfen_kraul().
GetAI_npc_snufflenose_gopher()
UnitAI* GetAI_npc_snufflenose_gopher (Creature * pCreature)
Definition at line 232 of file razorfen_kraul.cpp.
Referenced by AddSC_razorfen_kraul().
GetAI_npc_willix_the_importer()
UnitAI* GetAI_npc_willix_the_importer (Creature * pCreature)
Definition at line 132 of file razorfen_kraul.cpp.
Referenced by AddSC_razorfen_kraul().
QuestAccept_npc_willix_the_importer()
bool QuestAccept_npc_willix_the_importer (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 137 of file razorfen_kraul.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_WILLIX_THE_IMPORTER, SAY_WILLIX_READY, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_razorfen_kraul().
Variable Documentation
aBoarSpawn
const float aBoarSpawn[4][3] static
Initial value:
=
{
    {2151.420f, 1733.18f, 52.10f},
    {2144.463f, 1726.89f, 51.93f},
    {1956.433f, 1597.97f, 81.75f},
    {1958.971f, 1599.01f, 81.44f}
}
Definition at line 58 of file razorfen_kraul.cpp.
Referenced by npc_willix_the_importerAI::WaypointReached().