CMaNGOS_WoTLK: redridge_mountains.cpp File Reference
redridge_mountains.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_corporal_keeshan_escortAI
Enumerations
enum {
QUEST_MISSING_IN_ACTION = 219 , SPELL_MOCKING_BLOW = 21008 , SPELL_SHIELD_BASH = 11972 , SAY_CORPORAL_KEESHAN_1 = -1000561 ,
SAY_CORPORAL_KEESHAN_2 = -1000562 , SAY_CORPORAL_KEESHAN_3 = -1000563 , SAY_CORPORAL_KEESHAN_4 = -1000564 , SAY_CORPORAL_KEESHAN_5 = -1000565
}
Functions
UnitAI * GetAI_npc_corporal_keeshan (Creature *pCreature)
bool QuestAccept_npc_corporal_keeshan (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_redridge_mountains ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_MISSING_IN_ACTION
SPELL_MOCKING_BLOW
SPELL_SHIELD_BASH
SAY_CORPORAL_KEESHAN_1
SAY_CORPORAL_KEESHAN_2
SAY_CORPORAL_KEESHAN_3
SAY_CORPORAL_KEESHAN_4
SAY_CORPORAL_KEESHAN_5
Definition at line 34 of file redridge_mountains.cpp.
Function Documentation
AddSC_redridge_mountains()
void AddSC_redridge_mountains ()
Definition at line 143 of file redridge_mountains.cpp.
References Script::GetAI, GetAI_npc_corporal_keeshan(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_corporal_keeshan(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_corporal_keeshan()
UnitAI* GetAI_npc_corporal_keeshan (Creature * pCreature)
Definition at line 130 of file redridge_mountains.cpp.
Referenced by AddSC_redridge_mountains().
QuestAccept_npc_corporal_keeshan()
bool QuestAccept_npc_corporal_keeshan (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 135 of file redridge_mountains.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_MISSING_IN_ACTION, and UnitAI::SendAIEvent().
Referenced by AddSC_redridge_mountains().