CMaNGOS_WoTLK: Relations.cpp File Reference
Relations.cpp File Reference
Relations API for supported Entities.
#include "Server/DBCStores.h"
#include "Entities/Unit.h"
#include "Entities/Player.h"
#include "Entities/Corpse.h"
#include "Entities/GameObject.h"
#include "Entities/DynamicObject.h"
#include "Entities/Vehicle.h"
#include "Globals/ObjectMgr.h"
#include "Tools/Formulas.h"
Functions
static ReputationRank GetFactionReaction (FactionTemplateEntry const *thisTemplate, FactionTemplateEntry const *otherTemplate)
Get faction template to faction tenplate reaction.
static ReputationRank GetFactionReaction (FactionTemplateEntry const *thisTemplate, Unit const *unit)
Get faction template to unit reaction.
Detailed Description
Relations API for supported Entities.
Date
September, 2017
Relations API controls various interactions between entities, such as friendliness or hostility.
Relations API is split into three tiers:
Tier 1 is a direct reverse engineered gameplay logic from the game. It should never be modified with custom logic to be in sync with the client we aim to support. Each function presented here has a counterpart in client for comparision.
Tier 2 is a server-side extension to plug holes left by original client-side perspective. It builds up on previous tier for entities not represented client-side. All functions presented here are required to mimic the look and feel of the original API. No functions in this tier have a real client-side counterpart.
Tier 3 is a custom server-side convinience API for CMaNGOS. This is a stylistically relaxed set of custom wrappers and helpers for various subsystems. All functions presented in this tier are exclusive to the emulator and have no outside influence.
Tier 1 is implied to be "set in stone" as it comes from 1st hand source - the game itself. The only reason Tier 1 API should be ever modified is to fix possible mistakes in reverse engineered code. Any user modifications or additions to Tier 1 which are not coming from client's code should be rejected to preserve overall integrity.
Tiers 2 and 3 are serverside APIs and will be extended in the future as demand arises during actual rollout.
Definition in file Relations.cpp.
Function Documentation
GetFactionReaction() [1/2]
static ReputationRank GetFactionReaction (FactionTemplateEntry const * thisTemplate, FactionTemplateEntry const * otherTemplate) inline static
Get faction template to faction tenplate reaction.
Note
Relations API Tier 1
Client-side counterpart: static function (original symbol name unknown)
Definition at line 108 of file Relations.cpp.
References FactionTemplateEntry::enemyFaction, FactionTemplateEntry::enemyGroupMask, FactionTemplateEntry::faction, FACTION_TEMPLATE_FLAG_HATES_ALL_EXCEPT_FRIENDS, FactionTemplateEntry::factionFlags, FactionTemplateEntry::factionGroupMask, FactionTemplateEntry::friendFaction, FactionTemplateEntry::friendGroupMask, MANGOS_ASSERT, REP_FRIENDLY, REP_HOSTILE, and REP_NEUTRAL.
Referenced by GetFactionReaction(), GameObject::GetReactionTo(), Player::GetReactionTo(), Unit::GetReactionTo(), GameObject::IsEnemy(), and GameObject::IsFriend().
GetFactionReaction() [2/2]
static ReputationRank GetFactionReaction (FactionTemplateEntry const * thisTemplate, Unit const * unit) static
Get faction template to unit reaction.
Note
Relations API Tier 1
Client-side counterpart: static CGUnit_C::UnitReaction(int factionTemplateID, const CGUnit_C *unit) Faction template id was replaced with FactionTemplateEntry ptr for performance, now caller is responsible for lookup Used as static function instead of being a static method of Unit class
Definition at line 162 of file Relations.cpp.
References FactionTemplateEntry::faction, Unit::GetControllingPlayer(), GetFactionReaction(), Unit::GetFactionTemplateEntry(), ReputationMgr::GetRank(), Object::HasFlag(), FactionEntry::HasReputation(), FactionTemplateEntry::IsContestedGuardFaction(), MANGOS_ASSERT, PLAYER_FLAGS, PLAYER_FLAGS_CONTESTED_PVP, REP_HOSTILE, REP_NEUTRAL, sFactionStore, UNIT_FIELD_FLAGS, UNIT_FIELD_FLAGS_2, UNIT_FLAG2_IGNORE_REPUTATION, and UNIT_FLAG_PLAYER_CONTROLLED.