CMaNGOS_WoTLK: Rogue.cpp File Reference
Rogue.cpp File Reference
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct Preparation
struct Stealth
struct VanishRogue
struct SapRogue
struct SetupRogue
struct DirtyDeeds
struct KillingSpreeStorage
struct KillingSpree
struct PreyOnTheWeak
Enumerations
enum { SPELL_DISTRACT = 1725 , SPELL_EARTHBIND = 3600 , SPELL_MASS_DISPEL = 39897 , SPELL_MASS_DISPEL_2 = 32592 }
Functions
void CastHighestStealthRank (Unit *caster)
void LoadRogueScripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_DISTRACT
SPELL_EARTHBIND
SPELL_MASS_DISPEL
SPELL_MASS_DISPEL_2
Definition at line 36 of file Rogue.cpp.
Function Documentation
CastHighestStealthRank()
void CastHighestStealthRank (Unit * caster)
Definition at line 64 of file Rogue.cpp.
References Unit::CastSpell(), Object::IsPlayer(), WorldObject::IsSpellReady(), SQLStorage::LookupEntry(), WorldObject::RemoveSpellCooldown(), sSpellTemplate, and TRIGGERED_OLD_TRIGGERED.
Referenced by VanishRogue::OnCast().
LoadRogueScripts()
void LoadRogueScripts ()
Definition at line 226 of file Rogue.cpp.
Referenced by SpellScriptMgr::LoadScripts().