CMaNGOS_WoTLK: ruins_of_ahnqirajScripts.cpp File Reference
ruins_of_ahnqirajScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct mob_anubisath_guardianAI
Enumerations
enum {
SPELL_METEOR = 24340 , SPELL_PLAGUE = 22997 , SPELL_SHADOW_STORM = 26546 , SPELL_THUNDER_CLAP = 26554 ,
SPELL_REFLECT_ARFR = 13022 , SPELL_REFLECT_FSSH = 19595 , SPELL_ENRAGE = 8599 , SPELL_EXPLODE = 25698 ,
SPELL_SUMMON_ANUB_SWARMGUARD = 17430 , SPELL_SUMMON_ANUB_WARRIOR = 17431 , EMOTE_FRENZY = -1000002 , NPC_ANUB_WARRIOR = 15537 ,
NPC_ANUB_SWARM = 15538
}
Functions
UnitAI * GetAI_mob_anubisath_guardian (Creature *pCreature)
void AddSC_ruins_of_ahnqiraj ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_METEOR
SPELL_PLAGUE
SPELL_SHADOW_STORM
SPELL_THUNDER_CLAP
SPELL_REFLECT_ARFR
SPELL_REFLECT_FSSH
SPELL_ENRAGE
SPELL_EXPLODE
SPELL_SUMMON_ANUB_SWARMGUARD
SPELL_SUMMON_ANUB_WARRIOR
EMOTE_FRENZY
NPC_ANUB_WARRIOR
NPC_ANUB_SWARM
Definition at line 33 of file ruins_of_ahnqirajScripts.cpp.
Function Documentation
AddSC_ruins_of_ahnqiraj()
void AddSC_ruins_of_ahnqiraj ()
Definition at line 163 of file ruins_of_ahnqirajScripts.cpp.
References Script::GetAI, GetAI_mob_anubisath_guardian(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_anubisath_guardian()
UnitAI* GetAI_mob_anubisath_guardian (Creature * pCreature)
Definition at line 158 of file ruins_of_ahnqirajScripts.cpp.
Referenced by AddSC_ruins_of_ahnqiraj().