CMaNGOS_WoTLK: sc_grid_searchers.h File Reference
sc_grid_searchers.h File Reference
#include "Entities/Object.h"
Data Structures
struct ObjectDistanceOrder
struct ObjectDistanceOrderReversed
Functions
GameObject * GetClosestGameObjectWithEntry (WorldObject *source, uint32 entry, float maxSearchRange)
Creature * GetClosestCreatureWithEntry (WorldObject *source, uint32 entry, float maxSearchRange, bool onlyAlive=true, bool onlyDead=false, bool excludeSelf=false)
void GetGameObjectListWithEntryInGrid (GameObjectList &goList, WorldObject *source, uint32 entry, float maxSearchRange)
void GetGameObjectListWithEntryInGrid (GameObjectList &goList, WorldObject *source, std::vector< uint32 > const &entries, float maxSearchRange)
void GetCreatureListWithEntryInGrid (CreatureList &creatureList, WorldObject *source, uint32 entry, float maxSearchRange)
void GetCreatureListWithEntryInGrid (CreatureList &creatureList, WorldObject *source, std::vector< uint32 > const &entries, float maxSearchRange)
void GetPlayerListWithEntryInWorld (PlayerList &playerList, WorldObject *source, float maxSearchRange)
Function Documentation
GetClosestCreatureWithEntry()
Creature* GetClosestCreatureWithEntry (WorldObject * source, uint32 entry, float maxSearchRange, bool onlyAlive = true, bool onlyDead = false, bool excludeSelf = false)
Definition at line 26 of file sc_grid_searchers.cpp.
References Cell::VisitGridObjects().
Referenced by npc_storm_tempered_keeperAI::Aggro(), mob_shadowmoon_soulstealerAI::Aggro(), AreaTrigger_at_ancient_leaf(), AreaTrigger_at_ancient_male_vrykul(), AreaTrigger_at_beggar(), AreaTrigger_at_brewfest_receive_keg(), AreaTrigger_at_brewfest_send_keg(), AreaTrigger_at_commander_dawnforge(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_murkdeep(), AreaTrigger_at_nats_landing(), AreaTrigger_at_nifflevar(), AreaTrigger_at_overlord_drakuru(), AreaTrigger_at_scent_larkorwi(), AreaTrigger_at_sentry_point(), AreaTrigger_at_spearborn_encampment(), AreaTrigger_at_stomach_cthun(), AreaTrigger_at_twiggy_flathead(), AreaTrigger_at_twilight_grove(), boss_janalaiAI::boss_janalaiAI(), boss_terokkAI::boss_terokkAI(), npc_commander_dawnforgeAI::CanStartEvent(), npc_living_flareAI::CheckPortalDist(), npc_theramore_spar_controller::CombatantIntro(), boss_kiljaedenAI::DoActivateDragonOrb(), npc_eris_havenfireAI::DoAttackArchersTarget(), npc_cenarion_sparrowhawkAI::DoFindNearbyStones(), instance_karazhan::DoPrepareChessEvent(), boss_selin_fireheartAI::DoSelectNearestCrystal(), trial_companion_commonAI::DoUseNearbyMountIfCan(), EffectAuraDummy_spell_aura_dummy_npc(), Spell::EffectDummy(), EffectDummyCreature_npc_harpoon_fire_state(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_npc_wants_fruit_credit(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_spell_ooze_flood(), boss_eranikusAI::EnterEvadeMode(), npc_maghar_escortAI::EnterEvadeMode(), npc_sunblade_scoutAI::ExecuteAction(), boss_ouroAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_warlord_kalithreshAI::ExecuteActions(), npc_bashir_flesh_fiendAI::ExecuteActions(), npc_theramore_spar_controller::GetCombatants(), npc_a_special_surpriseAI::GetSpeakerByEntry(), GOQuestAccept_GO_crystal_prison(), GossipHello_npc_colonel_jules(), GossipHello_npc_corrupt_saber(), GOUse_go_cage_door(), GOUse_go_cage_trap(), GOUse_go_containment_sphere(), GOUse_go_elune_fire(), GOUse_go_ethereum_prison(), GOUse_go_ethereum_stasis(), GOUse_go_furbolg_food(), GOUse_go_harbinger_second_trial(), GOUse_go_jump_a_tron(), GOUse_go_naga_brazier(), GOUse_go_ossirian_crystal(), GOUse_go_quest_still_at_it_credit(), GOUse_go_shield_generator(), GOUse_go_stasis_chamber_alpha(), GOUse_go_stasis_chamber_mana_tombs(), GOUse_go_stasis_chamber_shaffar(), ChildTbcAI::HandleAerisLanding(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), npc_theramore_spar_controller::HandleBlueWin(), ChildTbcAI::HandleCallOfTheFarseer(), npc_bonechewer_combatant::HandleEventStart(), ChildTbcAI::HandleHchuuAndTheMushroomPeople(), npc_theramore_spar_controller::HandleMotivation(), ChildTbcAI::HandleNowWhenIGrowUp(), npc_theramore_spar_controller::HandleRedWin(), npc_khadgars_servantAI::HandleStart(), ChildTbcAI::HandleTimeToVisitTheCaverns(), npc_theramore_spar_controller::HandleWin(), npc_bt_battle_sensor::IllidariAttackNearestEnemy(), ItemUse_item_orb_of_draconic_energy(), go_nether_drake_egg_trapAI::JustDespawned(), npc_akamaAI::JustDidDialogueStep(), npc_demolitionist_legosoAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_lich_king_villageAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDied(), npc_vindicator_sedaiAI::JustDied(), npc_dimensiusAI::JustDied(), npc_avatar_of_terokkAI::JustDied(), NecropolisHealthAI::JustDied(), NecroticShard::JustDied(), npc_cultist_engineer::JustDied(), PallidHorrorAI::JustDied(), npc_captured_vanguardAI::JustDied(), boss_thaddiusAddsAI::JustReachedHome(), npc_dawnblade_blood_knight::JustRespawned(), npc_bird_spiritAI::JustRespawned(), go_dragon_head::JustSpawned(), npc_colonel_julesAI::JustSummoned(), mob_ohganAI::KilledUnit(), boss_mandokirAI::KilledUnit(), npc_black_holeAI::MoveInLineOfSight(), npc_theramore_spar_controller::MoveIntoPosition(), npc_shadowlord_deathwailAI::MovementInform(), npc_disobedient_dragonmaw_peonAI::MovementInform(), trial_companion_commonAI::MovementInform(), npc_deadsoul_orb::MovementInform(), npc_living_flareAI::MovementInform(), npc_apexis_flayerAI::MoveToCrystal(), npc_deadsoul_orb::MoveToNextTrigger(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), NpcSpellClick_npc_storm_totem(), spell_lingering_fumes_targetting::OnAfterHit(), instance_temple_of_ahnqiraj::OnCreatureDeath(), HookTentacleTrigger::OnEffectExecute(), spell_tag_troll::OnEffectExecute(), SummonSmokeBeacon::OnEffectExecute(), PowerOfTheBlueFlight::OnEffectExecute(), go_unadorned_spike::OnLootStateChange(), GossipNPCPeriodicTalk::OnPeriodicDummy(), BattleGroundEY::ProcessCaptureEvent(), ProcessEventId_arcanite_buoy(), ProcessEventId_sedai_vision(), ProcessEventId_Soulgrinder(), BattleGroundAV::ProcessPlayerAssaultsPoint(), QuestAccept_npc_mikhail(), QuestAccept_npc_rigger_gizelton(), QuestAcceptGO_crystalline_tear(), npc_anchorite_baradaAI::ReceiveAIEvent(), npc_emilyAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_xiri::ReceiveAIEvent(), npc_simone_the_inconspicuousAI::Reset(), SelectRandomFlameshockerSpawnTarget(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), npc_thunder_orbAI::SpellHit(), npc_fel_cannon::SpellHit(), NecropolisRelayAI::SpellHit(), NecropolisProxyAI::SpellHit(), npc_warp_gate::SpellHit(), mob_enslaved_netherwing_drakeAI::SpellHit(), npc_shadowlord_deathwailAI::SpellHitTarget(), boss_heiganAI::StartEruptions(), npc_lord_illidan_stormrageAI::StartEvent(), npc_dirty_larryAI::StartEvent(), world_map_outland::StartManaSlaveEvent(), npc_theramore_spar_controller::StartSparring(), boss_heiganAI::StopEruptions(), boss_flame_leviathanAI::SummonedMovementInform(), npc_simone_the_inconspicuousAI::Transform(), npc_krazAI::UpdateAI(), npc_bonechewer_combatant::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), go_containment::UpdateAI(), npc_blackwing_orbAI::UpdateAI(), npc_ancient_male_vrykulAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), go_vehicle_teleporter::UpdateAI(), npc_vimgol_AI::UpdateAI(), npc_vimgol_middle_bunnyAI::UpdateAI(), npc_supplicantAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), mob_enslaved_netherwing_drakeAI::UpdateAI(), go_ai_fixed_trap::UpdateAI(), npc_khadgars_servantAI::UpdateEscortAI(), npc_maxx_a_million_escortAI::UpdateEscortAI(), npc_deathstalker_erlandAI::WaypointReached(), npc_kineloryAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_proudhoofAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_father_kamarosAI::WaypointReached(), npc_ancestral_wolfAI::WaypointReached(), npc_bessyAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), npc_drijyaAI::WaypointReached(), and npc_khadgars_servantAI::WaypointReached().
GetClosestGameObjectWithEntry()
GameObject* GetClosestGameObjectWithEntry (WorldObject * source, uint32 entry, float maxSearchRange)
Definition at line 13 of file sc_grid_searchers.cpp.
References Cell::VisitGridObjects().
Referenced by AreaTrigger_at_coilfang_waterfall(), npc_cage_trap_triggerAI::CorpseRemoved(), npc_death_knight_initiateAI::DamageTaken(), npc_ranshallaAI::DoChannelTorchSpell(), npc_harrison_jonesAI::DoCleanChamberRoom(), npc_scarlet_courierAI::DoDespawnTree(), dummy_dragonAI::DoEjectTwilightPlayersIfCan(), dummy_dragonAI::DoOpenPortal(), boss_razorscaleAI::DoRepairHarpoon(), EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), Spell::EffectDummy(), EffectDummyCreature_npc_bot_trigger(), EffectDummyCreature_npc_harpoon_fire_state(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), npc_lazy_peonAI::GoLumberPile(), GossipHello_npc_field_marshal_afrasiabi(), GossipHello_npc_high_overlord_saurfang(), GossipHello_npc_major_mattingly(), GossipHello_npc_overlord_runthalak(), GOUse_go_mausoleum_door(), GOUse_go_mausoleum_trigger(), npc_razorthorn_ravager_pet::HandleAnimations(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), npc_smolderwing::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), boss_mawsAI::JustDied(), dummy_dragonAI::JustDied(), npc_cultist_engineer::JustDied(), npc_death_knight_initiateAI::JustReachedHome(), boss_sartharionAI::JustReachedHome(), dummy_dragonAI::JustReachedHome(), npc_melizza_brimbuzzleAI::JustStartedEscort(), npc_lurgglbrAI::JustStartedEscort(), npc_isla_starmaneAI::JustStartedEscort(), npc_bloodmaul_stout_triggerAI::MoveInLineOfSight(), npc_shadowlord_deathwailAI::MovementInform(), npc_cenarion_sparrowhawkAI::MovementInform(), npc_nesingwary_trapperAI::MovementInform(), NecroticShard::NecroticShard(), spell_crystal_spike_visual_aura::OnApply(), instance_icecrown_citadel::OnCreatureDeath(), world_map_outland::OnCreatureRespawn(), ProcessEventId_arcanite_buoy(), ProcessEventId_event_antalarion_statue_activation(), QuestAccept_npc_rinji(), boss_ossirianAI::ReceiveAIEvent(), npc_captured_arkonarinAI::ReceiveAIEvent(), npc_harrison_jonesAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_manaforge_control_consoleAI::ResetControlConsoleAndDespawn(), boss_ossirianAI::SpellHit(), npc_ashliAI::SpellHitTarget(), SummonCultists(), boss_lich_king_horAI::SummonedCreatureJustDied(), npc_kyle_the_frenziedAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), boss_mawsAI::UpdateAI(), npc_tipsy_mcmanusAI::UpdateAI(), npc_bot_triggerAI::UpdateAI(), npc_danath_trollbaneAI::UpdateAI(), npc_nazgrelAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), npc_domesticated_felboarAI::UpdateAI(), npc_belnistraszAI::UpdateEscortAI(), npc_ranger_lilathaAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointReached(), npc_muglashAI::WaypointReached(), npc_stinky_ignatzAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), and npc_galen_goodwardAI::WaypointStart().
GetCreatureListWithEntryInGrid() [1/2]
void GetCreatureListWithEntryInGrid (CreatureList & creatureList, WorldObject * source, std::vector< uint32 > const & entries, float maxSearchRange)
Definition at line 62 of file sc_grid_searchers.cpp.
References Cell::VisitGridObjects().
GetCreatureListWithEntryInGrid() [2/2]
void GetCreatureListWithEntryInGrid (CreatureList & creatureList, WorldObject * source, uint32 entry, float maxSearchRange)
Definition at line 54 of file sc_grid_searchers.cpp.
References Cell::VisitGridObjects().
Referenced by npc_anubisath_sentinelAI::Aggro(), AreaTrigger_at_lights_hammer(), AreaTrigger_at_underbelly_a(), AreaTrigger_at_underbelly_h(), npc_vimgol_middle_bunnyAI::CastBunnySpell(), npc_private_hendelAI::DamageTaken(), world_map_outland::DespawnCrystalforgeGuardians(), DespawnCultists(), DespawnEventDoodads(), DespawnShadowsOfDoom(), npc_colonel_julesAI::DespawnSummons(), npc_harrison_jonesAI::DoCleanChamberRoom(), boss_janalaiAI::DoCreateFireWall(), npc_wildaAI::DoDespawnSpirits(), boss_tethyrAI::DoEncounterCleanup(), npc_wildaAI::DoFreeSpirits(), go_elemental_rift::DoRespawnElementalsIfCan(), instance_ruins_of_ahnqiraj::DoSortArmyWaves(), npc_Shattered_Hand_Scout::DoStartRunning(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), npc_Shattered_Hand_Scout::DoZealotsEmoteReady(), EffectScriptEffectCreature_npc_putricide(), npc_bt_battle_sensor::FindFormationMarkers(), GetFindersAmount(), npc_chess_piece_genericAI::GetMovementSquare(), go_vehicle_teleporter::GetTeleportTarget(), GossipSelect_go_manaforge(), GossipSelect_npc_saeed(), GOUse_go_scourge_enclosure(), GOUse_go_wooden_door(), boss_vaelastraszAI::HandleIntro(), NecroticShard::HandleShardMinionSpawnerSmall(), ChildTbcAI::HandleTripToTheDarkPortal(), HasMinion(), mob_arugal_voidwalkerAI::InitVoidWalkersGroup(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), boss_coren_direbrewAI::JustDied(), boss_golemaggAI::JustDied(), boss_tethyrAI::JustDied(), boss_doomwalkerAI::JustRespawned(), npc_letollAI::JustStartedEscort(), npc_harrison_jonesAI::JustSummoned(), boss_scarlet_commander_mograineAI::MograineCallForHelp(), npc_king_ymironAI::MoveInLineOfSight(), boss_tethyrAI::MovementInform(), boss_lady_vashjAI::MovementInform(), NpcSpellClick_npc_obedienceCrystal(), SapphironBlizzardInit::OnEffectExecute(), ZombieChowSearch::OnPeriodicTrigger(), ProcessEventId_event_go_tower_destroy(), ProcessEventId_event_go_ulduar_tower(), ProcessEventId_event_purify_food(), QuestAccept_npc_private_hendel(), npc_proudhoofAI::ReceiveAIEvent(), npc_supplicantAI::ReceiveAIEvent(), npc_shadowlord_deathwailAI::SoulstealerEnteredCombat(), boss_kelthuzadAI::SpellHit(), UncommonMinionspawner(), guard_hallows_end_helperAI::UpdateAI(), npc_firecrackers_bunnyAI::UpdateAI(), mob_big_oozeAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_salhadaarAI::UpdateAI(), npc_energy_ballAI::UpdateAI(), npc_hurley_blackbreathAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_apothecary_hanesAI::WaypointReached(), and npc_squad_leaderAI::WaypointReached().
GetGameObjectListWithEntryInGrid() [1/2]
void GetGameObjectListWithEntryInGrid (GameObjectList & goList, WorldObject * source, std::vector< uint32 > const & entries, float maxSearchRange)
Definition at line 46 of file sc_grid_searchers.cpp.
References Cell::VisitGridObjects().
GetGameObjectListWithEntryInGrid() [2/2]
void GetGameObjectListWithEntryInGrid (GameObjectList & goList, WorldObject * source, uint32 entry, float maxSearchRange)
Definition at line 38 of file sc_grid_searchers.cpp.
References WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), and Cell::VisitGridObjects().
Referenced by DespawnEventDoodads(), DespawnNecropolis(), boss_tethyrAI::DoEncounterCleanup(), npc_felhound_trackerAI::DoFindNewCrystal(), npc_rookery_hatcherAI::DoFindNewEgg(), npc_snufflenose_gopherAI::DoFindNewTubber(), npc_demolitionist_legosoAI::DoRespawnFires(), npc_demolitionist_legosoAI::DoRespawnObjects(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), boss_tethyrAI::MovementInform(), HakkarSummoned::OnEffectExecute(), LivingFlareDetonator::OnEffectExecute(), npc_obelisk_triggerAI::Reset(), npc_ashliAI::SpellHitTarget(), SummonCultists(), npc_brain_yogg_saronAI::SummonedCreatureJustDied(), npc_harkorAI::UpdateAI(), npc_krazAI::UpdateAI(), npc_obelisk_triggerAI::UpdateAI(), npc_belnistraszAI::UpdateEscortAI(), and npc_ranshallaAI::WaypointReached().
GetPlayerListWithEntryInWorld()
void GetPlayerListWithEntryInWorld (PlayerList & playerList, WorldObject * source, float maxSearchRange)
Definition at line 70 of file sc_grid_searchers.cpp.
References Cell::VisitWorldObjects().
Referenced by AttackPlayerWithQuest(), boss_skeramAI::ExecuteAction(), npc_avatar_of_terokkAI::JustDied(), ThaddiusCharge::OnPeriodicTrigger(), npc_vimgol_middle_bunnyAI::playersInsideCircles(), Aura::TriggerSpell(), and npc_salhadaarAI::UpdateAI().