CMaNGOS_WoTLK: scholomance.cpp File Reference
scholomance.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_spectral_tutorAI
Enumerations
enum {
SPELL_IMAGE_PROJECTION = 17651 , SPELL_IMAGE_PROJECTION_HEAL = 17652 , SPELL_IMAGE_PROJECTION_SUMMON = 17653 , SPELL_MANA_BURN = 17630 ,
SPELL_SILENCE = 12528
}
Functions
UnitAI * GetAI_npc_spectral_tutor (Creature *pCreature)
void AddSC_scholomance ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_IMAGE_PROJECTION
SPELL_IMAGE_PROJECTION_HEAL
SPELL_IMAGE_PROJECTION_SUMMON
SPELL_MANA_BURN
SPELL_SILENCE
Definition at line 34 of file scholomance.cpp.
Function Documentation
AddSC_scholomance()
void AddSC_scholomance ()
Definition at line 124 of file scholomance.cpp.
References Script::GetAI, GetAI_npc_spectral_tutor(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_spectral_tutor()
UnitAI* GetAI_npc_spectral_tutor (Creature * pCreature)
Definition at line 119 of file scholomance.cpp.
Referenced by AddSC_scholomance().