CMaNGOS_WoTLK: scourge_invasion.cpp File Reference
scourge_invasion.cpp File Reference
#include "scourge_invasion.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "World/WorldStateDefines.h"
#include "Grids/CellImpl.h"
#include "GameEvents/GameEventMgr.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "World/World.h"
#include <cmath>
Data Structures
class GoCircle
class GoNecropolis
struct MouthAI
struct NecropolisAI
struct NecropolisHealthAI
struct NecropolisProxyAI
struct NecropolisRelayAI
struct NecroticShard
struct MinionspawnerAI
struct npc_cultist_engineer
struct SummonBoss
struct ScourgeMinion
struct PallidHorrorAI
struct DespawnerSelf
struct CommuniqueTrigger
Functions
uint32 GetCampType (Creature *unit)
bool IsGuardOrBoss (Unit *unit)
Unit * SelectRandomFlameshockerSpawnTarget (Creature *unit, Creature *except, float radius)
void ChangeZoneEventStatus (Creature *mouth, bool on)
void DespawnEventDoodads (Creature *shard)
void DespawnNecropolis (Unit *despawner)
void SummonCultists (Unit *shard)
void DespawnCultists (Unit *despawner)
void DespawnShadowsOfDoom (Unit *despawner)
uint32 HasMinion (Creature *summoner, float)
bool UncommonMinionspawner (Creature *pSummoner)
uint32 GetFindersAmount (Creature *shard)
void AddSC_scourge_invasion ()
Function Documentation
AddSC_scourge_invasion()
void AddSC_scourge_invasion ()
Definition at line 1314 of file scourge_invasion.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
ChangeZoneEventStatus()
void ChangeZoneEventStatus (Creature * mouth, bool on)
Definition at line 75 of file scourge_invasion.cpp.
References GAME_EVENT_SCOURGE_INVASION_AZSHARA, GAME_EVENT_SCOURGE_INVASION_BLASTED_LANDS, GAME_EVENT_SCOURGE_INVASION_BURNING_STEPPES, GAME_EVENT_SCOURGE_INVASION_EASTERN_PLAGUELANDS, GAME_EVENT_SCOURGE_INVASION_TANARIS, GAME_EVENT_SCOURGE_INVASION_WINTERSPRING, WorldObject::GetZoneId(), SAVE_ID_SCOURGE_INVASION, sGameEventMgr, sWorld, sWorldState, ZONEID_AZSHARA, ZONEID_BLASTED_LANDS, ZONEID_BURNING_STEPPES, ZONEID_EASTERN_PLAGUELANDS, ZONEID_TANARIS, and ZONEID_WINTERSPRING.
Referenced by MouthAI::ReceiveAIEvent().
DespawnCultists()
void DespawnCultists (Unit * despawner)
Definition at line 200 of file scourge_invasion.cpp.
References GetCreatureListWithEntryInGrid(), INSPECT_DISTANCE, and NPC_CULTIST_ENGINEER.
Referenced by NecroticShard::JustDied().
DespawnEventDoodads()
void DespawnEventDoodads (Creature * shard)
Definition at line 144 of file scourge_invasion.cpp.
References GetCreatureListWithEntryInGrid(), GetGameObjectListWithEntryInGrid(), GO_SKULLPILE_01, GO_SKULLPILE_02, GO_SKULLPILE_03, GO_SKULLPILE_04, GO_SUMMON_CIRCLE, GO_SUMMONER_SHIELD, GO_UNDEAD_FIRE, GO_UNDEAD_FIRE_AURA, and NPC_SCOURGE_INVASION_MINION_FINDER.
Referenced by NecroticShard::JustDied(), and NecroticShard::NecroticShard().
DespawnNecropolis()
void DespawnNecropolis (Unit * despawner)
Definition at line 163 of file scourge_invasion.cpp.
References ATTACK_DISTANCE, GetGameObjectListWithEntryInGrid(), GO_NECROPOLIS_BIG, GO_NECROPOLIS_HUGE, GO_NECROPOLIS_MEDIUM, GO_NECROPOLIS_SMALL, and GO_NECROPOLIS_TINY.
Referenced by NecropolisHealthAI::SpellHitTarget().
DespawnShadowsOfDoom()
void DespawnShadowsOfDoom (Unit * despawner)
Definition at line 212 of file scourge_invasion.cpp.
References GetCreatureListWithEntryInGrid(), and NPC_SHADOW_OF_DOOM.
GetCampType()
uint32 GetCampType (Creature * unit) inline
Definition at line 32 of file scourge_invasion.cpp.
References Unit::HasAura(), SPELL_CAMP_TYPE_GHOST_GHOUL, SPELL_CAMP_TYPE_GHOST_SKELETON, and SPELL_CAMP_TYPE_GHOUL_SKELETON.
Referenced by NecroticShard::SpellHit().
GetFindersAmount()
uint32 GetFindersAmount (Creature * shard)
Definition at line 261 of file scourge_invasion.cpp.
References GetCreatureListWithEntryInGrid(), and NPC_SCOURGE_INVASION_MINION_FINDER.
Referenced by NecroticShard::SpellHit().
HasMinion()
uint32 HasMinion (Creature * summoner, float)
Definition at line 224 of file scourge_invasion.cpp.
References ATTACK_DISTANCE, GetCreatureListWithEntryInGrid(), NPC_BONE_WITCH, NPC_GHOUL_BERSERKER, NPC_LUMBERING_HORROR, NPC_SKELETAL_SHOCKTROOPER, NPC_SPECTRAL_SOLDIER, and NPC_SPIRIT_OF_THE_DAMNED.
Referenced by NecroticShard::HandleShardMinionSpawnerSmall(), and NecroticShard::SpellHit().
IsGuardOrBoss()
bool IsGuardOrBoss (Unit * unit) inline
Definition at line 34 of file scourge_invasion.cpp.
References Object::GetEntry(), NPC_DEATHGUARD_ELITE, NPC_HIGHLORD_BOLVAR_FORDRAGON, NPC_LADY_SYLVANAS_WINDRUNNER, NPC_ROYAL_DREADGUARD, NPC_STORMWIND_CITY_GUARD, NPC_STORMWIND_ROYAL_GUARD, NPC_UNDERCITY_ELITE_GUARDIAN, NPC_UNDERCITY_GUARDIAN, and NPC_VARIMATHRAS.
Referenced by ScourgeMinion::MoveInLineOfSight(), and PallidHorrorAI::MoveInLineOfSight().
SelectRandomFlameshockerSpawnTarget()
Unit* SelectRandomFlameshockerSpawnTarget (Creature * unit, Creature * except, float radius)
Definition at line 39 of file scourge_invasion.cpp.
References Unit::CanAttack(), GetClosestCreatureWithEntry(), GetRandomGenerator(), WorldObject::GetZoneId(), NPC_FLAMESHOCKER, VISIBILITY_DISTANCE_TINY, and Cell::VisitAllObjects().
Referenced by PallidHorrorAI::ExecuteAction().
SummonCultists()
void SummonCultists (Unit * shard)
Definition at line 174 of file scourge_invasion.cpp.
References AI_EVENT_CUSTOM_A, CONTACT_DISTANCE, GetClosestGameObjectWithEntry(), GetGameObjectListWithEntryInGrid(), GO_SUMMON_CIRCLE, GO_SUMMONER_SHIELD, HOUR, IN_MILLISECONDS, INSPECT_DISTANCE, M_PI_F, NPC_CULTIST_ENGINEER, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, and WorldObject::UpdateGroundPositionZ().
UncommonMinionspawner()
bool UncommonMinionspawner (Creature * pSummoner)
Definition at line 239 of file scourge_invasion.cpp.
References GetCreatureListWithEntryInGrid(), NPC_BONE_WITCH, NPC_LUMBERING_HORROR, NPC_SPIRIT_OF_THE_DAMNED, and urand().