CMaNGOS_WoTLK: ScriptLoader.cpp File Reference
ScriptLoader.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Functions
void AddSC_battleground ()
void AddSC_example_creature ()
void AddSC_example_escort ()
void AddSC_example_gossip_codebox ()
void AddSC_example_misc ()
void AddSC_areatrigger_scripts ()
void AddSC_bosses_emerald_dragons ()
void AddSC_generic_creature ()
void AddSC_go_scripts ()
void AddSC_guards ()
void AddSC_item_scripts ()
void AddSC_item_scripts_wotlk ()
void AddSC_npc_professions ()
void AddSC_npcs_special ()
void AddSC_quests_scripts ()
void AddSC_spell_scripts ()
void AddSC_spell_scripts_wotlk ()
void AddSC_world_map_scripts ()
void AddSC_boss_highlord_kruul ()
void AddSC_war_effort ()
void AddSC_scourge_invasion ()
void AddSC_lunar_festival ()
void AddSC_suns_reach_reclamation ()
void AddSC_world_map_ebon_hold ()
void AddSC_shade_of_the_horseman ()
void AddSC_childrens_week_tbc ()
void AddSC_midsummer_festival ()
void AddSC_hallows_end ()
void AddSC_brewfest ()
void AddSC_blackrock_depths ()
void AddSC_boss_ambassador_flamelash ()
void AddSC_boss_coren_direbrew ()
void AddSC_boss_draganthaurissan ()
void AddSC_boss_general_angerforge ()
void AddSC_boss_high_interrogator_gerstahn ()
void AddSC_instance_blackrock_depths ()
void AddSC_boss_overlordwyrmthalak ()
void AddSC_boss_pyroguard_emberseer ()
void AddSC_boss_gyth ()
void AddSC_instance_blackrock_spire ()
void AddSC_boss_razorgore ()
void AddSC_boss_vaelastrasz ()
void AddSC_boss_broodlord ()
void AddSC_boss_firemaw ()
void AddSC_boss_ebonroc ()
void AddSC_boss_flamegor ()
void AddSC_boss_chromaggus ()
void AddSC_boss_nefarian ()
void AddSC_boss_victor_nefarius ()
void AddSC_instance_blackwing_lair ()
void AddSC_boss_mr_smite ()
void AddSC_deadmines ()
void AddSC_instance_deadmines ()
void AddSC_gnomeregan ()
void AddSC_boss_thermaplugg ()
void AddSC_instance_gnomeregan ()
void AddSC_boss_attumen ()
void AddSC_boss_curator ()
void AddSC_boss_maiden_of_virtue ()
void AddSC_boss_shade_of_aran ()
void AddSC_boss_netherspite ()
void AddSC_boss_nightbane ()
void AddSC_boss_prince_malchezaar ()
void AddSC_boss_terestian_illhoof ()
void AddSC_boss_moroes ()
void AddSC_bosses_opera ()
void AddSC_chess_event ()
void AddSC_instance_karazhan ()
void AddSC_karazhan ()
void AddSC_boss_felblood_kaelthas ()
void AddSC_boss_selin_fireheart ()
void AddSC_boss_vexallus ()
void AddSC_boss_priestess_delrissa ()
void AddSC_instance_magisters_terrace ()
void AddSC_magisters_terrace ()
void AddSC_boss_lucifron ()
void AddSC_boss_magmadar ()
void AddSC_boss_gehennas ()
void AddSC_boss_garr ()
void AddSC_boss_baron_geddon ()
void AddSC_boss_shazzrah ()
void AddSC_boss_golemagg ()
void AddSC_boss_sulfuron ()
void AddSC_boss_majordomo ()
void AddSC_boss_ragnaros ()
void AddSC_instance_molten_core ()
void AddSC_molten_core ()
void AddSC_ebon_hold ()
void AddSC_boss_arcanist_doan ()
void AddSC_boss_herod ()
void AddSC_boss_mograine_and_whitemane ()
void AddSC_boss_headless_horseman ()
void AddSC_instance_scarlet_monastery ()
void AddSC_boss_darkmaster_gandling ()
void AddSC_boss_jandicebarov ()
void AddSC_instance_scholomance ()
void AddSC_scholomance ()
void AddSC_boss_hummel ()
void AddSC_shadowfang_keep ()
void AddSC_instance_shadowfang_keep ()
void AddSC_boss_maleki_the_pallid ()
void AddSC_boss_cannon_master_willey ()
void AddSC_boss_baroness_anastari ()
void AddSC_boss_dathrohan_balnazzar ()
void AddSC_boss_order_of_silver_hand ()
void AddSC_instance_stratholme ()
void AddSC_stratholme ()
void AddSC_instance_sunken_temple ()
void AddSC_sunken_temple ()
void AddSC_boss_brutallus ()
void AddSC_boss_eredar_twins ()
void AddSC_boss_felmyst ()
void AddSC_boss_kalecgos ()
void AddSC_boss_kiljaeden ()
void AddSC_boss_muru ()
void AddSC_instance_sunwell_plateau ()
void AddSC_sunwell_plateau ()
void AddSC_boss_archaedas ()
void AddSC_instance_uldaman ()
void AddSC_uldaman ()
void AddSC_boss_akilzon ()
void AddSC_boss_halazzi ()
void AddSC_boss_janalai ()
void AddSC_boss_malacrass ()
void AddSC_boss_nalorakk ()
void AddSC_instance_zulaman ()
void AddSC_zulaman ()
void AddSC_boss_zuljin ()
void AddSC_boss_arlokk ()
void AddSC_boss_hakkar ()
void AddSC_boss_jeklik ()
void AddSC_boss_mandokir ()
void AddSC_boss_marli ()
void AddSC_boss_ouro ()
void AddSC_boss_renataki ()
void AddSC_boss_thekal ()
void AddSC_boss_venoxis ()
void AddSC_instance_zulgurub ()
void AddSC_zulgurub ()
void AddSC_alterac_mountains ()
void AddSC_arathi_highlands ()
void AddSC_blasted_lands ()
void AddSC_boss_kazzakAI ()
void AddSC_burning_steppes ()
void AddSC_dun_morogh ()
void AddSC_eastern_plaguelands ()
void AddSC_elwynn_forest ()
void AddSC_eversong_woods ()
void AddSC_ghostlands ()
void AddSC_hinterlands ()
void AddSC_ironforge ()
void AddSC_isle_of_queldanas ()
void AddSC_loch_modan ()
void AddSC_redridge_mountains ()
void AddSC_searing_gorge ()
void AddSC_silvermoon_city ()
void AddSC_silverpine_forest ()
void AddSC_stormwind_city ()
void AddSC_stranglethorn_vale ()
void AddSC_swamp_of_sorrows ()
void AddSC_tirisfal_glades ()
void AddSC_undercity ()
void AddSC_western_plaguelands ()
void AddSC_westfall ()
void AddSC_wetlands ()
void AddSC_world_eastern_kingdoms ()
void AddSC_instance_blackfathom_deeps ()
void AddSC_boss_aeonus ()
void AddSC_boss_chrono_lord_deja ()
void AddSC_boss_temporus ()
void AddSC_dark_portal ()
void AddSC_instance_dark_portal ()
void AddSC_hyjal ()
void AddSC_boss_archimonde ()
void AddSC_boss_anetheron ()
void AddSC_boss_azgalor ()
void AddSC_boss_kazrogal ()
void AddSC_boss_rage_winterchill ()
void AddSC_instance_mount_hyjal ()
void AddSC_instance_old_hillsbrad ()
void AddSC_old_hillsbrad ()
void AddSC_culling_of_stratholme ()
void AddSC_instance_culling_of_stratholme ()
void AddSC_dire_maul ()
void AddSC_instance_dire_maul ()
void AddSC_instance_maraudon ()
void AddSC_boss_noxxion ()
void AddSC_boss_onyxia ()
void AddSC_instance_onyxias_lair ()
void AddSC_instance_razorfen_downs ()
void AddSC_razorfen_downs ()
void AddSC_instance_razorfen_kraul ()
void AddSC_razorfen_kraul ()
void AddSC_boss_ayamiss ()
void AddSC_boss_buru ()
void AddSC_boss_kurinnaxx ()
void AddSC_boss_ossirian ()
void AddSC_boss_moam ()
void AddSC_boss_rajaxx ()
void AddSC_ruins_of_ahnqiraj ()
void AddSC_instance_ruins_of_ahnqiraj ()
void AddSC_boss_cthun ()
void AddSC_boss_fankriss ()
void AddSC_boss_huhuran ()
void AddSC_bug_trio ()
void AddSC_boss_sartura ()
void AddSC_boss_skeram ()
void AddSC_boss_twinemperors ()
void AddSC_boss_viscidus ()
void AddSC_mob_anubisath_sentinel ()
void AddSC_instance_temple_of_ahnqiraj ()
void AddSC_instance_wailing_caverns ()
void AddSC_wailing_caverns ()
void AddSC_boss_zumrah ()
void AddSC_instance_zulfarrak ()
void AddSC_zulfarrak ()
void AddSC_ashenvale ()
void AddSC_azshara ()
void AddSC_azuremyst_isle ()
void AddSC_bloodmyst_isle ()
void AddSC_boss_azuregos ()
void AddSC_darkshore ()
void AddSC_desolace ()
void AddSC_durotar ()
void AddSC_dustwallow_marsh ()
void AddSC_felwood ()
void AddSC_feralas ()
void AddSC_moonglade ()
void AddSC_mulgore ()
void AddSC_orgrimmar ()
void AddSC_silithus ()
void AddSC_stonetalon_mountains ()
void AddSC_tanaris ()
void AddSC_teldrassil ()
void AddSC_the_barrens ()
void AddSC_thousand_needles ()
void AddSC_thunder_bluff ()
void AddSC_ungoro_crater ()
void AddSC_winterspring ()
void AddSC_world_kalimdor ()
void AddSC_world_northrend ()
void AddSC_boss_amanitar ()
void AddSC_boss_jedoga ()
void AddSC_boss_nadox ()
void AddSC_boss_taldaram ()
void AddSC_boss_volazj ()
void AddSC_instance_ahnkahet ()
void AddSC_boss_anubarak ()
void AddSC_boss_hadronox ()
void AddSC_boss_krikthir ()
void AddSC_instance_azjol_nerub ()
void AddSC_boss_argent_challenge ()
void AddSC_boss_black_knight ()
void AddSC_boss_grand_champions ()
void AddSC_instance_trial_of_the_champion ()
void AddSC_trial_of_the_champion ()
void AddSC_boss_anubarak_trial ()
void AddSC_boss_faction_champions ()
void AddSC_boss_jaraxxus ()
void AddSC_instance_trial_of_the_crusader ()
void AddSC_northrend_beasts ()
void AddSC_trial_of_the_crusader ()
void AddSC_twin_valkyr ()
void AddSC_boss_novos ()
void AddSC_boss_tharonja ()
void AddSC_boss_trollgore ()
void AddSC_instance_draktharon_keep ()
void AddSC_boss_colossus ()
void AddSC_boss_eck ()
void AddSC_boss_galdarah ()
void AddSC_boss_moorabi ()
void AddSC_boss_sladran ()
void AddSC_instance_gundrak ()
void AddSC_boss_bronjahm ()
void AddSC_boss_devourer_of_souls ()
void AddSC_instance_forge_of_souls ()
void AddSC_boss_lich_king ()
void AddSC_halls_of_reflection ()
void AddSC_instance_halls_of_reflection ()
void AddSC_boss_garfrost ()
void AddSC_boss_krick_and_ick ()
void AddSC_boss_tyrannus ()
void AddSC_instance_pit_of_saron ()
void AddSC_pit_of_saron ()
void AddSC_blood_prince_council ()
void AddSC_boss_blood_queen_lanathel ()
void AddSC_boss_deathbringer_saurfang ()
void AddSC_boss_festergut ()
void AddSC_boss_lady_deathwhisper ()
void AddSC_boss_lord_marrowgar ()
void AddSC_boss_professor_putricide ()
void AddSC_boss_rotface ()
void AddSC_boss_sindragosa ()
void AddSC_boss_the_lich_king ()
void AddSC_boss_valithria_dreamwalker ()
void AddSC_gunship_battle ()
void AddSC_icecrown_citadel ()
void AddSC_instance_icecrown_citadel ()
void AddSC_boss_anubrekhan ()
void AddSC_boss_four_horsemen ()
void AddSC_boss_faerlina ()
void AddSC_boss_gluth ()
void AddSC_boss_gothik ()
void AddSC_boss_grobbulus ()
void AddSC_boss_kelthuzad ()
void AddSC_boss_loatheb ()
void AddSC_boss_maexxna ()
void AddSC_boss_noth ()
void AddSC_boss_heigan ()
void AddSC_boss_patchwerk ()
void AddSC_boss_razuvious ()
void AddSC_boss_sapphiron ()
void AddSC_boss_thaddius ()
void AddSC_instance_naxxramas ()
void AddSC_naxxramas ()
void AddSC_boss_malygos ()
void AddSC_instance_eye_of_eternity ()
void AddSC_boss_anomalus ()
void AddSC_boss_keristrasza ()
void AddSC_boss_ormorok ()
void AddSC_boss_telestra ()
void AddSC_instance_nexus ()
void AddSC_boss_eregos ()
void AddSC_boss_urom ()
void AddSC_boss_varos ()
void AddSC_instance_oculus ()
void AddSC_oculus ()
void AddSC_boss_sartharion ()
void AddSC_instance_obsidian_sanctum ()
void AddSC_boss_baltharus ()
void AddSC_boss_halion ()
void AddSC_boss_saviana ()
void AddSC_boss_zarithrian ()
void AddSC_instance_ruby_sanctum ()
void AddSC_ruby_sanctum ()
void AddSC_boss_bjarngrim ()
void AddSC_boss_ionar ()
void AddSC_boss_loken ()
void AddSC_boss_volkhan ()
void AddSC_instance_halls_of_lightning ()
void AddSC_boss_sjonnir ()
void AddSC_halls_of_stone ()
void AddSC_instance_halls_of_stone ()
void AddSC_boss_assembly_of_iron ()
void AddSC_boss_algalon ()
void AddSC_boss_auriaya ()
void AddSC_boss_flame_leviathan ()
void AddSC_boss_freya ()
void AddSC_boss_general_vezax ()
void AddSC_boss_hodir ()
void AddSC_boss_ignis ()
void AddSC_boss_kologarn ()
void AddSC_boss_mimiron ()
void AddSC_boss_razorscale ()
void AddSC_boss_thorim ()
void AddSC_boss_xt_002 ()
void AddSC_boss_yogg_saron ()
void AddSC_instance_ulduar ()
void AddSC_ulduar ()
void AddSC_boss_ingvar ()
void AddSC_boss_keleseth ()
void AddSC_instance_utgarde_keep ()
void AddSC_utgarde_keep ()
void AddSC_boss_gortok ()
void AddSC_boss_skadi ()
void AddSC_boss_svala ()
void AddSC_boss_ymiron ()
void AddSC_instance_pinnacle ()
void AddSC_boss_archavon ()
void AddSC_boss_emalon ()
void AddSC_boss_koralon ()
void AddSC_boss_toravon ()
void AddSC_instance_vault_of_archavon ()
void AddSC_boss_ichoron ()
void AddSC_boss_xevozz ()
void AddSC_instance_violet_hold ()
void AddSC_violet_hold ()
void AddSC_borean_tundra ()
void AddSC_dalaran ()
void AddSC_dragonblight ()
void AddSC_grizzly_hills ()
void AddSC_howling_fjord ()
void AddSC_icecrown ()
void AddSC_sholazar_basin ()
void AddSC_storm_peaks ()
void AddSC_wintergrasp ()
void AddSC_zuldrak ()
void AddSC_boss_exarch_maladaar ()
void AddSC_boss_shirrak ()
void AddSC_boss_nexusprince_shaffar ()
void AddSC_boss_pandemonius ()
void AddSC_mana_tombs ()
void AddSC_boss_yor ()
void AddSC_boss_anzu ()
void AddSC_boss_darkweaver_syth ()
void AddSC_boss_talon_king_ikiss ()
void AddSC_instance_sethekk_halls ()
void AddSC_boss_ambassador_hellmaw ()
void AddSC_boss_blackheart_the_inciter ()
void AddSC_boss_grandmaster_vorpil ()
void AddSC_boss_murmur ()
void AddSC_instance_shadow_labyrinth ()
void AddSC_black_temple ()
void AddSC_boss_illidan ()
void AddSC_boss_shade_of_akama ()
void AddSC_boss_supremus ()
void AddSC_boss_gurtogg_bloodboil ()
void AddSC_boss_mother_shahraz ()
void AddSC_boss_reliquary_of_souls ()
void AddSC_boss_teron_gorefiend ()
void AddSC_boss_najentus ()
void AddSC_boss_illidari_council ()
void AddSC_instance_black_temple ()
void AddSC_boss_fathomlord_karathress ()
void AddSC_boss_hydross_the_unstable ()
void AddSC_boss_lady_vashj ()
void AddSC_boss_leotheras_the_blind ()
void AddSC_boss_morogrim_tidewalker ()
void AddSC_boss_the_lurker_below ()
void AddSC_instance_serpentshrine_cavern ()
void AddSC_boss_ahune ()
void AddSC_instance_slave_pens ()
void AddSC_boss_hydromancer_thespia ()
void AddSC_boss_mekgineer_steamrigger ()
void AddSC_boss_warlord_kalithresh ()
void AddSC_instance_steam_vault ()
void AddSC_boss_hungarfen ()
void AddSC_boss_swamplord_muselek ()
void AddSC_boss_black_stalker ()
void AddSC_instance_underbog ()
void AddSC_boss_gruul ()
void AddSC_boss_high_king_maulgar ()
void AddSC_instance_gruuls_lair ()
void AddSC_boss_broggok ()
void AddSC_boss_kelidan_the_breaker ()
void AddSC_boss_the_maker ()
void AddSC_instance_blood_furnace ()
void AddSC_boss_nazan_and_vazruden ()
void AddSC_boss_omor_the_unscarred ()
void AddSC_boss_watchkeeper_gargolmar ()
void AddSC_instance_ramparts ()
void AddSC_boss_magtheridon ()
void AddSC_instance_magtheridons_lair ()
void AddSC_boss_grand_warlock_nethekurse ()
void AddSC_boss_warbringer_omrogg ()
void AddSC_boss_warchief_kargath_bladefist ()
void AddSC_instance_shattered_halls ()
void AddSC_arcatraz ()
void AddSC_boss_dalliah ()
void AddSC_boss_harbinger_skyriss ()
void AddSC_boss_soccothrates ()
void AddSC_instance_arcatraz ()
void AddSC_boss_high_botanist_freywinn ()
void AddSC_boss_thorngrin ()
void AddSC_boss_laj ()
void AddSC_boss_warp_splinter ()
void AddSC_boss_alar ()
void AddSC_boss_high_astromancer_solarian ()
void AddSC_boss_kaelthas ()
void AddSC_boss_void_reaver ()
void AddSC_instance_the_eye ()
void AddSC_boss_mechano_lord_capacitus ()
void AddSC_boss_nethermancer_sepethrea ()
void AddSC_boss_pathaleon_the_calculator ()
void AddSC_instance_mechanar ()
void AddSC_blades_edge_mountains ()
void AddSC_bashir_landing ()
void AddSC_shartuul_transporter ()
void AddSC_boss_doomlordkazzak ()
void AddSC_boss_doomwalker ()
void AddSC_hellfire_peninsula ()
void AddSC_nagrand ()
void AddSC_netherstorm ()
void AddSC_shadowmoon_valley ()
void AddSC_shattrath_city ()
void AddSC_terokkar_forest ()
void AddSC_boss_terokk ()
void AddSC_OutlandWorldScript ()
void AddSC_zangarmarsh ()
void AddScripts ()
Function Documentation
AddSC_alterac_mountains()
void AddSC_alterac_mountains ()
Definition at line 29 of file alterac_mountains.cpp.
Referenced by AddScripts().
AddSC_arathi_highlands()
void AddSC_arathi_highlands ()
Definition at line 253 of file arathi_highlands.cpp.
References Script::GetAI, GetAI_npc_kinelory(), GetAI_npc_professor_phizzlethorpe(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_kinelory(), QuestAccept_npc_professor_phizzlethorpe(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_arcatraz()
void AddSC_arcatraz ()
Definition at line 408 of file arcatrazScripts.cpp.
References Script::GetAI, GetAI_npc_arcatraz_defender(), GetAI_npc_millhouse_manastorm(), GetAI_npc_warden_mellichar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_areatrigger_scripts()
void AddSC_areatrigger_scripts ()
Definition at line 625 of file areatrigger_scripts.cpp.
References AreaTrigger_at_aldurthar_gate(), AreaTrigger_at_ancient_leaf(), AreaTrigger_at_area_52(), AreaTrigger_at_childrens_week_spot(), AreaTrigger_at_coilfang_waterfall(), AreaTrigger_at_haramad_teleport(), AreaTrigger_at_hive_tower(), AreaTrigger_at_hot_on_the_trail(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_legion_teleporter(), AreaTrigger_at_murkdeep(), AreaTrigger_at_quetzlun(), AreaTrigger_at_ravenholdt(), AreaTrigger_at_scent_larkorwi(), AreaTrigger_at_spearborn_encampment(), AreaTrigger_at_stormwright_shelf(), AreaTrigger_at_twilight_grove(), AreaTrigger_at_warsong_farms(), AreaTrigger_at_waygate(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ashenvale()
void AddSC_ashenvale ()
Definition at line 638 of file ashenvale.cpp.
References Script::GetAI, GetAI_npc_feero_ironhand(), GetAI_npc_muglash(), GetAI_npc_ruul_snowhoofAI(), GetAI_npc_torek(), GOUse_go_naga_brazier(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_feero_ironhand(), QuestAccept_npc_muglash(), QuestAccept_npc_ruul_snowhoof(), QuestAccept_npc_torek(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_azshara()
void AddSC_azshara ()
Definition at line 766 of file azshara.cpp.
References Script::GetAI, GetAI_boss_maws(), GetAI_go_lightning(), GetAI_mobs_spitelashes(), GetAI_npc_depth_charge(), GetAI_npc_felhound_tracker(), GetAI_npc_rizzle_sprysprocket(), Script::GetGameObjectAI, GossipHello_npc_loramus_thalipedes(), GossipHello_npc_rizzle_sprysprocket(), GossipSelect_npc_loramus_thalipedes(), GossipSelect_npc_rizzle_sprysprocket(), GOUse_go_southfury_moonstone(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, ProcessEventId_arcanite_buoy(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_azuremyst_isle()
void AddSC_azuremyst_isle ()
Definition at line 276 of file azuremyst_isle.cpp.
References Script::GetAI, GetAI_npc_draenei_survivor(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_magwin(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_bashir_landing()
void AddSC_bashir_landing ()
Definition at line 702 of file bashir_landing.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_battleground()
void AddSC_battleground ()
Definition at line 439 of file battlegrounds.cpp.
References Script::GetAI, Script::GetGameObjectAI, GossipHello_npc_spirit_guide(), Script::Name, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_black_temple()
void AddSC_black_temple ()
Definition at line 327 of file black_templeScripts.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_blackrock_depths()
void AddSC_blackrock_depths ()
Definition at line 1899 of file blackrock_depths.cpp.
References AreaTrigger_at_ring_of_law(), AreaTrigger_at_shadowforge_bridge(), EffectDummyCreature_spell_banner_of_provocation(), Script::GetAI, GetAI_boss_plugger_spazzring(), GetAI_npc_grimstone(), GetAI_npc_hurley_blackbreath(), GetAI_npc_ironhand_guardian(), GetAI_npc_marshal_windsor(), GetAI_npc_mistress_nagmara(), GetAI_npc_phalanx(), GetAI_npc_rocknot(), GossipHello_boss_doomrel(), GossipHello_npc_dughal_stormwing(), GossipHello_npc_mistress_nagmara(), GossipHello_npc_tobias_seecher(), GossipSelect_boss_doomrel(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_mistress_nagmara(), GossipSelect_npc_tobias_seecher(), GOUse_go_bar_ale_mug(), GOUse_go_bar_beer_keg(), GOUse_go_relic_coffer_door(), GOUse_go_shadowforge_brazier(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, QuestAccept_npc_marshal_windsor(), QuestRewarded_npc_mistress_nagmara(), QuestRewarded_npc_rocknot(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_blades_edge_mountains()
void AddSC_blades_edge_mountains ()
Definition at line 3339 of file blades_edge_mountains.cpp.
References AreaTrigger_at_raven_prophecy(), EffectDummyCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_npc_simon_game_bunny(), EffectScriptEffectCreature_spell_diminution_powder(), Script::GetAI, GetAI_mobs_nether_drake(), GetAI_npc_apexis_flayerAI(), GetAI_npc_bird_spirit(), GetAI_npc_bloodmaul_dire_wolf(), GetAI_npc_bloodmaul_stout_trigger(), GetAI_npc_daranelle(), GetAI_npc_deadsoul_orb(), GetAI_npc_evergrove_druidAI(), GetAI_npc_fel_cannon(), GetAI_npc_frequency_scanner(), GetAI_npc_light_orb_collector(), GetAI_npc_simon_game_bunny(), GetAI_npc_soulgrinder(), GetAI_npc_spirit_prisoner_of_bladespire(), GetAI_npc_supplicant(), GetAI_npc_vimgol(), GetAI_npc_vimgol_middle_bunny(), GetAI_npc_vimgol_visual_bunny(), GetAI_npc_warp_gate(), GetAI_obelisk_triggerAI(), Script::GetGameObjectAI, GetGOAI_go_aura_generator_000(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, Script::pEffectScriptEffectNPC, Script::pProcessEventId, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, ProcessEventId_Soulgrinder(), QuestAccept_npc_evergrove_druid(), QuestRewarded_into_the_soulgrinder(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_blasted_lands()
void AddSC_blasted_lands ()
Definition at line 43 of file blasted_lands.cpp.
References functionRuneOfTheDefiler, Script::Name, Script::pTrapSearching, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_blood_prince_council()
void AddSC_blood_prince_council ()
Definition at line 843 of file blood_prince_council.cpp.
References Script::GetAI, GetAI_boss_keleseth_icc(), GetAI_boss_taldaram_icc(), GetAI_boss_valanar_icc(), GetAI_npc_ball_of_flame(), GetAI_npc_blood_orb_control(), GetAI_npc_dark_nucleus(), GetAI_npc_kinetic_bomb(), GetAI_npc_queen_lanathel_intro(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_bloodmyst_isle()
void AddSC_bloodmyst_isle ()
Definition at line 433 of file bloodmyst_isle.cpp.
References Script::GetAI, GetAI_mob_webbed_creature(), GetAI_npc_demolitionist_legoso(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_demolitionist_legoso(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_borean_tundra()
void AddSC_borean_tundra ()
Definition at line 1563 of file borean_tundra.cpp.
References EffectAuraDummy_npc_beryl_sorcerer(), EffectAuraDummy_npc_captured_beryl_sorcerer(), EffectAuraDummy_npc_nexus_drake_hatchling(), EffectAuraDummy_npc_oil_stained_wolf(), EffectAuraDummy_npc_scourged_flamespitter(), EffectAuraDummy_spell_aura_dummy_crates_carried(), EffectDummyCreature_npc_nexus_drake_hatchling(), EffectDummyCreature_npc_oil_stained_wolf(), Script::GetAI, GetAI_npc_bonker_togglevolt(), GetAI_npc_jenny(), GetAI_npc_lurgglbr(), GetAI_npc_mootoo_the_youngerAI(), GetAI_npc_nesingwary_trapper(), GetAI_npc_nexus_drake_hatchling(), GetAI_npc_oil_stained_wolf(), GetAI_npc_orphaned_mammoth_calf(), GetAI_npc_proudhoof(), GetAI_npc_scourged_flamespitter(), GetAI_npc_seaforium_depth_charge(), GetAI_npc_sinkhole_kill_credit(), Script::GetGameObjectAI, Script::Name, NpcSpellClick_npc_storm_totem(), Script::pEffectAuraDummy, Script::pEffectDummyNPC, Script::pNpcSpellClick, Script::pQuestAcceptNPC, QuestAccept_npc_bonker_togglevolt(), QuestAccept_npc_lurgglbr(), QuestAccept_npc_mootoo_the_younger(), QuestAccept_npc_proudhoof(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_aeonus()
void AddSC_boss_aeonus ()
Definition at line 157 of file boss_aeonus.cpp.
References Script::GetAI, GetAI_boss_aeonus(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ahune()
void AddSC_boss_ahune ()
Definition at line 396 of file boss_ahune.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_akilzon()
void AddSC_boss_akilzon ()
Definition at line 362 of file boss_akilzon.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_alar()
void AddSC_boss_alar ()
Definition at line 587 of file boss_alar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_algalon()
void AddSC_boss_algalon ()
Definition at line 804 of file boss_algalon.cpp.
References Script::GetAI, GetAI_boss_algalon(), GetAI_npc_black_hole(), GetAI_npc_collapsing_star(), GetAI_npc_living_constellation(), GetAI_npc_worm_hole(), GOUse_go_celestial_access(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_amanitar()
void AddSC_boss_amanitar ()
Definition at line 230 of file boss_amanitar.cpp.
References Script::GetAI, GetAI_boss_amanitar(), GetAI_npc_amanitar_mushroom(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ambassador_flamelash()
void AddSC_boss_ambassador_flamelash ()
Definition at line 146 of file boss_ambassador_flamelash.cpp.
References Script::GetAI, GetAI_boss_ambassador_flamelash(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ambassador_hellmaw()
void AddSC_boss_ambassador_hellmaw ()
Definition at line 177 of file boss_ambassador_hellmaw.cpp.
References Script::GetAI, GetAI_boss_ambassador_hellmaw(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anetheron()
void AddSC_boss_anetheron ()
Definition at line 204 of file boss_anetheron.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anomalus()
void AddSC_boss_anomalus ()
Definition at line 231 of file boss_anomalus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anubarak()
void AddSC_boss_anubarak ()
Definition at line 308 of file boss_anubarak.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anubarak_trial()
void AddSC_boss_anubarak_trial ()
Definition at line 765 of file boss_anubarak_trial.cpp.
References EffectDummyCreature_spell_dummy_permafrost(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anubrekhan()
void AddSC_boss_anubrekhan ()
Definition at line 149 of file boss_anubrekhan.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_anzu()
void AddSC_boss_anzu ()
Definition at line 477 of file boss_anzu.cpp.
References Script::GetAI, GetAI_boss_anzu(), GetAI_npc_anzu_bird_spirit(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_arcanist_doan()
void AddSC_boss_arcanist_doan ()
Definition at line 133 of file boss_arcanist_doan.cpp.
References Script::GetAI, GetAI_boss_arcanist_doan(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_archaedas()
void AddSC_boss_archaedas ()
Definition at line 235 of file boss_archaedas.cpp.
References EffectAuraDummy_spell_aura_dummy_awaken_dwarf(), EffectDummyCreature_npc_vault_warder(), Script::GetAI, GetAI_boss_archaedas(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_archavon()
void AddSC_boss_archavon ()
Definition at line 26 of file boss_archavon.cpp.
Referenced by AddScripts().
AddSC_boss_archimonde()
void AddSC_boss_archimonde ()
Definition at line 489 of file boss_archimonde.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_argent_challenge()
void AddSC_boss_argent_challenge ()
Definition at line 343 of file boss_argent_challenge.cpp.
References Script::GetAI, GetAI_boss_eadric(), GetAI_boss_paletress(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_arlokk()
void AddSC_boss_arlokk ()
Definition at line 287 of file boss_arlokk.cpp.
References Script::GetAI, GOUse_go_gong_of_bethekk(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_assembly_of_iron()
void AddSC_boss_assembly_of_iron ()
Definition at line 777 of file assembly_of_iron.cpp.
References Script::GetAI, GetAI_boss_brundir(), GetAI_boss_molgeim(), GetAI_boss_steelbreaker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_attumen()
void AddSC_boss_attumen ()
Definition at line 409 of file boss_midnight.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_auriaya()
void AddSC_boss_auriaya ()
Definition at line 380 of file boss_auriaya.cpp.
References Script::GetAI, GetAI_boss_auriaya(), GetAI_boss_feral_defender(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ayamiss()
void AddSC_boss_ayamiss ()
Definition at line 353 of file boss_ayamiss.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_azgalor()
void AddSC_boss_azgalor ()
Definition at line 166 of file boss_azgalor.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_azuregos()
void AddSC_boss_azuregos ()
Definition at line 157 of file boss_azuregos.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_baltharus()
void AddSC_boss_baltharus ()
Definition at line 227 of file boss_baltharus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_baron_geddon()
void AddSC_boss_baron_geddon ()
Definition at line 118 of file boss_baron_geddon.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_baroness_anastari()
void AddSC_boss_baroness_anastari ()
Definition at line 206 of file boss_baroness_anastari.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_bjarngrim()
void AddSC_boss_bjarngrim ()
Definition at line 369 of file boss_bjarngrim.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_black_knight()
void AddSC_boss_black_knight ()
Definition at line 458 of file boss_black_knight.cpp.
References EffectDummyCreature_black_knight_res(), Script::GetAI, GetAI_boss_black_knight(), GetAI_npc_black_knight_ghoul(), GetAI_npc_black_knight_gryphon(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_black_stalker()
void AddSC_boss_black_stalker ()
Definition at line 204 of file boss_black_stalker.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_blackheart_the_inciter()
void AddSC_boss_blackheart_the_inciter ()
Definition at line 296 of file boss_blackheart_the_inciter.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_blood_queen_lanathel()
void AddSC_boss_blood_queen_lanathel ()
Definition at line 329 of file boss_blood_queen_lanathel.cpp.
References Script::GetAI, GetAI_boss_blood_queen_lanathel(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_broggok()
void AddSC_boss_broggok ()
Definition at line 137 of file boss_broggok.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_bronjahm()
void AddSC_boss_bronjahm ()
Definition at line 294 of file boss_bronjahm.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_broodlord()
void AddSC_boss_broodlord ()
Definition at line 122 of file boss_broodlord_lashlayer.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_brutallus()
void AddSC_boss_brutallus ()
Definition at line 573 of file boss_brutallus.cpp.
References AreaTrigger_at_madrigosa(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_buru()
void AddSC_boss_buru ()
Definition at line 298 of file boss_buru.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_cannon_master_willey()
void AddSC_boss_cannon_master_willey ()
Definition at line 111 of file boss_cannon_master_willey.cpp.
References Script::GetAI, GetAI_boss_cannon_master_willey(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_chromaggus()
void AddSC_boss_chromaggus ()
Definition at line 149 of file boss_chromaggus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_chrono_lord_deja()
void AddSC_boss_chrono_lord_deja ()
Definition at line 152 of file boss_chrono_lord_deja.cpp.
References Script::GetAI, GetAI_boss_chrono_lord_deja(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_colossus()
void AddSC_boss_colossus ()
Definition at line 372 of file boss_colossus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_coren_direbrew()
void AddSC_boss_coren_direbrew ()
Definition at line 273 of file boss_coren_direbrew.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedNPC, QuestRewarded_npc_coren_direbrew(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_cthun()
void AddSC_boss_cthun ()
Definition at line 768 of file boss_cthun.cpp.
References AreaTrigger_at_stomach_cthun(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_curator()
void AddSC_boss_curator ()
Definition at line 243 of file boss_curator.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_dalliah()
void AddSC_boss_dalliah ()
Definition at line 211 of file boss_dalliah.cpp.
References Script::GetAI, GetAI_boss_dalliah(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_darkmaster_gandling()
void AddSC_boss_darkmaster_gandling ()
Definition at line 115 of file boss_darkmaster_gandling.cpp.
References Script::GetAI, GetAI_boss_darkmaster_gandling(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_darkweaver_syth()
void AddSC_boss_darkweaver_syth ()
Definition at line 227 of file boss_darkweaver_syth.cpp.
References Script::GetAI, GetAI_boss_darkweaver_syth(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_dathrohan_balnazzar()
void AddSC_boss_dathrohan_balnazzar ()
Definition at line 202 of file boss_dathrohan_balnazzar.cpp.
References Script::GetAI, GetAI_boss_dathrohan_balnazzar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_deathbringer_saurfang()
void AddSC_boss_deathbringer_saurfang ()
Definition at line 385 of file boss_deathbringer_saurfang.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_devourer_of_souls()
void AddSC_boss_devourer_of_souls ()
Definition at line 397 of file boss_devourer_of_souls.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_doomlordkazzak()
void AddSC_boss_doomlordkazzak ()
Definition at line 197 of file boss_doomlord_kazzak.cpp.
References Script::GetAI, GetAI_boss_doomlordkazzak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_doomwalker()
void AddSC_boss_doomwalker ()
Definition at line 264 of file boss_doomwalker.cpp.
References Script::GetAI, GetAI_boss_doomwalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_draganthaurissan()
void AddSC_boss_draganthaurissan ()
Definition at line 239 of file boss_emperor_dagran_thaurissan.cpp.
References Script::GetAI, GetAI_boss_emperor_dagran_thaurissan(), GetAI_boss_moira_bronzebeard(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ebonroc()
void AddSC_boss_ebonroc ()
Definition at line 113 of file boss_ebonroc.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_eck()
void AddSC_boss_eck ()
Definition at line 48 of file boss_eck.cpp.
Referenced by AddScripts().
AddSC_boss_emalon()
void AddSC_boss_emalon ()
Definition at line 26 of file boss_emalon.cpp.
Referenced by AddScripts().
AddSC_boss_eredar_twins()
void AddSC_boss_eredar_twins ()
Definition at line 689 of file boss_eredar_twins.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_eregos()
void AddSC_boss_eregos ()
Definition at line 278 of file boss_eregos.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_exarch_maladaar()
void AddSC_boss_exarch_maladaar ()
Definition at line 322 of file boss_exarch_maladaar.cpp.
References Script::GetAI, GetAI_boss_exarch_maladaar(), GetAI_mob_stolen_soul(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_faction_champions()
void AddSC_boss_faction_champions ()
Definition at line 1340 of file boss_faction_champions.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_faerlina()
void AddSC_boss_faerlina ()
Definition at line 115 of file boss_faerlina.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_fankriss()
void AddSC_boss_fankriss ()
Definition at line 203 of file boss_fankriss.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_fathomlord_karathress()
void AddSC_boss_fathomlord_karathress ()
Definition at line 564 of file boss_fathomlord_karathress.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_felblood_kaelthas()
void AddSC_boss_felblood_kaelthas ()
Definition at line 549 of file boss_felblood_kaelthas.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_felmyst()
void AddSC_boss_felmyst ()
Definition at line 657 of file boss_felmyst.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_festergut()
void AddSC_boss_festergut ()
Definition at line 360 of file boss_festergut.cpp.
References EffectScriptEffectCreature_spell_inhale_blight(), Script::GetAI, GetAI_boss_festergut(), GetAI_npc_orange_gas_stalker(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_firemaw()
void AddSC_boss_firemaw ()
Definition at line 113 of file boss_firemaw.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_flame_leviathan()
void AddSC_boss_flame_leviathan ()
Definition at line 731 of file boss_flame_leviathan.cpp.
References Script::GetAI, GetAI_boss_flame_leviathan(), GetAI_npc_freya_ward(), GetAI_npc_hodir_fury(), GetAI_npc_hodir_fury_reticle(), GetAI_npc_mimiron_inferno(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_flamegor()
void AddSC_boss_flamegor ()
Definition at line 118 of file boss_flamegor.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_four_horsemen()
void AddSC_boss_four_horsemen ()
Definition at line 455 of file boss_four_horsemen.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_freya()
void AddSC_boss_freya ()
Definition at line 1132 of file boss_freya.cpp.
References EffectScriptEffectCreature_boss_freya(), Script::GetAI, GetAI_boss_freya(), GetAI_npc_eonars_gift(), GetAI_npc_healthy_spore(), GetAI_npc_iron_roots(), GetAI_npc_nature_bomb(), GetAI_npc_snaplasher(), GetAI_npc_storm_lasher(), GetAI_npc_water_spirit(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_galdarah()
void AddSC_boss_galdarah ()
Definition at line 186 of file boss_galdarah.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_garfrost()
void AddSC_boss_garfrost ()
Definition at line 296 of file boss_forgemaster_garfrost.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_garr()
void AddSC_boss_garr ()
Definition at line 149 of file boss_garr.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gehennas()
void AddSC_boss_gehennas ()
Definition at line 110 of file boss_gehennas.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_general_angerforge()
void AddSC_boss_general_angerforge ()
Definition at line 117 of file boss_general_angerforge.cpp.
References Script::GetAI, GetAI_boss_general_angerforge(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_general_vezax()
void AddSC_boss_general_vezax ()
Definition at line 413 of file boss_general_vezax.cpp.
References Script::GetAI, GetAI_boss_general_vezax(), GetAI_npc_saronite_vapor(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_saronite_barrier(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gluth()
void AddSC_boss_gluth ()
Definition at line 214 of file boss_gluth.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_golemagg()
void AddSC_boss_golemagg ()
Definition at line 186 of file boss_golemagg.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gortok()
void AddSC_boss_gortok ()
Definition at line 103 of file boss_gortok.cpp.
References Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_gortok_event(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gothik()
void AddSC_boss_gothik ()
Definition at line 431 of file boss_gothik.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_grand_champions()
void AddSC_boss_grand_champions ()
Definition at line 966 of file boss_grand_champions.cpp.
References Script::GetAI, GetAI_boss_champion_hunter(), GetAI_boss_champion_mage(), GetAI_boss_champion_rogue(), GetAI_boss_champion_shaman(), GetAI_boss_champion_warrior(), GetAI_npc_champion_mount(), GetAI_npc_trial_grand_champion(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_grand_warlock_nethekurse()
void AddSC_boss_grand_warlock_nethekurse ()
Definition at line 411 of file boss_nethekurse.cpp.
References Script::GetAI, GetAI_boss_grand_warlock_nethekurse(), GetAI_mob_fel_orc_convert(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_grandmaster_vorpil()
void AddSC_boss_grandmaster_vorpil ()
Definition at line 322 of file boss_grandmaster_vorpil.cpp.
References Script::GetAI, GetAI_boss_grandmaster_vorpil(), GetAI_npc_void_traveler(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_grobbulus()
void AddSC_boss_grobbulus ()
Definition at line 158 of file boss_grobbulus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gruul()
void AddSC_boss_gruul ()
Definition at line 226 of file boss_gruul.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gurtogg_bloodboil()
void AddSC_boss_gurtogg_bloodboil ()
Definition at line 311 of file boss_bloodboil.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_gyth()
void AddSC_boss_gyth ()
Definition at line 151 of file boss_gyth.cpp.
References Script::GetAI, GetAI_boss_gyth(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hadronox()
void AddSC_boss_hadronox ()
Definition at line 220 of file boss_hadronox.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hakkar()
void AddSC_boss_hakkar ()
Definition at line 128 of file boss_hakkar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_halazzi()
void AddSC_boss_halazzi ()
Definition at line 382 of file boss_halazzi.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_halion()
void AddSC_boss_halion ()
Definition at line 1108 of file boss_halion.cpp.
References Script::GetAI, GOUse_go_twilight_portal(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_harbinger_skyriss()
void AddSC_boss_harbinger_skyriss ()
Definition at line 185 of file boss_harbinger_skyriss.cpp.
References Script::GetAI, GetAI_boss_harbinger_skyriss(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_headless_horseman()
void AddSC_boss_headless_horseman ()
Definition at line 510 of file boss_headless_horseman.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_heigan()
void AddSC_boss_heigan ()
Definition at line 223 of file boss_heigan.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_herod()
void AddSC_boss_herod ()
Definition at line 174 of file boss_herod.cpp.
References Script::GetAI, GetAI_boss_herod(), GetAI_mob_scarlet_trainee(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_high_astromancer_solarian()
void AddSC_boss_high_astromancer_solarian ()
Definition at line 506 of file boss_astromancer.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_high_botanist_freywinn()
void AddSC_boss_high_botanist_freywinn ()
Definition at line 198 of file boss_high_botanist_freywinn.cpp.
References Script::GetAI, GetAI_boss_high_botanist_freywinn(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_high_interrogator_gerstahn()
void AddSC_boss_high_interrogator_gerstahn ()
Definition at line 108 of file boss_high_interrogator_gerstahn.cpp.
References Script::GetAI, GetAI_boss_high_interrogator_gerstahn(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_high_king_maulgar()
void AddSC_boss_high_king_maulgar ()
Definition at line 380 of file boss_high_king_maulgar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_highlord_kruul()
void AddSC_boss_highlord_kruul ()
Definition at line 409 of file boss_highlord_kruul.cpp.
References Script::GetAI, GetAI_boss_highlord_kruul(), GetAI_npc_infernal_hound(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hodir()
void AddSC_boss_hodir ()
Definition at line 451 of file boss_hodir.cpp.
References Script::GetAI, GetAI_boss_hodir(), GetAI_npc_flash_freeze(), GetAI_npc_icicle_target(), Script::Name, Script::pProcessEventId, ProcessEventId_event_boss_hodir(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_huhuran()
void AddSC_boss_huhuran ()
Definition at line 151 of file boss_huhuran.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hummel()
void AddSC_boss_hummel ()
Definition at line 426 of file boss_hummel.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedNPC, QuestRewarded_boss_apothecary_hummel(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hungarfen()
void AddSC_boss_hungarfen ()
Definition at line 181 of file boss_hungarfen.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hydromancer_thespia()
void AddSC_boss_hydromancer_thespia ()
Definition at line 158 of file boss_hydromancer_thespia.cpp.
References Script::GetAI, GetAI_boss_thespiaAI(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_hydross_the_unstable()
void AddSC_boss_hydross_the_unstable ()
Definition at line 355 of file boss_hydross_the_unstable.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ichoron()
void AddSC_boss_ichoron ()
Definition at line 355 of file boss_ichoron.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ignis()
void AddSC_boss_ignis ()
Definition at line 363 of file boss_ignis.cpp.
References EffectScriptEffectCreature_npc_iron_construct(), EffectScriptEffectCreature_npc_scorch(), Script::GetAI, GetAI_boss_ignis(), GetAI_npc_iron_construct(), GetAI_npc_scorch(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_illidan()
void AddSC_boss_illidan ()
Definition at line 2343 of file boss_illidan.cpp.
References Script::GetAI, GossipHello_npc_akama_illidan(), GossipSelect_npc_akama_illidan(), GOUse_go_cage_trap(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_illidari_council()
void AddSC_boss_illidari_council ()
Definition at line 717 of file illidari_council.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ingvar()
void AddSC_boss_ingvar ()
Definition at line 493 of file boss_ingvar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ionar()
void AddSC_boss_ionar ()
Definition at line 365 of file boss_ionar.cpp.
References EffectDummyCreature_boss_ionar(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_janalai()
void AddSC_boss_janalai ()
Definition at line 427 of file boss_janalai.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_jandicebarov()
void AddSC_boss_jandicebarov ()
Definition at line 104 of file boss_jandice_barov.cpp.
References Script::GetAI, GetAI_boss_jandicebarov(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_jaraxxus()
void AddSC_boss_jaraxxus ()
Definition at line 302 of file boss_jaraxxus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_jedoga()
void AddSC_boss_jedoga ()
Definition at line 459 of file boss_jedoga.cpp.
References EffectAuraDummy_spell_aura_dummy_sacrifice_beam(), Script::GetAI, GetAI_boss_jedoga(), GetAI_npc_twilight_volunteer(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_jeklik()
void AddSC_boss_jeklik ()
Definition at line 307 of file boss_jeklik.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kaelthas()
void AddSC_boss_kaelthas ()
Definition at line 1931 of file boss_kaelthas.cpp.
References EffectDummyCreature_kael_phase_2(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kalecgos()
void AddSC_boss_kalecgos ()
Definition at line 717 of file boss_kalecgos.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kazrogal()
void AddSC_boss_kazrogal ()
Definition at line 165 of file boss_kazrogal.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kazzakAI()
void AddSC_boss_kazzakAI ()
Definition at line 269 of file boss_kazzak.cpp.
References Script::GetAI, GetAI_boss_kazzak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_keleseth()
void AddSC_boss_keleseth ()
Definition at line 312 of file boss_keleseth.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kelidan_the_breaker()
void AddSC_boss_kelidan_the_breaker ()
Definition at line 376 of file boss_kelidan_the_breaker.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kelthuzad()
void AddSC_boss_kelthuzad ()
Definition at line 617 of file boss_kelthuzad.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_keristrasza()
void AddSC_boss_keristrasza ()
Definition at line 192 of file boss_keristrasza.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kiljaeden()
void AddSC_boss_kiljaeden ()
Definition at line 1395 of file boss_kiljaeden.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kologarn()
void AddSC_boss_kologarn ()
Definition at line 543 of file boss_kologarn.cpp.
References Script::GetAI, GetAI_boss_kologarn(), GetAI_npc_focused_eyebeam(), GetAI_npc_rubble_stalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_koralon()
void AddSC_boss_koralon ()
Definition at line 26 of file boss_koralon.cpp.
Referenced by AddScripts().
AddSC_boss_krick_and_ick()
void AddSC_boss_krick_and_ick ()
Definition at line 352 of file boss_krick_and_ick.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_krikthir()
void AddSC_boss_krikthir ()
Definition at line 159 of file boss_krikthir.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_kurinnaxx()
void AddSC_boss_kurinnaxx ()
Definition at line 125 of file boss_kurinnaxx.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_lady_deathwhisper()
void AddSC_boss_lady_deathwhisper ()
Definition at line 665 of file boss_lady_deathwhisper.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_lady_vashj()
void AddSC_boss_lady_vashj ()
Definition at line 749 of file boss_lady_vashj.cpp.
References Script::GetAI, GOUse_go_shield_generator(), GOUse_go_vashj_bridge(), Script::Name, OnLootItemTaintedCore(), Script::pGOUse, Script::pItemLoot, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_laj()
void AddSC_boss_laj ()
Definition at line 219 of file boss_laj.cpp.
References Script::GetAI, GetAI_boss_laj(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_leotheras_the_blind()
void AddSC_boss_leotheras_the_blind ()
Definition at line 530 of file boss_leotheras_the_blind.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_lich_king()
void AddSC_boss_lich_king ()
Definition at line 354 of file boss_lich_king.cpp.
References AreaTrigger_at_wrath_lich_king(), EffectScriptEffectCreature_spell_stun_break(), Script::GetAI, Script::Name, Script::pAreaTrigger, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_loatheb()
void AddSC_boss_loatheb ()
Definition at line 148 of file boss_loatheb.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_loken()
void AddSC_boss_loken ()
Definition at line 196 of file boss_loken.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_lord_marrowgar()
void AddSC_boss_lord_marrowgar ()
Definition at line 493 of file boss_lord_marrowgar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_lucifron()
void AddSC_boss_lucifron ()
Definition at line 99 of file boss_lucifron.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_maexxna()
void AddSC_boss_maexxna ()
Definition at line 277 of file boss_maexxna.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_magmadar()
void AddSC_boss_magmadar ()
Definition at line 124 of file boss_magmadar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_magtheridon()
void AddSC_boss_magtheridon ()
Definition at line 506 of file boss_magtheridon.cpp.
References Script::GetAI, Script::GetGameObjectAI, GOUse_go_manticron_cube(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_maiden_of_virtue()
void AddSC_boss_maiden_of_virtue ()
Definition at line 142 of file boss_maiden_of_virtue.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_majordomo()
void AddSC_boss_majordomo ()
Definition at line 444 of file boss_majordomo_executus.cpp.
References Script::GetAI, GetAI_boss_majordomo(), GossipHello_boss_majordomo(), GossipSelect_boss_majordomo(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_malacrass()
void AddSC_boss_malacrass ()
Definition at line 459 of file boss_malacrass.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_maleki_the_pallid()
void AddSC_boss_maleki_the_pallid ()
Definition at line 113 of file boss_maleki_the_pallid.cpp.
References Script::GetAI, GetAI_boss_maleki_the_pallid(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_malygos()
void AddSC_boss_malygos ()
Definition at line 989 of file boss_malygos.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_focusing_iris(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mandokir()
void AddSC_boss_mandokir ()
Definition at line 291 of file boss_mandokir.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_marli()
void AddSC_boss_marli ()
Definition at line 150 of file boss_marli.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mechano_lord_capacitus()
void AddSC_boss_mechano_lord_capacitus ()
Definition at line 280 of file boss_mechano_lord_capacitus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mekgineer_steamrigger()
void AddSC_boss_mekgineer_steamrigger ()
Definition at line 294 of file boss_mekgineer_steamrigger.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mimiron()
void AddSC_boss_mimiron ()
Definition at line 2007 of file boss_mimiron.cpp.
References EffectDummyCreature_npc_bot_trigger(), Script::GetAI, GetAI_boss_aerial_unit(), GetAI_boss_leviathan_mk2(), GetAI_boss_leviathan_mk2_turret(), GetAI_boss_mimiron(), GetAI_boss_vx001(), GetAI_npc_bot_trigger(), GetAI_npc_computer(), GetAI_npc_frost_bomb(), GetAI_npc_mimiron_flames(), GetAI_npc_proximity_mine(), GetAI_npc_rocket_strike(), GOUse_go_big_red_button(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_moam()
void AddSC_boss_moam ()
Definition at line 174 of file boss_moam.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mograine_and_whitemane()
void AddSC_boss_mograine_and_whitemane ()
Definition at line 507 of file boss_mograine_and_whitemane.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_moorabi()
void AddSC_boss_moorabi ()
Definition at line 178 of file boss_moorabi.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_moroes()
void AddSC_boss_moroes ()
Definition at line 291 of file boss_moroes.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_morogrim_tidewalker()
void AddSC_boss_morogrim_tidewalker ()
Definition at line 322 of file boss_morogrim_tidewalker.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mother_shahraz()
void AddSC_boss_mother_shahraz ()
Definition at line 231 of file boss_mother_shahraz.cpp.
References Script::GetAI, GetAI_boss_shahraz(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_mr_smite()
void AddSC_boss_mr_smite ()
Definition at line 260 of file boss_mr_smite.cpp.
References Script::GetAI, GetAI_boss_mr_smite(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_murmur()
void AddSC_boss_murmur ()
Definition at line 316 of file boss_murmur.cpp.
References Script::GetAI, GetAI_boss_murmur(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_muru()
void AddSC_boss_muru ()
Definition at line 791 of file boss_muru.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nadox()
void AddSC_boss_nadox ()
Definition at line 240 of file boss_nadox.cpp.
References Script::GetAI, GetAI_boss_nadox(), GetAI_mob_ahnkahar_egg(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_najentus()
void AddSC_boss_najentus ()
Definition at line 200 of file boss_warlord_najentus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nalorakk()
void AddSC_boss_nalorakk ()
Definition at line 261 of file boss_nalorakk.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nazan_and_vazruden()
void AddSC_boss_nazan_and_vazruden ()
Definition at line 500 of file boss_nazan_and_vazruden.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nefarian()
void AddSC_boss_nefarian ()
Definition at line 292 of file boss_nefarian.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nethermancer_sepethrea()
void AddSC_boss_nethermancer_sepethrea ()
Definition at line 216 of file boss_nethermancer_sepethrea.cpp.
References Script::GetAI, GetAI_boss_nethermancer_sepethrea(), GetAI_npc_raging_flames(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_netherspite()
void AddSC_boss_netherspite ()
Definition at line 585 of file boss_netherspite.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nexusprince_shaffar()
void AddSC_boss_nexusprince_shaffar ()
Definition at line 196 of file boss_nexusprince_shaffar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_nightbane()
void AddSC_boss_nightbane ()
Definition at line 470 of file boss_nightbane.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_summon_nightbane(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_noth()
void AddSC_boss_noth ()
Definition at line 354 of file boss_noth.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_novos()
void AddSC_boss_novos ()
Definition at line 409 of file boss_novos.cpp.
References EffectAuraDummy_npc_crystal_channel_target(), Script::GetAI, GetAI_boss_novos(), GetAI_npc_crystal_channel_target(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_noxxion()
void AddSC_boss_noxxion ()
Definition at line 112 of file boss_noxxion.cpp.
References EffectAuraDummy_spell_aura_dummy_noxxion_spawns(), Script::GetAI, GetAI_boss_noxxion(), Script::Name, Script::pEffectAuraDummy, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_omor_the_unscarred()
void AddSC_boss_omor_the_unscarred ()
Definition at line 213 of file boss_omor_the_unscarred.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_onyxia()
void AddSC_boss_onyxia ()
Definition at line 534 of file boss_onyxia.cpp.
References Script::GetAI, GetAI_boss_onyxia(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_order_of_silver_hand()
void AddSC_boss_order_of_silver_hand ()
Definition at line 173 of file boss_order_of_silver_hand.cpp.
References Script::GetAI, GetAI_boss_silver_hand_bossesAI(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ormorok()
void AddSC_boss_ormorok ()
Definition at line 297 of file boss_ormorok.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ossirian()
void AddSC_boss_ossirian ()
Definition at line 311 of file boss_ossirian.cpp.
References Script::GetAI, GOUse_go_ossirian_crystal(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ouro()
void AddSC_boss_ouro ()
Definition at line 439 of file boss_ouro.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_overlordwyrmthalak()
void AddSC_boss_overlordwyrmthalak ()
Definition at line 149 of file boss_overlord_wyrmthalak.cpp.
References Script::GetAI, GetAI_boss_overlordwyrmthalak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_pandemonius()
void AddSC_boss_pandemonius ()
Definition at line 135 of file boss_pandemonius.cpp.
References Script::GetAI, GetAI_boss_pandemonius(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_patchwerk()
void AddSC_boss_patchwerk ()
Definition at line 135 of file boss_patchwerk.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_pathaleon_the_calculator()
void AddSC_boss_pathaleon_the_calculator ()
Definition at line 264 of file boss_pathaleon_the_calculator.cpp.
References Script::GetAI, GetAI_boss_pathaleon_the_calculator(), GetAI_mob_nether_wraith(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_priestess_delrissa()
void AddSC_boss_priestess_delrissa ()
Definition at line 1122 of file boss_priestess_delrissa.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_prince_malchezaar()
void AddSC_boss_prince_malchezaar ()
Definition at line 352 of file boss_prince_malchezaar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_professor_putricide()
void AddSC_boss_professor_putricide ()
Definition at line 788 of file boss_professor_putricide.cpp.
References EffectDummyCreature_npc_putricide(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_spell_eat_ooze(), EffectScriptEffectCreature_spell_ooze_flood(), Script::GetAI, GetAI_boss_professor_putricide(), GetAI_npc_choking_gas_bomb(), GetAI_npc_gas_cloud_icc(), GetAI_npc_growing_ooze_puddle(), GetAI_npc_puddle_stalker(), GetAI_npc_volatile_ooze_icc(), Script::Name, Script::pEffectDummyNPC, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_pyroguard_emberseer()
void AddSC_boss_pyroguard_emberseer ()
Definition at line 200 of file boss_pyroguard_emberseer.cpp.
References Script::GetAI, GetAI_boss_pyroguard_emberseer(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_rage_winterchill()
void AddSC_boss_rage_winterchill ()
Definition at line 169 of file boss_rage_winterchill.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ragnaros()
void AddSC_boss_ragnaros ()
Definition at line 350 of file boss_ragnaros.cpp.
References Script::GetAI, GetAI_boss_ragnaros(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_rajaxx()
void AddSC_boss_rajaxx ()
Definition at line 372 of file boss_rajaxx.cpp.
References Script::GetAI, GossipHello_npc_general_andorov(), GossipSelect_npc_general_andorov(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_razorgore()
void AddSC_boss_razorgore ()
Definition at line 300 of file boss_razorgore.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventIdRazorgorePossess(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_razorscale()
void AddSC_boss_razorscale ()
Definition at line 912 of file boss_razorscale.cpp.
References EffectDummyCreature_npc_harpoon_fire_state(), Script::GetAI, GetAI_boss_razorscale(), GetAI_npc_expedition_commander(), GetAI_npc_harpoon_fire_state(), GetAI_npc_razorscale_spawner(), GossipHello_npc_expedition_commander(), GossipSelect_npc_expedition_commander(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_harpoon_shot(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_razuvious()
void AddSC_boss_razuvious ()
Definition at line 161 of file boss_razuvious.cpp.
References Script::GetAI, Script::Name, NpcSpellClick_npc_obedienceCrystal(), Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_reliquary_of_souls()
void AddSC_boss_reliquary_of_souls ()
Definition at line 753 of file boss_reliquary_of_souls.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_renataki()
void AddSC_boss_renataki ()
Definition at line 134 of file boss_renataki.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_rotface()
void AddSC_boss_rotface ()
Definition at line 452 of file boss_rotface.cpp.
References EffectScriptEffectCreature_spell_unstable_ooze(), Script::GetAI, GetAI_boss_rotface(), GetAI_mob_big_ooze(), GetAI_mob_little_ooze(), Script::Name, Script::pEffectScriptEffectNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sapphiron()
void AddSC_boss_sapphiron ()
Definition at line 369 of file boss_sapphiron.cpp.
References Script::GetAI, GOUse_go_sapphiron_birth(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sartharion()
void AddSC_boss_sartharion ()
Definition at line 1313 of file boss_sartharion.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sartura()
void AddSC_boss_sartura ()
Definition at line 162 of file boss_sartura.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_saviana()
void AddSC_boss_saviana ()
Definition at line 275 of file boss_saviana.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_selin_fireheart()
void AddSC_boss_selin_fireheart ()
Definition at line 302 of file boss_selin_fireheart.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_shade_of_akama()
void AddSC_boss_shade_of_akama ()
Definition at line 783 of file boss_shade_of_akama.cpp.
References Script::GetAI, GossipHello_npc_akama(), GossipSelect_npc_akama(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_shade_of_aran()
void AddSC_boss_shade_of_aran ()
Definition at line 506 of file boss_shade_of_aran.cpp.
References Script::GetAI, boss_aranAI::GetNormalSpellCooldown(), Script::Name, NPC_SHADOW_OF_ARAN, Script::RegisterSelf(), sObjectMgr, SPELL_ARCANE_MISSILES, SPELL_FIREBALL, and SPELL_FROSTBOLT.
Referenced by AddScripts().
AddSC_boss_shazzrah()
void AddSC_boss_shazzrah ()
Definition at line 126 of file boss_shazzrah.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_shirrak()
void AddSC_boss_shirrak ()
Definition at line 165 of file boss_shirrak.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sindragosa()
void AddSC_boss_sindragosa ()
Definition at line 849 of file boss_sindragosa.cpp.
References Script::GetAI, GetAI_boss_sindragosa(), GetAI_mob_frost_bomb(), GetAI_npc_rimefang_icc(), GetAI_npc_spinestalker_icc(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sjonnir()
void AddSC_boss_sjonnir ()
Definition at line 331 of file boss_sjonnir.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_skadi()
void AddSC_boss_skadi ()
Definition at line 566 of file boss_skadi.cpp.
References AreaTrigger_at_skadi(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_skeram()
void AddSC_boss_skeram ()
Definition at line 384 of file boss_skeram.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sladran()
void AddSC_boss_sladran ()
Definition at line 249 of file boss_sladran.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_soccothrates()
void AddSC_boss_soccothrates ()
Definition at line 296 of file boss_soccothrates.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_sulfuron()
void AddSC_boss_sulfuron ()
Definition at line 183 of file boss_sulfuron_harbinger.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_supremus()
void AddSC_boss_supremus ()
Definition at line 334 of file boss_supremus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_svala()
void AddSC_boss_svala ()
Definition at line 248 of file boss_svala.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_call_flames(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_swamplord_muselek()
void AddSC_boss_swamplord_muselek ()
Definition at line 260 of file boss_swamplord_muselek.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_taldaram()
void AddSC_boss_taldaram ()
Definition at line 334 of file boss_taldaram.cpp.
References Script::GetAI, GetAI_boss_taldaram(), GOUse_go_nerubian_device(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_talon_king_ikiss()
void AddSC_boss_talon_king_ikiss ()
Definition at line 220 of file boss_talon_king_ikiss.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_telestra()
void AddSC_boss_telestra ()
Definition at line 360 of file boss_telestra.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_temporus()
void AddSC_boss_temporus ()
Definition at line 184 of file boss_temporus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_terestian_illhoof()
void AddSC_boss_terestian_illhoof ()
Definition at line 296 of file boss_terestian_illhoof.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_terokk()
void AddSC_boss_terokk ()
Definition at line 314 of file boss_terokk.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_summon_terokk(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_teron_gorefiend()
void AddSC_boss_teron_gorefiend ()
Definition at line 429 of file boss_teron_gorefiend.cpp.
References AreaTrigger_at_teron_gorefiend(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_thaddius()
void AddSC_boss_thaddius ()
Definition at line 761 of file boss_thaddius.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_tharonja()
void AddSC_boss_tharonja ()
Definition at line 285 of file boss_tharonja.cpp.
References Script::GetAI, GetAI_boss_tharonja(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_the_lich_king()
void AddSC_boss_the_lich_king ()
Definition at line 737 of file boss_the_lich_king.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_the_lurker_below()
void AddSC_boss_the_lurker_below ()
Definition at line 356 of file boss_the_lurker_below.cpp.
References Script::GetAI, GOUse_go_strange_pool(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_the_maker()
void AddSC_boss_the_maker ()
Definition at line 110 of file boss_the_maker.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_thekal()
void AddSC_boss_thekal ()
Definition at line 429 of file boss_thekal.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_thermaplugg()
void AddSC_boss_thermaplugg ()
Definition at line 267 of file boss_thermaplugg.cpp.
References EffectDummyCreature_spell_boss_thermaplugg(), Script::GetAI, GetAI_boss_thermaplugg(), GOUse_go_gnomeface_button(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_thorim()
void AddSC_boss_thorim ()
Definition at line 1052 of file boss_thorim.cpp.
References Script::GetAI, GetAI_boss_sif(), GetAI_boss_thorim(), GetAI_npc_runic_colossus(), GetAI_npc_thunder_orb(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_thorngrin()
void AddSC_boss_thorngrin ()
Definition at line 138 of file boss_thorngrin_the_tender.cpp.
References Script::GetAI, GetAI_boss_thorngrin(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_toravon()
void AddSC_boss_toravon ()
Definition at line 26 of file boss_toravon.cpp.
Referenced by AddScripts().
AddSC_boss_trollgore()
void AddSC_boss_trollgore ()
Definition at line 237 of file boss_trollgore.cpp.
References Script::GetAI, GetAI_boss_trollgore(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_twinemperors()
void AddSC_boss_twinemperors ()
Definition at line 421 of file boss_twinemperors.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_tyrannus()
void AddSC_boss_tyrannus ()
Definition at line 311 of file boss_scourgelord_tyrannus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_urom()
void AddSC_boss_urom ()
Definition at line 360 of file boss_urom.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_vaelastrasz()
void AddSC_boss_vaelastrasz ()
Definition at line 390 of file boss_vaelastrasz.cpp.
References AreaTrigger_at_vaelastrasz(), Script::GetAI, GossipHello_boss_vaelastrasz(), GossipSelect_boss_vaelastrasz(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_boss_vaelastrasz(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_valithria_dreamwalker()
void AddSC_boss_valithria_dreamwalker ()
Definition at line 150 of file boss_valithria_dreamwalker.cpp.
References Script::GetAI, GetAI_boss_valithria_dreamwalker(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_varos()
void AddSC_boss_varos ()
Definition at line 311 of file boss_varos.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_call_captain(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_venoxis()
void AddSC_boss_venoxis ()
Definition at line 125 of file boss_venoxis.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_vexallus()
void AddSC_boss_vexallus ()
Definition at line 250 of file boss_vexallus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_victor_nefarius()
void AddSC_boss_victor_nefarius ()
Definition at line 242 of file boss_victor_nefarius.cpp.
References Script::GetAI, GossipHello_boss_victor_nefarius(), GossipSelect_boss_victor_nefarius(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_viscidus()
void AddSC_boss_viscidus ()
Definition at line 567 of file boss_viscidus.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_void_reaver()
void AddSC_boss_void_reaver ()
Definition at line 180 of file boss_void_reaver.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_volazj()
void AddSC_boss_volazj ()
Definition at line 290 of file boss_volazj.cpp.
References Script::GetAI, GetAI_boss_volazj(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_volkhan()
void AddSC_boss_volkhan ()
Definition at line 408 of file boss_volkhan.cpp.
References EffectDummyCreature_boss_volkhan(), EffectDummyCreature_npc_volkhan_anvil(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_warbringer_omrogg()
void AddSC_boss_warbringer_omrogg ()
Definition at line 414 of file boss_warbringer_omrogg.cpp.
References Script::GetAI, GetAI_boss_warbringer_omrogg(), GetAI_mob_omrogg_heads(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_warchief_kargath_bladefist()
void AddSC_boss_warchief_kargath_bladefist ()
Definition at line 349 of file boss_warchief_kargath_bladefist.cpp.
References Script::GetAI, GetAI_boss_warchief_kargath_bladefist(), GetAI_npc_blade_dance_target(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_warlord_kalithresh()
void AddSC_boss_warlord_kalithresh ()
Definition at line 289 of file boss_warlord_kalithresh.cpp.
References Script::GetAI, GetAI_boss_warlord_kalithresh(), GetAI_mob_naga_distiller(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_warp_splinter()
void AddSC_boss_warp_splinter ()
Definition at line 199 of file boss_warp_splinter.cpp.
References Script::GetAI, GetAI_boss_warp_splinter(), GetAI_npc_sapling(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_watchkeeper_gargolmar()
void AddSC_boss_watchkeeper_gargolmar ()
Definition at line 177 of file boss_watchkeeper_gargolmar.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_xevozz()
void AddSC_boss_xevozz ()
Definition at line 246 of file boss_xevozz.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_xt_002()
void AddSC_boss_xt_002 ()
Definition at line 535 of file boss_xt_002.cpp.
References Script::GetAI, GetAI_boss_heart_deconstructor(), GetAI_boss_xt_002(), GetAI_npc_scrapbot(), GetAI_npc_xt_toy_pile(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_ymiron()
void AddSC_boss_ymiron ()
Definition at line 463 of file boss_ymiron.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_achiev_kings_bane(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_yogg_saron()
void AddSC_boss_yogg_saron ()
Definition at line 1680 of file boss_yogg_saron.cpp.
References EffectDummyCreature_npc_immortal_guardian(), Script::GetAI, GetAI_boss_sara(), GetAI_boss_yogg_saron(), GetAI_npc_brain_yogg_saron(), GetAI_npc_constrictor_tentacle(), GetAI_npc_death_ray(), GetAI_npc_descent_madness(), GetAI_npc_guardian_of_yogg(), GetAI_npc_immortal_guardian(), GetAI_npc_keeper_mimiron(), GetAI_npc_keeper_thorim(), GetAI_npc_ominous_cloud(), GetAI_npc_voice_yogg_saron(), Script::Name, NpcSpellClick_npc_descent_madness(), Script::pEffectDummyNPC, Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_yor()
void AddSC_boss_yor ()
Definition at line 282 of file boss_yor.cpp.
References Script::GetAI, GetAInpc_ethereum_prisoner_dungeon(), GOUse_go_stasis_chamber_mana_tombs(), GOUse_go_stasis_chamber_shaffar(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_zarithrian()
void AddSC_boss_zarithrian ()
Definition at line 123 of file boss_zarithrian.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_zuljin()
void AddSC_boss_zuljin ()
Definition at line 565 of file boss_zuljin.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_boss_zumrah()
void AddSC_boss_zumrah ()
Definition at line 208 of file boss_zumrah.cpp.
References Script::GetAI, GetAI_boss_zumrah(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_bosses_emerald_dragons()
void AddSC_bosses_emerald_dragons ()
Definition at line 550 of file bosses_emerald_dragons.cpp.
References Script::GetAI, GetAI_boss_emeriss(), GetAI_boss_lethon(), GetAI_boss_taerar(), GetAI_boss_ysondre(), GetAI_npc_spirit_shade(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_bosses_opera()
void AddSC_bosses_opera ()
Definition at line 1360 of file bosses_opera.cpp.
References EffectDummyCreature_spell_drink_poison(), Script::GetAI, GossipHello_npc_grandmother(), GossipSelect_npc_grandmother(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_brewfest()
void AddSC_brewfest ()
Definition at line 835 of file brewfest.cpp.
References AreaTrigger_at_brewfest_barker(), AreaTrigger_at_brewfest_quest_barking(), AreaTrigger_at_brewfest_receive_keg(), AreaTrigger_at_brewfest_send_keg(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_bug_trio()
void AddSC_bug_trio ()
Definition at line 376 of file boss_bug_trio.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_burning_steppes()
void AddSC_burning_steppes ()
Definition at line 563 of file burning_steppes.cpp.
References EffectDummyCreature_spell_capture_grark(), Script::GetAI, GetAI_npc_grark_lorkrub(), GetAI_npc_klinfran(), GossipHello_npc_klinfran(), GossipSelect_npc_klinfran(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_grark_lorkrub(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_chess_event()
void AddSC_chess_event ()
Definition at line 1690 of file chess_event.cpp.
References EffectDummyCreature_npc_chess_generic(), Script::GetAI, GetAI_npc_echo_of_medivh(), GetAI_npc_human_charger(), GetAI_npc_human_cleric(), GetAI_npc_human_conjurer(), GetAI_npc_human_footman(), GetAI_npc_king_llane(), GetAI_npc_orc_grunt(), GetAI_npc_orc_necrolyte(), GetAI_npc_orc_warlock(), GetAI_npc_orc_wolf(), GetAI_npc_summoned_daemon(), GetAI_npc_warchief_blackhand(), GetAI_npc_water_elemental(), GossipHello_npc_echo_of_medivh(), GossipHello_npc_human_charger(), GossipHello_npc_human_cleric(), GossipHello_npc_human_conjurer(), GossipHello_npc_human_footman(), GossipHello_npc_king_llane(), GossipHello_npc_orc_grunt(), GossipHello_npc_orc_necrolyte(), GossipHello_npc_orc_warlock(), GossipHello_npc_orc_wolf(), GossipHello_npc_summoned_daemon(), GossipHello_npc_warchief_blackhand(), GossipHello_npc_water_elemental(), GossipSelect_npc_chess_generic(), GossipSelect_npc_echo_of_medivh(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_childrens_week_tbc()
void AddSC_childrens_week_tbc ()
Definition at line 881 of file childrens_week_tbc.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_culling_of_stratholme()
void AddSC_culling_of_stratholme ()
Definition at line 984 of file culling_of_stratholme.cpp.
References EffectAuraDummy_spell_aura_dummy_npc_crates_dummy(), EffectDummyCreature_npc_spell_dummy_crusader_strike(), Script::GetAI, GetAI_npc_arthas(), GossipHello_npc_arthas(), GossipHello_npc_chromie(), GossipSelect_npc_arthas(), GossipSelect_npc_chromie(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_chromie(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dalaran()
void AddSC_dalaran ()
Definition at line 210 of file dalaran.cpp.
References AreaTrigger_at_underbelly_a(), AreaTrigger_at_underbelly_h(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dark_portal()
void AddSC_dark_portal ()
Definition at line 395 of file dark_portalScripts.cpp.
References EffectDummyCreature_npc_medivh_black_morass(), EffectDummyCreature_npc_time_rift_channel(), Script::GetAI, GetAI_npc_medivh_black_morass(), GetAI_npc_time_rift(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_darkshore()
void AddSC_darkshore ()
Definition at line 1003 of file darkshore.cpp.
References EffectDummyCreature_awaken_kerlonian(), Script::GetAI, GetAI_npc_kerlonian(), GetAI_npc_prospector_remtravel(), GetAI_npc_rabid_bear(), GetAI_npc_therylune(), GetAI_npc_threshwackonator(), GetAI_npc_volcor(), GossipHello_npc_threshwackonator(), GossipSelect_npc_threshwackonator(), GOUse_go_furbolg_food(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_event_purify_food(), QuestAccept_npc_kerlonian(), QuestAccept_npc_prospector_remtravel(), QuestAccept_npc_therylune(), QuestAccept_npc_volcor(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_deadmines()
void AddSC_deadmines ()
Definition at line 57 of file deadmines.cpp.
References GOUse_go_defias_cannon(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_desolace()
void AddSC_desolace ()
Definition at line 667 of file desolace.cpp.
References EffectDummyCreature_npc_aged_dying_ancient_kodo(), Script::GetAI, GetAI_npc_aged_dying_ancient_kodo(), GetAI_npc_dalinda_malem(), GetAI_npc_magrami_spectre(), GetAI_npc_melizza_brimbuzzle(), GossipHello_npc_aged_dying_ancient_kodo(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pQuestAcceptNPC, QuestAccept_npc_cork_gizelton(), QuestAccept_npc_dalinda_malem(), QuestAccept_npc_melizza_brimbuzzle(), QuestAccept_npc_rigger_gizelton(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dire_maul()
void AddSC_dire_maul ()
Definition at line 236 of file dire_maul.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_spells_warlock_dreadsteed(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dragonblight()
void AddSC_dragonblight ()
Definition at line 465 of file dragonblight.cpp.
References Script::GetAI, GetAI_npc_destructive_ward(), Script::GetGameObjectAI, Script::Name, NpcSpellClick_npc_crystalline_ice_giant(), Script::pNpcSpellClick, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dun_morogh()
void AddSC_dun_morogh ()
Definition at line 29 of file dun_morogh.cpp.
Referenced by AddScripts().
AddSC_durotar()
void AddSC_durotar ()
Definition at line 246 of file durotar.cpp.
References EffectDummyCreature_lazy_peon_spell(), Script::GetAI, GetAI_npc_lazy_peon(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_dustwallow_marsh()
void AddSC_dustwallow_marsh ()
Definition at line 1926 of file dustwallow_marsh.cpp.
References AreaTrigger_at_nats_landing(), AreaTrigger_at_sentry_point(), Script::GetAI, GetAI_mob_invis_firework_helper(), GetAI_mobs_risen_husk_spirit(), GetAI_npc_major_mills(), GetAI_npc_morokk(), GetAI_npc_ogron(), GetAI_npc_private_hendel(), GetAI_npc_restless_apparition(), GetAI_npc_smolderwing(), GetAI_npc_stinky_ignatz(), Script::Name, Script::pAreaTrigger, Script::pQuestAcceptNPC, QuestAccept_npc_major_mills(), QuestAccept_npc_morokk(), QuestAccept_npc_ogron(), QuestAccept_npc_private_hendel(), QuestAccept_npc_stinky_ignatz(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_eastern_plaguelands()
void AddSC_eastern_plaguelands ()
Definition at line 354 of file eastern_plaguelands.cpp.
References Script::GetAI, GetAI_npc_eris_havenfire(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_eris_havenfire(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ebon_hold()
void AddSC_ebon_hold ()
Definition at line 2348 of file ebon_hold.cpp.
References EffectDummyCreature_npc_death_knight_initiate(), EffectDummyCreature_npc_scarlet_ghoul(), Script::GetAI, Script::GetGameObjectAI, GossipHello_npc_death_knight_initiate(), GossipHello_npc_highlord_darion_mograine(), GossipSelect_npc_death_knight_initiate(), GossipSelect_npc_highlord_darion_mograine(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_elwynn_forest()
void AddSC_elwynn_forest ()
Definition at line 29 of file elwynn_forest.cpp.
Referenced by AddScripts().
AddSC_eversong_woods()
void AddSC_eversong_woods ()
Definition at line 568 of file eversong_woods.cpp.
References Script::GetAI, GetAI_npc_apprentice_mirvedaAI(), GetAI_npc_infused_crystalAI(), GetAI_npc_kelerun_bloodmourn(), GetAI_npc_prospector_anvilward(), GossipHello_npc_prospector_anvilward(), GossipSelect_npc_prospector_anvilward(), GOUse_go_harbinger_second_trial(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_kelerun_bloodmourn(), QuestAccept_unexpected_results(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_example_creature()
void AddSC_example_creature ()
Definition at line 281 of file example_creature.cpp.
References Script::GetAI, GetAI_example_creature(), GossipHello_example_creature(), GossipSelect_example_creature(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_example_escort()
void AddSC_example_escort ()
Definition at line 225 of file example_escort.cpp.
References Script::GetAI, GetAI_example_escort(), GossipHello_example_escort(), GossipSelect_example_escort(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_example_gossip_codebox()
void AddSC_example_gossip_codebox ()
Definition at line 90 of file example_gossip_codebox.cpp.
References GossipHello_example_gossip_codebox(), GossipSelect_example_gossip_codebox(), GossipSelectWithCode_example_gossip_codebox(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGossipSelectWithCode, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_example_misc()
void AddSC_example_misc ()
Definition at line 50 of file example_misc.cpp.
References AreaTrigger_at_example(), GOUse_example_go_teleporter(), ItemUse_example_item(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pItemUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_felwood()
void AddSC_felwood ()
Definition at line 494 of file felwood.cpp.
References EffectDummyCreature_npc_kitten(), Script::GetAI, GetAI_npc_arei(), GetAI_npc_captured_arkonarin(), GetAI_npc_kitten(), GossipHello_npc_corrupt_saber(), GossipSelect_npc_corrupt_saber(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_arei(), QuestAccept_npc_captured_arkonarin(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_feralas()
void AddSC_feralas ()
Definition at line 627 of file feralas.cpp.
References EffectDummyCreature_npc_shay_leafrunner(), Script::GetAI, GetAI_npc_captured_sprite_darter(), GetAI_npc_kindal_moonweaver(), GetAI_npc_oox22fe(), GetAI_npc_shay_leafrunner(), GOUse_go_cage_door(), Script::Name, Script::pEffectDummyNPC, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_kindal_moonweaver(), QuestAccept_npc_oox22fe(), QuestAccept_npc_shay_leafrunner(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_generic_creature()
void AddSC_generic_creature ()
Definition at line 170 of file mob_generic_creature.cpp.
References Script::GetAI, GetAI_generic_creature(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ghostlands()
void AddSC_ghostlands ()
Definition at line 166 of file ghostlands.cpp.
References Script::GetAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_ranger_lilatha(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_gnomeregan()
void AddSC_gnomeregan ()
Definition at line 706 of file gnomeregan.cpp.
References Script::GetAI, GetAI_npc_blastmaster_emi_shortfuse(), GetAI_npc_kernobee(), GossipHello_npc_blastmaster_emi_shortfuse(), GossipSelect_npc_blastmaster_emi_shortfuse(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_kernobee(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_go_scripts()
void AddSC_go_scripts ()
Definition at line 1208 of file go_scripts.cpp.
References Script::GetAI, GetAI_go_bells(), GetAI_go_containment(), GetAI_go_darkmoon_faire_music(), GetAI_go_dragon_head(), GetAI_go_elemental_rift(), GetAI_go_fel_cannonball_stack_trap(), GetAI_go_unadorned_spike(), GetAIgo_brewfest_music(), GetAIgo_midsummer_music(), GetAIgo_pirate_day_music(), Script::GetGameObjectAI, GOUse_go_andorhal_tower(), GOUse_go_ethereum_prison(), GOUse_go_ethereum_stasis(), GOUse_go_jump_a_tron(), GOUse_go_mysterious_snow_mound(), GOUse_go_scourge_enclosure(), GOUse_go_stasis_chamber_alpha(), GOUse_go_tele_to_dalaran_crystal(), GOUse_go_tele_to_violet_stand(), Script::Name, Script::pGOUse, Script::pTrapSearching, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_grizzly_hills()
void AddSC_grizzly_hills ()
Definition at line 718 of file grizzly_hills.cpp.
References EffectAuraDummy_npc_depleted_war_golem(), Script::GetAI, GetAI_npc_depleted_war_golem(), GetAI_npc_emily(), GetAI_npc_harrison_jones(), Script::Name, Script::pEffectAuraDummy, Script::pQuestAcceptNPC, QuestAccept_npc_emily(), QuestAccept_npc_harrison_jones(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_guards()
void AddSC_guards ()
Definition at line 558 of file guards.cpp.
References EffectDummyCreature_npc_city_guard(), Script::GetAI, GetAI_guard_azuremyst(), GetAI_guard_bluffwatcher(), GetAI_guard_contested(), GetAI_guard_darnassus(), GetAI_guard_dunmorogh(), GetAI_guard_durotar(), GetAI_guard_elwynnforest(), GetAI_guard_eversong(), GetAI_guard_exodar(), GetAI_guard_ironforge(), GetAI_guard_mulgore(), GetAI_guard_orgrimmar(), GetAI_guard_shattrath(), GetAI_guard_shattrath_aldor(), GetAI_guard_shattrath_scryer(), GetAI_guard_silvermoon(), GetAI_guard_stormwind(), GetAI_guard_teldrassil(), GetAI_guard_tirisfal(), GetAI_guard_undercity(), GossipHello_guard_hallows_end_helper(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_gunship_battle()
void AddSC_gunship_battle ()
Definition at line 156 of file gunship_battle.cpp.
References GossipHello_npc_muradin_gunship(), GossipHello_npc_saurfang_gunship(), GossipSelect_npc_muradin_gunship(), GossipSelect_npc_saurfang_gunship(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_hallows_end()
void AddSC_hallows_end ()
Definition at line 28 of file hallows_end.cpp.
Referenced by AddScripts().
AddSC_halls_of_reflection()
void AddSC_halls_of_reflection ()
Definition at line 339 of file halls_of_reflectionScripts.cpp.
References AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_frostworn_general(), AreaTrigger_at_queldelar_start(), EffectAuraDummy_spell_aura_dummy_frostmourne_equip(), EffectDummyCreature_spell_summon_reflections(), Script::Name, Script::pAreaTrigger, Script::pEffectAuraDummy, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_halls_of_stone()
void AddSC_halls_of_stone ()
Definition at line 694 of file halls_of_stoneScripts.cpp.
References Script::GetAI, GossipHello_npc_brann_hos(), GossipSelect_npc_brann_hos(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_brann_achievement_fail(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_hellfire_peninsula()
void AddSC_hellfire_peninsula ()
Definition at line 2398 of file hellfire_peninsula.cpp.
References EffectDummyCreature_npc_fel_guard_hound(), Script::GetAI, GetAI_danath_trollbane(), GetAI_go_smoke_beacon(), GetAI_nazgrel(), GetAI_npc_aeranas(), GetAI_npc_ancestral_wolf(), GetAI_npc_anchorite_barada(), GetAI_npc_colonel_jules(), GetAI_npc_credit_marker_they_must_burn(), GetAI_npc_demoniac_scryer(), GetAI_npc_fel_guard_hound(), GetAI_npc_krun(), GetAI_npc_laughing_skull(), GetAI_npc_maghar_escort(), GetAI_npc_vindicator_sedai(), GetAI_npc_wounded_blood_elf(), Script::GetGameObjectAI, GossipHello_npc_anchorite_barada(), GossipHello_npc_colonel_jules(), GossipHello_npc_demoniac_scryer(), GossipSelect_npc_anchorite_barada(), GossipSelect_npc_demoniac_scryer(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, ProcessEventId_sedai_vision(), QuestAccept_npc_wounded_blood_elf(), QuestComplete_npc_nazgrel(), QuestComplete_npc_trollbane(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_hinterlands()
void AddSC_hinterlands ()
Definition at line 391 of file hinterlands.cpp.
References Script::GetAI, GetAI_npc_00x09hl(), GetAI_npc_rinji(), Script::Name, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_WildhammerMessage(), QuestAccept_npc_00x09hl(), QuestAccept_npc_rinji(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_howling_fjord()
void AddSC_howling_fjord ()
Definition at line 977 of file howling_fjord.cpp.
References AreaTrigger_at_ancient_male_vrykul(), AreaTrigger_at_nifflevar(), Script::GetAI, GetAI_npc_ancient_male_vrykul(), GetAI_npc_apothecary_hanes(), GetAI_npc_firecrackers_bunny(), GetAI_npc_king_ymiron(), GetAI_npc_lich_king_village(), GetAI_npc_silvermoon_harry(), GossipHello_npc_silvermoon_harry(), GossipSelect_npc_silvermoon_harry(), Script::Name, NpcSpellClick_npc_scalawag_frog(), Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pNpcSpellClick, Script::pQuestAcceptNPC, QuestAccept_npc_apothecary_hanes(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_hyjal()
void AddSC_hyjal ()
Definition at line 315 of file hyjalScripts.cpp.
References Script::GetAI, GossipSelect_npc_jaina_proudmoore(), GossipSelect_npc_thrall(), Script::Name, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_icecrown()
void AddSC_icecrown ()
Definition at line 980 of file icecrown.cpp.
References EffectDummyCreature_npc_grand_admiral_westwind(), Script::GetAI, GetAI_npc_father_kamaros(), GetAI_npc_grand_admiral_westwind(), GetAI_npc_infantry(), GetAI_npc_squad_leader(), GossipHello_npc_saronite_mine_slave(), GossipSelect_npc_saronite_mine_slave(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_father_kamaros(), QuestAccept_npc_squad_leader(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_icecrown_citadel()
void AddSC_icecrown_citadel ()
Definition at line 484 of file icecrown_citadelScripts.cpp.
References AreaTrigger_at_frozen_throne_tele(), AreaTrigger_at_lights_hammer(), AreaTrigger_at_putricides_trap(), AreaTrigger_at_rampart_skull(), Script::GetAI, GetAI_npc_putricides_trap(), Script::GetGameObjectAI, GossipHello_go_icc_teleporter(), GossipSelect_go_icc_teleporter(), Script::Name, Script::pAreaTrigger, Script::pGossipHelloGO, Script::pGossipSelectGO, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_ahnkahet()
void AddSC_instance_ahnkahet ()
Definition at line 424 of file ahnkahet.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ahnkahet(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_arcatraz()
void AddSC_instance_arcatraz ()
Definition at line 519 of file arcatraz.cpp.
References Script::GetInstanceData, GetInstanceData_instance_arcatraz(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_azjol_nerub()
void AddSC_instance_azjol_nerub ()
Definition at line 470 of file azjol-nerub.cpp.
References Script::GetInstanceData, GetInstanceData_instance_azjol_nerub(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_black_temple()
void AddSC_instance_black_temple ()
Definition at line 502 of file black_temple.cpp.
References Script::GetInstanceData, GetInstanceData_instance_black_temple(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_blackfathom_deeps()
void AddSC_instance_blackfathom_deeps ()
Definition at line 288 of file instance_blackfathom_deeps.cpp.
References Script::GetInstanceData, GetInstanceData_instance_blackfathom_deeps(), GOUse_go_fathom_stone(), GOUse_go_fire_of_akumai(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_blackrock_depths()
void AddSC_instance_blackrock_depths ()
Definition at line 836 of file instance_blackrock_depths.cpp.
References Script::GetInstanceData, GetInstanceData_instance_blackrock_depths(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_blackrock_spire()
void AddSC_instance_blackrock_spire ()
Definition at line 963 of file instance_blackrock_spire.cpp.
References AreaTrigger_at_blackrock_spire(), Script::GetAI, GetAI_npc_rookery_hatcher(), Script::GetInstanceData, GetInstanceData_instance_blackrock_spire(), GOUse_go_father_flame(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_spell_altar_emberseer(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_blackwing_lair()
void AddSC_instance_blackwing_lair ()
Definition at line 830 of file blackwing_lair.cpp.
References GetAI_go_suppression(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_blackwing_lair(), Script::Name, Script::pProcessEventId, ProcessEventId_event_weekly_chromatic_selection(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_blood_furnace()
void AddSC_instance_blood_furnace ()
Definition at line 482 of file blood_furnace.cpp.
References Script::GetInstanceData, GOUse_go_prison_cell_lever(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_culling_of_stratholme()
void AddSC_instance_culling_of_stratholme ()
Definition at line 960 of file instance_culling_of_stratholme.cpp.
References AreaTrigger_at_culling_of_stratholme(), Script::GetInstanceData, GetInstanceData_instance_culling_of_stratholme(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_dark_portal()
void AddSC_instance_dark_portal ()
Definition at line 627 of file dark_portal.cpp.
References AreaTrigger_at_dark_portal(), Script::GetInstanceData, GetInstanceData_instance_dark_portal(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_deadmines()
void AddSC_instance_deadmines ()
Definition at line 264 of file instance_deadmines.cpp.
References Script::GetInstanceData, GetInstanceData_instance_deadmines(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_dire_maul()
void AddSC_instance_dire_maul ()
Definition at line 677 of file instance_dire_maul.cpp.
References EffectDummyCreature_spell_guard_slip_kik(), GetAI_go_fixed_trap(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_dire_maul(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_draktharon_keep()
void AddSC_instance_draktharon_keep ()
Definition at line 352 of file instance_draktharon_keep.cpp.
References Script::GetInstanceData, GetInstanceData_instance_draktharon_keep(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_eye_of_eternity()
void AddSC_instance_eye_of_eternity ()
Definition at line 215 of file eye_of_eternity.cpp.
References Script::GetInstanceData, GetInstanceData_instance_eye_of_eternity(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_forge_of_souls()
void AddSC_instance_forge_of_souls ()
Definition at line 194 of file forge_of_souls.cpp.
References Script::GetInstanceData, GetInstanceData_instance_forge_of_souls(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_gnomeregan()
void AddSC_instance_gnomeregan ()
Definition at line 279 of file instance_gnomeregan.cpp.
References Script::GetInstanceData, GetInstanceData_instance_gnomeregan(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_gruuls_lair()
void AddSC_instance_gruuls_lair ()
Definition at line 149 of file gruuls_lair.cpp.
References Script::GetInstanceData, GetInstanceData_instance_gruuls_lair(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_gundrak()
void AddSC_instance_gundrak ()
Definition at line 489 of file gundrak.cpp.
References Script::GetInstanceData, GOUse_go_gundrak_altar(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_halls_of_lightning()
void AddSC_instance_halls_of_lightning ()
Definition at line 178 of file instance_halls_of_lightning.cpp.
References Script::GetInstanceData, GetInstanceData_instance_halls_of_lightning(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_halls_of_reflection()
void AddSC_instance_halls_of_reflection ()
Definition at line 701 of file halls_of_reflection.cpp.
References Script::GetInstanceData, GetInstanceData_instance_halls_of_reflection(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_halls_of_stone()
void AddSC_instance_halls_of_stone ()
Definition at line 692 of file halls_of_stone.cpp.
References Script::GetInstanceData, GetInstanceData_instance_halls_of_stone(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_icecrown_citadel()
void AddSC_instance_icecrown_citadel ()
Definition at line 1196 of file icecrown_citadel.cpp.
References AreaTrigger_at_icecrown_citadel(), Script::GetInstanceData, GetInstanceData_instance_icecrown_citadel(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_gameobject_citadel_valve(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_karazhan()
void AddSC_instance_karazhan ()
Definition at line 879 of file karazhan.cpp.
References Script::GetInstanceData, GetInstanceData_instance_karazhan(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_magisters_terrace()
void AddSC_instance_magisters_terrace ()
Definition at line 217 of file magisters_terrace.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_magtheridons_lair()
void AddSC_instance_magtheridons_lair ()
Definition at line 268 of file magtheridons_lair.cpp.
References Script::GetInstanceData, GetInstanceData_instance_magtheridons_lair(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_maraudon()
void AddSC_instance_maraudon ()
Definition at line 192 of file instance_maraudon.cpp.
References GetAI_go_larva_spewer(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_maraudon(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_mechanar()
void AddSC_instance_mechanar ()
Definition at line 312 of file mechanar.cpp.
References Script::GetInstanceData, GetInstanceData_instance_mechanar(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_molten_core()
void AddSC_instance_molten_core ()
Definition at line 310 of file molten_core.cpp.
References GetInstance_instance_molten_core(), Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_mount_hyjal()
void AddSC_instance_mount_hyjal ()
Definition at line 1883 of file hyjal.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
Definition at line 860 of file naxxramas.cpp.
References AreaTrigger_at_naxxramas(), Script::GetInstanceData, GetInstanceData_instance_naxxramas(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_nexus()
void AddSC_instance_nexus ()
Definition at line 245 of file nexus.cpp.
References Script::GetInstanceData, GetInstanceData_instance_nexus(), GOUse_go_containment_sphere(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_obsidian_sanctum()
void AddSC_instance_obsidian_sanctum ()
Definition at line 148 of file obsidian_sanctum.cpp.
References Script::GetInstanceData, GetInstanceData_instance_obsidian_sanctum(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_oculus()
void AddSC_instance_oculus ()
Definition at line 271 of file oculus.cpp.
References Script::GetInstanceData, GetInstanceData_instance_oculus(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_old_hillsbrad()
void AddSC_instance_old_hillsbrad ()
Definition at line 359 of file old_hillsbrad.cpp.
References Script::GetInstanceData, GetInstanceData_instance_old_hillsbrad(), Script::Name, Script::pProcessEventId, ProcessEventId_event_go_barrel_old_hillsbrad(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_onyxias_lair()
void AddSC_instance_onyxias_lair ()
Definition at line 143 of file instance_onyxias_lair.cpp.
References Script::GetInstanceData, GetInstanceData_instance_onyxias_lair(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_pinnacle()
void AddSC_instance_pinnacle ()
Definition at line 549 of file utgarde_pinnacle.cpp.
References AreaTrigger_at_svala_intro(), Script::GetInstanceData, GetInstanceData_instance_pinnacle(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_pit_of_saron()
void AddSC_instance_pit_of_saron ()
Definition at line 583 of file pit_of_saron.cpp.
References Script::GetInstanceData, GetInstanceData_instance_pit_of_saron(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_ramparts()
void AddSC_instance_ramparts ()
Definition at line 165 of file hellfire_ramparts.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ramparts(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_razorfen_downs()
void AddSC_instance_razorfen_downs ()
Definition at line 195 of file instance_razorfen_downs.cpp.
References Script::GetInstanceData, GetInstanceData_instance_razorfen_downs(), Script::Name, Script::pProcessEventId, ProcessEventId_event_go_tutenkash_gong(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_razorfen_kraul()
void AddSC_instance_razorfen_kraul ()
Definition at line 125 of file instance_razorfen_kraul.cpp.
References Script::GetInstanceData, GetInstanceData_instance_razorfen_kraul(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_ruby_sanctum()
void AddSC_instance_ruby_sanctum ()
Definition at line 389 of file ruby_sanctum.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ruby_sanctum(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_ruins_of_ahnqiraj()
void AddSC_instance_ruins_of_ahnqiraj ()
Definition at line 396 of file ruins_of_ahnqiraj.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ruins_of_ahnqiraj(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_scarlet_monastery()
void AddSC_instance_scarlet_monastery ()
Definition at line 220 of file instance_scarlet_monastery.cpp.
References AreaTrigger_at_cathedral_entrance(), Script::GetInstanceData, GetInstanceData_instance_scarlet_monastery(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_scholomance()
void AddSC_instance_scholomance ()
Definition at line 509 of file instance_scholomance.cpp.
References Script::GetInstanceData, GetInstanceData_instance_scholomance(), Script::Name, Script::pProcessEventId, ProcessEventId_dawn_gambit(), ProcessEventId_event_spell_gandling_shadow_portal(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_serpentshrine_cavern()
void AddSC_instance_serpentshrine_cavern ()
Definition at line 438 of file serpent_shrine.cpp.
References Script::GetAI, Script::GetInstanceData, GOUse_go_ssc_boss_consoles(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_sethekk_halls()
void AddSC_instance_sethekk_halls ()
Definition at line 297 of file sethekk_halls.cpp.
References Script::GetInstanceData, GetInstanceData_instance_sethekk_halls(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_summon_raven_god(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_shadow_labyrinth()
void AddSC_instance_shadow_labyrinth ()
Definition at line 248 of file shadow_labyrinth.cpp.
References GetAIgo_screaming_hall_door(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_instance_shadow_labyrinth(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_shadowfang_keep()
void AddSC_instance_shadowfang_keep ()
Definition at line 462 of file instance_shadowfang_keep.cpp.
References Script::GetInstanceData, GetInstanceData_instance_shadowfang_keep(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_shattered_halls()
void AddSC_instance_shattered_halls ()
Definition at line 943 of file shattered_halls.cpp.
References AreaTrigger_at_shattered_halls(), Script::GetAI, Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_slave_pens()
void AddSC_instance_slave_pens ()
Definition at line 138 of file slave_pens.cpp.
References AreaTrigger_at_naturalist_bite(), Script::GetInstanceData, GossipHello_npc_naturalist_bite(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_steam_vault()
void AddSC_instance_steam_vault ()
Definition at line 195 of file steam_vault.cpp.
References Script::GetInstanceData, GetInstanceData_instance_steam_vault(), GOUse_go_main_chambers_access_panel(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_stratholme()
void AddSC_instance_stratholme ()
Definition at line 1282 of file stratholme.cpp.
References Script::GetInstanceData, GetInstanceData_instance_stratholme(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_sunken_temple()
void AddSC_instance_sunken_temple ()
Definition at line 521 of file sunken_temple.cpp.
References Script::GetInstanceData, GetInstanceData_instance_sunken_temple(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_sunwell_plateau()
void AddSC_instance_sunwell_plateau ()
Definition at line 882 of file sunwell_plateau.cpp.
References AreaTrigger_at_sunwell_plateau(), Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_temple_of_ahnqiraj()
void AddSC_instance_temple_of_ahnqiraj ()
Definition at line 469 of file temple_of_ahnqiraj.cpp.
References AreaTrigger_at_temple_ahnqiraj(), Script::GetInstanceData, GetInstanceData_instance_temple_of_ahnqiraj(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_reset_cthun(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_the_eye()
void AddSC_instance_the_eye ()
Definition at line 232 of file the_eye.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_trial_of_the_champion()
void AddSC_instance_trial_of_the_champion ()
Definition at line 1188 of file instance_trial_of_the_champion.cpp.
References Script::GetInstanceData, GetInstanceData_instance_trial_of_the_champion(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_trial_of_the_crusader()
void AddSC_instance_trial_of_the_crusader ()
Definition at line 968 of file trial_of_the_crusader.cpp.
References Script::GetGameObjectAI, Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_uldaman()
void AddSC_instance_uldaman ()
Definition at line 325 of file instance_uldaman.cpp.
References Script::GetInstanceData, GetInstanceData_instance_uldaman(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_altar_boss_aggro(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_ulduar()
void AddSC_instance_ulduar ()
Definition at line 1758 of file ulduar.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ulduar(), Script::Name, Script::pProcessEventId, ProcessEventId_event_ulduar(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_underbog()
void AddSC_instance_underbog ()
Definition at line 104 of file underbog.cpp.
References AreaTrigger_at_ghazan_surface(), Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_utgarde_keep()
void AddSC_instance_utgarde_keep ()
Definition at line 270 of file utgarde_keep.cpp.
References Script::GetInstanceData, GetInstanceData_instance_utgarde_keep(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_vault_of_archavon()
void AddSC_instance_vault_of_archavon ()
Definition at line 26 of file instance_vault_of_archavon.cpp.
Referenced by AddScripts().
AddSC_instance_violet_hold()
void AddSC_instance_violet_hold ()
Definition at line 977 of file violet_hold.cpp.
References Script::GetInstanceData, GetInstanceData_instance_violet_hold(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_wailing_caverns()
void AddSC_instance_wailing_caverns ()
Definition at line 159 of file wailing_caverns.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_zulaman()
void AddSC_instance_zulaman ()
Definition at line 825 of file zulaman.cpp.
References Script::GetInstanceData, GetInstanceData_instance_zulaman(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_zulfarrak()
void AddSC_instance_zulfarrak ()
Definition at line 249 of file instance_zulfarrak.cpp.
References Script::GetInstanceData, GetInstanceData_instance_zulfarrak(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_instance_zulgurub()
void AddSC_instance_zulgurub ()
Definition at line 245 of file zulgurub.cpp.
References AreaTrigger_at_zulgurub(), Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ironforge()
void AddSC_ironforge ()
Definition at line 29 of file ironforge.cpp.
Referenced by AddScripts().
AddSC_isle_of_queldanas()
void AddSC_isle_of_queldanas ()
Definition at line 418 of file isle_of_queldanas.cpp.
References Script::GetAI, GetAI_npc_converted_sentry(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_item_scripts()
void AddSC_item_scripts ()
Definition at line 355 of file item_scripts.cpp.
References ItemUse_item_arcane_charges(), ItemUse_item_flying_machine(), ItemUse_item_gor_dreks_ointment(), ItemUse_item_orb_of_draconic_energy(), ItemUse_item_petrov_cluster_bombs(), Script::Name, Script::pItemUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_item_scripts_wotlk()
void AddSC_item_scripts_wotlk ()
Definition at line 143 of file item_scripts_wotlk.cpp.
Referenced by AddScripts().
AddSC_karazhan()
void AddSC_karazhan ()
Definition at line 592 of file karazhanScripts.cpp.
References Script::GetAI, GetAI_npc_barnesAI(), GetAI_npc_image_arcanagosAI(), GetAI_npc_image_of_medivhAI(), GossipHello_npc_barnes(), GossipSelect_npc_barnes(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, ProcessEventId_event_spell_medivh_journal(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_loch_modan()
void AddSC_loch_modan ()
Definition at line 130 of file loch_modan.cpp.
References Script::GetAI, GetAI_npc_miran(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_miran(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_lunar_festival()
void AddSC_lunar_festival ()
Definition at line 129 of file lunar_festival.cpp.
Referenced by AddScripts().
AddSC_magisters_terrace()
void AddSC_magisters_terrace ()
Definition at line 151 of file magisters_terraceScripts.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_scrying_orb(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_mana_tombs()
void AddSC_mana_tombs ()
Definition at line 293 of file mana_tombsScripts.cpp.
References Script::GetAI, GetAI_npc_shaheen(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_shaheen(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_midsummer_festival()
void AddSC_midsummer_festival ()
Definition at line 495 of file midsummer_festival.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, Script::pQuestRewardedGO, QuestRewardedBonfireDesecrate(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_mob_anubisath_sentinel()
void AddSC_mob_anubisath_sentinel ()
Definition at line 380 of file mob_anubisath_sentinel.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_molten_core()
void AddSC_molten_core ()
Definition at line 29 of file molten_coreScripts.cpp.
Referenced by AddScripts().
AddSC_moonglade()
void AddSC_moonglade ()
Definition at line 1068 of file moonglade.cpp.
References Script::GetAI, GetAI_boss_eranikus(), GetAI_npc_keeper_remulos(), GOUse_go_omen_cluster(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_keeper_remulos(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_mulgore()
void AddSC_mulgore ()
Definition at line 170 of file mulgore.cpp.
References Script::GetAI, GetAI_npc_kyle_the_frenzied(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_nagrand()
void AddSC_nagrand ()
Definition at line 658 of file nagrand.cpp.
References Script::GetAI, GetAI_mob_lump(), GetAI_npc_creditmarker_visit_with_ancestors(), GetAI_npc_nagrand_captive(), GossipHello_npc_gurthock(), Script::Name, Script::pGossipHello, Script::pQuestAcceptNPC, QuestAccept_npc_gurthock(), QuestAccept_npc_nagrand_captive(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_naxxramas()
void AddSC_naxxramas ()
Definition at line 70 of file naxxramasScripts.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_netherstorm()
void AddSC_netherstorm ()
Definition at line 4044 of file netherstorm.cpp.
References AreaTrigger_at_commander_dawnforge(), AreaTrigger_at_socrethar_seat(), Script::GetAI, GetAI_npc_bessy(), GetAI_npc_captured_vanguard(), GetAI_npc_commander_dawnforge(), GetAI_npc_dimensius(), GetAI_npc_drijya(), GetAI_npc_energy_ball(), GetAI_npc_manaforge_control_console(), GetAI_npc_manaforge_spawnAI(), GetAI_npc_maxx_a_million(), GetAI_npc_protectorate_demolitionist(), GetAI_npc_saeed(), GetAI_npc_salhadaar(), GetAI_npc_scrapped_fel_reaver(), GetAI_npc_void_conduit(), GetAI_npc_zeppit(), GossipHello_go_manaforge(), GossipHello_npc_adyen_the_lightwarden(), GossipSelect_go_manaforge(), GossipSelect_npc_adyen_the_lightwarden(), GossipSelect_npc_saeed(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pQuestAcceptNPC, QuestAccept_npc_bessy(), QuestAccept_npc_captured_vanguard(), QuestAccept_npc_drijya(), QuestAccept_npc_maxx_a_million(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_northrend_beasts()
void AddSC_northrend_beasts ()
Definition at line 1114 of file boss_northrend_beasts.cpp.
References EffectDummyCreature_worm_emerge(), Script::GetAI, Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_npc_professions()
void AddSC_npc_professions ()
Definition at line 375 of file npc_professions.cpp.
References GossipHello_npc_prof_leather(), GossipSelect_npc_prof_leather(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_npcs_special()
void AddSC_npcs_special ()
Definition at line 3115 of file npcs_special.cpp.
References EffectDummyCreature_npc_redemption_target(), Script::GetAI, GetAI_npc_air_force_bots(), GetAI_npc_chicken_cluck(), GetAI_npc_doctor(), GetAI_npc_garments_of_quests(), GetAI_npc_guardian(), GetAI_npc_injured_patient(), GetAI_npc_mojo(), GetAI_npc_redemption_target(), GetAI_npc_snakes(), GetAI_npc_spring_rabbit(), GetAI_npc_the_cleaner(), Script::GetGameObjectAI, GossipHello_npc_gossip_npc(), GossipHello_npc_innkeeper(), GossipSelect_npc_innkeeper(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_doctor(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_oculus()
void AddSC_oculus ()
Definition at line 113 of file oculusScripts.cpp.
Referenced by AddScripts().
AddSC_old_hillsbrad()
void AddSC_old_hillsbrad ()
Definition at line 1421 of file old_hillsbradScripts.cpp.
References AreaTrigger_at_bartolo_ginsetti(), AreaTrigger_at_beggar(), Script::GetAI, GetAI_npc_taretha(), GetAI_npc_thrall_old_hillsbrad(), GossipHello_npc_erozion(), GossipHello_npc_taretha(), GossipHello_npc_thrall_old_hillsbrad(), GossipSelect_npc_erozion(), GossipSelect_npc_taretha(), GossipSelect_npc_thrall_old_hillsbrad(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_orgrimmar()
void AddSC_orgrimmar ()
Definition at line 62 of file orgrimmar.cpp.
References GossipHello_npc_high_overlord_saurfang(), GossipHello_npc_overlord_runthalak(), Script::Name, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_OutlandWorldScript()
void AddSC_OutlandWorldScript ()
Definition at line 1929 of file world_outland.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_pit_of_saron()
void AddSC_pit_of_saron ()
Definition at line 315 of file pit_of_saronScripts.cpp.
References AreaTrigger_at_pit_of_saron(), Script::GetAI, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_quests_scripts()
void AddSC_quests_scripts ()
Definition at line 300 of file quest_scripts.cpp.
References Script::GetAI, GetAI_npc_xiri(), Script::Name, Script::pQuestRewardedNPC, QuestRewarded_tbc_attunement_titles(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_razorfen_downs()
void AddSC_razorfen_downs ()
Definition at line 306 of file razorfen_downs.cpp.
References Script::GetAI, GetAI_npc_belnistrasz(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_belnistrasz(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_razorfen_kraul()
void AddSC_razorfen_kraul ()
Definition at line 267 of file razorfen_kraul.cpp.
References EffectDummyCreature_npc_snufflenose_gopher(), Script::GetAI, GetAI_npc_snufflenose_gopher(), GetAI_npc_willix_the_importer(), Script::Name, Script::pEffectDummyNPC, Script::pQuestAcceptNPC, QuestAccept_npc_willix_the_importer(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_redridge_mountains()
void AddSC_redridge_mountains ()
Definition at line 143 of file redridge_mountains.cpp.
References Script::GetAI, GetAI_npc_corporal_keeshan(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_corporal_keeshan(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ruby_sanctum()
void AddSC_ruby_sanctum ()
Definition at line 65 of file ruby_sanctumScripts.cpp.
Referenced by AddScripts().
AddSC_ruins_of_ahnqiraj()
void AddSC_ruins_of_ahnqiraj ()
Definition at line 163 of file ruins_of_ahnqirajScripts.cpp.
References Script::GetAI, GetAI_mob_anubisath_guardian(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_scholomance()
void AddSC_scholomance ()
Definition at line 124 of file scholomance.cpp.
References Script::GetAI, GetAI_npc_spectral_tutor(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_scourge_invasion()
void AddSC_scourge_invasion ()
Definition at line 1314 of file scourge_invasion.cpp.
References Script::GetAI, Script::GetGameObjectAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_searing_gorge()
void AddSC_searing_gorge ()
Definition at line 144 of file searing_gorge.cpp.
References Script::GetAI, GetAI_npc_dorius_stonetender(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_dorius_stonetender(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_shade_of_the_horseman()
void AddSC_shade_of_the_horseman ()
Definition at line 1065 of file shade_of_the_horseman.cpp.
References Script::GetAI, Script::GetGameObjectAI, GossipHello_go_large_jack_o_lantern(), GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), GossipSelect_go_large_jack_o_lantern(), GossipSelect_npc_orphan_matron(), GOUse_go_large_jack_o_lantern(), Script::Name, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_orphan_matron(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_shadowfang_keep()
void AddSC_shadowfang_keep ()
Definition at line 639 of file shadowfang_keep.cpp.
References Script::GetAI, GossipHello_npc_shadowfang_prisoner(), GossipSelect_npc_shadowfang_prisoner(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_shadowmoon_valley()
void AddSC_shadowmoon_valley ()
Definition at line 5357 of file shadowmoon_valley.cpp.
References EffectDummyCreature_npc_dragonmaw_peon(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_npc_totem_of_spirits(), Script::GetAI, GetAI_mob_bt_battle_fighter(), GetAI_mob_enslaved_netherwing_drake(), GetAI_mob_mature_netherwing_drake(), GetAI_npc_bt_battle_sensor(), GetAI_npc_disobedient_dragonmaw_peon(), GetAI_npc_domesticated_felboar(), GetAI_npc_shadowlord_deathwail(), GetAI_npc_spawned_oronok_tornheart(), GetAI_npc_veneratus_spawn_node(), GetAI_npc_wilda(), GOQuestAccept_GO_crystal_prison(), GossipHello_npc_spawned_oronok_tornheart(), GossipSelect_npc_spawned_oronok_tornheart(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, Script::pQuestAcceptGO, Script::pQuestAcceptNPC, ProcessEventId_event_spell_soul_captured_credit(), QuestAccept_npc_commander(), QuestAccept_npc_dragonmaw_racer(), QuestAccept_npc_wilda(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_shartuul_transporter()
void AddSC_shartuul_transporter ()
Definition at line 924 of file shartuul_transporter.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_CharmDegrader(), ProcessEventId_CharmShivan(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_shattrath_city()
void AddSC_shattrath_city ()
Definition at line 730 of file shattrath_city.cpp.
References Script::GetAI, GetAI_npc_dirty_larry(), GetAI_npc_salsalabim(), GossipHello_npc_dirty_larry(), GossipSelect_npc_dirty_larry(), GossipSelect_npc_salsalabim(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestRewardedNPC, QuestRewarded_npc_adal(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_sholazar_basin()
void AddSC_sholazar_basin ()
Definition at line 642 of file sholazar_basin.cpp.
References EffectDummyCreature_npc_wants_fruit_credit(), Script::GetAI, GetAI_npc_helice(), GetAI_npc_injured_rainspeaker(), GetAI_npc_tipsy_mcmanus(), GossipHello_npc_tipsy_mcmanus(), GossipSelect_npc_tipsy_mcmanus(), GOUse_go_quest_still_at_it_credit(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_helice(), QuestAccept_npc_injured_rainspeaker(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_silithus()
void AddSC_silithus ()
Definition at line 1050 of file silithus.cpp.
References Script::GetAI, GetAI_npc_anachronos_the_ancient(), GetAI_npc_solenor(), GossipHello_npc_solenor(), GossipSelect_npc_solenor(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptGO, QuestAcceptGO_crystalline_tear(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_silvermoon_city()
void AddSC_silvermoon_city ()
Definition at line 29 of file silvermoon_city.cpp.
Referenced by AddScripts().
AddSC_silverpine_forest()
void AddSC_silverpine_forest ()
Definition at line 308 of file silverpine_forest.cpp.
References Script::GetAI, GetAI_npc_deathstalker_erland(), GetAI_npc_deathstalker_faerleia(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_deathstalker_erland(), QuestAccept_npc_deathstalker_faerleia(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_spell_scripts()
void AddSC_spell_scripts ()
Definition at line 1667 of file spell_scripts.cpp.
References EffectAuraDummy_spell_aura_dummy_npc(), EffectDummyCreature_spell_dummy_npc(), EffectDummyGameObj_spell_dummy_go(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyGO, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_spell_scripts_wotlk()
void AddSC_spell_scripts_wotlk ()
Definition at line 102 of file spell_scripts_wotlk.cpp.
Referenced by AddScripts().
AddSC_stonetalon_mountains()
void AddSC_stonetalon_mountains ()
Definition at line 217 of file stonetalon_mountains.cpp.
References Script::GetAI, GetAI_npc_kaya(), GetAIgo_covertops(), Script::GetGameObjectAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_kaya(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_storm_peaks()
void AddSC_storm_peaks ()
Definition at line 364 of file storm_peaks.cpp.
References EffectDummyCreature_npc_restless_frostborn(), Script::GetAI, GetAI_npc_floating_spirit(), GetAI_npc_injured_miner(), GossipHello_npc_injured_miner(), GossipSelect_npc_injured_miner(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_injured_miner(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_stormwind_city()
void AddSC_stormwind_city ()
Definition at line 1133 of file stormwind_city.cpp.
References Script::GetAI, GetAI_npc_bartleby(), GetAI_npc_dashel_stonefist(), GetAI_npc_reginald_windsor(), GetAI_npc_squire_rowe(), Script::GetGameObjectAI, GossipHello_npc_field_marshal_afrasiabi(), GossipHello_npc_lady_katrana_prestor(), GossipHello_npc_major_mattingly(), GossipHello_npc_reginald_windsor(), GossipHello_npc_squire_rowe(), GossipSelect_npc_lady_katrana_prestor(), GossipSelect_npc_reginald_windsor(), GossipSelect_npc_squire_rowe(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_bartleby(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_reginald_windsor(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_stranglethorn_vale()
void AddSC_stranglethorn_vale ()
Definition at line 110 of file stranglethorn_vale.cpp.
References Script::GetAI, GetAI_mob_yenniku(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_stratholme()
void AddSC_stratholme ()
Definition at line 353 of file stratholmeScripts.cpp.
References Script::GetAI, GetAI_mob_restless_soul(), GetAI_mobs_spectral_ghostly_citizen(), GossipHello_npc_aurius(), GOUse_go_gauntlet_gate(), GOUse_go_service_gate(), GOUse_go_stratholme_postbox(), Script::Name, Script::pGossipHello, Script::pGOUse, Script::pQuestRewardedNPC, QuestRewarded_npc_aurius(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_sunken_temple()
void AddSC_sunken_temple ()
Definition at line 285 of file sunken_templeScripts.cpp.
References AreaTrigger_at_shade_of_eranikus(), Script::GetAI, GetAI_npc_malfurion(), GOUse_go_eternal_flame(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_antalarion_statue_activation(), ProcessEventId_event_avatar_of_hakkar(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_suns_reach_reclamation()
void AddSC_suns_reach_reclamation ()
Definition at line 74 of file suns_reach_reclamation.cpp.
References Script::Name, Script::pQuestRewardedNPC, QuestRewarded_suns_reach_reclamation(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_sunwell_plateau()
void AddSC_sunwell_plateau ()
Definition at line 272 of file sunwell_plateauScripts.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_swamp_of_sorrows()
void AddSC_swamp_of_sorrows ()
Definition at line 157 of file swamp_of_sorrows.cpp.
References Script::GetAI, GetAI_npc_galen_goodward(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_galen_goodward(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_tanaris()
void AddSC_tanaris ()
Definition at line 554 of file tanaris.cpp.
References Script::GetAI, GetAI_mob_aquementas(), GetAI_npc_custodian_of_time(), GetAI_npc_oox17tn(), GetAI_npc_tooga(), GossipHello_npc_stone_watcher_of_norgannon(), GossipSelect_npc_stone_watcher_of_norgannon(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_oox17tn(), QuestAccept_npc_tooga(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_teldrassil()
void AddSC_teldrassil ()
Definition at line 104 of file teldrassil.cpp.
References Script::GetAI, GetAI_npc_mist(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_mist(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_terokkar_forest()
void AddSC_terokkar_forest ()
Definition at line 1290 of file terokkar_forest.cpp.
References Script::GetAI, GetAI_go_monstrous_kaliri_egg(), GetAI_mob_netherweb_victim(), GetAI_mob_unkor_the_ruthless(), GetAI_npc_akuno(), GetAI_npc_avatar_of_terokk(), GetAI_npc_cenarion_sparrowhawk(), GetAI_npc_hungry_nether_ray(), GetAI_npc_isla_starmane(), GetAI_npc_letoll(), GetAI_npc_minion_of_terokk(), GetAI_npc_skyguard_prisoner(), GetAI_npc_skywing(), Script::GetGameObjectAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_akuno(), QuestAccept_npc_isla_starmane(), QuestAccept_npc_letoll(), QuestAccept_npc_skyguard_prisoner(), QuestAccept_npc_skywing(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_the_barrens()
void AddSC_the_barrens ()
Definition at line 1095 of file the_barrens.cpp.
References AreaTrigger_at_twiggy_flathead(), Script::GetAI, GetAI_npc_foreman_silixiz(), GetAI_npc_gallywix(), GetAI_npc_gilthares(), GetAI_npc_regthar_deathgate(), GetAI_npc_taskmaster_fizzule(), GetAI_npc_twiggy_flathead(), GetAI_npc_venture_co_lookout(), GetAI_npc_wizzlecranks_shredder(), GossipHello_npc_regthar_deathgate(), GossipSelect_npc_regthar_deathgate(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_gilthares(), QuestAccept_npc_regthar_deathgate(), QuestAccept_npc_wizzlecranks_shredder(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_thousand_needles()
void AddSC_thousand_needles ()
Definition at line 379 of file thousand_needles.cpp.
References Script::GetAI, GetAI_npc_lakota_windsong(), GetAI_npc_paoka_swiftmountain(), GetAI_npc_plucky_johnson(), GossipHello_npc_plucky_johnson(), GossipSelect_npc_plucky_johnson(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_kanati(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_paoka_swiftmountain(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_thunder_bluff()
void AddSC_thunder_bluff ()
Definition at line 30 of file thunder_bluff.cpp.
Referenced by AddScripts().
AddSC_tirisfal_glades()
void AddSC_tirisfal_glades ()
Definition at line 179 of file tirisfal_glades.cpp.
References Script::GetAI, GetAI_npc_calvin_montague(), GOUse_go_mausoleum_door(), GOUse_go_mausoleum_trigger(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_calvin_montague(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_trial_of_the_champion()
void AddSC_trial_of_the_champion ()
Definition at line 96 of file trial_of_the_champion.cpp.
References GossipHello_npc_toc_herald(), GossipSelect_npc_toc_herald(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_trial_of_the_crusader()
void AddSC_trial_of_the_crusader ()
Definition at line 208 of file trial_of_the_crusaderScripts.cpp.
References Script::GetAI, GetAI_npc_barrett_ramsey(), GossipHello_npc_barrett_ramsey(), GossipSelect_npc_barrett_ramsey(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_twin_valkyr()
void AddSC_twin_valkyr ()
Definition at line 517 of file boss_twin_valkyr.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_uldaman()
void AddSC_uldaman ()
Definition at line 27 of file uldaman.cpp.
Referenced by AddScripts().
AddSC_ulduar()
void AddSC_ulduar ()
Definition at line 612 of file ulduarScripts.cpp.
References Script::GetAI, GetAI_npc_charged_sphere(), GetAI_npc_storm_tempered_keeper(), GossipHello_go_ulduar_teleporter(), GossipHello_npc_brann_ulduar(), GossipHello_npc_keeper_norgannon(), GossipHello_npc_ulduar_keeper(), GossipSelect_go_ulduar_teleporter(), GossipSelect_npc_brann_ulduar(), GossipSelect_npc_keeper_norgannon(), GossipSelect_npc_ulduar_keeper(), GOUse_go_activate_tram(), Script::Name, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_go_ulduar_tower(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_undercity()
void AddSC_undercity ()
Definition at line 175 of file undercity.cpp.
References Script::GetAI, GetAI_npc_lady_sylvanas_windrunner(), Script::Name, Script::pQuestRewardedNPC, QuestRewarded_npc_lady_sylvanas_windrunner(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_ungoro_crater()
void AddSC_ungoro_crater ()
Definition at line 807 of file ungoro_crater.cpp.
References Script::GetAI, GetAI_npc_ame01(), GetAI_npc_precious_the_devourer(), GetAI_npc_ringo(), GetAI_npc_simone_seductress(), GetAI_npc_simone_the_inconspicuous(), GossipHello_npc_simone_the_inconspicuous(), GossipSelect_npc_simone_the_inconspicuous(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_ame01(), QuestAccept_npc_ringo(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_utgarde_keep()
void AddSC_utgarde_keep ()
Definition at line 173 of file utgarde_keepScripts.cpp.
References Script::GetAI, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_violet_hold()
void AddSC_violet_hold ()
Definition at line 431 of file violet_holdScripts.cpp.
References EffectDummyCreature_npc_door_seal(), EffectDummyCreature_npc_teleportation_portal(), Script::GetAI, GossipHello_npc_sinclari(), GossipSelect_npc_sinclari(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_wailing_caverns()
void AddSC_wailing_caverns ()
Definition at line 522 of file wailing_cavernsScripts.cpp.
References Script::GetAI, GossipHello_npc_disciple_of_naralex(), GossipSelect_npc_disciple_of_naralex(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_war_effort()
void AddSC_war_effort ()
Definition at line 268 of file war_effort.cpp.
References Script::GetAI, Script::Name, Script::pQuestRewardedGO, Script::pQuestRewardedNPC, QuestRewarded_war_effort(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_western_plaguelands()
void AddSC_western_plaguelands ()
Definition at line 1122 of file western_plaguelands.cpp.
References EffectDummyCreature_npc_taelan_fordring(), Script::GetAI, GetAI_npc_anchorite_truuen(), GetAI_npc_isillien(), GetAI_npc_taelan_fordring(), GetAI_npc_the_scourge_cauldron(), GetAI_npc_tirion_fordring(), Script::Name, Script::pEffectDummyNPC, Script::pQuestAcceptNPC, Script::pQuestRewardedNPC, QuestAccept_npc_anchorite_truuen(), QuestAccept_npc_taelan_fordring(), QuestRewarded_npc_taelan_fordring(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_westfall()
void AddSC_westfall ()
Definition at line 427 of file westfall.cpp.
References Script::GetAI, GetAI_npc_daphne_stilwell(), GetAI_npc_defias_traitor(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_daphne_stilwell(), QuestAccept_npc_defias_traitor(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_wetlands()
void AddSC_wetlands ()
Definition at line 227 of file wetlands.cpp.
References Script::GetAI, GetAI_npc_tapoke_slim_jahn(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_mikhail(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_wintergrasp()
void AddSC_wintergrasp ()
Definition at line 281 of file wintergrasp.cpp.
References Script::GetAI, GetAI_go_vehicle_teleporter(), GetAI_npc_spirit_guide_wintergrasp(), Script::GetGameObjectAI, Script::Name, Script::pProcessEventId, ProcessEventId_event_go_tower_destroy(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_winterspring()
void AddSC_winterspring ()
Definition at line 721 of file winterspring.cpp.
References Script::GetAI, GetAI_npc_artorius(), GetAI_npc_ranshalla(), GossipHello_npc_artorius(), GossipSelect_npc_artorius(), GOUse_go_elune_fire(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_ranshalla(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_world_eastern_kingdoms()
void AddSC_world_eastern_kingdoms ()
Definition at line 476 of file world_eastern_kingdoms.cpp.
References Script::GetAI, GetAI_go_infernaling_summoner_portal_hound(), GetAI_npc_agent_proudwell(), Script::GetGameObjectAI, Script::GetInstanceData, GetInstanceData_world_map_eastern_kingdoms(), GOUse_go_infernaling_summoner_portal_hound(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_world_kalimdor()
void AddSC_world_kalimdor ()
Definition at line 468 of file world_kalimdor.cpp.
References Script::GetInstanceData, GetInstanceData_world_map_kalimdor(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_world_map_ebon_hold()
void AddSC_world_map_ebon_hold ()
Definition at line 516 of file world_map_ebon_hold.cpp.
References GetInstance_world_map_ebon_hold(), Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_world_map_scripts()
void AddSC_world_map_scripts ()
Definition at line 264 of file world_map_scripts.cpp.
References Script::Name, Script::pProcessEventId, ProcessEventTransports(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_world_northrend()
void AddSC_world_northrend ()
Definition at line 48 of file world_northrend.cpp.
References Script::GetInstanceData, Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_zangarmarsh()
void AddSC_zangarmarsh ()
Definition at line 454 of file zangarmarsh.cpp.
References Script::GetAI, GetAI_npc_cooshcoosh(), GetAI_npc_fhwoor(), GetAI_npc_frostbite(), GetAI_npc_kayra_longmane(), Script::Name, Script::pProcessEventId, Script::pQuestAcceptNPC, ProcessEventId_event_taxi_stormcrow(), QuestAccept_npc_fhwoor(), QuestAccept_npc_kayra_longmane(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_zulaman()
void AddSC_zulaman ()
Definition at line 2267 of file zulamanScripts.cpp.
References Script::GetAI, GossipHello_npc_ashli(), GossipHello_npc_harkor(), GossipHello_npc_harrison_jones_za(), GossipHello_npc_kraz(), GossipHello_npc_tanzar(), GossipSelect_npc_ashli(), GossipSelect_npc_harkor(), GossipSelect_npc_harrison_jones_za(), GossipSelect_npc_kraz(), GossipSelect_npc_tanzar(), GOUse_go_wooden_door(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_ritual_of_power(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_zuldrak()
void AddSC_zuldrak ()
Definition at line 841 of file zuldrak.cpp.
References AreaTrigger_at_overlord_drakuru(), EffectDummyCreature_npc_decaying_ghoul(), Script::GetAI, GetAI_npc_decaying_ghoul(), GetAI_npc_ghoul_feeding_bunny(), Script::Name, Script::pAreaTrigger, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_zulfarrak()
void AddSC_zulfarrak ()
Definition at line 105 of file zulfarrak.cpp.
References AreaTrigger_at_zulfarrak(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_go_zulfarrak_gong(), ProcessEventId_event_spell_unlocking(), and Script::RegisterSelf().
Referenced by AddScripts().
AddSC_zulgurub()
void AddSC_zulgurub ()
Definition at line 190 of file zulgurubScripts.cpp.
References Script::GetAI, GetAI_npc_soulflayer(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
AddScripts()
void AddScripts ()
Definition at line 506 of file ScriptLoader.cpp.
References AddSC_alterac_mountains(), AddSC_arathi_highlands(), AddSC_arcatraz(), AddSC_areatrigger_scripts(), AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bashir_landing(), AddSC_battleground(), AddSC_black_temple(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_blasted_lands(), AddSC_blood_prince_council(), AddSC_bloodmyst_isle(), AddSC_borean_tundra(), AddSC_boss_aeonus(), AddSC_boss_ahune(), AddSC_boss_akilzon(), AddSC_boss_alar(), AddSC_boss_algalon(), AddSC_boss_amanitar(), AddSC_boss_ambassador_flamelash(), AddSC_boss_ambassador_hellmaw(), AddSC_boss_anetheron(), AddSC_boss_anomalus(), AddSC_boss_anubarak(), AddSC_boss_anubarak_trial(), AddSC_boss_anubrekhan(), AddSC_boss_anzu(), AddSC_boss_arcanist_doan(), AddSC_boss_archaedas(), AddSC_boss_archavon(), AddSC_boss_archimonde(), AddSC_boss_argent_challenge(), AddSC_boss_arlokk(), AddSC_boss_assembly_of_iron(), AddSC_boss_attumen(), AddSC_boss_auriaya(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_baltharus(), AddSC_boss_baron_geddon(), AddSC_boss_baroness_anastari(), AddSC_boss_bjarngrim(), AddSC_boss_black_knight(), AddSC_boss_black_stalker(), AddSC_boss_blackheart_the_inciter(), AddSC_boss_blood_queen_lanathel(), AddSC_boss_broggok(), AddSC_boss_bronjahm(), AddSC_boss_broodlord(), AddSC_boss_brutallus(), AddSC_boss_buru(), AddSC_boss_cannon_master_willey(), AddSC_boss_chromaggus(), AddSC_boss_chrono_lord_deja(), AddSC_boss_colossus(), AddSC_boss_coren_direbrew(), AddSC_boss_cthun(), AddSC_boss_curator(), AddSC_boss_dalliah(), AddSC_boss_darkmaster_gandling(), AddSC_boss_darkweaver_syth(), AddSC_boss_dathrohan_balnazzar(), AddSC_boss_deathbringer_saurfang(), AddSC_boss_devourer_of_souls(), AddSC_boss_doomlordkazzak(), AddSC_boss_doomwalker(), AddSC_boss_draganthaurissan(), AddSC_boss_ebonroc(), AddSC_boss_eck(), AddSC_boss_emalon(), AddSC_boss_eredar_twins(), AddSC_boss_eregos(), AddSC_boss_exarch_maladaar(), AddSC_boss_faction_champions(), AddSC_boss_faerlina(), AddSC_boss_fankriss(), AddSC_boss_fathomlord_karathress(), AddSC_boss_felblood_kaelthas(), AddSC_boss_felmyst(), AddSC_boss_festergut(), AddSC_boss_firemaw(), AddSC_boss_flame_leviathan(), AddSC_boss_flamegor(), AddSC_boss_four_horsemen(), AddSC_boss_freya(), AddSC_boss_galdarah(), AddSC_boss_garfrost(), AddSC_boss_garr(), AddSC_boss_gehennas(), AddSC_boss_general_angerforge(), AddSC_boss_general_vezax(), AddSC_boss_gluth(), AddSC_boss_golemagg(), AddSC_boss_gortok(), AddSC_boss_gothik(), AddSC_boss_grand_champions(), AddSC_boss_grand_warlock_nethekurse(), AddSC_boss_grandmaster_vorpil(), AddSC_boss_grobbulus(), AddSC_boss_gruul(), AddSC_boss_gurtogg_bloodboil(), AddSC_boss_gyth(), AddSC_boss_hadronox(), AddSC_boss_hakkar(), AddSC_boss_halazzi(), AddSC_boss_halion(), AddSC_boss_harbinger_skyriss(), AddSC_boss_headless_horseman(), AddSC_boss_heigan(), AddSC_boss_herod(), AddSC_boss_high_astromancer_solarian(), AddSC_boss_high_botanist_freywinn(), AddSC_boss_high_interrogator_gerstahn(), AddSC_boss_high_king_maulgar(), AddSC_boss_highlord_kruul(), AddSC_boss_hodir(), AddSC_boss_huhuran(), AddSC_boss_hummel(), AddSC_boss_hungarfen(), AddSC_boss_hydromancer_thespia(), AddSC_boss_hydross_the_unstable(), AddSC_boss_ichoron(), AddSC_boss_ignis(), AddSC_boss_illidan(), AddSC_boss_illidari_council(), AddSC_boss_ingvar(), AddSC_boss_ionar(), AddSC_boss_janalai(), AddSC_boss_jandicebarov(), AddSC_boss_jaraxxus(), AddSC_boss_jedoga(), AddSC_boss_jeklik(), AddSC_boss_kaelthas(), AddSC_boss_kalecgos(), AddSC_boss_kazrogal(), AddSC_boss_kazzakAI(), AddSC_boss_keleseth(), AddSC_boss_kelidan_the_breaker(), AddSC_boss_kelthuzad(), AddSC_boss_keristrasza(), AddSC_boss_kiljaeden(), AddSC_boss_kologarn(), AddSC_boss_koralon(), AddSC_boss_krick_and_ick(), AddSC_boss_krikthir(), AddSC_boss_kurinnaxx(), AddSC_boss_lady_deathwhisper(), AddSC_boss_lady_vashj(), AddSC_boss_laj(), AddSC_boss_leotheras_the_blind(), AddSC_boss_lich_king(), AddSC_boss_loatheb(), AddSC_boss_loken(), AddSC_boss_lord_marrowgar(), AddSC_boss_lucifron(), AddSC_boss_maexxna(), AddSC_boss_magmadar(), AddSC_boss_magtheridon(), AddSC_boss_maiden_of_virtue(), AddSC_boss_majordomo(), AddSC_boss_malacrass(), AddSC_boss_maleki_the_pallid(), AddSC_boss_malygos(), AddSC_boss_mandokir(), AddSC_boss_marli(), AddSC_boss_mechano_lord_capacitus(), AddSC_boss_mekgineer_steamrigger(), AddSC_boss_mimiron(), AddSC_boss_moam(), AddSC_boss_mograine_and_whitemane(), AddSC_boss_moorabi(), AddSC_boss_moroes(), AddSC_boss_morogrim_tidewalker(), AddSC_boss_mother_shahraz(), AddSC_boss_mr_smite(), AddSC_boss_murmur(), AddSC_boss_muru(), AddSC_boss_nadox(), AddSC_boss_najentus(), AddSC_boss_nalorakk(), AddSC_boss_nazan_and_vazruden(), AddSC_boss_nefarian(), AddSC_boss_nethermancer_sepethrea(), AddSC_boss_netherspite(), AddSC_boss_nexusprince_shaffar(), AddSC_boss_nightbane(), AddSC_boss_noth(), AddSC_boss_novos(), AddSC_boss_noxxion(), AddSC_boss_omor_the_unscarred(), AddSC_boss_onyxia(), AddSC_boss_order_of_silver_hand(), AddSC_boss_ormorok(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_overlordwyrmthalak(), AddSC_boss_pandemonius(), AddSC_boss_patchwerk(), AddSC_boss_pathaleon_the_calculator(), AddSC_boss_priestess_delrissa(), AddSC_boss_prince_malchezaar(), AddSC_boss_professor_putricide(), AddSC_boss_pyroguard_emberseer(), AddSC_boss_rage_winterchill(), AddSC_boss_ragnaros(), AddSC_boss_rajaxx(), AddSC_boss_razorgore(), AddSC_boss_razorscale(), AddSC_boss_razuvious(), AddSC_boss_reliquary_of_souls(), AddSC_boss_renataki(), AddSC_boss_rotface(), AddSC_boss_sapphiron(), AddSC_boss_sartharion(), AddSC_boss_sartura(), AddSC_boss_saviana(), AddSC_boss_selin_fireheart(), AddSC_boss_shade_of_akama(), AddSC_boss_shade_of_aran(), AddSC_boss_shazzrah(), AddSC_boss_shirrak(), AddSC_boss_sindragosa(), AddSC_boss_sjonnir(), AddSC_boss_skadi(), AddSC_boss_skeram(), AddSC_boss_sladran(), AddSC_boss_soccothrates(), AddSC_boss_sulfuron(), AddSC_boss_supremus(), AddSC_boss_svala(), AddSC_boss_swamplord_muselek(), AddSC_boss_taldaram(), AddSC_boss_talon_king_ikiss(), AddSC_boss_telestra(), AddSC_boss_temporus(), AddSC_boss_terestian_illhoof(), AddSC_boss_terokk(), AddSC_boss_teron_gorefiend(), AddSC_boss_thaddius(), AddSC_boss_tharonja(), AddSC_boss_the_lich_king(), AddSC_boss_the_lurker_below(), AddSC_boss_the_maker(), AddSC_boss_thekal(), AddSC_boss_thermaplugg(), AddSC_boss_thorim(), AddSC_boss_thorngrin(), AddSC_boss_toravon(), AddSC_boss_trollgore(), AddSC_boss_twinemperors(), AddSC_boss_tyrannus(), AddSC_boss_urom(), AddSC_boss_vaelastrasz(), AddSC_boss_valithria_dreamwalker(), AddSC_boss_varos(), AddSC_boss_venoxis(), AddSC_boss_vexallus(), AddSC_boss_victor_nefarius(), AddSC_boss_viscidus(), AddSC_boss_void_reaver(), AddSC_boss_volazj(), AddSC_boss_volkhan(), AddSC_boss_warbringer_omrogg(), AddSC_boss_warchief_kargath_bladefist(), AddSC_boss_warlord_kalithresh(), AddSC_boss_warp_splinter(), AddSC_boss_watchkeeper_gargolmar(), AddSC_boss_xevozz(), AddSC_boss_xt_002(), AddSC_boss_ymiron(), AddSC_boss_yogg_saron(), AddSC_boss_yor(), AddSC_boss_zarithrian(), AddSC_boss_zuljin(), AddSC_boss_zumrah(), AddSC_bosses_emerald_dragons(), AddSC_bosses_opera(), AddSC_brewfest(), AddSC_bug_trio(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_childrens_week_tbc(), AddSC_culling_of_stratholme(), AddSC_dalaran(), AddSC_dark_portal(), AddSC_darkshore(), AddSC_deadmines(), AddSC_desolace(), AddSC_dire_maul(), AddSC_dragonblight(), AddSC_dun_morogh(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_eastern_plaguelands(), AddSC_ebon_hold(), AddSC_elwynn_forest(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_example_gossip_codebox(), AddSC_example_misc(), AddSC_felwood(), AddSC_feralas(), AddSC_generic_creature(), AddSC_ghostlands(), AddSC_gnomeregan(), AddSC_go_scripts(), AddSC_grizzly_hills(), AddSC_guards(), AddSC_gunship_battle(), AddSC_hallows_end(), AddSC_halls_of_reflection(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_howling_fjord(), AddSC_hyjal(), AddSC_icecrown(), AddSC_icecrown_citadel(), AddSC_instance_ahnkahet(), AddSC_instance_arcatraz(), AddSC_instance_azjol_nerub(), AddSC_instance_black_temple(), AddSC_instance_blackfathom_deeps(), AddSC_instance_blackrock_depths(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_blood_furnace(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dark_portal(), AddSC_instance_deadmines(), AddSC_instance_dire_maul(), AddSC_instance_draktharon_keep(), AddSC_instance_eye_of_eternity(), AddSC_instance_forge_of_souls(), AddSC_instance_gnomeregan(), AddSC_instance_gruuls_lair(), AddSC_instance_gundrak(), AddSC_instance_halls_of_lightning(), AddSC_instance_halls_of_reflection(), AddSC_instance_halls_of_stone(), AddSC_instance_icecrown_citadel(), AddSC_instance_karazhan(), AddSC_instance_magisters_terrace(), AddSC_instance_magtheridons_lair(), AddSC_instance_maraudon(), AddSC_instance_mechanar(), AddSC_instance_molten_core(), AddSC_instance_mount_hyjal(), AddSC_instance_naxxramas(), AddSC_instance_nexus(), AddSC_instance_obsidian_sanctum(), AddSC_instance_oculus(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_pinnacle(), AddSC_instance_pit_of_saron(), AddSC_instance_ramparts(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruby_sanctum(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_scarlet_monastery(), AddSC_instance_scholomance(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_sethekk_halls(), AddSC_instance_shadow_labyrinth(), AddSC_instance_shadowfang_keep(), AddSC_instance_shattered_halls(), AddSC_instance_slave_pens(), AddSC_instance_steam_vault(), AddSC_instance_stratholme(), AddSC_instance_sunken_temple(), AddSC_instance_sunwell_plateau(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_eye(), AddSC_instance_trial_of_the_champion(), AddSC_instance_trial_of_the_crusader(), AddSC_instance_uldaman(), AddSC_instance_ulduar(), AddSC_instance_underbog(), AddSC_instance_utgarde_keep(), AddSC_instance_vault_of_archavon(), AddSC_instance_violet_hold(), AddSC_instance_wailing_caverns(), AddSC_instance_zulaman(), AddSC_instance_zulfarrak(), AddSC_instance_zulgurub(), AddSC_ironforge(), AddSC_isle_of_queldanas(), AddSC_item_scripts(), AddSC_item_scripts_wotlk(), AddSC_karazhan(), AddSC_loch_modan(), AddSC_lunar_festival(), AddSC_magisters_terrace(), AddSC_mana_tombs(), AddSC_midsummer_festival(), AddSC_mob_anubisath_sentinel(), AddSC_molten_core(), AddSC_moonglade(), AddSC_mulgore(), AddSC_nagrand(), AddSC_naxxramas(), AddSC_netherstorm(), AddSC_northrend_beasts(), AddSC_npc_professions(), AddSC_npcs_special(), AddSC_oculus(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_OutlandWorldScript(), AddSC_pit_of_saron(), AddSC_quests_scripts(), AddSC_razorfen_downs(), AddSC_razorfen_kraul(), AddSC_redridge_mountains(), AddSC_ruby_sanctum(), AddSC_ruins_of_ahnqiraj(), AddSC_scholomance(), AddSC_scourge_invasion(), AddSC_searing_gorge(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shartuul_transporter(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_silvermoon_city(), AddSC_silverpine_forest(), AddSC_spell_scripts(), AddSC_spell_scripts_wotlk(), AddSC_stonetalon_mountains(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_stranglethorn_vale(), AddSC_stratholme(), AddSC_sunken_temple(), AddSC_suns_reach_reclamation(), AddSC_sunwell_plateau(), AddSC_swamp_of_sorrows(), AddSC_tanaris(), AddSC_teldrassil(), AddSC_terokkar_forest(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_thunder_bluff(), AddSC_tirisfal_glades(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_twin_valkyr(), AddSC_uldaman(), AddSC_ulduar(), AddSC_undercity(), AddSC_ungoro_crater(), AddSC_utgarde_keep(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_war_effort(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_wetlands(), AddSC_wintergrasp(), AddSC_winterspring(), AddSC_world_eastern_kingdoms(), AddSC_world_kalimdor(), AddSC_world_map_ebon_hold(), AddSC_world_map_scripts(), AddSC_world_northrend(), AddSC_zangarmarsh(), AddSC_zulaman(), AddSC_zuldrak(), AddSC_zulfarrak(), and AddSC_zulgurub().
Referenced by ScriptDevAIMgr::Initialize().