CMaNGOS_WoTLK: ScriptDevAIMgr.cpp File Reference
ScriptDevAIMgr.cpp File Reference
#include "include/sc_common.h"
#include "Policies/Singleton.h"
#include "Config/Config.h"
#include "Database/DatabaseEnv.h"
#include "Server/DBCStores.h"
#include "Globals/ObjectMgr.h"
#include "Util/ProgressBar.h"
#include "system/system.h"
#include "ScriptDevAIMgr.h"
#include "Spells/SpellAuras.h"
Functions
INSTANTIATE_SINGLETON_1 (ScriptDevAIMgr)
void FillSpellSummary ()
void LoadDatabase ()
void DoScriptText (int32 iTextEntry, WorldObject *pSource, Unit *pTarget, uint32 chatTypeOverride)
Function that does script text.
void DoBroadcastText (int32 iTextEntry, WorldObject *pSource, Unit *pTarget, uint32 chatTypeOverride)
Function that does broadcast text.
void DoOrSimulateScriptTextForMap (int32 iTextEntry, uint32 uiCreatureEntry, Map *pMap, Creature *pCreatureSource, Unit *pTarget)
Function that either simulates or does script text for a map.
Function Documentation
DoBroadcastText()
void DoBroadcastText (int32 iTextEntry, WorldObject * pSource, Unit * pTarget, uint32 chatTypeOverride)
Function that does broadcast text.
Parameters
iTextEntry Entry of the text
pSource Source of the text
pTarget Can be nullptr (depending on CHAT_TYPE of iTextEntry). Possible target for the text
Definition at line 69 of file ScriptDevAIMgr.cpp.
References DoDisplayText(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetTypeId(), and script_error_log().
Referenced by npc_tesla_coilAI::Aggro(), npc_dorius_stonetenderAI::Aggro(), npc_captured_arkonarinAI::Aggro(), npc_guardianAI::Aggro(), BossAI::Aggro(), AreaTrigger_at_beggar(), AreaTrigger_at_overlord_drakuru(), npc_disciple_of_naralexAI::AttackedBy(), boss_gothikAI::boss_gothikAI(), npc_theramore_spar_controller::CombatantIntro(), npc_theramore_spar_controller::CombatantSalute(), boss_galdarahAI::DoPhaseSwitch(), boss_sladranAI::ExecuteAction(), boss_lady_blaumeuxAI::ExecuteAction(), boss_rivendare_naxxAI::ExecuteAction(), boss_thane_korthazzAI::ExecuteAction(), boss_sir_zeliekAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_maexxnaAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_patchwerkAI::ExecuteAction(), boss_sapphironAI::ExecuteAction(), PallidHorrorAI::ExecuteAction(), GossipSelect_npc_prospector_anvilward(), npc_theramore_spar_controller::HandleBlueWin(), boss_gothikAI::HandleGroundPhase(), boss_heiganAI::HandleGroundPhase(), BrewfestEvent::HandleKegTappingEvent(), npc_theramore_spar_controller::HandleMotivation(), npc_theramore_spar_controller::HandleRedWin(), boss_heiganAI::HandleStartChanneling(), boss_heiganAI::HandleTaunt(), npc_theramore_spar_controller::HandleWin(), boss_thekalAI::JustDied(), boss_lady_blaumeuxAI::JustDied(), boss_rivendare_naxxAI::JustDied(), boss_thane_korthazzAI::JustDied(), boss_sir_zeliekAI::JustDied(), boss_stalaggAI::JustDied(), boss_feugenAI::JustDied(), PallidHorrorAI::JustDied(), BossAI::JustDied(), SilithusBossAI::JustRespawned(), npc_vimgol_middle_bunnyAI::JustSummoned(), boss_anubrekhanAI::JustSummoned(), npc_ethereal_frostworgAI::JustSummoned(), CombatAI::KilledUnit(), MouthAI::MouthAI(), boss_anubrekhanAI::MoveInLineOfSight(), boss_faerlinaAI::MoveInLineOfSight(), npc_theramore_spar_controller::MoveIntoPosition(), npc_ethereal_frostworgAI::MovementInform(), boss_sapphironAI::MovementInform(), npc_vimgol_AI::MovementInform(), npc_ethereal_frostworgAI::npc_ethereal_frostworgAI(), WidowsEmbrace::OnApply(), MutatingInjection::OnApply(), AuraPreWarning::OnApply(), AuraWarning::OnApply(), CharmDrakuruServant::OnApply(), DropDisguise::OnApply(), ScourgeDisguiseExpiring::OnApply(), FetchAlchemistsApprentice::OnApply(), BrewfestBarkerBunny::OnApply(), CallOfTheFalcon::OnApply(), DemoniacVisitation::OnApply(), TriggerTeslas::OnEffectExecute(), IceBolt::OnEffectExecute(), PotCheck::OnEffectExecute(), ImpInABottleSay::OnEffectExecute(), GossipNPCPeriodicTriggerTalk::OnEffectExecute(), TribalDeath::OnEffectExecute(), ZombieChowSearch::OnPeriodicTrigger(), SummonSkeletonsNoth::OnPeriodicTrigger(), boss_lady_blaumeuxAI::OnSpellCast(), boss_sir_zeliekAI::OnSpellCast(), boss_maexxnaAI::OnSpellCast(), boss_thaddiusAI::OnSpellCooldownAdded(), npc_foreman_klaven_mortwakeAI::OnStealthAlert(), boss_gothikAI::ProcessCentralDoor(), QuestAccept_npc_ranger_lilatha(), MouthAI::ReceiveAIEvent(), ScourgeMinion::ReceiveAIEvent(), instance_wailing_caverns::SetData(), boss_razuviousAI::SpellHit(), npc_bartolo_ginsetti::StartScript(), npc_brewfest_barker::StartScript(), npc_theramore_spar_controller::StartSparring(), boss_anubrekhanAI::SummonedCreatureDespawn(), npc_bartolo_ginsetti::UpdateAI(), npc_redemption_targetAI::UpdateAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_ranger_lilathaAI::WaypointReached(), npc_prospector_anvilwardAI::WaypointReached(), npc_dorius_stonetenderAI::WaypointReached(), npc_captured_arkonarinAI::WaypointReached(), npc_kanatiAI::WaypointReached(), and npc_disciple_of_naralexAI::WaypointReached().
DoOrSimulateScriptTextForMap()
void DoOrSimulateScriptTextForMap (int32 iTextEntry, uint32 uiCreatureEntry, Map * pMap, Creature * pCreatureSource, Unit * pTarget)
Function that either simulates or does script text for a map.
Parameters
iTextEntry Entry of the text, stored in SD2-database, only type CHAT_TYPE_ZONE_YELL supported
uiCreatureEntry Id of the creature of whom saying will be simulated
pMap Given Map on which the map-wide text is displayed
pCreatureSource Can be nullptr. If pointer to Creature is given, then the creature does the map-wide text
pTarget Can be nullptr. Possible target for the text
Definition at line 96 of file ScriptDevAIMgr.cpp.
References CHAT_MSG_MONSTER_EMOTE, CHAT_MSG_MONSTER_YELL, CHAT_TYPE_ZONE_EMOTE, CHAT_TYPE_ZONE_YELL, debug_log(), MangosStringLocale::Emote, GetCreatureTemplateStore(), Map::GetId(), GetMangosStringData(), Object::GetObjectGuid(), MangosStringLocale::LanguageId, Map::MonsterYellToMap(), Map::PlayDirectSoundToMap(), script_error_log(), MangosStringLocale::SoundId, and MangosStringLocale::Type.
Referenced by ScriptedInstance::DoOrSimulateScriptTextForThisInstance().
DoScriptText()
void DoScriptText (int32 iTextEntry, WorldObject * pSource, Unit * pTarget, uint32 chatTypeOverride)
Function that does script text.
Parameters
iTextEntry Entry of the text, stored in SD2-database
pSource Source of the text
pTarget Can be nullptr (depending on CHAT_TYPE of iTextEntry). Possible target for the text
Definition at line 44 of file ScriptDevAIMgr.cpp.
References DoDisplayText(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetTypeId(), and script_error_log().
Referenced by boss_swamplord_muselekAI::Aggro(), npc_professor_phizzlethorpeAI::Aggro(), npc_hurley_blackbreathAI::Aggro(), boss_emperor_dagran_thaurissanAI::Aggro(), boss_broodlordAI::Aggro(), boss_kazzakAI::Aggro(), npc_grark_lorkrubAI::Aggro(), boss_thermapluggAI::Aggro(), boss_curatorAI::Aggro(), boss_maiden_of_virtueAI::Aggro(), boss_moroesAI::Aggro(), boss_nightbaneAI::Aggro(), boss_malchezaarAI::Aggro(), boss_aranAI::Aggro(), boss_terestianAI::Aggro(), boss_strawmanAI::Aggro(), boss_tinheadAI::Aggro(), boss_roarAI::Aggro(), boss_bigbadwolfAI::Aggro(), boss_julianneAI::Aggro(), boss_romuloAI::Aggro(), boss_priestess_delrissaAI::Aggro(), boss_selin_fireheartAI::Aggro(), boss_vexallusAI::Aggro(), boss_arcanist_doanAI::Aggro(), boss_herodAI::Aggro(), boss_scarlet_commander_mograineAI::Aggro(), boss_dathrohan_balnazzarAI::Aggro(), boss_kalecgosAI::Aggro(), npc_sunblade_protectorAI::Aggro(), npc_tapoke_slim_jahnAI::Aggro(), boss_akilzonAI::Aggro(), boss_halazziAI::Aggro(), boss_janalaiAI::Aggro(), boss_malacrassAI::Aggro(), boss_nalorakkAI::Aggro(), boss_zuljinAI::Aggro(), npc_amanishi_scoutAI::Aggro(), boss_arlokkAI::Aggro(), boss_hakkarAI::Aggro(), boss_jeklikAI::Aggro(), boss_mandokirAI::Aggro(), boss_marliAI::Aggro(), boss_thekalAI::Aggro(), example_escortAI::Aggro(), npc_muglashAI::Aggro(), npc_magwinAI::Aggro(), boss_aeonusAI::Aggro(), boss_chrono_lord_dejaAI::Aggro(), boss_temporusAI::Aggro(), boss_archimondeAI::Aggro(), npc_thrall_old_hillsbradAI::Aggro(), npc_volcorAI::Aggro(), npc_oox22feAI::Aggro(), npc_clintar_dw_spiritAI::Aggro(), boss_onyxiaAI::Aggro(), boss_moamAI::Aggro(), boss_ossirianAI::Aggro(), npc_oox17tnAI::Aggro(), boss_sarturaAI::Aggro(), boss_skeramAI::Aggro(), boss_zumrahAI::Aggro(), boss_jedogaAI::Aggro(), boss_nadoxAI::Aggro(), boss_taldaramAI::Aggro(), boss_volazjAI::Aggro(), boss_anubarakAI::Aggro(), boss_krikthirAI::Aggro(), npc_bonker_togglevoltAI::Aggro(), npc_proudhoofAI::Aggro(), boss_anubarak_trialAI::Aggro(), boss_fjolaAI::Aggro(), boss_eydisAI::Aggro(), boss_novosAI::Aggro(), boss_tharonjaAI::Aggro(), boss_trollgoreAI::Aggro(), boss_moorabiAI::Aggro(), npc_father_kamarosAI::Aggro(), npc_grand_admiral_westwindAI::Aggro(), boss_bronjahmAI::Aggro(), boss_devourer_of_soulsAI::Aggro(), boss_blood_queen_lanathelAI::Aggro(), boss_deathbringer_saurfangAI::Aggro(), boss_festergutAI::Aggro(), boss_lady_deathwhisperAI::Aggro(), boss_lord_marrowgarAI::Aggro(), boss_professor_putricideAI::Aggro(), boss_rotfaceAI::Aggro(), boss_sindragosaAI::Aggro(), boss_the_lich_king_iccAI::Aggro(), boss_malygosAI::Aggro(), boss_ormorokAI::Aggro(), boss_eregosAI::Aggro(), boss_varosAI::Aggro(), boss_sartharionAI::Aggro(), mob_tenebronAI::Aggro(), mob_shadronAI::Aggro(), mob_vesperonAI::Aggro(), boss_baltharusAI::Aggro(), boss_halion_realAI::Aggro(), boss_savianaAI::Aggro(), boss_zarithrianAI::Aggro(), boss_bjarngrimAI::Aggro(), boss_ionarAI::Aggro(), boss_lokenAI::Aggro(), boss_volkhanAI::Aggro(), boss_sjonnirAI::Aggro(), boss_brundirAI::Aggro(), boss_molgeimAI::Aggro(), boss_steelbreakerAI::Aggro(), boss_auriayaAI::Aggro(), boss_flame_leviathanAI::Aggro(), boss_general_vezaxAI::Aggro(), boss_hodirAI::Aggro(), boss_ignisAI::Aggro(), boss_kologarnAI::Aggro(), boss_xt_002AI::Aggro(), boss_kelesethAI::Aggro(), boss_svalaAI::Aggro(), boss_ymironAI::Aggro(), boss_exarch_maladaarAI::Aggro(), boss_nexusprince_shaffarAI::Aggro(), boss_pandemoniusAI::Aggro(), boss_darkweaver_sythAI::Aggro(), boss_talon_king_ikissAI::Aggro(), boss_ambassador_hellmawAI::Aggro(), boss_blackheart_the_inciterAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_gurtogg_bloodboilAI::Aggro(), boss_shahrazAI::Aggro(), boss_teron_gorefiendAI::Aggro(), boss_najentusAI::Aggro(), boss_doomlordkazzakAI::Aggro(), boss_doomwalkerAI::Aggro(), boss_fathomlord_karathressAI::Aggro(), boss_hydross_the_unstableAI::Aggro(), boss_lady_vashjAI::Aggro(), boss_morogrim_tidewalkerAI::Aggro(), boss_thespiaAI::Aggro(), boss_mekgineer_steamriggerAI::Aggro(), boss_warlord_kalithreshAI::Aggro(), boss_gruulAI::Aggro(), boss_high_king_maulgarAI::Aggro(), boss_kelidan_the_breakerAI::Aggro(), boss_the_makerAI::Aggro(), boss_vazrudenAI::Aggro(), boss_omor_the_unscarredAI::Aggro(), boss_watchkeeper_gargolmarAI::Aggro(), boss_grand_warlock_nethekurseAI::Aggro(), boss_warbringer_omroggAI::Aggro(), boss_warchief_kargath_bladefistAI::Aggro(), npc_shattered_hand_legionnaire::Aggro(), npc_protectorate_demolitionistAI::Aggro(), npc_dimensiusAI::Aggro(), boss_dalliahAI::Aggro(), boss_soccothratesAI::Aggro(), boss_high_botanist_freywinnAI::Aggro(), boss_thorngrinAI::Aggro(), boss_warp_splinterAI::Aggro(), boss_high_astromancer_solarianAI::Aggro(), boss_thaladred_the_darkenerAI::Aggro(), boss_lord_sanguinarAI::Aggro(), boss_grand_astromancer_capernianAI::Aggro(), boss_master_engineer_telonicusAI::Aggro(), boss_void_reaverAI::Aggro(), boss_mechano_lord_capacitusAI::Aggro(), boss_nethermancer_sepethreaAI::Aggro(), boss_pathaleon_the_calculatorAI::Aggro(), boss_highlord_kruulAI::Aggro(), boss_emerissAI::Aggro(), boss_lethonAI::Aggro(), boss_taerarAI::Aggro(), boss_ysondreAI::Aggro(), npc_the_cleanerAI::Aggro(), boss_kelthuzadAI::Aggro(), boss_essence_of_sufferingAI::Aggro(), boss_essence_of_desireAI::Aggro(), boss_essence_of_angerAI::Aggro(), npc_kineloryAI::Aggro(), npc_marshal_windsorAI::Aggro(), npc_00x09hlAI::Aggro(), npc_rinjiAI::Aggro(), example_creatureAI::Aggro(), npc_prospector_remtravelAI::Aggro(), npc_stinky_ignatzAI::Aggro(), npc_areiAI::Aggro(), npc_willix_the_importerAI::Aggro(), mob_aquementasAI::Aggro(), npc_giltharesAI::Aggro(), npc_ame01AI::Aggro(), boss_eadricAI::Aggro(), boss_paletressAI::Aggro(), boss_jaraxxusAI::Aggro(), npc_squad_leaderAI::Aggro(), boss_ingvarAI::Aggro(), mob_fel_orc_convertAI::Aggro(), mob_lumpAI::Aggro(), npc_letollAI::Aggro(), npc_kindal_moonweaverAI::Aggro(), guardAI::Aggro(), boss_majordomoAI::Aggro(), boss_arugalAI::Aggro(), npc_deathstalker_erlandAI::Aggro(), boss_brutallusAI::Aggro(), npc_galen_goodwardAI::Aggro(), npc_defias_traitorAI::Aggro(), boss_buruAI::Aggro(), boss_veknilashAI::Aggro(), boss_veklorAI::Aggro(), boss_forgemaster_garfrostAI::Aggro(), boss_ickAI::Aggro(), boss_tyrannusAI::Aggro(), boss_anomalusAI::Aggro(), boss_keristraszaAI::Aggro(), boss_telestraAI::Aggro(), boss_ichoronAI::Aggro(), boss_xevozzAI::Aggro(), mob_shadowmoon_channelerAI::Aggro(), mob_bt_battle_fighterAI::Aggro(), AreaTrigger_at_example(), AreaTrigger_at_frostmourne_chamber(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_naturalist_bite(), AreaTrigger_at_naxxramas(), AreaTrigger_at_raven_prophecy(), AreaTrigger_at_twilight_grove(), npc_drijyaAI::AttackedBy(), npc_blastmaster_emi_shortfuseAI::AttackedBy(), npc_belnistraszAI::AttackedBy(), npc_feero_ironhandAI::AttackedBy(), boss_uromAI::AttackStart(), boss_plugger_spazzringAI::AttackThief(), npc_lazy_peonAI::Awaken(), boss_vaelastraszAI::BeginSpeech(), boss_anzuAI::boss_anzuAI(), boss_maievAI::boss_maievAI(), boss_terokkAI::boss_terokkAI(), boss_sartharionAI::CallDragon(), npc_shattered_hand_legionnaire::CallForReinforcements(), npc_twiggy_flatheadAI::CanStartEvent(), boss_archimondeAI::CheckLeash(), npc_ringoAI::ClearFaint(), npc_kerlonianAI::ClearSleeping(), mob_anubisath_guardianAI::DamageTaken(), boss_julianneAI::DamageTaken(), boss_romuloAI::DamageTaken(), npc_deathstalker_vincentAI::DamageTaken(), npc_dashel_stonefistAI::DamageTaken(), npc_tapoke_slim_jahnAI::DamageTaken(), npc_akamaAI::DamageTaken(), mob_lumpAI::DamageTaken(), npc_grand_admiral_westwindAI::DamageTaken(), boss_deathbringer_saurfangAI::DamageTaken(), boss_freyaAI::DamageTaken(), boss_ingvarAI::DamageTaken(), npc_private_hendelAI::DamageTaken(), npc_silvermoon_harryAI::DamageTaken(), three_nature_alliesAI::DamageTaken(), npc_scrap_reaverAI::Die(), boss_buruAI::DoAttackNewTarget(), npc_eris_havenfireAI::DoBalanceEventEnd(), npc_shadowlord_deathwailAI::DoBeginDescent(), boss_illidan_stormrageAI::DoCastEyeBlastIfCan(), boss_fjolaAI::DoCastSpecialAbility(), npc_ranshallaAI::DoChannelTorchSpell(), npc_tipsy_mcmanusAI::DoCheckDistillationTask(), instance_culling_of_stratholme::DoChromieWhisper(), npc_mistAI::DoComplete(), npc_ranshallaAI::DoContinueEscort(), boss_silithidRoyaltyAI::DoDummyConsume(), npc_manaforge_control_consoleAI::DoFailEvent(), npc_manaforge_control_consoleAI::DoFinalSpawnForCreature(), instance_dark_portal::DoHandleAreaTrigger(), mob_tenebronAI::DoHandleBreathYell(), mob_shadronAI::DoHandleBreathYell(), mob_vesperonAI::DoHandleBreathYell(), npc_graufAI::DoHandleBreathYell(), instance_icecrown_citadel::DoHandleCitadelAreaTrigger(), boss_pyroguard_emberseerAI::DoHandleEmberseerGrowing(), boss_eadricAI::DoHandleEventEnd(), boss_paletressAI::DoHandleEventEnd(), instance_trial_of_the_crusader::DoHandleEventEpilogue(), npc_eris_havenfireAI::DoHandlePhaseEnd(), boss_julianneAI::DoHandleRomuloResurrect(), boss_lady_vashjAI::DoInformGeneratorStopped(), instance_stratholme::DoMoveBackDefenders(), boss_vazruden_heraldAI::DoMoveToCenter(), boss_vazruden_heraldAI::DoMoveToCombat(), DialogueHelper::DoNextDialogueStep(), mob_unkor_the_ruthlessAI::DoNice(), dummy_dragonAI::DoOpenPortal(), instance_black_temple::DoOpenPreMotherDoor(), boss_skadiAI::DoPrepareForGauntlet(), boss_midnightAI::DoPrepareMount(), instance_blackrock_spire::DoProcessEmberseerEvent(), boss_headless_horsemanAI::DoRejoinHead(), instance_violet_hold::DoReleaseBoss(), boss_xt_002AI::DoResetToNormalPhase(), boss_halazziAI::DoReuniteSpirits(), instance_stratholme::DoScarletBastionDefense(), boss_selin_fireheartAI::DoSelectNearestCrystal(), instance_ruins_of_ahnqiraj::DoSendNextArmyWave(), instance_blackrock_spire::DoSendNextFlamewreathWave(), instance_azjol_nerub::DoSendWatcherOrKrikthir(), npc_daphne_stilwellAI::DoSendWave(), world_map_eastern_kingdoms::DoSpawn(), npc_wildaAI::DoSpawnAssassin(), instance_mechanar::DoSpawnBridgeWave(), instance_scholomance::DoSpawnGandlingIfCan(), boss_emerissAI::DoSpecialDragonAbility(), boss_lethonAI::DoSpecialDragonAbility(), boss_taerarAI::DoSpecialDragonAbility(), boss_ysondreAI::DoSpecialDragonAbility(), instance_shadowfang_keep::DoSpeech(), instance_pit_of_saron::DoStartAmbushEvent(), npc_highlord_darion_mograineAI::DoStartConclusion(), npc_lady_sylvanas_windrunnerAI::DoStartLamentEvent(), npc_Shattered_Hand_Scout::DoStartRunning(), boss_lady_deathwhisperAI::DoStartSecondPhase(), npc_beast_combat_stalkerAI::DoSummonNextBeast(), npc_eris_havenfireAI::DoSummonWave(), hyjalAI::DoTalk(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), npc_anubisath_sentinelAI::DoTransferAbility(), npc_halion_controllerAI::DoUpdateCorporeality(), npc_muglashAI::DoWaveSummon(), boss_grand_warlock_nethekurseAI::DoYellForPeonAggro(), boss_grand_warlock_nethekurseAI::DoYellForPeonDeath(), boss_warbringer_omroggAI::DoYellForThreat(), EffectAuraDummy_npc_depleted_war_golem(), EffectAuraDummy_spell_aura_dummy_npc(), Spell::EffectDummy(), EffectDummyCreature_npc_city_guard(), EffectDummyCreature_npc_kitten(), EffectDummyCreature_spell_capture_grark(), EffectDummyCreature_spell_drink_poison(), EffectDummyCreature_spell_dummy_npc(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_npc_scorch(), EffectScriptEffectCreature_spell_unstable_ooze(), boss_ichoronAI::EndSplitPhase(), npc_thrall_old_hillsbradAI::EnterEvadeMode(), boss_vazruden_heraldAI::EnterEvadeMode(), boss_vazrudenAI::EnterEvadeMode(), boss_omor_the_unscarredAI::EnterEvadeMode(), boss_high_king_maulgarAI::EventCouncilDeath(), boss_baron_geddonAI::ExecuteAction(), npc_sunblade_scoutAI::ExecuteAction(), boss_talon_king_ikissAI::ExecuteAction(), boss_watchkeeper_gargolmarAI::ExecuteAction(), boss_chromaggusAI::ExecuteAction(), boss_flamegorAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_maiden_of_virtueAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_dorotheeAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), boss_vexallusAI::ExecuteAction(), boss_garrAI::ExecuteAction(), mob_core_ragerAI::ExecuteAction(), boss_magmadarAI::ExecuteAction(), boss_ragnarosAI::ExecuteAction(), npc_highlord_darion_mograineAI::ExecuteAction(), boss_arugalAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kalecgos_humanoidAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_janalaiAI::ExecuteAction(), boss_malacrassAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_jeklikAI::ExecuteAction(), npc_gurubashi_bat_riderAI::ExecuteAction(), boss_marliAI::ExecuteAction(), boss_venoxisAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), boss_anetheronAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_kazrogalAI::ExecuteAction(), boss_rage_winterchillAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), npc_corrupted_furbolgAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_moamAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), npc_anubisath_sentinelAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_krikthirAI::ExecuteAction(), boss_moorabiAI::ExecuteAction(), boss_bronjahmAI::ExecuteAction(), boss_forgemaster_garfrostAI::ExecuteAction(), boss_ickAI::ExecuteAction(), boss_tyrannusAI::ExecuteAction(), boss_rimefang_posAI::ExecuteAction(), boss_deathbringer_saurfangAI::ExecuteAction(), boss_lady_deathwhisperAI::ExecuteAction(), boss_kelthuzadAI::ExecuteAction(), boss_anomalusAI::ExecuteAction(), boss_keristraszaAI::ExecuteAction(), boss_ormorokAI::ExecuteAction(), boss_telestraAI::ExecuteAction(), boss_eregosAI::ExecuteAction(), boss_baltharusAI::ExecuteAction(), boss_zarithrianAI::ExecuteAction(), boss_sjonnirAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), boss_kelesethAI::ExecuteAction(), boss_svalaAI::ExecuteAction(), boss_ichoronAI::ExecuteAction(), boss_xevozzAI::ExecuteAction(), boss_shirrakAI::ExecuteAction(), boss_nexusprince_shaffarAI::ExecuteAction(), boss_blackheart_the_inciterAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), boss_maievAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_essence_of_sufferingAI::ExecuteAction(), boss_essence_of_desireAI::ExecuteAction(), boss_essence_of_angerAI::ExecuteAction(), npc_akamaAI::ExecuteAction(), boss_supremusAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_veras_darkshadowAI::ExecuteAction(), boss_terokkAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), npc_magister_aledisAI::ExecuteAction(), npc_eye_of_shartuulAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_warlord_kalithreshAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), boss_highlord_kruulAI::ExecuteActions(), boss_anzuAI::ExecuteActions(), boss_zuljinAI::ExecutePhaseTransition(), instance_dark_portal::ExecutePostEventStep(), npc_adyen_the_lightwardenAI::ExecuteTimer(), npc_commanderAI::FailEvent(), boss_freyaAI::FetchElders(), npc_regthar_deathgateAI::FinishEvent(), world_map_outland::FinishPhase(), npc_dragonmaw_racerAI::FinishRace(), npc_anzu_bird_spiritAI::FreezeSpirits(), GossipSelect_boss_doomrel(), GossipSelect_example_gossip_codebox(), GossipSelect_npc_barnes(), GossipSelect_npc_death_knight_initiate(), GossipSelect_npc_dughal_stormwing(), GossipSelect_npc_regthar_deathgate(), GossipSelect_npc_saeed(), GossipSelect_npc_salsalabim(), GossipSelect_npc_saronite_mine_slave(), GossipSelect_npc_shadowfang_prisoner(), GossipSelect_npc_silvermoon_harry(), GossipSelect_npc_spawned_oronok_tornheart(), GossipSelect_npc_thrall_old_hillsbrad(), GossipSelect_npc_threshwackonator(), GossipSelect_npc_tobias_seecher(), GossipSelect_npc_ulduar_keeper(), GossipSelectWithCode_example_gossip_codebox(), GOUse_go_cage_door(), GOUse_go_naga_brazier(), GOUse_go_wooden_door(), ChildTbcAI::HandleAerisLanding(), npc_disobedient_dragonmaw_peonAI::HandleAngry(), mob_torlothAI::HandleAnimation(), boss_kiljaedenAI::HandleAttackDelay(), ChildTbcAI::HandleAuchindounAndTheRingOfObservance(), instance_blackrock_depths::HandleBarPatrol(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirOutro(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), ChildTbcAI::HandleCallOfTheFarseer(), instance_scholomance::HandleDawnGambitEvent(), npc_general_andorovAI::HandleDespawn(), boss_ragnarosAI::HandleEnterCombat(), npc_grand_collectorAI::HandleEvent(), boss_kalecgosAI::HandleExit(), boss_felmystAI::HandleFelmystSpawnDelay(), npc_shartuulAI::HandleFightSequence(), ChildTbcAI::HandleHchuuAndTheMushroomPeople(), boss_nefarianAI::HandleInitialYell(), boss_vaelastraszAI::HandleIntro(), boss_dorotheeAI::HandleIntro(), boss_felblood_kaelthasAI::HandleIntro(), boss_lady_vashjAI::HandleIntroText(), boss_kiljaedenAI::HandleKalecYell(), boss_scarlet_commander_mograineAI::HandleLayOnHandsTimer(), boss_kelthuzadAI::HandleLichKingAnswer(), ChildTbcAI::HandleNowWhenIGrowUp(), boss_felblood_kaelthasAI::HandleOutro(), boss_majordomoAI::HandleOutro(), npc_akama_illidanAI::HandleOutro(), boss_telestraAI::HandlePersonalityMerge(), boss_high_astromancer_solarianAI::HandlePhase2Delay(), boss_ragnarosAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), npc_ethereal_sphereAI::HandlePlayerSummon(), boss_high_inquisitor_whitemaneAI::HandleResurrection(), ChildTbcAI::HandleSeatOfTheNaaru(), world_map_outland::HandleShartuulAddSpawns(), world_map_outland::HandleShartuulSpawnSequence(), boss_vaelastraszAI::HandleSpeech(), npc_shadowfang_prisonerAI::HandleSpeech(), boss_high_astromancer_solarianAI::HandleSplitPhaseDelay(), npc_khadgars_servantAI::HandleStart(), ChildTbcAI::HandleTimeToVisitTheCaverns(), ChildTbcAI::HandleTripToTheDarkPortal(), ChildTbcAI::HandleVisitTheThroneOfTheElements(), boss_cthunAI::HandleWeaken(), instance_sunwell_plateau::ImpYell(), boss_viscidusAI::IncreaseHitCount(), npc_squire_roweAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_akamaAI::JustDidDialogueStep(), npc_valentine_boss_managerAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), npc_demolitionist_legosoAI::JustDidDialogueStep(), npc_arthasAI::JustDidDialogueStep(), npc_melizza_brimbuzzleAI::JustDidDialogueStep(), npc_areiAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), instance_trial_of_the_champion::JustDidDialogueStep(), npc_lich_king_villageAI::JustDidDialogueStep(), boss_mimironAI::JustDidDialogueStep(), npc_expedition_commanderAI::JustDidDialogueStep(), boss_thorimAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), boss_nefarianAI::JustDied(), boss_kazzakAI::JustDied(), boss_curatorAI::JustDied(), boss_maiden_of_virtueAI::JustDied(), boss_attumenAI::JustDied(), boss_moroesAI::JustDied(), boss_malchezaarAI::JustDied(), boss_aranAI::JustDied(), boss_terestianAI::JustDied(), boss_dorotheeAI::JustDied(), boss_strawmanAI::JustDied(), boss_tinheadAI::JustDied(), boss_roarAI::JustDied(), boss_croneAI::JustDied(), boss_priestess_delrissaAI::JustDied(), boss_headless_horsemanAI::JustDied(), boss_dathrohan_balnazzarAI::JustDied(), boss_brutallusAI::JustDied(), boss_alythessAI::JustDied(), boss_sacrolashAI::JustDied(), boss_felmystAI::JustDied(), boss_sathrovarrAI::JustDied(), boss_akilzonAI::JustDied(), boss_halazziAI::JustDied(), boss_janalaiAI::JustDied(), boss_malacrassAI::JustDied(), boss_nalorakkAI::JustDied(), boss_zuljinAI::JustDied(), boss_arlokkAI::JustDied(), boss_jeklikAI::JustDied(), boss_marliAI::JustDied(), boss_thekalAI::JustDied(), boss_venoxisAI::JustDied(), npc_arthasAI::JustDied(), boss_aeonusAI::JustDied(), boss_chrono_lord_dejaAI::JustDied(), boss_temporusAI::JustDied(), npc_medivh_black_morassAI::JustDied(), boss_anetheronAI::JustDied(), boss_azgalorAI::JustDied(), boss_rage_winterchillAI::JustDied(), npc_thrall_old_hillsbradAI::JustDied(), boss_ossirianAI::JustDied(), boss_sarturaAI::JustDied(), boss_skeramAI::JustDied(), boss_jedogaAI::JustDied(), boss_nadoxAI::JustDied(), boss_taldaramAI::JustDied(), boss_volazjAI::JustDied(), boss_anubarakAI::JustDied(), boss_krikthirAI::JustDied(), boss_black_knightAI::JustDied(), boss_anubarak_trialAI::JustDied(), boss_fjolaAI::JustDied(), boss_eydisAI::JustDied(), boss_novosAI::JustDied(), boss_tharonjaAI::JustDied(), boss_trollgoreAI::JustDied(), boss_moorabiAI::JustDied(), boss_bronjahmAI::JustDied(), boss_devourer_of_soulsAI::JustDied(), boss_valanar_iccAI::JustDied(), boss_keleseth_iccAI::JustDied(), boss_taldaram_iccAI::JustDied(), boss_blood_queen_lanathelAI::JustDied(), boss_festergutAI::JustDied(), boss_lady_deathwhisperAI::JustDied(), boss_lord_marrowgarAI::JustDied(), boss_professor_putricideAI::JustDied(), boss_rotfaceAI::JustDied(), boss_sindragosaAI::JustDied(), boss_the_lich_king_iccAI::JustDied(), boss_valithria_dreamwalkerAI::JustDied(), boss_kelthuzadAI::JustDied(), boss_malygosAI::JustDied(), boss_ormorokAI::JustDied(), boss_eregosAI::JustDied(), boss_uromAI::JustDied(), boss_varosAI::JustDied(), boss_sartharionAI::JustDied(), boss_baltharusAI::JustDied(), boss_halion_realAI::JustDied(), boss_halion_twilightAI::JustDied(), boss_zarithrianAI::JustDied(), boss_bjarngrimAI::JustDied(), boss_ionarAI::JustDied(), boss_lokenAI::JustDied(), boss_volkhanAI::JustDied(), boss_sjonnirAI::JustDied(), npc_brann_hosAI::JustDied(), boss_brundirAI::JustDied(), boss_molgeimAI::JustDied(), boss_steelbreakerAI::JustDied(), boss_auriayaAI::JustDied(), boss_flame_leviathanAI::JustDied(), boss_general_vezaxAI::JustDied(), boss_ignisAI::JustDied(), boss_kologarnAI::JustDied(), boss_xt_002AI::JustDied(), boss_yogg_saronAI::JustDied(), boss_ingvarAI::JustDied(), boss_kelesethAI::JustDied(), boss_skadiAI::JustDied(), boss_svalaAI::JustDied(), boss_ymironAI::JustDied(), boss_exarch_maladaarAI::JustDied(), boss_nexusprince_shaffarAI::JustDied(), boss_pandemoniusAI::JustDied(), boss_darkweaver_sythAI::JustDied(), boss_talon_king_ikissAI::JustDied(), boss_ambassador_hellmawAI::JustDied(), boss_blackheart_the_inciterAI::JustDied(), boss_grandmaster_vorpilAI::JustDied(), boss_gurtogg_bloodboilAI::JustDied(), boss_shahrazAI::JustDied(), boss_essence_of_angerAI::JustDied(), boss_teron_gorefiendAI::JustDied(), boss_najentusAI::JustDied(), npc_soulgrinderAI::JustDied(), boss_doomlordkazzakAI::JustDied(), boss_doomwalkerAI::JustDied(), boss_fathomlord_karathressAI::JustDied(), boss_hydross_the_unstableAI::JustDied(), boss_lady_vashjAI::JustDied(), boss_leotheras_the_blindAI::JustDied(), boss_morogrim_tidewalkerAI::JustDied(), boss_thespiaAI::JustDied(), boss_mekgineer_steamriggerAI::JustDied(), boss_warlord_kalithreshAI::JustDied(), boss_swamplord_muselekAI::JustDied(), boss_gruulAI::JustDied(), boss_high_king_maulgarAI::JustDied(), boss_kelidan_the_breakerAI::JustDied(), boss_the_makerAI::JustDied(), boss_vazrudenAI::JustDied(), boss_omor_the_unscarredAI::JustDied(), boss_watchkeeper_gargolmarAI::JustDied(), boss_magtheridonAI::JustDied(), boss_grand_warlock_nethekurseAI::JustDied(), boss_warbringer_omroggAI::JustDied(), boss_warchief_kargath_bladefistAI::JustDied(), mob_torlothAI::JustDied(), npc_shadowlord_deathwailAI::JustDied(), npc_millhouse_manastormAI::JustDied(), boss_dalliahAI::JustDied(), boss_harbinger_skyrissAI::JustDied(), boss_soccothratesAI::JustDied(), boss_high_botanist_freywinnAI::JustDied(), boss_thorngrinAI::JustDied(), boss_warp_splinterAI::JustDied(), boss_high_astromancer_solarianAI::JustDied(), boss_kaelthasAI::JustDied(), boss_thaladred_the_darkenerAI::JustDied(), boss_lord_sanguinarAI::JustDied(), boss_grand_astromancer_capernianAI::JustDied(), boss_master_engineer_telonicusAI::JustDied(), boss_void_reaverAI::JustDied(), boss_mechano_lord_capacitusAI::JustDied(), boss_nethermancer_sepethreaAI::JustDied(), boss_pathaleon_the_calculatorAI::JustDied(), npc_avatar_of_terokkAI::JustDied(), npc_shade_of_the_horsemanAI::JustDied(), npc_a_special_surpriseAI::JustDied(), npc_general_andorovAI::JustDied(), boss_veknilashAI::JustDied(), boss_veklorAI::JustDied(), boss_forgemaster_garfrostAI::JustDied(), boss_tyrannusAI::JustDied(), boss_anomalusAI::JustDied(), boss_keristraszaAI::JustDied(), boss_telestraAI::JustDied(), boss_ichoronAI::JustDied(), boss_xevozzAI::JustDied(), boss_gathios_the_shattererAI::JustDied(), boss_high_nethermancer_zerevorAI::JustDied(), boss_lady_malandeAI::JustDied(), boss_veras_darkshadowAI::JustDied(), boss_terokkAI::JustDied(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), example_escortAI::JustDied(), mob_tenebronAI::JustDied(), mob_shadronAI::JustDied(), mob_vesperonAI::JustDied(), boss_scarlet_commander_mograineAI::JustPreventedDeath(), boss_apothecary_hummelAI::JustPreventedDeath(), npc_shartuulAI::JustPreventedDeath(), npc_sunblade_protectorAI::JustReachedHome(), npc_guardian_of_yoggAI::JustReachedHome(), npc_bonechewer_brawler::JustReachedHome(), npc_bonechewer_combatant::JustReachedHome(), npc_captured_vanguardAI::JustReachedHome(), boss_kazzakAI::JustRespawned(), npc_kalecgosAI::JustRespawned(), boss_anetheronAI::JustRespawned(), boss_azgalorAI::JustRespawned(), boss_kazrogalAI::JustRespawned(), boss_rage_winterchillAI::JustRespawned(), npc_magrami_spectre::JustRespawned(), boss_anzuAI::JustRespawned(), npc_grand_collectorAI::JustRespawned(), boss_doomlordkazzakAI::JustRespawned(), boss_highlord_kruulAI::JustRespawned(), npc_shade_of_the_horsemanAI::JustRespawned(), npc_injured_rainspeakerAI::JustStartedEscort(), npc_isla_starmaneAI::JustStartedEscort(), boss_gythAI::JustSummoned(), npc_blastmaster_emi_shortfuseAI::JustSummoned(), npc_miranAI::JustSummoned(), npc_highlord_darion_mograineAI::JustSummoned(), npc_feero_ironhandAI::JustSummoned(), npc_time_riftAI::JustSummoned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_tarethaAI::JustSummoned(), npc_areiAI::JustSummoned(), mob_ahnkahar_eggAI::JustSummoned(), boss_taldaram_iccAI::JustSummoned(), boss_rotfaceAI::JustSummoned(), boss_anomalusAI::JustSummoned(), npc_prison_event_controllerAI::JustSummoned(), npc_teleportation_portalAI::JustSummoned(), npc_shaheenAI::JustSummoned(), npc_protectorate_demolitionistAI::JustSummoned(), npc_skyguard_prisonerAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_midnightAI::JustSummoned(), boss_kelthuzadAI::JustSummoned(), boss_terokkAI::JustSummoned(), boss_omor_the_unscarredAI::JustSummoned(), boss_emperor_dagran_thaurissanAI::KilledUnit(), boss_thermapluggAI::KilledUnit(), boss_midnightAI::KilledUnit(), boss_aranAI::KilledUnit(), boss_strawmanAI::KilledUnit(), boss_tinheadAI::KilledUnit(), boss_roarAI::KilledUnit(), boss_selin_fireheartAI::KilledUnit(), boss_herodAI::KilledUnit(), boss_scarlet_commander_mograineAI::KilledUnit(), boss_high_inquisitor_whitemaneAI::KilledUnit(), boss_archaedasAI::KilledUnit(), npc_arthasAI::KilledUnit(), boss_aeonusAI::KilledUnit(), boss_chrono_lord_dejaAI::KilledUnit(), npc_thrall_old_hillsbradAI::KilledUnit(), boss_onyxiaAI::KilledUnit(), boss_veknilashAI::KilledUnit(), boss_zumrahAI::KilledUnit(), boss_jedogaAI::KilledUnit(), boss_nadoxAI::KilledUnit(), boss_taldaramAI::KilledUnit(), boss_volazjAI::KilledUnit(), boss_anubarakAI::KilledUnit(), boss_eadricAI::KilledUnit(), boss_paletressAI::KilledUnit(), boss_black_knightAI::KilledUnit(), boss_novosAI::KilledUnit(), boss_tharonjaAI::KilledUnit(), boss_moorabiAI::KilledUnit(), boss_blood_queen_lanathelAI::KilledUnit(), boss_festergutAI::KilledUnit(), boss_professor_putricideAI::KilledUnit(), boss_sindragosaAI::KilledUnit(), boss_malygosAI::KilledUnit(), boss_uromAI::KilledUnit(), boss_varosAI::KilledUnit(), boss_sartharionAI::KilledUnit(), mob_tenebronAI::KilledUnit(), mob_shadronAI::KilledUnit(), mob_vesperonAI::KilledUnit(), boss_bjarngrimAI::KilledUnit(), boss_ionarAI::KilledUnit(), boss_lokenAI::KilledUnit(), boss_volkhanAI::KilledUnit(), npc_brann_hosAI::KilledUnit(), boss_brundirAI::KilledUnit(), boss_molgeimAI::KilledUnit(), boss_steelbreakerAI::KilledUnit(), boss_auriayaAI::KilledUnit(), boss_flame_leviathanAI::KilledUnit(), boss_general_vezaxAI::KilledUnit(), boss_ymironAI::KilledUnit(), boss_exarch_maladaarAI::KilledUnit(), boss_nexusprince_shaffarAI::KilledUnit(), boss_pandemoniusAI::KilledUnit(), boss_darkweaver_sythAI::KilledUnit(), boss_talon_king_ikissAI::KilledUnit(), boss_ambassador_hellmawAI::KilledUnit(), boss_grandmaster_vorpilAI::KilledUnit(), boss_fathomlord_karathressAI::KilledUnit(), boss_hydross_the_unstableAI::KilledUnit(), boss_lady_vashjAI::KilledUnit(), boss_morogrim_tidewalkerAI::KilledUnit(), boss_thespiaAI::KilledUnit(), boss_mekgineer_steamriggerAI::KilledUnit(), boss_warlord_kalithreshAI::KilledUnit(), boss_swamplord_muselekAI::KilledUnit(), boss_kelidan_the_breakerAI::KilledUnit(), boss_the_makerAI::KilledUnit(), boss_vazrudenAI::KilledUnit(), boss_omor_the_unscarredAI::KilledUnit(), boss_watchkeeper_gargolmarAI::KilledUnit(), boss_grand_warlock_nethekurseAI::KilledUnit(), boss_warbringer_omroggAI::KilledUnit(), npc_wounded_blood_elfAI::KilledUnit(), npc_millhouse_manastormAI::KilledUnit(), boss_dalliahAI::KilledUnit(), boss_soccothratesAI::KilledUnit(), boss_high_botanist_freywinnAI::KilledUnit(), boss_warp_splinterAI::KilledUnit(), boss_kaelthasAI::KilledUnit(), boss_nethermancer_sepethreaAI::KilledUnit(), boss_pathaleon_the_calculatorAI::KilledUnit(), boss_vaelastraszAI::KilledUnit(), boss_kazzakAI::KilledUnit(), boss_julianneAI::KilledUnit(), boss_romuloAI::KilledUnit(), boss_headless_horsemanAI::KilledUnit(), boss_anubarak_trialAI::KilledUnit(), trial_crusader_commonAI::KilledUnit(), boss_jaraxxusAI::KilledUnit(), boss_fjolaAI::KilledUnit(), boss_eydisAI::KilledUnit(), boss_trollgoreAI::KilledUnit(), boss_devourer_of_soulsAI::KilledUnit(), boss_valanar_iccAI::KilledUnit(), boss_keleseth_iccAI::KilledUnit(), boss_taldaram_iccAI::KilledUnit(), boss_lord_marrowgarAI::KilledUnit(), boss_rotfaceAI::KilledUnit(), boss_valithria_dreamwalkerAI::KilledUnit(), boss_halion_realAI::KilledUnit(), boss_halion_twilightAI::KilledUnit(), boss_savianaAI::KilledUnit(), boss_algalonAI::KilledUnit(), boss_freyaAI::KilledUnit(), boss_hodirAI::KilledUnit(), boss_ignisAI::KilledUnit(), boss_kologarnAI::KilledUnit(), boss_leviathan_mk2AI::KilledUnit(), boss_vx001AI::KilledUnit(), boss_aerial_unitAI::KilledUnit(), boss_thorimAI::KilledUnit(), boss_xt_002AI::KilledUnit(), boss_saraAI::KilledUnit(), boss_yogg_saronAI::KilledUnit(), boss_doomlordkazzakAI::KilledUnit(), boss_doomwalkerAI::KilledUnit(), boss_warchief_kargath_bladefistAI::KilledUnit(), boss_harbinger_skyrissAI::KilledUnit(), boss_mechano_lord_capacitusAI::KilledUnit(), boss_highlord_kruulAI::KilledUnit(), boss_the_lich_king_iccAI::KilledUnit(), boss_ickAI::KilledUnit(), boss_krickAI::KilledUnit(), boss_tyrannusAI::KilledUnit(), boss_nefarianAI::KilledUnit(), boss_priestess_delrissaAI::KilledUnit(), boss_arugalAI::KilledUnit(), boss_mandokirAI::KilledUnit(), boss_eranikusAI::KilledUnit(), boss_krikthirAI::KilledUnit(), boss_bronjahmAI::KilledUnit(), boss_forgemaster_garfrostAI::KilledUnit(), boss_deathbringer_saurfangAI::KilledUnit(), boss_lady_deathwhisperAI::KilledUnit(), boss_kelthuzadAI::KilledUnit(), boss_anomalusAI::KilledUnit(), boss_keristraszaAI::KilledUnit(), boss_ormorokAI::KilledUnit(), boss_telestraAI::KilledUnit(), boss_eregosAI::KilledUnit(), boss_baltharusAI::KilledUnit(), boss_zarithrianAI::KilledUnit(), boss_sjonnirAI::KilledUnit(), boss_ingvarAI::KilledUnit(), boss_kelesethAI::KilledUnit(), boss_skadiAI::KilledUnit(), boss_svalaAI::KilledUnit(), boss_leotheras_the_blindAI::KilledUnit(), boss_magtheridonAI::KilledUnit(), boss_thorngrinAI::KilledUnit(), boss_high_astromancer_solarianAI::KilledUnit(), boss_void_reaverAI::KilledUnit(), boss_ichoronAI::KilledUnit(), boss_xevozzAI::KilledUnit(), boss_novosAI::LostOneCrystal(), npc_draenei_survivorAI::MoveInLineOfSight(), boss_aeonusAI::MoveInLineOfSight(), boss_chrono_lord_dejaAI::MoveInLineOfSight(), npc_kerlonianAI::MoveInLineOfSight(), npc_threshwackonatorAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_mistAI::MoveInLineOfSight(), boss_zumrahAI::MoveInLineOfSight(), boss_jedogaAI::MoveInLineOfSight(), boss_anubarakAI::MoveInLineOfSight(), boss_krikthirAI::MoveInLineOfSight(), boss_anubarak_trialAI::MoveInLineOfSight(), boss_mimironAI::MoveInLineOfSight(), npc_expedition_commanderAI::MoveInLineOfSight(), npc_scrapbotAI::MoveInLineOfSight(), boss_saraAI::MoveInLineOfSight(), npc_ominous_cloudAI::MoveInLineOfSight(), boss_exarch_maladaarAI::MoveInLineOfSight(), boss_talon_king_ikissAI::MoveInLineOfSight(), boss_grandmaster_vorpilAI::MoveInLineOfSight(), npc_daranelleAI::MoveInLineOfSight(), npc_supplicantAI::MoveInLineOfSight(), boss_warlord_kalithreshAI::MoveInLineOfSight(), npc_veneratus_spawn_nodeAI::MoveInLineOfSight(), npc_khadgars_servantAI::MoveInLineOfSight(), boss_aranAI::MoveInLineOfSight(), boss_nalorakkAI::MoveInLineOfSight(), boss_temporusAI::MoveInLineOfSight(), boss_ossirianAI::MoveInLineOfSight(), boss_nexusprince_shaffarAI::MoveInLineOfSight(), boss_watchkeeper_gargolmarAI::MoveInLineOfSight(), boss_kaelthasAI::MoveInLineOfSight(), boss_felmystAI::MovementInform(), boss_forgemaster_garfrostAI::MovementInform(), npc_aether_tech_vendorAI::MovementInform(), boss_broggokAI::MovementInform(), npc_shadowlord_deathwailAI::MovementInform(), boss_kaelthasAI::MovementInform(), boss_selin_fireheartAI::MovementInform(), boss_illidan_stormrageAI::MovementInform(), npc_akama_illidanAI::MovementInform(), boss_nefarianAI::MovementInform(), boss_eranikusAI::MovementInform(), npc_highlord_darion_mograineAI::MovementInform(), boss_thorimAI::MovementInform(), npc_annhyldeAI::MovementInform(), boss_ymironAI::MovementInform(), boss_professor_putricideAI::MovementInform(), boss_the_lich_king_iccAI::MovementInform(), boss_blood_queen_lanathelAI::MovementInform(), boss_jedogaAI::MovementInform(), boss_malygosAI::MovementInform(), boss_savianaAI::MovementInform(), npc_rethhedronAI::MovementInform(), npc_domesticated_felboarAI::MovementInform(), npc_cenarion_sparrowhawkAI::MovementInform(), npc_anachronos_the_ancientAI::MovementInform(), boss_icehowlAI::MovementInform(), npc_grand_admiral_westwindAI::MovementInform(), npc_graufAI::MovementInform(), boss_lady_vashjAI::MovementInform(), npc_dragonmaw_peonAI::MovementInform(), npc_vindicator_sedaiAI::MovementInform(), npc_dragonmaw_racer_skyshatterAI::MovementInform(), npc_living_flareAI::MovementInform(), npc_dirty_larryAI::NextStep(), npc_commanderAI::npc_commanderAI(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), npc_ethereum_prisoner_dungeonAI::npc_ethereum_prisoner_dungeonAI(), npc_ethereum_prisonerAI::npc_ethereum_prisonerAI(), npc_kittenAI::npc_kittenAI(), npc_krunAI::npc_krunAI(), npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI(), npc_malfurionAI::npc_malfurionAI(), npc_power_sparkAI::npc_power_sparkAI(), npc_vindicator_sedaiAI::npc_vindicator_sedaiAI(), DarknessOfSouls::OnApply(), FetchAlchemistsApprentice::OnApply(), instance_shadowfang_keep::OnCreatureDeath(), instance_stratholme::OnCreatureDeath(), instance_zulaman::OnCreatureDeath(), instance_blackrock_depths::OnCreatureDeath(), instance_blackrock_spire::OnCreatureDeath(), instance_karazhan::OnCreatureDeath(), instance_scarlet_monastery::OnCreatureDeath(), instance_pit_of_saron::OnCreatureDeath(), instance_icecrown_citadel::OnCreatureDeath(), instance_utgarde_keep::OnCreatureDeath(), instance_azjol_nerub::OnCreatureEnterCombat(), instance_pit_of_saron::OnCreatureEnterCombat(), spell_launch_harpoon::OnEffectExecute(), DestroyEgg::OnEffectExecute(), SummonHakkar::OnEffectExecute(), ViscidusExplode::OnEffectExecute(), spell_out_cold::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), BanishExile::OnEffectExecute(), HorsemanConflagrateTargetTest::OnEffectExecute(), boss_broodlordAI::OnLeash(), boss_warchief_kargath_bladefistAI::OnLeash(), boss_essence_of_sufferingAI::OnPhaseFinished(), boss_essence_of_desireAI::OnPhaseFinished(), boss_jeklikAI::OnSpellCast(), boss_arlokkAI::OnSpellCast(), boss_moorabiAI::OnSpellCast(), boss_kelthuzadAI::OnSpellCast(), boss_azgalorAI::OnSpellCooldownAdded(), npc_gallywixAI::OnStealthAlert(), npc_venture_co_lookoutAI::OnStealthAlert(), npc_foreman_silixizAI::OnStealthAlert(), npc_zeppitAI::OwnerKilledUnit(), npc_spawned_oronok_tornheartAI::PointMovementInform(), npc_brann_hosAI::PrepareTribunalEvent(), ProcessEventId_CharmDegrader(), ProcessEventId_CharmShivan(), ProcessEventId_event_spell_summon_nightbane(), ProcessEventId_WildhammerMessage(), ProcessEventTransports(), instance_dire_maul::ProcessForceFieldOpening(), world_map_outland::ProgressShartuul(), QuestAccept_npc_00x09hl(), QuestAccept_npc_akuno(), QuestAccept_npc_belnistrasz(), QuestAccept_npc_bessy(), QuestAccept_npc_captured_vanguard(), QuestAccept_npc_daphne_stilwell(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_deathstalker_erland(), QuestAccept_npc_deathstalker_faerleia(), QuestAccept_npc_defias_traitor(), QuestAccept_npc_dragonmaw_racer(), QuestAccept_npc_feero_ironhand(), QuestAccept_npc_galen_goodward(), QuestAccept_npc_gilthares(), QuestAccept_npc_helice(), QuestAccept_npc_injured_rainspeaker(), QuestAccept_npc_kaya(), QuestAccept_npc_kayra_longmane(), QuestAccept_npc_kerlonian(), QuestAccept_npc_kindal_moonweaver(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_letoll(), QuestAccept_npc_muglash(), QuestAccept_npc_ogron(), QuestAccept_npc_oox17tn(), QuestAccept_npc_oox22fe(), QuestAccept_npc_paoka_swiftmountain(), QuestAccept_npc_professor_phizzlethorpe(), QuestAccept_npc_ranshalla(), QuestAccept_npc_regthar_deathgate(), QuestAccept_npc_shay_leafrunner(), QuestAccept_npc_skywing(), QuestAccept_npc_therylune(), QuestAccept_npc_torek(), QuestAccept_npc_wilda(), QuestAccept_npc_willix_the_importer(), QuestAccept_npc_wizzlecranks_shredder(), QuestRewarded_into_the_soulgrinder(), QuestRewarded_npc_rocknot(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), boss_alythessAI::ReceiveAIEvent(), boss_sacrolashAI::ReceiveAIEvent(), boss_halion_realAI::ReceiveAIEvent(), boss_freyaAI::ReceiveAIEvent(), boss_ambassador_hellmawAI::ReceiveAIEvent(), boss_teron_gorefiendAI::ReceiveAIEvent(), boss_terokkAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), npc_salhadaarAI::ReceiveAIEvent(), boss_selin_fireheartAI::ReceiveAIEvent(), npc_taelan_fordringAI::ReceiveAIEvent(), boss_coren_direbrewAI::ReceiveAIEvent(), boss_sathrovarrAI::ReceiveAIEvent(), boss_mandokirAI::ReceiveAIEvent(), npc_anubarak_trial_spikeAI::ReceiveAIEvent(), boss_leotheras_the_blindAI::ReceiveAIEvent(), npc_kineloryAI::ReceiveAIEvent(), npc_corporal_keeshan_escortAI::ReceiveAIEvent(), npc_anchorite_truuenAI::ReceiveAIEvent(), npc_stinky_ignatzAI::ReceiveAIEvent(), npc_areiAI::ReceiveAIEvent(), npc_harrison_jonesAI::ReceiveAIEvent(), npc_apothecary_hanesAI::ReceiveAIEvent(), npc_grand_admiral_westwindAI::ReceiveAIEvent(), npc_tipsy_mcmanusAI::ReceiveAIEvent(), npc_injured_minerAI::ReceiveAIEvent(), boss_yogg_saronAI::ReceiveAIEvent(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_fhwoorAI::ReceiveAIEvent(), npc_scarlet_ghoulAI::ReceiveAIEvent(), boss_head_of_horsemanAI::ReceiveAIEvent(), boss_kalecgosAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), boss_razorscaleAI::ReceiveAIEvent(), boss_xt_002AI::ReceiveAIEvent(), boss_ingvarAI::ReceiveAIEvent(), boss_general_vezaxAI::ReceiveAIEvent(), boss_skadiAI::ReceiveAIEvent(), npc_demolitionist_legosoAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_emilyAI::ReceiveAIEvent(), mob_big_oozeAI::ReceiveAIEvent(), npc_highlord_darion_mograineAI::ReceiveAIEvent(), npc_domesticated_felboarAI::ReceiveAIEvent(), boss_ichoronAI::ReceiveAIEvent(), npc_adyen_the_lightwardenAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), example_creatureAI::ReceiveEmote(), npc_supplicantAI::ReceiveEmote(), npc_chicken_cluckAI::ReceiveEmote(), npc_cenarion_sparrowhawkAI::Reset(), mob_vrykul_skeletonAI::Revive(), world_map_outland::ScriptAction(), boss_sartharionAI::SendFlameTsunami(), instance_stratholme::SetData(), instance_black_temple::SetData(), instance_blood_furnace::SetData(), world_map_outland::SetData(), instance_blackrock_depths::SetData(), instance_blackwing_lair::SetData(), instance_sunken_temple::SetData(), instance_dark_portal::SetData(), instance_dire_maul::SetData(), instance_ruins_of_ahnqiraj::SetData(), instance_trial_of_the_crusader::SetData(), instance_icecrown_citadel::SetData(), instance_violet_hold::SetData(), instance_arcatraz::SetData(), instance_blackwing_lair::SetData64(), npc_ringoAI::SetFaint(), boss_viscidusAI::SetPhase(), npc_kerlonianAI::SetSleeping(), instance_ulduar::SpawnKeeperHelper(), instance_molten_core::SpawnMajordomo(), boss_headless_horsemanAI::SpellHit(), npc_rizzle_sprysprocketAI::SpellHit(), npc_solenorAI::SpellHit(), npc_simone_seductressAI::SpellHit(), npc_artoriusAI::SpellHit(), boss_thorimAI::SpellHit(), boss_fathomlord_karathressAI::SpellHit(), boss_zuljinAI::SpellHit(), boss_kelthuzadAI::SpellHit(), boss_essence_of_angerAI::SpellHit(), guardAI_stormwind::SpellHit(), npc_blackwing_orbAI::SpellHit(), boss_attumenAI::SpellHit(), boss_najentusAI::SpellHit(), boss_magtheridonAI::SpellHit(), npc_living_flareAI::SpellHit(), npc_forest_frogAI::SpellHit(), npc_scrapped_fel_reaverAI::SpellHit(), blood_prince_council_baseAI::SpellHit(), boss_malygosAI::SpellHit(), mobs_nether_drakeAI::SpellHit(), mob_enslaved_netherwing_drakeAI::SpellHit(), npc_injured_patientAI::SpellHit(), npc_garments_of_questsAI::SpellHit(), npc_kyle_the_frenziedAI::SpellHit(), npc_nagrand_captiveAI::SpellHitTarget(), boss_devourer_of_soulsAI::SpellHitTarget(), npc_rizzle_sprysprocketAI::SpellHitTarget(), boss_volazjAI::SpellHitTarget(), npc_voice_yogg_saronAI::SpellHitTarget(), boss_bronjahmAI::SpellHitTarget(), boss_flame_leviathanAI::SpellHitTarget(), boss_brutallusAI::SpellHitTarget(), npc_dreadmawAI::SpellHitTarget(), boss_moorabiAI::SpellHitTarget(), boss_zuljinAI::SpellHitTarget(), npc_harrison_jones_zaAI::StartEvent(), npc_amanishi_lookoutAI::StartEvent(), npc_lord_illidan_stormrageAI::StartEvent(), npc_ethereum_prisoner_dungeonAI::StartEvent(), npc_shade_of_the_horsemanAI::StartLanding(), boss_kelthuzadAI::StartPhase2(), boss_majordomoAI::StartSummonEvent(), boss_herodAI::SummonedCreature(), npc_agent_proudwell::SummonedCreatureDespawn(), npc_grark_lorkrubAI::SummonedCreatureJustDied(), npc_deathstalker_faerleiaAI::SummonedCreatureJustDied(), boss_malacrassAI::SummonedCreatureJustDied(), npc_regthar_deathgateAI::SummonedCreatureJustDied(), npc_eris_havenfireAI::SummonedCreatureJustDied(), boss_dorotheeAI::SummonedCreatureJustDied(), npc_miranAI::SummonedCreatureJustDied(), npc_feero_ironhandAI::SummonedCreatureJustDied(), npc_twiggy_flatheadAI::SummonedCreatureJustDied(), boss_paletressAI::SummonedCreatureJustDied(), npc_beast_combat_stalkerAI::SummonedCreatureJustDied(), npc_emilyAI::SummonedCreatureJustDied(), boss_kologarnAI::SummonedCreatureJustDied(), npc_brain_yogg_saronAI::SummonedCreatureJustDied(), boss_terestianAI::SummonedCreatureJustDied(), boss_priestess_delrissaAI::SummonedCreatureJustDied(), boss_majordomoAI::SummonedCreatureJustDied(), npc_daphne_stilwellAI::SummonedCreatureJustDied(), boss_mandokirAI::SummonedCreatureJustDied(), npc_manaforge_control_consoleAI::SummonedMovementInform(), npc_twiggy_flatheadAI::SummonedMovementInform(), npc_thrall_old_hillsbradAI::SummonedMovementInform(), boss_jedogaAI::SummonedMovementInform(), boss_reliquary_of_soulsAI::SummonedMovementInform(), boss_eranikusAI::SummonedMovementInform(), npc_adyen_the_lightwardenAI::SummonedPointReached(), npc_adyen_the_lightwardenAI::SummonedWaypointReached(), boss_mekgineer_steamriggerAI::SummonMechanichs(), boss_warp_splinterAI::SummonTreants(), boss_gurtogg_bloodboilAI::SwitchPhase(), boss_netherspiteAI::SwitchPhases(), boss_darkweaver_sythAI::SythSummoning(), instance_deadmines::Update(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_trial_of_the_champion::Update(), instance_ruby_sanctum::Update(), instance_blood_furnace::Update(), instance_magtheridons_lair::Update(), instance_shattered_halls::Update(), instance_temple_of_ahnqiraj::Update(), npc_forest_frogAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_krazAI::UpdateAI(), npc_ashliAI::UpdateAI(), boss_archimondeAI::UpdateAI(), boss_eranikusAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), boss_thorngrinAI::UpdateAI(), boss_mechano_lord_capacitusAI::UpdateAI(), boss_highlord_kruulAI::UpdateAI(), guard_hallows_end_helperAI::UpdateAI(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_mistress_nagmaraAI::UpdateAI(), boss_plugger_spazzringAI::UpdateAI(), boss_general_angerforgeAI::UpdateAI(), boss_gythAI::UpdateAI(), npc_klinfranAI::UpdateAI(), boss_mr_smiteAI::UpdateAI(), npc_eris_havenfireAI::UpdateAI(), npc_kelerun_bloodmournAI::UpdateAI(), npc_infused_crystalAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_tinheadAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_bigbadwolfAI::UpdateAI(), boss_romuloAI::UpdateAI(), npc_echo_of_medivhAI::UpdateAI(), npc_eye_of_acherusAI::UpdateAI(), npc_scarlet_ghoulAI::UpdateAI(), npc_scarlet_courierAI::UpdateAI(), boss_arcanist_doanAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_herodAI::UpdateAI(), npc_dashel_stonefistAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_malfurionAI::UpdateAI(), npc_calvin_montagueAI::UpdateAI(), boss_archaedasAI::UpdateAI(), example_creatureAI::UpdateAI(), boss_mawsAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), boss_aeonusAI::UpdateAI(), npc_restless_apparitionAI::UpdateAI(), boss_onyxiaAI::UpdateAI(), npc_twiggy_flatheadAI::UpdateAI(), boss_zumrahAI::UpdateAI(), boss_nadoxAI::UpdateAI(), boss_taldaramAI::UpdateAI(), boss_anubarakAI::UpdateAI(), npc_nesingwary_trapperAI::UpdateAI(), boss_eadricAI::UpdateAI(), boss_paletressAI::UpdateAI(), boss_anubarak_trialAI::UpdateAI(), boss_jaraxxusAI::UpdateAI(), boss_icehowlAI::UpdateAI(), boss_fjolaAI::UpdateAI(), npc_destructive_wardAI::UpdateAI(), boss_novosAI::UpdateAI(), boss_tharonjaAI::UpdateAI(), boss_trollgoreAI::UpdateAI(), npc_ancient_male_vrykulAI::UpdateAI(), npc_king_ymironAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), boss_devourer_of_soulsAI::UpdateAI(), blood_prince_council_baseAI::UpdateAI(), boss_valanar_iccAI::UpdateAI(), boss_keleseth_iccAI::UpdateAI(), boss_taldaram_iccAI::UpdateAI(), boss_blood_queen_lanathelAI::UpdateAI(), boss_festergutAI::UpdateAI(), boss_lord_marrowgarAI::UpdateAI(), boss_professor_putricideAI::UpdateAI(), boss_sindragosaAI::UpdateAI(), boss_the_lich_king_iccAI::UpdateAI(), boss_malygosAI::UpdateAI(), boss_uromAI::UpdateAI(), boss_varosAI::UpdateAI(), boss_sartharionAI::UpdateAI(), boss_halion_realAI::UpdateAI(), boss_halion_twilightAI::UpdateAI(), npc_halion_controllerAI::UpdateAI(), boss_savianaAI::UpdateAI(), npc_tipsy_mcmanusAI::UpdateAI(), boss_bjarngrimAI::UpdateAI(), boss_ionarAI::UpdateAI(), boss_lokenAI::UpdateAI(), boss_volkhanAI::UpdateAI(), npc_brann_hosAI::UpdateAI(), boss_brundirAI::UpdateAI(), boss_molgeimAI::UpdateAI(), boss_steelbreakerAI::UpdateAI(), boss_algalonAI::UpdateAI(), boss_auriayaAI::UpdateAI(), boss_flame_leviathanAI::UpdateAI(), boss_freyaAI::UpdateAI(), boss_general_vezaxAI::UpdateAI(), boss_hodirAI::UpdateAI(), boss_ignisAI::UpdateAI(), boss_kologarnAI::UpdateAI(), boss_mimironAI::UpdateAI(), boss_leviathan_mk2AI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), npc_runic_colossusAI::UpdateAI(), boss_xt_002AI::UpdateAI(), boss_saraAI::UpdateAI(), boss_yogg_saronAI::UpdateAI(), npc_voice_yogg_saronAI::UpdateAI(), boss_exarch_maladaarAI::UpdateAI(), boss_pandemoniusAI::UpdateAI(), boss_grandmaster_vorpilAI::UpdateAI(), boss_murmurAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_soulgrinderAI::UpdateAI(), boss_doomlordkazzakAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_hydross_the_unstableAI::UpdateAI(), boss_thespiaAI::UpdateAI(), mob_omrogg_headsAI::UpdateAI(), boss_warbringer_omroggAI::UpdateAI(), npc_aeranasAI::UpdateAI(), npc_danath_trollbaneAI::UpdateAI(), npc_nazgrelAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_manaforge_control_consoleAI::UpdateAI(), npc_commander_dawnforgeAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_lord_illidan_stormrageAI::UpdateAI(), npc_domesticated_felboarAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), boss_dalliahAI::UpdateAI(), boss_harbinger_skyrissAI::UpdateAI(), boss_soccothratesAI::UpdateAI(), boss_high_botanist_freywinnAI::UpdateAI(), boss_lajAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), boss_thaladred_the_darkenerAI::UpdateAI(), boss_nethermancer_sepethreaAI::UpdateAI(), boss_pathaleon_the_calculatorAI::UpdateAI(), npc_hungry_nether_rayAI::UpdateAI(), npc_cenarion_sparrowhawkAI::UpdateAI(), npc_redemption_targetAI::UpdateAI(), go_ai_fixed_trap::UpdateAI(), npc_warlock_mount_ritualAI::UpdateAI(), mob_tenebronAI::UpdateDragonAI(), mob_shadronAI::UpdateDragonAI(), mob_vesperonAI::UpdateDragonAI(), npc_galen_goodwardAI::UpdateEscortAI(), npc_harrison_jones_zaAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_khadgars_servantAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_rocknotAI::UpdateEscortAI(), npc_rinjiAI::UpdateEscortAI(), example_escortAI::UpdateEscortAI(), npc_rizzle_sprysprocketAI::UpdateEscortAI(), npc_arthasAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_wizzlecranks_shredderAI::UpdateEscortAI(), npc_lurgglbrAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_maxx_a_million_escortAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_garments_of_questsAI::UpdateEscortAI(), npc_morokkAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), npc_toogaAI::UpdateFollowerAI(), npc_ringoAI::UpdateFollowerAI(), boss_plugger_spazzringAI::WarnThief(), npc_spawned_oronok_tornheartAI::WaypointMotionType(), npc_deathstalker_erlandAI::WaypointReached(), npc_oox22feAI::WaypointReached(), npc_clintar_dw_spiritAI::WaypointReached(), npc_oox17tnAI::WaypointReached(), npc_kayra_longmaneAI::WaypointReached(), npc_shadowfang_prisonerAI::WaypointReached(), npc_adyen_the_lightwardenAI::WaypointReached(), npc_squire_roweAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_daphne_stilwellAI::WaypointReached(), npc_defias_traitorAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_ruul_snowhoofAI::WaypointReached(), npc_keeper_remulosAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointReached(), npc_saeed_escortAI::WaypointReached(), npc_professor_phizzlethorpeAI::WaypointReached(), npc_kineloryAI::WaypointReached(), npc_grimstoneAI::WaypointReached(), npc_phalanxAI::WaypointReached(), npc_rocknotAI::WaypointReached(), npc_marshal_windsorAI::WaypointReached(), npc_hurley_blackbreathAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_blastmaster_emi_shortfuseAI::WaypointReached(), npc_00x09hlAI::WaypointReached(), npc_rinjiAI::WaypointReached(), npc_miranAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_muglashAI::WaypointReached(), npc_torekAI::WaypointReached(), npc_feero_ironhandAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_arthasAI::WaypointReached(), npc_prospector_remtravelAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_theryluneAI::WaypointReached(), npc_melizza_brimbuzzleAI::WaypointReached(), npc_ogronAI::WaypointReached(), npc_stinky_ignatzAI::WaypointReached(), npc_belnistraszAI::WaypointReached(), npc_willix_the_importerAI::WaypointReached(), npc_kayaAI::WaypointReached(), npc_custodian_of_timeAI::WaypointReached(), npc_giltharesAI::WaypointReached(), npc_wizzlecranks_shredderAI::WaypointReached(), npc_lakota_windsongAI::WaypointReached(), npc_paoka_swiftmountainAI::WaypointReached(), npc_ame01AI::WaypointReached(), npc_ranshallaAI::WaypointReached(), npc_lurgglbrAI::WaypointReached(), npc_bonker_togglevoltAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_proudhoofAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_apothecary_hanesAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_father_kamarosAI::WaypointReached(), npc_heliceAI::WaypointReached(), npc_injured_rainspeakerAI::WaypointReached(), npc_injured_minerAI::WaypointReached(), npc_shaheenAI::WaypointReached(), npc_ancestral_wolfAI::WaypointReached(), npc_wounded_blood_elfAI::WaypointReached(), npc_nagrand_captiveAI::WaypointReached(), npc_bessyAI::WaypointReached(), npc_protectorate_demolitionistAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), npc_drijyaAI::WaypointReached(), npc_wildaAI::WaypointReached(), npc_khadgars_servantAI::WaypointReached(), npc_akunoAI::WaypointReached(), npc_letollAI::WaypointReached(), npc_isla_starmaneAI::WaypointReached(), npc_skywingAI::WaypointReached(), npc_skyguard_prisonerAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), npc_corporal_keeshan_escortAI::WaypointReached(), example_escortAI::WaypointReached(), npc_demolitionist_legosoAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointStart(), npc_blastmaster_emi_shortfuseAI::WaypointStart(), npc_wizzlecranks_shredderAI::WaypointStart(), npc_lurgglbrAI::WaypointStart(), npc_isla_starmaneAI::WaypointStart(), npc_corporal_keeshan_escortAI::WaypointStart(), npc_demolitionist_legosoAI::WaypointStart(), and npc_commanderAI::WinEvent().
FillSpellSummary()
void FillSpellSummary ()
Definition at line 211 of file sc_creature.cpp.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, TSpellSummary::Effects, SQLStorageBase::GetMaxEntry(), GetSpellStore(), SQLStorage::LookupEntry(), SELECT_EFFECT_AURA, SELECT_EFFECT_DAMAGE, SELECT_EFFECT_HEALING, SELECT_TARGET_ANY_ENEMY, SELECT_TARGET_ANY_FRIEND, SELECT_TARGET_AOE_ENEMY, SELECT_TARGET_AOE_FRIEND, SELECT_TARGET_SELF, SELECT_TARGET_SINGLE_ENEMY, SELECT_TARGET_SINGLE_FRIEND, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MAX_HEALTH, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_INSTAKILL, SPELL_EFFECT_SCHOOL_DAMAGE, SpellSummary, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_LOCATION_CASTER_SRC, TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_UNIT_CASTER, TARGET_UNIT_ENEMY, TARGET_UNIT_FRIEND, TARGET_UNIT_FRIEND_AND_PARTY, TARGET_UNIT_PARTY, and TSpellSummary::Targets.
Referenced by ScriptDevAIMgr::Initialize().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (ScriptDevAIMgr)
LoadDatabase()
void LoadDatabase ()
Definition at line 24 of file ScriptDevAIMgr.cpp.
References pSystemMgr.
Referenced by ScriptDevAIMgr::Initialize(), and ItemUse_example_item().