CMaNGOS_WoTLK: ScriptMgr.cpp File Reference
ScriptMgr.cpp File Reference
#include "DBScripts/ScriptMgr.h"
#include "Policies/Singleton.h"
#include "Log.h"
#include "Util/ProgressBar.h"
#include "Globals/ObjectMgr.h"
#include "MotionGenerators/WaypointManager.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/Cell.h"
#include "Grids/CellImpl.h"
#include "Server/SQLStorages.h"
#include "BattleGround/BattleGround.h"
#include "OutdoorPvP/OutdoorPvP.h"
#include "MotionGenerators/WaypointMovementGenerator.h"
#include "Mails/Mail.h"
#include "AI/ScriptDevAI/ScriptDevAIMgr.h"
#include "Maps/InstanceData.h"
#include "Entities/Object.h"
#include "Entities/Transports.h"
#include <string_view>
Functions
INSTANTIATE_SINGLETON_1 (ScriptMgr)
uint8 GetSpellStartDBScriptPriority (SpellEntry const *spellinfo, SpellEffectIndex effIdx)
bool StartEvents_Event (Map *map, uint32 id, Object *source, Object *target, bool isStart)
Variables
constexpr std::array< std::string_view, SCRIPT_TYPE_MAX > scriptTableNames
Function Documentation
GetSpellStartDBScriptPriority()
uint8 GetSpellStartDBScriptPriority (SpellEntry const * spellinfo, SpellEffectIndex effIdx)
Definition at line 66 of file ScriptMgr.cpp.
References SpellEntry::Effect, SpellEntry::EffectTriggerSpell, SQLStorage::LookupEntry(), SPELL_EFFECT_DUMMY, SPELL_EFFECT_SCRIPT_EFFECT, SPELL_EFFECT_TRIGGER_MISSILE, SPELL_EFFECT_TRIGGER_SPELL, and sSpellTemplate.
Referenced by ScriptMgr::CanSpellEffectStartDBScript(), and ScriptMgr::LoadScriptMap().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (ScriptMgr)
StartEvents_Event()
bool StartEvents_Event (Map * map, uint32 id, Object * source, Object * target, bool isStart)
Definition at line 3373 of file ScriptMgr.cpp.
References BattleGroundMap::GetBG(), BattleGround::HandleEvent(), OutdoorPvP::HandleEvent(), Map::IsBattleGroundOrArena(), Object::IsGameObject(), Object::IsPlayer(), Object::isType(), Object::IsUnit(), MANGOS_ASSERT, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE_TARGET, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET, SCRIPT_TYPE_EVENT, Map::ScriptsStart(), sOutdoorPvPMgr, sScriptDevAIMgr, and TYPEMASK_CREATURE_OR_GAMEOBJECT.
Referenced by Transport::DoEventIfAny(), Spell::EffectSendEvent(), world_map_outland::ExecuteChatCommand(), GameObject::ForceGameObjectHealth(), FlagClickBg::OnEffectExecute(), Player::OnTaxiFlightRouteProgress(), GameObject::TickCapturePoint(), ElevatorTransport::Update(), and GameObject::Use().
Variable Documentation
scriptTableNames
constexpr std::array<std::string_view, SCRIPT_TYPE_MAX> scriptTableNames constexpr
Initial value:
{
    "dbscripts_on_quest_end",
    "dbscripts_on_quest_start",
    "dbscripts_on_spell",
    "dbscripts_on_go_use",
    "dbscripts_on_go_template_use",
    "dbscripts_on_event",
    "dbscripts_on_gossip",
    "dbscripts_on_creature_death",
    "dbscripts_on_creature_movement",
    "dbscripts_on_relay",
    "internal_use",
}
Definition at line 43 of file ScriptMgr.cpp.
Referenced by ScriptMgr::LoadScripts().