CMaNGOS_WoTLK: ScriptMgr.h File Reference
ScriptMgr.h File Reference
#include "Common.h"
#include "Entities/ObjectGuid.h"
#include "Server/DBCEnums.h"
#include "DBScripts/ScriptMgrDefines.h"
#include <memory>
Data Structures
struct ScriptInfo
class ScriptAction
class ScriptMgr
Macros
#define MAX_TEXT_ID 4
#define MAX_SCRIPT_FLAG_VALID (2 * SCRIPT_FLAG_BUDDY_BY_STRING_ID - 1)
#define sScriptMgr MaNGOS::Singleton<ScriptMgr>::Instance()
Typedefs
typedef std::multimap< uint32, std::shared_ptr< ScriptInfo > > ScriptMap
typedef std::map< uint32, ScriptMap > ScriptMapMap
typedef std::pair< const char *, ScriptMapMap > ScriptMapMapName
Enumerations
enum ScriptCommand {
SCRIPT_COMMAND_TALK = 0 , SCRIPT_COMMAND_EMOTE = 1 , SCRIPT_COMMAND_FIELD_SET = 2 , SCRIPT_COMMAND_MOVE_TO = 3 ,
SCRIPT_COMMAND_FLAG_SET = 4 , SCRIPT_COMMAND_FLAG_REMOVE = 5 , SCRIPT_COMMAND_TELEPORT_TO = 6 , SCRIPT_COMMAND_QUEST_EXPLORED = 7 ,
SCRIPT_COMMAND_KILL_CREDIT = 8 , SCRIPT_COMMAND_RESPAWN_GAMEOBJECT = 9 , SCRIPT_COMMAND_TEMP_SPAWN_CREATURE = 10 , SCRIPT_COMMAND_OPEN_DOOR = 11 ,
SCRIPT_COMMAND_CLOSE_DOOR = 12 , SCRIPT_COMMAND_ACTIVATE_OBJECT = 13 , SCRIPT_COMMAND_REMOVE_AURA = 14 , SCRIPT_COMMAND_CAST_SPELL = 15 ,
SCRIPT_COMMAND_PLAY_SOUND = 16 , SCRIPT_COMMAND_CREATE_ITEM = 17 , SCRIPT_COMMAND_DESPAWN_SELF = 18 , SCRIPT_COMMAND_PLAY_MOVIE = 19 ,
SCRIPT_COMMAND_MOVEMENT = 20 , SCRIPT_COMMAND_SET_ACTIVEOBJECT = 21 , SCRIPT_COMMAND_SET_FACTION = 22 , SCRIPT_COMMAND_MORPH_TO_ENTRY_OR_MODEL = 23 ,
SCRIPT_COMMAND_MOUNT_TO_ENTRY_OR_MODEL = 24 , SCRIPT_COMMAND_SET_RUN = 25 , SCRIPT_COMMAND_ATTACK_START = 26 , SCRIPT_COMMAND_GO_LOCK_STATE = 27 ,
SCRIPT_COMMAND_STAND_STATE = 28 , SCRIPT_COMMAND_MODIFY_NPC_FLAGS = 29 , SCRIPT_COMMAND_SEND_TAXI_PATH = 30 , SCRIPT_COMMAND_TERMINATE_SCRIPT = 31 ,
SCRIPT_COMMAND_PAUSE_WAYPOINTS = 32 , SCRIPT_COMMAND_XP_USER = 33 , SCRIPT_COMMAND_TERMINATE_COND = 34 , SCRIPT_COMMAND_SEND_AI_EVENT = 35 ,
SCRIPT_COMMAND_SET_FACING = 36 , SCRIPT_COMMAND_MOVE_DYNAMIC = 37 , SCRIPT_COMMAND_SEND_MAIL = 38 , SCRIPT_COMMAND_SET_HOVER = 39 ,
SCRIPT_COMMAND_DESPAWN_GO = 40 , SCRIPT_COMMAND_RESPAWN = 41 , SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS = 42 , SCRIPT_COMMAND_RESET_GO = 43 ,
SCRIPT_COMMAND_UPDATE_TEMPLATE = 44 , SCRIPT_COMMAND_START_RELAY_SCRIPT = 45 , SCRIPT_COMMAND_CAST_CUSTOM_SPELL = 46 , SCRIPT_COMMAND_INTERRUPT_SPELL = 47 ,
SCRIPT_COMMAND_MODIFY_UNIT_FLAGS = 48 , SCRIPT_COMMAND_SET_DATA_64 = 49 , SCRIPT_COMMAND_ZONE_PULSE = 50 , SCRIPT_COMMAND_SPAWN_GROUP = 51 ,
SCRIPT_COMMAND_SET_GOSSIP_MENU = 52 , SCRIPT_COMMAND_SET_WORLDSTATE = 53 , SCRIPT_COMMAND_SET_SHEATHE = 54 , SCRIPT_COMMAND_SET_STRING_ID = 55
}
enum ScriptInfoDataFlags {
SCRIPT_FLAG_BUDDY_AS_TARGET = 0x001 , SCRIPT_FLAG_REVERSE_DIRECTION = 0x002 , SCRIPT_FLAG_SOURCE_TARGETS_SELF = 0x004 , SCRIPT_FLAG_COMMAND_ADDITIONAL = 0x008 ,
SCRIPT_FLAG_BUDDY_BY_GUID = 0x010 , SCRIPT_FLAG_BUDDY_IS_PET = 0x020 , SCRIPT_FLAG_BUDDY_IS_DESPAWNED = 0x040 , SCRIPT_FLAG_BUDDY_BY_POOL = 0x080 ,
SCRIPT_FLAG_BUDDY_BY_SPAWN_GROUP = 0x100 , SCRIPT_FLAG_ALL_ELIGIBLE_BUDDIES = 0x200 , SCRIPT_FLAG_BUDDY_BY_GO = 0x400 , SCRIPT_FLAG_BUDDY_BY_STRING_ID = 0x800
}
Functions
bool StartEvents_Event (Map *map, uint32 id, Object *source, Object *target, bool isStart=true)
Macro Definition Documentation
MAX_SCRIPT_FLAG_VALID
#define MAX_SCRIPT_FLAG_VALID (2 * SCRIPT_FLAG_BUDDY_BY_STRING_ID - 1)
Definition at line 162 of file ScriptMgr.h.
MAX_TEXT_ID
#define MAX_TEXT_ID 4
Definition at line 144 of file ScriptMgr.h.
sScriptMgr
#define sScriptMgr MaNGOS::Singleton<ScriptMgr>::Instance()
Definition at line 721 of file ScriptMgr.h.
Typedef Documentation
ScriptMap
typedef std::multimap< uint32 , std::shared_ptr<ScriptInfo> > ScriptMap
Definition at line 649 of file ScriptMgr.h.
ScriptMapMap
typedef std::map< uint32 , ScriptMap > ScriptMapMap
Definition at line 650 of file ScriptMgr.h.
ScriptMapMapName
typedef std::pair<const char*, ScriptMapMap> ScriptMapMapName
Definition at line 651 of file ScriptMgr.h.
Enumeration Type Documentation
ScriptCommand
enum ScriptCommand
Enumerator
SCRIPT_COMMAND_TALK
SCRIPT_COMMAND_EMOTE
SCRIPT_COMMAND_FIELD_SET
SCRIPT_COMMAND_MOVE_TO
SCRIPT_COMMAND_FLAG_SET
SCRIPT_COMMAND_FLAG_REMOVE
SCRIPT_COMMAND_TELEPORT_TO
SCRIPT_COMMAND_QUEST_EXPLORED
SCRIPT_COMMAND_KILL_CREDIT
SCRIPT_COMMAND_RESPAWN_GAMEOBJECT
SCRIPT_COMMAND_TEMP_SPAWN_CREATURE
SCRIPT_COMMAND_OPEN_DOOR
SCRIPT_COMMAND_CLOSE_DOOR
SCRIPT_COMMAND_ACTIVATE_OBJECT
SCRIPT_COMMAND_REMOVE_AURA
SCRIPT_COMMAND_CAST_SPELL
SCRIPT_COMMAND_PLAY_SOUND
SCRIPT_COMMAND_CREATE_ITEM
SCRIPT_COMMAND_DESPAWN_SELF
SCRIPT_COMMAND_PLAY_MOVIE
SCRIPT_COMMAND_MOVEMENT
SCRIPT_COMMAND_SET_ACTIVEOBJECT
SCRIPT_COMMAND_SET_FACTION
SCRIPT_COMMAND_MORPH_TO_ENTRY_OR_MODEL
SCRIPT_COMMAND_MOUNT_TO_ENTRY_OR_MODEL
SCRIPT_COMMAND_SET_RUN
SCRIPT_COMMAND_ATTACK_START
SCRIPT_COMMAND_GO_LOCK_STATE
SCRIPT_COMMAND_STAND_STATE
SCRIPT_COMMAND_MODIFY_NPC_FLAGS
SCRIPT_COMMAND_SEND_TAXI_PATH
SCRIPT_COMMAND_TERMINATE_SCRIPT
SCRIPT_COMMAND_PAUSE_WAYPOINTS
SCRIPT_COMMAND_XP_USER
SCRIPT_COMMAND_TERMINATE_COND
SCRIPT_COMMAND_SEND_AI_EVENT
SCRIPT_COMMAND_SET_FACING
SCRIPT_COMMAND_MOVE_DYNAMIC
SCRIPT_COMMAND_SEND_MAIL
SCRIPT_COMMAND_SET_HOVER
SCRIPT_COMMAND_DESPAWN_GO
SCRIPT_COMMAND_RESPAWN
SCRIPT_COMMAND_SET_EQUIPMENT_SLOTS
SCRIPT_COMMAND_RESET_GO
SCRIPT_COMMAND_UPDATE_TEMPLATE
SCRIPT_COMMAND_START_RELAY_SCRIPT
SCRIPT_COMMAND_CAST_CUSTOM_SPELL
SCRIPT_COMMAND_INTERRUPT_SPELL
SCRIPT_COMMAND_MODIFY_UNIT_FLAGS
SCRIPT_COMMAND_SET_DATA_64
SCRIPT_COMMAND_ZONE_PULSE
SCRIPT_COMMAND_SPAWN_GROUP
SCRIPT_COMMAND_SET_GOSSIP_MENU
SCRIPT_COMMAND_SET_WORLDSTATE
SCRIPT_COMMAND_SET_SHEATHE
SCRIPT_COMMAND_SET_STRING_ID
Definition at line 36 of file ScriptMgr.h.
ScriptInfoDataFlags
enum ScriptInfoDataFlags
Enumerator
SCRIPT_FLAG_BUDDY_AS_TARGET
SCRIPT_FLAG_REVERSE_DIRECTION
SCRIPT_FLAG_SOURCE_TARGETS_SELF
SCRIPT_FLAG_COMMAND_ADDITIONAL
SCRIPT_FLAG_BUDDY_BY_GUID
SCRIPT_FLAG_BUDDY_IS_PET
SCRIPT_FLAG_BUDDY_IS_DESPAWNED
SCRIPT_FLAG_BUDDY_BY_POOL
SCRIPT_FLAG_BUDDY_BY_SPAWN_GROUP
SCRIPT_FLAG_ALL_ELIGIBLE_BUDDIES
SCRIPT_FLAG_BUDDY_BY_GO
SCRIPT_FLAG_BUDDY_BY_STRING_ID
Definition at line 146 of file ScriptMgr.h.
Function Documentation
StartEvents_Event()
bool StartEvents_Event (Map * map, uint32 id, Object * source, Object * target, bool isStart = true)
Definition at line 3373 of file ScriptMgr.cpp.
References BattleGroundMap::GetBG(), BattleGround::HandleEvent(), OutdoorPvP::HandleEvent(), Map::IsBattleGroundOrArena(), Object::IsGameObject(), Object::IsPlayer(), Object::isType(), Object::IsUnit(), MANGOS_ASSERT, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE_TARGET, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_TARGET, SCRIPT_TYPE_EVENT, Map::ScriptsStart(), sOutdoorPvPMgr, sScriptDevAIMgr, and TYPEMASK_CREATURE_OR_GAMEOBJECT.
Referenced by Transport::DoEventIfAny(), Spell::EffectSendEvent(), world_map_outland::ExecuteChatCommand(), GameObject::ForceGameObjectHealth(), FlagClickBg::OnEffectExecute(), Player::OnTaxiFlightRouteProgress(), GameObject::TickCapturePoint(), ElevatorTransport::Update(), and GameObject::Use().