CMaNGOS_WoTLK: searing_gorge.cpp File Reference
searing_gorge.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_dorius_stonetenderAI
Enumerations
enum {
SAY_DORIUS_AGGRO_1 = 4351 , SAY_DORIUS_AGGRO_2 = 4353 , SAY_DORIUS_TO_PLAYER = 4354 , SAY_DORIUS_FINISH = 4359 ,
NPC_DARK_IRON_STEELSHIFTER = 8337 , SPELL_MARKSMAN_HIT = 12198 , RELAY_SCRIPT_FINISHED = 8284 , PATH_ID = 8284 ,
QUEST_ID_SUNTARA_STONES = 3367
}
Functions
UnitAI * GetAI_npc_dorius_stonetender (Creature *pCreature)
bool QuestAccept_npc_dorius_stonetender (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_searing_gorge ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_DORIUS_AGGRO_1
SAY_DORIUS_AGGRO_2
SAY_DORIUS_TO_PLAYER
SAY_DORIUS_FINISH
NPC_DARK_IRON_STEELSHIFTER
SPELL_MARKSMAN_HIT
RELAY_SCRIPT_FINISHED
PATH_ID
QUEST_ID_SUNTARA_STONES
Definition at line 35 of file searing_gorge.cpp.
Function Documentation
AddSC_searing_gorge()
void AddSC_searing_gorge ()
Definition at line 144 of file searing_gorge.cpp.
References Script::GetAI, GetAI_npc_dorius_stonetender(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_dorius_stonetender(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_dorius_stonetender()
UnitAI* GetAI_npc_dorius_stonetender (Creature * pCreature)
Definition at line 128 of file searing_gorge.cpp.
Referenced by AddSC_searing_gorge().
QuestAccept_npc_dorius_stonetender()
bool QuestAccept_npc_dorius_stonetender (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 133 of file searing_gorge.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_SUNTARA_STONES, and UnitAI::SendAIEvent().
Referenced by AddSC_searing_gorge().