CMaNGOS_WoTLK: serpent_shrine.cpp File Reference
serpent_shrine.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "serpent_shrine.h"
Data Structures
struct npc_serpentshrine_parasiteAI
Functions
uint32 EncounterTypeFromGOEntry (uint32 goEntry)
bool GOUse_go_ssc_boss_consoles (Player *, GameObject *pGo)
void AddSC_instance_serpentshrine_cavern ()
Function Documentation
AddSC_instance_serpentshrine_cavern()
void AddSC_instance_serpentshrine_cavern ()
Definition at line 438 of file serpent_shrine.cpp.
References Script::GetAI, Script::GetInstanceData, GOUse_go_ssc_boss_consoles(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
EncounterTypeFromGOEntry()
uint32 EncounterTypeFromGOEntry (uint32 goEntry)
Definition at line 331 of file serpent_shrine.cpp.
References GO_CONSOLE_HYDROSS, GO_CONSOLE_KARATHRESS, GO_CONSOLE_LEOTHERAS, GO_CONSOLE_LURKER, GO_CONSOLE_MOROGRIM, TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
Referenced by instance_serpentshrine_cavern::EngageBossConsole().
GOUse_go_ssc_boss_consoles()
bool GOUse_go_ssc_boss_consoles (Player * , GameObject * pGo)
Definition at line 383 of file serpent_shrine.cpp.
References Object::GetEntry(), WorldObject::GetInstanceData(), GO_CONSOLE_HYDROSS, GO_CONSOLE_KARATHRESS, GO_CONSOLE_LEOTHERAS, GO_CONSOLE_LURKER, GO_CONSOLE_MOROGRIM, InstanceData::SetData(), SPECIAL, TYPE_HYDROSS_EVENT, TYPE_KARATHRESS_EVENT, TYPE_LEOTHERAS_EVENT, TYPE_MOROGRIM_EVENT, and TYPE_THELURKER_EVENT.
Referenced by AddSC_instance_serpentshrine_cavern().