CMaNGOS_WoTLK: sethekk_halls.cpp File Reference
sethekk_halls.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sethekk_halls.h"
#include "Entities/TemporarySpawn.h"
Enumerations
enum AnzuIntro {
TRIGGER_COUNT = 14 , SPELL_OTHERWORLDLY_PORTAL = 39952 , SPELL_PURPLE_BANISH_STATE = 32566 , SPELL_RAVEN_GOD_SUMMON_BEAMS = 39978 ,
SPELL_ULTRIS_DESTROYED = 35757 , SPELL_RED_LIGHTNING_BOLT = 39990
}
Functions
bool ProcessEventId_event_spell_summon_raven_god (uint32, Object *source, Object *, bool bIsStart)
InstanceData * GetInstanceData_instance_sethekk_halls (Map *pMap)
void AddSC_instance_sethekk_halls ()
Variables
float triggerPositions [TRIGGER_COUNT][4]
Enumeration Type Documentation
AnzuIntro
enum AnzuIntro
Enumerator
TRIGGER_COUNT
SPELL_OTHERWORLDLY_PORTAL
SPELL_PURPLE_BANISH_STATE
SPELL_RAVEN_GOD_SUMMON_BEAMS
SPELL_ULTRIS_DESTROYED
SPELL_RED_LIGHTNING_BOLT
Definition at line 147 of file sethekk_halls.cpp.
Function Documentation
AddSC_instance_sethekk_halls()
void AddSC_instance_sethekk_halls ()
Definition at line 297 of file sethekk_halls.cpp.
References Script::GetInstanceData, GetInstanceData_instance_sethekk_halls(), Script::Name, Script::pProcessEventId, ProcessEventId_event_spell_summon_raven_god(), and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_sethekk_halls()
InstanceData* GetInstanceData_instance_sethekk_halls (Map * pMap)
Definition at line 292 of file sethekk_halls.cpp.
Referenced by AddSC_instance_sethekk_halls().
ProcessEventId_event_spell_summon_raven_god()
bool ProcessEventId_event_spell_summon_raven_god (uint32 , Object * source, Object * , bool bIsStart)
Definition at line 259 of file sethekk_halls.cpp.
References DONE, WorldObject::GetInstanceData(), Object::GetTypeId(), IN_PROGRESS, NPC_ANZU, TYPE_ANZU, and TYPEID_PLAYER.
Referenced by AddSC_instance_sethekk_halls().
Variable Documentation
triggerPositions
float triggerPositions[TRIGGER_COUNT][4]
Initial value:
=
{
    { -55.26986f, 313.4585f, 50.90593f, 0.3316126f},
    { -59.17055f, 314.39f, 51.65655f, 0.541052f},
    { -79.32272f, 314.4245f, 50.42631f, 2.181662f},
    { -86.93535f, 314.4072f, 50.36619f, 5.916666f},
    { -82.65174f, 314.4917f, 49.48673f, 0.4712389f},
    { -110.0913f, 314.4524f, 50.17954f, 1.43117f},
    { -113.7065f, 314.51f, 51.44148f, 0.2617994f},
    { -112.4148f, 258.7079f, 50.66346f, 0.4363323f},
    { -108.5766f, 258.7865f, 51.30656f, 3.124139f},
    { -88.22328f, 258.7913f, 50.12397f, 2.600541f},
    { -84.26708f, 258.7147f, 49.33371f, 4.328416f},
    { -80.07829f, 258.7955f, 50.39458f, 0.2268928f},
    { -59.91186f, 259.3824f, 50.82623f, 1.37881f},
    { -55.34531f, 258.1663f, 51.48593f, 1.623156f},
}
Definition at line 158 of file sethekk_halls.cpp.
Referenced by instance_sethekk_halls::StartAnzuIntro().