CMaNGOS_WoTLK: shadowmoon_valley.cpp File Reference
shadowmoon_valley.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct mob_mature_netherwing_drakeAI
struct mob_enslaved_netherwing_drakeAI
struct npc_dragonmaw_peonAI
struct npc_wildaAI
struct TorlothCinematic
struct Location
struct WaveData
struct mob_torlothAI
struct npc_lord_illidan_stormrageAI
struct npc_totem_of_spiritsAI
struct WaveCoords
struct npc_shadowlord_deathwailAI
struct mob_shadowmoon_soulstealerAI
struct npc_spawned_oronok_tornheartAI
struct npc_domesticated_felboarAI
struct npc_veneratus_spawn_nodeAI
struct npc_disobedient_dragonmaw_peonAI
struct SpawnData
struct DeadliestScriptInfo
struct npc_commanderAI
struct npc_commander_hobbAI
struct npc_commander_arcusAI
struct DragonmawRacerScriptInfo
struct npc_dragonmaw_racerAI
struct npc_dragonmaw_racer_muckjawAI
struct npc_dragonmaw_racer_tropeAI
struct npc_dragonmaw_racer_corlokAI
struct npc_dragonmaw_racer_ichmanAI
struct npc_dragonmaw_racer_mulverickAI
struct npc_dragonmaw_racer_skyshatterAI
struct DragonmawKnockdownTheAggroCheck
struct mob_bt_battle_fighterAI
struct FormationMap
struct npc_bt_battle_sensor
struct TagGreaterFelfireDiemetradon
struct DragonmawIllusionBase
struct DragonmawIllusionTransform
struct CallingRider
Enumerations
enum {
SAY_JUST_EATEN = -1000175 , SPELL_PLACE_CARCASS = 38439 , SPELL_JUST_EATEN = 38502 , SPELL_NETHER_BREATH = 38467 ,
SPELL_INTANGIBLE_PRESENCE = 36513 , QUEST_KINDNESS = 10804 , NPC_EVENT_PINGER = 22131 , GO_FLAYER_CARCASS = 185155
}
enum {
FACTION_FRIENDLY = 1840 , SPELL_HIT_FORCE_OF_NELTHARAKU = 38762 , SPELL_FORCE_OF_NELTHARAKU = 38775 , EMOTE_ON_HIT_FORCE = -1015001 ,
QUEST_FORCE_OF_NELT = 10854 , NPC_DRAGONMAW_SUBJUGATOR = 21718 , NPC_ESCAPE_DUMMY = 21348
}
enum {
SAY_PEON_1 = -1000652 , SAY_PEON_2 = -1000653 , SAY_PEON_3 = -1000654 , SAY_PEON_4 = -1000655 ,
SAY_PEON_5 = -1000656 , SPELL_SERVING_MUTTON = 40468 , NPC_DRAGONMAW_KILL_CREDIT = 23209 , EQUIP_ID_MUTTON = 2202 ,
POINT_DEST = 1
}
enum {
SAY_WIL_START = -1000381 , SAY_WIL_AGGRO_1 = -1000382 , SAY_WIL_AGGRO_2 = -1000383 , SAY_WIL_FREE_SPIRITS = -1000384 ,
SAY_WIL_FIND_EXIT = -1000386 , SAY_WIL_PROGRESS_1 = -1000385 , SAY_WIL_PROGRESS_2 = -1000387 , SAY_WIL_PROGRESS_3 = -1000388 ,
SAY_WIL_PROGRESS_4 = -1001168 , SAY_WIL_PROGRESS_5 = -1001169 , SAY_WIL_JUST_AHEAD = -1000389 , SAY_WIL_END = -1000390 ,
SPELL_CHAIN_LIGHTNING = 16006 , SPELL_EARTHBING_TOTEM = 15786 , SPELL_FROST_SHOCK = 12548 , SPELL_HEALING_WAVE = 12491 ,
SPELL_WATER_BUBBLE = 35929 , SPELL_BREAK_WATER_PRISON = 35933 , QUEST_ESCAPE_COILSCAR = 10451 , NPC_COILSKAR_ASSASSIN = 21044 ,
NPC_CAPTURED_WATER_SPIRIT = 21029
}
enum {
QUEST_BATTLE_OF_THE_CRIMSON_WATCH = 10781 , EVENT_COOLDOWN = 30000 , SAY_EVENT_START = -1015103 , SAY_TORLOTH_DIALOGUE1 = -1000532 ,
SAY_TORLOTH_DIALOGUE2 = -1000533 , SAY_TORLOTH_DIALOGUE3 = -1000534 , SAY_ILLIDAN_DIALOGUE = -1000535 , SAY_ILLIDAN_SUMMON1 = -1000536 ,
SAY_ILLIDAN_SUMMON2 = -1000537 , SAY_ILLIDAN_SUMMON3 = -1000538 , SAY_ILLIDAN_SUMMON4 = -1000539 , SAY_EVENT_COMPLETED = -1000540 ,
MODEL_ID_FELGUARD = 18654 , MODEL_ID_DREADLORD = 19991 , NPC_ILLIDARI_SOLDIER = 22075 , NPC_ILLIDARI_MIND_BREAKER = 22074 ,
NPC_ILLIDARI_HIGHLORD = 19797 , NPC_TORLOTH_THE_MAGNIFICENT = 22076 , NPC_LORD_ILLIDAN = 22083 , NPC_MARCUS_AURALION = 22073
}
enum CinematicCreature { LORD_ILLIDAN = 1 , TORLOTH = 0 }
enum {
SPELL_CLEAVE = 15284 , SPELL_SHADOWFURY = 39082 , SPELL_SPELL_REFLECTION = 33961 , SPELL_SPIRIT_PARTICLES = 37119 ,
SPELL_SHADOWFORM = 37816 , FACTION_HOSTILE = 14
}
enum TorlothActions {
TORLOTH_CLEAVE , TORLOTH_SHADOWFURY , TORLOTH_SPELL_REFLECTION , TORLOTH_ACTION_MAX ,
TORLOTH_ANIMATIONS
}
enum {
QUEST_SPIRITS_FIRE_AND_EARTH = 10458 , QUEST_SPIRITS_WATER = 10480 , QUEST_SPIRITS_AIR = 10481 , SPELL_ELEMENTAL_SIEVE = 36035 ,
SPELL_CALL_TO_THE_SPIRITS = 36206 , SPELL_EARTH_CAPTURED = 36025 , SPELL_FIERY_CAPTURED = 36115 , SPELL_WATER_CAPTURED = 36170 ,
SPELL_AIR_CAPTURED = 36181 , SPELL_EARTH_CAPTURED_CREDIT = 36108 , SPELL_FIERY_CAPTURED_CREDIT = 36117 , SPELL_WATER_CAPTURED_CREDIT = 36171 ,
SPELL_AIR_CAPTURED_CREDIT = 36182 , NPC_TOTEM_OF_SPIRITS = 21071 , NPC_EARTH_SPIRIT = 21050 , NPC_FIERY_SPIRIT = 21061 ,
NPC_WATER_SPIRIT = 21059 , NPC_AIR_SPIRIT = 21060 , NPC_EARTHEN_SOUL = 21073 , NPC_FIERY_SOUL = 21097 ,
NPC_WATERY_SOUL = 21109 , NPC_AIRY_SOUL = 21116 , NPC_CREDIT_MARKER_EARTH = 21092 , NPC_CREDIT_MARKER_FIERY = 21094 ,
NPC_CREDIT_MARKER_WATER = 21095 , NPC_CREDIT_MARKER_AIR = 21096 , EVENT_EARTH = 13513 , EVENT_FIERY = 13514 ,
EVENT_WATER = 13515 , EVENT_AIR = 13516
}
enum {
SAY_BEGIN_DESCENT = -1015002 , SAY_HEART_RETRIEVED = -1015003 , SAY_DEAD = -1015004 , NPC_SHADOWLORD_DEATHWAIL = 22006 ,
NPC_HOF_VISUAL_TRIGGER = 22058 , NPC_SHADOWMOON_SOULSTEALER = 22061 , NPC_DEATHWAIL_VISUAL_TRIG = 22096 , NPC_SHADOWMOON_RETAINER = 22102 ,
NPC_FELFIRE_SUMMONER = 22121 , GOBJECT_HEART_OF_FURY = 185125 , SPELL_SHADOW_BOLT = 12471 , SPELL_SHADOW_BOLT_VOLLEY = 15245 ,
SPELL_FEAR = 27641 , SPELL_FEL_FIREBALL = 38312 , SPELL_SUMMON_FEL_FIRE = 38375 , FEAR_CD = 20000 ,
FEL_FIREBALL_CD = 6000 , SHADOW_BOLT_CD = 4000 , SHADOW_BOLT_VOLLEY_CD = 10000 , PLAYER_CHECK_CD = 2000 ,
RETAINER_WAVE_CD = 100000 , MAX_PLAYER_DISTANCE = 100 , RETAINER_DESPAWN_TIME = 180000 , DEATHWAIL_DESPAWN_TIME = 300000
}
enum {
SAY_ORONOK_TOGETHER = -1000803 , SAY_ORONOK_READY = -1000804 , SAY_ORONOK_ELEMENTS = -1000805 , SAY_ORONOK_EPILOGUE_1 = -1000806 ,
SAY_TORLOK_EPILOGUE_2 = -1000807 , SAY_ORONOK_EPILOGUE_3 = -1000808 , SAY_EARTH_EPILOGUE_4 = -1000809 , SAY_FIRE_EPILOGUE_5 = -1000810 ,
SAY_EARTH_EPILOGUE_6 = -1000811 , SAY_ORONOK_EPILOGUE_7 = -1000812 , EMOTE_GIVE_WEAPONS = -1000813 , SAY_ORONOK_EPILOGUE_8 = -1000814 ,
GOSSIP_ITEM_FIGHT = -3000109 , GOSSIP_TEXT_ID_ORONOK = 10421 , SPELL_EARTHBIND_TOTEM = 15786 , SPELL_ORONOK_SPEED_INCREASE = 37246 ,
SPELL_ELEMENTAL_SPAWN_IN = 25035 , NPC_ORONOK_TORN_HEART = 21685 , NPC_GROMTOR_SON_OF_ORONOK = 21687 , NPC_BORAK_SON_OF_ORONOK = 21686 ,
NPC_CYRUKH_THE_FIRELORD = 21181 , NPC_REDEEMED_SPIRIT_OF_EARTH = 21739 , NPC_REDEEMED_SPIRIT_OF_FIRE = 21740 , NPC_REDEEMED_SPIRIT_OF_AIR = 21738 ,
NPC_REDEEMED_SPIRIT_OF_WATER = 21741 , NPC_EARTHMENDER_TORLOK = 21024 , GO_MARK_OF_KAELTHAS = 185170 , QUEST_CIPHER_OF_DAMNATION = 10588 ,
POINT_ID_ATTACK_READY = 1 , POINT_ID_ELEMENTS = 2 , POINT_ID_EPILOGUE = 3 , WAYPOINT_ID_DESPAWN = 5 ,
WAYPOINT_ID_INTRO_FINAL = 31 , EVENT_STARTED_MOVING = 1 , EVENT_GIVE_WEAPONS = 2 , EVENT_MOUNT = 3 ,
EVENT_HOVER_AND_MOVE = 4 , MOUNT_ID_ORONOK = 17721 , FACTION_ORONOK_COMBAT = 495 , FACTION_ORONOK_FRIENDLY = 35 ,
PATH_ID_OUTRO = 2
}
enum {
EMOTE_SNIFF_AIR = -1000907 , EMOTE_START_DIG = -1000908 , EMOTE_SQUEAL = -1000909 , SPELL_SHADOWMOON_TUBER = 36462 ,
SPELL_SPECIAL_UNARMED = 33334 , SPELL_TUBER_WHISTLE = 36652 , NPC_DOMESTICATED_FELBOAR = 21195 , NPC_SHADOWMOON_TUBER_NODE = 21347 ,
GO_SHADOWMOON_TUBER_MOUND = 184701
}
enum { SAY_VENERATUS_SPAWN = -1000579 , NPC_VENERATUS = 20427 , NPC_SPIRIT_HUNTER = 21332 }
enum {
SAY_IDLE1 = -1001285 , SAY_IDLE2 = -1001286 , SAY_BOOTERANG1 = -1001287 , SAY_BOOTERANG2 = -1001288 ,
SAY_BOOTERANG3 = -1001289 , SAY_BOOTERANG4 = -1001290 , SAY_BOOTERANG5 = -1001291 , SAY_BOOTERANG6 = -1001292 ,
SPELL_BOOTERANG = 40742 , SPELL_LAZY_AND_GOOD_FOR_NOTHING = 40732 , SPELL_DEFIANT_AND_ENRAGED = 40735 , SPELL_PEON_CLEAR_ALL = 40762 ,
SPELL_KICK = 34802 , SPELL_SUNDER_ARMOR = 15572 , NPC_PEON = 22252 , NPC_PEON_WORK_NODE = 23308 ,
NPC_DISOBEDIENT_PEON = 23311 , FACTION_DISOBEDIENT = 14 , FACTION_WHACKED = 62 , EMOTE_WORKING = 233 ,
POINT_ARRIVED = 1
}
enum {
SAY_EVENT_ACCEPT_ARCUS = -1001293 , SAY_EVENT_START_ARCUS = -1001294 , SAY_EVENT_END_ARCUS = -1001295 , SAY_EVENT_ACCEPT_HOBB = -1001296 ,
SAY_EVENT_START_HOBB = -1001297 , SAY_EVENT_END_HOBB = -1001298 , QUEST_DEADLIEST_TRAP_SCRYERS = 11097 , QUEST_DEADLIEST_TRAP_ALDOR = 11101 ,
SPELL_AIMED_SHOT = 38370 , SPELL_SHOOT = 41440 , SPELL_MULTI_SHOT = 41448 , NPC_SANCTUM_DEFENDER = 23435 ,
NPC_ALTAR_DEFENDER = 23453 , NPC_SCRYERS_DRAGONMAW_SKYBREAKER = 23440 , NPC_ALDOR_DRAGONMAW_SKYBREAKER = 23441 , COMMANDER_HOBB = 0 ,
COMMANDER_ARCUS = 1 , COMMANDER_COUNT = 2 , DEFENDER_SPAWN_COUNT = 10 , DRAGONMAW_SPAWN_COUNT = 9 ,
LAST_POINT_HOBB = 2 , LAST_POINT_ARCUS = 6 , POINT_HOME = 1 , DRAGONMAW_KILL_COUNT = 30
}
enum CommanderActions : uint32 {
COMMANDER_COMBAT_ACTION_AIMED_SHOT , COMMANDER_COMBAT_ACTION_MULTI_SHOT , COMMANDER_COMBAT_ACTION_SHOOT , COMMANDER_COMBAT_ACTION_MAX ,
COMMANDER_ACTION_START_QUEST_FLAGS , COMMANDER_ACTION_START_QUEST_TEXT , COMMANDER_ACTION_START_QUEST_MOVEMENT , COMMANDER_ACTION_POST_MOVEMENT_TEXT ,
COMMANDER_ACTION_POST_MOVEMENT_FACE_DIRECTION , COMMANDER_ACTION_POST_MOVEMENT_START_EVENT , COMMANDER_ACTION_WIN_RETURN , COMMANDER_ACTION_FAIL_EVENT
}
enum {
QUEST_MUCKJAW = 11064 , QUEST_TROPE = 11067 , QUEST_CORLOK = 11068 , QUEST_ICHMAN = 11069 ,
QUEST_MULVERICK = 11070 , QUEST_SKYSHATTER = 11071 , SAY_START_MUCKJAW = -1001299 , SAY_END_MUCKJAW = -1001300 ,
SAY_START_TROPE = -1001301 , SAY_END_TROPE = -1001302 , SAY_START_CORLOK = -1001303 , SAY_END_CORLOK = -1001304 ,
SAY_START_ICHMAN = -1001305 , SAY_END_ICHMAN = -1001306 , SAY_START_MULVERICK = -1001307 , SAY_END_MULVERICK = -1001308 ,
SAY_START_SKYSHATTER = -1001309 , SAY_MID_SKYSHATTER = -1001310 , SAY_END_SKYSHATTER = -1001311 , SPELL_AGGRO_CHECK_MUCKJAW = 40847 ,
SPELL_AGGRO_CHECK_TROPE = 40984 , SPELL_AGGRO_CHECK_CORLOK = 40992 , SPELL_AGGRO_CHECK_ICHMAN = 41006 , SPELL_AGGRO_CHECK_MULVERICK = 41014 ,
SPELL_AGGRO_CHECK_SKYSHATTER = 41020 , SPELL_AGGRO_BURST_MUCKJAW = 40850 , SPELL_AGGRO_BURST_TROPE = 40986 , SPELL_AGGRO_BURST_CORLOK = 40994 ,
SPELL_AGGRO_BURST_ICHMAN = 41008 , SPELL_AGGRO_BURST_MULVERICK = 41016 , SPELL_AGGRO_BURST_SKYSHATTER = 41023 , SPELL_ATTACK_TROPE = 40909 ,
SPELL_ATTACK_CORLOK = 40894 , SPELL_ATTACK_ICHMAN = 40928 , SPELL_ATTACK_MULVERICK = 40930 , SPELL_ATTACK_SKYSHATTER = 40945 ,
NPC_TARGET_TROPE = 23357 , NPC_TARGET_CORLOK = 23358 , NPC_TARGET_ICHMAN = 23359 , NPC_TARGET_MULVERICK = 23360 ,
NPC_TARGET_SKYSHATTER = 23361 , RACER_MUCKJAW = 0 , RACER_TROPE = 1 , RACER_CORLOK = 2 ,
RACER_ICHMAN = 3 , RACER_MULVERICK = 4 , RACER_SKYSHATTER = 5 , RACER_COUNT = 6
}
enum {
NPC_DOOMWALKER = 17711 , NPC_FORMATION_MARKER = 19179 , NPC_ILLIDARI_RAVAGER = 22857 , NPC_SHADOWHOOF_ASSASSIN = 22858 ,
NPC_ILLIDARI_SUCCUBUS = 22860 , NPC_LIGHTSWORN_VINDICATOR = 22861 , NPC_ANCHORITE_CAALEN = 22862 , NPC_SEASONED_MAGISTER = 22863 ,
NPC_FYRA_DAWNSTAR = 22864 , NPC_BT_BATTLE_SENOR = 22934 , NPC_SHADOWLORD = 22988 , SAY_VINDICATOR_ON_AGGRO_1 = -1015062 ,
SAY_MAG_ON_AGGRO_1 = -1015063 , SAY_MAG_ON_AGGRO_2 = -1015064 , SAY_MAG_ON_AGGRO_3 = -1015065 , SAY_CAALEN_FORWARD = -1015032 ,
SAY_FYRA_ONWARD = -1015031 , ILLIDARI_ATTACK_INTERVAL = 150000 , REINFORCE_INTERVAL = 30000 , SPELL_BATTLE_FLOW_REGULATOR = 39699 ,
SPELL_RAVAGER_CLEAVE = 15496 , SPELL_RAVAGER_CUTDOWN = 32009 , SPELL_RAVAGER_DEMORALIZING_SHOUT = 16244 , SPELL_ASSASSIN_DEBILITATING_STRIKE = 37577 ,
SPELL_ASSASSIN_SINISTER_STRIKE = 14873 , SPELL_SUCCUBUS_LASH_OF_PAIN = 32202 , SPELL_SUCCUBUS_SEDUCTION = 31865 , SPELL_VINDICATOR_EXORCISM = 33632 ,
SPELL_VINDICATOR_HAMMER = 13005 , SPELL_VINDICATOR_HOLY_LIGHT = 13952 , SPELL_VINDICATOR_SEAL_OF_SAC = 13903 , SPELL_CAALEN_HOLY_SMITE = 20696 ,
SPELL_CAALEN_PRAYER_OF_HEALING = 35943 , SPELL_MAGISTER_FIREBALL = 9053 , SPELL_SHADOWLORD_INFERNO = 39941 , SPELL_SHADOWLORD_CARRION_SWARM = 39942 ,
SPELL_SHADOWLORD_SLEEP = 12098
}
enum { ILLIDARI_CLEAVE , ILLIDARI_CUTDOWN , ILLIDARI_DEMORALIZING_SHOUT , ILLIDARI_ACTION_MAX }
enum { ASSASSIN_DEBILITATING_STRIKE , ASSASSIN_SINISTER_STRIKE , ASSASSIN_ACTION_MAX }
enum { SUCCUBUS_LASH_OF_PAIN , SUCCUBUS_SEDUCTION , SUCCUBUS_ACTION_MAX }
enum {
VINDICATOR_EXORCISM , VINDICATOR_HAMMER , VINDICATOR_HOLY_LIGHT , VINDICATOR_SEAL_OF_SAC ,
VINDICATOR_ACTION_MAX
}
enum { CAALEN_HOLY_SMITE , CAALEN_PRAYER_OF_HEALING , CAALEN_ACTION_MAX }
enum { MAGISTER_FIREBALL , MAGISTER_ACTION_MAX }
enum { SHADOWLORD_INFERNO , SHADOWLORD_CARRION_SWARM , SHADOWLORD_SLEEP , SHADOWLORD_ACTION_MAX }
Functions
UnitAI * GetAI_mob_mature_netherwing_drake (Creature *pCreature)
UnitAI * GetAI_mob_enslaved_netherwing_drake (Creature *pCreature)
bool EffectDummyCreature_npc_dragonmaw_peon (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_wilda (Creature *pCreature)
bool QuestAccept_npc_wilda (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GOQuestAccept_GO_crystal_prison (Player *player, GameObject *, Quest const *quest)
bool EffectDummyCreature_npc_totem_of_spirits (Unit *, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool ProcessEventId_event_spell_soul_captured_credit (uint32 uiEventId, Object *pSource, Object *, bool bIsStart)
UnitAI * GetAI_npc_shadowlord_deathwail (Creature *pCreature)
UnitAI * GetAI_npc_spawned_oronok_tornheart (Creature *pCreature)
bool GossipHello_npc_spawned_oronok_tornheart (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_spawned_oronok_tornheart (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_domesticated_felboar (Creature *pCreature)
bool EffectDummyCreature_npc_shadowmoon_tuber_node (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_veneratus_spawn_node (Creature *pCreature)
UnitAI * GetAI_npc_disobedient_dragonmaw_peon (Creature *pCreature)
bool QuestAccept_npc_commander (Player *player, Creature *questgiver, Quest const *quest)
bool QuestAccept_npc_dragonmaw_racer (Player *player, Creature *questgiver, Quest const *quest)
UnitAI * GetAI_mob_bt_battle_fighter (Creature *pCreature)
UnitAI * GetAI_npc_bt_battle_sensor (Creature *pCreature)
void AddSC_shadowmoon_valley ()
Variables
const float EVENT_AREA_RADIUS = 65.0
static TorlothCinematic TorlothAnim []
static Location SpawnLocation []
static WaveData WavesInfo []
static const WaveCoords WaveSpawnCoords [3][3]
static const WaveCoords * WaveGroupOneSpawnCoords = WaveSpawnCoords[0]
static const WaveCoords * WaveGroupTwoSpawnCoords = WaveSpawnCoords[1]
static const WaveCoords * WaveGroupThreeSpawnCoords = WaveSpawnCoords[2]
static const WaveCoords DeathwailDescentCoords []
static const DialogueEntry aOutroDialogue []
static const Position aDamnationLocations []
static SpawnData defenderSpawns [COMMANDER_COUNT][DEFENDER_SPAWN_COUNT]
static SpawnData dragonmawSpawns [COMMANDER_COUNT][DRAGONMAW_SPAWN_COUNT]
static DeadliestScriptInfo deadliestScriptInfo [COMMANDER_COUNT]
static DragonmawRacerScriptInfo dragonmawRacesScriptInfo [RACER_COUNT]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_JUST_EATEN
SPELL_PLACE_CARCASS
SPELL_JUST_EATEN
SPELL_NETHER_BREATH
SPELL_INTANGIBLE_PRESENCE
QUEST_KINDNESS
NPC_EVENT_PINGER
GO_FLAYER_CARCASS
Definition at line 51 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
FACTION_FRIENDLY
SPELL_HIT_FORCE_OF_NELTHARAKU
SPELL_FORCE_OF_NELTHARAKU
EMOTE_ON_HIT_FORCE
QUEST_FORCE_OF_NELT
NPC_DRAGONMAW_SUBJUGATOR
NPC_ESCAPE_DUMMY
Definition at line 198 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_PEON_1
SAY_PEON_2
SAY_PEON_3
SAY_PEON_4
SAY_PEON_5
SPELL_SERVING_MUTTON
NPC_DRAGONMAW_KILL_CREDIT
EQUIP_ID_MUTTON
POINT_DEST
Definition at line 313 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_WIL_START
SAY_WIL_AGGRO_1
SAY_WIL_AGGRO_2
SAY_WIL_FREE_SPIRITS
SAY_WIL_FIND_EXIT
SAY_WIL_PROGRESS_1
SAY_WIL_PROGRESS_2
SAY_WIL_PROGRESS_3
SAY_WIL_PROGRESS_4
SAY_WIL_PROGRESS_5
SAY_WIL_JUST_AHEAD
SAY_WIL_END
SPELL_CHAIN_LIGHTNING
SPELL_EARTHBING_TOTEM
SPELL_FROST_SHOCK
SPELL_HEALING_WAVE
SPELL_WATER_BUBBLE
SPELL_BREAK_WATER_PRISON
QUEST_ESCAPE_COILSCAR
NPC_COILSKAR_ASSASSIN
NPC_CAPTURED_WATER_SPIRIT
Definition at line 472 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_BATTLE_OF_THE_CRIMSON_WATCH
EVENT_COOLDOWN
SAY_EVENT_START
SAY_TORLOTH_DIALOGUE1
SAY_TORLOTH_DIALOGUE2
SAY_TORLOTH_DIALOGUE3
SAY_ILLIDAN_DIALOGUE
SAY_ILLIDAN_SUMMON1
SAY_ILLIDAN_SUMMON2
SAY_ILLIDAN_SUMMON3
SAY_ILLIDAN_SUMMON4
SAY_EVENT_COMPLETED
MODEL_ID_FELGUARD
MODEL_ID_DREADLORD
NPC_ILLIDARI_SOLDIER
NPC_ILLIDARI_MIND_BREAKER
NPC_ILLIDARI_HIGHLORD
NPC_TORLOTH_THE_MAGNIFICENT
NPC_LORD_ILLIDAN
NPC_MARCUS_AURALION
Definition at line 704 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_CLEAVE
SPELL_SHADOWFURY
SPELL_SPELL_REFLECTION
SPELL_SPIRIT_PARTICLES
SPELL_SHADOWFORM
FACTION_HOSTILE
Definition at line 812 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SPIRITS_FIRE_AND_EARTH
QUEST_SPIRITS_WATER
QUEST_SPIRITS_AIR
SPELL_ELEMENTAL_SIEVE
SPELL_CALL_TO_THE_SPIRITS
SPELL_EARTH_CAPTURED
SPELL_FIERY_CAPTURED
SPELL_WATER_CAPTURED
SPELL_AIR_CAPTURED
SPELL_EARTH_CAPTURED_CREDIT
SPELL_FIERY_CAPTURED_CREDIT
SPELL_WATER_CAPTURED_CREDIT
SPELL_AIR_CAPTURED_CREDIT
NPC_TOTEM_OF_SPIRITS
NPC_EARTH_SPIRIT
NPC_FIERY_SPIRIT
NPC_WATER_SPIRIT
NPC_AIR_SPIRIT
NPC_EARTHEN_SOUL
NPC_FIERY_SOUL
NPC_WATERY_SOUL
NPC_AIRY_SOUL
NPC_CREDIT_MARKER_EARTH
NPC_CREDIT_MARKER_FIERY
NPC_CREDIT_MARKER_WATER
NPC_CREDIT_MARKER_AIR
EVENT_EARTH
EVENT_FIERY
EVENT_WATER
EVENT_AIR
Definition at line 1172 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_BEGIN_DESCENT
SAY_HEART_RETRIEVED
SAY_DEAD
NPC_SHADOWLORD_DEATHWAIL
NPC_HOF_VISUAL_TRIGGER
NPC_SHADOWMOON_SOULSTEALER
NPC_DEATHWAIL_VISUAL_TRIG
NPC_SHADOWMOON_RETAINER
NPC_FELFIRE_SUMMONER
GOBJECT_HEART_OF_FURY
SPELL_SHADOW_BOLT
SPELL_SHADOW_BOLT_VOLLEY
SPELL_FEAR
SPELL_FEL_FIREBALL
SPELL_SUMMON_FEL_FIRE
FEAR_CD
FEL_FIREBALL_CD
SHADOW_BOLT_CD
SHADOW_BOLT_VOLLEY_CD
PLAYER_CHECK_CD
RETAINER_WAVE_CD
MAX_PLAYER_DISTANCE
RETAINER_DESPAWN_TIME
DEATHWAIL_DESPAWN_TIME
Definition at line 1377 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ORONOK_TOGETHER
SAY_ORONOK_READY
SAY_ORONOK_ELEMENTS
SAY_ORONOK_EPILOGUE_1
SAY_TORLOK_EPILOGUE_2
SAY_ORONOK_EPILOGUE_3
SAY_EARTH_EPILOGUE_4
SAY_FIRE_EPILOGUE_5
SAY_EARTH_EPILOGUE_6
SAY_ORONOK_EPILOGUE_7
EMOTE_GIVE_WEAPONS
SAY_ORONOK_EPILOGUE_8
GOSSIP_ITEM_FIGHT
GOSSIP_TEXT_ID_ORONOK
SPELL_EARTHBIND_TOTEM
SPELL_ORONOK_SPEED_INCREASE
SPELL_ELEMENTAL_SPAWN_IN
NPC_ORONOK_TORN_HEART
NPC_GROMTOR_SON_OF_ORONOK
NPC_BORAK_SON_OF_ORONOK
NPC_CYRUKH_THE_FIRELORD
NPC_REDEEMED_SPIRIT_OF_EARTH
NPC_REDEEMED_SPIRIT_OF_FIRE
NPC_REDEEMED_SPIRIT_OF_AIR
NPC_REDEEMED_SPIRIT_OF_WATER
NPC_EARTHMENDER_TORLOK
GO_MARK_OF_KAELTHAS
QUEST_CIPHER_OF_DAMNATION
POINT_ID_ATTACK_READY
POINT_ID_ELEMENTS
POINT_ID_EPILOGUE
WAYPOINT_ID_DESPAWN
WAYPOINT_ID_INTRO_FINAL
EVENT_STARTED_MOVING
EVENT_GIVE_WEAPONS
EVENT_MOUNT
EVENT_HOVER_AND_MOVE
MOUNT_ID_ORONOK
FACTION_ORONOK_COMBAT
FACTION_ORONOK_FRIENDLY
PATH_ID_OUTRO
Definition at line 1882 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_SNIFF_AIR
EMOTE_START_DIG
EMOTE_SQUEAL
SPELL_SHADOWMOON_TUBER
SPELL_SPECIAL_UNARMED
SPELL_TUBER_WHISTLE
NPC_DOMESTICATED_FELBOAR
NPC_SHADOWMOON_TUBER_NODE
GO_SHADOWMOON_TUBER_MOUND
Definition at line 2372 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_VENERATUS_SPAWN
NPC_VENERATUS
NPC_SPIRIT_HUNTER
Definition at line 2499 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_IDLE1
SAY_IDLE2
SAY_BOOTERANG1
SAY_BOOTERANG2
SAY_BOOTERANG3
SAY_BOOTERANG4
SAY_BOOTERANG5
SAY_BOOTERANG6
SPELL_BOOTERANG
SPELL_LAZY_AND_GOOD_FOR_NOTHING
SPELL_DEFIANT_AND_ENRAGED
SPELL_PEON_CLEAR_ALL
SPELL_KICK
SPELL_SUNDER_ARMOR
NPC_PEON
NPC_PEON_WORK_NODE
NPC_DISOBEDIENT_PEON
FACTION_DISOBEDIENT
FACTION_WHACKED
EMOTE_WORKING
POINT_ARRIVED
Definition at line 2536 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_EVENT_ACCEPT_ARCUS
SAY_EVENT_START_ARCUS
SAY_EVENT_END_ARCUS
SAY_EVENT_ACCEPT_HOBB
SAY_EVENT_START_HOBB
SAY_EVENT_END_HOBB
QUEST_DEADLIEST_TRAP_SCRYERS
QUEST_DEADLIEST_TRAP_ALDOR
SPELL_AIMED_SHOT
SPELL_SHOOT
SPELL_MULTI_SHOT
NPC_SANCTUM_DEFENDER
NPC_ALTAR_DEFENDER
NPC_SCRYERS_DRAGONMAW_SKYBREAKER
NPC_ALDOR_DRAGONMAW_SKYBREAKER
COMMANDER_HOBB
COMMANDER_ARCUS
COMMANDER_COUNT
DEFENDER_SPAWN_COUNT
DRAGONMAW_SPAWN_COUNT
LAST_POINT_HOBB
LAST_POINT_ARCUS
POINT_HOME
DRAGONMAW_KILL_COUNT
Definition at line 2734 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MUCKJAW
QUEST_TROPE
QUEST_CORLOK
QUEST_ICHMAN
QUEST_MULVERICK
QUEST_SKYSHATTER
SAY_START_MUCKJAW
SAY_END_MUCKJAW
SAY_START_TROPE
SAY_END_TROPE
SAY_START_CORLOK
SAY_END_CORLOK
SAY_START_ICHMAN
SAY_END_ICHMAN
SAY_START_MULVERICK
SAY_END_MULVERICK
SAY_START_SKYSHATTER
SAY_MID_SKYSHATTER
SAY_END_SKYSHATTER
SPELL_AGGRO_CHECK_MUCKJAW
SPELL_AGGRO_CHECK_TROPE
SPELL_AGGRO_CHECK_CORLOK
SPELL_AGGRO_CHECK_ICHMAN
SPELL_AGGRO_CHECK_MULVERICK
SPELL_AGGRO_CHECK_SKYSHATTER
SPELL_AGGRO_BURST_MUCKJAW
SPELL_AGGRO_BURST_TROPE
SPELL_AGGRO_BURST_CORLOK
SPELL_AGGRO_BURST_ICHMAN
SPELL_AGGRO_BURST_MULVERICK
SPELL_AGGRO_BURST_SKYSHATTER
SPELL_ATTACK_TROPE
SPELL_ATTACK_CORLOK
SPELL_ATTACK_ICHMAN
SPELL_ATTACK_MULVERICK
SPELL_ATTACK_SKYSHATTER
NPC_TARGET_TROPE
NPC_TARGET_CORLOK
NPC_TARGET_ICHMAN
NPC_TARGET_MULVERICK
NPC_TARGET_SKYSHATTER
RACER_MUCKJAW
RACER_TROPE
RACER_CORLOK
RACER_ICHMAN
RACER_MULVERICK
RACER_SKYSHATTER
RACER_COUNT
Definition at line 3174 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_DOOMWALKER
NPC_FORMATION_MARKER
NPC_ILLIDARI_RAVAGER
NPC_SHADOWHOOF_ASSASSIN
NPC_ILLIDARI_SUCCUBUS
NPC_LIGHTSWORN_VINDICATOR
NPC_ANCHORITE_CAALEN
NPC_SEASONED_MAGISTER
NPC_FYRA_DAWNSTAR
NPC_BT_BATTLE_SENOR
NPC_SHADOWLORD
SAY_VINDICATOR_ON_AGGRO_1
SAY_MAG_ON_AGGRO_1
SAY_MAG_ON_AGGRO_2
SAY_MAG_ON_AGGRO_3
SAY_CAALEN_FORWARD
SAY_FYRA_ONWARD
ILLIDARI_ATTACK_INTERVAL
REINFORCE_INTERVAL
SPELL_BATTLE_FLOW_REGULATOR
SPELL_RAVAGER_CLEAVE
SPELL_RAVAGER_CUTDOWN
SPELL_RAVAGER_DEMORALIZING_SHOUT
SPELL_ASSASSIN_DEBILITATING_STRIKE
SPELL_ASSASSIN_SINISTER_STRIKE
SPELL_SUCCUBUS_LASH_OF_PAIN
SPELL_SUCCUBUS_SEDUCTION
SPELL_VINDICATOR_EXORCISM
SPELL_VINDICATOR_HAMMER
SPELL_VINDICATOR_HOLY_LIGHT
SPELL_VINDICATOR_SEAL_OF_SAC
SPELL_CAALEN_HOLY_SMITE
SPELL_CAALEN_PRAYER_OF_HEALING
SPELL_MAGISTER_FIREBALL
SPELL_SHADOWLORD_INFERNO
SPELL_SHADOWLORD_CARRION_SWARM
SPELL_SHADOWLORD_SLEEP
Definition at line 3594 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
ILLIDARI_CLEAVE
ILLIDARI_CUTDOWN
ILLIDARI_DEMORALIZING_SHOUT
ILLIDARI_ACTION_MAX
Definition at line 3645 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
ASSASSIN_DEBILITATING_STRIKE
ASSASSIN_SINISTER_STRIKE
ASSASSIN_ACTION_MAX
Definition at line 3653 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SUCCUBUS_LASH_OF_PAIN
SUCCUBUS_SEDUCTION
SUCCUBUS_ACTION_MAX
Definition at line 3660 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
VINDICATOR_EXORCISM
VINDICATOR_HAMMER
VINDICATOR_HOLY_LIGHT
VINDICATOR_SEAL_OF_SAC
VINDICATOR_ACTION_MAX
Definition at line 3667 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
CAALEN_HOLY_SMITE
CAALEN_PRAYER_OF_HEALING
CAALEN_ACTION_MAX
Definition at line 3676 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
MAGISTER_FIREBALL
MAGISTER_ACTION_MAX
Definition at line 3683 of file shadowmoon_valley.cpp.
anonymous enum
anonymous enum
Enumerator
SHADOWLORD_INFERNO
SHADOWLORD_CARRION_SWARM
SHADOWLORD_SLEEP
SHADOWLORD_ACTION_MAX
Definition at line 3689 of file shadowmoon_valley.cpp.
CinematicCreature
enum CinematicCreature
Enumerator
LORD_ILLIDAN
TORLOTH
Definition at line 733 of file shadowmoon_valley.cpp.
CommanderActions
enum CommanderActions : uint32
Enumerator
COMMANDER_COMBAT_ACTION_AIMED_SHOT
COMMANDER_COMBAT_ACTION_MULTI_SHOT
COMMANDER_COMBAT_ACTION_SHOOT
COMMANDER_COMBAT_ACTION_MAX
COMMANDER_ACTION_START_QUEST_FLAGS
COMMANDER_ACTION_START_QUEST_TEXT
COMMANDER_ACTION_START_QUEST_MOVEMENT
COMMANDER_ACTION_POST_MOVEMENT_TEXT
COMMANDER_ACTION_POST_MOVEMENT_FACE_DIRECTION
COMMANDER_ACTION_POST_MOVEMENT_START_EVENT
COMMANDER_ACTION_WIN_RETURN
COMMANDER_ACTION_FAIL_EVENT
Definition at line 2778 of file shadowmoon_valley.cpp.
TorlothActions
enum TorlothActions
Enumerator
TORLOTH_CLEAVE
TORLOTH_SHADOWFURY
TORLOTH_SPELL_REFLECTION
TORLOTH_ACTION_MAX
TORLOTH_ANIMATIONS
Definition at line 824 of file shadowmoon_valley.cpp.
Function Documentation
AddSC_shadowmoon_valley()
void AddSC_shadowmoon_valley ()
Definition at line 5357 of file shadowmoon_valley.cpp.
References EffectDummyCreature_npc_dragonmaw_peon(), EffectDummyCreature_npc_shadowmoon_tuber_node(), EffectDummyCreature_npc_totem_of_spirits(), Script::GetAI, GetAI_mob_bt_battle_fighter(), GetAI_mob_enslaved_netherwing_drake(), GetAI_mob_mature_netherwing_drake(), GetAI_npc_bt_battle_sensor(), GetAI_npc_disobedient_dragonmaw_peon(), GetAI_npc_domesticated_felboar(), GetAI_npc_shadowlord_deathwail(), GetAI_npc_spawned_oronok_tornheart(), GetAI_npc_veneratus_spawn_node(), GetAI_npc_wilda(), GOQuestAccept_GO_crystal_prison(), GossipHello_npc_spawned_oronok_tornheart(), GossipSelect_npc_spawned_oronok_tornheart(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pProcessEventId, Script::pQuestAcceptGO, Script::pQuestAcceptNPC, ProcessEventId_event_spell_soul_captured_credit(), QuestAccept_npc_commander(), QuestAccept_npc_dragonmaw_racer(), QuestAccept_npc_wilda(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_dragonmaw_peon()
bool EffectDummyCreature_npc_dragonmaw_peon (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 449 of file shadowmoon_valley.cpp.
References Creature::AI(), EFFECT_INDEX_1, EMOTE_ONESHOT_NONE, Object::GetObjectGuid(), Object::GetTypeId(), Unit::HandleEmote(), npc_dragonmaw_peonAI::SetPlayerTarget(), SPELL_SERVING_MUTTON, and TYPEID_PLAYER.
Referenced by AddSC_shadowmoon_valley().
EffectDummyCreature_npc_shadowmoon_tuber_node()
bool EffectDummyCreature_npc_shadowmoon_tuber_node (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 2471 of file shadowmoon_valley.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, EFFECT_INDEX_0, GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), Object::GetEntry(), GO_SHADOWMOON_TUBER_MOUND, GameObject::IsSpawned(), NPC_DOMESTICATED_FELBOAR, NPC_SHADOWMOON_TUBER_NODE, UnitAI::SendAIEvent(), and SPELL_TUBER_WHISTLE.
Referenced by AddSC_shadowmoon_valley().
EffectDummyCreature_npc_totem_of_spirits()
bool EffectDummyCreature_npc_totem_of_spirits (Unit * , uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 1267 of file shadowmoon_valley.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, SPELL_AIR_CAPTURED, SPELL_AIR_CAPTURED_CREDIT, SPELL_EARTH_CAPTURED, SPELL_EARTH_CAPTURED_CREDIT, SPELL_FIERY_CAPTURED, SPELL_FIERY_CAPTURED_CREDIT, SPELL_WATER_CAPTURED, SPELL_WATER_CAPTURED_CREDIT, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_shadowmoon_valley().
GetAI_mob_bt_battle_fighter()
UnitAI* GetAI_mob_bt_battle_fighter (Creature * pCreature)
Definition at line 4343 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_mob_enslaved_netherwing_drake()
UnitAI* GetAI_mob_enslaved_netherwing_drake (Creature * pCreature)
Definition at line 304 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_mob_mature_netherwing_drake()
UnitAI* GetAI_mob_mature_netherwing_drake (Creature * pCreature)
Definition at line 189 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_bt_battle_sensor()
UnitAI* GetAI_npc_bt_battle_sensor (Creature * pCreature)
Definition at line 5292 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_disobedient_dragonmaw_peon()
UnitAI* GetAI_npc_disobedient_dragonmaw_peon (Creature * pCreature)
Definition at line 2725 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_domesticated_felboar()
UnitAI* GetAI_npc_domesticated_felboar (Creature * pCreature)
Definition at line 2466 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_shadowlord_deathwail()
UnitAI* GetAI_npc_shadowlord_deathwail (Creature * pCreature)
Definition at line 1758 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_spawned_oronok_tornheart()
UnitAI* GetAI_npc_spawned_oronok_tornheart (Creature * pCreature)
Definition at line 2335 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_veneratus_spawn_node()
UnitAI* GetAI_npc_veneratus_spawn_node (Creature * pCreature)
Definition at line 2527 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GetAI_npc_wilda()
UnitAI* GetAI_npc_wilda (Creature * pCreature)
Definition at line 681 of file shadowmoon_valley.cpp.
Referenced by AddSC_shadowmoon_valley().
GOQuestAccept_GO_crystal_prison()
bool GOQuestAccept_GO_crystal_prison (Player * player, GameObject * , Quest const * quest)
Definition at line 1157 of file shadowmoon_valley.cpp.
References GetClosestCreatureWithEntry(), Quest::GetQuestId(), NPC_LORD_ILLIDAN, and QUEST_BATTLE_OF_THE_CRIMSON_WATCH.
Referenced by AddSC_shadowmoon_valley().
GossipHello_npc_spawned_oronok_tornheart()
bool GossipHello_npc_spawned_oronok_tornheart (Player * pPlayer, Creature * pCreature)
Definition at line 2340 of file shadowmoon_valley.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_FIGHT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_ORONOK, QUEST_CIPHER_OF_DAMNATION, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_shadowmoon_valley().
GossipSelect_npc_spawned_oronok_tornheart()
bool GossipSelect_npc_spawned_oronok_tornheart (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 2353 of file shadowmoon_valley.cpp.
References aDamnationLocations, DoScriptText(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, MotionMaster::MovePoint(), POINT_ID_ELEMENTS, Object::RemoveFlag(), SAY_ORONOK_ELEMENTS, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_shadowmoon_valley().
ProcessEventId_event_spell_soul_captured_credit()
bool ProcessEventId_event_spell_soul_captured_credit (uint32 uiEventId, Object * pSource, Object * , bool bIsStart)
Definition at line 1299 of file shadowmoon_valley.cpp.
References EVENT_AIR, EVENT_EARTH, EVENT_FIERY, EVENT_WATER, Object::GetTypeId(), Player::KilledMonsterCredit(), NPC_CREDIT_MARKER_AIR, NPC_CREDIT_MARKER_EARTH, NPC_CREDIT_MARKER_FIERY, NPC_CREDIT_MARKER_WATER, and TYPEID_UNIT.
Referenced by AddSC_shadowmoon_valley().
QuestAccept_npc_commander()
bool QuestAccept_npc_commander (Player * player, Creature * questgiver, Quest const * quest)
Definition at line 3156 of file shadowmoon_valley.cpp.
References Creature::AI(), Quest::GetQuestId(), QUEST_DEADLIEST_TRAP_ALDOR, and QUEST_DEADLIEST_TRAP_SCRYERS.
Referenced by AddSC_shadowmoon_valley().
QuestAccept_npc_dragonmaw_racer()
bool QuestAccept_npc_dragonmaw_racer (Player * player, Creature * questgiver, Quest const * quest)
Definition at line 3543 of file shadowmoon_valley.cpp.
References Creature::AI(), DoScriptText(), dragonmawRacesScriptInfo, Unit::GetMotionMaster(), Object::GetObjectGuid(), Quest::GetQuestId(), MotionMaster::MovePath(), PATH_FROM_EXTERNAL, QUEST_CORLOK, QUEST_ICHMAN, QUEST_MUCKJAW, QUEST_MULVERICK, QUEST_SKYSHATTER, QUEST_TROPE, Object::SetUInt32Value(), DragonmawRacerScriptInfo::startText, UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
Referenced by AddSC_shadowmoon_valley().
QuestAccept_npc_wilda()
bool QuestAccept_npc_wilda (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 686 of file shadowmoon_valley.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, Quest::GetQuestId(), QUEST_ESCAPE_COILSCAR, SAY_WIL_START, Creature::SetFactionTemporary(), Unit::SetLevitate(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_shadowmoon_valley().
Variable Documentation
aDamnationLocations
const Position aDamnationLocations[] static
Initial value:
=
{
    { -3587.229f, 1892.889f, 47.32373f, 2.199115f},
    { -3598.681f, 1888.016f, 47.32373f, 1.692969f},
    { -3605.315f, 1884.477f, 47.32373f, 1.308997f},
    { -3591.871f, 1886.822f, 47.32373f, 1.850049f},
    { -3595.36f, 1869.78f, 47.24f},
    { -3635.90f, 1860.94f, 52.93f},
    { -3599.71f, 1897.94f, 47.24f}
}
Definition at line 1966 of file shadowmoon_valley.cpp.
Referenced by npc_spawned_oronok_tornheartAI::EnterEvadeMode(), GossipSelect_npc_spawned_oronok_tornheart(), npc_spawned_oronok_tornheartAI::JustDidDialogueStep(), and npc_spawned_oronok_tornheartAI::WaypointMotionType().
aOutroDialogue
const DialogueEntry aOutroDialogue[] static
Initial value:
=
{
    {QUEST_CIPHER_OF_DAMNATION,     0,                              32000},
    {NPC_CYRUKH_THE_FIRELORD,       0,                              0},
    {EVENT_STARTED_MOVING,          0,                              1000},
    {NPC_EARTHMENDER_TORLOK,        0,                              1000},
    {SAY_ORONOK_EPILOGUE_1,         NPC_ORONOK_TORN_HEART,          5000},
    {SAY_TORLOK_EPILOGUE_2,         NPC_EARTHMENDER_TORLOK,         5000},
    {NPC_REDEEMED_SPIRIT_OF_EARTH,  0,                              5000},
    {SAY_ORONOK_EPILOGUE_3,         NPC_ORONOK_TORN_HEART,          5000},
    {SAY_EARTH_EPILOGUE_4,          NPC_REDEEMED_SPIRIT_OF_EARTH,   5000},
    {SAY_FIRE_EPILOGUE_5,           NPC_REDEEMED_SPIRIT_OF_FIRE,    14000},
    {SAY_EARTH_EPILOGUE_6,          NPC_REDEEMED_SPIRIT_OF_EARTH,   6000},
    {SAY_ORONOK_EPILOGUE_7,         NPC_ORONOK_TORN_HEART,          6000},
    {SAY_ORONOK_EPILOGUE_8,         NPC_ORONOK_TORN_HEART,          1000},
    {EVENT_GIVE_WEAPONS,            0,                              8500},
    {EVENT_MOUNT,                   0,                              1000},
    {EVENT_HOVER_AND_MOVE,          0,                              1000},
    {NPC_ORONOK_TORN_HEART,         0,                              0},
    {0, 0, 0},
}
Definition at line 1944 of file shadowmoon_valley.cpp.
deadliestScriptInfo
DeadliestScriptInfo deadliestScriptInfo[COMMANDER_COUNT] static
Initial value:
=
{
    { NPC_SCRYERS_DRAGONMAW_SKYBREAKER, NPC_SANCTUM_DEFENDER, LAST_POINT_HOBB, SAY_EVENT_ACCEPT_HOBB, SAY_EVENT_START_HOBB, SAY_EVENT_END_HOBB, SAY_EVENT_ACCEPT_ARCUS, QUEST_DEADLIEST_TRAP_SCRYERS },
    { NPC_ALDOR_DRAGONMAW_SKYBREAKER,   NPC_ALTAR_DEFENDER,   LAST_POINT_ARCUS, SAY_EVENT_ACCEPT_ARCUS, SAY_EVENT_START_ARCUS, SAY_EVENT_END_ARCUS, SAY_EVENT_ACCEPT_ARCUS, QUEST_DEADLIEST_TRAP_ALDOR }
}
Definition at line 2865 of file shadowmoon_valley.cpp.
Referenced by npc_commanderAI::FailEvent(), npc_commanderAI::MovementInform(), npc_commanderAI::npc_commanderAI(), npc_commanderAI::SpawnDefenders(), npc_commanderAI::SpawnSpecificDragonmaw(), npc_commanderAI::SummonedCreatureJustDied(), and npc_commanderAI::WinEvent().
DeathwailDescentCoords
const WaveCoords DeathwailDescentCoords[] static
Initial value:
=
{
    {-3245.675f, 298.3688f, 171.9848f},
    {-3251.500f, 301.2324f, 167.3459f},
    {-3258.824f, 302.1381f, 162.9848f},
    {-3267.146f, 297.6195f, 157.9292f},
    {-3266.891f, 283.9230f, 155.4848f},
    {-3261.760f, 278.8767f, 150.5682f},
    {-3255.110f, 278.1188f, 147.8738f},
    {-3248.274f, 278.3419f, 143.6453f},
    {-3245.108f, 287.5689f, 142.7843f},
    {-3248.166f, 289.8274f, 139.0618f},
}
Definition at line 1363 of file shadowmoon_valley.cpp.
Referenced by npc_shadowlord_deathwailAI::DoBeginDescent(), and npc_shadowlord_deathwailAI::MovementInform().
defenderSpawns
SpawnData defenderSpawns[COMMANDER_COUNT][DEFENDER_SPAWN_COUNT] static
Initial value:
=
{
    {
        { -4084.224f,1066.301f,31.44092f,5.427974f },
        { -4077.014f,1070.703f,31.12169f,5.375614f },
        { -4070.818f,1074.806f,31.39684f,5.393067f },
        { -4063.517f,1079.07f, 32.32865f,5.462881f },
        { -4086.24f, 1060.344f,31.0915f, 5.305801f },
        { -4078.464f,1065.285f,31.17392f,5.358161f },
        { -4071.446f,1070.082f,30.65687f,5.358161f },
        { -4064.422f,1074.611f,31.13296f,5.323254f },
        { -4056.84f, 1079.573f,32.50325f,5.5676f   },
        { -4074.189f,1076.387f,31.9625f, 5.358161f }
    },
    {
        { -3094.992f,662.7219f,-12.76196f,2.583087f },
        { -3091.117f,678.4016f,-16.35974f,3.036873f },
        { -3088.423f,684.4808f,-17.56973f,3.141593f },
        { -3093.32f, 673.4081f,-15.20303f,2.879793f },
        { -3085.618f,692.2532f,-17.65626f,3.089233f },
        { -3096.634f,667.7632f,-13.79022f,2.775074f },
        { -3083.601f,687.3881f,-17.03627f,3.089233f },
        { -3086.168f,680.5683f,-15.94252f,2.984513f },
        { -3088.57f, 674.317f, -14.89533f,2.75762f  },
        { -3091.114f,668.1656f,-14.13708f,2.740167f }
    }
}
Definition at line 2799 of file shadowmoon_valley.cpp.
Referenced by npc_commanderAI::SpawnDefenders().
dragonmawRacesScriptInfo
DragonmawRacerScriptInfo dragonmawRacesScriptInfo[RACER_COUNT] static
Initial value:
=
{
    { QUEST_MUCKJAW, SAY_START_MUCKJAW, 0, 0, SPELL_AGGRO_CHECK_MUCKJAW, SPELL_AGGRO_BURST_MUCKJAW, SAY_END_MUCKJAW },
    { QUEST_TROPE, SAY_START_TROPE, SPELL_ATTACK_TROPE, NPC_TARGET_TROPE, SPELL_AGGRO_CHECK_TROPE, SPELL_AGGRO_BURST_TROPE, SAY_END_TROPE },
    { QUEST_CORLOK, SAY_START_CORLOK, SPELL_ATTACK_CORLOK, NPC_TARGET_CORLOK, SPELL_AGGRO_CHECK_CORLOK, SPELL_AGGRO_BURST_CORLOK, SAY_END_CORLOK },
    { QUEST_ICHMAN, SAY_START_ICHMAN, SPELL_ATTACK_ICHMAN, NPC_TARGET_ICHMAN, SPELL_AGGRO_CHECK_ICHMAN, SPELL_AGGRO_BURST_ICHMAN, SAY_END_ICHMAN },
    { QUEST_MULVERICK, SAY_START_MULVERICK, SPELL_ATTACK_MULVERICK, NPC_TARGET_MULVERICK, SPELL_AGGRO_CHECK_MULVERICK, SPELL_AGGRO_BURST_MULVERICK, SAY_END_MULVERICK },
    { QUEST_SKYSHATTER, SAY_START_SKYSHATTER, SPELL_ATTACK_SKYSHATTER, NPC_TARGET_SKYSHATTER, SPELL_AGGRO_CHECK_SKYSHATTER, SPELL_AGGRO_BURST_SKYSHATTER, SAY_END_SKYSHATTER }
}
Definition at line 3247 of file shadowmoon_valley.cpp.
Referenced by npc_dragonmaw_racerAI::AttackPlayer(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), npc_dragonmaw_racerAI::FailRace(), npc_dragonmaw_racerAI::FinishRace(), npc_dragonmaw_racerAI::JustSummoned(), QuestAccept_npc_dragonmaw_racer(), npc_dragonmaw_racerAI::StartAttack(), and npc_dragonmaw_racerAI::StartRace().
dragonmawSpawns
SpawnData dragonmawSpawns[COMMANDER_COUNT][DRAGONMAW_SPAWN_COUNT] static
Initial value:
=
{
    {
        { -4063.342f, 928.9622f, 82.92392f, 0.f},
        { -4101.632f, 942.9062f, 58.77553f, 0.f},
        { -3996.584f, 984.6102f, 39.35212f, 0.f},
        { -4059.524f, 924.002f,  65.44735f, 0.f},
        { -4037.429f, 946.7924f, 83.17754f, 0.f},
        { -4088.804f, 925.6664f, 67.03867f, 0.f},
        { -4037.43f,  934.6457f, 40.03371f, 0.f},
        { -4079.224f, 931.5303f, 76.49546f, 0.f},
        { -4108.912f, 938.1812f, 94.50812f, 0.f},
    },
    {
        { -3277.004f, 696.5723f, 35.61721f, 0.f},
        { -2953.928f, 533.5043f, 92.35249f, 0.f},
        { -3276.309f, 709.3771f, 25.12147f, 0.f},
        { -2992.797f, 545.8665f, 70.36189f, 0.f},
        { -3287.957f, 725.9796f, 51.60571f, 0.f},
        { -3293.602f, 759.0432f, 44.21932f, 0.f},
        { -3286.902f, 732.0245f, 27.88107f, 0.f},
        { -3016.981f, 534.4969f, 21.01351f, 0.f},
        { -3269.654f, 687.1747f, 33.11995f, 0.f},
    }
}
Definition at line 2827 of file shadowmoon_valley.cpp.
Referenced by npc_commanderAI::SpawnSpecificDragonmaw().
EVENT_AREA_RADIUS
const float EVENT_AREA_RADIUS = 65.0
Definition at line 739 of file shadowmoon_valley.cpp.
SpawnLocation
Location SpawnLocation[] static
Initial value:
=
{
    { -4615.8556f, 1342.2532f, 139.9f, 1.612f},
    { -4598.9365f, 1377.3182f, 139.9f, 3.917f},
    { -4598.4697f, 1360.8999f, 139.9f, 2.427f},
    { -4589.3599f, 1369.1061f, 139.9f, 3.165f},
    { -4608.3477f, 1386.0076f, 139.9f, 4.108f},
    { -4633.1889f, 1359.8033f, 139.9f, 0.949f},
    { -4623.5791f, 1351.4574f, 139.9f, 0.971f},
    { -4607.2988f, 1351.6099f, 139.9f, 2.416f},
    { -4633.7764f, 1376.0417f, 139.9f, 5.608f},
    { -4600.2461f, 1369.1240f, 139.9f, 3.056f},
    { -4631.7808f, 1367.9459f, 139.9f, 0.020f},
    { -4600.2461f, 1369.1240f, 139.9f, 3.056f},
    { -4631.7808f, 1367.9459f, 139.9f, 0.020f},
    { -4615.5586f, 1353.0031f, 139.9f, 1.540f},
    { -4616.4736f, 1384.2170f, 139.9f, 4.971f},
    { -4627.1240f, 1378.8752f, 139.9f, 2.544f}
}
Definition at line 766 of file shadowmoon_valley.cpp.
TorlothAnim
TorlothCinematic TorlothAnim[] static
Initial value:
=
{
    {SAY_TORLOTH_DIALOGUE1, TORLOTH, 2000},
    {SAY_ILLIDAN_DIALOGUE, LORD_ILLIDAN, 7000},
    {SAY_TORLOTH_DIALOGUE2, TORLOTH, 3000},
    {0, TORLOTH, 1000},
    {SAY_TORLOTH_DIALOGUE3, TORLOTH, 7000},
    {0, TORLOTH, 0},
}
Definition at line 748 of file shadowmoon_valley.cpp.
Referenced by mob_torlothAI::HandleAnimation().
WaveGroupOneSpawnCoords
const WaveCoords* WaveGroupOneSpawnCoords = WaveSpawnCoords[0] static
Definition at line 1359 of file shadowmoon_valley.cpp.
Referenced by npc_shadowlord_deathwailAI::DoSummonWave().
WaveGroupThreeSpawnCoords
const WaveCoords* WaveGroupThreeSpawnCoords = WaveSpawnCoords[2] static
Definition at line 1361 of file shadowmoon_valley.cpp.
Referenced by npc_shadowlord_deathwailAI::DoSummonWave().
WaveGroupTwoSpawnCoords
const WaveCoords* WaveGroupTwoSpawnCoords = WaveSpawnCoords[1] static
Definition at line 1360 of file shadowmoon_valley.cpp.
Referenced by npc_shadowlord_deathwailAI::DoSummonWave().
WavesInfo
WaveData WavesInfo[] static
Initial value:
=
{
    {9, 0, NPC_ILLIDARI_SOLDIER, 10000, 7000, SAY_ILLIDAN_SUMMON1},
    {2, 9, NPC_ILLIDARI_MIND_BREAKER, 10000, 7000, SAY_ILLIDAN_SUMMON2},
    {4, 11, NPC_ILLIDARI_HIGHLORD, 10000, 7000, SAY_ILLIDAN_SUMMON3},
    {1, 15, NPC_TORLOTH_THE_MAGNIFICENT, 10000, 7000, SAY_ILLIDAN_SUMMON4}
}
Definition at line 796 of file shadowmoon_valley.cpp.
Referenced by npc_lord_illidan_stormrageAI::SummonWave(), and npc_lord_illidan_stormrageAI::UpdateAI().
WaveSpawnCoords
const WaveCoords WaveSpawnCoords[3][3] static
Initial value:
=
{
    {
        {-3220.212f, 257.0669f, 139.0887f},
        {-3214.421f, 253.1379f, 139.1302f},
        {-3218.280f, 248.6299f, 139.1302f},
    },
    {
        {-3256.545f, 260.2362f, 137.1539f},
        {-3253.961f, 257.7454f, 137.1894f},
        {-3258.832f, 256.8369f, 137.1468f},
    },
    {
        {-3219.986f, 259.6718f, 139.0960f},
        {-3214.978f, 256.4007f, 139.1302f},
        {-3217.333f, 252.0130f, 139.1302f},
    }
}
Definition at line 1337 of file shadowmoon_valley.cpp.