CMaNGOS_WoTLK: shade_of_the_horseman.cpp File Reference
shade_of_the_horseman.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Entities/TemporarySpawn.h"
#include "AI/ScriptDevAI/scripts/world/world_map_scripts.h"
#include "World/WorldState.h"
Data Structures
struct npc_orphan_matronAI
struct npc_orphanAI
struct npc_shade_of_the_horsemanAI
struct npc_headless_horseman_fireAI
struct go_large_jack_o_lanternAI
struct HorsemanCreateWaterBucket
struct HorsemanManiacalLaughDelayed
struct HorsemanManiacalLaugh
struct HorsemanStartFirePeriodic
struct HorsemanStartFireTargetTest
struct HorsemanStartFire
struct HorsemanFire
struct HorsemanConflagratePeriodic
struct AllFiresOutTest
struct HorsemanConflagrateTargetTest
struct BucketLands
struct FireExtinguish
struct InvisibleCampfireRemove
struct HumanChildLaughter
struct HumanChildCrying
struct OrcChildLaughter
Macros
#define GOSSIP_ITEM_WHO_IS_HORSEMAN "Who is the Headless Horseman?"
#define GOSSIP_ITEM_SMASH_PUMPKIN "Smash the pumpkin!"
#define GOSSIP_ITEM_FORCE_START_EVENT "DEBUG: Start Shade of the Horseman event"
Enumerations
enum ShadeOfTheHorseman {
SPELL_JACK_O_LANTERNED = 44185 , SPELL_SHADE_DURATION = 44738 , SPELL_MANIACAL_LAUGH_OTHER_DELAY_17 = 44000 , SPELL_MANIACAL_LAUGH_DELAY_17 = 43884 ,
SPELL_MANIACAL_LAUGH = 43885 , SPELL_START_FIRE_PERIODIC = 42140 , SPELL_START_FIRE_TARGET_TEST = 42143 , SPELL_START_FIRE = 42132 ,
SPELL_START_FIRE_TRAIL = 42142 , SPELL_CONFLAGRATE_TARGET_TEST = 42638 , SPELL_CONFLAGRATION_PERIODIC = 42637 , SPELL_CONFLAGRATION = 42380 ,
SPELL_CONFLAGRATION_SOUND = 48149 , SPELL_CONFLAGRATION_SOUND_THROTTLE = 48148 , SPELL_MANIACAL_LAUGHTER_DELAYED_9 = 43886 , SPELL_VICTORY_EVENT = 42682 ,
SPELL_SUMMON_LARGE_JACKOLANTERN = 44255 , SPELL_WISP_ESCAPE_MISSILE = 43034 , SPELL_SHADE_VISUAL = 43904 , SPELL_CLIMAX_GHOST_VISUAL = 42575 ,
SPELL_HAS_WATER_BUCKET = 42336 , SPELL_GIVE_WATER_BUCKET = 42322 , SPELL_GIVE_WATER_BUCKET_NO_MISSILE = 42349 , SPELL_THROW_BUCKET = 42340 ,
SPELL_FIRE_EXTINGUISH = 42348 , SPELL_BUCKET_LANDS = 42339 , SPELL_CREATE_WATER_BUCKET_COSMETIC = 42229 , SPELL_CREATE_WATER_BUCKET_SPLASH = 43244 ,
SPELL_CREATE_WATER_BUCKET = 42144 , SPELL_CREATE_FIRE_NODE = 42118 , SPELL_FIRE_EXTINGUISH_GUARD = 42228 , SPELL_START_FIRE_GUARD = 43715 ,
SPELL_START_FIRE_TARGET_TEST_GUARD = 43711 , SPELL_ALL_FIRES_OUT_TEST = 42151 , SPELL_CREATE_PUMPKIN_TREATS = 42757 , SPELL_CREATE_PUMPKIN_TREATS_AURA = 42774 ,
SPELL_FIRES_OUT_VICTORY_AURA = 42235 , SPELL_VICTORY = 42265 , SPELL_LOOT_JACK_O_LANTERN = 44242 , SPELL_HAS_JACK_O_LANTERN_LOOT = 44245 ,
SPELL_HAS_LOOTED_JACK_O_LANTERN = 44246 , SPELL_SMOKE = 42355 , SPELL_MATRON_QUEST_ACCEPTED = 47768 , SPELL_MATRON_EVENT = 47771 ,
SPELL_QUEST_CREDIT_1 = 42242 , SPELL_QUEST_CREDIT_2 = 47775 , SPELL_ORC_CHILD_LAUGHTER = 43324 , SPELL_HUMAN_CHILD_LAUGHTER = 43321 ,
SPELL_HUMAN_CHILD_CRYING = 43323 , SPELL_FIRE_NONGROWING_ONSPAWN = 42273 , SPELL_FIRE_ONSPAWN = 42080 , SPELL_FIRE_ONSPAWN_SIZE = 42096 ,
SPELL_FIRE_SIZE = 42091 , SPELL_SPREAD_FIRE = 42079 , SPELL_DIM_FIRE = 42154 , SPELL_INVISIBLE_CAMPFIRE_CREATE = 42176 ,
SPELL_INVISIBLE_CAMPFIRE_REMOVE = 42178 , SPELL_FIRE = 42074 , SPELL_FIRE_UPDATE_SIZE = 42112 , SPELL_VISUAL_LARGE_FIRE = 42075 ,
SPELL_CLEAVE = 15496 , SPELL_CONFLAGRATION_2 = 42869 , NPC_SHADE_OF_THE_HORSEMAN = 23543 , NPC_HEADLESS_HORSEMAN_FIRE = 23537 ,
SAY_SHADE_SPAWN = -1015124 , SAY_SHADE_FAILING_1 = -1015125 , SAY_SHADE_FAILING_2 = -1015126 , SAY_SHADE_FLAMES_DIED = -1015127 ,
SAY_SHADE_CONFLAGRATION = -1015128 , EMOTE_SHADE_CONFLAGRATION = -1015129 , SAY_SHADE_DEATH = -1015130 , SAY_SHADE_FAILED = -1015131 ,
SAY_ORPHAN_SHADE_1 = -1015132 , SAY_ORPHAN_SHADE_2 = -1015133 , SAY_ORPHAN_SHADE_3 = -1015134 , SAY_ORPHAN_SHADE_4 = -1015135 ,
SAY_ORPHAN_SHADE_5 = -1015136 , TEXT_ID_MASKED_MATRON_ALL_CLEAR = 11473 , TEXT_ID_MASKED_MATRON_SPAWNED = 11474 , TEXT_ID_MASKED_MATRON_LANDED = 11475 ,
TEXT_ID_MASKED_MATRON_VICTORY = 11476 , TEXT_ID_MATRON_WHO_IS_THE_HORSEMAN = 11590 , TEXT_ID_COSTUMED_MATRON_ALL_CLEAR = 11143 , TEXT_ID_COSTUMED_MATRON_SPAWNED = 11177 ,
TEXT_ID_COSTUMED_MATRON_LANDED = 11145 , TEXT_ID_COSTUMED_MATRON_VICTORY = 11147 , TEXT_ID_ORPHAN_SPAWNED_LANDED = 11356 , TEXT_ID_TOURING_ORPHAN_VICTORY = 11358 ,
TEXT_ID_TOURING_ORPHAN_ALL_CLEAR = 11359 , TEXT_ID_TRAVELING_ORPHAN_ALL_CLEAR = 11477 , TEXT_ID_TRAVELING_ORPHAN_VICTORY = 11479 , TEXT_ID_JACK_O_LANTERN_INITIAL = 12137 ,
TEXT_ID_JACK_O_LANTERN_SMASHED = 12138 , TEXT_ID_JACK_O_LANTERN_TREASURE = 60003 , SOUND_ID_MANIACAL_LAUGH = 11975 , SOUND_ID_ORC_FEMALE_KID_CRY = 11816 ,
SOUND_ID_ORC_MALE_KID_CRY = 11817 , SOUND_ID_HUMAN_MALE_KID_CRY = 11818 , SOUND_ID_HUMAN_FEMALE_KID_CRY = 11819 , SOUND_ID_HUMAN_FEMALE_KID_LAUGH = 11820 ,
SOUND_ID_HUMAN_MALE_KID_LAUGH = 11821 , SOUND_ID_ORC_MALE_KID_LAUGH = 11822 , SOUND_ID_ORC_FEMALE_KID_LAUGH = 11823 , SOUND_ID_CONFLAG = 12573 ,
SOUND_ID_CONFLAG_01 = 12574 , DISPLAY_ID_HEADLESS_HORSEMAN_MOUNT = 22653 , QUEST_LET_THE_FIRES_COME_ALLIANCE = 12135 , QUEST_LET_THE_FIRES_COME_HORDE = 12139
}
enum ShadeOfTheHorsemanPathId {
PATH_ID_GOLDSHIRE_FLY_IN = 0 , PATH_ID_GOLDSHIRE_CIRCLING , PATH_ID_GOLDSHIRE_BOMBING , PATH_ID_GOLDSHIRE_LANDING ,
PATH_ID_GOLDSHIRE_FAILED , PATH_ID_RAZOR_HILL_FLY_IN , PATH_ID_RAZOR_HILL_CIRCLING , PATH_ID_RAZOR_HILL_BOMBING ,
PATH_ID_RAZOR_HILL_LANDING , PATH_ID_RAZOR_HILL_FAILED , PATH_ID_FALCONWING_SQUARE_FLY_IN , PATH_ID_FALCONWING_SQUARE_CIRCLING ,
PATH_ID_FALCONWING_SQUARE_BOMBING , PATH_ID_FALCONWING_SQUARE_LANDING , PATH_ID_FALCONWING_SQUARE_FAILED , PATH_ID_BRILL_FLY_IN ,
PATH_ID_BRILL_CIRCLING , PATH_ID_BRILL_BOMBING , PATH_ID_BRILL_LANDING , PATH_ID_BRILL_FAILED ,
PATH_ID_AZURE_WATCH_FLY_IN , PATH_ID_AZURE_WATCH_CIRCLING , PATH_ID_AZURE_WATCH_BOMBING , PATH_ID_AZURE_WATCH_LANDING ,
PATH_ID_AZURE_WATCH_FAILED , PATH_ID_KHARANOS_FLY_IN , PATH_ID_KHARANOS_CIRCLING , PATH_ID_KHARANOS_BOMBING ,
PATH_ID_KHARANOS_LANDING , PATH_ID_KHARANOS_FAILED
}
Functions
bool GossipHello_npc_orphan_matron (Player *player, Creature *creature)
bool GossipSelect_npc_orphan_matron (Player *player, Creature *creature, uint32, uint32 action)
bool QuestAccept_npc_orphan_matron (Player *, Creature *creature, const Quest *quest)
bool GossipHello_npc_orphan (Player *player, Creature *creature)
bool GossipHello_go_large_jack_o_lantern (Player *player, GameObject *go)
bool GossipSelect_go_large_jack_o_lantern (Player *player, GameObject *go, uint32, uint32 action)
bool GOUse_go_large_jack_o_lantern (Player *, GameObject *)
void AddSC_shade_of_the_horseman ()
Macro Definition Documentation
GOSSIP_ITEM_FORCE_START_EVENT
#define GOSSIP_ITEM_FORCE_START_EVENT "DEBUG: Start Shade of the Horseman event"
Definition at line 205 of file shade_of_the_horseman.cpp.
GOSSIP_ITEM_SMASH_PUMPKIN
#define GOSSIP_ITEM_SMASH_PUMPKIN "Smash the pumpkin!"
Definition at line 204 of file shade_of_the_horseman.cpp.
GOSSIP_ITEM_WHO_IS_HORSEMAN
#define GOSSIP_ITEM_WHO_IS_HORSEMAN "Who is the Headless Horseman?"
Definition at line 203 of file shade_of_the_horseman.cpp.
Enumeration Type Documentation
ShadeOfTheHorseman
enum ShadeOfTheHorseman
Enumerator
SPELL_JACK_O_LANTERNED
SPELL_SHADE_DURATION
SPELL_MANIACAL_LAUGH_OTHER_DELAY_17
SPELL_MANIACAL_LAUGH_DELAY_17
SPELL_MANIACAL_LAUGH
SPELL_START_FIRE_PERIODIC
SPELL_START_FIRE_TARGET_TEST
SPELL_START_FIRE
SPELL_START_FIRE_TRAIL
SPELL_CONFLAGRATE_TARGET_TEST
SPELL_CONFLAGRATION_PERIODIC
SPELL_CONFLAGRATION
SPELL_CONFLAGRATION_SOUND
SPELL_CONFLAGRATION_SOUND_THROTTLE
SPELL_MANIACAL_LAUGHTER_DELAYED_9
SPELL_VICTORY_EVENT
SPELL_SUMMON_LARGE_JACKOLANTERN
SPELL_WISP_ESCAPE_MISSILE
SPELL_SHADE_VISUAL
SPELL_CLIMAX_GHOST_VISUAL
SPELL_HAS_WATER_BUCKET
SPELL_GIVE_WATER_BUCKET
SPELL_GIVE_WATER_BUCKET_NO_MISSILE
SPELL_THROW_BUCKET
SPELL_FIRE_EXTINGUISH
SPELL_BUCKET_LANDS
SPELL_CREATE_WATER_BUCKET_COSMETIC
SPELL_CREATE_WATER_BUCKET_SPLASH
SPELL_CREATE_WATER_BUCKET
SPELL_CREATE_FIRE_NODE
SPELL_FIRE_EXTINGUISH_GUARD
SPELL_START_FIRE_GUARD
SPELL_START_FIRE_TARGET_TEST_GUARD
SPELL_ALL_FIRES_OUT_TEST
SPELL_CREATE_PUMPKIN_TREATS
SPELL_CREATE_PUMPKIN_TREATS_AURA
SPELL_FIRES_OUT_VICTORY_AURA
SPELL_VICTORY
SPELL_LOOT_JACK_O_LANTERN
SPELL_HAS_JACK_O_LANTERN_LOOT
SPELL_HAS_LOOTED_JACK_O_LANTERN
SPELL_SMOKE
SPELL_MATRON_QUEST_ACCEPTED
SPELL_MATRON_EVENT
SPELL_QUEST_CREDIT_1
SPELL_QUEST_CREDIT_2
SPELL_ORC_CHILD_LAUGHTER
SPELL_HUMAN_CHILD_LAUGHTER
SPELL_HUMAN_CHILD_CRYING
SPELL_FIRE_NONGROWING_ONSPAWN
SPELL_FIRE_ONSPAWN
SPELL_FIRE_ONSPAWN_SIZE
SPELL_FIRE_SIZE
SPELL_SPREAD_FIRE
SPELL_DIM_FIRE
SPELL_INVISIBLE_CAMPFIRE_CREATE
SPELL_INVISIBLE_CAMPFIRE_REMOVE
SPELL_FIRE
SPELL_FIRE_UPDATE_SIZE
SPELL_VISUAL_LARGE_FIRE
SPELL_CLEAVE
SPELL_CONFLAGRATION_2
NPC_SHADE_OF_THE_HORSEMAN
NPC_HEADLESS_HORSEMAN_FIRE
SAY_SHADE_SPAWN
SAY_SHADE_FAILING_1
SAY_SHADE_FAILING_2
SAY_SHADE_FLAMES_DIED
SAY_SHADE_CONFLAGRATION
EMOTE_SHADE_CONFLAGRATION
SAY_SHADE_DEATH
SAY_SHADE_FAILED
SAY_ORPHAN_SHADE_1
SAY_ORPHAN_SHADE_2
SAY_ORPHAN_SHADE_3
SAY_ORPHAN_SHADE_4
SAY_ORPHAN_SHADE_5
TEXT_ID_MASKED_MATRON_ALL_CLEAR
TEXT_ID_MASKED_MATRON_SPAWNED
TEXT_ID_MASKED_MATRON_LANDED
TEXT_ID_MASKED_MATRON_VICTORY
TEXT_ID_MATRON_WHO_IS_THE_HORSEMAN
TEXT_ID_COSTUMED_MATRON_ALL_CLEAR
TEXT_ID_COSTUMED_MATRON_SPAWNED
TEXT_ID_COSTUMED_MATRON_LANDED
TEXT_ID_COSTUMED_MATRON_VICTORY
TEXT_ID_ORPHAN_SPAWNED_LANDED
TEXT_ID_TOURING_ORPHAN_VICTORY
TEXT_ID_TOURING_ORPHAN_ALL_CLEAR
TEXT_ID_TRAVELING_ORPHAN_ALL_CLEAR
TEXT_ID_TRAVELING_ORPHAN_VICTORY
TEXT_ID_JACK_O_LANTERN_INITIAL
TEXT_ID_JACK_O_LANTERN_SMASHED
TEXT_ID_JACK_O_LANTERN_TREASURE
SOUND_ID_MANIACAL_LAUGH
SOUND_ID_ORC_FEMALE_KID_CRY
SOUND_ID_ORC_MALE_KID_CRY
SOUND_ID_HUMAN_MALE_KID_CRY
SOUND_ID_HUMAN_FEMALE_KID_CRY
SOUND_ID_HUMAN_FEMALE_KID_LAUGH
SOUND_ID_HUMAN_MALE_KID_LAUGH
SOUND_ID_ORC_MALE_KID_LAUGH
SOUND_ID_ORC_FEMALE_KID_LAUGH
SOUND_ID_CONFLAG
SOUND_ID_CONFLAG_01
DISPLAY_ID_HEADLESS_HORSEMAN_MOUNT
QUEST_LET_THE_FIRES_COME_ALLIANCE
QUEST_LET_THE_FIRES_COME_HORDE
Definition at line 30 of file shade_of_the_horseman.cpp.
ShadeOfTheHorsemanPathId
enum ShadeOfTheHorsemanPathId
Enumerator
PATH_ID_GOLDSHIRE_FLY_IN
PATH_ID_GOLDSHIRE_CIRCLING
PATH_ID_GOLDSHIRE_BOMBING
PATH_ID_GOLDSHIRE_LANDING
PATH_ID_GOLDSHIRE_FAILED
PATH_ID_RAZOR_HILL_FLY_IN
PATH_ID_RAZOR_HILL_CIRCLING
PATH_ID_RAZOR_HILL_BOMBING
PATH_ID_RAZOR_HILL_LANDING
PATH_ID_RAZOR_HILL_FAILED
PATH_ID_FALCONWING_SQUARE_FLY_IN
PATH_ID_FALCONWING_SQUARE_CIRCLING
PATH_ID_FALCONWING_SQUARE_BOMBING
PATH_ID_FALCONWING_SQUARE_LANDING
PATH_ID_FALCONWING_SQUARE_FAILED
PATH_ID_BRILL_FLY_IN
PATH_ID_BRILL_CIRCLING
PATH_ID_BRILL_BOMBING
PATH_ID_BRILL_LANDING
PATH_ID_BRILL_FAILED
PATH_ID_AZURE_WATCH_FLY_IN
PATH_ID_AZURE_WATCH_CIRCLING
PATH_ID_AZURE_WATCH_BOMBING
PATH_ID_AZURE_WATCH_LANDING
PATH_ID_AZURE_WATCH_FAILED
PATH_ID_KHARANOS_FLY_IN
PATH_ID_KHARANOS_CIRCLING
PATH_ID_KHARANOS_BOMBING
PATH_ID_KHARANOS_LANDING
PATH_ID_KHARANOS_FAILED
Definition at line 164 of file shade_of_the_horseman.cpp.
Function Documentation
AddSC_shade_of_the_horseman()
void AddSC_shade_of_the_horseman ()
Definition at line 1065 of file shade_of_the_horseman.cpp.
References Script::GetAI, Script::GetGameObjectAI, GossipHello_go_large_jack_o_lantern(), GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), GossipSelect_go_large_jack_o_lantern(), GossipSelect_npc_orphan_matron(), GOUse_go_large_jack_o_lantern(), Script::Name, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_orphan_matron(), and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_go_large_jack_o_lantern()
bool GossipHello_go_large_jack_o_lantern (Player * player, GameObject * go)
Definition at line 727 of file shade_of_the_horseman.cpp.
References GAMEOBJECT_TYPE_QUESTGIVER, GameObject::GetGoType(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_SMASH_PUMPKIN, GOSSIP_SENDER_MAIN, Unit::HasAura(), Player::PrepareQuestMenu(), Player::SendPreparedQuest(), SPELL_HAS_LOOTED_JACK_O_LANTERN, TEXT_ID_JACK_O_LANTERN_INITIAL, and TEXT_ID_JACK_O_LANTERN_SMASHED.
Referenced by AddSC_shade_of_the_horseman().
GossipHello_npc_orphan()
bool GossipHello_npc_orphan (Player * player, Creature * creature)
Definition at line 366 of file shade_of_the_horseman.cpp.
References InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), ShadeOfTheHorsemanData::GetTypeFromZoneId(), WorldObject::GetZoneId(), NPC_TOURING_ORPHAN, SHADE_PHASE_ALL_CLEAR, SHADE_PHASE_LANDED, SHADE_PHASE_SPAWNED, SHADE_PHASE_VICTORY, TEXT_ID_ORPHAN_SPAWNED_LANDED, TEXT_ID_TOURING_ORPHAN_ALL_CLEAR, TEXT_ID_TOURING_ORPHAN_VICTORY, TEXT_ID_TRAVELING_ORPHAN_ALL_CLEAR, TEXT_ID_TRAVELING_ORPHAN_VICTORY, and TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE.
Referenced by AddSC_shade_of_the_horseman().
GossipHello_npc_orphan_matron()
bool GossipHello_npc_orphan_matron (Player * player, Creature * creature)
Definition at line 264 of file shade_of_the_horseman.cpp.
References InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), ShadeOfTheHorsemanData::GetTypeFromZoneId(), WorldObject::GetZoneId(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ICON_INTERACT_1, GOSSIP_ITEM_FORCE_START_EVENT, GOSSIP_ITEM_WHO_IS_HORSEMAN, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), NPC_COSTUMED_ORPHAN_MATRON, Player::PrepareQuestMenu(), SHADE_PHASE_ALL_CLEAR, SHADE_PHASE_LANDED, SHADE_PHASE_SPAWNED, SHADE_PHASE_VICTORY, TEXT_ID_COSTUMED_MATRON_ALL_CLEAR, TEXT_ID_COSTUMED_MATRON_LANDED, TEXT_ID_COSTUMED_MATRON_SPAWNED, TEXT_ID_COSTUMED_MATRON_VICTORY, TEXT_ID_MASKED_MATRON_ALL_CLEAR, TEXT_ID_MASKED_MATRON_LANDED, TEXT_ID_MASKED_MATRON_SPAWNED, TEXT_ID_MASKED_MATRON_VICTORY, and TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE.
Referenced by AddSC_shade_of_the_horseman().
GossipSelect_go_large_jack_o_lantern()
bool GossipSelect_go_large_jack_o_lantern (Player * player, GameObject * go, uint32 , uint32 action)
Definition at line 746 of file shade_of_the_horseman.cpp.
References Unit::CastSpell(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, Unit::HasAura(), Unit::RemoveAurasDueToSpell(), SPELL_HAS_LOOTED_JACK_O_LANTERN, SPELL_LOOT_JACK_O_LANTERN, SPELL_VICTORY, TEXT_ID_JACK_O_LANTERN_TREASURE, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_shade_of_the_horseman().
GossipSelect_npc_orphan_matron()
bool GossipSelect_npc_orphan_matron (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 293 of file shade_of_the_horseman.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, UnitAI::SendAIEvent(), and TEXT_ID_MATRON_WHO_IS_THE_HORSEMAN.
Referenced by AddSC_shade_of_the_horseman().
GOUse_go_large_jack_o_lantern()
bool GOUse_go_large_jack_o_lantern (Player * , GameObject *)
Definition at line 760 of file shade_of_the_horseman.cpp.
Referenced by AddSC_shade_of_the_horseman().
QuestAccept_npc_orphan_matron()
bool QuestAccept_npc_orphan_matron (Player * , Creature * creature, const Quest * quest)
Definition at line 305 of file shade_of_the_horseman.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Quest::GetQuestId(), QUEST_LET_THE_FIRES_COME_ALLIANCE, QUEST_LET_THE_FIRES_COME_HORDE, and UnitAI::SendAIEvent().
Referenced by AddSC_shade_of_the_horseman().