CMaNGOS_WoTLK: shadowfang_keep.cpp File Reference
shadowfang_keep.cpp File Reference
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shadowfang_keep.h"
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
Data Structures
struct npc_shadowfang_prisonerAI
struct mob_arugal_voidwalkerAI
struct SpawnPoint
struct boss_arugalAI
struct npc_deathstalker_vincentAI
struct ForsakenSkill
Enumerations
enum {
SAY_FREE_AS = -1033000 , SAY_OPEN_DOOR_AS = -1033001 , SAY_POST_DOOR_AS = -1033002 , EMOTE_VANISH_AS = -1033014 ,
SAY_FREE_AD = -1033003 , SAY_OPEN_DOOR_AD = -1033004 , SAY_POST1_DOOR_AD = -1033005 , SAY_POST2_DOOR_AD = -1033006 ,
EMOTE_UNLOCK_DOOR_AD = -1033015 , SPELL_UNLOCK = 6421 , GOSSIP_ITEM_DOOR = -3033000
}
enum { NPC_VOIDWALKER = 4627 , SPELL_DARK_OFFERING = 7154 , MAX_VOID_WALKERS = 4 }
enum ArugalVoidWalker { VOIDWALKER_DARKOFFERING , VOIDWALKER_CHECK_GROUP , VOIDWALKER_ACTIONS_MAX }
enum {
SPELL_VOID_BOLT = 7588 , SPELL_SHADOW_PORT_UPPER_LEDGE = 7587 , SPELL_SHADOW_PORT_SPAWN_LEDGE = 7586 , SPELL_SHADOW_PORT_STAIRS = 7136 ,
SPELL_ARUGALS_CURSE = 7621 , SPELL_THUNDERSHOCK = 7803
}
enum ArugalPosition { POSITION_SPAWN_LEDGE = 0 , POSITION_UPPER_LEDGE = 1 , POSITION_STAIRS = 2 }
enum ArugalActions {
ARUGAL_TELEPORT , ARUGAL_CURSE , ARUGAL_VOID_BOLT , ARUGAL_THUNDERSHOCK ,
ARUGAL_ACTIONS_MAX
}
enum { SAY_VINCENT_DIE = -1033016 , FACTION_FRIENDLY = 35 }
Functions
bool GossipHello_npc_shadowfang_prisoner (Player *player, Creature *creature)
bool GossipSelect_npc_shadowfang_prisoner (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_shadowfang_keep ()
Variables
static const Waypoint voidwalkerHome = { -146.06f, 2172.84f, 127.953f}
static const SpawnPoint VWSpawns []
const float HEIGHT_FENRUS_ROOM = 140.0f
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_FREE_AS
SAY_OPEN_DOOR_AS
SAY_POST_DOOR_AS
EMOTE_VANISH_AS
SAY_FREE_AD
SAY_OPEN_DOOR_AD
SAY_POST1_DOOR_AD
SAY_POST2_DOOR_AD
EMOTE_UNLOCK_DOOR_AD
SPELL_UNLOCK
GOSSIP_ITEM_DOOR
Definition at line 44 of file shadowfang_keep.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_VOIDWALKER
SPELL_DARK_OFFERING
MAX_VOID_WALKERS
Definition at line 195 of file shadowfang_keep.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_VOID_BOLT
SPELL_SHADOW_PORT_UPPER_LEDGE
SPELL_SHADOW_PORT_SPAWN_LEDGE
SPELL_SHADOW_PORT_STAIRS
SPELL_ARUGALS_CURSE
SPELL_THUNDERSHOCK
Definition at line 343 of file shadowfang_keep.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_VINCENT_DIE
FACTION_FRIENDLY
Definition at line 563 of file shadowfang_keep.cpp.
ArugalActions
enum ArugalActions
Enumerator
ARUGAL_TELEPORT
ARUGAL_CURSE
ARUGAL_VOID_BOLT
ARUGAL_THUNDERSHOCK
ARUGAL_ACTIONS_MAX
Definition at line 379 of file shadowfang_keep.cpp.
ArugalPosition
enum ArugalPosition
Enumerator
POSITION_SPAWN_LEDGE
POSITION_UPPER_LEDGE
POSITION_STAIRS
Definition at line 353 of file shadowfang_keep.cpp.
ArugalVoidWalker
enum ArugalVoidWalker
Enumerator
VOIDWALKER_DARKOFFERING
VOIDWALKER_CHECK_GROUP
VOIDWALKER_ACTIONS_MAX
Definition at line 202 of file shadowfang_keep.cpp.
Function Documentation
AddSC_shadowfang_keep()
void AddSC_shadowfang_keep ()
Definition at line 639 of file shadowfang_keep.cpp.
References Script::GetAI, GossipHello_npc_shadowfang_prisoner(), GossipSelect_npc_shadowfang_prisoner(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_shadowfang_prisoner()
bool GossipHello_npc_shadowfang_prisoner (Player * player, Creature * creature)
Definition at line 160 of file shadowfang_keep.cpp.
References DONE, InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ADA, GOSSIP_ASH, GOSSIP_ICON_CHAT, GOSSIP_ITEM_DOOR, GOSSIP_SENDER_MAIN, NPC_ADA, and TYPE_FREE_NPC.
Referenced by AddSC_shadowfang_keep().
GossipSelect_npc_shadowfang_prisoner()
bool GossipSelect_npc_shadowfang_prisoner (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 172 of file shadowfang_keep.cpp.
References Creature::AI(), DoScriptText(), Object::GetEntry(), GOSSIP_ACTION_INFO_DEF, NPC_ASH, SAY_FREE_AD, and SAY_FREE_AS.
Referenced by AddSC_shadowfang_keep().
Variable Documentation
HEIGHT_FENRUS_ROOM
const float HEIGHT_FENRUS_ROOM = 140.0f
Definition at line 377 of file shadowfang_keep.cpp.
Referenced by boss_arugalAI::boss_arugalAI().
voidwalkerHome
const Waypoint voidwalkerHome = { -146.06f, 2172.84f, 127.953f} static
Definition at line 210 of file shadowfang_keep.cpp.
Referenced by boss_arugalAI::ReceiveAIEvent().
VWSpawns
const SpawnPoint VWSpawns[] static
Initial value:
=
{
    { -155.352f, 2172.780f, 128.448f, 4.679f},
    { -147.059f, 2163.193f, 128.696f, 0.128f},
    { -148.869f, 2180.859f, 128.448f, 1.814f},
    { -140.203f, 2175.263f, 128.448f, 0.373f}
}
Definition at line 366 of file shadowfang_keep.cpp.
Referenced by boss_arugalAI::ReceiveAIEvent().