CMaNGOS_WoTLK: shartuul_transporter.cpp File Reference
shartuul_transporter.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/outland/world_outland.h"
#include "Spells/Scripts/SpellScript.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
Data Structures
struct npc_doomguard_punisherAI
struct npc_shivan_assassinAI
struct npc_eye_of_shartuulAI
struct npc_dreadmawAI
struct npc_shartuulAI
struct PossessionTransfer
struct TouchOfMadness
struct MadnessRift
struct EredarPreGateBeam
struct ThrowAxe
struct SuperJump
struct CleansingFlame
struct RampagingCharge
struct CheckCrystalFocusSpell
struct AbsorbLife
struct ShartuulDiveBomb
struct FlyingAttackAura
struct ShartuulFireballBarrage
struct ChaosStrike
struct ChaosStrikeDamage
struct ChaosStrikeTransform
struct DeathBlast
struct Iceblast
struct ShivanShapeshiftForm
struct BuildPortableFelCannon
struct StunField
struct StunRopeAttunement
Enumerations
enum Possession { SPELL_POSSESSION_TRANSFER_P1 = 40503 , SPELL_POSSESSION_TRANSFER_P2 = 41962 , SPELL_CHARM_P2 = 40382 , SPELL_CHARM_P3 = 40523 }
enum { SPELL_FEL_FLAMES = 40561 }
enum PunisherActions { PUNISHER_POSSESSION_TRANSFER , PUNISHER_FEL_FLAMES , PUNISHER_ACTION_MAX , PUNISHER_ATTACK_DELAY }
enum ShivanActions { SHIVAN_POSSESSION_TRANSFER , SHIVAN_ACTION_MAX , SHIVAN_ATTACK_DELAY , SHIVAN_OOC_ANIM }
enum { SPELL_FEL_FIREBALL = 40633 , SPELL_DISRUPTION_RAY = 41550 , SPELL_DARK_GLARE = 41936 , SPELL_TONGUE_LASH = 42002 }
enum EyeActions {
EYE_DARK_GLARE , EYE_DISRUPTION_RAY , EYE_TONGUE_LASH , EYE_FEL_FIREBALL ,
EYE_ACTION_MAX , EYE_ATTACK_DELAY
}
enum { SPELL_RAMPAGING_CHARGE = 41939 , SPELL_GROWTH = 41953 , SPELL_LACERATING_BITE = 41940 }
enum DreadmawActions { DREADMAW_RAMPAGING_CHARGE , DREADMAW_GROWTH , DREADMAW_ACTION_MAX , DREADMAW_ATTACK_DELAY }
enum {
SPELL_SHADOW_BOLT = 41069 , SPELL_SHADOW_RESONANCE = 41961 , SPELL_MAGNETIC_PULL = 41959 , SPELL_TELEPORT = 41993 ,
SPELL_IMMOLATE = 41958 , SPELL_INCINERATE = 41960
}
enum ShartuulActions {
SHARTUUL_TELEPORT , SHARTUUL_INCINERATE , SHARTUUL_IMMOLATE , SHARTUUL_SHADOW_RESONANCE ,
SHARTUUL_SHADOW_BOLT , SHARTUUL_ACTION_MAX , SHARTUUL_HANDLE_FIGHT_START
}
enum {
ITEM_CHARGED_CRYSTAL_FOCUS = 32578 , SPELL_CRYSTAL_CHARGE_VACUUM = 40660 , SPELL_CHAOS_STRIKE = 40741 , SPELL_CHAOS_STRIKE_TRIGGER = 41964 ,
SPELL_CHAOS_FORM = 42006 , SPELL_FLAME_BUFFET = 41596 , SPELL_CORRUPTED_LIGHT = 41965 , SPELL_ABSORB_LIFE = 40501 ,
SPELL_FLYING_ATTACK_AURA = 40557 , SPELL_KNOCKBACK_IMMUNE_FLY = 40795 , SPELL_BOMBING_RUN = 41076
}
enum { SPELL_SIPHON_LIFE = 41597 , SPELL_DARK_MENDING = 41938 }
enum { SPELL_ASPECT_OF_THE_FLAME = 41593 , SPELL_ASPECT_OF_THE_ICE = 41594 , SPELL_ASPECT_OF_THE_SHADOW = 41595 }
enum {
SPELL_SUMMON_STUN_ZONE_GRAPHIC_NS = 40776 , SPELL_SUMMON_STUN_ZONE_GRAPHIC_WE = 40783 , SPELL_STUN_ROPE_ATTUNEMENT = 40777 , SPELL_STUN_ROPE = 40778 ,
SPELL_STUN_ZONE = 40775
}
Functions
bool ProcessEventId_CharmDegrader (uint32, Object *pSource, Object *, bool)
bool ProcessEventId_CharmShivan (uint32, Object *pSource, Object *, bool)
void AddSC_shartuul_transporter ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_FEL_FLAMES
Definition at line 31 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FEL_FIREBALL
SPELL_DISRUPTION_RAY
SPELL_DARK_GLARE
SPELL_TONGUE_LASH
Definition at line 202 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_RAMPAGING_CHARGE
SPELL_GROWTH
SPELL_LACERATING_BITE
Definition at line 303 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SHADOW_BOLT
SPELL_SHADOW_RESONANCE
SPELL_MAGNETIC_PULL
SPELL_TELEPORT
SPELL_IMMOLATE
SPELL_INCINERATE
Definition at line 394 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
ITEM_CHARGED_CRYSTAL_FOCUS
SPELL_CRYSTAL_CHARGE_VACUUM
SPELL_CHAOS_STRIKE
SPELL_CHAOS_STRIKE_TRIGGER
SPELL_CHAOS_FORM
SPELL_FLAME_BUFFET
SPELL_CORRUPTED_LIGHT
SPELL_ABSORB_LIFE
SPELL_FLYING_ATTACK_AURA
SPELL_KNOCKBACK_IMMUNE_FLY
SPELL_BOMBING_RUN
Definition at line 668 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SIPHON_LIFE
SPELL_DARK_MENDING
Definition at line 758 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_ASPECT_OF_THE_FLAME
SPELL_ASPECT_OF_THE_ICE
SPELL_ASPECT_OF_THE_SHADOW
Definition at line 829 of file shartuul_transporter.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_STUN_ZONE_GRAPHIC_NS
SPELL_SUMMON_STUN_ZONE_GRAPHIC_WE
SPELL_STUN_ROPE_ATTUNEMENT
SPELL_STUN_ROPE
SPELL_STUN_ZONE
Definition at line 879 of file shartuul_transporter.cpp.
DreadmawActions
enum DreadmawActions
Enumerator
DREADMAW_RAMPAGING_CHARGE
DREADMAW_GROWTH
DREADMAW_ACTION_MAX
DREADMAW_ATTACK_DELAY
Definition at line 310 of file shartuul_transporter.cpp.
EyeActions
enum EyeActions
Enumerator
EYE_DARK_GLARE
EYE_DISRUPTION_RAY
EYE_TONGUE_LASH
EYE_FEL_FIREBALL
EYE_ACTION_MAX
EYE_ATTACK_DELAY
Definition at line 210 of file shartuul_transporter.cpp.
Possession
enum Possession
Enumerator
SPELL_POSSESSION_TRANSFER_P1
SPELL_POSSESSION_TRANSFER_P2
SPELL_CHARM_P2
SPELL_CHARM_P3
Definition at line 22 of file shartuul_transporter.cpp.
PunisherActions
enum PunisherActions
Enumerator
PUNISHER_POSSESSION_TRANSFER
PUNISHER_FEL_FLAMES
PUNISHER_ACTION_MAX
PUNISHER_ATTACK_DELAY
Definition at line 36 of file shartuul_transporter.cpp.
ShartuulActions
enum ShartuulActions
Enumerator
SHARTUUL_TELEPORT
SHARTUUL_INCINERATE
SHARTUUL_IMMOLATE
SHARTUUL_SHADOW_RESONANCE
SHARTUUL_SHADOW_BOLT
SHARTUUL_ACTION_MAX
SHARTUUL_HANDLE_FIGHT_START
Definition at line 404 of file shartuul_transporter.cpp.
ShivanActions
enum ShivanActions
Enumerator
SHIVAN_POSSESSION_TRANSFER
SHIVAN_ACTION_MAX
SHIVAN_ATTACK_DELAY
SHIVAN_OOC_ANIM
Definition at line 113 of file shartuul_transporter.cpp.
Function Documentation
AddSC_shartuul_transporter()
void AddSC_shartuul_transporter ()
Definition at line 924 of file shartuul_transporter.cpp.
References Script::GetAI, Script::Name, Script::pProcessEventId, ProcessEventId_CharmDegrader(), ProcessEventId_CharmShivan(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventId_CharmDegrader()
bool ProcessEventId_CharmDegrader (uint32 , Object * pSource, Object * , bool)
Definition at line 564 of file shartuul_transporter.cpp.
References DoScriptText(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Object::IsPlayer(), NPC_OVERSEER_SHARTUUL, and SAY_SECOND_DEMON.
Referenced by AddSC_shartuul_transporter().
ProcessEventId_CharmShivan()
bool ProcessEventId_CharmShivan (uint32 , Object * pSource, Object * , bool)
Definition at line 575 of file shartuul_transporter.cpp.
References DoScriptText(), WorldObject::GetInstanceData(), ScriptedInstance::GetSingleCreatureFromStorage(), Object::IsPlayer(), NPC_OVERSEER_SHARTUUL, and SAY_THIRD_DEMON.
Referenced by AddSC_shartuul_transporter().