CMaNGOS_WoTLK: SharedDefines.h File Reference
SharedDefines.h File Reference
#include "Platform/Define.h"
Macros
#define MAX_GENDER 3
#define MAX_RACES 12
#define RACEMASK_ALL_PLAYABLE
#define RACEMASK_ALLIANCE
#define RACEMASK_HORDE
#define MAX_CLASSES 12
#define CLASSMASK_ALL_PLAYABLE
#define CLASSMASK_ALL_CREATURES ((1<<(CLASS_WARRIOR-1)) | (1<<(CLASS_PALADIN-1)) | (1<<(CLASS_ROGUE-1)) | (1<<(CLASS_MAGE-1)))
#define MAX_CREATURE_CLASS 4
#define CLASSMASK_WAND_USERS ((1<<(CLASS_PRIEST-1))|(1<<(CLASS_MAGE-1))|(1<<(CLASS_WARLOCK-1)))
#define CLASSMASK_RELIC_USERS ((1<<(CLASS_PALADIN-1))|(1<<(CLASS_SHAMAN-1))|(1<<(CLASS_DRUID-1))|(1<<(CLASS_DEATH_KNIGHT-1)))
#define PLAYER_MAX_BATTLEGROUND_QUEUES 2
#define MIN_REPUTATION_RANK (REP_HATED)
#define MAX_REPUTATION_RANK 8
#define MAX_SPILLOVER_FACTIONS 4
#define MAX_STATS 5
#define MAX_POWERS 7
#define MAX_SPELL_SCHOOL 7
#define MAX_ITEM_QUALITY 8
#define MAX_TALENT_SPEC_COUNT 2
#define MAX_GLYPH_SLOT_INDEX 6
#define MAX_SHEATHETYPE 8
#define LANGUAGES_COUNT 19
#define PVP_TEAM_COUNT 2
#define FIRST_MECHANIC 1
#define MAX_MECHANIC 32
#define IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK
#define IMMUNE_TO_INCAPACITATE_MASK
#define IMMUNE_TO_ROOT_AND_SNARE_MASK
#define IMMUNE_TO_ROOT_AND_STUN_MASK
#define IMMUNE_TO_SILENCE_AND_STUN_AND_FEAR_MASK
#define IMMUNE_TO_INTERRUPT_AND_SILENCE_MASK
#define MECHANIC_NOT_REMOVED_BY_SHAPESHIFT
#define DISPEL_ALL_MASK ((1<<DISPEL_MAGIC) | (1<<DISPEL_CURSE) | (1<<DISPEL_DISEASE) | (1<<DISPEL_POISON))
#define MAX_SPELL_IMMUNITY 6
#define MAX_ATTACK 3
#define MAX_GAMEOBJECT_TYPE 36
#define MAX_TRAINER_TYPE 4
#define MAX_SKILL_TYPE 789
#define SPELL_ID_GENERIC_LEARN 483
#define SPELL_ID_GENERIC_LEARN_PET 55884
#define SPELL_ID_PASSIVE_BATTLE_STANCE 2457
#define SPELL_ID_PASSIVE_RESURRECTION_SICKNESS 15007
#define SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_5s 6119
#define SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_0s 6123
#define SPELL_ID_AUTOSHOT 75
#define SPELL_ID_SHADOWMELD 58984
#define SPELL_ID_BATTLEGROUND_DESERTER 26013
#define MAX_WEATHER_TYPE 4
#define MAX_CHAT_MSG_TYPE 0x34
#define MAX_PET_DIET 9
#define CHAIN_SPELL_JUMP_RADIUS 10
#define GUILD_BANK_MAX_TABS 6
#define GUILD_BANK_MAX_SLOTS 98
#define GUILD_BANK_MAX_LOGS 25
#define GUILD_BANK_MONEY_LOGS_TAB 100
#define GUILD_EVENTLOG_MAX_RECORDS 100
#define GUILD_RANKS_MIN_COUNT 5
#define GUILD_RANKS_MAX_COUNT 10
#define MAX_BATTLEGROUND_TYPE_ID 33
#define TOTEM_SLOT_NONE 255
#define MAX_TOTEM_SLOT 4
#define EXPECTED_MANGOSD_CLIENT_BUILD {12340, 0}
#define MAX_EXPANSION 2
#define DEFAULT_MAX_CREATURE_LEVEL 85
#define SPELL_RIDE_VEHICLE_HARDCODED 46598
#define SPELL_VEHICLE_PARACHUTE 45472
Enumerations
enum Gender { GENDER_MALE = 0 , GENDER_FEMALE = 1 , GENDER_NONE = 2 }
enum Races {
RACE_HUMAN = 1 , RACE_ORC = 2 , RACE_DWARF = 3 , RACE_NIGHTELF = 4 ,
RACE_UNDEAD = 5 , RACE_TAUREN = 6 , RACE_GNOME = 7 , RACE_TROLL = 8 ,
RACE_GOBLIN = 9 , RACE_BLOODELF = 10 , RACE_DRAENEI = 11 , RACE_FEL_ORC = 12 ,
RACE_NAGA = 13 , RACE_BROKEN = 14 , RACE_SKELETON = 15 , RACE_VRYKUL = 16 ,
RACE_TUSKARR = 17 , RACE_FOREST_TROLL = 18 , RACE_TAUNKA = 19 , RACE_NORTHREND_SKELETON = 20 ,
RACE_ICE_TROLL = 21
}
enum Classes {
CLASS_WARRIOR = 1 , CLASS_PALADIN = 2 , CLASS_HUNTER = 3 , CLASS_ROGUE = 4 ,
CLASS_PRIEST = 5 , CLASS_DEATH_KNIGHT = 6 , CLASS_SHAMAN = 7 , CLASS_MAGE = 8 ,
CLASS_WARLOCK = 9 , CLASS_DRUID = 11
}
enum ReputationRank {
REP_HATED = 0 , REP_HOSTILE = 1 , REP_UNFRIENDLY = 2 , REP_NEUTRAL = 3 ,
REP_FRIENDLY = 4 , REP_HONORED = 5 , REP_REVERED = 6 , REP_EXALTED = 7
}
enum MoneyConstants { COPPER = 1 , SILVER = COPPER * 100 , GOLD = SILVER * 100 }
enum Stats {
STAT_STRENGTH = 0 , STAT_AGILITY = 1 , STAT_STAMINA = 2 , STAT_INTELLECT = 3 ,
STAT_SPIRIT = 4
}
enum Powers : uint32 {
POWER_MANA = 0 , POWER_RAGE = 1 , POWER_FOCUS = 2 , POWER_ENERGY = 3 ,
POWER_HAPPINESS = 4 , POWER_RUNE = 5 , POWER_RUNIC_POWER = 6 , POWER_HEALTH = 0xFFFFFFFE
}
enum SpellSchools {
SPELL_SCHOOL_NORMAL = 0 , SPELL_SCHOOL_HOLY = 1 , SPELL_SCHOOL_FIRE = 2 , SPELL_SCHOOL_NATURE = 3 ,
SPELL_SCHOOL_FROST = 4 , SPELL_SCHOOL_SHADOW = 5 , SPELL_SCHOOL_ARCANE = 6
}
The different spell schools that are available, used in both damage calculation and spell casting to decide what should be affected, the SPELL_SCHOOL_NORMAL is the armor, others should be self explanatory.
enum SpellSchoolMask : uint32 {
SPELL_SCHOOL_MASK_NONE = 0x00 , SPELL_SCHOOL_MASK_NORMAL = (1 << SPELL_SCHOOL_NORMAL) , SPELL_SCHOOL_MASK_HOLY = (1 << SPELL_SCHOOL_HOLY) , SPELL_SCHOOL_MASK_FIRE = (1 << SPELL_SCHOOL_FIRE) ,
SPELL_SCHOOL_MASK_NATURE = (1 << SPELL_SCHOOL_NATURE) , SPELL_SCHOOL_MASK_FROST = (1 << SPELL_SCHOOL_FROST) , SPELL_SCHOOL_MASK_SHADOW = (1 << SPELL_SCHOOL_SHADOW) , SPELL_SCHOOL_MASK_ARCANE = (1 << SPELL_SCHOOL_ARCANE) ,
SPELL_SCHOOL_MASK_SPELL , SPELL_SCHOOL_MASK_MAGIC = (SPELL_SCHOOL_MASK_HOLY | SPELL_SCHOOL_MASK_SPELL) , SPELL_SCHOOL_MASK_ALL = (SPELL_SCHOOL_MASK_NORMAL | SPELL_SCHOOL_MASK_MAGIC) , SPELL_SCHOOL_MULTI_ASTRAL = (SPELL_SCHOOL_MASK_ARCANE | SPELL_SCHOOL_MASK_NATURE) ,
SPELL_SCHOOL_MULTI_CHAOS = (SPELL_SCHOOL_MASK_ALL) , SPELL_SCHOOL_MULTI_DIVINE = (SPELL_SCHOOL_MASK_ARCANE | SPELL_SCHOOL_MASK_HOLY) , SPELL_SCHOOL_MULTI_ELEMENTAL = (SPELL_SCHOOL_MASK_FIRE | SPELL_SCHOOL_MASK_FROST | SPELL_SCHOOL_MASK_NATURE) , SPELL_SCHOOL_MULTI_FIRESTORM = (SPELL_SCHOOL_MASK_FIRE | SPELL_SCHOOL_MASK_NATURE) ,
SPELL_SCHOOL_MULTI_FROSTFIRE = (SPELL_SCHOOL_MASK_FROST | SPELL_SCHOOL_MASK_FIRE) , SPELL_SCHOOL_MULTI_PLAGUE = (SPELL_SCHOOL_MASK_NATURE | SPELL_SCHOOL_MASK_SHADOW) , SPELL_SCHOOL_MULTI_RADIANT = (SPELL_SCHOOL_MASK_FIRE | SPELL_SCHOOL_MASK_HOLY) , SPELL_SCHOOL_MULTI_SHADOWFLAME = (SPELL_SCHOOL_MASK_SHADOW | SPELL_SCHOOL_MASK_FIRE) ,
SPELL_SCHOOL_MULTI_SHADOWFROST = (SPELL_SCHOOL_MASK_SHADOW | SPELL_SCHOOL_MASK_FROST) , SPELL_SCHOOL_MULTI_SHADOWSTRIKE = (SPELL_SCHOOL_MASK_SHADOW | SPELL_SCHOOL_MASK_NORMAL) , SPELL_SCHOOL_MULTI_SPELLSHADOW = (SPELL_SCHOOL_MASK_ARCANE | SPELL_SCHOOL_MASK_SHADOW) , SPELL_SCHOOL_MULTI_TWILIGHT = (SPELL_SCHOOL_MASK_HOLY | SPELL_SCHOOL_MASK_SHADOW) ,
SPELL_SCHOOL_MULTI_CHROMATIC = (SPELL_SCHOOL_MASK_SPELL) , SPELL_SCHOOL_MULTI_FROSTSTORM = (SPELL_SCHOOL_MASK_FROST | SPELL_SCHOOL_MASK_NATURE) , SPELL_SCHOOL_MULTI_HOLYFROST = (SPELL_SCHOOL_MASK_HOLY | SPELL_SCHOOL_MASK_FROST) , SPELL_SCHOOL_MULTI_HOLYSTORM = (SPELL_SCHOOL_MASK_HOLY | SPELL_SCHOOL_MASK_NATURE) ,
SPELL_SCHOOL_MULTI_SPELLFIRE = (SPELL_SCHOOL_MASK_ARCANE | SPELL_SCHOOL_MASK_FIRE) , SPELL_SCHOOL_MULTI_SPELLFROST = (SPELL_SCHOOL_MASK_ARCANE | SPELL_SCHOOL_MASK_FROST)
}
A bitmask of the available SpellSchools.
enum ItemQualities {
ITEM_QUALITY_POOR = 0 , ITEM_QUALITY_NORMAL = 1 , ITEM_QUALITY_UNCOMMON = 2 , ITEM_QUALITY_RARE = 3 ,
ITEM_QUALITY_EPIC = 4 , ITEM_QUALITY_LEGENDARY = 5 , ITEM_QUALITY_ARTIFACT = 6 , ITEM_QUALITY_HEIRLOOM = 7
}
enum SheathTypes {
SHEATHETYPE_NONE = 0 , SHEATHETYPE_MAINHAND = 1 , SHEATHETYPE_OFFHAND = 2 , SHEATHETYPE_LARGEWEAPONLEFT = 3 ,
SHEATHETYPE_LARGEWEAPONRIGHT = 4 , SHEATHETYPE_HIPWEAPONLEFT = 5 , SHEATHETYPE_HIPWEAPONRIGHT = 6 , SHEATHETYPE_SHIELD = 7
}
enum CharacterSlot {
SLOT_HEAD = 0 , SLOT_NECK = 1 , SLOT_SHOULDERS = 2 , SLOT_SHIRT = 3 ,
SLOT_CHEST = 4 , SLOT_WAIST = 5 , SLOT_LEGS = 6 , SLOT_FEET = 7 ,
SLOT_WRISTS = 8 , SLOT_HANDS = 9 , SLOT_FINGER1 = 10 , SLOT_FINGER2 = 11 ,
SLOT_TRINKET1 = 12 , SLOT_TRINKET2 = 13 , SLOT_BACK = 14 , SLOT_MAIN_HAND = 15 ,
SLOT_OFF_HAND = 16 , SLOT_RANGED = 17 , SLOT_TABARD = 18 , SLOT_EMPTY = 19
}
enum Language {
LANG_UNIVERSAL = 0 , LANG_ORCISH = 1 , LANG_DARNASSIAN = 2 , LANG_TAURAHE = 3 ,
LANG_DWARVISH = 6 , LANG_COMMON = 7 , LANG_DEMONIC = 8 , LANG_TITAN = 9 ,
LANG_THALASSIAN = 10 , LANG_DRACONIC = 11 , LANG_KALIMAG = 12 , LANG_GNOMISH = 13 ,
LANG_TROLL = 14 , LANG_GUTTERSPEAK = 33 , LANG_DRAENEI = 35 , LANG_ZOMBIE = 36 ,
LANG_GNOMISH_BINARY = 37 , LANG_GOBLIN_BINARY = 38 , LANG_ADDON = 0xFFFFFFFF
}
enum Team {
TEAM_NONE = 0 , TEAM_BOTH_ALLOWED = 0 , TEAM_INVALID = 1 , HORDE = 67 ,
ALLIANCE = 469
}
enum BattleGroundWinner { WINNER_HORDE = 0 , WINNER_ALLIANCE = 1 , WINNER_NONE = 2 }
enum PvpTeamIndex { TEAM_INDEX_ALLIANCE = 0 , TEAM_INDEX_HORDE = 1 , TEAM_INDEX_NEUTRAL = 2 }
enum Mechanics {
MECHANIC_NONE = 0 , MECHANIC_CHARM = 1 , MECHANIC_DISORIENTED = 2 , MECHANIC_DISARM = 3 ,
MECHANIC_DISTRACT = 4 , MECHANIC_FEAR = 5 , MECHANIC_GRIP = 6 , MECHANIC_ROOT = 7 ,
MECHANIC_PACIFY = 8 , MECHANIC_SILENCE = 9 , MECHANIC_SLEEP = 10 , MECHANIC_SNARE = 11 ,
MECHANIC_STUN = 12 , MECHANIC_FREEZE = 13 , MECHANIC_KNOCKOUT = 14 , MECHANIC_BLEED = 15 ,
MECHANIC_BANDAGE = 16 , MECHANIC_POLYMORPH = 17 , MECHANIC_BANISH = 18 , MECHANIC_SHIELD = 19 ,
MECHANIC_SHACKLE = 20 , MECHANIC_MOUNT = 21 , MECHANIC_INFECTED = 22 , MECHANIC_TURN = 23 ,
MECHANIC_HORROR = 24 , MECHANIC_INVULNERABILITY = 25 , MECHANIC_INTERRUPT = 26 , MECHANIC_DAZE = 27 ,
MECHANIC_DISCOVERY = 28 , MECHANIC_IMMUNE_SHIELD = 29 , MECHANIC_SAPPED = 30 , MECHANIC_ENRAGED = 31
}
enum DispelType {
DISPEL_NONE = 0 , DISPEL_MAGIC = 1 , DISPEL_CURSE = 2 , DISPEL_DISEASE = 3 ,
DISPEL_POISON = 4 , DISPEL_STEALTH = 5 , DISPEL_INVISIBILITY = 6 , DISPEL_ALL = 7 ,
DISPEL_SPE_NPC_ONLY = 8 , DISPEL_ENRAGE = 9 , DISPEL_ZG_TICKET = 10 , DESPEL_OLD_UNUSED = 11
}
enum SpellImmunity {
IMMUNITY_EFFECT = 0 , IMMUNITY_STATE = 1 , IMMUNITY_SCHOOL = 2 , IMMUNITY_DAMAGE = 3 ,
IMMUNITY_DISPEL = 4 , IMMUNITY_MECHANIC = 5
}
enum WeaponAttackType { BASE_ATTACK = 0 , OFF_ATTACK = 1 , RANGED_ATTACK = 2 }
enum SpellMissInfo {
SPELL_MISS_NONE = 0 , SPELL_MISS_MISS = 1 , SPELL_MISS_RESIST = 2 , SPELL_MISS_DODGE = 3 ,
SPELL_MISS_PARRY = 4 , SPELL_MISS_BLOCK = 5 , SPELL_MISS_EVADE = 6 , SPELL_MISS_IMMUNE = 7 ,
SPELL_MISS_IMMUNE2 = 8 , SPELL_MISS_DEFLECT = 9 , SPELL_MISS_ABSORB = 10 , SPELL_MISS_REFLECT = 11
}
enum SpellHitType {
SPELL_HIT_TYPE_CRIT_DEBUG = 0x01 , SPELL_HIT_TYPE_CRIT = 0x02 , SPELL_HIT_TYPE_HIT_DEBUG = 0x04 , SPELL_HIT_TYPE_SPLIT = 0x08 ,
SPELL_HIT_TYPE_VICTIM_IS_ATTACKER = 0x10 , SPELL_HIT_TYPE_ATTACK_TABLE_DEBUG = 0x20
}
enum SpellDmgClass { SPELL_DAMAGE_CLASS_NONE = 0 , SPELL_DAMAGE_CLASS_MAGIC = 1 , SPELL_DAMAGE_CLASS_MELEE = 2 , SPELL_DAMAGE_CLASS_RANGED = 3 }
enum SpellPreventionType { SPELL_PREVENTION_TYPE_NONE = 0 , SPELL_PREVENTION_TYPE_SILENCE = 1 , SPELL_PREVENTION_TYPE_PACIFY = 2 }
enum SpellRangeIndex { SPELL_RANGE_IDX_SELF_ONLY = 1 , SPELL_RANGE_IDX_COMBAT = 2 , SPELL_RANGE_IDX_ANYWHERE = 13 , SPELL_RANGE_IDX_HUNTER = 114 }
indexes from SpellRange.dbc, listed only special and used in code
enum SpellRangeFlags { SPELL_RANGE_FLAG_MELEE = 0x1 , SPELL_RANGE_FLAG_RANGED = 0x2 }
enum DamageEffectType {
DIRECT_DAMAGE = 0 , SPELL_DIRECT_DAMAGE = 1 , DOT = 2 , HEAL = 3 ,
NODAMAGE = 4 , SELF_DAMAGE_ROGUE_FALL = 5 , SELF_DAMAGE = 6 , INSTAKILL = 7 ,
SPELL_DAMAGE_SHIELD = 8 , SPLIT_DAMAGE = 9
}
enum GameobjectTypes {
GAMEOBJECT_TYPE_DOOR = 0 , GAMEOBJECT_TYPE_BUTTON = 1 , GAMEOBJECT_TYPE_QUESTGIVER = 2 , GAMEOBJECT_TYPE_CHEST = 3 ,
GAMEOBJECT_TYPE_BINDER = 4 , GAMEOBJECT_TYPE_GENERIC = 5 , GAMEOBJECT_TYPE_TRAP = 6 , GAMEOBJECT_TYPE_CHAIR = 7 ,
GAMEOBJECT_TYPE_SPELL_FOCUS = 8 , GAMEOBJECT_TYPE_TEXT = 9 , GAMEOBJECT_TYPE_GOOBER = 10 , GAMEOBJECT_TYPE_TRANSPORT = 11 ,
GAMEOBJECT_TYPE_AREADAMAGE = 12 , GAMEOBJECT_TYPE_CAMERA = 13 , GAMEOBJECT_TYPE_MAP_OBJECT = 14 , GAMEOBJECT_TYPE_MO_TRANSPORT = 15 ,
GAMEOBJECT_TYPE_DUEL_ARBITER = 16 , GAMEOBJECT_TYPE_FISHINGNODE = 17 , GAMEOBJECT_TYPE_SUMMONING_RITUAL = 18 , GAMEOBJECT_TYPE_MAILBOX = 19 ,
GAMEOBJECT_TYPE_DO_NOT_USE = 20 , GAMEOBJECT_TYPE_GUARDPOST = 21 , GAMEOBJECT_TYPE_SPELLCASTER = 22 , GAMEOBJECT_TYPE_MEETINGSTONE = 23 ,
GAMEOBJECT_TYPE_FLAGSTAND = 24 , GAMEOBJECT_TYPE_FISHINGHOLE = 25 , GAMEOBJECT_TYPE_FLAGDROP = 26 , GAMEOBJECT_TYPE_MINI_GAME = 27 ,
GAMEOBJECT_TYPE_DO_NOT_USE_2 = 28 , GAMEOBJECT_TYPE_CAPTURE_POINT = 29 , GAMEOBJECT_TYPE_AURA_GENERATOR = 30 , GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY = 31 ,
GAMEOBJECT_TYPE_BARBER_CHAIR = 32 , GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING = 33 , GAMEOBJECT_TYPE_GUILD_BANK = 34 , GAMEOBJECT_TYPE_TRAPDOOR = 35
}
enum GameObjectFlags {
GO_FLAG_IN_USE = 0x00000001 , GO_FLAG_LOCKED = 0x00000002 , GO_FLAG_INTERACT_COND = 0x00000004 , GO_FLAG_TRANSPORT = 0x00000008 ,
GO_FLAG_NO_INTERACT = 0x00000010 , GO_FLAG_NODESPAWN = 0x00000020 , GO_FLAG_TRIGGERED = 0x00000040 , GO_FLAG_AI_OBSTACLE = 0x00000080 ,
GO_FLAG_FREEZE_ANIMATION = 0x00000100 , GO_FLAG_DAMAGED = 0x00000200 , GO_FLAG_DESTROYED = 0x00000400
}
enum GameObjectDynamicLowFlags {
GO_DYNFLAG_LO_ACTIVATE = 0x01 , GO_DYNFLAG_LO_ANIMATE = 0x02 , GO_DYNFLAG_LO_NO_INTERACT = 0x04 , GO_DYNFLAG_LO_SPARKLE = 0x08 ,
GO_DYNFLAG_LO_STOPPED = 0x10
}
enum TextEmotes {
TEXTEMOTE_AGREE = 1 , TEXTEMOTE_AMAZE = 2 , TEXTEMOTE_ANGRY = 3 , TEXTEMOTE_APOLOGIZE = 4 ,
TEXTEMOTE_APPLAUD = 5 , TEXTEMOTE_BASHFUL = 6 , TEXTEMOTE_BECKON = 7 , TEXTEMOTE_BEG = 8 ,
TEXTEMOTE_BITE = 9 , TEXTEMOTE_BLEED = 10 , TEXTEMOTE_BLINK = 11 , TEXTEMOTE_BLUSH = 12 ,
TEXTEMOTE_BONK = 13 , TEXTEMOTE_BORED = 14 , TEXTEMOTE_BOUNCE = 15 , TEXTEMOTE_BRB = 16 ,
TEXTEMOTE_BOW = 17 , TEXTEMOTE_BURP = 18 , TEXTEMOTE_BYE = 19 , TEXTEMOTE_CACKLE = 20 ,
TEXTEMOTE_CHEER = 21 , TEXTEMOTE_CHICKEN = 22 , TEXTEMOTE_CHUCKLE = 23 , TEXTEMOTE_CLAP = 24 ,
TEXTEMOTE_CONFUSED = 25 , TEXTEMOTE_CONGRATULATE = 26 , TEXTEMOTE_COUGH = 27 , TEXTEMOTE_COWER = 28 ,
TEXTEMOTE_CRACK = 29 , TEXTEMOTE_CRINGE = 30 , TEXTEMOTE_CRY = 31 , TEXTEMOTE_CURIOUS = 32 ,
TEXTEMOTE_CURTSEY = 33 , TEXTEMOTE_DANCE = 34 , TEXTEMOTE_DRINK = 35 , TEXTEMOTE_DROOL = 36 ,
TEXTEMOTE_EAT = 37 , TEXTEMOTE_EYE = 38 , TEXTEMOTE_FART = 39 , TEXTEMOTE_FIDGET = 40 ,
TEXTEMOTE_FLEX = 41 , TEXTEMOTE_FROWN = 42 , TEXTEMOTE_GASP = 43 , TEXTEMOTE_GAZE = 44 ,
TEXTEMOTE_GIGGLE = 45 , TEXTEMOTE_GLARE = 46 , TEXTEMOTE_GLOAT = 47 , TEXTEMOTE_GREET = 48 ,
TEXTEMOTE_GRIN = 49 , TEXTEMOTE_GROAN = 50 , TEXTEMOTE_GROVEL = 51 , TEXTEMOTE_GUFFAW = 52 ,
TEXTEMOTE_HAIL = 53 , TEXTEMOTE_HAPPY = 54 , TEXTEMOTE_HELLO = 55 , TEXTEMOTE_HUG = 56 ,
TEXTEMOTE_HUNGRY = 57 , TEXTEMOTE_KISS = 58 , TEXTEMOTE_KNEEL = 59 , TEXTEMOTE_LAUGH = 60 ,
TEXTEMOTE_LAYDOWN = 61 , TEXTEMOTE_MESSAGE = 62 , TEXTEMOTE_MOAN = 63 , TEXTEMOTE_MOON = 64 ,
TEXTEMOTE_MOURN = 65 , TEXTEMOTE_NO = 66 , TEXTEMOTE_NOD = 67 , TEXTEMOTE_NOSEPICK = 68 ,
TEXTEMOTE_PANIC = 69 , TEXTEMOTE_PEER = 70 , TEXTEMOTE_PLEAD = 71 , TEXTEMOTE_POINT = 72 ,
TEXTEMOTE_POKE = 73 , TEXTEMOTE_PRAY = 74 , TEXTEMOTE_ROAR = 75 , TEXTEMOTE_ROFL = 76 ,
TEXTEMOTE_RUDE = 77 , TEXTEMOTE_SALUTE = 78 , TEXTEMOTE_SCRATCH = 79 , TEXTEMOTE_SEXY = 80 ,
TEXTEMOTE_SHAKE = 81 , TEXTEMOTE_SHOUT = 82 , TEXTEMOTE_SHRUG = 83 , TEXTEMOTE_SHY = 84 ,
TEXTEMOTE_SIGH = 85 , TEXTEMOTE_SIT = 86 , TEXTEMOTE_SLEEP = 87 , TEXTEMOTE_SNARL = 88 ,
TEXTEMOTE_SPIT = 89 , TEXTEMOTE_STARE = 90 , TEXTEMOTE_SURPRISED = 91 , TEXTEMOTE_SURRENDER = 92 ,
TEXTEMOTE_TALK = 93 , TEXTEMOTE_TALKEX = 94 , TEXTEMOTE_TALKQ = 95 , TEXTEMOTE_TAP = 96 ,
TEXTEMOTE_THANK = 97 , TEXTEMOTE_THREATEN = 98 , TEXTEMOTE_TIRED = 99 , TEXTEMOTE_VICTORY = 100 ,
TEXTEMOTE_WAVE = 101 , TEXTEMOTE_WELCOME = 102 , TEXTEMOTE_WHINE = 103 , TEXTEMOTE_WHISTLE = 104 ,
TEXTEMOTE_WORK = 105 , TEXTEMOTE_YAWN = 106 , TEXTEMOTE_BOGGLE = 107 , TEXTEMOTE_CALM = 108 ,
TEXTEMOTE_COLD = 109 , TEXTEMOTE_COMFORT = 110 , TEXTEMOTE_CUDDLE = 111 , TEXTEMOTE_DUCK = 112 ,
TEXTEMOTE_INSULT = 113 , TEXTEMOTE_INTRODUCE = 114 , TEXTEMOTE_JK = 115 , TEXTEMOTE_LICK = 116 ,
TEXTEMOTE_LISTEN = 117 , TEXTEMOTE_LOST = 118 , TEXTEMOTE_MOCK = 119 , TEXTEMOTE_PONDER = 120 ,
TEXTEMOTE_POUNCE = 121 , TEXTEMOTE_PRAISE = 122 , TEXTEMOTE_PURR = 123 , TEXTEMOTE_PUZZLE = 124 ,
TEXTEMOTE_RAISE = 125 , TEXTEMOTE_READY = 126 , TEXTEMOTE_SHIMMY = 127 , TEXTEMOTE_SHIVER = 128 ,
TEXTEMOTE_SHOO = 129 , TEXTEMOTE_SLAP = 130 , TEXTEMOTE_SMIRK = 131 , TEXTEMOTE_SNIFF = 132 ,
TEXTEMOTE_SNUB = 133 , TEXTEMOTE_SOOTHE = 134 , TEXTEMOTE_STINK = 135 , TEXTEMOTE_TAUNT = 136 ,
TEXTEMOTE_TEASE = 137 , TEXTEMOTE_THIRSTY = 138 , TEXTEMOTE_VETO = 139 , TEXTEMOTE_SNICKER = 140 ,
TEXTEMOTE_STAND = 141 , TEXTEMOTE_TICKLE = 142 , TEXTEMOTE_VIOLIN = 143 , TEXTEMOTE_SMILE = 163 ,
TEXTEMOTE_RASP = 183 , TEXTEMOTE_PITY = 203 , TEXTEMOTE_GROWL = 204 , TEXTEMOTE_BARK = 205 ,
TEXTEMOTE_SCARED = 223 , TEXTEMOTE_FLOP = 224 , TEXTEMOTE_LOVE = 225 , TEXTEMOTE_MOO = 226 ,
TEXTEMOTE_OPENFIRE = 327 , TEXTEMOTE_FLIRT = 328 , TEXTEMOTE_JOKE = 329 , TEXTEMOTE_COMMEND = 243 ,
TEXTEMOTE_WINK = 363 , TEXTEMOTE_PAT = 364 , TEXTEMOTE_SERIOUS = 365 , TEXTEMOTE_MOUNTSPECIAL = 366 ,
TEXTEMOTE_GOODLUCK = 367 , TEXTEMOTE_BLAME = 368 , TEXTEMOTE_BLANK = 369 , TEXTEMOTE_BRANDISH = 370 ,
TEXTEMOTE_BREATH = 371 , TEXTEMOTE_DISAGREE = 372 , TEXTEMOTE_DOUBT = 373 , TEXTEMOTE_EMBARRASS = 374 ,
TEXTEMOTE_ENCOURAGE = 375 , TEXTEMOTE_ENEMY = 376 , TEXTEMOTE_EYEBROW = 377 , TEXTEMOTE_TOAST = 378
}
enum Emote {
EMOTE_ONESHOT_NONE = 0 , EMOTE_ONESHOT_TALK = 1 , EMOTE_ONESHOT_BOW = 2 , EMOTE_ONESHOT_WAVE = 3 ,
EMOTE_ONESHOT_CHEER = 4 , EMOTE_ONESHOT_EXCLAMATION = 5 , EMOTE_ONESHOT_QUESTION = 6 , EMOTE_ONESHOT_EAT = 7 ,
EMOTE_STATE_DANCE = 10 , EMOTE_ONESHOT_LAUGH = 11 , EMOTE_STATE_SLEEP = 12 , EMOTE_STATE_SIT = 13 ,
EMOTE_ONESHOT_RUDE = 14 , EMOTE_ONESHOT_ROAR = 15 , EMOTE_ONESHOT_KNEEL = 16 , EMOTE_ONESHOT_KISS = 17 ,
EMOTE_ONESHOT_CRY = 18 , EMOTE_ONESHOT_CHICKEN = 19 , EMOTE_ONESHOT_BEG = 20 , EMOTE_ONESHOT_APPLAUD = 21 ,
EMOTE_ONESHOT_SHOUT = 22 , EMOTE_ONESHOT_FLEX = 23 , EMOTE_ONESHOT_SHY = 24 , EMOTE_ONESHOT_POINT = 25 ,
EMOTE_STATE_STAND = 26 , EMOTE_STATE_READYUNARMED = 27 , EMOTE_STATE_WORK_SHEATHED = 28 , EMOTE_STATE_POINT = 29 ,
EMOTE_STATE_NONE = 30 , EMOTE_ONESHOT_WOUND = 33 , EMOTE_ONESHOT_WOUNDCRITICAL = 34 , EMOTE_ONESHOT_ATTACKUNARMED = 35 ,
EMOTE_ONESHOT_ATTACK1H = 36 , EMOTE_ONESHOT_ATTACK2HTIGHT = 37 , EMOTE_ONESHOT_ATTACK2HLOOSE = 38 , EMOTE_ONESHOT_PARRYUNARMED = 39 ,
EMOTE_ONESHOT_PARRYSHIELD = 43 , EMOTE_ONESHOT_READYUNARMED = 44 , EMOTE_ONESHOT_READY1H = 45 , EMOTE_ONESHOT_READYBOW = 48 ,
EMOTE_ONESHOT_SPELLPRECAST = 50 , EMOTE_ONESHOT_SPELLCAST = 51 , EMOTE_ONESHOT_BATTLEROAR = 53 , EMOTE_ONESHOT_SPECIALATTACK1H = 54 ,
EMOTE_ONESHOT_KICK = 60 , EMOTE_ONESHOT_ATTACKTHROWN = 61 , EMOTE_STATE_STUN = 64 , EMOTE_STATE_DEAD = 65 ,
EMOTE_ONESHOT_SALUTE = 66 , EMOTE_STATE_KNEEL = 68 , EMOTE_STATE_USESTANDING = 69 , EMOTE_ONESHOT_WAVE_NOSHEATHE = 70 ,
EMOTE_ONESHOT_CHEER_NOSHEATHE = 71 , EMOTE_ONESHOT_EAT_NOSHEATHE = 92 , EMOTE_STATE_STUN_NOSHEATHE = 93 , EMOTE_ONESHOT_DANCE = 94 ,
EMOTE_ONESHOT_SALUTE_NOSHEATH = 113 , EMOTE_STATE_USESTANDING_NOSHEATHE = 133 , EMOTE_ONESHOT_LAUGH_NOSHEATHE = 153 , EMOTE_STATE_WORK = 173 ,
EMOTE_STATE_SPELLPRECAST = 193 , EMOTE_ONESHOT_READYRIFLE = 213 , EMOTE_STATE_READYRIFLE = 214 , EMOTE_STATE_WORK_MINING = 233 ,
EMOTE_STATE_WORK_CHOPWOOD = 234 , EMOTE_STATE_APPLAUD = 253 , EMOTE_ONESHOT_LIFTOFF = 254 , EMOTE_ONESHOT_YES = 273 ,
EMOTE_ONESHOT_NO = 274 , EMOTE_ONESHOT_TRAIN = 275 , EMOTE_ONESHOT_LAND = 293 , EMOTE_STATE_AT_EASE = 313 ,
EMOTE_STATE_READY1H = 333 , EMOTE_STATE_SPELLKNEELSTART = 353 , EMOTE_STATE_SUBMERGED = 373 , EMOTE_ONESHOT_SUBMERGE = 374 ,
EMOTE_STATE_READY2H = 375 , EMOTE_STATE_READYBOW = 376 , EMOTE_ONESHOT_MOUNTSPECIAL = 377 , EMOTE_STATE_TALK = 378 ,
EMOTE_STATE_FISHING = 379 , EMOTE_ONESHOT_FISHING = 380 , EMOTE_ONESHOT_LOOT = 381 , EMOTE_STATE_WHIRLWIND = 382 ,
EMOTE_STATE_DROWNED = 383 , EMOTE_STATE_HOLD_BOW = 384 , EMOTE_STATE_HOLD_RIFLE = 385 , EMOTE_STATE_HOLD_THROWN = 386 ,
EMOTE_ONESHOT_DROWN = 387 , EMOTE_ONESHOT_STOMP = 388 , EMOTE_ONESHOT_ATTACKOFF = 389 , EMOTE_ONESHOT_ATTACKOFFPIERCE = 390 ,
EMOTE_STATE_ROAR = 391 , EMOTE_STATE_LAUGH = 392 , EMOTE_ONESHOT_CREATURE_SPECIAL = 393 , EMOTE_ONESHOT_JUMPLANDRUN = 394 ,
EMOTE_ONESHOT_JUMPEND = 395 , EMOTE_ONESHOT_TALK_NOSHEATHE = 396 , EMOTE_ONESHOT_POINT_NOSHEATHE = 397 , EMOTE_STATE_CANNIBALIZE = 398 ,
EMOTE_ONESHOT_JUMPSTART = 399 , EMOTE_STATE_DANCESPECIAL = 400 , EMOTE_ONESHOT_DANCESPECIAL = 401 , EMOTE_ONESHOT_CUSTOMSPELL01 = 402 ,
EMOTE_ONESHOT_CUSTOMSPELL02 = 403 , EMOTE_ONESHOT_CUSTOMSPELL03 = 404 , EMOTE_ONESHOT_CUSTOMSPELL04 = 405 , EMOTE_ONESHOT_CUSTOMSPELL05 = 406 ,
EMOTE_ONESHOT_CUSTOMSPELL06 = 407 , EMOTE_ONESHOT_CUSTOMSPELL07 = 408 , EMOTE_ONESHOT_CUSTOMSPELL08 = 409 , EMOTE_ONESHOT_CUSTOMSPELL09 = 410 ,
EMOTE_ONESHOT_CUSTOMSPELL10 = 411 , EMOTE_STATE_EXCLAIM = 412 , EMOTE_STATE_DANCE_CUSTOM = 413 , EMOTE_STATE_SIT_CHAIR_MED = 415 ,
EMOTE_STATE_CUSTOM_SPELL_01 = 416 , EMOTE_STATE_CUSTOM_SPELL_02 = 417 , EMOTE_STATE_EAT = 418 , EMOTE_STATE_CUSTOM_SPELL_04 = 419 ,
EMOTE_STATE_CUSTOM_SPELL_03 = 420 , EMOTE_STATE_CUSTOM_SPELL_05 = 421 , EMOTE_STATE_SPELLEFFECT_HOLD = 422 , EMOTE_STATE_EAT_NO_SHEATHE = 423 ,
EMOTE_STATE_MOUNT = 424 , EMOTE_STATE_READY2HL = 425 , EMOTE_STATE_SIT_CHAIR_HIGH = 426 , EMOTE_STATE_FALL = 427 ,
EMOTE_STATE_LOOT = 428 , EMOTE_STATE_SUBMERGED_NEW = 429 , EMOTE_ONESHOT_COWER = 430 , EMOTE_STATE_COWER = 431 ,
EMOTE_ONESHOT_USESTANDING = 432 , EMOTE_STATE_STEALTH_STAND = 433 , EMOTE_ONESHOT_OMNICAST_GHOUL = 434 , EMOTE_ONESHOT_ATTACKBOW = 435 ,
EMOTE_ONESHOT_ATTACKRIFLE = 436 , EMOTE_STATE_SWIM_IDLE = 437 , EMOTE_STATE_ATTACK_UNARMED = 438 , EMOTE_ONESHOT_SPELLCAST_W_SOUND = 439 ,
EMOTE_ONESHOT_DODGE = 440 , EMOTE_ONESHOT_PARRY1H = 441 , EMOTE_ONESHOT_PARRY2H = 442 , EMOTE_ONESHOT_PARRY2HL = 443 ,
EMOTE_STATE_FLYFALL = 444 , EMOTE_ONESHOT_FLYDEATH = 445 , EMOTE_STATE_FLY_FALL = 446 , EMOTE_ONESHOT_FLY_SIT_GROUND_DOWN = 447 ,
EMOTE_ONESHOT_FLY_SIT_GROUND_UP = 448 , EMOTE_ONESHOT_EMERGE = 449 , EMOTE_ONESHOT_DRAGONSPIT = 450 , EMOTE_STATE_SPECIALUNARMED = 451 ,
EMOTE_ONESHOT_FLYGRAB = 452 , EMOTE_STATE_FLYGRABCLOSED = 453 , EMOTE_ONESHOT_FLYGRABTHROWN = 454 , EMOTE_STATE_FLY_SIT_GROUND = 455 ,
EMOTE_STATE_WALKBACKWARDS = 456 , EMOTE_ONESHOT_FLYTALK = 457 , EMOTE_ONESHOT_FLYATTACK1H = 458 , EMOTE_STATE_CUSTOMSPELL08 = 459 ,
EMOTE_ONESHOT_FLY_DRAGONSPIT = 460 , EMOTE_STATE_SIT_CHAIR_LOW = 461 , EMOTE_ONE_SHOT_STUN = 462 , EMOTE_ONESHOT_SPELLCAST_OMNI = 463 ,
EMOTE_STATE_READYTHROWN = 465 , EMOTE_ONESHOT_WORK_CHOPWOOD = 466 , EMOTE_ONESHOT_WORK_MINING = 467 , EMOTE_STATE_SPELL_CHANNEL_OMNI = 468 ,
EMOTE_STATE_SPELL_CHANNEL_DIRECTED = 469 , EMOTE_STAND_STATE_NONE = 470 , EMOTE_STATE_READYJOUST = 471 , EMOTE_STATE_STRANGULATE = 473 ,
EMOTE_STATE_READYSPELLOMNI = 474 , EMOTE_STATE_HOLD_JOUST = 475 , EMOTE_ONESHOT_CRY_JAINA = 476
}
enum Anim {
ANIM_STAND = 0x0 , ANIM_DEATH = 0x1 , ANIM_SPELL = 0x2 , ANIM_STOP = 0x3 ,
ANIM_WALK = 0x4 , ANIM_RUN = 0x5 , ANIM_DEAD = 0x6 , ANIM_RISE = 0x7 ,
ANIM_STANDWOUND = 0x8 , ANIM_COMBATWOUND = 0x9 , ANIM_COMBATCRITICAL = 0xA , ANIM_SHUFFLE_LEFT = 0xB ,
ANIM_SHUFFLE_RIGHT = 0xC , ANIM_WALK_BACKWARDS = 0xD , ANIM_STUN = 0xE , ANIM_HANDS_CLOSED = 0xF ,
ANIM_ATTACKUNARMED = 0x10 , ANIM_ATTACK1H = 0x11 , ANIM_ATTACK2HTIGHT = 0x12 , ANIM_ATTACK2HLOOSE = 0x13 ,
ANIM_PARRYUNARMED = 0x14 , ANIM_PARRY1H = 0x15 , ANIM_PARRY2HTIGHT = 0x16 , ANIM_PARRY2HLOOSE = 0x17 ,
ANIM_PARRYSHIELD = 0x18 , ANIM_READYUNARMED = 0x19 , ANIM_READY1H = 0x1A , ANIM_READY2HTIGHT = 0x1B ,
ANIM_READY2HLOOSE = 0x1C , ANIM_READYBOW = 0x1D , ANIM_DODGE = 0x1E , ANIM_SPELLPRECAST = 0x1F ,
ANIM_SPELLCAST = 0x20 , ANIM_SPELLCASTAREA = 0x21 , ANIM_NPCWELCOME = 0x22 , ANIM_NPCGOODBYE = 0x23 ,
ANIM_BLOCK = 0x24 , ANIM_JUMPSTART = 0x25 , ANIM_JUMP = 0x26 , ANIM_JUMPEND = 0x27 ,
ANIM_FALL = 0x28 , ANIM_SWIMIDLE = 0x29 , ANIM_SWIM = 0x2A , ANIM_SWIM_LEFT = 0x2B ,
ANIM_SWIM_RIGHT = 0x2C , ANIM_SWIM_BACKWARDS = 0x2D , ANIM_ATTACKBOW = 0x2E , ANIM_FIREBOW = 0x2F ,
ANIM_READYRIFLE = 0x30 , ANIM_ATTACKRIFLE = 0x31 , ANIM_LOOT = 0x32 , ANIM_SPELL_PRECAST_DIRECTED = 0x33 ,
ANIM_SPELL_PRECAST_OMNI = 0x34 , ANIM_SPELL_CAST_DIRECTED = 0x35 , ANIM_SPELL_CAST_OMNI = 0x36 , ANIM_SPELL_BATTLEROAR = 0x37 ,
ANIM_SPELL_READYABILITY = 0x38 , ANIM_SPELL_SPECIAL1H = 0x39 , ANIM_SPELL_SPECIAL2H = 0x3A , ANIM_SPELL_SHIELDBASH = 0x3B ,
ANIM_EMOTE_TALK = 0x3C , ANIM_EMOTE_EAT = 0x3D , ANIM_EMOTE_WORK = 0x3E , ANIM_EMOTE_USE_STANDING = 0x3F ,
ANIM_EMOTE_EXCLAMATION = 0x40 , ANIM_EMOTE_QUESTION = 0x41 , ANIM_EMOTE_BOW = 0x42 , ANIM_EMOTE_WAVE = 0x43 ,
ANIM_EMOTE_CHEER = 0x44 , ANIM_EMOTE_DANCE = 0x45 , ANIM_EMOTE_LAUGH = 0x46 , ANIM_EMOTE_SLEEP = 0x47 ,
ANIM_EMOTE_SIT_GROUND = 0x48 , ANIM_EMOTE_RUDE = 0x49 , ANIM_EMOTE_ROAR = 0x4A , ANIM_EMOTE_KNEEL = 0x4B ,
ANIM_EMOTE_KISS = 0x4C , ANIM_EMOTE_CRY = 0x4D , ANIM_EMOTE_CHICKEN = 0x4E , ANIM_EMOTE_BEG = 0x4F ,
ANIM_EMOTE_APPLAUD = 0x50 , ANIM_EMOTE_SHOUT = 0x51 , ANIM_EMOTE_FLEX = 0x52 , ANIM_EMOTE_SHY = 0x53 ,
ANIM_EMOTE_POINT = 0x54 , ANIM_ATTACK1HPIERCE = 0x55 , ANIM_ATTACK2HLOOSEPIERCE = 0x56 , ANIM_ATTACKOFF = 0x57 ,
ANIM_ATTACKOFFPIERCE = 0x58 , ANIM_SHEATHE = 0x59 , ANIM_HIPSHEATHE = 0x5A , ANIM_MOUNT = 0x5B ,
ANIM_RUN_LEANRIGHT = 0x5C , ANIM_RUN_LEANLEFT = 0x5D , ANIM_MOUNT_SPECIAL = 0x5E , ANIM_KICK = 0x5F ,
ANIM_SITDOWN = 0x60 , ANIM_SITTING = 0x61 , ANIM_SITUP = 0x62 , ANIM_SLEEPDOWN = 0x63 ,
ANIM_SLEEPING = 0x64 , ANIM_SLEEPUP = 0x65 , ANIM_SITCHAIRLOW = 0x66 , ANIM_SITCHAIRMEDIUM = 0x67 ,
ANIM_SITCHAIRHIGH = 0x68 , ANIM_LOADBOW = 0x69 , ANIM_LOADRIFLE = 0x6A , ANIM_ATTACKTHROWN = 0x6B ,
ANIM_READYTHROWN = 0x6C , ANIM_HOLDBOW = 0x6D , ANIM_HOLDRIFLE = 0x6E , ANIM_HOLDTHROWN = 0x6F ,
ANIM_LOADTHROWN = 0x70 , ANIM_EMOTE_SALUTE = 0x71 , ANIM_KNEELDOWN = 0x72 , ANIM_KNEELING = 0x73 ,
ANIM_KNEELUP = 0x74 , ANIM_ATTACKUNARMEDOFF = 0x75 , ANIM_SPECIALUNARMED = 0x76 , ANIM_STEALTHWALK = 0x77 ,
ANIM_STEALTHSTAND = 0x78 , ANIM_KNOCKDOWN = 0x79 , ANIM_EATING = 0x7A , ANIM_USESTANDINGLOOP = 0x7B ,
ANIM_CHANNELCASTDIRECTED = 0x7C , ANIM_CHANNELCASTOMNI = 0x7D , ANIM_WHIRLWIND = 0x7E , ANIM_BIRTH = 0x7F ,
ANIM_USESTANDINGSTART = 0x80 , ANIM_USESTANDINGEND = 0x81 , ANIM_HOWL = 0x82 , ANIM_DROWN = 0x83 ,
ANIM_DROWNED = 0x84 , ANIM_FISHINGCAST = 0x85 , ANIM_FISHINGLOOP = 0x86 , ANIM_FLY = 0x87 ,
ANIM_EMOTE_WORK_NO_SHEATHE = 0x88 , ANIM_EMOTE_STUN_NO_SHEATHE = 0x89 , ANIM_EMOTE_USE_STANDING_NO_SHEATHE = 0x8A , ANIM_SPELL_SLEEP_DOWN = 0x8B ,
ANIM_SPELL_KNEEL_START = 0x8C , ANIM_SPELL_KNEEL_LOOP = 0x8D , ANIM_SPELL_KNEEL_END = 0x8E , ANIM_SPRINT = 0x8F ,
ANIM_IN_FIGHT = 0x90 , ANIM_GAMEOBJ_SPAWN = 145 , ANIM_GAMEOBJ_CLOSE = 146 , ANIM_GAMEOBJ_CLOSED = 147 ,
ANIM_GAMEOBJ_OPEN = 148 , ANIM_GAMEOBJ_OPENED = 149 , ANIM_GAMEOBJ_DESTROY = 150 , ANIM_GAMEOBJ_DESTROYED = 151 ,
ANIM_GAMEOBJ_REBUILD = 152 , ANIM_GAMEOBJ_CUSTOM0 = 153 , ANIM_GAMEOBJ_CUSTOM1 = 154 , ANIM_GAMEOBJ_CUSTOM2 = 155 ,
ANIM_GAMEOBJ_CUSTOM3 = 156 , ANIM_GAMEOBJ_DESPAWN = 157 , ANIM_HOLD = 158 , ANIM_DECAY = 159 ,
ANIM_BOWPULL = 160 , ANIM_BOWRELEASE = 161 , ANIM_SHIPSTART = 162 , ANIM_SHIPMOVEING = 163 ,
ANIM_SHIPSTOP = 164 , ANIM_GROUPARROW = 165 , ANIM_ARROW = 166 , ANIM_CORPSEARROW = 167 ,
ANIM_GUIDEARROW = 168 , ANIM_SWAY = 169 , ANIM_DRUIDCATPOUNCE = 170 , ANIM_DRUIDCATRIP = 171 ,
ANIM_DRUIDCATRAKE = 172 , ANIM_DRUIDCATRAVAGE = 173 , ANIM_DRUIDCATCLAW = 174 , ANIM_DRUIDCATCOWER = 175 ,
ANIM_DRUIDBEARSWIPE = 176 , ANIM_DRUIDBEARBITE = 177 , ANIM_DRUIDBEARMAUL = 178 , ANIM_DRUIDBEARBASH = 179 ,
ANIM_DRAGONTAIL = 180 , ANIM_DRAGONSTOMP = 181 , ANIM_DRAGONSPIT = 182 , ANIM_DRAGONSPITHOVER = 183 ,
ANIM_DRAGONSPITFLY = 184 , ANIM_EMOTEYES = 185 , ANIM_EMOTENO = 186 , ANIM_JUMPLANDRUN = 187 ,
ANIM_LOOTHOLD = 188 , ANIM_LOOTUP = 189 , ANIM_STANDHIGH = 190 , ANIM_IMPACT = 191 ,
ANIM_LIFTOFF = 192 , ANIM_HOVER = 193 , ANIM_SUCCUBUSENTICE = 194 , ANIM_EMOTETRAIN = 195 ,
ANIM_EMOTEDEAD = 196 , ANIM_EMOTEDANCEONCE = 197 , ANIM_DEFLECT = 198 , ANIM_EMOTEEATNOSHEATHE = 199 ,
ANIM_LAND = 200 , ANIM_SUBMERGE = 201 , ANIM_SUBMERGED = 202 , ANIM_CANNIBALIZE = 203 ,
ANIM_ARROWBIRTH = 204 , ANIM_GROURARROWBIRTH = 205 , ANIM_CORPSEARROWBIRTH = 206 , ANIM_GUIDEARROWBIRTH = 207 ,
ANIM_EMOTETALKNOSHEATHE = 208 , ANIM_EMOTEPOINTNOSHEATHE = 209 , ANIM_EMOTESALUTENOSHEATHE = 210 , ANIM_EMOTEDANCESPECIAL = 211 ,
ANIM_MUTILATE = 212 , ANIM_CUSTOMSPELL01 = 213 , ANIM_CUSTOMSPELL02 = 214 , ANIM_CUSTOMSPELL03 = 215 ,
ANIM_CUSTOMSPELL04 = 216 , ANIM_CUSTOMSPELL05 = 217 , ANIM_CUSTOMSPELL06 = 218 , ANIM_CUSTOMSPELL07 = 219 ,
ANIM_CUSTOMSPELL08 = 220 , ANIM_CUSTOMSPELL09 = 221 , ANIM_CUSTOMSPELL10 = 222 , ANIM_StealthRun = 223
}
enum LockKeyType { LOCK_KEY_NONE = 0 , LOCK_KEY_ITEM = 1 , LOCK_KEY_SKILL = 2 , LOCK_KEY_SPELL = 3 }
enum LockType {
LOCKTYPE_NONE = 0 , LOCKTYPE_PICKLOCK = 1 , LOCKTYPE_HERBALISM = 2 , LOCKTYPE_MINING = 3 ,
LOCKTYPE_DISARM_TRAP = 4 , LOCKTYPE_OPEN = 5 , LOCKTYPE_TREASURE = 6 , LOCKTYPE_CALCIFIED_ELVEN_GEMS = 7 ,
LOCKTYPE_CLOSE = 8 , LOCKTYPE_ARM_TRAP = 9 , LOCKTYPE_QUICK_OPEN = 10 , LOCKTYPE_QUICK_CLOSE = 11 ,
LOCKTYPE_OPEN_TINKERING = 12 , LOCKTYPE_OPEN_KNEELING = 13 , LOCKTYPE_OPEN_ATTACKING = 14 , LOCKTYPE_GAHZRIDIAN = 15 ,
LOCKTYPE_BLASTING = 16 , LOCKTYPE_SLOW_OPEN = 17 , LOCKTYPE_SLOW_CLOSE = 18 , LOCKTYPE_FISHING = 19 ,
LOCKTYPE_INSCRIPTION = 20 , LOCKTYPE_OPEN_FROM_VEHICLE = 21
}
enum TrainerType { TRAINER_TYPE_CLASS = 0 , TRAINER_TYPE_MOUNTS = 1 , TRAINER_TYPE_TRADESKILLS = 2 , TRAINER_TYPE_PETS = 3 }
enum CreatureType {
CREATURE_TYPE_BEAST = 1 , CREATURE_TYPE_DRAGONKIN = 2 , CREATURE_TYPE_DEMON = 3 , CREATURE_TYPE_ELEMENTAL = 4 ,
CREATURE_TYPE_GIANT = 5 , CREATURE_TYPE_UNDEAD = 6 , CREATURE_TYPE_HUMANOID = 7 , CREATURE_TYPE_CRITTER = 8 ,
CREATURE_TYPE_MECHANICAL = 9 , CREATURE_TYPE_NOT_SPECIFIED = 10 , CREATURE_TYPE_TOTEM = 11 , CREATURE_TYPE_NON_COMBAT_PET = 12 ,
CREATURE_TYPE_GAS_CLOUD = 13
}
enum CreatureFamily {
CREATURE_FAMILY_WOLF = 1 , CREATURE_FAMILY_CAT = 2 , CREATURE_FAMILY_SPIDER = 3 , CREATURE_FAMILY_BEAR = 4 ,
CREATURE_FAMILY_BOAR = 5 , CREATURE_FAMILY_CROCOLISK = 6 , CREATURE_FAMILY_CARRION_BIRD = 7 , CREATURE_FAMILY_CRAB = 8 ,
CREATURE_FAMILY_GORILLA = 9 , CREATURE_FAMILY_HORSE_CUSTOM = 10 , CREATURE_FAMILY_RAPTOR = 11 , CREATURE_FAMILY_TALLSTRIDER = 12 ,
CREATURE_FAMILY_FELHUNTER = 15 , CREATURE_FAMILY_VOIDWALKER = 16 , CREATURE_FAMILY_SUCCUBUS = 17 , CREATURE_FAMILY_DOOMGUARD = 19 ,
CREATURE_FAMILY_SCORPID = 20 , CREATURE_FAMILY_TURTLE = 21 , CREATURE_FAMILY_IMP = 23 , CREATURE_FAMILY_BAT = 24 ,
CREATURE_FAMILY_HYENA = 25 , CREATURE_FAMILY_BIRD_OF_PREY = 26 , CREATURE_FAMILY_WIND_SERPENT = 27 , CREATURE_FAMILY_REMOTE_CONTROL = 28 ,
CREATURE_FAMILY_FELGUARD = 29 , CREATURE_FAMILY_DRAGONHAWK = 30 , CREATURE_FAMILY_RAVAGER = 31 , CREATURE_FAMILY_WARP_STALKER = 32 ,
CREATURE_FAMILY_SPOREBAT = 33 , CREATURE_FAMILY_NETHER_RAY = 34 , CREATURE_FAMILY_SERPENT = 35 , CREATURE_FAMILY_MOTH = 37 ,
CREATURE_FAMILY_CHIMAERA = 38 , CREATURE_FAMILY_DEVILSAUR = 39 , CREATURE_FAMILY_GHOUL = 40 , CREATURE_FAMILY_SILITHID = 41 ,
CREATURE_FAMILY_WORM = 42 , CREATURE_FAMILY_RHINO = 43 , CREATURE_FAMILY_WASP = 44 , CREATURE_FAMILY_CORE_HOUND = 45 ,
CREATURE_FAMILY_SPIRIT_BEAST = 46
}
enum CreatureTypeFlags {
CREATURE_TYPEFLAGS_TAMEABLE = 0x00000001 , CREATURE_TYPEFLAGS_GHOST_VISIBLE = 0x00000002 , CREATURE_TYPEFLAGS_UNK3 = 0x00000004 , CREATURE_TYPEFLAGS_UNK4 = 0x00000008 ,
CREATURE_TYPEFLAGS_UNK5 = 0x00000010 , CREATURE_TYPEFLAGS_UNK6 = 0x00000020 , CREATURE_TYPEFLAGS_UNK7 = 0x00000040 , CREATURE_TYPEFLAGS_INTERACT_DEAD = 0x00000080 ,
CREATURE_TYPEFLAGS_HERBLOOT = 0x00000100 , CREATURE_TYPEFLAGS_MININGLOOT = 0x00000200 , CREATURE_TYPEFLAGS_UNK11 = 0x00000400 , CREATURE_TYPEFLAGS_MOUNTED_COMBAT = 0x00000800 ,
CREATURE_TYPEFLAGS_CAN_ASSIST = 0x00001000 , CREATURE_TYPEFLAGS_UNK14 = 0x00002000 , CREATURE_TYPEFLAGS_UNK15 = 0x00004000 , CREATURE_TYPEFLAGS_ENGINEERLOOT = 0x00008000 ,
CREATURE_TYPEFLAGS_EXOTIC = 0x00010000 , CREATURE_TYPEFLAGS_UNK18 = 0x00020000 , CREATURE_TYPEFLAGS_SIEGE_WEAPON = 0x00040000 , CREATURE_TYPEFLAGS_UNK20 = 0x00080000 ,
CREATURE_TYPEFLAGS_UNK21 = 0x00100000 , CREATURE_TYPEFLAGS_UNK22 = 0x00200000 , CREATURE_TYPEFLAGS_UNK23 = 0x00400000 , CREATURE_TYPEFLAGS_SQUIRE = 0x00800000 ,
CREATURE_TYPEFLAGS_UNK25 = 0x01000000 , CREATURE_TYPEFLAGS_UNK26 = 0x02000000 , CREATURE_TYPEFLAGS_TREAT_AS_IN_RAID = 0x04000000 , CREATURE_TYPEFLAGS_UNK28 = 0x08000000 ,
CREATURE_TYPEFLAGS_UNK29 = 0x10000000 , CREATURE_TYPEFLAGS_UNK30 = 0x20000000 , CREATURE_TYPEFLAGS_UNK31 = 0x40000000 , CREATURE_TYPEFLAGS_QUEST_BOSS = 0x80000000
}
enum CreatureEliteType {
CREATURE_ELITE_NORMAL = 0 , CREATURE_ELITE_ELITE = 1 , CREATURE_ELITE_RAREELITE = 2 , CREATURE_ELITE_WORLDBOSS = 3 ,
CREATURE_ELITE_RARE = 4 , CREATURE_UNKNOWN = 5
}
enum HolidayIds {
HOLIDAY_NONE = 0 , HOLIDAY_FIREWORKS_SPECTACULAR = 62 , HOLIDAY_FEAST_OF_WINTER_VEIL = 141 , HOLIDAY_NOBLEGARDEN = 181 ,
HOLIDAY_CHILDRENS_WEEK = 201 , HOLIDAY_CALL_TO_ARMS_AV = 283 , HOLIDAY_CALL_TO_ARMS_WS = 284 , HOLIDAY_CALL_TO_ARMS_AB = 285 ,
HOLIDAY_FISHING_EXTRAVAGANZA = 301 , HOLIDAY_HARVEST_FESTIVAL = 321 , HOLIDAY_HALLOWS_END = 324 , HOLIDAY_LUNAR_FESTIVAL = 327 ,
HOLIDAY_FIRE_FESTIVAL = 341 , HOLIDAY_CALL_TO_ARMS_EY = 353 , HOLIDAY_BREWFEST = 372 , HOLIDAY_DARKMOON_FAIRE_ELWYNN = 374 ,
HOLIDAY_DARKMOON_FAIRE_THUNDER = 375 , HOLIDAY_DARKMOON_FAIRE_SHATTRATH = 376 , HOLIDAY_PIRATES_DAY = 398 , HOLIDAY_CALL_TO_ARMS_SA = 400 ,
HOLIDAY_PILGRIMS_BOUNTY = 404 , HOLIDAY_WOTLK_LAUNCH = 406 , HOLIDAY_DAY_OF_DEAD = 409 , HOLIDAY_CALL_TO_ARMS_ISLE_OF_C = 420 ,
HOLIDAY_LOVE_IS_IN_THE_AIR = 423
}
enum QuestSort {
QUEST_SORT_EPIC = 1 , QUEST_SORT_WAILING_CAVERNS_OLD = 21 , QUEST_SORT_SEASONAL = 22 , QUEST_SORT_UNDERCITY_OLD = 23 ,
QUEST_SORT_HERBALISM = 24 , QUEST_SORT_BATTLEGROUNDS = 25 , QUEST_SORT_ULDAMN_OLD = 41 , QUEST_SORT_WARLOCK = 61 ,
QUEST_SORT_WARRIOR = 81 , QUEST_SORT_SHAMAN = 82 , QUEST_SORT_FISHING = 101 , QUEST_SORT_BLACKSMITHING = 121 ,
QUEST_SORT_PALADIN = 141 , QUEST_SORT_MAGE = 161 , QUEST_SORT_ROGUE = 162 , QUEST_SORT_ALCHEMY = 181 ,
QUEST_SORT_LEATHERWORKING = 182 , QUEST_SORT_ENGINEERING = 201 , QUEST_SORT_TREASURE_MAP = 221 , QUEST_SORT_SUNKEN_TEMPLE_OLD = 241 ,
QUEST_SORT_HUNTER = 261 , QUEST_SORT_PRIEST = 262 , QUEST_SORT_DRUID = 263 , QUEST_SORT_TAILORING = 264 ,
QUEST_SORT_SPECIAL = 284 , QUEST_SORT_COOKING = 304 , QUEST_SORT_FIRST_AID = 324 , QUEST_SORT_LEGENDARY = 344 ,
QUEST_SORT_DARKMOON_FAIRE = 364 , QUEST_SORT_AHN_QIRAJ_WAR = 365 , QUEST_SORT_LUNAR_FESTIVAL = 366 , QUEST_SORT_REPUTATION = 367 ,
QUEST_SORT_INVASION = 368 , QUEST_SORT_MIDSUMMER = 369 , QUEST_SORT_BREWFEST = 370 , QUEST_SORT_INSCRIPTION = 371 ,
QUEST_SORT_DEATH_KNIGHT = 372 , QUEST_SORT_JEWELCRAFTING = 373 , QUEST_SORT_NOBLEGARDEN = 374 , QUEST_SORT_PILGRIMS_BOUNTY = 375 ,
QUEST_SORT_LOVE_IS_IN_THE_AIR = 376
}
enum SkillType {
SKILL_NONE = 0 , SKILL_FROST = 6 , SKILL_FIRE = 8 , SKILL_ARMS = 26 ,
SKILL_COMBAT = 38 , SKILL_SUBTLETY = 39 , SKILL_SWORDS = 43 , SKILL_AXES = 44 ,
SKILL_BOWS = 45 , SKILL_GUNS = 46 , SKILL_BEAST_MASTERY = 50 , SKILL_SURVIVAL = 51 ,
SKILL_MACES = 54 , SKILL_2H_SWORDS = 55 , SKILL_HOLY = 56 , SKILL_SHADOW = 78 ,
SKILL_DEFENSE = 95 , SKILL_LANG_COMMON = 98 , SKILL_RACIAL_DWARVEN = 101 , SKILL_LANG_ORCISH = 109 ,
SKILL_LANG_DWARVEN = 111 , SKILL_LANG_DARNASSIAN = 113 , SKILL_LANG_TAURAHE = 115 , SKILL_DUAL_WIELD = 118 ,
SKILL_RACIAL_TAUREN = 124 , SKILL_ORC_RACIAL = 125 , SKILL_RACIAL_NIGHT_ELF = 126 , SKILL_FIRST_AID = 129 ,
SKILL_FERAL_COMBAT = 134 , SKILL_STAVES = 136 , SKILL_LANG_THALASSIAN = 137 , SKILL_LANG_DRACONIC = 138 ,
SKILL_LANG_DEMON_TONGUE = 139 , SKILL_LANG_TITAN = 140 , SKILL_LANG_OLD_TONGUE = 141 , SKILL_SURVIVAL2 = 142 ,
SKILL_RIDING_HORSE = 148 , SKILL_RIDING_WOLF = 149 , SKILL_RIDING_TIGER = 150 , SKILL_RIDING_RAM = 152 ,
SKILL_SWIMING = 155 , SKILL_2H_MACES = 160 , SKILL_UNARMED = 162 , SKILL_MARKSMANSHIP = 163 ,
SKILL_BLACKSMITHING = 164 , SKILL_LEATHERWORKING = 165 , SKILL_ALCHEMY = 171 , SKILL_2H_AXES = 172 ,
SKILL_DAGGERS = 173 , SKILL_THROWN = 176 , SKILL_HERBALISM = 182 , SKILL_GENERIC_DND = 183 ,
SKILL_RETRIBUTION = 184 , SKILL_COOKING = 185 , SKILL_MINING = 186 , SKILL_PET_IMP = 188 ,
SKILL_PET_FELHUNTER = 189 , SKILL_TAILORING = 197 , SKILL_ENGINEERING = 202 , SKILL_PET_SPIDER = 203 ,
SKILL_PET_VOIDWALKER = 204 , SKILL_PET_SUCCUBUS = 205 , SKILL_PET_INFERNAL = 206 , SKILL_PET_DOOMGUARD = 207 ,
SKILL_PET_WOLF = 208 , SKILL_PET_CAT = 209 , SKILL_PET_BEAR = 210 , SKILL_PET_BOAR = 211 ,
SKILL_PET_CROCILISK = 212 , SKILL_PET_CARRION_BIRD = 213 , SKILL_PET_CRAB = 214 , SKILL_PET_GORILLA = 215 ,
SKILL_PET_RAPTOR = 217 , SKILL_PET_TALLSTRIDER = 218 , SKILL_RACIAL_UNDED = 220 , SKILL_CROSSBOWS = 226 ,
SKILL_WANDS = 228 , SKILL_POLEARMS = 229 , SKILL_PET_SCORPID = 236 , SKILL_ARCANE = 237 ,
SKILL_PET_TURTLE = 251 , SKILL_ASSASSINATION = 253 , SKILL_FURY = 256 , SKILL_PROTECTION = 257 ,
SKILL_PROTECTION2 = 267 , SKILL_PET_TALENTS = 270 , SKILL_PLATE_MAIL = 293 , SKILL_LANG_GNOMISH = 313 ,
SKILL_LANG_TROLL = 315 , SKILL_ENCHANTING = 333 , SKILL_DEMONOLOGY = 354 , SKILL_AFFLICTION = 355 ,
SKILL_FISHING = 356 , SKILL_ENHANCEMENT = 373 , SKILL_RESTORATION = 374 , SKILL_ELEMENTAL_COMBAT = 375 ,
SKILL_SKINNING = 393 , SKILL_MAIL = 413 , SKILL_LEATHER = 414 , SKILL_CLOTH = 415 ,
SKILL_SHIELD = 433 , SKILL_FIST_WEAPONS = 473 , SKILL_RIDING_RAPTOR = 533 , SKILL_RIDING_MECHANOSTRIDER = 553 ,
SKILL_RIDING_UNDEAD_HORSE = 554 , SKILL_RESTORATION2 = 573 , SKILL_BALANCE = 574 , SKILL_DESTRUCTION = 593 ,
SKILL_HOLY2 = 594 , SKILL_DISCIPLINE = 613 , SKILL_LOCKPICKING = 633 , SKILL_PET_BAT = 653 ,
SKILL_PET_HYENA = 654 , SKILL_PET_BIRD_OF_PREY = 655 , SKILL_PET_WIND_SERPENT = 656 , SKILL_LANG_GUTTERSPEAK = 673 ,
SKILL_RIDING_KODO = 713 , SKILL_RACIAL_TROLL = 733 , SKILL_RACIAL_GNOME = 753 , SKILL_RACIAL_HUMAN = 754 ,
SKILL_JEWELCRAFTING = 755 , SKILL_RACIAL_BLOODELF = 756 , SKILL_PET_EVENT_RC = 758 , SKILL_LANG_DRAENEI = 759 ,
SKILL_RACIAL_DRAENEI = 760 , SKILL_PET_FELGUARD = 761 , SKILL_RIDING = 762 , SKILL_PET_DRAGONHAWK = 763 ,
SKILL_PET_NETHER_RAY = 764 , SKILL_PET_SPOREBAT = 765 , SKILL_PET_WARP_STALKER = 766 , SKILL_PET_RAVAGER = 767 ,
SKILL_PET_SERPENT = 768 , SKILL_INTERNAL = 769 , SKILL_DK_BLOOD = 770 , SKILL_DK_FROST = 771 ,
SKILL_DK_UNHOLY = 772 , SKILL_INSCRIPTION = 773 , SKILL_PET_MOTH = 775 , SKILL_RUNEFORGING = 776 ,
SKILL_MOUNTS = 777 , SKILL_COMPANIONS = 778 , SKILL_PET_EXOTIC_CHIMAERA = 780 , SKILL_PET_EXOTIC_DEVILSAUR = 781 ,
SKILL_PET_GHOUL = 782 , SKILL_PET_EXOTIC_SILITHID = 783 , SKILL_PET_EXOTIC_WORM = 784 , SKILL_PET_WASP = 785 ,
SKILL_PET_EXOTIC_RHINO = 786 , SKILL_PET_EXOTIC_CORE_HOUND = 787 , SKILL_PET_EXOTIC_SPIRIT_BEAST = 788
}
enum SkillCategory {
SKILL_CATEGORY_ATTRIBUTES = 5 , SKILL_CATEGORY_WEAPON = 6 , SKILL_CATEGORY_CLASS = 7 , SKILL_CATEGORY_ARMOR = 8 ,
SKILL_CATEGORY_SECONDARY = 9 , SKILL_CATEGORY_LANGUAGES = 10 , SKILL_CATEGORY_PROFESSION = 11 , SKILL_CATEGORY_GENERIC = 12
}
enum TotemCategory {
TC_SKINNING_SKIFE_OLD = 1 , TC_EARTH_TOTEM = 2 , TC_AIR_TOTEM = 3 , TC_FIRE_TOTEM = 4 ,
TC_WATER_TOTEM = 5 , TC_COPPER_ROD = 6 , TC_SILVER_ROD = 7 , TC_GOLDEN_ROD = 8 ,
TC_TRUESILVER_ROD = 9 , TC_ARCANITE_ROD = 10 , TC_MINING_PICK_OLD = 11 , TC_PHILOSOPHERS_STONE = 12 ,
TC_BLACKSMITH_HAMMER_OLD = 13 , TC_ARCLIGHT_SPANNER = 14 , TC_GYROMATIC_MA = 15 , TC_MASTER_TOTEM = 21 ,
TC_FEL_IRON_ROD = 41 , TC_ADAMANTITE_ROD = 62 , TC_ETERNIUM_ROD = 63 , TC_HOLLOW_QUILL = 81 ,
TC_RUNED_AZURITE_ROD = 101 , TC_VIRTUOSO_INKING_SET = 121 , TC_DRUMS = 141 , TC_GNOMISH_ARMY_KNIFE = 161 ,
TC_BLACKSMITH_HAMMER = 162 , TC_MINING_PICK = 165 , TC_SKINNING_KNIFE = 166 , TC_HAMMER_PICK = 167 ,
TC_BLADED_PICKAXE = 168 , TC_FLINT_AND_TINDER = 169 , TC_RUNED_COBALT_ROD = 189 , TC_RUNED_TITANIUM_ROD = 190
}
enum UnitDynFlags {
UNIT_DYNFLAG_NONE = 0x0000 , UNIT_DYNFLAG_LOOTABLE = 0x0001 , UNIT_DYNFLAG_TRACK_UNIT = 0x0002 , UNIT_DYNFLAG_TAPPED = 0x0004 ,
UNIT_DYNFLAG_TAPPED_BY_PLAYER = 0x0008 , UNIT_DYNFLAG_SPECIALINFO = 0x0010 , UNIT_DYNFLAG_DEAD = 0x0020 , UNIT_DYNFLAG_REFER_A_FRIEND = 0x0040 ,
UNIT_DYNFLAG_TAPPED_BY_ALL_THREAT_LIST = 0x0080
}
enum CorpseDynFlags { CORPSE_DYNFLAG_LOOTABLE = 0x0001 }
enum WeatherType {
WEATHER_TYPE_FINE = 0 , WEATHER_TYPE_RAIN = 1 , WEATHER_TYPE_SNOW = 2 , WEATHER_TYPE_STORM = 3 ,
WEATHER_TYPE_THUNDERS = 86 , WEATHER_TYPE_BLACKRAIN = 90
}
enum ChatMsg {
CHAT_MSG_ADDON = 0xFFFFFFFF , CHAT_MSG_SYSTEM = 0x00 , CHAT_MSG_SAY = 0x01 , CHAT_MSG_PARTY = 0x02 ,
CHAT_MSG_RAID = 0x03 , CHAT_MSG_GUILD = 0x04 , CHAT_MSG_OFFICER = 0x05 , CHAT_MSG_YELL = 0x06 ,
CHAT_MSG_WHISPER = 0x07 , CHAT_MSG_WHISPER_FOREIGN = 0x08 , CHAT_MSG_WHISPER_INFORM = 0x09 , CHAT_MSG_EMOTE = 0x0A ,
CHAT_MSG_TEXT_EMOTE = 0x0B , CHAT_MSG_MONSTER_SAY = 0x0C , CHAT_MSG_MONSTER_PARTY = 0x0D , CHAT_MSG_MONSTER_YELL = 0x0E ,
CHAT_MSG_MONSTER_WHISPER = 0x0F , CHAT_MSG_MONSTER_EMOTE = 0x10 , CHAT_MSG_CHANNEL = 0x11 , CHAT_MSG_CHANNEL_JOIN = 0x12 ,
CHAT_MSG_CHANNEL_LEAVE = 0x13 , CHAT_MSG_CHANNEL_LIST = 0x14 , CHAT_MSG_CHANNEL_NOTICE = 0x15 , CHAT_MSG_CHANNEL_NOTICE_USER = 0x16 ,
CHAT_MSG_AFK = 0x17 , CHAT_MSG_DND = 0x18 , CHAT_MSG_IGNORED = 0x19 , CHAT_MSG_SKILL = 0x1A ,
CHAT_MSG_LOOT = 0x1B , CHAT_MSG_MONEY = 0x1C , CHAT_MSG_OPENING = 0x1D , CHAT_MSG_TRADESKILLS = 0x1E ,
CHAT_MSG_PET_INFO = 0x1F , CHAT_MSG_COMBAT_MISC_INFO = 0x20 , CHAT_MSG_COMBAT_XP_GAIN = 0x21 , CHAT_MSG_COMBAT_HONOR_GAIN = 0x22 ,
CHAT_MSG_COMBAT_FACTION_CHANGE = 0x23 , CHAT_MSG_BG_SYSTEM_NEUTRAL = 0x24 , CHAT_MSG_BG_SYSTEM_ALLIANCE = 0x25 , CHAT_MSG_BG_SYSTEM_HORDE = 0x26 ,
CHAT_MSG_RAID_LEADER = 0x27 , CHAT_MSG_RAID_WARNING = 0x28 , CHAT_MSG_RAID_BOSS_EMOTE = 0x29 , CHAT_MSG_RAID_BOSS_WHISPER = 0x2A ,
CHAT_MSG_FILTERED = 0x2B , CHAT_MSG_BATTLEGROUND = 0x2C , CHAT_MSG_BATTLEGROUND_LEADER = 0x2D , CHAT_MSG_RESTRICTED = 0x2E ,
CHAT_MSG_BNET = 0x2F , CHAT_MSG_ACHIEVEMENT = 0x30 , CHAT_MSG_GUILD_ACHIEVEMENT = 0x31 , CHAT_MSG_ARENA_POINTS = 0x32 ,
CHAT_MSG_PARTY_LEADER = 0x33
}
enum ChatLinkColors {
CHAT_LINK_COLOR_TRADE = 0xffffd000 , CHAT_LINK_COLOR_TALENT = 0xff4e96f7 , CHAT_LINK_COLOR_SPELL = 0xff71d5ff , CHAT_LINK_COLOR_ENCHANT = 0xffffd000 ,
CHAT_LINK_COLOR_ACHIEVEMENT = 0xffffff00 , CHAT_LINK_COLOR_GLYPH = 0xff66bbff
}
enum PetDiet {
PET_DIET_MEAT = 1 , PET_DIET_FISH = 2 , PET_DIET_CHEESE = 3 , PET_DIET_BREAD = 4 ,
PET_DIET_FUNGAS = 5 , PET_DIET_FRUIT = 6 , PET_DIET_RAW_MEAT = 7 , PET_DIET_RAW_FISH = 8
}
enum AiReaction {
AI_REACTION_ALERT = 0 , AI_REACTION_FRIENDLY = 1 , AI_REACTION_HOSTILE = 2 , AI_REACTION_AFRAID = 3 ,
AI_REACTION_DESTROY = 4
}
enum DiminishingReturnsType { DRTYPE_NONE = 0 , DRTYPE_PLAYER = 1 , DRTYPE_ALL = 2 }
enum DiminishingGroup {
DIMINISHING_NONE , DIMINISHING_CONTROL_STUN , DIMINISHING_TRIGGER_STUN , DIMINISHING_CONTROL_ROOT ,
DIMINISHING_TRIGGER_ROOT , DIMINISHING_FEAR_CHARM_BLIND , DIMINISHING_DISORIENT , DIMINISHING_HORROR ,
DIMINISHING_CYCLONE , DIMINISHING_CHEAPSHOT_POUNCE , DIMINISHING_DISARM , DIMINISHING_SILENCE ,
DIMINISHING_FREEZE_SLEEP , DIMINISHING_BANISH , DIMINISHING_LIMITONLY
}
enum InstanceResetMethod {
INSTANCE_RESET_ALL , INSTANCE_RESET_CHANGE_DIFFICULTY , INSTANCE_RESET_GLOBAL , INSTANCE_RESET_GROUP_DISBAND ,
INSTANCE_RESET_GROUP_JOIN , INSTANCE_RESET_RESPAWN_DELAY
}
enum ShapeshiftForm {
FORM_NONE = 0x00 , FORM_CAT = 0x01 , FORM_TREE = 0x02 , FORM_TRAVEL = 0x03 ,
FORM_AQUA = 0x04 , FORM_BEAR = 0x05 , FORM_AMBIENT = 0x06 , FORM_GHOUL = 0x07 ,
FORM_DIREBEAR = 0x08 , FORM_STEVES_GHOUL = 0x09 , FORM_THARONJA_SKELETON = 0x0A , FORM_TEST_OF_STRENGTH = 0x0B ,
FORM_BLB_PLAYER = 0x0C , FORM_SHADOW_DANCE = 0x0D , FORM_CREATUREBEAR = 0x0E , FORM_CREATURECAT = 0x0F ,
FORM_GHOSTWOLF = 0x10 , FORM_BATTLESTANCE = 0x11 , FORM_DEFENSIVESTANCE = 0x12 , FORM_BERSERKERSTANCE = 0x13 ,
FORM_TEST = 0x14 , FORM_ZOMBIE = 0x15 , FORM_METAMORPHOSIS = 0x16 , FORM_UNDEAD = 0x19 ,
FORM_FRENZY = 0x1A , FORM_FLIGHT_EPIC = 0x1B , FORM_SHADOW = 0x1C , FORM_FLIGHT = 0x1D ,
FORM_STEALTH = 0x1E , FORM_MOONKIN = 0x1F , FORM_SPIRITOFREDEMPTION = 0x20
}
enum ShapeshiftFlags {
SHAPESHIFT_FLAG_STANCE = 0x00000001 , SHAPESHIFT_FLAG_NOT_TOGGLEABLE = 0x00000002 , SHAPESHIFT_FLAG_PERSIST_ON_DEATH = 0x00000004 , SHAPESHIFT_FLAG_CAN_NPC_INTERACT = 0x00000008 ,
SHAPESHIFT_FLAG_DONT_USE_WEAPON = 0x00000010 , SHAPESHIFT_FLAG_AGILITY_ATTACK_BONUS = 0x00000020 , SHAPESHIFT_FLAG_CAN_USE_EQUIPPED_ITEMS = 0x00000040 , SHAPESHIFT_FLAG_CAN_USE_ITEMS = 0x00000080 ,
SHAPESHIFT_FLAG_DONT_AUTO_UNSHIFT = 0x00000100 , SHAPESHIFT_FLAG_CONSIDERED_DEAD = 0x00000200 , SHAPESHIFT_FLAG_CAN_ONLY_CAST_SHAPESHIFT_SPELLS = 0x00000400 , SHAPESHIFT_FLAG_STANCE_CANCEL_AT_FLIGHTMASTER = 0x00000800 ,
SHAPESHIFT_FLAG_NO_EMOTE_SOUNDS = 0x00001000 , SHAPESHIFT_FLAG_NO_TRIGGER_TELEPORT = 0x00002000 , SHAPESHIFT_FLAG_CANNOT_CHANGE_EQUIPPED_ITEMS = 0x00004000 , SHAPESHIFT_FLAG_RESUMMON_PETS_ON_UNSHIFT = 0x00008000 ,
SHAPESHIFT_FLAG_CANNOT_USE_GAME_OBJECTS = 0x00010000
}
enum CharLoginFailReasons {
CHAR_LOGIN_NO_WORLD = 0x01 , CHAR_LOGIN_DUPLICATE_CHARACTER = 0x02 , CHAR_LOGIN_NO_INSTANCES = 0x03 , CHAR_LOGIN_DISABLED = 0x04 ,
CHAR_LOGIN_NO_CHARACTER = 0x05 , CHAR_LOGIN_LOCKED_FOR_TRANSFER = 0x06 , CHAR_LOGIN_LOCKED_BY_BILLING = 0x07 , CHAR_LOGIN_FAILED = 0x08
}
enum ResponseCodes {
RESPONSE_SUCCESS = 0x00 , RESPONSE_FAILURE = 0x01 , RESPONSE_CANCELLED = 0x02 , RESPONSE_DISCONNECTED = 0x03 ,
RESPONSE_FAILED_TO_CONNECT = 0x04 , RESPONSE_CONNECTED = 0x05 , RESPONSE_VERSION_MISMATCH = 0x06 , CSTATUS_CONNECTING = 0x07 ,
CSTATUS_NEGOTIATING_SECURITY = 0x08 , CSTATUS_NEGOTIATION_COMPLETE = 0x09 , CSTATUS_NEGOTIATION_FAILED = 0x0A , CSTATUS_AUTHENTICATING = 0x0B ,
AUTH_OK = 0x0C , AUTH_FAILED = 0x0D , AUTH_REJECT = 0x0E , AUTH_BAD_SERVER_PROOF = 0x0F ,
AUTH_UNAVAILABLE = 0x10 , AUTH_SYSTEM_ERROR = 0x11 , AUTH_BILLING_ERROR = 0x12 , AUTH_BILLING_EXPIRED = 0x13 ,
AUTH_VERSION_MISMATCH = 0x14 , AUTH_UNKNOWN_ACCOUNT = 0x15 , AUTH_INCORRECT_PASSWORD = 0x16 , AUTH_SESSION_EXPIRED = 0x17 ,
AUTH_SERVER_SHUTTING_DOWN = 0x18 , AUTH_ALREADY_LOGGING_IN = 0x19 , AUTH_LOGIN_SERVER_NOT_FOUND = 0x1A , AUTH_WAIT_QUEUE = 0x1B ,
AUTH_BANNED = 0x1C , AUTH_ALREADY_ONLINE = 0x1D , AUTH_NO_TIME = 0x1E , AUTH_DB_BUSY = 0x1F ,
AUTH_SUSPENDED = 0x20 , AUTH_PARENTAL_CONTROL = 0x21 , AUTH_LOCKED_ENFORCED = 0x22 , REALM_LIST_IN_PROGRESS = 0x23 ,
REALM_LIST_SUCCESS = 0x24 , REALM_LIST_FAILED = 0x25 , REALM_LIST_INVALID = 0x26 , REALM_LIST_REALM_NOT_FOUND = 0x27 ,
ACCOUNT_CREATE_IN_PROGRESS = 0x28 , ACCOUNT_CREATE_SUCCESS = 0x29 , ACCOUNT_CREATE_FAILED = 0x2A , CHAR_LIST_RETRIEVING = 0x2B ,
CHAR_LIST_RETRIEVED = 0x2C , CHAR_LIST_FAILED = 0x2D , CHAR_CREATE_IN_PROGRESS = 0x2E , CHAR_CREATE_SUCCESS = 0x2F ,
CHAR_CREATE_ERROR = 0x30 , CHAR_CREATE_FAILED = 0x31 , CHAR_CREATE_NAME_IN_USE = 0x32 , CHAR_CREATE_DISABLED = 0x33 ,
CHAR_CREATE_PVP_TEAMS_VIOLATION = 0x34 , CHAR_CREATE_SERVER_LIMIT = 0x35 , CHAR_CREATE_ACCOUNT_LIMIT = 0x36 , CHAR_CREATE_SERVER_QUEUE = 0x37 ,
CHAR_CREATE_ONLY_EXISTING = 0x38 , CHAR_CREATE_EXPANSION = 0x39 , CHAR_CREATE_EXPANSION_CLASS = 0x3A , CHAR_CREATE_LEVEL_REQUIREMENT = 0x3B ,
CHAR_CREATE_UNIQUE_CLASS_LIMIT = 0x3C , CHAR_CREATE_CHARACTER_IN_GUILD = 0x3D , CHAR_CREATE_RESTRICTED_RACECLASS = 0x3E , CHAR_CREATE_CHARACTER_CHOOSE_RACE = 0x3F ,
CHAR_CREATE_CHARACTER_ARENA_LEADER = 0x40 , CHAR_CREATE_CHARACTER_DELETE_MAIL = 0x41 , CHAR_CREATE_CHARACTER_SWAP_FACTION = 0x42 , CHAR_CREATE_CHARACTER_RACE_ONLY = 0x43 ,
CHAR_CREATE_CHARACTER_GOLD_LIMIT = 0x44 , CHAR_CREATE_FORCE_LOGIN = 0x45 , CHAR_DELETE_IN_PROGRESS = 0x46 , CHAR_DELETE_SUCCESS = 0x47 ,
CHAR_DELETE_FAILED = 0x48 , CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER = 0x49 , CHAR_DELETE_FAILED_GUILD_LEADER = 0x4A , CHAR_DELETE_FAILED_ARENA_CAPTAIN = 0x4B ,
CHAR_NAME_SUCCESS = 0x57 , CHAR_NAME_FAILURE = 0x58 , CHAR_NAME_NO_NAME = 0x59 , CHAR_NAME_TOO_SHORT = 0x5A ,
CHAR_NAME_TOO_LONG = 0x5B , CHAR_NAME_INVALID_CHARACTER = 0x5C , CHAR_NAME_MIXED_LANGUAGES = 0x5D , CHAR_NAME_PROFANE = 0x5E ,
CHAR_NAME_RESERVED = 0x5F , CHAR_NAME_INVALID_APOSTROPHE = 0x60 , CHAR_NAME_MULTIPLE_APOSTROPHES = 0x61 , CHAR_NAME_THREE_CONSECUTIVE = 0x62 ,
CHAR_NAME_INVALID_SPACE = 0x63 , CHAR_NAME_CONSECUTIVE_SPACES = 0x64 , CHAR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS = 0x65 , CHAR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END = 0x66 ,
CHAR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME = 0x67
}
enum BanMode { BAN_ACCOUNT , BAN_CHARACTER , BAN_IP }
Ban function modes.
enum BanReturn { BAN_SUCCESS , BAN_SYNTAX_ERROR , BAN_NOTFOUND }
Ban function return codes.
enum BattleGroundTypeId {
BATTLEGROUND_TYPE_NONE = 0 , BATTLEGROUND_AV = 1 , BATTLEGROUND_WS = 2 , BATTLEGROUND_AB = 3 ,
BATTLEGROUND_NA = 4 , BATTLEGROUND_BE = 5 , BATTLEGROUND_AA = 6 , BATTLEGROUND_EY = 7 ,
BATTLEGROUND_RL = 8 , BATTLEGROUND_SA = 9 , BATTLEGROUND_DS = 10 , BATTLEGROUND_RV = 11 ,
BATTLEGROUND_IC = 30 , BATTLEGROUND_RB = 32
}
enum ArenaType { ARENA_TYPE_NONE = 0 , ARENA_TYPE_2v2 = 2 , ARENA_TYPE_3v3 = 3 , ARENA_TYPE_5v5 = 5 }
enum MailResponseType {
MAIL_SEND = 0 , MAIL_MONEY_TAKEN = 1 , MAIL_ITEM_TAKEN = 2 , MAIL_RETURNED_TO_SENDER = 3 ,
MAIL_DELETED = 4 , MAIL_MADE_PERMANENT = 5
}
enum MailResponseResult {
MAIL_OK = 0 , MAIL_ERR_EQUIP_ERROR = 1 , MAIL_ERR_CANNOT_SEND_TO_SELF = 2 , MAIL_ERR_NOT_ENOUGH_MONEY = 3 ,
MAIL_ERR_RECIPIENT_NOT_FOUND = 4 , MAIL_ERR_NOT_YOUR_TEAM = 5 , MAIL_ERR_INTERNAL_ERROR = 6 , MAIL_ERR_DISABLED_FOR_TRIAL_ACC = 14 ,
MAIL_ERR_RECIPIENT_CAP_REACHED = 15 , MAIL_ERR_CANT_SEND_WRAPPED_COD = 16 , MAIL_ERR_MAIL_AND_CHAT_SUSPENDED = 17 , MAIL_ERR_TOO_MANY_ATTACHMENTS = 18 ,
MAIL_ERR_MAIL_ATTACHMENT_INVALID = 19 , MAIL_ERR_ITEM_HAS_EXPIRED = 21
}
enum PetTameFailureReason {
PETTAME_INVALIDCREATURE = 1 , PETTAME_TOOMANY = 2 , PETTAME_CREATUREALREADYOWNED = 3 , PETTAME_NOTTAMEABLE = 4 ,
PETTAME_ANOTHERSUMMONACTIVE = 5 , PETTAME_UNITSCANTTAME = 6 , PETTAME_NOPETAVAILABLE = 7 , PETTAME_INTERNALERROR = 8 ,
PETTAME_TOOHIGHLEVEL = 9 , PETTAME_DEAD = 10 , PETTAME_NOTDEAD = 11 , PETTAME_CANTCONTROLEXOTIC = 12 ,
PETTAME_UNKNOWNERROR = 13
}
enum TotemSlot { TOTEM_SLOT_FIRE = 0 , TOTEM_SLOT_EARTH = 1 , TOTEM_SLOT_WATER = 2 , TOTEM_SLOT_AIR = 3 }
enum TradeStatus {
TRADE_STATUS_BUSY = 0 , TRADE_STATUS_BEGIN_TRADE = 1 , TRADE_STATUS_OPEN_WINDOW = 2 , TRADE_STATUS_TRADE_CANCELED = 3 ,
TRADE_STATUS_TRADE_ACCEPT = 4 , TRADE_STATUS_BUSY_2 = 5 , TRADE_STATUS_NO_TARGET = 6 , TRADE_STATUS_BACK_TO_TRADE = 7 ,
TRADE_STATUS_TRADE_COMPLETE = 8 , TRADE_STATUS_TRADE_REJECTED = 9 , TRADE_STATUS_TARGET_TO_FAR = 10 , TRADE_STATUS_WRONG_FACTION = 11 ,
TRADE_STATUS_CLOSE_WINDOW = 12 , TRADE_STATUS_IGNORE_YOU = 14 , TRADE_STATUS_YOU_STUNNED = 15 , TRADE_STATUS_TARGET_STUNNED = 16 ,
TRADE_STATUS_YOU_DEAD = 17 , TRADE_STATUS_TARGET_DEAD = 18 , TRADE_STATUS_YOU_LOGOUT = 19 , TRADE_STATUS_TARGET_LOGOUT = 20 ,
TRADE_STATUS_TRIAL_ACCOUNT = 21 , TRADE_STATUS_WRONG_REALM = 22 , TRADE_STATUS_NOT_ON_TAPLIST = 23
}
enum EncounterCreditType { ENCOUNTER_CREDIT_KILL_CREATURE = 0 , ENCOUNTER_CREDIT_CAST_SPELL = 1 , ENCOUNTER_CREDIT_SCRIPT = 2 }
enum WorldStateType { WORLD_STATE_REMOVE = 0 , WORLD_STATE_ADD = 1 }
enum ActivateTaxiReply {
ERR_TAXIOK = 0 , ERR_TAXIUNSPECIFIEDSERVERERROR = 1 , ERR_TAXINOSUCHPATH = 2 , ERR_TAXINOTENOUGHMONEY = 3 ,
ERR_TAXITOOFARAWAY = 4 , ERR_TAXINOVENDORNEARBY = 5 , ERR_TAXINOTVISITED = 6 , ERR_TAXIPLAYERBUSY = 7 ,
ERR_TAXIPLAYERALREADYMOUNTED = 8 , ERR_TAXIPLAYERSHAPESHIFTED = 9 , ERR_TAXIPLAYERMOVING = 10 , ERR_TAXISAMENODE = 11 ,
ERR_TAXINOTSTANDING = 12
}
enum AreaLockStatus {
AREA_LOCKSTATUS_OK = 0 , AREA_LOCKSTATUS_UNKNOWN_ERROR = 1 , AREA_LOCKSTATUS_INSUFFICIENT_EXPANSION = 2 , AREA_LOCKSTATUS_TOO_LOW_LEVEL = 3 ,
AREA_LOCKSTATUS_TOO_HIGH_LEVEL = 4 , AREA_LOCKSTATUS_RAID_LOCKED = 5 , AREA_LOCKSTATUS_QUEST_NOT_COMPLETED = 6 , AREA_LOCKSTATUS_MISSING_ITEM = 7 ,
AREA_LOCKSTATUS_MISSING_DIFFICULTY = 8 , AREA_LOCKSTATUS_ZONE_IN_COMBAT = 9 , AREA_LOCKSTATUS_INSTANCE_IS_FULL = 10 , AREA_LOCKSTATUS_NOT_ALLOWED = 11 ,
AREA_LOCKSTATUS_HAS_BIND = 12 , AREA_LOCKSTATUS_TOO_MANY_INSTANCE = 13 , AREA_LOCKSTATUS_DIFFICULTY_REQUIREMENT = 14
}
enum TrackedAuraType { TRACK_AURA_TYPE_NOT_TRACKED = 0 , TRACK_AURA_TYPE_SINGLE_TARGET = 1 , TRACK_AURA_TYPE_CONTROL_VEHICLE = 2 , MAX_TRACKED_AURA_TYPES }
enum Expansions { EXPANSION_NONE = 0 , EXPANSION_TBC = 1 , EXPANSION_WOTLK = 2 }
enum MaxLevel { MAX_LEVEL_CLASSIC = 60 , MAX_LEVEL_TBC = 70 , MAX_LEVEL_WOTLK = 80 }
enum TeleportLocation { TELEPORT_LOCATION_HOMEBIND = 0 , TELEPORT_LOCATION_BG_ENTRY_POINT = 1 }
enum CreatureLootStatus {
CREATURE_LOOT_STATUS_NONE = 0 , CREATURE_LOOT_STATUS_PICKPOCKETED = 1 , CREATURE_LOOT_STATUS_LOOTED = 2 , CREATURE_LOOT_STATUS_SKIN_AVAILABLE = 3 ,
CREATURE_LOOT_STATUS_SKINNED = 4
}
enum LootMethod {
FREE_FOR_ALL = 0 , ROUND_ROBIN = 1 , MASTER_LOOT = 2 , GROUP_LOOT = 3 ,
NEED_BEFORE_GREED = 4 , NOT_GROUP_TYPE_LOOT = 5
}
enum LootType {
LOOT_CORPSE = 1 , LOOT_PICKPOCKETING = 2 , LOOT_FISHING = 3 , LOOT_DISENCHANTING = 4 ,
LOOT_SKINNING = 6 , LOOT_PROSPECTING = 7 , LOOT_MILLING = 8 , LOOT_FISHINGHOLE = 20 ,
LOOT_FISHING_FAIL = 21 , LOOT_INSIGNIA = 22 , LOOT_MAIL = 23 , LOOT_SPELL = 24 ,
LOOT_DEBUG = 100
}
enum MovementEvent { EVENT_CHARGE = 10000 , EVENT_JUMP = 10001 , EVENT_FALL = 10002 }
Functions
SpellSchools GetFirstSchoolInMask (SpellSchoolMask mask)
static Team GetTeamIdByTeamIndex (PvpTeamIndex teamIndex)
static PvpTeamIndex GetTeamIndexByTeamId (Team team)
uint8 ClassByQuestSort (int32 QuestSort)
SkillType SkillByLockType (LockType locktype)
bool IsArenaTypeValid (ArenaType type)
Variables
static const uint8 classToIndex [MAX_CLASSES] = { 0, 0, 1, 0, 2, 0, 0, 0, 3, 0, 0, 0 }
const uint32 ItemQualityColors [MAX_ITEM_QUALITY]
uint32 const CREATURE_TYPEMASK_DEMON_OR_UNDEAD = (1 << (CREATURE_TYPE_DEMON - 1)) | (1 << (CREATURE_TYPE_UNDEAD - 1))
uint32 const CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD = (1 << (CREATURE_TYPE_HUMANOID - 1)) | (1 << (CREATURE_TYPE_UNDEAD - 1))
uint32 const CREATURE_TYPEMASK_MECHANICAL_OR_ELEMENTAL = (1 << (CREATURE_TYPE_MECHANICAL - 1)) | (1 << (CREATURE_TYPE_ELEMENTAL - 1))
static const MaxLevel maxLevelForExpansion [MAX_EXPANSION+1] = { MAX_LEVEL_CLASSIC, MAX_LEVEL_TBC, MAX_LEVEL_WOTLK }
Macro Definition Documentation
CHAIN_SPELL_JUMP_RADIUS
#define CHAIN_SPELL_JUMP_RADIUS 10
Definition at line 1805 of file SharedDefines.h.
CLASSMASK_ALL_CREATURES
#define CLASSMASK_ALL_CREATURES ((1<<(CLASS_WARRIOR-1)) | (1<<(CLASS_PALADIN-1)) | (1<<(CLASS_ROGUE-1)) | (1<<(CLASS_MAGE-1)))
Definition at line 103 of file SharedDefines.h.
CLASSMASK_ALL_PLAYABLE
#define CLASSMASK_ALL_PLAYABLE
Value:
    ((1<<(CLASS_WARRIOR-1))|(1<<(CLASS_PALADIN-1))|(1<<(CLASS_HUNTER-1))| \
    (1<<(CLASS_ROGUE-1))  |(1<<(CLASS_PRIEST-1)) |(1<<(CLASS_SHAMAN-1))| \
    (1<<(CLASS_MAGE-1))   |(1<<(CLASS_WARLOCK-1))|(1<<(CLASS_DRUID-1)) | \
    (1<<(CLASS_DEATH_KNIGHT-1)) )
Definition at line 97 of file SharedDefines.h.
CLASSMASK_RELIC_USERS
#define CLASSMASK_RELIC_USERS ((1<<(CLASS_PALADIN-1))|(1<<(CLASS_SHAMAN-1))|(1<<(CLASS_DRUID-1))|(1<<(CLASS_DEATH_KNIGHT-1)))
Definition at line 112 of file SharedDefines.h.
CLASSMASK_WAND_USERS
#define CLASSMASK_WAND_USERS ((1<<(CLASS_PRIEST-1))|(1<<(CLASS_MAGE-1))|(1<<(CLASS_WARLOCK-1)))
Definition at line 110 of file SharedDefines.h.
DEFAULT_MAX_CREATURE_LEVEL
#define DEFAULT_MAX_CREATURE_LEVEL 85
Definition at line 2276 of file SharedDefines.h.
DISPEL_ALL_MASK
#define DISPEL_ALL_MASK ((1<<DISPEL_MAGIC) | (1<<DISPEL_CURSE) | (1<<DISPEL_DISEASE) | (1<<DISPEL_POISON))
Definition at line 459 of file SharedDefines.h.
EXPECTED_MANGOSD_CLIENT_BUILD
#define EXPECTED_MANGOSD_CLIENT_BUILD {12340, 0}
Definition at line 2249 of file SharedDefines.h.
FIRST_MECHANIC
#define FIRST_MECHANIC 1
Definition at line 403 of file SharedDefines.h.
GUILD_BANK_MAX_LOGS
#define GUILD_BANK_MAX_LOGS 25
Definition at line 1810 of file SharedDefines.h.
GUILD_BANK_MAX_SLOTS
#define GUILD_BANK_MAX_SLOTS 98
Definition at line 1809 of file SharedDefines.h.
GUILD_BANK_MAX_TABS
#define GUILD_BANK_MAX_TABS 6
Definition at line 1808 of file SharedDefines.h.
GUILD_BANK_MONEY_LOGS_TAB
#define GUILD_BANK_MONEY_LOGS_TAB 100
Definition at line 1811 of file SharedDefines.h.
GUILD_EVENTLOG_MAX_RECORDS
#define GUILD_EVENTLOG_MAX_RECORDS 100
Definition at line 1812 of file SharedDefines.h.
GUILD_RANKS_MAX_COUNT
#define GUILD_RANKS_MAX_COUNT 10
Definition at line 1814 of file SharedDefines.h.
GUILD_RANKS_MIN_COUNT
#define GUILD_RANKS_MIN_COUNT 5
Definition at line 1813 of file SharedDefines.h.
IMMUNE_TO_INCAPACITATE_MASK
#define IMMUNE_TO_INCAPACITATE_MASK
Value:
    ( \
    (1<<(MECHANIC_CHARM   -1))|(1<<(MECHANIC_DISORIENTED-1))|(1<<(MECHANIC_FEAR  -1))| \
    (1<<(MECHANIC_ROOT    -1))|(1<<(MECHANIC_PACIFY     -1))|(1<<(MECHANIC_SLEEP -1))| \
    (1<<(MECHANIC_SNARE   -1))|(1<<(MECHANIC_STUN       -1))|(1<<(MECHANIC_FREEZE-1))| \
    (1<<(MECHANIC_KNOCKOUT-1))|(1<<(MECHANIC_POLYMORPH  -1))|(1<<(MECHANIC_BANISH-1))| \
    (1<<(MECHANIC_HORROR  -1)))
Definition at line 416 of file SharedDefines.h.
IMMUNE_TO_INTERRUPT_AND_SILENCE_MASK
#define IMMUNE_TO_INTERRUPT_AND_SILENCE_MASK
Value:
    ( \
    (1<<(MECHANIC_INTERRUPT-1))|(1<<(MECHANIC_SILENCE-1)))
Definition at line 432 of file SharedDefines.h.
IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK
#define IMMUNE_TO_MOVEMENT_IMPAIRMENT_AND_LOSS_CONTROL_MASK
Value:
    ( \
    (1<<(MECHANIC_CHARM   -1))|(1<<(MECHANIC_DISORIENTED-1))|(1<<(MECHANIC_FEAR  -1))| \
    (1<<(MECHANIC_ROOT    -1))|(1<<(MECHANIC_PACIFY     -1))|(1<<(MECHANIC_SLEEP -1))| \
    (1<<(MECHANIC_SNARE   -1))|(1<<(MECHANIC_STUN       -1))|(1<<(MECHANIC_FREEZE-1))| \
    (1<<(MECHANIC_KNOCKOUT-1))|(1<<(MECHANIC_POLYMORPH  -1))|(1<<(MECHANIC_BANISH-1))| \
    (1<<(MECHANIC_SHACKLE -1))|(1<<(MECHANIC_TURN       -1))|(1<<(MECHANIC_HORROR-1))| \
    (1<<(MECHANIC_DAZE    -1))|(1<<(MECHANIC_SAPPED     -1)))
Definition at line 407 of file SharedDefines.h.
IMMUNE_TO_ROOT_AND_SNARE_MASK
#define IMMUNE_TO_ROOT_AND_SNARE_MASK
Value:
    ( \
    (1<<(MECHANIC_ROOT-1))|(1<<(MECHANIC_SNARE-1)))
Definition at line 423 of file SharedDefines.h.
IMMUNE_TO_ROOT_AND_STUN_MASK
#define IMMUNE_TO_ROOT_AND_STUN_MASK
Value:
    ( \
    (1<<(MECHANIC_ROOT-1))|(1<<(MECHANIC_STUN-1)))
Definition at line 426 of file SharedDefines.h.
IMMUNE_TO_SILENCE_AND_STUN_AND_FEAR_MASK
#define IMMUNE_TO_SILENCE_AND_STUN_AND_FEAR_MASK
Value:
    ( \
    (1<<(MECHANIC_SILENCE-1))|(1<<(MECHANIC_STUN-1))|(1<<(MECHANIC_FEAR-1)))
Definition at line 429 of file SharedDefines.h.
LANGUAGES_COUNT
#define LANGUAGES_COUNT 19
Definition at line 335 of file SharedDefines.h.
MAX_ATTACK
#define MAX_ATTACK 3
Definition at line 484 of file SharedDefines.h.
MAX_BATTLEGROUND_TYPE_ID
#define MAX_BATTLEGROUND_TYPE_ID 33
Definition at line 2088 of file SharedDefines.h.
MAX_CHAT_MSG_TYPE
#define MAX_CHAT_MSG_TYPE 0x34
Definition at line 1778 of file SharedDefines.h.
MAX_CLASSES
#define MAX_CLASSES 12
Definition at line 95 of file SharedDefines.h.
MAX_CREATURE_CLASS
#define MAX_CREATURE_CLASS 4
Definition at line 104 of file SharedDefines.h.
MAX_EXPANSION
#define MAX_EXPANSION 2
Definition at line 2263 of file SharedDefines.h.
MAX_GAMEOBJECT_TYPE
#define MAX_GAMEOBJECT_TYPE 36
Definition at line 597 of file SharedDefines.h.
MAX_GENDER
#define MAX_GENDER 3
Definition at line 31 of file SharedDefines.h.
MAX_GLYPH_SLOT_INDEX
#define MAX_GLYPH_SLOT_INDEX 6
Definition at line 272 of file SharedDefines.h.
MAX_ITEM_QUALITY
#define MAX_ITEM_QUALITY 8
Definition at line 257 of file SharedDefines.h.
MAX_MECHANIC
#define MAX_MECHANIC 32
Definition at line 404 of file SharedDefines.h.
MAX_PET_DIET
#define MAX_PET_DIET 9
Definition at line 1803 of file SharedDefines.h.
MAX_POWERS
#define MAX_POWERS 7
Definition at line 163 of file SharedDefines.h.
MAX_RACES
#define MAX_RACES 12
Definition at line 60 of file SharedDefines.h.
MAX_REPUTATION_RANK
#define MAX_REPUTATION_RANK 8
Definition at line 129 of file SharedDefines.h.
MAX_SHEATHETYPE
#define MAX_SHEATHETYPE 8
Definition at line 286 of file SharedDefines.h.
MAX_SKILL_TYPE
#define MAX_SKILL_TYPE 789
Definition at line 1616 of file SharedDefines.h.
MAX_SPELL_IMMUNITY
#define MAX_SPELL_IMMUNITY 6
Definition at line 475 of file SharedDefines.h.
MAX_SPELL_SCHOOL
#define MAX_SPELL_SCHOOL 7
Definition at line 184 of file SharedDefines.h.
MAX_SPILLOVER_FACTIONS
#define MAX_SPILLOVER_FACTIONS 4
Definition at line 131 of file SharedDefines.h.
MAX_STATS
#define MAX_STATS 5
Definition at line 149 of file SharedDefines.h.
MAX_TALENT_SPEC_COUNT
#define MAX_TALENT_SPEC_COUNT 2
Definition at line 271 of file SharedDefines.h.
MAX_TOTEM_SLOT
#define MAX_TOTEM_SLOT 4
Definition at line 2158 of file SharedDefines.h.
MAX_TRAINER_TYPE
#define MAX_TRAINER_TYPE 4
Definition at line 1249 of file SharedDefines.h.
MAX_WEATHER_TYPE
#define MAX_WEATHER_TYPE 4
Definition at line 1719 of file SharedDefines.h.
MECHANIC_NOT_REMOVED_BY_SHAPESHIFT
#define MECHANIC_NOT_REMOVED_BY_SHAPESHIFT
Value:
    ( \
    (1<<(MECHANIC_CHARM -1))|(1<<(MECHANIC_DISORIENTED-1))|(1<<(MECHANIC_FEAR  -1))| \
    (1<<(MECHANIC_PACIFY-1))|(1<<(MECHANIC_STUN       -1))|(1<<(MECHANIC_FREEZE-1))| \
    (1<<(MECHANIC_BANISH-1))|(1<<(MECHANIC_SHACKLE    -1))|(1<<(MECHANIC_HORROR-1))| \
    (1<<(MECHANIC_TURN  -1))|(1<<(MECHANIC_DAZE       -1))|(1<<(MECHANIC_SAPPED-1)))
Definition at line 436 of file SharedDefines.h.
MIN_REPUTATION_RANK
#define MIN_REPUTATION_RANK (REP_HATED)
Definition at line 128 of file SharedDefines.h.
PLAYER_MAX_BATTLEGROUND_QUEUES
#define PLAYER_MAX_BATTLEGROUND_QUEUES 2
Definition at line 114 of file SharedDefines.h.
PVP_TEAM_COUNT
#define PVP_TEAM_COUNT 2
Definition at line 361 of file SharedDefines.h.
RACEMASK_ALL_PLAYABLE
#define RACEMASK_ALL_PLAYABLE
Value:
    ((1<<(RACE_HUMAN-1))    |(1<<(RACE_ORC-1))      |(1<<(RACE_DWARF-1))   | \
    (1<<(RACE_NIGHTELF-1))  |(1<<(RACE_UNDEAD-1))   |(1<<(RACE_TAUREN-1))  | \
    (1<<(RACE_GNOME-1))     |(1<<(RACE_TROLL-1))    |(1<<(RACE_BLOODELF-1))| \
    (1<<(RACE_DRAENEI-1)))
Definition at line 62 of file SharedDefines.h.
RACEMASK_ALLIANCE
#define RACEMASK_ALLIANCE
Value:
    ((1<<(RACE_HUMAN-1))    |(1<<(RACE_DWARF-1))    |(1<<(RACE_NIGHTELF-1))| \
    (1<<(RACE_GNOME-1))     |(1<<(RACE_DRAENEI-1)))
Definition at line 69 of file SharedDefines.h.
RACEMASK_HORDE
#define RACEMASK_HORDE
Value:
    ((1<<(RACE_ORC-1))      |(1<<(RACE_UNDEAD-1))   |(1<<(RACE_TAUREN-1))  | \
    (1<<(RACE_TROLL-1))     |(1<<(RACE_BLOODELF-1)))
Definition at line 73 of file SharedDefines.h.
SPELL_ID_AUTOSHOT
#define SPELL_ID_AUTOSHOT 75
Definition at line 1705 of file SharedDefines.h.
SPELL_ID_BATTLEGROUND_DESERTER
#define SPELL_ID_BATTLEGROUND_DESERTER 26013
Definition at line 1707 of file SharedDefines.h.
SPELL_ID_GENERIC_LEARN
#define SPELL_ID_GENERIC_LEARN 483
Definition at line 1699 of file SharedDefines.h.
SPELL_ID_GENERIC_LEARN_PET
#define SPELL_ID_GENERIC_LEARN_PET 55884
Definition at line 1700 of file SharedDefines.h.
SPELL_ID_PASSIVE_BATTLE_STANCE
#define SPELL_ID_PASSIVE_BATTLE_STANCE 2457
Definition at line 1701 of file SharedDefines.h.
SPELL_ID_PASSIVE_RESURRECTION_SICKNESS
#define SPELL_ID_PASSIVE_RESURRECTION_SICKNESS 15007
Definition at line 1702 of file SharedDefines.h.
SPELL_ID_SHADOWMELD
#define SPELL_ID_SHADOWMELD 58984
Definition at line 1706 of file SharedDefines.h.
SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_0s
#define SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_0s 6123
Definition at line 1704 of file SharedDefines.h.
SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_5s
#define SPELL_ID_WEAPON_SWITCH_COOLDOWN_1_5s 6119
Definition at line 1703 of file SharedDefines.h.
SPELL_RIDE_VEHICLE_HARDCODED
#define SPELL_RIDE_VEHICLE_HARDCODED 46598
Definition at line 2279 of file SharedDefines.h.
SPELL_VEHICLE_PARACHUTE
#define SPELL_VEHICLE_PARACHUTE 45472
Definition at line 2280 of file SharedDefines.h.
TOTEM_SLOT_NONE
#define TOTEM_SLOT_NONE 255
Definition at line 2156 of file SharedDefines.h.
Enumeration Type Documentation
ActivateTaxiReply
enum ActivateTaxiReply
Enumerator
ERR_TAXIOK
ERR_TAXIUNSPECIFIEDSERVERERROR
ERR_TAXINOSUCHPATH
ERR_TAXINOTENOUGHMONEY
ERR_TAXITOOFARAWAY
ERR_TAXINOVENDORNEARBY
ERR_TAXINOTVISITED
ERR_TAXIPLAYERBUSY
ERR_TAXIPLAYERALREADYMOUNTED
ERR_TAXIPLAYERSHAPESHIFTED
ERR_TAXIPLAYERMOVING
ERR_TAXISAMENODE
ERR_TAXINOTSTANDING
Definition at line 2201 of file SharedDefines.h.
AiReaction
enum AiReaction
Enumerator
AI_REACTION_ALERT
AI_REACTION_FRIENDLY
AI_REACTION_HOSTILE
AI_REACTION_AFRAID
AI_REACTION_DESTROY
Definition at line 1816 of file SharedDefines.h.
Anim
enum Anim
Enumerator
ANIM_STAND
ANIM_DEATH
ANIM_SPELL
ANIM_STOP
ANIM_WALK
ANIM_RUN
ANIM_DEAD
ANIM_RISE
ANIM_STANDWOUND
ANIM_COMBATWOUND
ANIM_COMBATCRITICAL
ANIM_SHUFFLE_LEFT
ANIM_SHUFFLE_RIGHT
ANIM_WALK_BACKWARDS
ANIM_STUN
ANIM_HANDS_CLOSED
ANIM_ATTACKUNARMED
ANIM_ATTACK1H
ANIM_ATTACK2HTIGHT
ANIM_ATTACK2HLOOSE
ANIM_PARRYUNARMED
ANIM_PARRY1H
ANIM_PARRY2HTIGHT
ANIM_PARRY2HLOOSE
ANIM_PARRYSHIELD
ANIM_READYUNARMED
ANIM_READY1H
ANIM_READY2HTIGHT
ANIM_READY2HLOOSE
ANIM_READYBOW
ANIM_DODGE
ANIM_SPELLPRECAST
ANIM_SPELLCAST
ANIM_SPELLCASTAREA
ANIM_NPCWELCOME
ANIM_NPCGOODBYE
ANIM_BLOCK
ANIM_JUMPSTART
ANIM_JUMP
ANIM_JUMPEND
ANIM_FALL
ANIM_SWIMIDLE
ANIM_SWIM
ANIM_SWIM_LEFT
ANIM_SWIM_RIGHT
ANIM_SWIM_BACKWARDS
ANIM_ATTACKBOW
ANIM_FIREBOW
ANIM_READYRIFLE
ANIM_ATTACKRIFLE
ANIM_LOOT
ANIM_SPELL_PRECAST_DIRECTED
ANIM_SPELL_PRECAST_OMNI
ANIM_SPELL_CAST_DIRECTED
ANIM_SPELL_CAST_OMNI
ANIM_SPELL_BATTLEROAR
ANIM_SPELL_READYABILITY
ANIM_SPELL_SPECIAL1H
ANIM_SPELL_SPECIAL2H
ANIM_SPELL_SHIELDBASH
ANIM_EMOTE_TALK
ANIM_EMOTE_EAT
ANIM_EMOTE_WORK
ANIM_EMOTE_USE_STANDING
ANIM_EMOTE_EXCLAMATION
ANIM_EMOTE_QUESTION
ANIM_EMOTE_BOW
ANIM_EMOTE_WAVE
ANIM_EMOTE_CHEER
ANIM_EMOTE_DANCE
ANIM_EMOTE_LAUGH
ANIM_EMOTE_SLEEP
ANIM_EMOTE_SIT_GROUND
ANIM_EMOTE_RUDE
ANIM_EMOTE_ROAR
ANIM_EMOTE_KNEEL
ANIM_EMOTE_KISS
ANIM_EMOTE_CRY
ANIM_EMOTE_CHICKEN
ANIM_EMOTE_BEG
ANIM_EMOTE_APPLAUD
ANIM_EMOTE_SHOUT
ANIM_EMOTE_FLEX
ANIM_EMOTE_SHY
ANIM_EMOTE_POINT
ANIM_ATTACK1HPIERCE
ANIM_ATTACK2HLOOSEPIERCE
ANIM_ATTACKOFF
ANIM_ATTACKOFFPIERCE
ANIM_SHEATHE
ANIM_HIPSHEATHE
ANIM_MOUNT
ANIM_RUN_LEANRIGHT
ANIM_RUN_LEANLEFT
ANIM_MOUNT_SPECIAL
ANIM_KICK
ANIM_SITDOWN
ANIM_SITTING
ANIM_SITUP
ANIM_SLEEPDOWN
ANIM_SLEEPING
ANIM_SLEEPUP
ANIM_SITCHAIRLOW
ANIM_SITCHAIRMEDIUM
ANIM_SITCHAIRHIGH
ANIM_LOADBOW
ANIM_LOADRIFLE
ANIM_ATTACKTHROWN
ANIM_READYTHROWN
ANIM_HOLDBOW
ANIM_HOLDRIFLE
ANIM_HOLDTHROWN
ANIM_LOADTHROWN
ANIM_EMOTE_SALUTE
ANIM_KNEELDOWN
ANIM_KNEELING
ANIM_KNEELUP
ANIM_ATTACKUNARMEDOFF
ANIM_SPECIALUNARMED
ANIM_STEALTHWALK
ANIM_STEALTHSTAND
ANIM_KNOCKDOWN
ANIM_EATING
ANIM_USESTANDINGLOOP
ANIM_CHANNELCASTDIRECTED
ANIM_CHANNELCASTOMNI
ANIM_WHIRLWIND
ANIM_BIRTH
ANIM_USESTANDINGSTART
ANIM_USESTANDINGEND
ANIM_HOWL
ANIM_DROWN
ANIM_DROWNED
ANIM_FISHINGCAST
ANIM_FISHINGLOOP
ANIM_FLY
ANIM_EMOTE_WORK_NO_SHEATHE
ANIM_EMOTE_STUN_NO_SHEATHE
ANIM_EMOTE_USE_STANDING_NO_SHEATHE
ANIM_SPELL_SLEEP_DOWN
ANIM_SPELL_KNEEL_START
ANIM_SPELL_KNEEL_LOOP
ANIM_SPELL_KNEEL_END
ANIM_SPRINT
ANIM_IN_FIGHT
ANIM_GAMEOBJ_SPAWN
ANIM_GAMEOBJ_CLOSE
ANIM_GAMEOBJ_CLOSED
ANIM_GAMEOBJ_OPEN
ANIM_GAMEOBJ_OPENED
ANIM_GAMEOBJ_DESTROY
ANIM_GAMEOBJ_DESTROYED
ANIM_GAMEOBJ_REBUILD
ANIM_GAMEOBJ_CUSTOM0
ANIM_GAMEOBJ_CUSTOM1
ANIM_GAMEOBJ_CUSTOM2
ANIM_GAMEOBJ_CUSTOM3
ANIM_GAMEOBJ_DESPAWN
ANIM_HOLD
ANIM_DECAY
ANIM_BOWPULL
ANIM_BOWRELEASE
ANIM_SHIPSTART
ANIM_SHIPMOVEING
ANIM_SHIPSTOP
ANIM_GROUPARROW
ANIM_ARROW
ANIM_CORPSEARROW
ANIM_GUIDEARROW
ANIM_SWAY
ANIM_DRUIDCATPOUNCE
ANIM_DRUIDCATRIP
ANIM_DRUIDCATRAKE
ANIM_DRUIDCATRAVAGE
ANIM_DRUIDCATCLAW
ANIM_DRUIDCATCOWER
ANIM_DRUIDBEARSWIPE
ANIM_DRUIDBEARBITE
ANIM_DRUIDBEARMAUL
ANIM_DRUIDBEARBASH
ANIM_DRAGONTAIL
ANIM_DRAGONSTOMP
ANIM_DRAGONSPIT
ANIM_DRAGONSPITHOVER
ANIM_DRAGONSPITFLY
ANIM_EMOTEYES
ANIM_EMOTENO
ANIM_JUMPLANDRUN
ANIM_LOOTHOLD
ANIM_LOOTUP
ANIM_STANDHIGH
ANIM_IMPACT
ANIM_LIFTOFF
ANIM_HOVER
ANIM_SUCCUBUSENTICE
ANIM_EMOTETRAIN
ANIM_EMOTEDEAD
ANIM_EMOTEDANCEONCE
ANIM_DEFLECT
ANIM_EMOTEEATNOSHEATHE
ANIM_LAND
ANIM_SUBMERGE
ANIM_SUBMERGED
ANIM_CANNIBALIZE
ANIM_ARROWBIRTH
ANIM_GROURARROWBIRTH
ANIM_CORPSEARROWBIRTH
ANIM_GUIDEARROWBIRTH
ANIM_EMOTETALKNOSHEATHE
ANIM_EMOTEPOINTNOSHEATHE
ANIM_EMOTESALUTENOSHEATHE
ANIM_EMOTEDANCESPECIAL
ANIM_MUTILATE
ANIM_CUSTOMSPELL01
ANIM_CUSTOMSPELL02
ANIM_CUSTOMSPELL03
ANIM_CUSTOMSPELL04
ANIM_CUSTOMSPELL05
ANIM_CUSTOMSPELL06
ANIM_CUSTOMSPELL07
ANIM_CUSTOMSPELL08
ANIM_CUSTOMSPELL09
ANIM_CUSTOMSPELL10
ANIM_StealthRun
Definition at line 978 of file SharedDefines.h.
AreaLockStatus
enum AreaLockStatus
Enumerator
AREA_LOCKSTATUS_OK
AREA_LOCKSTATUS_UNKNOWN_ERROR
AREA_LOCKSTATUS_INSUFFICIENT_EXPANSION
AREA_LOCKSTATUS_TOO_LOW_LEVEL
AREA_LOCKSTATUS_TOO_HIGH_LEVEL
AREA_LOCKSTATUS_RAID_LOCKED
AREA_LOCKSTATUS_QUEST_NOT_COMPLETED
AREA_LOCKSTATUS_MISSING_ITEM
AREA_LOCKSTATUS_MISSING_DIFFICULTY
AREA_LOCKSTATUS_ZONE_IN_COMBAT
AREA_LOCKSTATUS_INSTANCE_IS_FULL
AREA_LOCKSTATUS_NOT_ALLOWED
AREA_LOCKSTATUS_HAS_BIND
AREA_LOCKSTATUS_TOO_MANY_INSTANCE
AREA_LOCKSTATUS_DIFFICULTY_REQUIREMENT
Definition at line 2218 of file SharedDefines.h.
ArenaType
enum ArenaType
Enumerator
ARENA_TYPE_NONE
ARENA_TYPE_2v2
ARENA_TYPE_3v3
ARENA_TYPE_5v5
Definition at line 2090 of file SharedDefines.h.
BanMode
enum BanMode
Ban function modes.
Enumerator
BAN_ACCOUNT
BAN_CHARACTER
BAN_IP
Definition at line 2055 of file SharedDefines.h.
BanReturn
enum BanReturn
Ban function return codes.
Enumerator
BAN_SUCCESS
BAN_SYNTAX_ERROR
BAN_NOTFOUND
Definition at line 2063 of file SharedDefines.h.
BattleGroundTypeId
enum BattleGroundTypeId
Enumerator
BATTLEGROUND_TYPE_NONE
BATTLEGROUND_AV
BATTLEGROUND_WS
BATTLEGROUND_AB
BATTLEGROUND_NA
BATTLEGROUND_BE
BATTLEGROUND_AA
BATTLEGROUND_EY
BATTLEGROUND_RL
BATTLEGROUND_SA
BATTLEGROUND_DS
BATTLEGROUND_RV
BATTLEGROUND_IC
BATTLEGROUND_RB
Definition at line 2071 of file SharedDefines.h.
BattleGroundWinner
enum BattleGroundWinner
Enumerator
WINNER_HORDE
WINNER_ALLIANCE
WINNER_NONE
Definition at line 347 of file SharedDefines.h.
CharacterSlot
enum CharacterSlot
Enumerator
SLOT_HEAD
SLOT_NECK
SLOT_SHOULDERS
SLOT_SHIRT
SLOT_CHEST
SLOT_WAIST
SLOT_LEGS
SLOT_FEET
SLOT_WRISTS
SLOT_HANDS
SLOT_FINGER1
SLOT_FINGER2
SLOT_TRINKET1
SLOT_TRINKET2
SLOT_BACK
SLOT_MAIN_HAND
SLOT_OFF_HAND
SLOT_RANGED
SLOT_TABARD
SLOT_EMPTY
Definition at line 288 of file SharedDefines.h.
CharLoginFailReasons
enum CharLoginFailReasons
Enumerator
CHAR_LOGIN_NO_WORLD
CHAR_LOGIN_DUPLICATE_CHARACTER
CHAR_LOGIN_NO_INSTANCES
CHAR_LOGIN_DISABLED
CHAR_LOGIN_NO_CHARACTER
CHAR_LOGIN_LOCKED_FOR_TRANSFER
CHAR_LOGIN_LOCKED_BY_BILLING
CHAR_LOGIN_FAILED
Definition at line 1925 of file SharedDefines.h.
ChatLinkColors
enum ChatLinkColors
Enumerator
CHAT_LINK_COLOR_TRADE
CHAT_LINK_COLOR_TALENT
CHAT_LINK_COLOR_SPELL
CHAT_LINK_COLOR_ENCHANT
CHAT_LINK_COLOR_ACHIEVEMENT
CHAT_LINK_COLOR_GLYPH
Definition at line 1780 of file SharedDefines.h.
ChatMsg
enum ChatMsg
Enumerator
CHAT_MSG_ADDON
CHAT_MSG_SYSTEM
CHAT_MSG_SAY
CHAT_MSG_PARTY
CHAT_MSG_RAID
CHAT_MSG_GUILD
CHAT_MSG_OFFICER
CHAT_MSG_YELL
CHAT_MSG_WHISPER
CHAT_MSG_WHISPER_FOREIGN
CHAT_MSG_WHISPER_INFORM
CHAT_MSG_EMOTE
CHAT_MSG_TEXT_EMOTE
CHAT_MSG_MONSTER_SAY
CHAT_MSG_MONSTER_PARTY
CHAT_MSG_MONSTER_YELL
CHAT_MSG_MONSTER_WHISPER
CHAT_MSG_MONSTER_EMOTE
CHAT_MSG_CHANNEL
CHAT_MSG_CHANNEL_JOIN
CHAT_MSG_CHANNEL_LEAVE
CHAT_MSG_CHANNEL_LIST
CHAT_MSG_CHANNEL_NOTICE
CHAT_MSG_CHANNEL_NOTICE_USER
CHAT_MSG_AFK
CHAT_MSG_DND
CHAT_MSG_IGNORED
CHAT_MSG_SKILL
CHAT_MSG_LOOT
CHAT_MSG_MONEY
CHAT_MSG_OPENING
CHAT_MSG_TRADESKILLS
CHAT_MSG_PET_INFO
CHAT_MSG_COMBAT_MISC_INFO
CHAT_MSG_COMBAT_XP_GAIN
CHAT_MSG_COMBAT_HONOR_GAIN
CHAT_MSG_COMBAT_FACTION_CHANGE
CHAT_MSG_BG_SYSTEM_NEUTRAL
CHAT_MSG_BG_SYSTEM_ALLIANCE
CHAT_MSG_BG_SYSTEM_HORDE
CHAT_MSG_RAID_LEADER
CHAT_MSG_RAID_WARNING
CHAT_MSG_RAID_BOSS_EMOTE
CHAT_MSG_RAID_BOSS_WHISPER
CHAT_MSG_FILTERED
CHAT_MSG_BATTLEGROUND
CHAT_MSG_BATTLEGROUND_LEADER
CHAT_MSG_RESTRICTED
CHAT_MSG_BNET
CHAT_MSG_ACHIEVEMENT
CHAT_MSG_GUILD_ACHIEVEMENT
CHAT_MSG_ARENA_POINTS
CHAT_MSG_PARTY_LEADER
Definition at line 1721 of file SharedDefines.h.
Classes
enum Classes
Enumerator
CLASS_WARRIOR
CLASS_PALADIN
CLASS_HUNTER
CLASS_ROGUE
CLASS_PRIEST
CLASS_DEATH_KNIGHT
CLASS_SHAMAN
CLASS_MAGE
CLASS_WARLOCK
CLASS_DRUID
Definition at line 78 of file SharedDefines.h.
CorpseDynFlags
enum CorpseDynFlags
Enumerator
CORPSE_DYNFLAG_LOOTABLE
Definition at line 1693 of file SharedDefines.h.
CreatureEliteType
enum CreatureEliteType
Enumerator
CREATURE_ELITE_NORMAL
CREATURE_ELITE_ELITE
CREATURE_ELITE_RAREELITE
CREATURE_ELITE_WORLDBOSS
CREATURE_ELITE_RARE
CREATURE_UNKNOWN
Definition at line 1355 of file SharedDefines.h.
CreatureFamily
enum CreatureFamily
Enumerator
CREATURE_FAMILY_WOLF
CREATURE_FAMILY_CAT
CREATURE_FAMILY_SPIDER
CREATURE_FAMILY_BEAR
CREATURE_FAMILY_BOAR
CREATURE_FAMILY_CROCOLISK
CREATURE_FAMILY_CARRION_BIRD
CREATURE_FAMILY_CRAB
CREATURE_FAMILY_GORILLA
CREATURE_FAMILY_HORSE_CUSTOM
CREATURE_FAMILY_RAPTOR
CREATURE_FAMILY_TALLSTRIDER
CREATURE_FAMILY_FELHUNTER
CREATURE_FAMILY_VOIDWALKER
CREATURE_FAMILY_SUCCUBUS
CREATURE_FAMILY_DOOMGUARD
CREATURE_FAMILY_SCORPID
CREATURE_FAMILY_TURTLE
CREATURE_FAMILY_IMP
CREATURE_FAMILY_BAT
CREATURE_FAMILY_HYENA
CREATURE_FAMILY_BIRD_OF_PREY
CREATURE_FAMILY_WIND_SERPENT
CREATURE_FAMILY_REMOTE_CONTROL
CREATURE_FAMILY_FELGUARD
CREATURE_FAMILY_DRAGONHAWK
CREATURE_FAMILY_RAVAGER
CREATURE_FAMILY_WARP_STALKER
CREATURE_FAMILY_SPOREBAT
CREATURE_FAMILY_NETHER_RAY
CREATURE_FAMILY_SERPENT
CREATURE_FAMILY_MOTH
CREATURE_FAMILY_CHIMAERA
CREATURE_FAMILY_DEVILSAUR
CREATURE_FAMILY_GHOUL
CREATURE_FAMILY_SILITHID
CREATURE_FAMILY_WORM
CREATURE_FAMILY_RHINO
CREATURE_FAMILY_WASP
CREATURE_FAMILY_CORE_HOUND
CREATURE_FAMILY_SPIRIT_BEAST
Definition at line 1274 of file SharedDefines.h.
CreatureLootStatus
enum CreatureLootStatus
Enumerator
CREATURE_LOOT_STATUS_NONE
CREATURE_LOOT_STATUS_PICKPOCKETED
CREATURE_LOOT_STATUS_LOOTED
CREATURE_LOOT_STATUS_SKIN_AVAILABLE
CREATURE_LOOT_STATUS_SKINNED
Definition at line 2289 of file SharedDefines.h.
CreatureType
enum CreatureType
Enumerator
CREATURE_TYPE_BEAST
CREATURE_TYPE_DRAGONKIN
CREATURE_TYPE_DEMON
CREATURE_TYPE_ELEMENTAL
CREATURE_TYPE_GIANT
CREATURE_TYPE_UNDEAD
CREATURE_TYPE_HUMANOID
CREATURE_TYPE_CRITTER
CREATURE_TYPE_MECHANICAL
CREATURE_TYPE_NOT_SPECIFIED
CREATURE_TYPE_TOTEM
CREATURE_TYPE_NON_COMBAT_PET
CREATURE_TYPE_GAS_CLOUD
Definition at line 1252 of file SharedDefines.h.
CreatureTypeFlags
enum CreatureTypeFlags
Enumerator
CREATURE_TYPEFLAGS_TAMEABLE
CREATURE_TYPEFLAGS_GHOST_VISIBLE
CREATURE_TYPEFLAGS_UNK3
CREATURE_TYPEFLAGS_UNK4
CREATURE_TYPEFLAGS_UNK5
CREATURE_TYPEFLAGS_UNK6
CREATURE_TYPEFLAGS_UNK7
CREATURE_TYPEFLAGS_INTERACT_DEAD
CREATURE_TYPEFLAGS_HERBLOOT
CREATURE_TYPEFLAGS_MININGLOOT
CREATURE_TYPEFLAGS_UNK11
CREATURE_TYPEFLAGS_MOUNTED_COMBAT
CREATURE_TYPEFLAGS_CAN_ASSIST
CREATURE_TYPEFLAGS_UNK14
CREATURE_TYPEFLAGS_UNK15
CREATURE_TYPEFLAGS_ENGINEERLOOT
CREATURE_TYPEFLAGS_EXOTIC
CREATURE_TYPEFLAGS_UNK18
CREATURE_TYPEFLAGS_SIEGE_WEAPON
CREATURE_TYPEFLAGS_UNK20
CREATURE_TYPEFLAGS_UNK21
CREATURE_TYPEFLAGS_UNK22
CREATURE_TYPEFLAGS_UNK23
CREATURE_TYPEFLAGS_SQUIRE
CREATURE_TYPEFLAGS_UNK25
CREATURE_TYPEFLAGS_UNK26
CREATURE_TYPEFLAGS_TREAT_AS_IN_RAID
CREATURE_TYPEFLAGS_UNK28
CREATURE_TYPEFLAGS_UNK29
CREATURE_TYPEFLAGS_UNK30
CREATURE_TYPEFLAGS_UNK31
CREATURE_TYPEFLAGS_QUEST_BOSS
Definition at line 1319 of file SharedDefines.h.
DamageEffectType
enum DamageEffectType
Enumerator
DIRECT_DAMAGE
SPELL_DIRECT_DAMAGE
DOT
HEAL
NODAMAGE
SELF_DAMAGE_ROGUE_FALL
SELF_DAMAGE
INSTAKILL
SPELL_DAMAGE_SHIELD
SPLIT_DAMAGE
Definition at line 543 of file SharedDefines.h.
DiminishingGroup
enum DiminishingGroup
Enumerator
DIMINISHING_NONE
DIMINISHING_CONTROL_STUN
DIMINISHING_TRIGGER_STUN
DIMINISHING_CONTROL_ROOT
DIMINISHING_TRIGGER_ROOT
DIMINISHING_FEAR_CHARM_BLIND
DIMINISHING_DISORIENT
DIMINISHING_HORROR
DIMINISHING_CYCLONE
DIMINISHING_CHEAPSHOT_POUNCE
DIMINISHING_DISARM
DIMINISHING_SILENCE
DIMINISHING_FREEZE_SLEEP
DIMINISHING_BANISH
DIMINISHING_LIMITONLY
Definition at line 1834 of file SharedDefines.h.
DiminishingReturnsType
enum DiminishingReturnsType
Enumerator
DRTYPE_NONE
DRTYPE_PLAYER
DRTYPE_ALL
Definition at line 1826 of file SharedDefines.h.
DispelType
enum DispelType
Enumerator
DISPEL_NONE
DISPEL_MAGIC
DISPEL_CURSE
DISPEL_DISEASE
DISPEL_POISON
DISPEL_STEALTH
DISPEL_INVISIBILITY
DISPEL_ALL
DISPEL_SPE_NPC_ONLY
DISPEL_ENRAGE
DISPEL_ZG_TICKET
DESPEL_OLD_UNUSED
Definition at line 443 of file SharedDefines.h.
Emote
enum Emote
Enumerator
EMOTE_ONESHOT_NONE
EMOTE_ONESHOT_TALK
EMOTE_ONESHOT_BOW
EMOTE_ONESHOT_WAVE
EMOTE_ONESHOT_CHEER
EMOTE_ONESHOT_EXCLAMATION
EMOTE_ONESHOT_QUESTION
EMOTE_ONESHOT_EAT
EMOTE_STATE_DANCE
EMOTE_ONESHOT_LAUGH
EMOTE_STATE_SLEEP
EMOTE_STATE_SIT
EMOTE_ONESHOT_RUDE
EMOTE_ONESHOT_ROAR
EMOTE_ONESHOT_KNEEL
EMOTE_ONESHOT_KISS
EMOTE_ONESHOT_CRY
EMOTE_ONESHOT_CHICKEN
EMOTE_ONESHOT_BEG
EMOTE_ONESHOT_APPLAUD
EMOTE_ONESHOT_SHOUT
EMOTE_ONESHOT_FLEX
EMOTE_ONESHOT_SHY
EMOTE_ONESHOT_POINT
EMOTE_STATE_STAND
EMOTE_STATE_READYUNARMED
EMOTE_STATE_WORK_SHEATHED
EMOTE_STATE_POINT
EMOTE_STATE_NONE
EMOTE_ONESHOT_WOUND
EMOTE_ONESHOT_WOUNDCRITICAL
EMOTE_ONESHOT_ATTACKUNARMED
EMOTE_ONESHOT_ATTACK1H
EMOTE_ONESHOT_ATTACK2HTIGHT
EMOTE_ONESHOT_ATTACK2HLOOSE
EMOTE_ONESHOT_PARRYUNARMED
EMOTE_ONESHOT_PARRYSHIELD
EMOTE_ONESHOT_READYUNARMED
EMOTE_ONESHOT_READY1H
EMOTE_ONESHOT_READYBOW
EMOTE_ONESHOT_SPELLPRECAST
EMOTE_ONESHOT_SPELLCAST
EMOTE_ONESHOT_BATTLEROAR
EMOTE_ONESHOT_SPECIALATTACK1H
EMOTE_ONESHOT_KICK
EMOTE_ONESHOT_ATTACKTHROWN
EMOTE_STATE_STUN
EMOTE_STATE_DEAD
EMOTE_ONESHOT_SALUTE
EMOTE_STATE_KNEEL
EMOTE_STATE_USESTANDING
EMOTE_ONESHOT_WAVE_NOSHEATHE
EMOTE_ONESHOT_CHEER_NOSHEATHE
EMOTE_ONESHOT_EAT_NOSHEATHE
EMOTE_STATE_STUN_NOSHEATHE
EMOTE_ONESHOT_DANCE
EMOTE_ONESHOT_SALUTE_NOSHEATH
EMOTE_STATE_USESTANDING_NOSHEATHE
EMOTE_ONESHOT_LAUGH_NOSHEATHE
EMOTE_STATE_WORK
EMOTE_STATE_SPELLPRECAST
EMOTE_ONESHOT_READYRIFLE
EMOTE_STATE_READYRIFLE
EMOTE_STATE_WORK_MINING
EMOTE_STATE_WORK_CHOPWOOD
EMOTE_STATE_APPLAUD
EMOTE_ONESHOT_LIFTOFF
EMOTE_ONESHOT_YES
EMOTE_ONESHOT_NO
EMOTE_ONESHOT_TRAIN
EMOTE_ONESHOT_LAND
EMOTE_STATE_AT_EASE
EMOTE_STATE_READY1H
EMOTE_STATE_SPELLKNEELSTART
EMOTE_STATE_SUBMERGED
EMOTE_ONESHOT_SUBMERGE
EMOTE_STATE_READY2H
EMOTE_STATE_READYBOW
EMOTE_ONESHOT_MOUNTSPECIAL
EMOTE_STATE_TALK
EMOTE_STATE_FISHING
EMOTE_ONESHOT_FISHING
EMOTE_ONESHOT_LOOT
EMOTE_STATE_WHIRLWIND
EMOTE_STATE_DROWNED
EMOTE_STATE_HOLD_BOW
EMOTE_STATE_HOLD_RIFLE
EMOTE_STATE_HOLD_THROWN
EMOTE_ONESHOT_DROWN
EMOTE_ONESHOT_STOMP
EMOTE_ONESHOT_ATTACKOFF
EMOTE_ONESHOT_ATTACKOFFPIERCE
EMOTE_STATE_ROAR
EMOTE_STATE_LAUGH
EMOTE_ONESHOT_CREATURE_SPECIAL
EMOTE_ONESHOT_JUMPLANDRUN
EMOTE_ONESHOT_JUMPEND
EMOTE_ONESHOT_TALK_NOSHEATHE
EMOTE_ONESHOT_POINT_NOSHEATHE
EMOTE_STATE_CANNIBALIZE
EMOTE_ONESHOT_JUMPSTART
EMOTE_STATE_DANCESPECIAL
EMOTE_ONESHOT_DANCESPECIAL
EMOTE_ONESHOT_CUSTOMSPELL01
EMOTE_ONESHOT_CUSTOMSPELL02
EMOTE_ONESHOT_CUSTOMSPELL03
EMOTE_ONESHOT_CUSTOMSPELL04
EMOTE_ONESHOT_CUSTOMSPELL05
EMOTE_ONESHOT_CUSTOMSPELL06
EMOTE_ONESHOT_CUSTOMSPELL07
EMOTE_ONESHOT_CUSTOMSPELL08
EMOTE_ONESHOT_CUSTOMSPELL09
EMOTE_ONESHOT_CUSTOMSPELL10
EMOTE_STATE_EXCLAIM
EMOTE_STATE_DANCE_CUSTOM
EMOTE_STATE_SIT_CHAIR_MED
EMOTE_STATE_CUSTOM_SPELL_01
EMOTE_STATE_CUSTOM_SPELL_02
EMOTE_STATE_EAT
EMOTE_STATE_CUSTOM_SPELL_04
EMOTE_STATE_CUSTOM_SPELL_03
EMOTE_STATE_CUSTOM_SPELL_05
EMOTE_STATE_SPELLEFFECT_HOLD
EMOTE_STATE_EAT_NO_SHEATHE
EMOTE_STATE_MOUNT
EMOTE_STATE_READY2HL
EMOTE_STATE_SIT_CHAIR_HIGH
EMOTE_STATE_FALL
EMOTE_STATE_LOOT
EMOTE_STATE_SUBMERGED_NEW
EMOTE_ONESHOT_COWER
EMOTE_STATE_COWER
EMOTE_ONESHOT_USESTANDING
EMOTE_STATE_STEALTH_STAND
EMOTE_ONESHOT_OMNICAST_GHOUL
EMOTE_ONESHOT_ATTACKBOW
EMOTE_ONESHOT_ATTACKRIFLE
EMOTE_STATE_SWIM_IDLE
EMOTE_STATE_ATTACK_UNARMED
EMOTE_ONESHOT_SPELLCAST_W_SOUND
EMOTE_ONESHOT_DODGE
EMOTE_ONESHOT_PARRY1H
EMOTE_ONESHOT_PARRY2H
EMOTE_ONESHOT_PARRY2HL
EMOTE_STATE_FLYFALL
EMOTE_ONESHOT_FLYDEATH
EMOTE_STATE_FLY_FALL
EMOTE_ONESHOT_FLY_SIT_GROUND_DOWN
EMOTE_ONESHOT_FLY_SIT_GROUND_UP
EMOTE_ONESHOT_EMERGE
EMOTE_ONESHOT_DRAGONSPIT
EMOTE_STATE_SPECIALUNARMED
EMOTE_ONESHOT_FLYGRAB
EMOTE_STATE_FLYGRABCLOSED
EMOTE_ONESHOT_FLYGRABTHROWN
EMOTE_STATE_FLY_SIT_GROUND
EMOTE_STATE_WALKBACKWARDS
EMOTE_ONESHOT_FLYTALK
EMOTE_ONESHOT_FLYATTACK1H
EMOTE_STATE_CUSTOMSPELL08
EMOTE_ONESHOT_FLY_DRAGONSPIT
EMOTE_STATE_SIT_CHAIR_LOW
EMOTE_ONE_SHOT_STUN
EMOTE_ONESHOT_SPELLCAST_OMNI
EMOTE_STATE_READYTHROWN
EMOTE_ONESHOT_WORK_CHOPWOOD
EMOTE_ONESHOT_WORK_MINING
EMOTE_STATE_SPELL_CHANNEL_OMNI
EMOTE_STATE_SPELL_CHANNEL_DIRECTED
EMOTE_STAND_STATE_NONE
EMOTE_STATE_READYJOUST
EMOTE_STATE_STRANGULATE
EMOTE_STATE_READYSPELLOMNI
EMOTE_STATE_HOLD_JOUST
EMOTE_ONESHOT_CRY_JAINA
Definition at line 799 of file SharedDefines.h.
EncounterCreditType
enum EncounterCreditType
Enumerator
ENCOUNTER_CREDIT_KILL_CREATURE
ENCOUNTER_CREDIT_CAST_SPELL
ENCOUNTER_CREDIT_SCRIPT
Definition at line 2188 of file SharedDefines.h.
Expansions
enum Expansions
Enumerator
EXPANSION_NONE
EXPANSION_TBC
EXPANSION_WOTLK
Definition at line 2256 of file SharedDefines.h.
GameObjectDynamicLowFlags
enum GameObjectDynamicLowFlags
Enumerator
GO_DYNFLAG_LO_ACTIVATE
GO_DYNFLAG_LO_ANIMATE
GO_DYNFLAG_LO_NO_INTERACT
GO_DYNFLAG_LO_SPARKLE
GO_DYNFLAG_LO_STOPPED
Definition at line 614 of file SharedDefines.h.
GameObjectFlags
enum GameObjectFlags
Enumerator
GO_FLAG_IN_USE
GO_FLAG_LOCKED
GO_FLAG_INTERACT_COND
GO_FLAG_TRANSPORT
GO_FLAG_NO_INTERACT
GO_FLAG_NODESPAWN
GO_FLAG_TRIGGERED
GO_FLAG_AI_OBSTACLE
GO_FLAG_FREEZE_ANIMATION
GO_FLAG_DAMAGED
GO_FLAG_DESTROYED
Definition at line 599 of file SharedDefines.h.
GameobjectTypes
enum GameobjectTypes
Enumerator
GAMEOBJECT_TYPE_DOOR
GAMEOBJECT_TYPE_BUTTON
GAMEOBJECT_TYPE_QUESTGIVER
GAMEOBJECT_TYPE_CHEST
GAMEOBJECT_TYPE_BINDER
GAMEOBJECT_TYPE_GENERIC
GAMEOBJECT_TYPE_TRAP
GAMEOBJECT_TYPE_CHAIR
GAMEOBJECT_TYPE_SPELL_FOCUS
GAMEOBJECT_TYPE_TEXT
GAMEOBJECT_TYPE_GOOBER
GAMEOBJECT_TYPE_TRANSPORT
GAMEOBJECT_TYPE_AREADAMAGE
GAMEOBJECT_TYPE_CAMERA
GAMEOBJECT_TYPE_MAP_OBJECT
GAMEOBJECT_TYPE_MO_TRANSPORT
GAMEOBJECT_TYPE_DUEL_ARBITER
GAMEOBJECT_TYPE_FISHINGNODE
GAMEOBJECT_TYPE_SUMMONING_RITUAL
GAMEOBJECT_TYPE_MAILBOX
GAMEOBJECT_TYPE_DO_NOT_USE
GAMEOBJECT_TYPE_GUARDPOST
GAMEOBJECT_TYPE_SPELLCASTER
GAMEOBJECT_TYPE_MEETINGSTONE
GAMEOBJECT_TYPE_FLAGSTAND
GAMEOBJECT_TYPE_FISHINGHOLE
GAMEOBJECT_TYPE_FLAGDROP
GAMEOBJECT_TYPE_MINI_GAME
GAMEOBJECT_TYPE_DO_NOT_USE_2
GAMEOBJECT_TYPE_CAPTURE_POINT
GAMEOBJECT_TYPE_AURA_GENERATOR
GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY
GAMEOBJECT_TYPE_BARBER_CHAIR
GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING
GAMEOBJECT_TYPE_GUILD_BANK
GAMEOBJECT_TYPE_TRAPDOOR
Definition at line 557 of file SharedDefines.h.
Gender
enum Gender
Enumerator
GENDER_MALE
GENDER_FEMALE
GENDER_NONE
Definition at line 24 of file SharedDefines.h.
HolidayIds
enum HolidayIds
Enumerator
HOLIDAY_NONE
HOLIDAY_FIREWORKS_SPECTACULAR
HOLIDAY_FEAST_OF_WINTER_VEIL
HOLIDAY_NOBLEGARDEN
HOLIDAY_CHILDRENS_WEEK
HOLIDAY_CALL_TO_ARMS_AV
HOLIDAY_CALL_TO_ARMS_WS
HOLIDAY_CALL_TO_ARMS_AB
HOLIDAY_FISHING_EXTRAVAGANZA
HOLIDAY_HARVEST_FESTIVAL
HOLIDAY_HALLOWS_END
HOLIDAY_LUNAR_FESTIVAL
HOLIDAY_FIRE_FESTIVAL
HOLIDAY_CALL_TO_ARMS_EY
HOLIDAY_BREWFEST
HOLIDAY_DARKMOON_FAIRE_ELWYNN
HOLIDAY_DARKMOON_FAIRE_THUNDER
HOLIDAY_DARKMOON_FAIRE_SHATTRATH
HOLIDAY_PIRATES_DAY
HOLIDAY_CALL_TO_ARMS_SA
HOLIDAY_PILGRIMS_BOUNTY
HOLIDAY_WOTLK_LAUNCH
HOLIDAY_DAY_OF_DEAD
HOLIDAY_CALL_TO_ARMS_ISLE_OF_C
HOLIDAY_LOVE_IS_IN_THE_AIR
Definition at line 1366 of file SharedDefines.h.
InstanceResetMethod
enum InstanceResetMethod
Enumerator
INSTANCE_RESET_ALL
INSTANCE_RESET_CHANGE_DIFFICULTY
INSTANCE_RESET_GLOBAL
INSTANCE_RESET_GROUP_DISBAND
INSTANCE_RESET_GROUP_JOIN
INSTANCE_RESET_RESPAWN_DELAY
Definition at line 1858 of file SharedDefines.h.
ItemQualities
enum ItemQualities
Enumerator
ITEM_QUALITY_POOR
ITEM_QUALITY_NORMAL
ITEM_QUALITY_UNCOMMON
ITEM_QUALITY_RARE
ITEM_QUALITY_EPIC
ITEM_QUALITY_LEGENDARY
ITEM_QUALITY_ARTIFACT
ITEM_QUALITY_HEIRLOOM
Definition at line 245 of file SharedDefines.h.
Language
enum Language
Enumerator
LANG_UNIVERSAL
LANG_ORCISH
LANG_DARNASSIAN
LANG_TAURAHE
LANG_DWARVISH
LANG_COMMON
LANG_DEMONIC
LANG_TITAN
LANG_THALASSIAN
LANG_DRACONIC
LANG_KALIMAG
LANG_GNOMISH
LANG_TROLL
LANG_GUTTERSPEAK
LANG_DRAENEI
LANG_ZOMBIE
LANG_GNOMISH_BINARY
LANG_GOBLIN_BINARY
LANG_ADDON
Definition at line 312 of file SharedDefines.h.
LockKeyType
enum LockKeyType
Enumerator
LOCK_KEY_NONE
LOCK_KEY_ITEM
LOCK_KEY_SKILL
LOCK_KEY_SPELL
Definition at line 1207 of file SharedDefines.h.
LockType
enum LockType
Enumerator
LOCKTYPE_NONE
LOCKTYPE_PICKLOCK
LOCKTYPE_HERBALISM
LOCKTYPE_MINING
LOCKTYPE_DISARM_TRAP
LOCKTYPE_OPEN
LOCKTYPE_TREASURE
LOCKTYPE_CALCIFIED_ELVEN_GEMS
LOCKTYPE_CLOSE
LOCKTYPE_ARM_TRAP
LOCKTYPE_QUICK_OPEN
LOCKTYPE_QUICK_CLOSE
LOCKTYPE_OPEN_TINKERING
LOCKTYPE_OPEN_KNEELING
LOCKTYPE_OPEN_ATTACKING
LOCKTYPE_GAHZRIDIAN
LOCKTYPE_BLASTING
LOCKTYPE_SLOW_OPEN
LOCKTYPE_SLOW_CLOSE
LOCKTYPE_FISHING
LOCKTYPE_INSCRIPTION
LOCKTYPE_OPEN_FROM_VEHICLE
Definition at line 1215 of file SharedDefines.h.
LootMethod
enum LootMethod
Enumerator
FREE_FOR_ALL
ROUND_ROBIN
MASTER_LOOT
GROUP_LOOT
NEED_BEFORE_GREED
NOT_GROUP_TYPE_LOOT
Definition at line 2298 of file SharedDefines.h.
LootType
enum LootType
Enumerator
LOOT_CORPSE
LOOT_PICKPOCKETING
LOOT_FISHING
LOOT_DISENCHANTING
LOOT_SKINNING
LOOT_PROSPECTING
LOOT_MILLING
LOOT_FISHINGHOLE
LOOT_FISHING_FAIL
LOOT_INSIGNIA
LOOT_MAIL
LOOT_SPELL
LOOT_DEBUG
Definition at line 2310 of file SharedDefines.h.
MailResponseResult
enum MailResponseResult
Enumerator
MAIL_OK
MAIL_ERR_EQUIP_ERROR
MAIL_ERR_CANNOT_SEND_TO_SELF
MAIL_ERR_NOT_ENOUGH_MONEY
MAIL_ERR_RECIPIENT_NOT_FOUND
MAIL_ERR_NOT_YOUR_TEAM
MAIL_ERR_INTERNAL_ERROR
MAIL_ERR_DISABLED_FOR_TRIAL_ACC
MAIL_ERR_RECIPIENT_CAP_REACHED
MAIL_ERR_CANT_SEND_WRAPPED_COD
MAIL_ERR_MAIL_AND_CHAT_SUSPENDED
MAIL_ERR_TOO_MANY_ATTACHMENTS
MAIL_ERR_MAIL_ATTACHMENT_INVALID
MAIL_ERR_ITEM_HAS_EXPIRED
Definition at line 2110 of file SharedDefines.h.
MailResponseType
enum MailResponseType
Enumerator
MAIL_SEND
MAIL_MONEY_TAKEN
MAIL_ITEM_TAKEN
MAIL_RETURNED_TO_SENDER
MAIL_DELETED
MAIL_MADE_PERMANENT
Definition at line 2100 of file SharedDefines.h.
MaxLevel
enum MaxLevel
Enumerator
MAX_LEVEL_CLASSIC
MAX_LEVEL_TBC
MAX_LEVEL_WOTLK
Definition at line 2266 of file SharedDefines.h.
Mechanics
enum Mechanics
Enumerator
MECHANIC_NONE
MECHANIC_CHARM
MECHANIC_DISORIENTED
MECHANIC_DISARM
MECHANIC_DISTRACT
MECHANIC_FEAR
MECHANIC_GRIP
MECHANIC_ROOT
MECHANIC_PACIFY
MECHANIC_SILENCE
MECHANIC_SLEEP
MECHANIC_SNARE
MECHANIC_STUN
MECHANIC_FREEZE
MECHANIC_KNOCKOUT
MECHANIC_BLEED
MECHANIC_BANDAGE
MECHANIC_POLYMORPH
MECHANIC_BANISH
MECHANIC_SHIELD
MECHANIC_SHACKLE
MECHANIC_MOUNT
MECHANIC_INFECTED
MECHANIC_TURN
MECHANIC_HORROR
MECHANIC_INVULNERABILITY
MECHANIC_INTERRUPT
MECHANIC_DAZE
MECHANIC_DISCOVERY
MECHANIC_IMMUNE_SHIELD
MECHANIC_SAPPED
MECHANIC_ENRAGED
Definition at line 367 of file SharedDefines.h.
MoneyConstants
enum MoneyConstants
Enumerator
COPPER
SILVER
GOLD
Definition at line 133 of file SharedDefines.h.
MovementEvent
enum MovementEvent
Enumerator
EVENT_CHARGE
EVENT_JUMP
EVENT_FALL
Definition at line 2328 of file SharedDefines.h.
PetDiet
enum PetDiet
Enumerator
PET_DIET_MEAT
PET_DIET_FISH
PET_DIET_CHEESE
PET_DIET_BREAD
PET_DIET_FUNGAS
PET_DIET_FRUIT
PET_DIET_RAW_MEAT
PET_DIET_RAW_FISH
Definition at line 1791 of file SharedDefines.h.
PetTameFailureReason
enum PetTameFailureReason
Enumerator
PETTAME_INVALIDCREATURE
PETTAME_TOOMANY
PETTAME_CREATUREALREADYOWNED
PETTAME_NOTTAMEABLE
PETTAME_ANOTHERSUMMONACTIVE
PETTAME_UNITSCANTTAME
PETTAME_NOPETAVAILABLE
PETTAME_INTERNALERROR
PETTAME_TOOHIGHLEVEL
PETTAME_DEAD
PETTAME_NOTDEAD
PETTAME_CANTCONTROLEXOTIC
PETTAME_UNKNOWNERROR
Definition at line 2130 of file SharedDefines.h.
Powers
enum Powers : uint32
Enumerator
POWER_MANA
POWER_RAGE
POWER_FOCUS
POWER_ENERGY
POWER_HAPPINESS
POWER_RUNE
POWER_RUNIC_POWER
POWER_HEALTH
Definition at line 151 of file SharedDefines.h.
PvpTeamIndex
enum PvpTeamIndex
Enumerator
TEAM_INDEX_ALLIANCE
TEAM_INDEX_HORDE
TEAM_INDEX_NEUTRAL
Definition at line 354 of file SharedDefines.h.
QuestSort
enum QuestSort
Enumerator
QUEST_SORT_EPIC
QUEST_SORT_WAILING_CAVERNS_OLD
QUEST_SORT_SEASONAL
QUEST_SORT_UNDERCITY_OLD
QUEST_SORT_HERBALISM
QUEST_SORT_BATTLEGROUNDS
QUEST_SORT_ULDAMN_OLD
QUEST_SORT_WARLOCK
QUEST_SORT_WARRIOR
QUEST_SORT_SHAMAN
QUEST_SORT_FISHING
QUEST_SORT_BLACKSMITHING
QUEST_SORT_PALADIN
QUEST_SORT_MAGE
QUEST_SORT_ROGUE
QUEST_SORT_ALCHEMY
QUEST_SORT_LEATHERWORKING
QUEST_SORT_ENGINEERING
QUEST_SORT_TREASURE_MAP
QUEST_SORT_SUNKEN_TEMPLE_OLD
QUEST_SORT_HUNTER
QUEST_SORT_PRIEST
QUEST_SORT_DRUID
QUEST_SORT_TAILORING
QUEST_SORT_SPECIAL
QUEST_SORT_COOKING
QUEST_SORT_FIRST_AID
QUEST_SORT_LEGENDARY
QUEST_SORT_DARKMOON_FAIRE
QUEST_SORT_AHN_QIRAJ_WAR
QUEST_SORT_LUNAR_FESTIVAL
QUEST_SORT_REPUTATION
QUEST_SORT_INVASION
QUEST_SORT_MIDSUMMER
QUEST_SORT_BREWFEST
QUEST_SORT_INSCRIPTION
QUEST_SORT_DEATH_KNIGHT
QUEST_SORT_JEWELCRAFTING
QUEST_SORT_NOBLEGARDEN
QUEST_SORT_PILGRIMS_BOUNTY
QUEST_SORT_LOVE_IS_IN_THE_AIR
Definition at line 1397 of file SharedDefines.h.
Races
enum Races
Enumerator
RACE_HUMAN
RACE_ORC
RACE_DWARF
RACE_NIGHTELF
RACE_UNDEAD
RACE_TAUREN
RACE_GNOME
RACE_TROLL
RACE_GOBLIN
RACE_BLOODELF
RACE_DRAENEI
RACE_FEL_ORC
RACE_NAGA
RACE_BROKEN
RACE_SKELETON
RACE_VRYKUL
RACE_TUSKARR
RACE_FOREST_TROLL
RACE_TAUNKA
RACE_NORTHREND_SKELETON
RACE_ICE_TROLL
Definition at line 34 of file SharedDefines.h.
ReputationRank
enum ReputationRank
Enumerator
REP_HATED
REP_HOSTILE
REP_UNFRIENDLY
REP_NEUTRAL
REP_FRIENDLY
REP_HONORED
REP_REVERED
REP_EXALTED
Definition at line 116 of file SharedDefines.h.
ResponseCodes
enum ResponseCodes
Enumerator
RESPONSE_SUCCESS
RESPONSE_FAILURE
RESPONSE_CANCELLED
RESPONSE_DISCONNECTED
RESPONSE_FAILED_TO_CONNECT
RESPONSE_CONNECTED
RESPONSE_VERSION_MISMATCH
CSTATUS_CONNECTING
CSTATUS_NEGOTIATING_SECURITY
CSTATUS_NEGOTIATION_COMPLETE
CSTATUS_NEGOTIATION_FAILED
CSTATUS_AUTHENTICATING
AUTH_OK
AUTH_FAILED
AUTH_REJECT
AUTH_BAD_SERVER_PROOF
AUTH_UNAVAILABLE
AUTH_SYSTEM_ERROR
AUTH_BILLING_ERROR
AUTH_BILLING_EXPIRED
AUTH_VERSION_MISMATCH
AUTH_UNKNOWN_ACCOUNT
AUTH_INCORRECT_PASSWORD
AUTH_SESSION_EXPIRED
AUTH_SERVER_SHUTTING_DOWN
AUTH_ALREADY_LOGGING_IN
AUTH_LOGIN_SERVER_NOT_FOUND
AUTH_WAIT_QUEUE
AUTH_BANNED
AUTH_ALREADY_ONLINE
AUTH_NO_TIME
AUTH_DB_BUSY
AUTH_SUSPENDED
AUTH_PARENTAL_CONTROL
AUTH_LOCKED_ENFORCED
REALM_LIST_IN_PROGRESS
REALM_LIST_SUCCESS
REALM_LIST_FAILED
REALM_LIST_INVALID
REALM_LIST_REALM_NOT_FOUND
ACCOUNT_CREATE_IN_PROGRESS
ACCOUNT_CREATE_SUCCESS
ACCOUNT_CREATE_FAILED
CHAR_LIST_RETRIEVING
CHAR_LIST_RETRIEVED
CHAR_LIST_FAILED
CHAR_CREATE_IN_PROGRESS
CHAR_CREATE_SUCCESS
CHAR_CREATE_ERROR
CHAR_CREATE_FAILED
CHAR_CREATE_NAME_IN_USE
CHAR_CREATE_DISABLED
CHAR_CREATE_PVP_TEAMS_VIOLATION
CHAR_CREATE_SERVER_LIMIT
CHAR_CREATE_ACCOUNT_LIMIT
CHAR_CREATE_SERVER_QUEUE
CHAR_CREATE_ONLY_EXISTING
CHAR_CREATE_EXPANSION
CHAR_CREATE_EXPANSION_CLASS
CHAR_CREATE_LEVEL_REQUIREMENT
CHAR_CREATE_UNIQUE_CLASS_LIMIT
CHAR_CREATE_CHARACTER_IN_GUILD
CHAR_CREATE_RESTRICTED_RACECLASS
CHAR_CREATE_CHARACTER_CHOOSE_RACE
CHAR_CREATE_CHARACTER_ARENA_LEADER
CHAR_CREATE_CHARACTER_DELETE_MAIL
CHAR_CREATE_CHARACTER_SWAP_FACTION
CHAR_CREATE_CHARACTER_RACE_ONLY
CHAR_CREATE_CHARACTER_GOLD_LIMIT
CHAR_CREATE_FORCE_LOGIN
CHAR_DELETE_IN_PROGRESS
CHAR_DELETE_SUCCESS
CHAR_DELETE_FAILED
CHAR_DELETE_FAILED_LOCKED_FOR_TRANSFER
CHAR_DELETE_FAILED_GUILD_LEADER
CHAR_DELETE_FAILED_ARENA_CAPTAIN
CHAR_NAME_SUCCESS
CHAR_NAME_FAILURE
CHAR_NAME_NO_NAME
CHAR_NAME_TOO_SHORT
CHAR_NAME_TOO_LONG
CHAR_NAME_INVALID_CHARACTER
CHAR_NAME_MIXED_LANGUAGES
CHAR_NAME_PROFANE
CHAR_NAME_RESERVED
CHAR_NAME_INVALID_APOSTROPHE
CHAR_NAME_MULTIPLE_APOSTROPHES
CHAR_NAME_THREE_CONSECUTIVE
CHAR_NAME_INVALID_SPACE
CHAR_NAME_CONSECUTIVE_SPACES
CHAR_NAME_RUSSIAN_CONSECUTIVE_SILENT_CHARACTERS
CHAR_NAME_RUSSIAN_SILENT_CHARACTER_AT_BEGINNING_OR_END
CHAR_NAME_DECLENSION_DOESNT_MATCH_BASE_NAME
Definition at line 1937 of file SharedDefines.h.
ShapeshiftFlags
enum ShapeshiftFlags
Enumerator
SHAPESHIFT_FLAG_STANCE
SHAPESHIFT_FLAG_NOT_TOGGLEABLE
SHAPESHIFT_FLAG_PERSIST_ON_DEATH
SHAPESHIFT_FLAG_CAN_NPC_INTERACT
SHAPESHIFT_FLAG_DONT_USE_WEAPON
SHAPESHIFT_FLAG_AGILITY_ATTACK_BONUS
SHAPESHIFT_FLAG_CAN_USE_EQUIPPED_ITEMS
SHAPESHIFT_FLAG_CAN_USE_ITEMS
SHAPESHIFT_FLAG_DONT_AUTO_UNSHIFT
SHAPESHIFT_FLAG_CONSIDERED_DEAD
SHAPESHIFT_FLAG_CAN_ONLY_CAST_SHAPESHIFT_SPELLS
SHAPESHIFT_FLAG_STANCE_CANCEL_AT_FLIGHTMASTER
SHAPESHIFT_FLAG_NO_EMOTE_SOUNDS
SHAPESHIFT_FLAG_NO_TRIGGER_TELEPORT
SHAPESHIFT_FLAG_CANNOT_CHANGE_EQUIPPED_ITEMS
SHAPESHIFT_FLAG_RESUMMON_PETS_ON_UNSHIFT
SHAPESHIFT_FLAG_CANNOT_USE_GAME_OBJECTS
Definition at line 1904 of file SharedDefines.h.
ShapeshiftForm
enum ShapeshiftForm
Enumerator
FORM_NONE
FORM_CAT
FORM_TREE
FORM_TRAVEL
FORM_AQUA
FORM_BEAR
FORM_AMBIENT
FORM_GHOUL
FORM_DIREBEAR
FORM_STEVES_GHOUL
FORM_THARONJA_SKELETON
FORM_TEST_OF_STRENGTH
FORM_BLB_PLAYER
FORM_SHADOW_DANCE
FORM_CREATUREBEAR
FORM_CREATURECAT
FORM_GHOSTWOLF
FORM_BATTLESTANCE
FORM_DEFENSIVESTANCE
FORM_BERSERKERSTANCE
FORM_TEST
FORM_ZOMBIE
FORM_METAMORPHOSIS
FORM_UNDEAD
FORM_FRENZY
FORM_FLIGHT_EPIC
FORM_SHADOW
FORM_FLIGHT
FORM_STEALTH
FORM_MOONKIN
FORM_SPIRITOFREDEMPTION
Definition at line 1869 of file SharedDefines.h.
SheathTypes
enum SheathTypes
Enumerator
SHEATHETYPE_NONE
SHEATHETYPE_MAINHAND
SHEATHETYPE_OFFHAND
SHEATHETYPE_LARGEWEAPONLEFT
SHEATHETYPE_LARGEWEAPONRIGHT
SHEATHETYPE_HIPWEAPONLEFT
SHEATHETYPE_HIPWEAPONRIGHT
SHEATHETYPE_SHIELD
Definition at line 274 of file SharedDefines.h.
SkillCategory
enum SkillCategory
Enumerator
SKILL_CATEGORY_ATTRIBUTES
SKILL_CATEGORY_WEAPON
SKILL_CATEGORY_CLASS
SKILL_CATEGORY_ARMOR
SKILL_CATEGORY_SECONDARY
SKILL_CATEGORY_LANGUAGES
SKILL_CATEGORY_PROFESSION
SKILL_CATEGORY_GENERIC
Definition at line 1632 of file SharedDefines.h.
SkillType
enum SkillType
Enumerator
SKILL_NONE
SKILL_FROST
SKILL_FIRE
SKILL_ARMS
SKILL_COMBAT
SKILL_SUBTLETY
SKILL_SWORDS
SKILL_AXES
SKILL_BOWS
SKILL_GUNS
SKILL_BEAST_MASTERY
SKILL_SURVIVAL
SKILL_MACES
SKILL_2H_SWORDS
SKILL_HOLY
SKILL_SHADOW
SKILL_DEFENSE
SKILL_LANG_COMMON
SKILL_RACIAL_DWARVEN
SKILL_LANG_ORCISH
SKILL_LANG_DWARVEN
SKILL_LANG_DARNASSIAN
SKILL_LANG_TAURAHE
SKILL_DUAL_WIELD
SKILL_RACIAL_TAUREN
SKILL_ORC_RACIAL
SKILL_RACIAL_NIGHT_ELF
SKILL_FIRST_AID
SKILL_FERAL_COMBAT
SKILL_STAVES
SKILL_LANG_THALASSIAN
SKILL_LANG_DRACONIC
SKILL_LANG_DEMON_TONGUE
SKILL_LANG_TITAN
SKILL_LANG_OLD_TONGUE
SKILL_SURVIVAL2
SKILL_RIDING_HORSE
SKILL_RIDING_WOLF
SKILL_RIDING_TIGER
SKILL_RIDING_RAM
SKILL_SWIMING
SKILL_2H_MACES
SKILL_UNARMED
SKILL_MARKSMANSHIP
SKILL_BLACKSMITHING
SKILL_LEATHERWORKING
SKILL_ALCHEMY
SKILL_2H_AXES
SKILL_DAGGERS
SKILL_THROWN
SKILL_HERBALISM
SKILL_GENERIC_DND
SKILL_RETRIBUTION
SKILL_COOKING
SKILL_MINING
SKILL_PET_IMP
SKILL_PET_FELHUNTER
SKILL_TAILORING
SKILL_ENGINEERING
SKILL_PET_SPIDER
SKILL_PET_VOIDWALKER
SKILL_PET_SUCCUBUS
SKILL_PET_INFERNAL
SKILL_PET_DOOMGUARD
SKILL_PET_WOLF
SKILL_PET_CAT
SKILL_PET_BEAR
SKILL_PET_BOAR
SKILL_PET_CROCILISK
SKILL_PET_CARRION_BIRD
SKILL_PET_CRAB
SKILL_PET_GORILLA
SKILL_PET_RAPTOR
SKILL_PET_TALLSTRIDER
SKILL_RACIAL_UNDED
SKILL_CROSSBOWS
SKILL_WANDS
SKILL_POLEARMS
SKILL_PET_SCORPID
SKILL_ARCANE
SKILL_PET_TURTLE
SKILL_ASSASSINATION
SKILL_FURY
SKILL_PROTECTION
SKILL_PROTECTION2
SKILL_PET_TALENTS
SKILL_PLATE_MAIL
SKILL_LANG_GNOMISH
SKILL_LANG_TROLL
SKILL_ENCHANTING
SKILL_DEMONOLOGY
SKILL_AFFLICTION
SKILL_FISHING
SKILL_ENHANCEMENT
SKILL_RESTORATION
SKILL_ELEMENTAL_COMBAT
SKILL_SKINNING
SKILL_MAIL
SKILL_LEATHER
SKILL_CLOTH
SKILL_SHIELD
SKILL_FIST_WEAPONS
SKILL_RIDING_RAPTOR
SKILL_RIDING_MECHANOSTRIDER
SKILL_RIDING_UNDEAD_HORSE
SKILL_RESTORATION2
SKILL_BALANCE
SKILL_DESTRUCTION
SKILL_HOLY2
SKILL_DISCIPLINE
SKILL_LOCKPICKING
SKILL_PET_BAT
SKILL_PET_HYENA
SKILL_PET_BIRD_OF_PREY
SKILL_PET_WIND_SERPENT
SKILL_LANG_GUTTERSPEAK
SKILL_RIDING_KODO
SKILL_RACIAL_TROLL
SKILL_RACIAL_GNOME
SKILL_RACIAL_HUMAN
SKILL_JEWELCRAFTING
SKILL_RACIAL_BLOODELF
SKILL_PET_EVENT_RC
SKILL_LANG_DRAENEI
SKILL_RACIAL_DRAENEI
SKILL_PET_FELGUARD
SKILL_RIDING
SKILL_PET_DRAGONHAWK
SKILL_PET_NETHER_RAY
SKILL_PET_SPOREBAT
SKILL_PET_WARP_STALKER
SKILL_PET_RAVAGER
SKILL_PET_SERPENT
SKILL_INTERNAL
SKILL_DK_BLOOD
SKILL_DK_FROST
SKILL_DK_UNHOLY
SKILL_INSCRIPTION
SKILL_PET_MOTH
SKILL_RUNEFORGING
SKILL_MOUNTS
SKILL_COMPANIONS
SKILL_PET_EXOTIC_CHIMAERA
SKILL_PET_EXOTIC_DEVILSAUR
SKILL_PET_GHOUL
SKILL_PET_EXOTIC_SILITHID
SKILL_PET_EXOTIC_WORM
SKILL_PET_WASP
SKILL_PET_EXOTIC_RHINO
SKILL_PET_EXOTIC_CORE_HOUND
SKILL_PET_EXOTIC_SPIRIT_BEAST
Definition at line 1460 of file SharedDefines.h.
SpellDmgClass
enum SpellDmgClass
Enumerator
SPELL_DAMAGE_CLASS_NONE
SPELL_DAMAGE_CLASS_MAGIC
SPELL_DAMAGE_CLASS_MELEE
SPELL_DAMAGE_CLASS_RANGED
Definition at line 513 of file SharedDefines.h.
SpellHitType
enum SpellHitType
Enumerator
SPELL_HIT_TYPE_CRIT_DEBUG
SPELL_HIT_TYPE_CRIT
SPELL_HIT_TYPE_HIT_DEBUG
SPELL_HIT_TYPE_SPLIT
SPELL_HIT_TYPE_VICTIM_IS_ATTACKER
SPELL_HIT_TYPE_ATTACK_TABLE_DEBUG
Definition at line 503 of file SharedDefines.h.
SpellImmunity
enum SpellImmunity
Enumerator
IMMUNITY_EFFECT
IMMUNITY_STATE
IMMUNITY_SCHOOL
IMMUNITY_DAMAGE
IMMUNITY_DISPEL
IMMUNITY_MECHANIC
Definition at line 465 of file SharedDefines.h.
SpellMissInfo
enum SpellMissInfo
Enumerator
SPELL_MISS_NONE
SPELL_MISS_MISS
SPELL_MISS_RESIST
SPELL_MISS_DODGE
SPELL_MISS_PARRY
SPELL_MISS_BLOCK
SPELL_MISS_EVADE
SPELL_MISS_IMMUNE
SPELL_MISS_IMMUNE2
SPELL_MISS_DEFLECT
SPELL_MISS_ABSORB
SPELL_MISS_REFLECT
Definition at line 487 of file SharedDefines.h.
SpellPreventionType
enum SpellPreventionType
Enumerator
SPELL_PREVENTION_TYPE_NONE
SPELL_PREVENTION_TYPE_SILENCE
SPELL_PREVENTION_TYPE_PACIFY
Definition at line 521 of file SharedDefines.h.
SpellRangeFlags
enum SpellRangeFlags
Enumerator
SPELL_RANGE_FLAG_MELEE
SPELL_RANGE_FLAG_RANGED
Definition at line 537 of file SharedDefines.h.
SpellRangeIndex
enum SpellRangeIndex
indexes from SpellRange.dbc, listed only special and used in code
Enumerator
SPELL_RANGE_IDX_SELF_ONLY
SPELL_RANGE_IDX_COMBAT
SPELL_RANGE_IDX_ANYWHERE
SPELL_RANGE_IDX_HUNTER
Definition at line 529 of file SharedDefines.h.
SpellSchoolMask
enum SpellSchoolMask : uint32
A bitmask of the available SpellSchools.
Used for convenience
Enumerator
SPELL_SCHOOL_MASK_NONE
SPELL_SCHOOL_MASK_NORMAL
SPELL_SCHOOL_MASK_HOLY
SPELL_SCHOOL_MASK_FIRE
SPELL_SCHOOL_MASK_NATURE
SPELL_SCHOOL_MASK_FROST
SPELL_SCHOOL_MASK_SHADOW
SPELL_SCHOOL_MASK_ARCANE
SPELL_SCHOOL_MASK_SPELL
SPELL_SCHOOL_MASK_MAGIC
SPELL_SCHOOL_MASK_ALL
SPELL_SCHOOL_MULTI_ASTRAL
SPELL_SCHOOL_MULTI_CHAOS
SPELL_SCHOOL_MULTI_DIVINE
SPELL_SCHOOL_MULTI_ELEMENTAL
SPELL_SCHOOL_MULTI_FIRESTORM
SPELL_SCHOOL_MULTI_FROSTFIRE
SPELL_SCHOOL_MULTI_PLAGUE
SPELL_SCHOOL_MULTI_RADIANT
SPELL_SCHOOL_MULTI_SHADOWFLAME
SPELL_SCHOOL_MULTI_SHADOWFROST
SPELL_SCHOOL_MULTI_SHADOWSTRIKE
SPELL_SCHOOL_MULTI_SPELLSHADOW
SPELL_SCHOOL_MULTI_TWILIGHT
SPELL_SCHOOL_MULTI_CHROMATIC
SPELL_SCHOOL_MULTI_FROSTSTORM
SPELL_SCHOOL_MULTI_HOLYFROST
SPELL_SCHOOL_MULTI_HOLYSTORM
SPELL_SCHOOL_MULTI_SPELLFIRE
SPELL_SCHOOL_MULTI_SPELLFROST
Definition at line 189 of file SharedDefines.h.
SpellSchools
enum SpellSchools
The different spell schools that are available, used in both damage calculation and spell casting to decide what should be affected, the SPELL_SCHOOL_NORMAL is the armor, others should be self explanatory.
Note that these are the values to use for changing ie, the armor via a Modifier, and it is the Modifier::m_miscValue that should be set.
Enumerator
SPELL_SCHOOL_NORMAL
SPELL_SCHOOL_HOLY
SPELL_SCHOOL_FIRE
SPELL_SCHOOL_NATURE
SPELL_SCHOOL_FROST
SPELL_SCHOOL_SHADOW
SPELL_SCHOOL_ARCANE
Definition at line 173 of file SharedDefines.h.
Stats
enum Stats
Enumerator
STAT_STRENGTH
STAT_AGILITY
STAT_STAMINA
STAT_INTELLECT
STAT_SPIRIT
Definition at line 140 of file SharedDefines.h.
Team
enum Team
Enumerator
TEAM_NONE
TEAM_BOTH_ALLOWED
TEAM_INVALID
HORDE
ALLIANCE
Definition at line 338 of file SharedDefines.h.
TeleportLocation
enum TeleportLocation
Enumerator
TELEPORT_LOCATION_HOMEBIND
TELEPORT_LOCATION_BG_ENTRY_POINT
Definition at line 2282 of file SharedDefines.h.
TextEmotes
enum TextEmotes
Enumerator
TEXTEMOTE_AGREE
TEXTEMOTE_AMAZE
TEXTEMOTE_ANGRY
TEXTEMOTE_APOLOGIZE
TEXTEMOTE_APPLAUD
TEXTEMOTE_BASHFUL
TEXTEMOTE_BECKON
TEXTEMOTE_BEG
TEXTEMOTE_BITE
TEXTEMOTE_BLEED
TEXTEMOTE_BLINK
TEXTEMOTE_BLUSH
TEXTEMOTE_BONK
TEXTEMOTE_BORED
TEXTEMOTE_BOUNCE
TEXTEMOTE_BRB
TEXTEMOTE_BOW
TEXTEMOTE_BURP
TEXTEMOTE_BYE
TEXTEMOTE_CACKLE
TEXTEMOTE_CHEER
TEXTEMOTE_CHICKEN
TEXTEMOTE_CHUCKLE
TEXTEMOTE_CLAP
TEXTEMOTE_CONFUSED
TEXTEMOTE_CONGRATULATE
TEXTEMOTE_COUGH
TEXTEMOTE_COWER
TEXTEMOTE_CRACK
TEXTEMOTE_CRINGE
TEXTEMOTE_CRY
TEXTEMOTE_CURIOUS
TEXTEMOTE_CURTSEY
TEXTEMOTE_DANCE
TEXTEMOTE_DRINK
TEXTEMOTE_DROOL
TEXTEMOTE_EAT
TEXTEMOTE_EYE
TEXTEMOTE_FART
TEXTEMOTE_FIDGET
TEXTEMOTE_FLEX
TEXTEMOTE_FROWN
TEXTEMOTE_GASP
TEXTEMOTE_GAZE
TEXTEMOTE_GIGGLE
TEXTEMOTE_GLARE
TEXTEMOTE_GLOAT
TEXTEMOTE_GREET
TEXTEMOTE_GRIN
TEXTEMOTE_GROAN
TEXTEMOTE_GROVEL
TEXTEMOTE_GUFFAW
TEXTEMOTE_HAIL
TEXTEMOTE_HAPPY
TEXTEMOTE_HELLO
TEXTEMOTE_HUG
TEXTEMOTE_HUNGRY
TEXTEMOTE_KISS
TEXTEMOTE_KNEEL
TEXTEMOTE_LAUGH
TEXTEMOTE_LAYDOWN
TEXTEMOTE_MESSAGE
TEXTEMOTE_MOAN
TEXTEMOTE_MOON
TEXTEMOTE_MOURN
TEXTEMOTE_NO
TEXTEMOTE_NOD
TEXTEMOTE_NOSEPICK
TEXTEMOTE_PANIC
TEXTEMOTE_PEER
TEXTEMOTE_PLEAD
TEXTEMOTE_POINT
TEXTEMOTE_POKE
TEXTEMOTE_PRAY
TEXTEMOTE_ROAR
TEXTEMOTE_ROFL
TEXTEMOTE_RUDE
TEXTEMOTE_SALUTE
TEXTEMOTE_SCRATCH
TEXTEMOTE_SEXY
TEXTEMOTE_SHAKE
TEXTEMOTE_SHOUT
TEXTEMOTE_SHRUG
TEXTEMOTE_SHY
TEXTEMOTE_SIGH
TEXTEMOTE_SIT
TEXTEMOTE_SLEEP
TEXTEMOTE_SNARL
TEXTEMOTE_SPIT
TEXTEMOTE_STARE
TEXTEMOTE_SURPRISED
TEXTEMOTE_SURRENDER
TEXTEMOTE_TALK
TEXTEMOTE_TALKEX
TEXTEMOTE_TALKQ
TEXTEMOTE_TAP
TEXTEMOTE_THANK
TEXTEMOTE_THREATEN
TEXTEMOTE_TIRED
TEXTEMOTE_VICTORY
TEXTEMOTE_WAVE
TEXTEMOTE_WELCOME
TEXTEMOTE_WHINE
TEXTEMOTE_WHISTLE
TEXTEMOTE_WORK
TEXTEMOTE_YAWN
TEXTEMOTE_BOGGLE
TEXTEMOTE_CALM
TEXTEMOTE_COLD
TEXTEMOTE_COMFORT
TEXTEMOTE_CUDDLE
TEXTEMOTE_DUCK
TEXTEMOTE_INSULT
TEXTEMOTE_INTRODUCE
TEXTEMOTE_JK
TEXTEMOTE_LICK
TEXTEMOTE_LISTEN
TEXTEMOTE_LOST
TEXTEMOTE_MOCK
TEXTEMOTE_PONDER
TEXTEMOTE_POUNCE
TEXTEMOTE_PRAISE
TEXTEMOTE_PURR
TEXTEMOTE_PUZZLE
TEXTEMOTE_RAISE
TEXTEMOTE_READY
TEXTEMOTE_SHIMMY
TEXTEMOTE_SHIVER
TEXTEMOTE_SHOO
TEXTEMOTE_SLAP
TEXTEMOTE_SMIRK
TEXTEMOTE_SNIFF
TEXTEMOTE_SNUB
TEXTEMOTE_SOOTHE
TEXTEMOTE_STINK
TEXTEMOTE_TAUNT
TEXTEMOTE_TEASE
TEXTEMOTE_THIRSTY
TEXTEMOTE_VETO
TEXTEMOTE_SNICKER
TEXTEMOTE_STAND
TEXTEMOTE_TICKLE
TEXTEMOTE_VIOLIN
TEXTEMOTE_SMILE
TEXTEMOTE_RASP
TEXTEMOTE_PITY
TEXTEMOTE_GROWL
TEXTEMOTE_BARK
TEXTEMOTE_SCARED
TEXTEMOTE_FLOP
TEXTEMOTE_LOVE
TEXTEMOTE_MOO
TEXTEMOTE_OPENFIRE
TEXTEMOTE_FLIRT
TEXTEMOTE_JOKE
TEXTEMOTE_COMMEND
TEXTEMOTE_WINK
TEXTEMOTE_PAT
TEXTEMOTE_SERIOUS
TEXTEMOTE_MOUNTSPECIAL
TEXTEMOTE_GOODLUCK
TEXTEMOTE_BLAME
TEXTEMOTE_BLANK
TEXTEMOTE_BRANDISH
TEXTEMOTE_BREATH
TEXTEMOTE_DISAGREE
TEXTEMOTE_DOUBT
TEXTEMOTE_EMBARRASS
TEXTEMOTE_ENCOURAGE
TEXTEMOTE_ENEMY
TEXTEMOTE_EYEBROW
TEXTEMOTE_TOAST
Definition at line 623 of file SharedDefines.h.
TotemCategory
enum TotemCategory
Enumerator
TC_SKINNING_SKIFE_OLD
TC_EARTH_TOTEM
TC_AIR_TOTEM
TC_FIRE_TOTEM
TC_WATER_TOTEM
TC_COPPER_ROD
TC_SILVER_ROD
TC_GOLDEN_ROD
TC_TRUESILVER_ROD
TC_ARCANITE_ROD
TC_MINING_PICK_OLD
TC_PHILOSOPHERS_STONE
TC_BLACKSMITH_HAMMER_OLD
TC_ARCLIGHT_SPANNER
TC_GYROMATIC_MA
TC_MASTER_TOTEM
TC_FEL_IRON_ROD
TC_ADAMANTITE_ROD
TC_ETERNIUM_ROD
TC_HOLLOW_QUILL
TC_RUNED_AZURITE_ROD
TC_VIRTUOSO_INKING_SET
TC_DRUMS
TC_GNOMISH_ARMY_KNIFE
TC_BLACKSMITH_HAMMER
TC_MINING_PICK
TC_SKINNING_KNIFE
TC_HAMMER_PICK
TC_BLADED_PICKAXE
TC_FLINT_AND_TINDER
TC_RUNED_COBALT_ROD
TC_RUNED_TITANIUM_ROD
Definition at line 1644 of file SharedDefines.h.
TotemSlot
enum TotemSlot
Enumerator
TOTEM_SLOT_FIRE
TOTEM_SLOT_EARTH
TOTEM_SLOT_WATER
TOTEM_SLOT_AIR
Definition at line 2148 of file SharedDefines.h.
TrackedAuraType
enum TrackedAuraType
Enumerator
TRACK_AURA_TYPE_NOT_TRACKED
TRACK_AURA_TYPE_SINGLE_TARGET
TRACK_AURA_TYPE_CONTROL_VEHICLE
MAX_TRACKED_AURA_TYPES
Definition at line 2237 of file SharedDefines.h.
TradeStatus
enum TradeStatus
Enumerator
TRADE_STATUS_BUSY
TRADE_STATUS_BEGIN_TRADE
TRADE_STATUS_OPEN_WINDOW
TRADE_STATUS_TRADE_CANCELED
TRADE_STATUS_TRADE_ACCEPT
TRADE_STATUS_BUSY_2
TRADE_STATUS_NO_TARGET
TRADE_STATUS_BACK_TO_TRADE
TRADE_STATUS_TRADE_COMPLETE
TRADE_STATUS_TRADE_REJECTED
TRADE_STATUS_TARGET_TO_FAR
TRADE_STATUS_WRONG_FACTION
TRADE_STATUS_CLOSE_WINDOW
TRADE_STATUS_IGNORE_YOU
TRADE_STATUS_YOU_STUNNED
TRADE_STATUS_TARGET_STUNNED
TRADE_STATUS_YOU_DEAD
TRADE_STATUS_TARGET_DEAD
TRADE_STATUS_YOU_LOGOUT
TRADE_STATUS_TARGET_LOGOUT
TRADE_STATUS_TRIAL_ACCOUNT
TRADE_STATUS_WRONG_REALM
TRADE_STATUS_NOT_ON_TAPLIST
Definition at line 2160 of file SharedDefines.h.
TrainerType
enum TrainerType
Enumerator
TRAINER_TYPE_CLASS
TRAINER_TYPE_MOUNTS
TRAINER_TYPE_TRADESKILLS
TRAINER_TYPE_PETS
Definition at line 1241 of file SharedDefines.h.
UnitDynFlags
enum UnitDynFlags
Enumerator
UNIT_DYNFLAG_NONE
UNIT_DYNFLAG_LOOTABLE
UNIT_DYNFLAG_TRACK_UNIT
UNIT_DYNFLAG_TAPPED
UNIT_DYNFLAG_TAPPED_BY_PLAYER
UNIT_DYNFLAG_SPECIALINFO
UNIT_DYNFLAG_DEAD
UNIT_DYNFLAG_REFER_A_FRIEND
UNIT_DYNFLAG_TAPPED_BY_ALL_THREAT_LIST
Definition at line 1680 of file SharedDefines.h.
WeaponAttackType
enum WeaponAttackType
Enumerator
BASE_ATTACK
OFF_ATTACK
RANGED_ATTACK
Definition at line 477 of file SharedDefines.h.
WeatherType
enum WeatherType
Enumerator
WEATHER_TYPE_FINE
WEATHER_TYPE_RAIN
WEATHER_TYPE_SNOW
WEATHER_TYPE_STORM
WEATHER_TYPE_THUNDERS
WEATHER_TYPE_BLACKRAIN
Definition at line 1709 of file SharedDefines.h.
WorldStateType
enum WorldStateType
Enumerator
WORLD_STATE_REMOVE
WORLD_STATE_ADD
Definition at line 2195 of file SharedDefines.h.
Function Documentation
ClassByQuestSort()
uint8 ClassByQuestSort (int32 QuestSort) inline
Definition at line 1442 of file SharedDefines.h.
References CLASS_DEATH_KNIGHT, CLASS_DRUID, CLASS_HUNTER, CLASS_MAGE, CLASS_PALADIN, CLASS_PRIEST, CLASS_ROGUE, CLASS_SHAMAN, CLASS_WARLOCK, CLASS_WARRIOR, QUEST_SORT_DEATH_KNIGHT, QUEST_SORT_DRUID, QUEST_SORT_HUNTER, QUEST_SORT_MAGE, QUEST_SORT_PALADIN, QUEST_SORT_PRIEST, QUEST_SORT_ROGUE, QUEST_SORT_SHAMAN, QUEST_SORT_WARLOCK, and QUEST_SORT_WARRIOR.
GetFirstSchoolInMask()
SpellSchools GetFirstSchoolInMask (SpellSchoolMask mask) inline
Definition at line 236 of file SharedDefines.h.
References MAX_SPELL_SCHOOL, and SPELL_SCHOOL_NORMAL.
Referenced by Unit::ApplyTotalThreatModifier(), Spell::CalculatePowerCost(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), and WrathOfTheTitansProcAura::OnProc().
GetTeamIdByTeamIndex()
static Team GetTeamIdByTeamIndex (PvpTeamIndex teamIndex) inline static
Definition at line 363 of file SharedDefines.h.
References ALLIANCE, HORDE, and TEAM_INDEX_ALLIANCE.
Referenced by BattleGroundIC::AddPlayer(), BattleGroundSA::AwardBonusHonor(), BattleGroundAV::ChangeMineOwner(), BattleGroundIC::DoApplyObjectiveBenefits(), BattleGroundIC::DoApplyTeamBuff(), BattleGroundAV::EndBattleGround(), BattleGroundSA::HandlePlayerClickedOnFlag(), BattleGroundAV::InitializeNode(), BattleGroundAB::ProcessNodeCapture(), BattleGroundAV::ProcessPlayerDestroyedPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundSA::SetupBattleground(), BattleGroundAB::Update(), BattleGroundIC::Update(), and BattleGroundWS::Update().
GetTeamIndexByTeamId()
static PvpTeamIndex GetTeamIndexByTeamId (Team team) inline static
Definition at line 364 of file SharedDefines.h.
References ALLIANCE, TEAM_INDEX_ALLIANCE, and TEAM_INDEX_HORDE.
Referenced by BattleGroundEY::AddPoints(), BattleGroundSA::AlterTeleportLocation(), Battlefield::CanAddPlayerToRaid(), BattleGroundAV::CanPlayerDoMineQuest(), BattleGroundSA::CheckAchievementCriteriaMeet(), BattlefieldWG::CleanupBattlefield(), BattleGroundWS::ClearDroppedFlagGuid(), BattleGround::GetArenaTeamIdForTeam(), BattleGround::GetArenaTeamRatingChangeForTeam(), BattlefieldWG::GetBattlefieldReady(), BattleGround::GetBgRaid(), BattleGroundWS::GetDroppedFlagGuid(), BattleGroundWS::GetFlagState(), BattleGround::GetPlayersCountByTeam(), BattleGround::GetTeamStartLoc(), BattlefieldWG::HandleCapturePointEvent(), BattlefieldWG::HandleCreatureCreate(), BattlefieldWG::HandleCreatureDeath(), BattlefieldWG::HandleDestructibleBuildingEvent(), BattleGroundWS::HandleEvent(), Battlefield::HandleExitRequest(), BattlefieldWG::HandleGameObjectCreate(), BattleGroundAV::HandleKillPlayer(), BattleGroundIC::HandleKillPlayer(), BattleGroundAV::HandleKillUnit(), BattleGroundIC::HandlePlayerClickedOnFlag(), BattleGroundAB::HandlePlayerClickedOnFlag(), BattleGroundWS::HandlePlayerDroppedFlag(), Battlefield::HandlePlayerEnterZone(), BattlefieldWG::HandlePlayerEnterZone(), BattleGroundAV::HandleQuestComplete(), Battlefield::HandleQueueInviteResponse(), Battlefield::HandleWarInviteResponse(), Battlefield::InvitePlayerToQueue(), BattleGroundWS::IsFlagHeldFor45Seconds(), BattleGroundAB::IsTeamScores500Disadvantage(), BattlefieldWG::LockWorkshops(), BattleGroundWS::ProcessDroppedFlagActions(), instance_icecrown_citadel::ProcessEventNpcs(), BattleGroundWS::ProcessFlagPickUpFromBase(), BattleGroundAV::ProcessPlayerAssaultsPoint(), BattleGroundAV::ProcessPlayerDefendsPoint(), BattleGroundWS::ProcessPlayerFlagScoreEvent(), BattleGroundQueue::RemovePlayer(), BattleGroundWS::RemovePlayer(), BattleGroundWS::RespawnDroppedFlag(), BattleGroundWS::RespawnFlagAtBase(), BattleGround::SetArenaTeamIdForTeam(), BattleGround::SetArenaTeamRatingChangeForTeam(), BattleGround::SetBgRaid(), BattleGround::SetTeamStartLoc(), BattleGroundSA::TeleportPlayerToStartArea(), and BattleGround::UpdatePlayersCountByTeam().
IsArenaTypeValid()
bool IsArenaTypeValid (ArenaType type) inline
Definition at line 2098 of file SharedDefines.h.
References ARENA_TYPE_2v2, ARENA_TYPE_3v3, and ARENA_TYPE_5v5.
Referenced by ArenaTeam::Create(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleOfferPetitionOpcode(), WorldSession::HandlePetitionSignOpcode(), WorldSession::HandleTurnInPetitionOpcode(), and ArenaTeam::LoadArenaTeamFromDB().
SkillByLockType()
SkillType SkillByLockType (LockType locktype) inline
Definition at line 1618 of file SharedDefines.h.
References LOCKTYPE_FISHING, LOCKTYPE_HERBALISM, LOCKTYPE_INSCRIPTION, LOCKTYPE_MINING, LOCKTYPE_PICKLOCK, SKILL_FISHING, SKILL_HERBALISM, SKILL_INSCRIPTION, SKILL_LOCKPICKING, SKILL_MINING, and SKILL_NONE.
Referenced by Spell::CanOpenLock(), and PlayerbotAI::DoLoot().
Variable Documentation
classToIndex
const uint8 classToIndex[MAX_CLASSES] = { 0, 0, 1, 0, 2, 0, 0, 0, 3, 0, 0, 0 } static
Definition at line 108 of file SharedDefines.h.
Referenced by ObjectMgr::GetCreatureClassLvlStats(), and ObjectMgr::LoadCreatureClassLvlStats().
CREATURE_TYPEMASK_DEMON_OR_UNDEAD
uint32 const CREATURE_TYPEMASK_DEMON_OR_UNDEAD = (1 << (CREATURE_TYPE_DEMON - 1)) | (1 << (CREATURE_TYPE_UNDEAD - 1))
Definition at line 1269 of file SharedDefines.h.
Referenced by Unit::CalculateSpellCritChance().
CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD
uint32 const CREATURE_TYPEMASK_HUMANOID_OR_UNDEAD = (1 << (CREATURE_TYPE_HUMANOID - 1)) | (1 << (CREATURE_TYPE_UNDEAD - 1))
Definition at line 1270 of file SharedDefines.h.
Referenced by PlayerbotRogueAI::DoNextCombatManeuver(), and MaNGOS::CannibalizeObjectCheck::operator()().
CREATURE_TYPEMASK_MECHANICAL_OR_ELEMENTAL
uint32 const CREATURE_TYPEMASK_MECHANICAL_OR_ELEMENTAL = (1 << (CREATURE_TYPE_MECHANICAL - 1)) | (1 << (CREATURE_TYPE_ELEMENTAL - 1))
Definition at line 1271 of file SharedDefines.h.
Referenced by CorpseExplosionDK::OnCheckTarget(), and MaNGOS::ExplodeCorpseObjectCheck::operator()().
ItemQualityColors
const uint32 ItemQualityColors[MAX_ITEM_QUALITY]
Initial value:
=
{
    0xff9d9d9d,
    0xffffffff,
    0xff1eff00,
    0xff0070dd,
    0xffa335ee,
    0xffff8000,
    0xffe6cc80,
    0xffe6cc80
}
Definition at line 259 of file SharedDefines.h.
Referenced by ChatHandler::CheckEscapeSequences().
maxLevelForExpansion
const MaxLevel maxLevelForExpansion[MAX_EXPANSION+1] = { MAX_LEVEL_CLASSIC, MAX_LEVEL_TBC, MAX_LEVEL_WOTLK } static
Definition at line 2273 of file SharedDefines.h.
Referenced by Player::GetAreaTriggerLockStatus().