CMaNGOS_WoTLK: shattrath_city.cpp File Reference
shattrath_city.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "World/WorldState.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_dirty_larryAI
struct npc_khadgars_servantAI
struct npc_salsalabimAI
struct DemonBroiledSurprise
Enumerations
enum {
SAY_START = -1000274 , EMOTE_KNUCKLES = -1001242 , SAY_COUNT = -1000275 , SAY_COUNT_1 = -1000276 ,
SAY_COUNT_2 = -1000277 , SAY_ATTACK = -1000278 , SAY_GIVEUP = -1000279 , QUEST_WHAT_BOOK = 10231 ,
ENTRY_CREEPJACK = 19726 , ENTRY_MALONE = 19725 , GOSSIP_ITEM_BOOK = -3000105
}
enum {
SAY_KHAD_START = -1000489 , SAY_KHAD_SERV_0 = -1000234 , SAY_KHAD_SERV_1 = -1000235 , SAY_KHAD_SERV_2 = -1000236 ,
SAY_KHAD_SERV_3 = -1000237 , SAY_KHAD_SERV_4 = -1000238 , SAY_KHAD_SERV_5 = -1000239 , SAY_KHAD_SERV_6 = -1000240 ,
SAY_KHAD_SERV_7 = -1000241 , SAY_KHAD_SERV_8 = -1000242 , SAY_KHAD_SERV_9 = -1000243 , SAY_KHAD_SERV_10 = -1000244 ,
SAY_KHAD_SERV_11 = -1000245 , SAY_KHAD_SERV_12 = -1000246 , SAY_KHAD_SERV_13 = -1000247 , SAY_KHAD_SERV_14 = -1000248 ,
SAY_KHAD_SERV_15 = -1000249 , SAY_KHAD_SERV_16 = -1000250 , SAY_KHAD_SERV_17 = -1000251 , SAY_KHAD_SERV_18 = -1000252 ,
SAY_KHAD_SERV_19 = -1000253 , SAY_KHAD_SERV_20 = -1000254 , SAY_KHAD_SERV_21 = -1000255 , SAY_KHAD_INJURED = -1000490 ,
SAY_KHAD_MIND_YOU = -1000491 , SAY_KHAD_MIND_ALWAYS = -1000492 , SAY_KHAD_ALDOR_GREET = -1000493 , SAY_KHAD_SCRYER_GREET = -1000494 ,
SAY_KHAD_HAGGARD = -1000495 , NPC_KHADGAR = 18166 , NPC_SHANIR = 18597 , NPC_IZZARD = 18622 ,
NPC_ADYRIA = 18596 , NPC_ANCHORITE = 19142 , NPC_ARCANIST = 18547 , NPC_HAGGARD = 19684 ,
QUEST_CITY_LIGHT = 10211
}
enum { FACTION_HOSTILE_SA = 90 , QUEST_10004 = 10004 , SPELL_MAGNETIC_PULL = 31705 , SAY_SAL_AGGRO = -1015104 }
enum {
QUEST_KAELTHAS_AND_THE_VERDANT_SPHERE = 11007 , QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON = 10888 , QUEST_CUDGEL_OF_KARDESH = 10901 , TITLE_CHAMPION_OF_THE_NAARU = 53 ,
SCRIPT_RELAY_ID = 10061
}
enum { SPELL_DEMON_BROILED_SURPRISE = 43753 }
Functions
bool GossipHello_npc_dirty_larry (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_dirty_larry (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_dirty_larry (Creature *pCreature)
UnitAI * GetAI_npc_salsalabim (Creature *pCreature)
bool GossipSelect_npc_salsalabim (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool QuestRewarded_npc_adal (Player *player, Creature *creature, Quest const *quest)
void AddSC_shattrath_city ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START
EMOTE_KNUCKLES
SAY_COUNT
SAY_COUNT_1
SAY_COUNT_2
SAY_ATTACK
SAY_GIVEUP
QUEST_WHAT_BOOK
ENTRY_CREEPJACK
ENTRY_MALONE
GOSSIP_ITEM_BOOK
Definition at line 37 of file shattrath_city.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_KHAD_START
SAY_KHAD_SERV_0
SAY_KHAD_SERV_1
SAY_KHAD_SERV_2
SAY_KHAD_SERV_3
SAY_KHAD_SERV_4
SAY_KHAD_SERV_5
SAY_KHAD_SERV_6
SAY_KHAD_SERV_7
SAY_KHAD_SERV_8
SAY_KHAD_SERV_9
SAY_KHAD_SERV_10
SAY_KHAD_SERV_11
SAY_KHAD_SERV_12
SAY_KHAD_SERV_13
SAY_KHAD_SERV_14
SAY_KHAD_SERV_15
SAY_KHAD_SERV_16
SAY_KHAD_SERV_17
SAY_KHAD_SERV_18
SAY_KHAD_SERV_19
SAY_KHAD_SERV_20
SAY_KHAD_SERV_21
SAY_KHAD_INJURED
SAY_KHAD_MIND_YOU
SAY_KHAD_MIND_ALWAYS
SAY_KHAD_ALDOR_GREET
SAY_KHAD_SCRYER_GREET
SAY_KHAD_HAGGARD
NPC_KHADGAR
NPC_SHANIR
NPC_IZZARD
NPC_ADYRIA
NPC_ANCHORITE
NPC_ARCANIST
NPC_HAGGARD
QUEST_CITY_LIGHT
Definition at line 301 of file shattrath_city.cpp.
anonymous enum
anonymous enum
Enumerator
FACTION_HOSTILE_SA
QUEST_10004
SPELL_MAGNETIC_PULL
SAY_SAL_AGGRO
Definition at line 606 of file shattrath_city.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_KAELTHAS_AND_THE_VERDANT_SPHERE
QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON
QUEST_CUDGEL_OF_KARDESH
TITLE_CHAMPION_OF_THE_NAARU
SCRIPT_RELAY_ID
Definition at line 675 of file shattrath_city.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DEMON_BROILED_SURPRISE
Definition at line 702 of file shattrath_city.cpp.
Function Documentation
AddSC_shattrath_city()
void AddSC_shattrath_city ()
Definition at line 730 of file shattrath_city.cpp.
References Script::GetAI, GetAI_npc_dirty_larry(), GetAI_npc_salsalabim(), GossipHello_npc_dirty_larry(), GossipSelect_npc_dirty_larry(), GossipSelect_npc_salsalabim(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestRewardedNPC, QuestRewarded_npc_adal(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_dirty_larry()
UnitAI* GetAI_npc_dirty_larry (Creature * pCreature)
Definition at line 292 of file shattrath_city.cpp.
Referenced by AddSC_shattrath_city().
GetAI_npc_salsalabim()
UnitAI* GetAI_npc_salsalabim (Creature * pCreature)
Definition at line 657 of file shattrath_city.cpp.
Referenced by AddSC_shattrath_city().
GossipHello_npc_dirty_larry()
bool GossipHello_npc_dirty_larry (Player * pPlayer, Creature * pCreature)
Definition at line 267 of file shattrath_city.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BOOK, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_INCOMPLETE, and QUEST_WHAT_BOOK.
Referenced by AddSC_shattrath_city().
GossipSelect_npc_dirty_larry()
bool GossipSelect_npc_dirty_larry (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 279 of file shattrath_city.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_shattrath_city().
GossipSelect_npc_salsalabim()
bool GossipSelect_npc_salsalabim (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 662 of file shattrath_city.cpp.
References Creature::AI(), UnitAI::AttackStart(), DoScriptText(), FACTION_HOSTILE_SA, SAY_SAL_AGGRO, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_REACH_HOME.
Referenced by AddSC_shattrath_city().
QuestRewarded_npc_adal()
bool QuestRewarded_npc_adal (Player * player, Creature * creature, Quest const * quest)
Definition at line 685 of file shattrath_city.cpp.
References CUSTOM_EVENT_ADALS_SONG_OF_BATTLE, WorldObject::GetMap(), Quest::GetQuestId(), Player::GetQuestStatus(), QUEST_CUDGEL_OF_KARDESH, QUEST_KAELTHAS_AND_THE_VERDANT_SPHERE, QUEST_STATUS_COMPLETE, QUEST_TRIAL_OF_THE_NAARU_MAGTHERIDON, Map::SCRIPT_EXEC_PARAM_UNIQUE_BY_SOURCE, SCRIPT_RELAY_ID, SCRIPT_TYPE_RELAY, Map::ScriptsStart(), Player::SetTitle(), sWorldState, and TITLE_CHAMPION_OF_THE_NAARU.
Referenced by AddSC_shattrath_city().