CMaNGOS_WoTLK: shattered_halls.cpp File Reference
shattered_halls.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "shattered_halls.h"
#include "AI/EventAI/CreatureEventAI.h"
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct npc_shattered_hands_zealotAI
struct npc_Shattered_Hand_Scout
struct npc_shattered_hand_legionnaire
Enumerations
enum ShatteredHandLegionnairActions { LEGIONNAIRE_PUMMEL , LEGIONNAIRE_AURA_OF_DISCIPLIN , LEGIONNAIRE_ACTION_MAX , LEGIONNAIRE_CALL_FOR_REINFORCEMENTS }
enum ShatteredHandLegionnair {
SPELL_AURA_OF_DISCIPLIN = 30472 , SPELL_PUMMEL = 15615 , SPELL_ENRAGE = 30485 , EMOTE_ENRAGE = -1540066 ,
MOB_FEL_ORC = 17083 , FIRST_LEGIONNAIRE_GUID = 5400074 , SECOND_LEGIONNAIRE_GUID = 5400077 , THIRD_LEGIONNAIRE_GUID = 5400075 ,
FOURTH_LEGIONNAIRE_GUID = 5400076 , FIFTH_LEGIONNAIRE_GUID = 5400282 , SIXTH_LEGIONNAIRE_GUID = 5400078 , SEVENTH_LEGIONNAIRE_GUID = 5400062 ,
EIGHT_LEGIONNAIRE_GUID = 5400264 , DEFAULT_LEGIONNAIRE = 1
}
Functions
bool AreaTrigger_at_shattered_halls (Player *player, AreaTriggerEntry const *)
void AddSC_instance_shattered_halls ()
Variables
static float gauntletSpawnCoords [1][3]
static float scoutCoords [1][3]
static float zealotSpawnCoords [3][3]
static float zealotWaypoints [4][3]
static float firstWaveWaypoints [2][3]
static float zealotDestinations [8][3]
static float FelOrcCoords [][4]
static const int32 aRandomAggro [] = { -1540200, -1540201, -1540202, -1540203, -1540204, -1540205, -1540206 }
static const int32 aRandomReinf [] = { -1540056, -1540057, -1540058, -1540059, -1540060, -1540061, -1540062, 1540063, 1540064, 1540065 }
Enumeration Type Documentation
ShatteredHandLegionnair
enum ShatteredHandLegionnair
Enumerator
SPELL_AURA_OF_DISCIPLIN
SPELL_PUMMEL
SPELL_ENRAGE
EMOTE_ENRAGE
MOB_FEL_ORC
FIRST_LEGIONNAIRE_GUID
SECOND_LEGIONNAIRE_GUID
THIRD_LEGIONNAIRE_GUID
FOURTH_LEGIONNAIRE_GUID
FIFTH_LEGIONNAIRE_GUID
SIXTH_LEGIONNAIRE_GUID
SEVENTH_LEGIONNAIRE_GUID
EIGHT_LEGIONNAIRE_GUID
DEFAULT_LEGIONNAIRE
Definition at line 787 of file shattered_halls.cpp.
ShatteredHandLegionnairActions
enum ShatteredHandLegionnairActions
Enumerator
LEGIONNAIRE_PUMMEL
LEGIONNAIRE_AURA_OF_DISCIPLIN
LEGIONNAIRE_ACTION_MAX
LEGIONNAIRE_CALL_FOR_REINFORCEMENTS
Definition at line 779 of file shattered_halls.cpp.
Function Documentation
AddSC_instance_shattered_halls()
void AddSC_instance_shattered_halls ()
Definition at line 943 of file shattered_halls.cpp.
References AreaTrigger_at_shattered_halls(), Script::GetAI, Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_shattered_halls()
bool AreaTrigger_at_shattered_halls (Player * player, AreaTriggerEntry const *)
Definition at line 919 of file shattered_halls.cpp.
References DONE, instance_shattered_halls::GetData(), WorldObject::GetInstanceData(), IN_PROGRESS, InstanceData::instance, Unit::IsAlive(), Player::IsGameMaster(), Map::IsRegularDifficulty(), NOT_STARTED, instance_shattered_halls::SetData(), TYPE_BLADEFIST, TYPE_EXECUTION, and TYPE_OMROGG.
Referenced by AddSC_instance_shattered_halls().
Variable Documentation
aRandomAggro
const int32 aRandomAggro[] = { -1540200, -1540201, -1540202, -1540203, -1540204, -1540205, -1540206 } static
Definition at line 818 of file shattered_halls.cpp.
Referenced by npc_shattered_hand_legionnaire::Aggro().
aRandomReinf
const int32 aRandomReinf[] = { -1540056, -1540057, -1540058, -1540059, -1540060, -1540061, -1540062, 1540063, 1540064, 1540065 } static
Definition at line 819 of file shattered_halls.cpp.
Referenced by npc_shattered_hand_legionnaire::CallForReinforcements().
FelOrcCoords
float FelOrcCoords[][4] static
Initial value:
=
{
    { 69.774910f, 46.661671f, -13.211f, 3.127f},
    { 81.417f, 113.488f, -13.223f, 3.127f },
    { 49.958f, 151.284f, -13.229f, 6.169f },
    { 89.46494293212890625f, 187.3341217041015625f, -13.1455421447753906f, 3.39255523681640625f },
    { 79.96329498291015625f, 219.032073974609375f, -13.1396903991699218f, 3.984550714492797851f },
    { 83.5307159423828125f, 250.534454345703125f, -13.1131420135498046f, 3.607418537139892578f }
}
Definition at line 808 of file shattered_halls.cpp.
Referenced by npc_shattered_hand_legionnaire::CallForReinforcements().
firstWaveWaypoints
float firstWaveWaypoints[2][3] static
Initial value:
=
{
    {495.646f, 313.251f, 1.945f},
    {497.516f, 319.176f, 1.945f}
}
Definition at line 318 of file shattered_halls.cpp.
Referenced by instance_shattered_halls::DoSummonInitialWave().
gauntletSpawnCoords
float gauntletSpawnCoords[1][3] static
Initial value:
=
{
    { 409.848f, 315.385f, 1.921f}
}
Definition at line 293 of file shattered_halls.cpp.
scoutCoords
float scoutCoords[1][3] static
Initial value:
=
{
    {494.015f, 316.213f, 1.945f}
}
Definition at line 298 of file shattered_halls.cpp.
Referenced by npc_Shattered_Hand_Scout::DoStartRunning().
zealotDestinations
float zealotDestinations[8][3] static
Initial value:
=
{
    {362.577f, 311.449f, 1.918f},
    {362.592f, 320.969f, 1.918f},
    {384.897f, 311.348f, 1.946f},
    {384.212f, 321.826f, 1.946f},
    {422.212f, 310.864f, 1.946f},
    {419.034f, 319.279f, 1.940f},
    {463.375f, 310.195f, 1.935f},
    {458.814f, 321.833f, 1.946f}
}
Definition at line 324 of file shattered_halls.cpp.
Referenced by npc_shattered_hands_zealotAI::MovementInform().
zealotSpawnCoords
float zealotSpawnCoords[3][3] static
Initial value:
=
{
    {519.107f, 273.546f, 1.916f},
    {504.649f, 302.811f, 1.940f},
    {506.683f, 329.961f, 2.069f}
}
Definition at line 303 of file shattered_halls.cpp.
Referenced by instance_shattered_halls::DoSummonInitialWave(), and instance_shattered_halls::DoSummonSHZealot().
zealotWaypoints
float zealotWaypoints[4][3] static
Initial value:
=
{
    {518.681f, 291.375f, 1.923f},
    {504.559f, 315.952f, 1.942f},
    {482.445f, 315.779f, 1.939f},
    {352.104f, 315.725f, 3.139f},
}
Definition at line 310 of file shattered_halls.cpp.
Referenced by instance_shattered_halls::DoSummonSHZealot(), and npc_shattered_hands_zealotAI::MovementInform().