CMaNGOS_WoTLK: sholazar_basin.cpp File Reference
sholazar_basin.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_heliceAI
struct npc_injured_rainspeakerAI
struct StillAtItData
struct npc_tipsy_mcmanusAI
struct ShootRJR
struct ParachutePeriodicDummy
Enumerations
enum {
QUEST_ENGINEERING_DISASTER = 12688 , SAY_HELICE_ACCEPT = -1000657 , SAY_HELICE_EXPLOSIVES_1 = -1000658 , SAY_HELICE_EXPLODE_1 = -1000659 ,
SAY_HELICE_MOVE_ON = -1000660 , SAY_HELICE_EXPLOSIVES_2 = -1000661 , SAY_HELICE_EXPLODE_2 = -1000662 , SAY_HELICE_COMPLETE = -1000663 ,
SPELL_DETONATE_EXPLOSIVES_1 = 52369 , SPELL_DETONATE_EXPLOSIVES_2 = 52371
}
enum {
QUEST_FORTUNATE_MISUNDERSTAND = 12570 , GOSSIP_ITEM_READY = -3000103 , SAY_ACCEPT = -1000605 , SAY_START = -1000606 ,
SAY_END_1 = -1000607 , SAY_END_2 = -1000608 , SAY_TRACKER = -1000609 , NPC_FRENZYHEART_TRACKER = 28077 ,
SPELL_ORACLE_ESCORT_START = 51341 , SPELL_FEIGN_DEATH = 51329 , SPELL_ORACLE_INTRO = 51448
}
enum {
SAY_DISTILLATION_START = -1001125 , SAY_ADD_ORANGE = -1001126 , SAY_ADD_BANANAS = -1001127 , SAY_ADD_PAPAYA = -1001128 ,
SAY_LIGHT_BRAZIER = -1001129 , SAY_OPEN_VALVE = -1001130 , SAY_ACTION_COMPLETE_1 = -1001131 , SAY_ACTION_COMPLETE_2 = -1001132 ,
SAY_ACTION_COMPLETE_3 = -1001133 , SAY_ACTION_COMPLETE_4 = -1001134 , SAY_DISTILLATION_FAIL = -1001135 , SAY_DISTILLATION_COMPLETE = -1001136 ,
GOSSIP_ITEM_TIPSY_MCMANUS = -3000114 , TEXT_ID_READY = 13288 , QUEST_ID_STILL_AT_IT = 12644 , SPELL_TOSS_ORANGE = 51931 ,
SPELL_TOSS_BANANA = 51932 , SPELL_TOSS_PAPAYA = 51933 , NPC_WANTS_ORANGE_TRIGGER = 28535 , NPC_WANTS_PAPAYA_TRIGGER = 28536 ,
NPC_WANTS_BANANA_TRIGGER = 28537 , NPC_TIPSY_MCMANUS = 28566 , GO_THUNDERBREW_JUNGLE_PUNCH = 190643 , GO_PRESSURE_VALVE = 190635 ,
GO_BRAZIER = 190636
}
Functions
UnitAI * GetAI_npc_helice (Creature *pCreature)
bool QuestAccept_npc_helice (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_injured_rainspeaker (Creature *pCreature)
bool QuestAccept_npc_injured_rainspeaker (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_tipsy_mcmanus (Creature *pCreature)
bool GossipHello_npc_tipsy_mcmanus (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_tipsy_mcmanus (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool EffectDummyCreature_npc_wants_fruit_credit (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
bool GOUse_go_quest_still_at_it_credit (Player *pPlayer, GameObject *pGo)
void AddSC_sholazar_basin ()
Variables
static const StillAtItData aStillAtItFruits [3]
static const StillAtItData aStillAtItMachines [2]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_ENGINEERING_DISASTER
SAY_HELICE_ACCEPT
SAY_HELICE_EXPLOSIVES_1
SAY_HELICE_EXPLODE_1
SAY_HELICE_MOVE_ON
SAY_HELICE_EXPLOSIVES_2
SAY_HELICE_EXPLODE_2
SAY_HELICE_COMPLETE
SPELL_DETONATE_EXPLOSIVES_1
SPELL_DETONATE_EXPLOSIVES_2
Definition at line 39 of file sholazar_basin.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_FORTUNATE_MISUNDERSTAND
GOSSIP_ITEM_READY
SAY_ACCEPT
SAY_START
SAY_END_1
SAY_END_2
SAY_TRACKER
NPC_FRENZYHEART_TRACKER
SPELL_ORACLE_ESCORT_START
SPELL_FEIGN_DEATH
SPELL_ORACLE_INTRO
Definition at line 204 of file sholazar_basin.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_DISTILLATION_START
SAY_ADD_ORANGE
SAY_ADD_BANANAS
SAY_ADD_PAPAYA
SAY_LIGHT_BRAZIER
SAY_OPEN_VALVE
SAY_ACTION_COMPLETE_1
SAY_ACTION_COMPLETE_2
SAY_ACTION_COMPLETE_3
SAY_ACTION_COMPLETE_4
SAY_DISTILLATION_FAIL
SAY_DISTILLATION_COMPLETE
GOSSIP_ITEM_TIPSY_MCMANUS
TEXT_ID_READY
QUEST_ID_STILL_AT_IT
SPELL_TOSS_ORANGE
SPELL_TOSS_BANANA
SPELL_TOSS_PAPAYA
NPC_WANTS_ORANGE_TRIGGER
NPC_WANTS_PAPAYA_TRIGGER
NPC_WANTS_BANANA_TRIGGER
NPC_TIPSY_MCMANUS
GO_THUNDERBREW_JUNGLE_PUNCH
GO_PRESSURE_VALVE
GO_BRAZIER
Definition at line 331 of file sholazar_basin.cpp.
Function Documentation
AddSC_sholazar_basin()
void AddSC_sholazar_basin ()
Definition at line 642 of file sholazar_basin.cpp.
References EffectDummyCreature_npc_wants_fruit_credit(), Script::GetAI, GetAI_npc_helice(), GetAI_npc_injured_rainspeaker(), GetAI_npc_tipsy_mcmanus(), GossipHello_npc_tipsy_mcmanus(), GossipSelect_npc_tipsy_mcmanus(), GOUse_go_quest_still_at_it_credit(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_helice(), QuestAccept_npc_injured_rainspeaker(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_wants_fruit_credit()
bool EffectDummyCreature_npc_wants_fruit_credit (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 567 of file sholazar_basin.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, EFFECT_INDEX_0, GetClosestCreatureWithEntry(), Object::GetEntry(), Object::GetTypeId(), INTERACTION_DISTANCE, NPC_TIPSY_MCMANUS, QUEST_ID_STILL_AT_IT, QUEST_STATUS_INCOMPLETE, UnitAI::SendAIEvent(), SPELL_TOSS_BANANA, SPELL_TOSS_ORANGE, SPELL_TOSS_PAPAYA, and TYPEID_PLAYER.
Referenced by AddSC_sholazar_basin().
GetAI_npc_helice()
UnitAI* GetAI_npc_helice (Creature * pCreature)
Definition at line 179 of file sholazar_basin.cpp.
Referenced by AddSC_sholazar_basin().
GetAI_npc_injured_rainspeaker()
UnitAI* GetAI_npc_injured_rainspeaker (Creature * pCreature)
Definition at line 277 of file sholazar_basin.cpp.
Referenced by AddSC_sholazar_basin().
GetAI_npc_tipsy_mcmanus()
UnitAI* GetAI_npc_tipsy_mcmanus (Creature * pCreature)
Definition at line 539 of file sholazar_basin.cpp.
Referenced by AddSC_sholazar_basin().
GossipHello_npc_tipsy_mcmanus()
bool GossipHello_npc_tipsy_mcmanus (Player * pPlayer, Creature * pCreature)
Definition at line 544 of file sholazar_basin.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TIPSY_MCMANUS, GOSSIP_SENDER_MAIN, QUEST_ID_STILL_AT_IT, QUEST_STATUS_INCOMPLETE, and TEXT_ID_READY.
Referenced by AddSC_sholazar_basin().
GossipSelect_npc_tipsy_mcmanus()
bool GossipSelect_npc_tipsy_mcmanus (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 553 of file sholazar_basin.cpp.
References Creature::AI(), AI_EVENT_START_EVENT, GOSSIP_ACTION_INFO_DEF, and UnitAI::SendAIEvent().
Referenced by AddSC_sholazar_basin().
GOUse_go_quest_still_at_it_credit()
bool GOUse_go_quest_still_at_it_credit (Player * pPlayer, GameObject * pGo)
Definition at line 587 of file sholazar_basin.cpp.
References AI_EVENT_CUSTOM_B, GetClosestCreatureWithEntry(), Object::GetEntry(), Player::GetQuestStatus(), INTERACTION_DISTANCE, NPC_TIPSY_MCMANUS, QUEST_ID_STILL_AT_IT, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_sholazar_basin().
QuestAccept_npc_helice()
bool QuestAccept_npc_helice (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 184 of file sholazar_basin.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_ENGINEERING_DISASTER, SAY_HELICE_ACCEPT, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_sholazar_basin().
QuestAccept_npc_injured_rainspeaker()
bool QuestAccept_npc_injured_rainspeaker (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 282 of file sholazar_basin.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_FORTUNATE_MISUNDERSTAND, Unit::RemoveAurasDueToSpell(), SAY_ACCEPT, Creature::SetFactionTemporary(), SPELL_FEIGN_DEATH, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_sholazar_basin().
Variable Documentation
aStillAtItFruits
const StillAtItData aStillAtItFruits[3] static
Initial value:
=
{
    {SAY_ADD_ORANGE,     NPC_WANTS_ORANGE_TRIGGER},
    {SAY_ADD_BANANAS,    NPC_WANTS_BANANA_TRIGGER},
    {SAY_ADD_PAPAYA,     NPC_WANTS_PAPAYA_TRIGGER},
}
Definition at line 372 of file sholazar_basin.cpp.
Referenced by npc_tipsy_mcmanusAI::ReceiveAIEvent(), and npc_tipsy_mcmanusAI::UpdateAI().
aStillAtItMachines
const StillAtItData aStillAtItMachines[2] static
Initial value:
=
{
    {SAY_LIGHT_BRAZIER,  GO_BRAZIER},
    {SAY_OPEN_VALVE,     GO_PRESSURE_VALVE},
}
Definition at line 379 of file sholazar_basin.cpp.
Referenced by npc_tipsy_mcmanusAI::ReceiveAIEvent(), and npc_tipsy_mcmanusAI::UpdateAI().