CMaNGOS_WoTLK: silithus.cpp File Reference
silithus.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct EventLocations
struct npc_anachronos_the_ancientAI
struct npc_solenorAI
Macros
#define GOSSIP_ITEM "Show me your real face, demon."
Enumerations
enum {
NPC_MERITHRA_OF_THE_DREAM = 15378 , NPC_CAELESTRASZ = 15379 , NPC_ARYGOS = 15380 , NPC_ANACHRONOS_THE_ANCIENT = 15381 ,
NPC_ANACHRONOS_QUEST_TRIGGER = 15454 , NPC_FANDRAL_STAGHELM = 15382 , NPC_KALDOREI_INFANTRY = 15423 , NPC_QIRAJI_WASP = 15414 ,
NPC_QIRAJI_DRONE = 15421 , NPC_QIRAJI_TANK = 15422 , NPC_ANUBISATH_CONQUEROR = 15424 , GO_MERITHRA_WAKE = 180604 ,
QUEST_A_PAWN_ON_THE_ETERNAL_BOARD = 8519 , SAY_ANACHRONOS_INTRO_1 = -1000740 , SAY_FANDRAL_INTRO_2 = -1000741 , SAY_MERITHRA_INTRO_3 = -1000742 ,
EMOTE_ARYGOS_NOD = -1000743 , SAY_CAELESTRASZ_INTRO_4 = -1000744 , EMOTE_MERITHRA_GLANCE = -1000745 , SAY_MERITHRA_INTRO_5 = -1000746 ,
SAY_MERITHRA_ATTACK_1 = -1000747 , SAY_ARYGOS_ATTACK_2 = -1000748 , SAY_ARYGOS_ATTACK_3 = -1000749 , SAY_CAELESTRASZ_ATTACK_4 = -1000750 ,
SAY_CAELESTRASZ_ATTACK_5 = -1000751 , SAY_ANACHRONOS_SEAL_1 = -1000752 , SAY_FANDRAL_SEAL_2 = -1000753 , SAY_ANACHRONOS_SEAL_3 = -1000754 ,
SAY_ANACHRONOS_SEAL_4 = -1000755 , SAY_ANACHRONOS_SEAL_5 = -1000756 , SAY_FANDRAL_SEAL_6 = -1000757 , EMOTE_FANDRAL_EXHAUSTED = -1000758 ,
SAY_ANACHRONOS_EPILOGUE_1 = -1000759 , SAY_ANACHRONOS_EPILOGUE_2 = -1000760 , SAY_ANACHRONOS_EPILOGUE_3 = -1000761 , EMOTE_ANACHRONOS_SCEPTER = -1000762 ,
SAY_FANDRAL_EPILOGUE_4 = -1000763 , SAY_FANDRAL_EPILOGUE_5 = -1000764 , EMOTE_FANDRAL_SHATTER = -1000765 , SAY_ANACHRONOS_EPILOGUE_6 = -1000766 ,
SAY_FANDRAL_EPILOGUE_7 = -1000767 , EMOTE_ANACHRONOS_DISPPOINTED = -1000768 , EMOTE_ANACHRONOS_PICKUP = -1000769 , SAY_ANACHRONOS_EPILOGUE_8 = -1000770 ,
SPELL_GREEN_DRAGON_TRANSFORM = 25105 , SPELL_RED_DRAGON_TRANSFORM = 25106 , SPELL_BLUE_DRAGON_TRANSFORM = 25107 , SPELL_BRONZE_DRAGON_TRANSFORM = 25108 ,
SPELL_MERITHRA_WAKE = 25145 , SPELL_ARYGOS_VENGEANCE = 25149 , SPELL_CAELESTRASZ_MOLTEN_RAIN = 25150 , SPELL_TIME_STOP = 25158 ,
SPELL_HOVER = 17131 , SPELL_GLYPH_OF_WARDING = 25166 , SPELL_PRISMATIC_BARRIER = 25159 , SPELL_CALL_ANCIENTS = 25167 ,
SPELL_SHATTER_HAMMER = 25182 , EQUIP_ID_SCEPTRE = 15410 , POINT_ID_DRAGON_ATTACK = 1 , POINT_ID_EXIT = 2 ,
POINT_ID_GATE = 3 , POINT_ID_SCEPTER_1 = 4 , POINT_ID_SCEPTER_2 = 5 , POINT_ID_EPILOGUE = 6 ,
DATA_HANDLE_SCEPTER = 7 , DATA_MERITHRA_ATTACK = 8 , DATA_CAELASTRASZ_ATTACK = 9 , MERITHRA_TAKEOFF = 10 ,
ARYGOS_TAKEOFF = 11 , CAELESTRASZ_TAKEOFF = 12 , MAX_DRAGONS = 4 , MAX_CONQUERORS = 3 ,
MAX_QIRAJI = 6 , MAX_KALDOREI = 20
}
enum {
SPELL_FOOLS_PLIGHT = 23504 , SPELL_SOUL_FLAME = 23272 , SPELL_DREADFUL_FRIGHT = 23275 , SPELL_CREEPING_DOOM = 23589 ,
SPELL_CRIPPLING_CLIP = 23279 , EMOTE_IMMOBILIZED = -1001252 , SPELL_FROST_TRAP = 13810 , NPC_NELSON_THE_NICE = 14536 ,
NPC_SOLENOR_THE_SLAYER = 14530 , NPC_CREEPING_DOOM = 14761 , NPC_THE_CLEANER = 14503 , QUEST_STAVE_OF_THE_ANCIENTS = 7636
}
Functions
UnitAI * GetAI_npc_anachronos_the_ancient (Creature *pCreature)
bool QuestAcceptGO_crystalline_tear (Player *pPlayer, GameObject *pGo, const Quest *pQuest)
bool GossipHello_npc_solenor (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_solenor (Player *pPlayer, Creature *pCreature, uint32, uint32)
UnitAI * GetAI_npc_solenor (Creature *pCreature)
void AddSC_silithus ()
Variables
static const DialogueEntry aEventDialogue []
static EventLocations aEternalBoardNPCs [MAX_DRAGONS]
static EventLocations aQirajiWarriors [MAX_CONQUERORS]
static EventLocations aEternalBoardMovement []
Macro Definition Documentation
GOSSIP_ITEM
#define GOSSIP_ITEM "Show me your real face, demon."
Definition at line 793 of file silithus.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_MERITHRA_OF_THE_DREAM
NPC_CAELESTRASZ
NPC_ARYGOS
NPC_ANACHRONOS_THE_ANCIENT
NPC_ANACHRONOS_QUEST_TRIGGER
NPC_FANDRAL_STAGHELM
NPC_KALDOREI_INFANTRY
NPC_QIRAJI_WASP
NPC_QIRAJI_DRONE
NPC_QIRAJI_TANK
NPC_ANUBISATH_CONQUEROR
GO_MERITHRA_WAKE
QUEST_A_PAWN_ON_THE_ETERNAL_BOARD
SAY_ANACHRONOS_INTRO_1
SAY_FANDRAL_INTRO_2
SAY_MERITHRA_INTRO_3
EMOTE_ARYGOS_NOD
SAY_CAELESTRASZ_INTRO_4
EMOTE_MERITHRA_GLANCE
SAY_MERITHRA_INTRO_5
SAY_MERITHRA_ATTACK_1
SAY_ARYGOS_ATTACK_2
SAY_ARYGOS_ATTACK_3
SAY_CAELESTRASZ_ATTACK_4
SAY_CAELESTRASZ_ATTACK_5
SAY_ANACHRONOS_SEAL_1
SAY_FANDRAL_SEAL_2
SAY_ANACHRONOS_SEAL_3
SAY_ANACHRONOS_SEAL_4
SAY_ANACHRONOS_SEAL_5
SAY_FANDRAL_SEAL_6
EMOTE_FANDRAL_EXHAUSTED
SAY_ANACHRONOS_EPILOGUE_1
SAY_ANACHRONOS_EPILOGUE_2
SAY_ANACHRONOS_EPILOGUE_3
EMOTE_ANACHRONOS_SCEPTER
SAY_FANDRAL_EPILOGUE_4
SAY_FANDRAL_EPILOGUE_5
EMOTE_FANDRAL_SHATTER
SAY_ANACHRONOS_EPILOGUE_6
SAY_FANDRAL_EPILOGUE_7
EMOTE_ANACHRONOS_DISPPOINTED
EMOTE_ANACHRONOS_PICKUP
SAY_ANACHRONOS_EPILOGUE_8
SPELL_GREEN_DRAGON_TRANSFORM
SPELL_RED_DRAGON_TRANSFORM
SPELL_BLUE_DRAGON_TRANSFORM
SPELL_BRONZE_DRAGON_TRANSFORM
SPELL_MERITHRA_WAKE
SPELL_ARYGOS_VENGEANCE
SPELL_CAELESTRASZ_MOLTEN_RAIN
SPELL_TIME_STOP
SPELL_HOVER
SPELL_GLYPH_OF_WARDING
SPELL_PRISMATIC_BARRIER
SPELL_CALL_ANCIENTS
SPELL_SHATTER_HAMMER
EQUIP_ID_SCEPTRE
POINT_ID_DRAGON_ATTACK
POINT_ID_EXIT
POINT_ID_GATE
POINT_ID_SCEPTER_1
POINT_ID_SCEPTER_2
POINT_ID_EPILOGUE
DATA_HANDLE_SCEPTER
DATA_MERITHRA_ATTACK
DATA_CAELASTRASZ_ATTACK
MERITHRA_TAKEOFF
ARYGOS_TAKEOFF
CAELESTRASZ_TAKEOFF
MAX_DRAGONS
MAX_CONQUERORS
MAX_QIRAJI
MAX_KALDOREI
Definition at line 34 of file silithus.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FOOLS_PLIGHT
SPELL_SOUL_FLAME
SPELL_DREADFUL_FRIGHT
SPELL_CREEPING_DOOM
SPELL_CRIPPLING_CLIP
EMOTE_IMMOBILIZED
SPELL_FROST_TRAP
NPC_NELSON_THE_NICE
NPC_SOLENOR_THE_SLAYER
NPC_CREEPING_DOOM
NPC_THE_CLEANER
QUEST_STAVE_OF_THE_ANCIENTS
Definition at line 772 of file silithus.cpp.
Function Documentation
AddSC_silithus()
void AddSC_silithus ()
Definition at line 1050 of file silithus.cpp.
References Script::GetAI, GetAI_npc_anachronos_the_ancient(), GetAI_npc_solenor(), GossipHello_npc_solenor(), GossipSelect_npc_solenor(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptGO, QuestAcceptGO_crystalline_tear(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_anachronos_the_ancient()
UnitAI* GetAI_npc_anachronos_the_ancient (Creature * pCreature)
Definition at line 747 of file silithus.cpp.
Referenced by AddSC_silithus().
GetAI_npc_solenor()
UnitAI* GetAI_npc_solenor (Creature * pCreature)
Definition at line 1045 of file silithus.cpp.
Referenced by AddSC_silithus().
GossipHello_npc_solenor()
bool GossipHello_npc_solenor (Player * pPlayer, Creature * pCreature)
Definition at line 1029 of file silithus.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and QUEST_STAVE_OF_THE_ANCIENTS.
Referenced by AddSC_silithus().
GossipSelect_npc_solenor()
bool GossipSelect_npc_solenor (Player * pPlayer, Creature * pCreature, uint32 , uint32)
Definition at line 1038 of file silithus.cpp.
References Creature::AI(), and Object::GetObjectGuid().
Referenced by AddSC_silithus().
QuestAcceptGO_crystalline_tear()
bool QuestAcceptGO_crystalline_tear (Player * pPlayer, GameObject * pGo, const Quest * pQuest)
Definition at line 752 of file silithus.cpp.
References GetClosestCreatureWithEntry(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Quest::GetQuestId(), NPC_ANACHRONOS_THE_ANCIENT, QUEST_A_PAWN_ON_THE_ETERNAL_BOARD, WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_DESPAWN.
Referenced by AddSC_silithus().
Variable Documentation
aEternalBoardMovement
EventLocations aEternalBoardMovement[] static
Initial value:
=
{
    { -8159.951f, 1525.241f, 74.994f},
    { -8106.238f, 1525.948f, 2.639f},
    { -8103.861f, 1525.923f, 2.677f},
    { -8107.387f, 1523.641f, 2.609f},
    { -8100.921f, 1527.740f, 2.871f},
    { -8115.270f, 1515.926f, 3.305f},
    { -8116.879f, 1530.615f, 3.762f},
    { -7997.790f, 1548.664f, 3.738f},
    { -8061.933f, 1496.196f, 2.556f},
    { -8008.705f, 1446.063f, 44.104f},
}
Definition at line 215 of file silithus.cpp.
Referenced by npc_anachronos_the_ancientAI::JustDidDialogueStep(), npc_anachronos_the_ancientAI::SummonedMovementInform(), and npc_anachronos_the_ancientAI::UpdateAI().
aEternalBoardNPCs
EventLocations aEternalBoardNPCs[MAX_DRAGONS] static
Initial value:
=
{
    { -8029.301f, 1534.612f, 2.609f, 3.121f, NPC_FANDRAL_STAGHELM},
    { -8034.227f, 1536.580f, 2.609f, 6.161f, NPC_ARYGOS},
    { -8031.935f, 1532.658f, 2.609f, 1.012f, NPC_CAELESTRASZ},
    { -8034.106f, 1534.224f, 2.609f, 0.290f, NPC_MERITHRA_OF_THE_DREAM},
}
Definition at line 200 of file silithus.cpp.
Referenced by npc_anachronos_the_ancientAI::DoInitialSummons().
aEventDialogue
const DialogueEntry aEventDialogue[] static
Definition at line 136 of file silithus.cpp.
aQirajiWarriors
EventLocations aQirajiWarriors[MAX_CONQUERORS] static
Initial value:
=
{
    { -8092.12f, 1508.32f, 2.94f, 0.0f, 0 },
    { -8096.54f, 1525.84f, 2.83f, 0.0f, 0 },
    { -8097.81f, 1541.74f, 2.88f, 0.0f, 0 },
}
Definition at line 208 of file silithus.cpp.
Referenced by npc_anachronos_the_ancientAI::DoInitialSummons(), npc_anachronos_the_ancientAI::DoSummonKaldorei(), and npc_anachronos_the_ancientAI::DoSummonQiraji().