CMaNGOS_WoTLK: silverpine_forest.cpp File Reference
silverpine_forest.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_deathstalker_erlandAI
struct SpawnPoint
struct npc_deathstalker_faerleiaAI
Enumerations
enum {
SAY_START_1 = -1000306 , SAY_START_2 = -1000307 , SAY_AGGRO_1 = -1000308 , SAY_AGGRO_2 = -1000309 ,
SAY_AGGRO_3 = -1000310 , SAY_PROGRESS = -1000311 , SAY_END = -1000312 , SAY_RANE = -1000313 ,
SAY_RANE_REPLY = -1000314 , SAY_CHECK_NEXT = -1000315 , SAY_QUINN = -1000316 , SAY_QUINN_REPLY = -1000317 ,
SAY_BYE = -1000318 , QUEST_ERLAND = 435 , NPC_RANE = 1950 , NPC_QUINN = 1951
}
enum {
QUEST_PYREWOOD_AMBUSH = 452 , SPELL_DRINK_POTION = 3359 , SAY_START = -1000553 , SAY_COMPLETED = -1000554 ,
NPC_COUNCILMAN_SMITHERS = 2060 , NPC_COUNCILMAN_THATHER = 2061 , NPC_COUNCILMAN_HENDRICKS = 2062 , NPC_COUNCILMAN_WILHELM = 2063 ,
NPC_COUNCILMAN_HARTIN = 2064 , NPC_COUNCILMAN_HIGARTH = 2066 , NPC_COUNCILMAN_COOPER = 2065 , NPC_COUNCILMAN_BRUNSWICK = 2067 ,
NPC_LORD_MAYOR_MORRISON = 2068
}
Functions
bool QuestAccept_npc_deathstalker_erland (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_deathstalker_erland (Creature *pCreature)
bool QuestAccept_npc_deathstalker_faerleia (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_deathstalker_faerleia (Creature *pCreature)
void AddSC_silverpine_forest ()
Variables
SpawnPoint SpawnPoints []
static float m_afMoveCoords [] = { -410.69f, 1498.04f, 19.77f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_START_1
SAY_START_2
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_PROGRESS
SAY_END
SAY_RANE
SAY_RANE_REPLY
SAY_CHECK_NEXT
SAY_QUINN
SAY_QUINN_REPLY
SAY_BYE
QUEST_ERLAND
NPC_RANE
NPC_QUINN
Definition at line 36 of file silverpine_forest.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_PYREWOOD_AMBUSH
SPELL_DRINK_POTION
SAY_START
SAY_COMPLETED
NPC_COUNCILMAN_SMITHERS
NPC_COUNCILMAN_THATHER
NPC_COUNCILMAN_HENDRICKS
NPC_COUNCILMAN_WILHELM
NPC_COUNCILMAN_HARTIN
NPC_COUNCILMAN_HIGARTH
NPC_COUNCILMAN_COOPER
NPC_COUNCILMAN_BRUNSWICK
NPC_LORD_MAYOR_MORRISON
Definition at line 134 of file silverpine_forest.cpp.
Function Documentation
AddSC_silverpine_forest()
void AddSC_silverpine_forest ()
Definition at line 308 of file silverpine_forest.cpp.
References Script::GetAI, GetAI_npc_deathstalker_erland(), GetAI_npc_deathstalker_faerleia(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_deathstalker_erland(), QuestAccept_npc_deathstalker_faerleia(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_deathstalker_erland()
UnitAI* GetAI_npc_deathstalker_erland (Creature * pCreature)
Definition at line 125 of file silverpine_forest.cpp.
Referenced by AddSC_silverpine_forest().
GetAI_npc_deathstalker_faerleia()
UnitAI* GetAI_npc_deathstalker_faerleia (Creature * pCreature)
Definition at line 303 of file silverpine_forest.cpp.
Referenced by AddSC_silverpine_forest().
QuestAccept_npc_deathstalker_erland()
bool QuestAccept_npc_deathstalker_erland (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 113 of file silverpine_forest.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_ERLAND, and SAY_START_1.
Referenced by AddSC_silverpine_forest().
QuestAccept_npc_deathstalker_faerleia()
bool QuestAccept_npc_deathstalker_faerleia (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 288 of file silverpine_forest.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_PYREWOOD_AMBUSH, SAY_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_silverpine_forest().
Variable Documentation
m_afMoveCoords
float m_afMoveCoords[] = { -410.69f, 1498.04f, 19.77f} static
Definition at line 174 of file silverpine_forest.cpp.
Referenced by npc_deathstalker_faerleiaAI::JustSummoned().
SpawnPoints
SpawnPoint SpawnPoints[]
Initial value:
=
{
    { -397.45f, 1509.56f, 18.87f, 4.73f},
    { -398.35f, 1510.75f, 18.87f, 4.76f},
    { -396.41f, 1511.06f, 18.87f, 4.74f}
}
Definition at line 167 of file silverpine_forest.cpp.
Referenced by npc_deathstalker_faerleiaAI::UpdateAI().