CMaNGOS_WoTLK: SkillExtraItems.cpp File Reference
SkillExtraItems.cpp File Reference
#include "Skills/SkillExtraItems.h"
#include "Database/DatabaseEnv.h"
#include "Log.h"
#include "Util/ProgressBar.h"
#include "Entities/Player.h"
#include "Server/DBCStores.h"
#include <map>
Data Structures
struct SkillExtraItemEntry
Typedefs
typedef std::map< uint32, SkillExtraItemEntry > SkillExtraItemMap
Functions
void LoadSkillExtraItemTable ()
bool canCreateExtraItems (Player *player, uint32 spellId, float &additionalChance, uint8 &additionalMax)
Variables
SkillExtraItemMap SkillExtraItemStore
Typedef Documentation
SkillExtraItemMap
typedef std::map<uint32, SkillExtraItemEntry> SkillExtraItemMap
Definition at line 50 of file SkillExtraItems.cpp.
Function Documentation
canCreateExtraItems()
bool canCreateExtraItems (Player * player, uint32 spellId, float & additionalChance, uint8 & additionalMax)
Definition at line 122 of file SkillExtraItems.cpp.
References SkillExtraItemEntry::additionalCreateChance, SkillExtraItemEntry::additionalMaxNum, Player::HasSpell(), SkillExtraItemEntry::requiredSpecialization, and SkillExtraItemStore.
Referenced by Spell::DoCreateItem().
LoadSkillExtraItemTable()
void LoadSkillExtraItemTable ()
Definition at line 55 of file SkillExtraItems.cpp.
References SkillExtraItemEntry::additionalCreateChance, SkillExtraItemEntry::additionalMaxNum, QueryResult::Fetch(), Field::GetFloat(), QueryResult::GetRowCount(), Field::GetUInt32(), Field::GetUInt8(), SQLStorage::LookupEntry(), QueryResult::NextRow(), Database::Query(), SkillExtraItemEntry::requiredSpecialization, SkillExtraItemStore, sLog, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
Referenced by ChatHandler::HandleReloadSkillExtraItemTemplateCommand(), and World::SetInitialWorldSettings().
Variable Documentation
SkillExtraItemStore
SkillExtraItemMap SkillExtraItemStore
Definition at line 52 of file SkillExtraItems.cpp.
Referenced by canCreateExtraItems(), and LoadSkillExtraItemTable().