CMaNGOS_WoTLK: SkillDiscovery.h File Reference
SkillDiscovery.h File Reference
#include "Common.h"
Functions
void LoadSkillDiscoveryTable ()
uint32 GetSkillDiscoverySpell (uint32 skillId, uint32 spellId, Player *player)
uint32 GetExplicitDiscoverySpell (uint32 spellId, Player *player)
Function Documentation
GetExplicitDiscoverySpell()
uint32 GetExplicitDiscoverySpell (uint32 spellId, Player * player)
Definition at line 164 of file SkillDiscovery.cpp.
References Player::GetSkillValue(), Player::HasSpell(), rand_chance_f(), SkillDiscoveryStore, and sSpellMgr.
Referenced by Spell::EffectScriptEffect().
GetSkillDiscoverySpell()
uint32 GetSkillDiscoverySpell (uint32 skillId, uint32 spellId, Player * player)
Definition at line 201 of file SkillDiscovery.cpp.
References CONFIG_FLOAT_RATE_SKILL_DISCOVERY, Player::GetSkillValue(), Player::HasSpell(), roll_chance_f(), SkillDiscoveryStore, and sWorld.
Referenced by Player::UpdateCraftSkill().
LoadSkillDiscoveryTable()
void LoadSkillDiscoveryTable ()
Definition at line 49 of file SkillDiscovery.cpp.
References QueryResult::Fetch(), Field::GetFloat(), Field::GetInt32(), SQLStorageBase::GetMaxEntry(), QueryResult::GetRowCount(), Field::GetUInt32(), IsExplicitDiscoverySpell(), SQLStorage::LookupEntry(), SpellEntry::Mechanic, MECHANIC_DISCOVERY, QueryResult::NextRow(), Database::Query(), SkillDiscoveryStore, sLog, sSpellMgr, sSpellTemplate, BarGoLink::step(), and WorldDatabase.
Referenced by ChatHandler::HandleReloadSkillDiscoveryTemplateCommand(), and World::SetInitialWorldSettings().