CMaNGOS_WoTLK: slave_pens.cpp File Reference
slave_pens.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "slave_pens.h"
#include "World/WorldStateDefines.h"
Enumerations
enum { SAY_AREATRIGGER = -1547000 , GOSSIP_CAGED = 7520 , GOSSIP_RELEASED = 7540 , FACTION_RELEASED = 113 }
Functions
bool AreaTrigger_at_naturalist_bite (Player *player, AreaTriggerEntry const *)
bool GossipHello_npc_naturalist_bite (Player *player, Creature *creature)
void AddSC_instance_slave_pens ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AREATRIGGER
GOSSIP_CAGED
GOSSIP_RELEASED
FACTION_RELEASED
Definition at line 104 of file slave_pens.cpp.
Function Documentation
AddSC_instance_slave_pens()
void AddSC_instance_slave_pens ()
Definition at line 138 of file slave_pens.cpp.
References AreaTrigger_at_naturalist_bite(), Script::GetInstanceData, GossipHello_npc_naturalist_bite(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_naturalist_bite()
bool AreaTrigger_at_naturalist_bite (Player * player, AreaTriggerEntry const *)
Definition at line 114 of file slave_pens.cpp.
References DATA_NATURALIST, DoScriptText(), InstanceData::GetData(), Map::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_NATURALIST_BITE, SAY_AREATRIGGER, and InstanceData::SetData().
Referenced by AddSC_instance_slave_pens().
GossipHello_npc_naturalist_bite()
bool GossipHello_npc_naturalist_bite (Player * player, Creature * creature)
Definition at line 128 of file slave_pens.cpp.
References FACTION_RELEASED, Unit::GetFaction(), GOSSIP_CAGED, GOSSIP_RELEASED, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_instance_slave_pens().