CMaNGOS_WoTLK: soapC.cpp File Reference
soapC.cpp File Reference
#include "soapH.h"
Functions
SOAP_FMAC3 int SOAP_FMAC4 soap_getheader (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_putheader (struct soap *soap)
SOAP_FMAC3 void SOAP_FMAC4 soap_serializeheader (struct soap *soap)
SOAP_FMAC3 void SOAP_FMAC4 soap_header (struct soap *soap)
SOAP_FMAC3 void SOAP_FMAC4 soap_fault (struct soap *soap)
SOAP_FMAC3 void SOAP_FMAC4 soap_serializefault (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_putfault (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_getfault (struct soap *soap)
SOAP_FMAC3 const char **SOAP_FMAC4 soap_faultcode (struct soap *soap)
SOAP_FMAC3 const char **SOAP_FMAC4 soap_faultsubcode (struct soap *soap)
SOAP_FMAC3 const char *SOAP_FMAC4 soap_check_faultsubcode (struct soap *soap)
SOAP_FMAC3 const char **SOAP_FMAC4 soap_faultstring (struct soap *soap)
SOAP_FMAC3 const char **SOAP_FMAC4 soap_faultdetail (struct soap *soap)
SOAP_FMAC3 const char *SOAP_FMAC4 soap_check_faultdetail (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap *soap)
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement (struct soap *soap, int *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap *soap, const void *ptr, const char *tag, int id, int type)
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap *soap, const void *ptr, int type)
SOAP_FMAC3 void *SOAP_FMAC4 soap_dupelement (struct soap *soap, const void *ptr, int type)
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void *ptr, int type)
SOAP_FMAC3 void *SOAP_FMAC4 soap_instantiate (struct soap *soap, int t, const char *type, const char *arrayType, size_t *n)
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap_clist *p)
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int t, int b)
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap *soap, int t, int tt, void *p, size_t index, const void *q, void **x)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap *soap, const char *tag, int id, const char *a, const char *type)
SOAP_FMAC3 char *SOAP_FMAC4 soap_in_byte (struct soap *soap, const char *tag, char *a, const char *type)
SOAP_FMAC3 char *SOAP_FMAC4 soap_new_byte (struct soap *soap, int n)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap *soap, const char *a, const char *tag, const char *type)
SOAP_FMAC3 char *SOAP_FMAC4 soap_get_byte (struct soap *soap, char *p, const char *tag, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap *soap, const char *tag, int id, const int *a, const char *type)
SOAP_FMAC3 int *SOAP_FMAC4 soap_in_int (struct soap *soap, const char *tag, int *a, const char *type)
SOAP_FMAC3 int *SOAP_FMAC4 soap_new_int (struct soap *soap, int n)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap *soap, const int *a, const char *tag, const char *type)
SOAP_FMAC3 int *SOAP_FMAC4 soap_get_int (struct soap *soap, int *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap *soap, const struct SOAP_ENV__Fault *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Fault *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap *soap, const char *tag, struct SOAP_ENV__Fault *a, const char *type)
SOAP_FMAC1 struct SOAP_ENV__Fault *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap *soap, const struct SOAP_ENV__Fault *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap *soap, const struct SOAP_ENV__Reason *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Reason *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap *soap, const char *tag, struct SOAP_ENV__Reason *a, const char *type)
SOAP_FMAC1 struct SOAP_ENV__Reason *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap *soap, const struct SOAP_ENV__Reason *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap *soap, const struct SOAP_ENV__Detail *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Detail *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap *soap, const char *tag, struct SOAP_ENV__Detail *a, const char *type)
SOAP_FMAC1 struct SOAP_ENV__Detail *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap *soap, const struct SOAP_ENV__Detail *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap *soap, const struct SOAP_ENV__Code *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Code *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap *soap, const char *tag, struct SOAP_ENV__Code *a, const char *type)
SOAP_FMAC1 struct SOAP_ENV__Code *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap *soap, const struct SOAP_ENV__Code *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap *soap, const struct SOAP_ENV__Header *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap *soap, const char *tag, int id, const struct SOAP_ENV__Header *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap *soap, const char *tag, struct SOAP_ENV__Header *a, const char *type)
SOAP_FMAC1 struct SOAP_ENV__Header *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap *soap, const struct SOAP_ENV__Header *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap *soap, const struct ns1__executeCommand *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap *soap, const char *tag, int id, const struct ns1__executeCommand *a, const char *type)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap *soap, const char *tag, struct ns1__executeCommand *a, const char *type)
SOAP_FMAC1 struct ns1__executeCommand *SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap *soap, const struct ns1__executeCommand *a, const char *tag, const char *type)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap *soap, const struct ns1__executeCommandResponse *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap *soap, const char *tag, int id, const struct ns1__executeCommandResponse *a, const char *type)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap *soap, const char *tag, struct ns1__executeCommandResponse *a, const char *type)
SOAP_FMAC1 struct ns1__executeCommandResponse *SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap *soap, int n, const char *type, const char *arrayType, size_t *size)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap *soap, const struct ns1__executeCommandResponse *a, const char *tag, const char *type)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap *soap, const char *tag, int id, struct SOAP_ENV__Reason *const *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap *soap, const char *tag, struct SOAP_ENV__Reason **a, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *const *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason **p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap *soap, const char *tag, int id, struct SOAP_ENV__Detail *const *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap *soap, const char *tag, struct SOAP_ENV__Detail **a, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *const *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail **p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap *soap, const char *tag, int id, struct SOAP_ENV__Code *const *a, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap *soap, const char *tag, struct SOAP_ENV__Code **a, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *const *a, const char *tag, const char *type)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code **p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap *soap, char **const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap *soap, const char *tag, int id, char **const *a, const char *type)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_in_PointerTostring (struct soap *soap, const char *tag, char ***a, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap *soap, char **const *a, const char *tag, const char *type)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_get_PointerTostring (struct soap *soap, char ***p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap *soap, char *const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap *soap, const char *tag, int id, char *const *a, const char *type)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in__QName (struct soap *soap, const char *tag, char **a, const char *type)
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap *soap, char *const *a, const char *tag, const char *type)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get__QName (struct soap *soap, char **p, const char *tag, const char *type)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap *soap, char *const *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap *soap, const char *tag, int id, char *const *a, const char *type)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in_string (struct soap *soap, const char *tag, char **a, const char *type)
SOAP_FMAC3 char **SOAP_FMAC4 soap_new_string (struct soap *soap, int n)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap *soap, char *const *a, const char *tag, const char *type)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get_string (struct soap *soap, char **p, const char *tag, const char *type)
Function Documentation
soap_check_faultdetail()
SOAP_FMAC3 const char* SOAP_FMAC4 soap_check_faultdetail (struct soap * soap)
Definition at line 164 of file soapC.cpp.
References soap_fault().
soap_check_faultsubcode()
SOAP_FMAC3 const char* SOAP_FMAC4 soap_check_faultsubcode (struct soap * soap)
Definition at line 124 of file soapC.cpp.
References soap_fault().
soap_default_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * a)
Definition at line 1294 of file soapC.cpp.
References ns1__executeCommand::command, and soap_default_string().
Referenced by soap_in_ns1__executeCommand(), soap_new_req_ns1__executeCommand(), soap_new_set_ns1__executeCommand(), soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_default_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * a)
Definition at line 1396 of file soapC.cpp.
References ns1__executeCommandResponse::result.
Referenced by soap_in_ns1__executeCommandResponse(), soap_new_req_ns1__executeCommandResponse(), soap_new_set_ns1__executeCommandResponse(), soap_read_ns1__executeCommandResponse(), and soap_serve_ns1__executeCommand().
soap_default_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * a)
Definition at line 1083 of file soapC.cpp.
References soap_default__QName(), SOAP_ENV__Code::SOAP_ENV__Subcode, and SOAP_ENV__Code::SOAP_ENV__Value.
Referenced by soap_in_SOAP_ENV__Code(), soap_instantiate_ns1__executeCommand(), soap_instantiate_SOAP_ENV__Code(), soap_new_req_SOAP_ENV__Code(), soap_new_set_SOAP_ENV__Code(), and soap_read_SOAP_ENV__Code().
soap_default_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * a)
Definition at line 965 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, and SOAP_ENV__Detail::fault.
Referenced by soap_faultdetail(), soap_in_SOAP_ENV__Detail(), soap_instantiate_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Detail(), soap_new_set_SOAP_ENV__Detail(), and soap_read_SOAP_ENV__Detail().
soap_default_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * a)
Definition at line 646 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default__QName(), soap_default_string(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, and SOAP_ENV__Fault::SOAP_ENV__Role.
Referenced by soap_fault(), soap_in_SOAP_ENV__Fault(), soap_new_req_SOAP_ENV__Fault(), soap_new_set_SOAP_ENV__Fault(), and soap_read_SOAP_ENV__Fault().
soap_default_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * a)
Definition at line 1203 of file soapC.cpp.
Referenced by soap_header(), soap_in_SOAP_ENV__Header(), soap_new_req_SOAP_ENV__Header(), soap_new_set_SOAP_ENV__Header(), and soap_read_SOAP_ENV__Header().
soap_default_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * a)
Definition at line 857 of file soapC.cpp.
References soap_default_string(), and SOAP_ENV__Reason::SOAP_ENV__Text.
Referenced by soap_in_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Reason(), soap_new_set_SOAP_ENV__Reason(), and soap_read_SOAP_ENV__Reason().
soap_delelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void * ptr, int type)
Definition at line 401 of file soapC.cpp.
soap_dupelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_dupelement (struct soap * soap, const void * ptr, int type)
Definition at line 388 of file soapC.cpp.
soap_fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_fault (struct soap * soap)
Definition at line 61 of file soapC.cpp.
References soap_default_SOAP_ENV__Fault(), and soap_new_SOAP_ENV__Fault().
Referenced by soap_check_faultdetail(), soap_check_faultsubcode(), soap_faultcode(), soap_faultdetail(), soap_faultstring(), soap_faultsubcode(), and soap_serializefault().
soap_faultcode()
SOAP_FMAC3 const char** SOAP_FMAC4 soap_faultcode (struct soap * soap)
Definition at line 101 of file soapC.cpp.
References soap_fault().
soap_faultdetail()
SOAP_FMAC3 const char** SOAP_FMAC4 soap_faultdetail (struct soap * soap)
Definition at line 144 of file soapC.cpp.
References soap_default_SOAP_ENV__Detail(), soap_fault(), and soap_new_SOAP_ENV__Detail().
soap_faultstring()
SOAP_FMAC3 const char** SOAP_FMAC4 soap_faultstring (struct soap * soap)
Definition at line 136 of file soapC.cpp.
References soap_fault().
soap_faultsubcode()
SOAP_FMAC3 const char** SOAP_FMAC4 soap_faultsubcode (struct soap * soap)
Definition at line 109 of file soapC.cpp.
References soap_fault().
soap_fbase()
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int t, int b)
Definition at line 509 of file soapC.cpp.
soap_fdelete()
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap_clist * p)
Definition at line 442 of file soapC.cpp.
References SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
soap_finsert()
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap * soap, int t, int tt, void * p, size_t index, const void * q, void ** x)
Definition at line 524 of file soapC.cpp.
References SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_get__QName()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get__QName (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1763 of file soapC.cpp.
References soap_getindependent(), and soap_in__QName().
Referenced by soap_read__QName().
soap_get_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_get_byte (struct soap * soap, char * p, const char * tag, const char * type)
Definition at line 602 of file soapC.cpp.
References soap_getindependent(), and soap_in_byte().
Referenced by soap_read_byte().
soap_get_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_get_int (struct soap * soap, int * p, const char * tag, const char * type)
Definition at line 636 of file soapC.cpp.
References soap_getindependent(), and soap_in_int().
Referenced by soap_read_int().
soap_get_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p, const char * tag, const char * type)
Definition at line 1388 of file soapC.cpp.
References soap_getindependent(), and soap_in_ns1__executeCommand().
Referenced by soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_get_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p, const char * tag, const char * type)
Definition at line 1490 of file soapC.cpp.
References soap_getindependent(), and soap_in_ns1__executeCommandResponse().
Referenced by soap_read_ns1__executeCommandResponse().
soap_get_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code ** p, const char * tag, const char * type)
Definition at line 1671 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Code().
soap_get_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail ** p, const char * tag, const char * type)
Definition at line 1608 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Detail().
soap_get_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason ** p, const char * tag, const char * type)
Definition at line 1548 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Reason().
soap_get_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_get_PointerTostring (struct soap * soap, char *** p, const char * tag, const char * type)
Definition at line 1729 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerTostring().
soap_get_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p, const char * tag, const char * type)
Definition at line 1191 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Code().
Referenced by soap_read_SOAP_ENV__Code().
soap_get_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p, const char * tag, const char * type)
Definition at line 1071 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Detail().
Referenced by soap_read_SOAP_ENV__Detail().
soap_get_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p, const char * tag, const char * type)
Definition at line 845 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Fault().
Referenced by soap_getfault(), and soap_read_SOAP_ENV__Fault().
soap_get_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p, const char * tag, const char * type)
Definition at line 1284 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Header().
Referenced by soap_read_SOAP_ENV__Header().
soap_get_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p, const char * tag, const char * type)
Definition at line 953 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Reason().
Referenced by soap_read_SOAP_ENV__Reason().
soap_get_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get_string (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1805 of file soapC.cpp.
References soap_getindependent(), and soap_in_string().
Referenced by soap_read_string().
soap_getelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_getelement (struct soap * soap, int * type)
Definition at line 198 of file soapC.cpp.
References soap_in__QName(), soap_in_byte(), soap_in_int(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_PointerTostring(), soap_in_string(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_getindependent(), soap_ignore_element(), and soap_in_SOAP_ENV__Detail().
soap_getfault()
SOAP_FMAC3 int SOAP_FMAC4 soap_getfault (struct soap * soap)
Definition at line 96 of file soapC.cpp.
References soap_get_SOAP_ENV__Fault().
soap_getheader()
SOAP_FMAC3 int SOAP_FMAC4 soap_getheader (struct soap * soap)
Definition at line 26 of file soapC.cpp.
References soap_in_SOAP_ENV__Header().
soap_getindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap * soap)
Definition at line 177 of file soapC.cpp.
References soap_getelement(), and soap_ignore_element().
Referenced by soap_get__QName(), soap_get_byte(), soap_get_int(), soap_get_ns1__executeCommand(), soap_get_ns1__executeCommandResponse(), soap_get_PointerToSOAP_ENV__Code(), soap_get_PointerToSOAP_ENV__Detail(), soap_get_PointerToSOAP_ENV__Reason(), soap_get_PointerTostring(), soap_get_SOAP_ENV__Code(), soap_get_SOAP_ENV__Detail(), soap_get_SOAP_ENV__Fault(), soap_get_SOAP_ENV__Header(), soap_get_SOAP_ENV__Reason(), and soap_get_string().
soap_header()
SOAP_FMAC3 void SOAP_FMAC4 soap_header (struct soap * soap)
Definition at line 52 of file soapC.cpp.
References soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
soap_ignore_element()
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap * soap)
Definition at line 281 of file soapC.cpp.
References soap_getelement().
Referenced by soap_getindependent(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_in__QName()
SOAP_FMAC3 char** SOAP_FMAC4 soap_in__QName (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1750 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_get__QName(), soap_getelement(), soap_in_SOAP_ENV__Code(), and soap_in_SOAP_ENV__Fault().
soap_in_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_in_byte (struct soap * soap, const char * tag, char * a, const char * type)
Definition at line 581 of file soapC.cpp.
References SOAP_TYPE_byte.
Referenced by soap_get_byte(), and soap_getelement().
soap_in_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_in_int (struct soap * soap, const char * tag, int * a, const char * type)
Definition at line 615 of file soapC.cpp.
References SOAP_TYPE_int.
Referenced by soap_get_int(), and soap_getelement().
soap_in_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap * soap, const char * tag, struct ns1__executeCommand * a, const char * type)
Definition at line 1318 of file soapC.cpp.
References ns1__executeCommand::command, soap_default_ns1__executeCommand(), soap_finsert(), soap_ignore_element(), soap_in_string(), and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_get_ns1__executeCommand(), and soap_getelement().
soap_in_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap * soap, const char * tag, struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1420 of file soapC.cpp.
References ns1__executeCommandResponse::result, soap_default_ns1__executeCommandResponse(), soap_finsert(), soap_ignore_element(), soap_in_PointerTostring(), and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_get_ns1__executeCommandResponse(), and soap_getelement().
soap_in_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code ** a, const char * type)
Definition at line 1640 of file soapC.cpp.
References soap_in_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_PointerToSOAP_ENV__Code(), soap_in_SOAP_ENV__Code(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail ** a, const char * type)
Definition at line 1577 of file soapC.cpp.
References soap_in_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_PointerToSOAP_ENV__Detail(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason ** a, const char * type)
Definition at line 1517 of file soapC.cpp.
References soap_in_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_PointerToSOAP_ENV__Reason(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_in_PointerTostring (struct soap * soap, const char * tag, char *** a, const char * type)
Definition at line 1698 of file soapC.cpp.
References soap_in_string(), and SOAP_TYPE_string.
Referenced by soap_get_PointerTostring(), soap_getelement(), and soap_in_ns1__executeCommandResponse().
soap_in_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code * a, const char * type)
Definition at line 1112 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_finsert(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_SOAP_ENV__Code(), and soap_in_PointerToSOAP_ENV__Code().
soap_in_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail * a, const char * type)
Definition at line 992 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), soap_finsert(), soap_getelement(), soap_ignore_element(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_SOAP_ENV__Detail(), and soap_in_PointerToSOAP_ENV__Detail().
soap_in_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap * soap, const char * tag, struct SOAP_ENV__Fault * a, const char * type)
Definition at line 703 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default_SOAP_ENV__Fault(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_finsert(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), soap_in_PointerToSOAP_ENV__Detail(), soap_in_PointerToSOAP_ENV__Reason(), soap_in_string(), and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_get_SOAP_ENV__Fault().
soap_in_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap * soap, const char * tag, struct SOAP_ENV__Header * a, const char * type)
Definition at line 1223 of file soapC.cpp.
References soap_default_SOAP_ENV__Header(), soap_finsert(), soap_ignore_element(), and SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_get_SOAP_ENV__Header(), and soap_getheader().
soap_in_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason * a, const char * type)
Definition at line 883 of file soapC.cpp.
References soap_default_SOAP_ENV__Reason(), SOAP_ENV__Reason::SOAP_ENV__Text, soap_finsert(), soap_ignore_element(), soap_in_string(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_SOAP_ENV__Reason(), and soap_in_PointerToSOAP_ENV__Reason().
soap_in_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_in_string (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1784 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_get_string(), soap_getelement(), soap_in_ns1__executeCommand(), soap_in_PointerTostring(), soap_in_SOAP_ENV__Fault(), and soap_in_SOAP_ENV__Reason().
soap_instantiate()
SOAP_FMAC3 void* SOAP_FMAC4 soap_instantiate (struct soap * soap, int t, const char * type, const char * arrayType, size_t * n)
Definition at line 409 of file soapC.cpp.
References soap_instantiate_ns1__executeCommand(), soap_instantiate_ns1__executeCommandResponse(), soap_instantiate_SOAP_ENV__Code(), soap_instantiate_SOAP_ENV__Detail(), soap_instantiate_SOAP_ENV__Fault(), soap_instantiate_SOAP_ENV__Header(), soap_instantiate_SOAP_ENV__Reason(), SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
soap_instantiate_ns1__executeCommand()
SOAP_FMAC1 struct ns1__executeCommand* SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 1359 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
Referenced by soap_instantiate(), and soap_new_ns1__executeCommand().
soap_instantiate_ns1__executeCommandResponse()
SOAP_FMAC1 struct ns1__executeCommandResponse* SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 1461 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_ns1__executeCommandResponse().
soap_instantiate_SOAP_ENV__Code()
SOAP_FMAC1 struct SOAP_ENV__Code* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 1162 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Code().
soap_instantiate_SOAP_ENV__Detail()
SOAP_FMAC1 struct SOAP_ENV__Detail* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 1042 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Detail().
soap_instantiate_SOAP_ENV__Fault()
SOAP_FMAC1 struct SOAP_ENV__Fault* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 816 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Fault().
soap_instantiate_SOAP_ENV__Header()
SOAP_FMAC1 struct SOAP_ENV__Header* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 1255 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Header().
soap_instantiate_SOAP_ENV__Reason()
SOAP_FMAC1 struct SOAP_ENV__Reason* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 924 of file soapC.cpp.
References soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Reason().
soap_markelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap * soap, const void * ptr, int type)
Definition at line 357 of file soapC.cpp.
References soap_serialize_ns1__executeCommand(), soap_serialize_ns1__executeCommandResponse(), soap_serialize_PointerTostring(), soap_serialize_string(), SOAP_TYPE__QName, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_serialize_SOAP_ENV__Detail().
soap_new_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_new_byte (struct soap * soap, int n)
Definition at line 587 of file soapC.cpp.
References soap_default_byte().
soap_new_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_new_int (struct soap * soap, int n)
Definition at line 621 of file soapC.cpp.
References soap_default_int().
soap_new_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_new_string (struct soap * soap, int n)
Definition at line 1790 of file soapC.cpp.
References soap_default_string().
soap_out__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1745 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put__QName().
soap_out_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap * soap, const char * tag, int id, const char * a, const char * type)
Definition at line 576 of file soapC.cpp.
References SOAP_TYPE_byte.
Referenced by soap_put_byte(), and soap_putelement().
soap_out_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap * soap, const char * tag, int id, const int * a, const char * type)
Definition at line 610 of file soapC.cpp.
References SOAP_TYPE_int.
Referenced by soap_put_int(), and soap_putelement().
soap_out_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap * soap, const char * tag, int id, const struct ns1__executeCommand * a, const char * type)
Definition at line 1308 of file soapC.cpp.
References ns1__executeCommand::command, soap_out_string(), and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_put_ns1__executeCommand(), and soap_putelement().
soap_out_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap * soap, const char * tag, int id, const struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1410 of file soapC.cpp.
References ns1__executeCommandResponse::result, soap_out_PointerTostring(), and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_put_ns1__executeCommandResponse(), and soap_putelement().
soap_out_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Code *const * a, const char * type)
Definition at line 1629 of file soapC.cpp.
References soap_out_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Code().
soap_out_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Detail *const * a, const char * type)
Definition at line 1569 of file soapC.cpp.
References soap_out_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Detail().
soap_out_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Reason *const * a, const char * type)
Definition at line 1509 of file soapC.cpp.
References soap_out_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Reason().
soap_out_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap * soap, const char * tag, int id, char **const * a, const char * type)
Definition at line 1690 of file soapC.cpp.
References soap_out_string(), and SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommandResponse(), soap_put_PointerTostring(), and soap_putelement().
soap_out_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Code * a, const char * type)
Definition at line 1099 of file soapC.cpp.
References SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_out_PointerToSOAP_ENV__Code(), and soap_put_SOAP_ENV__Code().
soap_out_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Detail * a, const char * type)
Definition at line 981 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_putelement(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_PointerToSOAP_ENV__Detail(), and soap_put_SOAP_ENV__Detail().
soap_out_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Fault * a, const char * type)
Definition at line 676 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), soap_out_PointerToSOAP_ENV__Detail(), soap_out_PointerToSOAP_ENV__Reason(), soap_out_string(), and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_put_SOAP_ENV__Fault().
soap_out_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Header * a, const char * type)
Definition at line 1215 of file soapC.cpp.
References SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_put_SOAP_ENV__Header(), and soap_putheader().
soap_out_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Reason * a, const char * type)
Definition at line 871 of file soapC.cpp.
References SOAP_ENV__Reason::SOAP_ENV__Text, soap_out_string(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_PointerToSOAP_ENV__Reason(), and soap_put_SOAP_ENV__Reason().
soap_out_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1779 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommand(), soap_out_PointerTostring(), soap_out_SOAP_ENV__Fault(), soap_out_SOAP_ENV__Reason(), soap_put_string(), and soap_putelement().
soap_put__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1756 of file soapC.cpp.
References soap_out__QName(), and soap_putindependent().
Referenced by soap_POST_send__QName(), soap_PUT__QName(), and soap_write__QName().
soap_put_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap * soap, const char * a, const char * tag, const char * type)
Definition at line 595 of file soapC.cpp.
References soap_out_byte(), and soap_putindependent().
Referenced by soap_POST_send_byte(), soap_PUT_byte(), and soap_write_byte().
soap_put_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap * soap, const int * a, const char * tag, const char * type)
Definition at line 629 of file soapC.cpp.
References soap_out_int(), and soap_putindependent().
Referenced by soap_POST_send_int(), soap_PUT_int(), and soap_write_int().
soap_put_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a, const char * tag, const char * type)
Definition at line 1381 of file soapC.cpp.
References soap_out_ns1__executeCommand(), and soap_putindependent().
Referenced by soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_put_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a, const char * tag, const char * type)
Definition at line 1483 of file soapC.cpp.
References soap_out_ns1__executeCommandResponse(), and soap_putindependent().
Referenced by soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_put_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a, const char * tag, const char * type)
Definition at line 1664 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Code(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a, const char * tag, const char * type)
Definition at line 1601 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Detail(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a, const char * tag, const char * type)
Definition at line 1541 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Reason(), and soap_putindependent().
soap_put_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap * soap, char **const * a, const char * tag, const char * type)
Definition at line 1722 of file soapC.cpp.
References soap_out_PointerTostring(), and soap_putindependent().
soap_put_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a, const char * tag, const char * type)
Definition at line 1184 of file soapC.cpp.
References soap_out_SOAP_ENV__Code(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_put_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a, const char * tag, const char * type)
Definition at line 1064 of file soapC.cpp.
References soap_out_SOAP_ENV__Detail(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_put_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a, const char * tag, const char * type)
Definition at line 838 of file soapC.cpp.
References soap_out_SOAP_ENV__Fault(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_putfault(), and soap_write_SOAP_ENV__Fault().
soap_put_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a, const char * tag, const char * type)
Definition at line 1277 of file soapC.cpp.
References soap_out_SOAP_ENV__Header(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), and soap_write_SOAP_ENV__Header().
soap_put_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a, const char * tag, const char * type)
Definition at line 946 of file soapC.cpp.
References soap_out_SOAP_ENV__Reason(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_put_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1798 of file soapC.cpp.
References soap_out_string(), and soap_putindependent().
Referenced by soap_POST_send_string(), soap_PUT_string(), and soap_write_string().
soap_putelement()
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap * soap, const void * ptr, const char * tag, int id, int type)
Definition at line 325 of file soapC.cpp.
References soap_out_byte(), soap_out_int(), soap_out_ns1__executeCommand(), soap_out_ns1__executeCommandResponse(), soap_out_PointerTostring(), soap_out_string(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_out_SOAP_ENV__Detail(), and soap_putindependent().
soap_putfault()
SOAP_FMAC3 int SOAP_FMAC4 soap_putfault (struct soap * soap)
Definition at line 89 of file soapC.cpp.
References soap_put_SOAP_ENV__Fault().
soap_putheader()
SOAP_FMAC3 int SOAP_FMAC4 soap_putheader (struct soap * soap)
Definition at line 34 of file soapC.cpp.
References soap_out_SOAP_ENV__Header().
Referenced by soap_serve_ns1__executeCommand().
soap_putindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap * soap)
Definition at line 310 of file soapC.cpp.
References soap_putelement().
Referenced by soap_put__QName(), soap_put_byte(), soap_put_int(), soap_put_ns1__executeCommand(), soap_put_ns1__executeCommandResponse(), soap_put_PointerToSOAP_ENV__Code(), soap_put_PointerToSOAP_ENV__Detail(), soap_put_PointerToSOAP_ENV__Reason(), soap_put_PointerTostring(), soap_put_SOAP_ENV__Code(), soap_put_SOAP_ENV__Detail(), soap_put_SOAP_ENV__Fault(), soap_put_SOAP_ENV__Header(), soap_put_SOAP_ENV__Reason(), and soap_put_string().
soap_serialize__QName()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap * soap, char *const * a)
Definition at line 1737 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a)
Definition at line 1300 of file soapC.cpp.
References ns1__executeCommand::command, and soap_serialize_string().
Referenced by soap_markelement(), soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_serialize_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a)
Definition at line 1402 of file soapC.cpp.
References ns1__executeCommandResponse::result, and soap_serialize_PointerTostring().
Referenced by soap_markelement(), soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_serialize_PointerToSOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a)
Definition at line 1620 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a)
Definition at line 1560 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a)
Definition at line 1500 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerTostring()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap * soap, char **const * a)
Definition at line 1681 of file soapC.cpp.
References soap_serialize_string(), and SOAP_TYPE_string.
Referenced by soap_markelement(), and soap_serialize_ns1__executeCommandResponse().
soap_serialize_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a)
Definition at line 1090 of file soapC.cpp.
References SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_serialize__QName(), and soap_serialize_PointerToSOAP_ENV__Code().
Referenced by soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_serialize_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a)
Definition at line 973 of file soapC.cpp.
References SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, and soap_markelement().
Referenced by soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_serialize_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a)
Definition at line 660 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_serialize__QName(), soap_serialize_PointerToSOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_serialize_string().
Referenced by soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_serializefault(), and soap_write_SOAP_ENV__Fault().
soap_serialize_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a)
Definition at line 1208 of file soapC.cpp.
Referenced by soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), soap_serializeheader(), and soap_write_SOAP_ENV__Header().
soap_serialize_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a)
Definition at line 863 of file soapC.cpp.
References SOAP_ENV__Reason::SOAP_ENV__Text, and soap_serialize_string().
Referenced by soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_serialize_string()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap * soap, char *const * a)
Definition at line 1771 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_markelement(), soap_serialize_ns1__executeCommand(), soap_serialize_PointerTostring(), soap_serialize_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Reason().
soap_serializefault()
SOAP_FMAC3 void SOAP_FMAC4 soap_serializefault (struct soap * soap)
Definition at line 82 of file soapC.cpp.
References soap_fault(), and soap_serialize_SOAP_ENV__Fault().
soap_serializeheader()
SOAP_FMAC3 void SOAP_FMAC4 soap_serializeheader (struct soap * soap)
Definition at line 46 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Header().
Referenced by soap_serve_ns1__executeCommand().