CMaNGOS_WoTLK: soapH.h File Reference
soapH.h File Reference
#include "soapStub.h"
Macros
#define SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_ns1__executeCommand_DEFINED
#define SOAP_TYPE_ns1__executeCommandResponse_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerTostring_DEFINED
#define SOAP_TYPE__QName_DEFINED
#define soap__QName2s(soap, a) soap_QName2s(soap, (a))
#define soap_s2_QName(soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
#define soap_instantiate__QName soap_instantiate_string
#define soap_new__QName soap_new_string
#define SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE_string_DEFINED
#define soap_string2s(soap, a) (a)
#define soap_s2string(soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
Functions
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap *, const void *, int)
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap *)
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap *)
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement (struct soap *, int *)
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap *, const void *, const char *, int, int)
SOAP_FMAC3 void *SOAP_FMAC4 soap_dupelement (struct soap *, const void *, int)
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void *, int)
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap *)
SOAP_FMAC3 const char **SOAP_FMAC4 soap_faultcode (struct soap *soap)
SOAP_FMAC3 void *SOAP_FMAC4 soap_instantiate (struct soap *, int, const char *, const char *, size_t *)
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap_clist *)
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int, int)
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap *, int, int, void *, size_t, const void *, void **)
void soap_default_byte (struct soap *soap, char *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap *, const char *, int, const char *, const char *)
SOAP_FMAC3 char *SOAP_FMAC4 soap_in_byte (struct soap *, const char *, char *, const char *)
SOAP_FMAC3 char *SOAP_FMAC4 soap_new_byte (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap *, const char *, const char *, const char *)
int soap_write_byte (struct soap *soap, char const *p)
int soap_PUT_byte (struct soap *soap, const char *URL, char const *p)
int soap_POST_send_byte (struct soap *soap, const char *URL, char const *p)
SOAP_FMAC3 char *SOAP_FMAC4 soap_get_byte (struct soap *, char *, const char *, const char *)
int soap_read_byte (struct soap *soap, char *p)
int soap_GET_byte (struct soap *soap, const char *URL, char *p)
int soap_POST_recv_byte (struct soap *soap, char *p)
void soap_default_int (struct soap *soap, int *a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap *, const char *, int, const int *, const char *)
SOAP_FMAC3 int *SOAP_FMAC4 soap_in_int (struct soap *, const char *, int *, const char *)
SOAP_FMAC3 int *SOAP_FMAC4 soap_new_int (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap *, const int *, const char *, const char *)
int soap_write_int (struct soap *soap, int const *p)
int soap_PUT_int (struct soap *soap, const char *URL, int const *p)
int soap_POST_send_int (struct soap *soap, const char *URL, int const *p)
SOAP_FMAC3 int *SOAP_FMAC4 soap_get_int (struct soap *, int *, const char *, const char *)
int soap_read_int (struct soap *soap, int *p)
int soap_GET_int (struct soap *soap, const char *URL, int *p)
int soap_POST_recv_int (struct soap *soap, int *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap *, struct SOAP_ENV__Fault *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap *, const struct SOAP_ENV__Fault *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap *, const char *, int, const struct SOAP_ENV__Fault *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap *, const char *, struct SOAP_ENV__Fault *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Fault *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault (struct soap *soap, int n=-1)
struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault (struct soap *soap)
struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault (struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap *, const struct SOAP_ENV__Fault *, const char *, const char *)
int soap_write_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault const *p)
int soap_PUT_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault const *p)
int soap_POST_send_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault const *p)
SOAP_FMAC3 struct SOAP_ENV__Fault *SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap *, struct SOAP_ENV__Fault *, const char *, const char *)
int soap_read_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *p)
int soap_GET_SOAP_ENV__Fault (struct soap *soap, const char *URL, struct SOAP_ENV__Fault *p)
int soap_POST_recv_SOAP_ENV__Fault (struct soap *soap, struct SOAP_ENV__Fault *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap *, const struct SOAP_ENV__Reason *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap *, const char *, int, const struct SOAP_ENV__Reason *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap *, const char *, struct SOAP_ENV__Reason *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Reason *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason (struct soap *soap, int n=-1)
struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason (struct soap *soap)
struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason (struct soap *soap, char *SOAP_ENV__Text)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap *, const struct SOAP_ENV__Reason *, const char *, const char *)
int soap_write_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason const *p)
int soap_PUT_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason const *p)
int soap_POST_send_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason const *p)
SOAP_FMAC3 struct SOAP_ENV__Reason *SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *, const char *, const char *)
int soap_read_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *p)
int soap_GET_SOAP_ENV__Reason (struct soap *soap, const char *URL, struct SOAP_ENV__Reason *p)
int soap_POST_recv_SOAP_ENV__Reason (struct soap *soap, struct SOAP_ENV__Reason *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap *, const struct SOAP_ENV__Detail *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap *, const char *, int, const struct SOAP_ENV__Detail *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap *, const char *, struct SOAP_ENV__Detail *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Detail *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail (struct soap *soap, int n=-1)
struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail (struct soap *soap, int __type, void *fault)
struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail (struct soap *soap, char *__any, int __type, void *fault)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap *, const struct SOAP_ENV__Detail *, const char *, const char *)
int soap_write_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail const *p)
int soap_PUT_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail const *p)
int soap_POST_send_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail const *p)
SOAP_FMAC3 struct SOAP_ENV__Detail *SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *, const char *, const char *)
int soap_read_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *p)
int soap_GET_SOAP_ENV__Detail (struct soap *soap, const char *URL, struct SOAP_ENV__Detail *p)
int soap_POST_recv_SOAP_ENV__Detail (struct soap *soap, struct SOAP_ENV__Detail *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap *, const struct SOAP_ENV__Code *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap *, const char *, int, const struct SOAP_ENV__Code *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap *, const char *, struct SOAP_ENV__Code *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Code *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code (struct soap *soap, int n=-1)
struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code (struct soap *soap)
struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code (struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap *, const struct SOAP_ENV__Code *, const char *, const char *)
int soap_write_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code const *p)
int soap_PUT_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code const *p)
int soap_POST_send_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code const *p)
SOAP_FMAC3 struct SOAP_ENV__Code *SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *, const char *, const char *)
int soap_read_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *p)
int soap_GET_SOAP_ENV__Code (struct soap *soap, const char *URL, struct SOAP_ENV__Code *p)
int soap_POST_recv_SOAP_ENV__Code (struct soap *soap, struct SOAP_ENV__Code *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap *, struct SOAP_ENV__Header *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap *, const struct SOAP_ENV__Header *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap *, const char *, int, const struct SOAP_ENV__Header *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap *, const char *, struct SOAP_ENV__Header *, const char *)
SOAP_FMAC1 struct SOAP_ENV__Header *SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap *, int, const char *, const char *, size_t *)
struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header (struct soap *soap, int n=-1)
struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header (struct soap *soap)
struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header (struct soap *soap)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap *, const struct SOAP_ENV__Header *, const char *, const char *)
int soap_write_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header const *p)
int soap_PUT_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header const *p)
int soap_POST_send_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header const *p)
SOAP_FMAC3 struct SOAP_ENV__Header *SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap *, struct SOAP_ENV__Header *, const char *, const char *)
int soap_read_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *p)
int soap_GET_SOAP_ENV__Header (struct soap *soap, const char *URL, struct SOAP_ENV__Header *p)
int soap_POST_recv_SOAP_ENV__Header (struct soap *soap, struct SOAP_ENV__Header *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap *, struct ns1__executeCommand *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap *, const struct ns1__executeCommand *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap *, const char *, int, const struct ns1__executeCommand *, const char *)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap *, const char *, struct ns1__executeCommand *, const char *)
SOAP_FMAC1 struct ns1__executeCommand *SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap *, int, const char *, const char *, size_t *)
struct ns1__executeCommand * soap_new_ns1__executeCommand (struct soap *soap, int n=-1)
struct ns1__executeCommand * soap_new_req_ns1__executeCommand (struct soap *soap)
struct ns1__executeCommand * soap_new_set_ns1__executeCommand (struct soap *soap, char *command)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap *, const struct ns1__executeCommand *, const char *, const char *)
int soap_write_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand const *p)
int soap_PUT_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand const *p)
int soap_POST_send_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand const *p)
SOAP_FMAC3 struct ns1__executeCommand *SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap *, struct ns1__executeCommand *, const char *, const char *)
int soap_read_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *p)
int soap_GET_ns1__executeCommand (struct soap *soap, const char *URL, struct ns1__executeCommand *p)
int soap_POST_recv_ns1__executeCommand (struct soap *soap, struct ns1__executeCommand *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap *, struct ns1__executeCommandResponse *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap *, const struct ns1__executeCommandResponse *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap *, const char *, int, const struct ns1__executeCommandResponse *, const char *)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap *, const char *, struct ns1__executeCommandResponse *, const char *)
SOAP_FMAC1 struct ns1__executeCommandResponse *SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap *, int, const char *, const char *, size_t *)
struct ns1__executeCommandResponse * soap_new_ns1__executeCommandResponse (struct soap *soap, int n=-1)
struct ns1__executeCommandResponse * soap_new_req_ns1__executeCommandResponse (struct soap *soap)
struct ns1__executeCommandResponse * soap_new_set_ns1__executeCommandResponse (struct soap *soap, char **result)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap *, const struct ns1__executeCommandResponse *, const char *, const char *)
int soap_write_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse const *p)
int soap_PUT_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse const *p)
int soap_POST_send_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse const *p)
SOAP_FMAC3 struct ns1__executeCommandResponse *SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap *, struct ns1__executeCommandResponse *, const char *, const char *)
int soap_read_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *p)
int soap_GET_ns1__executeCommandResponse (struct soap *soap, const char *URL, struct ns1__executeCommandResponse *p)
int soap_POST_recv_ns1__executeCommandResponse (struct soap *soap, struct ns1__executeCommandResponse *p)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap *, const char *, int, struct SOAP_ENV__Reason *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap *, const char *, struct SOAP_ENV__Reason **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Reason **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap *, struct SOAP_ENV__Reason **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap *, const char *, int, struct SOAP_ENV__Detail *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap *, const char *, struct SOAP_ENV__Detail **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Detail **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap *, struct SOAP_ENV__Detail **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap *, const char *, int, struct SOAP_ENV__Code *const *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap *, const char *, struct SOAP_ENV__Code **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code *const *, const char *, const char *)
SOAP_FMAC3 struct SOAP_ENV__Code **SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap *, struct SOAP_ENV__Code **, const char *, const char *)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap *, char **const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap *, const char *, int, char **const *, const char *)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_in_PointerTostring (struct soap *, const char *, char ***, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap *, char **const *, const char *, const char *)
SOAP_FMAC3 char ***SOAP_FMAC4 soap_get_PointerTostring (struct soap *, char ***, const char *, const char *)
void soap_default__QName (struct soap *soap, char **a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap *, char *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap *, const char *, int, char *const *, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in__QName (struct soap *, const char *, char **, const char *)
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap *, char *const *, const char *, const char *)
int soap_write__QName (struct soap *soap, char *const *p)
int soap_PUT__QName (struct soap *soap, const char *URL, char *const *p)
int soap_POST_send__QName (struct soap *soap, const char *URL, char *const *p)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get__QName (struct soap *, char **, const char *, const char *)
int soap_read__QName (struct soap *soap, char **p)
int soap_GET__QName (struct soap *soap, const char *URL, char **p)
int soap_POST_recv__QName (struct soap *soap, char **p)
void soap_default_string (struct soap *soap, char **a)
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap *, char *const *)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap *, const char *, int, char *const *, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_in_string (struct soap *, const char *, char **, const char *)
SOAP_FMAC3 char **SOAP_FMAC4 soap_new_string (struct soap *soap, int n=-1)
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap *, char *const *, const char *, const char *)
int soap_write_string (struct soap *soap, char *const *p)
int soap_PUT_string (struct soap *soap, const char *URL, char *const *p)
int soap_POST_send_string (struct soap *soap, const char *URL, char *const *p)
SOAP_FMAC3 char **SOAP_FMAC4 soap_get_string (struct soap *, char **, const char *, const char *)
int soap_read_string (struct soap *soap, char **p)
int soap_GET_string (struct soap *soap, const char *URL, char **p)
int soap_POST_recv_string (struct soap *soap, char **p)
Macro Definition Documentation
soap__QName2s
#define soap__QName2s (soap, a) soap_QName2s(soap, (a))
Definition at line 921 of file soapH.h.
soap_instantiate__QName
#define soap_instantiate__QName soap_instantiate_string
Definition at line 927 of file soapH.h.
soap_new__QName
#define soap_new__QName soap_new_string
Definition at line 930 of file soapH.h.
soap_s2_QName
#define soap_s2_QName (soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
Definition at line 924 of file soapH.h.
soap_s2string
#define soap_s2string (soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
Definition at line 1008 of file soapH.h.
soap_string2s
#define soap_string2s (soap, a) (a)
Definition at line 1005 of file soapH.h.
SOAP_TYPE__QName_DEFINED
#define SOAP_TYPE__QName_DEFINED
Definition at line 908 of file soapH.h.
SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE__XML_DEFINED
Definition at line 988 of file soapH.h.
SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_byte_DEFINED
Definition at line 51 of file soapH.h.
SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_int_DEFINED
Definition at line 122 of file soapH.h.
SOAP_TYPE_ns1__executeCommand_DEFINED
#define SOAP_TYPE_ns1__executeCommand_DEFINED
Definition at line 682 of file soapH.h.
SOAP_TYPE_ns1__executeCommandResponse_DEFINED
#define SOAP_TYPE_ns1__executeCommandResponse_DEFINED
Definition at line 771 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
Definition at line 888 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
Definition at line 875 of file soapH.h.
SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
Definition at line 862 of file soapH.h.
SOAP_TYPE_PointerTostring_DEFINED
#define SOAP_TYPE_PointerTostring_DEFINED
Definition at line 899 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
Definition at line 498 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
Definition at line 397 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
Definition at line 195 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
Definition at line 593 of file soapH.h.
SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
Definition at line 304 of file soapH.h.
SOAP_TYPE_string_DEFINED
#define SOAP_TYPE_string_DEFINED
Definition at line 992 of file soapH.h.
Function Documentation
soap_default__QName()
void soap_default__QName (struct soap * soap, char ** a) inline
Definition at line 910 of file soapH.h.
Referenced by soap_default_SOAP_ENV__Code(), and soap_default_SOAP_ENV__Fault().
soap_default_byte()
void soap_default_byte (struct soap * soap, char * a) inline
Definition at line 53 of file soapH.h.
Referenced by soap_new_byte().
soap_default_int()
void soap_default_int (struct soap * soap, int * a) inline
Definition at line 124 of file soapH.h.
Referenced by soap_new_int().
soap_default_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * a)
Definition at line 1294 of file soapC.cpp.
References ns1__executeCommand::command, and soap_default_string().
Referenced by soap_in_ns1__executeCommand(), soap_new_req_ns1__executeCommand(), soap_new_set_ns1__executeCommand(), soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_default_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * a)
Definition at line 1396 of file soapC.cpp.
References ns1__executeCommandResponse::result.
Referenced by soap_in_ns1__executeCommandResponse(), soap_new_req_ns1__executeCommandResponse(), soap_new_set_ns1__executeCommandResponse(), soap_read_ns1__executeCommandResponse(), and soap_serve_ns1__executeCommand().
soap_default_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * a)
Definition at line 1083 of file soapC.cpp.
References soap_default__QName(), SOAP_ENV__Code::SOAP_ENV__Subcode, and SOAP_ENV__Code::SOAP_ENV__Value.
Referenced by soap_in_SOAP_ENV__Code(), soap_instantiate_ns1__executeCommand(), soap_instantiate_SOAP_ENV__Code(), soap_new_req_SOAP_ENV__Code(), soap_new_set_SOAP_ENV__Code(), and soap_read_SOAP_ENV__Code().
soap_default_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * a)
Definition at line 965 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, and SOAP_ENV__Detail::fault.
Referenced by soap_faultdetail(), soap_in_SOAP_ENV__Detail(), soap_instantiate_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Detail(), soap_new_set_SOAP_ENV__Detail(), and soap_read_SOAP_ENV__Detail().
soap_default_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * a)
Definition at line 646 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default__QName(), soap_default_string(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, and SOAP_ENV__Fault::SOAP_ENV__Role.
Referenced by soap_fault(), soap_in_SOAP_ENV__Fault(), soap_new_req_SOAP_ENV__Fault(), soap_new_set_SOAP_ENV__Fault(), and soap_read_SOAP_ENV__Fault().
soap_default_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * a)
Definition at line 1203 of file soapC.cpp.
Referenced by soap_header(), soap_in_SOAP_ENV__Header(), soap_new_req_SOAP_ENV__Header(), soap_new_set_SOAP_ENV__Header(), and soap_read_SOAP_ENV__Header().
soap_default_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * a)
Definition at line 857 of file soapC.cpp.
References soap_default_string(), and SOAP_ENV__Reason::SOAP_ENV__Text.
Referenced by soap_in_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Reason(), soap_new_set_SOAP_ENV__Reason(), and soap_read_SOAP_ENV__Reason().
soap_default_string()
void soap_default_string (struct soap * soap, char ** a) inline
Definition at line 994 of file soapH.h.
Referenced by soap_default_ns1__executeCommand(), soap_default_SOAP_ENV__Fault(), soap_default_SOAP_ENV__Reason(), and soap_new_string().
soap_delelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement (const void * ptr, int type)
Definition at line 401 of file soapC.cpp.
soap_dupelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_dupelement (struct soap * soap, const void * ptr, int type)
Definition at line 388 of file soapC.cpp.
soap_faultcode()
SOAP_FMAC3 const char** SOAP_FMAC4 soap_faultcode (struct soap * soap)
Definition at line 101 of file soapC.cpp.
References soap_fault().
soap_fbase()
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase (int t, int b)
Definition at line 509 of file soapC.cpp.
soap_fdelete()
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete (struct soap_clist * p)
Definition at line 442 of file soapC.cpp.
References SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
soap_finsert()
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert (struct soap * soap, int t, int tt, void * p, size_t index, const void * q, void ** x)
Definition at line 524 of file soapC.cpp.
References SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_get__QName()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get__QName (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1763 of file soapC.cpp.
References soap_getindependent(), and soap_in__QName().
Referenced by soap_read__QName().
soap_GET__QName()
int soap_GET__QName (struct soap * soap, const char * URL, char ** p) inline
Definition at line 972 of file soapH.h.
References soap_read__QName().
soap_get_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_get_byte (struct soap * soap, char * p, const char * tag, const char * type)
Definition at line 602 of file soapC.cpp.
References soap_getindependent(), and soap_in_byte().
Referenced by soap_read_byte().
soap_GET_byte()
int soap_GET_byte (struct soap * soap, const char * URL, char * p) inline
Definition at line 106 of file soapH.h.
References soap_read_byte().
soap_get_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_get_int (struct soap * soap, int * p, const char * tag, const char * type)
Definition at line 636 of file soapC.cpp.
References soap_getindependent(), and soap_in_int().
Referenced by soap_read_int().
soap_GET_int()
int soap_GET_int (struct soap * soap, const char * URL, int * p) inline
Definition at line 177 of file soapH.h.
References soap_read_int().
soap_get_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_get_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p, const char * tag, const char * type)
Definition at line 1388 of file soapC.cpp.
References soap_getindependent(), and soap_in_ns1__executeCommand().
Referenced by soap_read_ns1__executeCommand(), and soap_serve_ns1__executeCommand().
soap_GET_ns1__executeCommand()
int soap_GET_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand * p) inline
Definition at line 755 of file soapH.h.
References soap_read_ns1__executeCommand().
soap_get_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_get_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p, const char * tag, const char * type)
Definition at line 1490 of file soapC.cpp.
References soap_getindependent(), and soap_in_ns1__executeCommandResponse().
Referenced by soap_read_ns1__executeCommandResponse().
soap_GET_ns1__executeCommandResponse()
int soap_GET_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse * p) inline
Definition at line 844 of file soapH.h.
References soap_read_ns1__executeCommandResponse().
soap_get_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code ** p, const char * tag, const char * type)
Definition at line 1671 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Code().
soap_get_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail ** p, const char * tag, const char * type)
Definition at line 1608 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Detail().
soap_get_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason ** p, const char * tag, const char * type)
Definition at line 1548 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerToSOAP_ENV__Reason().
soap_get_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_get_PointerTostring (struct soap * soap, char *** p, const char * tag, const char * type)
Definition at line 1729 of file soapC.cpp.
References soap_getindependent(), and soap_in_PointerTostring().
soap_get_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_get_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p, const char * tag, const char * type)
Definition at line 1191 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Code().
Referenced by soap_read_SOAP_ENV__Code().
soap_GET_SOAP_ENV__Code()
int soap_GET_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code * p) inline
Definition at line 573 of file soapH.h.
References soap_read_SOAP_ENV__Code().
soap_get_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_get_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p, const char * tag, const char * type)
Definition at line 1071 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Detail().
Referenced by soap_read_SOAP_ENV__Detail().
soap_GET_SOAP_ENV__Detail()
int soap_GET_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail * p) inline
Definition at line 478 of file soapH.h.
References soap_read_SOAP_ENV__Detail().
soap_get_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_get_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p, const char * tag, const char * type)
Definition at line 845 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Fault().
Referenced by soap_getfault(), and soap_read_SOAP_ENV__Fault().
soap_GET_SOAP_ENV__Fault()
int soap_GET_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault * p) inline
Definition at line 284 of file soapH.h.
References soap_read_SOAP_ENV__Fault().
soap_get_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_get_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p, const char * tag, const char * type)
Definition at line 1284 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Header().
Referenced by soap_read_SOAP_ENV__Header().
soap_GET_SOAP_ENV__Header()
int soap_GET_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header * p) inline
Definition at line 664 of file soapH.h.
References soap_read_SOAP_ENV__Header().
soap_get_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_get_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p, const char * tag, const char * type)
Definition at line 953 of file soapC.cpp.
References soap_getindependent(), and soap_in_SOAP_ENV__Reason().
Referenced by soap_read_SOAP_ENV__Reason().
soap_GET_SOAP_ENV__Reason()
int soap_GET_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason * p) inline
Definition at line 377 of file soapH.h.
References soap_read_SOAP_ENV__Reason().
soap_get_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_get_string (struct soap * soap, char ** p, const char * tag, const char * type)
Definition at line 1805 of file soapC.cpp.
References soap_getindependent(), and soap_in_string().
Referenced by soap_read_string().
soap_GET_string()
int soap_GET_string (struct soap * soap, const char * URL, char ** p) inline
Definition at line 1052 of file soapH.h.
References soap_read_string().
soap_getelement()
SOAP_FMAC3 void* SOAP_FMAC4 soap_getelement (struct soap * soap, int * type)
Definition at line 198 of file soapC.cpp.
References soap_in__QName(), soap_in_byte(), soap_in_int(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_PointerTostring(), soap_in_string(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_getindependent(), soap_ignore_element(), and soap_in_SOAP_ENV__Detail().
soap_getindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent (struct soap * soap)
Definition at line 177 of file soapC.cpp.
References soap_getelement(), and soap_ignore_element().
Referenced by soap_get__QName(), soap_get_byte(), soap_get_int(), soap_get_ns1__executeCommand(), soap_get_ns1__executeCommandResponse(), soap_get_PointerToSOAP_ENV__Code(), soap_get_PointerToSOAP_ENV__Detail(), soap_get_PointerToSOAP_ENV__Reason(), soap_get_PointerTostring(), soap_get_SOAP_ENV__Code(), soap_get_SOAP_ENV__Detail(), soap_get_SOAP_ENV__Fault(), soap_get_SOAP_ENV__Header(), soap_get_SOAP_ENV__Reason(), and soap_get_string().
soap_ignore_element()
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element (struct soap * soap)
Definition at line 281 of file soapC.cpp.
References soap_getelement().
Referenced by soap_getindependent(), soap_in_ns1__executeCommand(), soap_in_ns1__executeCommandResponse(), soap_in_SOAP_ENV__Code(), soap_in_SOAP_ENV__Detail(), soap_in_SOAP_ENV__Fault(), soap_in_SOAP_ENV__Header(), and soap_in_SOAP_ENV__Reason().
soap_in__QName()
SOAP_FMAC3 char** SOAP_FMAC4 soap_in__QName (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1750 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_get__QName(), soap_getelement(), soap_in_SOAP_ENV__Code(), and soap_in_SOAP_ENV__Fault().
soap_in_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_in_byte (struct soap * soap, const char * tag, char * a, const char * type)
Definition at line 581 of file soapC.cpp.
References SOAP_TYPE_byte.
Referenced by soap_get_byte(), and soap_getelement().
soap_in_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_in_int (struct soap * soap, const char * tag, int * a, const char * type)
Definition at line 615 of file soapC.cpp.
References SOAP_TYPE_int.
Referenced by soap_get_int(), and soap_getelement().
soap_in_ns1__executeCommand()
SOAP_FMAC3 struct ns1__executeCommand* SOAP_FMAC4 soap_in_ns1__executeCommand (struct soap * soap, const char * tag, struct ns1__executeCommand * a, const char * type)
Definition at line 1318 of file soapC.cpp.
References ns1__executeCommand::command, soap_default_ns1__executeCommand(), soap_finsert(), soap_ignore_element(), soap_in_string(), and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_get_ns1__executeCommand(), and soap_getelement().
soap_in_ns1__executeCommandResponse()
SOAP_FMAC3 struct ns1__executeCommandResponse* SOAP_FMAC4 soap_in_ns1__executeCommandResponse (struct soap * soap, const char * tag, struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1420 of file soapC.cpp.
References ns1__executeCommandResponse::result, soap_default_ns1__executeCommandResponse(), soap_finsert(), soap_ignore_element(), soap_in_PointerTostring(), and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_get_ns1__executeCommandResponse(), and soap_getelement().
soap_in_PointerToSOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code ** a, const char * type)
Definition at line 1640 of file soapC.cpp.
References soap_in_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_PointerToSOAP_ENV__Code(), soap_in_SOAP_ENV__Code(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail ** a, const char * type)
Definition at line 1577 of file soapC.cpp.
References soap_in_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_PointerToSOAP_ENV__Detail(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason ** a, const char * type)
Definition at line 1517 of file soapC.cpp.
References soap_in_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_PointerToSOAP_ENV__Reason(), and soap_in_SOAP_ENV__Fault().
soap_in_PointerTostring()
SOAP_FMAC3 char*** SOAP_FMAC4 soap_in_PointerTostring (struct soap * soap, const char * tag, char *** a, const char * type)
Definition at line 1698 of file soapC.cpp.
References soap_in_string(), and SOAP_TYPE_string.
Referenced by soap_get_PointerTostring(), soap_getelement(), and soap_in_ns1__executeCommandResponse().
soap_in_SOAP_ENV__Code()
SOAP_FMAC3 struct SOAP_ENV__Code* SOAP_FMAC4 soap_in_SOAP_ENV__Code (struct soap * soap, const char * tag, struct SOAP_ENV__Code * a, const char * type)
Definition at line 1112 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_finsert(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_get_SOAP_ENV__Code(), and soap_in_PointerToSOAP_ENV__Code().
soap_in_SOAP_ENV__Detail()
SOAP_FMAC3 struct SOAP_ENV__Detail* SOAP_FMAC4 soap_in_SOAP_ENV__Detail (struct soap * soap, const char * tag, struct SOAP_ENV__Detail * a, const char * type)
Definition at line 992 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), soap_finsert(), soap_getelement(), soap_ignore_element(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_get_SOAP_ENV__Detail(), and soap_in_PointerToSOAP_ENV__Detail().
soap_in_SOAP_ENV__Fault()
SOAP_FMAC3 struct SOAP_ENV__Fault* SOAP_FMAC4 soap_in_SOAP_ENV__Fault (struct soap * soap, const char * tag, struct SOAP_ENV__Fault * a, const char * type)
Definition at line 703 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default_SOAP_ENV__Fault(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_finsert(), soap_ignore_element(), soap_in__QName(), soap_in_PointerToSOAP_ENV__Code(), soap_in_PointerToSOAP_ENV__Detail(), soap_in_PointerToSOAP_ENV__Reason(), soap_in_string(), and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_get_SOAP_ENV__Fault().
soap_in_SOAP_ENV__Header()
SOAP_FMAC3 struct SOAP_ENV__Header* SOAP_FMAC4 soap_in_SOAP_ENV__Header (struct soap * soap, const char * tag, struct SOAP_ENV__Header * a, const char * type)
Definition at line 1223 of file soapC.cpp.
References soap_default_SOAP_ENV__Header(), soap_finsert(), soap_ignore_element(), and SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_get_SOAP_ENV__Header(), and soap_getheader().
soap_in_SOAP_ENV__Reason()
SOAP_FMAC3 struct SOAP_ENV__Reason* SOAP_FMAC4 soap_in_SOAP_ENV__Reason (struct soap * soap, const char * tag, struct SOAP_ENV__Reason * a, const char * type)
Definition at line 883 of file soapC.cpp.
References soap_default_SOAP_ENV__Reason(), SOAP_ENV__Reason::SOAP_ENV__Text, soap_finsert(), soap_ignore_element(), soap_in_string(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_get_SOAP_ENV__Reason(), and soap_in_PointerToSOAP_ENV__Reason().
soap_in_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_in_string (struct soap * soap, const char * tag, char ** a, const char * type)
Definition at line 1784 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_get_string(), soap_getelement(), soap_in_ns1__executeCommand(), soap_in_PointerTostring(), soap_in_SOAP_ENV__Fault(), and soap_in_SOAP_ENV__Reason().
soap_instantiate()
SOAP_FMAC3 void* SOAP_FMAC4 soap_instantiate (struct soap * soap, int t, const char * type, const char * arrayType, size_t * n)
Definition at line 409 of file soapC.cpp.
References soap_instantiate_ns1__executeCommand(), soap_instantiate_ns1__executeCommandResponse(), soap_instantiate_SOAP_ENV__Code(), soap_instantiate_SOAP_ENV__Detail(), soap_instantiate_SOAP_ENV__Fault(), soap_instantiate_SOAP_ENV__Header(), soap_instantiate_SOAP_ENV__Reason(), SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_SOAP_ENV__Code, SOAP_TYPE_SOAP_ENV__Detail, SOAP_TYPE_SOAP_ENV__Fault, SOAP_TYPE_SOAP_ENV__Header, and SOAP_TYPE_SOAP_ENV__Reason.
soap_instantiate_ns1__executeCommand()
SOAP_FMAC1 struct ns1__executeCommand* SOAP_FMAC2 soap_instantiate_ns1__executeCommand (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 71 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
Referenced by soap_instantiate(), and soap_new_ns1__executeCommand().
soap_instantiate_ns1__executeCommandResponse()
SOAP_FMAC1 struct ns1__executeCommandResponse* SOAP_FMAC2 soap_instantiate_ns1__executeCommandResponse (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 52 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_ns1__executeCommandResponse().
soap_instantiate_SOAP_ENV__Code()
SOAP_FMAC1 struct SOAP_ENV__Code* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 112 of file soapC.cpp.
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Code().
soap_instantiate_SOAP_ENV__Detail()
SOAP_FMAC1 struct SOAP_ENV__Detail* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 136 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Detail().
soap_instantiate_SOAP_ENV__Fault()
SOAP_FMAC1 struct SOAP_ENV__Fault* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 194 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Fault().
soap_instantiate_SOAP_ENV__Header()
SOAP_FMAC1 struct SOAP_ENV__Header* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 88 of file soapC.cpp.
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Header().
soap_instantiate_SOAP_ENV__Reason()
SOAP_FMAC1 struct SOAP_ENV__Reason* SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason (struct soap * soap, int n, const char * type, const char * arrayType, size_t * size)
Definition at line 157 of file soapC.cpp.
References soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
Referenced by soap_instantiate(), and soap_new_SOAP_ENV__Reason().
soap_markelement()
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement (struct soap * soap, const void * ptr, int type)
Definition at line 357 of file soapC.cpp.
References soap_serialize_ns1__executeCommand(), soap_serialize_ns1__executeCommandResponse(), soap_serialize_PointerTostring(), soap_serialize_string(), SOAP_TYPE__QName, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_serialize_SOAP_ENV__Detail().
soap_new_byte()
SOAP_FMAC3 char* SOAP_FMAC4 soap_new_byte (struct soap * soap, int n = -1)
Definition at line 587 of file soapC.cpp.
References soap_default_byte().
soap_new_int()
SOAP_FMAC3 int* SOAP_FMAC4 soap_new_int (struct soap * soap, int n = -1)
Definition at line 621 of file soapC.cpp.
References soap_default_int().
soap_new_ns1__executeCommand()
struct ns1__executeCommand* soap_new_ns1__executeCommand (struct soap * soap, int n = -1) inline
Definition at line 689 of file soapH.h.
References soap_instantiate_ns1__executeCommand().
Referenced by soap_new_req_ns1__executeCommand(), and soap_new_set_ns1__executeCommand().
soap_new_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_ns1__executeCommandResponse (struct soap * soap, int n = -1) inline
Definition at line 778 of file soapH.h.
References soap_instantiate_ns1__executeCommandResponse().
Referenced by soap_new_req_ns1__executeCommandResponse(), and soap_new_set_ns1__executeCommandResponse().
soap_new_req_ns1__executeCommand()
struct ns1__executeCommand* soap_new_req_ns1__executeCommand (struct soap * soap) inline
Definition at line 694 of file soapH.h.
References soap_default_ns1__executeCommand(), and soap_new_ns1__executeCommand().
soap_new_req_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_req_ns1__executeCommandResponse (struct soap * soap) inline
Definition at line 783 of file soapH.h.
References soap_default_ns1__executeCommandResponse(), and soap_new_ns1__executeCommandResponse().
soap_new_req_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_req_SOAP_ENV__Code (struct soap * soap) inline
Definition at line 510 of file soapH.h.
References soap_default_SOAP_ENV__Code(), and soap_new_SOAP_ENV__Code().
soap_new_req_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_req_SOAP_ENV__Detail (struct soap * soap, int __type, void * fault) inline
Definition at line 409 of file soapH.h.
References SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
soap_new_req_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_req_SOAP_ENV__Fault (struct soap * soap) inline
Definition at line 207 of file soapH.h.
References soap_default_SOAP_ENV__Fault(), and soap_new_SOAP_ENV__Fault().
soap_new_req_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_req_SOAP_ENV__Header (struct soap * soap) inline
Definition at line 605 of file soapH.h.
References soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
soap_new_req_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_req_SOAP_ENV__Reason (struct soap * soap) inline
Definition at line 316 of file soapH.h.
References soap_default_SOAP_ENV__Reason(), and soap_new_SOAP_ENV__Reason().
soap_new_set_ns1__executeCommand()
struct ns1__executeCommand* soap_new_set_ns1__executeCommand (struct soap * soap, char * command) inline
Definition at line 705 of file soapH.h.
References ns1__executeCommand::command, soap_default_ns1__executeCommand(), and soap_new_ns1__executeCommand().
soap_new_set_ns1__executeCommandResponse()
struct ns1__executeCommandResponse* soap_new_set_ns1__executeCommandResponse (struct soap * soap, char ** result) inline
Definition at line 794 of file soapH.h.
References ns1__executeCommandResponse::result, soap_default_ns1__executeCommandResponse(), and soap_new_ns1__executeCommandResponse().
soap_new_set_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_set_SOAP_ENV__Code (struct soap * soap, char * SOAP_ENV__Value, struct SOAP_ENV__Code * SOAP_ENV__Subcode) inline
Definition at line 521 of file soapH.h.
References soap_default_SOAP_ENV__Code(), SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, and soap_new_SOAP_ENV__Code().
soap_new_set_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_set_SOAP_ENV__Detail (struct soap * soap, char * __any, int __type, void * fault) inline
Definition at line 424 of file soapH.h.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_default_SOAP_ENV__Detail(), and soap_new_SOAP_ENV__Detail().
soap_new_set_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_set_SOAP_ENV__Fault (struct soap * soap, char * faultcode, char * faultstring, char * faultactor, struct SOAP_ENV__Detail * detail, struct SOAP_ENV__Code * SOAP_ENV__Code, struct SOAP_ENV__Reason * SOAP_ENV__Reason, char * SOAP_ENV__Node, char * SOAP_ENV__Role, struct SOAP_ENV__Detail * SOAP_ENV__Detail) inline
Definition at line 218 of file soapH.h.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, soap_default_SOAP_ENV__Fault(), SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, and soap_new_SOAP_ENV__Fault().
soap_new_set_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_set_SOAP_ENV__Header (struct soap * soap) inline
Definition at line 616 of file soapH.h.
References soap_default_SOAP_ENV__Header(), and soap_new_SOAP_ENV__Header().
soap_new_set_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_set_SOAP_ENV__Reason (struct soap * soap, char * SOAP_ENV__Text) inline
Definition at line 327 of file soapH.h.
References soap_default_SOAP_ENV__Reason(), SOAP_ENV__Reason::SOAP_ENV__Text, and soap_new_SOAP_ENV__Reason().
soap_new_SOAP_ENV__Code()
struct SOAP_ENV__Code* soap_new_SOAP_ENV__Code (struct soap * soap, int n = -1) inline
Definition at line 505 of file soapH.h.
References soap_instantiate_SOAP_ENV__Code().
Referenced by soap_instantiate_ns1__executeCommand(), soap_instantiate_SOAP_ENV__Code(), soap_new_req_SOAP_ENV__Code(), and soap_new_set_SOAP_ENV__Code().
soap_new_SOAP_ENV__Detail()
struct SOAP_ENV__Detail* soap_new_SOAP_ENV__Detail (struct soap * soap, int n = -1) inline
Definition at line 404 of file soapH.h.
References soap_instantiate_SOAP_ENV__Detail().
Referenced by soap_faultdetail(), soap_instantiate_SOAP_ENV__Reason(), soap_new_req_SOAP_ENV__Detail(), and soap_new_set_SOAP_ENV__Detail().
soap_new_SOAP_ENV__Fault()
struct SOAP_ENV__Fault* soap_new_SOAP_ENV__Fault (struct soap * soap, int n = -1) inline
Definition at line 202 of file soapH.h.
References soap_instantiate_SOAP_ENV__Fault().
Referenced by soap_fault(), soap_new_req_SOAP_ENV__Fault(), and soap_new_set_SOAP_ENV__Fault().
soap_new_SOAP_ENV__Header()
struct SOAP_ENV__Header* soap_new_SOAP_ENV__Header (struct soap * soap, int n = -1) inline
Definition at line 600 of file soapH.h.
References soap_instantiate_SOAP_ENV__Header().
Referenced by soap_header(), soap_new_req_SOAP_ENV__Header(), and soap_new_set_SOAP_ENV__Header().
soap_new_SOAP_ENV__Reason()
struct SOAP_ENV__Reason* soap_new_SOAP_ENV__Reason (struct soap * soap, int n = -1) inline
Definition at line 311 of file soapH.h.
References soap_instantiate_SOAP_ENV__Reason().
Referenced by soap_new_req_SOAP_ENV__Reason(), and soap_new_set_SOAP_ENV__Reason().
soap_new_string()
SOAP_FMAC3 char** SOAP_FMAC4 soap_new_string (struct soap * soap, int n = -1)
Definition at line 1790 of file soapC.cpp.
References soap_default_string().
soap_out__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1745 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put__QName().
soap_out_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte (struct soap * soap, const char * tag, int id, const char * a, const char * type)
Definition at line 576 of file soapC.cpp.
References SOAP_TYPE_byte.
Referenced by soap_put_byte(), and soap_putelement().
soap_out_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int (struct soap * soap, const char * tag, int id, const int * a, const char * type)
Definition at line 610 of file soapC.cpp.
References SOAP_TYPE_int.
Referenced by soap_put_int(), and soap_putelement().
soap_out_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommand (struct soap * soap, const char * tag, int id, const struct ns1__executeCommand * a, const char * type)
Definition at line 1308 of file soapC.cpp.
References ns1__executeCommand::command, soap_out_string(), and SOAP_TYPE_ns1__executeCommand.
Referenced by soap_put_ns1__executeCommand(), and soap_putelement().
soap_out_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__executeCommandResponse (struct soap * soap, const char * tag, int id, const struct ns1__executeCommandResponse * a, const char * type)
Definition at line 1410 of file soapC.cpp.
References ns1__executeCommandResponse::result, soap_out_PointerTostring(), and SOAP_TYPE_ns1__executeCommandResponse.
Referenced by soap_put_ns1__executeCommandResponse(), and soap_putelement().
soap_out_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Code *const * a, const char * type)
Definition at line 1629 of file soapC.cpp.
References soap_out_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_out_SOAP_ENV__Code(), soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Code().
soap_out_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Detail *const * a, const char * type)
Definition at line 1569 of file soapC.cpp.
References soap_out_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Detail().
soap_out_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason (struct soap * soap, const char * tag, int id, struct SOAP_ENV__Reason *const * a, const char * type)
Definition at line 1509 of file soapC.cpp.
References soap_out_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_SOAP_ENV__Fault(), and soap_put_PointerToSOAP_ENV__Reason().
soap_out_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring (struct soap * soap, const char * tag, int id, char **const * a, const char * type)
Definition at line 1690 of file soapC.cpp.
References soap_out_string(), and SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommandResponse(), soap_put_PointerTostring(), and soap_putelement().
soap_out_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Code * a, const char * type)
Definition at line 1099 of file soapC.cpp.
References SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_out_PointerToSOAP_ENV__Code(), and soap_put_SOAP_ENV__Code().
soap_out_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Detail * a, const char * type)
Definition at line 981 of file soapC.cpp.
References SOAP_ENV__Detail::__any, SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, soap_putelement(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_out_PointerToSOAP_ENV__Detail(), and soap_put_SOAP_ENV__Detail().
soap_out_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Fault * a, const char * type)
Definition at line 676 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_out__QName(), soap_out_PointerToSOAP_ENV__Code(), soap_out_PointerToSOAP_ENV__Detail(), soap_out_PointerToSOAP_ENV__Reason(), soap_out_string(), and SOAP_TYPE_SOAP_ENV__Fault.
Referenced by soap_put_SOAP_ENV__Fault().
soap_out_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Header * a, const char * type)
Definition at line 1215 of file soapC.cpp.
References SOAP_TYPE_SOAP_ENV__Header.
Referenced by soap_put_SOAP_ENV__Header(), and soap_putheader().
soap_out_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason (struct soap * soap, const char * tag, int id, const struct SOAP_ENV__Reason * a, const char * type)
Definition at line 871 of file soapC.cpp.
References SOAP_ENV__Reason::SOAP_ENV__Text, soap_out_string(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_out_PointerToSOAP_ENV__Reason(), and soap_put_SOAP_ENV__Reason().
soap_out_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string (struct soap * soap, const char * tag, int id, char *const * a, const char * type)
Definition at line 1779 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_out_ns1__executeCommand(), soap_out_PointerTostring(), soap_out_SOAP_ENV__Fault(), soap_out_SOAP_ENV__Reason(), soap_put_string(), and soap_putelement().
soap_POST_recv__QName()
int soap_POST_recv__QName (struct soap * soap, char ** p) inline
Definition at line 979 of file soapH.h.
References soap_read__QName().
soap_POST_recv_byte()
int soap_POST_recv_byte (struct soap * soap, char * p) inline
Definition at line 113 of file soapH.h.
References soap_read_byte().
soap_POST_recv_int()
int soap_POST_recv_int (struct soap * soap, int * p) inline
Definition at line 184 of file soapH.h.
References soap_read_int().
soap_POST_recv_ns1__executeCommand()
int soap_POST_recv_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p) inline
Definition at line 762 of file soapH.h.
References soap_read_ns1__executeCommand().
soap_POST_recv_ns1__executeCommandResponse()
int soap_POST_recv_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p) inline
Definition at line 851 of file soapH.h.
References soap_read_ns1__executeCommandResponse().
soap_POST_recv_SOAP_ENV__Code()
int soap_POST_recv_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p) inline
Definition at line 580 of file soapH.h.
References soap_read_SOAP_ENV__Code().
soap_POST_recv_SOAP_ENV__Detail()
int soap_POST_recv_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p) inline
Definition at line 485 of file soapH.h.
References soap_read_SOAP_ENV__Detail().
soap_POST_recv_SOAP_ENV__Fault()
int soap_POST_recv_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p) inline
Definition at line 291 of file soapH.h.
References soap_read_SOAP_ENV__Fault().
soap_POST_recv_SOAP_ENV__Header()
int soap_POST_recv_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p) inline
Definition at line 671 of file soapH.h.
References soap_read_SOAP_ENV__Header().
soap_POST_recv_SOAP_ENV__Reason()
int soap_POST_recv_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p) inline
Definition at line 384 of file soapH.h.
References soap_read_SOAP_ENV__Reason().
soap_POST_recv_string()
int soap_POST_recv_string (struct soap * soap, char ** p) inline
Definition at line 1059 of file soapH.h.
References soap_read_string().
soap_POST_send__QName()
int soap_POST_send__QName (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 953 of file soapH.h.
References soap_put__QName().
soap_POST_send_byte()
int soap_POST_send_byte (struct soap * soap, const char * URL, char const * p) inline
Definition at line 87 of file soapH.h.
References soap_put_byte().
soap_POST_send_int()
int soap_POST_send_int (struct soap * soap, const char * URL, int const * p) inline
Definition at line 158 of file soapH.h.
References soap_put_int().
soap_POST_send_ns1__executeCommand()
int soap_POST_send_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand const * p) inline
Definition at line 735 of file soapH.h.
References soap_put_ns1__executeCommand(), and soap_serialize_ns1__executeCommand().
soap_POST_send_ns1__executeCommandResponse()
int soap_POST_send_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse const * p) inline
Definition at line 824 of file soapH.h.
References soap_put_ns1__executeCommandResponse(), and soap_serialize_ns1__executeCommandResponse().
soap_POST_send_SOAP_ENV__Code()
int soap_POST_send_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code const * p) inline
Definition at line 553 of file soapH.h.
References soap_put_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Code().
soap_POST_send_SOAP_ENV__Detail()
int soap_POST_send_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail const * p) inline
Definition at line 458 of file soapH.h.
References soap_put_SOAP_ENV__Detail(), and soap_serialize_SOAP_ENV__Detail().
soap_POST_send_SOAP_ENV__Fault()
int soap_POST_send_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault const * p) inline
Definition at line 264 of file soapH.h.
References soap_put_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Fault().
soap_POST_send_SOAP_ENV__Header()
int soap_POST_send_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header const * p) inline
Definition at line 644 of file soapH.h.
References soap_put_SOAP_ENV__Header(), and soap_serialize_SOAP_ENV__Header().
soap_POST_send_SOAP_ENV__Reason()
int soap_POST_send_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason const * p) inline
Definition at line 357 of file soapH.h.
References soap_put_SOAP_ENV__Reason(), and soap_serialize_SOAP_ENV__Reason().
soap_POST_send_string()
int soap_POST_send_string (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1033 of file soapH.h.
References soap_put_string().
soap_put__QName()
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1756 of file soapC.cpp.
References soap_out__QName(), and soap_putindependent().
Referenced by soap_POST_send__QName(), soap_PUT__QName(), and soap_write__QName().
soap_PUT__QName()
int soap_PUT__QName (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 945 of file soapH.h.
References soap_put__QName().
soap_put_byte()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte (struct soap * soap, const char * a, const char * tag, const char * type)
Definition at line 595 of file soapC.cpp.
References soap_out_byte(), and soap_putindependent().
Referenced by soap_POST_send_byte(), soap_PUT_byte(), and soap_write_byte().
soap_PUT_byte()
int soap_PUT_byte (struct soap * soap, const char * URL, char const * p) inline
Definition at line 79 of file soapH.h.
References soap_put_byte().
soap_put_int()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int (struct soap * soap, const int * a, const char * tag, const char * type)
Definition at line 629 of file soapC.cpp.
References soap_out_int(), and soap_putindependent().
Referenced by soap_POST_send_int(), soap_PUT_int(), and soap_write_int().
soap_PUT_int()
int soap_PUT_int (struct soap * soap, const char * URL, int const * p) inline
Definition at line 150 of file soapH.h.
References soap_put_int().
soap_put_ns1__executeCommand()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a, const char * tag, const char * type)
Definition at line 1381 of file soapC.cpp.
References soap_out_ns1__executeCommand(), and soap_putindependent().
Referenced by soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_PUT_ns1__executeCommand()
int soap_PUT_ns1__executeCommand (struct soap * soap, const char * URL, struct ns1__executeCommand const * p) inline
Definition at line 727 of file soapH.h.
References soap_put_ns1__executeCommand(), and soap_serialize_ns1__executeCommand().
soap_put_ns1__executeCommandResponse()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a, const char * tag, const char * type)
Definition at line 1483 of file soapC.cpp.
References soap_out_ns1__executeCommandResponse(), and soap_putindependent().
Referenced by soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_PUT_ns1__executeCommandResponse()
int soap_PUT_ns1__executeCommandResponse (struct soap * soap, const char * URL, struct ns1__executeCommandResponse const * p) inline
Definition at line 816 of file soapH.h.
References soap_put_ns1__executeCommandResponse(), and soap_serialize_ns1__executeCommandResponse().
soap_put_PointerToSOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a, const char * tag, const char * type)
Definition at line 1664 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Code(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a, const char * tag, const char * type)
Definition at line 1601 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Detail(), and soap_putindependent().
soap_put_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a, const char * tag, const char * type)
Definition at line 1541 of file soapC.cpp.
References soap_out_PointerToSOAP_ENV__Reason(), and soap_putindependent().
soap_put_PointerTostring()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring (struct soap * soap, char **const * a, const char * tag, const char * type)
Definition at line 1722 of file soapC.cpp.
References soap_out_PointerTostring(), and soap_putindependent().
soap_put_SOAP_ENV__Code()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a, const char * tag, const char * type)
Definition at line 1184 of file soapC.cpp.
References soap_out_SOAP_ENV__Code(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_PUT_SOAP_ENV__Code()
int soap_PUT_SOAP_ENV__Code (struct soap * soap, const char * URL, struct SOAP_ENV__Code const * p) inline
Definition at line 545 of file soapH.h.
References soap_put_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Code().
soap_put_SOAP_ENV__Detail()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a, const char * tag, const char * type)
Definition at line 1064 of file soapC.cpp.
References soap_out_SOAP_ENV__Detail(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_PUT_SOAP_ENV__Detail()
int soap_PUT_SOAP_ENV__Detail (struct soap * soap, const char * URL, struct SOAP_ENV__Detail const * p) inline
Definition at line 450 of file soapH.h.
References soap_put_SOAP_ENV__Detail(), and soap_serialize_SOAP_ENV__Detail().
soap_put_SOAP_ENV__Fault()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a, const char * tag, const char * type)
Definition at line 838 of file soapC.cpp.
References soap_out_SOAP_ENV__Fault(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_putfault(), and soap_write_SOAP_ENV__Fault().
soap_PUT_SOAP_ENV__Fault()
int soap_PUT_SOAP_ENV__Fault (struct soap * soap, const char * URL, struct SOAP_ENV__Fault const * p) inline
Definition at line 256 of file soapH.h.
References soap_put_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Fault().
soap_put_SOAP_ENV__Header()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a, const char * tag, const char * type)
Definition at line 1277 of file soapC.cpp.
References soap_out_SOAP_ENV__Header(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), and soap_write_SOAP_ENV__Header().
soap_PUT_SOAP_ENV__Header()
int soap_PUT_SOAP_ENV__Header (struct soap * soap, const char * URL, struct SOAP_ENV__Header const * p) inline
Definition at line 636 of file soapH.h.
References soap_put_SOAP_ENV__Header(), and soap_serialize_SOAP_ENV__Header().
soap_put_SOAP_ENV__Reason()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a, const char * tag, const char * type)
Definition at line 946 of file soapC.cpp.
References soap_out_SOAP_ENV__Reason(), and soap_putindependent().
Referenced by soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_PUT_SOAP_ENV__Reason()
int soap_PUT_SOAP_ENV__Reason (struct soap * soap, const char * URL, struct SOAP_ENV__Reason const * p) inline
Definition at line 349 of file soapH.h.
References soap_put_SOAP_ENV__Reason(), and soap_serialize_SOAP_ENV__Reason().
soap_put_string()
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string (struct soap * soap, char *const * a, const char * tag, const char * type)
Definition at line 1798 of file soapC.cpp.
References soap_out_string(), and soap_putindependent().
Referenced by soap_POST_send_string(), soap_PUT_string(), and soap_write_string().
soap_PUT_string()
int soap_PUT_string (struct soap * soap, const char * URL, char *const * p) inline
Definition at line 1025 of file soapH.h.
References soap_put_string().
soap_putelement()
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement (struct soap * soap, const void * ptr, const char * tag, int id, int type)
Definition at line 325 of file soapC.cpp.
References soap_out_byte(), soap_out_int(), soap_out_ns1__executeCommand(), soap_out_ns1__executeCommandResponse(), soap_out_PointerTostring(), soap_out_string(), SOAP_TYPE__QName, SOAP_TYPE_byte, SOAP_TYPE_int, SOAP_TYPE_ns1__executeCommand, SOAP_TYPE_ns1__executeCommandResponse, SOAP_TYPE_PointerTostring, and SOAP_TYPE_string.
Referenced by soap_out_SOAP_ENV__Detail(), and soap_putindependent().
soap_putindependent()
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent (struct soap * soap)
Definition at line 310 of file soapC.cpp.
References soap_putelement().
Referenced by soap_put__QName(), soap_put_byte(), soap_put_int(), soap_put_ns1__executeCommand(), soap_put_ns1__executeCommandResponse(), soap_put_PointerToSOAP_ENV__Code(), soap_put_PointerToSOAP_ENV__Detail(), soap_put_PointerToSOAP_ENV__Reason(), soap_put_PointerTostring(), soap_put_SOAP_ENV__Code(), soap_put_SOAP_ENV__Detail(), soap_put_SOAP_ENV__Fault(), soap_put_SOAP_ENV__Header(), soap_put_SOAP_ENV__Reason(), and soap_put_string().
soap_read__QName()
int soap_read__QName (struct soap * soap, char ** p) inline
Definition at line 962 of file soapH.h.
References soap_get__QName().
Referenced by soap_GET__QName(), and soap_POST_recv__QName().
soap_read_byte()
int soap_read_byte (struct soap * soap, char * p) inline
Definition at line 96 of file soapH.h.
References soap_get_byte().
Referenced by soap_GET_byte(), and soap_POST_recv_byte().
soap_read_int()
int soap_read_int (struct soap * soap, int * p) inline
Definition at line 167 of file soapH.h.
References soap_get_int().
Referenced by soap_GET_int(), and soap_POST_recv_int().
soap_read_ns1__executeCommand()
int soap_read_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand * p) inline
Definition at line 744 of file soapH.h.
References soap_default_ns1__executeCommand(), and soap_get_ns1__executeCommand().
Referenced by soap_GET_ns1__executeCommand(), and soap_POST_recv_ns1__executeCommand().
soap_read_ns1__executeCommandResponse()
int soap_read_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse * p) inline
Definition at line 833 of file soapH.h.
References soap_default_ns1__executeCommandResponse(), and soap_get_ns1__executeCommandResponse().
Referenced by soap_GET_ns1__executeCommandResponse(), and soap_POST_recv_ns1__executeCommandResponse().
soap_read_SOAP_ENV__Code()
int soap_read_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code * p) inline
Definition at line 562 of file soapH.h.
References soap_default_SOAP_ENV__Code(), and soap_get_SOAP_ENV__Code().
Referenced by soap_GET_SOAP_ENV__Code(), and soap_POST_recv_SOAP_ENV__Code().
soap_read_SOAP_ENV__Detail()
int soap_read_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail * p) inline
Definition at line 467 of file soapH.h.
References soap_default_SOAP_ENV__Detail(), and soap_get_SOAP_ENV__Detail().
Referenced by soap_GET_SOAP_ENV__Detail(), and soap_POST_recv_SOAP_ENV__Detail().
soap_read_SOAP_ENV__Fault()
int soap_read_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault * p) inline
Definition at line 273 of file soapH.h.
References soap_default_SOAP_ENV__Fault(), and soap_get_SOAP_ENV__Fault().
Referenced by soap_GET_SOAP_ENV__Fault(), and soap_POST_recv_SOAP_ENV__Fault().
soap_read_SOAP_ENV__Header()
int soap_read_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header * p) inline
Definition at line 653 of file soapH.h.
References soap_default_SOAP_ENV__Header(), and soap_get_SOAP_ENV__Header().
Referenced by soap_GET_SOAP_ENV__Header(), and soap_POST_recv_SOAP_ENV__Header().
soap_read_SOAP_ENV__Reason()
int soap_read_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason * p) inline
Definition at line 366 of file soapH.h.
References soap_default_SOAP_ENV__Reason(), and soap_get_SOAP_ENV__Reason().
Referenced by soap_GET_SOAP_ENV__Reason(), and soap_POST_recv_SOAP_ENV__Reason().
soap_read_string()
int soap_read_string (struct soap * soap, char ** p) inline
Definition at line 1042 of file soapH.h.
References soap_get_string().
Referenced by soap_GET_string(), and soap_POST_recv_string().
soap_serialize__QName()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName (struct soap * soap, char *const * a)
Definition at line 1737 of file soapC.cpp.
References SOAP_TYPE__QName.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_ns1__executeCommand()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommand (struct soap * soap, const struct ns1__executeCommand * a)
Definition at line 1300 of file soapC.cpp.
References ns1__executeCommand::command, and soap_serialize_string().
Referenced by soap_markelement(), soap_POST_send_ns1__executeCommand(), soap_PUT_ns1__executeCommand(), and soap_write_ns1__executeCommand().
soap_serialize_ns1__executeCommandResponse()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__executeCommandResponse (struct soap * soap, const struct ns1__executeCommandResponse * a)
Definition at line 1402 of file soapC.cpp.
References ns1__executeCommandResponse::result, and soap_serialize_PointerTostring().
Referenced by soap_markelement(), soap_POST_send_ns1__executeCommandResponse(), soap_PUT_ns1__executeCommandResponse(), soap_serve_ns1__executeCommand(), and soap_write_ns1__executeCommandResponse().
soap_serialize_PointerToSOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code *const * a)
Definition at line 1620 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Code(), and SOAP_TYPE_SOAP_ENV__Code.
Referenced by soap_serialize_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail *const * a)
Definition at line 1560 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Detail(), and SOAP_TYPE_SOAP_ENV__Detail.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerToSOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason *const * a)
Definition at line 1500 of file soapC.cpp.
References soap_serialize_SOAP_ENV__Reason(), and SOAP_TYPE_SOAP_ENV__Reason.
Referenced by soap_serialize_SOAP_ENV__Fault().
soap_serialize_PointerTostring()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring (struct soap * soap, char **const * a)
Definition at line 1681 of file soapC.cpp.
References soap_serialize_string(), and SOAP_TYPE_string.
Referenced by soap_markelement(), and soap_serialize_ns1__executeCommandResponse().
soap_serialize_SOAP_ENV__Code()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code (struct soap * soap, const struct SOAP_ENV__Code * a)
Definition at line 1090 of file soapC.cpp.
References SOAP_ENV__Code::SOAP_ENV__Subcode, SOAP_ENV__Code::SOAP_ENV__Value, soap_serialize__QName(), and soap_serialize_PointerToSOAP_ENV__Code().
Referenced by soap_POST_send_SOAP_ENV__Code(), soap_PUT_SOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Code(), and soap_write_SOAP_ENV__Code().
soap_serialize_SOAP_ENV__Detail()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail (struct soap * soap, const struct SOAP_ENV__Detail * a)
Definition at line 973 of file soapC.cpp.
References SOAP_ENV__Detail::__type, SOAP_ENV__Detail::fault, and soap_markelement().
Referenced by soap_POST_send_SOAP_ENV__Detail(), soap_PUT_SOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Detail(), and soap_write_SOAP_ENV__Detail().
soap_serialize_SOAP_ENV__Fault()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault (struct soap * soap, const struct SOAP_ENV__Fault * a)
Definition at line 660 of file soapC.cpp.
References SOAP_ENV__Fault::detail, SOAP_ENV__Fault::faultactor, SOAP_ENV__Fault::faultcode, SOAP_ENV__Fault::faultstring, SOAP_ENV__Fault::SOAP_ENV__Code, SOAP_ENV__Fault::SOAP_ENV__Detail, SOAP_ENV__Fault::SOAP_ENV__Node, SOAP_ENV__Fault::SOAP_ENV__Reason, SOAP_ENV__Fault::SOAP_ENV__Role, soap_serialize__QName(), soap_serialize_PointerToSOAP_ENV__Code(), soap_serialize_PointerToSOAP_ENV__Detail(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_serialize_string().
Referenced by soap_POST_send_SOAP_ENV__Fault(), soap_PUT_SOAP_ENV__Fault(), soap_serializefault(), and soap_write_SOAP_ENV__Fault().
soap_serialize_SOAP_ENV__Header()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header (struct soap * soap, const struct SOAP_ENV__Header * a)
Definition at line 1208 of file soapC.cpp.
Referenced by soap_POST_send_SOAP_ENV__Header(), soap_PUT_SOAP_ENV__Header(), soap_serializeheader(), and soap_write_SOAP_ENV__Header().
soap_serialize_SOAP_ENV__Reason()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason (struct soap * soap, const struct SOAP_ENV__Reason * a)
Definition at line 863 of file soapC.cpp.
References SOAP_ENV__Reason::SOAP_ENV__Text, and soap_serialize_string().
Referenced by soap_POST_send_SOAP_ENV__Reason(), soap_PUT_SOAP_ENV__Reason(), soap_serialize_PointerToSOAP_ENV__Reason(), and soap_write_SOAP_ENV__Reason().
soap_serialize_string()
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string (struct soap * soap, char *const * a)
Definition at line 1771 of file soapC.cpp.
References SOAP_TYPE_string.
Referenced by soap_markelement(), soap_serialize_ns1__executeCommand(), soap_serialize_PointerTostring(), soap_serialize_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Reason().
soap_write__QName()
int soap_write__QName (struct soap * soap, char *const * p) inline
Definition at line 934 of file soapH.h.
References soap_put__QName().
soap_write_byte()
int soap_write_byte (struct soap * soap, char const * p) inline
Definition at line 68 of file soapH.h.
References soap_put_byte().
soap_write_int()
int soap_write_int (struct soap * soap, int const * p) inline
Definition at line 139 of file soapH.h.
References soap_put_int().
soap_write_ns1__executeCommand()
int soap_write_ns1__executeCommand (struct soap * soap, struct ns1__executeCommand const * p) inline
Definition at line 719 of file soapH.h.
References soap_put_ns1__executeCommand(), and soap_serialize_ns1__executeCommand().
soap_write_ns1__executeCommandResponse()
int soap_write_ns1__executeCommandResponse (struct soap * soap, struct ns1__executeCommandResponse const * p) inline
Definition at line 808 of file soapH.h.
References soap_put_ns1__executeCommandResponse(), and soap_serialize_ns1__executeCommandResponse().
soap_write_SOAP_ENV__Code()
int soap_write_SOAP_ENV__Code (struct soap * soap, struct SOAP_ENV__Code const * p) inline
Definition at line 537 of file soapH.h.
References soap_put_SOAP_ENV__Code(), and soap_serialize_SOAP_ENV__Code().
soap_write_SOAP_ENV__Detail()
int soap_write_SOAP_ENV__Detail (struct soap * soap, struct SOAP_ENV__Detail const * p) inline
Definition at line 442 of file soapH.h.
References soap_put_SOAP_ENV__Detail(), and soap_serialize_SOAP_ENV__Detail().
soap_write_SOAP_ENV__Fault()
int soap_write_SOAP_ENV__Fault (struct soap * soap, struct SOAP_ENV__Fault const * p) inline
Definition at line 248 of file soapH.h.
References soap_put_SOAP_ENV__Fault(), and soap_serialize_SOAP_ENV__Fault().
soap_write_SOAP_ENV__Header()
int soap_write_SOAP_ENV__Header (struct soap * soap, struct SOAP_ENV__Header const * p) inline
Definition at line 628 of file soapH.h.
References soap_put_SOAP_ENV__Header(), and soap_serialize_SOAP_ENV__Header().
soap_write_SOAP_ENV__Reason()
int soap_write_SOAP_ENV__Reason (struct soap * soap, struct SOAP_ENV__Reason const * p) inline
Definition at line 341 of file soapH.h.
References soap_put_SOAP_ENV__Reason(), and soap_serialize_SOAP_ENV__Reason().
soap_write_string()
int soap_write_string (struct soap * soap, char *const * p) inline
Definition at line 1014 of file soapH.h.
References soap_put_string().