CMaNGOS_WoTLK: SpawnManager.h File Reference
SpawnManager.h File Reference
#include "Common.h"
#include "Entities/ObjectGuid.h"
#include "Maps/SpawnGroup.h"
#include <string>
Data Structures
class SpawnInfo
class SpawnManager
Functions
bool operator< (SpawnInfo const &lhs, SpawnInfo const &rhs)
Function Documentation
operator<()
bool operator< (SpawnInfo const & lhs, SpawnInfo const & rhs)
Definition at line 25 of file SpawnManager.cpp.
References SpawnInfo::GetRespawnTime().
Referenced by ChatHandler::HandleListCreatureCommand(), and ChatHandler::HandleListObjectCommand().