CMaNGOS_WoTLK: SpellAuras.cpp File Reference
SpellAuras.cpp File Reference
#include "Common.h"
#include "Database/DatabaseEnv.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "Server/Opcodes.h"
#include "Log.h"
#include "World/World.h"
#include "Globals/ObjectMgr.h"
#include "Spells/SpellMgr.h"
#include "Entities/Player.h"
#include "Entities/Unit.h"
#include "Spells/Spell.h"
#include "Entities/DynamicObject.h"
#include "Groups/Group.h"
#include "Entities/UpdateData.h"
#include "Entities/UpdateMask.h"
#include "Globals/ObjectAccessor.h"
#include "Policies/Singleton.h"
#include "Entities/Totem.h"
#include "Entities/Creature.h"
#include "BattleGround/BattleGround.h"
#include "OutdoorPvP/OutdoorPvP.h"
#include "AI/BaseAI/CreatureAI.h"
#include "AI/ScriptDevAI/ScriptDevAIMgr.h"
#include "Util/Util.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "Entities/Vehicle.h"
#include "Grids/CellImpl.h"
#include "Tools/Language.h"
#include "Maps/MapManager.h"
#include "Loot/LootMgr.h"
#include "Entities/TemporarySpawn.h"
#include "Maps/InstanceData.h"
#include "AI/ScriptDevAI/include/sc_grid_searchers.h"
Data Structures
struct ReapplyAffectedPassiveAurasHelper
Macros
#define NULL_AURA_SLOT 0xFF
Functions
Aura * CreateAura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster, Item *castItem, uint64 scriptValue)
SpellAuraHolder * CreateSpellAuraHolder (SpellEntry const *spellproto, Unit *target, WorldObject *caster, Item *castItem, SpellEntry const *triggeredBy)
bool IsRemovedOnShapeshiftLost (SpellEntry const *spellproto, ObjectGuid const &casterGuid, ObjectGuid const &targetGuid)
Variables
pAuraHandler AuraHandler [TOTAL_AURAS]
An array with all the different handlers for taking care of the various aura types that are defined in AuraType.
static AuraType const frozenAuraTypes [] = { SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_AURA_NONE }
Macro Definition Documentation
NULL_AURA_SLOT
#define NULL_AURA_SLOT 0xFF
Definition at line 55 of file SpellAuras.cpp.
Function Documentation
CreateAura()
Aura* CreateAura (SpellEntry const * spellproto, SpellEffectIndex eff, int32 const * currentDamage, int32 const * currentBasePoints, SpellAuraHolder * holder, Unit * target, Unit * caster, Item * castItem, uint64 scriptValue)
Definition at line 524 of file SpellAuras.cpp.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), Spell::EffectApplyAreaAura(), Spell::EffectApplyAura(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::RemoveAurasDueToSpellBySteal().
CreateSpellAuraHolder()
SpellAuraHolder* CreateSpellAuraHolder (SpellEntry const * spellproto, Unit * target, WorldObject * caster, Item * castItem, SpellEntry const * triggeredBy)
Definition at line 538 of file SpellAuras.cpp.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), go_aura_generator::CheckAndApplyAura(), Spell::DoSpellHitOnUnit(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::RemoveAurasDueToSpellBySteal(), AreaAura::Update(), go_aura_generator_000AI::UpdateAI(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
IsRemovedOnShapeshiftLost()
bool IsRemovedOnShapeshiftLost (SpellEntry const * spellproto, ObjectGuid const & casterGuid, ObjectGuid const & targetGuid) inline
Definition at line 9840 of file SpellAuras.cpp.
References SpellEntry::EffectApplyAuraName, SpellEntry::HasAttribute(), SpellEntry::Id, SPELL_ATTR_AURA_IS_DEBUFF, SPELL_ATTR_EX2_ALLOW_WHILE_NOT_SHAPESHIFTED, SPELL_ATTR_NOT_SHAPESHIFT, SPELL_AURA_MOD_DODGE_PERCENT, SPELLFAMILY_DRUID, SpellEntry::SpellFamilyName, and SpellEntry::Stances.
Referenced by SpellAuraHolder::SpellAuraHolder().
Variable Documentation
AuraHandler
pAuraHandler AuraHandler[TOTAL_AURAS]
An array with all the different handlers for taking care of the various aura types that are defined in AuraType.
Definition at line 61 of file SpellAuras.cpp.
Referenced by Aura::ApplyModifier().
frozenAuraTypes
AuraType const frozenAuraTypes[] = { SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_AURA_NONE } static
Definition at line 382 of file SpellAuras.cpp.
Referenced by Aura::HandleAuraModRoot(), and Aura::HandleAuraModStun().