CMaNGOS_WoTLK: SpellMgr.h File Reference
SpellMgr.h File Reference
#include "Common.h"
#include "Globals/SharedDefines.h"
#include "Spells/SpellAuraDefines.h"
#include "Spells/SpellTargets.h"
#include "Server/DBCStructure.h"
#include "Server/DBCStores.h"
#include "Entities/DynamicObject.h"
#include "Entities/GameObject.h"
#include "Entities/Corpse.h"
#include "Entities/Unit.h"
#include "Spells/SpellAuras.h"
#include "Server/SQLStorages.h"
#include "Spells/SpellEffectDefines.h"
#include <map>
Data Structures
struct SpellProcEventEntry
struct SpellBonusEntry
struct SpellThreatEntry
struct SpellTargetEntry
struct SpellTargetPosition
struct SpellCone
class PetAura
struct SpellArea
struct SpellChainNode
struct SpellLearnSkillNode
struct SpellLearnSpellNode
struct PetDefaultSpellsEntry
class SpellMgr
Macros
#define MELEE_BASED_TRIGGER_MASK
#define NEGATIVE_TRIGGER_MASK
#define SPELL_CAST_TRIGGER_MASK
#define ELIXIR_BATTLE_MASK 0x01
#define ELIXIR_GUARDIAN_MASK 0x02
#define ELIXIR_FLASK_MASK (ELIXIR_BATTLE_MASK|ELIXIR_GUARDIAN_MASK)
#define ELIXIR_UNSTABLE_MASK 0x04
#define ELIXIR_SHATTRATH_MASK 0x08
#define ELIXIR_WELL_FED 0x10
#define MAX_SPELL_TARGET_TYPE 6
#define sSpellMgr SpellMgr::Instance()
Typedefs
typedef std::unordered_map< uint32, SpellProcEventEntry > SpellProcEventMap
typedef std::unordered_map< uint32, SpellBonusEntry > SpellBonusMap
typedef std::map< uint32, uint8 > SpellElixirMap
typedef std::map< uint32, float > SpellProcItemEnchantMap
typedef std::map< uint32, SpellThreatEntry > SpellThreatMap
typedef std::unordered_map< uint32, SpellTargetPosition > SpellTargetPositionMap
typedef std::map< uint32, PetAura > SpellPetAuraMap
typedef std::multimap< uint32, SpellArea > SpellAreaMap
typedef std::multimap< uint32, SpellArea const * > SpellAreaForAuraMap
typedef std::multimap< uint32, SpellArea const * > SpellAreaForAreaMap
typedef std::pair< SpellAreaMap::const_iterator, SpellAreaMap::const_iterator > SpellAreaMapBounds
typedef std::pair< SpellAreaForAuraMap::const_iterator, SpellAreaForAuraMap::const_iterator > SpellAreaForAuraMapBounds
typedef std::pair< SpellAreaForAreaMap::const_iterator, SpellAreaForAreaMap::const_iterator > SpellAreaForAreaMapBounds
typedef std::unordered_map< uint32, SpellChainNode > SpellChainMap
typedef std::multimap< uint32, uint32 > SpellChainMapNext
typedef std::map< uint32, SpellLearnSkillNode > SpellLearnSkillMap
typedef std::multimap< uint32, SpellLearnSpellNode > SpellLearnSpellMap
typedef std::pair< SpellLearnSpellMap::const_iterator, SpellLearnSpellMap::const_iterator > SpellLearnSpellMapBounds
typedef std::multimap< uint32, SkillLineAbilityEntry const * > SkillLineAbilityMap
typedef std::pair< SkillLineAbilityMap::const_iterator, SkillLineAbilityMap::const_iterator > SkillLineAbilityMapBounds
typedef std::multimap< uint32, SkillRaceClassInfoEntry const * > SkillRaceClassInfoMap
typedef std::pair< SkillRaceClassInfoMap::const_iterator, SkillRaceClassInfoMap::const_iterator > SkillRaceClassInfoMapBounds
typedef std::multimap< uint32, uint32 > PetLevelupSpellSet
typedef std::map< uint32, PetLevelupSpellSet > PetLevelupSpellMap
typedef std::map< int32, PetDefaultSpellsEntry > PetDefaultSpellsMap
Enumerations
enum SpellCategories { SPELLCATEGORY_HEALTH_MANA_POTIONS = 4 , SPELLCATEGORY_DEVOUR_MAGIC = 12 , SPELLCATEGORY_JUDGEMENT = 1210 }
enum SpellSpecific {
SPELL_NORMAL , SPELL_FOOD , SPELL_DRINK , SPELL_FOOD_AND_DRINK ,
SPELL_WELL_FED , SPELL_FLASK_ELIXIR , SPELL_SEAL , SPELL_JUDGEMENT ,
SPELL_BLESSING , SPELL_AURA , SPELL_STING , SPELL_ASPECT ,
SPELL_TRACKER , SPELL_CURSE , SPELL_MAGE_ARMOR , SPELL_WARLOCK_ARMOR ,
SPELL_ELEMENTAL_SHIELD , SPELL_BUFF_CASTER_POWER , SPELL_BATTLE_ELIXIR , SPELL_GUARDIAN_ELIXIR ,
SPELL_SHOUT_BUFF , SPELL_CORRUPTION_DEBUFF , SPELL_UA_IMMOLATE , SPELL_HAND ,
SPELL_PRESENCE
}
enum ProcFlags : uint32 {
PROC_FLAG_NONE = 0x00000000 , PROC_FLAG_HEARTBEAT = 0x00000001 , PROC_FLAG_KILL = 0x00000002 , PROC_FLAG_DEAL_MELEE_SWING = 0x00000004 ,
PROC_FLAG_TAKE_MELEE_SWING = 0x00000008 , PROC_FLAG_DEAL_MELEE_ABILITY = 0x00000010 , PROC_FLAG_TAKE_MELEE_ABILITY = 0x00000020 , PROC_FLAG_DEAL_RANGED_ATTACK = 0x00000040 ,
PROC_FLAG_TAKE_RANGED_ATTACK = 0x00000080 , PROC_FLAG_DEAL_RANGED_ABILITY = 0x00000100 , PROC_FLAG_TAKE_RANGED_ABILITY = 0x00000200 , PROC_FLAG_DEAL_HELPFUL_ABILITY = 0x00000400 ,
PROC_FLAG_TAKE_HELPFUL_ABILITY = 0x00000800 , PROC_FLAG_DEAL_HARMFUL_ABILITY = 0x00001000 , PROC_FLAG_TAKE_HARMFUL_ABILITY = 0x00002000 , PROC_FLAG_DEAL_HELPFUL_SPELL = 0x00004000 ,
PROC_FLAG_TAKE_HELPFUL_SPELL = 0x00008000 , PROC_FLAG_DEAL_HARMFUL_SPELL = 0x00010000 , PROC_FLAG_TAKE_HARMFUL_SPELL = 0x00020000 , PROC_FLAG_DEAL_HARMFUL_PERIODIC = 0x00040000 ,
PROC_FLAG_TAKE_HARMFUL_PERIODIC = 0x00080000 , PROC_FLAG_TAKE_ANY_DAMAGE = 0x00100000 , PROC_FLAG_ON_TRAP_ACTIVATION = 0x00200000 , PROC_FLAG_MAIN_HAND_WEAPON_SWING = 0x00400000 ,
PROC_FLAG_OFF_HAND_WEAPON_SWING = 0x00800000 , PROC_FLAG_DEATH = 0x01000000
}
enum ProcFlagsEx {
PROC_EX_NONE = 0x0000000 , PROC_EX_NORMAL_HIT = 0x0000001 , PROC_EX_CRITICAL_HIT = 0x0000002 , PROC_EX_MISS = 0x0000004 ,
PROC_EX_RESIST = 0x0000008 , PROC_EX_DODGE = 0x0000010 , PROC_EX_PARRY = 0x0000020 , PROC_EX_BLOCK = 0x0000040 ,
PROC_EX_EVADE = 0x0000080 , PROC_EX_IMMUNE = 0x0000100 , PROC_EX_DEFLECT = 0x0000200 , PROC_EX_ABSORB = 0x0000400 ,
PROC_EX_REFLECT = 0x0000800 , PROC_EX_INTERRUPT = 0x0001000 , PROC_EX_FULL_BLOCK = 0x0002000 , PROC_EX_RESERVED2 = 0x0004000 ,
PROC_EX_RESERVED3 = 0x0008000 , PROC_EX_EX_TRIGGER_ALWAYS = 0x0010000 , PROC_EX_EX_ONE_TIME_TRIGGER = 0x0020000 , PROC_EX_PERIODIC_POSITIVE = 0x0040000 ,
PROC_EX_CAST_END = 0x0080000 , PROC_EX_MAGNET = 0x0100000 , PROC_EX_INTERNAL_HOT = 0x2000000
}
enum SpellTargetType {
SPELL_TARGET_TYPE_GAMEOBJECT = 0 , SPELL_TARGET_TYPE_CREATURE = 1 , SPELL_TARGET_TYPE_DEAD = 2 , SPELL_TARGET_TYPE_CREATURE_GUID = 3 ,
SPELL_TARGET_TYPE_GAMEOBJECT_GUID = 4 , SPELL_TARGET_TYPE_STRING_ID = 5
}
Functions
SpellSpecific GetSpellSpecific (uint32 spellId)
float GetSpellRadius (SpellRadiusEntry const *radius)
uint32 GetSpellCastTime (SpellEntry const *spellInfo, WorldObject *caster, Spell *spell=nullptr, bool consume=false)
uint32 GetSpellCastTimeForBonus (SpellEntry const *spellProto, DamageEffectType damagetype)
float CalculateDefaultCoefficient (SpellEntry const *spellProto, DamageEffectType const damagetype)
float GetSpellMinRange (SpellRangeEntry const *range, bool friendly=false)
float GetSpellMaxRange (SpellRangeEntry const *range, bool friendly=false)
uint32 GetSpellRecoveryTime (SpellEntry const *spellInfo)
int32 GetSpellDuration (SpellEntry const *spellInfo)
int32 GetSpellMaxDuration (SpellEntry const *spellInfo)
int32 CalculateSpellDuration (SpellEntry const *spellInfo, Unit const *caster, Unit const *target, AuraScript *auraScript)
uint16 GetSpellAuraMaxTicks (SpellEntry const *spellInfo)
uint16 GetSpellAuraMaxTicks (uint32 spellId)
WeaponAttackType GetWeaponAttackType (SpellEntry const *spellInfo)
bool IsSpellHaveEffect (SpellEntry const *spellInfo, SpellEffects effect)
bool IsAuraApplyEffect (SpellEntry const *spellInfo, SpellEffectIndex effecIdx)
bool IsAuraApplyEffects (SpellEntry const *entry, SpellEffectIndexMask mask)
bool IsSpellAppliesAura (SpellEntry const *spellInfo, uint32 effectMask=((1<< EFFECT_INDEX_0)|(1<< EFFECT_INDEX_1)|(1<< EFFECT_INDEX_2)))
bool IsSpellWithNonAuraEffect (SpellEntry const *spellInfo)
uint32 GetAuraEffectMask (SpellEntry const *spellInfo)
bool IsEffectHandledImmediatelySpellLaunch (SpellEntry const *spellInfo, SpellEffectIndex effecIdx)
bool IsPeriodicRegenerateEffect (SpellEntry const *spellInfo, SpellEffectIndex effecIdx)
bool IsCastEndProcModifierAura (SpellEntry const *spellInfo, SpellEffectIndex effecIdx, SpellEntry const *procSpell)
bool IsSpellHaveAura (SpellEntry const *spellInfo, AuraType aura, uint32 effectMask=(1<< EFFECT_INDEX_0)|(1<< EFFECT_INDEX_1)|(1<< EFFECT_INDEX_2))
bool IsNextMeleeSwingSpell (SpellEntry const *spellInfo)
bool IsSpellLastAuraEffect (SpellEntry const *spellInfo, SpellEffectIndex effecIdx)
bool IsSealSpell (SpellEntry const *spellInfo)
bool IsAuraRemoveOnStacking (SpellEntry const *spellInfo, int32 effIdx)
bool IsCharmAura (SpellEntry const *spellInfo, int32 effIdx)
bool IsAuraRefreshInsteadOfRecast (SpellEntry const *spellInfo, int32 effIdx)
bool IsAuraSpellRefreshInsteadOfRecast (SpellEntry const *spellInfo)
bool IsAllowingDeadTarget (SpellEntry const *spellInfo)
bool IsElementalShield (SpellEntry const *spellInfo)
bool IsExplicitDiscoverySpell (SpellEntry const *spellInfo)
bool IsLootCraftingSpell (SpellEntry const *spellInfo)
bool IsSpellEffectTriggerSpell (const SpellEntry *entry, SpellEffectIndex effIndex)
bool IsSpellEffectTriggerSpellByAura (const SpellEntry *entry, SpellEffectIndex effIndex)
bool IsSpellTriggerSpellByAura (const SpellEntry *entry)
bool IsSpellEffectAbleToCrit (const SpellEntry *entry, SpellEffectIndex index)
bool IsSpellAbleToCrit (const SpellEntry *entry)
bool IsPassiveSpell (uint32 spellId)
bool IsPassiveSpell (SpellEntry const *spellInfo)
bool IsPassiveSpellStackableWithRanks (SpellEntry const *spellProto)
bool IsSpellAffectedBySpellMods (SpellEntry const *spellInfo)
bool IsAutocastable (SpellEntry const *spellInfo)
bool IsAutocastable (uint32 spellId)
bool IsPossessCharmType (uint32 spellId)
bool IsSpellNeedSendOnObjectUpdate (uint32 spellId)
bool IsSpellRemoveAllMovementAndControlLossEffects (SpellEntry const *spellProto)
uint32 GetAllowedMechanicMask (SpellEntry const *spellProto)
bool SpellCancelsAuraEffect (SpellEntry const *spellInfo, SpellEntry const *auraSpellInfo, uint8 auraEffIndex)
bool IsDeathOnlySpell (SpellEntry const *spellInfo)
bool IsDeathPersistentSpell (SpellEntry const *spellInfo)
bool IsNonCombatSpell (SpellEntry const *spellInfo)
bool IsSpellSetRun (SpellEntry const *spellInfo)
bool IsSpellRemovedOnEvade (SpellEntry const *spellInfo)
bool IsChanneledDelayedSpell (SpellEntry const *spellInfo)
bool IsExplicitPositiveTarget (uint32 targetA)
bool IsExplicitNegativeTarget (uint32 targetA)
bool IsResistableSpell (const SpellEntry *entry)
bool IsSpellEffectDamage (SpellEntry const &spellInfo, SpellEffectIndex i)
bool IsSpellEffectDummy (SpellEntry const &spellInfo, SpellEffectIndex i)
bool IsSpellEffectsDamage (SpellEntry const &spellInfo, uint8 effectMask=EFFECT_MASK_ALL)
bool IsBinarySpell (SpellEntry const &spellInfo, uint8 effectMask=EFFECT_MASK_ALL)
bool IsCasterSourceTarget (uint32 target)
bool IsSpellWithScriptUnitTarget (SpellEntry const *spellInfo)
bool IsSpellWithCasterSourceTargetsOnly (SpellEntry const *spellInfo)
bool IsPointEffectTarget (SpellTarget target)
bool IsAreaEffectPositiveTarget (SpellTarget target)
bool IsAreaEffectTarget (SpellTarget target)
bool IsAreaOfEffectSpell (SpellEntry const *spellInfo)
bool IsAreaAuraEffect (uint32 effect)
bool HasAreaAuraEffect (SpellEntry const *spellInfo)
bool IsPersistentAuraEffect (uint32 effect)
bool HasPersistentAuraEffect (SpellEntry const *spellInfo)
bool IsOnlySelfTargeting (SpellEntry const *spellInfo)
bool IsDirectDamageSpell (SpellEntry const *spellInfo)
bool IsCheckCastTarget (uint32 target)
uint32 GetCheckCastEffectMask (SpellEntry const *spellInfo)
bool HasSpellTarget (SpellEntry const *spellInfo, uint32 target)
uint32 GetCheckCastSelfEffectMask (SpellEntry const *spellInfo)
bool IsUnitTargetTarget (uint32 target)
bool HasMissingTargetFromClient (SpellEntry const *spellInfo)
bool IsSpellRequireTarget (SpellEntry const *spellInfo)
bool IsScriptTarget (uint32 target)
bool IsNeutralTarget (uint32 target)
bool IsFriendlyTarget (uint32 target)
bool IsHostileTarget (uint32 target)
bool IsEffectTargetScript (uint32 targetA, uint32 targetB)
bool IsEffectTargetNeutral (uint32 targetA, uint32 targetB)
bool IsEffectTargetPositive (uint32 targetA, uint32 targetB)
bool IsEffectTargetNegative (uint32 targetA, uint32 targetB)
bool IsNeutralEffectTargetPositive (uint32 etarget, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveEffectTargetMode (const SpellEntry *entry, SpellEffectIndex effIndex, const WorldObject *caster=nullptr, const WorldObject *target=nullptr, bool recursive=false)
bool IsPositiveEffect (const SpellEntry *spellproto, SpellEffectIndex effIndex, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveAuraEffect (const SpellEntry *entry, SpellEffectIndex effIndex, const WorldObject *=nullptr, const WorldObject *=nullptr)
bool IsPositiveSpellTargetModeForSpecificTarget (const SpellEntry *entry, uint8 effectMask, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveSpellTargetModeForSpecificTarget (uint32 spellId, uint8 effectMask, const WorldObject *caster, const WorldObject *target)
bool IsPositiveSpellTargetMode (const SpellEntry *entry, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveSpellTargetMode (uint32 spellId, const WorldObject *caster, const WorldObject *target)
bool IsPositiveSpell (const SpellEntry *entry, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveEffectMask (const SpellEntry *entry, uint8 effectMask, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsPositiveSpell (uint32 spellId, const WorldObject *caster=nullptr, const WorldObject *target=nullptr)
bool IsSpellDoNotReportFailure (SpellEntry const *spellInfo)
bool CanPierceImmuneAura (SpellEntry const *spellInfo, SpellEntry const *auraSpellInfo, uint8 effectMask=0, SpellEffectIndex effIdx=EFFECT_INDEX_0)
void GetChainJumpRange (SpellEntry const *spellInfo, SpellEffectIndex effIdx, float &minSearchRangeCaster, float &maxSearchRangeTarget)
bool IsDispelSpell (SpellEntry const *spellInfo)
bool isSpellBreakStealth (SpellEntry const *spellInfo)
bool IsAutoRepeatRangedSpell (SpellEntry const *spellInfo)
bool IsSpellRequiresRangedAP (SpellEntry const *spellInfo)
SpellCastResult GetErrorAtShapeshiftedCast (SpellEntry const *spellInfo, uint32 form)
bool IsChanneledSpell (SpellEntry const *spellInfo)
bool IsNeedCastSpellAtFormApply (SpellEntry const *spellInfo, ShapeshiftForm form)
bool IsNeedCastSpellAtOutdoor (SpellEntry const *spellInfo)
bool IsReflectableSpell (SpellEntry const *spellInfo)
bool IsIgnoreLosSpell (SpellEntry const *spellInfo)
bool IsIgnoreLosSpellEffect (SpellEntry const *spellInfo, SpellEffectIndex effIdx)
bool IsIgnoreLosSpellCast (SpellEntry const *spellInfo)
bool IsItemAura (SpellEntry const *spellInfo)
bool NeedsComboPoints (SpellEntry const *spellInfo)
SpellSchoolMask GetSpellSchoolMask (SpellEntry const *spellInfo)
uint32 GetSpellMechanicMask (SpellEntry const *spellInfo, uint32 effectMask)
uint32 GetAllSpellMechanicMask (SpellEntry const *spellInfo)
Mechanics GetEffectMechanic (SpellEntry const *spellInfo, SpellEffectIndex effect)
bool IsIgnoreRootSpell (SpellEntry const *spellInfo)
uint32 GetDispellMask (DispelType dispel)
bool IsPartyOrRaidTarget (uint32 target)
bool IsGroupRestrictedBuff (SpellEntry const *spellInfo)
bool IsSpellSpecificUniquePerCaster (SpellSpecific specific)
bool IsSpellSpecificUniquePerTarget (SpellSpecific specific)
bool IsSpellSpecificIdentical (SpellSpecific specific, SpellSpecific specific2)
bool IsSimilarAuraEffect (SpellEntry const *entry, uint32 effect, SpellEntry const *entry2, uint32 effect2)
bool IsStackableAuraEffect (SpellEntry const *entry, SpellEntry const *entry2, uint32 i, Unit *pTarget=nullptr)
bool IsStackableSpell (SpellEntry const *entry, SpellEntry const *entry2, Unit *pTarget=nullptr)
bool IsSimilarExistingAuraStronger (const SpellAuraHolder *holder, const SpellAuraHolder *existing)
bool IsSimilarExistingAuraStronger (const Unit *caster, const SpellEntry *entry, const SpellAuraHolder *existing, uint32 affectedMask, int32 amounts[MAX_EFFECT_INDEX])
DiminishingGroup GetDiminishingReturnsGroupForSpell (SpellEntry const *spellproto, bool triggered)
bool IsDiminishingReturnsGroupDurationLimited (DiminishingGroup group)
bool IsDiminishingReturnsGroupDurationDiminished (DiminishingGroup group, bool pvp)
DiminishingReturnsType GetDiminishingReturnsGroupType (DiminishingGroup group)
int32 GetDiminishingReturnsLimitDuration (DiminishingGroup group, SpellEntry const *spellproto)
bool IsSubjectToDiminishingLevels (DiminishingGroup group, bool pvp)
bool IsCreatureDRSpell (SpellEntry const *spellInfo)
SpellEntry const * GetSpellEntryByDifficulty (uint32 id, Difficulty difficulty, bool isRaid)
bool IsPrimaryProfessionSkill (uint32 skill)
bool IsProfessionSkill (uint32 skill)
bool IsProfessionOrRidingSkill (uint32 skill)
Macro Definition Documentation
ELIXIR_BATTLE_MASK
#define ELIXIR_BATTLE_MASK 0x01
Definition at line 2539 of file SpellMgr.h.
ELIXIR_FLASK_MASK
#define ELIXIR_FLASK_MASK (ELIXIR_BATTLE_MASK|ELIXIR_GUARDIAN_MASK)
Definition at line 2541 of file SpellMgr.h.
ELIXIR_GUARDIAN_MASK
#define ELIXIR_GUARDIAN_MASK 0x02
Definition at line 2540 of file SpellMgr.h.
ELIXIR_SHATTRATH_MASK
#define ELIXIR_SHATTRATH_MASK 0x08
Definition at line 2543 of file SpellMgr.h.
ELIXIR_UNSTABLE_MASK
#define ELIXIR_UNSTABLE_MASK 0x04
Definition at line 2542 of file SpellMgr.h.
ELIXIR_WELL_FED
#define ELIXIR_WELL_FED 0x10
Definition at line 2544 of file SpellMgr.h.
MAX_SPELL_TARGET_TYPE
#define MAX_SPELL_TARGET_TYPE 6
Definition at line 2568 of file SpellMgr.h.
MELEE_BASED_TRIGGER_MASK
#define MELEE_BASED_TRIGGER_MASK
Value:
                                  (PROC_FLAG_DEAL_MELEE_SWING        | \
                                  PROC_FLAG_TAKE_MELEE_SWING             | \
                                  PROC_FLAG_DEAL_MELEE_ABILITY  | \
                                  PROC_FLAG_TAKE_MELEE_ABILITY       | \
                                  PROC_FLAG_DEAL_RANGED_ATTACK       | \
                                  PROC_FLAG_TAKE_RANGED_ABILITY            | \
                                  PROC_FLAG_DEAL_RANGED_ABILITY | \
                                  PROC_FLAG_TAKE_RANGED_ABILITY)
Definition at line 2465 of file SpellMgr.h.
NEGATIVE_TRIGGER_MASK
#define NEGATIVE_TRIGGER_MASK
Value:
                               (MELEE_BASED_TRIGGER_MASK                | \
                               PROC_FLAG_DEAL_HARMFUL_ABILITY      | \
                               PROC_FLAG_TAKE_HARMFUL_ABILITY           | \
                               PROC_FLAG_DEAL_HARMFUL_SPELL | \
                               PROC_FLAG_TAKE_HARMFUL_SPELL)
Definition at line 2474 of file SpellMgr.h.
SPELL_CAST_TRIGGER_MASK
#define SPELL_CAST_TRIGGER_MASK
Value:
                                 (PROC_FLAG_SUCCESSFUL_MELEE_SPELL_HIT    | \
                                 PROC_FLAG_SUCCESSFUL_RANGED_HIT         | \
                                 PROC_FLAG_SUCCESSFUL_RANGED_SPELL_HIT   | \
                                 PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_POS | \
                                 PROC_FLAG_DONE_SPELL_NONE_DMG_CLASS_NEG | \
                                 PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_POS| \
                                 PROC_FLAG_DONE_SPELL_MAGIC_DMG_CLASS_NEG)
Definition at line 2480 of file SpellMgr.h.
sSpellMgr
#define sSpellMgr SpellMgr::Instance()
Definition at line 3356 of file SpellMgr.h.
Typedef Documentation
PetDefaultSpellsMap
typedef std::map<int32, PetDefaultSpellsEntry> PetDefaultSpellsMap
Definition at line 2725 of file SpellMgr.h.
PetLevelupSpellMap
typedef std::map<uint32, PetLevelupSpellSet> PetLevelupSpellMap
Definition at line 2712 of file SpellMgr.h.
PetLevelupSpellSet
typedef std::multimap<uint32, uint32> PetLevelupSpellSet
Definition at line 2711 of file SpellMgr.h.
SkillLineAbilityMap
typedef std::multimap<uint32, SkillLineAbilityEntry const*> SkillLineAbilityMap
Definition at line 2705 of file SpellMgr.h.
SkillLineAbilityMapBounds
typedef std::pair<SkillLineAbilityMap::const_iterator, SkillLineAbilityMap::const_iterator> SkillLineAbilityMapBounds
Definition at line 2706 of file SpellMgr.h.
SkillRaceClassInfoMap
typedef std::multimap<uint32, SkillRaceClassInfoEntry const*> SkillRaceClassInfoMap
Definition at line 2708 of file SpellMgr.h.
SkillRaceClassInfoMapBounds
typedef std::pair<SkillRaceClassInfoMap::const_iterator, SkillRaceClassInfoMap::const_iterator> SkillRaceClassInfoMapBounds
Definition at line 2709 of file SpellMgr.h.
SpellAreaForAreaMap
typedef std::multimap<uint32 , SpellArea const*> SpellAreaForAreaMap
Definition at line 2668 of file SpellMgr.h.
SpellAreaForAreaMapBounds
typedef std::pair<SpellAreaForAreaMap::const_iterator, SpellAreaForAreaMap::const_iterator> SpellAreaForAreaMapBounds
Definition at line 2671 of file SpellMgr.h.
SpellAreaForAuraMap
typedef std::multimap<uint32 , SpellArea const*> SpellAreaForAuraMap
Definition at line 2667 of file SpellMgr.h.
SpellAreaForAuraMapBounds
typedef std::pair<SpellAreaForAuraMap::const_iterator, SpellAreaForAuraMap::const_iterator> SpellAreaForAuraMapBounds
Definition at line 2670 of file SpellMgr.h.
SpellAreaMap
typedef std::multimap<uint32 , SpellArea> SpellAreaMap
Definition at line 2666 of file SpellMgr.h.
SpellAreaMapBounds
typedef std::pair<SpellAreaMap::const_iterator, SpellAreaMap::const_iterator> SpellAreaMapBounds
Definition at line 2669 of file SpellMgr.h.
SpellBonusMap
typedef std::unordered_map<uint32, SpellBonusEntry> SpellBonusMap
Definition at line 2537 of file SpellMgr.h.
SpellChainMap
typedef std::unordered_map<uint32, SpellChainNode> SpellChainMap
Definition at line 2682 of file SpellMgr.h.
SpellChainMapNext
typedef std::multimap<uint32, uint32> SpellChainMapNext
Definition at line 2683 of file SpellMgr.h.
SpellElixirMap
typedef std::map<uint32, uint8> SpellElixirMap
Definition at line 2553 of file SpellMgr.h.
SpellLearnSkillMap
typedef std::map<uint32, SpellLearnSkillNode> SpellLearnSkillMap
Definition at line 2693 of file SpellMgr.h.
SpellLearnSpellMap
typedef std::multimap<uint32, SpellLearnSpellNode> SpellLearnSpellMap
Definition at line 2702 of file SpellMgr.h.
SpellLearnSpellMapBounds
typedef std::pair<SpellLearnSpellMap::const_iterator, SpellLearnSpellMap::const_iterator> SpellLearnSpellMapBounds
Definition at line 2703 of file SpellMgr.h.
SpellPetAuraMap
typedef std::map<uint32, PetAura> SpellPetAuraMap
Definition at line 2646 of file SpellMgr.h.
SpellProcEventMap
typedef std::unordered_map<uint32, SpellProcEventEntry> SpellProcEventMap
Definition at line 2536 of file SpellMgr.h.
SpellProcItemEnchantMap
typedef std::map<uint32, float> SpellProcItemEnchantMap
Definition at line 2554 of file SpellMgr.h.
SpellTargetPositionMap
typedef std::unordered_map<uint32, SpellTargetPosition> SpellTargetPositionMap
Definition at line 2597 of file SpellMgr.h.
SpellThreatMap
typedef std::map<uint32, SpellThreatEntry> SpellThreatMap
Definition at line 2555 of file SpellMgr.h.
Enumeration Type Documentation
ProcFlags
enum ProcFlags : uint32
Enumerator
PROC_FLAG_NONE
PROC_FLAG_HEARTBEAT
PROC_FLAG_KILL
PROC_FLAG_DEAL_MELEE_SWING
PROC_FLAG_TAKE_MELEE_SWING
PROC_FLAG_DEAL_MELEE_ABILITY
PROC_FLAG_TAKE_MELEE_ABILITY
PROC_FLAG_DEAL_RANGED_ATTACK
PROC_FLAG_TAKE_RANGED_ATTACK
PROC_FLAG_DEAL_RANGED_ABILITY
PROC_FLAG_TAKE_RANGED_ABILITY
PROC_FLAG_DEAL_HELPFUL_ABILITY
PROC_FLAG_TAKE_HELPFUL_ABILITY
PROC_FLAG_DEAL_HARMFUL_ABILITY
PROC_FLAG_TAKE_HARMFUL_ABILITY
PROC_FLAG_DEAL_HELPFUL_SPELL
PROC_FLAG_TAKE_HELPFUL_SPELL
PROC_FLAG_DEAL_HARMFUL_SPELL
PROC_FLAG_TAKE_HARMFUL_SPELL
PROC_FLAG_DEAL_HARMFUL_PERIODIC
PROC_FLAG_TAKE_HARMFUL_PERIODIC
PROC_FLAG_TAKE_ANY_DAMAGE
PROC_FLAG_ON_TRAP_ACTIVATION
PROC_FLAG_MAIN_HAND_WEAPON_SWING
PROC_FLAG_OFF_HAND_WEAPON_SWING
PROC_FLAG_DEATH
Definition at line 2422 of file SpellMgr.h.
ProcFlagsEx
enum ProcFlagsEx
Enumerator
PROC_EX_NONE
PROC_EX_NORMAL_HIT
PROC_EX_CRITICAL_HIT
PROC_EX_MISS
PROC_EX_RESIST
PROC_EX_DODGE
PROC_EX_PARRY
PROC_EX_BLOCK
PROC_EX_EVADE
PROC_EX_IMMUNE
PROC_EX_DEFLECT
PROC_EX_ABSORB
PROC_EX_REFLECT
PROC_EX_INTERRUPT
PROC_EX_FULL_BLOCK
PROC_EX_RESERVED2
PROC_EX_RESERVED3
PROC_EX_EX_TRIGGER_ALWAYS
PROC_EX_EX_ONE_TIME_TRIGGER
PROC_EX_PERIODIC_POSITIVE
PROC_EX_CAST_END
PROC_EX_MAGNET
PROC_EX_INTERNAL_HOT
Definition at line 2487 of file SpellMgr.h.
SpellCategories
enum SpellCategories
Enumerator
SPELLCATEGORY_HEALTH_MANA_POTIONS
SPELLCATEGORY_DEVOUR_MAGIC
SPELLCATEGORY_JUDGEMENT
Definition at line 47 of file SpellMgr.h.
SpellSpecific
enum SpellSpecific
Enumerator
SPELL_NORMAL
SPELL_FOOD
SPELL_DRINK
SPELL_FOOD_AND_DRINK
SPELL_WELL_FED
SPELL_FLASK_ELIXIR
SPELL_SEAL
SPELL_JUDGEMENT
SPELL_BLESSING
SPELL_AURA
SPELL_STING
SPELL_ASPECT
SPELL_TRACKER
SPELL_CURSE
SPELL_MAGE_ARMOR
SPELL_WARLOCK_ARMOR
SPELL_ELEMENTAL_SHIELD
SPELL_BUFF_CASTER_POWER
SPELL_BATTLE_ELIXIR
SPELL_GUARDIAN_ELIXIR
SPELL_SHOUT_BUFF
SPELL_CORRUPTION_DEBUFF
SPELL_UA_IMMOLATE
SPELL_HAND
SPELL_PRESENCE
Definition at line 55 of file SpellMgr.h.
SpellTargetType
enum SpellTargetType
Enumerator
SPELL_TARGET_TYPE_GAMEOBJECT
SPELL_TARGET_TYPE_CREATURE
SPELL_TARGET_TYPE_DEAD
SPELL_TARGET_TYPE_CREATURE_GUID
SPELL_TARGET_TYPE_GAMEOBJECT_GUID
SPELL_TARGET_TYPE_STRING_ID
Definition at line 2558 of file SpellMgr.h.
Function Documentation
CalculateDefaultCoefficient()
float CalculateDefaultCoefficient (SpellEntry const * spellProto, DamageEffectType const damagetype)
Definition at line 319 of file SpellMgr.cpp.
References DOT, GetSpellAuraMaxTicks(), GetSpellCastTimeForBonus(), GetSpellDuration(), and IsChanneledSpell().
Referenced by ChatHandler::HandleDebugSpellCoefsCommand(), SpellMgr::LoadSpellBonuses(), and Unit::SpellBonusWithCoeffs().
CalculateSpellDuration()
int32 CalculateSpellDuration (SpellEntry const * spellInfo, Unit const * caster, Unit const * target, AuraScript * auraScript)
Definition at line 79 of file SpellMgr.cpp.
References Unit::GetComboPoints(), Object::GetFloatValue(), GetSpellDuration(), GetSpellMaxDuration(), WorldObject::GetSpellModOwner(), Unit::HasAffectedAura(), SpellEntry::HasAttribute(), SpellEntry::Id, Object::IsPlayer(), AuraScript::OnDurationCalculate(), SPELL_ATTR_EX3_IGNORE_CASTER_MODIFIERS, SPELL_ATTR_EX5_SPELL_HASTE_AFFECTS_PERIODIC, SPELL_AURA_PERIODIC_HASTE, SPELLMOD_DURATION, and UNIT_MOD_CAST_SPEED.
Referenced by Spell::AddUnitTarget(), Spell::cast(), and SpellAuraHolder::SpellAuraHolder().
CanPierceImmuneAura()
bool CanPierceImmuneAura (SpellEntry const * spellInfo, SpellEntry const * auraSpellInfo, uint8 effectMask = 0, SpellEffectIndex effIdx = EFFECT_INDEX_0) inline
Definition at line 1685 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectMechanic, SpellEntry::EffectMiscValue, SpellEntry::HasAttribute(), MAX_EFFECT_INDEX, SpellEntry::Mechanic, MECHANIC_BANISH, MECHANIC_IMMUNE_SHIELD, MECHANIC_INVULNERABILITY, SPELL_ATTR_EX2_NO_SCHOOL_IMMUNITIES, SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, SPELL_ATTR_EX_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS, SPELL_ATTR_NO_IMMUNITIES, and SPELL_AURA_MECHANIC_IMMUNITY_MASK.
Referenced by Unit::IsImmuneToSchool(), and Unit::IsImmuneToSpell().
GetAllowedMechanicMask()
uint32 GetAllowedMechanicMask (SpellEntry const * spellProto) inline
Definition at line 492 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectMiscValue, MAX_EFFECT_INDEX, SPELL_AURA_MECHANIC_IMMUNITY, and SPELL_AURA_MECHANIC_IMMUNITY_MASK.
Referenced by Spell::CheckCasterAuras().
GetAllSpellMechanicMask()
uint32 GetAllSpellMechanicMask (SpellEntry const * spellInfo) inline
Definition at line 1893 of file SpellMgr.h.
References SpellEntry::EffectMechanic, and SpellEntry::Mechanic.
Referenced by SpellAuraHolder::_AddSpellAuraHolder(), SpellAuraHolder::_RemoveSpellAuraHolder(), GetDiminishingReturnsGroupForSpell(), Aura::HandleAuraModShapeshift(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), Unit::MeleeDamageBonusTaken(), Unit::RemoveSpellsCausingAura(), and Unit::SpellDamageBonusTaken().
GetAuraEffectMask()
uint32 GetAuraEffectMask (SpellEntry const * spellInfo) inline
Definition at line 178 of file SpellMgr.h.
References IsAuraApplyEffect(), and MAX_EFFECT_INDEX.
Referenced by Spell::AddUnitTarget().
GetChainJumpRange()
void GetChainJumpRange (SpellEntry const * spellInfo, SpellEffectIndex effIdx, float & minSearchRangeCaster, float & maxSearchRangeTarget) inline
Definition at line 1725 of file SpellMgr.h.
References CHAIN_SPELL_JUMP_RADIUS, SpellEntry::DmgClass, SpellEntry::EffectChainTarget, SpellEntry::Id, SpellRangeEntry::ID, SpellRangeEntry::maxRange, SpellEntry::rangeIndex, SPELL_DAMAGE_CLASS_MELEE, and sSpellRangeStore.
Referenced by Spell::SetTargetMap().
GetCheckCastEffectMask()
uint32 GetCheckCastEffectMask (SpellEntry const * spellInfo) inline
Definition at line 1243 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, IsCheckCastTarget(), and MAX_EFFECT_INDEX.
Referenced by Spell::CheckCast(), and Unit::MeetsSelectAttackingRequirement().
GetCheckCastSelfEffectMask()
uint32 GetCheckCastSelfEffectMask (SpellEntry const * spellInfo) inline
Definition at line 1261 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, MAX_EFFECT_INDEX, and TARGET_UNIT_CASTER.
Referenced by Spell::CheckCast().
GetDiminishingReturnsGroupForSpell()
DiminishingGroup GetDiminishingReturnsGroupForSpell (SpellEntry const * spellproto, bool triggered)
Definition at line 3293 of file SpellMgr.cpp.
References DIMINISHING_BANISH, DIMINISHING_CHEAPSHOT_POUNCE, DIMINISHING_CONTROL_ROOT, DIMINISHING_CONTROL_STUN, DIMINISHING_CYCLONE, DIMINISHING_DISARM, DIMINISHING_DISORIENT, DIMINISHING_FEAR_CHARM_BLIND, DIMINISHING_FREEZE_SLEEP, DIMINISHING_HORROR, DIMINISHING_LIMITONLY, DIMINISHING_NONE, DIMINISHING_SILENCE, DIMINISHING_TRIGGER_ROOT, DIMINISHING_TRIGGER_STUN, GetAllSpellMechanicMask(), SpellEntry::IsFitToFamilyMask(), SpellEntry::Mechanic, MECHANIC_BANISH, MECHANIC_CHARM, MECHANIC_DISARM, MECHANIC_FEAR, MECHANIC_FREEZE, MECHANIC_HORROR, MECHANIC_INTERRUPT, MECHANIC_KNOCKOUT, MECHANIC_POLYMORPH, MECHANIC_ROOT, MECHANIC_SAPPED, MECHANIC_SHACKLE, MECHANIC_SILENCE, MECHANIC_SLEEP, MECHANIC_STUN, MECHANIC_TURN, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_PRIEST, SPELLFAMILY_ROGUE, SPELLFAMILY_UNK1, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyName, and SpellEntry::SpellIconID.
Referenced by Spell::AddUnitTarget().
GetDiminishingReturnsGroupType()
DiminishingReturnsType GetDiminishingReturnsGroupType (DiminishingGroup group)
Definition at line 3469 of file SpellMgr.cpp.
References DIMINISHING_BANISH, DIMINISHING_CHEAPSHOT_POUNCE, DIMINISHING_CONTROL_ROOT, DIMINISHING_CONTROL_STUN, DIMINISHING_CYCLONE, DIMINISHING_DISARM, DIMINISHING_DISORIENT, DIMINISHING_FEAR_CHARM_BLIND, DIMINISHING_FREEZE_SLEEP, DIMINISHING_HORROR, DIMINISHING_SILENCE, DIMINISHING_TRIGGER_ROOT, DIMINISHING_TRIGGER_STUN, DRTYPE_ALL, DRTYPE_NONE, and DRTYPE_PLAYER.
Referenced by IsSubjectToDiminishingLevels().
GetDiminishingReturnsLimitDuration()
int32 GetDiminishingReturnsLimitDuration (DiminishingGroup group, SpellEntry const * spellproto)
Definition at line 3409 of file SpellMgr.cpp.
References IsDiminishingReturnsGroupDurationLimited(), SPELLFAMILY_DRUID, SPELLFAMILY_PALADIN, SpellEntry::SpellFamilyFlags, and SpellEntry::SpellFamilyName.
Referenced by Unit::ApplyDiminishingToDuration().
GetDispellMask()
uint32 GetDispellMask (DispelType dispel) inline
Definition at line 1926 of file SpellMgr.h.
References DISPEL_ALL, and DISPEL_ALL_MASK.
Referenced by UnitAI::DoFindFriendlyEligibleDispel(), Spell::EffectDispel(), Spell::EffectStealBeneficialBuff(), PlayerbotClassAI::GetDispelTarget(), PlayerbotHunterAI::IsTargetEnraged(), and Unit::RemoveAurasWithDispelType().
GetEffectMechanic()
Mechanics GetEffectMechanic (SpellEntry const * spellInfo, SpellEffectIndex effect) inline
Definition at line 1904 of file SpellMgr.h.
References SpellEntry::EffectMechanic, SpellEntry::Mechanic, and MECHANIC_NONE.
Referenced by Aura::PeriodicTick().
GetErrorAtShapeshiftedCast()
SpellCastResult GetErrorAtShapeshiftedCast (SpellEntry const * spellInfo, uint32 form)
Definition at line 527 of file SpellMgr.cpp.
References SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellShapeshiftFormEntry::flags1, GetTalentSpellCost(), SpellEntry::HasAttribute(), SpellEntry::Id, sLog, SPELL_ATTR_EX2_ALLOW_WHILE_NOT_SHAPESHIFTED, SPELL_ATTR_NOT_SHAPESHIFT, SPELL_CAST_OK, SPELL_EFFECT_LEARN_SPELL, SPELL_FAILED_NOT_SHAPESHIFT, SPELL_FAILED_ONLY_SHAPESHIFT, sSpellShapeshiftFormStore, SpellEntry::Stances, and SpellEntry::StancesNot.
Referenced by Player::ApplyEquipSpell(), and Spell::CheckCast().
GetSpellAuraMaxTicks() [1/2]
uint16 GetSpellAuraMaxTicks (SpellEntry const * spellInfo)
Definition at line 281 of file SpellMgr.cpp.
References SpellEntry::Effect, SpellEntry::EffectAmplitude, SpellEntry::EffectApplyAuraName, GetSpellDuration(), MAX_EFFECT_INDEX, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, and SPELL_EFFECT_APPLY_AURA.
Referenced by CalculateDefaultCoefficient(), GetSpellAuraMaxTicks(), and Unit::HandleDummyAuraProc().
GetSpellAuraMaxTicks() [2/2]
uint16 GetSpellAuraMaxTicks (uint32 spellId)
Definition at line 307 of file SpellMgr.cpp.
References GetSpellAuraMaxTicks(), SQLStorage::LookupEntry(), sLog, and sSpellTemplate.
GetSpellCastTime()
uint32 GetSpellCastTime (SpellEntry const * spellInfo, WorldObject * caster, Spell * spell = nullptr, bool consume = false)
Definition at line 110 of file SpellMgr.cpp.
References SpellEntry::baseLevel, SpellEntry::CastingTimeIndex, SpellCastTimesEntry::CastTime, SpellCastTimesEntry::CastTimePerLevel, Spell::GetCastItem(), Object::GetFloatValue(), SpellCastTargets::getItemTarget(), WorldObject::GetSpellModOwner(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, Spell::IsAutoRepeat(), Object::IsPlayer(), Spell::IsRangedSpell(), Spell::IsTriggeredSpellWithRedundantCastTime(), Object::IsUnit(), Unit::m_modAttackSpeedPct, Spell::m_targets, SpellCastTimesEntry::MinCastTime, RANGED_ATTACK, SPELL_ATTR_EX3_IGNORE_CASTER_MODIFIERS, SPELL_ATTR_IS_ABILITY, SPELL_ATTR_IS_TRADESKILL, SPELL_ATTR_USES_RANGED_SLOT, SPELLMOD_CASTING_TIME, sSpellCastTimesStore, TRADE_SLOT_NONTRADED, TYPEID_GAMEOBJECT, and UNIT_MOD_CAST_SPEED.
Referenced by GetSpellCastTimeForBonus(), Unit::HandleModCastingSpeedNotStackAuraProc(), Spell::Prepare(), and Totem::SetTypeBySummonSpell().
GetSpellCastTimeForBonus()
uint32 GetSpellCastTimeForBonus (SpellEntry const * spellProto, DamageEffectType damagetype)
Definition at line 179 of file SpellMgr.cpp.
References DOT, SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, GetSpellCastTime(), GetSpellDuration(), IsAreaEffectTarget(), IsChanneledSpell(), MAX_EFFECT_INDEX, SPELL_AURA_DUMMY, SPELL_AURA_MOD_CONFUSE, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_ROOT, SPELL_AURA_MOD_STUN, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_POWER_BURN, SPELL_EFFECT_POWER_DRAIN, and SPELL_EFFECT_SCHOOL_DAMAGE.
Referenced by CalculateDefaultCoefficient().
GetSpellDuration()
int32 GetSpellDuration (SpellEntry const * spellInfo)
Definition at line 59 of file SpellMgr.cpp.
References SpellDurationEntry::Duration, SpellEntry::DurationIndex, and sSpellDurationStore.
Referenced by CalculateDefaultCoefficient(), CalculateSpellDuration(), SpellAuraHolder::CleanupTriggeredSpells(), Spell::DelayedChannel(), Spell::EffectHeal(), Spell::EffectInterruptCast(), GetSpellAuraMaxTicks(), GetSpellCastTimeForBonus(), Pet::LoadPetFromDB(), Pet::TryLoadFromDB(), PetAI::UpdateAI(), and PlayerbotAI::UseItem().
GetSpellEntryByDifficulty()
SpellEntry const* GetSpellEntryByDifficulty (uint32 id, Difficulty difficulty, bool isRaid)
Definition at line 3586 of file SpellMgr.cpp.
References GetPrevDifficulty(), SQLStorage::LookupEntry(), REGULAR_DIFFICULTY, SpellDifficultyEntry::spellId, sSpellDifficultyStore, and sSpellTemplate.
Referenced by Unit::HasAuraOfDifficulty(), Creature::LoadCreatureAddon(), Unit::RemoveAurasDueToSpell(), and Spell::Spell().
GetSpellMaxDuration()
int32 GetSpellMaxDuration (SpellEntry const * spellInfo)
Definition at line 69 of file SpellMgr.cpp.
References SpellDurationEntry::Duration, SpellEntry::DurationIndex, and sSpellDurationStore.
Referenced by SpellAuraHolder::_AddSpellAuraHolder(), and CalculateSpellDuration().
GetSpellMaxRange()
float GetSpellMaxRange (SpellRangeEntry const * range, bool friendly = false) inline
Definition at line 99 of file SpellMgr.h.
References SpellRangeEntry::maxRange, and SpellRangeEntry::maxRangeFriendly.
Referenced by UnitAI::CalculateSpellRange(), Spell::CheckCast(), Spell::EffectDummy(), Spell::EffectTransmitted(), Spell::FindCorpseUsing(), Spell::GetMinMaxRange(), Spell::GetSpellRangeAndRadius(), Unit::HandleDummyAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), PlayerbotAI::initSpell(), GameObject::IsAtInteractDistance(), Unit::MeetsSelectAttackingRequirement(), DemonBroiledSurprise::OnCheckCast(), RaiseDeadHyjal::OnCheckCast(), TossIceBoulder::OnRadiusCalculate(), RandomRadiusPicker::OnRadiusCalculate(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), Spell::SetTargetMap(), and TotemAI::UpdateAI().
GetSpellMechanicMask()
uint32 GetSpellMechanicMask (SpellEntry const * spellInfo, uint32 effectMask) inline
Definition at line 1875 of file SpellMgr.h.
References SpellEntry::EffectMechanic, MAX_EFFECT_INDEX, and SpellEntry::Mechanic.
Referenced by Unit::CalculateAuraDuration().
GetSpellMinRange()
float GetSpellMinRange (SpellRangeEntry const * range, bool friendly = false) inline
Definition at line 93 of file SpellMgr.h.
References SpellRangeEntry::minRange, and SpellRangeEntry::minRangeFriendly.
Referenced by UnitAI::AddMainSpell(), Spell::EffectTransmitted(), Spell::GetMinMaxRange(), Unit::MeetsSelectAttackingRequirement(), RandomRadiusPicker::OnRadiusCalculate(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), and Spell::SetTargetMap().
GetSpellRadius()
float GetSpellRadius (SpellRadiusEntry const * radius) inline
Definition at line 89 of file SpellMgr.h.
References SpellRadiusEntry::Radius.
Referenced by AreaAura::AreaAura(), Spell::CheckCast(), Spell::EffectPersistentAA(), Spell::EffectSummonType(), Spell::EffectTransmitted(), PlayerbotClassAI::FleeFromAoEIfCan(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), Spell::GetSpellRangeAndRadius(), Unit::HandleDummyAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::MeetsSelectAttackingRequirement(), Aura::PeriodicDummyTick(), Spell::SendChannelStart(), Spell::SetTargetMap(), and go_aura_generator_000AI::UpdateAI().
GetSpellRecoveryTime()
uint32 GetSpellRecoveryTime (SpellEntry const * spellInfo) inline
Definition at line 105 of file SpellMgr.h.
References SpellEntry::CategoryRecoveryTime, and SpellEntry::RecoveryTime.
Referenced by Spell::EffectDummy(), SpellMgr::GetSpellAllowedInLocationError(), and PetAI::UpdateAI().
GetSpellSchoolMask()
SpellSchoolMask GetSpellSchoolMask (SpellEntry const * spellInfo) inline
Definition at line 1870 of file SpellMgr.h.
References SpellEntry::SchoolMask.
Referenced by Unit::CalculateAbsorbResistBlock(), Aura::CalculateAuraEffectValue(), Unit::CalculateCritAmount(), Spell::CalculatePowerCost(), Unit::CanDeflectAbility(), Unit::CanParryAbility(), Unit::DealDamage(), Unit::DealMeleeDamage(), Spell::DoSpellHitOnUnit(), Spell::EffectDummy(), Spell::EffectEnvironmentalDMG(), Spell::EffectHeal(), Spell::EffectInterruptCast(), Spell::EffectSchoolDMG(), Spell::EffectThreat(), Spell::EffectWeaponDmg(), Aura::HandleAuraDummy(), Aura::HandleAuraModRoot(), Aura::HandleAuraModSchoolImmunity(), Aura::HandleAuraModStun(), Unit::HandleDummyAuraProc(), Aura::HandleFeignDeath(), Aura::HandleManaShield(), Aura::HandlePeriodicDamage(), Aura::HandlePeriodicHeal(), Unit::HandleProcTriggerSpellAuraProc(), Spell::HandleThreatSpells(), WorldObject::HasGCDOrCooldownWithinMargin(), Aura::IsCritFromAbilityAura(), Unit::IsImmuneToSchool(), Unit::IsImmuneToSpell(), Unit::IsImmuneToSpellEffect(), WorldObject::IsSpellReady(), Player::LockOutSpells(), PowerWordShield::OnAuraValueCalculate(), WrathOfTheTitansProcAura::OnProc(), Aura::PeriodicTick(), Player::RemoveSpellLockout(), Unit::SendPeriodicAuraLog(), Spell::Spell(), Unit::SpellDamageBonusTaken(), Unit::SpellHealingBonusDone(), Unit::SpellHealingBonusTaken(), Unit::SpellHitResult(), and HostileRefManager::threatAssist().
GetSpellSpecific()
SpellSpecific GetSpellSpecific (uint32 spellId)
Definition at line 376 of file SpellMgr.cpp.
References SpellEntry::Category, SpellEntry::Dispel, DISPEL_CURSE, DISPEL_POISON, SpellEntry::HasAttribute(), SpellEntry::Id, IsElementalShield(), SpellEntry::IsFitToFamilyMask(), IsSealSpell(), IsSpellHaveAura(), SQLStorage::LookupEntry(), SPELL_ASPECT, SPELL_ATTR_EX6_ALLOW_WHILE_RIDING_VEHICLE, SPELL_AURA, SPELL_AURA_TRACK_CREATURES, SPELL_AURA_TRACK_RESOURCES, SPELL_AURA_TRACK_STEALTHED, SPELL_BLESSING, SPELL_BUFF_CASTER_POWER, SPELL_CORRUPTION_DEBUFF, SPELL_CURSE, SPELL_ELEMENTAL_SHIELD, SPELL_HAND, SPELL_JUDGEMENT, SPELL_MAGE_ARMOR, SPELL_NORMAL, SPELL_PRESENCE, SPELL_SEAL, SPELL_SHOUT_BUFF, SPELL_STING, SPELL_TRACKER, SPELL_UA_IMMOLATE, SPELL_WARLOCK_ARMOR, SPELLFAMILY_DEATHKNIGHT, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_PALADIN, SPELLFAMILY_POTION, SPELLFAMILY_PRIEST, SPELLFAMILY_SHAMAN, SPELLFAMILY_WARLOCK, SPELLFAMILY_WARRIOR, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, sSpellMgr, and sSpellTemplate.
Referenced by PlayerbotAI::CanReceiveSpecificSpell(), SpellAuraHolder::HandleSpellSpecificBoosts(), IsStackableAuraEffect(), and Unit::RemoveNoStackAurasDueToAuraHolder().
GetWeaponAttackType()
WeaponAttackType GetWeaponAttackType (SpellEntry const * spellInfo)
Definition at line 338 of file SpellMgr.cpp.
References BASE_ATTACK, SpellEntry::DmgClass, SpellEntry::HasAttribute(), OFF_ATTACK, RANGED_ATTACK, SPELL_ATTR_EX2_AUTO_REPEAT, SPELL_ATTR_EX3_REQUIRES_OFFHAND_WEAPON, SPELL_DAMAGE_CLASS_MELEE, and SPELL_DAMAGE_CLASS_RANGED.
Referenced by Unit::CalculateAbilityDeflectChance(), Unit::CalculateSpellCritChance(), Unit::CalculateSpellMissChance(), Unit::GetCritChance(), Unit::GetHitChance(), Unit::GetMissChance(), Aura::HandlePeriodicDamage(), Spell::HandleThreatSpells(), Unit::MeleeSpellHitResult(), Aura::PeriodicTick(), Unit::RollSpellCritOutcome(), and Spell::Spell().
HasAreaAuraEffect()
bool HasAreaAuraEffect (SpellEntry const * spellInfo) inline
Definition at line 1160 of file SpellMgr.h.
References SpellEntry::Effect, and IsAreaAuraEffect().
Referenced by Spell::CheckCast(), WorldSession::HandleCancelAuraOpcode(), SpellAuraHolder::IsNeedVisibleSlot(), and Unit::RemoveArenaAuras().
HasMissingTargetFromClient()
bool HasMissingTargetFromClient (SpellEntry const * spellInfo) inline
Definition at line 1295 of file SpellMgr.h.
References EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, and IsUnitTargetTarget().
Referenced by Player::CastItemUseSpell(), WorldSession::HandleCastSpellOpcode(), and WorldSession::HandlePetCastSpellOpcode().
HasPersistentAuraEffect()
bool HasPersistentAuraEffect (SpellEntry const * spellInfo) inline
Definition at line 1173 of file SpellMgr.h.
References SpellEntry::Effect, and IsPersistentAuraEffect().
Referenced by Spell::SendSpellStart().
HasSpellTarget()
bool HasSpellTarget (SpellEntry const * spellInfo, uint32 target) inline
Definition at line 1252 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, and MAX_EFFECT_INDEX.
Referenced by PlayerAI::AddPlayerSpellAction(), and Spell::CheckRange().
IsAllowingDeadTarget()
bool IsAllowingDeadTarget (SpellEntry const * spellInfo) inline
Definition at line 320 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_EX2_ALLOW_DEAD_TARGET, SPELL_ATTR_PASSIVE, TARGET_FLAG_CORPSE_ALLY, TARGET_FLAG_CORPSE_ENEMY, TARGET_FLAG_UNIT_DEAD, and SpellEntry::Targets.
Referenced by Spell::CheckTarget(), and Spell::IsValidDeadOrAliveTarget().
IsAreaAuraEffect()
bool IsAreaAuraEffect (uint32 effect) inline
Definition at line 1155 of file SpellMgr.h.
References SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AREA_AURA_OWNER, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_PET, and SPELL_EFFECT_APPLY_AREA_AURA_RAID.
Referenced by Spell::CanAutoCast(), ChatHandler::HandleAuraCommand(), and HasAreaAuraEffect().
IsAreaEffectPositiveTarget()
bool IsAreaEffectPositiveTarget (SpellTarget target) inline
Definition at line 1098 of file SpellMgr.h.
References TARGET_ENUM_UNITS_FRIEND_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_FRIEND_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_UNIT_FRIEND_AND_PARTY, and TARGET_UNIT_RAID_AND_CLASS.
Referenced by SpellMgr::SelectAuraRankForLevel().
IsAreaEffectTarget()
bool IsAreaEffectTarget (SpellTarget target) inline
Definition at line 1117 of file SpellMgr.h.
References TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_DYNOBJ_LOC, TARGET_ENUM_UNITS_ENEMY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_104, TARGET_ENUM_UNITS_ENEMY_IN_CONE_24, TARGET_ENUM_UNITS_FRIEND_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_FRIEND_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_SCRIPT_AOE_AT_SRC_LOC, TARGET_UNIT_FRIEND_AND_PARTY, and TARGET_UNIT_RAID_AND_CLASS.
Referenced by GetSpellCastTimeForBonus(), WorldSession::HandleUseItemOpcode(), and IsAreaOfEffectSpell().
IsAreaOfEffectSpell()
bool IsAreaOfEffectSpell (SpellEntry const * spellInfo) inline
Definition at line 1144 of file SpellMgr.h.
References EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, and IsAreaEffectTarget().
Referenced by Spell::CheckCast(), Unit::GetMissChance(), Unit::MeleeDamageBonusTaken(), Unit::RemoveSpellAuraHolder(), and Unit::SpellDamageBonusTaken().
IsAuraApplyEffect()
bool IsAuraApplyEffect (SpellEntry const * spellInfo, SpellEffectIndex effecIdx) inline
Definition at line 121 of file SpellMgr.h.
References SpellEntry::Effect, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AREA_AURA_OWNER, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_PET, SPELL_EFFECT_APPLY_AREA_AURA_RAID, SPELL_EFFECT_APPLY_AURA, and SPELL_EFFECT_PERSISTENT_AREA_AURA.
Referenced by Unit::AddSpellAuraHolder(), Spell::CheckCast(), GetAuraEffectMask(), IsAuraApplyEffects(), Totem::IsImmuneToSpellEffect(), IsPositiveAuraEffect(), IsSpellAppliesAura(), IsSpellEffectTriggerSpellByAura(), and IsSpellWithNonAuraEffect().
IsAuraApplyEffects()
bool IsAuraApplyEffects (SpellEntry const * entry, SpellEffectIndexMask mask) inline
Definition at line 138 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, IsAuraApplyEffect(), and MAX_EFFECT_INDEX.
Referenced by Spell::AddUnitTarget(), Spell::CheckCast(), and Unit::IsImmuneToSpell().
IsAuraRefreshInsteadOfRecast()
bool IsAuraRefreshInsteadOfRecast (SpellEntry const * spellInfo, int32 effIdx) inline
Definition at line 282 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, SpellEntry::Id, SPELL_AURA_DUMMY, SPELL_AURA_MOD_BASE_RESISTANCE, SPELL_AURA_MOD_DAMAGE_TAKEN, SPELL_AURA_MOD_INCREASE_ENERGY, SPELL_AURA_MOD_RESISTANCE, SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_THREAT, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELL_AURA_NONE, and SPELL_AURA_PROC_TRIGGER_DAMAGE.
Referenced by IsAuraSpellRefreshInsteadOfRecast().
IsAuraRemoveOnStacking()
bool IsAuraRemoveOnStacking (SpellEntry const * spellInfo, int32 effIdx) inline
Definition at line 255 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, SPELL_AURA_MOD_INCREASE_ENERGY, SPELL_AURA_MOD_INCREASE_HEALTH, SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT, and SPELL_AURA_MOD_STAT.
Referenced by SpellAuraHolder::SetStackAmount(), and Aura::UpdateAuraScaling().
IsAuraSpellRefreshInsteadOfRecast()
bool IsAuraSpellRefreshInsteadOfRecast (SpellEntry const * spellInfo) inline
Definition at line 312 of file SpellMgr.h.
References IsAuraRefreshInsteadOfRecast().
IsAutocastable() [1/2]
bool IsAutocastable (SpellEntry const * spellInfo) inline
Definition at line 442 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_EX_NO_AUTOCAST_AI, and SPELL_ATTR_PASSIVE.
Referenced by Pet::addSpell(), CharmInfo::AddSpellToActionBar(), WorldSession::HandlePetSpellAutocastOpcode(), CharmInfo::InitCharmCreateSpells(), IsAutocastable(), CharmInfo::LoadPetActionBar(), and Pet::ToggleAutocast().
IsAutocastable() [2/2]
bool IsAutocastable (uint32 spellId) inline
Definition at line 447 of file SpellMgr.h.
References IsAutocastable(), SQLStorage::LookupEntry(), and sSpellTemplate.
IsAutoRepeatRangedSpell()
bool IsAutoRepeatRangedSpell (SpellEntry const * spellInfo) inline
Definition at line 1769 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_EX2_AUTO_REPEAT, and SPELL_ATTR_USES_RANGED_SLOT.
Referenced by PlayerbotAI::CastSpell(), and Spell::Spell().
IsBinarySpell()
bool IsBinarySpell (SpellEntry const & spellInfo, uint8 effectMask = EFFECT_MASK_ALL) inline
Definition at line 942 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectMechanic, IsSpellEffectDamage(), IsSpellEffectDummy(), IsSpellEffectTriggerSpell(), and MAX_EFFECT_INDEX.
Referenced by Unit::CalculateAbsorbResistBlock(), and Unit::CalculateSpellResistChance().
IsCastEndProcModifierAura()
bool IsCastEndProcModifierAura (SpellEntry const * spellInfo, SpellEffectIndex effecIdx, SpellEntry const * procSpell)
Definition at line 957 of file SpellMgr.cpp.
References SpellEntry::EffectApplyAuraName, SpellEntry::EffectMiscValue, IsEffectHandledImmediatelySpellLaunch(), MAX_EFFECT_INDEX, SPELL_AURA_ADD_FLAT_MODIFIER, SPELL_AURA_ADD_PCT_MODIFIER, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, SPELLMOD_CASTING_TIME, SPELLMOD_COOLDOWN, SPELLMOD_COST, SPELLMOD_GLOBAL_COOLDOWN, SPELLMOD_NOT_LOSE_CASTING_TIME, SPELLMOD_RADIUS, and SPELLMOD_RANGE.
Referenced by Aura::CanProcFrom(), and Unit::ProcDamageAndSpellFor().
IsCasterSourceTarget()
bool IsCasterSourceTarget (uint32 target) inline
Definition at line 1006 of file SpellMgr.h.
References TARGET_ENUM_GAMEOBJECTS_SCRIPT_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_ENEMY_IN_CONE_104, TARGET_ENUM_UNITS_ENEMY_IN_CONE_24, TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_LOCATION_CASTER_BACK_LEFT, TARGET_LOCATION_CASTER_BACK_RIGHT, TARGET_LOCATION_CASTER_FISHING_SPOT, TARGET_LOCATION_CASTER_FRONT_LEFT, TARGET_LOCATION_CASTER_FRONT_RIGHT, TARGET_LOCATION_RANDOM_CIRCUMFERENCE, TARGET_LOCATION_UNIT_MINION_POSITION, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_COMPANION, TARGET_UNIT_CASTER_MASTER, and TARGET_UNIT_CASTER_PET.
Referenced by IsSpellWithCasterSourceTargetsOnly(), and Unit::SpellHitResult().
IsChanneledDelayedSpell()
bool IsChanneledDelayedSpell (SpellEntry const * spellInfo) inline
Definition at line 854 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, SPELL_ATTR_EX_IS_CHANNELED, and SPELL_ATTR_EX_IS_SELF_CHANNELED.
IsChanneledSpell()
bool IsChanneledSpell (SpellEntry const * spellInfo) inline
Definition at line 1781 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_EX_IS_CHANNELED, and SPELL_ATTR_EX_IS_SELF_CHANNELED.
Referenced by Spell::_handle_immediate_phase(), Unit::AddSpellAuraHolder(), CalculateDefaultCoefficient(), Spell::cancel(), GameObject::CastSpell(), Spell::EffectPersistentAA(), SpellEvent::Execute(), Spell::GetCurrentContainer(), GetSpellCastTimeForBonus(), Spell::GetSpellSpeed(), WorldSession::HandleCancelAuraOpcode(), Spell::IsDelayedSpell(), Spell::IsNeedSendToClient(), SpellAuraHolder::IsSaveToDbHolder(), IsStackableAuraEffect(), ArcaneConcentration::OnCheckProc(), UnitAI::OnSpellCastStateChange(), Spell::Prepare(), Unit::RemoveSpellAuraHolder(), Unit::SpellHitResult(), and Spell::WriteSpellGoTargets().
IsCharmAura()
bool IsCharmAura (SpellEntry const * spellInfo, int32 effIdx) inline
Definition at line 269 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, SPELL_AURA_AOE_CHARM, SPELL_AURA_MOD_CHARM, and SPELL_AURA_MOD_POSSESS.
Referenced by SpellAuraHolder::IsCharm().
IsCheckCastTarget()
bool IsCheckCastTarget (uint32 target) inline
Definition at line 1223 of file SpellMgr.h.
References SpellTargetInfoTable, TARGET_ENUMERATOR_CHAIN, TARGET_ENUMERATOR_SINGLE, TARGET_SCRIPT, TARGET_TYPE_UNIT, TARGET_UNIT_CASTER, TARGET_UNIT_CASTER_MASTER, TARGET_UNIT_ENEMY_NEAR_CASTER, TARGET_UNIT_FRIEND_NEAR_CASTER, and TARGET_UNIT_NEAR_CASTER.
Referenced by GetCheckCastEffectMask().
IsCreatureDRSpell()
bool IsCreatureDRSpell (SpellEntry const * spellInfo)
Definition at line 3502 of file SpellMgr.cpp.
References SpellEntry::Id.
Referenced by Spell::CanSpellDiminish().
IsDeathOnlySpell()
bool IsDeathOnlySpell (SpellEntry const * spellInfo) inline
Definition at line 552 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, and SPELL_ATTR_EX3_ONLY_ON_GHOSTS.
Referenced by Unit::AddSpellAuraHolder(), Spell::CheckCast(), Spell::EffectApplyAura(), and Spell::IsValidDeadOrAliveTarget().
IsDeathPersistentSpell()
bool IsDeathPersistentSpell (SpellEntry const * spellInfo) inline
Definition at line 557 of file SpellMgr.h.
References SpellEntry::HasAttribute(), and SPELL_ATTR_EX3_ALLOW_AURA_WHILE_DEAD.
Referenced by Unit::AddSpellAuraHolder(), Spell::EffectApplyAura(), and SpellAuraHolder::SpellAuraHolder().
IsDiminishingReturnsGroupDurationDiminished()
bool IsDiminishingReturnsGroupDurationDiminished (DiminishingGroup group, bool pvp)
Definition at line 3459 of file SpellMgr.cpp.
Referenced by Unit::ApplyDiminishingToDuration(), Unit::GetDiminishing(), and Unit::IncrDiminishing().
IsDiminishingReturnsGroupDurationLimited()
bool IsDiminishingReturnsGroupDurationLimited (DiminishingGroup group)
Definition at line 3438 of file SpellMgr.cpp.
References DIMINISHING_BANISH, DIMINISHING_CHEAPSHOT_POUNCE, DIMINISHING_CONTROL_ROOT, DIMINISHING_CONTROL_STUN, DIMINISHING_CYCLONE, DIMINISHING_DISORIENT, DIMINISHING_FEAR_CHARM_BLIND, DIMINISHING_FREEZE_SLEEP, DIMINISHING_LIMITONLY, DIMINISHING_TRIGGER_ROOT, and DIMINISHING_TRIGGER_STUN.
Referenced by GetDiminishingReturnsLimitDuration().
IsDirectDamageSpell()
bool IsDirectDamageSpell (SpellEntry const * spellInfo) inline
Definition at line 1209 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SPELL_EFFECT_SCHOOL_DAMAGE, and SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL.
IsDispelSpell()
bool IsDispelSpell (SpellEntry const * spellInfo) inline
Definition at line 1759 of file SpellMgr.h.
References IsSpellHaveEffect(), and SPELL_EFFECT_DISPEL.
IsEffectHandledImmediatelySpellLaunch()
bool IsEffectHandledImmediatelySpellLaunch (SpellEntry const * spellInfo, SpellEffectIndex effecIdx) inline
Definition at line 188 of file SpellMgr.h.
References SpellEntry::Effect, SPELL_EFFECT_CHARGE, SPELL_EFFECT_CHARGE_DEST, SPELL_EFFECT_HEAL, SPELL_EFFECT_HEAL_MECHANICAL, SPELL_EFFECT_HEAL_PCT, SPELL_EFFECT_JUMP, SPELL_EFFECT_JUMP_DEST, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, and SPELL_EFFECT_WEAPON_PERCENT_DAMAGE.
Referenced by Spell::DoAllTargetlessEffects(), Spell::HandleImmediateEffectExecution(), and IsCastEndProcModifierAura().
IsEffectTargetNegative()
bool IsEffectTargetNegative (uint32 targetA, uint32 targetB) inline
Definition at line 1354 of file SpellMgr.h.
References IsHostileTarget().
Referenced by IsPositiveAuraEffect(), and IsPositiveEffectTargetMode().
IsEffectTargetNeutral()
bool IsEffectTargetNeutral (uint32 targetA, uint32 targetB) inline
Definition at line 1344 of file SpellMgr.h.
References IsNeutralTarget().
Referenced by IsPositiveEffectTargetMode().
IsEffectTargetPositive()
bool IsEffectTargetPositive (uint32 targetA, uint32 targetB) inline
Definition at line 1349 of file SpellMgr.h.
References IsFriendlyTarget().
Referenced by IsPositiveEffectTargetMode().
IsEffectTargetScript()
bool IsEffectTargetScript (uint32 targetA, uint32 targetB) inline
Definition at line 1339 of file SpellMgr.h.
References IsScriptTarget().
Referenced by IsPositiveEffectTargetMode().
IsElementalShield()
bool IsElementalShield (SpellEntry const * spellInfo) inline
Definition at line 325 of file SpellMgr.h.
References SpellEntry::Id, and SpellEntry::SpellFamilyFlags.
Referenced by GetSpellSpecific().
IsExplicitDiscoverySpell()
bool IsExplicitDiscoverySpell (SpellEntry const * spellInfo) inline
Definition at line 331 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, SpellEntry::Id, SPELL_EFFECT_CREATE_ITEM_2, SPELL_EFFECT_CREATE_RANDOM_ITEM, and SPELL_EFFECT_SCRIPT_EFFECT.
Referenced by LoadSkillDiscoveryTable().
IsExplicitNegativeTarget()
bool IsExplicitNegativeTarget (uint32 targetA)
Definition at line 513 of file SpellMgr.cpp.
References TARGET_LOCATION_CASTER_TARGET_POSITION, and TARGET_UNIT_ENEMY.
IsExplicitPositiveTarget()
bool IsExplicitPositiveTarget (uint32 targetA)
Definition at line 496 of file SpellMgr.cpp.
References TARGET_UNIT_FRIEND, TARGET_UNIT_FRIEND_CHAIN_HEAL, TARGET_UNIT_PARTY, TARGET_UNIT_RAID, and TARGET_UNIT_RAID_AND_CLASS.
Referenced by SpellMgr::SelectAuraRankForLevel().
IsFriendlyTarget()
bool IsFriendlyTarget (uint32 target) inline
Definition at line 1329 of file SpellMgr.h.
References MAX_SPELL_TARGETS, SpellTargetInfoTable, and TARGET_HELPFUL.
Referenced by IsEffectTargetPositive().
IsGroupRestrictedBuff()
bool IsGroupRestrictedBuff (SpellEntry const * spellInfo) inline
Definition at line 1954 of file SpellMgr.h.
References SpellEntry::Id.
Referenced by Unit::RemoveAllGroupBuffsFromCaster().
IsHostileTarget()
bool IsHostileTarget (uint32 target) inline
Definition at line 1334 of file SpellMgr.h.
References MAX_SPELL_TARGETS, SpellTargetInfoTable, and TARGET_HARMFUL.
Referenced by IsEffectTargetNegative().
IsIgnoreLosSpell()
bool IsIgnoreLosSpell (SpellEntry const * spellInfo) inline
Definition at line 1808 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, SPELL_ATTR_EX2_IGNORE_LINE_OF_SIGHT, and SPELL_ATTR_EX5_ALWAYS_LINE_OF_SIGHT.
Referenced by Spell::CheckRange(), IsIgnoreLosSpellCast(), and IsIgnoreLosSpellEffect().
IsIgnoreLosSpellCast()
bool IsIgnoreLosSpellCast (SpellEntry const * spellInfo) inline
Definition at line 1848 of file SpellMgr.h.
References IsIgnoreLosSpell(), and SpellEntry::rangeIndex.
Referenced by Spell::CheckCast(), and CreatureEventAI::ProcessAction().
IsIgnoreLosSpellEffect()
bool IsIgnoreLosSpellEffect (SpellEntry const * spellInfo, SpellEffectIndex effIdx) inline
Definition at line 1830 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, SpellEntry::EffectRadiusIndex, SpellEntry::HasAttribute(), IsIgnoreLosSpell(), SPELL_ATTR_EX5_ALWAYS_LINE_OF_SIGHT, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_UNIT_FRIEND_AND_PARTY, TARGET_UNIT_FRIEND_CHAIN_HEAL, and TARGET_UNIT_RAID_AND_CLASS.
Referenced by Spell::CheckCast(), and Spell::CheckTarget().
IsIgnoreRootSpell()
bool IsIgnoreRootSpell (SpellEntry const * spellInfo) inline
Definition at line 1913 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectMiscValue, SpellEntry::HasAttribute(), MAX_EFFECT_INDEX, MECHANIC_ROOT, SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, SPELL_AURA_MECHANIC_IMMUNITY, SPELL_EFFECT_APPLY_AURA, and TARGET_UNIT_CASTER.
Referenced by Spell::Spell().
IsItemAura()
bool IsItemAura (SpellEntry const * spellInfo) inline
Definition at line 1854 of file SpellMgr.h.
References SpellEntry::Id.
Referenced by SpellAuraHolder::IsSaveToDbHolder().
IsLootCraftingSpell()
bool IsLootCraftingSpell (SpellEntry const * spellInfo) inline
Definition at line 339 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectItemType, SpellEntry::Id, SPELL_EFFECT_CREATE_ITEM_2, SPELL_EFFECT_CREATE_RANDOM_ITEM, and SpellEntry::TotemCategory.
Referenced by Spell::EffectCreateItem2(), SpellMgr::IsSpellValid(), and LoadLootTemplates_Spell().
IsNeedCastSpellAtFormApply()
bool IsNeedCastSpellAtFormApply (SpellEntry const * spellInfo, ShapeshiftForm form) inline
Definition at line 1786 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_DO_NOT_DISPLAY, SPELL_ATTR_EX2_ALLOW_WHILE_NOT_SHAPESHIFTED, SPELL_ATTR_PASSIVE, and SpellEntry::Stances.
Referenced by Player::CheckAreaExploreAndOutdoor(), Aura::HandleShapeshiftBoosts(), and Player::IsNeedCastPassiveLikeSpellAtLearn().
IsNeedCastSpellAtOutdoor()
bool IsNeedCastSpellAtOutdoor (SpellEntry const * spellInfo) inline
Definition at line 1795 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_ONLY_OUTDOORS, and SPELL_ATTR_PASSIVE.
Referenced by Player::CheckAreaExploreAndOutdoor().
IsNeutralEffectTargetPositive()
bool IsNeutralEffectTargetPositive (uint32 etarget, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1359 of file SpellMgr.h.
References MAX_SPELL_TARGETS, SpellTargetInfoTable, TARGET_TYPE_UNIT, TYPEID_PLAYER, and TYPEID_UNIT.
Referenced by IsPositiveEffectTargetMode().
IsNeutralTarget()
bool IsNeutralTarget (uint32 target) inline
Definition at line 1324 of file SpellMgr.h.
References MAX_SPELL_TARGETS, SpellTargetInfoTable, and TARGET_NEUTRAL.
Referenced by IsEffectTargetNeutral().
IsNextMeleeSwingSpell()
bool IsNextMeleeSwingSpell (SpellEntry const * spellInfo) inline
Definition at line 234 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_ON_NEXT_SWING, and SPELL_ATTR_ON_NEXT_SWING_NO_DAMAGE.
Referenced by PlayerAI::AddPlayerSpellAction(), Unit::CalculateEffectiveMissChance(), UnitAI::CanCastSpell(), Spell::DoAllEffectOnTarget(), Spell::GetCurrentContainer(), Spell::GetMinMaxRange(), Spell::Prepare(), Spell::PrepareMasksForProcSystem(), Unit::ProcDamageAndSpell(), and Spell::update().
IsNonCombatSpell()
bool IsNonCombatSpell (SpellEntry const * spellInfo) inline
Definition at line 562 of file SpellMgr.h.
References SpellEntry::HasAttribute(), and SPELL_ATTR_NOT_IN_COMBAT_ONLY_PEACEFUL.
Referenced by Spell::CheckCast(), Spell::CheckPetCast(), WorldSession::HandleUseItemOpcode(), Unit::SetInCombatState(), and PetAI::UpdateAI().
IsOnlySelfTargeting()
bool IsOnlySelfTargeting (SpellEntry const * spellInfo) inline
Definition at line 1181 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, MAX_EFFECT_INDEX, TARGET_LOCATION_CURRENT_REFERENCE, TARGET_NONE, and TARGET_UNIT_CASTER.
Referenced by WorldObject::CalculateSpellEffectValue(), Spell::CheckCast(), ObjectMgr::ConvertCreatureAddonAuras(), Unit::HandleProcTriggerSpellAuraProc(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), and PetAI::UpdateAI().
IsPartyOrRaidTarget()
bool IsPartyOrRaidTarget (uint32 target) inline
Definition at line 1934 of file SpellMgr.h.
References TARGET_ENUM_UNITS_PARTY_AOE_AT_DEST_LOC, TARGET_ENUM_UNITS_PARTY_AOE_AT_SRC_LOC, TARGET_ENUM_UNITS_PARTY_WITHIN_CASTER_RANGE, TARGET_ENUM_UNITS_RAID_WITHIN_CASTER_RANGE, TARGET_UNIT_FRIEND_AND_PARTY, TARGET_UNIT_FRIEND_NEAR_CASTER, TARGET_UNIT_PARTY, TARGET_UNIT_RAID, TARGET_UNIT_RAID_AND_CLASS, and TARGET_UNIT_RAID_NEAR_CASTER.
IsPassiveSpell() [1/2]
bool IsPassiveSpell (SpellEntry const * spellInfo)
Definition at line 371 of file SpellMgr.cpp.
References SpellEntry::HasAttribute(), and SPELL_ATTR_PASSIVE.
IsPassiveSpell() [2/2]
bool IsPassiveSpell (uint32 spellId)
Definition at line 363 of file SpellMgr.cpp.
References SQLStorage::LookupEntry(), and sSpellTemplate.
Referenced by PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandSpells(), Player::ActivateSpec(), Pet::addSpell(), Unit::AddSpellAuraHolder(), Unit::CalculateDamageAbsorbAndResist(), Pet::CanTakeMoreActiveSpells(), Spell::CheckCast(), Pet::GetCharmSpells(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), WorldSession::HandleCancelAuraOpcode(), WorldSession::HandleCastSpellOpcode(), PlayerbotMgr::HandleMasterOutgoingPacket(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCastSpellOpcode(), Aura::HandleShapeshiftBoosts(), CharmInfo::InitCharmCreateSpells(), PlayerbotAI::initPetSpell(), CharmInfo::InitPossessCreateSpells(), CharmInfo::InitVehicleCreateSpells(), Player::IsActionButtonDataValid(), IsPassiveSpellStackableWithRanks(), IsSpellAffectedBySpellMods(), SpellMgr::LoadSpellLearnSpells(), Unit::ModifyAuraState(), DevourMagic::OnCheckCast(), Unit::RemoveNoStackAurasDueToAuraHolder(), Player::removeSpell(), Pet::resetTalents(), Player::resetTalents(), SpellMgr::SelectAuraRankForLevel(), Spell::SendCastResult(), ChatHandler::ShowSpellListHelper(), SpellAuraHolder::SpellAuraHolder(), and CharmInfo::ToggleCreatureAutocast().
IsPassiveSpellStackableWithRanks()
bool IsPassiveSpellStackableWithRanks (SpellEntry const * spellProto) inline
Definition at line 431 of file SpellMgr.h.
References IsPassiveSpell(), IsSpellHaveEffect(), MANGOS_ASSERT, and SPELL_EFFECT_APPLY_AURA.
Referenced by Unit::AddSpellAuraHolder(), and Unit::RemoveNoStackAurasDueToAuraHolder().
IsPeriodicRegenerateEffect()
bool IsPeriodicRegenerateEffect (SpellEntry const * spellInfo, SpellEffectIndex effecIdx) inline
Definition at line 210 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_AURA_PERIODIC_HEAL, and SPELL_AURA_PERIODIC_HEALTH_FUNNEL.
Referenced by Totem::IsImmuneToSpellEffect().
IsPersistentAuraEffect()
bool IsPersistentAuraEffect (uint32 effect) inline
Definition at line 1168 of file SpellMgr.h.
References SPELL_EFFECT_PERSISTENT_AREA_AURA.
Referenced by HasPersistentAuraEffect().
IsPointEffectTarget()
bool IsPointEffectTarget (SpellTarget target) inline
Definition at line 1072 of file SpellMgr.h.
References TARGET_LOCATION_CASTER_HOME_BIND, TARGET_LOCATION_CASTER_SRC, TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_LOCATION_CHANNEL_TARGET_DEST, TARGET_LOCATION_DATABASE, TARGET_LOCATION_EAST, TARGET_LOCATION_NE, TARGET_LOCATION_NORTH, TARGET_LOCATION_NW, TARGET_LOCATION_SCRIPT_NEAR_CASTER, TARGET_LOCATION_SE, TARGET_LOCATION_SOUTH, TARGET_LOCATION_SW, TARGET_LOCATION_UNIT_POSITION, and TARGET_LOCATION_WEST.
Referenced by WorldSession::HandleUseItemOpcode(), and IsPositiveEffectTargetMode().
IsPositiveAuraEffect()
bool IsPositiveAuraEffect (const SpellEntry * entry, SpellEffectIndex effIndex, const WorldObject * = nullptr, const WorldObject * = nullptr) inline
Definition at line 1587 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::HasAttribute(), IsAuraApplyEffect(), IsEffectTargetNegative(), SPELL_ATTR_AURA_IS_DEBUFF, SPELL_ATTR_EX4_AURA_IS_BUFF, and SPELL_EFFECT_APPLY_AREA_AURA_ENEMY.
Referenced by Aura::Aura().
IsPositiveEffect()
bool IsPositiveEffect (const SpellEntry * spellproto, SpellEffectIndex effIndex, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1423 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::Id, IsPositiveEffectTargetMode(), SPELL_AURA_CONTROL_VEHICLE, SPELL_AURA_DUMMY, SPELL_AURA_MOD_MELEE_HASTE, SPELL_AURA_PERIODIC_DAMAGE, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_CREATE_ITEM, SPELL_EFFECT_DUMMY, SPELL_EFFECT_KILL_CREDIT_GROUP, SPELL_EFFECT_KILL_CREDIT_PERSONAL, SPELL_EFFECT_PERSISTENT_AREA_AURA, SPELL_EFFECT_QUEST_COMPLETE, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_SCRIPT_EFFECT, SPELL_EFFECT_SEND_TAXI, SPELL_EFFECT_SUMMON_CHANGE_ITEM, and SPELL_EFFECT_TELEPORT_UNITS.
Referenced by Spell::CheckTarget(), DynamicObject::Create(), Unit::IsImmuneToSpellEffect(), IsPositiveEffectMask(), IsPositiveSpell(), IsSimilarAuraEffect(), IsStackableAuraEffect(), Spell::prepareDataForTriggerSystem(), and SpellMgr::SelectAuraRankForLevel().
IsPositiveEffectMask()
bool IsPositiveEffectMask (const SpellEntry * entry, uint8 effectMask, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1655 of file SpellMgr.h.
References SpellEntry::Effect, IsPositiveEffect(), and MAX_EFFECT_INDEX.
Referenced by Spell::cast(), Spell::CheckCast(), Unit::IsImmuneToSpell(), Spell::PrepareMasksForProcSystem(), and Unit::SpellHitResult().
IsPositiveEffectTargetMode()
bool IsPositiveEffectTargetMode (const SpellEntry * entry, SpellEffectIndex effIndex, const WorldObject * caster = nullptr, const WorldObject * target = nullptr, bool recursive = false) inline
Definition at line 1376 of file SpellMgr.h.
References DETAIL_LOG, SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, SpellEntry::EffectTriggerSpell, SpellEntry::HasAttribute(), SpellEntry::Id, IsEffectTargetNegative(), IsEffectTargetNeutral(), IsEffectTargetPositive(), IsEffectTargetScript(), IsNeutralEffectTargetPositive(), IsPointEffectTarget(), IsSpellEffectTriggerSpell(), SQLStorage::LookupEntry(), MAX_EFFECT_INDEX, SPELL_ATTR_PASSIVE, and sSpellTemplate.
Referenced by IsPositiveEffect(), IsPositiveSpellTargetMode(), and IsPositiveSpellTargetModeForSpecificTarget().
IsPositiveSpell() [1/2]
bool IsPositiveSpell (const SpellEntry * entry, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1642 of file SpellMgr.h.
References SpellEntry::Effect, IsPositiveEffect(), and MAX_EFFECT_INDEX.
Referenced by PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandSpells(), Player::_LoadAuras(), Unit::CalculateAuraDuration(), Unit::CalculateEffectiveCritChance(), Unit::CalculateSpellCritChance(), PlayerbotAI::CanReachWithSpellAttack(), Unit::CasterHitTargetWithSpell(), Player::CastItemCombatSpell(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), Spell::CheckCast(), Spell::CheckPetCast(), Spell::DoSpellHitOnUnit(), Spell::finish(), Aura::HandleAuraModSchoolImmunity(), Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), PlayerbotAI::initSpell(), Totem::IsImmuneToSpellEffect(), IsPositiveSpell(), IsReflectableSpell(), IsStackableAuraEffect(), DevourMagic::OnCheckCast(), Spell::SetTargetMap(), PetAI::UpdateAI(), and PlayerbotAI::UpdateAI().
IsPositiveSpell() [2/2]
bool IsPositiveSpell (uint32 spellId, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1667 of file SpellMgr.h.
References IsPositiveSpell(), SQLStorage::LookupEntry(), and sSpellTemplate.
IsPositiveSpellTargetMode() [1/2]
bool IsPositiveSpellTargetMode (const SpellEntry * entry, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1623 of file SpellMgr.h.
References SpellEntry::Effect, IsPositiveEffectTargetMode(), and MAX_EFFECT_INDEX.
Referenced by Unit::HandleProcTriggerSpellAuraProc(), and IsPositiveSpellTargetMode().
IsPositiveSpellTargetMode() [2/2]
bool IsPositiveSpellTargetMode (uint32 spellId, const WorldObject * caster, const WorldObject * target) inline
Definition at line 1635 of file SpellMgr.h.
References IsPositiveSpellTargetMode(), SQLStorage::LookupEntry(), and sSpellTemplate.
IsPositiveSpellTargetModeForSpecificTarget() [1/2]
bool IsPositiveSpellTargetModeForSpecificTarget (const SpellEntry * entry, uint8 effectMask, const WorldObject * caster = nullptr, const WorldObject * target = nullptr) inline
Definition at line 1603 of file SpellMgr.h.
References SpellEntry::Effect, IsPositiveEffectTargetMode(), and MAX_EFFECT_INDEX.
Referenced by IsPositiveSpellTargetModeForSpecificTarget().
IsPositiveSpellTargetModeForSpecificTarget() [2/2]
bool IsPositiveSpellTargetModeForSpecificTarget (uint32 spellId, uint8 effectMask, const WorldObject * caster, const WorldObject * target) inline
Definition at line 1616 of file SpellMgr.h.
References IsPositiveSpellTargetModeForSpecificTarget(), SQLStorage::LookupEntry(), and sSpellTemplate.
IsPossessCharmType()
bool IsPossessCharmType (uint32 spellId) inline
Definition at line 458 of file SpellMgr.h.
Referenced by Unit::TakeCharmOf(), and Unit::Uncharm().
IsPrimaryProfessionSkill()
bool IsPrimaryProfessionSkill (uint32 skill)
Definition at line 33 of file SpellMgr.cpp.
References SkillLineEntry::categoryId, SKILL_CATEGORY_PROFESSION, and sSkillLineStore.
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandSkill(), Player::GetTrainerSpellState(), SpellMgr::IsPrimaryProfessionSpell(), and IsProfessionSkill().
IsProfessionOrRidingSkill()
bool IsProfessionOrRidingSkill (uint32 skill) inline
Definition at line 2734 of file SpellMgr.h.
References IsProfessionSkill(), and SKILL_RIDING.
Referenced by PlayerbotAI::_HandleCommandSpells(), GetSkillRangeType(), and SpellMgr::IsProfessionOrRidingSpell().
IsProfessionSkill()
bool IsProfessionSkill (uint32 skill) inline
Definition at line 2729 of file SpellMgr.h.
References IsPrimaryProfessionSkill(), SKILL_COOKING, SKILL_FIRST_AID, and SKILL_FISHING.
Referenced by IsProfessionOrRidingSkill(), SpellMgr::IsProfessionSpell(), and Player::UpdateSpellTrainedSkills().
IsReflectableSpell()
bool IsReflectableSpell (SpellEntry const * spellInfo) inline
Definition at line 1800 of file SpellMgr.h.
References SpellEntry::DmgClass, SpellEntry::HasAttribute(), IsPositiveSpell(), SPELL_ATTR_EX_NO_REFLECTION, SPELL_ATTR_IS_ABILITY, SPELL_ATTR_NO_IMMUNITIES, SPELL_ATTR_PASSIVE, and SPELL_DAMAGE_CLASS_MAGIC.
Referenced by Unit::CalculateAbsorbResistBlock(), Aura::PeriodicTick(), and Spell::Spell().
IsResistableSpell()
bool IsResistableSpell (const SpellEntry * entry) inline
Definition at line 871 of file SpellMgr.h.
References SpellEntry::DmgClass, and SPELL_DAMAGE_CLASS_NONE.
Referenced by Unit::CalculateAbsorbResistBlock(), Unit::CalculateSpellResistChance(), and Aura::PeriodicTick().
IsScriptTarget()
bool IsScriptTarget (uint32 target) inline
Definition at line 1319 of file SpellMgr.h.
References MAX_SPELL_TARGETS, SpellTargetInfoTable, and TARGET_SCRIPT.
Referenced by IsEffectTargetScript().
IsSealSpell()
bool IsSealSpell (SpellEntry const * spellInfo) inline
Definition at line 247 of file SpellMgr.h.
References EFFECT_INDEX_0, SpellEntry::EffectImplicitTargetA, SpellEntry::IsFitToFamily(), SPELLFAMILY_PALADIN, and TARGET_UNIT_CASTER.
Referenced by SpellAuraHolder::_AddSpellAuraHolder(), SpellAuraHolder::_RemoveSpellAuraHolder(), GetSpellSpecific(), and spell_judgement::OnEffectExecute().
IsSimilarAuraEffect()
bool IsSimilarAuraEffect (SpellEntry const * entry, uint32 effect, SpellEntry const * entry2, uint32 effect2) inline
Definition at line 2057 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, and IsPositiveEffect().
Referenced by IsSimilarExistingAuraStronger(), and IsStackableAuraEffect().
IsSimilarExistingAuraStronger() [1/2]
bool IsSimilarExistingAuraStronger (const SpellAuraHolder * holder, const SpellAuraHolder * existing) inline
Definition at line 2333 of file SpellMgr.h.
References EFFECT_INDEX_0, SpellAuraHolder::GetAuraByEffectIndex(), Aura::GetModifier(), SpellAuraHolder::GetSpellProto(), Aura::GetStackAmount(), IsSimilarAuraEffect(), Modifier::m_amount, and MAX_EFFECT_INDEX.
Referenced by Spell::CheckCast(), and Unit::RemoveNoStackAurasDueToAuraHolder().
IsSimilarExistingAuraStronger() [2/2]
bool IsSimilarExistingAuraStronger (const Unit * caster, const SpellEntry * entry, const SpellAuraHolder * existing, uint32 affectedMask, int32 amounts[MAX_EFFECT_INDEX]) inline
Definition at line 2371 of file SpellMgr.h.
References EFFECT_INDEX_0, SpellAuraHolder::GetAuraByEffectIndex(), Aura::GetModifier(), SpellAuraHolder::GetSpellProto(), Aura::GetStackAmount(), IsSimilarAuraEffect(), Modifier::m_amount, and MAX_EFFECT_INDEX.
IsSpellAbleToCrit()
bool IsSpellAbleToCrit (const SpellEntry * entry) inline
Definition at line 415 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::HasAttribute(), IsSpellEffectAbleToCrit(), MAX_EFFECT_INDEX, and SPELL_ATTR_EX2_CANT_CRIT.
Referenced by Unit::CanCrit().
IsSpellAffectedBySpellMods()
bool IsSpellAffectedBySpellMods (SpellEntry const * spellInfo) inline
Definition at line 437 of file SpellMgr.h.
References SpellEntry::HasAttribute(), IsPassiveSpell(), and SPELL_ATTR_EX3_CAN_PROC_FROM_PROCS.
IsSpellAppliesAura()
bool IsSpellAppliesAura (SpellEntry const * spellInfo, uint32 effectMask = ((1 << EFFECT_INDEX_0) | (1 << EFFECT_INDEX_1) | (1 << EFFECT_INDEX_2))) inline
Definition at line 159 of file SpellMgr.h.
References IsAuraApplyEffect(), and MAX_EFFECT_INDEX.
Referenced by Creature::ApplyGameEventSpells(), ObjectMgr::ConvertCreatureAddonAuras(), Spell::DoSpellHitOnUnit(), Unit::GetCritMultiplier(), ChatHandler::HandleAuraCommand(), ChatHandler::HandleGMVisibleCommand(), and WorldSession::HandlePlayerLogin().
isSpellBreakStealth()
bool isSpellBreakStealth (SpellEntry const * spellInfo) inline
Definition at line 1764 of file SpellMgr.h.
References SpellEntry::HasAttribute(), and SPELL_ATTR_EX_ALLOW_WHILE_STEALTHED.
IsSpellDoNotReportFailure()
bool IsSpellDoNotReportFailure (SpellEntry const * spellInfo) inline
Definition at line 1674 of file SpellMgr.h.
References SpellEntry::Id.
Referenced by Spell::CheckCast().
IsSpellEffectAbleToCrit()
bool IsSpellEffectAbleToCrit (const SpellEntry * entry, SpellEffectIndex index) inline
Definition at line 395 of file SpellMgr.h.
References SpellEntry::DmgClass, SpellEntry::Effect, SpellEntry::EffectMiscValue, SpellEntry::HasAttribute(), POWER_MANA, SPELL_ATTR_EX2_CANT_CRIT, SPELL_EFFECT_ENERGIZE, SPELL_EFFECT_HEAL, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, SPELL_EFFECT_WEAPON_PERCENT_DAMAGE, and SpellEntry::SpellFamilyName.
Referenced by IsSpellAbleToCrit().
IsSpellEffectDamage()
bool IsSpellEffectDamage (SpellEntry const & spellInfo, SpellEffectIndex i) inline
Definition at line 876 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_EFFECT_ENVIRONMENTAL_DAMAGE, SPELL_EFFECT_HEALTH_LEECH, SPELL_EFFECT_NORMALIZED_WEAPON_DMG, SPELL_EFFECT_SCHOOL_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE, SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL, and SPELL_EFFECT_WEAPON_PERCENT_DAMAGE.
Referenced by IsBinarySpell(), and IsSpellEffectsDamage().
IsSpellEffectDummy()
bool IsSpellEffectDummy (SpellEntry const & spellInfo, SpellEffectIndex i) inline
Definition at line 910 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SPELL_AURA_DUMMY, SPELL_AURA_PERIODIC_DUMMY, and SPELL_EFFECT_DUMMY.
Referenced by IsBinarySpell().
IsSpellEffectsDamage()
bool IsSpellEffectsDamage (SpellEntry const & spellInfo, uint8 effectMask = EFFECT_MASK_ALL) inline
Definition at line 932 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, IsSpellEffectDamage(), and MAX_EFFECT_INDEX.
Referenced by Unit::SpellHitResult().
IsSpellEffectTriggerSpell()
bool IsSpellEffectTriggerSpell (const SpellEntry * entry, SpellEffectIndex effIndex) inline
Definition at line 347 of file SpellMgr.h.
References SpellEntry::Effect, SPELL_EFFECT_TRIGGER_MISSILE, SPELL_EFFECT_TRIGGER_SPELL, SPELL_EFFECT_TRIGGER_SPELL_2, and SPELL_EFFECT_TRIGGER_SPELL_WITH_VALUE.
Referenced by IsBinarySpell(), and IsPositiveEffectTargetMode().
IsSpellEffectTriggerSpellByAura()
bool IsSpellEffectTriggerSpellByAura (const SpellEntry * entry, SpellEffectIndex effIndex) inline
Definition at line 363 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, IsAuraApplyEffect(), SPELL_AURA_PERIODIC_TRIGGER_BY_CLIENT, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE, SPELL_AURA_PROC_TRIGGER_DAMAGE, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE, and SPELL_AURA_TRIGGER_LINKED_AURA.
Referenced by IsSpellTriggerSpellByAura().
IsSpellHaveAura()
bool IsSpellHaveAura (SpellEntry const * spellInfo, AuraType aura, uint32 effectMask = (1 << EFFECT_INDEX_0) | (1 << EFFECT_INDEX_1) | (1 << EFFECT_INDEX_2)) inline
Definition at line 225 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, and MAX_EFFECT_INDEX.
Referenced by Unit::AddSpellAuraHolder(), Spell::CheckCast(), SpellMgr::CheckUsedSpells(), Spell::CheckVehicle(), ObjectMgr::ConvertCreatureAddonAuras(), Spell::DoSummonVehicle(), GetSpellSpecific(), Aura::HandleAuraDummy(), SpellAuraHolder::IsNeedVisibleSlot(), IsSpellRemovedOnEvade(), Player::Mount(), SpellHasteHealerTrinket::OnCheckProc(), SpellAuraHolder::SpellAuraHolder(), and SpellAuraHolder::UnregisterAndCleanupTrackedAuras().
IsSpellHaveEffect()
bool IsSpellHaveEffect (SpellEntry const * spellInfo, SpellEffects effect) inline
Definition at line 113 of file SpellMgr.h.
References SpellEntry::Effect.
Referenced by Spell::_handle_finish_phase(), Player::addSpell(), Player::CastItemCombatSpell(), Spell::CheckCast(), SpellMgr::CheckUsedSpells(), ObjectMgr::ConvertCreatureAddonAuras(), ChatHandler::HandleAuraCommand(), ChatHandler::HandleLearnAllCommand(), Unit::HandleOverrideClassScriptAuraProc(), Unit::HandleProcTriggerSpellAuraProc(), IsDispelSpell(), IsPassiveSpellStackableWithRanks(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), SpellMgr::LoadSpellLearnSpells(), Unit::MeleeDamageBonusDone(), Unit::MeleeDamageBonusTaken(), Player::removeSpell(), and Spell::TakeCastItem().
IsSpellLastAuraEffect()
bool IsSpellLastAuraEffect (SpellEntry const * spellInfo, SpellEffectIndex effecIdx) inline
Definition at line 239 of file SpellMgr.h.
References SpellEntry::EffectApplyAuraName, and MAX_EFFECT_INDEX.
IsSpellNeedSendOnObjectUpdate()
bool IsSpellNeedSendOnObjectUpdate (uint32 spellId) inline
Definition at line 470 of file SpellMgr.h.
IsSpellRemoveAllMovementAndControlLossEffects()
bool IsSpellRemoveAllMovementAndControlLossEffects (SpellEntry const * spellProto) inline
Definition at line 480 of file SpellMgr.h.
References EFFECT_INDEX_0, EFFECT_INDEX_1, EFFECT_INDEX_2, SpellEntry::EffectApplyAuraName, SpellEntry::EffectMiscValue, SpellEntry::HasAttribute(), SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, and SPELL_AURA_MECHANIC_IMMUNITY.
Referenced by Aura::HandleModMechanicImmunity().
IsSpellRemovedOnEvade()
bool IsSpellRemovedOnEvade (SpellEntry const * spellInfo) inline
Definition at line 584 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SpellEntry::Id, IsSpellHaveAura(), SPELL_ATTR_EX_AURA_STAYS_AFTER_COMBAT, SPELL_ATTR_SS_IGNORE_EVADE, SPELL_AURA_CONTROL_VEHICLE, SPELL_AURA_FLY, SPELL_AURA_MIRROR_IMAGE, SPELL_AURA_MIRROR_NAME, SPELL_AURA_MOD_CHARM, and SPELL_AURA_MOD_POSSESS.
Referenced by Unit::RemoveAllAurasOnEvade().
IsSpellRequiresRangedAP()
bool IsSpellRequiresRangedAP (SpellEntry const * spellInfo) inline
Definition at line 1774 of file SpellMgr.h.
References SpellEntry::DmgClass, SPELL_DAMAGE_CLASS_MELEE, SPELLFAMILY_HUNTER, and SpellEntry::SpellFamilyName.
Referenced by Unit::SpellBonusWithCoeffs().
IsSpellRequireTarget()
bool IsSpellRequireTarget (SpellEntry const * spellInfo) inline
Definition at line 1310 of file SpellMgr.h.
References SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, IsUnitTargetTarget(), and MAX_EFFECT_INDEX.
Referenced by Spell::EffectForceCast(), Spell::EffectTriggerSpell(), WorldSession::HandlePetActionHelper(), Unit::TriggerProccedSpell(), and PetAI::UpdateAI().
IsSpellSetRun()
bool IsSpellSetRun (SpellEntry const * spellInfo) inline
Definition at line 568 of file SpellMgr.h.
References SpellEntry::Id.
Referenced by Spell::DoSummonWild().
IsSpellSpecificIdentical()
bool IsSpellSpecificIdentical (SpellSpecific specific, SpellSpecific specific2) inline
Definition at line 2024 of file SpellMgr.h.
References SPELL_BATTLE_ELIXIR, SPELL_DRINK, SPELL_FLASK_ELIXIR, SPELL_FOOD, SPELL_FOOD_AND_DRINK, and SPELL_GUARDIAN_ELIXIR.
Referenced by Unit::RemoveNoStackAurasDueToAuraHolder().
IsSpellSpecificUniquePerCaster()
bool IsSpellSpecificUniquePerCaster (SpellSpecific specific) inline
Definition at line 1974 of file SpellMgr.h.
References SPELL_ASPECT, SPELL_AURA, SPELL_BLESSING, SPELL_CORRUPTION_DEBUFF, SPELL_CURSE, SPELL_HAND, SPELL_JUDGEMENT, SPELL_SHOUT_BUFF, SPELL_STING, and SPELL_UA_IMMOLATE.
Referenced by PlayerbotAI::CanReceiveSpecificSpell(), and Unit::RemoveNoStackAurasDueToAuraHolder().
IsSpellSpecificUniquePerTarget()
bool IsSpellSpecificUniquePerTarget (SpellSpecific specific) inline
Definition at line 1998 of file SpellMgr.h.
References SPELL_BATTLE_ELIXIR, SPELL_BUFF_CASTER_POWER, SPELL_DRINK, SPELL_ELEMENTAL_SHIELD, SPELL_FLASK_ELIXIR, SPELL_FOOD, SPELL_FOOD_AND_DRINK, SPELL_GUARDIAN_ELIXIR, SPELL_MAGE_ARMOR, SPELL_PRESENCE, SPELL_SEAL, SPELL_TRACKER, SPELL_WARLOCK_ARMOR, and SPELL_WELL_FED.
Referenced by Unit::RemoveNoStackAurasDueToAuraHolder().
IsSpellTriggerSpellByAura()
bool IsSpellTriggerSpellByAura (const SpellEntry * entry) inline
Definition at line 382 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, IsSpellEffectTriggerSpellByAura(), and MAX_EFFECT_INDEX.
Referenced by SpellAuraHolder::IsNeedVisibleSlot().
IsSpellWithCasterSourceTargetsOnly()
bool IsSpellWithCasterSourceTargetsOnly (SpellEntry const * spellInfo) inline
Definition at line 1051 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, SpellEntry::EffectImplicitTargetB, IsCasterSourceTarget(), and MAX_EFFECT_INDEX.
Referenced by Spell::CheckCast(), and Unit::RemoveNoStackAurasDueToAuraHolder().
IsSpellWithNonAuraEffect()
bool IsSpellWithNonAuraEffect (SpellEntry const * spellInfo) inline
Definition at line 169 of file SpellMgr.h.
References IsAuraApplyEffect(), and MAX_EFFECT_INDEX.
Referenced by Spell::DoSpellHitOnUnit().
IsSpellWithScriptUnitTarget()
bool IsSpellWithScriptUnitTarget (SpellEntry const * spellInfo) inline
Definition at line 1035 of file SpellMgr.h.
References SpellEntry::Effect, SpellEntry::EffectImplicitTargetA, MAX_EFFECT_INDEX, and TARGET_UNIT_SCRIPT_NEAR_CASTER.
Referenced by Spell::CheckCast().
IsStackableAuraEffect()
bool IsStackableAuraEffect (SpellEntry const * entry, SpellEntry const * entry2, uint32 i, Unit * pTarget = nullptr) inline
Definition at line 2065 of file SpellMgr.h.
References SpellEntry::Dispel, SpellEntry::DmgClass, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, SpellEntry::EffectBasePoints, SpellEntry::EffectMiscValue, ClassFamilyMask::Empty(), GetSpellSpecific(), SpellEntry::HasAttribute(), SpellEntry::Id, IsChanneledSpell(), SpellEntry::IsFitToFamilyMask(), IsPositiveEffect(), IsPositiveSpell(), IsSimilarAuraEffect(), MAX_EFFECT_INDEX, SpellEntry::PreventionType, SPELL_ATTR_EX2_NOT_AN_ACTION, SPELL_ATTR_EX3_DOT_STACKING_RULE, SPELL_AURA_AOE_CHARM, SPELL_AURA_DAMAGE_SHIELD, SPELL_AURA_DUMMY, SPELL_AURA_EMPATHY, SPELL_AURA_HASTE_SPELLS, SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS, SPELL_AURA_MOD_ATTACK_POWER, SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK, SPELL_AURA_MOD_CHARM, SPELL_AURA_MOD_DAMAGE_DONE, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN, SPELL_AURA_MOD_DAMAGE_TAKEN, SPELL_AURA_MOD_DECREASE_SPEED, SPELL_AURA_MOD_DETECT_RANGE, SPELL_AURA_MOD_HEALING_DONE, SPELL_AURA_MOD_HEALING_PCT, SPELL_AURA_MOD_HEALTH_REGEN_PERCENT, SPELL_AURA_MOD_INCREASE_HEALTH, SPELL_AURA_MOD_INCREASE_SPEED, SPELL_AURA_MOD_MELEE_HASTE, SPELL_AURA_MOD_MOUNTED_SPEED_NOT_STACK, SPELL_AURA_MOD_PERCENT_STAT, SPELL_AURA_MOD_POSSESS, SPELL_AURA_MOD_POSSESS_PET, SPELL_AURA_MOD_RANGED_HASTE, SPELL_AURA_MOD_RATING, SPELL_AURA_MOD_RESISTANCE, SPELL_AURA_MOD_RESISTANCE_PCT, SPELL_AURA_MOD_SHAPESHIFT, SPELL_AURA_MOD_SPELL_CRIT_CHANCE, SPELL_AURA_MOD_SPELL_HIT_CHANCE, SPELL_AURA_MOD_STAT, SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE, SPELL_AURA_MOUNTED, SPELL_AURA_OBS_MOD_HEALTH, SPELL_AURA_OBS_MOD_MANA, SPELL_AURA_PERIODIC_DAMAGE, SPELL_AURA_PERIODIC_DAMAGE_PERCENT, SPELL_AURA_PERIODIC_DUMMY, SPELL_AURA_PERIODIC_ENERGIZE, SPELL_AURA_PERIODIC_HEAL, SPELL_AURA_PERIODIC_LEECH, SPELL_AURA_PERIODIC_MANA_LEECH, SPELL_AURA_PERIODIC_TRIGGER_SPELL, SPELL_AURA_PHASE, SPELL_AURA_POWER_BURN_MANA, SPELL_AURA_PREVENTS_FLEEING, SPELL_AURA_PROC_TRIGGER_SPELL, SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS, SPELL_AURA_SET_VEHICLE_ID, SPELL_AURA_SPELL_MAGNET, SPELL_WELL_FED, SPELLFAMILY_DRUID, SPELLFAMILY_GENERIC, SPELLFAMILY_POTION, SPELLFAMILY_SHAMAN, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, SpellEntry::SpellIconID, SpellEntry::SpellVisual, UNIT_FIELD_FLAGS, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by IsStackableSpell().
IsStackableSpell()
bool IsStackableSpell (SpellEntry const * entry, SpellEntry const * entry2, Unit * pTarget = nullptr) inline
Definition at line 2323 of file SpellMgr.h.
References SpellEntry::Effect, EFFECT_INDEX_0, SpellEntry::EffectApplyAuraName, IsStackableAuraEffect(), and MAX_EFFECT_INDEX.
Referenced by Unit::AddSpellAuraHolder(), SpellMgr::IsSpellStackableWithSpell(), and AreaAura::Update().
IsSubjectToDiminishingLevels()
bool IsSubjectToDiminishingLevels (DiminishingGroup group, bool pvp)
Definition at line 3495 of file SpellMgr.cpp.
References DRTYPE_ALL, DRTYPE_PLAYER, and GetDiminishingReturnsGroupType().
Referenced by Unit::ApplyDiminishingToDuration(), and Spell::DoSpellHitOnUnit().
IsUnitTargetTarget()
bool IsUnitTargetTarget (uint32 target) inline
Definition at line 1270 of file SpellMgr.h.
References TARGET_LOCATION_CASTER_TARGET_POSITION, TARGET_LOCATION_UNIT_BACK, TARGET_LOCATION_UNIT_BACK_LEFT, TARGET_LOCATION_UNIT_BACK_RIGHT, TARGET_LOCATION_UNIT_FRONT, TARGET_LOCATION_UNIT_FRONT_LEFT, TARGET_LOCATION_UNIT_FRONT_RIGHT, TARGET_LOCATION_UNIT_LEFT, TARGET_LOCATION_UNIT_RIGHT, TARGET_UNIT, TARGET_UNIT_ENEMY, TARGET_UNIT_FRIEND, TARGET_UNIT_FRIEND_AND_PARTY, TARGET_UNIT_FRIEND_CHAIN_HEAL, TARGET_UNIT_PARTY, and TARGET_UNIT_RAID.
Referenced by HasMissingTargetFromClient(), and IsSpellRequireTarget().
NeedsComboPoints()
bool NeedsComboPoints (SpellEntry const * spellInfo) inline
Definition at line 1865 of file SpellMgr.h.
References SpellEntry::HasAttribute(), SPELL_ATTR_EX_FINISHING_MOVE_DAMAGE, and SPELL_ATTR_EX_FINISHING_MOVE_DURATION.
Referenced by Spell::CheckCast(), and Spell::finish().
SpellCancelsAuraEffect()
bool SpellCancelsAuraEffect (SpellEntry const * spellInfo, SpellEntry const * auraSpellInfo, uint8 auraEffIndex) inline
Definition at line 509 of file SpellMgr.h.
References SpellEntry::Dispel, SpellEntry::Effect, SpellEntry::EffectApplyAuraName, SpellEntry::EffectMechanic, SpellEntry::EffectMiscValue, SpellEntry::HasAttribute(), MAX_SPELL_EFFECTS, SpellEntry::Mechanic, SpellEntry::SchoolMask, SPELL_ATTR_EX2_NO_SCHOOL_IMMUNITIES, SPELL_ATTR_EX_IMMUNITY_PURGES_EFFECT, SPELL_ATTR_NO_IMMUNITIES, SPELL_AURA_DISPEL_IMMUNITY, SPELL_AURA_MECHANIC_IMMUNITY, SPELL_AURA_SCHOOL_IMMUNITY, SPELL_AURA_STATE_IMMUNITY, and SPELL_EFFECT_APPLY_AURA.
Referenced by Spell::CheckSpellCancelsAuraEffect().