CMaNGOS_WoTLK: SpellAuras.h File Reference
SpellAuras.h File Reference
#include "Spells/SpellAuraDefines.h"
#include "Server/DBCEnums.h"
#include "Entities/ObjectGuid.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct Modifier
Used to modify what an Aura does to a player/npc.
class SpellAuraHolder
class Aura
class AreaAura
class PersistentAreaAura
class GameObjectAura
Typedefs
typedef void(Aura::* pAuraHandler) (bool Apply, bool Real)
Enumerations
enum SpellAuraHolderState { SPELLAURAHOLDER_STATE_CREATED = 0 , SPELLAURAHOLDER_STATE_READY = 1 , SPELLAURAHOLDER_STATE_REMOVING = 2 , SPELLAURAHOLDER_STATE_DB_LOAD = 3 }
Functions
Aura * CreateAura (SpellEntry const *spellproto, SpellEffectIndex eff, int32 const *currentDamage, int32 const *currentBasePoints, SpellAuraHolder *holder, Unit *target, Unit *caster=nullptr, Item *castItem=nullptr, uint64 scriptValue=0)
SpellAuraHolder * CreateSpellAuraHolder (SpellEntry const *spellproto, Unit *target, WorldObject *caster, Item *castItem=nullptr, SpellEntry const *triggeredBy=nullptr)
Typedef Documentation
pAuraHandler
typedef void(Aura::* pAuraHandler) (bool Apply, bool Real)
Definition at line 263 of file SpellAuras.h.
Enumeration Type Documentation
SpellAuraHolderState
enum SpellAuraHolderState
Enumerator
SPELLAURAHOLDER_STATE_CREATED
SPELLAURAHOLDER_STATE_READY
SPELLAURAHOLDER_STATE_REMOVING
SPELLAURAHOLDER_STATE_DB_LOAD
Definition at line 84 of file SpellAuras.h.
Function Documentation
CreateAura()
Aura* CreateAura (SpellEntry const * spellproto, SpellEffectIndex eff, int32 const * currentDamage, int32 const * currentBasePoints, SpellAuraHolder * holder, Unit * target, Unit * caster = nullptr, Item * castItem = nullptr, uint64 scriptValue = 0)
Definition at line 280 of file SpellAuras.cpp.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), Spell::EffectApplyAreaAura(), Spell::EffectApplyAura(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::RemoveAurasDueToSpellBySteal().
CreateSpellAuraHolder()
SpellAuraHolder* CreateSpellAuraHolder (SpellEntry const * spellproto, Unit * target, WorldObject * caster, Item * castItem = nullptr, SpellEntry const * triggeredBy = nullptr)
Definition at line 538 of file SpellAuras.cpp.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), go_aura_generator::CheckAndApplyAura(), Spell::DoSpellHitOnUnit(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::RemoveAurasDueToSpellBySteal(), AreaAura::Update(), go_aura_generator_000AI::UpdateAI(), and MaNGOS::DynamicObjectUpdater::VisitHelper().