CMaNGOS_WoTLK: Spell.h File Reference
Spell.h File Reference
#include "Common.h"
#include "Maps/GridDefines.h"
#include "Globals/SharedDefines.h"
#include "Server/DBCEnums.h"
#include "Entities/ObjectGuid.h"
#include "Entities/Unit.h"
#include "Entities/Player.h"
#include "Server/SQLStorages.h"
#include "Spells/SpellEffectDefines.h"
Data Structures
struct SpellCastTargetsReader
class SpellCastTargets
class SpellLog
class SpellEvent
class SpellModRAII
class SpellCastArgs
class Spell
struct Spell::CreaturePosition
struct Spell::TargetInfo
struct Spell::GOTargetInfo
struct Spell::ItemTargetInfo
struct Spell::CorpseTargetInfo
struct Spell::DestTargetInfo
struct Spell::TempTargetData
struct Spell::TempTargetingData
struct Spell::EffectSkillInfo
struct MaNGOS::SpellNotifierPlayer
struct MaNGOS::SpellNotifierCreatureAndPlayer
Namespaces
MaNGOS
class Singleton
Typedefs
typedef std::multimap< uint64, uint64 > SpellTargetTimeMap
typedef void(Spell::* pEffect) (SpellEffectIndex eff_idx)
Enumerations
enum SpellCastFlags {
CAST_FLAG_NONE = 0x00000000 , CAST_FLAG_HIDDEN_COMBATLOG = 0x00000001 , CAST_FLAG_UNKNOWN2 = 0x00000002 , CAST_FLAG_UNKNOWN3 = 0x00000004 ,
CAST_FLAG_UNKNOWN4 = 0x00000008 , CAST_FLAG_PERSISTENT_AA = 0x00000010 , CAST_FLAG_AMMO = 0x00000020 , CAST_FLAG_UNKNOWN7 = 0x00000040 ,
CAST_FLAG_UNKNOWN8 = 0x00000080 , CAST_FLAG_UNKNOWN9 = 0x00000100 , CAST_FLAG_UNKNOWN10 = 0x00000200 , CAST_FLAG_UNKNOWN11 = 0x00000400 ,
CAST_FLAG_PREDICTED_POWER = 0x00000800 , CAST_FLAG_UNKNOWN13 = 0x00001000 , CAST_FLAG_UNKNOWN14 = 0x00002000 , CAST_FLAG_UNKNOWN15 = 0x00004000 ,
CAST_FLAG_UNKNOWN16 = 0x00008000 , CAST_FLAG_UNKNOWN17 = 0x00010000 , CAST_FLAG_ADJUST_MISSILE = 0x00020000 , CAST_FLAG_NO_GCD = 0x00040000 ,
CAST_FLAG_VISUAL_CHAIN = 0x00080000 , CAST_FLAG_UNKNOWN21 = 0x00100000 , CAST_FLAG_PREDICTED_RUNES = 0x00200000 , CAST_FLAG_IMMUNITY = 0x04000000
}
enum SpellFlags { SPELL_FLAG_NORMAL = 0x00 , SPELL_FLAG_REFLECTED = 0x01 , SPELL_FLAG_REDIRECTED = 0x02 }
enum SpellNotifyPushType {
PUSH_CONE , PUSH_SELF_CENTER , PUSH_SRC_CENTER , PUSH_DEST_CENTER ,
PUSH_TARGET_CENTER
}
enum CheckException { EXCEPTION_NONE , EXCEPTION_MAGNET }
enum SpellState {
SPELL_STATE_CREATED = 0 , SPELL_STATE_TARGETING = 1 , SPELL_STATE_CASTING = 2 , SPELL_STATE_DELAYED = 3 ,
SPELL_STATE_TRAVELING = 4 , SPELL_STATE_LANDING = 5 , SPELL_STATE_CHANNELING = 6 , SPELL_STATE_FINISHED = 7
}
enum SpellTargets { SPELL_TARGETS_ASSISTABLE , SPELL_TARGETS_AOE_ATTACKABLE , SPELL_TARGETS_CHAIN_ATTACKABLE , SPELL_TARGETS_ALL }
enum ReplenishType { REPLENISH_UNDEFINED = 0 , REPLENISH_HEALTH = 20 , REPLENISH_MANA = 21 , REPLENISH_RAGE = 22 }
Functions
bool IsQuestTameSpell (uint32 spellId)
ByteBuffer & operator<< (ByteBuffer &buf, SpellCastTargets const &targets)
ByteBuffer & operator>> (ByteBuffer &buf, SpellCastTargetsReader const &targets)
Variables
static const uint32 SPELL_INTERRUPT_NONPLAYER = 32747
Typedef Documentation
pEffect
typedef void(Spell::* pEffect) (SpellEffectIndex eff_idx)
Definition at line 1314 of file Spell.h.
SpellTargetTimeMap
typedef std::multimap<uint64, uint64> SpellTargetTimeMap
Definition at line 266 of file Spell.h.
Enumeration Type Documentation
CheckException
enum CheckException
Enumerator
EXCEPTION_NONE
EXCEPTION_MAGNET
Definition at line 88 of file Spell.h.
ReplenishType
enum ReplenishType
Enumerator
REPLENISH_UNDEFINED
REPLENISH_HEALTH
REPLENISH_MANA
REPLENISH_RAGE
Definition at line 1100 of file Spell.h.
SpellCastFlags
enum SpellCastFlags
Enumerator
CAST_FLAG_NONE
CAST_FLAG_HIDDEN_COMBATLOG
CAST_FLAG_UNKNOWN2
CAST_FLAG_UNKNOWN3
CAST_FLAG_UNKNOWN4
CAST_FLAG_PERSISTENT_AA
CAST_FLAG_AMMO
CAST_FLAG_UNKNOWN7
CAST_FLAG_UNKNOWN8
CAST_FLAG_UNKNOWN9
CAST_FLAG_UNKNOWN10
CAST_FLAG_UNKNOWN11
CAST_FLAG_PREDICTED_POWER
CAST_FLAG_UNKNOWN13
CAST_FLAG_UNKNOWN14
CAST_FLAG_UNKNOWN15
CAST_FLAG_UNKNOWN16
CAST_FLAG_UNKNOWN17
CAST_FLAG_ADJUST_MISSILE
CAST_FLAG_NO_GCD
CAST_FLAG_VISUAL_CHAIN
CAST_FLAG_UNKNOWN21
CAST_FLAG_PREDICTED_RUNES
CAST_FLAG_IMMUNITY
Definition at line 44 of file Spell.h.
SpellFlags
enum SpellFlags
Enumerator
SPELL_FLAG_NORMAL
SPELL_FLAG_REFLECTED
SPELL_FLAG_REDIRECTED
Definition at line 72 of file Spell.h.
SpellNotifyPushType
enum SpellNotifyPushType
Enumerator
PUSH_CONE
PUSH_SELF_CENTER
PUSH_SRC_CENTER
PUSH_DEST_CENTER
PUSH_TARGET_CENTER
Definition at line 79 of file Spell.h.
SpellState
enum SpellState
Enumerator
SPELL_STATE_CREATED
SPELL_STATE_TARGETING
SPELL_STATE_CASTING
SPELL_STATE_DELAYED
SPELL_STATE_TRAVELING
SPELL_STATE_LANDING
SPELL_STATE_CHANNELING
SPELL_STATE_FINISHED
Definition at line 246 of file Spell.h.
SpellTargets
enum SpellTargets
Enumerator
SPELL_TARGETS_ASSISTABLE
SPELL_TARGETS_AOE_ATTACKABLE
SPELL_TARGETS_CHAIN_ATTACKABLE
SPELL_TARGETS_ALL
Definition at line 258 of file Spell.h.
Function Documentation
IsQuestTameSpell()
bool IsQuestTameSpell (uint32 spellId)
Definition at line 104 of file Spell.cpp.
References SpellEntry::Effect, EFFECT_INDEX_0, EFFECT_INDEX_1, SpellEntry::EffectApplyAuraName, SQLStorage::LookupEntry(), SPELL_AURA_DUMMY, SPELL_EFFECT_APPLY_AURA, SPELL_EFFECT_THREAT, and sSpellTemplate.
Referenced by Aura::HandleAuraDummy().
operator<<()
ByteBuffer& operator<< (ByteBuffer & buf, SpellCastTargets const & targets) inline
Definition at line 234 of file Spell.h.
References SpellCastTargets::write().
operator>>()
ByteBuffer& operator>> (ByteBuffer & buf, SpellCastTargetsReader const & targets) inline
Definition at line 240 of file Spell.h.
References SpellCastTargetsReader::caster, SpellCastTargets::read(), and SpellCastTargetsReader::targets.
Variable Documentation
SPELL_INTERRUPT_NONPLAYER
const uint32 SPELL_INTERRUPT_NONPLAYER = 32747 static
Definition at line 396 of file Spell.h.
Referenced by Spell::DoAllEffectOnTarget().