var spell__scripts_8cpp =
[
    [ "GreaterInvisibilityMob", "structGreaterInvisibilityMob.html", "structGreaterInvisibilityMob" ],
    [ "InebriateRemoval", "structInebriateRemoval.html", "structInebriateRemoval" ],
    [ "AstralBite", "structAstralBite.html", "structAstralBite" ],
    [ "FelInfusion", "structFelInfusion.html", "structFelInfusion" ],
    [ "AuchenaiPossess", "structAuchenaiPossess.html", "structAuchenaiPossess" ],
    [ "GettingSleepyAura", "structGettingSleepyAura.html", "structGettingSleepyAura" ],
    [ "AllergiesAura", "structAllergiesAura.html", "structAllergiesAura" ],
    [ "RaiseDead", "structRaiseDead.html", "structRaiseDead" ],
    [ "UseCorpse", "structUseCorpse.html", "structUseCorpse" ],
    [ "SplitDamage", "structSplitDamage.html", "structSplitDamage" ],
    [ "TKDive", "structTKDive.html", "structTKDive" ],
    [ "CurseOfPain", "structCurseOfPain.html", "structCurseOfPain" ],
    [ "spell_seed_of_corruption_npc", "structspell__seed__of__corruption__npc.html", "structspell__seed__of__corruption__npc" ],
    [ "WondervoltTrap", "structWondervoltTrap.html", "structWondervoltTrap" ],
    [ "deflection", "structdeflection.html", "structdeflection" ],
    [ "spell_eject_all_passengers", "structspell__eject__all__passengers.html", "structspell__eject__all__passengers" ],
    [ "FoodAnimation", "structFoodAnimation.html", "structFoodAnimation" ],
    [ "DrinkAnimation", "structDrinkAnimation.html", "structDrinkAnimation" ],
    [ "Drink", "structDrink.html", "structDrink" ],
    [ "spell_effect_summon_no_follow_movement", "structspell__effect__summon__no__follow__movement.html", "structspell__effect__summon__no__follow__movement" ],
    [ "SpellHasteHealerTrinket", "structSpellHasteHealerTrinket.html", "structSpellHasteHealerTrinket" ],
    [ "IncreasedHealingDoneDummy", "structIncreasedHealingDoneDummy.html", "structIncreasedHealingDoneDummy" ],
    [ "spell_scourge_strike", "structspell__scourge__strike.html", "structspell__scourge__strike" ],
    [ "TribalDeath", "structTribalDeath.html", "structTribalDeath" ],
    [ "RetaliationCreature", "structRetaliationCreature.html", "structRetaliationCreature" ],
    [ "HateToHalf", "structHateToHalf.html", "structHateToHalf" ],
    [ "HateToZero", "structHateToZero.html", "structHateToZero" ],
    [ "PreventSpellIfSameAuraOnCaster", "structPreventSpellIfSameAuraOnCaster.html", "structPreventSpellIfSameAuraOnCaster" ],
    [ "InstillLordValthalaksSpirit", "structInstillLordValthalaksSpirit.html", "structInstillLordValthalaksSpirit" ],
    [ "Stoned", "structStoned.html", "structStoned" ],
    [ "BirthNoVisualInstantSpawn", "structBirthNoVisualInstantSpawn.html", "structBirthNoVisualInstantSpawn" ],
    [ "SleepVisualFlavor", "structSleepVisualFlavor.html", "structSleepVisualFlavor" ],
    [ "CallOfTheFalcon", "structCallOfTheFalcon.html", "structCallOfTheFalcon" ],
    [ "ForgetArmorsmith", "structForgetArmorsmith.html", "structForgetArmorsmith" ],
    [ "ForgetWeaponsmith", "structForgetWeaponsmith.html", "structForgetWeaponsmith" ],
    [ "ForgetSwordsmith", "structForgetSwordsmith.html", "structForgetSwordsmith" ],
    [ "ForgetAxesmith", "structForgetAxesmith.html", "structForgetAxesmith" ],
    [ "ForgetHammersmith", "structForgetHammersmith.html", "structForgetHammersmith" ],
    [ "GameobjectCallForHelpOnUsage", "structGameobjectCallForHelpOnUsage.html", "structGameobjectCallForHelpOnUsage" ],
    [ "Submerged", "structSubmerged.html", "structSubmerged" ],
    [ "Stand", "structStand.html", "structStand" ],
    [ "SeedOfCorruptionNpc", "spell__scripts_8cpp.html#ad82d6b3035edc734a11fe1501ecc3384", [
      [ "SPELL_SEED_OF_CORRUPTION_PROC_DEFAULT", "spell__scripts_8cpp.html#ad82d6b3035edc734a11fe1501ecc3384a7a920006f7f0749a52018d770de4580d", null ],
      [ "SPELL_SEED_OF_CORRUPTION_NPC_24558", "spell__scripts_8cpp.html#ad82d6b3035edc734a11fe1501ecc3384a57455e92820ec663db0b6db8a9bd67f4", null ],
      [ "SPELL_SEED_OF_CORRUPTION_PROC_NPC_24558", "spell__scripts_8cpp.html#ad82d6b3035edc734a11fe1501ecc3384a7b413387c527f5fa01c05ca98897fc7b", null ]
    ] ],
    [ "spell_call_of_the_falcon", "spell__scripts_8cpp.html#a6fb97f8bf7a795850f8528ddb06ad421", [
      [ "YELL_KILL_FALCONER", "spell__scripts_8cpp.html#a6fb97f8bf7a795850f8528ddb06ad421a5a39b31a0df903376b7fdeccec5ed01b", null ],
      [ "NPC_BLOODWARDER_FALCONER", "spell__scripts_8cpp.html#a6fb97f8bf7a795850f8528ddb06ad421afc9087bb84b1e462296a4a50c2d2e086", null ],
      [ "NPC_BLOODFALCON", "spell__scripts_8cpp.html#a6fb97f8bf7a795850f8528ddb06ad421a1fb775b518a73e7414085dc9d6e8dd7d", null ],
      [ "SPELL_CALL_OF_THE_FALCON", "spell__scripts_8cpp.html#a6fb97f8bf7a795850f8528ddb06ad421ad3a9ff967f523c7ed7491cfa1cccdb1a", null ]
    ] ],
    [ "SpellVisualKitFoodOrDrink", "spell__scripts_8cpp.html#ab5dc2f0db632b600b7225488a8f811e0", [
      [ "SPELL_VISUAL_KIT_FOOD", "spell__scripts_8cpp.html#ab5dc2f0db632b600b7225488a8f811e0a1de54c214a2330a8d3956fcad5e765eb", null ],
      [ "SPELL_VISUAL_KIT_DRINK", "spell__scripts_8cpp.html#ab5dc2f0db632b600b7225488a8f811e0a0a4801e600ff724ee711fb48859d3199", null ]
    ] ],
    [ "AddSC_spell_scripts", "spell__scripts_8cpp.html#a43495915f350f04b806915ebfe45de1c", null ],
    [ "EffectAuraDummy_spell_aura_dummy_npc", "spell__scripts_8cpp.html#a51075024a6480b2af8a9aaf0d13a88b0", null ],
    [ "EffectDummyCreature_spell_dummy_npc", "spell__scripts_8cpp.html#a1bf9672549088384ec82cf9643079c35", null ],
    [ "EffectDummyGameObj_spell_dummy_go", "spell__scripts_8cpp.html#a2ff6b29352e6f9f74ff529b5ea544b29", null ]
];