CMaNGOS_WoTLK: spell_scripts.cpp File Reference
spell_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/SpellAuras.h"
#include "Spells/Scripts/SpellScript.h"
#include "Grids/Cell.h"
#include "Grids/CellImpl.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
#include "OutdoorPvP/OutdoorPvP.h"
Data Structures
struct GreaterInvisibilityMob
struct InebriateRemoval
struct AstralBite
struct FelInfusion
struct AuchenaiPossess
struct GettingSleepyAura
struct AllergiesAura
struct RaiseDead
struct UseCorpse
struct SplitDamage
struct TKDive
struct CurseOfPain
struct spell_seed_of_corruption_npc
struct WondervoltTrap
struct deflection
struct spell_eject_all_passengers
struct FoodAnimation
struct DrinkAnimation
struct Drink
struct spell_effect_summon_no_follow_movement
struct SpellHasteHealerTrinket
struct IncreasedHealingDoneDummy
struct spell_scourge_strike
struct TribalDeath
struct RetaliationCreature
struct HateToHalf
struct HateToZero
struct PreventSpellIfSameAuraOnCaster
struct InstillLordValthalaksSpirit
struct Stoned
struct BirthNoVisualInstantSpawn
struct SleepVisualFlavor
struct CallOfTheFalcon
struct ForgetArmorsmith
struct ForgetWeaponsmith
struct ForgetSwordsmith
struct ForgetAxesmith
struct ForgetHammersmith
struct GameobjectCallForHelpOnUsage
struct Submerged
struct Stand
Enumerations
enum {
SPELL_CAST_FISHING_NET = 29866 , GO_RED_SNAPPER = 181616 , NPC_ANGRY_MURLOC = 17102 , ITEM_RED_SNAPPER = 23614 ,
SPELL_ANUNIAQS_NET = 21014 , GO_TASTY_REEF_FISH = 186949 , NPC_REEF_SHARK = 24637 , ITEM_TASTY_REEF_FISH = 34127
}
enum {
SPELL_TAG_MURLOC = 30877 , SPELL_TAG_MURLOC_PROC = 30875 , NPC_BLACKSILT_MURLOC = 17326 , NPC_TAGGED_MURLOC = 17654 ,
SPELL_HEALING_SALVE = 29314 , SPELL_HEALING_SALVE_DUMMY = 29319 , NPC_MAGHAR_GRUNT = 16846 , SPELL_RECHARGING_BATTERY = 34219 ,
NPC_DRAINED_PHASE_HUNTER = 19595 , SPELL_ADMINISTER_ANTIDOTE = 34665 , NPC_HELBOAR = 16880 , NPC_DREADTUSK = 16992 ,
SPELL_DISCIPLINING_ROD = 56033 , SAY_RAND_WORK1 = -1000555 , SAY_RAND_WORK2 = -1000556 , SAY_RAND_WORK3 = -1000557 ,
SAY_RAND_ATTACK1 = -1000558 , SAY_RAND_ATTACK2 = -1000559 , SAY_RAND_ATTACK3 = -1000560 , SPELL_FEL_SIPHON_DUMMY = 44936 ,
NPC_FELBLOOD_INITIATE = 24918 , NPC_EMACIATED_FELBLOOD = 24955 , SPELL_INOCULATE_OWLKIN = 29528 , NPC_OWLKIN = 16518 ,
NPC_OWLKIN_INOC = 16534 , SPELL_MODIFIED_MOJO = 50706 , NPC_PROPHET_OF_SSERATUS = 28068 , NPC_WEAK_PROPHET_OF_SSERATUS = 28151 ,
SPELL_SEEDS_OF_NATURES_WRATH = 49587 , NPC_REANIMATED_FROSTWYRM = 26841 , NPC_TURGID = 27808 , NPC_DEATHGAZE = 27122 ,
NPC_WEAK_REANIMATED_FROSTWYRM = 27821 , NPC_WEAK_TURGID = 27809 , NPC_WEAK_DEATHGAZE = 27807 , SPELL_ULTRASONIC_SCREWDRIVER = 46023 ,
SPELL_REPROGRAM_KILL_CREDIT = 46027 , NPC_COLLECT_A_TRON = 25793 , SPELL_SUMMON_COLLECT_A_TRON = 46034 , NPC_DEFENDO_TANK = 25758 ,
SPELL_SUMMON_DEFENDO_TANK = 46058 , NPC_SCAVENGE_A8 = 25752 , SPELL_SUMMON_SCAVENGE_A8 = 46063 , NPC_SCAVENGE_B6 = 25792 ,
SPELL_SUMMON_SCAVENGE_B6 = 46066 , NPC_SENTRY_BOT = 25753 , SPELL_SUMMON_SENTRY_BOT = 46068 , SPELL_STRENGTH_ANCIENTS = 47575 ,
SPELL_CREATE_BARK_WALKERS = 47550 , FACTION_HOSTILE = 16 , EMOTE_AGGRO = -1000551 , EMOTE_CREATE = -1000552 ,
SAY_SPECIMEN = -1000581 , NPC_NEXUS_DRAKE_HATCHLING = 26127 , SPELL_RAELORASZ_FIREBALL = 46704 , SPELL_ORB_OF_MURLOC_CONTROL = 45109 ,
SPELL_GREENGILL_SLAVE_FREED = 45110 , SPELL_ENRAGE = 45111 , NPC_FREED_GREENGILL_SLAVE = 25085 , NPC_DARKSPINE_MYRMIDON = 25060 ,
NPC_DARKSPINE_SIREN = 25073 , SPELL_BLESSING_OF_PEACE = 66719 , NPC_FALLEN_HERO_SPIRIT = 32149 , NPC_FALLEN_HERO_SPIRIT_PROXY = 35055 ,
SAY_BLESS_1 = -1000594 , SAY_BLESS_2 = -1000595 , SAY_BLESS_3 = -1000596 , SAY_BLESS_4 = -1000597 ,
SAY_BLESS_5 = -1000598 , SPELL_DARKMENDER_TINCTURE = 52741 , SPELL_SUMMON_CORRUPTED_SCARLET = 54415 , NPC_CORPSES_RISE_CREDIT_BUNNY = 29398 ,
SPELL_AHUNAES_KNIFE = 52090 , NPC_SCALPS_KILL_CREDIT_BUNNY = 28622 , SPELL_TAILS_UP_GENDER_MASTER = 62110 , SPELL_TAILS_UP_AURA = 62109 ,
SPELL_FORCE_LEOPARD_SUMMON = 62117 , SPELL_FORCE_BEAR_SUMMON = 62118 , NPC_FROST_LEOPARD = 29327 , NPC_ICEPAW_BEAR = 29319 ,
NPC_LEOPARD_KILL_CREDIT = 33005 , NPC_BEAR_KILL_CREDIT = 33006 , SAY_ITS_FEMALE = -1000642 , SAY_ITS_MALE = -1000643 ,
SPELL_THROW_GORDAWG_BOULDER = 32001 , NPC_MINION_OF_GUROK = 18181 , SPELL_HIT_APPLE = 51331 , SPELL_MISS_APPLE = 51332 ,
SPELL_MISS_APPLE_HIT_BIRD = 51366 , SPELL_APPLE_FALLS_TO_GROUND = 51371 , NPC_APPLE = 28053 , NPC_LUCKY_WILHELM = 28054 ,
NPC_DROSTAN = 28328 , SAY_LUCKY_HIT_1 = -1000644 , SAY_LUCKY_HIT_2 = -1000645 , SAY_LUCKY_HIT_3 = -1000646 ,
SAY_LUCKY_HIT_APPLE = -1000647 , SAY_DROSTAN_GOT_LUCKY_1 = -1000648 , SAY_DROSTAN_GOT_LUCKY_2 = -1000649 , SAY_DROSTAN_HIT_BIRD_1 = -1000650 ,
SAY_DROSTAN_HIT_BIRD_2 = -1000651 , SPELL_LURIELLES_PENDANT = 43340 , NPC_CHILL_NYMPH = 23678 , NPC_LURIELLE = 24117 ,
FACTION_FRIENDLY = 35 , SAY_FREE_1 = -1000781 , SAY_FREE_2 = -1000782 , SAY_FREE_3 = -1000783 ,
SPELL_SHROUD_OF_DEATH = 10848 , SPELL_SPIRIT_PARTICLES = 17327 , NPC_FRANCLORN_FORGEWRIGHT = 8888 , NPC_GAERIYAN = 9299 ,
SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR = 37136 , NPC_ENCASED_ELECTROMENTAL = 21731 , SPELL_MELODIOUS_RAPTURE = 21050 , SPELL_MELODIOUS_RAPTURE_VISUAL = 21051 ,
NPC_DEEPRUN_RAT = 13016 , NPC_ENTHRALLED_DEEPRUN_RAT = 13017 , SPELL_THROW_ICE = 56099 , SPELL_FROZEN_IRON_SCRAP = 56101 ,
NPC_SMOLDERING_SCRAP_BUNNY = 30169 , GO_SMOLDERING_SCRAP = 192124
}
enum { SPELL_POSSESS = 32830 , SPELL_POSSESS_BUFF = 32831 , SPELL_POSSESS_INVIS = 32832 , SPELL_KNOCKDOWN = 13360 }
enum { SPELL_USE_CORPSE = 33985 }
enum SeedOfCorruptionNpc { SPELL_SEED_OF_CORRUPTION_PROC_DEFAULT = 32865 , SPELL_SEED_OF_CORRUPTION_NPC_24558 = 44141 , SPELL_SEED_OF_CORRUPTION_PROC_NPC_24558 = 43991 }
enum SpellVisualKitFoodOrDrink { SPELL_VISUAL_KIT_FOOD = 406 , SPELL_VISUAL_KIT_DRINK = 438 }
enum {
SPELL_THISTLEFUR_DEATH = 8603 , SPELL_RIVERPAW_DEATH = 8655 , SPELL_STROMGARDE_DEATH = 8894 , SPELL_CRUSHRIDGE_DEATH = 9144 ,
SAY_RAGE_FALLEN = 1151
}
enum spell_call_of_the_falcon { YELL_KILL_FALCONER = 17624 , NPC_BLOODWARDER_FALCONER = 17994 , NPC_BLOODFALCON = 18155 , SPELL_CALL_OF_THE_FALCON = 34853 }
Functions
bool EffectDummyGameObj_spell_dummy_go (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, GameObject *pGOTarget, ObjectGuid)
bool EffectAuraDummy_spell_aura_dummy_npc (const Aura *pAura, bool bApply)
bool EffectDummyCreature_spell_dummy_npc (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_spell_scripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_CAST_FISHING_NET
GO_RED_SNAPPER
NPC_ANGRY_MURLOC
ITEM_RED_SNAPPER
SPELL_ANUNIAQS_NET
GO_TASTY_REEF_FISH
NPC_REEF_SHARK
ITEM_TASTY_REEF_FISH
Definition at line 64 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_TAG_MURLOC
SPELL_TAG_MURLOC_PROC
NPC_BLACKSILT_MURLOC
NPC_TAGGED_MURLOC
SPELL_HEALING_SALVE
SPELL_HEALING_SALVE_DUMMY
NPC_MAGHAR_GRUNT
SPELL_RECHARGING_BATTERY
NPC_DRAINED_PHASE_HUNTER
SPELL_ADMINISTER_ANTIDOTE
NPC_HELBOAR
NPC_DREADTUSK
SPELL_DISCIPLINING_ROD
SAY_RAND_WORK1
SAY_RAND_WORK2
SAY_RAND_WORK3
SAY_RAND_ATTACK1
SAY_RAND_ATTACK2
SAY_RAND_ATTACK3
SPELL_FEL_SIPHON_DUMMY
NPC_FELBLOOD_INITIATE
NPC_EMACIATED_FELBLOOD
SPELL_INOCULATE_OWLKIN
NPC_OWLKIN
NPC_OWLKIN_INOC
SPELL_MODIFIED_MOJO
NPC_PROPHET_OF_SSERATUS
NPC_WEAK_PROPHET_OF_SSERATUS
SPELL_SEEDS_OF_NATURES_WRATH
NPC_REANIMATED_FROSTWYRM
NPC_TURGID
NPC_DEATHGAZE
NPC_WEAK_REANIMATED_FROSTWYRM
NPC_WEAK_TURGID
NPC_WEAK_DEATHGAZE
SPELL_ULTRASONIC_SCREWDRIVER
SPELL_REPROGRAM_KILL_CREDIT
NPC_COLLECT_A_TRON
SPELL_SUMMON_COLLECT_A_TRON
NPC_DEFENDO_TANK
SPELL_SUMMON_DEFENDO_TANK
NPC_SCAVENGE_A8
SPELL_SUMMON_SCAVENGE_A8
NPC_SCAVENGE_B6
SPELL_SUMMON_SCAVENGE_B6
NPC_SENTRY_BOT
SPELL_SUMMON_SENTRY_BOT
SPELL_STRENGTH_ANCIENTS
SPELL_CREATE_BARK_WALKERS
FACTION_HOSTILE
EMOTE_AGGRO
EMOTE_CREATE
SAY_SPECIMEN
NPC_NEXUS_DRAKE_HATCHLING
SPELL_RAELORASZ_FIREBALL
SPELL_ORB_OF_MURLOC_CONTROL
SPELL_GREENGILL_SLAVE_FREED
SPELL_ENRAGE
NPC_FREED_GREENGILL_SLAVE
NPC_DARKSPINE_MYRMIDON
NPC_DARKSPINE_SIREN
SPELL_BLESSING_OF_PEACE
NPC_FALLEN_HERO_SPIRIT
NPC_FALLEN_HERO_SPIRIT_PROXY
SAY_BLESS_1
SAY_BLESS_2
SAY_BLESS_3
SAY_BLESS_4
SAY_BLESS_5
SPELL_DARKMENDER_TINCTURE
SPELL_SUMMON_CORRUPTED_SCARLET
NPC_CORPSES_RISE_CREDIT_BUNNY
SPELL_AHUNAES_KNIFE
NPC_SCALPS_KILL_CREDIT_BUNNY
SPELL_TAILS_UP_GENDER_MASTER
SPELL_TAILS_UP_AURA
SPELL_FORCE_LEOPARD_SUMMON
SPELL_FORCE_BEAR_SUMMON
NPC_FROST_LEOPARD
NPC_ICEPAW_BEAR
NPC_LEOPARD_KILL_CREDIT
NPC_BEAR_KILL_CREDIT
SAY_ITS_FEMALE
SAY_ITS_MALE
SPELL_THROW_GORDAWG_BOULDER
NPC_MINION_OF_GUROK
SPELL_HIT_APPLE
SPELL_MISS_APPLE
SPELL_MISS_APPLE_HIT_BIRD
SPELL_APPLE_FALLS_TO_GROUND
NPC_APPLE
NPC_LUCKY_WILHELM
NPC_DROSTAN
SAY_LUCKY_HIT_1
SAY_LUCKY_HIT_2
SAY_LUCKY_HIT_3
SAY_LUCKY_HIT_APPLE
SAY_DROSTAN_GOT_LUCKY_1
SAY_DROSTAN_GOT_LUCKY_2
SAY_DROSTAN_HIT_BIRD_1
SAY_DROSTAN_HIT_BIRD_2
SPELL_LURIELLES_PENDANT
NPC_CHILL_NYMPH
NPC_LURIELLE
FACTION_FRIENDLY
SAY_FREE_1
SAY_FREE_2
SAY_FREE_3
SPELL_SHROUD_OF_DEATH
SPELL_SPIRIT_PARTICLES
NPC_FRANCLORN_FORGEWRIGHT
NPC_GAERIYAN
SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR
NPC_ENCASED_ELECTROMENTAL
SPELL_MELODIOUS_RAPTURE
SPELL_MELODIOUS_RAPTURE_VISUAL
NPC_DEEPRUN_RAT
NPC_ENTHRALLED_DEEPRUN_RAT
SPELL_THROW_ICE
SPELL_FROZEN_IRON_SCRAP
NPC_SMOLDERING_SCRAP_BUNNY
GO_SMOLDERING_SCRAP
Definition at line 135 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_POSSESS
SPELL_POSSESS_BUFF
SPELL_POSSESS_INVIS
SPELL_KNOCKDOWN
Definition at line 971 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_USE_CORPSE
Definition at line 1032 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_THISTLEFUR_DEATH
SPELL_RIVERPAW_DEATH
SPELL_STROMGARDE_DEATH
SPELL_CRUSHRIDGE_DEATH
SAY_RAGE_FALLEN
Definition at line 1351 of file spell_scripts.cpp.
SeedOfCorruptionNpc
enum SeedOfCorruptionNpc
Enumerator
SPELL_SEED_OF_CORRUPTION_PROC_DEFAULT
SPELL_SEED_OF_CORRUPTION_NPC_24558
SPELL_SEED_OF_CORRUPTION_PROC_NPC_24558
Definition at line 1103 of file spell_scripts.cpp.
spell_call_of_the_falcon
enum spell_call_of_the_falcon
Enumerator
YELL_KILL_FALCONER
NPC_BLOODWARDER_FALCONER
NPC_BLOODFALCON
SPELL_CALL_OF_THE_FALCON
Definition at line 1502 of file spell_scripts.cpp.
SpellVisualKitFoodOrDrink
enum SpellVisualKitFoodOrDrink
Enumerator
SPELL_VISUAL_KIT_FOOD
SPELL_VISUAL_KIT_DRINK
Definition at line 1209 of file spell_scripts.cpp.
Function Documentation
AddSC_spell_scripts()
void AddSC_spell_scripts ()
Definition at line 1667 of file spell_scripts.cpp.
References EffectAuraDummy_spell_aura_dummy_npc(), EffectDummyCreature_spell_dummy_npc(), EffectDummyGameObj_spell_dummy_go(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyGO, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_npc()
bool EffectAuraDummy_spell_aura_dummy_npc (const Aura * pAura, bool bApply)
Definition at line 316 of file spell_scripts.cpp.
References Creature::AI(), UnitAI::AttackStart(), AURA_STATE_HEALTHLESS_35_PERCENT, Unit::CastSpell(), DoScriptText(), EFFECT_INDEX_0, Creature::ForcedDespawn(), Aura::GetCaster(), GetClosestCreatureWithEntry(), Aura::GetEffIndex(), Object::GetEntry(), Aura::GetId(), Object::GetObjectGuid(), Unit::getStandState(), Aura::GetTarget(), Object::GetTypeId(), Unit::HasAuraState(), IN_MILLISECONDS, Unit::m_AuraFlags, NPC_BLACKSILT_MURLOC, NPC_DARKSPINE_MYRMIDON, NPC_DARKSPINE_SIREN, NPC_DRAINED_PHASE_HUNTER, NPC_ENCASED_ELECTROMENTAL, NPC_FALLEN_HERO_SPIRIT, NPC_FALLEN_HERO_SPIRIT_PROXY, NPC_FRANCLORN_FORGEWRIGHT, NPC_GAERIYAN, NPC_MAGHAR_GRUNT, NPC_NEXUS_DRAKE_HATCHLING, NPC_TAGGED_MURLOC, SAY_BLESS_1, SAY_BLESS_2, SAY_BLESS_3, SAY_BLESS_4, SAY_BLESS_5, SAY_SPECIMEN, Unit::SetStandState(), SPELL_BLESSING_OF_PEACE, SPELL_ENRAGE, SPELL_HEALING_SALVE, SPELL_HEALING_SALVE_DUMMY, SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR, SPELL_RAELORASZ_FIREBALL, SPELL_RECHARGING_BATTERY, SPELL_SHROUD_OF_DEATH, SPELL_SPIRIT_PARTICLES, SPELL_TAG_MURLOC, SPELL_TAG_MURLOC_PROC, TRIGGERED_OLD_TRIGGERED, TYPEID_UNIT, UNIT_AURAFLAG_ALIVE_INVISIBLE, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_SLEEP, UNIT_STAND_STATE_STAND, Creature::UpdateEntry(), and urand().
Referenced by AddSC_spell_scripts().
EffectDummyCreature_spell_dummy_npc()
bool EffectDummyCreature_spell_dummy_npc (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 492 of file spell_scripts.cpp.
References Creature::AI(), Creature::AIM_Initialize(), UnitAI::AttackStart(), Unit::AttackStop(), Unit::CastSpell(), Unit::DeleteThreatList(), DoScriptText(), EFFECT_INDEX_0, EMOTE_AGGRO, EMOTE_CREATE, EMOTE_STATE_WORK, FACTION_FRIENDLY, FACTION_HOSTILE, Unit::FindGuardianWithEntry(), Creature::ForcedDespawn(), frand(), GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), Object::GetEntry(), Creature::GetLootRecipient(), Unit::GetMotionMaster(), Object::GetObjectGuid(), GetSpellStore(), Unit::getStandState(), Object::GetTypeId(), GO_JUST_DEACTIVATED, GO_SMOLDERING_SCRAP, Unit::HandleEmote(), IN_MILLISECONDS, INTERACTION_DISTANCE, irand(), Creature::IsCorpse(), Player::KilledMonsterCredit(), M_PI_F, MotionMaster::MoveFleeing(), MotionMaster::MoveFollow(), NPC_BEAR_KILL_CREDIT, NPC_BLACKSILT_MURLOC, NPC_CHILL_NYMPH, NPC_COLLECT_A_TRON, NPC_CORPSES_RISE_CREDIT_BUNNY, NPC_DEATHGAZE, NPC_DEEPRUN_RAT, NPC_DEFENDO_TANK, NPC_DREADTUSK, NPC_DROSTAN, NPC_EMACIATED_FELBLOOD, NPC_ENTHRALLED_DEEPRUN_RAT, NPC_FELBLOOD_INITIATE, NPC_FREED_GREENGILL_SLAVE, NPC_FROST_LEOPARD, NPC_HELBOAR, NPC_ICEPAW_BEAR, NPC_LEOPARD_KILL_CREDIT, NPC_LUCKY_WILHELM, NPC_LURIELLE, NPC_MINION_OF_GUROK, NPC_OWLKIN, NPC_OWLKIN_INOC, NPC_PROPHET_OF_SSERATUS, NPC_REANIMATED_FROSTWYRM, NPC_SCALPS_KILL_CREDIT_BUNNY, NPC_SCAVENGE_A8, NPC_SCAVENGE_B6, NPC_SENTRY_BOT, NPC_SMOLDERING_SCRAP_BUNNY, NPC_TAGGED_MURLOC, NPC_TURGID, NPC_WEAK_DEATHGAZE, NPC_WEAK_PROPHET_OF_SSERATUS, NPC_WEAK_REANIMATED_FROSTWYRM, NPC_WEAK_TURGID, Unit::RemoveAurasDueToSpell(), SAY_DROSTAN_GOT_LUCKY_1, SAY_DROSTAN_GOT_LUCKY_2, SAY_DROSTAN_HIT_BIRD_1, SAY_DROSTAN_HIT_BIRD_2, SAY_FREE_1, SAY_FREE_2, SAY_FREE_3, SAY_ITS_FEMALE, SAY_ITS_MALE, SAY_LUCKY_HIT_1, SAY_LUCKY_HIT_2, SAY_LUCKY_HIT_3, SAY_LUCKY_HIT_APPLE, SAY_RAND_ATTACK1, SAY_RAND_ATTACK2, SAY_RAND_ATTACK3, SAY_RAND_WORK1, SAY_RAND_WORK2, SAY_RAND_WORK3, Unit::setFaction(), Creature::SetFactionTemporary(), Unit::SetStandState(), SPELL_ADMINISTER_ANTIDOTE, SPELL_AHUNAES_KNIFE, SPELL_APPLE_FALLS_TO_GROUND, SPELL_CREATE_BARK_WALKERS, SPELL_DARKMENDER_TINCTURE, SPELL_DISCIPLINING_ROD, SPELL_ENRAGE, SPELL_FEL_SIPHON_DUMMY, SPELL_FORCE_BEAR_SUMMON, SPELL_FORCE_LEOPARD_SUMMON, SPELL_FROZEN_IRON_SCRAP, SPELL_GREENGILL_SLAVE_FREED, SPELL_HIT_APPLE, SPELL_INOCULATE_OWLKIN, SPELL_LURIELLES_PENDANT, SPELL_MELODIOUS_RAPTURE, SPELL_MELODIOUS_RAPTURE_VISUAL, SPELL_MISS_APPLE, SPELL_MISS_APPLE_HIT_BIRD, SPELL_MODIFIED_MOJO, SPELL_ORB_OF_MURLOC_CONTROL, SPELL_REPROGRAM_KILL_CREDIT, SPELL_SEEDS_OF_NATURES_WRATH, SPELL_STRENGTH_ANCIENTS, SPELL_SUMMON_COLLECT_A_TRON, SPELL_SUMMON_CORRUPTED_SCARLET, SPELL_SUMMON_DEFENDO_TANK, SPELL_SUMMON_SCAVENGE_A8, SPELL_SUMMON_SCAVENGE_B6, SPELL_SUMMON_SENTRY_BOT, SPELL_TAG_MURLOC_PROC, SPELL_TAILS_UP_AURA, SPELL_TAILS_UP_GENDER_MASTER, SPELL_THROW_GORDAWG_BOULDER, SPELL_THROW_ICE, SPELL_ULTRASONIC_SCREWDRIVER, Unit::Suicide(), WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, TEMPSPAWN_CORPSE_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, UNIT_STAND_STATE_STAND, Creature::UpdateEntry(), and urand().
Referenced by AddSC_spell_scripts().
EffectDummyGameObj_spell_dummy_go()
bool EffectDummyGameObj_spell_dummy_go (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, GameObject * pGOTarget, ObjectGuid)
Definition at line 80 of file spell_scripts.cpp.
References EFFECT_INDEX_0, Object::GetEntry(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GameObject::GetRespawnTime(), Object::GetTypeId(), GO_JUST_DEACTIVATED, GO_RED_SNAPPER, GO_TASTY_REEF_FISH, ITEM_RED_SNAPPER, ITEM_TASTY_REEF_FISH, NPC_ANGRY_MURLOC, NPC_REEF_SHARK, GameObject::SetLootState(), SPELL_ANUNIAQS_NET, SPELL_CAST_FISHING_NET, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, TYPEID_PLAYER, and urand().
Referenced by AddSC_spell_scripts().