CMaNGOS_WoTLK: SQLStorages.h File Reference
SQLStorages.h File Reference
#include "Database/SQLStorage.h"
Functions
SQLStorage const * GetSpellStore ()
Variables
SQLStorage sCreatureStorage
SQLStorage sCreatureDataAddonStorage
SQLStorage sCreatureInfoAddonStorage
SQLStorage sCreatureModelStorage
SQLStorage sEquipmentStorage
SQLStorage sPageTextStore
SQLStorage sItemStorage
SQLStorage sInstanceTemplate
SQLStorage sWorldTemplate
SQLStorage sConditionStorage
SQLStorage sSpellTemplate
SQLStorage sSpellCones
SQLStorage sDungeonEncounterStore
SQLStorage sAreaGroupStore
SQLStorage sCreatureConditionalSpawnStore
SQLStorage sWorldSafeLocsStore
SQLHashStorage sGOStorage
SQLMultiStorage sVehicleAccessoryStorage
SQLMultiStorage sSpellScriptTargetStorage
Function Documentation
GetSpellStore()
SQLStorage const* GetSpellStore ()
Definition at line 71 of file SQLStorages.cpp.
References sSpellTemplate.
Referenced by npc_king_llaneAI::DoCastPrimarySpell(), npc_warchief_blackhandAI::DoCastPrimarySpell(), npc_human_conjurerAI::DoCastPrimarySpell(), npc_orc_warlockAI::DoCastPrimarySpell(), npc_human_footmanAI::DoCastPrimarySpell(), npc_orc_gruntAI::DoCastPrimarySpell(), npc_water_elementalAI::DoCastPrimarySpell(), npc_summoned_daemonAI::DoCastPrimarySpell(), npc_human_chargerAI::DoCastPrimarySpell(), npc_orc_wolfAI::DoCastPrimarySpell(), npc_human_clericAI::DoCastPrimarySpell(), npc_orc_necrolyteAI::DoCastPrimarySpell(), npc_king_llaneAI::DoCastSecondarySpell(), npc_warchief_blackhandAI::DoCastSecondarySpell(), npc_human_conjurerAI::DoCastSecondarySpell(), npc_orc_warlockAI::DoCastSecondarySpell(), npc_human_footmanAI::DoCastSecondarySpell(), npc_orc_gruntAI::DoCastSecondarySpell(), npc_water_elementalAI::DoCastSecondarySpell(), npc_summoned_daemonAI::DoCastSecondarySpell(), npc_human_chargerAI::DoCastSecondarySpell(), npc_orc_wolfAI::DoCastSecondarySpell(), npc_human_clericAI::DoCastSecondarySpell(), npc_orc_necrolyteAI::DoCastSecondarySpell(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_spell_eat_ooze(), EffectScriptEffectCreature_spell_ooze_flood(), EquippedOk(), FillSpellSummary(), ItemUse_item_arcane_charges(), ItemUse_item_gor_dreks_ointment(), ItemUse_item_orb_of_draconic_energy(), ItemUse_item_petrov_cluster_bombs(), ScriptedAI::SelectSpell(), npc_kyle_the_frenziedAI::UpdateAI(), and npc_dragonmaw_peonAI::UpdateAI().
Variable Documentation
sAreaGroupStore
SQLStorage sAreaGroupStore extern
sConditionStorage
SQLStorage sConditionStorage extern
sCreatureConditionalSpawnStore
SQLStorage sCreatureConditionalSpawnStore extern
sCreatureDataAddonStorage
SQLStorage sCreatureDataAddonStorage extern
sCreatureInfoAddonStorage
SQLStorage sCreatureInfoAddonStorage extern
sCreatureModelStorage
SQLStorage sCreatureModelStorage extern
sCreatureStorage
SQLStorage sCreatureStorage extern
sDungeonEncounterStore
SQLStorage sDungeonEncounterStore extern
sEquipmentStorage
SQLStorage sEquipmentStorage extern
sGOStorage
SQLHashStorage sGOStorage extern
sInstanceTemplate
SQLStorage sInstanceTemplate extern
sItemStorage
SQLStorage sItemStorage extern
sPageTextStore
SQLStorage sPageTextStore extern
sSpellCones
SQLStorage sSpellCones extern
sSpellScriptTargetStorage
SQLMultiStorage sSpellScriptTargetStorage extern
sSpellTemplate
SQLStorage sSpellTemplate extern
sVehicleAccessoryStorage
SQLMultiStorage sVehicleAccessoryStorage extern
sWorldSafeLocsStore
SQLStorage sWorldSafeLocsStore extern
sWorldTemplate
SQLStorage sWorldTemplate extern