CMaNGOS_WoTLK: SQLStorages.cpp File Reference
SQLStorages.cpp File Reference
#include "Server/SQLStorages.h"
Functions
SQLStorage const * GetSpellStore ()
Variables
const char CreatureInfosrcfmt [] = "isssiiiiiiiiiifiiiiliiiiiiiiiifffiiiiiiiiffffffiiiiffffiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiss"
const char CreatureInfodstfmt [] = "isssiiiiiiiiiifiiiiliiiiiiiiiifffiiiiiiiiffffffiiiiffffiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisi"
const char CreatureDataAddonInfofmt [] = "iibbbiis"
const char CreatureConditionalSpawnSrcFmt [] = "iiix"
const char CreatureConditionalSpawnDstFmt [] = "iii"
const char CreatureModelfmt [] = "iffffbii"
const char CreatureInfoAddonInfofmt [] = "iibbbiis"
const char EquipmentInfofmt [] = "iiii"
const char GameObjectInfosrcfmt [] = "iiissssiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiis"
const char GameObjectInfodstfmt [] = "iiissssiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"
const char ItemPrototypesrcfmt [] = "iiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiffiffiiiiiiiiiifiiifiiiiiifiiiiiifiiiiiifiiiiiifiiiisiiiiiiiiiiiiiiiiiiiiiiiiifiiisiiiii"
const char ItemPrototypedstfmt [] = "iiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiffiffiiiiiiiiiifiiifiiiiiifiiiiiifiiiiiifiiiiiifiiiisiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiii"
const char PageTextfmt [] = "isi"
const char InstanceTemplatesrcfmt [] = "iiiisl"
const char InstanceTemplatedstfmt [] = "iiiiil"
const char WorldTemplatesrcfmt [] = "is"
const char WorldTemplatedstfmt [] = "ii"
const char ConditionsFmt [] = "iiiiiiix"
const char SpellTemplatefmt [] = "iiiiiiiiiiiiiiiix"
const char VehicleAccessorySrcFmt [] = "iiix"
const char VehicleAccessoryDstFmt [] = "iii"
const char SpellScriptTargetFmt [] = "iiii"
const char SpellEntryfmt [] = "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssssssssssssssssssiiiiiLiiiiifffiiiiiiiiiifffiiii"
const char SpellConefmt [] = "ii"
const char DungeonEncounterFmt [] = "iiiiiissssssssssssssssii"
const char AreaGroupEntryFmt [] = "iiiiiiii"
const char WorldSafeLocsFmt [] = "iiffffs"
SQLStorage sCreatureStorage (CreatureInfosrcfmt, CreatureInfodstfmt, "entry", "creature_template")
SQLStorage sCreatureDataAddonStorage (CreatureDataAddonInfofmt, "guid", "creature_addon")
SQLStorage sCreatureModelStorage (CreatureModelfmt, "modelid", "creature_model_info")
SQLStorage sCreatureInfoAddonStorage (CreatureInfoAddonInfofmt, "entry", "creature_template_addon")
SQLStorage sEquipmentStorage (EquipmentInfofmt, "entry", "creature_equip_template")
SQLStorage sItemStorage (ItemPrototypesrcfmt, ItemPrototypedstfmt, "entry", "item_template")
SQLStorage sPageTextStore (PageTextfmt, "entry", "page_text")
SQLStorage sInstanceTemplate (InstanceTemplatesrcfmt, InstanceTemplatedstfmt, "map", "instance_template")
SQLStorage sWorldTemplate (WorldTemplatesrcfmt, WorldTemplatedstfmt, "map", "world_template")
SQLStorage sConditionStorage (ConditionsFmt, "condition_entry", "conditions")
SQLStorage sSpellTemplate (SpellEntryfmt, "id", "spell_template")
SQLStorage sSpellCones (SpellConefmt, "id", "spell_cone")
SQLStorage sDungeonEncounterStore (DungeonEncounterFmt, "id", "instance_dungeon_encounters")
SQLStorage sAreaGroupStore (AreaGroupEntryFmt, "id", "area_group_template")
SQLStorage sCreatureConditionalSpawnStore (CreatureConditionalSpawnSrcFmt, CreatureConditionalSpawnDstFmt, "guid", "creature_conditional_spawn")
SQLStorage sWorldSafeLocsStore (WorldSafeLocsFmt, "id", "world_safe_locs")
SQLHashStorage sGOStorage (GameObjectInfosrcfmt, GameObjectInfodstfmt, "entry", "gameobject_template")
SQLMultiStorage sVehicleAccessoryStorage (VehicleAccessorySrcFmt, VehicleAccessoryDstFmt, "vehicle_entry", "vehicle_accessory")
SQLMultiStorage sSpellScriptTargetStorage (SpellScriptTargetFmt, "entry", "spell_script_target")
Function Documentation
GetSpellStore()
SQLStorage const* GetSpellStore ()
Definition at line 71 of file SQLStorages.cpp.
References sSpellTemplate.
Referenced by npc_king_llaneAI::DoCastPrimarySpell(), npc_warchief_blackhandAI::DoCastPrimarySpell(), npc_human_conjurerAI::DoCastPrimarySpell(), npc_orc_warlockAI::DoCastPrimarySpell(), npc_human_footmanAI::DoCastPrimarySpell(), npc_orc_gruntAI::DoCastPrimarySpell(), npc_water_elementalAI::DoCastPrimarySpell(), npc_summoned_daemonAI::DoCastPrimarySpell(), npc_human_chargerAI::DoCastPrimarySpell(), npc_orc_wolfAI::DoCastPrimarySpell(), npc_human_clericAI::DoCastPrimarySpell(), npc_orc_necrolyteAI::DoCastPrimarySpell(), npc_king_llaneAI::DoCastSecondarySpell(), npc_warchief_blackhandAI::DoCastSecondarySpell(), npc_human_conjurerAI::DoCastSecondarySpell(), npc_orc_warlockAI::DoCastSecondarySpell(), npc_human_footmanAI::DoCastSecondarySpell(), npc_orc_gruntAI::DoCastSecondarySpell(), npc_water_elementalAI::DoCastSecondarySpell(), npc_summoned_daemonAI::DoCastSecondarySpell(), npc_human_chargerAI::DoCastSecondarySpell(), npc_orc_wolfAI::DoCastSecondarySpell(), npc_human_clericAI::DoCastSecondarySpell(), npc_orc_necrolyteAI::DoCastSecondarySpell(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), EffectScriptEffectCreature_npc_putricide(), EffectScriptEffectCreature_spell_eat_ooze(), EffectScriptEffectCreature_spell_ooze_flood(), EquippedOk(), FillSpellSummary(), ItemUse_item_arcane_charges(), ItemUse_item_gor_dreks_ointment(), ItemUse_item_orb_of_draconic_energy(), ItemUse_item_petrov_cluster_bombs(), ScriptedAI::SelectSpell(), npc_kyle_the_frenziedAI::UpdateAI(), and npc_dragonmaw_peonAI::UpdateAI().
Variable Documentation
AreaGroupEntryFmt
const char AreaGroupEntryFmt[] = "iiiiiiii"
Definition at line 46 of file SQLStorages.cpp.
ConditionsFmt
const char ConditionsFmt[] = "iiiiiiix"
Definition at line 38 of file SQLStorages.cpp.
CreatureConditionalSpawnDstFmt
const char CreatureConditionalSpawnDstFmt[] = "iii"
Definition at line 25 of file SQLStorages.cpp.
CreatureConditionalSpawnSrcFmt
const char CreatureConditionalSpawnSrcFmt[] = "iiix"
Definition at line 24 of file SQLStorages.cpp.
CreatureDataAddonInfofmt
const char CreatureDataAddonInfofmt[] = "iibbbiis"
Definition at line 23 of file SQLStorages.cpp.
CreatureInfoAddonInfofmt
const char CreatureInfoAddonInfofmt[] = "iibbbiis"
Definition at line 27 of file SQLStorages.cpp.
CreatureInfodstfmt
const char CreatureInfodstfmt[] = "isssiiiiiiiiiifiiiiliiiiiiiiiifffiiiiiiiiffffffiiiiffffiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiisi"
Definition at line 22 of file SQLStorages.cpp.
CreatureInfosrcfmt
const char CreatureInfosrcfmt[] = "isssiiiiiiiiiifiiiiliiiiiiiiiifffiiiiiiiiffffffiiiiffffiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiss"
Definition at line 21 of file SQLStorages.cpp.
CreatureModelfmt
const char CreatureModelfmt[] = "iffffbii"
Definition at line 26 of file SQLStorages.cpp.
DungeonEncounterFmt
const char DungeonEncounterFmt[] = "iiiiiissssssssssssssssii"
Definition at line 45 of file SQLStorages.cpp.
EquipmentInfofmt
const char EquipmentInfofmt[] = "iiii"
Definition at line 28 of file SQLStorages.cpp.
GameObjectInfodstfmt
const char GameObjectInfodstfmt[] = "iiissssiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii"
Definition at line 30 of file SQLStorages.cpp.
GameObjectInfosrcfmt
const char GameObjectInfosrcfmt[] = "iiissssiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiis"
Definition at line 29 of file SQLStorages.cpp.
InstanceTemplatedstfmt
const char InstanceTemplatedstfmt[] = "iiiiil"
Definition at line 35 of file SQLStorages.cpp.
InstanceTemplatesrcfmt
const char InstanceTemplatesrcfmt[] = "iiiisl"
Definition at line 34 of file SQLStorages.cpp.
ItemPrototypedstfmt
const char ItemPrototypedstfmt[] = "iiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiffiffiiiiiiiiiifiiifiiiiiifiiiiiifiiiiiifiiiiiifiiiisiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiii"
Definition at line 32 of file SQLStorages.cpp.
ItemPrototypesrcfmt
const char ItemPrototypesrcfmt[] = "iiiisiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiffiffiiiiiiiiiifiiifiiiiiifiiiiiifiiiiiifiiiiiifiiiisiiiiiiiiiiiiiiiiiiiiiiiiifiiisiiiii"
Definition at line 31 of file SQLStorages.cpp.
PageTextfmt
const char PageTextfmt[] = "isi"
Definition at line 33 of file SQLStorages.cpp.
sAreaGroupStore
SQLStorage sAreaGroupStore(AreaGroupEntryFmt, "id", "area_group_template") (AreaGroupEntryFmt , "id" , "area_group_template")
Referenced by SpellMgr::GetSpellAllowedInLocationError(), and ObjectMgr::LoadAreaGroups().
sConditionStorage
SQLStorage sConditionStorage(ConditionsFmt, "condition_entry", "conditions") (ConditionsFmt , "condition_entry" , "conditions")
Referenced by ConditionEntry::CanBeUsedWithoutPlayer(), ConditionEntry::Evaluate(), IsConditionSatisfied(), ObjectMgr::IsConditionSatisfied(), ConditionEntry::IsValid(), AchievementCriteriaRequirement::IsValid(), ObjectMgr::IsVendorItemValid(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadConditions(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), LootStore::LoadLootTable(), ObjectMgr::LoadNPCSpellClickSpells(), ScriptMgr::LoadScripts(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellAreas(), and ObjectMgr::LoadTrainers().
sCreatureConditionalSpawnStore
SQLStorage sCreatureConditionalSpawnStore(CreatureConditionalSpawnSrcFmt, CreatureConditionalSpawnDstFmt, "guid", "creature_conditional_spawn") (CreatureConditionalSpawnSrcFmt , CreatureConditionalSpawnDstFmt , "guid" , "creature_conditional_spawn")
Referenced by ObjectMgr::GetCreatureConditionalSpawn(), and ObjectMgr::LoadCreatureConditionalSpawn().
sCreatureDataAddonStorage
SQLStorage sCreatureDataAddonStorage(CreatureDataAddonInfofmt, "guid", "creature_addon") (CreatureDataAddonInfofmt , "guid" , "creature_addon")
Referenced by ObjectMgr::GetCreatureAddon(), and ObjectMgr::LoadCreatureAddons().
sCreatureInfoAddonStorage
SQLStorage sCreatureInfoAddonStorage(CreatureInfoAddonInfofmt, "entry", "creature_template_addon") (CreatureInfoAddonInfofmt , "entry" , "creature_template_addon")
Referenced by ObjectMgr::GetCreatureTemplateAddon(), and ObjectMgr::LoadCreatureAddons().
sCreatureModelStorage
SQLStorage sCreatureModelStorage(CreatureModelfmt, "modelid", "creature_model_info") (CreatureModelfmt , "modelid" , "creature_model_info")
Referenced by ObjectMgr::GetCreatureModelInfo(), ObjectMgr::LoadCreatureModelInfo(), and ObjectMgr::LoadCreatureModelRace().
sCreatureStorage
SQLStorage sCreatureStorage(CreatureInfosrcfmt, CreatureInfodstfmt, "entry", "creature_template") (CreatureInfosrcfmt , CreatureInfodstfmt , "entry" , "creature_template")
Referenced by Player::BuildEnumData(), ObjectMgr::GetCreatureTemplate(), GetCreatureTemplateStore(), ChatHandler::HandleLookupCreatureCommand(), ConditionEntry::IsValid(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureModelRace(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemRequiredTarget(), LoadLootTemplates_Creature(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Skinning(), SpellMgr::LoadPetDefaultSpells(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuests(), ScriptMgr::LoadScripts(), SpellMgr::LoadSpellScriptTarget(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), ObjectMgr::LoadTrainerTemplates(), ObjectMgr::LoadVehicleAccessory(), and ObjectMgr::LoadVendorTemplates().
sDungeonEncounterStore
SQLStorage sDungeonEncounterStore(DungeonEncounterFmt, "id", "instance_dungeon_encounters") (DungeonEncounterFmt , "id" , "instance_dungeon_encounters")
Referenced by ConditionEntry::Evaluate(), ConditionEntry::IsValid(), ObjectMgr::LoadDungeonEncounters(), and ObjectMgr::LoadInstanceEncounters().
sEquipmentStorage
SQLStorage sEquipmentStorage(EquipmentInfofmt, "entry", "creature_equip_template") (EquipmentInfofmt , "entry" , "creature_equip_template")
Referenced by ObjectMgr::GetEquipmentInfo(), and ObjectMgr::LoadEquipmentTemplates().
sGOStorage
SQLHashStorage sGOStorage(GameObjectInfosrcfmt, GameObjectInfodstfmt, "entry", "gameobject_template") (GameObjectInfosrcfmt , GameObjectInfodstfmt , "entry" , "gameobject_template")
Referenced by CheckGOLinkedTrapId(), ScriptMgr::CollectPossibleEventIds(), PlayerbotClassAI::FleeFromTrapGOIfCan(), ObjectMgr::GetGameObjectInfo(), ChatHandler::HandleLookupObjectCommand(), Player::LoadFromDB(), ObjectMgr::LoadGameObjectForQuests(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), LoadLootTemplates_Gameobject(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuests(), SpellMgr::LoadSpellScriptTarget(), TransportMgr::LoadTransportTemplates(), and GameObject::TriggerLinkedGameObject().
sInstanceTemplate
SQLStorage sInstanceTemplate(InstanceTemplatesrcfmt, InstanceTemplatedstfmt, "map", "instance_template") (InstanceTemplatesrcfmt , InstanceTemplatedstfmt , "map" , "instance_template")
Referenced by ObjectMgr::GetInstanceTemplate(), and ObjectMgr::LoadInstanceTemplate().
sItemStorage
SQLStorage sItemStorage(ItemPrototypesrcfmt, ItemPrototypedstfmt, "entry", "item_template") (ItemPrototypesrcfmt , ItemPrototypedstfmt , "entry" , "item_template")
Referenced by LootMgr::CheckDropStats(), Player::EnchantmentFitsRequirements(), Item::GemsFitSockets(), Item::GenerateItemRandomPropertyId(), ObjectMgr::GetItemPrototype(), ChatHandler::HandleAddItemSetCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleQuestAddCommand(), ObjectMgr::LoadItemConverts(), ObjectMgr::LoadItemExpireConverts(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadItemRequiredTarget(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Item(), LoadLootTemplates_Milling(), LoadLootTemplates_Prospecting(), ObjectMgr::LoadQuests(), Loot::PrintLootList(), and ChatHandler::ShowItemListHelper().
sPageTextStore
SQLStorage sPageTextStore(PageTextfmt, "entry", "page_text") (PageTextfmt , "entry" , "page_text")
Referenced by WorldSession::HandlePageTextQueryOpcode(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadPageTextLocales(), and ObjectMgr::LoadPageTexts().
SpellConefmt
const char SpellConefmt[] = "ii"
Definition at line 44 of file SQLStorages.cpp.
SpellEntryfmt
const char SpellEntryfmt[] = "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiifiiiiiiiiiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiiiiiiiifffiiiiiiiiiiiiiiifffiiiiiiiiiiiiiissssssssssssssssssssssssssssssssiiiiiLiiiiifffiiiiiiiiiifffiiii"
Definition at line 43 of file SQLStorages.cpp.
SpellScriptTargetFmt
const char SpellScriptTargetFmt[] = "iiii"
Definition at line 42 of file SQLStorages.cpp.
SpellTemplatefmt
const char SpellTemplatefmt[] = "iiiiiiiiiiiiiiiix"
Definition at line 39 of file SQLStorages.cpp.
sSpellCones
SQLStorage sSpellCones(SpellConefmt, "id", "spell_cone") (SpellConefmt , "id" , "spell_cone")
Referenced by ObjectMgr::CheckSpellCones(), Spell::GetCone(), and ObjectMgr::LoadSpellTemplate().
sSpellScriptTargetStorage
SQLMultiStorage sSpellScriptTargetStorage(SpellScriptTargetFmt, "entry", "spell_script_target") (SpellScriptTargetFmt , "entry" , "spell_script_target")
Referenced by Spell::CheckScriptTargeting(), SpellTargetMgr::Initialize(), ObjectMgr::LoadItemRequiredTarget(), SpellMgr::LoadSpellScriptTarget(), Spell::SetTargetMap(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
sSpellTemplate
SQLStorage sSpellTemplate(SpellEntryfmt, "id", "spell_template") (SpellEntryfmt , "id" , "spell_template")
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandProcess(), PlayerbotAI::_HandleCommandSkill(), PlayerbotAI::_HandleCommandSpells(), Player::_HandleDeadlyPoison(), Player::_LoadAuras(), Pet::_LoadAuras(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Unit::AddGameObject(), UnitAI::AddInitialCooldowns(), AddItemsSetItem(), UnitAI::AddMainSpell(), PlayerAI::AddPlayerSpellAction(), Spell::AddPrecastSpell(), Pet::addSpell(), Player::addSpell(), Spell::AddTriggeredSpell(), Player::ApplyEquipCooldown(), Creature::ApplyGameEventSpells(), Player::ApplyItemEquipSpell(), Player::ApplySpellMod(), AreaTrigger_at_area_52(), Aura::Aura(), boss_selin_fireheartAI::boss_selin_fireheartAI(), PlayerbotAI::Buff(), WorldSession::BuildListAuctionItems(), Unit::CalculateDamageAbsorbAndResist(), PlayerbotAI::CanReachWithSpellAttack(), Unit::CastCustomSpell(), CastHighestStealthRank(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), GameObject::CastSpell(), Unit::CastSpell(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), ChatHandler::CheckEscapeSequences(), CheckGOSpellId(), ObjectMgr::CheckSpellCones(), SpellMgr::CheckUsedSpells(), UnitAI::ChooseTarget(), SpellAuraHolder::CleanupTriggeredSpells(), ScriptMgr::CollectPossibleEventIds(), ObjectMgr::ConvertCreatureAddonAuras(), DynamicObject::Create(), GameObject::DealGameObjectDamage(), Unit::DealSpellDamage(), UnitAI::DoCastSpellIfCan(), UnitAI::DoFindFriendlyEligibleDispel(), UnitAI::DoFindFriendlyMissingBuff(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), Spell::DoSummonVehicle(), Spell::EffectCancelAura(), Spell::EffectDestroyAllTotems(), Spell::EffectDummy(), Spell::EffectEnchantItemTmp(), Spell::EffectEnergize(), Spell::EffectForceCast(), Spell::EffectLearnPetSpell(), Spell::EffectScriptEffect(), Spell::EffectSummonRafFriend(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerRitualOfSummoning(), Spell::EffectTriggerSpell(), Spell::EffectTriggerSpellWithValue(), Player::EquipItem(), boss_curatorAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), PlayerbotAI::FindMount(), PlayerbotClassAI::FleeFromAoEIfCan(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), Player::GetKnownTalentRankById(), PlayerbotAI::getPetSpellId(), GetSpellAuraMaxTicks(), PlayerbotAI::GetSpellCharges(), GetSpellEntryByDifficulty(), GameObject::GetSpellForLock(), PlayerbotAI::getSpellId(), GetSpellSpecific(), GetSpellStartDBScriptPriority(), GetSpellStore(), Item::GetTotalAP(), Player::GetTrainerSpellState(), WorldSession::HandleAcceptTradeOpcode(), ChatHandler::HandleAuraCommand(), Aura::HandleAuraModShapeshift(), Aura::HandleAuraModStun(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleCancelAuraOpcode(), ChatHandler::HandleCastBackCommand(), ChatHandler::HandleCastCommand(), ChatHandler::HandleCastDistCommand(), ChatHandler::HandleCastSelfCommand(), WorldSession::HandleCastSpellOpcode(), ChatHandler::HandleCastTargetCommand(), ChatHandler::HandleCooldownClearCommand(), ChatHandler::HandleDamageCommand(), ChatHandler::HandleDebugSpellCoefsCommand(), Unit::HandleDummyAuraProc(), ChatHandler::HandleGMVisibleCommand(), WorldSession::HandleItemQuerySingleOpcode(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLearnAllGMCommand(), ChatHandler::HandleLearnAllMyPetTalentsCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleLearnSkillRecipesHelper(), ChatHandler::HandleListTalentsCommand(), ChatHandler::HandleLookupSpellCommand(), PlayerbotMgr::HandleMasterOutgoingPacket(), WorldSession::HandlePetActionHelper(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePlayerLogin(), Unit::HandleProcTriggerSpellAuraProc(), WorldSession::HandleSelfResOpcode(), Aura::HandleShapeshiftBoosts(), SpellAuraHolder::HandleSpellSpecificBoosts(), Aura::HandleTriggerLinkedAura(), WorldSession::HandleUseItemOpcode(), Unit::HasAuraOfDifficulty(), PlayerbotAI::HasSpellReagents(), Pet::IgnoresOwnersDeath(), PlayerbotAI::In_Range(), CharmInfo::InitCharmCreateSpells(), SpellTargetMgr::Initialize(), Pet::InitLevelupSpellsForLevel(), PlayerbotAI::initPetSpell(), CharmInfo::InitPossessCreateSpells(), PlayerbotAI::initSpell(), Player::IsActionButtonDataValid(), SpellModifier::isAffectedOnSpell(), IsAutocastable(), IsPassiveSpell(), IsPositiveEffectTargetMode(), IsPositiveSpell(), IsPositiveSpellTargetMode(), IsPositiveSpellTargetModeForSpecificTarget(), SpellMgr::IsPrimaryProfessionSpell(), SpellMgr::IsProfessionOrRidingSpell(), SpellMgr::IsProfessionSpell(), IsQuestTameSpell(), WorldObject::IsSpellReady(), SpellMgr::IsSpellValid(), ConditionEntry::IsValid(), AchievementCriteriaRequirement::IsValid(), Unit::JustKilledCreature(), npc_corrupted_lightning_totemAI::JustRespawned(), Player::learnQuestRewardedSpells(), Creature::LoadCreatureAddon(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureSpellLists(), ObjectMgr::LoadCreatureTemplateSpells(), LoadDBCStores(), GameEventMgr::LoadFromDB(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadItemRequiredTarget(), LoadLootTemplates_Spell(), ObjectMgr::LoadNPCSpellClickSpells(), CharmInfo::LoadPetActionBar(), SpellMgr::LoadPetDefaultSpells(), Pet::LoadPetFromDB(), SpellMgr::LoadPetLevelupSpellMap(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadQuests(), ScriptMgr::LoadScriptMap(), SpellScriptMgr::LoadScripts(), ScriptMgr::LoadScripts(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellScriptTarget(), SpellMgr::LoadSpellTargetPositions(), ObjectMgr::LoadSpellTemplate(), ObjectMgr::LoadTrainers(), Player::LockOutSpells(), Unit::MeetsSelectAttackingRequirement(), Unit::ModifyAuraState(), DarknessOfSouls::OnApply(), SwiftFlightFormPassive::OnAuraValueCalculate(), PrayerOfMending::OnCheckCast(), SpellBurnBrutallus::OnCheckTarget(), PrayerOfMending::OnEffectExecute(), LavaLash::OnEffectExecute(), spell_judgement::OnEffectExecute(), EarthquakeGuardian::OnPeriodicTrigger(), PeriodicRotate::OnPeriodicTrigger(), PeriodicScarabTrigger::OnPeriodicTrigger(), PeriodicIceBolt::OnPeriodicTrigger(), SpoutTurning::OnPeriodicTrigger(), BloodReserveEnchant::OnProc(), UnitAI::OnSpellInterrupt(), UpdateZoneDependentPetsHelper::operator()(), CreatureEventAI::ProcessAction(), Spell::ProcSpellAuraTriggers(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank(), Unit::RemoveAuraHolderDueToSpellByDispel(), Unit::RemoveAurasDueToSpell(), Unit::RemoveGameObject(), Unit::RemoveRankAurasDueToSpell(), Player::RemoveSomeCooldown(), Player::removeSpell(), WorldObject::RemoveSpellCooldown(), Player::RemoveSpellLockout(), Player::RewardQuest(), BattleGround::RewardSpellCast(), Unit::SelectAttackingTarget(), Unit::SelectAttackingTargets(), SpellMgr::SelectAuraRankForLevel(), Spell::SelectMountByAreaAndSkill(), Totem::SetTypeBySummonSpell(), Spell::Spell(), SpellAuraHolder::SpellAuraHolder(), CharacterDatabaseCleaner::SpellCheck(), Unit::SpellNonMeleeDamageLog(), Creature::StartCooldown(), Unit::TriggerProccedSpell(), Aura::TriggerSpell(), Aura::TriggerSpellWithValue(), Pet::TryLoadFromDB(), Pet::Unsummon(), PetAI::UpdateAI(), TotemAI::UpdateAI(), PlayerbotAI::UpdateAI(), Player::UpdateCraftSkill(), Player::UpdatePotionCooldown(), UnitAI::UpdateSpellLists(), GameObject::Use(), PlayerbotAI::UseItem(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
sVehicleAccessoryStorage
SQLMultiStorage sVehicleAccessoryStorage(VehicleAccessorySrcFmt, VehicleAccessoryDstFmt, "vehicle_entry", "vehicle_accessory") (VehicleAccessorySrcFmt , VehicleAccessoryDstFmt , "vehicle_entry" , "vehicle_accessory")
Referenced by VehicleInfo::Initialize(), and ObjectMgr::LoadVehicleAccessory().
sWorldSafeLocsStore
SQLStorage sWorldSafeLocsStore(WorldSafeLocsFmt, "id", "world_safe_locs") (WorldSafeLocsFmt , "id" , "world_safe_locs")
Referenced by BattleGroundMgr::CreateInitialBattleGrounds(), GraveyardManager::GetClosestGraveyardHelper(), ChatHandler::HandleGoGraveyardCommand(), ChatHandler::HandleLinkGraveCommand(), World::LoadGraveyardZones(), and World::LoadWorldSafeLocs().
sWorldTemplate
SQLStorage sWorldTemplate(WorldTemplatesrcfmt, WorldTemplatedstfmt, "map", "world_template") (WorldTemplatesrcfmt , WorldTemplatedstfmt , "map" , "world_template")
Referenced by ObjectMgr::GetWorldTemplate(), and ObjectMgr::LoadWorldTemplate().
VehicleAccessoryDstFmt
const char VehicleAccessoryDstFmt[] = "iii"
Definition at line 41 of file SQLStorages.cpp.
VehicleAccessorySrcFmt
const char VehicleAccessorySrcFmt[] = "iiix"
Definition at line 40 of file SQLStorages.cpp.
WorldSafeLocsFmt
const char WorldSafeLocsFmt[] = "iiffffs"
Definition at line 47 of file SQLStorages.cpp.
WorldTemplatedstfmt
const char WorldTemplatedstfmt[] = "ii"
Definition at line 37 of file SQLStorages.cpp.
WorldTemplatesrcfmt
const char WorldTemplatesrcfmt[] = "is"
Definition at line 36 of file SQLStorages.cpp.