CMaNGOS_WoTLK: steam_vault.cpp File Reference
steam_vault.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "steam_vault.h"
Functions
bool GOUse_go_main_chambers_access_panel (Player *, GameObject *pGo)
InstanceData * GetInstanceData_instance_steam_vault (Map *pMap)
void AddSC_instance_steam_vault ()
Function Documentation
AddSC_instance_steam_vault()
void AddSC_instance_steam_vault ()
Definition at line 195 of file steam_vault.cpp.
References Script::GetInstanceData, GetInstanceData_instance_steam_vault(), GOUse_go_main_chambers_access_panel(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_steam_vault()
InstanceData* GetInstanceData_instance_steam_vault (Map * pMap)
Definition at line 190 of file steam_vault.cpp.
Referenced by AddSC_instance_steam_vault().
GOUse_go_main_chambers_access_panel()
bool GOUse_go_main_chambers_access_panel (Player * , GameObject * pGo)
Definition at line 33 of file steam_vault.cpp.
References InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), GO_ACCESS_PANEL_HYDRO, GO_ACCESS_PANEL_MEK, InstanceData::SetData(), SPECIAL, TYPE_HYDROMANCER_THESPIA, and TYPE_MEKGINEER_STEAMRIGGER.
Referenced by AddSC_instance_steam_vault().