CMaNGOS_WoTLK: stonetalon_mountains.cpp File Reference
stonetalon_mountains.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "Grids/GridNotifiers.h"
#include "Grids/CellImpl.h"
Data Structures
struct npc_kayaAI
struct go_covertopsAI
Enumerations
enum {
NPC_GRIMTOTEM_RUFFIAN = 11910 , NPC_GRIMTOTEM_BRUTE = 11912 , NPC_GRIMTOTEM_SORCERER = 11913 , SAY_START = -1000357 ,
SAY_AMBUSH = -1000358 , SAY_END = -1000359 , QUEST_PROTECT_KAYA = 6523
}
enum CovertOpsAlphaBetaMisc {
NPC_VENTURE_DEFORESTER = 3991 , NPC_VENTURE_LOGGER = 3989 , NPC_VENTURE_DIGGER = 3999 , NPC_VENTURE_OVERLORD = 4004 ,
NPC_VENTURE_OPERATOR = 3988 , PHASE_INACTIVE = 0 , PHASE_CALLING = 1 , PHASE_HOMING = 2
}
Functions
UnitAI * GetAI_npc_kaya (Creature *pCreature)
bool QuestAccept_npc_kaya (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
GameObjectAI * GetAIgo_covertops (GameObject *pGo)
void AddSC_stonetalon_mountains ()
Variables
static const uint32 ventureCoList [5] = { NPC_VENTURE_DEFORESTER, NPC_VENTURE_LOGGER, NPC_VENTURE_DIGGER, NPC_VENTURE_OVERLORD, NPC_VENTURE_OPERATOR }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
NPC_GRIMTOTEM_RUFFIAN
NPC_GRIMTOTEM_BRUTE
NPC_GRIMTOTEM_SORCERER
SAY_START
SAY_AMBUSH
SAY_END
QUEST_PROTECT_KAYA
Definition at line 33 of file stonetalon_mountains.cpp.
CovertOpsAlphaBetaMisc
enum CovertOpsAlphaBetaMisc
Enumerator
NPC_VENTURE_DEFORESTER
NPC_VENTURE_LOGGER
NPC_VENTURE_DIGGER
NPC_VENTURE_OVERLORD
NPC_VENTURE_OPERATOR
PHASE_INACTIVE
PHASE_CALLING
PHASE_HOMING
Definition at line 106 of file stonetalon_mountains.cpp.
Function Documentation
AddSC_stonetalon_mountains()
void AddSC_stonetalon_mountains ()
Definition at line 217 of file stonetalon_mountains.cpp.
References Script::GetAI, GetAI_npc_kaya(), GetAIgo_covertops(), Script::GetGameObjectAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_kaya(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_kaya()
UnitAI* GetAI_npc_kaya (Creature * pCreature)
Definition at line 82 of file stonetalon_mountains.cpp.
Referenced by AddSC_stonetalon_mountains().
GetAIgo_covertops()
GameObjectAI* GetAIgo_covertops (GameObject * pGo)
Definition at line 208 of file stonetalon_mountains.cpp.
Referenced by AddSC_stonetalon_mountains().
QuestAccept_npc_kaya()
bool QuestAccept_npc_kaya (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
Definition at line 87 of file stonetalon_mountains.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_PASSIVE, Quest::GetQuestId(), QUEST_PROTECT_KAYA, SAY_START, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_stonetalon_mountains().
Variable Documentation
ventureCoList
const uint32 ventureCoList[5] = { NPC_VENTURE_DEFORESTER, NPC_VENTURE_LOGGER, NPC_VENTURE_DIGGER, NPC_VENTURE_OVERLORD, NPC_VENTURE_OPERATOR } static
Definition at line 121 of file stonetalon_mountains.cpp.
Referenced by go_covertopsAI::OnLootStateChange().