CMaNGOS_WoTLK: storm_peaks.cpp File Reference
storm_peaks.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_floating_spiritAI
struct npc_injured_minerAI
struct CastNetStormforgedPursuer
struct npc_ethereal_frostworgAI
Enumerations
enum {
SPELL_BLOW_HODIRS_HORN = 55983 , SPELL_SUMMON_FROST_GIANG_SPIRIT = 55986 , SPELL_SUMMON_FROST_WARRIOR_SPIRIT = 55991 , SPELL_SUMMON_FROST_GHOST_SPIRIT = 55992 ,
NPC_FROST_GIANT_GHOST_KC = 30138 , NPC_FROST_DWARF_GHOST_KC = 30139 , NPC_NIFFELEM_FOREFATHER = 29974 , NPC_FROSTBORN_WARRIOR = 30135 ,
NPC_FROSTBORN_GHOST = 30144
}
enum {
SAY_MINER_READY = -1001051 , SAY_MINER_COMPLETE = -1001052 , GOSSIP_ITEM_ID_READY = -3000112 , TEXT_ID_POISONED = 13650 ,
TEXT_ID_READY = 13651 , SPELL_FEIGN_DEATH = 51329 , QUEST_ID_BITTER_DEPARTURE = 12832
}
enum { SPELL_SUMMON_INFILTRATOR = 56325 , NPC_STORMFORGED_INFILTRATOR = 30222 , FROSTWOLF_MOVE_NORMAL = 1 , FROSTWOLF_MOVE_FINAL = 2 }
enum FrostwolfActions { FROSTWOLF_CHANGE_DIRECTION , FROSTWOLF_RESUME_SEARCH , FROSTWOLF_FIND_INFILTRATOR , FROSTWOLF_SUMMON_INFILTRATOR }
Functions
UnitAI * GetAI_npc_floating_spirit (Creature *pCreature)
bool EffectDummyCreature_npc_restless_frostborn (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
UnitAI * GetAI_npc_injured_miner (Creature *pCreature)
bool GossipHello_npc_injured_miner (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_injured_miner (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool QuestAccept_npc_injured_miner (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_storm_peaks ()
Variables
static const uint32 ethereal_frostworg_emotes [4][2]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_BLOW_HODIRS_HORN
SPELL_SUMMON_FROST_GIANG_SPIRIT
SPELL_SUMMON_FROST_WARRIOR_SPIRIT
SPELL_SUMMON_FROST_GHOST_SPIRIT
NPC_FROST_GIANT_GHOST_KC
NPC_FROST_DWARF_GHOST_KC
NPC_NIFFELEM_FOREFATHER
NPC_FROSTBORN_WARRIOR
NPC_FROSTBORN_GHOST
Definition at line 37 of file storm_peaks.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MINER_READY
SAY_MINER_COMPLETE
GOSSIP_ITEM_ID_READY
TEXT_ID_POISONED
TEXT_ID_READY
SPELL_FEIGN_DEATH
QUEST_ID_BITTER_DEPARTURE
Definition at line 110 of file storm_peaks.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SUMMON_INFILTRATOR
NPC_STORMFORGED_INFILTRATOR
FROSTWOLF_MOVE_NORMAL
FROSTWOLF_MOVE_FINAL
Definition at line 243 of file storm_peaks.cpp.
FrostwolfActions
enum FrostwolfActions
Enumerator
FROSTWOLF_CHANGE_DIRECTION
FROSTWOLF_RESUME_SEARCH
FROSTWOLF_FIND_INFILTRATOR
FROSTWOLF_SUMMON_INFILTRATOR
Definition at line 253 of file storm_peaks.cpp.
Function Documentation
AddSC_storm_peaks()
void AddSC_storm_peaks ()
Definition at line 364 of file storm_peaks.cpp.
References EffectDummyCreature_npc_restless_frostborn(), Script::GetAI, GetAI_npc_floating_spirit(), GetAI_npc_injured_miner(), GossipHello_npc_injured_miner(), GossipSelect_npc_injured_miner(), Script::Name, Script::pEffectDummyNPC, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_injured_miner(), and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_npc_restless_frostborn()
bool EffectDummyCreature_npc_restless_frostborn (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 75 of file storm_peaks.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), Object::GetTypeId(), Unit::IsAlive(), NPC_FROST_DWARF_GHOST_KC, NPC_FROST_GIANT_GHOST_KC, NPC_FROSTBORN_GHOST, NPC_FROSTBORN_WARRIOR, NPC_NIFFELEM_FOREFATHER, SPELL_BLOW_HODIRS_HORN, SPELL_SUMMON_FROST_GHOST_SPIRIT, SPELL_SUMMON_FROST_GIANG_SPIRIT, SPELL_SUMMON_FROST_WARRIOR_SPIRIT, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
Referenced by AddSC_storm_peaks().
GetAI_npc_floating_spirit()
UnitAI* GetAI_npc_floating_spirit (Creature * pCreature)
Definition at line 66 of file storm_peaks.cpp.
Referenced by AddSC_storm_peaks().
GetAI_npc_injured_miner()
UnitAI* GetAI_npc_injured_miner (Creature * pCreature)
Definition at line 183 of file storm_peaks.cpp.
Referenced by AddSC_storm_peaks().
GossipHello_npc_injured_miner()
bool GossipHello_npc_injured_miner (Player * pPlayer, Creature * pCreature)
Definition at line 188 of file storm_peaks.cpp.
References Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ID_READY, GOSSIP_SENDER_MAIN, Unit::HasAura(), Unit::isQuestGiver(), Player::PrepareQuestMenu(), SPELL_FEIGN_DEATH, TEXT_ID_POISONED, and TEXT_ID_READY.
Referenced by AddSC_storm_peaks().
GossipSelect_npc_injured_miner()
bool GossipSelect_npc_injured_miner (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 204 of file storm_peaks.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, GOSSIP_ACTION_INFO_DEF, and UnitAI::SendAIEvent().
Referenced by AddSC_storm_peaks().
QuestAccept_npc_injured_miner()
bool QuestAccept_npc_injured_miner (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 215 of file storm_peaks.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_BITTER_DEPARTURE, and UnitAI::SendAIEvent().
Referenced by AddSC_storm_peaks().
Variable Documentation
ethereal_frostworg_emotes
const uint32 ethereal_frostworg_emotes[4][2] static
Initial value:
=
{
    {30909, 30910},
    {30911, 30912},
    {30913, 30914},
    {30915, 30915}
}
Definition at line 261 of file storm_peaks.cpp.
Referenced by npc_ethereal_frostworgAI::MovementInform(), and npc_ethereal_frostworgAI::npc_ethereal_frostworgAI().