CMaNGOS_WoTLK: stormwind_city.cpp File Reference
stormwind_city.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "world_eastern_kingdoms.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_bartlebyAI
struct npc_dashel_stonefistAI
struct npc_squire_roweAI
struct npc_reginald_windsorAI
struct go_portal_to_orgrimmar
struct go_portal_to_undercity
Macros
#define GOSSIP_ITEM_KAT_1 "Pardon the intrusion, Lady Prestor, but Highlord Bolvar suggested that I seek your advice."
#define GOSSIP_ITEM_KAT_2 "My apologies, Lady Prestor."
#define GOSSIP_ITEM_KAT_3 "Begging your pardon, Lady Prestor. That was not my intent."
#define GOSSIP_ITEM_KAT_4 "Thank you for your time, Lady Prestor."
Enumerations
enum { FACTION_ENEMY = 168 , QUEST_BEAT = 1640 }
enum {
QUEST_MISSING_DIPLO_PT8 = 1447 , FACTION_HOSTILE = 168 , NPC_OLD_TOWN_THUG = 4969 , SAY_STONEFIST_1 = -1001274 ,
SAY_STONEFIST_2 = -1001275 , SAY_STONEFIST_3 = -1001276
}
enum {
SAY_SIGNAL_SENT = -1000822 , SAY_DISMOUNT = -1000823 , SAY_WELCOME = -1000824 , GOSSIP_ITEM_WINDSOR = -3000106 ,
GOSSIP_TEXT_ID_DEFAULT = 9063 , GOSSIP_TEXT_ID_PROGRESS = 9064 , GOSSIP_TEXT_ID_START = 9065 , NPC_WINDSOR_MOUNT = 12581 ,
SPELL_BLUE_FIREWORK = 11540 , SPELL_DISMISS_HORSE = 20000 , SPELL_WINDSOR_INSPIRATION = 20273 , QUEST_STORMWIND_RENDEZVOUS = 6402 ,
QUEST_THE_GREAT_MASQUERADE = 6403
}
enum {
SAY_WINDSOR_QUEST_ACCEPT = -1000825 , SAY_WINDSOR_GET_READY = -1000826 , SAY_PRESTOR_SIEZE = -1000827 , SAY_JON_DIALOGUE_1 = -1000828 ,
SAY_WINDSOR_DIALOGUE_2 = -1000829 , SAY_WINDSOR_DIALOGUE_3 = -1000830 , SAY_JON_DIALOGUE_4 = -1000832 , SAY_JON_DIALOGUE_5 = -1000833 ,
SAY_WINDSOR_DIALOGUE_6 = -1000834 , SAY_WINDSOR_DIALOGUE_7 = -1000835 , SAY_JON_DIALOGUE_8 = -1000836 , SAY_JON_DIALOGUE_9 = -1000837 ,
SAY_JON_DIALOGUE_10 = -1000838 , SAY_JON_DIALOGUE_11 = -1000839 , SAY_WINDSOR_DIALOGUE_12 = -1000840 , SAY_WINDSOR_DIALOGUE_13 = -1000841 ,
SAY_WINDSOR_BEFORE_KEEP = -1000849 , SAY_WINDSOR_TO_KEEP = -1000850 , SAY_WINDSOR_KEEP_1 = -1000851 , SAY_BOLVAR_KEEP_2 = -1000852 ,
SAY_WINDSOR_KEEP_3 = -1000853 , SAY_PRESTOR_KEEP_4 = -1000855 , SAY_PRESTOR_KEEP_5 = -1000856 , SAY_WINDSOR_KEEP_6 = -1000857 ,
SAY_WINDSOR_KEEP_7 = -1000859 , SAY_WINDSOR_KEEP_8 = -1000860 , SAY_PRESTOR_KEEP_9 = -1000863 , SAY_BOLVAR_KEEP_10 = -1000864 ,
SAY_PRESTOR_KEEP_11 = -1000865 , SAY_WINDSOR_KEEP_12 = -1000866 , SAY_PRESTOR_KEEP_13 = -1000867 , SAY_PRESTOR_KEEP_14 = -1000868 ,
SAY_BOLVAR_KEEP_15 = -1000869 , SAY_WINDSOR_KEEP_16 = -1000870 , EMOTE_CONTEMPLATION = -1000831 , EMOTE_PRESTOR_LAUGH = -1000854 ,
EMOTE_WINDSOR_TABLETS = -1000858 , EMOTE_WINDSOR_READ = -1000861 , EMOTE_BOLVAR_GASP = -1000862 , EMOTE_WINDSOR_DIE = -1000871 ,
EMOTE_GUARD_TRANSFORM = -1000872 , GOSSIP_ITEM_REGINALD = -3000107 , GOSSIP_TEXT_ID_MASQUERADE = 5633 , SPELL_ONYXIA_TRANSFORM = 20409 ,
SPELL_WINDSOR_READ = 20358 , SPELL_WINDSOR_DEATH = 20465 , SPELL_ONYXIA_DESPAWN = 20466 , SPELL_HAMMER_OF_JUSTICE = 10308 ,
SPELL_SHIELD_WALL = 871 , SPELL_STRONG_CLEAVE = 8255 , NPC_GUARD_ROYAL = 1756 , NPC_GUARD_CITY = 68 ,
NPC_GUARD_PATROLLER = 1976 , NPC_GUARD_ONYXIA = 12739 , MAX_ROYAL_GUARDS = 6
}
enum { GO_HEAD_OF_NEFARIAN_SW = 179882 , GO_HEAD_OF_ONYXIA_SW = 179558 , GOSSIP_HEAD_MAT = 5754 , GOSSIP_HEAD_AFRA = 6027 }
Functions
bool QuestAccept_npc_bartleby (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_bartleby (Creature *pCreature)
bool QuestAccept_npc_dashel_stonefist (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_dashel_stonefist (Creature *pCreature)
bool GossipHello_npc_lady_katrana_prestor (Player *player, Creature *creature)
bool GossipSelect_npc_lady_katrana_prestor (Player *player, Creature *creature, uint32, uint32 action)
UnitAI * GetAI_npc_squire_rowe (Creature *creature)
bool GossipHello_npc_squire_rowe (Player *player, Creature *creature)
bool GossipSelect_npc_squire_rowe (Player *player, Creature *creature, uint32, uint32 action)
UnitAI * GetAI_npc_reginald_windsor (Creature *creature)
bool QuestAccept_npc_reginald_windsor (Player *player, Creature *creature, const Quest *quest)
bool GossipHello_npc_reginald_windsor (Player *player, Creature *creature)
bool GossipSelect_npc_reginald_windsor (Player *player, Creature *creature, uint32, uint32 action)
bool GossipHello_npc_major_mattingly (Player *player, Creature *creature)
bool GossipHello_npc_field_marshal_afrasiabi (Player *player, Creature *creature)
void AddSC_stormwind_city ()
Variables
static const DialogueEntry aIntroDialogue []
static const float aWindsorSpawnLoc [3] = { -9145.68f, 373.79f, 90.64f}
static const float aWindsorMoveLoc [3] = { -9050.39f, 443.55f, 93.05f}
static const float aGuardLocations [MAX_ROYAL_GUARDS][4]
static const float aMoveLocations [10][3]
static const DialogueEntry aMasqueradeDialogue []
Macro Definition Documentation
GOSSIP_ITEM_KAT_1
#define GOSSIP_ITEM_KAT_1 "Pardon the intrusion, Lady Prestor, but Highlord Bolvar suggested that I seek your advice."
Definition at line 203 of file stormwind_city.cpp.
GOSSIP_ITEM_KAT_2
#define GOSSIP_ITEM_KAT_2 "My apologies, Lady Prestor."
Definition at line 204 of file stormwind_city.cpp.
GOSSIP_ITEM_KAT_3
#define GOSSIP_ITEM_KAT_3 "Begging your pardon, Lady Prestor. That was not my intent."
Definition at line 205 of file stormwind_city.cpp.
GOSSIP_ITEM_KAT_4
#define GOSSIP_ITEM_KAT_4 "Thank you for your time, Lady Prestor."
Definition at line 206 of file stormwind_city.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FACTION_ENEMY
QUEST_BEAT
Definition at line 40 of file stormwind_city.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MISSING_DIPLO_PT8
FACTION_HOSTILE
NPC_OLD_TOWN_THUG
SAY_STONEFIST_1
SAY_STONEFIST_2
SAY_STONEFIST_3
Definition at line 88 of file stormwind_city.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_SIGNAL_SENT
SAY_DISMOUNT
SAY_WELCOME
GOSSIP_ITEM_WINDSOR
GOSSIP_TEXT_ID_DEFAULT
GOSSIP_TEXT_ID_PROGRESS
GOSSIP_TEXT_ID_START
NPC_WINDSOR_MOUNT
SPELL_BLUE_FIREWORK
SPELL_DISMISS_HORSE
SPELL_WINDSOR_INSPIRATION
QUEST_STORMWIND_RENDEZVOUS
QUEST_THE_GREAT_MASQUERADE
Definition at line 249 of file stormwind_city.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_WINDSOR_QUEST_ACCEPT
SAY_WINDSOR_GET_READY
SAY_PRESTOR_SIEZE
SAY_JON_DIALOGUE_1
SAY_WINDSOR_DIALOGUE_2
SAY_WINDSOR_DIALOGUE_3
SAY_JON_DIALOGUE_4
SAY_JON_DIALOGUE_5
SAY_WINDSOR_DIALOGUE_6
SAY_WINDSOR_DIALOGUE_7
SAY_JON_DIALOGUE_8
SAY_JON_DIALOGUE_9
SAY_JON_DIALOGUE_10
SAY_JON_DIALOGUE_11
SAY_WINDSOR_DIALOGUE_12
SAY_WINDSOR_DIALOGUE_13
SAY_WINDSOR_BEFORE_KEEP
SAY_WINDSOR_TO_KEEP
SAY_WINDSOR_KEEP_1
SAY_BOLVAR_KEEP_2
SAY_WINDSOR_KEEP_3
SAY_PRESTOR_KEEP_4
SAY_PRESTOR_KEEP_5
SAY_WINDSOR_KEEP_6
SAY_WINDSOR_KEEP_7
SAY_WINDSOR_KEEP_8
SAY_PRESTOR_KEEP_9
SAY_BOLVAR_KEEP_10
SAY_PRESTOR_KEEP_11
SAY_WINDSOR_KEEP_12
SAY_PRESTOR_KEEP_13
SAY_PRESTOR_KEEP_14
SAY_BOLVAR_KEEP_15
SAY_WINDSOR_KEEP_16
EMOTE_CONTEMPLATION
EMOTE_PRESTOR_LAUGH
EMOTE_WINDSOR_TABLETS
EMOTE_WINDSOR_READ
EMOTE_BOLVAR_GASP
EMOTE_WINDSOR_DIE
EMOTE_GUARD_TRANSFORM
GOSSIP_ITEM_REGINALD
GOSSIP_TEXT_ID_MASQUERADE
SPELL_ONYXIA_TRANSFORM
SPELL_WINDSOR_READ
SPELL_WINDSOR_DEATH
SPELL_ONYXIA_DESPAWN
SPELL_HAMMER_OF_JUSTICE
SPELL_SHIELD_WALL
SPELL_STRONG_CLEAVE
NPC_GUARD_ROYAL
NPC_GUARD_CITY
NPC_GUARD_PATROLLER
NPC_GUARD_ONYXIA
MAX_ROYAL_GUARDS
Definition at line 455 of file stormwind_city.cpp.
anonymous enum
anonymous enum
Enumerator
GO_HEAD_OF_NEFARIAN_SW
GO_HEAD_OF_ONYXIA_SW
GOSSIP_HEAD_MAT
GOSSIP_HEAD_AFRA
Definition at line 1100 of file stormwind_city.cpp.
Function Documentation
AddSC_stormwind_city()
void AddSC_stormwind_city ()
Definition at line 1133 of file stormwind_city.cpp.
References Script::GetAI, GetAI_npc_bartleby(), GetAI_npc_dashel_stonefist(), GetAI_npc_reginald_windsor(), GetAI_npc_squire_rowe(), Script::GetGameObjectAI, GossipHello_npc_field_marshal_afrasiabi(), GossipHello_npc_lady_katrana_prestor(), GossipHello_npc_major_mattingly(), GossipHello_npc_reginald_windsor(), GossipHello_npc_squire_rowe(), GossipSelect_npc_lady_katrana_prestor(), GossipSelect_npc_reginald_windsor(), GossipSelect_npc_squire_rowe(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_bartleby(), QuestAccept_npc_dashel_stonefist(), QuestAccept_npc_reginald_windsor(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_bartleby()
UnitAI* GetAI_npc_bartleby (Creature * pCreature)
Definition at line 79 of file stormwind_city.cpp.
Referenced by AddSC_stormwind_city().
GetAI_npc_dashel_stonefist()
UnitAI* GetAI_npc_dashel_stonefist (Creature * pCreature)
Definition at line 194 of file stormwind_city.cpp.
Referenced by AddSC_stormwind_city().
GetAI_npc_reginald_windsor()
UnitAI* GetAI_npc_reginald_windsor (Creature * creature)
Definition at line 1020 of file stormwind_city.cpp.
Referenced by AddSC_stormwind_city().
GetAI_npc_squire_rowe()
UnitAI* GetAI_npc_squire_rowe (Creature * creature)
Definition at line 406 of file stormwind_city.cpp.
Referenced by AddSC_stormwind_city().
GossipHello_npc_field_marshal_afrasiabi()
bool GossipHello_npc_field_marshal_afrasiabi (Player * player, Creature * creature)
Definition at line 1121 of file stormwind_city.cpp.
References GetClosestGameObjectWithEntry(), Creature::GetCreatureInfo(), GO_HEAD_OF_NEFARIAN_SW, GOSSIP_HEAD_AFRA, CreatureInfo::GossipMenuId, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_stormwind_city().
GossipHello_npc_lady_katrana_prestor()
bool GossipHello_npc_lady_katrana_prestor (Player * player, Creature * creature)
Definition at line 208 of file stormwind_city.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KAT_1, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_stormwind_city().
GossipHello_npc_major_mattingly()
bool GossipHello_npc_major_mattingly (Player * player, Creature * creature)
Definition at line 1109 of file stormwind_city.cpp.
References GetClosestGameObjectWithEntry(), Creature::GetCreatureInfo(), GO_HEAD_OF_ONYXIA_SW, GOSSIP_HEAD_MAT, CreatureInfo::GossipMenuId, Player::PrepareGossipMenu(), and Player::SendPreparedGossip().
Referenced by AddSC_stormwind_city().
GossipHello_npc_reginald_windsor()
bool GossipHello_npc_reginald_windsor (Player * player, Creature * creature)
Definition at line 1036 of file stormwind_city.cpp.
References Creature::AI(), DEFAULT_GOSSIP_MESSAGE, Object::GetObjectGuid(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_REGINALD, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_MASQUERADE, Unit::isQuestGiver(), Player::PrepareQuestMenu(), QUEST_STATUS_COMPLETE, QUEST_STORMWIND_RENDEZVOUS, and QUEST_THE_GREAT_MASQUERADE.
Referenced by AddSC_stormwind_city().
GossipHello_npc_squire_rowe()
bool GossipHello_npc_squire_rowe (Player * player, Creature * creature)
Definition at line 411 of file stormwind_city.cpp.
References Creature::AI(), Object::GetObjectGuid(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_WINDSOR, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_DEFAULT, GOSSIP_TEXT_ID_PROGRESS, GOSSIP_TEXT_ID_START, QUEST_STATUS_COMPLETE, QUEST_STORMWIND_RENDEZVOUS, and QUEST_THE_GREAT_MASQUERADE.
Referenced by AddSC_stormwind_city().
GossipSelect_npc_lady_katrana_prestor()
bool GossipSelect_npc_lady_katrana_prestor (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 221 of file stormwind_city.cpp.
References Player::AreaExploredOrEventHappens(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KAT_2, GOSSIP_ITEM_KAT_3, GOSSIP_ITEM_KAT_4, and GOSSIP_SENDER_MAIN.
Referenced by AddSC_stormwind_city().
GossipSelect_npc_reginald_windsor()
bool GossipSelect_npc_reginald_windsor (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1060 of file stormwind_city.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_stormwind_city().
GossipSelect_npc_squire_rowe()
bool GossipSelect_npc_squire_rowe (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 438 of file stormwind_city.cpp.
References Creature::AI(), and GOSSIP_ACTION_INFO_DEF.
Referenced by AddSC_stormwind_city().
QuestAccept_npc_bartleby()
bool QuestAccept_npc_bartleby (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 69 of file stormwind_city.cpp.
References Creature::AI(), UnitAI::AttackStart(), FACTION_ENEMY, Quest::GetQuestId(), QUEST_BEAT, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_COMBAT_STOP, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_stormwind_city().
QuestAccept_npc_dashel_stonefist()
bool QuestAccept_npc_dashel_stonefist (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 178 of file stormwind_city.cpp.
References Creature::AI(), DoScriptText(), FACTION_HOSTILE, Object::GetObjectGuid(), Quest::GetQuestId(), QUEST_MISSING_DIPLO_PT8, REACT_AGGRESSIVE, Object::RemoveFlag(), SAY_STONEFIST_1, Creature::SetFactionTemporary(), UnitAI::SetReactState(), TEMPFACTION_RESTORE_COMBAT_STOP, TEMPFACTION_RESTORE_RESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by AddSC_stormwind_city().
QuestAccept_npc_reginald_windsor()
bool QuestAccept_npc_reginald_windsor (Player * player, Creature * creature, const Quest * quest)
Definition at line 1025 of file stormwind_city.cpp.
References Creature::AI(), Quest::GetQuestId(), and QUEST_THE_GREAT_MASQUERADE.
Referenced by AddSC_stormwind_city().
Variable Documentation
aGuardLocations
const float aGuardLocations[MAX_ROYAL_GUARDS][4] static
Initial value:
=
{
    { -8968.510f, 512.556f, 96.352f, 3.849f},
    { -8969.780f, 515.012f, 96.593f, 3.955f},
    { -8972.410f, 518.228f, 96.594f, 4.281f},
    { -8965.170f, 508.565f, 96.352f, 3.825f},
    { -8962.960f, 506.583f, 96.593f, 3.802f},
    { -8961.080f, 503.828f, 96.593f, 3.465f},
}
Definition at line 525 of file stormwind_city.cpp.
Referenced by npc_reginald_windsorAI::WaypointReached().
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {NPC_WINDSOR,                0,           3000},
    {NPC_WINDSOR_MOUNT,          0,           1000},
    {SAY_DISMOUNT,               NPC_WINDSOR, 2000},
    {QUEST_STORMWIND_RENDEZVOUS, 0,           2000},
    {QUEST_THE_GREAT_MASQUERADE, 0,           0},
    {0, 0, 0},
}
Definition at line 271 of file stormwind_city.cpp.
aMasqueradeDialogue
const DialogueEntry aMasqueradeDialogue[] static
Definition at line 548 of file stormwind_city.cpp.
aMoveLocations
const float aMoveLocations[10][3] static
Initial value:
=
{
    { -8967.960f, 510.008f, 96.351f},
    { -8959.440f, 505.424f, 96.595f},
    { -8957.670f, 507.056f, 96.595f},
    { -8970.680f, 519.252f, 96.595f},
    { -8969.100f, 520.395f, 96.595f},
    { -8974.590f, 516.213f, 96.590f},
    { -8505.770f, 338.312f, 120.886f},
    { -8448.690f, 337.074f, 121.330f},
    { -8448.279f, 338.398f, 121.329f}
}
Definition at line 535 of file stormwind_city.cpp.
Referenced by npc_reginald_windsorAI::JustDidDialogueStep(), and npc_reginald_windsorAI::WaypointReached().
aWindsorMoveLoc
const float aWindsorMoveLoc[3] = { -9050.39f, 443.55f, 93.05f} static
Definition at line 282 of file stormwind_city.cpp.
Referenced by npc_squire_roweAI::JustSummoned().
aWindsorSpawnLoc
const float aWindsorSpawnLoc[3] = { -9145.68f, 373.79f, 90.64f} static
Definition at line 281 of file stormwind_city.cpp.
Referenced by npc_squire_roweAI::WaypointReached().