CMaNGOS_WoTLK: stratholmeScripts.cpp File Reference
stratholmeScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "stratholme.h"
Data Structures
struct mob_restless_soulAI
struct mobs_spectral_ghostly_citizenAI
Enumerations
enum {
SAY_ZAPPED0 = -1329000 , SAY_ZAPPED1 = -1329001 , SAY_ZAPPED2 = -1329002 , SAY_ZAPPED3 = -1329003 ,
QUEST_RESTLESS_SOUL = 5282 , SPELL_EGAN_BLASTER = 17368 , SPELL_SOUL_FREED = 17370 , SPELL_SUMMON_FREED_SOUL = 17408 ,
NPC_RESTLESS_SOUL = 11122 , NPC_FREED_SOUL = 11136
}
enum { SPELL_HAUNTING_PHANTOM = 16336 , SPELL_SLAP = 6754 }
enum { GOSSIP_TEXT_AURIUS_1 = 3755 , GOSSIP_TEXT_AURIUS_2 = 3756 , GOSSIP_TEXT_AURIUS_3 = 3757 }
Functions
bool GOUse_go_service_gate (Player *, GameObject *pGo)
bool GOUse_go_gauntlet_gate (Player *pPlayer, GameObject *pGo)
bool GOUse_go_stratholme_postbox (Player *pPlayer, GameObject *pGo)
UnitAI * GetAI_mob_restless_soul (Creature *pCreature)
UnitAI * GetAI_mobs_spectral_ghostly_citizen (Creature *pCreature)
bool QuestRewarded_npc_aurius (Player *, Creature *pCreature, const Quest *pQuest)
bool GossipHello_npc_aurius (Player *pPlayer, Creature *pCreature)
void AddSC_stratholme ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_ZAPPED0
SAY_ZAPPED1
SAY_ZAPPED2
SAY_ZAPPED3
QUEST_RESTLESS_SOUL
SPELL_EGAN_BLASTER
SPELL_SOUL_FREED
SPELL_SUMMON_FREED_SOUL
NPC_RESTLESS_SOUL
NPC_FREED_SOUL
Definition at line 129 of file stratholmeScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_HAUNTING_PHANTOM
SPELL_SLAP
Definition at line 213 of file stratholmeScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_TEXT_AURIUS_1
GOSSIP_TEXT_AURIUS_2
GOSSIP_TEXT_AURIUS_3
Definition at line 306 of file stratholmeScripts.cpp.
Function Documentation
AddSC_stratholme()
void AddSC_stratholme ()
Definition at line 353 of file stratholmeScripts.cpp.
References Script::GetAI, GetAI_mob_restless_soul(), GetAI_mobs_spectral_ghostly_citizen(), GossipHello_npc_aurius(), GOUse_go_gauntlet_gate(), GOUse_go_service_gate(), GOUse_go_stratholme_postbox(), Script::Name, Script::pGossipHello, Script::pGOUse, Script::pQuestRewardedNPC, QuestRewarded_npc_aurius(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_restless_soul()
UnitAI* GetAI_mob_restless_soul (Creature * pCreature)
Definition at line 204 of file stratholmeScripts.cpp.
Referenced by AddSC_stratholme().
GetAI_mobs_spectral_ghostly_citizen()
UnitAI* GetAI_mobs_spectral_ghostly_citizen (Creature * pCreature)
Definition at line 297 of file stratholmeScripts.cpp.
Referenced by AddSC_stratholme().
GossipHello_npc_aurius()
bool GossipHello_npc_aurius (Player * pPlayer, Creature * pCreature)
Definition at line 329 of file stratholmeScripts.cpp.
References DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_TEXT_AURIUS_1, GOSSIP_TEXT_AURIUS_2, GOSSIP_TEXT_AURIUS_3, Unit::isQuestGiver(), Player::PrepareQuestMenu(), TYPE_AURIUS, and TYPE_BARON.
Referenced by AddSC_stratholme().
GOUse_go_gauntlet_gate()
bool GOUse_go_gauntlet_gate (Player * pPlayer, GameObject * pGo)
Definition at line 59 of file stratholmeScripts.cpp.
References Unit::CastSpell(), InstanceData::GetData(), Player::GetGroup(), WorldObject::GetInstanceData(), Unit::HasAura(), IN_PROGRESS, GroupReference::next(), NOT_STARTED, InstanceData::SetData(), SPELL_BARON_ULTIMATUM, TRIGGERED_OLD_TRIGGERED, and TYPE_BARON_RUN.
Referenced by AddSC_stratholme().
GOUse_go_service_gate()
bool GOUse_go_service_gate (Player * , GameObject * pGo)
Definition at line 40 of file stratholmeScripts.cpp.
References InstanceData::GetData(), WorldObject::GetInstanceData(), IN_PROGRESS, NOT_STARTED, InstanceData::SetData(), and TYPE_BARTHILAS_RUN.
Referenced by AddSC_stratholme().
GOUse_go_stratholme_postbox()
bool GOUse_go_stratholme_postbox (Player * pPlayer, GameObject * pGo)
Definition at line 95 of file stratholmeScripts.cpp.
References Unit::CastSpell(), DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetRandomPoint(), IN_PROGRESS, NPC_UNDEAD_POSTMAN, InstanceData::SetData(), SPECIAL, SPELL_SUMMON_POSTMASTER, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, and TYPE_POSTMASTER.
Referenced by AddSC_stratholme().
QuestRewarded_npc_aurius()
bool QuestRewarded_npc_aurius (Player * , Creature * pCreature, const Quest * pQuest)
Definition at line 313 of file stratholmeScripts.cpp.
References DONE, InstanceData::GetData(), WorldObject::GetInstanceData(), Quest::GetQuestId(), QUEST_MEDALLION_FAITH, InstanceData::SetData(), TYPE_AURIUS, and TYPE_BARON.
Referenced by AddSC_stratholme().