CMaNGOS_WoTLK: stranglethorn_vale.cpp File Reference
stranglethorn_vale.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct mob_yennikuAI
Enumerations
enum { SPELL_YENNIKUS_RELEASE = 3607 , QUEST_ID_SAVING_YENNIKU = 592 , FACTION_ID_HORDE_GENERIC = 83 }
Functions
UnitAI * GetAI_mob_yenniku (Creature *_Creature)
void AddSC_stranglethorn_vale ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_YENNIKUS_RELEASE
QUEST_ID_SAVING_YENNIKU
FACTION_ID_HORDE_GENERIC
Definition at line 34 of file stranglethorn_vale.cpp.
Function Documentation
AddSC_stranglethorn_vale()
void AddSC_stranglethorn_vale ()
Definition at line 110 of file stranglethorn_vale.cpp.
References Script::GetAI, GetAI_mob_yenniku(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_yenniku()
UnitAI* GetAI_mob_yenniku (Creature * _Creature)
Definition at line 101 of file stranglethorn_vale.cpp.
Referenced by AddSC_stranglethorn_vale().