CMaNGOS_WoTLK: ShadeOfTheHorsemanData Struct Reference
ShadeOfTheHorsemanData Struct Reference
#include <world_map_scripts.h>
Public Member Functions
ShadeOfTheHorsemanData (std::vector< uint32 > areaIds)
void Reset ()
uint32 GetDataAttackPhase (uint32 id) const
void SetDataAttackPhase (uint32 id, uint32 value)
bool IsConditionFulfilled (uint32 conditionId, uint32 areaId) const
uint32 HandleGetData (uint32 id) const
void HandleSetData (uint32 id, uint32 value)
Static Public Member Functions
static uint32 GetTypeFromZoneId (uint32 zoneId)
Data Fields
uint32 m_shadeOfTheHorsemanAttackPhases [MAX_VILLAGES]
std::vector< uint32 > m_areaIds
Detailed Description
Definition at line 83 of file world_map_scripts.h.
Constructor & Destructor Documentation
ShadeOfTheHorsemanData()
ShadeOfTheHorsemanData::ShadeOfTheHorsemanData (std::vector< uint32 > areaIds) inline
Definition at line 85 of file world_map_scripts.h.
Member Function Documentation
GetDataAttackPhase()
uint32 ShadeOfTheHorsemanData::GetDataAttackPhase (uint32 id) const
Definition at line 172 of file world_map_scripts.cpp.
References m_shadeOfTheHorsemanAttackPhases.
GetTypeFromZoneId()
uint32 ShadeOfTheHorsemanData::GetTypeFromZoneId (uint32 zoneId) static
Definition at line 250 of file world_map_scripts.cpp.
References SHADE_VILLAGE_AZURE_WATCH, SHADE_VILLAGE_BRILL, SHADE_VILLAGE_FALCONWING_SQUARE, SHADE_VILLAGE_GOLDSHIRE, SHADE_VILLAGE_KHARANOS, SHADE_VILLAGE_RAZOR_HILL, ZONEID_AZUREMYST_ISLE, ZONEID_DUN_MOROGH, ZONEID_DUROTAR, ZONEID_ELWYNN_FOREST, ZONEID_EVERSONG_WOODS, and ZONEID_TIRISFAL_GLADES.
Referenced by GossipHello_npc_orphan(), GossipHello_npc_orphan_matron(), go_large_jack_o_lanternAI::JustDespawned(), npc_shade_of_the_horsemanAI::JustDied(), npc_shade_of_the_horsemanAI::JustRespawned(), npc_shade_of_the_horsemanAI::StartLanding(), npc_orphan_matronAI::SummonShadeOfTheHorseman(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), and npc_headless_horseman_fireAI::UpdateAI().
HandleGetData()
uint32 ShadeOfTheHorsemanData::HandleGetData (uint32 id) const
Definition at line 240 of file world_map_scripts.cpp.
References m_shadeOfTheHorsemanAttackPhases, and TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE.
Referenced by world_map_eastern_kingdoms::GetData(), world_map_kalimdor::GetData(), and world_map_outland::GetData().
HandleSetData()
void ShadeOfTheHorsemanData::HandleSetData (uint32 id, uint32 value)
Definition at line 245 of file world_map_scripts.cpp.
References m_shadeOfTheHorsemanAttackPhases, and TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE.
Referenced by world_map_eastern_kingdoms::SetData(), world_map_outland::SetData(), and world_map_kalimdor::SetData().
IsConditionFulfilled()
bool ShadeOfTheHorsemanData::IsConditionFulfilled (uint32 conditionId, uint32 areaId) const
Definition at line 182 of file world_map_scripts.cpp.
References AREAID_AZURE_WATCH, AREAID_BRILL, AREAID_FALCONWING_SQUARE, AREAID_GOLDSHIRE, AREAID_KHARANOS, AREAID_RAZOR_HILL, INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_AZURE_WATCH, INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_GOLDSHIRE, INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_KHARANOS, INSTANCE_CONDITION_ID_FIRE_TRAINING_BRILL, INSTANCE_CONDITION_ID_FIRE_TRAINING_FALCONWING, INSTANCE_CONDITION_ID_FIRE_TRAINING_RAZOR_HILL, INSTANCE_CONDITION_ID_LET_THE_FIRES_COME_ALLIANCE, INSTANCE_CONDITION_ID_LET_THE_FIRES_COME_HORDE, INSTANCE_CONDITION_ID_STOP_THE_FIRES_ALLIANCE, INSTANCE_CONDITION_ID_STOP_THE_FIRES_HORDE, INSTANCE_CONDITION_ID_THE_HEADLESS_HORSEMAN_ALLIANCE, INSTANCE_CONDITION_ID_THE_HEADLESS_HORSEMAN_HORDE, m_shadeOfTheHorsemanAttackPhases, SHADE_PHASE_ALL_CLEAR, SHADE_PHASE_SPAWNED, SHADE_PHASE_VICTORY, SHADE_VILLAGE_AZURE_WATCH, SHADE_VILLAGE_BRILL, SHADE_VILLAGE_FALCONWING_SQUARE, SHADE_VILLAGE_GOLDSHIRE, SHADE_VILLAGE_KHARANOS, and SHADE_VILLAGE_RAZOR_HILL.
Referenced by world_map_eastern_kingdoms::CheckConditionCriteriaMeet(), world_map_kalimdor::CheckConditionCriteriaMeet(), and world_map_outland::CheckConditionCriteriaMeet().
Reset()
void ShadeOfTheHorsemanData::Reset ()
Definition at line 167 of file world_map_scripts.cpp.
References m_shadeOfTheHorsemanAttackPhases.
Referenced by world_map_eastern_kingdoms::Initialize(), world_map_kalimdor::Initialize(), and world_map_outland::Initialize().
SetDataAttackPhase()
void ShadeOfTheHorsemanData::SetDataAttackPhase (uint32 id, uint32 value)
Definition at line 177 of file world_map_scripts.cpp.
References m_shadeOfTheHorsemanAttackPhases.
Field Documentation
m_areaIds
std::vector<uint32> ShadeOfTheHorsemanData::m_areaIds
Definition at line 100 of file world_map_scripts.h.
m_shadeOfTheHorsemanAttackPhases
uint32 ShadeOfTheHorsemanData::m_shadeOfTheHorsemanAttackPhases[MAX_VILLAGES]
Definition at line 86 of file world_map_scripts.h.
Referenced by GetDataAttackPhase(), HandleGetData(), HandleSetData(), IsConditionFulfilled(), Reset(), and SetDataAttackPhase().
The documentation for this struct was generated from the following files:
world_map_scripts.h
world_map_scripts.cpp