CMaNGOS_WoTLK: CharmInfo Struct Reference
CharmInfo Struct Reference
Game
#include <Unit.h>
Public Member Functions
CharmInfo (Unit *unit)
~CharmInfo ()
void SetCharmState (std::string const &ainame, bool withNewThreatList=true)
void SetCharmState (UnitAI *ai, bool withNewThreatList=true)
void ResetCharmState ()
uint32 GetPetNumber () const
void SetPetNumber (uint32 petnumber, bool statwindow)
uint32 GetPetLastAttackCommandTime () const
void SetPetLastAttackCommandTime (uint32 time)
void SetCommandState (CommandStates st)
CommandStates GetCommandState () const
bool HasCommandState (CommandStates state) const
void InitVehicleCreateSpells ()
void InitPossessCreateSpells ()
void InitCharmCreateSpells ()
void InitPetActionBar ()
void InitEmptyActionBar ()
void ProcessUnattackableTargets (CombatData *combatData)
bool AddSpellToActionBar (uint32 spellId, ActiveStates newstate=ACT_DECIDE, uint8 forceSlot=255)
bool RemoveSpellFromActionBar (uint32 spellId)
void LoadPetActionBar (const std::string &data)
void BuildActionBar (WorldPacket &data) const
void SetSpellAutocast (uint32 spell_id, bool state)
void SetActionBar (uint8 index, uint32 spellOrAction, ActiveStates type)
UnitActionBarEntry const * GetActionBarEntry (uint8 index) const
void ToggleCreatureAutocast (uint32 spellid, bool apply)
CharmSpellEntry * GetCharmSpell (uint8 index)
void SetIsRetreating (bool retreating=false)
bool GetIsRetreating () const
void ResetStayPosition ()
void SetStayPosition ()
bool UpdateStayPosition ()
float GetStayPosX () const
float GetStayPosY () const
float GetStayPosZ () const
float GetStayPosO () const
uint32 GetSpellOpener () const
uint32 GetSpellOpenerMinRange () const
uint32 GetSpellOpenerMaxRange () const
void SetSpellOpener (uint32 spellId=0, uint32 minRange=0, uint32 maxRange=0)
UnitAI * GetAI () const
CombatData * GetCombatData () const
void SetCharmStartPosition (Position const &position)
Position const & GetCharmStartPosition ()
void SetWalk (bool walk)
bool GetWalk () const
Unit * GetUnit ()
Private Attributes
Unit * m_unit
UnitAI * m_ai
CombatData * m_combatData
UnitActionBarEntry PetActionBar [MAX_UNIT_ACTION_BAR_INDEX]
CharmSpellEntry m_charmspells [CREATURE_MAX_SPELLS]
CommandStates m_CommandState
uint32 m_petnumber
uint32 m_petLastAttackCommandTime
uint32 m_opener
uint32 m_openerMinRange
uint32 m_openerMaxRange
uint32 m_unitFieldFlags
uint8 m_unitFieldBytes2_1
bool m_retreating
bool m_stayPosSet
float m_stayPosX
float m_stayPosY
float m_stayPosZ
float m_stayPosO
Position m_charmStartPosition
bool m_walk
bool m_deleted
Detailed Description
Definition at line 937 of file Unit.h.
Constructor & Destructor Documentation
CharmInfo()
CharmInfo::CharmInfo (Unit * unit) explicit
Definition at line 11543 of file Unit.cpp.
References ACT_DISABLED, and m_charmspells.
~CharmInfo()
CharmInfo::~CharmInfo ()
Definition at line 11555 of file Unit.cpp.
References m_ai, m_combatData, and m_deleted.
Member Function Documentation
AddSpellToActionBar()
bool CharmInfo::AddSpellToActionBar (uint32 spellId, ActiveStates newstate = ACT_DECIDE, uint8 forceSlot = 255)
Definition at line 11765 of file Unit.cpp.
References ACT_DECIDE, ACT_DISABLED, ACT_PASSIVE, IsAutocastable(), MAX_UNIT_ACTION_BAR_INDEX, PetActionBar, SetActionBar(), and sSpellMgr.
Referenced by Pet::addSpell(), InitCharmCreateSpells(), InitPossessCreateSpells(), and InitVehicleCreateSpells().
BuildActionBar()
void CharmInfo::BuildActionBar (WorldPacket & data) const
Definition at line 11896 of file Unit.cpp.
References PetActionBar.
Referenced by Player::CharmSpellInitialize(), Player::PetSpellInitialize(), Player::PossessSpellInitialize(), and Player::VehicleSpellInitialize().
GetActionBarEntry()
UnitActionBarEntry const* CharmInfo::GetActionBarEntry (uint8 index) const inline
Definition at line 972 of file Unit.h.
References PetActionBar.
Referenced by Pet::CleanupActionBar(), WorldSession::HandlePetSetAction(), Pet::InitializeSpellsForControllableGuardian(), and Pet::SavePetToDB().
GetAI()
UnitAI* CharmInfo::GetAI () const inline
Definition at line 1001 of file Unit.h.
References m_ai.
Referenced by Creature::AI(), Pet::AI(), and Player::AI().
GetCharmSpell()
CharmSpellEntry* CharmInfo::GetCharmSpell (uint8 index) inline
Definition at line 976 of file Unit.h.
References m_charmspells.
Referenced by Player::CharmSpellInitialize(), and Creature::GetPetAutoSpellOnPos().
GetCharmStartPosition()
Position const& CharmInfo::GetCharmStartPosition () inline
Definition at line 1005 of file Unit.h.
References m_charmStartPosition.
Referenced by Unit::Uncharm().
GetCombatData()
CombatData* CharmInfo::GetCombatData () const inline
Definition at line 1002 of file Unit.h.
References m_combatData.
Referenced by Creature::GetCombatData(), and Player::GetCombatData().
GetCommandState()
CommandStates CharmInfo::GetCommandState () const inline
Definition at line 952 of file Unit.h.
References m_CommandState.
Referenced by Player::CharmSpellInitialize(), Player::PetSpellInitialize(), and Player::VehicleSpellInitialize().
GetIsRetreating()
bool CharmInfo::GetIsRetreating () const inline
Definition at line 979 of file Unit.h.
References m_retreating.
Referenced by PetAI::AttackedBy(), and PetAI::UpdateAI().
GetPetLastAttackCommandTime()
uint32 CharmInfo::GetPetLastAttackCommandTime () const inline
Definition at line 948 of file Unit.h.
References m_petLastAttackCommandTime.
Referenced by PetAI::UpdateAI().
GetPetNumber()
uint32 CharmInfo::GetPetNumber () const inline
Definition at line 946 of file Unit.h.
References m_petnumber.
Referenced by Pet::_LoadAuras(), Pet::_LoadSpellCooldowns(), Pet::_LoadSpells(), Pet::_SaveAuras(), Pet::_SaveSpellCooldowns(), Pet::_SaveSpells(), WorldSession::HandlePetRename(), Pet::resetTalentsForAllPetsOf(), Pet::SavePetToDB(), WorldSession::SendStablePet(), Pet::Unsummon(), and Player::UnsummonPetTemporaryIfAny().
GetSpellOpener()
uint32 CharmInfo::GetSpellOpener () const inline
Definition at line 990 of file Unit.h.
References m_opener.
Referenced by PetAI::UpdateAI().
GetSpellOpenerMaxRange()
uint32 CharmInfo::GetSpellOpenerMaxRange () const inline
Definition at line 992 of file Unit.h.
References m_openerMaxRange.
Referenced by PetAI::UpdateAI().
GetSpellOpenerMinRange()
uint32 CharmInfo::GetSpellOpenerMinRange () const inline
Definition at line 991 of file Unit.h.
References m_openerMinRange.
Referenced by PetAI::UpdateAI().
GetStayPosO()
float CharmInfo::GetStayPosO () const inline
Definition at line 988 of file Unit.h.
References m_stayPosO.
Referenced by PetAI::UpdateAI().
GetStayPosX()
float CharmInfo::GetStayPosX () const inline
Definition at line 985 of file Unit.h.
References m_stayPosX.
Referenced by PetAI::UpdateAI().
GetStayPosY()
float CharmInfo::GetStayPosY () const inline
Definition at line 986 of file Unit.h.
References m_stayPosY.
Referenced by PetAI::UpdateAI().
GetStayPosZ()
float CharmInfo::GetStayPosZ () const inline
Definition at line 987 of file Unit.h.
References m_stayPosZ.
Referenced by PetAI::UpdateAI().
GetUnit()
Unit* CharmInfo::GetUnit () inline
Definition at line 1010 of file Unit.h.
References m_unit.
Referenced by Unit::TakeCharmOf().
GetWalk()
bool CharmInfo::GetWalk () const inline
Definition at line 1008 of file Unit.h.
References m_walk.
Referenced by ResetCharmState().
HasCommandState()
bool CharmInfo::HasCommandState (CommandStates state) const inline
Definition at line 953 of file Unit.h.
References m_CommandState.
Referenced by ScriptedPetAI::ResetPetCombat(), PetAI::UpdateAI(), ScriptedPetAI::UpdateAI(), npc_scrap_reaverAI::UpdateAI(), and npc_living_flareAI::UpdateAI().
InitCharmCreateSpells()
void CharmInfo::InitCharmCreateSpells ()
Definition at line 11713 of file Unit.cpp.
References ACT_COMMAND, ACT_DISABLED, ACT_ENABLED, ACT_PASSIVE, ACTION_BAR_INDEX_START, AddSpellToActionBar(), Unit::CastSpell(), COMMAND_ATTACK, CREATURE_MAX_SPELLS, SpellEntry::EffectImplicitTargetA, Unit::GetCharmSpells(), SpellEntry::HasAttribute(), InitPetActionBar(), IsAutocastable(), IsPassiveSpell(), Object::IsPlayer(), SQLStorage::LookupEntry(), m_charmspells, m_unit, UnitActionBarEntry::SetActionAndType(), SetActionBar(), SPELL_ATTR_EX5_NOT_AVAILABLE_WHILE_CHARMED, sSpellTemplate, TARGET_UNIT_CASTER, and TRIGGERED_OLD_TRIGGERED.
Referenced by Unit::TakeCharmOf().
InitEmptyActionBar()
void CharmInfo::InitEmptyActionBar ()
Definition at line 11625 of file Unit.cpp.
References ACT_PASSIVE, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_START, and SetActionBar().
Referenced by InitPossessCreateSpells(), and InitVehicleCreateSpells().
InitPetActionBar()
void CharmInfo::InitPetActionBar ()
Definition at line 11610 of file Unit.cpp.
References ACT_COMMAND, ACT_DISABLED, ACT_REACTION, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_PET_SPELL_END, ACTION_BAR_INDEX_PET_SPELL_START, ACTION_BAR_INDEX_START, COMMAND_ATTACK, and SetActionBar().
Referenced by InitCharmCreateSpells(), Pet::InitializeSpellsForControllableGuardian(), Pet::InitPetCreateSpells(), and LoadPetActionBar().
InitPossessCreateSpells()
void CharmInfo::InitPossessCreateSpells ()
Definition at line 11691 of file Unit.cpp.
References ACT_COMMAND, ACT_PASSIVE, AddSpellToActionBar(), Unit::CastSpell(), COMMAND_ATTACK, CREATURE_MAX_SPELLS, Unit::GetCharmSpells(), SpellEntry::HasAttribute(), Unit::hasUnitState(), InitEmptyActionBar(), IsPassiveSpell(), Object::IsPlayer(), SQLStorage::LookupEntry(), m_unit, SetActionBar(), SPELL_ATTR_EX5_NOT_AVAILABLE_WHILE_CHARMED, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, and UNIT_STAT_MELEE_ATTACKING.
Referenced by ShivanShapeshiftForm::OnApply(), Unit::TakeCharmOf(), and Unit::TakePossessOf().
InitVehicleCreateSpells()
void CharmInfo::InitVehicleCreateSpells ()
Definition at line 11631 of file Unit.cpp.
References AddSpellToActionBar(), Unit::CastSpell(), CREATURE_MAX_SPELLS, Unit::GetCharmSpells(), Object::GetTypeId(), InitEmptyActionBar(), IsPassiveSpell(), m_unit, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
Referenced by VehicleInfo::ApplySeatMods().
LoadPetActionBar()
void CharmInfo::LoadPetActionBar (const std::string & data)
Definition at line 11864 of file Unit.cpp.
References ACT_DISABLED, ACT_PASSIVE, ACTION_BAR_INDEX_END, ACTION_BAR_INDEX_START, UnitActionBarEntry::GetAction(), InitPetActionBar(), IsAutocastable(), SQLStorage::LookupEntry(), PetActionBar, UnitActionBarEntry::SetActionAndType(), SetActionBar(), sSpellTemplate, and StrSplit().
Referenced by Pet::LoadPetFromDB().
ProcessUnattackableTargets()
void CharmInfo::ProcessUnattackableTargets (CombatData * combatData)
Definition at line 11648 of file Unit.cpp.
References Unit::AttackStop(), RefManager< TO, FROM >::begin(), Unit::CanAttack(), RefManager< TO, FROM >::end(), ThreatManager::getThreatList(), Object::GetTypeId(), CombatData::hostileRefManager, m_unit, CombatData::threatManager, and TYPEID_UNIT.
Referenced by Unit::TakeCharmOf(), and Unit::TakePossessOf().
RemoveSpellFromActionBar()
bool CharmInfo::RemoveSpellFromActionBar (uint32 spellId)
Definition at line 11804 of file Unit.cpp.
References ACT_DISABLED, MAX_UNIT_ACTION_BAR_INDEX, PetActionBar, SetActionBar(), and sSpellMgr.
Referenced by Pet::removeSpell().
ResetCharmState()
void CharmInfo::ResetCharmState ()
Definition at line 11582 of file Unit.cpp.
References GetWalk(), Object::IsCreature(), m_unit, m_unitFieldBytes2_1, m_unitFieldFlags, Object::RemoveFlag(), Object::SetByteValue(), Object::SetFlag(), SetWalk(), UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_PET_IN_COMBAT, and UNIT_FLAG_PLAYER_CONTROLLED.
Referenced by Unit::Uncharm().
ResetStayPosition()
void CharmInfo::ResetStayPosition ()
Definition at line 11914 of file Unit.cpp.
References m_stayPosO, m_stayPosSet, m_stayPosX, m_stayPosY, and m_stayPosZ.
Referenced by WorldSession::HandlePetActionHelper(), and SetCommandState().
SetActionBar()
void CharmInfo::SetActionBar (uint8 index, uint32 spellOrAction, ActiveStates type) inline
Definition at line 968 of file Unit.h.
References PetActionBar, and UnitActionBarEntry::SetActionAndType().
Referenced by AddSpellToActionBar(), Pet::CleanupActionBar(), WorldSession::HandlePetSetAction(), InitCharmCreateSpells(), InitEmptyActionBar(), Pet::InitializeSpellsForControllableGuardian(), InitPetActionBar(), InitPossessCreateSpells(), LoadPetActionBar(), and RemoveSpellFromActionBar().
SetCharmStartPosition()
void CharmInfo::SetCharmStartPosition (Position const & position) inline
Definition at line 1004 of file Unit.h.
References m_charmStartPosition.
Referenced by Unit::TakeCharmOf(), and Unit::TakePossessOf().
SetCharmState() [1/2]
void CharmInfo::SetCharmState (std::string const & ainame, bool withNewThreatList = true)
Definition at line 11562 of file Unit.cpp.
References FactorySelector::GetSpecificAI(), and m_unit.
Referenced by Unit::TakeCharmOf(), and Unit::TakePossessOf().
SetCharmState() [2/2]
void CharmInfo::SetCharmState (UnitAI * ai, bool withNewThreatList = true)
Definition at line 11567 of file Unit.cpp.
References Object::GetByteValue(), Object::GetUInt32Value(), Unit::IsWalking(), m_ai, m_combatData, m_unit, m_unitFieldBytes2_1, m_unitFieldFlags, SetWalk(), UNIT_BYTES_2_OFFSET_PVP_FLAG, UNIT_FIELD_BYTES_2, and UNIT_FIELD_FLAGS.
SetCommandState()
void CharmInfo::SetCommandState (CommandStates st)
Definition at line 11842 of file Unit.cpp.
References COMMAND_FOLLOW, COMMAND_STAY, m_CommandState, ResetStayPosition(), SetIsRetreating(), and SetSpellOpener().
Referenced by WorldSession::HandlePetAction(), WorldSession::HandlePetActionHelper(), Unit::TakeCharmOf(), and Unit::TakePossessOf().
SetIsRetreating()
void CharmInfo::SetIsRetreating (bool retreating = false) inline
Definition at line 978 of file Unit.h.
References m_retreating.
Referenced by WorldSession::HandlePetActionHelper(), SetCommandState(), Unit::TakeCharmOf(), and PetAI::UpdateAI().
SetPetLastAttackCommandTime()
void CharmInfo::SetPetLastAttackCommandTime (uint32 time) inline
Definition at line 949 of file Unit.h.
References m_petLastAttackCommandTime.
Referenced by WorldSession::HandlePetActionHelper().
SetPetNumber()
void CharmInfo::SetPetNumber (uint32 petnumber, bool statwindow)
Definition at line 11833 of file Unit.cpp.
References m_petnumber, m_unit, Object::SetUInt32Value(), and UNIT_FIELD_PETNUMBER.
Referenced by Pet::_LoadGuardianPetNumber(), Spell::EffectCreateTamedPet(), Spell::EffectSummonPet(), Spell::EffectTameCreature(), and Pet::LoadPetFromDB().
SetSpellAutocast()
void CharmInfo::SetSpellAutocast (uint32 spell_id, bool state)
Definition at line 11902 of file Unit.cpp.
References ACT_DISABLED, ACT_ENABLED, and PetActionBar.
Referenced by WorldSession::HandlePetSpellAutocastOpcode().
SetSpellOpener()
void CharmInfo::SetSpellOpener (uint32 spellId = 0, uint32 minRange = 0, uint32 maxRange = 0) inline
Definition at line 994 of file Unit.h.
References m_opener, m_openerMaxRange, and m_openerMinRange.
Referenced by WorldSession::HandlePetActionHelper(), SetCommandState(), and PetAI::UpdateAI().
SetStayPosition()
void CharmInfo::SetStayPosition ()
Definition at line 11923 of file Unit.cpp.
References Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::Finalized(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), WorldObject::GetTransport(), m_stayPosO, m_stayPosSet, m_stayPosX, m_stayPosY, m_stayPosZ, m_unit, Unit::movespline, and Movement::Location::orientation.
Referenced by UpdateStayPosition().
SetWalk()
void CharmInfo::SetWalk (bool walk) inline
Definition at line 1007 of file Unit.h.
References m_walk.
Referenced by ResetCharmState(), and SetCharmState().
ToggleCreatureAutocast()
void CharmInfo::ToggleCreatureAutocast (uint32 spellid, bool apply)
Definition at line 11823 of file Unit.cpp.
References ACT_DISABLED, ACT_ENABLED, ByteConverter::apply(), IsPassiveSpell(), and m_charmspells.
Referenced by WorldSession::HandlePetSetAction(), and WorldSession::HandlePetSpellAutocastOpcode().
UpdateStayPosition()
bool CharmInfo::UpdateStayPosition ()
Definition at line 11945 of file Unit.cpp.
References m_stayPosSet, and SetStayPosition().
Referenced by PetAI::UpdateAI().
Field Documentation
m_ai
UnitAI* CharmInfo::m_ai private
Definition at line 1014 of file Unit.h.
Referenced by GetAI(), SetCharmState(), and ~CharmInfo().
m_charmspells
CharmSpellEntry CharmInfo::m_charmspells[CREATURE_MAX_SPELLS] private
Definition at line 1017 of file Unit.h.
Referenced by CharmInfo(), GetCharmSpell(), InitCharmCreateSpells(), and ToggleCreatureAutocast().
m_charmStartPosition
Position CharmInfo::m_charmStartPosition private
Definition at line 1033 of file Unit.h.
Referenced by GetCharmStartPosition(), and SetCharmStartPosition().
m_combatData
CombatData* CharmInfo::m_combatData private
Definition at line 1015 of file Unit.h.
Referenced by GetCombatData(), SetCharmState(), and ~CharmInfo().
m_CommandState
CommandStates CharmInfo::m_CommandState private
Definition at line 1018 of file Unit.h.
Referenced by GetCommandState(), HasCommandState(), and SetCommandState().
m_deleted
bool CharmInfo::m_deleted private
Definition at line 1036 of file Unit.h.
Referenced by ~CharmInfo().
m_opener
uint32 CharmInfo::m_opener private
Definition at line 1021 of file Unit.h.
Referenced by GetSpellOpener(), and SetSpellOpener().
m_openerMaxRange
uint32 CharmInfo::m_openerMaxRange private
Definition at line 1023 of file Unit.h.
Referenced by GetSpellOpenerMaxRange(), and SetSpellOpener().
m_openerMinRange
uint32 CharmInfo::m_openerMinRange private
Definition at line 1022 of file Unit.h.
Referenced by GetSpellOpenerMinRange(), and SetSpellOpener().
m_petLastAttackCommandTime
uint32 CharmInfo::m_petLastAttackCommandTime private
Definition at line 1020 of file Unit.h.
Referenced by GetPetLastAttackCommandTime(), and SetPetLastAttackCommandTime().
m_petnumber
uint32 CharmInfo::m_petnumber private
Definition at line 1019 of file Unit.h.
Referenced by GetPetNumber(), and SetPetNumber().
m_retreating
bool CharmInfo::m_retreating private
Definition at line 1026 of file Unit.h.
Referenced by GetIsRetreating(), and SetIsRetreating().
m_stayPosO
float CharmInfo::m_stayPosO private
Definition at line 1031 of file Unit.h.
Referenced by GetStayPosO(), ResetStayPosition(), and SetStayPosition().
m_stayPosSet
bool CharmInfo::m_stayPosSet private
Definition at line 1027 of file Unit.h.
Referenced by ResetStayPosition(), SetStayPosition(), and UpdateStayPosition().
m_stayPosX
float CharmInfo::m_stayPosX private
Definition at line 1028 of file Unit.h.
Referenced by GetStayPosX(), ResetStayPosition(), and SetStayPosition().
m_stayPosY
float CharmInfo::m_stayPosY private
Definition at line 1029 of file Unit.h.
Referenced by GetStayPosY(), ResetStayPosition(), and SetStayPosition().
m_stayPosZ
float CharmInfo::m_stayPosZ private
Definition at line 1030 of file Unit.h.
Referenced by GetStayPosZ(), ResetStayPosition(), and SetStayPosition().
m_unit
Unit* CharmInfo::m_unit private
Definition at line 1013 of file Unit.h.
Referenced by GetUnit(), InitCharmCreateSpells(), InitPossessCreateSpells(), InitVehicleCreateSpells(), ProcessUnattackableTargets(), ResetCharmState(), SetCharmState(), SetPetNumber(), and SetStayPosition().
m_unitFieldBytes2_1
uint8 CharmInfo::m_unitFieldBytes2_1 private
Definition at line 1025 of file Unit.h.
Referenced by ResetCharmState(), and SetCharmState().
m_unitFieldFlags
uint32 CharmInfo::m_unitFieldFlags private
Definition at line 1024 of file Unit.h.
Referenced by ResetCharmState(), and SetCharmState().
m_walk
bool CharmInfo::m_walk private
Definition at line 1034 of file Unit.h.
Referenced by GetWalk(), and SetWalk().
PetActionBar
UnitActionBarEntry CharmInfo::PetActionBar[MAX_UNIT_ACTION_BAR_INDEX] private
Definition at line 1016 of file Unit.h.
Referenced by AddSpellToActionBar(), BuildActionBar(), GetActionBarEntry(), LoadPetActionBar(), RemoveSpellFromActionBar(), SetActionBar(), and SetSpellAutocast().
The documentation for this struct was generated from the following files:
Unit.h
Unit.cpp