CMaNGOS_WoTLK: AchievementCriteriaRequirement Struct Reference
AchievementCriteriaRequirement Struct Reference
#include <AchievementMgr.h>
Public Member Functions
AchievementCriteriaRequirement ()
AchievementCriteriaRequirement (uint32 reqType, uint32 _value1, uint32 _value2)
bool IsValid (AchievementCriteriaEntry const *criteria) const
bool Meets (uint32 criteria_id, Player const *source, Unit const *target, uint32 miscvalue1=0) const
Data Fields
AchievementCriteriaRequirementType requirementType
union {
struct {
uint32 id
} creature
struct {
uint32 class_id
uint32 race_id
} classRace
struct {
uint32 percent
} health
struct {
uint32 own_team_flag
} player_dead
struct {
uint32 spell_id
uint32 effect_idx
} aura
struct {
uint32 id
} area
struct {
uint32 minvalue
} value
struct {
uint32 minlevel
} level
struct {
uint32 gender
} gender
struct {
uint32 difficulty
} difficulty
struct {
uint32 maxcount
} map_players
struct {
uint32 team
} team
struct {
uint32 state
} drunk
struct {
uint32 id
} holiday
struct {
uint32 min_score
uint32 max_score
} bg_loss_team_score
struct {
uint32 item_level
uint32 item_quality
} equipped_item
struct {
uint32 nth_birthday
} birthday_login
struct {
uint32 title_id
} known_title
struct {
uint32 creatureType
uint32 customCond
} creatureType
struct {
uint32 mapId
} mapId
struct {
uint32 conditionEntry
} worldStateCondition
struct {
uint32 value1
uint32 value2
} raw
};
Detailed Description
Definition at line 81 of file AchievementMgr.h.
Constructor & Destructor Documentation
AchievementCriteriaRequirement() [1/2]
AchievementCriteriaRequirement::AchievementCriteriaRequirement () inline
Definition at line 208 of file AchievementMgr.h.
References raw.
AchievementCriteriaRequirement() [2/2]
AchievementCriteriaRequirement::AchievementCriteriaRequirement (uint32 reqType, uint32 _value1, uint32 _value2) inline
Definition at line 214 of file AchievementMgr.h.
References raw.
Member Function Documentation
IsValid()
bool AchievementCriteriaRequirement::IsValid (AchievementCriteriaEntry const * criteria) const
Definition at line 73 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_REQUIRE_DISABLED, ACHIEVEMENT_CRITERIA_REQUIRE_HOLIDAY, ACHIEVEMENT_CRITERIA_REQUIRE_INSTANCE_SCRIPT, ACHIEVEMENT_CRITERIA_REQUIRE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_REQUIRE_KNOWN_TITLE, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_DIFFICULTY, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_ID, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_PLAYER_COUNT, ACHIEVEMENT_CRITERIA_REQUIRE_NONE, ACHIEVEMENT_CRITERIA_REQUIRE_NTH_BIRTHDAY, ACHIEVEMENT_CRITERIA_REQUIRE_PVP_SCRIPT, ACHIEVEMENT_CRITERIA_REQUIRE_S_AREA, ACHIEVEMENT_CRITERIA_REQUIRE_S_AURA, ACHIEVEMENT_CRITERIA_REQUIRE_S_DRUNK, ACHIEVEMENT_CRITERIA_REQUIRE_S_EQUIPPED_ITEM_LVL, ACHIEVEMENT_CRITERIA_REQUIRE_T_AURA, ACHIEVEMENT_CRITERIA_REQUIRE_T_CREATURE, ACHIEVEMENT_CRITERIA_REQUIRE_T_GENDER, ACHIEVEMENT_CRITERIA_REQUIRE_T_LEVEL, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_CLASS_RACE, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_DEAD, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_LESS_HEALTH, ACHIEVEMENT_CRITERIA_REQUIRE_T_TEAM, ACHIEVEMENT_CRITERIA_REQUIRE_VALUE, ACHIEVEMENT_CRITERIA_REQUIRE_WORLDSTATE_CONDITION, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET, ACHIEVEMENT_CRITERIA_TYPE_BE_SPELL_TARGET2, ACHIEVEMENT_CRITERIA_TYPE_BG_OBJECTIVE_CAPTURE, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL, ACHIEVEMENT_CRITERIA_TYPE_CAST_SPELL2, ACHIEVEMENT_CRITERIA_TYPE_COMPLETE_QUEST, ACHIEVEMENT_CRITERIA_TYPE_DO_EMOTE, ACHIEVEMENT_CRITERIA_TYPE_EQUIP_EPIC_ITEM, ACHIEVEMENT_CRITERIA_TYPE_FALL_WITHOUT_DYING, ACHIEVEMENT_CRITERIA_TYPE_GET_KILLING_BLOWS, ACHIEVEMENT_CRITERIA_TYPE_HONORABLE_KILL, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE, ACHIEVEMENT_CRITERIA_TYPE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_TYPE_LOOT_TYPE, ACHIEVEMENT_CRITERIA_TYPE_ON_LOGIN, ACHIEVEMENT_CRITERIA_TYPE_SPECIAL_PVP_KILL, ACHIEVEMENT_CRITERIA_TYPE_USE_ITEM, ACHIEVEMENT_CRITERIA_TYPE_WIN_BG, ACHIEVEMENT_CRITERIA_TYPE_WIN_DUEL, ACHIEVEMENT_CRITERIA_TYPE_WIN_RATED_ARENA, ALLIANCE, area, aura, CLASSMASK_ALL_PLAYABLE, classRace, creature, CREATURE_TYPE_GAS_CLOUD, creatureType, difficulty, drunk, SpellEntry::EffectApplyAuraName, equipped_item, gender, GENDER_NONE, GetAreaEntryByAreaID(), ObjectMgr::GetCreatureTemplate(), health, holiday, HORDE, AchievementCriteriaEntry::ID, known_title, level, SQLStorage::LookupEntry(), map_players, mapId, MAX_DIFFICULTY, MAX_DRUNKEN, MAX_EFFECT_INDEX, MAX_ITEM_QUALITY, player_dead, RACEMASK_ALL_PLAYABLE, AchievementCriteriaEntry::requiredType, requirementType, sCharTitlesStore, sConditionStorage, sHolidaysStore, sLog, sMapStore, sSpellTemplate, STRONG_MAX_LEVEL, team, and worldStateCondition.
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaRequirements().
Meets()
bool AchievementCriteriaRequirement::Meets (uint32 criteria_id, Player const * source, Unit const * target, uint32 miscvalue1 = 0) const
Definition at line 300 of file AchievementMgr.cpp.
References ACHIEVEMENT_CRITERIA_REQUIRE_DISABLED, ACHIEVEMENT_CRITERIA_REQUIRE_HOLIDAY, ACHIEVEMENT_CRITERIA_REQUIRE_INSTANCE_SCRIPT, ACHIEVEMENT_CRITERIA_REQUIRE_KILL_CREATURE_TYPE, ACHIEVEMENT_CRITERIA_REQUIRE_KNOWN_TITLE, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_DIFFICULTY, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_ID, ACHIEVEMENT_CRITERIA_REQUIRE_MAP_PLAYER_COUNT, ACHIEVEMENT_CRITERIA_REQUIRE_NONE, ACHIEVEMENT_CRITERIA_REQUIRE_NTH_BIRTHDAY, ACHIEVEMENT_CRITERIA_REQUIRE_PVP_SCRIPT, ACHIEVEMENT_CRITERIA_REQUIRE_S_AREA, ACHIEVEMENT_CRITERIA_REQUIRE_S_AURA, ACHIEVEMENT_CRITERIA_REQUIRE_S_DRUNK, ACHIEVEMENT_CRITERIA_REQUIRE_S_EQUIPPED_ITEM_LVL, ACHIEVEMENT_CRITERIA_REQUIRE_T_AURA, ACHIEVEMENT_CRITERIA_REQUIRE_T_CREATURE, ACHIEVEMENT_CRITERIA_REQUIRE_T_GENDER, ACHIEVEMENT_CRITERIA_REQUIRE_T_LEVEL, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_CLASS_RACE, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_DEAD, ACHIEVEMENT_CRITERIA_REQUIRE_T_PLAYER_LESS_HEALTH, ACHIEVEMENT_CRITERIA_REQUIRE_T_TEAM, ACHIEVEMENT_CRITERIA_REQUIRE_VALUE, ACHIEVEMENT_CRITERIA_REQUIRE_WORLDSTATE_CONDITION, area, aura, birthday_login, InstanceData::CheckAchievementCriteriaMeet(), classRace, CONDITION_FROM_WORLDSTATE, CONFIG_UINT32_BIRTHDAY_TIME, creature, creatureType, difficulty, drunk, equipped_item, gender, Player::GetBattleGround(), Player::GetCachedZoneId(), Player::GetDrunkenstateByValue(), Player::GetDrunkValue(), Object::GetEntry(), Unit::getGender(), Unit::GetHealth(), WorldObject::GetInstanceData(), Player::GetItemByPos(), Unit::GetLevel(), WorldObject::GetMap(), WorldObject::GetMapId(), Unit::GetMaxHealth(), Map::GetPlayersCountExceptGMs(), Item::GetProto(), Map::GetSpawnMode(), Player::GetTeam(), Object::GetTypeId(), WorldObject::GetZoneAndAreaId(), Unit::HasAura(), Player::HasTitle(), health, holiday, Player::InBattleGround(), INVENTORY_SLOT_BAG_0, Unit::IsAlive(), IsConditionSatisfied(), Object::IsInWorld(), Unit::IsTrivialForTarget(), ItemPrototype::ItemLevel, known_title, level, map_players, mapId, player_dead, ItemPrototype::Quality, requirementType, sCharTitlesStore, sGameEventMgr, sLog, sOutdoorPvPMgr, sWorld, team, TYPEID_PLAYER, TYPEID_UNIT, value, and worldStateCondition.
Field Documentation
union { ... }
struct { ... } AchievementCriteriaRequirement::area
Referenced by IsValid(), and Meets().
struct { ... } AchievementCriteriaRequirement::aura
Referenced by IsValid(), and Meets().
struct { ... } AchievementCriteriaRequirement::bg_loss_team_score
struct { ... } AchievementCriteriaRequirement::birthday_login
Referenced by Meets().
class_id
uint32 AchievementCriteriaRequirement::class_id
Definition at line 95 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::classRace
Referenced by IsValid(), and Meets().
conditionEntry
uint32 AchievementCriteriaRequirement::conditionEntry
Definition at line 198 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::creature
Referenced by IsValid(), and Meets().
creatureType [1/2]
uint32 AchievementCriteriaRequirement::creatureType
Definition at line 187 of file AchievementMgr.h.
Referenced by IsValid(), and Meets().
[2/2]
struct { ... } AchievementCriteriaRequirement::creatureType
customCond
uint32 AchievementCriteriaRequirement::customCond
Definition at line 188 of file AchievementMgr.h.
difficulty [1/2]
uint32 AchievementCriteriaRequirement::difficulty
Definition at line 139 of file AchievementMgr.h.
Referenced by IsValid(), and Meets().
[2/2]
struct { ... } AchievementCriteriaRequirement::difficulty
struct { ... } AchievementCriteriaRequirement::drunk
Referenced by IsValid(), and Meets().
effect_idx
uint32 AchievementCriteriaRequirement::effect_idx
Definition at line 113 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::equipped_item
Referenced by IsValid(), and Meets().
gender [1/2]
uint32 AchievementCriteriaRequirement::gender
Definition at line 133 of file AchievementMgr.h.
Referenced by IsValid(), and Meets().
[2/2]
struct { ... } AchievementCriteriaRequirement::gender
struct { ... } AchievementCriteriaRequirement::health
Referenced by IsValid(), and Meets().
struct { ... } AchievementCriteriaRequirement::holiday
Referenced by IsValid(), and Meets().
id
uint32 AchievementCriteriaRequirement::id
Definition at line 90 of file AchievementMgr.h.
item_level
uint32 AchievementCriteriaRequirement::item_level
Definition at line 171 of file AchievementMgr.h.
item_quality
uint32 AchievementCriteriaRequirement::item_quality
Definition at line 172 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::known_title
Referenced by IsValid(), and Meets().
struct { ... } AchievementCriteriaRequirement::level
Referenced by IsValid(), and Meets().
struct { ... } AchievementCriteriaRequirement::map_players
Referenced by IsValid(), and Meets().
mapId [1/2]
uint32 AchievementCriteriaRequirement::mapId
Definition at line 193 of file AchievementMgr.h.
Referenced by IsValid(), and Meets().
[2/2]
struct { ... } AchievementCriteriaRequirement::mapId
max_score
uint32 AchievementCriteriaRequirement::max_score
Definition at line 165 of file AchievementMgr.h.
maxcount
uint32 AchievementCriteriaRequirement::maxcount
Definition at line 144 of file AchievementMgr.h.
min_score
uint32 AchievementCriteriaRequirement::min_score
Definition at line 164 of file AchievementMgr.h.
minlevel
uint32 AchievementCriteriaRequirement::minlevel
Definition at line 128 of file AchievementMgr.h.
minvalue
uint32 AchievementCriteriaRequirement::minvalue
Definition at line 123 of file AchievementMgr.h.
nth_birthday
uint32 AchievementCriteriaRequirement::nth_birthday
Definition at line 177 of file AchievementMgr.h.
own_team_flag
uint32 AchievementCriteriaRequirement::own_team_flag
Definition at line 106 of file AchievementMgr.h.
percent
uint32 AchievementCriteriaRequirement::percent
Definition at line 101 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::player_dead
Referenced by IsValid(), and Meets().
race_id
uint32 AchievementCriteriaRequirement::race_id
Definition at line 96 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::raw
Referenced by AchievementCriteriaRequirement().
requirementType
AchievementCriteriaRequirementType AchievementCriteriaRequirement::requirementType
Definition at line 83 of file AchievementMgr.h.
Referenced by IsValid(), AchievementGlobalMgr::LoadAchievementCriteriaRequirements(), and Meets().
spell_id
uint32 AchievementCriteriaRequirement::spell_id
Definition at line 112 of file AchievementMgr.h.
state
uint32 AchievementCriteriaRequirement::state
Definition at line 154 of file AchievementMgr.h.
team [1/2]
uint32 AchievementCriteriaRequirement::team
Definition at line 149 of file AchievementMgr.h.
Referenced by IsValid(), and Meets().
[2/2]
struct { ... } AchievementCriteriaRequirement::team
title_id
uint32 AchievementCriteriaRequirement::title_id
Definition at line 182 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::value
Referenced by Meets().
value1
uint32 AchievementCriteriaRequirement::value1
Definition at line 203 of file AchievementMgr.h.
value2
uint32 AchievementCriteriaRequirement::value2
Definition at line 204 of file AchievementMgr.h.
struct { ... } AchievementCriteriaRequirement::worldStateCondition
Referenced by IsValid(), and Meets().
The documentation for this struct was generated from the following files:
AchievementMgr.h
AchievementMgr.cpp