CMaNGOS_WoTLK: boss_freyaAI Struct Reference
boss_freyaAI Struct Reference
Public Member Functions
boss_freyaAI (Creature *pCreature)
void Reset () override
void Aggro (Unit *) override
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void AttackStart (Unit *pWho) override
== Triggered Actions Requested ==================
void MoveInLineOfSight (Unit *pWho) override
== Reactions At =================================
void JustReachedHome () override
Called at reaching home after MoveTargetedHome.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void DamageTaken (Unit *, uint32 &uiDamage, DamageEffectType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
void KilledUnit (Unit *pVictim) override
Called when the creature kills a unit.
void JustSummoned (Creature *pSummoned) override
Called when the creature summon successfully other creature.
void SummonedCreatureJustDied (Creature *pSummoned) override
Called when a summoned creature is killed.
void ReceiveAIEvent (AIEventType eventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
void FetchElders ()
void DoDrainElders ()
void UpdateAI (const uint32 uiDiff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void JustDied (Unit *)
Called when the creature is killed.
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Data Fields
instance_ulduar * m_pInstance
bool m_bIsRegularMode
bool m_bEventFinished
bool m_bDeforestationComplete
uint32 m_uiEpilogueTimer
uint32 m_uiBerserkTimer
uint32 m_uiDrainEldersTimer
uint32 m_uiAlliesNatureTimer
uint8 m_uiAlliesWaveCount
uint32 m_uiSunbeamTimer
uint32 m_uiNatureBombTimer
uint32 m_uiLifebindersGiftTimer
uint32 m_uiThreeAlliesTimer
uint32 m_uiUnstableEnergyTimer
uint32 m_uiIronRootsTimer
uint32 m_uiGroundTremorTimer
uint32 m_uiDeforestationTimer
uint8 m_uiWaterSpiritDeadCount
uint8 m_uiSnaplasherDeadCount
uint8 m_uiStormlasherDeadCount
ObjectGuid m_waterSpiritGuid
ObjectGuid m_stormLasherGuid
ObjectGuid m_snaplasherGuid
std::vector< uint32 > spawnSpellsVector
Additional Inherited Members
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 186 of file boss_freya.cpp.
Constructor & Destructor Documentation
boss_freyaAI()
boss_freyaAI::boss_freyaAI (Creature * pCreature) inline
Definition at line 188 of file boss_freya.cpp.
References aAlliesSpawnSpells, WorldObject::GetInstanceData(), WorldObject::GetMap(), Map::IsRegularDifficulty(), m_bEventFinished, m_bIsRegularMode, m_pInstance, m_uiEpilogueTimer, MAX_ALLIES_SPELLS, Reset(), and spawnSpellsVector.
Member Function Documentation
Aggro()
void boss_freyaAI::Aggro (Unit *) inline override virtual
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
Called at creature EnterCombat with an enemy This is a SD2 internal function Called by default on creature EnterCombat with an enemy
Reimplemented from ScriptedAI.
Definition at line 262 of file boss_freya.cpp.
References CAST_AURA_NOT_PRESENT, CAST_TRIGGERED, UnitAI::DoCastSpellIfCan(), FetchElders(), IN_PROGRESS, m_bEventFinished, m_bIsRegularMode, CreatureAI::m_creature, m_pInstance, instance_ulduar::SetData(), SPELL_ATTUNED_TO_NATURE, SPELL_TOUCH_OF_EONAR, SPELL_TOUCH_OF_EONAR_H, and TYPE_FREYA.
AttackStart()
void boss_freyaAI::AttackStart (Unit * who) inline override virtual
== Triggered Actions Requested ==================
Called when creature attack expected (if creature can and no have current victim) Note: for reaction at hostile action must be called AttackedBy function. Note: Usually called by MoveInLineOfSight, in Unit::SelectHostileTarget or when the AI is forced to attack an enemy
Parameters
pWho Unit* who is possible target
Reimplemented from CreatureAI.
Definition at line 277 of file boss_freya.cpp.
References CreatureAI::AttackStart(), and m_bEventFinished.
DamageTaken()
void boss_freyaAI::DamageTaken (Unit * , uint32 & , DamageEffectType , SpellEntry const *) inline override virtual
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
Parameters
pDealer Unit* who will deal Damage to the creature
uiDamage Amount of Damage that will be dealt, can be changed here
Reimplemented from CreatureAI.
Definition at line 342 of file boss_freya.cpp.
References CAST_TRIGGERED, Unit::CastSpell(), UnitAI::DoCastSpellIfCan(), DONE, DoScriptText(), EnterEvadeMode(), instance_ulduar::GetData(), Unit::GetHealth(), Unit::GetSpellAuraHolder(), m_bEventFinished, m_bIsRegularMode, CreatureAI::m_creature, m_pInstance, m_uiEpilogueTimer, MIN_ATTUNED_NATURE_STACKS, SAY_EPILOGUE, instance_ulduar::SetData(), instance_ulduar::SetSpecialAchievementCriteria(), SPELL_ATTUNED_TO_NATURE, SPELL_FREYA_CREDIT, SPELL_SUMMON_CHEST_0, SPELL_SUMMON_CHEST_0_H, SPELL_SUMMON_CHEST_1, SPELL_SUMMON_CHEST_1_H, SPELL_SUMMON_CHEST_2, SPELL_SUMMON_CHEST_2_H, SPELL_SUMMON_CHEST_3, SPELL_SUMMON_CHEST_3_H, TRIGGERED_OLD_TRIGGERED, TYPE_ACHIEV_BACK_NATURE, TYPE_FREYA, and TYPE_FREYA_HARD.
DoDrainElders()
void boss_freyaAI::DoDrainElders () inline
Definition at line 571 of file boss_freya.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), m_pInstance, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRACH, NPC_ELDER_STONEBARK, SPELL_DRAINED_OF_POWER, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by UpdateAI().
EnterEvadeMode()
void boss_freyaAI::EnterEvadeMode () inline override virtual
This function cleans up the combat state if the creature evades It will:
Drop Auras
Drop all threat
Stop combat
Move the creature home
Clear tagging for loot
call Reset()
Reimplemented from ScriptedAI.
Definition at line 329 of file boss_freya.cpp.
References Unit::CombatStop(), Unit::GetMotionMaster(), Unit::IsAlive(), m_bEventFinished, CreatureAI::m_creature, MotionMaster::MoveTargetedHome(), Unit::RemoveAllAurasOnEvade(), Reset(), and Creature::SetLootRecipient().
Referenced by DamageTaken().
FetchElders()
void boss_freyaAI::FetchElders () inline
Definition at line 517 of file boss_freya.cpp.
References DoScriptText(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_bIsRegularMode, CreatureAI::m_creature, m_pInstance, m_uiDrainEldersTimer, m_uiGroundTremorTimer, m_uiIronRootsTimer, m_uiUnstableEnergyTimer, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRACH, NPC_ELDER_STONEBARK, SAY_AGGRO, SAY_AGGRO_HARD, instance_ulduar::SetData(), SPELL_BRIGHTLEAF_ESSENCE_CHANNEL, SPELL_BRIGHTLEAF_ESSENCE_CHANNEL_H, SPELL_FULL_HEAL, SPELL_IRONBRANCH_ESSENCE_CHANNEL, SPELL_IRONBRANCH_ESSENCE_CHANNEL_H, SPELL_STONEBARK_ESSEMCE_CHANNEL, SPELL_STONEBARK_ESSEMCE_CHANNEL_H, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, and TYPE_FREYA_HARD.
Referenced by Aggro().
JustReachedHome()
void boss_freyaAI::JustReachedHome () inline override virtual
Called at reaching home after MoveTargetedHome.
Reimplemented from UnitAI.
Definition at line 295 of file boss_freya.cpp.
References FAIL, ScriptedInstance::GetSingleCreatureFromStorage(), m_pInstance, NPC_ELDER_BRIGHTLEAF, NPC_ELDER_IRONBRACH, NPC_ELDER_STONEBARK, instance_ulduar::SetData(), TYPE_FREYA, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
JustSummoned()
void boss_freyaAI::JustSummoned (Creature *) inline override virtual
Called when the creature summon successfully other creature.
Parameters
pSummoned Creature that got summoned
Reimplemented from UnitAI.
Definition at line 389 of file boss_freya.cpp.
References Creature::AI(), UnitAI::AttackStart(), Unit::CastSpell(), Object::GetEntry(), Object::GetObjectGuid(), Unit::GetVictim(), CreatureAI::m_creature, m_snaplasherGuid, m_stormLasherGuid, m_waterSpiritGuid, NPC_ANCIENT_CONSERVATOR, NPC_DETONATING_LASHER, NPC_EONARS_GIFT, NPC_NATURE_BOMB, NPC_SNAPLASHER, NPC_STORM_LASHER, NPC_WATER_SPIRIT, SPELL_AUTO_GROW, SPELL_LIFEBINDERS_GIFT_VISUAL, SPELL_NATURE_BOMB_GO, SPELL_PHEROMONES, and TRIGGERED_OLD_TRIGGERED.
KilledUnit()
void boss_freyaAI::KilledUnit (Unit *) inline override virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented from UnitAI.
Definition at line 381 of file boss_freya.cpp.
References DoScriptText(), Object::GetTypeId(), CreatureAI::m_creature, SAY_SLAY_1, SAY_SLAY_2, TYPEID_PLAYER, and urand().
MoveInLineOfSight()
void boss_freyaAI::MoveInLineOfSight (Unit * who) inline override virtual
== Reactions At =================================
Called if IsVisible(Unit* pWho) is true at each (relative) override pWho move, reaction at visibility zone enter Note: The Unit* pWho can be out of Line of Sight, usually this is only visibiliy (by state) and range dependendend Note: This function is not called for creatures who are in evade mode
Parameters
pWho Unit* who moved in the visibility range and is visisble
Reimplemented from UnitAI.
Definition at line 286 of file boss_freya.cpp.
References m_bEventFinished, and UnitAI::MoveInLineOfSight().
ReceiveAIEvent()
void boss_freyaAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) inline override virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented from ScriptedAI.
Definition at line 477 of file boss_freya.cpp.
References AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, CAST_TRIGGERED, UnitAI::DoCastSpellIfCan(), DoScriptText(), GetRandomGenerator(), CreatureAI::m_creature, m_uiAlliesWaveCount, m_uiThreeAlliesTimer, MAX_ALLIES_SPELLS, SAY_ADDS_CONSERVATOR, SAY_ADDS_LASHER, SAY_ADDS_TRIO, spawnSpellsVector, SPELL_SUMMON_WAVE_1, SPELL_SUMMON_WAVE_10, and SPELL_SUMMON_WAVE_3.
Reset()
void boss_freyaAI::Reset () inline override virtual
Reimplemented from CreatureAI.
Definition at line 235 of file boss_freya.cpp.
References GetRandomGenerator(), IN_MILLISECONDS, m_bDeforestationComplete, m_uiAlliesNatureTimer, m_uiAlliesWaveCount, m_uiBerserkTimer, m_uiDeforestationTimer, m_uiDrainEldersTimer, m_uiGroundTremorTimer, m_uiIronRootsTimer, m_uiLifebindersGiftTimer, m_uiNatureBombTimer, m_uiSnaplasherDeadCount, m_uiStormlasherDeadCount, m_uiSunbeamTimer, m_uiThreeAlliesTimer, m_uiUnstableEnergyTimer, m_uiWaterSpiritDeadCount, MINUTE, and spawnSpellsVector.
Referenced by boss_freyaAI(), and EnterEvadeMode().
SummonedCreatureJustDied()
void boss_freyaAI::SummonedCreatureJustDied (Creature *) inline override virtual
Called when a summoned creature is killed.
Parameters
pSummoned Summoned Creature* that got killed
Reimplemented from UnitAI.
Definition at line 420 of file boss_freya.cpp.
References Unit::CastSpell(), Object::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), m_bDeforestationComplete, CreatureAI::m_creature, m_pInstance, m_uiDeforestationTimer, m_uiSnaplasherDeadCount, m_uiStormlasherDeadCount, m_uiWaterSpiritDeadCount, MIN_DEFORESTATION_COUNT, NPC_ANCIENT_CONSERVATOR, NPC_DETONATING_LASHER, NPC_FREYA_ACHIEV_TRIGGER, NPC_SNAPLASHER, NPC_STORM_LASHER, NPC_WATER_SPIRIT, SPELL_ATTUNED_10_STACKS, SPELL_ATTUNED_25_STACKS, SPELL_ATTUNED_2_STACKS, SPELL_DEFORESTATION_CREDIT, and TRIGGERED_OLD_TRIGGERED.
UpdateAI()
void boss_freyaAI::UpdateAI (const uint32 diff) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented from UnitAI.
Definition at line 602 of file boss_freya.cpp.
References ATTACKING_TARGET_RANDOM, CAST_OK, CAST_TRIGGERED, Unit::CastSpell(), UnitAI::DoCastSpellIfCan(), DoDrainElders(), UnitAI::DoMeleeAttackIfReady(), DoScriptText(), EMOTE_ALLIES_NATURE, Creature::ForcedDespawn(), Map::GetCreature(), WorldObject::GetMap(), Unit::GetVictim(), Unit::HasAura(), m_bIsRegularMode, CreatureAI::m_creature, m_snaplasherGuid, m_stormLasherGuid, m_uiAlliesNatureTimer, m_uiAlliesWaveCount, m_uiBerserkTimer, m_uiDeforestationTimer, m_uiDrainEldersTimer, m_uiEpilogueTimer, m_uiGroundTremorTimer, m_uiIronRootsTimer, m_uiLifebindersGiftTimer, m_uiNatureBombTimer, m_uiSunbeamTimer, m_uiThreeAlliesTimer, m_uiUnstableEnergyTimer, m_waterSpiritGuid, MAX_ALLIES_WAVES, SAY_BERSERK, Unit::SelectAttackingTarget(), Unit::SelectHostileTarget(), SPELL_BERSERK, SPELL_FEIGN_DEATH, SPELL_FULL_HEAL, SPELL_GROUND_TREMOR, SPELL_GROUND_TREMOR_H, SPELL_IRON_ROOTS, SPELL_IRON_ROOTS_H, SPELL_LIFEBINDERS_GIFT_SUMMON, SPELL_NATURE_BOMB_SUMMON, SPELL_SUMMON_ALLIES_OF_NATURE, SPELL_SUMMON_ALLIES_OF_NATURE_H, SPELL_SUNBEAM, SPELL_SUNBEAM_H, SPELL_TELEPORT, SPELL_UNSTABLE_SUN_BEAM, SPELL_UNSTABLE_SUN_BEAM_H, Unit::Suicide(), and TRIGGERED_OLD_TRIGGERED.
Field Documentation
m_bDeforestationComplete
bool boss_freyaAI::m_bDeforestationComplete
Definition at line 206 of file boss_freya.cpp.
Referenced by Reset(), and SummonedCreatureJustDied().
m_bEventFinished
bool boss_freyaAI::m_bEventFinished
Definition at line 205 of file boss_freya.cpp.
Referenced by Aggro(), AttackStart(), boss_freyaAI(), DamageTaken(), EnterEvadeMode(), and MoveInLineOfSight().
m_bIsRegularMode
bool boss_freyaAI::m_bIsRegularMode
Definition at line 204 of file boss_freya.cpp.
Referenced by Aggro(), boss_freyaAI(), DamageTaken(), FetchElders(), and UpdateAI().
m_pInstance
instance_ulduar* boss_freyaAI::m_pInstance
Definition at line 203 of file boss_freya.cpp.
Referenced by Aggro(), boss_freyaAI(), DamageTaken(), DoDrainElders(), FetchElders(), JustReachedHome(), and SummonedCreatureJustDied().
m_snaplasherGuid
ObjectGuid boss_freyaAI::m_snaplasherGuid
Definition at line 231 of file boss_freya.cpp.
Referenced by JustSummoned(), and UpdateAI().
m_stormLasherGuid
ObjectGuid boss_freyaAI::m_stormLasherGuid
Definition at line 230 of file boss_freya.cpp.
Referenced by JustSummoned(), and UpdateAI().
m_uiAlliesNatureTimer
uint32 boss_freyaAI::m_uiAlliesNatureTimer
Definition at line 212 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
m_uiAlliesWaveCount
uint8 boss_freyaAI::m_uiAlliesWaveCount
Definition at line 213 of file boss_freya.cpp.
Referenced by ReceiveAIEvent(), Reset(), and UpdateAI().
m_uiBerserkTimer
uint32 boss_freyaAI::m_uiBerserkTimer
Definition at line 209 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
m_uiDeforestationTimer
uint32 boss_freyaAI::m_uiDeforestationTimer
Definition at line 224 of file boss_freya.cpp.
Referenced by Reset(), SummonedCreatureJustDied(), and UpdateAI().
m_uiDrainEldersTimer
uint32 boss_freyaAI::m_uiDrainEldersTimer
Definition at line 210 of file boss_freya.cpp.
Referenced by FetchElders(), Reset(), and UpdateAI().
m_uiEpilogueTimer
uint32 boss_freyaAI::m_uiEpilogueTimer
Definition at line 208 of file boss_freya.cpp.
Referenced by boss_freyaAI(), DamageTaken(), and UpdateAI().
m_uiGroundTremorTimer
uint32 boss_freyaAI::m_uiGroundTremorTimer
Definition at line 222 of file boss_freya.cpp.
Referenced by FetchElders(), Reset(), and UpdateAI().
m_uiIronRootsTimer
uint32 boss_freyaAI::m_uiIronRootsTimer
Definition at line 221 of file boss_freya.cpp.
Referenced by FetchElders(), Reset(), and UpdateAI().
m_uiLifebindersGiftTimer
uint32 boss_freyaAI::m_uiLifebindersGiftTimer
Definition at line 217 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
m_uiNatureBombTimer
uint32 boss_freyaAI::m_uiNatureBombTimer
Definition at line 216 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
m_uiSnaplasherDeadCount
uint8 boss_freyaAI::m_uiSnaplasherDeadCount
Definition at line 226 of file boss_freya.cpp.
Referenced by Reset(), and SummonedCreatureJustDied().
m_uiStormlasherDeadCount
uint8 boss_freyaAI::m_uiStormlasherDeadCount
Definition at line 227 of file boss_freya.cpp.
Referenced by Reset(), and SummonedCreatureJustDied().
m_uiSunbeamTimer
uint32 boss_freyaAI::m_uiSunbeamTimer
Definition at line 215 of file boss_freya.cpp.
Referenced by Reset(), and UpdateAI().
m_uiThreeAlliesTimer
uint32 boss_freyaAI::m_uiThreeAlliesTimer
Definition at line 218 of file boss_freya.cpp.
Referenced by ReceiveAIEvent(), Reset(), and UpdateAI().
m_uiUnstableEnergyTimer
uint32 boss_freyaAI::m_uiUnstableEnergyTimer
Definition at line 220 of file boss_freya.cpp.
Referenced by FetchElders(), Reset(), and UpdateAI().
m_uiWaterSpiritDeadCount
uint8 boss_freyaAI::m_uiWaterSpiritDeadCount
Definition at line 225 of file boss_freya.cpp.
Referenced by Reset(), and SummonedCreatureJustDied().
m_waterSpiritGuid
ObjectGuid boss_freyaAI::m_waterSpiritGuid
Definition at line 229 of file boss_freya.cpp.
Referenced by JustSummoned(), and UpdateAI().
spawnSpellsVector
std::vector<uint32> boss_freyaAI::spawnSpellsVector
Definition at line 233 of file boss_freya.cpp.
Referenced by boss_freyaAI(), ReceiveAIEvent(), and Reset().
The documentation for this struct was generated from the following file:
boss_freya.cpp