CMaNGOS_WoTLK: ScalingStatValuesEntry Struct Reference
ScalingStatValuesEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
uint32 getssdMultiplier (uint32 mask) const
uint32 getArmorMod (uint32 mask) const
uint32 getDPSMod (uint32 mask) const
uint32 getSpellBonus (uint32 mask) const
uint32 getFeralBonus (uint32 mask) const
Data Fields
uint32 Id
uint32 Level
uint32 ssdMultiplier [4]
uint32 armorMod [4]
uint32 dpsMod [6]
uint32 spellBonus
uint32 ssdMultiplier2
uint32 ssdMultiplier3
uint32 armorMod2 [4]
Detailed Description
Definition at line 1590 of file DBCStructure.h.
Member Function Documentation
getArmorMod()
uint32 ScalingStatValuesEntry::getArmorMod (uint32 mask) const inline
Definition at line 1644 of file DBCStructure.h.
References armorMod, and armorMod2.
Referenced by Player::_ApplyItemBonuses().
getDPSMod()
uint32 ScalingStatValuesEntry::getDPSMod (uint32 mask) const inline
Definition at line 1661 of file DBCStructure.h.
References dpsMod.
Referenced by Player::_ApplyItemBonuses().
getFeralBonus()
uint32 ScalingStatValuesEntry::getFeralBonus (uint32 mask) const inline
Definition at line 1682 of file DBCStructure.h.
Referenced by Player::_ApplyItemBonuses().
getSpellBonus()
uint32 ScalingStatValuesEntry::getSpellBonus (uint32 mask) const inline
Definition at line 1675 of file DBCStructure.h.
References spellBonus.
Referenced by Player::_ApplyItemBonuses().
getssdMultiplier()
uint32 ScalingStatValuesEntry::getssdMultiplier (uint32 mask) const inline
Definition at line 1630 of file DBCStructure.h.
References ssdMultiplier, ssdMultiplier2, and ssdMultiplier3.
Referenced by Player::_ApplyItemBonuses().
Field Documentation
armorMod
uint32 ScalingStatValuesEntry::armorMod[4]
Definition at line 1595 of file DBCStructure.h.
Referenced by getArmorMod().
armorMod2
uint32 ScalingStatValuesEntry::armorMod2[4]
Definition at line 1601 of file DBCStructure.h.
Referenced by getArmorMod().
dpsMod
uint32 ScalingStatValuesEntry::dpsMod[6]
Definition at line 1596 of file DBCStructure.h.
Referenced by getDPSMod().
Id
uint32 ScalingStatValuesEntry::Id
Definition at line 1592 of file DBCStructure.h.
Level
uint32 ScalingStatValuesEntry::Level
Definition at line 1593 of file DBCStructure.h.
spellBonus
uint32 ScalingStatValuesEntry::spellBonus
Definition at line 1597 of file DBCStructure.h.
Referenced by getSpellBonus().
ssdMultiplier
uint32 ScalingStatValuesEntry::ssdMultiplier[4]
Definition at line 1594 of file DBCStructure.h.
Referenced by getssdMultiplier().
ssdMultiplier2
uint32 ScalingStatValuesEntry::ssdMultiplier2
Definition at line 1598 of file DBCStructure.h.
Referenced by getssdMultiplier().
ssdMultiplier3
uint32 ScalingStatValuesEntry::ssdMultiplier3
Definition at line 1599 of file DBCStructure.h.
Referenced by getssdMultiplier().
The documentation for this struct was generated from the following file:
DBCStructure.h