CMaNGOS_WoTLK: Die< Side, Default, Sides > Struct Template Reference
Die< Side, Default, Sides > Struct Template Reference
#include <Util.h>
Public Member Functions
Die ()
Side roll (uint32 random)
void set (uint8 side, float chancef)
Data Fields
uint32 chance [Sides]
Detailed Description
template<class Side, Side Default, uint8 Sides>
struct Die< Side, Default, Sides >
Definition at line 107 of file Util.h.
Constructor & Destructor Documentation
Die()
template<class Side , Side Default, uint8 Sides> Die< Side, Default, Sides >::Die () inline explicit
Definition at line 110 of file Util.h.
References Die< Side, Default, Sides >::chance.
Member Function Documentation
roll()
template<class Side , Side Default, uint8 Sides> Side Die< Side, Default, Sides >::roll (uint32 random) inline
Definition at line 111 of file Util.h.
References Die< Side, Default, Sides >::chance.
Referenced by Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), Unit::RollMagicResistanceMultiplierOutcomeAgainst(), and Unit::RollMeleeOutcomeAgainst().
set()
template<class Side , Side Default, uint8 Sides> void Die< Side, Default, Sides >::set (uint8 side, float chancef) inline
Definition at line 125 of file Util.h.
References Die< Side, Default, Sides >::chance, and chance_u().
Referenced by Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), and Unit::RollMeleeOutcomeAgainst().
Field Documentation
chance
template<class Side , Side Default, uint8 Sides> uint32 Die< Side, Default, Sides >::chance[Sides]
Definition at line 130 of file Util.h.
Referenced by Die< Side, Default, Sides >::Die(), Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), Die< Side, Default, Sides >::roll(), Unit::RollMagicResistanceMultiplierOutcomeAgainst(), Unit::RollMeleeOutcomeAgainst(), and Die< Side, Default, Sides >::set().
The documentation for this struct was generated from the following file:
Util.h