CMaNGOS_WoTLK: DancingRuneWeapon Struct Reference
DancingRuneWeapon Struct Reference
Public Member Functions
void OnSummon (Spell *spell, Creature *summon) const override
void OnApply (Aura *aura, bool apply) const override
bool OnCheckProc (Aura *aura, ProcExecutionData &data) const override
SpellAuraProcResult OnProc (Aura *aura, ProcExecutionData &procData) const override
Public Member Functions inherited from SpellScript
virtual ~SpellScript ()=default
virtual void OnInit (Spell *) const
virtual void OnSuccessfulStart (Spell *) const
virtual void OnSuccessfulFinish (Spell *) const
virtual SpellCastResult OnCheckCast (Spell *, bool) const
virtual void OnSpellCastResultOverride (SpellCastResult &, uint32 &, uint32 &) const
virtual void OnEffectExecute (Spell *, SpellEffectIndex) const
virtual void OnRadiusCalculate (Spell *, SpellEffectIndex, bool, float &) const
virtual void OnDestTarget (Spell *) const
virtual bool OnCheckTarget (const Spell *, GameObject *, SpellEffectIndex) const
virtual bool OnCheckTarget (const Spell *, Unit *, SpellEffectIndex) const
virtual void OnCast (Spell *) const
virtual void OnHit (Spell *, SpellMissInfo) const
virtual void OnAfterHit (Spell *) const
virtual void OnSummon (Spell *, GameObject *) const
virtual uint32 GetPhaseMaskOverride (Spell *) const
Public Member Functions inherited from AuraScript
virtual ~AuraScript ()=default
virtual void OnHolderInit (SpellAuraHolder *, WorldObject *) const
virtual void OnAuraInit (Aura *) const
virtual int32 OnAuraValueCalculate (AuraCalcData &, int32 value) const
virtual void OnDamageCalculate (Aura *, Unit *, int32 &, float &) const
virtual int32 OnDurationCalculate (WorldObject const *, Unit const *, int32 duration) const
virtual void OnAfterApply (Aura *, bool) const
virtual void OnAbsorb (Aura *, int32 &, int32 &, uint32 &, int32 &, bool &, bool &) const
virtual void OnManaAbsorb (Aura *, int32 &) const
virtual void OnAuraDeathPrevention (Aura *, int32 &) const
virtual void OnDispel (SpellAuraHolder *, Unit *, uint32, uint32) const
virtual void OnPeriodicCalculateAmount (Aura *, uint32 &) const
virtual void OnPeriodicTrigger (Aura *, PeriodicTriggerData &) const
virtual void OnPeriodicDummy (Aura *) const
virtual void OnPeriodicTickEnd (Aura *) const
virtual void OnPersistentAreaAuraEnd (DynamicObject *) const
virtual void OnHeartbeat (Aura *) const
virtual uint32 GetAuraScriptCustomizationValue (Aura *) const
Detailed Description
Definition at line 401 of file DeathKnight.cpp.
Member Function Documentation
OnApply()
void DancingRuneWeapon::OnApply (Aura * aura, bool apply) const inline override virtual
Reimplemented from AuraScript.
Definition at line 416 of file DeathKnight.cpp.
References ByteConverter::apply(), EFFECT_INDEX_1, Unit::FindGuardianWithEntry(), Aura::GetEffIndex(), Aura::GetTarget(), and NPC_DANCING_RUNE_WEAPON.
OnCheckProc()
bool DancingRuneWeapon::OnCheckProc (Aura * aura, ProcExecutionData & data) const inline override virtual
Reimplemented from AuraScript.
Definition at line 423 of file DeathKnight.cpp.
References EFFECT_INDEX_1, Aura::GetEffIndex(), SpellEntry::IsFitToFamily(), SPELLFAMILY_DEATHKNIGHT, and ProcExecutionData::spellInfo.
OnProc()
SpellAuraProcResult DancingRuneWeapon::OnProc (Aura * aura, ProcExecutionData & procData) const inline override virtual
Reimplemented from AuraScript.
Definition at line 430 of file DeathKnight.cpp.
References Unit::CastSpell(), EFFECT_INDEX_1, Unit::FindGuardianWithEntry(), Aura::GetEffIndex(), Aura::GetTarget(), Unit::GetVictim(), NPC_DANCING_RUNE_WEAPON, SPELL_AURA_PROC_OK, ProcExecutionData::spellInfo, TRIGGERED_IGNORE_COSTS, and TRIGGERED_NORMAL_COMBAT_CAST.
OnSummon()
void DancingRuneWeapon::OnSummon (Spell * spell, Creature * summon) const inline override virtual
Reimplemented from SpellScript.
Definition at line 403 of file DeathKnight.cpp.
References Creature::AI(), Unit::CastSpell(), Spell::GetCaster(), M_PI_F, UnitAI::SetMoveChaseParams(), SPELL_COPY_WEAPON, SPELL_DANCING_RUNE_WEAPON_VISUAL, SPELL_DEATH_KNIGHT_PET_SCALING_03, SPELL_FAKE_AGGRO_RADIUS_8YD, SPELL_RUNE_WEAPON_MARK, SPELL_RUNE_WEAPON_SCALING_01, SPELL_RUNE_WEAPON_SCALING_02, and TRIGGERED_NONE.
The documentation for this struct was generated from the following file:
DeathKnight.cpp