CMaNGOS_WoTLK: MaNGOS::UnitLastSearcher< Check > Struct Template Reference
MaNGOS::UnitLastSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitLastSearcher (Unit *&result, Check &check)
void Visit (CreatureMapType &m)
void Visit (PlayerMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
Unit *& i_object
Check & i_check
Detailed Description
template<class Check>
struct MaNGOS::UnitLastSearcher< Check >
Definition at line 371 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitLastSearcher()
template<class Check > MaNGOS::UnitLastSearcher< Check >::UnitLastSearcher (Unit *& result, Check & check) inline
Definition at line 377 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/3]
template<class Check > void MaNGOS::UnitLastSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 564 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void MaNGOS::UnitLastSearcher< Check >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 383 of file GridNotifiers.h.
Visit() [3/3]
template<class Check > void MaNGOS::UnitLastSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 577 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Field Documentation
i_check
template<class Check > Check& MaNGOS::UnitLastSearcher< Check >::i_check
Definition at line 375 of file GridNotifiers.h.
i_object
template<class Check > Unit*& MaNGOS::UnitLastSearcher< Check >::i_object
Definition at line 374 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 MaNGOS::UnitLastSearcher< Check >::i_phaseMask
Definition at line 373 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h