CMaNGOS_WoTLK: go_fel_cannonball_stack_trap Struct Reference
go_fel_cannonball_stack_trap Struct Reference
Public Member Functions
go_fel_cannonball_stack_trap (GameObject *go)
void JustSpawned () override
void JustDespawned () override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
ObjectGuid m_bunny
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 965 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_fel_cannonball_stack_trap()
go_fel_cannonball_stack_trap::go_fel_cannonball_stack_trap (GameObject * go) inline
Definition at line 967 of file go_scripts.cpp.
Member Function Documentation
JustDespawned()
void go_fel_cannonball_stack_trap::JustDespawned () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 977 of file go_scripts.cpp.
References Map::GetCreature(), WorldObject::GetMap(), m_bunny, and GameObjectAI::m_go.
JustSpawned()
void go_fel_cannonball_stack_trap::JustSpawned () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 971 of file go_scripts.cpp.
References Object::GetObjectGuid(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_bunny, GameObjectAI::m_go, NPC_BOMBING_RUN_TARGET_BUNNY, WorldObject::SummonCreature(), and TEMPSPAWN_MANUAL_DESPAWN.
Field Documentation
m_bunny
ObjectGuid go_fel_cannonball_stack_trap::m_bunny
Definition at line 969 of file go_scripts.cpp.
Referenced by JustDespawned(), and JustSpawned().
The documentation for this struct was generated from the following file:
go_scripts.cpp