CMaNGOS_WoTLK: MaNGOS::WorldObjectListSearcher< Check > Struct Template Reference
MaNGOS::WorldObjectListSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectListSearcher (WorldObjectList &objects, Check &check)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (GameObjectMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
WorldObjectList & i_objects
Check & i_check
Detailed Description
template<class Check>
struct MaNGOS::WorldObjectListSearcher< Check >
Definition at line 238 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectListSearcher()
template<class Check > MaNGOS::WorldObjectListSearcher< Check >::WorldObjectListSearcher (WorldObjectList & objects, Check & check) inline
Definition at line 244 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/6]
template<class Check > void MaNGOS::WorldObjectListSearcher< Check >::Visit (CorpseMapType & m)
Definition at line 451 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [2/6]
template<class Check > void MaNGOS::WorldObjectListSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 442 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [3/6]
template<class Check > void MaNGOS::WorldObjectListSearcher< Check >::Visit (DynamicObjectMapType & m)
Definition at line 469 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [4/6]
template<class Check > void MaNGOS::WorldObjectListSearcher< Check >::Visit (GameObjectMapType & m)
Definition at line 460 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [5/6]
template<class Check > template<class NOT_INTERESTED > void MaNGOS::WorldObjectListSearcher< Check >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 253 of file GridNotifiers.h.
Visit() [6/6]
template<class Check > void MaNGOS::WorldObjectListSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 433 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Field Documentation
i_check
template<class Check > Check& MaNGOS::WorldObjectListSearcher< Check >::i_check
Definition at line 242 of file GridNotifiers.h.
i_objects
template<class Check > WorldObjectList& MaNGOS::WorldObjectListSearcher< Check >::i_objects
Definition at line 241 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 MaNGOS::WorldObjectListSearcher< Check >::i_phaseMask
Definition at line 240 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h