CMaNGOS_WoTLK: MaNGOS::MessageDistDeliverer Struct Reference
MaNGOS::MessageDistDeliverer Struct Reference
#include <GridNotifiers.h>
Public Member Functions
MessageDistDeliverer (Player const &pl, WorldPacket const &msg, float dist, bool to_self, bool ownTeamOnly)
void Visit (CameraMapType &m)
template<class SKIP >
void Visit (GridRefManager< SKIP > &)
Data Fields
Player const & i_player
WorldPacket const & i_message
bool i_toSelf
bool i_ownTeamOnly
float i_dist
Detailed Description
Definition at line 95 of file GridNotifiers.h.
Constructor & Destructor Documentation
MessageDistDeliverer()
MaNGOS::MessageDistDeliverer::MessageDistDeliverer (Player const & pl, WorldPacket const & msg, float dist, bool to_self, bool ownTeamOnly) inline
Definition at line 103 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/2]
void MessageDistDeliverer::Visit (CameraMapType & m)
Definition at line 178 of file GridNotifiers.cpp.
References Unit::GetOwner(), Player::GetSession(), Player::GetTeam(), i_dist, i_message, i_ownTeamOnly, i_player, i_toSelf, and WorldObject::InSamePhase().
Visit() [2/2]
template<class SKIP > void MaNGOS::MessageDistDeliverer::Visit (GridRefManager< SKIP > &) inline
Definition at line 106 of file GridNotifiers.h.
Field Documentation
i_dist
float MaNGOS::MessageDistDeliverer::i_dist
Definition at line 101 of file GridNotifiers.h.
Referenced by Visit().
i_message
WorldPacket const& MaNGOS::MessageDistDeliverer::i_message
Definition at line 98 of file GridNotifiers.h.
Referenced by Visit().
i_ownTeamOnly
bool MaNGOS::MessageDistDeliverer::i_ownTeamOnly
Definition at line 100 of file GridNotifiers.h.
Referenced by Visit().
i_player
Player const& MaNGOS::MessageDistDeliverer::i_player
Definition at line 97 of file GridNotifiers.h.
Referenced by Visit().
i_toSelf
bool MaNGOS::MessageDistDeliverer::i_toSelf
Definition at line 99 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp