CMaNGOS_WoTLK: CreatureCreatePos Struct Reference
CreatureCreatePos Struct Reference
#include <Creature.h>
Public Member Functions
CreatureCreatePos (Map *map, float x, float y, float z, float o, uint32 phaseMask)
CreatureCreatePos (WorldObject *closeObject, float ori, float dist=0.0f, float angle=0.0f)
Map * GetMap () const
uint32 GetPhaseMask () const
void SelectFinalPoint (Creature *cr, bool staticSpawn)
bool Relocate (Creature *cr) const
Data Fields
Position m_pos
Private Attributes
Map * m_map
uint32 m_phaseMask
WorldObject * m_closeObject
float m_angle
float m_dist
Detailed Description
Definition at line 496 of file Creature.h.
Constructor & Destructor Documentation
CreatureCreatePos() [1/2]
CreatureCreatePos::CreatureCreatePos (Map * map, float x, float y, float z, float o, uint32 phaseMask) inline
Definition at line 500 of file Creature.h.
References m_pos, Position::o, Position::x, Position::y, and Position::z.
CreatureCreatePos() [2/2]
CreatureCreatePos::CreatureCreatePos (WorldObject * closeObject, float ori, float dist = 0.0f, float angle = 0.0f) inline
Definition at line 503 of file Creature.h.
References m_pos, and Position::o.
Member Function Documentation
GetMap()
Map* CreatureCreatePos::GetMap () const inline
Definition at line 507 of file Creature.h.
References m_map.
Referenced by Creature::Create(), Pet::Create(), Totem::Create(), and Pet::LoadPetFromDB().
GetPhaseMask()
uint32 CreatureCreatePos::GetPhaseMask () const inline
Definition at line 508 of file Creature.h.
References m_phaseMask.
Referenced by Creature::Create(), Pet::Create(), and Totem::Create().
Relocate()
bool CreatureCreatePos::Relocate (Creature * cr) const
Definition at line 126 of file Creature.cpp.
References Object::GetGuidStr(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::IsPositionValid(), m_pos, Position::o, WorldObject::Relocate(), sLog, Position::x, Position::y, and Position::z.
Referenced by Creature::Create(), Pet::Create(), and Totem::Create().
SelectFinalPoint()
void CreatureCreatePos::SelectFinalPoint (Creature * cr, bool staticSpawn)
Definition at line 108 of file Creature.cpp.
References WorldObject::GetClosePoint(), Unit::GetObjectBoundingRadius(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), m_angle, m_closeObject, m_dist, m_pos, Unit::UpdateAllowedPositionZ(), Position::x, Position::y, and Position::z.
Referenced by Creature::Create(), Pet::Create(), and Totem::Create().
Field Documentation
m_angle
float CreatureCreatePos::m_angle private
Definition at line 518 of file Creature.h.
Referenced by SelectFinalPoint().
m_closeObject
WorldObject* CreatureCreatePos::m_closeObject private
Definition at line 517 of file Creature.h.
Referenced by SelectFinalPoint().
m_dist
float CreatureCreatePos::m_dist private
Definition at line 519 of file Creature.h.
Referenced by SelectFinalPoint().
m_map
Map* CreatureCreatePos::m_map private
Definition at line 515 of file Creature.h.
Referenced by GetMap().
m_phaseMask
uint32 CreatureCreatePos::m_phaseMask private
Definition at line 516 of file Creature.h.
Referenced by GetPhaseMask().
m_pos
Position CreatureCreatePos::m_pos
Definition at line 513 of file Creature.h.
Referenced by Totem::Create(), CreatureCreatePos(), Relocate(), SelectFinalPoint(), and Creature::SetRespawnCoord().
The documentation for this struct was generated from the following files:
Creature.h
Creature.cpp