CMaNGOS_WoTLK: MaNGOS::SpellNotifierCreatureAndPlayer Struct Reference
MaNGOS::SpellNotifierCreatureAndPlayer Struct Reference
#include <Spell.h>
Public Member Functions
float GetCenterX () const
float GetCenterY () const
SpellNotifierCreatureAndPlayer (Spell &spell, UnitList &data, float radius, float cone, SpellNotifyPushType type, SpellTargets TargetType=SPELL_TARGETS_AOE_ATTACKABLE, WorldObject *originalCaster=nullptr)
template<class T >
void Visit (GridRefManager< T > &m)
template<>
void Visit (CorpseMapType &)
template<>
void Visit (GameObjectMapType &)
template<>
void Visit (DynamicObjectMapType &)
template<>
void Visit (CameraMapType &)
Data Fields
UnitList & i_data
Spell & i_spell
SpellNotifyPushType i_push_type
float i_radius
float i_cone
SpellTargets i_TargetType
WorldObject * i_originalCaster
WorldObject * i_castingObject
bool i_playerControlled
float i_centerX
float i_centerY
float i_centerZ
Detailed Description
Definition at line 1145 of file Spell.h.
Constructor & Destructor Documentation
SpellNotifierCreatureAndPlayer()
MaNGOS::SpellNotifierCreatureAndPlayer::SpellNotifierCreatureAndPlayer (Spell & spell, UnitList & data, float radius, float cone, SpellNotifyPushType type, SpellTargets TargetType = SPELL_TARGETS_AOE_ATTACKABLE, WorldObject * originalCaster = nullptr) inline
Definition at line 1163 of file Spell.h.
References Spell::GetAffectiveCasterObject(), SpellCastTargets::getDestination(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), SpellCastTargets::getSource(), SpellCastTargets::getUnitTarget(), i_castingObject, i_centerX, i_centerY, i_centerZ, i_originalCaster, i_playerControlled, i_push_type, i_spell, WorldObject::IsControlledByPlayer(), SpellCastTargets::m_targetMask, Spell::m_targets, PUSH_CONE, PUSH_DEST_CENTER, PUSH_SELF_CENTER, PUSH_SRC_CENTER, PUSH_TARGET_CENTER, sLog, TARGET_FLAG_DEST_LOCATION, and TARGET_FLAG_SOURCE_LOCATION.
Member Function Documentation
GetCenterX()
float MaNGOS::SpellNotifierCreatureAndPlayer::GetCenterX () const inline
Definition at line 1160 of file Spell.h.
References i_centerX.
Referenced by Spell::FillAreaTargets().
GetCenterY()
float MaNGOS::SpellNotifierCreatureAndPlayer::GetCenterY () const inline
Definition at line 1161 of file Spell.h.
References i_centerY.
Referenced by Spell::FillAreaTargets().
Visit() [1/5]
template<> void MaNGOS::SpellNotifierCreatureAndPlayer::Visit (CameraMapType &) inline
Definition at line 1310 of file Spell.h.
Visit() [2/5]
template<> void MaNGOS::SpellNotifierCreatureAndPlayer::Visit (CorpseMapType &) inline
Definition at line 1307 of file Spell.h.
Visit() [3/5]
template<> void MaNGOS::SpellNotifierCreatureAndPlayer::Visit (DynamicObjectMapType &) inline
Definition at line 1309 of file Spell.h.
Visit() [4/5]
template<> void MaNGOS::SpellNotifierCreatureAndPlayer::Visit (GameObjectMapType &) inline
Definition at line 1308 of file Spell.h.
Visit() [5/5]
template<class T > void MaNGOS::SpellNotifierCreatureAndPlayer::Visit (GridRefManager< T > & m) inline
Definition at line 1204 of file Spell.h.
References GridRefManager< OBJECT >::begin(), WorldObject::CanAssistSpell(), WorldObject::CanAttackSpell(), DIST_CALC_COMBAT_REACH, DIST_CALC_NONE, GridRefManager< OBJECT >::end(), SpellEntry::HasAttribute(), i_castingObject, i_centerX, i_centerY, i_centerZ, i_cone, i_data, i_originalCaster, i_push_type, i_radius, i_spell, i_TargetType, WorldObject::IsControlledByPlayer(), WorldObject::isInBack(), WorldObject::isInFront(), Spell::m_spellInfo, PUSH_CONE, PUSH_DEST_CENTER, PUSH_SELF_CENTER, PUSH_SRC_CENTER, PUSH_TARGET_CENTER, SPELL_ATTR_EX5_IGNORE_AREA_EFFECT_PVP_CHECK, SPELL_ATTR_EX6_IGNORE_PHASE_SHIFT, SPELL_TARGETS_ALL, SPELL_TARGETS_AOE_ATTACKABLE, SPELL_TARGETS_ASSISTABLE, and SPELL_TARGETS_CHAIN_ATTACKABLE.
Field Documentation
i_castingObject
WorldObject* MaNGOS::SpellNotifierCreatureAndPlayer::i_castingObject
Definition at line 1154 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer(), and Visit().
i_centerX
float MaNGOS::SpellNotifierCreatureAndPlayer::i_centerX
Definition at line 1156 of file Spell.h.
Referenced by GetCenterX(), SpellNotifierCreatureAndPlayer(), and Visit().
i_centerY
float MaNGOS::SpellNotifierCreatureAndPlayer::i_centerY
Definition at line 1157 of file Spell.h.
Referenced by GetCenterY(), SpellNotifierCreatureAndPlayer(), and Visit().
i_centerZ
float MaNGOS::SpellNotifierCreatureAndPlayer::i_centerZ
Definition at line 1158 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer(), and Visit().
i_cone
float MaNGOS::SpellNotifierCreatureAndPlayer::i_cone
Definition at line 1151 of file Spell.h.
Referenced by Visit().
i_data
UnitList& MaNGOS::SpellNotifierCreatureAndPlayer::i_data
Definition at line 1147 of file Spell.h.
Referenced by Visit().
i_originalCaster
WorldObject* MaNGOS::SpellNotifierCreatureAndPlayer::i_originalCaster
Definition at line 1153 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer(), and Visit().
i_playerControlled
bool MaNGOS::SpellNotifierCreatureAndPlayer::i_playerControlled
Definition at line 1155 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer().
i_push_type
SpellNotifyPushType MaNGOS::SpellNotifierCreatureAndPlayer::i_push_type
Definition at line 1149 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer(), and Visit().
i_radius
float MaNGOS::SpellNotifierCreatureAndPlayer::i_radius
Definition at line 1150 of file Spell.h.
Referenced by Visit().
i_spell
Spell& MaNGOS::SpellNotifierCreatureAndPlayer::i_spell
Definition at line 1148 of file Spell.h.
Referenced by SpellNotifierCreatureAndPlayer(), and Visit().
i_TargetType
SpellTargets MaNGOS::SpellNotifierCreatureAndPlayer::i_TargetType
Definition at line 1152 of file Spell.h.
Referenced by Visit().
The documentation for this struct was generated from the following file:
Spell.h