CMaNGOS_WoTLK: DemonicCircleSummon Struct Reference
DemonicCircleSummon Struct Reference
Public Member Functions
void OnApply (Aura *aura, bool apply) const override
void OnPeriodicDummy (Aura *aura) const override
Public Member Functions inherited from AuraScript
virtual ~AuraScript ()=default
virtual void OnHolderInit (SpellAuraHolder *, WorldObject *) const
virtual void OnAuraInit (Aura *) const
virtual int32 OnAuraValueCalculate (AuraCalcData &, int32 value) const
virtual void OnDamageCalculate (Aura *, Unit *, int32 &, float &) const
virtual int32 OnDurationCalculate (WorldObject const *, Unit const *, int32 duration) const
virtual void OnAfterApply (Aura *, bool) const
virtual bool OnCheckProc (Aura *, ProcExecutionData &) const
virtual SpellAuraProcResult OnProc (Aura *, ProcExecutionData &) const
virtual void OnAbsorb (Aura *, int32 &, int32 &, uint32 &, int32 &, bool &, bool &) const
virtual void OnManaAbsorb (Aura *, int32 &) const
virtual void OnAuraDeathPrevention (Aura *, int32 &) const
virtual void OnDispel (SpellAuraHolder *, Unit *, uint32, uint32) const
virtual void OnPeriodicCalculateAmount (Aura *, uint32 &) const
virtual void OnPeriodicTrigger (Aura *, PeriodicTriggerData &) const
virtual void OnPeriodicTickEnd (Aura *) const
virtual void OnPersistentAreaAuraEnd (DynamicObject *) const
virtual void OnHeartbeat (Aura *) const
virtual uint32 GetAuraScriptCustomizationValue (Aura *) const
Detailed Description
Definition at line 395 of file Warlock.cpp.
Member Function Documentation
OnApply()
void DemonicCircleSummon::OnApply (Aura * aura, bool apply) const inline override virtual
Reimplemented from AuraScript.
Definition at line 397 of file Warlock.cpp.
References ByteConverter::apply(), DEMONIC_CIRCLE_SUMMON, GameObject::ForcedDespawn(), Unit::GetGameObject(), and Aura::GetTarget().
OnPeriodicDummy()
void DemonicCircleSummon::OnPeriodicDummy (Aura * aura) const inline override virtual
Reimplemented from AuraScript.
Definition at line 410 of file Warlock.cpp.
References Unit::CastSpell(), DEMONIC_CIRCLE_IN_RANGE_AURA, DEMONIC_CIRCLE_SUMMON, WorldObject::GetDistance(), Unit::GetGameObject(), Aura::GetTarget(), Unit::HasAura(), Unit::RemoveAurasDueToSpell(), TRIGGERED_IGNORE_CURRENT_CASTED_SPELL, TRIGGERED_IGNORE_GCD, and TRIGGERED_INSTANT_CAST.
The documentation for this struct was generated from the following file:
Warlock.cpp