CMaNGOS_WoTLK: AuraScript Struct Reference
AuraScript Struct Reference
#include <SpellScript.h>
Public Member Functions
virtual ~AuraScript ()=default
virtual void OnHolderInit (SpellAuraHolder *, WorldObject *) const
virtual void OnAuraInit (Aura *) const
virtual int32 OnAuraValueCalculate (AuraCalcData &, int32 value) const
virtual void OnDamageCalculate (Aura *, Unit *, int32 &, float &) const
virtual int32 OnDurationCalculate (WorldObject const *, Unit const *, int32 duration) const
virtual void OnApply (Aura *, bool) const
virtual void OnAfterApply (Aura *, bool) const
virtual bool OnCheckProc (Aura *, ProcExecutionData &) const
virtual SpellAuraProcResult OnProc (Aura *, ProcExecutionData &) const
virtual void OnAbsorb (Aura *, int32 &, int32 &, uint32 &, int32 &, bool &, bool &) const
virtual void OnManaAbsorb (Aura *, int32 &) const
virtual void OnAuraDeathPrevention (Aura *, int32 &) const
virtual void OnDispel (SpellAuraHolder *, Unit *, uint32, uint32) const
virtual void OnPeriodicCalculateAmount (Aura *, uint32 &) const
virtual void OnPeriodicTrigger (Aura *, PeriodicTriggerData &) const
virtual void OnPeriodicDummy (Aura *) const
virtual void OnPeriodicTickEnd (Aura *) const
virtual void OnPersistentAreaAuraEnd (DynamicObject *) const
virtual void OnHeartbeat (Aura *) const
virtual uint32 GetAuraScriptCustomizationValue (Aura *) const
Detailed Description
Definition at line 84 of file SpellScript.h.
Constructor & Destructor Documentation
~AuraScript()
virtual AuraScript::~AuraScript () virtual default
Member Function Documentation
GetAuraScriptCustomizationValue()
virtual uint32 AuraScript::GetAuraScriptCustomizationValue (Aura *) const inline virtual
Reimplemented in Polymorph, GossipNPCAppearanceAllPirateDay, GossipNPCAppearanceAllSpiritOfCompetition, and OrbOfDeception.
Definition at line 131 of file SpellScript.h.
OnAbsorb()
virtual void AuraScript::OnAbsorb (Aura * , int32 & , int32 & , uint32 & , int32 & , bool & , bool &) const inline virtual
Reimplemented in HodirsProtectiveGaze, ArdentDefender, WillOfTheNecropolis, and ShadowOfDeath.
Definition at line 111 of file SpellScript.h.
OnAfterApply()
virtual void AuraScript::OnAfterApply (Aura * , bool) const inline virtual
Definition at line 105 of file SpellScript.h.
OnApply()
virtual void AuraScript::OnApply (Aura * , bool) const inline virtual
Reimplemented in GossipNPCAppearanceAllBrewfest, DemoniacVisitation, CurseOfBoundlessAgonyRemoval, NetherChargePassive, SpellReflectionRaid, Overpower, DemonicCircleSummon, SeedOfCorruption, CurseOfDoom, SentryTotem, KillingSpree, DirtyDeeds, ShadowAffinityDots, GlyphOfShadowWordDeath, GlyphOfLightwell, LightwellRenew, PainSuppression, FingersOfFrostDummy, RapidKilling, Brambles, DancingRuneWeapon, DeathKnightDisease, CallOfTheFalcon, SleepVisualFlavor, Stoned, Drink, AllergiesAura, GettingSleepyAura, AuchenaiPossess, InebriateRemoval, GreaterInvisibilityMob, HorsemanManiacalLaugh, TorchesCaught, BraziersHit, TestRibbonPoleChannel, OgrilaFlasks, GDRPeriodicDamage, BrewfestBarkerBunny, AppleTrapFriendly, RamsteinsSwiftWorkRam, GiddyUp, StormcrowAmulet, ShadowyDisguise, WOTAOldDOT, WrathOfTheAstromancer, BuildPortableFelCannon, ShivanShapeshiftForm, FlyingAttackAura, EredarPreGateBeam, PossessionTransfer, DragonmawIllusionTransform, DragonmawIllusionBase, TagGreaterFelfireDiemetradon, RingOfFlame, ScrapReaverSpell, CharmRavager, LivingFlareUnstable, LivingFlareMaster, ShadowGraspMagth, ShadowGraspCube, GronnLordsGrasp, LeoWhirlwindAura, InsidiousWhisper, VashjPersuasion, CoaxMarmot, Soaring, VerasDeadlyPoisonTick, VerasVanish, ShadowOfDeathRemove, ShadowOfDeath, SupremusRandomTarget, ParasiticShadowfiendAura, HarpoonersMark, ShapeOfTheBeast, FetchAlchemistsApprentice, HaveChilledSerpentMucus, HaveAmberseed, HaveMuddyMireMaggot, HaveWitheredBatwing, ArgentStandUnitRideGargoyle, ScourgeDisguiseExpiring, DropDisguise, DrakuramasTeleportScript03, DrakuramasTeleportScript02, DrakuramasTeleportScript01, CharmDrakuruServant, CharmGeist, spell_void_shift_aura, spell_drained_aura, spell_protective_bubble_aura, spell_create_spirit_fount_beam_aura, spell_freezing_cloud_aura, spell_awaken_subboss_aura, spell_ingvar_transform_aura, spell_carve_stone_aura, spell_petrifying_grip_aura, spell_soul_consumption_aura, spell_fiery_combustion_aura, spell_leave_twilight_realm_aura, spell_twilight_shift_aura, spell_ride_oculus_drake_saddle, spell_telestra_clone_dies_aura, spell_crystal_spike_visual_aura, spell_intense_cold_aura, spell_vortex_aura, ThaddiusCharge, ForcedObedience, AuraWarning, AuraPreWarning, MutatingInjection, WidowsEmbrace, RocketPack, spell_dark_adherent_martyrdom_aura, spell_dark_fanatic_martyrdom_aura, spell_dark_empowerment_aura, spell_dark_transformation_aura, spell_grip_of_agony_aura, spell_feigh_death_pos_aura, spell_strangulating_aura, spell_pursuit, spell_corrupt_soul_aura, FlyingMachineControls, spell_web_door_aura, spell_remove_mushroom_power, ViscidusFreeze, MutateBug, TrueFulfillment, HuhuranWyvernSting, CThunMouthTentacle, EternalSilence, RenatakiVanishTeleport, ThreateningGaze, CallOfTheBeast, SpellFury, ShieldOfTheBlue, VengeanceOfTheBlueFlight, OpenPortalFromShattrath, SinisterReflectionClone, DarknessOfSouls, CurseOfBoundlessAgony, SpectralRealmAura, Encapsulate, TriggerStrafe, FogOfCorruptionCharm, DarkFlameFireAura, DarkFlameShadowAura, spell_break_ice, DeathCloudBrutallus, HexOfJammalanAura, AnastariPossess, EyeOfAcherus, spell_mana_rage_selin, Sacrifice, Enfeeble, MoroesVanish, SparAuras, UnarmedWoodcutter, PossessRazorgore, DirebrewDisarmPrecast, spell_repair_cannon_aura, InactiveBattleground, ArenaPreparation, IncreasedHolyLightHealing, IncreasedHealingDoneDummy, PowerCircleAura, X52RocketHelmetAura, AshbringerItemAura, NetherChargeTimer, and SnakeWrap.
Definition at line 101 of file SpellScript.h.
OnAuraDeathPrevention()
virtual void AuraScript::OnAuraDeathPrevention (Aura * , int32 &) const inline virtual
Reimplemented in ShadowOfDeath.
Definition at line 115 of file SpellScript.h.
OnAuraInit()
virtual void AuraScript::OnAuraInit (Aura *) const inline virtual
Reimplemented in KillingSpree, FakeAggroRadius8YD, and Icecrown25MeleeTrinket.
Definition at line 91 of file SpellScript.h.
OnAuraValueCalculate()
virtual int32 AuraScript::OnAuraValueCalculate (AuraCalcData & , int32 value) const inline virtual
Reimplemented in DemonicKnowledge, EarthShield, DeathKnightBloodParasitePetScaling, DeathKnightArmyOfTheDead1, DeathKnightRuneWeaponScaling2, DeathKnightRuneWeaponScaling1, DeathKnightPetScaling3, DeathKnightPetScaling2, DeathKnightPetScaling1, InfernalPetScaling4, InfernalPetScaling3, InfernalPetScaling2, InfernalPetScaling1, EarthElementalPetScaling4, EarthElementalPetScaling3, EarthElementalPetScaling2, EarthElementalPetScaling1, FeralSpiritPetScaling4, FeralSpiritPetScaling3, FeralSpiritPetScaling2, FeralSpiritPetScaling1, DruidPetScaling4, DruidPetScaling3, DruidPetScaling2, DruidPetScaling1, ElementalPetScaling4, ElementalPetScaling3, ElementalPetScaling2, ElementalPetScaling1, PriestPetScaling4, PriestPetScaling3, PriestPetScaling2, PriestPetScaling1, MagePetScaling4, MagePetScaling3, MagePetScaling2, MagePetScaling1, WarlockPetScaling5, WarlockPetScaling4, WarlockPetScaling3, WarlockPetScaling2, WarlockPetScaling1, HunterSnakeTrapScaling1, HunterPetScaling4, HunterPetScaling3, HunterPetScaling2, HunterPetScaling1, PowerWordShield, ExplosiveShot, ExposeWeakness, SwiftFlightFormPassive, FormScalingAttackPowerAuras, ArmyOfTheDead, CryptFeverServerside, StoicismAbsorb, and GDRPeriodicDamage.
Definition at line 93 of file SpellScript.h.
Referenced by Spell::CheckCast().
OnCheckProc()
virtual bool AuraScript::OnCheckProc (Aura * , ProcExecutionData &) const inline virtual
Reimplemented in ArcaneConcentration, DeathRuneDK, DancingRuneWeapon, ProcOnlyBelow35Percent, FingersOfFrostProc, LockAndLoad, SuddenDoom, BloodReserveEnchant, SiphonLifeWotlk, SetupRogue, Stealth, JudgementsOfTheWise, DeepFreezeImmunityState, SpellHasteHealerTrinket, SpellAbsorption, DarkFlameFireAura, DarkFlameShadowAura, WrathOfTheTitansProcAura, and SparAuras.
Definition at line 107 of file SpellScript.h.
OnDamageCalculate()
virtual void AuraScript::OnDamageCalculate (Aura * , Unit * , int32 & , float &) const inline virtual
Reimplemented in GlyphOfShadowWordDeath, DirtyDeeds, GlyphOfLightwell, IncreasedHolyLightHealing, and IncreasedHealingDoneDummy.
Definition at line 95 of file SpellScript.h.
OnDispel()
virtual void AuraScript::OnDispel (SpellAuraHolder * , Unit * , uint32 , uint32) const inline virtual
Reimplemented in UnstableAffliction, and DarkFiendAura.
Definition at line 117 of file SpellScript.h.
OnDurationCalculate()
virtual int32 AuraScript::OnDurationCalculate (WorldObject const * , Unit const * , int32 duration) const inline virtual
Reimplemented in WyvernSting.
Definition at line 97 of file SpellScript.h.
Referenced by CalculateSpellDuration().
OnHeartbeat()
virtual void AuraScript::OnHeartbeat (Aura *) const inline virtual
Reimplemented in DrinkAnimation, and FoodAnimation.
Definition at line 129 of file SpellScript.h.
OnHolderInit()
virtual void AuraScript::OnHolderInit (SpellAuraHolder * , WorldObject *) const inline virtual
Reimplemented in InhibitMagic, FingersOfFrostDummy, ReducedProcChancePast60, and ForceOfNatureSummon.
Definition at line 89 of file SpellScript.h.
OnManaAbsorb()
virtual void AuraScript::OnManaAbsorb (Aura * , int32 &) const inline virtual
Definition at line 113 of file SpellScript.h.
OnPeriodicCalculateAmount()
virtual void AuraScript::OnPeriodicCalculateAmount (Aura * , uint32 &) const inline virtual
Reimplemented in CurseOfAgony, DeathAndDecay, CurseOfBoundlessAgony, SpellBurnDamageBrutallus, and DigestiveAcidPeriodic.
Definition at line 119 of file SpellScript.h.
OnPeriodicDummy()
virtual void AuraScript::OnPeriodicDummy (Aura *) const inline virtual
Reimplemented in DemonicCircleSummon, PreyOnTheWeak, KillingSpree, ExplosiveShot, ForceOfNatureSummon, SummonGargoyle, FakeAggroRadius8YD, DeathRuneDK, Drink, AllergiesAura, HorsemanConflagratePeriodic, HorsemanFire, HorsemanStartFirePeriodic, HorsemanManiacalLaughDelayed, GossipNPCPeriodicTalk, RibbonPoleDancerCheckAura, TrickyTreat, MoleMachinePortalSchedule, MoleMachinePortSchedule, RamGallop, RamCanter, RamTrot, RamNeutral, GiddyUp, NetherVaporLightning, SummonIceSpearKnockbackDelayer, HarpoonersMark, RandomIngredientAura, spell_splatter_aura, spell_summon_gauntlet_mobs_periodic_aura, spell_frost_tomb_aura, spell_summon_earthen_dwarf_aura, spell_summon_malformed_ooze_aura, spell_summon_iron_trogg_aura, spell_summon_iron_dwarf_aura, ParachutePeriodicDummy, spell_parachute_aura, spell_crystal_spike_aura, RocketPackPeriodic, spell_permafrost_aura, spell_wailing_souls_aura, spell_soulstorm_visual_aura, GripOfSladran, MojoFrenzy, spell_leeching_swarm_aura, spell_summon_anubar_periodic_aura, TransformVisualPeriodic, SummonBloodElvesPeriodic, ForsakenSkill, spell_irresistible_cologne_spill_aura, spell_alluring_perfume_spill_aura, and DirebrewDisarmPrecast.
Definition at line 123 of file SpellScript.h.
OnPeriodicTickEnd()
virtual void AuraScript::OnPeriodicTickEnd (Aura *) const inline virtual
Reimplemented in MageIgnite, Regrowth, CurseOfPain, AuchenaiPossess, GreaterInvisibilityMob, TestRibbonPoleChannel, GravityLapseKnockup, EredarPreGateBeam, TerokkAncientFlames, WebWrapDamage, MarkOfKazrogal, ActivateSunbladeProtectorChannel, SpellShadowPulsePeriodic, CurseOfBoundlessAgonyRemoval, CurseOfBoundlessAgony, AnastariPossess, and NetherChargePassive.
Definition at line 125 of file SpellScript.h.
OnPeriodicTrigger()
virtual void AuraScript::OnPeriodicTrigger (Aura * , PeriodicTriggerData &) const inline virtual
Reimplemented in RapidRecuperationPeriodic, SpoutTurning, VerasDeadlyPoison, SpellAbsorption, ThaddiusTeslaChain, ThaddiusCharge, PeriodicIceBolt, SummonSkeletonsNoth, SummonZombieChow, ZombieChowSearch, spell_ley_line_focus_item, ArmyOfTheDead, PeriodicScarabTrigger, PeriodicRotate, PeriodicSummonEyeTrigger, EarthquakeGuardian, ShadowSpike, Armageddon, spell_siphon_of_acherus_aura, spell_emblazon_runeblade_aura, spell_enervating_brand_aura, FrostBlast, PlagueWaveController, spell_mana_barrier_aura, spell_explosive_barrage_aura, and spell_gunship_cannon_fire_aura.
Definition at line 121 of file SpellScript.h.
OnPersistentAreaAuraEnd()
virtual void AuraScript::OnPersistentAreaAuraEnd (DynamicObject *) const inline virtual
Reimplemented in DebrisMagtheridon, and FocusTargetVisual.
Definition at line 127 of file SpellScript.h.
Referenced by DynamicObject::OnPersistentAreaAuraEnd().
OnProc()
virtual SpellAuraProcResult AuraScript::OnProc (Aura * , ProcExecutionData &) const inline virtual
Reimplemented in Vigilance, SiphonLifeWotlk, SoulLeech, SeedOfCorruption, AncestralAwakening, ItemShamanT10Elemental2PBonus, EarthShield, LightwellRenew, JudgementsOfTheWise, LockAndLoad, RoarOfSacrifice, DancingRuneWeapon, SuddenDoom, HealthLeechPassive, DeathRuneDK, UnholyBlightDK, BloodReserveEnchant, RetaliationDummyCreature, spell_seed_of_corruption_npc, Icecrown25MeleeTrinket, DiscerningEyeOfTheBeast, SwiftHandOfJustice, ViscidusFrostWeakness, ViscidusFreeze, WrathOfTheTitansProcAura, FlagAuraBg, FingersOfFrostDummy, RetaliationWarrior, spell_paladin_tier_6_trinket, Entrapment, DarkFlameFireAura, and DarkFlameShadowAura.
Definition at line 109 of file SpellScript.h.
References SPELL_AURA_PROC_OK.
The documentation for this struct was generated from the following file:
SpellScript.h