CMaNGOS_WoTLK: VendorItemData Struct Reference
VendorItemData Struct Reference
#include <Creature.h>
Public Member Functions
VendorItem * GetItem (uint32 slot) const
bool Empty () const
uint8 GetItemCount () const
void AddItem (uint32 item, uint32 maxcount, uint32 ptime, uint32 ExtendedCost, uint16 conditonId)
bool RemoveItem (uint32 item_id)
VendorItem const * FindItemCostPair (uint32 item_id, uint32 extendedCost) const
void Clear ()
Data Fields
VendorItemList m_items
Detailed Description
Definition at line 409 of file Creature.h.
Member Function Documentation
AddItem()
void VendorItemData::AddItem (uint32 item, uint32 maxcount, uint32 ptime, uint32 ExtendedCost, uint16 conditonId) inline
Definition at line 420 of file Creature.h.
References m_items.
Referenced by ObjectMgr::AddVendorItem(), and ObjectMgr::LoadVendors().
Clear()
void VendorItemData::Clear () inline
Definition at line 427 of file Creature.h.
References m_items.
Empty()
bool VendorItemData::Empty () const inline
Definition at line 418 of file Creature.h.
References m_items.
Referenced by Player::BuyItemFromVendorSlot(), and Player::PrepareGossipMenu().
FindItemCostPair()
VendorItem const * VendorItemData::FindItemCostPair (uint32 item_id, uint32 extendedCost) const
Definition at line 88 of file Creature.cpp.
References m_items.
Referenced by ObjectMgr::IsVendorItemValid().
GetItem()
VendorItem* VendorItemData::GetItem (uint32 slot) const inline
Definition at line 413 of file Creature.h.
References m_items.
Referenced by PlayerbotAI::Buy(), Player::BuyItemFromVendorSlot(), and WorldSession::SendListInventory().
GetItemCount()
uint8 VendorItemData::GetItemCount () const inline
Definition at line 419 of file Creature.h.
References m_items.
Referenced by PlayerbotAI::Buy(), Player::BuyItemFromVendorSlot(), ObjectMgr::IsVendorItemValid(), and WorldSession::SendListInventory().
RemoveItem()
bool VendorItemData::RemoveItem (uint32 item_id)
Definition at line 70 of file Creature.cpp.
References m_items.
Field Documentation
m_items
VendorItemList VendorItemData::m_items
Definition at line 411 of file Creature.h.
Referenced by AddItem(), Clear(), Empty(), FindItemCostPair(), GetItem(), GetItemCount(), and RemoveItem().
The documentation for this struct was generated from the following files:
Creature.h
Creature.cpp