CMaNGOS_WoTLK: SetGameMasterOffHelper Struct Reference
SetGameMasterOffHelper Struct Reference
Public Member Functions
SetGameMasterOffHelper (uint32 _faction)
void operator() (Unit *unit) const
Data Fields
uint32 faction
Detailed Description
Definition at line 2654 of file Player.cpp.
Constructor & Destructor Documentation
SetGameMasterOffHelper()
SetGameMasterOffHelper::SetGameMasterOffHelper (uint32 _faction) inline explicit
Definition at line 2656 of file Player.cpp.
Member Function Documentation
operator()()
void SetGameMasterOffHelper::operator() (Unit * unit) const inline
Definition at line 2657 of file Player.cpp.
References RefManager< TO, FROM >::clearReferences(), faction, Unit::getHostileRefManager(), and Unit::setFaction().
Field Documentation
faction
uint32 SetGameMasterOffHelper::faction
Definition at line 2662 of file Player.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
Player.cpp