CMaNGOS_WoTLK: GameobjectModelData Struct Reference
GameobjectModelData Struct Reference
#include <GameObjectModelVmaps.h>
Public Member Functions
GameobjectModelData (const std::string &name_, const G3D::AABox &box)
Static Public Member Functions
static ModelList LoadGameObjectModelList (std::string fileName)
static std::tuple< std::vector< TileBuilding const * >, std::map< uint32, std::vector< TileBuilding const * > >, std::map< uint32, std::vector< TileBuilding const * > >, std::map< uint32, uint32 > > GetTileBuildingData (uint32 mapId, uint32 tileX, uint32 tileY, ModelList &modelList)
static std::tuple< uint32, uint32, uint32, uint32 > CalculateBuildingTiles (TileBuilding const &building, G3D::AABox mdl_box)
Data Fields
std::string name
G3D::AABox bound
Detailed Description
Definition at line 36 of file GameObjectModelVmaps.h.
Constructor & Destructor Documentation
GameobjectModelData()
GameobjectModelData::GameobjectModelData (const std::string & name_, const G3D::AABox & box) inline
Definition at line 38 of file GameObjectModelVmaps.h.
Referenced by LoadGameObjectModelList().
Member Function Documentation
CalculateBuildingTiles()
std::tuple< uint32, uint32, uint32, uint32 > GameobjectModelData::CalculateBuildingTiles (TileBuilding const & building, G3D::AABox mdl_box) static
Definition at line 109 of file GameObjectModelVmaps.cpp.
References GRID_SIZE, TileBuilding::ori, TileBuilding::x, TileBuilding::y, and TileBuilding::z.
Referenced by GetTileBuildingData(), and GameObjectModel::LoadGOVmapModels().
GetTileBuildingData()
std::tuple< std::vector< TileBuilding const * >, std::map< uint32, std::vector< TileBuilding const * > >, std::map< uint32, std::vector< TileBuilding const * > >, std::map< uint32, uint32 > > GameobjectModelData::GetTileBuildingData (uint32 mapId, uint32 tileX, uint32 tileY, ModelList & modelList) static
Definition at line 60 of file GameObjectModelVmaps.cpp.
References BuildingMap, TileBuilding::byDefault, CalculateBuildingTiles(), TileBuilding::displayId, modelList, TileBuilding::tileFlags, and TileBuilding::tileNumber.
Referenced by GameObjectModel::LoadGOVmapModels().
LoadGameObjectModelList()
ModelList GameobjectModelData::LoadGameObjectModelList (std::string fileName) static
Definition at line 26 of file GameObjectModelVmaps.cpp.
References GameobjectModelData().
Referenced by GameObjectModel::LoadGOVmapModels().
Field Documentation
bound
G3D::AABox GameobjectModelData::bound
Definition at line 42 of file GameObjectModelVmaps.h.
name
std::string GameobjectModelData::name
Definition at line 41 of file GameObjectModelVmaps.h.
The documentation for this struct was generated from the following files:
GameObjectModelVmaps.h
GameObjectModelVmaps.cpp