CMaNGOS_WoTLK: boss_kaelthasAI Struct Reference
boss_kaelthasAI Struct Reference
Public Member Functions
boss_kaelthasAI (Creature *creature)
void Reset () override
void ResetSize ()
void JustRespawned ()
This will by default result in reattacking, if the creature has no victim.
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void ReceiveAIEvent (AIEventType eventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
void DoDespawnSummons ()
void MoveInLineOfSight (Unit *who) override
== Reactions At =================================
void KilledUnit (Unit *) override
Called when the creature kills a unit.
void JustDied (Unit *) override
Called when the creature is killed.
void JustReachedHome () override
Called at reaching home after MoveTargetedHome.
void JustSummoned (Creature *summoned) override
Called when the creature summon successfully other creature.
void SpellHit (Unit *, const SpellEntry *spellInfo) override
Called when hit by a spell.
void SpellHitTarget (Unit *target, const SpellEntry *spellInfo) override
void OnSpellInterrupt (SpellEntry const *spellInfo) override
void MovementInform (uint32 motionType, uint32 pointId) override
Called at waypoint reached or point movement finished.
void AdvisorDefeated (uint32 uiEntry)
void ExecuteActions ()
void UpdateAI (const uint32 uiDiff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
virtual void Aggro (Unit *)
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Data Fields
ScriptedInstance * m_instance
uint32 m_uiFireballTimer
uint32 m_uiArcaneDisruptionTimer
uint32 m_uiPhoenixTimer
uint32 m_uiFlameStrikeTimer
uint32 m_pyroblastCounter
uint32 m_uiShockBarrierTimer
uint32 m_uiMindControlTimer
uint32 m_uiExplodeTimer
uint32 m_uiGravityLapseTimer
uint32 m_uiGravityExpireTimer
uint32 m_uiNetherBeamTimer
uint32 m_uiNetherVaporTimer
uint8 m_uiGravityIndex
uint32 m_uiPhaseTimer
uint8 m_uiPhase
uint8 m_uiPhaseSubphase
uint32 m_phaseTransitionTimer
uint32 m_phaseTransitionStage
uint32 m_phaseTransitionGrowthTimer
uint32 m_phaseTransitionGrowthStage
uint32 m_phaseTransitionPureNetherBeamTimer
uint32 m_phaseTransitionPureNetherBeamStage
GuidVector m_worldTriggersFirstStage
GuidVector m_worldTriggersExplosions
GuidVector m_worldTriggersSecondStage
GuidVector m_netherVapor
GuidList m_lSummonedGuidList
GuidVector m_weapons
uint32 m_weaponAttackTimer
GuidSet m_charmTargets
bool m_actionReadyStatus [KAEL_ACTION_MAX]
bool m_rangeMode
Additional Inherited Members
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 259 of file boss_kaelthas.cpp.
Constructor & Destructor Documentation
boss_kaelthasAI()
boss_kaelthasAI::boss_kaelthasAI (Creature * creature) inline
Definition at line 261 of file boss_kaelthas.cpp.
References Reset().
Member Function Documentation
AdvisorDefeated()
void boss_kaelthasAI::AdvisorDefeated (uint32 uiEntry) inline
Definition at line 599 of file boss_kaelthas.cpp.
References m_uiPhase, m_uiPhaseTimer, NPC_TELONICUS, and PHASE_1_ADVISOR.
DoDespawnSummons()
void boss_kaelthasAI::DoDespawnSummons () inline
Definition at line 401 of file boss_kaelthas.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Map::GetCreature(), WorldObject::GetMap(), CreatureAI::m_creature, m_lSummonedGuidList, m_netherVapor, NPC_PHOENIX, and UnitAI::SendAIEvent().
Referenced by JustDied(), ReceiveAIEvent(), and Reset().
ExecuteActions()
void boss_kaelthasAI::ExecuteActions () inline virtual
Reimplemented from UnitAI.
Definition at line 611 of file boss_kaelthas.cpp.
References aCenterPos, ATTACKING_TARGET_RANDOM, Unit::CanReactInCombat(), CAST_AURA_NOT_PRESENT, CAST_OK, Unit::CastSpell(), UnitAI::DoCastSpellIfCan(), DoScriptText(), ScriptedAI::DoStartMovement(), EMOTE_PYROBLAST, FORCED_MOVEMENT_RUN, UnitAI::GetCombatScriptStatus(), Unit::GetHealthPercent(), Unit::GetMotionMaster(), ThreatManager::getThreatList(), Unit::getThreatManager(), Unit::GetVictim(), Unit::hasUnitState(), Unit::InterruptNonMeleeSpells(), Unit::IsNonMeleeSpellCasted(), WorldObject::IsSpellReady(), WorldObject::IsWithinCombatDist(), KAEL_ACTION_ARCANE_DISRUPTION, KAEL_ACTION_FIREBALL, KAEL_ACTION_FLAMESTRIKE, KAEL_ACTION_GRAVITY_LAPSE, KAEL_ACTION_MAX, KAEL_ACTION_MELEE_MODE, KAEL_ACTION_MIND_CONTROL, KAEL_ACTION_NETHER_BEAM, KAEL_ACTION_NETHER_VAPOR, KAEL_ACTION_PHASE_5, KAEL_ACTION_PHOENIX, KAEL_ACTION_PYROBLAST_INIT, KAEL_ACTION_PYROBLAST_SEQUENCE, KAEL_ACTION_SHOCK_BARRIER, m_actionReadyStatus, UnitAI::m_attackDistance, CreatureAI::m_creature, m_pyroblastCounter, m_rangeMode, m_uiArcaneDisruptionTimer, m_uiFireballTimer, m_uiFlameStrikeTimer, m_uiGravityExpireTimer, m_uiGravityIndex, m_uiGravityLapseTimer, m_uiMindControlTimer, m_uiNetherBeamTimer, m_uiNetherVaporTimer, m_uiPhase, m_uiPhoenixTimer, m_uiShockBarrierTimer, UnitAI::m_unit, Unit::MeleeAttackStart(), MotionMaster::MovePoint(), PHASE_4_SOLO, PHASE_5_GRAVITY, PHASE_TRANSITION, POINT_ID_CENTER, SAY_GRAVITYLAPSE1, SAY_GRAVITYLAPSE2, SAY_MINDCONTROL1, SAY_MINDCONTROL2, SAY_SUMMON_PHOENIX1, SAY_SUMMON_PHOENIX2, SELECT_FLAG_PLAYER, Unit::SelectAttackingTarget(), UnitAI::SetCombatMovement(), UnitAI::SetCombatScriptStatus(), UnitAI::SetMeleeEnabled(), Unit::SetTarget(), SPELL_ARCANE_DISRUPTION, SPELL_BANISH, SPELL_FIREBALL, SPELL_FLAME_STRIKE, SPELL_GRAVITY_LAPSE, SPELL_MIND_CONTROL, SPELL_NETHER_BEAM, SPELL_NETHER_VAPOR_SUMMON, SPELL_PHOENIX_ANIMATION, SPELL_PYROBLAST, SPELL_SHOCK_BARRIER, TRIGGERED_OLD_TRIGGERED, UNIT_STAT_CHANNELING, UNIT_STAT_PROPELLED, UNIT_STAT_RETREATING, and urand().
Referenced by UpdateAI().
GetAIInformation()
void boss_kaelthasAI::GetAIInformation (ChatHandler & reader) inline override virtual
This function shows if combat movement is enabled, overwrite for more info.
Reimplemented from ScriptedAI.
Definition at line 388 of file boss_kaelthas.cpp.
References m_uiPhase, and ChatHandler::PSendSysMessage().
JustDied()
void boss_kaelthasAI::JustDied (Unit *) inline override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from UnitAI.
Definition at line 451 of file boss_kaelthas.cpp.
References Unit::CastSpell(), DoDespawnSummons(), DONE, DoScriptText(), CreatureAI::m_creature, m_instance, ResetSize(), SAY_DEATH, InstanceData::SetData(), SPELL_REMOVE_WEAPONS, TRIGGERED_OLD_TRIGGERED, and TYPE_KAELTHAS.
JustReachedHome()
void boss_kaelthasAI::JustReachedHome () inline override virtual
Called at reaching home after MoveTargetedHome.
Reimplemented from UnitAI.
Definition at line 463 of file boss_kaelthas.cpp.
References Unit::CastSpell(), FAIL, CreatureAI::m_creature, m_instance, InstanceData::SetData(), SPELL_REMOVE_WEAPONS, TRIGGERED_OLD_TRIGGERED, and TYPE_KAELTHAS.
JustRespawned()
void boss_kaelthasAI::JustRespawned () inline virtual
This will by default result in reattacking, if the creature has no victim.
This function calls Reset() to reset variables as expected.
Reimplemented from ScriptedAI.
Definition at line 379 of file boss_kaelthas.cpp.
References aAdvisors, ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedAI::JustRespawned(), and m_instance.
JustSummoned()
void boss_kaelthasAI::JustSummoned (Creature *) inline override virtual
Called when the creature summon successfully other creature.
Parameters
pSummoned Creature that got summoned
Reimplemented from UnitAI.
Definition at line 471 of file boss_kaelthas.cpp.
References Creature::AI(), CAST_AURA_NOT_PRESENT, CAST_FORCE_TARGET_SELF, CAST_TRIGGERED, UnitAI::DoCastSpellIfCan(), Object::GetEntry(), Object::GetObjectGuid(), m_lSummonedGuidList, m_netherVapor, m_weaponAttackTimer, m_weapons, NPC_FLAME_STRIKE_TRIGGER, NPC_NETHER_VAPOR, REACT_PASSIVE, Creature::SetCorpseDelay(), UnitAI::SetReactState(), and SPELL_FLAME_STRIKE_DUMMY.
KilledUnit()
void boss_kaelthasAI::KilledUnit (Unit *) inline override virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented from UnitAI.
Definition at line 441 of file boss_kaelthas.cpp.
References DoScriptText(), CreatureAI::m_creature, SAY_SLAY1, SAY_SLAY2, SAY_SLAY3, and urand().
MoveInLineOfSight()
void boss_kaelthasAI::MoveInLineOfSight (Unit * who) inline override virtual
== Reactions At =================================
Called if IsVisible(Unit* pWho) is true at each (relative) override pWho move, reaction at visibility zone enter Note: The Unit* pWho can be out of Line of Sight, usually this is only visibiliy (by state) and range dependendend Note: This function is not called for creatures who are in evade mode
Parameters
pWho Unit* who moved in the visibility range and is visisble
Reimplemented from UnitAI.
Definition at line 418 of file boss_kaelthas.cpp.
References Unit::CanAttackOnSight(), Unit::CastSpell(), DoScriptText(), Unit::GetAttackDistance(), Object::HasFlag(), IN_PROGRESS, Player::IsGameMaster(), Object::IsPlayer(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), CreatureAI::m_creature, m_instance, m_uiPhase, PHASE_0_NOT_BEGUN, PHASE_1_ADVISOR, SAY_INTRO, UnitAI::SetCombatMovement(), UnitAI::SetCombatScriptStatus(), InstanceData::SetData(), Object::SetFlag(), Creature::SetInCombatWithZone(), SPELL_REMOVE_WEAPONS, TRIGGERED_OLD_TRIGGERED, TYPE_KAELTHAS, UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED, and UNIT_FLAG_UNINTERACTIBLE.
MovementInform()
void boss_kaelthasAI::MovementInform (uint32 , uint32) inline override virtual
Called at waypoint reached or point movement finished.
Parameters
uiMovementType Type of the movement (enum MovementGeneratorType)
uiData Data related to the finished movement (ie point-id)
Reimplemented from UnitAI.
Definition at line 539 of file boss_kaelthas.cpp.
References DoScriptText(), ScriptedAI::DoStartMovement(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), Unit::GetVictim(), CreatureAI::m_creature, m_instance, m_phaseTransitionTimer, m_uiArcaneDisruptionTimer, m_uiPhase, m_worldTriggersExplosions, m_worldTriggersFirstStage, m_worldTriggersSecondStage, NPC_WORLD_TRIGGER_LARGE, PHASE_5_GRAVITY, POINT_ID_CENTER, POINT_ID_LAND, POINT_MOTION_TYPE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_PHASE5_NUTS, UnitAI::SetCombatMovement(), UnitAI::SetCombatScriptStatus(), Unit::SetFacingTo(), Object::SetFlag(), Unit::SetHover(), Unit::SetLevitate(), Unit::SetTarget(), sLog, SPELL_KAEL_FULL_POWER, triggers, TRIGGERS_EXPLOSION, TRIGGERS_FIRST_STAGE, TRIGGERS_TOTAL, UNIT_FIELD_FLAGS, and UNIT_FLAG_UNINTERACTIBLE.
OnSpellInterrupt()
void boss_kaelthasAI::OnSpellInterrupt (SpellEntry const * spellInfo) inline override virtual
Reimplemented from UnitAI.
Definition at line 533 of file boss_kaelthas.cpp.
References SpellEntry::Id, KAEL_ACTION_PYROBLAST_SEQUENCE, m_actionReadyStatus, and SPELL_PYROBLAST.
ReceiveAIEvent()
void boss_kaelthasAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) inline override virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented from ScriptedAI.
Definition at line 393 of file boss_kaelthas.cpp.
References AI_EVENT_CUSTOM_B, and DoDespawnSummons().
Reset()
void boss_kaelthasAI::Reset () inline override virtual
Reimplemented from CreatureAI.
Definition at line 311 of file boss_kaelthas.cpp.
References DoDespawnSummons(), KAEL_ACTION_FIREBALL, KAEL_ACTION_MAX, KAEL_ACTION_MELEE_MODE, KAEL_ACTION_PHASE_5, m_actionReadyStatus, UnitAI::m_attackAngle, UnitAI::m_attackDistance, m_charmTargets, m_phaseTransitionGrowthStage, m_phaseTransitionGrowthTimer, m_phaseTransitionPureNetherBeamStage, m_phaseTransitionPureNetherBeamTimer, m_phaseTransitionStage, m_phaseTransitionTimer, m_rangeMode, m_uiArcaneDisruptionTimer, m_uiExplodeTimer, m_uiFireballTimer, m_uiFlameStrikeTimer, m_uiGravityExpireTimer, m_uiGravityIndex, m_uiGravityLapseTimer, m_uiMindControlTimer, m_uiNetherBeamTimer, m_uiNetherVaporTimer, m_uiPhase, m_uiPhaseSubphase, m_uiPhaseTimer, m_uiPhoenixTimer, m_uiShockBarrierTimer, PHASE_0_NOT_BEGUN, ResetSize(), UnitAI::SetCombatMovement(), UnitAI::SetCombatScriptStatus(), and UnitAI::SetMeleeEnabled().
Referenced by boss_kaelthasAI().
ResetSize()
void boss_kaelthasAI::ResetSize () inline
Definition at line 371 of file boss_kaelthas.cpp.
References CreatureAI::m_creature, MOVE_RUN, OBJECT_FIELD_SCALE_X, Object::SetFloatValue(), Unit::UpdateModelData(), and Unit::UpdateSpeed().
Referenced by JustDied(), and Reset().
SpellHit()
void boss_kaelthasAI::SpellHit (Unit * , const SpellEntry *) inline override virtual
Called when hit by a spell.
Parameters
pCaster Caster who casted the spell
pSpell The spell that hit the creature
Reimplemented from UnitAI.
Definition at line 498 of file boss_kaelthas.cpp.
References CAST_TRIGGERED, UnitAI::DoCastSpellIfCan(), SpellEntry::Id, m_auiSpellSummonWeapon, CreatureAI::m_creature, m_uiPhase, m_uiPhaseTimer, PHASE_2_WEAPON, and SPELL_SUMMON_WEAPONS.
SpellHitTarget()
void boss_kaelthasAI::SpellHitTarget (Unit * target, const SpellEntry * spellInfo) inline override virtual
Reimplemented from UnitAI.
Definition at line 518 of file boss_kaelthas.cpp.
References CAST_TRIGGERED, Unit::CastSpell(), UnitAI::DoCastSpellIfCan(), Object::GetObjectGuid(), Object::GetTypeId(), SpellEntry::Id, m_auiSpellGravityLapseTeleport, m_charmTargets, m_uiGravityIndex, SPELL_GRAVITY_LAPSE, SPELL_GRAVITY_LAPSE_AURA, SPELL_GRAVITY_LAPSE_KNOCKBACK, SPELL_MIND_CONTROL, TRIGGERED_OLD_TRIGGERED, and TYPEID_PLAYER.
UpdateAI()
void boss_kaelthasAI::UpdateAI (const uint32 diff) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented from UnitAI.
Definition at line 823 of file boss_kaelthas.cpp.
References CAST_OK, Unit::CastSpell(), UnitAI::DoCastSpellIfCan(), UnitAI::DoMeleeAttackIfReady(), UnitAI::DoResetThreat(), DoScriptText(), ScriptedInstance::DoUseDoorOrButton(), ExecuteActions(), flightPos, FORCED_MOVEMENT_WALK, Map::GetCreature(), WorldObject::GetMap(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_BRIDGE_WINDOW, GO_KAEL_STATUE_LEFT, GO_KAEL_STATUE_RIGHT, groupOneIndices, groupThreeIndices, groupTwoIndices, KAEL_ACTION_ARCANE_DISRUPTION, KAEL_ACTION_FIREBALL, KAEL_ACTION_FLAMESTRIKE, KAEL_ACTION_GRAVITY_LAPSE, KAEL_ACTION_MIND_CONTROL, KAEL_ACTION_NETHER_BEAM, KAEL_ACTION_NETHER_VAPOR, KAEL_ACTION_PHOENIX, KAEL_ACTION_PYROBLAST_INIT, KAEL_ACTION_SHOCK_BARRIER, landPos, m_actionReadyStatus, CreatureAI::m_creature, m_instance, m_netherVapor, m_phaseTransitionGrowthStage, m_phaseTransitionGrowthTimer, m_phaseTransitionPureNetherBeamStage, m_phaseTransitionPureNetherBeamTimer, m_phaseTransitionStage, m_phaseTransitionTimer, m_uiArcaneDisruptionTimer, m_uiFireballTimer, m_uiFlameStrikeTimer, m_uiGravityExpireTimer, m_uiGravityLapseTimer, m_uiMindControlTimer, m_uiNetherBeamTimer, m_uiNetherVaporTimer, m_uiPhase, m_uiPhaseSubphase, m_uiPhaseTimer, m_uiPhoenixTimer, m_uiShockBarrierTimer, m_weaponAttackTimer, m_weapons, m_worldTriggersExplosions, m_worldTriggersFirstStage, m_worldTriggersSecondStage, MotionMaster::MovePoint(), NPC_CAPERNIAN, NPC_SANGUINAR, NPC_TELONICUS, NPC_THALADRED, PHASE_1_ADVISOR, PHASE_2_WEAPON, PHASE_3_ADVISOR_ALL, PHASE_4_SOLO, PHASE_5_GRAVITY, PHASE_TRANSITION, WorldObject::PlayDirectSound(), POINT_ID_AIR, POINT_ID_LAND, REACT_AGGRESSIVE, Unit::RemoveAurasDueToSpell(), Object::RemoveFlag(), SAY_INTRO_CAPERNIAN, SAY_INTRO_SANGUINAR, SAY_INTRO_TELONICUS, SAY_INTRO_THALADRED, SAY_PHASE2_WEAPON, SAY_PHASE3_ADVANCE, SAY_PHASE4_INTRO2, Unit::SelectHostileTarget(), UnitAI::SetCombatMovement(), UnitAI::SetCombatScriptStatus(), Unit::SetHover(), Unit::SetLevitate(), UnitAI::SetMeleeEnabled(), WorldObject::SetOrientation(), SOUND_PHASE_TRANSITION1, SOUND_PHASE_TRANSITION2, SPELL_EXPLODE, SPELL_EXPLODE_1, SPELL_EXPLODE_2, SPELL_EXPLODE_3, SPELL_EXPLODE_4, SPELL_FLOATING_DROWNED, SPELL_KAEL_FULL_POWER, SPELL_KAEL_GAIN_POWER, SPELL_KAEL_STUN, SPELL_NETHERBEAM, SPELL_NETHERBEAM_EXPLODE, SPELL_NETHERBEAM_GLOW3, SPELL_RESURRECTION, SPELL_SUMMON_WEAPONS, TRIGGERED_NONE, TRIGGERS_GROUP_ONE, TRIGGERS_GROUP_THREE, TRIGGERS_GROUP_TWO, triggerSpellIds, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_UNINTERACTIBLE, and urand().
Field Documentation
m_actionReadyStatus
bool boss_kaelthasAI::m_actionReadyStatus[KAEL_ACTION_MAX]
Definition at line 307 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), OnSpellInterrupt(), Reset(), and UpdateAI().
m_charmTargets
GuidSet boss_kaelthasAI::m_charmTargets
Definition at line 305 of file boss_kaelthas.cpp.
Referenced by Reset(), and SpellHitTarget().
m_instance
ScriptedInstance* boss_kaelthasAI::m_instance
Definition at line 266 of file boss_kaelthas.cpp.
Referenced by JustDied(), JustReachedHome(), JustRespawned(), MoveInLineOfSight(), MovementInform(), and UpdateAI().
m_lSummonedGuidList
GuidList boss_kaelthasAI::m_lSummonedGuidList
Definition at line 301 of file boss_kaelthas.cpp.
Referenced by DoDespawnSummons(), and JustSummoned().
m_netherVapor
GuidVector boss_kaelthasAI::m_netherVapor
Definition at line 300 of file boss_kaelthas.cpp.
Referenced by DoDespawnSummons(), JustSummoned(), and UpdateAI().
m_phaseTransitionGrowthStage
uint32 boss_kaelthasAI::m_phaseTransitionGrowthStage
Definition at line 292 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_phaseTransitionGrowthTimer
uint32 boss_kaelthasAI::m_phaseTransitionGrowthTimer
Definition at line 291 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_phaseTransitionPureNetherBeamStage
uint32 boss_kaelthasAI::m_phaseTransitionPureNetherBeamStage
Definition at line 294 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_phaseTransitionPureNetherBeamTimer
uint32 boss_kaelthasAI::m_phaseTransitionPureNetherBeamTimer
Definition at line 293 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_phaseTransitionStage
uint32 boss_kaelthasAI::m_phaseTransitionStage
Definition at line 289 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_phaseTransitionTimer
uint32 boss_kaelthasAI::m_phaseTransitionTimer
Definition at line 288 of file boss_kaelthas.cpp.
Referenced by MovementInform(), Reset(), and UpdateAI().
m_pyroblastCounter
uint32 boss_kaelthasAI::m_pyroblastCounter
Definition at line 273 of file boss_kaelthas.cpp.
Referenced by ExecuteActions().
m_rangeMode
bool boss_kaelthasAI::m_rangeMode
Definition at line 309 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), and Reset().
m_uiArcaneDisruptionTimer
uint32 boss_kaelthasAI::m_uiArcaneDisruptionTimer
Definition at line 269 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), MovementInform(), Reset(), and UpdateAI().
m_uiExplodeTimer
uint32 boss_kaelthasAI::m_uiExplodeTimer
Definition at line 276 of file boss_kaelthas.cpp.
Referenced by Reset().
m_uiFireballTimer
uint32 boss_kaelthasAI::m_uiFireballTimer
Definition at line 268 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiFlameStrikeTimer
uint32 boss_kaelthasAI::m_uiFlameStrikeTimer
Definition at line 271 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiGravityExpireTimer
uint32 boss_kaelthasAI::m_uiGravityExpireTimer
Definition at line 279 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiGravityIndex
uint8 boss_kaelthasAI::m_uiGravityIndex
Definition at line 282 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and SpellHitTarget().
m_uiGravityLapseTimer
uint32 boss_kaelthasAI::m_uiGravityLapseTimer
Definition at line 278 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiMindControlTimer
uint32 boss_kaelthasAI::m_uiMindControlTimer
Definition at line 275 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiNetherBeamTimer
uint32 boss_kaelthasAI::m_uiNetherBeamTimer
Definition at line 280 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiNetherVaporTimer
uint32 boss_kaelthasAI::m_uiNetherVaporTimer
Definition at line 281 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiPhase
uint8 boss_kaelthasAI::m_uiPhase
Definition at line 285 of file boss_kaelthas.cpp.
Referenced by AdvisorDefeated(), ExecuteActions(), GetAIInformation(), MoveInLineOfSight(), MovementInform(), Reset(), SpellHit(), and UpdateAI().
m_uiPhaseSubphase
uint8 boss_kaelthasAI::m_uiPhaseSubphase
Definition at line 286 of file boss_kaelthas.cpp.
Referenced by Reset(), and UpdateAI().
m_uiPhaseTimer
uint32 boss_kaelthasAI::m_uiPhaseTimer
Definition at line 284 of file boss_kaelthas.cpp.
Referenced by AdvisorDefeated(), Reset(), SpellHit(), and UpdateAI().
m_uiPhoenixTimer
uint32 boss_kaelthasAI::m_uiPhoenixTimer
Definition at line 270 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_uiShockBarrierTimer
uint32 boss_kaelthasAI::m_uiShockBarrierTimer
Definition at line 274 of file boss_kaelthas.cpp.
Referenced by ExecuteActions(), Reset(), and UpdateAI().
m_weaponAttackTimer
uint32 boss_kaelthasAI::m_weaponAttackTimer
Definition at line 303 of file boss_kaelthas.cpp.
Referenced by JustSummoned(), and UpdateAI().
m_weapons
GuidVector boss_kaelthasAI::m_weapons
Definition at line 302 of file boss_kaelthas.cpp.
Referenced by JustSummoned(), and UpdateAI().
m_worldTriggersExplosions
GuidVector boss_kaelthasAI::m_worldTriggersExplosions
Definition at line 297 of file boss_kaelthas.cpp.
Referenced by MovementInform(), and UpdateAI().
m_worldTriggersFirstStage
GuidVector boss_kaelthasAI::m_worldTriggersFirstStage
Definition at line 296 of file boss_kaelthas.cpp.
Referenced by MovementInform(), and UpdateAI().
m_worldTriggersSecondStage
GuidVector boss_kaelthasAI::m_worldTriggersSecondStage
Definition at line 298 of file boss_kaelthas.cpp.
Referenced by MovementInform(), and UpdateAI().
The documentation for this struct was generated from the following file:
boss_kaelthas.cpp