CMaNGOS_WoTLK: FormationMap Struct Reference
FormationMap Struct Reference
Public Member Functions
void clearMaps ()
void registerFormationMarker (ObjectGuid marker)
ObjectGuid claimFormationMarker (ObjectGuid occupant)
bool releaseFormationMarker (ObjectGuid occupant)
ObjectGuid getRandomOccupant ()
void EngageInBlackTempleAssault (int numberTroops, int point, Map *map)
Data Fields
std::map< ObjectGuid, ObjectGuid > markerToOccupant
std::map< ObjectGuid, ObjectGuid > occupantToMarker
Detailed Description
Definition at line 4352 of file shadowmoon_valley.cpp.
Member Function Documentation
claimFormationMarker()
ObjectGuid FormationMap::claimFormationMarker (ObjectGuid occupant) inline
Definition at line 4369 of file shadowmoon_valley.cpp.
References ObjectGuid::IsEmpty(), markerToOccupant, occupantToMarker, and urand().
Referenced by npc_bt_battle_sensor::GetAvailableMarkerFromMap().
clearMaps()
void FormationMap::clearMaps () inline
Definition at line 4357 of file shadowmoon_valley.cpp.
References markerToOccupant, and occupantToMarker.
Referenced by npc_bt_battle_sensor::FindFormationMarkers(), and npc_bt_battle_sensor::Reset().
EngageInBlackTempleAssault()
void FormationMap::EngageInBlackTempleAssault (int numberTroops, int point, Map * map) inline
Definition at line 4423 of file shadowmoon_valley.cpp.
References Map::GetCreature(), occupantToMarker, and releaseFormationMarker().
Referenced by npc_bt_battle_sensor::ReceiveAIEvent().
getRandomOccupant()
ObjectGuid FormationMap::getRandomOccupant () inline
Definition at line 4408 of file shadowmoon_valley.cpp.
References occupantToMarker, and urand().
Referenced by npc_bt_battle_sensor::ReinforceAldorScryerFrontline().
registerFormationMarker()
void FormationMap::registerFormationMarker (ObjectGuid marker) inline
Definition at line 4363 of file shadowmoon_valley.cpp.
References markerToOccupant.
Referenced by npc_bt_battle_sensor::FindFormationMarkers().
releaseFormationMarker()
bool FormationMap::releaseFormationMarker (ObjectGuid occupant) inline
Definition at line 4398 of file shadowmoon_valley.cpp.
References markerToOccupant, and occupantToMarker.
Referenced by EngageInBlackTempleAssault(), npc_bt_battle_sensor::ReceiveAIEvent(), and npc_bt_battle_sensor::ReinforceAldorScryerFrontline().
Field Documentation
markerToOccupant
std::map<ObjectGuid, ObjectGuid> FormationMap::markerToOccupant
Definition at line 4354 of file shadowmoon_valley.cpp.
Referenced by claimFormationMarker(), clearMaps(), registerFormationMarker(), and releaseFormationMarker().
occupantToMarker
std::map<ObjectGuid, ObjectGuid> FormationMap::occupantToMarker
Definition at line 4355 of file shadowmoon_valley.cpp.
Referenced by claimFormationMarker(), clearMaps(), EngageInBlackTempleAssault(), getRandomOccupant(), and releaseFormationMarker().
The documentation for this struct was generated from the following file:
shadowmoon_valley.cpp