CMaNGOS_WoTLK: LfgProposal Struct Reference
LfgProposal Struct Reference
Stores group data related to proposal to join.
#include <LFGQueue.h>
Public Member Functions
LfgProposal (uint32 dungeon=0)
void UpdatePlayerProposal (ObjectGuid guid, bool accept)
Players data.
void UpdateProposal (LFGQueue &queue)
void FailProposal (LFGQueue &queue)
void AcceptProposal (LFGQueue &queue)
Data Fields
uint32 id
uint32 dungeonId
Proposal Id.
LfgProposalState state
Dungeon to join.
ObjectGuid group
State of the proposal.
ObjectGuid leader
Proposal group (0 if new)
TimePoint cancelTime
Leader guid.
uint32 encounters
Time when we will cancel this proposal.
bool isNew
Dungeon Encounters.
GuidList queues
Determines if it's new group or not.
GuidList showorder
Queue Ids to remove/readd.
LfgProposalPlayerContainer players
Show order in update window.
Detailed Description
Stores group data related to proposal to join.
Definition at line 55 of file LFGQueue.h.
Constructor & Destructor Documentation
LfgProposal()
LfgProposal::LfgProposal (uint32 dungeon = 0) inline
Definition at line 57 of file LFGQueue.h.
Member Function Documentation
AcceptProposal()
void LfgProposal::AcceptProposal (LFGQueue & queue)
Definition at line 407 of file LFGQueue.cpp.
References Group::AddMember(), World::BroadcastPersonalized(), WorldSession::BuildLfgUpdate(), WorldSession::BuildLfgUpdateProposal(), dungeonId, ObjectGuid::GetCounter(), LFGQueueData::GetJoinTime(), LFGQueue::GetPartyMemberCountAtJoin(), LFGQueue::GetQueueData(), group, LFGDungeonData::id, isNew, leader, LFG_PROPOSAL_SUCCESS, LFG_STATE_DUNGEON, LFG_UPDATETYPE_GROUP_FOUND, LFG_UPDATETYPE_REMOVED_FROM_QUEUE, LFGQueueData::m_playerInfoPerGuid, LFGQueuePlayer::m_roles, MANGOS_ASSERT, PLAYER_ROLE_DAMAGE, PLAYER_ROLE_HEALER, PLAYER_ROLE_LEADER, PLAYER_ROLE_TANK, players, queues, LFGQueue::RemoveFromQueue(), LFGQueue::RemoveProposal(), LFGQueue::SetPartyMemberCountAtJoin(), LFGQueueData::SetState(), sLFGMgr, sObjectMgr, state, sWorld, LfgUpdateData::updateType, LFGQueue::UpdateWaitTimeAvg(), LFGQueue::UpdateWaitTimeDps(), LFGQueue::UpdateWaitTimeHealer(), and LFGQueue::UpdateWaitTimeTank().
Referenced by UpdateProposal().
FailProposal()
void LfgProposal::FailProposal (LFGQueue & queue)
Definition at line 360 of file LFGQueue.cpp.
References LfgProposalPlayer::answer, World::BroadcastPersonalized(), WorldSession::BuildLfgUpdate(), LFGQueue::GetQueueData(), LfgProposalPlayer::group, ObjectGuid::IsGroup(), LFG_PROPOSAL_FAILED, LFG_STATE_FAILED, LFG_STATE_QUEUED, LFG_UPDATETYPE_PROPOSAL_DECLINED, LFG_UPDATETYPE_PROPOSAL_FAILED, LFG_UPDATETYPE_REMOVED_FROM_QUEUE, LFGQueueData::m_ownerGuid, LFGQueueData::m_playerInfoPerGuid, players, queues, LFGQueue::RemoveProposal(), LFGQueueData::SetState(), state, sWorld, and LfgUpdateData::updateType.
Referenced by UpdateProposal().
UpdatePlayerProposal()
void LfgProposal::UpdatePlayerProposal (ObjectGuid guid, bool accept)
Players data.
Definition at line 325 of file LFGQueue.cpp.
References players.
Referenced by LFGQueue::UpdateProposal().
UpdateProposal()
void LfgProposal::UpdateProposal (LFGQueue & queue)
Definition at line 330 of file LFGQueue.cpp.
References AcceptProposal(), cancelTime, FailProposal(), LFG_ANSWER_DENY, LFG_ANSWER_PENDING, players, and sWorld.
Referenced by LFGQueue::Update().
Field Documentation
cancelTime
TimePoint LfgProposal::cancelTime
Leader guid.
Definition at line 66 of file LFGQueue.h.
Referenced by LFGQueueData::PopQueue(), and UpdateProposal().
dungeonId
uint32 LfgProposal::dungeonId
Proposal Id.
Definition at line 62 of file LFGQueue.h.
Referenced by AcceptProposal(), WorldSession::BuildLfgUpdateProposal(), and LFGQueueData::PopQueue().
encounters
uint32 LfgProposal::encounters
Time when we will cancel this proposal.
Definition at line 67 of file LFGQueue.h.
Referenced by WorldSession::BuildLfgUpdateProposal(), and LFGQueueData::PopQueue().
group
ObjectGuid LfgProposal::group
State of the proposal.
Definition at line 64 of file LFGQueue.h.
Referenced by AcceptProposal(), WorldSession::BuildLfgUpdateProposal(), and LFGQueueData::PopQueue().
id
uint32 LfgProposal::id
Definition at line 61 of file LFGQueue.h.
Referenced by WorldSession::BuildLfgUpdateProposal(), and LFGQueue::Update().
isNew
bool LfgProposal::isNew
Dungeon Encounters.
Definition at line 68 of file LFGQueue.h.
Referenced by AcceptProposal(), WorldSession::BuildLfgUpdateProposal(), and LFGQueueData::PopQueue().
leader
ObjectGuid LfgProposal::leader
Proposal group (0 if new)
Definition at line 65 of file LFGQueue.h.
Referenced by AcceptProposal(), and LFGQueueData::PopQueue().
players
LfgProposalPlayerContainer LfgProposal::players
Show order in update window.
Definition at line 71 of file LFGQueue.h.
Referenced by AcceptProposal(), WorldSession::BuildLfgUpdateProposal(), FailProposal(), LFGQueueData::PopQueue(), UpdatePlayerProposal(), and UpdateProposal().
queues
GuidList LfgProposal::queues
Determines if it's new group or not.
Definition at line 69 of file LFGQueue.h.
Referenced by AcceptProposal(), FailProposal(), LFGQueueData::PopQueue(), and LFGQueue::UpdateProposal().
showorder
GuidList LfgProposal::showorder
Queue Ids to remove/readd.
Definition at line 70 of file LFGQueue.h.
state
LfgProposalState LfgProposal::state
Dungeon to join.
Definition at line 63 of file LFGQueue.h.
Referenced by AcceptProposal(), WorldSession::BuildLfgUpdateProposal(), FailProposal(), and LFGQueueData::PopQueue().
The documentation for this struct was generated from the following files:
LFGQueue.h
LFGQueue.cpp