CMaNGOS_WoTLK: Channel::PlayerInfo Struct Reference
Channel::PlayerInfo Struct Reference
Public Member Functions
bool HasFlag (uint8 flag) const
void SetFlag (uint8 flag, bool state)
bool IsOwner () const
void SetOwner (bool state)
bool IsModerator () const
void SetModerator (bool state)
bool IsMuted () const
void SetMuted (bool state)
Data Fields
ObjectGuid player
uint8 flags
Detailed Description
Definition at line 122 of file Channel.h.
Member Function Documentation
HasFlag()
bool Channel::PlayerInfo::HasFlag (uint8 flag) const inline
Definition at line 127 of file Channel.h.
References flags.
Referenced by IsModerator(), IsMuted(), and IsOwner().
IsModerator()
bool Channel::PlayerInfo::IsModerator () const inline
Definition at line 131 of file Channel.h.
References HasFlag(), and Channel::MEMBER_FLAG_MODERATOR.
IsMuted()
bool Channel::PlayerInfo::IsMuted () const inline
Definition at line 133 of file Channel.h.
References HasFlag(), and Channel::MEMBER_FLAG_MUTED.
IsOwner()
bool Channel::PlayerInfo::IsOwner () const inline
Definition at line 129 of file Channel.h.
References HasFlag(), and Channel::MEMBER_FLAG_OWNER.
SetFlag()
void Channel::PlayerInfo::SetFlag (uint8 flag, bool state) inline
Definition at line 128 of file Channel.h.
References flags.
Referenced by SetModerator(), SetMuted(), and SetOwner().
SetModerator()
void Channel::PlayerInfo::SetModerator (bool state) inline
Definition at line 132 of file Channel.h.
References Channel::MEMBER_FLAG_MODERATOR, and SetFlag().
SetMuted()
void Channel::PlayerInfo::SetMuted (bool state) inline
Definition at line 134 of file Channel.h.
References Channel::MEMBER_FLAG_MUTED, and SetFlag().
SetOwner()
void Channel::PlayerInfo::SetOwner (bool state) inline
Definition at line 130 of file Channel.h.
References Channel::MEMBER_FLAG_OWNER, and SetFlag().
Field Documentation
flags
uint8 Channel::PlayerInfo::flags
Definition at line 125 of file Channel.h.
Referenced by HasFlag(), Channel::Join(), and SetFlag().
player
ObjectGuid Channel::PlayerInfo::player
Definition at line 124 of file Channel.h.
Referenced by Channel::Join().
The documentation for this struct was generated from the following file:
Channel.h