CMaNGOS_WoTLK: UpdateZoneDependentPetsHelper Struct Reference
UpdateZoneDependentPetsHelper Struct Reference
Public Member Functions
UpdateZoneDependentPetsHelper (Player *_owner, uint32 zone, uint32 area)
void operator() (Unit *unit) const
Data Fields
Player * owner
uint32 zone_id
uint32 area_id
Detailed Description
Definition at line 22377 of file Player.cpp.
Constructor & Destructor Documentation
UpdateZoneDependentPetsHelper()
UpdateZoneDependentPetsHelper::UpdateZoneDependentPetsHelper (Player * _owner, uint32 zone, uint32 area) inline explicit
Definition at line 22379 of file Player.cpp.
Member Function Documentation
operator()()
void UpdateZoneDependentPetsHelper::operator() (Unit * unit) const inline
Definition at line 22380 of file Player.cpp.
References Object::GetTypeId(), Object::GetUInt32Value(), SQLStorage::LookupEntry(), PET_SAVE_AS_DELETED, SPELL_CAST_OK, sSpellMgr, sSpellTemplate, TYPEID_UNIT, and UNIT_CREATED_BY_SPELL.
Field Documentation
area_id
uint32 UpdateZoneDependentPetsHelper::area_id
Definition at line 22390 of file Player.cpp.
owner
Player* UpdateZoneDependentPetsHelper::owner
Definition at line 22388 of file Player.cpp.
zone_id
uint32 UpdateZoneDependentPetsHelper::zone_id
Definition at line 22389 of file Player.cpp.
The documentation for this struct was generated from the following file:
Player.cpp