CMaNGOS_WoTLK: PvPDifficultyEntry Struct Reference
PvPDifficultyEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
BattleGroundBracketId GetBracketId () const
Data Fields
uint32 mapId
uint32 bracketId
uint32 minLevel
uint32 maxLevel
uint32 difficulty
Detailed Description
Definition at line 1541 of file DBCStructure.h.
Member Function Documentation
GetBracketId()
BattleGroundBracketId PvPDifficultyEntry::GetBracketId () const inline
Definition at line 1551 of file DBCStructure.h.
References bracketId.
Referenced by BattleGroundQueue::AddGroup(), BattleGroundMgr::CreateNewBattleGround(), WorldSession::HandleBattlefieldPortOpcode(), WorldSession::HandleBattlefieldStatusOpcode(), WorldSession::HandleBattlemasterJoinArena(), WorldSession::HandleBattlemasterJoinOpcode(), and BattleGround::SetBracket().
Field Documentation
bracketId
uint32 PvPDifficultyEntry::bracketId
Definition at line 1545 of file DBCStructure.h.
Referenced by GetBracketId().
difficulty
uint32 PvPDifficultyEntry::difficulty
Definition at line 1548 of file DBCStructure.h.
Referenced by MapManager::CreateBattleGroundMap().
mapId
uint32 PvPDifficultyEntry::mapId
Definition at line 1544 of file DBCStructure.h.
Referenced by Group::CanJoinBattleGroundQueue().
maxLevel
uint32 PvPDifficultyEntry::maxLevel
Definition at line 1547 of file DBCStructure.h.
Referenced by BattleGroundQueue::AddGroup(), GetBattlegroundBracketByLevel(), and BattleGround::SetBracket().
minLevel
uint32 PvPDifficultyEntry::minLevel
Definition at line 1546 of file DBCStructure.h.
Referenced by BattleGroundQueue::AddGroup(), and BattleGround::SetBracket().
The documentation for this struct was generated from the following file:
DBCStructure.h