CMaNGOS_WoTLK: MaNGOS::UnitSearcher< Check > Struct Template Reference
MaNGOS::UnitSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitSearcher (Unit *&result, Check &check)
void Visit (CreatureMapType &m)
void Visit (PlayerMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
Unit *& i_object
Check & i_check
Detailed Description
template<class Check>
struct MaNGOS::UnitSearcher< Check >
Definition at line 354 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitSearcher()
template<class Check > MaNGOS::UnitSearcher< Check >::UnitSearcher (Unit *& result, Check & check) inline
Definition at line 360 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/3]
template<class Check > void MaNGOS::UnitSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 524 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void MaNGOS::UnitSearcher< Check >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 366 of file GridNotifiers.h.
Visit() [3/3]
template<class Check > void MaNGOS::UnitSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 544 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Field Documentation
i_check
template<class Check > Check& MaNGOS::UnitSearcher< Check >::i_check
Definition at line 358 of file GridNotifiers.h.
i_object
template<class Check > Unit*& MaNGOS::UnitSearcher< Check >::i_object
Definition at line 357 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 MaNGOS::UnitSearcher< Check >::i_phaseMask
Definition at line 356 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h