CMaNGOS_WoTLK: MaNGOS::SpellNotifierPlayer Struct Reference
MaNGOS::SpellNotifierPlayer Struct Reference
#include <Spell.h>
Public Member Functions
SpellNotifierPlayer (Spell &spell, UnitList &data, const uint32 &i, float radius)
void Visit (PlayerMapType &m)
template<class SKIP >
void Visit (GridRefManager< SKIP > &)
Data Fields
UnitList & i_data
Spell & i_spell
const uint32 & i_index
float i_radius
WorldObject * i_originalCaster
Detailed Description
Definition at line 1110 of file Spell.h.
Constructor & Destructor Documentation
SpellNotifierPlayer()
MaNGOS::SpellNotifierPlayer::SpellNotifierPlayer (Spell & spell, UnitList & data, const uint32 & i, float radius) inline
Definition at line 1118 of file Spell.h.
References Spell::GetCastingObject(), i_originalCaster, and i_spell.
Member Function Documentation
Visit() [1/2]
template<class SKIP > void MaNGOS::SpellNotifierPlayer::Visit (GridRefManager< SKIP > &) inline
Definition at line 1142 of file Spell.h.
Visit() [2/2]
void MaNGOS::SpellNotifierPlayer::Visit (PlayerMapType & m) inline
Definition at line 1124 of file Spell.h.
References WorldObject::CanAttackSpell(), i_data, i_originalCaster, i_radius, i_spell, Unit::IsAlive(), Unit::IsTaxiFlying(), WorldObject::IsWithinDist3d(), SpellCastTargets::m_destPos, Spell::m_spellInfo, Spell::m_targets, Position::x, Position::y, and Position::z.
Field Documentation
i_data
UnitList& MaNGOS::SpellNotifierPlayer::i_data
Definition at line 1112 of file Spell.h.
Referenced by Visit().
i_index
const uint32& MaNGOS::SpellNotifierPlayer::i_index
Definition at line 1114 of file Spell.h.
i_originalCaster
WorldObject* MaNGOS::SpellNotifierPlayer::i_originalCaster
Definition at line 1116 of file Spell.h.
Referenced by SpellNotifierPlayer(), and Visit().
i_radius
float MaNGOS::SpellNotifierPlayer::i_radius
Definition at line 1115 of file Spell.h.
Referenced by Visit().
i_spell
Spell& MaNGOS::SpellNotifierPlayer::i_spell
Definition at line 1113 of file Spell.h.
Referenced by SpellNotifierPlayer(), and Visit().
The documentation for this struct was generated from the following file:
Spell.h