CMaNGOS_WoTLK: LadyDeathwhisperElevator Struct Reference
LadyDeathwhisperElevator Struct Reference
Public Member Functions
LadyDeathwhisperElevator (GameObject *go)
void JustReachedStopPoint () override
void HandleStateChange ()
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Additional Inherited Members
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 439 of file icecrown_citadelScripts.cpp.
Constructor & Destructor Documentation
LadyDeathwhisperElevator()
LadyDeathwhisperElevator::LadyDeathwhisperElevator (GameObject * go) inline
Definition at line 441 of file icecrown_citadelScripts.cpp.
References TimerManager::AddCustomAction(), and HandleStateChange().
Member Function Documentation
HandleStateChange()
void LadyDeathwhisperElevator::HandleStateChange () inline
Definition at line 454 of file icecrown_citadelScripts.cpp.
References GameObject::GetGoState(), GO_STATE_ACTIVE, GO_STATE_READY, GameObjectAI::m_go, and GameObject::SetGoState().
Referenced by LadyDeathwhisperElevator().
JustReachedStopPoint()
void LadyDeathwhisperElevator::JustReachedStopPoint () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 449 of file icecrown_citadelScripts.cpp.
References TimerManager::ResetTimer().
UpdateAI()
void LadyDeathwhisperElevator::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 459 of file icecrown_citadelScripts.cpp.
References TimerManager::UpdateTimers().
The documentation for this struct was generated from the following file:
icecrown_citadelScripts.cpp