CMaNGOS_WoTLK: MaNGOS::CreatureVisitObjectsNotifier Struct Reference
MaNGOS::CreatureVisitObjectsNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
CreatureVisitObjectsNotifier (Creature &c)
template<class T >
void Visit (GridRefManager< T > &)
template<>
void Visit (PlayerMapType &)
template<>
void Visit (CreatureMapType &)
Data Fields
Creature & i_creature
Detailed Description
Definition at line 156 of file GridNotifiers.h.
Constructor & Destructor Documentation
CreatureVisitObjectsNotifier()
MaNGOS::CreatureVisitObjectsNotifier::CreatureVisitObjectsNotifier (Creature & c) inline
Definition at line 159 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/3]
template<> void MaNGOS::CreatureVisitObjectsNotifier::Visit (CreatureMapType & m) inline
Definition at line 166 of file GridNotifiersImpl.h.
References Unit::IsAlive(), and UnitVisitObjectsNotifierWorker().
Visit() [2/3]
template<class T > void MaNGOS::CreatureVisitObjectsNotifier::Visit (GridRefManager< T > &) inline
Definition at line 160 of file GridNotifiers.h.
Visit() [3/3]
template<> void MaNGOS::CreatureVisitObjectsNotifier::Visit (PlayerMapType & m) inline
Definition at line 147 of file GridNotifiersImpl.h.
References Player::AI(), Unit::IsAlive(), Unit::IsTaxiFlying(), and UnitVisitObjectsNotifierWorker().
Field Documentation
i_creature
Creature& MaNGOS::CreatureVisitObjectsNotifier::i_creature
Definition at line 158 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h