CMaNGOS_WoTLK: boss_razorscaleAI Struct Reference
boss_razorscaleAI Struct Reference
Public Member Functions
boss_razorscaleAI (Creature *pCreature)
void Reset () override
void JustDied (Unit *) override
Called when the creature is killed.
void Aggro (Unit *) override
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void JustReachedHome () override
Called at reaching home after MoveTargetedHome.
void JustSummoned (Creature *pSummoned) override
Called when the creature summon successfully other creature.
void ReceiveAIEvent (AIEventType eventType, Unit *, Unit *pInvoker, uint32) override
Called when an AI Event is received.
void DoSpawnMoleMachines ()
void DoMoveEngineersToHarpoon ()
void DoRepairHarpoon (GameObject *pSource)
bool SelectCustomHostileTarget ()
void UpdateAI (const uint32 uiDiff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void MoveInLineOfSight (Unit *)
== Reactions At =================================
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void KilledUnit (Unit *)
Called when the creature kills a unit.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Data Fields
instance_ulduar * m_pInstance
bool m_bIsRegularMode
uint8 m_uiPhase
bool m_bIsGrounded
uint32 m_uiBerserkTimer
uint32 m_uiFireballTimer
uint32 m_uiDevouringFlameTimer
uint32 m_uiDwarfSpawnTimer
uint32 m_uiRepairHarpoonTimer
uint32 m_uiShackleTimer
uint32 m_uiGroundedTimer
uint8 m_uiGroundedStep
uint32 m_uiFlameBuffetTimer
uint32 m_uiFuseArmorTimer
uint32 m_uiFlameBreathTimer
uint8 m_uiMaxHarpoons
uint8 m_uiCurrentHarpoon
uint8 m_uiHarpoonsUsed
uint8 m_uiFlyPhaseCount
GuidList m_lEngineersGuids
GuidList m_lTrappersGuids
GuidVector m_vHarpoonsGuids
Additional Inherited Members
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 123 of file boss_razorscale.cpp.
Constructor & Destructor Documentation
boss_razorscaleAI()
boss_razorscaleAI::boss_razorscaleAI (Creature * pCreature) inline
Definition at line 125 of file boss_razorscale.cpp.
References WorldObject::GetInstanceData(), WorldObject::GetMap(), Unit::GetMotionMaster(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), Map::IsRegularDifficulty(), m_bIsRegularMode, CreatureAI::m_creature, m_pInstance, m_uiMaxHarpoons, MotionMaster::MoveRandomAroundPoint(), and Reset().
Member Function Documentation
Aggro()
void boss_razorscaleAI::Aggro (Unit *) inline override virtual
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
Called at creature EnterCombat with an enemy This is a SD2 internal function Called by default on creature EnterCombat with an enemy
Reimplemented from ScriptedAI.
Definition at line 201 of file boss_razorscale.cpp.
References instance_ulduar::GetEngineersGuids(), instance_ulduar::GetHarpoonsGuids(), instance_ulduar::GetTrappersGuids(), IN_PROGRESS, m_lEngineersGuids, m_lTrappersGuids, m_pInstance, m_vHarpoonsGuids, instance_ulduar::SetData(), and TYPE_RAZORSCALE.
DoMoveEngineersToHarpoon()
void boss_razorscaleAI::DoMoveEngineersToHarpoon () inline
Definition at line 308 of file boss_razorscale.cpp.
References Map::GetCreature(), Map::GetGameObject(), WorldObject::GetMap(), INTERACTION_DISTANCE, CreatureAI::m_creature, m_lEngineersGuids, M_PI_F, m_uiCurrentHarpoon, and m_vHarpoonsGuids.
Referenced by ReceiveAIEvent(), and UpdateAI().
DoRepairHarpoon()
void boss_razorscaleAI::DoRepairHarpoon (GameObject * pSource) inline
Definition at line 333 of file boss_razorscale.cpp.
References GetClosestGameObjectWithEntry(), GO_HARPOON_GUN_1, GO_HARPOON_GUN_2, GO_HARPOON_GUN_3, GO_HARPOON_GUN_4, HOUR, GameObject::Refresh(), and GameObject::SetRespawnTime().
Referenced by UpdateAI().
DoSpawnMoleMachines()
void boss_razorscaleAI::DoSpawnMoleMachines () inline
Definition at line 294 of file boss_razorscale.cpp.
References afRazorscaleSpawnersPos, WorldObject::GetRandomPoint(), CreatureAI::m_creature, NPC_RAZORSCALE_SPAWNER, roll_chance_i(), WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_DESPAWN.
Referenced by UpdateAI().
JustDied()
void boss_razorscaleAI::JustDied (Unit *) inline override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from UnitAI.
Definition at line 195 of file boss_razorscale.cpp.
References DONE, m_pInstance, instance_ulduar::SetData(), and TYPE_RAZORSCALE.
JustReachedHome()
void boss_razorscaleAI::JustReachedHome () inline override virtual
Called at reaching home after MoveTargetedHome.
Reimplemented from UnitAI.
Definition at line 214 of file boss_razorscale.cpp.
References FAIL, Unit::GetMotionMaster(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), CreatureAI::m_creature, m_pInstance, MotionMaster::MoveRandomAroundPoint(), instance_ulduar::SetData(), and TYPE_RAZORSCALE.
JustSummoned()
void boss_razorscaleAI::JustSummoned (Creature *) inline override virtual
Called when the creature summon successfully other creature.
Parameters
pSummoned Creature that got summoned
Reimplemented from UnitAI.
Definition at line 222 of file boss_razorscale.cpp.
References AI_EVENT_CUSTOM_A, Unit::CastSpell(), Object::GetEntry(), WorldObject::GetPositionY(), m_bIsRegularMode, CreatureAI::m_creature, NPC_DEVOURING_FLAME, NPC_RAZORSCALE_SPAWNER, UnitAI::SendAIEvent(), SPELL_DEVOURING_FLAME_AURA, SPELL_DEVOURING_FLAME_AURA_H, SPELL_SUMMON_MOLE_MACHINE, and TRIGGERED_OLD_TRIGGERED.
ReceiveAIEvent()
void boss_razorscaleAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) inline override virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented from ScriptedAI.
Definition at line 236 of file boss_razorscale.cpp.
References afRazorscaleGroundPos, AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, DoMoveEngineersToHarpoon(), DoScriptText(), Map::GetCreature(), WorldObject::GetMap(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::GetSpeedRate(), CreatureAI::m_creature, m_lTrappersGuids, M_PI_F, m_pInstance, m_uiHarpoonsUsed, m_uiMaxHarpoons, m_uiPhase, m_uiRepairHarpoonTimer, m_uiShackleTimer, MOVE_RUN, MotionMaster::MovePointTOL(), NPC_EXPEDITION_COMMANDER, NPC_RAZORSCALE_CONTROLLER, PHASE_TRANSITION, SAY_GROUNDED, Unit::SetSpeedRate(), Creature::SetWalk(), SPEED_RATE_HELPERS, and SPEED_RATE_RAZORSCALE.
Reset()
void boss_razorscaleAI::Reset () inline override virtual
Reimplemented from CreatureAI.
Definition at line 165 of file boss_razorscale.cpp.
References IN_MILLISECONDS, m_bIsGrounded, CreatureAI::m_creature, m_uiBerserkTimer, m_uiCurrentHarpoon, m_uiDevouringFlameTimer, m_uiDwarfSpawnTimer, m_uiFireballTimer, m_uiFlameBreathTimer, m_uiFlameBuffetTimer, m_uiFlyPhaseCount, m_uiFuseArmorTimer, m_uiGroundedStep, m_uiGroundedTimer, m_uiHarpoonsUsed, m_uiPhase, m_uiRepairHarpoonTimer, m_uiShackleTimer, MINUTE, PHASE_AIR, Object::SetByteFlag(), UnitAI::SetCombatMovement(), Unit::SetLevitate(), UNIT_BYTE1_FLAG_FLY_ANIM, and UNIT_FIELD_BYTES_1.
Referenced by boss_razorscaleAI().
SelectCustomHostileTarget()
bool boss_razorscaleAI::SelectCustomHostileTarget () inline
Definition at line 352 of file boss_razorscale.cpp.
References ScriptedAI::EnterEvadeMode(), ThreatManager::getThreatList(), Unit::getThreatManager(), Unit::GetVictim(), Unit::HasAuraType(), Unit::IsInCombat(), CreatureAI::m_creature, m_uiPhase, PHASE_GROUNDED, PHASE_ONLY_GROUND, Unit::SelectHostileTarget(), and SPELL_AURA_MOD_TAUNT.
Referenced by UpdateAI().
UpdateAI()
void boss_razorscaleAI::UpdateAI (const uint32 diff) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented from UnitAI.
Definition at line 376 of file boss_razorscale.cpp.
References ATTACKING_TARGET_RANDOM, CAST_OK, UnitAI::DoCastSpellIfCan(), UnitAI::DoMeleeAttackIfReady(), DoMoveEngineersToHarpoon(), DoRepairHarpoon(), UnitAI::DoResetThreat(), DoScriptText(), DoSpawnMoleMachines(), ScriptedAI::DoStartMovement(), EMOTE_BREATH, EMOTE_GROUNDED, EMOTE_HARPOON_READY, GetClosestCreatureWithEntry(), Map::GetCreature(), Map::GetGameObject(), Unit::GetHealthPercent(), WorldObject::GetMap(), Unit::GetMotionMaster(), Creature::GetRespawnCoord(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::GetSpeedRate(), Unit::GetVictim(), GO_JUST_DEACTIVATED, HOUR, m_bIsGrounded, m_bIsRegularMode, CreatureAI::m_creature, m_lEngineersGuids, m_lTrappersGuids, m_pInstance, m_uiBerserkTimer, m_uiCurrentHarpoon, m_uiDevouringFlameTimer, m_uiDwarfSpawnTimer, m_uiFireballTimer, m_uiFlameBreathTimer, m_uiFlameBuffetTimer, m_uiFlyPhaseCount, m_uiFuseArmorTimer, m_uiGroundedStep, m_uiGroundedTimer, m_uiHarpoonsUsed, m_uiMaxHarpoons, m_uiPhase, m_uiRepairHarpoonTimer, m_uiShackleTimer, m_vHarpoonsGuids, MOVE_RUN, MotionMaster::MovePointTOL(), NPC_EXPEDITION_COMMANDER, NPC_EXPEDITION_ENGINEER, PHASE_AIR, PHASE_GROUNDED, PHASE_ONLY_GROUND, PHASE_TRANSITION, Unit::RemoveAurasDueToSpell(), Object::RemoveByteFlag(), SAY_EXTINGUISH_FIRE, Unit::SelectAttackingTarget(), SelectCustomHostileTarget(), Object::SetByteFlag(), UnitAI::SetCombatMovement(), Unit::SetLevitate(), instance_ulduar::SetSpecialAchievementCriteria(), Unit::SetSpeedRate(), SPEED_RATE_RAZORSCALE, SPELL_BERSERK, SPELL_DEVOURING_FLAME, SPELL_FIREBALL, SPELL_FIREBALL_H, SPELL_FIREBOLT, SPELL_FLAME_BREATH, SPELL_FLAME_BREATH_H, SPELL_FLAME_BUFFET, SPELL_FLAME_BUFFET_H, SPELL_FUSE_ARMOR, SPELL_SHACKLE, SPELL_STUN, SPELL_WING_BUFFET, TRIGGERED_NONE, TYPE_ACHIEV_QUICK_SHAVE, UNIT_BYTE1_FLAG_FLY_ANIM, and UNIT_FIELD_BYTES_1.
Field Documentation
m_bIsGrounded
bool boss_razorscaleAI::m_bIsGrounded
Definition at line 139 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_bIsRegularMode
bool boss_razorscaleAI::m_bIsRegularMode
Definition at line 136 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI(), JustSummoned(), and UpdateAI().
m_lEngineersGuids
GuidList boss_razorscaleAI::m_lEngineersGuids
Definition at line 161 of file boss_razorscale.cpp.
Referenced by Aggro(), DoMoveEngineersToHarpoon(), and UpdateAI().
m_lTrappersGuids
GuidList boss_razorscaleAI::m_lTrappersGuids
Definition at line 162 of file boss_razorscale.cpp.
Referenced by Aggro(), ReceiveAIEvent(), and UpdateAI().
m_pInstance
instance_ulduar* boss_razorscaleAI::m_pInstance
Definition at line 135 of file boss_razorscale.cpp.
Referenced by Aggro(), boss_razorscaleAI(), JustDied(), JustReachedHome(), ReceiveAIEvent(), and UpdateAI().
m_uiBerserkTimer
uint32 boss_razorscaleAI::m_uiBerserkTimer
Definition at line 141 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiCurrentHarpoon
uint8 boss_razorscaleAI::m_uiCurrentHarpoon
Definition at line 157 of file boss_razorscale.cpp.
Referenced by DoMoveEngineersToHarpoon(), Reset(), and UpdateAI().
m_uiDevouringFlameTimer
uint32 boss_razorscaleAI::m_uiDevouringFlameTimer
Definition at line 144 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiDwarfSpawnTimer
uint32 boss_razorscaleAI::m_uiDwarfSpawnTimer
Definition at line 145 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFireballTimer
uint32 boss_razorscaleAI::m_uiFireballTimer
Definition at line 143 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFlameBreathTimer
uint32 boss_razorscaleAI::m_uiFlameBreathTimer
Definition at line 154 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFlameBuffetTimer
uint32 boss_razorscaleAI::m_uiFlameBuffetTimer
Definition at line 152 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFlyPhaseCount
uint8 boss_razorscaleAI::m_uiFlyPhaseCount
Definition at line 159 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFuseArmorTimer
uint32 boss_razorscaleAI::m_uiFuseArmorTimer
Definition at line 153 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiGroundedStep
uint8 boss_razorscaleAI::m_uiGroundedStep
Definition at line 150 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiGroundedTimer
uint32 boss_razorscaleAI::m_uiGroundedTimer
Definition at line 149 of file boss_razorscale.cpp.
Referenced by Reset(), and UpdateAI().
m_uiHarpoonsUsed
uint8 boss_razorscaleAI::m_uiHarpoonsUsed
Definition at line 158 of file boss_razorscale.cpp.
Referenced by ReceiveAIEvent(), Reset(), and UpdateAI().
m_uiMaxHarpoons
uint8 boss_razorscaleAI::m_uiMaxHarpoons
Definition at line 156 of file boss_razorscale.cpp.
Referenced by boss_razorscaleAI(), ReceiveAIEvent(), and UpdateAI().
m_uiPhase
uint8 boss_razorscaleAI::m_uiPhase
Definition at line 138 of file boss_razorscale.cpp.
Referenced by ReceiveAIEvent(), Reset(), SelectCustomHostileTarget(), and UpdateAI().
m_uiRepairHarpoonTimer
uint32 boss_razorscaleAI::m_uiRepairHarpoonTimer
Definition at line 146 of file boss_razorscale.cpp.
Referenced by ReceiveAIEvent(), Reset(), and UpdateAI().
m_uiShackleTimer
uint32 boss_razorscaleAI::m_uiShackleTimer
Definition at line 148 of file boss_razorscale.cpp.
Referenced by ReceiveAIEvent(), Reset(), and UpdateAI().
m_vHarpoonsGuids
GuidVector boss_razorscaleAI::m_vHarpoonsGuids
Definition at line 163 of file boss_razorscale.cpp.
Referenced by Aggro(), DoMoveEngineersToHarpoon(), and UpdateAI().
The documentation for this struct was generated from the following file:
boss_razorscale.cpp