CMaNGOS_WoTLK: SentryTotemAI Struct Reference
SentryTotemAI Struct Reference
Public Member Functions
void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
void RemoveAura ()
void JustDied (Unit *killer) override
Called when the creature is killed.
void OnUnsummon () override
TotemAI (Creature *creature)
Public Member Functions inherited from TotemAI
TotemAI (Creature *creature)
void SpellHit (Unit *unit, const SpellEntry *spellInfo) override
Called when hit by a spell.
void MoveInLineOfSight (Unit *who) override
== Reactions At =================================
void EnterEvadeMode () override
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
bool IsVisible (Unit *who) const override
== State checks =================================
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Public Member Functions inherited from CreatureEventAI
CreatureEventAI (Creature *creature)
~CreatureEventAI ()
void InitAI ()
void GetAIInformation (ChatHandler &reader) override
== Information about AI ========================
void JustRespawned () override
Called when creature is respawned (for reseting variables)
void Reset () override
void JustReachedHome () override
Called at reaching home after MoveTargetedHome.
void EnterCombat (Unit *enemy) override
Called for reaction at enter to combat if not in combat yet.
void EnterEvadeMode () override
Called for reaction at stopping attack at no attackers or targets This is called usually in Unit::SelectHostileTarget, if no more target exists.
void KilledUnit (Unit *victim) override
Called when the creature kills a unit.
void JustSummoned (Creature *summoned) override
Called when the creature summon successfully other creature.
void MoveInLineOfSight (Unit *who) override
== Reactions At =================================
void SpellHit (Unit *unit, const SpellEntry *spellInfo) override
Called when hit by a spell.
void SpellHitTarget (Unit *target, const SpellEntry *spell) override
void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damagetype, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
void JustPreventedDeath (Unit *attacker)
void HealedBy (Unit *healer, uint32 &healedAmount) override
Called at any Heal received from any Unit.
void ReceiveEmote (Player *player, uint32 textEmote) override
Called at text emote receive from player.
void SummonedCreatureJustDied (Creature *summoned) override
Called when a summoned creature is killed.
void SummonedCreatureDespawn (Creature *summoned) override
Called when a summoned creature gets TemporarySummon::UnSummon ed.
void ReceiveAIEvent (AIEventType eventType, Unit *sender, Unit *invoker, uint32 miscValue) override
Called when an AI Event is received.
void CorpseRemoved (uint32 &respawnDelay) override
Called when the corpse of this creature gets removed.
void OnSpellCast (SpellEntry const *spellInfo, Unit *target) override
virtual void UpdateEventTimers (const uint32 diff) override
void ProcessEvents (Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
bool CheckEvent (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
void ResetEvent (CreatureEventAIHolder &holder)
void CheckAndReadyEventForExecution (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
void IncreaseDepthIfNecessary ()
virtual bool ProcessEvent (CreatureEventAIHolder &holder, Unit *actionInvoker=nullptr, Unit *AIEventSender=nullptr)
virtual bool ProcessAction (CreatureEventAI_Action const &action, uint32 rnd, uint32 eventId, Unit *actionInvoker, Unit *AIEventSender, Unit *eventTarget)
uint32 GetRandActionParam (uint32 rnd, uint32 param1, uint32 param2, uint32 param3) const
int32 GetRandActionParam (uint32 rnd, int32 param1, int32 param2, int32 param3) const
Unit * GetTargetByType (uint32 target, Unit *actionInvoker, Unit *AIEventSender, Unit *eventTarget, bool &isError, uint32 forSpellId=0, uint32 selectFlags=0) const
If the bool& param is true, an error should be reported.
bool SpawnedEventConditionsCheck (CreatureEventAI_Event const &event) const
MovementGeneratorType GetDefaultMovement ()
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Additional Inherited Members
Static Public Member Functions inherited from TotemAI
static int Permissible (const Creature *creature)
Static Public Member Functions inherited from CreatureEventAI
static int Permissible (const Creature *creature)
Protected Types inherited from CreatureEventAI
typedef std::vector< CreatureEventAIHolder > CreatureEventAIList
Protected Member Functions inherited from TotemAI
std::string GetAIName () override
Totem & getTotem () const
Protected Member Functions inherited from CreatureEventAI
std::string GetAIName () override
bool IsTimerExecutedEvent (EventAI_Type type) const
bool IsRepeatableEvent (EventAI_Type type) const
bool IsTimerBasedEvent (EventAI_Type type) const
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureEventAI
uint32 m_EventUpdateTime
uint32 m_EventDiff
bool m_bEmptyList
CreatureEventAIList m_CreatureEventAIList
std::vector< std::vector< std::reference_wrapper< CreatureEventAIHolder > > > m_creatureEventAITempList
uint32 m_depth
uint8 m_Phase
bool m_HasOOCLoSEvent
uint32 m_InvinceabilityHpLevel
uint32 m_throwAIEventMask
uint32 m_throwAIEventStep
float m_LastSpellMaxRange
uint32 m_despawnAggregationMask
std::set< uint32 > m_entriesForDespawn
GuidVector m_despawnGuids
MovementGeneratorType m_defaultMovement
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 54 of file Shaman.cpp.
Member Function Documentation
AttackStart()
void SentryTotemAI::AttackStart (Unit * who) inline override virtual
== Triggered Actions Requested ==================
Called when creature attack expected (if creature can and no have current victim) Note: for reaction at hostile action must be called AttackedBy function. Note: Usually called by MoveInLineOfSight, in Unit::SelectHostileTarget or when the AI is forced to attack an enemy
Parameters
pWho Unit* who is possible target
Reimplemented from TotemAI.
Definition at line 58 of file Shaman.cpp.
References TotemAI::AttackStart(), Object::GetObjectGuid(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), Unit::GetSpawner(), CreatureAI::m_creature, and MSG_MINIMAP_PING.
JustDied()
void SentryTotemAI::JustDied (Unit *) inline override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from CreatureEventAI.
Definition at line 78 of file Shaman.cpp.
References CreatureEventAI::JustDied(), and RemoveAura().
OnUnsummon()
void SentryTotemAI::OnUnsummon () inline override virtual
Reimplemented from UnitAI.
Definition at line 84 of file Shaman.cpp.
References UnitAI::OnUnsummon(), and RemoveAura().
RemoveAura()
void SentryTotemAI::RemoveAura () inline
Definition at line 72 of file Shaman.cpp.
References Unit::GetSpawner(), Object::GetUInt32Value(), CreatureAI::m_creature, and UNIT_CREATED_BY_SPELL.
Referenced by JustDied(), and OnUnsummon().
TotemAI()
TotemAI::TotemAI explicit
Definition at line 33 of file TotemAI.cpp.
The documentation for this struct was generated from the following file:
Shaman.cpp