CMaNGOS_WoTLK: world_map_eastern_kingdoms Struct Reference
world_map_eastern_kingdoms Struct Reference
Public Member Functions
world_map_eastern_kingdoms (Map *pMap)
void Initialize () override
bool CheckConditionCriteriaMeet (Player const *player, uint32 instanceConditionId, WorldObject const *conditionSource, uint32 conditionSourceType) const override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void DespawnAdds ()
void DoSpawn (uint32 spawnId)
void OnEventHappened (uint16 event_id, bool activate, bool resume) override
void Update (uint32 diff) override
uint32 GetData (uint32 type) const override
void SetData (uint32 type, uint32 data) override
Public Member Functions inherited from ScriptedMap
ScriptedMap (Map *map)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Data Fields
std::set< ObjectGuid > _spawn
std::set< ObjectGuid > _spawnBoss
std::set< ObjectGuid > _spawnSupport
std::set< ObjectGuid > _spawnProtector
std::set< ObjectGuid > _spawnGuardian
Position const spawnPortalPos = { -11900.3f, -3207.62f, -14.7534f, 0.146405f }
Position const spawnPortalPos1 = { -11901.25f, -3202.272f, -14.7534f, 0.146405f }
Position const spawnBossPortalPos = { -11891.500f, -3207.010f, -14.798f, 0.146405f }
Position const spawnReinforcementPos = { -11815.1f, -3190.39f, -30.7338f, 3.32447f }
ShadeOfTheHorsemanData m_shadeData
BrewfestEvent m_brewfestEvent
Data Fields inherited from InstanceData
Map * instance
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 30 of file world_eastern_kingdoms.cpp.
Constructor & Destructor Documentation
world_map_eastern_kingdoms()
world_map_eastern_kingdoms::world_map_eastern_kingdoms (Map * pMap) inline
Definition at line 32 of file world_eastern_kingdoms.cpp.
References AREAID_BRILL, AREAID_GOLDSHIRE, and AREAID_KHARANOS.
Member Function Documentation
CheckConditionCriteriaMeet()
bool world_map_eastern_kingdoms::CheckConditionCriteriaMeet (Player const * player, uint32 instanceConditionId, WorldObject const * conditionSource, uint32 conditionSourceType) const inline override virtual
Reimplemented from InstanceData.
Definition at line 162 of file world_eastern_kingdoms.cpp.
References WorldObject::GetAreaId(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_GOLDSHIRE, INSTANCE_CONDITION_ID_LET_THE_FIRES_COME_HORDE, ShadeOfTheHorsemanData::IsConditionFulfilled(), and script_error_log().
DespawnAdds()
void world_map_eastern_kingdoms::DespawnAdds () inline
Definition at line 265 of file world_eastern_kingdoms.cpp.
DoSpawn()
void world_map_eastern_kingdoms::DoSpawn (uint32 spawnId) inline
Definition at line 283 of file world_eastern_kingdoms.cpp.
References DoScriptText(), IN_MILLISECONDS, JTH_SPAWN, LMR_SPAWN, M_PI, MH_SPAWN, MINUTE, NPC_AGENT_PROUDWELL, NPC_AZUREMYST_VINDICATOR, NPC_DREADKNIGHT, NPC_FELGUARD_LIEUTENANT, NPC_JUSTINIUS_THE_HARBINGER, NPC_LORD_MARSHAL_RAYNOR, NPC_MELGROMM_HIGHMOUNTAIN, NPC_STORMWIND_MARSHAL, NPC_THUNDER_BLUFF_HUNTSMAN, Position::o, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, urand(), Position::x, Position::y, and Position::z.
GetData()
uint32 world_map_eastern_kingdoms::GetData (uint32 type) const inline override virtual
Reimplemented from InstanceData.
Definition at line 378 of file world_eastern_kingdoms.cpp.
References ShadeOfTheHorsemanData::HandleGetData(), TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, and TYPE_SHADE_OF_THE_HORSEMAN_MAX.
Initialize()
void world_map_eastern_kingdoms::Initialize () inline override virtual
Reimplemented from InstanceData.
Definition at line 157 of file world_eastern_kingdoms.cpp.
References ShadeOfTheHorsemanData::Reset().
OnCreatureCreate()
void world_map_eastern_kingdoms::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceData.
Definition at line 172 of file world_eastern_kingdoms.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), NPC_AGENT_PROUDWELL, NPC_ARGENT_GUARDIAN, NPC_ARGENT_PROTECTOR, NPC_BELBI_QUIKSWITCH, NPC_BOLVAR, NPC_DARK_IRON_HERALD, NPC_DREADKNIGHT, NPC_FALSTAD_WILDHAMMER, NPC_FELGUARD_LIEUTENANT, NPC_GORDOK_BREW_BARKER, NPC_HIGHLORD_KRUUL, NPC_HINDENBURG, NPC_INVADING_ANGUISHER, NPC_INVADING_FEL_STALKER, NPC_INVADING_FELGUARD, NPC_INVADING_INFERNAL, NPC_INVADING_VOIDWALKER, NPC_IPFELKOFER_IRONKEG, NPC_ITA_THUNDERBREW, NPC_JONATHAN, NPC_JUSTINIUS_THE_HARBINGER, NPC_LORD_MARSHAL_RAYNOR, NPC_MAEVE_BARLEYBREW, NPC_MEEFI_FARTHROTTLE, NPC_MEKKATORQUE, NPC_MELGROMM_HIGHMOUNTAIN, NPC_NECROPOLIS_HEALTH, NPC_NEZRAZ, NPC_PRESTOR, NPC_SHORT_JOHN_MITHRIL, NPC_SQUIBBY_OVERSPECK, NPC_WINDSOR, NPC_WRYNN, and NPC_ZAPETTA.
OnCreatureDeath()
void world_map_eastern_kingdoms::OnCreatureDeath (Creature * pCreature) inline override virtual
Reimplemented from InstanceData.
Definition at line 227 of file world_eastern_kingdoms.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), NPC_ARGENT_GUARDIAN, NPC_ARGENT_PROTECTOR, NPC_DREADKNIGHT, NPC_FELGUARD_LIEUTENANT, NPC_JUSTINIUS_THE_HARBINGER, NPC_LORD_MARSHAL_RAYNOR, NPC_MELGROMM_HIGHMOUNTAIN, and NPC_NECROPOLIS_HEALTH.
OnEventHappened()
void world_map_eastern_kingdoms::OnEventHappened (uint16 event_id, bool activate, bool resume) inline override virtual
Reimplemented from InstanceData.
Definition at line 342 of file world_eastern_kingdoms.cpp.
References EVENT_REINFORCEMENTS_NEEDED, EVENT_SPAWN, EVENT_SPAWN_BOSS, GAME_EVENT_BEFORE_THE_STORM, GAME_EVENT_BREWFEST_DARK_IRON_ATTACK, GAME_EVENT_BREWFEST_KEG_TAPPING, GAME_EVENT_GURUBASHI_ARENA, NPC_SHORT_JOHN_MITHRIL, BrewfestEvent::StartDarkIronAttackEvent(), and BrewfestEvent::StartKegTappingEvent().
OnObjectCreate()
void world_map_eastern_kingdoms::OnObjectCreate (GameObject * pGo) inline override virtual
Reimplemented from InstanceData.
Definition at line 255 of file world_eastern_kingdoms.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), and GO_SUMMON_CIRCLE.
SetData()
void world_map_eastern_kingdoms::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from InstanceData.
Definition at line 385 of file world_eastern_kingdoms.cpp.
References ShadeOfTheHorsemanData::HandleSetData(), TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, and TYPE_SHADE_OF_THE_HORSEMAN_MAX.
Update()
void world_map_eastern_kingdoms::Update (uint32 diff) inline override virtual
Reimplemented from InstanceData.
Definition at line 370 of file world_eastern_kingdoms.cpp.
References HOLIDAY_BREWFEST, sGameEventMgr, and BrewfestEvent::Update().
Field Documentation
_spawn
std::set<ObjectGuid> world_map_eastern_kingdoms::_spawn
Definition at line 141 of file world_eastern_kingdoms.cpp.
_spawnBoss
std::set<ObjectGuid> world_map_eastern_kingdoms::_spawnBoss
Definition at line 142 of file world_eastern_kingdoms.cpp.
_spawnGuardian
std::set<ObjectGuid> world_map_eastern_kingdoms::_spawnGuardian
Definition at line 145 of file world_eastern_kingdoms.cpp.
_spawnProtector
std::set<ObjectGuid> world_map_eastern_kingdoms::_spawnProtector
Definition at line 144 of file world_eastern_kingdoms.cpp.
_spawnSupport
std::set<ObjectGuid> world_map_eastern_kingdoms::_spawnSupport
Definition at line 143 of file world_eastern_kingdoms.cpp.
Referenced by npc_agent_proudwell::SummonedCreatureDespawn().
m_brewfestEvent
BrewfestEvent world_map_eastern_kingdoms::m_brewfestEvent
Definition at line 155 of file world_eastern_kingdoms.cpp.
m_shadeData
ShadeOfTheHorsemanData world_map_eastern_kingdoms::m_shadeData
Definition at line 153 of file world_eastern_kingdoms.cpp.
spawnBossPortalPos
Position const world_map_eastern_kingdoms::spawnBossPortalPos = { -11891.500f, -3207.010f, -14.798f, 0.146405f }
Definition at line 149 of file world_eastern_kingdoms.cpp.
spawnPortalPos
Position const world_map_eastern_kingdoms::spawnPortalPos = { -11900.3f, -3207.62f, -14.7534f, 0.146405f }
Definition at line 147 of file world_eastern_kingdoms.cpp.
spawnPortalPos1
Position const world_map_eastern_kingdoms::spawnPortalPos1 = { -11901.25f, -3202.272f, -14.7534f, 0.146405f }
Definition at line 148 of file world_eastern_kingdoms.cpp.
spawnReinforcementPos
Position const world_map_eastern_kingdoms::spawnReinforcementPos = { -11815.1f, -3190.39f, -30.7338f, 3.32447f }
Definition at line 150 of file world_eastern_kingdoms.cpp.
The documentation for this struct was generated from the following file:
world_eastern_kingdoms.cpp