CMaNGOS_WoTLK: MaNGOS::UnitListSearcher< Check > Struct Template Reference
MaNGOS::UnitListSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
UnitListSearcher (UnitList &objects, Check &check)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
UnitList & i_objects
Check & i_check
Detailed Description
template<class Check>
struct MaNGOS::UnitListSearcher< Check >
Definition at line 388 of file GridNotifiers.h.
Constructor & Destructor Documentation
UnitListSearcher()
template<class Check > MaNGOS::UnitListSearcher< Check >::UnitListSearcher (UnitList & objects, Check & check) inline
Definition at line 394 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/3]
template<class Check > void MaNGOS::UnitListSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 599 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [2/3]
template<class Check > template<class NOT_INTERESTED > void MaNGOS::UnitListSearcher< Check >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 400 of file GridNotifiers.h.
Visit() [3/3]
template<class Check > void MaNGOS::UnitListSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 590 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Field Documentation
i_check
template<class Check > Check& MaNGOS::UnitListSearcher< Check >::i_check
Definition at line 392 of file GridNotifiers.h.
i_objects
template<class Check > UnitList& MaNGOS::UnitListSearcher< Check >::i_objects
Definition at line 391 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 MaNGOS::UnitListSearcher< Check >::i_phaseMask
Definition at line 390 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h