CMaNGOS_WoTLK: MaNGOS::CameraDistWorker< Do > Struct Template Reference
MaNGOS::CameraDistWorker< Do > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
CameraDistWorker (WorldObject const *searcher, float _dist, Do &_do)
void Visit (CameraMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
WorldObject const * i_searcher
float i_dist
Do & i_do
Detailed Description
template<class Do>
struct MaNGOS::CameraDistWorker< Do >
Definition at line 522 of file GridNotifiers.h.
Constructor & Destructor Documentation
CameraDistWorker()
template<class Do > MaNGOS::CameraDistWorker< Do >::CameraDistWorker (WorldObject const * searcher, float _dist, Do & _do) inline
Definition at line 528 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/2]
template<class Do > void MaNGOS::CameraDistWorker< Do >::Visit (CameraMapType & m) inline
Definition at line 531 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), Camera::GetBody(), Camera::GetOwner(), MaNGOS::CameraDistWorker< Do >::i_dist, MaNGOS::CameraDistWorker< Do >::i_do, MaNGOS::CameraDistWorker< Do >::i_searcher, WorldObject::InSamePhase(), and WorldObject::IsWithinDist().
Visit() [2/2]
template<class Do > template<class NOT_INTERESTED > void MaNGOS::CameraDistWorker< Do >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 540 of file GridNotifiers.h.
Field Documentation
i_dist
template<class Do > float MaNGOS::CameraDistWorker< Do >::i_dist
Definition at line 525 of file GridNotifiers.h.
Referenced by MaNGOS::CameraDistWorker< Do >::Visit().
i_do
template<class Do > Do& MaNGOS::CameraDistWorker< Do >::i_do
Definition at line 526 of file GridNotifiers.h.
Referenced by MaNGOS::CameraDistWorker< Do >::Visit().
i_searcher
template<class Do > WorldObject const* MaNGOS::CameraDistWorker< Do >::i_searcher
Definition at line 524 of file GridNotifiers.h.
Referenced by MaNGOS::CameraDistWorker< Do >::Visit().
The documentation for this struct was generated from the following file:
GridNotifiers.h