CMaNGOS_WoTLK: ObjectPosSelector Struct Reference
ObjectPosSelector Struct Reference
#include <ObjectPosSelector.h>
Data Structures
struct OccupiedArea
Public Types
typedef std::multimap< float, OccupiedArea > UsedAreaList
typedef UsedAreaList::value_type UsedArea
Public Member Functions
ObjectPosSelector (float x, float y, float dist, float searchedForSize, WorldObject const *searchPosFor)
void AddUsedArea (WorldObject const *obj, float angle, float dist)
Add used area (circle) near target object excluded from possible searcher position.
bool CheckOriginalAngle () const
Check original (0.0f) angle fit to existed used area excludes.
void InitializeAngle ()
Initialize data for search angles starting from first possible angle at both sides.
bool NextAngle (float &angle)
Find next angle in free area.
bool NextUsedAngle (float &angle)
Find next angle in used area, that used if no angle found in free area with LoS.
bool CheckAngle (UsedArea const &usedArea, UsedAreaSide side, float angle) const
Check searcher circle not intercepting with used circle.
void InitializeAngle (UsedAreaSide side)
Initialize data for search angles starting from first possible angle at side.
bool NextSideAngle (UsedAreaSide side, float &angle)
Find next angle at side.
Data Fields
float m_centerX
float m_centerY
float m_searcherDist
float m_searchedForReqHAngle
UsedAreaList m_UsedAreaLists [2]
UsedAreaList::const_iterator m_nextUsedAreaItr [2]
float m_stepAngle [2]
WorldObject const * m_searchPosFor
Detailed Description
Definition at line 40 of file ObjectPosSelector.h.
Member Typedef Documentation
UsedArea
typedef UsedAreaList::value_type ObjectPosSelector::UsedArea
Definition at line 50 of file ObjectPosSelector.h.
UsedAreaList
typedef std::multimap<float, OccupiedArea> ObjectPosSelector::UsedAreaList
Definition at line 49 of file ObjectPosSelector.h.
Constructor & Destructor Documentation
ObjectPosSelector()
ObjectPosSelector::ObjectPosSelector (float x, float y, float dist, float searchedForSize, WorldObject const * searchPosFor)
Definition at line 25 of file ObjectPosSelector.cpp.
References DEFAULT_WORLD_OBJECT_SIZE, m_nextUsedAreaItr, m_searchedForReqHAngle, m_searcherDist, m_stepAngle, m_UsedAreaLists, OCCUPY_POS_ANGLE_ATAN_FACTOR, USED_POS_MINUS, and USED_POS_PLUS.
Member Function Documentation
AddUsedArea()
void ObjectPosSelector::AddUsedArea (WorldObject const * obj, float angle, float dist)
Add used area (circle) near target object excluded from possible searcher position.
Parameters
obj Object that occupies area
angle Angle of used circle center point from target-searcher line
dist Distance from target object center point to used circle center point
Used circles data stored as projections to searcher dist size circle as angle coordinate and half angle size
Definition at line 55 of file ObjectPosSelector.cpp.
References WorldObject::GetObjectBoundingRadius(), m_UsedAreaLists, MANGOS_ASSERT, OCCUPY_POS_ANGLE_ATAN_FACTOR, USED_POS_MINUS, and USED_POS_PLUS.
Referenced by MaNGOS::NearUsedPosDo::add().
CheckAngle()
bool ObjectPosSelector::CheckAngle (UsedArea const & usedArea, UsedAreaSide side, float angle) const
Check searcher circle not intercepting with used circle.
Parameters
usedArea Used circle as projection to searcher distance circle in angles form
side Side of used circle
angle Checked angle
Returns
true, if used circle not intercepted with searcher circle in terms projection angles
Definition at line 81 of file ObjectPosSelector.cpp.
References m_searchPosFor, and SignOf().
Referenced by CheckOriginalAngle().
CheckOriginalAngle()
bool ObjectPosSelector::CheckOriginalAngle () const
Check original (0.0f) angle fit to existed used area excludes.
Returns
true, if 0.0f angle with m_searcher_halfangle*2 angle size not intercept with used circles
Definition at line 94 of file ObjectPosSelector.cpp.
References CheckAngle(), m_UsedAreaLists, USED_POS_MINUS, and USED_POS_PLUS.
Referenced by WorldObject::GetNearPointAt().
InitializeAngle() [1/2]
void ObjectPosSelector::InitializeAngle ()
Initialize data for search angles starting from first possible angle at both sides.
Definition at line 104 of file ObjectPosSelector.cpp.
References USED_POS_MINUS, and USED_POS_PLUS.
Referenced by WorldObject::GetNearPointAt().
InitializeAngle() [2/2]
void ObjectPosSelector::InitializeAngle (UsedAreaSide side)
Initialize data for search angles starting from first possible angle at side.
Definition at line 113 of file ObjectPosSelector.cpp.
References m_nextUsedAreaItr, m_searchedForReqHAngle, m_stepAngle, and m_UsedAreaLists.
NextAngle()
bool ObjectPosSelector::NextAngle (float & angle)
Find next angle in free area.
Parameters
angle Return at success found angle
Returns
true, if angle found
Definition at line 137 of file ObjectPosSelector.cpp.
References M_PI_F, m_stepAngle, NextSideAngle(), USED_POS_MINUS, and USED_POS_PLUS.
Referenced by WorldObject::GetNearPointAt().
NextSideAngle()
bool ObjectPosSelector::NextSideAngle (UsedAreaSide side, float & angle)
Find next angle at side.
Parameters
side Side of angle
angle Return at success found angle
Returns
true, if angle found
Definition at line 172 of file ObjectPosSelector.cpp.
References m_nextUsedAreaItr, M_PI_F, m_searchedForReqHAngle, m_searchPosFor, m_stepAngle, m_UsedAreaLists, and SignOf().
Referenced by NextAngle().
NextUsedAngle()
bool ObjectPosSelector::NextUsedAngle (float & angle)
Find next angle in used area, that used if no angle found in free area with LoS.
Parameters
angle Return at success found angle
Returns
true, if angle found
Definition at line 212 of file ObjectPosSelector.cpp.
References m_nextUsedAreaItr, m_UsedAreaLists, SignOf(), USED_POS_MINUS, and USED_POS_PLUS.
Referenced by WorldObject::GetNearPointAt().
Field Documentation
m_centerX
float ObjectPosSelector::m_centerX
Definition at line 67 of file ObjectPosSelector.h.
m_centerY
float ObjectPosSelector::m_centerY
Definition at line 68 of file ObjectPosSelector.h.
m_nextUsedAreaItr
UsedAreaList::const_iterator ObjectPosSelector::m_nextUsedAreaItr[2]
Definition at line 74 of file ObjectPosSelector.h.
Referenced by InitializeAngle(), NextSideAngle(), NextUsedAngle(), and ObjectPosSelector().
m_searchedForReqHAngle
float ObjectPosSelector::m_searchedForReqHAngle
Definition at line 70 of file ObjectPosSelector.h.
Referenced by InitializeAngle(), NextSideAngle(), and ObjectPosSelector().
m_searcherDist
float ObjectPosSelector::m_searcherDist
Definition at line 69 of file ObjectPosSelector.h.
Referenced by MaNGOS::NearUsedPosDo::add(), and ObjectPosSelector().
m_searchPosFor
WorldObject const* ObjectPosSelector::m_searchPosFor
Definition at line 78 of file ObjectPosSelector.h.
Referenced by MaNGOS::NearUsedPosDo::add(), CheckAngle(), and NextSideAngle().
m_stepAngle
float ObjectPosSelector::m_stepAngle[2]
Definition at line 76 of file ObjectPosSelector.h.
Referenced by InitializeAngle(), NextAngle(), NextSideAngle(), and ObjectPosSelector().
m_UsedAreaLists
UsedAreaList ObjectPosSelector::m_UsedAreaLists[2]
Definition at line 72 of file ObjectPosSelector.h.
Referenced by AddUsedArea(), CheckOriginalAngle(), InitializeAngle(), NextSideAngle(), NextUsedAngle(), and ObjectPosSelector().
The documentation for this struct was generated from the following files:
ObjectPosSelector.h
ObjectPosSelector.cpp