CMaNGOS_WoTLK: DynTreeImpl Struct Reference
DynTreeImpl Struct Reference
Public Types
typedef GameObjectModel Model
typedef ParentTree base
Public Types inherited from RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >
enum { CELL_NUMBER = 64 }
typedef std::unordered_multimap< const T *, Node * > MemberTable
Public Member Functions
DynTreeImpl ()
void insert (const Model &mdl)
void remove (const Model &mdl)
void balance ()
void update (uint32 difftime)
Public Member Functions inherited from RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >
RegularGrid2D ()
~RegularGrid2D ()
void insert (const T &value)
template<class M >
auto MapEqualRange (M &map, typename M::key_type const &key) -> IteratorPair< decltype(map.begin())>
void remove (const T &value)
void balance ()
bool contains (const T &value) const
int size () const
Node & getGrid (int x, int y)
template<typename RayCallback >
void intersectRay (const Ray &ray, RayCallback &intersectCallback, float max_dist, bool ignoreM2Model)
template<typename RayCallback >
void intersectRay (const Ray &ray, RayCallback &intersectCallback, float &max_dist, const Vector3 &end, bool ignoreM2Model)
template<typename IsectCallback >
void intersectPoint (const Vector3 &point, IsectCallback &intersectCallback)
template<typename RayCallback >
void intersectZAllignedRay (const Ray &ray, RayCallback &intersectCallback, float &max_dist)
Data Fields
ShortTimeTracker rebalance_timer
int unbalanced_times
Data Fields inherited from RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >
MemberTable memberTable
Node * nodes [CELL_NUMBER][CELL_NUMBER]
Detailed Description
Definition at line 55 of file DynamicTree.cpp.
Member Typedef Documentation
base
typedef ParentTree DynTreeImpl::base
Definition at line 58 of file DynamicTree.cpp.
Model
typedef GameObjectModel DynTreeImpl::Model
Definition at line 57 of file DynamicTree.cpp.
Constructor & Destructor Documentation
DynTreeImpl()
DynTreeImpl::DynTreeImpl () inline
Definition at line 60 of file DynamicTree.cpp.
Member Function Documentation
balance()
void DynTreeImpl::balance () inline
Definition at line 78 of file DynamicTree.cpp.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::balance(), and unbalanced_times.
Referenced by DynamicMapTree::balance(), and update().
insert()
void DynTreeImpl::insert (const Model & mdl) inline
Definition at line 66 of file DynamicTree.cpp.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert(), and unbalanced_times.
Referenced by DynamicMapTree::insert().
remove()
void DynTreeImpl::remove (const Model & mdl) inline
Definition at line 72 of file DynamicTree.cpp.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::remove(), and unbalanced_times.
Referenced by DynamicMapTree::remove().
update()
void DynTreeImpl::update (uint32 difftime) inline
Definition at line 84 of file DynamicTree.cpp.
References balance(), CHECK_TREE_PERIOD, ShortTimeTracker::Passed(), rebalance_timer, ShortTimeTracker::Reset(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::size(), unbalanced_times, and ShortTimeTracker::Update().
Referenced by DynamicMapTree::update().
Field Documentation
rebalance_timer
ShortTimeTracker DynTreeImpl::rebalance_timer
Definition at line 98 of file DynamicTree.cpp.
Referenced by update().
unbalanced_times
int DynTreeImpl::unbalanced_times
Definition at line 99 of file DynamicTree.cpp.
Referenced by balance(), insert(), remove(), and update().
The documentation for this struct was generated from the following file:
DynamicTree.cpp