CMaNGOS_WoTLK: go_aura_generator Struct Reference
go_aura_generator Struct Reference
Public Member Functions
go_aura_generator (GameObject *go)
void ReceiveAIEvent (AIEventType eventType, uint32 miscValue=0) override
void ChangeState (bool apply)
void CheckAndApplyAura ()
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
uint32 m_auraSearchTimer
SpellEntry const * m_spellInfo
bool m_started
float m_radius
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 1098 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_aura_generator()
go_aura_generator::go_aura_generator (GameObject * go) inline
Definition at line 1100 of file go_scripts.cpp.
Member Function Documentation
ChangeState()
void go_aura_generator::ChangeState (bool apply) inline
Definition at line 1114 of file go_scripts.cpp.
References ByteConverter::apply(), CheckAndApplyAura(), SpellAuraHolder::GetCasterGuid(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPlayers(), Unit::GetSpellAuraHolderBounds(), SpellEntry::Id, GameObjectAI::m_go, m_spellInfo, m_started, and Unit::RemoveSpellAuraHolder().
Referenced by ReceiveAIEvent().
CheckAndApplyAura()
void go_aura_generator::CheckAndApplyAura () inline
Definition at line 1141 of file go_scripts.cpp.
References SpellAuraHolder::AddAura(), Unit::AddSpellAuraHolder(), GameObjectInfo::auraGenerator, CreateSpellAuraHolder(), DIST_CALC_COMBAT_REACH, EFFECT_INDEX_0, SpellAuraHolder::GetCasterGuid(), WorldObject::GetDistance(), GameObject::GetGOInfo(), WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetPlayers(), WorldObject::GetPosition(), Unit::GetSpellAuraHolderBounds(), SpellEntry::Id, GameObjectAI::m_go, m_spellInfo, and Unit::RemoveSpellAuraHolder().
Referenced by ChangeState(), and UpdateAI().
ReceiveAIEvent()
void go_aura_generator::ReceiveAIEvent (AIEventType eventType, uint32 miscValue = 0) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 1108 of file go_scripts.cpp.
References AI_EVENT_CUSTOM_A, and ChangeState().
UpdateAI()
void go_aura_generator::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 1176 of file go_scripts.cpp.
References CheckAndApplyAura(), m_auraSearchTimer, and m_started.
Field Documentation
m_auraSearchTimer
uint32 go_aura_generator::m_auraSearchTimer
Definition at line 1103 of file go_scripts.cpp.
Referenced by UpdateAI().
m_radius
float go_aura_generator::m_radius
Definition at line 1106 of file go_scripts.cpp.
m_spellInfo
SpellEntry const* go_aura_generator::m_spellInfo
Definition at line 1104 of file go_scripts.cpp.
Referenced by ChangeState(), and CheckAndApplyAura().
m_started
bool go_aura_generator::m_started
Definition at line 1105 of file go_scripts.cpp.
Referenced by ChangeState(), and UpdateAI().
The documentation for this struct was generated from the following file:
go_scripts.cpp