CMaNGOS_WoTLK: ClassFamilyMask Struct Reference
ClassFamilyMask Struct Reference
#include <DBCStructure.h>
Public Member Functions
ClassFamilyMask ()
ClassFamilyMask (uint64 familyFlags, uint32 familyFlags2=0)
bool Empty () const
bool operator! () const
operator void const * () const
bool IsFitToFamilyMask (uint64 familyFlags, uint32 familyFlags2=0) const
bool IsFitToFamilyMask (uint32 index, uint32 familyFlags) const
bool IsFitToFamilyMask (ClassFamilyMask const &mask) const
uint64 operator& (uint64 mask) const
ClassFamilyMask & operator|= (ClassFamilyMask const &mask)
Data Fields
uint64 Flags
uint32 Flags2
Detailed Description
Definition at line 1767 of file DBCStructure.h.
Constructor & Destructor Documentation
ClassFamilyMask() [1/2]
ClassFamilyMask::ClassFamilyMask () inline
Definition at line 1772 of file DBCStructure.h.
ClassFamilyMask() [2/2]
ClassFamilyMask::ClassFamilyMask (uint64 familyFlags, uint32 familyFlags2 = 0) inline explicit
Definition at line 1773 of file DBCStructure.h.
Member Function Documentation
Empty()
bool ClassFamilyMask::Empty () const inline
Definition at line 1775 of file DBCStructure.h.
References Flags, and Flags2.
Referenced by Unit::HandleProcTriggerSpellAuraProc(), SpellMgr::IsSingleTargetSpells(), IsStackableAuraEffect(), operator void const *(), and operator!().
IsFitToFamilyMask() [1/3]
bool ClassFamilyMask::IsFitToFamilyMask (ClassFamilyMask const & mask) const inline
Definition at line 1794 of file DBCStructure.h.
References Flags, and Flags2.
IsFitToFamilyMask() [2/3]
bool ClassFamilyMask::IsFitToFamilyMask (uint32 index, uint32 familyFlags) const inline
Definition at line 1784 of file DBCStructure.h.
References Flags, and Flags2.
IsFitToFamilyMask() [3/3]
bool ClassFamilyMask::IsFitToFamilyMask (uint64 familyFlags, uint32 familyFlags2 = 0) const inline
Definition at line 1779 of file DBCStructure.h.
References Flags, and Flags2.
Referenced by Player::AddSpellMod(), Aura::CanProcFrom(), Spell::EffectScriptEffect(), and SpellEntry::IsFitToFamilyMask().
operator void const *()
ClassFamilyMask::operator void const * () const inline
Definition at line 1777 of file DBCStructure.h.
References Empty().
operator!()
bool ClassFamilyMask::operator! () const inline
Definition at line 1776 of file DBCStructure.h.
References Empty().
operator&()
uint64 ClassFamilyMask::operator& (uint64 mask) const inline
Definition at line 1799 of file DBCStructure.h.
References Flags.
operator|=()
ClassFamilyMask& ClassFamilyMask::operator|= (ClassFamilyMask const & mask) inline
Definition at line 1804 of file DBCStructure.h.
References Flags, and Flags2.
Field Documentation
Flags
uint64 ClassFamilyMask::Flags
Definition at line 1769 of file DBCStructure.h.
Referenced by Empty(), Aura::HandleNoReagentUseAura(), IsFitToFamilyMask(), operator&(), and operator|=().
Flags2
uint32 ClassFamilyMask::Flags2
Definition at line 1770 of file DBCStructure.h.
Referenced by Empty(), Aura::HandleNoReagentUseAura(), IsFitToFamilyMask(), and operator|=().
The documentation for this struct was generated from the following file:
DBCStructure.h