CMaNGOS_WoTLK: RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell Struct Reference
RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell Struct Reference
#include <RegularGrid.h>
Public Member Functions
bool operator== (const Cell &c2) const
bool isValid () const
Static Public Member Functions
static Cell ComputeCell (float fx, float fy)
Data Fields
int x
int y
Detailed Description
template<class T, class Node, class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>>
struct RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell
Definition at line 132 of file RegularGrid.h.
Member Function Documentation
ComputeCell()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> static Cell RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::ComputeCell (float fx, float fy) inline static
Definition at line 137 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::CELL_NUMBER, and CELL_SIZE.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay().
isValid()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> bool RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid () const inline
Definition at line 143 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::CELL_NUMBER, RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay().
operator==()
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> bool RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::operator== (const Cell & c2) const inline
Definition at line 135 of file RegularGrid.h.
References RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x, and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y.
Field Documentation
x
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> int RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::x
Definition at line 134 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::operator==().
y
template<class T , class Node , class NodeCreatorFunc = NodeCreator<Node>, class BoundsFunc = BoundsTrait<T>, class PositionFunc = PositionTrait<T>> int RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::y
Definition at line 134 of file RegularGrid.h.
Referenced by RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::insert(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectPoint(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::intersectZAllignedRay(), RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::isValid(), and RegularGrid2D< T, Node, NodeCreatorFunc, BoundsFunc, PositionFunc >::Cell::operator==().
The documentation for this struct was generated from the following file:
RegularGrid.h