CMaNGOS_WoTLK: MaNGOS::CameraDistLambdaWorker Struct Reference
MaNGOS::CameraDistLambdaWorker Struct Reference
#include <GridNotifiers.h>
Public Member Functions
CameraDistLambdaWorker (WorldObject const *searcher, float _dist, std::function< void(Player *)> const &_do)
void Visit (CameraMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
WorldObject const * i_searcher
float i_dist
std::function< void(Player *)> const & i_do
Detailed Description
Definition at line 543 of file GridNotifiers.h.
Constructor & Destructor Documentation
CameraDistLambdaWorker()
MaNGOS::CameraDistLambdaWorker::CameraDistLambdaWorker (WorldObject const * searcher, float _dist, std::function< void(Player *)> const & _do) inline
Definition at line 549 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/2]
void MaNGOS::CameraDistLambdaWorker::Visit (CameraMapType & m) inline
Definition at line 552 of file GridNotifiers.h.
References Camera::GetBody(), Camera::GetOwner(), i_dist, i_do, i_searcher, and WorldObject::IsWithinDist().
Visit() [2/2]
template<class NOT_INTERESTED > void MaNGOS::CameraDistLambdaWorker::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 561 of file GridNotifiers.h.
Field Documentation
i_dist
float MaNGOS::CameraDistLambdaWorker::i_dist
Definition at line 546 of file GridNotifiers.h.
Referenced by Visit().
i_do
std::function<void(Player*)> const& MaNGOS::CameraDistLambdaWorker::i_do
Definition at line 547 of file GridNotifiers.h.
Referenced by Visit().
i_searcher
WorldObject const* MaNGOS::CameraDistLambdaWorker::i_searcher
Definition at line 545 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following file:
GridNotifiers.h