CMaNGOS_WoTLK: AchievementCriteriaRequirementSet Struct Reference
AchievementCriteriaRequirementSet Struct Reference
#include <AchievementMgr.h>
Public Types
typedef std::vector< AchievementCriteriaRequirement > Storage
Public Member Functions
AchievementCriteriaRequirementSet ()
void Add (AchievementCriteriaRequirement const &data)
bool Meets (Player const *source, Unit const *target, uint32 miscvalue=0) const
void SetCriteriaId (uint32 id)
Private Attributes
uint32 criteria_id
Storage storage
Detailed Description
Definition at line 225 of file AchievementMgr.h.
Member Typedef Documentation
Storage
typedef std::vector<AchievementCriteriaRequirement> AchievementCriteriaRequirementSet::Storage
Definition at line 228 of file AchievementMgr.h.
Constructor & Destructor Documentation
AchievementCriteriaRequirementSet()
AchievementCriteriaRequirementSet::AchievementCriteriaRequirementSet () inline
Definition at line 227 of file AchievementMgr.h.
Member Function Documentation
Add()
void AchievementCriteriaRequirementSet::Add (AchievementCriteriaRequirement const & data) inline
Definition at line 229 of file AchievementMgr.h.
References storage.
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaRequirements().
Meets()
bool AchievementCriteriaRequirementSet::Meets (Player const * source, Unit const * target, uint32 miscvalue = 0) const
Definition at line 435 of file AchievementMgr.cpp.
References criteria_id, and storage.
Referenced by AchievementMgr::UpdateAchievementCriteria().
SetCriteriaId()
void AchievementCriteriaRequirementSet::SetCriteriaId (uint32 id) inline
Definition at line 231 of file AchievementMgr.h.
References criteria_id.
Referenced by AchievementGlobalMgr::LoadAchievementCriteriaRequirements().
Field Documentation
criteria_id
uint32 AchievementCriteriaRequirementSet::criteria_id private
Definition at line 233 of file AchievementMgr.h.
Referenced by Meets(), and SetCriteriaId().
storage
Storage AchievementCriteriaRequirementSet::storage private
Definition at line 234 of file AchievementMgr.h.
Referenced by Add(), and Meets().
The documentation for this struct was generated from the following files:
AchievementMgr.h
AchievementMgr.cpp