CMaNGOS_WoTLK: VehicleSeatEntry Struct Reference
VehicleSeatEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
bool HasFlag (VehicleSeatFlags flag) const
bool HasFlag (VehicleSeatFlagsB flag) const
bool CanEnterOrExit () const
bool CanSwitchFromSeat () const
bool IsUsableByOverride () const
bool IsEjectable () const
Data Fields
uint32 m_ID
uint32 m_flags
int32 m_attachmentID
float m_attachmentOffsetX
float m_attachmentOffsetY
float m_attachmentOffsetZ
float m_enterPreDelay
float m_enterSpeed
float m_enterGravity
float m_enterMinDuration
float m_enterMaxDuration
float m_enterMinArcHeight
float m_enterMaxArcHeight
int32 m_enterAnimStart
int32 m_enterAnimLoop
int32 m_rideAnimStart
int32 m_rideAnimLoop
int32 m_rideUpperAnimStart
int32 m_rideUpperAnimLoop
float m_exitPreDelay
float m_exitSpeed
float m_exitGravity
float m_exitMinDuration
float m_exitMaxDuration
float m_exitMinArcHeight
float m_exitMaxArcHeight
int32 m_exitAnimStart
int32 m_exitAnimLoop
int32 m_exitAnimEnd
float m_passengerYaw
float m_passengerPitch
float m_passengerRoll
int32 m_passengerAttachmentID
int32 m_vehicleEnterAnim
int32 m_vehicleExitAnim
int32 m_vehicleRideAnimLoop
int32 m_vehicleEnterAnimBone
int32 m_vehicleExitAnimBone
int32 m_vehicleRideAnimLoopBone
float m_vehicleEnterAnimDelay
float m_vehicleExitAnimDelay
uint32 m_vehicleAbilityDisplay
uint32 m_enterUISoundID
uint32 m_exitUISoundID
int32 m_uiSkin
uint32 m_flagsB
Detailed Description
Definition at line 2298 of file DBCStructure.h.
Member Function Documentation
CanEnterOrExit()
bool VehicleSeatEntry::CanEnterOrExit () const inline
Definition at line 2362 of file DBCStructure.h.
References HasFlag(), SEAT_FLAG_CAN_CONTROL, SEAT_FLAG_CAN_EXIT, and SEAT_FLAG_SHOULD_USE_VEH_SEAT_EXIT_ANIM_ON_FORCED_EXIT.
CanSwitchFromSeat()
bool VehicleSeatEntry::CanSwitchFromSeat () const inline
Definition at line 2363 of file DBCStructure.h.
References HasFlag(), and SEAT_FLAG_CAN_SWITCH.
Referenced by VehicleInfo::SwitchSeat().
HasFlag() [1/2]
bool VehicleSeatEntry::HasFlag (VehicleSeatFlags flag) const inline
Definition at line 2359 of file DBCStructure.h.
References m_flags.
Referenced by CanEnterOrExit(), CanSwitchFromSeat(), IsEjectable(), and IsUsableByOverride().
HasFlag() [2/2]
bool VehicleSeatEntry::HasFlag (VehicleSeatFlagsB flag) const inline
Definition at line 2360 of file DBCStructure.h.
References m_flagsB.
IsEjectable()
bool VehicleSeatEntry::IsEjectable () const inline
Definition at line 2369 of file DBCStructure.h.
References HasFlag(), and SEAT_FLAG_B_EJECTABLE.
IsUsableByOverride()
bool VehicleSeatEntry::IsUsableByOverride () const inline
Definition at line 2364 of file DBCStructure.h.
References HasFlag(), SEAT_FLAG_B_USABLE_FORCED, SEAT_FLAG_B_USABLE_FORCED_2, SEAT_FLAG_B_USABLE_FORCED_3, SEAT_FLAG_B_USABLE_FORCED_4, SEAT_FLAG_UNCONTROLLED, and SEAT_FLAG_UNK15.
Field Documentation
m_attachmentID
int32 VehicleSeatEntry::m_attachmentID
Definition at line 2302 of file DBCStructure.h.
m_attachmentOffsetX
float VehicleSeatEntry::m_attachmentOffsetX
Definition at line 2303 of file DBCStructure.h.
m_attachmentOffsetY
float VehicleSeatEntry::m_attachmentOffsetY
Definition at line 2304 of file DBCStructure.h.
m_attachmentOffsetZ
float VehicleSeatEntry::m_attachmentOffsetZ
Definition at line 2305 of file DBCStructure.h.
m_enterAnimLoop
int32 VehicleSeatEntry::m_enterAnimLoop
Definition at line 2314 of file DBCStructure.h.
m_enterAnimStart
int32 VehicleSeatEntry::m_enterAnimStart
Definition at line 2313 of file DBCStructure.h.
m_enterGravity
float VehicleSeatEntry::m_enterGravity
Definition at line 2308 of file DBCStructure.h.
m_enterMaxArcHeight
float VehicleSeatEntry::m_enterMaxArcHeight
Definition at line 2312 of file DBCStructure.h.
m_enterMaxDuration
float VehicleSeatEntry::m_enterMaxDuration
Definition at line 2310 of file DBCStructure.h.
m_enterMinArcHeight
float VehicleSeatEntry::m_enterMinArcHeight
Definition at line 2311 of file DBCStructure.h.
m_enterMinDuration
float VehicleSeatEntry::m_enterMinDuration
Definition at line 2309 of file DBCStructure.h.
m_enterPreDelay
float VehicleSeatEntry::m_enterPreDelay
Definition at line 2306 of file DBCStructure.h.
m_enterSpeed
float VehicleSeatEntry::m_enterSpeed
Definition at line 2307 of file DBCStructure.h.
m_enterUISoundID
uint32 VehicleSeatEntry::m_enterUISoundID
Definition at line 2342 of file DBCStructure.h.
m_exitAnimEnd
int32 VehicleSeatEntry::m_exitAnimEnd
Definition at line 2328 of file DBCStructure.h.
m_exitAnimLoop
int32 VehicleSeatEntry::m_exitAnimLoop
Definition at line 2327 of file DBCStructure.h.
m_exitAnimStart
int32 VehicleSeatEntry::m_exitAnimStart
Definition at line 2326 of file DBCStructure.h.
m_exitGravity
float VehicleSeatEntry::m_exitGravity
Definition at line 2321 of file DBCStructure.h.
m_exitMaxArcHeight
float VehicleSeatEntry::m_exitMaxArcHeight
Definition at line 2325 of file DBCStructure.h.
m_exitMaxDuration
float VehicleSeatEntry::m_exitMaxDuration
Definition at line 2323 of file DBCStructure.h.
m_exitMinArcHeight
float VehicleSeatEntry::m_exitMinArcHeight
Definition at line 2324 of file DBCStructure.h.
m_exitMinDuration
float VehicleSeatEntry::m_exitMinDuration
Definition at line 2322 of file DBCStructure.h.
m_exitPreDelay
float VehicleSeatEntry::m_exitPreDelay
Definition at line 2319 of file DBCStructure.h.
m_exitSpeed
float VehicleSeatEntry::m_exitSpeed
Definition at line 2320 of file DBCStructure.h.
m_exitUISoundID
uint32 VehicleSeatEntry::m_exitUISoundID
Definition at line 2343 of file DBCStructure.h.
m_flags
uint32 VehicleSeatEntry::m_flags
Definition at line 2301 of file DBCStructure.h.
Referenced by VehicleInfo::Board(), Spell::CheckVehicle(), HasFlag(), VehicleInfo::SwitchSeat(), and VehicleInfo::UnBoard().
m_flagsB
uint32 VehicleSeatEntry::m_flagsB
Definition at line 2345 of file DBCStructure.h.
Referenced by HasFlag().
m_ID
uint32 VehicleSeatEntry::m_ID
Definition at line 2300 of file DBCStructure.h.
Referenced by VehicleInfo::UnBoard().
m_passengerAttachmentID
int32 VehicleSeatEntry::m_passengerAttachmentID
Definition at line 2332 of file DBCStructure.h.
m_passengerPitch
float VehicleSeatEntry::m_passengerPitch
Definition at line 2330 of file DBCStructure.h.
m_passengerRoll
float VehicleSeatEntry::m_passengerRoll
Definition at line 2331 of file DBCStructure.h.
m_passengerYaw
float VehicleSeatEntry::m_passengerYaw
Definition at line 2329 of file DBCStructure.h.
m_rideAnimLoop
int32 VehicleSeatEntry::m_rideAnimLoop
Definition at line 2316 of file DBCStructure.h.
m_rideAnimStart
int32 VehicleSeatEntry::m_rideAnimStart
Definition at line 2315 of file DBCStructure.h.
m_rideUpperAnimLoop
int32 VehicleSeatEntry::m_rideUpperAnimLoop
Definition at line 2318 of file DBCStructure.h.
m_rideUpperAnimStart
int32 VehicleSeatEntry::m_rideUpperAnimStart
Definition at line 2317 of file DBCStructure.h.
m_uiSkin
int32 VehicleSeatEntry::m_uiSkin
Definition at line 2344 of file DBCStructure.h.
m_vehicleAbilityDisplay
uint32 VehicleSeatEntry::m_vehicleAbilityDisplay
Definition at line 2341 of file DBCStructure.h.
m_vehicleEnterAnim
int32 VehicleSeatEntry::m_vehicleEnterAnim
Definition at line 2333 of file DBCStructure.h.
m_vehicleEnterAnimBone
int32 VehicleSeatEntry::m_vehicleEnterAnimBone
Definition at line 2336 of file DBCStructure.h.
m_vehicleEnterAnimDelay
float VehicleSeatEntry::m_vehicleEnterAnimDelay
Definition at line 2339 of file DBCStructure.h.
m_vehicleExitAnim
int32 VehicleSeatEntry::m_vehicleExitAnim
Definition at line 2334 of file DBCStructure.h.
m_vehicleExitAnimBone
int32 VehicleSeatEntry::m_vehicleExitAnimBone
Definition at line 2337 of file DBCStructure.h.
m_vehicleExitAnimDelay
float VehicleSeatEntry::m_vehicleExitAnimDelay
Definition at line 2340 of file DBCStructure.h.
m_vehicleRideAnimLoop
int32 VehicleSeatEntry::m_vehicleRideAnimLoop
Definition at line 2335 of file DBCStructure.h.
m_vehicleRideAnimLoopBone
int32 VehicleSeatEntry::m_vehicleRideAnimLoopBone
Definition at line 2338 of file DBCStructure.h.
The documentation for this struct was generated from the following file:
DBCStructure.h