CMaNGOS_WoTLK: MaNGOS::DynamicObjectUpdater Struct Reference
MaNGOS::DynamicObjectUpdater Struct Reference
#include <GridNotifiers.h>
Public Member Functions
DynamicObjectUpdater (DynamicObject &dynobject, Unit *caster, bool positive)
template<class T >
void Visit (GridRefManager< T > &)
void VisitHelper (Unit *target)
template<>
void Visit (CreatureMapType &)
template<>
void Visit (PlayerMapType &)
Data Fields
DynamicObject & i_dynobject
Unit * i_check
bool i_positive
bool i_script
Detailed Description
Definition at line 167 of file GridNotifiers.h.
Constructor & Destructor Documentation
DynamicObjectUpdater()
MaNGOS::DynamicObjectUpdater::DynamicObjectUpdater (DynamicObject & dynobject, Unit * caster, bool positive) inline
Definition at line 183 of file GridNotifiersImpl.h.
References Unit::GetOwner(), and i_check.
Member Function Documentation
Visit() [1/3]
template<> void MaNGOS::DynamicObjectUpdater::Visit (CreatureMapType & m) inline
Definition at line 315 of file GridNotifiersImpl.h.
Visit() [2/3]
template<class T > void MaNGOS::DynamicObjectUpdater::Visit (GridRefManager< T > &) inline
Definition at line 175 of file GridNotifiers.h.
Visit() [3/3]
template<> void MaNGOS::DynamicObjectUpdater::Visit (PlayerMapType & m) inline
Definition at line 322 of file GridNotifiersImpl.h.
VisitHelper()
void MaNGOS::DynamicObjectUpdater::VisitHelper (Unit * target) inline
Definition at line 192 of file GridNotifiersImpl.h.
References SpellAuraHolder::AddAura(), Unit::AddAuraToModList(), Unit::AddSpellAuraHolder(), Aura::ApplyModifier(), Unit::CanAssistSpell(), Unit::CanAttackSpell(), Unit::CasterHitTargetWithSpell(), CreateSpellAuraHolder(), DIST_CALC_NONE, SQLMultiStorage::SQLMSIteratorBounds< T >::first, SpellAuraHolder::GetAuraByEffectIndex(), SpellAuraHolder::GetAuraDuration(), SQLMultiStorage::getBounds(), Unit::GetCombatManager(), Unit::GetCombatReach(), Object::GetEntry(), Unit::GetSpellAuraHolder(), Object::GetTypeId(), SpellEntry::HasAttribute(), SpellEntry::Id, Unit::IsAlive(), Unit::IsImmuneToSpell(), Unit::IsImmuneToSpellEffect(), CombatManager::IsInEvadeMode(), Unit::IsPlayerControlled(), Unit::IsTaxiFlying(), SQLStorage::LookupEntry(), SQLMultiStorage::SQLMSIteratorBounds< T >::second, SpellAuraHolder::SendAuraUpdate(), SpellAuraHolder::SetAuraDuration(), SPELL_ATTR_EX2_IGNORE_LINE_OF_SIGHT, SPELL_ATTR_EX3_ONLY_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER, SPELL_ATTR_EX5_NOT_ON_PLAYER_CONTROLLED_NPC, SPELL_ATTR_NO_IMMUNITIES, SPELL_TARGET_TYPE_CREATURE, SPELL_TARGET_TYPE_DEAD, SPELL_TARGET_TYPE_GAMEOBJECT, SPELL_TARGET_TYPE_GAMEOBJECT_GUID, sSpellScriptTargetStorage, sSpellTemplate, TYPEID_PLAYER, TYPEID_UNIT, and VISIBILITY_OFF.
Field Documentation
i_check
Unit* MaNGOS::DynamicObjectUpdater::i_check
Definition at line 170 of file GridNotifiers.h.
Referenced by DynamicObjectUpdater().
i_dynobject
DynamicObject& MaNGOS::DynamicObjectUpdater::i_dynobject
Definition at line 169 of file GridNotifiers.h.
i_positive
bool MaNGOS::DynamicObjectUpdater::i_positive
Definition at line 171 of file GridNotifiers.h.
i_script
bool MaNGOS::DynamicObjectUpdater::i_script
Definition at line 172 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h