CMaNGOS_WoTLK: SpawnGameObjectInMapsWorker Struct Reference
SpawnGameObjectInMapsWorker Struct Reference
Public Member Functions
SpawnGameObjectInMapsWorker (uint32 guid, GameObjectData const *data)
void operator() (Map *map)
Data Fields
uint32 i_guid
GameObjectData const * i_data
Detailed Description
Definition at line 2313 of file GameObject.cpp.
Constructor & Destructor Documentation
SpawnGameObjectInMapsWorker()
SpawnGameObjectInMapsWorker::SpawnGameObjectInMapsWorker (uint32 guid, GameObjectData const * data) inline
Definition at line 2315 of file GameObject.cpp.
Member Function Documentation
operator()()
void SpawnGameObjectInMapsWorker::operator() (Map * map) inline
Definition at line 2318 of file GameObject.cpp.
References GameObject::CreateGameObject(), i_data, i_guid, GameObjectData::id, Map::IsLoaded(), GameObject::LoadFromDB(), MANGOS_ASSERT, GameObjectData::posX, GameObjectData::posY, and sObjectMgr.
Field Documentation
i_data
GameObjectData const* SpawnGameObjectInMapsWorker::i_data
Definition at line 2335 of file GameObject.cpp.
Referenced by operator()().
i_guid
uint32 SpawnGameObjectInMapsWorker::i_guid
Definition at line 2334 of file GameObject.cpp.
Referenced by operator()().
The documentation for this struct was generated from the following file:
GameObject.cpp