CMaNGOS_WoTLK: DreadsteedQuestObjects Struct Reference
DreadsteedQuestObjects Struct Reference
Public Member Functions
DreadsteedQuestObjects (GameObject *go)
void JustSpawned () override
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
void OnLootStateChange (Unit *) override
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
void OnUse (Unit *user, SpellEntry const *) override
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnGoStateChange (GOState)
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
uint32 m_uiPulseTimer = 0
ObjectGuid m_lastUserGuid
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 164 of file dire_maul.cpp.
Constructor & Destructor Documentation
DreadsteedQuestObjects()
DreadsteedQuestObjects::DreadsteedQuestObjects (GameObject * go) inline
Definition at line 166 of file dire_maul.cpp.
Member Function Documentation
JustSpawned()
void DreadsteedQuestObjects::JustSpawned () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 171 of file dire_maul.cpp.
References GameObjectAI::m_go, and GameObject::SetRespawnDelay().
OnLootStateChange()
void DreadsteedQuestObjects::OnLootStateChange (Unit *) inline override virtual
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
Reimplemented from GameObjectAI.
Definition at line 213 of file dire_maul.cpp.
References GameObject::GetLootState(), GO_JUST_DEACTIVATED, GameObjectAI::m_go, and m_uiPulseTimer.
OnUse()
void DreadsteedQuestObjects::OnUse (Unit * user, SpellEntry const *) inline override virtual
Reimplemented from GameObjectAI.
Definition at line 219 of file dire_maul.cpp.
References Object::GetObjectGuid(), m_lastUserGuid, and m_uiPulseTimer.
UpdateAI()
void DreadsteedQuestObjects::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 176 of file dire_maul.cpp.
References GameObject::CastSpell(), Object::GetEntry(), WorldObject::GetInstanceData(), WorldObject::GetMap(), Map::GetUnit(), GO_BELL_OF_DETHMOORA, GO_DOOMSDAY_CANDLE, GO_RITUAL_CANDLE_AURA, GO_WHEEL_OF_BLACK_MARCH, GameObjectAI::m_go, m_lastUserGuid, m_uiPulseTimer, SPELL_BLACK_MARCH_BLESSING, SPELL_RITUAL_BELL_AURA, SPELL_RITUAL_CANDLE_AURA, and TRIGGERED_OLD_TRIGGERED.
Field Documentation
m_lastUserGuid
ObjectGuid DreadsteedQuestObjects::m_lastUserGuid
Definition at line 169 of file dire_maul.cpp.
Referenced by OnUse(), and UpdateAI().
m_uiPulseTimer
uint32 DreadsteedQuestObjects::m_uiPulseTimer = 0
Definition at line 168 of file dire_maul.cpp.
Referenced by OnLootStateChange(), OnUse(), and UpdateAI().
The documentation for this struct was generated from the following file:
dire_maul.cpp