CMaNGOS_WoTLK: spell_skeletal_gryphon_escape Struct Reference
spell_skeletal_gryphon_escape Struct Reference
Public Member Functions
void OnEffectExecute (Spell *spell, SpellEffectIndex effIdx) const override
Public Member Functions inherited from SpellScript
virtual ~SpellScript ()=default
virtual void OnInit (Spell *) const
virtual void OnSuccessfulStart (Spell *) const
virtual void OnSuccessfulFinish (Spell *) const
virtual SpellCastResult OnCheckCast (Spell *, bool) const
virtual void OnSpellCastResultOverride (SpellCastResult &, uint32 &, uint32 &) const
virtual void OnRadiusCalculate (Spell *, SpellEffectIndex, bool, float &) const
virtual void OnDestTarget (Spell *) const
virtual bool OnCheckTarget (const Spell *, GameObject *, SpellEffectIndex) const
virtual bool OnCheckTarget (const Spell *, Unit *, SpellEffectIndex) const
virtual void OnCast (Spell *) const
virtual void OnHit (Spell *, SpellMissInfo) const
virtual void OnAfterHit (Spell *) const
virtual void OnSummon (Spell *, Creature *) const
virtual void OnSummon (Spell *, GameObject *) const
virtual uint32 GetPhaseMaskOverride (Spell *) const
Detailed Description
Definition at line 2302 of file ebon_hold.cpp.
Member Function Documentation
OnEffectExecute()
void spell_skeletal_gryphon_escape::OnEffectExecute (Spell * spell, SpellEffectIndex effIdx) const inline override virtual
Reimplemented from SpellScript.
Definition at line 2304 of file ebon_hold.cpp.
References SpellEntry::CalculateSimpleValue(), EFFECT_INDEX_0, Spell::GetUnitTarget(), WorldObject::IsBoarded(), Object::IsPlayer(), Spell::m_spellInfo, and Unit::RemoveAurasDueToSpell().
The documentation for this struct was generated from the following file:
ebon_hold.cpp