CMaNGOS_WoTLK: GossipNPCPeriodicTriggerTalk Struct Reference
GossipNPCPeriodicTriggerTalk Struct Reference
Public Member Functions
void OnEffectExecute (Spell *spell, SpellEffectIndex) const override
Public Member Functions inherited from SpellScript
virtual ~SpellScript ()=default
virtual void OnInit (Spell *) const
virtual void OnSuccessfulStart (Spell *) const
virtual void OnSuccessfulFinish (Spell *) const
virtual SpellCastResult OnCheckCast (Spell *, bool) const
virtual void OnSpellCastResultOverride (SpellCastResult &, uint32 &, uint32 &) const
virtual void OnRadiusCalculate (Spell *, SpellEffectIndex, bool, float &) const
virtual void OnDestTarget (Spell *) const
virtual bool OnCheckTarget (const Spell *, GameObject *, SpellEffectIndex) const
virtual bool OnCheckTarget (const Spell *, Unit *, SpellEffectIndex) const
virtual void OnCast (Spell *) const
virtual void OnHit (Spell *, SpellMissInfo) const
virtual void OnAfterHit (Spell *) const
virtual void OnSummon (Spell *, Creature *) const
virtual void OnSummon (Spell *, GameObject *) const
virtual uint32 GetPhaseMaskOverride (Spell *) const
Detailed Description
Definition at line 2860 of file npcs_special.cpp.
Member Function Documentation
OnEffectExecute()
void GossipNPCPeriodicTriggerTalk::OnEffectExecute (Spell * spell, SpellEffectIndex) const inline override virtual
Reimplemented from SpellScript.
Definition at line 2862 of file npcs_special.cpp.
References Unit::AI(), brewfestTextsAlliance, brewfestTextsHorde, DoBroadcastText(), Spell::GetCaster(), Object::GetEntry(), GetRandomText(), Spell::GetUnitTarget(), GOSSIP_EVENT_BREWFEST, GOSSIP_EVENT_HALLOWS_END, GOSSIP_EVENT_LUNAR_FESTIVAL, GOSSIP_EVENT_MIDSUMMER, GOSSIP_EVENT_PIRATES_DAY, GOSSIP_EVENT_SPIRIT_OF_COMPETITION, GOSSIP_EVENT_WINTER_VEIL, hallowsEndTextsAlliance, hallowsEndTextsHorde, lunarTextsAlliance, lunarTextsHorde, GossipNPCAI::m_chosenEvent, midsummerTextsAlliance, midsummerTextsHorde, NPC_BLOOD_ELF_COMMONER, NPC_DRAENEI_COMMONER, NPC_DWARF_COMMONER, NPC_FORSAKEN_COMMONER, NPC_GNOME_COMMONER, NPC_GOBLIN_COMMONER, NPC_HUMAN_COMMONER, NPC_NIGHT_ELF_COMMONER, NPC_ORC_COMMONER, NPC_TAUREN_COMMONER, NPC_TROLL_COMMONER, winterTextsAlliance, winterTextsGoblin, and winterTextsHorde.
The documentation for this struct was generated from the following file:
npcs_special.cpp