CMaNGOS_WoTLK: go_ai_bell Struct Reference
go_ai_bell Struct Reference
Public Member Functions
go_ai_bell (GameObject *go)
uint32 GetBellSound (GameObject *pGo) const
PlayPacketSettings GetBellZoneOrArea (GameObject *pGo) const
void OnEventHappened (uint16 event_id, bool activate, bool resume) override
Called when a Game Event starts or ends.
void UpdateAI (const uint32 uiDiff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
uint32 m_uiBellTolls
uint32 m_uiBellSound
uint32 m_uiBellTimer
PlayPacketSettings m_playTo
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 443 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_ai_bell()
go_ai_bell::go_ai_bell (GameObject * go) inline
Definition at line 445 of file go_scripts.cpp.
References GameObjectAI::m_go, WorldObject::SetActiveObjectState(), and WorldObject::SetNotifyOnEventState().
Member Function Documentation
GetBellSound()
uint32 go_ai_bell::GetBellSound (GameObject * pGo) const inline
Definition at line 456 of file go_scripts.cpp.
References BELLTOLLALLIANCE, BELLTOLLDWARFGNOME, BELLTOLLHORDE, BELLTOLLKARAZHAN, BELLTOLLNIGHTELF, BELLTOLLTRIBAL, BRILL_AREA, DARNASSUS_AREA, WorldObject::GetAreaId(), Object::GetEntry(), GO_ALLIANCE_BELL, GO_HORDE_BELL, GO_KARAZHAN_BELL, IRONFORGE_1_AREA, IRONFORGE_2_AREA, TARREN_MILL_AREA, and UNDERCITY_AREA.
GetBellZoneOrArea()
PlayPacketSettings go_ai_bell::GetBellZoneOrArea (GameObject * pGo) const inline
Definition at line 500 of file go_scripts.cpp.
References DARNASSUS_AREA, WorldObject::GetAreaId(), Object::GetEntry(), GO_ALLIANCE_BELL, GO_HORDE_BELL, GO_KARAZHAN_BELL, IRONFORGE_2_AREA, PLAY_AREA, PLAY_ZONE, and UNDERCITY_AREA.
OnEventHappened()
void go_ai_bell::OnEventHappened (uint16 , bool , bool) inline override virtual
Called when a Game Event starts or ends.
Parameters
eventId to specify id of event from database
activate to specify if it started or stopped
resume to specify whether it launched normally or was resumed after a restart
Reimplemented from GameObjectAI.
Definition at line 531 of file go_scripts.cpp.
References EVENT_ID_BELLS, WorldObject::GetAreaId(), WorldObject::GetMap(), GameObjectAI::m_go, m_uiBellSound, m_uiBellTimer, m_uiBellTolls, and Map::PlayDirectSoundToMap().
UpdateAI()
void go_ai_bell::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 546 of file go_scripts.cpp.
References WorldObject::GetAreaId(), GameObjectAI::m_go, m_uiBellSound, m_uiBellTimer, m_uiBellTolls, PLAY_AREA, and WorldObject::PlayDirectSound().
Field Documentation
m_playTo
PlayPacketSettings go_ai_bell::m_playTo
Definition at line 454 of file go_scripts.cpp.
m_uiBellSound
uint32 go_ai_bell::m_uiBellSound
Definition at line 452 of file go_scripts.cpp.
Referenced by OnEventHappened(), and UpdateAI().
m_uiBellTimer
uint32 go_ai_bell::m_uiBellTimer
Definition at line 453 of file go_scripts.cpp.
Referenced by OnEventHappened(), and UpdateAI().
m_uiBellTolls
uint32 go_ai_bell::m_uiBellTolls
Definition at line 451 of file go_scripts.cpp.
Referenced by OnEventHappened(), and UpdateAI().
The documentation for this struct was generated from the following file:
go_scripts.cpp