CMaNGOS_WoTLK: ItemRequiredTarget Struct Reference
ItemRequiredTarget Struct Reference
#include <Item.h>
Public Member Functions
ItemRequiredTarget (ItemRequiredTargetType uiType, uint32 uiTargetEntry)
bool IsFitToRequirements (Unit *pUnitTarget) const
Data Fields
ItemRequiredTargetType m_uiType
uint32 m_uiTargetEntry
Detailed Description
Definition at line 259 of file Item.h.
Constructor & Destructor Documentation
ItemRequiredTarget()
ItemRequiredTarget::ItemRequiredTarget (ItemRequiredTargetType uiType, uint32 uiTargetEntry) inline
Definition at line 261 of file Item.h.
Member Function Documentation
IsFitToRequirements()
bool ItemRequiredTarget::IsFitToRequirements (Unit * pUnitTarget) const
Definition at line 1256 of file Item.cpp.
References Object::GetEntry(), Object::GetTypeId(), Unit::IsAlive(), ITEM_TARGET_TYPE_CREATURE, ITEM_TARGET_TYPE_DEAD, m_uiTargetEntry, m_uiType, and TYPEID_UNIT.
Field Documentation
m_uiTargetEntry
uint32 ItemRequiredTarget::m_uiTargetEntry
Definition at line 263 of file Item.h.
Referenced by IsFitToRequirements().
m_uiType
ItemRequiredTargetType ItemRequiredTarget::m_uiType
Definition at line 262 of file Item.h.
Referenced by IsFitToRequirements().
The documentation for this struct was generated from the following files:
Item.h
Item.cpp