CMaNGOS_WoTLK: go_ai_fixed_trap Struct Reference
go_ai_fixed_trap Struct Reference
Public Member Functions
go_ai_fixed_trap (GameObject *go)
void UpdateAI (const uint32) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 628 of file instance_dire_maul.cpp.
Constructor & Destructor Documentation
go_ai_fixed_trap()
go_ai_fixed_trap::go_ai_fixed_trap (GameObject * go) inline
Definition at line 630 of file instance_dire_maul.cpp.
Member Function Documentation
UpdateAI()
void go_ai_fixed_trap::UpdateAI (const uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 632 of file instance_dire_maul.cpp.
References DoScriptText(), FACTION_HOSTILE, GetClosestCreatureWithEntry(), GO_JUST_DEACTIVATED, GameObject::IsSpawned(), GameObjectAI::m_go, NPC_GUARD_SLIPKIK, SAY_SLIPKIK_TRAP, GameObject::SetLootState(), TEMPFACTION_RESTORE_RESPAWN, and GameObject::Use().
The documentation for this struct was generated from the following file:
instance_dire_maul.cpp