CMaNGOS_WoTLK: MaNGOS::VisibleNotifier Struct Reference
MaNGOS::VisibleNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
VisibleNotifier (Camera &c)
template<class T >
void Visit (GridRefManager< T > &m)
void Visit (CameraMapType &)
void Notify (void)
Data Fields
Camera & i_camera
UpdateData i_data
GuidSet i_clientGUIDs
WorldObjectSet i_visibleNow
Detailed Description
Definition at line 36 of file GridNotifiers.h.
Constructor & Destructor Documentation
VisibleNotifier()
MaNGOS::VisibleNotifier::VisibleNotifier (Camera & c) inline explicit
Definition at line 43 of file GridNotifiers.h.
Member Function Documentation
Notify()
void VisibleNotifier::Notify (void)
Definition at line 41 of file GridNotifiers.cpp.
References UpdateData::AddOutOfRangeGUID(), Player::BeforeVisibilityDestroy(), UpdateData::BuildPacket(), DEBUG_FILTER_LOG, ObjectAccessor::FindPlayer(), Object::GetGuidStr(), WorldObject::GetMap(), UpdateData::GetOutOfRangeGUIDs(), Camera::GetOwner(), UpdateData::GetPacketCount(), Player::GetSession(), WorldObject::GetTransport(), Map::GetWorldObject(), UpdateData::HasData(), i_camera, i_clientGUIDs, i_data, i_visibleNow, Object::isType(), LOG_FILTER_VISIBILITY_CHANGES, Map::m_objRemoveList, Player::RemoveAtClient(), Player::SendAurasForTarget(), WorldSession::SendPacket(), sLog, TYPEID_UNIT, TYPEMASK_UNIT, and Player::UpdateVisibilityOf().
Referenced by Camera::UpdateVisibilityForOwner().
Visit() [1/2]
void MaNGOS::VisibleNotifier::Visit (CameraMapType &) inline
Definition at line 45 of file GridNotifiers.h.
Visit() [2/2]
template<class T > void MaNGOS::VisibleNotifier::Visit (GridRefManager< T > & m) inline
Definition at line 33 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), i_camera, i_clientGUIDs, i_data, i_visibleNow, and Camera::UpdateVisibilityOf().
Field Documentation
i_camera
Camera& MaNGOS::VisibleNotifier::i_camera
Definition at line 38 of file GridNotifiers.h.
Referenced by Notify(), and Visit().
i_clientGUIDs
GuidSet MaNGOS::VisibleNotifier::i_clientGUIDs
Definition at line 40 of file GridNotifiers.h.
Referenced by Notify(), and Visit().
i_data
UpdateData MaNGOS::VisibleNotifier::i_data
Definition at line 39 of file GridNotifiers.h.
Referenced by Notify(), and Visit().
i_visibleNow
WorldObjectSet MaNGOS::VisibleNotifier::i_visibleNow
Definition at line 41 of file GridNotifiers.h.
Referenced by Notify(), and Visit().
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp
GridNotifiersImpl.h