CMaNGOS_WoTLK: Cell Struct Reference
Cell Struct Reference
#include <Cell.h>
Public Member Functions
Cell ()
Cell (const Cell &cell)
Cell (CellPair const &p)
void Compute (uint32 &x, uint32 &y) const
bool DiffCell (const Cell &cell) const
bool DiffGrid (const Cell &cell) const
uint32 CellX () const
uint32 CellY () const
uint32 GridX () const
uint32 GridY () const
bool NoCreate () const
void SetNoCreate ()
GridPair gridPair () const
CellPair cellPair () const
Cell & operator= (const Cell &cell)
bool operator== (const Cell &cell) const
bool operator!= (const Cell &cell) const
template<class T , class CONTAINER >
void Visit (const CellPair &cellPair, TypeContainerVisitor< T, CONTAINER > &visitor, Map &m, float x, float y, float radius) const
template<class T , class CONTAINER >
void Visit (const CellPair &cellPair, TypeContainerVisitor< T, CONTAINER > &visitor, Map &m, const WorldObject &obj, float radius) const
Static Public Member Functions
static CellArea CalculateCellArea (float x, float y, float radius)
template<class T >
static void VisitGridObjects (const WorldObject *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (const WorldObject *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (const WorldObject *obj, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitGridObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitWorldObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
template<class T >
static void VisitAllObjects (float x, float y, Map *map, T &visitor, float radius, bool dont_load=true)
Data Fields
union {
struct {
unsigned grid_x: 6
unsigned grid_y: 6
unsigned cell_x: 6
unsigned cell_y: 6
unsigned nocreate: 1
unsigned reserved: 7
} Part
uint32 All
} data
Private Member Functions
template<class T , class CONTAINER >
void VisitCircle (TypeContainerVisitor< T, CONTAINER > &, Map &, const CellPair &, const CellPair &) const
Detailed Description
Definition at line 45 of file Cell.h.
Constructor & Destructor Documentation
Cell() [1/3]
Cell::Cell () inline
Definition at line 47 of file Cell.h.
References data.
Cell() [2/3]
Cell::Cell (const Cell & cell) inline
Definition at line 48 of file Cell.h.
References All, and data.
Cell() [3/3]
Cell::Cell (CellPair const & p) inline explicit
Definition at line 27 of file CellImpl.h.
References data, MAX_NUMBER_OF_CELLS, CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Member Function Documentation
CalculateCellArea()
CellArea Cell::CalculateCellArea (float x, float y, float radius) inline static
Definition at line 37 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), and CoordPair< LIMIT >::normalize().
Referenced by Map::Update(), Visit(), and Map::VisitNearbyCellsOf().
cellPair()
CellPair Cell::cellPair () const inline
Definition at line 78 of file Cell.h.
References data, and MAX_NUMBER_OF_CELLS.
CellX()
uint32 Cell::CellX () const inline
Definition at line 69 of file Cell.h.
References data.
Referenced by Map::Add(), Map::AddToGrid(), Map::CreatePlayerOnClient(), Map::CreatureCellRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::EnsureGridLoaded(), Map::EnsureGridLoadedAtEnter(), Map::GameObjectRelocation(), ChatHandler::HandleGPSCommand(), Map::PlayerRelocation(), Map::RemoveFromGrid(), Map::Visit(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
CellY()
uint32 Cell::CellY () const inline
Definition at line 70 of file Cell.h.
References data.
Referenced by Map::Add(), Map::AddToGrid(), Map::CreatePlayerOnClient(), Map::CreatureCellRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::EnsureGridLoaded(), Map::EnsureGridLoadedAtEnter(), Map::GameObjectRelocation(), ChatHandler::HandleGPSCommand(), Map::PlayerRelocation(), Map::RemoveFromGrid(), Map::Visit(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
Compute()
void Cell::Compute (uint32 & x, uint32 & y) const inline
Definition at line 51 of file Cell.h.
References data, and MAX_NUMBER_OF_CELLS.
DiffCell()
bool Cell::DiffCell (const Cell & cell) const inline
Definition at line 57 of file Cell.h.
References data, and Part.
Referenced by Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), and Map::PlayerRelocation().
DiffGrid()
bool Cell::DiffGrid (const Cell & cell) const inline
Definition at line 63 of file Cell.h.
References data, and Part.
Referenced by Map::CreatureCellRelocation(), Map::DynamicObjectRelocation(), Map::GameObjectRelocation(), Map::PlayerRelocation(), and ObjectGridRespawnMover::Visit().
gridPair()
GridPair Cell::gridPair () const inline
Definition at line 76 of file Cell.h.
References GridX(), and GridY().
Referenced by Map::CreatureCellRelocation(), Map::DynamicObjectRelocation(), and Map::GameObjectRelocation().
GridX()
uint32 Cell::GridX () const inline
Definition at line 71 of file Cell.h.
References data.
Referenced by Map::Add(), Map::CreatePlayerOnClient(), Map::CreatureCellRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::EnsureGridLoaded(), Map::EnsureGridLoadedAtEnter(), Map::ForceLoadGrid(), Map::GameObjectRelocation(), gridPair(), ChatHandler::HandleGPSCommand(), Map::PlayerRelocation(), Map::Remove(), Map::Visit(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
GridY()
uint32 Cell::GridY () const inline
Definition at line 72 of file Cell.h.
References data.
Referenced by Map::Add(), Map::CreatePlayerOnClient(), Map::CreatureCellRelocation(), Map::CreatureRespawnRelocation(), Map::DynamicObjectRelocation(), Map::EnsureGridLoaded(), Map::EnsureGridLoadedAtEnter(), Map::ForceLoadGrid(), Map::GameObjectRelocation(), gridPair(), ChatHandler::HandleGPSCommand(), Map::PlayerRelocation(), Map::Remove(), Map::Visit(), ObjectWorldLoader::Visit(), and ObjectGridLoader::Visit().
NoCreate()
bool Cell::NoCreate () const inline
Definition at line 73 of file Cell.h.
References data.
Referenced by Map::Visit().
operator!=()
bool Cell::operator!= (const Cell & cell) const inline
Definition at line 92 of file Cell.h.
References operator==().
operator=()
Cell& Cell::operator= (const Cell & cell) inline
Definition at line 85 of file Cell.h.
References All, and data.
operator==()
bool Cell::operator== (const Cell & cell) const inline
Definition at line 91 of file Cell.h.
References All, and data.
Referenced by operator!=().
SetNoCreate()
void Cell::SetNoCreate () inline
Definition at line 74 of file Cell.h.
References data.
Referenced by Map::ExecuteDistWorker(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), Map::Update(), Map::UpdateObjectVisibility(), VisitAllObjects(), VisitGridObjects(), Map::VisitNearbyCellsOf(), and VisitWorldObjects().
Visit() [1/2]
template<class T , class CONTAINER > void Cell::Visit (const CellPair & cellPair, TypeContainerVisitor< T, CONTAINER > & visitor, Map & m, const WorldObject & obj, float radius) const inline
Definition at line 54 of file CellImpl.h.
References WorldObject::GetObjectBoundingRadius(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), and Visit().
Visit() [2/2]
template<class T , class CONTAINER > void Cell::Visit (const CellPair & cellPair, TypeContainerVisitor< T, CONTAINER > & visitor, Map & m, float x, float y, float radius) const inline
Definition at line 62 of file CellImpl.h.
References CalculateCellArea(), data, CellArea::high_bound, CellArea::low_bound, MAX_VISIBILITY_DISTANCE, Part, TOTAL_NUMBER_OF_CELLS_PER_MAP, Map::Visit(), VisitCircle(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Map::ExecuteDistWorker(), PlayerbotAI::findNearbyCreature(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), Map::UpdateObjectVisibility(), Visit(), VisitAllObjects(), VisitGridObjects(), and VisitWorldObjects().
VisitAllObjects() [1/2]
template<class T > void Cell::VisitAllObjects (const WorldObject * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 197 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), MANGOS_ASSERT, SetNoCreate(), and Visit().
Referenced by Spell::CheckScriptTargeting(), Spell::EffectScriptEffect(), UnitVisitObjectsInRangeNotifyEvent::Execute(), ChaseMovementGenerator::FanOut(), Spell::FillAreaTargets(), PlayerbotAI::findNearbyCorpse(), ScriptAction::GetScriptProcessTargets(), Player::HandleStealthedUnitsDetection(), Unit::InterruptSpellsCastedOnMe(), GameobjectCallForHelpOnUsage::OnSuccessfulStart(), SelectRandomFlameshockerSpawnTarget(), Unit::SelectRandomFriendlyTarget(), Unit::SelectRandomUnfriendlyTarget(), UnitAI::SendAIEventAround(), Spell::SendSpellGo(), Player::SetGameMaster(), Spell::SetTargetMap(), DynamicObject::Update(), GameObject::Update(), AreaAura::Update(), TotemAI::UpdateAI(), and Camera::UpdateVisibilityForOwner().
VisitAllObjects() [2/2]
template<class T > void Cell::VisitAllObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 235 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), SetNoCreate(), and Visit().
VisitCircle()
template<class T , class CONTAINER > void Cell::VisitCircle (TypeContainerVisitor< T, CONTAINER > & visitor, Map & m, const CellPair & begin_cell, const CellPair & end_cell) const inline private
Definition at line 123 of file CellImpl.h.
References data, Part, Map::Visit(), CoordPair< LIMIT >::x_coord, and CoordPair< LIMIT >::y_coord.
Referenced by Visit().
VisitGridObjects() [1/2]
template<class T > void Cell::VisitGridObjects (const WorldObject * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 175 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), SetNoCreate(), and Visit().
Referenced by Creature::CallForHelp(), Spell::CheckCast(), Spell::CheckScriptTargeting(), UnitAI::DoFindFriendlyEligibleDispel(), ScriptedAI::DoFindFriendlyMissingBuff(), UnitAI::DoFindFriendlyMissingBuff(), CreatureAI::DoRetreat(), UnitAI::DoSelectConditionalFriendly(), UnitAI::DoSelectLowestHpFriendly(), Spell::EffectDummy(), Spell::EffectScriptEffect(), ConditionEntry::Evaluate(), ScriptAction::ExecuteDbscriptCommand(), Spell::FindCorpseUsing(), PlayerbotAI::findNearbyGO(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), PlayerbotClassAI::FleeFromTrapGOIfCan(), GetClosestCreatureWithEntry(), GetClosestGameObjectWithEntry(), GetCreatureListWithEntryInGrid(), GetGameObjectListWithEntryInGrid(), ScriptAction::GetScriptProcessTargets(), GOUse_go_cage_door(), ChatHandler::HandleGameObjectNearSpawnedCommand(), ChatHandler::HandleMmapTestArea(), ChatHandler::HandleRespawnCommand(), GameObject::LookupFishingHoleAround(), CombatConditionMgr::Meets(), Spell::OnCheckTarget(), go_covertopsAI::OnLootStateChange(), Spell::SetTargetMap(), GameObject::TriggerLinkedGameObject(), UnsummonVisualWaypoints(), and AreaAura::Update().
VisitGridObjects() [2/2]
template<class T > void Cell::VisitGridObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 213 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), SetNoCreate(), and Visit().
VisitWorldObjects() [1/2]
template<class T > void Cell::VisitWorldObjects (const WorldObject * obj, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 186 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), WorldObject::GetMap(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), SetNoCreate(), and Visit().
Referenced by _DoLocalizedTextAround(), WorldObject::BuildUpdateData(), Spell::FindCorpseUsing(), ScriptedAI::GetPlayerAtMinimumRange(), GetPlayerListWithEntryInWorld(), ScriptAction::GetScriptProcessTargets(), WorldSession::HandleTextEmoteOpcode(), Spell::OnCheckTarget(), GreaterInvisibilityMob::OnPeriodicTickEnd(), AchievementMgr::SendAchievementEarned(), WorldObject::SendMessageToSetExcept(), and GameObject::TickCapturePoint().
VisitWorldObjects() [2/2]
template<class T > void Cell::VisitWorldObjects (float x, float y, Map * map, T & visitor, float radius, bool dont_load = true) inline static
Definition at line 224 of file CellImpl.h.
References MaNGOS::ComputeCellPair(), SetNoCreate(), and Visit().
Field Documentation
All
uint32 Cell::All
Definition at line 104 of file Cell.h.
Referenced by Cell(), operator=(), and operator==().
cell_x
unsigned Cell::cell_x
Definition at line 99 of file Cell.h.
cell_y
unsigned Cell::cell_y
Definition at line 100 of file Cell.h.
union { ... } Cell::data
Referenced by Cell(), cellPair(), CellX(), CellY(), Compute(), DiffCell(), DiffGrid(), Map::ExecuteDistWorker(), GridX(), GridY(), ObjectGridLoader::LoadN(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), NoCreate(), operator=(), operator==(), Map::Remove(), SetNoCreate(), Visit(), and VisitCircle().
grid_x
unsigned Cell::grid_x
Definition at line 97 of file Cell.h.
grid_y
unsigned Cell::grid_y
Definition at line 98 of file Cell.h.
nocreate
unsigned Cell::nocreate
Definition at line 101 of file Cell.h.
struct { ... } Cell::Part
Referenced by DiffCell(), DiffGrid(), Map::ExecuteDistWorker(), ObjectGridLoader::LoadN(), Map::MessageBroadcast(), Map::MessageDistBroadcast(), Map::Remove(), Visit(), and VisitCircle().
reserved
unsigned Cell::reserved
Definition at line 102 of file Cell.h.
The documentation for this struct was generated from the following files:
Cell.h
CellImpl.h