CMaNGOS_WoTLK: world_map_outland Struct Reference
world_map_outland Struct Reference
Public Member Functions
world_map_outland (Map *pMap)
void Initialize () override
uint32 GetData (uint32 type) const override
void SetData (uint32 type, uint32 data) override
bool CheckConditionCriteriaMeet (Player const *player, uint32 instanceConditionId, WorldObject const *conditionSource, uint32 conditionSourceType) const override
uint32 CalculateBashirTimerValue ()
void FillInitialWorldStates (ByteBuffer &data, uint32 &count, uint32, uint32 areaId) override
uint32 GetIntroTimer (uint32 eventId)
void StartBashirLandingEvent ()
void SpawnAlliesAtCrystalforge (BashirPhases phaseId, Player *player)
void StartBashirAtCustomSpot (BashirPhases phaseId, Player *player)
void HandleBashirMobDeath (Creature *creature)
void SpawnRandomBashirMob ()
void SpawnTowerDefenders ()
void DespawnCrystalforgeGuardians ()
void DespawnBashir (bool all)
uint32 GetActionTimer (OutlandActions action)
void StartBattlePhase ()
void StartTransitionPhase ()
void StartPhase (BashirPhases phase)
void SpawnBoss (BashirPhases phase)
void FinishPhase (BashirPhases phase)
void StartManaSlaveEvent ()
void HandleBashirSpawnEnemy ()
void HandleBashirEnemyAttack ()
void HandleBashirOutro ()
void ScriptAction (uint32 eventId)
Creature * GetShartuulManager ()
Creature * GetCurrentDemon ()
Player * GetCurrentPlayer ()
void ProgressShartuul (ShartuulPhases phase)
uint32 GetSpellIdForEntry (uint32 entry)
void HandleShartuulAddSpawns ()
void HandleShartuulAddAttack ()
void HandleShartuulEventReset ()
void HandleShartuulSpawnSequence ()
void OnCreatureCreate (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void OnCreatureEvade (Creature *creature) override
void OnCreatureDespawn (Creature *creature) override
void OnCreatureDeath (Creature *creature) override
void OnObjectCreate (GameObject *go) override
void Update (const uint32 diff) override
void ShowChatCommands (ChatHandler *handler) override
void ExecuteChatCommand (ChatHandler *handler, char *args) override
Public Member Functions inherited from ScriptedMap
ScriptedMap (Map *map)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void ResetTimer (uint32 index, uint32 timer)
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index)
virtual void ReduceTimer (uint32 index, uint32 timer)
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer)
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer)
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
virtual void UpdateTimers (const uint32 diff)
virtual void UpdateTimers (const uint32 diff, bool combat)
virtual void ResetAllTimers ()
virtual void GetAIInformation (ChatHandler &reader)
Data Fields
uint8 m_uiEmissaryOfHate_KilledAddCount
uint8 m_uiRazaan_KilledAddCount
ObjectGuid m_lastRingOfBlood
uint32 m_shartuulEventActive
uint32 m_shartuulShieldPercent
ShartuulPhases m_shartuulPhase
GuidVector m_shartuulAttackAdds
uint32 m_shartuulWave
Position m_spawnPosition
uint32 m_shartuulSpawnSequenceStage
ObjectGuid m_shartuulLargeAOI
ObjectGuid m_playerGuid
std::set< ObjectGuid > m_ignoredGuids
GuidVector m_fires
uint32 m_shartuulTimer
std::tm m_bashirTime
uint32 m_bashirTimer
BashirPhases m_bashirPhase
GuidVector m_bashirSpawns
GuidVector m_bashirEnemySpawns
GuidVector m_bashirEnemyWaveSpawns
Creature * m_apprentice
uint32 m_bashirIntroStage
uint32 m_deadTowerCounter
uint32 m_bashirKillCounter
std::vector< BashirCombatSpawn * > m_bashirPhaseSpawnData
std::vector< BashirCombatSpawn * > m_bashirPhaseSpawnDataUsed
ShadeOfTheHorsemanData m_shadeData
Data Fields inherited from InstanceData
Map * instance
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 257 of file world_outland.cpp.
Constructor & Destructor Documentation
world_map_outland()
world_map_outland::world_map_outland (Map * pMap) inline
Definition at line 259 of file world_outland.cpp.
References AREAID_AZURE_WATCH, and AREAID_FALCONWING_SQUARE.
Member Function Documentation
CalculateBashirTimerValue()
uint32 world_map_outland::CalculateBashirTimerValue () inline
Definition at line 475 of file world_outland.cpp.
References m_bashirTime.
Referenced by FillInitialWorldStates(), and Update().
CheckConditionCriteriaMeet()
bool world_map_outland::CheckConditionCriteriaMeet (Player const * player, uint32 instanceConditionId, WorldObject const * conditionSource, uint32 conditionSourceType) const inline override virtual
Reimplemented from InstanceData.
Definition at line 451 of file world_outland.cpp.
References BASHIR_PHASE_START, WorldObject::GetAreaId(), Object::GetGuidStr(), ScriptedInstance::GetSingleCreatureFromStorage(), INSTANCE_CONDITION_ID_BASHIR_FLYING, INSTANCE_CONDITION_ID_BASHIR_IN_PROGRESS, INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_GOLDSHIRE, INSTANCE_CONDITION_ID_LET_THE_FIRES_COME_HORDE, INSTANCE_CONDITION_ID_SOCRETHAR_GOSSIP, Unit::IsAlive(), ShadeOfTheHorsemanData::IsConditionFulfilled(), Unit::IsInCombat(), m_bashirPhase, m_shadeData, NPC_SOCRETHAR, and script_error_log().
DespawnBashir()
void world_map_outland::DespawnBashir (bool all) inline
Definition at line 663 of file world_outland.cpp.
References BASHIR_DESPAWN, BASHIR_PHASE_NOT_ACTIVE, Map::GetCreature(), InstanceData::instance, m_bashirEnemySpawns, m_bashirPhase, m_bashirSpawns, and NPC_SKYGUARD_AETHER_TECH.
Referenced by ExecuteChatCommand(), and HandleBashirOutro().
DespawnCrystalforgeGuardians()
void world_map_outland::DespawnCrystalforgeGuardians () inline
Definition at line 651 of file world_outland.cpp.
References GetCreatureListWithEntryInGrid(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_BASHIR_CRYSTALFORGE, NPC_BASHIR_RAIDER, and NPC_BASHIR_SPELL_THIEF.
Referenced by SetData(), and StartBashirAtCustomSpot().
ExecuteChatCommand()
void world_map_outland::ExecuteChatCommand (ChatHandler * handler, char * args) inline override virtual
Reimplemented from InstanceData.
Definition at line 1836 of file world_outland.cpp.
References ALLIANCE, BASHIR_DESPAWN, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, BASHIR_PHASE_ALL_VENDORS_SPAWNED, BASHIR_PHASE_START, BASHIR_PHASE_TRANSITION_1, BASHIR_PHASE_TRANSITION_2, BASHIR_PHASE_TRANSITION_3, Player::CanStoreNewItem(), DespawnBashir(), EQUIP_ERR_OK, ChatHandler::ExtractLiteralArg(), ChatHandler::ExtractUInt32(), Item::GenerateItemRandomPropertyId(), WorldSession::GetPlayer(), ObjectGuid::GetRawValue(), ChatHandler::GetSession(), ScriptedInstance::GetSingleGameObjectFromStorage(), Player::GetTeam(), GO_HALAA_BANNER, HandleShartuulEventReset(), ITEM_CRYSTALFORGED_DARKRUNE, m_lastRingOfBlood, NULL_BAG, NULL_SLOT, ChatHandler::PSendSysMessage(), Player::SendNewItem(), StartBashirAtCustomSpot(), StartBashirLandingEvent(), StartEvents_Event(), and Player::StoreNewItem().
FillInitialWorldStates()
void world_map_outland::FillInitialWorldStates (ByteBuffer & data, uint32 & count, uint32 , uint32 areaId) inline override virtual
Reimplemented from InstanceData.
Definition at line 480 of file world_outland.cpp.
References AREAID_SHARTUUL_TRANSPORTER, AREAID_SKYGUARD_OUTPOST, CalculateBashirTimerValue(), InstanceData::FillInitialWorldStateData(), m_shartuulEventActive, m_shartuulShieldPercent, WORLD_STATE_BASHIR_TIMER_WOTLK, WORLD_STATE_SHARTUUL_EVENT_ACTIVE, and WORLD_STATE_SHARTUUL_SHIELD_REMAINING.
FinishPhase()
void world_map_outland::FinishPhase (BashirPhases phase) inline
Definition at line 804 of file world_outland.cpp.
References BASHIR_ACTION_ENEMY_ATTACK, BASHIR_ACTION_SPAWN_ENEMY, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, TimerManager::DisableTimer(), DoScriptText(), Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_bashirEnemySpawns, NPC_SKYGUARD_AETHER_TECH, SAY_TECH_PHASE_1, SAY_TECH_PHASE_2, SAY_TECH_PHASE_3, and StartPhase().
Referenced by OnCreatureDeath().
GetActionTimer()
uint32 world_map_outland::GetActionTimer (OutlandActions action) inline
Definition at line 680 of file world_outland.cpp.
References BASHIR_ACTION_ENEMY_ATTACK, BASHIR_ACTION_INTRO, BASHIR_ACTION_SPAWN_ENEMY, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, and m_bashirPhase.
Referenced by HandleBashirEnemyAttack(), HandleBashirSpawnEnemy(), and StartBattlePhase().
GetCurrentDemon()
Creature* world_map_outland::GetCurrentDemon () inline
Definition at line 1025 of file world_outland.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), m_shartuulPhase, NPC_DOOMGUARD_PUNISHER, NPC_FELGUARD_DEGRADER, NPC_SHIVAN_ASSASSIN, PHASE_0_SHARTUUL_DISABLED, PHASE_1_FELGUARD_DEGRADER_ADDS, PHASE_2_FELGUARD_DEGRADER_BOSS, PHASE_3_DOOMGUARD_PUNISHER_ADDS, PHASE_4_DOOMGUARD_PUNISHER_BOSS, PHASE_5_SHIVAN_ASSASSIN_BOSS_1, PHASE_6_SHIVAN_ASSASSIN_BOSS_2, and PHASE_7_SHIVAN_ASSASSIN_BOSS_3.
Referenced by HandleShartuulAddAttack(), HandleShartuulAddSpawns(), HandleShartuulEventReset(), HandleShartuulSpawnSequence(), ProgressShartuul(), SetData(), and Update().
GetCurrentPlayer()
Player* world_map_outland::GetCurrentPlayer () inline
Definition at line 1045 of file world_outland.cpp.
References Map::GetPlayer(), InstanceData::instance, and m_playerGuid.
Referenced by HandleShartuulSpawnSequence().
GetData()
uint32 world_map_outland::GetData (uint32 type) const inline override virtual
Reimplemented from InstanceData.
Definition at line 333 of file world_outland.cpp.
References ShadeOfTheHorsemanData::HandleGetData(), m_shadeData, TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, and TYPE_SHADE_OF_THE_HORSEMAN_MAX.
GetIntroTimer()
uint32 world_map_outland::GetIntroTimer (uint32 eventId) inline
Definition at line 501 of file world_outland.cpp.
Referenced by ScriptAction(), and StartBashirLandingEvent().
GetShartuulManager()
Creature* world_map_outland::GetShartuulManager () inline
Definition at line 1020 of file world_outland.cpp.
References ScriptedInstance::GetSingleCreatureFromStorage(), and NPC_FEL_PORTAL_ALARM.
GetSpellIdForEntry()
uint32 world_map_outland::GetSpellIdForEntry (uint32 entry) inline
Definition at line 1168 of file world_outland.cpp.
References NPC_FEL_IMP_DEFENDER, NPC_FELHOUND_DEFENDER, NPC_GANARG_UNDERLING, NPC_MOARG_TORMENTER, SPELL_LEGION_RING_FEL_HOUND_TRANSFORM, SPELL_LEGION_RING_FEL_IMP_TRANSFORM, SPELL_LEGION_RING_INFERNAL_TRANSFORM, and SPELL_LEGION_RING_MOARG_TRANSFORM.
Referenced by HandleShartuulAddSpawns().
HandleBashirEnemyAttack()
void world_map_outland::HandleBashirEnemyAttack () inline
Definition at line 843 of file world_outland.cpp.
References BASHIR_ACTION_ENEMY_ATTACK, BASHIR_PHASE_2, GetActionTimer(), Map::GetCreature(), ObjectGuid::GetEntry(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_bashirEnemyWaveSpawns, m_bashirPhase, NPC_BASHIR_SUBPRIMAL, NPC_SKYGUARD_AETHER_TECH, NPC_SLAVERING_SLAVE, TimerManager::ResetTimer(), and urand().
Referenced by Initialize().
HandleBashirMobDeath()
void world_map_outland::HandleBashirMobDeath (Creature * creature) inline
Definition at line 585 of file world_outland.cpp.
References BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, Creature::GetRespawnCoord(), m_bashirKillCounter, m_bashirPhase, m_bashirPhaseSpawnData, m_bashirPhaseSpawnDataUsed, PHASE_1_KILL_COUNT, PHASE_2_KILL_COUNT, PHASE_3_KILL_COUNT, SpawnBoss(), SpawnRandomBashirMob(), BashirCombatSpawn::x, and BashirCombatSpawn::y.
Referenced by OnCreatureDeath().
HandleBashirOutro()
void world_map_outland::HandleBashirOutro () inline
Definition at line 904 of file world_outland.cpp.
References AI_EVENT_CUSTOM_B, DespawnBashir(), DoScriptText(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_SKYGUARD_AETHER_TECH, and SAY_TECH_END.
Referenced by Initialize().
HandleBashirSpawnEnemy()
void world_map_outland::HandleBashirSpawnEnemy () inline
Definition at line 836 of file world_outland.cpp.
References BASHIR_ACTION_SPAWN_ENEMY, GetActionTimer(), m_bashirPhaseSpawnData, TimerManager::ResetTimer(), and SpawnRandomBashirMob().
Referenced by Initialize().
HandleShartuulAddAttack()
void world_map_outland::HandleShartuulAddAttack () inline
Definition at line 1278 of file world_outland.cpp.
References Map::GetCreature(), GetCurrentDemon(), InstanceData::instance, m_shartuulAttackAdds, SHARTUUL_FACTION_HOSTILE, TEMPFACTION_RESTORE_REACH_HOME, TEMPFACTION_RESTORE_RESPAWN, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, and UNIT_FLAG_UNINTERACTIBLE.
Referenced by Initialize().
HandleShartuulAddSpawns()
void world_map_outland::HandleShartuulAddSpawns () inline
Definition at line 1180 of file world_outland.cpp.
References Unit::CastSpell(), DoScriptText(), Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetCurrentDemon(), ScriptedInstance::GetSingleCreatureFromStorage(), GetSpellIdForEntry(), InstanceData::instance, m_ignoredGuids, m_shartuulAttackAdds, m_shartuulPhase, m_shartuulWave, m_spawnPosition, NPC_FEL_IMP_DEFENDER, NPC_FELHOUND_DEFENDER, NPC_GANARG_UNDERLING, NPC_LEGION_RING_SHIELD_ZAPPER_INVISMAN, NPC_OVERSEER_SHARTUUL, NPC_SHIVAN_ASSASSIN, Position::o, PHASE_1_FELGUARD_DEGRADER_ADDS, PHASE_3_DOOMGUARD_PUNISHER_ADDS, PHASE_4_DOOMGUARD_PUNISHER_BOSS, ProgressShartuul(), TimerManager::ResetTimer(), SAY_FIRST_MOARG, SAY_FIRST_SPAWNS, SAY_LAST_MOARG, secondPhaseSpawns, SHARTUUL_ADD_ATTACK, SHARTUUL_PHASE_2_MAX_WAVE, SHARTUUL_SPAWN_ADDS, SPELL_SPAWN_LIGHTNING, TEMPSPAWN_TIMED_OOC_OR_CORPSE_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, urand(), Position::x, Position::y, and Position::z.
Referenced by Initialize().
HandleShartuulEventReset()
void world_map_outland::HandleShartuulEventReset () inline
Definition at line 1294 of file world_outland.cpp.
References AREAID_SHARTUUL_TRANSPORTER, CURRENT_CHANNELED_SPELL, Creature::ForcedDespawn(), Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetCurrentDemon(), Map::GetGameObject(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_JUST_DEACTIVATED, HIGHGUID_UNIT, InstanceData::instance, m_fires, m_playerGuid, m_shartuulEventActive, m_shartuulLargeAOI, m_shartuulPhase, m_shartuulShieldPercent, NPC_DOOMGUARD_PUNISHER, NPC_DREADMAW, NPC_EYE_OF_SHARTUUL, NPC_FEL_EYE_STALK, NPC_FEL_IMP_DEFENDER, NPC_FELGUARD_DEGRADER, NPC_FELHOUND_DEFENDER, NPC_GANARG_UNDERLING, NPC_LEGION_RING_EVENT_INVISMAN, NPC_MOARG_TORMENTER, NPC_SHARTUUL, NPC_SHIVAN_ASSASSIN, PHASE_0_SHARTUUL_DISABLED, pillarTargeting, Player::SendUpdateWorldState(), SPELL_LEGION_RING_EYE_STALK_TRANSFORM, sWorldState, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_FLAG_UNINTERACTIBLE, WORLD_STATE_SHARTUUL_EVENT_ACTIVE, and WORLD_STATE_SHARTUUL_SHIELD_REMAINING.
Referenced by ExecuteChatCommand(), Initialize(), SetData(), and Update().
HandleShartuulSpawnSequence()
void world_map_outland::HandleShartuulSpawnSequence () inline
Definition at line 1379 of file world_outland.cpp.
References AI_EVENT_CUSTOM_A, DoScriptText(), Map::GetCreature(), GetCurrentDemon(), GetCurrentPlayer(), ScriptedInstance::GetSingleCreatureFromStorage(), HIGHGUID_UNIT, InstanceData::instance, m_shartuulLargeAOI, m_shartuulSpawnSequenceStage, NPC_DREADMAW, NPC_EYE_OF_SHARTUUL, NPC_INVISIBLE_STALKER_LARGE_AOI, NPC_LEGION_RING_EVENT_INVISMAN_LG, NPC_OVERSEER_SHARTUUL, NPC_PORTABLE_FEL_CANNON, NPC_SHARTUUL, NPC_WARP_GATE_SHIELD_SHARTUUL, Position::o, POINT_SHARTUUL_FIGHT, TimerManager::ResetTimer(), SAY_DREADMAW_SPAWN, SAY_EYE_SPAWN, SHARTUUL_SPAWN_SEQUENCE, shartuulMovePosition, shartuulSpawnPosition, SPELL_BOSS_SHADOW_PORTAL_STATE, SPELL_COSMETIC_EREDAR_PRE_GATE_BEAM, SPELL_COSMETIC_LEGION_RING_EREDAR_LIGHTNING, SPELL_COSMETIC_LEGION_RING_PURPLE_LIGHTNING, SPELL_LEGION_RING_BEHOLDER_TRANSFORM, SPELL_LEGION_RING_DREADMAW_TRANSFORM, SPELL_TOUCH_OF_MADNESS, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_DESPAWN, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, Position::x, Position::y, and Position::z.
Referenced by Initialize().
Initialize()
void world_map_outland::Initialize () inline override virtual
Reimplemented from InstanceData.
Definition at line 295 of file world_outland.cpp.
References TimerManager::AddCustomAction(), AREAID_DEATHS_DOOR, BASHIR_ACTION_ENEMY_ATTACK, BASHIR_ACTION_INTRO, BASHIR_ACTION_OUTRO, BASHIR_ACTION_SPAWN_ENEMY, BASHIR_PHASE_NOT_ACTIVE, Map::GetVariableManager(), HandleBashirEnemyAttack(), HandleBashirOutro(), HandleBashirSpawnEnemy(), HandleShartuulAddAttack(), HandleShartuulAddSpawns(), HandleShartuulEventReset(), HandleShartuulSpawnSequence(), IN_MILLISECONDS, InstanceData::instance, m_bashirIntroStage, m_bashirPhase, m_bashirTime, m_bashirTimer, m_ignoredGuids, m_shadeData, m_shartuulEventActive, m_shartuulPhase, m_shartuulShieldPercent, m_shartuulTimer, m_uiEmissaryOfHate_KilledAddCount, m_uiRazaan_KilledAddCount, PHASE_0_SHARTUUL_DISABLED, ShadeOfTheHorsemanData::Reset(), ScriptAction(), secondPhaseSpawns, WorldStateVariableManager::SetVariable(), WorldStateVariableManager::SetVariableData(), SHARTUUL_ADD_ATTACK, SHARTUUL_EVENT_RESET, SHARTUUL_SPAWN_ADDS, SHARTUUL_SPAWN_SEQUENCE, WORLD_STATE_DEATHS_DOOR_EVENT_ACTIVE, WORLD_STATE_DEATHS_DOOR_NORTH_WARP_GATE_HEALTH, and WORLD_STATE_DEATHS_DOOR_SOUTH_WARP_GATE_HEALTH.
OnCreatureCreate()
void world_map_outland::OnCreatureCreate (Creature * creature) inline override virtual
Reimplemented from InstanceData.
Definition at line 1525 of file world_outland.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, Unit::GetCombatManager(), Map::GetCreature(), Object::GetEntry(), Object::GetObjectGuid(), InstanceData::instance, Creature::IsTemporarySummon(), m_apprentice, m_bashirEnemySpawns, m_bashirEnemyWaveSpawns, m_bashirSpawns, ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_AETHER_TECH_ADEPT, NPC_AETHER_TECH_APPRENTICE, NPC_AETHER_TECH_ASSISTANT, NPC_AETHER_TECH_MASTER, NPC_BASHIR_CONTROLLER, NPC_BASHIR_FLESH_FIEND, NPC_BASHIR_INQUISITOR, NPC_BASHIR_SUBPRIMAL, NPC_COSTUMED_ORPHAN_MATRON, NPC_DEATHS_DOOR_NORTH_WARP_GATE, NPC_DEATHS_DOOR_SOUTH_WARP_GATE, NPC_DISRUPTOR_TOWER, NPC_DOOMGUARD_PUNISHER, NPC_DREADMAW, NPC_EMISSARY_OF_HATE, NPC_EYE_OF_SHARTUUL, NPC_FEL_IMP_DEFENDER, NPC_FEL_PORTAL_ALARM, NPC_FELGUARD_DEGRADER, NPC_FELHOUND_DEFENDER, NPC_FURYWING, NPC_GANARG_UNDERLING, NPC_GRAND_COLLECTOR, NPC_GURTHOCK, NPC_INSIDION, NPC_LEGION_RING_EVENT_INVISMAN_LG, NPC_LEGION_RING_SHIELD_ZAPPER_INVISMAN, NPC_MASKED_ORPHAN_MATRON, NPC_MOARG_TORMENTER, NPC_MOGOR, NPC_OBSIDIA, NPC_OSCILLATING_FREQUENCY_SCANNER_BUNNY, NPC_OVERSEER_SHARTUUL, NPC_RIVENDARK, NPC_SHARTUUL, NPC_SHIVAN_ASSASSIN, NPC_SKYGUARD_AETHER_TECH, NPC_SKYGUARD_LIEUTENANT, NPC_SKYGUARD_RANGER, NPC_SKYGUARD_TARGET, NPC_SLAVERING_SLAVE, NPC_SOCRETHAR, NPC_VIMGOL_VISUAL_BUNNY, NPC_WARP_GATE_SHIELD_SHARTUUL, NPC_WHISPER_RAVEN_GOD_TEMPLATE, NPC_WYRM_FROM_BEYOND, NPC_YSIEL_WINDSINGER, PHASE_0_SHARTUUL_DISABLED, UnitAI::SendAIEvent(), WorldObject::SetActiveObjectState(), Object::SetFlag(), CombatManager::SetLeashingDisable(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_PLAYER.
OnCreatureDeath()
void world_map_outland::OnCreatureDeath (Creature * creature) inline override virtual
Reimplemented from InstanceData.
Definition at line 1693 of file world_outland.cpp.
References aSpawnLocations, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, FinishPhase(), Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), HandleBashirMobDeath(), m_bashirEnemyWaveSpawns, m_deadTowerCounter, m_lastRingOfBlood, m_uiEmissaryOfHate_KilledAddCount, NPC_BASHIR_CONTROLLER, NPC_BASHIR_FLESH_FIEND, NPC_BASHIR_RECKONER, NPC_BASHIR_SUBPRIMAL, NPC_BROKENTOE, NPC_DISRUPTOR_TOWER, NPC_EMISSARY_OF_HATE, NPC_FEL_EYE_STALK, NPC_GRAND_COLLECTOR, NPC_GURTHOCK, NPC_IRESPEAKER, NPC_MOGOR, NPC_MURKBLOOD_TWIN, NPC_ROKDAR, NPC_SKRAGATH, NPC_SKYGUARD_TARGET, NPC_SLAVERING_SLAVE, NPC_UNLEASHED_HELLION, NPC_WARMAUL_CHAMPION, POS_IDX_EMISSARY_SPAWN, Unit::RemoveAurasDueToSpell(), sLog, SPELL_LEGION_RING_EYE_STALK_TRANSFORM, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
OnCreatureDespawn()
void world_map_outland::OnCreatureDespawn (Creature * creature) inline override virtual
Reimplemented from InstanceData.
Definition at line 1676 of file world_outland.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), m_lastRingOfBlood, NPC_BROKENTOE, NPC_GURTHOCK, NPC_MOGOR, NPC_MURKBLOOD_TWIN, NPC_ROKDAR, NPC_SKRAGATH, NPC_WARMAUL_CHAMPION, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
OnCreatureEvade()
void world_map_outland::OnCreatureEvade (Creature * creature) inline override virtual
Reimplemented from InstanceData.
Definition at line 1661 of file world_outland.cpp.
References Creature::ForcedDespawn(), Object::GetEntry(), NPC_BROKENTOE, NPC_MOGOR, NPC_MURKBLOOD_TWIN, NPC_ROKDAR, NPC_SKRAGATH, and NPC_WARMAUL_CHAMPION.
OnCreatureRespawn()
void world_map_outland::OnCreatureRespawn (Creature * creature) inline override virtual
Reimplemented from InstanceData.
Definition at line 1610 of file world_outland.cpp.
References Creature::AI(), Unit::CastSpell(), DIST_CALC_NONE, GetClosestGameObjectWithEntry(), Unit::GetCombatManager(), WorldObject::GetDistance(), Object::GetEntry(), Object::GetObjectGuid(), Creature::GetRespawnPosition(), GO_SALVAGED_ETHEREUM_PRISON, Creature::IsTemporarySummon(), m_lastRingOfBlood, m_shartuulLargeAOI, m_shartuulPhase, m_spawnPosition, NPC_BROKENTOE, NPC_DOOMGUARD_PUNISHER, NPC_ETHEREUM_PRISONER, NPC_FEL_EYE_STALK, NPC_INVISIBLE_STALKER_LARGE_AOI, NPC_MOGOR, NPC_MURKBLOOD_TWIN, NPC_ROKDAR, NPC_SKRAGATH, NPC_WARMAUL_CHAMPION, NPC_WARP_GATE_SHIELD_SHARTUUL, PHASE_7_SHIVAN_ASSASSIN_BOSS_3, REACT_PASSIVE, Object::RemoveFlag(), Unit::SetCanEnterCombat(), Creature::SetCorpseDelay(), CombatManager::SetLeashingCheck(), UnitAI::SetReactState(), SHARTUUL_FACTION_HOSTILE, SPELL_BOSS_FEL_PORTAL_STATE, SPELL_LEGION_RING_EYE_STALK_TRANSFORM, TEMPFACTION_RESTORE_REACH_HOME, TEMPFACTION_RESTORE_RESPAWN, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, and UNIT_FLAG_UNINTERACTIBLE.
OnObjectCreate()
void world_map_outland::OnObjectCreate (GameObject * go) inline override virtual
Reimplemented from InstanceData.
Definition at line 1748 of file world_outland.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), GO_BASHIR_CRYSTALFORGE, GO_HALAA_BANNER, GO_ROCKET_FIRE, GO_ROCKET_SMOKE, GO_WARP_GATE_FIRE_BIG, GO_WARP_GATE_FIRE_SMALL, m_fires, ScriptedInstance::m_goEntryGuidCollection, and ScriptedInstance::m_goEntryGuidStore.
ProgressShartuul()
void world_map_outland::ProgressShartuul (ShartuulPhases phase) inline
Definition at line 1050 of file world_outland.cpp.
References AI_EVENT_CUSTOM_A, AREAID_SHARTUUL_TRANSPORTER, TimerManager::DisableTimer(), DoScriptText(), Unit::GetCharmer(), Map::GetCreature(), GetCurrentDemon(), Map::GetGameObject(), Object::GetObjectGuid(), ScriptedInstance::GetSingleCreatureFromStorage(), GO_READY, HIGHGUID_UNIT, InstanceData::instance, m_fires, m_playerGuid, m_shartuulEventActive, m_shartuulPhase, m_shartuulShieldPercent, m_shartuulSpawnSequenceStage, m_shartuulWave, NPC_DOOMGUARD_PUNISHER, NPC_LEGION_RING_EVENT_INVISMAN, NPC_OVERSEER_SHARTUUL, NPC_SHIVAN_ASSASSIN, NPC_WARP_GATE_SHIELD_SHARTUUL, PHASE_1_FELGUARD_DEGRADER_ADDS, PHASE_2_FELGUARD_DEGRADER_BOSS, PHASE_3_DOOMGUARD_PUNISHER_ADDS, PHASE_4_DOOMGUARD_PUNISHER_BOSS, PHASE_5_SHIVAN_ASSASSIN_BOSS_1, PHASE_6_SHIVAN_ASSASSIN_BOSS_2, PHASE_7_SHIVAN_ASSASSIN_BOSS_3, pillarTargeting, TimerManager::ResetTimer(), SAY_AGGRO_SHIVAN, SAY_DREADMAW_DEATH, SAY_FIRST_HAMMER, SAY_LAST_HAMMER, SAY_SHARTUUL_START, Player::SendUpdateWorldState(), SHARTUUL_SPAWN_ADDS, SHARTUUL_SPAWN_SEQUENCE, SPELL_COSMETIC_LEGION_RING_GREEN_MATTER, SPELL_COSMETIC_VISUAL_SHELL_SHIELD, SPELL_LEGION_RING_SHIELD_EXPLODE, sWorldState, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, WORLD_STATE_SHARTUUL_EVENT_ACTIVE, and WORLD_STATE_SHARTUUL_SHIELD_REMAINING.
Referenced by HandleShartuulAddSpawns(), and SetData().
ScriptAction()
void world_map_outland::ScriptAction (uint32 eventId) inline
Definition at line 914 of file world_outland.cpp.
References BASHIR_ACTION_INTRO, DoScriptText(), Map::GetCreature(), ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetIntroTimer(), Unit::GetMotionMaster(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, m_bashirIntroStage, Unit::Mount(), MOUNT_NETHER_RAY_DISPLAY_ID, MotionMaster::MovePoint(), MotionMaster::MoveWaypoint(), NPC_SKYGUARD_AETHER_TECH, NPC_SKYGUARD_LIEUTENANT, NPC_SKYGUARD_RANGER, PATH_ID_BIG_PATH, TimerManager::ResetTimer(), SAY_LIEUTENANT_1, SAY_LIEUTENANT_2, SAY_LIEUTENANT_3, SAY_LIEUTENANT_4, SAY_LIEUTENANT_5, SAY_LIEUTENANT_6, SAY_RANGER_1, Unit::SetFacingTo(), Object::SetFlag(), Unit::SetHover(), WorldObject::SetOrientation(), Creature::SetWalk(), UNIT_FIELD_FLAGS, and UNIT_FLAG_IMMUNE_TO_NPC.
Referenced by Initialize().
SetData()
void world_map_outland::SetData (uint32 type, uint32 data) inline override virtual
Reimplemented from InstanceData.
Definition at line 340 of file world_outland.cpp.
References AREAID_SHARTUUL_TRANSPORTER, BASHIR_PHASE_1, BASHIR_PHASE_NOT_ACTIVE, DespawnCrystalforgeGuardians(), ScriptedInstance::DespawnGuids(), DoScriptText(), EVENT_DOOMGUARD_PUNISHER_DEATH, EVENT_DREADMAW_DEATH, EVENT_EYE_OF_SHARTUUL_DEATH, EVENT_FAIL, EVENT_SHARTUUL_DEATH, EVENT_SHIVAN_ASSASSIN_DEATH, EVENT_SMASH_SHIELD, EVENT_START, ScriptedInstance::GetCreatureGuidVectorFromStorage(), GetCurrentDemon(), ScriptedInstance::GetSingleCreatureFromStorage(), Map::GetVariableManager(), ShadeOfTheHorsemanData::HandleSetData(), HandleShartuulEventReset(), InstanceData::instance, m_bashirPhase, m_lastRingOfBlood, m_shadeData, m_shartuulShieldPercent, NPC_GURTHOCK, NPC_MOGOR, NPC_OVERSEER_SHARTUUL, NPC_SKYGUARD_TARGET, PHASE_1_FELGUARD_DEGRADER_ADDS, PHASE_2_FELGUARD_DEGRADER_BOSS, PHASE_3_DOOMGUARD_PUNISHER_ADDS, PHASE_5_SHIVAN_ASSASSIN_BOSS_1, PHASE_6_SHIVAN_ASSASSIN_BOSS_2, PHASE_7_SHIVAN_ASSASSIN_BOSS_3, ProgressShartuul(), TimerManager::ResetTimer(), SAY_FIFTH_HAMMER, SAY_SECOND_HAMMER, Player::SendUpdateWorldState(), WorldStateVariableManager::SetVariable(), SHARTUUL_EVENT_RESET, StartPhase(), sWorldState, TYPE_BASHIR, TYPE_DEATHS_DOOR_NORTH, TYPE_DEATHS_DOOR_SOUTH, TYPE_MOGOR, TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, TYPE_SHADE_OF_THE_HORSEMAN_MAX, TYPE_SHARTUUL, TYPE_TEROKK, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, WORLD_STATE_DEATHS_DOOR_NORTH_WARP_GATE_HEALTH, WORLD_STATE_DEATHS_DOOR_SOUTH_WARP_GATE_HEALTH, and WORLD_STATE_SHARTUUL_SHIELD_REMAINING.
ShowChatCommands()
void world_map_outland::ShowChatCommands (ChatHandler * handler) inline override virtual
Reimplemented from InstanceData.
Definition at line 1830 of file world_outland.cpp.
References ChatHandler::SendSysMessage().
SpawnAlliesAtCrystalforge()
void world_map_outland::SpawnAlliesAtCrystalforge (BashirPhases phaseId, Player * player) inline
Definition at line 543 of file world_outland.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, BASHIR_PHASE_2, BASHIR_PHASE_3, BASHIR_PHASE_ALL_VENDORS_SPAWNED, BASHIR_PHASE_TRANSITION_2, BASHIR_PHASE_TRANSITION_3, bashirCustomSpawnPositions, EMOTE_STATE_USESTANDING, EMOTE_STATE_USESTANDING_NOSHEATHE, Unit::HandleEmote(), NPC_AETHER_TECH_ADEPT, NPC_AETHER_TECH_ASSISTANT, NPC_AETHER_TECH_MASTER, NPC_SKYGUARD_AETHER_TECH, NPC_SKYGUARD_LIEUTENANT, NPC_SKYGUARD_RANGER, UnitAI::SendAIEvent(), Unit::SetCanFly(), WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by StartBashirAtCustomSpot().
SpawnBoss()
void world_map_outland::SpawnBoss (BashirPhases phase) inline
Definition at line 777 of file world_outland.cpp.
References BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, bashirSpawnPositions, Unit::CastSpell(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, NPC_BASHIR_FLESH_FIEND, NPC_DISRUPTOR_TOWER, NPC_GRAND_COLLECTOR, NPC_SKYGUARD_AETHER_TECH, SpawnTowerDefenders(), SPELL_SPIRIT_SPAWN_IN, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_TIMED_DESPAWN, and TRIGGERED_NONE.
Referenced by HandleBashirMobDeath().
SpawnRandomBashirMob()
void world_map_outland::SpawnRandomBashirMob () inline
Definition at line 614 of file world_outland.cpp.
References BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, Unit::CastSpell(), ScriptedInstance::GetSingleCreatureFromStorage(), m_bashirPhaseSpawnData, m_bashirPhaseSpawnDataUsed, NPC_BASHIR_CONTROLLER, NPC_BASHIR_RECKONER, NPC_BASHIR_SUBPRIMAL, NPC_SKYGUARD_AETHER_TECH, NPC_SLAVERING_SLAVE, BashirCombatSpawn::ori, BashirCombatSpawn::phaseId, SPELL_ETHEREAL_TELEPORT, SPELL_SPIRIT_SPAWN_IN, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_NONE, urand(), BashirCombatSpawn::x, BashirCombatSpawn::y, and BashirCombatSpawn::z.
Referenced by HandleBashirMobDeath(), HandleBashirSpawnEnemy(), and StartBattlePhase().
SpawnTowerDefenders()
void world_map_outland::SpawnTowerDefenders () inline
Definition at line 641 of file world_outland.cpp.
References bashirCombatDisruptorSpawnLocations, Unit::CastSpell(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_BASHIR_SUBPRIMAL, NPC_SKYGUARD_AETHER_TECH, SPELL_SPIRIT_SPAWN_IN, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TRIGGERED_NONE.
Referenced by SpawnBoss().
StartBashirAtCustomSpot()
void world_map_outland::StartBashirAtCustomSpot (BashirPhases phaseId, Player * player) inline
Definition at line 578 of file world_outland.cpp.
References DespawnCrystalforgeGuardians(), SpawnAlliesAtCrystalforge(), and StartPhase().
Referenced by ExecuteChatCommand().
StartBashirLandingEvent()
void world_map_outland::StartBashirLandingEvent () inline
Definition at line 525 of file world_outland.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, BASHIR_ACTION_INTRO, BASHIR_PHASE_START, bashirSpawnPositions, GetIntroTimer(), m_apprentice, m_bashirIntroStage, m_bashirPhase, m_deadTowerCounter, NPC_SKYGUARD_AETHER_TECH, NPC_SKYGUARD_LIEUTENANT, NPC_SKYGUARD_RANGER, TimerManager::ResetTimer(), UnitAI::SendAIEvent(), WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by ExecuteChatCommand(), and Update().
StartBattlePhase()
void world_map_outland::StartBattlePhase () inline
Definition at line 700 of file world_outland.cpp.
References BASHIR_ACTION_ENEMY_ATTACK, BASHIR_ACTION_SPAWN_ENEMY, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, bashirCombatSpawnLocations, GetActionTimer(), m_bashirEnemySpawns, m_bashirEnemyWaveSpawns, m_bashirPhase, m_bashirPhaseSpawnData, PHASE_1_INITIAL_SPAWN_COUNT, PHASE_2_INITIAL_SPAWN_COUNT, PHASE_3_INITIAL_SPAWN_COUNT, TimerManager::ResetTimer(), and SpawnRandomBashirMob().
Referenced by StartPhase().
StartManaSlaveEvent()
void world_map_outland::StartManaSlaveEvent () inline
Definition at line 829 of file world_outland.cpp.
References CRYSTALFORGE_SLAVE_EVENT_CONTROLLER_ENTRY, CRYSTALFORGE_SLAVE_EVENT_RELAY_ID, GetClosestCreatureWithEntry(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_BASHIR_CRYSTALFORGE, InstanceData::instance, SCRIPT_TYPE_RELAY, and Map::ScriptsStart().
Referenced by Update().
StartPhase()
void world_map_outland::StartPhase (BashirPhases phase) inline
Definition at line 755 of file world_outland.cpp.
References BASHIR_ACTION_OUTRO, BASHIR_PHASE_1, BASHIR_PHASE_2, BASHIR_PHASE_3, BASHIR_PHASE_ALL_VENDORS_SPAWNED, BASHIR_PHASE_TRANSITION_1, BASHIR_PHASE_TRANSITION_2, BASHIR_PHASE_TRANSITION_3, IN_MILLISECONDS, m_bashirPhase, TimerManager::ResetTimer(), StartBattlePhase(), and StartTransitionPhase().
Referenced by FinishPhase(), SetData(), and StartBashirAtCustomSpot().
StartTransitionPhase()
void world_map_outland::StartTransitionPhase () inline
Definition at line 734 of file world_outland.cpp.
References Creature::AI(), AI_EVENT_CUSTOM_A, BASHIR_PHASE_TRANSITION_1, BASHIR_PHASE_TRANSITION_2, BASHIR_PHASE_TRANSITION_3, bashirSpawnPositions, ScriptedInstance::GetSingleCreatureFromStorage(), m_bashirPhase, Unit::Mount(), MOUNT_NETHER_RAY_DISPLAY_ID, NPC_AETHER_TECH_ADEPT, NPC_AETHER_TECH_ASSISTANT, NPC_AETHER_TECH_MASTER, NPC_SKYGUARD_AETHER_TECH, UnitAI::SendAIEvent(), WorldObject::SummonCreature(), and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by StartPhase().
Update()
void world_map_outland::Update (const uint32 diff) inline override virtual
Reimplemented from InstanceData.
Definition at line 1768 of file world_outland.cpp.
References AREAID_SKYGUARD_OUTPOST, BASHIR_PHASE_NOT_ACTIVE, CalculateBashirTimerValue(), Unit::GetCharmer(), GetCurrentDemon(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), HandleShartuulEventReset(), IN_MILLISECONDS, Unit::IsAlive(), m_bashirPhase, m_bashirTime, m_bashirTimer, m_shartuulPhase, m_shartuulTimer, PHASE_0_SHARTUUL_DISABLED, PHASE_1_FELGUARD_DEGRADER_ADDS, PHASE_3_DOOMGUARD_PUNISHER_ADDS, Player::SendUpdateWorldState(), StartBashirLandingEvent(), StartManaSlaveEvent(), sWorldState, TimerManager::UpdateTimers(), and WORLD_STATE_BASHIR_TIMER_WOTLK.
Field Documentation
m_apprentice
Creature* world_map_outland::m_apprentice
Definition at line 286 of file world_outland.cpp.
Referenced by OnCreatureCreate(), and StartBashirLandingEvent().
m_bashirEnemySpawns
GuidVector world_map_outland::m_bashirEnemySpawns
Definition at line 284 of file world_outland.cpp.
Referenced by DespawnBashir(), FinishPhase(), OnCreatureCreate(), and StartBattlePhase().
m_bashirEnemyWaveSpawns
GuidVector world_map_outland::m_bashirEnemyWaveSpawns
Definition at line 285 of file world_outland.cpp.
Referenced by HandleBashirEnemyAttack(), OnCreatureCreate(), OnCreatureDeath(), and StartBattlePhase().
m_bashirIntroStage
uint32 world_map_outland::m_bashirIntroStage
Definition at line 287 of file world_outland.cpp.
Referenced by Initialize(), ScriptAction(), and StartBashirLandingEvent().
m_bashirKillCounter
uint32 world_map_outland::m_bashirKillCounter
Definition at line 289 of file world_outland.cpp.
Referenced by HandleBashirMobDeath().
m_bashirPhase
BashirPhases world_map_outland::m_bashirPhase
Definition at line 282 of file world_outland.cpp.
Referenced by CheckConditionCriteriaMeet(), DespawnBashir(), GetActionTimer(), HandleBashirEnemyAttack(), HandleBashirMobDeath(), Initialize(), SetData(), StartBashirLandingEvent(), StartBattlePhase(), StartPhase(), StartTransitionPhase(), and Update().
m_bashirPhaseSpawnData
std::vector<BashirCombatSpawn*> world_map_outland::m_bashirPhaseSpawnData
Definition at line 290 of file world_outland.cpp.
Referenced by HandleBashirMobDeath(), HandleBashirSpawnEnemy(), SpawnRandomBashirMob(), and StartBattlePhase().
m_bashirPhaseSpawnDataUsed
std::vector<BashirCombatSpawn*> world_map_outland::m_bashirPhaseSpawnDataUsed
Definition at line 291 of file world_outland.cpp.
Referenced by HandleBashirMobDeath(), and SpawnRandomBashirMob().
m_bashirSpawns
GuidVector world_map_outland::m_bashirSpawns
Definition at line 283 of file world_outland.cpp.
Referenced by DespawnBashir(), and OnCreatureCreate().
m_bashirTime
std::tm world_map_outland::m_bashirTime
Definition at line 280 of file world_outland.cpp.
Referenced by CalculateBashirTimerValue(), Initialize(), and Update().
m_bashirTimer
uint32 world_map_outland::m_bashirTimer
Definition at line 281 of file world_outland.cpp.
Referenced by Initialize(), and Update().
m_deadTowerCounter
uint32 world_map_outland::m_deadTowerCounter
Definition at line 288 of file world_outland.cpp.
Referenced by OnCreatureDeath(), and StartBashirLandingEvent().
m_fires
GuidVector world_map_outland::m_fires
Definition at line 277 of file world_outland.cpp.
Referenced by HandleShartuulEventReset(), OnObjectCreate(), and ProgressShartuul().
m_ignoredGuids
std::set<ObjectGuid> world_map_outland::m_ignoredGuids
Definition at line 276 of file world_outland.cpp.
Referenced by HandleShartuulAddSpawns(), and Initialize().
m_lastRingOfBlood
ObjectGuid world_map_outland::m_lastRingOfBlood
Definition at line 264 of file world_outland.cpp.
Referenced by ExecuteChatCommand(), OnCreatureDeath(), OnCreatureDespawn(), OnCreatureRespawn(), and SetData().
m_playerGuid
ObjectGuid world_map_outland::m_playerGuid
Definition at line 275 of file world_outland.cpp.
Referenced by GetCurrentPlayer(), HandleShartuulEventReset(), and ProgressShartuul().
m_shadeData
ShadeOfTheHorsemanData world_map_outland::m_shadeData
Definition at line 293 of file world_outland.cpp.
Referenced by CheckConditionCriteriaMeet(), GetData(), Initialize(), and SetData().
m_shartuulAttackAdds
GuidVector world_map_outland::m_shartuulAttackAdds
Definition at line 270 of file world_outland.cpp.
Referenced by HandleShartuulAddAttack(), and HandleShartuulAddSpawns().
m_shartuulEventActive
uint32 world_map_outland::m_shartuulEventActive
Definition at line 267 of file world_outland.cpp.
Referenced by FillInitialWorldStates(), HandleShartuulEventReset(), Initialize(), and ProgressShartuul().
m_shartuulLargeAOI
ObjectGuid world_map_outland::m_shartuulLargeAOI
Definition at line 274 of file world_outland.cpp.
Referenced by HandleShartuulEventReset(), HandleShartuulSpawnSequence(), and OnCreatureRespawn().
m_shartuulPhase
ShartuulPhases world_map_outland::m_shartuulPhase
Definition at line 269 of file world_outland.cpp.
Referenced by GetCurrentDemon(), HandleShartuulAddSpawns(), HandleShartuulEventReset(), Initialize(), OnCreatureRespawn(), ProgressShartuul(), and Update().
m_shartuulShieldPercent
uint32 world_map_outland::m_shartuulShieldPercent
Definition at line 268 of file world_outland.cpp.
Referenced by FillInitialWorldStates(), HandleShartuulEventReset(), Initialize(), ProgressShartuul(), and SetData().
m_shartuulSpawnSequenceStage
uint32 world_map_outland::m_shartuulSpawnSequenceStage
Definition at line 273 of file world_outland.cpp.
Referenced by HandleShartuulSpawnSequence(), and ProgressShartuul().
m_shartuulTimer
uint32 world_map_outland::m_shartuulTimer
Definition at line 278 of file world_outland.cpp.
Referenced by Initialize(), and Update().
m_shartuulWave
uint32 world_map_outland::m_shartuulWave
Definition at line 271 of file world_outland.cpp.
Referenced by HandleShartuulAddSpawns(), and ProgressShartuul().
m_spawnPosition
Position world_map_outland::m_spawnPosition
Definition at line 272 of file world_outland.cpp.
Referenced by HandleShartuulAddSpawns(), and OnCreatureRespawn().
m_uiEmissaryOfHate_KilledAddCount
uint8 world_map_outland::m_uiEmissaryOfHate_KilledAddCount
Definition at line 261 of file world_outland.cpp.
Referenced by Initialize(), and OnCreatureDeath().
m_uiRazaan_KilledAddCount
uint8 world_map_outland::m_uiRazaan_KilledAddCount
Definition at line 262 of file world_outland.cpp.
Referenced by Initialize().
The documentation for this struct was generated from the following file:
world_outland.cpp