CMaNGOS_WoTLK: world_map_kalimdor Struct Reference
world_map_kalimdor Struct Reference
Public Member Functions
world_map_kalimdor (Map *pMap)
void Initialize () override
bool CheckConditionCriteriaMeet (Player const *player, uint32 instanceConditionId, WorldObject const *conditionSource, uint32 conditionSourceType) const override
void OnCreatureCreate (Creature *pCreature) override
void OnCreatureDeath (Creature *pCreature) override
void OnObjectCreate (GameObject *pGo) override
void DoDespawnElementalRifts (uint8 index)
bool GhostOPlasmEventStep (GhostOPlasmEvent &eventData)
void Update (uint32 diff) override
void SetData (uint32 uiType, uint32 uiData)
uint32 GetData (uint32 type) const override
void OnEventHappened (uint16 event_id, bool activate, bool) override
Public Member Functions inherited from ScriptedMap
ScriptedMap (Map *map)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
void DoStartTimedAchievement (AchievementCriteriaTypes criteriaType, uint32 uiTimedCriteriaMiscId)
Helper function to start a timed achievement criteria for players in the map.
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
virtual void Load (const char *)
virtual const char * Save () const
void SaveToDB () const
virtual bool IsEncounterInProgress () const
virtual void OnPlayerEnter (Player *)
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureRespawn (Creature *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckAchievementCriteriaMeet (uint32 criteria_id, Player const *source, Unit const *target=nullptr, uint32 miscvalue1=0) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
void SendEncounterFrame (uint32 type, ObjectGuid sourceGuid=ObjectGuid(), uint8 param1=0, uint8 param2=0) const
Data Fields
uint8 m_uiMurkdeepAdds_KilledAddCount
std::vector< GhostOPlasmEvent > m_vGOEvents
uint32 m_uiOmenResetTimer
uint32 m_uiOmenMoonlightTimer
uint8 m_uiRocketsCounter
uint32 m_encounter [MAX_ENCOUNTER]
bool b_isOmenSpellCreditDone
std::array< std::vector< ObjectGuid >, MAX_ELEMENTS > m_aElementalRiftGUIDs
uint32 m_uiDronesTimer
uint32 m_freedSpriteDarter
ShadeOfTheHorsemanData m_shadeData
BrewfestEvent m_brewfestEvent
Data Fields inherited from InstanceData
Map * instance
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Detailed Description
Definition at line 38 of file world_kalimdor.cpp.
Constructor & Destructor Documentation
world_map_kalimdor()
world_map_kalimdor::world_map_kalimdor (Map * pMap) inline
Definition at line 40 of file world_kalimdor.cpp.
References AREAID_RAZOR_HILL.
Member Function Documentation
CheckConditionCriteriaMeet()
bool world_map_kalimdor::CheckConditionCriteriaMeet (Player const * player, uint32 instanceConditionId, WorldObject const * conditionSource, uint32 conditionSourceType) const inline override virtual
Reimplemented from InstanceData.
Definition at line 77 of file world_kalimdor.cpp.
References WorldObject::GetAreaId(), Object::GetGuidStr(), INSTANCE_CONDITION_ID_FIRE_BRIGADE_PRACTICE_GOLDSHIRE, INSTANCE_CONDITION_ID_LET_THE_FIRES_COME_HORDE, ShadeOfTheHorsemanData::IsConditionFulfilled(), m_shadeData, and script_error_log().
DoDespawnElementalRifts()
void world_map_kalimdor::DoDespawnElementalRifts (uint8 index) inline
Definition at line 232 of file world_kalimdor.cpp.
References Map::GetGameObject(), GO_JUST_DEACTIVATED, InstanceData::instance, and m_aElementalRiftGUIDs.
Referenced by OnCreatureDeath().
GetData()
uint32 world_map_kalimdor::GetData (uint32 type) const inline override virtual
Reimplemented from InstanceData.
Definition at line 447 of file world_kalimdor.cpp.
References ShadeOfTheHorsemanData::HandleGetData(), m_encounter, m_shadeData, TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, and TYPE_SHADE_OF_THE_HORSEMAN_MAX.
Referenced by SetData(), and Update().
GhostOPlasmEventStep()
bool world_map_kalimdor::GhostOPlasmEventStep (GhostOPlasmEvent & eventData) inline
Definition at line 243 of file world_kalimdor.cpp.
References GhostOPlasmEvent::despawnTimer, Map::GetCreature(), Map::GetGameObject(), Map::GetHeightInRange(), Unit::GetMotionMaster(), Object::GetObjectGuid(), Map::GetReachableRandomPointOnGround(), GhostOPlasmEvent::guid, InstanceData::instance, MotionMaster::MovePoint(), NPC_MAGRAMI_SPECTRE, GhostOPlasmEvent::phaseCounter, SPELL_SPIRIT_SPAWN_OUT, WorldObject::SummonCreature(), GhostOPlasmEvent::summonedMagrami, TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by Update().
Initialize()
void world_map_kalimdor::Initialize () inline override virtual
Reimplemented from InstanceData.
Definition at line 57 of file world_kalimdor.cpp.
References AREAID_THERAMORE_ISLE, b_isOmenSpellCreditDone, Map::GetVariableManager(), InstanceData::instance, m_aElementalRiftGUIDs, m_encounter, m_freedSpriteDarter, m_shadeData, m_uiDronesTimer, m_uiMurkdeepAdds_KilledAddCount, m_uiOmenMoonlightTimer, m_uiOmenResetTimer, m_uiRocketsCounter, m_vGOEvents, ShadeOfTheHorsemanData::Reset(), WorldStateVariableManager::SetVariableData(), WORLD_STATE_TETHYR_COUNT, and WORLD_STATE_TETHYR_SHOW.
OnCreatureCreate()
void world_map_kalimdor::OnCreatureCreate (Creature * pCreature) inline override virtual
Reimplemented from InstanceData.
Definition at line 87 of file world_kalimdor.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), ScriptedInstance::m_npcEntryGuidCollection, ScriptedInstance::m_npcEntryGuidStore, NPC_AVALANCHION, NPC_BARON_CHARR, NPC_BLIX_FIXWIDGET, NPC_DARK_IRON_HERALD, NPC_DROHNS_DISTILLERY_BARKER, NPC_FREZZA, NPC_GORDOK_BREW_BARKER_H, NPC_GREEB_RAMROCKET, NPC_HIGHLORD_KRUUL, NPC_HORNIZZ, NPC_KRENDLE_BIGPOCKETS, NPC_MURKDEEP, NPC_NECROPOLIS_HEALTH, NPC_OMEN, NPC_PRINCESS_TEMPESTRIA, NPC_SNURK_BUCKSQUICK, NPC_TAPPER_SWINDLEKEG, NPC_TCHALIS_VOODOO_BREWERY_BARKER, NPC_THE_WINDREAVER, NPC_VOLJIN, and NPC_ZELLI_HOTNOZZLE.
OnCreatureDeath()
void world_map_kalimdor::OnCreatureDeath (Creature * pCreature) inline override virtual
Reimplemented from InstanceData.
Definition at line 119 of file world_kalimdor.cpp.
References aSpawnLocations, DoDespawnElementalRifts(), DONE, ELEMENTAL_AIR, ELEMENTAL_EARTH, ELEMENTAL_FIRE, ELEMENTAL_WATER, Object::GetEntry(), Object::GetObjectGuid(), WorldObject::GetRandomPoint(), InstanceData::instance, Creature::IsTemporarySummon(), ScriptedInstance::m_npcEntryGuidCollection, m_uiMurkdeepAdds_KilledAddCount, NPC_AVALANCHION, NPC_BARON_CHARR, NPC_COLOSSUS_OF_ASHI, NPC_COLOSSUS_OF_REGAL, NPC_COLOSSUS_OF_ZORA, NPC_GREYMIST_COASTRUNNNER, NPC_GREYMIST_HUNTER, NPC_GREYMIST_WARRIOR, NPC_MURKDEEP, NPC_NECROPOLIS_HEALTH, NPC_OMEN, NPC_PRINCESS_TEMPESTRIA, NPC_THE_WINDREAVER, POS_IDX_MURKDEEP_MOVE, POS_IDX_MURKDEEP_SPAWN, SetData(), WorldObject::SpawnCreature(), WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_OMEN.
OnEventHappened()
void world_map_kalimdor::OnEventHappened (uint16 event_id, bool activate, bool) inline override virtual
Reimplemented from InstanceData.
Definition at line 454 of file world_kalimdor.cpp.
References GAME_EVENT_BREWFEST_DARK_IRON_ATTACK, GAME_EVENT_BREWFEST_KEG_TAPPING, m_brewfestEvent, BrewfestEvent::StartDarkIronAttackEvent(), and BrewfestEvent::StartKegTappingEvent().
OnObjectCreate()
void world_map_kalimdor::OnObjectCreate (GameObject * pGo) inline override virtual
Reimplemented from InstanceData.
Definition at line 203 of file world_kalimdor.cpp.
References ELEMENTAL_AIR, ELEMENTAL_EARTH, ELEMENTAL_FIRE, ELEMENTAL_WATER, Object::GetEntry(), Object::GetObjectGuid(), GO_AIR_RIFT, GO_EARTH_RIFT, GO_FIRE_RIFT, GO_GHOST_MAGNET, GO_ROCKET_CLUSTER, GO_SUMMON_CIRCLE, GO_WATER_RIFT, m_aElementalRiftGUIDs, ScriptedInstance::m_goEntryGuidCollection, ScriptedInstance::m_goEntryGuidStore, m_vGOEvents, and WorldObject::SetActiveObjectState().
SetData()
void world_map_kalimdor::SetData (uint32 uiType, uint32 uiData) inline virtual
Reimplemented from InstanceData.
Definition at line 352 of file world_kalimdor.cpp.
References AREAID_THERAMORE_ISLE, aSpawnLocations, DONE, GetData(), ScriptedInstance::GetSingleGameObjectFromStorage(), WorldStateVariableManager::GetVariable(), Map::GetVariableManager(), GO_ROCKET_CLUSTER, ShadeOfTheHorsemanData::HandleSetData(), IN_MILLISECONDS, IN_PROGRESS, InstanceData::instance, m_encounter, m_freedSpriteDarter, m_shadeData, m_uiDronesTimer, m_uiOmenMoonlightTimer, m_uiOmenResetTimer, m_uiRocketsCounter, MAX_ROCKETS, MINUTE, NOT_STARTED, NPC_MINION_OMEN, NPC_OMEN, POS_IDX_MINION_OMEN_START, POS_IDX_MINION_OMEN_STOP, POS_IDX_OMEN_MOVE, POS_IDX_OMEN_SPAWN, WorldStateVariableManager::SetVariable(), Map::SetZoneWeather(), SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN, TYPE_FREEDOM_CREATURES, TYPE_GONG_TIME, TYPE_HIVE, TYPE_OMEN, TYPE_SHADE_OF_THE_HORSEMAN_ATTACK_PHASE, TYPE_SHADE_OF_THE_HORSEMAN_MAX, TYPE_TETHYR, urand(), WORLD_STATE_TETHYR_COUNT, and WORLD_STATE_TETHYR_SHOW.
Referenced by OnCreatureDeath(), and Update().
Update()
void world_map_kalimdor::Update (uint32 diff) inline override virtual
Reimplemented from InstanceData.
Definition at line 285 of file world_kalimdor.cpp.
References b_isOmenSpellCreditDone, DONE, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), GhostOPlasmEventStep(), HOLIDAY_BREWFEST, m_brewfestEvent, m_encounter, m_uiDronesTimer, m_uiOmenMoonlightTimer, m_uiOmenResetTimer, m_uiRocketsCounter, m_vGOEvents, NOT_STARTED, NPC_OMEN, SetData(), sGameEventMgr, SPELL_OMEN_MOONLIGHT, TRIGGERED_OLD_TRIGGERED, TYPE_HIVE, TYPE_OMEN, and BrewfestEvent::Update().
Field Documentation
b_isOmenSpellCreditDone
bool world_map_kalimdor::b_isOmenSpellCreditDone
Definition at line 48 of file world_kalimdor.cpp.
Referenced by Initialize(), and Update().
m_aElementalRiftGUIDs
std::array<std::vector<ObjectGuid>, MAX_ELEMENTS> world_map_kalimdor::m_aElementalRiftGUIDs
Definition at line 49 of file world_kalimdor.cpp.
Referenced by DoDespawnElementalRifts(), Initialize(), and OnObjectCreate().
m_brewfestEvent
BrewfestEvent world_map_kalimdor::m_brewfestEvent
Definition at line 55 of file world_kalimdor.cpp.
Referenced by OnEventHappened(), and Update().
m_encounter
uint32 world_map_kalimdor::m_encounter[MAX_ENCOUNTER]
Definition at line 47 of file world_kalimdor.cpp.
Referenced by GetData(), Initialize(), SetData(), and Update().
m_freedSpriteDarter
uint32 world_map_kalimdor::m_freedSpriteDarter
Definition at line 51 of file world_kalimdor.cpp.
Referenced by Initialize(), and SetData().
m_shadeData
ShadeOfTheHorsemanData world_map_kalimdor::m_shadeData
Definition at line 53 of file world_kalimdor.cpp.
Referenced by CheckConditionCriteriaMeet(), GetData(), Initialize(), and SetData().
m_uiDronesTimer
uint32 world_map_kalimdor::m_uiDronesTimer
Definition at line 50 of file world_kalimdor.cpp.
Referenced by Initialize(), SetData(), and Update().
m_uiMurkdeepAdds_KilledAddCount
uint8 world_map_kalimdor::m_uiMurkdeepAdds_KilledAddCount
Definition at line 42 of file world_kalimdor.cpp.
Referenced by Initialize(), and OnCreatureDeath().
m_uiOmenMoonlightTimer
uint32 world_map_kalimdor::m_uiOmenMoonlightTimer
Definition at line 45 of file world_kalimdor.cpp.
Referenced by Initialize(), SetData(), and Update().
m_uiOmenResetTimer
uint32 world_map_kalimdor::m_uiOmenResetTimer
Definition at line 44 of file world_kalimdor.cpp.
Referenced by Initialize(), SetData(), and Update().
m_uiRocketsCounter
uint8 world_map_kalimdor::m_uiRocketsCounter
Definition at line 46 of file world_kalimdor.cpp.
Referenced by Initialize(), SetData(), and Update().
m_vGOEvents
std::vector<GhostOPlasmEvent> world_map_kalimdor::m_vGOEvents
Definition at line 43 of file world_kalimdor.cpp.
Referenced by Initialize(), OnObjectCreate(), and Update().
The documentation for this struct was generated from the following file:
world_kalimdor.cpp