CMaNGOS_WoTLK: MaNGOS::MessageDeliverer Struct Reference
MaNGOS::MessageDeliverer Struct Reference
#include <GridNotifiers.h>
Public Member Functions
MessageDeliverer (Player const &pl, WorldPacket const &msg, bool to_self)
void Visit (CameraMapType &m)
template<class SKIP >
void Visit (GridRefManager< SKIP > &)
Data Fields
Player const & i_player
WorldPacket const & i_message
bool i_toSelf
Detailed Description
Definition at line 62 of file GridNotifiers.h.
Constructor & Destructor Documentation
MessageDeliverer()
MaNGOS::MessageDeliverer::MessageDeliverer (Player const & pl, WorldPacket const & msg, bool to_self) inline
Definition at line 67 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/2]
void MessageDeliverer::Visit (CameraMapType & m)
Definition at line 135 of file GridNotifiers.cpp.
References Unit::GetOwner(), Player::GetSession(), i_message, i_player, i_toSelf, and WorldObject::InSamePhase().
Visit() [2/2]
template<class SKIP > void MaNGOS::MessageDeliverer::Visit (GridRefManager< SKIP > &) inline
Definition at line 69 of file GridNotifiers.h.
Field Documentation
i_message
WorldPacket const& MaNGOS::MessageDeliverer::i_message
Definition at line 65 of file GridNotifiers.h.
Referenced by Visit().
i_player
Player const& MaNGOS::MessageDeliverer::i_player
Definition at line 64 of file GridNotifiers.h.
Referenced by Visit().
i_toSelf
bool MaNGOS::MessageDeliverer::i_toSelf
Definition at line 66 of file GridNotifiers.h.
Referenced by Visit().
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiers.cpp