CMaNGOS_WoTLK: go_bonfire Struct Reference
go_bonfire Struct Reference
Public Member Functions
go_bonfire (GameObject *go)
void JustSpawned () override
void ChangeState (bool active)
void ReceiveAIEvent (AIEventType eventType, uint32=0)
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustDespawned ()
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
bool m_alliance
bool m_state
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 31 of file midsummer_festival.cpp.
Constructor & Destructor Documentation
go_bonfire()
go_bonfire::go_bonfire (GameObject * go) inline
Definition at line 33 of file midsummer_festival.cpp.
References GameObjectAI::m_go, and GameObject::SetGoArtKit().
Member Function Documentation
ChangeState()
void go_bonfire::ChangeState (bool active) inline
Definition at line 46 of file midsummer_festival.cpp.
References Object::GetEntry(), Object::GetObjectGuid(), m_alliance, GameObjectAI::m_go, m_state, WorldObject::SendGameObjectCustomAnim(), and sWorldState.
Referenced by ReceiveAIEvent().
JustSpawned()
void go_bonfire::JustSpawned () inline override virtual
Reimplemented from GameObjectAI.
Definition at line 38 of file midsummer_festival.cpp.
References GameObject::CastSpell(), Object::GetEntry(), GameObject::GetGOInfo(), WorldObject::GetZoneId(), m_alliance, GameObjectAI::m_go, GameObjectInfo::name, SPELL_SUMMON_MIDSUMMER_BONFIRE_BUNNIES, sWorldState, and TRIGGERED_OLD_TRIGGERED.
ReceiveAIEvent()
void go_bonfire::ReceiveAIEvent (AIEventType eventType, uint32 = 0) inline virtual
Reimplemented from GameObjectAI.
Definition at line 53 of file midsummer_festival.cpp.
References AI_EVENT_CUSTOM_A, AI_EVENT_CUSTOM_B, ChangeState(), and m_state.
Field Documentation
m_alliance
bool go_bonfire::m_alliance
Definition at line 35 of file midsummer_festival.cpp.
Referenced by ChangeState(), and JustSpawned().
m_state
bool go_bonfire::m_state
Definition at line 36 of file midsummer_festival.cpp.
Referenced by ChangeState(), and ReceiveAIEvent().
The documentation for this struct was generated from the following file:
midsummer_festival.cpp