CMaNGOS_WoTLK: Script Struct Reference
Script Struct Reference
#include <ScriptDevAIMgr.h>
Public Member Functions
Script ()
void RegisterSelf (bool bReportError=true)
Data Fields
std::string Name
bool(* pGossipHello)(Player *, Creature *)
bool(* pGossipHelloGO)(Player *, GameObject *)
bool(* pGossipSelect)(Player *, Creature *, uint32, uint32)
bool(* pGossipSelectGO)(Player *, GameObject *, uint32, uint32)
bool(* pGossipSelectWithCode)(Player *, Creature *, uint32, uint32, const char *)
bool(* pGossipSelectGOWithCode)(Player *, GameObject *, uint32, uint32, const char *)
uint32(* pDialogStatusNPC)(const Player *, const Creature *)
uint32(* pDialogStatusGO)(const Player *, const GameObject *)
bool(* pQuestAcceptNPC)(Player *, Creature *, Quest const *)
bool(* pQuestAcceptGO)(Player *, GameObject *, Quest const *)
bool(* pQuestAcceptItem)(Player *, Item *, Quest const *)
bool(* pQuestRewardedNPC)(Player *, Creature *, Quest const *)
bool(* pQuestRewardedGO)(Player *, GameObject *, Quest const *)
bool(* pGOUse)(Player *, GameObject *)
bool(* pItemUse)(Player *, Item *, SpellCastTargets const &)
bool(* pItemLoot)(Player *, Item *, bool)
bool(* pAreaTrigger)(Player *, AreaTriggerEntry const *)
bool(* pNpcSpellClick)(Player *, Creature *, uint32)
bool(* pProcessEventId)(uint32, Object *, Object *, bool)
bool(* pEffectDummyNPC)(Unit *, uint32, SpellEffectIndex, Creature *, ObjectGuid)
bool(* pEffectDummyGO)(Unit *, uint32, SpellEffectIndex, GameObject *, ObjectGuid)
bool(* pEffectDummyItem)(Unit *, uint32, SpellEffectIndex, Item *, ObjectGuid)
bool(* pEffectScriptEffectNPC)(Unit *, uint32, SpellEffectIndex, Creature *, ObjectGuid)
bool(* pEffectAuraDummy)(const Aura *, bool)
std::function< bool(Unit *)> * pTrapSearching
GameObjectAI *(* GetGameObjectAI)(GameObject *)
UnitAI *(* GetAI)(Creature *)
InstanceData *(* GetInstanceData)(Map *)
Detailed Description
Definition at line 85 of file ScriptDevAIMgr.h.
Constructor & Destructor Documentation
Script()
Script::Script () inline
Definition at line 87 of file ScriptDevAIMgr.h.
Member Function Documentation
RegisterSelf()
void Script::RegisterSelf (bool bReportError = true)
Definition at line 147 of file ScriptDevAIMgr.cpp.
References Name, script_error_log(), and sScriptDevAIMgr.
Referenced by AddSC_arathi_highlands(), AddSC_arcatraz(), AddSC_areatrigger_scripts(), AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bashir_landing(), AddSC_battleground(), AddSC_black_temple(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_blasted_lands(), AddSC_blood_prince_council(), AddSC_bloodmyst_isle(), AddSC_borean_tundra(), AddSC_boss_aeonus(), AddSC_boss_ahune(), AddSC_boss_akilzon(), AddSC_boss_alar(), AddSC_boss_algalon(), AddSC_boss_amanitar(), AddSC_boss_ambassador_flamelash(), AddSC_boss_ambassador_hellmaw(), AddSC_boss_anetheron(), AddSC_boss_anomalus(), AddSC_boss_anubarak(), AddSC_boss_anubarak_trial(), AddSC_boss_anubrekhan(), AddSC_boss_anzu(), AddSC_boss_arcanist_doan(), AddSC_boss_archaedas(), AddSC_boss_archimonde(), AddSC_boss_argent_challenge(), AddSC_boss_arlokk(), AddSC_boss_assembly_of_iron(), AddSC_boss_attumen(), AddSC_boss_auriaya(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_baltharus(), AddSC_boss_baron_geddon(), AddSC_boss_baroness_anastari(), AddSC_boss_bjarngrim(), AddSC_boss_black_knight(), AddSC_boss_black_stalker(), AddSC_boss_blackheart_the_inciter(), AddSC_boss_blood_queen_lanathel(), AddSC_boss_broggok(), AddSC_boss_bronjahm(), AddSC_boss_broodlord(), AddSC_boss_brutallus(), AddSC_boss_buru(), AddSC_boss_cannon_master_willey(), AddSC_boss_chromaggus(), AddSC_boss_chrono_lord_deja(), AddSC_boss_colossus(), AddSC_boss_coren_direbrew(), AddSC_boss_cthun(), AddSC_boss_curator(), AddSC_boss_dalliah(), AddSC_boss_darkmaster_gandling(), AddSC_boss_darkweaver_syth(), AddSC_boss_dathrohan_balnazzar(), AddSC_boss_deathbringer_saurfang(), AddSC_boss_devourer_of_souls(), AddSC_boss_doomlordkazzak(), AddSC_boss_doomwalker(), AddSC_boss_draganthaurissan(), AddSC_boss_ebonroc(), AddSC_boss_eredar_twins(), AddSC_boss_eregos(), AddSC_boss_exarch_maladaar(), AddSC_boss_faction_champions(), AddSC_boss_faerlina(), AddSC_boss_fankriss(), AddSC_boss_fathomlord_karathress(), AddSC_boss_felblood_kaelthas(), AddSC_boss_felmyst(), AddSC_boss_festergut(), AddSC_boss_firemaw(), AddSC_boss_flame_leviathan(), AddSC_boss_flamegor(), AddSC_boss_four_horsemen(), AddSC_boss_freya(), AddSC_boss_galdarah(), AddSC_boss_garfrost(), AddSC_boss_garr(), AddSC_boss_gehennas(), AddSC_boss_general_angerforge(), AddSC_boss_general_vezax(), AddSC_boss_gluth(), AddSC_boss_golemagg(), AddSC_boss_gortok(), AddSC_boss_gothik(), AddSC_boss_grand_champions(), AddSC_boss_grand_warlock_nethekurse(), AddSC_boss_grandmaster_vorpil(), AddSC_boss_grobbulus(), AddSC_boss_gruul(), AddSC_boss_gurtogg_bloodboil(), AddSC_boss_gyth(), AddSC_boss_hadronox(), AddSC_boss_hakkar(), AddSC_boss_halazzi(), AddSC_boss_halion(), AddSC_boss_harbinger_skyriss(), AddSC_boss_headless_horseman(), AddSC_boss_heigan(), AddSC_boss_herod(), AddSC_boss_high_astromancer_solarian(), AddSC_boss_high_botanist_freywinn(), AddSC_boss_high_interrogator_gerstahn(), AddSC_boss_high_king_maulgar(), AddSC_boss_highlord_kruul(), AddSC_boss_hodir(), AddSC_boss_huhuran(), AddSC_boss_hummel(), AddSC_boss_hungarfen(), AddSC_boss_hydromancer_thespia(), AddSC_boss_hydross_the_unstable(), AddSC_boss_ichoron(), AddSC_boss_ignis(), AddSC_boss_illidan(), AddSC_boss_illidari_council(), AddSC_boss_ingvar(), AddSC_boss_ionar(), AddSC_boss_janalai(), AddSC_boss_jandicebarov(), AddSC_boss_jaraxxus(), AddSC_boss_jedoga(), AddSC_boss_jeklik(), AddSC_boss_kaelthas(), AddSC_boss_kalecgos(), AddSC_boss_kazrogal(), AddSC_boss_kazzakAI(), AddSC_boss_keleseth(), AddSC_boss_kelidan_the_breaker(), AddSC_boss_kelthuzad(), AddSC_boss_keristrasza(), AddSC_boss_kiljaeden(), AddSC_boss_kologarn(), AddSC_boss_krick_and_ick(), AddSC_boss_krikthir(), AddSC_boss_kurinnaxx(), AddSC_boss_lady_deathwhisper(), AddSC_boss_lady_vashj(), AddSC_boss_laj(), AddSC_boss_leotheras_the_blind(), AddSC_boss_lich_king(), AddSC_boss_loatheb(), AddSC_boss_loken(), AddSC_boss_lord_marrowgar(), AddSC_boss_lucifron(), AddSC_boss_maexxna(), AddSC_boss_magmadar(), AddSC_boss_magtheridon(), AddSC_boss_maiden_of_virtue(), AddSC_boss_majordomo(), AddSC_boss_malacrass(), AddSC_boss_maleki_the_pallid(), AddSC_boss_malygos(), AddSC_boss_mandokir(), AddSC_boss_marli(), AddSC_boss_mechano_lord_capacitus(), AddSC_boss_mekgineer_steamrigger(), AddSC_boss_mimiron(), AddSC_boss_moam(), AddSC_boss_mograine_and_whitemane(), AddSC_boss_moorabi(), AddSC_boss_moroes(), AddSC_boss_morogrim_tidewalker(), AddSC_boss_mother_shahraz(), AddSC_boss_mr_smite(), AddSC_boss_murmur(), AddSC_boss_muru(), AddSC_boss_nadox(), AddSC_boss_najentus(), AddSC_boss_nalorakk(), AddSC_boss_nazan_and_vazruden(), AddSC_boss_nefarian(), AddSC_boss_nethermancer_sepethrea(), AddSC_boss_netherspite(), AddSC_boss_nexusprince_shaffar(), AddSC_boss_nightbane(), AddSC_boss_noth(), AddSC_boss_novos(), AddSC_boss_noxxion(), AddSC_boss_omor_the_unscarred(), AddSC_boss_onyxia(), AddSC_boss_order_of_silver_hand(), AddSC_boss_ormorok(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_overlordwyrmthalak(), AddSC_boss_pandemonius(), AddSC_boss_patchwerk(), AddSC_boss_pathaleon_the_calculator(), AddSC_boss_priestess_delrissa(), AddSC_boss_prince_malchezaar(), AddSC_boss_professor_putricide(), AddSC_boss_pyroguard_emberseer(), AddSC_boss_rage_winterchill(), AddSC_boss_ragnaros(), AddSC_boss_rajaxx(), AddSC_boss_razorgore(), AddSC_boss_razorscale(), AddSC_boss_razuvious(), AddSC_boss_reliquary_of_souls(), AddSC_boss_renataki(), AddSC_boss_rotface(), AddSC_boss_sapphiron(), AddSC_boss_sartharion(), AddSC_boss_sartura(), AddSC_boss_saviana(), AddSC_boss_selin_fireheart(), AddSC_boss_shade_of_akama(), AddSC_boss_shade_of_aran(), AddSC_boss_shazzrah(), AddSC_boss_shirrak(), AddSC_boss_sindragosa(), AddSC_boss_sjonnir(), AddSC_boss_skadi(), AddSC_boss_skeram(), AddSC_boss_sladran(), AddSC_boss_soccothrates(), AddSC_boss_sulfuron(), AddSC_boss_supremus(), AddSC_boss_svala(), AddSC_boss_swamplord_muselek(), AddSC_boss_taldaram(), AddSC_boss_talon_king_ikiss(), AddSC_boss_telestra(), AddSC_boss_temporus(), AddSC_boss_terestian_illhoof(), AddSC_boss_terokk(), AddSC_boss_teron_gorefiend(), AddSC_boss_thaddius(), AddSC_boss_tharonja(), AddSC_boss_the_lich_king(), AddSC_boss_the_lurker_below(), AddSC_boss_the_maker(), AddSC_boss_thekal(), AddSC_boss_thermaplugg(), AddSC_boss_thorim(), AddSC_boss_thorngrin(), AddSC_boss_trollgore(), AddSC_boss_twinemperors(), AddSC_boss_tyrannus(), AddSC_boss_urom(), AddSC_boss_vaelastrasz(), AddSC_boss_valithria_dreamwalker(), AddSC_boss_varos(), AddSC_boss_venoxis(), AddSC_boss_vexallus(), AddSC_boss_victor_nefarius(), AddSC_boss_viscidus(), AddSC_boss_void_reaver(), AddSC_boss_volazj(), AddSC_boss_volkhan(), AddSC_boss_warbringer_omrogg(), AddSC_boss_warchief_kargath_bladefist(), AddSC_boss_warlord_kalithresh(), AddSC_boss_warp_splinter(), AddSC_boss_watchkeeper_gargolmar(), AddSC_boss_xevozz(), AddSC_boss_xt_002(), AddSC_boss_ymiron(), AddSC_boss_yogg_saron(), AddSC_boss_yor(), AddSC_boss_zarithrian(), AddSC_boss_zuljin(), AddSC_boss_zumrah(), AddSC_bosses_emerald_dragons(), AddSC_bosses_opera(), AddSC_brewfest(), AddSC_bug_trio(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_childrens_week_tbc(), AddSC_culling_of_stratholme(), AddSC_dalaran(), AddSC_dark_portal(), AddSC_darkshore(), AddSC_deadmines(), AddSC_desolace(), AddSC_dire_maul(), AddSC_dragonblight(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_eastern_plaguelands(), AddSC_ebon_hold(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_example_gossip_codebox(), AddSC_example_misc(), AddSC_felwood(), AddSC_feralas(), AddSC_generic_creature(), AddSC_ghostlands(), AddSC_gnomeregan(), AddSC_go_scripts(), AddSC_grizzly_hills(), AddSC_guards(), AddSC_gunship_battle(), AddSC_halls_of_reflection(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_howling_fjord(), AddSC_hyjal(), AddSC_icecrown(), AddSC_icecrown_citadel(), AddSC_instance_ahnkahet(), AddSC_instance_arcatraz(), AddSC_instance_azjol_nerub(), AddSC_instance_black_temple(), AddSC_instance_blackfathom_deeps(), AddSC_instance_blackrock_depths(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_blood_furnace(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dark_portal(), AddSC_instance_deadmines(), AddSC_instance_dire_maul(), AddSC_instance_draktharon_keep(), AddSC_instance_eye_of_eternity(), AddSC_instance_forge_of_souls(), AddSC_instance_gnomeregan(), AddSC_instance_gruuls_lair(), AddSC_instance_gundrak(), AddSC_instance_halls_of_lightning(), AddSC_instance_halls_of_reflection(), AddSC_instance_halls_of_stone(), AddSC_instance_icecrown_citadel(), AddSC_instance_karazhan(), AddSC_instance_magisters_terrace(), AddSC_instance_magtheridons_lair(), AddSC_instance_maraudon(), AddSC_instance_mechanar(), AddSC_instance_molten_core(), AddSC_instance_mount_hyjal(), AddSC_instance_naxxramas(), AddSC_instance_nexus(), AddSC_instance_obsidian_sanctum(), AddSC_instance_oculus(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_pinnacle(), AddSC_instance_pit_of_saron(), AddSC_instance_ramparts(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruby_sanctum(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_scarlet_monastery(), AddSC_instance_scholomance(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_sethekk_halls(), AddSC_instance_shadow_labyrinth(), AddSC_instance_shadowfang_keep(), AddSC_instance_shattered_halls(), AddSC_instance_slave_pens(), AddSC_instance_steam_vault(), AddSC_instance_stratholme(), AddSC_instance_sunken_temple(), AddSC_instance_sunwell_plateau(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_eye(), AddSC_instance_trial_of_the_champion(), AddSC_instance_trial_of_the_crusader(), AddSC_instance_uldaman(), AddSC_instance_ulduar(), AddSC_instance_underbog(), AddSC_instance_utgarde_keep(), AddSC_instance_violet_hold(), AddSC_instance_wailing_caverns(), AddSC_instance_zulaman(), AddSC_instance_zulfarrak(), AddSC_instance_zulgurub(), AddSC_isle_of_queldanas(), AddSC_item_scripts(), AddSC_karazhan(), AddSC_loch_modan(), AddSC_magisters_terrace(), AddSC_mana_tombs(), AddSC_midsummer_festival(), AddSC_mob_anubisath_sentinel(), AddSC_moonglade(), AddSC_mulgore(), AddSC_nagrand(), AddSC_naxxramas(), AddSC_netherstorm(), AddSC_northrend_beasts(), AddSC_npc_professions(), AddSC_npcs_special(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_OutlandWorldScript(), AddSC_pit_of_saron(), AddSC_quests_scripts(), AddSC_razorfen_downs(), AddSC_razorfen_kraul(), AddSC_redridge_mountains(), AddSC_ruins_of_ahnqiraj(), AddSC_scholomance(), AddSC_scourge_invasion(), AddSC_searing_gorge(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shartuul_transporter(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_silverpine_forest(), AddSC_spell_scripts(), AddSC_stonetalon_mountains(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_stranglethorn_vale(), AddSC_stratholme(), AddSC_sunken_temple(), AddSC_suns_reach_reclamation(), AddSC_sunwell_plateau(), AddSC_swamp_of_sorrows(), AddSC_tanaris(), AddSC_teldrassil(), AddSC_terokkar_forest(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_tirisfal_glades(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_twin_valkyr(), AddSC_ulduar(), AddSC_undercity(), AddSC_ungoro_crater(), AddSC_utgarde_keep(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_war_effort(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_wetlands(), AddSC_wintergrasp(), AddSC_winterspring(), AddSC_world_eastern_kingdoms(), AddSC_world_kalimdor(), AddSC_world_map_ebon_hold(), AddSC_world_map_scripts(), AddSC_world_northrend(), AddSC_zangarmarsh(), AddSC_zulaman(), AddSC_zuldrak(), AddSC_zulfarrak(), AddSC_zulgurub(), LoadDeathKnightScripts(), and LoadShamanScripts().
Field Documentation
GetAI
UnitAI*(* Script::GetAI) (Creature *)
Definition at line 127 of file ScriptDevAIMgr.h.
Referenced by AddSC_arathi_highlands(), AddSC_arcatraz(), AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bashir_landing(), AddSC_battleground(), AddSC_black_temple(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_blood_prince_council(), AddSC_bloodmyst_isle(), AddSC_borean_tundra(), AddSC_boss_aeonus(), AddSC_boss_ahune(), AddSC_boss_akilzon(), AddSC_boss_alar(), AddSC_boss_algalon(), AddSC_boss_amanitar(), AddSC_boss_ambassador_flamelash(), AddSC_boss_ambassador_hellmaw(), AddSC_boss_anetheron(), AddSC_boss_anomalus(), AddSC_boss_anubarak(), AddSC_boss_anubarak_trial(), AddSC_boss_anubrekhan(), AddSC_boss_anzu(), AddSC_boss_arcanist_doan(), AddSC_boss_archaedas(), AddSC_boss_archimonde(), AddSC_boss_argent_challenge(), AddSC_boss_arlokk(), AddSC_boss_assembly_of_iron(), AddSC_boss_attumen(), AddSC_boss_auriaya(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_baltharus(), AddSC_boss_baron_geddon(), AddSC_boss_baroness_anastari(), AddSC_boss_bjarngrim(), AddSC_boss_black_knight(), AddSC_boss_black_stalker(), AddSC_boss_blackheart_the_inciter(), AddSC_boss_blood_queen_lanathel(), AddSC_boss_broggok(), AddSC_boss_bronjahm(), AddSC_boss_broodlord(), AddSC_boss_brutallus(), AddSC_boss_buru(), AddSC_boss_cannon_master_willey(), AddSC_boss_chromaggus(), AddSC_boss_chrono_lord_deja(), AddSC_boss_colossus(), AddSC_boss_coren_direbrew(), AddSC_boss_cthun(), AddSC_boss_curator(), AddSC_boss_dalliah(), AddSC_boss_darkmaster_gandling(), AddSC_boss_darkweaver_syth(), AddSC_boss_dathrohan_balnazzar(), AddSC_boss_deathbringer_saurfang(), AddSC_boss_devourer_of_souls(), AddSC_boss_doomlordkazzak(), AddSC_boss_doomwalker(), AddSC_boss_draganthaurissan(), AddSC_boss_ebonroc(), AddSC_boss_eredar_twins(), AddSC_boss_eregos(), AddSC_boss_exarch_maladaar(), AddSC_boss_faction_champions(), AddSC_boss_faerlina(), AddSC_boss_fankriss(), AddSC_boss_fathomlord_karathress(), AddSC_boss_felblood_kaelthas(), AddSC_boss_felmyst(), AddSC_boss_festergut(), AddSC_boss_firemaw(), AddSC_boss_flame_leviathan(), AddSC_boss_flamegor(), AddSC_boss_four_horsemen(), AddSC_boss_freya(), AddSC_boss_galdarah(), AddSC_boss_garfrost(), AddSC_boss_garr(), AddSC_boss_gehennas(), AddSC_boss_general_angerforge(), AddSC_boss_general_vezax(), AddSC_boss_gluth(), AddSC_boss_golemagg(), AddSC_boss_gothik(), AddSC_boss_grand_champions(), AddSC_boss_grand_warlock_nethekurse(), AddSC_boss_grandmaster_vorpil(), AddSC_boss_grobbulus(), AddSC_boss_gruul(), AddSC_boss_gurtogg_bloodboil(), AddSC_boss_gyth(), AddSC_boss_hadronox(), AddSC_boss_hakkar(), AddSC_boss_halazzi(), AddSC_boss_halion(), AddSC_boss_harbinger_skyriss(), AddSC_boss_headless_horseman(), AddSC_boss_heigan(), AddSC_boss_herod(), AddSC_boss_high_astromancer_solarian(), AddSC_boss_high_botanist_freywinn(), AddSC_boss_high_interrogator_gerstahn(), AddSC_boss_high_king_maulgar(), AddSC_boss_highlord_kruul(), AddSC_boss_hodir(), AddSC_boss_huhuran(), AddSC_boss_hummel(), AddSC_boss_hungarfen(), AddSC_boss_hydromancer_thespia(), AddSC_boss_hydross_the_unstable(), AddSC_boss_ichoron(), AddSC_boss_ignis(), AddSC_boss_illidan(), AddSC_boss_illidari_council(), AddSC_boss_ingvar(), AddSC_boss_ionar(), AddSC_boss_janalai(), AddSC_boss_jandicebarov(), AddSC_boss_jaraxxus(), AddSC_boss_jedoga(), AddSC_boss_jeklik(), AddSC_boss_kaelthas(), AddSC_boss_kalecgos(), AddSC_boss_kazrogal(), AddSC_boss_kazzakAI(), AddSC_boss_keleseth(), AddSC_boss_kelidan_the_breaker(), AddSC_boss_kelthuzad(), AddSC_boss_keristrasza(), AddSC_boss_kiljaeden(), AddSC_boss_kologarn(), AddSC_boss_krick_and_ick(), AddSC_boss_krikthir(), AddSC_boss_kurinnaxx(), AddSC_boss_lady_deathwhisper(), AddSC_boss_lady_vashj(), AddSC_boss_laj(), AddSC_boss_leotheras_the_blind(), AddSC_boss_lich_king(), AddSC_boss_loatheb(), AddSC_boss_loken(), AddSC_boss_lord_marrowgar(), AddSC_boss_lucifron(), AddSC_boss_maexxna(), AddSC_boss_magmadar(), AddSC_boss_magtheridon(), AddSC_boss_maiden_of_virtue(), AddSC_boss_majordomo(), AddSC_boss_malacrass(), AddSC_boss_maleki_the_pallid(), AddSC_boss_malygos(), AddSC_boss_mandokir(), AddSC_boss_marli(), AddSC_boss_mechano_lord_capacitus(), AddSC_boss_mekgineer_steamrigger(), AddSC_boss_mimiron(), AddSC_boss_moam(), AddSC_boss_mograine_and_whitemane(), AddSC_boss_moorabi(), AddSC_boss_moroes(), AddSC_boss_morogrim_tidewalker(), AddSC_boss_mother_shahraz(), AddSC_boss_mr_smite(), AddSC_boss_murmur(), AddSC_boss_muru(), AddSC_boss_nadox(), AddSC_boss_najentus(), AddSC_boss_nalorakk(), AddSC_boss_nazan_and_vazruden(), AddSC_boss_nefarian(), AddSC_boss_nethermancer_sepethrea(), AddSC_boss_netherspite(), AddSC_boss_nexusprince_shaffar(), AddSC_boss_nightbane(), AddSC_boss_noth(), AddSC_boss_novos(), AddSC_boss_noxxion(), AddSC_boss_omor_the_unscarred(), AddSC_boss_onyxia(), AddSC_boss_order_of_silver_hand(), AddSC_boss_ormorok(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_overlordwyrmthalak(), AddSC_boss_pandemonius(), AddSC_boss_patchwerk(), AddSC_boss_pathaleon_the_calculator(), AddSC_boss_priestess_delrissa(), AddSC_boss_prince_malchezaar(), AddSC_boss_professor_putricide(), AddSC_boss_pyroguard_emberseer(), AddSC_boss_rage_winterchill(), AddSC_boss_ragnaros(), AddSC_boss_rajaxx(), AddSC_boss_razorgore(), AddSC_boss_razorscale(), AddSC_boss_razuvious(), AddSC_boss_reliquary_of_souls(), AddSC_boss_renataki(), AddSC_boss_rotface(), AddSC_boss_sapphiron(), AddSC_boss_sartharion(), AddSC_boss_sartura(), AddSC_boss_saviana(), AddSC_boss_selin_fireheart(), AddSC_boss_shade_of_akama(), AddSC_boss_shade_of_aran(), AddSC_boss_shazzrah(), AddSC_boss_shirrak(), AddSC_boss_sindragosa(), AddSC_boss_sjonnir(), AddSC_boss_skadi(), AddSC_boss_skeram(), AddSC_boss_sladran(), AddSC_boss_soccothrates(), AddSC_boss_sulfuron(), AddSC_boss_supremus(), AddSC_boss_svala(), AddSC_boss_swamplord_muselek(), AddSC_boss_taldaram(), AddSC_boss_talon_king_ikiss(), AddSC_boss_telestra(), AddSC_boss_temporus(), AddSC_boss_terestian_illhoof(), AddSC_boss_terokk(), AddSC_boss_teron_gorefiend(), AddSC_boss_thaddius(), AddSC_boss_tharonja(), AddSC_boss_the_lich_king(), AddSC_boss_the_lurker_below(), AddSC_boss_the_maker(), AddSC_boss_thekal(), AddSC_boss_thermaplugg(), AddSC_boss_thorim(), AddSC_boss_thorngrin(), AddSC_boss_trollgore(), AddSC_boss_twinemperors(), AddSC_boss_tyrannus(), AddSC_boss_urom(), AddSC_boss_vaelastrasz(), AddSC_boss_valithria_dreamwalker(), AddSC_boss_varos(), AddSC_boss_venoxis(), AddSC_boss_vexallus(), AddSC_boss_victor_nefarius(), AddSC_boss_viscidus(), AddSC_boss_void_reaver(), AddSC_boss_volazj(), AddSC_boss_volkhan(), AddSC_boss_warbringer_omrogg(), AddSC_boss_warchief_kargath_bladefist(), AddSC_boss_warlord_kalithresh(), AddSC_boss_warp_splinter(), AddSC_boss_watchkeeper_gargolmar(), AddSC_boss_xevozz(), AddSC_boss_xt_002(), AddSC_boss_ymiron(), AddSC_boss_yogg_saron(), AddSC_boss_yor(), AddSC_boss_zarithrian(), AddSC_boss_zuljin(), AddSC_boss_zumrah(), AddSC_bosses_emerald_dragons(), AddSC_bosses_opera(), AddSC_brewfest(), AddSC_bug_trio(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_childrens_week_tbc(), AddSC_culling_of_stratholme(), AddSC_dalaran(), AddSC_dark_portal(), AddSC_darkshore(), AddSC_desolace(), AddSC_dire_maul(), AddSC_dragonblight(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_eastern_plaguelands(), AddSC_ebon_hold(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_felwood(), AddSC_feralas(), AddSC_generic_creature(), AddSC_ghostlands(), AddSC_gnomeregan(), AddSC_go_scripts(), AddSC_grizzly_hills(), AddSC_guards(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_howling_fjord(), AddSC_hyjal(), AddSC_icecrown(), AddSC_icecrown_citadel(), AddSC_instance_blackrock_spire(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_shattered_halls(), AddSC_isle_of_queldanas(), AddSC_karazhan(), AddSC_loch_modan(), AddSC_magisters_terrace(), AddSC_mana_tombs(), AddSC_midsummer_festival(), AddSC_mob_anubisath_sentinel(), AddSC_moonglade(), AddSC_mulgore(), AddSC_nagrand(), AddSC_naxxramas(), AddSC_netherstorm(), AddSC_northrend_beasts(), AddSC_npcs_special(), AddSC_old_hillsbrad(), AddSC_pit_of_saron(), AddSC_quests_scripts(), AddSC_razorfen_downs(), AddSC_razorfen_kraul(), AddSC_redridge_mountains(), AddSC_ruins_of_ahnqiraj(), AddSC_scholomance(), AddSC_scourge_invasion(), AddSC_searing_gorge(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shartuul_transporter(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_silverpine_forest(), AddSC_stonetalon_mountains(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_stranglethorn_vale(), AddSC_stratholme(), AddSC_sunken_temple(), AddSC_sunwell_plateau(), AddSC_swamp_of_sorrows(), AddSC_tanaris(), AddSC_teldrassil(), AddSC_terokkar_forest(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_tirisfal_glades(), AddSC_trial_of_the_crusader(), AddSC_twin_valkyr(), AddSC_ulduar(), AddSC_undercity(), AddSC_ungoro_crater(), AddSC_utgarde_keep(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_war_effort(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_wetlands(), AddSC_wintergrasp(), AddSC_winterspring(), AddSC_world_eastern_kingdoms(), AddSC_zangarmarsh(), AddSC_zulaman(), AddSC_zuldrak(), AddSC_zulgurub(), ScriptDevAIMgr::GetCreatureAI(), LoadDeathKnightScripts(), and LoadShamanScripts().
GetGameObjectAI
GameObjectAI*(* Script::GetGameObjectAI) (GameObject *)
Definition at line 126 of file ScriptDevAIMgr.h.
Referenced by AddSC_azshara(), AddSC_battleground(), AddSC_blades_edge_mountains(), AddSC_borean_tundra(), AddSC_boss_magtheridon(), AddSC_dire_maul(), AddSC_dragonblight(), AddSC_ebon_hold(), AddSC_go_scripts(), AddSC_hellfire_peninsula(), AddSC_icecrown_citadel(), AddSC_instance_blackwing_lair(), AddSC_instance_dire_maul(), AddSC_instance_maraudon(), AddSC_instance_shadow_labyrinth(), AddSC_instance_trial_of_the_crusader(), AddSC_midsummer_festival(), AddSC_npcs_special(), AddSC_scourge_invasion(), AddSC_shade_of_the_horseman(), AddSC_stonetalon_mountains(), AddSC_stormwind_city(), AddSC_terokkar_forest(), AddSC_wintergrasp(), AddSC_world_eastern_kingdoms(), and ScriptDevAIMgr::GetGameObjectAI().
GetInstanceData
InstanceData*(* Script::GetInstanceData) (Map *)
Definition at line 128 of file ScriptDevAIMgr.h.
Referenced by AddSC_instance_ahnkahet(), AddSC_instance_arcatraz(), AddSC_instance_azjol_nerub(), AddSC_instance_black_temple(), AddSC_instance_blackfathom_deeps(), AddSC_instance_blackrock_depths(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_blood_furnace(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dark_portal(), AddSC_instance_deadmines(), AddSC_instance_dire_maul(), AddSC_instance_draktharon_keep(), AddSC_instance_eye_of_eternity(), AddSC_instance_forge_of_souls(), AddSC_instance_gnomeregan(), AddSC_instance_gruuls_lair(), AddSC_instance_gundrak(), AddSC_instance_halls_of_lightning(), AddSC_instance_halls_of_reflection(), AddSC_instance_halls_of_stone(), AddSC_instance_icecrown_citadel(), AddSC_instance_karazhan(), AddSC_instance_magisters_terrace(), AddSC_instance_magtheridons_lair(), AddSC_instance_maraudon(), AddSC_instance_mechanar(), AddSC_instance_molten_core(), AddSC_instance_mount_hyjal(), AddSC_instance_naxxramas(), AddSC_instance_nexus(), AddSC_instance_obsidian_sanctum(), AddSC_instance_oculus(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_pinnacle(), AddSC_instance_pit_of_saron(), AddSC_instance_ramparts(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruby_sanctum(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_scarlet_monastery(), AddSC_instance_scholomance(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_sethekk_halls(), AddSC_instance_shadow_labyrinth(), AddSC_instance_shadowfang_keep(), AddSC_instance_shattered_halls(), AddSC_instance_slave_pens(), AddSC_instance_steam_vault(), AddSC_instance_stratholme(), AddSC_instance_sunken_temple(), AddSC_instance_sunwell_plateau(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_eye(), AddSC_instance_trial_of_the_champion(), AddSC_instance_trial_of_the_crusader(), AddSC_instance_uldaman(), AddSC_instance_ulduar(), AddSC_instance_underbog(), AddSC_instance_utgarde_keep(), AddSC_instance_violet_hold(), AddSC_instance_wailing_caverns(), AddSC_instance_zulaman(), AddSC_instance_zulfarrak(), AddSC_instance_zulgurub(), AddSC_OutlandWorldScript(), AddSC_world_eastern_kingdoms(), AddSC_world_kalimdor(), AddSC_world_map_ebon_hold(), AddSC_world_northrend(), and ScriptDevAIMgr::CreateInstanceData().
Name
std::string Script::Name
Definition at line 98 of file ScriptDevAIMgr.h.
Referenced by AddSC_arathi_highlands(), AddSC_arcatraz(), AddSC_areatrigger_scripts(), AddSC_ashenvale(), AddSC_azshara(), AddSC_azuremyst_isle(), AddSC_bashir_landing(), AddSC_battleground(), AddSC_black_temple(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_blasted_lands(), AddSC_blood_prince_council(), AddSC_bloodmyst_isle(), AddSC_borean_tundra(), AddSC_boss_aeonus(), AddSC_boss_ahune(), AddSC_boss_akilzon(), AddSC_boss_alar(), AddSC_boss_algalon(), AddSC_boss_amanitar(), AddSC_boss_ambassador_flamelash(), AddSC_boss_ambassador_hellmaw(), AddSC_boss_anetheron(), AddSC_boss_anomalus(), AddSC_boss_anubarak(), AddSC_boss_anubarak_trial(), AddSC_boss_anubrekhan(), AddSC_boss_anzu(), AddSC_boss_arcanist_doan(), AddSC_boss_archaedas(), AddSC_boss_archimonde(), AddSC_boss_argent_challenge(), AddSC_boss_arlokk(), AddSC_boss_assembly_of_iron(), AddSC_boss_attumen(), AddSC_boss_auriaya(), AddSC_boss_ayamiss(), AddSC_boss_azgalor(), AddSC_boss_azuregos(), AddSC_boss_baltharus(), AddSC_boss_baron_geddon(), AddSC_boss_baroness_anastari(), AddSC_boss_bjarngrim(), AddSC_boss_black_knight(), AddSC_boss_black_stalker(), AddSC_boss_blackheart_the_inciter(), AddSC_boss_blood_queen_lanathel(), AddSC_boss_broggok(), AddSC_boss_bronjahm(), AddSC_boss_broodlord(), AddSC_boss_brutallus(), AddSC_boss_buru(), AddSC_boss_cannon_master_willey(), AddSC_boss_chromaggus(), AddSC_boss_chrono_lord_deja(), AddSC_boss_colossus(), AddSC_boss_coren_direbrew(), AddSC_boss_cthun(), AddSC_boss_curator(), AddSC_boss_dalliah(), AddSC_boss_darkmaster_gandling(), AddSC_boss_darkweaver_syth(), AddSC_boss_dathrohan_balnazzar(), AddSC_boss_deathbringer_saurfang(), AddSC_boss_devourer_of_souls(), AddSC_boss_doomlordkazzak(), AddSC_boss_doomwalker(), AddSC_boss_draganthaurissan(), AddSC_boss_ebonroc(), AddSC_boss_eredar_twins(), AddSC_boss_eregos(), AddSC_boss_exarch_maladaar(), AddSC_boss_faction_champions(), AddSC_boss_faerlina(), AddSC_boss_fankriss(), AddSC_boss_fathomlord_karathress(), AddSC_boss_felblood_kaelthas(), AddSC_boss_felmyst(), AddSC_boss_festergut(), AddSC_boss_firemaw(), AddSC_boss_flame_leviathan(), AddSC_boss_flamegor(), AddSC_boss_four_horsemen(), AddSC_boss_freya(), AddSC_boss_galdarah(), AddSC_boss_garfrost(), AddSC_boss_garr(), AddSC_boss_gehennas(), AddSC_boss_general_angerforge(), AddSC_boss_general_vezax(), AddSC_boss_gluth(), AddSC_boss_golemagg(), AddSC_boss_gortok(), AddSC_boss_gothik(), AddSC_boss_grand_champions(), AddSC_boss_grand_warlock_nethekurse(), AddSC_boss_grandmaster_vorpil(), AddSC_boss_grobbulus(), AddSC_boss_gruul(), AddSC_boss_gurtogg_bloodboil(), AddSC_boss_gyth(), AddSC_boss_hadronox(), AddSC_boss_hakkar(), AddSC_boss_halazzi(), AddSC_boss_halion(), AddSC_boss_harbinger_skyriss(), AddSC_boss_headless_horseman(), AddSC_boss_heigan(), AddSC_boss_herod(), AddSC_boss_high_astromancer_solarian(), AddSC_boss_high_botanist_freywinn(), AddSC_boss_high_interrogator_gerstahn(), AddSC_boss_high_king_maulgar(), AddSC_boss_highlord_kruul(), AddSC_boss_hodir(), AddSC_boss_huhuran(), AddSC_boss_hummel(), AddSC_boss_hungarfen(), AddSC_boss_hydromancer_thespia(), AddSC_boss_hydross_the_unstable(), AddSC_boss_ichoron(), AddSC_boss_ignis(), AddSC_boss_illidan(), AddSC_boss_illidari_council(), AddSC_boss_ingvar(), AddSC_boss_ionar(), AddSC_boss_janalai(), AddSC_boss_jandicebarov(), AddSC_boss_jaraxxus(), AddSC_boss_jedoga(), AddSC_boss_jeklik(), AddSC_boss_kaelthas(), AddSC_boss_kalecgos(), AddSC_boss_kazrogal(), AddSC_boss_kazzakAI(), AddSC_boss_keleseth(), AddSC_boss_kelidan_the_breaker(), AddSC_boss_kelthuzad(), AddSC_boss_keristrasza(), AddSC_boss_kiljaeden(), AddSC_boss_kologarn(), AddSC_boss_krick_and_ick(), AddSC_boss_krikthir(), AddSC_boss_kurinnaxx(), AddSC_boss_lady_deathwhisper(), AddSC_boss_lady_vashj(), AddSC_boss_laj(), AddSC_boss_leotheras_the_blind(), AddSC_boss_lich_king(), AddSC_boss_loatheb(), AddSC_boss_loken(), AddSC_boss_lord_marrowgar(), AddSC_boss_lucifron(), AddSC_boss_maexxna(), AddSC_boss_magmadar(), AddSC_boss_magtheridon(), AddSC_boss_maiden_of_virtue(), AddSC_boss_majordomo(), AddSC_boss_malacrass(), AddSC_boss_maleki_the_pallid(), AddSC_boss_malygos(), AddSC_boss_mandokir(), AddSC_boss_marli(), AddSC_boss_mechano_lord_capacitus(), AddSC_boss_mekgineer_steamrigger(), AddSC_boss_mimiron(), AddSC_boss_moam(), AddSC_boss_mograine_and_whitemane(), AddSC_boss_moorabi(), AddSC_boss_moroes(), AddSC_boss_morogrim_tidewalker(), AddSC_boss_mother_shahraz(), AddSC_boss_mr_smite(), AddSC_boss_murmur(), AddSC_boss_muru(), AddSC_boss_nadox(), AddSC_boss_najentus(), AddSC_boss_nalorakk(), AddSC_boss_nazan_and_vazruden(), AddSC_boss_nefarian(), AddSC_boss_nethermancer_sepethrea(), AddSC_boss_netherspite(), AddSC_boss_nexusprince_shaffar(), AddSC_boss_nightbane(), AddSC_boss_noth(), AddSC_boss_novos(), AddSC_boss_noxxion(), AddSC_boss_omor_the_unscarred(), AddSC_boss_onyxia(), AddSC_boss_order_of_silver_hand(), AddSC_boss_ormorok(), AddSC_boss_ossirian(), AddSC_boss_ouro(), AddSC_boss_overlordwyrmthalak(), AddSC_boss_pandemonius(), AddSC_boss_patchwerk(), AddSC_boss_pathaleon_the_calculator(), AddSC_boss_priestess_delrissa(), AddSC_boss_prince_malchezaar(), AddSC_boss_professor_putricide(), AddSC_boss_pyroguard_emberseer(), AddSC_boss_rage_winterchill(), AddSC_boss_ragnaros(), AddSC_boss_rajaxx(), AddSC_boss_razorgore(), AddSC_boss_razorscale(), AddSC_boss_razuvious(), AddSC_boss_reliquary_of_souls(), AddSC_boss_renataki(), AddSC_boss_rotface(), AddSC_boss_sapphiron(), AddSC_boss_sartharion(), AddSC_boss_sartura(), AddSC_boss_saviana(), AddSC_boss_selin_fireheart(), AddSC_boss_shade_of_akama(), AddSC_boss_shade_of_aran(), AddSC_boss_shazzrah(), AddSC_boss_shirrak(), AddSC_boss_sindragosa(), AddSC_boss_sjonnir(), AddSC_boss_skadi(), AddSC_boss_skeram(), AddSC_boss_sladran(), AddSC_boss_soccothrates(), AddSC_boss_sulfuron(), AddSC_boss_supremus(), AddSC_boss_svala(), AddSC_boss_swamplord_muselek(), AddSC_boss_taldaram(), AddSC_boss_talon_king_ikiss(), AddSC_boss_telestra(), AddSC_boss_temporus(), AddSC_boss_terestian_illhoof(), AddSC_boss_terokk(), AddSC_boss_teron_gorefiend(), AddSC_boss_thaddius(), AddSC_boss_tharonja(), AddSC_boss_the_lich_king(), AddSC_boss_the_lurker_below(), AddSC_boss_the_maker(), AddSC_boss_thekal(), AddSC_boss_thermaplugg(), AddSC_boss_thorim(), AddSC_boss_thorngrin(), AddSC_boss_trollgore(), AddSC_boss_twinemperors(), AddSC_boss_tyrannus(), AddSC_boss_urom(), AddSC_boss_vaelastrasz(), AddSC_boss_valithria_dreamwalker(), AddSC_boss_varos(), AddSC_boss_venoxis(), AddSC_boss_vexallus(), AddSC_boss_victor_nefarius(), AddSC_boss_viscidus(), AddSC_boss_void_reaver(), AddSC_boss_volazj(), AddSC_boss_volkhan(), AddSC_boss_warbringer_omrogg(), AddSC_boss_warchief_kargath_bladefist(), AddSC_boss_warlord_kalithresh(), AddSC_boss_warp_splinter(), AddSC_boss_watchkeeper_gargolmar(), AddSC_boss_xevozz(), AddSC_boss_xt_002(), AddSC_boss_ymiron(), AddSC_boss_yogg_saron(), AddSC_boss_yor(), AddSC_boss_zarithrian(), AddSC_boss_zuljin(), AddSC_boss_zumrah(), AddSC_bosses_emerald_dragons(), AddSC_bosses_opera(), AddSC_brewfest(), AddSC_bug_trio(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_childrens_week_tbc(), AddSC_culling_of_stratholme(), AddSC_dalaran(), AddSC_dark_portal(), AddSC_darkshore(), AddSC_deadmines(), AddSC_desolace(), AddSC_dire_maul(), AddSC_dragonblight(), AddSC_durotar(), AddSC_dustwallow_marsh(), AddSC_eastern_plaguelands(), AddSC_ebon_hold(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_example_gossip_codebox(), AddSC_example_misc(), AddSC_felwood(), AddSC_feralas(), AddSC_generic_creature(), AddSC_ghostlands(), AddSC_gnomeregan(), AddSC_go_scripts(), AddSC_grizzly_hills(), AddSC_guards(), AddSC_gunship_battle(), AddSC_halls_of_reflection(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_howling_fjord(), AddSC_hyjal(), AddSC_icecrown(), AddSC_icecrown_citadel(), AddSC_instance_ahnkahet(), AddSC_instance_arcatraz(), AddSC_instance_azjol_nerub(), AddSC_instance_black_temple(), AddSC_instance_blackfathom_deeps(), AddSC_instance_blackrock_depths(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_blood_furnace(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dark_portal(), AddSC_instance_deadmines(), AddSC_instance_dire_maul(), AddSC_instance_draktharon_keep(), AddSC_instance_eye_of_eternity(), AddSC_instance_forge_of_souls(), AddSC_instance_gnomeregan(), AddSC_instance_gruuls_lair(), AddSC_instance_gundrak(), AddSC_instance_halls_of_lightning(), AddSC_instance_halls_of_reflection(), AddSC_instance_halls_of_stone(), AddSC_instance_icecrown_citadel(), AddSC_instance_karazhan(), AddSC_instance_magisters_terrace(), AddSC_instance_magtheridons_lair(), AddSC_instance_maraudon(), AddSC_instance_mechanar(), AddSC_instance_molten_core(), AddSC_instance_mount_hyjal(), AddSC_instance_naxxramas(), AddSC_instance_nexus(), AddSC_instance_obsidian_sanctum(), AddSC_instance_oculus(), AddSC_instance_old_hillsbrad(), AddSC_instance_onyxias_lair(), AddSC_instance_pinnacle(), AddSC_instance_pit_of_saron(), AddSC_instance_ramparts(), AddSC_instance_razorfen_downs(), AddSC_instance_razorfen_kraul(), AddSC_instance_ruby_sanctum(), AddSC_instance_ruins_of_ahnqiraj(), AddSC_instance_scarlet_monastery(), AddSC_instance_scholomance(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_sethekk_halls(), AddSC_instance_shadow_labyrinth(), AddSC_instance_shadowfang_keep(), AddSC_instance_shattered_halls(), AddSC_instance_slave_pens(), AddSC_instance_steam_vault(), AddSC_instance_stratholme(), AddSC_instance_sunken_temple(), AddSC_instance_sunwell_plateau(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_the_eye(), AddSC_instance_trial_of_the_champion(), AddSC_instance_trial_of_the_crusader(), AddSC_instance_uldaman(), AddSC_instance_ulduar(), AddSC_instance_underbog(), AddSC_instance_utgarde_keep(), AddSC_instance_violet_hold(), AddSC_instance_wailing_caverns(), AddSC_instance_zulaman(), AddSC_instance_zulfarrak(), AddSC_instance_zulgurub(), AddSC_isle_of_queldanas(), AddSC_item_scripts(), AddSC_karazhan(), AddSC_loch_modan(), AddSC_magisters_terrace(), AddSC_mana_tombs(), AddSC_midsummer_festival(), AddSC_mob_anubisath_sentinel(), AddSC_moonglade(), AddSC_mulgore(), AddSC_nagrand(), AddSC_naxxramas(), AddSC_netherstorm(), AddSC_northrend_beasts(), AddSC_npc_professions(), AddSC_npcs_special(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_OutlandWorldScript(), AddSC_pit_of_saron(), AddSC_quests_scripts(), AddSC_razorfen_downs(), AddSC_razorfen_kraul(), AddSC_redridge_mountains(), AddSC_ruins_of_ahnqiraj(), AddSC_scholomance(), AddSC_scourge_invasion(), AddSC_searing_gorge(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shartuul_transporter(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_silverpine_forest(), AddSC_spell_scripts(), AddSC_stonetalon_mountains(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_stranglethorn_vale(), AddSC_stratholme(), AddSC_sunken_temple(), AddSC_suns_reach_reclamation(), AddSC_sunwell_plateau(), AddSC_swamp_of_sorrows(), AddSC_tanaris(), AddSC_teldrassil(), AddSC_terokkar_forest(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_tirisfal_glades(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_twin_valkyr(), AddSC_ulduar(), AddSC_undercity(), AddSC_ungoro_crater(), AddSC_utgarde_keep(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_war_effort(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_wetlands(), AddSC_wintergrasp(), AddSC_winterspring(), AddSC_world_eastern_kingdoms(), AddSC_world_kalimdor(), AddSC_world_map_ebon_hold(), AddSC_world_map_scripts(), AddSC_world_northrend(), AddSC_zangarmarsh(), AddSC_zulaman(), AddSC_zuldrak(), AddSC_zulfarrak(), AddSC_zulgurub(), LoadDeathKnightScripts(), LoadShamanScripts(), and RegisterSelf().
pAreaTrigger
bool(* Script::pAreaTrigger) (Player *, AreaTriggerEntry const *)
Definition at line 116 of file ScriptDevAIMgr.h.
Referenced by AddSC_areatrigger_scripts(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_boss_brutallus(), AddSC_boss_cthun(), AddSC_boss_lich_king(), AddSC_boss_skadi(), AddSC_boss_teron_gorefiend(), AddSC_boss_vaelastrasz(), AddSC_brewfest(), AddSC_dalaran(), AddSC_dustwallow_marsh(), AddSC_example_misc(), AddSC_halls_of_reflection(), AddSC_howling_fjord(), AddSC_icecrown_citadel(), AddSC_instance_blackrock_spire(), AddSC_instance_culling_of_stratholme(), AddSC_instance_dark_portal(), AddSC_instance_icecrown_citadel(), AddSC_instance_naxxramas(), AddSC_instance_pinnacle(), AddSC_instance_scarlet_monastery(), AddSC_instance_shattered_halls(), AddSC_instance_slave_pens(), AddSC_instance_sunwell_plateau(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_underbog(), AddSC_instance_zulgurub(), AddSC_netherstorm(), AddSC_old_hillsbrad(), AddSC_pit_of_saron(), AddSC_sunken_temple(), AddSC_the_barrens(), AddSC_zuldrak(), AddSC_zulfarrak(), and ScriptDevAIMgr::OnAreaTrigger().
pDialogStatusGO
uint32(* Script::pDialogStatusGO) (const Player *, const GameObject *)
Definition at line 107 of file ScriptDevAIMgr.h.
Referenced by ScriptDevAIMgr::GetDialogStatus().
pDialogStatusNPC
uint32(* Script::pDialogStatusNPC) (const Player *, const Creature *)
Definition at line 106 of file ScriptDevAIMgr.h.
Referenced by ScriptDevAIMgr::GetDialogStatus().
pEffectAuraDummy
bool(* Script::pEffectAuraDummy) (const Aura *, bool)
Definition at line 123 of file ScriptDevAIMgr.h.
Referenced by AddSC_borean_tundra(), AddSC_boss_archaedas(), AddSC_boss_jedoga(), AddSC_boss_novos(), AddSC_boss_noxxion(), AddSC_culling_of_stratholme(), AddSC_grizzly_hills(), AddSC_halls_of_reflection(), AddSC_spell_scripts(), and ScriptDevAIMgr::OnAuraDummy().
pEffectDummyGO
bool(* Script::pEffectDummyGO) (Unit *, uint32, SpellEffectIndex, GameObject *, ObjectGuid)
Definition at line 120 of file ScriptDevAIMgr.h.
Referenced by AddSC_spell_scripts(), and ScriptDevAIMgr::OnEffectDummy().
pEffectDummyItem
bool(* Script::pEffectDummyItem) (Unit *, uint32, SpellEffectIndex, Item *, ObjectGuid)
Definition at line 121 of file ScriptDevAIMgr.h.
Referenced by ScriptDevAIMgr::OnEffectDummy().
pEffectDummyNPC
bool(* Script::pEffectDummyNPC) (Unit *, uint32, SpellEffectIndex, Creature *, ObjectGuid)
Definition at line 119 of file ScriptDevAIMgr.h.
Referenced by AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_borean_tundra(), AddSC_boss_anubarak_trial(), AddSC_boss_archaedas(), AddSC_boss_black_knight(), AddSC_boss_ionar(), AddSC_boss_kaelthas(), AddSC_boss_mimiron(), AddSC_boss_professor_putricide(), AddSC_boss_razorscale(), AddSC_boss_thermaplugg(), AddSC_boss_volkhan(), AddSC_boss_yogg_saron(), AddSC_bosses_opera(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_culling_of_stratholme(), AddSC_dark_portal(), AddSC_darkshore(), AddSC_desolace(), AddSC_durotar(), AddSC_ebon_hold(), AddSC_felwood(), AddSC_feralas(), AddSC_guards(), AddSC_halls_of_reflection(), AddSC_hellfire_peninsula(), AddSC_icecrown(), AddSC_instance_dire_maul(), AddSC_northrend_beasts(), AddSC_npcs_special(), AddSC_razorfen_kraul(), AddSC_shadowmoon_valley(), AddSC_sholazar_basin(), AddSC_spell_scripts(), AddSC_storm_peaks(), AddSC_violet_hold(), AddSC_western_plaguelands(), AddSC_zuldrak(), and ScriptDevAIMgr::OnEffectDummy().
pEffectScriptEffectNPC
bool(* Script::pEffectScriptEffectNPC) (Unit *, uint32, SpellEffectIndex, Creature *, ObjectGuid)
Definition at line 122 of file ScriptDevAIMgr.h.
Referenced by AddSC_blades_edge_mountains(), AddSC_boss_festergut(), AddSC_boss_freya(), AddSC_boss_ignis(), AddSC_boss_lich_king(), AddSC_boss_professor_putricide(), AddSC_boss_rotface(), and ScriptDevAIMgr::OnEffectScriptEffect().
pGossipHello
bool(* Script::pGossipHello) (Player *, Creature *)
Definition at line 100 of file ScriptDevAIMgr.h.
Referenced by AddSC_azshara(), AddSC_battleground(), AddSC_blackrock_depths(), AddSC_boss_illidan(), AddSC_boss_majordomo(), AddSC_boss_rajaxx(), AddSC_boss_razorscale(), AddSC_boss_shade_of_akama(), AddSC_boss_vaelastrasz(), AddSC_boss_victor_nefarius(), AddSC_bosses_opera(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_culling_of_stratholme(), AddSC_darkshore(), AddSC_desolace(), AddSC_ebon_hold(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_example_gossip_codebox(), AddSC_felwood(), AddSC_gnomeregan(), AddSC_guards(), AddSC_gunship_battle(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_howling_fjord(), AddSC_icecrown(), AddSC_instance_slave_pens(), AddSC_karazhan(), AddSC_nagrand(), AddSC_netherstorm(), AddSC_npc_professions(), AddSC_npcs_special(), AddSC_old_hillsbrad(), AddSC_orgrimmar(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_stratholme(), AddSC_tanaris(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_ulduar(), AddSC_ungoro_crater(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_winterspring(), AddSC_zulaman(), and ScriptDevAIMgr::OnGossipHello().
pGossipHelloGO
bool(* Script::pGossipHelloGO) (Player *, GameObject *)
Definition at line 101 of file ScriptDevAIMgr.h.
Referenced by AddSC_icecrown_citadel(), AddSC_netherstorm(), AddSC_shade_of_the_horseman(), AddSC_ulduar(), and ScriptDevAIMgr::OnGossipHello().
pGossipSelect
bool(* Script::pGossipSelect) (Player *, Creature *, uint32, uint32)
Definition at line 102 of file ScriptDevAIMgr.h.
Referenced by AddSC_azshara(), AddSC_blackrock_depths(), AddSC_boss_illidan(), AddSC_boss_majordomo(), AddSC_boss_rajaxx(), AddSC_boss_razorscale(), AddSC_boss_shade_of_akama(), AddSC_boss_vaelastrasz(), AddSC_boss_victor_nefarius(), AddSC_bosses_opera(), AddSC_burning_steppes(), AddSC_chess_event(), AddSC_culling_of_stratholme(), AddSC_darkshore(), AddSC_ebon_hold(), AddSC_eversong_woods(), AddSC_example_creature(), AddSC_example_escort(), AddSC_example_gossip_codebox(), AddSC_felwood(), AddSC_gnomeregan(), AddSC_gunship_battle(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_howling_fjord(), AddSC_hyjal(), AddSC_icecrown(), AddSC_karazhan(), AddSC_netherstorm(), AddSC_npc_professions(), AddSC_npcs_special(), AddSC_old_hillsbrad(), AddSC_shade_of_the_horseman(), AddSC_shadowfang_keep(), AddSC_shadowmoon_valley(), AddSC_shattrath_city(), AddSC_sholazar_basin(), AddSC_silithus(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_tanaris(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_trial_of_the_champion(), AddSC_trial_of_the_crusader(), AddSC_ulduar(), AddSC_ungoro_crater(), AddSC_violet_hold(), AddSC_wailing_caverns(), AddSC_winterspring(), AddSC_zulaman(), and ScriptDevAIMgr::OnGossipSelect().
pGossipSelectGO
bool(* Script::pGossipSelectGO) (Player *, GameObject *, uint32, uint32)
Definition at line 103 of file ScriptDevAIMgr.h.
Referenced by AddSC_icecrown_citadel(), AddSC_netherstorm(), AddSC_shade_of_the_horseman(), AddSC_ulduar(), and ScriptDevAIMgr::OnGossipSelect().
pGossipSelectGOWithCode
bool(* Script::pGossipSelectGOWithCode) (Player *, GameObject *, uint32, uint32, const char *)
Definition at line 105 of file ScriptDevAIMgr.h.
Referenced by ScriptDevAIMgr::OnGossipSelect().
pGossipSelectWithCode
bool(* Script::pGossipSelectWithCode) (Player *, Creature *, uint32, uint32, const char *)
Definition at line 104 of file ScriptDevAIMgr.h.
Referenced by AddSC_example_gossip_codebox(), and ScriptDevAIMgr::OnGossipSelect().
pGOUse
bool(* Script::pGOUse) (Player *, GameObject *)
Definition at line 113 of file ScriptDevAIMgr.h.
Referenced by AddSC_ashenvale(), AddSC_azshara(), AddSC_blackrock_depths(), AddSC_boss_algalon(), AddSC_boss_arlokk(), AddSC_boss_halion(), AddSC_boss_illidan(), AddSC_boss_lady_vashj(), AddSC_boss_magtheridon(), AddSC_boss_mimiron(), AddSC_boss_ossirian(), AddSC_boss_sapphiron(), AddSC_boss_taldaram(), AddSC_boss_the_lurker_below(), AddSC_boss_thermaplugg(), AddSC_boss_yor(), AddSC_darkshore(), AddSC_deadmines(), AddSC_eversong_woods(), AddSC_example_misc(), AddSC_feralas(), AddSC_go_scripts(), AddSC_instance_blackfathom_deeps(), AddSC_instance_blackrock_spire(), AddSC_instance_blood_furnace(), AddSC_instance_gundrak(), AddSC_instance_nexus(), AddSC_instance_serpentshrine_cavern(), AddSC_instance_steam_vault(), AddSC_moonglade(), AddSC_shade_of_the_horseman(), AddSC_sholazar_basin(), AddSC_stratholme(), AddSC_sunken_temple(), AddSC_tirisfal_glades(), AddSC_ulduar(), AddSC_winterspring(), AddSC_world_eastern_kingdoms(), AddSC_zulaman(), and ScriptDevAIMgr::OnGameObjectUse().
pItemLoot
bool(* Script::pItemLoot) (Player *, Item *, bool)
Definition at line 115 of file ScriptDevAIMgr.h.
Referenced by AddSC_boss_lady_vashj(), and ScriptDevAIMgr::OnItemLoot().
pItemUse
bool(* Script::pItemUse) (Player *, Item *, SpellCastTargets const &)
Definition at line 114 of file ScriptDevAIMgr.h.
Referenced by AddSC_example_misc(), AddSC_item_scripts(), and ScriptDevAIMgr::OnItemUse().
pNpcSpellClick
bool(* Script::pNpcSpellClick) (Player *, Creature *, uint32)
Definition at line 117 of file ScriptDevAIMgr.h.
Referenced by AddSC_borean_tundra(), AddSC_boss_razuvious(), AddSC_boss_yogg_saron(), AddSC_dragonblight(), AddSC_howling_fjord(), and ScriptDevAIMgr::OnNpcSpellClick().
pProcessEventId
bool(* Script::pProcessEventId) (uint32, Object *, Object *, bool)
Definition at line 118 of file ScriptDevAIMgr.h.
Referenced by AddSC_azshara(), AddSC_blades_edge_mountains(), AddSC_boss_general_vezax(), AddSC_boss_gortok(), AddSC_boss_hodir(), AddSC_boss_malygos(), AddSC_boss_nightbane(), AddSC_boss_razorgore(), AddSC_boss_razorscale(), AddSC_boss_svala(), AddSC_boss_terokk(), AddSC_boss_varos(), AddSC_boss_ymiron(), AddSC_darkshore(), AddSC_dire_maul(), AddSC_halls_of_stone(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_instance_blackrock_spire(), AddSC_instance_blackwing_lair(), AddSC_instance_icecrown_citadel(), AddSC_instance_old_hillsbrad(), AddSC_instance_razorfen_downs(), AddSC_instance_scholomance(), AddSC_instance_sethekk_halls(), AddSC_instance_temple_of_ahnqiraj(), AddSC_instance_uldaman(), AddSC_instance_ulduar(), AddSC_karazhan(), AddSC_magisters_terrace(), AddSC_shadowmoon_valley(), AddSC_shartuul_transporter(), AddSC_sunken_temple(), AddSC_ulduar(), AddSC_wintergrasp(), AddSC_world_map_scripts(), AddSC_zangarmarsh(), AddSC_zulaman(), AddSC_zulfarrak(), and ScriptDevAIMgr::OnProcessEvent().
pQuestAcceptGO
bool(* Script::pQuestAcceptGO) (Player *, GameObject *, Quest const *)
Definition at line 109 of file ScriptDevAIMgr.h.
Referenced by AddSC_shadowmoon_valley(), AddSC_silithus(), and ScriptDevAIMgr::OnQuestAccept().
pQuestAcceptItem
bool(* Script::pQuestAcceptItem) (Player *, Item *, Quest const *)
Definition at line 110 of file ScriptDevAIMgr.h.
Referenced by ScriptDevAIMgr::OnQuestAccept().
pQuestAcceptNPC
bool(* Script::pQuestAcceptNPC) (Player *, Creature *, Quest const *)
Definition at line 108 of file ScriptDevAIMgr.h.
Referenced by AddSC_arathi_highlands(), AddSC_ashenvale(), AddSC_azuremyst_isle(), AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_bloodmyst_isle(), AddSC_borean_tundra(), AddSC_boss_vaelastrasz(), AddSC_burning_steppes(), AddSC_culling_of_stratholme(), AddSC_darkshore(), AddSC_desolace(), AddSC_dustwallow_marsh(), AddSC_eastern_plaguelands(), AddSC_eversong_woods(), AddSC_felwood(), AddSC_feralas(), AddSC_ghostlands(), AddSC_gnomeregan(), AddSC_grizzly_hills(), AddSC_hellfire_peninsula(), AddSC_hinterlands(), AddSC_howling_fjord(), AddSC_icecrown(), AddSC_loch_modan(), AddSC_mana_tombs(), AddSC_moonglade(), AddSC_nagrand(), AddSC_netherstorm(), AddSC_npcs_special(), AddSC_razorfen_downs(), AddSC_razorfen_kraul(), AddSC_redridge_mountains(), AddSC_searing_gorge(), AddSC_shade_of_the_horseman(), AddSC_shadowmoon_valley(), AddSC_sholazar_basin(), AddSC_silverpine_forest(), AddSC_stonetalon_mountains(), AddSC_storm_peaks(), AddSC_stormwind_city(), AddSC_swamp_of_sorrows(), AddSC_tanaris(), AddSC_teldrassil(), AddSC_terokkar_forest(), AddSC_the_barrens(), AddSC_thousand_needles(), AddSC_tirisfal_glades(), AddSC_ungoro_crater(), AddSC_western_plaguelands(), AddSC_westfall(), AddSC_wetlands(), AddSC_winterspring(), AddSC_zangarmarsh(), and ScriptDevAIMgr::OnQuestAccept().
pQuestRewardedGO
bool(* Script::pQuestRewardedGO) (Player *, GameObject *, Quest const *)
Definition at line 112 of file ScriptDevAIMgr.h.
Referenced by AddSC_midsummer_festival(), AddSC_war_effort(), and ScriptDevAIMgr::OnQuestRewarded().
pQuestRewardedNPC
bool(* Script::pQuestRewardedNPC) (Player *, Creature *, Quest const *)
Definition at line 111 of file ScriptDevAIMgr.h.
Referenced by AddSC_blackrock_depths(), AddSC_blades_edge_mountains(), AddSC_boss_coren_direbrew(), AddSC_boss_hummel(), AddSC_hellfire_peninsula(), AddSC_quests_scripts(), AddSC_shattrath_city(), AddSC_stratholme(), AddSC_suns_reach_reclamation(), AddSC_undercity(), AddSC_war_effort(), AddSC_western_plaguelands(), and ScriptDevAIMgr::OnQuestRewarded().
pTrapSearching
std::function<bool(Unit*)>* Script::pTrapSearching
Definition at line 124 of file ScriptDevAIMgr.h.
Referenced by AddSC_blasted_lands(), AddSC_go_scripts(), and ScriptDevAIMgr::OnTrapSearch().
The documentation for this struct was generated from the following files:
ScriptDevAIMgr.h
ScriptDevAIMgr.cpp