CMaNGOS_WoTLK: go_screaming_hall_door Struct Reference
go_screaming_hall_door Struct Reference
Public Member Functions
go_screaming_hall_door (GameObject *go)
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
ScriptedInstance * m_pInstance
uint32 m_doorCheckNearbyPlayersTimer
bool m_doorOpen
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 193 of file shadow_labyrinth.cpp.
Constructor & Destructor Documentation
go_screaming_hall_door()
go_screaming_hall_door::go_screaming_hall_door (GameObject * go) inline
Definition at line 195 of file shadow_labyrinth.cpp.
References WorldObject::GetInstanceData(), and m_pInstance.
Member Function Documentation
UpdateAI()
void go_screaming_hall_door::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 204 of file shadow_labyrinth.cpp.
References AI_EVENT_CUSTOM_A, DONE, Map::ExecuteDistWorker(), InstanceData::GetData(), WorldObject::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), m_doorCheckNearbyPlayersTimer, m_doorOpen, GameObjectAI::m_go, m_pInstance, NPC_MURMUR, TYPE_VORPIL, and GameObject::Use().
Field Documentation
m_doorCheckNearbyPlayersTimer
uint32 go_screaming_hall_door::m_doorCheckNearbyPlayersTimer
Definition at line 201 of file shadow_labyrinth.cpp.
Referenced by UpdateAI().
m_doorOpen
bool go_screaming_hall_door::m_doorOpen
Definition at line 202 of file shadow_labyrinth.cpp.
Referenced by UpdateAI().
m_pInstance
ScriptedInstance* go_screaming_hall_door::m_pInstance
Definition at line 200 of file shadow_labyrinth.cpp.
Referenced by go_screaming_hall_door(), and UpdateAI().
The documentation for this struct was generated from the following file:
shadow_labyrinth.cpp