CMaNGOS_WoTLK: ScriptedAI Struct Reference
ScriptedAI Struct Reference
Documentation of UnitAI functions can be found in MaNGOS source.
#include <sc_creature.h>
Public Member Functions
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void ReceiveAIEvent (AIEventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
virtual void Aggro (Unit *)
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void Reset ()
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void MoveInLineOfSight (Unit *)
== Reactions At =================================
virtual void JustReachedHome ()
Called at reaching home after MoveTargetedHome.
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void JustDied (Unit *)
Called when the creature is killed.
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void KilledUnit (Unit *)
Called when the creature kills a unit.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (Creature *)
Called when the creature summon successfully other creature.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Protected Member Functions
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Private Attributes
uint32 m_uiEvadeCheckCooldown
Additional Inherited Members
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Documentation of UnitAI functions can be found in MaNGOS source.
Definition at line 46 of file sc_creature.h.
Constructor & Destructor Documentation
ScriptedAI() [1/2]
ScriptedAI::ScriptedAI (Creature * creature, uint32 combatActions) explicit
Definition at line 22 of file sc_creature.cpp.
ScriptedAI() [2/2]
ScriptedAI::ScriptedAI (Creature * creature) inline explicit
Definition at line 50 of file sc_creature.h.
~ScriptedAI()
ScriptedAI::~ScriptedAI () inline
Definition at line 51 of file sc_creature.h.
Member Function Documentation
Aggro()
virtual void ScriptedAI::Aggro (Unit *) inline virtual
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
Called at creature EnterCombat with an enemy This is a SD2 internal function Called by default on creature EnterCombat with an enemy
Reimplemented in boss_heiganAI, BossAI, npc_guardianAI, generic_creatureAI, mob_bt_battle_fighterAI, mob_shadowmoon_soulstealerAI, mob_shadowmoon_channelerAI, boss_xevozzAI, boss_ichoronAI, boss_telestraAI, boss_keristraszaAI, boss_anomalusAI, boss_thaddiusAddsAI, boss_nothAI, boss_gluthAI, boss_anubrekhanAI, boss_tyrannusAI, boss_ickAI, boss_forgemaster_garfrostAI, npc_anubisath_sentinelAI, boss_veklorAI, boss_veknilashAI, boss_buruAI, npc_defias_traitorAI, npc_galen_goodwardAI, boss_felmystAI, boss_brutallusAI, npc_deathstalker_erlandAI, boss_arugalAI, boss_ragnarosAI, boss_majordomoAI, npc_dawnblade_blood_knight, guardAI, npc_escortAI, npc_kindal_moonweaverAI, npc_letollAI, npc_warden_mellicharAI, mob_lumpAI, mob_fel_orc_convertAI, boss_ingvarAI, npc_storm_tempered_keeperAI, npc_squad_leaderAI, boss_jaraxxusAI, boss_crusader_druid_restoAI, trial_crusader_commonAI, trial_companion_commonAI, npc_black_knight_ghoulAI, boss_paletressAI, boss_eadricAI, npc_artoriusAI, npc_simone_seductressAI, npc_precious_the_devourerAI, npc_ame01AI, npc_giltharesAI, mob_aquementasAI, npc_solenorAI, npc_willix_the_importerAI, npc_areiAI, npc_captured_arkonarinAI, npc_stinky_ignatzAI, npc_prospector_remtravelAI, example_creatureAI, npc_dorius_stonetenderAI, npc_rinjiAI, npc_00x09hlAI, npc_klinfranAI, npc_marshal_windsorAI, npc_kineloryAI, boss_essence_of_angerAI, boss_essence_of_desireAI, boss_essence_of_sufferingAI, boss_kelthuzadAI, boss_razorgoreAI, mob_phoenix_tkAI, npc_the_cleanerAI, npc_burster_wormAI, boss_ysondreAI, boss_taerarAI, boss_lethonAI, boss_emerissAI, boss_highlord_kruulAI, boss_pathaleon_the_calculatorAI, npc_raging_flamesAI, boss_nethermancer_sepethreaAI, boss_mechano_lord_capacitusAI, boss_void_reaverAI, boss_master_engineer_telonicusAI, boss_grand_astromancer_capernianAI, boss_lord_sanguinarAI, boss_thaladred_the_darkenerAI, boss_high_astromancer_solarianAI, boss_alarAI, boss_warp_splinterAI, boss_thorngrinAI, boss_high_botanist_freywinnAI, boss_soccothratesAI, boss_dalliahAI, npc_wildaAI, npc_dimensiusAI, npc_protectorate_demolitionistAI, npc_shattered_hand_legionnaire, npc_Shattered_Hand_Scout, boss_warchief_kargath_bladefistAI, boss_warbringer_omroggAI, boss_grand_warlock_nethekurseAI, mob_hellfire_channelerAI, boss_watchkeeper_gargolmarAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_the_makerAI, boss_kelidan_the_breakerAI, boss_broggokAI, boss_high_king_maulgarAI, boss_gruulAI, boss_warlord_kalithreshAI, boss_mekgineer_steamriggerAI, boss_thespiaAI, boss_ahuneAI, boss_morogrim_tidewalkerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_hydross_the_unstableAI, boss_fathomlord_karathressAI, boss_doomwalkerAI, boss_doomlordkazzakAI, boss_illidari_councilAI, boss_najentusAI, boss_teron_gorefiendAI, boss_supremusAI, boss_shade_of_akamaAI, boss_shahrazAI, boss_illidan_stormrageAI, boss_gurtogg_bloodboilAI, npc_greater_shadowfiend, boss_grandmaster_vorpilAI, boss_blackheart_the_inciterAI, boss_ambassador_hellmawAI, boss_talon_king_ikissAI, boss_darkweaver_sythAI, boss_anzuAI, boss_pandemoniusAI, boss_nexusprince_shaffarAI, boss_exarch_maladaarAI, boss_ymironAI, boss_svalaAI, boss_skadiAI, mob_dragonflayer_forge_masterAI, boss_kelesethAI, boss_xt_002AI, npc_runic_colossusAI, boss_thorimAI, boss_razorscaleAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_kologarnAI, boss_ignisAI, boss_hodirAI, boss_general_vezaxAI, npc_snaplasherAI, boss_freyaAI, boss_flame_leviathanAI, boss_auriayaAI, boss_algalonAI, boss_steelbreakerAI, boss_molgeimAI, boss_brundirAI, boss_sjonnirAI, boss_volkhanAI, boss_lokenAI, boss_ionarAI, boss_bjarngrimAI, boss_zarithrianAI, boss_savianaAI, boss_halion_twilightAI, boss_halion_realAI, boss_baltharusAI, mob_vesperonAI, mob_shadronAI, mob_tenebronAI, boss_sartharionAI, boss_varosAI, boss_uromAI, boss_eregosAI, boss_ormorokAI, boss_malygosAI, npc_tesla_coilAI, boss_thaddiusAI, boss_sapphironAI, boss_gothikAI, boss_sir_zeliekAI, boss_thane_korthazzAI, boss_rivendare_naxxAI, boss_lady_blaumeuxAI, boss_the_lich_king_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_rotfaceAI, boss_professor_putricideAI, boss_lord_marrowgarAI, boss_lady_deathwhisperAI, boss_festergutAI, boss_deathbringer_saurfangAI, boss_blood_queen_lanathelAI, npc_blood_orb_controlAI, boss_devourer_of_soulsAI, boss_bronjahmAI, npc_grand_admiral_westwindAI, npc_father_kamarosAI, boss_moorabiAI, boss_trollgoreAI, boss_tharonjaAI, boss_novosAI, boss_eydisAI, boss_fjolaAI, boss_gormokAI, npc_beast_combat_stalkerAI, boss_anubarak_trialAI, boss_black_knightAI, argent_champion_commonAI, npc_proudhoofAI, npc_bonker_togglevoltAI, boss_krikthirAI, boss_anubarakAI, boss_volazjAI, boss_taldaramAI, boss_nadoxAI, boss_jedogaAI, boss_amanitarAI, boss_zumrahAI, npc_anubisath_defenderAI, boss_viscidusAI, boss_twin_emperorsAI, boss_skeramAI, boss_sarturaAI, npc_ouro_spawnerAI, boss_huhuranAI, boss_fankrissAI, boss_cthunAI, boss_eye_of_cthunAI, boss_silithidRoyaltyAI, npc_oox17tnAI, mob_anubisath_guardianAI, boss_ossirianAI, boss_moamAI, boss_onyxiaAI, npc_clintar_dw_spiritAI, npc_oox22feAI, npc_volcorAI, npc_kerlonianAI, npc_thrall_old_hillsbradAI, boss_archimondeAI, boss_temporusAI, boss_chrono_lord_dejaAI, boss_aeonusAI, npc_arthasAI, boss_azuregosAI, npc_magwinAI, npc_muglashAI, example_escortAI, mob_zealot_zathAI, mob_zealot_lorkhanAI, boss_thekalAI, boss_marliAI, boss_mandokirAI, npc_gurubashi_bat_riderAI, boss_jeklikAI, boss_hakkarAI, boss_arlokkAI, npc_amanishi_scoutAI, npc_amanishi_tempestAI, boss_zuljinAI, boss_nalorakkAI, boss_malacrassAI, boss_janalaiAI, boss_halazziAI, boss_akilzonAI, npc_tapoke_slim_jahnAI, npc_daphne_stilwellAI, npc_tirion_fordringAI, npc_taelan_fordringAI, boss_archaedasAI, npc_sunblade_protectorAI, npc_sunblade_scoutAI, boss_muruAI, boss_kalecgos_humanoidAI, boss_kalecgosAI, boss_sacrolashAI, boss_alythessAI, boss_dathrohan_balnazzarAI, npc_reginald_windsorAI, boss_scarlet_commander_mograineAI, boss_herodAI, boss_arcanist_doanAI, boss_sulfuronAI, boss_shazzrahAI, boss_magmadarAI, boss_lucifronAI, boss_golemaggAI, boss_gehennasAI, boss_garrAI, boss_baron_geddonAI, boss_vexallusAI, boss_selin_fireheartAI, boss_priestess_delrissaAI, boss_felblood_kaelthasAI, boss_romuloAI, boss_julianneAI, boss_bigbadwolfAI, boss_croneAI, boss_roarAI, boss_tinheadAI, boss_strawmanAI, boss_terestianAI, boss_aranAI, boss_malchezaarAI, boss_nightbaneAI, boss_netherspiteAI, boss_moroesAI, boss_midnightAI, boss_maiden_of_virtueAI, boss_curatorAI, boss_thermapluggAI, npc_grark_lorkrubAI, boss_kazzakAI, boss_victor_nefariusAI, boss_vaelastraszAI, boss_flamegorAI, boss_firemawAI, boss_ebonrocAI, boss_chromaggusAI, boss_broodlordAI, boss_general_angerforgeAI, boss_emperor_dagran_thaurissanAI, boss_ambassador_flamelashAI, boss_plugger_spazzringAI, npc_hurley_blackbreathAI, npc_phalanxAI, npc_professor_phizzlethorpeAI, npc_magister_aledisAI, boss_swamplord_muselekAI, and boss_anetheronAI.
Definition at line 168 of file sc_creature.h.
Referenced by npc_dawnblade_blood_knight::Aggro(), and EnterCombat().
CanCast()
bool ScriptedAI::CanCast (Unit * target, SpellEntry const * spellInfo, bool triggered = false)
Definition at line 184 of file sc_creature.cpp.
References Unit::GetPower(), GetSpellRangeStore(), Object::HasFlag(), WorldObject::IsInRange(), CreatureAI::m_creature, SpellEntry::manaCost, SpellRangeEntry::maxRange, SpellRangeEntry::minRange, SpellEntry::powerType, SpellEntry::rangeIndex, UNIT_FIELD_FLAGS, and UNIT_FLAG_SILENCED.
DoFindFriendlyMissingBuff()
CreatureList ScriptedAI::DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Definition at line 308 of file sc_creature.cpp.
References CreatureAI::m_creature, and Cell::VisitGridObjects().
Referenced by boss_sulfuronAI::ExecuteAction().
DoPlaySoundToSet()
void ScriptedAI::DoPlaySoundToSet (WorldObject * source, uint32 soundId)
Definition at line 86 of file sc_creature.cpp.
References Object::GetGUIDLow(), GetSoundEntriesStore(), Object::GetTypeId(), WorldObject::PlayDirectSound(), and script_error_log().
Referenced by boss_gothikAI::boss_gothikAI(), npc_king_llaneAI::DamageTaken(), npc_warchief_blackhandAI::DamageTaken(), npc_simon_game_bunnyAI::DoCleanupGame(), npc_simon_game_bunnyAI::DoCompleteGame(), npc_simon_game_bunnyAI::DoSetupLevel(), hyjalAI::DoTalk(), boss_bigbadwolfAI::JustDied(), boss_savianaAI::JustDied(), npc_king_llaneAI::JustDied(), npc_warchief_blackhandAI::JustDied(), npc_human_conjurerAI::JustDied(), npc_orc_warlockAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), npc_water_elementalAI::JustDied(), npc_summoned_daemonAI::JustDied(), npc_human_chargerAI::JustDied(), npc_orc_wolfAI::JustDied(), npc_human_clericAI::JustDied(), npc_orc_necrolyteAI::JustDied(), boss_halion_realAI::KilledUnit(), boss_halion_twilightAI::KilledUnit(), npc_harkorAI::MoveInLineOfSight(), npc_ashliAI::MoveInLineOfSight(), npc_simon_game_bunnyAI::ReceiveAIEvent(), npc_forest_frogAI::SpellHit(), mob_soaring_eagleAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_ashliAI::UpdateAI(), npc_echo_of_medivhAI::UpdateAI(), and boss_yogg_saronAI::UpdateAI().
DoStartMovement()
void ScriptedAI::DoStartMovement (Unit * victim)
Definition at line 65 of file sc_creature.cpp.
References Unit::GetMotionMaster(), UnitAI::m_attackAngle, UnitAI::m_attackDistance, CreatureAI::m_creature, UnitAI::m_moveFurther, and MotionMaster::MoveChase().
Referenced by boss_magtheridonAI::boss_magtheridonAI(), boss_supremusAI::boss_supremusAI(), boss_julianneAI::DoRemoveFakeDeath(), boss_romuloAI::DoRemoveFakeDeath(), boss_xt_002AI::DoResetToNormalPhase(), npc_sunblade_scoutAI::ExecuteAction(), boss_moroesAI::ExecuteAction(), boss_kaelthasAI::ExecuteActions(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_felmystAI::HandleTransitionDelay(), boss_illidan_stormrageAI::JustDidDialogueStep(), boss_kaelthasAI::MovementInform(), boss_doomwalkerAI::MovementInform(), boss_jeklikAI::MovementInform(), boss_malygosAI::MovementInform(), npc_sunblade_scoutAI::MovementInform(), boss_warlord_kalithreshAI::MovementInform(), boss_lady_malandeAI::OnSpellCooldownAdded(), mob_phoenix_tkAI::OnSpellCooldownAdded(), boss_lady_malandeAI::OnSpellInterrupt(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_maievAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), npc_amanishi_scoutAI::ReceiveAIEvent(), boss_leviathan_mk2AI::ReceiveAIEvent(), boss_selin_fireheartAI::ReceiveAIEvent(), npc_champion_mountAI::ReceiveAIEvent(), boss_leviathan_mk2AI::SpellHit(), mob_water_globuleAI::SpellHitTarget(), boss_netherspiteAI::SwitchPhases(), npc_trial_grand_championAI::UpdateAI(), npc_champion_mountAI::UpdateAI(), boss_razorscaleAI::UpdateAI(), boss_thorimAI::UpdateAI(), and advisor_base_ai::UpdateAI().
DoStartNoMovement()
void ScriptedAI::DoStartNoMovement (Unit * victim)
Definition at line 71 of file sc_creature.cpp.
References Unit::GetMotionMaster(), CreatureAI::m_creature, MotionMaster::MoveIdle(), and Unit::StopMoving().
DoStopAttack()
void ScriptedAI::DoStopAttack ()
Definition at line 80 of file sc_creature.cpp.
References Unit::AttackStop(), Unit::GetVictim(), and CreatureAI::m_creature.
DoTeleportPlayer()
void ScriptedAI::DoTeleportPlayer (Unit * unit, float x, float y, float z, float ori)
Definition at line 294 of file sc_creature.cpp.
References Object::GetGuidStr(), WorldObject::GetMapId(), Object::GetTypeId(), CreatureAI::m_creature, script_error_log(), TELE_TO_NOT_LEAVE_COMBAT, and TYPEID_PLAYER.
Referenced by boss_grandmaster_vorpilAI::DoTeleportToPlatform().
EnterCombat()
void ScriptedAI::EnterCombat (Unit * enemy) override virtual
This function only calls Aggro, which is to be used for scripting purposes.
Reimplemented from CreatureAI.
Reimplemented in boss_emerald_dragonAI, boss_tethyrAI, and boss_high_inquisitor_whitemaneAI.
Definition at line 36 of file sc_creature.cpp.
References Aggro(), and CreatureAI::EnterCombat().
Referenced by boss_tethyrAI::EnterCombat(), and boss_emerald_dragonAI::EnterCombat().
EnterEvadeMode()
void ScriptedAI::EnterEvadeMode () override virtual
This function cleans up the combat state if the creature evades It will:
Drop Auras
Drop all threat
Stop combat
Move the creature home
Clear tagging for loot
call Reset()
Reimplemented from UnitAI.
Reimplemented in npc_the_cleanerAI, npc_injured_patientAI, boss_alarAI, boss_warp_splinterAI, boss_soccothratesAI, boss_dalliahAI, npc_millhouse_manastormAI, npc_shivan_assassinAI, npc_spawned_oronok_tornheartAI, mob_shadowmoon_soulstealerAI, mob_torlothAI, npc_scrapped_fel_reaverAI, npc_manaforge_spawnAI, npc_maghar_escortAI, npc_magister_aledisAI, npc_anchorite_baradaAI, boss_magtheridonAI, boss_omor_the_unscarredAI, boss_vazrudenAI, boss_vazruden_heraldAI, boss_ahuneAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, boss_fathomguard_caribdisAI, boss_fathomguard_tidalvessAI, boss_fathomguard_sharkkisAI, npc_fel_cannon, boss_teron_gorefiendAI, npc_enslaved_soulAI, boss_essence_of_angerAI, essence_base_AI, boss_maievAI, boss_xevozzAI, boss_ichoronAI, boss_saraAI, boss_sifAI, boss_thorimAI, boss_vx001AI, boss_hodirAI, boss_freyaAI, mob_molten_golemAI, boss_uromAI, npc_tesla_coilAI, boss_nothAI, boss_kelthuzadAI, boss_heiganAI, boss_gothikAI, npc_spinestalker_iccAI, npc_rimefang_iccAI, boss_sindragosaAI, boss_deathbringer_saurfangAI, blood_prince_council_baseAI, npc_grand_admiral_westwindAI, npc_infantryAI, npc_living_mojoAI, boss_fjolaAI, npc_beast_combat_stalkerAI, boss_jaraxxusAI, npc_nexus_drake_hatchlingAI, boss_volazjAI, npc_disciple_of_naralexAI, npc_precious_the_devourerAI, npc_taskmaster_fizzuleAI, npc_anubisath_sentinelAI, boss_viscidusAI, OuroScarab, npc_ouro_moundAI, boss_cthunAI, npc_solenorAI, npc_kaldorei_eliteAI, npc_general_andorovAI, boss_ayamissAI, boss_eranikusAI, npc_thrall_old_hillsbradAI, hyjalAI, boss_archimondeAI, boss_azuregosAI, boss_thekalAI, boss_mandokirAI, boss_jeklikAI, boss_zuljinAI, boss_halazziAI, npc_tirion_fordringAI, npc_isillienAI, npc_taelan_fordringAI, boss_entropiusAI, boss_muruAI, boss_kiljaedenAI, boss_kalecgos_humanoidAI, boss_sathrovarrAI, boss_kalecgosAI, boss_felmystAI, boss_sacrolashAI, boss_alythessAI, boss_baroness_anastariAI, mob_yennikuAI, npc_spectral_tutorAI, boss_high_inquisitor_whitemaneAI, boss_scarlet_commander_mograineAI, npc_death_knight_initiateAI, boss_ragnarosAI, priestess_companion_commonAI, boss_felblood_kaelthasAI, npc_chess_piece_genericAI, boss_nightbaneAI, boss_netherspiteAI, boss_attumenAI, boss_midnightAI, boss_nefarianAI, and boss_coren_direbrewAI.
Definition at line 53 of file sc_creature.cpp.
References UnitAI::EnterEvadeMode(), and CreatureAI::Reset().
Referenced by npc_deathstalker_vincentAI::DamageTaken(), npc_dashel_stonefistAI::DamageTaken(), npc_tapoke_slim_jahnAI::DamageTaken(), npc_kaylaan_the_lostAI::DamageTaken(), argent_champion_commonAI::DamageTaken(), boss_algalonAI::DamageTaken(), npc_bartlebyAI::DamageTaken(), npc_private_hendelAI::DamageTaken(), npc_salsalabimAI::DamageTaken(), npc_eris_havenfireAI::DoBalanceEventEnd(), npc_tipsy_mcmanusAI::DoCheckDistillationTask(), npc_highlord_darion_mograineAI::DoStartConclusion(), boss_coren_direbrewAI::EnterEvadeMode(), boss_nefarianAI::EnterEvadeMode(), boss_midnightAI::EnterEvadeMode(), boss_attumenAI::EnterEvadeMode(), boss_netherspiteAI::EnterEvadeMode(), priestess_companion_commonAI::EnterEvadeMode(), boss_ragnarosAI::EnterEvadeMode(), npc_death_knight_initiateAI::EnterEvadeMode(), boss_scarlet_commander_mograineAI::EnterEvadeMode(), boss_high_inquisitor_whitemaneAI::EnterEvadeMode(), npc_spectral_tutorAI::EnterEvadeMode(), mob_yennikuAI::EnterEvadeMode(), boss_baroness_anastariAI::EnterEvadeMode(), boss_kalecgosAI::EnterEvadeMode(), boss_sathrovarrAI::EnterEvadeMode(), npc_taelan_fordringAI::EnterEvadeMode(), npc_isillienAI::EnterEvadeMode(), boss_halazziAI::EnterEvadeMode(), boss_zuljinAI::EnterEvadeMode(), boss_jeklikAI::EnterEvadeMode(), boss_mandokirAI::EnterEvadeMode(), boss_thekalAI::EnterEvadeMode(), boss_azuregosAI::EnterEvadeMode(), boss_archimondeAI::EnterEvadeMode(), npc_thrall_old_hillsbradAI::EnterEvadeMode(), boss_ayamissAI::EnterEvadeMode(), npc_solenorAI::EnterEvadeMode(), boss_cthunAI::EnterEvadeMode(), npc_ouro_moundAI::EnterEvadeMode(), OuroScarab::EnterEvadeMode(), boss_viscidusAI::EnterEvadeMode(), npc_anubisath_sentinelAI::EnterEvadeMode(), npc_taskmaster_fizzuleAI::EnterEvadeMode(), npc_precious_the_devourerAI::EnterEvadeMode(), npc_disciple_of_naralexAI::EnterEvadeMode(), boss_volazjAI::EnterEvadeMode(), boss_jaraxxusAI::EnterEvadeMode(), npc_living_mojoAI::EnterEvadeMode(), blood_prince_council_baseAI::EnterEvadeMode(), boss_deathbringer_saurfangAI::EnterEvadeMode(), boss_sindragosaAI::EnterEvadeMode(), boss_gothikAI::EnterEvadeMode(), boss_heiganAI::EnterEvadeMode(), boss_uromAI::EnterEvadeMode(), boss_saraAI::EnterEvadeMode(), boss_ichoronAI::EnterEvadeMode(), boss_xevozzAI::EnterEvadeMode(), boss_teron_gorefiendAI::EnterEvadeMode(), npc_fel_cannon::EnterEvadeMode(), boss_fathomguard_sharkkisAI::EnterEvadeMode(), boss_fathomguard_tidalvessAI::EnterEvadeMode(), boss_fathomguard_caribdisAI::EnterEvadeMode(), boss_leotheras_the_blindAI::EnterEvadeMode(), boss_ahuneAI::EnterEvadeMode(), boss_vazruden_heraldAI::EnterEvadeMode(), boss_vazrudenAI::EnterEvadeMode(), boss_omor_the_unscarredAI::EnterEvadeMode(), boss_magtheridonAI::EnterEvadeMode(), npc_anchorite_baradaAI::EnterEvadeMode(), mob_torlothAI::EnterEvadeMode(), npc_shivan_assassinAI::EnterEvadeMode(), boss_warp_splinterAI::EnterEvadeMode(), boss_alarAI::EnterEvadeMode(), npc_injured_patientAI::EnterEvadeMode(), npc_the_cleanerAI::EnterEvadeMode(), npc_bonechewer_brawler::ExecuteAction(), npc_bonechewer_combatant::ExecuteAction(), npc_lich_king_villageAI::JustDidDialogueStep(), npc_king_ymironAI::JustDidDialogueStep(), boss_algalonAI::JustDidDialogueStep(), boss_tethyrAI::KilledUnit(), dummy_dragonAI::MovementInform(), npc_dirty_larryAI::NextStep(), npc_corrupted_furbolgAI::npc_corrupted_furbolgAI(), boss_mr_smiteAI::PhaseEquipEnd(), npc_nexus_drake_hatchlingAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), mobs_spectral_ghostly_citizenAI::ReceiveEmote(), boss_razorscaleAI::SelectCustomHostileTarget(), mobs_nether_drakeAI::SpellHit(), npc_jaina_sylvanas_horAI::SpellHitTarget(), boss_brutallusAI::SpellHitTarget(), npc_deathstalker_vincentAI::UpdateAI(), npc_scourged_flamespitterAI::UpdateAI(), npc_calvin_montagueAI::UpdateAI(), boss_archaedasAI::UpdateAI(), npc_plucky_johnsonAI::UpdateAI(), npc_silvermoon_harryAI::UpdateAI(), npc_tipsy_mcmanusAI::UpdateAI(), npc_dark_matterAI::UpdateAI(), npc_bloodmaul_dire_wolfAI::UpdateAI(), npc_fel_cannon::UpdateAI(), boss_warchief_kargath_bladefistAI::UpdateAI(), mob_lumpAI::UpdateAI(), npc_void_conduitAI::UpdateAI(), npc_domesticated_felboarAI::UpdateAI(), mob_unkor_the_ruthlessAI::UpdateAI(), npc_chicken_cluckAI::UpdateAI(), npc_redemption_targetAI::UpdateAI(), npc_garments_of_questsAI::UpdateEscortAI(), and npc_commanderAI::WinEvent().
GetAIInformation()
void ScriptedAI::GetAIInformation (ChatHandler & reader) override virtual
This function shows if combat movement is enabled, overwrite for more info.
Reimplemented from UnitAI.
Reimplemented in boss_kaelthasAI, npc_commanderAI, npc_simon_game_bunnyAI, boss_illidan_stormrageAI, npc_anubisath_sentinelAI, npc_arthasAI, boss_kiljaedenAI, boss_brutallusAI, mob_arugal_voidwalkerAI, npc_highlord_darion_mograineAI, boss_thermapluggAI, and Scripted_NoMovementAI.
Definition at line 28 of file sc_creature.cpp.
References ChatHandler::GetOnOffStr(), UnitAI::IsCombatMovement(), and ChatHandler::PSendSysMessage().
Referenced by npc_escortAI::GetAIInformation(), npc_highlord_darion_mograineAI::GetAIInformation(), and npc_commanderAI::GetAIInformation().
GetAIName()
std::string ScriptedAI::GetAIName () inline override protected virtual
Reimplemented from UnitAI.
Definition at line 204 of file sc_creature.h.
References Creature::GetAIName(), and CreatureAI::m_creature.
GetPlayerAtMinimumRange()
Player * ScriptedAI::GetPlayerAtMinimumRange (float minimumRange) const
Definition at line 329 of file sc_creature.cpp.
References CreatureAI::m_creature, and Cell::VisitWorldObjects().
JustRespawned()
void ScriptedAI::JustRespawned () override virtual
This will by default result in reattacking, if the creature has no victim.
This function calls Reset() to reset variables as expected.
Reimplemented from UnitAI.
Reimplemented in SilithusBossAI, npc_shade_of_the_horsemanAI, GossipNPCAI, npc_imp_in_a_ball, mob_phoenix_tkAI, npc_fire_nova_totemAI, npc_shaman_elementalAI, npc_ethereum_prisonerAI, boss_highlord_kruulAI, npc_kayra_longmaneAI, npc_minion_of_terokkAI, npc_avatar_of_terokkAI, npc_skyguard_prisonerAI, NetherCharge, npc_nether_vaporAI, StunField, npc_spawned_oronok_tornheartAI, mob_shadowmoon_soulstealerAI, npc_shadowlord_deathwailAI, mob_torlothAI, mob_enslaved_netherwing_drakeAI, npc_scrapped_fel_reaverAI, npc_salhadaarAI, npc_captured_vanguardAI, npc_rethhedronAI, npc_nagrand_captiveAI, npc_vindicator_sedaiAI, npc_wounded_blood_elfAI, boss_kelidan_the_breakerAI, mob_underbog_mushroomAI, npc_serpentshrine_parasiteAI, mob_water_globuleAI, npc_inner_demonAI, npc_caribdis_cyclone, boss_doomwalkerAI, boss_doomlordkazzakAI, npc_evergrove_druidAI, npc_soulgrinderAI, npc_frequency_scanner, npc_bird_spiritAI, npc_shadow_constructAI, npc_doom_blossomAI, boss_shade_of_akamaAI, npc_enslaved_soulAI, npc_parasitic_shadowfiendAI, npc_shadow_demonAI, npc_akama_illidanAI, boss_illidan_stormrageAI, npc_grand_collectorAI, npc_disruptor_towerAI, dummy_blackheart_the_inciterAI, boss_anzuAI, npc_ethereum_prisoner_dungeonAI, boss_yorAI, npc_decaying_ghoulAI, boss_kelesethAI, npc_brann_hosAI, boss_thaddiusAddsAI, npc_web_wrapAI, boss_forgemaster_garfrostAI, npc_corrupted_soul_fragmentAI, boss_bronjahmAI, npc_infantryAI, npc_nerubian_burrowerAI, npc_proudhoofAI, npc_nexus_drake_hatchlingAI, npc_disciple_of_naralexAI, boss_skeramAI, OuroScarab, npc_ouro_moundAI, boss_ouroAI, npc_ouro_triggerAI, npc_general_andorovAI, npc_smolderwing, npc_morokkAI, npc_magrami_spectre, npc_rabid_bearAI, npc_theryluneAI, npc_thrall_old_hillsbradAI, hyjalAI, boss_rage_winterchillAI, boss_kazrogalAI, boss_azgalorAI, boss_archimondeAI, boss_anetheronAI, npc_soulflayerAI, boss_renatakiAI, npc_zulian_prowlerAI, npc_feather_vortexAI, npc_corrupted_lightning_totemAI, mob_soaring_eagleAI, npc_singularityAI, npc_darknessAI, boss_kiljaedenAI, boss_felmystAI, npc_shadow_imageAI, mobs_spectral_ghostly_citizenAI, boss_apothecary_hummelAI, boss_high_inquisitor_whitemaneAI, boss_headless_horsemanAI, boss_majordomoAI, npc_kalecgosAI, mob_fel_crystalAI, boss_selin_fireheartAI, npc_ellrys_duskhallowAI, boss_terestianAI, boss_nightbaneAI, npc_dawnblade_blood_knight, npc_shattered_sun_fighterAI, npc_rinjiAI, npc_ranger_lilathaAI, npc_apprentice_mirvedaAI, boss_kazzakAI, boss_nefarianAI, boss_kaelthasAI, npc_regthar_deathgateAI, and npc_demonic_vaporAI.
Definition at line 60 of file sc_creature.cpp.
References CreatureAI::Reset().
Referenced by npc_demonic_vaporAI::JustRespawned(), boss_kaelthasAI::JustRespawned(), boss_nefarianAI::JustRespawned(), npc_apprentice_mirvedaAI::JustRespawned(), npc_ranger_lilathaAI::JustRespawned(), npc_rinjiAI::JustRespawned(), npc_dawnblade_blood_knight::JustRespawned(), boss_nightbaneAI::JustRespawned(), npc_ellrys_duskhallowAI::JustRespawned(), npc_kalecgosAI::JustRespawned(), boss_headless_horsemanAI::JustRespawned(), boss_high_inquisitor_whitemaneAI::JustRespawned(), boss_apothecary_hummelAI::JustRespawned(), mobs_spectral_ghostly_citizenAI::JustRespawned(), npc_shadow_imageAI::JustRespawned(), boss_felmystAI::JustRespawned(), boss_kiljaedenAI::JustRespawned(), npc_darknessAI::JustRespawned(), npc_singularityAI::JustRespawned(), npc_zulian_prowlerAI::JustRespawned(), boss_renatakiAI::JustRespawned(), boss_anetheronAI::JustRespawned(), boss_archimondeAI::JustRespawned(), boss_azgalorAI::JustRespawned(), boss_kazrogalAI::JustRespawned(), boss_rage_winterchillAI::JustRespawned(), hyjalAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_theryluneAI::JustRespawned(), npc_morokkAI::JustRespawned(), boss_ouroAI::JustRespawned(), npc_ouro_moundAI::JustRespawned(), OuroScarab::JustRespawned(), boss_skeramAI::JustRespawned(), npc_disciple_of_naralexAI::JustRespawned(), npc_nexus_drake_hatchlingAI::JustRespawned(), npc_nerubian_burrowerAI::JustRespawned(), npc_disruptor_towerAI::JustRespawned(), boss_illidan_stormrageAI::JustRespawned(), npc_akama_illidanAI::JustRespawned(), npc_shadow_demonAI::JustRespawned(), npc_parasitic_shadowfiendAI::JustRespawned(), boss_shade_of_akamaAI::JustRespawned(), npc_caribdis_cyclone::JustRespawned(), mob_water_globuleAI::JustRespawned(), mob_underbog_mushroomAI::JustRespawned(), boss_kelidan_the_breakerAI::JustRespawned(), npc_rethhedronAI::JustRespawned(), npc_scrapped_fel_reaverAI::JustRespawned(), mob_enslaved_netherwing_drakeAI::JustRespawned(), mob_torlothAI::JustRespawned(), npc_nether_vaporAI::JustRespawned(), npc_shaman_elementalAI::JustRespawned(), GossipNPCAI::JustRespawned(), and SilithusBossAI::JustRespawned().
ReceiveAIEvent()
void ScriptedAI::ReceiveAIEvent (AIEventType , Unit * , Unit * , uint32) inline override virtual
Called when an AI Event is received.
Parameters
eventType to specify the event, default cases listed in enum AIEventType
pSender Creature that sent this event
pInvoker Unit that triggered this event (like an attacker)
Reimplemented from UnitAI.
Reimplemented in hyjalAI, boss_rimefang_posAI, npc_tirion_fordringAI, npc_isillienAI, npc_dawnblade_blood_knight, npc_headless_horseman_fireAI, npc_xiri, npc_bt_battle_sensor, npc_adyen_the_lightwardenAI, npc_evergrove_druidAI, npc_akamaAI, boss_ichoronAI, boss_galdarahAI, mob_core_ragerAI, npc_shattered_sun_marksmanAI, npc_prison_event_controllerAI, npc_halion_controllerAI, mob_soaring_eagleAI, npc_domesticated_felboarAI, npc_nazgrelAI, npc_danath_trollbaneAI, npc_champion_mountAI, trial_companion_commonAI, npc_highlord_darion_mograineAI, mob_big_oozeAI, npc_emilyAI, npc_arthasAI, npc_demolitionist_legosoAI, npc_supplicantAI, npc_graufAI, boss_skadiAI, boss_general_vezaxAI, npc_power_sparkAI, boss_crusader_warlockAI, boss_crusader_priest_shadowAI, boss_crusader_shaman_restoAI, boss_crusader_priest_discAI, boss_crusader_paladin_holyAI, boss_crusader_druid_restoAI, boss_ingvarAI, npc_brann_hosAI, boss_varosAI, npc_infantryAI, npc_anchorite_baradaAI, npc_decaying_ghoulAI, npc_ghoul_feeding_bunnyAI, npc_keeper_mimironAI, boss_heart_deconstructorAI, boss_xt_002AI, boss_sifAI, npc_razorscale_spawnerAI, npc_expedition_commanderAI, boss_razorscaleAI, boss_kologarnAI, npc_living_constellationAI, boss_algalonAI, mob_tenebronAI, boss_malygosAI, npc_king_ymironAI, boss_crusader_rogueAI, boss_crusader_paladin_retriAI, boss_crusader_warriorAI, boss_crusader_death_knightAI, boss_crusader_mageAI, boss_crusader_hunterAI, boss_crusader_druid_balanceAI, boss_black_knightAI, npc_nexus_drake_hatchlingAI, npc_kerlonianAI, boss_kalecgosAI, npc_valentine_boss_managerAI, boss_head_of_horsemanAI, boss_headless_horsemanAI, npc_death_knight_initiateAI, npc_chess_piece_genericAI, npc_netherspite_portalAI, npc_fhwoorAI, npc_skyguard_prisonerAI, npc_drijyaAI, npc_nagrand_captiveAI, npc_simon_game_bunnyAI, npc_shaheenAI, npc_brain_yogg_saronAI, npc_voice_yogg_saronAI, boss_yogg_saronAI, npc_injured_minerAI, npc_tipsy_mcmanusAI, npc_grand_admiral_westwindAI, npc_father_kamarosAI, npc_squad_leaderAI, npc_apothecary_hanesAI, npc_harrison_jonesAI, npc_proudhoofAI, npc_mootoo_the_youngerAI, npc_bonker_togglevoltAI, npc_shay_leafrunnerAI, npc_areiAI, npc_captured_arkonarinAI, npc_stinky_ignatzAI, npc_tapoke_slim_jahnAI, npc_anchorite_truuenAI, npc_dorius_stonetenderAI, npc_corporal_keeshan_escortAI, npc_kernobeeAI, npc_kineloryAI, boss_alarAI, mob_shadowmoon_channelerAI, boss_leotheras_the_blindAI, boss_lady_vashjAI, npc_bonechewer_brawler, npc_anubarak_trial_spikeAI, boss_ossirianAI, boss_renatakiAI, boss_mandokirAI, boss_akilzonAI, npc_sinister_reflectionAI, boss_sathrovarrAI, boss_arugalAI, boss_bigbadwolfAI, boss_coren_direbrewAI, npc_dreadmawAI, npc_eye_of_shartuulAI, npc_shivan_assassinAI, npc_doomguard_punisherAI, ScourgeMinion, npc_cultist_engineer, boss_silithidRoyaltyAI, npc_amanishi_hatcherAI, npc_taelan_fordringAI, boss_selin_fireheartAI, npc_orphan_matronAI, mob_phoenix_tkAI, boss_kaelthasAI, npc_lord_illidan_stormrageAI, npc_energy_ballAI, npc_salhadaarAI, npc_manaforge_control_consoleAI, npc_shattered_hand_legionnaire, boss_magtheridonAI, boss_vazruden_heraldAI, npc_ice_spear_bunnyAI, boss_terokkAI, npc_spirit_prisoner_of_bladespire, npc_bloodmaul_dire_wolfAI, mob_blood_elf_council_voice_triggerAI, boss_teron_gorefiendAI, boss_supremusAI, npc_creature_generatorAI, boss_reliquary_of_soulsAI, npc_shadow_demonAI, npc_akama_illidanAI, npc_skyguard_aether_techAI, boss_murmurAI, boss_ambassador_hellmawAI, boss_anzuAI, npc_teleportation_portalAI, boss_aerial_unitAI, boss_vx001AI, boss_leviathan_mk2AI, boss_mimironAI, boss_freyaAI, boss_halion_twilightAI, boss_halion_realAI, boss_professor_putricideAI, boss_lady_deathwhisperAI, twin_jormungars_commonAI, boss_taldaramAI, boss_viscidusAI, boss_cthunAI, npc_general_andorovAI, npc_major_mills, boss_arlokkAI, npc_amanishi_scoutAI, npc_ashliAI, npc_krazAI, npc_tanzarAI, npc_harkorAI, npc_amanishi_lookoutAI, npc_harrison_jones_zaAI, boss_janalaiAI, boss_muruAI, boss_kiljaedenAI, boss_sacrolashAI, boss_alythessAI, boss_shazzrahAI, mob_pure_energyAI, boss_aranAI, boss_moroesAI, boss_razorgoreAI, boss_pyroguard_emberseerAI, npc_spirit_guideAI, npc_charged_sphereAI, npc_descent_madnessAI, npc_bot_triggerAI, boss_lich_king_horAI, MouthAI, boss_maievAI, boss_illidan_stormrageAI, npc_skyguard_rangerAI, npc_anzu_bird_spiritAI, boss_telestraAI, boss_zuljinAI, boss_malacrassAI, and boss_felblood_kaelthasAI.
Definition at line 137 of file sc_creature.h.
SelectSpell()
SpellEntry const * ScriptedAI::SelectSpell (Unit * target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
Definition at line 100 of file sc_creature.cpp.
References Unit::GetCharmSpells(), Unit::GetPower(), GetSpellRangeStore(), GetSpellStore(), Object::HasFlag(), WorldObject::IsWithinDistInMap(), SQLStorage::LookupEntry(), CreatureAI::m_creature, UnitAI::m_unit, SpellEntry::manaCost, SpellRangeEntry::maxRange, SpellEntry::Mechanic, SpellRangeEntry::minRange, SpellEntry::powerType, SpellEntry::rangeIndex, SpellEntry::SchoolMask, SpellSummary, UNIT_FIELD_FLAGS, UNIT_FLAG_SILENCED, and urand().
Referenced by guardAI::UpdateAI(), and generic_creatureAI::UpdateAI().
SetEquipmentSlots()
void ScriptedAI::SetEquipmentSlots (bool loadDefault, int32 mainHand = EQUIP_NO_CHANGE, int32 offHand = EQUIP_NO_CHANGE, int32 ranged = EQUIP_NO_CHANGE)
Definition at line 341 of file sc_creature.cpp.
References BASE_ATTACK, CreatureInfo::EquipmentTemplateId, Creature::GetCreatureInfo(), Creature::hasWeapon(), Creature::LoadEquipment(), CreatureAI::m_creature, OFF_ATTACK, RANGED_ATTACK, Creature::SetCanDualWield(), Creature::SetVirtualItem(), Creature::UpdateDamagePhysical(), VIRTUAL_ITEM_SLOT_0, VIRTUAL_ITEM_SLOT_1, and VIRTUAL_ITEM_SLOT_2.
Referenced by boss_malchezaarAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_ingvarAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_illidan_stormrageAI::HandlePhaseBehaviour(), boss_zuljinAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), npc_highlord_darion_mograineAI::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), boss_ingvarAI::JustReachedHome(), npc_thrall_old_hillsbradAI::JustRespawned(), boss_mr_smiteAI::MovementInform(), boss_mr_smiteAI::PhaseEquipProcess(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_black_knightAI::ReceiveAIEvent(), boss_mr_smiteAI::Reset(), boss_malchezaarAI::Reset(), boss_zuljinAI::Reset(), npc_thrall_old_hillsbradAI::Reset(), boss_black_knightAI::Reset(), npc_grand_admiral_westwindAI::Reset(), npc_dragonmaw_peonAI::Reset(), boss_dathrohan_balnazzarAI::UpdateAI(), npc_grand_admiral_westwindAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), npc_daphne_stilwellAI::WaypointReached(), and npc_thrall_old_hillsbradAI::WaypointReached().
Field Documentation
m_uiEvadeCheckCooldown
uint32 ScriptedAI::m_uiEvadeCheckCooldown private
Definition at line 207 of file sc_creature.h.
The documentation for this struct was generated from the following files:
sc_creature.h
sc_creature.cpp