CMaNGOS_WoTLK: go_manticron_cubeAI Struct Reference
go_manticron_cubeAI Struct Reference
Public Member Functions
go_manticron_cubeAI (GameObject *go)
void SetManticronCubeUser (ObjectGuid user)
Player * GetManticronCubeLastUser () const
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void UpdateAI (const uint32)
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
ObjectGuid m_lastUser
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 399 of file boss_magtheridon.cpp.
Constructor & Destructor Documentation
go_manticron_cubeAI()
go_manticron_cubeAI::go_manticron_cubeAI (GameObject * go) inline
Definition at line 401 of file boss_magtheridon.cpp.
Member Function Documentation
GetManticronCubeLastUser()
Player* go_manticron_cubeAI::GetManticronCubeLastUser () const inline
Definition at line 406 of file boss_magtheridon.cpp.
References WorldObject::GetMap(), Map::GetPlayer(), GameObjectAI::m_go, and m_lastUser.
Referenced by GOUse_go_manticron_cube().
SetManticronCubeUser()
void go_manticron_cubeAI::SetManticronCubeUser (ObjectGuid user) inline
Definition at line 405 of file boss_magtheridon.cpp.
References m_lastUser.
Field Documentation
m_lastUser
ObjectGuid go_manticron_cubeAI::m_lastUser
Definition at line 403 of file boss_magtheridon.cpp.
Referenced by GetManticronCubeLastUser(), and SetManticronCubeUser().
The documentation for this struct was generated from the following file:
boss_magtheridon.cpp