CMaNGOS_WoTLK: spell_assemble_cage Struct Reference
spell_assemble_cage Struct Reference
Public Member Functions
SpellCastResult OnCheckCast (Spell *spell, bool) const override
void OnEffectExecute (Spell *spell, SpellEffectIndex effIdx) const override
Public Member Functions inherited from SpellScript
virtual ~SpellScript ()=default
virtual void OnInit (Spell *) const
virtual void OnSuccessfulStart (Spell *) const
virtual void OnSuccessfulFinish (Spell *) const
virtual void OnSpellCastResultOverride (SpellCastResult &, uint32 &, uint32 &) const
virtual void OnRadiusCalculate (Spell *, SpellEffectIndex, bool, float &) const
virtual void OnDestTarget (Spell *) const
virtual bool OnCheckTarget (const Spell *, GameObject *, SpellEffectIndex) const
virtual bool OnCheckTarget (const Spell *, Unit *, SpellEffectIndex) const
virtual void OnCast (Spell *) const
virtual void OnHit (Spell *, SpellMissInfo) const
virtual void OnAfterHit (Spell *) const
virtual void OnSummon (Spell *, Creature *) const
virtual void OnSummon (Spell *, GameObject *) const
virtual uint32 GetPhaseMaskOverride (Spell *) const
Detailed Description
Definition at line 670 of file grizzly_hills.cpp.
Member Function Documentation
OnCheckCast()
SpellCastResult spell_assemble_cage::OnCheckCast (Spell * spell, bool) const inline override virtual
Reimplemented from SpellScript.
Definition at line 672 of file grizzly_hills.cpp.
References SpellCastTargets::getUnitTarget(), Unit::HasAura(), Spell::m_targets, SPELL_CAST_OK, and SPELL_FAILED_BAD_TARGETS.
OnEffectExecute()
void spell_assemble_cage::OnEffectExecute (Spell * spell, SpellEffectIndex effIdx) const inline override virtual
Reimplemented from SpellScript.
Definition at line 684 of file grizzly_hills.cpp.
References Unit::AI(), Unit::CastSpell(), UnitAI::ClearCombatOnlyRoot(), Unit::CombatStopWithPets(), EFFECT_INDEX_0, Creature::ForcedDespawn(), Spell::GetUnitTarget(), Object::IsCreature(), Unit::RemoveAllAurasOnEvade(), Unit::SetImmuneToNPC(), Unit::SetImmuneToPlayer(), and TRIGGERED_OLD_TRIGGERED.
The documentation for this struct was generated from the following file:
grizzly_hills.cpp