CMaNGOS_WoTLK: SpellRankHelper< EntryType, WorkerType, StorageType > Struct Template Reference
SpellRankHelper< EntryType, WorkerType, StorageType > Struct Template Reference
Public Member Functions
SpellRankHelper (SpellMgr &_mgr, StorageType &_storage)
void RecordRank (EntryType &entry, uint32 spell_id)
void FillHigherRanks ()
Data Fields
std::set< uint32 > firstRankSpells
std::set< uint32 > firstRankSpellsWithCustomRanks
SpellMgr & mgr
WorkerType worker
uint32 customRank
Detailed Description
template<typename EntryType, typename WorkerType, typename StorageType>
struct SpellRankHelper< EntryType, WorkerType, StorageType >
Definition at line 654 of file SpellMgr.cpp.
Constructor & Destructor Documentation
SpellRankHelper()
template<typename EntryType , typename WorkerType , typename StorageType > SpellRankHelper< EntryType, WorkerType, StorageType >::SpellRankHelper (SpellMgr & _mgr, StorageType & _storage) inline
Definition at line 656 of file SpellMgr.cpp.
Member Function Documentation
FillHigherRanks()
template<typename EntryType , typename WorkerType , typename StorageType > void SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks () inline
Definition at line 685 of file SpellMgr.cpp.
References SpellMgr::doForHighRanks(), SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpells, SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpellsWithCustomRanks, SpellRankHelper< EntryType, WorkerType, StorageType >::mgr, sLog, and SpellRankHelper< EntryType, WorkerType, StorageType >::worker.
Referenced by SpellMgr::LoadSpellProcEvents(), and SpellMgr::LoadSpellThreats().
RecordRank()
template<typename EntryType , typename WorkerType , typename StorageType > void SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank (EntryType & entry, uint32 spell_id) inline
Definition at line 657 of file SpellMgr.cpp.
References SpellRankHelper< EntryType, WorkerType, StorageType >::customRank, SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpells, SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpellsWithCustomRanks, SpellMgr::GetFirstSpellInChain(), SQLStorage::LookupEntry(), SpellRankHelper< EntryType, WorkerType, StorageType >::mgr, sLog, sSpellTemplate, and SpellRankHelper< EntryType, WorkerType, StorageType >::worker.
Referenced by SpellMgr::LoadSpellProcEvents(), and SpellMgr::LoadSpellThreats().
Field Documentation
customRank
template<typename EntryType , typename WorkerType , typename StorageType > uint32 SpellRankHelper< EntryType, WorkerType, StorageType >::customRank
Definition at line 704 of file SpellMgr.cpp.
Referenced by SpellMgr::LoadSpellProcEvents(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
firstRankSpells
template<typename EntryType , typename WorkerType , typename StorageType > std::set<uint32> SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpells
Definition at line 699 of file SpellMgr.cpp.
Referenced by SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
firstRankSpellsWithCustomRanks
template<typename EntryType , typename WorkerType , typename StorageType > std::set<uint32> SpellRankHelper< EntryType, WorkerType, StorageType >::firstRankSpellsWithCustomRanks
Definition at line 700 of file SpellMgr.cpp.
Referenced by SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
mgr
template<typename EntryType , typename WorkerType , typename StorageType > SpellMgr& SpellRankHelper< EntryType, WorkerType, StorageType >::mgr
Definition at line 702 of file SpellMgr.cpp.
Referenced by SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
worker
template<typename EntryType , typename WorkerType , typename StorageType > WorkerType SpellRankHelper< EntryType, WorkerType, StorageType >::worker
Definition at line 703 of file SpellMgr.cpp.
Referenced by SpellRankHelper< EntryType, WorkerType, StorageType >::FillHigherRanks(), SpellMgr::LoadSpellProcEvents(), SpellMgr::LoadSpellThreats(), and SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank().
The documentation for this struct was generated from the following file:
SpellMgr.cpp