CMaNGOS_WoTLK: MaNGOS::PlayerVisitObjectsNotifier Struct Reference
MaNGOS::PlayerVisitObjectsNotifier Struct Reference
#include <GridNotifiers.h>
Public Member Functions
PlayerVisitObjectsNotifier (Player &pl)
template<class T >
void Visit (GridRefManager< T > &)
template<>
void Visit (PlayerMapType &)
template<>
void Visit (CreatureMapType &)
Data Fields
Player & i_player
Detailed Description
Definition at line 145 of file GridNotifiers.h.
Constructor & Destructor Documentation
PlayerVisitObjectsNotifier()
MaNGOS::PlayerVisitObjectsNotifier::PlayerVisitObjectsNotifier (Player & pl) inline
Definition at line 148 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/3]
template<> void MaNGOS::PlayerVisitObjectsNotifier::Visit (CreatureMapType & m) inline
Definition at line 104 of file GridNotifiersImpl.h.
References Unit::IsAlive(), and UnitVisitObjectsNotifierWorker().
Visit() [2/3]
template<class T > void MaNGOS::PlayerVisitObjectsNotifier::Visit (GridRefManager< T > &) inline
Definition at line 149 of file GridNotifiers.h.
Visit() [3/3]
template<> void MaNGOS::PlayerVisitObjectsNotifier::Visit (PlayerMapType & m) inline
Definition at line 125 of file GridNotifiersImpl.h.
References Player::AI(), Unit::IsAlive(), Unit::IsTaxiFlying(), and UnitVisitObjectsNotifierWorker().
Field Documentation
i_player
Player& MaNGOS::PlayerVisitObjectsNotifier::i_player
Definition at line 147 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h