CMaNGOS_WoTLK: MaNGOS::WorldObjectWorker< Do > Struct Template Reference
MaNGOS::WorldObjectWorker< Do > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectWorker (WorldObject const *searcher, Do const &_do)
void Visit (GameObjectMapType &m)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
Do const & i_do
Detailed Description
template<class Do>
struct MaNGOS::WorldObjectWorker< Do >
Definition at line 257 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectWorker()
template<class Do > MaNGOS::WorldObjectWorker< Do >::WorldObjectWorker (WorldObject const * searcher, Do const & _do) inline
Definition at line 262 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/6]
template<class Do > void MaNGOS::WorldObjectWorker< Do >::Visit (CorpseMapType & m) inline
Definition at line 285 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), MaNGOS::WorldObjectWorker< Do >::i_do, and MaNGOS::WorldObjectWorker< Do >::i_phaseMask.
Visit() [2/6]
template<class Do > void MaNGOS::WorldObjectWorker< Do >::Visit (CreatureMapType & m) inline
Definition at line 278 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), MaNGOS::WorldObjectWorker< Do >::i_do, and MaNGOS::WorldObjectWorker< Do >::i_phaseMask.
Visit() [3/6]
template<class Do > void MaNGOS::WorldObjectWorker< Do >::Visit (DynamicObjectMapType & m) inline
Definition at line 292 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), MaNGOS::WorldObjectWorker< Do >::i_do, and MaNGOS::WorldObjectWorker< Do >::i_phaseMask.
Visit() [4/6]
template<class Do > void MaNGOS::WorldObjectWorker< Do >::Visit (GameObjectMapType & m) inline
Definition at line 265 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), MaNGOS::WorldObjectWorker< Do >::i_do, and MaNGOS::WorldObjectWorker< Do >::i_phaseMask.
Visit() [5/6]
template<class Do > template<class NOT_INTERESTED > void MaNGOS::WorldObjectWorker< Do >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 299 of file GridNotifiers.h.
Visit() [6/6]
template<class Do > void MaNGOS::WorldObjectWorker< Do >::Visit (PlayerMapType & m) inline
Definition at line 272 of file GridNotifiers.h.
References GridRefManager< OBJECT >::begin(), GridRefManager< OBJECT >::end(), MaNGOS::WorldObjectWorker< Do >::i_do, and MaNGOS::WorldObjectWorker< Do >::i_phaseMask.
Field Documentation
i_do
template<class Do > Do const& MaNGOS::WorldObjectWorker< Do >::i_do
Definition at line 260 of file GridNotifiers.h.
Referenced by MaNGOS::WorldObjectWorker< Do >::Visit().
i_phaseMask
template<class Do > uint32 MaNGOS::WorldObjectWorker< Do >::i_phaseMask
Definition at line 259 of file GridNotifiers.h.
Referenced by MaNGOS::WorldObjectWorker< Do >::Visit().
The documentation for this struct was generated from the following file:
GridNotifiers.h