CMaNGOS_WoTLK: WorldObjectChangeAccumulator Struct Reference
WorldObjectChangeAccumulator Struct Reference
Public Member Functions
WorldObjectChangeAccumulator (WorldObject &obj, UpdateDataMapType &d)
void Visit (CameraMapType &m)
template<class SKIP >
void Visit (GridRefManager< SKIP > &)
Data Fields
UpdateDataMapType & i_updateDatas
WorldObject & i_object
Detailed Description
Definition at line 2655 of file Object.cpp.
Constructor & Destructor Documentation
WorldObjectChangeAccumulator()
WorldObjectChangeAccumulator::WorldObjectChangeAccumulator (WorldObject & obj, UpdateDataMapType & d) inline
Definition at line 2659 of file Object.cpp.
References Object::BuildUpdateDataForPlayer(), i_object, i_updateDatas, Object::isType(), and TYPEMASK_PLAYER.
Member Function Documentation
Visit() [1/2]
void WorldObjectChangeAccumulator::Visit (CameraMapType & m) inline
Definition at line 2667 of file Object.cpp.
References Object::BuildUpdateDataForPlayer(), Unit::GetOwner(), Player::HasAtClient(), i_object, and i_updateDatas.
Visit() [2/2]
template<class SKIP > void WorldObjectChangeAccumulator::Visit (GridRefManager< SKIP > &) inline
Definition at line 2677 of file Object.cpp.
Field Documentation
i_object
WorldObject& WorldObjectChangeAccumulator::i_object
Definition at line 2658 of file Object.cpp.
Referenced by Visit(), and WorldObjectChangeAccumulator().
i_updateDatas
UpdateDataMapType& WorldObjectChangeAccumulator::i_updateDatas
Definition at line 2657 of file Object.cpp.
Referenced by Visit(), and WorldObjectChangeAccumulator().
The documentation for this struct was generated from the following file:
Object.cpp