CMaNGOS_WoTLK: boss_aeonusAI Struct Reference
boss_aeonusAI Struct Reference
Public Member Functions
boss_aeonusAI (Creature *pCreature)
void Reset () override
void Aggro (Unit *) override
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void MoveInLineOfSight (Unit *pWho) override
== Reactions At =================================
void JustDied (Unit *) override
Called when the creature is killed.
void KilledUnit (Unit *) override
Called when the creature kills a unit.
void UpdateAI (const uint32 uiDiff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void ReceiveAIEvent (AIEventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void JustReachedHome ()
Called at reaching home after MoveTargetedHome.
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void CorpseRemoved (uint32 &)
Called when the corpse of this creature gets removed.
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (Creature *)
Called when the creature summon successfully other creature.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void MovementInform (uint32, uint32)
Called at waypoint reached or point movement finished.
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual bool AssistPlayerInCombat (Unit *)
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual uint32 GetCurrentWaypointPath () const
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Data Fields
ScriptedInstance * m_pInstance
bool m_bIsRegularMode
uint32 m_uiSandBreathTimer
uint32 m_uiTimeStopTimer
uint32 m_uiFrenzyTimer
uint32 m_uiCleaveTimer
Additional Inherited Members
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Detailed Description
Definition at line 46 of file boss_aeonus.cpp.
Constructor & Destructor Documentation
boss_aeonusAI()
boss_aeonusAI::boss_aeonusAI (Creature * pCreature) inline
Definition at line 48 of file boss_aeonus.cpp.
References WorldObject::GetInstanceData(), WorldObject::GetMap(), Map::IsRegularDifficulty(), m_bIsRegularMode, m_pInstance, and Reset().
Member Function Documentation
Aggro()
void boss_aeonusAI::Aggro (Unit *) inline override virtual
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
Called at creature EnterCombat with an enemy This is a SD2 internal function Called by default on creature EnterCombat with an enemy
Reimplemented from ScriptedAI.
Definition at line 73 of file boss_aeonus.cpp.
References DoScriptText(), CreatureAI::m_creature, and SAY_AGGRO.
JustDied()
void boss_aeonusAI::JustDied (Unit *) inline override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from UnitAI.
Definition at line 93 of file boss_aeonus.cpp.
References DoScriptText(), CreatureAI::m_creature, and SAY_DEATH.
KilledUnit()
void boss_aeonusAI::KilledUnit (Unit *) inline override virtual
Called when the creature kills a unit.
Parameters
pVictim Victim that got killed
Reimplemented from UnitAI.
Definition at line 98 of file boss_aeonus.cpp.
References DoScriptText(), CreatureAI::m_creature, SAY_SLAY1, SAY_SLAY2, and urand().
MoveInLineOfSight()
void boss_aeonusAI::MoveInLineOfSight (Unit * who) inline override virtual
== Reactions At =================================
Called if IsVisible(Unit* pWho) is true at each (relative) override pWho move, reaction at visibility zone enter Note: The Unit* pWho can be out of Line of Sight, usually this is only visibiliy (by state) and range dependendend Note: This function is not called for creatures who are in evade mode
Parameters
pWho Unit* who moved in the visibility range and is visisble
Reimplemented from UnitAI.
Definition at line 78 of file boss_aeonus.cpp.
References CAST_OK, UnitAI::DoCastSpellIfCan(), DoScriptText(), Object::GetEntry(), Object::GetTypeId(), WorldObject::IsWithinDistInMap(), CreatureAI::m_creature, UnitAI::MoveInLineOfSight(), NPC_TIME_KEEPER, SAY_BANISH, SPELL_BANISH_HELPER, and TYPEID_UNIT.
Reset()
void boss_aeonusAI::Reset () inline override virtual
Reimplemented from CreatureAI.
Definition at line 63 of file boss_aeonus.cpp.
References CAST_AURA_NOT_PRESENT, CAST_TRIGGERED, UnitAI::DoCastSpellIfCan(), m_bIsRegularMode, CreatureAI::m_creature, m_uiCleaveTimer, m_uiFrenzyTimer, m_uiSandBreathTimer, m_uiTimeStopTimer, SPELL_DOUBLE_ATTACK, SPELL_THRASH, and urand().
Referenced by boss_aeonusAI().
UpdateAI()
void boss_aeonusAI::UpdateAI (const uint32 diff) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented from UnitAI.
Definition at line 103 of file boss_aeonus.cpp.
References CAST_OK, UnitAI::DoCastSpellIfCan(), UnitAI::DoMeleeAttackIfReady(), DoScriptText(), EMOTE_GENERIC_FRENZY, Unit::GetVictim(), m_bIsRegularMode, CreatureAI::m_creature, m_uiCleaveTimer, m_uiFrenzyTimer, m_uiSandBreathTimer, m_uiTimeStopTimer, Unit::SelectHostileTarget(), SPELL_CLEAVE, SPELL_ENRAGE, SPELL_SAND_BREATH, SPELL_SAND_BREATH_H, SPELL_TIME_STOP, and urand().
Field Documentation
m_bIsRegularMode
bool boss_aeonusAI::m_bIsRegularMode
Definition at line 56 of file boss_aeonus.cpp.
Referenced by boss_aeonusAI(), Reset(), and UpdateAI().
m_pInstance
ScriptedInstance* boss_aeonusAI::m_pInstance
Definition at line 55 of file boss_aeonus.cpp.
Referenced by boss_aeonusAI().
m_uiCleaveTimer
uint32 boss_aeonusAI::m_uiCleaveTimer
Definition at line 61 of file boss_aeonus.cpp.
Referenced by Reset(), and UpdateAI().
m_uiFrenzyTimer
uint32 boss_aeonusAI::m_uiFrenzyTimer
Definition at line 60 of file boss_aeonus.cpp.
Referenced by Reset(), and UpdateAI().
m_uiSandBreathTimer
uint32 boss_aeonusAI::m_uiSandBreathTimer
Definition at line 58 of file boss_aeonus.cpp.
Referenced by Reset(), and UpdateAI().
m_uiTimeStopTimer
uint32 boss_aeonusAI::m_uiTimeStopTimer
Definition at line 59 of file boss_aeonus.cpp.
Referenced by Reset(), and UpdateAI().
The documentation for this struct was generated from the following file:
boss_aeonus.cpp