CMaNGOS_WoTLK: go_brewfest_music Struct Reference
go_brewfest_music Struct Reference
Public Member Functions
go_brewfest_music (GameObject *go)
Team GetZoneAlignment (GameObject *go) const
void PlayAllianceMusic ()
void PlayHordeMusic ()
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Public Member Functions inherited from GameObjectAI
GameObjectAI (GameObject *go)
virtual ~GameObjectAI ()
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnLootStateChange (Unit *)
Called when the GO has its state changed in GameObject::SetLootState (whatever the reason is) LootState to which the GO is changed to is accessible in the GameObjectAI through GetLootState() User can be nullptr.
virtual void OnGoStateChange (GOState)
virtual void JustSpawned ()
virtual void JustDespawned ()
virtual void ReceiveAIEvent (AIEventType, uint32=0)
virtual void OnUse (Unit *, SpellEntry const *)
virtual void OnHeartbeat ()
virtual void JustReachedStopPoint ()
Data Fields
Team m_zoneTeam
int32 m_musicSelectTimer
int32 m_musicStartTimer
uint32 m_rand
Additional Inherited Members
Protected Attributes inherited from GameObjectAI
GameObject * m_go
Detailed Description
Definition at line 652 of file go_scripts.cpp.
Constructor & Destructor Documentation
go_brewfest_music()
go_brewfest_music::go_brewfest_music (GameObject * go) inline
Definition at line 654 of file go_scripts.cpp.
References m_musicSelectTimer, and m_musicStartTimer.
Member Function Documentation
GetZoneAlignment()
Team go_brewfest_music::GetZoneAlignment (GameObject * go) const inline
Definition at line 665 of file go_scripts.cpp.
References ALLIANCE, DARNASSUS, EXODAR, WorldObject::GetAreaId(), HORDE, IRONFORGE_1, IRONFORGE_2, ORGRIMMAR_1, ORGRIMMAR_2, SHATTRATH, SILVERMOON, STORMWIND, TEAM_NONE, THUNDERBLUFF, and UNDERCITY.
PlayAllianceMusic()
void go_brewfest_music::PlayAllianceMusic () inline
Definition at line 687 of file go_scripts.cpp.
References EVENT_BREWFESTDWARF01, EVENT_BREWFESTDWARF02, EVENT_BREWFESTDWARF03, GameObjectAI::m_go, m_rand, and WorldObject::PlayMusic().
Referenced by UpdateAI().
PlayHordeMusic()
void go_brewfest_music::PlayHordeMusic () inline
Definition at line 703 of file go_scripts.cpp.
References EVENT_BREWFESTGOBLIN01, EVENT_BREWFESTGOBLIN02, EVENT_BREWFESTGOBLIN03, GameObjectAI::m_go, m_rand, and WorldObject::PlayMusic().
Referenced by UpdateAI().
UpdateAI()
void go_brewfest_music::UpdateAI (const uint32 uint32) inline override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers.
Parameters
uiDiff Passed time since last call
Reimplemented from GameObjectAI.
Definition at line 719 of file go_scripts.cpp.
References ALLIANCE, Map::ExecuteDistWorker(), WorldObject::GetMap(), WorldObject::GetVisibilityData(), VisibilityData::GetVisibilityDistance(), HOLIDAY_BREWFEST, HORDE, IsHolidayActive(), GameObjectAI::m_go, m_musicSelectTimer, m_musicStartTimer, m_rand, m_zoneTeam, PlayAllianceMusic(), PlayHordeMusic(), TEAM_NONE, and urand().
Field Documentation
m_musicSelectTimer
int32 go_brewfest_music::m_musicSelectTimer
Definition at line 661 of file go_scripts.cpp.
Referenced by go_brewfest_music(), and UpdateAI().
m_musicStartTimer
int32 go_brewfest_music::m_musicStartTimer
Definition at line 662 of file go_scripts.cpp.
Referenced by go_brewfest_music(), and UpdateAI().
m_rand
uint32 go_brewfest_music::m_rand
Definition at line 663 of file go_scripts.cpp.
Referenced by PlayAllianceMusic(), PlayHordeMusic(), and UpdateAI().
m_zoneTeam
Team go_brewfest_music::m_zoneTeam
Definition at line 660 of file go_scripts.cpp.
Referenced by UpdateAI().
The documentation for this struct was generated from the following file:
go_scripts.cpp