CMaNGOS_WoTLK: npc_escortAI Struct Reference
npc_escortAI Struct Reference abstract
#include <escort_ai.h>
Public Member Functions
npc_escortAI (Creature *creature)
~npc_escortAI ()
void GetAIInformation (ChatHandler &reader) override
== Information about AI ========================
virtual void Aggro (Unit *who) override
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
void JustDied (Unit *killer) override
Called when the creature is killed.
void CorpseRemoved (uint32 &) override
Called when the corpse of this creature gets removed.
void UpdateAI (const uint32 diff) override
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
virtual void UpdateEscortAI (const uint32 diff)
void MovementInform (uint32 moveType, uint32 pointId) override
Called at waypoint reached or point movement finished.
virtual void WaypointReached (uint32 pointId)=0
virtual void WaypointStart (uint32)
void Start (bool run=false, const Player *player=nullptr, const Quest *quest=nullptr, bool instantRespawn=false, bool canLoopPath=false, uint32 waypointPath=0)
void End ()
void SetRun (bool run=true)
void SetEscortPaused (bool paused)
bool HasEscortState (uint32 escortState) const
void SetCurrentWaypoint (uint32 pointId)
void FailQuestForPlayerAndGroup ()
bool AssistPlayerInCombat (Unit *who) override
uint32 GetCurrentWaypointPath () const override
Public Member Functions inherited from ScriptedAI
ScriptedAI (Creature *creature, uint32 combatActions)
ScriptedAI (Creature *creature)
~ScriptedAI ()
void GetAIInformation (ChatHandler &reader) override
This function shows if combat movement is enabled, overwrite for more info.
void EnterCombat (Unit *enemy) override
This function only calls Aggro, which is to be used for scripting purposes.
void EnterEvadeMode () override
This function cleans up the combat state if the creature evades It will:
void JustRespawned () override
This will by default result in reattacking, if the creature has no victim.
void ReceiveAIEvent (AIEventType, Unit *, Unit *, uint32) override
Called when an AI Event is received.
void DoStartMovement (Unit *victim)
void DoStartNoMovement (Unit *victim)
void DoStopAttack ()
void DoPlaySoundToSet (WorldObject *source, uint32 soundId)
void DoTeleportPlayer (Unit *unit, float x, float y, float z, float ori)
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat)
Player * GetPlayerAtMinimumRange (float minimumRange) const
SpellEntry const * SelectSpell (Unit *target, int32 school, int32 mechanic, SelectTarget selectTargets, uint32 powerCostMin, uint32 powerCostMax, float rangeMin, float rangeMax, SelectEffect selectEffects)
bool CanCast (Unit *target, SpellEntry const *spellInfo, bool triggered=false)
void SetEquipmentSlots (bool loadDefault, int32 mainHand=EQUIP_NO_CHANGE, int32 offHand=EQUIP_NO_CHANGE, int32 ranged=EQUIP_NO_CHANGE)
Public Member Functions inherited from CreatureAI
CreatureAI (Creature *creature)
CreatureAI (Creature *creature, uint32 combatActions)
virtual void Reset ()
virtual void OnRemoveFromWorld ()
virtual void AttackStart (Unit *who) override
== Triggered Actions Requested ==================
virtual void DamageTaken (Unit *dealer, uint32 &damage, DamageEffectType damageType, SpellEntry const *spellInfo) override
Called at any Damage from any attacker (before damage apply) Note: Use for recalculation damage or special reaction at damage for attack reaction use AttackedBy called for not DOT damage in Unit::DealDamage also.
virtual void JustPreventedDeath (Unit *)
void DoFakeDeath (uint32 spellId=0)
void SetDeathPrevention (bool state)
void ResetDeathPrevented ()
void AttackPassengersIfCan (Unit *who)
Helper function which handles the combat reaction for vehicle passengers.
bool DoRetreat () override
void DoCallForHelp (float radius) override
void RetreatingArrived () override
void RetreatingEnded () override
void HandleAssistanceCall (Unit *sender, Unit *invoker) override
void AddUnreachabilityCheck ()
CreatureSpellList const & GetSpellList () const
void TimedFleeingEnded () override
void OnCallForHelp (Unit *enemy) override
virtual void RequestFollow (Unit *followee) override
virtual void RelinquishFollow (ObjectGuid follower) override
Public Member Functions inherited from UnitAI
UnitAI (Unit *unit)
UnitAI (Unit *unit, uint32 combatActions)
virtual ~UnitAI ()
virtual void MoveInLineOfSight (Unit *)
== Reactions At =================================
virtual void JustReachedHome ()
Called at reaching home after MoveTargetedHome.
virtual void SummonedJustReachedHome (Creature *)
Called at reaching home after MoveTargetedHome.
virtual void HealedBy (Unit *, uint32 &)
Called at any Heal received from any Unit.
virtual void DamageDeal (Unit *, uint32 &, DamageEffectType, SpellEntry const *)
Called at any Damage to any victim (before damage apply)
virtual void SummonedCreatureJustDied (Creature *)
Called when a summoned creature is killed.
virtual void KilledUnit (Unit *)
Called when the creature kills a unit.
virtual void OwnerKilledUnit (Unit *)
Called when owner of m_creature (if m_creature is PROTECTOR_PET) kills a unit.
virtual void JustSummoned (Creature *)
Called when the creature summon successfully other creature.
virtual void JustSummoned (GameObject *)
Called when the creature summon successfully a gameobject.
virtual void SummonedCreatureDespawn (Creature *)
Called when a summoned creature gets TemporarySummon::UnSummon ed.
virtual void SpellHit (Unit *, const SpellEntry *)
Called when hit by a spell.
virtual void SpellHitTarget (Unit *target, const SpellEntry *spellInfo, SpellMissInfo)
Called when spell hits creature's target.
virtual void SpellHitTarget (Unit *, const SpellEntry *)
virtual void AttackedBy (Unit *attacker)
Called when the creature is target of hostile action: swing, hostile spell landed, fear/etc)
virtual void SummonedMovementInform (Creature *, uint32, uint32)
Called if a temporary summoned of m_creature reach a move point.
virtual void ReceiveEmote (Player *, uint32)
Called at text emote receive from player.
virtual uint32 GetScriptData ()
== Data Fetch bind ==============================
virtual void CombatStop ()
Called when creature stop attack expected Note: have to be called to reinitialize some states or movement Note: Not needed for creature, they use EnterEvadeMode.
virtual bool IsVisible (Unit *) const
== State checks =================================
bool DoMeleeAttackIfReady () const
Check if this AI can be replaced in possess case.
CanCastResult CanCastSpell (Unit *target, const SpellEntry *spellInfo, bool isTriggered) const
Internal helper function, to check if a spell can be cast.
virtual CanCastResult DoCastSpellIfCan (Unit *target, uint32 spellId, uint32 castFlags=0)
Function to cast a spell if possible.
void SetCombatMovement (bool enable, bool stopOrStartMovement=false)
Set combat movement (on/off), also sets UNIT_STAT_NO_COMBAT_MOVEMENT.
bool IsCombatMovement () const
void SetFollowMovement (bool enable)
void SendAIEventAround (AIEventType eventType, Unit *invoker, uint32 delay, float radius, uint32 miscValue=0) const
== Event Handling ===============================
void SendAIEvent (AIEventType eventType, Unit *invoker, Unit *receiver, uint32 miscValue=0) const
Send an AI Event to a Creature.
virtual void OnEventHappened (uint16, bool, bool)
Called when a Game Event starts or ends.
virtual void OnSpellCastStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnChannelStateChange (Spell const *spell, bool state, WorldObject *target=nullptr)
virtual void OnSpellCast (SpellEntry const *, Unit *)
virtual void OnStealthAlert (Unit *who)
virtual void OnLeash ()
virtual void OnHeartbeat ()
virtual void OnUnsummon ()
void CheckForHelp (Unit *, Unit *, float)
void DetectOrAttack (Unit *who)
bool CanTriggerStealthAlert (Unit *who, float attackRadius) const
virtual void HandleMovementOnAttackStart (Unit *victim, bool targetChange) const
uint32 GetAttackDistance ()
void SetMoveChaseParams (float dist, float angle, bool moveFurther)
Unit * DoSelectLowestHpFriendly (float range, float minMissing=1.f, bool percent=false, bool targetSelf=true) const
Unit * DoSelectConditionalFriendly (float range, int32 unitConditionId) const
float CalculateSpellRange (SpellEntry const *spellInfo) const
CreatureList DoFindFriendlyEligibleDispel (uint32 spellId, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (SpellEntry const *spellInfo, bool self=true) const
CreatureList DoFindFriendlyEligibleDispel (float range, uint32 dispelMask=0, uint32 mechanicMask=0, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (float range, uint32 spellId, bool inCombat, bool self=true) const
CreatureList DoFindFriendlyMissingBuff (SpellEntry const *spellInfo, bool inCombat, bool self=true) const
void DoStartMovement (Unit *victim)
void SetReactState (ReactStates st)
ReactStates GetReactState () const
bool HasReactState (ReactStates state) const
virtual bool CanExecuteCombatAction ()
bool CanCastSpell ()
void SetCombatScriptStatus (bool state)
bool GetCombatScriptStatus () const
void SetAIOrder (AIOrders order)
AIOrders GetAIOrder () const
bool DoFlee (uint32 duration=0)
void DoDistance ()
void DoResetThreat ()
void SetMeleeEnabled (bool state)
virtual void JustRootedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual void JustStunnedTarget (SpellEntry const *spellInfo, Unit *victim)
virtual bool CanHandleCharm ()
virtual void JustGotCharmed (Unit *charmer)
virtual void JumpingEnded ()
void AttackSpecificEnemy (std::function< void(Unit *, Unit *&)> check)
virtual void AttackClosestEnemy ()
void SetAIImmobilizedState (bool apply, bool combatOnly=false)
void ClearCombatOnlyRoot ()
virtual void HandleDelayedInstantAnimation (SpellEntry const *)
virtual bool IsTargetingRestricted ()
virtual void OnTaunt ()
virtual bool IsPreventingDeath () const
bool IsMeleeEnabled () const
virtual void UpdateEventTimers (const uint32)
virtual void ExecuteActions ()
virtual void ExecuteAction (uint32)
void AddMainSpell (uint32 spellId)
void AddDistanceSpell (uint32 spellId)
void SetRangedMode (bool state, float distance, RangeModeType type)
void SetCurrentRangedMode (bool state)
bool GetCurrentRangedMode ()
virtual void JustStoppedMovementOfTarget (SpellEntry const *spell, Unit *victim)
virtual void OnSpellInterrupt (SpellEntry const *spellInfo)
virtual void OnSpellCooldownAdded (SpellEntry const *spellInfo)
virtual void DistancingStarted ()
virtual void DistancingEnded ()
void DistanceYourself ()
CanCastResult HandleSpellCastResult (CanCastResult result, SpellEntry const *spellInfo)
bool IsRangedUnit ()
SpellSchoolMask GetMainAttackSchoolMask () const
bool IsMainSpellPrevented (SpellEntry const *spellInfo) const
bool IsEligibleForDistancing () const
void SpellListChanged ()
void UpdateSpellLists ()
std::pair< bool, Unit * > ChooseTarget (CreatureSpellListTargeting *targetData, uint32 spellId) const
void AddInitialCooldowns ()
virtual void CreatureGroupMemberDied (Unit *)
Public Member Functions inherited from CombatActions
CombatActions (uint32 maxCombatActions)
void AddCombatAction (uint32 id, bool disabled)
void AddCombatAction (uint32 id, uint32 timer)
void AddCombatAction (uint32 id, std::chrono::milliseconds timer)
void AddCombatAction (uint32 id, uint32 timerMin, uint32 timerMax)
void AddCombatAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax)
void AddTimerlessCombatAction (uint32 id, bool byDefault)
virtual void ResetTimer (uint32 index, uint32 timer) override
virtual void ResetTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DisableTimer (uint32 index) override
virtual void ReduceTimer (uint32 index, uint32 timer) override
virtual void ReduceTimer (uint32 index, std::chrono::milliseconds timer)
virtual void DelayTimer (uint32 index, uint32 timer) override
virtual void DelayTimer (uint32 index, std::chrono::milliseconds timer)
virtual void ResetIfNotStarted (uint32 index, uint32 timer) override
virtual void ResetIfNotStarted (uint32 index, std::chrono::milliseconds timer)
void DisableCombatAction (uint32 index)
void ResetCombatAction (uint32 index, uint32 timer)
void ResetCombatAction (uint32 index, std::chrono::milliseconds timer)
void DelayCombatAction (uint32 index, uint32 timer)
void DelayCombatAction (uint32 index, std::chrono::milliseconds timer)
void SetActionReadyStatus (uint32 index, bool state)
bool GetActionReadyStatus (uint32 index)
virtual void UpdateTimers (const uint32 diff, bool combat) override
virtual void ResetAllTimers () override
size_t GetCombatActionCount ()
Public Member Functions inherited from TimerManager
TimerManager ()
void AddCustomAction (uint32 id, bool disabled, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timer, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, uint32 timerMin, uint32 timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
void AddCustomAction (uint32 id, std::chrono::milliseconds timerMin, std::chrono::milliseconds timerMax, std::function< void()> functor, TimerCombat timerCombat=TIMER_ALWAYS)
virtual void UpdateTimers (const uint32 diff)
Protected Member Functions
Player * GetPlayerForEscort () const
bool IsSD2EscortMovement (uint32 moveType) const
Helper function for transition between old Escort Movment and using WaypointMMGen.
virtual void JustStartedEscort ()
void SetEscortWaypoints (uint32 pathId)
Protected Member Functions inherited from ScriptedAI
std::string GetAIName () override
Protected Member Functions inherited from UnitAI
void DespawnGuids (GuidVector &spawns)
Protected Member Functions inherited from TimerManager
void AddTimer (uint32 id, Timer &&timer)
Protected Attributes
const Quest * m_questForEscort
Protected Attributes inherited from CreatureAI
Creature * m_creature
bool m_deathPrevented
float m_followAngle
float m_followDist
ObjectGuid m_requestedFollower
Protected Attributes inherited from UnitAI
Unit * m_unit
== Fields =======================================
float m_attackDistance
How should an enemy be chased.
float m_attackAngle
bool m_moveFurther
bool m_chaseRun
float m_visibilityDistance
bool m_combatMovementStarted
bool m_dismountOnAggro
bool m_meleeEnabled
bool m_combatOnlyRoot
ReactStates m_reactState
bool m_combatScriptHappening
AIOrders m_currentAIOrder
Spell const * m_currentSpell
bool m_teleportUnreachable
bool m_rangedMode
RangeModeType m_rangedModeSetting
float m_chaseDistance
bool m_currentRangedMode
std::unordered_set< uint32 > m_mainSpells
std::unordered_set< uint32 > m_distanceSpells
uint32 m_mainSpellId
uint32 m_mainSpellCost
SpellEntry const * m_mainSpellInfo
float m_mainSpellMinRange
SpellSchoolMask m_mainAttackMask
bool m_distancingCooldown
bool m_spellListCooldown
Private Member Functions
bool IsPlayerOrGroupInRange ()
void AddEscortState (uint32 escortState)
void RemoveEscortState (uint32 escortState)
Private Attributes
ObjectGuid m_playerGuid
uint32 m_playerCheckTimer
uint32 m_escortState
bool m_isRunning
bool m_canInstantRespawn
bool m_canReturnToStart
uint32 m_waypointPathID
uint32 m_currentEscortWaypointPath
Detailed Description
Definition at line 19 of file escort_ai.h.
Constructor & Destructor Documentation
npc_escortAI()
npc_escortAI::npc_escortAI (Creature * creature) explicit
Definition at line 19 of file escort_ai.cpp.
~npc_escortAI()
npc_escortAI::~npc_escortAI () inline
Definition at line 23 of file escort_ai.h.
Member Function Documentation
AddEscortState()
void npc_escortAI::AddEscortState (uint32 escortState) inline private
Definition at line 71 of file escort_ai.h.
References m_escortState.
Referenced by SetEscortPaused(), and Start().
Aggro()
void npc_escortAI::Aggro (Unit *) override virtual
This is a SD2 internal function, that every AI must implement Usally used to reset combat variables Called by default on creature evade and respawn In most scripts also called in the constructor of the AI.
Called at creature EnterCombat with an enemy This is a SD2 internal function Called by default on creature EnterCombat with an enemy
Reimplemented from ScriptedAI.
Reimplemented in npc_defias_traitorAI, npc_galen_goodwardAI, npc_deathstalker_erlandAI, npc_letollAI, npc_squad_leaderAI, npc_ame01AI, npc_giltharesAI, npc_willix_the_importerAI, npc_areiAI, npc_captured_arkonarinAI, npc_stinky_ignatzAI, npc_prospector_remtravelAI, npc_dorius_stonetenderAI, npc_rinjiAI, npc_00x09hlAI, npc_marshal_windsorAI, npc_kineloryAI, npc_wildaAI, npc_protectorate_demolitionistAI, npc_father_kamarosAI, npc_proudhoofAI, npc_bonker_togglevoltAI, npc_oox17tnAI, npc_clintar_dw_spiritAI, npc_oox22feAI, npc_volcorAI, npc_thrall_old_hillsbradAI, npc_arthasAI, npc_magwinAI, npc_muglashAI, example_escortAI, npc_tapoke_slim_jahnAI, npc_daphne_stilwellAI, npc_tirion_fordringAI, npc_taelan_fordringAI, npc_reginald_windsorAI, npc_grark_lorkrubAI, npc_hurley_blackbreathAI, npc_phalanxAI, and npc_professor_phizzlethorpeAI.
Definition at line 52 of file escort_ai.cpp.
AssistPlayerInCombat()
bool npc_escortAI::AssistPlayerInCombat (Unit * who) override virtual
Reimplemented from UnitAI.
Definition at line 55 of file escort_ai.cpp.
References CreatureAI::AttackStart(), Unit::CanAttackNow(), CREATURE_TYPEFLAGS_CAN_ASSIST, CreatureInfo::CreatureTypeFlags, Unit::EngageInCombatWith(), Unit::GetBeneficiaryPlayer(), Creature::GetCreatureInfo(), Unit::GetVictim(), HasEscortState(), Unit::hasUnitState(), WorldObject::IsWithinDistInMap(), WorldObject::IsWithinLOSInMap(), CreatureAI::m_creature, MAX_PLAYER_DISTANCE, STATE_ESCORT_ESCORTING, UNIT_STAT_CONFUSED, UNIT_STAT_FEIGN_DEATH, UNIT_STAT_FLEEING, and UNIT_STAT_STUNNED.
CorpseRemoved()
void npc_escortAI::CorpseRemoved (uint32 &) override virtual
Called when the corpse of this creature gets removed.
Parameters
uiRespawnDelay Delay (in seconds). If != 0, then this is the time after which the creature will respawn, if = 0 the default respawn-delay will be used
Reimplemented from UnitAI.
Reimplemented in npc_thrall_old_hillsbradAI.
Definition at line 112 of file escort_ai.cpp.
References UnitAI::IsCombatMovement(), m_escortState, UnitAI::SetCombatMovement(), and STATE_ESCORT_NONE.
Referenced by npc_thrall_old_hillsbradAI::CorpseRemoved().
End()
void npc_escortAI::End ()
Definition at line 299 of file escort_ai.cpp.
References m_playerGuid, m_questForEscort, RemoveEscortState(), and STATE_ESCORT_ESCORTING.
Referenced by npc_dorius_stonetenderAI::SpellHit(), npc_cork_gizeltonAI::WaypointReached(), and npc_captured_arkonarinAI::WaypointReached().
FailQuestForPlayerAndGroup()
void npc_escortAI::FailQuestForPlayerAndGroup ()
Definition at line 103 of file escort_ai.cpp.
References GetPlayerForEscort(), Quest::GetQuestId(), and m_questForEscort.
Referenced by JustDied(), npc_morokkAI::JustReachedHome(), npc_ranshallaAI::SpellHit(), and UpdateAI().
GetAIInformation()
void npc_escortAI::GetAIInformation (ChatHandler &) override virtual
== Information about AI ========================
This funcion is used to display information about the AI. It is called when the .npc aiinfo command is used. Use this for on-the-fly debugging
Parameters
reader is a ChatHandler to send messages to.
Reimplemented from UnitAI.
Reimplemented in npc_arthasAI.
Definition at line 31 of file escort_ai.cpp.
References ScriptedAI::GetAIInformation(), Unit::GetMotionMaster(), Quest::GetQuestId(), ObjectGuid::GetString(), MotionMaster::GetWaypointPathInformation(), HasEscortState(), CreatureAI::m_creature, m_playerGuid, m_questForEscort, ChatHandler::PSendSysMessage(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, and STATE_ESCORT_RETURNING.
GetCurrentWaypointPath()
uint32 npc_escortAI::GetCurrentWaypointPath () const inline override virtual
Reimplemented from UnitAI.
Definition at line 57 of file escort_ai.h.
References m_currentEscortWaypointPath.
GetPlayerForEscort()
Player* npc_escortAI::GetPlayerForEscort () const inline protected
Definition at line 60 of file escort_ai.h.
References WorldObject::GetMap(), Map::GetPlayer(), CreatureAI::m_creature, and m_playerGuid.
Referenced by example_escortAI::Aggro(), npc_muglashAI::Aggro(), npc_father_kamarosAI::Aggro(), npc_areiAI::Aggro(), npc_ame01AI::Aggro(), npc_keeper_remulosAI::DoHandleOutro(), FailQuestForPlayerAndGroup(), IsPlayerOrGroupInRange(), npc_squire_roweAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_grark_lorkrubAI::JustDidDialogueStep(), npc_tapoke_slim_jahnAI::JustDidDialogueStep(), npc_demolitionist_legosoAI::JustDidDialogueStep(), npc_melizza_brimbuzzleAI::JustDidDialogueStep(), npc_areiAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), example_escortAI::JustDied(), npc_tapoke_slim_jahnAI::JustReachedHome(), npc_injured_rainspeakerAI::JustStartedEscort(), npc_grark_lorkrubAI::JustSummoned(), npc_tapoke_slim_jahnAI::JustSummoned(), npc_wildaAI::JustSummoned(), npc_letollAI::JustSummoned(), npc_cork_gizeltonAI::MakeQuestFailAndClean(), npc_khadgars_servantAI::MoveInLineOfSight(), npc_dorius_stonetenderAI::SpellHit(), npc_saeed_escortAI::UpdateAI(), npc_khadgars_servantAI::UpdateEscortAI(), npc_rinjiAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_wizzlecranks_shredderAI::UpdateEscortAI(), npc_lurgglbrAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), npc_morokkAI::UpdateEscortAI(), npc_ranger_lilathaAI::WaypointReached(), npc_deathstalker_erlandAI::WaypointReached(), npc_oox22feAI::WaypointReached(), npc_clintar_dw_spiritAI::WaypointReached(), npc_oox17tnAI::WaypointReached(), npc_kayra_longmaneAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_daphne_stilwellAI::WaypointReached(), npc_defias_traitorAI::WaypointReached(), npc_ruul_snowhoofAI::WaypointReached(), npc_cork_gizeltonAI::WaypointReached(), npc_keeper_remulosAI::WaypointReached(), npc_maxx_a_million_escortAI::WaypointReached(), npc_saeed_escortAI::WaypointReached(), npc_professor_phizzlethorpeAI::WaypointReached(), npc_kineloryAI::WaypointReached(), npc_marshal_windsorAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_prospector_anvilwardAI::WaypointReached(), npc_00x09hlAI::WaypointReached(), npc_rinjiAI::WaypointReached(), npc_miranAI::WaypointReached(), npc_dorius_stonetenderAI::WaypointReached(), npc_anchorite_truuenAI::WaypointReached(), npc_tapoke_slim_jahnAI::WaypointReached(), npc_muglashAI::WaypointReached(), npc_torekAI::WaypointReached(), npc_feero_ironhandAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_prospector_remtravelAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_theryluneAI::WaypointReached(), npc_dalinda_malemAI::WaypointReached(), npc_melizza_brimbuzzleAI::WaypointReached(), npc_stinky_ignatzAI::WaypointReached(), npc_captured_arkonarinAI::WaypointReached(), npc_willix_the_importerAI::WaypointReached(), npc_kayaAI::WaypointReached(), npc_custodian_of_timeAI::WaypointReached(), npc_giltharesAI::WaypointReached(), npc_wizzlecranks_shredderAI::WaypointReached(), npc_kanatiAI::WaypointReached(), npc_lakota_windsongAI::WaypointReached(), npc_paoka_swiftmountainAI::WaypointReached(), npc_ame01AI::WaypointReached(), npc_lurgglbrAI::WaypointReached(), npc_bonker_togglevoltAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_proudhoofAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_apothecary_hanesAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_father_kamarosAI::WaypointReached(), npc_heliceAI::WaypointReached(), npc_injured_rainspeakerAI::WaypointReached(), npc_injured_minerAI::WaypointReached(), npc_shaheenAI::WaypointReached(), npc_wounded_blood_elfAI::WaypointReached(), npc_nagrand_captiveAI::WaypointReached(), npc_bessyAI::WaypointReached(), npc_protectorate_demolitionistAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), npc_drijyaAI::WaypointReached(), npc_wildaAI::WaypointReached(), npc_akunoAI::WaypointReached(), npc_letollAI::WaypointReached(), npc_isla_starmaneAI::WaypointReached(), npc_skywingAI::WaypointReached(), npc_skyguard_prisonerAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), npc_corporal_keeshan_escortAI::WaypointReached(), example_escortAI::WaypointReached(), npc_wizzlecranks_shredderAI::WaypointStart(), and npc_lurgglbrAI::WaypointStart().
HasEscortState()
bool npc_escortAI::HasEscortState (uint32 escortState) const inline
Definition at line 48 of file escort_ai.h.
References m_escortState.
Referenced by npc_grark_lorkrubAI::Aggro(), npc_tapoke_slim_jahnAI::Aggro(), example_escortAI::Aggro(), npc_muglashAI::Aggro(), npc_rinjiAI::Aggro(), npc_galen_goodwardAI::Aggro(), AssistPlayerInCombat(), npc_belnistraszAI::AttackedBy(), npc_tapoke_slim_jahnAI::DamageTaken(), npc_clintar_dw_spiritAI::DoStart(), npc_thrall_old_hillsbradAI::EnterEvadeMode(), GetAIInformation(), JustDied(), example_escortAI::JustDied(), npc_daphne_stilwellAI::JustReachedHome(), npc_morokkAI::JustReachedHome(), npc_ranger_lilathaAI::MoveInLineOfSight(), npc_rizzle_sprysprocketAI::MoveInLineOfSight(), npc_grark_lorkrubAI::MoveInLineOfSight(), npc_ogronAI::MoveInLineOfSight(), npc_custodian_of_timeAI::MoveInLineOfSight(), npc_protectorate_demolitionistAI::MoveInLineOfSight(), MovementInform(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_phalanxAI::Reset(), npc_rocknotAI::Reset(), npc_marshal_windsorAI::Reset(), npc_hurley_blackbreathAI::Reset(), npc_grark_lorkrubAI::Reset(), npc_ranger_lilathaAI::Reset(), npc_blastmaster_emi_shortfuseAI::Reset(), npc_00x09hlAI::Reset(), npc_miranAI::Reset(), npc_dorius_stonetenderAI::Reset(), npc_daphne_stilwellAI::Reset(), npc_tapoke_slim_jahnAI::Reset(), npc_muglashAI::Reset(), npc_feero_ironhandAI::Reset(), npc_magwinAI::Reset(), npc_thrall_old_hillsbradAI::Reset(), npc_volcorAI::Reset(), npc_ogronAI::Reset(), npc_captured_arkonarinAI::Reset(), npc_oox22feAI::Reset(), npc_clintar_dw_spiritAI::Reset(), npc_keeper_remulosAI::Reset(), npc_oox17tnAI::Reset(), npc_wizzlecranks_shredderAI::Reset(), npc_disciple_of_naralexAI::Reset(), npc_lurgglbrAI::Reset(), npc_mootoo_the_youngerAI::Reset(), npc_maxx_a_million_escortAI::Reset(), npc_protectorate_demolitionistAI::Reset(), npc_drijyaAI::Reset(), npc_saeed_escortAI::Reset(), npc_isla_starmaneAI::Reset(), npc_skywingAI::Reset(), SetCurrentWaypoint(), SetEscortPaused(), Start(), npc_squire_roweAI::SummonedMovementInform(), UpdateAI(), npc_galen_goodwardAI::UpdateEscortAI(), npc_khadgars_servantAI::UpdateEscortAI(), npc_rinjiAI::UpdateEscortAI(), example_escortAI::UpdateEscortAI(), npc_muglashAI::UpdateEscortAI(), npc_rizzle_sprysprocketAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_morokkAI::UpdateEscortAI(), and npc_cork_gizeltonAI::WaypointReached().
IsPlayerOrGroupInRange()
bool npc_escortAI::IsPlayerOrGroupInRange () private
Definition at line 120 of file escort_ai.cpp.
References GetPlayerForEscort().
Referenced by UpdateAI().
IsSD2EscortMovement()
bool npc_escortAI::IsSD2EscortMovement (uint32 moveType) const protected
Helper function for transition between old Escort Movment and using WaypointMMGen.
Definition at line 177 of file escort_ai.cpp.
References EXTERNAL_WAYPOINT_MOVE.
Referenced by MovementInform().
JustDied()
void npc_escortAI::JustDied (Unit *) override virtual
Called when the creature is killed.
Parameters
pKiller Unit* who killed the creature
Reimplemented from UnitAI.
Reimplemented in npc_harrison_jonesAI, npc_oox17tnAI, npc_oox22feAI, example_escortAI, npc_00x09hlAI, npc_captured_vanguardAI, npc_keeper_remulosAI, npc_daphne_stilwellAI, npc_thrall_old_hillsbradAI, npc_arthasAI, and npc_blastmaster_emi_shortfuseAI.
Definition at line 95 of file escort_ai.cpp.
References FailQuestForPlayerAndGroup(), HasEscortState(), m_playerGuid, m_questForEscort, and STATE_ESCORT_ESCORTING.
Referenced by npc_daphne_stilwellAI::JustDied(), npc_keeper_remulosAI::JustDied(), npc_captured_vanguardAI::JustDied(), npc_00x09hlAI::JustDied(), example_escortAI::JustDied(), npc_oox22feAI::JustDied(), npc_oox17tnAI::JustDied(), npc_harrison_jonesAI::JustDied(), npc_emilyAI::ReceiveAIEvent(), and npc_tapoke_slim_jahnAI::WaypointReached().
JustStartedEscort()
virtual void npc_escortAI::JustStartedEscort () inline protected virtual
Reimplemented in npc_isla_starmaneAI, npc_letollAI, npc_injured_rainspeakerAI, npc_lurgglbrAI, npc_disciple_of_naralexAI, npc_melizza_brimbuzzleAI, and npc_dalinda_malemAI.
Definition at line 62 of file escort_ai.h.
Referenced by Start().
MovementInform()
void npc_escortAI::MovementInform (uint32 , uint32) override virtual
Called at waypoint reached or point movement finished.
Parameters
uiMovementType Type of the movement (enum MovementGeneratorType)
uiData Data related to the finished movement (ie point-id)
Reimplemented from UnitAI.
Reimplemented in npc_arthasAI, and npc_tirion_fordringAI.
Definition at line 182 of file escort_ai.cpp.
References EXTERNAL_WAYPOINT_FINISHED_LAST, EXTERNAL_WAYPOINT_MOVE_START, Creature::ForcedDespawn(), HasEscortState(), IsSD2EscortMovement(), JUST_DIED, m_canInstantRespawn, CreatureAI::m_creature, Creature::Respawn(), Creature::SetDeathState(), STATE_ESCORT_ESCORTING, WaypointReached(), and WaypointStart().
Referenced by npc_tirion_fordringAI::MovementInform(), and npc_arthasAI::MovementInform().
RemoveEscortState()
void npc_escortAI::RemoveEscortState (uint32 escortState) inline private
Definition at line 72 of file escort_ai.h.
References m_escortState.
Referenced by End(), and SetEscortPaused().
SetCurrentWaypoint()
void npc_escortAI::SetCurrentWaypoint (uint32 pointId)
Definition at line 205 of file escort_ai.cpp.
References Object::GetGuidStr(), Unit::GetMotionMaster(), HasEscortState(), CreatureAI::m_creature, script_error_log(), MotionMaster::SetNextWaypoint(), and STATE_ESCORT_PAUSED.
Referenced by npc_thrall_old_hillsbradAI::JustRespawned(), npc_injured_minerAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_phalanxAI::Reset(), npc_hurley_blackbreathAI::Reset(), npc_volcorAI::StartEscort(), npc_rocknotAI::WaypointReached(), and npc_injured_minerAI::WaypointReached().
SetEscortPaused()
void npc_escortAI::SetEscortPaused (bool paused)
Definition at line 306 of file escort_ai.cpp.
References AddEscortState(), Unit::GetMotionMaster(), HasEscortState(), CreatureAI::m_creature, MotionMaster::PauseWaypoints(), RemoveEscortState(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, and MotionMaster::UnpauseWaypoints().
Referenced by npc_tapoke_slim_jahnAI::DamageTaken(), npc_ranshallaAI::DoChannelTorchSpell(), npc_thrall_old_hillsbradAI::DoRestartEscortMovement(), npc_muglashAI::DoWaveSummon(), npc_shadowfang_prisonerAI::HandleSpeech(), npc_squire_roweAI::JustDidDialogueStep(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_taelan_fordringAI::JustDidDialogueStep(), npc_keeper_remulosAI::JustDidDialogueStep(), npc_barnesAI::JustDidDialogueStep(), npc_demolitionist_legosoAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDidDialogueStep(), npc_tarethaAI::JustDidDialogueStep(), npc_melizza_brimbuzzleAI::JustDidDialogueStep(), npc_ranshallaAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_injured_minerAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_phalanxAI::Reset(), npc_hurley_blackbreathAI::Reset(), npc_harrison_jones_zaAI::SetHoldState(), npc_rizzle_sprysprocketAI::SpellHit(), npc_volcorAI::StartEscort(), npc_grark_lorkrubAI::SummonedCreatureJustDied(), npc_arthasAI::SummonedCreatureJustDied(), npc_thrall_old_hillsbradAI::SummonedCreatureJustDied(), npc_captured_arkonarinAI::SummonedCreatureJustDied(), npc_harrison_jonesAI::SummonedCreatureJustDied(), npc_emilyAI::SummonedCreatureJustDied(), npc_shaheenAI::SummonedCreatureJustDied(), npc_fhwoorAI::SummonedCreatureJustDied(), npc_daphne_stilwellAI::SummonedCreatureJustDied(), npc_thrall_old_hillsbradAI::SummonedMovementInform(), npc_saeed_escortAI::UpdateAI(), npc_khadgars_servantAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_hurley_blackbreathAI::UpdateEscortAI(), npc_ogronAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_ranshallaAI::UpdateEscortAI(), npc_heliceAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_drijyaAI::UpdateEscortAI(), npc_letollAI::UpdateEscortAI(), npc_marshal_windsorAI::UpdateEscortAI(), npc_morokkAI::UpdateEscortAI(), npc_blastmaster_emi_shortfuseAI::UpdateEscortAI(), npc_shadowfang_prisonerAI::WaypointReached(), npc_squire_roweAI::WaypointReached(), npc_reginald_windsorAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_taelan_fordringAI::WaypointReached(), npc_isillienAI::WaypointReached(), npc_tirion_fordringAI::WaypointReached(), npc_daphne_stilwellAI::WaypointReached(), npc_harrison_jones_zaAI::WaypointReached(), npc_keeper_remulosAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_tarethaAI::WaypointReached(), npc_saeed_escortAI::WaypointReached(), npc_grimstoneAI::WaypointReached(), npc_phalanxAI::WaypointReached(), npc_rocknotAI::WaypointReached(), npc_marshal_windsorAI::WaypointReached(), npc_hurley_blackbreathAI::WaypointReached(), npc_grark_lorkrubAI::WaypointReached(), npc_blastmaster_emi_shortfuseAI::WaypointReached(), npc_barnesAI::WaypointReached(), npc_muglashAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_arthasAI::WaypointReached(), npc_volcorAI::WaypointReached(), npc_morokkAI::WaypointReached(), npc_ogronAI::WaypointReached(), npc_captured_arkonarinAI::WaypointReached(), npc_areiAI::WaypointReached(), npc_belnistraszAI::WaypointReached(), npc_willix_the_importerAI::WaypointReached(), npc_disciple_of_naralexAI::WaypointReached(), npc_ranshallaAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_heliceAI::WaypointReached(), npc_injured_minerAI::WaypointReached(), npc_shaheenAI::WaypointReached(), npc_protectorate_demolitionistAI::WaypointReached(), npc_drijyaAI::WaypointReached(), npc_khadgars_servantAI::WaypointReached(), npc_letollAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), and npc_demolitionist_legosoAI::WaypointReached().
SetEscortWaypoints()
void npc_escortAI::SetEscortWaypoints (uint32 pathId) protected
Definition at line 323 of file escort_ai.cpp.
References m_waypointPathID.
Referenced by npc_captured_sprite_darterAI::Reset().
SetRun()
void npc_escortAI::SetRun (bool run = true)
Definition at line 219 of file escort_ai.cpp.
References debug_log(), CreatureAI::m_creature, m_isRunning, and Creature::SetWalk().
Referenced by npc_shadowfang_prisonerAI::HandleSpeech(), npc_thrall_old_hillsbradAI::JustDidDialogueStep(), npc_melizza_brimbuzzleAI::JustDidDialogueStep(), npc_shaheenAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::SummonedCreatureJustDied(), npc_ogronAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_protectorate_demolitionistAI::UpdateEscortAI(), npc_ranger_lilathaAI::WaypointReached(), npc_kayra_longmaneAI::WaypointReached(), npc_galen_goodwardAI::WaypointReached(), npc_daphne_stilwellAI::WaypointReached(), npc_defias_traitorAI::WaypointReached(), npc_thrall_old_hillsbradAI::WaypointReached(), npc_tarethaAI::WaypointReached(), npc_professor_phizzlethorpeAI::WaypointReached(), npc_kineloryAI::WaypointReached(), npc_hurley_blackbreathAI::WaypointReached(), npc_rinjiAI::WaypointReached(), npc_tapoke_slim_jahnAI::WaypointReached(), npc_magwinAI::WaypointReached(), npc_arthasAI::WaypointReached(), npc_theryluneAI::WaypointReached(), npc_wizzlecranks_shredderAI::WaypointReached(), npc_mootoo_the_youngerAI::WaypointReached(), npc_harrison_jonesAI::WaypointReached(), npc_emilyAI::WaypointReached(), npc_squad_leaderAI::WaypointReached(), npc_father_kamarosAI::WaypointReached(), npc_nagrand_captiveAI::WaypointReached(), npc_captured_vanguardAI::WaypointReached(), npc_drijyaAI::WaypointReached(), npc_akunoAI::WaypointReached(), npc_letollAI::WaypointReached(), npc_skyguard_prisonerAI::WaypointReached(), npc_fhwoorAI::WaypointReached(), npc_corporal_keeshan_escortAI::WaypointReached(), and npc_wizzlecranks_shredderAI::WaypointStart().
Start()
void npc_escortAI::Start (bool run = false, const Player * player = nullptr, const Quest * quest = nullptr, bool instantRespawn = false, bool canLoopPath = false, uint32 waypointPath = 0)
Definition at line 239 of file escort_ai.cpp.
References AddEscortState(), MotionMaster::Clear(), debug_log(), Object::GetEntry(), Object::GetGUIDLow(), Unit::GetMotionMaster(), Object::GetObjectGuid(), Creature::GetScriptName(), Unit::GetVictim(), HasEscortState(), JustStartedEscort(), m_canInstantRespawn, m_canReturnToStart, CreatureAI::m_creature, m_currentEscortWaypointPath, m_isRunning, m_playerGuid, m_questForEscort, m_waypointPathID, MotionMaster::MoveWaypoint(), PATH_FROM_EXTERNAL, PATH_FROM_WAYPOINT_PATH, script_error_log(), Object::SetUInt32Value(), Creature::SetWalk(), STATE_ESCORT_ESCORTING, Unit::StopMoving(), sWaypointMgr, UNIT_NPC_FLAG_NONE, and UNIT_NPC_FLAGS.
Referenced by npc_clintar_dw_spiritAI::DoStart(), GossipSelect_example_escort(), npc_khadgars_servantAI::HandleStart(), npc_reginald_windsorAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustRespawned(), npc_custodian_of_timeAI::MoveInLineOfSight(), npc_protectorate_demolitionistAI::MoveInLineOfSight(), npc_ancestral_wolfAI::npc_ancestral_wolfAI(), npc_taelan_fordringAI::ReceiveAIEvent(), npc_kineloryAI::ReceiveAIEvent(), npc_corporal_keeshan_escortAI::ReceiveAIEvent(), npc_dorius_stonetenderAI::ReceiveAIEvent(), npc_anchorite_truuenAI::ReceiveAIEvent(), npc_tapoke_slim_jahnAI::ReceiveAIEvent(), npc_stinky_ignatzAI::ReceiveAIEvent(), npc_captured_arkonarinAI::ReceiveAIEvent(), npc_areiAI::ReceiveAIEvent(), npc_bonker_togglevoltAI::ReceiveAIEvent(), npc_mootoo_the_youngerAI::ReceiveAIEvent(), npc_proudhoofAI::ReceiveAIEvent(), npc_harrison_jonesAI::ReceiveAIEvent(), npc_apothecary_hanesAI::ReceiveAIEvent(), npc_squad_leaderAI::ReceiveAIEvent(), npc_father_kamarosAI::ReceiveAIEvent(), npc_injured_minerAI::ReceiveAIEvent(), npc_shaheenAI::ReceiveAIEvent(), npc_nagrand_captiveAI::ReceiveAIEvent(), npc_drijyaAI::ReceiveAIEvent(), npc_skyguard_prisonerAI::ReceiveAIEvent(), npc_fhwoorAI::ReceiveAIEvent(), npc_demolitionist_legosoAI::ReceiveAIEvent(), npc_arthasAI::ReceiveAIEvent(), npc_emilyAI::ReceiveAIEvent(), npc_isillienAI::ReceiveAIEvent(), npc_tirion_fordringAI::ReceiveAIEvent(), npc_volcorAI::StartEscort(), npc_harrison_jones_zaAI::StartEvent(), npc_magwinAI::StartEvent(), npc_cork_gizeltonAI::StartRiggerEscort(), npc_grimstoneAI::UpdateEscortAI(), npc_rocknotAI::UpdateEscortAI(), npc_hurley_blackbreathAI::UpdateEscortAI(), mob_scarlet_traineeAI::UpdateEscortAI(), npc_rizzle_sprysprocketAI::UpdateEscortAI(), npc_tarethaAI::UpdateEscortAI(), npc_garments_of_questsAI::UpdateEscortAI(), and npc_blastmaster_emi_shortfuseAI::UpdateEscortAI().
UpdateAI()
void npc_escortAI::UpdateAI (const uint32 diff) override virtual
Called at World update tick, by default every 100ms This setting is dependend on CONFIG_UINT32_INTERVAL_MAPUPDATE Note: Use this function to handle Timers, Threat-Management and MeleeAttacking.
Parameters
uiDiff Passed time since last call
Reimplemented from UnitAI.
Reimplemented in npc_saeed_escortAI, and npc_thrall_old_hillsbradAI.
Definition at line 129 of file escort_ai.cpp.
References debug_log(), FailQuestForPlayerAndGroup(), Creature::ForcedDespawn(), Creature::GetCreatureGroup(), Unit::GetVictim(), HasEscortState(), Creature::IsPet(), IsPlayerOrGroupInRange(), JUST_DIED, m_canInstantRespawn, CreatureAI::m_creature, m_playerCheckTimer, m_playerGuid, m_questForEscort, PET_SAVE_AS_DELETED, Creature::Respawn(), Creature::SetDeathState(), STATE_ESCORT_ESCORTING, STATE_ESCORT_PAUSED, STATE_ESCORT_RETURNING, and UpdateEscortAI().
UpdateEscortAI()
void npc_escortAI::UpdateEscortAI (const uint32 diff) virtual
Reimplemented in npc_blastmaster_emi_shortfuseAI, npc_ancestral_wolfAI, npc_injured_rainspeakerAI, npc_morokkAI, npc_dorius_stonetenderAI, npc_marshal_windsorAI, npc_garments_of_questsAI, npc_fhwoorAI, npc_skywingAI, npc_isla_starmaneAI, npc_letollAI, npc_akunoAI, npc_wildaAI, npc_drijyaAI, npc_captured_vanguardAI, npc_protectorate_demolitionistAI, npc_maxx_a_million_escortAI, npc_nagrand_captiveAI, npc_shaheenAI, npc_heliceAI, npc_father_kamarosAI, npc_squad_leaderAI, npc_apothecary_hanesAI, npc_harrison_jonesAI, npc_proudhoofAI, npc_lurgglbrAI, npc_ranshallaAI, npc_disciple_of_naralexAI, npc_wizzlecranks_shredderAI, npc_belnistraszAI, npc_areiAI, npc_captured_arkonarinAI, npc_ogronAI, npc_melizza_brimbuzzleAI, npc_tarethaAI, npc_thrall_old_hillsbradAI, npc_arthasAI, npc_demolitionist_legosoAI, npc_rizzle_sprysprocketAI, npc_torekAI, npc_muglashAI, example_escortAI, npc_tapoke_slim_jahnAI, mob_scarlet_traineeAI, npc_corporal_keeshan_escortAI, npc_rinjiAI, npc_grark_lorkrubAI, npc_hurley_blackbreathAI, npc_rocknotAI, npc_phalanxAI, npc_grimstoneAI, npc_kineloryAI, npc_squire_roweAI, npc_barnesAI, npc_khadgars_servantAI, npc_keeper_remulosAI, npc_captured_sprite_darterAI, npc_cork_gizeltonAI, npc_harrison_jones_zaAI, npc_daphne_stilwellAI, npc_tirion_fordringAI, npc_isillienAI, npc_taelan_fordringAI, npc_galen_goodwardAI, and npc_reginald_windsorAI.
Definition at line 171 of file escort_ai.cpp.
References UnitAI::UpdateAI().
Referenced by UpdateAI(), and npc_cork_gizeltonAI::UpdateEscortAI().
WaypointReached()
virtual void npc_escortAI::WaypointReached (uint32 pointId) pure virtual
Implemented in npc_garments_of_questsAI, mob_scarlet_traineeAI, npc_demolitionist_legosoAI, example_escortAI, npc_corporal_keeshan_escortAI, npc_fhwoorAI, npc_skyguard_prisonerAI, npc_skywingAI, npc_isla_starmaneAI, npc_letollAI, npc_akunoAI, npc_khadgars_servantAI, npc_wildaAI, npc_drijyaAI, npc_captured_vanguardAI, npc_protectorate_demolitionistAI, npc_bessyAI, npc_nagrand_captiveAI, npc_wounded_blood_elfAI, npc_ancestral_wolfAI, npc_shaheenAI, npc_injured_minerAI, npc_injured_rainspeakerAI, npc_heliceAI, npc_father_kamarosAI, npc_squad_leaderAI, npc_apothecary_hanesAI, npc_emilyAI, npc_harrison_jonesAI, npc_proudhoofAI, npc_mootoo_the_youngerAI, npc_bonker_togglevoltAI, npc_lurgglbrAI, npc_ranshallaAI, npc_disciple_of_naralexAI, npc_ame01AI, npc_paoka_swiftmountainAI, npc_lakota_windsongAI, npc_kanatiAI, npc_wizzlecranks_shredderAI, npc_giltharesAI, npc_custodian_of_timeAI, npc_kayaAI, npc_willix_the_importerAI, npc_belnistraszAI, npc_areiAI, npc_captured_arkonarinAI, npc_stinky_ignatzAI, npc_ogronAI, npc_morokkAI, npc_melizza_brimbuzzleAI, npc_dalinda_malemAI, npc_theryluneAI, npc_volcorAI, npc_prospector_remtravelAI, npc_arthasAI, npc_magwinAI, npc_rizzle_sprysprocketAI, npc_feero_ironhandAI, npc_torekAI, npc_muglashAI, npc_tapoke_slim_jahnAI, npc_anchorite_truuenAI, npc_dorius_stonetenderAI, npc_miranAI, npc_barnesAI, npc_rinjiAI, npc_00x09hlAI, npc_blastmaster_emi_shortfuseAI, npc_prospector_anvilwardAI, npc_grark_lorkrubAI, npc_hurley_blackbreathAI, npc_marshal_windsorAI, npc_rocknotAI, npc_phalanxAI, npc_grimstoneAI, npc_kineloryAI, npc_professor_phizzlethorpeAI, npc_saeed_escortAI, npc_maxx_a_million_escortAI, npc_tarethaAI, npc_thrall_old_hillsbradAI, npc_keeper_remulosAI, npc_captured_sprite_darterAI, npc_cork_gizeltonAI, npc_ruul_snowhoofAI, npc_harrison_jones_zaAI, npc_defias_traitorAI, npc_daphne_stilwellAI, npc_tirion_fordringAI, npc_isillienAI, npc_taelan_fordringAI, npc_galen_goodwardAI, npc_reginald_windsorAI, npc_squire_roweAI, npc_shadowfang_prisonerAI, npc_kayra_longmaneAI, npc_oox17tnAI, npc_clintar_dw_spiritAI, npc_oox22feAI, npc_deathstalker_erlandAI, and npc_ranger_lilathaAI.
Referenced by MovementInform().
WaypointStart()
virtual void npc_escortAI::WaypointStart (uint32) inline virtual
Reimplemented in npc_demolitionist_legosoAI, npc_corporal_keeshan_escortAI, npc_isla_starmaneAI, npc_lurgglbrAI, npc_wizzlecranks_shredderAI, npc_00x09hlAI, npc_blastmaster_emi_shortfuseAI, npc_stinky_ignatzAI, npc_maxx_a_million_escortAI, and npc_galen_goodwardAI.
Definition at line 40 of file escort_ai.h.
Referenced by MovementInform().
Field Documentation
m_canInstantRespawn
bool npc_escortAI::m_canInstantRespawn private
Definition at line 80 of file escort_ai.h.
Referenced by MovementInform(), Start(), and UpdateAI().
m_canReturnToStart
bool npc_escortAI::m_canReturnToStart private
Definition at line 81 of file escort_ai.h.
Referenced by Start().
m_currentEscortWaypointPath
uint32 npc_escortAI::m_currentEscortWaypointPath private
Definition at line 84 of file escort_ai.h.
Referenced by GetCurrentWaypointPath(), and Start().
m_escortState
uint32 npc_escortAI::m_escortState private
Definition at line 76 of file escort_ai.h.
Referenced by AddEscortState(), CorpseRemoved(), HasEscortState(), and RemoveEscortState().
m_isRunning
bool npc_escortAI::m_isRunning private
Definition at line 79 of file escort_ai.h.
Referenced by SetRun(), and Start().
m_playerCheckTimer
uint32 npc_escortAI::m_playerCheckTimer private
Definition at line 75 of file escort_ai.h.
Referenced by UpdateAI().
m_playerGuid
ObjectGuid npc_escortAI::m_playerGuid private
Definition at line 74 of file escort_ai.h.
Referenced by End(), GetAIInformation(), GetPlayerForEscort(), JustDied(), Start(), and UpdateAI().
m_questForEscort
const Quest* npc_escortAI::m_questForEscort protected
Definition at line 66 of file escort_ai.h.
Referenced by End(), FailQuestForPlayerAndGroup(), GetAIInformation(), JustDied(), Start(), npc_cork_gizeltonAI::StartRiggerEscort(), and UpdateAI().
m_waypointPathID
uint32 npc_escortAI::m_waypointPathID private
Definition at line 83 of file escort_ai.h.
Referenced by SetEscortWaypoints(), and Start().
The documentation for this struct was generated from the following files:
escort_ai.h
escort_ai.cpp