CMaNGOS_WoTLK: MaNGOS::WorldObjectSearcher< Check > Struct Template Reference
MaNGOS::WorldObjectSearcher< Check > Struct Template Reference
#include <GridNotifiers.h>
Public Member Functions
WorldObjectSearcher (WorldObject *&result, Check &check)
void Visit (GameObjectMapType &m)
void Visit (PlayerMapType &m)
void Visit (CreatureMapType &m)
void Visit (CorpseMapType &m)
void Visit (DynamicObjectMapType &m)
template<class NOT_INTERESTED >
void Visit (GridRefManager< NOT_INTERESTED > &)
Data Fields
uint32 i_phaseMask
WorldObject *& i_object
Check & i_check
Detailed Description
template<class Check>
struct MaNGOS::WorldObjectSearcher< Check >
Definition at line 219 of file GridNotifiers.h.
Constructor & Destructor Documentation
WorldObjectSearcher()
template<class Check > MaNGOS::WorldObjectSearcher< Check >::WorldObjectSearcher (WorldObject *& result, Check & check) inline
Definition at line 225 of file GridNotifiers.h.
Member Function Documentation
Visit() [1/6]
template<class Check > void MaNGOS::WorldObjectSearcher< Check >::Visit (CorpseMapType & m)
Definition at line 393 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [2/6]
template<class Check > void MaNGOS::WorldObjectSearcher< Check >::Visit (CreatureMapType & m)
Definition at line 373 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [3/6]
template<class Check > void MaNGOS::WorldObjectSearcher< Check >::Visit (DynamicObjectMapType & m)
Definition at line 413 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [4/6]
template<class Check > void MaNGOS::WorldObjectSearcher< Check >::Visit (GameObjectMapType & m)
Definition at line 333 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Visit() [5/6]
template<class Check > template<class NOT_INTERESTED > void MaNGOS::WorldObjectSearcher< Check >::Visit (GridRefManager< NOT_INTERESTED > &) inline
Definition at line 234 of file GridNotifiers.h.
Visit() [6/6]
template<class Check > void MaNGOS::WorldObjectSearcher< Check >::Visit (PlayerMapType & m)
Definition at line 353 of file GridNotifiersImpl.h.
References GridRefManager< OBJECT >::begin(), and GridRefManager< OBJECT >::end().
Field Documentation
i_check
template<class Check > Check& MaNGOS::WorldObjectSearcher< Check >::i_check
Definition at line 223 of file GridNotifiers.h.
i_object
template<class Check > WorldObject*& MaNGOS::WorldObjectSearcher< Check >::i_object
Definition at line 222 of file GridNotifiers.h.
i_phaseMask
template<class Check > uint32 MaNGOS::WorldObjectSearcher< Check >::i_phaseMask
Definition at line 221 of file GridNotifiers.h.
The documentation for this struct was generated from the following files:
GridNotifiers.h
GridNotifiersImpl.h