CMaNGOS_WoTLK: sunken_templeScripts.cpp File Reference
sunken_templeScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sunken_temple.h"
Data Structures
struct npc_malfurionAI
struct SummonHakkar
struct HakkarSummoned
struct HexOfJammalanAura
Enumerations
enum { QUEST_THE_CHARGE_OF_DRAGONFLIGHTS = 8555 , QUEST_ERANIKUS_TYRANT_OF_DREAMS = 8733 }
enum {
EMOTE_MALFURION1 = -1109000 , SAY_MALFURION1 = -1109001 , SAY_MALFURION2 = -1109002 , SAY_MALFURION3 = -1109003 ,
SAY_MALFURION4 = -1109004 , MAX_MALFURION_TEMPLE_SPEECHES = 6
}
Functions
bool AreaTrigger_at_shade_of_eranikus (Player *pPlayer, AreaTriggerEntry const *)
UnitAI * GetAI_npc_malfurion (Creature *pCreature)
bool ProcessEventId_event_antalarion_statue_activation (uint32 uiEventId, Object *pSource, Object *pTarget, bool)
bool ProcessEventId_event_avatar_of_hakkar (uint32, Object *source, Object *, bool)
bool GOUse_go_eternal_flame (Player *, GameObject *pGo)
void AddSC_sunken_temple ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_THE_CHARGE_OF_DRAGONFLIGHTS
QUEST_ERANIKUS_TYRANT_OF_DREAMS
Definition at line 36 of file sunken_templeScripts.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_MALFURION1
SAY_MALFURION1
SAY_MALFURION2
SAY_MALFURION3
SAY_MALFURION4
MAX_MALFURION_TEMPLE_SPEECHES
Definition at line 65 of file sunken_templeScripts.cpp.
Function Documentation
AddSC_sunken_temple()
void AddSC_sunken_temple ()
Definition at line 285 of file sunken_templeScripts.cpp.
References AreaTrigger_at_shade_of_eranikus(), Script::GetAI, GetAI_npc_malfurion(), GOUse_go_eternal_flame(), Script::Name, Script::pAreaTrigger, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_antalarion_statue_activation(), ProcessEventId_event_avatar_of_hakkar(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_shade_of_eranikus()
bool AreaTrigger_at_shade_of_eranikus (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 42 of file sunken_templeScripts.cpp.
References aSunkenTempleLocation, WorldObject::GetInstanceData(), Player::GetQuestRewardStatus(), Player::GetQuestStatus(), IN_PROGRESS, NPC_MALFURION, QUEST_ERANIKUS_TYRANT_OF_DREAMS, QUEST_STATUS_COMPLETE, QUEST_THE_CHARGE_OF_DRAGONFLIGHTS, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_MALFURION.
Referenced by AddSC_sunken_temple().
GetAI_npc_malfurion()
UnitAI* GetAI_npc_malfurion (Creature * pCreature)
Definition at line 144 of file sunken_templeScripts.cpp.
Referenced by AddSC_sunken_temple().
GOUse_go_eternal_flame()
bool GOUse_go_eternal_flame (Player * , GameObject * pGo)
Definition at line 212 of file sunken_templeScripts.cpp.
References GAMEOBJECT_FLAGS, instance_sunken_temple::GetData(), WorldObject::GetInstanceData(), GO_FLAG_NO_INTERACT, IN_PROGRESS, instance_sunken_temple::SetData(), Object::SetFlag(), SPECIAL, and TYPE_AVATAR.
Referenced by AddSC_sunken_temple().
ProcessEventId_event_antalarion_statue_activation()
bool ProcessEventId_event_antalarion_statue_activation (uint32 uiEventId, Object * pSource, Object * pTarget, bool)
Definition at line 153 of file sunken_templeScripts.cpp.
References GetClosestGameObjectWithEntry(), Object::GetTypeId(), GO_ATALAI_LIGHT, GO_ATALAI_TRAP_1, GO_ATALAI_TRAP_2, GO_ATALAI_TRAP_3, INTERACTION_DISTANCE, MINUTE, NOT_STARTED, TYPE_ATALARION, TYPEID_GAMEOBJECT, and TYPEID_PLAYER.
Referenced by AddSC_sunken_temple().
ProcessEventId_event_avatar_of_hakkar()
bool ProcessEventId_event_avatar_of_hakkar (uint32 , Object * source, Object * , bool)
Definition at line 191 of file sunken_templeScripts.cpp.
References FAIL, Object::GetTypeId(), IN_PROGRESS, NOT_STARTED, TYPE_AVATAR, and TYPEID_PLAYER.
Referenced by AddSC_sunken_temple().