CMaNGOS_WoTLK: sunwell_plateau.cpp File Reference
sunwell_plateau.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "sunwell_plateau.h"
#include "Maps/MapPersistentStateMgr.h"
Enumerations
enum SunwellActions { ACTION_SPAWN_MURU , ACTION_IMP_YELL , ACTION_MURU_DOOR }
Functions
static bool sortByPositionX (Creature *pFirst, Creature *pSecond)
bool AreaTrigger_at_sunwell_plateau (Player *player, AreaTriggerEntry const *at)
void AddSC_instance_sunwell_plateau ()
Variables
static const DialogueEntry aFelmystOutroDialogue []
Enumeration Type Documentation
SunwellActions
enum SunwellActions
Enumerator
ACTION_SPAWN_MURU
ACTION_IMP_YELL
ACTION_MURU_DOOR
Definition at line 60 of file sunwell_plateau.cpp.
Function Documentation
AddSC_instance_sunwell_plateau()
void AddSC_instance_sunwell_plateau ()
Definition at line 882 of file sunwell_plateau.cpp.
References AreaTrigger_at_sunwell_plateau(), Script::GetInstanceData, Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_sunwell_plateau()
bool AreaTrigger_at_sunwell_plateau (Player * player, AreaTriggerEntry const * at)
Definition at line 866 of file sunwell_plateau.cpp.
References AREATRIGGER_TWINS, instance_sunwell_plateau::GetData(), WorldObject::GetInstanceData(), AreaTriggerEntry::id, Unit::IsDead(), Player::IsGameMaster(), NOT_STARTED, instance_sunwell_plateau::SetData(), SPECIAL, and TYPE_EREDAR_TWINS.
Referenced by AddSC_instance_sunwell_plateau().
sortByPositionX()
static bool sortByPositionX (Creature * pFirst, Creature * pSecond) static
Definition at line 562 of file sunwell_plateau.cpp.
References WorldObject::GetPositionX().
Referenced by instance_sunwell_plateau::DoSortFlightTriggers().
Variable Documentation
aFelmystOutroDialogue
const DialogueEntry aFelmystOutroDialogue[] static
Initial value:
=
{
    {NPC_KALECGOS_MADRIGOSA, 0,                        10000},
    {SAY_KALECGOS_OUTRO,     NPC_KALECGOS_MADRIGOSA,   5000},
    {NPC_FELMYST,            0,                        5000},
    {SPELL_OPEN_BACK_DOOR,   0,                        9000},
    {NPC_BRUTALLUS,          0,                        0},
    {0, 0, 0},
}
Definition at line 37 of file sunwell_plateau.cpp.