CMaNGOS_WoTLK: swamp_of_sorrows.cpp File Reference
swamp_of_sorrows.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_galen_goodwardAI
Enumerations
enum Galen {
QUEST_GALENS_ESCAPE = 1393 , GO_GALENS_CAGE = 37118 , SAY_PERIODIC = -1000582 , SAY_QUEST_ACCEPTED = -1000583 ,
SAY_ATTACKED_1 = -1000584 , SAY_ATTACKED_2 = -1000585 , SAY_QUEST_COMPLETE = -1000586 , EMOTE_WHISPER = -1000587 ,
EMOTE_DISAPPEAR = -1000588
}
Functions
bool QuestAccept_npc_galen_goodward (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_galen_goodward (Creature *creature)
void AddSC_swamp_of_sorrows ()
Enumeration Type Documentation
Galen
enum Galen
Enumerator
QUEST_GALENS_ESCAPE
GO_GALENS_CAGE
SAY_PERIODIC
SAY_QUEST_ACCEPTED
SAY_ATTACKED_1
SAY_ATTACKED_2
SAY_QUEST_COMPLETE
EMOTE_WHISPER
EMOTE_DISAPPEAR
Definition at line 35 of file swamp_of_sorrows.cpp.
Function Documentation
AddSC_swamp_of_sorrows()
void AddSC_swamp_of_sorrows ()
Definition at line 157 of file swamp_of_sorrows.cpp.
References Script::GetAI, GetAI_npc_galen_goodward(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_galen_goodward(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_galen_goodward()
UnitAI* GetAI_npc_galen_goodward (Creature * creature)
Definition at line 152 of file swamp_of_sorrows.cpp.
Referenced by AddSC_swamp_of_sorrows().
QuestAccept_npc_galen_goodward()
bool QuestAccept_npc_galen_goodward (Player * player, Creature * creature, const Quest * quest)
Definition at line 137 of file swamp_of_sorrows.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_GALENS_ESCAPE, SAY_QUEST_ACCEPTED, Creature::SetFactionTemporary(), TEMPFACTION_RESTORE_RESPAWN, and TEMPFACTION_TOGGLE_IMMUNE_TO_NPC.
Referenced by AddSC_swamp_of_sorrows().