CMaNGOS_WoTLK: tanaris.cpp File Reference
tanaris.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
Data Structures
struct mob_aquementasAI
struct npc_custodian_of_timeAI
struct npc_oox17tnAI
struct npc_toogaAI
Macros
#define GOSSIP_ITEM_NORGANNON_1 "What function do you serve?"
#define GOSSIP_ITEM_NORGANNON_2 "What are the Plates of Uldum?"
#define GOSSIP_ITEM_NORGANNON_3 "Where are the Plates of Uldum?"
#define GOSSIP_ITEM_NORGANNON_4 "Excuse me? We've been \"reschedueled for visitations\"? What does that mean?!"
#define GOSSIP_ITEM_NORGANNON_5 "So, what's inside Uldum?"
#define GOSSIP_ITEM_NORGANNON_6 "I will return when i have the Plates of Uldum."
Enumerations
enum {
AGGRO_YELL_AQUE = -1000168 , SPELL_AQUA_JET = 13586 , SPELL_FROST_SHOCK = 15089 , ITEM_SILVER_TOTEM = 11522 ,
ITEM_BOOK_AQUOR = 11169 , ITEM_SILVERY_CLAWS = 11172 , ITEM_IRONTREE_HEART = 11173 , FACTION_FRIENDLY = 35 ,
FACTION_ELEMENTAL = 91
}
enum {
WHISPER_CUSTODIAN_1 = -1000217 , WHISPER_CUSTODIAN_2 = -1000218 , WHISPER_CUSTODIAN_3 = -1000219 , WHISPER_CUSTODIAN_4 = -1000220 ,
WHISPER_CUSTODIAN_5 = -1000221 , WHISPER_CUSTODIAN_6 = -1000222 , WHISPER_CUSTODIAN_7 = -1000223 , WHISPER_CUSTODIAN_8 = -1000224 ,
WHISPER_CUSTODIAN_9 = -1000225 , WHISPER_CUSTODIAN_10 = -1000226 , WHISPER_CUSTODIAN_11 = -1000227 , WHISPER_CUSTODIAN_12 = -1000228 ,
WHISPER_CUSTODIAN_13 = -1000229 , WHISPER_CUSTODIAN_14 = -1000230 , SPELL_CUSTODIAN_OF_TIME = 34877 , SPELL_QID_10277 = 34883 ,
QUEST_ID_CAVERNS_OF_TIME = 10277
}
enum {
SAY_OOX_START = -1000287 , SAY_OOX_AGGRO1 = -1000288 , SAY_OOX_AGGRO2 = -1000289 , SAY_OOX_AMBUSH = -1000290 ,
SAY_OOX17_AMBUSH_REPLY = -1000291 , SAY_OOX_END = -1000292 , QUEST_RESCUE_OOX_17TN = 648 , NPC_SCORPION = 7803 ,
NPC_SCOFFLAW = 7805 , NPC_SHADOW_MAGE = 5617
}
enum {
SAY_TOOG_THIRST = -1000391 , SAY_TOOG_WORRIED = -1000392 , SAY_TOOG_POST_1 = -1000393 , SAY_TORT_POST_2 = -1000394 ,
SAY_TOOG_POST_3 = -1000395 , SAY_TORT_POST_4 = -1000396 , SAY_TOOG_POST_5 = -1000397 , SAY_TORT_POST_6 = -1000398 ,
QUEST_TOOGA = 1560 , NPC_TORTA = 6015 , POINT_ID_TO_WATER = 1
}
Functions
UnitAI * GetAI_mob_aquementas (Creature *pCreature)
UnitAI * GetAI_npc_custodian_of_time (Creature *pCreature)
UnitAI * GetAI_npc_oox17tn (Creature *pCreature)
bool QuestAccept_npc_oox17tn (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool GossipHello_npc_stone_watcher_of_norgannon (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_stone_watcher_of_norgannon (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_tooga (Creature *pCreature)
bool QuestAccept_npc_tooga (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_tanaris ()
Variables
const float m_afToWaterLoc [] = { -7032.664551f, -4906.199219f, -1.606446f}
Macro Definition Documentation
GOSSIP_ITEM_NORGANNON_1
#define GOSSIP_ITEM_NORGANNON_1 "What function do you serve?"
Definition at line 343 of file tanaris.cpp.
GOSSIP_ITEM_NORGANNON_2
#define GOSSIP_ITEM_NORGANNON_2 "What are the Plates of Uldum?"
Definition at line 344 of file tanaris.cpp.
GOSSIP_ITEM_NORGANNON_3
#define GOSSIP_ITEM_NORGANNON_3 "Where are the Plates of Uldum?"
Definition at line 345 of file tanaris.cpp.
GOSSIP_ITEM_NORGANNON_4
#define GOSSIP_ITEM_NORGANNON_4 "Excuse me? We've been \"reschedueled for visitations\"? What does that mean?!"
Definition at line 346 of file tanaris.cpp.
GOSSIP_ITEM_NORGANNON_5
#define GOSSIP_ITEM_NORGANNON_5 "So, what's inside Uldum?"
Definition at line 347 of file tanaris.cpp.
GOSSIP_ITEM_NORGANNON_6
#define GOSSIP_ITEM_NORGANNON_6 "I will return when i have the Plates of Uldum."
Definition at line 348 of file tanaris.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AGGRO_YELL_AQUE
SPELL_AQUA_JET
SPELL_FROST_SHOCK
ITEM_SILVER_TOTEM
ITEM_BOOK_AQUOR
ITEM_SILVERY_CLAWS
ITEM_IRONTREE_HEART
FACTION_FRIENDLY
FACTION_ELEMENTAL
Definition at line 40 of file tanaris.cpp.
anonymous enum
anonymous enum
Enumerator
WHISPER_CUSTODIAN_1
WHISPER_CUSTODIAN_2
WHISPER_CUSTODIAN_3
WHISPER_CUSTODIAN_4
WHISPER_CUSTODIAN_5
WHISPER_CUSTODIAN_6
WHISPER_CUSTODIAN_7
WHISPER_CUSTODIAN_8
WHISPER_CUSTODIAN_9
WHISPER_CUSTODIAN_10
WHISPER_CUSTODIAN_11
WHISPER_CUSTODIAN_12
WHISPER_CUSTODIAN_13
WHISPER_CUSTODIAN_14
SPELL_CUSTODIAN_OF_TIME
SPELL_QID_10277
QUEST_ID_CAVERNS_OF_TIME
Definition at line 139 of file tanaris.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_OOX_START
SAY_OOX_AGGRO1
SAY_OOX_AGGRO2
SAY_OOX_AMBUSH
SAY_OOX17_AMBUSH_REPLY
SAY_OOX_END
QUEST_RESCUE_OOX_17TN
NPC_SCORPION
NPC_SCOFFLAW
NPC_SHADOW_MAGE
Definition at line 228 of file tanaris.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_TOOG_THIRST
SAY_TOOG_WORRIED
SAY_TOOG_POST_1
SAY_TORT_POST_2
SAY_TOOG_POST_3
SAY_TORT_POST_4
SAY_TOOG_POST_5
SAY_TORT_POST_6
QUEST_TOOGA
NPC_TORTA
POINT_ID_TO_WATER
Definition at line 399 of file tanaris.cpp.
Function Documentation
AddSC_tanaris()
void AddSC_tanaris ()
Definition at line 554 of file tanaris.cpp.
References Script::GetAI, GetAI_mob_aquementas(), GetAI_npc_custodian_of_time(), GetAI_npc_oox17tn(), GetAI_npc_tooga(), GossipHello_npc_stone_watcher_of_norgannon(), GossipSelect_npc_stone_watcher_of_norgannon(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_oox17tn(), QuestAccept_npc_tooga(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_aquementas()
UnitAI* GetAI_mob_aquementas (Creature * pCreature)
Definition at line 130 of file tanaris.cpp.
Referenced by AddSC_tanaris().
GetAI_npc_custodian_of_time()
UnitAI* GetAI_npc_custodian_of_time (Creature * pCreature)
Definition at line 219 of file tanaris.cpp.
Referenced by AddSC_tanaris().
GetAI_npc_oox17tn()
UnitAI* GetAI_npc_oox17tn (Creature * pCreature)
Definition at line 319 of file tanaris.cpp.
Referenced by AddSC_tanaris().
GetAI_npc_tooga()
UnitAI* GetAI_npc_tooga (Creature * pCreature)
Definition at line 538 of file tanaris.cpp.
Referenced by AddSC_tanaris().
GossipHello_npc_stone_watcher_of_norgannon()
bool GossipHello_npc_stone_watcher_of_norgannon (Player * pPlayer, Creature * pCreature)
Definition at line 350 of file tanaris.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_1, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_tanaris().
GossipSelect_npc_stone_watcher_of_norgannon()
bool GossipSelect_npc_stone_watcher_of_norgannon (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 363 of file tanaris.cpp.
References Player::AreaExploredOrEventHappens(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_NORGANNON_2, GOSSIP_ITEM_NORGANNON_3, GOSSIP_ITEM_NORGANNON_4, GOSSIP_ITEM_NORGANNON_5, GOSSIP_ITEM_NORGANNON_6, and GOSSIP_SENDER_MAIN.
Referenced by AddSC_tanaris().
QuestAccept_npc_oox17tn()
bool QuestAccept_npc_oox17tn (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 324 of file tanaris.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_FRIEND_ACTIVE, Quest::GetQuestId(), QUEST_RESCUE_OOX_17TN, SAY_OOX_START, WorldObject::SetActiveObjectState(), Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_tanaris().
QuestAccept_npc_tooga()
bool QuestAccept_npc_tooga (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 543 of file tanaris.cpp.
References Creature::AI(), FACTION_ESCORT_N_FRIEND_PASSIVE, Quest::GetQuestId(), and QUEST_TOOGA.
Referenced by AddSC_tanaris().
Variable Documentation
m_afToWaterLoc
const float m_afToWaterLoc[] = { -7032.664551f, -4906.199219f, -1.606446f}
Definition at line 416 of file tanaris.cpp.
Referenced by npc_toogaAI::UpdateFollowerAI().