CMaNGOS_WoTLK: teldrassil.cpp File Reference
teldrassil.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
Data Structures
struct npc_mistAI
Enumerations
enum {
SAY_AT_HOME = -1000323 , EMOTE_AT_HOME = -1000324 , QUEST_MIST = 938 , NPC_ARYNIA = 3519 ,
FACTION_DARNASSUS = 79
}
Functions
UnitAI * GetAI_npc_mist (Creature *pCreature)
bool QuestAccept_npc_mist (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_teldrassil ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AT_HOME
EMOTE_AT_HOME
QUEST_MIST
NPC_ARYNIA
FACTION_DARNASSUS
Definition at line 35 of file teldrassil.cpp.
Function Documentation
AddSC_teldrassil()
void AddSC_teldrassil ()
Definition at line 104 of file teldrassil.cpp.
References Script::GetAI, GetAI_npc_mist(), Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_mist(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_mist()
UnitAI* GetAI_npc_mist (Creature * pCreature)
Definition at line 88 of file teldrassil.cpp.
Referenced by AddSC_teldrassil().
QuestAccept_npc_mist()
bool QuestAccept_npc_mist (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 93 of file teldrassil.cpp.
References Creature::AI(), FACTION_DARNASSUS, Quest::GetQuestId(), and QUEST_MIST.
Referenced by AddSC_teldrassil().