CMaNGOS_WoTLK: temple_of_ahnqiraj.cpp File Reference
temple_of_ahnqiraj.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "temple_of_ahnqiraj.h"
Functions
InstanceData * GetInstanceData_instance_temple_of_ahnqiraj (Map *pMap)
bool AreaTrigger_at_temple_ahnqiraj (Player *player, AreaTriggerEntry const *at)
bool ProcessEventId_event_reset_cthun (uint32, Object *source, Object *, bool)
void AddSC_instance_temple_of_ahnqiraj ()
Variables
static const DialogueEntry aIntroDialogue []
Function Documentation
AddSC_instance_temple_of_ahnqiraj()
void AddSC_instance_temple_of_ahnqiraj ()
Definition at line 469 of file temple_of_ahnqiraj.cpp.
References AreaTrigger_at_temple_ahnqiraj(), Script::GetInstanceData, GetInstanceData_instance_temple_of_ahnqiraj(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_event_reset_cthun(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_temple_ahnqiraj()
bool AreaTrigger_at_temple_ahnqiraj (Player * player, AreaTriggerEntry const * at)
Definition at line 442 of file temple_of_ahnqiraj.cpp.
References AREATRIGGER_SARTURA, AREATRIGGER_TWIN_EMPERORS, WorldObject::GetInstanceData(), AreaTriggerEntry::id, Unit::IsAlive(), and Player::IsGameMaster().
Referenced by AddSC_instance_temple_of_ahnqiraj().
GetInstanceData_instance_temple_of_ahnqiraj()
InstanceData* GetInstanceData_instance_temple_of_ahnqiraj (Map * pMap)
Definition at line 437 of file temple_of_ahnqiraj.cpp.
Referenced by AddSC_instance_temple_of_ahnqiraj().
ProcessEventId_event_reset_cthun()
bool ProcessEventId_event_reset_cthun (uint32 , Object * source, Object * , bool)
Definition at line 456 of file temple_of_ahnqiraj.cpp.
References FAIL, Object::GetTypeId(), TYPE_CTHUN, and TYPEID_UNIT.
Referenced by AddSC_instance_temple_of_ahnqiraj().
Variable Documentation
aIntroDialogue
const DialogueEntry aIntroDialogue[] static
Initial value:
=
{
    {EMOTE_EYE_INTRO,       NPC_MASTERS_EYE, 2000},
    {STAND_EMPERORS_INTRO,  0,               6000},
    {SAY_EMPERORS_INTRO_1,  NPC_VEKLOR,      6000},
    {SAY_EMPERORS_INTRO_2,  NPC_VEKNILASH,   8000},
    {SAY_EMPERORS_INTRO_3,  NPC_VEKLOR,      3000},
    {SAY_EMPERORS_INTRO_4,  NPC_VEKNILASH,   3000},
    {SAY_EMPERORS_INTRO_5,  NPC_VEKLOR,      1000},
    {SAY_EMPERORS_INTRO_6,  NPC_VEKNILASH,   0},
    {0, 0, 0}
}
Definition at line 27 of file temple_of_ahnqiraj.cpp.