CMaNGOS_WoTLK: terokkar_forest.cpp File Reference
terokkar_forest.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/pet_ai.h"
Data Structures
struct mob_unkor_the_ruthlessAI
struct mob_netherweb_victimAI
struct npc_akunoAI
struct npc_hungry_nether_rayAI
struct npc_letollAI
struct npc_isla_starmaneAI
struct npc_skywingAI
struct npc_cenarion_sparrowhawkAI
struct npc_skyguard_prisonerAI
struct npc_avatar_of_terokkAI
struct npc_minion_of_terokkAI
struct go_monstrous_kaliri_egg
struct ShadowyDisguise
Enumerations
enum { SAY_SUBMIT = -1000194 , FACTION_FRIENDLY = 35 , SPELL_PULVERIZE = 2676 , SPELL_QUID9889 = 32174 }
enum { NPC_FREED_WARRIOR = 22459 , QUEST_TAKEN_IN_NIGHT = 10873 }
enum {
SAY_AKU_START = -1000477 , SAY_AKU_AMBUSH_A = -1000478 , SAY_AKU_AMBUSH_B = -1000479 , SAY_AKU_AMBUSH_B_REPLY = -1000480 ,
SAY_AKU_COMPLETE = -1000481 , SPELL_CHAIN_LIGHTNING = 39945 , QUEST_ESCAPING_TOMB = 10887 , NPC_CABAL_SKIRMISHER = 21661
}
enum { EMOTE_FEED = -1000628 , NPC_BLACK_WARP_CHASER = 23219 , SPELL_FEED_CREDIT = 41427 }
enum {
SAY_LE_START = -1000511 , SAY_LE_KEEP_SAFE = -1000512 , SAY_LE_NORTH = -1000513 , SAY_LE_ARRIVE = -1000514 ,
SAY_LE_BURIED = -1000515 , SAY_LE_ALMOST = -1000516 , SAY_LE_DRUM = -1000517 , SAY_LE_DRUM_REPLY = -1000518 ,
SAY_LE_DISCOVERY = -1000519 , SAY_LE_DISCOVERY_REPLY = -1000520 , SAY_LE_NO_LEAVE = -1000521 , SAY_LE_NO_LEAVE_REPLY1 = -1000522 ,
SAY_LE_NO_LEAVE_REPLY2 = -1000523 , SAY_LE_NO_LEAVE_REPLY3 = -1000524 , SAY_LE_NO_LEAVE_REPLY4 = -1000525 , SAY_LE_SHUT = -1000526 ,
SAY_LE_REPLY_HEAR = -1000527 , SAY_LE_IN_YOUR_FACE = -1000528 , SAY_LE_HELP_HIM = -1000529 , EMOTE_LE_PICK_UP = -1000530 ,
SAY_LE_THANKS = -1000531 , QUEST_DIGGING_BONES = 10922 , NPC_RESEARCHER = 22464 , NPC_BONE_SIFTER = 22466 ,
MAX_RESEARCHER = 4
}
enum {
QUEST_ESCAPE_FROM_FIREWING_POINT_A = 10051 , QUEST_ESCAPE_FROM_FIREWING_POINT_H = 10052 , SAY_ISLA_PERIODIC_1 = -1000629 , SAY_ISLA_PERIODIC_2 = -1000630 ,
SAY_ISLA_PERIODIC_3 = -1000631 , SAY_ISLA_START = -1000632 , SAY_ISLA_WAITING = -1000633 , SAY_ISLA_LEAVE_BUILDING = -1000634 ,
GO_CAGE = 182794 , SPELL_ENTANGLING_ROOTS = 33844 , SPELL_MOONFIRE = 15798 , SPELL_WRATH = 9739 ,
SPELL_TRAVELFORM = 32447
}
enum {
SAY_SKYWING_START = -1000797 , SAY_SKYWING_TREE_DOWN = -1000798 , SAY_SKYWING_TREE_UP = -1000799 , SAY_SKYWING_JUMP = -1000800 ,
SAY_SKYWING_SUMMON = -1000801 , SAY_SKYWING_END = -1000802 , SPELL_FEATHERY_CYCLONE_BURST = 39166 , SPELL_RILAK_THE_REDEEMED = 39179 ,
NPC_LUANGA_THE_IMPRISONER = 18533 , QUEST_SKYWING = 10898
}
enum {
EMOTE_FOLLOW = -1000963 , EMOTE_SURVEY = -1000964 , EMOTE_LOCATE = -1000965 , NPC_SKETTIS_RAVEN_STONE = 22986 ,
GO_RAVEN_STONE = 185541
}
enum {
SAY_ESCORT_START = -1001006 , SAY_AMBUSH_END = -1001007 , SAY_ESCORT_COMPLETE = -1001008 , SAY_AMBUSH_1 = -1001009 ,
SAY_AMBUSH_2 = -1001010 , SAY_AMBUSH_3 = -1001011 , SAY_AMBUSH_4 = -1001012 , NPC_WING_GUARD = 21644 ,
GO_PRISONER_CAGE = 185952 , QUEST_ID_ESCAPE_SKETTIS = 11085 , SPELL_PORT_LOCATION_1 = 41136 , SPELL_PORT_LOCATION_2 = 41138 ,
SPELL_PORT_LOCATION_3 = 41141 , SPELL_CAGE_SUMMON = 41147
}
enum {
SPELL_TERRIFYING_SCREECH = 38021 , SPELL_FEATHER_BURST = 39068 , SAY_DEFENDER_GRASHNA = -1001241 , NPC_DEFENDER_GRASHNA = 22373 ,
QUEST_SKETTIS_OFFENSIVE = 10879
}
Functions
UnitAI * GetAI_mob_unkor_the_ruthless (Creature *pCreature)
UnitAI * GetAI_mob_netherweb_victim (Creature *pCreature)
bool QuestAccept_npc_akuno (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_akuno (Creature *pCreature)
UnitAI * GetAI_npc_hungry_nether_ray (Creature *pCreature)
UnitAI * GetAI_npc_letoll (Creature *pCreature)
bool QuestAccept_npc_letoll (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
bool QuestAccept_npc_isla_starmane (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_isla_starmane (Creature *pCreature)
bool QuestAccept_npc_skywing (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_skywing (Creature *pCreature)
UnitAI * GetAI_npc_cenarion_sparrowhawk (Creature *pCreature)
UnitAI * GetAI_npc_skyguard_prisoner (Creature *pCreature)
bool QuestAccept_npc_skyguard_prisoner (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AttackPlayerWithQuest (Creature *creature)
UnitAI * GetAI_npc_avatar_of_terokk (Creature *pCreature)
UnitAI * GetAI_npc_minion_of_terokk (Creature *pCreature)
GameObjectAI * GetAI_go_monstrous_kaliri_egg (GameObject *go)
void AddSC_terokkar_forest ()
Variables
const uint32 netherwebVictims [6]
static float m_afAmbushB1 [] = { -2895.525879f, 5336.431641f, -11.800f}
static float m_afAmbushB2 [] = { -2890.604980f, 5331.938965f, -11.282f}
static const float aLuangaSpawnCoords [3] = { -3507.203f, 4084.619f, 92.947f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SUBMIT
FACTION_FRIENDLY
SPELL_PULVERIZE
SPELL_QUID9889
Definition at line 44 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_FREED_WARRIOR
QUEST_TAKEN_IN_NIGHT
Definition at line 137 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_AKU_START
SAY_AKU_AMBUSH_A
SAY_AKU_AMBUSH_B
SAY_AKU_AMBUSH_B_REPLY
SAY_AKU_COMPLETE
SPELL_CHAIN_LIGHTNING
QUEST_ESCAPING_TOMB
NPC_CABAL_SKIRMISHER
Definition at line 187 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_FEED
NPC_BLACK_WARP_CHASER
SPELL_FEED_CREDIT
Definition at line 291 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_LE_START
SAY_LE_KEEP_SAFE
SAY_LE_NORTH
SAY_LE_ARRIVE
SAY_LE_BURIED
SAY_LE_ALMOST
SAY_LE_DRUM
SAY_LE_DRUM_REPLY
SAY_LE_DISCOVERY
SAY_LE_DISCOVERY_REPLY
SAY_LE_NO_LEAVE
SAY_LE_NO_LEAVE_REPLY1
SAY_LE_NO_LEAVE_REPLY2
SAY_LE_NO_LEAVE_REPLY3
SAY_LE_NO_LEAVE_REPLY4
SAY_LE_SHUT
SAY_LE_REPLY_HEAR
SAY_LE_IN_YOUR_FACE
SAY_LE_HELP_HIM
EMOTE_LE_PICK_UP
SAY_LE_THANKS
QUEST_DIGGING_BONES
NPC_RESEARCHER
NPC_BONE_SIFTER
MAX_RESEARCHER
Definition at line 379 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ESCAPE_FROM_FIREWING_POINT_A
QUEST_ESCAPE_FROM_FIREWING_POINT_H
SAY_ISLA_PERIODIC_1
SAY_ISLA_PERIODIC_2
SAY_ISLA_PERIODIC_3
SAY_ISLA_START
SAY_ISLA_WAITING
SAY_ISLA_LEAVE_BUILDING
GO_CAGE
SPELL_ENTANGLING_ROOTS
SPELL_MOONFIRE
SPELL_WRATH
SPELL_TRAVELFORM
Definition at line 631 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_SKYWING_START
SAY_SKYWING_TREE_DOWN
SAY_SKYWING_TREE_UP
SAY_SKYWING_JUMP
SAY_SKYWING_SUMMON
SAY_SKYWING_END
SPELL_FEATHERY_CYCLONE_BURST
SPELL_RILAK_THE_REDEEMED
NPC_LUANGA_THE_IMPRISONER
QUEST_SKYWING
Definition at line 781 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
EMOTE_FOLLOW
EMOTE_SURVEY
EMOTE_LOCATE
NPC_SKETTIS_RAVEN_STONE
GO_RAVEN_STONE
Definition at line 907 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_ESCORT_START
SAY_AMBUSH_END
SAY_ESCORT_COMPLETE
SAY_AMBUSH_1
SAY_AMBUSH_2
SAY_AMBUSH_3
SAY_AMBUSH_4
NPC_WING_GUARD
GO_PRISONER_CAGE
QUEST_ID_ESCAPE_SKETTIS
SPELL_PORT_LOCATION_1
SPELL_PORT_LOCATION_2
SPELL_PORT_LOCATION_3
SPELL_CAGE_SUMMON
Definition at line 998 of file terokkar_forest.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_TERRIFYING_SCREECH
SPELL_FEATHER_BURST
SAY_DEFENDER_GRASHNA
NPC_DEFENDER_GRASHNA
QUEST_SKETTIS_OFFENSIVE
Definition at line 1146 of file terokkar_forest.cpp.
Function Documentation
AddSC_terokkar_forest()
void AddSC_terokkar_forest ()
Definition at line 1290 of file terokkar_forest.cpp.
References Script::GetAI, GetAI_go_monstrous_kaliri_egg(), GetAI_mob_netherweb_victim(), GetAI_mob_unkor_the_ruthless(), GetAI_npc_akuno(), GetAI_npc_avatar_of_terokk(), GetAI_npc_cenarion_sparrowhawk(), GetAI_npc_hungry_nether_ray(), GetAI_npc_isla_starmane(), GetAI_npc_letoll(), GetAI_npc_minion_of_terokk(), GetAI_npc_skyguard_prisoner(), GetAI_npc_skywing(), Script::GetGameObjectAI, Script::Name, Script::pQuestAcceptNPC, QuestAccept_npc_akuno(), QuestAccept_npc_isla_starmane(), QuestAccept_npc_letoll(), QuestAccept_npc_skyguard_prisoner(), QuestAccept_npc_skywing(), and Script::RegisterSelf().
Referenced by AddScripts().
AttackPlayerWithQuest()
void AttackPlayerWithQuest (Creature * creature)
Definition at line 1158 of file terokkar_forest.cpp.
References Creature::AI(), UnitAI::AttackStart(), GetPlayerListWithEntryInWorld(), and QUEST_SKETTIS_OFFENSIVE.
Referenced by npc_avatar_of_terokkAI::JustRespawned(), and npc_minion_of_terokkAI::JustRespawned().
GetAI_go_monstrous_kaliri_egg()
GameObjectAI* GetAI_go_monstrous_kaliri_egg (GameObject * go)
Definition at line 1275 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_mob_netherweb_victim()
UnitAI* GetAI_mob_netherweb_victim (Creature * pCreature)
Definition at line 178 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_mob_unkor_the_ruthless()
UnitAI* GetAI_mob_unkor_the_ruthless (Creature * pCreature)
Definition at line 128 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_akuno()
UnitAI* GetAI_npc_akuno (Creature * pCreature)
Definition at line 282 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_avatar_of_terokk()
UnitAI* GetAI_npc_avatar_of_terokk (Creature * pCreature)
Definition at line 1218 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_cenarion_sparrowhawk()
UnitAI* GetAI_npc_cenarion_sparrowhawk (Creature * pCreature)
Definition at line 989 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_hungry_nether_ray()
UnitAI* GetAI_npc_hungry_nether_ray (Creature * pCreature)
Definition at line 370 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_isla_starmane()
UnitAI* GetAI_npc_isla_starmane (Creature * pCreature)
Definition at line 772 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_letoll()
UnitAI* GetAI_npc_letoll (Creature * pCreature)
Definition at line 604 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_minion_of_terokk()
UnitAI* GetAI_npc_minion_of_terokk (Creature * pCreature)
Definition at line 1255 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_skyguard_prisoner()
UnitAI* GetAI_npc_skyguard_prisoner (Creature * pCreature)
Definition at line 1130 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
GetAI_npc_skywing()
UnitAI* GetAI_npc_skywing (Creature * pCreature)
Definition at line 898 of file terokkar_forest.cpp.
Referenced by AddSC_terokkar_forest().
QuestAccept_npc_akuno()
bool QuestAccept_npc_akuno (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 266 of file terokkar_forest.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_ESCAPING_TOMB, SAY_AKU_START, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_terokkar_forest().
QuestAccept_npc_isla_starmane()
bool QuestAccept_npc_isla_starmane (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 759 of file terokkar_forest.cpp.
References Creature::AI(), ALLIANCE, FACTION_ESCORT_A_NEUTRAL_ACTIVE, FACTION_ESCORT_H_NEUTRAL_ACTIVE, Quest::GetQuestId(), Player::GetTeam(), QUEST_ESCAPE_FROM_FIREWING_POINT_A, QUEST_ESCAPE_FROM_FIREWING_POINT_H, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_terokkar_forest().
QuestAccept_npc_letoll()
bool QuestAccept_npc_letoll (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 609 of file terokkar_forest.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_DIGGING_BONES, SAY_LE_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_terokkar_forest().
QuestAccept_npc_skyguard_prisoner()
bool QuestAccept_npc_skyguard_prisoner (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 1135 of file terokkar_forest.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_ID_ESCAPE_SKETTIS, and UnitAI::SendAIEvent().
Referenced by AddSC_terokkar_forest().
QuestAccept_npc_skywing()
bool QuestAccept_npc_skywing (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 883 of file terokkar_forest.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_N_NEUTRAL_PASSIVE, Quest::GetQuestId(), QUEST_SKYWING, SAY_SKYWING_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_terokkar_forest().
Variable Documentation
aLuangaSpawnCoords
const float aLuangaSpawnCoords[3] = { -3507.203f, 4084.619f, 92.947f} static
Definition at line 798 of file terokkar_forest.cpp.
Referenced by npc_skywingAI::WaypointReached().
m_afAmbushB1
float m_afAmbushB1[] = { -2895.525879f, 5336.431641f, -11.800f} static
Definition at line 201 of file terokkar_forest.cpp.
Referenced by npc_akunoAI::WaypointReached().
m_afAmbushB2
float m_afAmbushB2[] = { -2890.604980f, 5331.938965f, -11.282f} static
Definition at line 202 of file terokkar_forest.cpp.
Referenced by npc_akunoAI::WaypointReached().
netherwebVictims
const uint32 netherwebVictims[6]
Initial value:
=
{
    18470, 16805, 21242, 18452, 22482, 21285
}
Definition at line 144 of file terokkar_forest.cpp.
Referenced by mob_netherweb_victimAI::JustDied().