CMaNGOS_WoTLK: the_barrens.cpp File Reference
the_barrens.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_giltharesAI
struct npc_taskmaster_fizzuleAI
struct npc_twiggy_flatheadAI
struct npc_wizzlecranks_shredderAI
struct npc_gallywixAI
struct npc_venture_co_lookoutAI
struct npc_foreman_silixizAI
struct SpawnPoint
struct npc_regthar_deathgateAI
struct npc_regthar_deathgateAI::KilledSlot
Macros
#define COUNTERATTACK_RESPAWN_TIME_HORDE 12
#define COUNTERATTACK_RESPAWN_TIME_HORDE_INC 1
#define COUNTERATTACK_RESPAWN_TIME_KOLKAR 10
Typedefs
typedef std::vector< SpawnPoint > SpawnPointVector
Enumerations
enum {
SAY_GIL_START = -1000370 , SAY_GIL_AT_LAST = -1000371 , SAY_GIL_PROCEED = -1000372 , SAY_GIL_FREEBOOTERS = -1000373 ,
SAY_GIL_AGGRO_1 = -1000374 , SAY_GIL_AGGRO_2 = -1000375 , SAY_GIL_AGGRO_3 = -1000376 , SAY_GIL_AGGRO_4 = -1000377 ,
SAY_GIL_ALMOST = -1000378 , SAY_GIL_SWEET = -1000379 , SAY_GIL_FREED = -1000380 , QUEST_FREE_FROM_HOLD = 898 ,
AREA_MERCHANT_COAST = 391
}
enum {
FACTION_FRIENDLY_F = 35 , SPELL_FLARE = 10113 , SPELL_FOLLY = 10137 , FIZZULE_FLARE_1 = 1 ,
FIZZULE_FLARE_2 = 2 , FIZZULE_SALUTE = 3 , FIZZULE_WHISTLE = 4
}
enum {
SAY_BIG_WILL_READY = -1000123 , SAY_TWIGGY_BEGIN = -1000124 , SAY_TWIGGY_FRAY = -1000125 , SAY_TWIGGY_DOWN = -1000126 ,
SAY_TWIGGY_OVER = -1000127 , NPC_TWIGGY = 6248 , NPC_BIG_WILL = 6238 , NPC_AFFRAY_CHALLENGER = 6240 ,
QUEST_AFFRAY = 1719 , FACTION_FRIENDLY = 35 , FACTION_HOSTILE_WILL = 32 , FACTION_HOSTILE_CHALLENGER = 14 ,
MAX_CHALLENGERS = 6
}
enum {
SAY_START = -1000298 , SAY_STARTUP1 = -1000299 , SAY_STARTUP2 = -1000300 , SAY_MERCENARY = -1000301 ,
SAY_PROGRESS_1 = -1000302 , SAY_PROGRESS_2 = -1000303 , SAY_PROGRESS_3 = -1000304 , SAY_END = -1000305 ,
QUEST_ESCAPE = 863 , FACTION_RATCHET = 637 , NPC_PILOT_WIZZ = 3451 , NPC_MERCENARY = 3282
}
enum {
SPELL_DECIMATE = 10268 , SPELL_SLUSH = 10267 , SAY_STEALTH_ALERT_GALLYWIX = -1010005 , SAY_STEALTH_ALERT_SILIXIZ = -1010006 ,
SAY_STEALTH_ALERT_LOOKOUT_1 = -1010007 , SAY_STEALTH_ALERT_LOOKOUT_2 = -1010008
}
enum {
QUEST_COUNTERATTACK = 4021 , SAY_START_REGTHAR = -1010001 , SAY_DEFENDER = -1010002 , YELL_RETREAT = -1010003 ,
NPC_REGTHAR_DEATHGATE = 3389 , NPC_WARLORD_KROMZAR = 9456 , NPC_HORDE_DEFENDER = 9457 , NPC_HORDE_AXE_THROWER = 9458 ,
NPC_KOLKAR_INVADER = 9524 , NPC_KOLKAR_STORMSEER = 9523 , KILL_LIMIT = 20
}
Functions
UnitAI * GetAI_npc_gilthares (Creature *pCreature)
bool QuestAccept_npc_gilthares (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_taskmaster_fizzule (Creature *creature)
UnitAI * GetAI_npc_twiggy_flathead (Creature *pCreature)
bool AreaTrigger_at_twiggy_flathead (Player *pPlayer, AreaTriggerEntry const *)
bool QuestAccept_npc_wizzlecranks_shredder (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_wizzlecranks_shredder (Creature *pCreature)
UnitAI * GetAI_npc_gallywix (Creature *creature)
UnitAI * GetAI_npc_venture_co_lookout (Creature *creature)
UnitAI * GetAI_npc_foreman_silixiz (Creature *creature)
UnitAI * GetAI_npc_regthar_deathgate (Creature *creature)
bool GossipHello_npc_regthar_deathgate (Player *player, Creature *creature)
bool QuestAccept_npc_regthar_deathgate (Player *player, Creature *creature, Quest const *quest)
bool GossipSelect_npc_regthar_deathgate (Player *player, Creature *creature, uint32, uint32 action)
void AddSC_the_barrens ()
Variables
static const float aAffrayChallengerLoc [8][4]
static const SpawnPointVector spawnPointsHorde
static const SpawnPointVector spawnPointsKromzar
static const SpawnPointVector spawnPointsKolkar
Macro Definition Documentation
COUNTERATTACK_RESPAWN_TIME_HORDE
#define COUNTERATTACK_RESPAWN_TIME_HORDE 12
Definition at line 771 of file the_barrens.cpp.
COUNTERATTACK_RESPAWN_TIME_HORDE_INC
#define COUNTERATTACK_RESPAWN_TIME_HORDE_INC 1
Definition at line 772 of file the_barrens.cpp.
COUNTERATTACK_RESPAWN_TIME_KOLKAR
#define COUNTERATTACK_RESPAWN_TIME_KOLKAR 10
Definition at line 773 of file the_barrens.cpp.
Typedef Documentation
SpawnPointVector
typedef std::vector<SpawnPoint> SpawnPointVector
Definition at line 780 of file the_barrens.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GIL_START
SAY_GIL_AT_LAST
SAY_GIL_PROCEED
SAY_GIL_FREEBOOTERS
SAY_GIL_AGGRO_1
SAY_GIL_AGGRO_2
SAY_GIL_AGGRO_3
SAY_GIL_AGGRO_4
SAY_GIL_ALMOST
SAY_GIL_SWEET
SAY_GIL_FREED
QUEST_FREE_FROM_HOLD
AREA_MERCHANT_COAST
Definition at line 39 of file the_barrens.cpp.
anonymous enum
anonymous enum
Enumerator
FACTION_FRIENDLY_F
SPELL_FLARE
SPELL_FOLLY
FIZZULE_FLARE_1
FIZZULE_FLARE_2
FIZZULE_SALUTE
FIZZULE_WHISTLE
Definition at line 145 of file the_barrens.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_BIG_WILL_READY
SAY_TWIGGY_BEGIN
SAY_TWIGGY_FRAY
SAY_TWIGGY_DOWN
SAY_TWIGGY_OVER
NPC_TWIGGY
NPC_BIG_WILL
NPC_AFFRAY_CHALLENGER
QUEST_AFFRAY
FACTION_FRIENDLY
FACTION_HOSTILE_WILL
FACTION_HOSTILE_CHALLENGER
MAX_CHALLENGERS
Definition at line 275 of file the_barrens.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_STARTUP1
SAY_STARTUP2
SAY_MERCENARY
SAY_PROGRESS_1
SAY_PROGRESS_2
SAY_PROGRESS_3
SAY_END
QUEST_ESCAPE
FACTION_RATCHET
NPC_PILOT_WIZZ
NPC_MERCENARY
Definition at line 511 of file the_barrens.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_DECIMATE
SPELL_SLUSH
SAY_STEALTH_ALERT_GALLYWIX
SAY_STEALTH_ALERT_SILIXIZ
SAY_STEALTH_ALERT_LOOKOUT_1
SAY_STEALTH_ALERT_LOOKOUT_2
Definition at line 665 of file the_barrens.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_COUNTERATTACK
SAY_START_REGTHAR
SAY_DEFENDER
YELL_RETREAT
NPC_REGTHAR_DEATHGATE
NPC_WARLORD_KROMZAR
NPC_HORDE_DEFENDER
NPC_HORDE_AXE_THROWER
NPC_KOLKAR_INVADER
NPC_KOLKAR_STORMSEER
KILL_LIMIT
Definition at line 752 of file the_barrens.cpp.
Function Documentation
AddSC_the_barrens()
void AddSC_the_barrens ()
Definition at line 1095 of file the_barrens.cpp.
References AreaTrigger_at_twiggy_flathead(), Script::GetAI, GetAI_npc_foreman_silixiz(), GetAI_npc_gallywix(), GetAI_npc_gilthares(), GetAI_npc_regthar_deathgate(), GetAI_npc_taskmaster_fizzule(), GetAI_npc_twiggy_flathead(), GetAI_npc_venture_co_lookout(), GetAI_npc_wizzlecranks_shredder(), GossipHello_npc_regthar_deathgate(), GossipSelect_npc_regthar_deathgate(), Script::Name, Script::pAreaTrigger, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_gilthares(), QuestAccept_npc_regthar_deathgate(), QuestAccept_npc_wizzlecranks_shredder(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_twiggy_flathead()
bool AreaTrigger_at_twiggy_flathead (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 488 of file the_barrens.cpp.
References Creature::AI(), GetClosestCreatureWithEntry(), Player::GetQuestStatus(), Unit::IsAlive(), Player::IsGameMaster(), NPC_TWIGGY, QUEST_AFFRAY, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_the_barrens().
GetAI_npc_foreman_silixiz()
UnitAI* GetAI_npc_foreman_silixiz (Creature * creature)
Definition at line 743 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_gallywix()
UnitAI* GetAI_npc_gallywix (Creature * creature)
Definition at line 733 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_gilthares()
UnitAI* GetAI_npc_gilthares (Creature * pCreature)
Definition at line 121 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_regthar_deathgate()
UnitAI* GetAI_npc_regthar_deathgate (Creature * creature)
Definition at line 1050 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_taskmaster_fizzule()
UnitAI* GetAI_npc_taskmaster_fizzule (Creature * creature)
Definition at line 266 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_twiggy_flathead()
UnitAI* GetAI_npc_twiggy_flathead (Creature * pCreature)
Definition at line 483 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_venture_co_lookout()
UnitAI* GetAI_npc_venture_co_lookout (Creature * creature)
Definition at line 738 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GetAI_npc_wizzlecranks_shredder()
UnitAI* GetAI_npc_wizzlecranks_shredder (Creature * pCreature)
Definition at line 660 of file the_barrens.cpp.
Referenced by AddSC_the_barrens().
GossipHello_npc_regthar_deathgate()
bool GossipHello_npc_regthar_deathgate (Player * player, Creature * creature)
Definition at line 1055 of file the_barrens.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, Unit::isQuestGiver(), Player::PrepareQuestMenu(), QUEST_COUNTERATTACK, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_the_barrens().
GossipSelect_npc_regthar_deathgate()
bool GossipSelect_npc_regthar_deathgate (Player * player, Creature * creature, uint32 , uint32 action)
Definition at line 1083 of file the_barrens.cpp.
References Creature::AI(), DoScriptText(), GOSSIP_ACTION_INFO_DEF, and SAY_START_REGTHAR.
Referenced by AddSC_the_barrens().
QuestAccept_npc_gilthares()
bool QuestAccept_npc_gilthares (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 126 of file the_barrens.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_FREE_FROM_HOLD, SAY_GIL_START, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_the_barrens().
QuestAccept_npc_regthar_deathgate()
bool QuestAccept_npc_regthar_deathgate (Player * player, Creature * creature, Quest const * quest)
Definition at line 1071 of file the_barrens.cpp.
References Creature::AI(), DoScriptText(), Quest::GetQuestId(), QUEST_COUNTERATTACK, and SAY_START_REGTHAR.
Referenced by AddSC_the_barrens().
QuestAccept_npc_wizzlecranks_shredder()
bool QuestAccept_npc_wizzlecranks_shredder (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 647 of file the_barrens.cpp.
References Creature::AI(), DoScriptText(), FACTION_RATCHET, Quest::GetQuestId(), QUEST_ESCAPE, SAY_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_the_barrens().
Variable Documentation
aAffrayChallengerLoc
const float aAffrayChallengerLoc[8][4] static
Initial value:
=
{
    { -1683.0f, -4326.0f, 2.79f, 0.00f},
    { -1682.0f, -4329.0f, 2.79f, 0.00f},
    { -1683.0f, -4330.0f, 2.79f, 0.00f},
    { -1680.0f, -4334.0f, 2.79f, 1.49f},
    { -1674.0f, -4326.0f, 2.79f, 3.49f},
    { -1677.0f, -4334.0f, 2.79f, 1.66f},
    { -1713.79f, -4342.09f, 6.05f, 6.15f},
    { -1682.31f, -4329.68f, 2.78f, 0.0f},
}
Definition at line 296 of file the_barrens.cpp.
Referenced by npc_twiggy_flatheadAI::JustSummoned(), npc_twiggy_flatheadAI::SetChallengers(), and npc_twiggy_flatheadAI::UpdateAI().
spawnPointsHorde
const SpawnPointVector spawnPointsHorde static
Initial value:
{
    { -307.23f, -1919.84f, 91.66f, 0.64f},
    { -281.15f, -1906.39f, 91.66f, 1.88f},
    { -270.09f, -1901.58f, 91.66f, 1.88f},
    { -275.24f, -1901.96f, 91.66f, 1.90f},
    { -295.84f, -1913.58f, 91.66f, 1.86f},
    { -221.61f, -1936.54f, 94.00f, 0.41f},
    { -226.65f, -1927.87f, 93.24f, 0.41f},
}
Definition at line 782 of file the_barrens.cpp.
Referenced by npc_regthar_deathgateAI::StartEvent(), and npc_regthar_deathgateAI::UpdateAI().
spawnPointsKolkar
const SpawnPointVector spawnPointsKolkar static
Initial value:
{
    { -290.26f, -1860.85f, 92.48f, 3.68f},
    { -311.46f, -1871.16f, 92.64f, 6.06f},
    { -321.75f, -1868.48f, 93.73f, 0.30f},
    { -338.12f, -1852.10f, 94.09f, 0.01f},
    { -311.46f, -1847.78f, 94.93f, 6.15f},
    { -292.02f, -1840.00f, 93.06f, 3.51f},
    { -267.14f, -1853.97f, 93.24f, 3.52f},
    { -267.68f, -1832.77f, 92.69f, 3.52f},
    { -279.70f, -1845.67f, 92.81f, 3.83f},
    { -338.99f, -1868.68f, 93.50f, 0.17f},
    { -210.28f, -1916.22f, 92.87f, 4.89f},
    { -209.09f, -1922.44f, 93.26f, 3.87f},
    { -206.64f, -1924.83f, 93.78f, 2.41f},
    { -283.57f, -1883.91f, 92.60f, 3.53f},
    { -197.50f, -1929.31f, 94.03f, 3.51f}
}
Definition at line 800 of file the_barrens.cpp.
Referenced by npc_regthar_deathgateAI::StartEvent(), and npc_regthar_deathgateAI::UpdateAI().
spawnPointsKromzar
const SpawnPointVector spawnPointsKromzar static
Initial value:
{
    { -281.19f, -1855.54f, 92.58f, 4.85f},
    { -283.66f, -1858.45f, 92.47f, 4.85f},
    { -286.50f, -1856.18f, 92.44f, 4.85f}
}
Definition at line 793 of file the_barrens.cpp.
Referenced by npc_regthar_deathgateAI::UpdateAI().