CMaNGOS_WoTLK: thousand_needles.cpp File Reference
thousand_needles.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
Data Structures
struct npc_kanatiAI
struct npc_lakota_windsongAI
struct npc_paoka_swiftmountainAI
struct npc_plucky_johnsonAI
Macros
#define GOSSIP_ITEM_QUEST "Please tell me the Phrase.."
Enumerations
enum {
SAY_KAN_START = 6149 , QUEST_PROTECT_KANATI = 4966 , NPC_GALAK_ASS = 10720 , FACTION_KANATI_ESCORT = 232 ,
PATH_ID_KANATI = 10638
}
enum {
SAY_LAKO_START = -1000365 , SAY_LAKO_LOOK_OUT = -1000366 , SAY_LAKO_HERE_COME = -1000367 , SAY_LAKO_MORE = -1000368 ,
SAY_LAKO_END = -1000369 , QUEST_FREE_AT_LAST = 4904 , NPC_GRIM_BANDIT = 10758 , ID_AMBUSH_1 = 0 ,
ID_AMBUSH_2 = 2 , ID_AMBUSH_3 = 4
}
enum {
SAY_START = -1000362 , SAY_WYVERN = -1000363 , SAY_COMPLETE = -1000364 , QUEST_HOMEWARD = 4770 ,
NPC_WYVERN = 4107
}
enum { FACTION_FRIENDLY = 35 , QUEST_SCOOP = 1950 , SPELL_PLUCKY_HUMAN = 9192 , SPELL_PLUCKY_CHICKEN = 9220 }
Functions
bool QuestAccept_npc_kanati (Player *player, Creature *creature, const Quest *quest)
UnitAI * GetAI_npc_lakota_windsong (Creature *pCreature)
bool QuestAccept_npc_lakota_windsong (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_paoka_swiftmountain (Creature *pCreature)
bool QuestAccept_npc_paoka_swiftmountain (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_plucky_johnson (Creature *pCreature)
bool GossipHello_npc_plucky_johnson (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_plucky_johnson (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_thousand_needles ()
Variables
const float m_afGalakLoc [] = { -4867.387695f, -1357.353760f, -48.226f}
float m_afBanditLoc [6][6]
float m_afWyvernLoc [3][3]
Macro Definition Documentation
GOSSIP_ITEM_QUEST
#define GOSSIP_ITEM_QUEST "Please tell me the Phrase.."
Definition at line 287 of file thousand_needles.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_KAN_START
QUEST_PROTECT_KANATI
NPC_GALAK_ASS
FACTION_KANATI_ESCORT
PATH_ID_KANATI
Definition at line 39 of file thousand_needles.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_LAKO_START
SAY_LAKO_LOOK_OUT
SAY_LAKO_HERE_COME
SAY_LAKO_MORE
SAY_LAKO_END
QUEST_FREE_AT_LAST
NPC_GRIM_BANDIT
ID_AMBUSH_1
ID_AMBUSH_2
ID_AMBUSH_3
Definition at line 107 of file thousand_needles.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_START
SAY_WYVERN
SAY_COMPLETE
QUEST_HOMEWARD
NPC_WYVERN
Definition at line 203 of file thousand_needles.cpp.
anonymous enum
anonymous enum
Enumerator
FACTION_FRIENDLY
QUEST_SCOOP
SPELL_PLUCKY_HUMAN
SPELL_PLUCKY_CHICKEN
Definition at line 279 of file thousand_needles.cpp.
Function Documentation
AddSC_thousand_needles()
void AddSC_thousand_needles ()
Definition at line 379 of file thousand_needles.cpp.
References Script::GetAI, GetAI_npc_lakota_windsong(), GetAI_npc_paoka_swiftmountain(), GetAI_npc_plucky_johnson(), GossipHello_npc_plucky_johnson(), GossipSelect_npc_plucky_johnson(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_kanati(), QuestAccept_npc_lakota_windsong(), QuestAccept_npc_paoka_swiftmountain(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_lakota_windsong()
UnitAI* GetAI_npc_lakota_windsong (Creature * pCreature)
Definition at line 181 of file thousand_needles.cpp.
Referenced by AddSC_thousand_needles().
GetAI_npc_paoka_swiftmountain()
UnitAI* GetAI_npc_paoka_swiftmountain (Creature * pCreature)
Definition at line 257 of file thousand_needles.cpp.
Referenced by AddSC_thousand_needles().
GetAI_npc_plucky_johnson()
UnitAI* GetAI_npc_plucky_johnson (Creature * pCreature)
Definition at line 354 of file thousand_needles.cpp.
Referenced by AddSC_thousand_needles().
GossipHello_npc_plucky_johnson()
bool GossipHello_npc_plucky_johnson (Player * pPlayer, Creature * pCreature)
Definition at line 359 of file thousand_needles.cpp.
References Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_QUEST, GOSSIP_SENDER_MAIN, QUEST_SCOOP, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_thousand_needles().
GossipSelect_npc_plucky_johnson()
bool GossipSelect_npc_plucky_johnson (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 368 of file thousand_needles.cpp.
References Player::AreaExploredOrEventHappens(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, and QUEST_SCOOP.
Referenced by AddSC_thousand_needles().
QuestAccept_npc_kanati()
bool QuestAccept_npc_kanati (Player * player, Creature * creature, const Quest * quest)
Definition at line 90 of file thousand_needles.cpp.
References Creature::AI(), FACTION_KANATI_ESCORT, Quest::GetQuestId(), PATH_ID_KANATI, QUEST_PROTECT_KANATI, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_thousand_needles().
QuestAccept_npc_lakota_windsong()
bool QuestAccept_npc_lakota_windsong (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 186 of file thousand_needles.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_FREE_AT_LAST, SAY_LAKO_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_thousand_needles().
QuestAccept_npc_paoka_swiftmountain()
bool QuestAccept_npc_paoka_swiftmountain (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 262 of file thousand_needles.cpp.
References Creature::AI(), DoScriptText(), FACTION_ESCORT_H_NEUTRAL_ACTIVE, Quest::GetQuestId(), QUEST_HOMEWARD, SAY_START, Creature::SetFactionTemporary(), and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_thousand_needles().
Variable Documentation
m_afBanditLoc
float m_afBanditLoc[6][6]
Initial value:
=
{
    { -4905.479492f, -2062.732666f, 84.352f},
    { -4915.201172f, -2073.528320f, 84.733f},
    { -4878.883301f, -1986.947876f, 91.966f},
    { -4877.503906f, -1966.113403f, 91.859f},
    { -4767.985352f, -1873.169189f, 90.192f},
    { -4788.861328f, -1888.007813f, 89.888f}
}
Definition at line 123 of file thousand_needles.cpp.
Referenced by npc_lakota_windsongAI::DoSpawnBandits().
m_afGalakLoc
const float m_afGalakLoc[] = { -4867.387695f, -1357.353760f, -48.226f}
Definition at line 51 of file thousand_needles.cpp.
Referenced by npc_kanatiAI::DoSpawnGalak().
m_afWyvernLoc
float m_afWyvernLoc[3][3]
Initial value:
=
{
    { -4990.606f, -906.057f, -5.343f},
    { -4970.241f, -927.378f, -4.951f},
    { -4985.364f, -952.528f, -5.199f}
}
Definition at line 213 of file thousand_needles.cpp.
Referenced by npc_paoka_swiftmountainAI::DoSpawnWyvern().