CMaNGOS_WoTLK: TicketCommands.cpp File Reference
TicketCommands.cpp File Reference
#include "Common.h"
#include "Chat.h"
#include "Globals/ObjectMgr.h"
#include "GMTickets/GMTicketMgr.h"
#include "Mails/Mail.h"
#include "Tools/Language.h"
Functions
static bool HandleTicketMgrCommandResult (ChatHandler &ch, uint32 ticketId, GMTicketMgr::CommandResult result)
Function Documentation
HandleTicketMgrCommandResult()
static bool HandleTicketMgrCommandResult (ChatHandler & ch, uint32 ticketId, GMTicketMgr::CommandResult result) inline static
Definition at line 27 of file TicketCommands.cpp.
References GMTicketMgr::COMMAND_RESULT_ACCESS_DENIED, GMTicketMgr::COMMAND_RESULT_PLAYER_OFFLINE, GMTicketMgr::COMMAND_RESULT_SUCCESS, GMTicketMgr::COMMAND_RESULT_TICKET_NOT_ASSIGNED, GMTicketMgr::COMMAND_RESULT_TICKET_NOT_FOUND, GMTicketMgr::COMMAND_RESULT_TICKET_UNSEEN, GMTicket::GetIdTag(), LANG_COMMAND_TICKET_ACCESS_DENIED, LANG_COMMAND_TICKET_NOT_ASSIGNED, LANG_COMMAND_TICKET_NOT_FOUND, LANG_COMMAND_TICKET_PLAYER_OFFLINE, LANG_COMMAND_TICKET_UNSEEN, and ChatHandler::PSendSysMessage().
Referenced by ChatHandler::HandleTicketDiscardCommand(), ChatHandler::HandleTicketEscalateCommand(), ChatHandler::HandleTicketNoteCommand(), ChatHandler::HandleTicketReadCommand(), ChatHandler::HandleTicketResolveCommand(), ChatHandler::HandleTicketSortCommand(), and ChatHandler::HandleTicketWhisperCommand().