CMaNGOS_WoTLK: tirisfal_glades.cpp File Reference
tirisfal_glades.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
Data Structures
struct npc_calvin_montagueAI
Enumerations
enum { QUEST_ULAG = 1819 , NPC_ULAG = 6390 , GO_TRIGGER = 104593 , GO_DOOR = 176594 }
enum { SAY_COMPLETE = -1000356 , SD_SPELL_DRINK = 2639 , QUEST_590 = 590 , FACTION_HOSTILE = 168 }
Functions
bool GOUse_go_mausoleum_door (Player *pPlayer, GameObject *)
bool GOUse_go_mausoleum_trigger (Player *pPlayer, GameObject *pGo)
UnitAI * GetAI_npc_calvin_montague (Creature *pCreature)
bool QuestAccept_npc_calvin_montague (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
void AddSC_tirisfal_glades ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
QUEST_ULAG
NPC_ULAG
GO_TRIGGER
GO_DOOR
Definition at line 37 of file tirisfal_glades.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_COMPLETE
SD_SPELL_DRINK
QUEST_590
FACTION_HOSTILE
Definition at line 79 of file tirisfal_glades.cpp.
Function Documentation
AddSC_tirisfal_glades()
void AddSC_tirisfal_glades ()
Definition at line 179 of file tirisfal_glades.cpp.
References Script::GetAI, GetAI_npc_calvin_montague(), GOUse_go_mausoleum_door(), GOUse_go_mausoleum_trigger(), Script::Name, Script::pGOUse, Script::pQuestAcceptNPC, QuestAccept_npc_calvin_montague(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_calvin_montague()
UnitAI* GetAI_npc_calvin_montague (Creature * pCreature)
Definition at line 163 of file tirisfal_glades.cpp.
Referenced by AddSC_tirisfal_glades().
GOUse_go_mausoleum_door()
bool GOUse_go_mausoleum_door (Player * pPlayer, GameObject *)
Definition at line 45 of file tirisfal_glades.cpp.
References GetClosestGameObjectWithEntry(), Player::GetQuestStatus(), GO_STATE_READY, GO_TRIGGER, NPC_ULAG, QUEST_STATUS_INCOMPLETE, QUEST_ULAG, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_OR_DEAD_DESPAWN.
Referenced by AddSC_tirisfal_glades().
GOUse_go_mausoleum_trigger()
bool GOUse_go_mausoleum_trigger (Player * pPlayer, GameObject * pGo)
Definition at line 60 of file tirisfal_glades.cpp.
References GAMEOBJECT_FLAGS, GetClosestGameObjectWithEntry(), Player::GetQuestStatus(), GO_DOOR, GO_FLAG_INTERACT_COND, GO_STATE_ACTIVE, QUEST_STATUS_INCOMPLETE, QUEST_ULAG, and GameObject::SetGoState().
Referenced by AddSC_tirisfal_glades().
QuestAccept_npc_calvin_montague()
bool QuestAccept_npc_calvin_montague (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 168 of file tirisfal_glades.cpp.
References Creature::AI(), UnitAI::AttackStart(), FACTION_HOSTILE, Quest::GetQuestId(), QUEST_590, Creature::SetFactionTemporary(), Unit::SetImmuneToPlayer(), TEMPFACTION_RESTORE_COMBAT_STOP, and TEMPFACTION_RESTORE_RESPAWN.
Referenced by AddSC_tirisfal_glades().