CMaNGOS_WoTLK: trial_of_the_crusaderScripts.cpp File Reference
trial_of_the_crusaderScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_crusader.h"
Data Structures
struct RamseyInfo
struct npc_barrett_ramseyAI
Enumerations
enum {
GOSSIP_TEXT_BEAST_INIT = 14664 , GOSSIP_TEXT_BEAST_START = 14665 , GOSSIP_TEXT_BEAST_WIPE_INIT = 14667 , GOSSIP_TEXT_BEAST_WIPE_START = 14668 ,
GOSSIP_TEXT_JARAXXUS_INIT = 14678 , GOSSIP_TEXT_JARAXXUS_START = 14680 , GOSSIP_TEXT_JARAXXUS_WIPE_INIT = 14679 , GOSSIP_TEXT_JARAXXUS_WIPE_START = 14682 ,
GOSSIP_TEXT_PVP_INIT = 14813 , GOSSIP_TEXT_PVP_START = 14814 , GOSSIP_TEXT_PVP_WIPE_INIT = 14815 , GOSSIP_TEXT_PVP_WIPE_START = 14816 ,
GOSSIP_TEXT_TWINS_INIT = 14819 , GOSSIP_TEXT_TWINS_START = 14821 , GOSSIP_TEXT_TWINS_WIPE_INIT = 14820 , GOSSIP_TEXT_TWINS_WIPE_START = 14822 ,
GOSSIP_TEXT_ANUB_INIT = 14828 , GOSSIP_TEXT_ANUB_START = 14829 , GOSSIP_ITEM_BEAST_INIT = -3649000 , GOSSIP_ITEM_BEAST_START = -3649001 ,
GOSSIP_ITEM_BEAST_WIPE_INIT = -3649002 , GOSSIP_ITEM_BEAST_WIPE_START = -3649014 , GOSSIP_ITEM_JARAXXUS_INIT = -3649003 , GOSSIP_ITEM_JARAXXUS_START = -3649011 ,
GOSSIP_ITEM_JARAXXUS_WIPE_INIT = -3649004 , GOSSIP_ITEM_JARAXXUS_WIPE_START = -3649015 , GOSSIP_ITEM_PVP_INIT = -3649005 , GOSSIP_ITEM_PVP_START = -3649006 ,
GOSSIP_ITEM_PVP_WIPE_INIT = -3649012 , GOSSIP_ITEM_PVP_WIPE_START = -3649013 , GOSSIP_ITEM_TWINS_INIT = -3649007 , GOSSIP_ITEM_TWINS_START = -3649008 ,
GOSSIP_ITEM_TWINS_WIPE_INIT = -3649016 , GOSSIP_ITEM_TWINS_WIPE_START = -3649017 , GOSSIP_ITEM_ANUB_INIT = -3649009 , GOSSIP_ITEM_ANUB_START = -3649010
}
Functions
bool GossipHello_npc_barrett_ramsey (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_barrett_ramsey (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
UnitAI * GetAI_npc_barrett_ramsey (Creature *pCreature)
void AddSC_trial_of_the_crusader ()
Variables
static const RamseyInfo aRamseyInfo []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_TEXT_BEAST_INIT
GOSSIP_TEXT_BEAST_START
GOSSIP_TEXT_BEAST_WIPE_INIT
GOSSIP_TEXT_BEAST_WIPE_START
GOSSIP_TEXT_JARAXXUS_INIT
GOSSIP_TEXT_JARAXXUS_START
GOSSIP_TEXT_JARAXXUS_WIPE_INIT
GOSSIP_TEXT_JARAXXUS_WIPE_START
GOSSIP_TEXT_PVP_INIT
GOSSIP_TEXT_PVP_START
GOSSIP_TEXT_PVP_WIPE_INIT
GOSSIP_TEXT_PVP_WIPE_START
GOSSIP_TEXT_TWINS_INIT
GOSSIP_TEXT_TWINS_START
GOSSIP_TEXT_TWINS_WIPE_INIT
GOSSIP_TEXT_TWINS_WIPE_START
GOSSIP_TEXT_ANUB_INIT
GOSSIP_TEXT_ANUB_START
GOSSIP_ITEM_BEAST_INIT
GOSSIP_ITEM_BEAST_START
GOSSIP_ITEM_BEAST_WIPE_INIT
GOSSIP_ITEM_BEAST_WIPE_START
GOSSIP_ITEM_JARAXXUS_INIT
GOSSIP_ITEM_JARAXXUS_START
GOSSIP_ITEM_JARAXXUS_WIPE_INIT
GOSSIP_ITEM_JARAXXUS_WIPE_START
GOSSIP_ITEM_PVP_INIT
GOSSIP_ITEM_PVP_START
GOSSIP_ITEM_PVP_WIPE_INIT
GOSSIP_ITEM_PVP_WIPE_START
GOSSIP_ITEM_TWINS_INIT
GOSSIP_ITEM_TWINS_START
GOSSIP_ITEM_TWINS_WIPE_INIT
GOSSIP_ITEM_TWINS_WIPE_START
GOSSIP_ITEM_ANUB_INIT
GOSSIP_ITEM_ANUB_START
Definition at line 27 of file trial_of_the_crusaderScripts.cpp.
Function Documentation
AddSC_trial_of_the_crusader()
void AddSC_trial_of_the_crusader ()
Definition at line 208 of file trial_of_the_crusaderScripts.cpp.
References Script::GetAI, GetAI_npc_barrett_ramsey(), GossipHello_npc_barrett_ramsey(), GossipSelect_npc_barrett_ramsey(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_barrett_ramsey()
UnitAI* GetAI_npc_barrett_ramsey (Creature * pCreature)
Definition at line 203 of file trial_of_the_crusaderScripts.cpp.
Referenced by AddSC_trial_of_the_crusader().
GossipHello_npc_barrett_ramsey()
bool GossipHello_npc_barrett_ramsey (Player * pPlayer, Creature * pCreature)
Definition at line 123 of file trial_of_the_crusaderScripts.cpp.
References aRamseyInfo, countof, FAIL, InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, RamseyInfo::uiEntry, and RamseyInfo::uiOptionId.
Referenced by AddSC_trial_of_the_crusader().
GossipSelect_npc_barrett_ramsey()
bool GossipSelect_npc_barrett_ramsey (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 160 of file trial_of_the_crusaderScripts.cpp.
References aRamsayPositions, aRamseyInfo, FAIL, InstanceData::GetData(), Object::GetEntry(), WorldObject::GetInstanceData(), Unit::GetMotionMaster(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_SENDER_MAIN, MotionMaster::MovePoint(), NOT_STARTED, Object::RemoveFlag(), InstanceData::SetData(), Object::SetFlag(), SPECIAL, UNIT_FIELD_FLAGS, UNIT_FLAG_UNINTERACTIBLE, UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_trial_of_the_crusader().
Variable Documentation
aRamseyInfo
const RamseyInfo aRamseyInfo[] static
Initial value:
=
{
    {NPC_RAMSEY_1, GOSSIP_TEXT_BEAST_INIT,  GOSSIP_ITEM_BEAST_INIT,  GOSSIP_TEXT_BEAST_WIPE_INIT,  GOSSIP_ITEM_BEAST_WIPE_INIT,  0},
    {NPC_RAMSEY_1, GOSSIP_TEXT_BEAST_START, GOSSIP_ITEM_BEAST_START, GOSSIP_TEXT_BEAST_WIPE_START, GOSSIP_ITEM_BEAST_WIPE_START, TYPE_NORTHREND_BEASTS},
    {NPC_RAMSEY_2, GOSSIP_TEXT_JARAXXUS_INIT,  GOSSIP_ITEM_JARAXXUS_INIT,  GOSSIP_TEXT_JARAXXUS_WIPE_INIT,  GOSSIP_ITEM_JARAXXUS_WIPE_INIT,  0},
    {NPC_RAMSEY_2, GOSSIP_TEXT_JARAXXUS_START, GOSSIP_ITEM_JARAXXUS_START, GOSSIP_TEXT_JARAXXUS_WIPE_START, GOSSIP_ITEM_JARAXXUS_WIPE_START, TYPE_JARAXXUS},
    {NPC_RAMSEY_3, GOSSIP_TEXT_PVP_INIT,  GOSSIP_ITEM_PVP_INIT,  GOSSIP_TEXT_PVP_WIPE_INIT,  GOSSIP_ITEM_PVP_WIPE_INIT,  0},
    {NPC_RAMSEY_3, GOSSIP_TEXT_PVP_START, GOSSIP_ITEM_PVP_START, GOSSIP_TEXT_PVP_WIPE_START, GOSSIP_ITEM_PVP_WIPE_START, TYPE_FACTION_CHAMPIONS},
    {NPC_RAMSEY_4, GOSSIP_TEXT_TWINS_INIT,  GOSSIP_ITEM_TWINS_INIT,  GOSSIP_TEXT_TWINS_WIPE_INIT,  GOSSIP_ITEM_TWINS_WIPE_INIT,  0},
    {NPC_RAMSEY_4, GOSSIP_TEXT_TWINS_START, GOSSIP_ITEM_TWINS_START, GOSSIP_TEXT_TWINS_WIPE_START, GOSSIP_ITEM_TWINS_WIPE_START, TYPE_TWIN_VALKYR},
    {NPC_RAMSEY_5, GOSSIP_TEXT_ANUB_INIT,  GOSSIP_ITEM_ANUB_INIT,  0,  0,  0},
    {NPC_RAMSEY_5, GOSSIP_TEXT_ANUB_START, GOSSIP_ITEM_ANUB_START, 0, 0, TYPE_ANUBARAK},
}
Definition at line 90 of file trial_of_the_crusaderScripts.cpp.
Referenced by GossipHello_npc_barrett_ramsey(), and GossipSelect_npc_barrett_ramsey().