CMaNGOS_WoTLK: trial_of_the_champion.cpp File Reference
trial_of_the_champion.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "trial_of_the_champion.h"
Enumerations
enum {
GOSSIP_ITEM_READY = -3650000 , GOSSIP_ITEM_READY_SKIP_INTRO = -3650001 , GOSSIP_ITEM_READY_NEXT_CHALLENGE = -3650002 , TEXT_ID_READY_FIRST_CHALLENGE = 14688 ,
TEXT_ID_READY_NEXT_CHALLENGE = 14737 , TEXT_ID_READY_FINAL_CHALLENGE = 14738
}
Functions
bool GossipHello_npc_toc_herald (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_toc_herald (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
void AddSC_trial_of_the_champion ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_READY
GOSSIP_ITEM_READY_SKIP_INTRO
GOSSIP_ITEM_READY_NEXT_CHALLENGE
TEXT_ID_READY_FIRST_CHALLENGE
TEXT_ID_READY_NEXT_CHALLENGE
TEXT_ID_READY_FINAL_CHALLENGE
Definition at line 31 of file trial_of_the_champion.cpp.
Function Documentation
AddSC_trial_of_the_champion()
void AddSC_trial_of_the_champion ()
Definition at line 96 of file trial_of_the_champion.cpp.
References GossipHello_npc_toc_herald(), GossipSelect_npc_toc_herald(), Script::Name, Script::pGossipHello, Script::pGossipSelect, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_npc_toc_herald()
bool GossipHello_npc_toc_herald (Player * pPlayer, Creature * pCreature)
Definition at line 42 of file trial_of_the_champion.cpp.
References DONE, instance_trial_of_the_champion::GetData(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_READY, GOSSIP_ITEM_READY_NEXT_CHALLENGE, GOSSIP_ITEM_READY_SKIP_INTRO, GOSSIP_SENDER_MAIN, NOT_STARTED, TEXT_ID_READY_FINAL_CHALLENGE, TEXT_ID_READY_FIRST_CHALLENGE, TEXT_ID_READY_NEXT_CHALLENGE, TYPE_ARGENT_CHAMPION, TYPE_BLACK_KNIGHT, and TYPE_GRAND_CHAMPIONS.
Referenced by AddSC_trial_of_the_champion().
GossipSelect_npc_toc_herald()
bool GossipSelect_npc_toc_herald (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 68 of file trial_of_the_champion.cpp.
References instance_trial_of_the_champion::DoPrepareArgentChallenge(), instance_trial_of_the_champion::DoPrepareBlackKnight(), instance_trial_of_the_champion::DoPrepareChampions(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, Object::RemoveFlag(), UNIT_NPC_FLAG_GOSSIP, and UNIT_NPC_FLAGS.
Referenced by AddSC_trial_of_the_champion().