CMaNGOS_WoTLK: ulduar.cpp File Reference
ulduar.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
#include "Entities/Transports.h"
Data Structures
struct UlduarKeeperSpawns
Enumerations
enum {
SAY_PRE_LEVIATHAN_1 = -1603239 , SAY_PRE_LEVIATHAN_2 = -1603240 , SAY_PRE_LEVIATHAN_3 = -1603241 , SAY_FREYA_HELP = -1603009 ,
SAY_HODIR_HELP = -1603093 , SAY_THORIM_HELP = -1603155 , SAY_MIMIRON_HELP = -1603195 , SPELL_KEEPER_ACTIVE = 62647 ,
SPELL_CLEAR_INSANE = 63122
}
Functions
InstanceData * GetInstanceData_instance_ulduar (Map *pMap)
bool ProcessEventId_event_ulduar (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_instance_ulduar ()
Variables
static const DialogueEntry aUlduarDialogue []
static UlduarKeeperSpawns m_aKeepersSpawnLocs []
static UlduarKeeperSpawns m_aKeeperHelperLocs []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_PRE_LEVIATHAN_1
SAY_PRE_LEVIATHAN_2
SAY_PRE_LEVIATHAN_3
SAY_FREYA_HELP
SAY_HODIR_HELP
SAY_THORIM_HELP
SAY_MIMIRON_HELP
SPELL_KEEPER_ACTIVE
SPELL_CLEAR_INSANE
Definition at line 28 of file ulduar.cpp.
Function Documentation
AddSC_instance_ulduar()
void AddSC_instance_ulduar ()
Definition at line 1758 of file ulduar.cpp.
References Script::GetInstanceData, GetInstanceData_instance_ulduar(), Script::Name, Script::pProcessEventId, ProcessEventId_event_ulduar(), and Script::RegisterSelf().
Referenced by AddScripts().
GetInstanceData_instance_ulduar()
InstanceData* GetInstanceData_instance_ulduar (Map * pMap)
Definition at line 1714 of file ulduar.cpp.
Referenced by AddSC_instance_ulduar().
ProcessEventId_event_ulduar()
bool ProcessEventId_event_ulduar (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 1719 of file ulduar.cpp.
References EVENT_ID_SCRAP_REPAIR, EVENT_ID_SHUTDOWN, EVENT_ID_SPELL_SHATTER, Object::GetTypeId(), TYPE_ACHIEV_NERF_ENG, TYPE_ACHIEV_SHUTOUT, and TYPEID_UNIT.
Referenced by AddSC_instance_ulduar().
Variable Documentation
aUlduarDialogue
const DialogueEntry aUlduarDialogue[] static
Initial value:
=
{
    {SAY_PRE_LEVIATHAN_1,       NPC_BRONZEBEARD_RADIO,      7000},
    {SAY_PRE_LEVIATHAN_2,       NPC_BRONZEBEARD_RADIO,      5000},
    {SAY_PRE_LEVIATHAN_3,       NPC_BRONZEBEARD_RADIO,      2000},
    {NPC_LEVIATHAN,             0,                          0},
    {0, 0, 0}
}
Definition at line 43 of file ulduar.cpp.
m_aKeeperHelperLocs
UlduarKeeperSpawns m_aKeeperHelperLocs[] static
Initial value:
=
{
    {2036.873f,  25.42513f, 338.4984f, 3.909f, NPC_FREYA_HELPER,   TYPE_KEEPER_FREYA,   SAY_FREYA_HELP},
    {2036.658f, -73.58822f, 338.4985f, 2.460f, NPC_MIMIRON_HELPER, TYPE_KEEPER_MIMIRON, SAY_MIMIRON_HELP},
    {1939.045f, -90.87457f, 338.5426f, 0.994f, NPC_HODIR_HELPER,   TYPE_KEEPER_HODIR,   SAY_HODIR_HELP},
    {1939.148f,  42.49035f, 338.5427f, 5.235f, NPC_THORIM_HELPER,  TYPE_KEEPER_THORIM,  SAY_THORIM_HELP},
}
Definition at line 67 of file ulduar.cpp.
Referenced by instance_ulduar::OnPlayerEnter(), instance_ulduar::SetData(), and instance_ulduar::SpawnKeeperHelper().
m_aKeepersSpawnLocs
UlduarKeeperSpawns m_aKeepersSpawnLocs[] static
Initial value:
=
{
    {1945.682f, 33.34201f,  411.4408f, 5.270f, NPC_KEEPER_FREYA,   TYPE_FREYA,   0},
    {2028.766f, 17.42014f,  411.4446f, 3.857f, NPC_KEEPER_MIMIRON, TYPE_MIMIRON, 0},
    {1945.761f, -81.52171f, 411.4407f, 1.029f, NPC_KEEPER_HODIR,   TYPE_HODIR,   0},
    {2028.822f, -65.73573f, 411.4426f, 2.460f, NPC_KEEPER_THORIM,  TYPE_THORIM,  0},
}
Definition at line 59 of file ulduar.cpp.
Referenced by instance_ulduar::OnPlayerEnter(), and instance_ulduar::SpawnFriendlyKeeper().