CMaNGOS_WoTLK: ulduarScripts.cpp File Reference
ulduarScripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "ulduar.h"
Data Structures
struct npc_storm_tempered_keeperAI
struct npc_charged_sphereAI
Enumerations
enum TeleporterSpells {
SPELL_TELE_LIGHTS_HAMMER = 70781 , SPELL_TELE_ORATORY_DAMNED = 70856 , SPELL_TELE_RAMPART_OF_SKULLS = 70857 , SPELL_TELE_DEATHBRINGERS_RISE = 70858 ,
SPELL_TELE_UPPER_SPIRE = 70859 , SPELL_TELE_FROZEN_THRONE = 70860 , SPELL_TELE_SINDRAGOSAS_LAIR = 70861 , SPELL_TELE_EXPEDITION_BASE_CAMP = 64014 ,
SPELL_TELE_FORMATION_GROUNDS = 64032 , SPELL_TELE_COLOSSAL_FORGE = 64028 , SPELL_TELE_SCRAPYARD = 64031 , SPELL_TELE_ANTECHAMBER_OF_ULDUAR = 64030 ,
SPELL_TELE_SHATTERED_WALKWAY = 64029 , SPELL_TELE_CONSERVATORY_OF_LIFE = 64024 , SPELL_TELE_SPARK_OF_IMAGINATION = 65061 , SPELL_TELE_PRISON_OF_YOGG = 65042
}
enum TeleporterGossipItems {
GOSSIP_ITEM_TELE_LIGHTS_HAMMER = -3631000 , GOSSIP_ITEM_TELE_ORATORY_DAMNED = -3631001 , GOSSIP_ITEM_TELE_RAMPART_OF_SKULLS = -3631002 , GOSSIP_ITEM_TELE_DEATHBRINGERS_RISE = -3631003 ,
GOSSIP_ITEM_TELE_UPPER_SPIRE = -3631004 , GOSSIP_ITEM_TELE_SINDRAGOSAS_LAIR = -3631005 , GOSSIP_ITEM_TELE_BASE_CAMP = -3603000 , GOSSIP_ITEM_TELE_FORMATION_GROUNDS = -3603001 ,
GOSSIP_ITEM_TELE_COLOSSAL_FORGE = -3603002 , GOSSIP_ITEM_TELE_SCRAPYARD = -3603003 , GOSSIP_ITEM_TELE_ANTECHAMBER = -3603004 , GOSSIP_ITEM_TELE_WALKWAY = -3603005 ,
GOSSIP_ITEM_TELE_CONSERVATORY = -3603006 , GOSSIP_ITEM_TELE_SPARK_IMAGINATION = -3603007 , GOSSIP_ITEM_TELE_YOGG_SARON = -3603008
}
enum { GOSSIP_ITEM_BEGIN_ASSAULT = -3603012 , GOSSIP_TEXT_ID_BRANN = 14369 }
enum {
GOSSIP_ITEM_ACTIVATE_SYSTEMS = -3603010 , GOSSIP_ITEM_CONFIRMED = -3603011 , GOSSIP_TEXT_ID_GREET = 14375 , GOSSIP_TEXT_ID_DEFENSES = 14496 ,
GOSSIP_TEXT_ID_ACTIVATED = 14497
}
enum {
SPELL_FORKED_LIGHTNING = 63541 , SPELL_SEPARATION_ANXIETY = 63539 , SPELL_VENGEFUL_SURGE = 63630 , SPELL_SUMMON_CHARGED_SPHERE = 63527 ,
SPELL_CHARGED_SPERE = 63537 , SPELL_SUPERCHARGED = 63528 , NPC_TEMPERED_KEEPER_1 = 33699 , NPC_TEMPERED_KEEPER_2 = 33722 ,
NPC_CHARGED_SPHERE = 33715 , MAX_KEEPER_DISTANCE = 70
}
enum {
SAY_KEEPER_ACTIVE = -1603012 , GOSSIP_ITEM_LEND_AID = -3603013 , GOSSIP_ITEM_KEEPER_CONFIRM = -3603014 , GOSSIP_TEXT_ID_HODIR = 14326 ,
GOSSIP_TEXT_ID_FREYA = 14332 , GOSSIP_TEXT_ID_THORIM = 14333 , GOSSIP_TEXT_ID_MIMIRON = 14334 , GOSSIP_TEXT_ID_KEEPER_CONFIRM = 14325 ,
GOSSIP_TEXT_ID_YOGG_DEFEATED = 384
}
Functions
bool GossipHello_go_ulduar_teleporter (Player *pPlayer, GameObject *pGo)
bool GossipSelect_go_ulduar_teleporter (Player *pPlayer, GameObject *pGo, uint32 uiSender, uint32 uiAction)
bool GossipHello_npc_brann_ulduar (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_brann_ulduar (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GossipHello_npc_keeper_norgannon (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_keeper_norgannon (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool ProcessEventId_event_go_ulduar_tower (uint32 uiEventId, Object *pSource, Object *, bool)
UnitAI * GetAI_npc_storm_tempered_keeper (Creature *pCreature)
UnitAI * GetAI_npc_charged_sphere (Creature *pCreature)
bool GossipHello_npc_ulduar_keeper (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_ulduar_keeper (Player *pPlayer, Creature *pCreature, uint32, uint32 uiAction)
bool GOUse_go_activate_tram (Player *pPlayer, GameObject *pGo)
void AddSC_ulduar ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_BEGIN_ASSAULT
GOSSIP_TEXT_ID_BRANN
Definition at line 193 of file ulduarScripts.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_ITEM_ACTIVATE_SYSTEMS
GOSSIP_ITEM_CONFIRMED
GOSSIP_TEXT_ID_GREET
GOSSIP_TEXT_ID_DEFENSES
GOSSIP_TEXT_ID_ACTIVATED
Definition at line 238 of file ulduarScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FORKED_LIGHTNING
SPELL_SEPARATION_ANXIETY
SPELL_VENGEFUL_SURGE
SPELL_SUMMON_CHARGED_SPHERE
SPELL_CHARGED_SPERE
SPELL_SUPERCHARGED
NPC_TEMPERED_KEEPER_1
NPC_TEMPERED_KEEPER_2
NPC_CHARGED_SPHERE
MAX_KEEPER_DISTANCE
Definition at line 343 of file ulduarScripts.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_KEEPER_ACTIVE
GOSSIP_ITEM_LEND_AID
GOSSIP_ITEM_KEEPER_CONFIRM
GOSSIP_TEXT_ID_HODIR
GOSSIP_TEXT_ID_FREYA
GOSSIP_TEXT_ID_THORIM
GOSSIP_TEXT_ID_MIMIRON
GOSSIP_TEXT_ID_KEEPER_CONFIRM
GOSSIP_TEXT_ID_YOGG_DEFEATED
Definition at line 508 of file ulduarScripts.cpp.
TeleporterGossipItems
enum TeleporterGossipItems
Enumerator
GOSSIP_ITEM_TELE_LIGHTS_HAMMER
GOSSIP_ITEM_TELE_ORATORY_DAMNED
GOSSIP_ITEM_TELE_RAMPART_OF_SKULLS
GOSSIP_ITEM_TELE_DEATHBRINGERS_RISE
GOSSIP_ITEM_TELE_UPPER_SPIRE
GOSSIP_ITEM_TELE_SINDRAGOSAS_LAIR
GOSSIP_ITEM_TELE_BASE_CAMP
GOSSIP_ITEM_TELE_FORMATION_GROUNDS
GOSSIP_ITEM_TELE_COLOSSAL_FORGE
GOSSIP_ITEM_TELE_SCRAPYARD
GOSSIP_ITEM_TELE_ANTECHAMBER
GOSSIP_ITEM_TELE_WALKWAY
GOSSIP_ITEM_TELE_CONSERVATORY
GOSSIP_ITEM_TELE_SPARK_IMAGINATION
GOSSIP_ITEM_TELE_YOGG_SARON
Definition at line 63 of file ulduarScripts.cpp.
TeleporterSpells
enum TeleporterSpells
Enumerator
SPELL_TELE_LIGHTS_HAMMER
SPELL_TELE_ORATORY_DAMNED
SPELL_TELE_RAMPART_OF_SKULLS
SPELL_TELE_DEATHBRINGERS_RISE
SPELL_TELE_UPPER_SPIRE
SPELL_TELE_FROZEN_THRONE
SPELL_TELE_SINDRAGOSAS_LAIR
SPELL_TELE_EXPEDITION_BASE_CAMP
SPELL_TELE_FORMATION_GROUNDS
SPELL_TELE_COLOSSAL_FORGE
SPELL_TELE_SCRAPYARD
SPELL_TELE_ANTECHAMBER_OF_ULDUAR
SPELL_TELE_SHATTERED_WALKWAY
SPELL_TELE_CONSERVATORY_OF_LIFE
SPELL_TELE_SPARK_OF_IMAGINATION
SPELL_TELE_PRISON_OF_YOGG
Definition at line 49 of file ulduarScripts.cpp.
Function Documentation
AddSC_ulduar()
void AddSC_ulduar ()
Definition at line 612 of file ulduarScripts.cpp.
References Script::GetAI, GetAI_npc_charged_sphere(), GetAI_npc_storm_tempered_keeper(), GossipHello_go_ulduar_teleporter(), GossipHello_npc_brann_ulduar(), GossipHello_npc_keeper_norgannon(), GossipHello_npc_ulduar_keeper(), GossipSelect_go_ulduar_teleporter(), GossipSelect_npc_brann_ulduar(), GossipSelect_npc_keeper_norgannon(), GossipSelect_npc_ulduar_keeper(), GOUse_go_activate_tram(), Script::Name, Script::pGossipHello, Script::pGossipHelloGO, Script::pGossipSelect, Script::pGossipSelectGO, Script::pGOUse, Script::pProcessEventId, ProcessEventId_event_go_ulduar_tower(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_charged_sphere()
UnitAI* GetAI_npc_charged_sphere (Creature * pCreature)
Definition at line 499 of file ulduarScripts.cpp.
Referenced by AddSC_ulduar().
GetAI_npc_storm_tempered_keeper()
UnitAI* GetAI_npc_storm_tempered_keeper (Creature * pCreature)
Definition at line 455 of file ulduarScripts.cpp.
Referenced by AddSC_ulduar().
GossipHello_go_ulduar_teleporter()
bool GossipHello_go_ulduar_teleporter (Player * pPlayer, GameObject * pGo)
Definition at line 76 of file ulduarScripts.cpp.
References DONE, instance_ulduar::GetData(), GameObject::GetGOInfo(), GameObjectInfo::GetGossipMenuId(), Player::GetGossipTextId(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_TELE_ANTECHAMBER, GOSSIP_ITEM_TELE_BASE_CAMP, GOSSIP_ITEM_TELE_COLOSSAL_FORGE, GOSSIP_ITEM_TELE_CONSERVATORY, GOSSIP_ITEM_TELE_FORMATION_GROUNDS, GOSSIP_ITEM_TELE_SCRAPYARD, GOSSIP_ITEM_TELE_SPARK_IMAGINATION, GOSSIP_ITEM_TELE_WALKWAY, GOSSIP_ITEM_TELE_YOGG_SARON, GOSSIP_SENDER_MAIN, Player::IsGameMaster(), NOT_STARTED, TYPE_AURIAYA, TYPE_KOLOGARN, TYPE_LEVIATHAN, TYPE_MIMIRON, TYPE_VEZAX, and TYPE_XT002.
Referenced by AddSC_ulduar().
GossipHello_npc_brann_ulduar()
bool GossipHello_npc_brann_ulduar (Player * pPlayer, Creature * pCreature)
Definition at line 199 of file ulduarScripts.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_BEGIN_ASSAULT, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_BRANN, NOT_STARTED, TYPE_LEVIATHAN, and TYPE_LEVIATHAN_GAUNTLET.
Referenced by AddSC_ulduar().
GossipHello_npc_keeper_norgannon()
bool GossipHello_npc_keeper_norgannon (Player * pPlayer, Creature * pCreature)
Definition at line 248 of file ulduarScripts.cpp.
References WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_ACTIVATE_SYSTEMS, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_GREET, NOT_STARTED, TYPE_LEVIATHAN, TYPE_LEVIATHAN_GAUNTLET, TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, and TYPE_TOWER_THORIM.
Referenced by AddSC_ulduar().
GossipHello_npc_ulduar_keeper()
bool GossipHello_npc_ulduar_keeper (Player * pPlayer, Creature * pCreature)
Definition at line 523 of file ulduarScripts.cpp.
References DONE, Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_LEND_AID, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_FREYA, GOSSIP_TEXT_ID_HODIR, GOSSIP_TEXT_ID_MIMIRON, GOSSIP_TEXT_ID_THORIM, GOSSIP_TEXT_ID_YOGG_DEFEATED, NPC_KEEPER_FREYA, NPC_KEEPER_HODIR, NPC_KEEPER_MIMIRON, NPC_KEEPER_THORIM, TYPE_KEEPER_FREYA, TYPE_KEEPER_HODIR, TYPE_KEEPER_MIMIRON, TYPE_KEEPER_THORIM, and TYPE_YOGGSARON.
Referenced by AddSC_ulduar().
GossipSelect_go_ulduar_teleporter()
bool GossipSelect_go_ulduar_teleporter (Player * pPlayer, GameObject * pGo, uint32 uiSender, uint32 uiAction)
Definition at line 122 of file ulduarScripts.cpp.
References GameObject::CastSpell(), WorldObject::GetInstanceData(), GOSSIP_ACTION_INFO_DEF, Unit::IsInCombat(), SPELL_TELE_ANTECHAMBER_OF_ULDUAR, SPELL_TELE_COLOSSAL_FORGE, SPELL_TELE_CONSERVATORY_OF_LIFE, SPELL_TELE_EXPEDITION_BASE_CAMP, SPELL_TELE_FORMATION_GROUNDS, SPELL_TELE_PRISON_OF_YOGG, SPELL_TELE_SCRAPYARD, SPELL_TELE_SHATTERED_WALKWAY, SPELL_TELE_SPARK_OF_IMAGINATION, and TRIGGERED_OLD_TRIGGERED.
Referenced by AddSC_ulduar().
GossipSelect_npc_brann_ulduar()
bool GossipSelect_npc_brann_ulduar (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 211 of file ulduarScripts.cpp.
References FAIL, WorldObject::GetInstanceData(), Unit::GetMotionMaster(), GOSSIP_ACTION_INFO_DEF, IN_PROGRESS, MotionMaster::MoveWaypoint(), TYPE_LEVIATHAN_GAUNTLET, TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, and TYPE_TOWER_THORIM.
Referenced by AddSC_ulduar().
GossipSelect_npc_keeper_norgannon()
bool GossipSelect_npc_keeper_norgannon (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 261 of file ulduarScripts.cpp.
References DONE, Creature::ForcedDespawn(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_CONFIRMED, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_ACTIVATED, GOSSIP_TEXT_ID_DEFENSES, IN_PROGRESS, NPC_BRANN_BRONZEBEARD, NPC_EXPLORER_DELLORAH, TYPE_LEVIATHAN_GAUNTLET, TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, and TYPE_TOWER_THORIM.
Referenced by AddSC_ulduar().
GossipSelect_npc_ulduar_keeper()
bool GossipSelect_npc_ulduar_keeper (Player * pPlayer, Creature * pCreature, uint32 , uint32 uiAction)
Definition at line 563 of file ulduarScripts.cpp.
References DONE, DoScriptText(), Object::GetEntry(), WorldObject::GetInstanceData(), Object::GetObjectGuid(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ICON_CHAT, GOSSIP_ITEM_KEEPER_CONFIRM, GOSSIP_SENDER_MAIN, GOSSIP_TEXT_ID_KEEPER_CONFIRM, NPC_KEEPER_FREYA, NPC_KEEPER_HODIR, NPC_KEEPER_MIMIRON, NPC_KEEPER_THORIM, SAY_KEEPER_ACTIVE, TYPE_KEEPER_FREYA, TYPE_KEEPER_HODIR, TYPE_KEEPER_MIMIRON, and TYPE_KEEPER_THORIM.
Referenced by AddSC_ulduar().
GOUse_go_activate_tram()
bool GOUse_go_activate_tram (Player * pPlayer, GameObject * pGo)
Definition at line 595 of file ulduarScripts.cpp.
References WorldObject::GetInstanceData(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_STATE_ACTIVE, GO_STATE_READY, GO_TRAM, and instance_ulduar::SetTramRotateTimer().
Referenced by AddSC_ulduar().
ProcessEventId_event_go_ulduar_tower()
bool ProcessEventId_event_go_ulduar_tower (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 299 of file ulduarScripts.cpp.
References EVENT_ID_TOWER_FLAME, EVENT_ID_TOWER_FROST, EVENT_ID_TOWER_LIFE, EVENT_ID_TOWER_STORMS, FAIL, GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING, GetCreatureListWithEntryInGrid(), Object::GetTypeId(), NPC_GENERATOR_SMALL, instance_ulduar::SetData(), TYPE_TOWER_FREYA, TYPE_TOWER_HODIR, TYPE_TOWER_MIMIRON, TYPE_TOWER_THORIM, and TYPEID_GAMEOBJECT.
Referenced by AddSC_ulduar().