CMaNGOS_WoTLK: undercity.cpp File Reference
undercity.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/TimerAI.h"
Data Structures
struct npc_lady_sylvanas_windrunnerAI
Enumerations
enum {
EMOTE_LAMENT_START = -1000193 , SAY_LAMENT_END = -1000196 , EMOTE_LAMENT_END = -1000197 , SAY_AMBASSADOR = -1001277 ,
SPELL_HIGHBORNE_AURA = 37090 , SPELL_SYLVANAS_CAST = 36568 , SPELL_RIBBON_OF_SOULS = 37099 , NPC_AMBASSADOR = 16287 ,
NPC_HIGHBORNE_LAMENTER = 21628 , NPC_HIGHBORNE_BUNNY = 21641 , QUEST_ID_JOURNEY_UNDERCITY = 9180 , MAX_LAMENTERS = 4
}
enum SylvanasActions {
SYLV_AMBASSADOR_WHISPER , SYLV_SUMMON_HIGHBORNE , SYLV_HIGHBORNE_BUNNY , SYLV_LAMENT_END ,
SYLV_KNEEL , SYLV_STAND
}
Functions
UnitAI * GetAI_npc_lady_sylvanas_windrunner (Creature *pCreature)
bool QuestRewarded_npc_lady_sylvanas_windrunner (Player *pPlayer, Creature *pCreature, Quest const *pQuest)
void AddSC_undercity ()
Variables
static const float aHighborneLoc [MAX_LAMENTERS][5]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EMOTE_LAMENT_START
SAY_LAMENT_END
EMOTE_LAMENT_END
SAY_AMBASSADOR
SPELL_HIGHBORNE_AURA
SPELL_SYLVANAS_CAST
SPELL_RIBBON_OF_SOULS
NPC_AMBASSADOR
NPC_HIGHBORNE_LAMENTER
NPC_HIGHBORNE_BUNNY
QUEST_ID_JOURNEY_UNDERCITY
MAX_LAMENTERS
Definition at line 35 of file undercity.cpp.
SylvanasActions
enum SylvanasActions
Enumerator
SYLV_AMBASSADOR_WHISPER
SYLV_SUMMON_HIGHBORNE
SYLV_HIGHBORNE_BUNNY
SYLV_LAMENT_END
SYLV_KNEEL
SYLV_STAND
Definition at line 63 of file undercity.cpp.
Function Documentation
AddSC_undercity()
void AddSC_undercity ()
Definition at line 175 of file undercity.cpp.
References Script::GetAI, GetAI_npc_lady_sylvanas_windrunner(), Script::Name, Script::pQuestRewardedNPC, QuestRewarded_npc_lady_sylvanas_windrunner(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_lady_sylvanas_windrunner()
UnitAI* GetAI_npc_lady_sylvanas_windrunner (Creature * pCreature)
Definition at line 159 of file undercity.cpp.
Referenced by AddSC_undercity().
QuestRewarded_npc_lady_sylvanas_windrunner()
bool QuestRewarded_npc_lady_sylvanas_windrunner (Player * pPlayer, Creature * pCreature, Quest const * pQuest)
Definition at line 164 of file undercity.cpp.
References Creature::AI(), Object::GetObjectGuid(), Quest::GetQuestId(), and QUEST_ID_JOURNEY_UNDERCITY.
Referenced by AddSC_undercity().
Variable Documentation
aHighborneLoc
const float aHighborneLoc[MAX_LAMENTERS][5] static
Initial value:
=
{
    {1286.178f, 312.7989f, -61.15427f, 0.594699f, 1.0f},
    {1287.959f, 311.5340f, -61.26538f, 1.140551f, 2.0f},
    {1290.516f, 311.1839f, -61.20983f, 1.521469f, 3.0f},
    {1292.552f, 311.8947f, -61.07092f, 1.953438f, 4.0f},
}
Definition at line 55 of file undercity.cpp.
Referenced by npc_lady_sylvanas_windrunnerAI::npc_lady_sylvanas_windrunnerAI().