CMaNGOS_WoTLK: ungoro_crater.cpp File Reference
ungoro_crater.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/base/follower_ai.h"
Data Structures
struct npc_ame01AI
struct npc_ringoAI
struct npc_precious_the_devourerAI
struct npc_simone_seductressAI
struct npc_simone_the_inconspicuousAI
Macros
#define GOSSIP_ITEM "Show me your real face, demon."
Enumerations
enum {
SAY_AME_START = -1000446 , SAY_AME_PROGRESS = -1000447 , SAY_AME_END = -1000448 , SAY_AME_AGGRO1 = -1000449 ,
SAY_AME_AGGRO2 = -1000450 , SAY_AME_AGGRO3 = -1000451 , QUEST_CHASING_AME = 4245
}
enum {
SAY_RIN_START_1 = -1000416 , SAY_RIN_START_2 = -1000417 , SAY_FAINT_1 = -1000418 , SAY_FAINT_2 = -1000419 ,
SAY_FAINT_3 = -1000420 , SAY_FAINT_4 = -1000421 , SAY_WAKE_1 = -1000422 , SAY_WAKE_2 = -1000423 ,
SAY_WAKE_3 = -1000424 , SAY_WAKE_4 = -1000425 , SAY_RIN_END_1 = -1000426 , SAY_SPR_END_2 = -1000427 ,
SAY_RIN_END_3 = -1000428 , EMOTE_RIN_END_4 = -1000429 , EMOTE_RIN_END_5 = -1000430 , SAY_RIN_END_6 = -1000431 ,
SAY_SPR_END_7 = -1000432 , EMOTE_RIN_END_8 = -1000433 , SPELL_REVIVE_RINGO = 15591 , QUEST_A_LITTLE_HELP = 4491 ,
NPC_SPRAGGLE = 9997
}
enum {
SPELL_FOOLS_PLIGHT = 23504 , SPELL_CHAIN_LIGHTNING = 23206 , SPELL_TEMPTRESS_KISS = 23205 , SPELL_SILENCE = 23207 ,
EMOTE_SILENCE = -1001250 , NPC_SIMONE_THE_INCONSPICUOUS = 14527 , NPC_SIMONE_THE_SEDUCTRESS = 14533 , NPC_PRECIOUS = 14528 ,
NPC_PRECIOUS_THE_DEVOURER = 14538 , NPC_THE_CLEANER = 14503 , QUEST_STAVE_OF_THE_ANCIENTS = 7636
}
Functions
bool QuestAccept_npc_ame01 (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_ame01 (Creature *pCreature)
UnitAI * GetAI_npc_ringo (Creature *pCreature)
bool QuestAccept_npc_ringo (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_precious_the_devourer (Creature *pCreature)
UnitAI * GetAI_npc_simone_seductress (Creature *pCreature)
bool GossipHello_npc_simone_the_inconspicuous (Player *pPlayer, Creature *pCreature)
bool GossipSelect_npc_simone_the_inconspicuous (Player *pPlayer, Creature *pCreature, uint32, uint32)
UnitAI * GetAI_npc_simone_the_inconspicuous (Creature *pCreature)
void AddSC_ungoro_crater ()
Macro Definition Documentation
GOSSIP_ITEM
#define GOSSIP_ITEM "Show me your real face, demon."
Definition at line 357 of file ungoro_crater.cpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_AME_START
SAY_AME_PROGRESS
SAY_AME_END
SAY_AME_AGGRO1
SAY_AME_AGGRO2
SAY_AME_AGGRO3
QUEST_CHASING_AME
Definition at line 37 of file ungoro_crater.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_RIN_START_1
SAY_RIN_START_2
SAY_FAINT_1
SAY_FAINT_2
SAY_FAINT_3
SAY_FAINT_4
SAY_WAKE_1
SAY_WAKE_2
SAY_WAKE_3
SAY_WAKE_4
SAY_RIN_END_1
SAY_SPR_END_2
SAY_RIN_END_3
EMOTE_RIN_END_4
EMOTE_RIN_END_5
SAY_RIN_END_6
SAY_SPR_END_7
EMOTE_RIN_END_8
SPELL_REVIVE_RINGO
QUEST_A_LITTLE_HELP
NPC_SPRAGGLE
Definition at line 125 of file ungoro_crater.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_FOOLS_PLIGHT
SPELL_CHAIN_LIGHTNING
SPELL_TEMPTRESS_KISS
SPELL_SILENCE
EMOTE_SILENCE
NPC_SIMONE_THE_INCONSPICUOUS
NPC_SIMONE_THE_SEDUCTRESS
NPC_PRECIOUS
NPC_PRECIOUS_THE_DEVOURER
NPC_THE_CLEANER
QUEST_STAVE_OF_THE_ANCIENTS
Definition at line 339 of file ungoro_crater.cpp.
Function Documentation
AddSC_ungoro_crater()
void AddSC_ungoro_crater ()
Definition at line 807 of file ungoro_crater.cpp.
References Script::GetAI, GetAI_npc_ame01(), GetAI_npc_precious_the_devourer(), GetAI_npc_ringo(), GetAI_npc_simone_seductress(), GetAI_npc_simone_the_inconspicuous(), GossipHello_npc_simone_the_inconspicuous(), GossipSelect_npc_simone_the_inconspicuous(), Script::Name, Script::pGossipHello, Script::pGossipSelect, Script::pQuestAcceptNPC, QuestAccept_npc_ame01(), QuestAccept_npc_ringo(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_ame01()
UnitAI* GetAI_npc_ame01 (Creature * pCreature)
Definition at line 116 of file ungoro_crater.cpp.
Referenced by AddSC_ungoro_crater().
GetAI_npc_precious_the_devourer()
UnitAI* GetAI_npc_precious_the_devourer (Creature * pCreature)
Definition at line 423 of file ungoro_crater.cpp.
Referenced by AddSC_ungoro_crater().
GetAI_npc_ringo()
UnitAI* GetAI_npc_ringo (Creature * pCreature)
Definition at line 320 of file ungoro_crater.cpp.
Referenced by AddSC_ungoro_crater().
GetAI_npc_simone_seductress()
UnitAI* GetAI_npc_simone_seductress (Creature * pCreature)
Definition at line 654 of file ungoro_crater.cpp.
Referenced by AddSC_ungoro_crater().
GetAI_npc_simone_the_inconspicuous()
UnitAI* GetAI_npc_simone_the_inconspicuous (Creature * pCreature)
Definition at line 802 of file ungoro_crater.cpp.
Referenced by AddSC_ungoro_crater().
GossipHello_npc_simone_the_inconspicuous()
bool GossipHello_npc_simone_the_inconspicuous (Player * pPlayer, Creature * pCreature)
Definition at line 785 of file ungoro_crater.cpp.
References Player::GetGossipTextId(), Object::GetObjectGuid(), Player::GetQuestStatus(), GOSSIP_ACTION_INFO_DEF, GOSSIP_ITEM, GOSSIP_SENDER_MAIN, QUEST_STATUS_INCOMPLETE, and QUEST_STAVE_OF_THE_ANCIENTS.
Referenced by AddSC_ungoro_crater().
GossipSelect_npc_simone_the_inconspicuous()
bool GossipSelect_npc_simone_the_inconspicuous (Player * pPlayer, Creature * pCreature, uint32 , uint32)
Definition at line 794 of file ungoro_crater.cpp.
References Creature::AI(), EMOTE_ONESHOT_LAUGH, Object::GetObjectGuid(), and Unit::HandleEmote().
Referenced by AddSC_ungoro_crater().
QuestAccept_npc_ame01()
bool QuestAccept_npc_ame01 (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 97 of file ungoro_crater.cpp.
References Creature::AI(), ALLIANCE, FACTION_ESCORT_A_PASSIVE, FACTION_ESCORT_H_PASSIVE, Quest::GetQuestId(), Player::GetTeam(), HORDE, QUEST_CHASING_AME, Creature::SetFactionTemporary(), Unit::SetStandState(), TEMPFACTION_RESTORE_RESPAWN, TEMPFACTION_TOGGLE_IMMUNE_TO_NPC, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_ungoro_crater().
QuestAccept_npc_ringo()
bool QuestAccept_npc_ringo (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 325 of file ungoro_crater.cpp.
References Creature::AI(), FACTION_ESCORT_N_FRIEND_PASSIVE, Quest::GetQuestId(), QUEST_A_LITTLE_HELP, Unit::SetStandState(), and UNIT_STAND_STATE_STAND.
Referenced by AddSC_ungoro_crater().