CMaNGOS_WoTLK: Unit.cpp File Reference
Unit.cpp File Reference
#include "Entities/Unit.h"
#include "Log.h"
#include "Server/Opcodes.h"
#include "Server/WorldPacket.h"
#include "Server/WorldSession.h"
#include "World/World.h"
#include "Globals/ObjectMgr.h"
#include "Entities/ObjectGuid.h"
#include "Spells/SpellMgr.h"
#include "Entities/Player.h"
#include "Entities/Creature.h"
#include "Spells/Spell.h"
#include "Groups/Group.h"
#include "Spells/SpellAuras.h"
#include "Globals/ObjectAccessor.h"
#include "AI/CreatureAISelector.h"
#include "Entities/TemporarySpawn.h"
#include "Entities/Pet.h"
#include "Util/Util.h"
#include "Entities/Totem.h"
#include "Entities/Vehicle.h"
#include "BattleGround/BattleGround.h"
#include "Maps/InstanceData.h"
#include "OutdoorPvP/OutdoorPvP.h"
#include "Maps/GridDefines.h"
#include "Grids/GridNotifiersImpl.h"
#include "Grids/CellImpl.h"
#include "Maps/MapPersistentStateMgr.h"
#include "MotionGenerators/MovementGenerator.h"
#include "Movement/MoveSplineInit.h"
#include "Movement/MoveSpline.h"
#include "Entities/CreatureLinkingMgr.h"
#include "Tools/Formulas.h"
#include "Entities/Transports.h"
#include "Anticheat/Anticheat.hpp"
#include <math.h>
#include <limits>
#include <array>
Data Structures
struct PetOwnerKilledUnitHelper
struct CombatStopWithPetsHelper
struct SetSpeedRateHelper
struct SetPhaseMaskHelper
struct SetImmuneToNPCHelper
struct SetImmuneToPlayerHelper
struct SetPvPHelper
struct SetPvPFreeForAllHelper
struct SetPvPSanctuaryHelper
struct StopAttackFactionHelper
class UnitVisitObjectsInRangeNotifyEvent
Typedefs
typedef std::array< uint32, NUM_SPELL_PARTIAL_RESISTS > SpellPartialResistChanceEntry
typedef std::vector< SpellPartialResistChanceEntry > SpellPartialResistDistribution
Enumerations
enum SwingErrors { SWING_ERROR_NOT_IN_RANGE , SWING_ERROR_TARGET_NOT_ALIVE , SWING_ERROR_BAD_FACING , SWING_ERROR_CANT_ATTACK_TARGET }
Functions
static SpellPartialResistDistribution InitSpellPartialResistDistribution ()
Variables
float baseMoveSpeed [MAX_MOVE_TYPE]
static const SpellPartialResistDistribution SPELL_PARTIAL_RESIST_DISTRIBUTION = InitSpellPartialResistDistribution()
static const float AVOIDANCE_DIMINISHING_COEFFICIENT [MAX_CLASSES]
static const float AVOIDANCE_DIMINISHING_DODGE_CAP [MAX_CLASSES]
const float AVOIDANCE_DIMINISHING_PARRY_CAP [MAX_CLASSES]
const float AVOIDANCE_DIMINISHING_MISS_CAP [MAX_CLASSES]
Typedef Documentation
SpellPartialResistChanceEntry
typedef std::array<uint32, NUM_SPELL_PARTIAL_RESISTS> SpellPartialResistChanceEntry
Definition at line 76 of file Unit.cpp.
SpellPartialResistDistribution
typedef std::vector<SpellPartialResistChanceEntry> SpellPartialResistDistribution
Definition at line 77 of file Unit.cpp.
Enumeration Type Documentation
SwingErrors
enum SwingErrors
Enumerator
SWING_ERROR_NOT_IN_RANGE
SWING_ERROR_TARGET_NOT_ALIVE
SWING_ERROR_BAD_FACING
SWING_ERROR_CANT_ATTACK_TARGET
Definition at line 574 of file Unit.cpp.
Function Documentation
InitSpellPartialResistDistribution()
static SpellPartialResistDistribution InitSpellPartialResistDistribution () inline static
Definition at line 78 of file Unit.cpp.
References NUM_SPELL_PARTIAL_RESISTS, SPELL_PARTIAL_RESIST_NONE, SPELL_PARTIAL_RESIST_PCT_100, SPELL_PARTIAL_RESIST_PCT_20, and SPELL_PARTIAL_RESIST_PCT_80.
Variable Documentation
AVOIDANCE_DIMINISHING_COEFFICIENT
const float AVOIDANCE_DIMINISHING_COEFFICIENT[MAX_CLASSES] static
Initial value:
=
{
    0.0000f,
    0.9560f,
    0.9560f,
    0.9880f,
    0.9880f,
    0.9830f,
    0.9560f,
    0.9880f,
    0.9830f,
    0.9830f,
    0.0000f,
    0.9720f
}
Definition at line 3778 of file Unit.cpp.
Referenced by Unit::CalculateEffectiveDodgeChance(), Unit::CalculateEffectiveMissChance(), and Unit::CalculateEffectiveParryChance().
AVOIDANCE_DIMINISHING_DODGE_CAP
const float AVOIDANCE_DIMINISHING_DODGE_CAP[MAX_CLASSES] static
Initial value:
=
{
    0.000000f,
    88.129021f,
    88.129021f,
    145.560408f,
    145.560408f,
    150.375940f,
    88.129021f,
    145.560408f,
    150.375940f,
    150.375940f,
    0.000000f,
    116.890707f,
}
Definition at line 3794 of file Unit.cpp.
Referenced by Unit::CalculateEffectiveDodgeChance().
AVOIDANCE_DIMINISHING_MISS_CAP
const float AVOIDANCE_DIMINISHING_MISS_CAP[MAX_CLASSES]
Initial value:
=
{
    0.0f,
    16.0f,
    16.0f,
    0.0f,
    0.0f,
    0.0f,
    16.0f,
    0.0f,
    0.0f,
    0.0f,
    0.0f,
    0.0f,
}
Definition at line 4522 of file Unit.cpp.
Referenced by Unit::CalculateEffectiveMissChance().
AVOIDANCE_DIMINISHING_PARRY_CAP
const float AVOIDANCE_DIMINISHING_PARRY_CAP[MAX_CLASSES]
Initial value:
=
{
    0.000000f,
    47.003525f,
    47.003525f,
    145.560408f,
    145.560408f,
    0.000000f,
    47.003525f,
    145.560408f,
    0.000000f,
    0.000000f,
    0.000000f,
    0.000000f,
}
Definition at line 3863 of file Unit.cpp.
Referenced by Unit::CalculateEffectiveParryChance().
SPELL_PARTIAL_RESIST_DISTRIBUTION
const SpellPartialResistDistribution SPELL_PARTIAL_RESIST_DISTRIBUTION = InitSpellPartialResistDistribution() static
Definition at line 135 of file Unit.cpp.
Referenced by Unit::CalculateEffectiveMissChance(), Unit::CalculateSpellResistChance(), and Unit::RollMagicResistanceMultiplierOutcomeAgainst().